### ISSUE TITLE
I want to limit the blocks available in the widget area.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#33350]
I would like to limit the blocks available in the widget area to only the following two

- Group
- Legacy Widget

However, **I want to freely place blocks inside the Group block**.

What should I do in this case?

If there is currently no method to make this possible, I would like you to implement a way to make it happen.
Because the specification of the new widget feature will break the traditional theme. (Reference: #32723)

# What I have tried

I was able to get the first control by using the `'allowed_block_types_all'` hook.

```
add_filter( 'allowed_block_types_all', function ( $allowed_block_types, $block_editor_context ) {
    return ['core/legacy-widget', 'core/group' ];
}, 99, 2);
```

<img width="543" alt="スクリーンショット 2021-07-12 11 45 14" src="https://user-images.githubusercontent.com/31400297/125224127-f20ac380-e307-11eb-8c68-2402baea480c.png">

In this case, the inside of the group block is also restricted.

**Comment by talldan** [comment]
Yes, `allowed_block_types_all` filters all the blocks available in the editor, even in inner blocks.

From what I understand, what you're asking isn't possible. There would need to be a few different things:
- a way to limit the blocks available in the widget area block for the standalone widget editor
- a way to limit the blocks available in the root block list in the customize widget editor, but in a way that doesn't affect child blocks
- a way to define the blocks available in the group block

I realise this situation is not ideal. The widget grouping feature that you've been discussing is something that's being prioritised for after WordPress 5.8 (https://github.com/WordPress/gutenberg/issues/33242). It's not possible now to release further enhancements to 5.8, as there's now a feature freeze and the release is fairly imminent.

While those contributing to the new widget screens hope to get everything right for 5.8, that hasn't been the case for this particular issue. The classic widgets plugin is the best option if things are not working for you, but hopefully a solution to this problem will be in place for 5.9 and everything will be back on track for you.

**Comment by ddryo** [comment]
Thank you.
I'll turn it off until 5.9.
