### ISSUE TITLE
Extend the utility of pagination blocks

### ISSUE THREAD

**Issue by carlomanf** [WordPress/gutenberg#33357]
There are a number of different pagination template tags that exist, with different purposes.

[`previous_posts_link`](https://developer.wordpress.org/reference/functions/previous_posts_link/) and [`next_posts_link`](https://developer.wordpress.org/reference/functions/next_posts_link/) are designed to paginate queries that are `! is_singular()`. This is what the Query Pagination block currently does.

There are also [`previous_post_link`](https://developer.wordpress.org/reference/functions/previous_post_link/) and [`next_post_link`](https://developer.wordpress.org/reference/functions/next_post_link/), which are designed to paginate queries that are `is_singular()`. These currently have no block equivalent, as far as I'm aware.

Furthermore, there is [`wp_link_pages`](https://developer.wordpress.org/reference/functions/wp_link_pages/). This also paginates queries that are `is_singular()`, but does so in terms of intra-post pagination rather than inter-post pagination. The Page Break block is designed to work together with this template tag, but the template tag itself currently has no block equivalent, as far as I'm aware.

The easy solution is to add new blocks for these template tags, but it might be worth exploring the viability of simplifying them all into the Query Pagination block and automatically determine which kind of pagination to use in which context.

**Comment by ntsekouras** [comment]
>There are also previous_post_link and next_post_link, which are designed to paginate queries that are is_singular(). These currently have no block equivalent, as far as I'm aware.

Hey 👋 - there is `Post Navigation Link` which has block variations for `next and previous` post.

**Comment by carlomanf** [comment]
> > There are also previous_post_link and next_post_link, which are designed to paginate queries that are is_singular(). These currently have no block equivalent, as far as I'm aware.
> 
> Hey 👋 - there is `Post Navigation Link` which has block variations for `next and previous` post.

Thanks for your reply. I didn't see those ones because I was testing with core version 5.8 and had the plugin deactivated.

After looking more closely, I see there is also a Table of Contents block that possibly might act as an equivalent to `wp_link_pages`, but I can't tell for sure because the block is temporarily de-registered. Hoping someone familiar with that block can confirm.

**Comment by ntsekouras** [comment]
Table of contents blocks has some issues that need to be resolved first. Check this PR for more info: https://github.com/WordPress/gutenberg/pull/29718

**Comment by carlomanf** [comment]
Closing as duplicate of #29484
