### ISSUE TITLE
User Testing - Pasting Content with HTML

### ISSUE THREAD

**Issue by webtrainingwheels** [WordPress/gutenberg#3336]
## Issue Overview

I wanted to transfer some content from another post. It's text with some html for images and headings. I switched to HTML before pasting. After I pasted I got this very unclear and unfriendly message  - the average user will have no idea what this means or which each option will do: 
![gutenberg-paste-content](https://user-images.githubusercontent.com/1043076/32413927-4a3ee7bc-c213-11e7-9bb7-27bb1fe7f537.jpeg)

"Overwrite" appears to get rid of my content entirely. I didn't expect that (actually I have no idea what I expected from this option, but not that) .

Convert Classic Text - this is actually the default behaviour I expected, but calling it "classic text" made me worry my html is going to get removed. I was relieved when it converted to a normal block.

Edit as HTML Block - I don't really know why that's different than the behaviour of the classic text block. I tried this option and it took me a while to realize I could switch into Preview mode at the top of the screen
. 
On the right I saw this: 
![html-block](https://user-images.githubusercontent.com/1043076/32413964-2d57d414-c214-11e7-9e7f-f998d5f4eb11.jpeg)
"right here in the editor" and I kept thinking "WHERE???" so maybe a Preview button over there would be helpful? Otherwise that message seems out of context. 

But now I want to actually edit the content I pasted, maybe add another image or something, but I can't because there's no toolbar and I can't find a way to convert it to a "normal" block. 
Am I missing a way to convert this to a "classic text"/normal block, or is it really not possible?
If not, I have to re-do the process and this time choose "Classic Text"

**Comment by mtias** [comment]
@iseulde could you look at this one when you have a moment?

**Comment by iseulde** [comment]
I'm having a hard time following the steps you took to end up with the externally modified message. Did you paste the contents of your clipboard in HTML or visual mode? I'm not sure how to get it either way. Could you also share some example HTML?

**Comment by webtrainingwheels** [comment]
Quick screen recording: http://jmp.sh/oJ17Z4K
Here's the HTML I pasted: https://pastebin.com/XQYVwTt3

If I paste the HTML directly into the paragraph block, it's converted to blocks, but the size and alignment on the image are removed so the text is no longer wrapped (I'm not clear on if Gutenberg is supposed to currently be able to align images properly, so this may be "intended" by Gutenberg at the moment, but certainly not expected as a user):
http://jmp.sh/6Fs0GhE

**Comment by iseulde** [comment]
@webtrainingwheels As far as I see, this behaviour is currently what is supposed to happen. You modified one block directly, and there's a lot more than what the block itself can handle, so it gives you this message with the option to overwrite with what it can handle, put it in a classic block, or edit it again as HTML to something that it can handle.

What you probably want to do is directly paste the content in visual mode (not with "edit as HTML"), or open the code editor and paste it there. You're correct that we currently don't keep the alignment out of pasted content, which should be fixed.

**Comment by iseulde** [comment]
For the first issue, maybe we should add an extra (fourth) option to attempt to convert the content to blocks? That's a lot of options though, but it makes sense if there's a bunch of extra content. :)

**Comment by webtrainingwheels** [comment]
Thanks for your reply!
I think what I'm saying is that the messaging itself doesn't make any sense to a user  - it needs to be finessed because the options aren't clear at all (see my original post for comments on the messages.) There's no real indication as to why Gutenberg can't handle the content as-is, nor what the user needs to do to get the desired result. It's more of user experience issue than a technical issue.

About this: "we currently don't keep the alignment out of pasted content, which should be fixed."
Do you mean that it's currently a known issue and being worked on? Or should I open a separate issue about that behaviour?

**Comment by iseulde** [comment]
Yes, you're correct that the messaging could be improved, though I don't immediately know how. I'll see what I can do. For the alignment, I created https://github.com/WordPress/gutenberg/pull/3724. I'll also create another PR to handle images in a paragraph like your example content you shared here.

**Comment by mtias** [comment]
There are some improvements to this dialog already merged.
