### ISSUE TITLE
CardFooter lost its box-sizing CSS property

### ISSUE THREAD

**Issue by alshakero** [WordPress/gutenberg#33363]
This PR https://github.com/WordPress/gutenberg/pull/32566 seems to have created a bug in `CardFooter` component. You can see it [here](https://github.com/Automattic/wp-calypso/issues/54445). 

I think that before #32566, CardFooter had `box-sizing: border-box` and it was removed. 

Putting it back seems to fix the issue.

// cc @ciampo

**Comment by ciampo** [comment]
Thank you for the ping! I opened https://github.com/WordPress/gutenberg/pull/33511 with the fix
