### ISSUE TITLE
Docs: CLI options for `@wordpress/docgen` are not properly documented at Block Editor Handbook

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#33365]
## Description

CLI options of `@wordpress/docgen` are properly documented in the package' [`README.md`](https://github.com/WordPress/gutenberg/tree/trunk/packages/docgen) but the HTML automatically generated at https://developer.wordpress.org/block-editor/reference-guides/packages/packages-docgen/#cli-options is not properly generating the options for the commands

## Expected behavior

The CLI options at https://developer.wordpress.org/block-editor/reference-guides/packages/packages-docgen/#cli-options should appear with double dash `--` (as defined in the package) and not with single dash `-` (as is currently displayed)

**Comment by Thelmachido** [comment]
Hi @juanmaguitar As there hasn’t been any movement on this issue in two years, I’ve marked it as stale. Let me know if you think it should be kept open. Thanks!

**Comment by kathrynwp** [comment]
Pinging @WordPress/documentation in case someone would be able to help get these fixes made, if possible!

**Comment by ryanwelcher** [comment]
I think this is functionality that is missing in the docgen tool. I may be mistaken, but I believe that the docs are generated based on docblock tags. I can talke a look at this during the WCUS 2022 contributor day,

**Comment by ryanwelcher** [comment]
@juanmaguitar this seems like a feature request. I'm going to remove the docs-related labels but if I am mistaken, please let me know.

**Comment by juanmaguitar** [comment]
This had been fixed! 🎉
