### ISSUE TITLE
`theme.json` properties can't be overridden in PHP

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#33367]
## Description

`theme.json` properties cannot be (easily) overridden on the server-side due to the current implementation of filtering the block editor settings at a priority set to `PHP_INT_MAX`.

Being able to filter theme.json from PHP is a valuable way to ease the on-ramp to theme.json adoption; for example if a theme includes an existing settings panel for configuring colors and fonts, they may be able to use PHP to insert this configuration into the theme.json file until a global style editor is available to client users.

I would propose updating the filter to hook in at `999` which still conveys that the filter is _intended_ to be run late while still allowing developers the option to adjust without a more complex unhook/rehook dance.

**Comment by aristath** [comment]
As far as I know, `theme.json` is not intended to run late, it's intended to override PHP. 
The "old" method was using theme-supports which can be added at any time, anywhere. The theme.json file must override those theme-supports and therefore it must run last and not just late. I believe that's why it runs on `PHP_INT_MAX`...

**Comment by chrisvanpatten** [comment]
@aristath I understand conceptually why it’s running late, it just makes the upgrade path unnecessarily complex if you’re migrating from, for example, custom settings pages.

**Comment by justintadlock** [comment]
One other use case I have had in mind is add-on plugins (or even theme/child options).  I'm kind of imagining scenarios where I might build a settings page for configuring certain defaults that are not covered by the Global Styles system.  Being able to take custom plugin settings, hook in, and overrule `theme.json` values would be useful.

Is there even a hook that runs on both the front end and editor for this?  I think `block_editor_settings_all` is just on the admin side, right?

**Comment by aristath** [comment]
I believe there are plans to _filter_ theme.json values so it can be overridden, but this has not yet been implemented.

**Comment by overclokk** [comment]
Even if you filter the theme.json the result will be sanitized with the schema from the core, but if you only want to have a dynamic theme.json you can follow this issue #33524 where I linked a library for generating the theme.json from a PHP array.

**Comment by Soean** [comment]
I think we can close this issue:

PR: https://github.com/WordPress/gutenberg/pull/44015
Docs: https://developer.wordpress.org/block-editor/reference-guides/filters/global-styles-filters/
