### ISSUE TITLE
'Browse All' button in Social Icons Block in Widget Editor does not display social icons

### ISSUE THREAD

**Issue by circlecube** [WordPress/gutenberg#33372]
## Description
In the new widget editor screen when adding a social block, populating the list with the proper social media links displays a "browse all" button. When the button is clicked there is no list of social sites and the user is taken to the block inserter. Confusing because you can search for things like youtube and twitter etc, but these are the embeds and not the social links to place in the social media block. This will be an ideal place where users will want to use this feature and list social media links in sidebars and this drops them into a confusing and bad experience. 

## Step-by-step reproduction instructions
1. Go to widget editor.
2. Add a social icons block
3. Click "browse all" button in social icon inserter.
4. See block inserter with no social icons listed.

## Expected behavior
A user would expect to be able to browse all the social site icons that are available.

## Actual behavior
Currently users will be taken to the block inserter and have no way to browse all sites available. They will see blocks (some of which are social sites but embed blocks for these sites so if they attempt to add them will be adding additional blocks to the widget area rather than links to the social icons block.)

## Screenshots or screen recording (optional)
https://share.getcloudapp.com/Wnux5EJP

## WordPress information
- WordPress version: 5.8-RC2
- Gutenberg version: Same behavior with Gutenberg Not installed and latest (11.0.0)
- Are all plugins except Gutenberg deactivated? Only plugin is "WordPress Beta Tester"
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty-One

## Device information
- Device: MacBook Pro
- Operating system: Mac 10.15.7
- Browser: Chrome 91.0.4472.114 (latest)

**Comment by circlecube** [comment]
Similar to https://github.com/Automattic/wp-calypso/issues/46382 (though I can't reproduce that one anymore). 

This is specific to the widget editor. The widget editor, in my opinion, is a much more common use case for this social icons block than the post editor.

**Comment by noisysocks** [comment]
I was able to reproduce this. It's very late in the 5.8 release cycle but it's easy to fix this then let's do it because, as you say, Social Icons is a useful block in this context.

**Comment by noisysocks** [comment]
Any fix we make won't receive thorough testing ahead of the 5.8 final release so I think let's punt this to 5.8.1 but mark it as a priority by including it in https://github.com/WordPress/gutenberg/issues/33242.
