### ISSUE TITLE
Notice and Warning with Gutenberg 11.0.0

### ISSUE THREAD

**Issue by kafleg** [WordPress/gutenberg#33377]
## Description
There is a notice and warning with the latest version of Gutenberg. 

Notice:  Undefined index: styles in E:\laragon\www\reviews\wp-content\plugins\gutenberg\lib\global-styles.php on line 138

Warning:  Invalid argument supplied for foreach() in E:\laragon\www\reviews\wp-content\plugins\gutenberg\lib\global-styles.php on line 138

The latest version of the Gutenberg plugin is installed and activated. All the other plugins are deactivated. Also, activated the Twenty Twenty-One theme. 

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Go to Appearance > Customize 
2. You will see the notice but it will go out after the customizer will fully load.
3. Press ctrl+u and at the top, you will see them. 

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 11.0.0
- Are all plugins except Gutenberg deactivated? - Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? - Yes

## Device information
- Device: Desktop 
- Operating system: Windows 10
- Browser: Edge

**Comment by talldan** [comment]
Thanks for reporting. I didn't realise this happened in the customizer as well.

It should be fixed by https://github.com/WordPress/gutenberg/pull/33127 which will be part of Gutenberg 11.1.
