### ISSUE TITLE
Color Selection UX Is Confusing!

### ISSUE THREAD

**Issue by ahmadawais** [WordPress/gutenberg#3337]
The color selection user experience is confusing! I'm using the Gutenberg v1.6.1.
When I select a color — a major portion of it becomes white and it feels like I have selected white color instead of that one. 

GIF.

![image](http://on.ahmda.ws/nVYr/c)

The UX should be different. The selected color should retain itself and only there should be a border for focus or something! Anything but this!

**Comment by karmatosed** [comment]
There is already an improvement that resolves this: https://github.com/WordPress/gutenberg/pull/3054. It shows an indicator. As this has previously been reported going to close.

**Comment by ahmadawais** [comment]
@karmatosed Thanks for letting me know. I was unable to find that. Glad it's being worked on.
