### ISSUE TITLE
Top Bar Alignment Issue

### ISSUE THREAD

**Issue by ahmadawais** [WordPress/gutenberg#3338]
Using Gutenberg v1.6.1 the top bar gets misaligned when you close all the sidebars. I suppose this should be fixed? With something like max-width in the header container.

Take a look. 

![image](http://on.ahmda.ws/nVl8/c)

GIF.
![image](http://on.ahmda.ws/nUAA/c)

**Comment by mtias** [comment]
This is the intended behaviour, the toolbar is aligned to the left. There were some ideas about placing it in the center on large viewports.

Also see: https://github.com/WordPress/gutenberg/pull/3311

**Comment by ahmadawais** [comment]
@mtias Feel free to close this one. But I think center alignment is better suited. Full disclosure, I don't like the top bar — having it in every block was a better option. Having the top bar only when multiple blocks are selected could have been a better option.

**Comment by youknowriad** [comment]
@ahmadawais you might like this https://github.com/WordPress/gutenberg/pull/3311

I don't know if the toggle will be there forever, but we're still exploring possibilities

**Comment by mtias** [comment]
> Full disclosure, I don't like the top bar — having it in every block was a better option.

Me too, I like the proximity and think it is more intuitive. Given there is a strong split of preference here, we are going with a toggle so we can user test more broadly the two approaches. It might also end up being one of our few new "options" to add.

**Comment by ahmadawais** [comment]
^That is awesome. Thank you for letting me know. Having it as an option would make a lot of sense. It's a major decision and the UI with top bar looks weird to me after all this effort.
