### ISSUE TITLE
Update Block Inserter text label to indicate how to close

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#33397]
## Description

[If one uses the text icon only option](https://make.wordpress.org/core/2020/12/21/core-editor-improvement-text-only-icons-for-the-toolbar/), the block inserter icon turns into a notice that says "Add". However, if you open it, the "Add" prompt remains and doesn't update to say something like "Close". This makes it hard to know what exactly to do to close the block inserter. 

_Feel free to update the title of this. I struggled to make it descriptive enough!_

## Step-by-step reproduction instructions

1. Create a new post. 
2. Head to Options > Preferences and turn on showing text only icons. Close out. 
3. Click "Add" and notice the block inserter opens up. 
4. Notice that the "Add" prompt remains and doesn't change to say something contextual like "close". 

## Expected behaviour

Expect the prompt to say "Close" or something similar. 

## Actual behaviour

Prompt continues to say "Add". 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/125512750-0b255987-7069-41e3-9c5c-97278fea43b8.mov

## WordPress information
- WordPress version: 5.8 RC 3
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? No, WP Beta Tester plugin. 
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: MacOs
- Browser: Chrome 89

**Comment by getsource** [comment]
@annezazu Thank you! Here is a PR that modifies the label if the inserter is open:
https://github.com/WordPress/gutenberg/pull/33534
