### ISSUE TITLE
Mobile: Low Contrast Checker/Notice for Text-Based Blocks

### ISSUE THREAD

**Issue by SiobhyB** [WordPress/gutenberg#33396]
## Description

The option to add colours to text blocks was introduced to the apps in https://github.com/WordPress/gutenberg/pull/33250. 

A nice feature that accompanies this option on the web is the following notice when colours with a low contrast are being used together:

```
This colour combination may be hard for people to read. Try using a brighter background colour and/or a darker text colour.
```

The notice is a useful prompt for site owners that helps to promote accessibility and it could be nice to add to the apps.

## Step-by-step reproduction instructions

* Add a new text block (e.g. the paragraph block) to a new a post in the mobile app and type some text.
* Tap the block's cog/gear icon to edit its settings.
* Select a foreground and background colour that have a low contrast to one another (e.g. two really dark colours).
* Observe how the text is hard to read, but there is no notice like there is on the web.

## Screenshots or screen recording

The notice as it appears on the web:

<img width="697" alt="Screenshot 2021-07-13 at 19 55 45" src="https://user-images.githubusercontent.com/2998162/125509458-f12d69b1-165e-40ad-826f-fab8c65f7679.png">

**Comment by chipsnyder** [comment]
This is a great suggestion @SiobhyB!

**Comment by jd-alexander** [comment]
Good idea! The `help` prop could be leveraged to include this notice below the colors. 

<kbd><img src="https://user-images.githubusercontent.com/1509205/132387033-152c8617-af7b-4065-b60f-65f63d8c02e7.png" width="320"></kbd>

**Comment by SiobhyB** [comment]
Noting here that I'll be working on this week, for HACK week, with @iamthomasbishop. :) @iamthomasbishop, an initial question I have is whether you'd like to see this notice on both the colour picker's main sheet and sub sheet.

| Main Sheet | Sub Sheet |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/2998162/133073820-d9b8eee9-0304-4639-85f7-ee26dc0f2f4c.png" width="100%"> | <img src="https://user-images.githubusercontent.com/2998162/133073904-5e51ab6d-1791-464f-a034-9b80fa199cdb.png" width="100%"> |

My first thought is that it should appear in both places, but also wonder whether that may make the main sheet seem cluttered for some blocks. Interested to hear your thoughts!
