### ISSUE TITLE
Template Editor: Preview Does Not Recognize Changes to Template Without Updating

### ISSUE THREAD

**Issue by donalirl** [WordPress/gutenberg#33409]
## Description
When changing the template of a page, you cannot preview the new layout unless you also click Update to apply the change.

## Step-by-step reproduction instructions

Using Gutenberg 9.7+ and a FSE ready theme:

1. Visit the page editor.
2. Under Template, select a different page template.
3. Click Preview and notice that the preview does not show the page in the newly-selected template.
4. Exit the Preview and this time click Update to apply the newly-selected template.
5. Preview again, and notice the new template is shown.

## Expected behaviour
I expected Preview to show me the selected template even without Updating to save the change.

## Actual behaviour
The Preview did not show the selected template.

## Screenshots or screen recording (optional)
In this example,  my 'Portfolio' template contains a Navigation block in the header, but when I Preview, it is not shown until I click Update to apply the change:

https://user-images.githubusercontent.com/30727666/125544539-b11606a5-2454-4030-b6d7-00d0a5a126d8.mp4

**Comment by annezazu** [comment]
Thanks for flagging. This was previously reported and closed here for context: https://github.com/WordPress/gutenberg/issues/31567 in favor of this issue: https://github.com/WordPress/gutenberg/issues/17727 Closing this one out too!

**Comment by donalirl** [comment]
> Thanks for flagging. This was previously reported and closed here for context: #31567 in favor of this issue: #17727 Closing this one out too!

Thank you! I promise I did search for existing issues before reporting 😅 I think I had the wrong labels...

**Comment by annezazu** [comment]
Oh no worries at all :D This happens to me all the time.
