### ISSUE TITLE
Documentation: Remove withSelect HOC references in favor of useSelect

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#33411]
Recently, the docs have been updated to use the `useState` hook instead of the `withState` HOC, because the later has been deprecated:

https://github.com/WordPress/gutenberg/pull/33173

Even if it's not deprecated (as far as I know), I would like to see references to the `withSelect` HOC removed from the docs in favor of the simpler `useSelect` hook to encourage devs to use more modern React ways.

For example, here:

https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/creating-dynamic-blocks/

**Comment by Mamaduka** [comment]
The list of files that contain `withSelect` reference in examples:

```
docs/how-to-guides/block-tutorial/creating-dynamic-blocks.md
docs/how-to-guides/format-api/2-toolbar-button.md
docs/how-to-guides/sidebar-tutorial/plugin-sidebar-5-update-meta.md
docs/how-to-guides/sidebar-tutorial/plugin-sidebar-6-finishing-touches.md
docs/how-to-guides/sidebar-tutorial/plugin-sidebar-4-initialize-input.md
packages/core-data/README.md
```

...and `grep` command just in case I missed something:

```bash
grep --include=\*.md --exclude-dir=node_modules -rwl -e "withSelect(" .
```

**Comment by Patil2099** [comment]
I would love to take this up
