### ISSUE TITLE
Inconsistent Markdown rendering of unordered lists 

### ISSUE THREAD

**Issue by uxcitizen** [WordPress/gutenberg#3341]
## Issue Overview

I am trying to use Markdown to create an unordered list within a paragraph. Sometimes the Markdown renders and sometimes it doesn't.

## Steps to Reproduce (for bugs)

1. I create a new paragraph block OR hit enter to type
2. I type a hyphen and a space `- ` to create a list item in Markdown
3. Sometimes the Markdown renders it into a bullet point and sometimes it does not. See this gif

https://cloudup.com/cB-mrx_P1Ul
 

I am using
Firefox 56.0.2
WordPress 4.8.3
Local by Flywheel
No other plugins

## Expected Behavior

I would expect the Markdown to render in the editor, consistently, OR that it would render on save, the way it does in Calypso if I have Markdown enabled.

## Current Behavior

Sometimes bullet points render in Markdown and sometimes they do not.

## Possible Solution

?

## Related Issues and/or PRs

#1843

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mtias** [comment]
@androb @ephox-mogran could you look at this when you get a chance?

**Comment by EphoxJames** [comment]
@uxcitizen can you still replicate this in Wordpress 4.9? What do you mean when you type "the list took a long time to type"? There doesn't seem to be any obvious delay in the animation.

I couldn't replicate what you showed in the gif using Wordpress 4.9 on Firefox 57 and Chrome 62 (both on linux mint). I was not using "local" as I couldn't find a plugin by that name.

**Comment by uxcitizen** [comment]
I was not able to reproduce it in 4.9, Firefox 57. Feel free to close for now - If I am able to replicate again I will let you know.

(Local is [Local by Flywheel](https://local.getflywheel.com/), a local WordPress install tool)
