### ISSUE TITLE
Core Data uses hardcoded `baseURL` prefix for taxonomies and post types 

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#33420]
## Description

`loadTaxonomyEntities` and `loadPostTypeEntities` fetch `wp/v2/taxonomies` / `wp/v2/types` to get information about existing taxonomies and post types for later use.

Unfortunately, when doing so they assume every `baseURL` starts with `wp/v2`:

https://github.com/WordPress/gutenberg/blob/ee69822d9317d0d4c9ca42b951dbf6700b0dadd6/packages/core-data/src/entities.js#L209

https://github.com/WordPress/gutenberg/blob/ee69822d9317d0d4c9ca42b951dbf6700b0dadd6/packages/core-data/src/entities.js#L178

This is incorrect, because a post type in WordPress can potentially have a different REST controller forcing a different namespace or REST base.

It would be better to derive this from the `wp:items` link in `_links`

Aside: technically `WP_REST_Post_Types_Controller` has a hardcoded `wp/v2` prefix as well, but that should be fixed in core: https://core.trac.wordpress.org/ticket/53656

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by spacedmonkey** [comment]
Cross posting [#53656](https://core.trac.wordpress.org/ticket/53656).

This issue maybe fixed in core first. The plan would be add the namespace into the post type endpoint, so it doesn't have to be hardcoded here.

**Comment by swissspidy** [comment]
AFAICT the namespace is already available from the post type endpoint via the `wp:items` link, which is the solution I proposed above.

**Comment by spacedmonkey** [comment]
I have a PR to fix this ticket at #35850. It requires upstream changed to be merged into core.
