### ISSUE TITLE
Undefined support for core/freeform block when oldEditor not set

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#33422]
If the `core/freeform` block is not registered (possibly because `window.wp.oldEditor` is not set and the classic block is not loaded - Gutenberg is used outside of WordPress, for example) then if classic content is encountered you get the following undefined error as classic content doesn't have a block name:

![image](https://user-images.githubusercontent.com/1277682/125634562-b5153364-6ad6-4824-8305-084b93ab49c5.png)

To reproduce:
- Edit `wp-includes/script-loader.php` and disable this code:
```php
	$scripts->add_inline_script(
		'editor',
		'window.wp.oldEditor = window.wp.editor;',
		'after'
	);
```
- Load the editor, switch to code mode, and enter some plain text - this is classic content

![image](https://user-images.githubusercontent.com/1277682/125635097-8112ab5d-9f12-48ae-9f2a-5b4d1508a64f.png)

- Switch to visual mode and see the above `undefined` error

**Comment by Thelmachido** [comment]
Hi! There hasn’t been any movement on this issue in a while, I’ve marked it as stale. Let me know if you think it should be kept open. Thanks!

**Comment by kathrynwp** [comment]
I'm still able to replicate this with WordPress 6.0.1 and no plugins active.

@johngodley @gziolo Any chance of a PR for this one? Should it be kept open? Thanks!

**Comment by jordesign** [comment]
As this has been stale for almost 12 months - I'm going to close it out. Please feel free to re-open if needed.
