### ISSUE TITLE
Text for dropdown fields within legacy widgets in the Customizer is off centered

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#33431]
## Description
When editing a legacy menu widget in the Customizer in Firefox, the text for dropdown menus is misaligned. It works correctly on the Widgets admin screen.

## Step-by-step reproduction instructions
1. Add a menu to the site.
2. Open the Widgets panel in the Customizer.
3. Insert a legacy navigation widget.
4. Observe the dropdown text is pulled out of the field.

## Expected behaviour
The text is properly aligned within the field.

## Actual behaviour
It is not.

## Screenshots or screen recording (optional)
![Screen Shot 2021-07-14 at 13 06 09](https://user-images.githubusercontent.com/359867/125663410-79f820c0-909a-443e-9ce7-0ef4bc72f090.png)
![Screen Shot 2021-07-14 at 13 06 26](https://user-images.githubusercontent.com/359867/125663425-8ab84928-57c3-4b9a-96a4-55c13ea38f7a.png)

## WordPress information
- WordPress version: 5.8 RC3
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Macbook
- Operating system: MacOS 10.15.x
- Browser: Firefox nightly (`91.0a1 (2021-07-09) (64-bit)`), but also found in `89`.

**Comment by noisysocks** [comment]
Looks like a good candidate for 5.8.1.
