### ISSUE TITLE
Weird theme.json behavior: block specific typography settings

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#33436]
## Description
In the theme.json I added block based settings. 
```
"blocks":{
            "core/paragraph":{
                "customFontSize":true,
                "customLineHeight":true,
                "dropCap":true,
            },
            "core/heading":{
                "customFontWeight":true,
            }
        }, 
```

As instructed  in above post, section "Intermediate Testing Steps" > Typography, 
I saw the controls for heading as well as paragraph but VSCode put red squirrly lines underneath the last commas, and the settings disappeared on reload. 

Also, when the settings are visible the three cover blocks all go full width. 

I am aware that it all sound pretty weird. So, I made a video: 
https://recordit.co/62rzs1QE9S

## Step-by-step reproduction instructions
Use the instructions of the [FSE Call for Testing no 8](https://make.wordpress.org/test/2021/06/24/call-for-testing-thrive-with-theme-json/)
Follow Instructions under headline "Intermediate Testing Steps" 
- Set-up your testing environment
- Layout
- Typography. 

[Full theme.json is available here](https://gist.github.com/bph/fa359f27b12f8e3a87ce36d03090dde3)
## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 11.0 and Nightly
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system:  MacOS 10.15.7
- Browser: Chrome Version 91.0.4472.114

**Comment by bobbingwide** [comment]
After changing `theme.json` it's a good idea to validate it using a tool such as jsonlint.com. 
I believe VSCode is trying to tell you there's a syntax error.
If there's a syntax error then `theme.json` isn't loaded
There should have been a message. 
When there's a syntax error none of your settings will work.

Jsonlint reports
```
Error: Parse error on line 62:
..."dropCap": true,			},			"core/heading"
----------------------^
Expecting 'STRING', got '}'
```

**Comment by bph** [comment]
You would think, yes.  @bobbingwide  - But it DID  load, and it showed the settings in the editor, that weren't there before. And without the commas, the settings wouldn't load. It's the weirdest thing.

**Comment by annezazu** [comment]
Digging into this, when I use the theme.json file as is, I briefly see an error message while loading a new post:

<img width="1413" alt="Screen Shot 2021-07-15 at 9 41 24 PM" src="https://user-images.githubusercontent.com/26996883/125888431-d79a0c4e-b717-4d47-b72a-eae0bafdbd00.png">

However, the drop cap doesn't appear as you highlight in your video. I'm not sure what's going on here but I can replicate what you're describing with 5.8 RC 3 + GB 11.0. @jffng might you be able to do some sleuthing here? This feels like a bug to me as drop cap should still show for a paragraph block.

**Comment by jffng** [comment]
👋 

From the snippet you shared, I think you are missing a "typography" key underneath the block, so it would look like:

```
"settings": {
    "blocks": {
        "core/paragraph": {
            "typography": {
               "customFontSize": true,
               "customLineHeight": true,
               "dropCap": true
            }
        }
    }
}
```

Let me know if that helps...

**Comment by bph** [comment]
Thanks for eagle-eye @jffng :-) It all starts working when I added it. I really would have hoped for some indication or error message, to say “You can't have customFontSize setting without a "typography" parent."  Lets think some more about how to make it easier to flag these rookie mistakes. I am closing this issue.
Thanks for @annezazu @bobbingwide and @jffng for helping me figure this out.
