### ISSUE TITLE
isScrollable prop in CardBody component is causing a visual glitch in pre-existing components without isScrollable prop.

### ISSUE THREAD

**Issue by moon0326** [WordPress/gutenberg#33439]
## Description

The latest Gutenberg (11.0) causes a visual glitch on WooCommerce onboarding wizard pages where [Card](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/card/card-body/hook.js#L26) component is being used.

It looks like `isScrollable` has been added recently and the default value is set to `true`. I think the default value should be `false` to prevent any backward compatibility issues. 

## Step-by-step reproduction instructions

1. Deactivate plugins except for Gutenberg and WooCommerce
2. Navigate to WooCommerce -> Home to trigger the onboarding wizard.
3. Click the country dropdown and confirm the unexpected scrollbar.
4. Deactivate Gutenberg and repeat the same step. Confirm there is no scrollbar for this time.

## Expected behaviour
The scrollbar should not appear.

## Actual behaviour
Unexpected scrollbar appears where `Card` component is being used.

## Screenshots or screen recording (optional)

<img width="503" alt="Screen Shot 2021-07-14 at 4 47 24 PM" src="https://user-images.githubusercontent.com/4723145/125707204-c0ca5ded-b159-48cf-8241-ce7fd0e7fba3.png">

![Screen Shot 2021-07-14 at 4 33 01 PM](https://user-images.githubusercontent.com/4723145/125706367-33c70744-050d-410d-a4a6-9d4d70669fca.jpg)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 11.0.0
- Are all plugins except Gutenberg deactivated? No (WooCommerce is activated)
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Mac OS BigSur
- Browser: Chrome 91.0.4472.114

**Comment by moon0326** [comment]
WC Admin team is working on a fix for wordpress.com customers in this [PR](https://github.com/Automattic/wc-calypso-bridge/pull/710)

**Comment by talldan** [comment]
@moon0326 Do you know which PR caused the issue?

**Comment by moon0326** [comment]
@talldan I think this [PR](https://github.com/WordPress/gutenberg/pull/32566) caused the issue.

**Comment by talldan** [comment]
Thanks @moon0326.

@ciampo Is this something you'd have time to take a look at?

**Comment by ciampo** [comment]
Thank you @talldan for the ping — I opened (update: and merged) https://github.com/WordPress/gutenberg/pull/33490 which changes the default value of `isScrollable` to `false`.

Once that PR gets included in the next Gutenberg release, it'd be great if we could revert [the hotfix](https://github.com/Automattic/wc-calypso-bridge/pull/710), since it looks quite hacky — @moon0326 , would you be able to track this task on your side?

**Comment by moon0326** [comment]
> Thank you @talldan for the ping — I opened (update: and merged) #33490 which changes the default value of `isScrollable` to `false`.
> 
> Once that PR gets included in the next Gutenberg release, it'd be great if we could revert [the hotfix](https://github.com/Automattic/wc-calypso-bridge/pull/710), since it looks quite hacky — @moon0326 , would you be able to track this task on your side?

Thank you @ciampo for the PR 🙇  I'll track the task on my side.

It looks like the next release date is July 28, 2011, according to https://github.com/WordPress/gutenberg/milestones.

I'm setting a reminder to check it back on July 29, 2021. I'll work on a PR to revert back my change once I confirm the change in the new version.

**Comment by talldan** [comment]
Closing this as it seems like the issue has been fixed in this repo.
