### ISSUE TITLE
Editing Reusable Blocks that I don't have permission to Edit shows changes that aren't actually saved

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#33458]
## Description
If a user lacks the ability to edit a specific Reusable block (perhaps they are a Author and the block was originally made by someone else), Gutenberg still allows them to edit the block in the backend. Publishing/updating the post gives no warnings or errors, so they have no way to know that their actual published content looks different from what they currently see while editing. 

## Step-by-step reproduction instructions
Have User A (perhaps a Site Administrator) create a reusable block.
Have User B (say, an Author) author a post using the reusable block. 
After inserting the reusable block, edit it on the screen.

![2021-07-15 07_56_49-Window](https://user-images.githubusercontent.com/945157/125791970-3049b35b-35bd-40ea-97e7-20dee15d0683.png)
![2021-07-15 07_58_09-Window](https://user-images.githubusercontent.com/945157/125792057-b171088a-aecf-46b2-a747-01ae765636a7.png)
![2021-07-15 07_57_05-Window](https://user-images.githubusercontent.com/945157/125791993-909efa43-3fdd-46ab-8a81-a5e9389209b2.png)

## Expected behaviour
The author should simply NOT be able to edit the reusable block. They don't have the capability to it. 

## Actual behaviour
The author appears able to edit the reusable block, but the changes are simply silently discarded upon publishing/updating.

## WordPress information
- WordPress version: 5.8-RC-3
- Gutenberg version: 5.8-RC-3
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 91

**Comment by Thelmachido** [comment]
I wasn't able to replicate this, when I try to save the changes I would have made to the reusable block _as an author_ of the site I get an error. 

https://user-images.githubusercontent.com/41231764/186400198-8b6c3d75-c9ca-49e5-a2c5-4e5d1a1ed995.mov

WordPress 6.0.1 

Gutenberg 13.9.0

Theme - TT2 

I will close this issue for now
