### ISSUE TITLE
Column block: percent unit to control the column's width is missing in 5.8-RC3 

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#33463]
## Description
The `%` unit to control the column's width is missing in WP5.8-RC3. It was there in RC2.

## Step-by-step reproduction instructions
1. Add a new post.
2. Insert a Columns block.
3. Select a Column block.
4. In the settings sidebar, try to change its width.
5. Notice that the unit is set to `px` by default and that `%` is missing from the dropdown.

## Expected behaviour
By default, the unit to control the column's width should be set to `%`.

## Actual behaviour
The `%` unit is missing, making it impossible to change the column's width using percent.

## Screenshots
| 5.8-RC2  | 5.8-RC3 |
| ------------- | ------------- |
| ![column-wp5 8rc2](https://user-images.githubusercontent.com/44895380/125812306-badf48d4-bdf7-44d8-9d43-c6ff5600c719.png) | ![column-wp5 8rc3](https://user-images.githubusercontent.com/44895380/125812397-5fad6b00-90d6-4a5f-9359-ad39900dbe45.png) |

## WordPress information
- WordPress version: 5.8-RC3 
- Gutenberg version: Not installed
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

**Comment by youknowriad** [comment]
So I know what happened here, we fixed a bug in RC3 where the columns block was not using the `spacing.units` config and was using its own fallback. and WordPress defines a list of units by default that doesn't include `%`. So fixing this would be a small change, but the impact is that the `%` unit will be available in all places where we can use units (font size, height, width, margin, padding...). 

So it's a bit impactful, but I'm wondering if there's any valid reason for excluding `%` from the default available units.

**Comment by desrosj** [comment]
Were percentage units included previously in 5.7? This is described as a regression from RC2 to RC3.

If they were not present the previous release, I think I am comfortable categorizing this as a future item and not a blocker, as it's not technically a regression.

**Comment by desrosj** [comment]
Also, I'm a bit concerned with adding the percentage unit in more places without thorough exploration as that could prove more difficult to remove later for the other areas you mentioned.

**Comment by youknowriad** [comment]
> Were percentage units included previously in 5.7?

Yes, it was there but in 5.7 there was no way to define the units for the block using theme.json. Meaning that setting didn't exist. I think the other approach might be to remove the `spacing.units` default config entirely but that would mean that all blocks should ensure a default fallback on their own.

I think at this point adding the `%` to all controls seems safer.

**Comment by mcsf** [comment]
> I think at this point adding the `%` to all controls seems safer.

If it's limited to spacing controls, I think this is viable.
