### ISSUE TITLE
Query Pagination Next: Add an option to change &raquo; to another type of punctuation.

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#33474]
## What problem does this address?
By default the Query Pagination Next block outputs this:

"Next Page &raquo;"

Which can't be customized by the user.

## What is your proposed solution?
We should add an option to the block to change this to something else. Possible options could include:

"Next Page &rarr;"
"Next Page &lt;"

or simply

"Next Page"

**Comment by carolinan** [comment]
It is already possible to edit the text of the links, but perhaps this can be clearer in the editor.
