### ISSUE TITLE
Query Title: Search and 404 pages.

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#33476]
## What problem does this address?
The Query Title block is empty on the Search page

## What is your proposed solution?
The Query Title blocks should display "Search results" on a search page and "Nothing found" on a 404 page.

Some prior work on this here: https://github.com/WordPress/gutenberg/pull/27989

**Comment by coreymckrill** [comment]
I would also add the Posts page. If the site is configured with static pages for the Homepage and Posts page, it should output the page title of the Posts page. If the site is configured to show "Your latest posts", perhaps it could default to just "Posts" but then also be customizable via a block attribute?

**Comment by coreymckrill** [comment]
Also, I think ideally the `type` attribute wouldn't be necessary in this block, because it would be able to automatically identify which type of query it's in and output the appropriate title. That way the block could be used in a block template part that gets reused across multiple types of views.

**Comment by carolinan** [comment]
Do we still want a title specifically for the 404 page? I am not sure it would be helpful to have a block that could just as well be a heading block.

**Comment by scruffian** [comment]
The only advantage I see is translation, but since we can handle that with patterns then perhaps we can close this.
