### ISSUE TITLE
Clarify Gutenberg's goals and scope better in the WordPress.org readme.txt

### ISSUE THREAD

**Issue by markjaquith** [WordPress/gutenberg#3347]
There appears to be some confusion about the goals and scope of Gutenberg. The WordPress.org `readme.txt` downplays the scope, and could be rewritten to better reflect where the project is and is going.

"The goal of the block editor is to make adding rich content to WordPress simple and enjoyable."

Clearly the scope is much more than just replacing the current editor with a block-based editor. We should combat the FUD by making this clear. Not everyone will be reading GitHub tickets; any messaging that is more public-facing should be carefully considered.

**Comment by jasmussen** [comment]
As of the just-released v1.9 of the plugin, the readme has been drastically updated, with the Github readme as the template but with tweaks for .org. Finally, apologies for the delay! Please let me know if you feel this update doesn't address the ticket, and we'll reopen.
