### ISSUE TITLE
Add credit block

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#33475]
## What problem does this address?
Block themes might want to add a credit block in the footer.

## What is your proposed solution?
We should add a simple block that outputs "Proudly Powered by WordPress", which can be translated and customized.

Other options might include:
"Built with WordPress"
"Powered by WordPress"
"Website built with WordPress"
"Website powered by WordPress"

**Comment by aristath** [comment]
Why can't they just add a paragraph block with the text they want? :thinking: 
If they want to add a "credit" that says _"Powered by [WordPress](https://w.org)"_, I don't see why they can't just type 3 words and we need to add yet another block... A paragraph block is editable by users so if they want to change the credit on their sites to make it "Copyright 2021 my-business", there's nothing stopping them from customizing that.
Or is the purpose of the block to prevent users from customizing the text? 'Cause they can still just remove the block and add a paragraph in its place. Unless we want to lock the footer and _force_ users to have that credit? But that would go against WordPress's openness.
I fail to understand the reasoning behind the addition of such a block, can you please elaborate?

**Comment by scruffian** [comment]
The benefit is i18n. The text inside the block can be output by PHP and so it can be wrapped in `__` calls.

**Comment by aristath** [comment]
If the problem is that template strings can't be translated, then perhaps we should work on finding a way to fix that? 
Adding a new block simply because a string can't be translated sets a dangerous precedent and is a mere workaround for a deeper underlying issue... I fear if we start adding blocks for things that can't be translated, we're going to end up with a dozen new blocks instead of actually fixing translations in templates.

**Comment by scruffian** [comment]
Another opportunity I see is that it exposes a common design pattern in a theme which gives other services the opportunity to hook into. For example if I wanted to add a "Hosted by...." credit to my user's sites, this gives me a place to do that.

**Comment by mtias** [comment]
If it were to include a credit line and current year it'd be a nice thing to make dynamic. Maybe in that case the "powered by" is toggleable in case people want to show it. Maybe also a way to collapse into a W icon only?

**Comment by paaljoachim** [comment]
Hey

I happen to create a duplicate: https://github.com/WordPress/gutenberg/issues/47522
It shows some newer examples from current plugins.

**Comment by MaggieCabrera** [comment]
Happy to close this one in favor of yours, I don't have plans to pick this one up any time soon

**Comment by scruffian** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/47522
