### ISSUE TITLE
Legacy Widget: Custom HTML widget does not display code editor until clicked

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#33479]
## Description

In WordPress 5.7.2 the Custom HTML widget looks like this.

![image](https://user-images.githubusercontent.com/2474435/125852692-405d7da3-7f21-42e8-9f4e-6d5eeda10f74.png)

In WordPress 5.8-RC3 it first appears as

![image](https://user-images.githubusercontent.com/2474435/125853980-75b845b0-5d32-40a0-82f6-54d0afcd4b88.png)

Clicking on the content causes the Legacy widget to be displayed.
![image](https://user-images.githubusercontent.com/2474435/125854095-8cc6e51b-73ef-444a-be42-08828fad660a.png)

but you can't see the content.

Clicking in the content area displays the widget's text but some of it is hidden 
![image](https://user-images.githubusercontent.com/2474435/125854296-e72bd8dd-1e1a-4dfc-8353-341024076ce2.png)

## Description
This bug was detected testing WordPress 5.8-RC3 without Gutenberg. 

## Step-by-step reproduction instructions
1. Deactivate all plugins and activate a default theme, such as Twenty Eleven
2. In WordPress 5.7.2 create a Custom HTML sidebar widget.
In my example I'm using a couple of shortcodes, but you could write anything
```
[content]

[guts]
```
2. Update to WordPress 5.8-RC3
3. Choose Appearance > Widgets
4. Click on the contents of the Legacy widget 
5. Note you can't see the Content: at all
6. Click in the Content: area
7. The content appears but it's overlaid by the line numbers

## Expected behaviour
Either the Legacy Widget Custom HTML should display nicely
or the block should be automatically converted to the Custom HTML block.

## Actual behaviour
See the Description.

## Screenshots or screen recording (optional)
See the description

## WordPress information
- WordPress version: 5.8-RC3 
- Gutenberg version: Not installed 
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Twenty Eleven

## Device information
- Device: Desktop 
- Operating system: Windows 10 
- Browser: Chrome

**Comment by draganescu** [comment]
I was able to repro with the latest Gutenberg trunk (10 Aug 2021) and WP 5.8.

**Comment by talldan** [comment]
It was mentioned on #33604 that this is still a problem in WordPress 5.9.

**Comment by mattf10** [comment]
This is still a problem - it makes it virtually impossible to edit the HTML since the line numbers sit over the content.
<img width="182" alt="Screenshot 2023-02-13 at 15 41 02" src="https://user-images.githubusercontent.com/21988717/218488385-6d0e1c5e-3454-4dd4-9bd3-275932655ccd.png">

What do we need to do to get this fixed?

**Comment by draganescu** [comment]
Is this something that still a problem? I tested with trunk and I don't see neither the code editor, hence not the problem, in the custom HTML widget - anymore, but I also was not able to insert a custom HTML legacy widget anymore, for legacy widget I only have Meta and Navigation menu.

![Screenshot 2023-12-04 at 23 16 36](https://github.com/WordPress/gutenberg/assets/107534/bf9585a0-1fc5-4486-8958-a5c55e207b20)

**Comment by mattf10** [comment]
@draganescu  - no longer a problem for me.   The code editor line numbers now sit to the left of the code.
<img width="122" alt="Screenshot 2023-12-05 at 09 38 06" src="https://github.com/WordPress/gutenberg/assets/21988717/9956d802-f89e-402c-b1a1-52c149f01b92">

**Comment by draganescu** [comment]
In that case I will close this, thank you for the feedback evryone! 🙇🏻
