### ISSUE TITLE
Editable: Anchor conflicting with the multi-block select feature

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#3348]
## Issue Overview

I noticed an issue when trying to add an anchor to the block that isn't the last one on the page. I recorded what happens sometimes in the following screencast:

![anchor-issue](https://user-images.githubusercontent.com/699132/32443845-beec3540-c300-11e7-9d20-a15eb3b0284f.gif)

In some cases, an anchor doesn't get set properly when multi-block selection gets triggered.

## Steps to Reproduce (for bugs)

1. Add 2 paragraphs and fill them with content.
2. Try to add a link in the first paragraph.
3. If it works, try also to edit anchor settings.
4. It usually selects two blocks instead of updating anchor when link's tooltip overlaps the next block.

## Expected Behavior

Anchor gets configured properly, blocks don't get selected.

## Current Behavior

Anchor doesn't get updated, blocks are selected.

**Comment by aduth** [comment]
Additional context at #3454

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521736216000703)._

**Comment by gziolo** [comment]
It's no longer an issue.
