### ISSUE TITLE
[Components]: Migrate Avatar

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#33488]
Migrate Avatar component

**Comment by ntsekouras** [comment]
Internally this uses `Image` and `AspectRatio` from `g2`. @sarayourfriend is these something we need to migrate as well? They're not listed in the parent issue.

**Comment by sarayourfriend** [comment]
Yeah any dependencies will need to be migrated one by one. I can add them to the tracking issue.
