### ISSUE TITLE
Gallery block: look at renaming the Gallery component to Grid after refactor merged

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#33484]
See https://github.com/WordPress/gutenberg/pull/25940#discussion_r670128464

The class of the gallery component should be aligned with the component name, and suggestion is that Grid would be a better name for the component that actually lays out the gallery.

**Comment by glendaviesnz** [comment]
@talldan, we ended up removing the `blocks-gallery-grid` class as it was superfluous in the refactored layout, and just added an extra level of specificity for theme authors to try and override [as noted here](https://wptavern.com/gallery-block-refactor-expected-to-land-in-wordpress-5-9) - do you think it is still worth renaming the `Gallery` component to `Grid` anyway - I think it probably is, because it in itself isn't really the gallery component, it is just the layout part. `Layout` would be another name option.

**Comment by talldan** [comment]
You could do, but I don't feel strongly about it. Feel free to close this if the classname no longer mismatches the component name.

**Comment by glendaviesnz** [comment]
Given that the className clash is no longer an issue I am going to close this for now.
