### ISSUE TITLE
The link modal "moves" together with the caret

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3349]
To reproduce:

- insert a link or an "@" username in a paragraph
- after they're inserted in the content, the caret is at the end of the new insertion except in Safari, where it is at the beginning
- regardless, now use the left and arrow keys to move the caret through the link or username: don't keep the arrow key pressed, instead press and release multiple times
- the "link modal" popup moves left or right at each keystroke

![screen shot 2017-11-06 at 14 22 30](https://user-images.githubusercontent.com/1682452/32446057-fa4238ea-c307-11e7-81e2-c73698b7c49b.png)

![screen shot 2017-11-06 at 14 22 54](https://user-images.githubusercontent.com/1682452/32446059-fa5f6ed8-c307-11e7-9e6a-6f3ae964aba3.png)

**Comment by mtias** [comment]
This should no longer be an issue since arrow keys engage isTyping mode which hides UI.
