### ISSUE TITLE
Pasting a heading creates two heading blocks

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#3351]
## Steps to Reproduce (for bugs)
1. Select a heading from some online news article (or just body text, it doesn't matter technically)
2. Create a post in Gutenberg and add an empty Heading block
3. Paste the copied heading into this heading block
4. The heading block remains empty, but a new block with the pasted content is added below that one, PLUS an empty paragraph block below that one.

![headingsss](https://user-images.githubusercontent.com/6073772/32449842-f103ddaa-c312-11e7-88b8-fc387bbf3bf1.gif)

Gutenberg 1.6.1 + WP 4.8.3 vagrant + chrome

## Expected Behavior
The pasted content to end up in the block.

**Comment by karmatosed** [comment]
I can replicate, thanks for finding a good bug to fix.

**Comment by jorgefilipecosta** [comment]
With the merge of https://github.com/WordPress/gutenberg/pull/3949, this issue should be fixed.
