### ISSUE TITLE
A theme.json from child theme is not merged with the one in parent theme

### ISSUE THREAD

**Issue by overclokk** [WordPress/gutenberg#33512]
I'm testing the theme.json with a child theme and I see that when the child is active and theme.json is present in both child and parent this will replace the one in the parent theme instead of being merged with it, is it a desired behavior?

My first tought was to have some global settings in parent theme and some little modification in child theme.

**Comment by overclokk** [comment]
I just found this issue #25612 and I think that child themes will have more space in the future of FSE, I'd also like to have grand-chils supported from core, for now grand-childs are possible only with plugin.

**Comment by dashkevych** [comment]
It would be great if there was a [fallback](https://github.com/WordPress/WordPress/blob/9937fea517ac165ad01f67c54216469e48c48ca7/wp-includes/class-wp-theme-json-resolver.php#L218) for `theme.json` located in the parent theme if the child theme does not have one.

**Comment by overclokk** [comment]
@dashkevych yes, this is something similar to this issue https://github.com/WordPress/gutenberg/issues/33959 as well.

**Comment by iandunn** [comment]
This seems like a duplicate of #25612, is there anything unique here that I'm missing?

If not, this can be closed.

**Comment by overclokk** [comment]
@iandunn maybe yes, for now I close this issue in favor of https://github.com/WordPress/gutenberg/issues/25612
