### ISSUE TITLE
Enable the Code editor within the Widget Customizer/Screen

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#33518]
To create a consistent editing experience with the rest of the block editor, the widget editor/customizer should also have the code editor. 

I occasionally will copy content from one page to another by going into the code editor (on a particular page); copying the relevant markup/html and then copying it into a new page or area of my site.  
(I hope to do less of this as templates and patterns becoming easier to make; but neither are enabled to be inserted into widget customizer screen yet ; ref https://github.com/WordPress/gutenberg/issues/26170). 

I did this workflow again because I wanted to reproduce one of our reusable blocks in the block-based widgets but that's since that's not currently possible (ref https://github.com/WordPress/gutenberg/issues/32952) and didn't want to go through the motions of recreating the block(s) and setting their options. 

## Step-by-step reproduction instructions
1. visit path-to-your-site.test/wp-admin/widgets.php
2. select a widget area 
3. 

## Expected behaviour
have the code editor option available when a widget area was selected

## WordPress information
- WordPress version: 5.8-RC3
- Gutenberg version: 11.0.0
- Are all plugins except Gutenberg deactivated? n/a
- Are you using a default theme (e.g. Twenty Twenty-One)?

**Comment by noisysocks** [comment]
Thanks for the request.

We have a similar predicament in the widgets editor to what @noahtallen describes in https://github.com/WordPress/gutenberg/issues/22528#issuecomment-696921321 about the site editor. Unlike the post editor, there is no single entity which we can display the HTML code for. Instead the widgets screen displays multiple widget area entities. 

Put simply, the Code Editor would just show this:

```
<!-- wp:widget-area { "id": "header-1" } /-->
<!-- wp:widget-area { "id": "sidebar-1" } /-->
```

Which isn't very useful!

It might be something that we can implement in the future, particularly if we move away from showing multiple widget areas in the single screen. See also https://github.com/WordPress/gutenberg/issues/33254.

I'll close this issue out as "won't fix" for now but will leave note in https://github.com/WordPress/gutenberg/issues/33254 as yet another argument for moving away from the current approach involving Widget Area blocks.
