### ISSUE TITLE
Improvement for Panel

### ISSUE THREAD

**Issue by skalanter** [WordPress/gutenberg#33525]
Hi Team,

Hope you're well.

## Description(included actual behavior + expected behavior):

Since Appearance > Widgets is working with the Gutenberg(block editor), I think it needs a bit of improvement;
please check this online Google Doc: https://docs.google.com/document/d/19eNb5bNjuchpvz8BdGC9ISYB86gY6y4uFm4pWy3xMU4/edit?usp=sharing (6 items).

## WordPress information

- Using the latest WP 5.8 Beta / RC 4
- Gutenberg Version 11.0.0
- Go to this path: Appearance > Widgets

**Comment by kevin940726** [comment]
Hi! Thank you for opening the issue!

I wonder if it's possible to move the content from the Google Doc to the issue body itself? It's easier for us to keep track of all the suggestions, and also good for searchability.

**Comment by skalanter** [comment]
Hi, sure, I'll be moving all content here.

**Comment by skalanter** [comment]
Google Doc Content:

1. Possibility to show full width

2. Remove inner padding on appearance > widgets: [screenshot](https://lh5.googleusercontent.com/Bz6tDdiXtKxl5ELA8N8Zg4ZM6Miu9mtsXuBMHFqEs7tAG7SwKM19yo06oAnCM9SuipKMdEmzy-RPqiPrG429JAVOO1NbFUKelO-EJ1NywMjYu81Ar1cWMRseW61Ft_iTdJoF4MdI)
And shows like the front-end: [screenshot](https://lh3.googleusercontent.com/RShhlVzyHG8DUaN0rMfE0AaS1IIfbwJ3AHCWPzoIHn3JxsTTK4t5K0NbsB1BBwOXBZKQE5Pt7yx_6elFpe5wsuzoI2OMDoQj2pb06vPM2bhoa8dFWb4LYqGBUkSJl8FqdYqOxkXn)

3. Instead of using the click to change the view, using the [UI tab](https://www.google.com/search?q=ui+tab&tbm=isch&ved=2ahUKEwjL6-7NrurxAhXGgM4BHdvFC2sQ2-cCegQIABAA&oq=ui+tab&gs_lcp=CgNpbWcQAzIECCMQJzICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIAFDaCFjaCGDpCmgAcAB4AIABrQGIAa0BkgEDMC4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=ru_yYMvcC8aBur4P24uv2AY&bih=969&biw=1920&rlz=1C1CHBF_enIR868IR868#imgrc=oIwrLLzrIogUwM) for changes: [screenshot](https://lh6.googleusercontent.com/qa7Dzch2mQwKmAhVTN4vASYEv0UI1xS5ibQn7Gm1pe9sWCa48-2h06IoMJDZNdBML1QLpBFVKHqG5H0FRBZbzgF6djbO8167adBD_-8VM9CPV2M-5uH9IPvrB1pzNRjV3w1WzPLa)

4. Since the width of the widgets is smaller than posts and pages (I mean for Block Editor), it would be great if the widgets side panel keep open: [screenshot](https://lh5.googleusercontent.com/vzLCMD5cy-uxowX2SkN7LiQGENQ_33W1P5blJ8DAa6_T4tNol6bBrOSf3DVF36V6ZaXqGhUuvah4Y5HGI1MPm6dAfVeWy6XuBMzrdp_zF9se9sovtlYOalx3axyHufkOkUovze4l)

5. Since the theme and plugin, authors made custom widgets, especially for sidebars! So in this time, I think that widgets should be put at the first view, like this one: [screenshot](https://lh6.googleusercontent.com/jvtSAMQQGz9OC3NKA54VNpONL4IGsPhEsIHZQQ1F6ku_tHHFFxryojC0aQDI7EFXLsJ4TCt4hZwaH9y4MHrAEgtDKqtUpd2SHNP8PEDbX9z16JD2DvVqd0Ay6eY24Rx-02QFhwa7)

6. For each section of the widgets panel, it would be great if be possible to make it expanded/close: [screenshot](https://lh4.googleusercontent.com/MUn8H8_Bp7aWS7gnnh3T_VXUfuiwRLPd2L9WxtaB9mclyBts_XO2SLxFnQzwwYp-9byV1ZP5V17-2VaqEuPAaCY8FrbVvttGc0yiJC-1f3d_JwM4sX0kRA8AFwe1ZgfC4rerYp1s) 
Look at other page builders in the world, not just WordPress plugins (VC, KC, Oxygen, Elementor), look at Webflow, EditorX, Squarespace, even Mailchimp, and MailLite, and others…

Of course, this feature request wrote for widgets but perhaps useful for another place that uses Gutenberg.

**Comment by noisysocks** [comment]
Hi @skalanter. Could you please help the maintainers out and open seperate issues for each of your feature requests? It's difficult to discuss multiple enhancements in one issue as GitHub doesn't support threading. Some of your items are duplicates of other issues that have been discussed and some are enhancements that would apply to every block editor, not just the widgets block editor.

Thanks!
