### ISSUE TITLE
Ability to split the file theme.json into multiple files

### ISSUE THREAD

**Issue by overclokk** [WordPress/gutenberg#33524]
## What problem does this address?

When people will start using theme.json intensively will be a mess, thousand of line of configuration in a single file, it will hard to maintain without going crazy, this is just an example with 500 line https://github.com/Automattic/themes/blob/trunk/blockbase/theme.json

## What is your proposed solution?

I think the ability to have multiple file with splitted configuration should help avoid this problem.

**Comment by aristath** [comment]
If you are comfortable with `npm` and build processes, you can already do that... there are plenty of packages out there you can use to merge/combine JSON files.
If you are more comfortable with PHP, then that's pretty simple to do via PHP too.
So you _could_ have multiple json files in a dev folder in your theme, and then have something like this code in a `wp-content/mu-plugins/compile-theme-json.php` file:
```php
<?php
function combine_json_files( $input_files = array(), $output_path ) {
	$contents = [];
	foreach ( $input_files as $input_file ) {
		$contents = array_replace_recursive( $contents, json_decode( file_get_contents( $input_file ), true ) );
	}
	file_put_contents( $output_path, json_encode( $contents ) );
}

combine_json_files(
	[
		get_theme_file_path( 'json-parts/settings.json' ),
		get_theme_file_path( 'json-parts/styles.json' ),
	],
	get_theme_file_path( 'theme.json' )
);
```
You can split it to as many JSON files as you want, and the theme.json file will be auto-regenerated on each page-refresh. This can be useful while developing if you feel that your file's size is getting out of hand.
Or... you could compact the structure of your JSON file.
There's no reason why this should take up 10 lines:
```json
{
	"name": "small",  
	"slug": "small",  
	"size": "0.8em"
},
{
	"name": "normal",  
	"slug": "normal",  
	"size": "1em"
}
```
It can just as easily be written in 2 lines and will be just as readable:
```json
{ "name": "small",   "slug": "small",   "size": "0.8em" },
{ "name": "normal",  "slug": "normal",  "size": "1em" }

```
Granted, this won't be possible to do everywhere, but by changing simple things like that I was able to get my own theme.json file from 280 down to 135 lines, so it's definitely worth looking into. :+1:

**Comment by overclokk** [comment]
Thank you @aristath 

> If you are comfortable with npm and build processes, you can already do that

Yes, I know I can do it on development environment, but I just meant a native way in the core, if theme.json was in PHP we could have used `require()` inside a `theme.php`.

Inlining things for me it makes less readable the content.

**Comment by karmatosed** [comment]
I think it is certainly going to be a problem for some people. Still, I wonder how many will have lengthy theme.json or even if adding functionality into core almost encourages, causes more of an expectation it should be lengthy? 

I like the method proposed by @aristath; for me, this is more about how you choose as the creator to compile your files, not something I'd see core providing. Perhaps there are tools to compile a theme.json outside even; I recall those jquery compilers of the days gone past - maybe something similar - I know there's a visual theme.json builder, and maybe there's a compiler option someone could explore outside of core.

**Comment by overclokk** [comment]
If the theme.json was in php (theme.php) the issue did not exists, but we have a json file and I saw people who install tens and tens of plugins on its own WP and I saw devs who put all the code in one single file.

If this will not be a part of the core it's ok, I wll do on development creating my own tool (maybe also for wp-cli).
If I will do the PHP way I will not use json files but directly PHP arrays and at the end serialize the result.

> I know there's a visual theme.json builder

That kind of tool is good only for learning the schema, not for development.

**Comment by overclokk** [comment]
So, I built my generator for theme.json file from a PHP array https://bit.ly/3xl5Gsh
It's still experimental but for now it works as expected I think.

It works as a composer plugin and also as WP_CLI command.

With this library you have to provide only a callback that returns an array with all config, nothing else, you are free to build the configuration as you wish, this is up to you.
