### ISSUE TITLE
Pasting an IMG tag in an HTML paragraph locks the block - or - improve the locked block error

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#3352]
## Steps to Reproduce (for bugs)
1. Insert a paragraph block
2. Switch it to HTML mode
3. Type/paste an img tag into it
4. Click outside of the block
5. The block is now locked.

## Expected Behavior
This might be a small usecase, but I'd expect gutenberg to try and parse any HTML that I wrote in here back into the correct block(s). Maybe not something complex, but at least one simple IMG tag. 

## Current Behavior
Instead I am presented with three options: `Overwrite` (Yes I want to overwrite the block with my own HTML, but oh no, that option just clears it back to an empty paragraph block). There's `Convert to classic text`, which does what I want sort of _I guess_, though after that I can use `Convert into block` and it correctly turns it into an image block, but that's three confused clicks later. And there's `Edit as HTML` which just turns it into an HTML block, which seems redundant.

I'm not sure if there's a nice way to do it, but then at least the warning should be more descriptive, because it looks intimidating and doesn't explain the options well.

**Comment by iseulde** [comment]
@hedgefield Are you still experiencing this issue? Pasted images should form an image block. A lot has  changed there in the meantime.

**Comment by hedgefield** [comment]
It does still happen, though clicking `convert to blocks` does make it into an image block with the right image. Not super intuitive, but enough to close this I suppose?

**Comment by mtias** [comment]
Can this be closed now?

**Comment by hedgefield** [comment]
I would say yes. When clicking `Convert to blocks` now it does make an IMG block of it with the correct image (though it would be nicer if it did so without first throwing the error when the HTML is valid).
