### ISSUE TITLE
Impossible to change the title of a page!

### ISSUE THREAD

**Issue by byron-hawkins** [WordPress/gutenberg#33530]
Your editor makes it  impossible to change the title of a page! Please delete this extension from GitHub, from WordPress, and from all other sources of distribution. This extension should be permanently classified as malware!

**Comment by talldan** [comment]
@byron-hawkins Please could you use the provided template when reporting bugs. If you can report a new issue with the required details (particularly steps to reproduce, OS and browser details, WordPress and Gutenberg version numbers) it can be tested and verified.
