### ISSUE TITLE
Create a new @wordpress npm package for creating and managing local SSL Certs.

### ISSUE THREAD

**Issue by WraithKenny** [WordPress/gutenberg#33557]

**Comment by WraithKenny** [comment]
Seems like there's some newer packages that might either be useful to this, or actually solve this https://www.npmjs.com/search?q=keywords:certificate%20authority Have to go through the list and see.

**Comment by WraithKenny** [comment]
3 options seem worth investigating:
* https://www.npmjs.com/package/https-manager (https://github.com/UniWrighte/https-manager)
* https://www.npmjs.com/package/nodejs-self-signed-certificate-example (https://git.coolaj86.com/coolaj86/nodejs-self-signed-certificate-example.git)
* https://www.npmjs.com/package/cau (https://github.com/rse/cau)

The first option looks interesting; It's MIT licensed, and seems to have all the functions, and it's entirely node based (node-forge, which is very popular). Drawbacks: it's not itself widely used, documentation is sparse, but seems simple enough, so that's not the end of the world.

The second, "nodejs-self-signed-certificate-example" has "example" in the name, seems to be `sh` script based tutorial more than anything, but I could be wrong.

The third looks somewhat promising; I think it's intended as a wrapper around a docker image to access the unix functions, and looks both more complicated than we'd need, and not necessarily what we need.

I'll experiment a little with the first option and see if that obviates my proposal for a new package.

**Comment by swissspidy** [comment]
Do you know https://www.npmjs.com/package/devcert?

It seems to offer everything you seem to be looking for here and is hugely popular & stable.

I would not reinvent the wheel if this supports all requested features.

**Comment by WraithKenny** [comment]
Devcert seems totally awesome, thanks!
