### ISSUE TITLE
Allow passing the `query` argument to data selector shortcuts

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#33566]
## Description
Currently, it's not possible to pass the second argument to entity selector shortcuts like `getMedia`.

This will be useful for passing the `context` argument for REST API requests. See #32961.

## Expected behavior
Data selector shortcuts ignore the second argument.

## Actual behavior
Data selector shortcuts shouldn't ignore the second argument.

/cc @youknowriad

**Comment by youknowriad** [comment]
Seems it's just an oversight, let's allow that.
