### ISSUE TITLE
Build tooling: update release docs with information on automated grouping by feature request

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#33568]
Following the merge of https://github.com/WordPress/gutenberg/pull/33229 we need to update the docs to ensure they reflect how the changelog will be generated and what is expected of the release lead.

**Comment by gziolo** [comment]
I believe we can close it now that https://github.com/WordPress/gutenberg/pull/33573 landed. Is there anything left to cover in the docs?

**Comment by getdave** [comment]
Closing as forgot to link this up with the PR
