### ISSUE TITLE
Missing .editor-styles-wrapper in customizer's block-based widget editor.

### ISSUE THREAD

**Issue by inc2734** [WordPress/gutenberg#33571]
## Description

The post and widget screens have `.editor-styles-wrapper`, but the customizer does not. Therefore, some styles are not reflected in the widget preview in the customizer.

Also, styles added with `add_editor_style()` will not be reflected in the customizer.

## Step-by-step reproduction instructions

1. Go to customizer.
2. Click "Widgets" panel.

## Expected behaviour

I want to apply styles to the widget previews in the customizer as well as to the posts and widget screens.

## Actual behaviour

Some styles are not reflected in the widget preview in the customizer.

### Post edit screen

<img width="1279" alt="post-edit" src="https://user-images.githubusercontent.com/1094306/126341377-f948e219-490d-4c66-b338-80b5ae5a7660.png">

### Widgets screen

<img width="1276" alt="widgets" src="https://user-images.githubusercontent.com/1094306/126341395-bdcf298c-99f4-42a9-b0dc-192ee37a9bc4.png">

### Customizer

<img width="1276" alt="customizer" src="https://user-images.githubusercontent.com/1094306/126341413-5116c11a-0e93-4f9c-b770-4bb94f95f5c7.png">

## WordPress information
- WordPress: 5.8 RC4
- Twenty Twenty-OneVersion: 1.3

**Comment by getdave** [comment]
<img width="1279" alt="Screen Shot 2021-07-21 at 15 14 32" src="https://user-images.githubusercontent.com/444434/126503588-c7e41f1f-5790-4cce-9ee7-b681018ea8c6.png">

Confirmed that the Widgets screen has the class around each Widget area but the Customizer doesn't.

Looking at a fix.

**Comment by noisysocks** [comment]
This is expected. The Customizer does not support editor styles because there is already a styled preview of the content in the preview iframe, so I wouldn't expect to see `.editor-styles-wrapper` anywhere.
