### ISSUE TITLE
The new widget screen throws a PHP notice for deprecated components when using wp-editor scripts

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#33576]
## Description

There are plugins providing Gutenberg blocks with a dependency on `wp-editor` script. Using them with WordPress 5.8 triggers the following notice:

> Notice: wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see Debugging in WordPress for more information. (This message was added in version 5.8.0.) in /var/www/html/wp-includes/functions.php on line 5535

<img width="1508" alt="Zrzut ekranu 2021-07-20 o 17 46 56" src="https://user-images.githubusercontent.com/205419/126354967-ecc5c6a1-9033-4f0d-bff5-2476b5a5c9a3.png">

The rationale for the notice is discussed in depth in [Trac 53437](https://core.trac.wordpress.org/ticket/53437) and is beyond the scope of this issue.  

Here, we want to find a way of maintaining compatibility of the existing plugins with the older **and** newer versions of WP without setting the notice. 

* On WP 5.7 or lower enqueuing `wp-editor` doesn't trigger the notice at all 👍 
* On WP 5.8 or higher enqueuing `wp-editor` triggers the notice and encourages a refactor to stop relying on the `wp-editor` in favor of `wp-block-editor` and other scripts where the universal parts of `wp-editor` were moved. The problem is that such a refactor could conflict with WP 5.7 and lower.

As @peterwilsoncc noted, this could be solved with a shim for backwards compatibility. I propose such a shim here:

```php
if ( ! wp_script_is( 'legacy-editor-shim' ) ) {
	if ( wp_script_is( 'wp-block-editor' ) ) {
		wp_register_script( 'legacy-editor-shim', false, [ 'wp-block-editor', 'wp-server-side-render' ] );
		wp_add_inline_script(
			'legacy-editor-shim',
			'window.wp.editor = Object.assign( window.wp.editor || {}, window.wp.blockEditor, window.wp.serverSideRender );
			window.wp.editor.Editable = window.wp.blockEditor.RichText;',
			'after'
		);
	} else {
		wp_register_script( 'legacy-editor-shim', false, [ 'wp-editor' ] );
	}
}
```

With that code in place, the plugins could simply swap the `wp-editor` for `legacy-editor-shim` and enjoy `window.wp.editor` API compatible with both older and newer versions of WordPress.

I considered adding that snippet into core, but it simply wouldn't work: It would only be released in WordPress 5.8.1, 5.7.3, but it wouldn't be there in older versions like 5.8.0 or 5.7.2.

I think that each plugin would have to ship that shim individually. The first `if` would conveniently prevent conflicts between different plugins containing the same shim.

I am not excited about such a resolution, but I had no better ideas. What do y'all think?

cc @noisysocks @talldan @draganescu @bobbingwide

**Comment by kienstra** [comment]
Thanks for opening this, seeing the same issue in our plugin.

**Comment by johnstonphilip** [comment]
Just noting a few of the problems that have popped up in Genesis Blocks when we remove the `wp-editor` dependency:

- TypeError: Cannot read property 'getEditorSettings' of null
- TypeError: Cannot read property 'canUserUseUnfilteredHTML' of null

Those are coming from these lines:
```
const { canUserUseUnfilteredHTML } = select( 'core/editor' );
```

And
```
const getSettings = wp.data.select( 'core/editor' ).getEditorSettings();
```

Are there ways to get those values on the widgets page?

**Comment by johnstonphilip** [comment]
I was able to get the settings I needed (imageSizes) from the `core/block-editor` package like this:
`const getSettings = wp.data.select( 'core/block-editor' ).getSettings();`

I haven't yet found how to get `canUserUseUnfilteredHTML`

**Comment by cabrerahector** [comment]
Seeing this notice on one of my plugins as well. It uses the ServerSideRender component to render stuff.

So, basically to fix the notice we should be using this shim with our plugins @adamziel?

**Comment by bobbingwide** [comment]
@cabrerahector 

> Seeing this notice on one of my plugins as well. It uses the ServerSideRender component to render stuff.

I have a number of plugins with blocks that use ServerSideRender.
For my blocks which are built using `wp-scripts` I have changed the import for ServerSideRender from

```
import { ServerSideRender } from '@wordpress/editor'; 
```
to
```
import ServerSideRender from '@wordpress/server-side-render';
```

This removes the dependency. 

See https://github.com/bobbingwide/bobbingwide/issues/30#issuecomment-883282378

For the plugins which are built using older style code one pragmatic solution is to disable the doing it wrong logic.

```
remove_filter( 'admin_head', 'wp_check_widget_editor_deps' );
```
In my opinion the "doing it wrong" message is itself "doing it wrong". 
It only covers a small percentage of the possible reasons for the dependency on `wp-editor`.

See https://github.com/bobbingwide/bobbingwide/issues/30#issuecomment-880986396

**Comment by adamziel** [comment]
> I was able to get the settings I needed (imageSizes) from the `core/block-editor` package like this:
> `const getSettings = wp.data.select( 'core/block-editor' ).getSettings();`
> 
> I haven't yet found how to get `canUserUseUnfilteredHTML`

I managed to get it like that: `wp.data.select( 'core/block-editor' ).getSettings().__experimentalCanUserUseUnfilteredHTML`

**Comment by adamziel** [comment]
@bobbingwide 

https://github.com/WordPress/gutenberg/blob/eaf3f8b58b26e30c9a77fb0e2bafeda8e0462c0e/packages/editor/CHANGELOG.md#L175-L181

**Comment by adamziel** [comment]
@bobbingwide 

> ServerSideRender (...) only covers a small percentage of the possible reasons for the dependency on wp-editor.

You are absolutely right! I see how this transition may seem like an unnecessary hassle that just requires extra effort to deal with. I think I failed to provide more context here so let me make up for it now.

[@wordpess/editor](https://www.npmjs.com/package/@wordpress/editor) (or wp-editor) is a module you want to use when editing WordPress posts. This is what it says on the npm page:

> Having an awareness of the concept of a WordPress post, it associates the loading and saving mechanism of the value representing blocks to a post and its content. It also provides various components relevant for working with a post object in the context of an editor (e.g., a post title input component). This package can support editing posts of any post type and does not assume that rendering happens in any particular WordPress screen or layout arrangement.

Historically, it exposed plenty of general-purpose components such as `ServerSideRender`, `RichText`, `BlockControls` and such. This made sense because Gutenberg was only used as a post editor. This was also a perfect reason to have the editor module as a dependency – how would one work with Gutenberg without all these utilities?

Now, at one point it became apparent that Gutenberg will also be a foundation for other editors such as the widgets editor, navigation editor, full site editor etc. Since the widgets editor is completely separate from the post editor, it doesn't make sense for it to depend on post-specific things. So at one point things started becoming deprecated in `@wordpress/editor` and moved to other, more generic packages:

* [In Gutenberg 9.3.0 ServerSideRender 
was moved to `@wordpress/server-side-render`](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/CHANGELOG.md?plain=1#L181)

https://github.com/WordPress/gutenberg/blob/eaf3f8b58b26e30c9a77fb0e2bafeda8e0462c0e/packages/editor/CHANGELOG.md#L181

* [in Gutenberg 9.4.0 many components such as `RichText` or `InnerBlocks` were moved to `@wordpress/block-editor`](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/CHANGELOG.md?plain=1#L32)

https://github.com/WordPress/gutenberg/blob/eaf3f8b58b26e30c9a77fb0e2bafeda8e0462c0e/packages/editor/CHANGELOG.md#L32-L50

Since they're deprecated in `@wordpress/editor`, at some point they will be removed from that module entirely.

Now, there is also a situation with TinyMCE conflicting with `@wordpress/editor` which is a real problem inside of the widgets editor. Trac [ticket 53437](https://core.trac.wordpress.org/ticket/53437) contains the entire context for that so I'll just leave that link here. Tl;dr is that TinyMCE, which we use in the widgets editor, historically was available under `window.wp.editor`, but the `@wordpress/editor` package unfortunately got assigned the same name – hence the conflict. If you have a more convenient solution to offer, by all means feel free to comment on that issue.

---

The major point here is that, while inconvenient, the rationale behind that notice is:

* We are in the widgets editor.
* `@wordpress/editor` stands for the post editor – a different editor than the widgets editor.
* Your blocks may be used in many different contexts. If you want them to work in the widgets editor, you shouldn't specifically rely on the post editor.

I wonder if this may be just a case of poor choice of words inside the notice. How about summarizing these last three points and, perhaps, linking to this issue? cc @noisysocks @draganescu 

---

> For the plugins which are built using older style code one pragmatic solution is to disable the doing it wrong logic.
> remove_filter( 'admin_head', 'wp_check_widget_editor_deps' );

Sure, this is a reasonable workaround to make things "just work" for now in your plugin 👍 

It has a few downsides I can think of:

* It would hide the notice generated by other plugins
* It doesn't address the reliance on deprecated exports that may stop working at one point
* It doesn't remove the dependency on post editor in the context of widgets editor

So keep in mind it's a trade-off. As any trade-off, it may or may not be worth taking – you are the one to decide.

**Comment by peterwilsoncc** [comment]
> I considered adding that snippet into core, but it simply wouldn't work: It would only be released in WordPress 5.8.1, 5.7.3, but it wouldn't be there in older versions like 5.8.0 or 5.7.2.
> 
> I think that each plugin would have to ship that shim individually. The first `if` would conveniently prevent conflicts between different plugins containing the same shim.

Having thought about it for a few days, I think documenting a code snippet similar to this is the best solution over trying to add something to core -- as you say, it will be missing for versions 5.2 - 5.8.0 so there isn't much point.

Key points for the docs:

* Don't shim for plugins supporting a minimum WP version of 5.2 or later: use the new library
* I'd probably avoid suggesting using the shim in the `wp` namespace, just to avoid recommending developers  encroach on WordPress reserved words/locations.

FWIW, it's [very similar to the approach](https://plugins.trac.wordpress.org/browser/compact-archives/tags/4.1.0/inc/compact-archives.php?marks=187-223#L187) I took on one of the plugins in which I wanted to support the full range of WP versions with the block editor.

In terms of the shim itself, it might be easier to test if `wp-block-editor` is registered rather than using a version comparison. Obviously this occurred to me after I wrote the code I linked to above ;)

**Comment by adamziel** [comment]
> I think documenting a code snippet similar to this is the best solution over trying to add something to core

Where would you document that? Personally I think that release notes + blocks docs on WordPress.org are both a good place for that. I'm happy to create a PR for that.

> Don't shim for plugins supporting a minimum WP version of 5.2 or later: use the new library

Wait, did you mean 5.8? @peterwilsoncc 

> I'd probably avoid suggesting using the shim in the wp namespace, just to avoid recommending developers encroach on WordPress reserved words/locations.

Good idea! I just updated that snippet.

**Comment by peterwilsoncc** [comment]
> Wait, did you mean 5.8? @peterwilsoncc

No, I meant 5.2 as that is when the packages were split. It's only plugins supporting earlier versions of WP that need the shim.

> Where would you document that?

Probably in the [backward compatibility section](https://developer.wordpress.org/block-editor/how-to-guides/backward-compatibility) of the block editor handbook. It'd be good to let the plugin team know too so they can link to it in the plugin handbook (I'm not sure which page of that is most appropriate).

**Comment by adamziel** [comment]
> No, I meant 5.2 as that is when the packages were split. It's only plugins supporting earlier versions of WP that need the shim.

Right, I got confused :-) thanks!

**Comment by adamziel** [comment]
I don't think there's anything left to do here so I am closing this issue.
