### ISSUE TITLE
High-severity security vulnerability on current React Native version (0.64.0)

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#33588]
## Description

**Vulnerability details: https://github.com/advisories/GHSA-7f53-fmmv-mfjv**

GitHub notified about a high-security issue that was introduced in React Native version 0.59.0 and that is fixed in 0.64.1.

It would be nice to upgrade the React Native version to 0.64.1 or the last 0.64.X (0.64.2) to address this issue, here is some info about the changes between versions that will help us to proceed with the process:

- [Changes between 0.64.0 and 0.64.1](https://react-native-community.github.io/upgrade-helper/?from=0.64.0&to=0.64.1)
- [Changes between 0.64.0 and 0.64.2](https://react-native-community.github.io/upgrade-helper/?from=0.64.0&to=0.64.2)
- [0.64.1 changelog](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0641)
- [0.64.2 changelog](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0642)

The only change is the React Native version so most likely the upgrade should be straightforward but keep in mind that we also need to update all the dependencies forks:

- react-native-svg
- react-native-keyboard-aware-scroll-view
- react-native-gesture-handler
- react-native-video
- react-native-linear-gradient
- react-native-hsv-color-picker
- react-native-safe-area-context
- react-native-slider
- react-native-get-random-values
- react-native-masked-view
- react-native-screens
- react-native-reanimated
- react-native-prompt-android

## Step-by-step reproduction instructions

N/A

## Expected behaviour

N/A

## Actual behaviour

N/A

## Screenshots or screen recording (optional)

N/A

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: N/A
- Operating system: N/A
- WordPress app version: N/A

**Comment by gziolo** [comment]
Any plans to update React Native to v0.65 (https://reactnative.dev/blog/2021/08/06/version-065) in the upcoming days?

**Comment by skorasaurus** [comment]
0.66.2 is now used; can this be closed?

**Comment by geriux** [comment]
I'll close this since we are currently using `0.66.2`
