### ISSUE TITLE
Admin manifest fails to be created if admin bar is not present on the page

### ISSUE THREAD

**Issue by pierlon** [WordPress/gutenberg#33591]
## Description
If the admin bar is not present on an admin page, the admin manifest script fails with the error:

```
Uncaught TypeError: Window.getComputedStyle: Argument 1 is not an object.
```

That error can be traced back to here:

https://github.com/WordPress/gutenberg/blob/34d1a96007103cca1cad27bf74de92952f911544/packages/admin-manifest/src/index.js#L109-L110

I experienced this error when navigating to the Onboarding Wizard in the AMP for WordPress plugin.

## Expected behaviour

Admin manifest should still be created if admin bar is not present on the page.

## Actual behaviour

Admin manifest is not created if admin bar is not present on the page.

## Screenshots or screen recording (optional)

![image](https://user-images.githubusercontent.com/16200219/126462074-182ee94b-a5e0-4ac1-98ea-594fbdffe54a.png)

## WordPress information
- WordPress version: 5.8
- Gutenberg version: 11.1.0
- Are all plugins except Gutenberg deactivated? No, the AMP for WordPress plugin is activated
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Linux
- Browser:Firefox 90

**Comment by westonruter** [comment]
Introduced in https://github.com/WordPress/gutenberg/pull/33102. 

I suppose it should check if `adminBar` is `null`, and if so, use default values for `color` and `backgroundColor`. 

IMO, the PWA icon shouldn't be using the WP logo anyway, but rather it should be using the site icon: https://github.com/GoogleChromeLabs/pwa-wp/issues/295#issuecomment-883886363

See also https://github.com/GoogleChromeLabs/pwa-wp/issues/569. 

cc @ellatrix

**Comment by ellatrix** [comment]
@pierlon Could you share a screenshot of the page? Is the admin **menu** visible on the page?

**Comment by westonruter** [comment]
@ellatrix No, neither the admin menu nor the admin toolbar are shown on this page.

**Comment by westonruter** [comment]
It's a full-screen "wizard". In the AMP plugin, you can access it by activating and navigating to the onboarding wizard. I recall Yoast and WooCommerce have something similar.
