### ISSUE TITLE
Idea for block registry.

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#336]
Hi, just throwing out some ideas on the block registering API.

1. Currently block types are created via `wp.blocks.registerBlock( slug, settings )` which returns the block and also adds the block as a key, value pair to the somewhat global `blocks`.  This is a coupling that I do not think should be made.  I would recommend the creation of a block to be handled in a function `blockType( slug, settings )` ( or preferably just settings ).  Then the registry of blocks can be another factory function that creates registries of blocks, which can have the method `registerBlock( block )` on them.

This will make testing a lot easier/cleaner and will also create a bit more flexibility in the code for unforeseen future needs.

**Comment by nylen** [comment]
One drawback of this approach for clients would be that it's no longer possible to register a block in a single function call.

It looks like the proposed `blockType` function would either be `Object.assign` (or nothing, if the slug is included in the settings).  Maybe with some validation logic, but this validation would also need to be repeated inside `registerBlock`.

Given that, it's hard for me to see the advantages of pulling this operation out into two functions.

**Comment by BE-Webdesign** [comment]
>One drawback of this approach for clients would be that it's no longer possible to register a block in a single function call.

Yup, definitely.  I was thinking in the future there may come a point where two instances of the editor may need exist and will need to have different blockTypes registered to them. So for now we can probably close this out.  It can be done then, if it is ever needed.
