### ISSUE TITLE
Google Maps Block

### ISSUE THREAD

**Issue by TheRadicalDreamer** [WordPress/gutenberg#33606]
## What problem does this address?

It is really complicated to get a responsive google map iframe. Specially for common people.

## What is your proposed solution?

There should exist a google maps block that let you enter an address, confirm it, and then show a map with a pin.
This map should be responsive, because many solutions out there are not.

Second, it should allow you to set the type of map, like: streets, satellite, topography (think about the trekking lovers and sites of national parks.)

Google maps have this solution perfectly done, and should be copied.

When you lookup for an address (on web) click share and it will send you to a window to set things.
![image](https://user-images.githubusercontent.com/11801254/126539838-582de99e-4d0f-4b31-8966-24b8273519f4.png)

**Comment by talldan** [comment]
This is a tricky one @avagp because it means that WordPress, an open source project, is specifically endorsing and encouraging google maps over the other mapping products out there. There's a political aspect to that decision.

There's also a privacy aspect, since no doubt google would be collecting the data of WordPress users.

I think that's why this would generally be considered something to be implemented by a plugin, rather than something implemented by WordPress core.

Perhaps open source map alternatives could be considered for a map block. I'm not really educated on what the options are though.

**Comment by getdave** [comment]
I agree with Dan here. I doubt a _Google_ Maps block will ever be in Core. An open source alternative might be however. 

We could consider [MapLibre](https://maplibre.org/) which is the open source alternative to [Mapbox which recently rescinded it's open source license](https://wptavern.com/mapbox-gl-js-is-no-longer-open-source).

If you specifically need Google Maps then various Plugins offer an integration [including Jetpack](https://wordpress.com/support/wordpress-editor/blocks/map-block/).

**Comment by TheRadicalDreamer** [comment]
I get it, but how does that there is a youtube block and a vimeo block over
other video platforms?

**Comment by getdave** [comment]
> how does that there is a youtube block and a vimeo block ove

Those blocks are actually variations of the Embed block. Anything that exposes an [oEmbed API](https://oembed.com/) can be embedded in this fashion. The specific variations you mention are really just conveniences.

A map block would likely not function in the same way and would require a deeper integration. For example, Google Maps requires an API key which necessitates jumping through several layers of complex developer-focused documentation to access. That's not something that Core can sustain but it's perfect territory for a 3rd party Plugin, of which there are many.

I hope that helps to answer your question? If not, then I'd encourage you to raise your query in the next [Core Editor chat in WordPress Slack](https://make.wordpress.org/chat/) - perhaps in the `Open Floor` section.

**Comment by getdave** [comment]
I'm going to close out this Issue now as it's specifically about Google Maps. We can discuss an API Key free open maps solution in a new Issue if that's desirable.
