### ISSUE TITLE
Mobile Editor and web editor are out of sync after a theme change. 

### ISSUE THREAD

**Issue by chipsnyder** [WordPress/gutenberg#33608]
## Description
The web editor appears to be able to load certain color values from previous themes. This is the block HTML from the example below 

```
<!-- wp:paragraph {"backgroundColor":"green"} -->
<p class="has-green-background-color has-background">New colour</p>
<!-- /wp:paragraph -->
```
It would be ideal if we can figure out where these values are pulled from so that the mobile editor and preview are in sync. 

📓 I'm not sure that this is a bug on the mobile editor or a bug for GSS as a whole.

## Step-by-step reproduction instructions
1. Select a theme such as Twenty Twenty-One
2. Create a new post:
    - Select a color setting such as setting the background color of a paragraph block to Green
3. Publish the Post
4. Change the theme to something else such as Spearhead
5. Return to the post
    - Notice that the color in the editor has returned to the default values
6. Preview the Post
    - Notice that the color is shown with the old theme's color settings.

## Expected behavior
The Editor should match the appearance of Preview.

## Actual behavior
Preview somehow is retaining the colors from the previous theme. 

## Screenshots or screen recording (optional)
| Mobile Editor | Preview |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3384451/126541691-a71c26cb-ffa3-411d-941c-1d49134e6f2f.png) | ![image](https://user-images.githubusercontent.com/3384451/126541708-a73ab4cc-9c61-48b5-99d5-842fd8197ae5.png) |

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 11.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes and then a DotCom theme

## Device information
- Device: iPhone 12 ant Pixel 3a
- Operating system: iOS 13.5.1 and Android 11.0
- WordPress app version: 17.8 betas

**Comment by chipsnyder** [comment]
@enejb @geriux 

I’m not entirely sure yet which experience is “wrong” since the color displayed in the preview(and web) is now from an old theme selection but can we investigate this as part of GSS phase 2?

**Comment by geriux** [comment]
> can we investigate this as part of GSS phase 2?

We'll investigate it 👍

**Comment by youknowriad** [comment]
Just tested this again. I can't reproduce the issue, both frontend and backend don't render the color when you switch themes.
