### ISSUE TITLE
Social Icons Block should have Phone as an option

### ISSUE THREAD

**Issue by TheRadicalDreamer** [WordPress/gutenberg#33609]
## What problem does this address?

I know the mobile phone number is not a social network, but it is commonly used in the same place as social icons

## What is your proposed solution?

There should be a phone on the social icons list. Just like email is.
![image](https://user-images.githubusercontent.com/11801254/126545439-62e77557-f1c1-4555-b680-e5982f6978c4.png)

**Comment by TheRadicalDreamer** [comment]
And Whatsapp also by the way

**Comment by jasmussen** [comment]
This seems to be a duplicate of #32890, is that right?

**Comment by TheRadicalDreamer** [comment]
Yes. But I also mentioned WhatsApp as a missing icon

**Comment by jasmussen** [comment]
Cool, thanks. In that case we can close this one in favor of #32890 (phone icon), and #30378 (Whatsapp icon.)

**Comment by loyukfai** [comment]
Thanks for mentioning issue #30378, would we be so lucky to see these added in the next release? 😊
