### ISSUE TITLE
iOS - cursor hidden when editing on screen keyboard appears

### ISSUE THREAD

**Issue by tg-ephox** [WordPress/gutenberg#3360]
## Issue Overview

When I tap on a paragraph block at the bottom of the viewport (where the on screen keyboard will appear) the page isn't scrolled so the cursor is hidden. __Requires a HTML or Code block to be in the Post also (or any block rendering a TextareaAutosize.__

![ios-cursor](https://user-images.githubusercontent.com/30682649/32478208-2c727ce0-c3cf-11e7-9368-ac7146c6dd99.gif)

## Steps to Reproduce (for bugs)

1. Create post with HTML block and Paragraph 
2. Add enough text to the Paragraph so that it can be tapped in the area where keyboard will appear
3. Tap the Paragraph block (to edit) at the bottom of the viewport (where the keyboard will cover it)
4. Page doesn't scroll so cursor is hidden by the keyboard.

iOS (device or simulator)

## Expected Behavior

Page is scrolled so that cursor is visible

## Current Behavior

Page isn't scrolled and keyboard hides cursor

## Possible Solution

This is an issue in `react-autosize-textarea` where `this.currentValue` is not initialised so `componentDidUpdate` dispatches an un-necessary update event (https://github.com/buildo/react-autosize-textarea/blob/master/src/TextareaAutosize.js#L108).

Correcting this would fix the immediate issue but leaves 2 more... 

Firstly the Toolbar will now scroll offscreen when the on screen keyboard appears. (TinyMCE mobile hit the same issue but the solution was complex)

Secondly when the content of a `TextareaAutosize` is changed it scrolls the page as well, in the same way that is exhibited in this issue (the un-necessary update event).

I will investigate more in the `autosize` library that `TextareaAutosize` uses to see if a fix can be found.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by tg-ephox** [comment]
Can replicate `autosize` issue [here](http://output.jsbin.com/jujasez) (on iOS and on screen keyboard)

* Tap the text area
* Type on the on screen keyboard
* Page scrolls and hides text area

**Comment by tg-ephox** [comment]
`TextareaAutosize` appears to not be the only issue.  If I replace `TextareaAutosize` with `textarea` a problem still exists the first time I select a Paragraph in the area where the on screen keyboard will be shown.

In the following video I first tap a paragraph block in the area above where the keyboard will be shown and the pages scrolls up as expected.

Next I tap a paragraph block in the area below where the keyboard will be shown and the page doesn't scroll as expected the first time, but the second time and onwards it works as expected (for that paragraph)...

![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/30682649/32644591-3af58ec2-c62e-11e7-816b-48632ce7bf49.gif)

**Comment by tg-ephox** [comment]
If I remove [this](https://github.com/WordPress/gutenberg/blob/ceb4e69b9d90657eef12ca71ac077723d8019489/editor/modes/visual-editor/block.js#L260) line then it works as expected, not that this is a solution but it appears that somewhere that is manually setting focus is causing this issue...

**Comment by jorgefilipecosta** [comment]
Closing this PR for now as it duplicates https://github.com/WordPress/gutenberg/issues/2601 ( already existing) and  https://github.com/WordPress/gutenberg/issues/4731 (more recently created to collect mobile input behaviors).
Thank you for reporting and analyzing this @tg-ephox It should be solved soon with https://github.com/WordPress/gutenberg/pull/4775.
