### ISSUE TITLE
Featured Image block: Add an option to link to the post 

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#33602]
## What problem does this address?
When used in the query block it would be useful to be able to link the featured image to the post. 

## What is your proposed solution?
We should add an option to the block to link to the post like we do for the Post Title block.

**Comment by Mamaduka** [comment]
Hi, @scruffian

This featured was introduced in #25714.

## Screenshot
![CleanShot 2021-10-07 at 11 01 52](https://user-images.githubusercontent.com/240569/136335257-616ed11a-0eaa-4cc4-88ba-06b403cd64c6.png)

**Comment by scruffian** [comment]
Great!
