### ISSUE TITLE
Legacy Custom HTML widget CodeMirror has broken styles

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#33604]
## Description
CodeMirror for editing the Legacy Custom HTML widget has broken styling. See screenshot below.

## Step-by-step reproduction instructions
1. Activate Classic Widgets plugin.
2. Add Custom HTML widget.  
![image](https://user-images.githubusercontent.com/6892634/126535867-247fc913-76b8-4973-9db3-f1735b5513ef.png)
3. Deactivate Classic Widgets plugin.
4. Edit Custom HTML widget.  
![image](https://user-images.githubusercontent.com/6892634/126536024-d7d9d48f-902e-4909-b64b-eebc1dcb9856.png)

Note: at first the CodeMirror doesn't show content until it's focused:
![image](https://user-images.githubusercontent.com/6892634/126537700-7192b63a-3f2c-48b3-91b4-b5f4c2698c46.png)

Note 2: When Duplicating the block the second CodeMirror is styled correctly (except rather large font size):
![image](https://user-images.githubusercontent.com/6892634/126537594-48c1e4ad-b624-4039-923c-51062c58bb2c.png)
After page reload the duplicated CodeMirror is broken as well.

Note 3: My OS scrollbar width is increased with "Winaero Tweaker", could be a contributor to this.

## WordPress information
- WordPress version: 5.8
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 91

**Comment by talldan** [comment]
Thanks for reporting this. This bug is already being tracked in #33479, unfortunately it was reported just a little late for WordPress 5.8, but a fix is being targeted for 5.8.1.

**Comment by webbizagency** [comment]
Hi,
The bug is still there in WordPress 5.8.1 for information. It has been added to the WordPress 5.8.2 milestone on 9 Sep.

**Comment by webbizagency** [comment]
This is a workaround until the 5.8.2, you can add this in css/admin.css
`.CodeMirror pre { padding: 0 0 0 50px !important }`

**Comment by ktmn** [comment]
> a fix is being targeted for 5.8.1

@talldan Still broken for me with WP 5.9:

![image](https://user-images.githubusercontent.com/6892634/151127952-f323d87e-9589-4fc2-b6cf-a87c3442f8c8.png)

**Comment by talldan** [comment]
@ktmn Yes, unfortunately the issue #33479 is open and still needs a developer to work on it.

Please could you use that issue for commenting, as this one is closed.
