### ISSUE TITLE
Create Block: Improve readability of `save` attribute in `registerBlockType` call

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#33613]
## Description
When using the `@wordpress/create-block` package, the `registerBlockType` function is missing the `save:` property name before the save method. This leads to blocks failing to save (I learned an hour later…).

## Step-by-step reproduction instructions
1. Run `$ npx @wordpress/create-block test`

## Actual behaviour
In `/test/src/index.js`, I have the following (note the "save" line second-to-last):

```
registerBlockType( 'create-block/test', {
	/**
	 * @see ./edit.js
	 */
	edit: Edit,

	/**
	 * @see ./save.js
	 */
	save,
} );
```

## Expected behaviour
```
registerBlockType( 'create-block/test', {
	/**
	 * @see ./edit.js
	 */
	edit: Edit,

	/**
	 * @see ./save.js
	 */
	save: save,
} );
```

## WordPress information
- WordPress version: 5.8
- Gutenberg version: Not Installed
- Are all plugins except Gutenberg deactivated? Almost
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: n/a

**Comment by gziolo** [comment]
```js
{
    save,
}
```

It's a valid syntax. It uses the object property value shorthand syntax introduced in ES2015 (ES6). See a related article:

https://alligator.io/js/object-property-shorthand-es6/

Can you share more details about the error you see in the browser when saving your custom block?

**Comment by mrwweb** [comment]
@gziolo Thank you for this clarification. I now realize that in revising the code from create-block to try to support multiple blocks, I must have broken this. (I eventually figured the multiple blocks thing out thanks to a comment you left elsewhere, so thanks!)

So I guess this isn't a bug out of the box but it feels both easy to break and also confusing that it's inconsistent between `edit` and `save`. So I think I'd suggest adding it for clarity and stability still.

**Comment by gziolo** [comment]
> So I guess this isn't a bug out of the box but it feels both easy to break and also confusing that it's inconsistent between `edit` and `save`. So I think I'd suggest adding it for clarity and stability still.

Right, we can do it if that makes it easier to follow the code 👍🏻

**Comment by mrwweb** [comment]
> if that makes it easier to follow the code

Since so many examples do explicitly include `save: ` and it's not consistently used in other places, I think it would help. It would definitely make the code more robust if people innocently want to rename the `save` function. Also, I checked and the transpilation adds `save: ` explicitly anyway, so I'm really not quite sure what the arguments in favor are.

**Comment by gziolo** [comment]
Based on the discussion in #34548, @mkaz and I decided we will leave the syntax as is. When trying to apply the changes proposed we run into the issue with the default linting rules used by `@wordpress/scripts`. It looks like the coding guidelines favor the object shorthand notation.
