### ISSUE TITLE
Issues with Gutenberg block placements

### ISSUE THREAD

**Issue by nj0y** [WordPress/gutenberg#33611]
## Description
After wordpress/gutenberg update the editor in back-end has blocks showing outside of the page margin/parameters, and other weird placements for the blocks. (see screenshot).

## Step-by-step reproduction instructions
1. Go to backend
2. Select new post
3. Problem immediately visible on empty post with placement of starting paragraph block
4. Upon adding other blocks they move about the editting area.

## Expected behaviour
Normally all blocks would be aligned perfectly below each other with clear spacing on both sides of the page. 

## Actual behaviour
Blocks get placed in weird locations within the editor. Problem persists even in default theme and/or with plugins disabled. Does not seem to affect frontend appearance or functionalities. 

![spacing issue](https://user-images.githubusercontent.com/87780402/126546042-40ce99ae-19da-4a62-8145-7faf9c3b9aa8.png)

![block placement](https://user-images.githubusercontent.com/87780402/126547262-fa6ddc78-414c-4c84-944f-33ef0f01186c.png)

Despite it being (what seems to be a) mostly cosmetic issue during editting, I would like to know if there's a fix for this, or some conflict I'm missing. 

## WordPress information
- WordPress version: 5.8
- Gutenberg version: 10.7
- Are all plugins except Gutenberg deactivated? Yes (during testing, not anymore)
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes (during testing, not anymore)

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 91.0.4472.124

**Comment by getdave** [comment]
Thanks for the report.

Can you confirm whether this happens:

* When the Gutenberg Plugin is disabled?
* Using the latest Gutenberg Plugin?

Many thanks.

**Comment by nj0y** [comment]
Issue is solved. I set up a clean staging environment and problem is fixed. Must've been some theme residuals or other settings that I hadn't checked.
