### ISSUE TITLE
Draft posts are not previewable if the draft was previously published

### ISSUE THREAD

**Issue by TylerBarnes** [WordPress/gutenberg#33616]
## Description
Content doesn't update when previewing a draft when that draft was previously public.

## Step-by-step reproduction instructions
1. Open the edit page for a brand new post
2. Add a title and hit preview in a new tab
3. Notice the preview works great
4. Publish the post
5. Update the title and preview a couple times
6. Notice preview still works great
7. Switch the post to a draft
8. Update the title and preview
9. Notice no matter how many times you preview it shows the content from the last published version of the post and the preview doesn't update as it should

## Expected behaviour
Draft posts should always work with previews even if they were once published posts.

## Actual behaviour
Draft posts aren't previewable if they were previously published posts.

## WordPress information
- WordPress version: 5.8
- Gutenberg version: Whatever ships with WP 5.8
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: macOs 11.4
- Browser: Chrome 91.0.4472.164

**Comment by TylerBarnes** [comment]
I should add that this isn't an issue with the classic editor.

**Comment by getdave** [comment]
I was able to replicate this and it does seem to be a problem:

https://user-images.githubusercontent.com/444434/126782074-90a89e36-3e4e-4935-ab86-ccddd32e4929.mov

Once a post moves back to draft then the preview should be whatever is in the Editor, not what was previously published.

**Comment by getdave** [comment]
Digging into this a little, removing this line appears to fix the problem...

https://github.com/WordPress/gutenberg/blob/aa22cd7714bbbd63b95dd9cfab0a894cba6d5ec2/packages/editor/src/store/selectors.js#L908

As the call to `getAutosaveAttribute` is deprecated I'm going to follow the upgrade path to see if we can fix this.

**Comment by cpapazoglou** [comment]
👋 @getdave! Do you think those are related:

https://github.com/WordPress/gutenberg/issues/33758
https://github.com/WordPress/gutenberg/issues/21191

**Comment by getdave** [comment]
> 👋 @getdave! Do you think those are related:
> 
> #33758
> #21191

Very likely. I never managed to get the to the bottom of it.

**Comment by jorgecontreras** [comment]
I would like to work on this issue
