### ISSUE TITLE
Deleting Focal Point Value Setting Crashes Block

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#33617]
## Description
When deleting the value in a focal point input for the Media & Text or Cover block, the block crashes with the error "This block has encountered an error and cannot be previewed."

## Step-by-step reproduction instructions
1. Insert a Cover or Media & Text Block
2. Delete the value of the "Left" or "Top" focal point setting using `Backspace` or `Delete` keys
3. Block Crashes

## Expected behaviour
Block does not crash. Ideally, the focal point uses the default value of 50% rather than 0% when there is no value in the Left or Top settings field.

## Actual behaviour
Block crashes with error:

> "This block has encountered an error and cannot be previewed."

## Screenshots or screen recording (optional)
![animated GIF image showing the process described in step-by-step instructions with the Cover block](https://user-images.githubusercontent.com/1238696/126572251-ba6ce6d4-14ca-4366-8434-5ef014ea47a0.gif)

## Code snippet 
The block appears to crash when the background-position gets set to `NaN`:

```html
<!-- wp:cover {"url":"https://playground.local/wp-content/uploads/2020/09/2012-04-22_11-21-16_856.jpg","id":8,"focalPoint":{"x":null,"y":"0.50"}} -->
<div class="wp-block-cover has-background-dim"><img class="wp-block-cover__image-background wp-image-8" alt="" src="https://playground.local/wp-content/uploads/2020/09/2012-04-22_11-21-16_856.jpg" style="object-position:NaN% 50%" data-object-fit="cover" data-object-position="NaN% 50%"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
```

Console:

> Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. - react-dom.min.js:125:24
>     Ja https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:224
>     enqueueSetState https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:214
>     setState https://playground.local/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:20
>     componentDidUpdate https://playground.local/wp-includes/js/dist/components.min.js?ver=72eccad5b704ebf3e45a24b4da1773fe:10
>     oj https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:127
>     Aj https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:160
>     unstable_runWithPriority https://playground.local/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
>     Da https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
>     ab https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:154
>     Te https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146
>     Pg https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61
>     unstable_runWithPriority https://playground.local/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
>     Da https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
>     Pg https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61
>     ha https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
>     uj https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146
>     <anonymous> https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
>     ud https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:15
>     uf https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:15
>     Qd https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:42
>     sc https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
>     unstable_runWithPriority https://playground.local/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
>     Da https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
>     <anonymous> https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
>     Ei https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
>     Me https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:125
>     callback https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:139
>     Wg https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:67
>     oj https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:127
>     Aj https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:160
>     unstable_runWithPriority https://playground.local/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
>     Da https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
>     ab https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:154
>     Te https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146
>     Pg https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61
>     unstable_runWithPriority https://playground.local/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
>     Da https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
>     Pg https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61
>     ha https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
>     uj https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146
>     <anonymous> https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
>     ud https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:15
>     uf https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:15
>     Qd https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:42
>     sc https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
>     unstable_runWithPriority https://playground.local/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
>     Da https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
>     <anonymous> https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
>     Ei https://playground.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41

## WordPress information
- WordPress version: 5.8
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Firefox 91

**Comment by Mamaduka** [comment]
It looks like a bug with the `FocalPointPicker` component.
