### ISSUE TITLE
Image can be resized so small that it can't be selected anymore

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#3361]
## Steps to Reproduce
1. Add an image block (with an image)
2. Resize the image to it's smallest possible size
3. Click outside the block to deselect
4. Now you cannot select the image block anymore

Gutenberg 1.6.1 + WP 4.8.3 vagrant + chrome.

![resize noselect](https://user-images.githubusercontent.com/6073772/32492960-63ec4b82-c3bc-11e7-9f30-0161cd5132c8.gif)

Related to #3355

**Comment by mtias** [comment]
@youknowriad I thought we had added a limit here before.

**Comment by youknowriad** [comment]
Yes, we have a limit of 10px. Maybe we can do 20px.

**Comment by mtias** [comment]
Sounds sensible.
