### ISSUE TITLE
Resizing an image triggers multi-block select

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#3362]
## Steps to Reproduce (for bugs)
1. Add an image block (with an image)
2. Resize it down so it's not full width anymore
3. Resize it back up enthousiastically, expecting the grabber to hit the corner of the block, so you know it's as big as it can be.
4. Accidentally start selecting the blocks below

![resize drag select](https://user-images.githubusercontent.com/6073772/32493068-cd88a91e-c3bc-11e7-88b8-2d84d1ff8269.gif)

Gutenberg 1.6.1 + WP 4.8.3 vagrant + chrome.

## Expected Behavior
For multi-block select to be disabled while you are resizing an image.

**Comment by karmatosed** [comment]
I can recreate this too. Let's see about getting it fixed, thanks for reporting :)

**Comment by jorgefilipecosta** [comment]
Thank you for analyzing this issue @hedgefield and @karmatosed, it should be fixed with the merge of https://github.com/WordPress/gutenberg/pull/3602.
