### ISSUE TITLE
Copy - consider rewording 'overlay' color options in the navigation block

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#33640]
## What problem does this address?
The navigation block now has two additional overlay color options:
<img width="282" alt="Screenshot 2021-07-23 at 1 59 20 pm" src="https://user-images.githubusercontent.com/677833/126743764-75a38e67-c2a4-4203-b404-5ba0c9e767f9.png">

My first instinct on seeing these was that I wasn't really sure what they do. I tried changing the colors and it had no effect.

I went looking for the PR that introduced this and found #31149 and discovered that this controls the colors for submenus. I didn't have submenus, so that's why nothing happened.

The feature seems very cool, just not sure about the naming. I think users will find this confusing.

## What is your proposed solution?
Can the options be called 'Submenu text color' and 'Submenu background color'?

The block already uses the term 'submenu' for 'Show submenu indicator icons', so this would make things more consistent:
<img width="274" alt="Screenshot 2021-07-23 at 2 16 10 pm" src="https://user-images.githubusercontent.com/677833/126744023-84816c8f-5365-4409-9886-64aadc2e0b3b.png">

**Comment by talldan** [comment]
cc @jasmussen @georgeh

**Comment by jasmussen** [comment]
Good ticket, thanks for the ping. One of the tricky bits here is that at the moment, the color is used for _both dropdown menu background colors_, and _burger menu overlay menu colors_. I think the best solution is likely to let the latter inherit the former if unset, but also have its own separate color control. 

(This in turn requires a collapsed color picker as mocked up in https://github.com/WordPress/gutenberg/issues/27473#issuecomment-796773866, or we balloon the amount of color palettes in the inspector even further).

What do you think?

**Comment by talldan** [comment]
Potentially, yep. I definitely think this already exposes some shortcomings in the color system—it feels like overlay should be a completely separate element with distinct background and text color options, rather than having everything in one list of colors.

edit: Especially this swatch, it'd be nice to have a way to group background and foreground colors so that a user can see the contrast:
<img width="151" alt="Screenshot 2021-08-02 at 5 14 00 pm" src="https://user-images.githubusercontent.com/677833/127837326-72faea53-663b-478a-9664-234c9b46b321.png">

**Comment by jasmussen** [comment]
> it feels like overlay should be a completely separate element with distinct background and text color options, rather than having everything in one list

Yes, that as well. This is going to resurface as we explore mega-menu design tools. Intuitively you'd open a specific dropdown menu and see the contents of just that dropdown. But if you then change the number of columns shown, or the background/foreground/link colors, do you change those for the selected dropdown only? Or for all dropdowns in the menu?

<img width="1540" alt="04 Navigation item" src="https://user-images.githubusercontent.com/1204802/127837552-b7ec15c9-86bd-40dc-bd76-eaf1b13ce631.png">

There are adjacent issues with surfacing parent block inspector options even when a child block is selected, that might need to be the way this is ultimately addressed.

> Especially this swatch, it'd be nice to have a way to group background and foreground colors so that a user can see the contrast:

Coming back from some AFK, I'm not sure how much progress has been made on the "collapsible color picker" where the most recent mockup I know of is found [here](https://github.com/WordPress/gutenberg/issues/27473#issuecomment-796773866), but some of the behavior is described in #27331. The key aspect is we need to avoid duplicating the entire theme color palette for each property that can have a color set.

You bring up a good point about the colors shown in the collapsed panel as well, and some of the stacked color groups shown at the first link could potentially be leveraged there.

**Comment by annezazu** [comment]
This came up with the [ninth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/08/11/fse-program-testing-call-9-handling-highered-headers/#comment-1922):

> Also not sure how overlay colour settings works on the mobile menu.

Something to keep in mind is how the naming will impact what users expect these settings to do with the responsive menu option. Either way, excited to see more clarity included here and to see some ideas being shared!

**Comment by jasmussen** [comment]
Just to get the conversation flowing, in the future, colors will leverage [the ItemGroup component](https://github.com/WordPress/gutenberg/issues/35093) and be grouped like a stack of color rows. Shown here, with 3 different verbiage suggestions:
<img width="364" alt="Option 1" src="https://user-images.githubusercontent.com/1204802/138242372-e1950a41-0b85-411d-8bde-6f38cfc4ff93.png">
<img width="364" alt="Option 2" src="https://user-images.githubusercontent.com/1204802/138242380-c06a653b-7867-446d-8e30-cad5a24765ae.png">

<img width="364" alt="Option 3" src="https://user-images.githubusercontent.com/1204802/138242387-b03434d6-31fc-460b-9d40-2c55048651d8.png">

As is maybe clear from the above suggestions, the challenge is that the two last color options apply to _both_ dropdown menus, and the overlay menu opened from the 🍔 menu icon. Reconciling that with keeping the verbiage short (German usually adds 20% length) makes it tricky.

Dan suggested separate options, that could look like this:
<img width="364" alt="Option 4" src="https://user-images.githubusercontent.com/1204802/138242981-c2030235-6e6f-4481-962d-41dd7a8b3620.png">

In this one, the Overlay could still automatically inherit the color of dropdowns unless separately set, and the extra space definitely adds room for adding extra space. But by virtue of having 6 color options, this one really surfaces the need for the ItemGroup collapsing mechanism, but also might add a little confusion as to what the difference is between the last 4 options.

With the ItemGroup in place, there would also be room for help text, in case that would be useful:

<img width="364" alt="Option 5" src="https://user-images.githubusercontent.com/1204802/138243833-da837818-81ea-4110-ac0b-3722af35e174.png">

Any thoughts?

**Comment by jasmussen** [comment]
#35916 fixes this one, at least temporarily. The comment above suggests using ItemGroups, perhaps even splitting out the colors. That is something we can look at still. But in the mean time, the PR makes the labels more clear.
