### ISSUE TITLE
Dragging multiple images into an image block does not convert it to a gallery

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#3364]
## Expected Behavior
That dragging a bunch of images into an image block would convert it to a gallery block (or at least multiple image blocks).

## Current Behavior
It adds each image in one by one, replacing the previous one and cutting back and forth in an unclear order.

Gutenberg 1.6.1 + WP 4.8.3 vagrant + chrome.

![multiupload](https://user-images.githubusercontent.com/6073772/32493149-24fd12de-c3bd-11e7-9558-5c14905c7683.gif)

**Comment by youknowriad** [comment]
Dragging multiple images to the editor canvas should create galleries (that's doable using `files` transform in the Gallery block).

This could be enough if we disable the droppable zone on image blocks when you drag multiple images.

**Comment by hedgefield** [comment]
That currently also does not work in 1.6.1 🙃

**Comment by youknowriad** [comment]
Yes, It does not work yet, I was suggesting it as a way to fix this issue.

**Comment by karmatosed** [comment]
I agree this would be a good behaviour. My only concern is maybe there is a use case where someone would want separate images. We are making an assumption they want a gallery even when selected image.

**Comment by hedgefield** [comment]
I agree, that one is tricky. What we could try is showing a choice when you do that, like when a block gets locked and you have choices for overwriting or editing as html etc? Though in general it seems logical that if you only have one image block and you drag in multiple images, then it's not surprising that that would create a gallery.
