### ISSUE TITLE
[Widget Screen] Adding blocks to columns from 'Browse All' does not work as expected

### ISSUE THREAD

**Issue by sajmes** [WordPress/gutenberg#33658]
## Description

When adding a columns block in the widgets editor, adding blocks to the columns from 'browse all' does not behave as expected/how adding blocks to a column works in the regular editor. A block added from 'browse all' does not get added to the intended destination column where + was clicked. Instead it is added below the column block.

Adding blocks from the options presented in the initial block picker does work as expected. 

Additionally, the search feature does not work in 'browse all' unless you first search and then clear that search before searching again OR click somewhere outside the search field within 'browse all' to reveal all available blocks before searching.

## Expected behaviour

I expect that when clicking + in a column and clicking 'browse all' I will see a list of available blocks and can click a block in that area to add it to the destination column where + was clicked.

I expect that searching from 'browse all' will show all blocks that match my search criteria. 

## Actual behaviour

When clicking + in a column within a column block and then clicking 'browse all', I see only the column block in the 'browse all' area that slides out. I cannot see the available blocks until I click somewhere in the 'browse all' area.

Once available blocks are revealed, clicking a block does not add it to the destination column where + was clicked. Instead, it adds it below the column block as a new independent block. 

When clicking search in 'browse all' without having first clicked elsewhere in 'browse all', the search returns no results.

## Screenshots or screen recording (optional)

![Screen Capture on 2021-07-22 at 11-46-26](https://user-images.githubusercontent.com/76757079/126671617-a870635b-32ee-4803-b45b-2ac9acf94066.gif)

## WordPress information
- WordPress version: 5.8
- Gutenberg version: 11.0.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes - Twenty Twenty

## Device information
- Device: M1 Macbook Pro 
- Operating system: macOS 11.4
- Browser: Chrome 91.0.4472.114

**Comment by draganescu** [comment]
I tested and can confirm this broken behavior.

**Comment by kevin940726** [comment]
I believe this was fixed in #33802. Here's the screencast I just recorded in trunk.

https://user-images.githubusercontent.com/7753001/128123051-894b2b1e-c146-48ca-899e-9cc86362aa53.mp4
