### ISSUE TITLE
Dragging images into a gallery does not work

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#3365]
## Issue Overview
Dragging multiple images into a gallery block does nothing. Dragging in only one adds it as a separate image block either above or below the gallery block.

![galleryno](https://user-images.githubusercontent.com/6073772/32493817-8b50835c-c3bf-11e7-9387-9892e62b7c7c.gif)

**Comment by mtias** [comment]
This should be a consistent behaviour provided by an `ImageAre` reusable component that we — and any block author — can reuse.

**Comment by mtias** [comment]
Done in #3819.
