### ISSUE TITLE
FontSizePicker is not working with value type "number"

### ISSUE THREAD

**Issue by NasKadir123** [WordPress/gutenberg#33651]
## Description
After update to WordPress 5.8 version FontSizePicker doesn't support value with type of number.

## Step-by-step reproduction instructions
https://github.com/NasKadir123/textBlock here is example of a custom block. This block is working in previous versions, but not in the new one. When you change Font Size in FontSizePicker for example to "large" it works, but if you insert number inside Custom input, for example "24" then update and refresh the page it will throw the error. It has the same effect even if you don't want to use HOCs and will just have a value attribute with type number.

## Expected behaviour
It should work correctly.

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/49153601/126791873-f861438c-a5b2-469b-92f6-1cf8936a7c8b.mov
Sorry for the long pause after updating the page, my internet connection is slow.
## Code snippet (optional)
https://github.com/NasKadir123/textBlock @getdave Can you recheck it, please? Now publish and refresh the page. Thanks in advance!

## WordPress information
- WordPress version: 5.8
- Gutenberg version: 10.7
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: OS 10.15
- Browser: Firefox 89.0.1

**Comment by Mamaduka** [comment]
Thanks for reporting the issue, @NasKadir123.

I'm able to reproduce it.

**Comment by Mamaduka** [comment]
@NasKadir123 

Here's temporary fix for the issue:

```js
<FontSizePicker
	fontSizes={ fontSizes }
	fallbackFontSize={ fallbackFontSize }
	value={ fontSize.size }
	onChange={ ( value ) => {
		const fontSizeValue = value ? parseInt( value, 10 ) : undefined;

		if ( ! Number.isNaN( fontSizeValue ) ) {
			setFontSize( fontSizeValue )
		}
	} }
/>
```

I will try to create PR for `withFontSizes` HOC shortly.

**Comment by NasKadir123** [comment]
@Mamaduka Thanks a lot, will be waiting the next update.
