### ISSUE TITLE
Pasting an image URL into a paragraph creates a frankenstein block

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#3366]
Creating an empty paragraph block and pasting in the URL of an image makes the image appear correctly, but the block remains a paragraph block - not Freeform or HTML, an actual Paragraph block. It doesn't get converted to an image block. In Text View you can see the img tag is between p tags.

Gutenberg 1.6.1 + WP 4.8.3 vagrant + Chrome.

**Comment by iseulde** [comment]
Could you give an example of an image URL? If I paste an image URL, it will try to embed, but fail because there is no service handling it. Should still be added.

**Comment by hedgefield** [comment]
Ah, this has changed in 1.7, pasting it now fails and turns the empty paragraph block into an embed URL block saying `Sorry, we could not embed that content.`
