### ISSUE TITLE
Editor / Safari: Metabox panels floating over editor content area (10.7.0+)

### ISSUE THREAD

**Issue by JoshuaGoode** [WordPress/gutenberg#33668]
## Description
As of Gutenberg 10.7.0, and now WordPress core 5.8, metabox panels are no longer restricted to their editor region and are floating over the editor content area in Safari.

It seems `display` changes to `.edit-post-visual-editor` might be related.  Possibly from https://github.com/WordPress/gutenberg/pull/32581

## Prerequisites

* If the site is running a version below WordPress 5.8, install and activate Gutenberg 10.7.0 or higher.  The issue is now present in 5.8 without the need for the standalone plugin.
* Safari

## Step-by-step reproduction instructions
1. Create a post/page with multiple paragraphs worth of content.
2. Enable the Custom fields panel within editor Preferences.  Or, install a plugin such as Yoast which automatically adds and enables an editor metabox panel. 

## Expected behaviour
Metabox panels are restricted to the bottom of the editor, below body content.

## Actual behaviour
Metabox panels are floating over editor body content.

## Screenshots or screen recording (optional)
![image (1)](https://user-images.githubusercontent.com/4887830/126845013-d5649758-b161-46b4-ac03-ecec0749b70c.png)

## WordPress information
- WordPress version: Multiple, tested on 5.7.2 and 5.8
- Gutenberg version: If below version 5.8 of WP core, install and activate Gutenberg 10.7.0+
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Multiple macOS based devices.
- Operating system: Multiple versions of macOS
- Browser: Safari, tested as far back as 12.1 and as recent as 14.1

**Comment by JoshuaGoode** [comment]
## Workaround

One workaround, for now, is to hide the panels. 

1.  Access your editor preferences while in the editor by clicking **⋮** > Preferences 
2. Disable the additional panels within the Panels area. 
![image](https://user-images.githubusercontent.com/4887830/126845696-d80ec864-2614-44b7-8f2c-0c6ca123f634.png)

**Comment by talldan** [comment]
Also reported on the forums:
https://wordpress.org/support/topic/editor-issue-with-custom-fields-and-metabox-area/

**Comment by jasmussen** [comment]
Thanks for the report @JoshuaGoode. Do you have additional steps to reproduce? I can't reproduce it. Running Safari 14.1.2:

![saf](https://user-images.githubusercontent.com/1204802/127856587-06850c10-4d0e-4959-a6b2-9d727253f288.gif)

**Comment by jasmussen** [comment]
Looking further into it, I'm able to reproduce on older versions of Safari, such as version 13.

**Comment by jasmussen** [comment]
I believe I have a fix in https://github.com/WordPress/gutenberg/pull/33817.
