### ISSUE TITLE
Easy Heading adding - highlight to create a heading block

### ISSUE THREAD

**Issue by bernhardklug** [WordPress/gutenberg#33662]
## What problem does this address?
I can't just insert my text and add headings when I highlight the part.
## What is your proposed solution?
Just add a Heading option to this menu and if I highlight it and then choose heading only this part will be a new heading block.
<img width="613" alt="Screenshot 2021-07-23 at 20 06 40" src="https://user-images.githubusercontent.com/81229174/126823559-f9e31802-424e-4391-ace9-e80888d4af12.png">

**Comment by richtabor** [comment]
Hey mate, appreciate the feedback. It's not within scope to extend the toolbar with a heading control, but you can press enter, then transform the paragraph into a heading like this: 

https://github.com/WordPress/gutenberg/assets/1813435/5f003042-bfd3-49c4-b150-72d9f1655ab2
