### ISSUE TITLE
Shift-select in a group block doesn't select anything

### ISSUE THREAD

**Issue by MVColombie** [WordPress/gutenberg#33665]
## Description
Impossible to edit text after selecting several words with SHIFT key.

## Step-by-step reproduction instructions
1. Make a "group" with a text block;
2. Try to select several words using SHIF key

## Expected behaviour
Be able to do something, delete selected text, edit text block, etc.

## Actual behaviour
It's freezing the block and all blocks around. Impossible to edit nothing.

## Screenshots or screen recording (optional)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33600764/126824761-4075e79d-c641-4fc2-9fbe-c4f49cf7aeb3.gif)

## WordPress information
- WordPress version: 5.8
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes 2021

## Device information
- Device: Desktop
- Operating system: Mac OS Big Surr 11.2.2
- Browser: FireFox 90.0.2

**Comment by johngodley** [comment]
I can confirm that using the shift key inside a group doesn't work. It doesn't freeze anything for me, or cause any subsequent problems, and once I release the shift key I can continue editing. However, given that shift-select works outside of a group then it seems something in need of attention.

**Comment by them-es** [comment]
This issue should be solved once https://github.com/WordPress/gutenberg/pull/35668 has been merged 🤞
