### ISSUE TITLE
@wordpress/scripts: v17.0.0 release didn't update package.json properly

### ISSUE THREAD

**Issue by lucyllewy** [WordPress/gutenberg#33664]
## Description
Installing `@wordpress/scripts@^17.0.0` installs `eslint-plugin-markdown@^1.0.2`. The 17.0.0 release __should__ have updated this dependency to 2.2.0, but seemingly has not done so despite the `package.json` file in this repository indicating otherwise. The `package.json` file that is associated with 17.0.0 from my system is below in the code snippet section.

## Step-by-step reproduction instructions

1. `npm init`
2. `npm install @wordpress/scripts@17.0.0`
2. that's it.

## Expected behaviour
the NPM package of `@wordpress/scripts` version 17.0.0 should depend on the correct version of `eslint-plugin-markdown`

## Actual behaviour

the package depends on old, vulnerable, version of `eslint-plugin-markdown`

## Code snippet (optional)

<details>
<summary>package.json from installed @wordpress/scripts@^17.0.0</summary>

```json
{
  "_args": [
    [
      "@wordpress/scripts@17.0.0",
      "/home/dllewellyn/Development/WordPress/a-z-listing/plugins/a-z-listing"
    ]
  ],
  "_development": true,
  "_from": "@wordpress/scripts@17.0.0",
  "_id": "@wordpress/scripts@17.0.0",
  "_inBundle": false,
  "_integrity": "sha512-6cXDF9YxeylhAeTQLa5URDQKq4jiuRA3ElibQK9G9QTl3GmaUbnTj6+NP0FHXwFUrpvaKwQlTE83OaBsJ+7E6g==",
  "_location": "/@wordpress/scripts",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "@wordpress/scripts@17.0.0",
    "name": "@wordpress/scripts",
    "escapedName": "@wordpress%2fscripts",
    "scope": "@wordpress",
    "rawSpec": "17.0.0",
    "saveSpec": null,
    "fetchSpec": "17.0.0"
  },
  "_requiredBy": [
    "#DEV:/"
  ],
  "_resolved": "https://registry.npmjs.org/@wordpress/scripts/-/scripts-17.0.0.tgz",
  "_spec": "17.0.0",
  "_where": "/home/dllewellyn/Development/WordPress/a-z-listing/plugins/a-z-listing",
  "author": {
    "name": "The WordPress Contributors"
  },
  "bin": {
    "wp-scripts": "bin/wp-scripts.js"
  },
  "bugs": {
    "url": "https://github.com/WordPress/gutenberg/issues"
  },
  "dependencies": {
    "@svgr/webpack": "^5.2.0",
    "@wordpress/babel-preset-default": "^6.3.0",
    "@wordpress/dependency-extraction-webpack-plugin": "^3.2.0",
    "@wordpress/eslint-plugin": "^9.1.0",
    "@wordpress/jest-preset-default": "^7.1.0",
    "@wordpress/npm-package-json-lint-config": "^4.1.0",
    "@wordpress/postcss-plugins-preset": "^3.2.0",
    "@wordpress/prettier-config": "^1.1.0",
    "@wordpress/stylelint-config": "^19.1.0",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.2.2",
    "chalk": "^4.0.0",
    "check-node-version": "^4.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "cross-spawn": "^5.1.0",
    "css-loader": "^5.1.3",
    "cwd": "^0.10.0",
    "dir-glob": "^3.0.1",
    "eslint": "^7.17.0",
    "eslint-plugin-markdown": "^1.0.2",
    "expect-puppeteer": "^4.4.0",
    "file-loader": "^6.2.0",
    "filenamify": "^4.2.0",
    "ignore-emit-webpack-plugin": "^2.0.6",
    "jest": "^26.6.3",
    "jest-circus": "^26.6.3",
    "jest-dev-server": "^4.4.0",
    "jest-environment-node": "^26.6.2",
    "markdownlint": "^0.23.1",
    "markdownlint-cli": "^0.27.1",
    "merge-deep": "^3.0.3",
    "mini-css-extract-plugin": "^1.3.9",
    "minimist": "^1.2.0",
    "npm-package-json-lint": "^5.0.0",
    "postcss": "^8.2.15",
    "postcss-loader": "^4.2.0",
    "prettier": "npm:wp-prettier@2.2.1-beta-1",
    "puppeteer-core": "^10.1.0",
    "read-pkg-up": "^1.0.1",
    "resolve-bin": "^0.4.0",
    "sass": "^1.26.11",
    "sass-loader": "^10.1.1",
    "source-map-loader": "^0.2.4",
    "stylelint": "^13.8.0",
    "terser-webpack-plugin": "^3.0.3",
    "thread-loader": "^3.0.1",
    "url-loader": "^4.1.1",
    "webpack": "^4.46.0",
    "webpack-bundle-analyzer": "^4.2.0",
    "webpack-cli": "^3.3.11",
    "webpack-livereload-plugin": "^2.3.0",
    "webpack-sources": "^2.2.0"
  },
  "description": "Collection of reusable scripts for WordPress development.",
  "engines": {
    "node": ">=12",
    "npm": ">=6.9"
  },
  "files": [
    "bin",
    "config",
    "scripts",
    "utils"
  ],
  "gitHead": "743b70f86f1e75fd66a583bf659f2b2fe5daf1cc",
  "homepage": "https://github.com/WordPress/gutenberg/tree/HEAD/packages/scripts/README.md",
  "keywords": [
    "wordpress",
    "gutenberg",
    "scripts"
  ],
  "license": "GPL-2.0-or-later",
  "name": "@wordpress/scripts",
  "publishConfig": {
    "access": "public"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/WordPress/gutenberg.git",
    "directory": "packages/scripts"
  },
  "version": "17.0.0"
}
```
</details>

## WordPress information
- WordPress version: irrelevant
- Gutenberg version: irrelevant
- Are all plugins except Gutenberg deactivated? irrelevant
- Are you using a default theme (e.g. Twenty Twenty-One)? irrelevant

## Device information
- Device: Desktop
- Operating system: Ubuntu Linux 21.04
- Browser: irrelevant

**Comment by gziolo** [comment]
> The 17.0.0 release should have updated this dependency to 2.2.0, but seemingly has not done so despite the package.json file in this repository indicating otherwise. 

It wasn't included in the release and it's waiting for the next release:
https://github.com/WordPress/gutenberg/blob/trunk/packages/scripts/CHANGELOG.md#unreleased

You can learn more about the publishing process in the documentation:

https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/release.md#packages-releases-to-npm-and-wordpress-core-updates

We are using code from the most recent Gutenberg plugin release (with some exceptions) when publishing to npm to ensure to minimize the number of potential bugs introduced. 

> the package depends on old, vulnerable, version of eslint-plugin-markdown

@mkaz, should we do a bugfix release for the change you landed?

**Comment by lucyllewy** [comment]
Aah, I must have misread the commit logs. Sorry for the noise :-)

**Comment by mkaz** [comment]
I don't think it's necessary to do a bug fix release, unless it is causing a problem some how? The upgrade was just general maintenance to remove some deprecation warnings and to try to keep packages more up to date, there was not a specific fix or issue that required it.

@diddledan was there an issue, or did you just noticed the discrepancy?

**Comment by lucyllewy** [comment]
It's marked as a vulnerable dependency with severity "high" by npm audit

**Comment by gziolo** [comment]
Let's wrangle a release this week when the new RC version for the Gutenberg plugin is ready 👍🏻

**Comment by gziolo** [comment]
New version with the fix is now published to npm:

https://unpkg.com/browse/@wordpress/scripts@17.1.0/package.json
