### ISSUE TITLE
RichText Component not working with inline Toolbar inside InspectorControls because of z-index issue

### ISSUE THREAD

**Issue by tdesero** [WordPress/gutenberg#33666]
## Description
I am working on a custom block and I used the RichText component inside InspectorControls for this.
When I'm using my block, the Inline Toolbar for the RichText Component is not shown.
But when i disable the z-index of `.interface-interface-skeleton__content` inside the Chrome Dev-Tools it is working like expected again.

## Step-by-step reproduction instructions
Create a custom block and use `<RichText />` with inlineToolbar set to true inside `<InspectorControls />`.

## Expected behaviour
Toolbar should be shown when typing inside the RichText Component.

## Actual behaviour
Toolbar is not visible because of a wrong z-index.

## WordPress information
- WordPress version: 5.8
- Are all plugins except Gutenberg deactivated? Yes, except my own block.

## Device information
- Device: Desktop
- Operating system: macOS BigSur
- Browser: Chrome 91

**Comment by jordesign** [comment]
Hey @tdesero - I'm just checking through some older issues and wanted to see if this one is still relevant for you in your usage?

**Comment by tdesero** [comment]
It is currently not relevant anymore. Thanks for checking :)

**Comment by jordesign** [comment]
Thanks for confirming @tdesero - I'll close it up.
