### ISSUE TITLE
Site Editor: Content Pane set to 150px

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#33661]
With Gutenberg `trunk`/WP 5.8, I'm seeing the Site Editor height being set to 150px. This should fill to 100% of the edit-site-visual-editor div.

<img width="1186" alt="Screen Shot 2021-07-23 at 10 52 20 AM" src="https://user-images.githubusercontent.com/1270189/126822251-06320cb5-583c-49f3-8a2f-91c883693d03.png">

**Comment by kjellr** [comment]
I can reproduce in my testing as well:

<img width="1080" alt="Screen Shot 2021-07-23 at 2 00 44 PM" src="https://user-images.githubusercontent.com/1202812/126822769-684f2ea2-b168-44fe-ae74-9446eb4f0dd2.png">

**Comment by gwwar** [comment]
@ellatrix do you mind taking a look? I ran git bisect and it seems that this regession is coming from https://github.com/WordPress/gutenberg/pull/32323

Likely the iframe needs some updated event handling.

**Comment by ellatrix** [comment]
Thanks! I'll have a look today
