### ISSUE TITLE
New Block Widget: Add Visibility Options

### ISSUE THREAD

**Issue by kspilarski** [WordPress/gutenberg#33671]
## What problem does this address?
In the new block widget, there is no option to configure visibility. 

**New block widget (without visibility options):** 

<img width="297" alt="Screen Shot 2021-07-24 at 11 13 19 AM" src="https://user-images.githubusercontent.com/36863633/126863837-91f26343-04a8-4094-a2d7-ade05c783e9f.png">

<img width="595" alt="Screen Shot 2021-07-24 at 11 17 51 AM" src="https://user-images.githubusercontent.com/36863633/126864001-91a65271-6883-4f52-9ee5-e9f58c7dd7c5.png">

**Classic widget (with visibility options):** 

<img width="289" alt="Screen Shot 2021-07-24 at 11 20 03 AM" src="https://user-images.githubusercontent.com/36863633/126864059-a3b14fcf-b4c4-4ae6-afb2-21196bb2ae09.png">

 (In an AT site, even widget-visibility is enabled, visibility is not available. Workaround is to install Classic Widget plugin.) 

- User report: 30758048-hc

## What is your proposed solution?

Add visibility option in the new block widget to display blocks in particular posts or pages of the site.

**Comment by kspilarski** [comment]
User report: 30758048-hc

**Comment by mtias** [comment]
Widget visibility is a Jetpack feature, not a core one. I believe it's supported for non-block widgets already, but you can follow up on https://github.com/Automattic/jetpack/issues/20057
