### ISSUE TITLE
List view drag and drop - make it possible to drop at all levels of the hierarchy

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#33678]
## Description
At the moment, there's a known issue when dragging and dropping in List View. It's only possible to drag a block where there's an adjacent block at the position you wish to drop to.

For example, in the following structure, a paragraph can't be moved to after the group because the drag and drop system uses the presence of other blocks to determine the drop target:
<img width="343" alt="Screenshot 2021-07-26 at 1 46 11 pm" src="https://user-images.githubusercontent.com/677833/126939023-3dbb3539-4b8f-4d06-8b7b-5b2a127f3426.png">

Technically this is difficult to achieve because List View is currently implemented as a flat table. 

## Step-by-step reproduction instructions
1. Create a nested block structure with no blocks after the parent block
2. Try dragging and dropping one of the nested blocks after the parent

## Expected behaviour
It should be possible to drop a block after the parent

## Actual behaviour
This isn't possible if the parent block is the last block in a list, only when there's another a block after the parent block

## Video

https://user-images.githubusercontent.com/1813435/155583396-d20bd450-f9a7-4b91-ad15-7c66067ee327.mp4

**Comment by jasmussen** [comment]
Google Keep has a somewhat unique handling of nested items, which could _potentially_ inspire some behaviors in the list view. Specifically it embraces the fact that it's a _list_, as opposed to a complex layout as is seen in the canvas. Nesting an item simply requires you to use the drag handle and pull it rightwards, literally _indent_ it with the gesture:

![list handling](https://user-images.githubusercontent.com/1204802/127854988-af8b909f-8d54-4da9-a026-e047f8514407.gif)

Similarly, moving a nested item leftwards, literally un-indenting it with a gesture, un-nests it. 

This assumption that dragging an item rightwards is an intent to _nest_ an item under the preceeding item likely can't translate 1:1 to a list of actual blocks with content, but sharing in case it inspires adjacent ideas.

**Comment by zaguiini** [comment]
It's not only un-nesting... It's also not possible to move a block to the end of a group. It always becomes a child of the last node, instead of becoming the last node itself. It sounds confusing, so let me add a recording:

https://user-images.githubusercontent.com/26530524/146248792-65e4f0aa-dab9-4fc5-a367-cf758b73d8a6.mov

Look how I can make `Group` the previous sibling of `Layout Grid`, but I cannot make `Layout Grid` the next sibling of `Group`. It always ends up inside `Group`.

**Comment by talldan** [comment]
Thanks @zaguiini, yes that's another instance of the issue. It's hard to describe!

**Comment by skorasaurus** [comment]
Been wondering about this for a while, I thought I was doing something wrong because I couldn't figure out how to do that; relatively frustrating and still present in Gutenberg 13.8.1

**Comment by andrewserong** [comment]
I've opened a potential fix over in https://github.com/WordPress/gutenberg/pull/49742 to explore this.
