### ISSUE TITLE
Export other React APIs in bundled React

### ISSUE THREAD

**Issue by bfintal** [WordPress/gutenberg#33674]
## What problem does this address?
I'd prefer to use the bundled React and ReactDom in Gutenberg which are both available in `wp.element`, as opposed to shipping another version of React into the scripts I load in the editor.

Some of the third-party libraries I use import React and/or ReactDom functions, and unfortunately because of this the whole React code gets joined into my codebase.

I realized that when I add in my Webpack `externals` the following, I won't anymore have to ship React code:
```js
externals: {
    react: 'wp.element', // didn't work
    'react-dom': 'wp.element', // worked
}
```

Using the external `react-dom` worked, and it shaved off a large chunk of my compiled code and all worked fine inside the editor.

I'm getting an error though with the `react` external since not all React APIs are exported such as `React.PureComponent` (there was an old closed PR to add it in: https://github.com/WordPress/gutenberg/issues/8118). I'm not aware if `PureComponent` is the only missing API that's not exported in the Gutenberg-bundled React though.

## What is your proposed solution?
Export all missing React & ReactDom APIs in `wp.element` so that others may use them and won't have to ship their own React/ReactDom.

Feel free to educate whether this is a good idea or not. When I was exploring ways to lessen my shipped code, this came across like our current best practice of using the bundled jQuery in WordPress instead of shipping your own.

**Comment by gziolo** [comment]
https://github.com/WordPress/gutenberg/issues/8118 was closed with a following note from @youknowriad:

> We do have `wp.compose.pure` which solves the same problem and it works for any kind of React component (including functional ones). I'm closing this for now.

So far we wanted to see how far we can get by exposing only React APIs from `@wordpress/element` that are used in Gutenberg. Some were omitted on purpose we had alternatives. However, your use case is a valid concern since it makes it very hard to integrate some 3rd party libraries. The challenge is that every public API exposed from React translates into the maintainance cost to keep backward compatibility support even when React stops using it.

**Comment by Mamaduka** [comment]
There's a plan to [deprecate](https://github.com/WordPress/gutenberg/pull/57173) `wp.compose.pure`, so we might need to export `PureComponent`, even though React considers it a [legacy API](https://react.dev/reference/react/PureComponent).

**Comment by youknowriad** [comment]
Also, now that we're not transpiling to wp.element, folks are free to import from "react" (the script shipped in WordPress) directly. So let's close this issue.
