### ISSUE TITLE
List view drag and drop: expand collapsed parent blocks when dragging over them

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#33684]
## What problem does this address?
The title is fairly self-explanatory. Currently when dragging and dropping, collapsed parent blocks stay collpased, so there's no way to drop into them.

## What is your proposed solution?
Expand a collapsed area when dragging over it. There's an example in this comment - https://github.com/WordPress/gutenberg/issues/29727#issuecomment-854493551

https://user-images.githubusercontent.com/846565/120647790-e27b9d80-c472-11eb-8e6f-aa6f6709d61d.mp4

**Comment by andrewserong** [comment]
Just moving this one to the 6.5 column as I don't believe it's urgent for 6.4.

**Comment by andrewserong** [comment]
Resolved via #56625
