### ISSUE TITLE
List view drag and drop: Make it more obvious blocks can be dragged

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#33686]
## What problem does this address?
This was feedback on the PR that enabled drag and drop - https://github.com/WordPress/gutenberg/pull/33320#issuecomment-877323357

## What is your proposed solution?
A simple first option might be to show the 'drag' pointer when hovering over the block icon.

There might also be other visual improvements, though a drag handle might make things a bit visually busy.

**Comment by jasmussen** [comment]
While closed now, there are some mockups for how this could be handled in the original issue #29727 which I've copied here for easier reference:

**Note:** This change should apply to anywhere we use the List View component. Here shown for the Navigation block:

<img width="1440" alt="list view" src="https://user-images.githubusercontent.com/1204802/110657255-f6d83300-81c0-11eb-9d45-50aad95a20fb.png">

Make the entire list view item draggable:

<img width="1440" alt="list view hover" src="https://user-images.githubusercontent.com/1204802/110657281-fe97d780-81c0-11eb-8cad-e809b7a9de60.png">

You'd still be able to focus the item itself, or the ellipsis, individually:

<img width="1289" alt="focus" src="https://user-images.githubusercontent.com/1204802/110657287-022b5e80-81c1-11eb-8c1c-fc82f0ad6033.png">

The ellipsis menu contains a "Move to..." item that duplicates the move action.

**Comment by ramonjd** [comment]
I played around with this and felt that a modest start would be to change the cursor. The drag cursor is fairly universal.

- https://github.com/WordPress/gutenberg/pull/57493

https://github.com/WordPress/gutenberg/assets/6458278/befcee08-d142-4fe2-95cc-03419cf0f9f0

Adding the `dragHandle` cursor clutters the UI a bit in my opinion.

There's also an option of switching the block icon to `dragHandle` onHover, but it still seems confusing.
