### ISSUE TITLE
Admin bar clashes with top bar on mobile

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#3368]
Some elements of the mobile admin bar have an incorrect Z-depth with the Gutenberg top bar. In general, it seems weird that the content and the admin bar can be scrolled, but the top bar stays fixed.

![zfight](https://user-images.githubusercontent.com/6073772/32496037-2eded890-c3c8-11e7-8342-b30f8644e37e.gif)

**Comment by youknowriad** [comment]
Is it a z-index problem or the top bar should stay fixed on mobile?

**Comment by hedgefield** [comment]
I think it should stay fixed.

**Comment by codebykat** [comment]
Huh. Well, they should either both move or both stay still. I'm not sure what this is - it's like the pull-to-refresh thing, but without a refresh? It indicates that you're at the top of the page and can't scroll up any higher? Anyhow, I just tested on a few other websites I happened to have open. On Amazon and Wikipedia, everything bounces, including the top navbars. On a few other things (Twitter, DuckDuckGo, Wikipedia), there's a fixed top bar that doesn't bounce.

**Comment by hedgefield** [comment]
It happens when I scroll the writing area. On iOS, there's an elastic bounce built into scrollable views to not break the momentum of scrolling. In this case, it would feel natural to only have that applied to the writing canvas, but I can also see it apply to the page as a whole (since that would be the scrollable canvas of the browser).

Making the whole page elastic does perhaps make it confusing whether it's supposed to be a pull-to-refresh though, like you say. Plus that would interfere with the actual pull-to-refresh that's built into chrome on iOS. Lots of factors 🙃 so affixing the toolbars seems like the best option?

**Comment by karmatosed** [comment]
@hedgefield are you still getting this?

**Comment by hedgefield** [comment]
No, looks like it's fixed :)
