### ISSUE TITLE
Where to add Widget title in sidebar

### ISSUE THREAD

**Issue by themeansar** [WordPress/gutenberg#33688]
Hi,

Where to add widget title in sidebar like this: https://prnt.sc/1g37eyw

**Comment by talldan** [comment]
@themeansar With blocks, there's no specific title. 

A separate heading block can be used instead to serve as the title. The heading and the calendar blocks could be grouped together as well for a structure more like widgets had.

In future, there might be an easier way to do this, some background in this issue - https://github.com/WordPress/gutenberg/issues/32723.
