### ISSUE TITLE
Navigation editor: pressing the Esc key opens select mode

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#33693]
In the Navigation editor, it's possible to invoke the select mode by pressing the <kbd>Esc</kbd> key, just as in the Site editor. I'd like to propose removing this key binding since there's no indication in the UI of which is the currently active mode (or a way to switch between them).

This unexpected change is especially confusing when paired with this bug: https://github.com/WordPress/gutenberg/issues/33692. For example, if I press <kbd>Esc</kbd> to unselect the item, instead of that, I'm presented with a different toolbar that is also difficult to toggle off.

https://user-images.githubusercontent.com/4933/126984443-d4dc6775-e262-4d06-b03a-124ecc26ac33.mp4

**Comment by talldan** [comment]
@javierarce removing it might be a difficult subject, seeing as it's a feature that exists largely to improve the accessibility of the block editor. The navigation editor also lacks an easy way to access List View, which is another feature that makes navigating blocks easier when using a keyboard and a screen reader.

Are there ways that navigation mode might be retained, perhaps improving some of the things you mentioned? Fixing #33692 will be a good start 😄

**Comment by javierarce** [comment]
I'm closing this issue since the navigation screen is no longer actively developed.

Related: https://github.com/WordPress/gutenberg/issues/43620.
