### ISSUE TITLE
WordPress caught an error with one of your plugins, Gutenberg

### ISSUE THREAD

**Issue by bobmixon** [WordPress/gutenberg#33700]
## Description
I received an email indicating an error was caught. This is at the bottom of the email.
Error Details
=============
An error of type E_ERROR was caused in line 12 of the file /var/www/wp-content/plugins/gutenberg/lib/full-site-editing/class-wp-block-template.php. Error message: Cannot declare class WP_Block_Template, because the name is already in use

## Expected behaviour
My expectation would be for my blog to open.

## Actual behaviour
My blog doesn't open.

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

I cannot get to my admin screen to see any of this. I am not using the default theme.

## Device information
- Device: Desktop computer
- Operating system: Windows 10
- Browser: Microsoft Edge

**Comment by anton-vlasenko** [comment]
@bobmixon It looks like this issue is specific to your WordPress installation.
It's happening because it tries to redeclare existing class twice.
I have Gutenberg plugin enabled and I don't get this error.
Could you please provide steps on how to reproduce this issue because I'm not able to do it?
BTW to resolve your issue you can try to rename your `wp-content/plugins/gutenberg` folder to `wp-content/plugins/gutenberg-disabled` as it's described [here](https://www.ostraining.com/blog/wordpress/disable-a-wordpress-plugin/) (option 1). Please only do this at your own risk.

**Comment by talldan** [comment]
Seems related to this - https://core.trac.wordpress.org/ticket/53432, though it looks like that was fixed before WordPress 5.8 was released.

**Comment by talldan** [comment]
Also reported on the forums here:
https://wordpress.org/support/topic/how-to-uninstall-plugins-manually/

**Comment by hellofromtonya** [comment]
Hello @bobmixon, More information is needed for investigation:

- What is the WordPress' version number?
- What is the Gutenberg plugin's version?
- Did the fatal error happen during an upgrade process? 
     - If yes, was it during a WordPress upgrade or plugin upgrade?

**Comment by hellofromtonya** [comment]
>Seems related to this - https://core.trac.wordpress.org/ticket/53432, though it looks like that was fixed before WordPress 5.8 was released.

Context Notes:

- Older versions of the plugin (< 10.7) have incompatibilities with WordPress 5.8 which can cause a fatal error.
- As @talldan noted, a [fix was added to WordPress 5.8.0](https://core.trac.wordpress.org/ticket/53432) that deactivates an older version of the Gutenberg plugin. 
     - If the plugin is reactivated manually, then the plugin's installation causes a fatal error and the plugin is not activated (meaning the log will have a fatal error in it but the site remains operational).

**Comment by bobmixon** [comment]
Hi Tonya,

I am not able to log into admin to see any of these details.

I haven't done anything to the site, no upgrades, no posts, etc in over a year. My blog is hosted by godaddy and they do updates, etc. I received the first email a week ago.

Thank you!

Bob Mixon
Microsoft SharePoint MVP
Senior Office 365/SharePoint Solution Architect and Administrator

Nothing in this message should be interpreted as a digital or electronic signature that can be used to form, execute, document, agree to, enter into, accept or authenticate a contract or other legal document. This electronic mail transmission and any attached documents may contain confidential or privileged information for the sole use of the intended recipient(s). Any review, use, distribution or disclosure by anyone other than the intended recipient(s) is strictly prohibited. If you believe that you have received this message in error, please notify the sender by reply transmission and delete or destroy the message without copying or disclosing it.

**Comment by bobmixon** [comment]
Hi Anton,

Renaming the Gutenberg folder to Gutenberg-disabled worked. Is it safe for me to just remove this plugin?

Thank you!

Bob Mixon
Microsoft SharePoint MVP
Senior Office 365/SharePoint Solution Architect and Administrator

Nothing in this message should be interpreted as a digital or electronic signature that can be used to form, execute, document, agree to, enter into, accept or authenticate a contract or other legal document. This electronic mail transmission and any attached documents may contain confidential or privileged information for the sole use of the intended recipient(s). Any review, use, distribution or disclosure by anyone other than the intended recipient(s) is strictly prohibited. If you believe that you have received this message in error, please notify the sender by reply transmission and delete or destroy the message without copying or disclosing it.

**Comment by anton-vlasenko** [comment]
@bobmixon I can only guess.
If you simply delete the folder it should be fine, although that is not the best way to do it. There could be some tables and settings left in the database.
The proper way would be to delete the plugin from the plugins page (`wp-admin/plugins.php`).
![Screenshot 2021-07-27 at 20 02 50](https://user-images.githubusercontent.com/43744263/127205112-b95348f3-9c24-4d39-b97b-78e8a195bf20.png)
 But I can only guess what will happen if you do that. Most likely there will be no issues but I cannot guarantee anything since I don't have access to your WordPress installation.
Please note that this is not a support forum and everything that you do is at your own risk.

**Comment by bobmixon** [comment]
Hi Anton,

Thank you again for your help. I have the problem resolved.


  1.  I used FileZilla and renamed the plugin folder Gutenberg to Gutenberg-disabled.
  2.  Now I'm able to get to the admin dashboard. I see the Gutenberg plugin required an update. I ran the update.
  3.  Gutenberg updated without issue and my site is back running.

Thank you!

Bob Mixon
Microsoft SharePoint MVP
Senior Office 365/SharePoint Solution Architect and Administrator

Nothing in this message should be interpreted as a digital or electronic signature that can be used to form, execute, document, agree to, enter into, accept or authenticate a contract or other legal document. This electronic mail transmission and any attached documents may contain confidential or privileged information for the sole use of the intended recipient(s). Any review, use, distribution or disclosure by anyone other than the intended recipient(s) is strictly prohibited. If you believe that you have received this message in error, please notify the sender by reply transmission and delete or destroy the message without copying or disclosing it.

**Comment by anton-vlasenko** [comment]
You are welcome, @bobmixon.
