### ISSUE TITLE
Hide embed variations from in page (slash) inserter.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#33706]
## What problem does this address?

It would be nice to remove the embed variations that show up in the in page / (slash inserter).

![Screen Shot 2021-07-27 at 12 01 15](https://user-images.githubusercontent.com/5323259/127135814-c3b955a8-e3f5-4657-8d53-872977f46b2a.jpg)

![Screen Shot 2021-07-27 at 12 00 52](https://user-images.githubusercontent.com/5323259/127135827-781845f5-c2b2-4309-984d-6ba6e62525ad.jpg)

As having embed variations show up in the slash inserter creates visual distraction.
Only the default embed video option show be seen in the slash inserter.

![Screen Shot 2021-07-27 at 12 03 46](https://user-images.githubusercontent.com/5323259/127136072-187402bc-5a0f-4679-b904-c71a3dcfda02.jpg)

## What is your proposed solution?

Remove all embed variations from the / slash inserter. Only show the video embed in this location. Or if the user types out example Vimeo then the Vimeo embed variation will show up.

Associated:
allowed_block_types filter is ignored for embeds
https://github.com/WordPress/gutenberg/issues/25676
Remove unsupported core-embed/hulu block
https://github.com/WordPress/gutenberg/pull/23984

**Comment by mtias** [comment]
This would make it harder to select specific embeds, which is useful for many reasons. Forcing it to be an exact match could be fine, but also quite rough — typing `youtub` would list nothing until I type the final "e" and it can make it seem like there's no embed for it. I don't think this would be an enhancement.

**Comment by paaljoachim** [comment]
Yeah. I can see that. I am basically looking for ways to where we can hide the least used options from the slash inserter. Having the most used options show up initially and as the user adds additional letters other less used options could also show up.

**Comment by mtias** [comment]
We have discussed before the notion of having blocks "hidden" from the inserter but discoverable in search. Perhaps that can be a way to treat some of these embeds. Though at the same time a large part of the impetus of blocks was to unearth what was hidden for regular users.

**Comment by paaljoachim** [comment]
An example.
Write / and see most used block show up.
Write / I and have any "high level" / "Most used" blocks will show up that contain the letter i.
Write / I and another letter and have more precis blocks show up that contain the specific letters.
Etc.
In a sense this would with create a more refined overview based on letters added. I assume somewhat similar to what we have today, only a bit more fine tuned..:)

Of course another alternative is to create Block Editor documentation to where we show how to hide various embed or other blocks from the slash inserter.

I noticed this documentation: https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/

**Comment by skorasaurus** [comment]
If I recall correctly, the inserter doesn't take into account variations. For example, if a user often uses the vimeo variation, other embed variations will also appear as being used, so to speak; 

relevant code at https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/store/selectors.js#L1562

**Comment by ntsekouras** [comment]
>If I recall correctly, the inserter doesn't take into account variations. For example, if a user often uses the vimeo variation, other embed variations will also appear as being used, so to speak;

That used to be true yes, but has been fixed here: https://github.com/WordPress/gutenberg/pull/28663

**Comment by ntsekouras** [comment]
I guess a good alternative would be to handle this in the `block manager` (https://github.com/WordPress/gutenberg/issues/27708) by disabling specific block variations.

**Comment by paaljoachim** [comment]
#27708 is a very good alternative to this issue!

**Comment by jasmussen** [comment]
Untangling "mystery meat embed discovery" was a key principle of the block editor, so I'd avoid changing defaults to hide any of the embeds. On the contrary, the slash command to me feels like an egalitarian place that values core blocks the same as 3rd party blocks. #27708 gives user choice on top of that, which makes good sense. Should we close this one in favor of it?

**Comment by paaljoachim** [comment]
Closing!
