### ISSUE TITLE
Changing the order of a gallery is a confusing process

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#3370]
## Issue Overview
To change the layout of a gallery block, you have to go through this process:

1. Click Edit in the toolbar
2. Deselect the current images in the media library and reselect them in the new order you want
2. Click Create New Gallery
4. Click Insert Gallery

## Expected Behavior
Ideally, drag-and-drop the images around to reorder (you can already delete them inline). But even with drag-and-drop reordering in the media library and better (contextual) text on the buttons it would be improved.

**Comment by karmatosed** [comment]
Noting that the existing media implementation of gallery does have an easier reordering. We should at least be on par with that.

**Comment by mtias** [comment]
The ideal flow is what we have in https://github.com/WordPress/gutenberg/issues/743. Closing in favor of that.
