### ISSUE TITLE
Cover block: Text color

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#33723]
## What problem does this address?

It is currently difficult to set a text color for Cover block inner elements easily in one place. Currently if Cover block content contains of Heading, Paragraph and List, for example, I have to set text color for each one of these.
Instead, the preferable solution would be to set text color on the Cover block itself, so the inner elements can inherit the color.

## What is your proposed solution?

In my theme, I've tried to enable the text color control for Cover block using a JavaScript code in a file enqueued via `enqueue_block_editor_assets` action with PHP.

Here is the actual JavaScript code portion dealing with the issue:
```js
wp.hooks.addFilter(
	'blocks.registerBlockType',
	'my-custom-block-mods',
	function( settings, name ) {
		if ( 'core/cover' === name ) {
			settings = lodash.merge( {}, settings, {
				supports: {
					color: { text: true }
				},
			} );
		}

		return settings;
	}
);
```

This indeed produces a working text color control, which resolves my issue, actually.

Unfortunately, the code above breaks the custom overlay color functionality. When I use the code above, I can only choose the overlay color from predefined palette (which works well as the palette color class is applied on the Cover container) but I can no longer set a custom overlay color (which does not produce `background-color:...` inline style on the Cover container anymore).

I understand that overlay color is actually set as a background color on Cover container. But I fail to understand why enabling text color breaks (part of) this functionality.

Could anyone enlighten me please? Is there any way of implementing this currently via WordPress theme?
Could text color control be added to Cover block?

Thanks for any help!

**Comment by bgoewert** [comment]
I was trying to do this with theme.json. But it is being overwritten by the default `.wp-block-cover__inner-container` color.

``` json
"core/cover": {
	"color": {
		"text": "var(--wp--preset--color--black) !important"
	}
}
```

![image](https://user-images.githubusercontent.com/15313658/144289747-24cf065d-f2e0-44a4-aebb-168f5184076d.png)

I'm currently just overriding the default `.wp-block-cover__inner-container` class. But it would be nice to do this with theme.json as well as the block editor.

**Comment by akasunil** [comment]
I believe this is resolved in latest pull. We can close this issue. @Mamaduka 

![CleanShot 2024-03-14 at 14 07 45@2x](https://github.com/WordPress/gutenberg/assets/61308756/30bab45c-c1bf-43fd-bf52-27b942ccfba9)

**Comment by Mamaduka** [comment]
Thanks for the ping, @sunil25393. It was probably #41572.
