### ISSUE TITLE
UA string may cause URL Details endpoint request to fail

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#33722]
## Description

Using the new "rich preview" feature when creating an external link sometimes results in no rich preview for links where you would expect there to be a rich preview.

Some high profile offenders:

* `www.google.com`
* `www.wordpress.com`

This doesn't happen for `www.wordpress.org`.

After some investigation I wonder whether this is due to either:

1. The requests originating from `locahost`.
2. The default "WordPress" UA string send with the requests.

With some testing I found that altering the UA string to a valid browser string does in fact "solve" the problem. To mimic this add this filter:

```php
add_filter(
	'rest_url_details_http_request_args',
	function( $args ) {
		$args['user-agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246';
		return $args;
	}
);
```

With this in place the above URLs no longer 404 and return the expected "rich" results for _both_ the test URLs above.

In the original PR which improved the endpoint I [originally added some code to use a random valid UA string](https://github.com/WordPress/gutenberg/pull/31763/commits/87f4d330ad762e823af8144db2e0f64e53691d27) but this was [removed following feedback from the Core team](https://github.com/WordPress/gutenberg/pull/31763#issuecomment-847830949). Should we look to reinstate (cc @TimothyBJacobs or @spacedmonkey )?

cc'ing @azaozz and @hellofromtonya with whom I have been discussing this problem.

## Step-by-step reproduction instructions

1. Using Gutenberg Plugin.
2. Create post and add some text.
3. Create a link to either of the two examples above.
4. Click on the link to see the link preview.
5. See no rich preview results.
You can also check the raw usage of the API endpoint by:

1. New Post.
2. Open browser dev tools `Console`.
3. Type `copy(wpApiSettings.nonce)`.
4. Update the following URL replacing `YOUR_NONCE_HERE` with the value from the previous step.

```
http://localhost:8888/index.php?rest_route=%2F__experimental%2Furl-details&url=http%3A%2F%2Fwww.wordpress.com&_locale=user&_wpnonce=YOUR_NONCE_HERE
```

5. Paste into your browser.
6. The the "404" response code.

## Expected behaviour
Endpoint should return rich data parsed from the remote site.

## Actual behaviour
Endpoint returns that there was a 404 when requesting the remote site. The remote site has rejected the request.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/444434/127290945-9ceda80c-63c0-4331-8668-b432a8dd97bb.mov

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by TimothyBJacobs** [comment]
I'm still pretty opposed to WordPress falsifying a user-agent. If a server admin wants to block requests from WordPress, they should be able to.

**Comment by getdave** [comment]
> I'm still pretty opposed to WordPress falsifying a user-agent. If a server admin wants to block requests from WordPress, they should be able to.

I understand and appreciate your position here.

However, from a practical point of view this does leave us in a bit of a bind with the rich previews feature.

I think the problem might be that some services are blocking the request because the UA is similar to the UA used in the request made by WordPress  for [Pingbacks](https://developer.wordpress.org/reference/functions/pingback/).

Here is the format used by the UA for a Pingback request - https://core.trac.wordpress.org/browser/tags/5.8/src/wp-includes/comment.php#L3064

```
$client->useragent . ' -- WordPress/' . get_bloginfo( 'version' )
```

...and here is the one issued (using the default UA) by the `url-details` endpoint:

```
```
'WordPress/' . get_bloginfo( 'version' ) . '; ' . get_bloginfo( 'url' ).
```
```

I think the `WordPress/'` bit is probably the part the services are looking for and blocking.

Given this then, is there any scope for modifying the UA used by `url-details` to utilise a modified UA that doesn't include that exact string? I'm guessing not given that it's still a request issued by WordPress.

If we can't work around this, then the rich previews feature might be hampered a little. I guess users can live with it, but when you compare to a similar feature on other "writing" services such as Google Docs it leaves a little to be desired.

Any suggestions very welcome/appreciated.

**Comment by TimothyBJacobs** [comment]
IMO we can definitely change the user agent if we want, but I think it should be some variation of WordPress or WP.
