### ISSUE TITLE
Site Editor: Implement a settings object filter

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#33736]
## What problem does this address?

The **post editor** has the `block_editor_settings_all` and `block_editor_settings` filters that allow us to modify the `settings` object injected into the block editor. A similar filter, however, doesn't exist for the **site editor**.

As a developer, I want to extend the `settings` object in the site editor because it will allow me to add google font families as selectable options in global styles. Below is an example of what I'd like to achieve.

![2021-07-27 17 28 47](https://user-images.githubusercontent.com/5414230/127392982-7f2143b1-8a31-46a5-9ba6-65354b58afb6.gif)

## What is your proposed solution?

Apply a filter to the `settings` object before it's passed to the site editor for initialization.

## Notes
@nosolosw has described ways to extend the global styles in the block editor [here](https://github.com/WordPress/gutenberg/issues/27504#issuecomment-858761483), but they only apply to the post editor because they make use of the `block_settings` and `block_settings_all` hooks.

**Comment by gziolo** [comment]
By looking at the screenshot shared for the edit site, I think it should be possible to use the following check in the `block_editor_settings_all` filter:

```php
if ( isset( $_GET['page'] ) && $_GET['page'] === 'gutenberg-edit-site' ) {
   // apply modifications to the $settings here
}
```

Of course, it's something that would work only when the Gutenberg plugin is enabled. In the long run, we need a better way to detect the context like a screen: widgets vs post editor vs site editor. In the case of the post editor, the context might be content editing or template editing. I know that @youknowriad had some good thoughts about whether the post editor should be merged with the site editor at some point.

There are some options we could explore now that we have also a REST API endpoint that allows fetching block editor settings:
- we can have one gigantic settings object which describes different contexts similar to how Global Styles config is architected with overrides for blocks
- we can have several distinct settings that depend on the aforementioned contexts and they can be loaded with REST API call each time we change the context - it's closer to what we have now with edit post vs widgets screen
- we can have one general config, and load only contextual overrides with REST API calls

It's something that we should be able to address once we have a solid understanding of how the site editor interacts with other screens.

**Comment by jeyip** [comment]
> By looking at the screenshot shared for the edit site, I think it should be possible to use the following check in the block_editor_settings_all filter:

Hmmm...I'm not sure I follow @gziolo.

From what I can tell looking at [edit-site-page.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/full-site-editing/edit-site-page.php), the `block_editor_settings_all` filter is never applied when initializing the site editor, so we can't apply modifications to the `$settings` object before the page is loaded. 

https://github.com/WordPress/gutenberg/blob/be20becd8375992b30b0a5072b7ec7fb109e187c/lib/full-site-editing/edit-site-page.php#L92-L121

I opened [this PR](https://github.com/WordPress/gutenberg/pull/33737) because of the aforementioned issue, although I'm not sure if there are historical reasons for why we don't already filter settings for the site editor.

**Comment by gziolo** [comment]
I wrongly assumed that the edit site page is using `get_block_editor_settings` (or `gutenberg_get_block_editor_settings` to account for WP 5.7 that doesn't have this function) like other screens. https://github.com/WordPress/gutenberg/pull/33737 would have to land first to align with the post editor and widgets.

**Comment by jeyip** [comment]
> I wrongly assumed that the edit site page is using get_block_editor_settings (or gutenberg_get_block_editor_settings to account for WP 5.7 that doesn't have this function) like other screens. #33737 would have to land first to align with the post editor and widgets.

Ahhh I see -- that makes sense. Thanks for chiming in and clarifying 🙏
