### ISSUE TITLE
Make Block Descriptions More Clear

### ISSUE THREAD

**Issue by davidakennedy** [WordPress/gutenberg#3375]
## Issue Overview

While testing Version 1.6.1 of Gutenberg, specifically inserting and customizing the different blocks, I got confused by something. For example, when first testing out the Button block, I thought the block description was placeholder text. It currently reads: "A nice little button. Call something out with it." I thought I could edit that initially because I thought it was changeable, like many of the other settings in that panel.

## Possible Solution
A few possible solutions exist for this:
- Ensure the block descriptions don't read like placeholder/starter text.
- Provide a label for the description, since right now, it has none and that text looks like it's hanging out there all alone.

## Screenshots / Video
Possible solution, with label for block description:

![gutenberg-button-block-w-description](https://user-images.githubusercontent.com/1473618/32513984-b19ad60c-c3c9-11e7-91bc-3b019fb71d85.png)

**Comment by karmatosed** [comment]
I agree we should make the descriptions better. Thanks for the feedback.

**Comment by maddisondesigns** [comment]
Suggestion for Paragraph Block
_"This is a simple text only block for inserting a single paragraph of content."_

**Comment by pixolin** [comment]
The description for the Quote block still includes some philosophical reflection on quotations in general, which seems rather distracting for any user.

<img width="305" alt="screenshot_363" src="https://user-images.githubusercontent.com/1968542/48629589-555ac100-e9ba-11e8-95b7-bb4331768fcc.png">
