### ISSUE TITLE
@wordpress/scripts vulnerable via webpack thru glob-parent

### ISSUE THREAD

**Issue by lucyllewy** [WordPress/gutenberg#33768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

the `@wordpress/scripts` NPM package depends on a version of `webpack` which ultimately depends on a vulnerable version of `glob-parent`:

```plain
@wordpress/scripts > webpack > watchpack > watchpack-chokidar2 > chokidar > glob-parent
```

`npm audit` shows this as a "moderate" security vulnerability.

### Step-by-step reproduction instructions

1. `npm init`
2. `npm install @wordpress/scripts`
3. `npm audit`
4. read the audit report indicating vulnerabilities.

### Expected Behavior

`npm audit` gives the project a clean bill of health.

### Current Behavior

Has a security hole indicated by `npm audit`

**Comment by gziolo** [comment]
> the @wordpress/scripts NPM package depends on a version of webpack which ultimately depends on a vulnerable version of glob-parent:

`@wordpress/scripts` (and also Gutenberg) uses `webpack` 4.46.0 that is the most recent v4 version (7 months old). It looks like the only way to move forward is to finally upgrade webpack to v5.

**Comment by skorasaurus** [comment]
Thanks for reporting. 
For reference, npm audit may not always indicate an issue that needs to be immediately addressed or prioritized. to be clear though, I am not stating that the vulnerability in glob-parent is inconsequential for us; I have not examined it. 

Again, thank you for reporting; I do not wish to deter your reports. 

(this is an opinionated piece) - https://overreacted.io/npm-audit-broken-by-design/

**Comment by gziolo** [comment]
We are working on weback v5 upgrade in https://github.com/WordPress/gutenberg/pull/33818 that should resolve this issue
