### ISSUE TITLE
Sorting of search results for new plugins

### ISSUE THREAD

**Issue by Manja-S** [WordPress/gutenberg#33763]
## What problem does this address?
It is currently difficult to choose an up-to-date plugin because the search results for a new plugin are (apparently) shown randomly. This increases the risk of choosing an outdated plugin.

## What is your proposed solution?
Sort the plugins by 'tested with version' and maybe add a second sort by 'number of installations'.

‘needs design feedback’

**Comment by swissspidy** [comment]
Is this about the plugins page in WordPress admin? If so, you should report this at https://core.trac.wordpress.org/ since it's not related to Gutenberg

**Comment by Manja-S** [comment]
Thank you for pointing me to the right direction.
