### ISSUE TITLE
Possibility to remove some options from the `toolbar` in Gutenberg block?

### ISSUE THREAD

**Issue by kanlukasz** [WordPress/gutenberg#33773]
## What problem does this address?
It is basically the same situation I described in the [previous issue](https://github.com/WordPress/gutenberg/issues/33772). We need more control over what we can show and what we can hide in custom solutions like blocks but in **core blocks too**

For example, I would like to remove some items from here (I marked it in red)
![image](https://user-images.githubusercontent.com/30685349/127609784-96a5f54e-c73a-4164-9b50-5cefc983342d.png)

## What is your proposed solution?
Maybe we can use the new `theme.json` function for this?
Or maybe we can use option in `support: {}` when we create new custom block?

**Comment by kebbet** [comment]
Some options can be removed with the   `wp.richText.unregisterFormatType('core/link');`, but I agree, add these types of adjustments to the theme.json, and open up for more modifications.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/23619 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

I've added your post in that issue.
