### ISSUE TITLE
Option to disable “Transform to” in Gutenberg blocks

### ISSUE THREAD

**Issue by kanlukasz** [WordPress/gutenberg#33772]
## What problem does this address?
_The main problem is that everywhere is too much options that we can't remove as a developers who prepare our themes for our customers
End users who are regular non-technical users and use the edit panel are given too many options to click. This makes it likely that they will break something._

This applies, inter alia, to `Transform to` option
![image](https://user-images.githubusercontent.com/30685349/127609980-818619f6-e409-4514-8455-6b821fe5c4e9.png)

## What is your proposed solution?
Maybe we can use the new `theme.json` function for this?
Or maybe we can use option in `support: {}` when we create new custom block?

**Comment by stokesman** [comment]
This duplicates #31905.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/31905 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments), comment there, and follow its progress in the issue.
