### ISSUE TITLE
Link broken in documentation `https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#styles`

### ISSUE THREAD

**Issue by kebbet** [WordPress/gutenberg#33778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

The link to “block support mechanism” in the top section of Styles is broken - > https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#styles

The link points to https://developer.wordpress.org/block-editor/how-to-guides/themes/block-api/block-supports.md which is not present.

### Step-by-step reproduction instructions

1. Go to https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#styles
2. Click link "block support mechanism"

### Expected Behavior

A working link.

### Current Behavior

A non-working link.

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by wassim31** [comment]
I would like to take this issue as my first contribution to gutenberg if possible.
