### ISSUE TITLE
Automate process for contributor license agreements

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#33787]
## What problem does this address?

Over the last year, an effort was needed to dual license Gutenberg causing a fairly intense process of getting folks who have contributed to give consent: https://github.com/WordPress/gutenberg/issues/31913 & [Make Core post on dual licensing](https://make.wordpress.org/core/2021/03/05/dual-licensing-gutenberg-next-steps/ ). This is currently a cumbersome and manual process!

## What is your proposed solution?

@desrosj  brought to my attention how slack currently handles this and it seems advantageous to explore doing the same for this repo: 

![Screen Shot 2021-07-28 at 14 30 16](https://user-images.githubusercontent.com/26996883/127700818-88515dc8-de36-4f37-a2bb-5fea74926285.png)
![Screen Shot 2021-07-28 at 14 28 51](https://user-images.githubusercontent.com/26996883/127700809-d97355b8-8b3a-4696-893d-444d78eb911e.png)
![Screen Shot 2021-07-28 at 14 29 10](https://user-images.githubusercontent.com/26996883/127700812-59e04193-5675-498a-8577-31e208fb178e.png)
![Screen Shot 2021-07-28 at 14 29 26](https://user-images.githubusercontent.com/26996883/127700814-1b70b3a1-688c-4780-9ba3-625adb17149a.png)
![Screen Shot 2021-07-28 at 14 30 00](https://user-images.githubusercontent.com/26996883/127700817-9b274eac-2a62-4fb1-8f13-5968430507ba.png)

Note that there's a very clear comment on the issue itself upon the agreement being signed.

**Comment by jenkoian** [comment]
Another possible option would be to use the [Developer Certificate of Origin](https://developercertificate.org/) currently used by Linux and [OpenSearch](https://github.com/opensearch-project/OpenSearch) (Amazon's fork of ElasticSearch)

Here are some links with some more information:

https://opensource.com/article/18/3/cla-vs-dco-whats-difference

https://drewdevault.com/2021/04/12/DCO.html

**Comment by mchowning** [comment]
Thanks for this @annezazu ! Finding the right solution here is so tricky and the more ideas the better.

I think there are two issues here: (1) obtaining consent to license new contributions, and (2) obtaining consent to relicense past contributions.

### 1. Obtaining consent to license new contributions

I don't think we need to add any automation around licensing new contributions. Under [GitHub's terms of service](https://docs.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license), all contributions made to a repository are made under the terms of the repo's current license:

> Whenever you add Content to a repository containing notice of a license, you license that Content under the same terms, and you agree that you have the right to license that Content under those terms.

Unlike Slack, Gutenberg does not have either a CLA or non-standard license, and Gutenberg does contain a [notice of license](https://github.com/WordPress/gutenberg/blob/trunk/LICENSE.md), so this accomplishes all that we need with respect to licensing new contributions.

### 2. Obtaining consent to relicense past contributions

As you noted, the difficulty we have had has come from our need to obtain permission to dual-license past contributions.  Unfortunately, there does not appear to have been any easy way to automate this along the lines you suggest. All of the currently built license-bot type automation are solely concerned with licensing new contributions as opposed to obtaining permission to change a license (at least I didn't find any).

In addition, we've already gotten consent to the dual-license from 678 of Gutenberg's 822 past contributors ([current status](https://github.com/WordPress/gutenberg-license/blob/trunk/status.md)), so I don't think there's anything to be gained at this point from switching how we're obtaining consent to dual-license past contributions.

**Comment by annezazu** [comment]
Thanks for this excellent overview of why this might not be applicable going forward. Makes sense to me and I trust your read of it. Do you think it's okay to close this out as a result or shall we keep it open in case others might want to chime in?

**Comment by mchowning** [comment]
> Do you think it's okay to close this out as a result or shall we keep it open in case others might want to chime in?

Let's go ahead and close this out. If anyone has strong feelings here though, go ahead and leave a comment so we can reopen this.
