### ISSUE TITLE
Add possibility to close the Full Site Editing theme notice banner

### ISSUE THREAD

**Issue by ellenbauer** [WordPress/gutenberg#33792]
## What problem does this address?
At the moment the Full Site Editing theme notice banner is permanent and users have no option to close the notice.

I fear that this will discourage theme users to try FSE themes as well as theme developers to put the work in to get started adding FSE themes to the repository.

<img width="1400" alt="Screen Shot 2021-07-30 at 7 42 56 PM" src="https://user-images.githubusercontent.com/17613630/127736427-9f747df3-34c8-4875-9f46-45cb6ea4b3c9.png">

## What is your proposed solution?
My favourite solution would be to enable users to close the banner once they have read it.

Alternatively it would be helpful to at least change the wording to be a little bit more positive and encouraging. In my opinion the current wording is scaring users away from trying FSE themes.

**Comment by bph** [comment]
Current wording: "You're using an experimental Full Site Editing theme. Full Site Editing is an experimental feature and potential API changes are to be expected!" 

@ellenbauer Do you have any suggestion on how to adopt the wording to be less “scary”, but acknowledge that “there might be dragons"? 🐲🐉  

I agree: the message should be dismiss-able.

**Comment by ellenbauer** [comment]
Thank you so much for giving this ticket your attention @bph .

1. My favourite option would be to make it dismiss-able, as you suggested as well.

2. Regarding the wording: I believe mentioning API changes is not very user-friendly, since a lot of users don't really know what that means. I think the following would be easier to understand:

"You're using a Full Site Editing theme. Full Site Editing is an experimental feature and potential changes are to be expected."

or:

"You're using a Full Site Editing theme. Full Site Editing is a feature under active development and potential changes are to be expected."

What do you think?

**Comment by carolinan** [comment]
Maybe it can be removed now, as there is also a notice in core if you activate the theme without Gutenberg?

**Comment by Mamaduka** [comment]
Maybe we should display notice only on the Themes page and make it dismissable?

Unfortunately, default dismissable behavior will not prevent a message from re-appearing once the page re-loads. Also, loading extra JS files on the dashboard page to save user preferences in local storage will complicate things.

P.S. Happy to create PR to resolve this.

**Comment by ellenbauer** [comment]
@carolinan @Mamaduka Thank you so much for your help on this. It would be so wonderful to have a solution here since it is so distracting to have this notice always visible and also discourages users to start exploring FSE themes in my opinion.

Of course I love @carolinan idea to just remove it completely but whatever improves the current state would be wonderful to have. 

@Mamaduka yes, if you could create a PR that would be so great. Thank you so much for your help.

**Comment by Mamaduka** [comment]
The PR is ready for review - #34353. Please let me know if you also prefer to change the wording of the message.

**Comment by Mamaduka** [comment]
PR is merged, and the update should be available in Gutenberg 11.5. The notice only will be displayed on the Themes screen.

**Comment by ellenbauer** [comment]
Amazing, I can't wait, I think to only show the notice on the themes page is a great solution.

**Comment by Mamaduka** [comment]
The update should be available in 11.5, which was released yesterday 🎉

**Comment by carolinan** [comment]
Can we remove the notice now? 😸

**Comment by Mamaduka** [comment]
New PR is ready #36083.
