### ISSUE TITLE
Toggling off bold at the end of an inline boundary removes the bold from the current word

### ISSUE THREAD

**Issue by ephox-mogran** [WordPress/gutenberg#3380]
## Issue Overview

Bold is removed from the current word when pressing bold at the **end** of an inline link boundary

## Steps to Reproduce (for bugs)

1. Start typing in a paragraph block
2. Press Ctrl/Cmd + B to start bold formatting
3. Type: `hello`
4. Press Ctrl/Cmd + B to turn off bold for the next word

## Expected Behavior

Bold turns off for the next word, but `hello` stays bold

## Current Behavior

The bold is removed from `hello`

## Possible Solution

This is a bug in TinyMCE.

**Comment by ephox-mogran** [comment]
This should be fixed as of TInyMCE 4.7.2.

**Comment by ephox-mogran** [comment]
This can probably be closed as fixed by updating to 4.7.2. We'll verify that it is no longer happening.

**Comment by jasmussen** [comment]
Confirming as fixed! Nice!
