### ISSUE TITLE
Hook for iframed block editor

### ISSUE THREAD

**Issue by wpsoul** [WordPress/gutenberg#33803]
In current point, we have no access to iframe which is used in widget editor and template editor. 

Let me explain. For example, we have option to choose custom fonts, colors in Customizer. Then, theme creates variables based on user choice. We load these css variables in header via wp_head and in admin panel via admin hooks. But this doesn't work in iframes. 

In the current point iframes have only possibility to load static files with Block Meta API (which is very limited because it allows to attach only one style and one script to block, so, no possibilities for third party library) + add_editor_style function which is also very limited because you can use only static css files in it

We need some hook for iframes to allow developers to inject custom styles and scripts OR the possibility to attach something conditional via wp_add_inline... functions to iframe.

Also, in current point, environment becomes very complex. Previously we have Frontend and Backend scripts, now we have frontend, backend content context, backend widget context, backend template editor context, hooks and functions are not working across them, we need function which works across all backend context with option to choose context

**Comment by jasmussen** [comment]
The iframe is a useful tool to ensure the correct behavior of device previews and media queries, as well as to protect the editing canvas from CSS bleed. But as you outline in this comment, there are lots of considerations to take in account, which is why the iframe project has a roadmap in #33346. The issues and pull requests linked from that road map are likely going to get more visibility. Some of the issues you outline are already addressed in PRs like https://github.com/WordPress/gutenberg/pull/33389. Can you add your comments on one of those issues?

**Comment by wpsoul** [comment]
Checked your topics. Yes, I agree, improvements in add_editor_style with option to attach dynamic inline styles should fix most of problems. But, another good feature will be to add hook which works only in the Iframe context. Wordpress has hooks for everything, so, I am expecting to have them also for iframe. Something like admin_iframe_head which will be attached to Iframe head section.

**Comment by jasmussen** [comment]
Thanks for responding! Would you mind sharing that comment on the main thread instead? Then perhaps I can close this one so we keep it all in one place?

**Comment by wpsoul** [comment]
Sure, Added comment with my thoughts 

https://github.com/WordPress/gutenberg/issues/18571#issuecomment-890985304

**Comment by jasmussen** [comment]
Thank you. I'm closing this one in favor of that and we can always revisit!
