### ISSUE TITLE
Create a "recently used" or "most used" or "personal favorites" blocks section.

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#33807]
Currently, I'm admin of 5 different WordPress websites and all 5 of them are quite different. 
One is my personal gaming blog, one is my school website, one is actually a teacher's inspiration website for students, one is for my theater group and one is just to mess around on and test the translations I do for nl_BE, nl_NL-(formal)

Now, you might expect that I don't use the same blocks often on those websites. For example, I use way less images on my school site than on my gaming blog and the site for the theater group. 

Now, I find it a bit annoying to always have to scroll / search for the blocks I want to use. So, I suggest that in the block inserter we add a new tab or a new top section where either:

- The most recently used blocks (from one and/or all users) are displayed.
- The most used blocks (from one and/or all users) are displayed.
- Where an user can make their own section with "favorite" blocks where they can have easy access to them.

You could argue to use the reusable blocks for this, but that's for multiple blocks if I understand that feature correctly.

I don't really know what the most interesting way to handle/solve this "issue" is, but those are the three ways I can think off. It might save some seconds per article but as we say in Dutch: "All small bits help." (Since a lot of small timesaves clumped together into one is one big time save :) )

**Comment by talldan** [comment]
@NekoJonez There is a preference to show the most used blocks in the block library:
<img width="737" alt="Screenshot 2021-08-02 at 1 51 04 pm" src="https://user-images.githubusercontent.com/677833/127810604-fb5252c6-ff0f-4480-99b0-2d940345b698.png">

It looks like this when switched on:
<img width="340" alt="Screenshot 2021-08-02 at 1 52 05 pm" src="https://user-images.githubusercontent.com/677833/127810668-4a5a81f5-f56f-4b2a-9f07-3215296f1f95.png">

**Comment by NekoJonez** [comment]
Oh I see, I was honestly looking for that in WP.com but I'm looking over it. 

I think this is good enough to solve what I was saying in the first post... Don't you agree @talldan
