### ISSUE TITLE
Single quotes are rewritten as quotes in HTML block and Shortcode blocks

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#33813]
### Description

In some use cases one might need to use single quotes instead of quotes. It could be editorial (this bug report form suggests step by step instructions with `1. Go to '...'`) as one example. Or it could be technical, such as for use in shortcodes.

Originally reported [here](https://wordpress.org/support/topic/prevent-changing-single-quotes-to-double-quotes/), the following shortcode is broken on save, as the single quotes inside the data attribute are rewritten to quotes:

```
[tagged_heading heading="h2" text="Lorem ipsum dolor sit amet <mark data-tooltip='tooltip'></mark> sodales dui."]
```

This is an issue both in the HTML block, and the Shortcode blocks:

<img width="720" alt="Screenshot 2021-08-02 at 12 49 19" src="https://user-images.githubusercontent.com/1204802/127850292-d35aa35a-574d-4779-9ace-5c285d5694c7.png">

<img width="701" alt="Screenshot 2021-08-02 at 12 47 41" src="https://user-images.githubusercontent.com/1204802/127850294-2d6b9688-0a2c-4b50-8569-769bf1d9f69a.png">

Arguably neither block should rewrite/beautify their contents.

### Step-by-step reproduction instructions

1. Create a new post
2. Insert an HTML block, and paste the code above
3. Save, then reload the page.

_The reload is necessary for the editor to reflect the saved content._

### Expected Behavior

The single quote should stay intact.

### Current Behavior

Observe that the content of the shortcode has been edited to replace the single quotes.

**Comment by egornmore** [comment]
Found a fast-fix solution, which works for me. Single quotes will stay intact if they are placed on the first level and double quotes inside of the single quotes. So just swap them e.g. `[tagged_heading text='Lorem ipsum dolor sit amet <mark data-tooltip="tooltip"></mark> sodales dui.']`

**Comment by Thelmachido** [comment]
I was able to reproduce this as shown below: 

https://user-images.githubusercontent.com/41231764/186425887-732f45d1-ad52-4fda-8ff7-3fad4bff86d1.mov

WordPress 6.0.1

Gutenberg 13.9.0

Theme TT2

**Comment by Rale379** [comment]
I'm having a similar issue, but with the text inside a heading block. 
In the editor, a single quote is shown. but, on the frontend, the quote is replaced by a smart (curly) quote.
If I use an HTML block and substitute the quote for and HTML entity - &#39;  - the quote is preserved.
![image](https://github.com/user-attachments/assets/6646a9d0-6dbb-414d-ae2b-66a3f18dd50c)
![image](https://github.com/user-attachments/assets/5a317b6d-409e-40de-8dbf-2f1f23dfd5bd)
