### ISSUE TITLE
Media Library button misaligned on image block for small screens

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#33834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

The media library button is misaligned on small screens. It's aligned to the left while the other to items are centre aligned.

### Step-by-step reproduction instructions

On a small screen browser (579px wide or less):

1. Create a new post
2. Insert an image block
3. Observe the media library button is misaligned 

### Expected Behavior

Aligned buttons

### Current Behavior

Buttons are misaligned. The actions still work so purely a cosmetic issue.

### Screenshots or screen recording (optional)

Screen shot from a 320px wide screen, although it appears to happen at 579px wide and lower.

![Screen Shot 2021-08-03 at 2 10 02 pm](https://user-images.githubusercontent.com/519727/127959304-44cfb390-9e28-4484-b399-c6482efb3991.png)

### WordPress Information

5.9-alpha

### Gutenberg Information

11.1.0. Also happens in WP Core with Gutenberg disabled.

### What browsers are you seeing the problem on?

Firefox

### Device Information

Desktop

### Operating System Information

macOS Big Sur 11.4

**Comment by Mamaduka** [comment]
I think this issue was fixed in a recent plugin release.

![CleanShot 2022-03-29 at 19 53 57](https://user-images.githubusercontent.com/240569/160653695-0dd4fe6f-82a0-42d1-a5b5-33379434aea5.png)

**Comment by Thelmachido** [comment]
I can also confirm that this is no-longer an issue, tested on a 300px wide screen

<img width="501" alt="Untitled 4" src="https://user-images.githubusercontent.com/41231764/186426552-5bd13346-dcab-49d7-b6e4-6ed800c0dd0a.png">
 
Closing this issue
