### ISSUE TITLE
Post settings: Featured Image preview is too small

### ISSUE THREAD

**Issue by gavande1** [WordPress/gutenberg#33837]
## What problem does this address?
By default, the featured image preview uses the `post-thumbnail` version of an image. In Gutenberg, the featured image component first tries to use that value and otherwise uses the fallback value of the `thumbnail`. So, if `post-thumbnail` is not available the featured post thumbnail looks small and doesn't cover the full available area. 

Before Screenshot: 
![](https://cldup.com/tsG0XJkLW0.png)

## What is your proposed solution?

 The `thumbnail ` image is too small to cover the area and set bad expectations. So using the `full` version image instead of using the `thumbnail` version of the featured post image as a fallback.
 
To resolve this issue changing default fallback size from `thumbnail` to `full` can be done: https://github.com/WordPress/gutenberg/blob/6e308bf38f997f229379ea57fce82461a5bba084/packages/editor/src/components/post-featured-image/index.js#L75-L80

After Screenshot:
![](https://cldup.com/O_FTeUbveM.png)

**Comment by jordesign** [comment]
@gavande1  - just checking back on this issue - is it still relevant in the current state of the editor?

**Comment by gavande1** [comment]
I don't think so. We can close the issue if needed.
