### ISSUE TITLE
Between block inserter missing plus button on small/mobile screens

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#33836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

On small/mobile/narrow screens the between block inserter is missing the plus button on both the posts and widgets screen.

### Step-by-step reproduction instructions

On a small screened device (or desktop with the browser squished narrow):

1. Create a new post
2. Insert at least two blocks
3. Hover between the blocks to activate the inserter
4. Observe the blue line is displayed but the plus button is not

### Expected Behavior

Able to add blocks between existing blocks on narrow screens.

### Current Behavior

Unable to add blocks between two existing blocks as the inserter is missing the clickable plus icon. 

### Screenshots or screen recording (optional)

![Screen Shot 2021-08-03 at 2 31 13 pm](https://user-images.githubusercontent.com/519727/127961226-385148f5-97e4-4068-9959-27bbc3e9143f.png)

Screenshot from widgets editor although the same issue is applicable in the post editor. The inserter appears identical.

### WordPress Information

5.9-alpha

### Gutenberg Information

11.1.0, also present in WP without GB active.

### What browsers are you seeing the problem on?

Firefox

### Device Information

Desktop

### Operating System Information

macOS Big Sur 11.4

**Comment by jordesign** [comment]
Hey @peterwilsoncc  - Just checking back through some older issues. I'm seeing this as resolved in my testing in WP6.3 - with the inserted correctly showing the [+].

I'll close this for now - but if you spot that it's still happening somewhere please feel free to re-open.

<img width="342" alt="Screenshot 2023-08-18 at 10 05 11 am" src="https://github.com/WordPress/gutenberg/assets/1842363/ba1041aa-364b-4286-a21a-a8fe1675a328">
