### ISSUE TITLE
Add inline formatting items to better manage line breaks

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#33855]
## What problem does this address?

With responsive design and big font sizes, hard line breaks (`<br>`) don't help to have a good looking text on all viewport sizes.

To keep a good wrapping for headings or other large texts, we need to use non breaking spaces and the [`<wbr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) tag.

## What is your proposed solution?

It would be really great to be able to insert these tags from the inline formatting tools.

Related: #31401

**Comment by priethor** [comment]
Hi @benoitchantre !

Could you provide an example of a block composition that would benefit from this enhancement?

Thanks!

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @benoitchantre hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
