### ISSUE TITLE
TextControl type=number with min={0} after last update doesn't work for value 0.

### ISSUE THREAD

**Issue by katarzynapawelczak** [WordPress/gutenberg#33854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

TextControl for type=number with min={0} after last update doesn't work for value 0. When I try to put value 0, I get default value instead.

### Step-by-step reproduction instructions

1. Create a TextControl with type="number" and min={0}, code snippet below.
2. In Gutenberg try to set 0 value in this TextControl.

### Expected Behavior

With min={0} I can provide 0 value into TextControl (with type="number").

### Current Behavior

With min={0} I can't provide 0 value into TextControl (with type="number"). Instead, I get a default value.

### Code snippet (optional)

  `<TextControl
                  label="Border radius"
                  type="number"
                  onChange={(newValue) =>
                    props.setAttributes({
                      borderRadius: parseInt(newValue),
                    })
                  }
                  min={0}
                  value={props.attributes.borderRadius}
                />`

### WordPress Information

WordPress 5.8.

### Device Information

I have checked on Chrome and Firefox, and it's the same.

**Comment by talldan** [comment]
@katarzynapawelczak I tried testing this and couldn't reproduce the issue. Looking at the code, the `TextControl` component doesn't do anything special with the `min` prop, it just passes it straight to the dom element.

When you say you get a default value, what value is that? What does the declaration for your borderRadius attribute look like?

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @katarzynapawelczak hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
