### ISSUE TITLE
Typing swiftly into the Image Alt Text field results in incorrect text entry

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#33856]
## Description
When typing quickly into the Image Alt Text field, duplicate characters appear to be inserted into the field, resulting in incorrect text. This occurs on both iOS and Android. 

## Step-by-step reproduction instructions
1. Launch the editor.
2. Insert and Image block.
3. Tap the settings cog button to open the block settings.
4. Tap the Alt Text field.
5. Attempt to enter a sentence describing the image very quickly.

## Expected behaviour
The text typed is entered into the field. 

## Actual behaviour
The text is sometimes duplicated. 

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/438664/128053255-c234257f-9fff-4341-ba0d-7cd8ba9c4b37.mp4

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: 11.10
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Samsung Galaxy S20 / iPhone SE
- Operating system: Android 11 / iOS 14.1
- WordPress app version: 17.8

**Comment by SiobhyB** [comment]
Assigning myself, as per this comment: https://github.com/WordPress/gutenberg/issues/33857#issuecomment-896033256

**Comment by SiobhyB** [comment]
Closing, as this was fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/3818.
