### ISSUE TITLE
Once I've installed "insert headers and footers" plugin, I can not use Gutenberg editor any more.

### ISSUE THREAD

**Issue by shrewdacumen** [WordPress/gutenberg#33865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

it does not work but caused errors on every web pages after installed it.

It collides with the current version of Gutenburg editor of the latest WordPress.
Because it is too serious that I had to remove the plugin "insert headers and footers" and then reset the plugin database.

Among many error messages, what I've gotten from Gutenberg editor after having installed the plugin:
"Your site doesn't include support for the "themeisle-blocks/advanced-column block". You can leave the block intact, convert its content to a custom HTML block”

However, when I stop using the Gutenberg block editor (disable Gutenberg plugin), I can properly edit all pages with class editor..

And every page has HTML error messages as if they are the wrong syntax in HTML.

And the followings are the record showing all the plugins that I've installed:
a:44:{i:0;s:45:"addons-for-elementor/addons-for-elementor.php";i:1;s:39:"advanced-reset-wp/advanced-reset-wp.php";i:2;s:51:"all-in-one-wp-migration/all-in-one-wp-migration.php";i:3;s:47:"better-search-replace/better-search-replace.php";i:4;s:41:"better-wp-security/better-wp-security.php";i:5;s:33:"breadcrumb-tmc/breadcrumb-tmc.php";i:6;s:32:"buymeacoffee/buy-me-a-coffee.php";i:7;s:50:"cf7-widget-elementor/void-cf7-widget-elementor.php";i:8;s:36:"contact-form-7/wp-contact-form-7.php";i:9;s:39:"disable-gutenberg/disable-gutenberg.php";i:10;s:50:"disk-usage-sunburst/rbdusb-disk-usage-sunburst.php";i:11;s:39:"elementor-templater/elementemplator.php";i:12;s:23:"elementor/elementor.php";i:13;s:45:"enable-media-replace/enable-media-replace.php";i:14;s:31:"facebook-feed/facebook-feed.php";i:15;s:43:"google-analytics-dashboard-for-wp/gadwp.php";i:16;s:39:"icegram-rainmaker/icegram-rainmaker.php";i:17;s:19:"icegram/icegram.php";i:18;s:19:"imagify/imagify.php";i:19;s:23:"loginizer/loginizer.php";i:20;s:37:"mailchimp-for-wp/mailchimp-for-wp.php";i:21;s:28:"menu-shortcode/shortcode.php";i:22;s:37:"nivo-slider-lite/nivo-slider-lite.php";i:23;s:37:"paypal-donations/paypal-donations.php";i:24;s:37:"post-types-order/post-types-order.php";i:25;s:33:"press-elements/press-elements.php";i:26;s:29:"rss-importer/rss-importer.php";i:27;s:47:"selfhost-google-fonts/selfhost-google-fonts.php";i:28;s:30:"seo-by-rank-math/rank-math.php";i:29;s:43:"themeisle-companion/themeisle-companion.php";i:30;s:20:"visualizer/index.php";i:31;s:33:"w3-total-cache/w3-total-cache.php";i:32;s:33:"widget-context/widget-context.php";i:33;s:41:"wordpress-importer/wordpress-importer.php";i:34;s:27:"wp-asset-clean-up/wpacu.php";i:35;s:43:"wp-easy-testimonial/wp-easy-testimonial.php";i:36;s:29:"wp-mail-smtp/wp_mail_smtp.php";i:37;s:23:"wp-meteor/wp-meteor.php";i:38;s:39:"wp-product-review/wp-product-review.php";i:39;s:31:"wp-statistics/wp-statistics.php";i:40;s:35:"wp-youtube-lyte/wp-youtube-lyte.php";i:41;s:41:"wpcat2tag-importer/wpcat2tag-importer.php";i:42;s:24:"wpforms-lite/wpforms.php";i:43;s:33:"wps-hide-login/wps-hide-login.php";}

### Step-by-step reproduction instructions

1. install wp 5.8
2. install the theme "Photo Journal"
1. install the "insert header and footers" plugin.
2. try to edit any page or post.
3. then you can see the message "Your site doesn't include support for the "themeisle-blocks/advanced-column block". You can leave the block intact, convert its content to a custom HTML block”
4. Even after removing the "insert header and footers" plugin and unloaded all plugins, changed to the default theme, the problem persists.

### Expected Behavior

If the plug is the source of the problem. it should be back to normal after resetting all the pluggins.

The only solution I have is returning to the classic editor where I have no problem as such.

### Current Behavior

 what I've gotten from Gutenberg editor on every page and post is:
"Your site doesn't include support for the "themeisle-blocks/advanced-column block". You can leave the block intact, convert its content to a custom HTML block”

### Screenshots or screen recording (optional)

[https://drive.google.com/file/d/18oNzKS5z0eWux-00UzEs-SLo0Xyi6jAZ/view?usp=sharing](url)
![error message 2nd from Gutenberg editor, Aug 03, 2021](https://user-images.githubusercontent.com/684684/128116902-e68d1a43-474a-4e01-b7a0-6df9d2d4ccc9.png)

### Gutenberg Information

I don't know the version.
WP 5.8 has the gutenberg block editor.

### What browsers are you seeing the problem on?

Safari

### Device Information

Desktop (macOS 11.5) M1 and iPhoneSE2, iPad Pro 10.5', iPad Pro 12.9' and iPhone6S plus.

### Operating System Information

macOS 11.5 ARM64 M1 Apple Silicon
and iOS 14.7.1, iPadOS 14.7.1

**Comment by jasmussen** [comment]
Thanks for the report. I can't immediately reproduce this issue running Photo Journal and Insert Headers and Footers plugins:

<img width="1474" alt="Screenshot 2021-08-04 at 15 47 21" src="https://user-images.githubusercontent.com/1204802/128192301-fe1068ea-71f1-4872-96d9-6c27a3ef3b7e.png">

<img width="1164" alt="Screenshot 2021-08-04 at 15 47 40" src="https://user-images.githubusercontent.com/1204802/128192308-d51df140-a18b-4311-98d3-bc5b19b070c9.png">

From what I can tell from the error message, you are missing the "Advanced Columns" block entirely. That block, from what I can tell, is coming from a plugin called "Gutenberg Blocks and Template Library by Otter". Can you try and install that plugin and see if it solves your issue? For me that adds a "Section" block which under the hood registers itself as `themeisle-blocks/advanced-columns`, which appears to be the missing block.

<img width="780" alt="Screenshot 2021-08-04 at 15 53 09" src="https://user-images.githubusercontent.com/1204802/128193133-65a0bacb-3bae-47cb-97ae-46b6a4277dfa.png">

<img width="1474" alt="Screenshot 2021-08-04 at 15 52 52" src="https://user-images.githubusercontent.com/1204802/128193149-9e4e4bcb-d9e6-4b69-bd6b-ebdaac7f22e3.png">

**Comment by jasmussen** [comment]
For now I'm going to close this one as a fulfilled help request, but feel free to come back in case that was in error.
