### ISSUE TITLE
Change core/code value with custom fields

### ISSUE THREAD

**Issue by nhatrangnet** [WordPress/gutenberg#33864]
I need to change core/code value by the custom fields value.
With this way I can change/update post content by changing custom field value, and it will apply to one or multi core/code.

Can anyone suggest me a way to do it, thanks a lot.

**Comment by stokesman** [comment]
Perhaps you could get it done with the [`render_block`](https://developer.wordpress.org/reference/hooks/render_block/) filter. I think a better place for questions like this would be the [Developing with WordPress Forum](https://wordpress.org/support/forum/wp-advanced/) or maybe https://wordpress.stackexchange.com/.

**Comment by annezazu** [comment]
Going to close this out since I agree that this is more of a help request :)
