### ISSUE TITLE
Confusing navigation block inserter menu / block library

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#33867]
## What problem does this address?
The navigation block has a problem where it has a lot of inner block types and variations that aren't very well organised:
<img width="351" alt="Screenshot 2021-08-04 at 4 32 20 pm" src="https://user-images.githubusercontent.com/677833/128149395-b5d205fc-ccd0-48b9-9c93-87b5ca8c5b36.png">

Most of the time the user will want to insert either a link or maybe create a submenu as primary actions (https://github.com/WordPress/gutenberg/pull/33775) and in less frequent cases add social icons or a search bar.

As seen in the screenshot, there are lots of variations of the navigation link and the right option isn't always clear. Sorting by commonly used blocks also isn't necessarily helpful here because there are so many types that it's easy for something important to drop out of the top 6.

## What is your proposed solution?
There are two things that might help:
- Allow the sort order of blocks in the quick inserter to be predefined. (e.g. Link and Dropdown always stay as the first two)
- Make the process for inserting variations a two-step process. First a user would select 'Link' as the type of block they want to insert, and then the quick inserter could show the various types of link, they might choose 'Post Link' or 'Page Link' at that step. Essentially the main 'Link' block type in the quick inserter almost acts as a folder of variations.

## Update: Other solutions
I'm updating this description with some of the other solutions being discussed in the comments of this and other issues as they come up:
- Avoid showing navigation block variations in the inserter (just show 'Link') and let the Link UI decide what type of block should be created (https://github.com/WordPress/gutenberg/issues/33867#issuecomment-892485843)
- The appender only inserts Page Link blocks as a kind of default blocks. Other blocks are available from the block library using the `+` button in the editor header . Also enable the `/` inserter in the link block. (https://github.com/WordPress/gutenberg/issues/34041)
- Paginated quick inserter (https://github.com/WordPress/gutenberg/issues/33867#issuecomment-892648105)

**Comment by getdave** [comment]
Going to copy/paste my thoughts we discussed in WP Slack https://wordpress.slack.com/archives/C01KDAZJMQ9/p1628066836003800.

Possibly slightly off topic and may require another issue - let me know what you think?

Quick thought: why can’t we just make the link UI more intelligent and avoid asking users to have to select so many things?

I mean…why do I need to know the difference between Post and Page.

I can’t tell you how many times I had to explain this concept to my clients when I worked in agencies. Most folks just don’t care. They want a link to some content they created 😄 .

Could we at least look to ditch the distinction (from a user perspective) of Post vs Page (and possibly also Custom). The other types are more complex.

**Comment by talldan** [comment]
This is true.

There was a related discussion here about the number of blocks in the inserter - https://github.com/WordPress/gutenberg/pull/31584#pullrequestreview-678632496.

Definitely fine to pivot on this idea to something else. I'm also supportive of removing the variations from the inserter.

**Comment by getdave** [comment]
Just realise - the reason we have variations is because we need to know the type to persist when saving in order that it will be backwards compatible with the existing Menus system.

Perhaps we can change this so that when the link is created we discern the `type` (or `kind`) from the created link rather than relying on knowing it's variation type in advance.

**Comment by jasmussen** [comment]
Transforming from one type of menu item into another in-situ, such as transforming from a custom link block to a page link when linking to a page, would be a nice and mostly invisible tweak that could benefit things even without unifying multiple menu item type blocks. But even beyond that, we'll still probably need to scale the quick inserter better, as is suggested here. Social Links has a similar issue.

A while back I doodled this paginated version, with the 3rd item being the button to open the inserter sidebar:

<img width="440" alt="Quick Inserter" src="https://user-images.githubusercontent.com/1204802/128187010-490762cd-a178-434a-9f62-7bffa2ef2cd0.png">

It wouldn't solve how the frecency is often not what you'd expect it to be, but at least it might show all items right there.

**Comment by talldan** [comment]
> It wouldn't solve how the frecency is often not what you'd expect it to be, but at least it might show all items right there.

Yep, I think this is going to always be a valid part of the issue, because the first time a user interacts with the nav block the blocks that are usable outside of navigation (social icons, spacer) are likely to be first in the list.

The nav block really needs link to always be first, and if the dropdown block is merged, that should probably be second.

**Comment by jasmussen** [comment]
> The nav block really needs link to always be first, and if the dropdown block is merged, that should probably be second.

Agreed. Outside of making the frecency system smart enough to do this (or removing it entirely), it seems like it'd be useful with some sort of pinning system, especially if https://github.com/WordPress/gutenberg/pull/33775 comes to pass in a way that potentially expands the list of items drastically.

**Comment by talldan** [comment]
I fell into a trap of being solution oriented with this issue, so I've renamed it and updated the description to also contain some of the discussed options.

**Comment by talldan** [comment]
I'll close this, things have changed quite a bit.
