### ISSUE TITLE
Access Template Editor Outside of Post/Page and On the Sidebar

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#33869]
## What problem does this address?

The problem is that in order to access the template editor, a user has to open up a brand new post or an existing post. Access to the template editor can be difficult to find.
## What is your proposed solution?

The settings for the template editor should also be available in the WordPress sidebar as a new tab under pages. Showing the options "All Templates" and "Add New." This will reduce the number of clicks it takes to add a new template or edit a template if the user is not currently editing a page or post.

It will help users quickly view and access the templates they created.

If the theme does not support the new template feature, display a message showing this to the user. Also, display a link to the user on how to enable this feature for the theme.

**Comment by jasmussen** [comment]
You should already be able to access the template editor from the admin sidebar, under "Appearance":

<img width="1045" alt="Screenshot 2021-08-04 at 14 28 08" src="https://user-images.githubusercontent.com/1204802/128180721-a6b90100-9c6b-4cc3-a314-75eed4321b59.png">

Can you let me know if that's what you're looking for, or where you referring to something else?

**Comment by youknowriad** [comment]
@jasmussen I think what she's referring to is that the screen you're showing is not yet available in Core. It's not clear yet if this will land as is or we'll only keep the site editor but on the next couple major WP releases, we'll have some form of templates management outside the post editor for sure.

**Comment by jasmussen** [comment]
My apologies! I keep running the plugin so I don't see the parts that are missing. So the good news is, even if that screen isn't here yet, it will be 👍 👍

**Comment by jordesign** [comment]
Looping back to this old issue - @jasmussen  it looks like these menu items have been removed in core. Is it worth revisiting if they can be brought back? Have an entry point directly to templates is really handy (and in some ways a smaller change of editing-model than the Site Editor)

**Comment by jasmussen** [comment]
@jordesign you're referring to the legacy "Theme Editor" item from the Appearance menu, correct? 

* When you use a classic or hybrid themes, it should still be there, under appearance.
* When using a block theme, it's under Tools > Theme File Editor

<img width="367" alt="Screenshot 2022-03-03 at 08 33 11" src="https://user-images.githubusercontent.com/1204802/156517867-1ebffe5e-43da-405d-b48f-352eb8bd4c37.png">

In both cases, the feature is one that most of the time you should not be using. But this is especially true for block themes, where the Site Editor provides a safer, wysiwyg, means to edit your templates without replacing them.

**Comment by jordesign** [comment]
Jey @jasmussen  - I'm referring to the fact you used to be able to access a list of templates, and template parts from within WP Admin directly (as shown in your screenshot above). They don't seem to exist any more under 'Appearance' - only Themes and Site Editor

![](https://user-images.githubusercontent.com/1204802/128180721-a6b90100-9c6b-4cc3-a314-75eed4321b59.png)
[link to image](https://user-images.githubusercontent.com/1204802/128180721-a6b90100-9c6b-4cc3-a314-75eed4321b59.png)

**Comment by jasmussen** [comment]
Ah, they've moved inside the site editor:
![templates](https://user-images.githubusercontent.com/1204802/156524447-4ccf442f-483a-47b1-86d7-c820827fb9fc.gif)

Hope that's what you're looking for.

**Comment by jordesign** [comment]
With these now well established within the Site Editor (and the future of WP will be to manage templates in that inteface) - I'll mark this as completed.
