### ISSUE TITLE
Unify the patterns for adding an audio and video

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3386]
Right now there are differences between the two. The differences start on the placeholder:

![2017-11-08 at 14 08](https://user-images.githubusercontent.com/253067/32553282-4e088006-c48e-11e7-818c-6d76fe6d197d.png)

If we are allowing to 'use URL' then we should have this on video also. Are there technical limitations to this beyond the audio files? Is this the reason we don't?

**Comment by afercia** [comment]
Couple additional points:
- the "instructions" wording could be a bit more consistent, not sure why the audio one says also "or upload a new one" and the video one doesn't
- aside: the placeholder text `Enter URL of audio file here…` will likely be longer when translated in other languages and will end up being partially cut-off
