### ISSUE TITLE
Bring back visibility setting functionality in widget areas

### ISSUE THREAD

**Issue by ashleyleia** [WordPress/gutenberg#33877]

**Comment by priethor** [comment]
Hi @ashleyleia !

Could you provide some more information on this?

Thanks!

**Comment by ashleyleia** [comment]
As an example, I already had an old custom html widget in my sidebar. Now, with the Gutenberg editor handling the widget area, this is what it looks like, and how I can change the visibility so it's hidden on a particular page and its child pages:

<img width="289" alt="Screen Shot 2021-08-04 at 8 06 08 AM" src="https://user-images.githubusercontent.com/77593027/128205767-a13f6856-1167-4d0e-a619-94a5460b5472.png">

<img width="277" alt="Screen Shot 2021-08-04 at 8 06 19 AM" src="https://user-images.githubusercontent.com/77593027/128205802-a3bcb944-b501-4782-aa9f-b7187f3351b3.png">

If I now try to create a new block in the widget area, there is no custom html legacy widget available.

<img width="284" alt="Screen Shot 2021-08-04 at 8 09 50 AM" src="https://user-images.githubusercontent.com/77593027/128206039-8dc99d54-a4ef-4750-badd-00111645fb29.png">

So instead, I have to create a custom html block. But when I do that, there's no way for me to hide it on certain pages as I was previously able to do with the custom html widget.

<img width="328" alt="Screen Shot 2021-08-04 at 8 06 39 AM" src="https://user-images.githubusercontent.com/77593027/128206191-8e3c70a2-5454-4d60-b7a4-c2d6b57dd5c4.png">


If I didn't already happen to have an existing custom html widget that I could copy and then modify, there would no longer be a way for me to create custom html in my sidebar that was only visible on certain pages.

I happen to have the Wordpress.com business plan, so I can install the Classic Widgets plugin to get back that functionality, but that wouldn't be the case for most Wordpress.com users.

**Comment by priethor** [comment]
Thanks for the detailed update!

**Comment by talldan** [comment]
Hi @ashleyleia, thanks for reaching out. The visibility feature is part of the jetpack plugin. I believe there are plans to reimplement this and there's an issue here tracking adding it to the new screens - https://github.com/Automattic/jetpack/issues/20057.
