### ISSUE TITLE
Provide Block Pattern for Widget + Title to streamline creation of previous Widget screen markup

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#33874]
## What problem does this address?

As discussed at length in https://github.com/WordPress/gutenberg/issues/32723 the previous (non-block based) Widgets screen provided a discrete HTML structure for a "Widget". 

This was:

* Wrapping container element (Widget wrapper)
* Heading element (Widget title)
* Widget (the actual body of the Widget itself).

The new block based editor doesn't do this. Instead each block that is added is treated as a standalone "Widget". This makes is very difficult to replicate the structure of the previous Widgets screen in the new screen. This is often necessary for reasons of backwards compatibility.

## What is your proposed solution?

I've been exploring providing a Block Pattern called "Widget and title". When added this creates:

* `core/group` block with a `class` of `c-widget`.
* [Child] `core/heading` block with a placeholder and a `class` of `c-widget__title`.

All the user then need do is insert their chosen widget block (e.g. Archives) as a sibling of the Heading block (child of the Group) and you have a good replica of the previous structure. 

This avoids the hassle of creating it manually. Here's a demo of a prototype I created by hardcoding some block patterns in the `edit-widgets` package:

https://user-images.githubusercontent.com/444434/128193666-12e2c55e-4327-4db7-9c12-8ad404640577.mp4

In the future we could also explore whether it's possible to automatically transform a standalone Widget block into this Pattern.

**Comment by justintadlock** [comment]
Related: https://github.com/WordPress/gutenberg/issues/26170

**Comment by draganescu** [comment]
This has been solved by the introduction of the Widget Group block.
