### ISSUE TITLE
Site Editor is empty in firefox

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#33873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

With the latest release 11.2.0 the Site Editor returns an empty white screen in Firefox browser. Chrome not affected.

Console shows error: "Uncaught (in promise) TypeError: e.current is undefined" /build/block-editor/index.min.js:81:23487

### Step-by-step reproduction instructions

Activate a FSE/block based theme.
Click 'Site Editor'.
Notice the editor is completely empty.

### Expected Behavior

The Site Editor to load.

### Current Behavior

The Site Editor does not load.

### WordPress Information

5.8

### Gutenberg Information

11.2.0

### What browsers are you seeing the problem on?

Firefox

### Device Information

Desktop

### Operating System Information

Windows 10

**Comment by youknowriad** [comment]
I confirm I have the same issue with Firefox on MacOS

**Comment by creativecoder** [comment]
Note that I'm seeing the problem in Template editing mode in the post editor as well (when using Firefox).

It seems to be related to the iframe loading and ref issues in Firefox. I don't think the [document `load` event callback](https://github.com/WordPress/gutenberg/blob/a4bc4d19c4f7d495c96bce931a72089cc9713c41/packages/block-editor/src/components/iframe/index.js#L244) that sets up the refs for Firefox (according to the code comment there) ever has a chance to execute before the error in `useMultiSelection` crashes the editor.

**Comment by karmatosed** [comment]
I can also confirm I am getting the same issue in Firefox.  It works fine on both my local install and on server when use Safari or another browser.
