### ISSUE TITLE
ServerSideRenderer sends all registered attributes in 5.8

### ISSUE THREAD

**Issue by kenzap** [WordPress/gutenberg#33879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

After latest WordPress 5.8 update all of the blocks that rely on `<ServerSideRender>` have different behaviour for sending attributes. Instead of sending only specified attributes it sends all registered attributes of the block. This in return causes another issue. The backend part of the block that relies on ServerSideRender requires every single attribute to be declared too under PHP version. 

Dealing with large amount of attributes is inconvenient because frontend and backend attributes have to be defined in two different places.

In previous versions of WordPress this was not an issue as `<ServerSideRender>` can only send limited amount of attributes that are specified under [attributes properties](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-server-side-render/#attributes). Is there a simple workaround to register all backend attributes automatically?

Will attributes property of `<ServerSideRender>` element be deprecated in future as currently it makes no sense whether it is used or not?

The only difference is when the attributes property of `<ServerSideRender>` is not specified at all. In this case not a single attribute is being sent to the backend. I have attached a GIF video below.

### Step-by-step reproduction instructions

1. Create a Gutenberg block that relies on backend rendering with the help of `ServerSideRender` element

```
const { __ } = wp.i18n;
const { Component } = wp.element;
const { serverSideRender: ServerSideRender } = wp;
const { InspectorControls, PanelColorSettings } = wp.editor;
const { RangeControl, CheckboxControl, PanelBody, SelectControl, TextControl, TextareaControl } = wp.components;
import { InspectorContainer } from '../commonComponents/container/container';

/**
 * The edit function describes the structure of your block in the context of the editor.
 * This represents what the editor will render when the block is used.
 *
 * The "edit" property must be a valid function.
 * @param {Object} props - attributes
 * @returns {Node} rendered component
 */
export default class Edit extends Component {

    render() {
        const {
            className,
            attributes,
            setAttributes,
        } = this.props;

        return (
            <div className={ className }>
                <InspectorControls
                    setAttributes={ setAttributes }
                    { ...attributes }
                >
                    <PanelBody
                        title={ __( 'General', 'myticket-events' ) }
                        initialOpen={ false }
                    >

                        <RangeControl
                            label={ __( 'Records per page', 'myticket-events' ) }
                            value={ attributes.per_page }
                            onChange={ ( value ) => setAttributes( { per_page: value } ) }
                            min={ 1 }
                            max={ 50 }
                            help={ __( 'Specify the maximum number of events listed per single page.', 'myticket-events' ) }
                        />
                        
                        <TextControl
                            label={ __( 'Category', 'myticket-events' ) }
                            value={ attributes.category }
                            onChange={ ( category ) => setAttributes( { category } ) }
                            help={ __( 'Restrict all records to certain category. To view categories go to Products > Categories section.', 'myticket-events' ) }
                        />
                        
                        <SelectControl
                            label={ __( 'List events', 'myticket-events' ) }
                            value={ attributes.type }
                            options={[
                                { label:  __( 'All', 'myticket-events' ) , value: '' },
                                { label:  __( 'Upcomming', 'myticket-events' ) , value: 'upcomming' },
                                { label:  __( 'Past', 'myticket-events' ) , value: 'past' },
                            ]}
                            help={ __( 'Choose how current time affects listing.', 'myticket-events' ) }
                            onChange={ (type) => setAttributes( { type } ) }
                        />

                        <CheckboxControl
                            label={ __( 'Featured image', 'myticket-events' ) }
                            checked={ attributes.ftImage }
                            onChange={ (ftImage) => setAttributes( { ftImage } ) }
                        />

                        <SelectControl
                            label={ __( 'Query relation', 'myticket-events' ) }
                            value={ attributes.relation }
                            options={[
                                { label:  __( 'AND', 'myticket-events' ) , value: 'AND' },
                                { label:  __( 'OR', 'myticket-events' ) , value: 'OR' },
                            ]}
                            help={ __('This rule tells database how to filter results. If user selects two categories Golf and Swimming AND will show only those events that are in Golf and Swimming simultaneously. If user selects Golf and Swimming categories OR will picks up all events within Golf category and unites them with all events from Swimming category. The more checkboxes user ticks with OR relation the more results will be shown and vice versa if AND is selected.', 'myticket-events') }
                            onChange={ (relation) => setAttributes( { relation } ) }
                        />

                        <SelectControl
                            label={ __( 'Default order', 'myticket-events' ) }
                            value={ attributes.order }
                            options={[
                                { label:  __( 'None', 'myticket-events' ) , value: '' },
                                { label:  __( 'Popularity', 'myticket-events' ) , value: 'popularity' },
                                { label:  __( 'Rating', 'myticket-events' ) , value: 'rating' },
                                { label:  __( 'Newest', 'myticket-events' ) , value: 'newest' },
                                { label:  __( 'Lowest price', 'myticket-events' ) , value: 'lowestprice' },
                                { label: __( 'Highest price', 'myticket-events' ) , value: 'highestprice' },
                            ]}
                            help={ __( 'Choose default sorting method', 'myticket-events' ) }
                            onChange={ (order) => setAttributes( { order } ) }
                        />

                        <RangeControl
                            label={ __( 'Border radius', 'myticket-events' ) }
                            value={ attributes.borderRadius }
                            onChange={ ( borderRadius ) => setAttributes( { borderRadius } ) }
                            min={ 0 }
                            max={ 50 }
                        />

                        <CheckboxControl
                            label={ __( 'Pagination', 'myticket-events' ) }
                            checked={ attributes.pagination}
                            onChange={ (pagination) => setAttributes( { pagination } ) }
                        />

                    </PanelBody>

                    <InspectorContainer
                        setAttributes={ setAttributes }
                        { ...attributes }
                        withPadding
                        withWidth100
                        withBackground
                    />
                </InspectorControls>

                <ServerSideRender
                    block="myticket-events/listing-01"
                    attributes={ {
                        checkSidebar: false,
                        serverSide: true,
                    } }
                    httpMethod="POST"
                />
            </div>
        );
    }
}

```

2. Register various attributes under registerBlockType function

```
registerBlockType( 'myticket-events/listing-01', {
	// Block name. Block names must be string that contains a namespace prefix. Example: my-plugin/my-custom-block.
	title: __( 'MyTicket Listing 1', 'myticket-events' ), // Block title.
	icon: 'shield', // Block icon from Dashicons → https://developer.wordpress.org/resource/dashicons/.
	category: 'layout', // Block category — Group blocks together based on common traits E.g. common, formatting, layout widgets, embed.
	keywords: [
		__( 'myticket events', 'myticket-events' ),
		__( 'Event listing', 'myticket-events' ),
		__( 'Ticket', 'myticket-events' ),
	],
	supports: {
        align: [ 'full', 'wide' ],
    },
	attributes: {
		...blockProps,

        borderRadius: {
            type: 'number',
            default: 5,
        },
		title: {
			type: 'array',
			source: 'children',
			selector: 'h2',
		},
		checkFilter: {
			type: 'boolean',
			default: true
		},
		checkFilter2: {
			type: 'boolean',
			default: true
		},
		filterLocations: {
			type: 'string',
			default: ''
		}, 
```

3. Define any two attributes under `ServerSideRender` element.

```
                <ServerSideRender
                    block="myticket-events/listing-01"
                    attributes={ {
                        checkSidebar: false,
                        serverSide: true,
                    } }
                    httpMethod="POST"
                />
```

4. Save block and verify backend request. Refer to the image below. It sends all registerBlockType registered variables. 

<img width="1163" alt="Screen Shot 2021-08-04 at 5 51 01 PM" src="https://user-images.githubusercontent.com/7790165/128202904-59d82c26-80fa-4143-820c-7b2db5500ba5.png">

### Expected Behavior

After declaring these two variables `checkSidebar: false` and `serverSide: true` only these variables should be present in the query.

```
                <ServerSideRender
                    block="myticket-events/listing-01"
                    attributes={ {
                        checkSidebar: false,
                        serverSide: true,
                    } }
                />
```

### Current Behavior

Currently there are two variables `checkSidebar: false` and `serverSide: true` that are declared in the ServerSideRender component.

```
                <ServerSideRender
                    block="myticket-events/listing-01"
                    attributes={ {
                        checkSidebar: false,
                        serverSide: true,
                    } }
                />
```

However all of the attributes registered under registerBlockType are being sent to the backend. See the image example below.

<img width="1214" alt="Screen Shot 2021-08-04 at 5 40 34 PM" src="https://user-images.githubusercontent.com/7790165/128201043-6f56da04-0a38-4349-b381-80d69a4cdd1f.png">

### Screenshots or screen recording (optional)

![serversiderendering](https://user-images.githubusercontent.com/7790165/128205891-0779cb1b-c0c9-40ce-91a6-0e926c08bbad.gif)

### What browsers are you seeing the problem on?

Chrome, Safari

### Device Information

MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)

### Operating System Information

macOS Big Sur

**Comment by kevin940726** [comment]
I believe this was introduced in #29197.

https://github.com/WordPress/gutenberg/blob/5b8bf518f66b2ba14132d533c00d1199aba2c8f6/packages/server-side-render/src/server-side-render.js#L93

> The backend part of the block that relies on ServerSideRender requires every single attribute to be declared too under PHP version. Dealing with large amount of attributes is inconvenient because frontend and backend attributes have to be defined in two different places.

I don't really understand this part though. Isn't it a good practice to define all the attributes when registering the block? `block.json` could help with this to share between both frontend and backend code. Could you provide an example of when this is heavily inconvenient and impractical?

Though I do agree this could be considered a breaking change, and we should probably have some fix to it.

**Comment by areoimiles** [comment]
I have created a block that is rendered server side. This block is quite customisable and therefore has a lot of attributes. This works fine until I change too many attributes at which point the block displays "This block has encountered an error..." when editing in the block editor.

It looks as though server side blocks are rendered via this url endpoint "/wp-json/wp/v2/block-renderer/block/name" and the attributes are appended to the end of it. This endpoint returns a "414 Request-URI Too Long" if too many attributes are added.

Obviously I can change my server settings to make this work but I don't want the users of my plugin to have to go through this process. Am I missing a simple way around this without having to change server settings?

I think a simple fix would be to make the request to "/wp-json/wp/v2/block-renderer/block/name" within the block editor a POST instead of GET, this way it wouldn't matter how many attributes are added.

Any help on this would be much appreciated.

**Comment by jordesign** [comment]
Hi @kenzap - just checking in on this older issue. Do you still see it happening in recent versions of WordPress?

**Comment by jordesign** [comment]
With no further movement on this issue - I'll close it. Can be re-opened if needed in the future.
