### ISSUE TITLE
Allow specifying "root" page in Page List block

### ISSUE THREAD

**Issue by brylie** [WordPress/gutenberg#33883]
## What problem does this address?

Related to #31063

It would be useful to be able to specify the "root" page in a page list so that only children of that page would render in the list. For example, when allowing users to navigate within a section of a website where the sibling pages are all relevant. 

Similarly, it would be useful to control the depth rendered in the list.

## What is your proposed solution?

Basically, the Gutenberg Page List block should emulate the `wp_list_pages` method, allowing users to specify the `child_of`, `depth`, and other related properties.

In PHP, the code for rendering sibling pages 

```php
<?PHP
     $parent = get_parent_page();

     wp_list_pages(
          array(
               'child_of'  => $parent,
               'show_date' => '',
               'depth'     => 3,
               'title_li'  => '',
          )
     );

?>
```

**Comment by talldan** [comment]
I think there are existing issues for this - #31063 and #29585, so I'll close this one as a duplicate.

Thanks for reaching out though.

edit: Oh, I see this is slightly different. Still, I think it'd be worth rolling this into #31063 as it's so similar. I'll add a comment there.
