### ISSUE TITLE
Removing Block Types per the method in the developer guide doesn't work on Widgets Screen

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#33884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

There's a method described in the Block Editor reference guide for removing block types, that works perfectly on the normal Post Editor: https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#removing-blocks

This method does not work on the new Widgets screen. 

It's worth noting that the following:
allBlocks = wp.blocks.getBlockTypes(); 
Post->New : this returns all block types
Appearance->Widgets : this is empty

### Step-by-step reproduction instructions

Use the code snippet provided here in a basic plugin (or append to functions.php): https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#removing-blocks

### Expected Behavior

the core/verse block will be unavailable on the Widgets screen

### Current Behavior

the core/verse block IS available on the Widgets screen

### Code snippet (optional)

// my-plugin.js
wp.domReady( function () {
    wp.blocks.unregisterBlockType( 'core/verse' );
} );

<?php
// my-plugin.php
 
function my_plugin_deny_list_blocks() {
    wp_enqueue_script(
        'my-plugin-deny-list-blocks',
        plugins_url( 'my-plugin.js', __FILE__ ),
        array( 'wp-blocks', 'wp-dom-ready', 'wp-edit-post' )
    );
}
add_action( 'enqueue_block_editor_assets', 'my_plugin_deny_list_blocks' );

### WordPress Information

5.8

### Gutenberg Information

Not Installed

### What browsers are you seeing the problem on?

Chrome

### Device Information

Desktop

### Operating System Information

Windows 10

**Comment by kevin940726** [comment]
It's working for me though. Note that you'll have to change `wp-edit-post` to `wp-edit-widgets` in the dependency array to specifically wait for the Widgets screen registered the block.

```diff
<?php
// my-plugin.php
 
function my_plugin_deny_list_blocks() {
    wp_enqueue_script(
        'my-plugin-deny-list-blocks',
        plugins_url( 'my-plugin.js', __FILE__ ),
-        array( 'wp-blocks', 'wp-dom-ready', 'wp-edit-post' )
+        array( 'wp-blocks', 'wp-dom-ready', 'wp-edit-widgets' )
    );
}
add_action( 'enqueue_block_editor_assets', 'my_plugin_deny_list_blocks' );
```

Also worth noting that `wp.blocks.getBlockTypes()` returns the full list of block types for me in the Widgets screen too. There might be something else going on in your environment?

**Comment by MadtownLems** [comment]
Hey thanks a lot, changing the dependency to wp-edit-widgets has made it work for me also now! 🙏

Unsure if the documentation I referenced should be updated or not. Unsure if it's intended for just the Post Editor or also for block-based Widgets.

Thanks again!

**Comment by kevin940726** [comment]
It's actually mentioned in the doc:

> You want your unregister code to run last. The way to do that is specify the component that is registering the block as a dependency, in this case `wp-edit-post`.

If you think there's room for improvement, feel free to suggest changes and submit a PR! :)

Happy to help!
