### ISSUE TITLE
Query Block - Output Post Class within the editor for accurate styling

### ISSUE THREAD

**Issue by marktimemedia** [WordPress/gutenberg#33887]
## What problem does this address?
Loops that are build with the Query Block currently output the `post_class` on each `li` element in the frontend, which is great! This allows me as a theme developer to style the query block differently depending on which post type is being queried, or inherit styles I'm using for traditional archives.

<img width="465" alt="Screen Shot 2021-08-04 at 12 40 28 PM" src="https://user-images.githubusercontent.com/5798380/128228685-d5dc2ba6-ef07-4831-8dc6-e3429b425b69.png">
<img width="873" alt="Screen Shot 2021-08-04 at 12 43 18 PM" src="https://user-images.githubusercontent.com/5798380/128229059-1572ede5-41ae-4171-aa41-5db2593fe505.png">

However, the `post_class` is not output within the editor, meaning the content manager/admin will not see any of my custom styles when they are editing their content.
<img width="367" alt="Screen Shot 2021-08-04 at 12 44 13 PM" src="https://user-images.githubusercontent.com/5798380/128229388-960f5100-98e0-4696-8273-d50fff83ca27.png">
<img width="834" alt="Screen Shot 2021-08-04 at 12 43 37 PM" src="https://user-images.githubusercontent.com/5798380/128229401-4cffbdfc-16a9-42f1-9694-917aee2bf5f6.png">

## What is your proposed solution?
Dynamically output the `post_class` when the content manager/admin selects a post type to display in the Query Block, so that the editor styling can match the frontend styling

**Comment by huubl** [comment]
I have created a pull request to address this issue: https://github.com/WordPress/gutenberg/pull/60642.

**Comment by ntsekouras** [comment]
Fixed here: https://github.com/WordPress/gutenberg/pull/60642
