### ISSUE TITLE
Add icon for reusable blocks and update template part icon

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#33897]
## What problem does this address?

At the moment, reusable blocks don't have a dedicated icon. When only a single block is reused, that block's icon will be leveraged. When multiple blocks are reused, a default block icon is used. Separately, #30338 details how template part icons can be confusing, in part due to their detail when seen in the list view mixed with other.

## What is your proposed solution?

Create new icons for reusable blocks and template parts that speak to their linked/symbolic and structural nature, to be used in the main canvas, and in the List View:

![mockup](https://user-images.githubusercontent.com/1204802/128332604-68c3c6b0-d3b0-46c0-8c5d-89304f8c3b7e.png)

Shown in this mockup:

- A solid rhomboid symbol for template parts
- An outlined rhomboid symbol for reusable blocks.

The icons are stacked to indicate that they are "linked" — editing one edits it everywhere. By sharing the overall silhouette, the relationship between template parts and reusable blocks are hinted at. They are similar, but not the same. By being generic icons reused across the list view, the structural nature of those block types become implied, clearly differentiating them from content.

For situations where you create template parts, we keep the individual template part icons around. They are useful in the creation flow to indicate the position and usage of the part, and the added context of this creation flow helps dispel confusion, for example in #29295:

<img width="298" alt="a" src="https://user-images.githubusercontent.com/1204802/128333827-7642d66a-e0ec-4268-8f9b-627519830d31.png">

The icons would likely also be useful in the flow when you:

- assign a template part to an "area"
- when you create a new template part (and want to assign to an area)
- in the W sidebar as you are browsing different headers and footers
- the header area of the editor on isolated template part mode
- for browsing patterns for a specific area

**Comment by mtias** [comment]
Let's add these ones, I think it adds a layer of clarity that would be useful to have on these symbolic blocks. It should work a bit better once we get to coloring parts and reusable blocks, too.

**Comment by ntsekouras** [comment]
Fixed by: https://github.com/WordPress/gutenberg/pull/34002
