### ISSUE TITLE
Navigation Link - undo trap when added to inner block controllers via patterns.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#33908]
### Description

Inserting a block pattern that contains navigation-link components inside an inner block controller (such as a template part or reusable block) creates an undo trap.  After the pattern with the navigation link is added, it is no longer possible to undo any previous actions.

Example of the navigation section of a problematic pattern:
```
	<!-- wp:navigation {"orientation":"horizontal","itemsJustification":"center","align":"full","style":{"color":{"background":"#ececec"}}} -->
		<!-- wp:navigation-link {"label":"Home","url":"http:\/\/Home"} /-->
		<!-- wp:navigation-link {"label":"About","url":"http:\/\/About"} /-->
		<!-- wp:navigation-link {"label":"Contact","url":"http:\/\/Contact"} /-->
	<!-- /wp:navigation -->
```
			
related - https://github.com/WordPress/gutenberg/issues/8119

### Step-by-step reproduction instructions

1. Register a new block pattern for a template part that contains navigation-link blocks in the markup (this can be done by adding to the list in `lib/block-patterns.php` ).  an example of a pattern to add for in the array in `lib/block-patterns.php`:
```
		'tp-test'                 => array(
			'title'      => _x( 'tp test', 'Block pattern title', 'gutenberg' ),
			'blockTypes' => array( 'core/template-part/header' ),
			'content'    => '<!-- wp:group {"align":"full","style":{"color":{"background":"#ececec"}}} -->
			<div class="wp-block-group alignfull has-background" style="background-color:#ececec;"><div class="wp-block-group__inner-container">
			<!-- wp:navigation {"orientation":"horizontal","itemsJustification":"center","align":"full","style":{"color":{"background":"#ececec"}}} -->
			<!-- wp:navigation-link {"label":"Home","url":"http:\/\/Home"} /-->

			<!-- wp:navigation-link {"label":"About","url":"http:\/\/About"} /-->

			<!-- wp:navigation-link {"label":"Contact","url":"http:\/\/Contact"} /-->
			<!-- /wp:navigation --></div></div>
			<!-- /wp:group -->',
		),
```
2. Load the site editor.  Insert a "Header" block.
3. Select "New header" from the placeholder block that was just inserted.  The pattern you just added should appear as the first option, click "Choose" and create your template part.
4. Press 'undo'. Notice you are unable to undo any previous actions in the editor.

Similarly, this can be reproduced in the post editor by adding this pattern inside a reusable block.

### Expected Behavior

The 'undo' to work as expected, leading us back to the placeholder and any previous actions:

![undo-works-on-core](https://user-images.githubusercontent.com/28742426/128402433-98323f87-6c6e-463f-8455-4011a2c73c06.gif)

### Current Behavior

The undo action does not work:

![no-undo](https://user-images.githubusercontent.com/28742426/128402820-084cee9a-7805-4e61-8cde-585da21ecc4d.gif)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

**Comment by talldan** [comment]
I think this was fixed by https://github.com/WordPress/gutenberg/pull/34565. Thanks for flagging. I'll close it, but feel free to reopen if you can still reproduce.

**Comment by Addison-Stavlo** [comment]
I gave it a quick test and it seems to be fixed.  Thanks @talldan !
