### ISSUE TITLE
Unused `receiveUploadPermissions` action

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#33900]
I just realized that this code is not used anywhere and could be removed safely:

https://github.com/WordPress/gutenberg/blob/5e8e8b4ab102e54d9cf5b981d0aa38bb003aaba4/packages/core-data/src/actions.js#L727-L740

Everything goes through `receiveUserPermission` these days.

**Comment by gziolo** [comment]
Good catch. It would have to get deprecated and point to `receiveUserPermission `.

**Comment by khushishikhu** [comment]
hi @gziolo could you please assign me to this issue?

**Comment by skorasaurus** [comment]
> hi @gziolo could you please assign me to this issue?

done. :)

**Comment by jiteshdhamaniya** [comment]
@swissspidy @skorasaurus Created PR https://github.com/WordPress/gutenberg/pull/37508

**Comment by mauriac** [comment]
Going to close this, since the PR is merged.
