### ISSUE TITLE
Blocks: Error when transforming quote with content to list

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#3391]
## Issue Overview

Converting a quote block to a list block results in an error if the quote has text.

## Steps to Reproduce (for bugs)

1. Navigate to Posts > Add New
2. Insert a quote block
3. Add some text to the quote block
4. From the block toolbar, choose the transform option to convert to a List block

## Expected Behavior

Block is transformed to a list block with quote content.

## Current Behavior

Block suffers from an unhandled error:

```react-dom.f04e56af.js:65 Uncaught Error: Objects are not valid as a React child (found: object with keys {children}). If you meant to render a collection of children, use an array instead.```

## Possible Solution

Is it sensible to convert from a quote to a list? Does this transform need to exist?

**Comment by jorgefilipecosta** [comment]
Hi @aduth, I'm not being able to replicate this on master in chrome. Does this happen even with just quote in the post and any type of content, or it happens in more specific cases?

**Comment by aduth** [comment]
Strange, I am unable to reproduce now. Might have been a specific set of steps I had taken aside from just the ones included in the report. Worth keeping an eye on, but will close for now.
