### ISSUE TITLE
Navigation block - undo trap when initializing 'add all pages' with existing `textColor` attribute.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#33911]
### Description

When a navigation block has an existing `textColor` attribute, the process to initialize via the "Add all pages" option creates an undo trap, preventing the user from being able to undo the action or any previous actions.

 related - #8119

### Step-by-step reproduction instructions

1. Map tt1-blocks locally and update `block-template-parts/header.html` so that the navigation block has a "textColor" attribute.  Alternatively you can activate a theme that already does this such as Mayland-blocks from https://github.com/automattic/themes.  For this example, I am updating the navigation block in header.html of tt1-blocks by adding a textColor attribute like so: `<!-- wp:navigation {"orientation":"horizontal","textColor":"Purple","itemsJustification":"right"} /-->`
2. Load the site editor. You should see your header with an uninitialized navigation block.
3. Click the navigation block, and select the "Add all pages" option.
4. Try to "undo" and verify it is not possible to undo the initialization or any actions prior to it.

5. Undo your change to the header by removing the textColor attribute (if you instead activated Mayland-blocks as the original step, now activate tt1-blocks).
6. Repeat steps 2-4, and verify this time 'undo' works as expected.

### Expected Behavior

Undo to work as expected:

![undo works](https://user-images.githubusercontent.com/28742426/128406422-84b22eeb-9cd9-4657-b057-8e3ae17b7f6e.gif)

### Current Behavior

Undo is trapped in a loop:

![undo trapped](https://user-images.githubusercontent.com/28742426/128406283-a4f47146-2136-4f30-aade-df9f1cbdeaf6.gif)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

**Comment by Mamaduka** [comment]
Now that we have a default fallback for Navigation block (#42735), I can no longer reproduce this issue.

cc @draganescu

**Comment by draganescu** [comment]
What does "Map tt1-blocks locally" mean?

**Comment by Mamaduka** [comment]
@draganescu, I just translated it to "Install TT1 Blocks locally".

**Comment by draganescu** [comment]
I can confirm that following https://github.com/WordPress/gutenberg/pull/42735 this can't happen anymore.
