### ISSUE TITLE
Two 404s are displayed in the TemplatePanel.

### ISSUE THREAD

**Issue by torounit** [WordPress/gutenberg#33929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

When using the TT1 Blocks theme, two 404s are displayed in the select box of the TemplatePanel.

If you select the first 404, the default template will be applied. If you select the second 404, the correct template will be applied.

The result of getEditorSettings().availableTemplates is as follows.

```
{ 
  "": "Default template"
  0: "404"
  index: "Index"
  page: "Page"
  page-home: "page-home"
}
```

The fetchedTemplates look like the following

```
{
   404: "404"
   index: "Index"
   page: "Page"
   page-home: "page-home"
}
```

Merging these Objects will result in two 404s.

`0: "404"` is probably caused by array_marge.

### Step-by-step reproduction instructions

1.  Activate  TT1 Blocks theme.
2. Go to edit post.
3. Check template panel.

### Expected Behavior

Only one 404 will be displayed and the correct template will be set.

### Current Behavior

When the first 404 selected, the default template will be applied. 
When the second 404 selected, the correct template will be applied.

### Screenshots or screen recording (optional)

![スクリーンショット 2021-08-06 22 41 27](https://user-images.githubusercontent.com/1908815/128520163-61701c58-26d4-4059-b4d2-8075846466b6.png)

### WordPress Information

5.8

### Gutenberg Information

11

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by Mamaduka** [comment]
Thanks for the detailed report, @torounit.

I created a Trac ticket and attached the PR - https://core.trac.wordpress.org/ticket/53898.

**Comment by SergeyBiryukov** [comment]
Thanks for the report! Closing as fixed in https://core.trac.wordpress.org/changeset/51595.
