### ISSUE TITLE
Site Editor (Beta) crashes on load with React dom error

### ISSUE THREAD

**Issue by caseymilne** [WordPress/gutenberg#33922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

While trying to test FSE (Full Site Editing) with a range of FSE enabled themes and the latest Gutenberg plugin with WP core 5.8 I found the Site Editor crashes with a React DOM error that reads:

e.current is undefined

The result is the editor tries to load, a Gutenberg UX appears briefly and then the user is kicked back to the WP Admin page they were on after the Site Editor crashes. 

### Step-by-step reproduction instructions

Install latest Gutenberg plugin on WP 5.8, install an FSE theme such as the recommended testing theme TT1 Blocks. Click on "Site Editor" from the WP Admin or from the context bar on the front end. Watch as Site Editor tries to load and then crashes and returns you to the WP Admin from where you came. Check console for TypeError: e.current is undefined.

### Expected Behavior

Site Editor should load when FSE theme is active and Gutenberg plugin enabled. 

### Current Behavior

Site Editor tries to load, crashes immediately with a React DOM error.

### Operating System Information

Windows 10

**Comment by Mamaduka** [comment]
@eatbuildplay

Can you confirm that this issue happens in the Firefox browser?

There's a similar report #33873 and should be fixed via #33896.

**Comment by caseymilne** [comment]
Yes it was Firefox browser!

**Comment by caseymilne** [comment]
Confirmed Site Editor loading fine in Chrome, closing as duplicates #33873.

**Comment by caseymilne** [comment]
Thanks @Mamaduka Mamaduka
