### ISSUE TITLE
Replace usage of native `alert/confirm/prompt` with web content versions

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#33937]
## What problem does this address?

Major browsers - [starting with Chrome](https://www.chromestatus.com/feature/5148698084376576) - will soon restrict the `alert/confirm/prompt` functions from being used from within cross-origin iframes. They started [deprecating](https://developer.chrome.com/origintrials/#/view_trial/2541156089743802369) the usage of these functions in the cross-origin iframe contexts, but the intent, it seems, **is to completely remove them eventually.** 

The trial to prevent cross-origin iframes to trigger these functions was supposed to be active, meaning it shouldn't work anymore in Chrome 92 up to 96. It [might have been delayed](https://bugs.chromium.org/p/chromium/issues/detail?id=1065085#c72) for now (though I haven't tested it at the time I write this), but they're sticking to it.

This might not seem relevant to Gutenberg, but some applications do use the editor from an iframe. [Here's a real-world example of such an issue](https://github.com/Automattic/wp-calypso/issues/54781).

However - and this _is_ directly relevant to Gutenberg when used outside of an iframe context - It's possible that after disabling the cross-origin iframe use cases, these functions will be removed completely. It might take a good while, but the odds are it'll eventually happen.

## What is your proposed solution?

Replace these functions with our own versions that implement similar functionality using web contents (DOM and CSS through React components).

## Further reading:
* https://twitter.com/estark37/status/1422694845076762629
* https://twitter.com/domenic/status/1422647331804037120
* https://www.chromestatus.com/feature/5148698084376576
* https://developer.chrome.com/origintrials/#/view_trial/2541156089743802369
* https://bugs.chromium.org/p/chromium/issues/detail?id=1065085#c72

**Comment by Mamaduka** [comment]
Related #16583.
