### ISSUE TITLE
CSS Class Names: Add button to choose from block styles

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#33934]
When switching between block styles, the "Additional CSS class(es)" input within the Advanced accordion of the sidebar also updates to reflect the new style.

![Current Styles and CSS](https://user-images.githubusercontent.com/191598/128540175-c8cd358f-aba0-4fdc-86a5-3d2ec559ae6b.gif)

It might be nice to connect these two UI's a little, and offer a way to choose from the defined block styles from the Advanced section.

![CSS Class name menu](https://user-images.githubusercontent.com/191598/128540358-bd97f649-d67d-4877-ba01-753b11cd46f6.gif)

**Comment by kjellr** [comment]
I'm not totally sure this extra feature is necessary, but if we were to add it, I think the mockups would benefit from some sort of header/title/prepended label inside of the dropdown to be clear that the options there are Styles.

**Comment by mtias** [comment]
This would play well with the ability to register your own user styles once we get there.

**Comment by ramonjd** [comment]
I've made a first, and very rough, pass at this. The list won't show for blocks with no styles.

![Sep-03-2021 15-20-32](https://user-images.githubusercontent.com/6458278/131954521-3cd7ff2a-6640-4f33-8b60-bad8cfd9955d.gif)

I'm not also convinced it's necessary, but one argument for the feature would be that the editing styles class value is already connected to the styles controls.

![Sep-03-2021 15-25-56](https://user-images.githubusercontent.com/6458278/131954887-edabb4e5-b3c2-4817-b583-fe23bac8d5e0.gif)

So if you happen to clear the CSS style names manually, and your mouse is loitering about that place anyhow, then it's easier to restore and preview the alternative style options.

**Comment by kjellr** [comment]
> I'm not also convinced it's necessary, but one argument for the feature would be that the editing styles class value is already connected to the styles controls.

Yeah, that's a good point. Seems like a good reason to give this a try at least.

**Comment by ramonjd** [comment]
Closing for now until we can revisit the approach.

I've closed the attached [PR](https://github.com/WordPress/gutenberg/pull/34521), which explored a few avenues but ultimately couldn't achieve the desired design 1:1.

We can always reopen if folks think this feature is required and we can use what we've learned. 

Thanks to everyone for their help on this one!
