### ISSUE TITLE
Block pattern do not show in the inserter

### ISSUE THREAD

**Issue by moerphie** [WordPress/gutenberg#33946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

Hello,
since the update to version 5.8, this simple pattern is no longer displayed in the inserter.
```php
register_block_pattern(
	"mywpsite/test",
	[
		"title"         => esc_html__("Test"),
		"categories"    => ["mywpsite-default"],
		"content"       => trim(str_replace(["\n", "\r", "\t"], "", '
		<!-- wp:columns --><div class="wp-block-columns">
		<!-- wp:column --><div class="wp-block-column">

		<!-- wp:heading -->
		<h2>Hello world</h2>
		<!-- /wp:heading -->

		</div><!-- /wp:column -->
		</div><!-- /wp:columns -->
		')),
	]
);
```

Whenever I remove the column, the pattern is shown up.

### Step-by-step reproduction instructions

1. Add the code above to functions.php
2. Open WordPress and edit a post
3. The pattern is not displayed in the inserter on the left side

### Expected Behavior

Show up in the inserter

### Current Behavior

Will not be shown

**Comment by ntsekouras** [comment]
Hey 👋 - thanks for reporting this! I couldn't reproduce this though... Have you registered your category with `register_block_pattern_category`? If not, the pattern is shown under `Uncategorized` in the inserter.

**Comment by moerphie** [comment]
Yes. 
Sorry, here's the complete code:
```php
<?php
remove_theme_support("core-block-patterns");

add_action("init", function () {
	if (function_exists("register_block_pattern_category")) {
		register_block_pattern_category(
			"mywpsite-default",
			["label" => esc_html__("Presets")]
		);
	}

	if (function_exists("register_block_pattern")) {
		register_block_pattern(
			"mywpsite/test",
			[
				"title"         => esc_html__("Test"),
				"description"   => "",
				"keywords"      => [],
				"categories"    => ["mywpsite-default"],
				"content"       => trim(str_replace(["\n", "\r", "\t"], "", '
				<!-- wp:columns --><div class="wp-block-columns">
				<!-- wp:column --><div class="wp-block-column">

				<!-- wp:heading -->
				<h2>Lorem ipsum dolor sit amet vis</h2>
				<!-- /wp:heading -->

				<!-- wp:paragraph -->
				<p>Lorem ipsum dolor sit amet, nam nonumy dicunt voluptua ne. Idque nullam expetenda ex pro. Mandamus deseruisse reformidans mei ei. Saepe mucius admodum mel in, cu mei qualisque neglegentur. In tantas forensibus his, ullum atomorum te est, ad quod ponderum est. Te ius offendit comprehensam, at usu sumo reque nusquam.</p>
				<!-- /wp:paragraph -->

				</div><!-- /wp:column -->
				</div><!-- /wp:columns -->
				')),
			]
		);
	}
});
```


If I replace the content with this, it is shown:
```php
…
				"content"       => trim(str_replace(["\n", "\r", "\t"], "", '
				<!-- wp:heading -->
				<h2>Lorem ipsum dolor sit amet vis</h2>
				<!-- /wp:heading -->

				<!-- wp:paragraph -->
				<p>Lorem ipsum dolor sit amet, nam nonumy dicunt voluptua ne. Idque nullam expetenda ex pro. Mandamus deseruisse reformidans mei ei. Saepe mucius admodum mel in, cu mei qualisque neglegentur. In tantas forensibus his, ullum atomorum te est, ad quod ponderum est. Te ius offendit comprehensam, at usu sumo reque nusquam.</p>
				<!-- /wp:paragraph -->
				')),
…
```

So, it seems to be an issue with the column-block.

**Comment by ntsekouras** [comment]
Your full code doesn't change much to the previous snippet, and for me it still works... 🤔  I guess other folks could test this as well..

**Comment by Sandstromer** [comment]
I tested it with the full code @moerphie posted above, and yes it works okay for me too.

![moerphie-pattern](https://user-images.githubusercontent.com/76742815/128868739-a0df65c5-8059-435b-9077-a245b4ba1348.jpg)

![moerphie-pattern-inserted](https://user-images.githubusercontent.com/76742815/128868794-325d37b3-022f-404c-b6de-5bdf0e6fbb8a.jpg)

![moerphie-pattern-code](https://user-images.githubusercontent.com/76742815/128868821-39eca832-c220-4fd1-9399-e7aaf92c853a.jpg)

Sorry I can't see any issues with the code that would stop it from displaying!

**Comment by ntsekouras** [comment]
Another potential issue for your case @moerphie would be that in your `Preferences` you have `Columns` block disabled, or in general this block unregistered/disabled. Patterns are filtered for containing `allowedBlocks`, so if you have `Columns` disabled, it would not be shown.

Would that be the case for you?

**Comment by moerphie** [comment]
> Another potential issue for your case @moerphie would be that in your `Preferences` you have `Columns` block disabled, or in general this block unregistered/disabled. Patterns are filtered for containing `allowedBlocks`, so if you have `Columns` disabled, it would not be shown.
> 
> Would that be the case for you?

Good advice! In fact, this was the issue. 

`core/columns` was an allowed block type, but `core/column` was not included. 
In version 5.7 this was not a problem, but with 5.8 it now triggered the error. 

Thank you!
