### ISSUE TITLE
Core block testing documentation leads to 404

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#33947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [ ] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [ ] I have tested with a default theme.

### Description

On this page,
https://developer.wordpress.org/block-editor/contributors/code/testing-overview/#core-block-testing
there is a link leading to https://github.com/wordpress/gutenberg/blob/HEAD/packages/e2e-tests/fixtures/blocks/README.md which is a 404.

### Step-by-step reproduction instructions

Click the link above.

### Expected Behavior

I expected the link to not be a 404

### Current Behavior

The link is a 404

**Comment by Mamaduka** [comment]
It looks like this got fixed by 64fadb5, no need for my PR 😄
