### ISSUE TITLE
404 page perhaps not best default for site editing

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#33940]
It seems since the last few updates the 404 page for me has ended up being the default page that the site editor opens on. This seems a little strange as far as the experience goes. I assume it might be an ordering issue, although assuming isn't a good idea. I think perhaps using the template hierarchy might be better ordering in this case for opening. When it opened to the front page I had less disconnect, or index.

**Comment by skorasaurus** [comment]
I'm not able to reproduce this; the index template has been the default template when I tried to reproduce this (using the wei theme). please reopen if you're still experiencing this.
