### ISSUE TITLE
Some writing flow / keyboard shortcuts doesn't work in the site editor

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#33948]
In the site editor, I'm not able to use several writing flow interactions from the post editor.

 - The first one is "select all" shortcut, hitting "ctrl + a" twice doesn't select all the blocks
 - The other one I noticed is the "delete" or "backspace" to remove selected blocks.

**Comment by juanmaguitar** [comment]
The "Delete" Blocks shortcut (CTRL + OPTION + Z ) is not working for me either in the P2 editor

My keyboard details
- Spanish ISO (QWERTY) layout
- Using a [Magic Keyboard - Spanish](https://www.apple.com/shop/product/MK2A3E/A/magic-keyboard-spanish) but that combination of keys doesn’t work on the keyboard integrated in the laptop either

<img width="649" alt="Screenshot 2021-10-04 at 17 34 40" src="https://user-images.githubusercontent.com/422576/135882492-495a8a2b-6b6b-4610-86d7-338e183b6dc6.png">

**Comment by KokkieH** [comment]
Cmd/Ctrl-U for underlining also isn't working. In Firefox it opens `view source:`, and on Chrome it simply doesn't do anything.

Reported in the [WordPress.com forums](https://wordpress.com/forums/topic/shortcuts-issue/?view=all)

**Comment by youknowriad** [comment]
I'm temptatively adding this to the 5.9 board. I guess it's fine if we can't solve it on time.
