### ISSUE TITLE
Site Editor should be available for child themes if the appropriate index.html file exists in the parent

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#33959]
## What problem does this address?
Currently a theme requires a `block-templates/index.html` file to enable the Site Editor UI (which makes sense). However, if a child theme of the block based theme does not have an index.html file, it is opted-out of the experience. This means that child themes will have to duplicate index.html files just to be opted into the Site Editor (which isn't ideal if a child theme does not change the index blogroll view). 

## What should occur?
A parent theme's `block-templates/index.html` file should be available within child themes, which means child themes of Site Editor capable themes can use the Site Editor without having to duplicate that index file.

**Comment by Mamaduka** [comment]
Related #25612.
