### ISSUE TITLE
The query block should not use `Keywords` as a label, but `Tags`

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#33966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

The Query block Filters settings currently use `Keywords` as a label for the `Tags` filter. In most Locales, there is a difference between "tags" and "keywords". If you speak of the taxonomy (which is the case), "Tags" should be used instead of "Keywords".

PR incoming.

### Step-by-step reproduction instructions

1. Insert a Query block and use a post type that have "Tags" (like default "Posts" post type)
2. Got to Settings > Filters
3. The "Tags" taxonomy is labelled "Keywords" instead of "Tags"

### Expected Behavior

The "Tags" taxonomy must be labelled "Tags" instead of "Keywords".

### Current Behavior

The "Tags" taxonomy is labelled "Keywords" instead of "Tags", which is wrong.

### Screenshots or screen recording (optional)

<img width="269" alt="Screen-Shot-2021-07-07-at-6 30 18-PM" src="https://user-images.githubusercontent.com/1590998/128814851-11017336-db18-461c-97d1-c14c4c6bd855.png">

### WordPress Information

WP 5.8

### Gutenberg Information

Core (not installed)

**Comment by ntsekouras** [comment]
Hey 👋 - thanks for filing the issue!

>The "Tags" taxonomy is labelled "Keywords" instead of "Tags", which is wrong.

This is not the case. You can see it from your screenshot as well, that there is another control for `Tags`. The `Keyword` labeled control is for the `search` param in WP REST API: https://developer.wordpress.org/rest-api/reference/posts/.

**Comment by ntsekouras** [comment]
Closing this as it's been discussed in the linked PR: https://github.com/WordPress/gutenberg/pull/33967#issuecomment-895881370
