### ISSUE TITLE
Classic Block: Block title bar obscures images immediarely below it

### ISSUE THREAD

**Issue by pauljacobson** [WordPress/gutenberg#33968]
## What problem does this address?

When using a Classic Block, and adding an image beside text directly below the Classic Block title bar, the image is partially obscured when the block is in focus. Here is an example:  https://d.pr/i/zJBCRq/CIbekgepSg

## What is your proposed solution?

Enable images to shift below the toolbar with the accompanying text.

**Comment by stacimc** [comment]
I tested and can reproduce. There's a similar issue here when the Image is left-aligned: #25059

When you click into the Classic Block, the block content is pushed down the page to make room for the classic toolbar. Any other content floated left or right isn't pushed, so the toolbar will overlay it. The normal Block toolbar is inserted _above_ the block. So for example if you set up the same basic content but using a Paragraph block, you can see that the block content doesn't move when you click inside:

| Classic Block | Paragraph Block |
| --- | --- |
| ![classic-block](https://user-images.githubusercontent.com/63313398/130877886-86bb2ac3-9118-4bf4-b8e3-dea16c331caf.gif) | ![paragraph-block](https://user-images.githubusercontent.com/63313398/130877881-d76dbe52-452b-4472-80cf-06f87dffc251.gif) |

**Comment by Thelmachido** [comment]
The content is still pushed down but on the latest release the toolbar doesn't cover the image as shown below:

<img width="716" alt="Untitled" src="https://user-images.githubusercontent.com/41231764/183715808-56599811-5ea4-4e19-89e6-ee512f176637.png">

WordPress 6.0.1
Gutenberg 13.8.1 active or inactive
No other plugins active

Closing this issue
