### ISSUE TITLE
Adjust error message on blocks to be less scary and more informative

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3397]
Currently if you have an issue with blocks you get:

![2017-11-08 at 21 31](https://user-images.githubusercontent.com/253067/32575625-735c7d06-c4cc-11e7-960d-975e114b995a.png)

This is a little alarmist as a message. What about:

"Unfortunately, an error happened and the block can't be previewed."

That's not perfect but stating a block suffers and using such strong language probably isn't the best.

**Comment by aduth** [comment]
Related: #3208

You might not like my "catastrophic error" phrasing there 😆

**Comment by StaggerLeee** [comment]
Yes. Bring down white man privileges. No more discriminating Gutenberg error messages.

**Comment by hedgefield** [comment]
I'm all for it. Would this issue also apply to blocks that are locked by external content changes? Not that they should have the same error message, but the error that's shown there isn't super parsable by humans either :) mostly the buttons, their verbs are a bit vague.
