### ISSUE TITLE
Responsive menu label

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#33985]
It would be helpful if the responsive menu had the option to display a label on its open and close buttons, for example:

<img width="642" alt="Screen Shot 2021-08-03 at 12 31 54 PM" src="https://user-images.githubusercontent.com/5375500/128053401-6b147bfa-21d1-4d8c-bb18-8eb44cadf5bf.png">

I think this is a fairly common pattern, and maybe increases the accessibility of the responsive menu. 

Sorry if this is already in an issue somewhere! I couldn't find a specific discussion after searching for a bit.

## What is your proposed solution?

It's simple to achieve this by styling a pseudo-element on the existing button provided by the navigation block, but this does not allow us to translate the label without doing something messy. I think having an option in the navigation block's responsive settings to set and display the label would be great.

**Comment by mtias** [comment]
I think we discussed allowing a button (with customizable text) or the icon, but not a mix. cc @jasmussen
