### ISSUE TITLE
Look at automatically retrying E2E tests

### ISSUE THREAD

**Issue by vcanales** [WordPress/gutenberg#33980]
In the context of improving e2e test performance and stability, we can look into ways for retrying failing tests automatically. GitHub Action doesn't currently support this natively, and it doesn't seem to be coming yet, [regardless of community requests.](https://github.community/t/ability-to-rerun-just-a-single-job-in-a-workflow/17234/164)

One approach that I'm experimenting with is [caching previous results in order to use them in subsequent runs](https://github.com/WordPress/gutenberg/pull/33979/files) if necessary, using `actions/cache`.

**Comment by gziolo** [comment]
Related PRs: #33979, #31682.

**Comment by ellatrix** [comment]
This was done in #34432.
