### ISSUE TITLE
Template Mode: Preload `templates` OPTIONS

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#33994]
Recently capability checks were added to some Templates actions, like creating a new template. See #33392.

It might be a good idea to preload `OPTIONS` for the `/wp/v2/templates` REST API path. Like we do for `media` and `blocks`.

Should I create PR for WP core, or might it be better to add this to the plugin first?

/cc @gziolo @youknowriad

**Comment by gziolo** [comment]
> Should I create PR for WP core, or might it be better to add this to the plugin first?

You can use the `block_editor_rest_api_preload_paths` filter in the plugin:

https://github.com/WordPress/wordpress-develop/blob/9b565f7907ca1d4cb32eccc980de98683758df17/src/wp-includes/block-editor.php#L412

I would say it's simple enough to apply in both places.

**Comment by Mamaduka** [comment]
Thanks for the feedback, @gziolo.

I assume `lib/compat/wordpress-5-8` will be the right directory for this code, right?

**Comment by gziolo** [comment]
> I assume `lib/compat/wordpress-5-8` will be the right directory for this code, right?

Yes, it only should be `lib/compat/wordpress-5-9` as we are bridging functionality that is going to be included by default in WP 5.9.
