### ISSUE TITLE
How to provide default styles for the `block-editor` as a standalone package

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#34005]
The `block-editor` was never concerned with providing the CSS for default colors, the CSS was there by other means. Historically, that CSS was provided by the `block-library`. Now, it's provided by server code of global styles.

In landing https://github.com/WordPress/gutenberg/pull/33924 we realized that there's a subtle coupling between `block-library` and `block-editor`: the `block-library` is providing some CSS classes that the `block-editor` expects.

## How to test

Make the playground work default styles https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default

**Comment by jordesign** [comment]
Hey @oandregal  - just checking back to this older issue to see if it is still an issue for you?

**Comment by jordesign** [comment]
With no further movement on this in 2 years - I'm going to close it. We can always re-open and reconsider if there are more reports.

**Comment by spencerfinnell** [comment]
Additional discussion about Gutenberg as a standalone package #53874
