### ISSUE TITLE
Navigation Block sub-menu "more" indicator icon is off center in editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#34016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

When you add a sub-menu item of a sub-menu item (two layers), the icon shows as being off center. 

### Step-by-step reproduction instructions

1. Add a nav block and add a few items.
2. Add a sub-menu item to one item. 
3. Add a sub-menu item to that sub-menu item you just created (two layers).
4. See the > icon is off center but appears correctly on the front end of the site. 

### Expected Behavior

Expect the > icon to look the same in the editor as on the front end (to be centered). 

### Current Behavior

The icon is off center indicating there's additional sub-menu items. 

### Screenshots or screen recording (optional)

Front end view: 
<img width="447" alt="Screen Shot 2021-08-11 at 11 23 17 AM" src="https://user-images.githubusercontent.com/26996883/129057847-93426a8e-f1a6-4c47-aacc-ed1a8537fd29.png">

Editor view:
<img width="612" alt="Screen Shot 2021-08-11 at 11 23 27 AM" src="https://user-images.githubusercontent.com/26996883/129057850-6735bba1-c540-468a-9481-cbbb0eb33608.png">

### WordPress Information

WordPress 5.8

### Gutenberg Information

GB 11.2.1

### What browsers are you seeing the problem on?

Chrome

### Device Information

Desktop. 

### Operating System Information

MacOS

**Comment by jasmussen** [comment]
I'm having a hard time reproducing this one, can you provide some additional steps to reproduce, including which theme you are testing with? Perhaps even some example content.

**Comment by annezazu** [comment]
You're in luck :D I found this while doing the latest call for testing: https://make.wordpress.org/test/2021/08/11/fse-program-testing-call-9-handling-highered-headers/ There's demo content listed [here that you can import](https://cloudup.com/cei9RrWS12R) (just select Download in the top right). I was using TT1 blocks, GB 11.2.1, WordPress 5.8. 

The replication steps are pretty simple but to get more granular this navigation block was in a columns block that was set to 30/70. I put the block inside the 70% column and was writing out/following the steps for "Create a more complex menu for specifics" in the call for testing.

**Comment by jasmussen** [comment]
Thank you for your patience. The difference was subtle, and the issue was only in the site editor: #34168.
