### ISSUE TITLE
Improve how different types of nav items are rendered on the Navigation screen

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#34035]
The current design of the menu items is quite messy right now. For simple menus, it's probably fine… but when there are different items and empty states, the interface becomes cluttered. 

Here's an extreme example:

![image](https://user-images.githubusercontent.com/4933/129174171-0da7dd1f-ef5f-4fcb-81c7-91b41dcacb50.png)

Some of the things that would improve how menus look like could be:

- Unifying the look of the placeholders.
- Improving the spacing.
- Improving the design of the page list.

**Comment by javierarce** [comment]
Related issue:

- #34036

**Comment by talldan** [comment]
This should be improved quite a bit now with some recent styling fixes. I think the only things that's the same as the screenshot are the item placeholders.

@javierarce Would you be able to look at the latest version in `trunk` to see if there's anything you think can be improved?

**Comment by karmatosed** [comment]
For context here is what it currently looks like:

![2021-09-17 at 16 45](https://user-images.githubusercontent.com/253067/133816761-c4e20cf1-bef7-4ce9-af5f-47f66e29a254.png)

![2021-09-17 at 16 48](https://user-images.githubusercontent.com/253067/133817159-c6268685-f9be-4aad-9b1a-41e5754d78b8.png)

The edges certainly are easier in these examples.

My only issue is how the drop-down auto-closes that feels a little awkward when I might want to see within, but that probably doesn't need to be in MVP. There is also an issue already around the squiggles: https://github.com/WordPress/gutenberg/issues/34780

**Comment by javierarce** [comment]
I'm closing this issue since the navigation screen is no longer actively developed.

Related: https://github.com/WordPress/gutenberg/issues/43620.
