### ISSUE TITLE
Fix spacing issues in the mobile version of the Navigation editor screen

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#34032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

There are a couple of minor issues in the mobile version of the menu editor with the spacing between elements. Plus, an empty toolbar appears on top of the menu or placeholder.

### Step-by-step reproduction instructions

Visit the editor with a small device or open the mobile view.

### Expected Behavior

The menu should have some spacing on top, and the toolbar shouldn't be visible if it's empty.

### Current Behavior

See description & screenshots.

### Screenshots or screen recording (optional)

![image](https://user-images.githubusercontent.com/4933/129168727-91727235-b069-408c-8beb-6729d22af515.png)

![image](https://user-images.githubusercontent.com/4933/129168760-348e647f-f28d-421c-8d49-7371fd5b1bb2.png)

### WordPress Information

WordPress version: 5.8

### Gutenberg Information

Gutenberg version: 11.2.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Operating System Information

macOs Big Sur (11.5.1)

**Comment by vcanales** [comment]
> and the toolbar shouldn't be visible if it's empty.

Hi @javierarce — do you mean by this that if the Navigation menu hasn't been selected, the empty toolbar container shouldn't be shown? I interpret this part of the issue like this:

| Selected | Unselected |
| -- | -- |
| <img width="378" alt="image" src="https://user-images.githubusercontent.com/1157901/132542632-df82395a-fa81-46af-9158-de13b5d94fae.png"> | <img width="380" alt="Screen Shot 2021-09-08 at 12 57 18" src="https://user-images.githubusercontent.com/1157901/132543884-a90fae15-9772-4708-882e-570895752fa9.png"> |

**Comment by javierarce** [comment]
> Hi @javierarce — do you mean by this that if the Navigation menu hasn't been selected, the empty toolbar container shouldn't be shown? I interpret this part of the issue like this:

@vcanales yes, exactly, that's the issue

**Comment by Mamaduka** [comment]
Hi, @vcanales

I just wanted to check if you have availability to work on this fix? Otherwise, I'm happy to take over.

**Comment by vcanales** [comment]
> I just wanted to check if you have availability to work on this fix? Otherwise, I'm happy to take over.

I'm checking this out now, but I'll let you know if anything changes :)

**Comment by ndiego** [comment]
Since the Navigation Editor experiment is no longer being worked on and was removed, I am going to close this issue.
