### ISSUE TITLE
TinyMCE script loading

### ISSUE THREAD

**Issue by Afraithe** [WordPress/gutenberg#3405]
## Issue Overview
Currently, TinyMCE is loaded through a custom url used mostly for an easy way of getting nightlies at the start of the project. This should move to use NPM to pull down TinyMCE.

There also isn't really any reason why WP couldn't use the same TinyMCE for Gutenberg as for the "old" editor page (if the updates remain in sync). Ending up with the script included twice with different versions would be bad practice.

These are the lines affected in Gutenberg.
https://github.com/WordPress/gutenberg/blob/master/lib/client-assets.php#L244

## Current Behavior
Script is loaded vi a custom url.

## Possible Solution
Should pull down TinyMCE via NPM or similar.

**Comment by ephox-mogran** [comment]
@mtias are you aware of this issue?

**Comment by mtias** [comment]
Marking as part of build tooling.

**Comment by youknowriad** [comment]
Using the same version for TinyMCE for Gutenberg and the classic block would solve several issues. I tried this PR to align the versions #3840 but it doesn't solve the duplication issue.

Can we update the "Core" version in Gutenberg while in the plugin phase? maybe not, at least I'm not sure how to do so.

**Comment by danielbachhuber** [comment]
@mtias @youknowriad What, if anything, still needs to happen for this issue?

**Comment by youknowriad** [comment]
I think this is fixed now.
