### ISSUE TITLE
Group block loses inner container element when theme.json is enabled

### ISSUE THREAD

**Issue by grantgeard** [WordPress/gutenberg#34052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

For themes **_without_** a theme.json file, the group block markup is structured like so:
```html
<div class="wp-block-group">
    <div class="wp-block-group__inner-container">
        <!-- Inner Blocks -->
    </div>
</div>
```

For themes **_with_** a theme.json file, the group block markup is missing the inner container element:
```html
<div class="wp-block-group">
    <!-- Inner Blocks -->
</div>
```

This additional element is useful for a very common design pattern: a full width parent element with a contained and centered child element. With other elements that output an inner container (e.g., the cover block), and by using a similar structure and naming convention for custom blocks, it was easy to target and style these containers in conjunction with the alignment classes like so:

```css
.alignwide > [class*=__inner-container] { ... }
```

The structure of the markup should be consistent, one way or the other, regardless of whether theme.json is enabled.

### Step-by-step reproduction instructions

1. Start with theme that does not have a theme.json file.
2. Add a group block to any entry.
3. Add a theme.json file to the theme.

### Expected Behavior

The structure of the group block is consistent regardless of whether theme.json is enabled.

### Current Behavior

The structure of the block group changes when theme.json is enabled.

### WordPress Information

Tested on WordPress v5.8.

### Gutenberg Information

Issue occurs regardless of whether Gutenberg (v11.2.1) is installed.

**Comment by chthonic-ds** [comment]
This is the intended behaviour, the inner div was deprecated a few months ago for themes with a theme.json. 

See:
- https://github.com/WordPress/gutenberg/issues/30443
- `wp_restore_group_inner_container()` in https://github.com/WordPress/WordPress/blob/a2a8b77806aa9f60c4271cb8d277761c13461faa/wp-includes/block-supports/layout.php#L120

**Comment by grantgeard** [comment]
@chthonic-ds thanks for the information! It still seems to me like unexpected behavior for the structural markup of the block to be changing since that is not something that theme.json seems like it can otherwise effect.

If I'm approaching this layout the wrong way, what would be the intended or generally accepted way to achieve the design pattern I mentioned? If I have a full-width block in the middle of an entry, how do I nest child blocks within it that may just be the standard container width, or wide-aligned?

This seems like a very common use case, but I'm struggling to see any straightforward way to do this within the block editor given how it handles alignment (and also that alignment with theme.json enabled is now limited to root blocks). Should I just be using group blocks more frequently as generic content containers with child group blocks only being the standard width? This potentially works, but it's essentially the same approach as with the inner container, just with extra steps. It also doesn't feel very user friendly to me since content editors would need to do a lot of block nesting and it might not seem obvious where and when it needs to be done.

**Comment by chthonic-ds** [comment]
> what would be the intended or generally accepted way to achieve the design pattern I mentioned? If I have a full-width block in the middle of an entry, how do I nest child blocks within it that may just be the standard container width, or wide-aligned?

The intended way to achieve that pattern is by enabling the "Inherit default layout" toggle for the Group block:

![group-block-layout-inherit-default](https://user-images.githubusercontent.com/29587253/129314837-13b21985-42d7-46c6-994e-c842226ef3a4.jpg)

This depends on values being set for `contentSize` and `wideSize` in your theme.json. For example, in TT1 Blocks theme you'll see this: 
```
"settings: {
  "layout": {
    "contentSize": "610px",
    "wideSize": "1240px"
  }
}
```
Here's a quick mock-up in TT1 Blocks that shows the result of enabling "Inherit default layout" for default, wide, and full alignment:

![group-block-layout-support-examples](https://user-images.githubusercontent.com/29587253/129314677-c5a021a9-c839-47e9-bd9a-c996ed64b7d6.jpg)

**Comment by grantgeard** [comment]
> The intended way to achieve that pattern is by enabling the "Inherit default layout" toggle for the Group block:

I've reviewed the inherit default layout option and the TT1 theme and this looks to be more or less what I was looking for.

This method looks like it allows you to set the alignments of the children individually, which is nice, but it also seems to assume that you want the individual children to be the actual width defined in the layout as opposed to just falling within that width as it would work if there was an inner container wrapping the children. Any change to the width of an individual block (e.g., a max-width for a heading) seems to result in content that is still centered but now misaligned with it's siblings that are still using the defined sizes. Is there a way to avoid this ragged alignment?

**Comment by chthonic-ds** [comment]
I've noticed the line seems a bit blurry as to what is intended to be a Gutenberg default vs. something a theme is expected to manage. In this case I suspect the expectation is for the theme to manage the misalignment you've noted (though I might be missing something obvious here... so far I've opted to use custom CSS for themes instead of the CSS shipped with Gutenberg).

Perhaps it makes sense to close this issue and open a new one about the child alignment/misalignment?

**Comment by grantgeard** [comment]
I think you're probably right... The opinionated defaults can certainly be frustrating to deal with but I'd prefer not to have to manage the base styles myself. I'm not sure how possible it will be to achieve what I'm looking for without having wrapper elements for things like headings and paragraphs though. Hopefully there is some approach that I just haven't figured out yet. Thanks for the help!
