### ISSUE TITLE
Links are being removed from my "New Post" content

### ISSUE THREAD

**Issue by stephanieflores** [WordPress/gutenberg#34082]
### Description

Whenever I click publish on the screen, the links are being removed, and I have been experiencing this issue since last night, and it's the first time I have noticed this.
My only website where this is happening is this one: [beaglemylove.com](https://beaglemylove.com/)

### Step-by-step reproduction instructions

In the description, I've listed my issue.

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by tellthemachines** [comment]
@stephanieflores could you please add step-by-step reproduction instructions? E.g.:

1. Start a new post
2. Add a Paragraph and paste a link into it...

Otherwise it won't be possible to work out what is happening.

**Comment by tellthemachines** [comment]
Closing this issue due to lack of response from OP.
