### ISSUE TITLE
Featured Image Block: Support the duotone feature

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#34088]
Image blocks support the [Duotone feature](https://wordpress.org/news/2021/05/coloring-your-images-with-duotone-filters/) that arrived in WordPress 5.8, but this is not available for the featured image block. 

It would be useful to have this feature available for featured image blocks, so that users can maintain consistent colors throughout their entire site's graphics.

**Comment by richtabor** [comment]
Totally agree.

**Comment by mtias** [comment]
I think @ajlende was already looking at this!
