### ISSUE TITLE
Customize widgets: Make the option for opening the Block Inspector more obvious 

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#34087]
## What problem does this address?
The option for opening the block inspector is currently a little buried in the block options menu:
<img width="533" alt="Screenshot 2021-08-16 at 11 04 27 am" src="https://user-images.githubusercontent.com/677833/129547371-b68db22a-b40f-478c-ab1a-c85201a2f04a.png">

For some blocks, these options contain important functionality (the cover block is a good example) and users may not even realise this option exists.

## What is your proposed solution?
An option on the editor topbar? (this could do with a design review)

**Comment by sophiegyo** [comment]
I had no idea that existed until I happened upon this issue myself. Thanks! (Case in point, huh?).  I'd love it if there were a way to make it more obvious, and perhaps one click less to open it. Perhaps the cogwheel icon (that's used for that panel in the full page editor) placed in the toolbar, between the link icon and the block options menu?

Would adding this one in take up too much screen real estate?
![cogwheel](https://user-images.githubusercontent.com/36608681/130313176-9bf41802-686d-4d42-b81e-a09de076bcb9.png)

**Comment by javierarce** [comment]
I guess this one can be closed now that the top bar is in place, right?

**Comment by talldan** [comment]
I think it's still relevant in that there's no way to open that settings menu from the top bar:
<img width="303" alt="Screenshot 2021-10-08 at 5 44 40 pm" src="https://user-images.githubusercontent.com/677833/136536113-1472bdd7-a949-4997-90a3-4df71173124c.png">

**Comment by javierarce** [comment]
Oh, sorry 🤦 I didn't notice this issue was for the customizer, I thought it was related to the editor screen.

**Comment by noisysocks** [comment]
> An option on the editor topbar? (this could do with a design review)

What do you think @critterverse? Maybe could be similar to the proposal in https://github.com/WordPress/gutenberg/issues/33716.

**Comment by critterverse** [comment]
Love this idea! Good call @noisysocks, this would work really well based on the reordering of the top bar proposed in https://github.com/WordPress/gutenberg/issues/33716:

![Customizer-top-bar](https://user-images.githubusercontent.com/77359364/154345699-72fc28ce-086b-4de1-9703-0fb59e44e571.jpg)

**Comment by noisysocks** [comment]
Noting for future devs that https://github.com/WordPress/gutenberg/issues/34398, https://github.com/WordPress/gutenberg/issues/33716, and https://github.com/WordPress/gutenberg/issues/34087 could be good to tackle together as they all involve reconfiguring the toolbar.
