### ISSUE TITLE
Gallery block refactor: Console errors thrown in some instances when replacing images via Media Library

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#34098]
### Description

Following [Gallery block refactor PR](https://github.com/WordPress/gutenberg/pull/25940) testing instructions in: https://github.com/WordPress/gutenberg/issues/29882, I noticed the following issue:

If certain steps are followed, when replacing existing images in the refactored gallery via Media Library, console errors are thrown (it doesn't appear to affect functionality).

![image](https://user-images.githubusercontent.com/14988353/129652495-0e474030-c6fe-4cd8-a005-5d675c249b0f.png)

### Step-by-step reproduction instructions

1. Check out [Gallery refactor PR](https://github.com/WordPress/gutenberg/pull/25940) to local dev env
2. Insert a gallery block and add one image via the Media library
3. Save the post and reload the editor window
4. Replace the image in the existing gallery by clicking on the Media Library button and upload 2 new images to replace the existing one
4. Once the images are replaced, notice the console errors

### Screenshots, screen recording, code snippet

![gallery-refactor-replace-images](https://user-images.githubusercontent.com/14988353/129652348-8fb5b80c-312d-4c26-8249-25789be5eaae.gif)

### Environment info

- WP 5.8

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by glendaviesnz** [comment]
It turns out that this can be replicated without Jetpack installed as long as certain steps are followed. Have updated the description.

**Comment by andrewserong** [comment]
Great, thanks for confirming and updating the description, Glen!

**Comment by talldan** [comment]
Fixed by #34133
