### ISSUE TITLE
[Columns] Width listed in px rather than percentage

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#34096]
### Description

When adding in columns, the width is listed as px rather than percentages. 

### Step-by-step reproduction instructions

1. Head to Site Editor.
2. Add a Columns block.
3. Select 70/30 option.
4. Use list view to select an individual Column block and check the sidebar settings to view the width. 
5. See the width is set to px rather than percentages. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/129626406-44fde058-9666-4ff3-b0ed-a1adfb0a76b2.mov

### Environment info

- WordPress 5.8, GB 11.2.1, TT1 Blocks
- Chrome
- Desktop

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by walbo** [comment]
Seem there is an issue in themes that customize the spacing units. The TT1 theme does this here: https://github.com/WordPress/theme-experiments/blob/10dc98f4bb3848d3a70078a165668572992e57e1/tt1-blocks/theme.json#L178-L187
```json
"spacing": {
	"customPadding": true,
	"units": [
		"px",
		"em",
		"rem",
		"vh",
		"vw"
	]
},
```
Note that the TT1 theme doesn't have `%` in the allowed unit

When inserting the columns variations the `width` attributes is set in percentages. Thats why they initially are shown correctly but not allowed to edit as percentage.
https://github.com/WordPress/gutenberg/blob/1f186b936fbd8a124678eee3cd0af0ea678675e8/packages/block-library/src/columns/variations.js#L76-L79

Not sure the best approach to solve this issue. Should percentages always be allowed in `column` block regardless of `units` in theme.json?

**Comment by annezazu** [comment]
Oh wow! Thanks for this excellent sleuthing. Going to add in more labels to expand this conversation.

**Comment by ramonjd** [comment]
This is an interesting problem. 

It's especially noticeable when trying to reset a column's width values:

https://user-images.githubusercontent.com/6458278/131266966-10bce672-8e49-48dd-ad7b-7ea0224fbcc6.mp4

If I change the values/units, then remove them I can't return to the original width values and have to create a new column.

I wonder what our options are. I'm just rattling off some un-informed ideas to get things started.

If block variations natively require a specific unit, where should the compromise lie? Should the block itself enforce the use of `%` regardless of theme? Or should the variation follow the units defined in theme.json?

#### Allow block.json to define 'always-on' unit value

If we allow the block to tell theme.json what to do, we could perform a merge of customUnits, for example, using the arguments for [useCustomUnits](https://github.com/WordPress/gutenberg/blob/e9e62d3a10d57b581ca88ca89ee46a88d5d8507d/packages/components/src/unit-control/utils.js#L267) (so the columns block.json can define an immutable `%` unit)?

❗ I'm not sure the benefit would outweigh the obvious con, that is, it would dilute the authority of `theme.json`. 

#### Restore initial variation value

Maybe a lower barrier would be to store the initial value, e.g., `33.33%` regardless of whether the theme supports percentages, and restore it when we reset the control (requires the [ToolsPanel](https://github.com/WordPress/gutenberg/pull/32392). See also related PR: **Block Support: Add width block support feature** https://github.com/WordPress/gutenberg/pull/32502)

#### Transform

Could we create custom transforms or variations depending on the unit value.

Perhaps in the [onSelect](https://github.com/WordPress/gutenberg/blob/1eaad3cbad327e9fad5d8eef93c46aa773b7080b/packages/block-library/src/columns/edit.js#L249) callback of `__experimentalBlockVariationPicker`

This assumes of course that we have access to the custom units, and can check them against the units required by variations.js, AND then come up with a suitable replacement value depending on the unit. For example, `33.33%` to `{n}px`.

This seems like the most work.

I'd be very happy to learn about better ways to approach this!

**Comment by andrewserong** [comment]
> If we allow the block to tell theme.json what to do, we could perform a merge of customUnits, for example, using the arguments for useCustomUnits (so the columns block.json can define an immutable % unit)?

That's a compelling idea @ramonjd — it feels like the Columns block has been built expecting that the percentage unit will be available, so I quite like the idea of a block being able to define an immutable unit. I wonder what the consequences would be for theme authors? In the case of TT1-blocks, where the units value is set globally, having an individual block take care of its own _required_ units means that the theme author doesn't have to worry about potentially breaking block behaviour, so it could be beneficial, even if it's unexpected?

**Comment by richtabor** [comment]
> It's especially noticeable when trying to reset a column's width values:

I've run into this issue as well — resetting to `px` when initially set to `%`.

**Comment by andrewserong** [comment]
I'm just assigning myself to this one, I thought I'd see if I can come up with a fix for the Column block when the width is set to a value that isn't supported by the `spacing.units` value of the current theme's `theme.json` (e.g. percentage widths).

**Comment by andrewserong** [comment]
I have a PR ready for review in https://github.com/WordPress/gutenberg/pull/34768 that attempts to deal with this issue by ensuring that the UnitControl will always display the current value's unit (if it's a valid CSS unit) irrespective of the theme's list of allowed units. If a theme provides a more limited list of available units, then once the unit of the current value is switched away from the not-allowed-unit, then the provided list is respected. I _think_ this should resolve the issue for the Columns block requiring percentage widths for its variations, while also ensuring that we don't run into similar issues with other blocks.

Very happy for feedback, though, if folks think there's a better way to handle it!
