### ISSUE TITLE
Incorrect decoding Site Title in pre-publish checklist UI

### ISSUE THREAD

**Issue by JJJ** [WordPress/gutenberg#34092]
### Description

I have an apostrophe in my blog title: `JJJ's Blog`. That apostrophe is oddly decoded in the prepublish UI.

### Step-by-step reproduction instructions

1. WordPress Admin > Settings > General > Site Title > Put an apostrophe `'` here
2. Enable "Include pre-publish checklist" preference
3. Write a blog post using Gutenberg
4. Click "Publish"
5. Notice that the `'` is decoded to `&#039;`

## Settings
<img width="609" alt="jjj-on-2021-08-16-at-11-55-17@2x" src="https://user-images.githubusercontent.com/88951/129600764-904dbdd9-f6d2-42c0-8c24-f09eeea8c351.png">

## Are you ready to publish?
<img width="277" alt="jjj-on-2021-08-16-at-11-44-41@2x" src="https://user-images.githubusercontent.com/88951/129600642-d0cf8efa-58e1-4187-b1e9-3bb7cd115b26.png">

### Environment info

WordPress 5.8
Bundled Gutenberg version
Twenty Twenty-One theme
Any operating system

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by JJJ** [comment]
Line of code: https://github.com/WordPress/gutenberg/blob/54e8671ca26a2577645ae426e8f3245e1027b8f9/packages/editor/src/components/post-publish-panel/prepublish.js#L109

**Comment by JJJ** [comment]
Related: #33321, #33323.

**Comment by annezazu** [comment]
Thanks for reporting, finding the line of code, and sharing related issues <3 @walbo  it looks like you worked on this recently -- perhaps you can check this out too? :)

**Comment by walbo** [comment]
Did a quick test and I belive #33323 fixed this issue in Gutenberg. I do see the entities when running WP 5.8 without Gutenberg (looks like that is enviroment you are running).

I'm not sure how the process is when it comes to backporting PR's to minor WP releases but maybe #33323 should be included in WP 5.8.1?

**Comment by Mamaduka** [comment]
The issue should be resolved now. Props to @walbo.

![CleanShot 2022-05-10 at 09 02 14](https://user-images.githubusercontent.com/240569/167546060-ed5695e2-3a22-49d9-b867-8b61273c815e.png)
