### ISSUE TITLE
IE 11: typing / doesn't make the block autocomplete suggestions appear

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3409]
In IE 11, typing `/` to make the blocks autocomplete suggestions appear, doesn't do anything. In the screenshot below: IE 11 and Chrome on Windows:

![screenshot 108](https://user-images.githubusercontent.com/1682452/32612826-87720f52-c569-11e7-91e8-1c7a35f3329c.png)

**Comment by ephox-mogran** [comment]
The `Autocomplete` component binds `onInput` for listening to what the user is typing. This does not work on content editable in IE11. I can demonstrate this with a fiddle:

https://jsfiddle.net/arnt3csq/

This is a problem that quite a lot of people hit. Microsoft don't consider it a priority to fix in IE11

https://connect.microsoft.com/IE/feedback/details/794285/ie10-11-input-event-does-not-fire-on-div-with-contenteditable-set

There are no particularly good work arounds

https://stackoverflow.com/questions/1391278/contenteditable-change-events

Mainly what people do is listen to key events, and go from there. The `onInput` handler is just not going to work in IE.

**Comment by ephox-mogran** [comment]
Another issue: in `blocks/autocompleters/index.js`, we are using `parentElement` on a text node in `allowNode`. This returns null on IE, so `closest` can't be called on `null`.

https://developer.mozilla.org/en-US/docs/Web/API/Node/parentElement

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521735593000687)._
