### ISSUE TITLE
List Block: allow use of backspace key to convert a list item to a paragraph

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#34100]
## What problem does this address?
It's a standard behavior in Word Processors that using the backspace key at the start of a list item removes the bullet point, effectively turning the list item into normal text. The List Block doesn't seem to do this, which I think is unexpected.

The main use-case would be at the end of a list, a user wants to stop creating list items and go back to creating paragraphs. They press enter to create a new line and then backspace to make it a paragraph. Currently this is possible using the down-arrow key, but this isn't obvious because the editor looks like this:
<img width="594" alt="Screenshot 2021-08-17 at 11 20 47 am" src="https://user-images.githubusercontent.com/677833/129658582-02460656-9beb-4e28-b66d-4efde500e414.png">

It isn't clear that there's anything to arrow down to from the last list item. Most Word Processors don't do anything when the down arrow is used on the last line.

## What is your proposed solution?
Deleting at the start of a list item makes that item a paragraph.

I think the only downside of this would be that deleting a list item that has text in the middle of a list could result in three separate blocks being created (list, paragraph, list), but it could still be worth exploring this for the first or last list item only.

**Comment by ehti** [comment]
It would be great to have this solution incorporated.

When the list doesn't go away, no matter if you're pressing delete/backspace or 'unselect' it from the tool bar, it can become a bit frustrating. 🙂
