### ISSUE TITLE
[Discussion] i18n: the domain configuration will be overwritten by setLocaleData under @wordpress/i18n

### ISSUE THREAD

**Issue by arthur791004** [WordPress/gutenberg#34101]
### Description

Currently, calling `setLocaleData` with new locale data multiple times, the domain configuration will be overwritten. Maybe the user needs to take care of using `setLocaleData` to make all of the domain configurations the same. So,  I'm not sure it's a bug or not. Just want to discuss whether it makes sense to merge the domain configuration?

**What I expected to happen**

The domain configuration should be merged if we call `setLocaleData` multiple times.

**What actually happened**

The domain configuration only keeps the latest one

See: https://github.com/WordPress/gutenberg/blob/8c623e251af39eb10a753227f40b610afbd5fa0d/packages/i18n/src/create-i18n.js#L175

Suggested Changes
```js
const doSetLocaleData = ( data, domain = 'default' ) => {
	tannin.data[ domain ] = {
		...DEFAULT_LOCALE_DATA,
		...tannin.data[ domain ],
		...data,
		// Populate default domain configuration (supported locale dataa which omits
		// a plural forms expression).
		'': {
			...DEFAULT_LOCALE_DATA[ '' ],
			...( tannin.data[ domain ] || {} )[ '' ],
			...data[ '' ],
		};
	};
};
```

### Step-by-step reproduction instructions

1. Go to http://localhost:8888/wp-admin/post.php?post=1&action=edit
2. Open Developer Tool
3. Do following commands
    ```js
    wp.i18n.setLocaleData({ "": { lang: 'en' } })
    wp.i18n.setLocaleData({ "": {} })
    wp.i18n.getLocaleData()[""]

    // output: { plural_forms: f }
    ```
4. You can see the domain configuration is missing properties set by previous command.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/13596067/129659832-d23cd627-c3a8-4c21-993a-b6a68d0f87b4.png)

### Pre-checks

- [X] I have searched the existing issues.
- [ ] I have tested with all plugins deactivated except Gutenberg.

**Comment by swissspidy** [comment]
As mentioned on #37686 

An alternative approach might be to add a second `addLocaleData` function or so that does this, and leave `setLocaleData` unchanged, to avoid a breaking change like this.

**Comment by arthur791004** [comment]
Close it via https://github.com/WordPress/gutenberg/pull/37704
