### ISSUE TITLE
IE 11: missing "Add title" placeholder in the Add New page

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3410]
Thought there was already an issue about this. If I've missed it, please do feel free to close.

In IE 11, the Add New post page, the "Add Title" placeholder is not visible. Only after clicking into the field and then clicking outside, it becomes visible.

Screenshot: IE 11 on the left / Chrome on Windows on the right:

![screenshot 112](https://user-images.githubusercontent.com/1682452/32613861-3cc9a958-c56c-11e7-92ef-d53772cd6620.png)

**Comment by ephox-mogran** [comment]
This looks related to https://github.com/facebook/react/issues/11172

**Comment by ephox-mogran** [comment]
There was a [PR ](https://github.com/facebook/react/pull/11177/files) which according to the above issue, is going to be part of 16.1.

**Comment by aduth** [comment]
This appears to be resolved.

![image](https://user-images.githubusercontent.com/1779930/33956036-69dbfbda-e00b-11e7-8b38-8fbafcb923a2.png)

I suspect this was fixed in #3908 based on @ephox-mogran's comment.
