### ISSUE TITLE
Error, when slug of font size contains a number

### ISSUE THREAD

**Issue by scrobbleme** [WordPress/gutenberg#34110]
### Description

When I create a font size with a number in the slug, i.e.

```
 [
            'name' => 'Size 1',
            'slug' => 'size1',
            'size' => 10,
 ],
 [
            'name' => 'Size 2',
            'slug' => 'size2size',
            'size' => 20,
 ],
```

it becomes:

```
has-size-1-font-size
has-size-2-size-font-size
```

The expected behavior was

```
has-size1-font-size
has-size2size-font-size
```

If this is intended, it is anything else than obvious behavior.

### Step-by-step reproduction instructions

Create child theme and add something like:

```
add_action('after_setup_theme', function () {
    $font_sizes = [
        [
            'name' => 'Size 1',
            'slug' => 'size1',
            'size' => 50,
        ]
    ];

    add_theme_support('editor-font-sizes', $font_sizes);
}, 100);
```

### Environment info

- Latest WordPress 
- With a child theme of Twentytwentyone with the function above as only thing added

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been already been reported at https://github.com/WordPress/gutenberg/issues/31629. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
