### ISSUE TITLE
Preformatted block: add line-height control option

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#34127]
## What problem does this address?

As @noisysocks noted on [Trac ticket 48402](https://core.trac.wordpress.org/ticket/48402#comment:3):
With default `pre` element styles in the (Twenty Twenty) theme, "the line height in a Preformatted block is so large that it renders the block impractical for things such as ASCII art and diagrams."

Any theme can specify a large line-height, so having an option to reduce that on preformatted blocks would help. Then any adjustments for ASCII art do not affect other `pre` blocks that benefit from a larger line-height, such as Verse and Code.

Screenshot from the Trac ticket:
![preformatted diagram with gaps between characters](https://core.trac.wordpress.org/raw-attachment/ticket/48402/Preformatted.png)

## What is your proposed solution?

The Preformatted block could have the same line-height control currently available for Paragraph blocks (when opted in).

**Comment by noisysocks** [comment]
@nosolosw: Is `line-height` something that can be adjusted in global styles?

**Comment by oandregal** [comment]
Yup, absolutely. Any block can [declare support for it](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#lineheight) and then themes can [target that style](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#styles).

**Comment by noisysocks** [comment]
Awesome. Sounds like we just need to set `supports.lineHeight` to `true` in the Preformatted block, then.

> This value signals that a block supports the line-height CSS style property. When it does, the block editor will show an UI control for the user to set its value if the theme declares support.

**Comment by Mamaduka** [comment]
Fixed via #34064.
