### ISSUE TITLE
Explore "Site Branding" patterns for Site Title, Site Logo, Site Tagline

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#34123]
## What problem does this address?

Both in writing the ninth call for testing for the FSE Outreach Program and [in a recent item of feedback](https://make.wordpress.org/test/2021/08/11/fse-program-testing-call-9-handling-highered-headers/#comment-1883), it became clear that there might be an advantage to having theme blocks, like Site Title + Site Logo + Site Tagline, grouped in a way that makes them easier to quickly configure: 

> I mainly wanted to have the icon but up against the site title.

Right now doing something as simple as having the site logo next to the title is _extremely_ difficult, despite that likely being a common user action. 

## What is your proposed solution?

Inspired by the Media & Text Block, I think it would be neat to have a "Site Branding" block (not sold on the name - just using it to convey the idea) that includes Site Title + Site Logo + Site Tagline together with different block variations that allow for different common layouts.

**Comment by ntsekouras** [comment]
👋 - while this sounds like a common user need, I'm not sure creating a new block would be the best approach here. No strong opinions, but I think a couple of patterns would do the trick here. What do you think?

--cc @kjellr @jasmussen

**Comment by mtias** [comment]
Yes, I think there are many permutations for site title, logo, tagline, and navigation that the only way to handle properly is through patterns and better layout tools.

**Comment by kjellr** [comment]
> Right now doing something as simple as having the site logo next to the title is extremely difficult, despite that likely being a common user action.

Yeah, I think patterns are the simplest answer to this. Also, I expect this to get much easier (for both pattern creators and general users) once the [flexbox](https://github.com/WordPress/gutenberg/pull/33359) features are more mature.

**Comment by annezazu** [comment]
Ah yes! Patterns make perfect sense here. I'll retitle this around patterns for "site branding" instead. Thank you all for the direction.

**Comment by annezazu** [comment]
Feedback came in during the [FSE Outreach Program's all things media exploration](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2325) on this same topic where the inability to get things to line up as one wanted in the header proved to be such a point of frustration with FSE. You can see this discussed in [this user feedback video starting here](https://youtu.be/fQ-LkUeO83k?t=489). This further underscores how having patterns that show off different layouts will be hugely valuable to help folks quickly get what they want.

**Comment by annezazu** [comment]
Going to close this out as we now have header and footer patterns, which include much of this!
