### ISSUE TITLE
Allow for Global Block-level configuration of duotone

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#34122]
## What problem does this address?
If a theme is to be able to [define duotone configuration at the block level ](https://github.com/WordPress/gutenberg/issues/33642) then so too should a user.

## What is your proposed solution?
Allow a user to use the same duotone controls available to individual blocks in the FSE Global Styles panel.  Changing these global values would default all blocks to the values expressed there.

**Comment by MaggieCabrera** [comment]
https://github.com/WordPress/gutenberg/pull/48255 fixes this
