### ISSUE TITLE
Design Reference Guide

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#34136]
This collection of Figma files is a reference guide for the current active design projects and resources with the aim of improving discoverability and clarity. It will be updated on an ongoing basis.

- ### Icons ([Board](https://www.figma.com/file/fnyj380i05vGzuuH60frLQ/G2-Design?node-id=1178%3A0))
- ### Components ([Board](https://www.figma.com/file/fnyj380i05vGzuuH60frLQ/G2-Design?node-id=81%3A30))

----

- ### Global Styles ([Board](https://www.figma.com/file/oEkcAyhIvPFMVEAO8EImvA/Global-Styles))

Design work for iterations on specific blocks:

- ### Table Block ([Board](https://www.figma.com/file/Lac6TBUSZjbv3KyR26xiIi/Table-Block))
- ### Search Block ([Board](https://www.figma.com/file/ULWDWBaxA5S61RnDYAFQ6W/Search-Block))

**Comment by annezazu** [comment]
Closing this out as design process has moved into a different format since this was last used.
