### ISSUE TITLE
Inserting media via Gutenberg creates kebab case in media title vs. Upload New Media preserves whitespace

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#34149]
# Reproduction I: "Upload New Media" creates media title "My Great Photo"
1) Media > Add New
2) Drag-n-drop "My Great Photo.jpg"
3) Inspecting this in "Edit Media" shows a media title "My Great Photo".

# Reproduction II: Insertion via Gutenberg Editor creates media title "My-Super-Photo"
1) Edit an existing page or create a new page.
2) Set the cursor into an empty block.
3) Drag-n-drop "My Super Photo.jpg" into this block. This automatically creates a media page behind the scenes.
4) Save the page.
5) Inspecting the media title via "Edit Media"
- **Actual:** The media title is "My-Super-Photo".
- **Expected:** The media title should be "My Super Photo".
  - The media title should be the filename portion (without the suffix) in its purest possible form (UTF-8) and only the slug and filename should then be transformed according settings regarding ascii/whitespace/transliteration/escaping/punycode/etc.
  - Achieving the same goal via different means (Upload New Media vs. drag-n-drop in editor) should result in the same outcome. Otherwise this is an inconsistency.

(Wordpress v5.8)

**Comment by andrewserong** [comment]
Thanks for reporting @porg, I can reproduce the issue (uploaded files via the Media Library respect the whitespace characters in the filename for the media title, whereas when dragged into the block editor, the title is transformed to kebab-case). I also noticed that the conversion to kebab case in the media title happens when I upload an image via the Image block's placeholder in the editor, so it doesn't appear to be isolated to drag-and-drop.

**Comment by porg** [comment]
Updated issue title according your new findings that it's Gutenberg in general, via both methods (drag-n-drop + upload-button).

**Comment by porg** [comment]
- Can this faulty behavior please be fixed?
  - 4 months and nothing happened…
- Fixing this shouldn't be too hard.
  - Finding out why it is that way as it is, likely is the harder part: Maybe just sloppiness/thoughtlessness, but maybe also some technical constraints led to this.
- Please start the investigation at least. Thanks!

**Comment by porg** [comment]
I'm no developer and I don't know any Wordpress code at all, but my guess as a software tester:

### Usual processing order
1. Copy filename into variable.
2. From that variable strip the file extension but leave the rest intact.
3. Copy this into the media title.
4. Sanitize the remainder of the variable further: Replace spaces with hyphens, transliterate non ASCII, etc.
5. Rename the file to the sanitized name.

**I guess the bug happens** simply because the copying into the media title happens too late (after °4 sanitation).

If this is the case the fix should be fairly easy: Make sure copying to the media title happens before sanitation.

**Comment by adamsilverstein** [comment]
@porg this is actually something that happens on the core side where the logic to set the title is currently different in the REST API vs. the regular media uploader.

I proposed a fix in https://github.com/WordPress/wordpress-develop/pull/3981 that works in my testing, would be good to have some additional feedback, maybe from the REST API team in their weekly meeting. Since this is a core bug, I suggest opening a Trac ticket and closing this issue, then the REST API team can review my proposed fix.

**Comment by porg** [comment]
→  Thx! Closing this here now, as the root cause was identified to be in the REST API by @adamsilverstein 

@adamsilverstein: Please stay subscribed to this issue to get possible followup steps how to delegate this bug.

**Comment by porg** [comment]
1) Who has the authority to merge the fix?
2) With which WordPress version will this (likely) be available?
3) If one installs the Gutenberg plugin to get early access to new features, will this feature be available earlier?

**Comment by adamsilverstein** [comment]
@porg for next steps I think we need to create a Trac ticket for WordPress core that describes the issue, basically a copy of this ticket. Can you take that on or would you like help here?

https://core.trac.wordpress.org/newticket

**Comment by porg** [comment]
1. Perfect timing of you for getting back on this. Have had planned for just today to inquire on the progress.
2. I will file the issue in WordPress Core. Under the the Media component I assume.
3. Your fix failed the automated tests. More formality issues? Or is your fix incomplete?
4. Do you think it will make it into WP 6.2 (end of March 2023). Or too late for this?

**Comment by porg** [comment]
Created core ticket as [Media title falsely has kebab case when inserted via REST API (e.g. in Block Editor)](https://core.trac.wordpress.org/ticket/57957)
- I set **component** to "REST API" and left **Owner** and **Workflow-Keyword** empty.
- Please change the ticket metadata if something else is more adequate. Thanks.

**Comment by adamsilverstein** [comment]
> 1. Perfect timing of you for getting back on this. Have had planned for just today to inquire on the progress.
> 2. I will file the issue in WordPress Core. Under the the Media component I assume.

perfect, thanks

> 3. Your fix failed the automated tests. More formality issues? Or is your fix incomplete?

I'm not sure, I will check again

> 4. Do you think it will make it into WP 6.2 (end of March 2023). Or too late for this?

Unlikely for 6.2 we are very close to release; will aim for 6.3 early.

**Comment by porg** [comment]
Now found a duplicate, which was closed, where the discussion ended abruptly with not comment or resolution:
- #8902
