### ISSUE TITLE
Site Logo Block: Support the duotone feature

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#34146]
Similar to #34088 — another block that may occasionally benefit from duotone would be the site logo block.

Here's an example use case: A theme where the site logo is meant to have the same duotone feature applied as the featured images: 

![screenshot](https://user-images.githubusercontent.com/1202812/129944678-1d499179-5c8f-4dfa-bbc4-1854763af165.png)

**Comment by himanshu007-creator** [comment]
Hi, i would like to try
