### ISSUE TITLE
Global Styles: Block specific global styles don't work for the cover block

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#34150]
### Description

I'm seeing an issue with block-level global styling being overridden in the site editor and frontend, and it looks like it has to do with the [packages/block-library/src/cover/style.scss](https://github.com/Automattic/themes/blob/trunk/blockbase/assets/ponyfill.css) file. When I remove color style declaration, per block global styles work as expected.

https://github.com/WordPress/gutenberg/blob/b8852eece745ab50aefa85fde33b4b95f4085bc2/packages/block-library/src/cover/style.scss#L104-L108

### Step-by-step reproduction instructions

1. Activate a block theme like `blockbase` or `mayland-blocks`
2. Activate the site editor
3. Navigate to the site editor
4. Insert a cover block onto the page and add text content
5. Open the global styles sidebar, and select the "By Block Type" menu tab
6. Unfold the Cover block-level global styles panel and select different color options
7. Confirm that the color options do not change according to user customizations

### Screenshots, screen recording, code snippet

![2021-08-18 17 34 59](https://user-images.githubusercontent.com/5414230/129989467-2bccb2e2-a20d-4b75-976b-e2e2f39c21f8.gif)

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by creativecoder** [comment]
It seems that the Background Color selection in Global styles is something slightly different than the Overlay selection in the Cover block.

| **Cover Block Overlay** | **Block specific Global Styles** |
| - | - |
| <img width="268" alt="Screen Shot 2021-08-20 at 17 58 34" src="https://user-images.githubusercontent.com/1699996/130301318-d21aced7-11ce-4ce3-be00-0d6e19942493.png"> | <img width="267" alt="Screen Shot 2021-08-20 at 17 59 31" src="https://user-images.githubusercontent.com/1699996/130301322-49ad7aea-bec1-490f-b966-4ccdf0117e7f.png"> |

Additionally, I'm not sure how the Background Color Global Styles setting is intended to affect the Cover block. For Cover blocks without images, you must select a color when you create the block, so there's always a block specific setting to override the global style.

For Cover blocks with images, the block specific global style background color could be used to change the default overlay color, which seems useful. But the Global Style control would need an opacity setting added to it, and the css selector needs to be modified--right now it's setting the background color behind the image, which isn't very useful.

**Comment by oandregal** [comment]
Hey, this is what is happening: the cover block does not declare support for colors other than duotone, hence the global styles sidebar should not show any control for colors. This is a bug in the UI logic of the global styles sidebar. I'm working on a fix.

**Comment by oandregal** [comment]
Looked a bit into this. I can't prepare a fix now but this is why it's failing.

The panels in the global styles sidebar are passed the styles that the property supports. These are calculated in the `global-styles-provider.js` (see `getBlocksMetadata`) and the paths are taken from the support keys from the style property stored in the blocks package (see `packages/blocks/src/api/constants.js`:

```js
export const __EXPERIMENTAL_STYLE_PROPERTY = {
	backgroundColor: {
		value: [ 'color', 'background' ],
		support: [ 'color' ],
	},
	color: {
		value: [ 'color', 'text' ],
		support: [ 'color' ],
	},
	linkColor: {
		value: [ 'elements', 'link', 'color', 'text' ],
		support: [ 'color', 'link' ],
	},
};
```

While this mechanism of declaring support works fine for most properties, it doesn't for `backgroundColor` and `color`. The reason is that these two properties work differently from the other ones. The default behavior is that the property is only enabled explicitly: the `linkColor` is only enabled if the block `supports.color.link` is true. However, `backgroundColor` and `color` are opt-out: they're enabled if there's support for any color unless the block opts-out from them explicitly. Which is precisely what the cover block does:

```js
"supports": {
	"color": {
		"__experimentalDuotone": "selector",
		"text": false,
		"background": false
	}
}
```

We need to fix how we calculate support for `backgroundColor` and `color`.

**Comment by jeyip** [comment]
> We need to fix how we calculate support for backgroundColor and color

@nosolosw Do we still want to support the opt-out nature of `backgroundColor` and `color`? I'm assuming that we do.

**Comment by oandregal** [comment]
> Do we still want to support the opt-out nature of backgroundColor and color? I'm assuming that we do.

We need to keep it for backward compatibility purposes.

**Comment by jeyip** [comment]
I created a preliminary PR that continues to respect backgroundColor and color supports as opt out support keys. Would love to hear your thoughts on it when you get a chance @nosolosw  https://github.com/WordPress/gutenberg/pull/34293
