### ISSUE TITLE
New widgets

### ISSUE THREAD

**Issue by darkonelson** [WordPress/gutenberg#34162]
I dont know where is problemm but after 5.8 WP upgrade some widgets disappear. Second -Astra theme customizer wont work like before. No icons in customizer and cant open links on main menu??  Need to open 3 or 4 times customizer to get edit icons.  
I can edit widgets but there s not save button like on some YouTube videos. If I wont to edit widget only name appear and when I want to edit there is nothing inside???
I was thinking that is Astra theme problem but  everything directs me to new widgets.
Also if I test site for mobile some parts of theme not loaded -mainly widget area.
Nelson
![Astra customizer menu without icons for edit](https://user-images.githubusercontent.com/87546406/130046884-d937d046-bb04-4aa2-8e28-e5aea9e3d81b.jpg)
![Mobile test -some resources not loaded](https://user-images.githubusercontent.com/87546406/130046979-405c340f-1064-4fd4-88e6-bf34db11fd49.jpg)

**Comment by lwangdu** [comment]
If you install the classic widgets, it will fix this problem. The problem is installing the classic widgets, you can't use block widgets.

**Comment by darkonelson** [comment]
Yes I use plug in for old widgets. Why? New WP widgets on my page dont have
save button for some reason. I can create for example new widget and after
that cant save him. But widget appear on page. If I want to edit same
widget there is nothing inside??? I looked at the youtube instructions and
there is a save button everywhere but not with me. What would be the cause
of that? I really want to use new widgets.I used to have a screen where I
could prepare a widget and use it if I needed to. Now that's gone?
Thanks for your answer
Darko

**Comment by ramonjd** [comment]
For theme-specific support, it might be worth pinging the folks over in https://wordpress.org/support/theme/astra/, or the [theme authors themselves](https://wpastra.com/contact/). 

This article also might be helpful, https://wpastra.com/docs/enable-astra-widget-design-options/
