### ISSUE TITLE
Navigation submenu not selectable when overlapping cover block

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#34161]
### Description

Navigation with a submenu is not fully selectable and partially hidden, when the submenu extends far enough to overlap with a cover block.

This issue is only present when the "Enable responsive menu" display option is toggled on

### Step-by-step reproduction instructions

Add a navigation block with at least one submenu from a parent menu item.
Toggle the "Enable responsive menu" option.
Below the navigation, add a cover block.

### Screenshots, screen recording, code snippet

![responsive-menu-overlap](https://user-images.githubusercontent.com/76742815/130045030-e5edd143-7476-47e8-8974-ed92acf80827.jpg)

Notice the menu with the "Enable responsive menu" option not activated is okay.

### Environment info

WP 5.8
Gutenberg 11.3
Windows 10, Firefox and Chrome browser.
TT1 Blocks theme, same result in other themes also.

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by lwangdu** [comment]
That is interesting. I am using Mac Ox. I don't have this problem on Firefox or Chrome. See the screen shot.
![Screen Shot 2021-08-19 at 7 42 38 AM](https://user-images.githubusercontent.com/24829573/130090170-e6eae4f9-a785-4c66-ac48-4f51ab9bd404.png)

**Comment by Sandstromer** [comment]
It appears the responsive enabled menu has extra modal/container wrappers, the first one `.wp-block-navigation__responsive-container` has a z-index of 1. Changing this to 2 seems to fix it.

@lwangdu could this be one of those items that a Mac "fixes" on-the-fly?

**Comment by lwangdu** [comment]
You are right @Sandstromer if you I enable responsive menu, it changes background color. I can't tell looking at inspect z-index change or not. That is weird. See the screen short again.
![Screen Shot 2021-08-19 at 8 31 48 AM](https://user-images.githubusercontent.com/24829573/130099236-1729045c-7986-4f50-8417-54e225865a82.png)

**Comment by talldan** [comment]
Thanks for reporting, this seems like a regression of a previously fixed issue - https://github.com/WordPress/gutenberg/issues/20203.

**Comment by lwangdu** [comment]
This is something to do with enable responsive menu. Also I don't see enable responsive menu option when you create navigation header template section.
