### ISSUE TITLE
Inserting Gallery Block crashes Gutenberg

### ISSUE THREAD

**Issue by ephox-mogran** [WordPress/gutenberg#3417]
## Issue Overview

After creating a gallery, a JS error is thrown during rendering which breaks the page and shows a blank screen.

The error is:

```
TypeError: Cannot read property 'props' of null
    at index.js:16070
    at U (react.min.6b26329b.js:13)
    at u (react.min.6b26329b.js:12)
    at u (react.min.6b26329b.js:12)
    at u (react.min.6b26329b.js:12)
    at G (react.min.6b26329b.js:14)
    at Object.map (react.min.6b26329b.js:21)
    at index.js:16069
    at arrayMap (index.js:1376)
    at map (index.js:942)
```
Note, this is in `slot.js`.

## Steps to Reproduce (for bugs)

1. Create a new post
2. Insert a gallery

## Expected Behavior

A gallery is inserted and Gutenberg continues to work normally.

## Current Behavior

The app crashes

## Possible Solution

Something is returning a null value, so we'll just have to identify what it is.

**Comment by ephox-mogran** [comment]
Seems to happen for Heading as well.

**Comment by ephox-mogran** [comment]
It looks like it might be anything which has `BlockControls` with no child elements. Makes sense given that it's complaining about children in the slot code.

**Comment by tg-ephox** [comment]
@youknowriad 
It looks like [this line](https://github.com/WordPress/gutenberg/blob/80caeb8678f67809ba409ff276342340d62a018f/components/slot-fill/slot.js#L59) expects children to only be react elements and not null, false, undefined or an array.  

At first investigation it looks like [Children.toArray](https://reactjs.org/docs/react-api.html#reactchildrentoarray) might be able to handle more complex children structures.  But you might have had a reason not to use this?

From local testing (Heading, Gallery, Block Settings) the following change seemed to solve the issue:
```--- a/components/slot-fill/slot.js
+++ b/components/slot-fill/slot.js
@@ -55,11 +55,7 @@ class Slot extends Component {
                return (
                        <div ref={ this.bindNode }>
                                { map( getFills( name ), ( fill ) => {
-                                       const fillKey = fill.props.instanceId;
-                                       return Children.map( fill.props.children, ( child, childIndex ) => {
-                                               const childKey = `${ fillKey }---${ child.props.key || childIndex }`;
-                                               return cloneElement( child, { key: childKey } );
-                                       } );
+                                       return Children.toArray( fill.props.children );
                                } ) }
                        </div>
                );
```

**Comment by youknowriad** [comment]
Good exploration @tg-ephox Thanks for looking into this. There's no reason not to use `.toArray` but we still need to loop over the children to update their keys. This fixes a "remounting" bug we had in `react-slot-fill`.
