### ISSUE TITLE
Copied blocks get duplicated when pasted inside empty page

### ISSUE THREAD

**Issue by arjendejong12** [WordPress/gutenberg#34177]
### Description

When copying content from a Gutenberg page where the last block is a group block, and then pasting it into a new page or the same page with all blocks removed, causes all blocks except the last group block to be duplicated. This also happens with other blocks that use innerBlocks, like my custom container block or the container blocks from Stackable and Gutentor, so it seems that there's an issue with blocks that allow innerBlocks.

### Step-by-step reproduction instructions

1. Open a new page.
2. Paste code block below in the page.
3. See duplicated content except for the last block.

### Screenshots, screen recording, code snippet

```
<!-- wp:group {"backgroundColor":"vivid-green-cyan"} -->
<div class="wp-block-group has-vivid-green-cyan-background-color has-background"><!-- wp:paragraph -->
<p>This is group one.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p>This is a regular paragraph.</p>
<!-- /wp:paragraph -->

<!-- wp:group {"backgroundColor":"pale-cyan-blue"} -->
<div class="wp-block-group has-pale-cyan-blue-background-color has-background"><!-- wp:paragraph -->
<p>This is group two.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

![gif](https://user-images.githubusercontent.com/10572554/130093054-9f0a503d-ff18-46b7-9ce9-c9de1ee8188d.gif)

### Environment info

WordPress: 5.8
Gutenberg: 11.3
Theme: Twenty Twenty-One
Browsers: latest Firefox, Chrome
Device: Desktop with Windows 11

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by glagonikas** [comment]
Hi @arjendejong12 does this only occur in the scenario you described?

In our case, it also happens for 
1. A spacer block as the last element
2. A "Columns" block as the last element

If the page content ends in a "normal" element such as a paragraph, it doesn't duplicate.

Maybe it's worth testing the scenarios above and if you can reproduce, change the title, to widen the scope of the bug?

p.s. the problem appears to occur while pasting the content to the editor, not on copying. If you paste the content in a text editor, you should notice there's no duplication.

**Comment by arjendejong12** [comment]
Hey @glagonikas, this also happens here with both scenarios that you described.

**Comment by glagonikas** [comment]
Great, thanks for confirming.

@skorasaurus this seems to be an issue with more than one block types, not just "Group". Can you change the label to something more relevant? Possibly consider changing its priority, given it's probably more common than originally thought?

Updating the title to something more generic like "Copied blocks get duplicated when pasted inside empty page" might also help.

**Comment by skorasaurus** [comment]
ran into this again (although it does not happen every time I copy several blocks), forgot to document how to reproduce more clearly: 

1. create new page; 
2. take the code snippet, paste into code editor (not a code block) 
3. select the blocks, (make sure you select all 3) (snack notice at bottom of screen will state that 3 blocks have been copied to clipboard
4. exit page 
5. create new page 
6. control + v 
(I was able to also reproduce this same behavior if you copy it from a page that has already been published as well. 

also was reported at https://core.trac.wordpress.org/ticket/53749
