### ISSUE TITLE
Border controls: Add the ability to choose specific sides the border should appear on

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#34179]
The current border controls do not allow us to (for example) display the border only on the top or bottom of a block. Take this Twenty Twenty-One pullquote for example: 

<img width="652" alt="Screen Shot 2021-08-19 at 11 51 13 AM" src="https://user-images.githubusercontent.com/1202812/130101653-e9e7c8bf-201f-4a9d-b11e-0907149ffb5e.png">

If we apply border settings in theme.json, it'll apply the border on all sides, and there's no way to change that: 

<img width="641" alt="Screen Shot 2021-08-19 at 11 51 18 AM" src="https://user-images.githubusercontent.com/1202812/130101763-bc438445-3de9-49e3-bce3-d93d26f47be0.png">

---

Current border controls UI, for reference: 

<img width="280" alt="Screen Shot 2021-08-19 at 11 56 35 AM" src="https://user-images.githubusercontent.com/1202812/130101904-60edcdbb-b191-4576-b125-2b72d19a3aef.png">

**Comment by skorasaurus** [comment]
This has been implemented.
