### ISSUE TITLE
Is this healthy, the layout shifting

### ISSUE THREAD

**Issue by ugenegrg** [WordPress/gutenberg#34193]
If I search something in the block search the layout shifts to show the results.
Some are noticeable and some fine but could it be improved.
https://screencast-o-matic.com/watch/crjYjRVjHkM

**Comment by ramonjd** [comment]
> Some are noticeable and some fine but could it be improved.

Hi! Thanks for creating this issue.

Playing around with the inserter, I do see that the dialog does increase/decrease in height depending on how many block and patterns appear in the search results.

<img width="372" alt="Screen Shot 2021-08-24 at 3 38 48 pm" src="https://user-images.githubusercontent.com/6458278/130561925-87d90000-a88e-4ae7-810e-cdfd01845e7a.png">

Are there any specific improvements you could think of and add to the description? 

How would editor users benefit from these improvements?

Thank you!

**Comment by ugenegrg** [comment]
Hi Team, here is my suggestion. Not a good one :). But this is only - If I had to do by my way
https://screencast-o-matic.com/watch/crQ6h3VQKfT

**Comment by priethor** [comment]
There have been lots of changes in layout in the last two years in Gutenberg 😅 

@ugenegrg is this issue still relevant? Please feel free to reopen this ticket if so. 🙏
