### ISSUE TITLE
Post Date: Add more typography options.

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#34192]
When it comes to typography options, the Post Date block supports only font size at the moment. It would be great if we had more settings for things like:
- [x]  font-weight
- [x] font-style (italics)
- [x] uppercase
- [x] letter-spacing

This might be a can of worms, but it would also be nice to be able to use the headings font for Post Date (and post meta elements) in general. I looked over a few themes, and it seems to be a popular choice, that gives the design a more refined look:

Independent Publisher 2

![image](https://user-images.githubusercontent.com/4550351/130182921-d3505ccd-7dd0-4231-a3b9-82601136b017.png)

TwentyTwenty

![image](https://user-images.githubusercontent.com/4550351/130183384-efd00333-5456-4c99-90fe-ca126a45f2ba.png)

TwentySixteen

![image](https://user-images.githubusercontent.com/4550351/130183511-2cb93f03-202b-4243-878b-a91d35e950b0.png)

Ideally, these typography options would be available to Post Categories and Tags as well - I can open separate tickets for those if there's interest in adding them.

**Comment by scruffian** [comment]
Font weight is now possible to set, but not the others
