### ISSUE TITLE
Group inner container restoration can cause duplicate inners to occur with large content to check

### ISSUE THREAD

**Issue by davecpage** [WordPress/gutenberg#34199]
### Description

The regex used in `gutenberg_restore_group_inner_container()` and the corresponding `wp_restore_group_inner_container()` does not appear to work as intended when there is a large amount of inner content. This can lead to the first regex failing to detect the inner__container, leaving the second regex to add a second container. For themes that expect only one, this can cause layout issues.

An initial example of content that breaks with the regexes in that function: https://3v4l.org/1s7cT

The sample content is structured as :
* Group
  * Heading
  * Latest Posts (filtered to change the output HTML and add extra elements)

My understanding is that the backtracing steps get so overwelmed that they can trigger limits set on hosts, and failing the first match causes the second to be applied.

Partially this only occurs because if the content was originally written in WordPress 5.7 'the_content' will contain the inner__container, so the PHP should not run. Whilst creating/editing the content WP 5.8 the inner__container will never be there for the first regex to match against.

I'm thinking that to reduce the steps for the regex the Ungreedy flag can be added, but also the last groupings `((.|\S|\s)*)` don't appear to be required which would further reduce the overal steps.

Related: #30443, #30461

### Step-by-step reproduction instructions

1. Within WordPress 5.7 create content of a group and a large number of any other blocks that cause a lot of HTML, such as Latest Posts
2. Update the site to WP 5.8
3. Check the frontend HTML to see double inner__container for the group

### Screenshots, screen recording, code snippet

Markup and regex example with possible changes on https://3v4l.org/1s7cT

### Environment info

- WordPress version: 5.8
- Gutenberg version: 11.3.0 (not active)

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by talldan** [comment]
Thanks for the very detailed bug report!

I've labelled as a bug, though I haven't been able to test it.

@davecpage Would you be interested in contributing a fix for this problem? The code contribution guidelines are here - https://github.com/WordPress/gutenberg/tree/trunk/docs/contributors/code. It's not too difficult, but seems like a pull request would be the best way to get technical feedback.

I'll also cc @youknowriad @ockham who are familiar with the code.

**Comment by talldan** [comment]
There's a very similar issue reported here - https://github.com/WordPress/gutenberg/issues/34404.

**Comment by davecpage** [comment]
Hi @talldan I should have updated this ticket, as the code was already in core I submitted a patch via https://core.trac.wordpress.org/ticket/54013. Is that the best location for it? Or should it be in Gutenberg first then backport to core?

**Comment by talldan** [comment]
Thanks for contributing the code, @davecpage. I think the process is usually that the code is fixed in the Gutenberg plugin (this codebase) first and then backported. It's also probably ok to fix in core at the same time as here, though.

@noisysocks is the editor release lead for 5.9 and knows the process better than I.

**Comment by noisysocks** [comment]
The change needs to be made in both Core and in the plugin. If you open a Gutenberg PR with the change then I can ensure it makes it into WP 5.9.

**Comment by davecpage** [comment]
Hi @noisysocks I've added a PR for the Gutenberg repo which matches the change I submitted as part of https://core.trac.wordpress.org/ticket/54013
