### ISSUE TITLE
Provide means to enable/disable Global-level configuration of blocks

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#34206]
## What problem does this address?

While it's (theoretically*) possible for themes (via theme.json) to control what aspects a block has available for user control this disables access BOTH Globally (in the FSE Global Styles 'By Block' panel) as well as Locally (Block instance controls).

Because the two systems (Global ..er.. Global Styles and Local Block Styles) work differently it may be necessary to allow for GLOBAL but not LOCAL or LOCAL but not GLOBAL configuration of settings.

As an example; In the case of Blockbase the Global Style Mechanism for configuring button colors currently results in a poor user experience (hover states don't follow color choices, padding controls don't work, etc).  It is desired that the Global Style configuration for Buttons be disabled by the theme (preferably just COLORS and PADDING, though disabling ALL Global Style Configurations for Buttons would also be groovy).  LOCAL (block instance) controls of colors and padding work just as the user would expect and should remain in place.

Buttons have a long way to go before they can be appropriately styled Globally and until that effort is complete allowing a theme to decide and control which aspects of the GLOBAL style are provided to the user would mitigate that. 

## What is your proposed solution?
Provide configuration options in theme.json that allows for the enabling and disabling of Block-specific configuration controls in the FSE Global Styles panel.

Something such as:

````
{
    "version": 1,
    "settings": {
        "globalStyles": {
            "blocks": {
                "core/button": {
                    "color": {
                        "custom": false,
                    }
   ...
````

* Note that the ability to disable custom color controls at the ANY level for buttons doesn't seem to work either, though that's a separate issue as the mechanism is at least [documented](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/).

**Comment by karmatosed** [comment]
I don't think this needs design feedback as feels like it's on a non-interface level but I do like the idea of complete disabling myself. For now I am going to triage away that label though.
