### ISSUE TITLE
Pressing Delete followed by Enter deletes rest of paragraph

### ISSUE THREAD

**Issue by nyanpasu64** [WordPress/gutenberg#34213]
### Description

When I place the cursor at the end of a paragraph (or empty line), press Delete to merge the next paragraph into the current, then Enter to split the paragraph into two, the original next paragraph's text is deleted instead.

### Step-by-step reproduction instructions

1. Edit a post with two or more paragraphs, and place the cursor at the end of the first paragraph.
2. Press the Delete key to merge the next paragraph into the current.
3. Press the Enter key to split the two paragraphs again (which would work if the bug wasn't present).

If you place the cursor at the beginning of the second paragraph, then press Backspace and Enter, the bug does not occur.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/913957/130324988-73476292-8363-4147-87ab-94710a046fb1.mp4

### Environment info

- Version: Wordpress 5.8, built-in editor and Gutenberg 11.3.0, Argon theme
- Browser: Firefox and Edge
- Device: Laptop with Windows 10 x64

This seems related to #18103, like that issue was only partially fixed and this sequence of inputs is still broken.

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by westnz** [comment]
I was able to reproduce this error.
