### ISSUE TITLE
Nav Editor menu title doesn't support special characters

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34223]
### Description

In the new Navigation Editor screen, if you create a menu with a character such as an apostrophe then it will render incorrectly.

### Step-by-step reproduction instructions

1. In new Navigation Editor screen - create menu with title `Dave's Menu`.
2. Save.
3. See Menu title is not rendered correctly.

### Screenshots, screen recording, code snippet

<img width="1098" alt="Screen Shot 2021-08-23 at 10 27 35" src="https://user-images.githubusercontent.com/444434/130424615-2dec6070-95be-4274-b390-6f97a0067cd1.png">

### Pre-checks

- [ ] I have searched the existing issues.
- [ ] I have tested with all plugins deactivated except Gutenberg.

**Comment by Mamaduka** [comment]
@getdave, I can create a fix for this one later today unless you're already working on it.
