### ISSUE TITLE
Scripts: Filename changes to main.js when ouput-path parameter is added

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#34239]
### Description

Related to webpack v5 migration: #33818.

If I add a `output-path`, the build files are renamed to `main.js` and `main.asset.php`. Without the parameter, the filename doesn't change.

### Step-by-step reproduction instructions

`wp-scripts build --entry ./src/index.js --output-path=custom`

### Environment info

- WP Scripts 18

**Comment by gziolo** [comment]
There is a similar issue reported related to how entry points are handled with webpack 5: https://github.com/WordPress/gutenberg/issues/34236.

It looks like the following doesn't work anymore with the latest major version of `@wordpress/scripts`:
```sh
npx wp-scripts build ./src/frontend/index.js
```

**Comment by walbo** [comment]
The default entry name in webpack is `main`, and in the config filename is set to `[name].js`. You can overwrite the filename config by adding `--output-filename`.

```
wp-scripts build --entry ./src/index.js --output-path=custom --output-filename=index.js
```

**Comment by gziolo** [comment]
@walbo thank you for sharing the example. It partially works with the default webpack config, in the context of blocks:

<img width="352" alt="Screen Shot 2021-08-25 at 10 44 31" src="https://user-images.githubusercontent.com/699132/130759226-a9f60b59-8b83-4c59-902b-cf6fd2d56ba3.png">

While it applies changes to the output folder and the JavaScript filename, it doesn't get propagated to CSS chunks.

See my related comment for more details: https://github.com/WordPress/gutenberg/pull/34264#issuecomment-905306696.

**Comment by gziolo** [comment]
It looks like https://github.com/WordPress/gutenberg/pull/34264 will fix this issue.

**Comment by gziolo** [comment]
There is `@wordpress/scripts` v18.0.1 available with the fix.
