### ISSUE TITLE
scripts: Unknown command or entry 'index=./src/frontend/index.js'

### ISSUE THREAD

**Issue by cpiber** [WordPress/gutenberg#34236]
### Description

Related to webpack v5 migration: #33818.

Using the latest `@wordpress/scripts` (18.0.0), building with a custom entry point is not possible (`npx wp-scripts build ./src/frontent/index.js`).

```
[webpack-cli] Unknown command or entry 'index=./src/frontend/index.js'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

Works normally without the optional path.

Works as expected in 17.1.0.

### Step-by-step reproduction instructions

1. Install `@wordpress/scripts@latest`
2. Run `npx wp-scripts build <some path>`

### Environment info

- Ubuntu 18.04
- Node v14.17.5

### Pre-checks

- [X] I have searched the existing issues.
- [ ] I have tested with all plugins deactivated except Gutenberg.

**Comment by gziolo** [comment]
It looks like webpack 5 handles entry points differently when passed through CLI:

https://webpack.js.org/api/cli/#entry

vs

https://v4.webpack.js.org/api/cli/#usage-without-config-file

It's very likely that we can remove special handling added for webpack 4 from:

https://github.com/WordPress/gutenberg/blob/9e3be448664646245c875baa01539a7bd96ee99a/packages/scripts/utils/config.js#L112-L142

**Comment by gziolo** [comment]
It looks like https://github.com/WordPress/gutenberg/pull/34264 will fix this issue.

**Comment by gziolo** [comment]
There is `@wordpress/scripts` v18.0.1 available with the fix.
