### ISSUE TITLE
Cannot add reusable blocks to a widget area (“sidebar”)

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#34237]
### Description

Editorially-created reusable blocks are not available in widget areas. (With or without the Gutenberg plugin in use.)

### Step-by-step reproduction instructions

1. Navigate to a widget area.
2. Use the block selector options (including slash).
3. Reusable blocks are not available.

### Environment info

- WordPress Core 5.8
- With and without latest Gutenberg plugin.

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by talldan** [comment]
Thanks for reporting. This is already tracked in https://github.com/WordPress/gutenberg/issues/32952, so I'll close your issue.

**Comment by JTorresConsulta** [comment]
At this moment Wordpress has become a frustration factory

You cannot use widgets in the block editor
You also can't use blocks in the widget editor

LOL
