### ISSUE TITLE
Click into the Nav block area and write. Have link box show up.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#34247]
## What problem does this address?
Adding a block to the Navigation block.

## What is your proposed solution?
Click into the Nav field and write (as if it was a paragraph/heading block). Have the link control box show up and give alternatives. 

Mockup example. User writes the example word custom and stops writing and the link control shows up to give alternatives.
![Just-write-have-link-control-show-up](https://user-images.githubusercontent.com/5323259/130529089-604a2408-51a2-47dd-a4a5-abbadeb2ac96.jpg)

**Comment by mtias** [comment]
Closing as superseded by https://github.com/WordPress/gutenberg/issues/34041#issuecomment-900181007

**Comment by paaljoachim** [comment]
Ahh nice. Thanks for sharing Matias!
