### ISSUE TITLE
Highlighting column icon in toolbar to reflect which nested column is selected?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#34245]
## What problem does this address?
There is no visual to show which column one has selected. Yes one can assume by clicking all the way to the left that column one is selected. Clicking a little to the right that column 2 is selected etc.
But there is to clear way to know which column is currently selected.

## What is your proposed solution?

Here is the Header template showing a dark top part.
![Screen Shot 2021-08-24 at 00 07 33](https://user-images.githubusercontent.com/5323259/130525724-da55cae3-b376-49e8-b3a3-f66e864b050b.jpg)

As the Header is usually in the top of a page the icon shows a dark top section.
At the same time notice the Columns block which is nested inside the Header. It has no dark area. Perhaps because no column area is directly selected, as only the general Columns block is selected.

Here is what is seen when clicking the first column inside the columns block.
![Screen Shot 2021-08-24 at 00 11 17](https://user-images.githubusercontent.com/5323259/130526063-ca592056-5752-4c28-a2f7-ed66a230450c.jpg)

It looks like column 2 is selected. But this is just the general icon for the nested columns block. 

It would be nice to have a nested column block that had a dark area change depending on which column one is in.
There are of course a few things. The column block icon has only 3 columns. I assume that one can not easily change the nested column block to reflect which column one is in.
So I am looking at finding ways to have a visual que for the user to show which column area is currently selected.

**Comment by karmatosed** [comment]
@paaljoachim it seems a little unclear what you are actually intending here, are you suggesting a state change on the actual icons? That could be confusing and I think it needs to be weighed up as to the usability benefit.

- Are you looking at the toolbar for the icon?
- Do you need to see a consistent state for icon and if it changes will it cause usability issues?
- What benefit does seeing a small icon this change have if it might not even be clear (I'm not convinced what is being proposed is clear).

I would vote to not implement this and explore other options if this is a problem, the icon doesn't feel like the right solution.

**Comment by paaljoachim** [comment]
Hey Tammie. I will go ahead and close this issue.
