### ISSUE TITLE
Right column toolbar outside document canvas

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#34248]
### Description

TT1.
3 columns.
The right most column. Adding a Nav and search block these show outside the document screen when the browser window is at 1600px or smaller. Chrome OSX.

### Step-by-step reproduction instructions

1. Use TT1
2. Add three columns to the Header template area.
3. Select Column 3.
4. Add a Navigation block and a search block inside it.
5. Notice when either the Nav or the Search block is selected and the screen resolution is 1600px or smaller that the toolbar goes outside the canvas/document area.

### Screenshots, screen recording, code snippet

Resizing the browser window.

https://user-images.githubusercontent.com/5323259/130529960-322d5c83-8b26-4aac-ba88-86da401726c0.mp4

### Environment info

WordPress 5.8
Theme: TT1
Gutenberg plugin 11.3.0
OSX 11.5.2
Chrome
Local test site.

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by jasmussen** [comment]
Is this a duplicate of https://github.com/WordPress/gutenberg/issues/34053?

**Comment by paaljoachim** [comment]
Great! I was sure I made a duplicate! Thanks Joen!
