### ISSUE TITLE
Navigation block: Start writing to automatically add a custom link

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#34246]
## What problem does this address?
One has to add a block to the Navigation block.

## What is your proposed solution?
Click the black inserter icon and start writing and automatically have the option to add a custom link.

Going from this:
![Screen Shot 2021-08-24 at 00 24 46](https://user-images.githubusercontent.com/5323259/130527262-c94259c3-747a-4002-ab88-8d178b215654.jpg)

To this:
![Auto-Add-Custom-Link](https://user-images.githubusercontent.com/5323259/130527395-b4ea23a3-8509-493c-ac7d-c7fb900cccc7.jpg)

Or even better one just begins to write and Gutenberg assumes the user is writing the name of the custom link and automatically adds it.

![Screen Shot 2021-08-24 at 00 29 54](https://user-images.githubusercontent.com/5323259/130527661-71356769-5369-4751-84cb-28393236b9a4.jpg)

**Comment by paaljoachim** [comment]
Actually  if one writes the name of an existing page/post then one could have the option to add it to the Nav block.

**Comment by jasmussen** [comment]
I'm not sure this is the best idea as it dilutes the experience of the quick inserter as a tool to insert _blocks_. There's a great ticket in https://github.com/WordPress/gutenberg/issues/34041 that discusses the same problem but where solutions a few other solutions are explored. Should we close this one in favor of that, you think?

**Comment by paaljoachim** [comment]
Yeah. Lets focus on the issue #34041 and close this (for now).
