### ISSUE TITLE
Block style variations: make sure the name does not contain spacing before creating the class

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#34242]
### Description

This was reported in [slack](https://wordpress.slack.com/archives/C02QB2JS7/p1629731076397000) (link requires registration).

The process of generating a class for a style variation is not checking for spaces.

### Step-by-step reproduction instructions

- Add a style variation such as (note the spacing in the name):

```php
register_block_style( $block, array(
	'label' 			=> esc_html__( 'Style Name', 'slug' ),
	'name'  			=> 'style-class-1 style-class-2'
) );
```
- When this style variation is selected by the user the CSS class attached to the block is `is-style-class-1 style-class-2`.

There should be validation and sanitization of the `name` parameter so it doesn't contain spaces.

### Pre-checks

- [X] I have searched the existing issues.
- [ ] I have tested with all plugins deactivated except Gutenberg.

**Comment by amustaque97** [comment]
:wave: @oandregal, I would love to work on this issue. Could you please highlight some ideas/areas on how to fix this issue? 
As per my understanding, `register_block_style` can be called from any custom/user theme or plugin how can we add sanitisation/validation there? 
Thank You

**Comment by oandregal** [comment]
:wave: @amustaque97 You're very welcome to pick this up.

I presume there're two ways to address this:

- One approach would be fixing the issue when the style is registered. This requires fixing upstream, in WordPress core, where [that method is declared](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/blocks.php#L971). During registration we do some checks (such as making sure `name` is a string), so I presume we could also sanitize the provided value before is stored in the registry.

- The second approach would be making sure the name is sanitized when it's converted into a class. I haven't looked at this deeply, but looking at the [UI component that does this job](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/block-styles) should give you a hint.

Hope this is helpful!

**Comment by ntsekouras** [comment]
Hey @amustaque97 👋 !

I think @oandregal 's first suggestion is the proper place for this fix. As mentioned above it requires a fix in WP core and specifically [here](https://github.com/WordPress/wordpress-develop/blob/40fd54aedee161cbfa10d352053082ccc1d2c02a/src/wp-includes/class-wp-block-styles-registry.php#L54). By having a client side fix in `BlockStyles` component will not prevent the same issue from happening in other implementations of `selecting a style` which are going to use the `getBlockStyles` selector.

**Comment by amustaque97** [comment]
@ntsekouras, this issue can be closed now. WP core changes has been merged. You can check the status as well https://core.trac.wordpress.org/ticket/54296

**Comment by ntsekouras** [comment]
Thanks so much for your contribution @amustaque97! Great work 💯
