### ISSUE TITLE
Navigation Block: dragging a block in List View modal causes the modal to close unexpectedly

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#34254]
### Description

As soon as a user drags a block in the List View modal it closes unexpectedly.

This feature worked when the drag and drop feature was introduced, so this appears to be a regression.

### Step-by-step reproduction instructions

1. Add a navigation block with some links inside it
2. Select the navigation block and open the list view from the block's toolbar
3. Try dragging one of the blocks

Expected: It's possible to drag and drop a block
Actual: The modal closes unexpectedly and the drag operation is cancelled

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by jasmussen** [comment]
CC: @gwwar in case you have any ideas.

**Comment by talldan** [comment]
I'm not actually experiencing the issue now. I wonder if my build had some issues. Let me know if you can reproduce, but if not I'll close this tomorrow.

**Comment by gwwar** [comment]
This will likely happen if a drag-&-drop triggers the primary onClick handler

**Comment by gwwar** [comment]
FWIW I'm not able to trigger this on trunk, so it's probably okay to close out.

**Comment by gwwar** [comment]
🤔 So I dug around a bit, and I think the modal closing on a navigation block item select is a side-effect of the selected block focus (which is technically outside of the modal). I'll spin up a smaller PR that alters this behavior so the modal remains open on select, it doesn't appear like this was intentional.

**Comment by talldan** [comment]
Hmm, yeah. I haven't been able make it happen again!

I wonder what it was. I had a hunch that maybe LinkControl was stealing focus when a navigation link doesn't have a URL, but that doesn't seem to be the case.

**Comment by gwwar** [comment]
With changes in https://github.com/WordPress/gutenberg/pull/34337 this should no longer be possible 👍
