### ISSUE TITLE
Block Widgets: YouTube widget does not show embed preview

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#34252]
### Description

Youtube Widget does not show a preview of the embedded video within the Block Widget Editor in the customizer. The block/widget itself is there - but with no preview it is *very* difficult (near impossible) to select.

### Step-by-step reproduction instructions

1. Open the Customizer > Widgets and add a new YouTube widget.
2. Enter YouTube url into the field and embed.

### What I expected

The YouTube embed to show a preview within the Customizer

### What happened

No preview was shown - it looked as though the widget itself had disappeared.

### Additional Note

When viewing the widgets in the dedicated interface (Appearance > Widgets) the preview for the YouTube widget *does* display as expected.

### Screenshots, screen recording, code snippet

<img width="290" alt="Screen Shot 2021-08-24 at 12 45 56 pm" src="https://user-images.githubusercontent.com/1842363/130548016-2fb4e977-1fd7-4f7d-a37f-3cc56f89f13c.png">

Youtube widget in Customizer

<img width="1057" alt="Screen Shot 2021-08-24 at 12 45 18 pm" src="https://user-images.githubusercontent.com/1842363/130548025-a9a78ab8-a1cf-421e-9ce8-072cc1cc2521.png">

YouTube widget in Appearance > Widgets 

### Environment info

* WordPress 5.8
* Twenty Twenty One
* Present with no plugins active, *and* with only Gutenberg plugin active

### Pre-checks

- [X] I have searched the existing issues.
- [x] I have tested with all plugins deactivated except Gutenberg.

**Comment by liviopv** [comment]
Loading the Block Widgets editor from `/wp-admin/widgets.php` shows the Youtube Blocks correctly.

I'm seeing this error in the console, which seems to be related:

`customize.php:1 
Refused to execute script from 'https://artists.youtube.com/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

**Comment by annezazu** [comment]
This is wildly similar to this previous issue: https://github.com/WordPress/gutenberg/issues/30663

**Comment by walbo** [comment]
Related trac ticket: https://core.trac.wordpress.org/ticket/53609
Related PR: #33516

**Comment by noisysocks** [comment]
I'm no longer seeing this running latest Core & Gutenberg.
