### ISSUE TITLE
Navigation block: allow for collapsed (i.e. responsive) vertical menus on desktop/tablet

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#34253]
## What

Allow for drop-down menus, akin to HTML select boxes

## Why

In instances where a user is trying to add a vertical menu, and they might just like a select box, this would be helpful. Just a plain, ordinary drop-down.

For example, I am trying to create multiple group blocks, each with their own title and menu below. A drop-down would be useful here to ensure that each group remains in proportion to one another, and that all menu options are not exposed by default.

<img width="1406" alt="129625025-3cde99be-66c4-494c-b74b-fa1f97ad2103" src="https://user-images.githubusercontent.com/1842363/130550782-841b4c98-3a82-47e8-b8a6-cdf012c850c9.png">

## How

Not sure.

----

Originally reported by @jonny-a8c

**Comment by annezazu** [comment]
Thanks for this issue! Just wanted to note that a drop down block is being considered: https://github.com/WordPress/gutenberg/pull/33775 

cc @jasmussen

**Comment by jasmussen** [comment]
Thanks for the ping Anne!

Let me be sure I'm understanding this right, is this about allowing the creation of a navigation menu (or list of links if you'd like to call it that) which _always_ collapses to a burger button? If so, I definitely agree with that feature request, and there's a mockup and ticket for it in https://github.com/WordPress/gutenberg/issues/30370.

**Comment by metabreakr** [comment]
@jasmussen  Yes, that's the idea — a hamburger menu, or something similar, regardless of viewport size.

**Comment by jasmussen** [comment]
Awesome. I retitled https://github.com/WordPress/gutenberg/issues/30370 to include the ability to always show the burger menu. Should we close this one in favor of that?

**Comment by annezazu** [comment]
Yes! Thank you for connecting the dots as always. Closing out now.
