### ISSUE TITLE
Create an hour-and-minute only TimePicker; rename existing TimePicker

### ISSUE THREAD

**Issue by milkcask** [WordPress/gutenberg#34250]
## What problem does this address?

The existing TimePicker operates on a full timestamp that points to a specific moment. In many use cases, we expect hour and minute inputs only, and dates could be indefinite or inapplicable.

## What is your proposed solution?

We need an hour and minute picker similar to time-picker at baseweb https://baseweb.design/components/time-picker/ .

Additionally, the existing TimePicker should be renamed to DateTimePicker to reflect its actual behaviour and the existing DateTimePicker should either be renamed or merged. However, it would be a breaking change.

proposed label: [Feature] UI Components, Needs Design

**Comment by ramonjd** [comment]
Thanks for the suggestion @milkcask !

Is it possible to add a couple of screenshots of the current and proposed states, just to help folks, who are looking at this issue for the first time, to understand from a visual perspective.

Also, adding an example use case where you'd expect to have hour and minute inputs only would also help to spark discussion. 

Thank you!

**Comment by mirka** [comment]
Closing in favor of #52734
