### ISSUE TITLE
Pasting text into a list block copied from a paragraph block is broken

### ISSUE THREAD

**Issue by ashfame** [WordPress/gutenberg#34262]
### Description

Hi, Tested this on a fresh WordPress install with no plugins.

Any text that you copy from a paragraph block or a heading block, it probably copies some meta data along with it, which when pasted in a list item of a list block, prevents the paste operation from working. Nothing happens. Works fine if pasting in paragraph block or heading block.

In browser console, I do see logs `Received HTML: Ash` and `Received plain text: Ash` though.

### Step-by-step reproduction instructions

- Create a new post. In first paragraph, enter text like "Howdy Ash".
- Hit enter and now switch to a list block (I used markdown parsing functionality to switch to a list by typing a hyphen and hitting Tab key)
- Copy "Ash" from the first block and try to paste in the first list item.
- Nothing happens.

### Environment info

- WordPress version: 5.8 (fresh install)
- No plugins (Reproducible with and without Gutenberg plugin activated)

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by mupic** [comment]
Inserting text also does not work in a quote block.

**Comment by westnz** [comment]
I was able to reproduce this. Nothing happened when I tried to paste 'text' into a list block copied from a paragraph block.

**Comment by yansern** [comment]
I'm not familiar with Copy & Paste operations so this might be completely wrong. A quick investigation into `use-paste-handler.js` shows that the `create()` function returns plain text, ignoring the `multilineWrapperTags` param.

![image](https://user-images.githubusercontent.com/1287077/137736108-89639a9b-c6b8-4de0-ac56-8aee3dd6345f.png)

Will be digging into why `multilineWrapperTags` param is ignored next.

**Comment by ellatrix** [comment]
The list block has been completely rewritten in #42711. I tested this an the issues seems to be resolved. Feel free to reopen if it's not the case.
