### ISSUE TITLE
Expose user facing documentation on the Navigation Editor screen

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34266]
## What problem does this address?
As discussed in the August Hallway Hangout for the Navigation Editor, it would be helpful to have some user facing documentation for the Nav Editor screen.

## What is your proposed solution?

As a start this doesn't have to be built into the UI. It could be as simple as a link to a README file for the Nav Editor package on Github. 

The earlier we start writing the user-facing docs the better.

**Comment by javierarce** [comment]
One idea to expose this help section could be under the ellipsis menu of the top bar.

![image](https://user-images.githubusercontent.com/4933/133771303-e005c728-52be-4789-9a07-503a5238ae5d.png)

**Comment by getdave** [comment]
Let's do it!
