### ISSUE TITLE
Featured Image Block: Alignment controls don't work in template editor after changing sizing

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#34270]
### Description

The alignment controls for the featured image block don't work after changing the size of the block in the template editor. 

### Step-by-step reproduction instructions

1. Use a site with template editing.
2. Create a new template.
3. Add the featured image block.
4. Change the width of the block.
5. Try to use the alignment controls. Notice the alignment doesn't change in the editor or on the front end. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/130669907-cc71129f-6d0f-4ebf-b054-832b3d6ebb94.mov

### Environment info

- WordPress 5.8
- Gutenberg 11.3
- TT1 Blocks
- Chrome
- Desktop, MacOS

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by annezazu** [comment]
Note that within the Query Loop block, alignment works on the front end but doesn't correspond properly in the editor itself. Figured this is likely related but happy to open a new issue if needed:

https://user-images.githubusercontent.com/26996883/130670857-9366ac33-6c6f-4b8e-a928-be44e0952c09.mov

**Comment by oandregal** [comment]
Hey Anne, I'm trying to reproduce the issue but I can't. Tried with `trunk` and `11.3.0` on WordPress 5.8. Using different browsers as well (Firefox and Chrome). My OS is Linux but I doubt that would have any impact on the issue at hand.

This is what I'm doing:


https://user-images.githubusercontent.com/583546/131878034-825ca9ec-e512-4fc2-b1c3-ce0e13829530.mp4

**Comment by annezazu** [comment]
Seems like it's somehow working when I use Gutenberg nightly (woohoo!) but I did notice a weird sizing change after altering the alignment:

https://user-images.githubusercontent.com/26996883/131878964-871a96a3-0329-48e8-a716-025009e1b7e8.mov

I filed this with 11.3 so not sure what PRs could have happened to address this.

**Comment by ntsekouras** [comment]
The difference between the first video by @annezazu and all the rest is that in the first video the block is added in a `template` without any container (you can observer the block icon in toolbar and also the available alignments). In order for the alignments to work properly they need a wrapper container like `Group` that adds the proper styles for such alignments for its children.

**Comment by oandregal** [comment]
@ntsekouras Got it. So the bug is that the `align*` classes are scoped to `wp-container-*` so in this situation they won't be available. Can we make the float classes (left, center, right) unscoped from `wp-container-*`? cc @youknowriad 

I see that the wide/full controls are working as expected already (hidden when no container). So, the other fix I can think of is disabling the controls in that situation, although I'm not sure how to go about it as we'd need a mechanism to detect whether a block is within a _container_ block.

**Comment by oandregal** [comment]
Discussed this with Riad: another alternative is to enqueue the float classes for the `site-blocks` container as well. This is actually more promising than the other two: while it may have value to only output the float classes once, we also want to make sure they don't affect different types of layouts such as flex.

**Comment by oandregal** [comment]
Prepared a PR to fix this at https://github.com/WordPress/gutenberg/pull/34635
