### ISSUE TITLE
Undoing Site Editor Navigation Actions Doesn't Undo the Action

### ISSUE THREAD

**Issue by bbertucc** [WordPress/gutenberg#34273]
### Description

Undoing Site Editor Navigation Actions Doesn't Undo the Action, specifically when adding a page link as a sub page in the navigation block

### Step-by-step reproduction instructions

I'm following [FSE Program Testing Call #9](https://make.wordpress.org/test/2021/08/11/fse-program-testing-call-9-handling-highered-headers/#comment-1910).. I accidentally nested a page link under another link in the navigation block. Immediately after doing this, I tried to undo my action but `command-z` only reloaded the editor page. Nothing was undone.

### Environment info

using the reccomended enviornment in [FSE Program Testing Call #9](https://make.wordpress.org/test/2021/08/11/fse-program-testing-call-9-handling-highered-headers/#comment-1910) with Chrome Version 92.0.4515.159 on macOS v.11.4

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by talldan** [comment]
I think this may have been fixed by https://github.com/WordPress/gutenberg/pull/34565.

When I tested there's now no problem with undo/redo. I'll close the issue, but reply to mention if you're still having issues in the latest version of Gutenberg, @bbertucc.
