### ISSUE TITLE
Components: use `colord` instead of `tinycolor2` in `ColorPicker`

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#34286]
Part of #34284

## Why

The [`colord` library](https://github.com/omgovich/colord) may be a better replacement for [`tinycolor2`](https://github.com/bgrins/TinyColor), which is currently used by the `ColorPicker` component:

- it has a smaller size
- it comes with first-party TS types

## What

The maintainer of `colord` [reached out to us in a previous PR](https://github.com/WordPress/gutenberg/pull/33714#issuecomment-897157426) and suggested we take a look at the `colord` library.

We should first assess the feasibility of this refactor (partially started in https://github.com/WordPress/gutenberg/pull/34014#discussion_r687904062)

## A/C

- [x] Assess if `colord` provides all needed functionality
- [x] Assess if any breaking changes are introduced
- [ ] Swap the libraries, update imports

**Comment by jorgefilipecosta** [comment]
It seems like colord combined with the names and a11y plugins provides the functionality we need. The readability from tinyColor that is widely used is the same number as contrast in colors. There is a function in tinycolor2 to return the most readable color from an array of colors that we also use in some cases including for providing a public API abstraction on top of (getMostReadableColor), that has nothing equivalent in colord but it is just a simple loop checking the contrast of all the colors in an array and returning the highest so we can easily implement it.

I think as long as we add the two plugins we don't need to introduce any breaking change.

**Comment by gziolo** [comment]
I see this call in https://github.com/WordPress/gutenberg/pull/34605:

```js
import { colord, extend } from 'colord';
import namesPlugin from 'colord/plugins/names';
import a11yPlugin from 'colord/plugins/a11y';

extend( [ namesPlugin, a11yPlugin ] );
```

How is it going to scale? Can you extend with the same plugin multiple times?

I would also argue if the bundle size is going to be the deciding factor with the plugin architecture, the core library is smaller than `tinycolor2` (5 kB):

<img width="509" alt="Screen Shot 2021-09-07 at 09 33 32" src="https://user-images.githubusercontent.com/699132/132303560-52906a00-b95b-4b54-a66a-85ea65f41873.png">

but there is additional overhead when using plugins:

<img width="551" alt="Screen Shot 2021-09-07 at 09 33 21" src="https://user-images.githubusercontent.com/699132/132303713-be360665-c36c-4c02-9089-60a8ad9f2458.png">
<img width="445" alt="Screen Shot 2021-09-07 at 09 33 25" src="https://user-images.githubusercontent.com/699132/132303718-97679dec-628d-4562-b751-e0b53dc2cd81.png">

Anyway, I don't care what you end up using eventually. I just wanted to raise some concerns I had. The call is on your side if it's worth an effort.

**Comment by ciampo** [comment]
> I think as long as we add the two plugins we don't need to introduce any breaking change.

From our initial investigation, I remember finding a potential (small) breaking change: https://github.com/WordPress/gutenberg/pull/34014#discussion_r687904062

@jorgefilipecosta, would you mind looking into it as well and confirming if our initial findings were correct?

>  Can you extend with the same plugin multiple times?

~~It looks like the [`extend` function supports an array of active plugins](https://github.com/omgovich/colord/blob/master/src/extend.ts), so that shouldn't be a problem.~~

Edit: I misread your question. That's actually a great question and something that we should look into — we may need to initialise the plugin in a separate function and maybe implement something similar to the singleton pattern to use the library

> Anyway, I don't care what you end up using eventually. I just wanted to raise some concerns I had. The call is on your side if it's worth an effort.

Your concerns are definitely relevant! Size is only one potential improvement that we'd enjoy when switching to `colord` — this library should in fact be also faster at runtime, and comes with first-party types (see [this benchmark](https://github.com/omgovich/colord#benchmarks))

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta, would you mind looking into it as well and confirming if our initial findings were correct?

Hi @ciampo,
I did not notice the color picker component was including a tinycolor object on the callback. I shared some thoughts on https://github.com/WordPress/gutenberg/pull/34014#discussion_r705432911. But in summary, I think we should not return that object, we never documented anywhere that we do it and even if there was no component library change I think we should do the change sooner rather than later. We should also remove oldHue and source from there, this should be internal information.

**Comment by jorgefilipecosta** [comment]
Hi @gziolo,

> How is it going to scale? Can you extend with the same plugin multiple times?


Yes one can extend with the same plugin multiple times
https://github.com/omgovich/colord/blob/9fe0e2b8c11ec2a6ed371137d52966f0a38dc890/src/extend.ts#L9-L16

If the plugin is already registered as an extension the call to extend does nothing.

So I guess the current approach scales and may work, but it is not ideal from the developer experience point of view it would be better to not have to call extend all the time. But I'm not sure how to do that I would appreciate any insights here.

**Comment by gziolo** [comment]
> So I guess the current approach scales and may work, but it is not ideal from the developer experience point of view it would be better to not have to call extend all the time. But I'm not sure how to do that I would appreciate any insights here.

Let's add those `extend` calls where necessary for now. We can abstract it later if necessary. In practice, this API prevents tree-shaking because the imported extensions are used in the code in `extend` call so tools will assume that they should be never removed even when they aren't used. It isn't an issue in Gutenberg, but it's a minor thing for 3rd party projects that want to use a subset of components from `@wordpress/components`.

**Comment by ciampo** [comment]
> We should also remove oldHue and source from there, this should be internal information.

I quickly looked into `oldHue`, and found [this comment](https://github.com/WordPress/gutenberg/blob/a7e2895829c16ecd77a5ba22d84f1dee1cfb0977/packages/components/src/color-picker/utils.js#L38), which may be worth investigating to make sure that this issue wouldn't be there in the new version of the component.

On the other hand, I couldn't find any usage of the `source` prop 👌 

The current legacy adapter already takes care of [marking those two properties as deprecated](https://github.com/WordPress/gutenberg/blob/4210f00c17206f7bd92c21637659aa7d3738109c/packages/components/src/ui/color-picker/use-deprecated-props.ts#L24-L40). Probably, to avoid introducing more breaking changes than necessary, the better option is to leave the code for the `oldHue` and `source` props as-is. We should leave these props marked as deprecated, while not mentioning them in official docs.

> I think we should not return that object, we never documented anywhere that we do it and even if there was no component library change I think we should do the change sooner rather than later.

Regarding the removal of the `color` property (which is a `tinycolor2` object), we need to first make sure that there are no usages in Gutenberg — from a quick search, I could find a couple of usages in [`packages/components/src/custom-gradient-bar/control-points.js`](https://github.com/WordPress/gutenberg/blob/288ab5d44e1e48f3ca24574eb791dcef5431b7ea/packages/components/src/custom-gradient-bar/control-points.js)

After that's done, we can remove the `color` property from the values returned in the [legacy adapter](https://github.com/WordPress/gutenberg/blob/4210f00c17206f7bd92c21637659aa7d3738109c/packages/components/src/ui/color-picker/use-deprecated-props.ts#L93-L115), and proceed to migrate from `tinycolor2` to `colord`

**Comment by jorgefilipecosta** [comment]
> I quickly looked into oldHue, and found this comment, which may be worth investigating to make sure that this issue wouldn't be there in the new version of the component.

Good point, I guess we may need to have an oldHue in the state to avoid the issue but we should not pass it on to the onChange it may be relevant internally for the component but is not relevant for users of the component.

**Comment by jorgefilipecosta** [comment]
> Regarding the removal of the color property (which is a tinycolor2 object), we need to first make sure that there are no usages in Gutenberg — from a quick search, I could find a couple of usages in packages/components/src/custom-gradient-bar/control-points.js

These should be taken care of when we remove tinycolor for the gradient-related components.

**Comment by ciampo** [comment]
> These should be taken care of when we remove tinycolor for the gradient-related components.

Absolutely — sorry if I didn't explain myself clearly!

Nonetheless, something to keep in mind — I assume that the refactor from `tinycolor2` to `colord` should apply to all components in the package (although of course it should happen in smaller steps across different PRs)
