### ISSUE TITLE
Components: apply design feedback to g2 `ColorPicker`

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#34285]
Part of #34284

## Why

The `ColorPicker` component has been recently added to the Gutenberg repository and needs to go through a few design tweaks

## What

Mostly design refinements that were missed in the first iteration working on the component

## A/C

- [ ] The white border on the circle controls looks too wide in the storybook compared to the design
- [ ] The input padding is off, not sure if this is something we need to affect on all inputs or we can just start with the input + slider case.
- [ ] spacing between slider and input is off
- [ ] use the new settings icon from wp/icons (requires #34288)
- [ ] the color format dropdown should be rendered without borders, - [ ] not sure how we want to handle this at the component level since it should be an optional thing used rarely
- [ ] the slider circular handle is too big compared to designs

**Comment by mtias** [comment]
Moving these directly to the tracking issue.
