### ISSUE TITLE
Components:  better "rail" vs "track" docs in `<RangeControl />`

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#34292]
## Why

The `RangeControl` component's README has an ["Anatomy" section](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/range-control#anatomy) which refers to the different elements that the component is made of.

This section is missing an entry about the "Rail" part. 

## What

Update the `RangeControl` README to add info about the "Rail" element:

- The rail represents the whole surface of the slider (from the min to the max value selectable by the user) (the part in blue in the screenshot)
- The track represents the part of the rail from the minimum value possible to the currently selected value (the part in red in the screenshot)

https://user-images.githubusercontent.com/1083581/130783266-da19bd9e-2b31-4900-a453-df51e6ac7e23.mp4

## A/C

- [ ] Add a "Rail" entry to the "Anatomy" section in the `RangeControl` component's README
- [ ] Update the "Track" entry
- [ ] Update the schematics

**Comment by kkoppenhaver** [comment]
@ciampo I've put together a PR for this over at https://github.com/WordPress/gutenberg/pull/44057. But I see the third item in your checklist is `Update the schematics` and I'm not sure if there's more to be done on this one or if the PR is ok as-is.

**Comment by ryanwelcher** [comment]
@ciampo @kkoppenhaver just wanted to nudge this to see if we can bring it across the finish line.

**Comment by ciampo** [comment]
Closing this issue as it was fixed by https://github.com/WordPress/gutenberg/pull/44057
