### ISSUE TITLE
Button Block: Adding close button on the link control toggle or allow to close it using Esc key

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/gutenberg#34307]
### Description

While I was testing for the [FSE Program testing,](https://make.wordpress.org/test/2021/08/11/fse-program-testing-call-9-handling-highered-headers/)  I noticed there was no way to close the Button link toggle using Keyboard. 

### Step-by-step reproduction instructions

1. Create a button and enter text link
2. Open the link control toggle by using Ctrl+K or ⌘+K 
3. Once the toggle opens, search a post or page in the search bar
4. Select a post or page using down arrow key
5. Click Tab, and Enter to submit

Once submitted, the link control toggle stays open, and keyboard focus loops within the toggle. 

I tried using the Esc key and the arrow keys but could not figure out a way to close the toggle. 

### Screenshots, screen recording, code snippet

![screenshot1](https://user-images.githubusercontent.com/30734209/130855290-c47f8d1b-cda4-4916-ba04-02f742e88c1e.jpg)

### Pre-checks

- [x] I have searched the existing issues.
- [x] I have tested with all plugins deactivated except Gutenberg.

**Comment by annezazu** [comment]
Great find - thank you for opening!
