### ISSUE TITLE
Allow filtering the alignment options of blocks via `theme.json`

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#34317]
Related https://github.com/WordPress/gutenberg/issues/34316

The align options of blocks can be filtered using the [block_type_metadata](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#block_type_metadata) filter. It'd be easier for themes if they could filter those options via `theme.json` as we do with other settings such as `units`.

**Comment by oandregal** [comment]
Ran this by Riad and this is the context I've gathered:

- themes now define `layout.contentWidth` and `layout.wideSize` which already control the visibility of the alignment controls
- float options (left, center, right) are unaffected by the existing layout (they are always visible if the block supports it)
- disabling alignment options per block can be confusing to users
- we have different layout options (flow, flex) and alignments are contextual to the particular layout

I'm not sure we want to do this yet.

**Comment by fabiankaegy** [comment]
From my perspective, the ability to filter the alignment options of blocks via theme.json would be a significant improvement. It currently is the primary thing the `blocks.registerBlockType` hook in JS gets used for. 

```js
function addWideAlignmentOptions(settings, name) {
	if (name !== 'namespace/block-name') {
		return settings;
	}

	return {
		...settings,
		attributes: {
			...settings.attributes,
			align: {
				'wide',
				'full'
			},
		},
	};
}

addFilter(
	'blocks.registerBlockType',
	'add-wide-alignment-options',
	addWideAlignmentOptions,
);
```

Not having to manually filter the options but instead having a more declarative way of achieving this would reduce a lot of code that by nature is modifying settings at a relatively low level in the block API.

**Comment by oandregal** [comment]
Closing this one and it hasn't seen any movement in +2 years.
