### ISSUE TITLE
editor.BlockEdit hook, error on replace block

### ISSUE THREAD

**Issue by TetsuyaXD** [WordPress/gutenberg#34321]
### Description

The following code uses the editor.BlockEdit hook to wrap every third paragraph block and attach a container for an ad placeholder.
```javascript
const { createHigherOrderComponent } = wp.compose;
const { withSelect } = wp.data;
const { addFilter } = wp.hooks;

const withAdWrapper = createHigherOrderComponent(BlockEdit => {

  function AdWrapper(props) {
    const {
      hasMaybeAds
    } = props;

    if (props.name !== 'core/paragraph' || !hasMaybeAds) {
      return (
        <div>
          <BlockEdit {...props} />
        </div>
      );
    }

    return (
      <div>
        <div className="ad_placeholder"></div>
        <BlockEdit {...props} />
      </div>
    );
  }

  return withSelect((select, ownProps) => {
    const { name } = ownProps;

    if (name !== 'core/paragraph') {
      return {
        hasMaybeAds: false
      };
    }

    const { getEditedPostAttribute } = select('core/editor');
    const { getBlocks } = select('core/block-editor');

    const { disable_advertisement } = getEditedPostAttribute('meta') || {};
    const paragraphBlocks = getBlocks().filter(block => block.name === 'core/paragraph');
    const index = paragraphBlocks.findIndex(block => block.clientId === ownProps.clientId);
    const hasMaybeAds = (index > -1 && index % 4 === 0) && !disable_advertisement;

    return {
      hasMaybeAds
    };
  })(AdWrapper);
}, 'withAdWrapper');

addFilter('editor.BlockEdit', 'adWrapper', withAdWrapper);
```
When, under certain conditions, replacing the paragraph block with any other type this error is produced:
<img width="351" alt="Bildschirmfoto 2021-08-26 um 10 44 36" src="https://user-images.githubusercontent.com/33517730/130931700-0de83a20-5f99-41a5-aac4-9161cc3a0e1c.png">

This doesn't seem to be related to the props received from or anything else in "withSelect". One could wrap blocks randomly (replace the condition `props.name !== 'core/paragraph' || !hasMaybeAds` with `Math.random() < 0.5`) and the same error would occur.

### Step-by-step reproduction instructions

Using the code above:

1. Create a new post
2. For the first paragraph do anything which replaces it with another block type, f.e.:
    * Paste a youtube-URL
    * Create a heading
        1. type "/heading"
        2. press enter (**works fine when clicking on the button above!**)
   

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/33517730/130930212-63584061-04e5-495a-92e4-db279d8a8d6e.mov

### Environment info

Occurring since WordPress version 5.8

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by jordesign** [comment]
Hi @TetsuyaXD - looping back to this older issue. Is it something you still see in place in WP6.3 ?

**Comment by jordesign** [comment]
With no further comments or movement on this, I will close the issue.

If it _is_ still a problem - a new issue can be opened with updated details on how to reproduce.
