### ISSUE TITLE
Iframe: Stylesheet was not properly added error

### ISSUE THREAD

**Issue by renatho** [WordPress/gutenberg#34333]
### Description

In the latest version of Gutenberg, I started receiving an error in the console. It was introduced here: https://github.com/WordPress/gutenberg/pull/31870/files#diff-ab17abd38e687edd56573694ae3017e105e96b319571c190e9d4705c1872bc9cR58

Basically, the error is happening every time I select a block that contains the iframe to the sidebar, and this block enqueues styles through the following hooks: `enqueue_block_assets` / `enqueue_block_editor_assets`.

Since it's something new and we need backward compatibility in plugins, I wonder if it should be just a deprecation warning instead of an error. Or is there any other approach we could use for older WP versions along with the new approach?

Also, if we have styles shared between different blocks, how could we do that? Should `editorStyle` and `style` support arrays?

### Step-by-step reproduction instructions

1. Add a hook (`enqueue_block_assets` or `enqueue_block_editor_assets`) to enqueue styles.
2. Go to the editor.
3. Open the browser console.
4. Select a block which contains styles (to have the iframe in the sidebar with the thumbnail for the different styles).

### Screenshots, screen recording, code snippet

<img width="943" alt="Screen Shot 2021-08-26 at 11 44 09" src="https://user-images.githubusercontent.com/876340/130984162-1ac12926-0817-4b71-a2a8-9a378bd417d0.png">

### Environment info

- WordPress 5.8 / Gutenberg 11.3.0 / Chrome or Firefox

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by CreativeDive** [comment]
I can confirm, I get the same error messages by using the "enqueue_block_editor_assets" action.

In my case I have global block styles, which are not block specific.

Why this error messages are added with the latest release?

**Comment by richtabor** [comment]
I've run into this as well.

**Comment by CreativeDive** [comment]
@bph is this issue only related to "Backwards Compatibility" and "CSS Styling"? For me it sounds like wrong error messages.

This error message are also fired by styles which are included by `admin_enqueue_scripts`. But this styles are only related to the admin screen, not block related. It seems there is something wrong with this block styles check.

And on the other hand, the block style check should not fire on styles which are included with `enqueue_block_editor_assets`, because this action is allowed to load block editor styles.

**Comment by ellatrix** [comment]
Is this still an issue after WP 6.3? For more info on styles in the iframe, see https://make.wordpress.org/core/2023/07/18/miscellaneous-editor-changes-in-wordpress-6-3/#post-editor-iframed.

**Comment by renatho** [comment]
Hi @ellatrix! I just checked it on a site with WP 6.3, and I couldn't see the error anymore. So I'm closing this issue.
Thank you!
