### ISSUE TITLE
Show transformations in the ellipsis menu

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3434]
## Issue Overview

We've recently added "convert to blocks" as an option to the block level ellipsis menu on the Classic Text block. This feels like a natural place for this, since it's an advanced transformation at the block level.

Should we show other transforms in this menu? This would be a pattern that we could reuse from the current "Switcher" interface. 

## Mockups

When selecting on a single block:

![single select transform](https://user-images.githubusercontent.com/1204802/32671156-b3b090c4-c646-11e7-91aa-833f4441f129.png)

When multiple blocks are selected:

![multi select transform](https://user-images.githubusercontent.com/1204802/32671161-b8b0661c-c646-11e7-85cd-4c74dbb37820.png)

In these mockups we show _the most obvious transformation directly_ (that would be gallery when selecting multiple images, or perhaps quote when selecting multiple text blocks), as well as a "Transform into" popout menu. 

Is this a good design? Is the popout menu too complex? Do we think it might be a scalable pattern to show all transformations directly in the menu?

Perhaps this issue could be tackled in phases, to test what works.

**Comment by StaggerLeee** [comment]
Looks very modern and nice. At least for me.

**Comment by hedgefield** [comment]
Yeah this makes sense! I think it would also solve the issue we found where people don't notice or recognize the block switcher in the toolbar (especially now that it has been moved to the top bar). Smart thinking to put them in a foldout menu also, the list might get quite long.

**Comment by youknowriad** [comment]
First, I'd like to say that I like this idea a lot. Moving the switcher to this menu. A small concern I have with this design is the double "popover". You need to open the foldout menu, hover (or click) the "Turn Into" button to show the transformations.

I'd be in favor of showing all the transformations in the foldout menu after the separator.

**Comment by jasmussen** [comment]
> I'd be in favor of showing all the transformations in the foldout menu after the separator.

I think that's fine, especially as a start. Then we can see what becomes necessary.

**Comment by karmatosed** [comment]
I really like this idea, to me it's the kind of magical nudge that takes the experience to one that really engages people. I like having after the separator also.

**Comment by rileybrook** [comment]
> In these mockups we show the most obvious transformation directly (that would be gallery when selecting multiple images, or perhaps quote when selecting multiple text blocks)

Could you envision the amount of rules being set for "most obvious transformation" in this situation becoming too long or complicated? That complexity could be reduced by leaving out "obvious transformation" and just showing all transformation options, as has been planned for these early stages.

**Comment by jasmussen** [comment]
> Could you envision the set of rules required for "most obvious transformation" becoming too complicated? That complexity could be reduced by leaving "most obvious transformation" out of the foldout menu and just showing all transformation options, as planned for these early stages.

I can come up with a couple of opinions, but you make a solid point: perhaps we don't want to be arbiters of which transformations are possible.

**Comment by jorgefilipecosta** [comment]
Regarding the "obvious transformations", I think our approach to making a test with no distinction between obvious and non-obvious is good, maybe we don't need this at all. But if we take the conclusion that we need this distinction, I think It should be up to the transform implementor to use a flag that sets that his transformation is important, the downside his every block developer want's to give relevance to his blocks so we may end up with many "obvious" transformations.
