### ISSUE TITLE
theme.json v2: track changes

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#34349]
Part of https://github.com/WordPress/gutenberg/issues/20331

This issue is to track the changes we need to introduce in WordPress 5.9, which we should match to a new schema for `theme.json`.

- Update version to 2.
- Consolidate the names that already landed and add migration from v1 to v2:
  - Rename `spacing.customMargin` to `spacing.margin`.
  - Rename `spacing.customPadding` to `spacing.padding`.
  - Rename `typography.customLineHeight` to `typography.lineHeight`.
- Add the new properties to `VALID_SETTINGS` and `VALID_STYLES`.
- https://github.com/WordPress/gutenberg/pull/34485

**Comment by oandregal** [comment]
In origin, we used the `custom*` prefix for things that had both a preset and custom colors added by the user. For example, `color.customGradient` means the users can't use the custom colors in gradients, they are limited to preset gradients. However, `color.link` means the users can't set link color.

We should remove the `custom*` prefix those properties that don't need it: `spacing.margin`, `spacing.padding`, `typography.lineHeight`.

**Comment by oandregal** [comment]
cc @mtias @youknowriad @mcsf @jorgefilipecosta @gziolo @aaronrobertshaw @ramonjd 

We can implement the migration from v1 to v2 for the properties above, as we did in the plugin when we introduced v1 ([see](https://github.com/WordPress/gutenberg/blob/trunk/lib/class-wp-theme-json-schema-v0.php)), so in `theme.json` you'd use the name without the `custom` prefix.

I wonder how this affects the "internal" names: ideally, the names of the properties in the `__experimentalFeatures` passed to the client can be also updated as well as the store. I understand this may require 3rd parties that hook into the block settings filter to update their filters, if they modify these values. Is this a reasonable request? I think it is, because a theme.json v2 could introduce shape changes anyway.

**Comment by mtias** [comment]
We should perhaps leave the renaming for when we stabilize and remove the `__experimental`.

**Comment by uniquesolution** [comment]
How about having multiple conditional theme.json files, so that one site can have multiple theme global styls for different pages conditionally? For example as we select page template is in page editor, how about having an option to also choose a different theme.json file ?

**Comment by mtias** [comment]
Multiple json files is indeed on the roadmap and conceptualized in the initial scope. The idea is it can be composed in a similar way to the theme hierarchy — so it can match a set of templates, or an individual page, etc. The idea is that template parts could also be theme.json providers, meaning you could overwrite or specify settings for ay template part in complex scenarios. Think a case where a sidebar might require a different set of color presets than the rest of the site.

Swapping theme.json files altogether will also be a good affordance for themes offering different schemes, etc. A dark theme could also be conceptualized under that model easily.

**Comment by uniquesolution** [comment]
Is this coming in Wordpress 5.9 ? Where we can see progress in this topic ? I would like see this particular topic progress and want to participate in suggestion if I find useful.

**Comment by oandregal** [comment]
PRs to remove the custom prefix from existing v1 settings at https://github.com/WordPress/gutenberg/pull/36154 and https://github.com/WordPress/gutenberg/pull/36155

**Comment by oandregal** [comment]
All tasks here have landed so I'm closing this. For reference, I'm porting the changes to WordPress core at https://github.com/WordPress/wordpress-develop/pull/1808
