### ISSUE TITLE
Proposal for naming distinction between template-parts and blocks

### ISSUE THREAD

**Issue by Humanify-nl** [WordPress/gutenberg#34366]
## What problem does this address?

With the upcoming full site editing, all the different block manipulations are going to become a handfull. The user experience may risk becoming somewhat fuzzy, because of the naming convention.

**What we have now:**
- Reusable (synced) block
- Block-style
- Block-variation
- Block-pattern
- Block-template (soon)
- Block-template-part (soon)

**What is unclear?**

When does it stop being a block and become a template part? Isn't everything a template-part? Isn't everything a block? What is the difference between a template part and a template block?

## What is your proposed solution?

**Proposal:**

I think there should be a naming convention that makes a clear distinction between 'block manipulations' and 'template parts'.

Something along these lines:

Blocks
- Block-style
- Block-variation
- Reusables

Template (full site editing)
- Template-block _(formerly block-template)_
- Template-block-part _(formerly block-template-part)_
- Template-block-pattern _(formerly block-pattern)_

**Reasoning:**

It being a 'block' is an abstract meaning; everything is a block, or a block with other blocks inside it. We should beware of naming everything a block+{...} because it becomes obtuse.

**For example:**

A _template-block_ has a clear meaning: it is a _block that is used in a template_. And a couple template blocks form a template. 

Yet, _block-template_ has a more fuzzy meaning: If i didnt know, I'd asssume from its name that it is a template for an individual block!

_Block-pattern_ is not as confusing, as its purpose is to make patterns (which aren't that dissimilar from template-parts). I would call it a template-block-pattern, but it is an edge case.

**Future**
I suppose eventually we will drop the whole block terminology as there will be no need to make distinctions between template-parts and block-template-parts.

**Comment by ramonjd** [comment]
The language around these entities has changed a great deal, especially with the introduction of patterns.

Block, style and theme variations are, in my opinion, still a contemporary example of possible confusion but I think it would be good to either edit this issue with current nomenclature or create a new one.

Going to close for now. 

Please reopen if you think it's still relevant. 

Thanks!

**Comment by Humanify-nl** [comment]
Hey! 

6.5 release has made big strides and I’m sure these things will get unified more without my input, thanks for notifying.
