### ISSUE TITLE
Full-width in reusable blocks

### ISSUE THREAD

**Issue by diegobroncano** [WordPress/gutenberg#34368]
### Description

Full-width blocks contain in a reusable block aren't seen as full-width blocks. It is expected to be seen as what is it, a full-width block.

### Step-by-step reproduction instructions

1. Create any full-width block (cover, group, image...)
2. Set block width as full-width.
3. Add the block to reusable blocks.

### Screenshots, screen recording, code snippet

![2021-08-30 01 07 26](https://user-images.githubusercontent.com/68561092/131268282-3babc347-fbc3-4d4e-b3a9-17071bb3a0c2.gif)

### Environment info

- WordPress 5.8, Gutenberg 11.3.0, Twenty Twenty-One 1.4
- Firefox and Chrome
- MacOS Desktop

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by talldan** [comment]
Thanks for reporting. There are some existing bug reports (https://github.com/WordPress/gutenberg/issues/8288 and https://github.com/WordPress/gutenberg/issues/17640), so I'll close this as a duplicate.
