### ISSUE TITLE
Post Navigation Link: Add typography settings

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#34381]
## What problem does this address?
Currently, the "Query Navigation Previous" and "Query Navigation Next" blocks (on the Index template) support the "Typography" settings dropdown in the right sidebar when you edit them, but the "Previous post" and "Next post" blocks (on the Single Post template) don't. Since these blocks are so similar, I think users might expect that they support the same typography settings.

## What is your proposed solution?
Add support for typography settings to the "Previous post" and "Next post" blocks. (On an unrelated note, shouldn't the p in the "post" part of the block names be capitalized?)

**Comment by mtias** [comment]
Broadly speaking all text-based blocks should have consistent and familiar tools, diverging only when explicitly stated.
