### ISSUE TITLE
Default line height is very tight

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#34397]
### Description

When a theme does not provide editor styles, the default line height appears very tight: 

<img width="1277" alt="Screen Shot 2021-08-30 at 4 05 44 PM" src="https://user-images.githubusercontent.com/1202812/131399380-bcd8830f-461c-4359-87a0-44609628005c.png">

This stems from the `reset` value here: 

<img width="249" alt="Screen Shot 2021-08-30 at 4 15 08 PM" src="https://user-images.githubusercontent.com/1202812/131399683-af2bca70-69fe-489d-90ca-11f7d8f3e69a.png">

If I remove that, it inherits the WP-Admin default of `1.5`, which looks a little nicer. `1.6` or so would be more comfortable, but I'm not sure exactly what our "reset" strategy is here... the resets are in place so as to not override theme-provided styles, but I imagine we're also aiming to provide some nice defaults for when themes don't provide any editor styles, right? Do we handle those defaults somewhere else?

Possibly related to https://github.com/WordPress/gutenberg/issues/31211

### Step-by-step reproduction instructions

1. Activate the Gutenberg plugin
2. Activate a theme that does not provide editor styles (I used [Isola](https://wordpress.org/themes/isola/)).
3. Edit a post.
4. Note the tight line height. 

### Environment info

Gutenberg 11.3.0

**Comment by kjellr** [comment]
cc @jasmussen when you're around — I feel like you have more knowledge of these resets than I do.

**Comment by jasmussen** [comment]
Hey, thanks for the ping. There's a bit of context in [this comment](https://github.com/WordPress/gutenberg/pull/34001#issuecomment-896646774):

> The intent of `serif` is to override the font that comes by default from `wp-admin` common styles and restore the browser default.
> and if I just checked WP core's code the default font is not added anymore unless the theme doesn't provide a `theme.json` file. So my question would be, what WP version are you testing with?

The comment seems to suggest that the system fonts are only output for classic themes. Which means we might be able to output a line-height there as well. But this would likely require a core patch to output that same line-height in context of the rule that outputs system fonts.

**Comment by kjellr** [comment]
Hmm ok. Core _does_ provide a default line height, but Gutenberg's `reset` styles override it. 😕 Presumably we'd need to have core provide a more specific rule?
