### ISSUE TITLE
Global Styles: Add the ability to set a background color for a specific post/page template

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#34390]
Global Styles currently lets you set the background color for specific blocks, or for the entire site globally. In addition to those controls, we should allow users to choose colors for individual post and page templates.

For example, someone might want their homepage to have a different background color than their blog posts.

_Related:_ https://github.com/WordPress/gutenberg/issues/27233

**Comment by mtias** [comment]
Let's consolidate in #27233 as it captures the essence of the proposal. A theme.json object corresponding to a specific post or page would just be the implicit `page-{id}` or `page-{slug}` template. Would you mind adding the comment there instead?
