### ISSUE TITLE
Code does not stick  after updating or posting<title>

### ISSUE THREAD

**Issue by lettyskitchen** [WordPress/gutenberg#34400]
### Description

I am unable to insert my Amazon ad custom code into a block. 
I’ve tried inserting using the html block but In Preview it gives an error--"This block contains unexpected or invalid content." Also, when I edit an older "classic" post and convert to blocks, the ad code icons show but when I update, there is just a gap in between Paragraph and recipe blocks in the live post.

<img width="1013" alt="Ad code visibility in small icons " src="https://user-images.githubusercontent.com/49080494/131416060-2465ff16-f28f-46cd-82c5-f0124cdd8d30.png">

Here’s a link to an older recipe post using the Classic editor plugin, a post that I didn’t convert to blocks as I edited. You can see the custom Native Shopping Ad just above the recipe. https://www.lettyskitchen.com/spicy-red-lentil-mushroom-pasta/ If I were to edit the post, the ad would dissapear forever. 

### Step-by-step reproduction instructions

I insert ad code using the html block.  In Preview it gives an error--"This block contains unexpected or invalid content."

Attached screenshot of the Native Shopping Ads code, the code I created in Amazon Associates and have tried to insert via HTML block.

You may surmise that I'm not a developer but a frustrated creator.
<img width="760" alt="Amazon Ad code I'm trying to insert" src="https://user-images.githubusercontent.com/49080494/131416979-1f4d31ed-e65c-4669-b320-6bdc6d6e3d38.png">

### Environment info

Using WP version 5.8 Custom theme.
Desktop Mac Big Sur latest update.

### Pre-checks

- [X] I have searched the existing issues.
- [ ] I have tested with all plugins deactivated except Gutenberg.

**Comment by annezazu** [comment]
Hey @lettyskitchen - so sorry for this frustrating experience! Since this is more of a support request than a technical issue with Gutenberg, I'm going to close this out for now. With that said, I highly recommend checking out the following article:

https://www.wpbeginner.com/wp-tutorials/how-to-add-amazon-ads-to-your-wordpress-site/

It should help you accomplish what you're looking for :)
