### ISSUE TITLE
Are Pullquotes in Gutenberg Duplicative Content? If so, move them to the data-attribute?

### ISSUE THREAD

**Issue by themightymo** [WordPress/gutenberg#3442]
First off, amaaazing work on Gutenberg.  It's fun to use, and I'm looking forward to the day when it's no longer in beta.

## Issue Overview
I'm the author of [Simple Pull Quote](https://wordpress.org/plugins/simple-pull-quote/), and one issue that people keep bringing to my attention is that pullquotes are more visual elements than traditional content elements.  

## Example of the Problem
If you are using a screen reader or reading via RSS feed, you probably don't want to read pull quotes as part of the content (they are duplicative and confusing - usually a partial sentence out of context). 

<img width="501" alt="duplicated" src="https://user-images.githubusercontent.com/179105/32698785-a429dab8-c770-11e7-8043-3f32a87c2a87.png">

## Possible Solution (Big Scope)
One solution people have brought up is to utilize the data-attribute element in html5.

Background:
* http://miekd.com/articles/pull-quotes-with-html5-and-css/
* https://qreativ.space/tutorials/html-5/pull-quote.html
* https://andytaylor.me/2012/12/03/pull-quotes/

I don't have enough background on all this to know whether or not the data-attribute element is the right place for pullquotes, but it does seem like a _better_ way to handle the data.  

Also, from the thinking I've done on the issue, the problem is not simple, especially within the context of a block-based editor like Gutenberg.  (Basically, I don't have a great ui solution, unfortunately...).

## Possible Solution For Accessibility & Screenreaders (Small Scope)
Is there a simple html way to ask screen readers to ignore content?  If so, we could add that to the html markup of pullquotes.
 

Anyway, just wanted to bring this up, as I'm curious if this has been discussed in relation to Gutenberg.

Thanks,
Toby

**Comment by youknowriad** [comment]
I personally don't see quotes/pull-quotes as duplicative content. I think it may defer per use-case. I think this might be a good option for a plugin: Provide a regular quote block and a "duplicative" quote block.
