### ISSUE TITLE
ESLint: disallow importing Enzyme for React testing

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#34437]
## Why

We should recommend using RTL instead of Enzyme for all new tests

## What

We should add a ESLint rule to help enforce that

## A/C

- [ ] Add new ESLint rule
- [ ] Disable rule in all existing files importing Enzyme

_Originally posted by @gziolo in https://github.com/WordPress/gutenberg/pull/34423#discussion_r700015058_

**Comment by tyxla** [comment]
We can actually close this, `enzyme` has been gone for almost 3 months since we removed it in #44494.
