### ISSUE TITLE
Add block inserter to navigation editor

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#34438]
## What problem does this address?
Bring the navigation editor more inline with other block editor, but adding the block inserter and undo / redo buttons to the top bar. 

The current state of top bars to compare. 

#### Post editor
<img width="411" alt="Screenshot 2021-08-30 at 23 24 31" src="https://user-images.githubusercontent.com/237508/131413861-b0311785-de6b-4678-a9e0-7c91e732e569.png">

#### Widget editor 
<img width="418" alt="Screenshot 2021-08-30 at 23 24 15" src="https://user-images.githubusercontent.com/237508/131413887-68965dd9-7d81-4ebd-981d-057df2c3df98.png">

#### Navigation editor
<img width="269" alt="Screenshot 2021-08-30 at 23 25 04" src="https://user-images.githubusercontent.com/237508/131413927-4d8029cb-8c24-43ca-b976-1242dd9866b3.png">

Original comment. https://github.com/WordPress/gutenberg/issues/31276#issuecomment-908747627

## What is your proposed solution?

Add block inserter to navigation editor

**Comment by draganescu** [comment]
Yes I think this is going to happen as part of the navigation block's evolution to a lighter experience as @mtias 's describes in #34041 👌🏻
