### ISSUE TITLE
Enhance block spacing gap config to also target the first block in a container

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#34441]
#33812 added a `blockGap` property to theme.json which enabled spacing blocks inside a container using a simpler set of rules:

```
[.container] > * + * {
	margin-top: var( --wp--style--block-gap );
	margin-bottom: 0;
}
```

In effect this simplifies margins to be _between blocks_ rather than both before and after, simplifying first-child/last-child rules and margin collapsing. 

However at the moment, the rule only targets n+1 blocks:

<img src="https://user-images.githubusercontent.com/1204802/131647155-dd976191-fbcc-44c2-829d-b8be62369136.gif">

A fix would be to also output the following rule:

```
[.container] > * {
	margin-top: 0;
	margin-bottom: 0;
};
```

That would ensure there are no default margins interfering with the first block in a stack.

**Comment by jasmussen** [comment]
CC: @youknowriad, just as a followup to https://github.com/WordPress/gutenberg/pull/33812#issuecomment-910103764.

**Comment by richtabor** [comment]
+1 — I noticed the same as I explored blockGap this morning.
