### ISSUE TITLE
Remove post-specific autosaving logic from core-data package

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#34450]
## What problem does this address?

This comment says it all:

https://github.com/WordPress/gutenberg/blob/35e16bbad16afb7209fb0e19b87d3a6f4108dd22/packages/core-data/src/actions.js#L425-L428

The autosaving logic [accounts for the majority of code in `saveEntityRecord`](https://github.com/WordPress/gutenberg/blob/796d25c34cdf26d1dd788eb174b18a1b282770d2/packages/core-data/src/actions.js#L424-L520). Evicting it to the server, or at least another Gutenberg package would make `core-data` more consistent and easier to reason about. It would also help with https://github.com/WordPress/gutenberg/issues/34449

[See also the related discussion about raw attributes](https://github.com/WordPress/gutenberg/pull/34388#issuecomment-909482357).

## What is your proposed solution?

At this point, none. I am merely creating an issue to create space for discussion.

**Comment by jordesign** [comment]
Hey @adamziel  - just checking if these items above mean _this_ one is now resolved? Or if it is something needs doing?

**Comment by jordesign** [comment]
With no further comments - I'll take this to be closed via https://github.com/WordPress/gutenberg/pull/34457
