### ISSUE TITLE
Show "group" and variations (Row, Stack) in multi-select toolbar

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#34461]
Let's surface the "group" action on the multi-select toolbar:

![image](https://user-images.githubusercontent.com/548849/131700652-f34e5dc8-5471-4cc0-9463-b9fe9a289b19.png)

It's a more common action to do when you multi-select and it's unnecessary buried:

![image](https://user-images.githubusercontent.com/548849/131700850-d1804788-663f-4c47-9c65-f6fa7d2ff5cd.png)

## To-do

* [x] https://github.com/WordPress/gutenberg/pull/39710
* [ ] Follow up with additional buttons for Row and Stack variations

**Comment by kjbenk** [comment]
@mtias Any thoughts about whether the other MenuItem of `Add to Reusable Blocks` should be moved as well? Does it make sense to move the `Group` MenuItem from that MenuGroup and add it to the top of the list? This would mean that `Add to Reusable Blocks` would be the only MenuItem in that group.

**Comment by kjbenk** [comment]
@mtias After looking into this some more, it seems like the `Group` menu item is added to the general `BlockSettingsMenuControls` slot (which developers can extend and add other items as desired). Would it be useful to move this button out of this menu group and into the main group (i.e. where Copy and Paste are)?

Also, it might be ideal if the `Group` button remained in the same relative location regardless of if multiple blocks were selected. I can see users getting confused if the `Group` item were to change location in the dropdown based on whether multiple blocks were selected.

**Comment by jiteshdhamaniya** [comment]
Created a PR https://github.com/WordPress/gutenberg/pull/37488 for this.

**Comment by jiteshdhamaniya** [comment]
> Created a PR #37488 for this.

I think I misunderstood and just moved up Group Menu in my PR.

@mtias in order to add it to multi-select toolbar, we need an icon, is there any existing icon we can use?

**Comment by mtias** [comment]
@jiteshdhamaniya Yes, the group icon can be used:

![image](https://user-images.githubusercontent.com/548849/146757519-132666d3-ade8-43c0-aa7a-c26c6f364841.png)

**Comment by jiteshdhamaniya** [comment]
> @jiteshdhamaniya Yes, the group icon can be used:
> 
> ![image](https://user-images.githubusercontent.com/548849/146757519-132666d3-ade8-43c0-aa7a-c26c6f364841.png)

alright, thanks. I will create a new PR.

**Comment by andrewserong** [comment]
Just closing this one out now as it was resolved by #34461 and https://github.com/WordPress/gutenberg/pull/39920
