### ISSUE TITLE
Feedback on using live preview with list view and sidebar open

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#34466]
## What problem does this address?

Currently, if both the List View and Sidebar are open, the live preview for changes to the Columns block aren't visible:

https://user-images.githubusercontent.com/26996883/131718236-3c4f8a94-5d1f-4c02-b846-ab5498824cdb.mp4

> Live Preview doesn’t work well while adjusting the column width when both the ‘ListView’ and right sidebar is active. Once closing either one of those the live preview works as expected.

I imagine this is true of other blocks too and is something we'll have to figure out how best to explore now that List View is a sidebar that folks might keep open. This came up as part of the [ninth call for testing with the FSE Outreach Program](https://make.wordpress.org/test/2021/08/11/fse-program-testing-call-9-handling-highered-headers/#comment-1922).

## What is your proposed solution?

If possible, would be great for live preview to work properly with both open :) If not, likely need to explore a way to guide users to close out items in order to properly manipulate content.

**Comment by karmatosed** [comment]
I think this is tricky but you are right @annezazu that at the core having live preview open with the sidebar seems the expected behaviour.

**Comment by jordesign** [comment]
I see this issue resolved in my testing on WP6.3 - Live preview when changing column size works even when sidebar and list view are open. I'll close it out as no longer reproducible,
