### ISSUE TITLE
Registering block with block.json not load translation

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#34478]
### Description

I have create a simple block using the command `npx @wordpress/create-block gutenpride` and I'm trying to load translations.

I have all string translated. The translation is correctly loaded and correctly set textdomain on block.json. However the translation are not loaded for the block.

This is the code I'm using.

```
function create_block_gutenpride_block_init() {
    load_plugin_textdomain( 'gutenpride', false, dirname( plugin_basename( __FILE__ ) ) . '/languages/' );

    register_block_type( __DIR__ );
    
    wp_set_script_translations( 'create-block-gutenpride', 'gutenpride' );

}

add_action( 'init', 'create_block_gutenpride_block_init' );
```

### Step-by-step reproduction instructions

1. create a block using `npx @wordpress/create-block gutenpride`
2. create translation using `wp i18n make-pot ./ languages/gutenpride.pot`
3. generate json with `wp i18n make-json gutenpride-it_IT.po --no-purge`

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by Tropicalista** [comment]
I found my answer here: https://wordpress.stackexchange.com/questions/394062/how-to-set-the-localization-for-a-gutenberg-block?noredirect=1#comment575990_394062

I think this should be added to documentation.

**Comment by mkaz** [comment]
I'm glad you found a solution, I've reopened it and labeled as documentation so we can capture it within the docs.

**Comment by Rahe** [comment]
Hello,

I have the bug too, with the exact same code.
The only way I've found to fix it is to change "file:build/index.js" for "./file:build/index.js" on the block.json.

Nicolas,

**Comment by gziolo** [comment]
> I found my answer here: https://wordpress.stackexchange.com/questions/394062/how-to-set-the-localization-for-a-gutenberg-block?noredirect=1#comment575990_394062

The code that handles translations for scripts registered with `block.json` is located in WordPress core:

https://github.com/WordPress/wordpress-develop/blob/6dc3ff47d2a699fa2191d54fc67d635364bd20ff/src/wp-includes/blocks.php#L115-L127

It feels like we could also patch the existing `register_block_script_handle` function to account for all the cases that are listed in the answer on StackExchange:

- detect whether JSON file was placed in the `languages` in the plugin folder
- removed the preceding `./` in the editor script path, i.e. `editorScript` becomes `file:build/index.js`, because otherwise, then WordPress would load the wrong file because of the different MD5 hash calculated

**Comment by gziolo** [comment]
We discussed this issue also on WordPress Slack (link requires registration at https://make.wordpress.org/chat):

https://wordpress.slack.com/archives/C02QB2JS7/p1641920214075100

There is a [Trac ticket](https://core.trac.wordpress.org/ticket/54797) created by @Rahe where I also left a comment on how we could improve handling in WordPress core to have a better developer experience.

> I'm glad you found a solution, I've reopened it and labeled as documentation so we can capture it within the docs.

It feels like we might be able to resolve this issue without the need for writing any custom code in the plugin or using a very specific format for the script paths.

**Comment by gziolo** [comment]
All the changes discussed are going to be applied directly in WordPress core so let's close this issue and continue in https://core.trac.wordpress.org/ticket/54797. All enhancements are planned for WordPress 6.0 release.
