### ISSUE TITLE
Theme.json slug containing a number has a hyphen added

### ISSUE THREAD

**Issue by brettsmason** [WordPress/gutenberg#34509]
### Description

I've been testing out `theme.json` to configure Gutenberg.
I'm using it in conjunction with Tailwind and am configuring Tailwind to use theme.json values, but want to use Tailwinds font size naming conventions, eg `text-xl`, `text-2xl` etc.

I've noticed if I include font sizes like this:

```
{
  "name": "XL",
  "slug": "xl",
  "size": "1.3rem"
},
{
  "name": "2XL",
  "slug": "2xl",
  "size": "1.5rem"
},
{
  "name": "3XL",
  "slug": "3xl",
  "size": "1.875rem"
},
{
  "name": "4XL",
  "slug": "4xl",
  "size": "2.25rem"
}
```

The css custom properties for 2xl, 3xl and 4xl are output like this (notice the hyphen after 2, 3 and 4):

```
--wp--preset--font-size--xl: 1.3rem;
--wp--preset--font-size--2-xl: 1.5rem;
--wp--preset--font-size--3-xl: 1.875rem;
--wp--preset--font-size--4-xl: 2.25rem;
```

I would of expected the variables to be:
```
--wp--preset--font-size--xl: 1.3rem;
--wp--preset--font-size--2xl: 1.5rem;
--wp--preset--font-size--3xl: 1.875rem;
--wp--preset--font-size--4xl: 2.25rem;
```

I'm referencing the custom property values in Tailwind classes and generating based off theme.json values, so its expecting them without an additional hyphen. 

Is this intended behaviour or a bug?

From investigating, its the result of the function `_wp_to_kebab_case`.

### Step-by-step reproduction instructions

1. Add the following to `settings.typography.fontSizes` within `theme.json`:
```
--wp--preset--font-size--xl: 1.3rem;
--wp--preset--font-size--2-xl: 1.5rem;
--wp--preset--font-size--3-xl: 1.875rem;
--wp--preset--font-size--4-xl: 2.25rem;
```

2. View the output custom properties as:
```
--wp--preset--font-size--xl: 1.3rem;
--wp--preset--font-size--2-xl: 1.5rem;
--wp--preset--font-size--3-xl: 1.875rem;
--wp--preset--font-size--4-xl: 2.25rem;
```

### Environment info

WordPress 5.8

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/31629 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
