### ISSUE TITLE
Navigation Block: Consider having the responsive option on by default

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#34511]
## What problem does this address?

This was brought up as [part of the ninth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/08/11/fse-program-testing-call-9-handling-highered-headers/#comment-1928):

> Almost seems like the responsive setting should be toggled ON by default. Not sure if we can leverage smarter defaults, but if it exists within a Header template part, it should be ON.

This seems worth exploring as the default state. 

## What is your proposed solution?

Enable the navigation block to have the responsive menu on by default :) Curious what you think @jasmussen as I imagine this has been thought about. I tried to look through both open and closed issues but couldn't find anything specifically related beyond the initial discussion including you wanting it to be on by default: https://github.com/WordPress/gutenberg/issues/22824#issuecomment-788916109

**Comment by jasmussen** [comment]
Thanks for creating this, yes, we definitely want this on by default. The reason it isn't yet, is that we wanted to make sure and work out any kinks in it first. But it's slowly stabilizing.

I do wonder if we want to address #33273 and #31957 first, though. What do you think, @vcanales? Happy to pair on all of this by the way!

**Comment by jasmussen** [comment]
CC: @vcanales Do you think it's time to look at this one? I think it could be!

**Comment by jasmussen** [comment]
Took a stab in #35917.
