### ISSUE TITLE
Navigation block's responsive modal can't be customized

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#34514]
## What problem does this address?

I'd like to be able to implement a design like the following, where the responsive menu doesn't take over the entire screen, and contains more than just links:

<img width="415" alt="Screen Shot 2021-09-02 at 3 36 14 PM" src="https://user-images.githubusercontent.com/484068/131924812-efd8e2fb-0f32-41ab-aab5-8239bbd8530a.png">

That doesn't seem possible right now, unless I resort to an ugly hack like filtering `render_block`.

For now I've turned off `Enable responsive menu`, and am building the open/close functionality myself. That's not too awful, but it'd be ideal if the contents could be customized without having to do that.

## What is your proposed solution?

Maybe support a `block-template-parts/responsive-navigation.html` template?

I'm open to other ideas as well.

**Comment by getdave** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/38201 where there is more discussion on the same topic.
