### ISSUE TITLE
Buttons: Support `gap` via theme.json

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#34527]
## What problem does this address?

#32366 adds a theme.json mechanism to provide a a `blockGap` value to space out items in a container. Spacing using gap has the benefit of letting you not worry about the first or last elements in a container, or complex nth-child margins in containers that wrap.

## What is your proposed solution?

As a next step, it would be nice to connect the block with theme.json, so that the block becomes a flex container with a custom gap value, such as this:

```
"core/buttons": {
	"spacing": {
		"blockGap": "2em"
	}
}
```

#33991 also provided a UI for the gap control, which would benefit here as well.

**Comment by andrewserong** [comment]
There's a PR in progress that will address this — #34546 (thanks for picking that up, @stacimc!)

**Comment by bradhogan** [comment]
This appears to be added now, but it's not working.  Whatever blockGap I define in my theme.json is ignored.

**Comment by andrewserong** [comment]
@bradley2083 there's a bit more context in https://github.com/WordPress/gutenberg/issues/39789, which is the current issue for tracking adding back in support for `blockGap` at the block level within `theme.json`. (There is a WIP PR to add the support in #39870)
