### ISSUE TITLE
theme.json styles are not loaded when previewing a FSE theme in the Customizer

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#34531]
### Description

If you have a non-FSE theme active, go to the Customizer, click the "Change" button next to the name of the active theme, and select a FSE theme to preview, the preview that gets loaded doesn't include any of the theme.json styles in the theme.

The preview does work if you have a FSE theme active (like Blockbase) and preview a different FSE theme (like TT1 Blocks), but not if your active theme is a non-FSE theme.

### Step-by-step reproduction instructions

1. Activate a non-FSE theme, like Twenty Twenty-One.
2. Go to the Customizer.
3. Next to the theme name, click the "Change" button and select a FSE theme, like TT1 Blocks.
4. The preview is loaded, but the theme.json styles are not output, resulting in the theme looking broken.

### Screenshots, screen recording, code snippet

<img width="2673" alt="image" src="https://user-images.githubusercontent.com/8181091/131969704-70422db6-fcd8-45d4-8ee8-f7f467e4d6e1.png">

### Environment info

WordPress 5.8, Gutenberg 11.4.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by oandregal** [comment]
Hey, I can repro.

Some info:

- The TwentyTwentyOne theme does load the `global-styles-inline-css` stylesheet. It does not have a `theme.json` but opts-in into link color, which needs the global stylesheet so we load it.
- I've pasted a `theme.json` in the folder of TwentyTwentyOne and I can confirm the global styles also work fine in this case.
- I've also tested switching from TwentyTwenty (no global stylesheet) to TwentTwentyOne (has global stylesheet) and works fine.

So, the global stylesheet is loaded fine in some situations. It appears to be somehow blocked for block-based themes in the customizer.

**Comment by oandregal** [comment]
I've got a fix at https://github.com/WordPress/gutenberg/pull/34540

**Comment by oandregal** [comment]
Meta trac ticket that may be related https://meta.trac.wordpress.org/ticket/5818#comment:4 (previews for themes with theme.json not working consistently in the theme directory)

**Comment by oandregal** [comment]
I've landed https://github.com/WordPress/gutenberg/pull/34704 a few days ago that was also relevant to this. https://github.com/WordPress/gutenberg/pull/34540 is still necessary.
