### ISSUE TITLE
Create Block: Allow specifying templates to a local directory

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#34547]
## What problem does this address?

The create block script supports external templates but only those hosted on NPM. It would make it more flexible to test specifying templates from a local directory. This also would help when creating an NPM package of templates for testing without having to publish every change.

## What is your proposed solution?

Add an option to detect if a local directory is specified and use that as a source for a template.
For example:

```
npx @wordpress/create-block --template ./local-directory
```

**Comment by gziolo** [comment]
I’m sure it works with local npm packages in the monorepo setup like Gutenberg. I have never tested it with local folders, but it should be only a few lines of code if necessary. The line that loads local template:

https://github.com/WordPress/gutenberg/blob/389a1cc273d629a089f4d28fb40eb39f6be371c5/packages/create-block/lib/templates.js#L127

**Comment by mkaz** [comment]
I did try getting it to work with local npm package, but the issue I ran into is that it calls `npm view ${templateName}` to check if the package exists. The `npm view` command only checks against the npm registry, so not local.

It will be relatively easy to code up to make flexible, but will just need some updates

**Comment by gziolo** [comment]
Closed with #35645.
