### ISSUE TITLE
[Document]  Update correct syntax for for prettier-config in README.md

### ISSUE THREAD

**Issue by khoipro** [WordPress/gutenberg#34555]
## What problem does this address?
Try to install npm "@wordpress/prettier-config" from a document: https://github.com/WordPress/gutenberg/blob/trunk/packages/prettier-config/README.md

## What is your proposed solution?

Alternatively, add this to `.prettierrc` file:

```
extends @wordpress/prettier-config
```

I believe correct syntax must be:

```
extends: ['@wordpress/prettier-config']
```

**Comment by MukulKolpe** [comment]
Hey @khoipro, can I work on this issue?

**Comment by Mamaduka** [comment]
Hello, @MukulKolpe

PR for this issue would be much appreciated.
