### ISSUE TITLE
Remove redundant calls to widget-type endpoint

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#34551]
### Description

In the widget edit screen, there are many calls to the widget-type endpoint. Each widget that loads, hits the widget type endpoint to get it's type. However, this is not needed, as when widgets are requests, the api call that is made looks like this 

/wp-json/wp/v2/widgets?context=edit&per_page=100&_embed=about&_locale=user

<img width="535" alt="Screenshot 2021-09-04 at 15 54 49" src="https://user-images.githubusercontent.com/237508/132098761-fd0de49e-c99e-4555-ae00-453dfaa46b18.png">

As you can see, the widget type is already embed in this request, meaning that no other API request is needed to load this data. 

### Step-by-step reproduction instructions

1. Create a number of legacy widgets. 
2. Go to new widget screen.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/237508/132098512-fcc2f53a-5bc8-4caf-ae10-846e90fa818b.mov

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by noisysocks** [comment]
The calls are being made to `/widget-types/:id/encode` which is an RPC-style endpoint that turns the widget's HTML form data into a serialised instance string needed for previewing. I don't believe we can embed that response into `/widgets` as it relies on using `FormData` in the browser to serialise the form.
