### ISSUE TITLE
Stuck in select block mode when selecting text inside a block which is wrapped in a group

### ISSUE THREAD

**Issue by passatgt** [WordPress/gutenberg#34552]
### Description

If you have a block that has editable text which you are currently typing and you are trying to select the text with holding down shift and clicking on it, it will instead select the whole block and it will be stuck in this state until you refresh the page, preventing you to edit the text. Happens only if the block in question is wrapped in a group. More clear on a video i guess...  

### Step-by-step reproduction instructions

1. Create a simple block that has text, like a paragraph
2. Enter some text in this block and wrap it in a group
3. Hold down Shift and click on a word to select the text
4. Instead of selecting the text, the block that you clicked on will be selected
5. The block selection state is stuck, anywhere else you click, it will select the block, but you won't be able to edit the text until refresh

### Screenshots, screen recording, code snippet

![recording 2021-09-04 17_45_19](https://user-images.githubusercontent.com/43415/132100320-59d2f3e8-76c0-4273-827d-4a1866e4934c.gif)

### Environment info

- WordPress 5.8
- Default TwentyTwenty theme
- macOS Big Sur 11.5.2 with Safari 14.1.2 & Chrome 92.0.4515.159

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by them-es** [comment]
Confirmed. But this issue can be closed as it already has been reported here https://github.com/WordPress/gutenberg/issues/33665
