### ISSUE TITLE
14.1.1 breaks page/posts title in the back end (front end remains fine)

### ISSUE THREAD

**Issue by ManniGH** [WordPress/gutenberg#34554]
### Description

Hi there,

This is just to report a bug/incompatibility in the latest version.

When I install 11.4.1, it breaks the title of every single page or post in the back end (only, the front end is fine).

In the admin panel, when editing a page/post:
- The font for the title is huge
- The margins for the title are very narrow
- The title always shows in bold, even when it should show in pale grey because it's hidden
- The rest of the page is fine

I'm using Astra Pro (latest) with Ultimate Gutenberg add-ons and Editor Plus in case it matters.

Reverting to 11.4.0 resolves the issue.

Thanks for resolving this and keep up the good work!

### Step-by-step reproduction instructions

To reproduce, I only have to install 14.1.1 and check a page/post title. They are all broken in the back end.
To fix, I simply have to reinstall 14.1.0

### Environment info

WP 5.8, Gutenberg 14.1.1 (only), Astra latest
Chrome for desktop
Windows 10 Pro x64 21H2.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
@ManniGH, are you able to add some screenshots of what you are seeing, a comparison of the 14.1.0 versus 14.1.1 would be helpful if possible

**Comment by ManniGH** [comment]
Hi Glen,

Sure, here are two screenshots.

Here is one after creating a new page with 14.1.1 (the issue is there with all existing pages and posts, I just thought I'd create a new one so you can see it's not because of any existing content). 

![1  Gutemberg test page with 14 1 1 (incorrect title formatting)](https://user-images.githubusercontent.com/14205865/132308503-73888541-7ab7-49dd-ac07-69c38537f3d9.JPG)

Here is a screenshot of the same page after reverting to 14.1.0.

![2  Gutemberg test page with 14 1 0 (correct)](https://user-images.githubusercontent.com/14205865/132308561-9eb5e5e3-dde0-4f8c-8d10-9ca1c899e36a.JPG)

Hope this helps!

**Comment by glendaviesnz** [comment]
@ellatrix it looks like this might be related to https://github.com/WordPress/gutenberg/pull/34489. Before this PR on TwentyTwenty the post title looks like:

<img width="1234" alt="before" src="https://user-images.githubusercontent.com/3629020/132432525-d54eb463-07fc-491e-b6b2-6209a84f5c47.png">

and after the PR:

<img width="1248" alt="after" src="https://user-images.githubusercontent.com/3629020/132432578-6f250a97-6349-4033-90eb-b35aef7ff92c.png">

was this change in the title width intentional?

**Comment by ManniGH** [comment]
Not @Ellatrix, but if the change in the width title is intentional after the PR, it doesn't work with all themes. With Astra, half my titles are unreadable in the editor because of this, it looks like trying to display them on a small mobile phone. There isn't even enough width to show some short words fully (see "page" in my first screenshot). Please revert to using full width as previously. Centering is not a problem, even though personally I don't like it, because not all titles are centered. It would be great to make these kinds of changes optional. I'm not sure why one's preference should become everyone's only choice.

Also 14.1.1 doesn't take into account when a title is disabled by the theme on a page/post in the editor so that it doesn't show on the front end. The title always shows in bold in 14.1.1, when until 14.1.0 a disabled title always showed in pale grey, so we could see the page/post title in the editor but we knew it was disabled and wouldn't show on the front end. This also needs to be fixed. Please look at my screenshots to see the difference. 14.1.0 shows it as it should be (and as it's always been), 14.1.1 wrecks it.

**Comment by glendaviesnz** [comment]
@ManniGH on looking into this further it seems that this is a [known breaking change](https://github.com/WordPress/gutenberg/pull/34489#issuecomment-912312107) that theme authors will need to account for. The best approach is probably to contact the Astra theme authors and see if they can release an update that accounts for this change. If you point them to https://github.com/WordPress/gutenberg/pull/34489 that should give them the context they need.

**Comment by ManniGH** [comment]
Thank you for your help, I've reported this to Astra just now, with a link to this thread so they can see the issue on my screenshots and a quote of your last post so they can look at #34489.

**Comment by glendaviesnz** [comment]
@ManniGH, I am going to close this issue for now, but feel free to re-open it if the Astra team have any trouble resolving this problem for you.
