### ISSUE TITLE
Improve notices location

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3457]
Right now notices appear like this:

![2017-11-13 at 14 22](https://user-images.githubusercontent.com/253067/32730210-4189175c-c87e-11e7-9ce9-dac5667f6f33.png)

In testing this is being seen as easy to miss. So, what can we do about it? Let me give a few options and we can work out where we go from here.

There are 3 basic positions that could be used:

Current position:

![position1](https://user-images.githubusercontent.com/253067/32730297-8573a766-c87e-11e7-8a05-8996ff2ff7c4.png)

Top position:

![position2](https://user-images.githubusercontent.com/253067/32730315-98e0a5ba-c87e-11e7-9539-452ab33e8ba9.png)

Fuller current (making it 700 or 800 px wide):

![position3](https://user-images.githubusercontent.com/253067/32730324-9f5f6fca-c87e-11e7-87be-8bc2ae400afd.png)

## 1. Variable placing, desktop top.

This position puts the desktop at the top but on mobile varies.

![top1](https://user-images.githubusercontent.com/253067/32731172-0c2c1548-c881-11e7-8ea7-04749c83b88a.png)

![top2](https://user-images.githubusercontent.com/253067/32731181-1140c6be-c881-11e7-82f6-a777486398a9.png)

Mobile looks like this:

![mobile1](https://user-images.githubusercontent.com/253067/32731260-41ad63ca-c881-11e7-8791-7ab549078ba7.png)

The positive aspect of this placing is it goes with the visual focus area. However, it can lead to a cluttered visual experience. The messages do not appear that often though. It's worth adding in that to deciding on a solution.

What does a longer message/translation look like?

![top3](https://user-images.githubusercontent.com/253067/32731197-1c4fb560-c881-11e7-88d6-1e93700804db.png)

That's not great, but we can iterate on this and we should work out how many messages would get this long.

## 2. Alternative just make the notice look less 'stuck on'
The issue right now is that the notice is incredibly subtle. What about making it wider and having it a little larger?

![var1](https://user-images.githubusercontent.com/253067/32731389-96cd900a-c881-11e7-9b81-bb6b8bb777aa.png)

Either option could work so interested in opinions.

**Comment by youknowriad** [comment]
What if we make the second option full-width? Do you think, this could work.

Also, the current notifications API allows for multiple notices to be shown at the same time. I don't think we have this use-case right now in the code.

**Comment by karmatosed** [comment]
@youknowriad, the reason I didn't make it full width was because I was unsure if we wanted the 'i' to be able to be open same time as messages. If we don't, then totally.

**Comment by hedgefield** [comment]
I'm with @youknowriad, 2 full-width seems like a great option.

**Comment by melchoyce** [comment]
Position 3 feels most scalable to me.

**Comment by karmatosed** [comment]
Next round of mocks then based on the feedback.

![messages](https://user-images.githubusercontent.com/253067/33239963-821a2ae6-d2a5-11e7-8f45-68c9d72ca435.png)

And on mobile:

![messages-mobile](https://user-images.githubusercontent.com/253067/33239964-886f47dc-d2a5-11e7-97ed-ebe5531c2d94.png)
