### ISSUE TITLE
Entire block's content deleted on single backspace in Vivaldi when the plugin is active

### ISSUE THREAD

**Issue by harbran** [WordPress/gutenberg#34571]
Same issue as #13979 (Firefox), this time when using Vivaldi Browser (Linux).
Using Chrome or Firefox works fine.
Regards
Harald Brandstetter

**Comment by bph** [comment]
@harbran I used the #13979 set of test instructions, 

1. Go to A New Post with the Gutenberg Editor
2. Begin typing anything into the empty block
3. Hit backspace
4. Entire block's content deleted.

And I wasn't able to reproduce any content deletion on single backspace with this configuration: 

- Vivaldi browser (4.1.2369.21 ) 
- on a Mac 10.15.7. 
- using the Gutenberg plugin version 11.4.1 and 
- WordPress 5.8 

It really would help if you could be more specific as to the steps on how to reproduce the occurrence. And add, as requested, browser make and version, OS (which Linux distribution and version) as well as Gutenberg plugin and WordPress versions.

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @harbran hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
