### ISSUE TITLE
Improve RangeControl with placeholder attribute

### ISSUE THREAD

**Issue by NenadObradovic** [WordPress/gutenberg#34577]
Hello guys,

Could you please consider improving the RangeControl component with a placeholder option as we have in TextControl? 

The placeholder can appear inside the input[type="number"] field.

Best regards,
Nenad

**Comment by bph** [comment]
Hi Nenad, 
What would be the benefit of the feature? Do you have an example on how this could look? 
Maybe you can elaborate some more.

**Comment by NenadObradovic** [comment]
Hello bph,

Please watch this video example https://www.screencast.com/t/GcjzqXaKL

I created an Advanced range component that contains a screen switcher to easily change some option values between devices. 

If you have a similar case, it will be a good feature to allow users to know at any time what the initial value of that option is, when they testing site responsive. ( In order to adjust option values for better responsiveness layout. )

Best regards,
Nenad

**Comment by NenadObradovic** [comment]
I forgot, it can be the default placeholder attribute for HTML element https://www.screencast.com/t/lLHu6m2IA

**Comment by bph** [comment]
@NenadObradovic,  looking at the [component Readme](https://github.com/WordPress/gutenberg/blob/14624ba070c9a7a9b18fddb22ba9b88a9ca304e8/packages/components/src/range-control/README.md), I discovered that there is already an implementation for the input field so a user can add the numbers. 

See this video from the Group block implementation

https://user-images.githubusercontent.com/39980/132242399-76e4a6db-18e6-472a-8f42-9c7cf1293fb5.mp4

Do you think that matches your use case?

**Comment by nenad** [comment]
@bph Wrong Nenad 😄 @NenadObradovic is who you need.

**Comment by NenadObradovic** [comment]
Hello @bph ,

Yup, that's right but we misunderstanding :/

At this moment if you add the RangeControl component you can set the input field next to rails and you can also set a default value, that value will show inside the input field.

But that's not what I need, my idea is that there is a **placeholder** value for the input field not **value**

Imagine you have 3 options one below the other, where each option changes the value of the same element depending on which device it is displayed on. https://www.screencast.com/t/8Hd3e2GHhrYE

For example, the purpose of the placeholder can be if you set 34 as value for the Desktop option, to set that placeholder value 34 for other options. https://www.screencast.com/t/rofS3ZwabkAM 

The Elementor page builder also implemented the same functionality in the latest version for their input fields https://www.screencast.com/t/Kza9fA3IH2DT

To be clear, I don't need a mechanism to automatically pick the value from some option and to set it as a placeholder for another one, I just need the possibility to set a placeholder value for the RangeOption component so you can be able to set whatever you want there.

Thanks for your time :)

Best regards,
Nenad

**Comment by bph** [comment]
@NenadObradovic  Here is the storyboard of the [RangeControl component](https://wordpress.github.io/gutenberg/?path=/story/components-rangecontrol--default) You can set the initial value or not and the user can type in a number, within in the predetermined min and max values.  This should do what you need. Give it a shot. I close this issue for now. We can open it up again. If it doesn't do what you need.
