### ISSUE TITLE
Show "none" as an alignment option and use contextual text to clarify settings.

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#34597]
Updates the design of the alignment dropdown to include "none" as an option (it's the same as unsetting). The center icon has been updated, and the previous icon for centering has been repurposed for indicating "None". There's help text for "None" and "Wide", to show the values for the content and wide area layout values.

<div align="center"><img width="444" alt="Group 259" src="https://user-images.githubusercontent.com/1204802/132249337-49089891-a9d2-44c8-bd1c-db923a8fb031.png"></div>

For themes that do not support wide or fullwide alignments we render some contextual text to clarify the missing buttons:

<div align="center"><img width="444" alt="Group 260" src="https://user-images.githubusercontent.com/1204802/132249552-d45aafa8-dc32-4b80-8e6f-985cbb98c7bf.png"></div>

**Comment by richtabor** [comment]
May be overthought, but perhaps there's a way to dismiss (_localStorage_) the "Your theme doesn't support.." notice so that it brings awareness, but doesn't convey the theme being sub-par every time you see this?

**Comment by mtias** [comment]
Perhaps we can reword it so that it's less of a "doesn't support" and more of a choice? We could use the same wording as on containers that don't have wide / full for various reasons, like columns or there being a sidebar.
