### ISSUE TITLE
When changing a slug offer options to update internal incoming links

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#34599]
# Problem Scope
- I outlined the overall problems I see with link management and link healing in Wordpress in this [core feature request](https://core.trac.wordpress.org/ticket/54024).
- 10 days passed, I researched & tested a lot, got feedback from you the Wordpress community!  Conclusion:
  - 👍 All issues outlined in that feature request can be solved with plugins, see next section.
  - ❌ Except for intercepting a slug-change during the event of saving a page.
  The very root cause, and the scope of this ticket!

# Problems when the slug changes, which covered, which not
- Plugin [Redirection](https://wordpress.org/plugins/redirection/)
  - Takes care on the transport level (HTTP)
  - ✅ It adds proper old-slug --> new-slug redirections
  - ✅ SEO juice is preserved
  - ✅ External links arrive well
  - ❌ But still your website contains outdated internal links where a redirect occurs each time, so only the symptom is taken care of (HTTP) but not the cause (outdated links in your website's HTML markup)
- Plugin [Broken Link Checker](https://wordpress.org/plugins/broken-link-checker/)
  - ✅ Really fixes the cause (the broken links in the HTML markup)
  - ✅ Does this with an initial job + recurring jobs (cronjob)
  - ❌ But has no event-based handling.
  - ❌ Has no functionality to also update link-texts (everything between `<a>` and `</a>`) automatically!
- The events which could trigger a link-healing
  - **When changing the slug of a page** --> heal the incoming links (scope of this ticket).
    - If your website starts with this feature being active, and you only ever change slugs via Editor, this alone is enough to never have broken internal links! But for legacy and exceptions we also need the other methods as an addition.
  - **When changing the page hierarchy** (moving pages around) or renaming a page which has children which hence affect their URL
    - Again the root cause is not fixed. But redirection (with the fuzzy logic) mostly works.
  - **Wordpress gets a request for an outdated-slug** for which it cannot find a resource (404)
    - It comes from an internal link (referrer URL from same domain)
    - WP looks into the origin URL, parses the markup for href=outdated-slug and if it finds the redundant fallback attributes data-type and data-id and they still point to a valid resource, redirects there temporarily (302 or semantically better 307) to serve the requestor quickly, and puts the outdated-slug into a processing queue for link-healing. This later looks for outdated-slug links in your entire website, heals the links in the markup and creates permanent redirects (301).

# Why in Gutenberg?
- All other issues are already handled by plugins. I cut out this very particular feature and propose to tackle it in Gutenberg, for these reasons: 
  - Any SAVE event which requires the possibility for per-incident-choice requires a UI. Hence the Editor is the right place for this.
  - Gutenberg is the prime choice, as it is now the default Editor.
  - (If desired, could be backported to Classic later)

# UX design proposal

https://user-images.githubusercontent.com/737143/212436784-744345d5-e389-448b-8e85-6715a17cd001.mp4

### Rationales behind the design
- You can set preferences (in core and the respective plugins)
  - and per-incidence you can change them if needed.
- Why not a popup after clicking save?
  - Pro: Likely easier to implement
  - Pro: Easy integration into other editors, like Classic
  - Con: All cons a modal brings! Very disruptive. Loss of context. Not in the spirit of Gutenberg.
  - Therefore in the Inspector only as a lightweight disruption "I have seen it and chosen a resolution, which I may also change to a dangerous setting, if I want/need to".
- Why hook into slug-change and not title-change?
  - In Gutenberg changing the title is not enforcing a slug-change. That's a good design decision!
  - If the user changes the slug, then it must already be a stronger reason.
    - And then caretaking for updating all incoming internal links's href-attribute and maybe also link text (=text between `<a>` and `</a>`) is very justified!
    - Because a link text promising the old title and then you get the new title is dis-orienting! (UX basics on navigation)

**Comment by porg** [comment]
Could someone please give the requested Technical Feedback?

**Comment by porg** [comment]
Hi @critterverse,
- as Design Director for Wordpress, maybe you are the right one to look into this, and get this thing going:
- Links are a core functionality of the web.
- Features to maintain healthy links should be a core functionality of a CMS.
- I took quite the effort back then to research and compile this issue together and to create the UX design for how this use case could potentially work. (mockup screen series attached) 
- Would appreciate a reaction. Thanks!

**Comment by porg** [comment]
@critterverse 
- this issue here from 2021-09-06 would be the end user's feature.
- I had also created a corresponding issue for "core" on 2021-08-27 which would/could serve as the technical foundation:
[Internal links with href=outdated-slug and a data-type data-id as fallback should use that and update href=new-slug instead of resulting in broken link (404)](https://core.trac.wordpress.org/ticket/54024)
  - That core issue only got a classification "Component: Editor" by @SergeyBiryukov and nothing more since then.
- A slug-change is a realistic use case and the user goal to then not needing to fix all incoming internal links manually is obvious and not too much asked, IMHO.
  - A somehow realistic expectation from a CMS.
  - E.g. the Atlassian Confluence Wiki points links to both numeric-ID and slug, and in case you change the slug all incoming links in the markup of the source pages are fixed to point to the new slug (due to all links pointing both by ID and slug).
- Currently in Wordpress: Broken incoming internal links due to a slug change need to be manually fixed or fixed by help of plugins.
  - To make that situation even less UX friendly: You need to use two different kind of plugins! One to fix broken HTML links in the markup. And one to create HTTP redirects.
  - Instead of cleverly tackling the root cause of the problem -- the slug change in the page editor (now by default Gutenberg) -- and intercepting and fixing the problem right there!
- I'd appreciate a reaction.

**Comment by porg** [comment]
- Transformed the user story into a video for better consumption.
  - Because Github offers no lightbox to click through an image series.
  - So just pause the video and go back / forth to the slide you need.
- Hope this will get some attention.

**Comment by porg** [comment]
Dear @jeffgolenski @mtias @jameskoster — From my research you are the senior people involved in UX design and architecture of Gutenberg at Automattic, and I hope to reach my intended audience with this comment.
- Please tell me whether you consider my proposal to be in scope for Gutenberg or not and why. Thanks!
  - **Fact**: The Gutenberg Site Editor offers to change the slug in its Inspector panel.
  - **Use Case**: User changes the slug.
  - **Desired reaction/assistance**: Gutenberg offers integrated options to fix incoming links, especially for those in the markup of internal pages/posts.
- Creating and repairing links to me is a core function of a CMS.
  - WordPress so far was rather reluctant on the repairing aspect and did not handle this in Core.
  - But left this up to various plugins, which fixed this in various degrees, but none of those fixes the root cause (outdated links in markup), see my analysis in the ticket description.
- Do you think it is about to change that and put "Link Fixing" on the roadmap for Gutenberg?

**Comment by jasmussen** [comment]
Hey, thanks for the detailed issue. I'm mainly involved in the design sense on the project, so I can speak mostly at a high level. 

My first instinct when reading this issue was that it seems to be potentially larger than just the Gutenberg editor itself, indeed being relevant to the content stored in the database. If I'm not misreading you, what you'd like to see is that any links to a particular post get updated once that particular post has its slug updated. But presumably you'd like to see this happen also in case the URL scheme gets updated (i.e. if you used `?p=ID` URL format and updated to one of the `.htaccess` powered URL schemas). 

I'd love to see that too, but it's also likely to be a big technical challenge to get such a database search and replace right without data loss. Furthermore, I have a feeling this conversation must've been had for updating slugs in WordPress before. It might even be a conversation like this that led to the creation of the redirect system, where past URLs always redirect to the newer URLs automatically. (I.e. if you changed `slug-a` to `slug-b`, WordPress will know to redirect the former to the latter in perpeuity). 

It may be best to ask about this feature on the WordPress core trac, so that the potential history can get properly surfaced. What do you think? https://core.trac.wordpress.org/

**Comment by mtias** [comment]
This is not easy to implement for inline links in serialized content, which is how WP works for general user content. The ability to treat links as dynamic sources is contingent on something like https://github.com/WordPress/gutenberg/discussions/39831 

WordPress will update any dynamic links already that are stored as ids or other general references. It doesn't know how to update user content in rich text fields, though. Feel free to include this potential use case in the above discussion thread to consider. It's not currently something actionable from just the Gutenberg side of things.

**Comment by porg** [comment]
I had put a lot of research and UX design effort into this.

@mtias Please help to explain something to me which I have troubles to understand, e.g. this statement:

> not easy to implement for inline links in serialized content

E.g. in the markup of https://example.com/work/ there's a link to https://example.com/work/event-equipment-management/ in this form:

    <p><a href="https://example.com/work/event-equipment-management/" data-type="page" data-id="1570">Event &amp; Equipment Management</a></p>
    
1. There is certainly no problem to identify without doubt incoming links:
- Especially if they have additional backup/redundancy attributes like data-type data-id, shown in the sample above.
- 3rd party page builders or blocks possibly create links with `href` only, which should still be enough for unique identification (URL as in "**unique** resource locator")
- If the page with the `id 1570` and the `slug "/event-equipment-management/"` changes its slug, then a loop could go through all serialized content (aka page markup) and find the incoming link instances by `href` and/or `data-id` without doubt and adapt the `href` value to the new slug and optionally also the link text between `<a> and </a>` as proposed.

2. Or is this a performance problem predominantly?
- Too slow fo perform in real world websites?
- That for this WordPress would need database structures which provide all the interlinking information necessary for quick backlink identification (and correction)?
- Is this what's currently not available? And what's the quintessence of your linked proposal?

**Comment by mtias** [comment]
Performance and data integrity. To ensure server rendered content has the correct and updated link (a requirement) your example would need to be parsed server-side and the href updated accordingly. Doing that across the database can be expensive and error prone without easy ways to recover from should something go badly. Doing it at runtime — treating all inline links as dynamic — for all possible links is more realistic but can also be challenging to extract cleanly and inexpensively across a large variety of hosts. Furthermore, relying on inline IDs can be problematic when generating an export, and would need to be handled across all possible sources of inline content. All in all, it's a complicated problem with many pieces to the puzzle to do reliably and do it well at the scale expected.

The discussion above is about defining a reliable way to treat inline serialized content as dynamic content, but it's still early and speculative.

**Comment by sovetski** [comment]
Hi, any update on this?

**Comment by porg** [comment]
IMHO managing links and their integrity is a core function of a CMS and in consequence also its main editor, which for Wordpress is Gutenberg.

I know there's technical debt. And due to that a lot of lurking compatibility challenges.

But sooner or later someone should have the courage to tackle this long lasting lack.

Maybe it can also be made in a manner that the situation gets better in Gutenberg while remaining unchanged (=quite bad) for other editors/builders. As long as it's not getting worse for others, no harm is done.

Quite the contrary: That departure towards improvement would then encourage others to follow suit with Gutenberg as the best practice for link healing then!

**Comment by porg** [comment]
@mtias do you see value in my proposed approach from the comment above to move forward and serve as a best practise?

**Comment by mtias** [comment]
Hi @porg — the proposal is not really actionable as explained in the previous comments. If you want to advocate for dynamic links I'd encourage you to go the discussion thread I linked above about "bits". WP is not going to be doing a search and replace across all possible content types so a mechanism to make links dynamic is a prerequisite.
