### ISSUE TITLE
Additional css classes should be applied to transformed blocks

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#34592]
## What problem does this address?
When transforming blocks between each other, classes added through the Advanced Additional CSS field are not carried with the transform. Is there a clear reason behind this? Related to transforms explorations in #34591 and #34590.

## What is your proposed solution?
I’d expect that if I’ve added a class myself, that class would be persistent when transforming a block.

## Screenshot 
<img width="568" alt="Screen Shot 2021-09-06 at 11 27 00 AM" src="https://user-images.githubusercontent.com/1813435/132238904-a16a8650-8b5b-4a6e-aa2b-beca72a1aff6.png">

**Comment by Sandstromer** [comment]
Is there any way of detecting whether a class has been added by the user, versus a class added by selecting a block style?

What I'm getting at is a block style and its CSS class will often be specific to that block, and keeping the class when transforming a block could possibly lead to confusion?

**Comment by richtabor** [comment]
> Is there any way of detecting whether a class has been added by the user, versus a class added by selecting a block style?

Not 100% sure myself, but we could omit `.is-style-...` from being carried over.

**Comment by Mamaduka** [comment]
I think the issue was fixed via #38964.

**Comment by richtabor** [comment]
Yup, just confirmed it. Thanks George!
