### ISSUE TITLE
Add Block: List

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#346]
## Attributes

- Formatting bar

## Markup

```html
<ul>
	<li>The quick brown fox jumps over the lazy dog.</li>
</ul>
```

```html
<ol>
	<li>The quick brown fox jumps over the lazy dog.</li>
</ol>
```

## States

Existing text:

![list neutral](https://cloud.githubusercontent.com/assets/1204802/25338131/77a6545a-28fe-11e7-806a-62f009649a01.png)

Switching to a list:

![list switch to list](https://cloud.githubusercontent.com/assets/1204802/25338139/7a2e1a28-28fe-11e7-91d3-a5960cbbfd62.png)

Selected:

![list unordered selected](https://cloud.githubusercontent.com/assets/1204802/25338144/7dbb0c00-28fe-11e7-9cc7-d50861256300.png)

Neutral unordered:

![list undordered neutral](https://cloud.githubusercontent.com/assets/1204802/25338148/81877cce-28fe-11e7-9d53-945e9bb2acf4.png)

Hover:

![list unordered hover](https://cloud.githubusercontent.com/assets/1204802/25338150/84398174-28fe-11e7-975a-58576b2b3aaf.png)

Neutral ordered:

![list ordered neutral](https://cloud.githubusercontent.com/assets/1204802/25338152/87ae19f0-28fe-11e7-8312-f381f17a128c.png)

Placeholder, when inserted as a block:

![list placeholder selected](https://cloud.githubusercontent.com/assets/1204802/25338156/8b0adfc0-28fe-11e7-8ca5-84da8f06da40.png)

**Comment by mtias** [comment]
Something to consider: it'd be neat to allow easy re-arrangement of individual list items with up/down arrows. That's something I do often and it takes some dancing around copy/paste and not losing inline formatting of list while doing so.

**Comment by jasmussen** [comment]
> it'd be neat to allow easy re-arrangement of individual list items with up/down arrows

Google Keep has a neat interface for this:

![mar-29-2017 13-20-27](https://cloud.githubusercontent.com/assets/1204802/24452276/bbe4752e-1482-11e7-9cdb-e5e6361e2a1a.gif)

@spocke How hard would this be to make as a TinyMCE improvement? On a scale from "trivial" to "nightmare hellride".

**Comment by iseulde** [comment]
Something to keep in mind here as well are nested lists:

* Down
  * down
    * down the rabbit hole.

**Comment by androb** [comment]
Other requirements to think about:

- Ending list when you are in the last item and it is empty and you hit
enter again
- Splitting lists into two lists if you hit enter twice in the middle of
the list
- Joining two lists if you hit delete key at first character and there is a
list before it

**Comment by spocke** [comment]
It might become complicated on nested lists since how do you drag between levels. For example beginning of a indented list is the same location as after the unindented item.

The location between these two are the same but the user could want to drag before b inside that list or after a.1. However I guess that could be done by just supporting the "a" case and the user would have to indent it to get it to the same level as "b". 
* a
  * b

**Comment by circlecube** [comment]
With nested lists, it's also useful to keep in mind the UI for indenting the list/nested list.

-For moving a list item deeper down the rabbit hole (right)
-Also for moving a list item up the nested structure (left)
-What to do with the nested list items when their parent moves up/down the hierarchy? I'd assume just leave them where they are in relation to the moving li. Here's how it is done in the current editor:
![nested list items](https://cloud.githubusercontent.com/assets/698049/24454974/f9764aba-145b-11e7-8389-57d554b446f2.gif)

**Comment by mtias** [comment]
I think maybe instead of dragging, just up/down arrows like we do for blocks themselves could be interesting.

**Comment by joyously** [comment]
The `ol` can have a `reversed` attribute and a `start` attribute.
The `li` can have a `value` attribute.

**Comment by androb** [comment]
Regarding implementation, if this were to be implemented as a "wrapped TinyMCE that is constrained to just do lists" @Afraithe has raised concerns about how this would be achieved.

Perhaps this is better implemented as part of the more generic "TinyMCE Block" that is getting discussed in PR #335

**Comment by Afraithe** [comment]
Yeah, contraining TinyMCE to "just" handle lists isn't really what it's made for, so not sure how that would work.

**Comment by androb** [comment]
Could we potentially view Text, List, Tables, Headings and (maybe) Quotes as different twists on the same thing? As contained in a "Smart Text Block" (aka TinyMCE with some UI changes).

Underneath the hood, a Smart Text Block would behave slightly differently than the regular blocks but, to the user, it would feel the same. For example, the Type Indicator would switch a paragraph to a list inside the Text Block, not create entirely new blocks. It would look seamless with the Gutenberg experience. 

Copy/paste, undo/redo, and a lot of the simple text interactions (#179) would work much better within the Smart Text Block. There would be more of a _type type type_ experience.

A Smart Text Block would cope much better with unstructured/legacy content and content imported from elsewhere yet would retain the overall user experience of Gutenberg.

(Yes this is similar to what is getting discussed in #335)

**Comment by annaephox** [comment]
We have made a start on list block: #358 
Feedback welcome!

**Comment by mimo84** [comment]
Just an update on the implementation of the block plugin. As I will be away for the time being, at this moment we merged in basic editing and implementation for the editor and block level operations (align).
I opened a new PR about block switching and save / update content.
We need to find a better way to extract the attributes in the onChange method.
Next things to be implemented are block list toolbar, where to hook switching block type. Needs to be discussed also if block switching belongs to the plugin itself or not. For example, how do we manage swapping a heading block to a list block and which actions should be possible or not possible.
Ideas welcome :)

**Comment by jasmussen** [comment]
@mimo84 @intronic I see the list block in master, hooray! 

I also noticed the alignments, which were part of the mockups initially. Upon reflection it doesn't seem like text align makes any sense at all in the list block, do you agree? 

On the other hand, indent and unindent makes a lot of sense to have, so I've updated the mockups on this page. Let me know if you're still working on these and/or could use some help.

**Comment by EphoxJames** [comment]
@jasmussen To create the list as shown in the mockups above it seems I will need to have an ordered and unordered variant so I can create transforms between them (looking at the heading block for an example). Alternatively I could create buttons like with the alignment selector or the heading levels. Which is the preferred approach?

**Comment by EphoxJames** [comment]
I've submitted a pull request to enable the updating of list content based on @mimo84 's pull request.
https://github.com/WordPress/gutenberg/pull/598

**Comment by jasmussen** [comment]
> To create the list as shown in the mockups above it seems I will need to have an ordered and unordered variant so I can create transforms between them (looking at the heading block for an example). 

Correct, we'd need separate blocks for unordered list, and ordered lists, and a way to switch between them using the Switcher.

> Alternatively I could create buttons like with the alignment selector or the heading levels. Which is the preferred approach?

I think it may be good to focus on those blocks primarily, as opposed to the flow. Because the flow for creating lists might evolve, as tracked here: https://github.com/WordPress/gutenberg/issues/539#issuecomment-298556693

In other words, we know that we'll need the two list blocks. But we haven't fully decided what the best approach for creating them is. 

Thanks! Please reach out here or in DM or anywhere, if I can be of more help.

**Comment by jasmussen** [comment]
As an update, your PR looks great, and I think we should get it merged in without any more feature work. That will close this ticket. 

Future enhancements, like flows for creating lists, and whether a list is a single or multiple blocks, I will open separate tickets for that.

**Comment by EphoxJames** [comment]
@jasmussen I've updated the pull request to a mergeable state. Should I merge it myself or should that be done by reviewers? Is the procedure that wordpress follows documented somewhere?

**Comment by jasmussen** [comment]
> I've updated the pull request to a mergeable state. Should I merge it myself or should that be done by reviewers? Is the procedure that wordpress follows documented somewhere?

Nice work! You can merge it yourself once it's approved by the reviewers. I'll ask and see if we can get that expedited!

**Comment by jasmussen** [comment]
Closing in favor of #704 🎉
