### ISSUE TITLE
Using currentColor as background for button can be risky

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#3460]
@jasmussen Using currentColor as background for button can be a little bit risky for color contrast.

This is example of one of my themes:

<img width="411" alt="button background color contrast issue" src="https://user-images.githubusercontent.com/1820415/32745190-9e03993a-c8ba-11e7-9c23-c56b1b47a86c.png">

It has color contrast of 1.3:1.

I have my own suggestion in PR #3445 for button CSS.

**Comment by jasmussen** [comment]
Tried a fix in that PR referenced above.
