### ISSUE TITLE
Tweak LabelWrapper's max-width.

### ISSUE THREAD

**Issue by tmatsuur** [WordPress/gutenberg#34609]
## What problem does this address?

The 'Custom' label in the typographic properties translates to 'カスタム' in Japanese.
In my environment, the width of the label is just a little bit too short, so it is translated as 'カスタ...'. in my environment.
Is it possible to improve this problem?

![image](https://user-images.githubusercontent.com/495138/132445895-b8937f0b-1725-4dfe-bfd4-17434dd9f8c7.png)

My environment
OS: Windows 10
Browser: Google Chrome
WordPress: 5.8.0

## What is your proposed solution?

The inline style for this label will look like this.
```
.css-1kxnmuk-View-LabelWrapper {
    max-width: calc(100% - 10px);
}
```

Changing this "10px" to a smaller value such as ".5em" can be expected to improve the situation.

The source code files that seem to be involved are as follows.

input-control/styles/input-control-styles.tsx : 261-263
```
export const LabelWrapper = styled( FlexItem )`
	max-width: calc( 100% - 10px );
`;
```

**Comment by jordesign** [comment]
Hi @tmatsuur  - do you still taking this place in the current interface?

**Comment by tmatsuur** [comment]
Thank you for your comments.
The latest UI has changed the areas I noted and the issues I initially felt have been resolved.
