### ISSUE TITLE
Add in applied feedback messages

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3461]
This is an exploration of the idea suggested by @hedgefield and builds on from the messages work in #3457. 

Let's consider having feedback messages when something is applied. Some good cases for this would be:

- Links
- Captions
- Buttons..

Possible placing for these:

## In top bar: this is the least elegant solution in my opinion

![1](https://user-images.githubusercontent.com/253067/32749340-fec06144-c8b6-11e7-802c-fbd590fd55cc.png)

## Beside the action: not sure this scales for all cases

![2](https://user-images.githubusercontent.com/253067/32749353-06aef80c-c8b7-11e7-905d-f2d17f4c53e5.png)

## Underneath the action: this possibly is a better format

![3](https://user-images.githubusercontent.com/253067/32749379-17ef0e4a-c8b7-11e7-8234-85af0b7ec371.png)

## Let's research and consider before we design

- Where should the message go?
- Are there any existing patterns in core we can use for this?
- If there are no existing, what are some examples design wise of this in other applications?

**Comment by mtias** [comment]
Why do we need messages for these actions? I think messages should be used for important async calls, like updating and saving a post or a global block. The success message for applying a link should be that the link shows.

**Comment by hedgefield** [comment]
For links this isn't such a problem, but the Button block does not distinguish between an entered URL and an applied URL. Pressing Enter or the Apply button does not give any feedback. That's confusing. A whole message might be a bit intense, but at least the button should change styling/become hidden/display a checkmark to show that what you did had an impact. See https://github.com/WordPress/gutenberg/pull/3427#issuecomment-343879781 for context.

**Comment by karmatosed** [comment]
Let's close and look at auditing messages as a group.
