### ISSUE TITLE
Filter the nesting level of items in the navigation block

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#34611]
Draft

We're currently hardcoding the nesting level of links in the navigation block to 5. I believe we should allow people to change this value.

**Comment by talldan** [comment]
This might be a silly idea, but what if it were a prop of the Edit component so that it could be filtered using the existing BlockEdit filter. e.g.:
```jsx
NavigationLinkEdit( { maxNestingLevel = 5, // ... } ) {
```

**Comment by draganescu** [comment]
That's actually not a bad idea at all. We reuse a filter why add another one.
