### ISSUE TITLE
block metadata frontStyle and frontScript just for front-end

### ISSUE THREAD

**Issue by amir2mi** [WordPress/gutenberg#34620]
As it is suggested in the [block metadata documentation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#editor-style) block.json is a big help for blocks and in this file styles and scripts can be set to be enqueued.

Currently, a block can have four types of assets:
`style` & `script` that will be enqueued for both **editor** and **front-end**.
`editorStyle` & `editorScript` that will be enqueued just for editor.

But what happens if a style or script be different for editor and front-end there is no option like `frontStyle` and `frontScript` to achieve different assets for editor and front-end.

**Comment by Mamaduka** [comment]
Hi, @amir2mi

Here's a tracking issue for proposed improvements #33542.

**Comment by amir2mi** [comment]
Hi @Mamaduka, thanks. I'll wait for it undoubtedly changes will be cool!
