### ISSUE TITLE
Error when trying to type link address

### ISSUE THREAD

**Issue by vladanost** [WordPress/gutenberg#3463]
Gutenberg 1.6.1

## Issue Overview

Error when trying to type link address

## Steps to Reproduce (for bugs)

1. Add a paragraph block and add some text
2. Select part of the text and click on link icon in the toolbar
3. Type link address

Tested in Chrome 62.0.3202.89 and Firefox 56.0.2 

## Expected Behavior

You should be able to type link text

## Current Behavior

Uncaught Error: Invalid assumption: expected selection to be within the autocomplete container is displaying in js console.

## Screenshots / Video

![screen shot 2017-11-13 at 23 09 52](https://user-images.githubusercontent.com/1592693/32752004-ea5fcfb2-c8c7-11e7-9057-c5b0c7cf7f26.png)
![screen shot 2017-11-13 at 23 07 26](https://user-images.githubusercontent.com/1592693/32752011-eddef4ec-c8c7-11e7-9c99-5681d358aeb9.png)

**Comment by EphoxJames** [comment]
There is a PR open to fix this issue at #3398 waiting on approval to merge.

**Comment by EphoxJames** [comment]
It's basically because the autocompleter treats the wrapped component as a black box so it would catch any input event, including input events from text fields which don't use the same selection model as contentEditable.

**Comment by EphoxJames** [comment]
The PR fixes this by filtering input events to only come from a contentEditable component though the reviewer decided that this was insufficient in case the URL input was changed to contentEditable in future so it also adds a CSS selector to filter the event sources.

**Comment by EphoxJames** [comment]
Hmmm, it seems a completely different thing has broken the URL dialog since I wrote that PR.

**Comment by EphoxJames** [comment]
See #3466 where there is an analysis of the second issue.
