### ISSUE TITLE
Release 11.5.0

### ISSUE THREAD

**Issue by getsource** [WordPress/gutenberg#34636]
Tracking issue to note/order which PRs should be pulled into release/11.5

Oldest to Newest ↓
- [x] https://github.com/WordPress/gutenberg/pull/34639
- [x] https://github.com/WordPress/gutenberg/pull/34651
- [x] https://github.com/WordPress/gutenberg/pull/34264

**Comment by ntsekouras** [comment]
👋 - not merged yet but this one should be included: https://github.com/WordPress/gutenberg/pull/34639

-----
--edit:

This above got merged and would be good to also include: https://github.com/WordPress/gutenberg/pull/34651. They are both follow ups for Social List `flex` layout.

**Comment by gziolo** [comment]
I'm about to cherry-pick non-production change into the release branch:
- https://github.com/WordPress/gutenberg/pull/34264

I want to publish to npm WordPress packages based on the release branch and this PR included a bug fix for `@wordpress/scripts` that fixes backward compatibility issues.

**Comment by getsource** [comment]
Thanks everyone!
