### ISSUE TITLE
Block mover handles showing over link input

### ISSUE THREAD

**Issue by vladanost** [WordPress/gutenberg#3464]
Gutenberg 1.6.1

## Issue Overview

Block mover handles showing over link input when hovering over the block that is bellow it.

## Steps to Reproduce (for bugs)

1. Create 2 paragraphs. Make sure that first paragraph has only one sentence. 
2. Select part of the text from first paragraph and click on the link icon in the toolbar
3. hover over the second paragraph

Tested in Chrome 62.0.3202.89 and Firefox 56.0.2

## Expected Behavior

Mover handles should stay bellow the link address input field.

## Current Behavior

Mover handles are on top of link address input field.

## Possible Solution

Increase z-index on link address input field.

## Screenshots / Video

![screen shot 2017-11-13 at 23 34 17](https://user-images.githubusercontent.com/1592693/32753267-756c63be-c8cc-11e7-8933-ecc22acace0e.png)

**Comment by Soean** [comment]
This issue seems to be fixed. So you can close the issue.
