### ISSUE TITLE
Video block captions: Add support for margins and alignment

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#34642]
## What problem does this address?
Themes need a way to style captions inside video blocks, especially margins and text alignment properties.

## What is your proposed solution?
We could do this by adding controls to the video block, so that users can edit them, or we could just make the controls available in theme.json.

Alternatively we could add support for the figcaption element to the elements part of theme.json, and apply the same settings to images and videos.

**Comment by carolinan** [comment]
Can this issue be closed? The caption can be styled using theme.json and global styles. (Classic themes can keep using CSS)

**Comment by scruffian** [comment]
Yes, let's close this.
