### ISSUE TITLE
Post Author: Add support for font weight

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#34640]
## What problem does this address?
It would be good to be able to set a font weight for the Post Author name. The weight should only target the author's name, not the byline.

**Comment by ramonjd** [comment]
https://github.com/WordPress/gutenberg/pull/34064 is in train to add font weight and style appearance to the Post Author block, albeit at the block container level. 

Block support applies the styles to block's root element by default. 

One way to target inner blocks is to use `__experimentalSkipSerialization`, and apply the styles to the inner blocks manually in the block itself. 

The catch is that global styles/theme.json style definition can't yet target inner blocks in the same way.

There is an ongoing discussion about how to tackle this challenge, as there are now several blocks with similar requirements.

See: https://github.com/WordPress/gutenberg/issues/33255

**Comment by aaronrobertshaw** [comment]
This issue was resolved with the [creation of a Post Author Name block ](https://github.com/WordPress/gutenberg/pull/36001)that adopted font-weight support. That block was also extended to have full typography supports in https://github.com/WordPress/gutenberg/pull/43319
