### ISSUE TITLE
HTML Block: Add support for color and border

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#34645]
## What problem does this address?
Themes need a way to customize the HTML block, particularly the color and border properties.

## What is your proposed solution?
We can add support for color and border to block so that it can be changed via theme.json.

**Comment by mtias** [comment]
Not sure I follow this one. The html block just renders the html on the front?

**Comment by scruffian** [comment]
In Quadrat for example we are modifying the color and border of the textarea in the editor, so that it matches the forms in the front end:

<img width="704" alt="Screenshot 2021-09-09 at 09 32 50" src="https://user-images.githubusercontent.com/275961/132651927-07bae12e-d49c-4ca7-bf64-398bcfee5725.png">

Without this the HTML block is pretty hard to use:

<img width="716" alt="Screenshot 2021-09-09 at 09 32 42" src="https://user-images.githubusercontent.com/275961/132651975-00557b91-a9c7-4b3a-82ea-d283bc30d3a0.png">

Perhaps this will be dealt with when we allow form elements in Global Styles...

**Comment by mtias** [comment]
This seems like the HTML block should force a white background. cc @jasmussen It's not meant to blend with the theme, it's a code view that will render the HTML on the front anyways.

**Comment by jasmussen** [comment]
Right, the HTML block should be considered "editor UI", and have the same materials and styling as the block toolbar. I'll see if I can increase the specificity of those styles to survive anything the theme throws at it.
