### ISSUE TITLE
Image block: Add font size control for captions

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#34643]
## What problem does this address?
Themes need a way to control font size of captions for image blocks.

## What is your proposed solution?
We could add a control for font size to the block and have it target captions with `experimentalSelector`. Alternatively we could add support for `figcaption` to the elements part of Global Styles.

**Comment by glendaviesnz** [comment]
Changed the title to `Image block` as once experimental flag removed for refactored gallery the gallery images are Images blocks - so fix should primarily target the Image block. Switch it back @scruffian if I have misunderstood this.

**Comment by ramonjd** [comment]
Just adding some cursory experimental findings.

I added typography block support to the Image block and gave the `<figcaption />` a style of `font-style: inherit`, overriding the currently-defined `13px`.

Works fine, albeit the default figcaption font size inherits from up the tree somewhere, in the example below, from `--wp--preset--font-size--normal` so it's slightly bigger.

<img width="500" alt="Screen Shot 2022-01-06 at 3 12 49 pm" src="https://user-images.githubusercontent.com/6458278/148327064-d7e60674-1db8-40a0-975a-4764b6403737.png">

The `13px`, I discovered, comes from [a mixin](https://github.com/WordPress/gutenberg/blob/0d6a201ff902267dc7b48e9be355f70c2717e5ad/packages/base-styles/_mixins.scss#L195) that adds default styles to captions for Audio, Embed, Table and Video Blocks, under the assumption that _"figcaptions are not likely to be styled in the majority of existing themes"_. [Example](https://github.com/WordPress/gutenberg/blob/ccac0950408d6264ede33092843483e8fc3b919c/packages/block-library/src/image/style.scss#L67)

So to keep the status quo we'd need to ensure that the 13px from the mixin is the default until a user-defined font value is detected.

I'm not so sure that typography support on the Image block is even appropriate. Perhaps we could had something to the block inspector toolbar?

<img width="266" alt="Screen Shot 2022-01-06 at 3 29 00 pm" src="https://user-images.githubusercontent.com/6458278/148328200-eeecd16a-51d9-4b1a-952a-e1336677c094.png">

**Comment by beafialho** [comment]
+1 this would be really useful! In addition, it would be great to be able to edit the alignment of the caption to be center, left and right aligned.

**Comment by richtabor** [comment]
> Alternatively we could add support for figcaption to the elements part of Global Styles.

@scruffian Think this is good to close, now that we have captions in Global Styles via https://github.com/WordPress/gutenberg/issues/34643?

**Comment by scruffian** [comment]
Happy to close this for now. If we feel like we need per-block control we can open another issue.
