### ISSUE TITLE
Table block: Margin/padding support

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#34652]
## What problem does this address?
Themes need a way to customize the margins and paddings of the table block.

## What is your proposed solution?
We should add support for margin and padding so that they can be modified by theme.json

**Comment by draganescu** [comment]
Adding

```
"spacing": {
			"margin": true,
			"padding": true
		},

```

to `block.json` results in margin and padding being applied to the `figure` tag of the table.

<img width="646" alt="Screenshot 2022-05-24 at 15 23 43" src="https://user-images.githubusercontent.com/107534/170034074-f8e91a9f-842e-47d6-89cf-157f07a4d074.png">

I would expect the table block to also have controls for cell padding and gap, but I suppose this is another issue?

**Comment by scruffian** [comment]
I think so yes although I might expect the padding/spacing to be applied to the table tag itself - which we can do using __experimentalSelector...

**Comment by draganescu** [comment]
The table block's `block.json` already uses `"__experimentalSelector": ".wp-block-table > table"` and the `__experimentalBorder` supports applies to it, but spacing (margin and padding) seem to ignore it.

**Comment by jordesign** [comment]
I"m seeing margin and padding support for the Table block now (in WP6.3) so closing this as resolved.

![Uploading Screenshot 2023-09-05 at 2.47.23 pm.png…]()
