### ISSUE TITLE
Intermittent failure "Cannot read property hasClass of undefined"

### ISSUE THREAD

**Issue by ephox-mogran** [WordPress/gutenberg#3465]
## Issue Overview

Gutenberg is throwing an error intermittently if Chrome inspector tools are showing. The failure is probably relatively irrelevant to the rest of the Gutenberg page, so it isn't noticeable unless the inspector is open.

It seems to be related to heartbeat. Specifically, this code:

```
var e, f;
    a(document).on("heartbeat-tick.wp-auth-check", function(a, f) {
        "wp-auth-check"in f && (d(),
        !f["wp-auth-check"] && e.hasClass("hidden") ? b() : f["wp-auth-check"] && !e.hasClass("hidden") && c())
    }).on("heartbeat-send.wp-auth-check", function(a, b) {
        (new Date).getTime() > f && (b["wp-auth-check"] = !0)
    }).ready(function() {
        d(),
        e = a("#wp-auth-check-wrap"),
        e.find(".wp-auth-check-close").on("click", function() {
            c()
        })
```

## Steps to Reproduce (for bugs)

1. Create a new post
2. Open the Chrome inspector
3. Do things, move the mouse, open the block inserter .... talk to people 
4. Wait

Apologies for not giving a better replication case, but it really is intermittent!

**Comment by tg-ephox** [comment]
The error occurs on [this](https://github.com/WordPress/WordPress/blob/54a2c0dd1fb52f6e86f76871f45aacd5b917881e/wp-includes/js/wp-auth-check.js#L99) line.

It looks like `wrap` is never initialized because the `ready` event is not triggered...

**Comment by youknowriad** [comment]
This is probably a metaboxes issue, I tried using `jquery.holdReady` to fix those kinds of errors but apparently, this is still not working somehow.

**Comment by Presskopp** [comment]
Having this console error I wonder if it's meant to be:
`			if ( ! data['wp-auth-check'] && wp-auth-check-wrap.hasClass('hidden') ) {
				show();
			} else if ( data['wp-auth-check'] && ! wp-auth-check-wrap.hasClass('hidden') ) {
				hide();`

**Comment by youknowriad** [comment]
@Presskopp Do you have a way to reproduce consistently on a new install?

**Comment by Presskopp** [comment]
fresh, clean installation of 4.9–de_DE plus Gutenberg v1.7

open this screen, do a little, after few seconds errors start to show

(screenshot following)

**Comment by Presskopp** [comment]
![image](https://user-images.githubusercontent.com/18373563/33172494-b020192a-d050-11e7-8ef8-dcf61c02a432.png)

**Comment by youknowriad** [comment]
@Presskopp Do you use a specific theme/plugin? You have an horizontal bar on your screenshot which indicates that you have metaboxes.

Regardless, this #3616 will fix your issue

**Comment by Presskopp** [comment]
Theme is Twenty Seventeen v1.4 - as I said it's just a clean installation without plugins except Gutenberg.

**Comment by youknowriad** [comment]
I'm personally not able to reproduce on a fresh install with the last Gutenberg published version. Just tried here http://poopy.life/

**Comment by Presskopp** [comment]
ok, maybe it' s because of my browser tools (PHP Console, React Dev Tools..), but see

**Comment by Presskopp** [comment]
![image](https://user-images.githubusercontent.com/18373563/33174360-020108ec-d058-11e7-9f68-b9e22b2f2730.png)
