### ISSUE TITLE
Table block: Figcaption support

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#34650]
## What problem does this address?
Themes need a way to target table block captions, particularly font size and text-align.

## What is your proposed solution?
We could add these controls to the block so that they can be customized by theme.json, or we could make figcaption an element which can be customzied by Global Styles.

**Comment by carolinan** [comment]
I believe this was solved by #41140?

**Comment by scruffian** [comment]
Yes! Thanks @carolinan
