### ISSUE TITLE
Feedback on problems with writing in the block editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#34664]
## What problem does this address?

While drafting a longer post a few weekends ago, I found myself a bit distracted due to the interface in a way that I hadn't been previously. This was partially due to me throwing down sentences in chunks and trying to build them into paragraphs. Since I don't see this as an unusual way to start writing and do almost solely write in the block editor, I wanted to pass along some specific items of feedback that I noticed in this experience that proved to be cumbersome, especially since writing posts is obviously a main goal for users. 

**The block toolbar for a paragraph block covers the text completely above.** This hiding effect makes it really hard to see all of your writing and feels more distracting/disorienting, especially when drafting a post:

![toolbar covering](https://user-images.githubusercontent.com/26996883/132546979-ced9f18d-2acf-4d41-9382-0bdee6356468.gif)

**The “type / to choose a block” ends up being just one more item of text to ignore when trying to think/write.** When trying to get into the writing mood, I find having one more item of text to block out of my brain in order to find the words I want to write to be less than ideal. This is especially true when starting to write a sentence, deleting, and restarting only to see that phrase pop up (both when deleting and beneath the text if I started writing there too):

![prompt](https://user-images.githubusercontent.com/26996883/132547833-f4e8bdf8-8d03-4379-ba88-f0a61ee32db4.gif)

**The sheer number of ways to add a block can feel a bit overwhelming and confusing.** In most cases, I can see two black + buttons, one floating button, the overall prompt, and the Inserter. This seems to get worse when the Top Toolbar mode is enabled. This is related to the currently open issue around the + button in general but I'm including it here for comprehensiveness https://github.com/WordPress/gutenberg/issues/26404 

![add block prompts](https://user-images.githubusercontent.com/26996883/132551573-17169cf7-7b75-4f59-bf69-d06e47a836ca.gif)

## What is your proposed solution?

Previously, there were some explorations in https://github.com/WordPress/gutenberg/issues/2460#issuecomment-336915515 and https://github.com/WordPress/gutenberg/issues/2876 that were a bit inconclusive (should this be a plugin's role or Core's role?). Personally, I'd love to see a mode offered that helps solve some of these problems and that's tailored towards writing.

**Comment by sybrew** [comment]
There was great advocacy for enabling "Top Toolbar" by default. I believe it was for this reason. But that's neither here nor there, and I cannot fantom a fix for this non-"Top Toolbar" feature that'd also be accessible. Perhaps, the time has come to remove features that didn't work out the way they were envisioned.

**Comment by jameskoster** [comment]
I've often wondered how we might split tools based on the current editor mode. For example, perhaps in Select mode you find tools that apply to the whole block such as position, transformations, and text alignment (some of these ideas inspired https://github.com/WordPress/gutenberg/issues/31236).

In edit mode you find text tools like bold / italic, but only when you select some text. Otherwise you get a reduced plain text editing experience.

https://user-images.githubusercontent.com/846565/155123630-d4433abe-0701-4f3d-b687-56146e8b4c1c.mp4

**Comment by Thelmachido** [comment]
Hi, @annezazu would it be safe to say that the problems highlighted here have been resolved by the distraction-free mode in the block editor?

**Comment by annezazu** [comment]
In many ways, yes. My only hesitation in closing this out is that the pain points remain in the base block experience, despite there essentially being a work around. I'd prefer to see the base writing experience also improve. Let's close it out though as some iterations have occurred since I opened this.
