### ISSUE TITLE
Can't update existing featured image on Gutenberg 11.4.1

### ISSUE THREAD

**Issue by khristiansnyder** [WordPress/gutenberg#34671]
### Description

With Gutenberg 11.4.1 active, updating a post/page that has an existing featured image just results in a spinning icon and the image never updates within the editor. It does seem to update on the front end.

### Step-by-step reproduction instructions

1. Open the editor of a post with an existing featured image
2. Try and update that image in the editor. After selecting the image in the media library, a spinning icon shows but never updates:

![](https://user-images.githubusercontent.com/41035049/132551106-58dfd5df-6591-4e72-bb92-d6290c6319bf.png)

### Environment info

Gutenberg 11.4.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by khristiansnyder** [comment]
This is the PR that introduced the issue, it seems: https://github.com/WordPress/gutenberg/pull/34034

**Comment by lwangdu** [comment]
I am having same issue with Gutenberg 11.4.1

**Comment by creativecoder** [comment]
I do see this issue on 11.4.1.

However I _don't_ see this issue while running `trunk` (marked as 11.5.0-rc.1) on the same site, so I anticipate it will be resolved with the 11.5 release.

**Comment by talldan** [comment]
Thanks for reporting. It looks like this was previously and reported resolved (#34506, #34583) and as mentioned will be fixed in 11.5.
