### ISSUE TITLE
Format toolbar not reflecting current editor state

### ISSUE THREAD

**Issue by ephox-mogran** [WordPress/gutenberg#3467]
## Issue Overview

The bold, italic buttons etc. are not reflecting the current editor state as you move the cursor (via keyboard or clicking).

## Steps to Reproduce (for bugs)

1. Create a new paragraph
2. Select one of the words and make it bold
3. Move the cursor around in that paragraph

## Expected Behavior

The bold state reflects where the cursor is

## Current Behavior

The bold state gets out of sync.

## Possible Solution

This looks like it is also an issue with how the slot is not updating when non bubbling virtually. The related issue is #3466 . @tg-ephox is creating a PR for this fix.

**Comment by mtias** [comment]
It seems this affects more than just inline formatting. If you switch the quote style the toolbar state doesn't update:

![image](https://user-images.githubusercontent.com/548849/32778821-aa7e5fe8-c93b-11e7-9db0-bbe40a1a012a.png)
