### ISSUE TITLE
Embed Preview not unfurling for some links

### ISSUE THREAD

**Issue by kosiew** [WordPress/gutenberg#34676]
### Description

Rich Preview is not working for some links eg 
https://vietnamhoonist.com/2021/08/31/tong-hop-tin-tuc-thang-8-2021/, 

For links like:
https://wp20180808.com/contact/
https://wp20180808.com/about/

We get a message that `Sorry, this content could not be embedded.`

### Step-by-step reproduction instructions

1.  On the page editor, paste the link on a new line to a post. URL: [https://vietnamhoonist.com/2021/08/31/tong-hop-tin-tuc-thang-8-2021/](https://vietnamhoonist.com/2021/08/31/tong-hop-tin-tuc-thang-8-2021/) It doesn't unfurl, but only shows a link that is embedded without any preview on the editor.
2.  When previewing the page, it doesn't show the preview of the post shared, it only shows a link.
3.  Shared another link from the same site on the editor, it unfurls and shows the preview.
4.  When previewing the page on the front end, it doesn't show the preview on the front end.
5.  Checked by pasting link from another blog (simple as well as an atomic site), it unfurls in the editor as well as on the front end.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/29057562/132629982-27216940-36d6-4862-ace6-25bef35f3eee.mp4

### Environment info

Operating System
Windows, macOS

Browser
Chrome/Chromium

WordPress 5.8

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jpantani** [comment]
I noticed that those blog links point to WordPress.com hosted sites. 
Do you have an example of a WP embed that doesn't work that is not WordPress.com based? 
For example https://make.wordpress.org/core/2021/09/13/a-week-in-core-september-13-2021/ works.

**Comment by gwwar** [comment]
I also see Make blog post links working. For the provided links noted in the issue, I see a 404 returned:

<img width="891" alt="CleanShot 2021-09-13 at 16 00 32@2x" src="https://user-images.githubusercontent.com/1270189/133167778-1ccad235-8eb5-423b-aae2-b15e030db657.png">

**Comment by kosiew** [comment]
I tested with https://wpstore102.mystagingwebsite.com/test/ and it does embed correctly.

I will raise this with WordPress.com.

Thanks @jpantani, @gwwar for looking.

**Comment by gwwar** [comment]
Thanks for double checking @kosiew ! I'm going to close this one for now, but let us know if there are other cases to look at.
