### ISSUE TITLE
Social Icons block removes items-justified-x class when duplicated

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#34686]
### Description

When you duplicate a Social Icons block set to a "Justify X" value other than left, the duplicate loses the justify setting or reverses to the setting the original had when the post was last saved. This also happens if you duplicate a group containing a Social Icons block with a justify setting.

### Step-by-step reproduction instructions

1. Add a Social Icons block
2. Set it to "Justify right".
3. Duplicate the block. The duplicate reverts to "Justify left".

To have the duplicate reverse to the value the original had when the post was last updated:

1. Add a Social Icons block.
2. Set it to "Justify right".
3. Update the post and reload.
4. Set the Social Icons block to "Justify center".
5. Duplicate the block. The duplicate now reverts to "Justify right" – the value the original had when the post was updated.

### Environment info

Gutenberg 11.4.1, WordPress 5.8.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Sandstromer** [comment]
I can reproduce and confirm this.

The duplicated block doesn't really revert to 'Justify Left' though.
The justify class `items-justified-x` is not carried over with the duplication, and is empty on the duplicated block.

**Comment by jasmussen** [comment]
CC: @mkaz in case you'd want to pair on this one, or have additional context.

**Comment by mkaz** [comment]
I could not duplicate this. In fact, when using the latest Gutenberg plugin it does not add those utility classes but appear to be setting the alignment for the container. It looks like it [might of been changed in this one](https://github.com/WordPress/gutenberg/pull/34651).

![social-justify](https://user-images.githubusercontent.com/45363/136289500-baac2cb4-c323-47a9-b67b-dc14ae419036.gif)

Can we confirm this is still an issue?

**Comment by andersnoren** [comment]
I can't replicate it in 11.6.0 either, so it seems like it's been fixed.
