### ISSUE TITLE
Components: reconcile multiple README and CONTRIBUTING into single docs

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#34692]
## What

Follow up to #33960 — There are currently multiple README and CONTRIBUTING files in the `@wordpress/components` package — we should reconcile them into single files.

## Why

Keeping our docs clear and up-to-date

## A/C

- [ ] Only one README and one CONTRIBUTING file should be present at the root of the package
- [ ] Information should be consolidated within the same doc(s)
- [ ] Out-of-date information should be removed

**Comment by ryanwelcher** [comment]
@ciampo is this issue still relevant?

**Comment by ciampo** [comment]
Hey @ryanwelcher , yes it is. I'll see if we squeeze in some time to work on this in the upcoming days

**Comment by ciampo** [comment]
cc @chad1008 — we talked about this task recently, here's the related open issue

**Comment by ciampo** [comment]
Closing as solved by #50226
