### ISSUE TITLE
Make React work in the front-end with blocks out of the box.

### ISSUE THREAD

**Issue by ivanjeremic** [WordPress/gutenberg#34718]
I personally think the reason why React developers struggle with this is React is an amazing tool for building interactive UI and the fact that Blocks are not interactive in the front-end is somehow a missed opportunity considering how manny react developers are out there, something like this build in would not only boost the block development since more react devs would come in, it will also help create amazing new things with Gutenberg and blocks.

**Comment by gziolo** [comment]
Thank you for opening this issue. There is already a similar discussion happening in #14446. I will close this one and copy your comment there.
