### ISSUE TITLE
theme.json: support a description value for templateParts

### ISSUE THREAD

**Issue by chthonic-ds** [WordPress/gutenberg#34723]
## What problem does this address?

In theme.json `templateParts` supports two values: `name` and `area`. 

`name` matches with the filename for a template part. When viewing Site Editor > Template Parts, available parts are described using the value for `name`. This can result in an "unfriendly" label for each part, especially if using overly descriptive names.

For example, the following in theme.json:
```
"templateParts": [
     {
         "name": "header-site-logo",
         "area": "header"
     },
     {
         "name": "header-site-logo-navigation",
         "area": "header"
     },
     {
         "name": "header-site-logo-site-title-navigation",
         "area": "header"
     }
 ]
```
...currently displays like this in the Site Editor:

![template-part-label-current](https://user-images.githubusercontent.com/29587253/132795393-67d19172-7a72-437c-8fcf-7fcd575444bf.png)

## What is your proposed solution?

Is it possible to support a third value in `templateParts`, please? Perhaps `description` could work as the key. 

This would allow for the following:
```
"templateParts": [
     {
         "name": "header-site-logo",
         "area": "header",
         "description": "Logo only"
     },
     {
         "name": "header-site-logo-navigation",
         "area": "header",
         "description": "Logo & navigation"
     },
     {
         "name": "header-site-logo-site-title-navigation",
         "area": "header",
         "description": "Logo, site title & navigation"
     }
 ]
```
![template-part-label-proposed](https://user-images.githubusercontent.com/29587253/132796066-af1dd7e2-e957-4f33-91eb-b76f0fd0d545.png)

**Comment by Mamaduka** [comment]
I just created PR to add this enhancement - #35626.
