### ISSUE TITLE
In a list, undoing delete then pressing Enter creates zero or two empty lines

### ISSUE THREAD

**Issue by nyanpasu64** [WordPress/gutenberg#34722]
### Description

When editing text in a list block, undoing deletions and then pressing Enter may result in 0 or 2 lines being created.

### Step-by-step reproduction instructions

1. Create a list block with 3 elements, the middle indented. Save a draft and reload (this means you can't test these steps on https://wordpress.org/gutenberg/).
2. Place the cursor at the end of the indented middle line.
3. Press Del (to join the third line into the second) followed by Home.
4. Press Del 1 or more times, wait a second, and press Del 1 or more times or Ctrl-Del.
5. Undo 3 times (to undo the 3 distinct Del key presses) to return to the initial state, then press Enter.

This Enter key press does not generate an empty line, but instead moves the cursor down to the third line and indents it by 1 level.

If you instead pressed Enter after step 2, you'd create an empty line and place the cursor onto it.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/913957/132789603-2dffad89-20d5-414d-b911-68b26bbd3568.mp4

I also found a variant of the bug which causes *two* newlines to be created, but I couldn't figure out reproducible steps to achieve this:

https://user-images.githubusercontent.com/913957/132789662-c9c670d5-02d6-428d-a564-843aa45a5204.mp4

### Environment info

- WordPress 5.8.1, Gutenberg 11.4.1, Argon theme
- Firefox, Chromium
- Arch Linux

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg and WordPress. Therefore, I am going to close this issue. If anyone can replicate it in the future, please feel free to reopen this issue with additional information.
