### ISSUE TITLE
Block Supports: Add additional PHP test coverage

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#34728]
## What problem does this address?

Now that Block Supports are widely used for blocks in Gutenberg, let's investigate whether it'd be helpful to add additional block-level PHP tests to ensure the stability of the block supports and that we don't accidentally introduce regressions when we make updates to existing block supports.

## What is your proposed solution?

The Block Supports PHP code that lives in `lib/block-supports` appears to currently have test coverage that mostly addresses `theme.json` support, via the tests in `phpunit/class-wp-theme-json-test.php`. For example, this ensures that given a `theme.json` file with a particular shape, the resulting generated CSS looks correct.

In addition to these tests, I propose that we look into adding PHPUnit tests to cover the server-side Block Supports behaviour that isn't directly related to the `theme.json` output. I included a few tests as part of the blockGap support in #33991, which added in a separate test file for spacing in `phpunit/block-supports/spacing-test.php`. Some examples of behaviour that could be good to test:

* The `gutenberg_apply_spacing_support` function and that an individual block that opts into the spacing support receives the expected styles.
* The `__experimentalSkipSerialization` flag in a block's supports, and test that a block that opts into that flag doesn't get the styles added.

For the purposes of this issue, let's review the key areas that could use additional test coverage in the following files under `lib/block-supports/`:

* [x] `border.php`
* [x] `colors.php`
* [ ] `dimensions.php`
* [ ] `duotone.php`
* [ ] `elements.php`
* [x] `layout.php`
* [x] `spacing.php`
* [x] `typography.php`

---

This is more of an overview issue to track exploring whether it's appropriate to add tests to the above block supports, and track which areas we think would be good to focus on. If there _are_ additional tests that we already have that I've missed, please let me know, or if you have strong feelings about PHP test coverage, I'm keen to hear what other folks think, too!

**Comment by ramonjd** [comment]
Tests have been added for:

- border.php
- colors.php
- layout.php
- spacing.php
- typography.php

**Comment by andrewserong** [comment]
Excellent, thanks for the update @ramonjd! Looks like we now have coverage for the main areas I was originally concerned about when I wrote up the issue 🎉
