### ISSUE TITLE
Inconsistent text case when displaying template part names

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#34737]
On my site I have a template part named "header". In the top bar, the block toolbar, and the Inspector this is capitalised and appears as "Header", but in the navigation sidebar it is not:

<img width="1468" alt="Screenshot 2021-09-10 at 11 54 08" src="https://user-images.githubusercontent.com/846565/132843099-b437bbfa-058b-43fd-bf61-afe2135ba32e.png">

Let's decide on the correct implementation and apply that consistently.

**Comment by carolinan** [comment]
I feel like the name that the user entered during the template creation should be displayed, and the capitalization should not be changed.

**Comment by jameskoster** [comment]
This is also an issue in the template part ellipsis menu:

<img width="293" alt="Screenshot 2022-05-30 at 16 40 22" src="https://user-images.githubusercontent.com/846565/171025364-b23a5c95-19e2-4659-ba20-9f1ed7acc71a.png">

> * Edit **h**eader
> * Remove **H**eader

**Comment by carolinan** [comment]
I am not able to reproduce this any more (using Gutenberg trunk).
The only part that does not display the template part title as I entered it, is the inspector.
[And an issue for that was created here: #42154](https://github.com/WordPress/gutenberg/issues/42154).

**Comment by jameskoster** [comment]
I'm still seeing the slug being used in the ellipsis menu:

<img width="735" alt="Screenshot 2022-07-07 at 11 56 25" src="https://user-images.githubusercontent.com/846565/177757954-f00e8dce-ee27-4869-9905-22508e569441.png">

But it looks like that will be fixed in 42221.

**Comment by Mamaduka** [comment]
@jameskoster, I made sure to use correct casing when swapped actions :)
