### ISSUE TITLE
Reusable block: Pluralize the message "Convert to regular blocks" depending on the number of blocks contained

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#34749]
## Description

The action "Convert to regular blocks" is in plural form for all cases, including when the reusable block only contains a single block. It would be great if we detect the number of blocks contained and pluralize the message:
- Reusable block only contains a single block: `Convert to a regular block`
- Reusable block contains multiple blocks: `Convert to regular blocks`

## Step-by-step reproduction instructions

1. Go to the web version of the editor.
2. Open a post/page.
3. Add any block and click on the options button located in the toolbar (the three dots icon).
4. Click on "Add to Reusable blocks" and set a name for the block.
5. Open the app (native version of the editor).
6. Open a post/page.
7. Tap on the ➕ button.
8. Navigate to the Reusable tab.
9. Tap on the recently created reusable block and select the block.
10. Tap on the block settings (three dots button).
11. Observe that the action "Convert to regular books" is in plural form.

## Expected behaviour

The action "Convert to regular blocks" should be in singular if the reusable block only contains a single block.

## Actual behaviour

The action "Convert to regular blocks" is in plural form when the reusable block only contains a single block.

## Screenshots or screen recording (optional)

<img src=https://user-images.githubusercontent.com/14905380/132894719-32468e91-611d-4d3b-957b-74fa08e7997b.png width=400>

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 12 Pro Max
- Operating system: iOS 14.5
- WordPress app version: `develop`

**Comment by illusaen** [comment]
In order to do this, we would need to first convert the block and then count the number -- perhaps by making a new function in `gutenberg/packages/reusable-blocks/src/store/selectors.js` that is based on the `gutenberg/packages/reusable-blocks/src/store/actions.js`'s `__experimentalConvertBlockToStatic` function, wheree it does everything up until making the `newBlocks` and then returns the `newBlocks.length` instead of dispatching `replaceBlocks`.

However, this seems a bit convoluted and maybe a bit wasteful because we'd have to redo the same thing if the user clicked on the actual option. @mchowning WDYT?

**Comment by illusaen** [comment]
Also interestingly enough, it seems like there's another place where this comes up -- `ReusableBlockEdit` where it says "Editing reusable blocks is not yet supported..." and "Alternatively, you can detach and edit these blocks separately by tapping "Convert to regular blocks."". If we do decide to do this we should also change it there.

**Comment by mchowning** [comment]
> ...this seems a bit convoluted and maybe a bit wasteful because we'd have to redo the same thing if the user clicked on the actual option. @mchowning WDYT?

I'm not that familiar with reusable blocks, so let's hold off on this until we get @fluiddot 's thoughts to see what he had in mind here.

**Comment by fluiddot** [comment]
> In order to do this, we would need to first convert the block and then count the number -- perhaps by making a new function in `gutenberg/packages/reusable-blocks/src/store/selectors.js` that is based on the `gutenberg/packages/reusable-blocks/src/store/actions.js`'s `__experimentalConvertBlockToStatic` function, wheree it does everything up until making the `newBlocks` and then returns the `newBlocks.length` instead of dispatching `replaceBlocks`.

A reusable block is very similar to a Group block, where a set of blocks are rendered within another one, so I think we could determine the block count by checking the inner blocks rendered within a reusable block ([reference](https://github.com/WordPress/gutenberg/blob/c386fd09299aab83df2b9da2dbab59016c6dba50/packages/block-library/src/block/edit.native.js#L210)) and hence, we probably won't need to do the conversion.

**Comment by michelmany** [comment]
Hi guys. I don't see any new updates on this issue here. Can I try to work on this as my "Good first issue" contribution? 
Thank you.
