### ISSUE TITLE
Change excerpt length in post excerpt block

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34757]
## What problem does this address?

When listing out a set of posts a post-excerpt block is displayed. However there is no option to control the length of the text that is displayed.

## What is your proposed solution?
Provide a UI control to control the length of the excerpt.

**Comment by mtias** [comment]
For reference, the Latest Post block allows setting excerpt length:

![image](https://user-images.githubusercontent.com/548849/133067269-f0dcf452-eb36-407f-906c-a91364bbd84e.png)

**Comment by ntsekouras** [comment]
This is a related PR: https://github.com/WordPress/gutenberg/pull/33366 that removed for now this field, and I explain the inconsistencies with this field.

In a few words `excerpt_length` filter is used only when an `excerpt` is not explicitly set, so if we want to be consistent we need to trim the returned content with `wordCount` attributes and also somehow find the value in `js` and handle the ` excerpt_more` filter.

**Comment by dingo-d** [comment]
Will the read more length of the excerpt block be returned in WP 5.9 or GB plugin 12.3?

**Comment by carolinan** [comment]
@dingo-d I don't see a pull request for solving the issue, so I don't think it will be solved in time.

**Comment by cadop** [comment]
Please consider fixing this

**Comment by annezazu** [comment]
This was mentioned in the [latest FSE Outreach Program call for testing](https://make.wordpress.org/test/2022/03/31/fse-program-testing-call-13-authoring-an-author-template/#comment-2438):

>The Post Excerpt block under the Query Loop doesn’t have an option to adjust the excerpt length. (The Latest Posts block does have this option.)

It does feel odd that the controls exist in the Latest Posts block but not here. When thinking about expanding functionality, this seems like a high impact quick win.

**Comment by ellenbauer** [comment]
> It does feel odd that the controls exist in the Latest Posts block but not here.

So true, I also think consistency between blocks is missing here. I heard that it might not be so easy to add Excerpt length settings to the block. But from a theme author's side, this seems to be something we would have loved to have solved in WordPress for so many years. Therefore, it would be amazing to have a solution for this issue.

**Comment by annezazu** [comment]
@scruffian might this fit as being under general block support work? https://github.com/WordPress/gutenberg/issues/41113

**Comment by BrunoAHVincent** [comment]
Any updates on this, I'm trying to add excerpt text to dynamic header, and needs to be very short

**Comment by mtias** [comment]
@ntsekouras can we revisit this and try to find a more straightforward solution? I'm not sure what consistency you are referring to with wordcount, but it seems like a minor concern compared to the ability to control length when setting up a design.

**Comment by paaljoachim** [comment]
I noticed this missing as I am exploring Twenty Twenty Two for a site with a lot of written material. I am hoping it can be added soon. Thanks!

**Comment by richtabor** [comment]
Dropping a note that this would be pretty useful in improving the query block.

**Comment by carolinan** [comment]
Any help in moving it forward would be appreciated. I have not been able to reliably determine if an excerpt is generated automatically vs created by the user. 
- When the excerpt is created by the user, the length limitation needs to be removed, otherwise their entered text will not show.
- It seems that once a post is saved, the excerpt is saved as if it is user generated, regardless if it has been edited or not?

**Comment by mtias** [comment]
I feel trimming the text should be unrelated to whether the text is crafted by the user or pulled from the content. There could be instances were a user crafted excerpt works well in one query view, but there's another more condensed sidebar display that wants to show a single line, even if it's user generated.

**Comment by carolinan** [comment]
Perhaps then the length option should only be available when in the site editor or inside a query.

**Comment by richtabor** [comment]
> I feel trimming the text should be unrelated to whether the text is crafted by the user or pulled from the content. 

Agreed.

**Comment by carolinan** [comment]
It is now implemented in the PR. But it is the opposite of how the excerpt length filter works in WP Core.

**Comment by annezazu** [comment]
Noting that this was brought up in the [nineteenth call for testing for the FSE Outreach program as desired](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2812). Let me know if I can help at all in moving this work forward (bring in reviews, etc).

**Comment by carolinan** [comment]
I need help with including `@WordPress/wordcount` in `block-library`, I don't think I did it correctly (I did not push an updated lock file).
It needs a new accessibility review after the recent updates: https://github.com/WordPress/gutenberg/pull/44964#discussion_r1033648590
And general code and usability reviews.

**Comment by annezazu** [comment]
Thank you! 

@alexstine do you think you could provide an accessibility review? 
@getdave could you help with including `@WordPress/wordcount` in `block-library` as well as perhaps provide a code review?

I'll work on a usability review and will leave some notes as I have them on the PR.

**Comment by alexstine** [comment]
@annezazu Sure. I will try to take a look soon.

**Comment by waqastariqkhan** [comment]
Hi everyone, [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-excerpt/index.php)

on line 80, there is this comment: 

 _* If themes or plugins filter the excerpt_length, we need to
 * override the filter in the editor, otherwise
 * the excerpt length block setting has no effect.
 * Returns 100 because 100 is the max length in the setting._

Shouldn't excerpt_length hook defined  [here](https://developer.wordpress.org/reference/hooks/excerpt_length) alter the length of the excerpt block?

I tried using it but it seems to have no effect, or am I missing something?


Thanks

**Comment by carolinan** [comment]
Hi
The filter should not affect the block because it would override the block **setting**.

**Comment by carolinan** [comment]
I would like to suggest that, if there are more feature requests, enhancements or bug reports for this block please open new issues.
