### ISSUE TITLE
Subscribe not working inside useEffect

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#34754]
### Description

I am trying to use subscribe in a React way, by subscribing inside Edit component of the block in order to "catch" state when editor is saving. However, when placed inside useEffect hook, subscribe does not work. 

This does not work:
```jsx
export default function Edit({ attributes, setAttributes}) {

	useEffect(() => {
		const unsubscribe = subscribe(
			() => {
				const savingPost = select('core/editor').isSavingPost();
				const autoSavingPost = select('core/editor').isAutosavingPost();
				if (savingPost && ! autoSavingPost) {
					console.log('post is saved!');
					unsubscribe();
				}
			}
		)
		return unsubscribe();	
	}, [])
// further code
```
However, this does:
```jsx
export default function Edit({ attributes, setAttributes}) {

	const unsubscribe = subscribe(
		() => {
			const savingPost = select('core/editor').isSavingPost();
			const autoSavingPost = select('core/editor').isAutosavingPost();
			if (savingPost && ! autoSavingPost) {
				console.log('post is saved!');
				unsubscribe();
			}
		}
	)
//further code
```
Am I not subscribing too many times (each time component is rendered) if subscribe is not placed in useEffect? What is solution?

### Step-by-step reproduction instructions

Please enter the code in whatever block's Edit function.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @Lovor01

It's not recommended to subscribe to a data store directly. Instead, it would be best to use the `useSelect` [custom hook](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#useselect).

Updated example:
```js
export default function Edit({ attributes, setAttributes}) {

	const hasSavedPost = useSelect( ( select ) => {
		const savingPost = select('core/editor').isSavingPost();
		const autoSavingPost = select('core/editor').isAutosavingPost();

                return savingPost && ! autoSavingPost;
	}, []);
// further code
```

**Comment by Lovor01** [comment]
You are right! Thx
