### ISSUE TITLE
Border color picker should default to currently selected color

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34758]
## What problem does this address?

When choosing a custom border color it always defaults to the same hex code (possibly the first color in your color palette?) even if you've got another palette color already selected.

## What is your proposed solution?

If I've got a border color from my palette already selected and I want to "tweak" that color then when I open "Custom color" it should default to the hex of the currently selected color.

## Screencaptured

https://user-images.githubusercontent.com/444434/132960988-ac57bb0a-75e8-4a62-96d9-61221b0e1f90.mp4

**Comment by richtabor** [comment]
Does this occur in the text or background color picker UIs? I think this may be localized to the Border Color but I’m not 100%.

**Comment by getdave** [comment]
Confirmed yes it happens only on border color. As that's experimental perhaps it has an issue. Will rename Issue now.

**Comment by mtias** [comment]
@getdave is this still the case?

**Comment by getdave** [comment]
This was fixed and no longer an Issue for me using WP 6.0 and Gutenberg Plugin `13.4.0 `
