### ISSUE TITLE
Allow special user defined settings to theme.json 

### ISSUE THREAD

**Issue by mkkeck** [WordPress/gutenberg#34755]
## What problem does this address?
It would be nice to have a section in theme.json for settings, which are used for kind of 'special user defined' which is not parsed by Gutenberg/WordPress.

Using workflows and build tools (Webpack, Babel, Sass) which could import the 'special user defined' (and of course other settings to) for getting these settings needed to build and compile. With this, a theme developer may be able, to adjust all settings at a centralized file.

I have many settings, which I have to set several times - for sass, javascript and php. Why not use the theme.json as an centralized config file and parse or import it every where it is needed?

## What is your proposed solution?
Adding a section to theme.json, which is not automatic parsed, modified or overwritten by WordPress/Gutenberg core. Make these section clear to all developers with a specific name, for example `site`, `sitewide` or what ever.

**Comment by oandregal** [comment]
Hey Michael, I've got two thoughts about this.

You can already do it. It's just not "sanctioned" by WordPress. Any setting that is present in the file but is not valid according to the schema will be ignored. If a specific tool requires data stored in a certain format in `theme.json` people will use it, similarly to what happens with `package.json` for npm: there are fields there that are not documented or used by the official `npm` documentation.

The other thought is that I'm not sure it's a good idea to use this as a place to put "all the things". The file has a specific goal, which is helping themes. Things like perhaps generating the required "style.css" file from data stored in theme.json would be cool to have. Starting to pollute the file with things unrelated to themes can be confusing.

**Comment by mkkeck** [comment]
@oandregal Hi André,
the main reason was for adding extra configs for the theme like social services with the https://github.com/WordPress/gutenberg/issues/19041#issuecomment-921784434

**Comment by oandregal** [comment]
Thanks for sharing, Michael. This is a topic that have popped up lately in a few PRs and issues. I feel it merits discussion in a centralized place. Created https://github.com/WordPress/gutenberg/issues/35114

**Comment by ramonjd** [comment]
Going to close this given that it's "technically" possible and https://github.com/WordPress/gutenberg/issues/35114 to add anything to theme.json.

Social icons related discussions can remain on https://github.com/WordPress/gutenberg/issues/19041 or in the Icon registration discussion:

- https://github.com/WordPress/gutenberg/discussions/53510

Feel free to reopen if you think this specific feature is still more widely relevant.

Thanks!
