### ISSUE TITLE
More flexibility of date formats in Post Date block

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34762]
## What problem does this address?

There are many (non US centric) ways to format a date. The Post Date block locks you into 3 choices.

<img width="432" alt="Screen Shot 2021-09-11 at 22 34 09" src="https://user-images.githubusercontent.com/444434/132962160-39deccc0-129d-4871-bea5-ccf4af31030b.png">

## What is your proposed solution?

Provide more date options.

Alternatively - for full flexibility - allow user to provide date format using some standard notation such as ~[that which PHP uses to format dates](https://www.php.net/manual/en/datetime.format.php)~ that which is already in use [within `Settings -> General` under the `Date Format` section](https://wordpress.org/support/article/formatting-date-and-time/).

**Comment by Sandstromer** [comment]
The date format options seems to be locked into the Site Language setting.

For example switch language from English (United States) to English (UK), and notice the available formats of the Post Date block change to day month year ordering.

So yes I too could see circumstances where a site owner may want to use e.g. English (United States) but have the post dates in another language format.

**Comment by torounit** [comment]
This issue seems to have been resolved in #39209, closed.
