### ISSUE TITLE
Why Block Template uses HTML Comment Syntax?

### ISSUE THREAD

**Issue by ngdangtu-vn** [WordPress/gutenberg#34764]
## What problem does this address?
I have a visual, semantical problems with HTML Comment Syntax:

```HTML
<!-- wp:blabla -->
<html> content bla bla </html>
<!-- /wp:blabla -->
```

To me, comment should always be comment. Even though I'm aware that this is not something new and has been used a lot in C, C++ and Rust (especially for WASM). But those are totally difference branch of languages. So using comment as sub notation syntax can be readable. However this is not the case for HTML. With this kind of usage, we don't have nesting, longer syntax, a big mess between genuinely comment and notation comment.

If I work alone, nesting could be no problem since I can avoid formatters. I can chunk the long syntax to many lines. I can do that but... What happens if we work as a team. Sb's definitely not happy to not using any formatter. They will dumb shit and as the result... you can find some themes that fully support FSE and get the feeling...

## What is your proposed solution?
I would like WP support XML. It should be a great choice since XML and HTML was supported [generally by default](https://www.php.net/manual/en/xml.installation.php) in PHP.

```XML
<?xml version="1.0" encoding="UTF-8"?>
<!-- no need for html root tag, wp:template will convert all the custom attrs like lang to html attr because the wp:template should not have and special attr aside namespace attr -->
<wp:template xmlns:wp="https://wordpress.org">
  <!-- always use absolute path with root as the theme dir -->
  <wp:use src="templates/header"/>
  <wp:query name="p" post-type="post">
  <!-- or like this: -->
  <!-- <wp:query load-params="query/main.json"> -->
    <article id="wp:p.id">
      <wp:print content="wp:p.content"/>
    </article>
  </wp:query>
  <wp:use src="templates/footer"/>
</wp:template>
```

Even though it has a small down side, XML is much more powerful for this task so I sincerely hope we can go with this approach.

Downside:
- XML must be convert to html so Js can start to do it job on client. It will take time to convert back HTML notation comment for Js to work (if I understand the HTML Comment Syntax correctly).
- Conflict with XML file that is intended to sent directly to clients. Even though it is not serious problem, it still take a bit of time for wp to check which files to send or not.

The 2 downside points could make the process slower a little bit. But for visitor we can always use cache to increase the speed. For editor/admin... maybe we can use the power of client to [convert XML](https://developer.mozilla.org/en-US/docs/Web/Guide/Parsing_and_serializing_XML)?

**Comment by tellthemachines** [comment]
Good question! You can find an overview of the technical decisions behind the block editor [here](https://make.wordpress.org/core/2017/01/17/editor-technical-overview/), and there's also a snippet in [the FAQ](https://developer.wordpress.org/block-editor/explanations/faq/#how-is-data-stored-ive-seen-html-comments-what-is-their-purpose) that might be of interest.

I'm going to go ahead and close this issue as, if nothing else, the need for backwards compatibility means it's too late in the game to change such a structural aspect of the editor now.
