### ISSUE TITLE
Ability to assign a custom label to Group blocks

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34760]
## What problem does this address?

Group blocks are often used to build up the structure of a website. You can even change the tagname to be `<section>` (or various other structural elements).

Currently in List View it can be difficult to remember which Group represents which part of the page. 

## What is your proposed solution?

It would be nice to be able to assign an arbitrary label to a Group block in order to "mark" it within your UI as representing some specific piece of content.

For example, I might name the top of my site masthead as `Site Masthead`. This should then show up in the list view as the primary label, perhaps with the name of the _block_ in parenthesis next to it.

**Comment by richtabor** [comment]
Here’s what I’ve proposed: https://github.com/WordPress/gutenberg/issues/33583

**Comment by getdave** [comment]
Thanks @richtabor. I'll close in favour of #33583.
