### ISSUE TITLE
Block supports: margin/padding controls not showing in the Block Editor when enabled at theme.json settings block level.

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#34766]
### Description

Setting `customMargin` and/or `customPadding` to `true`  in `settings.blocks[ $block_name ].spacing` in theme.json has no effect in the Block Editor when trying to enable spacing block supports.

### Step-by-step reproduction instructions

Enable margin and padding spacing support for the Group Block in `packages/block-library/src/group/block.json`, e.g., 

```json
"supports": {
        ...
	"spacing": {
		"padding": true,
		"margin": true
	},
```

Enable block supports specifically for Group Block in theme.json, e.g.,

```json
"settings": {
   ...
   "spacing": {
	"customMargin": false,
	"customPadding": false,
	"units": [ "px", "em", "rem", "vh", "vw", "%" ]
   },
    ...
    "blocks": {
        "core/group": {
		"spacing": {
			"customMargin": true,
			"customPadding": true
			}
		},
```

Note that we've disabled `customMargin` and `customPadding` at the root level of settings.

In the Block Editor, insert a Group Block, then toggle the spacing controls under the Dimensions Panel.

See that padding/margin controls are enabled, but they don't appear when toggling using the Tools Panel.

### Screenshots, screen recording, code snippet

![spaced-out](https://user-images.githubusercontent.com/6458278/133069612-46536432-7249-49cf-a073-c139594b8aa8.gif)

I haven't backtraced everything fully yet, but I suspect that we're not merging the block-level settings somewhere correctly (?)

### Environment info

WordPress 5.8
Gutenberg 11.5
TT1 Blocks and Twenty Twenty One

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
cc @oandregal who might just know what's going on off the top of his head! 😆 

also cc @aaronrobertshaw who noticed this problem as well and helped me test.

**Comment by aaronrobertshaw** [comment]
I can't yet speak to what the exact issue or cause is but I can add some extra details around what I've seen so far.

- I believe the settings within the block editor store are correct
- Logging out the block specific values from `useSetting` begins as `true` then flips to `false`
- This change appears to be because we lose the `blockName` from the block edit context and end up with a malformed path
- This could be due to the current approach injecting the controls into the dimensions panel via a slot that doesn't bubble virtually.
- I've not replicated the issue yet while testing with a [separate PR](https://github.com/WordPress/gutenberg/pull/34725) working to make the dimensions panel slot bubble virtually.

I'll continue debugging and testing this tomorrow if no one finds a solution before then.

**Comment by ramonjd** [comment]
> I've not replicated the issue yet while testing with a separate PR working to make the dimensions panel slot bubble virtually.

Aside from the reducing spacing around the input controls, it works as expected using #34725

![noice](https://user-images.githubusercontent.com/6458278/133172057-bd46f9aa-c4bd-4e5f-8099-ed5da1aadfc1.gif)

> This could be due to the current approach injecting the controls into the dimensions panel via a slot that doesn't bubble virtually.

Sounds like you're on to something. When I set `bubblesVirtually` to `true` on the [InspectorControls.Slot](https://github.com/WordPress/gutenberg/pull/34725/files#diff-068538657061c47f0a58cfc331259bbeabe11bcc0c576a0cc496d262e5b0038cR134) the Tools Panel Item hook kicks in and starts wanting to use ToolsPanelContext properties.

**Comment by aaronrobertshaw** [comment]
> Aside from the reducing spacing around the input controls, it works as expected using #34725

There is a separate component for the [virtual bubbling Slot](https://github.com/WordPress/gutenberg/blob/5cca2e1a8021679aaf2fc713c1a2c1cce168c374/packages/components/src/slot-fill/bubbles-virtually/slot.js) which introduces a `<div>` so it can apply refs etc. This `div` breaks the layout for the `ToolsPanel` as shown in your screenshot. For a quick fix, I'll work on updating the ToolsPanel to handle that `div`.

**Comment by ramonjd** [comment]
Retested  now that #34725 is merged. I can no longer replicate. 👍
