### ISSUE TITLE
Link with one line looks out of line in interface on navigation

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#34779]
The link looks out of line with the icon on the link screen. I saw this on Chrome running the latest build. I am aware it might be due to not having 2 lines of text, but when one line is there it looks a little weird visually.

![2021-09-13 at 13 12](https://user-images.githubusercontent.com/253067/133081373-ab230d05-dae4-4965-ab06-b7c49592f882.png)

**Comment by getdave** [comment]
@karmatosed do you have a suggestion for how we handle such cases? Would you prefer that if there is only a single line that the icon and the text are aligned centrally?

**Comment by getdave** [comment]
I think this is probably an edge case. Adding a valid link almost always ends up with multiple lines. 

@karmatosed please could you advise on:

- how you can replicate this situation as a regular user
- your suggestions for how to handle such cases

Much appreciated 🙇‍♂️

**Comment by annezazu** [comment]
I'm going to close this out since there hasn't been follow up. I tried to replicate but the current nav screen with GB 12.5.3 and WordPress 5.9 isn't quite usable right now. Feel free to re-open if this needs to be re-addressed. 

>Would you prefer that if there is only a single line that the icon and the text are aligned centrally?

I think that is the gist fwiw :)
