### ISSUE TITLE
[Navigation Block] Add option to use the "responsive menu" at all times

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#34783]
Sometimes a site may want to hide menu items behind a hamburger even on large screens. When "Enable responsive menu" is active, we should add an additional checkbox that lets users enforce that behavior. 

Example:

![Video Theme 2](https://user-images.githubusercontent.com/1202812/133093784-8475c3ed-cd6a-42f9-93f3-6f9bdd2fb12d.jpg)

_I was sure there was another issue for this, but I couldn't find one. Feel free to close if I'm mistaken!_

**Comment by karmatosed** [comment]
Oh my goodness yes +1 and so many +1's! I actually found myself this week thinking about how to do this in the code so would love this feature, thank you @kjellr for creating the issue 🙌🏻

**Comment by jasmussen** [comment]
Partially tracked in #30370, but I've turned that one into an overview issue, because this feels small enough that it's worth splitting out anyway and fixing.

**Comment by jasmussen** [comment]
CC: @vcanales, happy to pair on this one.

**Comment by carolinan** [comment]
so many +++ :)
