### ISSUE TITLE
Allow clearing / removing the media.

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#34796]

**Comment by stacimc** [comment]
When a user adds the Site Logo block and uploads an image, it is possible to _replace_ the image but not to clear/remove it:

<img width="308" alt="Screen Shot 2021-09-14 at 11 36 23 AM" src="https://user-images.githubusercontent.com/63313398/133314702-1c3d5894-a32f-426e-b880-256d4fc7e700.png">

If the user deletes the block, the Site Logo will still be persisted (assuming they saved before deleting). To clear the logo they have to go the Customizer -> Site Identity view, which may not be obvious.

<img width="301" alt="Screen Shot 2021-09-14 at 11 39 53 AM" src="https://user-images.githubusercontent.com/63313398/133315146-40f9c27d-84c2-45d0-89f4-0fa68030f7d5.png">

It would be nice to have a similar option to clear the media from within the block.

**Comment by apeatling** [comment]
🎉
