### ISSUE TITLE
Buttons on placeholders lack space

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#3480]
Visual regression:

![image](https://user-images.githubusercontent.com/548849/32787959-3e9a420c-c958-11e7-8bdc-5a874d320070.png)

Before:
![image](https://user-images.githubusercontent.com/548849/32788476-90085c7c-c959-11e7-83e4-c72fc6254c56.png)

cc @jasmussen @karmatosed

**Comment by karmatosed** [comment]
I am seeing this in Chrome..

![2017-11-14 at 15 44](https://user-images.githubusercontent.com/253067/32789099-dbd4f1e4-c952-11e7-9c57-ede34ff4582a.png)

Same with Safari.

**Comment by mtias** [comment]
Also seeing it in the save draft button:

![image](https://user-images.githubusercontent.com/548849/32789303-c6f6f020-c95b-11e7-9328-707e755c2855.png)
