### ISSUE TITLE
Update @wordpress/create-block documentation to explain usage of npx.

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/gutenberg#34822]
## What problem does this address?
The existing documentation for the `create-block` package does not explain what `npx` is or why it is being used instead of `npm`. This may be confusing to some users who are not familiar with the node ecosystem.

## What is your proposed solution?
A short explanation on why npx is correct for this usage with a link out to some official documentation such as https://docs.npmjs.com/cli/v7/commands/npx

**Comment by gziolo** [comment]
Initially `npm init @wordpress/block` was the promoted command, but it has some limitations so we landed on using `npx` in all places. @mkaz, should we add a section about `npx` in JS tutorial and only link in `@wordpress/create-block`?

**Comment by mkaz** [comment]
I suppose it's fine, I would not add it to the Quick Start section, but a short sentence in the other section.

To a certain degree I have an expectation that if people want more information they can Google it. The docs do mention right before requiring a node environment installed, so to me that connects the command as part of Node, but probably better to be explicit.

I'm never sure if giving more information overloads and takes away from the part we're trying to teach them. The key is type this command and it will create a block placeholder. Start talking about remote packages and node executable packages is veering away from starting with blocks.
