### ISSUE TITLE
Gutenberg Templates of post_type wp_template fullsite editor can't update slug( )

### ISSUE THREAD

**Issue by mrkunau** [WordPress/gutenberg#34841]
### Description

I'm working on fse with wordpress 5.9-alpha-51813 and Gutenberg Version 11.4.1 but can't update slug(post_name) on post type 'wp_template'

/wp-admin/edit.php?post_type=wp_template 
add new a custom template then change slug on input field then Update.
please look video : https://gyazo.com/2e9bb766e8e40c9528199d643fbcadd9
After saved then reload edit post slug is don't update

What do I need to do to update the slug ? please help me. Thanks!

### Step-by-step reproduction instructions

Go to : /wp-admin/edit.php?post_type=wp_template
Click Addnew a template
Change slug in input Slug on right metabox
Click Update then reload edit post again ( slug is don't save )

### Screenshots, screen recording, code snippet

https://gyazo.com/2e9bb766e8e40c9528199d643fbcadd9

### Environment info

Wordpress 5.9-alpha-51813 
Gutenberg Version 11.4.1
Theme FSE

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carlomanf** [comment]
#32861 might be the same issue.

**Comment by mrkunau** [comment]
> #32861 might be the same issue.

Yes - i think so, same issue. 
We must add category-{post_type}.html then push to block-template folder in theme , edit it using SiteEditor and that will create new template with category-{post_type} slug, this is so inconvenient.
Thank you @carlomanf !

**Comment by annezazu** [comment]
Closing this out as a duplicate :)

**Comment by mrkunau** [comment]
> Closing this out as a duplicate :)

Thanks @annezazu ! Looking forward to the fix update soon.
