### ISSUE TITLE
Using a single non-pixel value for settings.spacing.units reverts to pixels

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#34848]
### Description

Setting an array with `settings.spacing.units` containing a single value which is not "px" shows "px" next to the input field, and the values are in pixels. This makes it impossible to set the control to only allow e.g. REM.

### Step-by-step reproduction instructions

1. Set `settings.spacing.units` to `["rem"]`
2. Interact with the block spacing control. The indicator says "px" and the value from the field is applied as pixels.

### Environment info

- WordPress 5.8.1. 
- Gutenberg plugin not in use.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi!
With current trunk of Gutenberg **enabled**:

I tested this with the group block and site title, the spacing control is not displaying any unit until I change the value, 
and then it displays the rem unit.

-When I tested with a block that had a padding already set in the block markup (in the HTML template file),
it showed the numeric value inside the setting, but no unit showed until I made changes to that field.

Can you tell me which editor (block, template) and block(s) you tested with? Then I can retest but it sounds like it may have been fixed already.

**Comment by markhowellsmead** [comment]
Is working as expected with the Gutenberg plugin (which we can't use).

**Comment by carolinan** [comment]
Updates will be ported to WP eventually :)
