### ISSUE TITLE
Remove Block label: Update to include the name of the block to be removed

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#34863]
## What problem does this address?

During testing of the new refactored Gallery block, it was reported that going to remove an image from the gallery, in the drop-down menu the label "Remove block" can be confusing — the feedback was, how can you be sure that the block you're about to remove is the Image block?

This is the view:

![image](https://user-images.githubusercontent.com/14988353/133553193-46746fba-8398-4f5b-85c8-20f8910d2fa0.png)

## What is your proposed solution?

The proposed idea was to update the label for "Remove block" to include the name of the current block. So, for an image block within a gallery, the user would see "Remove Image", but if the Gallery is selected, it would read "Remove Gallery".

I imagine this could be useful for a number of situations where container blocks are in use, so ensuring that a user can tell when they're deleting a Button block versus the Buttons block, etc.

On the other hand, perhaps having a single "Remove block" item in the menu gives a predictable label, so I'll add a Discussion label for this enhancement idea.

**Comment by carolinan** [comment]
I would love to see this for all blocks: https://github.com/WordPress/gutenberg/issues/30740

**Comment by andrewserong** [comment]
Thanks @carolinan, glad to hear there's others who'd like this feature, too! Since your issue pre-dates this one, I'll close this as a duplicate 🙂

**Comment by andrewserong** [comment]
Closing as duplicate. Let's track the work in #30740 instead.
