### ISSUE TITLE
Add <meta charset="utf-8"> on copy / paste

### ISSUE THREAD

**Issue by emendo-web** [WordPress/gutenberg#34867]
### Description

When you made a copy / paste. Gutenberg add a meta tag charset in the content. Test with header, paragraphe, ...

There is already a issue open for this in block link : #33585 
But concerne a lot of block.

### Step-by-step reproduction instructions

1. Create a paragraphe or title block
2. Write text
3. Create a new block paragraphe or title
4. copy then content of the first block in the second one
5. Display "Code editor"
6. You should see `<meta charset="utf-8">` where you paste your text

### Environment info

- Wordpress 5.8.1
- Also test by installed the last gutenberg plugin 11.4.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by camilopbam** [comment]
I'm also getting this same issue on a fresh WP 5.8.1 site with both custom themes and Twenty Twenty-one.

**Comment by camilopbam** [comment]
Wanted to add that this issue seems to be happening only on Chromium-based browsers. Firefox and Safari are safe.

**Comment by JohannesHoppe** [comment]
I can confirm this bug, it's super annoying...

**Comment by gVee** [comment]
I'm sure that happened when coping **something from a block** and paste into another.And I suggest that we take this issue as a [Bug]

Testing on **something from a block**：

- Header(h2, h3....)
- Paragraphe(p)
- List(ul, ol...)
- Quote(blockquote)

### Environment info
Wordpress： 5.8.1
OS：MacOS 11.4
Browser：Chrome 95.0.4638.54(arm64)

I have some suggestion on issue : #33585

**Comment by markhowellsmead** [comment]
Same here, appears everywhere in the block editor when copying/pasting. Appears to be <s>resolved</s> in discussion by #36356.

**Comment by camilopbam** [comment]
This seems to be fixed on WP 5.9

**Comment by skorasaurus** [comment]
Hi, 
I'm not able to reproduce this in WordPress 5.9.3 either in chrome; please reopen and comment if you are still experiencing this.
