### ISSUE TITLE
Since Gutenberg updated editing order of pictures in a gallery no longer works

### ISSUE THREAD

**Issue by SeanFordyce** [WordPress/gutenberg#34896]
### Description

I am wondering if other people are having the same issue. The arrows in a gallery allowing you to change the order of pictures in a gallery no longer work for me since the latest update today 9/16/21. I am wondering also if there is a planned fix as I can no longer edit the picture order in my galleries. This is an issue that started today and is an incompatibility with ultimate addons for Gutenberg
Thanks

### Step-by-step reproduction instructions

When you click on a gallery, arrows appear over the pictures. Now they do not move the picture within the gallery as they used to.
This is only when ultimate addons for Gutenberg is activated

### Environment info

Wordpress 5.8.1 
Gutenberg11.5.0
Astra theme
Relevant Plugin: Ultimate add-ons for Gutenberg
This stopped working with the latest Gutenberg update today
I use a windows 10 machine and Chrome for editing my site.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hi @SeanFordyce, I just tested and this seems to be a conflict between Ultimate add-ons for Gutenberg and the newest version of Gutenberg. If you uninstall the plugin, the issues go away. Therefore, I would submit a support ticket in their [support forum](https://wordpress.org/support/plugin/ultimate-addons-for-gutenberg/) on WordPress.org. The plugin author will need to fix in their plugin.

**Comment by annezazu** [comment]
Thanks for chiming in here @ndiego! Based on the above response, I'm going to close this out after adding a few labels :)

**Comment by SeanFordyce** [comment]
Thank you!
