### ISSUE TITLE
Idea: Smart Text Block

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#349]
Could we potentially view Text, List, Tables, and Headings as different twists on the same thing? As contained in a "Smart Text Block" (aka TinyMCE with some UI changes).

Underneath the hood, a Smart Text Block would behave slightly differently than the regular blocks but, to the user, it would feel the same. It would look seamless with the Gutenberg experience. For example:
- the Type Indicator would switch a paragraph to a list inside the Text Block, not create entirely new blocks
- the toolbars would adjust to the context
- there would be a sidebar hover indicator
- elements within the text block would have drag and drop
- etc.

Copy/paste, undo/redo, and a lot of the simple text interactions (#179) would work much better within the Smart Text Block. There would be more of a _type type type_ experience.

**Why?**
A Smart Text Block would cope much better with unstructured/legacy content and content imported from elsewhere yet would retain the overall user experience of Gutenberg. It will also work much better on mobile devices once we get to that.

This picks up on the conversations in #335 and #346 . In particular this image from @annaephox 

![image](https://cloud.githubusercontent.com/assets/2160304/24476852/c83f470c-1489-11e7-9215-d3a3ebdbb50d.png)

**Comment by jasmussen** [comment]
Linking discussion that happened here also: https://github.com/WordPress/gutenberg/pull/335#issuecomment-290060865

Great ticket.

**Comment by Afraithe** [comment]
I like to think of it as "formatting blocks" and "complex blocks". So TinyMCE would handle the formatting blocks such as image, lists, tables. And then we have more complex blocks that usually are a combination of elements, such as image caption, video embed, image gallery etc, that would be handles by the block api (outside in the current context, but via our block api, possible inside of tinymce as well). I think this will make the _type type type_ experience not so different from current solution and easier to implement as well. Now it might still look very "blocky" to the user, wether the block is "inside" or "outside" of tinymce in this case, the look and feel could be the same.

**Comment by jasmussen** [comment]
So a bunch of exciting things going on at the same time. So as to not duplicate work, let's zoom out a bit.

It looks like #358 overlaps @iseulde work on #347, but there is also overlap between the "Smart Text Block" concept and @aduth work on #335. That's not to say those are bad — it's good that we are thinking in the same directions, we just need a little coordination. 

Zooming out: we need a block that is very close to the current editor, but with UI changes (not an overwhelming amount of buttons and a kitchen sink). We need this block to load old posts, and unparsable blocks. This is essentially the block proposed here, and the very same block that @aduth has started work on in #335. A user will be able to use this block the same way the editor works now, but won’t have the advantage of having controls specific to the block.

We've had many names for it. Generic, Fallback, Unknown, Smart Text, HTML Block, Visual Editor Block. For now, let's call this **Freeform Block**, until such a time as we can find a better name (and I encourage your suggestions). 

This block is not the `Editable` component which is wrapping TinyMCE and is used by several blocks to display editable areas. 

Maybe @aduth can bootstrap this block in #335 and open it to improvements?

CC: @youknowriad does this read right to you? 👆

**Comment by androb** [comment]
How about "Writer's Block" ... or is that too punny? 🤓

**Comment by jasmussen** [comment]
😂

🌟🌟🌟🌟🌟 👏

**Comment by jasmussen** [comment]
Should we close this in favor of #365?

**Comment by jasmussen** [comment]
Closing in favor of #365.
