### ISSUE TITLE
Template name and description in editor too close together in dropdown

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#34936]
When you use the dropdown to see the template name and description, both are very close together.

![2021-09-17 at 19 21](https://user-images.githubusercontent.com/253067/133836172-bc7b4b05-ab58-4b39-9869-87b077f90b45.png)

My recommendation would be to just add a single space between them to give some breathing room.

![2021-09-17 at 19 25](https://user-images.githubusercontent.com/253067/133836349-03450334-17f4-485d-b525-5f7b70584410.png)

This was seen using the latest version, TT1 blocks and Chrome. I add the theme just in case that's impacting anything here. I will add bug as a label because it makes it very hard to comprehend what is going on without the space.

**Comment by Mamaduka** [comment]
Thanks for creating this issue. Missing space has been bugging me for a while now, but I always forgot to create PR.

What do you think about the `4px` margin-left on the description element?
