### ISSUE TITLE
Post terms block shows post not found multiple times

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#34937]
Whilst showing that a term doesn't exist is great information, I am unsure it's good repeating it. For example, you can have the following if you view default TT1: 

![2021-09-17 at 19 32](https://user-images.githubusercontent.com/253067/133837236-3559bdb5-fe18-487b-a06e-cd8b9db606d0.png)

My recommendation would be to only show once this message as it seems to not require multiple instances. I think an argument might be able to be had for multiple if there is also other content being shown, but in this case, there isn't, it's only showing those 2. I also might be wrong and there's something else going on here.

**Comment by carolinan** [comment]
I think the title confused me; The post term block does not display the message twice, correct? 
But the theme has two post terms blocks, one for the tags and one for the categories.

Inside a loop, it correctly displays "No tags" and so on.

**Comment by ntsekouras** [comment]
Thanks for reporting @karmatosed! I'm going to close this one as the behavior was expected, as @carolinan explains above, and also it seems it has been [resolved here](https://github.com/WordPress/gutenberg/pull/35517), in the way that we have moved forward with a unification of theme blocks placeholder content.

Feel free to reopen if you think we need to take some alternative approach.
