### ISSUE TITLE
Headings in the site editor navigation sidebar

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#34959]
At some point it seems that a regression has occurred with the appearance of headings in the site editor navigation sidebar. We currently have two different styles:

<img src="https://user-images.githubusercontent.com/846565/133994374-2983591d-df8b-4003-bd58-0a61a93dcbf2.gif" width="284">

Looking back at the original designs, the [titleSmall](https://github.com/WordPress/gutenberg/blob/570678931afd73ffcdb9cdfa39c1c371f984242a/packages/components/src/text/styles/text-mixins.native.js#L26) type style should be utilised for both.

**Comment by zaguiini** [comment]
@jameskoster, I have a question on https://github.com/WordPress/gutenberg/pull/36009. Please take a look when possible!

**Comment by paaljoachim** [comment]
I made a 9 minute video where I in general go through the FSE sidebar menu:
https://youtu.be/EtGr1Uld1b4

Example.
Going to Page Templates. There is no obvious heading and Page templates become a part of the content. Like so:

![Screenshot 2021-10-28 at 14 25 00](https://user-images.githubusercontent.com/5323259/139254688-4d9890d7-502e-41dd-b267-f63d0f3c551f.jpg)

Having Page templates as a heading that stands out compared to other items in this screen will very much help. As one would clearly see that one is in the Page templates section.

The same goes for various other sections as well.

**Comment by creativecoder** [comment]
Resolved by #36009
