### ISSUE TITLE
Only show one + at a time on link adding

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#34962]
It can get very confusing within in the link adding interface if you have more than one + showing, for example:

![2021-09-20 at 13 41](https://user-images.githubusercontent.com/253067/134004053-2c9fee46-d35b-4f85-9c7c-519cd499af4e.png)

I saw this on Chrome adding a submenu and hovering over the item below where that is. My recommendation would be to only allow one + at a time.

**Comment by javierarce** [comment]
I haven't been able to reproduce this issue… if someone could confirm that, I think that we could close this ticket.

**Comment by jordesign** [comment]
Closing this as I can no longer recreate it in WP6.3
