### ISSUE TITLE
Embedded Content Block

### ISSUE THREAD

**Issue by darrencoutts118** [WordPress/gutenberg#3497]
## Issue Overview

Version 1.7 - This does not look quite right to me? The top links needs some styling or removed.

![image](https://user-images.githubusercontent.com/9951843/32841068-5278ed3c-ca11-11e7-91b1-d47dcc843807.png)

## Steps to Reproduce (for bugs)

1. Install Version 1.7
2. Edit the demo page
3. See the last block
4.

## Expected Behavior

Visual could look better than it currently does

## Screenshots / Video

![image](https://user-images.githubusercontent.com/9951843/32841123-72620548-ca11-11e7-9ee1-b9f80b8cbbba.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by swissspidy** [comment]
Check out http://develop.svn.wordpress.org/branches/4.9/src/wp-includes/js/wp-embed.js for how these embeds should be handled.

Probably just need to embed this script. It does a bit more than just 041faab9305d1bfd967a92b4d862ce6d6d3d7a63.

**Comment by aduth** [comment]
@swissspidy @imath Can this be considered closed by #4226?

**Comment by imath** [comment]
Hi @aduth Yes, the top link is no more showing now.
