### ISSUE TITLE
Multiple RichText with same tagName making conflict

### ISSUE THREAD

**Issue by mhsohag11** [WordPress/gutenberg#34982]
### Description

I have adde two RichText block with same tagName. Everything is fine and data also saved properly. But when I reload the page , console error have been showing with this message ( **This block contains unexpected or invalid content.**)
If I used different tagName for both RichText no problem occurred .
Codes : 

`
import { registerBlockType } from '@wordpress/blocks';

import {
    RichText,
    useBlockProps,
} from '@wordpress/block-editor';

registerBlockType( 'rul-gb/call-to-action', {
    title: 'Call to Action',
    icon: 'image-filter',
    category: 'common',
    classNamewords: [ 'cta','call to action' ],
    attributes: {
        title_one: {
            type: 'string',
            source: 'html',
            selector: 'h2',
        },
        title_two: {
            type: 'string',
            source: 'html',
            selector: 'h2',
        },
    },

    edit({ attributes, setAttributes }) {
        const blockProps = useBlockProps();

        return (
            <div>
            <RichText
                {...blockProps}
                tagName="h2"
                value={attributes.title}
                allowedFormats={['core/bold', 'core/italic']}
                onChange={(title_one) => setAttributes({ title_one })}
                placeholder="Title One"
                className="item-one"
            />
            <RichText
                {...blockProps}
                tagName="h2"
                value={attributes.title_two}
                allowedFormats={['core/bold', 'core/italic']}
                onChange={(title_two) => setAttributes({ title_two })}
                placeholder="Title Two"
                className="item-two"
            />
            </div>
        );
    },

    save({ attributes }) {
        const blockProps = useBlockProps.save();

        return (

            <div>
                <RichText.Content {...blockProps} className="item-one" tagName="h2" value={attributes.title_one} />
                <RichText.Content {...blockProps} className="item-two" tagName="h2" value={attributes.title_two} />
            </div>

        )
    }
} );`

Console Error : 

> blocks.min.js?ver=7ed7fe32dad771c4e0af4f56539ff156:2 Block validation: Block validation failed for `rul-gb/call-to-action` ({name: 'rul-gb/call-to-action', icon: {…}, keywords: Array(0), attributes: {…}, providesContext: {…}, …}).
> 
> Content generated by `save` function:
> 
> <div class="wp-block-rul-gb-call-to-action"><h2 class="item-one">One</h2><h2 class="item-two">One</h2></div>
> 
> Content retrieved from post body:
> 
> <div class="wp-block-rul-gb-call-to-action"><h2 class="item-one">One</h2><h2 class="item-two">Two</h2></div>

### Step-by-step reproduction instructions

1. Same tagName making issue for multiple RichText

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
The first issue is that in your edit function, the first RichText has the `value` of `attributes.title`, it should be `attributes.title_one`.

The second issue is that in your attribute declaration, the two attributes use the same `selector`, it's worth thinking of these like CSS selectors, those selectors need to be able to select the correct individual elements from your save function, e.g. `h2.item-one` and `h2.item-two`.

**Comment by mhsohag11** [comment]
Thank you @talldan for your valuable response 👍
First issue is my typing mistake :)

The second issue is the main part and finally **I have solved my problem**  

Just need to individual identifier  in selector :  ( Example Below )

```
    attributes: {
        title_one: {
            type: 'string',
            source: 'html',
            selector: 'h2.item-one',
        },
        title_two: {
            type: 'string',
            source: 'html',
            selector: 'h2.item-two',
        },
    },
```

>  selector: 'h2.item-one',
> 
>  selector: 'h2.item-two',
