### ISSUE TITLE
Improve unit test coverage for REST API menus endpoints. 

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#34992]
#### Background
The menus endpoints, menu, menu locations and menu items were originally worked on by @spacedmonkey and developed in [another](https://github.com/WP-API/menus-endpoints) github repo. These endpoints, were merged into this plugin in https://github.com/WordPress/gutenberg/pull/20292. 

Now that the menus endpoints are being used for the menu screen. There have been a number of changes to the REST API endpoint over the last couple of months these changes include. 

#31656, #34673, #34888, #34835

Let's audit and improve PHPUnit test coverage for these endpoints.

**Comment by anton-vlasenko** [comment]
Let's consider adding these unit tests as well: https://github.com/WordPress/gutenberg/pull/34857/commits/5b6c2d2b47b71fc6801165c7967f1f7baa97e317
Discussion can be found here: https://github.com/WordPress/gutenberg/pull/34857
