### ISSUE TITLE
Comments Query Loop block

### ISSUE THREAD

**Issue by SantosGuillamot** [WordPress/gutenberg#34996]
## Description

An advanced block that allows displaying the comments of a specific post based on different parameters and visual configurations. It should be similar to the [Query Loop block](https://wordpress.org/support/article/query-loop-block/).

This block is part of the Post Comments Loop block, for more context please visit this [Tracking Issue](https://github.com/WordPress/gutenberg/issues/34994) or its [GitHub project](https://github.com/WordPress/gutenberg/projects/61).

## Potential Settings

- **Layout settings**: It should be similar to the ones in the [Query Loop](https://wordpress.org/support/article/query-loop-block/#query-loop-settings).
    - It can inherit the default layout or change the width and content.
    - It could be nice to be able to select the content and width (or the padding) of the child comments.
- **Color settings:** It should be the same as the [Query Loop](https://wordpress.org/support/article/query-loop-block/#query-loop-settings).
- **Loop settings:**
    - Order by: There is a [Discussion Setting](https://wordpress.com/support/settings/discussion-settings/#other-comment-settings) to select the order of the comments. I guess we should use this by default unless they change it in the Comment Loop block.
- **List view settings**. We can replicate the settings in the [Query Loop](https://wordpress.org/support/article/query-loop-block/#block-toolbar-options):
    - Items per page: There is a [Discussion Setting](https://wordpress.com/support/settings/discussion-settings/#other-comment-settings) to select how many top level comments users want per page. I think we should respect that unless it is changed in the block itself.
    - Offset.
    - Max pages.
- **Advanced settings:** We can replicate the behaviour in the [Query Loop](https://wordpress.org/support/article/query-loop-block/#advanced-settings):
    - HTML element: Allow users to select if they want a `<div>` , `<section>` , `<aside>` HTML element.

## References

- This should be similar to the Query Loop block: [Guide](https://wordpress.org/support/article/query-loop-block/) and [GitHub](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/query/).

**Comment by michalczaplinski** [comment]
Could you assign the issue to me @SantosGuillamot? It seem that I cannot do it myself as a contributor. Thanks!

**Comment by michalczaplinski** [comment]
Hi @jameskoster! Do you have a design for the icon for this block?

**Comment by jameskoster** [comment]
Ah, no we don't. It's probably safe to use the regular loop block for now, and we can explore design for a dedicated comment loop block later. I'm not 100% sure we need one.

Edit: Actually, the Post Comments icon might make more sense than the regular loop icon. It doesn't look as 'loopy' but will probably be adequate.

**Comment by gziolo** [comment]
This block needs more work so let's reopen the issue.

**Comment by SantosGuillamot** [comment]
Great! Is there any place to check which tasks are left to consider this issue done?

**Comment by gziolo** [comment]
The comment https://github.com/WordPress/gutenberg/pull/35231#issuecomment-952459025 from @michalczaplinski should be a good summary of what's left.

**Comment by michalczaplinski** [comment]
Continuing adding features and improvements to the Comments Query and Comment Template in https://github.com/WordPress/gutenberg/pull/36065
