### ISSUE TITLE
Post Comments Pagination block

### ISSUE THREAD

**Issue by SantosGuillamot** [WordPress/gutenberg#35007]
## Description

Displays a paginated navigation to next/previous set of comments, when applicable. This should be similar to the [Query Pagination block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/query-pagination).

This block is part of the Post Comments Loop block, for more context please visit this [Tracking Issue](https://github.com/WordPress/gutenberg/issues/34994) or its [GitHub project](https://github.com/WordPress/gutenberg/projects/61).

## Potential Settings

- **Color settings:** This should be similar to the [Query Pagination block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/query-pagination).
- **Pagination Arrow:** It allows users to select if they want none/Arrow/Chevron in the Next & Previous buttons. This should be similar to the [Query Pagination block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/query-pagination).

## Requirements

- This block should only be available inside the [Post Comments Query Loop Block](https://github.com/WordPress/gutenberg/issues/34996).
- If there is just one page, we shouldn't show the pagination.

## References

This should be similar to the [Query Pagination block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/query-pagination).

**Comment by DAreRodz** [comment]
Hey! I want to start working on this, could you assign this issue to me? Thanks. :blush:
