### ISSUE TITLE
wp-block-styles theme support seems to do nothing

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#35002]
### Description

I tested my custom theme with `add_theme_support( 'wp-block-styles' );` and without it, and it seems that nothing changes, the same amount of css files are loaded, the same amount of css rules applied.

If something is changed, I cannot notice it, so perhaps better explanation of the feature would be needed.

### Step-by-step reproduction instructions

Test wordpress site with `add_theme_support( 'wp-block-styles' );` in functions.php and without it

### Environment info

Irrelevant

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aristath** [comment]
Thank you for reporting this issue @Lovor01!
Is your theme a classic theme, or a block theme (FSE)?

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @Lovor01 hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
