### ISSUE TITLE
Post Comments Pagination Previous block

### ISSUE THREAD

**Issue by SantosGuillamot** [WordPress/gutenberg#35009]
## Description

Displays the previous comments page link. This should be similar to the [Query Pagination Previous block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/query-pagination-previous).

This block is part of the Post Comments Loop block, for more context please visit this [Tracking Issue](https://github.com/WordPress/gutenberg/issues/34994) or its [GitHub project](https://github.com/WordPress/gutenberg/projects/61).

## Potential Settings

- **Typography:** This should be similar to the [Query Pagination Previous block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/query-pagination-previous).
- **Color settings:** This should be similar to the [Query Pagination Previous block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/query-pagination-previous).

## Requirements

- This block should only be available inside the [Post Comments Pagination Block](https://github.com/WordPress/gutenberg/issues/35007).
- If there are no previous pages, we shouldn't show the button.

## References

This should be similar to the [Query Pagination Previous block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/query-pagination-previous).

**Comment by karmatosed** [comment]
I noticed this has the label for needs design and I want to help out with theme blocks. Regarding what it should support, a first feature set to me seems to be what is supported by query pagination block:

`
		"color": {
			"gradients": true,
			"link": true
		},
		"typography": {
			"fontSize": true,
			"lineHeight": true
		}`

I would also probably lean heavily on that for a design pattern, but wanted to check before dove in there what other thoughts might be around this (if any).

**Comment by SantosGuillamot** [comment]
> Regarding what it should support, a first feature set to me seems to be what is supported by query pagination block.

I totally agree, replicating the set used by the query pagination block seems fine to me.

> I would also probably lean heavily on that for a design pattern.

I agree with this as well 🙂 . I feel that having consistency between different blocks would be helpful for both the developers and the users.
