### ISSUE TITLE
Cannot add reusable block in widget

### ISSUE THREAD

**Issue by MatzeKitt** [WordPress/gutenberg#35004]
### Description

Despite the closed issue #22875 I cannot use the inserter to add a reusable block in a widget. Is it intended to work? If I search for a reusable block in the widget area, there is no block to select.

### Step-by-step reproduction instructions

1. Create a reusable block called "Reusable"
2. Go to the widget area.
3. Use the inserter and search for "Reusable"

### Environment info

- WordPress 5.9-alpha-51831
- Gutenberg 11.5.1
- Safari 15

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or reported at https://github.com/WordPress/gutenberg/issues/32952 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
