### ISSUE TITLE
Comments Template block

### ISSUE THREAD

**Issue by SantosGuillamot** [WordPress/gutenberg#35000]
## Description

Contains the block elements used to render a comment, like the content, date, or author for example. This should be similar to the [Post Template block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-template/).

This block is part of the Post Comments Loop block, for more context please visit this [Tracking Issue](https://github.com/WordPress/gutenberg/issues/34994) or its [GitHub project](https://github.com/WordPress/gutenberg/projects/61).

## Potential Settings

The settings should be the same as the [Post Template block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-template/).

## Requirements

This block should only be available inside the [Post Comments Query Loop Block](https://github.com/WordPress/gutenberg/issues/34996).

## References

- This should be similar to the [Post Template Block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-template/).
- Each block element will be handled in different issues:
    - Comment Author (**[Comment Author Block #30572](https://github.com/WordPress/gutenberg/issues/30572)**)
    - Comment Date (**[Comment Date Block #30573](https://github.com/WordPress/gutenberg/issues/30573)**)
    - Comment Content (**[Comment Content Block #30574](https://github.com/WordPress/gutenberg/issues/30574)**)
    - Comment Author Gravatar (**[Comment Author Gravatar Block #30575](https://github.com/WordPress/gutenberg/issues/30575)**)
    - Comment Reply Link (**[Comment Reply Link Block #30576](https://github.com/WordPress/gutenberg/issues/30576)**)
    - Edit Comment link (**[Edit Comment Link Block #30577](https://github.com/WordPress/gutenberg/issues/30577)**)

**Comment by michalczaplinski** [comment]
A stub of this block is created in the https://github.com/WordPress/gutenberg/pull/35231 PR.

**Comment by SantosGuillamot** [comment]
As mentioned in [this Pull Request](https://github.com/WordPress/gutenberg/pull/35743) and [this related issue](https://github.com/WordPress/gutenberg/issues/35732), we should consider how to handle when comments are closed in a post. If I understood it correctly:

* We should show a "Comments are closed" message if comments have been opened previously.
* We shouldn't show a "Comments are closed" message if comments haven't been opened previously. We could even include a setting to hide/show this message.

**Comment by gziolo** [comment]
Nit: I think that the name of the block should be Comment Template block to align with Post Template block. There is a plural form "Comments" in the title. It looks like we should have all blocks necessary for the template ready quite soon. Some blocks landed/were updated recently, the remaining are in progress but in very advanced stage.
