### ISSUE TITLE
Core themes throwing stylesheet was not properly added error.

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#35018]
### Description

~I'm not sure if this is expected behavior, but when inserting certain types of blocks we can see a "stylesheet was not properly added error" in console.~

Edit: So chatting with folks we do still support these themes, the console error is more of a warning to use a newer path.

Let's change the console.error to console.warn to make this less scary (deprecations typically show up as warnings vs error).

### Step-by-step reproduction instructions

1. Use one of the following themes (twentyten, twentyeleven, twentytwelve, twentythirteen, twentyfourteen, twentyfifteen, twentysixteen, twentyseventeen, and twentytwenty)
2. Add a block that has a styles block setting panel (image block, site-logo, social-links etc)
3. Make sure the sidebar is open and select the block
Expected: no js errors thrown
Actual:
<img width="1295" alt="CleanShot 2021-09-21 at 11 10 58@2x" src="https://user-images.githubusercontent.com/1270189/134224724-d44aa9aa-53a0-4303-9010-cc556ae327fd.png">

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1270189/134224669-dc52f333-74cc-4599-9c93-e30827e7cf22.mp4

### Environment info

Gutenberg trunk / wp-develop master

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gwwar** [comment]
Going to refile this in trac since we'll need theme updates

**Comment by gwwar** [comment]
Added https://core.trac.wordpress.org/ticket/54158#ticket

**Comment by gwwar** [comment]
So chatting with folks we do still support these themes, the console error is more of a warning to use a newer path. 

With that in mind I'll update the issue to change the console.error to console.warn to make this less scary (deprecations typically show up as warnings vs error).

**Comment by oandregal** [comment]
errors have been transformed into warnings at https://github.com/WordPress/gutenberg/pull/35914 so I presume we can close this now.
