### ISSUE TITLE
Post Comments Pagination Numbers block

### ISSUE THREAD

**Issue by SantosGuillamot** [WordPress/gutenberg#35010]
## Description

Displays a list of page numbers for comments pagination. This should be similar to the [Query Pagination Numbers block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/query-pagination-numbers).

This block is part of the Post Comments Loop block, for more context please visit this [Tracking Issue](https://github.com/WordPress/gutenberg/issues/34994) or its [GitHub project](https://github.com/WordPress/gutenberg/projects/61).

## Requirements

This block should only be available inside the [Post Comments Pagination Block](https://github.com/WordPress/gutenberg/issues/35007).

## References

This should be similar to the [Query Pagination Numbers block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/query-pagination-numbers).

**Comment by cbravobernal** [comment]
Maybe @javierarce could help us with the design.

**Comment by DAreRodz** [comment]
I'm planning to work on this issue, so I've assigned it to me.

@c4rl0sbr4v0, for the design, I'll keep the same of the Query Pagination Numbers block.
