### ISSUE TITLE
Singing header and footer Templates option to sign different post or page 

### ISSUE THREAD

**Issue by lwangdu** [WordPress/gutenberg#35012]
What problem does this address?
Right now there is no way to sign footer or header templates to different pages or posts like the main template from the WordPress dashboard.

What is your proposed solution?

Options 
Template Part from WP the dashboard: 
Option to sign to: footer1 or  footer3 or 
header1 or header2

**Comment by annezazu** [comment]
@lwangdu thanks for opening this issue! Do you mean there is no way to assign a footer or header template to different pages? Want to make sure I understand what you're asking :)

**Comment by carlomanf** [comment]
I could be wrong, but is this potentially the same request as #29173?

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @lwangdu hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
