### ISSUE TITLE
Edit page and edit event not working

### ISSUE THREAD

**Issue by ACBLDistrict21Webmaster** [WordPress/gutenberg#35022]
### Description

On about Sep 14, edit page and edit event quit working. The body of the browser window is blank.

The problem persists if activate only the Gutenberg plugin.

The problem resolves if deactivate only the Gutenberg plugin, though surely this will cause other problems.

Sample of edit-page page source attached (only Gutenberg plugin activated).

### Step-by-step reproduction instructions

1. Open WP admin.
2. Edit page, or edit event.

### Screenshots, screen recording, code snippet

[wp-page-edit.htm.txt](https://github.com/WordPress/gutenberg/files/7206618/wp-page-edit.htm.txt)

### Environment info

WordPress 5.8.1
Gutenberg plugin 11.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Can you share if there's an error message in your browser's console? 

You can access it by pressing pressing "control + Shift + i " while in your browser and then clicking the "console button". 

From there, please upload a screenshot or screen recording with it open You can use LIEcap to create a GIF screen recording: https://www.cockos.com/licecap/

**Comment by ACBLDistrict21Webmaster** [comment]
Great to hear from you, Will.

I just upgraded to Gutenberg 11.6.0, but the problem persists.

Following are recordings of the browser console while I recreate the
problem with all plugins activated, and another with only the Gutenberg
plugin activated.

All plugins activated
<https://drive.google.com/file/d/1-0eJAyjecnRWU0MJClDyWn5BGPI-0pty/view?usp=sharing>

Only Gutenberg plugin activated
<https://drive.google.com/file/d/1nCd6_VT4T-mS8zDQOMy5QuitRc2GJIz8/view?usp=sharing>

Best regards,
Grant Robinson
Webmaster, ACBL District 21

**Comment by ACBLDistrict21Webmaster** [comment]
Actually, I provided the requested information 15 days ago. What else do I need to do? Also, I don't know how to comment on this thread without closing it, so here goes.

I can add that I paid for some WP support from GoDaddy on this issue. They believe that the Gutenberg plugin is conflicting with WP 5.8.1. Since I don't need more Gutenberg functionality than what WP provides, I can delete the plugin. I am no longer blocked by this bug.
