### ISSUE TITLE
Triple click within inline code should select only all inline code, not surrounding regular text.

### ISSUE THREAD

**Issue by ai2n** [WordPress/gutenberg#35023]
## What problem does this address?
Inline code is frequently something short you want to select/copy all of quickly.

In apps like Slack, one of the fastest ways to do that is by triple clicking on the inline code, which expands your selection to include the entire inline code text.

_Example of triple click behavior in Slack on regular text and inline code text:_
![Comparison gif](https://imgur.com/mH6IpGr.gif)

From there you are able to copy or act on the inline code text quickly, without the slow process of having to first make an accurate selection by aiming your mouse carefully.

Gutenberg doesn't work like this currently, it treats the inline code like any other regular text, and selects all surrounding text.

## What is your proposed solution?
Adjust inline code text to limit the selection to itself.

**Comment by ellatrix** [comment]
Unfortunately we are limited to what behaviours browsers implement. You can text this with https://codepen.io/iseulde/pen/XWoraex. So this is not something we can fix.

**Comment by ellatrix** [comment]
Btw, I tried this in Slack (on macOS) and triple click also expands to the whole text.

![slack-triple-click](https://github.com/WordPress/gutenberg/assets/4710635/1200a371-bf60-463e-ac19-8ed5f1bb7d9c)
