### ISSUE TITLE
Remove duplicated blockToMenuItem function

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#35037]
### Description

The `blockToMenuItem` [lives in the `edit-navigation` package](https://github.com/WordPress/gutenberg/blob/bf53422023187a97b1b71a6d79af3581f8179dab/packages/edit-navigation/src/store/transform.js#L21-L73), but also [in the `block-library`](https://github.com/WordPress/gutenberg/blob/11294e370b29a237080b946e405c61ed75fa9509/packages/block-library/src/navigation/menu-items-to-blocks.js).

It would be great to remove the duplicate code and have only one copy of that function.

Block library seems to only use it to create a placeholder. Perhaps we could remove it from there? Do the blocks need to know about the underlying data model?

cc @getdave

**Comment by getdave** [comment]
Yup. That's what I was looking at in https://github.com/WordPress/gutenberg/issues/31580.

> Do the blocks need to know about the underlying data model?

I don't know the answer to that at the moment. Happy to discuss.

**Comment by Mamaduka** [comment]
Closing the issue since the editor is no longer maintained and has been removed from the project.
