### ISSUE TITLE
Unexpected "Block Settings" sections added to Customizer

### ISSUE THREAD

**Issue by chad1008** [WordPress/gutenberg#35041]
### Description

Starting with the v11.5.0 release, the Customizer is displaying a "Block Widgets" section for each of the active theme's registered widget areas. Opening one of these sections at first reveals a blank panel. Clicking the Customizer's "back" button then reveals the corresponding widget area, rather than actually backing out to initial Customizer view. From there, the user can edit blocks normally and the "back" button will lead to the initial Customizer view.

This appears to have been introduced in #34543.

### Step-by-step reproduction instructions

1. Activate a theme with registered widget areas (I tested with Twenty Twenty)
2. Open Appearance > Customize
3. Note the Block Settings sections. On Twenty Twenty these appear just above the normal "Widgets" section
4. Open one of the Block Settings. You'll get either a blank panel (first open) or "No Block Selected" (subsequent opens)
5. Back out one step in Customizer
6. Now the blocks for the related widget area appear and can be edited normall
7. Back out one more step
8. You should now be back to start

The Widgets panel and indivudal block settings all appear to function normally when accessed through the usual flow.

### Screenshots, screen recording, code snippet

<img width="341" alt="Screen Shot 2021-09-22 at 08 19 12" src="https://user-images.githubusercontent.com/13856531/134343472-9933a5a3-6463-4afd-a7bb-75d48d6956c5.png">

### Environment info

WP 5.8.0, GB 11.5.0 and 11.5.1, running Twenty Twenty
Chrome 93.0.4577.63
MacOS 11.5.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by AlexanderMonsanto** [comment]
zd-4320575

**Comment by mreishus** [comment]
@chad1008 This should be solved by #35055 which is now merged.

**Comment by noisysocks** [comment]
I believe this was fixed. I can no longer reproduce it running latest WP/Gutenberg.
