### ISSUE TITLE
Navigation: Justify items right in vertical navigation

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#35040]
### Description

When in vertical mode, the justify right option in the navigation block doesn't behave as expected.

### Step-by-step reproduction instructions

Create a vertical navigation block, and then try to align the items right. It looks like this:
<img width="785" alt="Screenshot 2021-09-22 at 13 24 37" src="https://user-images.githubusercontent.com/275961/134343045-e635b90b-3585-4678-b05e-cc499f7317d3.png">

### Screenshots, screen recording, code snippet

It should look like this:
<img width="652" alt="Screenshot 2021-09-22 at 13 28 06" src="https://user-images.githubusercontent.com/275961/134343630-66220cef-088a-4611-84e1-bfc680aafe69.png">

In addition, the submenus should open to the left:
<img width="843" alt="Screenshot 2021-09-22 at 14 42 08" src="https://user-images.githubusercontent.com/275961/134354803-72c101d8-42d5-4131-ab17-48a5b556a4e9.png">

cc @jasmussen 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Thanks for the ticket. I have a fix in #35077. It's a bit of a big PR as it surfaced a bunch of smaller issues, but it'll all be good to land. Would appreciate your testing.
