### ISSUE TITLE
Navigation editor: Nested block-based menu items are deleted and re-created on each save

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#35047]
[As noted in 34541:](https://github.com/WordPress/gutenberg/pull/34541#discussion_r712325699)

The `mapMenuItemsToBlocks` function assigns the `__internalEntityRecord` attribute to all the blocks representing classic menu items. This way we can match blocks with menu items and update the correct ones.

Unfortunately, it doesn't assign `__internalEntityRecord`  to nested blocks. The save function "thinks" it sees new menu items and that it doesn't see the old ones. This results in deleting and re-creating the same menu items on each save:

https://github.com/WordPress/gutenberg/blob/bf53422023187a97b1b71a6d79af3581f8179dab/packages/edit-navigation/src/store/transform.js#L174-L184

cc @talldan

**Comment by Mamaduka** [comment]
Closing the issue since the editor is no longer maintained and has been removed from the project.
