### ISSUE TITLE
Navigation editor: Fail loudly when attempting to save unsupported blocks

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#35045]
Navigation editor only processes a subset of blocks in the editor, silently omitting anything that's not supported:

https://github.com/WordPress/gutenberg/blob/fa5728771df7cdc86369f7157d6aa763649937a7/packages/edit-navigation/src/store/actions.js#L207-L209

It would be useful to log a warning and make any problems there apparent.

**Comment by anton-vlasenko** [comment]
@adamziel 
> It would be useful to logging a warning and make any problems there apparent.

When you say it would be helpful to log warnings, do you mean simple browser console warnings?
Or do we need something more complicated?

**Comment by adamziel** [comment]
>  do you mean simple browser console warnings?

@anton-vlasenko Yup, exactly! Just to let the developers know something is off. I think we could use [`@wordpress/warning`](https://www.npmjs.com/package/@wordpress/warning) here.
