### ISSUE TITLE
ToolsPanel: improve unit tests

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#35057]
## What

Improve unit tests by partially rewriting them. They should not be checking implementation details (like classnames, the presence of certain react components...), but instead, they should test the `ToolsPanel` component replicating the way end-users interact with it.

## Why

Here's a [great explainer](https://kentcdodds.com/blog/testing-implementation-details)

## A/C

* [ ] There should be no usages of `querySelector`, `querySelectorAll` or any similar way of getting an element from the DOM.
* [ ] Similarly, we should not test the exact DOM structure (e.g. getting parent elements, or checking for the existence of a specific React component). We should instead, for example, find components by role, or accessible text
* [ ] Add coverage for behaviour related to unique panelIds to cover the user behaviour of switching between similar blocks that share common ToolsPanels. A concrete example is to cover the bug fix in #35375

**Comment by aaronrobertshaw** [comment]
A PR has been created addressing as much as possible from the list in the description: https://github.com/WordPress/gutenberg/pull/35658
