### ISSUE TITLE
Anchor/Link text potentially causing legacy widget to break closed state "no preview" representation in editor

### ISSUE THREAD

**Issue by ts-mz** [WordPress/gutenberg#35052]
### Description

**Note bene:** I have tried this with the custom legacy example "foo" widget from the Codex, and could not reproduce the error, because the preview of the title is rendered fine upon saving.

That said, I have a custom legacy widget class that displays well in both open and closed state in the new widget editor unless there is an Anchor/Link with text present in the $output variable of the legacy widget. It doesn't matter if the code is actually echoed out or not.

`$output = '<a href="abc.com"></a>';`

will work fine, while

`$output = '<a href="abc.com">xyz</a>';`

will cause the closed state represenation of the legacy widget visually disappear in the editor. It is still clickable, and the open state is still completely functional.

In other words the no-preview-representation

`<div class="wp-block-legacy-widget__edit-no-preview">
    <h3>Widget Name</h3>
    <p>No preview available.</p>
    </div>`
  
  is not rendered in the source code. Instead apparently the entire frontend is loaded as an iframe into

`<div class="wp-block-legacy-widget__edit-preview">
    <div class="components-disabled css-u2jump e1ac3xxk0">
        <iframe class="wp-block-legacy-widget__edit-preview-iframe" tabindex="-1" title="Legacy Widget Preview" srcdoc="		<!doctype html>
		<html lang=&quot;de-DE&quot;>
		<head>...
`  

### Step-by-step reproduction instructions

1. Create a custom legacy widget/class for which no preview rendering is possible
2. Have it output an anchor link with text
3. See the closed legacy widget representation disappear

### Environment info

Local xampp Install, php 7.3.5
latest released WP
latest released Gutenberg 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment]
cc @getdave in case you have any insights :)

**Comment by getdave** [comment]
👍 I think perhaps @noisysocks would be better placed to look into this one.

Also I'm not sure this is a Link Editing issue. I'm almost sure it will be specific to the Widgets editor. Remove label for now but can be re-added by @noisysocks if he feels I'm wrong.

**Comment by noisysocks** [comment]
Could you please share a screenshot of what you're seeing? I'm not quire sure what you mean by "the closed legacy widget representation". 

Also, could you please share the PHP code for the the custom widget that you're using for testing?

The "No preview available." message appears when the widget renders empty markup. `<a href="#"></a>` would be considered empty and `<a href="#">foo</a>` would be considered **not** empty.

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @ts-mz hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
