### ISSUE TITLE
Version 11.5.1 - No longer loads Editor CSS 

### ISSUE THREAD

**Issue by steveangstrom** [WordPress/gutenberg#35054]
### Problem
My sites editorstyles.css fail to apply to many elements with the current version of Gutenberg

### 1:
using a "normal" / common theme such as the Hello theme, child
then add an editorstyle.css in the usual way

in /THEMENAME/functions.php

`add_editor_style('css/editorstyle.css');`

```
 .editor-styles-wrapper {
      font-family: "Cabin",cabin,sans-serif;
  }
```

2 ### Result
**in WordPress 5.8.1 with Gutenberg 11.5.1**
the fonts in the editor render with a mixture of fonts, including "serif"

INCORRECT (Gutenberg Plugin  11.5.1)
![gutenberg - messing up editor css](https://user-images.githubusercontent.com/8482649/134370397-6e8b43ff-1331-40b0-8d93-88945a6b0058.png)

in the incorrect version, plugin version, this rule is taking precendence
```
html :where(.editor-styles-wrapper) {
 background:#fff;
 color:initial;
 font-family:serif;
 font-size:medium;
 line-height:normal;
 padding:8px
}
```

CORRECT (no plugin, just WP)
![editor css no gutenberg](https://user-images.githubusercontent.com/8482649/134370310-39d388d0-6d9b-47ba-884e-84833e31f1c1.png)

### Screenshots, screen recording, code snippet

![gutenberg - messing up editor css](https://user-images.githubusercontent.com/8482649/134374483-656ea404-f03d-4d26-80d6-fb1095073ed4.png)

### Environment info

WP V5.8.1
Gutenberg Version 11.5.1
Theme Hello (Child)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
cc @jasmussen I wonder if this is related to the change in the reset styles somehow?

@steveangstrom would you mind providing a zip of your theme?

**Comment by jasmussen** [comment]
Question, when you add the editor style do you specifically target `.editor-styles-wrapper` in the editor style? `add_editor_style` is best paired with targetting `body` just as you would on the frontend, and it then rewrites that to `body`. In experiments with the site editor iframe, it's possible that parsing has changed between versions.

**Comment by steveangstrom** [comment]
Hi folks, apologies I'm a bit rushed at the moment but here's the content of my editor style to answer a few questions @jasmussen  you can see the target of .editor-styles-wrapper in the second declaration.
```

html {
    font-size: 18px;
    line-height: normal;
}
.edit-post-visual-editor__content-area .editor-styles-wrapper {
   padding: 0px;
  }
  .editor-styles-wrapper {
      font-family: "Cabin",cabin,sans-serif;
  }
/********* WIDTH FIX *************/

/* Main column width */
.wp-block {
    max-width: 1100px;
}

/* Width of "wide" blocks */
.wp-block[data-align="wide"] {
    max-width: 1080px;
}

/* Width of "full-wide" blocks */
.wp-block[data-align="full"] {
    max-width: none;
}
/**********************/
.editor-styles-wrapper,
h1,h2,h3,h4,h5,p,ul,li{
  font-family: cabin,Roboto,Oxygen-Sans,Ubuntu,Cantarell!important;
}
h1,
h2,
h3,
h4,
h5,
h6 {
  margin-top: initial;
  margin-bottom: 0.2rem;
  font-family:"Cabin",cabin,sans-serif;
  font-weight:600;
  line-height:1.1;
  color:inherit
}

h1 {	font-size: min(max(48px, 5vw), 68px);font-weight:600;line-height: initial;}
h2 {	font-size: min(max(40px, 5vw), 56px);font-weight:600;line-height: initial;}
h3 {	font-size: min(max(38px, 5vw), 48px);font-weight:600;line-height: initial;}
h4 {	font-size: min(max(28px, 2.2vw), 38px);	font-weight:400;line-height: initial;}
h5 {	font-size: min(max(20px, 2.2vw), 28px);	font-weight:400;line-height: initial;}
h6 {	font-size: min(max(17px, 2.2vw), 20px);	font-weight:400;line-height: initial;}
p{font-size: 17px; font-weight:400; line-height: initial;}
.editor-post-title {font-weight:600; color:var(--sc-bodytext-dark);font-size: 56px;}
.editor-post-title .editor-post-title__input{font-weight:600;color:var(--sc-bodytext-dark);font-size: 56px;}
```

**Comment by steveangstrom** [comment]
I've just realised something, this is the rule in reset which is enforcing serif

```
html :where(.editor-styles-wrapper) {
	color: initial;
	font-family: serif;
	font-size: medium;
	line-height: normal;
}
```

In my site , the block which is mis-styled has output like this

```
<div class="post_text ">
<h3 class="sc_post_grid--title">A W.I.L Testimonial</h3>
  <div class="post_body">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit  pariatur.…</div>
  <div class="testimonial_credits"><span>Jane Doe</span><span>Head of Marketing</span><span>Janedoe Enterprises</span><span>https://janedoe.com/contact</span></div>
</div>
```

The H3 has the correct font, but the `<div class="post_body">Lorem ipsum d...`   inherits Serif from the reset.css, because it matches that rule.  the reset is more specific than 

```
.editor-styles-wrapper {
      font-family: "Cabin",cabin,sans-serif;
  }
```

**Comment by jasmussen** [comment]
Thank you for the added information. Can you try and replace `.editor-styles-wrapper` with `body` in your editor style?

**Comment by steveangstrom** [comment]
> Can you try and replace `.editor-styles-wrapper` with `body` in your editor style?

Thank you, I targetted BODY as you suggested and the styles are now applied correctly.

**Comment by jasmussen** [comment]
Awesome, happy to hear that. I'll close this one then!
