### ISSUE TITLE
ToolsPanel: move away from hardcoded classnames

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#35058]
## What

Requires #34345 first, to make sure that tests don't rely on classnames.

We should refactor the `ToolsPanel` component so that it avoids using hardcoded classnames as much as possible.

Currently, the hardcoded classnames in `TooolsPanel` are:

- `components-tools-panel`. This class could be replaced by using the context system, so that `ToolsPanelHeader` knows if it's being rendered inside a `ToolsPanel`
- `single-column`. This class should be removed because it currently introduces circular dependencies with the [`block-editor`](https://github.com/WordPress/gutenberg/blob/4dc6fe86d1f59bab985eb0cb8be481be582415f6/packages/block-editor/src/hooks/dimensions.js#L101) and [`edit-site`](https://github.com/WordPress/gutenberg/blob/20c711d8e75a6dfb12425eacb14f71766a2be3df/packages/edit-site/src/components/sidebar/dimensions-panel.js#L182) (as also specified in https://github.com/WordPress/gutenberg/pull/34725#pullrequestreview-761168248)
- `components-base-control` as explained in https://github.com/WordPress/gutenberg/pull/34725#discussion_r715297703
- `components-dropdown-menu` and `components-dropdown-menu__toggle` — these classnames are going to be tougher to remove, since they would need first the `DropdownMenu` component to be refactored and use the new context System. After that, we could use the component's computed selector at runtime ([example](https://github.com/WordPress/gutenberg/blob/3fd7cdc97d56786a42ce51f9e8738f0c7cb4e6e8/packages/components/src/flyout/styles.ts#L36))

## Why

We should avoid using hardcoded classnames as much as possible in our components:

- it goes against the [Styling guidelines](https://kentcdodds.com/blog/testing-implementation-details), where classnames are generated at runtime
- hardcoded classnames can be effectively treated as public API, which can later need to involuntary breaking changes later on.

## A/C

- [ ] Remove the `components-tools-panel` classname
- [ ] Remove the `single-column` classname
- [ ] Remove the `components-dropdown-menu` and `components-dropdown-menu__toggle` classnames

**Comment by aaronrobertshaw** [comment]
A PR removing all the hardcoded classnames except for `single-column` is up: #35415 

Adopting the Grid component to handle the `ToolsPanel` layout, and thus remove the `single-column` class, should be possible but will involve a little more work. I'll take care of that in a separate PR.
