### ISSUE TITLE
Block Editor State: Calls to receiveBlocks insert undefined values into block tree

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#35066]
### Description

Calling `receiveBlocks` inserts `undefined` innerBlocks into the root node of `block-editor` block tree state.

### Step-by-step reproduction instructions

1. Checkout this PR https://github.com/WordPress/gutenberg/pull/35067
2. Open the post editor
3. Verify that, for the information logged into the dev console, that `undefined` values are introduced into `block-editor` block tree state.

### Screenshots, screen recording, code snippet

<img width="625" alt="Screen Shot 2021-09-22 at 9 50 27 PM" src="https://user-images.githubusercontent.com/5414230/134456311-0d621490-dc84-4838-8749-980c845534f2.png">

### Environment info

- WordPress dev (5.9-alpha-51739)
- Gutenberg dev

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Addison-Stavlo** [comment]
While I wasn't able to find the `undefined` value by loading the editor in that PR, I was able to repro by doing `wp.data.dispatch('core/block-editor').receiveBlocks( [ wp.blocks.createBlock( 'core/image' ) ] );` (from test instructions on riad's PR linked above - it seems to fix the issue 😁 )
