### ISSUE TITLE
Remove Meetup.com variation from the embed block

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#35085]
### Description

Trying to add a meetup.com block gives no preview of the embed, nor does it display on the front-end. 

There is the distinct possibility that Meetup.com, like other providers, stopped publishing oEmbed. I also tested it with the Classic Editor, and it didn't render an oEmbed either. 

And the end point https://api.meetup.com/oembed renders a "not found"

### Step-by-step reproduction instructions

1. add a post
2. insert a meetup.com block
3. add url (I used [this event](https://www.meetup.com/learn-wordpress-discussions/events/280780344))

### Screenshots, screen recording, code snippet

![Screen Shot 2021-09-23 at 8 00 18 AM](https://user-images.githubusercontent.com/39980/134503787-8425ea86-fe75-4beb-ab05-f96901322a36.png)
![Screen Shot 2021-09-23 at 8 00 00 AM](https://user-images.githubusercontent.com/39980/134503821-fbb5a52a-1110-4fc5-b22a-02e953ab20de.png)

### Environment info

First Test
- WordPress 5.8.1
- Gutenberg Nightly (9/22)
- Twenty-Twenty-one Theme

Second Test
- WordPress.5.8.1
- no Gutenberg plugin
- plain _s theme. 
 
Third Test
- WordPress 5.8.1
- Classic Editor plugin
- plain _s theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Soean** [comment]
I can't find the embed endpoint the docs anymore. In the wayback machine the site shows that the endpoint is deprecated 
 https://web.archive.org/web/20200718004152/https://www.meetup.com/de-DE/meetup_api/docs/oembed/

**Comment by bph** [comment]
Nice sleuthing, @Soean! So, not a bug.  I guess, we would need to deprecate the meetup.com block. I'll change the title of the issue, then
![Screen Shot 2021-09-23 at 5 07 46 PM](https://user-images.githubusercontent.com/39980/134584228-c3ef5932-1724-443f-b145-162d7821ce1d.png)
.

**Comment by MuhammadFaizanHaidar** [comment]
Hi @bph I would love to contribute to this ticket I need some guidance . Do I need to remove 'meetup-com' block from variations.js? Thanks

**Comment by bph** [comment]
@MuhammadFaizanHaidar that would be my instinct, and that's all there is nothing to back it up. Intuition fails me 50% of the time. 
I probably would also look at cleaning out Facebook and Instagram variations, as those have been deprecated, which already happened back in October 2020. 

On the other hand, why haven't they been removed? There might be some underlying reason, that's not entirely obvious to me, so I am a bit hesitant to say go for it. 

The fastest way to get eyes on your idea and comments would be to submit a PR with the changes you want to make and ask for a review. If you haven't yet, make sure you read through the [Contributor Guide](https://developer.wordpress.org/block-editor/contributors/) before submitting a PR.

**Comment by Mamaduka** [comment]
Hi, @bph. This probably would require a sibling ticket on WP Core Trac.

**Comment by peterwilsoncc** [comment]
I've created a sibling ticket for this on trac https://core.trac.wordpress.org/ticket/55997#ticket
