### ISSUE TITLE
Inserter: Update default view of Patterns tab

### ISSUE THREAD

**Issue by kellychoffman** [WordPress/gutenberg#35102]
When no patterns are packaged with current theme, the current view for the pattern inserter is not very inspiring. It would be more useful to have a `Featured` section as the default view. Quick mock: 

<img width="291" alt="Screen Shot 2021-09-23 at 7 58 03 PM" src="https://user-images.githubusercontent.com/5835847/134611473-cbccb84d-df87-4e78-87f6-06282cb7ae34.png">

**Current view for reference:** 

<img width="350" alt="Screen Shot 2021-09-23 at 7 59 11 PM" src="https://user-images.githubusercontent.com/5835847/134611544-50b34576-ef7c-4b99-8cef-b91646394dc4.png">

Looking at the directory, suggested patterns to show:

- https://wordpress.org/patterns/pattern/two-images-with-shared-colored-strip/
- https://wordpress.org/patterns/pattern/offset-gallery-with-fixed-background-and-quote/
- https://wordpress.org/patterns/pattern/triptych-with-two-images-and-a-text-area/
- https://wordpress.org/patterns/pattern/callout-over-a-patterned-background/
- https://wordpress.org/patterns/pattern/three-columns-with-offset-images/
- https://wordpress.org/patterns/pattern/offset-images-with-descriptions/
- https://wordpress.org/patterns/pattern/image-on-solid-color-with-description/
- https://wordpress.org/patterns/pattern/centered-introduction-text-with-button-and-offset-images/
- https://wordpress.org/patterns/pattern/heading/
- https://wordpress.org/patterns/pattern/simple-call-to-action/
- https://wordpress.org/patterns/pattern/two-images-with-text-and-buttons/
- https://wordpress.org/patterns/pattern/large-header-with-left-aligned-text/
- https://wordpress.org/patterns/pattern/header-with-hatched-pattern/

cc @kjellr for suggestions on which patterns to feature here

**Comment by Mamaduka** [comment]
Related #33046.

cc @priethor

**Comment by kellychoffman** [comment]
Sorry for the dupe! Will close mine in favor of Kjell's.
