### ISSUE TITLE
"Save as..." for Reusable Blocks

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#35113]
It's not always clear where your edits will take you when working with a Reusable Block. Occasionally you'll find yourself making changes that are so extensive that creating a brand new Reusable Block becomes desirable.

Unless I'm mistaken, if you wanted to do this currently you'd need to copy/paste the blocks, create a new Reusable Block, then undo all the changes you made to the one you were originally working with... this is a bit of an ordeal.

When https://github.com/WordPress/gutenberg/pull/32464 is merged it will be possible to save reusable blocks directly from their toolbar.

<img width="1032" alt="Screenshot 2021-09-24 at 12 08 30" src="https://user-images.githubusercontent.com/846565/134665095-8702ab53-5da3-4956-9523-aab635e8ad76.png">

I wonder if we could use this pattern to introduce a "Save as..." option? Or maybe something simpler, exposed in the ellipsis menu?

<img width="629" alt="Screenshot 2021-09-24 at 13 54 15" src="https://user-images.githubusercontent.com/846565/134677751-808b8123-a30d-467a-b5c8-d73f299ddb67.png">

Naturally we'd need to expose this functionality in the multi-entity save panel too. Perhaps this makes the ellipsis menu a better location.

**Comment by karmatosed** [comment]
If adding save as, I think the ellipsis works a little better than the 'save as' dropdown - however that might be because the flow is new. Maybe with some iterations that could work but I'm not convinced.

**Comment by jameskoster** [comment]
Yeah the ellipsis probably makes more sense when we think about how we might present this affordance in the multi-entity save interface:

<img width="1355" alt="Screenshot 2021-09-27 at 11 15 53" src="https://user-images.githubusercontent.com/846565/134890233-338c5fa2-771d-402c-8b77-5caa1c399bfb.png">

Especially when we consider other potential actions like discarding changes, or renaming.

**Comment by jordesign** [comment]
https://github.com/WordPress/gutenberg/pull/32464 is not yet merged - so there's currently no way to specifically Save Synced Patterns in the toolbar. But this may be something we want to keep open to keep considering. What do you think @jameskoster ?

**Comment by jameskoster** [comment]
The pattern management experience evolved _a lot_ in 6.3 where it is now possible to duplicate and edit individual patterns in isolation. We can probably close this out :)
