### ISSUE TITLE
Post content block: Add font and color properties

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#35118]
Whilst the query block is amazing, along with the group block, I would recommend that post content has some basic styling features added to it. Currently, this is all you see:

![2021-09-24 at 16 02](https://user-images.githubusercontent.com/253067/134697293-231b6f0e-d0e3-4929-8681-00a84e211f54.png)

Compare this to post title:

![2021-09-24 at 16 03](https://user-images.githubusercontent.com/253067/134697381-75d5ec74-c609-44eb-82ff-510c34ea94c9.png)

Many other 'post' blocks have at least font and color settings, but this one doesn't yet.

**Comment by carolinan** [comment]
But the post content block _displays the content that you added to your post_, and that content is already styled?
You select the "inner" block inside the post content to change the color, etc.

**Comment by karmatosed** [comment]
@carolinan I wonder if there's a case for someone wanting to though unify the styling or at least use global styles here?

**Comment by carolinan** [comment]
I don't understand how that would work? The blocks in the post content could be anything, a quote, table, paragraphs, or even another query loop with more post content blocks?

**Comment by karmatosed** [comment]
Right and perhaps you could set the font family across all?

**Comment by porg** [comment]
## Post Content Block: Possible benefits of attributes Margin and Background-Color

https://github.com/WordPress/gutenberg/assets/737143/444047ce-8420-4be1-81c6-d08c54fc809a

## I also agree that the Post Content block needs more styling properties

- **Font**: Instinctively against it.
  - Overriding font in the Post Content block leads to a lot of overriding/specificity issues.
  - Feels counter-intuitive to the modular CSS approach Gutenberg follows in general
  - That should be handled with:
    - Block Editor → Styles → Typography. 
    - Block Editor → Styles → Blocks → Select block which shall deviate typographically.
  - What is the use case?
    - Entirely different font attributes in certain page template which is styled very differently?
      - Sounds reasonable to then need a "big override" via Post Content block.
      - But still my first instinct: A lot of conflict and contradictions to the Gutenberg styling architecture.

- **Color**: Certainly yes. See my use case below.

- **Margin** and **Background-Color** were my personally needed attributes for Post Content, as shown above.
  - Workaround: Wrap whole page content in group and operate on this one, and add custom CSS to override hardcoded Post-Content attributes you mislike.
  - Disadvantages:
    - Deeper nesting than necessary.
    - Inflexibilities: Some of the ideas shown in the mockup video above would be way easier with attributes of the Post Content block.

**Comment by ramonjd** [comment]
The post content block has opted into most supports it appears:

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-content/block.json#L10

<img width="281" alt="Screenshot 2024-04-08 at 4 18 36 pm" src="https://github.com/WordPress/gutenberg/assets/6458278/acdd4c25-9138-4637-b180-841c169fc49f">

I think the main issue has been resolved. Maybe we could add a follow up issue if the default supports don't make sense?

I'll close for now. Feel free to reopen if it's still relevant.

Thank you!
