### ISSUE TITLE
Site editor: Undefined index: __unstableType

### ISSUE THREAD

**Issue by franmastromarino** [WordPress/gutenberg#35126]
### Description

PHP error Undefined index: __unstableType wp-content\plugins\gutenberg\lib\compat\wordpress-5.9\default-editor-styles.php on line 29

### Step-by-step reproduction instructions

define('WP_DEBUG', true);
define('SCRIPT_DEBUG', true);
define('WP_CACHE', true);

### Screenshots, screen recording, code snippet

https://snipboard.io/TLF10d.jpg

### Environment info

WordPress version: 5.8.1
Gutenberg version: 11.5.1
Are all plugins except Gutenberg deactivated? Yes
Are you using a default theme (e.g. Twenty Twenty-One)? No

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for reporting the issue, @quadlayers.

The notice was fixed via #34735 and will be available in Gutenberg 11.6.

**Comment by franmastromarino** [comment]
great! thanks
