### ISSUE TITLE
Arrow key behavior in basic paragraph blocks (repeat behavior)

### ISSUE THREAD

**Issue by pzelchenko** [WordPress/gutenberg#35129]
### Description

(I've searched for this issue but haven't found anything; perhaps it's already been discussed.)

Normally when in a paragraph block and at the end of the block, using down-arrow or right-arrow to move to first character or down into first line (respectively) of next paragraph block behaves as expected. However, at a certain point it can begin to exhibit the following behavior: another such keypress will take you to the _last_ character of the _subsequent_ block (see video). Originally I thought this was standard behavior, but it seems to "kick in" at some unknown point. I've had it repeat twice in a day, still not sure what triggers it. Therefore I would call it repeating and probably repeatable when we know the incantation. Maybe someone has seen this before? Also, I have not yet figured out how to reset the behavior to normal.

(Chrome Windows, assume same behavior on other browsers)

### Step-by-step reproduction instructions

See above description

You sure don't make it very easy to help fix the world - now I suddenly need to trim my video to less than 10 MB?? Time for another 10 minutes of fun instead of doing my own work.

### Screenshots, screen recording, code snippet

[Edit Post ‹ View from the L — WordPress.com - Google Chrome 2021-09-26 23-51-09.zip](https://github.com/WordPress/gutenberg/files/7231684/Edit.Post.View.from.the.L.WordPress.com.-.Google.Chrome.2021-09-26.23-51-09.zip)

### Environment info

Basic theme, Latest Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by paaljoachim** [comment]
I am using WordPress 5.8
Theme: Twenty Twenty One
Gutenberg plugin active version 11.5.1
Self hosted WP in a local development site.

I added a few paragraphs. Moved the blinking cursor a few steps back and then forward. Added some text. Went to the paragraph below added some text. Continued moving the cursor around with the arrow keys. I have not yet been able to produce the jumping cursor as you showed in the video.

**Comment by pzelchenko** [comment]
It doesn't happen right away. I haven't yet figured out how it reproduces.

--
Peter Zelchenko 手机(+86)/微信18221718104
College of Design and Innovation, Tongji University 同济大学设计与创新学院






On Monday, September 27, 2021, 04:51:28 AM GMT+8, Paal Joachim Romdahl ***@***.***> wrote: 







I am using WordPress 5.8
Theme: Twenty Twenty One
Gutenberg plugin active version 11.5.1
Self hosted WP in a local development site.

I added a few paragraphs. Moved the blinking cursor a few steps back and then forward. Added some text. Went to the paragraph below added some text. Continued moving the cursor around with the arrow keys. I have not yet been able to produce the jumping cursor as you showed in the video.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shaunandrews** [comment]
Based on some Slack conversations (https://wordpress.slack.com/archives/C02S78ZAL/p1632834506131400?thread_ts=1632591597.126000&cid=C02S78ZAL) it seems this was resolved by rebooting.

I'll close this for now, but we can reopen if it happens again.

**Comment by pzelchenko** [comment]
Thanks Shaun and all. Nice workflow, guys. I've been watching the QC loop degrade for five decades, and for a volunteer effort this is very streamlined and impressive. Slack has always been a bit of a dog, and the chat.* onboarding was nasty, but you're using it well.

--
Peter Zelchenko 手机(+86)/微信18221718104
College of Design and Innovation, Tongji University 同济大学设计与创新学院

On Tuesday, September 28, 2021, 11:38:33 PM GMT+8, Shaun Andrews ***@***.***> wrote: 

Closed #35129.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
