### ISSUE TITLE
Media & Text Block error while dragging inside it more than one block

### ISSUE THREAD

**Issue by oglekler** [WordPress/gutenberg#35128]
### Description

"The editor has encountered an unexpected error" and the recovery attempt is not working. I've got this error with no plugins on WordPress version 5.8.1 and the Twenty Twenty-One theme.

### Step-by-step reproduction instructions

1. Add in the Block Editor some text or/and images (more the one block)
2. Add Media & Text block
3. Select several blocks and try to move them inside the content part of the Media & Text block.

### Screenshots, screen recording, code snippet

Demo: https://disk.yandex.ru/i/WTYH94aslSYTug

### Environment info

WordPress 5.8.1 and the Twenty Twenty-One 1.4 theme, no plugins.

I've checked in Google Chrome 93.0.4577.82 (Official Build) (64-bit) and Firefox 92.0 (64-bit).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
It is possibly related to #34631.

**Comment by Mamaduka** [comment]
The error happens because both `startRef.current` and `endRef.current` are `undefined` after dragging multi-selected blocks into another block - "Media & Text," "Columns" or any block that support inner blocks.

Pinging @ellatrix since I'm not very familiar with this part of code.

**Comment by Mamaduka** [comment]
I just merged a fix for this issue, and it should be available in Gutenberg 11.7.
