### ISSUE TITLE
Query Loop: Include a Query Pagination option on the block variations panel

### ISSUE THREAD

**Issue by inaikem** [WordPress/gutenberg#35134]
### What

Add the _Query Pagination_ block when selecting a variation.

### Why

When you add the _Query Loop_ block and select a variation:

![QueryLoopBlock](https://user-images.githubusercontent.com/16104522/134504729-41285ba6-6511-487a-9c5f-ba4398eed9d3.png)

You would expect that those would include pagination, but they don't. It's confusing because you can see pagination settings on the block:

![QueryLoopBlock2](https://user-images.githubusercontent.com/16104522/134504897-cb943c87-cf7a-4d18-a8c9-5f81df9a25a7.png)

But once on the live page, it won't show any pages/pagination.

And it's quite tricky to add the _Query Pagination_ block, you need to have the _Query Loop_ block selected, and use the + icon inside of it to be able to search for the _Query Pagination_ one.

---

Originally reported in https://github.com/Automattic/wp-calypso/issues/56501.

**Comment by ntsekouras** [comment]
--cc @mtias, @kjellr, @jameskoster, @aristath for sharing thoughts 😄 

FYI the `Query Pagination` block was not included in these variations initially, as it was implemented later to work properly.

**Comment by jameskoster** [comment]
I can definitely see the current UX being confusing. To make matters worse I'm not sure the average user would be familiar with the term "pagination", so finding the block may be a challenge on its own.

It therefore seems sensible to include Query Pagination by default in these variations.
