### ISSUE TITLE
Heading block: setting colors causes some unexpected results in site editing

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#35144]
I found this fun little situation using Chrome where I could change different colors without expected results. The following gif probably explains it better, but as you can see, it's not picking up the correct colors and setting the entire line:

![2021-09-26_11 07 08](https://user-images.githubusercontent.com/253067/134904396-e2768bb8-4eb7-4467-8791-c2f4d9a1ab63.gif)

It seems to be seeing it 'all' as a link, which it's not.

**Comment by carolinan** [comment]
I was not able to reproduce this with current trunk of Gutenberg, which version are you using?
Chrome, Windows:
![Text color is changed using the custom color palette](https://user-images.githubusercontent.com/7422055/134918606-2ac67ca3-9682-4cf4-bb2a-6256fc0582a0.gif)

**Comment by karmatosed** [comment]
@carolinan latest version was what I was using so that's interesting you can't produce. It was with Chrome, Mac.

**Comment by carolinan** [comment]
Does your theme have any setting for the custom link color 
https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#link-color-control
Just grasping for things that might affect it 🤔

**Comment by karmatosed** [comment]
@carolinan it does. I can't currently recreate this outside my own theme using the latest version so let's maybe consider it might have been fixed or at least be something to do with custom links.
