### ISSUE TITLE
Cannot upload or use media items from within Gutenberg

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#3514]
When attempting to upload multiple media items from within the Gutenberg error (starting with a Cover Image block and uploading items to fill the media library), the following errors occur and no uploads complete successfully:

> ![2017-11-16t15 11 44 0800](https://user-images.githubusercontent.com/227022/32878542-69f79c6c-cae1-11e7-882f-c679ccc437d8.png)

Using the standalone media library page, the uploads complete as expected, with progress indicators for each uploaded file.

When I go back to Gutenberg to try to insert the now-uploaded images, the media library modal displays "No items found", which is incorrect:

> ![2017-11-16t15 20 13 0800](https://user-images.githubusercontent.com/227022/32878608-ab8564d4-cae1-11e7-8e91-f2a1f9a5430e.png)

When uploading a single media item, the upload appears to complete successfully, but it's difficult to tell because the media interface won't show it.

Using WP 4.9 and Gutenberg 1.7.0, no other plugins activated.

**Comment by nylen** [comment]
I'm no longer able to reproduce this issue.  I'm not sure exactly what changed but I did switch themes a couple of times and change the permalink settings on the site.  I'll reopen if I see it again.

**Comment by cyberfunk** [comment]
Hello the latest wordpress uses Gutenberg exclusively but my media library says "No Items Found" when trying to add existing images to posts. I refreshed/flushed permalinks but that did not fix the issue. I have to use the Classic Editor plug-in to restore my media library but would like to prepare my theme for the future with Gutenberg. Have you run into this problem with the latest build of WordPress?
