### ISSUE TITLE
Navigation Editor: Maintain backwards compatibility with existing filters and actions.

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#35157]
The new navigation editor needs to ensure the existing actions and filters are maintained. This is a working list of filters and actions. 

### Filters 

- [customize_nav_menu_available_items](https://developer.wordpress.org/reference/hooks/customize_nav_menu_available_item_types/)
- [customize_nav_menu_searched_items](https://developer.wordpress.org/reference/hooks/customize_nav_menu_searched_items/)
- [customize_nav_menu_available_item_types](https://developer.wordpress.org/reference/hooks/customize_nav_menu_available_item_types/)
- [wp_nav_locations_listed_per_menu](https://developer.wordpress.org/reference/hooks/wp_nav_locations_listed_per_menu/)
- [nav_menu_items_{$post_type_name}_recent](https://developer.wordpress.org/reference/hooks/nav_menu_items_post_type_name_recent/)
- [nav_menu_items_{$post_type_name}](https://developer.wordpress.org/reference/hooks/nav_menu_items_post_type_name/)
- [nav_menu_meta_box_object](https://developer.wordpress.org/reference/hooks/nav_menu_meta_box_object/)
- [nav_menu_submenu_css_class](https://developer.wordpress.org/reference/hooks/nav_menu_submenu_css_class/)
- [wp_get_nav_menu_object](https://developer.wordpress.org/reference/hooks/wp_get_nav_menu_object/)
- [has_nav_menu](https://developer.wordpress.org/reference/hooks/has_nav_menu/)
- [wp_get_nav_menu_name](https://developer.wordpress.org/reference/hooks/wp_get_nav_menu_name/)
- [wp_get_nav_menus](https://developer.wordpress.org/reference/hooks/wp_get_nav_menus/)
- [wp_get_nav_menu_items](https://developer.wordpress.org/reference/hooks/wp_get_nav_menu_items/)
- [nav_menu_attr_title](https://developer.wordpress.org/reference/hooks/nav_menu_attr_title/)
- [nav_menu_description](https://developer.wordpress.org/reference/hooks/nav_menu_description/)
- [wp_setup_nav_menu_item](https://developer.wordpress.org/reference/hooks/wp_setup_nav_menu_item/)

### Actions
- [wp_nav_menu_item_custom_fields](https://developer.wordpress.org/reference/hooks/wp_nav_menu_item_custom_fields/) - See https://github.com/WordPress/gutenberg/issues/31551
- [wp_nav_menu_item_custom_fields_customize_template](https://developer.wordpress.org/reference/hooks/wp_nav_menu_item_custom_fields_customize_template/)
- [after_menu_locations_table](https://developer.wordpress.org/reference/hooks/after_menu_locations_table/)
- [wp_update_nav_menu_item](https://developer.wordpress.org/reference/hooks/wp_update_nav_menu_item/)
- [wp_delete_nav_menu](https://developer.wordpress.org/reference/hooks/wp_delete_nav_menu/)
- [wp_create_nav_menu](https://developer.wordpress.org/reference/hooks/wp_create_nav_menu/)
- [wp_update_nav_menu](https://developer.wordpress.org/reference/hooks/wp_update_nav_menu_item/)
- [wp_add_nav_menu_item](https://developer.wordpress.org/reference/hooks/wp_add_nav_menu_item/)

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
