### ISSUE TITLE
RangeControl marks styling regression

### ISSUE THREAD

**Issue by stokesman** [WordPress/gutenberg#35153]
### Description

The marks in RangeControl are vertically off-center.

I've visited the [WordPress Design Library](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library) looking for any specs on the mark placement. I found the designs for range controls but could not find any of them with marks.

Given the lack of specs, I'd recommend adjusting them vertically to center on the rail since they were like that originally.

#### Current Styling
![image](https://user-images.githubusercontent.com/9000376/134948887-8c2af9f8-ccb1-4fce-8ac2-7aa47ba82981.png)

#### Expected Styling (from #26745)
![range-controls-fixed-negative-min](https://user-images.githubusercontent.com/9000376/98409178-36cab600-2027-11eb-8ede-4e1901dcd6aa.png)

### Step-by-step reproduction instructions

Check the marks story for RangeControl in storybook.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by HILAYTRIVEDI** [comment]
@stokesman I can't able to generate the error.
https://www.awesomescreenshot.com/image/14134856?key=230c4db092cda02a0162b73b2166b348

**Comment by stokesman** [comment]
Thanks for testing this @HILAYTRIVEDI. I see from your screenshot that they are not off the rails completely but they are still not as expected. Posting a portion of your image here:

![image](https://user-images.githubusercontent.com/9000376/135118467-b5149efc-c4b4-4964-9426-bc681f7d178c.png)

The marks should be vertically centered on the rails.

**Comment by HILAYTRIVEDI** [comment]
#Range control marks center aligned #35206
@stokesman  I made the required code changes in this PR. Please review, thank you.

**Comment by ciampo** [comment]
Looks like #64481 was opened (and recently fixed) for this same issue. Going to close this PR.
