### ISSUE TITLE
frontend link in details info box

### ISSUE THREAD

**Issue by uniquesolution** [WordPress/gutenberg#35169]
## What problem does this address?
In block editor when we are in full screen mode, there is no direct link available to copy or open the frontend. We have to either go to settings => Page => Permalink or have to disable full screen mode and then at top adminbar provide the view page link.

## What is your proposed solution?
I suggest there should be one more place for easily getting the page frontend link, and that is details box at top bar of editor. See the screenshot for exact location https://ibb.co/q7cWHSX

**Comment by carolinan** [comment]
Hi
Maybe I misunderstood, but the preview button has a link where you open the page on the front end, without disabling full screen mode:
![image](https://user-images.githubusercontent.com/7422055/135029386-6268f0fe-8988-4a31-b01a-dfc514d23acc.png)

**Comment by talldan** [comment]
Closing this as per the above comment.
