### ISSUE TITLE
Consider notice or preventing blocks from going in positions in full site editor where they will not work

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#35162]
Certain blocks need to be placed with or within others to work in the full site editor. For example query pagination, doesn't work unless you put it in the query loop. However, you can place this anywhere on the site editor. This could easily lead to confusion. Whilst it does make sense that it works in the loop, it might be presumed knowledge others might not have. By limiting the use or notifying, creates a good experience for everyone and prevents frustration.

There are two options here I can think of, but there might be more:

- Add a notice when you try and place the block somewhere; it won't work.
- Don't allow the block to be used outside where it will work.

I understand this mechanism does need design, but I also think it needs discussion, so for now, adding the feedback label first.

**Comment by annezazu** [comment]
Thanks for opening this! I know there are a few efforts to make blocks more "context aware" (for ex with intrinsic design options). Some of this reminds me of discussions with the Navigation Block (https://github.com/WordPress/gutenberg/issues/30159) so, for now, I'm going to cc a few folks into the convo: @ntsekouras (for the query loop context) and @jasmussen (for the navigation block context).

**Comment by jasmussen** [comment]
I chatted with Tammie and we worked through the various cases to reproduce:

- The Query block can not be inserted outside of the Query Loop using either inserter.
- It can't be dragged out of the Query Loop in the canvas.
- But it can be dragged out of the Query Loop if dragging in the List View.
- It can also be copy/pasted outside of the Query Loop.

I did a quick similar test with the Navigation block which similarly limits Page Links from being moved outside of the Navigation block, and noted that I can neither drag it outside in the list view, or copy paste it outside.

So it seems like a fix is to investigate why it's possible to move the query pagination outside, and potentially fix that.

**Comment by ntsekouras** [comment]
👋 - I couldn't reproduce any unexpected behavior with `Query Pagination`... 🤔 

I tried both in post and site editors:
1. insert the block outside `Query Loop`
2. drag `Query Pagination` or any of its innerBlocks outside (both in editor and List View)
3. copy/paste `Query Pagination` or any of its innerBlocks outside

All pagination related blocks have the `parent` property set properly..

**Comment by jameskoster** [comment]
This issue spills out of the site editor into the post editor as well. It's currently possible to insert blocks like Post Content and Term Description in a post or page, which makes no sense at all (unless you have a Query in a post 🙈). 

> Don't allow the block to be used outside where it will work.

I wonder if the simplest solution is to contextually hide the block from the UI (inserter / quick inserter)? IE if I'm editing a post, there should be no way for me to find the Term Description block at all.

---

FWIW there are a number of circumstances in which this contextual awareness will be beneficial. These issues are related:

* https://github.com/WordPress/gutenberg/issues/27064
* https://github.com/WordPress/gutenberg/issues/31830

**Comment by ntsekouras** [comment]
>This issue spills out of the site editor into the post editor as well. It's currently possible to insert blocks like Post Content and Term Description in a post or page, which makes no sense at all 

This is a different issue whether to contextually hide/show some blocks. If the above issue can be reproduced, it's a bug in our block handling logic.

**Comment by jameskoster** [comment]
Fair enough. I suppose I'm just highlighting that there are various situations in the UX where this contextual awareness would be useful, in case it's something we can build in at a low level and utilise in these different circumstances.

**Comment by karmatosed** [comment]
> I couldn't reproduce any unexpected behavior with Query Pagination...

@ntsekouras were you using Chrome? I just wonder if that could be the problem as I am puzzled because pretty consistently I can copy/paste and do any of the steps @jasmussen outlined.

**Comment by carolinan** [comment]
I only tested the query (post template) and query pagination, and I am seeing the same as @ntsekouras, I can not insert, drag or copy/paste the blocks outside the parent query loop. Chrome and Opera on Windows.

In the site editor, when I copy the post template, and then paste it,
I do see the following message being added, and the block type for the message is paragraph:
_The Query block can not be inserted outside of the Query Loop using either inserter._

**Comment by ntsekouras** [comment]
>@ntsekouras were you using Chrome?

Yes

**Comment by annezazu** [comment]
This came up as a piece of feedback during the [tenth call for testing for the FSE Outreach program:](https://make.wordpress.org/test/2021/09/29/fse-program-testing-call-10-pattern-party/#comment-2098)

> It makes sense that ‘Post Categories’ and ‘Post Tags’ blocks can only work within the Query Loop block and when editing a Post and each would display categories and tags associated with that post. However, when someone tries to insert those blocks on the Page outside the Query loop block would just drop the spinning icon. Probably, because as we know Page has no category and outside the Query Loop, it can’t query the category. ‘Categories’ block would however work.


https://user-images.githubusercontent.com/26996883/136870326-74aaa8ad-37ba-46a8-87ee-5b6038ba4084.mov

**Comment by ntsekouras** [comment]
>However, when someone tries to insert those blocks on the Page outside the Query loop block would just drop the spinning icon.

The spinning issue for Post terms/categories has been fixed here: https://github.com/WordPress/gutenberg/pull/35957

**Comment by karmatosed** [comment]
I am unable to replicate what I could before today, so I am going to close this as my own ticket. Thanks, everyone.
