### ISSUE TITLE
Full Site Editing: Post title block breaks on editor view when it is set to be a link

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#35174]
### Description

With Full Site Editing enabled, open the editor view of a template. Add a `Post title` block to it, and using the block settings on the right, set it to be a link. The setting is called `Make title a link`. See that the block design breaks on the editor view. The block appears okay on live view though.

### Step-by-step reproduction instructions

- Enable Full Site Editing on your site.
- Click on the `Site Editor` menu on the left.
- When the template editor opens, add a `Post title` block to it.
- Activate the block setting `Make title a link` on the right.
- See that the block breaks on the editor view.

### Screenshots, screen recording, code snippet

A video of the issue is below:

https://user-images.githubusercontent.com/18581859/135055083-0f48edb6-35f2-4b72-b54c-c174e919c13c.mov

Looks okay when I try the same setting on the same block on a regular page editor:

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/18581859/135054622-02e83dce-d337-487a-b20b-249a961480bd.png">

### Environment info

- WordPress 5.8.1
- Gutenberg 11.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by arunsathiya** [comment]
It's worth noting that this happens only on the `Singular` template. It does not occur on `Index` template.

Also, my screenshot above shows that I have Jetpack installed, but I have tested on another site without Jetpack or other plugins. The only plugin active on my second site is Gutenberg. The issue occurs on it too.

<img width="1774" alt="image" src="https://user-images.githubusercontent.com/18581859/135055543-fbe0785f-1560-4fce-a900-9cd3d5736d22.png">

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/18581859/135055620-64c48654-5e4f-433a-ac26-c11c9ca2496a.png">

**Comment by annezazu** [comment]
Hey there! Thanks for filing this. I tried to replicate but wasn't able to, even when I tried to have the same inner block setup:

<img width="1261" alt="Screen Shot 2021-09-28 at 9 52 11 AM" src="https://user-images.githubusercontent.com/26996883/135100654-c72b886c-eac8-4bbf-bcb6-4e20bda86374.png">
<img width="773" alt="Screen Shot 2021-09-28 at 9 52 52 AM" src="https://user-images.githubusercontent.com/26996883/135100658-ec9eb03d-8436-45d8-89a5-e08695ca4ce0.png">

This was using Gutenberg 11.5.1 and WordPress 5.8.1 too.

**Comment by arunsathiya** [comment]
@annezazu Thank you for testing! To confirm, is that a FSE template editor, or a normal post/page editor? I ask because I am not seeing the selected template at the top of the editor. It appears as shown below:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/18581859/135102665-9a9b4f0c-3a8b-42dd-9cf6-666162ea10b6.png">

This issue occurs only on "Singular" template editor. I am not able to reproduce the issue on "Index" template editor.

**Comment by arunsathiya** [comment]
I also noticed that your editor reads "Template > Group > .." while mine reads "Document > Group > ..."

<img width="390" alt="image" src="https://user-images.githubusercontent.com/18581859/135103151-90e0e2f5-60f2-4c21-b7b1-c21c1809950e.png">

**Comment by annezazu** [comment]
Ah ha - I went straight into the template editor. No issues though with the Site Editor either:

<img width="1274" alt="Screen Shot 2021-09-28 at 10 22 01 AM" src="https://user-images.githubusercontent.com/26996883/135106265-b0e3a4bc-6b26-478e-aecc-acae743e91b8.png">

**Comment by arunsathiya** [comment]
@annezazu Could you enable the "Make title a link" option on the block settings on the right sidebar? When you do that, does the block crash?

**Comment by annezazu** [comment]
🤦🏼 Ah ha! Now can replicate - forgot to do that with this latest comment. Marking this as a bug :D

**Comment by jasmussen** [comment]
I can also reproduce on singular templates only:
<img width="477" alt="Screenshot 2021-09-30 at 08 22 32" src="https://user-images.githubusercontent.com/1204802/135398483-8ef85b4d-9f74-4c35-936a-839366f42889.png">
