### ISSUE TITLE
Cover Block: .alignleft & .alignright margins are being overwritten by inline styles

### ISSUE THREAD

**Issue by mikachan** [WordPress/gutenberg#35186]
### Description

When the Cover Block is left or right-aligned, there is no spacing between any wrapping content:

![image](https://user-images.githubusercontent.com/1645628/135084270-3b4a1fc7-8c20-482f-b56b-8ceac1b2f4e4.png)

This is caused by the inline styles overwriting the `margin-left: 2em` and `margin-right: 2em`:

<img src="https://user-images.githubusercontent.com/1645628/135084604-2fe9d3e8-a1d2-4563-84e0-eadfbb985edd.png" width="350" />

### Step-by-step reproduction instructions

1. Use the below example markup or insert a Cover Block
2. Add a couple of paragraphs next to the cover block
3. Align the cover block left or right
4. You should see the lack of spacing both in the editor and frontend

### Screenshots, screen recording, code snippet

Example block markup:

```
<!-- wp:cover {"url":"","id":761,"align":"left"} -->
<div class="wp-block-cover alignleft has-background-dim"><img class="wp-block-cover__image-background wp-image-761" alt="" src="image.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size">This is a left aligned cover block with a background image.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:paragraph -->
<p>The cover block lets you add text on top of images or videos.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>This blocktype has several alignment options, and you can also align or center the text inside the block.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The background image can be fixed and you can change its opacity and add an overlay color.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Make sure that the text wraps correctly over the image, and that text markup and alignments are working.</p>
<!-- /wp:paragraph -->
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I can no longer recreate this in WP6.3 - I will close this issue for now.
