### ISSUE TITLE
Disable "Height in pixels" when an embedded PDF is not shown inline

### ISSUE THREAD

**Issue by ilyakam** [WordPress/gutenberg#35195]
### Description

When I don't want to show an embedded PDF inline, I find it confusing that both controls for "Height in pixles" remain enabled. Instead, I would prefer that you disabled the slider and the input field so that it's clear that they have no effect on the embedded PDF when the inline preview is disabled.

### Step-by-step reproduction instructions

1. Draft a new post
2. Drag and drop a PDF
3. Open its block settings
4. Toggle "Show inline embed" to off
5. Adjust the slider and/or input field

**Expected**: not being able to perform step 5 because it doesn't make a difference while the PDF is not embedded inline.

**Actual**: I can change the values and "apply" them by enabling the "Show inline embed" toggle; however, this is confusing.

### Screenshots, screen recording, code snippet

![2021-09-28 - P2 - PDF Block - Disable Inputs](https://user-images.githubusercontent.com/183227/135147872-313ff516-e971-437d-afa6-5a2ae5152396.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by getsource** [comment]
Thanks much @ilyakam for the report!

I did a pass on this in #35207.

I opted to hide, rather than disable the controls, for the reasons you gave in the issue description (not useful and potentially confusing to users).

**Comment by ilyakam** [comment]
I agree, hiding the controls is a better idea! Thanks for taking care of this issue so quickly.
