### ISSUE TITLE
Future compatibility with plugins that add post meta fields and the post.php view

### ISSUE THREAD

**Issue by acosmin** [WordPress/gutenberg#352]
Hi! I just want to plan for the future and would like to know what exactly will happen with the `post.php` view and how plugins which make use of post meta and display custom fields will work when the new editor comes out :)

Thank you!

**Comment by acosmin** [comment]
Just to get things started, we have a few plugins using the `post.php` intensively:

ACF 1m+ active installs
CMB8 100k+ active installs + a thousands of themes using it as a drop-in library. 
Page builders
Most of the themes on .org use custom meta fields.

The numbers are high and I know the project may take up to a year to get into Core, but it's better to have some information on how meta fields will be handled.

Me and a few others had to abandon some projects (plugins/themes) because we don't know how everything will be integrated and we can't plan ahead.

Any info/pointers on this will be greatly appreciated.

Thank you!

**Comment by jasmussen** [comment]
The plan for addressing this is now detailed in #952. Thanks for opening this issue. For now I'm closing it as there's a plan to work on it with mockups in #952.
