### ISSUE TITLE
Range control breaks functionality at the styling level.

### ISSUE THREAD

**Issue by HILAYTRIVEDI** [WordPress/gutenberg#35208]
### Description

Description
While working on #34855, I noticed in RTL languages the range control stylings are messed up. They are still reflecting the LTR stylings instead of RTL.

### Step-by-step reproduction instructions

Step-by-step reproduction instructions
With WordPress set to an RTL language, interact with a range control and observe the stylings.

### Screenshots, screen recording, code snippet

https://www.awesomescreenshot.com/video/5421344?key=131c60abb9cd1554b0adbf3d9205fd7b

### Environment info

Gutenberg: 11.5.0-rc.1
WordPress: 5.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi,
does this only happen in Twenty Twenty-One or in other themes too?

**Comment by HILAYTRIVEDI** [comment]
> Hi, does this only happen in Twenty Twenty-One or in other themes too?

Hello @carolinan, yes it is happening in all the themes. So I guess it is problem with the component itself.

**Comment by stokesman** [comment]
Hi @HILAYTRIVEDI. It looks like this is a duplicate of #29519. Which even has an open PR to fix it but I think it's gone stale because with actual RTL language use there is no issue. It's more of an issue with testing RTL in a less complete way.
