### ISSUE TITLE
Wrapping TextControl in Tooltip results in error

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#35211]
### Description

Having this fragment of code in Edit function of the block:

```jsx
<Tooltip text="Klikni na prazan element za opcije ili počni tipkati">
	<TextControl
		className="prominent"
		value={ attributes.prominent }
		onChange={ ( prominent ) => setAttributes( { prominent } ) }
		// help="Upiši grad u kojem se održava događaj"
		placeholder="Istakni..."
		list="prominent-list"
		style={{color: attributes.prominentColor}}
	/>
</Tooltip>
```
gives this error:
```
The above error occurred in the <input> component:
    in input (created by ForwardRef(TextControl))
    in div (created by Context.Consumer)
    in StyledField (created by BaseControl)
    in div (created by Context.Consumer)
    in Wrapper (created by BaseControl)
    in BaseControl (created by ForwardRef(TextControl))
    in ForwardRef(TextControl) (created by Edit)
    in tooltip_Tooltip (created by Edit)
    in div (created by Edit)
    in div (created by Edit)
    in Edit (created by edit_Edit)
    in edit_Edit (created by WithToolbarControls(edit_Edit))
    in WithToolbarControls(edit_Edit) (created by WithInspectorControl(WithToolbarControls(edit_Edit)))
    in WithInspectorControl(WithToolbarControls(edit_Edit)) (created by WithInspectorControl(WithInspectorControl(WithToolbarControls(edit_Edit))))
    in WithInspectorControl(WithInspectorControl(WithToolbarControls(edit_Edit))) (created by WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(edit_…
```
It is `Tooltip` component that causes error, without it it works fine.
I expect adding tooltips to `TextControl` being common necessity. I resolved problem temporarily by adding title attribute, but with it I do not have so much control.

### Step-by-step reproduction instructions

Enter above code in Edit component of the block.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@Lovor01 It looks like you didn't include the error when copy/pasting. It just says 'The above error occurred in the <input> component'. Would you be able to check the console for the error? Thanks.

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @Lovor01 hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
