### ISSUE TITLE
Improve the comment selection interface in the Post Comment block

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#35215]
When you insert the Post Comment block, it asks you to input the ID of the comment you'd like to display:

<img src="https://user-images.githubusercontent.com/846565/135110270-16d0be0a-0416-4adc-b6a5-310f7fb9ce9f.png">

But there's no hint explaining what the ID is, or where to find it.

It seems to me that a low hanging fruit would be more copy explaining how to complete this task. 

But it may be better to design an enhanced interface that bypasses the user having to go and find the ID manually.

**Comment by javierarce** [comment]
I had never done it before, and the experience of looking for the id was confusing. If we could add an id column to the comments table in the admin, it would be then trivial to explain how to get the ids. I think that could be a good first step.

An enhanced design could include a list of the last X comments plus a search form.

**Comment by gziolo** [comment]
The plan is to deprecate the Post Comment block in favor of the Comments Query Loop block. I think this is a low priority task since it's marked as experimental in the plugin and it will never land in WordPress core.

**Comment by jordesign** [comment]
Closing this issue as the Legacy Comments block has been deprecated.
