### ISSUE TITLE
[Block] Media + Text: Support featured image

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#35221]
It would be great to have support for the post featured image in the context of the Query block so we could make Query block patterns like this:

<img width="660" alt="Screenshot 2021-09-29 at 15 56 46" src="https://user-images.githubusercontent.com/3593343/135283232-612ec498-73ca-42ad-b942-f57feefc835f.png">

/cc @mtias

**Comment by carolinan** [comment]
We can reproduce this design with rows or columns. But I think it may still be easier for many users to place the featured image in the media & text block.

**Comment by paaljoachim** [comment]
Current design:

![Screenshot 2022-09-22 at 12 21 45](https://user-images.githubusercontent.com/5323259/191722976-f94a9f40-12ec-45d5-bec7-6c1fa1f163b6.jpg)

Here is a look at the Cover block design:
![Screenshot 2022-09-22 at 12 24 17](https://user-images.githubusercontent.com/5323259/191759805-cb77f894-c658-447e-829c-c377834d9650.jpg)

Perhaps we could add the same UI which Cover block adds a Featured image into the Media & Text block?
@draganescu

**Comment by annezazu** [comment]
Punting to 6.5 as enough progress hasn't been made.

**Comment by annezazu** [comment]
Noting that the associated PR @carolinan started has had movement in the last week https://github.com/WordPress/gutenberg/pull/51491 but it's unclear if it'll make it in in time.

**Comment by colorful-tones** [comment]
Based on a recent Editor Triage async session - I'm moving this off the [WordPress 6.5 Editor Tasks board](https://github.com/orgs/WordPress/projects/148/views/1).
