### ISSUE TITLE
Post Title: return no markup if title is empty

### ISSUE THREAD

**Issue by mikachan** [WordPress/gutenberg#35224]
## What problem does this address?
Currently, if a post has an empty title, a heading tag is still rendered but with no content. This can cause problems with additional unwanted space, e.g. margin or padding from the heading element. However, I also think it makes sense not to render an element if the content is empty.

Here is an example:

![image](https://user-images.githubusercontent.com/1645628/135306869-9d401920-e80a-4bad-87e1-d4a9fe3a1956.png)

In this case, we wanted the post title to have large spacing around it, but if the title was empty it creates too much of a gap.

## What is your proposed solution?
If a post has an empty title, then the Post Title block should not return any markup.

**Comment by skorasaurus** [comment]
(I don't have an opinion at the moment, but others have requested the markup to be present) - https://github.com/WordPress/gutenberg/issues/29520

**Comment by MaggieCabrera** [comment]
> (I don't have an opinion at the moment, but others have requested the markup to be present) - #29520

A placeholder would be much better than an empty div creating an unwanted space. I think it would be good compromise in this case.

**Comment by carolinan** [comment]
I would prefer if there was a default like in the WordPress admin area where `(no title)` is displayed.
If this is implemented as suggested, it must respect existing filters, I am using this filter to add a title when the user has not entered one.

```
add_filter(
	'the_title',
	function( $title ) {
		if ( ! is_admin() && empty( $title ) ) {
			$title = __( '(No title)', 'textdomain' );
		}

		return $title;
	}
);

```
If the user does not want the title, they can also remove the block.

**Comment by scruffian** [comment]
I'm not sure I agree. Removing the block means going into the Site Editor, which feels like a more advanced use case, but I can imagine a lot of users not wanting titles on their pages.

**Comment by MaggieCabrera** [comment]
I think both options are valid: 

- wanting a placeholder if no title is added
- wanting the title to show for the posts that have it and no div to show at all (no margin/padding applied) for the ones that don't have it

Ideally, we could have option 2 and still have the filter that Carolina mentions still work. Maybe that title filter would need to apply markup if we are removing it from the block for option 1 to apply

**Comment by carolinan** [comment]
> I'm not sure I agree. Removing the block means going into the Site Editor, which feels like a more advanced use case, but I can imagine a lot of users not wanting titles on their pages.

This block can be placed anywhere not only in a template.

**Comment by scruffian** [comment]
> This block can be placed anywhere not only in a template.

True, but it will be placed in most single and page templates in most themes.
