### ISSUE TITLE
Usage of Flickity carousel cannot be used within block preview

### ISSUE THREAD

**Issue by snovosel** [WordPress/gutenberg#35229]
### Description

When implementing the third-party package `react-flickity-component` https://www.npmjs.com/package/react-flickity-component, usage of a block example by way of the BlockPreview component will throw the following error and crash the console:

```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node
```

Using the `git bisect` process I've been able to determine that this commit is what introduced this issue:
https://github.com/WordPress/gutenberg/commit/03d43d8424730212004cdf1ed842176ee9eec603

### Step-by-step reproduction instructions

1. Install the Coblocks plugin
2. within the menu inserter, hover the Gallery Carousel block within the menu - observe the block preview shown
3. hover onto another block within the menu and observe the editor crash with the above error

### Environment info

- Gutenberg 11.4+ 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I can't really see anything in 03d43d8 that might have caused it.

cc @ellatrix just in case you have any ideas.

I take it this was noticed via an incompatibility with coblocks given the mentioned issue (godaddy-wordpress/coblocks#2049)?

**Comment by ai2n** [comment]
I ran into a pretty much identical issue today, except it seemed to be triggered consistently by hovering over the Tiled Gallery block.

During testing, the issue persisted until I disabled the Coblocks plugin.

If you prefer I create a new issue report for this, please @ me and I'll do that.

**Comment by Thelmachido** [comment]
This is an issue that is coming because of CoBlocks so it was moved to the correct public repo: 

https://github.com/godaddy-wordpress/coblocks/issues/2416

The discussion is continuing there so I will be closing this issue.
