### ISSUE TITLE
Triggering Undo (Ctrl + Z) in Paragraph with inline formatting can move cursor unexpectedly

### ISSUE THREAD

**Issue by ephox-mogran** [WordPress/gutenberg#3524]
## Issue Overview

The caret representing where the user is typing is being reset back to the start of the block when triggering an undo inside a paragraph (Editable) if there are inline formatting elements (bold etc.). If you press Undo again, it often goes back to the right location.

Note, this is a TinyMCE bug. We will log it in the system, and let you know when it is fixed. 

## Steps to Reproduce (for bugs)

1. Create a new block (paragraph)
2. Type some words
3. Trigger bold with the keyboard (Ctrl + B)
4. Type some more words
5. Toggle off bold with keyboard (Ctrl + B)
6. Type some more words
7. Repeat a few times
8. Trigger Undo with Ctrl + Z a few times and watch the cursor

Note, if on a Mac, use Cmd instead of Ctrl.

## Expected Behavior

The cursor moves to just after the last word typed in the history.

## Current Behavior

The cursor jumps back to the start of the block on the first undo, then to the right place on the second undo, then to the start of the block on the third undo etc.

## Possible Solution

This will be solved inside TinyMCE's undo manager and caret positioning code.

**Comment by aduth** [comment]
@iseulde Do you know if this had been improved in recent improvements to the Undo history? (#4956)

**Comment by iseulde** [comment]
No, actually this will be worse for every action now because we don't store caret position at all with our history records (yet). It's a good question whether we want to do this or not.

**Comment by iseulde** [comment]
As commented last time, I think we need a decision here if we want to store caret position in history. Ds this something urgent? Need to be looked at before merge or not?

**Comment by iseulde** [comment]
Actually these last comments are different form what is reported, but the change in how we handle history makes this irrelevant now. Caret position will not move if you loop through history.

**Comment by mtias** [comment]
Let's close this for now. We can revisit.
