### ISSUE TITLE
Update alt=""  - Refresh Picture ALT description

### ISSUE THREAD

**Issue by tagol** [WordPress/gutenberg#35250]
### Description

Hello

I update der Piture Alt description.
But I did not Show on the Website.

solution: Delete Picture on the Page and  again insert.
Now the "Alt" Information show.

what am i doing wrong?
How can i update the Alt Informatione, without delete the Picture?

### Step-by-step reproduction instructions

1. Update the Alt description
2. Delete the Picture on the Page
3. Insert the Picture on the Page

### Environment info

- WP 5.6

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
There's an option in the sidebar for the image block:
<img width="287" alt="Screenshot 2021-10-12 at 3 28 59 pm" src="https://user-images.githubusercontent.com/677833/136911349-66169013-5461-4b6d-bf6f-cbfa0ba7b86f.png">

I think the 'alt' text from the media library is only added to block when creating a new block, it won't dynamically update.
