### ISSUE TITLE
Improve UX of "Move To" option 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#35262]
## What problem does this address?

It's unclear to me if this is an enhancement or a bug request so, for now, listing it as an enhancement :) If you select a block and use the ellipsis menu to select "move to", you're switched from Edit mode to Select mode without much clarity around what to do next. My expectation is that I'd actually be able to pick a final location for the block I was trying to move and instead you're left without much visual direction as to what is even possible to do (this is where it's unclear to me how this should work). Here's a short video showing the experience:

https://user-images.githubusercontent.com/26996883/135471589-beb2b9f5-d5a3-4bd5-b339-fa8f3e257504.mov

This was found thanks to a stream from @helen where she was trying to move a pattern from a block theme into the Header Template Part and thought she could use this functionality. 

## What is your proposed solution?

A few ideas:
- Give some sort of visual guidance to the user about either the modes switching from Edit to Select and what options one can take. 
- Rename the "Move to" option as it doesn't seem to live up to its name.

**Comment by javierarce** [comment]
The "Move to" label is a bit confusing for me too, but I think the current behavior of that option could be categorized as a bug since it doesn't reveal the black toolbar right away.

**Comment by annezazu** [comment]
Closing this out as https://github.com/WordPress/gutenberg/issues/60021 replaces the Select mode and this "move to" option is no longer available.
