### ISSUE TITLE
E2E: Clearing storage time cost

### ISSUE THREAD

**Issue by WunderBart** [WordPress/gutenberg#35269]
I've noticed that [clearing the `localStorage` in the `afterEach` hook](https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/config/setup-test-framework.js#L79) slows the specs down quite a bit: ~1.3s to each spec in my testing. For example, the `blocks/list.test.js` suite alone, when run locally, takes ~130s with the LS cleared after each spec and only ~74s without (43% faster). Is there anything we can do to optimize it? Would it be OK to clear it after each suite rather than each spec?

/cc @gziolo @youknowriad @tellthemachines @kevin940726

**Comment by youknowriad** [comment]
We could probably have a plugin that removes the local storage persistence entirely maybe

**Comment by kevin940726** [comment]
In my (local) testing, they are mostly only costing 1ms each call. I guess we need more testing before jumping into the conclusion?

**Comment by WunderBart** [comment]
> We could probably have a plugin that removes the local storage persistence entirely maybe

> In my (local) testing, they are mostly only costing 1ms each call

Sorry for not making this clear. You're right, the call itself takes just a few milliseconds tops. The delay comes from the fact that the LS is purged and anything that's there gets re-initialized (taking 1.3s) on each `it()`. So the solution to this issue could be having somewhat (partially?) persistent LS - maybe for the suite scope only?

**Comment by kevin940726** [comment]
I see! So the problem is in that specific test suite? Maybe it's worth to fix it in that test only then?

**Comment by WunderBart** [comment]
> I see! So the problem is in that specific test suite? Maybe it's worth to fix it in that test only then?

It actually applies basically to every test because we call `setupBrowser()` which clears the LS in the global `afterEach` hook. I think the delay comes from the fact that Gutenberg needs to fully initialize from scratch on each `it()` call. It makes sense from the determinism perspective, but I'm wondering if there's a reliable scenario in which we don't need to clear LS for each and every test. Does that make sense?

**Comment by kevin940726** [comment]
Does initializing take that long in every test? Or are them only taking `1.3s` in that specific test suite? So the problem isn't with _clearing_ the LS but rather we want to keep the cache across test suites for performance reasons. Any clue what's being stored in the LS that the tests take that long to initialize from scratch? We can cache them somewhere in the file system for most tests if that makes sense.

**Comment by WunderBart** [comment]
> Does initializing take that long in every test? Or are them only taking `1.3s` in that specific test suite? 

I've run all the block tests with and without clearing the LS, and in my testing, it added ~1.3s to every test.

**Comment by kevin940726** [comment]
Another way of thinking this is to investigate why it takes so long to initialize from scratch (cold start time), and focus on fixing that in our app since it's probably also affecting our end users as well.
