### ISSUE TITLE
Flaky test reporting: attach or link to artefacts

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#35278]
## What problem does this address?
Flaky tests are now raised as issues, which is really helpful.

Looking at the issue, it can still be difficult to establish what went wrong with a test run. For example, https://github.com/WordPress/gutenberg/issues/35257 where it doesn't seem possible to look at the test run that failed, possibly because it was retried. The error in the test is a little bit inconclusive.

## What is your proposed solution?
Having access to the artefacts within the issue would be really helpful.

**Comment by Mamaduka** [comment]
I think this only happens with flaky tests reports for PRs.
