### ISSUE TITLE
Let's add a Github Project board for WP 5.9.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#35279]
## What problem does this address?

There is no project board for WP 5.9 added yet to the above Project tab.
https://github.com/WordPress/gutenberg/projects

## What is your proposed solution?

Let's get a project board added as soon as possible. So that we can focus in on the issues that would be good to add to 5.9.

**Comment by gziolo** [comment]
It's done: https://github.com/WordPress/gutenberg/projects/62 🎉

**Comment by paaljoachim** [comment]
Ahh yes! Time to close this issue. Thank you Greg!
