### ISSUE TITLE
Allow for larger previews of block patterns, ability to copy patterns, and see favorites/most used

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#35274]
## What problem does this address?
Block pattern previews are too small.

## What is your proposed solution?
It would be very useful to be able to see block patterns within the editor in a similar way to how they are presented in the WordPress.org Pattern Directory (https://wordpress.org/patterns/).

One suggestion would be to allow a user to open a larger window (sitting on top of the editor perhaps) to browse, search, and preview patterns. This window would allow a user to copy or insert directly a pattern they like. Additionally, a way to favorite/save patterns for quick access later on other pages/posts within a site would be very useful as well.

Copied from [Core Trac-54167](https://core.trac.wordpress.org/ticket/54167).

**Comment by ntsekouras** [comment]
Related:
issue: https://github.com/WordPress/gutenberg/issues/26905
experiment: https://github.com/WordPress/gutenberg/pull/35006

**Comment by shaunandrews** [comment]
I believe #35773 resolves the main issue here: You can open a larger preview of patterns in a modal.

Adding the ability to copy a pattern, or save it to your favorites is likely in the future as the WordPress.org/patterns directory continues to improve.
