### ISSUE TITLE
Selectable Background for Query Loop Post Template

### ISSUE THREAD

**Issue by HairyCream** [WordPress/gutenberg#35276]
_## What problem does this address?_

As of WP 5.8.1 with Gutenberg Plugin 11.6 the options to customise the layout of the Query Loop Post Template are limited.

For example, the following Query Loop would display the Post Featured Image, Post Title, Post Excerpt inline.

![image](https://user-images.githubusercontent.com/6292620/135542351-a4c22456-38ed-4a28-b980-641751baf1e5.png)

I would like the Post Title and Post Excerpt to overlay the Post Featured image. This is a common design available with plugins, or could also be achieved with custom CSS.

_## What is your proposed solution?_

I suggest the Post Template block could have a Background option added, allowing the Featured Image to be selected. or other background options, such as color.

This is a similar suggestion to [#24660](https://github.com/WordPress/gutenberg/issues/24660#issue-681988640) although that discusses a similar option for the Group block.

Although a slightly different issue, I feel having a Link To Post option at the Post Template level would improve the user experience.

**Comment by paaljoachim** [comment]
That sounds like a very good idea @HairyCream Mike! Thank you for adding it!

I will ping Nik @ntsekouras so that he can take a look.

**Comment by ntsekouras** [comment]
👋 thanks for creating the issue @HairyCream !

I could also see that you found the relevant issue about this and this is great, but we can close this in favor of the existing one. The approach should be more generic as is described in a comment there: https://github.com/WordPress/gutenberg/issues/24660#issuecomment-682560933

>I don't think this is the right approach (the group block). I think it should be baked into background tools for any block. I also don't know if it should be abstracted to any dynamic property, at least not in UI. It could be as simple as a toggle on the background options (solid, gradient, image, video, featured image).

>There's been some discussions about allowing other properties (like text) to bet set to an entity (pos title). But that also proved to be maybe not necessary if you can just insert a post title block anywhere (within a cover block, etc).
