### ISSUE TITLE
Second headline shows mystery text obscured by new block-only when saving

### ISSUE THREAD

**Issue by Whirl3d** [WordPress/gutenberg#3528]
## Issue Overview

When saving a post from the editor, grey text (obscured by a headline block) appears behind the headline block.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

Chrome, no other plugins for WP environment
## Expected Behavior

Nothing in the UI should change and the UI shouldn't have overlapping text.
## Current Behavior

The UI changes and text from the new block appears to overlap other text that may be placeholder text.
## Screenshots / Video

![image](https://user-images.githubusercontent.com/1857220/32934767-0732e49c-cb3b-11e7-8664-cc701b4ed49e.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by Soean** [comment]
I can't reproduce the bug. Can you add the steps, you are doing before saving?

**Comment by youknowriad** [comment]
Closing, feel free to reopen when you provide more details on how to reproduce.
