### ISSUE TITLE
ShortcutProvider component not released in @wordpress/keyboard-shortcuts

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#35282]
### Description

https://github.com/WordPress/gutenberg/pull/34539 introduced the `ShortcutProvider` component. This is required by the `useShortcut` hook (used in places like `@wordpress/block-editor`), and effectively #34539 becomes an unintentional breaking change.

The `ShortcutProvider` component hasn't been released in `@wordpress/keyboard-shortcuts` yet, and the associated CHANGELOG.md isn't updated. I'm not sure I fully understand the [npm release process](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/release.md#packages-releases-to-npm-and-wordpress-core-updates) but I think the change needs to be in the CHANGELOG.md first?

Could `@wordpress/keyboard-shortcuts` be updated to include the recent changes?

### Step-by-step reproduction instructions

1. Install latest `@wordpress/keyboard-shortcuts` (3.0.2)
2. View module contents and note that `ShortcutProvider` is not exported

### Environment info

Gutenberg via npm modules

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mirka** [comment]
A related question I have is, if this _were_ listed in the CHANGELOG.md as a breaking change, would the release procedures have ensured that the npm package be released before the Gutenberg 11.6 release?

My concern is that there are breaking changes in a Gutenberg plugin release that aren't yet available in the released npm packages. It makes it difficult to build things in a way that works in both standalone environments (e.g. Storybook) and in dependency-extracted environments (`window.wp`).

**Comment by gziolo** [comment]
It looks like the most recent publishing to npm happened a month ago. We should perform another release as soon as Gutenberg 11.7 RC 1 is out (it should happen tomorrow). The npm publishing flow is constantly evolving. I have recently come to the conclusion that the best approach is to publish to npm as soon as the new RC for the Gutenberg plugin is ready as it helps with testing of the new npm release.

**Comment by mirka** [comment]
Sounds good, thanks!

**Comment by gziolo** [comment]
It should be now published to npm with `@wordpress/keyboard-shortcuts@3.0.3` based on the code from the upcoming Gutenberg 10.7 release.
