### ISSUE TITLE
Beta label on global styles looks like a button

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#35298]
Whilst it's great to show beta, I think having it not look like a button might be good. The problem is compounded by the fact that a lot is going on in this header:

![2021-10-02 at 00 40](https://user-images.githubusercontent.com/253067/135696305-de443db3-90ac-4b61-a9d1-76b64d80c799.png)

There are a few variations, and I think it depends on how obvious the 'beta' should be.

**Comment by jasmussen** [comment]
Definitely validm but given how very fleetingly temporary the chip is meant to be, it's probably not the highest priority, but as all things, open to PRs.

**Comment by mtias** [comment]
Closing this for now, the Beta label shouldn't stay there for long.
