### ISSUE TITLE
Feature image blog: text is too high in title

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#35297]
This was seen in Chrome, using latest build and TT1 to test. The title of the block is a little out of line:

![2021-10-02 at 00 22](https://user-images.githubusercontent.com/253067/135695466-b599c777-57a1-4a94-818d-b3b28f789d66.png)

My recommendation would be to change this to be:

![2021-10-02 at 00 24](https://user-images.githubusercontent.com/253067/135695507-68826419-ae9d-4608-8ab8-3d022c8d3c50.png)

**Comment by ntsekouras** [comment]
👋 I couldn't reproduce this with Chrome and  tt1 blocks `Version: 0.4.7` 🤔
