### ISSUE TITLE
Typewriter linebreak behavior

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#353]
In order to make the best possible writing experience, it would be good for text editing and scrolling to work similarly to how a typewriter works. That is:

- As you start typing in a blank editor, you type as usual.
- Once you've written enough and the amount of text starts reaching the bottom of the screen, plus minus 3 or 4 linebreaks, the scrollbar appears and stays permanently hugging the bottom of the screen. 

Video:

https://cloudup.com/cZjMkKjp7ZY

The behavior should be similar when you are typing in between large blocks of text, insofar as whenever you type type type there should still be 3 or 4 paragraphs worth of padding under the line at which you are typing. This will need some scrollbar tricking.

**Comment by iseulde** [comment]
We also tried this in core once, while fixing toolbars at the top and bottom. It's worth noting that you need to take more than ENTER into account. There's also typing that wraps when you reach the end, arrow keys, other types of input.

**Comment by jasmussen** [comment]
Great points.

> We also tried this in core once

That makes it sound like it was either proposed and rejected, or built and rejected. Can you recall the circumstances and reasoning?

**Comment by iseulde** [comment]
The circumstances were different, it was to keep the caret above the fixed bottom toolbar (word count, status, node path) when the "kitchen sink" is open.

**Comment by iseulde** [comment]
Same for the fixed top toolbar when you use the arrow keys to move the caret up, or hit backspace.

**Comment by jasmussen** [comment]
Except for the situation where you have the caret between paragraphs of long text, it seems to be working pretty well in the Calypso editor currently. Given a layout like https://wpcoredesign.mystagingwebsite.com/gutenberg/#admin, shouldn't it be possible to port the behavior and make it even better?

**Comment by aduth** [comment]
Some related Calypso experiments at https://github.com/Automattic/wp-calypso/pull/12346

Introduced there but later reverted was also behavior of preserving offset from bottom (pushing content up on newlines): https://github.com/Automattic/wp-calypso/pull/12346#issuecomment-288206636

**Comment by iseulde** [comment]
@jasmussen I have a *very experimental* branch to try this out: https://github.com/WordPress/gutenberg/compare/try/editable-typewriter
Atm it's very unpolished, just tried a few different things to see what works best etc. This one seems the most promising.

**Comment by jasmussen** [comment]
I like this a lot, @iseulde, it seems to work pretty well for me. 

As far as I can tell, there's only one niggle (which isn't too bad or a dealbreaker imo) — which is that as the typewriter effect kicks in, the scrollbar jumps as almost a flicker. Which, you know, makes sense because _that's how it works_. But I have to ask the obvious question: can this be solved by a bottom padding of sorts? Forgive me if that's a silly question.

**Comment by jasmussen** [comment]
As a bit of repository management, I'm going to close this ticket and file it in the "Ideas" project so we can revisit this in the future: https://github.com/WordPress/gutenberg/projects/8

Also worth noting that the base ingredients for typewriter scrolling will be implemented for mobile in https://github.com/WordPress/gutenberg/pull/5769.
