### ISSUE TITLE
Selecting all ( Ctrl + A ) in a classic block will copy the content to other blocks

### ISSUE THREAD

**Issue by naohanpen** [WordPress/gutenberg#35308]
### Description

If I do selecting all in a classic block, content in the block will be copied to other all blocks.
It may be technical bug.

( I'm not good at English, so my grammar may be uncorrected. )

### Step-by-step reproduction instructions

1. Visit post editor on WordPress, and create Paragraph Block and Classic Block.
2. On the classic block, select all content such use `ctrl + A`.
3. The selected contents may be copied to other blocks.

### Screenshots, screen recording, code snippet

Before Selecting:
![image](https://user-images.githubusercontent.com/88918376/135753386-bd70c22c-7197-4d16-b8a6-6f9a8d7ed89b.png)

After Selecting:
![image](https://user-images.githubusercontent.com/88918376/135753405-d9300d71-2cf4-4522-92d0-fab834ff9286.png)

### Environment info

- WordPress 5.8 & 5.9-alpha
- Google Chrome
- Window 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I was able to replicate this on trunk with OSX and cmd-a:

![cmd-a](https://user-images.githubusercontent.com/3629020/136720108-ad70ae04-9d28-4f6c-929f-bfc1293f819b.gif)

**Comment by glendaviesnz** [comment]
The issue happens some time after the [use-select-all](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/writing-flow/use-select-all.js) has completed - at that point the blocks are all selected as expected:

<img width="657" alt="Screen Shot 2021-10-11 at 5 17 17 PM" src="https://user-images.githubusercontent.com/3629020/136732627-2bc0e03a-9947-43ae-9027-c42cab79bf70.png">

At some point after that the content of each selected block is overwritten, but haven't managed to track down where exactly the happens yet, as stepping through the debugging session completes and the content is as expected, but is then overwritten when you focus somewhere in the editor again.
