### ISSUE TITLE
Selecting multiple blocks - Save as Pattern or Reusable block.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#35305]
## What problem does this address?

Selecting multiple blocks to create a Reusable block one needs to click the 3 dots (contextual drop down) to click Add to Reusable blocks. 

![Screenshot 2021-10-02 at 17 29 52](https://user-images.githubusercontent.com/5323259/135723079-31a1455b-76fe-4813-8371-61b7ea882efd.jpg)

It would be nice with a more direct method of selecting multiple blocks and saving these into Reusable blocks (Synced blocks) or Patterns.

## What is your proposed solution?

Adding icons for Reusable blocks and Patterns into the toolbar when a user has selected 2 or more blocks. (Need an icon for Patterns.)

![Muliti-select-save-as-Reusable-block-Save-as-Pattern](https://user-images.githubusercontent.com/5323259/135723207-cc64362a-0d1b-4f47-90c6-71f9e0b0499d.jpg)

Hovering over Patterns a tool tip is seen.
![Save-as-Pattern-tool-tips](https://user-images.githubusercontent.com/5323259/135723316-95601509-a2a2-4346-8549-0c6ee84134c7.jpg)

Associated:
Patterns: Create a pattern in a similar way to how we create a Reusable block.
https://github.com/WordPress/gutenberg/issues/31298

**Comment by mtias** [comment]
Done in #51144
