### ISSUE TITLE
Site Tagline: Support margins in theme.json

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#35323]
## What problem does this address?
The site tagline block uses a paragraph element, which means it inherits the margins from CSS for paragraphs:
<img width="829" alt="Screenshot 2021-10-04 at 13 49 30" src="https://user-images.githubusercontent.com/275961/135854296-4c19c26a-5e0a-4ba0-a91c-400fa26462f3.png">

## What is your proposed solution?
If we could control the margins in the theme.json, we could override these margins without CSS.

**Comment by carolinan** [comment]
I was able to reproduce this, but it is only the left and right margins that are overwritten, not top and bottom.
In the editor, this style is overwriting the tag line styles:

```
.editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper > *,
.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > * {
    max-width: 840px;
    margin-left: auto !important;
    margin-right: auto !important;
}
```

My theme.json style was:
```
"core/site-tagline": {
				"spacing": {
					"margin": {
						"top": "15px",
						"right": "15px",
						"bottom": "15px",
						"left": "15px"
					}
				}
			}

.editor-styles-wrapper .wp-block-site-tagline {
    margin-top: 15px;
    margin-right: 15px;
    margin-bottom: 15px;
    margin-left: 15px;
}
```

**Comment by carolinan** [comment]
Perhaps you could use padding as a work around for now?

**Comment by scruffian** [comment]
The issue in this case is that the block is inheriting margins from the theme's paragraph CSS, not from Gutenberg's. I could modify my theme CSS to include a `:not(.wp-block-site-tagline)` but I think it would be useful for themers generally to be able to control these margins.

**Comment by ndiego** [comment]
The Site Tagline block now [supports margin](https://developer.wordpress.org/block-editor/reference-guides/core-blocks/#site-tagline), so this can be closed.
