### ISSUE TITLE
Query loop displays non sticky posts when Sticky posts is set to only

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#35322]
### Description

If a WordPress install has no sticky posts, standard posts are displayed on the front when the query loop setting "Sticky posts" is set to "only".
This leads to an unexpected result if the theme developer has chosen one design for sticky posts, and another for standard posts. If the page has two queries, one for sticky only, and one without sticky, the posts are duplicated.

It works correctly in the editor.

### Step-by-step reproduction instructions

1. Trash or remove sticky from any sticky posts on your WordPress installation
2.  Add a query loop in the block editor.
3. Set the Sticky post setting to "only"
4. Confirm that no posts are displaying in the editor. The message "No results found." is shown.
5. Save and view the front. Confirm that non sticky posts are showing on the front.

### Environment info

WordPress 5.8.1
Emptytheme
Gutenberg, current trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
Thanks for reporting Carolina and for the excellent description/reproduction steps! I used your description as is for the PR 😄

**Comment by jffng** [comment]
When "sticky posts" are set to "Include" and "Inherit query from template" is also true, what is the intended behavior? Are the sticky posts supposed to appear first, or in the order they were published?

Currently it works like the latter, and I'm not sure if that's a bug related to this issue.

**Comment by carolinan** [comment]
Related: When the query loop is not set to` Inherit query from template`, and sticky posts are set to include, the sticky posts are shown first on all pages when navigating through the paged results. They are repeated on every page instead of only showing once.

**Comment by carolinan** [comment]
The problem with the sticky posts being repeated on top of page two+ seems to be because `is_home` returns false on the paginated result, resulting in that the sticky posts that have already been displayed, are not removed by WP_Query.

**Comment by carolinan** [comment]
I think that for the sticky posts to display correctly for both the default **and** for the home/blog  when `Inherit query from template` is enabled, we need one query for the standard posts and one for the sticky posts.
I don't mean two blocks, but two separate queries.

**Comment by KristofferBroberg** [comment]
Any progress on this? Bug is still present in WP 5.9. Should I open an issue?
