### ISSUE TITLE
Legacy widget: reorder the widgets alphabetically

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#35328]
Copied from Core-54105

### Problem

Right now the legacy widgets are displayed in some order which makes the list look quite random (see attached screenshot).

### Solution

Sorting them alphabetically should help the users find the widget they want faster.

### Screenshot

![Markup 2021-09-10 at 08 51 55](https://user-images.githubusercontent.com/107534/135893712-869ba142-0de7-42da-8f85-ef1bd2d00a1e.png)

**Comment by spacedmonkey** [comment]
Are you sure that this was fixed in [#53303](https://core.trac.wordpress.org/ticket/53303) and https://github.com/WordPress/wordpress-develop/commit/6194de49dcd79c9aeae7bd96722d69f752076f6f?

**Comment by draganescu** [comment]
Retested and it's fixed.
