### ISSUE TITLE
Duotone filter not rendering in some places

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#35331]
## Description

When applying duotone as a block style in theme.json, there are still a couple places the duotone filter doesn't get applied.

See https://github.com/WordPress/gutenberg/pull/34667#issuecomment-930287643

The thumbnail for block patterns that use duotone won't show the filter applied:
<img width="326" alt="Screenshot 2021-09-29 at 17 22 27" src="https://user-images.githubusercontent.com/3593343/135299678-875d8f83-45b5-4173-b455-6101f48ac32f.png">

The site editor shows the image without a filter but the frontend works fine. The post editor when I insert an image does work fine:
<img width="1254" alt="Screenshot 2021-09-29 at 17 22 51" src="https://user-images.githubusercontent.com/3593343/135299779-5eea53f3-2b62-4b4b-b5c0-8269d2d6f7cd.png">

## To reproduce

You can test on Skatepark applying https://github.com/Automattic/themes/pull/4740

Or by adding the following to your theme.json for testing the image and cover blocks.

```json
{
	"styles": {
		"blocks": {
			"core/cover": {
				"filter": {
					"duotone": "var(--wp--preset--duotone--blue-red)"
				}
			},
			"core/image": {
				"filter": {
					"duotone": "var(--wp--preset--duotone--blue-red)"
				}
			}
		}
	}
}
```

**Comment by ajlende** [comment]
The SVG containing the filter is generated during the [`admin_footer`](https://github.com/WordPress/gutenberg/blob/f45dce14bcb03b46783a826067547aeb698f2fc5/lib/block-supports/duotone.php#L326) hook which, I think, is causing the issue.

The assets for the site editor are generated during the [`admin_footer-toplevel_page_gutenberg-edit-site`](https://github.com/WordPress/gutenberg/blob/f45dce14bcb03b46783a826067547aeb698f2fc5/lib/client-assets.php) hook which is the last hook in [admin-footer.php](https://github.com/WordPress/wordpress-develop/blob/c69c34273a7537ba969c8e93d359735a1b58bb3a/src/wp-admin/admin-footer.php#L105), so the SVG never gets rendered.

**Comment by carolinan** [comment]
Did you try without using a preset var?

**Comment by andrewserong** [comment]
I'm currently working on refactoring a few of the block supports to ensure they render correctly in the site editor in #35450. I _think_ I've managed to get it working properly for Duotone in the Site Editor (haven't tested block patterns thumbnails yet) by outputting to `wp_footer` instead of `admin_footer`, but I'm keen for feedback on the PR as there's a lot of context to how Duotone was implemented that I might have missed! 🙂

**Comment by oandregal** [comment]
I'm marking this for 5.9. Please, feel free to remove if it isn't necessary.

**Comment by oandregal** [comment]
Braindump for when someone is able to pick this up.

While working on https://github.com/WordPress/gutenberg/pull/36236/ I discussed with Alex that for duotone to work on the site editor we need to port the same changes introduced in the server at https://github.com/WordPress/gutenberg/pull/34667 (and follow-ups). Refs:

- server: https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-5.9/class-wp-theme-json-gutenberg.php#L717 
- client: https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/global-styles/use-global-styles-output.js

**Comment by Mamaduka** [comment]
@oandregal, I'm removing this issue from WP 5.9 project board.

Feel free to add it back to a minor release board once it's created.

**Comment by ndiego** [comment]
@ajlende can this be closed now that #37727 is merged?

**Comment by ajlende** [comment]
https://github.com/WordPress/gutenberg/pull/37727 solved the problem for the site editor, but I've confirmed that there are still issues with the block/pattern previews.

<img width="1024" alt="Screen Shot 2022-04-19 at 11 19 44 AM" src="https://user-images.githubusercontent.com/5129775/164052646-ff05601b-b1c0-456b-b814-7c671548d426.png">

I haven't investigated why yet, but it seems some of the patterns are working, just not all of them.

![Screen Shot 2022-04-19 at 11 38 18](https://user-images.githubusercontent.com/5129775/164053153-1ce3df3f-256d-42b1-a543-96c10da2c394.png)

**Comment by matiasbenedetto** [comment]
A small PR with a potential fix for this issue: https://github.com/WordPress/gutenberg/pull/41249

**Comment by ajlende** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/41249
