### ISSUE TITLE
Navigation block HTML anchor doesn't add an id attribute to HTML

### ISSUE THREAD

**Issue by jacobcassidy** [WordPress/gutenberg#35349]
### Description

When adding and saving an "HTML anchor" in the Navigation block Advanced menu, no HTML id attribute is created for the nav element (adding class(es) works, however).

### Step-by-step reproduction instructions

1. Add a navigation block
2. Select the block settings for the navigation container
3. Open the Advanced dropdown menu in the block settings
4. Add an "HTML anchor" in the Advance dropdown menu
5. Save the page
6. Open the live page and use the inspector tool to check the HTML for the nav element you just created
7. Notice the lack of an "id" attribute.
8. Optional, go back to step 3 and add a class in the "Additional CSS class(es)" input field.
9. Do step 6 again and notice that the class has been added to confirm that classes are added but an id is not.

### Environment info

- WP version 5.8.1
- Gutenberg version 11.6.0
- No other plugins installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I believe this is a duplicate of https://github.com/WordPress/gutenberg/issues/29401

**Comment by jacobcassidy** [comment]
@carolinan, you are correct. I searched the "Navigation block" under projects and it didn't turn up in that list.
