### ISSUE TITLE
Insert Media dialog gets controls for: Thumbnail display squared/proportional + Sort order by date/name asc/desc

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#35346]
# Reproduction
- Edit a page
- Insert an image gallery
- The "Create gallery" (aka insert media) popup opens.

# The user experience in this dialog is problematic
<img width="1439" alt="Wordpress Gutenberg Insert Media Dialogue" src="https://user-images.githubusercontent.com/737143/136006147-246acd0e-74e5-4e93-8214-3e45d33de3d5.png">

# Problems
- This dialog follows the Wordpress design philosophy "decisions not choices" but here I'd propose "good defaults (=decision) which satisfy the majority but extra ad-hoc choices for users and use cases which require otherwise".

## Order is by upload date, newest first
- A good default suited for the majority of typical bloggers.
- In case you want to insert numbered image series or image stories (where upload order occurred not exactly in the lexicographical order) this gets a nightmare! Especially in combination with the other issue, read on.

## Squared thumbnails
- Very bad if you have many similar images, where the significant differences may be in the hidden areas.

# Proposals

The dialog gets extra controls. As illustrated in the mockup.

## Sort preference
- Dropdown menu with the choices "Date, Name"
- Nearby a toggle button for ascending or descending order
- "Date with newest on top" remains the default.

## Display preference
- Dropdown with these values:
  - "Thumbs" --> image fits container
    - Original image ratio is kept
    - Has no effect ofc if the source files were cropped due to: Settings > Media > Crop thumbnail to exact dimensions (normally thumbnails are proportional) = ON. But by default this is OFF as the remark in brackets indicates.
  - "Thumbs (squared)" --> image fills container
  - "List" with thumbs
  - "List (with micro thumbs)"

**Comment by talldan** [comment]
Hi @porg. The media library is a feature of WordPress core. Would you be able to create a ticket on WordPress trac for this - https://core.trac.wordpress.org/? Thanks.

**Comment by porg** [comment]
@talldan
- this issue here from 2021-10-05 would be the end user's feature
- and for "core" I had created a ticket on 2021-08-27 which would serve as the technical foundation:
[Internal links with href=outdated-slug and a data-type data-id as fallback should use that and update href=new-slug instead of resulting in broken link (404)](https://core.trac.wordpress.org/ticket/54024)
  - that core issue only got a classification "Component: Editor" by @SergeyBiryukov and nothing ever more since then.


@critterverse 
- Ensuring working internal incoming links to a page in case of a slug-change is a valid not so infrequent use case and user need.
- Currently broken incoming internal links due to a slug change nee to be manually fixed or fixed by help of two different kind of plugins (one for the HTML link markup fix, one with the HTTP redirection), instead of cleverly tackling the root cause of problem (the slug change in the page editor Gutenberg) and intercepting and fixing the problem right there!
- I'd appreciate a reaction.

**Comment by porg** [comment]
Pardon my previous comment from today. I deleted it now as I had posted it under the wrong issue. Sorry.

**Comment by porg** [comment]
Refiled this in core as:
👉 [Insert Media dialog gets ad-hoc controls: Thumbnails squared/proportional + Sort order by date/name asc/desc](https://core.trac.wordpress.org/ticket/57369)

**Comment by porg** [comment]
@critterverse pinging you to follow this issue (and its continuation over in the "core" issue tracker) as the "Insert Media" dialog is quite crucial for the UX of page editing, and hence is an essential part of the Gutenberg UX too.
