### ISSUE TITLE
Cover: Ability to drag to innerblocks broke

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#35345]
#29813 added the ability to drag and drop an image onto the edge of the Cover block to set just the background, or drag it in the innerblocks area inside to add as an image block inside. This behavior appears to have broken, so it's only possible to set the background:

![trunk](https://user-images.githubusercontent.com/1204802/136003712-69761ef4-8d37-4a7b-8b72-d3d9a666a32d.gif)

As part of #33132, the behavior and design of the upload dropzone is being refined:

![new](https://user-images.githubusercontent.com/1204802/136004869-cbb99e4a-de61-4f55-a383-0dfba03ba2a3.gif)

In light of that, it might be an opportunity to unify and simplify the design of the behavior. In part to have less bespoke CSS to customize components, in part to expand the utility of the components to work in more context. Outside of restoring the drag-over-edge behavior, one visual path forward might be to simply embrace that the blue upload card covers the full block, with reduced transparency to indicate its _background_ nature? Something to explore.

**Comment by Mamaduka** [comment]
@jasmussen, do we still want to restore previous drag-over-edge behavior here?

I think current behavior works well.

**Comment by jasmussen** [comment]
It's a good question, mainly because it's a larger question: what about other container blocks that can/will eventually have background support? 

The easiest solution is to decide: you can only ever drag and drop an image into a top level container. But for big site building contexts where you might want to drag an image into a deeply nested group, that's not a great solution.

The question then becomes: do we want the "drag to edge" behavior for groups once group blocks get the ability to have backgrounds? In my opinion: if the group block is big enough, yes! (You might have some really teensy Row blocks that barely have space for that edge clearance). This is probaly a complex one, though.

Another option is to not make it possible to drag and drop an image to use as a background, equally valid.

A fourth option, perhaps: embrae the actual footprint of blocks; if a Cover block has inner padding, you can drop an image on that padding and it'll set it as a background. If you drag it inside the actual content area, it's an image. This would scale to most cases, no? Even if it means you won't be able to drag and drop an image as a background on a default group block, which feels like an acceptable tradeoff. What do you think?

**Comment by jasmussen** [comment]
Since no-one has brought this up in a while, I'm going to close this one as not actually relevant. We can reopen if need be, but it also seems like there are some conversations we can have around how this needs to work in a more generic way once more than the cover block get the ability to have backgrounds added.

**Comment by Mamaduka** [comment]
Thank you, Joen, and sorry that I forgot about this issue 🙇

**Comment by jasmussen** [comment]
Heh, no worries, trying to clean up the backlog here!

**Comment by Mamaduka** [comment]
You are doing the important work!
