### ISSUE TITLE
Group block - no way to transform to "Row" and vice-versa

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#35355]
### Description

With the new row variation on the group block, there does not appear to be any way to transform a standard group block to row (flex layout), or the other way around from row to group.

Implementing this would be a huge time saver, as currently if you have say a group with the default layout, the only way to transform it to the flex layout (row variation) is to add a new "Row" group block and copy or drag the inner content to the new block and then delete the old now empty block.

Additionally, with a row block, toggling the 'Inherit default layout' option does transform it to the standard non-flex layout, but there is then no way to transform it back to the row variation.

### Step-by-step reproduction instructions

1. add a Group block
2. notice there is no option to transform to the "Row" variation.
3. add a new Row block
4. notice the only way to transform this to a standard Group block without flex layout, is to toggle the 'Inherit default layout' option on and then off.

### Environment info

WP 5.8.1
Gutenberg 11.6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sdwire** [comment]
Perhaps even worse... you **can** (accidentally) transform a Row into a Group, but then you can't put it back.

In a Row, if you toggle on the "Inherit default layout" option, the Row will suddenly become a Group. But toggling the option back off again will not change it back to a Row. Once you accidentally turn it into a Group, there's no going back. From there you have to create a new Row and manually drag back in all of the contents.

**Comment by skorasaurus** [comment]
@Sandstromer ; This was implemented in Gutenberg 12.6 - https://github.com/WordPress/gutenberg/pull/36202  :)
