### ISSUE TITLE
Modifying sibling block alignment causes temporary Cover block misalignment in Safari

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#35367]
### Description

When modifying the alignment of a sibling block of a Cover block, the Cover block will temporarily display misaligned in macOS Safari. Selecting the Cover block causes the alignment to update to the correct position. 

### Step-by-step reproduction instructions

1. Create a post in the block editor using macOS Safari. 
2. Add an Image block. 
3. Add a Cover block _after_ the Image block. 
4. Update the Image block's alignment. 
5. 💥 The Cover block jumps to an incorrect position, selecting the Cover block fixes the position. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/438664/136083609-4d0339a3-3e12-4dde-b92c-6ce312810d08.mov

### Environment info

- **WordPress:** WordPress.com 
- **Gutenberg:** v11.6.0 
- **Theme:** Twenty Twenty  
- **Browser:** macOS Safari 15.0 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment]
![safari-align-image-cover](https://github.com/WordPress/gutenberg/assets/4710635/40b58572-52de-44c0-8b8e-008b8d644915)

I can't reproduce this issue. Has this been fixed in the meantime? If not, could you copy paste the exact block configuration here?

**Comment by dcalhoun** [comment]
I am no longer able to reproduce. 🎉 I presume it was fixed after I reported it.
