### ISSUE TITLE
Allow themes to surface specific patterns from the Patterns Directory

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#35364]
With the launch of the pattern directory (and the upcoming ability for folks to submit their own patterns to it), we should consider building a route through which themes can highlight specific patterns to their users. 

Traditionally, themes have bundled their own proprietary patterns directly via PHP, and tend to highlight them in a category named after the theme: 

<img width="350" alt="Screen Shot 2021-10-05 at 1 56 50 PM" src="https://user-images.githubusercontent.com/1202812/136077179-d9d22907-9485-47b3-894c-0cd882138e0e.png">

This is fine, but it locks those patterns into that one specific theme. What if (for example) a theme could place all of those patterns directly in the Pattern Directory itself, and then reference them from within `theme.json`. These referenced patterns could either be highlighted in the inserter via a "Theme Name" category, or bubbled up to the top of the list and given a special "theme" badge of some kind.

This would:

- Cut down considerably on theme code. 
- Make theme patterns far easier to update, test, and review. 
- Encourage theme authors to seed the pattern directory with even more patterns. 
- Reduce pattern redundancy in the Pattern Directory by letting multiple themes reference the same simple patterns.

If a theme's pattern relied on special block styles, then the theme would still be free to register them the traditional way.

Related to #33046, #35115
This should maybe be part of https://github.com/WordPress/gutenberg/issues/31153?

**Comment by ntsekouras** [comment]
@ryelle how do you think this would be best implemented in patterns directory? I guess people would need to create/select their own category and also maybe have a way to get the data needed for fetching individual patterns(like an `id`)? 🤔 

Do you have any info about the roadmap of opening the patterns submission there? This issue needs some work on pattern directory first and the implementation in GB would be match simpler by adding some fields in `theme.json` to retrieve and register some patterns.

**Comment by ryelle** [comment]
I don't think we've discussed this, but the pattern slug (ex, `cover-with-title-and-audio`) would probably be a good identifier. The API could then be updated to accept `name=cover-with-title-and-audio` or something similar, and return a single pattern result… or a list of `name`s and return the full list of patterns for the theme, to avoid multiple API calls.

> create/select their own category 

Could patterns defined in the `theme.json` default to being shown in a category with the theme name? Like how the Twenty*s work now.

**Comment by ntsekouras** [comment]
>Could patterns defined in the theme.json default to being shown in a category with the theme name? Like how the Twenty*s work now.

I'm not sure about the nuances of the `theme.json` property implementation, but when we have an API to fetch them, we'll find a good solution. My first thoughts is that the `categories` will be from the fetched pattern, because if a theme fetches patterns created from others, is it okay to show them under a the theme's label?  🤷 

Could the patterns have a new `theme` property as well to get them all together?

**Comment by ryelle** [comment]
> My first thoughts is that the categories will be from the fetched pattern

Ah, true. I was still thinking we would want them also grouped under a "Theme" label. They could be all of the above, since patterns can have multiple categories. You could find a pattern under "Theme Name" and also under "Header" and "Text".

> Could the patterns have a new `theme` property as well to get them all together?

Do you mean on the Pattern Directory side?

**Comment by ntsekouras** [comment]
> >Could the patterns have a new theme property as well to get them all together?

>Do you mean on the Pattern Directory side?

I meant in their definition in general, but if we register a theme's category in their patterns, we will fetch them all by this specific category. So the question was more whether we store the theme's category in patterns or in a separate field and is probably about if this matters with how `patterns directory` works internally.

**Comment by kjellr** [comment]
> Could the patterns have a new theme property as well to get them all together?
> Do you mean on the Pattern Directory side?

I may not be following this correctly, but in general, I don't think we want to be tagging patterns for a specific theme in the pattern directory, since an individual pattern could (theoretically at least) be used for more than one theme.

**Comment by bph** [comment]
In issue #41282 you'll find a suggested way on how to implement a curated list of patterns from the pattern directory.
