### ISSUE TITLE
Allow pasting of images from Clipboard

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#3537]
One of my favorite features in GitHub is being able to paste images from your clipboard directly into the editor. This would be a great future enhancement for Gutenberg.

**Comment by mtias** [comment]
This works already but is not easy to trigger.

**Comment by iseulde** [comment]
Can confirm this in broken in Chrome. Works in Safari and Firefox.

**Comment by bkjproductions** [comment]
Couldn't you simply adopt the Image Elevator plugin's code for this?
https://wordpress.org/plugins/image-elevator/
