### ISSUE TITLE
Add end to end tests for post locking

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#35377]
## What problem does this address?
When reviewing #35361, I noticed there are no end to end tests for post locking.

## What is your proposed solution?
It would be great to add end to end tests to cover this functionality. To lock a post in a e2e test it should be a simple matter of running `await page.evaluate( () => wp.data.dispatch( 'core/editor' ).lockPostSaving( 'futurelock' ) );`.

The two test cases that would be need are:
- `it disables the publish button when a post is locked`
- `it disables the save shortcut when a post is locked`

The second one might be a little tricky, as the test would need to prove that nothing happens, but the first should be straightforward.

There are some files for the publishing panel and publishing process where the tests could be added:
- https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/specs/editor/various/publish-panel.test.js
- https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/specs/editor/various/publishing.test.js

**Comment by Sidsector9** [comment]
I would like to pick this up

**Comment by talldan** [comment]
Thanks @Sidsector9, feel free to ping me if you need any help along the way.

**Comment by amustaque97** [comment]
Looks like no one is working on this issue. I would love to give it a shot 😉 . Assigning to myself. 😃
