### ISSUE TITLE
Meta boxes as seen in version 1.7.0

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#3538]
I am testing version 1.7.0

I happen to have a Genesis theme activated and that automatically adds Theme SEO setting metaboxes into a post/page content screen.

This is what I see:
![screen shot 2017-11-17 at 22 29 05](https://user-images.githubusercontent.com/5323259/32969826-ccf1d5a2-cbe6-11e7-9a7b-e2f45aaf922e.png)

Gutenberg content area:
Add Title
Write your story 

+

Metaboxes area.

The meta boxes area should be like an accordion one can open and close. As the Theme SEO Settings is taking a lot of screen space. Leaving very little space for beginning to add content. This is not a blank piece of paper one begins writing in. Perhaps the meta boxes should begin with the meta boxes title and to the right of it an up/down arrow. To begin with either having it open or closed. As there should be some better visual ques to create a seperation of meta boxes and the content.

Perhaps something like this.....(This is just based on the above.)
![meta-boxes-adjustment-gutenberg](https://user-images.githubusercontent.com/5323259/32970167-21199470-cbe8-11e7-812e-68e918a3c65e.jpg)

**Comment by mtias** [comment]
Please, check the previous iterations here https://github.com/WordPress/gutenberg/pull/3147 as it was originally a collapsible box and there was a lot of feedback about it.

**Comment by paaljoachim** [comment]
Ahh thanks Matias!
