### ISSUE TITLE
Gallery is not working

### ISSUE THREAD

**Issue by jinlarse** [WordPress/gutenberg#35386]
### Description

Wordpress 5.8.1 the gallery will not work, its only open a single picture and no opportunities to browse further in the gallery

seean example where the gallery is not working: https://www.dagsturhelgeland.no/kvalvika/

### Step-by-step reproduction instructions

open the url
scroll down to where the gallery is in the page
click on a picture
the picture is open in the browser instead of opportunities to browse further in the gallery

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
> the picture is open in the browser instead of opportunities to browse further in the gallery

@jinlarse I don't think the gallery block in WordPress provides this feature.

I think you might have a plugin that previously did this and is now not working.

**Comment by glendaviesnz** [comment]
@talldan is correct that the current core gallery block does not offer a lightbox type function that allows you to open the full version of the gallery and scroll through them. It requires a plugin to do this, so probably the next step is to check your installed plugins and see if one of them is related to this, and if so post a question to their support forum. 

@jinlarse one other thing you might want to check is that you have selected attachment or media as the image link option in the gallery as some of the lightbox plugins require the Gallery `Link to` option to be set to one of these options to work.
