### ISSUE TITLE
ToggleGroupControl: Visual state of an undefined value is inconsistent

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#35383]
### Description

The visual state of an initial undefined `value` is different from when the value is set _back_ to undefined after being set to a defined value.

### Step-by-step reproduction instructions

1. Render a `ToggleGroupControl` with `value` initially undefined.
2. Render a `button` with an `onClick` to set the `value` to undefined.
3. Click on one of the toggle group options, then click the reset button.

https://codesandbox.io/s/togglegroupcontrol-undefined-state-h8z9q?file=/src/App.js

### Screenshots, screen recording, code snippet

<img src="https://user-images.githubusercontent.com/555336/136142988-08c437c5-fec3-4d2e-b38f-f515e411ddc7.gif" alt="An initial undefined value looks different from when the value is set from a truthy value back to undefined" width="300">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sRahul-00** [comment]
Hey there, can I work on this issue?

**Comment by mirka** [comment]
@sRahul-00 Sure thing, thank you!

I'll add that I probably think the correct visual state for undefined should be the initial, white one, instead of the black with grayed out text. Would you agree?

**Comment by sRahul-00** [comment]
> @sRahul-00 Sure thing, thank you!
> 
> I'll add that I probably think the correct visual state for undefined should be the initial, white one, instead of the black with grayed out text. Would you agree?

Yeah man!! Totally agreed...

**Comment by ntsekouras** [comment]
Hey @sRahul-00 👋 - thanks for your interest for this issue! Really appreciate it!!

This fix will be needed for the next WP version 5.9 and is a bit of time sensitive. Would it be possible to work on this soon? I'm happy to help and guide you with whatever you need 😄 

>I'll add that I probably think the correct visual state for undefined should be the initial, white one, instead of the black with grayed out text. Would you agree?

Yes, the backdrop should be removed when the selected value doesn't exist as an option.

**Comment by sRahul-00** [comment]
> Hey @sRahul-00 👋 - thanks for your interest for this issue! Really appreciate it!!
> 
> This fix will be needed for the next WP version 5.9 and is a bit of time sensitive. Would it be possible to work on this soon? I'm happy to help and guide you with whatever you need 😄

Yeah, sure. I'm new to this Open Source World, so I will be thrilled to work upon new opportunities.

**Comment by ntsekouras** [comment]
Hey @sRahul-00 👋 - that's great! So did you try anything for the issue? Will you pick it up?

**Comment by sRahul-00** [comment]
> Hey @sRahul-00 👋 - that's great! So did you try anything for the issue? Will you pick it up?

I'm really sorry. I couldn't a thing as I was really busy due to the construction going in my home. I'm really sorry again.

**Comment by ntsekouras** [comment]
No worries at all! Do you want me to pick it up and find yourself another good first issue? I'd be happy to help either way - you can ping me in the `wordpress.slack` for anything you want 😄

**Comment by sRahul-00** [comment]
yeah sure!! But after you're done, I request you to tell me how did you fix it. It'd be really helpful for beginner like me. Best of Luck btw
