### ISSUE TITLE
ToggleGroupControl: Missing border when initial `value` is undefined

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#35382]
### Description

When the initial value of a `ToggleGroupControl` is undefined, there is a missing border after the first item.

### Step-by-step reproduction instructions

```jsx
  <ToggleGroupControl value={undefined} >
    <ToggleGroupControlOption
      key="foo"
      label="foo"
      value="foo"
    />
    <ToggleGroupControlOption
      key="bar"
      label="bar"
      value="bar"
    />
  </ToggleGroupControl>
```

### Screenshots, screen recording, code snippet

<img src="https://user-images.githubusercontent.com/555336/136142065-73d770c0-42e8-4727-8bc4-b86d73c1f464.png" alt="ToggleGroupControl with missing border after first item" width="300">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by amustaque97** [comment]
I will be working on this issue. Will link a PR soon 😄

**Comment by ntsekouras** [comment]
Fixed by: https://github.com/WordPress/gutenberg/pull/35409
