### ISSUE TITLE
Inherit query from template no longer works on the front

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#35398]
### Description

With current Gutenberg trunk, I can not see any posts on the front on index and archive templates if the Query loop setting "Inherit query from template" is enabled.

_I suspect this was lack of testing of https://github.com/WordPress/gutenberg/pull/35329 on my part._

The posts show correctly in the editor.

### Step-by-step reproduction instructions

With reading settings set to display your latest posts:

1. Activate a block theme for example Tove or TT1 Blocks.
2. View the front -no posts are showing.
3. View an archive page -no posts are showing.

Optionally open the site editor and view that the posts are displaying correctly on these templates

### Environment info

WordPress 5.8.1, current Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
Let's revert and investigate the `sticky` issue better.
