### ISSUE TITLE
Paragraph Block: Provide a way to add a placeholder via Visual Editor

### ISSUE THREAD

**Issue by AliSoftware** [WordPress/gutenberg#35399]
## What problem does this address?

Adding a Placeholder for a Paragraph Block can only be done via the Code Editor.

If you want to provide a placeholder for a paragraph (useful e.g. when writing a pattern), you currently need to switch your editor to Code Editor, in order to be able to edit the code like so:

```
<!-- wp:paragraph {"placeholder":"Your placeholder text here"} -->
<p></p>
<!-- /wp:paragraph -->
```

I only discovered that useful placeholder feature by accident (editing another post), so the current way doesn't help discovery either.

## What is your proposed solution?

Provide a way to set a placeholder text to a Paragraph Block directly from the Visual Editor – maybe in the Advanced section of the Block Inspector panel?

**Comment by talldan** [comment]
I don't think this is intended as a user facing feature, it's more of a developer feature.

An alternative option might be better documentation for block attributes, which I think is tracked somewhere in github.

**Comment by jasmussen** [comment]
I'd echo Dan that it feels worth it to continue to elevate the docs to enhance this as far as is possible. One additional idea is to enhance the WordPress Pattern Directory submission process, of which [some plans are outlined here](https://make.wordpress.org/design/2021/03/30/wordpress-org-patterns-directory/). In this context, the UI might offer a good spot for contextual tips here.

**Comment by jordesign** [comment]
With no further discussion on this issue, and the fact that it sounds like an unlikely addition, I'll close it for now.
