### ISSUE TITLE
Starting with a blank piece of paper

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#3539]
Rethinking Gutenberg from the perspective of starting out blank. (This might even look similar to the evolution of TinyMCE...)

(Today)
![screen shot 2017-11-19 at 10 23 45](https://user-images.githubusercontent.com/5323259/32989298-c3a9b16c-cd13-11e7-8856-c81b45bb8115.png)

Instead of the above lets define a writing space as if it is a sheet of paper.

(New wireframe)
![starting-blank-gutenberg](https://user-images.githubusercontent.com/5323259/32989302-dbd1eac0-cd13-11e7-826e-223b6db82d6d.jpg)

NB! Image should rather be media giving a broader option for the user. 
There is no need to add paragraph. As the text document area is always present. Just click into the space and begin writing. Selecting text options for adjusting it should also show up.

**Comment by karmatosed** [comment]
I think right now @paaljoachim we have to test and let the UI stand as it is. We can iterate based on feedback as we get it from usability tests, but I do not think this is a good path for us to follow. We need to focus a little.
