### ISSUE TITLE
Animated 3 dots - visual clutter.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#3540]
I believe it creates a visual distraction having the 3 dots on the right when clicked animate.
From a vertical line of three dots to when clicked go into a horizontal line.

Btw
The top right 3 dots do not animate. Please keep the individual block 3 dots the same way.

**Comment by karmatosed** [comment]
Animation helps as contextual feedback, lets keep it for now. I would say if anything add for both. Let's test though and not remove it.
