### ISSUE TITLE
Layout: top margin overwrites theme.json block CSS when gap support enabled

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#35411]
### Description

Since Gutenberg 11.7 (in https://github.com/WordPress/gutenberg/pull/34491), the `gutenberg_get_layout_style` method adds the following CSS to `.wp-block-post-content` children and their adjacent siblings where block spacing support (A.K.A `blockGap`) is enabled:

```css
> * + * {
    margin-top: var( --wp--style--block-gap );
    margin-bottom: 0;
}
```
See [layout.php](https://github.com/WordPress/gutenberg/blob/release/11.7/lib/block-supports/layout.php#L68).

Block spacing support was introduced in https://github.com/WordPress/gutenberg/pull/33991.

For blocks that have opted-in to block spacing, such as the Columns block or in the  [PR for the Social Links block](https://github.com/WordPress/gutenberg/pull/35374), this CSS's specificity overwrites any block-specific top and bottom margins in `theme.json`.

Noticed by @stacimc when testing https://github.com/WordPress/gutenberg/pull/35374#issuecomment-936825363 👍 

### Step-by-step reproduction instructions

Set a top and bottom margin for the `core/columns` block in your `theme.json` 

```json
       ...
	"styles": {
                 ...
		"blocks": {
			"core/columns": {
				"spacing": {
					"margin": {
						"top": "20px",
						"bottom": "30px"
					}
				}
			}
		}
	}
```

In a new post, insert a Columns Block as a second block, for example, insert a paragraph first, then columns.

Save the post and inspect the styles.

#### What I expected

The `theme.json` styles would take precedence over any plugin-generated block layout styles.

#### What happened

The plugin-generated block layout styles take precedence. See screenshot below.

### Screenshots, screen recording, code snippet

<img width="821" alt="Screen Shot 2021-10-07 at 11 34 10 am" src="https://user-images.githubusercontent.com/6458278/136304109-751fb91d-477d-48d5-aae3-9fcbf7349766.png">

### Environment info

- WordPress 5.8, Gutenberg 11.7, TT1 Blocks

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ulziibat-n** [comment]
I have the same problem.

**Comment by ramonjd** [comment]
Closing. Cannot reproduce as of 14.3
