### ISSUE TITLE
Visual clutter - Adding multiple Paragraphs gives multiple placeholder texts

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#3541]
Clicking to add a paragraph adds another block with placeholder text that looks like this:
 
![screen shot 2017-11-17 at 23 08 11](https://user-images.githubusercontent.com/5323259/32971166-46cb9ff2-cbec-11e7-903e-43a98857b358.png)

The focus on the above is blocks not thinking adding content. By thinking about content it would not look like the above. Adding a new paragraph when thinking content.... would be something like this... I click to add a paragraph and the cursor jumps into the box so that I can begin to write. It would not create a bunch of boxes.

![screen shot 2017-11-17 at 23 11 19](https://user-images.githubusercontent.com/5323259/32971270-afe5d62e-cbec-11e7-8feb-43a0691b06bb.png)

**Comment by mtias** [comment]
You already reported this :) #2466

**Comment by paaljoachim** [comment]
Thanks for reminding me..:) I thought it was some new clutter..:O
