### ISSUE TITLE
Block inserter padding

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#35419]
### Description

This may be entirely intentional, but the block inserter seems to have more left padding than it does top and bottom, giving a slighly off-centre appearance:

![image](https://user-images.githubusercontent.com/1277682/136346399-a54659d1-f7aa-42de-a21c-86fb54cac3bf.png)

Here there are 24px of left padding, but if you look at the settings menu:

![image](https://user-images.githubusercontent.com/1277682/136347154-9d4f39b4-6862-47ae-9cdc-cb569f8ebf32.png)

There's only 16px of right padding.

In mobile this padding goes the other way and seems too small:

![image](https://user-images.githubusercontent.com/1277682/136346475-c4e713de-05c2-47dc-bad2-52b92e2e01c9.png)

### Step-by-step reproduction instructions

No steps needed

### Environment info

Gutenberg 11.6.0, Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by javierarce** [comment]
I agree with the problem. I can imagine that the different paddings are an attempt to align the items optically so they look good in normal situations (when the setting menu is not selected).

If we were to use the same number for the left and right padding, we'll end up with the problem of the toolbar in the middle of the image below: it would only look good when the settings menu is selected.

I think we could make the toolbar look more centered by reducing the right padding and setting its value to 8px.

![image](https://user-images.githubusercontent.com/4933/136423355-c584cf0f-d549-459b-8c23-8cb6bd831b11.png)

**Comment by youknowriad** [comment]
Doing some triage. cc @jasmussen in case this is still valid or if the current behavior is the expected one.

**Comment by jasmussen** [comment]
Indeed, this has since been changed and addressed through other means. Closing as fixed.
