### ISSUE TITLE
Inserter adding an image --> Add multiple images.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#3542]
Hovering over the inserter one can add a paragraph or an image.
One should also be able to select multiple images if one wants to do so automatically creating a gallery if one chooses to.

**Comment by youknowriad** [comment]
The blocks showing there are the most used blocks. If a person uses the "gallery" block a lot, it will show up. We can't show all the available blocks there.

**Comment by paaljoachim** [comment]
It starts out with paragraph and image. It might as well said media. Not just 1 image.
But opening it up so the user can select media, audio, video, 1 image or multiple images.

**Comment by youknowriad** [comment]
It's just a block, this means we'd have to build a custom UI to switch between blocks. And we're not sure the said blocks exist. (Core blocks are registered like any other block, we can't hard-code them). That said it's possible to add "special" APIs to allow this but I'm not sure it's worth the complexity.

**Comment by mtias** [comment]
Closing in favor of #3364.
