### ISSUE TITLE
Group block do hot have container child if HTML element isn't div

### ISSUE THREAD

**Issue by simkoG** [WordPress/gutenberg#35431]
### Description

The Group block has a helpfull inner container by default (`.wp-block-group__inner-container`). It comes handy if you want to make your group `.alignfull` but you want your inside content to be have max-width property.

If you change the default `div` HTML element to something else (eg. `section`) the inner `.wp-block-group__inner-container` div will be missing. 

It would be great if you would add this inner container to the other HTML elements for the Group block, too. 

### Step-by-step reproduction instructions

1. Add a Group element
2. Set the alignment to full width

The generated code will contain a `.wp-block-group__inner-container` `div` inside the `.wp-block-group` element.

3. Change the Group block to a `section` tag. (Show more settings > Advanced > HTML element > <section>

Now the `.wp-block-group__inner-container` missing from `.wp-block-group`. 

### Screenshots, screen recording, code snippet

Code showcase: 
https://gist.github.com/simkoG/88479bf1a45a9398049530c1bf728893

### Environment info

- Wordpress: 5.8.1
- Gutenberg version: 11.6.0
- (theme, browser and device is irrelevant)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by chthonic-ds** [comment]
Previous discussion at https://github.com/WordPress/gutenberg/issues/31061.

**Comment by Mamaduka** [comment]
The issue was fixed via #36256.
