### ISSUE TITLE
Row (Group variation) styling doesn't work for themes without `layout` support

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#35439]
### Description

The generated styles for the Row variation of the Group block do not work for themes that haven't enabled `layout` support in their `theme.json` (or just lack a `theme.json` entirely). This old Group markup, which has a nested div for the content with the class: `wp-block-group__inner-container`, is not accounted for in the generated front-end styles.

The result is that, when using these themes, although you can easily insert a Row in the block editor (and it looks just fine there), the Row erroneously appears the same as a vertical Group on the front-end.

### Step-by-step reproduction instructions

1. Use a theme that doesn't declare `layout` support. (Astra is a popular one.)
2. Create/edit a page in the block editor, insert a Row (the quickest way is to use the slash inserter in an empty Paragraph).
3. Insert some blocks into the row. Observe that it looks correct in the editor.
4. Save and view the page on the front-end. Observe that it looks wrong.

### Environment info

Wordpress 5.8.1

Gutenberg 11.6.0 (also happens in latest `trunk` as of when I'm making this issue)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
Hi @ZebulanStanphill I tried debugging this but failed for now. In 2021 theme which doesn't support "layout" either, it works properly.

The issue comes from the fact that the `wp-block-group__inner-container` div is added to the frontend when using Astra theme. but we do have logic in place to prevent this div from being added in `gutenberg_restore_group_inner_container`. I wonder if Astra is doing something special with that hook.

**Comment by Sandstromer** [comment]
Yes it seems to an issue with the Astra theme.

See `astra/inc/compatibility/class-astra-gutenberg.php` L24 the comment:
_Add Group block inner container when theme.json is added to avoid the group block width from changing to full width._

and L35 `restore_group_inner_container()` function.

**Comment by ZebulanStanphill** [comment]
Thanks, I've opened an issue at Astra's GitHub: https://github.com/brainstormforce/astra/issues/3431
