### ISSUE TITLE
List View: Replace template icons with template symbols

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#35453]
Followup to https://github.com/WordPress/gutenberg/pull/34002#issuecomment-904409098.

New generic symbol icons for template parts and reusable blocks were introduced in 34002:

> The icons are stacked to indicate that they are "linked" — editing one edits it everywhere. By sharing the overall silhouette, the relationship between template parts and reusable blocks are hinted at. They are similar, but not the same. By being generic icons reused across the list view, the structural nature of those block types become implied, clearly differentiating them from content.

The dedicated header/footer template part icons are still useful in [the future template part selector](https://github.com/WordPress/gutenberg/issues/29295):

<img width="298" src="https://user-images.githubusercontent.com/1204802/128333827-7642d66a-e0ec-4268-8f9b-627519830d31.png">

However in the list view, the icon to denote its _type_ should be used:
![128332604-68c3c6b0-d3b0-46c0-8c5d-89304f8c3b7e](https://user-images.githubusercontent.com/1204802/136518844-87e52807-6b05-4055-a4d4-61e592619e78.png)

**Comment by ntsekouras** [comment]
Thanks for creating the issue Joen! I haven't looked into in depth yet, but with the current behavior the active variation's name(if exists) is shown with the help of [useblockdisplayinformation](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/#useblockdisplayinformation). I'm not really fond of having specific handling, but I guess this should be one, in the `ListView` for not using this info.

**Comment by jasmussen** [comment]
Thanks for looking. Since for the moment we will primarily need the actual icons to be shown in a future template type selector, perhaps we could invert the logic, and just use that same icon for those block types, and revisit to show dedicated icons in that selector in the future?

**Comment by jasmussen** [comment]
@jameskoster can you glean whether following recent changes, we can close this one?

**Comment by jameskoster** [comment]
Yes I think so. The current icon assignment for headers, footers, template parts, and patterns seems good to me. 

We may need to revisit general template parts and synced patterns if those concepts merge fully, but that can probably be done in a new issue.
