### ISSUE TITLE
Navigation block - include Categories in allowed blocks

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#35467]
## What problem does this address?

In the Navigation block we can already add the Page List block. This is great for theme authors to create a default menu, but it may make more sense in some designs to use post Categories as the default menu instead.
## What is your proposed solution?

Including the Categories list as a navigation option would further enhance the Navigation block.

**Comment by getdave** [comment]
As I see it this is an important piece of missing functionality. Let's make sure it's on the Tracking Issue.

**Comment by getdave** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/65012 where there is more discussion
