### ISSUE TITLE
Create a list view for templates

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#35465]
The mosaic view of templates (#33770) can work very well for navigating a smaller number of templates, or for getting a feel for how global styles affect the site appearance beyond the scope of a single document. 

But it may not be optimal when there are many templates to display, or if you want to perform bulk actions.

It might be nice to offer a list view for templates, which is where you'd go to do bulk editing, or quickly navigate a large number of templates.

I acknowledge that we have the core list screen for templates in the Appearance menu, but if we want to provide a way to fluidly toggle between mosaic / list views then we should build this in to the site editor.

**Comment by karmatosed** [comment]
> I acknowledge that we have the core list screen for templates in the Appearance menu, but if we want to provide a way to fluidly toggle between mosaic / list views then we should build this in to the site editor.

I'm unclear what this means so want to check. Are you proposing that in the same screen you'd be able to switch between mosaic or list?

**Comment by jameskoster** [comment]
Yes, rough example:

![grid-list](https://user-images.githubusercontent.com/846565/137725354-7af95ac2-93af-4611-8566-455277a04122.gif)
