### ISSUE TITLE
Add .stylelintrc.json to @wordpress/create-block

### ISSUE THREAD

**Issue by khoipro** [WordPress/gutenberg#35485]
## What problem does this address?
When creating a new block with core blocks, it's requires to modify some BEM Class which generated by core, such as:

```css
.wp-block-group__inner-container
```

However latest @wordpress/create-block still report violating "Selector should use lowercase and separate words with hyphens   selector-class-pattern".

## What is your proposed solution?
Add `.stylelintrc.json` in package [@wordpress/create-block](https://github.com/WordPress/gutenberg/blob/trunk/packages/create-block/README.md) to ignore this warning.

```json
{
	"extends": "@wordpress/stylelint-config",
	"rules": {
		"selector-class-pattern": null
	}
}
```

- Refer with Gutenberg default stylelint config: https://github.com/WordPress/gutenberg/blob/d9e7541fe29c0022f2f5de2570ec60bee670aede/.stylelintrc.json#L11
- Related Issue: https://github.com/WordPress/gutenberg/issues/28616

**Comment by khoipro** [comment]
I think the patch should be there: https://github.com/WordPress/gutenberg/blob/trunk/packages/scripts/config/.stylelintrc.json

I will put my patch tomorrow.

**Comment by gziolo** [comment]
Should we revisit #28954 instead that tried to make the rule better aligned with what Gutenberg uses? An alternative would be to disable the rule everywhere (in `@wordpress/stylelint-config`) until we have a better validator.
