### ISSUE TITLE
No "hide_empty" setting on Categories block

### ISSUE THREAD

**Issue by DeveloperWil** [WordPress/gutenberg#35489]
## What problem does this address?
When using the categories block in the block editor, by default it hides categories that have no associated posts (empty categories).
There is no block setting to override this default behaviour.
I want the option for the Categories block to show all categories in WordPress or to hide empty categories.

## What is your proposed solution?
Add a "Hide Empty" = true/false setting to the Categories block settings.

**Comment by pbearne** [comment]
I will look at this

**Comment by mauriac** [comment]
I've just warmed up @pbearne 's PR
