### ISSUE TITLE
Site editor: Cannot read properties of undefined (reading 'getAlignments')

### ISSUE THREAD

**Issue by ribaricplusplus** [WordPress/gutenberg#35498]
### Description

I get the following error (and also the query block doesn't work) when I try to open the Site Editor while doing development on tt1-blocks:

```
use-available-alignments.js:34 Uncaught TypeError: Cannot read properties of undefined (reading 'getAlignments')
    at useAvailableAlignments (index.min.js:9375)
    at index.min.js:38282
    at renderWithHooks (react-dom.development.js:15015)
    at mountIndeterminateComponent (react-dom.development.js:17841)
    at beginWork (react-dom.development.js:19079)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3942)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3991)
    at invokeGuardedCallback (react-dom.development.js:4053)
    at beginWork$1 (react-dom.development.js:23994)
    at performUnitOfWork (react-dom.development.js:22806)
```
I created an issue here because the error happens in Gutenberg files so it's probably not a thing that the tt1-theme can do anything about. Maybe it's caused by some theme.json settings or I just did something wrong?

**Important note** this doesn't happen when I create a similar setup to do development on twentytwentytwo (https://github.com/WordPress/twentytwentytwo)

### Step-by-step reproduction instructions

I tried to do development on tt1-blocks from the theme-experiments repository (https://github.com/WordPress/theme-experiments). So I first cloned that repo (commit 304e6ef).

I used `@wordpress/env` to setup a server by adding this `.wp-env.json` to `theme-experiments` repository:

```
{
    "core": "WordPress/WordPress",
    "themes": [ "./tt1-blocks" ],
    "plugins": [ "/home/bruno/useful/gutenberg" ]
}
```

`/home/bruno/useful/gutenberg` is the path to the Gutenberg repository at commit cb71bf3a4d (latest commit at the time of writing this issue). This issue also appears if I install Gutenberg normally from WP admin rather than using wp-env.

Run `wp-env start`, activate tt1-blocks, and navigate to the Site editor. The error in the description appears and the query block doesn't work.

### Screenshots, screen recording, code snippet

Screenshot of the error:

![2021-10-11_11-14](https://user-images.githubusercontent.com/43731400/136767576-abe9f060-f0b5-4231-b257-1f6b55ad491d.png)

Query block not working:

![2021-10-11_11-16](https://user-images.githubusercontent.com/43731400/136767605-351e6353-6802-4668-b106-80bc8654c518.png)

### Environment info

- Opearing system: Debian
- Latest WordPress version (checked out by `@wordpress/env`)
- Gutenberg at commit cb71bf3a4d but it happens with other versions too

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I was able to reproduce the issue. It happens if I use the latest TT1 Blocks theme from the theme experiments repo.

**Comment by ntsekouras** [comment]
👋 Thanks for reporting this! 

I couldn't reproduce the issue with the latest `tt1-blocks` and Gutenberg `trunk`. In general this sounds more like a theme specific issue (misconfiguration at block level or theme.json 🤔 ). Can you still reproduce this problem? If not I guess we can close this issue 😄

**Comment by ribaricplusplus** [comment]
Yes, makes sense that it got fixed through one of the various changes. I'll close the issue. Thanks for taking a look!

**Comment by CzarnaMamba** [comment]
I have the same issue

**Comment by udayjain85** [comment]
Yes I have too..for color pallete
![image](https://github.com/WordPress/gutenberg/assets/29598642/353801c3-0d60-4025-a83f-6603621b79ee)
