### ISSUE TITLE
Overflow jumping - Block Pattern Category Panel in large screen (1920px)

### ISSUE THREAD

**Issue by khoipro** [WordPress/gutenberg#35494]
### Description

When opening a Block panel in 1920px (fullscreen), if we create a custom child theme block pattern category and add 3 block patterns, the block pattern overflow height could be jumping.

### Step-by-step reproduction instructions

1. Register a custom block pattern category in child theme.
2. Register 3 block patterns in child theme's block pattern category.
3. Go to Page Editing screen.
4. Add new block, then choose "Add New",
5. In panel, choose tab "Patterns".
6. From dropdown category, select child theme block pattern category.

### Screenshots, screen recording, code snippet

https://1drv.ms/u/s!AtRZFns2Yb2DgY8lCyNF9MRnofDcyw?e=OQEZRl

(2 videos, with laptop 13'' - no error; and with 1920px screen - error)

### Environment info

No Gutenberg plugin install.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting. There's a few places this happens and it seems to be caused by block previews conflicting with sidebar.

The issues are being tracked at https://github.com/WordPress/gutenberg/issues/24611
