### ISSUE TITLE
When a block theme is active, cross-link from category management to site editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#35504]
In appropriate scenarios, it might be nice to offer a shortcut from category management to visual editing of said category.

Here's a mockup I put together last year that communicates the idea. It obviously needs some design updates :)

<img width="643" alt="Screenshot 2021-10-11 at 10 32 10" src="https://user-images.githubusercontent.com/846565/136780054-f4d94048-071c-4c4e-8f31-76599236690d.png">

**Comment by mtias** [comment]
Also a link to the general category template from the main categories page.

**Comment by jameskoster** [comment]
Perhaps we no longer need the wp-admin version of category editing at all (Edit: when a block theme is active. Obviously we need it for classic themes). 

<img width="953" alt="Screenshot 2022-02-07 at 11 15 17" src="https://user-images.githubusercontent.com/846565/152778075-0f95d10d-720a-483f-ab86-ff558aa8d18f.png">

Instead, clicking the category in the table above could just take you directly to the site editor, and there you can directly manipulate things like the description, assuming that the active theme includes that block in the template. 

This would remedy a current UX issue in which folks edit the description and then don't understand why it doesn't appear on the frontend.

**Comment by jameskoster** [comment]
Closing in favor of #17099
