### ISSUE TITLE
Make “Read more” links more meaningful for the screen reader users

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/gutenberg#35500]
### Description

The repetitive links such as “Read more” can be ambiguous for the screen reader users. 
Adding the page or post title after “Read more” makes the text links more meaningful. 
For example, instead of hearing “Read more” alone, the screen reader users hear “Read more about hello world”. The page or post title can be hidden from the sighted users using screen-reader-text. 

### Step-by-step reproduction instructions

1. Using TT1 theme, replace the current query loop on the index file with different query loop that has “read more” option. 
2. Add “read more” link
3. On the front page, navigate to the read more link while using the screen reader. 

### Screenshots, screen recording, code snippet

![screenshot](https://user-images.githubusercontent.com/30734209/136776304-0bf5ec6f-6acf-42f7-a6df-8a6bfb11ff8d.jpg)

### Environment info

Firefox on macOS using VoiceOver

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi
The user is asked to enter their own text for the read more link. If they do not enter their own text, the read more link is not used.
Because the text is custom, we can't add the title after the text, since the result can be unexpected.

**Comment by TeBenachi** [comment]
Aha that’s true!

I wish there is a way to make the repetitive links more descriptive for those who decide to use the read more 😞
