### ISSUE TITLE
Site Editing block placeholders

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#35501]
A couple of recent PRs have sought to tidy up placeholder states for some of the site editing blocks:

* https://github.com/WordPress/gutenberg/pull/35243
* https://github.com/WordPress/gutenberg/pull/35397

It would be good to do this holistically across all of the site editing blocks. 

To clarify, these placeholders are for situations in which the blocks have no data to reference.

Here's how they look currently:

<img width="610" alt="Screenshot 2021-10-11 at 11 13 34" src="https://user-images.githubusercontent.com/846565/136773642-0c1d6ac9-99eb-491b-aade-ad6e40aa7c88.png">

There are several inconsistencies to address here. We have different content schemas, styling, image handling and so on.

For the text-based blocks, it's probably adequate to let the theme stylesheet handle their appearance. So let's remove any styling like padding, borders, font-size etc.

In regards to their content, I'm inclined to say that echoing the block name is probably the simplest and most intuitive approach for now. So instead of "An example title" and "no date" we'd have "Post title" and "Post date". This feels like a good foundation from which we can potentially do something more elaborate in the future ("Hello Dolly" for placeholder content?).

The new dashed outline applied to the site logo works well, so perhaps we can try that for the Featured Image as well.

- [x] Update styling: https://github.com/WordPress/gutenberg/pull/35513
- [x] Update content: #35517
- [x] Featured Image: https://github.com/WordPress/gutenberg/issues/36136

**Comment by noisysocks** [comment]
Closing this out in favour of https://github.com/WordPress/gutenberg/issues/36136 which is more specific/actionable.
