### ISSUE TITLE
[Post Featured Image]: Allow cropping and/or constraining to a certain ratio

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#35524]
Similar to https://github.com/WordPress/gutenberg/issues/33789. 

Alongside the featured image resizing controls, we should include the option to crop the featured image down to a specific image ratio. This could be a freeform crop control, or it could be just a set of options (1:1, 4:3, 16:9, etc.). 

The user can of course enter absolute pixel sizes to do this sort of thing, but then the image won't scale responsively. 

---
Example of all square images: 

<img width="1075" alt="default" src="https://user-images.githubusercontent.com/1202812/136839088-a96b80f2-8c2e-4e04-842f-5c22846ea6fc.png">

**Comment by mtias** [comment]
An `aspect-ratio` control would make sense.

**Comment by scruffian** [comment]
This is now possible, though we still need to add the aspect ratio controls. Let's close this in favour of https://github.com/WordPress/gutenberg/issues/38990
