### ISSUE TITLE
Post Title Block: Custom margin applied to Headings does is not reflected in the front-end

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#35522]
If a custom margin values are manually added to the Post Title block via block markup, they're reflected in the editor, but are not present in the front-end. 

## Sample markup

```
<!-- wp:post-title {"style":{"spacing":{"margin":{"top":"0px","bottom":"0px"}}} /-->
```

Or, here's a block pattern that uses this markup:

```
<!-- wp:post-template -->
<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"verticalAlignment":"top","width":"160px"} -->
<div class="wp-block-column is-vertically-aligned-top" style="flex-basis:160px"><!-- wp:post-date {"fontSize":"small"} /--></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"75%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:75%"><!-- wp:post-title {"isLink":true,"style":{"spacing":{"margin":{"top":"0px","bottom":"0px"}},"typography":{"fontSize":"clamp(3rem, 6vw, 4rem)"}}} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator -->
<!-- /wp:post-template -->
```

## Screenshots

Editor|Front-end
---|---
<img width="748" alt="Screen Shot 2021-10-11 at 1 58 54 PM" src="https://user-images.githubusercontent.com/1202812/136834329-f955c375-00fb-4037-9b7a-2884fa96a30e.png">|<img width="429" alt="Screen Shot 2021-10-11 at 1 59 08 PM" src="https://user-images.githubusercontent.com/1202812/136834328-28e78b67-b051-4cd5-a599-c7cb918ba12a.png">

Editor|Front-end
---|---
<img width="707" alt="Screen Shot 2021-10-11 at 1 57 27 PM" src="https://user-images.githubusercontent.com/1202812/136834183-0f098a0d-9803-4edb-83c6-2b946231ecef.png">|<img width="643" alt="Screen Shot 2021-10-11 at 1 57 47 PM" src="https://user-images.githubusercontent.com/1202812/136834186-50e4b55b-04ea-4cd6-9533-434815fda836.png">

**Comment by carolinan** [comment]
I learnt that this is true not only for the post title but also paragraphs, navigation.

**Comment by colorful-tones** [comment]
I believe this would require a larger rollout of `margin` support for pertinent blocks, correct? So, we would need to determine whether the Post Title is worthy of margin support.

I'm just trying to provide a bit further context.

Related Pull Requests and Issues
1. [Spacing Support: Add margin block support with configurable sides #30608](https://github.com/WordPress/gutenberg/pull/30608)
2. [Group Block: Add support for margin control to the group block #33909](https://github.com/WordPress/gutenberg/pull/33909)

**Comment by Mamaduka** [comment]
@colorful-tones is right. The margin attributes won't be saved if the block doesn't support "spacing."

**Comment by kjellr** [comment]
@mtias do you know of a reason we don't just enable spacing globally (for block themes at least)?

**Comment by colorful-tones** [comment]
@kjellr I just dropped a request for update on parent Issue: [Consistent dimension controls across blocks. #28356](https://github.com/WordPress/gutenberg/issues/28356). Trying to keep the boulder moving. 😄 👍

**Comment by kjellr** [comment]
Thanks, @colorful-tones!

**Comment by colorful-tones** [comment]
@kjellr I've got a PR opened to try and get margin spacing support in for Post Title block: [Post Title block - add spacing.margin support #35684](https://github.com/WordPress/gutenberg/pull/35684)

**Comment by MaggieCabrera** [comment]
This is happening with padding too, when applied to the markup of the template, it only shows up with padding in the editor, not the frontend.
