### ISSUE TITLE
Add a timeout for the in-between-inserter for cases where the onmouseout isn't invoked

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#35536]
The in-between inserter shows up when you hover between two blocks, and disappears when you move the cursor out from that area:

![inserter](https://user-images.githubusercontent.com/1204802/136928503-7c302b7d-aa8e-4e6c-8f0f-a89783003f9f.gif)

However a number of actions can cause this inserter to linger and stay, presumably because mouse action to fade the inserter out again isn't fired. One easy way to reproduce this is is to use the keyboard shortcut to open the list view, control alt O, while the inserter is present:

![lingering quick inserter](https://user-images.githubusercontent.com/1204802/136928841-7ec9619c-dfe1-45a4-be08-ea2721b5b2fb.gif)

Other ways to make the inserter linger is when keyboard shortcuts are used to resize the window, or to invoke the web inspector. It also happens if the viewport resizing gets invoked:

![lingering](https://user-images.githubusercontent.com/1204802/136929296-b6185ecf-91df-4e8c-bac6-835d4eb99c99.gif)

Quite simply, if you move the mouse out from canvas itself fast enough, it will stay around. Occasionally this can cause horizontal or even double scrollbars to appears, as the canvas size is reduced while a stray sibling inserter lingers in the canvas (#30055).

To address this and fade out the sibling inserter in these cases, can we add a timeout that checks if the mouse is over the sibling inserter, and fade it out if not? Are there other solutions?

**Comment by jameskoster** [comment]
In addition to the timeout, would it make sense to hide the in-between-inserter on any keystroke, and any click not directly on the [+]?

**Comment by jasmussen** [comment]
Good thought, yes. Perhaps also on any hover that is outside the canvas.

**Comment by jasmussen** [comment]
Another way to trigger the lingering inserter:

- Hover between two blocks to invoke the sibling inserter
- ⌘Tab or Alt Tab to go to a different window, then go back

**Comment by jameskoster** [comment]
Another one that may be specific to template parts:

![inbetween](https://user-images.githubusercontent.com/846565/137306294-ea6ca342-35b0-4eed-84a2-a60bf766975f.gif)

**Comment by ramonjd** [comment]
I've been toying around with adding an `onFocusOutside` to the [InsertionPointPopover](https://github.com/WordPress/gutenberg/blob/752d7759b373a1e748cabdc7f04cefcd99ccb684/packages/block-editor/src/components/block-tools/insertion-point.js#L284), then dispatching `hideInsertionPoint`. Seems like it might be worth trying.

**Comment by jasmussen** [comment]
Definitely seems worth trying. The sibling inserter appears so easily now, that I think we can/should be pretty aggressive in dismissing it as well. Focus/click outside would be a good start, but honestly even _hover outside_ should dismiss it, and that's often not the case now.

**Comment by ramonjd** [comment]
The inserter is proving to be fickle. While it might not cover all cases described, this might be a start: https://github.com/WordPress/gutenberg/pull/36798
