### ISSUE TITLE
Query Loop block toolbar settings don't scale down well 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#35531]
### Description

If you try to use the query loop block nested in a smaller space, like a column, the settings look broken. This was found as part of the tenth call for testing for the FSE outreach program. 

### Step-by-step reproduction instructions

1. Add a columns block. 
2. Change it to 4 columns. 
3. Add in a Query Loop block to the first column and see the problem. 

### Screenshots, screen recording, code snippet

Photo:

![EIySMY (1)](https://user-images.githubusercontent.com/26996883/136873034-7051572e-de1b-4eb6-a76f-0ed55ca8afa0.png)

Video:

https://user-images.githubusercontent.com/26996883/136872863-2f73961e-e91a-426b-b36a-5bdb2f985c1e.mov

### Environment info

- WordPress 5.8.1, Gutenberg 11.6, TT1 Blocks
- Latest version of Chrome on MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
In such scenarios many blocks have similar problems like `Cover`, `Image`, etc... It seems we get back to the `Placeholders` patterns and usage.

**Comment by youknowriad** [comment]
This issue has been solved in my testing. The placeholders adapt to the width now.
