### ISSUE TITLE
Order of "supports" panels

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#35541]
Right now the order of panels is not reflective of their importance, particularly border being so prominent. Let's revise it towards:

- Layout
- Color
- Typography
- Dimensions
- Border
- Advanced

**Comment by ramonjd** [comment]
I've swapped the styles supports order for now in https://github.com/WordPress/gutenberg/pull/35574

The Dimensions Inspector Controls group is, however, rendered as the [next to last Slot, before the Advanced controls](https://github.com/WordPress/gutenberg/blob/release/11.7/packages/block-editor/src/components/block-inspector/index.js#L132), so it'll always render in that position.

_**I think**_ we need to pick up on @gziolo's idea in https://github.com/WordPress/gutenberg/pull/34069 to achieve more control over the order of Inspector Control slots.

> Now, there is a question about what we do about Global Styles UI. If that should be a single group or we should have more groups, for example:
> 
> - default
> - layout
> - typography
> - border
> - color
> - dimensions

I'll get stuck into that straight away, but also cc @aaronrobertshaw for a confidence check on this opinion first :)

**Comment by ramonjd** [comment]
> I'll get stuck into that straight away, but also cc @aaronrobertshaw for a confidence check on this opinion first :)

Answered here: https://github.com/WordPress/gutenberg/pull/35574#issuecomment-941909519

> The grouped inspector controls slots will add a bit of a wrinkle to this as you mentioned. It might be handy to know that I'm creating these new inspector control groups as part of switching the block support panels to use the ToolsPanel.
> 
> These new groups/panels were being approached one at a time, typography, color, then border. I'm not sure there is a quicker or more efficient means of adopting the new groups/approach.
> 
> Obviously, this can be landed to get us one step closer if there is a hurry to improve it. Otherwise, we could address it incrementally, ensuring the panel switch PRs match the proposed order.

Thank you!

**Comment by aaronrobertshaw** [comment]
> The Dimensions Inspector Controls group is, however, rendered as the next to last Slot, before the Advanced controls, so it'll always render in that position.

The other block support panels will be switched to use new inspector control groups when they are updated to use the `ToolsPanel`. 

At this point, I've only updated the [typography panel PR.](https://github.com/WordPress/gutenberg/pull/33744) The [color](https://github.com/WordPress/gutenberg/pull/34027) and [border](https://github.com/WordPress/gutenberg/pull/33743) panel PRs will be updated in the next couple of days. As I do this, I'll make sure the panels are as close to the proposed order as possible.

> I think we need to pick up on @gziolo's idea in #34069 to achieve more control over the order of Inspector Control slots.

I'm a little behind with regards to the Global Styles sidebar, I know it's been overhauled recently. With its new presentation is this ordering applicable or is it only for block supports?

**Comment by ramonjd** [comment]
> I'm a little behind with regards to the Global Styles sidebar, I know it's been overhauled recently. With its new presentation is this ordering applicable or is it only for block supports?

That's a good question, thanks for reminding me. I had screenshots I prepared earlier to raise this, but... you know, forgot :)

Here's what I'm seeing in the Site Editor:

<img width="283" alt="Screen Shot 2021-10-13 at 1 31 10 pm" src="https://user-images.githubusercontent.com/6458278/137069329-04949d38-95c5-43fc-ac33-867536fc74b6.png">

<img width="284" alt="Screen Shot 2021-10-13 at 1 32 02 pm" src="https://user-images.githubusercontent.com/6458278/137069344-ae27848c-de50-4dcd-ab14-3c5962fd5c31.png">

I'd assume the order would persist throughout the app?

**Comment by aaronrobertshaw** [comment]
Yeah, so from those screenshots I'd take it that we won't be re-grouping all the panels, only swapping the positions of typography and layout from the first screenshot.

**Comment by mtias** [comment]
> I'm a little behind with regards to the Global Styles sidebar, I know it's been overhauled recently. With its new presentation is this ordering applicable or is it only for block supports?

Only for block supports for now. In global styles, only the per-block categories would reflect that order. The root level will remain as the design above.

**Comment by aaronrobertshaw** [comment]
With the color panel [switching to using the `ToolsPanel`](https://github.com/WordPress/gutenberg/pull/34027) and the grouped `InspectorControls` slot, the order of the block support panels now match the order outlined in this issue. I'll close this as a result.
