### ISSUE TITLE
Gutenberg does not work with OVH firewall enabled

### ISSUE THREAD

**Issue by barbayellow** [WordPress/gutenberg#3555]
First of all, I love this plugin. It changed the way I write posts. 

I installed Gutenberg and I had the exact same problem as #2565. So I removed CloudFlare. Same problem. I finally removed the firewall of my hosting provider (OVH, a French company) and Gutenberg finally worked. I did not check the code but I guess Gutenberg needs to reach some kind of API somewhere. 

So I wonder if Gutenberg could integrate a fallback when your hosting provider enables some kind of security measures. 

Once again, great job.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by pento** [comment]
@barbayellow: We recently made a change that may help, in #4396. If you're able to download the development version, we'd appreciate it if you could test and see if it works now. Alternatively, the upcoming Gutenberg 2.1 release will include the fix.

**Comment by karmatosed** [comment]
I am closing as we've not had any feedback on this and changes were made. If you are still experiencing this just add a note and we can reopen.
