### ISSUE TITLE
[@wordpress/eslint-plugin] Support for ESlint v8

### ISSUE THREAD

**Issue by scinos** [WordPress/gutenberg#35576]
### Description

ESlint v8 [has been released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) and it includes a few breaking changes.

`@wordpress/eslint-plugin` should support it. At the very least it should:

- Declare `8` as a valid peer dependency
- Update 3rd party `eslint-plugin-*` dependencies to a version that supports ESLint v8

I haven't check if the provided rules must be updated as well to work in ESLint v8

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by marekdedic** [comment]
Hi,
I initially got an error with something related to jest, now I'm getting
```
TypeError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json » plugin:@wordpress/recommended': Class extends value undefined is not a constructor or null
Referenced from: /home/runner/work/crdm-modern/crdm-modern/node_modules/@wordpress/eslint-plugin/index.js
    at Object.<anonymous> (/home/runner/work/crdm-modern/crdm-modern/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/CLIEngine.js:12:34)
    at Module._compile (/home/runner/work/crdm-modern/crdm-modern/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/home/runner/work/crdm-modern/crdm-modern/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/runner/work/crdm-modern/crdm-modern/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js:14:14)
    at Module._compile (/home/runner/work/crdm-modern/crdm-modern/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

Hope that helps, thanks!

**Comment by gziolo** [comment]
@simonhammes is working on the upgrade in https://github.com/WordPress/gutenberg/pull/36283 🎉

**Comment by ChristianMMacy** [comment]
Hello! Thank you for bumping the ESLint version. I see that the version is updated in TRUNK, but the current version on NPM is 9.3.0 and still has a peer dependency of ^6 | ^7. What does the release schedule look like for `eslint-plugin`? I.e. when will the current version be available via NPM?

If 9.3 should have the correct versions, I'd love help figuring out what might be going on that I keep getting the wrong peer dependency. (all my other packages that use eslint are on 8.4.1).

UPDATE: I noticed that the 36283 is schedule for [Gutenberg 12.2](https://github.com/WordPress/gutenberg/milestone/166), and I'm assuming that this package will get bumped at that time.

**Comment by gziolo** [comment]
See: https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/release.md#synchronizing-wordpress-trunk

> For each Gutenberg plugin release, WordPress trunk should be synchronized. Note that the WordPress trunk branch can be closed or in "feature-freeze" mode. Usually, this happens between the first beta and the first RC of the WordPress release cycle. During this period, the Gutenberg plugin releases should not be synchronized with WordPress Core.

We are in the process of releasing the next major WordPress version (5.9) so we don't do regular npm publishing every two weeks.

I plan to run [the development release](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/release.md#development-releases) with the `next` dist-tag later this week in case someone wants to use the most recent version earlier.

**Comment by gziolo** [comment]
It's now available for testing on npm with:
```
npm install --save-dev @wordpress/eslint-plugin@next
```

The stable version should be available in the second half of January.

**Comment by WraithKenny** [comment]
This is an obnoxious way of doing things. You should have a disclaimer on all your NPM Packages that says "Not for general usage: Only for Gutenberg dev." It's a mistake that I've added any of these packages to my theme projects.
