### ISSUE TITLE
Clicking on quick inserter or block toolbar does nothing when block library sidebar is open

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#35575]
### Description

If the block library sidebar is open, clicking on a block inserter in the canvas, or clicking anywhere on a block toolbar has no effect but to close the block library sidebar and focus the clicked element.

This seems to be related to the layout reflow that occurs when the sidebar is closed, because changing the sidebar styles to absolutely position it over the editor instead of by its side fixes the issue.

### Step-by-step reproduction instructions

1. In the post editor, make sure there's some content and select a block so that its toolbar is visible.
2. Click the "Add" button in the header to open the block library.
3. Try clicking "options" on the block toolbar. Verify that the options dropdown doesn't open, but the block library sidebar closes.

### Screenshots, screen recording, code snippet

![bloclib](https://user-images.githubusercontent.com/8096000/137068187-9c4586e7-e96a-4a74-8122-ff2306ceb3be.gif)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
This does seem the same as #51678 which is mentioned above. I'll close this issue in favour of that one as it has a little more activity, and more recent screenshots/cast
