### ISSUE TITLE
Make `publishPost` e2e util more resilient

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#35580]
Recently [with a failure in e2e tests](https://github.com/WordPress/gutenberg/issues/35387) it was discovered that the e2e util `publishPost` can be augmented to make sure the publish post action has been performed.

Currently the util relies on [waiting for the snackbar to exist](https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-test-utils/src/publish-post.js#L19), but after #34731 a snackbar is shown in other cases as well - like saving a draft. This can create unexpected results with race conditions. 

Some attempts were https://github.com/WordPress/gutenberg/pull/35565/commits/2d135c49cd4c602d4db6ee79d806d7cd67606ee1 and https://github.com/WordPress/gutenberg/pull/35579 with no success.

**Comment by Mamaduka** [comment]
@ntsekouras, is this still an issue after the Playwright migration?

**Comment by ntsekouras** [comment]
Let's close this one, yes.
