### ISSUE TITLE
Set focus on prior block after deleting multiple blocks

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3558]
A classic text editing flow is the following:

1. Type a bunch of text, many paragraphs
2. Decide that some of those are crap, and select those paragraphs
3. Press delete or backspace to delete them
4. Then start typing again

Gutenberg is good as far steps 1-3 go. You can easily select multiple paragraphs, either with the keyboard or the mouse. Delete and backspace also work fine for deleting this text. But once you delete text, focus isn't set anywhere. 

We have two options for improving this:

1. Set focus on the _preceding_ block. If that preceding block is a text block then ideally at the end of this text block
2. Insert an empty text block with focus, then you can either use the slash command, start typing again, or press backspace to delete the empty block.

Thoughts?

**Comment by karmatosed** [comment]
I think 2 makes sense for the existing flows in Gutenberg and to take advantage of the slash command. I worry a little about empty text blocks and this being an issue for users, but I think the slash command functionality means this is the best option.

**Comment by jasmussen** [comment]
As an addendum, since opening this ticket, we now have a "cursor indicator" even when you are `isEditing`. That is, if you're writing and outlines have faded out, if you arrow-key upwards into an image or gallery, that item has a black outline to indicate this is where the cursor/focus is, implying you can delete or backspace or press enter to create a linebreak after this.

Incidentally if we were able to set focus on the preceding block after deleting using backspace or delete, we could _keep_ you in `isEditing` mode.

**Comment by talldan** [comment]
@jasmussen - Working on https://github.com/WordPress/gutenberg/pull/8961 and noticed this ticket. I think this is now resolved (both in master and on #8961). Happy for this to be closed?

I've noticed a couple of other separate issues related to deleting and I'll make new issues for those.

**Comment by jasmussen** [comment]
Yaay, it's fixed indeed! Closing.
