### ISSUE TITLE
Split Post Author in to separate blocks

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#35596]
Post Author currently serves as a monolithic block for displaying all information relating to the post author:

* Name
* Avatar
* Bio
* Byline (not entirely sure where this comes from, seems to be attached to the block)

<img width="726" alt="Screenshot 2021-10-13 at 15 42 42" src="https://user-images.githubusercontent.com/846565/137156259-e08dddc3-8196-4a9b-b06a-ff08495674b8.png">

It would be more flexible (in terms of layout composition) for this information to be split in to separate blocks. Similar to what we're doing with the [comment blocks](https://github.com/WordPress/gutenberg/issues/34994).

- [x] Author Name #36001
- [x] Author Avatar #38591
- [x] Author Bio #38269
- [ ] ~Author Byline?~ Not planned.

These blocks should probably be restricted to either the Query block, or Singular templates.

**Comment by carolinan** [comment]
The question remains whether this should be a _user block_, with an author variation?
There is a long discussion here https://github.com/WordPress/gutenberg/issues/24952#issuecomment-840994975

**Comment by jameskoster** [comment]
In the context of template editing, something like a Post Author block simply needs to output the author of the associated post / page. It should not have options to change the author and so on. So perhaps an all-powerful _user_ block isn't required in this case? Or at least, this would be a stripped-down variation of such a block.

It may be worth checking in with the comments loop block work (#34994) which has similar requirements.

**Comment by karmatosed** [comment]
Would the idea be to offer a pattern that 'binds' all the blocks together? I say this because whilst splitting makes sense for those that want that control, it also can be very confusing to have so many tiny block pieces everywhere. I think we might want to balance both.

**Comment by jameskoster** [comment]
More than one pattern, I hope!

**Comment by ghost** [comment]
I want so much to see these split blocks. Additional suggestions: Author role/capability block, user meta/custom field block.

**Comment by carolinan** [comment]
We need to start thinking about how we are going to tie the individual blocks together.

**Comment by carolinan** [comment]
I raised a question here about if we also need a "View all posts by..." block? Where the correct link to the author archive is already included.

https://github.com/WordPress/gutenberg/issues/24952#issuecomment-1078642344

**Comment by t-hamano** [comment]
I think this issue can be closed.

Most elements of the Post Author block have already been split into separate blocks. The only Byline element doesn't exist as a block, but since it's just a `p` element, we should be able to use a paragraph block instead.

As a next step, #53427 has been submitted suggesting that this block be deprecated.
