### ISSUE TITLE
Translation note requested

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#35608]
https://plugins.trac.wordpress.org/browser/gutenberg/trunk/build/components/index.js#L52427

The string "Home and End" ... Is that refering to a homepage and it's ending OR the actual buttons on the keyboard "Home" and "End"?

I think adding a translation note here or having the "keyboard key" label would help translators.

**Comment by amieiro** [comment]
If you [review the source code,](https://github.com/WordPress/gutenberg/blob/9df736c678b2e8ef00c355e6cc9fb8092fe25484/packages/components/src/date-time/index.js#L138) I think the developer uses the "Home" and the "End" words as "the first (home) or last (end) day of a week". I think it needs a translation note, because the string it is not obvious. Would you like to make a PR with this change?

**Comment by NekoJonez** [comment]
I'm open in trying. @amieiro 
But, just thinking out loud here... Why are the terms home and end used? 
Wouldn't first and last/final day of the week make more sense?

**Comment by amieiro** [comment]
I don't know why the developer used this text. If you see [the blame](https://github.com/WordPress/gutenberg/blame/9df736c678b2e8ef00c355e6cc9fb8092fe25484/packages/components/src/date-time/index.js#L138) (git command), you can see that the developer is @ellatrix, so she could give us more information about the context.

**Comment by talldan** [comment]
This is referring to the Home and End keys on the keyboard. The example given is that pressing Home takes you to the first day of the week and End to the last day of the week.

It's displayed here in the help for the publishing UI where a user sets a publish date for a post:
<img width="292" alt="Screenshot 2021-10-14 at 4 09 52 pm" src="https://user-images.githubusercontent.com/677833/137277525-bdca8b8b-8762-43b0-b504-86c8b2296227.png">

**Comment by amieiro** [comment]
Thank you @talldan for the information. 
@NekoJonez I suppose you are sure of the context now. Would you like to send a PR?

**Comment by NekoJonez** [comment]
Yes. I'll attempt it later today.
