### ISSUE TITLE
Border Controls: Design Refinements

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#35602]
The border controls for blocks allow themes and users to set a border width, style, color, and radius. These controls currently look like this in the editor's sidebar:

<img width="745" alt="image" src="https://user-images.githubusercontent.com/191598/137172013-fc603fd7-0b04-45e2-b7b5-fbf53f8af38c.png">

These controls take up a lot of spacing, and as such are hidden behind an accordion. Unfortunately, the accordion isn't very _smart_ and defaults to it's closed state every time you select a block. This can make it cumbersome to update one or many block borders as you have to open to accordion every time. In addition, its currently not possible to define a border for individual sides of a block; Its all sides or no sides right now.

I have a few suggestions for improvement:

We can help simplify the UI by combining the color and width controls together into a more connected control.

<img width="474" alt="image" src="https://user-images.githubusercontent.com/191598/137181552-b1a36a09-738f-4599-83f1-e30eb8bb7549.png">

The color control is reduced down to the current value, and when pressed opens a popover that allows you to change the color and style of the border. The color swatch updates to help explain when the style is set to dashed or dotted.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/191598/137174888-aee98460-1543-44ca-bb65-74793e1069cd.png">
 
<img width="863" alt="image" src="https://user-images.githubusercontent.com/191598/137181709-b18f0299-c56e-4fe7-af68-7bab81a36328.png">

--

We can replace the accordion with [the new ```ToolsPanel``` component](https://developer.wordpress.org/block-editor/reference-guides/components/tools-panel/). This helps to bring consistency to the overall editor interface, but also resolves the issue with the accordion defaulting to it's closed state.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/191598/137180487-20b98fa1-56a8-4f76-9a53-268aca0b20ca.png">

--

We can add a range slider to help improve the ways the width value can be updated. The range slider is a more obvious method for mouse users to quickly change the value, and is very common with other inputs like the border width.

<img width="928" alt="image" src="https://user-images.githubusercontent.com/191598/137184073-3b491bb0-3a98-40ee-960d-d0854371c7fc.png">

--

Finally, we can make use the "link/unlink" pattern found in other controls like Padding, Margin, and Radius to make it possible to define borders for individual sides of a block.

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/191598/137186064-59c2a762-5413-4fcc-9064-832c4d0be7ad.png">

**Comment by mehul0810** [comment]
@shaunandrews These designs are just amazing!

Also, I would like to point a rare scenario related to the representation of a border with a random maximum number like `50px` or `99px`. I know these numbers are not much used with borders. But, we should ensure that any random high number of border widths entered doesn't mess up the border representation in the admin.

What will happen to the border representation when the border width is 50px as shown in the image below?
![CleanShot 2021-10-13 at 23 57 04@2x](https://user-images.githubusercontent.com/1852711/137192154-abeb9255-06a9-4b2b-b4e3-e1492bd229a1.png)

**Suggestion:** I think that we should allow adding any number of border widths but restrict the representation after a certain value like `5px` or `10px`.

**Comment by shaunandrews** [comment]
>  I think that we should allow adding any number of border widths but restrict the representation after a certain value like 5px or 10px.

Thats one solution. I think generally though, the representation might not have to actually reflect the width at all; The color might be enough to help enforce the connection to the controls.

**Comment by jeyip** [comment]
@shaunandrews This is awesome.

I'm dropping in to say that I was looking for this exact feature when testing out site editing. I'm not sure if I'll have time to work on this in the near future, but I'm keeping this issue on my radar.

**Comment by stacimc** [comment]
This looks fantastic 🤩

We'll need to adjust the controls depending on what border properties are supported by the particular block, but I don't think that will be difficult. The bigger question for me is whether it makes sense to have _optional_ controls, which are possible in a ToolsPanel context.

With these designs I don't think you'd want or need to make any of the controls optional. The `style` control gets hidden away nicely already, and the connected controls are much more compact.

**Comment by apeatling** [comment]
Closing this one out since all the work here is done! 🥳
