### ISSUE TITLE
Consider unfading outlines when moving arrowkeys between blocks

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3560]
When a non text block has focus, you can press the delete button to delete it. This works really well with the mouse:

![delete with mouse](https://user-images.githubusercontent.com/1204802/33011626-cfce2934-cdde-11e7-812e-f66f509b9aa6.gif)

This also works with the keyboard, but not at all as well:

![delete with keys](https://user-images.githubusercontent.com/1204802/33011641-df76d73c-cdde-11e7-8f27-61b9139756df.gif)

Simply put, there is no indication that the block has focus, because the "selected block outlines" have faded out because we're using arrowkeys.

Some ideas for improvement:

- Unfade outlines for a block as soon as you arrow-key into it. If it's a text block and you continue to arrow through it, the outlines will fade out again, but if it's not a text block the outlines will stay there
- Have a different focus style for non text blocks
- "Blink" the outlines whenever they're supposed to be faded out and you arrowkey between blocks

Thoughts?

**Comment by karmatosed** [comment]
> "Blink" the outlines whenever they're supposed to be faded out and you arrowkey between blocks

I lean towards exploring this. My thoughts are it could mimic breathing maybe?

**Comment by jasmussen** [comment]
> I lean towards exploring this. My thoughts are it could mimic breathing maybe?

So long as it's minimally intrusive, that sounds great to me. The idea of "blinking" the outlines when arrowing between blocks could simply serve as a reminder of which block has focus.
