### ISSUE TITLE
Shared state between two instances of Link Control in same block

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#35618]
### Description

When there are two links in one block, opening the link control and clicking "edit" on one, without saving any changes, will cause the link control of the other one to open in edit mode too. Furthermore, making an edit in one of the link controls and not saving, will cause the edited value from the first link control to show in the second link control when opened.

### Step-by-step reproduction instructions

1. Add two separate links to a paragraph.
2. Open the link control and click "edit" on the first one.
3. Change the URL, but don't save.
4. Click the second link to open its link control.
5. Verify that not only does it open in edit mode, its value is the same as the edited value from the first link.

Variation: on step 3, don't make any change. On step 5 verify the second link control also shows the same value as the first.

Expected behaviour would be that a link control never open in edit mode, and that its value, or edits to its value, not be shared with other link controls in the vicinity.

### Screenshots, screen recording, code snippet

![repeat-edits](https://user-images.githubusercontent.com/8096000/137264769-8554a770-912d-459a-882f-2a42dffb7cc0.gif)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
Related? https://github.com/WordPress/gutenberg/pull/32320

**Comment by getdave** [comment]
In https://github.com/WordPress/gutenberg/pull/32320 I suggested forcing a remount of `<LinkControl>` when the `value?.url` changes. Feels quite drastic though.

Other options also listed there. Would appreciate more 👀 to help come to a good solution.

**Comment by getdave** [comment]
This has now been fixed in https://github.com/WordPress/gutenberg/pull/34742
