### ISSUE TITLE
Post pagination: duplicate inner wrapper

### ISSUE THREAD

**Issue by chthonic-ds** [WordPress/gutenberg#35610]
### Description

The post pagination markup looked like this prior to the 11.7 release:
```
<div class="wp-container-61676156d9e74 wp-block-query-pagination">
  <div class="post-navigation-link-previous wp-block-post-navigation-link"></div>
  <div class="post-navigation-link-next wp-block-post-navigation-link"></div>
</div>
```
Since 11.7, there's a duplicate `.wp-block-query-pagination` attached to an inner wrapper `<div>`:
```
<div class="wp-container-61676156d9e74 wp-block-query-pagination">
  <div class="wp-block-query-pagination">
    <div class="post-navigation-link-previous wp-block-post-navigation-link"></div>
    <div class="post-navigation-link-next wp-block-post-navigation-link"></div>
  </div>
</div>
```

This means the flex styles managed by the `.wp-container-*` class are no longer applied to the intended target, `.wp-block-post-navigation-link`.

### Step-by-step reproduction instructions

1. Activate a theme with post pagination blocks (e.g. Tove).
2. Create a few posts to generate post pagination links.
3. With 11.6 active: visit a post and view the post pagination markup.
4. Repeat 3. with 11.7 active.

### Screenshots, screen recording, code snippet

11.6 active
![image](https://user-images.githubusercontent.com/29587253/137224869-aaecd7f7-e0c0-4781-8acf-3960f43b8882.png)

11.7 active
![image](https://user-images.githubusercontent.com/29587253/137224906-1d7eb3c0-63e3-4c75-9f4c-df3dfd98c99a.png)

### Environment info

- WordPress 5.8
- Gutenberg 11.7
- Any theme with post pagination blocks active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by chthonic-ds** [comment]
Looking at a `single.html` template:

Prior to 11.7, it seems `<div class="wp-block-query-pagination">` was required to wrap the previous/next pagination blocks? Like so:
```
<!-- wp:query-pagination {"layout":{"type":"flex","justifyContent":"space-between"}} -->
<div class="wp-block-query-pagination">
  <!-- wp:post-navigation-link {"type":"previous","label":"Previous","showTitle":true} /-->
  <!-- wp:post-navigation-link {"type":"next","label":"Next","showTitle":true} /-->
</div>
<!-- /wp:query-pagination -->
```
Since 11.7, it appears this is automatically handled by `<-- wp:query-pagination -->`. When the wrapper `<div>` is removed from the  template, the flex layout works correctly.

I guess this is not a bug and instead requires a theme update?

**Comment by chthonic-ds** [comment]
The two circumstances I'm seeing this happen with 11.7 active:

- When the markup in https://github.com/WordPress/gutenberg/issues/35610#issuecomment-942799171 has been used in a template
- When the template has been saved via the Site Editor, prior to updating to 11.7

The duplicate wrapper no longer appears once a template is saved via the Site Editor in 11.7.

**Comment by carolinan** [comment]
Yes I noticed this too and needed to update the markup in the themes .html file.
I assume this change will be announced in the post for the plugin release.

**Comment by Mamaduka** [comment]
Sorry, this is my fault. The change was introduced via #35092 to fix the empty container issue.

**Comment by Mamaduka** [comment]
The note has been added to the [release post](https://make.wordpress.org/core/2021/10/14/whats-new-in-gutenberg-11-7-october-13th/).

**Comment by chthonic-ds** [comment]
Thank you, @Mamaduka!
