### ISSUE TITLE
Quote block's deletion doesn't persist

### ISSUE THREAD

**Issue by hypest** [WordPress/gutenberg#35624]
### Description

Trying to delete a Quote block by backspacing, removes the block from the editor but the block is still there in "Code editor" mode. I'd expect the block to not be there after backspacing it.

Originally [spotted on the mobile app](https://github.com/wordpress-mobile/gutenberg-mobile/issues/4120) but we then noticed that it happens on the web clients too.

### Step-by-step reproduction instructions

1. Run Gutenberg off a merged PR like this one: http://m62bf9dp.gutenberg.run/wp-admin/post-new.php
2. Add a quote block. (it's fine to leave it empty)
3. Add a paragraph block after the Quote block and type in a couple of characters
4. Focus the Quote block input
5. Hit backspace to delete the Quote block
6. Switch to "Code editor" mode from the 3-dot menu on the top-right
7. Notice the Quote block's markup still being there 💥

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1032913/137284780-220349ed-5d1d-43a3-8d55-77348a26a9f5.mov

### Environment info

- Gutenberg off trunk b6f0bdf46dee9f29110f3c520b5c4dd892d5f1d1
- Browser: Firefox 93.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by fluiddot** [comment]
I think this might be related to the changes introduced in https://github.com/WordPress/gutenberg/pull/34241, I tried to reproduce this issue using the previous commit ([`d8808e8`](https://github.com/WordPress/gutenberg/commit/d8808e866ff760766c9eacbeb347c769fd7659ae)) of the PR merge commit ([`39806aa`](https://github.com/WordPress/gutenberg/commit/39806aa26f55b8b1ea246fcf56ba8afe7541bf64)) in `trunk`, and the issue didn't happen.

cc @youknowriad
