### ISSUE TITLE
Border Radius serialized with unit set to `undefined`

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#35628]
### Description

When setting the border radius via the slider control for any block that supports it, but not changing the default unit (`px`), the latter is serialized in the corresponding block attribute as `undefined`.

Potentially relevant PRs: https://github.com/WordPress/gutenberg/pull/33017 https://github.com/WordPress/gutenberg/pull/33117 cc/ @aaronrobertshaw @ntsekouras @oandregal 

Also cc/ing @andrewserong @ciampo (b/c #35281) -- Is there anything we can do to catch an issue like this at compile time level (e.g. by typing potential values of the unit in `UnitControl`?)

### Step-by-step reproduction instructions

1. Insert a block that has support for setting the border radius (Button, Group, Image, Pullquote, Search).
2. Use the sidebar control for setting the border radius, and set to an arbitrary value. Don't change the unit but leave it at its default `px`.
3. Switch to the code editor to inspect.

### Screenshots, screen recording, code snippet

![border-radius](https://user-images.githubusercontent.com/96308/137297215-95c220b0-541e-44ad-aa1e-d94d2a504dec.gif)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Interesting issue, thanks for the ping @ockham! I can only recreate this if I click a single time on the `RangeControl` for the border radius, without sliding left or right at all. If I enter a value directly in the `UnitControl`, or if I slide to adjust the range control at all, then the `px` unit is used and updated correctly in the code editor view.

I'll do a bit more digging, but I suspect there'll be some logic we might need to update in https://github.com/wordpress/gutenberg/blob/trunk/packages/block-editor/src/components/border-radius-control

EDIT: I think [this line](https://github.com/wordpress/gutenberg/blob/17be316ec0de21baaf7f40c256d2d45bfe94c118/packages/block-editor/src/components/border-radius-control/index.js#L65) is the culprit.

**Comment by andrewserong** [comment]
I've opened a fix in https://github.com/WordPress/gutenberg/pull/35651

**Comment by ciampo** [comment]
>  typing potential values of the unit in `UnitControl`

Hey @ockham, if I understand correctly what you meant, @andrewserong and I discussed it in https://github.com/WordPress/gutenberg/pull/35138#discussion_r716533125 and decided to leave it as a loose `string` type

**Comment by ockham** [comment]
> > typing potential values of the unit in `UnitControl`
> 
> Hey @ockham, if I understand correctly what you meant, @andrewserong and I discussed it in [#35138 (comment)](https://github.com/WordPress/gutenberg/pull/35138#discussion_r716533125) and decided to leave it as a loose `string` type

Thanks @ciampo! Yeah, that's what I meant 😄  That comment makes sense. However, I wonder how an `undefined` value could slip through if the type is set to `string`? 🤔  Maybe it's accidentally converted to an `'undefined'` string somewhere? 🤔

**Comment by ciampo** [comment]
Judging by the fix in #35651, could it be that the file where the bug originated from was not type-checked?

**Comment by ockham** [comment]
> Judging by the fix in #35651, could it be that the file where the bug originated from was not type-checked?

Ah, quite possibly! 😅
