### ISSUE TITLE
Get a warning when I set `define( 'SCRIPT_DEBUG', true );`.

### ISSUE THREAD

**Issue by chiilog** [WordPress/gutenberg#35627]
### Description

When I set `define( 'SCRIPT_DEBUG', true );` in wp-config.php, if I insert a block with a slash, I get a warning in the console. Note that the block will be displayed correctly.

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

If I insert a block from `Toggle block inserter`, the warning will not be displayed.

### Step-by-step reproduction instructions

1. Set `define( 'SCRIPT_DEBUG', true );` in wp-config.php
2. Open the developer tools in your browser.
3. Go to `/wp-admin/`
4. Go to the `Add New` page.
5. Click on editor content.
6. Type `/heading`.
7. Finally. You can see the following error in the developer tools.

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ForwardRef(RichTextWrapper) (created by ParagraphBlock)
    in ParagraphBlock (created by edit_Edit)
    in edit_Edit (created by WithToolbarControls(edit_Edit))
...
``` 

### Screenshots, screen recording, code snippet

<img width="1163" alt="20211014190053" src="https://user-images.githubusercontent.com/25993565/137296250-167efd64-0371-4cd1-a0f6-bbce696bbf1b.png">

### Environment info

- WordPress 5.8.1
  - I have not installed the Gutenberg plugin.
- macOS Big Sur 11.6
- Google Chrome 94.0.4606.81

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
It might be one of the warnings that is going to be no longer reported starting from React 18
because it often is a false positive. See more in https://github.com/facebook/react/pull/22114.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. I'm unable to reproduce this in a newer version of WordPress. Please reopen if you are still experiencing.
