### ISSUE TITLE
Cant add new colors in site editor

### ISSUE THREAD

**Issue by franmastromarino** [WordPress/gutenberg#35635]
### Description

Hello

There is a new issue in gutenberg 11.7.0

Is not possible to add new colors to the color palette

https://www.loom.com/share/c2f6d4ffe96f43c99a485b38508dafdf

https://snipboard.io/H6AsXc.jpg

### Step-by-step reproduction instructions

Go to Site Editor -> Sidebar -> Color -> Add new color

### Environment info

WordPress version: 5.8.2
Gutenberg version: 11.6.0
Are all plugins except Gutenberg deactivated? Yes
Are you using a default theme (e.g. Twenty Twenty-One)? No

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
I'm able to reproduce this as well on 11.7 although my console error message is different than yours. https://gist.github.com/skorasaurus/89a054c49ce75baaca26bb4b2790d345

I'm using the quadrat theme.

**Comment by Sandstromer** [comment]
Same issue for me too https://github.com/WordPress/gutenberg/issues/35640

When editing a color from the color palette, the Site Editor crashes when clicking anywhere in the color picker or the slider below the picker.

When adding a new color, the color picker works fine, but clicking "Save" button causes the Site Editor to crash.

**Comment by Pulmunen** [comment]
I'm coming across the same/similar issue to Sandstromer, here's my information:
Go to Site Editor -> Styles [navigator screen] -> Colors -> Palette and try to add a colour or edit a colour from the palette, the site editor crashes (styles panel closes, main content area goes blank).

Workaround: change/add colours in the relevant (child) theme's json.

https://www.loom.com/share/2caf3049157046209f568af97a8021e9
PHP 7.4.1
WP 5.8.1 (fresh install)
Gutenberg plugin 11.7.0
Both Chrome and Firefox
Themes (on both Chrome and Firefox): TT1 Blocks, Tove, FSE Tutorial
Active plugins: none (other than Gutenberg)
https://gist.github.com/Pulmunen/7a281ed85f59d1fce1f9d3f10d6eb8e0

**Comment by Mamaduka** [comment]
I think the issue got resolved via #35670. I'm no longer able to reproduce it on the current Gutenberg trunk.
