### ISSUE TITLE
New color picker: Overview of the bugs

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#35640]
### Description

- When slowly dragging the color picker the is some unexpected movement on the color picking circle.
- During the first interaction if we click right away on the color picker if it is inside a popover the popover closes unexpectedly.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Sandstromer** [comment]
Not sure if same issue, but when I try to use the color picker in the Site Editor to edit a color ~~or add a new color~~, clicking anywhere in the color picker or slider control, the whole Site Editor crashes with a resulting WSOD.

Edit: when editing a color from the color palette, the Site Editor crashes when clicking in the color picker.
When adding a new color, the color picker works fine, but clicking "Save" button causes the Site Editor to crash.

Gutenberg 11.7.0
Windows 10
Browser: Chrome and Firefox both same issue.

**Comment by ciampo** [comment]
@jorgefilipecosta do you mind if we close this issue in favour of #35677 and #35675 ? This way, progress on these issues can be tracked separately.

Overall progress on the `ColorPicker` can be followed in the tracking issue #34284

**Comment by jorgefilipecosta** [comment]
Yes I'm closing this since we already have separate issues. We have a fix for both available at https://github.com/WordPress/gutenberg/pull/35670.
