### ISSUE TITLE
Inconsistent inserter and inspector behaviour on large viewport

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#35643]
### Description

The behaviour of the block inserter and inspector is a little inconsistent when on a large viewport, and depends on the order in which you open them:

- Open block inserter and then open block inspector, and block inserter disappears
- Open block inspector and then open block inserter and both are visible

That is, what sidebars are open depends on the order in which they are opened.

This seems accidental rather than intentional.

The sidebars should behave in a more consistent way where either:

- Only one can be visible and opening one *always* closes the other
- Both can be visible regardless of which was opened first

A viewport that is smaller than large behaves in a consistent way.

Related discussion #23968

### Environment info

Gutenberg 11.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
This is solved now.
