### ISSUE TITLE
Combining text options into one toolbar

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#3564]
Lets look at the various toolbars we have today in regards to all matters text.

Paragraph:
![screen shot 2017-11-20 at 12 02 45](https://user-images.githubusercontent.com/5323259/33015411-f23b6890-cdea-11e7-81d5-a89b68373ec7.png)

Heading:
![heading-toolbar-gutenberg](https://user-images.githubusercontent.com/5323259/33015435-0602c562-cdeb-11e7-8bb7-6131328f4358.png)

Preformatted:
![preformatted-toolbar-gutenberg](https://user-images.githubusercontent.com/5323259/33015467-289ae79e-cdeb-11e7-9aa7-bee2ab3a2112.png)

Quote:
![quote-toolbar-gutenberg](https://user-images.githubusercontent.com/5323259/33015540-6fef8168-cdeb-11e7-9b14-14236a692064.png)

List:
![list-toolbar-gutenberg](https://user-images.githubusercontent.com/5323259/33015459-1b409a94-cdeb-11e7-8bed-b6fed34d4c17.png)

Verse:
![verse-toolbar-gutenberg](https://user-images.githubusercontent.com/5323259/33015567-84410c72-cdeb-11e7-8043-b6663783aaf2.png)

Having to switch between text toolbars like the above creates a higher complexity in creating a natural writing flow.

Having the Paragraph drop down similar to how TinyMCE does it with a drop down to select option h2, h3, h4 or preformated would then remove two extra toolbars. Heading and preformated easier and direct available. Cutting down on complexity in having to select another toolbar.  The verse toolbar really should not be needed as it should be easy enough in the natural writing to just write.

Quote and list could just be two drop down options in the default text toolbar.

Here is one idea of keeping it to 1 text toolbar. Making it easier on the user and of having text flowing.

![one-text-toolbar-gutenberg](https://user-images.githubusercontent.com/5323259/33015825-74f1a0dc-cdec-11e7-96cb-39bd88f70e3f.jpg)

@karmatosed

**Comment by karmatosed** [comment]
Right now, we have to do testing and I have to admit, I do not think combining is a good idea. We need to focus on what is important to users. The feedback we are getting right now is that the toolbar at the top is too missable. Adding iterations like this do not solve that. Let's close this and do more testing and loop back on iterations.
