### ISSUE TITLE
The navigation block links does not work in the front...

### ISSUE THREAD

**Issue by shadigaafar** [WordPress/gutenberg#35653]
### Description

The navigation block links does not work in the front..., and this due to `pointer-events` set to `none` instead of `unset`.

### Step-by-step reproduction instructions

1. Add a the navigation black to site editor 
2. Save and go to the front
3. Try click the nav links

### Environment info

gutenberg version: 11.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
> pointer-events set to none instead of unset

@shadigaafar I can't see anywhere that pointer-events would be set to none in the front end, and I haven't been able to reproduce this issue.

The only thing I do see is that links are set to `none` in some cases in the editor's CSS, so it might be a problem where your theme is loading editor styles on the front-end.

Is there any further info you can provide to help debug this? Thanks.

**Comment by shadigaafar** [comment]
@talldan Hi, nothing wrong with menu (except of the "open submenus on click"), you are right, not from the theme though, cos I was testing it on an empty theme. it turns out it was from one of the blocks I was developing which has `wp-edite-blocks` as a dependency and enqueued in the front....
