### ISSUE TITLE
Navigation Block: Second-Level Submenus Do Not Work on Click

### ISSUE THREAD

**Issue by donalirl** [WordPress/gutenberg#35654]
### Description

Second-level submenu items are not working in the Navigation block when "Open submenus on click" is toggled on.

### Step-by-step reproduction instructions

1. Insert a Navigation block with a submenu item and a submenu-item of that submenu item
2. In the block's display settings, ensure "open submenu on click" is toggled on
3. View the menu on the site and notice the second-level submenus do not appear

### Screenshots, screen recording, code snippet

Submenus working normally on hover:
![hover](https://user-images.githubusercontent.com/30727666/137420204-7a10c3ce-60c7-42f5-b0c9-717246775c28.gif)

Not working on click:
![click](https://user-images.githubusercontent.com/30727666/137420281-96f6e68f-a85c-425b-b821-49c50d75ce21.gif)

### Environment info

Gutenberg: v11.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
maybe related to https://github.com/WordPress/gutenberg/issues/35653 ?

**Comment by talldan** [comment]
I was able to reproduce this. Not sure it's related to #35653. The click event does seem to be triggering correctly and I see the `aria-expanded` attribute toggling correctly. Could be a CSS issue, but having a hard time figuring out exactly what it is. (cc @jasmussen @tellthemachines)
