### ISSUE TITLE
Consider to rename "Text mode" 

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3566]
See also https://core.trac.wordpress.org/ticket/38061

When switching to "Text mode", what users see in the editor is not exactly just text 🙂 Actually, it's a mix of text and code. Lots of code. I'd propose to consider to rename it to "Code", not sure which the best option between "Code mode" or "Code editor" would be. Any thoughts more than welcome.

More details on the trac ticket https://core.trac.wordpress.org/ticket/38061. For some background, see also https://core.trac.wordpress.org/ticket/20993

**Comment by youknowriad** [comment]
#3456 changes the design and the wording. Might fix this
