### ISSUE TITLE
Featured Image block: enable option to upload an image within the placeholder

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#35689]
## What problem does this address?

Currently, if you don't have a featured image set for a post, you are shown an empty, non actionable placeholder for the featured image. This makes for either a confusing or lackluster experience where one has to leave the editing experience to find and edit that specific post to add a featured image.

>  For now after this testing, I believe it would have been great if there was some simpler way to upload featured image for posts in query loop.

Current view:

<img width="759" alt="Screen Shot 2021-10-15 at 3 33 04 PM" src="https://user-images.githubusercontent.com/26996883/137543750-de45e631-17bd-4237-8894-af9a96c2ed27.png">

This came up as part of the [tenth call for testing for the FSE Outreach program](https://make.wordpress.org/test/2021/09/29/fse-program-testing-call-10-pattern-party/#comment-2128).

## What is your proposed solution?

While I know there are discussions around allowing for a fallback image https://github.com/WordPress/gutenberg/issues/34865 and rethinking featured images in this context https://github.com/WordPress/gutenberg/issues/27617, I believe that similar to the Site Logo block it might be smart to have a way to directly upload an image from the featured image block placeholder.

**Comment by jasmussen** [comment]
CC: @jameskoster as we just conversed on a separate PR about these placeholders. I also recall you mentioning that items in these loops should perhaps be inert, which might suggest the placeholder disappearing entirely in the shown example?

**Comment by ntsekouras** [comment]
Actually there is a way of uploading a featured image in the Placeholder. The above view is actually due to the not `editable` post blocks inside `Query Loop`. So maybe this issue is more related to the `editable/non-editable` post blocks?

**Comment by jameskoster** [comment]
The Featured Image needs to entertain three scenarios:

1. Data source present, no featured image set.
2. Data source present, featured image set.
3. No data source present.

In scenario one we need to render a placeholder which illustrates where the featured image would appear if set, and serve as a method to set it. In scenario two it must be possible to replace, or unset the current featured image, which effectively toggles it to scenario one.

For these two situations we can reuse the recently-implemented updates to the Site Logo block.

In the third scenario it should **not** be possible to set the featured image, but a placeholder should still appear.

**Comment by annezazu** [comment]
In light of the efforts here https://github.com/WordPress/gutenberg/issues/36136, wanted to follow up to see if this can officially be closed out! I'm asking because I noticed I can indeed upload an image within the Query Loop block and I'm not quite sure if that should be possible based on the convo above. Here's the current experience either way -- great work, folks, on improving the experience so dramatically:

https://user-images.githubusercontent.com/26996883/146978684-334d6318-0430-4490-8447-b69a3f657f3c.mov


cc @ntsekouras in particular around the editing abilities intended for 5.9 (this is using 5.9-beta3-52394).
