### ISSUE TITLE
Cannot edit post created from other editor

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#3568]
I published [a post](http://nosolosoftware.com/roma-fade-npr/) from the mobile WordPress app that contained a video and a paragraph.

When I try to edit it from Gutenberg, the editor shows nothing:
![editor-view](https://user-images.githubusercontent.com/583546/33017764-dcb1d0dc-cdf3-11e7-9240-fc5600b8d246.png)

The console displays an error:
![console-view](https://user-images.githubusercontent.com/583546/33017769-e1c99898-cdf3-11e7-8dbf-bf6fc5145eba.png)

It works in the classic editor and this is the HTML code I see in the text tab:

```
https://youtu.be/QGAzPtwUJJU

This puts me in the perfect mood before going for a walk in this sunny and cold Saturday.
```

**Comment by nosolosw** [comment]
I could repro this when opening some old draft (> several months old, some probably pre-Gutenberg) created with the classic editor. This is what happens:

![load-old-drafts](https://user-images.githubusercontent.com/583546/33598553-86b8fc08-d9a3-11e7-91d9-59ab69c8a447.gif)

Zoom in the error:

![load-old-drafts-error](https://user-images.githubusercontent.com/583546/33598660-dc848a3a-d9a3-11e7-8210-d52d1e087036.png)

The post would open blank, although it does have well-formed content ([attached](https://github.com/WordPress/gutenberg/files/1530394/post.html.txt) in case it helps). Sometimes, when I click the "Code editor" and then switch back to "Visual editor" the content would be shown. Other times, I get a "this block cannot be previewed" message.

This is in WordPress 4.9.1 and Gutenberg 1.8.1.

**Comment by aduth** [comment]
Appears this is likely due to the embed, and an issue with core embed handling where logic flows assume the presence of an editor instance indicates an iframe. Since we use the TinyMCE inline mode in Gutenberg, the iframe is not assigned:

https://github.com/WordPress/wordpress-develop/blob/1c2b0762c7f1a91394c633ae812505919bd297ed/src/wp-includes/js/mce-view.js#L864-L867

Possible options at first glance:

- Improve condition to also check truthiness of `iframeElement`
- Ensure that `self.editor` is not assigned in Gutenberg for `mce-view.js`

**Comment by aduth** [comment]
Related Core ticket: https://core.trac.wordpress.org/ticket/42416

**Comment by westonruter** [comment]
I've committed the [fix](https://core.trac.wordpress.org/changeset/42390) in WordPress core to close https://core.trac.wordpress.org/ticket/42416. So you can update to the next nightly for trunk or the 4.9 branch to resolve the issue. The fix will be included in 4.9.2 next month.

**Comment by nosolosw** [comment]
Thank you, Andrew and Weston.

**Comment by aduth** [comment]
Considering this fixed by https://core.trac.wordpress.org/changeset/42391

**Comment by nosolosw** [comment]
@westonruter @aduth just tested this after updating to WP4.9.2 and Gutenberg 2.0.0. It works :tada: 

I wanted to bring to your attention that I'm shown this message:

![screenshot from 2018-01-17 18-36-40](https://user-images.githubusercontent.com/583546/35057534-8c19482c-fbb5-11e7-9d22-9326ccd28c53.png)

Do you know something about this? Does it merit open a new issue?

**Comment by aduth** [comment]
@nosolosw I've not seen this error before, and there's not enough information in the error itself to debug; based on the presence of "youtube" keyword in the message, could it be an error from an iframe of a YouTube embed?

**Comment by nosolosw** [comment]
OK, this is unrelated to Gutenberg. I can repro with Gutenberg disabled: it happens when I embed an object served through HTTPS. I'll need to investigate more about what that header means, but it's probably because my blog uses HTTP, not HTTPS. Thanks for your time!
