### ISSUE TITLE
[Integration tests] Unexpected React state updates when rendering `LinkSettingsNavigation` component

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#35685]
## Description

Related to [this comment](https://github.com/WordPress/gutenberg/pull/35476#discussion_r728250436), we identified that the React Native testing library is giving the following warning when rendering the `LinkSettingsNavigation` component:
```
    Warning: An update to ForwardRef(NavigationContainer) inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at NavigationContainer (/Users/fluiddot/workspace/gutenberg-mobile/gutenberg/node_modules/@react-navigation/native/lib/commonjs/NavigationContainer.tsx:40:5)
        at View
        at View (/Users/fluiddot/workspace/gutenberg-mobile/gutenberg/node_modules/react-native/jest/mockComponent.js:28:18)
        at BottomSheetNavigationContainer (/Users/fluiddot/workspace/gutenberg-mobile/gutenberg/packages/components/src/mobile/bottom-sheet/bottom-sheet-navigation/navigation-container.native.js:64:2)
        at View
        at View (/Users/fluiddot/workspace/gutenberg-mobile/gutenberg/node_modules/react-native/jest/mockComponent.js:28:18)
        at View
        at View (/Users/fluiddot/workspace/gutenberg-mobile/gutenberg/node_modules/react-native/jest/mockComponent.js:28:18)
        at KeyboardAvoidingView (/Users/fluiddot/workspace/gutenberg-mobile/gutenberg/packages/components/src/mobile/bottom-sheet/keyboard-avoiding-view.native.js:26:16)
        at Unknown
        at Unknown (/Users/fluiddot/workspace/gutenberg-mobile/gutenberg/node_modules/react-native/jest/mockComponent.js:28:18)
        at BottomSheet (/Users/fluiddot/workspace/gutenberg-mobile/gutenberg/packages/components/src/mobile/bottom-sheet/index.native.js:51:16)
        at WithPreferredColorScheme(BottomSheet) (/Users/fluiddot/workspace/gutenberg-mobile/gutenberg/packages/compose/src/higher-order/with-preferred-color-scheme/index.native.js:14:23)
        at LinkSettingsNavigation (/Users/fluiddot/workspace/gutenberg-mobile/gutenberg/packages/components/src/mobile/link-settings/link-settings-navigation.native.js:18:15)
```

## Step-by-step reproduction instructions

1. Apply the following patch diff:
```diff
diff --git a/packages/components/src/mobile/link-settings/test/index.native.js b/packages/components/src/mobile/link-settings/test/index.native.js
new file mode 100644
index 0000000000000000000000000000000000000000..d5973ec3990f5de25ad88c6e84ce4aac0c7219a5
--- /dev/null
+++ b/packages/components/src/mobile/link-settings/test/index.native.js
@@ -0,0 +1,30 @@
+/**
+ * External dependencies
+ */
+import { render } from 'test/helpers';
+
+/**
+ * WordPress dependencies
+ */
+import { LinkSettingsNavigation } from '@wordpress/components';
+
+it( 'test LinkSettingsNavigation', () => {
+	const options = {
+		url: {
+			label: 'Button Link URL',
+			placeholder: 'Add URL',
+			autoFocus: true,
+			autoFill: true,
+		},
+	};
+	render(
+		<LinkSettingsNavigation
+			isVisible
+			onClose={ jest.fn() }
+			onDismiss={ jest.fn() }
+			setAttributes={ jest.fn() }
+			options={ options }
+			withBottomSheet
+		/>
+	);
+} );
```
2. Run the command `npm run native test -- link-settings/test`.
3. Observe the mentioned warning as an error log in the console.

## Expected behaviour

Rendering the `LinkSettingsNavigation` with the React Native testing library shouldn't give warnings/errors.

## Actual behaviour

Rendering the `LinkSettingsNavigation` with the React Native testing library is giving a warning.

## Screenshots or screen recording (optional)

N/A

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: N/A
- Operating system: N/A
- WordPress app version: N/A

**Comment by fluiddot** [comment]
After further investigation of this issue in the integration tests of the embed block ([reference](https://github.com/WordPress/gutenberg/pull/35476#pullrequestreview-778833337)), I found out that the issue is not really caused by React Navigation itself. I noticed that indeed the `NavigationContainer` is updating the state after the `initializeEditor` function is called, however, this is expected and could be covered in the integration test by calling functions that use `act` underneath to let the React Native testing library that the updates are expected.

The problem is related to how the React Native testing library identifies the React state updates and the fact that the function `initializeEditor` is asynchronous. The library uses the React package `react-reconciler` to control the rendering but I haven't dug deeper into the code to find the part that is causing the issue. As far as I tested, looks like it's not recommended to use the React Native testing library in an async function as it could lead to `act` warnings, like the one described in the issue.

The solution I introduced for this in https://github.com/WordPress/gutenberg/pull/35476 ([commit reference](https://github.com/WordPress/gutenberg/pull/35476/commits/ef6afb2e78bfde2ff2406c15da4df3e6f45667a3#diff-d5f0be6da4449d0e7e208bc29d6ee352d7923f69d26c9c0965a478de0238bb3e)) is to convert the async `initializeEditor` to a regular function and return a promise that executes the code related to `BlockList` component.

**Comment by fluiddot** [comment]
Regarding the issue related to rendering the `LinkSettingsNavigation` and `act` warnings, I think it's not really an issue as `NavigationContainer` component will cause a React state update, therefore the test should take it into account.

As an example, based on the [React Navigation example](https://callstack.github.io/react-native-testing-library/docs/react-navigation#example-tests) documented in the React Native testing library, here is how the test should look:
```diff
diff --git a/packages/components/src/mobile/link-settings/test/index.native.js b/packages/components/src/mobile/link-settings/test/index.native.js
new file mode 100644
index 0000000000000000000000000000000000000000..76bb662143a95afeaf6bf1a742b63b0a57eaab8b
--- /dev/null
+++ b/packages/components/src/mobile/link-settings/test/index.native.js
@@ -0,0 +1,32 @@
+/**
+ * External dependencies
+ */
+import { render } from 'test/helpers';
+
+/**
+ * WordPress dependencies
+ */
+import { LinkSettingsNavigation } from '@wordpress/components';
+
+it( 'test LinkSettingsNavigation', async () => {
+	const options = {
+		url: {
+			label: 'Button Link URL',
+			placeholder: 'Add URL',
+			autoFocus: true,
+			autoFill: true,
+		},
+	};
+	const { findByText } = render(
+		<LinkSettingsNavigation
+			isVisible
+			onClose={ jest.fn() }
+			onDismiss={ jest.fn() }
+			setAttributes={ jest.fn() }
+			options={ options }
+			withBottomSheet
+		/>
+	);
+	const label = await findByText( 'Button Link URL' );
+	expect( label ).toBeTruthy();
+} );
```

**NOTE:** By querying the link label, we're covering the React state updates caused by the `NavigationContainer` component.

**Comment by fluiddot** [comment]
Originally, I thought that all state updates would be observed when calling the `render` function, however, looks like this is not the case. Most likely this is related to the fact that there's a state update that happens asynchronously, here are some code references of the `NavigationContainer` related to this:

- `useLinking` hook returns a function named `getInitialState` ([reference](https://github.com/react-navigation/react-navigation/blob/513482425ac551a86358fa28fa18e41f16fb4d94/packages/native/src/NavigationContainer.tsx#L56-L60)) which is a promise ([reference](https://github.com/react-navigation/react-navigation/blob/513482425ac551a86358fa28fa18e41f16fb4d94/packages/native/src/useLinking.tsx#L319)).
- `getInitialState` is used when calling the `useThenable` hook ([reference](https://github.com/react-navigation/react-navigation/blob/513482425ac551a86358fa28fa18e41f16fb4d94/packages/native/src/NavigationContainer.tsx#L62)) to calculate the initial state, which can happen inside a `useEffect` hook that at the same time updates the state ([reference](https://github.com/react-navigation/react-navigation/blob/513482425ac551a86358fa28fa18e41f16fb4d94/packages/native/src/useThenable.tsx#L20-L42)).

**Comment by dcalhoun** [comment]
> Regarding the issue related to rendering the `LinkSettingsNavigation` and `act` warnings, I think it's not really an issue as `NavigationContainer` component will cause a React state update, therefore the test should take it into account.
> 
> As an example, based on the [React Navigation example](https://callstack.github.io/react-native-testing-library/docs/react-navigation#example-tests) documented in the React Native testing library, here is how the test should look:

> **NOTE:** By querying the link label, we're covering the React state updates caused by the `NavigationContainer` component.

@fluiddot great finds! I took a look at the history of the RNTL's React Navigation docs and it indeed looks like async queries were explicitly added in https://github.com/callstack/react-native-testing-library/pull/364 to address the `ForwardRef(NavigationContainer)` errors. 

My interpretation is that the initial query for _any_ screen that is accessed via navigation with React Navigation must rely upon an async query, as React Navigation will _always_ perform _some_ async state update during its navigation event render. So, I suppose we must either `await` the navigation trigger...

```js
await act( () => fireEvent.press( getByText() ) ); // query can be a non-async getBy*
```

...or, possibly better and aligns with documentation, await an async query _after_ triggering navigation...

```js
fireEvent.press( getByText() ); // query can be a non-async getBy*
await findByText(); // query must be an async findBy* or waitFor( () => getBy*() )
```

Is that how you perceive this? Do you consider this issue understood/resolved or is there more to research?

**Comment by fluiddot** [comment]
> My interpretation is that the initial query for _any_ screen that is accessed via navigation with React Navigation must rely upon an async query, as React Navigation will _always_ perform _some_ async state update during its navigation event render. So, I suppose we must either `await` the navigation trigger...
> 
> ```js
> await act( () => fireEvent.press( getByText() ) ); // query can be a non-async getBy*
> ```
> 
> ...or, possibly better and aligns with documentation, await an async query _after_ triggering navigation...
> 
> ```js
> fireEvent.press( getByText() ); // query can be a non-async getBy*
> await findByText(); // query must be an async findBy* or waitFor( () => getBy*() )
> ```
> 
> Is that how you perceive this?

Yeah exactly, the conclusion is that it's required to wait for asynchronous code to be executed, and therefore, as you commented, wrap the call with `act` or use a query function that uses `act` underneath.

> Do you consider this issue understood/resolved or is there more to research?

At this point, since this behavior is expected, I think we could close the issue with the findings and solutions we posted. Thanks @dcalhoun for the help on this 🙇 .
