### ISSUE TITLE
Post comment form input misaligned

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#35696]
On chrome the input isn't aligned to the action button:

![2021-10-15 at 22 35](https://user-images.githubusercontent.com/253067/137556319-9e9fb393-c8c8-4eca-8f64-d70be45034bf.png)

**Comment by gziolo** [comment]
This block is going to be deprecated so it's a low priority task since this block is experimental and will never land in WordPress core.

**Comment by jordesign** [comment]
Closing this issue as the Legacy Comments block has been deprecated.
