### ISSUE TITLE
Broken link in MenuItem component README.md

### ISSUE THREAD

**Issue by salcode** [WordPress/gutenberg#35690]
### Description

The link for `Shortcut's shortcut prop` points to `/packages/components/src/shortcut/README.md#shortcut`, which when viewed online creates the link (https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/shortcut/README.md#shortcut), which is a 404.

https://github.com/WordPress/gutenberg/blob/151b800139188760a3b165f2a665a409b1ff06e9/packages/components/src/menu-item/README.md?plain=1#L73

### Step-by-step reproduction instructions

1. Go to https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/menu-item
2. Scroll to the bottom of the page
3. Click the `Shortcut's shortcut prop.` link.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mikachan** [comment]
Closing this as it was fixed by https://github.com/WordPress/gutenberg/pull/36800 🎉
