### ISSUE TITLE
Post excerpt: add option to adjust length of excerpt

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#35698]
There is no way to change the length of the excerpt currently for this block. It seems like a really useful feature to perhaps bring into the sidebar in this instance.

![2021-10-15 at 22 43](https://user-images.githubusercontent.com/253067/137556737-5dbae02a-cf10-4f5e-9f0d-78b3d29d35e0.png)

**Comment by carolinan** [comment]
Hi
I am closing this as a duplicate of https://github.com/WordPress/gutenberg/issues/34757

Here is why the option needed to be removed:
https://github.com/WordPress/gutenberg/pull/33366
