### ISSUE TITLE
Post excerpt: consider adding spacing controls

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#35700]
One thing could be great to add to this block would be spacing controls because it has background color options and without those, it rapidly looks not so great:

![2021-10-15 at 22 48](https://user-images.githubusercontent.com/253067/137557292-b14a94bd-796a-44f6-80ca-41a3d1fc5f8a.png)

**Comment by carolinan** [comment]
🤔 How come it does not have the (.has-background) padding, that other blocks have when a background is added.

-Not saying that can replace proper spacing controls.
