### ISSUE TITLE
Image - Full Width Option Missing in Gutenberg 11.7.0

### ISSUE THREAD

**Issue by gsallman** [WordPress/gutenberg#35713]
### Description

When I upload an image I expect to see the Option 'Full Width' for the image. This is not present in Gutenberg 11.7.0, but if I disable the Gutenberg plugin the option is present.

### Step-by-step reproduction instructions

1. Upload an Image  with the 11.7.0 plugin installed
2. Attempt to set it to display 'Full width'
3. Disable the plugin
4. Now try and set the image to 'Full Width'

### Screenshots, screen recording, code snippet

I screenshot comprising two screengrabs is attached. The first shows 11.7.0 with the 'Full Width' option absent, and the second shows the core version of Gutenberg with the 'Full Width' option present

![full-width-missing](https://user-images.githubusercontent.com/5794634/137661677-cc157272-40fe-4a11-b62e-53ac420ca1b5.png)
.

### Environment info

- WordPress 5.8.1 with and without Gutenberg 11.7.0, ASTRA Pro (Child Theme).
- Firefox 93.0 (64-bit) 
- Win 10 PRO 20H2 Build 1942.1288

_No I have not tested this with all other plugins disabled, as disabling the Gutenberg plugin fixes the error._

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by chthonic-ds** [comment]
I can see the full-width option with Gutenberg 11.7.0 and WordPress 5.8.1.

![gutenberg-11 7-image-full-width-available](https://user-images.githubusercontent.com/29587253/137671763-8627fea9-d078-4617-8c49-8cff8ed8f9d2.jpg)

(Note: Wide width is missing from my screenshot due to the theme disabling it as an option.)

Is your image inside a parent element with layout support: for example, a Group block with "Inherit default layout" toggled off? Full-width will not be available for the image in this situation.

**Comment by gsallman** [comment]
@chthonic-ds  I'll do some more testing. I'm noticing the same problem on all the sites I look after now. I'll also reach out to the Astra Team. One thing, probably just a coincidence but both your and my menus with missing items both have five items on them...

**Comment by annezazu** [comment]
Noting that I can't replicate with Gutenberg 11.7.1 and WordPress 5.8.1 using the Twenty Twenty One theme:

<img width="529" alt="Screen Shot 2021-10-26 at 9 18 05 AM" src="https://user-images.githubusercontent.com/26996883/138886950-35ab521d-80ed-49e5-b33f-6320418c5a87.png">

**Comment by annezazu** [comment]
Going to close this out for now but feel free to re-open if the problem comes back up!
