### ISSUE TITLE
The style hook serializes every property independently from block support

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#35727]
### Description

While working on migrating the font family hook from `style` to `class` I've noticed the style hook serialized to `style` any property that it contains, independently from the block supports.

### Step-by-step reproduction instructions

Steps to reproduce:

1. Add a block (for example, list) and set a custom color for the text (it's serialized within `style`). This is now the block content:

```html
<!-- wp:list {"style":{"color":{"text":"#e42121"}}} -->
<ul class="has-text-color" style="color:#e42121"><li>one</li><li>two</li><li>three</li></ul>
<!-- /wp:list -->
```

2. Go to the `block.json` of the block and remove the `color` block support for the block. 

**What's the expected result at this point in terms of block validation?**

a) the block will still have the color and will be valid
b) the block will not have the color and will be invalid.

**Comment by oandregal** [comment]
I'd argue that the block should not have the style serialized to `style` in that particular case, so it'll become invalid because the original content does have the `style`.

However, another thing to consider is filtering: if a third-party (theme through `theme.json`, a plugin, etc) disables the color, I wouldn't expect the block to be invalidated, though.

**Comment by carolinan** [comment]
Can it c) not have the color, but also not cause an error message? Can it self repair?

**Comment by oandregal** [comment]
> Can it c) not have the color, but also not cause an error message? Can it self repair?

We'd need to do the same transformation for the front-end.

**Comment by oandregal** [comment]
This still happens, but now I think it's the proper behaviour: otherwise, the block will become invalid. The visual tools are disabled, as expected.
