### ISSUE TITLE
[Post Comments Block] Displays "Comments are closed" messages on pages, even when comments have never been open 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#35732]
Using any block theme, if you place a Comments block on a page template, you'll see a "Comments are closed" message to indicate that comments are closed. 

This is expected when comments have been open in the past. However, the message also shows up when no comments exist for a page, and that page has never had comments open in the first place. This seems wrong, and there's no way for the user to hide this message. 

**Proposed solution:** 

If the Post Comments block is placed on a page + comments are closed + no comments exist for that page, the block should automatically hide this message. 

**Related Discussion:**

Related: https://github.com/WordPress/twentytwentytwo/pull/127#issuecomment-945550177
Trac: https://core.trac.wordpress.org/ticket/54283

**Comment by carolinan** [comment]
I think this would be solved "magically" when the block is split and no longer uses the comments_template function?
_But will it be split in time?_

**Comment by audrasjb** [comment]
Indeed Gutenberg could use its own Comments template wrapper, however honestly if it's only to remove this message, I think the filter I proposed in [#54283](https://core.trac.wordpress.org/ticket/54283) is the easier approach to get a quick and satisfying result.

But the way, we need the comment block proposed in [PR#127](https://github.com/WordPress/twentytwentytwo/pull/127) on page block template :)

**Comment by audrasjb** [comment]
and thanks @kjellr for opening an issue here!
