### ISSUE TITLE
Media & Text - image is stretched vertically on front end

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#35738]
### Description

In the Media & Text block the image is stretched vertically on the front end.

The image is not stretched in the editor as the `.block-editor__container img` CSS contains `height: auto`.

However on the front end `height: auto` is missing from the block styling: `.wp-block-media-text__media img, .wp-block-media-text__media video`

### Step-by-step reproduction instructions

Add a Media & Text block
Select an image that with landscape dimensions (wider than the height)
Add enough text so that the text appears with a larger height than the image.
Leave the 'Crop image to fill entire column' option off.

View on front end and notice the image is stretched in the vertical.

### Editor view:
![media-text-image-editor-ok](https://user-images.githubusercontent.com/76742815/137771729-d89cefeb-d894-408f-8a80-30f3b727746d.png)

### Front end view:
![media-text-image-front-stretched](https://user-images.githubusercontent.com/76742815/137771817-78826474-95e1-4e41-9b28-463f886d3490.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I wasn't able to replicate this on WP 5.8.1 & Gutenberg 11.7 with TwentyTwentyOne or TwentyTwentyOne-Blocks themes:

<img width="938" alt="Screen Shot 2021-10-19 at 11 34 06 AM" src="https://user-images.githubusercontent.com/3629020/137815827-2a700868-13a4-4918-8c5a-15dda3edfa03.png">

@Sandstromer which version of Gutenberg and which theme are you using when you get this problem?

**Comment by Mamaduka** [comment]
I think the issue was fixed via #30092 and should be part of Gutenberg 11.8.

**Comment by Sandstromer** [comment]
@glendaviesnz - Gutenberg 11.7 and TT1-Blocks theme.

I don't see the issue with TwentyTwentyOne or some block themes such as Blockbase and Tove, as it they have their own `img { height: auto; }` CSS, but with a block theme that does not have this e.g. Twenty Twenty-Two or TT1-Blocks, the issue is present.

@Mamaduka - thank you for pointing out the PR. This will fix it so I will close this issue.
