### ISSUE TITLE
[Quote Block] Indentation and left border is not in sync between the front-end and the editor

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#35740]
By default (when a theme provides no styles), a quote block appears like this in the editor: 

<img width="244" alt="Screen Shot 2021-10-18 at 12 41 06 PM" src="https://user-images.githubusercontent.com/1202812/137773129-b35e5ebf-980f-4dfc-9ac5-018285e5d64c.png">

Note the pink alignment guides I've added in the screenshot. The quote is indented inside of the surrounding paragraph blocks. This indentation is not carried through to the front end. There, the border to the left of the quote hangs off the edge of the text column, and the quote text is shifted left by the same amount:  

<img width="233" alt="Screen Shot 2021-10-18 at 12 40 52 PM" src="https://user-images.githubusercontent.com/1202812/137773136-0166ed80-75e5-4d2d-a9ae-13aab63d09e6.png">

I believe the editor view is the correct one. 

## To reproduce:

1. Using a theme that does not provide any quote block styles, add a quote block.
2. Compare the frontend and backend

## Versions

Gutenberg Version 11.7.0

**Comment by mikachan** [comment]
This no longer seems to be an issue. Currently on GB 13.8.0-rc.1, I am seeing the same styles on the front end and in the editor, and they both look correct:

Front end:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/1645628/181300431-64c22a5c-0c62-40de-84ec-152b20dced9d.png">

Editor:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/1645628/181300555-eb607768-5b89-44ba-87a1-d26abcb13c4d.png">
