### ISSUE TITLE
Handle merging of URL Details REST API endpoint into Core for WP 5.9

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#35756]
[Rich URL previews](https://github.com/WordPress/gutenberg/pull/31464) were introduced for the Link UI in Gutenberg Plugin version 10.9.0. This work is now due to be merged into Core for the upcoming WP 5.9 release.

Therefore we need to ensure the supporting infrastructure is also merged into Core. This is mainly the URL Details REST API controller that was introduced in https://github.com/WordPress/gutenberg/pull/18042.

@hellofromtonya would you be available to pair with me on this one? 

---------

Left a comment about permission handling, after that I'm fine with this merging into GB.

> Is this supposed to land in 5.5? or Is it required for a feature that will land in WP 5.5? If it's supposed to be 5.5, a Core ticket might be needed.

Yep a trac ticket would be needed for this.

_Originally posted by @TimothyBJacobs in https://github.com/WordPress/gutenberg/issues/18042#issuecomment-645416834_

**Comment by TimothyBJacobs** [comment]
@getdave Let's make sure to stabilize the namespace first. I think this should go in `wp-block-editor/v1` to match the block editor settings route.

**Comment by hellofromtonya** [comment]
>@hellofromtonya would you be available to pair with me on this one?

Sure @getdave. Once the namespace is stabilized ([see Timothy's comment above](https://github.com/WordPress/gutenberg/issues/35756#issuecomment-946974745)) and he's 👍 with it, then it needs a Trac ticket and patch for commit (I can help with all of these).

**Comment by getdave** [comment]
> @getdave Let's make sure to stabilize the namespace first. I think this should go in `wp-block-editor/v1` to match the block editor settings route.

@TimothyBJacobs @hellofromtonya Ready for review here https://github.com/WordPress/gutenberg/pull/35915

**Comment by skorasaurus** [comment]
@getdave is this still applicable/valid ?

**Comment by getdave** [comment]
I believe this is in core already
