### ISSUE TITLE
Accessing the front-end from the site editor

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/gutenberg#35758]
## What problem does this address?

If I am not mistaken, it is rather tedious to access the front-end of the website after editing it in the site editor. When a page/post is edited and saved, a view page/post appears in the left bottom corner. This is not the case in the site editor. One has to open the left top menu (WordPress logo), navigate back and navigate via the dashboard to view the website’s front-end. This makes **4 clicks**.

## What is your proposed solution?
Maybe this will be addressed in the site preview (#29398). However, it would be nice to have direct access to the front-end in one click in the meantime.
In the left top menu (toggled by the WordPress logo),

- the site title could be a link to the front-end, or
- there could be a link to the front-end, like ‘Visit site’ (see screenshot for raw idea), like in the dashboard top toolbar.

![Screenshot 2021-10-19 at 13 12 42](https://user-images.githubusercontent.com/5901923/137900261-db17193b-69f6-4274-8c7e-8e81bcc2b3fd.png)

**Comment by Sandstromer** [comment]
I've not really thought about this before, but yes I agree providing a way to access the front end directly from the site editor would be great to have.

After all, we can directly access the site editor from the front end via the "Edit site" link in the admin bar, but going back the other way is currently not possible, without first exiting to the dashboard.

**Comment by paaljoachim** [comment]
Yep. It is a problem that is known but not fixed yet. Here is some discussion about it:
https://github.com/WordPress/gutenberg/issues/29398

Here is another issue: https://github.com/WordPress/gutenberg/issues/29398

**Comment by LittleBigThing** [comment]
@paaljoachim This idea is slightly different, I think, because it suggests to have a link to the homepage of the site.
In the discussion in #29398, as linked above, it is more about a live preview or a link to the page/post/anything you are modifying.
