### ISSUE TITLE
Navigation and  Mini Cart blocks conflict

### ISSUE THREAD

**Issue by grogou** [WordPress/gutenberg#35768]
## Describe the bug
The Mini Cart and Navigation blocks are using `window.onload` event, first for lazy load scripts, second one for init some MicroModal. So if I use these blocks on same page, only work the second rendered block action. In my case I have 

![image](https://user-images.githubusercontent.com/10712881/137478512-59df0bb0-244b-42b3-99bf-a30debd46400.png)
this and mini cart is not working. 

After some research.

I replaced `window.onload` to `window.addEventListener('load',function(){})`
Using this method ensures that the handler is additive and does not replace existing handlers. 
And the 2 blocks works properly.

### Step-by-step reproduction instructions

1. Create some page
2. Insert Navigation and Mini cart blocks and save
3. Open the page and check that last block in order is not working

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Mini cart is not a WordPress core or Gutenberg block, so you would need to contact the developer of that block.
This conflict can not be tested, as we need more information about the custom block.

**Comment by talldan** [comment]
Seems like a legit issue. This is where the nav block is overriding `onload`:
https://github.com/WordPress/gutenberg/blob/ff468f242c1e72a4d254429dba5e0294c6ce9281/packages/block-library/src/navigation/view.js#L92-L97

It could as you say use `addEventListener` or keep a ref to the previous `onload` and make sure it triggers it.

**Comment by carolinan** [comment]
I wasn't trying to say that it was not a legit issue, but that more information about which "mini cart" block is used.
Without that the reproduction instructions can't be followed.

```
Please confirm that you have tested with all plugins deactivated except Gutenberg.
Yes
```

**Comment by talldan** [comment]
I didn't say you weren't trying to say it wasn't a legit issue 😄 

You're right, better testing instructions would be good 👍 

Does look like a fairly easy code quality issue to fix that'll help the nav block to play nicely with plugins.

**Comment by grogou** [comment]
> 
> 
> I wasn't trying to say that it was not a legit issue, but that more information about which "mini cart" block is used. Without that the reproduction instructions can't be followed.
> 
> ```
> Please confirm that you have tested with all plugins deactivated except Gutenberg.
> Yes
> ```

Sorry @carolinan I will give you more information next time. Thank you.

**Comment by grogou** [comment]
It is something easy case so I didn't think we need something more explanation.

**Comment by grogou** [comment]
> 
> 
> Mini cart is not a WordPress core or Gutenberg block, so you would need to contact the developer of that block. This conflict can not be tested, as we need more information about the custom block.

Mini Cart is Woocommerce block, so I will remember it is not recognized block for Gutenberg.

**Comment by carolinan** [comment]
That's what I figured, but there is more than one with that name 😄
