### ISSUE TITLE
Allow block markup to modify blockGap values

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#35778]
We should allow block markup like this to modify the `blockGap` property for a single instance of a block. For example:

```
<!-- wp:group {"style": { "spacing": { "blockGap": "10px" } } } -->
```

Ideally, we could modify the `row` and `column` gap individually. Not sure about the naming here, but for example:

```
<!-- wp:group {"style": { "spacing": { "blockGap": {"vertical":"10px","horizontal":"15px" } } } -->
```

This would be useful in block patterns and templates, when you need just a one-off adjustment.

**Comment by ramonjd** [comment]
Thanks for creating this issue.

We're experimenting with something in https://github.com/WordPress/gutenberg/pull/35454 and over in https://github.com/WordPress/gutenberg/pull/35301 that (so far) saves the following block markup:

```html
<!-- wp:columns {"style":{"spacing":{"blockGap":{"row":"90px","column":"90px"}}}} -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column -->
<!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

Good to know there's another use case for splitting blockGap into row/column. 

cc @stacimc

**Comment by mtias** [comment]
@ramonjd is this issue still relevant?

**Comment by ramonjd** [comment]
Thanks for the ping.

General axial block gap support was added in:

- https://github.com/WordPress/gutenberg/pull/37736

@andrewserong pointed out to me that there's now an issue specific to the Row/Group block:

- https://github.com/WordPress/gutenberg/issues/47084

I think we can close this one.
