### ISSUE TITLE
Word Counts and Table of Contents layout - usability issues

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3578]
When opening the Word Counts / Table of Contents "Dropdown", a list of the headings in the post is displayed. Clicking one of the headings in the ToC moves focus to the corresponding heading block in the content. However, the "Dropdown" stays open, and it partially overlays the block that just received focus:

![screen shot 2017-11-20 at 19 58 10](https://user-images.githubusercontent.com/1682452/33036453-b22799b0-ce2e-11e7-8ac9-b33e3ee1f5fc.png)

Also, the "Dropdown" z-index conflicts with other parts of the UI:

![screen shot 2017-11-20 at 19 58 57](https://user-images.githubusercontent.com/1682452/33036480-c9fb72aa-ce2e-11e7-98be-ca1f734ee814.png)

About the first issue, I'm not sure moving focus to the heading block still makes sense for all the possible scenarios. When checking the ToC, users may want to:
- change the heading level: the controls to do this are now in the top toolbar and in the sidebar "Block" tab
- change the heading content or change its position or delete it: the controls to do these things are in the block

Moving focus to the heading block would fit just some of these workflows. On the other hand, I'm not sure what a better option would be.

**Comment by karmatosed** [comment]
I agree with the z-index but I do think that it staying open has a use case of navigating around. The act of opening, then clicking, then having to open again doesn't seem user friendly to me.

**Comment by afercia** [comment]
@karmatosed have you tested using only the keyboard? 🙂 when it stays open, closing it with the mouse is a matter of one second. To do the same with the keyboard, once focus has moved in a block, you have to navigate through the whole interface. I'd recommend to extend considerations about what is `user friendly` to _all_ users, regardless of the device they use.

**Comment by karmatosed** [comment]
I have and I think this is a case we need to balance experience. Not I am not saying it's perfect, just that leaving it open all the time isn't either.

**Comment by faishal** [comment]
@karmatosed I have submitted the PR #5630 which fix z-index issue mentioned above by @afercia 
![2018-03-15 13_59_08](https://user-images.githubusercontent.com/1633818/37452062-82273452-2859-11e8-990a-a6d8164b1c12.gif)
