### ISSUE TITLE
Post Author Name Font Weight

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#35782]
### Description

Calling this a bug because I think it is. I notice that the CSS for the Post Author Name is:

```
.wp-block-post-author__name {
    font-weight: 700;
    margin: 0;
}
```

The `font-weight: 700;` feels opinionated to me and should be left for themes to style.

### Step-by-step reproduction instructions

Straightforward.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi
This was removed in https://github.com/WordPress/gutenberg/pull/35513 and is fixed for 11.8.
The block will be split so there will be more updates. But it might not be split and tested in time for 5.9.
