### ISSUE TITLE
Column block: invalid flex-basis saved

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#35797]
### Description

After switching the unit type selector on a column block (px, % etc.), a flex-basis value is applied to the column even if the value field is empty.

### Step-by-step reproduction instructions

1. Add a columns block
2. Change the unit selector on a column block
3. Save
4. View the HTML in the frontend, where you will see the following.

```
<div class="wp-block-column" style="flex-basis:px">
…
</div>
```

### Environment info

- WordPress 5.8.1.
- The problem occurs with and without the current version of the Gutenberg plugin active.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aristath** [comment]
Using the latest `trunk` I can't replicate the issue so maybe this has already been fixed? 👀

**Comment by markhowellsmead** [comment]
@aristath Using a completely clean install of 5.8.1 (without the plugin) and Twenty Twenty-One with no customisation, I can definitely reproduce it. (Also if I install the latest public version of the plugin.)

The same issue applies for the padding control: switching to 'em' for both column padding and column width, _but leaving the value field blank_, produces `padding-top:em;padding-right:em;padding-bottom:em;padding-left:em;flex-basis:em`

**Comment by aristath** [comment]
Ah OK... This only happens if I choose a preset with equal columns-size - in which case the width values are empty by default.
