### ISSUE TITLE
Button block option label is confusing

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3579]
I raised #1473 a while ago and it was recently closed. The issue was that you couldn't stop text from wrapping when inserting a button block. While the solution seems to work, the implementation isn't that great.

There's a new toggle switch added to the Block settings called "Stand on a line". What does that even mean? No-one's going to know what what means. I know what the button does but that switch label means nothing.

It needs to be something that people understand like "Wrap text" or "Text wrap".

![button-settings](https://user-images.githubusercontent.com/2078245/33048755-a08abebc-ceb0-11e7-8fd0-a887b46ba573.png)

## Issue Overview

The issue is that the switch label does not give any indication as to what it does and it's confusing.

## Steps to Reproduce (for bugs)
1. Add button block
2. View the Block settings (in the right-hand sidebar)

## Possible Solution
Unless someone has a better suggestion for wording, change it to "Wrap text"

## Related Issues and/or PRs
#1473

_Firefox Quantum 57.0 (64-bit)
macOS Sierra 10.12.1
WordPress 4.9_

**Comment by karmatosed** [comment]
Wrap Text seems the best option.

**Comment by melchoyce** [comment]
Just encountered the same issue. +1 for `Wrap text`.
