### ISSUE TITLE
Preview crashes the editor (intermittent)

### ISSUE THREAD

**Issue by chad1008** [WordPress/gutenberg#35807]
### Description

Under certain conditions, the preview can crash the editor when previewing mobile/tablet and then switching back to desktop.

This isn't consistent and in my tests seems to happen most often when the post content is empty, but there may be more nuance to it than that.

_note: much of this issue is copied from @worldomonation's original [here](https://github.com/Automattic/wp-calypso/issues/57128)_

### Step-by-step reproduction instructions

1. start a new post.
2. add title.
3. press tab to move to the body of the post.
4. click on Preview button.
5. click on Mobile or Tablet.
6. click on Desktop.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/13856531/138120288-c8837a51-4886-4ff9-96b8-72d8620ab008.mov

https://user-images.githubusercontent.com/13856531/138120327-ca358755-39e3-4764-acfd-64a19ecfa7e3.mov

### Environment info

Reproducable on Mozilla Firefox, Microsoft Edge, and Google Chrome. I've personally tested and reproduced on Chrome 94.0.4606.81.

Tested on Gutenberg 11.7.0, but `git bisect` indicates it was introduced back in https://github.com/WordPress/gutenberg/pull/33342

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I was able to reproduce the issue, and it's mostly consistent when using reproduction steps.

## Details
```
Uncaught TypeError: Cannot read properties of null (reading 'removeEventListener')
    at packages/components/src/popover/index.js:459
```

https://github.com/WordPress/gutenberg/blob/a0c59f2ae2caeac94adcc1dbbe965d9851dcf907/packages/components/src/popover/index.js#L458-L468

## Screenshot
![CleanShot 2021-10-21 at 09 45 36](https://user-images.githubusercontent.com/240569/138218743-fa674204-f7b3-4e23-bfcd-de8c638550e5.png)

**Comment by Mamaduka** [comment]
I've somewhat a naive solution for this issue, but I will give it a go 😄 

I am assigning this issue to myself for now.
