### ISSUE TITLE
Gallery block is not properly displaying 100% wide when fullwidth (not 1:1 with the editor)

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#35809]
### Description

The Gallery block (**not the new Image block version**) is not properly rendering on the front-end of a site, when set to fullwidth. I've tested this with a number of themes, both block and classic. This example is with the TT1 Blocks theme. 

The new iteration of the block using flex, but that element is not set to 100% width. This makes the block stop when its maxed out on width in relation to its image sizes. Within the editor, this is not an issue — but on the front-end you can see the difference: 

### Step-by-step reproduction instructions

1. Activate TT1 theme (or any other Gutenberg-first theme really)
2. Add Gallery block with at least two images (if you add more, the screen has to be wider for you to see it). 
3. Set the block to alignfull 
4. Compare the editor v. the front-end. 

### Editor: 
<img width="1953" alt="Screen Shot 2021-10-20 at 11 43 28 AM" src="https://user-images.githubusercontent.com/1813435/138126083-8211987f-f547-478e-91be-ea243c5117a6.png">

### Front-end: 
<img width="1957" alt="Screen Shot 2021-10-20 at 11 43 48 AM" src="https://user-images.githubusercontent.com/1813435/138126131-57f720af-309f-4ddc-9a56-dfb23b40bee6.png">

### Proposed solution: 
Adding `width: 100%;` seems to resolve the issue on the front-end (though we'd need to double-check):
<img width="1957" alt="Screen Shot 2021-10-20 at 11 44 17 AM" src="https://user-images.githubusercontent.com/1813435/138126200-b94085d2-279e-4c0e-9008-2b5cd79a1d9d.png">

### Environment info

WP 5.8.1
Gutenberg 11.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hey @richtabor - given we're all switched over to the new Gallery block now - I can no longer recreate this issue. Ok to close?
