### ISSUE TITLE
ACF fields no longer working as expected

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3580]
ACF (advanced Custom Fields) don't work as expected. I have a number of test ACF fields, one of which is a Repeater with a Gallery field. Clicking the _Add to gallery_ button should open the media modal, allow you to select multiple images, and then close after clicking _Select_.

Clicking _Add row_ inserts multiple rows instead of just one. After clicking _Add to gallery_, selecting the images I want and clicking _Select_, the images are deselected. Doing the same thing a second time, does exactly the same thing. Does the same thing a third time, finally selects the images and closes the media modal.

When I'm returned to main window the ACF repeater has multiple rows which I never added. Clicking the _Add Row_ button again to add a new Row to the repeater, no longer works, or takes multiple clicks before it will perform the action. The _Delete row_ (-) and _Add row_ (+) buttons are just as unreliable.

## Steps to Reproduce (for bugs)
1. Add an ACF repeater that contains a Gallery field
2. Try and add images to the Gallery

## Expected Behavior
I should be able to simply click _Add to gallery_, select my images, and then return to the edit screen. it now takes multiple clicks and button functionality is completely broken

## Current Behavior
ACF Button behaviour is not working as expected

## Screenshots / Video
https://cl.ly/2u0O1a1W3L2z

_Firefox Quantum 57.0 (64-bit)
macOS Sierra 10.12.1
WordPress 4.9_

**Comment by StaggerLeee** [comment]
Additional one Taxonomy and one Select field are shown multiple times. 3 times both.

**Comment by youknowriad** [comment]
> Welcome to React hell.

This has nothing to do with React

Do you how this behaves in master. Some changes have been made to the metaboxes (not yet released)

**Comment by StaggerLeee** [comment]
It is gone with latest version. Duplicate fields.

**Comment by danielbachhuber** [comment]
Closing, as this seems to be a stale issue. Feel free to open a new issue for any new bug reports.
