### ISSUE TITLE
Button block: two "Change alignment" icons in toolbar

### ISSUE THREAD

**Issue by chthonic-ds** [WordPress/gutenberg#35814]
### Description

Two "Change alignment" icons are displayed in the Button block toolbar.

They offer different options:

- None, Wide width, and Full width
- None

### Step-by-step reproduction instructions

1. Add a Buttons block.
2. Select the default button to reveal the Button toolbar.
3. Observe two "Change alignment" icons are displayed.

### Screenshots, screen recording, code snippet

![buttons-duplicate-alignment-toggles](https://user-images.githubusercontent.com/29587253/138160045-d0ce5474-4081-472b-9a3b-b59302e1f84e.gif)

### Environment info

- WordPress 5.8.1, Gutenberg 11.7.0, tested with Empty and TT1 Blocks themes
- Chrome 94.0.4606.81
- Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I was able to replicate this on trunk and tt1-blocks.

**Comment by Mamaduka** [comment]
It is probably related to #35341.
