### ISSUE TITLE
Navigation Block - improve placeholder flow

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#35818]
## What problem does this address?
#35746 would introduce the concept of saving a navigation block's data to a separate post type, similar to how a template part works.

That PR introduces an extra step in the block setup. First you create or choose an existing 'Navigation menu':
<img width="625" alt="Screenshot 2021-10-21 at 2 22 03 pm" src="https://user-images.githubusercontent.com/677833/138222474-56e29769-cded-4746-9058-0feb3ba57e60.png">

If a new one is created there's a second step with the familiar block interface placeholder:
<img width="623" alt="Screenshot 2021-10-21 at 2 23 02 pm" src="https://user-images.githubusercontent.com/677833/138222602-adfe8043-e4db-40f7-a6c6-8ee6116a71ff.png">

This could do with some refinement.

**Comment by tellthemachines** [comment]
One thing that might be confusing is the apparent repetition between "Choose existing" (navigation block) and "Add existing menu" (classic menu). Ideally we have a single-step placeholder, but just putting all the current options of the two placeholders together won't work very well. Would be great to have some design thoughts on this! Cc. @jasmussen 

(I assigned myself the issue as I'm happy to deal with the implementation but need some guidance on what to do 😅 )

**Comment by talldan** [comment]
Yeah, that is definitely confusing.

Perhaps the 'Add existing menu' option could be rephrased to something like 'Copy existing menu', and the dropdown could include both the new navigation menus and classic menus.

**Comment by jasmussen** [comment]
Some of the dynamic behavior of the new interface is still a little beyond me so forgive me if I'm slow to pick this up, and please correct what I get wrong, thank you. As I understand it:

- In the first step you can choose to link to an existing cpt-saved menu which when edited syncs all the way round, whether being edited in the block or the screen.
- If you click "new", it's just the block as we know it, and it behaves like other blocks needing to be in a template part or reusable block if it needs to be synced.

If that is the case, then it _seems_ like the simplest solution would be to move the "Choose existing" dropdown into the block itself, and to replace the "Add existing menu" dropdown. What would be the shortcomings of this one?

**Comment by talldan** [comment]
> If you click "new", it's just the block as we know it, and it behaves like other blocks needing to be in a template part or reusable block if it needs to be synced.

This step does create a new 'wp_navigation' post. It's based on the flow when adding a new Template Part block.

It could be an option to move the naming of the post until after having clicked 'Start empty' or 'Add all pages'. So there would be one step to the placeholder with the following options:
- 'Use existing menu' - dropdown contains both the new 'wp_navigation' posts and classic menus. If the user selects a 'wp_navigation' menu it's loaded without the user having to name it. If a classic menu is selected, the user has an option to name the menu, but the input is perhaps pre-filled with the name of the classic menu?
- 'Add all pages' - after clicking user has to name the menu
- 'Start empty' - after clicking user has to name the menu

**Comment by tellthemachines** [comment]
> If a classic menu is selected, the user has an option to name the menu, but the input is perhaps pre-filled with the name of the classic menu?

What if we just use the classic menu name and skip this step altogether? The name can always be changed later in the inspector.

**Comment by talldan** [comment]
Yeah, wasn't sure whether it would be necessary. Sounds good 👍
