### ISSUE TITLE
Bad link to v11.7.1 changelog in the readme file

### ISSUE THREAD

**Issue by NobNob** [WordPress/gutenberg#35821]
### Description

In the updated string of the readme file for version 11.7.1, the link points to the 11.7.0 changelog:

`To read the changelog for Gutenberg 11.7.1, please navigate to the <a href="https://github.com/WordPress/gutenberg/releases/tag/v11.7.0">release page</a>.`

### Step-by-step reproduction instructions

As example, here is the string for **es_ES** at translate.wordpress.org:

https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev-readme/es/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=8950176&filters%5Btranslation_id%5D=88992662

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by oandregal** [comment]
:wave: Javier. Thanks for the report.

We missed updating that link during the release process. I've changed it [yesterday in our repo](https://github.com/WordPress/gutenberg/commit/05554af4ebc32b2d3a21f534c36d9da0a9f74f88) but that change won't be out to translate until we do a new release. Fixing an existing release is a bit convoluted and doing a v11.7.2 seems too much for this. We'd rather focus on shipping 11.8 in a few days.

I'm going to leave this open until 11.8 is released so other people that came to report this can see it.
