### ISSUE TITLE
Flex Layout: Allow control over vertical alignment of children

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#35849]
The current flex layout controls allow us to specify the horizontal justification of child items: 

<img width="177" alt="Screen Shot 2021-10-21 at 2 51 15 PM" src="https://user-images.githubusercontent.com/1202812/138338963-fa44632c-22db-46c6-bb2f-0da05611c7c6.png">

As a pair to that, we should have the ability to specify the vertical alignment of children too (`align-items`). We can probably reuse icons from the columns block: 

<img width="136" alt="Screen Shot 2021-10-21 at 2 54 34 PM" src="https://user-images.githubusercontent.com/1202812/138339442-a311e90c-ffd4-4dfd-ba61-e1cada01ffcd.png">

Related: #33687

**Comment by tellthemachines** [comment]
Do we want these controls in the sidebar, or is it enough to have them in the block toolbar?

<img width="575" alt="Screen Shot 2022-09-28 at 11 14 28 am" src="https://user-images.githubusercontent.com/8096000/192665248-858faef0-46e0-43a4-af9b-c3fad62eae7d.png">

Also, do we want them to be available for all blocks with flex layout? (I'm thinking of Navigation where these tools are currently disabled)

cc @WordPress/gutenberg-design

**Comment by jasmussen** [comment]
I think @youknowriad asked some questions about an interface for this a while back, and in response we made this inspector mockup for _container_ blocks ([Figma](https://www.figma.com/file/vmHxwa8WhiyiP9poe2om9J/Inspector-Panels?node-id=13371%3A33411)):

<img width="688" alt="Container" src="https://user-images.githubusercontent.com/1204802/192717754-142b8d97-ffcf-4f19-b585-caf6487db5d9.png">

I would think presence in the inspector could be a baseline, but for some blocks we'd almost certainly surface them in the block toolbar as well, on a curation basis, such as the Row block:

<img width="358" alt="Container row" src="https://user-images.githubusercontent.com/1204802/192718479-c8f4b686-e02f-4341-b359-951d16193fa7.png">

There's a question on `align-self` properties for inner blocks. This needs a bit more time in the oven, but this could be the basic idea:

<img width="364" alt="Inner group" src="https://user-images.githubusercontent.com/1204802/192718661-60cbe427-8254-437d-ab2d-85c0e3f9278a.png">

In the case of the inspector controls, we would probably make good use of the ToolsPanel behavior of not showing many of these options by default, allowing you instead to add them from the menu.

**Comment by jasmussen** [comment]
Sidenote on labels-only mode, that's a good opportunity to trim and revisit the verbiage for the labels, both to enhance glancability and toolbar-width. Instead of `Change items justification`, perhaps it could just be `Justification`, and instead of `Change vertical alignment` it could be reduced to `Vertical alignment`. What do you think?

**Comment by tellthemachines** [comment]
> In the case of the inspector controls, we would probably make good use of the ToolsPanel behavior of not showing many of these options by default, allowing you instead to add them from the menu.

This is another one for when we migrate Layout to ToolsPanel then 😄 

> Change items justification, perhaps it could just be Justification, and instead of Change vertical alignment it could be reduced to Vertical alignment. What do you think?

Yes, that would help! We should do something about Move up and down buttons too; would it be ok to make the buttons wider? I don't think we'd want the font size smaller than the current 12px otherwise it becomes unreadable.

**Comment by andrewserong** [comment]
> This is another one for when we migrate Layout to ToolsPanel then 😄

I think this would be great to do! I don't think we already have an issue for this particular task in isolation, so I've written it up in https://github.com/WordPress/gutenberg/issues/44560 so that it can be picked up when the time is right 🙂

**Comment by jasmussen** [comment]
> Yes, that would help! We should do something about Move up and down buttons too; would it be ok to make the buttons wider? I don't think we'd want the font size smaller than the current 12px otherwise it becomes unreadable.

I'd like to think that the block toolbar itself could use a further refactor. Many of the items inside are abs-positioned and have fixed widths, I would imagine that we could move towards varous flex properties here instead. A flex-basis as wide as the icon button should be could potentially grow automatically for wider text.

**Comment by tellthemachines** [comment]
> A flex-basis as wide as the icon button should be could potentially grow automatically for wider text.

Agreed, it makes sense for the button to resize according to its contents!

**Comment by skorasaurus** [comment]
Would love to see this customization as well since as of now, the row variation applies an inline`align-items: center` by default to its immediate children.

**Comment by tellthemachines** [comment]
@skorasaurus there are already controls in the Row block toolbar to change the vertical alignment:

<img width="643" alt="Screenshot 2023-03-09 at 3 20 36 pm" src="https://user-images.githubusercontent.com/8096000/223916041-5f6d4310-3bbe-45ff-aac5-241199bfb00c.png">

I also started a PR over in #47099 to remove the default alignment rules, but don't know how feasible that will be in terms of back compat.

It might be time to close this issue as the migration of layout to ToolsPanel is already tracked elsewhere 🤔

**Comment by andrewserong** [comment]
> It might be time to close this issue as the migration of layout to ToolsPanel is already tracked elsewhere 🤔

Agreed. We have an issue for that over in #44560, so I'll close out this one now.
