### ISSUE TITLE
IE11: Image Block broken

### ISSUE THREAD

**Issue by tg-ephox** [WordPress/gutenberg#3585]
## Issue Overview

Image Block dependency (re-resizable) uses JS functions not available in IE11 causing the block not to render

## Steps to Reproduce (for bugs)

1. Open Post with Image block in IE 11

**This block has encountered an error and cannot be previewed.**

## Expected Behavior

Image block works as in other browers

## Current Behavior

Errors

## Possible Solution

[babel pollyfill](https://babeljs.io/docs/usage/polyfill/) 
## Screenshots / Video

![screen shot 2017-11-21 at 4 46 59 pm](https://user-images.githubusercontent.com/30682649/33058538-c90fa5d4-cedb-11e7-8277-3911a195f4d8.png)

## Related Issues and/or PRs

https://github.com/WordPress/gutenberg/pull/746

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by aduth** [comment]
https://lodash.com/docs/4.17.4#endsWith

**Comment by youknowriad** [comment]
@aduth not as easy as it seems since the issue is in third-party code. We could PR there or provide a polyfill.

**Comment by aduth** [comment]
Oh, I missed that. We could also include it in the transpilation step, but I would expect the dependency should already be shipping a transpiled variant.

**Comment by aduth** [comment]
See: https://github.com/bokuweb/re-resizable/pull/160
