### ISSUE TITLE
[Post Date] Block controls don't show custom date formats

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#35854]
It's possible to use the block markup to customize the date format for the post date block. For example: 

```
<!-- wp:post-date {"format":"M","fontSize":"small"} /-->
```

^ This will display _only_ the month. Formats like this are valid markup, and are interpreted just fine by the editor, except they're not correctly shown in the date format dropdown. If you use a custom format here, the field will just have the default selected: 

<img width="278" alt="Screen Shot 2021-10-21 at 3 26 31 PM" src="https://user-images.githubusercontent.com/1202812/138343898-a22f3a3a-54ab-4cd5-a8af-fa41e3b30598.png">

Instead, if would be great if that could say "Custom" or something like that. 

Related: https://github.com/WordPress/gutenberg/issues/34762, https://github.com/WordPress/gutenberg/issues/35558

**Comment by torounit** [comment]
It appears to have been fixed in #39209.
