### ISSUE TITLE
Navigation: Centered navigation items not centered when the overlay menu option is set to mobile

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#35889]
### Description

In the navigation block, when the the overlay menu option is set to mobile, centered navigation items are not centered.

### Step-by-step reproduction instructions

- Add a navigation block
- Set the overlay menu to "Mobile"
- Set the item justification to "center"
- The items are left aligned

### Screenshots, screen recording, code snippet

This is evident in the Seedlet Blocks theme:
<img width="1060" alt="Screenshot 2021-10-22 at 21 23 30" src="https://user-images.githubusercontent.com/275961/138518415-42524fe1-1067-45fe-921b-5b1ae8e0725c.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Excellent report, turns out right aligned was also broken. Both are fixed in #35913.
