### ISSUE TITLE
Hold your place when switching between visual and HTML

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#359]
From <a href="https://twitter.com/HouseofGrays/status/847644997285404673">this tweet</a>:

> Still on my WordPress editor wish list: hold your place in the content when switching between visual and text mode. Or am I missing it?

Can we do this?

**Comment by iseulde** [comment]
Unless we also spit the text mode into small textareas, I think this will be hard. We tried to do this in core as well.

**Comment by jasmussen** [comment]
The task in itself definitely falls into "seems cool, if we can do it and have time we should".

When you say it would be hard, how hard would it be on a scale from _trivial_ to _nightmare hell-ride_?

Feels like this might be one of those situations where there might be a clever solution.

**Comment by iseulde** [comment]
Not sure, would have to try. The problem with a single textarea is that it's just the text contents dumped into a single box. There might be a way if we keep a clone in a div with the same measurements and keep an ID there, measure it, and scroll that height.

**Comment by mtias** [comment]
I am not sure this is worth keeping around in the current state. I suggest closing.

**Comment by jasmussen** [comment]
👍 👍
