### ISSUE TITLE
Editor crash when editing themes default color palette values

### ISSUE THREAD

**Issue by neilorangepeel** [WordPress/gutenberg#35901]
### Description

Via the full site editing editor, editing one of the themes default color palettes values results in a blank white screen.

### Step-by-step reproduction instructions

1. Fresh installation of WordPress Version 5.8.1 or higher.
2. Fresh install of Gutenberg plugin.
3. Install any Full Site Editing theme. (e.g. TT Blocks).
4. Head to 'Site Editor' > 'Styles' > 'Colors' > 'Palette' > Select on of the default color > change it's value

Not sure if this has been reported. I couldn't find it. 

### Screenshots, screen recording, code snippet

![wordpress-bug](https://user-images.githubusercontent.com/3746751/138599353-05c444ea-cc11-47ef-b3af-3570a5bc0e99.gif)

### Environment info

Wordpress Version 5.8.1 or higher
Gutenberg 11.7.1
TT Blocks theme (tested on other FSE themes also)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @neilorangepeel

Thanks for reporting the issue. I think it got resolved via #35670. I'm no longer able to reproduce it on the current Gutenberg trunk.
