### ISSUE TITLE
Gallery Refactor: Restore data-id attribute for image blocks

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/gutenberg#35907]
### Description

Block gallery image markup has included a `data-id` attribute on each gallery image `<img>` tag since WordPress 5.0. This attribute includes the image attachment post object's id for images hosted locally in the media library. It allows plugins and themes to access other structured data related to the image through the core `attachment` post type. This can be used in both PHP and JS to pre- or post-process the post content markup.

The data-id attribute is currently missing from the refactored gallery block (as of Gutenberg 11.7.1). Now that all gallery images are image blocks, this attribute should be provided for all locally-hosted images in the content. Adding the attribute to more images is much less likely to cause breakage than removing it from existing markup and on new gallery posts; in fact, it would probably resolve issues with current extender usage of this markup. In my usage, removing the attribute breaks several themes/plugin/sites that I maintain.

This was previously fixed here: https://github.com/WordPress/gutenberg/pull/30710, but appears to have been reverted. I can't find any discussion of why it was reverted. This is the only remaining blocking issue that I see for including the gallery refactor in core.

A possible backup plan would be to instead fix support for the core `get_post_galleries()` function that has been broken since WordPress 5.0. That would allow some programmatic relationship between images in the content and their associated attachment post objects. However, that would still be a break in backwards compatibility and require theme/plugin changes.

### Step-by-step reproduction instructions

1. Create an image gallery in WordPress 5.8 with images uploaded to the media library. 
2. Observe that the published gallery markup includes a `data-id` attribute on the gallery `<img>` tags.
3. Enable the gallery refactor experiment with Gutenberg 11.7 and create another image gallery with images uploaded to the media library.
4. Observe that the published gallery markup does not include the `data-id` attribute on the gallery `<img>` tags.
5. An example of the resulting breakage can be seen with the Arbutus theme. Using the `gallery` post format, the front page excerpt view should display a partial gallery with the first several images from in the post content. This doesn't work with the refactored gallery block - a blank bar displays instead.

### Screenshots, screen recording, code snippet

This was previously fixed with the code here: https://github.com/WordPress/gutenberg/commit/a2253ec518f3769b280c7c7c27e8ea1d0f265a3f

### Environment info

Testing with WordPress 5.9-alpha and Gutenberg 11.7.1 with the gallery block refactor experiment enabled.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by celloexpressions** [comment]
Also pinging @glendaviesnz on this.

**Comment by getsource** [comment]
Hey @celloexpressions! Thanks for the report. 

I looked into this a bit, and found discussion here:
https://github.com/WordPress/gutenberg/pull/25940#discussion_r618196856

**Comment by mtias** [comment]
Worth noting that this should be a simple hydration server-side, avoiding the serialization of data-attrs.

**Comment by glendaviesnz** [comment]
> Worth noting that this should be a simple hydration server-side, avoiding the serialization of data-attrs.

@mtias are you suggesting that we add a render callback to the core image block that adds the data-attrs server side, or that plugin authors can add this themselves if needed?

**Comment by glendaviesnz** [comment]
@celloexpressions I have started looking at what would be involved in getting `get_post_galleries` fixed using this [existing diff](https://core.trac.wordpress.org/attachment/ticket/43826/43826.diff) as a basis

**Comment by mtias** [comment]
That core would add it.

**Comment by ramonjd** [comment]
I'll make a start on this today

**Comment by glendaviesnz** [comment]
I have add a PR for a suggested update to the `get_post_galleries` method in core and updated the existing trac ticket at  https://core.trac.wordpress.org/ticket/43826#comment:42

**Comment by ramonjd** [comment]
> This was previously fixed here: #30710, but appears to have been reverted. I can't find any discussion of why it was reverted. 

@glendaviesnz pointed out to me that it would have entailed creating a deprecation. See: https://github.com/WordPress/gutenberg/pull/25940#discussion_r618196856

**Comment by mtias** [comment]
Yes, doing it purely server-side would avoid deprecations and be the correct way to go about it since it's not essential data and can be easily reconstructed.

**Comment by ramonjd** [comment]
Does anyone have advice for the Arbutus-related question: https://github.com/WordPress/gutenberg/pull/35975#issuecomment-953766673

I'm wondering if there's a wider need to add a `data-id` attribute to image at the point `$post->content` is rendered to the screen, or whether we can work with the theme developer for a fix on the theme side.

[Here's where Arbutus is looking for the attribute](https://themes.trac.wordpress.org/browser/arbutus/1.3/content-gallery.php#L21) and the [method that returns the excerpt](https://themes.trac.wordpress.org/browser/arbutus/1.3/inc/template-tags.php#L131).

**Comment by glendaviesnz** [comment]
Some more [context here](https://github.com/WordPress/gutenberg/pull/35975#issuecomment-953429858) @mtias, @celloexpressions  - the problem with the suggested server side addition of the `data-id` is that it happens after the post content has already passed through the theme functions so doesn't help.

**Comment by glendaviesnz** [comment]
@mtias, @celloexpressions maybe if we can get [this fix](https://github.com/WordPress/wordpress-develop/pull/1788) for get_post_galleries into 5.9 it will provide enough of a fallback?

**Comment by celloexpressions** [comment]
Thanks for looking into this @glendaviesnz. I would expect two categories of `data-id` usage that could become broken: server-side processing and client-side.

Fixing `get_post_gallieries()`, and hopefully by extension, `get_post_gallery()` and `get_post_gallery_images()`, probably eliminates most need for `data-id` for server side processing. I would speculate that many-to-most themes or plugins looking for ids that way do so as a fallback for those core PHP functions and are specific to galleries. And they should still have those functions in place to handle pre-5.0 output, so could continue working with 5.9+ without changes. These functions should definitely be fixed regardless, and doing so could be enough to justify removing the data attribute even though it won't preserve 1:1 compatibility.

Plugins and themes can also rely on this data attribute for front end processing. My Full Screen Galleries plugin is an example. I'm not sure how widespread that strategy may be. The breakage is less severe in that case, and it would be possible to look for the image ID from another source such as the class name as long as it's presented consistently in the markup. So that's a similar situation where it would be better to get the attribute added back into the frontend output, but there are potentially other options.

**Comment by ramonjd** [comment]
> image ID from another source such as the class name as long as it's presented consistently in the markup

@glendaviesnz will correct me if I'm way off, but there is a class attribute, e.g.,  `wp-image-86` [added to every image in save.js](https://github.com/WordPress/gutenberg/blob/0ca97366d0e6c2020dde9015bace9d9c1c970a1d/packages/block-library/src/image/save.js#L41)

Could that be useful in lieu of explicitly applying a `data-id` in the save.js as well?

**Comment by glendaviesnz** [comment]
> @glendaviesnz will correct me if I'm way off, but there is a class attribute, e.g., `wp-image-86` [added to every image in save.js](https://github.com/WordPress/gutenberg/blob/0ca97366d0e6c2020dde9015bace9d9c1c970a1d/packages/block-library/src/image/save.js#L41)

Yes, one of the reasons for the [initial reluctance to add the data-id](https://github.com/WordPress/gutenberg/pull/25940#discussion_r618196856) was the duplication of the value in the existing classname:

> This means, we'd need a deprecation for the image block, given that the id is already in the "className", I'm not sure this attribute is necessary at all personally.
