### ISSUE TITLE
Real Time Logs and Online Users

### ISSUE THREAD

**Issue by ritvikos** [WordPress/gutenberg#35909]
## Problem Statement:
When a website grows to a certain size, its owners, particularly individual creators may have certain concerns.
And they may be frightened that someone else has hacked their site and changed the configurations or updated their articles.

## Proposed Solution Overview:
Incorporating real-time online users and Login/Sign-In Logs onto the WordPress Top Right Side of the Top Bar, where the Howdy "User" is displayed, would be beneficial.
This method can give the site owner peace of mind about whether or not their site is being utilized by others.

## Logs (Feature):
The logs will include the user's local time, IP, username, and email with which the site was accessed.

## Real Time Users (Feature):
The color of real-time online users will change to red if someone other than the added users accesses and uses the WordPress Site; otherwise, it'll remain green.

**Comment by talldan** [comment]
@Ritvik-UX Thanks for reaching out with this feature request.

As this seems like a general WordPress feature, the right place to report this would be https://core.trac.wordpress.org/.

This github repository is for changes relating to Gutenberg and the block editor.

Would you be happy to create a new trac ticket for this? It'd be worth searching for existing tickets too, as someone else might have requested this feature.
