### ISSUE TITLE
Editor specific styles are not applied when the same selectors are used in common styles.

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#3592]
I was trying to play with the [Gutenberg block example](https://github.com/WordPress/gutenberg-examples) and for the [second example](https://github.com/WordPress/gutenberg-examples/tree/master/02-stylesheets) the editor specific style is never applied as this is always replaced by the common style.

**Comment by kmgalanakis** [comment]
While further debugging this, I've found out the issue is caused by [this line](https://github.com/WordPress/gutenberg/blob/master/lib/client-assets.php#L758) in combination with [this one](https://github.com/WordPress/gutenberg/blob/master/gutenberg.php#L135).

**Comment by kmgalanakis** [comment]
I've submitted a [pull request](https://github.com/WordPress/gutenberg/pull/3593) for this.

**Comment by youknowriad** [comment]
Do you know if this is still an issue. Meta boxes were changing the styling order but I believe it's fixed now since we're prefetching them?

**Comment by kmgalanakis** [comment]
@youknowriad this is not an issue anymore, as far as I can tell.

This seems to be working fine, so I'm closing this.
