### ISSUE TITLE
Create a Schemas Package

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#35927]
## What problem does this address?

Recently schema definitions for theme.json and block.json were uploaded to the SchemaStore.org ([theme.json](https://json.schemastore.org/theme-v1.json), and [block.json](https://json.schemastore.org/block.json)). 

Using JSON schemas makes it easier for development. Supported editors can show tooltips, autocomplete, and validation issues. Documenation on using schemas were added in: https://github.com/WordPress/gutenberg/pull/35835 https://github.com/WordPress/gutenberg/pull/35739

The SchemaStore.org is a global open collection of JSON schemas, plus includes good documentation on using schemas. So it is still worthwhile to list our schemas there, as developers may look there to use them as it gets popular.

@gziolo brought up in https://github.com/WordPress/gutenberg/issues/35902#issuecomment-950668162 and https://github.com/WordPress/gutenberg/pull/35843#issuecomment-949365738 that we should have a definitive source in the Gutenberg repo, which could also be used for validation during the build processs.
 
## What is your proposed solution?

We should create a "schemas" package at "@wordpress/schemas" to hold the definitive schemas definitions, these can by copied to the SchemaStore to keep in-sync. Another benefit of having the schemas in the Gutenberg repo is they would also get versioned with tags/branches related to the releases, for example the WP 5.8 could be:
`https://github.com/WordPress/gutenberg/tree/wp/5.8/packages/schemas/block.json`

## Questions

The schema store has three directories, `js`, `,css`, and `json` and the schemas are nested there.

@gziolo mentions in https://github.com/WordPress/gutenberg/issues/35902#issuecomment-950934321 that there are i18n configs that could find a home in the schemas package.

So what directory structure should we use in the package?

My suggestion for flexibility to create: a `json/` directory to start and store them there.

**Comment by gziolo** [comment]
> My suggestion for flexibility to create: a `json/` directory to start and store them there.

Sounds good 👍🏻 

The steps required to create a new WordPress package are documented in https://github.com/WordPress/gutenberg/tree/trunk/packages#creating-a-new-package.

**Comment by ryanwelcher** [comment]
Wanted to mention that the current block validator plugin ( https://wordpress.org/plugins/developers/block-plugin-validator ) incorrectly flags items that are actually valid. 
<img width="888" alt="block-validator" src="https://user-images.githubusercontent.com/1259027/139131960-b8a12376-c79e-4240-8343-96b2904b596d.png">
If we can use this package to also keep that tool up to date, we'll avoid a lot of frustration and confusion for developers.
