### ISSUE TITLE
Navigation block: Add buttons block to the allowed blocks

### ISSUE THREAD

**Issue by briceduclos** [WordPress/gutenberg#35924]
## What problem does this address?
The navigation block currently supports menu items  (page, post, custom, tag, category, ...) links, Social Icons, Spacer, and Search blocks (https://github.com/WordPress/gutenberg/issues/33278).

However, it’s currently not possible to add a button block while it’s a common feature to have a button inside the site’s header.

## What is your proposed solution?
Allow the Buttons block inside the navigation block.

**Comment by lwangdu** [comment]
I would love to have option to add a button on the navigation block to.

**Comment by chthonic-ds** [comment]
A big vote from me to allow a Buttons block as a child of the Navigation block. I just noticed this fairly common header/navigation pattern isn't currently possible:

![35924-add-button-inside-navigation-block](https://user-images.githubusercontent.com/29587253/154886909-e4495b52-baf1-4fdb-8bb5-672f5d4a702a.png)

**Comment by coreyworrell** [comment]
This issue needs traction.. At the minimum we should be able to apply classes to the anchor tag. Then you could at least manually style as a button, the Link Advanced CSS Class could be set to `wp-block-button` and a new Anchor CSS Class field could then be set to `wp-block-button__link has-primary-background-color has-background`. But it's much harder to do at the moment.

**Comment by masperber** [comment]
+1 to this feature request. This is very commonly requested on .com

**Comment by csabarakasz** [comment]
+1 to this feature!

**Comment by huubl** [comment]
+1!

Related:
https://github.com/WordPress/gutenberg/issues/46256
https://github.com/WordPress/gutenberg/issues/31387
