### ISSUE TITLE
Allow themes to opt-in to font-smoothing via theme.json

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#35934]
One reset-adjacent feature that many themes opt-into is font smoothing. Sure, they could do this with a couple lines of CSS, but I wonder if this is common enough that we should just allow it to be a single line in theme.json instead. 

```
-moz-osx-font-smoothing: grayscale;
-webkit-font-smoothing: antialiased;
```

The past three default themes (Twenty Nineteen, Twenty Twenty, and Twenty Twenty-One) all opted into this via CSS, and I'd like to do it for Twenty Twenty-Two as well.

**Comment by sagarnasit** [comment]
Hi @kjellr 

I use theme.json for almost all the themes I am currently working on. This looks like an excellent feature to add.

Let me know if I can take on adding this feature in the Gutenberg.

**Comment by kjellr** [comment]
Hey @sagarnasit — go for it! I think a PR would be worthwhile.

**Comment by sagarnasit** [comment]
Great! @kjellr 

This feature would go in `styles -> typography -> fontSmoothing` in the theme.json file

```
{
	"version": 1,
	"style": {
		"typography": {
			"fontSmoothing": true,
			...
		}
	}
	...
}

```

I have a couple of questions in mind.

1. Adding the above style should work fine. Does it require adding settings as well for font-smoothing?

2. Does this feature require support for `elements` and `block` level styles too?

**Comment by kjellr** [comment]
> Adding the above style should work fine. Does it require adding settings as well for font-smoothing?

I do not think we need any UI/settings for this. 

> Does this feature require support for elements and block level styles too?

I think just a global toggle would make sense for now.

**Comment by scruffian** [comment]
Looks like a good addition to me. I might even make it opt out...

**Comment by chthonic-ds** [comment]
Can this be kept as opt in, please? Those two lines of CSS are not supported for many users. For those it does affect, there's also the potential for a11y issues when applied to smaller text and/or text with a light font weight.

**Comment by sagarnasit** [comment]
@chthonic-ds Yes, this feature would be opt-out by default.

**Comment by bgardner** [comment]
Just throwing my two cents in:

1) I absolutely love the suggestion to add support for font-smoothing in theme.json. It’s something I use on practically every site I design.

2) I agree that it should not be turned on by default, for the reasons @chthonic-ds has said (among a few others, I am presuming.)

Given the simplicity of this PR/issue, I hope it finds its way into Gutenberg 11.9, and consequently 5.9. Huge win, IMO if it does.

**Comment by kjellr** [comment]
Closing as per the thoughts in https://github.com/WordPress/gutenberg/pull/36092#issuecomment-957873535.

**Comment by SamuelMiller** [comment]
As a said note, there are critics of anti-aliasing font smoothing (-moz-osx-font-smoothing: grayscale;
-webkit-font-smoothing: antialiased;) who say that it actually degrades the clarity of fonts on computer screens, particularly the typical dark text on a light background. It switches rendering from subpixel-rendering to pixel level rendering:
https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/
https://github.com/google/fonts/issues/1170

The Twenty Twenty Two's CSS has antialiasing enabled. Perhaps this is a mistake.
