### ISSUE TITLE
Cover block gets stuck when shift+clicking text

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#35953]
### Description

Cover block text paragraph gets stuck when shift+clicking on text.

### Step-by-step reproduction instructions

- Add Cover block
- Write text into paragraph
- Press shift and click somewhere on text
- Note how block gets "locked", you can't write anything anymore
- You can't enter text writing mode anymore
- Rich text buttons (B, I, ...) go missing from the toolbar on 2nd click
- You can press backspace and write again 

### Screenshots, screen recording, code snippet

<img width="859" alt="image" src="https://user-images.githubusercontent.com/87168/138875652-8ba104c0-9b60-46f7-bb22-c0a74cd4931c.png">

https://user-images.githubusercontent.com/87168/138875478-2ca3cbb0-95b5-480b-9571-1e1cf2bcaba3.mov

### Environment info

MacOS
Firefox 93
Gutenberg v11.7.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @simison

I think the issue got fixed via #35668.

**Comment by Mamaduka** [comment]
I was able to reproduce the issue. But I had to select Cover block first and then shift + click inner paragraph.

@ntsekouras, do you think this is related to the issue you fixed in #35668?
