### ISSUE TITLE
Allow users to edit the "default layout" in the Global Styles panel

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#35955]
Whenever you see a block with a "Layout" panel, you're able to select "Inherit default layout." This setting pulls from the theme options to provide a default layout. 

It seems natural that users would be able to edit these values in the "Layout" section of Global Styles, but they're not there currently:

<img width="280" alt="Screen Shot 2021-10-26 at 8 20 37 AM" src="https://user-images.githubusercontent.com/1202812/138877953-20f1eb88-bb44-42fb-9ec0-1f5eb476aca9.png">

(I searched before posting this, and was surprised that there wasn't an existing issue for this?)

**Comment by paaljoachim** [comment]
I believe that Jorge and Andre @jorgefilipecosta @oandregal would like to know about this issue.
Thank you for creating it @kjellr Kjell!

**Comment by ellenbauer** [comment]
I second that, I already had a few of our block theme users ask where they can change the theme's default width. This would be a very helpful addition to Global Styles.

Plus somehow Gutenberg 11.9.0 doesn't give access to general Layout settings. Is this intended?

**Comment by jorgefilipecosta** [comment]
So the issue here is on the block inspector of the normal post editor we should show the values that were set on theme.json? 

I guess if so it is a matter of merging https://github.com/WordPress/gutenberg/pull/34178 that does not for line-height and expand to other styles.

**Comment by kjellr** [comment]
Not quite — we don't show layout settings at all in Global Styles right now, but I think we should do so.

Today|Suggested
---|---
<img width="280" alt="138877953-20f1eb88-bb44-42fb-9ec0-1f5eb476aca9" src="https://user-images.githubusercontent.com/1202812/141785521-2b8c87cb-fd77-42fd-a0de-f15b0e345d7f.png">|<img width="280" alt="Frame 4" src="https://user-images.githubusercontent.com/1202812/141785522-b0512e9c-8f53-4b43-a42b-c476ab50bd0c.png">

(The layout settings there would show the default values from theme.json)

**Comment by jorgefilipecosta** [comment]
> Not quite — we don't show layout settings at all in Global Styles right now, but I think we should do so.
> 
> Today	Suggested
> <img alt="138877953-20f1eb88-bb44-42fb-9ec0-1f5eb476aca9" width="280" src="https://user-images.githubusercontent.com/1202812/141785521-2b8c87cb-fd77-42fd-a0de-f15b0e345d7f.png">	<img alt="Frame 4" width="280" src="https://user-images.githubusercontent.com/1202812/141785522-b0512e9c-8f53-4b43-a42b-c476ab50bd0c.png">
> (The layout settings there would show the default values from theme.json)

@youknowriad do you think we can expand the layouts panel in 5.9 with these additional styles?

**Comment by iamtakashi** [comment]
+1 on this. Thanks for creating it, @kjellr!
