### ISSUE TITLE
Add ability to restrict the list of allowed inner blocks to core blocks

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#35966]
## What problem does this address?

When working with custom blocks there are examples of blocks like for example a custom image carousel that should never be allowed within a core cover block. Or a custom grid block that should not be inserted in a column block. This currently is not possible.

## What is your proposed solution?

Either adding a filter in the core blocks that allows you to use the `wp.hooks.addFilter`  function to modify the list of `allowedBlocks` passed to the inner blocks component within the core blocks. 

There also is an old proposal here: #16560 that feels very similar that would add the allowed inner blocks to the blocks attributes / supports.

**Comment by fabiankaegy** [comment]
This appears to be resolved for the Core Column block as of #35342 and the Core Cover block as of #31326

**Comment by madfcat** [comment]
Yes. But what about adding restricting blocks on `core/quote` author field? You can add anything there.
`const quote_metadata` in `block-library.js` does not have `allowedBlocks` field, hence I can not even use `addFilter` hook.

**Comment by fabiankaegy** [comment]
@madfcat I'd encourage you to open a specific issue for that block
