### ISSUE TITLE
I don't think should_load_separate_core_block_assets supports registerFormatType or addFilter('blocks.registerBlockType',)

### ISSUE THREAD

**Issue by shimon246** [WordPress/gutenberg#35987]
`add_filter( 'should_load_separate_core_block_assets', '__return_true' );`
Does this filter hook work with blocks added with `registerFormatType` or filters added with `addFilter('blocks.registerBlockType',)`?

I don't think so, because registerFormatType can't be associated with css like register_block_type.

## Related references
Block-styles loading enhancements in WordPress 5.8
https://make.wordpress.org/core/2021/07/01/block-styles-loading-enhancements-in-wordpress-5-8/
registerFormatType
https://developer.wordpress.org/block-editor/how-to-guides/format-api/1-register-format/
@wordpress/compose
https://developer.wordpress.org/block-editor/reference-guides/packages/packages-compose/

**Comment by gziolo** [comment]
`registerFormatType` doesn't work with the `should_load_separate_core_block_assets` feature. This method has a different role. It allows adding new formatting controls for blocks that use RichText for inline editing.

Integration with `blocks.registerBlockType` filter won't take effect, because changes to the assets need to be applied on the server rather on the client. There are PHP hooks that you could use instead:
- https://developer.wordpress.org/reference/hooks/block_type_metadata/
- https://developer.wordpress.org/reference/hooks/block_type_metadata_settings/
- https://developer.wordpress.org/reference/hooks/register_block_type_args/

**Comment by shimon246** [comment]
@gziolo 
Thanks for commenting!👍

I still can't seem to get the block name with the PHP hook you advised.

## Complete code
my-plugin.php
```my-plugin.php
<?php
/**
 * Plugin Name: My Plugin
 */

add_filter('should_load_separate_core_block_assets', '__return_true');

function test_enqueue_block_editor_assets () {
  // For development testing
  $timestamp = date('ymdgis');
  wp_enqueue_script('my-block-script',  plugin_dir_url(__FILE__) .'index.js', [], $timestamp, true);
}
add_action( 'enqueue_block_editor_assets', 'test_enqueue_block_editor_assets' );

function test_block_type_metadata( $metadata ) {
  var_dump($metadata);
  return $metadata;
}
// add_filter('block_type_metadata', 'test_block_type_metadata');

function test_block_type_metadata_settings($settings, $metadata) {
  var_dump($settings);
  var_dump($metadata);
  return $metadata;
}
// add_filter('block_type_metadata_settings', 'test_block_type_metadata_settings', 10,2);

function test_register_block_type_args($args) {
  var_dump($args);
  return $args;
}
// add_filter('register_block_type_args', 'test_register_block_type_args');
```
index.js
```index.js
function addListBlockClassName(settings, name) {
  if (name !== 'core/list') {
    return settings;
  }
  return lodash.assign({}, settings, {
    supports: lodash.assign({}, settings.supports, {
      className: true,
    }),
  });
}

wp.hooks.addFilter(
  'blocks.registerBlockType',
  'my-plugin/class-names/list-block',
  addListBlockClassName
);
```

I used the Example code as a reference.
https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#blocks-registerblocktype

## Expected behavior
I want to set the style based on the block name `my-plugin/class-names/list-block` is displayed in the area I am debugging.

I'm thinking that if I can do this, I can use `should_load_separate_core_block_assets` to load them separately.

Of course, the core blocks and the custom blocks added in block.json will be displayed.

Am I interpreting this incorrectly?
