### ISSUE TITLE
Refine columns in Appearance > Templates

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#35995]
Some of the columns in the table at Appearance > Templates aren't all that useful, for example "Slug" and "Status".

The "Theme" column is also a little confusing because it always lists the active theme when you add a new custom template. 

Removing the Slug and Status columns seems like a simple change.

For the "Theme" column, one idea would be to change this to "Added by", then each template can inform which theme, plugin, or user originally added the template, and whether or not it has been customised. Here's an example:

<img width="929" alt="Screenshot 2021-10-27 at 12 27 04" src="https://user-images.githubusercontent.com/846565/139056962-51bf24cb-6cdb-4607-b2bb-011f34d01153.png">

**Comment by carlomanf** [comment]
#31971 already attempts this, it actually has the same exact changes as #35996 but goes one step further and modifies the output of the Theme column.
