### ISSUE TITLE
Use template editing mode when editing a template via Appearance > Templates

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#35990]
Currently, if you navigate to Appearance > Templates and open a template, the post editor mode is used. IE the content area is squished into a narrow column, and the document title is visible on the canvas.

This should instead use the same mode as when you edit a template in the site editor, or via the "Template" section of the Inspector when editing a post.

**Comment by carolinan** [comment]
Agreed, that it is using the post editor mode is something that has been confusing to both users and developers when I have tried to explain how templates work.

**Comment by carolinan** [comment]
So where would the edit link lead to if the template is not assigned to a post/page/custom post type? 
What if it is assigned to more than one post? Then you'd have to select which post to open with the template editing mode.

_Especially if the site editor is not in 5.9._ If it is in 5.9, I think the edit link would need to go there.

**Comment by carolinan** [comment]
The site editor uses a URL format with the theme name and the name (slug) of the template.
`admin.php?page=gutenberg-edit-site&postId=theme-experiments%2Femptytheme%2F%2Fsingular&postType=wp_template`

The edit link in the appearance > templates view would need to be updated to point to the site editor.
I was not able to figure out how to update/filter the `_edit_link` argument of `register_post_type` to include the theme name and template name, so perhaps the site editor could be updated to accept the `post id` instead.

**Comment by jameskoster** [comment]
> So where would the edit link lead to if the template is not assigned to a post/page/custom post type?
What if it is assigned to more than one post? Then you'd have to select which post to open with the template editing mode.

This is a template editing environment, so my expectation would be that they all link to a view where you edit the template, not the content. Something like:

<img width="1031" alt="Screenshot 2021-11-02 at 12 14 13" src="https://user-images.githubusercontent.com/846565/139844017-e21a3cb2-cf98-4249-bb2c-72b0f4cb745a.png">

In the future it might be nice to preview different items of compatible content while editing the template, but that doesn't seem essential for now.

**Comment by carlomanf** [comment]
Please look at addressing #36060 as a follow-up to this, because the post editor mode did enable access to revisions and the new mode should enable similar access.
