### ISSUE TITLE
Inserter: Insertion point is missing

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#3599]
Previously, we would show a blue line indicating where a newly inserted block would be placed. It appears that this has gone missing.

__Steps to reproduce:__

1. Navigate to Posts > New Post
2. Open inserter in header
3. Hover an inserter block option

__Expected result:__

Inserter blue line is shown where block will be inserted.

__Actual result:__

No line is shown.

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/pull/3613 fixed this.
