### ISSUE TITLE
Mixed use of "website" and "site"

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#36029]
### Description

During the translation of Gutenberg, I noticed that several strings use "site" and several use "website". I think it might be a good idea to use only one term instead of two. 

A good example from the search results: 

![image](https://user-images.githubusercontent.com/4569581/139210841-7447987a-89c4-4f7a-8d33-c9ff49be32ad.png)

Is it an idea to go over all the strings and make them all "website" or "site"?

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
fixed in https://github.com/WordPress/gutenberg/pull/36220
