### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by eirichmond** [WordPress/gutenberg#36025]
When I have SCRIPT_DEBUG enabled everytime I add my custom block I get the following warning:

`Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.`

this is the edit function:

```
export default function Edit({ attributes, setAttributes }) {
	const blockProps = useBlockProps( {
		className: 'my-random-classname-test',
	} );
	const {
		background_color
	} = attributes;

	function onChangeBgColor ( colorValue ) {
		setAttributes({background_color: colorValue})
	}

	return ([
		<InspectorControls>
			<PanelBody>
				<PanelColorSettings // Element Tag for Gutenberg standard colour selector
					title= { 'Background Colour' }
					colorSettings = {[
						{
							value: background_color,
							onChange: ( colorValue ) => onChangeBgColor(colorValue),
							label: __( 'Background Color' ),
						}
					]}
				/>
			</PanelBody>
		</InspectorControls>,
		<div { ...blockProps }>
			<div style={ { backgroundColor: background_color } }>this is another panel</div>
		</div>
	]);
}
```

**Comment by rowinski** [comment]
Have same error, but it's not about custom block, but built-in List block. It appears if I add some class to any List block. Then saving post doesn't change anything in post content.

**Comment by Mamaduka** [comment]
Hi, @eirichmond

Based on your snippet, you're returing multiple elements to render. While React supports this method, you'll need to manually provide a unique `key` for each element. Alternatively, you can use [`React.Fragment`](https://reactjs.org/docs/fragments.html#keyed-fragments) to return multiple elements.

@rowinski, I don't think it's a related issue. If you're still experiencing this behavior, please open the new issue.
