### ISSUE TITLE
Site editor - make it easier to get back to the dashboard

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#36021]
## What problem does this address?
At the moment it takes three clicks to get back to the dashboard, which seems excessive.

## What is your proposed solution?
Have an always available option to return to the dashboard in the navigation sidebar.

**Comment by annezazu** [comment]
Just noting that this has come up a fair bit with the FSE Outreach program, [including the latest call for testing](https://make.wordpress.org/test/2021/10/21/fse-program-pattern-party-summary/):

> The W menu item proves to be a point of confusion, especially when trying to go back to the dashboard. This was brought up by four folks very recently if you include the comments on this additional design post (repeat).

**Comment by javierarce** [comment]
I had a look at the PR that @carolinan is working on and I've been thinking about ways to organize the local back link and the dashboard one.  

<img width="296" alt="Screenshot 2021-10-29 at 18 07 02" src="https://user-images.githubusercontent.com/4933/139467412-fd82694d-dfaf-4137-ae0f-42448b671630.png">

One idea could be to use some sort of breadcrumb navigation. We don't have a lot of space, but on the other hand, if I'm not wrong we only have 3 levels to play with… so I think this could work.

I've used "Editor" as the name of the screen that contains Theme & Content, but maybe we could find a more appropriate name for that.

![image](https://user-images.githubusercontent.com/4933/139473421-1f2d90ca-4ca5-4a75-bb78-4037c734c4b0.png)

We could also replace the left arrow with the dashboard icon (so it's clear that the link refers to the wp-admin) and reduce the padding around the menus (so we gain some space for the breadcrumb).

![image](https://user-images.githubusercontent.com/4933/139473481-2ed9b958-af4b-4ec6-b7c6-68e1caa5cf8f.png)

**Comment by vindl** [comment]
I think this issue is no longer relevant after we merged https://github.com/WordPress/gutenberg/pull/36194. The W button is now taking the users back to the dashboard.

Feel free to reopen it if I missed something.
