### ISSUE TITLE
FSE - Unable to save background color on template part

### ISSUE THREAD

**Issue by poof86** [WordPress/gutenberg#36039]
In the FSE I'm able to select and change the background color of a template part.
Saving shows the template-part was modified, but reloading or checking front-end shows no background color was saved.

**Comment by carolinan** [comment]
I believe this has been solved, do you mind re-testing with the latest development version of Gutenberg?

**Comment by poof86** [comment]
I tried creating a development version of the Gutenberg plugin, but I get this error when I run build-plugin-zip.sh :
gutenberg/bin/build-plugin-zip.sh: line 75: syntax error near unexpected token `<'

which is this part of the script:

exec 3< <(
	# Get minified versions of vendor scripts.
	php bin/get-vendor-scripts.php
	# Get non-minified versions of vendor scripts (for SCRIPT_DEBUG).
	php bin/get-vendor-scripts.php debug
)
while...

I'm not sure how to continue
I'm on MacOS High Sierra

Thanks

**Comment by poof86** [comment]
I had to execute the script not like this **"sh build-plugin-zip.sh"** but like **"./build-plugin-zip.sh"**

But then I got the error **"Tracker "idealTree:inflate:" already exists"** 
I was using a version higher than the package.json "engines" property was asking.

Installed Node v14 and was able to build the plugin!

Let me test the Block Template-part background color styling next...

**Comment by poof86** [comment]
It works!

But I'm getting other issues now..
for example, the navigation bar doesn't show the correct item justification in front-end.
But that's what you get for using a development version right?

**Comment by carolinan** [comment]
Maybe you need to open a new issue for that 😄

**Comment by poof86** [comment]
> Maybe you need to open a new issue for that 😄

Shouldn't I only open issues for released versions of the Gutenberg plugin?
Or is it procedure to also open issues for development versions?

I'm kinda new to this
