### ISSUE TITLE
Colors (Highlight and custom editor-color-palette) markup not removed and Hightlight bug

### ISSUE THREAD

**Issue by webexpr-dhenriet** [WordPress/gutenberg#36031]
### Description

**If I use Highlight color from the dropdown menu  :** 

![Screenshot_2](https://user-images.githubusercontent.com/62699215/139231270-308d36b2-e09d-4af5-9245-fbf2a190b0aa.png)

```html
<!-- wp:paragraph -->
<p><mark style="background-color:rgba(0, 0, 0, 0)" class="has-inline-color has-blue-700-color">wording</mark></p>
<!-- /wp:paragraph -->
```

**If I use custom color from the sidebar editor-color-palette after used Highlight dropdown :** 
![Screenshot_4](https://user-images.githubusercontent.com/62699215/139231332-14966c90-b029-422c-9990-be58249abf24.png)

```html
<!-- wp:paragraph {"textColor":"red-700"} -->
<p class="has-red-700-color has-text-color"><mark style="background-color:rgba(0, 0, 0, 0)" class="has-inline-color has-blue-700-color">wording</mark></p>
<!-- /wp:paragraph -->
```

**`mark` is never removed so `has-red-700-color` will be never applied.**

![Screenshot_9](https://user-images.githubusercontent.com/62699215/139231436-a9ae2131-f080-4d22-9d08-8fc8f04c4f92.png)

-------

**If I try to add a custom color manually or to paste a hex code, dropdown is closing and do not save the value**

![Screenshot_1](https://user-images.githubusercontent.com/62699215/139232115-ccdf8a71-a26d-44a8-b7ab-4d3b6ce94f74.png)

### Step-by-step reproduction instructions

1) Go to admin, add a paragraph block, 
2) use Colors Highlight dropdown menu option to add a color
3) on the sidebar menu, use editor palette colors settings or add a custom
4) use Colors Highlight dropdown and try to enter a hex value or paste a value

### Environment info

WP 5.8.1
Gutenberg 11.8.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. This behavior is intentional: Highlighting features uses the [mark](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark) element which is provides inline styling and has priority over the paragraph element (a block level styling).
