### ISSUE TITLE
Refactor `normalizePath` function to use `URLSearchParams.sort` to sort the request parameters

### ISSUE THREAD

**Issue by anton-vlasenko** [WordPress/gutenberg#36046]
## What problem does this address?
We have `normalizePath` function in the `wordpress/url` package.
We could refactor it to reduce its size.

## What is your proposed solution?
We could use `URLSearchParams.sort` function to sort the request parameters instead of implementing our custom solution.
Please check https://github.com/WordPress/gutenberg/pull/35992#discussion_r738013100 to see the proposed solution.
All props go to @kevin940726.
Make sure that the unit tests don't fail and it works the same way as the old implementation.

**Comment by amustaque97** [comment]
I would love to work on this issue. Will mention a PR soon.

**Comment by alshakero** [comment]
I think this can be closed since URLSearchParams is a Web API (not JS); so it isn't supported on native. See https://github.com/WordPress/gutenberg/pull/36151 for details.

**Comment by anton-vlasenko** [comment]
https://github.com/WordPress/gutenberg/pull/36151#issuecomment-960730127

**Comment by anton-vlasenko** [comment]
https://github.com/WordPress/gutenberg/pull/36151#issuecomment-960730127
