### ISSUE TITLE
Proposal for backward Compatibility for metas and shortcodes

### ISSUE THREAD

**Issue by samjco** [WordPress/gutenberg#3604]
## Proposal for Backward Compatibility.
Because the WordPress world is gone half crazy about compatibility issues, One can say _"what can we do about it"_ instead of saying _"we don't want to progress to the future."_

Here are my thoughts on what can be done about it, But I think we have to stick with Shortcodes:

Make a Gutenberg button called **"Meta Page Options"**. 
This shows the meta options of all that would show in WordPress normally without Gutenberg: **(ACF, WooCommerce, custom meta, etc)**. When a user clicks this button a screen slides out showing the options as normal. Users can add their meta info and save via **AJAX**. Slide closes.

Now to render the options.
All developers have to do is make shortcodes or extend shortcodes.
To make your own shortcode we can do it with code or Elliott Condon has a nice **Shortcode Developer plugin**.

Gutenberg should include an option to **list all available shortcodes** from plugins loaded.

After shortcode block is added to Gutenberg editor, it can either show as a **placeholder** or temporarily as a **IFrame**.

When content is rendered for preview the IFrame is replaced (preg_replaced) with actual code.

This my 2 cents. 👍 

We should also think about added a **Gutenberg block Builder**. 👍

**Comment by danielbachhuber** [comment]
Apologies for the delayed reply, @samjco.

Thanks for the detailed feedback :) We'll keep it in mind as the project progresses.
