### ISSUE TITLE
Full Site Editing: Bigger and easier to see previews

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#36043]
## What problem does this address?

This is from Twenty Twenty Two new default theme. In Chrome.

![Full-Site-Editing-Front-Page-Preview](https://user-images.githubusercontent.com/5323259/139264502-fd22d6ea-2f42-4264-931f-233e95c63f05.jpg)

There is a lot going on, and it is difficult to focus on the small preview.
Details are difficult to see.

## What is your proposed solution?

A bigger preview that also contains a thicker border/outline. Creating a better contrast between the background.
It should also be easier to see the details inside the preview. (Here I just made the original preview bigger.)

![Full-Site-Editing-Front-Page-Preview-bigger-better-outline](https://user-images.githubusercontent.com/5323259/139265630-b4e2c104-bb10-446a-b7dc-d9fc489d0765.jpg)

It does not matter if it covers a bigger area of the layout canvas area, as one is looking at various templates to figure out which to use.

**Comment by paaljoachim** [comment]
Here is an example from TT1. Which is a lot better. (The preview could be even bigger.)

![Screenshot 2021-10-28 at 15 41 48](https://user-images.githubusercontent.com/5323259/139268007-2d1654aa-16c1-4e40-9f39-eaffdd993a48.jpg)

**Comment by jordesign** [comment]
Closing this issue as the template preview is no longer present in the Site Editor browse view as at WP6.3
