### ISSUE TITLE
FSE: block-template doesn't render in frontend (plain HTML template file)

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#36050]
### Description

The block-template, e.g. for a page, can be used in backend (Gutenberg editor), but on frontend the plain HTML is shown, the areas/block placeholders are not rendered.
What part of WordPress core/Gutenberg plugin is responsible for rendering the block-template HTML? Is it a filter?
Maybe the theme I am using somehow intercepts the renderer? How can I find this out?

### Step-by-step reproduction instructions

1. Enable a FSE theme.
2. Add some content to the site and to a page.
3. View the page.
Note that the page HTML is still the same as the block-template, block placeholders are still in place and not rendered.

### Environment info

- WordPress `5.8.1`
- Gutenberg plugin `11.8.0`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi
You may be looking for [do_blocks()](https://developer.wordpress.org/reference/functions/do_blocks/).
https://github.com/WordPress/gutenberg/blob/trunk/lib/full-site-editing/template-loader.php#L162

**Comment by strarsis** [comment]
@carolinan: Thank you, this is tremendously helpful!

The core [`locate_block_template`](https://github.com/WordPress/WordPress/blob/c7d3e267b8a7aebc28b23efa74b2971602852315/wp-includes/block-template.php#L22) function is used to find a matching template file. So there I can find the reason for why the block template in the theme is not used.


Edit: Found a typo in the comment by the way:
https://github.com/WordPress/WordPress/blob/c7d3e267b8a7aebc28b23efa74b2971602852315/wp-includes/block-template.php#L43
The word `hiearchy` has a typo, it should be `hierarchy`.

**Comment by strarsis** [comment]
See the reason and workaround for this:
https://discourse.roots.io/t/full-site-editing-fse-frontend-doesnt-load-template/21574/5

**Comment by tellthemachines** [comment]
Hi @strarsis, can we close this issue now, or is there anything you still need help with?

**Comment by strarsis** [comment]
@tellthemachines: Well, the typo with `hiearchy` in the comments is still there. 😼 

But otherwise the issue can be closed as `do_blocks` wasn't applied in this particular setup.

**Comment by tellthemachines** [comment]
Thanks @strarsis ! The typo was actually in Core (the link above is to the WordPress repo) and if you look at the [current version](https://github.com/WordPress/WordPress/blob/master/wp-includes/block-template.php#L73) of same file I think you'll find it's been fixed 🙂
