### ISSUE TITLE
`npm run test-unit:watch` no longer supports focused tests

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#36067]
The test runner no longer seems to support changing a test to `describe.only` or `it.only`.

To reproduce:
1. Run `npm run test-unit:watch`
2. Change a unit test to `it.only`.
3. Observe that the focused test is ignored. (this might depend on which test is set to `only`, I noticed this while trying it on `describe( 'undo'` - https://github.com/WordPress/gutenberg/blob/trunk/packages/core-data/src/test/reducer.js#L144)

**Comment by gziolo** [comment]
Isn't it related to the different test runner – Jest Circus – that is used with unit tests for some time? It's a new default starting from Jest 27 that we are going to update to quite soon anyway. Maybe this issue doesn't exist in Jest 27 anymore. We can test against https://github.com/WordPress/gutenberg/pull/33287. I doubt it's anything on the `@wordpress/scripts` side.

**Comment by simonhammes** [comment]
I tried to reproduce this, following the outlined steps: 
> 1. Run `npm run test-unit:watch`
> 2. Change a unit test to `it.only`.
> 3. Observe that the focused test is ignored. (this might depend on which test is set to `only`, I noticed this while trying it on `describe( 'undo'` - https://github.com/WordPress/gutenberg/blob/trunk/packages/core-data/src/test/reducer.js#L144)

But it works for me (on trunk, using `npm ci`).  
I modified the exact line in `reducer.js` to `describe.only` and Jest only executed this section.

**Comment by kevin940726** [comment]
I can't reproduce this either. For me, it's correctly running only the tests I specified. @talldan Could you provide more info or maybe try it with a different setup?

**Comment by talldan** [comment]
It still doesn't work for me. Here's a screenshot:
<img width="385" alt="Screenshot 2021-11-11 at 10 25 00 am" src="https://user-images.githubusercontent.com/677833/141226205-4e86da92-5861-494f-b2e0-9ae9a64a49f2.png">

To reproduce this:
1. Run `npm run test-unit:watch`
2. Add a focus test in the `reducer` file
3. Change the name of a test in the `selectors` file.

Expected - only the `reducer` test executes because it's focused
Actual - the test runner runs the focused test in addition to the other modified tests

**Comment by kevin940726** [comment]
Oh, I think this is expected? `only` only focuses tests in the same file, it doesn't prevent tests in other files from running.

**Comment by talldan** [comment]
Ah, ok, fair enough, didn't realise that. Seems like a bit of a useless feature, and I don't think it previously worked that way.

**Comment by kevin940726** [comment]
I believe it always works that way though 😅 , or at least suppose to. I normally filter the files in watch mode if I only want to focus some of the tests.
