### ISSUE TITLE
Developer experience improvements

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#36093]
It's just a curated list that's been sitting in my head for too long and it's growing bigger and bigger. I just want to list them down here for visibility and to hopefully gather some feedbacks.

Note that these improvements should only affect `development` mode, so that the production builds stay intact. While some of these sound like breaking changes, we can add some feature flags or environment variables to require the developers to opt-in to them.

- [ ] **Replace the 2-pass build steps in development workflow with single-pass**
  The current development workflow (`npm run dev`) consists of roughly 2 parts: building the packages with Babel and bundling them with webpack. This 2-pass workflow isn't really efficient, we're essentially starting 2 watchers on our file system and writing double the code to disk. Instead, we can leverage webpack to do all these in a single pass in development mode so that the initial startup could be faster.
- [ ] **Replace Babel with SWC**
  This just seems like a low-hanging fruit we can do to just drop replace babel with SWC to decrease the build time. Note that we'd probably lose some features that the custom babel plugins provide, so we have to handle them gracefully.
- [ ] **Prevent directly writing to disk**
  IO read/write is quite expensive, we can instead writing them to memory to improve the performance. A bonus advantage is that there's no longer a _stale_ build, since that whenever we change the files the build will be invalidated and recompiled.
- [ ] **Enable hot reload/refresh**
  React has official support of React Fast Refresh, while webpack can also offer CSS hot reload. This should dramatically improve our DX with a faster feedback cycle for simple changes like adjusting styles.

Thoughts? Prior arts we can take experience from? More ideas?
Hit the thumbs-up button and subscribe to this issue for more interesting ideas in the future 😜 .

**Comment by noisysocks** [comment]
> Replace the 2-pass build steps in development workflow with single-pass

I didn't think this was possible due to how we have it set up where each package is loaded into WordPress as a seperate dependency e.g. `@wordpress/components` → `build/components.js` → `wp-components`. But happy to be wrong. `npm run dev` is indeed getting really slow as the project grows 🙂

**Comment by kevin940726** [comment]
> I didn't think this was possible due to how we have it set up where each package is loaded into WordPress as a seperate dependency e.g. `@wordpress/components` → `build/components.js` → `wp-components`. But happy to be wrong. `npm run dev` is indeed getting really slow as the project grows 🙂

Hmm, not sure what you mean here. What we're currently doing is roughly this:

1. Build all packages into it's own `build` folder using Babel. So `packages/a11y` will build `packages/a11y/build` and `packages/a11y/build-module` etc.
2. Watch and rebuild everything in (1)
3. Start webpack watch and build all the packages into project's root `build` folder. However, the entries are `packages/*/build-module` (hence require (1))

Instead, I propose we skip (1) and (2) entirely, and just use webpack and `babel-loader` (or `swc-loader`) to build the packages from `packages/*/src` into project's root `build` folder. So every time we change something, we don't have to wait for Babel to output the build **then** wait for webpack to bundle them. We can just tell webpack to handle them all at once in memory. In theory, together with **"Prevent directly writing to disk"**, this should significantly improve the performance especially for devices that don't have SSDs 😆 .
