### ISSUE TITLE
Multi-entity saving: Cannot publish a post with site entity deselected

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#36096]
### Description

Before publishing a new post that contains post and site entities, deselecting the site entity, then hitting Publish triggers a Javascript error. The result is that I cannot publish a post.

The error is `this.props.setEntitiesSavedStatesCallback is not a function`
It looks like the prop `setEntitiesSavedStatesCallback` is not passed to the [post publish button](https://github.com/WordPress/gutenberg/blob/release/11.8/packages/editor/src/components/post-publish-button/index.js#L56) from the [post publish panel](https://github.com/WordPress/gutenberg/blob/release/11.8/packages/editor/src/components/post-publish-panel/index.js#L93).

First noticed while testing **Site Logo: Add option to set site icon from Site Logo block**
#35892 in https://github.com/WordPress/gutenberg/pull/35892#issuecomment-955811322

### Step-by-step reproduction instructions

1. Create a new post 
2. Insert a Site Logo block. Add or upload an image.
3. Insert some text or a heading.
4. Hit **Publish** to publish the post.
5. In the pre-publish save menu, deselect Logo, then hit **Save**, then **Publish**.
<img width="275" alt="Screen Shot 2021-11-01 at 12 24 09 pm" src="https://user-images.githubusercontent.com/6458278/139609118-bf8b89aa-51cd-4659-9553-dc5867f13e20.png">

### What I expected

That I could publish the post, or that I'd be given feedback as to why I couldn't publish the post without saving the site logo.

### What happened
Nothing in the editor, but the console throws the following error:

<img width="695" alt="Screen Shot 2021-11-01 at 8 55 31 am" src="https://user-images.githubusercontent.com/6458278/139608811-c1e1e130-689a-441b-9d2f-1b405f404ac5.png">

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/6458278/139608805-fc072ef9-519c-4cd9-8787-8fd84e3c0aae.mp4

### Environment info

- WordPress 5.8.1
- Gutenberg trunk
- TwentyTwentyOne and TT1 Blocks

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I have not been able to reproduce this (current trunk at c5e695d)

**Comment by stacimc** [comment]
I pulled current trunk and was able to reproduce this; to re-emphasize, it only happens when publishing a _brand new_ post for the first time.

I was also able to reproduce this with other non-post entities than Site Logo. For example I:

1. Start a new post view `wp-admin/post-new.php`
2. Insert the Template Part block and open the existing Footer template
3. Make some changes to the template
4. Click 'Publish' to publish the post
5. Deselect the Footer template from the pre-publish menu
6. Hit Save, then Publish

I get the same error here as well.

**Comment by ramonjd** [comment]
Was looking at this again. I _believe_ there's some race condition in the store, or we're not correctly removing entity edits when we save.

When the entity checkboxes are saved, and we update via [saveSpecifiedEntityEdits()](https://github.com/WordPress/gutenberg/blob/92f75c1480238323df4cac499c0560a9b32cbda7/packages/editor/src/components/entities-saved-states/index.js#L154), by the time we hit publish the [hasNonPostEntityChanges() selector ](https://github.com/WordPress/gutenberg/blob/a6908dcc4cde747ee2879317597f73179bf6e4d1/packages/editor/src/components/post-publish-button/index.js#L45) still returns true because [__experimentalGetDirtyEntityRecords](https://github.com/WordPress/gutenberg/blob/1e7f8371306f6604b0b0fcfd9e41f319bd2bc12c/packages/editor/src/store/selectors.js#L152) still thinks there are dirty entity records records `[{key: undefined, title: 'a8c-wp-env', name: 'site', kind: 'root'}]`.

I think.

**Comment by ramonjd** [comment]
Passing down the `setEntitiesSavedStatesCallback` prop to `<PostPublishButton />` creates the following effect:

https://user-images.githubusercontent.com/6458278/141091044-025abdf0-11ca-4eb9-aa88-914851126c00.mp4

I can't save the post without also saving the site entity.

**Comment by ockham** [comment]
> Was looking at this again. I _believe_ there's some race condition in the store, or we're not correctly removing entity edits when we save.
> 
> When the entity checkboxes are saved, and we update via [saveSpecifiedEntityEdits()](https://github.com/WordPress/gutenberg/blob/92f75c1480238323df4cac499c0560a9b32cbda7/packages/editor/src/components/entities-saved-states/index.js#L154), by the time we hit publish the [hasNonPostEntityChanges() selector ](https://github.com/WordPress/gutenberg/blob/a6908dcc4cde747ee2879317597f73179bf6e4d1/packages/editor/src/components/post-publish-button/index.js#L45) still returns true because [__experimentalGetDirtyEntityRecords](https://github.com/WordPress/gutenberg/blob/1e7f8371306f6604b0b0fcfd9e41f319bd2bc12c/packages/editor/src/store/selectors.js#L152) still thinks there are dirty entity records records `[{key: undefined, title: 'a8c-wp-env', name: 'site', kind: 'root'}]`.
> 
> I think.

PR to fix this behavior here: https://github.com/WordPress/gutenberg/pull/36573 (but that doesn't fix the issue entirely).

**Comment by ockham** [comment]
Here's an e2e test for this issue that I wrote (based on an existing one). Note that it doesn't actually fail (it just prints the `TypeError` to the console from which it's run, but passes). I hope it'll still come in handy in attempting to fix this issue, and later prevent it from re-appearing.

(I _think_ that the runtime JS error is eaten by `@wordpress/jest-console`. I thus added `expect( console ).not.toHaveErrored()`, but that's not causing the test to fail either. @gziolo Is that expected? Is there any other way to make an e2e test fail if there's a JS console error in the browser?)

```diff
diff --git a/packages/e2e-tests/specs/experiments/multi-entity-saving.test.js b/packages/e2e-tests/specs/experiments/multi-entity-saving.test.js
index a8429cc24a..db9e5444e1 100644
--- a/packages/e2e-tests/specs/experiments/multi-entity-saving.test.js
+++ b/packages/e2e-tests/specs/experiments/multi-entity-saving.test.js
@@ -229,6 +229,47 @@ describe( 'Multi-entity save flow', () => {
 					.saveEditedEntityRecord( 'root', 'site', undefined );
 			} );
 		} );
+
+		// Regression: https://github.com/WordPress/gutenberg/issues/36096
+		it( "Can publish even if some changes haven't been saved", async () => {
+			await createNewPost();
+			//await disablePrePublishChecks();
+
+			await insertBlock( 'Site Title' );
+			// Ensure title is retrieved before typing.
+			await page.waitForXPath( '//a[contains(text(), "gutenberg")]' );
+			const editableSiteTitleSelector =
+				'.wp-block-site-title a[contenteditable="true"]';
+			await page.waitForSelector( editableSiteTitleSelector );
+			await page.focus( editableSiteTitleSelector );
+			await page.keyboard.type( '...' );
+
+			await clickButton( 'Publish' );
+			await page.waitForSelector( savePanelSelector );
+			const checkboxInputs = await page.$$( checkboxInputSelector );
+			expect( checkboxInputs ).toHaveLength( 2 );
+
+			await checkboxInputs[ 0 ].click();
+			await page.click( entitiesSaveSelector );
+
+			await clickButton( 'Save' );
+			await page.waitForSelector( publishPanelSelector );
+
+			await clickButton( 'Publish' ); // Make sure we can publish.
+			expect( console ).not.toHaveErrored();
+
+			// Reset site entity to default value to not affect other tests.
+			await page.evaluate( () => {
+				wp.data
+					.dispatch( 'core' )
+					.editEntityRecord( 'root', 'site', undefined, {
+						title: 'gutenberg',
+					} );
+				wp.data
+					.dispatch( 'core' )
+					.saveEditedEntityRecord( 'root', 'site', undefined );
+			} );
+		} );
 	} );
 
 	describe( 'Site Editor', () => {
```

**Comment by gziolo** [comment]
@ockham, there is a code that should catch the errors and warnings printed on the Browser Console:

https://github.com/WordPress/gutenberg/blob/4384d9c942fe5e5e5767fc9c1c9db9b9ad526e6f/packages/e2e-tests/config/setup-test-framework.js#L106

The check you included in the example operates only on the test suite scope. It would catch issues triggered in the code executed by Jest. That’s why we listen for errors on the page with a listener using the code I shared above.

**Comment by ockham** [comment]
> @ockham, there is a code that should catch the errors and warnings printed on the Browser Console:
> 
> https://github.com/WordPress/gutenberg/blob/4384d9c942fe5e5e5767fc9c1c9db9b9ad526e6f/packages/e2e-tests/config/setup-test-framework.js#L106
> 
> The check you included in the example operates only on the test suite scope. It would catch issues triggered in the code executed by Jest. That’s why we listen for errors on the page with a listener using the code I shared above.

Thanks for replying @gziolo! I'm not sure I understand 100% -- can you clarify what needs to be done in order to have that console `TypeError` cause the test to fail? 😅

**Comment by gziolo** [comment]
> can you clarify what needs to be done in order to have that console TypeError cause the test to fail? 😅

It looks like you want to detect exceptions thrown. Do we have any [`onError`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror) handler configured? There are also Error Boundaries from React that might intercept errors thrown.

**Comment by paaljoachim** [comment]
It would be helpful to get an update on how this PR is coming along.
Thank you!

**Comment by ockham** [comment]
> It would be helpful to get an update on how this PR is coming along. Thank you!

Right, apologies for the lack of updates. The relevant code is unfortunately rather complex (nested callbacks etc) -- I think it's a result of the Publish/Update/Save logic requiring more and more of implicit state as multi-entity saving etc were implemented, and trying to fit that into the existing framework. Arguably, it could use a refactor with a somewheat different architecture (more explicit state?), based on the current requirements.

That said, I also had to drop the ball on this one since I was helping out with other WP 5.9 To-do items that were higher priority. I'm afraid I don't have a clear ETA when I'll be able to get back to this issue 😕

**Comment by paaljoachim** [comment]
Hey Bernie

The PR and various refactors will come along in its own pace...:)
Thanks for the update!

**Comment by stacimc** [comment]
I took a look at this and I think I was able to get it working. I understand if a refactor makes sense moving forward, but #37383 has a possible fix for the meantime and some notes for what I think is happening here, so hopefully it's helpful!

**Comment by ockham** [comment]
Filed draft PR with e2e test based on https://github.com/WordPress/gutenberg/issues/36096#issuecomment-971926623: https://github.com/WordPress/gutenberg/pull/37408
