### ISSUE TITLE
When the navigation block uses justify right, the overlay can't be closed

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#36102]
### Description

When the navigation block has lots of content and the menu items are set to justify right, the overlay can not be closed because the menu seems to be on top of the close button.

### Step-by-step reproduction instructions

1. Add a navigation block. Add lots of content or use an existing menu in the [theme test data.](https://github.com/WPTT/theme-test-data)
2. Select the toolbar option to justify items to the right.
3. Enable the overlay menu.
4. View the block on the front and open the overlay.
5. Try closing the overlay.

Note: I did not test on RTL.

### Screenshots, screen recording, code snippet

With right justification:
![menu item on top of close button](https://user-images.githubusercontent.com/7422055/139628503-7c5b381b-83e2-4a5f-b9fd-3ae7305185b8.png)

Without any justification setting:
![without justification, the close button is not covered.](https://user-images.githubusercontent.com/7422055/139628721-1bee67c5-9553-4cc5-8163-db6b36371303.png)

### Environment info

WordPress 5.8.1, Gutenberg current trunk, Did not test with older versions.
Tested with Twenty Twenty-Two and Emptytheme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Taking a look, thanks for the ticket!

**Comment by jasmussen** [comment]
Should be fixed by https://github.com/WordPress/gutenberg/pull/36105.
