### ISSUE TITLE
Horizontal scrollbar when left floated image present

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3612]
## Issue Overview

If you have a left floated image somewhere in your post blocklist, there's a horizontal scrollbar:

![screen shot 2017-11-22 at 14 00 32](https://user-images.githubusercontent.com/1204802/33128728-b3774008-cf8d-11e7-8f17-9a48fd072381.png)

It looks like the sibling inserter (insert between) needs a float clearer, or some smarts

## Possible Solution

Add "clear: left" to the sibling inserter.

CC: @aduth @mtias

**Comment by aduth** [comment]
Suspecting that this is because a block is assigned a specific width (600-something pixels), and this is currently not shrunk when floating adjacent an image.

**Comment by aduth** [comment]
Fix proposed in #3635

**Comment by aduth** [comment]
Fixed by #3635
