### ISSUE TITLE
Storybook: Missing stories for components

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#36128]
Some `@wordpress/components` components don't have any stories in the Storybook, making it hard to audit or discover.

<details>
<summary>A quick list of the missing ones</summary>
<p>

```bash
$ cd packages/components/src && comm -23 <(find . -maxdepth 1 -type d | sort) <(find . -type d -name  'stories' | sed -E 's/(.+)\/stories/\1/g' | sort)
```

```
./animation
./autocomplete
./circular-option-picker
./clipboard-button
./color-control
./color-list-picker
./composite
./dashicon
./dimension-control
./disclosure
./focusable-iframe
./footer-message-control
./higher-order
./isolated-event-container
./menu-group
./menu-item
./mobile
./palette-edit
./shortcut
./style-provider
./ui
./utils
```

</p>
</details>

We should try to add stories when appropriate.

**Comment by bangank36** [comment]
@mirka can external contributor contribute to the missing story? I am working with Gutenberg components and notice some missing components' story as well. thx

**Comment by mirka** [comment]
@bangank36 Thanks for the offer! Which one specifically are you planning to add?

**Comment by bangank36** [comment]
I re-run your suggested commands for the list of the missing stories again

### Detail status of Storybook stories
#### Edited on 08-Aug-2023
| Component                                    | TypeScript | Storybook |
| -------------------------------------------- | ---------- | --------- |
| [./animation](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/animation)                          |     ✅         |     ➖      |
| [./autocomplete](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/autocomplete)                    |            ✅     |      ❌     |
| [./clipboard-button](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/clipboard-button)               |      ✅       |     ❌ Deprecated      |
| [./color-control](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/color-control)                    |            ➖ |     ➖      |
| [./composite](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/composite)                            |            ➖ |     ➖      |
| [./dashicon](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/dashicon)                              |            ✅ |    ❌       |
| [./disclosure](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/disclosure)                          |            ➖ |     ➖      |
| [./focusable-iframe](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/focusable-iframe)              |     ❌       |      ❌     |
| [./footer-message-control](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/footer-message-control)  |    ➖        |     ➖      |
| [./higher-order](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/higher-order)                      |            ➖ |    ➖       |
| [./isolated-event-container](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/isolated-event-container)|      ✅       |      ❌     |
| [./menu-group](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/menu-group)                          |       ✅      |    ✅ [PR](https://github.com/WordPress/gutenberg/pull/53090)       |
| [./menu-item](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/menu-item)                            |            ✅ [PR](https://github.com/WordPress/gutenberg/pull/53132) |      ✅  [PR](https://github.com/WordPress/gutenberg/pull/53613)      |
| [./mobile](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/mobile)                                  |            ➖ |     ➖      |
| [./shortcut](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/shortcut)                              |     ✅       |     ✅ [53627](https://togithub.com/WordPress/gutenberg/pull/53627)      |
| [./style-provider](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/style-provider)                  |            ✅ |      ➖     |
| [./ui](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/ui)                                          |      ➖  #52953     |    ➖       |
| [./utils](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/utils)                                    |     ➖       |           ➖   |

Though there are some components I am not sure wether they should have stories or not, so I use ➖ to mark them as unknown, maybe a Gutenberg code owner can provide insights for them
 
-----

I think I can add stories for `menu-group` and `menu-item`, so far only [menu-item-choice](https://wordpress.github.io/gutenberg/?path=/docs/components-menuitemschoice--default) has story

- Other side notes on `/ui`, which is referred as Next Component System, it has some stories on storybook
1. [FormGroup](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-formgroup--default)
2. [Spinner](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-spinner--default)
3. [Tooltip](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-tooltip--default)
Should `ui` be placed on separated category like `Next Component`? When first working with components I tried to import `FormGroup` from `@wordpress/componets` only to find out that it is part of other packages `@wordpress/components/ui`

**Comment by mirka** [comment]
> I think I can add stories for `menu-group` and `menu-item`, so far only [menu-item-choice](https://wordpress.github.io/gutenberg/?path=/docs/components-menuitemschoice--default) has story

Yes, I think `menu-group` might be a good one to start. `menu-item` also needs a story, but in general it will be more efficient to migrate it to TypeScript first (part of #35744).

> * Other side notes on `/ui`, which is referred as Next Component System, it has some stories on storybook

Thanks for reminding me about these, we've been meaning to clean them up a bit 😅 (#52953)

**Comment by bangank36** [comment]
> menu-item

I can see prevous effort of converting menu-item to typescript here https://github.com/WordPress/gutenberg/pull/37020, will keep track on this.
So `menu-group` as the start for amending story 👍 

cc: @mirka for the pending [PR for menu-group story](https://togithub.com/WordPress/gutenberg/pull/53090)

**Comment by bangank36** [comment]
@mirka I submitted the [PR](https://togithub.com/WordPress/gutenberg/pull/53090) and there is `⚠️ Type of PR label error`, which should be adding by the code owner right? Thnks

**Comment by skorasaurus** [comment]
> @mirka I submitted the [PR](https://togithub.com/WordPress/gutenberg/pull/53090) and there is `⚠️ Type of PR label error`, which should be adding by the code owner right? Thnks

I took care of this for you.

**Comment by skorasaurus** [comment]
> @mirka I submitted the [PR](https://togithub.com/WordPress/gutenberg/pull/53090) and there is `⚠️ Type of PR label error`, which should be adding by the code owner right? Thnks

@bangank36 I took care of this for you and added the label to the PR.

**Comment by bangank36** [comment]
> 
> @bangank36 I took care of this for you and added the label to the PR.

I noticed, thank you so much @skorasaurus 🙇

**Comment by mirka** [comment]
FYI our Storybook is very broken right now ☹️ #53502

We'll try to get it fixed as soon as possible.

**Comment by mirka** [comment]
> FYI our Storybook is very broken right now ☹️ #53502

Should be fixed soon by #53520 🎉 

Some related follow-up work is need on #53541

**Comment by bangank36** [comment]
> Should be fixed soon by #53520 🎉

That's great news, then I can contribute to the stories of MenuItem as followed up of the merged PR #53132, ~~WIP~~ Stories can be found on ~~draft~~ PR https://github.com/WordPress/gutenberg/pull/53613
- There is some issue with parsing JSDoc and Types controls on Storybook, I guess it is related to `forwardRef`, working on it...

> Some related follow-up work is need on #53541

Per my understanding, it's the removal of `subcomponents` tab on Storybook V7 that leads to this task?
![image](https://github.com/WordPress/gutenberg/assets/10071857/775561b3-bd4a-4785-9b89-5dd80a537fb3)

I also noticed some ongoing discussions and complains about this feature is removed upon upgrading as well
[developer questions](https://togithub.com/storybookjs/storybook/issues/21253) , [[Feature Request]: Subcomponents support](https://togithub.com/storybookjs/storybook/issues/20782)

Do you think it worth follow the workaround suggestions to bring back the `subcomponents` while waiting for the #53541 to be completed? As I can see some V7 Storybook that support the `subcomponents` eg:
[@psui preview.tsx](https://github.com/x7ddf74479jn5/psui/blob/4e8e850dc5897e698a5da4c8475662a085de77ff/packages/components/.storybook/preview.tsx#L42) / [HoverCard stories](https://x7ddf74479jn5.github.io/psui/?path=/docs/components-hovercard--docs)

**Comment by bangank36** [comment]
@mirka Thanks for your valuable feedback on the recent PRs of MenuItem and Shortcut 🙇 , I'd like to keep contributing to Gutenberg, so far Text has not migrated to type and has no stories, I followed the checklist and I found some notes to get started

> Text (packages/components/src/text) (check truncate behaviors noted in this https://github.com/WordPress/gutenberg/pull/38842#pullrequestreview-888945388, try https://github.com/WordPress/gutenberg/pull/38842#discussion_r816895531 from adjustLineHeightForInnerControls)

**Comment by mirka** [comment]
> I'd like to keep contributing to Gutenberg, so far Text has not migrated to type and has no stories, I followed the checklist and I found some notes to get started
> 
> > Text (packages/components/src/text) (check truncate behaviors noted in this [#38842 (review)](https://github.com/WordPress/gutenberg/pull/38842#pullrequestreview-888945388), try [#38842 (comment)](https://github.com/WordPress/gutenberg/pull/38842#discussion_r816895531) from adjustLineHeightForInnerControls)

@bangank36 Wonderful. Let us know if you have any questions.

**Comment by ciampo** [comment]
Hey @bangank36 , just wanted to note that the `Text` component is being refactored to TypeScript in #54953 — although I'm not sure we'll also look at improving the truncate behaviour (like suggested in the notes that you quoted above).

I can see that a few more components now have stories. In the meantime, we've also [tidied up (and removed) the `ui` folder](https://github.com/WordPress/gutenberg/pull/54922).

What's left to track in this issue?

**Comment by bangank36** [comment]
@ciampo I just updated the tracking table here https://github.com/WordPress/gutenberg/issues/36128#issuecomment-1648975642
On the `Storybook` column there are some leftovers components with no Stories, do you think these worth invest to?

**Comment by ciampo** [comment]
Probably the only component that we could add stories for is `Autocomplete` — every other component listed there is deprecated or discouraged (as it is the case for [dashicons](https://github.com/WordPress/gutenberg/issues/43725)).

Do you have capacity to look into it?

**Comment by bangank36** [comment]
I will look into it if there is no PR currently! @ciampo

**Comment by ciampo** [comment]
> I will look into it if there is no PR currently! @ciampo

Thank you! I'm not sure it's going to be easy to do so, because I vaguely remember the component being quite tightly coupled with other areas of Gutenberg. But please do give it a try and let me know how it goes!

**Comment by mirka** [comment]
Closing this out since we basically have full coverage now, and a story for `Autocomplete` may be impractical. Thank you for all your help @bangank36!
