### ISSUE TITLE
Apply Site Logo placeholder treatment to Featured Image block

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36136]
Recently we enhanced the placeholder for the Site Logo block: https://github.com/WordPress/gutenberg/pull/35397

It would be neat to apply something similar to the Featured Image block as well. We can't quite do a 1:1 replication, as the Featured Image needs to entertain more contexts, which I'll outline below.

### Editing a template – no content

If you simply open something like the Page template in the site editor, you see the raw blocks that compose that template:

<img width="1593" alt="Screenshot 2021-11-02 at 09 40 09" src="https://user-images.githubusercontent.com/846565/139822711-84267691-7ed6-47b6-8341-d388593e85f8.png">

In this context, we can use the Site Logo placeholder appearance (the dashed illustration), but it **should not** be possible to set the featured image. 

### Editing a template – with content – no featured image set

If you edit a page (or post) that has no featured image set in the post editor, then navigate to edit the template via the "Template" panel in the Inspector, you should also see the dashed illustration. However in this scenario it **should** be possible to set the featured image.

### Editing a template – with content – featured image set

If you edit a page (or post) that has a featured image set in the post editor, then navigate to edit the template via the "Template" panel in the Inspector, you should simply see whatever featured image is set on the canvas. Like the Site Logo it should be possible to replace or unset the image.

**Comment by noisysocks** [comment]
Not sure how much work is involved here. If it's easy then let's get it in for WP 5.9. If not then let's drop it from the "Must haves" board and work on it in the plugin.

**Comment by annezazu** [comment]
As part of this effort, it would be neat if the duotone filters applied to the placeholder as well based on the feedback on trying to add the featured image block and a duotone filter in a template in the [eleventh FSE outreach program call for testing: ](https://make.wordpress.org/test/2021/11/08/fse-program-testing-call-11-site-editing-safari/#comment-2218)

>I found it a bit strange adding a featured image block and a duotone filter without seeing what the result would look like.

**Comment by jasmussen** [comment]
PR here: https://github.com/WordPress/gutenberg/pull/36517
