### ISSUE TITLE
Mark post navigation link and term description as non experimental

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#36134]
## What problem does this address?

The term description block was added in march 2021 and has lived an uneventful life without bug reports (in fact, so uneventful that it doesn't even have it's own label).

The post navigation link, _not to be confused with the navigation link block_, was added in February 2021 and has had a few enhancements since then.

It has two open issues, 1 enhancement and one possible bug:
https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BBlock%5D+Post+Navigation+Link%22

## What is your proposed solution?

I'd like both these blocks to be available in WordPress core.

The post navigation link is important for block themes, even if the variations are not used in Twenty Twenty-Two.
Block themes should not need to require Gutenberg to be able to use this feature,

The term description is needed for feature parity with classic themes, but is not as commonly used as the post navigation link.
It is usually paired with the query title, which is not experimental.

**Comment by kjellr** [comment]
I definitely think the post pagination should be marked as stable for 5.9. I'm less concerned about the term description, but mostly because I haven't used it personally. But like you noted, it's been around for a while and nobody's reported issues with it so it's probably fine. 

cc @noisysocks

**Comment by noisysocks** [comment]
Yep, makes sense.
