### ISSUE TITLE
Isolated template part editor: Height doesn't always wrap correctly

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36141]
I noticed when testing with the [Quadrat](https://wordpress.org/themes/quadrat/) theme that the height of the header in the isolated template part editing view is not correct. For some reason it is way too tall:

https://user-images.githubusercontent.com/846565/139853072-7ab7bb6c-4ec3-400b-8ffd-ad851234b45b.mp4

cc @kevin940726

**Comment by kevin940726** [comment]
Yeah, sometimes it's tricky since the height could dynamically change at any time. I'll take a look at this.

**Comment by noisysocks** [comment]
On tall viewports the height of the canvas is always too great. Would be good if we can make the canvas resize down to the intrinsic content size.

**Comment by noisysocks** [comment]
More canvas height weirdness here: https://github.com/WordPress/gutenberg/pull/37213#issuecomment-988661302

**Comment by ntsekouras** [comment]
This issues depend on each theme. For example in `Quadrat` there is this style.

`.editor-styles-wrapper .wp-site-blocks { min-height: 100vh... }` which makes the template part big. Could a simplistic solution of adding some styles like `min-height: auto !important` in the iframe (or by maybe first detecting such cases of vh) be enough? 🤔 

The scrolling issues are related to [this line](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/block-editor/resizable-editor.js#L62) and appear when we have height affecting styles to the root selector, which is the `body`.
