### ISSUE TITLE
Editing properties of a template part while editing a template can lead to confusing / unexpected results

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36143]
Consider the flow: You're editing a template and decide to change your site header a bit. You update the colors and save. I think the expectation here is that those changes would be applied globally to the header. However, that is not the case – those changes are only applied to the header in the context of the template being edited, as can be revealed when you go to edit the header in isolation. This is best illustrated in a short video:

https://user-images.githubusercontent.com/846565/139856589-92dfac00-5771-4408-a1bd-5561434032c5.mp4

Enabling users to override the defaults in the context of the template like this no doubt has its uses, but I'm not sure it would be the expected default behaviour.

**Comment by carolinan** [comment]
I believe this is the same as https://github.com/WordPress/gutenberg/issues/30732?

**Comment by jameskoster** [comment]
Right you are!
