### ISSUE TITLE
Broken default editor stylesheet font families

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#36150]
### Description

The latest Gutenberg release with WordPress 5.8.1 has a broken editor stylesheet, resulting in the highest precedence rule being `font-family: serif;`

<img width="797" alt="Screenshot 2021-11-02 at 15 20 42" src="https://user-images.githubusercontent.com/58855/139876532-5e1f53aa-3959-474e-885e-54eeaf959573.png">

This is caused by `reset.css`:

<img width="713" alt="Screenshot 2021-11-02 at 15 22 14" src="https://user-images.githubusercontent.com/58855/139876721-e4ed91b9-26eb-4b39-a8f3-b06daa09b382.png">

### Step-by-step reproduction instructions

Use Gutenberg 11.8 on WP 5.8.1 with a theme that has no editor styles

### Environment info

- WP 5.8.1
- Gutenberg 11.8
- Google Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi @tomjn ; 

I'm not able to reproduce this on Gutenberg 12.1 and WP 5.8.2; there are now inline rules that take precedence over the reset.css as shown in the image below. (Now, whether Gutenberg should be using so many inline rules, is another opinion :( ) 

I used the popper theme to test this. 

![image](https://user-images.githubusercontent.com/955351/146241225-c81fd2fd-f382-4986-848d-51e67db7aa23.png)

Please reopen if it's still an issue.

**Comment by jeffreyvr** [comment]
Though't I'd comment here, since this is something I'm experiencing too. If you use a an empty theme, with just an style.css (without styling in it) and an empty index.php - you'll get the serif font in the block editor.

I'm wondering whether this is the expected behaviour?

<img width="1079" alt="Screenshot 2022-08-01 at 15 12 44" src="https://user-images.githubusercontent.com/9550079/182155791-24e1d961-7570-4b82-a7e7-63fc5df6766f.png">


```
### wp-core ###

version: 6.0.1
site_language: nl_NL
user_language: nl_NL
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: development
user_count: 1
dotorg_communication: true

### wp-active-theme ###

name: Test (test)
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor
theme_path: /Users/xxxxxxx/Sites/xxxxxxx/wp-content/themes/test
auto_update: Uitgeschakeld

### wp-plugins-active (1) ###

Gutenberg: version: 13.7.3, author: Gutenberg Team, Auto-updates uitgeschakeld

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Niet beschikbaar
imagemagick_version: Niet beschikbaar
imagick_version: Niet beschikbaar
file_uploads: File uploads is turned off
post_max_size: 512M
upload_max_filesize: 512M
max_effective_size: 512 MB
max_file_uploads: 20
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Darwin 21.6.0 arm64
httpd_software: nginx/1.23.0
php_version: 8.1.8 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 512M
max_input_time: 60
upload_max_filesize: 512M
php_post_max_size: 512M
curl_version: 7.84.0 (SecureTransport) OpenSSL/1.1.1q
suhosin: false
imagick_availability: false
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 8.0.27
client_version: mysqlnd 8.1.8
max_allowed_packet: 67108864
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /Users/xxxxxx/Sites/xxxxx/wp-content
WP_PLUGIN_DIR: /Users/xxxxxxx/Sites/xxxxx/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: development
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

```

**Comment by tomjn** [comment]
The behaviour around this is highly inconsistent, so for Frontenberg I gave up and copied over the twentytwentytwo stylesheet to avoid it looking broken so often.

**Comment by rodrigo-arias** [comment]
I had to add a basic theme.json to make it look similar (and not the same) as an empty theme without theme.json

```
{
   "version":2,
   "settings":{
      "appearanceTools":true,
      "layout":{
         "wideSize":"95%"
      }
   },
   "styles":{
      "typography":{
         "fontFamily":"var(--wp--preset--font-family--system-font)",
         "lineHeight":"1.5",
         "fontSize":"18px"
      },
      "spacing":{
         "blockGap":"2rem"
      }
   }
}
```
