### ISSUE TITLE
Changing themes does not immediately invalidate theme editor color cache

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#36152]
## Description
When switching from a block-based theme to a non-block-based theme, the editor will continue displaying the previous themes colors in the editor until refreshed site data is manually fetched. This appears to occur on both iOS and Android. It also occurs in the opposite direction, i.e. block-based theme to non-block-based theme. Possibly related to https://github.com/WordPress/gutenberg/issues/33608. 

## Step-by-step reproduction instructions
1. Open the native editor for a site with a block-based theme. 
2. Note the editor displays the background and text colors for the theme.
3. Change the theme to a non-block-based theme in the mobile app, e.g. Seedlet. 
4. Open the native editor. 

## Expected behaviour
The editor displays the default background and text colors. 

## Actual behaviour
The editor displays the previously selected theme's background and text colors. 

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/438664/139912085-01b109a9-e55a-471c-82a6-87ec5a64aa80.MP4

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: v11.7.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: iPhone SE
- Operating system: iOS 15.1
- WordPress app version: 18.5.0.0 and 17.9.0.4

**Comment by geriux** [comment]
Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4588
