### ISSUE TITLE
Navigation block link popover has a `0` in it after unlinking and relinking

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#36170]
### Description

There's a `0` being shown in the nav block's link UI after a particular sequence of steps. I imagine this is accidentally being returned from a React component instead of `null` or `undefined`.

### Step-by-step reproduction instructions

1. Add a nav block
2. Start empty
3. Add a link
4. Select a URL to a page or post
5. Once done, click the link icon on the toolbar
6. Click the 'unlink' button in the link popover
7. Click on the 'Add link' text
8. Observe the link popover shows with a `0` in the top left corner

### Screenshots, screen recording, code snippet

<img width="396" alt="Screenshot 2021-11-03 at 5 07 31 pm" src="https://user-images.githubusercontent.com/677833/140034691-ca725f05-c698-430d-802b-e56b50f1fc0d.png">

### Environment info

Tested on latest `trunk` at the time of writing.
Tested using Brave on Mac OS.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
If anyone is interested, this is the line that caused the bug:
https://github.com/WordPress/gutenberg/blob/40ff1e5014a823cb4b2aa49d5aa537fb108ed64d/packages/block-editor/src/components/link-control/index.js#L256

You can find details about "why" this is happening in [new React docs](https://beta.reactjs.org/learn/conditional-rendering#logical-and-operator-) (see the "Gotcha" part).

**Comment by amustaque97** [comment]
I would love to take this forward and fix it.
