### ISSUE TITLE
Add a CSS Custom Property for column spacing

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#36184]
## What problem does this address?
As a theme developer, it's not very easy to adjust column spacing in CSS, because of the complexity of spacing and rules at different breakpoints. We usually need to add a series of CSS rules to override core, taking into account multiple breakpoints.

## What is your proposed solution?
It would be so much easier if theme developers could simply change the value of e.g. `--column-spacing-unit` in the theme CSS, instead of trying to override the CSS itself at various breakpoints. The requirement for our themes is usually a simple case of changing `2em` to (e.g.) `1rem`, or to `var(--unit)` (where `--unit` is defined in the theme code or as a custom property in theme.json, and used for various purposes).

**Comment by markhowellsmead** [comment]
I've just come across `--wp--style--block-gap` but this seems to be on a wider scope than just column spacing.

**Comment by carolinan** [comment]
With blockGap enabled in theme.json, you should be able to set a global site wide value but also set a specific value for the columns block.

**Comment by markhowellsmead** [comment]
Thanks @carolinan. It’s also occurred to me that I could alternatively redefine the custom property at block level.
