### ISSUE TITLE
Display the site name in the top bar in Appearance > Editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36207]
Currently the top bar in the Site Editor displays the name of the template being edited, and this works well when you edit a template in isolation (IE via Appearance > Templates). But clicking Appearance > Editor takes you to a unique view where you might be editing template and content all at the same time.

For example: If your site is configured to display a static home page, Appearance > Editor takes you to a view where you're editing whichever template is used to display that page. This could be anything from a Theme supplied "Page" or "Index" template, to a custom template created by the user, with any name. In this view users are _also_ able to edit the contents of that page, so displaying the template name alone in the top bar also feels like a mis-representation.

If your site is configured to display latest posts on the home page instead, then Appearance > Editor will take you to a view where you're editing either the Index or Home template (depending on what your theme supplies). But similar to the static home page scenario, it's also possible to edit the posts themselves in this view as well. So once again, the template name is not an intuitive title for this experience. 

All of this is made worse by the fact that template names like "Index" are not particularly user-friendly! 

<img width="964" alt="Screenshot 2021-11-04 at 10 33 30" src="https://user-images.githubusercontent.com/846565/140299122-ab17512a-a67e-4a28-8c6d-b4d86433eafb.png">

Since we are removing the navigation in the Site Editor for 5.9 (#36194) we can think more critically about what to display in the top bar. 

---

My initial supposition is that it might be better to simply display the site name, or URL in the top bar when you access the site editor via Appearance > Editor. This can also serve as a link to view the frontend, which is a feature folks have been asking for in the Site Editor for a long time:

<img width="954" alt="Screenshot 2021-11-04 at 10 33 38" src="https://user-images.githubusercontent.com/846565/140299576-3a3b3ba0-c12a-481a-b1f9-aa9870aebff2.png">

To clarify, this would only appear when a user clicks Appearance > Editor. If you edit a template via Appearance > Template, then it still makes sense to just display the template name in the top bar.

---

Without wanting to get too far ahead of myself, this could potentially lay the foundation for a way to navigate around content in the Site Editor in the future as well:

<img width="1573" alt="Screenshot 2021-11-04 at 10 44 42" src="https://user-images.githubusercontent.com/846565/140300703-aa2a3bf5-443d-40ad-9ead-466d22e5ee6c.png">

**Comment by carolinan** [comment]
So the entire template details modal is removed?

**Comment by carolinan** [comment]
Then is there a new flow for resetting saved changes to the theme default (the HTML file)?

**Comment by jameskoster** [comment]
The template details would still be present in the Inspector.

> Then is there a new flow for resetting saved changes to the theme default (the HTML file)?

Good catch. This may or may not be a good thing – since in Editor beta you can be editing template and content together, "Reset customizations" could mislead folks in to thinking their content changes would be reset too. 

If we want to keep this flow in Editor beta we may want to add it to the Inspector, something like:

<img width="528" alt="Screenshot 2021-11-05 at 13 56 38" src="https://user-images.githubusercontent.com/846565/140521820-c6f03301-04d3-4685-bfbb-ca0066d21fb5.png">

**Comment by jameskoster** [comment]
Just noting that if we were to do this, we could close out https://github.com/WordPress/gutenberg/issues/35758.

**Comment by annezazu** [comment]
With this closed out https://github.com/WordPress/gutenberg/issues/35758 can we close this issue out too? I am not quite seeing the overlap with current explorations: https://github.com/WordPress/gutenberg/issues/36667

**Comment by jameskoster** [comment]
What to display in the top bar still doesn't feel very clear. Probably fine to close this :)
