### ISSUE TITLE
HOOKS: Naming is unexpected

### ISSUE THREAD

**Issue by tg-ephox** [WordPress/gutenberg#3620]
## Issue Overview

Existing hooks use naming like 'core\anchor-attribute' but the '\a' is a non-existent escape sequence so this is interpreted as 'coreanchor-attribute'.  

I stumbled across this today investigating hooks for use in footnotes and created a hook named 'core\footontes' but '\f' is a valid escape sequence for ASCII character 12 (Line Feed) so my hook name was failing validation [here](https://github.com/WordPress/packages/blob/d62ecb778b95421fda0a069ddc52ac12a5480e73/packages/hooks/src/validateNamespace.js#L16)

Incidently the coment [here](https://github.com/WordPress/packages/blob/d62ecb778b95421fda0a069ddc52ac12a5480e73/packages/hooks/src/validateNamespace.js#L5) wasn't updated when the validation rules changed.

## Possible Solution

Use '-' to delimit hook name.

## Screenshots / Video

![screen shot 2017-11-23 at 3 49 40 pm](https://user-images.githubusercontent.com/30682649/33160235-39f2cfa2-d066-11e7-8224-1f5f94dc4fcc.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by gziolo** [comment]
@aduth pinging you so you were aware why `\a` got replaced with `-` for the hook namespace.

**Comment by aduth** [comment]
I think a better permanent solution is to update the underlying hooks implementation to use `/` for namespacing.

**Comment by gziolo** [comment]
Agreed, we need to relax validation first.
