### ISSUE TITLE
Duotone: Caching breaks duotones set through theme.json

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#36208]
### Description

When a duotone filter is set through theme.json, the SVGs are output to the footer using a side effect of ` gutenberg_render_duotone_filter_preset`. This happens the first time that Global Styles are generated. However, once this has happened the output value is cached. Once the cache is primed, Global Styles aren't generated in the code anymore, which means the side effect of `gutenberg_render_duotone_filter_preset` doesn't happen and the SVGs aren't output. This means that all images with a duotone applied via theme.json disappear.

### Step-by-step reproduction instructions

1. Ensure that your environment doesn't have any of these consts set: https://github.com/WordPress/gutenberg/blob/3e84b5671554281453ea0c635742d6a9e2994351/lib/compat/wordpress-5.9/get-global-styles-and-settings.php#L79
2. Apply a duotone filter to a theme via the theme.json file:

```
			"core/image": {
				"filter": {
					"duotone": "var(--wp--preset--duotone--default-filter)"
				}
			}
```

```
	"settings": {
		"color": {
			"duotone": [
                {
                    "colors": [ "#000", "#B9FB9C" ],
                    "slug": "default-filter",
                    "name": "Default filter"
                }
```
3. On the first load this works fine, on subsequent loads the images break

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ajlende** [comment]
Interestingly, when I set `$can_use_cached = true`, sometimes none of the theme.json styles load. These screenshots are using the skatepark theme.

![Screen Shot 2021-11-04 at 11 38 49](https://user-images.githubusercontent.com/5129775/140365285-ad589e65-f3de-4e8d-bb4b-f685b3e114e2.png)

![Screen Shot 2021-11-04 at 11 39 07](https://user-images.githubusercontent.com/5129775/140365201-5a01e3a8-646e-40ce-bfcb-db58816ade20.png)

EDIT: It seems to happen when I switch from `false` to `true` for a minute or so. It looks like the the `set_transient` call that happens assumes that there is something in the cache already even when it isn't. This can probably be disregarded.
