### ISSUE TITLE
FSE patterns are displayed in user's language instead of site's language

### ISSUE THREAD

**Issue by Chouby** [WordPress/gutenberg#36227]
### Description

Since [WordPress 4.7](https://wordpress.org/news/2016/12/vaughan/), each user can display the backend in its own language, possibly different than the site's main language. When using this feature, FSE patterns are displayed in the user's language instead of the site's main language.  

### Step-by-step reproduction instructions

1. Translate some strings of the theme Twenty Twenty Two, let say in French. I selected "ABOUT US" and "LATEST POSTS", using poedit or equivalent and save the .mo file.
2. Go to Settings > General and select the French language (make sure that in your user profile, the site's default language is selected).
3. Go to the Site Editor
4. Edit the footer template part
5. Select a new footer pattern. I used the "Blog footer" provided by Twenty Twenty Two which comes with the two strings translated at step 1
6. Check that the two strings are correctly displayed in French as expected.
7. Go to your profile and now select English as your user's language.
8. Go back to the Site Editor
9. Clear the footer customizations and edit it again
10. Select the same footer pattern as step 5
11. Check that now the stirings are displayed in English (user's language) instead of French (site's main language).

### Environment info

- WordPress 5.8.1
- Gütenberg 11.8.0
- Twenty Twenty Two development version from GitHub

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Thanks for reporting this issue. It was reviewed in today's Editor Bug Scrub and after review, it appears that everything is working as expected. While it might not be ideal for your situation, user language settings take precedent over site language settings as all REST API requests are fetched in user locale since https://github.com/WordPress/gutenberg/pull/10862.
