### ISSUE TITLE
Post Template returns empty string when no results found

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#36224]
### Description

I expected `index.php` to return `No results found` like `edit.js` does, but it returns an empty string.

https://github.com/WordPress/gutenberg/blob/9a2ae8d1838a41ddf51925d5e9534ca3c7b730d7/packages/block-library/src/post-template/index.php#L39-L41

https://github.com/WordPress/gutenberg/blob/9a2ae8d1838a41ddf51925d5e9534ca3c7b730d7/packages/block-library/src/post-template/edit.js#L143-L145

### Step-by-step reproduction instructions

1. Setup a FSE theme
1. Add a `search.html` template w/ the following:
	```html
	<!-- wp:query {"queryId":1,"query":{"perPage":10,"postType":"any","inherit":true}} -->
		<div class="wp-block-query">
			<!-- wp:post-template -->
				<!-- wp:post-title {"level":5,"isLink":true} /-->

				<!-- wp:post-excerpt /-->
			<!-- /wp:post-template -->
		</div>
	<!-- /wp:query -->
	```
1. Browse to `/?s=supercalifragilisticexpialidocious`

### Environment info

* Gutenberg 18768335e73d32a99e326f3eaa1250372a412b26
* Core 5.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by iandunn** [comment]
Related: #29521

**Comment by iandunn** [comment]
Also related: https://github.com/WordPress/gutenberg/issues/33476

**Comment by ramonjd** [comment]
I think this issue should be part of a bigger drive to make the "no results" state configurable.

Here are two issues that raise this:

- https://github.com/WordPress/gutenberg/issues/36609
- https://github.com/WordPress/gutenberg/issues/27302

I threw up https://github.com/WordPress/gutenberg/pull/38437 in haste, thinking that showing a message on the frontend, one that is consistent with the editor experience, would be a good thing.

But upon reflection I asked myself whether displaying text that isn't editable is something that might irk users, and also go against the spirit of theme editor. Do you think it might be best to wait until we deliver an editable solution?

**Comment by carolinan** [comment]
Can this issue be closed as fixed by https://github.com/WordPress/gutenberg/pull/38806 ?

**Comment by iandunn** [comment]
I think that'll work, thanks!
