### ISSUE TITLE
Investigate broken widgets test - "Should insert content using the global inserter"

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#36240]
Two widgets tests were skipped in #36239. 

It could do with some investigation. Was there a recent change here or in core that could've caused this?

This particular problem has happened previously, but then mysteriously stopped before re-appearing again recently.

cc @kevin940726 @noisysocks

**Comment by kevin940726** [comment]
I can't reproduce this locally after running the tests for several times. I'm starting to think that maybe they are actually just flaky tests, but for some reasons they won't recover after they failed. 🤔

**Comment by talldan** [comment]
Haven't seen this issue in a while, so closing.
