### ISSUE TITLE
RichText: Unable to add a custom highlight color

### ISSUE THREAD

**Issue by WunderBart** [WordPress/gutenberg#36254]
### Description

When trying to highlight text with a custom color, the input doesn't accept any new characters, and when trying to delete any character the popup menu closes. It seems to have been introduced with v11.8.0 as in my testing v11.7.1 works correctly (see demo videos).

### Step-by-step reproduction instructions

1. Write some text into a paragraph block
2. Select a part of this text
3. Open the `Highlight` menu from the rich text toolbar
4. Try to apply custom color via the text input (see demo)
5. See how the current value cannot be changed

### Screenshots, screen recording, code snippet

**Current Gutenberg version v11.8.0 (broken):**

https://user-images.githubusercontent.com/1451471/140508249-256d68db-b754-4c47-ae7e-25e735e99903.mov

**Previous Gutenberg version v11.7.1 (working):**

https://user-images.githubusercontent.com/1451471/140508431-830f6fde-bc06-442c-9c29-fd206aa5a631.mov

### Environment info

- WP 5.8.1
- Gutenberg v11.8.0
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by alshakero** [comment]
Can confirm this is reproducible in trunk.

**Comment by alshakero** [comment]
PR ready https://github.com/WordPress/gutenberg/pull/36263
