### ISSUE TITLE
Add JSON Schema for `.wp-env.json` files

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#36275]
## What problem does this address?

In the same way we now have JSON Schemas for `theme.json` and `block.json` I would love to also have it for the `.wp-env.json` file that is used by the `@wordpress/env` package to control the docker env. 

## What is your proposed solution?

Create a new schema in he `/schema/JSON` directory to host the `.wp-env.json` schema

**Comment by PerryRylance** [comment]
Just arrived here trying to find a schema whilst looking for possibilities to modify the wp-env PHP version - would be really good to have a schema!
