### ISSUE TITLE
When caret is in an empty text block, inserted blocks should replace it

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3627]
Current workflow:

- Type out a bunch of paragraphs
- Make a linebreak between two paragraphs
- Click top inserter to insert an image placeholder
- Result: the image placeholder is inserted after the empty paragraph block the caret was in

Proposed workflow: the image placeholder _replaces_ the empty paragraph block.

This already works when using the slash command.

This is just a small enhancement to make the writing flow in the block editor more closely mimic that of a traditional text editor. 

Possibly related, #3599

**Comment by mtias** [comment]
I agree with this.
