### ISSUE TITLE
Documentation: Generate theme.json metadata documentation from schema file

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#36278]
## What problem does this address?

With the theme.json file now a part of the Gutenberg repository (https://github.com/WordPress/gutenberg/pull/35998) we can take advantage of this file and use it to auto-generate theme.json reference documentation.

The [current theme.json documentation page](https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/themes/theme-json.md) includes a fair amount of explanation on using the theme.json that makes it hard to use as a reference.

## What is your proposed solution?

My proposal is to generate a new API reference document in the [reference-guides section](https://github.com/WordPress/gutenberg/tree/trunk/docs/reference-guides) that includes information from the schema file. This will make it easier when adding new settings and styles, because just the schema would need to be updated and it would self-document the new features.

The current documentation in the how-to-guides section could then be slimmed down and focus on explaining how to use the theme.json and not have to be updated to try and track every change. 

cc: @oandregal - since you've been greatly involved in theme.json (and automated docs)

**Comment by oandregal** [comment]
This would be great to have :) 

Splitting to have a reference doc with all the settings/styles and another explanatory one sounds great.

Whether to have a single reference file per version (theme-json-v1, theme-json-v2, theme-json-next) or having a single one where we mark in which version a given setting/style was added, I don't have a strong opinion about.
