### ISSUE TITLE
Stabilize Navigation Endpoints

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#36287]
The nav endpoints, `/menus`, `/menu-items` and `/menu-locations` are merging into Core for 5.9. The JS looks to still be referencing `__experimental` as the namespace. This needs to be upgraded to `wp/v2`.

**Comment by spacedmonkey** [comment]
Related: https://github.com/WordPress/gutenberg/pull/35846

**Comment by talldan** [comment]
This was addressed in #36368
