### ISSUE TITLE
Allow themes to provide alternate color palettes

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#36304]
Themes should be able to ship with multiple color schemes. For example, a "light" and a "dark" version that users can manually switch between. 

This was generally mentioned in the [Twenty Twenty-Two announcement post](https://make.wordpress.org/core/2021/10/06/introducing-twenty-twenty-two/), and is related to the "Alternate theme.json" idea being explored in https://github.com/WordPress/gutenberg/pull/35619. But it didn't have its own tracking issue until now. 🙂

**Comment by anarieldesign** [comment]
Hi, I couldn't agree more with the @kjellr. For example, if I want to create one theme with different demos, now if I change fonts and typography in the Global Styles and export the demo, import it to the new installation it doesn't import the changes in the Global Styles. So the only way is to use a child theme and this is exactly what I want to avoid or use Customizer for. It would be great if we can somehow export the changes with the demo or have an alternate theme.json and switcher

**Comment by mtias** [comment]
We have this now through the new browse styles panel.
