### ISSUE TITLE
Appearance > Navigation menus:    Visibility and publishing states

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#36309]
### Description

When I go to Appearance > Navigation menus > Edit,
I can select the visibility: Public, password protected, and private.
I can also set it to pending review and draft.

Do these make sense for this post type? Is there anything like draft menu?

_I believe this is not as much a bug, as something that is not implemented yet._

### Step-by-step reproduction instructions

1. Activate Twenty Twenty-Two.
2. Create and save a navigation menu with the navigation block.
3. Go to Appearance > Navigation menus > Edit and open the menu.

### Environment info

WordPress 5.8.1
Gutenberg current trunk
Twenty Twenty-Two.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Agreed, it'd be great to look at potentially removing that status option if it's possible. If not, it might just be something we have to live with for now.

cc @anton-vlasenko

**Comment by anton-vlasenko** [comment]
I've pushed the PR, but the tests are failing. There is something wrong with the trunk branch (other PRs fail too). We may need to wait for the fix.

**Comment by talldan** [comment]
`trunk` should be ok now. Rebasing the branch should get the tests passing.
