### ISSUE TITLE
Strange behavior with page list inside navigation area

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#36306]
### Description

In Twenty Twenty-Two, the goal is to show a working menu on the front, even if the user is on a fresh site.
For that purpose, the page list is used in the navigation block in the header template part.

When trying to combine the page list with the new navigation-area, there is a bug in the site editor.
It is possible to add a page list to a navigation block inside a navigation area, using the old markup:

```
<!-- wp:navigation-area {"area":"primary"} -->
<!-- wp:navigation {"itemsJustification":"right","isResponsive":true} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->
<!-- /wp:navigation-area -->
```

This displays the page list on the front.
In the editor, the page list is not used in the navigation block, but it is visible in the list view.

### Step-by-step reproduction instructions

1. Delete any saved menus and header template parts for Twenty Twenty-Two.
2. Add the code to the header.html template part in Twenty Twenty-Two:
 ```
<!-- wp:navigation-area {"area":"primary"} -->
<!-- wp:navigation {"itemsJustification":"right","isResponsive":true} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->
<!-- /wp:navigation-area -->
```
3. Activate Twenty Twenty-two. View the menu on the front.
4. Open the site editor. Open the list view.
5. Select the navigation block inside the navigation area. See that the page list is not used.
6. Try selecting the page list from the list view.

### Screenshots, screen recording, code snippet

![navigation-area](https://user-images.githubusercontent.com/7422055/140753429-588727e0-39a6-4bd3-9605-22735fde8a6c.gif)

### Environment info

WordPress 5.8.1
Gutenberg current trunk.
Twenty Twenty-Two.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting this. I think it'd be good to still allow markup like you describe so that if the Navigation Area has no assigned menu the block falls back to showing the Page List both in the editor and on the front-end of the site. If there is an assigned menu for an area then it would show that instead. Something must have gone wrong along the way for this not to work.

**Comment by carolinan** [comment]
I believe this issue can be closed since navigation areas are being reverted.
