### ISSUE TITLE
Text Columns: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3630]
To reproduce:
- add a Text Columns block
- by default, there are 2 columns
- click on the sidebar "Block" tab
- click the slider to change the number of columns (or try to change the number in the field)
- the block "crashes" and displays the message "This block has encountered an error and cannot be previewed."
- the sidebar content disappears

Error in the console:
`Uncaught TypeError: Cannot read property 'children' of undefined`

![screen shot 2017-11-23 at 16 49 07](https://user-images.githubusercontent.com/1682452/33181025-080c8560-d06f-11e7-99af-a00d3401c5a1.png)

"

**Comment by mhenrylucero** [comment]
I'm having the same issue.

**Comment by noisysocks** [comment]
This was fixed by #3715.
