### ISSUE TITLE
Appearance > Navigation menus > Edit shows template post attributes

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#36308]
### Description

With a full site editing theme active, and I go to Appearance, Navigation menus and select edit,
there is a meta box called post attributes below publish.
There is an option called Template that lists the available post templates.

### Step-by-step reproduction instructions

1. Activate Twenty Twenty-Two.
2. Create and save a navigation menu with the navigation block.
3. Go to Appearance, Navigation menus and edit the navigation menu.
4. See that it is possible to assign a template to the post type.

### Screenshots, screen recording, code snippet

![Post attribute meta box with a select list where you can select a template](https://user-images.githubusercontent.com/7422055/140758944-be9960c8-c8a4-497a-a91f-1a2eb267f4ed.png)

### Environment info

WordPress 5.8.1.
Current Gutenberg trunk
Twenty Twenty-Two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for flagging this too. Similar to https://github.com/WordPress/gutenberg/issues/36309, I think it'd be good to look at whether this can be refined for 5.9, so adding it to the board.

**Comment by carolinan** [comment]
I tried the following, without success:

1. [remove_post_type_support()](https://developer.wordpress.org/reference/functions/remove_post_type_support/) on _init_. This did nothing, _I was unable to remove any post type support._
2. [remove_meta_box()](https://developer.wordpress.org/reference/functions/remove_meta_box/) This caused a PHP error.
