### ISSUE TITLE
Block attributes: Consider making `type` a required property

### ISSUE THREAD

**Issue by walbo** [WordPress/gutenberg#36319]
## What problem does this address?
Currently block attributes requires either a `type` or an `enum`.

Only adding a `enum` on a attribute causes some issues on SSR blocks. When the attributes is prepared for render they are [validated with `rest_validate_value_from_schema`](https://github.com/WordPress/wordpress-develop/blob/31e92478728c8a95e8e297847699b03842558cd3/src/wp-includes/class-wp-block-type.php#L310). `rest_validate_value_from_schema` requires a `type` to be set. Without it a notice will be thrown because `type` doesn't exist (and a `_doing_it_wrong`).

Ex on block that will fail:
```php
<?php
register_block_type(
    'core/example',
    array(
        'attributes' => array(
            'value' => array(
                'enum' => array( 'ok', false ),
            ),
        ),
        'render_callback' => function( $block_attributes ) {
            return $block_attributes['value'];
        },
    )
);
```

Not sure there is any use cases where you can't set a `type`. The example above would be solved by adding `type => array( 'string', 'boolean' )`.

## What is your proposed solution?
In attributes make `type` required.

**Comment by gziolo** [comment]
I opened https://github.com/WordPress/gutenberg/pull/36351 that marks `type` as required. It also improves validation for the `enum` field.
