### ISSUE TITLE
ColorPicker enableAlpha=true breakes after alpha set to 100%

### ISSUE THREAD

**Issue by franmastromarino** [WordPress/gutenberg#36314]
### Description

Hello
We find this issue in the new colorpicker component

1. Create ColorPicker with enableAlpha=true
2. Set alpha to 100%
3. Change color

### Step-by-step reproduction instructions

1. Create ColorPicker with enableAlpha=true
2. Set alpha to 100%
3. Change color

### Screenshots, screen recording, code snippet

https://snipboard.io/qThJyr.jpg
https://gyazo.com/8ae83f32f30a6c1c70eb4b59090587ca

### Environment info

WordPress version: 5.8.2
Gutenberg version: 11.8.1
Are all plugins except Gutenberg deactivated? Yes
Are you using a default theme (e.g. Twenty Twenty-One)? No

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mirka** [comment]
Fixed in #36941
