### ISSUE TITLE
Support block patterns in post type templates

### ISSUE THREAD

**Issue by ethanclevenger91** [WordPress/gutenberg#36323]
## What problem does this address?
Registered block patterns can't subsequently be referenced within the `template` argument passed to `register_post_type`:

```
register_block_pattern('namespace/block-pattern-name', [
	'title' => 'My Block Pattern',
	'content' => '<!-- ... -->',
]);

// ...

register_post_type( 'my-post-type', [
	'template' => [
		[
			'namespace/block-pattern-name',
		],
	],
) );
```

And due to #33379, this means you have to maintain both the HTML string version of a block pattern to use in `register_block_pattern` so it can be inserted on-demand, plus a PHP array version of the block pattern for use in a template default. Not very DRY.

## What is your proposed solution?
Support block pattern names within the `template` arg of `register_post_type`.

It's possible I'm simply "doing it wrong", but I do not see documentation suggesting this is or isn't currently supported.

**Comment by talldan** [comment]
@ethanclevenger91 I don't think it has been historically supported. There is a new block type called the pattern block, so an option would be to use this in a template and make that block reference a specific pattern.

There's a very similar request here - #21830. I'm going to close this issue as a duplicate and leave more detailed feedback on #21830.
