### ISSUE TITLE
Site editor toolbar positioning underneath blocks can make it difficult to edit some blocks

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#36335]
### Description

The toolbar positioning in this image makes it very hard to edit some overlapped items in the navigation block's submenu:
<img width="631" alt="Screenshot 2021-11-09 at 10 56 13 am" src="https://user-images.githubusercontent.com/677833/140853923-a16bb257-24dc-4760-b7f1-b3b9338cef0f.png">

I imagine this situation could also happen with other blocks that break out of their container

### Step-by-step reproduction instructions

1. Add a navigation block somewhere near the top of the site editor so that the toolbar positions below the block
2. Add a submenu to the navigation block (Start Empty > Add a link > Convert the link to a submenu using the toolbar button)
3. Try editing the submenu.

### Environment info

Reproduced using the Brave Browser on Mac OS.

Latest Gutenberg `trunk`.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by noisysocks** [comment]
Confirmed this is still an issue when running WP 5.9 with and without the Gutenberg plugin.

**Comment by noisysocks** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/36977.
