### ISSUE TITLE
Highlight the template that displays the site home and posts pages

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36348]
In wp-admin, the Pages list marks which pages are used for certain purposes, IE the front (home) page, the posts page, the privacy policy page, and so on:

<img width="516" alt="Screenshot 2021-11-09 at 09 41 45" src="https://user-images.githubusercontent.com/846565/140900437-d128c8d7-09e5-4725-b026-5c15d00b3e23.png">

It would be helpful to mark templates the same way, and allow plugins to extend that functionality (note how WooCommerce marks the shop page, account page, and checkout page above).

We could use the same visual treatment, but since templates can resolve for many pages, the appearance can get a bit cluttered:

<img width="566" alt="Screenshot 2021-11-09 at 09 55 43" src="https://user-images.githubusercontent.com/846565/140902594-86305eaf-d0ed-44e5-8ba2-a5d5bc755135.png">

Another option would be to extend the description, or add a "Notable pages" (or similar) column.

**Comment by StefanXhunga** [comment]
Thank you for your assistance!

**Comment by jameskoster** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/36612.
