### ISSUE TITLE
Block inserter - never ending scrolling with Gutenberg >=11.4 and Genesis theme framework

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#36349]
### Description

When attempting to insert a Dynamic Content Block ( oik/content-block ) into a post I typed `/con`. The block inserter started populating with blocks then a while later the list started getting ever larger.

It was trying to display "Media and text in a full height container".
Here's a screen capture taken before the window started getting larger and larger.
Note: In order to get this screen capture I pressed the pause button in the Chrome Dev tools Sources tab.

![image](https://user-images.githubusercontent.com/2474435/140607901-1b866ff1-b91f-4a25-83ee-a9ee476d5b0a.png)

A short while later it looked like this
![image](https://user-images.githubusercontent.com/2474435/140607960-c7bfd51f-6fbd-47d5-850e-a78064a7b335.png)

A similar result was obtained for typing `on` into the main block inserter.
![image](https://user-images.githubusercontent.com/2474435/140607338-dc153dac-aafa-4ef2-ac67-0be8c34bd7c3.png)

The problem occurs when attempting to display the "Large header with text and a button block" pattern

The problem is related to the Genesis Framework. It occurs for Gutenberg 11.4.0 and higher. I'm using Genesis 3.3.5.

I asked a question on both Make WordPress slack `#core-editor` channel
https://wordpress.slack.com/archives/C02QB2JS7/p1636205307021200
 and  Genesis WP `#gutenberg` channel.
https://genesiswp.slack.com/archives/CAKLFDJ5A/p1636207731019100

> Hi, I've got a problem associated with the Genesis theme framework and Gutenberg 11.4.0 and higher. When using this combination of theme and plugin the block inserter produces an ever growing box for block patterns such as "Media and text in a full height container" ( just type m in the block inserter ) or "Large header with text and a button block" ( type on ). I don't really know where to start looking for the cause of the problem.

> Can someone reproduce this?

@paaljoachim suggested I raise this issue. 
Nobody replied to my questions hence this issue. 

### Step-by-step reproduction instructions

1. Install and activate Genesis or a Genesis child theme
2. Install and activate Gutenberg 11.4.0 or higher
3. In the block editor click on the block inserter icon
4. Type `me` or `con` for **Media and text in a full height container**   or `on` for "Large header with text and a button block"
5. See the Patterns section of the inserter grow for the above block patterns. 

### Environment info

- WordPress 5.8.1
- Gutenberg 11.4.0 and above
- Genesis theme framework v3.3.5
- Windows 10
- Chrome and Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bobbingwide** [comment]
Looking at both of the block patterns when loaded into the editor it would appear that the common denominator is  the style of the background image `min-height:100vh`. 

I reproduced this by creating my own block pattern that features this CSS.
It's just a simple cover block. 
```
<!-- wp:cover {"overlayColor":"vivid-red","minHeight":100,"minHeightUnit":"vh"} -->
<div class="wp-block-cover" style="min-height:100vh"><span aria-hidden="true" class="has-vivid-red-background-color has-background-dim-100 wp-block-cover__gradient-background has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
    <p class="has-text-align-center has-large-font-size">Issue #39</p>
    <!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->
```

Changing the `minHeight` to `99` resolved the ever growing problem in the inserter.
So did using a different unit: eg `px`

**Comment by annezazu** [comment]
This feels like the same bug as previously reported here: https://github.com/WordPress/gutenberg/issues/34729 

Going to close this out as a result but let me know if this issue doesn't match what you've found!

**Comment by bobbingwide** [comment]
> This feels like the same bug as previously reported

Agreed. Can someone chase the review of the PR that fixes this. https://github.com/WordPress/gutenberg/pull/35841
