### ISSUE TITLE
Move Theme Editor to Tools when a block theme is active

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36354]
Once the designs proposed in https://github.com/WordPress/gutenberg/issues/29630 are implemented, we're going to have two fairly similar menu items under Appearance:

* Editor (beta) – This is where you go to visually customise your home page and styles in the "Site Editor".
* Theme Editor – This is a code editor for theme files

In many ways, the Site Editor will become a safer, more visual, user friendly version of the Theme Editor over time. There may still be a need for a code editor, but it will be a more advanced feature for power users.

Therefore it may make sense to de-emphasise the Theme Editor. This eases any confusion between "Editor" and "Theme Editor" in the Appearance menu, and puts an advanced further out of reach for less technical users.

One suggestion in 29630 was to move it to the Tools menu, which I think is a decent idea:

<img width="1251" alt="Screenshot 2021-11-09 at 16 02 10" src="https://user-images.githubusercontent.com/846565/140959684-03b62dd6-35fd-4ad9-88f2-cdfb3818d6cd.png">

Any other thoughts / suggestions?

**Comment by carolinan** [comment]
I created [a Trac ticket ](https://core.trac.wordpress.org/ticket/54382)for this 5 days ago, and it has two simple patches, one that moves the theme editor menu item, and one that moves both the theme editor and the plugin editor menu item, as suggested in ticket.

I do not think that this should be solved by making changes to Gutenberg.
I also do not think it is a good idea to have them in two places depending on what type of theme is active.
I believe that always having the menu items in the same location makes them easier to use.

**Comment by carlomanf** [comment]
I did suggest moving both editors as Carolina mentioned, but then I tried out the latest implementation and changed my mind. What I noticed is the Templates item is now the primary way of navigating between templates, and the Editor item is nothing more than a shortcut to the default template. I now think it would be clearer to remove the new Editor item altogether and just rely on Templates, allowing the old Theme Editor to stay where it is.

**Comment by carolinan** [comment]
Hmm yes that is worth considering in my opinion.

**Comment by jameskoster** [comment]
> Editor item is nothing more than a shortcut to the default template

That's not _quite_ true. If you have a static home page set, then the Editor will load that template with the relevant page content in situ, enabling you to edit both at the same time. This lays the foundation for the broader "Site Editor" ambition where you're able to edit all aspects of your site at the same time.

There are also issues like #36207 that will help make the Editor feel more like a holistic "Site editor" for 5.9. As we make these changes and add more features like browse mode, inline content creation, site setting management, etc, I suspect we'll see a divergence between the Site Editor and the Template Editor. The latter being the place you go to edit templates absent of any content.

**Comment by carlomanf** [comment]
> If you have a static home page set, then the Editor will load that template with the relevant page content in situ, enabling you to edit both at the same time.

Thanks for the clarification. If content editing facilities are present, then wouldn't it be more appropriate for it to be elsewhere than Appearance?

**Comment by jameskoster** [comment]
I'm not sure there is an appropriate section currently since this idea of cross-context editing doesn't really exist in WP just yet. 

When the experience is much richer (you're able to navigate to different content/templates, edit site settings, etc – hopefully for 6.0) we might consider elevating it to the top level. But for now editing style and template feels very theme-oriented, so the Appearance section probably makes the most sense.

**Comment by carlomanf** [comment]
> this idea of cross-context editing doesn't really exist in WP just yet.

It appears you can say that again, because I notice that the Post Content block is not editable. I know it was editable in a previous version, so maybe this feature was removed, or maybe it's a problem on my end?

**Comment by jameskoster** [comment]
I think it depends. Post Content in a query can't be edited, but Post Content in a page can be.

**Comment by carlomanf** [comment]
I wasn't able to edit post content even outside of a query loop.

**Comment by jameskoster** [comment]
Interesting, it's working fine for me with multiple themes. That may be worth a dedicated ticket if you have the time?
