### ISSUE TITLE
Add shortcuts to access the pattern explorer

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36350]
The [Pattern Explorer](https://github.com/WordPress/gutenberg/pull/35773) is a powerful feature. We might consider adding shortcuts to make accessing it a bit easier.

One obvious option would be a keyboard shortcut. Another would be to surface it in the quick inserter:

<img width="669" alt="Screenshot 2021-11-09 at 10 14 16" src="https://user-images.githubusercontent.com/846565/140905588-a0b93c5b-fc66-4f8e-89fc-7371c3c6434b.png">

**Comment by annezazu** [comment]
Another shortcut to add would be in the quick inserter based on the feedback from the [eleventh call for testing for the FSE Outreach Program:](https://make.wordpress.org/test/2021/11/08/fse-program-testing-call-11-site-editing-safari/#comment-2218)

>Actually adding a pattern could be the same as adding a block through the Quick Inserter. Only one would see smaller thumbnails of patterns. Clicking Browse all would open the bigger inserter and have patterns tab selected.

Currently, when you search for patterns in the quick inserter you come up empty:

<img width="433" alt="Screen Shot 2021-11-15 at 8 17 53 PM" src="https://user-images.githubusercontent.com/26996883/141878268-e2b5f05a-a87d-4478-a02a-29dadcaf7ad0.png">

Instead, you could have something like this showing a few options or the most recently used patterns with a nudge to browse all that took you to the pattern explorer:

<img width="567" alt="Screen Shot 2021-11-15 at 8 21 47 PM" src="https://user-images.githubusercontent.com/26996883/141878525-f77e67ca-9649-42eb-9a30-28aba91a4bf9.png">

**Comment by paaljoachim** [comment]
One could actually take it a few steps further.
User begins to write "pattern headers" and sees various thumbnails show up. Perhaps even scrolling the area. Browse all would be fixed in the bottom, so the user can at any time click the Browse all button. The text could perhaps also change to say "Browse all patterns" This means having the text change depending on the context of the search.

**Comment by jameskoster** [comment]
These are interesting ideas, but I do wonder how frequently "pattern" comes up as a _search_ term in these interfaces. It seems a little unnatural – kind of like searching for "block".

**Comment by mtias** [comment]
Related #36697.

**Comment by nebulousGirl** [comment]
Why not make a pattern show up when its name is entered in the search?

**Comment by ehausen** [comment]
How about at least make it possible to open it programatically? 

Similar to have already can open the left side inserter panel:  
`wp.data.dispatch('core/edit-post').setIsInserterOpened(true);`

(Or is there a way to do it already?)

**Comment by ehausen** [comment]
To clarify, I was thinking about adding a button right in the toolbar to directly open the Pattern Explorer modal, but wasn't skilled enough to figure out how to trigger the opening of the modal. 

If anyone could suggest a code snippet that makes the Pattern Explorer popup (without the Inserter sidebar), I would be grateful.

I'm thinking that encouraging to use Pattern Explorer would be better for non tech savvy people and ideally could skip opening the Inserter sidebar that has all kinds of scary stuff and clutter.

**Comment by jameskoster** [comment]
@ehausen I think there is some overlap between your idea and the work going on in https://github.com/WordPress/gutenberg/pull/41156.

**Comment by annezazu** [comment]
Ended up opening a separate issue for discussion around being able to search for "Patterns" in the quick inserter: https://github.com/WordPress/gutenberg/issues/42343

**Comment by youknowriad** [comment]
Found this issue while doing a triage session. It seems the command palette is the logical place for this kind of features these days.

**Comment by jameskoster** [comment]
Agreed, let's close this one.
