### ISSUE TITLE
Color naming conflict for theme variables

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/gutenberg#36360]
### Description

As I was running through testing of [FSE Program Testing Call #11: Site Editing Safari](https://make.wordpress.org/test/2021/11/08/fse-program-testing-call-11-site-editing-safari/) I noticed an odd behavior with Global Styles custom colors. 

I'm running `WP 5.8.2-RC1-51987` using [Beta Tester plugin](https://wordpress.org/plugins/wordpress-beta-tester/), and using [Gutenberg 11.9 RC3](https://github.com/WordPress/gutenberg/releases/tag/v11.9.0-rc.3) with [TT1 Blocks theme](https://wordpress.org/themes/tt1-blocks/).

Here are the steps to recreate:

1. Choose Appearance > Styles and choose Colors
2. Under 'Palette' click on the '0 colors' to create a new custom palette
3. Use + (plus) icon to add a new color
4. Choose any color in the picker and type 'green' in the field. As soon as you complete 'green' the background of the page changes. There seems to be a CSS Custom Property name that is being overwritten.

While technically, this may make sense and _may_ even be the intended outcome. However, from a user perceptive it is not ideal and the behavior is unexpected.

This likely would involve more mature APIs for colors, and still being discussed in: [Default Colors, Theme Colors, and Custom Colors #29568](https://github.com/WordPress/gutenberg/issues/29568). Also, it would be ideal to do some validation or checking to make sure color naming does not conflict.

### Step-by-step reproduction instructions

(noted above)

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/405912/140997846-9b050f71-1c5a-4813-839f-d059aa829a41.mp4

### Environment info

- `WP 5.8.2-RC1-51987` using [Beta Tester plugin](https://wordpress.org/plugins/wordpress-beta-tester/), and using [Gutenberg 11.9 RC3](https://github.com/WordPress/gutenberg/releases/tag/v11.9.0-rc.3) with [TT1 Blocks theme](https://wordpress.org/themes/tt1-blocks/).
- Chrome 95.0.4638.69
- macOS 11.6

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by oandregal** [comment]
Thanks for reporting.

This should be resolved by https://github.com/WordPress/gutenberg/pull/36674 which added a `custom-` prefix to any user-provided color to fix this use case, so there's no conflicts with theme or default colors.
