### ISSUE TITLE
Edit Link functionality hidden by WP Admin left menu in Paragraph block

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/gutenberg#3637]
## Issue Overview
The leftmost edge of the Link modal within the Paragraph block appears behind the WP Admin left menu when clicking on text on the leftmost edge of the Paragraph block.

## Steps to Reproduce (for bugs)
1. Cloned a previous Gutenberg post.
2. Clicked on link text within an existing Paragraph block in attempts to edit the URL.
3. Unable to see the Edit icon.
Tested on macOS 10.13.1 using Firefox 57.0 (20171112125346) on the Make/Core WordPress install.

## Expected Behavior
The Link modal should appear fully within the editing area so that link details can easily be edited.

## Current Behavior
The Link modal appears hidden behind the WP Admin left menu and makes it difficult to edit the link details.

## Possible Solution
The Link modal could have its leftmost boundary set a certain number of pixels past the rightmost edge of the WP Admin left menu.

## Screenshots / Video
<img width="933" alt="image" src="https://user-images.githubusercontent.com/2818133/33187836-56d13e12-d05a-11e7-8edc-1385cf36dc58.png">

**Comment by hedgefield** [comment]
I would just keep the modal in the same place regardless of which word you are linking, like the permalink modal (but still below the block).

<img width="674" alt="screen shot 2017-11-24 at 12 53 43" src="https://user-images.githubusercontent.com/6073772/33209521-83cdfbbe-d116-11e7-89b6-ab049b3ba584.png">

**Comment by karmatosed** [comment]
I am going to link this to #4209 and close. There are a few issues with the link overlay we should consider.

@hedgefield I think we're at a crossroads with what we do, should the link be contextual or should it be consistently placed. I'd like us to explore what other designs do and ponder that approach in the linked issue.
