### ISSUE TITLE
"Paragraph" icon in Site Title level dropdown grows comically large on Firefox

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#36389]
### Description

When the "Paragraph" option of the heading level dropdown of the Site Title block is selected, the icon in the toolbar grows once the block is unselected and reselected. Sometimes it grows even bigger upon further deselection and reselection, leading to comical results. This bug occurs in Firefox, but not Chromium.

### Step-by-step reproduction instructions

1. Use Mozilla Firefox.
2. Insert a Site Title block.
3. Open the "Change heading level" dropdown.
4. Select "Paragraph".
5. Deselect the block.
6. Re-select the block.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/19592990/141228045-5f465354-fb7f-43e1-9ed2-9f7e959d5244.png)

![image](https://user-images.githubusercontent.com/19592990/141227627-3c93c5c4-32cb-4c99-b417-129771804eca.png)

### Environment info

Mozilla Firefox 94. WordPress 5.8.2 and Gutenberg 11.9.0. Twenty Twenty-One theme.

Also happens with latest Gutenberg `trunk` as of when this issue was created.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @ZebulanStanphill

I cannot reproduce the issue on the current trunk — testing with the TwentyTwentyTwo theme and Chrome browser.

**Comment by ZebulanStanphill** [comment]
@Mamaduka Ah, it looks like it only happens in Firefox. I can't reproduce it in Chromium. (Tested with Twenty Twenty-One.) I'll update this issue title/description to reflect that.

**Comment by ellatrix** [comment]
<img width="834" alt="Screenshot 2023-08-16 at 15 16 23" src="https://github.com/WordPress/gutenberg/assets/4710635/c2810d68-a692-4c08-b26b-57d1c23a68dc">

Seems to be fixed. I deselected and reselected, and it's looking fine. I'll close but please reopen if it's still an issue.
