### ISSUE TITLE
Gallery move items arrows disappear

### ISSUE THREAD

**Issue by jcoonrod** [WordPress/gutenberg#36383]
### Description

When a gallery block has more than 4 columns, the arrows for moving items does not show.

### Step-by-step reproduction instructions

1. Insert a Gallery block
2. specify a larger number of columns than 4, like 8.
3. Upload more than 8 images
4. Click on the image - normally < > arrows appear to move blocks but when the image is too narrow they do not appear. 
![Screenshot 2021-11-10 3 55 36 PM](https://user-images.githubusercontent.com/54367582/141192915-87c62e50-1f52-4969-b031-9cd310e9917a.png)
 

### Environment info

- Wordpress 5.8.1 using the built-in Gutenberg blocks using Edin theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@jcoonrod thanks for opening this issue! The Gallery Block has been refactored ahead of the 5.9 release and is available now using Gutenberg 11.9. I tried testing with this version and found the move items are still there, even after adding 8 columns:

<img width="796" alt="Screen Shot 2021-11-12 at 2 25 15 PM" src="https://user-images.githubusercontent.com/26996883/141523556-2426d027-4b45-48f6-a8f1-8a3a3187e2ca.png">

Closing this out as a result but you're welcome to ask for it to be reopened if you believe this is a mistake!
