### ISSUE TITLE
5.9 Alpha: WordPress admin footer is visible in the site editor footer

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#36395]
### Description

Please guide me if this is not the correct place to report this, then I can open a Trac ticket.

With WordPress trunk, (now at 5.9-alpha-51272-src),
at a browser window width above 782px, the WordPress admin footer is visible in the site editor.

### Step-by-step reproduction instructions

1. Using WordPress trunk, activate a full site editing theme like Twenty Twenty-Two.
2. Go to the appearance > editor(beta)
3. View the footer of the editor, and see the text.
( If a block is selected, the texts may also overlap because the breadcrumbs are also visible.)

### Screenshots, screen recording, code snippet

![Site Editor footer and WordPress admin footer text overlapping](https://user-images.githubusercontent.com/7422055/141265545-e43205cf-5ec2-4e69-91be-d536c78d555d.png)

### Environment info

WordPress trunk, (now at 5.9-alpha-51272-src) (this is not the nightly via the beta tester plugin, but pulled from wordpress-develop repository.)
Gutenberg is not active.
Twenty Twenty-Two.
PC, Windows10, Chrome.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Update, if I activate Gutenberg, current trunk, the WordPress admin footer is not visible in the site editor.

**Comment by Mamaduka** [comment]
I think this was fixed via #36390.

**Comment by annezazu** [comment]
I think @Mamaduka is right :) Going to close this out for now. Feel free to re-open.
