### ISSUE TITLE
Unable to remove block-templates support using remove_theme_support

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#36396]
### Description

`remove_theme_support('block-templates');` (applied using the `after_setup_theme` hook with priority 20) doesn't appear to work when the plugin (v11.9.0) is in use.

### Step-by-step reproduction instructions

1. Add the following code to the theme or a plugin
2. The template selector is still visible on the edit post screen.

### Screenshots, screen recording, code snippet

```
add_action('after_setup_theme', 'sht_remove_block_template_support', 20);

function sht_remove_block_template_support() {
	remove_theme_support('block-templates');
}
```

### Environment info

- WordPress 5.8.1
- Gutenberg 11.9.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
If your theme has a a theme.json file then this is intentional.

**Comment by annezazu** [comment]
@markhowellsmead  can you confirm what theme you are using?

**Comment by markhowellsmead** [comment]
My own theme.

**Comment by annezazu** [comment]
Got it! Do you have a theme.json file? Just want to get explicit to follow up on what Carolina said above :)

**Comment by markhowellsmead** [comment]
I do, yes. I’d hoped that I could continue to use theme.json without FSE, as I have done for projects built with 5.8, but this seems to be impossible. A shame.

**Comment by carolinan** [comment]
As far as I know, this did not change. Since 5.8, adding a theme.json has enabled the Template selector in the block editor.
https://make.wordpress.org/core/2021/06/25/introducing-theme-json-in-wordpress-5-8/

Maybe the issue would be helped by a longer description of the use case, an explanation to why this change is needed.

**Comment by markhowellsmead** [comment]
The use case is to allow the deactivation of block templates from the WordPress directory on sites where the layouts need to be more strictly managed. The users on these sites shouldn't be given the opportunity to import a block pattern from the Block Pattern Directory, as many of the patterns there wildly conflict with the layouts which conform to the CI/CD of the company/site.

**Comment by carolinan** [comment]
@markhowellsmead Block patterns and templates are separate, no templates can be imported from the WordPress directory.

To prevent block patterns from the directory, you can use:
`add_filter( 'should_load_remote_block_patterns', '__return_false' );
`
(From WP 5.8.0)

**Comment by markhowellsmead** [comment]
Ah, great. Thanks @carolinan. https://github.com/WordPress/gutenberg/issues/33500 seems to be the better place to track what this issue was originally about.
