### ISSUE TITLE
Missing ability to remove/override "Core" color palette

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#36407]
### Description

In the original tracking issue from Matias (#29568) it was outlined that

> Of course, it still needs to be possible to fully disable the default palette since sites that have stricter branding guidelines might prefer to remove it entirely, the same way the custom colors interface can be disabled, but it should not be the default behaviour that a theme palette overwrites the color palette.

Looking at the implementation now that does not seem to be the case. 

This is a big problem for custom builds with strict design systems where the litigation to certain brand colors is a very important need that is no longer met without the ability to remove / override that "Core" palette. 

I do understand and agree that the default behavior should be having both paletes. But like @mtias mentioned initially then this was proposed themes should be able to override / remove that. 

### Step-by-step reproduction instructions

There are no steps to reproduce as there is no API to remove the Core palette. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by fabiankaegy** [comment]
I would consider this to be a Bug that should be included in the WordPress 5.9 must-haves as it impacts Agencies and Custom builds very heavily. But of course I am biased that way because I am advocating for the Agency side. :)

**Comment by fabiankaegy** [comment]
My proposed solution for it would be introducing a new key to the `settings.color` object in `theme.json` for `corePalette` and `coreGradients` that could then either be overwritten or set to an empty array to remove it completely. 


```json
{
    "version": 1,
    "settings": {
        "color": {
            "corePalette": [],
            "coreGradients": []
        }
    }
}
```

**Comment by fabiankaegy** [comment]
To add some more context here. When you set the `settings.color.palette` to an empty array some of the blocks hide the Color options altogether. Which I think is the right behavior. But not all blocks adhere to that pattern. The `Sepperator` and the `Navigation` block for example do still show the color panel in the settings sidebar and just only show the Core palette. 

As soon as you add any colors to the `settings.color.palette` array all the blocks now consistently show the Color panel with both the Core and the Theme palette. 

And there does not seem to be a way in which you can remove or override the Core palette.

**Comment by ndiego** [comment]
100% agreed, there needs to be a way to remove the core palette and only display the palette provided by the theme. Perhaps something like the following in theme json. 

```
{
    "settings": {
        "color": {
            "palette": {
                "core": [],
                "theme": [
                    {
                        "slug": "foreground",
                        "color": "#000000",
                        "name": "Foreground"
                    },
                    ...
                ]
            }
        }
    }
}
```

Or maybe:

```
{
    "settings": {
        "color": {
            "palette": {
                "coreColors": "false",
                "theme": [
                    {
                        "slug": "foreground",
                        "color": "#000000",
                        "name": "Foreground"
                    },
                    ...
                ]
            }
        }
    }
}
```

**Comment by fabiankaegy** [comment]
I tried some other options that may not be as nice to use but would still function but somehow even filtering the `block_editor_settings_all` hook doesn't remove the Core palette. I'm not sure why it still shows but it must be coming in somewhere after the `block_editor_settings_all` hook is called. 

```php
add_filter(
	'block_editor_settings_all',
	'remove_core_color_palette'
);

/**
 * Remove the "Core" Color Palette in the editor settings
 *
 * @param array $settings block editor settings
 */
function remove_core_color_palette( $settings ) {
	$settings['__experimentalFeatures']['color']['palette']['core'] = [];

	return $settings;
}
```

**Comment by annezazu** [comment]
@oandregal tagging you into this :) Thank you all for kicking this off and flagging this so clearly.

**Comment by fabiankaegy** [comment]
I'm curious why the `block_editor_settings_all ` filter no longer gets applied here: https://github.com/WordPress/gutenberg/blob/b49b215f7b5682f61b42058349095449e089d17a/lib/global-styles.php#L109

The `WP_Theme_JSON_Resolver_Gutenberg::get_merged_data` function combines the raw data from the `theme.json` so there is no way of filtering it anymore.
https://github.com/WordPress/gutenberg/blob/b49b215f7b5682f61b42058349095449e089d17a/lib/class-wp-theme-json-resolver-gutenberg.php#L281-L291

From my perspective of course an API in `theme.json` like mentioned here: https://github.com/WordPress/gutenberg/issues/36407#issuecomment-966311088
https://github.com/WordPress/gutenberg/issues/36407#issuecomment-966359675
would be very cool. 

But the ability to filter the final merged `theme.json` settings before they get passed to the JS side would be a massive win because it would allow us to filter out the core palete. :)

**Comment by oandregal** [comment]
:wave: oh, thanks for bringing this up, we need to fix it for 5.9. Following Fabian's suggestion, I think we could do:

```json
{
    "version": 2,
    "settings": {
        "color": {
            "corePalette": "true/false",
            "coreGradients": "true/false"
        }
    }
}
```

This is, we allow themes to opt-out from the core solids & gradients but themes can't override the core colors. As I see it, the value of core colors is to provide a cross-theme palette that doesn't change.

@fabiankaegy (or anyone else) would you be interested in taking this one for yourself?

**Comment by fabiankaegy** [comment]
@oandregal That sounds great (y) and yes I do also think that it should be a boolean value and that you shouldn't be able to override the values of the core palette. I only mentioned it since it was in Matiases original comment :) 

As far as taking it my main goal for it is that it can make the 5.9 deadline and I am not 100% certain I have a full grasp of everything that is needed in order to get this done. 

Would it be a _simple_ addition here: https://github.com/WordPress/gutenberg/blob/ee398e050178133193febac5fb1bbcc33e79f50b/lib/global-styles.php#L164 that checks for the two values in the theme provided `theme.json` to then override the values of the core defaults?

**Comment by fabiankaegy** [comment]
I started a draft PR but I am not jet confident I know where exactly to place the setting. I've been looking at #36246 as an inspiration but I am having the fundamental issue that this needs to execute after the two JSON files are merged.

**Comment by ellenbauer** [comment]
I'm a bit late here but I just want to thank you @fabiankaegy to take the initiative here since having the core color palettes everywhere in the editor is just a super confusion user experience and not needed at all. So I'm very very happy if we can get this updated asap.

**Comment by steveangstrom** [comment]
I consider this to be a very serious show stopping bug.
I do not want my clients to see the "core" palette in any case.

Its important that the removal of core palettes is available from the PHP action too. Please don't assume that everyone is jumping into the json theming method on established sites

**Comment by paulwilde** [comment]
Does this change happen to also remove all the inline styles that automatically get output on every page of the frontend? Might be something to consider if it doesn't disabled those as they just add to the pagesize with no way to disable them (from what I could find).

<img width="819" alt="Screenshot 2021-11-15 at 1 03 43 pm" src="https://user-images.githubusercontent.com/704594/141786721-8da9fdef-f48a-4d1c-a6f4-21de95add4cd.png">

**Comment by fabiankaegy** [comment]
@paulwilde No this would not remove these classes. The reason for this is, that the Core palette is only removed from the Editor view so editors are not able to select from the Core palette anymore. 

However, the reason why the actual classes don't get removed is that if a block pattern from the core pattern library gets inserted it expects the core palette to be available. Editors could then change the color of that pattern to one of the theme colors. 

I can see how this is something that one may want to remove altogether. But that should be a separate issue that I think is important but not a 5.9 blocker.

**Comment by steveangstrom** [comment]
Was this tested with PHP themes before being closed?

PHP themed sites will exist for many years and these sites also update their WP / Gutenberg. PHP themed sites are also seeing core .   If I try to activate theme.json on any of my legacy or current dev sites it will break the site, so I will continue to create and support PHP themes. 

Please ensure that 99% of sites will function as per the docs. Please do not  make WP exist on a bleeding edge.

https://make.wordpress.org/core/2020/01/23/controlling-the-block-editor/

**Comment by fabiankaegy** [comment]
@steveangstrom I would treat your ticket here: #36489 as a follow up to this. The fix that was supplied here does not impact php themes and so it is correct to keep tracking the issue.

**Comment by skorasaurus** [comment]
> @paulwilde No this would not remove these classes. The reason for this is, that the Core palette is only removed from the Editor view so editors are not able to select from the Core palette anymore.
> 
> However, the reason why the actual classes don't get removed is that if a block pattern from the core pattern library gets inserted it expects the core palette to be available. Editors could then change the color of that pattern to one of the theme colors.
> 
> I can see how this is something that one may want to remove altogether. But that should be a separate issue that I think is important but not a 5.9 blocker.

The ability to remove those classes had been requested at https://github.com/WordPress/gutenberg/issues/24684 but it was declined. :(

**Comment by turansadri** [comment]
Things like this are extremely annoying when trying to create a site for clients with brand guidelines. No one wants the content editors to be able to use core colour palette for _anything_ and atm we are not able to remove it at all.

In how to guides theres option for "corePalette" and "coreGradients" showing but those are not included in JSON schema and they also don't work.

https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/

Is there any way to remove the core colors currently or are we forced to revert to Gutenberg 11.8.3?

![Screenshot 2021-11-17 at 9 47 46](https://user-images.githubusercontent.com/6302228/142158274-b5b02c03-9c2f-46d8-b968-b4f2209e2210.png)

**Comment by fabiankaegy** [comment]
@turansadri Hey there 👋 

The fix to allow you to remove the Core Palette and Gradients has been merged into Gutenberg. That means that the next version of the Gutenberg Plugin will include that fix. It has also been marked as something that should get included in the WordPress 5.9 release. 

The documentation in the Handbook is coming directly from the markdown files here in GitHub and therefore they get updated when a feature has been merged. Even when it may not jet be released. 

Till the next version of the Gutenberg Plugin is released I'm afraid the only option is to downgrade to 11.8.3 for the time being.

**Comment by gingerling** [comment]
Hi, is this about how to remove Default colours using the json? I have edited the theme colours to be as the brand guidelines need for my client (working in 5.9 beta 3) but can't seem to get rid of the default colours below that I don't really want them to use.

![Screenshot from 2022-01-18 16-51-14](https://user-images.githubusercontent.com/2853040/149981883-4bf6bd16-9d3c-4746-8b9d-0c8984ffba9b.png)

I'm not clear if this is a separate issue or not from reading this bug

**Comment by skorasaurus** [comment]
Hi @gingerling ; 

This is the same issue; I'm not able to reproduce your issue using the 5.9 RC2 (released last week) which is newer than beta 3 (released in december?). 

I recall there being a lot of changes recently with theme syntax and such; what worked for me in my theme.json to disable the default colors and only provide the theme provided colors is the following; this worked in 5.9 RC 2 both with gutenberg activated and not activated. 
```
{
  "version": 1,
  "settings": {
    "color": {
      "custom": false,
      "customGradient": false,
      "gradients": [],
      "link": false,
      "defaultPalette": false,
      "defaultGradients": false,

```

**Comment by timotheemoulin** [comment]
Hi @skorasaurus,

The mentionned settings doesn't seem to have any impact on the `default` color palette.
We can add theme colors, but not remove the default ones.

![image](https://user-images.githubusercontent.com/1841590/182314894-ae3d75bc-c6e5-455b-9d29-3c9ee3817a79.png)

Have the settings changed?
