### ISSUE TITLE
Changing Block Template Content Width value doesn't dirty save state

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#36409]
### Description

When modifying the content width/height of a Block Template Block the 'SAVE' button is not enabled.

<img src="https://user-images.githubusercontent.com/146530/141321249-1d4cdbc9-c53a-40b7-b010-96fa544e959f.png" width="300">

Making further changes to the template (such as a text change, etc) enables the save button and the layout width/height values ARE saved to the template.

Originally reported here: https://github.com/Automattic/themes/issues/4906

### Step-by-step reproduction instructions

Activate a theme (such as Blockbase) and open the FSE.
Select the Header Template and set a value for `Content` or `Wide` width.
Note that the [SAVE] button is not activated.

### Environment info

- Using latest version of WordPress (wp-env) and Gutenberg (/trunk) on Chrome or Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by DeoThemes** [comment]
The same bug happens in the opacity control of a Cover block.

**Comment by annezazu** [comment]
@pbking would you be okay closing this out in favor of this overall issue? https://github.com/WordPress/gutenberg/issues/30515 I don't feel strongly either way but do want to consolidate where we can.
