### ISSUE TITLE
Add CSS Custom Property for layout width to editor and frontend

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#36414]
### Description

Pretty much all the options that we set in `theme.json` are available to theme & plugin authors via CSS Custom Properties. That is not the case for the layout width settings. 

It would be really useful to be able to access the `contentWidth` and `wideWidth` values as custom properties.

```json
{
  "version": 1,
  "settings": {
    "layout": {
      "contentSize": "800px",
      "wideSize": "1000px"
    }
  }
}
```

Based on the other properties the naming scheme would probably be something like: 

```css
--wp--preset--layout--content-size: 800px;
--wp--preset--layout--wide-size: 1000px;
```

### Step-by-step reproduction instructions

does not apply

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by chthonic-ds** [comment]
See https://github.com/WordPress/gutenberg/pull/30081.

**Comment by fabiankaegy** [comment]
Thanks for raising that ticket :) Closing in favor of #30081.
