### ISSUE TITLE
Responsive Navigation overlay not changing colours when Submenu & overlay colours are set

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#36429]
### Description

When Submenu & overlay text and background colours are set in the Navigation block, the colours take effect on submenu navigation links, but not on the overlay. The only way to change overlay text and background colours is to set them for the whole Navigation.

### Step-by-step reproduction instructions

1. In a Navigation block, change Submenu & overlay text and background to non-default values.
2. Make sure "text" and "background" for the whole navigation are set to default.
3. Make sure overlay menu is active either on "mobile" or "always". 
4. Save and open the overlay menu in both the editor and the front end.
5. Verify that overlay text and background colours are default ones (black text on white background).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
CC: @georgeh @vcanales in case you have any insight into what might have regressed this.
