### ISSUE TITLE
It is impossible to set PM time using only keyboard

### ISSUE THREAD

**Issue by pansamolot** [WordPress/gutenberg#36422]
### Description

It is impossible to set post's time to any afternoon or evening time using just keyboard, because (an example -- an attempt of setting hour to 6 PM / 18:00):

* If you set hour field to `18` and press <kbd>Tab</kbd>, field's value will be reverted to previous one, because field does not accept values higher than 12
* If you set hour field to `6` and press <kbd>Tab</kbd>, field's value will be accepted, but AM/PM knob will be automatically shifted back to `AM`.

If you want to set afternoon/evening time you must always use mouse to click AM/PM knob back to `PM`.

### Step-by-step reproduction instructions

1. Go to any post and start editing it.
2. Click _Publish: immediately_ to change time.
3. Make sure that AM/PM knob is set to `PM`.
4. Click hour field and type `6`.
5. Press <kbd>Tab</kbd>.
6. Observe AM/PM knob auto-shifting back to `AM`.

### Environment info

* WordPress 5.8.2
* Gutenberg (the development plugin) version 11.9.0
* Theme WR-Elite version: 1.6 by WooRockets
* Chrome version 95.0.4638.69 (Official Build) (64-bit)
* Windows 10 version 10.0.19042 Build 19042

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Thanks for opening this issue! I tried to replicate with the same setup (WordPress 5.8.2 + GB 11.9) and found I was able to set the time to PM. I did notice it shifted to AM when I changed it to 6 but that I was still able to change the AM/PM to PM:

https://user-images.githubusercontent.com/26996883/141593663-a203dde4-9118-4af0-b1cf-e1e793fb51c5.mov

I'm going to close this out as a result but let me know if I missed something and this needs to be re-opened!

**Comment by pansamolot** [comment]
You are correct that additional 2 x <kbd>Tab</kbd> (to go to `AM` and then to `PM`) and then additional <kbd>Enter</kbd> (to confirm `PM`) does allow to set time to PM without touching the mouse. Thanks for this tip. I was always hitting <kbd>Esc</kbd> after setting hour and minute and thus my time remained at `AM`.

From this perspective you're right that we should keep this ticket closed.

However, I still think that it is wrong, pointless and counterproductive that we change AM/PM knob in any scenario. Maybe you disagree with my, but from my perspective this is just a way how Wordpress attempts to guess for me what I am intend to do. I'd strongly suggest removing this behaviour. If you agree then we may need to open another ticket for that.

**Comment by annezazu** [comment]
> I'd strongly suggest removing this behaviour. If you agree then we may need to open another ticket for that.

Looks like this is already covered and others agree with you in this issue: https://github.com/WordPress/gutenberg/issues/29720

Thanks for following up :)
