### ISSUE TITLE
Request: define font-weight for bold/strong text

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#36435]
## What problem does this address?

In the editor, text that is bolded is given a font-weight of 600.

However, with a theme that does not provide it's own CSS, on the front-end there is no font-weight defined for bolded text.
This sometimes results in a mis-match between the appearance in the editor vs the front-end.
The bolded text can appear either bolder or lighter than the editor depending on the font/browser combination.
## What is your proposed solution?

Have Gutenberg define a font-weight for `b, strong` that would be consistent across editor and front-end.

**Comment by eric-michel** [comment]
Second this proposal. I'm working on converting our theme to using `theme.json` and found the editor default of `600` for `<strong>` font-weight to be odd, given that `700` is often the standard. If we could set `b, strong` font weight options in `theme.json` (preferably by font family) that would unify between backend and frontend that'd be great!

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/30297 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

Please reopen if I misunderstood and that this is different than the other issue.
