### ISSUE TITLE
404 Error on a preloaded route when creating a new template part.

### ISSUE THREAD

**Issue by Hug0-Drelon** [WordPress/gutenberg#36438]
### Description

When adding a new template part in the admin screen, with the request `https://myblog.local/wp-admin/post-new.php?post_type=wp_template_part`, WordPress preloads data [here](https://github.com/WordPress/WordPress/blob/489b33c97a8942e43c92f3d4a5efe069fecccb32/wp-admin/edit-form-blocks.php#L55). Then there is a call to the route `/wp/v2/template-parts/\d+` with a digit as template part identifier, which is filtered by Gutenberg [here](https://github.com/WordPress/gutenberg/blob/8637cfc1c3550a63552e7a7985f23553b42466e5/lib/full-site-editing/class-gutenberg-rest-templates-controller.php#L175). 
Then the `gutenberg_get_block_template()` function is called and return`null` because it expects a string identifier (e.g. `twentytwentytwo//header`) [here](https://github.com/WordPress/gutenberg/blob/8637cfc1c3550a63552e7a7985f23553b42466e5/lib/full-site-editing/block-templates.php#L491). This leads to a 404 error in the previous `get_item()` function.
Although the template part is already created as auto-draft (thanks to WordPress and the call to `get_default_post_to_edit()` [here](https://github.com/WordPress/WordPress/blob/489b33c97a8942e43c92f3d4a5efe069fecccb32/wp-admin/post-new.php#L66)).

This shouldn't return an error if we expect that `wp_template_part` post type works like any others.
Also, it prevents anyone to add query parameters to the  `https://myblog.local/wp-admin/post-new.php?post_type=wp_template_part` request to get any information or to add any default value when a template part is created for instance.

### Step-by-step reproduction instructions

1. Go to Appearance >> Template Parts.
2. Click on "Add New".
3.  Use a debugger to see what happen [here](https://github.com/WordPress/gutenberg/blob/8637cfc1c3550a63552e7a7985f23553b42466e5/lib/full-site-editing/class-gutenberg-rest-templates-controller.php#L182) .

Indeed, the problem can't be seen in the interface.

### Environment info

WordPress 5.8.2, Gutenberg 11.8.3, TwentyTwentyTwo theme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
As Template Parts are both handled differently, *and* have a different post type slug now - I'll close this issue as no longer reproducible.
