### ISSUE TITLE
Navigation/Submenu block: Explicit overlay colors do not affect the Submenu on the frontend

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#36439]
### Description

Possibly related to #36429. When setting an explicit overlay color using the "Submenu & overlay background" property, it applies to submenus and submenu blocks in the editor only. 

Any submenu on the frontend will not inherit the color:

<img width="895" alt="Screenshot 2021-11-12 at 12 59 28" src="https://user-images.githubusercontent.com/1204802/141464030-d3709c5c-0ede-488e-b037-2ba69fb028af.png">

In the editor it works fine:
<img width="858" alt="Screenshot 2021-11-12 at 12 59 35" src="https://user-images.githubusercontent.com/1204802/141464044-c924b019-842a-4f6a-a5c6-9ad346a976e4.png">

### Step-by-step reproduction instructions

Create a navigation menu with at least two levels of nesting.

Set an explicit overlay background color. Note that it doesn't apply to the submenu on the frontend.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tellthemachines** [comment]
This is a duplicate of #36427, isn't it? I'm looking into it.

**Comment by jasmussen** [comment]
My apologies, I really did search first 🙈 

Closing in favor of #36427.
