### ISSUE TITLE
Gallery image link to custom url

### ISSUE THREAD

**Issue by Ezyweb-uk** [WordPress/gutenberg#36443]
## What problem does this address?
There is no 'Custom URL' option in WP v5.8.2 Gutenbery Gallery Block 'link to' options, I wish to link an image on mouse click to and external website. I've tried the 'Gallery Custom Links' plugin but that didn't add the option on my installation which uses the BuddyBoss Theme.

## What is your proposed solution?
Please add the option to link to an external url.

**Comment by annezazu** [comment]
Good news! In Gutenberg 11.9, a new gallery block refactor was released that allows you to link your image to an external website. You can read more about this change here and stay tuned for the 5.9 release where this is planned for inclusion: https://wordpress.org/news/2021/09/upcoming-gallery-block-improvements/
