### ISSUE TITLE
How can I get gutenberg back to work?

### ISSUE THREAD

**Issue by MartaPaola** [WordPress/gutenberg#36442]
Hi,
I created my website with all my pages in gutenberg. I have installed Elementor and then disabled it. Then I installed Storefront and created its child theme. Now that I want to edit a page I have the classic editor, but I want to have Gutenberg again. The plugin is already installed and active, but within the pages it is not visible.
How can I get gutenberg back to work?

thanks

**Comment by talldan** [comment]
Hi @MartaPaola. 

It'd be great if you could reach out about this on the WordPress support forums.
https://wordpress.org/support/forums/

This Github repository is for reporting bugs.

Your issue doesn't seem like a bug, but some combination of steps you've taken or plugins you've installed have resulted in the block editor becoming disabled.
