### ISSUE TITLE
(Site) "Editor (beta)" loads with wp-admin navigation in the background.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#36445]
There is a recent regression in the 11.9.0 releases that has caused the site editor to load with the wp-admin nav bar in the background instead of the blank editor canvas.

Current behavior with the regression:

![site-editor-wp-admin-background-loading](https://user-images.githubusercontent.com/28742426/141471073-d5d6928a-fe7e-4ffd-9b4c-edc8947d0223.gif)

Notice that when the editor starts loading, the wp-admin nav bar remains on the left while the rest of the screen turns white.  This remains in place until all editor content is loaded and dropped into place at once.

This may be related to https://github.com/WordPress/gutenberg/pull/36044 (cc @youknowriad ) as doing a local revert seems to resolve the issue and the behavior goes back to its previous and expected state:

![site-editor-proper-loading](https://user-images.githubusercontent.com/28742426/141470636-c1fafaca-325c-4a7b-a8b4-3f46dfd211d2.gif)

Notice how the blank editor canvas is shown while the editor content finishes loading, instead of awkward wp-admin nav menu with blank white screen.

This regression seems especially concerning in environments with longer load times.

**Comment by youknowriad** [comment]
This has been solved in WordPress trunk already and we should bring the same fix to the Gutenberg repo. Basically we need the `is-fullscreen` class added to the body classes. See https://github.com/WordPress/wordpress-develop/pull/1842 

That's also the same technique used in the post editor.
