### ISSUE TITLE
Image block: uploading an image replacement flashes old image before replacement

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#36458]
### Description

When uploading an image file over image block that already has image, the old image flashes for a moment after uploading has finished:

https://user-images.githubusercontent.com/87168/141594383-23bc31c9-3beb-4bd3-b647-91cb5cb13e47.mov

### Step-by-step reproduction instructions

1. Add image block
2. Upload image
3. Drag and drop another image into the block
4. After loading, the old image flashes for a brief moment

### Environment info

- Firefox / MacOS
- Gutenberg 11.8 and 11.9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Thanks for reporting @simison. I am no longer able to replicate this issue in WordPress 6.2 RC2. Therefore, it looks like this bug has been resolved in the past few years. If you continue to experience issues, please feel free to reopen this issue. Thanks!
