### ISSUE TITLE
Gutenberg List View hides inner block plus

### ISSUE THREAD

**Issue by CHEWX** [WordPress/gutenberg#36452]
### Description

If you're using inner blocks and the inner blocks plus is far left, when you have the nav open it hides it. You should be able to add blocks with the nav open all the while, it's shouldn't hide any content? Attached is open and closed, you can see how the plus is missing then open, so a user wouldn't know how to add an inner block, it's just empty.

![Screenshot 2021-11-12 at 15 56 01](https://user-images.githubusercontent.com/5207147/141496180-0f78659b-cb65-49e9-8bb9-a66524b950e0.jpg)
![Screenshot 2021-11-12 at 15 56 23](https://user-images.githubusercontent.com/5207147/141496184-49d6d163-ad48-439e-8940-89b092617827.jpg)

### Step-by-step reproduction instructions

This might be an ACF blocks related issue, but I would expect the same on a custom inner block.

1. Create inner block that is far left without a container.
2. Check for inner block + with both nav open and close.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by CHEWX** [comment]
This might be related to https://github.com/WordPress/gutenberg/issues/36451 as the NEW BLOCK UI, should really be centered with a line, not aligned left. This would probably fix the issue as it would be visible then. Although the point still stands that the nav should cover any blocks.

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using core blocks with inner blocks, like group, cover, etc. Would you be able to retest using the latest versions of Gutenberg and WordPress and see if this is still an issue?

**Comment by kathrynwp** [comment]
@CHEWX Hi again - one more check-in to see whether you are still experiencing this issue with the latest versions of Gutenberg and WordPress, otherwise we'll go ahead and close this out. Thanks!

**Comment by CHEWX** [comment]
Will take a look tomorrow.

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg and WordPress. Therefore, I am going to close this issue. If anyone can replicate it in the future, please feel free to reopen this issue with additional information.
