### ISSUE TITLE
Don't move the window while dragging a block

### ISSUE THREAD

**Issue by TheRadicalDreamer** [WordPress/gutenberg#36457]
## What problem does this address?

When taking and dragging a block around. At the moment i take the 6-dot mark, the window begins to scroll up or down depending on which half of the screen i am.
This is not only annoying on certain situations, but makes moving almost impossible on certain others.
For example, when i am trying to target a certain point in between blocks.

## What is your proposed solution?

I would love that the scrolling of the window begins on the top and the bottom of the screen, but no in the middle.

That way we can move things around without the window scrolling immediately.

[Screen recording 2021-11-12 18.47.26.zip](https://github.com/WordPress/gutenberg/files/7530579/Screen.recording.2021-11-12.18.47.26.zip)

**Comment by kevin940726** [comment]
Seems like this is the desired behavior introduced in https://github.com/WordPress/gutenberg/pull/23082. I personally found it counter-intuitive too but it seems like others are happy about the change. Would love to know what improvements or trade-offs we can make, maybe we should only trigger the scroll in a narrower threshold? c.c. @gravityrail and @talldan

**Comment by TheRadicalDreamer** [comment]
Yes exactly!

I do like the movement, but not immediately.

It should be over a threshold. Maybe top 20% of the screen and bottom 20% of the screen?

**Comment by talldan** [comment]
> the window begins to scroll up or down depending on which half of the screen i am.

It should be that if you move your mouse up above the point on the screen where you started dragging from the page starts scrolling up, and if you move it down below where you start dragging from the page starts scrolling down. I think that's similar to how a middle-click to scroll used to work on Windows (it may still work like that, I haven't tested it in a while).

> It should be over a threshold. Maybe top 20% of the screen and bottom 20% of the screen?

Yeah, I proposed that as an option (https://github.com/WordPress/gutenberg/pull/23446), though the preference was for the way it currently works. It could be worth revisiting now that more time has passed and there's been more usage. That pull request might be easy to resurrect, as I don't think the code has changed much. 

It is pretty easy to change the way this feature works, the hard part is finding an option that's generally agreeable.

**Comment by TheRadicalDreamer** [comment]
@talldan and @gravityrail i am honestly fine with any percentage is set. But I believe 20% for the top and bottom is fine, because it leaves you 60% of the center screen to move around freely with the screen scrolling, ultimately allowing you to precisely move the block.

Who do we need to call to make this a feature?

**Comment by talldan** [comment]
#24770 discusses the same thing, so closing as a duplicate and adding that issue to #63255
