### ISSUE TITLE
Add new block styling

### ISSUE THREAD

**Issue by CHEWX** [WordPress/gutenberg#36451]
### Description

Why are the block divider plus styled differently to the end divider? Shouldn't they be the same regardless of theme?

Attached example of both. The correct one is the one between blocks, but the end one isn't good.

![Screenshot 2021-11-12 at 15 47 56](https://user-images.githubusercontent.com/5207147/141494864-10cfa3ff-a54d-4bf8-a685-088374c94b5b.jpg)
![Screenshot 2021-11-12 at 15 47 44](https://user-images.githubusercontent.com/5207147/141494866-7693b6e5-09b6-4a26-ad79-c3c08b1e3a10.jpg)

### Step-by-step reproduction instructions

1. Add theme, any.
2. Add block.
3. Look at difference between blocks.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Hey @CHEWX! Thanks for opening this. There's a lot of discussion around the + block in general happening in this issue: https://github.com/WordPress/gutenberg/issues/26404 To better consolidate and move the conversation forward, I'm going to close this out as a result so the conversation can continue there.
