### ISSUE TITLE
The Color Palette are no longer in the editor

### ISSUE THREAD

**Issue by Denis74F** [WordPress/gutenberg#36459]
### Description

With the addition of Gutenberg 11.9.0 the color palettes are gone in the full site editor, did I miss something?

### Step-by-step reproduction instructions

Edit site
Colors

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi
I am not able to reproduce this. The panel is collapsed by default though.
Did you try with a different theme?

**Comment by Denis74F** [comment]
Hi,
I have tried with all the available themes, and they all don't show palette

<img width="1759" alt="Schermata 2021-11-13 alle 09 56 21" src="https://user-images.githubusercontent.com/60289158/141612764-843ac5e3-e5db-4df7-8b78-51d535c2dac8.png">
es

**Comment by lwangdu** [comment]
I think you have to click on the background. You can see the color palette.

**Comment by Denis74F** [comment]
Unfortunately, even clicking on the background the palettes are not displayed. There is only the possibility of creating new palettes, but the default theme palettes are not displayed.

**Comment by Denis74F** [comment]
Here is an example

https://user-images.githubusercontent.com/60289158/141648559-d58a1f18-966a-4d4a-9c59-6a8708427c89.mov

**Comment by ellenbauer** [comment]
I think it also seems that the theme's color palette can not be accessed in one overview list as before. Or am I missing something here?

Is there a new way theme authors can add colors to the Background/Test/Links list, so that general theme colors we want to make available to be changed can be changed right there?

**Comment by lwangdu** [comment]
I am using twenty twenty-two theme. The theme colors are available. See the screen short
![Screen Shot 2021-11-13 at 3 39 26 PM](https://user-images.githubusercontent.com/24829573/141662200-7fda0490-ce45-40b1-b5d3-a5fb9a40f380.png)

**Comment by Denis74F** [comment]
Hi @lwangdu,
the problem that I have exposed is different from what you want to show.
I'll explain well:
With Gutenberg **11.8.3** you had the possibility to change the colors of the palette of the theme used, in this way the customer had the possibility to completely customize the site in all shades of colors. For example, if you set an element with color "color:var(--wp--preset--color--bubiblockwhite)" it was enough to change the color of that palette and you could customize that particular color. In **Gutenberg 11.9.0** (in the screenshot shown by you) you only have the option to set the **background** color, **link** and **text**.

Here is an example to explain the problem well. I did the video with the theme I am developing, but the problem, as explained above, occurs with any theme available.

**Gutenberg 11.8.3**


https://user-images.githubusercontent.com/60289158/141663139-ae600ffe-d461-42ed-8abc-3f7ae869a79a.mov

**Gutenberg 11.9.0**


https://user-images.githubusercontent.com/60289158/141663224-e0baa241-1431-4068-97dd-75b545007e6a.mov

I hope I have well explained the problem encountered with the new version of Gutenberg

**Comment by carolinan** [comment]
I got you now, I did not understand from the original description that you meant the global styles. I thought you meant block color settings.

**Comment by Sandstromer** [comment]
I am also seeing this bug.

Under the 'PALETTE' heading it always says "0 colors" regardless of the theme and how many colors are actually defined by the theme, and then opening up the color palette it is completely empty.

**Comment by Denis74F** [comment]
Yes in my opinion it is inherent to the same bug.
If you add a color to the "PALETTE" it starts numbering them.

<img width="729" alt="Schermata 2021-11-15 alle 11 42 14" src="https://user-images.githubusercontent.com/60289158/141768118-aecd5cd8-999d-4949-a3fb-ad50717a2611.png">
.

**Comment by youknowriad** [comment]
This seems solved to me. If I'm missing something please provide some new testing instructions. Thank you.
