### ISSUE TITLE
Allow ability to give innerblocks alignment control when using theme.json

### ISSUE THREAD

**Issue by bethalessi** [WordPress/gutenberg#36465]
## What problem does this address?
If I use theme.json I lose the ability to give innerblocks alignment control. 

I have a simple "section" custom block: it's fullwidth and has set vertical padding and a background color. That's it. It allows my client to choose the "section" block, choose a background color, and add innerblocks. This way they can group content together with a pre-styled look without thinking about padding.

Without theme.json, it works perfectly. The paragraphs are the default content width and they can add innerblocks and choose wide alignment for the innerblocks. 

With theme.json, it breaks. Everything is left aligned, header blocks lose alignment control and cover/image/other custom blocks only have left/right/center but not wide/full alignment control. 

### How it looks in the editor with theme.json
<img width="2260" alt="Screen Shot 2021-11-13 at 10 36 44 AM" src="https://user-images.githubusercontent.com/11951296/141650052-40296f8e-1be8-41c9-8a94-f7abd4afb22f.png">

### How I expect it to look (with ability choose alignment on innerblocks)
<img width="1936" alt="Screen Shot 2021-11-13 at 10 45 37 AM" src="https://user-images.githubusercontent.com/11951296/141650084-410ff947-e46b-4882-b744-36a31189eff7.png">

## What is your proposed solution?
I understand there are implications for FSE, but many of us are developing hybrid themes and want control. We should be able to specify that we want innerblocks to have alignment control and to follow the default alignment. 

I know that you can toggle a switch on the Group block to inherit default alignment. But the purpose of my custom "section" block is to let my client group content without thinking about alignment or padding. They should not have to toggle anything.

If I want this control, does that mean I can't use theme.json?

It's frustrating to not have control over this.

**Comment by skorasaurus** [comment]
Hi, unfortunately I think https://github.com/WordPress/gutenberg/issues/33374 may be very similar to what you're experiencing?

**Comment by bethalessi** [comment]
@skorasaurus Ahh, it does indeed. Thank you. _But_ also doesn't solve the problem. My question then:

Does this mean I can't make a custom block that allows innerblocks to have alignment controls (if I use theme.json)? I see the group block allows it, but you have to toggle. I don't want my client to have to toggle.

I'm making themes for clients, not themes to be released to the world where all use cases have to be thought of. In that issue you linked to he used an example of it breaking if you use the columns block. I remove the columns block. 

I just want to be able to give innerblocks alignment control when building my custom block. I feel.... frustrated and confused. It feels strange to not have control as the developer of a private, custom theme.

**Comment by skorasaurus** [comment]
@bethalessi I don't know; I've also been trying to figure out how wide and full alignments interact with a 'hybrid' theme that is PHP based but also uses theme.json. (I'm not one of the core Gutenberg developers, just someone who occasionally helps triage issues on the tracker :) ) I'll close the issue since it overlaps with #33374 and encourage you to copy your reactions into that thread. 

I've found https://make.wordpress.org/core/2021/06/29/on-layout-and-content-width-in-wordpress-5-8/ helpful for background on CSS styling with theme.json
