### ISSUE TITLE
Navigation Block: Submenu additional class duplication

### ISSUE THREAD

**Issue by jacobcassidy** [WordPress/gutenberg#36464]
### Description

When adding a class to a submenu block under "Advanced", it gets duplicated in the HTML twice. If you add multiple classes, they all get duplicated twice.

### Step-by-step reproduction instructions

1. In the Editor, add a submenu block
2. Add a class for the submenu block in `Advanced > Additional CSS class(es)`
3. Save your page
4. Go to the live page and inspect the submenu block
5. Notice the additional class(es) you added are inserted twice.

### Screenshots, screen recording, code snippet

Add class called `test-submenu`
![Add class to submenu](https://user-images.githubusercontent.com/1895973/141649858-29044e5f-fe83-4744-9d99-ffebf0ce1411.png)

Check live page HTML for duplication of class:
![HTML class duplication](https://user-images.githubusercontent.com/1895973/141649885-d507acde-27c2-43e8-b7b1-2a0491c3c6c0.png)

### Environment info

- WP v5.8.2
- Glutenberg v11.9.0
- Chrome v95
- macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Looks like this should be a pretty simple fix. It has already been fixed in the navigation link block in https://github.com/WordPress/gutenberg/pull/35634 by deleting some code.

It should be possible to do the same in the submenu block.
