### ISSUE TITLE
Unable to use template-part in a Pattern block

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#36467]
### Description

~~When using a template-part block within a pattern, the template part renders empty on the front-end.~~

When using a template-part block within page/post content, the template part is rendered empty on the front-end.

### Step-by-step reproduction instructions

~~Create a registered pattern that contains a template part, e.g.:~~

~~register_block_pattern(~~

~~Use the pattern in a page/post or within a template, e.g.:~~

Use a template-part within the content of a page/post, e.g.:

```
<!-- wp:template-part {"slug":"header","tagName":"header"} /-->
```

Check the page on the front-end and notice empty space, and in the source code the template-part wrapper is present but its inner content is missing.

The other block `wp:post-title` is rendered correctly, and other blocks I tested are OK, so it seems there is some bug with rendering the `wp:template-part` block.

### Environment info

WP 5.8.2
Gutenberg 11.9.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Sandstromer** [comment]
Please ignore the part about putting a template-part within a pattern.

I have since realised this is not applicable, as it seems adding a template-part within a page/post content also renders empty content on the front-end, so it has nothing to do with the pattern block.

It looks to be an issue solely with the template part block when using it outside of a template, i.e. in a page or post.

**Comment by Sandstromer** [comment]
Okay, so what I was trying to do was create a page template with the site header inside a cover block.

This is possible when using the absolute path to the cover image in the header template, but I was attempting to make use of the new pattern block as with this we can include `get_template_directory_uri()` to get the image directory path.

Sadly, when using the pattern block this looks like it is treated as though it is page content, and as the template-part block cannot be used within page/post content, this results in the "Template part has been deleted or is unavailable: header" error message in the editor, and is empty on the front-end.

I really hope someone with more extensive knowledge of these issues can come up with a solution that would allow us to use template-parts within patterns.

**Comment by carolinan** [comment]
Does it not work if you place the pattern in the template part?

**Comment by talldan** [comment]
> Please ignore the part about putting a template-part within a pattern.

Should the issue be renamed?

**Comment by Sandstromer** [comment]
> 
> 
> Does it not work if you place the pattern in the template part?

Yes, pattern in a template part does work.

What I was trying to do was a template part in a pattern.

**Comment by Sandstromer** [comment]
> 
> 
> > Please ignore the part about putting a template-part within a pattern.
> 
> Should the issue be renamed?

Sorry for the confusion.

I renamed the issue a couple of times, and got myself confused thinking about whether it was an issue with patterns, template parts in patterns, template parts in page content, or template parts in patterns in templates. Got myself completely tied in knots.

I think I should be only using the inner blocks (Logo, Navigation etc) in a pattern and not using the already defined header template part.

My thinking was as there is already a header, we could simply reuse the header in a pattern. This would allow the user to only edit the one header template part, and then reuse this in various contexts, so the user wouldn't need to edit the indivdual blocks within the header, logo/site title/navigation etc more than once in different contexts.

I think I now have a better understanding why template parts are not valid blocks to used in post/page content (and thus also not valid in patterns), so I'll close this out.
