### ISSUE TITLE
Preferences: Adding a toggle to hide Patterns.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#36470]
## What problem does this address?

Clients might insert patterns the web site designer/developer do not want the client to insert.

![Screenshot 2021-11-13 at 23 56 41](https://user-images.githubusercontent.com/5323259/141661401-61e979d0-32f5-468f-a012-da84f96cbd7a.jpg)

## What is your proposed solution?

For a web site designer/developer to have more control over a web site they might want to hide specific aspects such as inserting patterns. My suggestion is to add a toggle into the Preferences modal to hide Patterns from appearing inside the block inserter.

I am not sure where such a toggle would be inserted.

![Screenshot 2021-11-13 at 23 58 13](https://user-images.githubusercontent.com/5323259/141661437-ac232549-a48e-4a29-8b7a-39dd4233fb98.jpg)

We could probably followup and do the same treatment for the block Inserter Reusable tab. 

@ntsekouras 

This issue was influenced by Justin's article here and the comments seen below.
https://wptavern.com/block-pattern-modal-explorer-coming-to-wordpress-5-9

Associated:
[Patterns]: Add a flag to hide patterns from UI
https://github.com/WordPress/gutenberg/pull/36108

**Comment by skorasaurus** [comment]
is this resolved by https://github.com/WordPress/gutenberg/pull/36108 ?

**Comment by ntsekouras** [comment]
There is `should_load_remote_block_patterns` filter that themes can use to hide the core patterns. I think having a flag in the preferences doesn't actually solves the issue described.

**Comment by ndiego** [comment]
Yeah, also you can use the following to hide all core patterns. 

```
remove_theme_support( 'core-block-patterns' );
```

If you combine this with #36108, you can hide all core patterns **plus** make any theme registered patterns hidden from the insertion UI. In doing so, the Pattern panel is hidden in the inserter. 

This got me thinking though. I believe this info should be included in the [Patterns doc](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/). I don't mind writing it if everyone agrees.

**Comment by paaljoachim** [comment]
@ndiego Nick do please add the info into the Patterns doc.
@mkaz can help if you need any help getting the information into the document.

**Comment by mtias** [comment]
Closing this as the presence of the patterns tab should be a reflection of whether there are registered patterns, not a separate preference.
