### ISSUE TITLE
Copy and paste that includes a nested block duplicates first block

### ISSUE THREAD

**Issue by smerriman** [WordPress/gutenberg#36474]
### Description

Copying and pasting blocks regularly result in the first block duplicated. It appears as if this happens any time the copied block contains nested ones (at least, it occurs with default Buttons, as well as similar custom blocks I've written myself).

### Step-by-step reproduction instructions

In a fresh installation of WordPress 5.8.2, create a new page and paste the below content.

The first paragraph will appear twice.

### Screenshots, screen recording, code snippet

```
<!-- wp:paragraph -->
<p>test</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">Sample button</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">Sample button 2</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
```

### Environment info

WordPress 5.8.2, no Gutenberg plugin
Twenty TwentyOne (but occurs in any)
Desktop, Firefox, Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. I am able to reproduce this without having the Gutenberg plugin activated; but I am not able to reproduce this when I have the Gutenberg plugin activated; the gutenberg plugin has newer fixes and features that will eventually be imported into the core version of WordPress. 
I can't find the issue at the moment; but I do recall this had been reported and fixed. 

If you're still able to reproduce this with the plugin installed, please reopen.
