### ISSUE TITLE
Add nudge to include name for Custom Color Palette

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#36473]
## What problem does this address?

This is pulled from the [eleventh call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/11/08/fse-program-testing-call-11-site-editing-safari/#comment-2217):

>I actually missed that I needed to add a name to the color at all 😅 Since there’s no placeholder text in the area where the color name should be added, I completely overlooked it and assumed I would just add the color, click Done, and voilà! However, it looks like not adding a color name at all means the colors won’t get saved. Adding some directive placeholder text next to the colors – or even an error message after clicking Done – might have helped me move past that. 

& another person:

> Just like @evarlese observed (and thanks for the precious notes!), the way to deal with the Custom Color Palette is not straight forward, at all. She already explained it really well, so adding my +1 also to the proposed solutions. Kudos Erica!

https://user-images.githubusercontent.com/26996883/141694781-83192cfb-0e89-4e4f-8268-6bb19af6f5fe.mp4

## What is your proposed solution?

Rather than resetting the custom color and not saving it, add in a prompt or warning to have someone include a name for the color. Perhaps it could be as simple as highlighting the field if it's empty or adding in placeholder text for where the name needs to go:

<img width="263" alt="Screen Shot 2021-11-14 at 2 07 22 PM" src="https://user-images.githubusercontent.com/26996883/141694909-1b47de20-1326-4c17-8769-ef5e6aca2c3e.png">

To make it less jarring, could just add a weighted border that's black to point it out more as a field: 

<img width="265" alt="Screen Shot 2021-11-14 at 2 08 17 PM" src="https://user-images.githubusercontent.com/26996883/141694945-34b70940-dd42-4c63-a110-183cd3cad610.png">
 
I'll leave it to designers :D

**Comment by noisysocks** [comment]
We should also add validation to this field. Names containing a space don't work for me when I use the custom colour. (Might be browser specific, I'm testing with Safari.)

**Comment by javierarce** [comment]
> Rather than resetting the custom color and not saving it, add in a prompt or warning to have someone include a name for the color. Perhaps it could be as simple as highlighting the field if it's empty or adding in placeholder text for where the name needs to go

Depending on how much time we have to fix this UI, I can propose different solutions. Here's the quickest one:

Similar to what @annezazu proposes, I suggest adding a temporary color name using "color" plus the number of items on the list. 

![image](https://user-images.githubusercontent.com/4933/142175524-cc045f9a-3962-42f9-af8e-512c8da5bba8.png)

The reason for this suggestion is that right now, when the user clicks the + button to add a new color, we immediately show the popover, and then we close it when they click outside. At the same time, we hide the input field, so I fear that some people will forget to change the "enter name" prompt.

Another important thing I would add right away is the hover state for the input fields when they aren't active:

https://user-images.githubusercontent.com/4933/142193306-8368d6a6-058d-4fba-97fb-2bce78b77e0f.mp4

**Comment by colorful-tones** [comment]
There may be some overlap here with [Color naming conflict for theme variables #36360](https://github.com/WordPress/gutenberg/issues/36360). Especially with mention of color name validation.

**Comment by richtabor** [comment]
I like the idea of having the intiial label for a color being "Color $count", so the user doesn't _have_ to think of/provide a label, and it is required.

**Comment by jiteshdhamaniya** [comment]
I'd just create a PR for it.

**Comment by ramonjd** [comment]
I've started a PR over at https://github.com/WordPress/gutenberg/pull/36940

It only adds the default name for new colors so far, but I can look at validation and onHover effect mentioned in https://github.com/WordPress/gutenberg/issues/36473#issuecomment-971493346 as well.

**Comment by ramonjd** [comment]
> Another important thing I would add right away is the hover state for the input fields when they aren't active:

Getting the hover state width right is difficult since the input width, when editing, is constrained by the minus button.

The minus button isn't rendered when the item isn't in editable mode.

Getting it this far required a minimal change however:

![Kapture 2021-12-01 at 13 49 47](https://user-images.githubusercontent.com/6458278/144163120-f1c8a961-3f19-4bc1-b83a-d21792ebbfc1.gif)
