### ISSUE TITLE
Inaccurate PHP notice in WP_Block_Type_Registry::register when $name is a path

### ISSUE THREAD

**Issue by pdewouters** [WordPress/gutenberg#36487]
### Description

When I use `register_block_type( __DIR__, ...)` to register a block, a PHP notice is thrown `PHP Notice:  WP_Block_Type_Registry::register was called <strong>incorrectly</strong>. Block type names must not contain uppercase characters.` if the path calculated by `__DIR__` contains uppercase letters. This doesn't seem right. A potential fix would be to make the check smarter ( detect if it's `$name` is a valid path?)

### Step-by-step reproduction instructions

Register a block using snippet below, in an environment that will have an uppercase letter in the path, e.g. `/Users/...`, this happens on a local install on a mac

### Screenshots, screen recording, code snippet

```
	register_block_type_from_metadata( __DIR__, [
		'render_callback' => function( array $attributes ) : string {
			ob_start();
			include __DIR__ . '/template.php';
			return ob_get_clean();
		},
	] );
```

### Environment info

WP 5.8.1
Does not have standalone Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@ryanwelcher not sure if you have some insights to share here?

**Comment by ryanwelcher** [comment]
@pdewouters what are the contents of the block.json file you are using for this example? I'm going to see if I can reproduce this locally.

**Comment by ryanwelcher** [comment]
Just wanted to follow up on this @pdewouters. I have been able to reproduce this error only when the path didn't exist - which based on your example is not the same steps to reproduce. There does seem to be a case where the validation fails to see that there is an issue with the path when using the `register_block_type_from_metadata` function - https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/blocks.php#L227

**Comment by pdewouters** [comment]
Ok, it seems that the issue might've resolved itself for now. I can't reproduce it anymore.

**Comment by ryanwelcher** [comment]
Thanks for the follow up!

**Comment by charlesdeb** [comment]
I had the same issue. I got this error message about upper case names (and my whole path did indeed include upper case names) when in actual fact as @ryanwelcher also experienced, I was trying to register a block to a path that didn't exist. Once I fixed that, then the error disappeared - even though my whole path still did include upper case characters.
