### ISSUE TITLE
Click to ->Editor (Beta) or ->Styles nothing happens

### ISSUE THREAD

**Issue by agatheschmidkoenig** [WordPress/gutenberg#36482]
### Description

I've installed the similar Theme and Gutenberg at two different hosting platforms. On one platform the **editor** and the **styles** don't work at all - allthough the website-conditions seems to be pefect, see below.

[my first issue, forbearance please]

### Step-by-step reproduction instructions

Got to Dashboard
Click to Design
Click to Editor (Beta) / Click to Styles

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/86146526/141749353-3a3b869b-8697-4db1-82ea-b26c48d9bb81.png)
![image](https://user-images.githubusercontent.com/86146526/141749447-9acf2de4-77aa-4c4a-b444-a1612ca6be09.png)

### Environment info

Latest WordPress, Latest Gutenberg, Aino (I changed the Theme into "twentytwentyone", which makes no difference)
Chrome/Edge
Desktop

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Hi @agatheschmidkoenig! Thanks so much for both testing this out and for filing your first issue. I tried to replicate this but am not able to. By chance, can you try deactivating all other plugins except Gutenberg and trying again? I can see in the screenshots you shared that other plugins are activated so it would be helpful to rule those out first :)

**Comment by agatheschmidkoenig** [comment]
Thank you so much for your answer (unfortunately i made the shoots above too early, although i testet after that with turned-off-plugins). Anyway after the latest gutenberg-release now there appears nothing more than white - hmmm, formerly there still was the side-bar. But still this non-working is just at one of my two hosting-platforms. Please let me know if i kann add further information. ;-)
![Screenshot 2021-11-18 111140](https://user-images.githubusercontent.com/86146526/142407141-84ad7128-fb4b-490f-88af-979659ed5b50.png)
![Screenshot 2021-11-18 111221](https://user-images.githubusercontent.com/86146526/142407144-d40f8348-a870-4d60-950b-d265a9e2f913.png)

**Comment by annezazu** [comment]
That's so strange. Do you see any browser errors? Thank you for following up <3

**Comment by agatheschmidkoenig** [comment]
It is really strange and I tested lots, as good as I can do that…
One is different in the browser:
**at-non-working-host:** .../wp-admin/themes.php?page=gutenberg-edit-site
**at-working-host:**…wp-admin/themes.php?page=gutenberg-edit-site&postId=15&postType=page
Thanks for answering. I hope it is simple.

**Comment by agatheschmidkoenig** [comment]
I will now follow another similar issue, seems to be a widerspread poblem. Thanks so far!

**Comment by annezazu** [comment]
Sounds good!
