### ISSUE TITLE
Improvements to pattern loading

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#36491]
I'd like to suggest a couple of refinements for the Patterns feature. They are a bit related, so that's why I'm submitting them together:

1. Improve the apparition of patterns on the sidebar and the Explore modal using spinners or a loading state. We are loading the patterns immediately, and they look a bit rough and glitchy. 

https://user-images.githubusercontent.com/4933/141802278-479d76d0-80ae-47e2-9924-e8c1506faa00.mov

2. When the Explore modal is open, the patterns in the sidebar disappear for no reason, which means that when the modal is closed, we have to load the patterns again and we get the rough loading state I mentioned before. In the following video, I open the modal and close it with the escape key.

https://user-images.githubusercontent.com/4933/141803865-f5e0deef-4461-472c-938b-050fc4088751.mov

**Comment by jameskoster** [comment]
Possibly related – https://github.com/WordPress/gutenberg/issues/35503

**Comment by jordesign** [comment]
The current state of the Pattern inserter is such that the issues mentioned here are no longer in place - closing this issue accordingly.

If there are similar concerns about the _current_ state of the pattern inserter, they can be raised in a new issue.
