### ISSUE TITLE
Navigation block view script JS console error

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#36506]
### Description

In WordPress 5.9 trunk, with Twenty Twenty-Two theme, the navigation block view script does not use the correct URL.

This may be related to returning `false` on the `$is_core_block` check in [blocks.php](https://github.com/WordPress/wordpress-develop/blob/c3222105d83cca007b0e9ab583c9f4ed6643d166/src/wp-includes/blocks.php#L103-L106).

### Step-by-step reproduction instructions

1. Update to the latest WordPress trunk.
2. (Install and) activate the Twenty Twenty-Two theme.
3. View the site (front end).
4. Open the browser console to view errors, or else view source and search for the `wp-block-navigation-view-js` script.

### Screenshots, screen recording, code snippet

![navigation block view script error](https://user-images.githubusercontent.com/17100257/141944199-34251096-3bc8-44a7-8e5e-4b6dfa1debb7.png)

### Environment info

- WordPress 5.9 trunk (r52178), without Gutenberg plugin
- Firefox 94, Chrome 95
- Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mkaz** [comment]
🤔 I can not duplicate, I'm not sure if it is environment or with WP.

I checked out trunk from: https://github.com/WordPress/wordpress

Running latest without plugin, and it includes this JS file:

```
<script type='text/javascript' src='http://localhost:8003/wp-includes/blocks/navigation/view.min.js?ver=4942262e50480536aae4cd504a13f19c' id='wp-block-navigation-view-js'></script>
```

The link you have to blocks.php does seem like the right spot, because looking at the path it is trying to pull in your error, it is the full file system path, so it is not doing the replacement part.

It looks like it determines if it is a core block if the `block.json` metadata file starts is located within the WP_INC directory, which should be the case, which makes me think it is a Windows path issue of some sort. I'm trying to test on Local now.

**Comment by mkaz** [comment]
ok, I can duplicate this now using Local on Windows. I'll see if I can dig into more why.

**Comment by chthonic-ds** [comment]
I'm not sure if the diagnosis in https://github.com/WordPress/gutenberg/issues/33273#issuecomment-876965582 is correct, but  there was a similar script path issue in earlier releases of Gutenberg, too.

**Comment by mkaz** [comment]
Good find @chthonic-ds thank you, that is the same issue. Working on a fix now.

I just confirmed in my test environment that:

 `ABSPATH . WPINC` => `C:/Users/marcu/Local Sites/wpbeta/app/public/wp-includes`

and

`$metadata['file']` => `C:\Users\marcu\Local Sites\wpbeta\app\public\wp-includes\blocks/navigation/block.json`

So the conditional check fails.

**Comment by mkaz** [comment]
I can't find the code in Gutenberg plugin, I'm not quite sure how it was migrated.
I created a ticket and patch with a fix on Trac at: https://core.trac.wordpress.org/ticket/54456

**Comment by carolinan** [comment]
The patch in the trac ticket is merged, can this be closed?

**Comment by sabernhardt** [comment]
The Trac change works for me.
