### ISSUE TITLE
Navigation area block uses same icon as template part block

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#36501]
### Description

Currently the Navigation Area block uses the same `symbolFilled` icon as the template part (if it isn't a header or footer variation).

I imagine it'd be a good idea to differentiate the two, especially in the inserter and list view:
<img width="221" alt="Screenshot 2021-11-16 at 9 54 48 am" src="https://user-images.githubusercontent.com/677833/141881530-3409378b-58fa-4676-99a9-0fbd3389b590.png">

### Step-by-step reproduction instructions

1. Open the inserter, search for Navigation Area and observe the icon
2. Search for Template Part and observe the icon, it's the same 😱 

### Please confirm that you have searched existing issues in the repo.

Yes, No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
Should it be the same as the navigation icon, or a variant of it?

<img width="232" alt="Screen Shot 2021-11-18 at 8 56 04 am" src="https://user-images.githubusercontent.com/6458278/142288821-22248bce-061f-460e-a48e-52d8fd7976ad.png">

I can't see anything in the [available icons](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library) that would be the perfect substitute.

Something like submenu might be okay?

<img width="251" alt="Screen Shot 2021-11-18 at 8 49 52 am" src="https://user-images.githubusercontent.com/6458278/142289058-eb19c869-c80b-4e81-a4f5-0f6be09b2fa8.png">

**Comment by talldan** [comment]
Lets hold off on this, as it looks like this block might be removed - #36524.
