### ISSUE TITLE
Page List block shows loading state often, doesn't seem to cache page data

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#36502]
### Description

The page list block doesn't seem to cache the data it uses. When editing I notice it shows a loading spinner regularly, even if the data is unchanged.

Usually requests to the REST API via the core-data package's API (e.g. `getEntityRecords`) are cached, so I wouldn't expect this problem.

### Step-by-step reproduction instructions

1. Add a page list block and observe the loading spinner
2. Add a second page list block and observe the loading spinner again, even though the data is the same as the first block
3. Open dev tools to the network tab
4. Add more page list blocks, observe that each block makes an identical request to the REST API when it could rely on cached data.

### Environment info

- WordPress `trunk`
- Gutenberg `trunk`
- Brave on Mac OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
The block uses `apiFetch` instead of the entity selectors.

**Comment by talldan** [comment]
> The block uses apiFetch instead of the entity selectors.

I wonder why, I couldn't see any discussion about it on https://github.com/WordPress/gutenberg/pull/31670.

@noisysocks @georgeh any recollection?

**Comment by georgeh** [comment]
Sorry I don't recall the specifics of why it's using apiFetch. Looking at the diff, I would guess it's because the existing code was already using apiFetch.

**Comment by Mamaduka** [comment]
Thanks for the clarification, @georgeh.
