### ISSUE TITLE
Stabilize Site Editor export endpoint

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#36515]
The `wp-json/__experimental/edit-site/v1/export` endpoint needs to be stabilized and included in WP core.

Originally reported on Trac: https://core.trac.wordpress.org/ticket/54448

**Comment by Mamaduka** [comment]
@TimothyBJacobs Should we also extend `WP_REST_Controller` for this REST API?

**Comment by TimothyBJacobs** [comment]
I think that would be good yeah. While this is a simple route we don't have any other "free standing" routes in Core.
