### ISSUE TITLE
Fix confusing ellipsis menu for the Custom Color Palette feature

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#36519]
### Description

The ellipsis that appears in the Color Palette section of the Global Styles is very confusing and doesn't have consistent behavior.

When you reach the panel, the ellipsis behaves like a button that allows editing the custom colors. This behavior is not the default one for this kind of element.

https://user-images.githubusercontent.com/4933/141981925-712927b9-e330-4b8e-b84a-2c95ebaf17f0.mp4

It's only when you are in that editing state, that the ellipsis menu acts as a button that reveals a menu with an option to remove custom colors. This means that in order to discover that functionality, the user needs to click on a button that previously did something totally different. 

<img width="274" alt="Screenshot 2021-11-16 at 13 04 09" src="https://user-images.githubusercontent.com/4933/141982221-fab0dd52-630e-47da-b25b-63bfb31a0782.png">

### What is your proposed solution?

We should probably redesign this section since there are some usability problems (see for example [this one](https://github.com/WordPress/gutenberg/issues/36473)), but in the meantime, I suggest fixing this problem by doing the following:

The ellipsis button should reveal a menu with two options:

- Edit custom colors
- Remove all custom colors

If the user is editing the colors, the first option should be disabled and/or indicate that they are inside that mode.

Also, since the remove functionality is destructive, we should probably add a prompt to confirm the action.

### Step-by-step reproduction instructions

1. Open the Global Styles sidebar.
2. Click Colors. 
3. Click Palette.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jiteshdhamaniya** [comment]
I’d just start working on a PR.

**Comment by glendaviesnz** [comment]
> I suggest fixing this problem by doing the following:
> The ellipsis button should reveal a menu with two options:
> Edit custom colors
> Remove all custom colors

@javierarce  I have [added a PR](https://github.com/WordPress/gutenberg/pull/36842), so we can explore how your suggestion works in practice.

**Comment by glendaviesnz** [comment]
@javierarce with #36842 merged are you happy for this issue to be closed?

**Comment by javierarce** [comment]
> @javierarce with #36842 merged are you happy for this issue to be closed?

Yes, I think we can close it. This part of the UI still needs a lot of work to improve, but your fix solved the awkwardness I reported. Thanks for fixing it!
