### ISSUE TITLE
Request: Block themes: link 'Customize' button to FSE 'Styles' instead of the old customizer

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#36512]
## What problem does this address?

When activating a block/FSE theme in Appearance > Themes, the 'Customize' button links to the old classic Customizer.

As this is not applicable to a block theme, this button would be better if it takes the user to the Site Editor or 'Styles' when activating a block theme.

Not too sure whether this would be a Gutenberg enhancement or core WP.

**Comment by annezazu** [comment]
Duplicate of this: https://github.com/WordPress/gutenberg/issues/30643

Thank you for opening though!

**Comment by Sandstromer** [comment]
Thank you for pointing me to the original issue. Guess I didn't look back far enough!
