### ISSUE TITLE
Using a user edited/created page template creates a duplicate viewport meta

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#36528]
### Description

This is an odd one. If you assign a theme-provided custom page template to a page, the frontend output looks roughly like this. 

![image](https://user-images.githubusercontent.com/4832319/142032474-9b766e43-62a0-4cfb-aa3f-66fdfa00dde9.png)

If you then edit the template in WordPress (not in the theme files) and save, the frontend output now has a duplicate meta viewport tag.

![image](https://user-images.githubusercontent.com/4832319/142032629-e3335f32-8354-47d1-a5fe-72c829367337.png)

You get the same output if you create a new page template from within the Block Editor. 

The issue can be easily reproduced with the Twenty Twenty-Two theme, but has been reproduced in a number of other themes including emptytheme. 

I am happy to explore further and work on a fix, but I am not sure where to start looking. If someone can point me to where the frontend output for templates "lives", I will take a look. 

### Step-by-step reproduction instructions

1. Install the latest version of Twenty Twenty-Two
2. Add a new page and give it the template "Page (No Separators)" and publish.
3. Look at the frontend markup and you will see only one meta viewport tag. 
4. Now from within the Block Editor, make a change to the "Page (No Separators)" and save it. 
5. Now refresh the page on the frontend and you will now see the duplicate meta viewport tags. 

### Environment info

WordPress 5.8.2, Gutenberg 11.9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Looks like it could be the same issue as reported here - https://core.trac.wordpress.org/ticket/53743

**Comment by ndiego** [comment]
Yeah that looks like it's the same issue.

**Comment by carolinan** [comment]
This PR included the solution for the title tag: https://github.com/WordPress/gutenberg/pull/36133
But more testing is needed to see if this is still an issue in 5.9 beta.

**Comment by carolinan** [comment]
Yes, still an issue on 5.9 beta 3 with Gutenberg trunk. When Gutenberg is not active, the tags are not duplicated.

**Comment by kafleg** [comment]
WordPress: 5.9 Bets
Gutenberg: Trunk Version Activated
Theme: TT2

![image](https://user-images.githubusercontent.com/13062231/146879151-feb70e08-58d1-4131-a1d9-ea66d09aec0d.png)

when Gutenberg is not activated,
WordPress: 5.9 Bets
Gutenberg: Not activated
Theme: TT2
![image](https://user-images.githubusercontent.com/13062231/146879340-b0bb2ca1-c856-44d7-b358-7e7a0ab0f718.png)

**Comment by kafleg** [comment]
Tested with Beta 4 as well, the issues is still there.

```
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
```

**Comment by bgardner** [comment]
Bumping as this is still a present issue.

**Comment by ndiego** [comment]
This no longer seems to be an issue in the latest version of WordPress, Gutenberg and with TT3.
