### ISSUE TITLE
Make it easier to unselect blocks

### ISSUE THREAD

**Issue by kellychoffman** [WordPress/gutenberg#36535]
Make it easier to unselect blocks. 

- [x] Pressing escape in Select mode unselects blocks (https://github.com/WordPress/gutenberg/pull/36945)
- [x] Clicking on anything that is not a block or UI element unselects blocks
- [x] Consider adding the frame from template part focus mode (https://github.com/WordPress/gutenberg/pull/36995)

**Comment by jasmussen** [comment]
Clicking the top-level breadcrumb deselects. Two other ideas for improvement:

1. Address #5803 and let clicking _below_ the blocks deselect, instead of create a new paragraph block. Could potentially be easy as it mostly disables code that intercepts it. Downside, it's mainly benefitting the post editor.
2. Escape enters select mode. We could make it so pressing Escape again deselects all blocks.

**Comment by shaunandrews** [comment]
> Escape enters select mode.

I suggest we rethink this shortcut; It doesn't really work when you have nested blocks, as you can't go into or out-of a container block. To me, it makes much more sense for `esc` to deselect all blocks, and to find a different shortcut for (and generally improve) Select mode.

Outside of that, I also think that if you click anywhere that isn't a block or a UI element that it should deselect all blocks. For example, if I click on the blank space (highlighted in yellow) in the top bar I expect that it would unselect all blocks:

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/191598/142064436-a432f82b-f50a-4688-a286-b10c8fe82a28.png">

**Comment by talldan** [comment]
> I suggest we rethink this shortcut; It doesn't really work when you have nested blocks, as you can't go into or out-of a container block. To me, it makes much more sense for esc to deselect all blocks, and to find a different shortcut for (and generally improve) Select mode.

It does work using arrow keys. I think the click-through overlay that template parts have is interfering with being able to select children. Maybe that shouldn't be active in select mode.

I understand the point though, escape does feel a lot more natural as a key for deselecting things, and I hear that a lot more computers have escape keys these days 😄

**Comment by noisysocks** [comment]
> Escape enters select mode. We could make it so pressing Escape again deselects all blocks.

I'm very fond of how [Craft](https://www.craft.do) handles this. If you're typing, <kbd>Esc</kbd> enters select mode. If you're in select mode, <kbd>Esc</kbd> deselects all blocks.

https://user-images.githubusercontent.com/612155/142137137-395dc2a3-a95b-402b-9b0b-4463c6c53f15.mp4

When you combine this with <kbd>Enter</kbd> to edit a block and <kbd>Shift</kbd>+<kbd>Space</kbd> for _Insert Before_ and <kbd>Space</kbd> for _Insert After_ it's all quite powerful.

https://user-images.githubusercontent.com/612155/142137419-49256321-b2dd-4f3f-b478-31653583a50d.mp4

> Outside of that, I also think that if you click anywhere that isn't a block or a UI element that it should deselect all blocks. For example, if I click on the blank space (highlighted in yellow) in the top bar I expect that it would unselect all blocks:

Agree. This trips me up a lot. It should work when you click on whitespace in the sidebar, too.

**Comment by jameskoster** [comment]
While keyboard shortcuts can help make it easier to deselect blocks, they are not very discoverable. I'm not convinced that folks should be forced to rely on this, shouldn't there should be a more ergonomic mechanic?

It many software deselection is facilitated by clicking empty space. The problem in the Site Editor of course is that blocks at the root level generally span the full width of the layout meaning there is no empty space to click.

We circumvented this in template part focus mode by making clicks in the dark grey area deselect blocks which (imo) feels natural:

https://user-images.githubusercontent.com/846565/142190442-e01c1d23-8dfa-4070-8157-a68e7ec68f74.mp4

Perhaps there's a case to be made for introducing this frame to the site editor as well?

**Comment by shaunandrews** [comment]
> I think the click-through overlay that template parts have is interfering with being able to select children. Maybe that shouldn't be active in select mode.

Ah, maybe that's a bug then, because in the site editor select mode with arrows _feels_ broken.

> I'm very fond of how Craft handles this.

We can definitely learn a lot from Craft. The way it handles edit/select modes is intuitive and also more abstract from a UI perspective; There are no buttons or anything for triggering modes, just a natural feeling combination of key commands.

> It should work when you click on whitespace in the sidebar, too.

I considered it at first, but I don't think its a good idea for the whitespace in the sidebar to unselect a block. It would likely be _too_ easy to unselect a block while you're actively editing it's settings in the sidebar.

> Perhaps there's a case to be made for introducing this frame to the site editor as well?

I believe the frame really only makes sense at larger viewport sizes; If we do add the frame we should be sure its not the only way to unselect all blocks. I don't think the frame makes much sense in the context of the post editor.

--

As I see it, next steps here are to open PR's that do the following:

- Unselect all blocks when clicking whitespace in the top bar.
- Add the frame around the canvas in the site editor.
- Map `esc` to unselecting blocks in select mode.
- Map `esc` to unselecting blocks in edit mode, and map a new key to select mode.

Then from those PR's we can see what works and what doesn't.

**Comment by jasmussen** [comment]
Good list, Shaun.

> Map esc to unselecting blocks in edit mode, and map a new key to select mode.

If Escape deselects blocks, we can use any key without modifiers, such as `v` which in many apps is used for the Arrow/select tool.

That said, this could be a big change, and so if we need an interim step, we could just start with just this one:

> Map esc to unselecting blocks in select mode.

With this in, you'd press Esc Esc (twice) to deselect.

**Comment by jameskoster** [comment]
> I don't think the frame makes much sense in the context of the post editor.

Agreed. It's worth noting that this issue is much less prevalent in that context as there is generally plenty of empty space to click:


https://user-images.githubusercontent.com/846565/142250239-cefb4042-f7f9-4418-8cb9-4f4fc247b80f.mp4

**Comment by noisysocks** [comment]
What action is required here?

**Comment by jasmussen** [comment]
Seems like the remaining piece is being able to click empty spots, for example in the header, to deselect blocks, a la [Shaun outlined here](https://github.com/WordPress/gutenberg/issues/36535#issuecomment-970672323).

**Comment by mtias** [comment]
@noisysocks I don't think what is pending is a must-have for 5.9, feel free to punt

**Comment by annezazu** [comment]
Looping back here as it wasn't clear where we left off. Using GB 14.4 on 6.0.3 shows the following:

- [ ] Unselect all blocks when clicking whitespace in the top bar.
- [x] Add the frame around the canvas in the site editor > I don't see this happening based on current designs
- [x] Map esc to unselecting blocks in select mode > this seems to work. 
- [ ] Map esc to unselecting blocks in edit mode, and map a new key to select mode

Here's a quick video of mapping escape to select mode in case I'm misunderstanding:

https://user-images.githubusercontent.com/26996883/198488254-be759956-3d43-4a6d-8dc4-919d0f444ebe.mov

**Comment by jasmussen** [comment]
Created https://github.com/WordPress/gutenberg/issues/47172 which would also affect this issue: press Escape twice to deselect and remain in edit mode.

**Comment by jordesign** [comment]
All these cases are now resolved in my testing - so will mark this issue as closed.
