### ISSUE TITLE
Global Styles: improvements to color picker design

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#36542]
## What problem does this address?

Currently, the color picker opens over top of the rest of the color palette obscuring the ability to see the entire set of colors:

<img width="414" alt="Screen Shot 2021-11-16 at 2 17 41 PM" src="https://user-images.githubusercontent.com/26996883/142051532-111503c4-c27f-490c-b8f0-02ec3d65a54c.png">

Additionally, the target design doesn't have any padding.

## What is your proposed solution?

- [ ] Move the color picker to the left of the sidebar to provide a clearer editing flow.
- [ ] Remove padding.

**Comment by mtias** [comment]
The target design reference:

![image](https://user-images.githubusercontent.com/548849/142059422-74cd1aee-0729-4b2a-87a3-03347f4200c7.png)

**Comment by oandregal** [comment]
Added a comment/tasks to also remove the padding from the existing component, so it matches the target design.
