### ISSUE TITLE
Color palette: Design updates

### ISSUE THREAD

**Issue by kellychoffman** [WordPress/gutenberg#36543]
Suggested improvements for 5.9

- [x] Add borders to the colour circles in the palettes (so the white color is seen).
- [x] #36542 
- [ ] Reposition the “Reset” button  (#36519)
- [x] Never show “core” to a user, use “default” instead. https://github.com/WordPress/gutenberg/pull/36622
- [x] Palettes should be reordered by theme, default, user. https://github.com/WordPress/gutenberg/pull/36622
- [x] In the styles sidebar, in the color submenu, in the uncommon event there are no colour palettes (see image below), there should be an indicator or CTA so that users don’t need to manually navigate deep into the menus to add colours. https://github.com/WordPress/gutenberg/pull/36684
- [x] The counter should count all the colors (default, theme, custom) and not only custom.
- [x] Show gradients and allow to edit them.
- [x] Show duotones (not editable yet).
- [x] Call them "palettes" not "color palettes".

PR for this started here: https://github.com/WordPress/gutenberg/pull/36243

**Comment by kellychoffman** [comment]
Reference image for when there is no color palettes:

![image](https://user-images.githubusercontent.com/27339341/142053654-7a84cda1-f534-472b-b4f6-a97cdb40e957.png)

**Comment by mtias** [comment]
And the target design reference:

![image](https://user-images.githubusercontent.com/548849/142059179-6c585456-982b-48b6-943f-453f48219d47.png)

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/36622 fixed _Never show “core” to a user, use “default” instead_ and _Palettes should be reordered by theme, default, user_.

Note that the mockups use "Custom" instead of "User" so I did that as well.

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/36684 to address the CTA for when there's no colors has been merged.

**Comment by oandregal** [comment]
Added a few tasks that I've seen missing from the mockups or that folks suggested upon reviewing this component:

- The counter should count all the colors (default, theme, custom) and not only custom.
- Show gradients and allow to edit them.
- Show duotones (not editable yet).
- Call them "palettes" not "color palettes".

**Comment by mtias** [comment]
@noisysocks I'm marking this as done as all the important items are covered. The rest button is not a must have and will be part of general improvements to the color panel.
