### ISSUE TITLE
Information icon is not intuitive and "information" is not clear ( it gives stats

### ISSUE THREAD

**Issue by ElectricFeet** [WordPress/gutenberg#3655]
## Issue Overview

When editing a page with Gutenberg, there is a bank of icons in the top left of the page.

<img width="459" alt="screen shot 2017-11-25 at 19 42 28" src="https://user-images.githubusercontent.com/6003638/33233606-df59d054-d218-11e7-9a64-0067181a29b2.png">

The 4th from the left is an icon that is normally associated with the concept of "pages", or (sometimes) "making a copy". 

<img width="40" alt="screen shot 2017-11-25 at 20 07 06" src="https://user-images.githubusercontent.com/6003638/33233798-3e0321ac-d21c-11e7-856f-1d3aa857b087.png">

Yet hovering gives a tooltip of "information". Clicking it gives page statistics.

The icon is not intuitive (**problem 1**) and the tooltip is not intuitive (**problem 2**). 

### Solution to problem 1
The icon should be replaced with an icon that is generally accepted to mean "information", or &mdash; even better &mdash; "statistics". In the current dashicons set, the following are more intuitive:
<img width="50" alt="screen shot 2017-11-25 at 19 56 52" src="https://user-images.githubusercontent.com/6003638/33233804-5bbba282-d21c-11e7-868a-6adca9951a89.png">
<img width="46" alt="screen shot 2017-11-25 at 19 57 20" src="https://user-images.githubusercontent.com/6003638/33233805-5eef2f78-d21c-11e7-856c-ddb2bb0ebbe0.png">

I prefer the first, though I realise that the "i" for information may not be intuitive in all languages, hence proposing the 2nd. Maybe a new dashicon is needed. 

### Problem to problem 2
The tooltip should be changed from "Information" to "Page information" or (better) "Page statistics" (or "Page analysis").

## Steps to Reproduce (for bugs)

1. Edit a page with Gutenberg plugin activated;
2. Hover / click on 4th icon from left.

**Comment by chthonic-ds** [comment]
Looks like this has been addressed in #3563.

**Comment by afercia** [comment]
Yep the icon has already been changed on master:

![screen shot 2017-11-26 at 13 54 19](https://user-images.githubusercontent.com/1682452/33240139-84001422-d2b1-11e7-8efb-3b59f30f9175.png)

The tooltip text could be improved a bit. Worth considering it is about "statistics" but also about the Table of Content. Ideally, a better wording should inform about both the counts and the ToC, and be _short_ enough:

![screen shot 2017-11-26 at 13 57 51](https://user-images.githubusercontent.com/1682452/33240157-f2b7c59a-d2b1-11e7-837e-2941744f0e22.png)

Aside: I'm not sure the paragraph count is of any use.

**Comment by ElectricFeet** [comment]
Great! :-)

I didn’t spot that there was also TOC info in there. That would indeed influence the tooltip text.

“Page structure”  [or “Post structure”, depending] would do it, perhaps.

As to being short: remember that when localized, it may no longer be short.

Paragraph count is useful, especially in relation to number of headings to break them up, so I’d keep it. Less importantly 4 stats balance out nicely: 3 stats would be less visually pleasing :)

I’m only at the beginning of my Gutenberg journey; I’ll try to flag up more problems as I find them. But I have to say, I like writing on Github’s interface more than Gutenberg. Maybe there’s some good practice to follow here.

**Comment by afercia** [comment]
> Less importantly 4 stats balance out nicely: 3 stats would be less visually pleasing 

Yeah I know, but that's really the last reason why we should add content 🙂

**Comment by mtias** [comment]
Going to close this as the main subject has been addressed. Thanks for the feedback!
