### ISSUE TITLE
Overview of WP 5.9 pending issues and blockers

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#36556]
# 👋 This list has served its purpose. Head over to the [WordPress 5.9 Must-Haves](https://github.com/WordPress/gutenberg/projects/62) project board to see block editor tasks for WP 5.9.

---

_Last updated: 14 December 2021_

🔺 Blocker for 5.9 Beta (_must_ be fixed before Beta1)
⚠️ Blocker for 5.9 Release (_can_ be fixed after Beta1, _must_ be fixed before RC preferably by Beta 4 to ensure included in a beta release)
🧪 Needs testing and feedback

The issues within each section are ordered by priority; contributors are welcome to pick issues from top to bottom in their area of expertise/interest.

## Site editing experience
- [x] https://github.com/WordPress/gutenberg/issues/37075 🧪
- [x] https://github.com/WordPress/gutenberg/pull/36379 🔺
- [x] https://github.com/WordPress/gutenberg/pull/36592 🔺
- [x] https://github.com/WordPress/gutenberg/issues/36597 ⚠️
- [x] [Ensure links to the Customizer send users to an appropriate destination in 5.9](https://core.trac.wordpress.org/ticket/54460) ⚠️
- [ ] [Update the Dashboard welcome banner for 5.9](https://core.trac.wordpress.org/ticket/54489) ⚠️
- [x] https://github.com/WordPress/twentytwentytwo/pull/243 ⚠️

## General interface

- [x] WordPress/gutenberg#36037 ⚠️
- [x] https://github.com/WordPress/gutenberg/pull/36605 ⚠️
- [x] https://github.com/WordPress/gutenberg/issues/36594 ⚠️

## Navigation block

- [x] https://github.com/WordPress/gutenberg/issues/36502 ⚠️
- [x] https://github.com/WordPress/gutenberg/pull/36727 ⚠️
- [x] https://github.com/WordPress/gutenberg/issues/36721 ⚠️
- [x] https://github.com/WordPress/gutenberg/pull/36591 ⚠️
- [x] https://github.com/WordPress/gutenberg/issues/36286

## Global styles & Design tools

- [x] https://github.com/WordPress/gutenberg/pull/37038 ⚠️
- [x] https://github.com/WordPress/gutenberg/issues/36543 ⚠️
- [x] https://github.com/WordPress/gutenberg/issues/36644 ⚠️

## Theme blocks

- [x] https://github.com/WordPress/gutenberg/issues/36136 ⚠️
- [x] https://github.com/WordPress/gutenberg/issues/30669 ⚠️ 
- [x] https://github.com/WordPress/gutenberg/issues/30668 ⚠️
- [x] https://github.com/WordPress/gutenberg/issues/36547 ⚠️

<details>

<summary>Non-blockers</summary>

## Site editing experience
- [x] https://github.com/WordPress/gutenberg/issues/36354
- [x] #36589
- [x] https://github.com/WordPress/gutenberg/issues/36530
- [ ] [Add an option to configure the site icon in general settings](https://core.trac.wordpress.org/ticket/54370)
- [x] https://github.com/WordPress/gutenberg/issues/37056

## General interface

- [x] https://github.com/WordPress/gutenberg/issues/35536

## Navigation block

- [x] https://github.com/WordPress/wordpress-develop/pull/1944
- [x] https://github.com/WordPress/gutenberg/issues/36593
- [x] https://github.com/WordPress/gutenberg/issues/36634
- [x] https://github.com/WordPress/gutenberg/issues/36722

## Global styles & Design tools

- [x] https://github.com/WordPress/gutenberg/issues/36546
- [x] https://github.com/WordPress/gutenberg/issues/36542
- [x] https://github.com/WordPress/gutenberg/issues/36473
- [x] https://github.com/WordPress/gutenberg/issues/36519
- [x] https://github.com/WordPress/gutenberg/issues/36640
- [x] https://github.com/WordPress/gutenberg/issues/36641
- [ ] https://github.com/WordPress/gutenberg/issues/36521

## Block themes

- [x] https://github.com/WordPress/gutenberg/issues/36548
- [x] https://github.com/WordPress/gutenberg/pull/36571
- [x] https://github.com/WordPress/gutenberg/issues/24834
- [ ] https://github.com/WordPress/gutenberg/issues/35607

## Theme blocks

- [x] https://github.com/WordPress/gutenberg/issues/36536 
- [x] https://github.com/WordPress/gutenberg/issues/30910

</details>

**Comment by Addison-Stavlo** [comment]
>Site Editor and site editing workflows
 Add templates list page for site editor #36379
 [FSE] Update "Customize" link from Appearance > Theme page for block themes #30643
 Move Theme Editor to Tools when a block theme is active #36354
 [Block Themes] Consider an FSE-compatible approach to starter content #35680
 Add a timeout for the in-between-inserter for cases where the onmouseout isn't invoked #35536
 Make it easier to unselect blocks #36535
 Select mode: Broken icons #36530
 Make the UI more clear when you are editing a template part #36533
 
I think there are some large red flags here that some things are not ready for 5.9.  Especially re-creating the entire post list for templates / template parts at the last minute.  Don't we want to give new flows ample testing in Gutenberg to ensure they are refined and the desired solution before including them in a core release?  We once thought the Nav Panel was a desired solution, imagine if we had shipped that to core WP just days after it had been developed.  We would be regretting it now. 

Overall, it seems like right now we are rushing things in a dangerous way.  We targeted 5.9 as the release for these items in core but too many things are just not ready, hence the rushing to change so many things at the last minute.  Wouldn't it be better to miss the expected target date than to rush potentially regrettable decisions and brand new flows into core WP at the last minute?

**Comment by oandregal** [comment]
Added a couple of bugs I ran into for the color component

https://github.com/WordPress/gutenberg/issues/36640
https://github.com/WordPress/gutenberg/issues/36641

**Comment by briceduclos** [comment]
Can this issue be added to the list: [The Group block's layout defaults break existing content #36057](https://github.com/WordPress/gutenberg/issues/36057). (it's inside the WordPress 5.9 Must-Haves project)

**Comment by stacimc** [comment]
Should [Add an option to configure the site icon in general settings](https://core.trac.wordpress.org/ticket/54370) be included in this list? (Currently missing a discoverable way to update the site icon for blocks themes).

**Comment by noisysocks** [comment]
> Can this issue be added to the list: [The Group block's layout defaults break existing content #36057](https://github.com/WordPress/gutenberg/issues/36057). (it's inside the WordPress 5.9 Must-Haves project)

Let's use the [WordPress 5.9 Must-Haves board](https://github.com/WordPress/gutenberg/projects/62) for bugs. This list serves as a way to direct contributor focus _in addition_ to the project board.

> Should [Add an option to configure the site icon in general settings](https://core.trac.wordpress.org/ticket/54370) be included in this list? (Currently missing a discoverable way to update the site icon for blocks themes).

I've added this, though without a ⚠️ since there is a workaround.

**Comment by aristath** [comment]
>  FSE: Fall back to Top level PHP theme templates when no FSE templates are available #24834

Already done in https://github.com/WordPress/gutenberg/pull/29026 and further refined in https://github.com/WordPress/gutenberg/pull/31604

**Comment by mtias** [comment]
Thanks for checking @aristath, it was listed to ensure it got a proper look since it's been a while since it was worked on.

**Comment by noisysocks** [comment]
>  [Site Editor] Templates list screen overview #36597 ⚠️

I'm going to check this one off as the majority of the items in #36597 have been completed.

**Comment by mtias** [comment]
We can punt #36535, #36533, #36544.

**Comment by hellofromtonya** [comment]
Following the discussion https://github.com/WordPress/gutenberg/issues/37075#issuecomment-988329949, #37075 is no longer considered a blocker for 5.9. Can the ⚠️ be removed from its title and from the blockers list above? @noisysocks @priethor

**Comment by priethor** [comment]
#37075 is still considered a top priority, although we agree it should not jeopardize the release timeline. It is being addressed in #36488, and because Beta 2 is already out I think it's important to keep the ⚠️ and highlight it to get contributors to test it as much as possible.

**Comment by hellofromtonya** [comment]
>#37075 is still considered a top priority, although we agree it should not jeopardize the release timeline. It is being addressed in #36488, and because Beta 2 is already out I think it's important to keep the ⚠️ and highlight it to get contributors to test it as much as possible.

While I appreciate it as priority, ⚠️ is a flag that it blocks 5.9 RC. But that's not the case now. It's something to get into the release if possible, but it no longer a blocker to stop 5.9 RC from happening.

@priethor the list is already prioritized, right? Removing the ⚠️ lets everyone including the release squad, community, etc. know that this issue will not block 5.9 RC or its final release.

**Comment by priethor** [comment]
The list is prioritized but visual indicators are most useful. Since you are right about the non-blocking nature and the issue is already fixed by #36488 , I've added a different icon instead to denote testing is required. How does that sound?

**Comment by hellofromtonya** [comment]
I like that 🧪 emoji (will borrow it). Thank you @priethor for updating it!

**Comment by noisysocks** [comment]
I hid the non-blockers underneath a `<details>` since it's not realistic that we'll be looking at them now that we're past beta 3.

All that's remaining is https://core.trac.wordpress.org/ticket/54489 and https://github.com/WordPress/gutenberg/pull/37038.

**Comment by noisysocks** [comment]
I'm hearing feedback that it's confusing to have both this issue and the [project board](https://github.com/WordPress/gutenberg/projects/62). Given most of the items here are checked off, and the two remaining items are also in the project board, I'm going to close this out.

Let's work on closing out as many items as we can in the project board before RC 1.
