### ISSUE TITLE
Global Styles: Make Blocks section more distinguishable

### ISSUE THREAD

**Issue by kafleg** [WordPress/gutenberg#36569]
## What problem does this address?
At first please see this image,
![image](https://user-images.githubusercontent.com/13062231/142216575-7c16e428-c603-4bda-90a9-e756b4f026fd.png)

In the style section of blocks, there is a text named Blocks but it is clickable and can open block list. But, it's not appearing like button or clickable things. It simply display like text. We can make it even better to make it like button. 

## What is your proposed solution?
We can simply make it like button to give the outline to that text.

**Comment by annezazu** [comment]
Thanks for this idea! Rather than make it look like a button, I wonder if it would make more sense to give it an icon so it is similar to the other Global Styles options cc @kellychoffman. Going to add design feedback for now.

**Comment by kafleg** [comment]
That might be the best option!

**Comment by kafleg** [comment]
That might be the best option!

**Comment by kafleg** [comment]
That might be the best option!

**Comment by aristath** [comment]
@youknowriad should we do this in 5.9? It looks like an easy fix and a good enhancement... We'd just need a suitable icon 🤔

**Comment by youknowriad** [comment]
I'll defer to designers for this, I just followed the design from the initial issue. cc @mtias @pablohoneyhoney @jasmussen

**Comment by mtias** [comment]
The full design is not yet implemented:

![image](https://user-images.githubusercontent.com/548849/145366141-cd54a5ca-c8e9-48a5-97bf-80aaacde2c74.png)

Note the chevron, proximity to the descriptive text, etc.

**Comment by youknowriad** [comment]
@aristath I added to the 5.9 board, should be an easy one indeed.

**Comment by ramonjd** [comment]
> It looks like an easy fix and a good enhancement... We'd just need a suitable icon

In case the full design ([mentioned above](https://github.com/WordPress/gutenberg/issues/36569#issuecomment-989648889)) isn't ready or not implemented in time, I've added the default "block" icon as used in the BlockIcon component in this [PR](https://github.com/WordPress/gutenberg/pull/37313).

<img width="293" alt="Screen Shot 2021-12-13 at 12 25 08 pm" src="https://user-images.githubusercontent.com/6458278/145739044-05cb9d04-4819-414f-88b5-c0c7863d70b3.png">
