### ISSUE TITLE
Copy Paste text into tabel, inserts space before and after pasted text.

### ISSUE THREAD

**Issue by oldrup** [WordPress/gutenberg#36560]
### Description

I'm copying plain text into a table, and a space is inserted into the cell, before and after the pasted text. I then remove those spaces manually. Happens every time. It does not matter if I use Ctrl-C and Ctrl-V or use the context menu. 

Is anyone able to reproduce that?

### Step-by-step reproduction instructions

1) copy some text from a paragraph
2) insert text into a table cell
3) notice that space is added before and after the inserted text

### Screenshots, screen recording, code snippet

Made a boring screenrecording here: https://www.loom.com/share/561125ffd8974c3fad83bef5f844097f
Hopefully the spaces are "visible" - I try to select them to make clear what's going on.

### Environment info

WordPress 5.8.2
Firefox. Latest version-

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by oldrup** [comment]
I just learned, that if pasting using Ctrl-Shift-V in Firefox, extra spaces are _not_ added. Not sure what to make of this - I would expect regular pasting a word or sentence, only to include exactly what I copied (no extra spaces), but it's a viable workaround to me.

**Comment by ellatrix** [comment]
Could you share what the console is logging when you paste the text?

**Comment by jordesign** [comment]
I'm unable to recreate this in testing - @oldrup are you able to confirm whether this is still evident for you?

**Comment by oldrup** [comment]
Thank you all for taking the time to test this. I was unable to reproduce this anymore. Closing issue. 🥳
![image](https://github.com/WordPress/gutenberg/assets/17141205/b78daf32-a3a3-4456-a105-3bbc1e0f79ef)
