### ISSUE TITLE
Make it possible to unset a featured image via the block

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36566]
I think we should revert #27291.

It seems perfectly reasonable to offer folks a way to unset the featured image via the block itself. Otherwise one has to go into the post settings of the Inspector to do so. That might involve quite a journey if you're editing something like a query in the Index template! 

It would be much more convenient to do this via the block.

**Comment by Mamaduka** [comment]
I can create PR for this shortly if no one else is working on it.
