### ISSUE TITLE
Gutenberg should not save empty blocks 

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3657]
When clicking at the end of the post content area, a new block (by default a paragraph) gets added. While editing content it's very common to click on this area, even if the actual intent isn't necessarily adding new content.

As a user, I see just an empty block and I have no clue I'm supposed to manually remove it otherwise it will get saved in the content.

![screen shot 2017-11-26 at 13 25 53](https://user-images.githubusercontent.com/1682452/33239973-301d4882-d2ae-11e7-8aa4-913c437c1a7a.png)

Clicking multiple times, creates new blocks each time:

![screen shot 2017-11-26 at 13 24 50](https://user-images.githubusercontent.com/1682452/33239974-3e4703e4-d2ae-11e7-9cf2-5d2b55e3d2b6.png)

At the moment, Gutenberg doesn't remove them when saving, so these empty paragraphs get saved in the post content:

![screen shot 2017-11-26 at 11 56 45](https://user-images.githubusercontent.com/1682452/33239984-624d9a6e-d2ae-11e7-9067-98878d710472.png)
<img width="1056" alt="screen shot 2017-11-26 at 13 27 38" src="https://user-images.githubusercontent.com/1682452/33239985-6268f70a-d2ae-11e7-88ea-4ac23321d45e.png">

Of course, these empty paragraphs get printed out in the front-end.

**Comment by youknowriad** [comment]
closed by #3650 for now, We'll revisit once we add the "empty placeholder" back.
