### ISSUE TITLE
Image block: inconsistent position of the Textual Alternative field in the sidebar

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3658]
- go in the demo content and click on the "landscape" image
- in the sidebar, click the "Block" tab
- observe the Textual Alternative field appears before the Additional CSS Class field

![screen shot 2017-11-26 at 13 36 51](https://user-images.githubusercontent.com/1682452/33240077-3ae4c6d0-d2b0-11e7-80e6-a8d298e81a90.png)

- create a new post
- add an image
- in the sidebar, click the "Block" tab
- observe the order in the sidebar is different: Additional CSS Class is the first field, followed by Textual Alternative and Size

![screen shot 2017-11-26 at 13 40 01](https://user-images.githubusercontent.com/1682452/33240082-6bd98ef6-d2b0-11e7-8a6d-534a7bc2443e.png)

- click outside the image block
- click the image again
- observe the order in the sidebar is different again: Textual Alternative is the first field, followed by Size and Additional CSS Class

![screen shot 2017-11-26 at 13 40 11](https://user-images.githubusercontent.com/1682452/33240095-aa9657dc-d2b0-11e7-8551-672de55989d0.png)

Apart from the inconsistent ordering, the image textual alternative is so important that I'd recommend to make sure it's always the first field in the sidebar.

**Comment by gziolo** [comment]
Article that describes the similar rendering issues and proposes some fixes: https://medium.com/@robin Pokorny/index-as-a-key-is-an-anti-pattern-e0349aece318. We reuse the same keys which in this case might not be ideal. It might be also a completely different issue 😃

**Comment by jorgefilipecosta** [comment]
It looks like images don't have a block description when no image is selected, so only the class selector appears in the inspector at the start. As it was rendered first this order is kept even after the image is added this is the reason inconsistency. The merge of https://github.com/WordPress/gutenberg/pull/3680/files will fix this problem.

**Comment by jorgefilipecosta** [comment]
This should be fixed with the merge of https://github.com/WordPress/gutenberg/pull/3756. Thank you for your report @afercia 👍  If the problem persists feel free to reopen and I will debug further.
