### ISSUE TITLE
The `block_editor_settings_all` filter does not get applied everywhere

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#36595]
### Description

The `block_editor_settings_all` allows you to hook into the editor settings generated by the theme.json file and override them. It doesn't get applied everywhere though. For example when trying to change the `contentSize` and `wideSize` values for a specific post type that currently isn't an option in the `theme.json` file the setting doesn't make it's way to the editor correctly.

```php
add_filter( 'block_editor_settings_all', 'modify_block_editor_settings', 10, 2 );

/**
 * modify block editor settings
 *
 * @param array                   $settings             settings
 * @param WP_Block_Editor_Context $block_editor_context block editor context
 *
 * @return array $settings
 */
function modify_block_editor_settings( $settings, $block_editor_context ) {
	if ( in_array( $block_editor_context->post->post_type, [ 'post' ], true ) ) {
		$settings['__experimentalFeatures']['layout']['contentSize'] = '650px';
		$settings['__experimentalFeatures']['layout']['wideSize']    = '850px';
	}

	return $settings;
}
```

### Step-by-step reproduction instructions

Set your content size in the `theme.json` file to something large like 1000px.

Add the following code to the `functions.php` file:

```php
add_filter( 'block_editor_settings_all', 'modify_block_editor_settings', 10, 2 );

/**
 * modify block editor settings
 *
 * @param array                   $settings             settings
 * @param WP_Block_Editor_Context $block_editor_context block editor context
 *
 * @return array $settings
 */
function modify_block_editor_settings( $settings, $block_editor_context ) {
	if ( in_array( $block_editor_context->post->post_type, [ 'post' ], true ) ) {
		$settings['__experimentalFeatures']['layout']['contentSize'] = '650px';
		$settings['__experimentalFeatures']['layout']['wideSize']    = '850px';
	}

	return $settings;
}
```

Go to the wp-admin and create a new post.

See that the `layout.contentWidth` has not been overwritten

### Environment info

Gutenberg: 11.9.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I can reproduce this partially. 
In WP 5.9.2, without Gutenberg active, the width is adjusted in the editor but not the front. 
With Gutenberg 12.8 active, only the sizes set is theme.json are used.

**Comment by fabiankaegy** [comment]
This can now be achieved using the theme.json filters instead.

**Comment by christofervas** [comment]
I found this post searching to filter theme.json for a specific custom post type. Is that possible? 

I have tried many ways to filter by post type for example using get_post_type() and I get warnings and memory errors. @fabiankaegy did you have any success with the theme.json filters such as the `wp_theme_json_data_theme`?

**Comment by styledev** [comment]
Noting here that this can not be achieved by using the theme.json filter (e.g. `wp_theme_json_data_theme`) only, it also requires overriding "__experimentalFeatures" `via block_editor_settings_all` filter.
