### ISSUE TITLE
Full Site Editing: Ensure that the site editor canvas loads only after the global styles are ready.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#36594]
### Description

An attempt to fix this has been done in #36044 that said, it seems it is still possible to experience this in some situations. Basically when you load the site editor, the canvas should only be rendered with the correct styles directly. While right now, it's possible to actually see the canvas unstyled for some milliseconds and then the global styles get applied.

### Step-by-step reproduction instructions

I'm not sure exactly about the exact instructions to reproduce. I've been able to see this with just a basic 2022 theme installation. That said for now, we should just test it, audit it and if we find a good way to reproduce, fix it.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jameskoster** [comment]
I believe this is somewhat related: https://github.com/WordPress/gutenberg/issues/35503

**Comment by annezazu** [comment]
Just noting that I can replicate with a fairly empty install using the Tove theme, latest version of Gutenberg (11.9.1), and WordPress 5.8.2. Here's a short video both showing how it sometimes does and doesn't happen though:

https://user-images.githubusercontent.com/26996883/142516749-3de49e59-b541-4504-aec1-3ee0ac9cfe93.mov

I'm a visual person so thought the video would help others understand :)
