### ISSUE TITLE
Remove "Save as" button from Navigation block toolbar

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#36593]
## What problem does this address?

If a theme inserts a Navigation block as part of a template, when viewing it in the editor, a "Save as" button appears in the block toolbar, like so:

<img width="434" alt="Screen Shot 2021-11-18 at 2 06 00 pm" src="https://user-images.githubusercontent.com/8096000/142344812-aa794a67-0cf3-444f-9dbe-069b5417376e.png">

This can be confusing for users (no other blocks have a save button), and is not strictly necessary for the navigation saving flow; any changes made to the block will be saved together with other template changes when clicking the editor "Save" button. 

## What is your proposed solution?

Remove the "Save as" button from the Navigation toolbar.

**Comment by tellthemachines** [comment]
Closing as duplicate of #36575

**Comment by mkaz** [comment]
I'm reopening this one. The other ticket #36575 was a duplicate but included two different issues with different priorities, so better to split out. Since this ticket has better details, it'll be a better one to work off.

**Comment by getdave** [comment]
~I'm looking into this one but would welcome any help.~

Looks like this might be addressed by https://github.com/WordPress/gutenberg/pull/36522?
