### ISSUE TITLE
Block becomes unusable with error "This block has encountered an error and cannot be previewed"

### ISSUE THREAD

**Issue by Jamesiewaimsy** [WordPress/gutenberg#36607]
Hi

im having an issue when I edit a page "This block has encountered an error and cannot be previewed" I have read all the forums and youtube

It was working last week and then just stopped.

Page
https://sevensoda.com.au/available-products/

**Comment by Jamesiewaimsy** [comment]
This happens only when I add the ALL PRODUCTS

**Comment by Jamesiewaimsy** [comment]
Can someone provide any links that can help me?

**Comment by talldan** [comment]
@Jamesiewaimsy I'm not sure what 'ALL PRODUCTS' is. Which particular block is it that isn't working?

**Comment by Jamesiewaimsy** [comment]
![image](https://user-images.githubusercontent.com/94611263/143016574-bc984178-2efa-48c9-9a95-ca0a73a5319b.png)

![image](https://user-images.githubusercontent.com/94611263/143016707-618692ca-7cad-402e-b4cd-665ee1ecfee5.png)

Talldan thank you for the reply, please see two screenshots I hope they help.

**Comment by Jamesiewaimsy** [comment]
If I click the three dots these are my options
![image](https://user-images.githubusercontent.com/94611263/143016886-e0583742-555e-4bb2-88d0-a28c2a7f56fa.png)

**Comment by talldan** [comment]
Thanks for the extra information. The All Products block isn't one that WordPress or Gutenberg provides by default so it's not something that can be addressed here.

You'll need to find out which of your plugins provides this block and then reach out to the plugin developer for support. If this plugin was added through the WordPress plugin directory you should be able to go to the plugin page and there will be support links there.
