### ISSUE TITLE
Site Logo: Align center doesn't work

### ISSUE THREAD

**Issue by andrewstaffell** [WordPress/gutenberg#36606]
https://github.com/WordPress/gutenberg/blob/0c5e279cf4bb0e80d1b310dfbaf409046b2627a3/packages/block-library/src/site-logo/style.scss#L21

This leaves it left-aligned for me? 

I don't get why it needs `display: table`. This seems to work better:

```
.wp-block-site-logo.aligncenter img {
    display: block;
    margin-right: auto;
    margin-left: auto;
}
```

Also `aligncenter` is appearing twice in the classes for the block:
```
<div class="is-style-default aligncenter aligncenter is-style-default wp-block-site-logo">
```

**Comment by ndiego** [comment]
@andrewstaffell thanks for posting this issue, you beat me to it! I am actually working on a fix for this right now.

**Comment by annezazu** [comment]
I _think_ the same issue came up with the [latest call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/11/08/fse-program-testing-call-11-site-editing-safari/#comment-2254) (let me know if this is a different issue though and I'll open a new one):

>The last thing I noticed was when adjusting the header area, when adding a third column in the middle and adding a site logo block to it, the site logo block would not be aligned centered if this alignment was set in the site editor. It does work for an image block, but not for the site logo block.

Excited to know a fix is already in the works! Thanks, Nick!

**Comment by ndiego** [comment]
@annezazu yup this is the same issue that you quoted!
