### ISSUE TITLE
Translated special characters not being displayed as expected

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#3660]
## Issue Overview

Translation HTML characters being escaped.

## Steps to Reproduce (for bugs)
1. Switch the site language to Dutch
2. Open the `Categories & Tags`
3. See `Categorie&#235;n` as name

<img width="284" alt="welcome_to_the_gutenberg_editor___nieuw_bericht_toevoegen_ _acceptance_test_ _wordpress" src="https://user-images.githubusercontent.com/2005352/33240892-9ea8005c-d2be-11e7-801b-3e86fb5567ba.png">

This translation is not being loaded from the gutenberg translations (https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/nl/default?page=1) as it does not exist in there.

Assuming this translation is a default WordPress translation instead.

**Comment by youknowriad** [comment]
I'm not able to reproduce this. Could you confirm on your side?

**Comment by moorscode** [comment]
This seems to be fixed in `1.9.1`!
