### ISSUE TITLE
Replace "Template Parts" list with area-based alternative

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36613]
Part of #36597

The Template Parts list works well:

<img width="1503" alt="Screenshot 2021-11-18 at 12 17 20" src="https://user-images.githubusercontent.com/846565/142413947-a92224dd-d2af-46f7-805c-1211b650696d.png">

However, "Template Parts" is a fairly technical term that we arguably shouldn't be surfacing unless absolutely necessary. Since template parts can be associated with specific areas, we might use those to refine the navigation:

<img width="1503" alt="Screenshot 2021-11-18 at 12 19 20" src="https://user-images.githubusercontent.com/846565/142414209-3afb146f-c53c-4c96-9793-47a6b4871753.png">

The main drawback here is that "general" template parts would only be accessible through templates directly.

cc @kellychoffman

**Comment by carolinan** [comment]
I like the simplicity of showing only header and footer, it _looks nice._

The problem I see is user created template parts.
"General" is the default area for user created template parts, and I don't think it is obvious that:
- There is something called an area
- How to change the area

I think that is why the template part area setting is under the Advanced panel.

If the general template parts are only accessible through templates, how are they deleted? It is not enough to only select and delete the block in place in the editor.
If I create a template part, I need to be able to find it again, so not having it listed is a major drawback, imagine just testing things, and it being added as clutter in the database.

**Comment by jameskoster** [comment]
I suppose we could still have a "Template Parts" menu item, which is where general template parts would live.

<img width="338" alt="Screenshot 2021-11-19 at 09 51 29" src="https://user-images.githubusercontent.com/846565/142602591-b0dabc9f-cf26-45aa-9528-fdfeeae6bd20.png">

(ignore the icons)

**Comment by talldan** [comment]
> (ignore the icons)

The icons look really nice though 😄

**Comment by jameskoster** [comment]
We can try adding the icons too, but I suspect that would involve edits to the underlying component and so might be better handled separately?

**Comment by talldan** [comment]
Here's a PR that tackles adding the icons - https://github.com/WordPress/gutenberg/pull/36893

**Comment by ribaricplusplus** [comment]
Should this still be done or should it be closed? I see that the main tracking issue #36597 is closed.

**Comment by jameskoster** [comment]
I think there's a decent argument for this change, if it's simple enough to implement. Not a strong opinion though, because it's unclear if this particular UI will persist in the long term (see https://github.com/WordPress/gutenberg/pull/39885).

**Comment by annezazu** [comment]
Closing this out as the interface has evolved immensely, including a "Patterns" section with template parts listed. What remains for consideration is this issue around emphasizing header/footer more: https://github.com/WordPress/gutenberg/issues/50958
