### ISSUE TITLE
Allow for hooking into conversion from classic Menu to Nav block

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#36616]
As per https://github.com/WordPress/gutenberg/issues/36576#issuecomment-972837892 there is a requirement for developers to be able to hook into the process which converts classic menus into navigation blocks.

Currently this is handled on the JS side in the following method of the Navigation block:

https://github.com/WordPress/gutenberg/blob/b8fd765d210daaf25967dd8ff86ad2de593ba4ca/packages/block-library/src/navigation/menu-items-to-blocks.js#L33

## Use case

The use case driving this issue is illustrated below. Specifically this point:

> ...in Polylang plugin we have a specific language switcher menu item we can use in the classic menu. It is specific because it is not a menu item as the other ones because it doesn't generate a simple link but several links (one per language).

Whilst this is specific to Polylang there are likely other Plugins that will need to control the mapping process.

## Potential Approaches

Looking at the code it looks as though if the classic menu item is saved with a `type` field of `block` then it will be automatically parsed as a block. In this case the `content` field of the menu item should be a serialized block. As a result when the block is parsed it will be detected as a valid block.

https://github.com/WordPress/gutenberg/blob/b8fd765d210daaf25967dd8ff86ad2de593ba4ca/packages/block-library/src/navigation/menu-items-to-blocks.js#L40-L50

If this approach is too difficult for Plugin authors then we may need to introduce a hook to allow them to manually create the block equivalent from a given menu item.

------

### Original Issue

In fact, in Polylang plugin we have a specific language switcher menu item we can use in the classic menu. It is specific because it is not a menu item as the other ones because it doesn't generate a simple link but several links (one per language).

The current migration feature when we use the new navigation block produce for all the menu items a navigation-link block.
For our specific menu-item, it's wrong: it should be converted to our naviagtion-language-switcher block.

We were looking for a solution when I asked a question on slack to know where the current conversion is done.
Surely here, I suppose 🤔https://github.com/WordPress/gutenberg/blob/v11.9.1/packages/block-library/src/navigation/menu-items-to-blocks.js

I push here the video I previously pushed on slack to better illustrate what I explain.
https://user-images.githubusercontent.com/1003778/142417108-4d3961f0-6ab9-4b1c-b32b-c4085a362e77.mp4

I would see an alternative: open the navigation block conversion to make it extensible and make possible to decide how to convert some menu-item. It's just an idea and what we were looking for at the beginning.

_Originally posted by @manooweb in https://github.com/WordPress/gutenberg/issues/36576#issuecomment-972837892_

**Comment by getdave** [comment]
> Potential Approaches

@manooweb Apologies. I just re-read the above and actually I can't see how this would work. You would need to save your Menu Item in classic land with a `type` field of `block`. That's never going to be achievable as the UI will then look very strange on the classic Menu screen.

I'll ponder on this a bit more and see if I can come up with some concrete solutions. If there's a way I can setup Polylang on my local machine to test out your specific issue that would help.

**Comment by adamziel** [comment]
If my understanding is correct, the problem goes like this:

1. Polylang has a special menu item called "Language switcher". Whenever a menu is rendered or returned by an API endpoint, that [menu item is turned into many items like "English, French, Spanish" by a filter.](https://github.com/polylang/polylang/blob/3ccb16fceeec1a56e71c2e5ecd82efdcd726599c/frontend/frontend-nav-menu.php#L92). 
2. Gutenberg migrates menu items to blocks one by one based on the REST API output. Language switcher is represented as many links, so instead of ending up with a single "language switcher" block, it ends up with one navigation link block per language.

I wonder if it would be enough to have a frontend filter like `after_migration_from_menu_items_to_blocks` where any plugin could reorganize the end result as needed? In this case, the language switcher blocks could be marked in a specific way and collapsed back into a single block. cc @getdave  @manooweb

**Comment by adamziel** [comment]
I proposed a way forward in https://github.com/WordPress/gutenberg/pull/36950. LMK if you think that would work @getdave @manooweb

**Comment by manooweb** [comment]
Tested and OK for me See https://github.com/WordPress/gutenberg/pull/36950#issuecomment-988660746

**Comment by getdave** [comment]
@adamziel can this be closed out?

**Comment by manooweb** [comment]
@getdave for me is yes. The PR has been merged and backported in WordPress 5.9 👍

**Comment by getdave** [comment]
Ok closing for now. @adamziel can reopen if he feels he needs to do any follow up here.
