### ISSUE TITLE
Verify classic templates work as a fallback to block ones

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#36615]
### Description

For the WordPress 5.9 release, we need to ensure themes can work in a hybrid mode so that they load block themes when available but can also use PHP ones as a fallback. For example, a block theme with an archive PHP template but no HTML one should be able to find and use the PHP template.

### Step-by-step reproduction instructions

1. Install a block theme.
2. Create two versions of the archive template, both in classic PHP and as a blocks template.
3. Verify the block template is being used.
4. Delete the block template, leaving only the PHP one.
5. Verify the classic template is used.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
there is an issue for this already at https://github.com/WordPress/gutenberg/issues/24834

**Comment by skorasaurus** [comment]
on second thought, I am reopening because this is on the 5.9 must haves board and don't have edit access to that; but should consolidate discussion of this into #24834 ; close this issue and then update the 5.9 board with that issue

**Comment by priethor** [comment]
Closing as duplicate of #24834
