### ISSUE TITLE
Navigation block 'missing link' tooltip positioned far away from it's source in site editor

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#36634]
### Description

It's easiest to show the screenshot rather than describe this:
<img width="379" alt="Screenshot 2021-11-19 at 11 03 42 am" src="https://user-images.githubusercontent.com/677833/142558290-52e179e4-c3f8-40e1-9e57-8b249c21fa63.png">

The 'This item is missing a link' text is far away from the 'Add Link' item it should be connected to.

In testing, I could only reproduce this in the site editor.

### Step-by-step reproduction instructions

1. Add a nav block in the site editor
2. Start empty
3. Click the plus button
4. Hover over the 'Add Link' text.

### Environment info

Mac OS, Brave, Gutenberg trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by adamziel** [comment]
This seems like an issue with the Popover component. Site editor is in an iframe, post editor isn't. `.popover-slot` where the tooltips are rendered is outside of the iframe. It seems like `computePopoverYAxisPosition` or some other function in proximity doesn't account account for the iframe's `top` value.

**Comment by adamziel** [comment]
iframes are only considered in when `Popover` receives either `anchorRef` or `getAnchorRect`, but in case of the tooltip neither of these is present. The position is based only on on `anchorRefFallback`. I think a sensible solution would be to still consider that an iframe may be among the parents in that case.

https://github.com/WordPress/gutenberg/blob/53374ba92c379480659a7df5ac456756ad3a798c/packages/components/src/popover/index.js#L45-L52

I proposed a solution in https://github.com/WordPress/gutenberg/pull/36876
