### ISSUE TITLE
Unusable with iPhone

### ISSUE THREAD

**Issue by zerosonesfun** [WordPress/gutenberg#36632]
### Description

When you try the scroll it jumps back to the original position. 

### Step-by-step reproduction instructions

Use iphone. 

### Screenshots, screen recording, code snippet

![057C0B4C-795B-4299-8946-D793333E3B5D](https://user-images.githubusercontent.com/41351317/142549484-7640657c-6efd-4c31-bd8a-124feec866b5.gif)

### Environment info

Fresh install of WordPress 6.0. Environment is iOS Safari and iOS Duck Duck Go browser. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by talldan** [comment]
@zerosonesfun Would you be able to provide more detail like which version of iOS and which version of WordPress / Gutenberg

**Comment by zerosonesfun** [comment]
iOS 15.1, iPhone XR, latest version of WordPress and Gutenberg. And I don’t think this is new per se. I feel like I’ve never been able to use it without some sort of quirkiness on the iPhone. 

But, I will say that Apple’s latest Safari updates cause issues at other sites too. So, this is a pretty tricky one.

**Comment by zerosonesfun** [comment]
This is still an issue. If you are posting anything more than regular text (adding blocks, video, etc.) you can only scroll so far on iOS. I assume it has to do with the virtual keyboard. Out of all iOS issues this really should get extra attention. I'm starting to accept the block editor, but if I can't do basics from my phone it makes it less appealing.

**Comment by zerosonesfun** [comment]
Closed because this seems to depend on plugins installed.

**Comment by nitinthewiz** [comment]
I've hit this issue on iOS lately and can confirm that it was the Notely and the WP Hide Posts plugins that were causing this issue in my case. Hope this helps anyone else who comes along.
