### ISSUE TITLE
Block Template creation is using empty content instead of the appropiate fallback

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#36648]
### Description

This was brought to my attention by @carolinan over at https://github.com/WordPress/twentytwentytwo/issues/256

When a theme doesn't provide a template for a specific page (404, Search for example) we will always fallback through the hierarchy and show in the frontend an alternative existing template. In the case of TT2, if the search.html doesn't exist, the frontend will show index.html instead:

<img width="1138" alt="Screenshot 2021-11-19 at 13 49 46" src="https://user-images.githubusercontent.com/3593343/142625983-8e8c8978-f116-4fca-8d13-7313799c0b72.png">

This is inconsistent with what the flow of template creation is showing us. When you try to create a new Search template, we see no content at all:

<img width="1134" alt="Screenshot 2021-11-19 at 13 49 24" src="https://user-images.githubusercontent.com/3593343/142626085-a600e637-f5c0-4141-b8d5-5cbb0619f508.png">

<img width="1137" alt="Screenshot 2021-11-19 at 13 49 40" src="https://user-images.githubusercontent.com/3593343/142626082-0ff9c614-570a-45d1-8b3f-881b7780d2d4.png">

This is inconsistent with what the user sees in the frontend before creating the template and forces them to create something from scratch.

### Step-by-step reproduction instructions

1. Install TT2, check in the frontend what a search results page returns
2. Go to the Site Editor and try to create a Search template
3. The Search template is empty.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kjellr** [comment]
cc @jameskoster do you know if this is a bug or not? I'm not sure if the site editor used to be smarter about this or not.

**Comment by jameskoster** [comment]
Yup, this is listed as a todo on https://github.com/WordPress/gutenberg/issues/36597 :)
