### ISSUE TITLE
Users should be able to add a custom gradient when the default gradients are disabled

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#36640]
### Description

The gradients panel doesn't allow user to add a custom gradient when the default gradients are disabled. The panel is empty but not hidden.

## How to test

- Use a theme that does not provide any solids or gradients.
- Set `defaultPalette` and `defaultGradients` to false.

This is what I see for solids:

![Captura de ecrã de 2021-11-19 10-44-14](https://user-images.githubusercontent.com/583546/142601822-cd92f366-4ce6-449b-9478-7bbbbcfc660c.png)

This is what I see for gradients (note that it's empty):

![Captura de ecrã de 2021-11-19 10-44-23](https://user-images.githubusercontent.com/583546/142601952-1354e578-20da-4b30-bb15-1e13608af7cd.png)

If I then disable the custom colors (`settings.color.custom` to false), this is what I see (the color panel is shown but it does not contain anything):

![Captura de ecrã de 2021-11-19 10-48-23](https://user-images.githubusercontent.com/583546/142602191-092a9dd0-f56d-4862-9696-e48e01a430f4.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
I thought I'd start working on a fix for this one. I have a PR open in https://github.com/WordPress/gutenberg/pull/36900, but I also noticed a couple of other issues with the gradient that I've raised in #36899. I'm just at the end of my week now, so I'll do some more investigating next week (I don't _think_ it's related to my PR, but I'll do more testing next week to be sure).

**Comment by andrewserong** [comment]
The main blocker in #36899 has been resolved, so the PR to fix the main issue here (ensure a custom gradient can be added when default and theme gradients are disabled) is ready for review now: #36900
