### ISSUE TITLE
Global Styles: Iterations on the user global styles endpoint.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#36644]
After reviewing some of the global styles behavior in WordPress 5.9, in association with the upcoming changes planned for Global Styles after 5.9, we noticed that the current behavior of the endpoint need some small changes in order to be future proof:

 - [ ] We want the ability to modify: "user", "theme" and "default" presets in the future, while right now we only update the "user" presets. This means "presets" need to be nested in the `settings` property.
 - [ ] The possibility for themes to have multiple global styles files (think multiple theme.json is planned for post 5.9 see #35619), this means we should be able to load and edit `my_theme/red` variation for instance using the endpoint. To avoid having separate endpoints, the best way to do this is to mimic the "templates" endpoint: Using "slugs" and also using an id that looks like `theme//slug`. The base theme.json should be `theme//index`. I guess this also means that the "link" we added to themes endpoint is now kind of useless.

To avoid future breaking changes, we should do that for 5.9.

**Comment by youknowriad** [comment]
For this particular issue, I've been hesitating back and forth about whether to do it or not.

Basically, this is adding complexity to an existing endpoint for a future potential use-cases. And in general I don't like doing that because we never know how these use-cases can evolve over time, meaning the added complexity if done today may prove to be wrong or useless.

On the other side, if we don't do it, we risk requiring a breaking change or potentially a new endpoint that duplicates some of the purpose of the current one.

At this point in time, I'm leaning towards the latter and just closing this issue. cc @noisysocks @jorgefilipecosta @oandregal 

I'd have love to make these endpoints experimental for now but I know the REST team is not fan of experimental APIs.

**Comment by noisysocks** [comment]
Can we mitigate against breaking changes by versioning the resource or something? For example put `"version": 1` in the JSON output? I suppose that's what the `v2` in `/wp/v2/` is for, though.

I agree that anticipating future needs is futile. Also, we're pretty far into the 5.9 cycle now so I'm more than happy to cut scope wherever possible.

**Comment by noisysocks** [comment]
Let's close 🙂 it's getting too late to really do anything now that we're in between beta 3 and beta 4.
