### ISSUE TITLE
[Site Editor] WP Menu area - Adjust < Dashboard text to 14px font.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#36658]
The following is based on testing the PR Gutenberg Build from this PR: https://github.com/WordPress/gutenberg/pull/36379#issuecomment-973432382

## What problem does this address?

The < Dashboard link uses a 13px font size vs the menu items below use a 14px font size.

![Screenshot 2021-11-19 at 16 07 52](https://user-images.githubusercontent.com/5323259/142645097-5a1ccea4-33eb-47bd-b7df-8273bdddb183.jpg)

## What is your proposed solution?

Let's use 14px font size also on the < Dashboard text link. As it creates a consistency of font size between the back link and the menu items.

**Comment by talldan** [comment]
If it's unintentional I think it can be considered a bug.

**Comment by mtias** [comment]
This is intentional to give some hierarchy to the rendering. The whole sidebar is still being tweaked, though.
