### ISSUE TITLE
[Site Editor] Templates list screen - make the screen thinner and add truncation to site title.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#36657]
The following is based on testing the PR Gutenberg Build from this PR: https://github.com/WordPress/gutenberg/pull/36379#issuecomment-973432382

## What problem does this address?

The black WP left menu area is too wide, and takes too much space based on the items inside of it.

![Screenshot 2021-11-19 at 15 55 21](https://user-images.githubusercontent.com/5323259/142643140-fcc66234-74bd-443e-ac51-2d1ad0d58148.jpg)

## What is your proposed solution?

Make the WP black menu thinner. Use truncation on the site title when needed.

![FSE-smaller-list-view](https://user-images.githubusercontent.com/5323259/142644207-810e2075-4073-4ea8-a1f6-a7e7d52a078d.jpg)

**Comment by karmatosed** [comment]
@paaljoachim what about translations and longer names there? I am thinking that whilst we have what we do today there, that section needs to grow and adapt. It also needs to have some spacing for accessibility.

**Comment by paaljoachim** [comment]
Hey @karmatosed Tammie
I just see a lot of air and wonder why there is so much air.
That is why I mentioned truncation. To have a specific character width area and then use truncation for characters after that, or one could perhaps have the site title use a second line if needed. I can always ping @joedolson Joe and hear what he says.

**Comment by joedolson** [comment]
For consistency, I feel like the menu should probably be the same width as either the customizer sidebar or the admin navigation; I think it would be nice if WordPress followed a consistent layout for all of these various toolsets. 

I do think that there are challenges here in figuring out where to provide space; on smaller screens, there can be very little area left for the site you're editing. 

I'd prefer to be able to see the entire site title. Particularly in some multisite setups, it's easy to end up with a whole collection of sites following a pattern like "University of California, Los Angeles - Department of Medical History", where truncation could cause serious problems keeping track of things. (Not a real example, so don't go checking out UCLA...)

Other than being able to see the full text of the options, I'm not sure there are any accessibility priorities around the width of the sidebar area.

**Comment by annezazu** [comment]
Let's close this out in favor of a more recent issue on the topic that has more up to date designs with the current approach in the site editor: https://github.com/WordPress/gutenberg/issues/60847

**Comment by paaljoachim** [comment]
Thank you for sharing the link to the other well covered issue, Anne!
