### ISSUE TITLE
Mobile menu not working in local Windows environment

### ISSUE THREAD

**Issue by Andrew-Starr** [WordPress/gutenberg#36673]
### Description

In a local Windows environment, the mobile navigation "hamburger" icon does nothing when clicked.

The required _/gutenberg/build/block-library/blocks/navigation/view.min.js_ is not loaded on the frontend, and is missing.

The file is present on a web hosted domain, but makes local theme development on a Windows machine very difficult.

### Step-by-step reproduction instructions

Add a naviagtion menu.
Set the Overlay Menu option to either Mobile or Always.
View frontend, click the mobile menu icon, and see that nothing happens.

### Environment info

WordPress version 5.8.2
Gutenberg version 11.9.1
Windows 10
Local hosting
Firefox, Chrome, Edge browser, same result.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by chthonic-ds** [comment]
https://github.com/WordPress/gutenberg/issues/36506 might be relevant, presuming your path to view.min.js is mangled. This has been a problem since GB 11.0.0.

**Comment by Andrew-Starr** [comment]
Yes thank you. That seems to be the same issue.

The .org theme review team are facing this issue (unable to fully test themes) when reviewing new themes submitted to .org https://github.com/WordPress/twentytwentytwo/issues/228

I'll close this issue as the previous one covers everything and it looks like a fix is on the way. :)
