### ISSUE TITLE
Clicking on an empty columns block inserter should open the block's settings

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#36682]
## What problem does this address?
It's difficult to select a parent column block, unless there are child blocks within it. The current workaround to selecting an empty column block is to try and click between the columns (but you'll probably select the + inserter) or navigate to the List view, and select the block from there. 

A common use case would be wanting to resize/color the colors of the column before adding content.

## What is your proposed solution?
When selecting the empty block inserter within the Columns block, the block's settings sidebar is opened. This should work for any block with an inserter when empty.

<img width="1314" alt="Screen Shot 2021-11-19 at 2 06 53 PM" src="https://user-images.githubusercontent.com/1813435/142677730-81304a17-c159-4ab1-b414-7c294633cac8.png">

**Comment by jordesign** [comment]
In my testing in WP6.3 - the toolbar is now shown when selecting a column inserter - closing this as no longer reproducible,
