### ISSUE TITLE
Docs request: How to create a block pattern

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#36688]
There is not a how to document for creating a block pattern. The only documentation is in the [reference section for the API](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/).

There is [a good /news article here](https://wordpress.org/news/2021/03/so-you-want-to-make-block-patterns/) with all the relevant info, this should also be in the docs themselves.

**Comment by jorgecontreras** [comment]
I'm adding a How to guide based on The Good Docs Project template for Block pattern creation.

**Comment by mkaz** [comment]
@jorgecontreras Thanks so much! I do have a PR that would add a template page for How To guides here, based off the same Good Docs Project template. Feedback welcome. https://github.com/WordPress/gutenberg/pull/36694

**Comment by anoopd** [comment]
@jorgecontreras  Have you finished that . I would like to know how you used that `Good Docs` template .

**Comment by mkaz** [comment]
@anoopd I have an [example template here](https://github.com/WordPress/gutenberg/blob/bac0163f0489a8bee99e7288139da8421fd24c9f/docs/contributors/documentation/how-to-guide-template.md) as part of the PR mentioned.

I'd welcome any feedback on anything to add or adjust on the template to make it easier to use.

**Comment by anoopd** [comment]
Ty will go through it .

**Comment by mkaz** [comment]
@jorgecontreras I see the commit on your fork for adding the pattern, do you want to submit that as a PR?
Let me know if you need any assistance, here is [the GitHub documentation on creating a PR from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by jorgecontreras** [comment]
> @jorgecontreras I see the commit on your fork for adding the pattern, do you want to submit that as a PR? Let me know if you need any assistance, here is [the GitHub documentation on creating a PR from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

hi @mkaz sounds good! I'll send a PR shortly. Thanks!

**Comment by santanainniss** [comment]
@mkaz @jorgecontreras Is there a PR for this? I'm wondering if I can possibly support here. Thank you!

**Comment by jorgecontreras** [comment]
> @mkaz @jorgecontreras Is there a PR for this? I'm wondering if I can possibly support here. Thank you!

Hi @santanainniss, there's a PR here:
https://github.com/WordPress/gutenberg/pull/37424

**Comment by ryanwelcher** [comment]
@jorgecontreras any update on this? Is the PR ready to merge?

**Comment by ryanwelcher** [comment]
Closing based on the existence of [these docs](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/). Feel free to re-open if I am mistaken.
