### ISSUE TITLE
Shift+Click in grouped blocks locks editor

### ISSUE THREAD

**Issue by BushnellWebWorks** [WordPress/gutenberg#36683]
### Description

When a block having child elements (such as "core/table" or "core/list") is grouped with one or more other components, shift+clicking across child elements within the block, prevents further editing on any blocks.

### Step-by-step reproduction instructions

1. Start with a block editor panel having at least one paragraph
2. Add two blocks, one having child elements (consistently happens with "core/list" or "core/table")
2. Group them
3. Inside the block with child elements, shift+click from one child to another

At this point it becomes impossible to update content in any blocks within the editor. For example, cannot click within a paragraph and add text.

- First noticed the issue with WP 5.8, not an issue with WP 5.7.2
- Issue persists in WP 5.8.2
- First uncovered the issue in a custom block using <InnerBlocks />, but can reproduce without code using the above steps

### Screenshots, screen recording, code snippet

Hard to convey "can't edit" within this recording, but after I shift+click within the "core/list" block then I try to click and type within other blocks.

![just_the_wp58_bug](https://user-images.githubusercontent.com/7585082/142692616-f674ab36-ed20-4c44-8f1e-77e76c2710cb.gif)

### Environment info

- WordPress 5.8, bug also confirmed in WordPress 5.8.2 (but not present in 5.7.2)
- Custom Theme

Browsers:
- Chrome Version 96.0.4664.55 (Official Build) (x86_64)
- Edge Version 95.0.1020.53 (Official build) (x86_64)
- Safari Version 14.1 (16611.1.21.161.6)

OS: 
Mac 11.3.1 
(also verbally confirmed with Windows users, versions unknown)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Hi @BushnellWebWorks, thanks for reporting this. I think this was fixed in the Gutenberg plugin, and the fix should be in WordPress 5.9.

It looks like one or both of these pull requests solved the problem:
- https://github.com/WordPress/gutenberg/pull/35988
- https://github.com/WordPress/gutenberg/pull/35668

Lets check in with @ntsekouras to make sure though.

**Comment by ntsekouras** [comment]
Thanks for the issue @BushnellWebWorks.

>Lets check in with @ntsekouras to make sure though.

Yes, this is fixed in the plugin and will be in WP 5.9 as @talldan said.

**Comment by BushnellWebWorks** [comment]
Thank you :)
