### ISSUE TITLE
Override parent blockGap

### ISSUE THREAD

**Issue by illycz** [WordPress/gutenberg#36692]
I'm testing Blockbase child theme and is impossible disable blockGap feature.
When I set settings.spacing.blockGap to false editor still generate margins for elements.

I think it's because Blockbase also specify blockGap  in styles.spacing and in this place is possible only set this to zero.
But I don't want generate this margins at all.

Thanks

**Comment by scruffian** [comment]
Could you just set the blockGap to 0?

**Comment by illycz** [comment]
> Could you just set the blockGap to 0?

I don't want generate this margins with high specificity at all.

**Comment by illycz** [comment]
This comment from Blockbase CSS is telling:
![image](https://user-images.githubusercontent.com/2109984/144676182-dfe692fc-0538-4153-b067-6507755e869b.png)

**Comment by scruffian** [comment]
I'm starting to wonder if we should remove this from Blockbase altogether...

**Comment by ndiego** [comment]
See https://github.com/WordPress/gutenberg/issues/37232, it's related. You can disable `blockGap` with `null`. For some reason `false` does not work.

**Comment by illycz** [comment]
Great, thanks for that!

**Comment by Mamaduka** [comment]
The solution mentioned by @ndiego is now documented - https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#what-is-blockgap-and-how-can-i-use-it.

I'm going to close the issue.
