### ISSUE TITLE
Hide "submenus" section in navigation block when there are no submenus

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#36698]
If I have no submenus in my navigation we should not render the submenu options:

![image](https://user-images.githubusercontent.com/548849/142775284-0b26e869-7b15-40d1-b2ab-76c74fffbf3e.png)

**Comment by mtias** [comment]
Also when "open on click" is toggled on, let's try not hiding "show icons" but forcing to look disabled yet "on":

![image](https://user-images.githubusercontent.com/548849/142775381-e114b7af-f76b-4f93-b518-62f27d9703be.png)

**Comment by mtias** [comment]
Instead of "show icons" let's be more clear as well with "show arrow" or something like that.

**Comment by jasmussen** [comment]
CC: @vcanales want to pair on this one?

**Comment by vcanales** [comment]
> CC: @vcanales want to pair on this one?

Absolutely!

**Comment by jasmussen** [comment]
This should be fixed!
