### ISSUE TITLE
Prioritize patterns on quick inserter instead of blocks at the root of templates

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#36697]
The quick inserter has been designed to accommodate a pattern-only view which has never been turned on yet. Let's try using it when the quick inserter is accessed at the top layer of a template. The top level means it's a direct descendant of the document, between any root template parts or existing blocks. In the following example of a block tree there would be two such places:

![image](https://user-images.githubusercontent.com/548849/142774278-08ec07f1-feec-47bf-af68-4f6005ccf6e8.png)

As a reminder, the design for the quick pattern insert looks like this:

<img width="840" alt="Inserter-patterns" src="https://user-images.githubusercontent.com/548849/142774992-01d055c4-8ad8-409d-b77f-1b41f0ba6f11.png">

This would optimize for inserting patterns from the theme when building templates and start bringing patterns into stronger focus. In the future we need to improve the browsing and listing experience of this inserter.

**Comment by jasmussen** [comment]
I think this could work well. 

One thing to consider is how to make it visually clear why the interface defaults to patterns here in the top level context. To help highlight that, I tried a mockup that zooms out the page into an exploded view:

<img width="2840" alt="Insert patterns i2" src="https://user-images.githubusercontent.com/1204802/143249270-187227c3-15f4-4eee-9241-10630ecc4bbf.png">

This view would put top level blocks in relief, and help surface that patterns can be inserted in the gutters between sections. The zoom level would help for the taller page-length patterns. 

This also reminds me of the older idea we discussed for [presenting a zoomed-out view](https://github.com/WordPress/gutenberg/issues/28175#issuecomment-760154317). That idea was also mentioned [in context of the mosaic view](https://github.com/WordPress/gutenberg/pull/33770#discussion_r691135350) and is conceptually well illustrated in [this animatic](https://github.com/WordPress/gutenberg/issues/32103#issuecomment-846119385).

**Comment by mtias** [comment]
Yes, indeed, it connects well with that idea. In the context of the zoomed-out view we can also make the sibling inserter always visible between pattern sections, for example. In that context it'd be nice to render the inserter larger, maybe coupled with the carousel view. But one step at a time!

**Comment by jasmussen** [comment]
Nice worko @jorgefilipecosta! Should we reopen this one for some of the design changes proposed here, that aren't yet implemented?
