### ISSUE TITLE
'Edit site' admin bar button doesn't match other buttons

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#36704]
The _Edit site_ button in the admin bar doesn't match other Core buttons in the admin bar.

- It is capitalised differently. (_Edit site_ versus _Edit Site_.)
- It doesn't have an icon.

<img width="468" alt="Screen Shot 2021-11-22 at 11 03 58 am" src="https://user-images.githubusercontent.com/612155/142784489-ad4e7684-926a-4db2-9e14-3ddc6923908f.png">

**Comment by ntsekouras** [comment]
Also should this become `Editor` probably like we have under `Appearance` menu? `Edit Site`[ is the same link for multisites](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/admin-bar.php#L390).

**Comment by Mamaduka** [comment]
I think this got fixed in core. We should do a follow-up about the "title case" in Trac.

![CleanShot 2022-01-05 at 09 46 50](https://user-images.githubusercontent.com/240569/148166851-4bc32244-f7ad-4d37-95e8-7457c011b09a.png)
