### ISSUE TITLE
Toolbar position in navigation's overlay is odd

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#36701]
The position of the toolbar when working with the overlay portion of a navigation menu looks random:

<img width="1501" alt="Screenshot 2021-11-21 at 13 26 00" src="https://user-images.githubusercontent.com/548849/142775725-7ca79f50-cdb6-4313-b572-7845b162e8f7.png">

**Comment by jasmussen** [comment]
The way this is "fixed" in the post editor, is that the overlay menu has a higher z-index than the block toolbar, covering it, the idea being that the block toolbar isn't useful to editing content inside (the mover controls aren't right, etc). That solution breaks in the site editor, as that's iframed and creates a stacking order that doesn't allow the menu overlay to be elevated above the block toolbar.

As a longer term solution, the contents of the overlay should probably be separately customizable to the menu itself, and could potentially be edited in "template part focus mode". 

As a near term solution, I wonder:

- Can we simply hide the block toolbar when this overlay is opened?
- Can we force the "top toolbar" option when this is opened?
- Perhaps a plan B if those fail, if we can attach a classname to the block toolbar when the overlay is opened, we can likely improve things from this state at least.

**Comment by jasmussen** [comment]
CC: @georgeh @vcanales @mkaz

**Comment by annezazu** [comment]
I also experienced some oddness with the UX when using the always on mobile option today that I think relates to this issue as well:

https://user-images.githubusercontent.com/26996883/143914573-44f3d3df-7e74-4bf8-b09c-758a2c642869.mov

From my point of view, I thought the vertical alignment was accidentally turned on and that somehow the navigation block had taken over my entire header. It wasn't quite clear how to get out of it and the scroll bar that suddenly appeared made everything feel very broken.

**Comment by jasmussen** [comment]
#36990 linked by github right above _mitigates_, but does not solve this one.

**Comment by mtias** [comment]
Closing as the entire overlay is due for a revision
