### ISSUE TITLE
Image Cropping does not use correct aspect ratio

### ISSUE THREAD

**Issue by beatricekulcsar** [WordPress/gutenberg#36713]
### Description

The image cropping tool of the image block does not work as expected when trying to change the aspect ratio. 

### Step-by-step reproduction instructions

1. Add image to post
2. crop image
3. choose aspect ratio "square"
4. frame image
5. click apply

#### Expected behavior:
Image gets cropped to the square preview as selected

#### Actual behavior:
Image gets cropped to a weird 2:1 aspect ratio that does not match the selected area.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/71608597/142828873-f4ba38db-686a-49a9-9585-cd81eff93caa.mov

### Environment info

WordPress Version 5.8.2
Gutenberg Version 11.9.1
Active Theme: TT1 Blocks (tt1-blocks), Version 0.4.7

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I tried replicating this with 5.9 without Gutenberg installed and with Gutenberg 12.5.3 installed but couldn't replicate using Twenty Twenty-Two:

https://user-images.githubusercontent.com/26996883/152720510-b40b901a-bf45-4952-9fb8-8fd2f6493bbf.mov

I'm going to close this out as a result but please re-open if this is still an issue you're experiencing!
