### ISSUE TITLE
Updating the loading spinner 

### ISSUE THREAD

**Issue by pablohoneyhoney** [WordPress/gutenberg#36725]
As the editor's design language keeps advancing and modernizing, it is also relevant to look at less-visible instances, like the [spinner component](https://wordpress.github.io/gutenberg/?path=/story/components-spinner--default), that retains currently an aged form, perhaps inherited from general WP:

<img width="79" alt="Screen Shot 2021-11-22 at 12 02 19 PM" src="https://user-images.githubusercontent.com/25516611/142850295-74ffb5e8-9452-4b15-bc47-4a683da8c45b.png">

![spinner](https://user-images.githubusercontent.com/25516611/142850203-7d083278-4226-4bfd-83ca-eb158c37c8de.gif)

And its position seems to be at odds, like in the below example of site editor and nav block. Not sure what the logic is here: 

![image](https://user-images.githubusercontent.com/25516611/142845986-9cefc7d2-e7f3-4663-8b48-f29471b73688.png)

Here's the proposal, with diverse scales (64, 48, 24) and color combinations (upcoming blueberry`3858E9` gray 300 `DDDDDD` gray 900 `1E1E1E` white `FFFFFF`) for potentially various contexts and circumstances: 

![Spinner-new](https://user-images.githubusercontent.com/25516611/142848899-d3281ab2-5448-48db-bacf-1a21001395b6.png)

![Spinner-new-lightbg](https://user-images.githubusercontent.com/25516611/142849180-ff556eb2-e6d8-4c5c-85cc-fd188496df6e.png)

**Comment by jameskoster** [comment]
Related: https://github.com/WordPress/gutenberg/issues/35503
