### ISSUE TITLE
Rename the `navigationMenuId` property to `id` in the Navigation block

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#36722]
## What problem does this address?

The attribute `navigationMenuId` is overly verbose.

## What is your proposed solution?

Simplify to `menuId` or simply `id`.

**Comment by mtias** [comment]
Also worth considering reusable blocks are using `"ref":123`. Might be ok to align there.

**Comment by Mamaduka** [comment]
This issue got fixed via #36739.
