### ISSUE TITLE
"upload_files" capability and Image relative blocks

### ISSUE THREAD

**Issue by imath** [WordPress/gutenberg#3672]
## Issue Overview
Gutenberg version 1.7.0
When a contributor uses Gutenberg he can use Image relative blocks. When he tries to use it as this role hasn't got the `upload_files` capability, the REST reply to site.url/wp-json/wp/v2/media is `rest_cannot_create` (403).

## Steps to Reproduce (for bugs)

1. Log in as a contributor.
2. Add a new post.
3. Select the image block.
4. Upload an image.
5. The image shows for a few milliseconds.
6. The Upload/Browse buttons are replacing the vanished image.
7. No feedback is provided to the contributor untill the automatic save feature run. Then the error is: "This block has encountered an error and cannot be previewed."

Chrome Version 62.0.3202.94

## Expected Behavior

Image/files relative blocks should only show `if ( current_user_can( 'upload_files' ) )`

## Current Behavior

Image/files relative blocks are showing no matter the "upload_files" capability of the logged in user.

## Screenshots / Video

Here is some oxygen :wink: https://cldup.com/K8qYyaHWbI.mp4

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mtias** [comment]
Latest PR here: https://github.com/WordPress/gutenberg/pull/4155
