### ISSUE TITLE
Remove the Navigation Area block

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#36728]
After the discussion was started in https://github.com/WordPress/gutenberg/issues/36524 and the block was soft deprecated in Gutenberg 12.0 (https://github.com/WordPress/gutenberg/pull/36727), it's time to remove it in Gutenberg 12.2.

I attached 12.1 label to this issue, let's bump it to 12.2 once that milestone is created.

cc @noisysocks @getdave @draganescu

**Comment by adamziel** [comment]
I implemented a revert in https://github.com/WordPress/gutenberg/pull/36604. It will probably be full of merge-conflicts by the time 12.2 is around the corner, but it could still serve as a blueprint.

**Comment by getdave** [comment]
Did the Nav Areas PHP code get merged to WP Core already? If so how do we revert that prior to 5.9?

**Comment by adamziel** [comment]
cc @noisysocks who did the WP Core merge

**Comment by noisysocks** [comment]
Ah, yeah, good flag. I opened a ticket: https://core.trac.wordpress.org/ticket/54506

**Comment by noisysocks** [comment]
Patch to remove Navigation Areas from Core: https://github.com/WordPress/wordpress-develop/pull/1944

**Comment by noisysocks** [comment]
Removing this from the WP 5.9 board as there's nothing remaining to do for WP 5.9. Next step is to remove the Navigation Area block from the plugin in Gutenberg 12.2.

**Comment by talldan** [comment]
I can't see it in the codebase, so will close this.

**Comment by getdave** [comment]
I removed it. Some how I forgot to cross link the issues. Thanks for following up.
