### ISSUE TITLE
Changing the Post Title Font Family does not apply on front-end

### ISSUE THREAD

**Issue by beatricekulcsar** [WordPress/gutenberg#36729]
### Description

Choosing a font family in the site editor does not have any effect on the front-end representation.

### Step-by-step reproduction instructions

1. click on post title
2. open settings side bar
3. select font family under typography

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/71608597/142855481-bd95d7a7-b5cd-4845-95ed-137c97e0d638.mov

### Environment info

WordPress Version 5.8.2
Gutenberg Version 11.9.1
Active Theme: TT1 Blocks (tt1-blocks), Version 0.4.7

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
👋 thanks for reporting this. I couldn't reproduce this though 🤔 

You changed the font family setting for a single Post Title block. If you wanted this to be effective for all blocks you should change the setting in Global Styles sidebar. Is this the case?

**Comment by beatricekulcsar** [comment]
I retested it myself and am no longer able to reproduce it either. Thanks for looking into it.
