### ISSUE TITLE
Wrong Viewport Width with Gutenberg plugin in the block pattern list

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#36733]
### Description

Hey,

I have noticed the viewport width is showing incorrect, if I using the Gutenberg plugin.

Correct view with latest WordPress 5.8.2 without installed Gutenberg plugin:

<img width="326" alt="Bildschirmfoto 2021-11-22 um 13 02 55" src="https://user-images.githubusercontent.com/31563167/142858821-20c6da39-91e6-46de-8c56-4d55f73bdffb.png">

Wrong view with latest WordPress 5.8.2 and with installed Gutenberg plugin 11.9.1:

<img width="329" alt="Bildschirmfoto 2021-11-22 um 13 06 08" src="https://user-images.githubusercontent.com/31563167/142858993-a03c25a6-d1b3-40a3-a921-aa28f7dce2ca.png">

In my case "FSE" Full Site Editing is disabled.

My viewport width is 1300px.

```
register_block_pattern(
			'example-name',
			array(
				'title'   => __( 'example title', 'wphave'),
				'categories' => array( 'example-cat' ),
				'viewportWidth' => 1300,
				...
```

How I can solve this or is this an existing bug? If so, I think this should be solved before WordPres 5.9 will released. Thank you.

### Step-by-step reproduction instructions

1. Click on the block inserter
2. Click in Pattern
3. You will see the issue

### Screenshots, screen recording, code snippet

Correct view with latest WordPress 5.8.2 without installed Gutenberg plugin:

<img width="326" alt="Bildschirmfoto 2021-11-22 um 13 02 55" src="https://user-images.githubusercontent.com/31563167/142858821-20c6da39-91e6-46de-8c56-4d55f73bdffb.png">

Wrong view with latest WordPress 5.8.2 and with installed Gutenberg plugin 11.9.1:

<img width="329" alt="Bildschirmfoto 2021-11-22 um 13 06 08" src="https://user-images.githubusercontent.com/31563167/142858993-a03c25a6-d1b3-40a3-a921-aa28f7dce2ca.png">

### Environment info

WordPress 5.8.2
Gutenberg plugin 11.9.1
NO FSE Full Site Editing activated

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
Looks like this was resolved,  I wasn't able to reproduce this issue on my screen of the same size as shown below:

- WordPress 6.0.2
- Gutenberg version 14.0.2
- Twenty Twenty-Two theme

https://user-images.githubusercontent.com/41231764/189389582-702327db-a614-4d12-9116-c38e2693df30.mov

Closing this as resolved
