### ISSUE TITLE
Separator Styles Preview is to small

### ISSUE THREAD

**Issue by beatricekulcsar** [WordPress/gutenberg#36732]
## What problem does this address?

The preview of the Separator Styles in the side bar are too small. When trying to select the Separator Style it is very difficult to see the appearance. 

## What is your proposed solution?

Give the preview a smaller viewport width.

**Comment by carolinan** [comment]
This seems to be bugged, the style variation preview is not available.
Using Gutenberg, current trunk 13.8.0-rc.1:
![Separator style variation preview only show the text  "No Preview Available."](https://user-images.githubusercontent.com/7422055/181718855-f94260af-b4b2-4f06-ab6e-2124475ef342.png)

The block inserter preview is correct I believe. It looks like it is full width, not the default short width:
![block preview in the block inserter shows the block in full width](https://user-images.githubusercontent.com/7422055/181719330-90cafda5-a9da-405f-bd5c-5f9541108e0d.png)

**Comment by carolinan** [comment]
If I deactivate Gutenberg, the style variation preview looks like this (I am hovering over the dot variation):
![The style variation preview shows correctly ](https://user-images.githubusercontent.com/7422055/181720062-87e7272e-2dee-4b51-921d-2426aa74f41d.png)

**Comment by fabiankaegy** [comment]
@carolinan I agree that this appears to be fixed with the new Block Style Preview :) This was still when the previews were rendered inline in the Block Settings Sidebar.
