### ISSUE TITLE
Add support for custom Block Editor settings

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#36749]
## What problem does this address?
With the existing `block_editor_settings_all` filter, users can modify any supported Block Editor setting. However, if you add your own settings via this filter, they are ignored in the Block Editor. Allowing users to register support for their own custom Block Editor settings would greatly increase the extensibility of the Block Editor and provide developers with an easy way to surface data without the need to write their own REST API endpoints.  

## What is your proposed solution?
Add an additional JS filter to the supported Block Editor settings and allow users to add support for their own settings. A proposed solution is provided in #36750.

**Comment by skorasaurus** [comment]
interesting; could this also be applied to 3rd party settings that the use would supply, ref https://github.com/WordPress/gutenberg/discussions/34908 ?

**Comment by ndiego** [comment]
Took a quick look at #34908. in theory, yes this would allow you add a custom setting for API keys or whatnot and then fetch it in the Block Editor using something like this:

```
const { customApiKey } = useSelect(
	( select ) => {
		const { getSettings } = select( blockEditorStore );

		return {
			customApiKey: getSettings().customApiKey
		};
	},
	[ rootClientId ]
);
```

**Comment by fabiankaegy** [comment]
@ndiego since you closed the PR stating that it was no longer needed does that also apply to the issue here?

**Comment by Mamaduka** [comment]
Using site settings is probably better suited for similar cases. It also allows more control over who can edit or read a setting value.

```jsx
export function Edit() {
	const [ apiKey, setApiKey ] = useEntityProp(
		'root',
		'site',
		'custom_api_key'
	);

	return <>{ apiKey ? <p>Your API Key: { apiKey }</p> : null }</>;
}
```

**Comment by ndiego** [comment]
> @ndiego since you closed the PR stating that it was no longer needed does that also apply to the issue here?

Yes, this can be closed. I ended up solving the root issue in my own plugin by creating [custom entities](https://github.com/ndiego/block-visibility/blob/728821e295e95cd158efc816b153ff282fcafbcd/src/editor/index.js#L34) and fetching the data (settings) with [`useEntityRecord()`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-core-data/#useentityrecord). Works great.
