### ISSUE TITLE
Backport the link color move to the footer to WordPress Core

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#36743]
### Description

Apparently, the fix in #35425 was not back portedproperly into core. The issue is here to track that work. cc @nois

### Step-by-step reproduction instructions

 - Try using 2022 theme
 - Notice the header doesn't have an extra margin at the top on Gutenberg but does so with just WP trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by noisysocks** [comment]
Moved to https://core.trac.wordpress.org/ticket/54491.
