### ISSUE TITLE
Keep block font-size and color adjustments when change block type

### ISSUE THREAD

**Issue by spencer-j** [WordPress/gutenberg#36745]
Hello Gutenberg team,
would be nice if the font-size adjustments and also color, or anything else could be kept when a switch of the block is made.
For e.G 
When i switch a headline H2 with a color red selected to a paragraph block, it would be nice if this color adjustment would persist. 
This would make an editors life much easier.
Greets spencer

**Comment by mtias** [comment]
Hi there! Style properties that are shared between blocks should indeed be preserved when transforming blocks. @jorgefilipecosta can you look into this?

**Comment by jorgefilipecosta** [comment]
Sure I will look into fixing this issue.
