### ISSUE TITLE
missing single and page templates in sidebar if page-xxx.html is included in the block-templates folder

### ISSUE THREAD

**Issue by franmastromarino** [WordPress/gutenberg#36756]
### Description

Single Post and Page templates are missing in the side editor templates sidebar

You can use this theme to check the issue

https://wordpress.org/themes/wowmall/

### Step-by-step reproduction instructions

1. Include 6 page-xxxx.html files in the /block-templates folder
2. Go to Editor / Browse all templates

### Screenshots, screen recording, code snippet

Sidebar -> https://snipboard.io/OXz9ct.jpg
Folder -> https://snipboard.io/fje6nG.jpg

### Environment info

WordPress version: 5.8.2
Gutenberg version: 11.9.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting this @quadlayers.

I think this is a known issue. The UI for selecting templates is being replaced for Gutenberg 12 and WordPress 5.9, and from what I can tell, that will solve the problem. There's an issue tracking that here - https://github.com/WordPress/gutenberg/issues/36597.

The design for the new UI is shown in this comment - https://github.com/WordPress/gutenberg/issues/29630#issuecomment-954159446

**Comment by franmastromarino** [comment]
ok thanks @talldan

**Comment by franmastromarino** [comment]
hello @talldan 

the issue haven been fixed yet, im testing gutenberg 12.0.1
