### ISSUE TITLE
Block transform previews: editor crashes when previewing CoBlocks transforms

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#36758]
### Description

When a CoBlocks plugin transform is previewed in the block transform menu the editor crashes. This has appears to have been broken since [this commit](https://github.com/WordPress/gutenberg/commit/03d43d8424730212004cdf1ed842176ee9eec603) that changed some of the block preview settings.

### Step-by-step reproduction instructions

1. Install the latest CoBlocks plugin and Gutenberg trunk on local dev env
2. Add a core Gallery block
3. Click on the block transform menu and mouse over one of the CoBlocks options, eg. Carousel, and notice that editor crashes
4. Check out [parent commit](2285c0054c697f9c16799e9b9f0a48d6fd51cf78) of the [breaking commit](https://github.com/WordPress/gutenberg/commit/03d43d8424730212004cdf1ed842176ee9eec603) and repeat above and transforms should work as expected

### Screenshots, screen recording, code snippet

Before:

![transform-before](https://user-images.githubusercontent.com/3629020/142966786-3cee1738-691a-4993-8b3f-487ba3823840.gif)

After:

![transform-after](https://user-images.githubusercontent.com/3629020/142966810-68b9fddd-6767-4472-84f6-4b1ad72b9c4f.gif)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
@ellatrix I ran out of time to try and work out why only CoBlocks seems to be affected by this change, so not sure if problem is at our end or theirs.

**Comment by ntsekouras** [comment]
Thanks for reporting @glendaviesnz . I'll close this in favor of https://github.com/WordPress/gutenberg/issues/35229.

**Comment by glendaviesnz** [comment]
🤦 thanks  - no idea how I managed to overlook that issue in my search yesterday!
