### ISSUE TITLE
Site Editor: Provide a way to edit custom template names

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36773]
It should be possible edit the name of a template (or template part) that has been created from scratch.

One minimal approach would be to allow the template name to be clicked and edited directly:

https://user-images.githubusercontent.com/846565/143018310-5c5fe748-a8ad-46fa-b8e8-7746854e2f80.mp4

This action should be available on template list view as well:

<img width="1039" alt="Screenshot 2021-11-23 at 11 44 53" src="https://user-images.githubusercontent.com/846565/143018538-a2a9406f-d7d4-48d9-95b9-9584748589b5.png">

From this perspective perhaps a modal might work better. That same modal could be invoked from both the list view, and the editor view.

<img width="1160" alt="Screenshot 2021-11-23 at 11 55 03" src="https://user-images.githubusercontent.com/846565/143019869-09d50119-fb7d-4e63-abae-d79d2720c28d.png">

**Comment by Mamaduka** [comment]
@jameskoster, what do you think about using UI from Template Mode?

![CleanShot 2021-11-25 at 20 40 22](https://user-images.githubusercontent.com/240569/143478213-db5c2861-f051-4d11-b9b6-f52eb6314b48.png)

**Comment by jameskoster** [comment]
That seems a little prominent to me, but it would be good to be consistent for now, and revisit holistically later 👍
