### ISSUE TITLE
product category uses page.html insted of index.html, archive.html or taxonomy.html

### ISSUE THREAD

**Issue by franmastromarino** [WordPress/gutenberg#36771]
### Description

Hello

The block template routing is not working correctly

WooCommerce product category uses the page.html pages

https://wowmall.store/demo/product-category/t-shirt/

Please check at the bottom you'll see the comments block

You can use this theme for testing 

https://wordpress.org/themes/wowmall/

```
wowmall/block-templates
wowmall/block-templates/index.html
wowmall/block-templates/archive.html
wowmall/block-templates/taxonomy.html
```

### Step-by-step reproduction instructions

1. Install WooCommerce
2. Go to category

### Environment info

WordPress version: 5.8.2
Gutenberg version: 11.9.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by franmastromarino** [comment]
hello any update on this?

you can test this with Wowmall theme

https://wordpress.org/themes/wowmall/

here is the page with the issue

https://wowmall.store/demo/product-category/shoes/

**Comment by carolinan** [comment]
Hi
Can you help by providing any more details for reproducing this?
You mention that the comments block is displaying, but I do not see the comments block on the link.
How are you identifying that this is the page.html template?
When I view source, the body class says archive, not page:
`<body class="archive tax-product_cat term-t-shirt term-234 wp-embed-responsive theme-wowmall woocommerce woocommerce-page woocommerce-no-js">
`

**Comment by franmastromarino** [comment]
hello this issue has been fixed

thanks
