### ISSUE TITLE
Preset colors from the default palette are serialized as inline styles

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#36770]
In testing the new color UI component that shows up to 3 different palettes (default, theme, custom), I've noticed that preset colors from the default palette are serialized as inline colors, instead of having their class applied, like the theme colors.

## How to reproduce

- Use a theme with `theme.json` support, for example TwentyTwentyTwo.
- Add a paragraph block with a link.
- Select a preset color from the theme palette for text, a preset color from the theme palette for background, and a preset color from the theme palette for link.

Notice that the color is serialized in the inline `style` attribute of the block instead of being serialized as a class.

**Comment by oandregal** [comment]
I still can repro this. cc @jorgefilipecosta

**Comment by Mamaduka** [comment]
I'm removing this issue from WP 5.9 project board since RC1 was released last night. But we should try and fix this in a minor release.

**Comment by jorgefilipecosta** [comment]
This issue seems to be already fixed on Gutenberg and WordPress core, @oandregal would you be able to retest?

**Comment by oandregal** [comment]
I've retested this in the latest WordPress 5.9 and WordPress 5.8 with the latest plugin: it works as expected so it can be closed.
