### ISSUE TITLE
PHP: client-assets.php undefined property notice

### ISSUE THREAD

**Issue by vladanost** [WordPress/gutenberg#3677]
Gutenberg 1.7.0

## Issue Overview

Undefined property: WP_Post_Type::$template in /.../plugins/gutenberg/lib/client-assets.php on line 786

## Steps to Reproduce (for bugs)

1. Add or edit post
2. Notice appears

## Current Behavior

PHP notice is displayed

**Comment by aduth** [comment]
Should be fixed now by #3674.
