### ISSUE TITLE
Site Editor: undo problem with Cover block

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#36781]
### Description

When you insert the cover block in the Site Editor, it takes two undo actions to remove it. This is not happening for other blocks that I tested.

### Step-by-step reproduction instructions

1. Go to `wp-admin/site-editor.php`
2. Insert the Cover block anywhere on the homepage.
3. Press Undo. Notice that the action is not reverted.
4. Press Undo again. The Cover block is now removed.

### Environment info

WordPress version: 5.9-alpha-52232
Gutenberg version: 12.0.0-rc.1
Theme: Twenty Twenty-Two v1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@vindl PR is ready for review. I'm changing the "Site Editor" label to "Cover" since it's a general blog issue unrelated to the editors.
