### ISSUE TITLE
Block Based Themes are not compatible with Certain plugins

### ISSUE THREAD

**Issue by uniquesolution** [WordPress/gutenberg#36787]
### Description

I have tested the same html form created by the html form plugin https://wordpress.org/plugins/html-forms/ with php theme and the new block theme (fse theme) , but in FSE theme the form is not submitting. So there is some kind of compatibility issue in new theme. I am using the default TT1 Block theme. Can anybody have idea what will be the issue? The form work just fine when using Twenty twenty one or any other theme of old php based. See this test site for checking https://uniquesweb.co.in/betatguten/test-form/

### Step-by-step reproduction instructions

1. Install Wordpress 5.8.2 , install gutenberg plugin, install any block theme (FSE theme, for example tt1 block theme)
2. Install HTML Forms plugin https://wordpress.org/plugins/html-forms/
3. Create any simple form using the plugin and insert it on any page using the block provided by the plugin
4. Try to submit the form, its just refreshes the page but form not succesfully submitted.
5. Now change the theme to any other php based theme for example default twenty  twenty one theme.
6. Now again try to submit the form, this time form successfully get submit and shows the successful submission msg.

Need to know is the plugin is missing something to have compatible with block theme or block theme is missing some functionality that not allowing some plugins to work properly ? 

### Environment info

Wordpress 5.8.2 to 5.9-alpha-52231
gutenberg plugin - ver. 11.9.1
Active Theme - TT1 Blocks (tt1-blocks) ver. 0.4.7
HTML Forms plugin - ver. 1.3.22

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment]
Hey there! Thanks for opening this issue @uniquesolution. By chance, have you reached out to the plugin authors yet? If so, I'd recommend doing so as a first step. They will ultimately know more about the code required on their end and what might be interfering, including whether it's related to block themes!

**Comment by uniquesolution** [comment]
Yes, I have already posted in forum support of plugin too. https://wordpress.org/support/topic/form-is-not-submitting-successfully/

But I am sure about this that this issue is only coming up with Block theme. For testing purpose I have also created a demo instawp wordpress setup to check it. https://togedu.us2.instawp.xyz/
Login detail:
Username: wp-admin
Password: 4yenISr^#^gmumBB)7

Currently TT1 Blocks theme is activated and you can check that form is not working, but when you choose any php based theme it work, You can try any other block theme and it will stop working.

**Comment by annezazu** [comment]
Very strange - I can replicate this! @jffng  do you have any insight here as to what might be causing this and where the problem lies (block themes or the plugin)?

**Comment by uniquesolution** [comment]
@annezazu and @jffng , as per my investigation the form plugin is using `<?php wp_footer(); ?>` for output in file plugins/html-forms/views/form-preview.php , and in TT1 Block theme or any other block theme, templates are created through html files and wp_footer is directly handled by wordpress in this case, So it appears to be some conflict between wordpress default wp_footer and the plugins inclusion. May be this clue help you to figure out what happening.

**Comment by uniquesolution** [comment]
I have created a demo test site at my server, to check this issue, but every situation HTML form is not working with block theme. The page where I added the form https://uniquesweb.co.in/demo/testing/sample-page/
Here is the login detail to check it.
Please check it 
https://uniquesweb.co.in/demo/testing/wp-admin/
username: wp-administrator
password:- 123abc789

**Comment by carolinan** [comment]
I have not been able to reproduce this with 5.9 beta 3. (Gutenberg not active, multiple block themes tested)
Having said that, plugin developers need to test their plugins carefully and update their plugins if needed.

**Comment by uniquesolution** [comment]
Its already resolved in newer version of wordpress, so there is no issue with block theme now.
