### ISSUE TITLE
Long URL forces link edit button outside display area 

### ISSUE THREAD

**Issue by kriskarkoski** [WordPress/gutenberg#36780]
### Description

When linking to a long URL the edit button is forced outside of the visible area, requiring you to scroll to see it. This only occurs with the Gutenberg plugin active and does not occur in the core block editor.

### Step-by-step reproduction instructions

1. Open the post or page editor
2. Add text
3. Link a long URL to the text, ex. wordpress.org/mz9dbSqC1TwS1hXFdWR6pa9GCqOEDfnLH6uq7QMpHjegIjCW9RV9hiBSWGW5gJGwh9jyPID0RtDO4xnViBBm74kBrKMEnogy5it
4. Click the linked text to edit the URL and note the absence of the edit button. It can be found by scrolling to the right.

### Screenshots, screen recording, code snippet

GB 11.9.1

<img width="382" alt="Screen Shot 2021-11-23 at 8 37 35 AM" src="https://user-images.githubusercontent.com/1900444/143034988-c74bc572-118e-4eba-a127-05140768e73c.png">
<img width="378" alt="Screen Shot 2021-11-23 at 8 37 40 AM" src="https://user-images.githubusercontent.com/1900444/143034992-8ff4283c-e047-421c-a0c7-a9aa36827af5.png">

WP 5.8.2 (Gutenberg plugin deactivated)

<img width="374" alt="Screen Shot 2021-11-23 at 8 39 01 AM" src="https://user-images.githubusercontent.com/1900444/143035052-c8b82c2c-db9b-4804-925f-b4f40a67aa80.png">

### Environment info

- WP 5.8.2
- Gutenberg 11.9.1 (issue only occurs with GB active)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by cngodles** [comment]
Wordpress 5.8.2, Gutenberg 12.0.1 (active)

Windows, Chrome latest. Might be why I have scroll bars in comparison.

<img src="https://user-images.githubusercontent.com/5685764/143343926-f88f86b1-db1b-4cad-9353-b19fe58b41ed.png" width="400">

<img src="https://user-images.githubusercontent.com/5685764/143344213-ca4b98a4-3c6b-4543-bf8d-c53e5ca3ffc8.png" width="400">

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; this has been fixed just yesterday at https://github.com/WordPress/gutenberg/issues/36961 and will be in an upcoming version of Gutenberg.

**Comment by sabernhardt** [comment]
As [reported on Trac](https://core.trac.wordpress.org/ticket/57404), 36961 fixed the long URLs in the modal (`.block-editor-link-control__search-item-info`), but not when that URL is also the _visible_ link text (`.block-editor-link-control__search-item-title`).

Chrome/Windows still has the horizontal scrollbar with Gutenberg 15.7, but Firefox wraps the URL.

![long URL text does not wrap or truncate](https://user-images.githubusercontent.com/17100257/236514351-b4fe23eb-065c-424a-bb06-8e8d95347a01.png)

Reopening this issue might be better than creating a new one.

**Comment by pixelvine** [comment]
This seems to be an issue again. I'm on wordpress version 6.3.2.

Cut Off URL and Link Option Icons

![Screenshot 2023-10-20 at 11 54 29 AM](https://github.com/WordPress/gutenberg/assets/68333878/64dd6409-1ffd-4095-8f8c-00f6a633a51b)

![Screenshot 2023-10-20 at 11 54 42 AM](https://github.com/WordPress/gutenberg/assets/68333878/a1a45af6-68dd-4e50-9886-5446ec45e6f6)

.block-editor-link-control Styling

![Screenshot 2023-10-20 at 11 55 09 AM](https://github.com/WordPress/gutenberg/assets/68333878/c2e2d83a-5a05-4144-a1c4-8826c979a604)

If I set the .block-editor-link-control max-width to something higher like 800px, the rest of the url and the edit icons are revealed.

![Screenshot 2023-10-20 at 11 56 44 AM](https://github.com/WordPress/gutenberg/assets/68333878/72a36d61-abb3-48a9-90f0-7b97c82e6972)

If it is going to be constrained to 350px, even if the url overflows, the edit icons should wrap to a new line to prevent them from being hidden.
