### ISSUE TITLE
Grouping and ungrouping the Header block results in loss of data

### ISSUE THREAD

**Issue by zaguiini** [WordPress/gutenberg#36788]
### Description

When you group the `Header` block and then ungroup it, all content inside the `Header` is lost and only the `Header` block itself remains on the page.

Apparently, the contents of the template part are lost. There is no way to re-select a template.

Adding another `Header` immediately below the affected header does not open the template part selector, resulting in another empty header. I'm not sure if this is related to the same problem or another issue.

### Step-by-step reproduction instructions

1. Open the block editor;
2. Insert the `Header` block;
3. Create a new group with the `Header` inside;
4. Click on the `...` on the newly created group;
5. Click "Ungroup".

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26530524/143089756-27a84918-0a2b-493f-9660-4dd4af13fcb6.mov

### Environment info

- WordPress 5.8.2;
- Gutenberg 11.9.1.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Tested and confirmed this!

**Comment by noisysocks** [comment]
Noting here that this is very possibly the same issue as https://github.com/WordPress/gutenberg/issues/36937.
