### ISSUE TITLE
Focussed destructive menu items inherit default styles

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36816]
When applying `isDestructive` to a `MenuItem` it inherits the default styles when focussed:

https://user-images.githubusercontent.com/846565/143227438-c3edff29-1f3d-4673-a0e4-04341eb76ec9.mp4

The thicker border seems fine, but a destructive action should probably always have the red highlight.

**Comment by ramonjd** [comment]
I've tested this on trunk in Safari, FF and Chrome (MacOS) and can't replicate. 

![Kapture 2021-12-13 at 12 05 13](https://user-images.githubusercontent.com/6458278/145737564-216c401a-b0fc-4a1c-873a-499d666245b7.gif)

Did you fix this in https://github.com/WordPress/gutenberg/pull/36915?

**Comment by jameskoster** [comment]
Yes :)
