### ISSUE TITLE
Docs - Next link in footer is always to Extensibility page

### ISSUE THREAD

**Issue by ptasker** [WordPress/gutenberg#3681]
## Issue Overview
All doc pages on https://wordpress.org/gutenberg/handbook/ have a link to Extensibility page. They don't appear to be respecting their place in the 'tree' of pages.

## Screenshots / Video

<img width="526" alt="wordpress" src="https://user-images.githubusercontent.com/535651/33287796-da7ea79c-d387-11e7-862f-210bb45c40de.png">

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
This looks fixed to me now:

![image](https://user-images.githubusercontent.com/36432/35166093-87c9a7ac-fd05-11e7-90a9-6c36d5892362.png)
