### ISSUE TITLE
<!DOCTYPE html> is missing in the Block pattern preview IFRAME and breaks the design of blocks

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#36812]
### Description

Hey together,

I have design differences between the editor output of blocks and the view of the block pattern preview.

I could figured out, that this issue comes from the missing `<!DOCTYPE html>` inside the block pattern preview iframe.

Please add this `<!DOCTYPE html>` to get the same design results like the block and frontend view.

### Step-by-step reproduction instructions

1. Go to the block editor
2. Click the block inserter
3. Click on pattern
4. Compare the preview of the block pattern and block editor result

IMPORTANT: It's seems without the `<!DOCTYPE html>`, the display: flex model can't interpreted in the correct way.

If you want to test it, please use an example which use items that using the flex model. Like my example screenshots.

### Screenshots, screen recording, code snippet

Correct view in block editor and frontend:
<img width="1350" alt="Bildschirmfoto 2021-11-24 um 11 41 16" src="https://user-images.githubusercontent.com/31563167/143223439-2af40440-44d1-4fff-ab6f-b683ad876f4f.png">

Wrong view in the block pattern preview iframe:
<img width="332" alt="Bildschirmfoto 2021-11-24 um 11 40 58" src="https://user-images.githubusercontent.com/31563167/143223454-ce44ebdc-c42b-4083-a872-dac181e7e154.png">

### Environment info

WordPress 5.8.2
Gutenberg 11.9.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Tagging @ryelle in case you have any insights here :)

**Comment by ryelle** [comment]
@CreativeDive What browser are you seeing this in? Do you see the same issue with the "Pricing Table" or "Three columns of text" patterns?

**Comment by CreativeDive** [comment]
Hello @ryelle @annezazu 

this video demonstrate how are the differences between the view with and without the `<!DOCTYPE html>`.

https://user-images.githubusercontent.com/31563167/146352888-acfe6844-3de1-4f45-b179-b2ed22d90c4f.mp4

In my case I work with the Safari browser (Version 15.1 (17612.2.9.1.20)) on MacOS.

The view of the default patterns "Pricing Table" is the same in both cases, but this example is not working like the flex model in my example.

Here are two examples, to compare this case:

### Example 1: The source code of the embedded iframe for the block pattern preview:

<img width="288" alt="Bildschirmfoto 2021-12-16 um 10 27 34" src="https://user-images.githubusercontent.com/31563167/146345411-dfe7146b-7a70-47df-bb6e-5f7c6c64a1fa.png">

### Example 2: The source code, if a website is embedded inside an iframe:

<img width="353" alt="Bildschirmfoto 2021-12-16 um 10 35 10" src="https://user-images.githubusercontent.com/31563167/146346027-c6cbb367-cf93-4b7a-9246-0a4e6336922a.png">

In the case of the block pattern preview iframe, there is no `<!DOCTYPE html>`. And you can also see if a doctype is there in a document, you will see this in the iframe source code like example two.

Finally we know, the very very important document declaration `<!DOCTYPE html>` is not included in the iframe for the block pattern preview.

As a web developer we know, the results of the rendered HTML can be different, depending on which document declaration `<!DOCTYPE html>` we use.

So HTML is interpreted in different ways. One time in the way with `<!DOCTYPE html>` for the block editor and frontend itself and one time in the other way without `<!DOCTYPE html>`.

You can test the differences by yourself. Create an document with a display flex model container. With `<!DOCTYPE html>` all the flex items have the same height. Without `<!DOCTYPE html>` all the flex items have a different height, if the length of the content is not the same.

Do you can fix this please?

**Comment by CreativeDive** [comment]
@ryelle is this description and screen recording helpful for you to get a overview about this issue here?

**Comment by CreativeDive** [comment]
@ryelle @annezazu hey I already have provided more informations. This issue is very easy to fix. No response here. Do you can fix this please before WordPress 5.9 will release?

The same here: https://github.com/WordPress/gutenberg/issues/36733

Nothing happened but the WP 5.9 release will come?!

**Comment by annezazu** [comment]
There are a lot of priorities to balance with WordPress 5.9. You can see the full project here: https://github.com/WordPress/gutenberg/projects/62 High priority bugs will be prioritized currently, especially since we're leading up to the RC1 period.

**Comment by CreativeDive** [comment]
@annezazu can't understand why issues, which are very easy to fix could not be processed faster.

Here is a priority high issue from may this year. https://github.com/WordPress/gutenberg/issues/31753

This issue is still open.

**Comment by annezazu** [comment]
I hear you! There are a ton of high priority projects and features to ship with each release. I've flagged this as best as I can and will continue to do so as fixes will always continue to happen with WordPress in due time. In turn, please keep in mind that what might be a major priority for you might not always be a major priority for the project as a whole. Thank you for continuing to flag these problems -- please keep doing so! It only helps the software continue to improve.

**Comment by CreativeDive** [comment]
It seems this is fixed now, I can see there is a `<!DOCTYPE html>` included in the pattern preview by the latest WordPress version.
