### ISSUE TITLE
DropZone component listeners not working on latest Chromium browser update

### ISSUE THREAD

**Issue by alvinchevolleaux** [WordPress/gutenberg#36824]
### Description

The onHTMLDrop event listener on the `DropZone` component seems to have stopped working on the latest version of Chrome (Version 96.0.4664.45 (Official Build) (64-bit)) but only on Windows, this doesn't appear to affect Chrome on Mac OS. 

It seems the `DropZone` component now only handles drag and drop as files rather than HTML.

In our particular case we have a raw transform handler:

```
transforms: {
	from: [
		{
			type: 'raw',
			isMatch: true,
			isMultiBlock: true,
			priority: 1,
			transform: function,
		},
	],
},
```

This never gets triggered on this version of Chrome. We have found a workaround which involves adding a new transform

```
transforms: {
	from: [
		{
			type: 'files',
			isMatch: true,
			isMultiBlock: true,
			priority: 1,
			transform: function,
		},
	],
},
```

### Step-by-step reproduction instructions

1. Drag and drop into a Gutenberg DropZone component

### Environment info

Gutenberg 10.7.4
Windows 10 / 11
Chrome Version 96.0.4664.45 (Official Build) (64-bit)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by glendaviesnz** [comment]
Thanks for reporting this @alvinchevolleaux. For me on Chrome 96.0.4664.55  the onHTMLDrop method seems to be capturing the dropped HTML correctly:

![dropzone](https://user-images.githubusercontent.com/3629020/143334459-cc8e75a4-67b4-496a-b4d9-c2c980d1b991.gif)

I also tried with a custom dropzone in a block and it seemed to capture html drop as expected separated to a file drop:

![more-drop](https://user-images.githubusercontent.com/3629020/143364748-81db770e-20fe-41a3-a825-b2a9e43cfa94.gif)

Are you able to provide a screen capture with some debugging of what you are seeing, or some more details about exactly what sort of html you are dragging and dropping, and how it should be transformed?

**Comment by alvinchevolleaux** [comment]
So this is a basic DropZone component that just does a `console.log` on `onHTML` and `onFilesDrop` events. 

On the affected browser (Chrome Version 96.0.4664.45 (Official Build) (64-bit) on Windows 11) this is the behaviour. As you can see it treats the drop as a file drop:
![drag_drop_issue1](https://user-images.githubusercontent.com/3525721/143867442-8d6b2ef3-531c-40d2-9036-a333a8494432.gif)

However on previous version of Chrome (and in this case Firefox) we get the expected onHTMLDrop triggered:
![drag_drop_issue2](https://user-images.githubusercontent.com/3525721/143867469-c78cc00a-2ff8-4469-b1e7-6090e3bab366.gif)

Are you on Windows? The same issue doesn't seem to affect Chrome 96 on OSX.

**Comment by glendaviesnz** [comment]
> Are you on Windows? The same issue doesn't seem to affect Chrome 96 on OSX.

No on OSX - sorry, I didn't interpret your note in the description as it being a Windows only problem, just that you were testing on Windows - apologies for causing you extra testing and clarification time.  I have updated the description to clarify that this appears to be a windows only problem.

**Comment by alvinchevolleaux** [comment]
> - sorry, I didn't interpret your note in the description as it being a Windows only problem, just that you were testing on Windows - apologies for causing you extra testing and clarification time. I have updated the description to clarify that this appears to be a windows only problem.

Yes sorry should have specified. It also seems to effect the latest version of Edge too on Windows so it seems to be Chromium browsers on Windows (10 and 11 tested) that are affected.
