### ISSUE TITLE
Site Editor: Inserter is pushed over too far when the W menu is opened

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36823]
<img width="506" alt="Screenshot 2021-11-24 at 14 56 39" src="https://user-images.githubusercontent.com/846565/143261597-4adf5468-3cba-4e6e-ac5c-d2b9a021712c.png">

When you open the W menu in the Site Editor, the padding on the top bar is too large which is pushing the Inserter button over unnecessarily.

**Comment by paaljoachim** [comment]
Associated issue:
[Site Editor] Templates list screen - make the screen thinner and add truncation to site title.
https://github.com/WordPress/gutenberg/issues/36657

**Comment by Mamaduka** [comment]
This issue is fixed now.

**Comment by jameskoster** [comment]
True:

<img width="567" alt="Screenshot 2021-11-26 at 12 13 10" src="https://user-images.githubusercontent.com/846565/143579417-1a984dd6-90ab-4640-bd32-40f15e145ee0.png">
