### ISSUE TITLE
Missing filters/possibility to change before_title for legacy widgets like nav_menu in new Gutenberg widgets editor

### ISSUE THREAD

**Issue by kubiqsk** [WordPress/gutenberg#36830]
### Description

currently it's not possible to change widgets `before_title` from `<h2>` to `<h4>` when you use new gutenberg widgets environment and legacy widgets like `nav_menu`
it's calling `the_widget` with `$arg` without any `apply_filter` in `wp-includes/blocks/legacy-widget.php`

### Step-by-step reproduction instructions

1. Go to `/wp-admin/widgets.php`
2. add Legacy Widget - Navigation Menu
3. Enter some title
3. On frontend it will be rendered as `<h2>` but there is no way how to change it to something else, like `<h4>` - no hook

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@kevin940726 any thoughts here?

**Comment by kevin940726** [comment]
I'm not really experienced with WP PHP filters, maybe @noisysocks knows?

**Comment by kubiqsk** [comment]
I think there are two possibilities

1. We can add some filter only for `render_block_core_legacy_widget` function in `/wp-includes/blocks/legacy-widget.php`, like:
```
$args = apply_filters( 'legacy_widget_args', $args, $instance, $widget_object );
```

2. or to make it more global and universal add filter to `the_widget` function in `/wp-includes/widgets.php`, like:
```
$args = apply_filters( 'the_widget_args', $args, $instance, $widget );
```

**Comment by noisysocks** [comment]
Double checking: Was there a way to do this previously? That is, is this a limitation of `the_widget` or is a limitation of the Legacy Widget block? I think it's the former. 

Adding a new `the_widget_args` filter to `the_widget` makes sense to me.

~We could also consider passing `$args` by reference to the existing `the_widget` filter, but that's more obtuse.~ **edit:** Actually, don't think that's possible using hooks.

We will need to make this change in Core, not Gutenberg.

**Comment by noisysocks** [comment]
Moved this here: https://core.trac.wordpress.org/ticket/55175
