### ISSUE TITLE
Editor crashes when publishing a post type with no title support

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#36838]
### Description

In the current Gutenberg plugin, when a post type has no post title support, the editor crashes when Save Draft or Publish are clicked. This does not happen in WordPress 5.8.2 without the Gutenberg plugin activated.

This seems similar to #29921, which crashed the editor when the code editor view was opened.

### Step-by-step reproduction instructions

1. Register a post type with no title support.
2. Create a new post of that post type.
3. Add something to the first block.
4. Click publish.

### Screenshots, screen recording, code snippet

The error message is https://gist.github.com/jeremyfelt/fc0de6099f6679bf307e4a36df6ce8d2, I don't have a Gutenberg development environment setup right now to see the non-minified error, but I am able to reproduce this on two sites locally.

### Environment info

- WordPress 5.8.2, Gutenberg 12.0.0 (and 11.9.1)
- Firefox 94
- Mac OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @jeremyfelt

I could reproduce the issue with Gutenberg trunk/12.00. I tried with Firefox and Chrome.

Can you provide more details?

**Comment by jeremyfelt** [comment]
@Mamaduka Thanks for taking a look! I was wrong on the no-title support. There was also one more piece of code I had active filtering the post title that was broken by 647547a7ab9947d212a8ba89a6054d91b546174a that ended up being the issue. I'm going to open a new enhancement request with more information for post types without titles.

**Comment by Mamaduka** [comment]
Thanks, @jeremyfelt.
