### ISSUE TITLE
Core palette opt out not working in site editor

### ISSUE THREAD

**Issue by Andrew-Starr** [WordPress/gutenberg#36852]
### Description

With the new `corePalette` and `coreGradients` keys, themes can opt out of displaying the core color palette.

This works correctly in the post editor, but in the site editor the core color palette and gradients are still available.

### Step-by-step reproduction instructions

Add the opt outs to theme.json as detailed in https://github.com/WordPress/gutenberg/pull/36492 and https://github.com/WordPress/gutenberg/issues/36407

```
"settings": {
		"color": {
			"corePalette": false,
			"coreGradients": false
```

Navigate to 'Posts' > 'Edit' to edit a post, and the core color palette is correctly removed from view.

Navigate to 'Appearance' > 'Styles' > 'Colors' > 'Elements' > 'Background', and see that the core color pallete and gradients are still available. This should not be the case

### Environment info

WP 5.8.2
Gutenberg 12.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by oandregal** [comment]
This has been fixed by https://github.com/WordPress/gutenberg/pull/36639 which will be part of Gutenberg 12.1, to be released in a few days.
