### ISSUE TITLE
Selecting a block in a container, then pressing enter inserts an empty block at the top of the container

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36857]
### Description

I would expect pressing enter to insert the empty block directly beneath the selected one. But here's what currently happens in both the post and site editors:

https://user-images.githubusercontent.com/846565/143431853-11f65981-294d-4e90-b62e-3393929ca7bc.mp4

### Step-by-step reproduction instructions

1. Open a document in the post or site editor
2. Insert a group block
3. Insert some child blocks inside the group
4. Select a child block
5. Press enter
6. Notice the empty block added to the top of the group

**Comment by Mamaduka** [comment]
The issue was fixed via #37453.
