### ISSUE TITLE
Site Editor: Add New - Custom/General template

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#36860]
Associated: 
[Site Editor] Templates list screen overview
https://github.com/WordPress/gutenberg/issues/36597

## What problem does this address?

In Templates.
When clicking "Add New". There is no option to create a general/custom template.

![Add-new-template](https://user-images.githubusercontent.com/5323259/143433529-93391a0f-dee8-428c-8de2-4558a2bce6f9.jpeg)

## What is your proposed solution?

We should be able to create a "Custom" template.

--

I initially added some info about it here:
Site Editor: Create consistency between Template and Templates Part - "Add New" modal/dropdown.
https://github.com/WordPress/gutenberg/issues/36741

**Comment by paaljoachim** [comment]
@annezazu 

I am able to add a new template for "Front Page", "Archive" and "Search" but not a custom/general template.
Are there plans to extend?

Anne made this reply:

> +1 to this question. I originally had the call for testing setup to add a custom/general template but now see this isn't an option. Going to have folks select Archive to move the task along but ideally would like them to create a custom template.
> 
> cc @kevin940726 

Here: https://github.com/WordPress/gutenberg/issues/36741#issuecomment-978066339

**Comment by jameskoster** [comment]
I think this goes hand-in-hand with both #36773 and #36664. 

At the moment the name and description are hard coded. But custom templates will require those to be supplied by the user.

**Comment by kevin940726** [comment]
I believe this is how it worked before. I'm not sure what needs to be done to support adding a _custom_ template. See https://github.com/WordPress/gutenberg/pull/26941 and https://github.com/WordPress/gutenberg/pull/27235.

**Comment by jameskoster** [comment]
Yup, custom templates are an enhancement. 

It's already possible to create them in the post editor using this UI:

<img width="311" alt="Screenshot 2021-11-30 at 10 26 30" src="https://user-images.githubusercontent.com/846565/144030250-b1b1224a-1562-4759-8c56-9dd500fb21b6.png">

We need to bring that functionality to the templates list view as well. 

A little thought will be required to get the name / description right in the popover. @paaljoachim did you have any thoughts there?

**Comment by paaljoachim** [comment]
@jameskoster I am not fully sure I am on the same track so to speak, but this is what I am thinking.

Starting with what we have currently. The Add New drop down showing various Template types and their description.
I would just add Custom to the drop down list as well as adding a generic description.

![Custom-template](https://user-images.githubusercontent.com/5323259/144098360-2fc6b8b3-408d-48ed-86ed-c30370d82aff.jpg)

User should then be able to edit a template and modify the descriptions of the custom templates. (Could do so through the 3 dot menu or directly inside the sidebar of a selected template.)

**Comment by jameskoster** [comment]
I think the description may need to be a little more elaborate, and explain where these "custom template"s can be used.

**Comment by paaljoachim** [comment]
Yes. That it does. Here is one suggestion. I assume it would be something like this (from my limited understanding).
"Create a custom template which can be used by any page or post by opening the Template sidebar panel and selecting the template you would like to use." I assume there is something more needed.

**Comment by jameskoster** [comment]
Maybe something like:

> Custom
> Can be applied manually to any post or page

What do you think?

**Comment by paaljoachim** [comment]
That is right on the dot! As the template is applied to a post or page.
Having the text "Can be applied manually to any post or page." Is exactly what it does!

**Comment by annezazu** [comment]
+1 I really like that phrasing!

**Comment by paaljoachim** [comment]
A use case.

I noticed the following brought up in the Slack channel: #fse-outreach-experiment
https://wordpress.slack.com/archives/C015GUFFC00/p1638588535130900

Point number 3.
"Could not find the Add New button on Templates screen. It was available only on template parts screen."

I am bringing it up here as another reason why we also need the Custom/General template in WP 5.9.
Through the theme or the user the Front Page, Search and Archive templates might already be added so that the Add New button will not any longer be seen.

![Screenshot 2021-12-06 at 21 37 00](https://user-images.githubusercontent.com/5323259/144918725-21555671-84d3-47dd-b6f6-4da95ff99d07.jpg)

Adding in the General/Custom option will always keep the Add New button visible in the Templates screen.

**Comment by ndiego** [comment]
Yes, I agree with @paaljoachim. The lack of an Add New button is a bit disorienting and would be a huge add if it can be included in 5.9.

**Comment by kevin940726** [comment]
Pinging @priethor, @noisysocks, and @youknowriad for whether or not to include this in 5.9. (I have no idea how this feature works though 😅 )

**Comment by Mamaduka** [comment]
I think it could be similar to how we handle it in `PostTemplateActions` - https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-post/src/components/sidebar/template/actions.js#L64-L118

**Comment by priethor** [comment]
@kevin940726 Although it can feel strange to the most advanced/tinkerer users to be able to add custom templates in the Template Editor and not in the Site Editor (less advanced users won't use the Template Editor), this will be the first version of the templates list, so although a nice to have, I don't think this is a blocker.

There is already a lot of work and testing in the works in #36488 and we should be mindful of the timeline, but I'm also happy to include it if contributors feel it is ok to add it at this late stage and somebody has the bandwidth to implement it 🙂

**Comment by kevin940726** [comment]
Works for me! Thank you @priethor!

**Comment by annezazu** [comment]
Noting this remains a point of confusion for the Site Editor functionality and came up in the [fourteenth call for testing for the FSE Outreach Program:](https://make.wordpress.org/test/2022/04/28/fse-program-testing-call-14-rallying-recipe-reviewers/#comment-2462)

>I think I prefer creating a new template in the Site Editor and not the Post or Page editor. I would like Post or Page templates to be choices under “Add New” on the Templates screen in the Site Editor.
