### ISSUE TITLE
Remove margins from blocks in a flex container

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#36867]
### Description

When items are stacked horizontally in a flex container the top margin causes wonky alignment:
<img width="247" alt="Screenshot 2021-11-25 at 12 46 46" src="https://user-images.githubusercontent.com/275961/143444868-5c01526b-28bf-4271-bb31-ef6e34e043cd.png">
<img width="512" alt="Screenshot 2021-11-25 at 12 46 54" src="https://user-images.githubusercontent.com/275961/143444875-a96cca21-4a7a-40fb-9fd0-34e101377d78.png">

### Step-by-step reproduction instructions

Add this markup to a post:
```
<!-- wp:group {"layout":{"type":"flex"}} -->
<div class="wp-block-group">

	<!-- wp:paragraph -->
	<p>one</p>
	<!-- /wp:paragraph -->

		<!-- wp:paragraph -->
		<p>two</p>
		<!-- /wp:paragraph -->


	<!-- wp:paragraph -->
	<p>three</p>
	<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
```

Confirm that the paragraphs aren't aligned.

### Screenshots, screen recording, code snippet

<img width="247" alt="Screenshot 2021-11-25 at 12 46 46" src="https://user-images.githubusercontent.com/275961/143444868-5c01526b-28bf-4271-bb31-ef6e34e043cd.png">

### Environment info

- Using blockbase

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Andrew-Starr** [comment]
This behaviour appears to be coming from the Blockbase theme.

I tested in other themes that don't add additional CSS to the paragraphs and this issue is not present.

In blockbase theme, see _/assets/ponyfill.css_ L207:

```
p.wp-block.wp-block-paragraph,
*[class^="wp-container"] > * + p,
*[class^="wp-container"] > p + *,
p {
	margin-top: 1em;
}
```

It may be worth opening an issue in the theme: https://github.com/Automattic/themes/tree/trunk/blockbase

**Comment by scruffian** [comment]
Sorry, you're right 🤦 

I made a PR here: https://github.com/Automattic/themes/pull/5104
