### ISSUE TITLE
Server-side rendered blocks produce extraneous whitespace in output

### ISSUE THREAD

**Issue by donnapep** [WordPress/gutenberg#3687]
## Issue Overview
Server-side rendered blocks produce extraneous whitespace in output

## Steps to Reproduce (for bugs)
1. Install and activate [Sensei](https://github.com/automattic/sensei/tree/update/block-support) (you’ll need the `update/block-support`​ branch)
2. Enable Sensei's REST API by adding the following to the `wp-config.php` file:
```
define( 'SENSEI_FEATURE_FLAG_REST_API_V1', true);
```
3. Download [Sensei Courses](https://github.com/Automattic/sensei-courses). `cd` into the directory and run `npm install` and `npm run build`. Upload the plugin to your site and activate it (ensure that Gutenberg is activated prior to activating Sensei Courses).
4. Create a course by going to _Courses_ > _Add New_. Give your course a title and description.
5. Create a new page and add the _Courses_ block.
6. Create another page and add the `[sensei_courses]` shortcode.
7. Browse to both pages on the front-end.
8. Notice that, although both pages are using the same PHP code for rendering, the page containing the _Courses_ block is outputting extra whitespace.

Chrome 62.0.3202.94 on MacOS 10.12.6 and WordPress 5.0-alpha-42247, Gutenberg 1.7.0.

## Expected Behavior
The HTML generated by the block should be the same as the HTML generated when using the shortcode.

## Current Behavior
The HTML generated by the block includes extraneous `<br>` and `<p>` tags.

### Shortcode HTML (Correct)
![correct](https://user-images.githubusercontent.com/1190420/33315243-25011770-d3fe-11e7-8a6d-579362144e57.jpg)

### Block HTML (Incorrect)
![incorrect](https://user-images.githubusercontent.com/1190420/33315250-295b24c8-d3fe-11e7-9dca-248e31ce967e.jpg)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by aduth** [comment]
Fixed by #3769
