### ISSUE TITLE
Hide Post Content block in the Post Editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36870]
It's currently possible to insert the Post Content block in a post, which creates this lacklustre outcome:

<img width="667" alt="Screenshot 2021-11-25 at 13 25 36" src="https://user-images.githubusercontent.com/846565/143449671-a0f41560-b856-4ce7-93ee-fc8b6c60cf36.png">

It would probably make more sense to simply not surface this block in the post editor, except in situations where it is applicable. The only such situation I can think of right now is inside a Query block.

**Comment by annezazu** [comment]
Still applicable in WP 6.2 and GB 15.7.1.

**Comment by richtabor** [comment]
I wrote this down the other day to post as well. Just a bit odd its accessible in the post editor.
