### ISSUE TITLE
Different output in php/js for theme.json

### ISSUE THREAD

**Issue by franmastromarino** [WordPress/gutenberg#36875]
### Description

Hello

The output for this setting is different in the site editor and the frontend

theme.json

`{
	"version": 1,
	"settings": {
		"custom": {
			"preset": {
				"h1": {
					"color": {
						"default": "var(--wp--preset--color--color-four)"
					},
					"typography": {
						"fontFamily": "var(--wp--preset--font-family--pt-sans-narrow)",
						"fontSize": "3.33rem",
						"lineHeight": "4.77rem",
						"letterSpacing": "0.2rem",
						"textTransform": "uppercase",
						"fontWeight": "700",
						"fontStyle": "normal"
					},
					"margin": "1.66rem 0rem 0.5rem 0rem"
				}
			}
		}
	}
}`

Frontend output

`	--wp--custom--preset--h1--color--default: var(--wp--preset--color--color-four);
	--wp--custom--preset--h1--typography--font-family: var(--wp--preset--font-family--pt-sans-narrow);
	--wp--custom--preset--h1--typography--font-size: 3.33rem;
	--wp--custom--preset--h1--typography--line-height: 4.77rem;
	--wp--custom--preset--h1--typography--letter-spacing: 0.2rem;
	--wp--custom--preset--h1--typography--text-transform: uppercase;
	--wp--custom--preset--h1--typography--font-weight: 700;
	--wp--custom--preset--h1--typography--font-style: normal;`

Site editor output

`	--wp--custom--preset--h-1--color--default: var(--wp--preset--color--color-four);
	--wp--custom--preset--h-1--typography--font-family: var(--wp--preset--font-family--pt-sans-narrow);
	--wp--custom--preset--h-1--typography--font-size: 3.33rem;
	--wp--custom--preset--h-1--typography--line-height: 4.77rem;
	--wp--custom--preset--h-1--typography--letter-spacing: 0.2rem;
	--wp--custom--preset--h-1--typography--text-transform: uppercase;
	--wp--custom--preset--h-1--typography--font-weight: 700;
	--wp--custom--preset--h-1--typography--font-style: normal;`

### Step-by-step reproduction instructions

1. Add rule to theme.json
2. Go to Site editor
3. Go to frontend

### Environment info

WordPress version: 5.8.2
Gutenberg version: 11.91

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by franmastromarino** [comment]
any update on this?

**Comment by annezazu** [comment]
Tagging @oandregal to share any insights :)

**Comment by oandregal** [comment]
Thanks for sharing and tagging! I've got a fix for this at https://github.com/WordPress/gutenberg/pull/37380
