### ISSUE TITLE
Inserter stays fixed on the screen when scrolling

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#36882]
### Description

When scrolling on the page and I hover to reveal an inserter, the inserter becomes fixed while I would expect it to scroll with the rest of the content.

It just feels jumpy when it doesn't stick to the place:

https://user-images.githubusercontent.com/87168/143483357-02a092c8-b71d-41ab-b7c3-ce342eee47ef.mov

https://user-images.githubusercontent.com/87168/143483569-b1a1425b-3b0c-4f76-9cbf-3417f5ef7853.mov

FYI @jasmussen perhaps this started after making the appender fixed in https://github.com/WordPress/gutenberg/pull/36605 ?

### Step-by-step reproduction instructions

- Go to site editor
- Reveal inserter by mouse hover and scroll with mouse scroll wheel

### Environment info

- Gutenberg v12.0.1
- Firefox 94 MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by jasmussen** [comment]
Thanks for the ping and the report. It is to an extent the same issue as #35536, which is crucially important for us to fix, and in the 5.9 list. The good news is, @ramonjd created a PR today that in my latest testing [appears to fix this really well](https://github.com/WordPress/gutenberg/pull/36798#issuecomment-979036010).

**Comment by simison** [comment]
@ramonjd is this fixed and can be closed?

**Comment by ramonjd** [comment]
> is this fixed and can be closed?

Thanks for the ping. Yes, will close 🎉
