### ISSUE TITLE
Navigation block: vertical orientation not working

### ISSUE THREAD

**Issue by weddje** [WordPress/gutenberg#36902]
### **Description**

I noticed that the vertical orientation isn't working for the navigation menu's. 
When I create a navigation menu on a blank page, within layout - orientation, I select vertical. In the editor the menu's are displayed vertically. But on the front-end the menu's are displayed horizontally.

### **Step-by-step reproduction instructions**
Activate a blocks-based theme (e.g. TwentyTwentyTwo)
Add a Group block to a post
Add a navigation block, select vertical orientation

### **Screenshots:**

<img width="1265" alt="Screenshot 2021-11-26 at 10 10 34" src="https://user-images.githubusercontent.com/47943998/143556160-95fdc3b2-4c49-4cc6-ab75-e90d93a37e9a.png">

<img width="663" alt="Screenshot 2021-11-26 at 10 11 11" src="https://user-images.githubusercontent.com/47943998/143556156-c1445e3e-6040-440d-812f-d77c04adc4d9.png">

<img width="327" alt="Screenshot 2021-11-26 at 10 14 14" src="https://user-images.githubusercontent.com/47943998/143556513-89d13b33-dd8a-4063-8bfd-a0e61e167a6b.png">

**Comment by annezazu** [comment]
I can confirm with Gutenberg 12.0.1 and using WordPress 5.9-alpha-52262.
