### ISSUE TITLE
Consider maxPages attribute on Page list as arg to get_pages

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#36905]
I wonder if it should be an argument to `get_pages`, usually that supports adding a limit.

_Originally posted by @talldan in https://github.com/WordPress/gutenberg/pull/36877#discussion_r757352570_

**Comment by annezazu** [comment]
Is this the same?! https://github.com/WordPress/gutenberg/issues/37340 If so, happy to close mine out :D

**Comment by getdave** [comment]
Oh man this was a poorly created Issue. My bad. Let's keep https://github.com/WordPress/gutenberg/issues/37340
