### ISSUE TITLE
[Icons]: strokeWidth props does not output HTML correctly

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#36903]
### Description

`strokeWidth` props is output as incorrect HTML `strokewidth` attribute on the save side.

### Step-by-step reproduction instructions

- Create a template for a plain custom block.
- Use the `Icon` component to render an icon that contains a strokeWidth props, both edit and save.

## Code (edit.js)

```php
import { Icon, archiveTitle } from '@wordpress/icons'
import { useBlockProps } from '@wordpress/block-editor';

export default function edit() {
	return (
		<div { ...useBlockProps() }>
			<Icon size={100} icon={ archiveTitle } />
		</div>
	);
}
```

## Code (save.js)

```php
import { useBlockProps } from '@wordpress/block-editor';
import { Icon, archiveTitle } from '@wordpress/icons'

export default function save() {
	return (
		<div { ...useBlockProps.save() }>
			<Icon size={100} icon={ archiveTitle } />
		</div>
	);
}
```

After you build the code above and check it in a browser, the appearance and HTML code will look like this.

## Appearance (Block Editor)
![editor](https://user-images.githubusercontent.com/54422211/143558061-c35b4b35-b839-4eeb-8756-d7447f4b7fbf.png)

## Appearance (Frontend)
![frontend](https://user-images.githubusercontent.com/54422211/143558072-c17f4972-157a-4240-8a9e-ea05309eaaf7.png)

As shown above, the strokeWidth props is rendered as an invalid "**strokewidth (lowercase w)**" in the frontend, resulting in different line thicknesses for the icons.

This problem occurred even when I did not use the Icon component and hard-coded the svg tag.

Is there any way to solve this?

### Environment info

- WordPress version: 5.8.2 
- Gutenberg version: 12.0.1 (It also occurred when the Gutenberg plugin was disabled)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
The same issue was filed recently by @KevinBatdorf in https://github.com/WordPress/gutenberg/issues/38553. Let's consolidate and close this one since the more recent issue explains the changes required for more attributes. Thank you for the report that is very helpful.
