### ISSUE TITLE
It shouldn't be possible to make a Template part a Reusable Block

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36916]
<img width="431" alt="Screenshot 2021-11-26 at 14 12 31" src="https://user-images.githubusercontent.com/846565/143593701-ebb94919-62d4-4eaf-9a5b-ec90ff5accef.png">

**Comment by Mamaduka** [comment]
We can disable this using [block support](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#reusable).
