### ISSUE TITLE
Docs - Permit handbook to be edited on GitHub

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#3692]
As a Gutenberg contributor, it would be easier to suggest edits to the handbook if it was editable on GitHub.

**Comment by mtias** [comment]
It is all editable [here](https://github.com/WordPress/gutenberg/tree/master/docs) — it syncs every 15 minutes or so, I believe.

**Comment by youknowriad** [comment]
@danielbachhuber The handbook is generated based on the `docs` folder of the repository and the manifest file https://github.com/WordPress/gutenberg/blob/master/docs/manifest.json

This is already possible then.

**Comment by danielbachhuber** [comment]
> The handbook is generated based on the docs folder of the repository and the manifest file https://github.com/WordPress/gutenberg/blob/master/docs/manifest.json

Oh, great. Can we include some call to action in the handbook itself?

For reference, WP-CLI has this:

![image](https://user-images.githubusercontent.com/36432/33322680-f1aef544-d3fe-11e7-965c-0560356a69fa.png)

**Comment by mtias** [comment]
Yes, sounds like a good idea. cc @pento

**Comment by pento** [comment]
Fixed in WordPress/gutenberg-theme#23.
