### ISSUE TITLE
Site Editor: Template part is missing after exiting focus mode

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#36937]
When switching into focus mode to edit the template part, it's missing after going back to the template using the "Back" button.

## Step-by-step reproduction instructions
1. Go to Appearance > Editor
2. Open templates details dropdown in the header.
3. Click on "More Options" for the area and "Edit {templatePartName}
4. Without doing anything, click the "Back" button.
5. See that now the template part you were editing is missing from the page.

## Screenshot
https://user-images.githubusercontent.com/240569/143783792-861f6c55-ed5c-4e53-bf6f-3499bcd22d26.mp4

I tested with TT1 Blocks and TT2 themes.

**Comment by Mamaduka** [comment]
@kevin940726, I remember you worked on this feature. Any ideas why this might be happening?

**Comment by kevin940726** [comment]
I did the bisecting and found the first bad commit is coming from https://github.com/WordPress/gutenberg/pull/36340. I have no idea why though. The problem goes away if I commented out this part:

https://github.com/WordPress/gutenberg/commit/5458edce15224ee1398d6697d317a6fd7e7abcac#diff-884dae78f1676d454c049107e9b05b2403eb042457f77f836bd170d104396b8bR226-R233

Maybe @tellthemachines knows why?

**Comment by Mamaduka** [comment]
Thanks for the follow-up, @kevin940726.

**Comment by tellthemachines** [comment]
> The problem goes away if I commented out this part:
> 5458edc#diff-884dae78f1676d454c049107e9b05b2403eb042457f77f836bd170d104396b8bR226-R233

No idea, but that code's specific to the navigation block. Does this issue happen with any template part or only one that contains a navigation?

**Comment by tellthemachines** [comment]
Answering my own question above 😅, I can reproduce this on latest trunk with any template part, whatever it contains. I'm also seeing a few PHP notices when loading the editor, not sure if they may be related:

```
Notice: Undefined property: WP_Block_Template::$origin in /var/www/html/wp-content/plugins/gutenberg/lib/compat/wordpress-5.9/class-gutenberg-rest-templates-controller.php on line 467

Notice: Undefined property: WP_Block_Template::$author in /var/www/html/wp-content/plugins/gutenberg/lib/compat/wordpress-5.9/class-gutenberg-rest-templates-controller.php on line 477
```

**Comment by Mamaduka** [comment]
Thanks for looking at the problem, @tellthemachines.

The PHP notices should be fixed now, but I don't think those are the cause.

**Comment by noisysocks** [comment]
The symptoms here look suspiciously like the ones in https://github.com/WordPress/gutenberg/issues/36788. Could be related.

**Comment by Mamaduka** [comment]
Hi folks, I tried to debug this issue but failed 😞 

Here are my findings so far:
* Started happening in Gutenberg 12.0
* The template part block's Edit component is rendered, but inner blocks aren't.
* We've all props required to render inner blocks, but they refuse to do so.
* When testing with TT2, I remove Site Logo and Navigation blocks from the header. Go back works as expected.

**Comment by noisysocks** [comment]
Pinging @WordPress/gutenberg-core for technical feedback.
