### ISSUE TITLE
Event Countdown Block

### ISSUE THREAD

**Issue by ai2n** [WordPress/gutenberg#36930]
### Description

The Event Countdown Block:
https://wordpress.com/support/wordpress-editor/blocks/event-countdown-block/

Doesn't work correctly.

**Expected result:**
The event time set is counted down to consistently across time zones. Two users in wildly different time zones should see the same amount of time until the event.

**Actual result:**
Each user in a different time zone sees a different countdown time because the Event time is not pinned, and is adjust to be local time based on the user's time zone.

### Step-by-step reproduction instructions

1. Create an Event block and set an Event time.
2. Note the displayed countdown time remaining from some time zone.
3. Compare to the countdown time remaining displayed when viewing it from a different time zone.
4. The countdown times will be different and based on the users time zone, but they should be the same.

### Environment info

- Gutenberg Version 12.0.1
- Hever theme.
- Chrome 95.0.4638.69 on Mac OS 11.6 Desktop.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by johnbillion** [comment]
Sorry to hear you're having a problem @ai2n but this block is provided by the commercial WordPress.com service, not by Gutenberg or the open source WordPress software. You should contact the WordPress.com support team instead.
