### ISSUE TITLE
Template Areas UI: Add support for other area types

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36955]
I was testing some FSE themes from the directory last week and spotted what I suspect is a bug:

<img width="1636" alt="Screenshot 2021-11-29 at 12 36 52" src="https://user-images.githubusercontent.com/846565/143869549-9fe32a0a-b66d-48db-b092-e117b00f732f.png">

The areas UI currently only seems to support Template Parts that are assigned to either the `header` or `footer` area. Other Template Parts (IE those assigned to the `navigation` or `sidebar` area) appear to be broken in the areas UI.

**Comment by jameskoster** [comment]
The same issue appears in the template dropdown:

<img width="279" alt="Screenshot 2021-11-29 at 12 40 27" src="https://user-images.githubusercontent.com/846565/143869834-b2cc967f-6731-4604-bac9-5c30e1220c4a.png">

**Comment by noisysocks** [comment]
@jameskoster: What theme are you using to reproduce this?

**Comment by jameskoster** [comment]
@noisysocks [Wowmall](https://wordpress.org/themes/wowmall/).

**Comment by Mamaduka** [comment]
I started working on the fix and will have PR ready for testing tomorrow.
