### ISSUE TITLE
missing self-URL check in RSS block (Trac: 54527)

### ISSUE THREAD

**Issue by DanielRuf** [WordPress/gutenberg#36969]
### Description

At https://github.com/WordPress/gutenberg/blob/fb8a732f00dd76e62eb0c6119ec99bd85db91e64/packages/block-library/src/rss/index.php#L16 there is the self-URL check missing, which can lead to negative impacts on websites.

Copied from https://core.trac.wordpress.org/ticket/54527:

At https://github.com/WordPress/WordPress/blob/5.8.2/wp-includes/widgets/class-wp-widget-rss.php#L48-L64 there is a check to prevent that the home / site_url URL is accidentally used as RSS feed URL as this can lead to interesting cases like infinite loops, many long-running http / curl requests and some sort of "Self" Denial of Service (DoS).

In WordPress 5.8.2 when we edit block-enabled them and add the RSS widget and use the same URL like home / site_url, then we get the mentioned problems because the check is missing there:
https://github.com/WordPress/WordPress/blob/5.8.2/wp-includes/blocks/rss.php#L16

### Step-by-step reproduction instructions

1. Add RSS block (to the footer of the website or to the homepage)
2. Enter the same URL that is currently defined as home / site_url
3. Save the page
4. Go to the page in the browser
5. You may see that the page loads for a very long time and then returns a curl error and each call of the website spawns more of the curl requests which could pile up and produce a high load on the server

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
Thanks for contributing, @DanielRuf.

I create PR to resolve this issue https://github.com/WordPress/gutenberg/pull/39756.
