### ISSUE TITLE
Allow Code Editor for Templates

### ISSUE THREAD

**Issue by palmsout** [WordPress/gutenberg#36966]
## What problem does this address?
I often find myself needing to see the underlying code generated by the block editor when editing templates. I know this was possible at some point, but it's not letting me do so now. I thought this was possible in the Site Editor, but a previous comment [here](https://github.com/WordPress/gutenberg/issues/34367#issuecomment-981477194) tells me it was never possible. Maybe I used to be able to do it using the Classic Editor, but now when I try to open a template in the classic editor, it forces me back to the block editor. Or maybe this used to be possible in Customizer? I'm not getting the option to do so now. 

Either way, this is something that would be really useful to me, and I suspect many. Especially useful when making small changes to margins, custom classes, and html in the custom html block, and also for speed (the block editor can still be slow). This might also be useful for those times when the save button is not activated by edits to custom html blocks (I often have to add a blank paragraph and delete it again to get the option to save). It would also be a useful way to be able to clone a template, by simply copying all of the generated code and then pasting it into a new template. 

## What is your proposed solution?

As you might suspect, I'm no expert, but I simply propose allowing for the code editor to be an available option when editing a template in the Site Editor, as it is when editing a post or page. There may have been context around why this wasn't done in the first place, but I haven't been able to find a thread addressing it here.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; (I personally agree as well and miss it). 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/22528. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in that issue.
