### ISSUE TITLE
Question:  Roles & Permissions in JS

### ISSUE THREAD

**Issue by scofennell** [WordPress/gutenberg#36970]
I want to do this:
```
	wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'taxonomy-panel-category' ); // Remove Yoast SEO meta box
	wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'taxonomy-panel-post_tag' ); // Remove discussion meta box

```

For users who cannot publish_posts.  I can't seem to understand how permssions/roles work in js.  I assume this is the right place to look:

https://developer.wordpress.org/block-editor/reference-guides/packages/packages-core-data/#canuser

But I can't seem to arrive at a working example.  Help?

As a workaround, I made a special JS file for users who cannot publish_posts, and I only enqueue it for them, which obviously I can easily do in php.  That works, but sets a really nasty precedent.  It would be awful to have to make a different JS file for every conditional thing you want to do in gutenberg JS.

**Comment by tellthemachines** [comment]
Hi @scofennell ! You'll want to use something like:
```
window.wp.data.select('core').canUser('create','pages')
```
Let me know if this helps!

**Comment by tellthemachines** [comment]
I'm going to go ahead and close this issue; feel free to open a new one if you have any further questions!
