### ISSUE TITLE
Global Styles: Custom Palette colors applied inconsistently and not globally

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#36979]
### Description

As part of the eleventh call for testing for the FSE Outreach program, an issue was found with using custom color palettes:

>custom palette colours could not be applied globally, e.g. to all the headings, though the theme defined colours did work when applied globally. The custom palette colours did however work when applied to individual blocks.

When testing this further, I found that they don't seem to work at all, either globally or for individual blocks. 

### Step-by-step reproduction instructions

1. Open up the Appearance > Editor (beta)
2. Open up global styles.
3. Go to the Colors section.
4. Add a custom color to the color palette. 
5. Try applying them to various parts of your site (background, text, etc). Notice no changes. 
6. Try selecting an individual block like the Post Title block and apply a custom color palette. Notice either no change (Post title block doesn't change) or some blocks do change (Site Title does change)

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/143950030-3c585bf6-580c-42d5-90c0-5d640242ad90.mov

### Environment info

- WordPress 5.9-alpha-52262
- Gutenberg 12.01
- TT1 blocks
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
@annezazu are you still seeing this on beta 3? I just gave it a try and custom colours seem to apply as expected:

![custom-colors](https://user-images.githubusercontent.com/3629020/146290275-a6090439-03bb-4f78-a746-950ad628c646.gif)

The above is in the content/footer area of the TwentyTwentyTwo theme - in the header area, some of the colour changes don't apply as they appear to be overridden by individual block settings in the template.

**Comment by annezazu** [comment]
Huzzah! I cannot replicate anymore either with beta 3. Thanks for following up. Closing this out :)
