### ISSUE TITLE
Conditionally show or hide inspector settings depending on other block settings

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#36972]
## What problem does this address?
As of Gutenberg 12.0, all color options available to a text block are shown in the inspector sidebar, such as Color, `Background Color`, and `Link Color`. However, some blocks like `Post Date` and `Post Date` can work entirely as links or plain text, making options like `Color` and `Link Color` mutually exclusive.

In the example below, the Color and Link Color of a Post Date block have been set to red and blue, respectively. As we can see, by toggling the Link setting option `Make title a link`, the full block toggles between a link or plain text, thus both color options are mutually exclusive.

https://user-images.githubusercontent.com/27339341/143932837-12cc5063-4512-47db-af93-c0ab02fc3ed4.mov

## What is your proposed solution?
Being able to conditionally show or hide the relevant style options depending on the state of other block settings would improve the user experience. In the case of `Post Title` and `Post Date` blocks, `Color` or `Link color` would be shown depending on the value of `Make title a link`.

In the case of Post Author, it can't contain links so the `Link Color` option never applies and should be hidden.

**Comment by ntsekouras** [comment]
Thanks for the issue @priethor! This seems to come up often and similar use cases would be when we a block is in a `placeholder` state, etc..

**Comment by annezazu** [comment]
Related issue: https://github.com/WordPress/gutenberg/issues/31255 Would love to see this! Closing out the original but wanted to be sure the feedback from the outreach program was known since this has come up quite often.

**Comment by richtabor** [comment]
I don't think is as much of an issue, now that the controls are behind the toolbelt UI, i.e. available when intentionally applied. And we also have text and link colors applied at the same time, when changing text color. 

Should we close this?

**Comment by annezazu** [comment]
Agreed. Let's close.
