### ISSUE TITLE
404, index, and archive templates are displaying in the Template selection in the block editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#36985]
### Description

In https://github.com/WordPress/gutenberg/pull/35802, hierarchical templates were excluded from the template selection in the block editor.
In 5.9-alpha-52272, the hierarchical templates are displaying in the drop down again.

### Step-by-step reproduction instructions

1. Install 5.9-alpha-52272
2. Activate a theme with support for template editing, for example Twenty Twenty-Two
3. Open the block editor and view the Template section.

### Screenshots, screen recording, code snippet

![The select list in the Template section in the block editor includes the incorrect templates](https://user-images.githubusercontent.com/7422055/143993263-5b345c23-40bb-435f-9983-0fc0d6844de8.png)

### Environment info

WordPress 5.9-alpha-52272 via the beta tester plugin.
Gutenberg is not active.
Windows 10, Chrome.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
This was fixed in https://github.com/WordPress/wordpress-develop/pull/2020.

**Comment by annezazu** [comment]
Closing this out :)
