### ISSUE TITLE
[Urgent] Colorpicker component Bug when enableAlpha selected True

### ISSUE THREAD

**Issue by sagarpatel124** [WordPress/gutenberg#36992]
### Description

From last few versions of Gutenberg, When color picker with enableAlpha=true for rgba with opacity, It's keep breaking block. 

In inspect elementor we get error : 
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside component Will Update or component Did Update. React limits the number of nested updates to prevent infinite loops.

https://reactjs.org/docs/error-decoder.html/?invariant=185 

We have confirmed, That's create error with Gutenberg's Default block "wp:list " also having this issue when gradient color picker is used. Check Video : https://www.loom.com/share/6806e79ff56b4f2d97fdad306defd133 

When used color picker with alpha true :  https://www.loom.com/share/4d66099e5cb24382b37203b9ccef9b63 

On top of that, In Gutenberg Standalone version Team have completely changed name of enableAlpha=true and In Wordpress version of Gutenberg have different name and value of that field. 

Hopefully, WordPress team come up with a stable solution of Gutenberg soon so Users doesn't get such issues. This is the reason why Gutenberg is worst rated plugin https://wordpress.org/plugins/gutenberg/ It definitely improved a lot lately but It needs to get stable soon. 

Being a developers of WordPress plugins, themes and other tools, We are facing lots and lots of issues due to instability of Gutenberg. Hopefully, Whole development curve will end soon and It will be stable for users to build highend websites using default page builder of WordPress. 

Please respond soon on above issue. It needed to fix soon. People are breaking their sites and we are getting bad comments all around from users. 

### Step-by-step reproduction instructions

When color picker with component with setting enableAlpha=true for rgba with opacity.

### Screenshots, screen recording, code snippet

https://www.loom.com/share/6806e79ff56b4f2d97fdad306defd133
https://www.loom.com/share/4d66099e5cb24382b37203b9ccef9b63

### Environment info

Gutenberg Version : 12.0.1 (May be started from 11.9 or something)
WordPress version : 5.8.2 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Thanks for reporting; possibly overlaps with scenario #2 at https://github.com/WordPress/gutenberg/issues/36899

**Comment by skorasaurus** [comment]
Thank you again for reporting and I understand your frustration with Gutenberg; this has been reported at https://github.com/WordPress/gutenberg/issues/36066 and you can follow that issue.
