### ISSUE TITLE
Color Picker: Refine the look of "unset" color picker

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#36998]
Extracting from [this comment](https://github.com/WordPress/gutenberg/pull/36994#issuecomment-982558698), the checkerboard background currently in place for the Custom Color card indicates transparency, but it should probably lean towards indicating "unset" instead. Also:

> We need to discriminate from "white" and "not set". Though perhaps that can be written in the place of the hex code.

There are the beginnings of a PR in `try/polish-unset-color-indicator-further`, but it isn't quite visually succesful:

<img src="https://user-images.githubusercontent.com/1204802/144041329-85714322-164e-4a4a-8f07-46720ae7537b.gif">

It also opens the question: should the checkerboard backgroud remain in place for when a color with opacity is created?

**Comment by supernovia** [comment]
Hi! FWIW I think the checkerboard thing is confusing. I'm used to seeing that from photoshop and what not, but I'm not sure users know what to do with it. And, I was just keeping those thoughts to myself til one of our volunteers reached out with similar feedback: it's not clear what the checkerboard area is for. I'm gathering it's a preview, but would it make more sense to just use the preview we can see in the live edit area?

Also, when we put in colors for the text, background, links, link background, and then all of the custom colors and default palettes together, it gets kind of unruly. Here's what I'm seeing:

<img width="328" alt="Screen Shot 2021-11-30 at 3 25 51 PM" src="https://user-images.githubusercontent.com/3476361/144138211-abd9a710-cdc5-4d1c-86ea-f7f266cc7ea8.png">

**Comment by supernovia** [comment]
Also, I've noticed when I set a color, say, for the text, the boxy area shows that as the background color with a different text color (like white). I'm not sure what that means.  You can see it in the video here, which I filed for another issue. Ignore the sound and just watch for the boxes:

https://cloudup.com/cJD1MDyAEBZ

**Comment by jasmussen** [comment]
As a small update, things now look like this in trunk:
<img width="685" alt="Screenshot 2021-12-27 at 11 00 33" src="https://user-images.githubusercontent.com/1204802/147460532-badd7fc6-3d45-4cb2-a11f-1faadd2fa05d.png">

**Comment by supernovia** [comment]
What if instead of trying to indicate unset, it just said "Theme Default" or something, and/or showed that color?

**Comment by jasmussen** [comment]
Unset does seem like a bit of a complicated term. But it still feels important to indicate that _no color is applied_, it literally has not been defined. The checkerboard indicating transparency is also misleading since the block doesn't necessarily have a transparent background if otherwise is provided by theme CSS.

So we need a visual treatment that indicates that no user choice has yet been made. "Not set" doesn't seem better:

<img width="718" alt="Screenshot 2022-01-18 at 09 15 03" src="https://user-images.githubusercontent.com/1204802/149897360-c206d003-e7cd-42d6-a8ea-1c5186da9765.png">

A strike-through also doesn't feel very clear, it adds noise and looks like an error:
<img width="712" alt="Screenshot 2022-01-18 at 09 17 20" src="https://user-images.githubusercontent.com/1204802/149897770-73e789f4-dce6-48da-8d9f-1efaaf26bd3e.png">

<img width="725" alt="Screenshot 2022-01-18 at 09 17 49" src="https://user-images.githubusercontent.com/1204802/149897774-bebb53d4-4bbb-4e1c-836e-291fd489dc91.png">

This needs a bit more thought.

**Comment by jasmussen** [comment]
I'm going to close this one for now. The color in the itemgroup does look unset, even if the color in the expanded color panel looks _transparent_. But the color panel is undergoing its own iterations, so this one seems like it's drifting out of date.
