### ISSUE TITLE
Widgets Editor: secondary sidebar should close on narrow widths

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#37014]
### Description

When working in the Widgets Editor I noticed that the layout interface's [secondary sidebar](https://github.com/WordPress/gutenberg/blob/release/12.0/packages/edit-widgets/src/components/layout/interface.js#L90) was hiding the workspace in narrow widths.

Unlike in the Post Editor, when narrowing the screen, the `.interface-interface-skeleton__secondary-sidebar` renders, albeit with no children.

<img width="800" alt="Screen Shot 2021-12-01 at 9 42 38 am" src="https://user-images.githubusercontent.com/6458278/144140163-bbdd5cca-0afb-4875-9fc6-5395a1d6e424.png">

Furthermore when activating block inserter, which is rendered by the secondary sidebar, and reducing the screen width, interacting with the block inserter doesn't trigger a close. See screenshots below.

### Step-by-step reproduction instructions

I was using TwentyTwenty and TwentyNineteen to test.

1. Open the Widgets Editor /wp-admin/widgets.php.
2. Reduce the width of the viewport.
3. The workspace and editor are hidden by then empty `.interface-interface-skeleton__secondary-sidebar` element (the screen is white and blank).
4. Return to a wide viewport width.
5. Activate the block inserter.
6. Reduce the width of the viewport.
7. Try to use the block inserter.
8. Observe that nothing happens.

### Screenshots, screen recording, code snippet

**Blank screen**
![widget-sidebar](https://user-images.githubusercontent.com/6458278/144132717-424ca2bd-6744-4162-8a49-92c18f9624f3.gif)

**Block inserter**
![Kapture 2021-12-01 at 09 48 54](https://user-images.githubusercontent.com/6458278/144141063-8687f269-69a9-4c44-9a56-4aa05ad0c3df.gif)

### Environment info

- WordPress 5.8.1
- Gutenberg trunk
- TwentyTwenty and TwentyNineteen

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I would like to close this issue as it does not seem to reproduce in the latest Gutenberg.

- The right sidebar disappears when the viewport width is reduced.
- If the viewport width is reduced with the block inserter open, the block inserter is displayed in full screen. However, inserting and opening/closing blocks will work (this is the same behavior as in the post editor).


https://github.com/WordPress/gutenberg/assets/54422211/762de4de-e79c-42e2-9220-224ebd623fe6
