### ISSUE TITLE
Hide the Nav Area block from the public UI

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#37023]
As suggested by @talldan we need to make sure the Nav Area block is not accessible from the Editor UI. It's been deprecated so we shouldn't have it appear.

----------

@adamziel @getdave Maybe we should make it so that the block isn't shown in the inserter as well. At the moment the block can still be used with the gutenberg plugin active.

_Originally posted by @talldan in https://github.com/WordPress/gutenberg/issues/36727#issuecomment-983218235_

**Comment by noisysocks** [comment]
Looks like this was fixed by #37026.
