### ISSUE TITLE
Navigation: Improve responsive behaviour

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#37035]
## What problem does this address?
There are several aspects of the navigation block that we have added custom CSS for in Blockbase, to overcome some limitations of the block. These are:

- Controlling the alignment and position of items when in overlay mode
- Controlling the size and color of navigation and navigation links when in overlay mode

## What is your proposed solution?
I don't have a clear idea of how to solve this. Ideally all of [this CSS](https://github.com/Automattic/themes/blob/trunk/blockbase/sass/blocks/_navigation.scss) in Blockbase could be expressed by attributes on the block.

This is what we are trying to achieve:
<img width="529" alt="Screenshot 2021-12-01 at 14 03 27" src="https://user-images.githubusercontent.com/275961/144248247-19294a99-8965-4642-845b-722dfc2dfb23.png">

This is the current behaviour without the additional CSS:
<img width="529" alt="Screenshot 2021-12-01 at 13 59 46" src="https://user-images.githubusercontent.com/275961/144248286-f1541c89-597f-4799-ade1-8f4d5d1a2a6c.png">

**Comment by jasmussen** [comment]
Thanks for the ticket! Can you let me know if https://github.com/WordPress/gutenberg/pull/36991 at least makes it so it isn't aligned to the bottom?

**Comment by getdave** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/49156
