### ISSUE TITLE
Cover block overlay color gradient options empty when using a block-based theme

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#37042]
## Description
While using the WordPress mobile app 18.8 prerelease, the gradient options presented for a Cover block's overlay color only include a single, white option. Selecting the one option does not modify the appearance of the Cover block. 

## Step-by-step reproduction instructions
1. Add a Cover block to the content with the native mobile editor. 
2. Select a color presented. 
3. Open the block settings. 
4. Tap _Color_. 
5. Tap _Gradient_. 
6. Tap the one gradient option presented. 

## Expected behaviour
Several gradient options are presented. Selecting one of the gradient options modifies the Cover block appearance to match the gradient color. 

## Actual behaviour
A single gradient option is presented. Selecting the one gradient option does not modify the Cover block appearance to match the gradient color. 

## Screenshots or screen recording (optional)
| WP 18.7 | WP 18.8 |
| - | - |
| ![Cover block gradient options are present in WP 18.7](https://user-images.githubusercontent.com/438664/144288677-4ae05906-7945-4a3a-9ffe-81cfd7f7b41c.PNG) | ![Cover block gradient options are missing in WP 18.8](https://user-images.githubusercontent.com/438664/144288746-168ed4a6-b34d-46c7-a0f2-b5226455d7d8.PNG) |

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: v12.0.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No, Geologist

## Device information
- Device: iPhone SE, Samsung Galaxy S20
- Operating system: iOS 15.2, Android 11
- WordPress app version: 18.8.0.2

**Comment by geriux** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/37372
