### ISSUE TITLE
Ability to upload custom icons for social icons

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#37059]
Currently, there are only a handful of social icons but I think it would be a neat feature that we can upload our icons ourselves. 

So, that we could upload icons of social platforms or tools that we locally use. EG: in Belgium and the Netherlands we use websites like Smartschool in schools and it would be overkill that we add an icon for that... But, it would be great that there is a possibility to add it for yourself.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/21330. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
