### ISSUE TITLE
Widgets: Widgets screen not working in Android browsers

### ISSUE THREAD

**Issue by KokkieH** [WordPress/gutenberg#37055]
### Description

The new widgets screen at `/wp-admin/widgets.php isn't working in any browser on Android.

I can replicate the issue across various browsers on Android, but it works fine in the same browsers on iOS. 

The screen loads normally if the Classic Widgets plugin is installed.

### Step-by-step reproduction instructions

1. Using a browser on an Android device, go to WP-Admin ->Appearance ->Widgets

The WordPress admin bar at the top of the screen loads correctly, but otherwise the screen is completely blank with no way to view or edit existing block widgets, or add new ones.

### Environment info

- Confirmed on WordPress version 5.8.2, Gutenberg 12.0.1. Also confirmed on a WordPress.com site
- Chrome 96, Firefox 94.1.2, and DuckDuckGo 5.102.3 on Android 9. Also confirmed with Chrome and Firefox on Android 12 using Browserstack.com

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
This was fixed in https://github.com/WordPress/gutenberg/pull/38017. Thanks for reporting it.

The fix is in WordPress 5.9 and Gutenberg 12.5.

**Comment by KokkieH** [comment]
Thanks for the fix :)
