### ISSUE TITLE
Elevate "Editor" over "Customize" in the Appearance menu

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#37056]
When a block theme is active, we hide access to the Customizer in the Appearance menu. However, when certain conditions are met the link will re-appear. My concern is that it re-appears _above_ the site editor link, which seems hierarchically inappropriate:

<img width="172" alt="Screenshot 2021-12-02 at 11 04 20" src="https://user-images.githubusercontent.com/846565/144410626-16178ff3-f69b-46da-b382-66cb8c7c54f1.png">

I suppose there are two options:

1. Adjust the priority of the Editor link, or;
2. Adjust the priority of the Customize link.

Whichever way we go, it seems sensible for the Editor link to take visual priority over the Customize link:

<img width="159" alt="Screenshot 2021-12-02 at 11 06 46" src="https://user-images.githubusercontent.com/846565/144411327-91e87ce7-9f12-4ea9-a405-fb8cc634ed96.png">

**Comment by Mamaduka** [comment]
I am assigning this to myself. I've PR almost ready, just need to run a few more tests :)
