### ISSUE TITLE
Duotone bug causing jarring UI response when selecting custom color

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#37069]
### Description

Apologies for the rough title (feel free to rename) but this was tricky to describe. Essentially, when trying to set a custom color with duotone, the UI starts to break down. This was found during the [eleventh FSE Outreach Program call for testing](https://make.wordpress.org/test/2021/11/08/fse-program-testing-call-11-site-editing-safari/).

cc @aj

### Step-by-step reproduction instructions

1. Open site editor
2. Within Query Loop block, add post featured image block.
3. Select duotone options.
4. Try adding your own custom color and drag the color picker around. 
5. See error.

### Screenshots, screen recording, code snippet

![duotone](https://user-images.githubusercontent.com/26996883/144459828-44064b68-cc51-4d26-bb52-e3e2f45d01fb.gif)

### Environment info

- Gutenberg 12.0.1 
- WordPress 5.9 beta 1
- TT1 blocks 

Note - this happens with both Gutenberg enabled and disabled. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mirka** [comment]
This has been fixed in #36941 🎉
