### ISSUE TITLE
Bullet position error with image

### ISSUE THREAD

**Issue by msdesign21** [WordPress/gutenberg#3707]
## Issue Overview

This might be a tricky error to reproduce, but when trying the Gutenberg Einstein test, resizing the image in relation to the bullet list caused the first bullet to jump around incorrectly. (see screen recording below)

## Steps to Reproduce (for bugs)

1. Use [this Einstein test](https://wpusabilitytesting.polldaddy.com/s/gutenberg-flow-a?p=2&r=FAC5E49AF2C75EAD582AEB837A7EB5BE). 
2. Try resizing the image to be slightly larger than the example causing the first bullet to be beneath the quote on the right. 
3. Clicking on/off the image or resizing again would not consistently move the bullet where you'd expect. 
I was using the latest Chrome. Was able to recreate (although a bit different) in Safari. 

## Expected Behavior

I would expect the bullet to stay in line and move around with the text. 

## Current Behavior

The bullet incorrectly jumps around when resizing an image around it. 

## Screenshots / Video

http://cld.wthms.co/eDDRny

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jorgefilipecosta** [comment]
Thank you for your report @msdesign21 the bug should be fixed with the merge of https://github.com/WordPress/gutenberg/pull/3740.
