### ISSUE TITLE
Rename `Query-` inner blocks to be more user-friendly

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#37079]
## What problem does this address?
The Query Loop block's inner blocks all include the `Query` prefix in their names, making them sound more complex than they actually are.

![image](https://user-images.githubusercontent.com/27339341/144495361-627ae4ee-99aa-443c-ab6a-5d474d134841.png)

## What is your proposed solution?
These blocks could be renamed to be more user-friendly, like `Page numbers` instead of `Query pagination numbers` and `Next Page` instead of `Query Pagination Next`, as they are only surfaced within a `Query Loop` context.

**Comment by gziolo** [comment]
Interesting idea. Should do the same for Comments Pagination blocks?

**Comment by priethor** [comment]
> Should do the same for Comments Pagination blocks?

I think it makes sense, as these pagination blocks provide very similar customization options, for the most part. Simplifying all of them to "the pagination blocks within my current context" might be more understandable for users than acknowledging there are multiple, different pagination blocks (now we have Query and Comments, but might have more in the future)

**Comment by priethor** [comment]
Updated the description with the, even more, user-friendly names approved in the PR, so that they serve as reference for the `Comments Pagination` blocks.

**Comment by gziolo** [comment]
We still need the same changes for Comments Pagination blocks. /cc @c4rl0sbr4v0 and @DAreRodz.

**Comment by cbravobernal** [comment]
Should we rename them to `Next Page` or `Next Comments`? Thanks!!

**Comment by DAreRodz** [comment]
@gziolo @c4rl0sbr4v0 As long as the parent block's name continues to be `Comments Pagination`, then I think it would be OK to name them `Next Page`, `Previous Page` and `Page Numbers`. I think it would be clear that `Page` refers to a page of comments. 🙂

**Comment by priethor** [comment]
`Next page` seems both more understandable and cohesive with other pagination blocks like the `Query Loop` one.

**Comment by ntsekouras** [comment]
I think we can close this one as the comment pagination blocks have proper names.
