### ISSUE TITLE
Tooltip: Adjust placement of tooltips to avoid overlapping their trigger

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#37076]
The `tooltip`'s that show throughout the editor sometimes overlap with the button or element that triggers the tooltip. Here's a few examples:

<img width="169" alt="image" src="https://user-images.githubusercontent.com/191598/144488243-aeedbb73-ff2e-40db-8960-ff65c2d1dba4.png">

<img width="156" alt="image" src="https://user-images.githubusercontent.com/191598/144487963-e333c80a-7cb1-48f2-b3fb-984543e78e0d.png">

<img width="79" alt="image" src="https://user-images.githubusercontent.com/191598/144488079-90db1c81-6862-4df3-a32c-de303ee65e6e.png">

<img width="280" alt="image" src="https://user-images.githubusercontent.com/191598/144488373-c6a88961-5b1b-42cf-a0dd-c04da4bc2888.png">

This _doesn't_ seem to be the case for the block toolbar, which gives the tooltip a little more breathing room:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/191598/144488209-af0680ef-9dfb-4cce-98c2-3c3de749bc66.png">

I think we should take this same approach everywhere the tooltip is displayed. Here's how it could work adding more space to the above examples:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/191598/144489321-8e9befc8-9dd4-4401-96b0-c4a621f2f61f.png">

**Comment by ramonjd** [comment]
Just tooling around with this a bit.

Assuming the position is "bottom", adding this to `packages/components/src/tooltip/style.scss` has some effect 

```css
.components-tooltip {
	margin-top: $grid-unit-15;
}
```

<img width="345" alt="Screen Shot 2021-12-03 at 7 04 02 am" src="https://user-images.githubusercontent.com/6458278/144494630-e52241c3-fb1a-4a57-aad0-0a6980deb01d.png">
<img width="220" alt="Screen Shot 2021-12-03 at 7 03 41 am" src="https://user-images.githubusercontent.com/6458278/144494633-d133dacb-ad7e-4dbd-b7a3-e5694b5aeee2.png">

There would have to be overriding classes for "top" and the other positions probably.

**Comment by jordesign** [comment]
I'm no longer able to reproduce the issue in the locations mentioned above (or elsewhere) in WP6.5 - tooltips all appear to offer some spacing between the element and the tip. Accordingly I'll close this as unreproducible,
