### ISSUE TITLE
Navigation block: placeholder menu border doesn't adjust to the menu's width

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#37077]
### Description

In Gutenberg 12.0.1 or WordPress 5.9 Beta 1, the border of the placeholder menu of the Navigation block doesn't adjust to its width.

### Step-by-step reproduction instructions

1. Spin up a WordPress 5.9 Beat, TT2, with or without the Gutenberg plugin.
2. Go to Appearance->Editor
3. Select the Navigation block
4. The bounding box of the Navigation block's placeholder menu is narrower than the menu itself.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/27339341/144494273-5b1bfeee-66de-4f2e-a6a4-9b9f2e7d5aa3.mov

### Environment info

- WordPress 5.9 Beta 1, with or without Gutenberg 12.0.1
- Chrome, Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Thanks for the ticket. I think this will be mitigated by a trio of PRs:

- Remove the "all pages" link: #36775
- Inherit orientation in setup state: #36778
- Remove gray blobs: #36858

_I will take a stab at a 4th one to see if I can reduce the placeholder state further, but it would be nice to get a green check for the three above as they all build upon each other._

Notably the last of those, removing the gray blob fake placeholder state, has a few dimensions to it:

- It's not meant to be a loading state, it's meant to pass the "squint" test and indicate what the block is about. But in testing (outreach program) it keeps coming back that people think of it as a loading state and assume no further action is meant to be taken.
- By removing the loading state and going back to a more basic placeholder, it might make it clear that themes are better off inserting a preconfigured navigation block, either with the Page List inserted from the start (I think TwentyTwentyTwo is already doing this), or even just loading by default the default navigation structure (as mused about in #36667). 

In either case, to me it seems valuable to revert back to the navigation block looking unconfigured, when it is unconfigured. What do you think?

**Comment by priethor** [comment]
> In either case, to me it seems valuable to revert back to the navigation block looking unconfigured, when it is unconfigured. What do you think?

I left [a comment on #36858](https://github.com/WordPress/gutenberg/pull/36858#issuecomment-985479040) to focus the conversation there 👍
