### ISSUE TITLE
Site Title: link color not applied in editor

### ISSUE THREAD

**Issue by Andrew-Starr** [WordPress/gutenberg#37071]
### Description

When the Site Title block is set to link to the homepage, changing the link color has no effect in the editor (site editor and post/page editor), although it does render correctly with the selected color on the frontend.

### Step-by-step reproduction instructions

Add the Site Title block to a post or page, or edit the header template in a FSE theme.
Make sure to keep the "Make title link to home" toggled on.
Change the link color to a different color than the default.
Notice that the color of the Site Title does not change to the selected color.
Save/update/publish the post.
View the post in the frontend and the Site Title block that you have added is displayed with the correct selected color.

### Environment info

WP 5.8.2
Gutenberg 12.0.1

Also same issue using WP 5.9 beta-1 without Gutenberg.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I am able to reproduce this on 5.9-beta2-52361, **but** only with a full site editing theme active, **after** changing the global styles site title link color. 

When I change the global style for the link color, then the color I added for the block in the editor is ignored, it is supposed to be the opposite. 🤔

**Comment by Smit2808** [comment]
Hi @Andrew-Starr 

I checked this issue and now it is working fine for the page, but if we edit the FSE and then change the site title link color and publish it, in the editor it will work but on the front side, the color is not changing.

My environment:
-> WP V5.9.2
-> GB V12.8.1
-> Browser chrome
-> MAC OS

Thank you.

**Comment by carolinan** [comment]
Tested again today with Gutenberg trunk.   This is enough to make one dizzy...

When editing individual site title blocks, all colors work correctly on the front, block editor, site editor. As long as there are no global styles saved.

When editing global styles > Site title:
- Only the background color and the text:hover color works in the site editor.
- On the front, the global styles overrides styles that were selected for individual site title blocks
- In the block editor, the global styles overrides styles that were selected for individual site title blocks: Except the background color.

**Comment by torounit** [comment]
Background works correctly.

The text color and background class are set to h1 ( ex. `.has-light-green-cyan-color` ). The color does not seem to change because it is overridden by the following style set in the `a` tag.

```
a:where(:not(.wp-element-button)) {
    color: var(--wp--preset--color--foreground);
    text-decoration: underline;
}
```

Looks like I need to inherit the h1 style.
