### ISSUE TITLE
Cannot select a different a global font family category if the underlying values are equal

### ISSUE THREAD

**Issue by zaguiini** [WordPress/gutenberg#37082]
### Description

When updating typography global styles, imagine the following options:

- Default
- A (DM Sans)
- B (DM Sans)

Both A and B categories have the same value: `"DM Sans", Sans-Serif`.

You tried to select `B`. However, `A` is the one that gets selected.

### Step-by-step reproduction instructions

1. Activate the Quadrat theme (there might be other themes that have the same issue);
2. Open the site editor;
3. Open the global styles panel;
4. Click on `Typography` > `Text`;
5. Check `Default` is selected under the "Font family" field;
6. Change it to `Headings`.

Check that `Body` gets selected instead.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26530524/144498164-6bac9e6a-7f34-4bc5-9f90-b702176e4c85.mov

Those variables come from `packages/edit-site/src/components/global-styles/typography-panel.js`:

![image](https://user-images.githubusercontent.com/26530524/144499230-3b9a77aa-5f09-4807-aa23-71357fc96d80.png)

It looks like we're using `fontFamily` as the value instead of the `slug`, so it just finds the first value that matches the `fontFamily` option instead of using the option slug.

### Environment info

- WordPress 5.8;
- Gutenberg 12.0.1;
- Quadrat theme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@oandregal tagging you in here in case you have some context :)

**Comment by oandregal** [comment]
:wave: I've looked at this and this is what I don't understand: what's the use case of having two fonts that are the same? Isn't it like providing two colors and both are "red"? With what I now know, I'd think the theme needs to be updated to provide a different set of fonts (or a single one) and this can be closed.

**Comment by aristath** [comment]
This is not a bug in Gutenberg... It's just a case of "doing it wrong". If A & B have the same value, then it doesn't matter which one is selected. Just like any other HTML `<select>` element, what gets saved (and used) is the value and not the label. If 2 options have the same value, then HTML & browsers will just pick the 1st option inside the select with that value.
Not a bug, it's just the way HTML works 🤷
