### ISSUE TITLE
WordPress 5.9 Beta 1 – UI issue with Clear button on Duotone Settings

### ISSUE THREAD

**Issue by monika-12** [WordPress/gutenberg#37087]
### Description

Clear button on Duotone settings overlaps with Focus Border and looks bad in the user interface.

### Step-by-step reproduction instructions

- Click on Duotone Settings
- Double click on Highlights option
- Focus Border on Highlight option will overlap with Clear button

### Screenshots, screen recording, code snippet

https://share.getcloudapp.com/z8u1jxrB

### Environment info

- macOS Big Sur V-11.6
- Browser: Google Chrome
- Local Environment: Local by Flywheel
- WordPress Version: development version (5.9-beta1)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I can replicate this with beta 1:

<img width="322" alt="Screen Shot 2021-12-03 at 11 03 44 AM" src="https://user-images.githubusercontent.com/26996883/144633876-8c031d58-2426-4d6e-9a63-00ea9928fb3f.png">

cc @ajlende :)

**Comment by amustaque97** [comment]
Hi, I would :heart: to take this up 😄

**Comment by amustaque97** [comment]
After investigation, I found that, [fix](https://github.com/WordPress/gutenberg/pull/37016) is already merged into `trunk` branch 3 days ago. Running latest code doesn't show this behavior. 

Screenshot:
<img width="1617" alt="image" src="https://user-images.githubusercontent.com/21127788/144725848-b1eb9df9-6b15-4223-b1da-e9f2274b7a41.png">


I believe we can close this issue. :)

**Comment by ajlende** [comment]
Resolved by https://github.com/WordPress/gutenberg/pull/37016
