### ISSUE TITLE
Added by column shows an empty grey circle for old templates if the site has no logo

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#37086]
### Description

This issue follows up on what @paaljoachim mentioned here - https://github.com/WordPress/gutenberg/pull/36763#issuecomment-979939409

The Added By column can show an empty dark grey circle in some situations.

It requires a very specific scenario. The user needs to have created the template or template part before author support was added to templates. This causes the site logo and name to display as a fallback. If the site has no logo, this is when a grey circle is shown.

It's a pretty easy to show an icon as a fallback, so we should do it. Just need to know which icon to use 😄 

### Step-by-step reproduction instructions

Testing is pretty difficult since it requires either existing old templates or for you to create a new template using an old version of WordPress and Gutenberg (maybe something like WP 5.8.2 and 11.9)

1. Remove any site logo
2. Create a template or template part
3. View the template or template part in the list

### Screenshots, screen recording, code snippet

![Screenshot 2021-11-26 at 13 03 40](https://user-images.githubusercontent.com/5323259/143578312-afa5ad9f-3405-4b12-b2a6-c0e5dc59c0a4.jpg)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by paaljoachim** [comment]
I would suggest using the W as a fallback icon. 


![W-placeholder-icon](https://user-images.githubusercontent.com/5323259/144567244-669536f9-2071-41c5-91fc-6904792b55a0.jpg)

**Comment by jameskoster** [comment]
Hmm, might the W icon might lead folks to believe that the template was added by WordPress itself (kind of like a default) rather than created from scratch by a user?

Other potential options to consider – globe or comment-author-gravatar:

<img width="1083" alt="Screenshot 2021-12-03 at 10 39 45" src="https://user-images.githubusercontent.com/846565/144588986-cab5ba7e-e8f9-453f-b043-52e8d18fa4df.png">

**Comment by paaljoachim** [comment]
> Hmm, might the W icon might lead folks to believe that the template was added by WordPress itself (kind of like a default) rather than created from scratch by a user?

Good point!

The comment-author-gravatar seems like a good icon to add. It signals that the template was added by a user.

**Comment by jameskoster** [comment]
It's a _little_ strange to have a person icon coupled with the site name, but it's probably ok since this is a corner case.
