### ISSUE TITLE
Interface is getting more & more confusing rather than easier

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3708]
## Issue Overview
The interface for Gutenberg is getting more and more confusing with each release, with icons and toolbars spread all over the screen, and inconsistencies galore.

After clicking on the More icon and switching to Code Editor, I then clicked on the More icon again and based on the highlighting of the options, I have no idea what view I'm in. Am I in the Visual Editor, because it's highlighted and looks lik it's selected, or am I in the Code Editor because it has a tick next to it, even though it doesn't appear to be highlighted like the other option.

![screenshot_526](https://user-images.githubusercontent.com/2078245/33353742-70aec81a-d503-11e7-8d47-7747eb5c951b.png)

Somehow I managed to change a paragraph block into some other type of block. I have no idea what type of block it is. It says Paragraph at the top of the block so at first I just presumed it was a paragraph block, but after inserting another paragraph block, this new block acts differently which would lead me to assume that the original block isn't actually a paragraph block, even though it specifically says paragraph at the top!  I honestly have no idea what's happening!!! ¯\_(ツ)_/¯

![screenshot_527](https://user-images.githubusercontent.com/2078245/33353840-f66d652e-d503-11e7-9ccf-377b9a2b2c12.png)

The Fix toolbar to Block option seems to work sometimes and not other times. You can see in the screenshot above and below, that the Fix toolbar to Block option isn't selected, yet the toolbar is fixed to the top of the block. If I select the Fix toolbar to Block option, the toolbar for other paragraph blocks actually stick to the top of the block. When I turn this option off, the toolbar moves back to the top of the screen for the paragraph blocks, but not for the other block at the top of the post (which btw, I still have no idea what it is!!).

![screenshot_528](https://user-images.githubusercontent.com/2078245/33353880-224888f4-d504-11e7-9b15-8b8da31157a3.png)

These icons don't mean anything, and are way too tiny, and hard to read. You would expect all the social media icons to have their respective icons. Why does the Twitter embed not have a twitter icon!? Instead it has an icon of a pin and two angled brackets 🤔

![screenshot_529](https://user-images.githubusercontent.com/2078245/33354199-d02a9e20-d505-11e7-8a6b-3a782496670e.png)

Why is it showing all these other blocks under Recent? The only block I've actually used was a paragraph block, but for some reason, it's indicating that I've used Images, Galleries, Heading, Button, Tables and a bunch of other blocks which I haven't touched in this post. So, the end effect is that the only block that I've actually used in this post, is hidden right down the bottom of the list, out of view, which forces me to scroll and go look for it. The whole idea of a "recent" tab is to make it easier to access the blocks that I've recently used. Adding all these other blocks that I haven't actually touched, makes this tab useless!

![screenshot_530](https://user-images.githubusercontent.com/2078245/33354523-67ab0dba-d507-11e7-981f-e8cb695936be.png)

I see two meaningless icons which are identical, yet they perform completely different functions. I can just imagine talking to a client when they have an issue. "Click the icon with the 3 vertical dots. No, not that 3 vertical dot icon, the other three vertical dot icon at the top of the page"

![screenshot_534](https://user-images.githubusercontent.com/2078245/33354888-2627aff4-d509-11e7-95b6-3b73c0e926a4.png)

![screenshot_533](https://user-images.githubusercontent.com/2078245/33354893-28bb66c0-d509-11e7-95e7-b98b268b4446.png)

 
## Expected Behavior
I shouldn't feel this confused and frustrated when trying to add a few simple paragraphs of text. I honestly have no idea how an ordinary blogger is going to use this thing without feeling extremely overwhelmed.

## Possible Solution
Tidy up the interface. Make it more consistent when performing actions. If it says Fix toolbar to top, then ALL toolbars should fix to top, not just some. Stop forcing me to go from one side of the screen to the complete other side of the screen when performing actions. On a large screen desktop monitor, this is really annoying. I have to click all the way over on the left of the screen to add a block. The next minute I have to click all the way over on the right of the screen to perform some other action. Page tools should be grouped together. Design more meaningful icons. Don't use the same icon in different places on the same screen to perform different functions. If I see two identical icons, I would expect that they would allow me to perform identical actions!

_Firefox Quantum 57.0
Gutenberg Version 1.8.0
macOS Sierra 10.12.1_

**Comment by mcsf** [comment]
@maddisondesigns, while I appreciate the intention, this macro-issue isn't very actionable. I suggest opening a set of small, focused issues, each with clear reproducibility instructions and/or discussion when applicable, so that dedicated conversations and fixes can happen. Also, don't interpret this as rejection, as there are valid points, but I'll wait for the dedicated issues to discuss. Thanks.

**Comment by maddisondesigns** [comment]
I've created 6 separate Issues (as listed above) for each of the issues mentioned here. I'll close this one
