### ISSUE TITLE
Color Palette Hex Value copy/paste and edit options can be improved

### ISSUE THREAD

**Issue by ellenbauer** [WordPress/gutenberg#37083]
## What problem does this address?
1. I copy a hex value the # is being added. When I then paste the value into another palette the result in an error since two ## are added.

![gb-color-palette-issue](https://user-images.githubusercontent.com/17613630/144512865-3cc52537-7ce6-43cc-b763-d59beda8ed07.jpg)

2. Additionally the usability for the color picker could be improved, since copied and editing is easily confused. A user assumes that clicking on the color value results in the edit option not the coping of the value.

## What is your proposed solution?
1. If the hex value is copied the # should not be added, so that pasting the color value in another palette will work.

2. Regarding the confusion between the copy and edit options, I would change the icon to be a copy icon make the 'click into the color value' the edit behaviour. This seems to be a more common behaviour e.g. being used to Figma and other design tools.

**Comment by mirka** [comment]
Thanks for the report! Consolidating with #37083
