### ISSUE TITLE
WordPress 5.9 Beta 1 UI Issue:  Clear button and color palette value need to be separated by a space 

### ISSUE THREAD

**Issue by monika-12** [WordPress/gutenberg#37088]
### Description

Whenever you open a color setting of Block, you will see the clear button overlapped with the value of the color box. It looks bad in the user interface and needs to be fixed.

### Step-by-step reproduction instructions

- Drag Heading block and open settings
- Click on Color options
- No space is left between Clear button and color option value

### Screenshots, screen recording, code snippet

https://share.getcloudapp.com/8Lu9Aj6d

### Environment info

macOS Big Sur V-11.6
Browser: Google Chrome
Local Environment: Local by Flywheel
WordPress Version: development version (5.9-beta1)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I can replicate this (need to not have any custom colors added):

<img width="277" alt="Screen Shot 2021-12-03 at 11 05 51 AM" src="https://user-images.githubusercontent.com/26996883/144634250-36ad4684-45a8-4ce8-b436-80ac1d295019.png">

**Comment by ndiego** [comment]
Confirming as well, was just about to add this issue 😉

**Comment by glendaviesnz** [comment]
This was fixed in https://github.com/WordPress/gutenberg/pull/37016 which was back ported yesterday, so should be in beta 2
