### ISSUE TITLE
`useSetting( 'color' )` does not consider deprecated flag

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#37094]
### Description

`useSetting` allows consumers to access data coming from `theme.json`. For a few cases, we introduced logic to fallback to the corresponding deprecated setting ([see](https://github.com/WordPress/gutenberg/blob/e2f00ff5ed1f4042386a48eedf4eafef36c9eb29/packages/block-editor/src/components/use-setting/index.js#L18)), so `userSetting( 'color.custom' )` will fallback to `settings.disableCustomColors` or `typography.lineHeight` will fallback to `settings.enableCustomLineHeight`.

While this works when accessing the setting directly, it doesn't when the consumer accesses the top-level key: `useSetting( 'color' )` does not consider the special handling for `color.custom` and so on.

**Comment by jorgefilipecosta** [comment]
I'm not sure if we should fix this issue. useSetting('color') should not be used unless one really wants the raw value as they are in the structure. On https://github.com/WordPress/gutenberg/pull/36841 I missed the fact that in one of the usages we need the back-compatibility and that was the issue.

**Comment by oandregal** [comment]
I don't have strong opinions other than fixing the current status, which is bug-prone. Both options (adding the backcompatibility logic or don't allow using `color` directly) work for me.

**Comment by oandregal** [comment]
For the record, @youknowriad also argued that we shouldn't allow using `useSetting` with top-level keys: https://github.com/WordPress/gutenberg/pull/36900#discussion_r761867471
