### ISSUE TITLE
Gutenberg Camel Case typography doesn't work when the text is typed in uppercase.

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#37095]
### Description

This is a replica of this issue: https://github.com/Automattic/wp-calypso/issues/58800

----
### Quick summary

The typography setting on a Paragraph Block normally allows text to be converted to uppercase, to lowercase, or to camel case. Text that is natively typed in uppercase cannot be converted to camel case.

### Steps to reproduce

1. Insert a Paragraph Block.
2. Type text in all uppercase.
3. Attempt to convert the text to camel case.

https://user-images.githubusercontent.com/12906034/144537146-fed20074-f727-44cf-9ada-0e0bfc4fbf9b.mp4

### What you expected to happen

Any text should be able to be converted to camel case.

### What actually happened

Text that is natively typed in uppercase cannot be converted to camel case.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

I suspect that this would affect relatively few users because it's rare for users to type natively in all uppercase. As a workaround, users could convert the text case externally on a site such as https://convertcase.net/

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Andrew-Starr** [comment]
I think this is the expected behaviour, as the CSS property `text-transform: capitalize` only converts the first letter of each word to uppercase, with the other letters staying the same as written.

**Comment by talldan** [comment]
Agreed, the button's aria-label is 'capitalize' (and it should maybe have a visible tooltip), so I would consider this the expected behavior.
