### ISSUE TITLE
Can't change number of columns in Text Column block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3709]
## Issue Overview
When trying to change the number of columns in a Text Column block, the block simply displays the error "This block has encountered an error and cannot be previewed"

![screenshot_535](https://user-images.githubusercontent.com/2078245/33355246-c9e7c2cc-d50a-11e7-83f1-54f4811e01e5.png)

## Steps to Reproduce (for bugs)

1. Insert Text Column block
2. Add content to the default two columns
3. Use the slider to change the number of columns

## Expected Behavior
Expected to be able to change the number of columns

## Current Behavior
Block crashes and just shows an error

_Firefox Quantum 57.0
Gutenberg Version 1.8.0
macOS Sierra 10.12.1_

**Comment by mtias** [comment]
Thanks for the report, will do a 1.8.1 release for this.

**Comment by maddisondesigns** [comment]
@mtias Can you please reopen this as this still hasn't been fixed. It still breaks when changing the number of columns

**Comment by mtias** [comment]
@maddisondesigns it doesn't break for me after the referenced fix. Does it still break the same way for you?

**Comment by maddisondesigns** [comment]
@mtias Yes, this still breaks in 1.9.1

![gutenberg-textcolumns](https://user-images.githubusercontent.com/2078245/34548056-a9e786e6-f153-11e7-8ce4-0dc9c68e34bd.gif)

**Comment by maddisondesigns** [comment]
@mtias Still breaking in 2.0.0

**Comment by maddisondesigns** [comment]
@mtias can this please be re-opened as this still isn't fixed

**Comment by maddisondesigns** [comment]
@mtias Still breaking in 2.1.0

Can you please re-open this.
