### ISSUE TITLE
ColorPalette: no way to clear custom colors if the defaultPalette is disabled

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#37093]
### Description

The clear button is not displayed when the default palette is disabled in a block theme.

And there is no way to clear a color once it has been set because there is no clear button on the custom color picker.

I tried emptying the Hex color textbox, but it is overwritten by a color with a value of #000000.

I think we need to either always show a clear button in the color picker, or add a clear button on the custom color picker popover.

https://user-images.githubusercontent.com/54422211/144590067-5dfd83c0-4941-4129-8144-94144ca9af6d.mp4

### Step-by-step reproduction instructions

- Create a block theme with a minimum of files. (`style.css`, `index.php`, `templates/index.html`, `theme.json`)
- Write the following code in theme.json to disable the default color palette.
```json
{
	"version": 2,
	"settings": {
		"defaultPalette": false
	}
}
```
- Select the color panel ( in the paragraph block, for example. )
Open the custom color picker and make sure that you cannot clear the color once it is set.

### Environment info

- WordPress version: 5.8.2
- Gutenberg version:  latest trunk (12.1.0-rc.1)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@apeatling might you know someone who might be able to check this out based on recent work on this UI?

**Comment by t-hamano** [comment]
This issue should have been resolved by #37791, but I checked again and for some reason it has not been improved in the latest gutenberg.
However, the clear button appears correctly in WordPress 5.9.1 with PR backported.

### Step-by-step reproduction instructions

- Create a block theme with a minimum of files.
- **Deactivate** gutenberg plugin (Clean WordPress 5.9.1).
- Disable `defaultPalette` and `pallete` on `theme.json`.

```json
{
	"version": 2,
	"settings": {
		"color": {
			"defaultPalette": false,
			"palette": []
		}
	}
}
```

- Create new post and open ColorPallete from one of the blocks.
- Confirm that the clear button is exists.
- **Activate** gutenberg plugin.
- Create new post and open ColorPallete from one of the blocks.
- Confirm that the clear button is **not** exists.

https://user-images.githubusercontent.com/54422211/156575877-68ff6d6b-4d53-4e95-82ad-5d75ceb71216.mp4

Is my reproduction flow is incorrect ?

**Comment by t-hamano** [comment]
Related: #38903

The problem with the clear button not showing up may occur with or without the default palette.

**Comment by t-hamano** [comment]
I found that this issue is not a bug, but a deliberate design change, as described in #40960.
Therefore, I would like to close this issue.
