### ISSUE TITLE
duplicate styles custom header

### ISSUE THREAD

**Issue by lwangdu** [WordPress/gutenberg#37111]
### Description

Seem to me creating duplicate styles when I created custom header. Please the screen shots.

### Step-by-step reproduction instructions

create site header.
change background color
add custom padding please see the edit  screen shot.

Front end and inspect html section. Seem to me there are too many duplicate styles as you can see on the front end screen shot.

I am not sure supposed be like that or not.
![edit site](https://user-images.githubusercontent.com/24829573/144647477-8db0955c-6c2e-43e2-a172-f89637d31ef5.png)
![frontend](https://user-images.githubusercontent.com/24829573/144647482-7e6a9507-2383-4725-a2d2-e505ca3d0b91.png)

### Environment info

WordPress 5.9 beta 1
TwentyTwenty-Two
Chrome and MacBook Pro

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
From what I can see, this is intended :) @oandregal can you confirm and close out if so?

**Comment by oandregal** [comment]
I'd cc @ntsekouras or @youknowriad for thoughts on this one as it seems layout-related styles.

**Comment by youknowriad** [comment]
This is intended yes, but I think we can improve the situation by making the layout work like any preset. For this reason I'm closing this in favor of #36944
