### ISSUE TITLE
PHP Unit Tests are failing

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#37116]
### Description

Copied (with edits) from https://github.com/WordPress/gutenberg/pull/37100#issuecomment-985614521:

> [T]he remaining PHP unit test that's failing [is]
>
> ```
> 1) WP_REST_URL_Details_Controller_Test::test_will_return_from_cache_if_populated
> Failed asserting that 'Example Website — - with encoded content.' contains "This value from cache".
> 
> /var/www/html/wp-content/plugins/gutenberg/phpunit/class-wp-rest-url-details-controller-test.php:302
> ```
>
> is probably due to https://github.com/WordPress/wordpress-develop/commit/1270c897a9b9e9f0cd5baa765676ea15a9a13399 (committed today at 11:34 UTC): I noticed it wasn't present on `trunk` for https://github.com/WordPress/gutenberg/runs/4407241926?check_suite_focus=true (at 11:15 UTC) but for the following merge https://github.com/WordPress/gutenberg/runs/4408138725?check_suite_focus=true (at 12:51 UTC), and it touches `src/wp-includes/rest-api/endpoints/class-wp-rest-url-details-controller.php` which seems relevant to the error 😬 

### Step-by-step reproduction instructions

Look at PHP unit tests for any recent commit, or run `test-unit-php` locally.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
For fun, I [updated the filters](https://github.com/WordPress/gutenberg/pull/37122/files) to reflect the change in https://github.com/WordPress/wordpress-develop/commit/1270c897a9b9e9f0cd5baa765676ea15a9a13399

<img width="829" alt="Screen Shot 2021-12-04 at 2 57 03 pm" src="https://user-images.githubusercontent.com/6458278/144696031-a5d1958d-ddd5-43fb-804a-ef43a705a0f8.png">

😱

**Comment by ramonjd** [comment]
Does that mean we'd have to update https://github.com/WordPress/gutenberg/blob/36746203fb97e715d709adbc9e9ff71037a42f14/lib/class-wp-rest-url-details-controller.php with the same changes as https://core.trac.wordpress.org/changeset/52311?

I have no context about why Gutenberg has it's own `WP_REST_URL_Details_Controller` class.

**Comment by ockham** [comment]
Fixed by #37122. Thanks @ramonjd!
