### ISSUE TITLE
Errors during the build process

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37123]
### Description

I am unable to build the plugin from trunk.
`npm install `-no errors reported
On `npm run build`:

Error 1:
```
> gutenberg@12.1.0-rc.1 build:package-types D:\wordpress-develop\src\wp-content\plugins\gutenberg
> node ./bin/packages/validate-typescript-version.js && tsc --build

Build Progress: [                              ] 0%blocks:
  assets by status 341 KiB [cached] 148 assets

  ERROR in unable to locate 'D:/wordpress-develop/src/wp-content/plugins/gutenberg/packages/block-library/build-style/*/style.css' glob

  ERROR in unable to locate 'D:/wordpress-develop/src/wp-content/plugins/gutenberg/packages/block-library/build-style/*/style-rtl.css' glob

  ERROR in unable to locate 'D:/wordpress-develop/src/wp-content/plugins/gutenberg/packages/block-library/build-style/*/editor.css' glob

  ERROR in unable to locate 'D:/wordpress-develop/src/wp-content/plugins/gutenberg/packages/block-library/build-style/*/editor-rtl.css' glob

  ERROR in unable to locate 'D:/wordpress-develop/src/wp-content/plugins/gutenberg/packages/block-library/build-style/*/theme.css' glob

  ERROR in unable to locate 'D:/wordpress-develop/src/wp-content/plugins/gutenberg/packages/block-library/build-style/*/theme-rtl.css' glob

  blocks (webpack 5.47.1) compiled with 6 errors in 978 ms
```

I wonder if this is related to the upgrade of fast-glob:
https://github.com/WordPress/gutenberg/pull/36260/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L172

If I revert fast-glob back to version 2.2.7, I do not have any build errors, but I am unsure of what other issues that may cause.
(I don't even know what a glob is...) I do not know how to troubleshoot it further, or if I need to open an issue here? https://github.com/mrmlnc/fast-glob/

Error 2:
```
packages:
  assets by status 15.2 KiB [cached] 110 assets
  ./packages/block-serialization-spec-parser/parser.js 47.2 KiB [built] [code generated]

  ERROR in a11y
  Module not found: Error: Can't resolve './packages/a11y' in 'D:\wordpress-develop\src\wp-content\plugins\gutenberg'
```
There are several packages that can't be resolved, I only copied the first message.

### Step-by-step reproduction instructions

-

### Screenshots, screen recording, code snippet

-

### Environment info

Windows 10.
NPM 6.14.15.
Node v14.17.3.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I am also a Windows user and have encountered the exact same symptoms.
I don't know the exact cause, but I think it is because **the path separator is different between Windows and Mac OS.**

The build succeeded by following [the fast-glob documentation](https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows) and replacing the path separator in the two files as shown below.


- `/bin/packages/build.js`
- `/bin/packages/build-worker.js`

```javascript
const PACKAGES_DIR = path.resolve( __dirname, '../../packages' );

// to

const PACKAGES_DIR = path.resolve( __dirname, '../../packages' ).replace( /\\/g, '/' );
```

I think it is not enough to just modify these two since the `PACKAGES_DIR` constants are defined in various files, but I could not determine if it is appropriate to just modify all those constants.

Hopefully this information will help you fix it.

**Comment by t-hamano** [comment]
I looked into it, and this is a fix that is only needed for some tasks that use fast-glob.
So, I'd like to submit PR if these two fixes make it pass the local build and test.

**Comment by talldan** [comment]
In the changelog for fastglob 3:
> Only forward-slashes in glob expression. Previously, we convert all slashes to the forward-slashes, which did not allow the use of escaping. See pattern syntax section in the README.md file.

So that might explain it.

**Comment by carolinan** [comment]
This has been solved, so I am closing this issue.
