### ISSUE TITLE
Make it easier to deselect a block

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3712]
If you have a very brief post, clicking _below_ the post no longer deselects the block:

![can t select no metaboxes](https://user-images.githubusercontent.com/1204802/33368859-1c1e63a6-d4f3-11e7-8f77-5bb2594c4e7e.gif)

This is likely a regression from the inline metaboxes. Previously the block container was at minimum 100% tall, meaning you could always click below the blocklist on short posts. Now it can't be 100% tall because there can be metaboxes:

![can t select no metaboxes](https://user-images.githubusercontent.com/1204802/33368939-5df1bae4-d4f3-11e7-8093-8961bc02ab55.gif)

The problem, likely, is that it's the block container that registers clicks as de-selects. Should we expand that so clicking _anywhere_ outside the block itself deselects it?

**Comment by aduth** [comment]
>Should we expand that so clicking anywhere outside the block itself deselects it?

One complication here is that we need the block to remain selected in some cases when clicking outside:

- Toolbar buttons
- Sidebar inspector

**Comment by jasmussen** [comment]
Another option is to distinguish between whether you have metaboxes or not, so we can at least have a 100% tall canvas if you don't have metaboxes. I also noticed that clicking left and right of the title block did not deselect blocks.

**Comment by aduth** [comment]
Technically a duplicate of #2322

**Comment by jasmussen** [comment]
Closing on favor of that, thanks.
