### ISSUE TITLE
Navigation block erroneously requests /wp/v2/block-navigation-areas in WP 5.9

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#37138]
### Description

The Navigation block is making a request to /wp/v2/block-navigation-areas. 

https://github.com/WordPress/gutenberg/blob/26556937b70bbf4aaef8c112321703b61a740284/packages/block-library/src/navigation/edit/index.js#L112-L117

This won't work when the block is used in WP 5.9 without the Gutenberg plugin active as that REST API endpoint does not exist.

### Step-by-step reproduction instructions

1. Run the latest WP 5.9 trunk with no Gutenberg plugin active.
2. Open the site editor.
3. Insert a Navigation block if there isn't already one on the page.
3. Open DevTools and look in the console.
4. You'll see a 404 error from a request to `/wp/v2/block-navigation-areas`.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Could be tricky to solve. I think the original intent was to keep nav areas in the Gutenberg plugin until the deprecation period ends (not sure when that is and it might have already passed).

**Comment by noisysocks** [comment]
If it hasn't already passed then we could wrap the relevant bits of JavaScript with an `if ( process.env.GUTENBERG_PHASE === 2 )`.
