### ISSUE TITLE
Bug in footer of full site editing WP 5.9 Beta 1

### ISSUE THREAD

**Issue by edujca** [WordPress/gutenberg#37158]
### Description

I used a clean installation: only WordPress 5.9 Beta 1 with Twenty Twenty Two theme. Later, I've added Gutemberg, but nothing changed.
The problem is in footer block. I added a button. But, when I want to delete it with "Remove button" in submemu, the system says: "The editor has encountered an unexpected error", and two buttons: "Attempt recovery" and "Copy the error". "Copy the error" doesn't seem to do nothing. When I click "Attempt recovery", I go back to the starting point.
Ty.

### Step-by-step reproduction instructions

1.- Add a button to footer blok.
2.- Try to delete it in submenu "Remove button".

### Screenshots, screen recording, code snippet

[https://drive.google.com/file/d/1CnneSjz6pt9d1yfeahbBw0VRjUgILVvy/view?usp=sharing](https://drive.google.com/file/d/1CnneSjz6pt9d1yfeahbBw0VRjUgILVvy/view?usp=sharing)

### Environment info

- WordPress 5.9 Beta 1
- Gutenberg 12.0.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Presskopp** [comment]
please correct the link, thank you

**Comment by talldan** [comment]
I haven't been able to reproduce the issue. It'd be good to get some more testing on this though, just to make sure.

**Comment by Andrew-Starr** [comment]
I was able to recreate this issue with this setup:

WP 5.9 beta 1
Gutenberg not installed

Add a button to the footer.
Remove button and it works correctly.

Add a button to the footer again.
Save changes.
Navigate away from the editor, back to dashboard.
Reload the editor.
Try to remove the button, and the error appears exactly the same as in @edujca video.

With Gutenberg installed, the issue did not appear when I tested, only with WP 5.9. beta 1.

**Comment by Andrew-Starr** [comment]
This is the error returned:

```
t@/wp-includes/js/dist/block-editor.min.js?ver=a8b01d71ac9e7d60f9e1b8f0e5728b6a:26:10601
hHnB/t.a</B<@/wp-includes/js/dist/block-editor.min.js?ver=a8b01d71ac9e7d60f9e1b8f0e5728b6a:26:11207
j/<@/wp-includes/js/dist/compose.min.js?ver=79f0086c957c9b1383183795eeeb6a7b:2:6019
A@/wp-includes/js/dist/compose.min.js?ver=79f0086c957c9b1383183795eeeb6a7b:2:9288
I/<@/wp-includes/js/dist/compose.min.js?ver=79f0086c957c9b1383183795eeeb6a7b:2:9745
Qj@/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:177:1
unstable_runWithPriority@/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:24:26
Za@/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:8
eb@/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:170:165
gf@/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:162:319
$g/<@/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:230
unstable_runWithPriority@/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:24:26
Za@/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:8
$g@/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:178
ja@/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:111
@/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:240:210
Ki@/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:44:407
```

**Comment by Andrew-Starr** [comment]
With both 5.9 beta 1 and Gutenberg plugin active, I could remove the button but on the first click of 'remove button' nothing happens. I had to click it a second time to remove the button.

**Comment by Andrew-Starr** [comment]
A bit of further testing brings up a couple of further issues.

The issue is not restricted to the footer, and this issue occurs when trying to remove a button from any template or part (header, footer, page etc.)

Also, this is weird but when I activated Gutenberg plugin, and then removed the button it works correctly and the button is removed.
Then I deactivated Gutenberg so only running 5.9 Beta, and then went back into the editor, and the previously removed buttons were still present in the places where they had been originally added.

Apologies for the seperate comments. I should really have tested fully and put it all in one comment.

**Comment by hellofromtonya** [comment]
Note: Originally reported in WordPress Core's Trac https://core.trac.wordpress.org/ticket/54590.

**Comment by edujca** [comment]
Hello. Yes, The problem was at first time without Gutenmerg installed. After it, as Andrew Atar says,on the first click of 'remove button' nothing happens. It was necessary to click it a second time to remove the button.

**Comment by carolinan** [comment]
I have not been able to reproduce this with WordPress 5.9-beta3-52379-src.

**Comment by Thelmachido** [comment]
I wasn't able to reproduce this issue when Gutenberg was active and deactivated as shown in the short video below:


https://user-images.githubusercontent.com/41231764/189391652-44e3ef00-5797-4937-a329-2ba29feb0e0f.mov

- WordPress 6.0.2
- Gutenberg version 14.0.2
- Twenty Twenty-Two theme

I will close this issue as resolved for now
