### ISSUE TITLE
Site editor fails to load when theme directory contains a period

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#37156]
### Description

The site editor fails to load when the theme's directory name contains a period. It fails on an API request to load templates: 

```
/wp-json/wp/v2/templates/twentytwentytwo-0.4.0//home?context=edit&_locale=user 404 (Not Found)
```

cc @noisysocks as I think this should be in 5.9 must-haves, it was originally discovered in the Beta 1 testing period: https://core.trac.wordpress.org/ticket/54544#comment:12

### Step-by-step reproduction instructions

1. Install / activate a theme whose zip name contains a period, e.g. the [latest TT2 release zip](https://github.com/WordPress/twentytwentytwo/archive/refs/tags/v0.4.0.zip). 
2. Go to the site editor
3. Confirm nothing loads

### Environment info

- WordPress 5.8.2, and 5.9 Beta
- Gutenberg `trunk`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I'm not sure that having a period in the theme name is considered valid though?

**Comment by jffng** [comment]
> I'm not sure that having a period in the theme name is considered valid though?

Valid how so? I can upload a theme with a period in its name, or rename an existing one.

**Comment by mkaz** [comment]
Looking through theme handbook and I couldn't find any rules around the naming of a theme directory. A period is a valid character to include in a directory for example `theme-1.0/`  

For this case, technically it's not the name of the theme but the directory that holds the theme files. So, this bug is about the directory name and not the `Theme Name:` specified in the style.css file.

**Comment by jffng** [comment]
Thanks @carolinan @mkaz , I updated the issue title to clarify the issue is with theme directory vs name.

**Comment by noisysocks** [comment]
> cc @noisysocks as I think this should be in 5.9 must-haves, it was originally discovered in the Beta 1 testing period: https://core.trac.wordpress.org/ticket/54544#comment:12

Just noting that the PR (https://github.com/WordPress/gutenberg/pull/37167) was backported into beta 4.
