### ISSUE TITLE
Make classic the default editor from admin bar

### ISSUE THREAD

**Issue by mskogly** [WordPress/gutenberg#3716]
## Issue Overview

Tried to look for duplicate but couldn't find one.

When activating the pluging the Edit link in the admin bar takes the user directly into gutenberg mode. I would prefer if:

1. The default editor was the classic
2. Or: If the post has been touched by Gutenberg, use gutenberg editor.

If  an old post has a shortcode that has been turned off, the editor comes up blank, must switch to html edit to see and remove shortcodes. After that the rest of the document is viewable in the editor. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Hi @mskogly,

Thanks for the suggestion. We'll keep this feedback in mind as we work out the optimal balance between introducing Gutenberg and making sure the classic editor is available to those who need it.
