### ISSUE TITLE
Wrapping Heading block text overlaps previous lines for block-based themes

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#37168]
## Description

When adding a Heading block in the native mobile editor, the line height is incorrect and results in overlapping lines of text. It would appear an incorrect line height is set for the Heading block. 

**This issue only occurs in [development environments](https://github.com/WordPress/gutenberg/blob/88cb6a632b8d4a1505a25c63637358f6de4a7916/packages/rich-text/src/component/index.native.js#L900-L902) at the time of writing.** This issue occurs in the latest v1.67.0 release and first occurred in v1.64.0. It only occurs on Android, not iOS. It is likely related to https://github.com/WordPress/gutenberg/pull/35314. 

## Step-by-step reproduction instructions
1. Set the current theme to _Geologist_. 
2. Add a Heading block to the editor. 
3. Type enough words to wrap the text to a second line. 

## Expected behaviour
The wrapped second line of text does overlaps the first line of text. 

## Actual behaviour
The wrapped second line of text does _not_ overlap the first line of text. 

## Screenshots or screen recording (optional)

<img alt="Too small of line hight for the Heading block causes wrapped text to overlap previous lines of text on Android" src="https://user-images.githubusercontent.com/438664/144921636-3cef204f-b1a1-413e-bb8d-23487300d8cf.jpg" width="300" />

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: v12.0.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No, Geologist

## Device information
- Device: Samsung Galaxy S20
- Operating system: Android 11
- WordPress app version: Gutenberg Mobile v1.67.0

**Comment by dcalhoun** [comment]
@geriux do you think this may be related to https://github.com/WordPress/gutenberg/pull/35314?

**Comment by hypest** [comment]
> but not in the latest WordPress mobile app release (18.8)

👋 @dcalhoun! Trying to understand the setup, do you mean that the production WP app doesn't exhibit the issue? And since I see the screenshot in the ticket being from WPAndroid, does that mean the app was pointing to a running Metro server and thus, exhibiting the issue? Thanks!

**Comment by dcalhoun** [comment]
> 👋 @dcalhoun! Trying to understand the setup, do you mean that the production WP app doesn't exhibit the issue? And since I see the screenshot in the ticket being from WPAndroid, does that mean the app was pointing to a running Metro server and thus, exhibiting the issue? 

@hypest I believe the font size feature [resides behind a development flag](https://github.com/WordPress/gutenberg/blob/88cb6a632b8d4a1505a25c63637358f6de4a7916/packages/rich-text/src/component/index.native.js#L900-L902). So, the issue is not present in a packaged release, but is present when connected to a Metro server. I will update the Issue description to improve clarity.

**Comment by geriux** [comment]
Hey there 👋 I'm working on a [fix](https://github.com/WordPress/gutenberg/pull/37285) for this issue, as @dcalhoun mentioned this is behind a development flag so this is not happening on production. Thanks for finding this bug! 🙇
