### ISSUE TITLE
Minimum/Maximum font size in tag cloud block

### ISSUE THREAD

**Issue by CGTS** [WordPress/gutenberg#37166]
## What problem does this address?
Currently the minimum /maximum size for fonts in the tag cloud are predefined. Adding the option to set the minimum/maximum sizes would allow for a more predictable outcome in the design of a site.

## What is your proposed solution?
Add inputs for minimum and maximum font sizes.

**Comment by amustaque97** [comment]
Hi, I would love to work on this issue. 
Thanks :smile:
