### ISSUE TITLE
Paragraph element does not allow uppercase text

### ISSUE THREAD

**Issue by genesis16** [WordPress/gutenberg#37173]
Hello I have been working on a project and I noticed the paragraph element does not allow uppercase/Capitalization of text.I had to change to a h5 and change the font size etc to get capitalisation back. 

Wordpress version 5.8.2

**Comment by Andrew-Starr** [comment]
The Letter Case setting is hidden by default in the paragraph block, unlike the heading block where it is always visible.

To enable letter case options, click the **+** symbol next to Typography in the block sidebar panel, and select Letter Case to make this setting visible in the typography options.

The **+** symbol is replaced by three vertical dots if any of the other options (Appearance, Line height, Letter spacing, Drop cap) are already enabled.

**Comment by annezazu** [comment]
Closing this out thanks to @Andrew-Starr  excellent guidance 💥
