### ISSUE TITLE
Editor History: Site logo block undo and redo issue

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#37170]
### Description

Undoing and redoing an image block with an uploaded image restores said image. This, however, does not happen for the site logo block. Instead, it restores an empty site logo block.

What's curious is that deleting the site logo block and reintroducing it through the block appender retrieves the previously uploaded site logo without issue.

### Step-by-step reproduction instructions

**Block Editor**

1. Navigate to the post editor
2. Add a site logo block
3. Upload a site logo
4. Add a paragraph block
5. Undo until all added blocks are gone
6. Redo until the paragraph block reappears
7. Verify that the uploaded site logo does not reappear

**Site Editor**

1. Enable full site editing by activating the Gutenberg plugin and an FSE enabled theme (Ex. Quadrat)
2. Navigate to the site editor
3. Add a site logo block
4. Upload a site logo
5. Add a paragraph block
6. Undo until all added blocks are gone
7. Redo until the paragraph block reappears
8. Verify that the uploaded site logo does not reappear

### Screenshots, screen recording, code snippet

**Site logo block not working**

![2021-12-06 16 49 31](https://user-images.githubusercontent.com/5414230/144946525-ba47532a-4730-438d-9148-1c31c145cb29.gif)

**Image block working**
![2021-12-06 16 59 28](https://user-images.githubusercontent.com/5414230/144947654-3f454493-12fb-44ce-9e7d-921beb066beb.gif)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I just tested with WordPress 6.2 RC2, and this issue remains.

**Comment by Mamaduka** [comment]
It was fixed by #50911.
