### ISSUE TITLE
Editor History: Font size settings don't redo properly

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#37172]
### Description

If font-size is the first block typography setting I update, I can undo and redo sizing without issue. I'm, however, unable to redo font-size changes when they are made _**after**_ other typography updates (line spacing, line height, etc.).

Ex. I update line spacing _and then_ I update font-size. When I undo and redo, font-sizes won't redo properly.

### Step-by-step reproduction instructions

**Block Editor**

1. Navigate to the post editor
2. Add text to a paragraph block
3. In the paragraph block's block settings menu, update line height
4. Update font size
5. Undo until the text and typography updates are gone
6. Redo until you return to the current revision
7. Verify that font-size isn't restored

**Site Editor**

1. Enable full site editing by activating the Gutenberg plugin and an FSE enabled theme (Ex. Quadrat)
2. Navigate to the site editor
3. Add text to a paragraph block
4. In the paragraph block's block settings menu, update line height
5. Update font size
6. Undo until the text and typography updates are gone
7. Redo until you return to the current revision
8. Verify that font-size isn't restored

### Screenshots, screen recording, code snippet

![2021-12-06 20 02 49](https://user-images.githubusercontent.com/5414230/144964183-2a49f287-716c-4646-a3dc-35e414d097c8.gif)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
Thanks for reporting @jeyip ! I'm looking at it and will have a PR soon hopefully 😄
