### ISSUE TITLE
Button alignment not working

### ISSUE THREAD

**Issue by wolffe** [WordPress/gutenberg#37177]
### Description

The button alignment does not work. Setting everything correctly in the back-end is not reflected in the front-end.

Changes are saved correctly, there are no errors in the console, and there are no other plugins active.

## Back-end

![Screenshot 2021-12-07 103419](https://user-images.githubusercontent.com/910240/145013622-bb675c71-cc12-4654-b1b4-90f5d4381e45.png)

## Front-end

![Screenshot 2021-12-07 103525](https://user-images.githubusercontent.com/910240/145013634-8600514e-66f9-438d-873c-cd967838525a.png)

### Step-by-step reproduction instructions

1. Go to any post or page
2. Add a Buttons block
3. Add one or more buttons
4. Align them center or right
5. Save and check

### Environment info

- Windows 11
- Chrome (latest)
- Gutenberg 12.0.2
- WordPress 5.9-beta1-52329

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I wasn't able to replicate this with WordPress 5.9 beta 3 using the Twenty Twenty-two theme. Closing this out as a result!

<img width="1147" alt="Screen Shot 2021-12-14 at 10 43 29 PM" src="https://user-images.githubusercontent.com/26996883/146119355-c62a8488-e195-4b73-bea9-ad802a565f2e.png">
<img width="491" alt="Screen Shot 2021-12-14 at 10 43 39 PM" src="https://user-images.githubusercontent.com/26996883/146119359-e6fea70a-70fb-491f-8205-a24cc8d9516c.png">
