### ISSUE TITLE
Post Comments Form block mistakenly says comments are not allowed

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#37182]
In my `single-post` template I have an instance of the Post Comments Form block that is quite insistent (note the double message) that comments are not enabled for this post type:

<img width="705" alt="Screenshot 2021-12-07 at 12 21 29" src="https://user-images.githubusercontent.com/846565/145028472-90cebcd1-b9cf-4963-a9a3-dc100d4b29a7.png">

However, comments are in fact enabled, and I see the comment form on the frontend just fine:

<img width="769" alt="Screenshot 2021-12-07 at 12 24 26" src="https://user-images.githubusercontent.com/846565/145028530-42cf44ab-ca66-455c-abe3-946723f60583.png">

---

I think it's probably safe to go ahead and display the form regardless of whether comments are enabled. Otherwise things get tricky. For example the `singlular` template can resolve to display posts _and_ pages, yet it is possible for comments to be enabled for posts and not for pages. In this case, it's not clear how the current implementation would determine whether or not to display the form.

We can put an notice in the block settings to remind users that comments are not enabled for any particular post type.

**Comment by michalczaplinski** [comment]
I believe this should be fixed in https://github.com/WordPress/gutenberg/pull/40108
