### ISSUE TITLE
ToolsPanel UI prevents styling of multiple paragraph blocks at once

### ISSUE THREAD

**Issue by chad1008** [WordPress/gutenberg#37188]
### Description

When Typography settings were migrated to the ToolsPanel UI (https://github.com/WordPress/gutenberg/pull/33744), the ability to edit the typography styling of multiple paragraph blocks at once was lost.

Previously, users could highlight multiple paragraph blocks and style them all together. Under the new UI, the typography controls are no longer visible for multi-block selections, and only colors can be edited.

### Step-by-step reproduction instructions

1. Start at `/wp-admin/post-new.php`
2. Create two or more paragraph blocks with text content
3. Click into one of the paragraphs and note the available typography options in the sidebar
4. Click and drag to highlight from the beginning of the first block to the end of the last block
5. Note the typography options are gone from the sidebar, but color options remain available

_Originally [reported on WordPress.com](https://github.com/Automattic/wp-calypso/issues/58904)_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by WunderBart** [comment]
Looks like a good candidate to be covered by an e2e test!

**Comment by aaronrobertshaw** [comment]
A WIP in progress fix is up in https://github.com/WordPress/gutenberg/pull/37216. I've run out of time today but will continue on this tomorrow.

**Comment by aaronrobertshaw** [comment]
I'm closing this as https://github.com/WordPress/gutenberg/pull/37216 has merged. If there are any further issues let me know.
