### ISSUE TITLE
Make the navigation block more internally consistent

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#37190]
There's quite some code duplication in the navigation block code, leading to inconsistent behaviors when seemingly the same feature is used using a different control.

### Multiple code paths for creating new menus

There are many ways a user may create a new, empty menu, and they are handled by different code paths:

https://github.com/WordPress/gutenberg/blob/2f7f045a0d8955d5521f82a1a0d0a72e938679ed/packages/block-library/src/navigation/edit/placeholder/index.js#L145-L147

https://github.com/WordPress/gutenberg/blob/2f7f045a0d8955d5521f82a1a0d0a72e938679ed/packages/block-library/src/navigation/edit/placeholder/index.js#L101-L110

https://github.com/WordPress/gutenberg/blob/2f7f045a0d8955d5521f82a1a0d0a72e938679ed/packages/block-library/src/navigation/edit/index.js#L298-L307

<img width="919" alt="CleanShot 2021-12-07 at 17 05 09@2x" src="https://user-images.githubusercontent.com/205419/145064011-f2cc1b80-6938-4cf0-bc6f-5b34a4343095.png">

I would like to have a single code path that is executed for each of these buttons.

### Multiple data sources for dropdown menus

There are two ways of accessing a dropdown menus, and they output inconsistent items because each is handled by a different code path:

![menus](https://user-images.githubusercontent.com/205419/145065889-0c844e45-160f-4b15-a1b1-8802861274a0.jpg)

### Multiple code paths for menu switching 

They are more consistent with each other, but still slightly different.

Block toolbar:

https://github.com/WordPress/gutenberg/blob/2f7f045a0d8955d5521f82a1a0d0a72e938679ed/packages/block-library/src/navigation/edit/index.js#L377-L382

Placeholder:

https://github.com/WordPress/gutenberg/blob/2f7f045a0d8955d5521f82a1a0d0a72e938679ed/packages/block-library/src/navigation/edit/index.js#L520-L524

### Unintuitive logic

https://github.com/WordPress/gutenberg/blob/8676d2ab7e420f0c47d026bab61e7495ea101423/packages/block-library/src/navigation/edit/index.js#L627-L629

I found it confusing that we're showing a placeholder when `! isPlaceholderShown`. It would be nice to have a `<LoadingState />` component.

cc @noisysocks @talldan @draganescu @tellthemachines @getdave

**Comment by talldan** [comment]
The 'Navigation menu has been deleted or is unavailable' message is something I'd already deleted once (https://github.com/WordPress/gutenberg/pull/36507).

Not sure why it was brought back again.

**Comment by adamziel** [comment]
I took that screenshot before you removed it 😅

**Comment by noisysocks** [comment]
Is this a bug or a code quality task? Wondering if we can punt it from the 5.9 board. Help me out by adding a `[Type]` label 😄

**Comment by adamziel** [comment]
@noisysocks I would say it's both :D but if I have to choose, it's more of a Code Quality thing. It should be fine to fix it in 6.0. I intuitively sense a larger refactor would be needed here, which means new bugs, which isn't great during the Beta period.

**Comment by Mamaduka** [comment]
I'm removing this from the 5.9 board but will add it to the Navigation one.

**Comment by getdave** [comment]
@adamziel Let's work on these items. The complexity of the block code has increased a lot in the run up to 5.9 and we need to refactor now to save ourselves pain later.

Let's break this up into tasks:

- [ ] Create loading component for Nav block.
- [x] Consolidate code paths for `Select menu` dropdowns
- [ ] Consolidate code paths for code paths for creating new menus

Let's make Issues for tackling each one.

**Comment by talldan** [comment]
> I took that screenshot before you removed it 😅

It's definitely back again 😓 :
https://github.com/WordPress/gutenberg/blob/99c72bf584a6f0cf47d4db73f10998b8b7e1d1c3/packages/block-library/src/navigation/edit/index.js#L443-L458

Must have accidentally been brought back as the result of a bad conflict resolution.

**Comment by talldan** [comment]
While we're talking about code quality, something else I noticed today is that `useNavigationEntities` does a lot. As does `useNavigationMenu` now. I think we could divide them into separate hooks:
- usePages
- useClassicMenus
- useClassicMenuItems
- useNavigationMenus
- useNavigationMenuPermissions

One reason is that Pages don't need to be requested all the time, only when the placeholder shows.

**Comment by getdave** [comment]
This has become a bit stale. Going to close it out.
