### ISSUE TITLE
Quote block: Large style can cause confusion for the user

### ISSUE THREAD

**Issue by dashkevych** [WordPress/gutenberg#37202]
### Description

By default, the Quote block comes with "Large" style. The main purpose of this custom style is to display a quote with a with larger font size.

In WordPress 5.9, we have Typography options which allow the user customize typography settings of the block, including Font Size.

So, I am wondering if we really need to have this style in a core if there is an option in a core which allows to change a font size of a block?

Moreover, having this style along with Typography options  can cause confusion for the user. The thing is that Typography options are shown in the sidebar with an active "Large" styles; however, some of Typography options do nothing when setting them. The user might think that something is broken because options are shown but do nothing when selecting them.

There is also another issue with this style: #22305.

### Step-by-step reproduction instructions

1. Add Quote block in Editor.
2. In Styles, select Large style.
3. In Typography, change font size from "Default" to other available size.

### Screenshots, screen recording, code snippet

<img width="1722" alt="preview_large_style_quote" src="https://user-images.githubusercontent.com/3655965/145099963-c36fe9f7-8a3e-4990-9f98-286e51285a16.png">

### Environment info

 - WordPress: 5.9-beta1
 - Twenty Twenty-One: Version: 1.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mtias** [comment]
Yes, this style is largely obsolete and we can likely just remove it from the UI (keeping the class styles in place for back compat).
