### ISSUE TITLE
Add heading level selector on block insert

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/gutenberg#37211]
_Apologies if this has been suggested before - I searched the repo and couldn't find anything like it mentioned._

## What problem does this address?
When adding a new heading block, it's always a few clicks and mouse movements to select the heading level (h2, h3, etc.). It would be great if this could be done at the time of inserting the block.

## What is your proposed solution?
Add slash commands for heading levels - i.e. `/h2`, `/h3`, `/h4`, etc. - then typing one of those it adds the heading block and updates the block setting to be for the relevant heading level. This would save a bunch of mouse clicks and UI interactions.

**Comment by chthonic-ds** [comment]
> Add slash commands for heading levels - i.e. /h2, /h3, /h4

Good news, this is already supported:

![slash-heading-variation](https://user-images.githubusercontent.com/29587253/145149803-00e70d16-2121-4b00-910a-ec8bb619e3c3.gif)

**Comment by hlashbrooke** [comment]
Ah! It wasn't there last time I tried it, but this is great - thanks!
