### ISSUE TITLE
Make it possible to edit template part properties in focus mode

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#37220]
When a template part is selected in the template editing view it's possible to edit its properties like `area` in the Advanced panel:

<img width="1388" alt="Screenshot 2021-12-08 at 10 57 27" src="https://user-images.githubusercontent.com/846565/145196844-74d88ced-0ecc-4ff3-939b-689f47748efd.png">

It should also be possible to manage these properties whilst editing a tempalte part in focus mode. Perhaps in the currently-empty Template tab:

<img width="1268" alt="Screenshot 2021-12-08 at 10 58 23" src="https://user-images.githubusercontent.com/846565/145196985-a34398d5-0e3c-4734-8847-747ba3898f31.png">

Or the template details popover:

<img width="265" alt="Screenshot 2021-12-08 at 10 59 40" src="https://user-images.githubusercontent.com/846565/145197167-42838bf2-b5c3-4449-9646-9af11b4ecfc4.png">

**Comment by karmatosed** [comment]
I like the idea of the template tab but my concern is we are heading to multiple places for information. I get the desire to access important things, but you don't need access to everything in all places, so working out the interaction paths is key here and use cases.

**Comment by jameskoster** [comment]
For me it's more a question of appropriate hierarchy. For example I don't know that it should be necessary to enter template part focus mode to change a template part properties, that could lead to some frustrating UX. So placing those options in the Advanced panel seems sensible. 

But since focus mode feels like the primary template part editing interface, it seems logical that fundamental properties like the name should be editable there too.

**Comment by jameskoster** [comment]
In light of [discussions elsewhere](https://github.com/WordPress/gutenberg/issues/27093#issuecomment-1122278224) it might make sense to put these controls in the top toolbar, with a view removing the sad and empty "Template" tab from the insepctor.

| Editing a post  | Editing a Template Part |
| --- | --- |
| <img width="599" alt="Screenshot 2022-05-12 at 14 27 31" src="https://user-images.githubusercontent.com/846565/168085937-2d73a2b8-ed4b-4d5c-a65f-a82598a6a335.png"> | <img width="464" alt="Screenshot 2022-05-12 at 14 27 46" src="https://user-images.githubusercontent.com/846565/168085994-eb96a429-3a73-4ce5-b267-a249f7051783.png"> |

If we need a short-term solution, it would probably be fine to put these controls (area / html element) in the Inspector.

**Comment by annezazu** [comment]
[Noting that this came up with the recent FSE Outreach Program's usability testing](https://make.wordpress.org/test/2022/06/20/fse-program-sign-up-for-usability-testing-by-june-24th/) as a big point of confusion. Someone created a new template part as a "general" item but named it "header new". Later, when in template part focus mode and when looking at the list of template parts, they tried to find a way to change the categorization but couldn't find an easy way to do so.

**Comment by Mamaduka** [comment]
This enhancement would be a requirement for #37943. Otherwise, users won't have access to the template part options.

**Comment by Mamaduka** [comment]
@jameskoster, I'm planning to start working on this (probably early next week). I noticed that the only properties we can edit in focus mode would be the `title` and `area`.

## Why

In focus mode, we don't have access to the template part block, just its contents, so we cannot change attributes. However, the `title` and `area` are stored in the entity, and we can change that.

**Comment by jameskoster** [comment]
@Mamaduka makes sense, I think those are the most important attributes anyway 👍
