### ISSUE TITLE
Improve treatment of the "Template Part Not Found" message

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#37222]
When there's an error with a theme's template part, the site displays a message like this:

<img width="953" alt="Screen Shot 2021-12-08 at 8 12 42 AM" src="https://user-images.githubusercontent.com/1202812/145214276-1ac6fdb4-7aaf-413b-81ef-29daaa6cd2d3.png">

This is helpful for development, but it's also a very confusing thing to show to users. Can we adjust this so that it fails more gracefully? (In my testing, this message appears whether or not `WP_DEBUG` is on or off)

**Comment by talldan** [comment]
@kjellr I made an issue related to this too - https://github.com/WordPress/gutenberg/issues/36510, it might be possible to close one of them as a duplicate.

The message doesn't seem to work when I test it, but maybe that depends on what kind of template part it is (file vs post). It looks like I'm testing the latter and you're testing the former.

**Comment by talldan** [comment]
BTW, my instinct was that the block could show its placeholder instead of the message so that a user can at least pick a different template part, but there might be other options.

**Comment by kjellr** [comment]
Hmm. These seem similar, but might be slightly different? In the case here, I'm mostly concerned about these messages showing up to front-end visitors.

**Comment by talldan** [comment]
Yes, I didn't quite catch that this was on the front-end of the site. 👍 

Do you think this should be fixed for 5.9? My feeling is that it probably should be, so I'll add it to the project board.

**Comment by kjellr** [comment]
Yeah, I think it should be. Thank you!

**Comment by Mamaduka** [comment]
@kjellr, PR is ready for the review :)
