### ISSUE TITLE
Overrides ability to import/export in WooCommerce

### ISSUE THREAD

**Issue by zandyring** [WordPress/gutenberg#3723]
## Issue Overview
Gutenberg options override core functionality in WooCommerce; the ability to import or export products from the Products screen.

## Steps to Reproduce (for bugs)

1. Enable Gutenberg (1.8.0)
2. Enable WooCommerce (3.2.5)
3. Navigate to All Products
4. Notice you cannot import or export

## Expected Behavior
I wouldn't expect enabling Gutenberg to remove core WooCommerce functionality.

## Current Behavior
This is what you should see:
<img width="381" alt="screen shot 2017-11-29 at 3 48 02 pm" src="https://user-images.githubusercontent.com/7304712/33398566-69df25b0-d51d-11e7-9a3d-84f8f0276756.png">

This is what you do see with Gutenberg enabled:
<img width="393" alt="screen shot 2017-11-29 at 3 48 24 pm" src="https://user-images.githubusercontent.com/7304712/33398588-7926efc6-d51d-11e7-8478-4026343ffa02.png">

I wasn't sure if this should be posted to the WooCommerce repo instead (I can recreate it there if need be), but my thinking was that it is a functionality that was caused by Gutenberg, so to go to the source.

**Comment by jasmussen** [comment]
CC: @pento
