### ISSUE TITLE
Add a feature allowing a "Read more" button block to be added at the bottom of each query block

### ISSUE THREAD

**Issue by CalumChilds** [WordPress/gutenberg#37247]
## What problem does this address?

Using the full-site block editor, it is currently impossible to add a "Read more" button block below each post. It currently only allows you to add a link at the bottom of each query.

## What is your proposed solution?

My proposed solution is to add the ability for a button to be added at the end of each query block.

**Comment by talldan** [comment]
> It currently only allows you to add a link at the bottom of each query.

> My proposed solution is to add the ability for a button to be added at the end of each query block.

@Wingo5315 Just to clarify, is the distinction here that you'd like to see support for a button in addition to a link?

**Comment by ntsekouras** [comment]
>@Wingo5315 Just to clarify, is the distinction here that you'd like to see support for a button in addition to a link?

I think @Wingo5315 is talking about a brand new `read more` block that could be used inside `Query Loop` to automatically extract each posts link. This has been discussed before and could involve the removal of  the `read more` inside `Post Excerpt`.

**Comment by CalumChilds** [comment]
> Just to clarify, is the distinction here that you'd like to see support for a button in addition to a link?

That is correct.

**Comment by carolinan** [comment]
Until it is a separate block, you can still style the read more link to look like a button block with theme.json _elements_.

**Comment by carolinan** [comment]
Though I'm still confused; the post excerpt has the read more link, but it is a link for each post, not per query.
Did you mean per post item, or per query (per list with post items)?
"added at the bottom of each query block" -where would that button lead? to the very last post?

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @Wingo5315 hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @Wingo5315 hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!

**Comment by CalumChilds** [comment]
I think it would be good to do it for each query.

**Comment by vegetable-bits** [comment]
@carolinan Can we reopen it? I don't like to hack it with CSS, the problem is duplicate CSS and chaging the button won't change the fake more button link. Have a stronger CTA (button) is a common requirement.

I think the excerpt should not have a more link. We have already a seperate core/more-link, I think the best is to have a option it is a link or button.

**Comment by vegetable-bits** [comment]
@ntsekouras I came up to this solution for now. Anyway, won't it be better to extend `core/read-more` with a button style?

```js
import { registerBlockType } from '@wordpress/blocks';
import { InnerBlocks, useBlockProps } from '@wordpress/block-editor';
import { __ } from '@wordpress/i18n';

const Edit = () => {
	const blockProps = useBlockProps({
		className: 'wp-block-button',
	});

	return (
		<div {...blockProps}>
			<InnerBlocks
				template={[
					[
						'core/read-more',
						{
							className:
								'wp-block-button__link wp-element-button',
						},
					],
				]}
				templateLock="all"
			/>
		</div>
	);
};

const Save = () => {
	const blockProps = useBlockProps.save({
		className: 'wp-block-buttons',
	});

	return (
		<div {...blockProps}>
			<div className="wp-block-button">
				<InnerBlocks.Content />
			</div>
		</div>
	);
};

registerBlockType('notor/read-more-button', {
	title: __('Read More Button', 'your-text-domain'),
	icon: 'button',
	category: 'design',
	supports: {
		align: true,
		html: false,
	},

	edit: Edit,
	save: Save,
});
```

**Comment by carolinan** [comment]
Using theme.json is not a CSS hack.
Since what you are asking for is separate from having a button **in the query loop** please search for or open a new issue.
