### ISSUE TITLE
[Reusable Block]: Save button should go before cancel button.

### ISSUE THREAD

**Issue by Rolilink** [WordPress/gutenberg#37241]
## What problem does this address?
Having the cancel button as the first option feels odd.

## What is your proposed solution?
Swapping the save and cancel button positions.

This was enhancement was asked by a user in the `wp-calypso` repo in this [issue](https://github.com/Automattic/wp-calypso/issues/52506).

**Comment by karmatosed** [comment]
I agree having cancel first seems strange and also having it as a full-on button seems weird to me.

![2022-01-07 at 19 12](https://user-images.githubusercontent.com/253067/148594978-d5c58635-9808-4c2c-98ea-c41dca3e7c08.png)

I would probably expect it to be just a tertiary style link.

**Comment by Trapsta** [comment]
@karmatosed , I'd like to work on a PR for this

**Comment by Trapsta** [comment]
@karmatosed, I think we can close this ticket based on the feedback in https://github.com/WordPress/gutenberg/pull/39273 . The sentiment is for the buttons' order to remain the same and updating the style of the cancel button to tertiary has already been taken care of in a different PR
