### ISSUE TITLE
Block patterns section sometimes glitches

### ISSUE THREAD

**Issue by CalumChilds** [WordPress/gutenberg#37246]
### Description

When I go into certain categories of the Block Patterns section of the block inserter, it sometimes glitches back and forth quite rapidly. A video of it is shown here: https://calumchilds.com/videos/wordpress-gutenberg-issue.mp4

### Step-by-step reproduction instructions

1. Click the "Add" button on the top-left of the screen.
2. Click the "Block Patterns" section.
3. Click on the "Ballyhoo" block category.

### Screenshots, screen recording, code snippet

https://calumchilds.com/videos/wordpress-gutenberg-issue.mp4

### Environment info

- WordPress 5.8, Gutenberg 12.1, Ballyhoo 1.0.16
- Firefox
- Windows 10 Home OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I tried to replicate this but was unable to with Firefox on a MacOS using Gutenberg 12.1, the same Ballyhoo theme (v1.0.16), and WordPress 5.8.2. Can you try using 5.8.2 rather than 5.8 to see if the issue persists?

**Comment by CalumChilds** [comment]
I used WordPress 5.8.2 and the issue still persisted. I tested it on Google Chrome and it doesn't glitch, so it seems to be a Firefox on Windows issue.

**Comment by jordesign** [comment]
Closing this issue as there's been no further reports since Dec 2021. @CalumChilds if you still witness this happening in FF on Windows in WP6.3 please feel free to re-open the issue.
