### ISSUE TITLE
Post title and toolbar should be outside editor-styles-wrapper in the post editor

### ISSUE THREAD

**Issue by franmastromarino** [WordPress/gutenberg#37256]
### Description

Hello

The post title and tinymce toolbar should be outside editor-styles-wrapper in the post editor

Otherwise the theme styles like button and headings affect the interface elements

https://snipboard.io/sfu5pT.jpg

### Step-by-step reproduction instructions

https://snipboard.io/sfu5pT.jpg

### Screenshots, screen recording, code snippet

https://snipboard.io/sfu5pT.jpg

### Environment info

WordPress version: 5.8.2
Gutenberg version: 12.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment]
This was fixed in https://github.com/WordPress/gutenberg/pull/46212, because the classic editor is now in a modal. Note that the fix only takes effect if al registered blocks are version 3 or higher. As for the post title, it is designed to be styled so that it's a (close) preview of the front-end.

**Comment by franmastromarino** [comment]
Thanks @ellatrix
