### ISSUE TITLE
Consider allowing themes to opt in to wp-block-styles via theme.json

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#37255]
`wp-block-styles` was considered and removed from #35593, as per @jasmussen's [comment here](https://github.com/WordPress/gutenberg/pull/35593#issuecomment-942317331). 

This seems ok to omit by default, but I do think it would be helpful for themes to have the option of using theme.json to opt into this feature in general. Currently, they must do so via `add_theme_support()`. Currently, this is [the only theme support call that Twenty Twenty-Two needs to make](https://github.com/WordPress/twentytwentytwo/blob/601d3d2a3bf791c7b0fafd773c7ae6c86374c7c4/functions.php#L22-L30), and it would be great to migrate that over to `theme.json`.

**Comment by zaguiini** [comment]
It would be awesome if Gutenberg by itself figured out which styles it needs based on block usage and loaded them on demand.

Example: I'm using the Image block. It makes sense to include the Image styles, while still not needing to load all the other styles.

**Comment by chthonic-ds** [comment]
@zaguiini this has been possible since WP 5.8, more info here: https://make.wordpress.org/core/2021/07/01/block-styles-loading-enhancements-in-wordpress-5-8/. It's still required for a theme to opt in as of WP 5.9beta2 but https://github.com/WordPress/gutenberg/pull/35593#issuecomment-942267837 suggests it will eventually be enabled by default.

**Comment by scruffian** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/40097

**Comment by scruffian** [comment]
After a chat with @mtias we decided that this isn't the right approach. Instead we should move this CSS to Global Styles, and then build a mechanism to disable the core theme.json file:

https://github.com/WordPress/gutenberg/issues/33977
https://github.com/WordPress/gutenberg/issues/40181

This would render the `wp-block-styles` theme support obsolete.

**Comment by mtias** [comment]
`wp.block-styles` predates many of the block attribute tools and as such is a very opaque system. In time, things we expressed in the stylesheet should become part of the `theme.json` toolset (styling captions as `elements.caption`, specifying default views for blocks like Quote, etc). At that point an extra stylesheet is unnecessary and inconvenient, and absorbing its properties into attributes is much more flexible.
