### ISSUE TITLE
Bullet list block copy/paste jumps to new block

### ISSUE THREAD

**Issue by msdesign21** [WordPress/gutenberg#3726]
## Issue Overview

If I try to copy/paste text into a bullet list block the text gets pushed to a new block, rather than pasting the text into the block I am in. 

<img src="http://cld.wthms.co/7NWpRs+"/>

## Steps to Reproduce (for bugs)

1. Use [this Einstein test](https://wpusabilitytesting.polldaddy.com/s/gutenberg-flow-a?p=2&r=FAC5E49AF2C75EAD582AEB837A7EB5BE). 
2. in a new Gutenberg post start a bullet list block then copy/paste the bulleted Einstein text. 
3. You can also try copy/paste text from another application to recreate the issue. (does not happen if you try to copy/paste text that is already bulleted) 

## Expected Behavior

I expected the text I paste into the bullet list block to stay in that block. 

## Current Behavior

When I try to paste text into a bullet list block the text gets pasted in a new block below. 

## Screenshots / Video

Here's a video explaining the issue: http://cld.wthms.co/0c0HzF

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jorgefilipecosta** [comment]
Hi @msdesign21 thank you a lot for your report 👍 It looks like this bug is a manifestation of the more general problem described in https://github.com/WordPress/gutenberg/issues/3241. When solving the general problem this bug will also be solved.

**Comment by jorgefilipecosta** [comment]
With the merge of https://github.com/WordPress/gutenberg/pull/3949, this issue should be fixed :)

**Comment by msdesign21** [comment]
Oh great! Thank you Jorge!
