### ISSUE TITLE
Card Component Docs are not properly formatted

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#37266]
### Description

Docs for the [card component](https://developer.wordpress.org/block-editor/reference-guides/components/card/#context) are not rendering correctly in the handbook; likely in an issue in the markdown syntax used.  

### Step-by-step reproduction instructions

n/a

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/955351/145480759-849efc4c-7e22-4405-bdc9-95f5e67d4f8b.png)

### Environment info

n/a

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mkaz** [comment]
Fixed in #37268

**Comment by skorasaurus** [comment]
thanks :)
