### ISSUE TITLE
Image block: alignment doesn't work when heading block is below

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#37278]
### Description

This is a replica of https://github.com/Automattic/wp-calypso/issues/58732

### Step-by-step reproduction instructions

Add image block to page or post
Add heading block below
Align image to left or right
See that float doesn't work and heading stays below image

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/6737345/145565647-0606e1be-212e-48b2-b7f2-2ee57515d461.png)

### Environment info

- WordPress 5.8.2, Gutenberg 12.1.0, theme TwentyTwentyOne
- Chrome, MacOS latest versions(96.0, 12.1)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
👋 - thanks for reporting this. I couldn't replicate it. Could be something specific to a theme having `clear` to `Heading` blocks?

**Comment by Robertght** [comment]
Hey @ntsekouras !

Thank you for checking this!

I re-tested this and it appears to happen with TwentyTwentyOne and Varia(and the child themes).

**Comment by ntsekouras** [comment]
I'll close this as it seems it's just theme specific issue. For example in TwentyTwentyOne there is the `clear:both` style.


<img width="588" alt="Screenshot 2021-12-10 at 8 34 59 PM" src="https://user-images.githubusercontent.com/16275880/145624531-f34108d7-fe98-437c-ba3d-074c666f415d.png">
