### ISSUE TITLE
Switching quote styles with a bulleted list

### ISSUE THREAD

**Issue by msdesign21** [WordPress/gutenberg#3727]
## Issue Overview

When trying the Einstein test when you try to change the quote style the bulleted list below does not retain the correct formatting. 

## Steps to Reproduce (for bugs)

1. Use [this Einstein test](https://wpusabilitytesting.polldaddy.com/s/gutenberg-flow-a?p=2&r=FAC5E49AF2C75EAD582AEB837A7EB5BE). 
2. Place the image, quote, and bulleted text as suggested in the example. 
3. Try switching quote styles with the bulleted list below. 

## Expected Behavior

When switching quote styles I'd expect the bullets to stay in line with the bulleted list. 

## Current Behavior

Changing the quote style causes the bulleted list to move beneath the image, the bullets do not stay in line: 
<img src="http://cld.wthms.co/0GEXDG+"/>

In a second test the behavior was a little different when switching quote styles. 
<img src="http://cld.wthms.co/EsZ2uI+"/>

## Screenshots / Video

Here's a video walk thru of the issue: http://cld.wthms.co/HWRcFh

## Related Issues and/or PRs

This may be related to #3707 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jorgefilipecosta** [comment]
Thank you for your report @msdesign21 the bug should be fixed with the merge of https://github.com/WordPress/gutenberg/pull/3740.
