### ISSUE TITLE
Wolfram Cloud Block: embedding doesn't work

### ISSUE THREAD

**Issue by zaguiini** [WordPress/gutenberg#37288]
### Description

The Wolfram Cloud block doesn't work. Passing an object URL, such as https://www.wolframcloud.com/obj/49564e91-774a-4df0-9d0d-261616db8fe8, reverts the block to a paragraph instead of embedding the page.

### Step-by-step reproduction instructions

1. Open FSE;
2. Add the `Wolfram Cloud` block;
3. Put any object URL.

Verify that you get a `Paragraph` block instead of the requested embed block.

### Environment info

- WordPress 5.8.2;
- Gutenberg 12.1.0.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @zaguiini 

Wolfram embed will be supported after WP 5.9. Unfortunately, it won’t work with 5.8.

**Comment by zaguiini** [comment]
> Hi, @zaguiini 
> 
> 
> 
> Wolfram embed will be supported after WP 5.9. Unfortunately, it won’t work with 5.8.

Right! What if we hide this block on <=5.8?

**Comment by Thelmachido** [comment]
Looks like this is now supported, I cannot reproduce this issue as shown below: 
<img width="1090" alt="Untitled" src="https://user-images.githubusercontent.com/41231764/190084496-4bb18e17-90b6-4da3-a4bb-e191eec05c07.png">

WordPress version 6.0.2 

Gutenberg version 14.0.3

Closing this issue
