### ISSUE TITLE
icons displaying in bottom corner of screen when content added to custom field

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3728]
## Issue Overview
When I added some content to a custom field and then saved the paged, several icons and a search field displayed out of place, in the bottom left-hand corner of the screen

![screenshot_537](https://user-images.githubusercontent.com/2078245/33410129-d717e832-d5d2-11e7-826c-5f541b89fc70.png)

## Steps to Reproduce (for bugs)
1. Added content into an ACF custom field on a Page
2. Clicked Update and Update (because there's two update buttons)

_Firefox Quantum 57.0
Gutenberg Version 1.8.0
macOS Sierra 10.12.1_

**Comment by brandonpayton** [comment]
I'm unable to reproduce this and will close for now. Please let me know if you're still experiencing the issue.
