### ISSUE TITLE
Request: Query Loop columns, switch width & margin values from em to rem

### ISSUE THREAD

**Issue by Andrew-Starr** [WordPress/gutenberg#37295]
## What problem does this address?
I've noticed sometimes with the Query Loop when setting the columns to more than 1, resizing the browser window can cause the columns to be stacked when they should be in the same row.

It is very subtle when the browser width is changed just a fraction, but when it happens it makes the last column suddenly jump to below the 1st column, leaving a big empty space where it should be.

## What is your proposed solution?
In testing various configurations of site padding and content widths coupled with different font sizes, I found that using `rem` values for the column width and margins is stable, whereas the current `em` values are not.

For example, 2 columns the current CSS is like this:
```
.wp-block-post-template.is-flex-container.is-flex-container.columns-2 > li,
.wp-block-query-loop.is-flex-container.is-flex-container.columns-2 > li {
    width: calc(50% - .625em);
}

.wp-block-post-template.is-flex-container li,
.wp-block-query-loop.is-flex-container li {
    margin-right: 1.25em;
}

.wp-block-post-template.is-flex-container li,
.wp-block-query-loop.is-flex-container li {
    margin: 0 0 1.25em;
}
```

Changing `em` to `rem` such as this, fixes the issues I am seeing:
```
.wp-block-post-template.is-flex-container.is-flex-container.columns-2 > li,
.wp-block-query-loop.is-flex-container.is-flex-container.columns-2 > li {
    width: calc(50% - .625rem);
}

.wp-block-post-template.is-flex-container li,
.wp-block-query-loop.is-flex-container li {
    margin-right: 1.25rem;
}

.wp-block-post-template.is-flex-container li,
.wp-block-query-loop.is-flex-container li {
    margin: 0 0 1.25rem;
}
```

The noticable difference in the actual margin spacing is very minimal, but much more stable in all browser widths.

**Comment by Andrew-Starr** [comment]
Video showing the issue.

https://user-images.githubusercontent.com/94701043/145810841-805cc548-3794-4503-a228-c4b29c2ce6b7.mp4

**Comment by aristath** [comment]
I'm not sure that using `rem` would be appropriate... 🤔 
The benefit of `em` vs `rem` is that `em` units are relative to their parent, so if the blocks are nested inside a container that changes the font-size, `em` allows the blocks to adapt so their sizing is consistent with their surroundings.

Are we sure this is not a browser bug? I'm unable to replicate it on my system...

**Comment by Andrew-Starr** [comment]
Yeah it could be a browser bug. The issue does not appear in Edge or Chrome, only Firefox.

I don't know anywhere near enough about how browsers go about calculating these values, and why Firefox would seem to be different.

I should also say that in my testing I'm using a variable `contentWidth` like this `min( calc(100vw - 2rem), 80rem)` to give some padding and prevent content bumping right up against the edges on smaller screens, and also variable font sizes that resize relative to the browser window.

I'd really like to keep these, and also have it working in Firefox, but it seems that browser is just not up to the job when it comes to more complex calculations?

**Comment by Andrew-Starr** [comment]
Closing this issue.

The variable `contentWidth` is fine, but it seems Firefox does not play nicely with variable font sizes.

Back to the drawing board!
