### ISSUE TITLE
Documentation version request

### ISSUE THREAD

**Issue by overclokk** [WordPress/gutenberg#37306]
## What problem does this address?
From the [documentation](https://developer.wordpress.org/block-editor/) it is currently difficult to find information about older version of the API, for example if I need to create a plugin that support older version of Gutenberg if I search on the docs I can only find information updated to the last release.

## What is your proposed solution?

To add different version of the documentation for different version of Gutenberg and WordPress, you can see an example by the Bootstrap CSS or even Laravel docs where you can choose the version you need.

**Comment by ryanwelcher** [comment]
Related: https://github.com/WordPress/gutenberg/discussions/48998

**Comment by skorasaurus** [comment]
Hi, 

This is being tracked at https://github.com/WordPress/gutenberg/issues/44430
