### ISSUE TITLE
Shortcuts: Delete multi selection shortcut triggered when clearing sidebar controls

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#37316]
#### Current Behaviour:

While multiple blocks are selected, clearing values from inputs in the `BlockInspector` using `del` or `backspace`, will trigger the keyboard shortcut to delete blocks, unexpectedly removing them.

#### Expected Behaviour: 

Using delete or backspace to clear values in a control such as the `UnitControl` would only clear that input's value not trigger removal of multiple blocks.

### Step-by-step reproduction instructions

1. On trunk, create a Post and add multiple paragraph blocks with text to it
2. Select those multiple paragraphs together
3. In the block inspector expand the color panel, click the color swatch, then toggle the edit button for the color value
4. In the color value field, press either the `del` or `backspace` keys
5. Notice the blocks were deleted.

**Note: Typgraphy panel will not be visible for multiple selections until https://github.com/WordPress/gutenberg/pull/37216 lands. This issue can also be replicated using line-height or letter-spacing if testing with that PR branch.**

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/60436221/145759649-bdae255c-150e-4c02-891b-c18ec9310b5b.mp4

### Environment info

- WordPress 5.8
- Gutenberg: Latest

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
I have a very naive attempt at a fix in https://github.com/WordPress/gutenberg/pull/37326

It's based on the premise that we should execute block-specific side effects where the focussed keydown target is not in the block editor.

There are probably use-cases that defeat this premise though 🤷 

The curious thing is the block inspector search box does not trigger the keyDown event handlers.
