### ISSUE TITLE
The code editor is available in template editing mode but only shows the post content

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37320]
### Description

The code editor is available when editing a template in the template editor (accessed from the block editor).
The code editor shows the post content and the post title and nothing else -even if both blocks are removed from the template.

-I thought the code editor was not yet supported and that it was meant to be disabled both in template editing and the site editor.

### Step-by-step reproduction instructions

1. Activate a theme with support for template editing
2. Go to the block editor.
3. Create a new template.
4. When inside the template editor, select Options -Code editor
5. Compare the code in the code editor with the actual template.

### Environment info

WordPress 5.9-beta2-52361 via the beta tester plugin
With and without Gutenberg current trunk.

For the theme, I usedTwenty Twenty-Two and a classic PHP-based theme, underscores (_s), and added support for template editing.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
That's correct. FSE currently doesn't support Code Editor mode, and we should probably disable it in Template Editing Mode since it doesn't work correctly.
