### ISSUE TITLE
Add new ratios in ImageBlock AspectRatioDropdown

### ISSUE THREAD

**Issue by koraysels** [WordPress/gutenberg#37322]
## What problem does this address?
Add extra aspect ratios to crop the images. 

## What is your proposed solution?
A filter that we can use to add more aspect ratios in the editor. 

## possible other solution: 
can we  enable free crop ? With draggable borders, without constraining to an aspect ration?

**Comment by karmatosed** [comment]
An interesting idea @koraysels. Let me put some labels on this for some consideration.

**Comment by lydia-schow** [comment]
I also need something like this. A site I'm working on needs 2:1 images, but that's not an option in [the dropdown](https://github.com/WordPress/gutenberg/blob/acf909f8f4a15db031fb5dce3979d7f8556f4162/packages/block-editor/src/components/image-editor/aspect-ratio-dropdown.js#L79-L96). A filter would also allow me to remove aspect ratios that shouldn't be used.

**Comment by skorasaurus** [comment]
thanks for reported; there's a lot of discussion on this in https://github.com/WordPress/gutenberg/issues/38990 ; please subscribe to that issue to follow its progress.

**Comment by skorasaurus** [comment]
There's also a pull request that implements this as well! 

It's available at https://github.com/WordPress/gutenberg/pull/47271 

If you would like to test it out @elijah-schow @koraysels - You can by installing a version of the gutenbeg plugin that has this added to it by: 
1. visiting https://github.com/WordPress/gutenberg/pull/47271/checks 
2. open the "build gutenberg plugin zip" link 
3. open the 'gutenberg plugin link on that page (as a screenshot, see https://github.com/WordPress/gutenberg/issues/40483#issuecomment-1104593308 
4. unzip the folder twice and place it in your plugins folder.
