### ISSUE TITLE
Docs: Update Meta Boxes to a single page how to guide 

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#37345]
Update [Meta Boxes guide](https://developer.wordpress.org/block-editor/how-to-guides/metabox/) to a single page how to guide.

Several of the older how to guides use multiple steps and include a lot more detail than focusing on just the problem/solution they are documenting. A [how to guide template ](https://developer.wordpress.org/block-editor/contributors/documentation/#templates) was recently added and we want to convert the older documentation to this new format.

The goal is to focus on the single problem at hand, state prerequisites and expectations up front, link to guides that can better explain development environment or JavaScript introduction. Also, if possible create a plugin example in [gutenberg-examples repo](https://github.com/wordpress/gutenberg-examples).

An example is the update to the Format Toolbar API in #37298

**Comment by anoopd** [comment]
@mkaz  
              I tried to create a plugin example as said in the tutorials but i am getting the exact problem mentioned in https://github.com/WordPress/gutenberg/issues/23304#issuecomment-697569607  .  The value is getting saved for the first time but not getting updated after that .
