### ISSUE TITLE
Interface is confusing and unable to determine what type of block is on page

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3734]
## Issue Overview
Somehow I managed to change a paragraph block into some other type of block. I have no idea what type of block it is. It says Paragraph at the top of the block so at first I just presumed it was a paragraph block, but after inserting another paragraph block, this new block acts differently which would lead me to assume that the original block isn't actually a paragraph block, even though it specifically says paragraph at the top! I honestly have no idea what's happening!!! ¯\_(ツ)_/¯

![screenshot_527](https://user-images.githubusercontent.com/2078245/33416393-5c3b70e8-d5f0-11e7-98ce-3af74c3794f4.png)

## Steps to Reproduce (for bugs)
1. Convert paragraph block into one of the above blocks. I have no idea what block it is!
2.
3.
4.

## Expected Behavior
I should be able to tell exactly what every single block is on my page just by looking at them. I shouldn't feel this confused and frustrated when trying to add a few simple paragraphs of text.

## Current Behavior
I've have a  block on my page and I have no idea what type of block it is, or why it behaves in the way it does. It says Paragraph at the top of the block, but I'm pretty sure it's not a Paragraph block because it behaves differently to other Paragraph blocks.

## Possible Solution
Make it easier to differentiate between each block. Each block should have the name of the block either at the top of the block, in the Block tab in the right-hand sidebar, or in the toolbar at the top of the page. Currently I have no way of telling which block is which. I honestly have no idea how an ordinary user/blogger is going to use this thing without feeling extremely overwhelmed and confused.

## Related Issues and/or PRs
#3708

_Firefox Quantum 57.0
Gutenberg Version 1.8.1
macOS Sierra 10.12.1_

**Comment by jasmussen** [comment]
Agreed. It would be good with a block type indicator to clearly indicate what you're looking at. In this case you were looking at a "Classic Text" block, which definitely does behave differently to a Paragraph block. 

Given there's a ticket for a block type indicator, #3081, can we close this one in favor of that?

**Comment by maddisondesigns** [comment]
@jasmussen Yep. That's fine. I'll close this one. Thanks for pointing that other one out. That pretty much covers what this one is about.
