### ISSUE TITLE
Converting Group Block to Cover Block removes content

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#37342]
### Description

This came up as part of the [eleventh call for testing for the FSE Outreach Program](https://wptavern.com/fse-outreach-round-11-going-on-a-site-editing-safari): 

>The biggest, ahem, hiccup that I ran into wiped all of my progress when editing my header. I tried to transform one of the outer Group blocks into a Cover to give it a background. It wiped everything in the header area clean, and the “undo” button did not seem to work. I just started over.

Unclear if this might be resolved by this PR that addresses a similar emptying effect with grouping/ungrouping: https://github.com/WordPress/gutenberg/pull/37280 

When testing, I found that hitting undo _twice_ brought back what was originally there. Undoing once, led to a weird in between state. Tied to this, I was surprised the double undo wasn't resolved by this from @Mamaduka  https://github.com/WordPress/gutenberg/pull/36807 

### Step-by-step reproduction instructions

1. Activate FSE and the TT2 theme.
2. Using List View, select a Group block within the Header.
3. Using the transforms menu, change the Group Block to a Cover block.
4. Notice the content gets emptied out.
5. Hit undo and notice it partially gets reverted but not all the way to what was there before.
6. Hit undo again and see content back to as it was. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/145910802-77a73c67-6668-4e1c-bb7d-2b994de2f0d5.mov

### Environment info

- WordPress 5.9-beta2
- Gutenberg 12.1.0
- Twenty Twenty-Two Theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Adding to 5.9 board so it can be triaged :)

**Comment by Mamaduka** [comment]
I was able to reproduce the issue on the current trunk. I will see if I can track it down further.

**Comment by Mamaduka** [comment]
I'm getting slightly different behavior when testing with Reusable Blocks:

* The content isn't lost during transformation, but only if I undo transformation action.
* Saving the post doesn't trigger a reusable block update
* After refreshing the page, the content is back.

## Screen reconding

https://user-images.githubusercontent.com/240569/145956216-464426f8-55f9-4c16-889c-0ef82b0ca257.mp4


/cc @youknowriad, @ntsekouras

**Comment by Mamaduka** [comment]
@annezazu I think this issue got fixed via #37484. Can you confirm?

## Screencast
https://user-images.githubusercontent.com/240569/147197383-a2fa35f3-76dd-42bf-9c82-92e35914c85f.mp4

**Comment by annezazu** [comment]
Can confirm! Just tested and it doesn't remove the content. Thank you for connecting the dots.
