### ISSUE TITLE
'Fix Toolbar to Block' option doesn't work consistently

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3735]
## Issue Overview
The Fix toolbar to Block option seems to work sometimes and not other times. You can see in this screenshot

![screenshot_527](https://user-images.githubusercontent.com/2078245/33417175-7b2c8f42-d5f4-11e7-8d59-0cfdb5f78670.png)

and the one below, that the Fix toolbar to Block option isn't selected, yet the toolbar is fixed to the top of the block. If I select the Fix toolbar to Block option, the toolbar for other paragraph blocks actually stick to the top of the block. When I turn this option off, the toolbar moves back to the top of the screen for the paragraph blocks, but not for the other block at the top of the post (which btw, I have no idea what type of block it is!!).

![screenshot_528](https://user-images.githubusercontent.com/2078245/33417126-353f47fe-d5f4-11e7-9acb-859f2e10392d.png)

## Steps to Reproduce (for bugs)
1. Select and deselect the Fix toolbar to block option and notice that some toolbars move and other dont

## Expected Behavior
I would expect that the toolbar on every block would switch between being displayed at the top of the block, or at the top of the page

## Current Behavior
Behaviour is inconsistent. The toolbar moves for some block but not for others

## Related Issues and/or PRs
#3708

_Firefox Quantum 57.0
Gutenberg Version 1.8.1
macOS Sierra 10.12.1_

**Comment by youknowriad** [comment]
Yes, we're aware of the exception of the "classic text block" and it's intentional. The classic text block is a block used to mimic the same behavior as the classic WP editor which could have several rows of toolbars and be personalized using plugins like TinyMCE Advanced. 

cc @jasmussen

**Comment by maddisondesigns** [comment]
Well that's extremely confusing and I'll be very surprised if this doesn't get raised as an issue over and over again once everyone starts using it. This block is much easier to use than the standard paragraph block as it doesn't litter your page with dozens and dozens of individual tiny blocks and actually makes moving multiple paragraphs of similar content, significantly easier than trying to move a dozen individual paragraph blocks.

**Comment by jasmussen** [comment]
I hear you, and Riad's notes are right on for now.

These days and weeks we are actively usertesting both the block-docked, and the top-docked toolbars to see which fare the better, and what information we might glean from them to improve toolbars overall. I suspect we can revisit this ticket once that dust settles.

**Comment by danielbachhuber** [comment]
@jasmussen @youknowriad Is this issue actionable, or can it be logged as feedback and closed?

**Comment by jasmussen** [comment]
@karmatosed can you recall the resent usertests on the top-docked vs. block-docked toolbar? I seem to remember the block-docked toolbar winning here.

If the results are mostly a wash, and we agree that keeping the option to choose where to place the toolbar (which I think we should), then there probably isn't much we can do here. 

If the top-docked toolbar tests are a clear winner, we could consider removing the block-docked toolbar, and re-doing the Classic toolbar so it's also top-docked.

**Comment by karmatosed** [comment]
Right now the winner is block docked by default and the option is useful for those that desire it. I think having the option right now is ok. Top docked is a clear not winner as soon as we have it by default users get lost.

For now, as a result lets close this.

**Comment by maddisondesigns** [comment]
This still doesn't change the fact that this bar doesn't move for the Classic block. It's pretty confusing that if someone does select the _Fix toolbar to Top_ option, the bar moves for every block except one.
