### ISSUE TITLE
Provide typography support at the Group block level.

### ISSUE THREAD

**Issue by Andrew-Starr** [WordPress/gutenberg#37363]
## What problem does this address?

Currently the Group block does not have typography controls.

Please see https://github.com/WordPress/gutenberg/issues/37330 for details of the issue.
## What is your proposed solution?

Consider adding typography support at the Group block level.

**Comment by Andrew-Starr** [comment]
Closing as will be fixed in https://github.com/WordPress/gutenberg/pull/37456

**Comment by talldan** [comment]
Usually we keep issues open, but link the PR to the issue. Then means when the PR is merged github will automatically close the issue.
