### ISSUE TITLE
Rename WP_Theme_JSON_Resolver methods to replace `custom_post_type` references

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#37379]
### Description

This issue is opened in to resync Gutenberg with WordPress Core. Core does not use `custom_post_type` naming as it's not custom to Core. In [Core's Trac ticket 54517](https://core.trac.wordpress.org/ticket/54517) and [changeset 52372](https://core.trac.wordpress.org/changeset/52372), the following methods were renamed:

* `WP_Theme_JSON_Resolver::get_user_custom_post_type_id()` renamed to `WP_Theme_JSON_Resolver::get_user_global_styles_post_id()`
* `WP_Theme_JSON_Resolver::get_user_data_from_custom_post_type()` renamed to `WP_Theme_JSON_Resolver:: get_user_data_from_wp_global_styles()`

This issue seeks to resync Gutenberg with Core to aid in backporting changes to Core.

### Step-by-step reproduction instructions

NA

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by oandregal** [comment]
Thanks, Tonya, for tracking the changes back to Gutenberg.
