### ISSUE TITLE
Update the editor's default font sizes

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#37378]
As per the comments in https://github.com/WordPress/gutenberg/pull/37038#issuecomment-993599138, we should update the default font-size presets provided by Gutenberg [as defined here](https://github.com/WordPress/gutenberg/blob/61de10636cca2869269db2c20315b763d11927fc/lib/compat/wordpress-5.9/theme.json#L196-L221). This will drop down to 4 sizes, eliminating the "Normal" font size.

```
"fontSizes": [
	{
		"type": "small",
		"size": "13px"
	},
	{
		"type": "medium",
		"size": "20px"
	},
	{
		"type": "large",
		"size": "36px"
	},
	{
		"type": "x-large",
		"size": "42px"
	}
],
```

When we remove the "Normal" font size, we'll need to provide a CSS fallback so that existing content with the `has-normal-font-size` class will continue to show at the previously supported font size (`16px`). Similarly, we'll need to make sure the "Huge" font size now maps to the x-large size.

**Comment by oandregal** [comment]
PR for this at https://github.com/WordPress/gutenberg/pull/37381
