### ISSUE TITLE
Block styling disappears for single block when multiple are highlighted

### ISSUE THREAD

**Issue by eoinsav** [WordPress/gutenberg#37385]
### Description

When highlighting text in a Paragraph Block, the following controls are available:

<img width="432" alt="Markup 2021-12-14 at 12 50 29" src="https://user-images.githubusercontent.com/35590156/146077283-6c5361a5-73df-40f2-b08b-c450ffdbd819.png">

--------

If you accidentally highlight another Block with your curser and then move it back, the above controls are gone, as shown here:

<img width="273" alt="Screenshot on 2021-12-14 at 12-51-48" src="https://user-images.githubusercontent.com/35590156/146077487-73978f0e-cbf4-405f-aacd-220dcb30e001.png">

### Step-by-step reproduction instructions

1. Add two paragraphs.
2. Highlight some text without leaving that Block and you should be able to make the text bold, italic, or add a link.
3. Highlight some text and leave that Block temporarily. Then move the cursor back up to the highlighted text and the bold, italic, etc options will be gone.

Here is a recording of that for clarity:

![Screen Capture on 2021-12-14 at 12-46-04](https://user-images.githubusercontent.com/35590156/146077812-d42f0467-f421-4b33-8172-a0a01ca5a369.gif)

### Environment info

WP Version 5.8.2
Gutenberg Version 12.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by eoinsav** [comment]
Probably related: https://github.com/WordPress/gutenberg/issues/37188

**Comment by carolinan** [comment]
I can reproduce this on 5.9-beta3-52379-src and Gutenberg trunk (Chrome, windows)

**Comment by ntsekouras** [comment]
Thanks for reporting this @eoinsav!

This seems to have been resolved here: https://github.com/WordPress/gutenberg/pull/38821, so I'm closing the issue. Feel free to reopen if you can still reproduce.

**Comment by eoinsav** [comment]
I am still able to recreate this on a few sites.

**Comment by jordesign** [comment]
I can also no longer recreate this in WP6.3.

I'll close it once again - but if there are instances where it still can be reproduced, please re-open with additional details.
