### ISSUE TITLE
__experimentalUseInnerBlocksProps is not available in Wordpress 5.9?

### ISSUE THREAD

**Issue by wpsoul** [WordPress/gutenberg#37386]
### Description

Today I tested beta version 2 for Wordpress 5.9 and found that this module is not available 

TypeError: (0 , _wordpress_block_editor__WEBPACK_IMPORTED_MODULE_4__.__experimentalUseInnerBlocksProps) is not a function

Will it be available in final release? Is any way now to make inner blocks without wrappers "block-editor-inner-blocks"?

### Step-by-step reproduction instructions

1. Use 

import {
	InnerBlocks,
	__experimentalUseInnerBlocksProps as useInnerBlocksProps
} from '@wordpress/block-editor';

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@wpsoul I believe the API is stable from WordPress 5.9 onwards, so your code would just be:
```jsx
import {
    useInnerBlocksProps
} from '@wordpress/block-editor';
```

However, for backwards compatibility with older WordPress versions you'll want to import both and check which one is defined.

**Comment by wpsoul** [comment]
Unfortunately, there is no option to check. Once you load both, one of module will break the code and there is no conditional import functionality. 

Some methods must be added to core to prevent breaking, for example __experimentalUseInnerBlocksProps must load proper module on both versions of Wordpress.

**Comment by talldan** [comment]
> Unfortunately, there is no option to check. Once you load both, one of module will break the code and there is no conditional import functionality.

> Some methods must be added to core to prevent breaking, for example __experimentalUseInnerBlocksProps must load proper module on both versions of Wordpress.

That isn't true. Imports for things that don't exist resolve to `undefined`, so you can use a simple ternary to handle backwards compatibility.

```jsx
import {
	useInnerBlocksProps as __stableUseInnerBlocksProps,
	__experimentalUseInnerBlocksProps,
} from '@wordpress/block-editor';

function MyBlock() {
        // ...

	const useInnerBlocksProps = __stableUseInnerBlocksProps
		? __stableUseInnerBlocksProps
		: __experimentalUseInnerBlocksProps;
    
        // ...
}
```

**Comment by wpsoul** [comment]
"for things that don't exist resolve to undefined"

Unfortunately for me, it generates error in webpack instead of undefined and all code crashed. I will check, maybe it's because of webpack settings

**Comment by giannis-koulouris-bb** [comment]
I have a similar concern when I use experimental components, I haven't figured out what is the best way to safely use them. I was expecting at least for the version of Gutenberg coming with WP Core to have a deprecation mechanism, a warning or something in the console letting you know that a certain component will change

**Comment by talldan** [comment]
> I have a similar concern when I use experimental components, I haven't figured out what is the best way to safely use them. I was expecting at least for the version of Gutenberg coming with WP Core to have a deprecation mechanism, a warning or something in the console letting you know that a certain component will change

@giannis-koulouris-bb One of the main purposes of the obtuse experimental prefix is to encourage developers not to use them, because there's a strong chance they'll break. The project is also not shy about making breaking changes to experimental APIs.

On the other hand, stable APIs are supported for a long time and will have deprecation notices.

So the best recommendation is not to use anything experimental. I realise sometimes an API will stay experimental for a long time, so that's a little difficult. Other times you may also want to prepare a plugin for an upcoming WordPress release. Still best to try to not use them if you can.

**Comment by wpsoul** [comment]
@talldan Problem here is that Gutenberg has huge amount of such experimental components and all of them are very useful and used in all complex Gutenberg plugins and themes. So, we need clear and safe migration guide in all new versions of Wordpress. 

I am reading Field Guide 5.9 and there is nothing about many deprecations. It means that many plugins will be broken and developers of plugins have no chance to know about deprecations until something will be broken.

**Comment by pbiron** [comment]
> > Unfortunately, there is no option to check. Once you load both, one of module will break the code and there is no conditional import functionality.
> 
> > Some methods must be added to core to prevent breaking, for example __experimentalUseInnerBlocksProps must load proper module on both versions of Wordpress.
> 
> That isn't true. Imports for things that don't exist resolve to `undefined`, so you can use a simple ternary to handle backwards compatibility.

Thanx Dan!  This works like a charm for me.

I added a comment to the [Take more control over Inner Block Areas (as a block developer)](https://make.wordpress.org/core/2021/12/28/take-more-control-over-inner-block-areas-as-a-block-developer/#comment-42393) dev note linking to your comment.
