### ISSUE TITLE
Post Comments Form Block error upon updating to 5.3 beta

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#37389]
### Description

This might be quite an edge case but, to be safe, reporting here. After using GB + beta 2 or 5.8.2 and adding in the Post Comments Form block, upon updating to 5.3, I see an error and the block does not load. I recognize this might be due to some happenings with the Comments Loop work potentially https://github.com/WordPress/gutenberg/issues/34994. cc @SantosGuillamot for any insights!

### Step-by-step reproduction instructions

1. Have a test site with 5.8.2 or 5.9 Beta 2 (didn't test with Beta 1) and Gutenberg installed and TT1 or TT2 as your theme.
2. Open up the site editor and add in the Post Comments Form block. I added it within a Query Loop.
3. Update your site to 5.9 Beta 3. 
4. Deactivate Gutenberg. 
5. Go to the Site Editor and see an error with the Post Comments Form block.

### Screenshots, screen recording, code snippet

<img width="871" alt="Screen Shot 2021-12-14 at 10 27 20 PM" src="https://user-images.githubusercontent.com/26996883/146117821-c43d1b59-a3b0-433d-8cc0-13f5333e3854.png">

### Environment info

- Starting with 5.9 Beta 2 or 5.8.2 before switching to WordPress 5.9 beta 3
- No Gutenberg
- TT1 and TT2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
Post Comments Form block is still experimental inside the Gutenberg plugin. It isn’t part of WordPress 5.9 release as well. The only block related to comments that WP 5.9 ships is the Post Comments block.

**Comment by annezazu** [comment]
I somehow missed this :) For reference, pulled up this discussion: https://github.com/WordPress/gutenberg/pull/35979#issuecomment-956937732 Closing this out as a result. Thanks for connecting the dots!
