### ISSUE TITLE
The animation in the welcome guide for the template editor hides the close button

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37399]
### Description

In the welcome guide for the template editor, the animation has dark grey background.
Once the animation stops, the close button which is also dark grey or black (#1e1e1e), is barely visible.
The contrast ratio for the background color and the icon is only 1.1.1.

### Step-by-step reproduction instructions

1. Activate a theme with support for template editing.
2. Create or open a post or page, and create or open a template.
3. Show the welcome guide.
4. Try to see the icon for the close button.

### Screenshots, screen recording, code snippet

![The welcome guide close icon is dark grey over a dark grey background](https://user-images.githubusercontent.com/7422055/146154144-6422d7b4-ba9f-4447-8f46-63a504bb2ba1.png)

### Environment info

WordPress 5.9-beta3-52379 Through the beta tester plugin
With and without Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by glendaviesnz** [comment]
Fix for this at #37435 - the only thing I wasn't sure about was how important the hover state color change is, ie. with the default dark grey icon the hover state is white, but with switching default to white there is now no change on hover. I don't think it matters but can add in some sort of difference on hover if others think it is important.
