### ISSUE TITLE
Unified Payment Interface [UPI] links corrupted by Gutenberg

### ISSUE THREAD

**Issue by mitradranirban** [WordPress/gutenberg#37398]
Unified Payment Interface or in short UPI is a revolutionary digital payment method created in India which has made digital payments simple, accessible, safe and secure. One way a person can simply pay through upi is to click a upi protocol url such as upi://pay?pa=MyVPA&pn=MyName&am=Amonunt&cur=INR . Though such urls work perfectly in vanilla webpages when clicked, by opening up upi enabled app for payment, gutenberg corrupts the urls by replacing the upi:// protocol with https:// protocol even when indicated by html mode. It will be better if Gutenberg supports upi protocols by a separate menu options which can be populated by necessary parameters such as VPA, Payee name, amount, comment etc. If not possible at least it should not corrupt upi protocol urls

**Comment by mitradranirban** [comment]
Necessary links for consideration 
https://www.npci.org.in/what-we-do/upi/product-overview 
https://en.wikipedia.org/wiki/Unified_Payments_Interface
https://www.mygov.in/digidhan/pages/pdf/sbi/NPCI%20Unified%20Payment%20Interface.pdf

**Comment by talldan** [comment]
@mitradranirban Please could you add some steps to reproduce this issue.

I had a go at testing, and there were no issues with the protocol being replaced.

**Comment by mitradranirban** [comment]
I set url to upi://pay/?pn=... which is converted after saving the page in gutenberg to https://pay/?pn=... however the UPI payment function will only work if the url starts with upi:// as in my vanilla html page
![Screenshot from 2021-12-15 15-22-41](https://user-images.githubusercontent.com/67600799/146168093-68cfabd1-91fa-485c-9b11-7c32820763e2.png)
![Screenshot from 2021-12-15 15-23-31](https://user-images.githubusercontent.com/67600799/146168099-629547d7-0b54-41dd-a48e-a4075a91a1d9.png)
![Screenshot from 2021-12-15 15-41-14](https://user-images.githubusercontent.com/67600799/146168106-9c790499-dd4c-4e01-b334-59c951733750.png)

**Comment by talldan** [comment]
Ok. It looks like you tried the same steps as I did. I'm seeing a different result on a clean installation of WordPress (5.9 beta) with only Gutenberg enabled.

Editor:
<img width="533" alt="Screen Shot 2021-12-16 at 9 29 45 am" src="https://user-images.githubusercontent.com/677833/146291462-4831b5e0-6146-4b3c-b8d5-22df7362a30d.png">

The resultant post:
<img width="546" alt="Screen Shot 2021-12-16 at 9 30 02 am" src="https://user-images.githubusercontent.com/677833/146291503-2ae4f88b-440c-4068-a1a0-748dfa5d0e17.png">

Which version of WordPress and Gutenberg do you have installed? Do you have any plugins installed that might cause an issue?

**Comment by mitradranirban** [comment]
![Screenshot_20211216-073158_Chrome](https://user-images.githubusercontent.com/67600799/146294464-fe84f376-23e6-47ca-86f5-a3bc9e496c5b.jpg)
I am using Wordpress 5.8.2 which is shows is up to date
The details are
`
### wp-core ###

version: 5.8.2
site_language: en_GB
user_language: en_GB
timezone: +05:30
permalink: /%year%/%monthnum%/%postname%/
https_status: true
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 94
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/atiprtgd/public_html/wp
wordpress_size: 50.96 MB (53434996 bytes)
uploads_path: /home/atiprtgd/public_html/wp/wp-content/uploads
uploads_size: 72.95 MB (76490471 bytes)
themes_path: /home/atiprtgd/public_html/wp/wp-content/themes
themes_size: 12.51 MB (13116387 bytes)
plugins_path: /home/atiprtgd/public_html/wp/wp-content/plugins
plugins_size: 76.62 MB (80346806 bytes)
database_size: 42.99 MB (45080275 bytes)
total_size: 256.03 MB (268468935 bytes)

### wp-active-theme ###

name: Twenty Twenty-One (twentytwentyone)
version: 1.4
author: the WordPress team
author_website: https://en-gb.wordpress.org/
parent_theme: none
theme_features: core-block-patterns, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, woocommerce, widgets-block-editor, post-thumbnails, automatic-feed-links, title-tag, post-formats, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, custom-background, editor-color-palette, editor-gradient-presets, responsive-embeds, custom-line-height, experimental-link-color, custom-spacing, custom-units, infinite-scroll, jetpack-geo-location, jetpack-content-options, widgets
theme_path: /home/atiprtgd/public_html/wp/wp-content/themes/twentytwentyone
auto_update: Disabled

### wp-themes-inactive (1) ###

Storefront: version: 3.9.1, author: Automattic, Auto-updates disabled

### wp-plugins-active (19) ###

Advanced Cron Manager: version: 2.4.1, author: BracketSpace, Auto-updates enabled
Bing Webmaster Url Submission: version: 1.0.13, author: Bing Webmaster, Auto-updates disabled
Google Listings and Ads: version: 1.9.0, author: WooCommerce, Auto-updates enabled
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: version: 8.4.365, author: HubSpot, Auto-updates enabled
HubSpot for WooCommerce: version: 1.2.6, author: MakeWebBetter, Auto-updates enabled
Jetpack: version: 10.4, author: Automattic, Auto-updates enabled
Kiasa UPI Payment plugin for WooCommerce: version: 1.2, author: Kiasa, Auto-updates disabled
MailPoet 3 (New): version: 3.75.1, author: MailPoet, Auto-updates enabled
MailPoet 3 Premium (New): version: 3.75.0, author: MailPoet, Auto-updates enabled
Razorpay for WooCommerce: version: 2.8.3, author: Team Razorpay, Auto-updates enabled
Site Kit by Google: version: 1.47.0, author: Google, Auto-updates enabled
Spoki - Chat Buttons and WooCommerce Notifications: version: 2.9.3, author: Reddoak Srl, Auto-updates enabled
Textlocal SMS Notifications: version: 3.0.0, author: Textlocal, Auto-updates disabled
WooCommerce: version: 6.0.0, author: Automattic, Auto-updates enabled
WooCommerce GST: version: 1.3, author: Stark Digital, Auto-updates disabled
Wordpress File Upload: version: 4.16.2, author: Nickolas Bossinas, Auto-updates enabled
WP Crontrol: version: 1.12.0, author: John Blackbourn & crontributors, Auto-updates enabled
WPForms Lite: version: 1.7.1.2, author: WPForms, Auto-updates enabled
WP Mail SMTP: version: 3.2.1, author: WPForms, Auto-updates enabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1650
imagemagick_version: ImageMagick 6.7.2-7 2017-03-23 Q16 http://www.imagemagick.org
imagick_version: 3.4.3
file_uploads: File uploads is turned off
post_max_size: 516M
upload_max_filesize: 512M
max_effective_size: 512 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 16 GB
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 48 MB
	imagick::RESOURCETYPE_MEMORY: 48 MB
	imagick::RESOURCETYPE_THREAD: not available
imagemagick_file_formats: 3FR, A, AAI, AI, ART, ARW, AVI, AVS, B, BGR, BGRA, BMP, BMP2, BMP3, BRF, C, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FITS, FRACTAL, FTS, G, G3, GIF, GIF87, GRADIENT, GRAY, GROUP4, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, ICB, ICO, ICON, INFO, INLINE, IPL, ISOBRL, J2C, JNG, JP2, JPC, JPEG, JPG, JPX, K, K25, KDC, LABEL, M, M2V, M4V, MAC, MAP, MAT, MATTE, MIFF, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NULL, O, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG24, PNG32, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, R, RADIAL-GRADIENT, RAF, RAS, RGB, RGBA, RGBO, RLA, RLE, SCR, SCT, SFW, SGI, SHTML, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UIL, UYVY, VDA, VICAR, VID, VIFF, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, Y, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, BMP, XPM
ghostscript_version: 8.71

### wp-server ###

server_architecture: Linux 4.19.150-76.ELK.el6.x86_64 x86_64
httpd_software: Apache
php_version: 7.4.26 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 512M
php_post_max_size: 516M
curl_version: 7.80.0 OpenSSL/1.1.1l
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.6.41-84.1
client_version: mysqlnd 7.4.26

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/atiprtgd/public_html/wp/wp-content
WP_PLUGIN_DIR: /home/atiprtgd/public_html/wp/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### jetpack ###

site_id: 165273803
ssl_cert: No
time_diff: undefined
version_option: 10.4:1638899666
old_version: 10.3:1635875352
public: Public
master_user: #1 admin
current_user: #1 admin
tokens_set: Blog User
blog_token: YAEQnv6OE$tKmZ15HUS44HmIKQ4HY$I^
user_token: UJ!WrN)N6fk44mVYQu#w20MXIjvaAQNN
version: 10.4
jp_plugin_dir: /home/atiprtgd/public_html/wp/wp-content/plugins/jetpack/
plan: free
protect_header: {"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
full_sync: {"started":"Wed, 07 Apr 2021 04:51:46 +0000","finished":"Wed, 07 Apr 2021 04:52:04 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"1"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[1],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/atipra.in\/wp","siteurl":"https:\/\/atipra.in\/wp","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### wpforms ###

version: 1.7.1.2
lite: Aug 8, 2019 @ 8:08am
upload_dir: Writable
db_tables: wprk_wpforms_tasks_meta
total_forms: 2
total_submissions: 52

### google-site-kit ###

version: 1.47.0
php_version: 7.4.26
wp_version: 5.8.2
reference_url: https://atipra.in/wp
amp_mode: no
site_status: connected-site
user_status: authenticated
verification_status: verified-meta
connected_user_count: 1
active_modules: site-verification, search-console, adsense, analytics, analytics-4, pagespeed-insights, tagmanager
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/adsense.readonly: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
	https://www.googleapis.com/auth/tagmanager.readonly: ✅
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ✅
	googlesitekit_view_dashboard: ✅
	googlesitekit_view_module_details: ✅
	googlesitekit_manage_options: ✅
enabled_features: 
	ideaHubModule: ⭕
	serviceSetupV2: ⭕
	swgModule: ⭕
	userInput: ⭕
	unifiedDashboard: ⭕
search_console_property: https://atipra.in/wp/
adsense_account_id: pub-415•••••••••••••
adsense_client_id: ca-pub-415•••••••••••••
adsense_account_status: approved
adsense_use_snippet: yes
adsense_web_stories_adunit_id: none
analytics_account_id: 6457••••
analytics_property_id: UA-6457••••••
analytics_profile_id: 1044•••••
analytics_use_snippet: yes
analytics_4_property_id: none
analytics_4_web_data_stream_id: none
analytics_4_measurement_id: none
analytics_4_use_snippet: yes
tagmanager_account_id: 6001••••••
tagmanager_container_id: GTM-5ZN••••
tagmanager_amp_container_id: none
tagmanager_use_snippet: yes

### wp_mail_smtp ###

version: 3.2.1
license_key_type: lite
debug: No debug notices found.
db_tables: wprk_wpmailsmtp_tasks_meta, wprk_wpmailsmtp_debug_events

`

**Comment by mitradranirban** [comment]
I installed a fresh version of Wordpress in another domainand found that it is working fine with upi link. SO probably some plugin in my installation is the reason for changing the protocol. Please close this issue now. However my request for inclusion of a dedicated payment link button for upi remains
