### ISSUE TITLE
OK, guys. Back to the drawing board!

### ISSUE THREAD

**Issue by blaasvaer** [WordPress/gutenberg#37405]
### Description

Image size do NOT work in any useful way. If you simply want to add an inline image you have to spend the whole day pulling hair and messing around with obscure settings that do NOT make it easy (actually impossible inside the Gutenberg Editor alone) to simply have an image follow the width of the text and maintain its proportions. Now, HOW could a simple case like that be completely missed by this team?

### Step-by-step reproduction instructions

1. Write some text
2. Insert inline image
3. And watch how the available settings do NOT allow for the scenario above ... which is in no way very special.

### Environment info

Not relevant here ... it's simply about how the Editor is poorly designed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@blaasvaer Could you update the issue title to something more appropriate? Ideally a brief description of the bug. Otherwise readers won't know what it's about when seeing it in the list of issues.

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @blaasvaer hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
