### ISSUE TITLE
[Navigation] The responsive menu contents flow oddly when using the Page List block

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#37413]
I'm seeing menu items flow in an unexpected left-to-right way when a page list block is involved. If the navigation block fills up most or all of the viewport, subsequent individual items float off to the right.

In the GIF below, the "Testing" items are individual pages, and the rest of the content is a single "Page List" block. 

![navigation](https://user-images.githubusercontent.com/1202812/146238685-a8b96481-b4ae-4cf8-8505-77e736e8118d.gif)

(Additionally, there's no bottom padding when this happens)

---

To reproduce: 

1. Add a navigation block.
2. Add a page list block inside.
3. Add additional, single page or link blocks. 
4. Set the responsive setting to be "Always"
5. Preview in the front end. 
6. Make the viewport shorter as shown in the GIF above.

---

Tested with:
Gutenberg Version 12.1.0
WordPress 5.8.2
[emptytheme](https://github.com/WordPress/theme-experiments/tree/master/emptytheme)

**Comment by kjellr** [comment]
cc @jasmussen in case you know what's causing this.

**Comment by jasmussen** [comment]
Huh, that's curious indeed. I'll take a look, thanks for the ticket!
