### ISSUE TITLE
Allow preview breakpoints customization

### ISSUE THREAD

**Issue by zaguiini** [WordPress/gutenberg#37418]
## What problem does this address?

Right now, preview "devices" are not self-explanatory. We see:

- Desktop (full-width);
- Tablet;
- Mobile.

But the user has no idea of the dimensions for each preview device.

## What is your proposed solution?

Add an option to customize the breakpoints for each viewport. We might also display the breakpoints in a lighter gray color right next to its name so it's at least clear which dimensions are we talking about.

**Comment by skorasaurus** [comment]
Thanks for reporting; 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/21235. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
