### ISSUE TITLE
Improve feedback on impossible actions

### ISSUE THREAD

**Issue by zaguiini** [WordPress/gutenberg#37420]
## What problem does this address?

Sometimes the user is attempting to perform an impossible action (e.g. trying to add two blocks that can't live together, or trying to nest un-nestable blocks) and there's no feedback at all that the action cannot be done.

That happens on both list view and the editor itself.

## What is your proposed solution?

- Change the cursor to `not-allowed`;
- Change the color of the drop space from blue to red.

**Comment by talldan** [comment]
@zaguiini Is this for drag and drop? If so, I think there's another request for such a feature - https://github.com/WordPress/gutenberg/issues/24174, and this can probably be closed as a duplicate.

**Comment by zaguiini** [comment]
Yep @talldan looks like a duplicate. Closing this one.
