### ISSUE TITLE
Selectively change font size inside Paragraph

### ISSUE THREAD

**Issue by zaguiini** [WordPress/gutenberg#37421]
## What problem does this address?

Allow font size change by selecting a range of already existing text:

![image](https://user-images.githubusercontent.com/26530524/146255199-e05285f0-71c4-4c13-9b36-af3d3b481c46.png)

Right now, changing the font size in the block settings changes the whole block's text size, not only the selected area.

## What is your proposed solution?

Split the selected range into multiple `Paragraph`s, one with the desired font size and the others with the current size.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/2518 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
