### ISSUE TITLE
Gutenberg Pattern Previews and Style Variant Previews broken when Grammarly Browser Extension Enabled

### ISSUE THREAD

**Issue by althe3rd** [WordPress/gutenberg#37423]
### Description

When editing a post/page the Gutenberg pattern previews and style variant previews that normally appear in a small iframe are broken when the Grammarly Browser Extension is enabled.

**Versions**
WordPress: 5.8.2
Chrome: Version 96.0.4664.110
Grammarly for Chrome Extension: 14.1042.0

With Grammarly Extension Enabled
![Screen Shot 2021-12-15 at 2 38 10 PM](https://user-images.githubusercontent.com/24361/146261408-aaff0214-ece3-4bc1-926e-966b8d2bedf3.png)

With Grammarly Extension Disabled
![Screen Shot 2021-12-15 at 2 38 46 PM](https://user-images.githubusercontent.com/24361/146261512-bdc2f7b9-cb99-4e69-a96e-4d41f331fb05.png)

I don't know if the grammarly extension is doing something it shouldn't or if gutenberg can disregard the grammarly extension when showing the pattern or style variant previews. But given the popularity of Grammarly and WordPress I think persuing some sort of solution here is worthwhile no matter where you place the responsibility of this issue.

### Step-by-step reproduction instructions

1. Install/Enable the Grammarly for Chrome browser extension
2. Open any WordPress instance and create a new page (or edit an existing one)
3. Attempt to use a block pattern by pressing the add block button and view then in the left hand sidebar or edit an existing block that contains a style variant in its properties on the right hand side. Previews of each should be missing or if they appear at all it will be intermitent and rare.

### Screenshots, screen recording, code snippet

With Grammarly Extension Enabled
![Screen Shot 2021-12-15 at 2 38 10 PM](https://user-images.githubusercontent.com/24361/146261408-aaff0214-ece3-4bc1-926e-966b8d2bedf3.png)

With Grammarly Extension Disabled
![Screen Shot 2021-12-15 at 2 38 46 PM](https://user-images.githubusercontent.com/24361/146261512-bdc2f7b9-cb99-4e69-a96e-4d41f331fb05.png)

### Environment info

**Versions**
OS Mac OS Monterey 12.0.1
WordPress: 5.8.2
Chrome: Version 96.0.4664.110
Grammarly for Chrome Extension: 14.1042.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by althe3rd** [comment]
I have also filed this bug with Grammarly as well hoping that one or the other party can take some action on getting this resolved. Many of our editors utilize grammarly in their day to day work.

**Comment by althe3rd** [comment]
This is looking more and more like a issue Gutenberg will need to address rather than the extension makers. Other extensions that also inject markup into the DOM seem to also cause a similar effect. I am testing other extensions and will report on those as they are evaluated.

**Comment by glendaviesnz** [comment]
Thanks for reporting this @althe3rd. I wasn't able to replicate it on the latest Gutenberg trunk on either WP 5.8.2 or 5.9, with the same versions of Chrome and Grammarly that you used:
![grammerly](https://user-images.githubusercontent.com/3629020/146307102-110c15ef-beaa-4761-b690-f225890fad0d.gif)

There were intermittent display issues if I ran WP 5.8.2 without the Gutenberg plugin. Are you in a position to try with the Gutenberg 12.1 plugin enabled and see if you still see this issue?

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg, WordPress, and Grammarly. Therefore, I am going to close this issue. If anyone is able to replicate in the future, please feel free to reopen with additional information.
