### ISSUE TITLE
In the template part list, there are text strings that use "template" instead of "template part"

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37439]
### Description

In the Appearance > Editor (beta) > Template Parts list:
- The heading above the list says "Template" instead of "Template part"
- The delete action says "delete template" instead of "delete template part"

### Step-by-step reproduction instructions

1. Activate a theme with support for fill site editing
2. Go to Appearance > Editor (beta) > Template Parts
3. Create a new custom template part
4. Click on the action menu for the user-created template part and see the text label for deleting the part.

### Screenshots, screen recording, code snippet

![The template part list in the site editor uses incorrect text strings](https://user-images.githubusercontent.com/7422055/146322162-c17c72a0-9053-4ce5-8a3d-582be4f37b49.png)

### Environment info

WordPress 5.9.0 Beta 3
With or without Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
@jameskoster Do you think we should change this simply to a "Delete"?

**Comment by jameskoster** [comment]
@Mamaduka yes I think that makes sense 👍
