### ISSUE TITLE
If I have an already created "Image Box Block" I cannot select the image after the first time. I also cannot make the "whole Image box block" clickable.

### ISSUE THREAD

**Issue by Darchorse64** [WordPress/gutenberg#37432]
If I have an already created "Image Box Block" I cannot select the image after the first time. I also cannot make the "whole Image box block" clickable.

It should be as simple as selecting the image block block and selecting from a drop down menu an "add URL" or something like that.

_Originally posted by @Darchorse64 in https://github.com/WordPress/gutenberg/issues/37431#issuecomment-995359144_

**Comment by talldan** [comment]
@Darchorse64 Would you be able to clarify what you mean by Image Box Block? That isn't something provided by the Gutenberg plugin. It might be that you have another plugin installed that adds this block. If so, I'd recommend reaching out to that plugin developer.

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @Darchorse64 hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
