### ISSUE TITLE
Theme color palette not showing colors with conflicting slug in default color palette

### ISSUE THREAD

**Issue by sagarnasit** [WordPress/gutenberg#37449]
### Description

Two different color palettes are shown on the editor, one with the default color palette of core and another with the theme's color palette set via theme.json.

The problem occurs when the theme color palette includes the same color slugs as the default color palette options. In this case, the theme color palette should take precedence over the default color palette of the same slug. The same thing applies to CSS color variables, the default color variable overrides the theme's color variable.

Colors with conflicting slugs do not appear on the color palette even with the `defaultPalette` setting being disabled.

## Current behavior
- Theme color palette does not show colors that conflict with default color palette slugs.
- CSS variable of default color palettes overrides the theme's color palette variables.

## Expected behavior
- Theme color palette should take precedence over the default color palette for the conflicting slug.
- Theme's color should override the CSS variable with the conflicting slug of the default color palette.

### Step-by-step reproduction instructions

1. Create a theme color palette with the color slug same as the default color palette.

```json
"palette": [
	  {
	      "slug": "black",
	      "color": "#1D1D1D",
	      "name": "Black"
	  },
	  {
	      "slug": "white",
	      "color": "#FFFFFF",
	      "name": "White"
	  },
	 {
            "slug": "primary",
            "color": "#DB5D5D",
            "name": "Primary"
      },
]
```

White and Black color has the conflicting slug from the default color palette.

2. Open an editor and look for a block that supports the color palette. No `black` and `white` color options are available under the theme color palette.
<img width="277" alt="image" src="https://user-images.githubusercontent.com/25276905/146354485-6fe62af0-5050-448c-8ddc-3ac13c3c476b.png">

3. Open frontend for CSS variable value. Black color CSS variables is overridden by default color palette's black color. 
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/25276905/146355038-0d30487d-faca-48fb-8640-a0462e03fbd2.png">

### Environment info

- WordPress: 5.8.2
- Gutenberg: 12.1.0
- Theme: Custom block theme
- Browser: Version 98.0.4755.0 (Official Build) canary (x86_64)
- OS: Mac OS Catalina

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by chthonic-ds** [comment]
See https://github.com/WordPress/gutenberg/issues/36772 and https://github.com/WordPress/gutenberg/pull/37008 for how this is being managed in WP 5.9.

**Comment by ndiego** [comment]
Yes, this will be resolved in 5.9 if `defaultPalette` is set to `false` in theme.json. Therefore, I believe this issue can be closed.

**Comment by markhowellsmead** [comment]
This is still an issue in 5.9, whether or not `defaultPalette` is `true`. White and black are never displayed in the Theme palette.

**Comment by sagarnasit** [comment]
Conflicting colors are not displayed on the color palette, but the CSS variables generated on the frontend are using the theme's color palette values when `defaultPalette` is `false`.

**Comment by chthonic-ds** [comment]
Using 5.9 (Gutenberg is not active), I see "white" and "black" displayed correctly in the theme palette.

Theme palette:

![37449-theme-core-colour-slugs](https://user-images.githubusercontent.com/29587253/152028174-019ac53a-6097-45ce-8e39-d177cc96f6f0.gif)

theme.json:

![image](https://user-images.githubusercontent.com/29587253/152028527-e99d8741-00ac-4940-a40a-685012430d5b.png)

**Comment by sagarnasit** [comment]
Works as expected after updating the Gutenberg plugin version. Closing the issue.

**Comment by markhowellsmead** [comment]
Confirmed in 5.9 without the plugin active and in a clean install. With `"defaultPalette": false`, `white` and `black` set in the theme palette are correctly shown. The issue must lie in my custom theme.
