### ISSUE TITLE
Use the same modal for creating new template parts in the editor and the template part list

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37440]
### Description

When you create a new template part in the site or template editor you can only add a name. To add an area, you must go to the Advanced section in the block settings sidebar.
And when you create a new template part in the template part list in the site editor, you can add a name and choose the area.
The help text also differs.

I think the larger modal with the area selection should also be used in the site- and template editors.

### Step-by-step reproduction instructions

1. Activate a theme with support for full site editing or template editing
2. Open the template part list in Appearance > Editor (beta), and select the Add new button to create a new template part.
3. Now go to the template editor via the block editor, or to the site editor,  and create a new template part, and compare the experience.

### Screenshots, screen recording, code snippet

In the editors, replace
![template-part-block-name-new-part](https://user-images.githubusercontent.com/7422055/146329616-b0391ccc-decf-4c3d-8658-15b6528568d6.png)

With 
![template-part-block-site-editor-create-new](https://user-images.githubusercontent.com/7422055/146329583-2b48cc2c-66dd-4d33-9267-ab2ab0e18f8d.png)

### Environment info

Gutenberg trunk,
WordPress 5.9.0 beta 3 via the beta tester plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by carolinan** [comment]
@jameskoster Also, looking at the screenshots above -are two cancel / close buttons needed here? I have not noticed it before.

**Comment by jameskoster** [comment]
I think this could be a good enhancement, but there is a lot to consider. For example how can we make better use of patterns as a part of the creation flow for headers and footers? And how can we streamline the insertion flow for existing template parts? Relying on the monolithic "Template part" block for all these flows doesn't seem very efficient or intuitive.

Just to connect some dots – I explored some concepts around these ideas in:

* https://github.com/WordPress/gutenberg/issues/31746
* https://github.com/WordPress/gutenberg/issues/31747
* https://github.com/WordPress/gutenberg/issues/31748

I would love to hear any feedback on those issues.

> are two cancel / close buttons needed here? I have not noticed it before.

Probably not :)
