### ISSUE TITLE
Add `comment-form` and `comment-list` to default `html5` theme support (backport from WordPress Core for parity)

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#37464]
### Description

Follow-up to PR #35593.

 In WordPress Core's [changeset 52369](https://core.trac.wordpress.org/changeset/52369), two additional `html5` theme supports were added: `'comment-form'` and `'comment-list'`. This issue seeks to backport the changeset from Core to Gutenberg to resync for parity.

The difference between Gutenberg and Core causes differences in Twenty Twenty-Two's comm ents markup output and visual styling. See Core Trac ticket https://core.trac.wordpress.org/ticket/54625 for more details.

To resync with Core by adding the 2 additional supports in the `lib/compat/wordpress-5.9/default-theme-support.php file https://github.com/WordPress/gutenberg/blob/7cbba2646a522738fd95894db8240e4d3d5ac1d3/lib/compat/wordpress-5.9/default-theme-supports.php#L12-L18

### Step-by-step reproduction instructions

NA

### Screenshots, screen recording, code snippet

NA

### Environment info

NA

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kjellr** [comment]
Please note that in addition to adding those two supports, there are some visual issues that will need to be fixed. 

Gutenberg (Current)|Core (Current)
---|---
<img width="639" alt="Screen Shot 2021-12-16 at 1 53 09 PM" src="https://user-images.githubusercontent.com/1202812/146431490-5e9c5438-ce7c-43d8-b62d-9b100199331a.png">|<img width="640" alt="Screen Shot 2021-12-16 at 1 53 29 PM" src="https://user-images.githubusercontent.com/1202812/146431493-dded9115-9c08-4e70-a106-c40351427915.png">


The current front-end appearance of the comments form as provided by is solid. We should continue to sync up with that once Gutenberg is using the new markup. And then we should backport those style fixes to core.

**Comment by kjellr** [comment]
Adding to the must-haves because of the indentation issue demonstrated above.

**Comment by glendaviesnz** [comment]
Possible PR for this at https://github.com/WordPress/gutenberg/pull/37536
