### ISSUE TITLE
Settings buttons animation inconsistent

### ISSUE THREAD

**Issue by davidsword** [WordPress/gutenberg#3746]
wp 4.9.1, gb 1.8.1, via Safari 11.0.1

![fancypancyanimation](https://user-images.githubusercontent.com/1996370/33462101-793ade46-d5ea-11e7-90cc-baae8e69200e.gif)

no fancy setting rotation on top right, inconsistent behaviour for same visual button.

**Comment by jasmussen** [comment]
Good ticket. I would agree there needs to be consistency here, though personally I feel like the fix would be to _not rotate the block ellipsis_. They are both icon buttons and should behave like other icon buttons.

**Comment by DevinWalker** [comment]
I've confirmed the PR above fixed this:

![2017-12-03_11-19-55](https://user-images.githubusercontent.com/1571635/33527948-dc458c62-d81e-11e7-87b7-db9efc0a96d7.gif)

This issue can be closed out.

**Comment by jasmussen** [comment]
Thanks Devin and @Rahmon!
