### ISSUE TITLE
disable block theme support will not disable block template.

### ISSUE THREAD

**Issue by cloudinstone** [WordPress/gutenberg#37461]
### Description

for example, I create a block theme 'test' and did some 'edit site' things to my website, then I decided to disable block template by remove 'block-template' and 'block-template-parts' folder. but it will not disable block template, block templates will still using by some archive pages.

why not just rename theme name? because I want to create a theme for users have choice to enable block supports or not.

### Step-by-step reproduction instructions

above

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi!
**If** your theme includes a theme.json file, then removing the folders you mentioned will not disable template editing.
[Template editing is activated with theme.json. ](https://make.wordpress.org/core/2021/06/25/introducing-theme-json-in-wordpress-5-8/) To disable it you need to remove the theme support, not only the folders.

`remove_theme_support( 'block-templates' );`

**Comment by jordesign** [comment]
Based on the comment above - it sounds like the behaviour is expected, so I'm closing the issue.
