### ISSUE TITLE
Previewing single post changes frontend doesn't work on block based themes

### ISSUE THREAD

**Issue by walbo** [WordPress/gutenberg#37463]
### Description

The preview functionality on block based themes doesn't work.

Inspecting on the editor page console, I do see a successful autosave fire right when the new tab opens, but somehow the preview isn't using the autosave data.

The preview works fine on non block bases themes (tested twentytwentyone).

Related core ticket: https://core.trac.wordpress.org/ticket/54635

### Step-by-step reproduction instructions

1. Activate a block based theme. Ex twentytwentytwo
2. Make some changes to a post/page (without saving)
3. Click on Preview
4. Click on Preview in new tab
5. Confirm that you changes isn't in the preview

### Environment info

Same bug in both WordPress 5.9 beta 3 (without Gutenberg) and in Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by adamsilverstein** [comment]
I verified the same problem with another block theme ("Alara") to verify the issue wasn't twentytwentytwo specific.

**Comment by adamsilverstein** [comment]
I spent some time digging into this. I found that in this check https://github.com/WordPress/wordpress-develop/blob/954e9c153fe9d1b4f74d76bab9dd5175fd36cebc/src/wp-includes/class-wp-query.php#L3205 
The call to `current_user_can` winds up breaking the review (even though it returns true). removing that check, the preview works fine. Still not sure why, these are my findings so far.
