### ISSUE TITLE
Add documentation describing how plugins can add templates

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#37476]
Related #37401, #36597

## What problem does this address?
It was mentioned in https://github.com/WordPress/gutenberg/issues/36597#issuecomment-973992841 that plugins can add templates via a filter. Setting some template fields (setting the `source` to 'plugin', and `theme` to the plugin slug) helps to indicate where the template came from.

Support for this has since been added to the template list interface.

As mentioned on #37401 the process for plugins adding templates isn't necessarily all that clear as the `theme` field doesn't seem obvious, but that's hard to change now due to backwards compatibility.

There's a risk if this isn't documented well that plugins will end up using inconsistent techniques for providing templates.

cc @Aljullu @tjcafferkey 

## What is your proposed solution?
Add some documentation and/or a tutorial for this process

**Comment by Mamaduka** [comment]
I am removing this issue from the 5.9 board. It's tracked in the documentation project.

**Comment by mburridge** [comment]
> Add some documentation and/or a tutorial for this process

Where do you think this documentation / tutorial should live?

- [ ] [Block Editor Handbook](https://developer.wordpress.org/block-editor/)
- [ ] [Plugin Handbook](https://developer.wordpress.org/plugins/)
- [ ] [Theme Handbook](https://developer.wordpress.org/themes/)

**Comment by talldan** [comment]
Probably in the plugin handbook.

**Comment by mburridge** [comment]
Thanks @talldan. In that case, if it's not something for the [Block Editor Handbook](https://developer.wordpress.org/block-editor/), do you think we should close this and open a new issue over in [Documentation-Issue-Tracker](https://github.com/WordPress/Documentation-Issue-Tracker)?

**Comment by annezazu** [comment]
@ndiego noting for you as you work on the block editor handbook overhaul. Can you follow up on this/ensure it's in the right place?

**Comment by talldan** [comment]
Closing this in favour of #61577, which should add a much easier API and docs.
