### ISSUE TITLE
Block API: Block splitting, insert after

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#375]
Related: #374
Slack discussion: https://wordpress.slack.com/archives/C02QB2JS7/p1491308809656882 (cc @spocke)

With current block APIs, we might be able to support this by passing additional callbacks to the `edit` render handler, e.g. `insertBlockAfter`.

Proposal:

```
insertBlockAfter( block: ?WPBlock )
```

- If passed `null`, inserts empty block after currently selected block
- If passed block, appends block after currently selected block
  - How does a block implementation know how to create a block node? Should we overload this to support passing e.g. markup string?

In all cases, moves cursor focus to start of newly inserted block.

**Comment by mtias** [comment]
In the context of the `inserter`, I was thinking we may want to have an action for insert block that is capable of handling any insertion position within the list of blocks in state.

**Comment by youknowriad** [comment]
Closing since this is already done
