### ISSUE TITLE
Color select component backdrop render and animation opportunities

### ISSUE THREAD

**Issue by KevinBatdorf** [WordPress/gutenberg#37506]
### Description

The rendering on the backdrop is inconsistent when rendering inside an animating parent. The current implementation has a delay of 100ms but it's not very reliable, and is also dependent on the parent animating for 100ms.

### Step-by-step reproduction instructions

1. Add a group block
2. Open the color settings
3. Press Background color
4. Toggle gradient and solid items

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1478421/146626852-1d982150-080d-48bb-980d-08968087a887.mov

### Environment info

- Gutenberg 12.2.0-rc.1
- TT1 Blocks
- Chrome
- Mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by KevinBatdorf** [comment]
Will submit a PR shortly

**Comment by ciampo** [comment]
Reopening — see details in #40021

**Comment by ciampo** [comment]
Opened #40107 with new tentative fix

**Comment by ciampo** [comment]
New approach with `framer-motion`'s shared animation layout in #40276

**Comment by stokesman** [comment]
I believe this should have closed with #50278.
