### ISSUE TITLE
Code block: editor styles override custom text colors

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#37511]
### Description

_Originally reported in [Trac #54644](https://core.trac.wordpress.org/ticket/54644)_

Custom color options do not apply when using the block editor's theme styles, either within the editor or on the front end. The color classes apply to the `pre` element, but the `code` element can have text color settings from the themes.scss (and/or the chosen theme).

### Step-by-step reproduction instructions

1. Activate Twenty Twenty-Two, Twenty Twenty-One, or another theme that uses the editor's theme styles.
2. Create a new post.
3. Add a Code block and insert some content.
4. Go to the block's color settings in the sidebar, and try changing the text color.
5. Create a Group block and set a text color there.
6. Inside the Group, add a Code block and insert some content.

The text color does not match the setting. (Background color changes as expected.)

### Screenshots, screen recording, code snippet

Alan's attempt to set a custom text color in Twenty Twenty-Two in the editor:

![color setting](https://core.trac.wordpress.org/raw-attachment/ticket/54644/code%20colour.gif)

The default color in theme.scss is a dark gray:
https://github.com/WordPress/gutenberg/blob/665f4de2f3c5729f04c177482cadf4bbb5ed8bba/packages/block-library/src/code/theme.scss#L3

Twenty Twenty-One has a style that can also override the custom color:

![Twenty Twenty-One front-end styles](https://user-images.githubusercontent.com/17100257/146663261-037ac96c-5599-47f8-998e-f538c6eec296.png)

### Environment info

WP version : 5.9-beta3
Themes: Twenty Twenty-Two, Twenty Twenty-One, Twenty Nineteen, Twenty Seventeen (setting text color works in Twenty Twenty)
Plugins Installed: None

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sabernhardt** [comment]
## Options 

### 1. Remove the text color from editor styles

This is the simplest edit, but a text color apparently has been in the codebase since before the block editor became the default in 2018.

### 2. Add a simple inherit style

This seems to fix the color in Twenty Seventeen, Twenty Nineteen and Twenty Twenty-Two. Twenty Twenty-One would still need a separate change.

```
.has-text-color code {
    color: inherit;
}
```

### 3. Add a more elaborate style

This could fix Twenty Twenty-One (and perhaps other themes that do the same), in addition to Twenty Seventeen, Twenty Nineteen and Twenty Twenty-Two.

```
.has-text-color .wp-block-code code,
.wp-block-code.has-text-color code {
    color: inherit;
}
```

**Comment by ank1traj** [comment]
Testing Environment - 

- WordPress version - 5.9 beta-4
- OS: MacOS Monterey 12.0.1
- Browser used - Version 96.0.4664.110 (Official Build) (arm64)

This issue is still not fixed.

**Comment by sabernhardt** [comment]
I think I should recommend the first option: removing the text color from the editor's "theme" CSS file. The `code` element assigns a text color without a contrasting background color. Even though removing the line would change the color on many sites, those sites _should_ fall back to the same color as surrounding content (or use their own `code` element styling).

Twenty Twenty-One's Dark Mode overrides the color on the front end, but the editor still shows the dark gray. Other themes have needed to override this style for their dark backgrounds, too.

**Comment by carolinan** [comment]
Unless I misunderstood something, this was fixed in https://github.com/WordPress/gutenberg/pull/37816.

**Comment by sabernhardt** [comment]
Ah, yes, that should fix it. Thanks!
