### ISSUE TITLE
@wordpress/prettier-config 's jsxBracketSameLine config is now deprecated

### ISSUE THREAD

**Issue by waviaei** [WordPress/gutenberg#37516]
### Description

When setting up our project's esllint using @wordpress/eslint-plugin, specified in `.eslintrc` as per:
`"extends": [ "plugin:@wordpress/eslint-plugin/recommended" ],`

I get this error notice `jsxBracketSameLine is deprecated.`

I found that this error notice is Prettier related, and comes from [this line in @wordpress/prettier-config](https://github.com/WordPress/gutenberg/blob/037fcc79749b186e01ba34f3104971aebc3288dc/packages/prettier-config/lib/index.js#L21)

This change is from Prettier 2.4
https://prettier.io/blog/2021/09/09/2.4.0.html

> This release renames the jsxBracketSameLine option to bracketSameLine, which supports HTML, Vue, and Angular in addition to JSX. The old name has been deprecated.

@wordpress/prettier-config's config setting needs to be updated

### Step-by-step reproduction instructions

Here, we are using @wordpress/eslint-plugin as standalone -- not as part of @wordpress/scripts

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
I opened #37607 to start making the official proposal to switch to the original Prettier in the most recent 2.5 version. Otherwise, we can't apply the changes proposed because we use a fork that is pinned to Prettier 2.2. I included the fix in #37607.

**Comment by waviaei** [comment]
@gziolo Thanks for the explanation. That explains why seeing the error when `@wordpress/eslint-plugin` is used separately from `@wordpress/scripts`. And yes, I agree, I think it will be better going forward, to move back to using the original Prettier .
