### ISSUE TITLE
Pasting list items that begin with a character and a dot --these characters are missing

### ISSUE THREAD

**Issue by JingshanDu** [WordPress/gutenberg#37518]
### Description

We have a numbered or unnumbered list in Word or some other word processing software, which contain items like this:

- E. xxxxxxxxxxxx

The first character is different in each item and it does not represent a number.

Expected behavior: when copy-pasting this text to WordPress, a list item should be generated with the following content:
- E. xxxxxxxxxxxx

Current behavior: "E." is missing, and the following content was created as a list item in WordPress editor:
- xxxxxxxxxxxx

Scope: This happens in both the classic and block paragraphs.

### Step-by-step reproduction instructions

1. Copy a list item in Word or some other word processing program
2. Paste in the Editor

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bdurette** [comment]
The behavior here seems highly dependent on the Copy source. Using Chrome for Mac. 

**Source: Google Docs**

![Screen Shot 2021-12-20 at 9 25 04 AM](https://user-images.githubusercontent.com/403387/146791275-1c24ee87-3c37-411b-95eb-32742926dfef.png)

**Source: Microsoft Word**

![Screen Shot 2021-12-20 at 9 25 55 AM](https://user-images.githubusercontent.com/403387/146791369-252e51fc-3be1-4ef3-ba8d-7b8e2631b4b0.png)

**Source: Slack**

![Screen Shot 2021-12-20 at 9 26 50 AM](https://user-images.githubusercontent.com/403387/146791537-5af11a79-d337-4b70-a908-2cf4e9d09315.png)

In no case do I find the stripping of the letter. Can you add some detail about the specific source and targets: OS, Software Version, Browser, Version, etc.?

**Comment by JingshanDu** [comment]
The problem has been isolated --it's associated with a plugin enabled by the service provider. After disabling that particular one, the problem is gone. I think this issue can be closed.
