### ISSUE TITLE
Color circles should not use gray

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#37522]
The color circles in global styles, palettes, and items should not be using static gray as borders but a shade of the main color. If we cannot use opacity because of how it's built we should generate it ourselves using the current color:

![image](https://user-images.githubusercontent.com/548849/146756941-961ab94a-bf67-4e48-b9da-7b0e1c846892.png)

**Comment by richtabor** [comment]
I used the same mechanism we use elsewhere for colors in https://github.com/WordPress/gutenberg/pull/37500.

**Comment by mtias** [comment]
Sweet!

**Comment by aristath** [comment]
Done in https://github.com/WordPress/gutenberg/pull/37500 👍
