### ISSUE TITLE
Missing block inserter when creating template parts from the template part list in the site editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37524]
### Description

If I activate a block theme, and go to Appearance > Editor (beta) > Template parts, and select "Add New",
the template part opens in isolation and there is no block inserter in the editor "canvas".
 
Eventually, I figured out that I could still click on the blue + icon in the top toolbar, and insert a pattern, but the experience was confusing.

### Step-by-step reproduction instructions

1. Activate a block theme, for example Twenty Twenty Two
2. Go to Appearance > Editor (beta) 
3. Select the Template part list in the navigation sidebar
4. Select "add new", select an area and name for your template part
5. On the next screen, see that the background of the editor is grey, not white, and that there is no inserter.

### Screenshots, screen recording, code snippet

![Create new template part](https://user-images.githubusercontent.com/7422055/146767959-79427cf3-a99f-419b-b735-09284ed9ad5a.png)

### Environment info

WordPress 5.9-beta3-52379-src ([via wordpress-develop](https://github.com/WordPress/wordpress-develop/))
With and wihout Gutenberg Trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I think this is regression after #37213. Here's a related discussion - https://github.com/WordPress/gutenberg/pull/37213/files#r764700120.

**Comment by westnz** [comment]
I have experienced the same issue

https://user-images.githubusercontent.com/89751452/149445164-cac8c6ce-7d66-4f9d-a5fc-8bdc361b13b5.mov
