### ISSUE TITLE
Themes: Consistent header space

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#37529]
## What problem does this address?
In many themes we want to have a space between the header template, and the rest of the content. It's important that this amount of space is consistent between all templates. We have tried several ways of achieving this but all are compromises:

1. Use a spacer block. We can just add a spacer block to the templates. The problem with this is that if a user modifies one template then they might not remember to update the others, and the spacing would be different on each template.
2. Add a spacer block to the header. By adding the spacer block to the header itself we ensure that the space is consistent between templates. However in lots of themes we also want to have a "header and footer only" template. In these templates we want to reuse the header from other templates, but without the space. This could be achieved by having two copies of the header block, but then users would have to maintain two copies of that template.
3. Create a `header-spacer` template. This template enables us to share the header template across all templates, without enforcing a large gap on templates that only want to use the header. The downside of this approach is it adds an additioanl template area to all templates which makes the editing experience sub-optimal.

**Comment by mtias** [comment]
> Add a spacer block to the header.

This seems the obvious one to me. Not sure I understand what a "header and footer only" template means or why it's needed.

**Comment by scruffian** [comment]
I did a bit more digging here. This root of the problem is that we are trying to reuse the same template parts across multiple themes. The header spacer template part enables us to configure the header spacer across many child themes without duplicating the header code. Unfortunately this comes at a cost of a suboptimal experience for users. If we want to share code across themes we need to create our own tools to do this, not rely on parent/child inheritance.
