### ISSUE TITLE
Improve embed flow

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#37523]
The current visual flow for embeds is quite unrefined. When there's an attempt at an embed we render a big white box that generally looks unstyled. The box then might collapse into a smaller thing if 1) embed didn't work 2) final embed is smaller than the box.

<img width="532" alt="Screenshot 2021-12-20 at 11 57 28" src="https://user-images.githubusercontent.com/548849/146759137-95016973-e04e-489c-a0e6-3291b5d683ed.png">

It seems to me we could do something more straightforward, like just showing the spinner in the middle or beginning of the line.

Related https://github.com/WordPress/gutenberg/issues/36725

**Comment by jameskoster** [comment]
It would be nice to eliminate the flash-of-unstyled embed that occurs as well. For example when you embed a tweet you will see the following for a split-second, before the full embed loads:

<img width="795" alt="Screenshot 2021-12-21 at 10 15 39" src="https://user-images.githubusercontent.com/846565/146912927-4655466d-65cb-4e6d-98b8-42b6d16ad972.png">

Ideally the loading state should persist until the embed UI is fully loaded.
