### ISSUE TITLE
Add missing `Gutenberg_Block_Template::$area` and `Gutenberg_Block_Template::$post_types` properties (Resync with WordPress Core)

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#37533]
### Description

The `$post_types` and `$area` properties are being assigned to/from the `_build_block_template_result_from_file()` and `_build_block_template_result_from_post()` functions, which were introduced in WP 5.9; however, these 2 new properties do not exist in the `Gutenberg_Block_Template` class.

[WordPress Core Trac 54670](https://core.trac.wordpress.org/ticket/54670) was opened and its PR https://github.com/WordPress/wordpress-develop/pull/2072 were opened to add these missing properties to `WP_Block_Template`.

I'm opening this issue to backport the Core changes, i.e. to resync Gutenberg with Core.

BTW Dynamic properties will be deprecated in PHP 8.2.

### Step-by-step reproduction instructions

na

### Screenshots, screen recording, code snippet

na

### Environment info

na

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by karmatosed** [comment]
@hellofromtonya as I don't see a label for backport that way adding this one, but perhaps we need that label?

**Comment by hellofromtonya** [comment]
@karmatosed I think adding a new label to capture backports from Core to Gutenberg is a great idea 💡
