### ISSUE TITLE
When a block is deleted, following blocks loose formatting.

### ISSUE THREAD

**Issue by laricastime** [WordPress/gutenberg#37534]
### Description

Hey guys.

My company (Olhar Digital) uses WP as a CMS and recently I've been stressed with a feature of the platform that I consider a bug.

I have block 1, block 2 and block 3. When I delete (with 'delete', not 'backspace') text between block 1 and block 2, the third block also goes up and it loses formatting. I've been told this is the pattern, but I can't believe it.

I recorded my screen so you can watch what I mean: https://www.youtube.com/watch?v=g2VcTYkUnh4.

I hope someone can help fix this. 

Thanks in advance for your hard work. 

Lay

### Step-by-step reproduction instructions

Write two paragraph blocks;
Write one title block;
Now use the delete button to delete text between the first and the second paragraph;
Pay attention to the third block (the title one) and see it will goes up and looses formating;

### Screenshots, screen recording, code snippet

https://www.youtube.com/watch?v=g2VcTYkUnh4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I can reproduce this with Gutenberg trunk and WordPress 5.9-beta3-52379-src. (No other plugins installed)

**Comment by Mamaduka** [comment]
I can also reproduce the issue.

## Screencast
https://user-images.githubusercontent.com/240569/147730579-2c5c1713-46aa-40a8-9a0b-3ecbe9d1ceac.mp4
