### ISSUE TITLE
Global styles sidebar: Post terms, post navigation, and query title are missing icons

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37541]
### Description

In the global styles sidebar in the site editor, these blocks are missing their custom icons. Instead, the "lego brick" is shown:
Post terms, post navigation, and query title.

### Step-by-step reproduction instructions

1. Activate a theme with support for full site editing
2. Go to Appearance > Editor
3. Open styles
4. Select Blocks
5. In the list of blocks, see the icons.

### Screenshots, screen recording, code snippet

![list of block names and icons ](https://user-images.githubusercontent.com/7422055/146863209-a975ce28-0cf5-42c8-9abf-d345e7ee6f31.png)

### Environment info

WordPress 5.9-beta3-52379-src
With and without Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Perhaps the real question is if these blocks should be visible here or if their variations should be used?
(Archive title, next/previous, post categories, post tags)

**Comment by carolinan** [comment]
Do you have any thoughts on this issue @jasmussen?

**Comment by jasmussen** [comment]
Good ticket, thank you. It seems like the _mini-icon with two rows of text below_ pattern used for the other related icons (post title, post excerpt etc) might work well here also. @javierarce since you created that excellent submenu icon yesterday, is this something you'd like to take a stab at? Otherwise I have some bandwidth to tackle this next week.

**Comment by javierarce** [comment]
@jasmussen please, go for it if you have the time, I'm a bit swamped with work right now.

**Comment by jasmussen** [comment]
Awesome, I'll take a stab, no worries 👌

**Comment by jasmussen** [comment]
Took a stab in #38521. Note I wasn't able to find the "Post Navigation Link" to insert, and it's unclear to me what it does. Can we just use the existing Pagination icon for it?
