### ISSUE TITLE
Comments Pagination Block: Unify the markup on all pagination blocks rendering on PHP

### ISSUE THREAD

**Issue by cbravobernal** [WordPress/gutenberg#37561]
## What problem does this address?

There is a different link markup used in the Previous Comments and in the number 1 from the Pagination Numbers block. 

## What is your proposed solution?

Previous Comments is using a different function to retrieve the link.
`paginate_links()` function is used on `paginate_comments_links()`on Pagination Numbers Block
`get_comments_pagenum_link()` function is used on `get_previous_comments_link()` on `Pagination Previous Block` and also on `get_next_comments_link()` and `Pagination Next Block`.

Could be any way to use the same structure for all pagination links?

**Comment by gziolo** [comment]
## Issue 1

Settings used:

<img width="828" alt="Screenshot 2022-02-17 at 11 05 35" src="https://user-images.githubusercontent.com/699132/154453210-659cbdee-467a-445c-88fb-d4634f85e888.png">

Old Post Comments block and Newer Comments link:

<img width="662" alt="Screenshot 2022-02-17 at 11 04 42" src="https://user-images.githubusercontent.com/699132/154453523-bd6568d3-5265-41a5-bfd2-36adf5c800c7.png">

New Comments Query Loop block and Newer Comments link:

<img width="505" alt="Screenshot 2022-02-17 at 11 04 52" src="https://user-images.githubusercontent.com/699132/154453333-dd4fe283-235f-4f20-b12e-5f4f6f60bc21.png">

New Comments Query Loop block and Page 3 has a different link:

<img width="442" alt="Screenshot 2022-02-17 at 11 05 01" src="https://user-images.githubusercontent.com/699132/154453693-0761bcb7-de46-4960-a52a-ccc4f5ca7195.png">

## Issue 2

Settings used:

<img width="831" alt="Screenshot 2022-02-17 at 11 10 42" src="https://user-images.githubusercontent.com/699132/154454112-b45d6080-0249-4789-bc7e-09471a7dcbb2.png">

Old Post Comments block and Older Comments link:

<img width="860" alt="Screenshot 2022-02-17 at 11 11 32" src="https://user-images.githubusercontent.com/699132/154454279-f7a917a8-64ae-4771-82f0-27cad985c4d5.png">


New Comments Query Loop block and Older Comments link:

<img width="792" alt="Screenshot 2022-02-17 at 11 12 05" src="https://user-images.githubusercontent.com/699132/154454395-ead9d261-6d50-4adf-908d-be07c0481a76.png">

New Comments Query Loop block and Page 1 has a different link:

<img width="619" alt="Screenshot 2022-02-17 at 11 12 33" src="https://user-images.githubusercontent.com/699132/154454476-d2592afe-1695-44ad-a34c-8894e637ee9b.png">

**Comment by mauriac** [comment]
@c4rl0sbr4v0 @gziolo I've submitted a PR, can you review it? thanks

**Comment by cbravobernal** [comment]
This issue will be fixed on Core.
