### ISSUE TITLE
Comments Pagination Block: should we use "Older" and "Newer" comments instead of "Previous" and "Next" tags?

### ISSUE THREAD

**Issue by cbravobernal** [WordPress/gutenberg#37562]
## What problem does this address?

Right now, in `Comments Pagination Block`, we use "Previous" and "Next" for the default labels of next and previous blocks.

After checking some themes and also functions we can find we use Older and Newer:

https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/link-template.php#L3172-L3181

In case the user is not ordering by the date of the comments, is this a valid approach?

**Comment by jasmussen** [comment]
Yes, to me older/newer reads better than next/previous. As you note, that phrasing will likely fall apart a bit if someone uses an odd or non-standard sorting order in their queries, so we'll need both terms.

**Comment by carolinan** [comment]
Is it not enough that the text is editable?

**Comment by cbravobernal** [comment]
I agree that having the text editable allows the user to decide what to show if they change the orderBy option. That is enough and already implemented.

In that case, we could change Next and Previous default labels by Older and Newer, right?

**Comment by carolinan** [comment]
Yes I believe it would be better if the block and the existing comment navigation matched.

**Comment by aristath** [comment]
It is possible to change the order of comments, so it can either be newer to older, or older to newer. That's why next/previous is easier. It doesn't depend on the order of the query and therefore always works properly.
If we do change the wording to newer/older, then we need to make sure that the labels adapt depending on the query order. We can't just string-replace the next/previous with older/newer and expect it to work for all scenarios, it will probably be more complicated than that.

**Comment by cbravobernal** [comment]
Thank you all for the responses, is really great to have the opinions of more experienced contributors.

I guess that WordPress, depending on the order, switches the functions `get_next` and `get_previous`. Cause as far I've seen both in templates and in the core, previous is always default as older, and next is always default as newer.

Anyway, we are also working on adding a sort option to the query block ([PR here](https://github.com/WordPress/gutenberg/pull/37297)), so adapting the pagination labels defaults should not be a really difficult task, although may I miss something.
