### ISSUE TITLE
Duplicate "Theme Editor" menu in Tools as 5.9 relocates and renames the menu item

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#37568]
### Description

WordPress Core's [changeset 52232](https://core.trac.wordpress.org/changeset/52232) backported to relocate the "Theme Editor" menu item from Appearance to Tools. However, when the Gutenberg plugin is enabled, it also adds a duplicate menu item.

Please note, [changeset 52406](https://core.trac.wordpress.org/changeset/52406) renamed the menu item "Theme File Editor", relocated the plugin editor menu item to Tools, and renamed the plugin editor to "Plugin File Editor".

### Step-by-step reproduction instructions

1. Upgrade to at least 5.9 Beta 4
2. Activate the Gutenberg plugin
3. Activate TT2
4. Go to the Tools

### Screenshots, screen recording, code snippet

![Screen Shot 2021-12-21 at 4 04 04 PM](https://user-images.githubusercontent.com/7284611/147003537-138d2d4a-5972-4e90-ba70-b7522080aed2.png)

### Environment info

- WordPress 5.9 Beta 4
- Gutenberg v 12.1.0
- OS: macOS Big Sur
- Localhost: Local and wp-env

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Do we want to to remove [gutenberg_move_theme_editor_in_block_themes()](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-5.9/move-theme-editor-menu-item.php), or add a version check for versions below 5.9.0?

**Comment by Mamaduka** [comment]
@carolinan, Are you working on this issue?
