### ISSUE TITLE
When customising a template from a plugin pressing the browser back button does not update the template list

### ISSUE THREAD

**Issue by opr** [WordPress/gutenberg#37585]
### Description

If you customise a template in the Site Editor, then press the browser back button, attempting to edit the same item again (without refreshing the template page) the`You attempted to edit an item that doesn't exist. Perhaps it was deleted?` error shows up.

### Step-by-step reproduction instructions

1. Install WooCommerce Blocks (or any other extension that adds templates to Gutenberg).
2. Go to the site editor templates list.
3. Find a template from a plugin that has not been customised.
4. Customise it and press save.
5. Use the browser back button to return to the template list.
6. Try to edit the same template again.
7. See the error

### Screenshots, screen recording, code snippet

https://www.loom.com/share/787ffc07d7594d5798d84f1f83bab848

### Environment info

Gutenberg 12.1.0 and WooCommerce blocks trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
Since RC was already released, I'm removing this issue from WP 5.9 board.

Custom template support in plugins isn't well tested or [documented](https://github.com/WordPress/gutenberg/issues/37476) feature.

Let's try to fix this for the next release.

**Comment by youknowriad** [comment]
We now have a formal Api to register templates #65958 and I can't reproduce this issue.
