### ISSUE TITLE
Template part focus mode doesn't handle empty template parts very well

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#37584]
I think this is most likely a result of the removal of the appender in https://github.com/WordPress/gutenberg/pull/37213.

It is especially problematic when creating a template part from scratch via list view. The resultant editor view makes it impossible to interact with the canvas. It all feels a bit confusing:

https://user-images.githubusercontent.com/846565/147083796-18d99d43-9102-40eb-bf2f-0003ce8b938b.mp4

As suggested in https://github.com/WordPress/gutenberg/issues/36827, I think it would make sense for the appender (or an empty paragraph) to appear if the template part is empty.

**Comment by Mamaduka** [comment]
Probably duplicate of #37524.

**Comment by jameskoster** [comment]
Right you are!
