### ISSUE TITLE
Post RN 0.66 Upgrade Tasks

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#37594]
## What problem does this address?
A few tasks arose during https://github.com/WordPress/gutenberg/pull/36328. This ticket captures those tasks in a single location for further consideration. 

## What is your proposed solution?
After https://github.com/WordPress/gutenberg/pull/36328 merges, we should address the following or create individual tickets to address them in the future:

- [ ] Upgrade third-party React Native dependencies, prioritizing those with [references to deprecated APIs](https://github.com/WordPress/gutenberg/pull/36328#discussion_r773816498). 
- [ ] https://github.com/WordPress/gutenberg/issues/37559
- [x] Evaluate suitability of monorepo for all forked React Native dependencies to ease burden of updating the React Native version used and pulling in upstream changes.  
- [ ] [Consider refactoring](https://github.com/WordPress/gutenberg/pull/36328#discussion_r774666233) `LinkSettingsScreen` to simplify and avoid leaking its concerns through better React Hook composition. 
- [ ] https://github.com/WordPress/gutenberg/issues/32884
- [ ] Set up [Flipper debugger](https://fbflipper.com) support

**Comment by hypest** [comment]
Let's keep this umbrella ticket in "triage mode" until the RN 0.66 upgrade is merged and we'll then evaluate if any of the follow-up tasks needs prioritized attention.

**Comment by hypest** [comment]
Seems to me that none of the items in the list so far are too pressing to work on immediately, what do you think @dcalhoun ? If so, I'd like to move this ticket out of the triage state and to the backlog.

**Comment by dcalhoun** [comment]
> Seems to me that none of the items in the list so far are too pressing to work on immediately, what do you think @dcalhoun ? If so, I'd like to move this ticket out of the triage state and to the backlog.

@hypest I agree that none of them are critical and that we should move it to the backlog. That said, I will share my thoughts on the impact of each task. 

>Upgrade third-party React Native dependencies, prioritizing those with [references to deprecated APIs](https://github.com/WordPress/gutenberg/pull/36328#discussion_r773816498).

Regardless of the deprecations, I believe the further we allow our dependencies to become outdated, the more difficult it will be to upgrade them. Additionally, I foresee these outdated dependencies eventually disrupting our ability to upgrade React Native itself. So, I believe we should look to schedule time to upgrade these dependencies within 2022. 

> [Improve stability and performance of BottomSheet animations #37559](https://github.com/WordPress/gutenberg/issues/37559)

As outlined in the issue, we have experienced a fair amount of challenges in both UX and code stability in this portion of the product. Given it is so heavily used, we should likely place a fair amount of importance on this feature. 

> Evaluate suitability of monorepo for all forked React Native dependencies to ease burden of updating the React Native version used and pulling in upstream changes.

In reality, this is only tangental related to the Gutenberg repository itself. The fork repository approach is more related to the WordPress mobile apps. WDYT about relocating this task elsewhere? 

> [Consider refactoring](https://github.com/WordPress/gutenberg/issues/37594) `LinkSettingsScreen` to simplify and avoid leaking its concerns through better React Hook composition.

A nice to have and likely a beneficial exercise for the team and project, but not a priority IMO. 

> [VirtualizedLists should never be nested inside plain ScrollViews error #32884](https://github.com/WordPress/gutenberg/issues/32884)

The error displays each time the Demo editor launches or reloads. So, it is a friction point for ongoing development and could confuse new contributors. Since we already have made some progress on a fix in https://github.com/WordPress/gutenberg/pull/33170, it is likely worthwhile to attempt to get this work "over the finish line" if we can afford the time. 
 
> Set up [Flipper debugger](https://fbflipper.com) support

Nice to have, but likely not a priority. I have a branch beginning this work, and will likely work on it in between other higher priority work.

**Comment by hypest** [comment]
Very useful context David, thanks for sharing!

It's clear that yeah, not all items are of the same importance or impact, and since none is critical but yet, a few are important enough, I'll go ahead and add "[Pri] high" to keep it close to the "surface", for us to revisit soon as we'll be planning 2022 projects. How's that sound to you?

**Comment by dcalhoun** [comment]
@hypest sounds good. Thank you.

**Comment by dcalhoun** [comment]
Closing this issue as the listed tasks are tracked elsewhere or have become less relevant. Feel free to re-open if deemed worthwhile. 

---

> * Upgrade third-party React Native dependencies, prioritizing those with https://github.com/WordPress/gutenberg/pull/36328#discussion_r773816498.

We have https://github.com/WordPress/gutenberg/issues/53359 and https://github.com/WordPress/gutenberg/issues/53360 tracking dependency upgrades that we deem important.

> * https://github.com/WordPress/gutenberg/issues/37559

The referenced issue provides enough tracking in itself.

> * Evaluate suitability of monorepo for all forked React Native dependencies to ease burden of updating the React Native version used and pulling in upstream changes.

This was marked completed.

> * [Consider refactoring](https://github.com/WordPress/gutenberg/issues/37594) `LinkSettingsScreen` to simplify and avoid leaking its concerns through better React Hook composition.

While still relevant, it is not a high priority. Refactoring this would likely also collide with or become dependent upon work to address https://github.com/WordPress/gutenberg/issues/37559. It is worth noting the link in the original issue description was incorrect, it should have been https://github.com/WordPress/gutenberg/pull/36328#discussion_r774666233. 

> * https://github.com/WordPress/gutenberg/issues/32884

The referenced issue provides enough tracking in itself.

> * Set up [Flipper debugger](https://fbflipper.com/) support

With the release of React Native 0.73, the core team is working to [replace Flipper with a new debugger](https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#experimental-new-debugger).
