### ISSUE TITLE
Click outside to dismiss mode switcher, inserter overlays

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#376]
Unsure if this will end up being satisfied by separate pull requests to address mode switcher and inserter separately, or common solution like a common Tooltip (Popover, Overlay) component.

__Steps to reproduce:__

1. Click Inserter / Mode Switcher
2. Click elsewhere on the page

__Expected result:__

Inserter / Mode Switcher toggled in step 1 is dismissed.

__Actual result:__

Inserter / Mode Switcher is not dismissed.

**Comment by kopepasah** [comment]
I agree that the switcher should disappear when a user performs an action (e.g. `click`) which takes focus away from the mode switcher.

This task is currently unassigned. Any objections to me diving in?

**Comment by youknowriad** [comment]
Thanks for the offer to help. Feel free to take tackle this task 👍 (or any unassigned task)

**Comment by BE-Webdesign** [comment]
#582, and #596, should close this out.
