### ISSUE TITLE
Coloring panel is unusable in RTL

### ISSUE THREAD

**Issue by Wesam000006** [WordPress/gutenberg#37605]
### Description

When the control panel in RTL language, the coloring panel goes off the browser borders, making it unusable.

Kindly see the attached phot

![Screenshot-2021-12-22-211431](https://user-images.githubusercontent.com/96513695/147195713-20418c46-4e2d-4946-bc8e-0c9ced3bffbd.jpg)
o

### Step-by-step reproduction instructions

1- Set control panel language to an RTL one
2- Try changing any element color
3- Here you go

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@Wesam000006 Thanks so much for testing! Can you confirm what version of WordPress you are using? For example, is this being tested with the WordPress 5.9 beta 4?

**Comment by Wesam000006** [comment]
@annezazu Thank you for responding.
I'm using WP 5.8.2, and the latest Gutenberg version.

**Comment by annezazu** [comment]
Excellent. Thank you! I tested and can confirm this with the latest version of Gutenberg but not with the WordPress 5.9 Beta 4 nightly release.

Gutenberg 12.2:

<img width="1235" alt="Screen Shot 2021-12-23 at 10 59 52 AM" src="https://user-images.githubusercontent.com/26996883/147264751-0df9c6e2-6a7d-4f06-87c8-5aa31f393fc1.png">

WordPress 5.9-beta4-52409:

https://user-images.githubusercontent.com/26996883/147264742-097cf29d-f790-4efa-92cc-a33bed5093c9.mov


cc @jorgefilipecosta I see you have some PRs recently around this feature. Might taking a look?
