### ISSUE TITLE
Unwanted closing P tag appear just before closing DIV tag

### ISSUE THREAD

**Issue by rajuahmmedbd** [WordPress/gutenberg#3760]
## Issue Overview

Some unwanted closing `<p>` tag appear just before closing `<div>` tag. It's happening with **Text Columns** block.

**Bug Output:**
```
<section class="wp-block-text-columns alignundefined columns-3">
    <div class="wp-block-column">
        <p>Example Text 1</p>
    </p></div>
    <div class="wp-block-column">
        <p>Example Text 2</p>
    </p></div>
    <div class="wp-block-column">
        <p>Example Text 3</p>
    </p></div>
</section>
```
See there is unwanted closing `<p>` tag.

**Comment by rajuahmmedbd** [comment]
I have found why it's happening. We are filtering content by `do_blocks()` before `do_shortcode()` and `wpautop()`. But when we are executing `gutenberg_wpautop()` and checking gutenberg block existence by `gutenberg_content_has_blocks()`, It's return false. Because we already removed `<!-- wp:` comment from `do_blocks()`.

Fix:
```
function gutenberg_wpautop( $content ) {
	if ( gutenberg_content_has_blocks( $content ) ) {
		return $content;
	}

	return wpautop( $content );
}
remove_filter( 'the_content', 'wpautop' );
add_filter( 'the_content', 'gutenberg_wpautop', 8 );
```

or

```
function gutenberg_wpautop( $content ) {
	if ( gutenberg_content_has_blocks( get_the_content() ) ) {
		return $content;
	}

	return wpautop( $content );
}
remove_filter( 'the_content', 'wpautop' );
add_filter( 'the_content', 'gutenberg_wpautop' );
```

**Comment by SherylHohman** [comment]
I'm experiencing closing p tags auto-inserted before closing divs as well.  I have turned off Gutenberg. Am using Classic eiditor. Everything is up to date. It is not for all closing divs though. On the page I'm obsessing over right now, it happens twice. Any other clues why this could happen?

**Comment by lkraav** [comment]
@SherylHohman see https://core.trac.wordpress.org/ticket/14050 first.
