### ISSUE TITLE
Highlight: can't manually type in a custom HEX code

### ISSUE THREAD

**Issue by formosattic** [WordPress/gutenberg#37628]
### Description

The Highlight won't let me manually enter an HEX code, and the color picker also jumps.
Related bug: https://github.com/WordPress/gutenberg/issues/37018

![](https://user-images.githubusercontent.com/15944096/147397036-387594b9-4d03-4728-8a43-b2b69e938163.gif)

Current workaround is to copy/paste the HEX code (though it has a minor issue too, see https://github.com/WordPress/gutenberg/issues/37018#issuecomment-1001093803), or set it manually in HTML view.

### Step-by-step reproduction instructions

1. Add a text with a Paragraph block
2. Use Highlight, and manually set a HEX code

### Environment info

*   Gutenberg 12.0.1
*   WordPress 5.8.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by lwangdu** [comment]
I am having seem issue with TT2 and WordPress 5.9 bate 4.

**Comment by annezazu** [comment]
I can replicate with TT1 and 5.9 beta 4 as well cc @jorgefilipecosta once more.

**Comment by jorgefilipecosta** [comment]
This issue seems to have been fixed on https://github.com/WordPress/gutenberg/pull/36263. I guess the fix needs some update. @alshakero would you be able to have a look?

**Comment by alshakero** [comment]
I can confirm this is fixed by https://github.com/WordPress/gutenberg/pull/36263

**Comment by jorgefilipecosta** [comment]
Hi @alshakero, I'm not sure if the issue is fixed I still seem to be able to replicate it on the trunk.

**Comment by alshakero** [comment]
I'll double check tomorrow.

**Comment by Greatdane** [comment]
@alshakero - Any update on this one, please? 

Also, is this a duplicate of https://github.com/WordPress/gutenberg/issues/37018 ?

**Comment by tellisbethel** [comment]
Hey there, @alshakero! If you're still on this particular case, did you get a chance to take another look at this issue? If not, is there anyone else we should ping? Thanks!

**Comment by annezazu** [comment]
Closing this back out as it should be resolved based on my testing with 6.0 RC4. Feel free to let me know if it needs to be reopened!

**Comment by dhruv-15-03** [comment]
Working on this! Will open a PR soon.
