### ISSUE TITLE
Feature request: Option to clear formatting

### ISSUE THREAD

**Issue by ricjcs** [WordPress/gutenberg#37632]
In Classic Edit mode (or classic block) there is an option to clear formatting.

![2021-12-27](https://user-images.githubusercontent.com/11923491/147492140-bf359bf0-41c8-494e-883a-80e01efbed85.jpg)

This option is very useful to clean the formatting of some content copied to the post, and also to quickly clean the formatting of texts produced in the editor itself.

It would be nice to have this option in the Paragraph Block and in the List Block.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/8869. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
