### ISSUE TITLE
Navigation Block: Classic menus not listed for nav block configured by theme

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#37634]
### Description

With WordPress 5.9 Beta 4, I tried creating a fresh site with 5.8.2, make a few menus using the prior way, and then switch to FSE. When adding the navigation block, I expected to see various "Classic" menus listed as a result but found none when trying to edit the navigation block that came with TT2. If I added a new navigation block, I could see them listed. I replicated this twice across different completely new test sites. When looking at the latest update on the nav block tracking, I don't see anything indicating that importing classic menus shouldn't work: https://github.com/WordPress/gutenberg/issues/35521

Note that the Manage Menus section doesn't list the classic menus either (not sure what's expected there). 

### Step-by-step reproduction instructions

1. Create a site with WP 5.8.2
2. Create a few menus with a classic theme.
3. Update to 5.9 Beta 4 and enable TT2.
4. Open the Appearance > Editor. 
5. Try to use the "select menu" option in the header for the navigation block listed. Notice classic menus are missing.
6. Add a brand new navigation block and see that classic menus are listed. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/147507377-b8bd6c2f-d75b-4113-ab03-b406e224b511.mov

### Environment info

- WordPres 5.9 beta 4
- TT2
- No Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @annezazu

Do you get different results if you use the Classic theme on 5.9 beta4 to create menus and then switch TT2?

**Comment by annezazu** [comment]
No. I get the same result sadly :( I tried that yesterday too and found it still does not show unless I add a brand new navigation block to the site editor.

**Comment by Mamaduka** [comment]
Thanks for the update, @annezazu. I will try to track this down tomorrow, and hopefully, we can ship the fix with 5.9.

**Comment by Mamaduka** [comment]
@annezazu, I think this behavior is intentional, but I couldn't find details in PRs. @talldan or @getdave might have more information.

**Comment by annezazu** [comment]
Thanks for digging in. Happy to close out if there's more context but wanted to report to be safe in case it wasn't :)

**Comment by Mamaduka** [comment]
@annezazu, I'm going to remove this from the 5.9 board. Once we have more context, we can find the next target release, minor or major.

**Comment by annezazu** [comment]
This issue matches https://github.com/WordPress/gutenberg/issues/38166 which has been resolved ahead of a 5.9 RC4.
