### ISSUE TITLE
Importing post with galleries doesn't work properly

### ISSUE THREAD

**Issue by christianoliveira** [WordPress/gutenberg#37630]
### Description

Feature "import" doesn't work properly when the imported post has galleries. I expect it to import the galleries and the images and the gallery to keep working, but instead of that when clicking an image in the gallery, another image is loaded.

The galleries were created using Jetpack Galleries

The import tools works ok in terms of actually importing the images to the Media database and showing them in the gallery, but it doesn't replace other fields that referes to the images that are important for the gallery to work properly, so some of the references of the images point to the previous ID (the ID of the image in the previous blog from where the post was imported) instead of the current ID of the image. 

It also seems that when the old ID doesn't exist in the current wordpress installation, the image is nevertheless correctly loaded when clicking on it, but if the ID exists, the image associated with that ID is loaded instead.

### Step-by-step reproduction instructions

You can see this in action in this published post: 

https://randomtrip.pt/guia-terceira-acores/

The post was imported and translated from https://randomtrip.es/guia-terceira-azores/ . The galleries show the correct pictures, but when clicking on them (when opening the gallery) in some cases the image loaded is completely different from the image in the gallery.

When inspecting the code of the first gallery, we can see that there are several references to randomtrip.es that should've been updated when importing the post, but they are not. Also, the IDs included in the first line (the one that defines the blog) are the IDs of the images in the origin post (the one imported), not on the current one. (red: incorrect references. green: correct references)

![import-galleries-not-working](https://user-images.githubusercontent.com/553835/147482356-1dd2f6e6-b8e3-4553-8c54-b8e595a9d371.jpg)

The actual IDs of those images in randomtrip.pt are:

- https://randomtrip.pt/wp-content/uploads/2021/12/angra-do-heroismo-prainha-1024x683.jpg => 10771
- https://randomtrip.pt/wp-content/uploads/2021/12/angra-do-heroismo-porto-1024x683.jpg => 10772
- https://randomtrip.pt/wp-content/uploads/2021/12/angra-do-heroismo-igreja-da-misericordia-1024x683.jpg => 10773
- https://randomtrip.pt/wp-content/uploads/2021/12/angra-do-heroismo-vasco-da-gama-1024x683.jpg => 10774

### Screenshots, screen recording, code snippet

https://drive.google.com/file/d/12pN05eEKWOWQpJPHBfe7gFgDLTUS-ZbZ/view?usp=sharing

### Environment info

- Wordpress 5.8.2
- Chrome 96.0.4664.110
- Mac OS 12.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@christianoliveira thanks for reporting this! 

> The galleries were created using Jetpack Galleries

Can you please report this in the Jetpack repo? You can find it here: https://github.com/Automattic/jetpack 

I'm going to close this out for now as this needs to be investigated by Jetpack first.

**Comment by christianoliveira** [comment]
@annezazu thanks, will publish the issue there then!

**Comment by christianoliveira** [comment]
Created the issue in the Jetpack repository: https://github.com/Automattic/jetpack/issues/22182

**Comment by annezazu** [comment]
Thanks so much!!
