### ISSUE TITLE
Template editor conditional tags and file loadings

### ISSUE THREAD

**Issue by wpsoul** [WordPress/gutenberg#37642]
I am trying to make perfomance improvements for template and widget editors, but currently I can't find any documentation or functionality for this.

In the current point, the only way to load conditional styles and scripts in Template editor is to attach them in block.json file in block registration. Problem is that this file doesn't support multiple files and conditional loading (for example by attribute value). Is any plan to make block.json script and styles more flexible? The perfect will be if we will have some option in javascript Edit and Save functions to store conditional styles of block in some storage and this storage will be used to render styles in head or footer section.

So I made redux store functionality and store conditional styles in post meta. Unfortunately, it doesn't work in Template editor, so I need some functions to detect if we are on Template editor environment. Something like is_template_editor, is_widget_editor, etc (I need for javascript and for PHP).

**Comment by annezazu** [comment]
cc @aristath and @youknowriad perhaps you all might have some ideas?

**Comment by tellthemachines** [comment]
Hi there! I'm not sure I get what you're trying to do. Do you want to load different styles and scripts for a specific block depending on which editor it's in? Would this be easier to solve by splitting those different functionalities into different blocks?

To answer the question of how to detect the environment, in PHP you can check which admin page you're on with [get_current_screen](https://developer.wordpress.org/reference/functions/get_current_screen/), but that won't differentiate between different views in the site editor for instance. 

There are also a few JS functions you can use: `wp.data.select('core/edit-post').isEditingTemplate()` will return true when in template editing mode within the post editor; likewise you can find out the slug for the template currently being edited in the site editor with `wp.data.select('core/edit-site').getPage()`.

Hope this helps!

**Comment by wpsoul** [comment]
This will be fixed in Wordpress 6.1 so I am closing
