### ISSUE TITLE
Error "This block has encountered an error and cannot be previewed" when adding BlockControls in edit.js

### ISSUE THREAD

**Issue by henimbola** [WordPress/gutenberg#37643]
### Description

Hi !
I'm trying to follow the tutorial [here](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/block-controls-toolbar-and-sidebar/) to learn how to create gutenberg blocks.
Whenever I try to add this :
 `			{
				<BlockControls>
					<AlignmentToolbar value={attributes.alignment} onChange={val => { setAttributes({ alignment: val === undefined ? 'none' : val }) }} />
				</BlockControls>
			}`

I always get an error like '"This block has encountered an error and cannot be previewed". Whereas it works when and don't add controls in the code. Why is that ?

Here is my complete code :

```
import { __ } from '@wordpress/i18n';
import { useBlockProps, InspectorControls, RichText, AlignmentToolbar } from '@wordpress/block-editor';
import './editor.scss';
import { TextControl } from '@wordpress/components';
import { Fragment } from '@wordpress/element';

export default function Edit({ attributes, setAttributes }) {
	return (
		<div {...useBlockProps()}>
			{
				<BlockControls>
					<AlignmentToolbar value={attributes.alignment} onChange={val => { setAttributes({ alignment: val === undefined ? 'none' : val }) }} />
				</BlockControls>
			}
			<div class="image-hover-block-text-container">
				<RichText
					tagName='p'
					value={attributes.message}
					onChange={val => setAttributes({ message: val })}
				/>
			</div>
		</div>
	);
}
```

### Step-by-step reproduction instructions

1. Create new block
2. Edit edit.js
3. Add BlockControls Tag

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/31709152/147598974-497ebf17-c18b-40b7-83e8-4762090a8806.png)

When I remove the `<BlockControls>` tag, it works fine. Everytime I add it, the block always crashes.

### Environment info

Local Wordpress with php
Npm

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @henimbola

It looks like you're missing the `BlockControls` import; applying the suggested changes below should fix the issue.

```diff
- import { useBlockProps, InspectorControls, RichText, AlignmentToolbar } from '@wordpress/block-editor';
+ import { useBlockProps, BlockControls, RichText, AlignmentToolbar } from '@wordpress/block-editor';
```

**Comment by henimbola** [comment]
Hi @Mamaduka Thanks for your quick feedback.
I didn't give attention on the imports. Thanks for your help.
I will see if it fixes.

**Comment by Mamaduka** [comment]
Hi, @henimbola

I just wanted to check in to see if my suggestion helped you fix the issue?

**Comment by Mamaduka** [comment]
Hi, @henimbola

I'm going to close this issue. Feel free to re-open it if you're still experiencing the error.

**Comment by majestryrandom** [comment]
> Hi, @henimbola
> 
> It looks like you're missing the `BlockControls` import; applying the suggested changes below should fix the issue.
> 
> ```diff
> - import { useBlockProps, InspectorControls, RichText, AlignmentToolbar } from '@wordpress/block-editor';
> + import { useBlockProps, BlockControls, RichText, AlignmentToolbar } from '@wordpress/block-editor';
> ```

Hi, where do i enter this command? thankyou
