### ISSUE TITLE
Zoom issue when editing a module in iOS

### ISSUE THREAD

**Issue by TwisterMc** [WordPress/gutenberg#3766]
## Issue Overview

When clicking the + sign to add a block, the block window opens up but it's zoomed in and you can't see the whole block window. 

## Steps to Reproduce (for bugs)

1. Grab an iPhone running the latest iOS and Safari. I'm on an iPhone 6S
2. Open up the WordPress admin and create a new post (or edit an existing one) that uses Gutenberg
3. Click the + sign to add a new block.
4. Notice that everything zooms in as the block window opens.

## Expected Behavior

Block window should not zoom in and whole block window should be visible.

## Current Behavior

Block window zooms in and things get cut off.

## Possible Solution

This looks relevant and describes the issue:
http://blog.osmosys.asia/2017/01/05/prevent-ios-from-zooming-in-on-input-fields/

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by TwisterMc** [comment]
Screenshot 
![img_4148b51d4f7c-1](https://user-images.githubusercontent.com/46997/33522785-d182b0ac-d7ba-11e7-8a09-be64738de12a.jpeg)

**Comment by danielbachhuber** [comment]
> This looks relevant and describes the issue:
> http://blog.osmosys.asia/2017/01/05/prevent-ios-from-zooming-in-on-input-fields/

I agree with this guess based on past experience. iOS zooms fields where the font size is < 16px. The most correct fix is to increase the font size in those fields.

**Comment by TwisterMc** [comment]
Looks like this has been fixed in one of the updates since I posted this ticket. I think there are still some issues with iOS when hitting the + button, but the zoom seems to be fixed.

**Comment by iseulde** [comment]
Seeing this too on iPad.

**Comment by iseulde** [comment]
But I cannot upload a screenshot on Github with the iPad... great.

**Comment by iseulde** [comment]
![c29e98c6-e0d3-4cd5-99c9-10e9817a7bab](https://user-images.githubusercontent.com/4710635/35686217-0eb5622c-076c-11e8-8770-2d173e2ce2d3.jpeg)

**Comment by TwisterMc** [comment]
As noted above, it seems to be working fine on iOS.

**Comment by jasmussen** [comment]
Given the recent tests, I'm going to close this one as fixed. The issue may have been inadvertently fixed as part of many updates done to the input and/or mobile UI.

If it turns out to not have been fixed, it's easy an quick to reopen. Thanks, all!
