### ISSUE TITLE
Site Logo block missing option to set site icon 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#37677]
### Description

While writing documentation for 5.9, I went to get screenshots for this change https://github.com/WordPress/gutenberg/pull/35892#event-5800922904 and was unable to see the option to set the site logo block as the site icon, despite someone else mentioning in the thread that they could with 5.9 beta 3. I tried with beta 4 and with the nightly beta 4 (5.9-beta4-52424). cc @stacim

### Step-by-step reproduction instructions

1. Open site editor.
2. Find or add the site logo block.
3. Upload an image.
4. Open sidebar settings.
5. Don't see an option to set as site icon.

### Screenshots, screen recording, code snippet

<img width="1398" alt="Screen Shot 2021-12-31 at 9 46 29 AM" src="https://user-images.githubusercontent.com/26996883/147829033-9edccb8f-b417-4e99-b2e8-a577ee5cc9ba.png">

### Environment info

- WordPress 5.9 beta 4 + nightly beta 4 version.
- Tried both with and without Gutenberg 12.2.0  (didn't work either way).
- TT2 theme
- Chrome
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
The #35892 got merged after beta 4 was released. The feature will be available in Gutenberg 12.3.

It has backported label, but I don't think we merge it now because of the size of the change and new strings.

We can probably backport it into a minor release.

**Comment by annezazu** [comment]
Ahhhh I see. I saw someone mention 5.9 beta 3 in testing in the comments so wanted to be safe by reporting :) Would be good to get it into a minor release. Thank you! I'll close this out.
