### ISSUE TITLE
iOS Can't Close Settings

### ISSUE THREAD

**Issue by TwisterMc** [WordPress/gutenberg#3767]
## Issue Overview

When clicking the gear to get into the settings, the window opens but it won't close. You also can't click on the Block tab.

## Steps to Reproduce (for bugs)

1. Grab an iPhone running the latest iOS and Safari. I'm on an iPhone 6S
2. Open up the WordPress admin and create a new post (or edit an existing one) that uses Gutenberg
3. Click on the gear icon to the right of the publish icon.
4. Click the x to close that window OR click on 'Block'

## Expected Behavior

Should be able to switch to the 'Block' settings and close the settings window when done.

## Current Behavior

Nothing happens when clicking on 'Block' or  the X to close the window.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Thanks for the report, @TwisterMc.

Could you include a GIF by chance? I tried to replicate in my iOS Simulator but it's not working in my local environment at the moment.

**Comment by TwisterMc** [comment]
Looks like one of the updates since I created this ticket has fixed it.  Consider it fixed.

**Comment by danielbachhuber** [comment]
Thanks @TwisterMc
