### ISSUE TITLE
Export tool turns var() into unicode characters

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/gutenberg#37671]
### Issue
When template files use variable `var()`, export tool turns the variable into Unicode characters. 

For example, Page template in Twenty Twenty-Two uses 
`var(--wp--custom--spacing--medium, 6rem)` on the line 5.  

![screenshot-TT2](https://user-images.githubusercontent.com/30734209/147786942-0043135a-6797-48ea-8a60-076ff2d1535a.jpg)

After exporting, the variable turns into 
`var(\u002d\u002dwp\u002d\u002dcustom\u002d\u002dspacing\u002d\u002dmedium, 6rem)`.

![screenshot-Export](https://user-images.githubusercontent.com/30734209/147787024-f9d7c552-1049-4149-838b-209fa9fe3fc7.jpg)

### Step-by-step reproduction instructions

1. Install Twenty Twenty-Two
2. Go to Editor < Templates <  Page
3. Click on the 3 dots on the top right corner to open the Tools panel
4. On the Tools panel, click Export to download templates and templates parts files
5. Check the line 5 on Page template file

### Environment info

I tested on 5.9-beta4 using Gutenberg v12.2.0 on Firefox /  macOS.

**Comment by annezazu** [comment]
cc @Mamaduka perhaps since you've done work around exporting items: https://github.com/WordPress/gutenberg/pull/36619

**Comment by Mamaduka** [comment]
Thanks for the ping, @annezazu. Assing this issue to myself and will have a look next week.

**Comment by chthonic-ds** [comment]
I believe this is happening for any instance of `--`, not just for CSS variables.

For example, `wp-block-query--cards` becomes `wp-block-query\u002d\u002dcards` when exported.

**Comment by Mamaduka** [comment]
Hi, @scruffian

Since you worked on recent export updates, do you remember if this is still an issue?

**Comment by scruffian** [comment]
We decided that this is the correct behaviour, see https://github.com/WordPress/gutenberg/issues/39576

**Comment by Mamaduka** [comment]
Thank you, @scruffian.

**Comment by tcmulder** [comment]
I'm confused, does this mean we're unable to use [BEM](https://en.bem.info/methodology/css/) class names for blocks? I have a select box that lets the user select multiple classes to apply to their block, which it saves as an array of class names, and right now my client is getting the "attempt block recovery" warning because classes like `carousel--dark` get converted to `carousel\u002d\u002ddark` in the `save` function but not in the post body.
