### ISSUE TITLE
Glitches in Editor toolbar Dropdowns

### ISSUE THREAD

**Issue by AnwerAR** [WordPress/gutenberg#3768]
## Issue Overview

Normally drop-downs under Editor Toolbar is expanding downwards as expected but upon resizing Window/viewport,  they are expanding upwards & downwards on each click respectively. 

## Steps to Reproduce

1. Open up Editor
2. Reduce window height by either opening Browser inspector or resizing window
3. Click on **Insert Block** or **Content Structure**  icons.

I am using Chrome/Win10 and using latest Master branch from this repo.
## Expected Behavior
Ideally shouldn't it expand dropdowns in downwards regardless or Window size?

## Screenshots / Video

![gutenberg - dropdown screenshot](https://user-images.githubusercontent.com/11960126/33526265-562f9288-d7f3-11e7-9287-05e25cfdd882.png)

Screencast link: https://drive.google.com/file/d/1CVtw_qeF0BqeP646AvIevT-JUcwR8RzU/view

**Comment by youknowriad** [comment]
This should behave better now since #3947  Please reopen if you still experience issues.
