### ISSUE TITLE
[Navigation] Vertical orientation control does not work with the "Page List" block

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#37694]
### Description

"Page List" block items do not stack when the "Vertical" orientation is selected. 

### Step-by-step reproduction instructions

1. Add a new navigation block. 
2. From the placeholder options, choose "Add all pages" 
3. In the sidebar, select the "Vertical" orientation. 
4. Note that the pages do not appear stacked. 

### Screenshots, screen recording, code snippet

![screenshot](https://user-images.githubusercontent.com/1202812/147971181-5ed3f8bd-3a71-4826-9365-646983da935d.gif)

### Environment info

WordPress 5.8.2
Gutenberg 12.3.0-rc.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kjellr** [comment]
cc @jasmussen in case this is related to any recent changes in https://github.com/WordPress/gutenberg/pull/37444.

**Comment by tellthemachines** [comment]
Closing as this has been fixed in #37718.
