### ISSUE TITLE
Copy/paste bug on pull quote blocks

### ISSUE THREAD

**Issue by sultann** [WordPress/gutenberg#37692]
### Description

When the user copies text from a different block that is formatted(Rich text) and attempts to paste in the pull quote block, nothing happens. 

### Step-by-step reproduction instructions

1. Create a post
2. Insert a paragraph block and within the block paste the first paragraph (https://prnt.sc/25uobgg) from https://www.lipsum.com/  make sure **Lorem Ipsum** part is bold like https://prnt.sc/25uoup0
3. Now insert a Pullquote block and paste the first line from the paragraph you created in step 2
4. It will not paste the content

### Screenshots, screen recording, code snippet

https://www.youtube.com/watch?v=fUN0R-mrRn8

### Environment info

- WordPress version 5.8.2
- Google Chrome version 96.0.4664.110
- MacOs Big Sur 11.5.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thank you for the video demonstrating the bug. I was not able to reproduce this; I used 
WordPress 5.9.3. and the Gutenberg plugin 

![image](https://user-images.githubusercontent.com/955351/148849906-8ef9e366-cee2-41ad-96d8-9bbb8fee83bd.png)

Could you try to reproduce this after you have installed and activated the newest version of the block editor that is available through [the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/)?

**Comment by adamwoodnz** [comment]
Closing following triage policy
