### ISSUE TITLE
block.json schema `supports.typography.fontSize|lineHeight` out of date

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#37707]
### Description

The schema for `fontSize` and `lineHeight` has not been updated with the change from `supports.fontSize` to `supports.typography.fontSize` and `supports.lineHeight` to `supports.typography.lineHeight`.

https://github.com/WordPress/gutenberg/blob/trunk/schemas/json/block.json

Related issues: https://github.com/WordPress/gutenberg/pull/36894, https://github.com/WordPress/gutenberg/issues/32600 

### Step-by-step reproduction instructions

1. Create a block with a `block.json`
2.  Extend the`block.json` with the following code
```json
  "$schema": "https://schemas.wp.org/wp/5.8/block.json",
  "supports": {
    "fontSize": false,
    "lineHeight": false
  }
```
3. There are no errors in Visual Studio Code based on the schema
4. When loading the site the following error is shown
> register_block_type_from_metadata() was called incorrectly. Block "pszh/cover" is declaring fontSize support in block.json file under supports.fontSize. fontSize support is now declared under supports.typography.fontSize. Please see Debugging in WordPress for more information. (This message was added in version 5.8.0.)

### Environment info

- WordPress 5.8

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by gziolo** [comment]
@oandregal or @jorgefilipecosta, can you validate this report? Thank you.

**Comment by oandregal** [comment]
Prepared https://github.com/WordPress/gutenberg/pull/37853 to update the schema.

**Comment by grappler** [comment]
Thank you @oandregal for fixing this. Will this be back ported to the `wp/5.8` branch so that the schema in https://schemas.wp.org/wp/5.8/block.json is also correct?

https://github.com/WordPress/gutenberg/blob/wp/5.8/schemas/json/block.json

**Comment by oandregal** [comment]
Prepared https://github.com/WordPress/gutenberg/pull/37913 for updating the `wp/5.8` branch as well.
