### ISSUE TITLE
Add support for Child Blocks like Child Themes

### ISSUE THREAD

**Issue by LantosIstvan** [WordPress/gutenberg#37705]
## What problem does this address?

This feature request only resembles similarity in the name with the following: https://github.com/WordPress/gutenberg/pull/6753

Although following Wordpress naming conventions, this describes better what the functionality should do. In any conflict with the other pull request, then change the name of this feature request whatever you want, until it describes the wanted functionality. If someone already asked for this feature, then please forgive me, I wasn't thorough to find it then.

**So to understand, this question IS NOT ABOUT BLOCK NESTING!**

**Gutanberg blocks should have a feature to import another block as a base for modifications, like re-styling, adding or replacing functions and re-appearing under a new block in the editor. In functionality, this is exactly what a child theme does!**

**For example: I want to make a gallery block, where the images statically resembles the look of an Instagram API request in footer area. For easier understanding, this is the mockup:**

![Clipboard01](https://user-images.githubusercontent.com/5021728/148038026-952f6df0-c6e1-4bbe-a32e-3a77a86a13b6.png)

**A well written gallery block already present in the core library, so why should I copy that code for my plugin for a slight re-styling? The easier solution would be to create a child block, have a slight CSS modification to put the images in one line until a responsive breakpoint, and maybe edit the code to limit maximum number of images able to upload in the gallery?**

**The advantages would be:**
- **Child blocks will get continous development from the base blocks, like a child theme.**
- **Less code clutter, more stable Wordpress installs.**
- **Ability to separate modified child blocks from the base blocks in the block browser.**

## What is your proposed solution?

The implementation should be turned on with a simple switch, like:

```php
<?php

/**
 * Plugin Name:     Gallery Block Child
 ...
 * Template:        core/gallery
 */
```

**Comment by aristath** [comment]
If all you need is CSS tweaks, then why not use the [`block-styles` API](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-styles/)?
You can easily add a new "variation" of the `core-gallery` block, and add all your styles in a custom class there using the [`register_block_style`](https://developer.wordpress.org/reference/functions/register_block_style/) function.

**Comment by draganescu** [comment]
With @aristath 's suggestion and your thumbs up @DJviolin may we close this issue?

**Comment by LantosIstvan** [comment]
I didn't had the time to implement yet, so I will close it.

If the community would want such feature in the far future, then they can reopen it.
