### ISSUE TITLE
Long post title break UI design in templates page

### ISSUE THREAD

**Issue by kafleg** [WordPress/gutenberg#37719]
### Description

I have added a long title of a post. When I went to the Edit template, the design of the post title will be weird. 
See the screenshot. 

### Step-by-step reproduction instructions

* Go to post > Add new
* Enter the title - For example( _A new post with a long title and content in WordPress with embed blocks and videos in an attractive way where we can get all the things in an elegant matter. Do you need even more length of the site title? Really! Oh, that’s is tough bro ;)_)
* Add content (optional)
* Publish the post.
* Again go to Posts > All posts > edit the post with that long title 
* Click on **Edit** at **Template: Single Post** 
* You will see the post title at the top. 

### Screenshots, screen recording, code snippet

![broken-ui-with-long-post-title](https://user-images.githubusercontent.com/13062231/148168469-dbdd2eb8-9789-4aa1-b975-e34333b520f0.png)

### Environment info

- Windows 11 PC
- Laragon Localhost
- PHP 7.4.19
- TT2 theme
- RC 1 - 5.9
- No Gutenberg plugin was installed or activated.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kafleg** [comment]
![image](https://user-images.githubusercontent.com/13062231/149075944-1a71b878-60a1-4862-9b23-1e62182793f5.png)

I can still see the issues.

**Comment by Mamaduka** [comment]
@kafleg, we haven't backported changes into 5.9. The fix will be part of the Gutenberg 12.4 release.
