### ISSUE TITLE
Site Logo: Adjusting image width with toolbar causes strange number calculations

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#37716]
### Description

When adjusting the image width for the site logo, the calculations for how wide the image is both get cut off and get set to very strangely exact numbers. 

### Step-by-step reproduction instructions

1. Add a site logo block.
2. Open block settings.
3. Try dragging the toolbar to adjust the width.
4. Notice problem

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/148146999-5767bc60-2acb-459c-9204-9cee2fc0acd6.mov

### Environment info

- WordPress 5.9 RC1
- Happens with GB 12.2 activated and deactivated
- Twenty Twenty-Two
- MacOS
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@annezazu, I cannot reproduce the bug on the current trunk, the same with RC when the plugin is deactivated.

https://user-images.githubusercontent.com/240569/148191227-bd123a9b-6a87-48a8-baf4-c95e12b8bc16.mp4

**Comment by annezazu** [comment]
Thank you. Just asked for more folks to help test in #core-test to see if we can get more situations covered.

**Comment by annezazu** [comment]
More insights from @costdev (thank you again):

>Can also reproduce 37716 - but only with images that are in landscape orientation. Tested with square, portrait and landscape.
