### ISSUE TITLE
Text decoration setting does not work on the Navigation block overlay or submenus

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37726]
### Description

The text decoration setting in the typography panel works for the standard navigation, but is not visible when a sub menu or the overlay menu is opened.

### Step-by-step reproduction instructions

1. Insert a navigation block
2. Enable either text decoration (underline or strike through)
3. Open the menu overlay and see that the links do not have the text decoration

(You need a theme that doesn't add extra styling to the links)

### Environment info

WordPress 5.9-RC1-52446

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
I think this is fixed in https://github.com/WordPress/gutenberg/pull/37963 ? Please reopen if I misundestand.
