### ISSUE TITLE
Improve the design of the post locking modal

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#37725]
I've noticed that the post locking modal presents some design problems we could address. 

![image](https://user-images.githubusercontent.com/4933/148238587-af7cbfe6-69cc-43bc-b75f-4452d447192e.png)

1. There's a big empty space before the message.
2. The username of the locked post is difficult to read. Highlighting it would improve its readability. 
3. The action buttons don't have a clear hierarchy (the tertiary action is sandwiched between the primary and the secondary ones).
4. We could explain what happens if the user decides to take over the post.
5. The modal that shows the other user's avatar doesn't show the username.

Here's a design proposal for this popover:

![image](https://user-images.githubusercontent.com/4933/148238646-c185833b-8d9e-4a7b-a839-a1109897a5fe.png)

Besides addressing the problems I've mentioned earlier, I've made some other changes:

1. I got rid of the dot at the end of the title and the redundant "User", and removed the title case of the "take over" button.
2. Since "taking over" is disruptive, I de-emphasize it and transformed it into a secondary action.
3. I right-aligned the actions and fixed the paddings.

[Figma file](https://www.figma.com/file/Srt2CR7UL76Col1dgL7XyJ/Post-Locking?node-id=201%3A181)

**Comment by karmatosed** [comment]
First, I love that this is getting some attention @javierarce so ✨ there.

I wonder though, could we go further? The bit that really gets me is the 2 actions on the same level. I understand they are a primary, secondary and tertiary style but they just feel so not great together. What could be the option to soothe that line of 'preview/take over/ exit the editor'?

**Comment by jasmussen** [comment]
Vast improvements. To echo Tammie a bit, I'd use at most two styles of buttons, for example primary and tertiary, or just three tertiary buttons. 

Good call unifying the case of "Take over", as we don't use titlecase in the editor. In that vein, should "Editor" be lowercase? Can it be simplified to "Exit editor" or perhaps even to just "Exit"?

**Comment by javierarce** [comment]
Thanks, @karmatosed & @jasmussen! I've refined the design using your feedback:

![image](https://user-images.githubusercontent.com/4933/148739665-24833b2d-f207-4e25-b8bc-d5ac9bdbb00b.png)

* To simplify the action row, I integrated the preview link inside the description.
* I changed "Exit the Editor" to "Exit editor" (I think writing just "Exit" could be confused with closing the modal)

From the two options on the bottom, I think the one on the left side (a tertiary plus a primary button) looks better and makes a better distinction between the options.

**Comment by jasmussen** [comment]
That looks great, I especially like the primary + tertiary one. I wonder, instead of linking "on this post" we could just output "(preview)" in parenthesis after? 

As a note to self mostly, it looks like the external link icon needs a figma update to become fill instead of outlines, as when scaled down the stroke should become a bit thinner as well.

**Comment by javierarce** [comment]
> That looks great, I especially like the primary + tertiary one. I wonder, instead of linking "on this post" we could just output "(preview)" in parenthesis after?

Good idea, let's try that, it'll be more clear. 

![image](https://user-images.githubusercontent.com/4933/148743378-f00e6810-f8d9-4cbe-9004-cb6fa2390da5.png)

> As a note to self mostly, it looks like the external link icon needs a figma update to become fill instead of outlines, as when scaled down the stroke should become a bit thinner as well.

True. Momentarily, I've updated the line weight on my Figma file.

**Comment by karmatosed** [comment]
@javierarce that's vastly better, thank you for taking the critique and running with it. I'd say :shipit: because it's so much better now and we can always build up.

**Comment by jasmussen** [comment]
I've started work in #37821, but note that many of the important details shown in the mockups above are not yet implemented, as some of the localization work can get gnarly. I'd appreciate help from anyone with skill in this area: feel free to push directly to the branch if you like.

**Comment by Mamaduka** [comment]
I created another follow-up PR to fix user avatar and display name issues.

What are the remaining items to close this issue?

**Comment by jasmussen** [comment]
I'll let Javier catch any details I missed, but it looks like there's an added paragraph: "If you take over, the other user will lose editing control to the post, but their changes will be saved."

**Comment by spacedmonkey** [comment]
Related: https://github.com/WordPress/gutenberg/pull/37789

**Comment by javierarce** [comment]
> I'll let Javier catch any details I missed, but it looks like there's an added paragraph: "If you take over, the other user will lose editing control to the post, but their changes will be saved."

Yes, I think that is the only thing left to close this issue.

**Comment by Mamaduka** [comment]
I will create the last PR for design changes shortly. We #37914 can merge separately.

**Comment by Mamaduka** [comment]
@javierarce this is how modal looks after applying remaining changes, including @jasmussen [suggestion for avatar](https://github.com/WordPress/gutenberg/pull/37914#issuecomment-1010955179) on top of the latest fixes.

![CleanShot 2022-01-13 at 17 02 29](https://user-images.githubusercontent.com/240569/149335494-b54b5533-4631-49c8-833c-688b1c089bcb.png)

**Comment by javierarce** [comment]
@Mamaduka would it be possible to place all the text on the same column? It would look cleaner.

![image](https://user-images.githubusercontent.com/4933/149366577-b663ccd2-d2c1-480c-8b24-078524b27bc7.png)
