### ISSUE TITLE
Minimum height of the cover block in Gutenberg has the unit "vw", more logical would be "vh".

### ISSUE THREAD

**Issue by annagson** [WordPress/gutenberg#37724]
## What problem does this address?
Gutenberg block "cover": When setting the cover's minimum height, the options are: px, em, rem and vw. The latter is the width of the viewport. "vh" is not an option.

## What is your proposed solution?
Add (or replace with) "vh", the height of the viewport.

**Comment by amustaque97** [comment]
Hey there! I would like to give it a shot :smile:

**Comment by chthonic-ds** [comment]
Previous issue with likely solution: https://github.com/WordPress/gutenberg/issues/36035

**Comment by amustaque97** [comment]
Hi, @ntsekouras , I saw you're working on the PR https://github.com/WordPress/gutenberg/pull/39145. 

Could you give me some insights about this issue! Does this issue require some action item?

Thank you

**Comment by ntsekouras** [comment]
👋 Thanks for creating the issue!

At first this seemed to me as duplicate of: https://github.com/WordPress/gutenberg/issues/36035 but I created a PR with a detailed description about this here: https://github.com/WordPress/gutenberg/pull/39383
