### ISSUE TITLE
Removing title support will partially hide the first block floating menu

### ISSUE THREAD

**Issue by amarinediary** [WordPress/gutenberg#37734]
### Description

When registering a new custom post type through [register_post_type()](https://developer.wordpress.org/reference/functions/register_post_type/), and setting the `support` parameter, removing the `title` core feature will partially hide the first page block floating menu.

### Step-by-step reproduction instructions

1. Remove support for the `title` feature from a post type.
```php
<?php

add_action( 'init', function () {

    remove_post_type_support( 'post', 'title' );

} );
```
2. Add a new post. 
3. The first block floating menu is partially hidden.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/7512732/148310282-6b322e50-666d-4469-818d-25a3bf6f98c5.png)

### Environment info

- Wordpress 5.8.2, matching Gutenberg on default theme.
- Chrome Version 96.0.4664.110 (Build officiel) (64 bits)
- Desktop Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/26239 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

**Comment by skorasaurus** [comment]
This should also be fixed if you are using the latest version of the block editor, [the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/). 

Please reopen if you are still experiencing this using the latest version of the block editor; ref https://github.com/WordPress/gutenberg/issues/26239#issuecomment-1011292860
