### ISSUE TITLE
Latest post block content jumps when switching between excerpt and full post

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37737]
### Description

When you add a latest post block and switch between showing excerpt and full post,
the text content changes position.

[The excerpt has margin set](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/latest-posts/style.scss#L49), but the post content (wp-block-latest-posts__post-full-content) does not:
```
.wp-block-latest-posts__post-excerpt {
	margin-top: 0.5em;
	margin-bottom: 1em;
}
```

### Step-by-step reproduction instructions

1. Add a latest post block
2. Display excerpt, then switch to Full post.
3. See the content move.

### Screenshots, screen recording, code snippet

![latest-posts](https://user-images.githubusercontent.com/7422055/148330124-e072930a-5dd9-42e4-84a5-6b4fa170158e.gif)

### Environment info

WordPress 5.9-RC1-52446

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Still present in WP6.3

**Comment by carolinan** [comment]
This was solved in https://github.com/WordPress/gutenberg/pull/66442.
