### ISSUE TITLE
Add has_block() function

### ISSUE THREAD

**Issue by ideadude** [WordPress/gutenberg#3773]
## Issue Overview

The idea is to add an has_block() function or similar to check if a post uses a specific block. This would be similar to the has_shortcode() function.

## Possible Solution

Implementation could be similar to the gutenberg_content_has_blocks() function:
https://github.com/WordPress/gutenberg/blob/9864a6092a965d2985307ed2456f83148a1dee78/lib/register.php#L370

This function is optimized for speed and simply uses strpos to check for `<!-- wp:`. has_block() could similarly check for `<!-- wp:blockname`. 

Alternatively, we could load all of the blocks for the post and loop through them until we found a block with that name. Maybe both implementations should be available (different functions or use a flag parameter) for different use cases.

**Comment by ideadude** [comment]
Pull request here: https://github.com/WordPress/gutenberg/pull/3781

Some notes that came up while working on this:
* These 2 functions along with gutenberg_post_has_blocks() and gutenberg_content_has_blocks() should probably be moved into /lib/blocks.php (hattip Riad)
* We should consider adding a block_exists() type function similar to shortcode_exists(). There is a way to do this on the JS-side I'm told. But when block registration is moved into the server side (good idea I think based on my 2 hour exposure to Gutenberg), we'll need a similar function. The shortcode/block analogy doesn't always hold up, but has_shortcode() and shortcode_exists() functions are important to plugin developers working on interoperability.

**Comment by tofumatt** [comment]
Closed in #9058.
