### ISSUE TITLE
WP 5.9: Some global styles strings are not translatable.

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#37743]
### Description

Hello, I found a few strings that are not translatable in the Global styles panel.

For example, "Add", "Add color", "Done" (…) strings. See screenshot below.

Context: using WP 5.9 RC 1, without Gutenberg plugin installed.

### Step-by-step reproduction instructions

1. Switch to a 100% translated WordPress Locale (example: fr_FR)
2. Go to global styles panel > colors > new color
3. See that some strings are not translated

### Screenshots, screen recording, code snippet

<img width="266" alt="Capture d’écran 2022-01-06 à 10 22 14" src="https://user-images.githubusercontent.com/1590998/148360780-1fdb25d6-bdab-437e-9b55-3c7a9fe284e2.png">

### Environment info

- WP 5.9 RC 1
- Gutenberg plugin NOT installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I can see that i18n functions are used with those strings.

Do you think there might be a problem when generation translation files?

https://github.com/WordPress/gutenberg/blob/f70f4664ac641bd107481c5c67ee6f5556a0a381/packages/components/src/palette-edit/index.js#L277-L296

**Comment by audrasjb** [comment]
Ah thank you, I didn't find the related file :)

Yes, this may be an issue with the translation file generator, because the string "Add color" doesn't exist at all in the translation packages.
https://translate.wordpress.org/projects/wp/dev/admin/fr/default/?filters%5Bterm%5D=Add+color&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by luminuu** [comment]
![grafik](https://user-images.githubusercontent.com/7585600/148654003-a0fd2f42-36b3-4dd7-b796-160f56322535.png)

Same with "Reset all" under the Typography section (here the german locale). This string also doesn't exist in any of the translation packages.

**Comment by grappler** [comment]
The translations exist for the mentioned strings in German.
![image](https://user-images.githubusercontent.com/1785641/151142474-a949ea99-b345-419a-a4c7-37a3517130aa.png)

![image](https://user-images.githubusercontent.com/1785641/151142634-8a84ce8d-bcfb-4ae9-944d-e49fb591edf8.png)

**Comment by Mamaduka** [comment]
Thanks for the confirmation, @grappler.

I think we can close this issue. It looks like this was a temporary issue with the translation file generator.
