### ISSUE TITLE
Site Editor regression - Redo is no longer available.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#37760]
### Description

After performing "undo" in the Site Editor the "redo" action is no longer available.

This was originally identified on v12.3.0 and is currently reproducible on the trunk branch.

### Step-by-step reproduction instructions

1. Load the Site Editor
2. Insert a block.
3. Click the "undo" button
4. Try to "redo" and notice the action is unavailable.

### Screenshots, screen recording, code snippet

![no-redo](https://user-images.githubusercontent.com/28742426/148437586-037f18cd-02c6-41a5-bfee-a54c4570d49d.gif)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Addison-Stavlo** [comment]
cc @youknowriad if you may have an idea about the regression or how to best triage this one.

**Comment by annezazu** [comment]
Noting that I can replicate in 5.9 RC1 :) Adding to 5.9 board.

**Comment by youknowriad** [comment]
This seem to be dependent on the content of the site editor, it doesn't happen consistently.
