### ISSUE TITLE
Editor gets locked after dismissing the link picker while having the software keyboard hidden

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#37773]
## Description

Dismissing the link picker without setting a link makes the editor get locked and prevents the user to interact with it and the app. This is a major issue as in order to keep using the app, the user would require closing and reopening it.

**UPDATE:** This issue only happens when the software keyboard is not displayed within the editor, like for example when an external keyboard is connected.

**NOTE:** ~~I couldn't manage to reproduce this behavior on Android so looks like it only affect the iOS version.~~ It can also be reproduced on Android by connecting an external keyboard and hiding the software keyboard.

I also confirm that this can't be reproduced on the latest WordPress app production version `18.8` and beta `18.9`.

## Step-by-step reproduction instructions

**Preparation:**
1. Connect an external keyboard to the device.
2. (Only on Android) Open the keyboard settings of the device and disable "Show on-screen keyboard" (see attached screenshot)
<img src=https://user-images.githubusercontent.com/14905380/148560072-158d95d6-2db1-4f2f-a39a-653da624add6.png width=200>

1. In a Paragraph block, tap on the Link button located in the formatting toolbar.
2. Tap on "Link to" item to open the link picker.
3. Tap on "Cancel" button to dismiss it.
4. Dismiss the block settings by tapping on the backdrop.
5. Observe that no interaction can be made on the editor and app.

## Expected behaviour

The editor and app should be interactable after dismissing the link picker.

## Actual behaviour

The editor and app get locked and prevent any kind of interaction after dismissing the link picker.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/148540767-23795e2b-3451-4b7f-8b11-5f52623eb172.mp4

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: Simulator - iPhone 12 Pro Max
- Operating system: iOS 15.0
- WordPress app version: develop

**Comment by fluiddot** [comment]
We've made further testing on iOS devices (iOS 14.7.1 and 15.1) and it couldn't be reproduced, so looks like this might be only affecting either using the Simulator or in development mode.

**Comment by antonis** [comment]
I confirm that I was able to reproduce the issue on a simulator (15.0) running Metro but not on a device (iPhone SE / iOS 14.7.1) running Metro.
<details>
<summary>I'm also getting a console error that might relate to the issue.</summary>

![IMG_0178](https://user-images.githubusercontent.com/304044/148555020-409579e3-4597-4542-9f3c-45498b95aa6f.PNG)
</details>

**Comment by fluiddot** [comment]
Upon further testing, we narrowed down the conditions for reproducing the issue to the presence of the software keyboard on iOS. This would limit the impact of the issue to devices where this keyboard is not displayed, due to for example having an external keyboard connected, which might be common when using the editor on tablets.

Additionally, I performed a test on Android by connecting an external keyboard and hiding the software keyboard, and I managed to reproduce the same issue there too. So this problem is not specific to iOS but to the presence of the software keyboard.

**Comment by fluiddot** [comment]
As @dcalhoun outlined in an internal discussion, this is most likely produced after the RN upgrade to 0.66 and related to potential unconsumed layout animations that can cause modals to become partially closed. This would be a good starting point for initiating investigations 👀 .
