### ISSUE TITLE
Consider iterating the styles for beta notifications and messaging

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#37784]
I will first say I am unsure if this should go here or needs to be iterated trac side. However, for now I am going to raise it here. It's also not a critical issue more one of clarity and potential confusion.

Right now you can end up with this in your menu:

![2022-01-07 at 16 43](https://user-images.githubusercontent.com/253067/148576953-e0492015-349f-4f32-8b56-718320217db2.png)

Which reads like 'warning beta'. We probably want a simple notice over having the full on notification style. However, the issue likely is there isn't another style to use (which is where this might not be something to fix here.

Beta messaging is important in the app and right now I don't think it's being totally optimised. It's easy to both alarm and be missed. Neither is ideal.

For example, in the site editor itself only global styles is flagged as 'beta'. When the entire thing is actually beta.

![2022-01-07 at 16 47](https://user-images.githubusercontent.com/253067/148577364-9a245e16-8a4c-4f1f-adff-699c297bbb8e.png)

## Possible actions
- Iterate the style to not be a notification for beta.
- Make the entire experience flagged as beta over just global styles.

**Comment by youknowriad** [comment]
Looks like this issue is not relevant anymore.
