### ISSUE TITLE
Using Block Alignment on Paragraphs Results in Buggy Editor Behavior

### ISSUE THREAD

**Issue by joshkoenig** [WordPress/gutenberg#3779]
## Issue Overview

Applying "Block Alignment" to text blocks can result in buggy editor behavior in an otherwise vanilla setup.

## Steps to Reproduce (for bugs)

1. Start a new post.
2. Create two paragraph blocks.
3. Give the second paragraph Block Alignment Left
4. Add a Text Column Block

At this point the text column block will appear out of place (half off the screen to the right), and a number of other things will be wonky. E.g. start adding an additional text block below and the editor will visually treat the two blocks as one "multi paragraph" block, which should be unpossible.

## Expected Behavior
I'm admittedly unclear of what block alignment is supposed to do in the context of a one-column layout, but the editor UI bugs seem like they may be symptomatic of some larger issues.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/143186/33528090-42870b0c-d821-11e7-9378-0feacf065068.png)

![image](https://user-images.githubusercontent.com/143186/33528092-4d782e24-d821-11e7-979f-1fa313604696.png)

**Comment by mtias** [comment]
I think we should just remove block alignments left/right from paragraphs. It floats them, but given the width remains the same now (it didn't use to), it just looks weird.

cc @jasmussen @karmatosed

**Comment by karmatosed** [comment]
> I think we should just remove block alignments left/right from paragraphs. It floats them, but given the width remains the same now (it didn't use to), it just looks weird.

I think if the width remains the same yes for now let's remove them.

**Comment by jasmussen** [comment]
Agreed, insofar as text is the smallest unit, and if we were to look at more advanced layouts in the future we might want to look at applying the block alignments to a container, instead of on the paragraph level.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521136821000794)._

**Comment by SuperGeniusZeb** [comment]
I think this issue can be closed now, as the original issue appears to be fixed and block alignment options will probably be removed from non-container blocks in the future.

**Comment by SuperGeniusZeb** [comment]
Paragraph blocks no longer support the block alignment option (or at least, the option is hidden and deprecated now), so can this issue be closed?
