### ISSUE TITLE
Consider reducing number of icons in sidebar

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#37790]
There are a lot of variations and interaction symbols in the sidebar, there were a few before global styles refresh and now it's getting quite intense. For example:

![2022-01-07 at 19 00](https://user-images.githubusercontent.com/253067/148593679-df893997-616f-4cd6-9132-21289d416df1.png)

There in this screenshot are 4 symbols someone has to learn and that seems like a lot to expect as a start. If we presume the open/close arrow is expected due to WordPress patterns, even those other 3 are adding a lot.

## Consider not having 2 symbols doing relatively the same thing

The '+' in typography reveals a menu:

![2022-01-07 at 19 03](https://user-images.githubusercontent.com/253067/148593906-ebb1d02a-93ff-41da-9de2-d5667120ce94.png)

So do the dots:

![2022-01-07 at 19 04](https://user-images.githubusercontent.com/253067/148593978-9eda96c4-2d56-47fc-bde0-82c2ddb710f0.png)

This is overly complex and whilst it might be something interim it needs resolving.

## Consider if some symbols even make sense

I would argue that this one doesn't make sense for the implementation and if it's just a format switch, having an icon seems a lot.

![2022-01-07 at 19 05](https://user-images.githubusercontent.com/253067/148594121-eed58fbd-73ef-4967-ac34-13469644767c.png)

## Proposal
Overall, I think considering the impact and assumptions of any icon being used for interactions in the sidebar is key so reviewing what we have and pairing down is good. There are a few focus points:

- Reduce where some have a double meaning.
- If have to use icon pick one make sense.
- Consider not even having icons.

**Comment by annezazu** [comment]
This recently merged PR might be welcome news, where it changes the  ➕ to only show it when all items are optional: https://github.com/WordPress/gutenberg/pull/38262

**Comment by karmatosed** [comment]
I am going to close this as work has gone on and continues to go on with side panel unification and the design system. As this is my own issue I no longer think having a separate issue is a valid use case in this repo.
