### ISSUE TITLE
It is difficult to find how to change the size of a featured image inside a query

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37799]
### Description

_This was first reported by stevekamn on WordPress slack._

When the post featured image block is placed inside a query and post template, the featured image is represented either
by a placeholder or the actual featured image.
These images have two different sets of controls, which makes it difficult to find how to change the size and scale.

If you happen to select the placeholder, you can only change the padding and margin.
To change the size and scale, you have to find a post or page in the post list that has an actual featured image, and select that.
So if your current list of posts does not include a featured image, this is a very confusing experience, and the feature is only discoverable by chance.

### Step-by-step reproduction instructions

1. Add a query block in the site editor.
2. Add a post featured image block to the post template inside the query.
3. With the feature image placeholder selected, open the block settings sidebar and open the dimensions panel.
Confirm that only the margin and padding controls are present.

### Screenshots, screen recording, code snippet

In the site editor, inside a query and post template block:
![inside query, the block only has padding and margin controls](https://user-images.githubusercontent.com/7422055/148637282-33a3f934-ac1a-4dcc-ba29-ae3cbf264822.png)

### Environment info

WordPress 5.9-RC1-52464

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
+1 to this issue. I've run into similar moments of confusion. Somewhat related work around the placeholder: https://github.com/WordPress/gutenberg/pull/36517 https://github.com/WordPress/gutenberg/issues/36136 and somewhat related issue around adding more controls: https://github.com/WordPress/gutenberg/issues/33789
