### ISSUE TITLE
`theme.json` custom properties not accessible via `getEditorSettings()` or `useSetting()`

### ISSUE THREAD

**Issue by andrewstaffell** [WordPress/gutenberg#37797]
### Description

I'd expect these functions to retrieve the custom properties advertised in the `theme.json` documentation, eg. 

```
{
    "version": 1,
    "settings": {
        "custom": {
            "line-height": {
                "body": 1.7,
                "heading": 1.3
            }
        }
    }
}
```

But apparently they don't?

### Step-by-step reproduction instructions

I'm testing both functions in the editor like this. Can't see any way to get the custom properties. They aren't among `settings` and `customProperty` is false or empty. 

```
import { registerPlugin } from '@wordpress/plugins';
import { PluginDocumentSettingPanel } from '@wordpress/edit-post';
import { useSelect } from '@wordpress/data';
import { useSetting } from '@wordpress/block-editor';

const PluginDocumentSettingPanelDemo = () => {
	const settings = useSelect(select => select('core/block-editor').getSettings());
	console.log(settings);
	const customProperty = useSetting('custom.lineHeight');
	console.log(customProperty);
}

registerPlugin( 'plugin-document-setting-panel-demo', {
    render: PluginDocumentSettingPanelDemo,
    icon: 'palmtree',
} );
```

### Environment info

WP 5.8.3
Gutenberg 12.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewstaffell** [comment]
My bad – it does work. I had a blank `custom: {}` property lower down the theme.json that was overwriting the other definitions.

**Comment by thirstycode** [comment]
Hi @andrewstaffell ,
I'm using a similar function in my plugin. Is there any API to set this fetched context?

`const customProperty = useSetting('typography.fontFamilies');`

Considering the above code, how can I update customProperty?
