### ISSUE TITLE
Keyboard shortcuts for headings do not work in Gutenberg

### ISSUE THREAD

**Issue by Wordpresslover** [WordPress/gutenberg#37796]
1. You select a text
2. Alt + Shift + 3 (or other number)
3. Nothing happens

That keyboard shorcuts for headings from official WP Manual do not work.
https://wordpress.org/support/article/keyboard-shortcuts/

Wordpress with Gutenberg requires 4 clicks to add a heading other then h2 to a selected text.

with 50 artcles a month, 6 heading per article - 1200 manual clicks have to be done - NIGHTMARE.

**Comment by talldan** [comment]
@Wordpresslover Not a fix for the reported issue, but a quick way to insert headings of a particular level in Gutenberg is to use the slash inserter.

In a new empty paragraph, If you type `/h4` and hit enter a h4 heading will be inserted

**Comment by bph** [comment]
@Wordpresslover 
Here is the documentation page for the Keyboard shortcuts available for the block-editor. 
https://wordpress.org/support/article/block-editor-keyboard-shortcuts/

Unfortunately. You are right that the shortcut that was working in the classic editor is not working on the block editor. 

Here is a workaround I have been using, to change existing text from a paragraph to a heading: 

- Place your cursor at the  beginning of the line,
- type the pound signs, ## for h2 and ### for h3 
- followed by a space. 

It gets automatically changed into the heading. 

You don't have to highlight the full line, just place the cursor at the beginning. It's also not a 1-key Shortcode but Markdown syntax. 

With a little practice, this might just be as fast if not faster as using the old shortcut. 

Here is a little video https://recordit.co/Ya6HGy2esZ

Hope, that helps. 

_PS: I updated the support page with a link to the Block Editor Shortcuts._

**Comment by bph** [comment]
@Wordpresslover I close this issue for now, unless my suggestion isn't a good replacement for your workflow. Please comment again here and I open up the issue again.
