### ISSUE TITLE
Support placeholder text for Editable component

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#378]
See image block mockups at #310

![image](https://cloud.githubusercontent.com/assets/1779930/24770315/84da1876-1ad7-11e7-982b-bd4f631e3dd9.png)

In order to show the default caption text "Write caption…" we need to be able to support a placeholder prop to the `<Editable />` component akin to the [`input` and `textarea` attribute of the same name](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/HTML5_updates#The_placeholder_attribute).

**Comment by BE-Webdesign** [comment]
Being worked on in #475.

**Comment by iseulde** [comment]
Added with #756.
