### ISSUE TITLE
The post featured image block displays two dimensions panels

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37800]
### Description

The post featured image has two dimensions panels; one for padding and margin, and one for width, height and scale.
I think the settings should display in the same panel.

### Step-by-step reproduction instructions

- Add a featured image to a post.
- Next, add the featured image block.
- Select the block and open the settings sidebar. Confirm that there are two panels.

### Screenshots, screen recording, code snippet

![two dimensions panels](https://user-images.githubusercontent.com/7422055/148638350-6c011927-e7ec-4658-be1c-84b065da830a.png)

### Environment info

WordPress 5.9-RC1-52464

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I see that this was fixed in #36540. Unfortunately, it looks like we missed it when picking up changes for beta.

I'm going to add backport to the minor release label.
