### ISSUE TITLE
Can't access property "ref", navigateRegionsProps is undefined

### ISSUE THREAD

**Issue by alessandrotesoro** [WordPress/gutenberg#37802]
### Description

Hi there,

I'm trying to use the `@wordpress/interface` package in a custom admin page but it's not working when the Gutenberg plugin is disabled. This is the error in the console:

```
Uncaught TypeError: can't access property "ref", navigateRegionsProps is undefined
```

Is there no way to use the interface package without the gutenberg plugin being active? 

### Step-by-step reproduction instructions

1. Deactivate the gutenberg plugin.
2. Create a custom admin page and enqueue the js assets.
3. Create the content of the page by using the `InterfaceSkeleton` component.

### Screenshots, screen recording, code snippet

```
import { InterfaceSkeleton, FullscreenMode } from "@wordpress/interface";

const AddPage = () => {
	return (
		<InterfaceSkeleton
			header={ <>header</> }
			secondarySidebar={ <>sec side</> }
			sidebar={
				<>side</>
			}
			content={
				<>
					content
				</>
			}
			footer={
				<>footer</>
			}
		/>
	);
}

export default AddPage
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hey @alessandrotesoro  - I know it's been a while, but I wanted to check if this is still an issue for you?

**Comment by jordesign** [comment]
With no further discussion here I will close the issue. If it still presents in some way - a new issue can be opened with updated details to reproduce.
