### ISSUE TITLE
Revert Font Family Support from various blocks for 5.9

### ISSUE THREAD

**Issue by luminuu** [WordPress/gutenberg#37826]
While testing 5.9 RC1 I found that the font family selection for paragraphs was not yet available. @carolinan and @bph mentioned the issue #37586, however, it was discussed to revert that feature as the Webfont API is not ready yet, so it got removed with PR #37815. 

While further testing I noticed that it is still in use by several blocks and to avoid unneccessary confusion in 5.9, I'd suggest to have it removed from those blocks as well:

- List
- Button
- Verse
- Navigation
- Post Title
- Archive Title
- Website Title
- Website Tagline

**Comment by annezazu** [comment]
cc @noisysocks for further review. Thank you for flagging this!

**Comment by noisysocks** [comment]
cc. @MaggieCabrera @aaroncampbell @apeatling

**Comment by ntsekouras** [comment]
I created a [quick PR](https://github.com/WordPress/gutenberg/pull/37911) for this, if we decide we want to revert for other 5.9 blocks too. IMO this makes sense, but want to hear other's thoughts too 😄

**Comment by ntsekouras** [comment]
Actually I saw that some blocks have this support from `5.8`, so I'm not really sure.. 🤔 

Example [here](https://github.com/WordPress/wordpress-develop/blob/5.8/src/wp-includes/blocks/list/block.json#L42).

**Comment by apeatling** [comment]
@mtias [comment](https://github.com/WordPress/gutenberg/pull/34064#issuecomment-959384115) specifically talked about making sure that font family was not a default control for these blocks when they are inserted. Blocks that already have font family could keep the support for it.

With the introduction of Tools Panel all of these blocks have font family hidden by default, so I think they are okay to leave as-is.

**Comment by ntsekouras** [comment]
>@mtias comment specifically talked about making sure that font family was not a default control for these blocks when they are inserted. Blocks that already have font family could keep the support for it.

Sounds good. There is no block with `font family` control set as default, so I guess we can close this issue, no?

**Comment by apeatling** [comment]
Yes good to close. :+1:
