### ISSUE TITLE
InspectorControls: Custom panel will be placed before Typegraphy panel

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#37845]
### Description

I hooked up the `editor.BlockEdit` and added my own `InspectorControls` as follows.

```javascript
const withInspectorControls = createHigherOrderComponent((BlockEdit) => {
  return (props) => {
    return (
      <>
        <BlockEdit {...props} />
        <InspectorControls>
          <PanelBody title='My Control'>My Control</PanelBody>
        </InspectorControls>
      </>
    );
  };
}, 'withInspectorControl');
addFilter('editor.BlockEdit', 'wpse', withInspectorControls);
```

It will be placed after all core panels, i.e. just before the Advanced panel in wordpress 5.8.3

However, for some reason, it is placed between the core panels, i.e. in front of the Typography panel in WordPress 5.9 (RC-1).

I have read the documentation and source for `InspectorControls`, but I could not understand why this behavior occurs.
Is there any way to place my own `InspectorControls` after all the core panels?

### Step-by-step reproduction instructions

Please look at the code in the description.

### Screenshots, screen recording, code snippet

![capture](https://user-images.githubusercontent.com/54422211/148886119-938a8130-b30d-49a7-b25f-152d15925c26.png)

### Environment info

- WordPress 5.8.3 and 5.9 RC-1
- Gutenberg 12.3.0（I tested both with the gutenberg plugin enabled and disabled.）

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ddryo** [comment]
I can still reproduce it with 5.9-RC3.

**Comment by ddryo** [comment]
I can still reproduce it with 5.9-RC4.

**Comment by t-hamano** [comment]
I have checked this issue again and the block sidebar is now split by tabs, e.g. #45005. Also, in #47105, the `styles` slot has been added, so this problem should not occur. I would therefore like to close this issue.

![inspectorcontrol](https://user-images.githubusercontent.com/54422211/216492502-22b17d9f-a18c-4454-a738-8438afab6f05.png)
