### ISSUE TITLE
Changing the unit or value of dimension controls sometimes doesn't work in the site editor

### ISSUE THREAD

**Issue by erikjoling** [WordPress/gutenberg#37856]
### Description

When I set the value or unit of the padding or margin of a block and try to change it, it reverts to the initial value/unit. 

### Step-by-step reproduction instructions

1. In the site editor go to a group block for example. 
2. Try to set the bottom padding to 5 rem.
3. Save
4. Now try to set the bottom padding to 1 px. Or to 0.
5. It reverts to 5 rem.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/20614110/148918713-c3dc804a-45f8-47b5-9414-2683a12c91e9.png)

### Environment info

- WordPress 5.9 RC-1
- Firefox
- Ubuntu

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by dianeco** [comment]
I've encountered similar issues. 

When you try to remove a value (by hitting backspace), it keeps the previous value and does not remove it. The user must hit backspace and then Enter to remove a value. Which is not consistent with the way the user can add a value (no need to hit Enter). Moreover, sometimes, when you try to reset all the values, nothing happens, or only some values are reset.
 
![remove-values](https://user-images.githubusercontent.com/44895380/148927485-8f5d7d1d-0eb8-4bd2-84e1-6d8d82c9f75f.gif)

Sometimes when you save, the values saved are different from what was indicated before saving.

![saved-values](https://user-images.githubusercontent.com/44895380/148927519-3882d252-e1be-4a79-af25-e2c190619c2b.gif)

**Comment by erikjoling** [comment]
For me the problem seems to be more present in firefox. Though removing a value in chrome also is troublesome.

The problem isn't limited to the group block by the way.

**Comment by dianeco** [comment]
I've encountered all the above issues on Chrome, using Mac or Windows.

**Comment by akasunil** [comment]
@erikjoling I have tested it with latest trunk and works fine.

**Comment by erikjoling** [comment]
This still doesn't work for me. Looking at issue #41845 the problem seems to be linked to Firefox. Just tested Chrome for a second and it worked as expected. 

@dianeco Does this problem still exist for you in Chrome?

I'm fine with closing this issue in favor of #41845

**Comment by t-hamano** [comment]
@erikjoling 

We were able to solve this problem with #42483.
After testing again, we no longer reproduce this issue and would like to close it.
If the issue has not been resolved, please feel free to reopen it.
