### ISSUE TITLE
Bottom sheet: Long labels make items to be cut off [only on Android]

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#37858]
## Description

On Android when an item (cell component) of a bottom sheet contains a long label, the content of the item gets cut off. I managed to reproduce this when setting the device's locale to Spanish and opening the block settings of an Embed block.

**NOTE:** On iOS this behavior can't be reproduced so this issue is specific to Android.

## Step-by-step reproduction instructions

**Preparation:**
Since this issue can only be reproduced on Android, so an Android device/emulator is required for testing it.

1. Change the device's locale to Spanish (any language that usually requires more space than English should work, i.e. Spanish, Portuguese or French).
2. Open a post/page.
3. Add an Embed block.
4. Set a YouTube URL (example: `https://www.youtube.com/watch?v=ssfHW5lwFZg`), this is required to display the media settings.
5. Open the block settings.
6. Observe that the item with the label "Resize for smaller devices" (the first one under the Media settings section) is cut off.

## Expected behaviour

Items within the bottom sheet modals should display their entire content.

## Actual behaviour

Items within the bottom sheet modals can be cut off if they have a long label.

## Screenshots or screen recording (optional)

**Android (content is cut off):**

Screenshot|Video capture
--|--
<img src=https://user-images.githubusercontent.com/14905380/148925507-a0860a3e-7dd7-442a-a45f-fdc2f9a29eb1.jpg width=300>|<video src=https://user-images.githubusercontent.com/14905380/148925543-1384c1d6-dd41-4e5d-a12e-b6ae83bd3f12.mp4>

**iOS (content is NOT cut off):**
<img src=https://user-images.githubusercontent.com/14905380/148925750-2a87ae39-1691-43d3-ae60-20c12189ad84.PNG width=300>

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: Samsung Galaxy S20 FE 5G
- Operating system: Android 11
- WordPress app version: 18.9 (1148)

**Comment by hypest** [comment]
👋 @dcalhoun , you probably have some bandwidth available to dive into this issue? Let me know if this doesn't lend itself too much for you picking it up. Thanks!

**Comment by dcalhoun** [comment]
> 👋 @dcalhoun , you probably have some bandwidth available to dive into this issue? Let me know if this doesn't lend itself too much for you picking it up. Thanks!

@hypest yep! Happy to work on addressing this issue.
