### ISSUE TITLE
Default custom color doesn't get saved

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#37861]
### Description

Probably a minor bug, but if a user adds a custom color and doesn't move the color picker or change its name, the color is not saved. 

### Step-by-step reproduction instructions

1. Go to the Global Styles
2. Edit the theme palette
3. Add a custom color by clicking the + icon
3. Click done without modifying anything 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4933/148929243-63d53712-a2a2-4a50-8be5-bf80bd420b88.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
How strange! Seems similar to this previous problem (just to connect some dots): https://github.com/WordPress/gutenberg/issues/36473

**Comment by javierarce** [comment]
Thanks, Anne! It could also be somehow related to [this PR](https://github.com/WordPress/gutenberg/pull/37496#pullrequestreview-835917787)

**Comment by t-hamano** [comment]
I, too, think this behavior can be treated as a bug.

In the current spec, if the color palette name conforms to the rule of `Color {number}` and is the default color (`#000`), then it is considered a temporary color and that color is removed when the "Done" button is pressed.

https://github.com/WordPress/gutenberg/blob/ab97d28a55b028139b66b8199d795445d830cad8/packages/components/src/palette-edit/index.tsx#L260-L270
