### ISSUE TITLE
Invisible Open save panel only visible in focus in the global styles section

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#37892]
### Description

**Note: this is a copy paste from a Trac ticket.**

> Go to Styles in the Site Editor (Right Panel at the top)
> Click on blocks
> For example, select Quote block
> Select typography
> Here, you won't see any button Open save panel. But when you try navigating via keyboard, then you can see that button.

See the following Trac ticket for more details and screenshots on the issue: https://core.trac.wordpress.org/ticket/54744

### Step-by-step reproduction instructions

See the following Trac ticket for more details and screenshots on the issue: https://core.trac.wordpress.org/ticket/54744

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
It's unclear to me if this is a bug :D Going to flag it for 5.9 to be safe.

**Comment by noisysocks** [comment]
I don't believe this is a bug. The hidden button is near to the end of the page DOM for assistive technology users to be more easily able to access the save panel.
