### ISSUE TITLE
Shortcodes are not working in page templates in the new "Beta" editor

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#37890]
### Description

**Note: this is a copy-paste of a ticket opened on Trac.**

> The shortcode block does not transform the shortcodes in the page template of the new "beta" editor (located at Appearance > Editor (beta)) of the full site editing when the shortcode is added to the "content" area, not into the "Header" or "Footer". (It works fine from these two.)

See the related Trac ticket for further details: https://core.trac.wordpress.org/ticket/54759

### Step-by-step reproduction instructions

See the related Trac ticket: https://core.trac.wordpress.org/ticket/54759

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
This was fixed in #37545.

We also found that running `wptexturize` (and maybe `do_shortcodes`) after the `do_blocks` might have some unexpected results - https://github.com/WordPress/gutenberg/issues/37754#issuecomment-1007345915
