### ISSUE TITLE
Preview for the 404 page similar to preview for other pages

### ISSUE THREAD

**Issue by oglekler** [WordPress/gutenberg#37896]
## What problem does this address?
How the page looks in the Editor and how the page looks on the front end can be very different. Users will be expecting the same behaviour with the ability to preview changes of the 404 page as with other pages.

## What is your proposed solution?
To add a front end preview for the 404 page.

![404](https://user-images.githubusercontent.com/16874687/149014306-c467791f-fc13-4b7e-a333-caa7718fdaee.gif)

**Comment by devinmaeztri** [comment]
Hello @OlaIola!  

Could you please add more information/screenshots about the difference you see on the front end currently, and the changes you expect to see?

Thanks!

**Comment by adamwoodnz** [comment]
Closing following triage policy
