### ISSUE TITLE
Blocks can get published without a Style, but once you select a Style, you can never de-select a Style

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#37897]
### Description

Take, for example, the Table Block - which has Default and Stripes as Styles by default.

If I add a Table Block to a Page and publish it, I have a Table with no style selected.

<figure class="wp-block-table"> (with no is-style-xxx)

However, once I click on Default or Stripes, I can never NOT have a style selected again. The UI simply doesn't support it. I can only toggle between the two Styles.

This feels incredibly inconsistent. Either I should be able to have a Table Block with no style (and be able to select that in the UI), or I should NOT be able to have a style-less Table Block and one should always be applied. I should NOT be permanently locked into a Style once I try one.

### Step-by-step reproduction instructions

1. Add a Table Block.
2. Publish the Post.
3. See that the Table Block has no style in the markup <figure class="wp-block-table"> (with no is-style-xxx)
4. Edit the post, and select a Style.
5. See that you can no longer get back to a style-less state with the UI.

### Environment info

WordPress 5.8.3 (and 5.9-RC2). Not using the Gutenberg plugin. Confirmed on 2021 theme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Hey @MadtownLems. I could be missing something but, from what I understand, the Style options automatically are set to "default". For example, if I add an image block, it's automatically set to Default but I can switch to Rounded and back again. This is also the case, from what I can see, with the Table block, Buttons block, and more. Is your issue about the UX of this or the fact that you want to have something other than the Default as the initial option or something else entirely?

Thanks for following up with extra info so I can better understand!

**Comment by MadtownLems** [comment]
When you first add the Table Block, the UI actually SHOWS 'Default' as selected. However, if you just publish the post, you'll see the table doesn't actually have the "is-style-regular" class. If you click on the already-selected 'Default' style, and publish/update the post, only NOW does the table have the "is-style-regular" class.

thanks for the quick reply - let me know if you still need more info!

**Comment by annezazu** [comment]
Ah ha! Thanks for clarifying. I'll update the labeling and see if others can provide more context as to why it's setup like this :)

**Comment by glendaviesnz** [comment]
It is possible to remove the `is-style-x` under the advanced tab in block settings panel, but this isn't at all obvious - a 'Clear' option might be useful in the Styles tab, but I am not aware of why it initially defaults to 'default' but doesn't add the class, so not sure of the implications of adding this.
![styles](https://user-images.githubusercontent.com/3629020/149046461-f08cdcab-dc76-417c-bb55-94b3bdedcaca.gif)

**Comment by talldan** [comment]
This is a flaw of the way default styles work in the style variations system. Not an easy issue to fix unfortunately, as previously attempted fixes have broken styles provided by plugins.

It was also reported at https://github.com/WordPress/gutenberg/issues/20706, so I'll close this as a duplicate.
