### ISSUE TITLE
Add code editor to Site Editor

### ISSUE THREAD

**Issue by CalumChilds** [WordPress/gutenberg#37909]
## What problem does this address?
This addresses the problem of having to export the theme each time you want to see class names or what may be causing a problem in the template.

## What is your proposed solution?
Make the code editor accessible in the Full Site Editor.

**Comment by carolinan** [comment]
Hi!
I am closing this as a duplicate of https://github.com/WordPress/gutenberg/issues/22528 and https://github.com/WordPress/gutenberg/issues/21245

See the pull request at https://github.com/WordPress/gutenberg/pull/37765
