### ISSUE TITLE
Gutenberg crash if custom post type has template lock

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#37912]
### Description

I create a custom post type with template lock. All works great, but if I select patterns on block inserter Gutenberg crashes.

I think the problem is template lock, because disabling it, all works great.

### Step-by-step reproduction instructions

1. Create a simple custom post type and set a template lock:

```		
'template' => array(
    array( 'core/paragraph' ),
),
'template_lock' => 'insert',
```
2. Go to your cpt and select block patterns
3. Gutenberg crash 
4. If you are lazy, simply download my [Popper plugin](https://wordpress.org/plugins/popper), try to disable the template lock and all works as expected.

### Environment info

- WordPress 5.8.3
- TwentyTwentyTwo theme
- Clean install

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hello, @Tropicalista

How are you inserting the pattern? The `template_lock` disables block inserter.

Am I missing any details?

## Screenshot
![CleanShot 2022-01-13 at 12 15 24](https://user-images.githubusercontent.com/240569/149291863-3e5da76c-a36c-422a-a766-fa41cdd21291.png)

**Comment by Tropicalista** [comment]
I have probably messed up something. I was testing the 5.9 release candidate.

Once the custom post type is created, the button is disabled. But if I try to insert a child block the pattern is enabled and should work. This was working great on 5.8.3.

You can test it using my plugin: https://wordpress.org/plugins/popper/

**Comment by t-hamano** [comment]
I have confirmed that this issue occurs not only with custom post types.

If `template_lock` is set to `insert`, the block should be locked and the inserter should be disabled.
But in the column block, it is unlocked and the editor crashes when the pattern is inserted.

I think blocks should not be able to be inserted at either level of hierarchy

## Testing Instruction

- Insert a column block and one paragraph block on the post editor.
- Activate `template_lock` with the following code:

```php
function custom_registered_post_type_post( $post_type, $post_type_object ) {
  $post_type_object->template = array(
    array( 'core/paragraph' )
  );
  $post_type_object->template_lock = 'insert';
}
add_action( 'registered_post_type_post', 'custom_registered_post_type_post', 10, 2 );
```

- Reload the post editor and confirm that **the paragraph block is not locked**.
- Press Enter to confirm that a new paragraph is created and **the block inserter is activated**.
- Selecting a pattern from the inserter will crash the editor.

https://user-images.githubusercontent.com/54422211/180800337-73860335-170f-47f5-94a0-39d99e62a6c1.mp4

## Error Info

```
pattern-panel.js:68 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at PatternInserterPanel (pattern-panel.js:68:31)
    at renderWithHooks (react-dom.js?ver=6.0.1:15015:20)
    at mountIndeterminateComponent (react-dom.js?ver=6.0.1:17841:15)
    at beginWork (react-dom.js?ver=6.0.1:19079:18)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=6.0.1:3942:16)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=6.0.1:3991:18)
    at invokeGuardedCallback (react-dom.js?ver=6.0.1:4053:33)
    at beginWork$1 (react-dom.js?ver=6.0.1:23994:9)
    at performUnitOfWork (react-dom.js?ver=6.0.1:22806:14)
    at workLoopSync (react-dom.js?ver=6.0.1:22737:7)
```
