### ISSUE TITLE
Deleting template or template part causes screen flash in Site Editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#37926]
### Description

When deleting a template or template part, the screen flashes upon deletion. It's a bit jarring of an experience! 

### Step-by-step reproduction instructions

1. Create a new template from the Site Editor.
2. Head to the template list and delete it. 
3. See the flash on the screen.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/149214443-e7c17376-ff5d-45aa-9386-8750c02e9abb.mov

### Environment info

- WordPress 5.9 RC2
- No GB
- TT2
- Chrome
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
This still happens in 5.9.

**Comment by youknowriad** [comment]
This happens probably because the request is retriggered. It's easy enough to keep the list visible but I guess we should show some feedback that the request is in progress. Might need some design here.
