### ISSUE TITLE
Duplicate style and svg

### ISSUE THREAD

**Issue by lwangdu** [WordPress/gutenberg#37927]
### Description

I am using WordPress  5.9 CR2 and Theme TT2. I am seeing duplicate style and http://www.w3.org/2000/svg as you can see on the screenshot.
![Screen Shot 2022-01-12 at 12 39 39 PM](https://user-images.githubusercontent.com/24829573/149219824-c7f27a6b-7c03-4b2c-8448-72a1348242c0.png)

### Step-by-step reproduction instructions

Go to the frontend the site
inspect > Elements

### Environment info

WordPress  5.9 CR2 and Theme TT2.
All the plugins are deactivated.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 
Thanks for reporting; I believe the duplicate styles were mostly resolved in https://github.com/WordPress/gutenberg/pull/40875 ; 
(also ref https://github.com/WordPress/gutenberg/issues/41434 )

Are you able to reproduce this after you have installed and activated the newest version of Gutenberg that is available through [the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/)? 

The SVG issue is currently being tracked at https://github.com/WordPress/gutenberg/issues/38299

**Comment by kathrynwp** [comment]
Hi there @lwangdu - since we have not heard back from you since the last ping, I'm going to go ahead and close this out. If you feel it should be reopened, please comment here and I'll be glad to come back to it!

**Comment by lwangdu** [comment]
Thank you @kathrynwp  Please closed the ticket.
