### ISSUE TITLE
Make Top Toolbar position in template part focus mode to be consistent with other editors

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#37946]
When you enable the "Top Toolbar" option it appears like so when editing a template part in focus mode:

<img width="1532" alt="Screenshot 2022-01-13 at 10 54 25" src="https://user-images.githubusercontent.com/846565/149317787-3f893042-1024-478d-8879-48c708d3cd70.png">

This looks a little strange. It might be better to do something like:

<img width="1686" alt="Screenshot 2022-01-13 at 10 57 14" src="https://user-images.githubusercontent.com/846565/149317833-ca0da109-9f12-4795-901c-c59002318274.png">

This would make it consistent with other editors, including the template editor which also utilises the dark frame:

<img width="1689" alt="Screenshot 2022-01-13 at 11 01 30" src="https://user-images.githubusercontent.com/846565/149318374-8e07ecc1-3c28-4cde-a06e-b2488868fa55.png">

**Comment by jasmussen** [comment]
Definitely better! Tangentially to this, a while back I explored what it might look like if the option still fixed the toolbar to the top, but still retained the same visual appearance of the floating version. The primary benefit would be an identical toolbar design that remained consistent across mobile and tablet previews as well. I ultimately feel these mockups were not succesful, but wanted to share in case they inspired better solutions. 
<img width="1440" alt="Top Toolbar" src="https://user-images.githubusercontent.com/1204802/149497995-16361b7a-6d32-4db5-bdff-aca426516466.png">
<img width="1440" alt="Top Toolbar, Mobile" src="https://user-images.githubusercontent.com/1204802/149498009-42288e34-f6a9-4e7a-a1bf-52bda44452df.png">
<img width="1440" alt="Top Toolbar, Template Editor" src="https://user-images.githubusercontent.com/1204802/149498013-d2b4c22e-f927-4d1e-966c-6a29ed7d78f1.png">

**Comment by jameskoster** [comment]
At some point I think it might be beneficial to evaluate the full scope of the top bar, and consider a more intentional / scalable design. Since it was originally implemented we've added so many features, not to mention new editing contexts. It feels a little bit like a soap box car right now :D

**Comment by mtias** [comment]
Related #40450.

**Comment by jordesign** [comment]
I'm seeing the tools appearing in the very top of the editor - even in the focus mode for template parts - so I'm going to close this issue as no longer reproducible.

<img width="1728" alt="Screenshot 2023-09-14 at 8 54 53 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/500a3e57-f120-4805-afa2-146f918d8468">

**Comment by jameskoster** [comment]
Thank you @jordesign!
