### ISSUE TITLE
Latest major version of Gutenberg (v1.8) no longer displaying content

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3794]
## Issue Overview
Since updating to the latest major version of Gutenberg (v1.8), I now have 11 Posts/Pages out of approximately 20 samples that I'd created, that no longer display any content. All these pages had some content in them previously, but now they don't show anything.

![gutenberg-nocontent](https://user-images.githubusercontent.com/2078245/33533177-8c538bf2-d8f3-11e7-9dda-853b43a68ae2.png)

If I click on the Code Editor view, this is the content that I can see, that isn't being displayed.

![gutenberg-nocontent2](https://user-images.githubusercontent.com/2078245/33533212-b427dab6-d8f3-11e7-8d54-631c2112be19.png)

This content was displaying fine prior to updating to v1.8

## Steps to Reproduce (for bugs)
1. Update to v1.8
2. Check for pages no longer displaying correctly

## Expected Behavior
I would expect my content to still exist after updating versions.

## Current Behavior
A significant number of pages are no longer rendering properly.

_Gutenberg 1.8.1
Firefox Quantum 57.0 (64-bit)_

**Comment by karmatosed** [comment]
I am struggling to recreate this, could you provide a little more information please. For example, are you using Twenty Seventeen? What plugins do you have active? Yes they shouldn't interfere, but they maybe are.

Could you also try 1.9 and see if you still get the same issues?

**Comment by maddisondesigns** [comment]
@karmatosed I just updated to v1.9 and still seeing the same issue on some pages. I did notice though, if I refresh the browse window after the page is initially loaded, it then seems to load correctly.

I'm using the Gutenberg theme, and the only plugins activated are Gutenberg (1.9.0), WooCommerce (3.2.5) and ACF Pro (5.6.7).

**Comment by danielbachhuber** [comment]
@maddisondesigns Were you able to track down the source of this issue?

**Comment by maddisondesigns** [comment]
@danielbachhuber You may as well close this. Pages seem to be opening up more consistently now. I cant replicate this at the moment.

What's more concerning is why I lost multiple pages of content (#3448). This was raised over 2 months ago.
