### ISSUE TITLE
Links with another page with anchor link not working in Gutenberg button block

### ISSUE THREAD

**Issue by base-creme** [WordPress/gutenberg#37960]
### Description

When adding anchor link to gutenberg button block, link is desactivated.

### Step-by-step reproduction instructions

1. Create button with block button
2. Enter name of a page (https://mysite.com/products)

Link works

1. Add anchor to link (https://mysite.com/products#latest)

Link doesn't work anymore.

### Environment info

Gutenberg 12.3.2
Wordpress 5.8.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@base-creme I tested and couldn't reproduce an issue. Would you be able to share some screenshots of what you're seeing in the editor for the link?

**Comment by base-creme** [comment]
Here is a short video to illustrate the issue.
The link in BO works well to the page with anchor.
When I update the page, the link is the right one but when I click on the CTA, nothing happens…
If I remove the hashtag, no problem in front.

https://user-images.githubusercontent.com/53814375/149664410-f6a4511e-e97e-49ee-8429-453f2077be74.mov

**Comment by talldan** [comment]
I'm afraid I still can't reproduce it. The video does help my reproduction steps (I now know you're talking about the link in the editor), but I still can't see what happens for you as the video's dimensions are very short and wide.

When you click the link, what's the URL in the address bar?

**Comment by base-creme** [comment]
Here it is : <img width="573" alt="Capture d’écran 2022-01-17 à 08 49 15" src="https://user-images.githubusercontent.com/53814375/149728698-2901fd69-237f-464c-9419-fc0be27a095d.png">

**Comment by talldan** [comment]
Thanks. It looks like the link is correct then.

It's probably an issue with your destination page, does it have the `form` id or name correctly specified?

**Comment by base-creme** [comment]
Thank you for you help, I really appreciate it.
The destination page has the id form. You see it when I tried the link in the back-office. It leads directly to the anchor in the destination page
<img width="1680" alt="Capture d’écran 2022-01-17 à 08 54 49" src="https://user-images.githubusercontent.com/53814375/149729668-2584bf37-a70e-4e89-969c-536b414770e3.png">
.

**Comment by talldan** [comment]
Sorry I can't be of much further help. The only other suggestion is that maybe your theme or a plugin is preventing the click events on the link from working. You could try disabling plugins or trying a different theme to see whether you can isolate the issue.

**Comment by adamwoodnz** [comment]
Closing following triage policy
