### ISSUE TITLE
Block themes that support the customizer has two Editor links under appearance

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37971]
### Description

When you activate a block theme that has support for the customizer, for example Blockbase, and you also activate Gutenberg, there are two links to the Editor.
One to wp-admin/site-editor.php and one to wp-admin/themes.php?page=gutenberg-edit-site

### Step-by-step reproduction instructions

1. Activate the themes "Aino" or "Blockbase" from the theme directory
2. Activate Gutenberg
3. View the links under the Appearance menu item in the WordPress admin

### Screenshots, screen recording, code snippet

![The appearance menu shows two links](https://user-images.githubusercontent.com/7422055/149459250-40a36fa7-56bc-49af-bb4f-7983e3b8db02.png)

### Environment info

WordPress version 5.9-RC2-52567
Gutenberg current trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Pinging @ellenbauer @kjellr in case these are theme issues.

**Comment by kjellr** [comment]
I haven't looked into this personally, but I believe @pbking found that in the case of Blockbase, this was a theme issue. There's a PR here that fixes it: https://github.com/Automattic/themes/pull/5303.

**Comment by Mamaduka** [comment]
Aino theme had a similar issue. So I've created PR downstream.
