### ISSUE TITLE
Columns block: blockGap enabled in theme.json but no "Block spacing" control in "Dimensions" panel

### ISSUE THREAD

**Issue by alexandrebuffet** [WordPress/gutenberg#37977]
### Description

The blockGap option for the Columns block appeared to have been introduced with [#34630](https://github.com/WordPress/gutenberg/pull/34630), but the "Block spacing" control no longer appears in the Dimensions panel.

Tested up with WordPress 5.9-RC2 and Twenty Twenty-Two, only padding and margin controls shows up.

On WordPress 5.8.3 + Gutenberg 12.3.2 and a custom block theme, even with `"blockGap": true` in `theme.json` only padding and margin controls shows up.

### Step-by-step reproduction instructions

1. Add the Columns core block in a page or template
2. "Block spacing" control no longer appears in the Dimensions panel

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/43843473/149502281-5f5a5708-c7fb-4b21-9ac6-d4f47ebb8f1b.png)

### Environment info

- WordPress 5.9-RC2 with Twenty Twenty-Two
- WordPress 5.8.3, Gutenberg 12.3.2 with Custom Block Theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
This is due to this change: https://github.com/WordPress/gutenberg/pull/37360#issuecomment-1001543631 A fix will come in 12.4: https://github.com/WordPress/gutenberg/pull/37436
