### ISSUE TITLE
[Color Picker] Make custom HEX text field available without a click

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#37981]
Currently (Gutenberg 12.4), the color value inputs are not available unless you click on the "Show detailed inputs" button. If you don't click that button, click on the hex value shown, you'll activate a "Copy" action. 

![inputs](https://user-images.githubusercontent.com/1202812/149522617-86ca10ed-eaaa-4311-95a5-6a2e5af9541c.gif)

Users who want to input their own custom HEX values need to learn to hit that icon before they can modify the current HEX value. I've found this to be confusing personally — more often than not, I'm coming here to _input_ a custom value, not _copy_ one, and I have to do an extra click to make that happen. Besides, the copy action feels a little over-engineered: it's generally common to copy/paste content from a standard form field. 
 
I'd suggest we just go ahead and show the detailed inputs by default: 

<img width="549" alt="Screen Shot 2022-01-14 at 8 31 26 AM" src="https://user-images.githubusercontent.com/1202812/149523272-68f7f360-5065-46b9-b552-be59e263724b.png">

... and if we really want a copy action, we can display it where the "Show detailed inputs" button currently lives: 

![Group 657](https://user-images.githubusercontent.com/1202812/149523973-cad54517-6359-4939-8f01-4aaa84f7f672.png)

(We'd need a new icon though, I just borrowed the "Pages" icon for now)

**Comment by jasmussen** [comment]
This makes sense to me. Designwise, one thing we could do is keep the interface as is, only let the hex code be editable on click, and then surface a copy icon inside the input field when it's focused?

**Comment by supernovia** [comment]
>  then surface a copy icon inside the input field when it's focused?

I like that. Can we be sure the copy format [matches what one should paste](https://github.com/WordPress/gutenberg/issues/37018), or better, make the input field automatically handle hex code whether or not there's a # in front?

**Comment by dozentis** [comment]
Nice, that you mentioned this issue, I am also annoyed by this  and wanted to report. (I had to recolor 10 blocks lately, and when inserting the hex value, I kept accidentally coming up with copy instead of edit

Four clicks and a long way with the mouse to paste a color value from clipboard. (screenshot WP5.9.1)

![colorpicking1](https://user-images.githubusercontent.com/98828023/155534040-185a19de-af23-45c4-8225-43b5c2b84d6d.jpg)
)

**Comment by dozentis** [comment]
My suggestion for quicker copying the color-value

![copy-color](https://user-images.githubusercontent.com/98828023/155534633-5e33c800-402d-4d8f-9443-97d841e507e5.jpg)

**Comment by dozentis** [comment]
And there is a little bug when copying a color by click from there and paste to another place. If you paste a copied color you'll notice that it pastes the hex sign too and the color becomes invalid.

![colorpicker-paste-bug](https://user-images.githubusercontent.com/98828023/155537502-f9c4d2e9-3c0b-4d94-bb65-a7655d586209.jpg)

**Comment by aaronrobertshaw** [comment]
The two main issues here should now be resolved with #41222 and #41223 landing.

- #41222 
    - A new copy button was added for all color models as you otherwise cannot easily copy the non-hex colors
    - It made sense to keep that copy button consistent 
- #41223 
    - This PR improved the UX around pasting hex values into its input field
