### ISSUE TITLE
"admin_footer" action is done twice

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#3798]
When loading the post edit page, the `admin_footer` action is called twice, once when loading the page and a second one when loading the metaboxes. 

For both of those cases `did_action` returns `1`.

If there is not a way to detect that the second `do_action('admin_footer')` is done when loading the metaboxes, I think we need to prevent things from being done twice.

**Comment by youknowriad** [comment]
This could probably be fixed by #3616

**Comment by kmgalanakis** [comment]
Thanks for the prompt answer, @youknowriad. Let me test this.

**Comment by kmgalanakis** [comment]
Yes, I confirm that #3616 fixes that, thanks! 😄

**Comment by youknowriad** [comment]
Let's leave it open until it's merged ;)
