### ISSUE TITLE
[Post Comments] Unnecessary code comments are output to the front end

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#37989]
### Description

The Post Comments block outputs unnecessary HTML comments on the front end. Most of this seems pretty harmless, but the `<!-- You can start editing here. -->` snippet seems like a really confusing message to show here. 🙂

### Step-by-step reproduction instructions

1. Add a "Post Comments" block. 
2. Publish or Preview the post on the front end. 
3. Open the inspector, and find the outputted code. 

### Screenshots, screen recording, code snippet

<img width="777" alt="Screen Shot 2022-01-14 at 3 11 25 PM" src="https://user-images.githubusercontent.com/1202812/149579013-3a2f8fd6-5989-4f6d-bdc5-ae9931e33a92.png">

### Environment info

Gutenberg 12.4-RC-1 (via `trunk`)
WordPress 5.8.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@kjellr Looks like those comments are coming from here:
https://github.com/WordPress/wordpress-develop/blob/a0b1f27de6c928fde51bbc7078b32ca9c9d6ed8d/src/wp-includes/theme-compat/comments.php#L30-L75

This may have to be a core trac ticket.

It seems like usually themes will provide their own comments template, and checking TT1, that also includes different HTML comments that are output to the frontend, so the block doesn't seem to be doing anything wrong, it's just the first time these comments have surfaced for a while 😄

**Comment by kjellr** [comment]
Thanks for looking into it, @talldan! I've opened a new core ticket here: https://core.trac.wordpress.org/ticket/54851

... and will close this one. 👍
