### ISSUE TITLE
Default color palette is visible even when a custom palette has been created in theme.json

### ISSUE THREAD

**Issue by tbriggs-mx** [WordPress/gutenberg#37994]
### Description

Prior to the recent Gutenberg upgrade, when we created a custom color palette in theme.json, this would replace the default colors. After the update, this is no longer the case.

Before Update:
![image](https://user-images.githubusercontent.com/94635235/149592238-0fbf918d-181a-4317-9ed3-b918d988f3aa.png)

After Update:
![image](https://user-images.githubusercontent.com/94635235/149592287-4ee33be3-4e6a-4594-8489-e667db478628.png)

### Step-by-step reproduction instructions

Spin up a new WordPress site and theme. Add theme.json and define color in settings. Here is the theme.json code I have:

```{
	"version": 2,
	"settings": {
		"color": {
			"background": true,
			"custom": false,
			"customDuotone": false,
			"customGradient": false,
			"duotone": [],
			"gradients": [],
			"link": false,
			"text": false,
			"palette": [
				{
					"name": "Brand 1",
					"slug": "brand-1",
					"color": "#F36F21"
				},
				{
					"name": "Brand 1 Hover",
					"slug": "brand-1-hover",
					"color": "#D5570C"
				},
				{
					"name": "Brand 2",
					"slug": "brand-2",
					"color": "#A8B0BA"
				},
				{
					"name": "Brand 3",
					"slug": "brand-3",
					"color": "#FCAF17"
				},
				{
					"name": "Brand 4",
					"slug": "brand-4",
					"color": "#00ADEE"
				},
				{
					"name": "Brand 5",
					"slug": "brand-5",
					"color": "#ED1C24"
				},
				{
					"name": "Brand 5 Hover",
					"slug": "brand-5-hover",
					"color": "#AC1421"
				}
			]
		},
		"blocks": {
			"core/heading": {
				"color": {
					"background": false,
					"text": true,
					"palette": [
						{
							"name": "Brand 1",
							"slug": "brand-1",
							"color": "#F36F21"
						},
						{
							"name": "Gray 1",
							"slug": "gray-1",
							"color": "#2B3C4A"
						},
						{
							"name": "Gray 2",
							"slug": "gray-2",
							"color": "#73848D"
						},
						{
							"name": "Gray 3",
							"slug": "gray-3",
							"color": "#333333"
						},
						{
							"name": "Gray 4",
							"slug": "gray-4",
							"color": "#6c6c6c"
						},
						{
							"name": "White",
							"slug": "white",
							"color": "#ffffff"
						}
					]
				}
			},
			"core/list": {
				"typography": {
					"fontFamilies": []
				}
			},
			"core/verse": {
				"typography": {
					"fontFamilies": []
				}
			},
			"core/navigation": {
				"typography": {
					"fontFamilies": [],
					"customFontStyle": false
				}
			},
			"core/pullquote": {
				"border": {
					"customStyle": false,
					"customWidth": false,
					"customColor": false,
					"customRadius": false
				}
			},
			"core/group": {
				"color": {
					"background": true,
					"palette": [
						{
							"name": "Gray 1",
							"slug": "gray-1",
							"color": "#2B3C4A"
						},
						{
							"name": "White",
							"slug": "white",
							"color": "#ffffff"
						}
					],
					"gradients": [
						{
							"slug": "white-to-gray",
							"gradient": "linear-gradient(to bottom,var(--wp--preset--color--white) 0%, var(--wp--preset--color--gray-7) 100%)",
							"name": "Vertical - White to Gray"
						}
					]
				}
			}
		}
	},
	"styles": {
		"spacing": {
			"blockGap": "var(--wp--custom--padding--small)"
		}
	}
}
```

### Environment info

- WordPress 5.8.3
- Gutenberg 12.3.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Andrew-Starr** [comment]
To disable the default color palette you now need to set `settings.color.defaultPalette` to false.

More details in the PR: https://github.com/WordPress/gutenberg/pull/36492#issuecomment-995072001

```
"settings": {
    "color": {
        "defaultPalette": false
```

**Comment by aristath** [comment]
As mentioned above, the default palette is shown by default, and one of the reasons for that is backwards-compatibility when switching themes. It can be disabled from theme.json as per the comment above, so I'll go ahead and close this one. 👍

**Comment by tbriggs-mx** [comment]
Awesome! I figured the syntax changed, but I couldn't find the update in the documentation and when I googled, I didn't come across the PR with this info. Thanks for your help!

**Comment by uniquesolution** [comment]
in latest version of wordpress 6.4.1 , even when I have "defaultPalette": false in json, still the default color palette is showing, is there any changes has been made to hide default palette?

**Comment by uniquesolution** [comment]
> in latest version of wordpress 6.4.1 , even when I have "defaultPalette": false in json, still the default color palette is showing, is there any changes has been made to hide default palette?

Has anybody checked it? `"settings": {
    "color": {
        "defaultPalette": false` not working any more

**Comment by alahmnat** [comment]
> > in latest version of wordpress 6.4.1 , even when I have "defaultPalette": false in json, still the default color palette is showing, is there any changes has been made to hide default palette?
> 
> Has anybody checked it? `"settings": { "color": { "defaultPalette": false` not working any more

Are you using the Content Blocks Builder plugin by chance? If so, that plugin hooks into WordPress's theme.json parser to re-enable a bunch of defaults, including `settings.color.defaultPalette`. You can override that code by adding a filter for `cbb_theme_json_data_default_settings` in your theme's functions.php that takes one parameter, and just return an empty array.

**Comment by uniquesolution** [comment]
> > > in latest version of wordpress 6.4.1 , even when I have "defaultPalette": false in json, still the default color palette is showing, is there any changes has been made to hide default palette?
> > 
> > 
> > Has anybody checked it? `"settings": { "color": { "defaultPalette": false` not working any more
> 
> Are you using the Content Blocks Builder plugin by chance? If so, that plugin hooks into WordPress's theme.json parser to re-enable a bunch of defaults, including `settings.color.defaultPalette`. You can override that code by adding a filter for `cbb_theme_json_data_default_settings` in your theme's functions.php that takes one parameter, and just return an empty array.

Yes I am using content block builder plugin, but can you show me example filter code using `cbb_theme_json_data_default_settings`?

**Comment by uniquesolution** [comment]
> adding a filter for `cbb_theme_json_data_default_settings`

Please help me with a sample filter function code, I am not much familiar with php coding.
