### ISSUE TITLE
Removing an inner button block makes the global button block to disappear

### ISSUE THREAD

**Issue by alanjacobmathew** [WordPress/gutenberg#37999]
### Description

In the post editor when removing the first button, the whole button block disappears from the viewport, making it impossible to add other button.

Here the button block exists since it can be accessed from the list view, but can't be accessed directly from the editor.

A similar issue exists in the site editor too, but couple of clicks near that button block gives access to the inner blocks

### Step-by-step reproduction instructions

- Create a new post
- Add a new button block
- Write some content in the first button
- Remove only the first button

The whole button block disappears from the editor, even though it exists and can be accessed from the list view.

### Screenshots, screen recording, code snippet

![Button block missing](https://user-images.githubusercontent.com/33965848/149612279-a2d0e7c3-381d-46af-ba8f-4c02c1625529.gif)

### Environment info

Version 5.9-RC2-52579
Brave, Chromium
Win 10 PC

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Thanks for reporting this! From what I can see, this is a duplicate of this issue: https://github.com/WordPress/gutenberg/issues/28217 Can you confirm and, if so, close this out and add any further insights to the original issue?

**Comment by alanjacobmathew** [comment]
It seems like the issue is similar and hence closing this.
