### ISSUE TITLE
Navigation Block: Menu close button doesn't work on mobile

### ISSUE THREAD

**Issue by ryelle** [WordPress/gutenberg#37996]
### Description

When using a touch device (like a phone), the mobile menu close button doesn't close. It appears to trigger twice, so the menu closes and immediately re-opens.

I was able to reproduce this on [the new wp.org News theme](https://wordpress.org/news-test/) and the [Twenty Twenty-Two demo](https://wp-themes.com/twentytwentytwo/), both use the navigation block.

### Step-by-step reproduction instructions

1. Go to either site listed above or a local site with a Navigation block
2. Use a touch device, or switch to touch simulator on your browser
3. Open the menu
4. Try to close it

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/541093/149596200-a0b2a37b-cece-4aeb-bf90-2d326a936875.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by chthonic-ds** [comment]
I believe https://github.com/WordPress/gutenberg/pull/36837 was supposed to address the underlying cause of this behaviour.

**Comment by ryelle** [comment]
It looks like that was released with v12.2 of Gutenberg, but I'm still able to replicate this on WP trunk + Gutenberg 12.3.2.

**Comment by carolinan** [comment]
I can reproduce this using an android phone, with other themes than TT2, on Gutenberg 12.3.2 WordPress 5.9-RC2-52579 multisite.

**Comment by getdave** [comment]
I tried this on latest WordPress 5.9 RC 1 with Gutenberg 12.3.2 on TT1 blocks and was unable to replicate:

https://user-images.githubusercontent.com/444434/149788005-6febe0f2-fdfe-4d0d-9d18-6c310149beb7.mp4

**Comment by getdave** [comment]
I tested on the iOS simulator on 5.9-RC2-52579 both with _and_ without Gutenberg 12.3.2 active on the TT1 theme and I was unable to replicate:

https://user-images.githubusercontent.com/444434/149788879-f9d30bc4-b925-4692-9448-1eabc9e3dde2.mov

Also same for TT2 theme:

https://user-images.githubusercontent.com/444434/149789069-6b534446-cf52-4293-82b4-fd4b0c31a58f.mov

I'll see if I can try this on an Android somehow.

I _was_ able to reproduce this on the new wp.org News theme and the Twenty Twenty-Two demo.

**Comment by ryelle** [comment]
My screen recording was using an Android, so maybe this isn't an issue on iOS?

Continuing to debug, I can reproduce this on WordPress 5.9-beta2-52353 + Gutenberg trunk using Twenty Twenty-Two, with Firefox responsive mode + touch simulation enabled.

It looks like `navigationToggleModal` is called twice for the close button, once with a `click` event and once with a `touchstart` event. 

Edit: The `touchstart` is on the close button, but the `click` is on the open button.

**Comment by ryelle** [comment]
It looks like micromodal had a regression (see https://github.com/ghosh/Micromodal/pull/488) which caused the issue in https://github.com/WordPress/gutenberg/pull/36837 to reappear. I had version 0.4.9 of micromodal, updated locally to 0.4.10, and that seems to have fixed the issue again.

**Comment by ryelle** [comment]
PR to update micromodal version: https://github.com/WordPress/gutenberg/pull/38032

**Comment by hellofromtonya** [comment]
Hey folks, PR #38032 was backported to Core for RC3 https://core.trac.wordpress.org/changeset/52598. Thank you everyone for contributing to fixing this issue 🎉
