### ISSUE TITLE
Code block: text color settings are overwritten by default style, border on code tag

### ISSUE THREAD

**Issue by luminuu** [WordPress/gutenberg#38007]
### Description

When using a Code block and trying to set another color for the text, it won't get applied in the editor and on the frontend. I expected to be able to change the text color when using another background color.

Also, the `<code>` tag itself has a `border` of `1px solid #ddd`. The border color in the settings only applies to the wrapping `<pre>` tag, not the `<code>` tag.

### Step-by-step reproduction instructions

1. Open or create a post or page.
2. Add a Code block to it.
3. Change the background color to a darker background, so the text becomes unreadable.
4. Add a border to the block via the settings.
4. Select a lighter text color for better color contrast.
5. The text stays in the original dark color, the light border on the code tag is also visible.

### Screenshots, screen recording, code snippet

![grafik](https://user-images.githubusercontent.com/7585600/149635490-badca1d2-9c6a-4551-8b11-1c8b153838a7.png)

### Environment info

- WordPress 5.9 RC2
- no Gutenberg plugin active
- Twenty Twenty-Two theme, same effect on other themes
- Browser: Chrome, Firefox
- OS: macOS Catalina

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by amustaque97** [comment]
:wave: I'm not able to reproduce the above error. I'm afraid if I have missed something.

Screencast of the steps:

https://user-images.githubusercontent.com/21127788/149649252-c32fd7ce-e3c6-49e4-adeb-401bde1ba0ee.mov



<br />

> Also, the \<code\> tag itself has a border of 1px solid #ddd. The border color in the settings only applies to the wrapping \<pre\> tag, not the \<code\> tag.


This is expected based on the recent changes #37818

**Comment by luminuu** [comment]
You are showing how to add the code block WITH the Gutenberg plugin activated. In my case, the Gutenberg plugin was NOT active. 

I now tested it with the Gutenberg plugin activated and I still have the same issues. I'll post a video later.

**Comment by luminuu** [comment]
https://user-images.githubusercontent.com/7585600/149659571-48083dae-8097-4c5e-ad94-dd3013896ab9.mp4

Here's a screen recording from my local environment. 5.9 RC2, without the Gutenberg plugin, showing the results of my first screenshot.

**Comment by sabernhardt** [comment]
This should be fixed in PR #37816 for Gutenberg 12.4 (plugin). Maybe it still can be backported for WordPress 5.9 (or 5.9.1), though.

**Comment by luminuu** [comment]
Closing this now as a fix is already done. Thanks for sharing the PR!
