### ISSUE TITLE
Issue in colorpicker component docs

### ISSUE THREAD

**Issue by MehbubRashid** [WordPress/gutenberg#38001]
### Description

In here, [https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/color-picker/README.md](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/color-picker/README.md), In usage section, it is written `import { ColorPicker } from '@wordpress/components/ui';` . But, it doesn't work.

Instead, if i do `import { ColorPicker } from '@wordpress/components';` , It works. 
I think this usage instruction is wrong and need to be corrected.

### Step-by-step reproduction instructions

1. Do import { ColorPicker } from '@wordpress/components/ui'; , it won't work
2. Do import { ColorPicker } from '@wordpress/components';, it works!

### Environment info

- WordPress version: 5.8
- Gutenberg: No (was testing in site frontend)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by amustaque97** [comment]
Thank you @MehbubRashid  for raising the concern :clap:. I have raised a PR for the same.

**Comment by MehbubRashid** [comment]
Great, @amustaque97 
Thanks
