### ISSUE TITLE
Widget Editor: Regression in 12.3.2 - Shows blank in any mobile browser

### ISSUE THREAD

**Issue by nagpai** [WordPress/gutenberg#38002]
### Description

On Gutenberg 12.3.2, The widget editor from 
`WP admin >> Appearance >> Widgets` 

shows as blank when accessed from a mobile browser, or a narrow viewport on any desktop browser. 

This error does not show up on older version of Gutenberg ( with the plugin disabled )

### Step-by-step reproduction instructions

1. Install and activate Gutenberg plugin to ensure you have version 12.3.2 
2. On a mobile browser or a desktop browser with narrow width, open up  `WP admin >> Appearance >> Widgets` 
3. You will notice a blank area in the widgets. 

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/4162931/149617261-0f0ae593-0861-4f11-b0e6-ea45fe441b43.png)
-----

Video:

https://user-images.githubusercontent.com/4162931/149617305-42688f7d-5498-457a-9167-5671ff45f011.mp4

### Environment info

- WP 5.8.2 
- Twenty Twenty One theme
- Gutenberg 12.3.2 
- LocalWP installation

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting. It looks like the issue is that the secondary sidebar (the sidebar that usually contains the inserter menu or List View) is covering the content when it shouldn't. And also the contents of that sidebar are not being displayed at all.

I'll work on tracking down the problem and put together a fix.
