### ISSUE TITLE
WordPress5.9 When using FontSizePicker with slider, if you select the size preset and then change the input area, an error occurs and the browser freezes.

### ISSUE THREAD

**Issue by shimotmk** [WordPress/gutenberg#38016]
### Description

When using the FontSizePicker with slider in WordPress 5.9 environment, if I select the size preset and then change the input area, an error occurs and the browser freezes.

- Size preset can be selected and changed.
- Custom size can be changed with the slider of Custom Size.
- Custom size can be changed in the input area of Custom Size.
- Select the Size preset and use the slider to change the size.
- When I select the Size preset and change the input area, an error occurs and the browser freezes

### Step-by-step reproduction instructions

1. Create a custom block using FontSizePicker with slider
2. If you select Size preset and change the input area, an error will occur and the browser will freeze

##  recording
https://user-images.githubusercontent.com/42362903/149697659-be147fcb-da2e-462e-9330-bb8bc903b559.mov

##  code snippet
Here is the edit.js code for the custom block used in recording.

```edit.js
import { __ } from '@wordpress/i18n';
import { useBlockProps, InspectorControls } from '@wordpress/block-editor';
import {
	PanelBody,
	FontSizePicker
} from '@wordpress/components';
import './editor.scss';
import { useState } from '@wordpress/element';

export default function Edit() {
	const fontSizes = [
		{
			name: __('Small', 'vk-blocks'),
			slug: 'small',
			size: '12px',
		},
		{
			name: __('Normal', 'vk-blocks'),
			slug: 'normal',
			size: '16px',
		},
		{
			name: __('Big', 'vk-blocks'),
			slug: 'big',
			size: '18px',
		},
		{
			name: __('Extra big', 'vk-blocks'),
			slug: 'extra-big',
			size: '21px',
		},
	];

	const fallbackFontSize = 16;
	const [fontSize, setFontSize] = useState(16);

	return (
		<div { ...useBlockProps() }>
			<InspectorControls>
				<PanelBody title={'FontSizePicker setting'}>
					<FontSizePicker
							fontSizes={fontSizes}
							value={fontSize}
							fallbackFontSize={fallbackFontSize}
							withSlider={true}
							onChange={setFontSize}
						/>
				</PanelBody>
			</InspectorControls>
			<div>
				<p style={{ fontSize: fontSize}}>
					{ __(
						'Example Plugin – hello from the editor!',
						'example-plugin'
					) }
				</p>
			</div>
		</div>
	);
}
```

## console error
The following console errors occur continuously in the browser.
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```

### Environment info

- WordPress 5.9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I also reproduced the problem with WordPRess 5.9 (without activating the Gutenberg plugin).
However, I could not reproduce it with the Gutenberg plugin activated.

I changed the version of `@wordpress/components` that imports the `FontSizePicker`, and found that the problem was reproduced in **v19.2.0**, but not in **v19.3.0**.

I did not find any issues that correspond to this problem, but it may have been resolved by the changes made between the two versions.

**Comment by t-hamano** [comment]
@shimotmk 

Could you please try activating the gutenberg plugin or importing the components from the latest @wordpress/components and see if the symptoms are reproduced?
If you are sure that the latest version of gutenberg does not have the problem, please close this issue.

**Comment by shimotmk** [comment]
@t-hamano 
Thanks for your comments! & sorry for the delay in replying.

I've enabled the Gutenberg plugin and the symptoms are gone, so I'll close this issue.
