### ISSUE TITLE
Navigation Block: Allow Letter Spacing Control

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#38033]
![Header 4](https://user-images.githubusercontent.com/908665/149821018-7265091a-c627-4457-bee9-ef17d5f1da58.png)

It'd be great if we could change letter spacing for navigation items. It'd be especially useful when they are uppercase.

I briefly tried to find if there is already a request, but I didn't see any. Please point me if there is a space where this has been discussed. 

## What problem does this address?
There doesn't seem to be a way to alter letter spacing for the navigation items.

## What is your proposed solution?
Allow the Navigation block to change letter spacing like the Header block.

**Comment by jasmussen** [comment]
Letter spacing for sure! Instead of making it Navigation block exclusive, though, shouldn't we instead make letter spacing a property of the general Typography panel? I imagine it being a non-default option you add from the ellipsis menu in the panel.

**Comment by jordesign** [comment]
Closing this issue as Letter Spacing is now available on the Navigation Block

<img width="317" alt="Screenshot 2023-10-27 at 10 53 28 am" src="https://github.com/WordPress/gutenberg/assets/1842363/54eb2f25-770f-4fe1-9432-64a1adc8ba03">
