### ISSUE TITLE
Images: Media Library empty when trying to add/change featured image

### ISSUE THREAD

**Issue by dartiss** [WordPress/gutenberg#3803]
When editing a post and I try to add or edit a featured image, my media library tab is not showing any images. I have LOADS. If I switch to using the standard editor for the same post, the media is shown correctly.

I'm not seeing anything in the JavaScript console that appears relevant - certainly nothing when I go into the featured image modal.

Running WP 4.9.1 and Gutenberg 1.8.1

**Comment by torounit** [comment]
I have same issue.

When add post  and  click `Set featured image`,  Media Library window open but, No item found and show errors.

```
Uncaught ReferenceError: TB_WIDTH is not defined at tb_position  at media-upload.js
```
```
Uncaught TypeError: Cannot read property 'hasClass' of undefined at wp-auth-check.js
```
https://github.com/WordPress/WordPress/blob/master/wp-includes/js/wp-auth-check.js#L101

When featured image panel close and reopen, That error did not occur.

**Comment by davidlaietta** [comment]
I have the same issue with the same console errors, and the media library continuously tries to load.

**Comment by monika-12** [comment]
I am also getting the same issue with same console error.

**Comment by danielbachhuber** [comment]
Hi folks,

Sorry for the late reply here. I can see images in the Media Library when setting a Featured Image using `master`:

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/36432/40546996-91263c6e-5fe5-11e8-8c3a-15a04858d8b4.png">

Feel free to re-open the issue if the problem still manifests and you have steps to reproduce.
