### ISSUE TITLE
Social Icons: theme styling may distort icon proportions

### ISSUE THREAD

**Issue by chad1008** [WordPress/gutenberg#38043]
### Description

Depending on how a theme styles the relevant `li` elements, the shape of social icon buttons can become distorted, often being stretched vertically.

Twenty Seventeen is a key example, where the theme styling sets:

```
.widget ul li, .widget ol li {
    border-bottom: 1px solid #ddd;
    border-top: 1px solid #ddd;
    padding: 0.5em 0;
}
```
Because the Social Icons block applies the background color directly to the `li` element, that padding leads to the button having a vertical pill-shape, instead of the expected circle that's shown in the Customizer/widgets.php

### Step-by-step reproduction instructions

1. Activate 2017
2. From Customizer or widgets.php, add a Social Icons widget with at least one icon added. Be sure to include a URL.
3. Note that in Customizer/widgets.php, the button is a circle, as expected.
4. Save your changes, and view the widget on the front end. Note the button is stretched vertically

### Screenshots, screen recording, code snippet

front end:
![image](https://user-images.githubusercontent.com/13856531/149933972-5a4a6e82-6af5-4b0a-a144-568fc1a41ee4.png)

widgets.php (Customizer also looks the same)
![image](https://user-images.githubusercontent.com/13856531/149934155-5df3ba20-3706-4d37-baa0-c104a84fb711.png)

### Environment info

- Tested with GB 12.3.2 on WordPress.com and locally with 6.0-alpha-52573 via wp-env
- Chrome  96.0.4664.110, MacOS 12.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

_Originally reported in https://github.com/Automattic/themes/issues/5345_

**Comment by kathrynwp** [comment]
I am still able to replicate this with:

WP 6.0.1 - local install
No plugins active
Twenty Seventeen 3.0 

![Self-hosted_Test_–_not_just_another_fake_company](https://user-images.githubusercontent.com/7662449/178780755-ea9191fa-6653-4556-b599-ca5d85d085a1.jpg)
