### ISSUE TITLE
Image size settings can be confusing

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#38050]
<img width="280" alt="Screenshot 2022-01-18 at 14 30 28" src="https://user-images.githubusercontent.com/846565/149956699-637d274a-183c-47ec-83fc-17420a44ece5.png">

We have "Image size" to determine which version of the source file to use. 

Then Width and Height specify how much space the image should occupy on the page. 

And finally there are percentage-based presets which set the Width and Height _relative to the selected "Image size"_.

---

### Problems

It's not clear which Image Size one should use, or what Image Size means, given there are dedicated inputs for width and height.

It is possible to mistakenly use inappropriate settings. E.G. set the height and width to some small value, but still use the full size Image Size. This is not performant. Or vice versa – set a large height / width, then use an Image Size that is too small, which results in a blurry image.

It's not really clear what the percentage presets actually do. I had to go in to Settings > Media to understand what is going on there. I'm also not entirely sure how useful this setting is.

---

At the very least it seems we can better communicate the relationship between Image Size and Height / Width. In the past I think @jasmussen has suggested displaying the pixel values of each size in the dropdown:

<img width="256" alt="Screenshot 2022-01-18 at 14 41 23" src="https://user-images.githubusercontent.com/846565/149958672-2b85686f-c1ee-4299-a009-64132b835bd4.png">

But in the end I wonder if the Image Size setting needs to be so prominent, or whether we can intelligently set it based on the Height / Width values.

**Comment by jasmussen** [comment]
I created #38068 for some general design improvements to the image block, it includes some of the conversation around improving the Size selector as well.

**Comment by glendaviesnz** [comment]
This is also now relevant in the Gallery block which uses nested Images blocks, and [when the 'crop images' option is toggled on the size selector can appear to have no impact at all](https://github.com/WordPress/gutenberg/issues/29917).

**Comment by Mamaduka** [comment]
This probably will be resolved by #49112.

cc @richtabor

**Comment by richtabor** [comment]
> This probably will be resolved by https://github.com/WordPress/gutenberg/pull/49112.

In part, yes. The "Size" select isn't part of that PR.

**Comment by jordesign** [comment]
@richtabor  - do you think that last remaining item is sufficiently covered by the work being considered in #38068? Worth consolidating?

**Comment by richtabor** [comment]
Here's what we have currently (no % based size group): 

<img width="278" alt="CleanShot 2023-09-14 at 09 29 43" src="https://github.com/WordPress/gutenberg/assets/1813435/c2443a6b-3b90-45cb-9ab2-4070de47ecde">

Unifying the dimensions panel to include height/width would help reduce the confusion, but I think we're sitting in a decent spot currently.

**Comment by jameskoster** [comment]
Agreed, this UI has improved _a lot_. Let's close this 🥂
