### ISSUE TITLE
Image: Improve the inspector, adopt the unified dimensions panel

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#38068]
Part of #28356 and related to #27331. 

The inspector controls for the Image block have built up over the years, and could use a little love and unification:
<img width="360" alt="Before" src="https://user-images.githubusercontent.com/1204802/150113499-ccc5a797-5290-4ab5-b205-c9fc3cb5aad7.png">

- The dimension controls could adopt the unified dimensions panel to add consistency across blocks
- Alt text could be simplified, and arguably deserves its own panel
- Dimension controls use an older version of the segmented control, and could benefit from the ToolsPanel reset behavior
- Image size could benefit from being a non-default ToolsPanel control, due to its complexity (#38050) and for consistency (#38044)

Here's a mockup taking a stab at some improvements:

<img width="688" alt="Image Block Inspector" src="https://user-images.githubusercontent.com/1204802/150116308-4e52f784-fe08-47a7-bec1-a9d2b80f222f.png">

- The unified Dimensions panel brings consistency and the ability to hide the Size control by default.
- Note the dimensions shown inside the size selector and the added help text ([suggested here](https://github.com/WordPress/gutenberg/pull/38044#pullrequestreview-856547867)).
- For some settings or base properties of the block, such as Styles, they could be integrated directly into the block card at the top.

**Comment by Mamaduka** [comment]
> Alt text could be simplified, and arguably deserves its own panel

I love the idea.

> For some settings or base properties of the block, such as Styles, they could be integrated directly into the block card at the top.

With the new Styles design, I think this would be a nice change. We already display variation transforms in the block card.

**Comment by mtias** [comment]
@jasmussen is this still relevant?

**Comment by jasmussen** [comment]
Parts of it are relevant, yes, but these are things that will also likely be naturally intuited when we get to updating the image block inspector. So I don't know that it needs an open issue. Closing for now, it'll be findable still!

**Comment by jasmussen** [comment]
I'm actually going to reopen this one, it keeps coming up in discussions around the ToolsPanel.

**Comment by richtabor** [comment]
For reference, here's what we have today: 

<img width="280" alt="CleanShot 2023-09-14 at 09 31 43" src="https://github.com/WordPress/gutenberg/assets/1813435/47c4746b-4877-4e8a-b53b-4aef13088fa0">
<img width="280" alt="CleanShot 2023-09-14 at 09 32 40" src="https://github.com/WordPress/gutenberg/assets/1813435/7d41c4ed-c35b-4b64-b5c5-464d4c4acb3b">

**Comment by richtabor** [comment]
What gets confusing is when the block is within a row or stack. Then there are two entries for width (also the same for site logo): 

<img width="277" alt="CleanShot 2023-09-14 at 09 33 34" src="https://github.com/WordPress/gutenberg/assets/1813435/5bfcb050-b7e8-4059-8eee-7d705165f963">

**Comment by jasmussen** [comment]
The width issue feels related to the Row block, but excellent point, it seems like we could definitely unify a) the tab in which width lives, and b) make sure there's only ever one width control. 

Perhaps the final question here is whether we can/should extract the Alternative text as a separate panel, or not. If we want to still do that, we can commandeer this issue to be about that.

**Comment by jasmussen** [comment]
I'll close this for now. Let's see what organically emerges.
