### ISSUE TITLE
Highlight text button: After selecting a color the text input loses focus

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#38082]
## Description

When writing text on a text block (i.e. Paragraph block), tapping on the Highlight text button and selecting a color, loses the focus of the block's text input, which forces the user to tap again in the block to continue writing.

## Step-by-step reproduction instructions

1. Add Paragraph block.
2. Tap on the Highlight text button (A) and select a color.
3. Observe that the text input loses focus.

## Expected behaviour

Text input shouldn't lose focus after selecting a color.

## Actual behaviour

Text input loses focus after selecting a color.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/150181538-2569dcdf-c537-4992-a918-4da688cdc3fc.mp4

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: Samsung Galaxy S20 FE 5G
- Operating system: Android 10
- WordPress app version: develop

**Comment by mchowning** [comment]
Verified this occurs on 18.9, so it's not a regression since that release.

**Comment by fluiddot** [comment]
This issue was solved in https://github.com/WordPress/gutenberg/pull/57069.
