### ISSUE TITLE
Returning to Post from Revisions

### ISSUE THREAD

**Issue by chriswathen** [WordPress/gutenberg#3808]
## Issue Overview
When user views post revisions, the return to post link returns the user to the post but under Classic Editor, when the user restores a post revision the post is restored and the classic editor is shown again. 

## Steps to Reproduce (for bugs)

1. Open post to edit
2. Click the **Revisions** link on the right
3. Click the "← Return to editor" which links to returns to correct post but Classic Editor

## Expected Behavior
Should return to post with Gutenberg editor

## Screenshots / Video

![image](https://user-images.githubusercontent.com/34251245/33574557-16d69494-d8ff-11e7-803b-715e403aa4ad.png)
![untitled-1](https://user-images.githubusercontent.com/34251245/33574654-7306c860-d8ff-11e7-94e7-1668b637fc35.png)

**Comment by Soean** [comment]
Hey @chriswathen, thanks for your creating this issue. This bug is already reported in #2808
There is also already a pull request for solving it, see #3511

**Comment by youknowriad** [comment]
closing as duplicate
