### ISSUE TITLE
attribute "boolean" is a string when used in block and needs eval

### ISSUE THREAD

**Issue by ivanjeremic** [WordPress/gutenberg#38087]
### Description

```
<ToggleControl
label="Muted"
help={attributes.muted ? "Enabled." : "Disabled."}
checked={attributes.muted}
onChange={(value) => setAttributes({ muted: value })}
/>
```

in block.json

```
"muted": {
"type": "boolean",
"default": false
}
```

In the frontend it only works when I use `eval()`

### Step-by-step reproduction instructions

Same as above

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@ivanjeremic I don't really understand this issue. Please could add some more detail to the description.

**Comment by ivanjeremic** [comment]
> @ivanjeremic I don't really understand this issue. Please could add some more detail to the description.

I use the Interactive Block example from WooCommerce, https://github.com/senadir/interactive-block so maybe some issue there with the rendering or parsing of the attributes.

**Comment by talldan** [comment]
cc @senadir, not sure if you're able to help with this one?

**Comment by senadir** [comment]
Thanks for the ping @talldan, we can close this issue and I will answer it here https://github.com/senadir/interactive-block/issues/2 as it related to our frontend attribute parsing function, which isn't part of Gutenberg.
