### ISSUE TITLE
Highlight text button: Undo applying a color breaks the undo history

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#38084]
## Description

After applying a color via the Highlight text button, the next undo actions are removed from history after undoing applying the color.

## Step-by-step reproduction instructions

1. Add a Paragraph block.
2. Type some text.
3. Apply bold/italic/strikethrough formats to some words.
4. Select a word and tap on the Highlight text button (A).
5. Select a color.
6. Execute other actions that can be undone (i.e. apply bold/italic/strikethrough formats to other words).
7. Tap on the undo button until it reaches the color apply action.
8. Observe that the undo history gets deleted and that previous actions can't be redone.

## Expected behaviour

Executing undo actions shouldn't delete the undo history.

## Actual behaviour

Undoing color apply action deletes the undo history.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/150187325-c1a083ff-f4b0-4580-b069-8d319233acd9.mp4

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: Samsung Galaxy S20 FE
- Operating system: 
- WordPress app version:

**Comment by mchowning** [comment]
I was also able to recreate this on the 18.9 version of the app, so it is not a regression since that release.

**Comment by fluiddot** [comment]
I managed to reproduce the issue in version `23.9`, although it doesn't happen consistently. For some reason, it's easier to reproduce it when performing the undo/redo actions quickly. That said, I'd advocate changing the priority to Low as seems to have less impact than it was when the issue was created.
