### ISSUE TITLE
Add Custom CSS to Global Style - similar to the additional CSS section in the customizer

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#38089]
## What problem does this address?

As the customizer by default is not visible for Full Site Editing themes we need another way of adding general CSS to a site.
It can take over for the Additional CSS section seen in the customizer.

## What is your proposed solution?

Adding a CSS edit section to Global Styles.

Thoughts?

@jorgefilipecosta

**Comment by bgardner** [comment]
I love this idea and have already considered creating an issue for it. With customizer inevitably going away, I think this is a huge win for those who need to customize a few things via CSS.

**Comment by ndiego** [comment]
This would be a handy addition. Possible duplicate issue here: https://github.com/WordPress/gutenberg/issues/30142.

**Comment by skorasaurus** [comment]
thanks for pointing out @ndiego ; let's continue discussion at https://github.com/WordPress/gutenberg/issues/30142

**Comment by courtneyr-dev** [comment]
I wanted to add a `box-shadow` to the borders of my groups. I'd love some custom CSS options here, or further support around border properties.
