### ISSUE TITLE
New Welcome's panel "Edit styles" link does not seem to work

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#38090]
### Description

The expected behavior would be to open the Global Styles panel on the site editor.

Original Trac ticket: https://core.trac.wordpress.org/ticket/54859

### Step-by-step reproduction instructions

1. On WP 5.9 RC3 Welcome panel, click "Edit styles" link.
2. It leads to the site editor, but it doesn't open the Global Styles panel, which would be the expected behavior.

### Environment info

- WP 5.9 RC 3, no plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hellofromtonya** [comment]
As I noted in the Trac ticket, this issue may be a bad URL. The one used is: `wp-admin/site-editor.php?styles=open`. Is this correct to automatically open the Styles area in the Site Editor? Or is this a bug that needs fixing?

It would be great to have this issue fixed quickly in case another issue is reported that warrants a RC4. cc @noisysocks @Mamaduka

**Comment by noisysocks** [comment]
That URL is correct. It looks like this functionality was accidentally removed in https://github.com/WordPress/gutenberg/pull/36637. I'll open a PR to add it back.

**Comment by audrasjb** [comment]
Alright, thank you!
