### ISSUE TITLE
Can't access navigation menu (post type) page in backend

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#38118]
### Description

It is not possible to edit navigation menus (Gutenberg), even as an admin user, 
as access to the `wp_navigation` post type page is denied.

An `admin` user (role) should be able to edit everything, including the navigation menus.
The `wp_navigation` post type declares its required capabilities as:
https://github.com/WordPress/gutenberg/blob/trunk/lib/navigation.php#L53-L64

Does an `admin` user role not include any of these capabilities?

### Step-by-step reproduction instructions

Getting the link:
1. (Create a navigation block)
2. Select the/a navigation block.
3. Open dropdown by selecting `Select menu` of that navigation block.
4. Select `Manage menus` in the dropdown.
5. This will link to `https://www.example.com/wp/wp-admin/edit.php?post_type=wp_navigation`.

Visit the `wp_navigation` post type page 
(`https://www.example.com/wp/wp-admin/edit.php?post_type=wp_navigation`).
Note the access denied error.

This is strange as the `admin` user role should already include the required `edit_theme_options` capability by default.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@strarsis Would you be able to share which Gutenberg / WordPress version you're using?

I tested with 5.9RC3 (with and without latest Gutenberg) and it seemed to work ok, I could access the menus page.

**Comment by talldan** [comment]
I think we got to the bottom of this. It only happens in classic themes.

The post type has `'show_ui' => wp_is_block_theme()`  defined in [Gutenberg](https://github.com/WordPress/gutenberg/blob/34ed60b61251e3f655048859a1350493c59141b1/lib/navigation.php#L41) and [Core](https://github.com/WordPress/wordpress-develop/blob/6223e0cf1efa86995de9d78d39360a3b8efa0c45/src/wp-includes/post.php#L506).

**Comment by noisysocks** [comment]
https://core.trac.wordpress.org/ticket/54889 tracks fixing this in Core. We'll need to make the same change in Gutenberg for older WP versions.

**Comment by strarsis** [comment]
@talldan: Yes, I am also using the latest WordPress and Gutenberg plugin versions.

The theme is a classic theme in a sense, yes.
