### ISSUE TITLE
Video: This block has encountered an error and cannot be previewed.

### ISSUE THREAD

**Issue by thetwosents** [WordPress/gutenberg#3811]
## Screenshots / Video

Just gonna submit a video of the issue if that is okay by you guys/girls:

[Video](https://youtu.be/E9fqnHQbRag)

Thanks and more than happy to record any other issues / tests I come across as I move forward!

- Jon

**Comment by alexmacarthur** [comment]
I'll take a look at this!

**Comment by alexmacarthur** [comment]
Hi, @thetwosents -- A couple of questions in troubleshooting this. I'm attempting to duplicate but have been unable to so far.

* Are you using the latest version of Gutenberg?
* Do you have the URL of the video you embedded? I want to try with that specific video. 
* How did you embed the video? Did you use custom HTML, or use the dedicated YouTube block?

**Comment by jjchrisdiehl** [comment]
I can add to this,

#### Steps to reproduce (loosely)
1. Added content
2. Toggled around a few different block types
3. Moved cursor up with up arrow on keyboard
4. Triggered warning about error

#### What I expected
Expected to be able to key around the editor without error

#### What happened instead
The error came up between two headers (the title and the following h2) then on refresh added the word Wordpress as a paragraph block between the headers.

#### Browser / OS version
Chrome Version 63.0.3239.84 (Official Build) (64-bit) / Windows 10 Version 1709

#### Screenshot / Video
I had a screenshot but of course, inadvertently copied over it, looked exactly like the OP post video. Will update if I run into this bug again

#### Context / Source
Was testing the Gutenberg plugin on my self-hosted site wptoolkit.us

**Comment by thetwosents** [comment]
Hey guys! Sorry, had my notifications turned off. I did an iframe embed link, though I can confirm this happens with any existing content, not just the video.

**Comment by danielbachhuber** [comment]
Hi @thetwosents,

Thanks for taking the time to report issues with Gutenberg. I'd like to figure out how we can identify what's actionable with this issue. To do so:

* Can you try to reproduce the issue with a new stock WordPress install (no custom plugins active, running Twenty Seventeen)?
* If the issue does reproduce, can you share exact reproduction steps, including the embed code you've used?
* If the issue doesn't reproduce, can you try deactivating all of your WordPress plugins on the original site, and activate them one by one until the issue reproduces?

Thanks!

**Comment by thetwosents** [comment]
Absolutely. Will do when I get in this evening!

**Comment by markx2** [comment]
Just had this error occur.

http://x2.lol/s/oj3bz.png

Was writing this post. 

http://romanticrobot.net/2018/01/20/sick-of-being-sick/

Move the cursor and the error happened. 

Solution was to reload the editor and choose the latest revision.

Not sure what else I can add to help?

**Comment by karmatosed** [comment]
I am unable to replicate this. For now, going to close as maybe it is resolved. If someone is still getting this using a default theme please update with a comment. A closed issue can always be reopened once more is known about it.
