### ISSUE TITLE
Request for `validateResolution...()` actions for the data api

### ISSUE THREAD

**Issue by rmorse** [WordPress/gutenberg#38128]
## What problem does this address?
When building more advanced stores using the data api, I'm finding it really useful to use the `invalidateResolution...()` actions.

So the resolution will be invalidated, and the resolver will be run again next time we ask for a piece of data via a selector.

_Ok, so far so good.  But what about the opposite?_

1.  Lets say I have a store, which interacts with a CPT called `product` (but it could be anything)...
2. We have one selector - `getProducts()` - which retreives a list of products.
3. And we have another selector `getProduct( id )` which retrieves a single product by ID.
4. Now lets say, we run `getProducts()` at some stage to list all our products and from here I can edit a product.
5. If I edit the product, we run `getProduct(id)` selector to get the product data.. and lets say we want a product with the ID of `1`... 
6. What happens when `getProducts()`  already retrieved the data for product `1`? 
7. The resolver is still run even though our state is already populated... but we don't actually need to run it...

This causes some other odd issues when the data finally comes back from the api for `getProduct(id)` and the update routines are run again but we're already using the state to do what we want (it's not empty).

I am actually trying to build a demo of the data api (with working endpionts), but only have the store code up for now:
https://stackblitz.com/edit/wp-data-api-custom-store?file=src%2Fstore%2Fselectors.js

Take a look also at the resolver, and how `getProducts()` populates the state used for `getProduct()`

## What is your proposed solution?
So the solution would be simply be to have a group of actions that match the `invalidateResolution...()` actions, but do the opposite - something like `validateResolution...()`

We can fire this before we use the `getProduct(id)` selector if we already have the data ( maybe when we resolve getProducts() ) so the resolver is skipped altogether until we decide to invalidate it.

_I hope the use case makes sense - perhaps I'm just looking at the bigger picture incorrectly!_

**Comment by rmorse** [comment]
@gziolo any thoughts if this would even possible (before we get onto if this is a good idea or not) ?

I had a look at the code and as far as I can tell this is a wrapper for an action provided by redux?:
https://github.com/WordPress/gutenberg/blob/52bfacb06156031aa440f234c5d2595a022cae55/packages/data/src/redux-store/metadata/actions.js#L108

~~So it would depend if redux offers the inverse?~~

----

Edit - ok I thought I had checked for resolvers, turns out there is one already, but not sure how that works exactly

https://github.com/WordPress/gutenberg/blob/73d52fa8d90bc7f9486d597cc8da9d3a641c1d79/packages/data/src/redux-store/metadata/reducer.ts#L76

I'm finding this difficult to understand, my guess is, we are ommiting a property (with a name matching the selector name) to remove its resolved state (invalidate it)?

So if we did the inverse, and create an object key that matches the selector name, we could potentially "validate" it?

**Comment by Mamaduka** [comment]
@rmorse, core data is already doing something similar for entity records.

So when you fetch records using `getEntityRecords`, it also resolves `getEntityRecord` for the list of results.

https://github.com/WordPress/gutenberg/blob/64b16f3442791a8afca1377f4260fb44d5f00227/packages/core-data/src/resolvers.js#L185-L204

Related PRs: #26575 and #31005.

**Comment by rmorse** [comment]
That looks fantastic @Mamaduka , will test this out on my project in the next few days - it makes perfect sense this is a use case that's already presented itself!

**Comment by rmorse** [comment]
Ok this is great! Thanks for the reference and pointing me in the right direction.

I did realise I had tried the singular start / finish resolution before, but I couldn't get that working, which I think now is due to to me setting up the arguments incorrectly (its quite confusing!).

Also, the example above shows this technique working with a custom redux store, took me a minute to find the wp data `createStore` equivelant.

Anyway, I've got this all working now, thanks a lot for the help!

----

For those that stumble on this ticket, if you're trying to resolve your selectors (because you've already fetched the same data by another method), you can use the technique used in this code snippet:

```js
/**
 * WordPress dependencies
 */
import { addQueryArgs } from '@wordpress/url';
import { controls } from '@wordpress/data';

// Get multiple products based on some query args
export function* getProducts( args ) {
	const path = addQueryArgs( `${ REST_BASE }/products`, args );
	const productsResult = yield getFromAPI( path );
	if ( productsResult ) {
		// Setup the resolution args for getProduct
		const resolutionsArgs = productsResult.map( ( product ) => {
			// This needs to match the order of the args passed to `getProducts`
			// We only have 1 arg, the ID.
			return [ product.id ];
		} );
		yield controls.dispatch(
			STORE_NAME,
			'startResolutions',
			'getProduct',
			resolutionsArgs
		);
		yield controls.dispatch(
			STORE_NAME,
			'finishResolutions',
			'getProduct',
			resolutionsArgs
		);
		return hydrateProducts( productsResult, args );
	}
}
// There will also be getProduct with its own implementation:
export function* getProduct(id) {
   //...
}
```
This example shows a call for multiple products via a rest endpoint, and then using `controls.dispatch`, we dispatch `startResolutions` and `finishResolutions` to resolve multiple individual `getProduct(id)` selectors.

**Comment by Mamaduka** [comment]
Thank you, @rmorse, for taking time and posting your solution 🦸
