### ISSUE TITLE
Create Block: Add consistency with the Edit/save components and how they are used.

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/gutenberg#38138]
## What problem does this address?
The default template that is used with the `@wordpress/create-block` package defines and uses the `save` and `Edit` components differently. This has caused some confusion in the past ( see #33613 and related #34548 ). I use the default package regularly to quickly scaffold up a block for any number of reasons and the first thing I do is to change the import for the `Edit` to `edit` and use object shorthand to access it in the `registerBlockType` call. This seems like an unnecessary step and we should standardize the usage here for both `save` and `Edit` as there is no clear reason why one is defined as a function and the other as a component when they both contain JSX.

## What is your proposed solution?
I propose that we name the functions using lowercase for both functions and add a reference to explain object-shorthand in the `registerBlockType` call.

**Comment by gziolo** [comment]
Resharing the conclusion from #38139:

> @gziolo this is fantastic, thanks for explaining this in such depth! Based on your explanation, I think makes sense to keep `save` lowercase as it's not meant to be a React component, and if it is, only the `render` function is actually used. This is a nuance that needs to be shared in other places. I'll close this out and focus on docs updates.
