### ISSUE TITLE
Focus mode: List templates that consume the template part

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#38130]
When editing a template part in focus mode, it's not always clear exactly where that template part is used, or indeed if it is used at all. This can reduce confidence in the consequence of any changes.

As block themes begin to bundle more templates / template parts (think templates for different archive types, multiple header options, content arrangements, and so on) this detachment could become more of an issue.

If we enable users to view a list of templates that consume the template part they're editing, that will help them better understand the full impact of their changes.

**Comment by jameskoster** [comment]
Quick example flow where this would be important:

* Theme bundles `content-one.html` and `content-two.html ` template parts for displaying post content.
* `archive.html`, `category.html`, and `search.html` all consume `content-one.html`. 
* `index.html` and `author.html`  consume `content-two.html`.
* If you were to edit `archive.html`, select `content-one.html` and enter focus mode, you may interpret that those changes would only be applied to `archive.html` which of course would not be the case – any changes would also affect `category.html` and `search.html`.

**Comment by jameskoster** [comment]
We can also extend this to Reusable Blocks, Navigation Menus, and any other entity that may in the future be editable in focus mode.

**Comment by mtias** [comment]
Isn't this a duplicate of #20476 ?

**Comment by jameskoster** [comment]
Pretty much :)

**Comment by mtias** [comment]
It can probably use an update since the designs are fairly old.
