### ISSUE TITLE
Undefined Index creating new WooCommerce Product (via Classic Editor mode)

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3813]
## Issue Overview
I just wanted to do some testing (totally unrelated to Gutenberg) and tried to create a new WooCommerce product via the Classic Editor.

![screenshot_544](https://user-images.githubusercontent.com/2078245/33595003-5e2545c0-d9ea-11e7-9856-0913d730a64c.png)

When the Add New Product screen displayed, I see a number of repeated Notices:

_Notice: Undefined index: title in /Volumes/Macintosh HD2/Sites/dev.wordpress-test.com/wp-admin/includes/template.php on line 1042_

![woocommerceaddnewproduct](https://user-images.githubusercontent.com/2078245/33595183-2da1d98a-d9eb-11e7-8c03-7f31299e959f.png)

## Steps to Reproduce (for bugs)
1. Click the _Classic Editor_ link on the _Add New_ button on the WooCommerce Products screen

_Firefox Quantum 57.0.1 (64-bit)
Gutenberg Version 1.8.1
WooCommerce Version 3.2.5
No other plugins activated_

**Comment by terriann** [comment]
Reported an issue with the same error output having to do with a different plugin + Gutenberg https://github.com/xwp/wp-customize-snapshots/issues/172

**Comment by danielbachhuber** [comment]
Thanks for the report, @maddisondesigns. This was fixed in #3856
