### ISSUE TITLE
Allow using gradients as body background color in theme.json

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#38131]
### Description

If I add a gradient or a gradient preset as the body background color in theme.json, the resulting CSS is invalid and the gradient not used.

```
"styles": {
	"color": {
		"background": "var(--wp--preset--gradient--pale-ocean)"
	}
}
```

Resulting CSS:
`body {
    background-color: var(--wp--preset--gradient--pale-ocean);`

In comparison if I apply the gradient to the body in Site Editor > Styles, the CSS used is  
`background: var(--wp--preset--gradient--pale-ocean);` which is valid.

Related:
https://github.com/WordPress/gutenberg/issues/32787

### Step-by-step reproduction instructions

Using a block theme:
1: Change the background color in the styles section in theme.json to use a gradient preset.
2. View the front of the website and confirm that the gradient is not used.
3. View source to confirm the CSS output.

### Environment info

WordPress version 5.9-RC3-52601 and Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Andrew-Starr** [comment]
You can use a gradient background but it has to be written like so:

```
"styles": {
	"color": {
		"background": "var:preset|gradient|pale-ocean"
	}
}
```

Having said that, it should be fixed so that the more expected usage of `var(--wp--preset--gradient--pale-ocean)` will also work.

**Comment by carolinan** [comment]
Since we _have_ to use it -where is that format documented?

It is not noted here, the only example uses a custom CSS property:
https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#top-level-styles

**Comment by Andrew-Starr** [comment]
Sorry I should have said it's not documented.

It's an issue that should be fixed.

After a bit more testing, using `var(--wp--preset--gradient--pale-ocean)` will work if the background gradient is defined in `styles.color.gradient`:

```
"styles": {
	"color": {
		"gradient": "var(--wp--preset--gradient--pale-ocean)"
	}
```

If we want to define `styles.color.background` then using `var:preset|gradient|pale-ocean` works:

```
"styles": {
	"color": {
		"background": "var:preset|gradient|pale-ocean"
	}
```

**Comment by carolinan** [comment]
Oh I did not know styles.color.gradient was possible.

**Comment by carolinan** [comment]
I see it is listed here in the new reference https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/#color-2

**Comment by carolinan** [comment]
@Andrew-Starr Then I consider this solved. Thank you!
The theme.json how to guide doc still needs to be updated, making a mental note.
