### ISSUE TITLE
Keyboard shortcut to toggle settings/sidebar's display is not working 

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#38146]
### Description

The keyboard shortcut to [show/hide settings sidebar,](https://developer.wordpress.org/block-editor/explanations/faq/#editor-shortcuts) done by `Ctrl+Shift+,` for windows and linux users does not show/hide settings sidebar as expected. 

### Step-by-step reproduction instructions

1. create a new post or page
2. Press `Ctrl+Shift+,` (press simultaneously the control button, shift, and the comma) ( [shortcut and mac directions taken from the FAQ](https://developer.wordpress.org/block-editor/explanations/faq/#editor-shortcuts)

The sidebar panel displaying a block's settings or the page/post's setting should appear or hide. 

### Environment info

- ubuntu 18.04
- English (US) QWERTY keyboard
- Chrome and Firefox 86
- WordPress 5.8.3 and gutenberg 12.4.1. 

Krishna Thackur also reported in the [#core-editor](https://wordpress.slack.com/archives/C02QB2JS7/p1642784465410900) slack that he has the same behavior using 5.9-RC3-52601

**- Notably, the shortcut works as expected for me on WordPress 5.7 with gutenberg plugin deactivated**

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by apeksha10** [comment]
Hi ,
I am able to replicate the above issue in Windows
Steps
Chrome browser
WordPress (5.9-RC3-52617) and Gutenberg 12.4.1.
Click (Press Ctrl+Shift+,)
 4.   The sidebar panel displaying a block's settings or the page/post's setting doesn't hide.
See the video: https://www.screencast.com/t/Tbtlww8S

**Comment by letasync** [comment]
Hi @skorasaurus
Thanks for confirming & reporting.

My test env was
Chrome browser on Window 10
WordPress 5.9-RC3-52601 without gutenberg or any other plugin.
and WordPress 5.8 with gutenberg 12.04  without any other plugin.

**Comment by t-hamano** [comment]
I would like to close this issue as it has been fixed in #43428. If you still reproduce it, please feel free to reopen it.
