### ISSUE TITLE
Cannot preview the Spacer block and change space dimensions

### ISSUE THREAD

**Issue by liorken** [WordPress/gutenberg#38159]
### Description

The Spacer block is not appearing in the Preview and you cannot change the space height. It shows an error message on the Preview, saying you cannot view it in preview. 

### Step-by-step reproduction instructions

1. Add Gutenberg "Spacer" to post.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
Hi, @LKENL

Can you give us more details, like what version of the Gutenberg plugin and WordPress are you using?

**Comment by liorken** [comment]
Gutenberg is version 12.3.0.
Wordpress is 5.8.3


בתאריך יום א׳, 23 בינו׳ 2022, 18:55, מאת George Mamadashvili ‏<
***@***.***>:

**Comment by Mamaduka** [comment]
Thank you, @LKENL.

There was a similar issue #37758, but it should be fixed in 12.3.

Would it be possible to see a screenshot of the error message?

**Comment by liorken** [comment]
Hi,

Attached the screenshot. It's in Hebrew, but the block that appears on the
screen is the error message of the spacer.

‫בתאריך יום ב׳, 24 בינו׳ 2022 ב-11:59 מאת ‪George Mamadashvili‬‏ <‪
***@***.***‬‏>:‬

**Comment by Mamaduka** [comment]
Hello, @LKENL

It looks like email replies don't send attachments to GitHub.

You probably have to use the comment form on the website.

**Comment by liorken** [comment]
Hi, 
This is the screenshot of the block that says "An error has occurred with this block. And we cannot show a preview of it." - The spacer block. Thanks.


![screen](https://user-images.githubusercontent.com/98255377/153342943-2f98f964-0603-4377-aa12-22a9668e6080.jpg)
)

**Comment by Mamaduka** [comment]
Hi, @LKENL

Thank you for the screenshot. This issue should be fixed in Gutenberg 12.4 and later.

**Comment by adamwoodnz** [comment]
Closing following triage policy. Please reopen if Gutenberg 12.4 did not fix the issue.
