### ISSUE TITLE
Query Block: Allow developers to extend the attributes

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#38163]
## What problem does this address?
As raised in https://github.com/WordPress/gutenberg/issues/24934 not all the filter options are available to in the Query Loop Block. I understand that will take time. In the meantime, it would be useful to allow developers to extend the Query Block to add their own settings.

With a new PHP filter as mentioned in https://github.com/WordPress/gutenberg/issues/36504 would allow developers to extend the output on the front end but I could not find a way to extend the `query` parameter of [`getEntityRecords( 'postType', postType, query )`](https://github.com/WordPress/gutenberg/blob/2323eeca3d0bc8b2723333ccb831ae731ae841aa/packages/block-library/src/post-template/edit.js#L150) to include new parameters.

Currently, I am using the following code to add a new text field to support a new `include` attribute, which is a comma delimited string of IDs to test. 

```js
const addIncludePosts = ( settings, name ) => {
	if ( name !== 'core/query' ) {
		return settings;
	}

	return {
		...settings,
		attributes: {
			...settings.attributes,
			query: {
				...settings.attributes.query,
				include: {
					type: 'array',
					default: [],
				},
			},
		},
	};
};

addFilter(
	'blocks.registerBlockType',
	'required/query-block/include-posts',
	addIncludePosts
);

/**
 * Override the default edit UI to include a new block inspector control for
 * assigning the anchor ID, if block supports anchor.
 *
 * @param {WPComponent} BlockEdit Original component.
 *
 * @return {WPComponent} Wrapped component.
 */
const withInspectorControl = createHigherOrderComponent( ( BlockEdit ) => {
	return ( props ) => {
		if ( props.name !== 'core/query' ) {
			return <BlockEdit { ...props } />;
		}

		const { query } = props.attributes;
		const include = query.include || [];

		return (
			<>
				<BlockEdit { ...props } />
				<InspectorControls>
					<PanelBody
						title={ __( 'Select Posts', 'ph-blocks' ) }
						initialOpen={ true }
					>
						<TextControl
							label={ __( 'Posts', 'ph-blocks' ) }
							value={ include.join() }
							onChange={ ( value ) => {
								props.setAttributes(
									{
										query: {
											...query,
											include: value.split( ',' )
										}
									}
								);
							} }
						/>
					</PanelBody>
				</InspectorControls>
			</>
		);
	};
}, 'withInspectorControl' );

addFilter(
	'editor.BlockEdit',
	'required/query-block/with-include-posts-control',
	withInspectorControl
);
```

## What is your proposed solution?
Allow the query in `PostTemplateEdit` to be extended.

**Related Issues**
- https://github.com/WordPress/gutenberg/issues/34977
- https://github.com/WordPress/gutenberg/issues/30706
- https://github.com/WordPress/gutenberg/issues/24934
- https://github.com/WordPress/gutenberg/issues/36504

**Comment by sc0ttkclark** [comment]
Clever solution here @grappler!

**Comment by ntsekouras** [comment]
Thanks for the issue @msaari! I'm closing this as this has been implemented here: https://github.com/WordPress/gutenberg/pull/44093.


You can read more about extending [Query Loop in the related docs page](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/extending-the-query-loop-block/).

Feel free to reopen, if you need something more/different.
