### ISSUE TITLE
Cannot save "Make template part" when the template part name is in multibyte language

### ISSUE THREAD

**Issue by waviaei** [WordPress/gutenberg#38160]
### Description

In the new (theme) editor, one can save block(s) as template parts, accessed via the "three-dots" menu. It seems you cannot save it if multibyte language is used as template part name.

Looking at the console error, there seem to be something with creating slug from the input text? and JS has stopped there, resulting in "saving" to not finish.

I tried same thing with English template name, and it worked.

Note: I have not tested in other multibyte language such as CK, but looking at the nature of the issue, I am suspecting it is multi-byte related.

### Step-by-step reproduction instructions

1. Pick something and click the three-dots menu (Here, I made a tweak at Query Loop for Home template)
2. Click "Make template part"
3. Enter multibyte language e.g. `私のテンプレートパーツのテスト`
4. Click "Create"

You should see that Create button do the animation to save, but never seem to end. If you keep open the dev tool console tab, you should be able to see `Cannot read properties of undefined (reading 'slug) error.

<img width="1715" alt="スクリーンショット 2022-01-23 17 30 52" src="https://user-images.githubusercontent.com/1564991/150671133-5b0551f8-b82d-47c7-80d6-b48adfc051bf.png">
(here you seeing the error three times, because I attempted three times)

Repeat above with non-multibyte language and you won't encounter the error.

### Environment info

- WordPress 5.9-RC3-52619 (using beta plugin)
- Theme: I checked with Automattic's Blockbase (v 2.0.15) and Livro (1.0.1) from .org. I could not activate twentytwenty two, as I got "It is not compatible with this version of WordPress, please update".

Gutenberg is **deactivated**.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Here's the error from the REST API response:

```json
{"code":"rest_invalid_param","message":"Invalid parameter(s): slug","data":{"status":400,"params":{"slug":"slug does not match pattern [a-zA-Z0-9_\\-]+."},"details":{"slug":{"code":"rest_invalid_pattern","message":"slug does not match pattern [a-zA-Z0-9_\\-]+.","data":null}}}}
```

I also noticed that I could create Templates using multibyte string as a name, but then I'm getting the following error if I try to delete it.

```json
{"code":"rest_no_route","message":"No route was found matching the URL and request method.","data":{"status":404}}
```

**Comment by inc2734** [comment]
If insert a template part block and try to create a new template part block with multibyte characters, an error will occur.

<img width="1274" alt="スクリーンショット 2022-02-15 23 38 14" src="https://user-images.githubusercontent.com/1094306/154084109-41c38a5f-b916-4d1a-8341-f9378f89c785.png">

Gutenberg version: 12.7.20220214

**Comment by Mamaduka** [comment]
Thanks for contributing, @inc2734.

I thought I covered all cases. I will have a look tomorrow and create a follow-up PR.
