### ISSUE TITLE
Navigation Block Submenu Obfuscated by Block Toolbar

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/gutenberg#38165]
### Description

When I add a submenu navigation item, I cannot see the block I am typing in. It remains hidden by the block toolbar.

 

### Step-by-step reproduction instructions

1. Go to Editor > Navigation Block
2. Create several navigation items
3. Select on navigation item and add a submenu

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/5519705/150704688-62d48862-f1e8-4af4-8eed-be0431d7dcec.mp4

### Environment info

- WordPress 5.9rc3, Twenty Twenty Two, with and without Gutenberg 12.5.x
- Chrome Version 97.0.4692.71
- Mac Monterey

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting.

There's an existing issue for this in https://github.com/WordPress/gutenberg/issues/36977, so I'll close this as a duplicate.
