### ISSUE TITLE
How to disable color settings in the cover block in WP5.9

### ISSUE THREAD

**Issue by erikjoling** [WordPress/gutenberg#38176]
### Description

Prior to WP5.9 I disabled the color settings of the cover block using theme.json like this:

`"settings": {
    "blocks": {
        "core/cover": {
            "color": {
                "palette": []
            }
        }
    }
}`

It seems this no longer disables the cover settings (with color and transparancy options) in WordPress 5.9 (RC-3).

Update: this also seems to be the case for other blocks.

### Step-by-step reproduction instructions

-

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/20614110/150768007-5b4d2536-1ed0-477b-a5ef-cfae6a49abba.png)

### Environment info

- WordPress 5.9 RC-3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi, 
try combining it with `"defaultPalette":false`
See https://make.wordpress.org/core/2022/01/08/updates-for-settings-styles-and-theme-json/

**Comment by erikjoling** [comment]
Thank you @carolinan 

I managed to disable the color settings with `"defaultPallete": false` and `"defaultGradients": false`. 

With the following code I specify a custom color palette and disable it for certain blocks. 

```
{
	"version": 1,
	"settings": {

		"color": {
			"palette": [
				{
					"name": "Yellow",
					"slug": "yellow",
					"color": "#FEFF31"
				},
				{
					"name": "Green",
					"slug": "green",
					"color": "#00EA84"
				}
			],
			"custom": false,
			"defaultPalette": false,

			"gradients": [],
			"customGradient": false,
			"defaultGradients": false
		},
		"blocks": {
			"core/paragraph": {
				"color": {
					"palette": []
				}
			},
			"core/cover": {
				"color": {
					"palette": []
				}
			}
		}
	}
}
```

Extra remark: notice the difference in plurality of the keywords `customGradient` and `defaultGradients`.

**Comment by skorasaurus** [comment]
Thanks for confirming that you're able to disable the color settings. :)

**Comment by jacobdubail** [comment]
How do we achieve this in version 2?
