### ISSUE TITLE
Global Styles Customized Palette doesn't reflect changes

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#38185]
### Description

UPDATE: This only seems to be happening in WP 5.8.2, not in WP 5.9

When using the Global Styles panel to change the Color Palette the values do not persist.

The values are stored in the CPT and the site is updated but the colors do not reflect the changes made in the editor.

This includes adding NEW palette colors as demonstrated with "Empty Theme" as well as modifying existing palette color as demonstrated with "Blockbase".

### Step-by-step reproduction instructions

Using a fresh install of Wordpress 5.8.3 and the /trunk version of Gutenberg
Activate a Block theme (Empty Theme and Blockbase were evaluated)
Open the Site editor and navigate to Global Settings Color panel.

Add a color to the palette and save the settings.
Note that the palette is removed from the UI.

Modify a color palette color that already exists and is being used by the theme (such as "Primary" in Blockbase).
Save the changes.
Note that the color value changes made do not persist.
Load the site view, note that the color changes are reflected in the site.

### Screenshots, screen recording, code snippet

Adding a palette color to Empty Theme
![GS-bug](https://user-images.githubusercontent.com/146530/150817161-dc241a23-5812-4146-a547-84cf59d468bb.gif)

Adjusting an existing palette color in Blockbase
![GS-bug2](https://user-images.githubusercontent.com/146530/150817404-1b85c2db-c155-42d2-8a6a-2edf096eb1d0.gif)

### Environment info

- Wordpress 5.8.2
- Gutenberg /trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@pbking Just so I understand, this doesn't happen in 5.9? If so, can this issue be closed :D

**Comment by pbking** [comment]
Yes, that's correct @annezazu.  I didn't realize that when opening.

This can be closed.
