### ISSUE TITLE
`@wordpress/wordcount` planned support for Chinese, Japanese, etc characters?

### ISSUE THREAD

**Issue by thomasplevy** [WordPress/gutenberg#38186]
## What problem does this address?

I'd like to use the `@wordpress/wordcount` package in my plugin to provide word counting functionality, however based on my initial review of the package it only supports Latin-based character sets. For example, passing the following Japanese character string results to `count()` results in `2` being returned:

```js
import { count } from '@wordpress/wordcount';
const numberOfWords = count( 'これは一言です。 これは2番目の言葉です。', 'words', {} );
```

Ideally, too, I would like to be able to pass in a mix of Latin and non-Latin characters and still have word counting work as expected.

I'm currently investigating alternatives to a (now defunct) JS wordcounting solution and since I'm developing in a WordPress plugin using this package would be ideal. Though not currently possible.

I haven't tried to determine how this library is used internally so it's possible this will never be added or supported but I wanted to check just in case.

## What is your proposed solution?

Add support for additional character sets for the library.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/13796 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

**Comment by thomasplevy** [comment]
@skorasaurus my bad... I searched "wordcount" and that issue didn't come up (which I assumed it would). It didn't occur to me to check the package tag. My apologies for wasting your time on this.

**Comment by skorasaurus** [comment]
no problem, the other issue didn't have the package tag on it until I just added it, I only remembered seeing that other issue a while back, so you may not have found it  anyways :)
