### ISSUE TITLE
[Feature Request] Add the ability to duplicate a template in the Site Editor

### ISSUE THREAD

**Issue by aurooba** [WordPress/gutenberg#38192]
## What problem does this address?
There are scenarios where two templates might be pretty similar with just some changes. Being able to duplicate a template would save a lot of time and work. 

## What is your proposed solution?
It would be super helpful if the kebab menu offered a `duplicate` option in addition to the reset option. I think duplicating a template is mostly only useful when it has been customized, so I've create a little mockup reflecting that in the language. When a template is in its default state, it wouldn't need to have this option.

<img width="639" alt="Screen Shot 2022-01-24 at 5 09 13 PM" src="https://user-images.githubusercontent.com/6925260/150886192-214fd762-b748-4670-a058-16e38a853f2a.png">

**Comment by paaljoachim** [comment]
Hi @aurooba 

Here is an issue I made a while ago. There is some discussion there.
[Site Editor] Templates list screen - Adding duplicate to 3 dot menu.
https://github.com/WordPress/gutenberg/issues/36665

**Comment by aurooba** [comment]
Thanks for flagging that, @paaljoachim, I did a search before, but didn't see that issue!
