### ISSUE TITLE
Editor: Global styles printed without default block styles.

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#38196]
### Description

When the block editor was introduced, the styles were split in to two sets:

* default styles, enqueued by default (with the handle `wp-block-library`)
* enhanced styles (with the handle `wp-block-library-theme` and behind the theme supports flag `wp-block-styles`)

This left it possible to remove all block editor default styles from a site with the code: 

```php
wp_dequeue_style( 'wp-block-library' );
// OR wp_deregister_style( 'wp-block-library' );
remove_theme_support( 'wp-block-styles' ); // Safety
```

The introduction of the new inline styles with the handle `global-styles` introduces a backward compatibility break on the code above as the inline styles are registered on their own handle.

To avoid the backward compatibility break, they should really be registered as inline styles on the `wp-block-library` style sheet.

### Step-by-step reproduction instructions

1. In a non-block theme, add the following code:
   ```php
   remove_theme_support( 'wp-block-styles' ); // Not required if never added
   add_action( 'wp_enqueue_scripts', function(){
     wp_deregister_style( 'wp-block-library' );
   }, 15 );
   ```
2. Run the site on WP 5.8 -- observe no editor CSS is output.
3. Upgrade the site to WP 5.9 -- observe the editor global-styles CSS is output

### Environment info

- WordPress 5.9 RC4 (trunk at time of writing)
- No plugins activated, not even Gutenberg.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
Doing some issue triage. Looks like we missed this at that time. I feel today changing how things work would be a bigger breaking change. Should we close the issue?

**Comment by peterwilsoncc** [comment]
I agree, I'll close this as unplanned.
