### ISSUE TITLE
Complete the remaining steps needed for creating themes without code

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#38199]
## What problem does this address?
Changes made to block themes can be exported from the Site Editor. But the export it is not a complete working theme.
If the export was complete, users could create themes without knowing any code.

## What is your proposed solution?

The following is missing for it to be a complete theme:

**Short term:**

- Add an empty index.php file to the export..  Also see https://core.trac.wordpress.org/ticket/54272
- Add a basic style.css file to the export.   [Example style.css file header with theme info.](https://developer.wordpress.org/themes/basics/main-stylesheet-style-css/#example)

These two additional files are all that is missing to be able to activate the theme.

**Long term:**
- Export theme.json. #36619 #39048
- _Suggestion: Replace the style.css file with information from theme.json._
- Naming the theme on export #38194
- _Suggestion: Include license file and readme._

**Comment by dreaddymck** [comment]
An option to import/replace would be nice as well.

**Comment by scruffian** [comment]
What do you think about just exporting the whole theme, like this https://github.com/WordPress/gutenberg/pull/39202 ?

**Comment by carolinan** [comment]
I am not sure. Of course we need to look at it from user perspective too, not only our developer perspective.

-It is useful to get all the changes, since then we as developers do not need to copy paste template markup
-Will users believe they are creating a new theme? Will they not take their new zip file and try to install it? They would end up with two themes with the same name? Will the zip and folder have a unique name, or the current theme name?

**Comment by scruffian** [comment]
We have made some good progress on this. What do you think about closing it in favour of https://github.com/WordPress/gutenberg/issues/39189?
