### ISSUE TITLE
Add caption/label to `core/site-logo` block

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#38190]
## What problem does this address?
Sometimes one wants to add a caption/label/subheading (but not the site one) to a `core/site-logo` block.

## What is your proposed solution?
Add an optional caption/lable support to the `core/site-logo` block as it is already the case with the `core/image` block.

**Comment by richtabor** [comment]
I'd say it's probably better to keep the Site Logo block with a standalone purpose. If you wanted to add a snippet of text, or even the Site Tagline, you can do so by wrapping them within a Row block perhaps.
