### ISSUE TITLE
The title of the Widget Group block becomes h2.widget-title.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#38197]
### Description

Thank you for creating the widget group block.

However, I found one problem.

The title of the Widget Group block becomes `h2.widget-title`.

The class set in `register_sidebar()` is not used.

### Step-by-step reproduction instructions

1. For example, we can set the Widget Title to `div.c-widget__title` as follows

```
register_sidebar(
    array(
        'name'          => 'Sidebar',
        'id'            => 'sidebar-1',
        'before_widget' => '<div id="%1$s" class="c-widget %2$s">',
        'after_widget'  => '</div>',
        'before_title'  => '<div class="c-widget__title">',
        'after_title'   => '</div>',
    )
);
```

2. Use Widget Group block.

### Screenshots, screen recording, code snippet

<img width="420" alt="スクリーンショット 2022-01-25 12 38 22" src="https://user-images.githubusercontent.com/31400297/150907096-244dda10-960a-4310-8351-4eba07410e3c.png">

The `div#block-7` at the top of this image is the HTML for using the Widget Group.

And below it, `div#categories-2` is the HTML when using the Legacy Widget.

### Environment info

- WordPress 5.9 RC4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ddryo** [comment]
Additionally, there is a similar problem with https://github.com/WordPress/gutenberg/issues/33507

**Comment by ddryo** [comment]
So, the Title of the Widget area is a situation where various DOMs can be mixed as shown below.

- `h2.widget-title` (Title of the Widget Group block)
- `h2.widgettitle` (Title of the Legacy Widget manually placed in the Group block) 
- `div.c-widget__title` (A class specified by the theme. Legacy widgets that have been installed in the past.)
- Just an `h2` tag. (A widget tile that is initially placed when we install WordPress 5.8 on our site.)

**Comment by annezazu** [comment]
@kevin940726 any insight here?

**Comment by noisysocks** [comment]
This should be fixed by https://core.trac.wordpress.org/changeset/52730. Please test the WP 5.9.1 RC when it is released to confirm.
