### ISSUE TITLE
Use more specific naming in edit site export files

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#38194]
## What problem does this address?

* The filename used when exporting templates from the site editor is `edit-site-export.zip`.
* The directory name used when extracting an `edit-site-export.zip` file is `theme`.

My current (still figuring this out) workflow is to start with a blank canvas in the site editor, add blocks, and then export the templates so that I can use the markup in the theme for activation elsewhere.

Repeating this process causes my downloads directory to fill up with `edit-site-export.zip`, `edit-site-export(1).zip`, `edit-site-export(2).zip`, etc...

When I extract those zip files, they become `theme/`, `theme 2/`, `theme 3/`, etc...

When working on multiple sites/themes at once, this quickly becomes confusing OR I need to manually rename each one when downloading.

## What is your proposed solution?

* The default filename should be more specific. Something like `edit-site-{domain}-{yyyymmdd}.zip`
* The default compressed directory name should be more specific. Something like `edit-site-{theme-name}/`

It would also be ideal to have a filter for these filenames.

**Comment by scruffian** [comment]
The export now has the name of the theme. I think we can close this.
