### ISSUE TITLE
Allow enabling/disabling autogenerated anchors in heading blocks

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#38216]
## What problem does this address?
Gutenberg 11.8 introduced a mechanism to autogenerate HTML anchors in Heading blocks. While a useful enhancement, there are cases where it might desirable to disable the automatic generation of headings.

The desire to control this setting has been expressed a few times:
- [Original PR comment](https://github.com/WordPress/gutenberg/pull/30825#issuecomment-959051708)
- [Bug report](https://github.com/WordPress/gutenberg/issues/38171)
- [Another comment in a related issue](https://github.com/WordPress/gutenberg/issues/36365#issuecomment-1020761232)

## What is your proposed solution?

Adding a flag to enable/disable the automatic anchor generation would provide developers the flexibility to decide whether to use them or not. Some implementation options include:
- Adding a flag to disable the automatic generation.
- Disabling again the automatic generation by default, and adding a flag to enable the anchor generation.
- In case the automatic generation is disabled by default, enable it if a ToC block exists in the current page/post.

**Comment by Mamaduka** [comment]
@priethor, let's add the "Needs Design" label as well.

I think this option can be placed in the "Preferences" panel, but I'm not exactly sure where.

**Comment by skorasaurus** [comment]
I'm a little confused why we should make another issue when there is already https://github.com/WordPress/gutenberg/issues/38171 open with this; please reopen and explain if this very different than the existing issue.

**Comment by priethor** [comment]
I opened this as a feature enhancement proposing different solutions and consolidating previous discussions around the subject, as #38171 was reported as a bug. I'm happy to continue work on that issue but I would recommend clarifying the issue title and description in that case.

**Comment by annezazu** [comment]
@priethor renamed the other issue to make it clearer - can you comment on that issue to consolidate all of this great information? Love your solutions.
