### ISSUE TITLE
Make Featured Image size controls available in Full-Site Editor (Template Parts)

### ISSUE THREAD

**Issue by sdwire** [WordPress/gutenberg#38211]
## What problem does this address?
[This PR](https://github.com/WordPress/gutenberg/pull/38044) added size controls to the Post Featured Image block. Those size controls are available within the block editor of a single post or page, but they are not available when editing a Post Featured Image block from the Full-Site Editor when adding the featured image to a template part.

## What is your proposed solution?
Make the new size controls for the Post Featured Image block available in the Full-Site Editor just like they are in the Post/Page editor

**Comment by carolinan** [comment]
This has been fixed. I don't know the exact version it was fixed in, but when I retest with Gutenberg version 14.0.2, the size controls are present in the site editor, inside and outside of queries and inside and outside of template parts.
