### ISSUE TITLE
WP 5.9-RC3: Block patterns library issues

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#38214]
### Description

I’ve noticed multiple issues with block patterns library in editor. This is related to WordPress 5.9-RC3 and does not happen on WordPress 5.8.3.

1. Patterns in the library **does not pick up theme styles**. I suspect this may be due to the theme adding editor styles via [`enqueue_block_editor_assets` action hook](https://developer.wordpress.org/reference/hooks/enqueue_block_editor_assets/). This worked on WP5.8.3 without issues though.
2. When there is a full screen Cover block in the pattern the **preview container gets constantly higher and higher**.
3. The **height of the pattern preview is wrong**, unlike in WP5.8.3 as can be seen in the videos below. This is most likely related to previous issue too.

### Step-by-step reproduction instructions

Here is the code of the block pattern that causes continual height change issue:
```html
<!-- wp:cover {"url":"https://pic.webmandesign.eu/WMDEMO/texture--pexels-adrien-olichon-2387532.jpg","id":999999,"dimRatio":80,"customOverlayColor":"#010101","minHeight":100,"minHeightUnit":"vh","contentPosition":"bottom center","align":"full","style":{"spacing":{"padding":{"bottom":"120px","right":"0px","left":"0px"}}}} -->
<div class="wp-block-cover alignfull has-background-dim-80 has-background-dim has-custom-content-position is-position-bottom-center" style="padding-right:0px;padding-bottom:120px;padding-left:0px;background-color:#010101;min-height:100vh"><img class="wp-block-cover__image-background wp-image-999999" alt="" src="https://pic.webmandesign.eu/WMDEMO/texture--pexels-adrien-olichon-2387532.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:spacer {"className":"has-20vmax-min-height"} -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer has-20vmax-min-height"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide","className":"is-style-stacked-on-tablet"} -->
<div class="wp-block-columns alignwide is-style-stacked-on-tablet"><!-- wp:column {"width":"50%"} -->
<div class="wp-block-column" style="flex-basis:50%"><!-- wp:heading {"fontSize":"huge"} -->
<h2 class="has-huge-font-size">Write some title text here</h2>
<!-- /wp:heading --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"20%","className":"is-style-hidden-on-tablet"} -->
<div class="wp-block-column is-style-hidden-on-tablet" style="flex-basis:20%"></div>
<!-- /wp:column -->

<!-- wp:column {"width":"30%"} -->
<div class="wp-block-column" style="flex-basis:30%"><!-- wp:spacer {"height":40} -->
<div style="height:40px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Just a short sentence. This is just a demo text you should overwrite. Write your own copy text here. This is just a demo text you should overwrite. Write your own copy text here. Just a short sentence.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link" href="#0">Click here →</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link" href="#0">Click here →</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:cover -->
```

### Screenshots, screen recording, code snippet

Video preview of the issues in WP 5.9-RC3:
https://user-images.githubusercontent.com/2456735/151014137-3b2b36ce-7bdd-4174-839d-cb37918d846d.mp4

Expected behavior (taken in WP 5.8.3) with no issues:
https://user-images.githubusercontent.com/2456735/151014155-40415aaf-f0fd-4534-931f-a265fa399a82.mp4

### Environment info

- WordPress 5.9-RC3
- Theme: Michelle 1.3.0, https://wordpress.org/themes/michelle/ (publicly available is only version 1.2.0, but the issues should occur there too; otherwise the current 1.3.0 code can be obtained from https://github.com/webmandesign/michelle)
- Also activated Gutenberg plugin version 12.4.1 but the result is the same as with pure WP 5.9-RC3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by hellofromtonya** [comment]
Hello @webmandesign 👋 

To link everything together, these issues were reported [in the support forum](https://wordpress.org/support/topic/wp-5-9-rc3-block-patterns-library-issues/) and [Trac](https://core.trac.wordpress.org/ticket/54901). And thank you for opening the issue here.

Shortly before you opened this issue, @Mamaduka replied to you in the support forum topic. Capturing the reply:

Here's @mamaduka reply: 

>Hello, Oliver
>
>1. You’re correct. The editor styles loaded via enqueue_block_editor_assets won’t work in future WP version. It’s [recommended](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#editor-styles) to use add_editor_style for block editor styles as well.
>
>2-3. Using full viewport height (100vh) in patterns was causing some unexpected behavior. WP 5.9-rc4 [fixed](https://github.com/WordPress/gutenberg/pull/38175) these issues.

**Comment by webmandesign** [comment]
Thank you @hellofromtonya for pointing me to the correct place where I can discus this issue.

> 1. You’re correct. The editor styles loaded via enqueue_block_editor_assets won’t work in future WP version. It’s recommended to use add_editor_style for block editor styles as well.

That’s unfortunate. I know I had some issues with `add_editor_style` for my particular use in the past, but I will have to try it again then.

From top of my head, how could I enqueue customized CSS variables to editor with `add_editor_style`? My themes use customizer to customize colors and other options which are ported to CSS via CSS variables. Is there a way to enqueue this PHP generated CSS code with `add_editor_style` somehow? Thanks for any info in advance.

**Comment by webmandesign** [comment]
OK, I've found out these:

#### 1. `enqueue_block_editor_assets` still works in patterns

The `enqueue_block_editor_assets` action hook still works even in block patterns library/inserter. The issue was with my theme's block editor styles using `div.editor-styles-wrapper`, while the new block pattern previews are iframes with `body.editor-styles-wrapper`.

Fixed this by adapting my theme's block editor stylesheet.

#### 2. Can not load Google Fonts to pattern preview iframe

I've noticed that `enqueue_block_editor_assets` action hook does not load all stylesheets I throw at it in block pattern preview. I've found out it only loads the stylesheets containing `.editor-styles-wrapper` string. Can anybody provide more info why this happens, and _can this be documented somewhere for theme authors_?

So, loading Google Fonts via stylesheet URL (such as https://fonts.googleapis.com/css?family=Josefin+Slab%3A300%2C400%2C700&display=swap) doesn't work as the stylesheet is being removed by Gutenberg from block pattern preview iframe.

I went ahead and tried inline CSS code with `@import url('https://fonts.googleapis.com/css?family=Josefin+Slab%3A300%2C400%2C700&display=swap');`. This does not work either, but I expect browser preventing cross-origin sources in iframe in this case.

So, my question now is how to load Google Fonts to block pattern preview so it is consistent with editor preview?

![block-patterns--google-font-issue](https://user-images.githubusercontent.com/2456735/151166845-4416e2c3-22b6-4c98-b79e-e5247723f7c2.png)

**Comment by webmandesign** [comment]
Closing this issue and opening new #38240 for the last issue found.
