### ISSUE TITLE
Block based theme : Image Block : Circle Style : 404 on mask url

### ISSUE THREAD

**Issue by MarieComet** [WordPress/gutenberg#38223]
### Description

With a block based theme (using theme.json), the Circle Style on Image block give a 404 error on mask URL, and image is not visible at all.

The CSS rule : 
```
.wp-block-image.is-style-circle-mask img {
  -webkit-mask-image: url('/wp-includes/blocks/image/data:image/svg+xml;utf8,<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"/></svg>');
  mask-image: url('/wp-includes/blocks/image/data:image/svg+xml;utf8,<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"/></svg>');
  mask-mode: alpha;
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
  -webkit-mask-size: contain;
  mask-size: contain;
  -webkit-mask-position: center;
  mask-position: center;
  border-radius: 0;
}
```

Visible here (left column) https://mariecomet.fr/a-propos/

### Step-by-step reproduction instructions

1. Use a block based theme, for example TT1 Blocks
2. Inside editor, inset an Image Block and set style to "Circle"
3. View the post in front

### Environment info

- WP 5.9
- TT1 Blocks (tt1-blocks) 0.4.8

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MarieComet** [comment]
Maybe I should move this issue to core.trac.wordpress.org ?
Let me know.

**Comment by annezazu** [comment]
I can't replicate this with 5.9 using TT2 or TT1 @MarieComet with the Post or Site editor! Can you share more info for replication?

**Comment by Mamaduka** [comment]
I don't think we have a "Circle" style for the core image block. There's Rounded, but it doesn't use an image mask as seen in example markup.

**Comment by adamwoodnz** [comment]
Closing following triage policy
