### ISSUE TITLE
WP 5.9: Block pattern preview does not apply correct `box-sizing` styles

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#38239]
### Description

While in block editor, the `box-sizing: border-box;` style is applied, in block patterns preview in patterns library/inserter the style is missing, thus rendering block pattern previews inconsistent from block editor previews.

### Step-by-step reproduction instructions

Compared Media & Text content spacing in block pattern preview and in editor/front-end.

### Screenshots, screen recording, code snippet

![wp5 9-block-patterns--no-box-sizing-styles](https://user-images.githubusercontent.com/2456735/151176807-e849d977-bbf8-4073-921e-548725195c84.png)

### Environment info

- WP 5.9
- Theme Michelle 1.3.0, https://github.com/webmandesign/michelle

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment]
Hey @webmandesign! Love seeing you open up some issues. I'm going to close this out as this overlaps with this currently open and worked on issue: https://github.com/WordPress/gutenberg/issues/37573 Mind commenting there?

**Comment by webmandesign** [comment]
Hi @annezazu :)

Thanks for your comment. I'm not sure whether this is related to #37573 actually. Though I'm going to provide my 2 cents to that issue too, I think this one is different.

This issue is really related to `box-sizing: border-box;` style not being applied by Gutenberg plugin in block pattern preview.
Once I apply
```scss
.editor-styles-wrapper {
	box-sizing: border-box;

	*,
	*::after,
	*::before {
		box-sizing: inherit;
	}
}
```
in my theme's block editor stylesheet that is also being enqueued in block pattern preview, this issue is resolved.

I just think those styles should be applied by Gutenberg plugin the same as [it is doing for editor](https://github.com/WordPress/gutenberg/blob/21dfe879f8193c747c4cc05cb79143fa90d74db2/packages/edit-post/src/style.scss#L70) - respectively [here](https://github.com/WordPress/gutenberg/blob/8cd3c473f4aacd3dc611f5797d1cf94d5c883266/packages/base-styles/_mixins.scss#L375).

**Comment by annezazu** [comment]
Gotcha! Let me re-open this then for good measure :)

**Comment by jordesign** [comment]
Hi @webmandesign  - I'm taking a look at this and unable to recreate any more - could you please confirm if you've still got that issue taking place with the most recent version of Gutenberg?

**Comment by webmandesign** [comment]
Hey @jordesign!
I've just checked and the issue still persists (when I remove the `box-sizing` styles from my theme's editor stylesheet). The core does not seem to apply `box-sizing: border-box;` in the pattern preview. But not even in the block editor content, actually. So it seems this is intentional and you can close the issue.

---

**Here is some more info I've found now:**

- It seems it affects only "classic" themes, the themes without `theme.json`.
- I haven't tested with a "hybrid" theme though (a classic theme with `theme.json`).
- Since I started developing block themes I don't experience this issue.
- And I've fixed the issue in my classic themes by adding [`box-sizing` styles to their block editor stylesheet](https://github.com/webmandesign/michelle/blob/master/assets/scss/editor-block/_base.scss#L6). So, maybe that's how it should be done in classic themes as WordPress does not know if the theme actually wants to use `box-sizing: border-box;`.
- Also, reading [the code comment](https://github.com/WordPress/gutenberg/blob/21dfe879f8193c747c4cc05cb79143fa90d74db2/packages/edit-post/src/style.scss#L62) it really seems the actual block content should not be affected by `box-sizing` styles anyway, if I understand it correctly.
- And finally, the same discrepancy is affecting the actual block editor content. I haven't noticed this before probably because I've used more specific selector to apply the `box-sizing` in editor.

Sorry for confusion caused and thank you for assistance! You can close the issue.
