### ISSUE TITLE
Can not load Google Fonts to pattern preview iframe

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#38240]
### Description

I've noticed that `enqueue_block_editor_assets` action hook does not load all stylesheets I throw at it in a block pattern preview. I've found out it only loads stylesheets containing `.editor-styles-wrapper` string. Can anybody provide more info why this happens, and _can this be documented somewhere for theme authors_?

This means loading Google Fonts via stylesheet URL (such as https://fonts.googleapis.com/css?family=Josefin+Slab%3A300%2C400%2C700&display=swap) doesn't work as the stylesheet is being removed by Gutenberg from block pattern preview iframe.

I went ahead and tried inline CSS code with `@import url('https://fonts.googleapis.com/css?family=Josefin+Slab%3A300%2C400%2C700&display=swap');` but this does not work either, though I expect browser preventing cross-origin sources in iframe in this case.

I presume block patterns are now (since WP 5.9) displayed within iframes only.
So, my question is how can I load Google Fonts to block pattern preview so it is consistent with editor preview?

### Step-by-step reproduction instructions

This actually depends on a theme. If a theme allows setting up Google Fonts font for typography and this font is being loaded from Google Fonts website, the issue occurs.

You can test this with Michelle theme (see "Environment info" below):
1. Go to _Appearance &rarr; Customize &rarr; Theme Options &rarr; Typography_ and set a different Google Fonts font for "Global font" and "Headings font".
2. Create a new page and insert a block pattern to its content.
3. Compare the font in page content preview in editor and in the block pattern library/inserter. The fonts are different as block pattern preview does not allow loading Google Fonts.

### Screenshots, screen recording, code snippet

![block-patterns--google-font-issue](https://user-images.githubusercontent.com/2456735/151166845-4416e2c3-22b6-4c98-b79e-e5247723f7c2.png)

### Environment info

- WP 5.9
- Theme Michelle 1.3.0, https://github.com/webmandesign/michelle

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by webmandesign** [comment]
For illustration, here is a video with comparison to WP 5.8.3 behavior:

https://user-images.githubusercontent.com/2456735/151227953-6efab67e-9a9d-48ca-9243-be66eb28b16d.mp4

**Comment by pjoulot** [comment]
_"I've noticed that enqueue_block_editor_assets action hook does not load all stylesheets I throw at it in a block pattern preview. I've found out it only loads stylesheets containing .editor-styles-wrapper string. Can anybody provide more info why this happens, and can this be documented somewhere for theme authors?"_

I have the same issue the update of wordpress 5.9 broke the preview feature. The styles were added with enqueue_block_editor_assets but they do not apply anymore. Adding `.editor-styles-wrapper`  doesn't seem to fix the issue though, and the documentation is not saying anything about this. The update has been out for a while, I am surprised that not more people encountered that regression.

**Comment by chthonic-ds** [comment]
Have you tried bundling your font requests with `add_editor_style()`?

In WP 5.9, I see fonts present in pattern previews using this approach:

```
function do_editor_styles() {
  add_editor_style(
    array(
      'editor-styles.css',
      'https://fonts.googleapis.com/css?family=Josefin+Slab%3A300%2C400%2C700&display=swap',
    )
  );
}

add_action( 'after_setup_theme', 'do_editor_styles' )
```

**Comment by htmgarcia** [comment]
@pjoulot as @chthonic-ds suggest, to load CSS in Site Editor iframe, the only way is through `add_editor_style()`, which will automatically set .editor-styles-wrapper for your CSS (due will be outputted directly in head, not as a linked file)

**Comment by webmandesign** [comment]
> I have the same issue the update of wordpress 5.9 broke the preview feature. The styles were added with enqueue_block_editor_assets but they do not apply anymore. Adding `.editor-styles-wrapper` doesn't seem to fix the issue though, and the documentation is not saying anything about this. The update has been out for a while, I am surprised that not more people encountered that regression.

@pjoulot Please check my reply at https://github.com/WordPress/gutenberg/issues/38214#issuecomment-1022172779 The issue for me was that I've used `div.editor-styles-wrapper` while block pattern preview is `body.editor-styles-wrapper`. If you are using pure `.editor-styles-wrapper` in your stylesheet it should work, though.

Check the iframe code with your browser code inspector to see what's going on in there if the styling issue persist.

Though please note that Google Fonts (or any 3rd party domain asset) is still not loaded in block preview, so the original issue I've reported here persist.

**Comment by webmandesign** [comment]
> Have you tried bundling your font requests with `add_editor_style()`?
> In WP 5.9, I see fonts present in pattern previews using this approach:

You are right, this might work as expected as the content of external stylesheet URLs are actually retrieved by WordPress with `wp_remote_get()` and then inlined. So no external domain request is being executed in iframe this way.

Thanks for pointing me to the right direction! Fixed :)

**Comment by timsinc** [comment]
Unfortunately, this still doesn't work if the external resource uses relative urls. Like `https://rsms.me/inter/inter.css` for instance 😞
