### ISSUE TITLE
Highlight text: Format button doesn't match current color when moving the caret

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#38246]
## Description

While testing the Highlight text feature, especially the changes introduced in https://github.com/WordPress/gutenberg/pull/37915, I noticed that the format button doesn't reflect the current color when placing the caret at the end of the text (see attached video capture).

## Step-by-step reproduction instructions

1. Add a Paragraph block.
2. Type some text.
3. Tap on the Highlight text format button and select a color.
4. Type some more text and observe that the selected color is applied to the text written.
5. Move the caret around and place it at the end of the text.
6. Type some more text.
6. Observe that the text written has previously selected color but the Highlight text format button shows no color.

## Expected behaviour

After moving the caret, the Highlight text format button should reflect the same color as the one applied to the text.

## Actual behaviour

After moving the caret, the Highlight text format doesn't reflect the same color as the one applied to the text.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/151197430-64be7ec3-cea8-4304-a4d6-eb1514adcc20.MP4

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 11
- Operating system: iOS 15.1
- WordPress app version: 19.1

**Comment by mchowning** [comment]
In addition, it seems that the behavior is quite a bit worse when swiping words on iOS. The swiping, as opposed to typing--of the words seemed to be important in recreating the issue. I'm not sure what original priority was assigned to this issue, but the behavior when swiping on iOS seems pretty poor to me and feels like it would justify making this a higher priority.

### Not Resetting Color

For example,

1. Create a new paragraph block
2. Apply a highlight color
3. Swipe a word (observe that the highlight color is applied)
4. "Reset" the highlight color (or change to a different color)
5. Swipe a second word (observe that the original highlight color persists).

https://user-images.githubusercontent.com/4656348/153029522-e5a280f5-47bc-4a21-ad8f-524028d49135.mov

### Resetting Color on "Earlier" Words

Now this is a fun one. With some persistence, I can get the color of "earlier" words to sometimes "update". It seems to happen more often when iOS autocorrects a word. 😮

https://user-images.githubusercontent.com/4656348/153038452-db01cf9d-77de-4a12-b3bb-a0d8be5ed189.mov

**Comment by geriux** [comment]
Thanks for the report!

> but the behavior when swiping on iOS seems pretty poor to me and feels like it would justify making this a higher priority.

Yeah, I think we should look into this and try to tackle the pending bugs related to this feature including the swiping words one.

**Comment by fluiddot** [comment]
I confirmed this is still reproducible in version 23.9. I'd keep the [Priority] High` label as it affects the writing flow.

@geriux I saw that you were working on a fix on Aztec ([reference](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1352#issuecomment-1353481639)) some time ago. I'm wondering if we could resume the work, let me know if I can help anyhow. Otherwise, feel free to unassign from the issue.

**Comment by geriux** [comment]
> @geriux I saw that you were working on a fix on Aztec (https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1352#issuecomment-1353481639) some time ago. I'm wondering if we could resume the work, let me know if I can help anyhow. Otherwise, feel free to unassign from the issue.

I'm going to pick this up this week, so we can move forward with that fix.
