### ISSUE TITLE
WP 5.9 theme.json schema doesn't allow setting the "version" property to 2

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#38242]
### Description

The new Twenty Twenty-Two theme ships with a theme.json file with the "version" property set to 2, but the WP 5.9 theme.json schema (https://schemas.wp.org/wp/5.9/theme.json) just allows the 1 value.

### Step-by-step reproduction instructions

1. Open a version 2 theme.json file with VS Code
2. Add the WP 5.9 theme.json schema (https://schemas.wp.org/wp/5.9/theme.json) to it
3. The "version" property is highlighted (Value is not accepted)

### Screenshots, screen recording, code snippet

![schema](https://user-images.githubusercontent.com/2060659/151190926-53147479-a277-434e-b5a7-37b08f41bba9.jpg)

### Environment info

- WordPress 5.9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment]
@mkaz @ryanwelcher can you all chime in here based on your work in this area?

**Comment by ryanwelcher** [comment]
Looks like it needs to be updated in the 5.9 branch - https://github.com/WordPress/gutenberg/blob/wp/5.9/schemas/json/theme.json#L1070.

**Comment by ryanwelcher** [comment]
@ajlende do we need to cherry-pick #36917 into the 5.9 branch?

**Comment by ajlende** [comment]
This affected [more than just the version tag](https://github.com/WordPress/gutenberg/pull/38294#issuecomment-1023593385). It looks like not all of the commits were labeled for inclusion in the release. I added the `Backport to WP Minor Release` label to everything affected, so the changes should be reflected when 5.9.1 lands.

**Comment by ocean90** [comment]
The version was updated in https://github.com/WordPress/gutenberg/commit/b23854a833b861ed31db74e918a5e1e1201d2023.
