### ISSUE TITLE
Mobile and Tablet preview closes tabs in Inspector

### ISSUE THREAD

**Issue by wpsoul** [WordPress/gutenberg#38258]
### Description

When I work on complex blocks and edit them in Inspector, I want to check how it looks in Mobile. But when I click to preview, whole Inspector reverts to initial state, so, I need to open all tabs again and scroll to option which I edit before. This makes very uncomfortable workflow. What I expect is that preview option will not change anything in Inspector

### Step-by-step reproduction instructions

1. Add any block on page
2. Open any closed tab in Inspector
3. Enable Preview option in Mobile or Tablet

You will see that all panels are shifting to initial state

### Screenshots, screen recording, code snippet

[Video](https://monosnap.com/file/jF11NaQpa4xhMOoNpuhRGXzIdu0n9V)

### Environment info

Wordpress 5.9 version

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I can confirm this. That seems like a frustrating bug. Thanks for reporting it.

**Comment by Mamaduka** [comment]
I'm no longer able to reproduce the issue. However, it might be due to the recent refactoring of some panels.

P.S. I think the switch from Desktop to Tablet/Mobile remounts the sidebar; this could be the cause of initial state loss.

## Screencast

https://user-images.githubusercontent.com/240569/167556008-4ab743e0-e0b7-40bf-bf0d-267d6a244784.mp4

**Comment by talldan** [comment]
It does still seem to happen for any sections that expand/collapse and are collapsed by default. For example if you expand 'Advanced', and then change the preview.

It does seem a bit better now because many of the sections are not of that style.

**Comment by youknowriad** [comment]
I can't reproduce this with the "Advanced" panel. I guess that's fixed.
