### ISSUE TITLE
Buttons: Add ability to apply styling from one Button block to all adjacent buttons in the same Buttons block

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#38267]
## What problem does this address?

Following on from the UX improvement in #37904 to copy button styling from adjacent buttons when inserting a button block, it'd be nice to come up with a way to easily copy the styling from one button in a set of buttons to the rest of the buttons within that same set.

Currently if you make changes to one block in isolation, there's no easy way to immediately apply those changes to all other blocks within the set. You have to already know to select all blocks at the one time. Imagine, as a user, making a change to one block as in the following screenshot, and then wanting to apply that style to all the other blocks in the set:

![image](https://user-images.githubusercontent.com/14988353/151299099-1110f1c5-7da2-40b0-8e9c-726d521f92b5.png)

## What is your proposed solution?

One option would be to provide a control at the individual block level (e.g. a button) to copy styling to all similar nearby blocks (kudos @mtias for the idea). This would primarily be to solve this issue for the Button / Buttons blocks, to make it easier to adjust the styling for one set of buttons, however it could be worth exploring a more general solution if it seems valuable for other blocks (e.g. images within a gallery block).

**Comment by ZebulanStanphill** [comment]
Divi has had a copy-styles feature for a few years now.

https://www.elegantthemes.com/blog/theme-releases/divi-feature-update-a-game-changing-new-way-to-be-creative-with-divi

Thanks to the standardization brought by the global styles system, I think it's definitely feasible to have something similar in Gutenberg.

Also, I imagine that the code added in #37596 might provide a little inspiration for how to implement a copy-styles feature.

**Comment by stackpath-andrew** [comment]
Sorry if this isn't relevant to the issue, but its the closest issue I have seen to my issue...

I have been struggling to get Border color options working in the editor for the button block. Is this possible? I tried enabling the appearanceTools and setting the blocks > core/button > border: { color: true }... but this isn't working. Any help is appreciated

**Comment by annezazu** [comment]
Could this be closed, considering we have the ability to copy/paste styles as well as customizing one button and creating a new one keeping the prior design?

**Comment by andrewserong** [comment]
Yes, of course, let's close this out 👍
