### ISSUE TITLE
Making groups as default wrapper

### ISSUE THREAD

**Issue by mertafor** [WordPress/gutenberg#38271]
## What problem does this address?

Sorry if this is a duplicate or someone mentioned this before. I have this certain problem since Gutenberg released and I was hoping devs would look into this at some point. But I see that still there are no viable solutions after several years of development.

I understand the minimalist approach yet this is a page editor and users should easily select and edit buttons without a hassle. Once I add a block, especially using Columns and other nested block types, there is no easy way to select this block and make changes. Whenever I click on a block, first I try to find out which block is currently selected. Is it an inner block or wrapper block? Deleting a Columns block is a real pain. You can't simply select the parent delete or modify everything. Every single three dot menus provides tons of styles and alignment options. I'm a WP developer and sometimes even I don't understand where I am and what I'm doing. In the end I delete this specific block and start over. In my opinion, editor requires certain UX improvements to fix these issues. 

## What is your proposed solution?

Almost all WP page builders, (Elementor, WPBakery etc.) use a default wrapper called Row. In other words it's a section wrapper div. Users can build the content into rows easily. Because even it's a front-end editor, you see its borders and setting buttons on hover or they're always visible. This clear separation and modification buttons make everything much clear to work with. Gutenberg's minimalistic approach makes it look cleaner maybe but it causes several usability issues. 

Gutenberg already has a feature called Group that does a very similar job to build nested blocks. Using Group as default wrapper  for a new block section could make things much easier to navigate, modify and delete. 

I'm sure it's very difficult to implement at this point, yet I wanted to mention this issue in case you'd consider improving it.

**Comment by talldan** [comment]
@mertafor There is now a row variation of the group block - https://github.com/WordPress/gutenberg/pull/34535.

It isn't a default or anything, though. That would be another step and I don't know whether it's something that's planned.

**Comment by mertafor** [comment]
@talldan It's my bad. Yes now I noticed rows also. However what I was trying to mention is the difficulty of navigating between blocks in nested blocks due to lack of visual guides (lines, borders, settings buttons etc.). 

In fact, I think it could be possible by using custom editor styling in a theme. But is there any way to changing the starter template of default Add new post / page? For example Add New Page creates a new page with single empty paragraph block. Is it possible to change it to a paragraph wrapped in a row through native WP functions?

Edit : After looked up that on Google, I found out that I can achieve this by using altering default templates.

**Comment by annezazu** [comment]
Going to close this out as the final piece of feedback around navigating nested blocks without visual guides has been covered across a few issues including: https://github.com/WordPress/gutenberg/issues/23892 Let me know if you believe anything remaining needs to be addressed though and I can reopen!
