### ISSUE TITLE
Examples on block variations

### ISSUE THREAD

**Issue by corbin-c** [WordPress/gutenberg#38279]
### Description

Hi,

It looks like the feature allowing one to provide specific examples for block variations is not working properly.

As stated in the [official WP documentation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/), we can supposedly use the `example` field to achieve this:

> example (optional, type Object) – Example provides structured data for the block preview. You can set to undefined to disable the preview shown for the block type. 

To my understanding, I should be able to produce a different example for each variation of a block, or even disable the preview for a given variation by setting the `example` field to `undefined`

None of this works. I still get the same example for each variation.

### Step-by-step reproduction instructions

1. Extend a native block to provide it with a new variation. For example, we extend the `core/paragraph` to create a "catchphrase" variation. This variation has a field `example` correctly defined.

```JSX
import { addFilter } from "@wordpress/hooks";

const paragraphSettings = (settings, name) => {
  if (name !== "core/paragraph") {
    return settings;
  }
  settings.attributes.variation = {
    type: "string",
    default: ""
  };
  settings.example: {
    variation: "",
    content: "Lorem ipsum dolor sit amet"
  };
  settings.variations = [{
      icon: "sticky",
      name: "catchphrase",
      title: "Catchphrase title",
      description: "Catchphrase description",
      attributes: {
        variation: "catchphrase"
      },
      example: {
        attributes: {
          variation: "catchphrase",
          content: "This is a catchphrase."
        }
      },
      isActive: (blockAttributes, variationAttributes) => { 
        return blockAttributes.variation === "catchphrase"
      }
    }]
  return settings;
}

addFilter(
  "blocks.registerBlockType",
  "gutenberg/issues/paragraph",
  paragraphSettings
);
```
2. Open the block editor and observe. The "catchphrase" variation is working, yet the example is the same as the paragraph (see screenshots attached below).

### Screenshots, screen recording, code snippet

![scr1](https://user-images.githubusercontent.com/43074339/151361411-1f9187e8-c55f-491a-871d-c8386439d065.png)
![scr2](https://user-images.githubusercontent.com/43074339/151361416-4d0f7180-6e8a-4279-99c2-62f522e86dcc.png)

### Environment info

- Wordpress 5.9
- Firefox 95

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gaambo** [comment]
I can confirm this issue also happens when registering a custom variation via `registerBlockVariation`. I've tried both `isDefault` states - it doesn't change the preview in the inserter.
In my case I do not have a specific `variation` attribute. 

```js
registerBlockVariation("core/media-text", {
    name: "cta-banner",
    isDefault: false,
    icon: "megaphone",
    title: __("Call-to-Action Banner"),
    description: __("Ein CTA-Banner mit Bild, Text und Button.", "zwettler"),
    attributes: {
      mediaPosition: "left",
      isStackedOnMobile: true,
      align: "full",
      backgroundColor: "oil-light",
      textColor: "white",
      className: "cta-banner",
    },
    isActive: (block, variation) => {
      return block.className.includes("cta-banner");
    },
    innerBlocks: [
      [
        "core/heading",
        {
          level: 2,
          fontSize: "headline-2",
          className: "is-style-with-signature",
          textColor: "white",
        },
      ],
      ["core/paragraph"],
      [
        "core/buttons",
        {
          layout: {
            type: "flex",
            justifyContent: "right",
            orientation: "horizontal",
          },
        },
        [["core/button", { className: "is-style-fill", text: "Tour buchen" }]],
      ],
    ],
    example: {
      attributes: {
        mediaPosition: "left",
        isStackedOnMobile: true,
        align: "full",
        backgroundColor: "oil-light",
        textColor: "white",
        className: "cta-banner",
        mediaType: "image",
        mediaUrl: "/wp-content/themes/zwettler/example-data/cta-banner.jpg",
      },
      innerBlocks: [
        {
          name: "core/heading",
          attributes: {
            content:
              'Come to meet <mark style="background-color:rgba(0, 0, 0, 0)" class="has-inline-color has-beer-light-color">us</mark>',
            level: 2,
            fontSize: "headline-2",
          },
        },
        {
          name: "core/paragraph",
          attributes: {
            content:
              "Most modern breweries use with continuous sparge,<br>collecting the original wort and the sparge water.",
          },
        },
        {
          name: "core/buttons",
          attributes: {
            layout: {
              type: "flex",
              justifyContent: "right",
              orientation: "horizontal",
            },
          },
          innerBlocks: [
            {
              name: "core/button",
              attributes: { className: "is-style-fill", text: "Tour buchen" },
            },
          ],
        },
      ],
    },
  });
```

Things I tried/tested: 
- the `isActive` function works and shows the correct variation title in the block sidebar
- setting other/simpler example data
- setting the example data on block registration correctly shows the preview with this data (allthough for all variations)

**Comment by gziolo** [comment]
This is where the `example` is selected for a block variation:
https://github.com/WordPress/gutenberg/blob/f833f821105aa7129533fff802937d22f14c3099/packages/block-editor/src/store/selectors.js#L1470-L1473

Documentation for the `example` field is available here:

https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-registration.md#example-optional

**Comment by gaambo** [comment]
Thanks for the hint. I did a debugging session and it's true that the file referenced by @gziolo sets the variations example attribute. 
But the `PreviewPanel` component get's the in the inserter hovered/focused block by the block name and does not care for the variation. This is also true for trunk at this moment: `const hoveredItemBlockType = getBlockType( name );`
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/inserter/preview-panel.js#L19-L21

It should be rewritten to get the variations data. the `item` passed to the component has a `id` which identifies the variation ( eg `core/media-text/cta-banner` in my example) - so I guess that could be used. If someone can push me in the right direction which function to use to get the variation, I'd be happy to make a PR.

**Comment by gziolo** [comment]
This is where the `onHover` callback sets the `item`:

https://github.com/WordPress/gutenberg/blob/71fcf86d67d11a364e832c6053a996470c5bd7d4/packages/block-editor/src/components/inserter/menu.js#L95-L101

The `item` and `onHover` get wired together inside `InserterListItem` component:

https://github.com/WordPress/gutenberg/blob/71fcf86d67d11a364e832c6053a996470c5bd7d4/packages/block-editor/src/components/inserter-list-item/index.js#L39-L47

There are a few places where the list of `items` is generated before passing individual entries to `InserterListItem` like:

1. https://github.com/WordPress/gutenberg/blob/71fcf86d67d11a364e832c6053a996470c5bd7d4/packages/block-editor/src/components/inserter/block-types-tab.js#L39-L42
  and used in:
  https://github.com/WordPress/gutenberg/blob/71fcf86d67d11a364e832c6053a996470c5bd7d4/packages/block-editor/src/components/inserter/block-types-tab.js#L126-L131
2. https://github.com/WordPress/gutenberg/blob/71fcf86d67d11a364e832c6053a996470c5bd7d4/packages/block-editor/src/components/inserter/search-results.js#L63-L68
  and used in:
  https://github.com/WordPress/gutenberg/blob/71fcf86d67d11a364e832c6053a996470c5bd7d4/packages/block-editor/src/components/inserter/search-results.js#L141-L147

It might be not that simple to track down the place that doesn't apply properly the block variation to the item shown in the inserter. It looks like it is likely that the current behavior differs depending on the context of how the search result is displayed: from the most used blocks, from the given category, when using the searching feature.

**Comment by gaambo** [comment]
The issue dos not exist anymore on trunk at this point of time. I tried with my[ example from above](https://github.com/WordPress/gutenberg/issues/38279#issuecomment-1025867721) and the inital test data provided by OP and the inserter correctly displays the example data from the variation. Can be closed.

**Comment by gziolo** [comment]
Excellent, thank you for checking @gaambo 💯
