### ISSUE TITLE
Gallery block - Adding images creates unexpected Image blocks

### ISSUE THREAD

**Issue by geriux** [WordPress/gutenberg#38287]
## Description
Currently, there's a bug when adding images to a Gallery, where it would create the gallery itself and Image blocks from those images below the Gallery block. This is an issue happening on **Android only** so it looks like it's a native side bug with media selection.

This issue is happening on the WordPress Android version `19.0` and it affects that version and the on-going release for `19.1`.

## Step-by-step reproduction instructions
- Open the WordPress Android app
- Start a new post
- Add a Gallery block
- Add some images (from the device)

## Expected behaviour
The Gallery block should show correctly with the previously selected images.

## Actual behaviour
The Gallery block shows up with the images but after it some Image blocks are created as well.

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/4885740/151385043-847d4a0e-dd7c-4f2f-acae-5386ee419e97.mov

## WordPress information
- WordPress version: Latest
- Gutenberg version: Latest version in trunk, `1.70.0` and `1.69.0`
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No, using `Calvin`

## Device information
- Device: Redmi Note 8T and Android Simulator
- Operating system: Android 11
- WordPress app version: `19.0`, `19.1`

**Comment by hypest** [comment]
Took a look to investigate and so far, I've noticed that the [processMediaUri(<list of media URIs>)](https://github.com/wordpress-mobile/WordPress-Android/blob/1acf27661a6162b55973be8284d97217c664cc78/WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCase.kt#L80) is called within a loop, producing the results we see. I have the sense that there's a bug right there.

Pinging you @ravishanker and @mkevins as you might have insights, thanks!

**Comment by mkevins** [comment]
> I have the sense that there's a bug right there.

I believe you are correct @hypest . Great job investigating that and implementing a solution!

**Comment by hypest** [comment]
Closed via https://github.com/wordpress-mobile/WordPress-Android/pull/15879
