### ISSUE TITLE
Bad coding paradigms in Gutenberg

### ISSUE THREAD

**Issue by ordigital** [WordPress/gutenberg#38293]
### Description

- Styles should be kept in stylesheet and not in page content. Attribute `style` should not be added to any tag! Any hardcoded values for colors, fonts etc. are unacceptable because they destroy website style consistency i.e. when using alternative hi-contrast css that inverts text/background colors for accessibility or when there's a button for changing global font size.
- There is no easy way to customize toolbar and navigator to get rid of all of this bad formatting options and to replace them with classes that would do the same but in a proper way.
- It is not possible to add custom button with more than one class.

This all makes Gutenberg a step backward in terms of coding standards. This problems could be easily avoided in TinyMCE by js but in Gutenberg it is just impossible to make editor produce proper HTML code. 

Why Gutenberg devs focus only visual aspects and not on accessibility, customizability and separation of code and styles?

### Step-by-step reproduction instructions

1. Turn on Gutenberg
2. Watch how you website content mixes with hardcoded styles

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mkkeck** [comment]
See here too: https://github.com/WordPress/gutenberg/issues/34613#issue-989661644

**Comment by mtias** [comment]
@ordigital check [this post](https://make.wordpress.org/core/2022/02/09/core-editor-improvement-curated-experiences-with-locking-apis-theme-json) that includes various examples of how you can control and disable style controls globally or on a per block basis.

You can also add custom classes in the advanced panel, if that's what you refer to.
