### ISSUE TITLE
"image_default_link_type" option doesn't work as of WP 5.9

### ISSUE THREAD

**Issue by cxlxin** [WordPress/gutenberg#38302]
As of WP 5.9 the `image_default_link_type` option doesn't work for the new galleries. Images do still work.

_Originally posted by @cxlxin in https://github.com/WordPress/gutenberg/issues/25582#issuecomment-1023612983_

**Comment by ajlende** [comment]
I know @glendaviesnz was doing a lot of the new gallery work. Maybe he has some insight.

**Comment by glendaviesnz** [comment]
Thanks for reporting. I have a potential fix for this here https://github.com/WordPress/gutenberg/pull/38310

**Comment by MarcGuay** [comment]
I am experiencing this problem with 6.3.1.
