### ISSUE TITLE
Error 405 saving widgets

### ISSUE THREAD

**Issue by friscoMad** [WordPress/gutenberg#38307]
### Description

After migrating 2 different installations to 5.9 I am seeing an error when I try to save any widget modification.
It seems that the save triggers a call to `https://XXXt/wp-json/batch/v1?_locale=user` but with the method OPTIONS that ends with an 405 error blocking any widget modification.

I have confirmed the issue with multiple themes and in at least 2 different installations and using Chrome and Firefox.

### Step-by-step reproduction instructions

1. Go toAppearance -> Widgets
2. Modify / Add a widget
3. Click Update
4. Get a "There was an error. The response is not a valid JSON response"

### Screenshots, screen recording, code snippet

![cap](https://user-images.githubusercontent.com/487098/151460027-0f783ea2-ae14-4fe6-9c6f-1ddde9eccb9f.gif)

### Environment info

`
### wp-core ###

version: 5.9
site_language: es_ES
user_language: es_ES
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: true
user_registration: false
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 6
site_count: 2
network_count: 1
dotorg_communication: true

### wp-dropins (1) ###

sunrise.php: true

### wp-active-theme ###

name: Twenty Twenty-One (twentytwentyone)
version: 1.5
author: el equipo WordPress
author_website: https://es.wordpress.org/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, title-tag, post-formats, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, custom-background, editor-color-palette, editor-gradient-presets, responsive-embeds, custom-line-height, experimental-link-color, custom-spacing, custom-units, widgets
theme_path: /home/neoseo/domains/neoseo.es/public_html/wp-content/themes/twentytwentyone
auto_update: Desactivado

### wp-themes-inactive (10) ###

Gleam: version: 2.8.3, author: Elegant Themes, Actualizaciones automáticas desactivadas
japan-style: version: 1.2, author: Good Design Web, Actualizaciones automáticas desactivadas
LifeCare: version: 1.1, author: AivahThemes, Actualizaciones automáticas desactivadas
Superhero: version: 1.4, author: Automattic, Actualizaciones automáticas desactivadas
Twenty Fifteen: version: 3.1, author: el equipo de WordPress, Actualizaciones automáticas desactivadas
Twenty Nineteen: version: 2.2, author: el equipo de WordPress, Actualizaciones automáticas desactivadas
Twenty Seventeen: version: 2.9, author: El equipo WordPress, Actualizaciones automáticas desactivadas
Twenty Sixteen: version: 2.6, author: el equipo WordPress, Actualizaciones automáticas desactivadas
Twenty Twenty: version: 1.9, author: El equipo de WordPress, Actualizaciones automáticas desactivadas
Twenty Twenty-Two: version: 1.0, author: El equipo de WordPress, Actualizaciones automáticas desactivadas

### wp-plugins-inactive (11) ###

Aivah Business Hours: version: 2.0, author: AivahThemes, Actualizaciones automáticas desactivadas
Breadcrumb NavXT: version: 7.0.2, author: John Havlik, Actualizaciones automáticas desactivadas
Classic Widgets: version: 0.3, author: WordPress Contributors, Actualizaciones automáticas desactivadas
Disable Gutenberg: version: 2.6, author: Jeff Starr, Actualizaciones automáticas desactivadas
Google Maps Ready!: version: 1.1.1, author: Google Maps plugin, Actualizaciones automáticas desactivadas
ImageInject: version: 1.17, author: Thomas Hoefter, Actualizaciones automáticas desactivadas
Jetpack: version: 10.5.1, author: Automattic, Actualizaciones automáticas desactivadas
Revolution Slider: version: 4.5.7, author: ThemePunch, Actualizaciones automáticas desactivadas
Video Thumbnails: version: 2.12.3, author: Sutherland Boswell, Actualizaciones automáticas desactivadas
WordPress Importer: version: 0.7, author: wordpressdotorg, Actualizaciones automáticas desactivadas
WordPress MU Domain Mapping: version: 0.5.5.1, author: Donncha O Caoimh, Actualizaciones automáticas desactivadas

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1808
imagemagick_version: ImageMagick 7.1.0-0 Q16 x86_64 2021-06-02 https://imagemagick.org
imagick_version: 3.5.1
file_uploads: File uploads is turned off
post_max_size: 64M
upload_max_filesize: 64M
max_effective_size: 64 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 9 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 49151
	imagick::RESOURCETYPE_MAP: 9 GB
	imagick::RESOURCETYPE_MEMORY: 5 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, A, AAI, AI, APNG, ART, ARW, ASHLAR, AVI, AVS, B, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, C, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FARBFELD, FAX, FF, FILE, FITS, FL32, FLV, FRACTAL, FTP, FTS, G, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K, K25, KDC, LABEL, M, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, O, ORA, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PHM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, R, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCREENSHOT, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, Y, YAML, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0 x86_64
httpd_software: Apache/2
php_version: 7.3.33 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 64M
php_post_max_size: 64M
curl_version: 7.29.0 NSS/3.53.1
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.35
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
max_allowed_packet: 268435456
max_connections: 150

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/neoseo/domains/neoseo.es/public_html/wp-content
WP_PLUGIN_DIR: /home/neoseo/domains/neoseo.es/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 64M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Sin definir
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Hey @friscoMad ! In my experience, a 405 error usually can indicate something on your server is blocking an action from happening. By chance, have you chatted with your host about this issue?

**Comment by friscoMad** [comment]
Closing, as @annezazu suggested this was a configuration error in my apache, sorry for bothering you. 😢

**Comment by annezazu** [comment]
No need to apologize 🤗 I've had this happen too and it can be tough to know what the root cause is. I'm very glad to know you were able to resolve it!

**Comment by rom0x** [comment]
Same problem. Keep getting "There was an error. The response is not a valid JSON response" when trying to save something under Design->Widgets. Running WordPress 6.1.1. Twenty-Two, no Plugins activated. Using Classic Editor and Classic Widgets, no problem.

**Comment by whyameye** [comment]
@rom0x do you have this in your nginx file?
`   location ~ ^/wp-json/ {
         rewrite ^/wp-json/(.*?)$ /?rest_route=/$1 last;
   }`
if so, try commenting it out

**Comment by rom0x** [comment]
> @rom0x do you have this in your nginx file? ` location ~ ^/wp-json/ { rewrite ^/wp-json/(.*?)$ /?rest_route=/$1 last; }` if so, try commenting it out

Hey. Thanks. Well, i have something similar in there

`    ## fixes potential 403 denied issues with WP-JSON ##
    location ~ ^/wp-json/ {
        ## if permalinks not enabled or not loaded properly in the browser ##
        rewrite ^/wp-json/(.*?)$ /?rest_route=/$1 last;
    }`

**Comment by whyameye** [comment]
I think I spoke too soon. I had the same problem as described here. When I commented out the lines I referenced it fixed this specific problem but later on I found not having those lines caused other issues so I had to add them back. I feel like at least in my case this is an nginx configuration problem but it's not obvious to me how to fix it.

**Comment by rom0x** [comment]
Thanks for letting me know. Yes it's strange. At least classic widgets are working correctly.

**Comment by heyfets** [comment]
I solved this problem by adding the index.php to rewrite:
```
location ~ ^/wp-json/ {
            rewrite ^/wp-json/(.*?)$ /index.php?rest_route=/$1 last;
        }
```
