### ISSUE TITLE
Must be able to remove / disable HTML anchors from selected / specific header blocks

### ISSUE THREAD

**Issue by RolfKyburz** [WordPress/gutenberg#38306]
### Description

As a heritage from a recent Gutenberg update, WP 5.9 now automatically adds anchors for all header blocks. Previously, header tags were not added reliably, so the fix is welcome. However, for TOC blocks which collect all blocks with an anchor, this has nasty side-effects: one can alter the anchor, but it seems impossible to eliminate an anchor from a header block (the empty anchor field instantly gets filled with the default anchor). This is really bad, for two reasons: for one, I don't want the main post title (and its subtitles in the header section, above the TOC) to be included in the list of content. Also, in long texts with as heavily stacked header hierarchy, I often want to eliminate some of the lowest level headers from the list of content, in order to keep it compact and readable. Working around this issue is non-trivial for non-specialists. Plus, opening existing posts may inadvertently add unwanted lines to the list of content, without the user noticing.

### Step-by-step reproduction instructions

in the "Advanced" sidebar widget, try removing the anchor from any header block

### Environment info

WP 5.9 / Gutenberg 12.4.1, Exhibit theme 1.04 / GeneratePress 3.1.1 parent theme, PHP 7.4.26

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/38171. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
