### ISSUE TITLE
Paragraph block issue when site is set to Polish language

### ISSUE THREAD

**Issue by piotrbak** [WordPress/gutenberg#38329]
### Description

When Polish language is being used, the paragraph block lacks the Font Size section.

### Step-by-step reproduction instructions

1. Set site language to Polish
2. Add new page
3. Add new paragraph
4. See the menu on the right, there is no way to change the font size
5. Change the language to English and repeat the 2,3,4 steps

### Screenshots, screen recording, code snippet

![image (20)](https://user-images.githubusercontent.com/26767037/151559065-bd159246-7f83-4815-88ad-07a9d6e6a53b.png)
![image (21)](https://user-images.githubusercontent.com/26767037/151559074-61c797d9-1b09-4d31-9514-1f027b70893e.png)

### Environment info

- WordPress 5.9
- Polish language

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tom-apps** [comment]
Same here.

**Comment by gziolo** [comment]
I can confirm the issue in WordPress 5.9. It works as expected when the latest version of the Gutenberg plugin is enabled. @Mamaduka, it looks like the fix could be backported to WordPress 5.9.2.

**Comment by Mamaduka** [comment]
@gziolo, I need to track down the PR that fixed this first. Do you know if this is an i18n specific issue?

**Comment by gziolo** [comment]
It looks like it's an integration issue in WordPress core because I can see the control (not translated) when the Gutenberg plugin from the `wp/5.9` branch is activated.

<img width="1034" alt="Screenshot 2022-02-25 at 09 10 43" src="https://user-images.githubusercontent.com/699132/155679376-6ebb14a4-77a6-4be6-a49b-e88d3767a6a6.png">

**Comment by Gierand** [comment]
@Mamaduka @gziolo Thanks for doing that. What's the next step? Do you have the capacity to work on PR, and maybe we can ship it with 6.0?

**Comment by gziolo** [comment]
It's still an issue in WordPress 6.0 RC 1!

**Comment by tomasztunik** [comment]
Confirmed it in the latest trunk as well, I'll try to have a look at it if nobody is already.

**Comment by tomasztunik** [comment]
Narrowed it down to a conflict with `__experimentalTextTransform` - when this supports feature is removed it starts working as expected. Sharing in case somebody is aware of any issues around that - will continue investigating. It doesn't work also if `__experimentalTextTransform` is the only additional supports feature besides `fontSize`.

Tested and works ok in Spanish so something very peculiar is going on here. 



| with `__experimentalTextTransform` | without |
|---|---|
|  ![Screenshot 2022-05-05 at 17 24 49](https://user-images.githubusercontent.com/112270/166957839-09510817-e0fa-4ab6-9647-c44b67cad1ec.jpg) |  ![Screenshot 2022-05-05 at 17 24 31](https://user-images.githubusercontent.com/112270/166957881-196d5e03-5fc3-43d9-a16c-229958832505.jpg) |

It seems like if certain languages are selected and `__experimentalTextTransform` is enabled the font size (Wielkość liter) doesn't get registered at all - it's missing in the sidebar and in the dropdown.
 
All translations seem to be present.

Looks like there is an issue in `ToolsPanelContext` and `useToolsPanel` that feed it with data where sometimes `menuItems` are not generated correctly

**Comment by tomasztunik** [comment]
@gziolo it seems the problem is coming from a translation clash. In Polish, we have translated `Font size` and `Letter case` as `Wielkość liter` (actually as - `Wielko\u015b\u0107 liter`) because of that and that it compares against a label in many places rather than a field key/name it causes a clash where the latter to register gets ignored as Gutenberg thinks it's already registered.

Do we want to add some preventive measures for this? 

This is where the problematic code lives - I can't see any more unique identifier, makes me wish we had one.

https://github.com/WordPress/gutenberg/blob/50ecf57504a4c181523361a54425e3cb5b822d9d/packages/components/src/tools-panel/tools-panel/hook.ts#L85-L102

 

We should still update the `Letter case` or `Font size` translations to avoid confusion of having two different meanings under the same translation. I believe `Font size` would better translate as `Wielkość czcionki`.

![Screenshot 2022-05-05 at 18 14 57](https://user-images.githubusercontent.com/112270/166967606-bac1716b-5df0-46e1-a5f1-d5f7be6ea1ec.jpg)

Also noticed that these translations seem to have unicode chars but there are others that have plain utf-8 chars for Polish letters.

**Comment by gziolo** [comment]
>  I believe Font size would better translate as Wielkość czcionki.

"Rozmiar czcionki" is another option 👍🏻 

It's a very interesting bug. I would say updating the translation will completely resolve it. There is this question whether having two different controls with the same name wouldn't be still confusing 😄

Anyway, I agree that in principle we should rather use machine generated unique ids to avoid this accidental issues.

**Comment by tomasztunik** [comment]
"Rozmiar czcionki" sounds better 👍

Can you update that? don't have a translator's account.

Should we create an issue with using labels as keys? Or maybe I can bring it
up on the next meeting open floor.

I'd update the title of the issue to make it easier to find and not unique
to polish if something similar happens for other languages.

And agreed, it was a tricky one! Took a while to realise what was right there in your face visible on the screenshots I've posted above with/without `__experimentalTextTransform` :)

**Comment by gziolo** [comment]
> Can you update that? don't have a translator's account.

I guess you only need an account on WordPress.org. You can change translations at https://translate.wordpress.org/locale/pl/default/wp/dev/. I will try it now.

**Comment by gziolo** [comment]
Done, it was easy to propose changes for both 6.0 and 5.9 :)
<img width="1222" alt="Screenshot 2022-05-06 at 09 46 32" src="https://user-images.githubusercontent.com/699132/167089551-4164df5c-bb00-45dc-964b-7293ff5dbdae.png">

**Comment by tomasztunik** [comment]
Nice, clicked around the translations interface after you mentioned it and saw your change - will keep this in mind for the future 👍

**Comment by Mamaduka** [comment]
It might be a good idea to provide translation context to avoid similar issues in another language.

**Comment by tomasztunik** [comment]
Adding context is not going to invalidate translations right? Should we provide it on both ends for `Font size` and for `Letter case` and if we were to add it should we add it on every occurrence?

Proposing:
> Ensure translation is distinct from <the_clashing_string>

Though I'm thinking if this is not too defensive, I feel even if a translation clash like this occurs we should have ways to avoid issues like this one. Had a quick search for `label ==` and it seems like the `tools-panel` hook is the only place where we use labels for comparison or cache keys.

**Comment by Mamaduka** [comment]
> Adding context is not going to invalidate translations right?

It won't, but usually a good way to avoid similar problems.

**Comment by tomasztunik** [comment]
Opened the PR with the translators' comments. I've added it only in the `TypographyPanel` file - let me know if you think this is enough or if we should put it all over.

**Comment by iworks** [comment]
This is completely odd to have to use latin1 letters without polish (or other languages) characters to avoid (wrong maybe?) string comparison.

I will change "Wielkość liter" into "Rozmiar liter" but I hope it will be only temporary.

As I understand it can cause more problems - anywhere we use polish diacritics? (js encoded strings)?

**Comment by tomasztunik** [comment]
@gziolo already updated the strings - the issue is not diacritics. The problem was two unique strings with different meanings were translated to Polish with the same translation and as this string/label was used as a uniqueness indicator it caused issues with UI not rendering as expected - it was more of a translation error.

~We will only need to approve the translation and release the new version of the dictionary.~ Seems like it was already approved.

**Comment by iworks** [comment]
> @gziolo already updated the strings - the issue is not diacritics. The problem was two unique strings with different meanings were translated to Polish with the same translation and as this string/label was used as a uniqueness indicator it caused issues with UI not rendering as expected - it was more of a translation error.
> 
> ~We will only need to approve the translation and release the new version of the dictionary.~ Seems like it was already approved.

ou... thank you for the explanation - then I can now return to proper translation, but I need to be careful to make it different for different base strings.

**Comment by Gierand** [comment]
@iworks, at this point for [version 6.0](https://translate.wordpress.org/projects/wp/dev/pl/default/?filters%5Bterm%5D=Wielko%C5%9B%C4%87+liter&filters%5Bcase_sensitive%5D=yes&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) the translation is still not correct and the problem has returned.

![image](https://user-images.githubusercontent.com/1615208/167992502-76bd44e4-7edb-4397-bc6a-9b956febe781.png)

**Comment by Gierand** [comment]
@iworks, in version 6.3 the problem is back.

![Screenshot 2023-07-23 at 14-01-04 Translations Polish 6 3 x – Development GlotPress WordPress org](https://github.com/WordPress/gutenberg/assets/1615208/22c627ff-de04-4f60-989d-7b1016edaa7f)

**Comment by iworks** [comment]
@Gierand you mean it is still an issue in Gutenberg...

**Comment by iworks** [comment]
Changed.

**Comment by Gierand** [comment]
> @Gierand you mean it is still an issue in Gutenberg...

Yes, apparently.
