### ISSUE TITLE
Pasting hex value into color picker defaults to black

### ISSUE THREAD

**Issue by KevinBatdorf** [WordPress/gutenberg#38334]
### Description

When pasting a hex value containing the `#`, the character isn't removed and a black color is computed.

### Step-by-step reproduction instructions

1. Add a block
2. Choose a color
3. Edit the hex value
4. Paste in a value with `#` at the start

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1478421/151591457-f6117446-0dd5-437b-82a1-7e2ce30ad5a7.mov

### Environment info

- WP 5.9
- Gutenberg 12.5.0-rc.1 
- TT1 Blocks theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aurooba** [comment]
Oh I was just coming to report this and see about a fix! Thank you @KevinBatdorf! This fix is going to be fantastic.
