### ISSUE TITLE
iOS Safari autocorrect suggests entire sentence not individual words

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#38330]
### Description

If you type into Gutenberg from iOS Safari your individual words aren't suggested for autocompletion. Instead, the entire piece of text gets added to the autocomplete suggestion. This gets longer and longer until Safari stops suggesting. It is reset when you hit enter.

Individual words are suggested in a plain `textarea`.

### Step-by-step reproduction instructions

Type into a paragraph using iOS Safari and note that the entire sentence is suggested, not the words

### Screenshots, screen recording, code snippet

Start typing and get a suggestion for the word:
![IMG_2158](https://user-images.githubusercontent.com/1277682/151560369-3109d68e-8962-4b7b-94b3-926b1fcec803.jpeg)

Continue typing and it suggests all the words:
![IMG_2159](https://user-images.githubusercontent.com/1277682/151560376-892b42e0-0dd6-4805-967b-ebd2ee15c5a0.jpeg)

Continue typing and get the entire sentence:
![IMG_2160](https://user-images.githubusercontent.com/1277682/151560379-99321017-9f63-4302-ae47-26d4cd3356dc.jpeg)

Start a new paragraph and it resets:
![IMG_2161](https://user-images.githubusercontent.com/1277682/151560381-91c41b04-903c-4a6a-9311-c195f3b0543e.jpeg)

### Environment info

- WordPress 5.9
- Gutenberg 12.5.0
- Safari iOS 15.3
- iPhone 13 Pro

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

(sorry for the massive screenshots)

**Comment by jeremyalzona** [comment]
This issue also persists on Safari for macOS — sentences are being kept in Safari’s autocorrect. I presume that if you have a MacBook with a Touch Bar (with predictive text turned on) that you are able to see this happening on par with iOS’s predictive text.

**Comment by youknowriad** [comment]
unfortunately I don't have iOS to test this but on Mac OS (Safari 15.4), I'm not able to reproduce.

**Comment by johnHackworth** [comment]
just noting this is also happening on the Tumblr's gutenberg instance:

![image](https://user-images.githubusercontent.com/1554855/173071463-78e221cf-63e2-4059-9f33-57a4e61ffd01.png)

**Comment by ellatrix** [comment]
I tried this in the latest WP and iOS and I can't reproduce. Maybe iOS Safari has fixed this? Are you still experiencing this issue?

**Comment by johngodley** [comment]
Yeah, this looks fixed to me. Unless anyone else is experiencing it then I think we can close the issue.

**Comment by astralbodies** [comment]
@ellatrix @johngodley I haven’t seen this happen in a while on wpcom or other sites lately. If I see it again, I’ll reopen the issue! 🥳

**Comment by ellatrix** [comment]
Awesome!
