### ISSUE TITLE
Metabox assets causing CSS problems

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#3833]
## Issue Overview
When plugins who render metaboxes also load styles that depend on WordPress styles, these dependencies will be loaded again and override other styles.

Yoast SEO adds custom styling to the admin-bar to be able to show the bullet for the content score.

## Steps to Reproduce (for bugs)

1. Activate a custom admin style.
2. Activate Yoast SEO
3. Visit a page/post with Gutenberg
4. Notice the admin bar changing color after the metabox AJAX has finished loading

## Expected Behavior

I expect the styles that are already loaded in the original page request to not be loaded again.

## Current Behavior
1. The `admin-bar.css` is loaded in the <head>
1. The `colors.css` is loaded after the `admin-bar.css`
1. The `admin-bar.css` is loaded again in the metabox request, overriding the `colors.css` styling

## Related Issues and/or PRs

Issue on the Yoast SEO repository: https://github.com/Yoast/wordpress-seo/issues/8407

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
I believe this is not an issue anymore since the meta boxes and their styles are prefetched right now. Can you confirm?

**Comment by moorscode** [comment]
This is no longer present in `1.9.1`!
