### ISSUE TITLE
npm install @wordpress/scripts --save-dev fails

### ISSUE THREAD

**Issue by helgatheviking** [WordPress/gutenberg#38346]
### Description

Running `npm install @wordpress/scripts --save-dev` in my plugin folder's directory is failing.

### Step-by-step reproduction instructions

Go to command line and run `npm install @wordpress/scripts --save-dev` 

### Screenshots, screen recording, code snippet

```
code EACCES
npm ERR! syscall rename
npm ERR! path /mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/nav-menu-roles/node_modules/eslint-module-utils
npm ERR! dest /mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/nav-menu-roles/node_modules/.eslint-module-utils.DELETE
npm ERR!     syscall: 'rename',
npm ERR!     path: '/mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/nav-menu-roles/node_modules/eslint-module-utils',npm ERR!     dest: '/mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/nav-menu-roles/node_modules/.eslint-module-utils.DELETE'
npm ERR!   },npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',npm ERR!   syscall: 'rename',
npm ERR!   path: '/mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/nav-menu-roles/node_modules/eslint-module-utils',
npm ERR!   dest: '/mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/nav-menu-roles/node_modules/.eslint-module-utils.DELETE',
npm ERR!   parent: 'nav-menu-roles'
npm ERR! }
```

### Environment info

Windows 11. Running Ubuntu-20.04 on WSL 2.. though the files are stored in Windows and mounted in Ubuntu. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
As you see `code EACCES`, I think it is not a problem with the package but the lack of write/access permissions to the directory.

Can you successfully install another npm package instead of `@wordpress/scripts` ?

Also, since your development environment seems to be built on a Windows host OS, so please try running the command directly on the host OS instead of from within WSL.

If you want to develop on WSL, the appropriate directory is `/home/{your_username}/`, not `/mnt/`.

**Comment by helgatheviking** [comment]
Yes I can successfully install many other packages in NPM even in the `/mnt/` directory. That's the windows folder mounted into the ubuntu system. It does run a little slow there so I am working on transitioning to hosting files in WSL itself. 

So far in my experience I haven't found these packages work well from the Windows OS. All packages appear to be written expecting users to have Mac or Linux OS, so WSL is one of the one paths forward for Windows-users. 

But in this case, removing the `node_modules` and reinstalling appears to have resolved the issue.
