### ISSUE TITLE
Home page won't use home template

### ISSUE THREAD

**Issue by gingerling** [WordPress/gutenberg#38345]
### Description

I have a static page listed under **settings** > **reading** as my homepage

![Screenshot from 2022-01-29 11-59-00](https://user-images.githubusercontent.com/2853040/151667944-d537ae22-c148-4edf-96e3-32c030a677bd.png)

However that page is using the "page" template not the **home** template

When I click **edit site** from the home page it shows this:

![Screenshot from 2022-01-29 16-04-53](https://user-images.githubusercontent.com/2853040/151667997-b29c3327-3cbd-4f3d-ad52-5776327a63b7.png)

(and indeed the template content is the same as what's showing, also)

I have the default template called **home page**, which I have edited and is ready to be used. I expected this to show for my home page, and it says it should display in my circumstances

![Screenshot from 2022-01-29 16-06-28](https://user-images.githubusercontent.com/2853040/151668071-ef82e4e5-2c57-4685-94d3-292e70773592.png)

In the page editor this homepage showing as set as **front page** 

![Screenshot from 2022-01-29 16-07-50](https://user-images.githubusercontent.com/2853040/151668122-3682e186-285d-418b-b85e-a1296cde42a5.png)

The template in page settings is listed as **default** 

![Screenshot from 2022-01-29 16-09-04](https://user-images.githubusercontent.com/2853040/151668186-d67b48fd-aaa3-410a-90bc-ed9ff7b17603.png)

There is no option to choose **Home** template:

![Screenshot from 2022-01-29 16-09-22](https://user-images.githubusercontent.com/2853040/151668197-5e3ffbff-0b97-4478-9322-f4dfaa7aff38.png)

I am aware I can choose the **front page** template, however, I don't want to as this is a blank template I must build the design from scratch. I have checked and find if I add the front page template, it does indeed replace content on the home page with a blank template. 

I don't see any way to use the **home** template for the home page, right now.

### Step-by-step reproduction instructions

as above

### Environment info

WordPress 5.9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by carolinan** [comment]
> I have the default template called front page,

The front page template takes precedence over the home template, even if you change the reading settings. This is true also for classic themes.  So if it exists you would need to delete it.

https://developer.wordpress.org/themes/basics/template-hierarchy/#front-page-display

**Comment by gingerling** [comment]
I realized just now the front page template is showing on my blog page.

I'm not sure what "if it exists" means but I don't have this template in my list

![Screenshot from 2022-01-30 12-23-27](https://user-images.githubusercontent.com/2853040/151699504-faf100f3-9513-47db-a60d-0a8a62d92fec.png)

and it's still showing in the add new button dropdown

![Screenshot from 2022-01-30 12-23-49](https://user-images.githubusercontent.com/2853040/151699509-a51f09af-f195-4acd-af5c-45bf5a8ab46e.png)

Is there another way to verify this?

Additionally, the home page is not actually USING the front page template (that I don't think exists) - it's using **page**, so I don't think that this is what is happening

**Comment by carolinan** [comment]
If it does not exist in the list, then that is not the page that is showing on the front.

**Comment by gingerling** [comment]
Sorry, please forgive me, I am dyslexic and am getting my "home page" and
"front page" template names confused in places I think.

In simple form:

Home page is set to show static page

Home page template should therefore be used

"Front page" template is not present to does not override this job

The site home page is using the "page" template (not home page template or
front page template)

**Comment by carolinan** [comment]
The static page uses the template that you set in the block editor, in the template section.
The page does not change template when it is set as the static home page.

**Comment by carolinan** [comment]
Related: https://github.com/WordPress/gutenberg/issues/38389

**Comment by gingerling** [comment]
This text then, is confusing for me:

"Displays as the site's homepage, or as the posts page when a static home page isn't set." [home page template description][

Additionally, I am unable to chose the home page template from the dropdown in the page settings, as shown here:

![image](https://user-images.githubusercontent.com/2853040/151955922-03797cbd-3157-4f3b-adb5-3b8c7d8fd6a2.png)

I'm still super confused about what the intended functionality is here!

**Comment by gingerling** [comment]
"Displays as the site's homepage, or as the posts page when a static home page isn't set."

I read this as:

"Displays as the site's homepage": this template displays for the homepage of the site (I assume post content will display anything from the page editor for that page)

"or as the posts page when a static home page isn't set": When the static home page IS set, this is the home page template. When the site displays the posts feed on the home page (and not a static page), this template used  there also..
 
 i.e **Whatever** it is that's on the home page of your website, be it blog feed or static content, then **this** is the template to edit.

but it seems like what is happening is this template only ever covers the posts page, if I made posts the front page it would display there, if posts are at /news then it shows there.

**Comment by carolinan** [comment]
Ah, the description was changed for the next version of Gutenberg. The new text is "Displays posts on the homepage, or on the Posts page if a static homepage is set"
https://github.com/WordPress/gutenberg/pull/38132

**Comment by gingerling** [comment]
OOOOOOH! well that makes a big difference! Okay, so

Intended functionality is:

Set static home page
That page will use the "page" template UNLESS
Front Page template is set up 
Then the entire page must be edited in the front page template, not with normal editor and template combo?

**Comment by carolinan** [comment]
I believe so, yes.

**Comment by gingerling** [comment]
okay. Has anyone asked if front page could actually have stuff in it rather than be blank? (can't see anything, but tbh I never do when I check!) The actual root cause behind all this is that I don't want to build from scratch, it's too much work. But I do need a little more control over the front page of the site.

**Comment by carolinan** [comment]
Yes, There are explorations around adding some default content depending on the template

**Comment by annezazu** [comment]
>The actual root cause behind all this is that I don't want to build from scratch, it's too much work. But I do need a little more control over the front page of the site.

There's also work being explored around integrating patterns into the experience when you create a new template to make it easier to quickly get started: https://github.com/WordPress/gutenberg/issues/36697

I'm going to close this out since this isn't an issue per say but general feedback that has been clarified thanks to the lovely @carolinan  Happy to re-open if folks would prefer or if there is some action I'm missing that needs to be taken.
