### ISSUE TITLE
Site Editor > Styles > Welcome Guide in the title.

### ISSUE THREAD

**Issue by heyadamsilver** [WordPress/gutenberg#38353]
### Description

Re-watching the Welcome Guide only shows the "Get Started" option/button vs the arrows for the guide.

### Step-by-step reproduction instructions

First time loading the site to EDIT with 5.9 the Welcome Guide is engaged.  Closing it and then trying to get it back by clicking the more tools and options button on the front end of a site, to re-watch the Welcome Guide - the arrows, tour is no longer avail, only Get Started. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/20097175/151707236-f3912d7a-2ae2-4d5b-80f1-456bb4824678.mov

### Environment info

Base install
WP 5.9 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by courtneyr-dev** [comment]
I can confirm the same results with Gutenberg 12.4 in Site Editor.

**Comment by talldan** [comment]
@heyadamsilver I think reason is that there are two different welcome guides, one for the whole editor (which just has one 'page') and a second for the styles panel (with multiple pages). The link in the main settings shows the guide for the whole editor.

The styles guide can be displayed again from this little menu:
![Screen Shot 2022-01-31 at 12 14 26 pm](https://user-images.githubusercontent.com/677833/151738127-50db09bb-be49-4c2b-ad72-b92c05688c3f.png)

Previous discussion on this was here - https://github.com/WordPress/gutenberg/issues/36544. I think this could do with some further design feedback or a decision by a designer on whether to iterate on this, so I've added the 'Needs Design Feedback' label.

**Comment by heyadamsilver** [comment]
@talldan 
Boom.. you are correct sir!  
Thanks! 
Closing the ticket!
