### ISSUE TITLE
Cannot remove block type from Gutenberg because it does not exists

### ISSUE THREAD

**Issue by mrfatguy** [WordPress/gutenberg#38355]
### Description

I can add Imgur block type to my post:

![image](https://user-images.githubusercontent.com/2903392/151719181-00dcfb16-caf9-4116-900b-e2285a0fd41e.png)

But, I can't remove it (stop it from appearing at the top of list), because Gutenberg claims that such block does not exist:

![image](https://user-images.githubusercontent.com/2903392/151719295-e42e3ddf-74fb-4ac7-ae0a-213b0393509e.png)

I don't have any plugin introducing any new blocks except the default ones (i.e. introduced by Gutenberg dev plugin itself). The Imgur block type has started to appear in my blocks list about a week ago while my plugins stack didn't change for past 2-3 years. This is 100% not any 3rd party plugin-related issue.

What should I do in this case? How should I get rid of Imgur block type?

### Step-by-step reproduction instructions

1. Start editing new post
2. Go to Gutenberg preferences, to _Blocks_ tab
3. Verify that there is no Imgur block listed there
4. Go back to Gutenberg editor, start a new block
5. Type `/img` to see image-related blocks.
6. See Imgur block available in the list.

### Screenshots, screen recording, code snippet

![Imgur](https://user-images.githubusercontent.com/2903392/151719546-f48abaf5-42d8-4cbf-a55a-0ac99e4c2df1.gif)

### Environment info

- Wordpress 5.9, Gutenberg 12.4.1, WR-Elite theme
- Microsoft Edge 97.0.1072.76 (Official build) (64-bit)
- Windows 10.0.19042 Build 19042

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by skorasaurus** [comment]
The `imgur` block is actually a block variation of the [embed block](https://wordpress.com/support/wordpress-editor/blocks/embed-block/). The embed block (and all of their variations) is enabled by default in Gutenberg.  

There's a [couple different approaches] (https://wordpress.stackexchange.com/questions/379612/how-to-remove-the-core-embed-blocks-in-wordpress-5-6) you can use to remove the imgur block variation from the core `embed`; more are also listed in [this issue](https://github.com/WordPress/gutenberg/issues/27913). 

You make a great point that block variations are not listed in block inserter's preferences and perhaps they should be.

**Comment by talldan** [comment]
There's a related issue here about the block manager not showing variations - https://github.com/WordPress/gutenberg/issues/27708

**Comment by skorasaurus** [comment]
thanks for finding that @talldan ; I'll close this issue since @trejder is requesting can be fulfilled through https://github.com/WordPress/gutenberg/issues/27708
