### ISSUE TITLE
WP 5.9 `wp.data.dispatch('core/editor').setupEditor();` back-compatibility break.

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#38361]
### Description

This was discovered by @mohitwp in https://github.com/10up/insecure-content-warning/issues/63 and worked around in the associated pull request in https://github.com/10up/insecure-content-warning/pull/64.

Prior to WordPress 5.9 the plugin was updating a blog post's content with the code:

```js
const content = wp.data.select('core/editor').getEditedPostAttribute('content');
const post = wp.data.select('core/editor').getCurrentPost();
const newContent = /* content update routine */
post.content = { raw: newContent };

wp.data.dispatch('core/editor').setupEditor(post);
```

Following the update to WP 5.9 the final line of code no longer works, ie the post's content is no longer replaced. No errors or warnings are logged in the console. 

I'm unable to find any indication of a hard deprecation in the documentation.

_I've reproduced this in the console with plugins disabled._

### Step-by-step reproduction instructions

To reproduce without plugins enabled.

1. Install the latest version WordPress 5.8
2. Create a post in the block editor
3. Run the following code in the console
   ```js
   (() => { 
     const content = wp.data.select('core/editor').getEditedPostAttribute('content');
     const post = wp.data.select('core/editor').getCurrentPost();
     const newContent = 'Gutenberg Block Editor';
     post.content = { raw: newContent };
     wp.data.dispatch('core/editor').setupEditor(post);
   })();
   ```
4. Observe the post content has updated.
5. Upgrade installation to WordPress 5.9
6. Create a post and run the above function in the console again
7. Observe the post content has not updated

### Environment info

- WordPress 5.9.0
- Gutenberg plugin disabled
- No plugins enabled for reproduction steps
- Browser: Firefox Developer Edition 97/macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I think possibly from https://github.com/WordPress/gutenberg/pull/33727? With the changes in the `actions.js`, it looks like `resetBlocks` is only called for new posts.

There is a question of whether `setupEditor` is the right function to use to update the editor content. The docs are not very explicit on the usage of that function and whether updating the editor content is an expected outcome of calling it. There were already some caveats around when the function would work with the previous implementation. This is something that's quite difficult to judge in retrospective, as I'm not sure what other APIs were available at the time or what other changes to the function/docs might have been made previously.

The solution in the linked PR with `resetBlocks` looks a lot better. 👍 

cc @youknowriad, would be great to get your thoughts.

**Comment by youknowriad** [comment]
Hi there! and sorry for the breakage @peterwilsoncc 

That looks like an unintended breaking change indeed. 

Reflecting on it, I think it might impact some plugins/third party code but not much. `setupEditor` seems like an editor/internal specific action to me that ideally shouldn't be needed at all or instead only used by the editor itself. I don't think it was meant to be used to reset blocks/post content. I agree that `resetBlocks` is a good option here, potentially you could also rely on `editEntityRecord` action. 

Restoring the previous behavior will eliminate the performance optimization, this is kind of similar to the filter we have in `editor.BlockListBlock` that prevent us sometimes from doing important optimizations. Given that there are good workarounds that work in previous versions too, I think it's preferable if we keep the new behavior here if possible.

**Comment by peterwilsoncc** [comment]
@youknowriad Thanks for following up.

I'd prefer to re-enable it to keep with WP's ethos of maintaining backward compatibility. If there is to be a break, then a soft deprecation needs to be in place for several versions of WP. For the plugin I experienced the issue on, we did need to bump the minimum supported WP version to account for the change. 

I'm seeing a few [apparent uses in the plugin directory](https://wpdirectory.net/search/01FTY9VGE1DDV5G7VYB6F3PZH8). It's difficult to tell with compressed code but I think the Visual Composer is the first true positive with 90,000+ installs.

**Comment by youknowriad** [comment]
I'd be fine if we try to reenable with a deprecation and remove it later, I don't want the user to pay the price of backward compatibility when the developer can make a small change to avoid the issue. Alternatively, I'm also ok with a dev note here.

**Comment by peterwilsoncc** [comment]
> I'd be fine if we try to reenable with a deprecation and remove it later

Thank you, can this be done for 5.9.1. I'll add it to the project for 5.9.x

> I don't want the user to pay the price of backward compatibility when the developer can make a small change to avoid the issue. Alternatively, I'm also ok with a dev note here.

I suspect you and I are looking at the same issue and coming to a different conclusion. I think the risk is the user pays because a developer doesn't realise they need to update their code.

I do agree that soft deprecation should eventually move to a hard deprecation but it's a discussion that needs to be regarding all of WordPress, not just the parts that are been worked on in this repository.

**Comment by youknowriad** [comment]
> I suspect you and I are looking at the same issue and coming to a different conclusion. I think the risk is the user pays because a developer doesn't realise they need to update their code.

I think it highly depends on the feature we're deprecating. In this case, it was never advertised as an API to reset post content and it was misused that way and the impact doesn't seem that high to me. 

But I agree with you that in general in Gutenberg (and core) we avoid breaking changes entirely and deprecation last years before considering removals.

**Comment by jordesign** [comment]
Hey @peterwilsoncc  - just wanted to check if you still see this an issue in 6.3 or if it has been resolved in the interim.

**Comment by peterwilsoncc** [comment]
> just wanted to check if you still see this an issue in 6.3 or if it has been resolved in the interim.

@jordesign Unfortunately it was never fixed but I think this can be closed as wontfix as it's been broken for a number of releases now.
