### ISSUE TITLE
Testing Overview docs formatting

### ISSUE THREAD

**Issue by pento** [WordPress/gutenberg#3838]
Ref: https://wordpress.org/gutenberg/handbook/reference/testing-overview/

In the first section, the shell scripts aren't highlighting correctly - code blocks don't work in lists, for some reason. I'm inclined to move the comment to be a sentence in the first list item, then the code can just be the command.

There are a bunch of soft line breaks in document. While these are allowed by the Markdown spec, Jetpack Markdown turns them into `<br/>`s, to match WordPress' behaviour.

See #3818.

**Comment by gziolo** [comment]
@pento thanks for investigating and opening this issue. Updating right away 👍
