### ISSUE TITLE
[Pagination] Allow users to customize page numbers

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#38386]
When using the "Pagination" block, it's possible to change the Typography and Color settings for the "Previous Post" and "Next Post" child blocks, but the "Page Numbers" block does not have this control: 

![page-numbers](https://user-images.githubusercontent.com/1202812/151862295-1d1e2af6-6af8-46d9-9a56-ab8ffdb66a8c.gif)

Additionally, it would be nice to be able to control the spacing in between the numbers. 

---
Tested with WordPress 5.9
Originally reported in the [Twenty Twenty-Two Support Forums](https://wordpress.org/support/topic/paging-with-numbering-has-too-small-numbers-and-spacing-between-them/).

**Comment by carolinan** [comment]
Do you think we should use block gap ("block spacing") for the numbers?

**Comment by carolinan** [comment]
Hmm how come the next and previous only have background color support  🤔

**Comment by kjellr** [comment]
Perhaps we should technically use it. But I don't think it should be the same default `blockGap` value that we use elsewhere since that's generally wider than we need.

**Comment by carolinan** [comment]
Yeah the default is no gap, it is only applied if a gap is added.
