### ISSUE TITLE
Widgets editor: Block appender does not appear as full width

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#38390]
### Description

The block appender in the Widgets screen appears as a small button to the right of the widget area. It should expand to fill the widget area.

You could potentially use `git bisect` to find what commit broke this.

### Step-by-step reproduction instructions

1. Activate a classic theme.
2. Go to Appearance → Widgets. 
3. Look at the block appender at the bottom of any widget area.

### Screenshots, screen recording, code snippet

<img width="743" alt="Screen Shot 2022-02-01 at 12 15 50" src="https://user-images.githubusercontent.com/612155/151899122-2d1832c9-b735-4c4a-8475-6f5c156a0cbb.png">

You can see what the appender button _should_ look like when there are no blocks in the widget area:

<img width="725" alt="Screen Shot 2022-02-04 at 10 43 00" src="https://user-images.githubusercontent.com/612155/152447810-bf55c8f3-dcbe-47b3-b1de-07d0bf8a7b87.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by itsmingjie** [comment]
Hi! I'm one of the program coordinators of a nonprofit program called [CodeDay Init](https://labs.codeday.org/), and we partner with colleges to help CS students make their first open-source contribution. 

We'll claim this issue for now and a group of students will be on it soon with mentorship! If this issue is no longer relevant, please let me know.

**Comment by noisysocks** [comment]
Thanks @itsmingjie! The issue is still relevant. Let me know if you need help or extra info.

**Comment by upluke** [comment]
@noisysocks Hi, my group is working on this issue. We think we're located the styling on this issue. It seems it's part of wordPress issue instead gutenberg issue. Is it possible this might be the case?

**Comment by noisysocks** [comment]
Hello! The code that implements this is in the `edit-widgets` package, which is in the Gutenberg repo. WordPress imports this package which is how it ends up there.

https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-widgets/
