### ISSUE TITLE
WordPress editor fails to display most used terms under certain conditions.

### ISSUE THREAD

**Issue by toolstack** [WordPress/gutenberg#38394]
### Description

Using the block editor for a post in WordPress 5.9 (or older) may not display the most used tags cloud if the number of tags defined on the site is less than the MAX_MOST_USED_TERMS value.

### Step-by-step reproduction instructions

1. Create a new WordPress site.
2. Create a few tag groups (say 5).
3. Create a post and add all of these tags to the post and then publish it.
4. Create a second post and go to the tag block, notice that no MOST USED tags are listed.

### Screenshots, screen recording, code snippet

editor.js contains the following code:

```
const MAX_MOST_USED_TERMS = 10;
const DEFAULT_QUERY = {
  per_page: MAX_MOST_USED_TERMS,
  orderby: 'count',
  order: 'desc',
  hide_empty: true,
  _fields: 'id,name,count',
  context: 'view'
};
function MostUsedTerms(_ref) {
  let {
    onSelect,
    taxonomy
  } = _ref;
  const {
    _terms,
    showTerms
  } = Object(external_wp_data_["useSelect"])(select => {
    const mostUsedTerms = select(external_wp_coreData_["store"]).getEntityRecords('taxonomy', taxonomy.slug, DEFAULT_QUERY);
    return {
      _terms: mostUsedTerms,
      showTerms: (mostUsedTerms === null || mostUsedTerms === void 0 ? void 0 : mostUsedTerms.length) === MAX_MOST_USED_TERMS
    };
  }, []);

  if (!showTerms) {
    return null;
  }
```

The problem occurs because of:
```showTerms: (mostUsedTerms === null || mostUsedTerms === void 0 ? void 0 : mostUsedTerms.length) === MAX_MOST_USED_TERMS```

Which compares the length of the returned tags list (5 in the above example case) with the `MAX_MOST_USED_TERMS` constant, which by default is set to 10.

This results in 5 being not equal to 10 and `showTerms` being set to false.

This, I beleive, is an incorrect use of the `MAX_MOST_USED_TERMS` constant as it should only be used to represent the *most* terms returned, not the minimum.

I'd suggest creating a new `MIN_MOST_USED_TERMS` constant, set to 1, and use this instead replacing the code as follows:
```showTerms: (mostUsedTerms === null || mostUsedTerms === void 0 ? void 0 : mostUsedTerms.length) >= MIN_MOST_USED_TERMS```

I came across this while wanting to increase the `MAX_MOST_USED_TERMS` above the default 10.  In my case I set it to 100, but the site only has 49 tags, so it never shows any most used tags for a post.

### Environment info

- WordPress 5.9
- PHP 8.0
- Gutenberg plugin not install, using default WordPress block editor included in 5.9.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ocean90** [comment]
The actual code can be seen here: https://github.com/WordPress/gutenberg/blob/69c882acf5b0bea7e847468ff3ef5a2d34f2bbb9/packages/editor/src/components/post-taxonomies/most-used-terms.js#L29-L39

**Comment by Mamaduka** [comment]
We can update the condition to check that there's at least one term returned and avoid using MAX/MIN completely.

What do you think?

**Comment by jasmussen** [comment]
Great thoughts. It makes sense to revisit the thresholds for min/max tags. 

Tags, unlike categories, can be spur-of-the-moment labels to help index random content, making it likely for big archives to have an ocean of tags, some of them used only once. That feels like a good reason to keep a max amount of suggestions to show.

The term "Most used tags" also feels like it implies a minimum amount of tags present on the site. The current min-threshold, 10, has shown itself too large. How about we lower that to 3? If need be, we can reduce it to 1, but that would dilute the "Most used" a bit. Not a strong opinion.

**Comment by toolstack** [comment]
> We can update the condition to check that there's at least one term returned and avoid using MAX/MIN completely.
> 
> What do you think?

This would work fine as well, I went with a MIN const simply to keep with the existing coding standard of using MAX.

**Comment by toolstack** [comment]
> Tags, unlike categories, can be spur-of-the-moment labels to help index random content, making it likely for big archives to have an ocean of tags, some of them used only once. That feels like a good reason to keep a max amount of suggestions to show.

Agreed, and the MIN/MAX should proably be controllable through a preference or API, as every site uses tags differently, so no one setting would work for everyone.

> The term "Most used tags" also feels like it implies a minimum amount of tags present on the site. The current min-threshold, 10, has shown itself too large. How about we lower that to 3? If need be, we can reduce it to 1, but that would dilute the "Most used" a bit. Not a strong opinion.

I think, as mentioned above, that this needs to be configurable somehow, no one setting will work for every site but 10 is probably a resonable default.

**Comment by Mamaduka** [comment]
I agree that it would be nice to control this via API. Maybe enable the feature and configure numbers via `register_taxonomy.`

Meanwhile, I've updated the min threshold for `showTerms` - https://github.com/WordPress/gutenberg/pull/38513

P.S. There's also a discussion to make the editor more extendible - #37448.
