### ISSUE TITLE
WP 5.9 Gutenberg Editor Not Working in Brave Browser

### ISSUE THREAD

**Issue by ritvikos** [WordPress/gutenberg#38395]
### Description

The Gutenberg editor is not working in brave browser and displaying blank screen only.  
Later, I shifted to Google Chrome and editor is now working.

### Step-by-step reproduction instructions

1. Open Brave Browser.
2. Disable the Brave Blocker.
3. Login the WP Site.
4. Open the editor (Both the Draft and Published posts not working).

### Environment info

- **Version:** 
WordPress 5.9

- **Browser:** 
Brave Browser without Brave Blocker

- **OS:** 
Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
My OS is also WIndows 11, and I installed the Brave browse.

Gutenberg Editor worked with the default browser settings, block theme and full site editor also work fine.

I'm wondering if the browser extension has any effect on this.

**Comment by talldan** [comment]
I also use Brave as my regular browser, though I'm usually on Mac OS. I've had no issues running any of the block editors.

Definitely work checking browser extensions. Also open up the developer tools (right click and choose 'Inspect') and look at the console tab to see if there are any errors in red text.

**Comment by ritvikos** [comment]
@t-hamano and @talldan:
Yeah! It was extension incompatibility, disabled all the extensions and Gutenberg working again!
Solved!
