### ISSUE TITLE
Post/page constantly in "dirty" state after activating some plugins

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#38411]
### Description

Upon activating some plugins (e.g. "Lightbox with photoswipe" , "Polylang",...) post/page is constantly in "dirty" - unsaved state. This did not happen in earlier versions of WordPress so I guess it is some kind of compatibility issue.

### Step-by-step reproduction instructions

1. Install plugin ("Lightbox with photoswipe", "Polylang")
2. Create page/post, enter some text
3. Press update button

When all plugins are deactivated, this does not happen.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Lovor01** [comment]
Update: I managed to trace the source of the problem - at least for plugin "Lightbox with photoswipe". It this hook on admin part: `add_action( 'add_meta_boxes', [$this, 'metaBox'] );`, which in turn calls this:
```
...
            add_meta_box(
                'lightbox-photoswipe',
                __('Lightbox with PhotoSwipe', 'lightbox-photoswipe'),
                [$this, 'metaBoxHtml'],
                $type,
                'side'
            );
...
```
This code is placed in lightbox-photoswipe.php on lines 146 and 1296

Therefore it seems, that old-way of creating meta-boxes ind editor now results in unsaved state.

**Comment by arnowelzel** [comment]
> Update: I managed to trace the source of the problem - at least for plugin "Lightbox with photoswipe". It this hook on admin part: `add_action( 'add_meta_boxes', [$this, 'metaBox'] );`, which in turn calls this:
> 
> ```
> ...
>             add_meta_box(
>                 'lightbox-photoswipe',
>                 __('Lightbox with PhotoSwipe', 'lightbox-photoswipe'),
>                 [$this, 'metaBoxHtml'],
>                 $type,
>                 'side'
>             );
> ...
> ```
> 
> This code is placed in lightbox-photoswipe.php on lines 146 and 1296
> 
> Therefore it seems, that old-way of creating meta-boxes ind editor now results in unsaved state.

Please verify this by disabling the option "Show this setting as checkbox in page/post editor" in the general settings of Lightbox with Photoswipe. If the option is disabled, the whole metabox code will not be called at all.

Also see https://github.com/arnowelzel/lightbox-photoswipe/blob/main/lightbox-photoswipe.php#L144-L148.

If the problem then still persist, there is another issue which has nothing to do with the metabox code.

**Comment by Lovor01** [comment]
> Please verify this by disabling the option "Show this setting as checkbox in page/post editor" in the general settings of Lightbox with Photoswipe. If the option is disabled, the whole metabox code will not be called at all.
> 
> Also see https://github.com/arnowelzel/lightbox-photoswipe/blob/main/lightbox-photoswipe.php#L144-L148.
> 
> If the problem then still persist, there is another issue which has nothing to do with the metabox code.
 
I can confirm the issue. Issue disappears when option "Show this setting as checkbox in page/post editor" is disabled.

However, I consider this a WordPress compatibility issue, not a plugin issue.

**Comment by arnowelzel** [comment]
> I can confirm the issue. Issue disappears when option "Show this setting as checkbox in page/post editor" is disabled.
> 
> However, I consider this a WordPress compatibility issue, not a plugin issue.

Anyway - I will implement the Gutenberg style metabox in the next update of my plugin and hopefully also find a way to disable the "old" style metabox if Gutenberg is detected.
