### ISSUE TITLE
Transformed or split Heading blocks have incorrect line height for block themes

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#38421]
## Description

Related to https://github.com/WordPress/gutenberg/issues/37168. While a block theme is utilized, transforming a block to a Heading block or splitting an existing Heading block results in the Heading block displaying an incorrect line height. This results in longer, wrapping text overlapping itself. 

The solution in https://github.com/WordPress/gutenberg/pull/37285 addressed the issue for typing into a Heading block, but transforming/splitting appears to remain an issue. 

This issue occurs only on Android, it does not occur on iOS. 

## Step-by-step reproduction instructions

1. Add a Paragraph block. 
2. Type enough text so that the text will wrap. 
3. Transform the Paragraph block to a Heading block. 

## Expected behaviour
The correct line height is applied to the Heading block and the text is not overlapping. 

## Actual behaviour

The incorrect line height is applied to the Heading block and the text is overlapping. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/438664/152023798-d1a2034b-d4ac-4755-9bf6-531583c35c86.mp4

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: 12.4.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No, Geologist. 

## Device information
- Device:  Samsung Galaxy S20
- Operating system:  Android 11
- WordPress app version:  18.9

**Comment by geriux** [comment]
This should be fixed in https://github.com/WordPress/gutenberg/pull/38205 to be confirmed in the `1.71.0` release.

**Comment by geriux** [comment]
I've just confirmed in the `1.71.0` build that this issue is fixed 🎉 

https://user-images.githubusercontent.com/4885740/152508214-8dbc92bd-f64f-47da-8960-e9842aa5b562.mp4


Closing the issue 😃
