### ISSUE TITLE
Add body background image to global styles (Customizer feature parity)

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#38436]
## What problem does this address?

I am receiving support questions related to block themes, and one of the questions that has been recurring is how to add a body background image without access to the Customizer.

This is possible using the cover block. But if you want to use the same background image on all pages on the site, you need to add the block to all the templates.
In my _opinion_, the cover block is superior to the body background image settings that is available in the customizer, except for in this scenario, because of the effort it takes to add the image to all templates.

## What is your proposed solution?

I am suggesting that a site wide body background image option could be added to the styles sidebar.

Related: https://github.com/WordPress/gutenberg/issues/16479

**Comment by carolinan** [comment]
This feature was requested by an attendee at a workshop at WCEU 2023.

**Comment by carolinan** [comment]
@WordPress/gutenberg-design Where might this feature go in the Site Editor Styles sidebar?
And how would this be handled in case you want different background images on different templates? 🤔

**Comment by jameskoster** [comment]
> Where might this feature go in the Site Editor Styles sidebar?

Good question, there's no obvious destination currently. 

> And how would this be handled in case you want different background images on different templates?

This part would be handled by https://github.com/WordPress/gutenberg/issues/40318

**Comment by carolinan** [comment]
Maybe a site-wide body background would instead be under WordPress Admin > Settings > General.

**Comment by jasmussen** [comment]
Ideally we could find an inspector interface that worked across both individual pages/templates, and globally, and was essentially the same. Exactly like how you might customize a group locally, or in global styles → Blocks. @SaxonF you had an "Elements" section in a mockup once, any instincts here?

**Comment by annezazu** [comment]
AFAIK this can be closed out thanks to completed work for 6.6 to add a site wide background image option to Styles under Layout: https://github.com/WordPress/gutenberg/issues/54336

Closing out but let me know if any piece of this needs to be reopened :)
