### ISSUE TITLE
Update the block editor docs site to link to the source code

### ISSUE THREAD

**Issue by rmorse** [WordPress/gutenberg#38449]
## What problem does this address?

Very often I find myself looking at the component  reference in docs -
https://developer.wordpress.org/block-editor/reference-guides/components/base-control/

And shortly after I realise I need to deep dive and take a look at the source code, but there is no way for me to do that.

A shortcut I have used, is to click the "edit" github link, which takes me to editing the README of the component on github, but it's hardly intuitive.

In addition, most of the older docs (core), link to the respective code refences on trac for the various PHP classes, so adding this in would keep in tune with that.

## What is your proposed solution?

I think people reading the docs, would more often want to see the source code, than edit the readme.

Perhaps a "view source" style link could appear there instead, or in addtion.

And perhaps the edit link, could be made less prominent either by moving it to a "meta" area (under the title?) or simply differentiating the style of the button.

Here I just duplicated the button as an example, but it needs a designer to take a look at:

![image](https://user-images.githubusercontent.com/853547/152153750-48fe40e9-6a26-4cfe-949b-fe0a1d8228a2.png)

--

I'm not sure how the docs are generated from the readme files in this repo, but if someone wants to send me in the right direction I can do some futher digging.

**Comment by aurooba** [comment]
I think this is a fantastic idea! I do the same thing you do, @rmorse! 

@gziolo what's the best route for making this kind of thing happen?

@estelaris would this design be under your purview since it's documentation?

**Comment by gziolo** [comment]
> what's the best route for making this kind of thing happen?

The site with the Block Editor Handbook is maintained by the WordPress Meta team. @fabiankaegy, do you remember where changes to the Gutenberg docs get applied before publishing on the site?

**Comment by fabiankaegy** [comment]
@gziolo This is all the documentation I have: 

> I wouldn't call it documented - a process runs every 15 minutes and calls this script that converts the markdown to WP pages.
> https://github.com/WordPress/wordpress.org/blob/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-developer/inc/import-block-editor.php

https://twitter.com/mkaz/status/1470762333047648256

**Comment by ndiego** [comment]
I have [moved this issue over](https://github.com/WordPress/wporg-developer/issues/240) to the Developer.WordPress.org Theme repo. There is nothing we can do to fix it here in the Gutenberg repo.
