### ISSUE TITLE
Image Block 

### ISSUE THREAD

**Issue by kajalmultidots** [WordPress/gutenberg#38448]
### Description

When we choose image block we have the options for default styles in right side. but when we choose those styles(Not set, Default, Rounded) in select box, nothing happen. 

### Step-by-step reproduction instructions

Go to Image Block
choose image and upload it
show the right side option (default Style)
choose any one from them but nothing happen.
For more understanding I have provided the video link.

### Screenshots, screen recording, code snippet

https://www.loom.com/share/b815ca69a30147a6bfb81ebae67e54c3

### Environment info

WordPress version : 5.9

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
As you can see in the select box labeled "**Default Style**", this is for setting what style will be applied by default when you insert a block.

Therefore, changing the value of the select box will not change the style of the block.

This is true not only for image blocks, but also for other blocks that have block styles.

**Comment by kajalmultidots** [comment]
hi @t-hamano 
ok got it 👍 
Thanks
