### ISSUE TITLE
Gutenberg - Post Content is buggy, created issues using it.

### ISSUE THREAD

**Issue by jenfloods** [WordPress/gutenberg#38455]
### Description

When I try to use the Post Content block, it tries to add another post content and says I can't do one inside another. I have not used this module before, first time trying to use it to set up a layout template for single blog post template using Reusable Block Extended for a shortcode. I've tried editing on a post or post, same issue occurs.
![Post Content block issues](https://user-images.githubusercontent.com/51378247/152199871-038659ec-26d4-4571-aa85-fb945aa58e08.png)
![Post Content Issue in Reusuable Block Extended plugin](https://user-images.githubusercontent.com/51378247/152199874-6766ba82-299c-474e-8dc3-388e128d3527.png)
 

### Step-by-step reproduction instructions

I go to edit a post or page, add Post Content to the page, I get this error shown in screenshot. I have tried it on another site, same error/issue happening.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by grappler** [comment]
The Post Content Block can only be used within the Query Loop Block or in the FSE template editor.

**Comment by jenfloods** [comment]
ok How does one make a single Post Template using Gutenberg then?

**Comment by grappler** [comment]
To be able to use the Full Site Editing template editor, you need to use a theme that support Full Site Editing. Here are a few free themes that support it: https://wordpress.org/themes/tags/full-site-editing/

**Comment by jenfloods** [comment]
Thanks, I found one that works with Divi builder.

**Comment by skorasaurus** [comment]
hi @jenfloods ; 
It appears your question has been answered so I am closing the issue. If you still need assistance, please comment.
