### ISSUE TITLE
[Comments Query Loop] [Query Loop] Consider using a generic Avatar block

### ISSUE THREAD

**Issue by cbravobernal** [WordPress/gutenberg#38456]
## What problem does this address?

Right now, we have on Gutenberg two different blocks:
- Post Author Avatar Block. Which @carolinan [is doing an amazing job there](https://github.com/WordPress/gutenberg/pull/38265)
- Comment Author Avatar Block. I'm doing an update [on this PR to make it better](https://github.com/WordPress/gutenberg/pull/38072)

We are working in parallel, but, we are also taking the other's code quite a lot. Both are really similar, being the only difference in the data we fetch to get the Avatar (post author ID vs post comment ID), but both are just user ID.

## What is your proposed solution?

Explore if it makes sense to have only a Core Avatar Block and absorb the complexity of deciding which Avatar should be displayed on each case. This way we can:

- Reduce code duplication.
- Reduce user complexity, as it would only appear one option when searching for an Avatar.

<img width="1191" alt="Screenshot 2022-02-02 at 18 05 37" src="https://user-images.githubusercontent.com/37012961/152201947-687f9f10-23ca-4f4b-ba15-d4524d94ba4c.png">

[Excalidraw link](https://excalidraw.com/#json=Qxc3p_tcecp2242-gU_7f,2E5tMX6Lc8e2zgp97QIPIA)

CC: @michalczaplinski , @carolinan , @ntsekouras , @gziolo , @DAreRodz , @mtias

**Comment by michalczaplinski** [comment]
Hey @c4rl0sbr4v0 I'm all in favour of working out a solution here - I only wonder why 7 of has have been assigned to this issue? 🤔

**Comment by carolinan** [comment]
I agree.

It was suggested that there could be a _user block_ with variations, but there was no interest or buy-in for that approach.
https://github.com/WordPress/gutenberg/issues/24952

**Comment by cbravobernal** [comment]
> Hey @c4rl0sbr4v0 I'm all in favour of working out a solution here - I only wonder why 7 of has have been assigned to this issue? 🤔

That is my fault. I did that so you get notified and can discuss it 😅

**Comment by ntsekouras** [comment]
Variations seem like it could work and is worth exploring for blocks like `author name, avatar`, etc.. where we would detect if we want to display info for post or comment authors. I'm not sure a specific `user` block is valuable if we have the other related blocks as standalone.
