### ISSUE TITLE
Double scroll some time

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/gutenberg#38453]
Hi,
Page content on showing double scroll bar some time?
You can see Video link.https://www.loom.com/share/d34e17fda7ab4707972434cc32c918c2

**Comment by Mamaduka** [comment]
I've also noticed this issue using the TT2 theme.

**Comment by sumitsinghwp** [comment]
Yes @Mamaduka

**Comment by youknowriad** [comment]
The loom link doesn't work anymore and I haven't been able to reproduce. I'm closing for now but reopen if you manage to get clearer instructions.
