### ISSUE TITLE
Regression: Cover Block style changes in 5.9 break opacity for older cover blocks

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#38466]
### Description

I have a site using the standard cover block with no customizations. When updating to WordPress 5.9, the block's opacity setting does not work until resaving the page which forces the cover block's markup and classes to change.

Prior to WordPress 5.9, the `has-background-dim-XX` class was on the cover block container. That class was moved to a `span` that's a direct descendant of the parent div. These markup changes won't be applied to legacy content until a post is resaved, but it appears the styles that make old cover block opacity work were removed.

Solution: The `has-background-dim-XX` classes that work when applied to the Cover block's parent container should be left in core indefinitely for the purposes of backward compatibility.

### Step-by-step reproduction instructions

1. In WordPress 5.8.3 or earlier, create a cover block with an opacity other than 50% (so that one of the `has-background-dim-XX` classes are applied)
2. Update to WordPress 5.9
3. Cover block has 50% opacity
4. Save the page
5. Cover block markup is changed and custom opacity is reapplied

### Screenshots, screen recording, code snippet

WordPress 5.8.3 (90% opacity, classes: `wp-block-cover alignfull has-background-dim-90 has-palette-2-background-color has-background-dim has-parallax is-style-no-padding`):
![image](https://user-images.githubusercontent.com/1238696/152256926-235913dc-1af9-45e2-b7f0-425aeea9985e.png)

WordPress 5.9:
![image](https://user-images.githubusercontent.com/1238696/152256975-3e88f174-9c78-4b9f-bcd6-11af43afc308.png)

### Environment info

- WordPress 5.9
- Themes Tested: Twenty Twenty One and `theme.json` child theme of [Michelle](https://www.webmandesign.eu/portfolio/michelle-wordpress-theme/)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mrwweb** [comment]
A quick note that I've updated the issue a few times and have replicated the issue on a simpler install using the Twenty Twenty One theme.

**Comment by annezazu** [comment]
Adding to the 5.9.x project board so it can be reviewed. Thank you for flagging!

**Comment by glendaviesnz** [comment]
This is fixed by https://github.com/WordPress/gutenberg/pull/38362, which is merged and flagged for inclusion in 5.9.1

**Comment by annezazu** [comment]
Ah ha! Just was about to come back through here after noticing your lovely PR. Thank you!

**Comment by glendaviesnz** [comment]
An additional note for anyone waiting for this to go out in 5.9.1 - [adding this](https://gist.github.com/glendaviesnz/b3480d37ff0ea75103cea8ca5bd1796b) to site custom CSS should fix the issue in the meantime.
