### ISSUE TITLE
Pressing Enter on a Block should engage "isTyping" mode

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#3846]
When you press enter on a block (say, heading) we should engage isTyping mode. At the moment it keeps the mode you are in. So if you have moved your mouse and pressed enter, the new block shows the toolbar.

**Comment by iseulde** [comment]
Correct, we only trigger isTyping on inside a block, not backspace/enter etc. cross blocks. If `isTyping` was already true before though, it will keep the toolbar hidden. If it was visible, it won't hide it. So I guess you're saying it should di the toolbars on any keyboard input actions?

**Comment by iseulde** [comment]
This again seems like one of those cases where it would be better if `Editable` could directly adjust the state instead of through the block.

**Comment by mtias** [comment]
Yes, I mean we should treat enter as a cross-block isTyping action.
