### ISSUE TITLE
Button Block Issue

### ISSUE THREAD

**Issue by kajalmultidots** [WordPress/gutenberg#38473]
### Description

When we choose Button block we have the option in sidebar for styles
If we choose any styles(Fill, Outline) that is reflected on Button but in the sidebar that option of styles(Fill, Outline) is not seen properly. This is same issue as Image Block.

### Step-by-step reproduction instructions

Go to Button Block
In the right side Go to Styles option (Fill, Outline)
There is some issue. It is not looking perfectly
I have attached the screenshot for better understanding

### Screenshots, screen recording, code snippet

<img width="1440" alt="Screenshot 2022-02-03 at 1 06 58 PM" src="https://user-images.githubusercontent.com/97427256/152301144-3d0f87f1-897d-4e0f-9363-bcd7c6943231.png">

### Environment info

WordPress Version : 5.9

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting: 
The outline style in the button block's sidebar preview is appearing cutoff. 
can you share what theme and web browser that you are using ? Can you also please deactivate all other plugins and share if you are still having the same experience after doing that? 

I am no able to reproduce it with WordPress 5.9, no plugins and the twentytwent

I am able to reproduce this using the popper theme, Wordpress 5.9, gutenberg deactivated, and if I zoom in my browser window (firefox 96, ubuntu)

![image](https://user-images.githubusercontent.com/955351/152408111-894f7ecf-de89-422e-917c-1d2b4033ffcf.png)

**Comment by skorasaurus** [comment]
@kajalmultidots 

The block style previews have been overhauled and implemented in https://github.com/WordPress/gutenberg/pull/34522 ;  Are you able to reproduce this after you have installed and activated the newest version of Gutenberg that is available through [the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/)?

**Comment by kajalmultidots** [comment]
Hello @skorasaurus,

As you can see in this video there is no plugins installed in my wordPress site,
And i'm using the theme Twenty-Twenty two and my wordPress version is also updated it is 5.9. 
I am using Mac and Chrome browser. 
I'm facing this issue as i mentioned previously. 
**Here is the video link I have attached.**
- https://www.loom.com/share/03397dd2624e45d9aca2ced84b409dad

Thank You

**Comment by skorasaurus** [comment]
@kajalmultidots 

Could you please test again with Gutenberg plugin installed and activated? [The Gutenberg plugin](https://wordpress.org/plugins/gutenberg/) contains the latest fixes and improvements of the block editor have yet to be added the core WordPress installation. The updates in the Gutenberg plugin will eventually be added to the core WordPress installation but we need to confirm whether the newest changes in Gutenberg have fixed this issue or not.

**Comment by kajalmultidots** [comment]
Hello @skorasaurus

Yes, it is working properly in Gutenberg Plugin. In that, the whole design is changed which is very good.
Thanks
