### ISSUE TITLE
In WordPress 5.9 color palette overlap with circular color picker issue

### ISSUE THREAD

**Issue by minaldiwan** [WordPress/gutenberg#38471]
### Description

In WordPress 5.9 color palette overlap with circular color picker issue are occured when we hover on circular color picker.
I have attached screenshot for it
<img width="1269" alt="Screenshot 2022-02-02 at 11 32 42 AM" src="https://user-images.githubusercontent.com/77973388/152292577-bf52bbcd-cfe5-4e10-be8b-47f04a114c8f.png">

### Step-by-step reproduction instructions

clicking on text editor moving to highlight setting block control setting
open the color palette setting hover on color picker
here we shown overlap between color palatte and circular color picker in google chrome.
added css for it.
`.components-color-palette__custom-color {
  margin-bottom: 8px;
}`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I can replicate this! I think this might be related somehow to some weirdness I'm seeing here potentially: https://github.com/WordPress/gutenberg/issues/38255

In any case, this is definitely a bug :) 

https://user-images.githubusercontent.com/26996883/153156680-b5e701a8-a0ac-4f53-a6c5-37ac7a829a3c.mov

**Comment by ndiego** [comment]
I can replicate in the Site Editor, but not in the standard page/post Editor.

**Comment by t-hamano** [comment]
This problem could not be reproduced, at least in WordPress 6.2 RC4. Is it possible to close this issue?
