### ISSUE TITLE
Query pagination prev/next arrow/chevron span incorrectly escaped

### ISSUE THREAD

**Issue by Andrew-Starr** [WordPress/gutenberg#38489]
### Description

When adding a Query Loop to a page/post and selecting the Arrow or Chevron style in the Pagination block, the inline span that is added to the Previous & Next links is being escaped incorrectly, resulting in incorrect markup.

This issue is only present when Gutenberg is active and only when added to a page/post, not when included in a template.

In 5.9 without Gutenberg active, the issue is not present and the arrow displays correctly.

### Step-by-step reproduction instructions

Add a Query Loop block to a post or page.
In the Pagination inner block, make sure to select Arrow or Chevron under Block > Settings > Arrow.
View post or page in frontend and notice the inline span in the previous and next links appear as `&lt;span class=&#039;wp-block-query-pagination-next-arrow is-arrow-arrow&#039;&gt;→&lt;/span&gt;`

### Screenshots, screen recording, code snippet

This is the resulting markup on the frontend with Gutenberg active

```
<a href="/test-page/?query-22-page=2" class="wp-block-query-pagination-next has-small-font-size">Next Page&lt;span class=&#039;wp-block-query-pagination-next-arrow is-arrow-arrow&#039;&gt;→&lt;/span&gt;</a>
```

### Environment info

WP 5.9
Gutenberg 12.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Andrew-Starr** [comment]
Without Gutenberg active, all is okay:

![next-page-link-span-ok](https://user-images.githubusercontent.com/94701043/152517482-b33db892-6169-41a0-8483-c1a456c7235a.jpg)

With Gutenberg active, the inline span is displayed incorrectly:

![next-page-link-span](https://user-images.githubusercontent.com/94701043/152517600-977d68dd-6676-4d02-ae7f-c7dd7a72d3fc.jpg)

**Comment by getdave** [comment]
I'll get a fix up for this shortly.
