### ISSUE TITLE
read more link not working

### ISSUE THREAD

**Issue by marieannabt** [WordPress/gutenberg#38499]
### Description

When Guntenberg is activated , my "read more" link disappear on all my pages. Instead, a line of code appears : 

`<a class="moretag" href="(https link)"><br>Read more</a>`

### Step-by-step reproduction instructions

Just activate the extension 

### Environment info

Destock and Mobile 
Gutenberg Version 12.5.0
Theme Seedlet

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Hey there! Thanks for opening this issue. Can you provide more context as to what's going on? I'm not able to replicate using Seedlet, WordPress 5.9, and Gutenberg 12.6. I tested by adding a read more to a post and viewing it on the homepage. I was able to find that the read more link showed up and properly took me to the post in question.

**Comment by adamwoodnz** [comment]
Closing following triage policy
