### ISSUE TITLE
Group Block [Row]: Support both vertical and horizontal alignment

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#38498]
## What problem does this address?

Right now using the row block the only vertical alignment possible is centered. Layouts like the one from the screenshot require extra CSS.

<img width="942" alt="Screenshot 2022-02-03 at 17 28 08" src="https://user-images.githubusercontent.com/3593343/152390562-3e8c6454-64ce-486d-8b46-38ab6ae88bb2.png">

## What is your proposed solution?

Since we are using flexbox, we could use vertical alignments like the column and the media+text blocks do:

<img width="163" alt="Screenshot 2022-02-03 at 17 57 34" src="https://user-images.githubusercontent.com/3593343/152390897-f68c985f-3a05-4963-bf87-a07a0a00f93e.png">

I've had a look and both the columns block and the media+text use `align-self` instead of `align-items`, I wonder what would be the best case for this.

I'd love your thoughts on this @youknowriad

**Comment by youknowriad** [comment]
I think adding alignment config like that to the "flex" layout makes sense. All blocks using that layout could benefit form it as well.

**Comment by vjsasinathan** [comment]
I am working on adding the alignment options

**Comment by vjsasinathan** [comment]
Seems to be a valid use case. Adding a vertical alignment configuration would definitely help content creators align with their design without extra CSS overrides. Feature enhancement on the way. Please assign the ticket to me.

**Comment by karmatosed** [comment]
@vjsasinathan thanks for taking this on, just assigned to you.

**Comment by MaggieCabrera** [comment]
Thank you @vjsasinathan please do tag me on your PR for review, please!

**Comment by WORX-Developer** [comment]
Please consider implementing "align-items: stretch" as well. As sometimes it is very handy to have equal height items in a row.

**Comment by paaljoachim** [comment]
@JustinyAhin Justin
Has made a draft PR here: https://github.com/WordPress/gutenberg/pull/40013
