### ISSUE TITLE
Sub-pixel scaling browser bug in live preview component

### ISSUE THREAD

**Issue by KevinBatdorf** [WordPress/gutenberg#38492]
### Description

Both the height and scaling on the live preview component allow sub-pixel values, which may cause browsers to behave unexpectedly.

The sub-pixel height its probably okay but the combination of the height and scaling could be the issue. 

Or maybe both could be clamped to a 2 digits?

### Step-by-step reproduction instructions

I added an example pattern for a block plugin I'm working on, and added the code via `register_block_pattern`. It might not be easy to reproduce as in my screencast below, but seeing the sub-pixel values is easy enough to view on any live component.

### Screenshots, screen recording, code snippet

Live preview built in 2022 pattern (no rendering issue though):

![Screen Shot 2022-02-03 at 10 39 17 AM](https://user-images.githubusercontent.com/1478421/152379867-bdf4fe72-2f42-434c-b8d8-dbf806b2c76f.png)

Custom pattern added with render issue:

https://user-images.githubusercontent.com/1478421/152380118-18fbeb74-6bd5-46ec-b0ea-88002ca849fe.mov

### Environment info

2022 theme
Happens in WP 5.9 with and without Gutenberg plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Nearly positive this matches this issue which has since been resolved: https://github.com/WordPress/gutenberg/issues/38501

Going to close out as a duplicate but thank you for opening and let me know if I somehow missed something causing this to need to remain open.

**Comment by KevinBatdorf** [comment]
Hi @annezazu I'm not sure that's related but I'll check it out and open the issue back up if I'm still seeing it.
