### ISSUE TITLE
When using Drop Cap alignment breaks if paragraph isn't long enough

### ISSUE THREAD

**Issue by tekknow90** [WordPress/gutenberg#38507]
When I use the Drop Cap like the screenshots below it misaligns with the rest of the page, the paragraph seems to need to be long enough to cover the drop cap to fix the issue.

I am on WordPress 5.9 using the Hotel Luxury theme.

![Screenshot (24)](https://user-images.githubusercontent.com/29907472/152460808-389a6c4a-162e-49fb-90d0-29b1eb189de8.png)
![Screenshot (25)](https://user-images.githubusercontent.com/29907472/152460817-5790e687-d92c-4e9c-913b-2cbb0bc4d32b.png)
![Screenshot (26)](https://user-images.githubusercontent.com/29907472/152460820-295217b6-4d4c-4ed8-8b01-f6ce24ef1d59.png)

**Comment by jordesign** [comment]
Closing this issue - as Drop Caps are no longer supported/addable in the editor
