### ISSUE TITLE
Image for preview when hovering at block in admin panel

### ISSUE THREAD

**Issue by budyaaa** [WordPress/gutenberg#38506]
### Description
It is currently impossible to simply set image as block preview in editor menu. Cause preview loads from edit function.
![image](https://user-images.githubusercontent.com/53225297/152455698-b2dbf2ae-28b0-45eb-ace8-0f8536f61127.png)

### Proposal
I think that adding new function to existing "edit" and "save" will be good idea. For example it can be named "example". In this function will be items for loading in preview. So developer can insert code inside it or simple image to show how block will be looking at user part of website.

**Comment by youknowriad** [comment]
There's already an "example" property that can be used to show image, just like we do for the image block. Let me know if I'm missing anything.
