### ISSUE TITLE
Individual patterns not scaled appropriately until after adding

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38501]
### Description

Pulling from this original issue with scrollbars https://github.com/WordPress/gutenberg/issues/37573, there now seems to be an issue where the height of the patterns preview is off. On my end with 5.9 sans Gutenberg, the experience is one where before adding the pattern, the height is off in the Inserter but, after adding it, the height shows up correctly.

### Step-by-step reproduction instructions

1. Open Inserter > Patterns tab.
2. Scroll through and look at patterns noticing they are cut off.
3. Add a cut off pattern.
4. Open the Inserter > Patterns tab and notice the same pattern you added is the right height.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/152405319-5546389f-9e82-40ac-b135-f70ba8cb9381.mov

### Environment info

- WordPress 5.9
- No Gutenberg.
- TT2
- MacOS
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by WhiteHeatherClub** [comment]
Patterns that are previewed incorrectly never appear correctly in the inserter for me, even after adding to the page. With latest Gutenberg plugin things are better - but not perfect. Correct aspect ratio **is** previewed, but very long patterns are being cut off.

https://user-images.githubusercontent.com/97255524/152446319-3c3085ea-4f9d-419b-9e61-e8c739c8e842.mp4

**Comment by jasmussen** [comment]
Wanted to crosslink this with #38181 which may well help. Notably for any devs looking at this, I would point to @ixkaito's [assessment of why the scaling issue happens](https://github.com/WordPress/gutenberg/pull/38181#issuecomment-1021835774), in case it helps debugging:

> The following image shows the reason for the race condition with the expanding patterns.
> 
> ![38181](https://user-images.githubusercontent.com/5457539/151101767-66976691-2410-479c-93f9-c1cfc4ec2a12.png)
> 
> The race condition occurs with full-height blocks with vertical margins and also blocks with a height over than 100vh, so it seems that we still need to set a max height to the viewport (`iframe`).

Thank you @ixkaito!

**Comment by ellatrix** [comment]
For me it just seems to take a few seconds to load, but after that it expands to fit the content correctly 🤔
Is it just that there's a delay in loading the preview, or does it stay collapsed for you?

**Comment by annezazu** [comment]
It stays collapsed for me.
