### ISSUE TITLE
Add help text below Link attributes in Inspector for Nav link and Nav Submenu blocks

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#38518]
## What problem does this address?

Some of the more obscure link attributes used within the block inspector controls of the `core/navigation-link` and `core/navigation-submenu` blocks may need some explanation in the interface. Currently they could be confused with other similarly named attributes.

<img width="361" alt="Screen Shot 2022-02-04 at 10 41 55" src="https://user-images.githubusercontent.com/444434/152515635-8d2744be-6eef-4649-8df9-471003796075.png">

## What is your proposed solution?

Add explanatory text below these attributes like we do with other attributes.

**Comment by jordesign** [comment]
Closing this as it seems this interface has changed both the labels and descriptions to be clearer. Please feel free to re-open if that's not the case.

<img width="272" alt="Screenshot 2023-10-25 at 9 18 44 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/04e9b529-1e32-411b-a7a9-3c81b174f835">
