### ISSUE TITLE
Support multiple color palettes on Mobile

### ISSUE THREAD

**Issue by geriux** [WordPress/gutenberg#38525]
## Description
On mobile, we are working on adding support for multiple color palettes in https://github.com/WordPress/gutenberg/pull/38417. 

Users can now create their own colors that would be shown in a `Custom` palette. So we'll have `Theme` and `Default` and the `Custom` palette will be shown if users add new colors.

The initial implementation is merging all palettes into one row, but it was mentioned from the code review feedback to maybe do something similar to the way the web editor does it:

<kbd><img width="150" src="https://user-images.githubusercontent.com/14905380/152340291-507aa861-a4ba-4637-822f-b72c0fc0db89.png" /></kbd>

On mobile we currently have one row of colors:

<kbd><img width="150" src="https://user-images.githubusercontent.com/14905380/152519816-a936c1db-3c63-432b-895b-12a86bc2d0c9.png"/></kbd>

@iamthomasbishop I was wondering if you had any design ideas about this since we've only had one row of colors until now. The functionality would be as it was before, you can only select one color at a time. Thank you!

**Comment by iamthomasbishop** [comment]
@geriux I think we could separate them similarly into sections, each section with a leading section header. Would something along the lines of this make sense?

<a href="https://user-images.githubusercontent.com/1200432/152567080-4768e279-19be-4d46-bf36-5bf987a7d3fd.png"><img src="https://user-images.githubusercontent.com/1200432/152567080-4768e279-19be-4d46-bf36-5bf987a7d3fd.png" width="1000"></a>

One other thing, which isn't directly related to this, but has me wondering: As far as I know, we don't currently support saving multiple "custom" colors on mobile (at least directly in the editor UI). Is the idea that we'd just show the custom color swatches that the user has already saved via the web UI?

**Comment by geriux** [comment]
> @geriux I think we could separate them similarly into sections, each section with a leading section header. Would something along the lines of this make sense?

It does, thank you for the mockup!

> Is the idea that we'd just show the custom color swatches that the user has already saved via the web UI?

That's correct, users won't be able to edit/customize them within the mobile editor.

Thanks again Thomas!
