### ISSUE TITLE
Building with Patterns

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#38529]
This issue will track and describe a few projects around making patterns a more central part of the experience of creating templates and pages.

## Inserter

- [x] #41379
- [x] #44582.

## Creation

This is about discovery and the user experience of starting with blank or partially blank templates, the role of semantic template parts as containers, etc.

- [ ] #48458. 💎
- [ ] #39281.
- [ ] #27575.
- [x] #44581.
- [x] #41397. ⚠️
- [x] #36697.
- [x] #28737.
- [x] #31033.
- [x] #28739.

## Theme Registration and Directory

- [x] #35364.
- [x] #36751.

## New Pages

- [x] #38787

**Comment by mtias** [comment]
I grouped some consideration that are being surfaced as we use patterns more as building tools into #39281 to try and address some of the main usability issues that are appearing.

**Comment by dugyen** [comment]
@mtias @annezazu 
Is it possible to add [those patterns available in wordpress.org ](https://wordpress.org/patterns/) to the themes's/patterns directory?

**Comment by dugyen** [comment]
It would help WordPress users to search directly from TT3 or Updated TT2 theme, not from WordPress.org

**Comment by annezazu** [comment]
@dugyen can you explain a bit more what you want to see? Feel free to DM me on slack (@annezazu on Make Slack) so we can talk out what you want and not detract from this issue. You are welcome to also open a new issue for this repo and tag me in it too :)

**Comment by simison** [comment]
@mtias @jorgefilipecosta for "New Pages" section, [block patterns for page creation](https://github.com/WordPress/gutenberg/pull/41791) is a great start. The modal could do with some UX improvements next up to get closer to the screenshot [in the original issue](https://github.com/WordPress/gutenberg/issues/38787).

[I elaborated more in a new issue](https://github.com/WordPress/gutenberg/issues/46498); mainly missing categories from the modal.

**Comment by scruffian** [comment]
Should we include this one? https://github.com/WordPress/gutenberg/issues/47880

**Comment by pamprn09** [comment]
@mtias Is it possible to create custom categories for the Patterns? At the moment all patterns created are shown in "My Patterns".

**Comment by annezazu** [comment]
@pamprn09 Custom pattern categories are not currently possible but are being considered for a future release. [You can read more here](https://github.com/WordPress/gutenberg/pull/51144#issuecomment-1620839856).

**Comment by mtias** [comment]
Closing this milestone.
