### ISSUE TITLE
Allow the registering of search synonyms for Patterns

### ISSUE THREAD

**Issue by ianstewart** [WordPress/gutenberg#38536]
## What problem does this address?

To my knowledge we don't register synonyms or aliases for Patterns and provide it for search in the same we do for Blocks. I expected this search …

![image](https://user-images.githubusercontent.com/545779/152584257-7bd14904-0226-4e60-a3c1-377352e73c48.png)

To reveal this cool patterns …

![image](https://user-images.githubusercontent.com/545779/152584335-ed6e9842-aeba-4713-a675-b90339bead70.png)

Which could also be a portfolio, or list, or feature, etc. May be especially valuable for users as the Pattern Directory grows, and even more valuable if/when synonyms could be localized.

## What is your proposed solution?

Allow listing of aliases for Patterns.

**Comment by mtias** [comment]
I don't think we should support aliases for patterns, instead we should just place them in multiple categories if needed.
