### ISSUE TITLE
Converting a Gallery block to images blocks resets "Image size" and a "Link to" settings

### ISSUE THREAD

**Issue by Socrapop** [WordPress/gutenberg#38544]
### Description

When converting a Gallery block to Image blocks, 
I expect the images to keep the "Link to" and "Image size" previously set in the Gallery Block
but those settings are reset to default on the converted images and sizes are not corresponding to settings.

### Step-by-step reproduction instructions

1. Create a Gallery block and add images
2. On the Gallery block, set the "Images size" to "Medium" and "Link to" to "Media file"
3. You can also set custom images sizes to "full" and "thumbnail" on individual images in the Gallery
4. Select the Gallery block, and transform to "image" blocks
5. The converted images are not linked anymore, and the images sizes are all set to "thumbnail", even if the visible size in the editor are different.

### Screenshots, screen recording, code snippet

![convertinggallerytoblock](https://user-images.githubusercontent.com/16670583/152640233-8c03451e-ce80-4e4e-aa16-dcc66d743978.gif)

### Environment info

Everything is up-to-date: Wordpress 5.9, Gutenberg 12.5.3, Twenty Twenty Two.
Browser : Mozilla Firefox
OS : Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
Thanks for reporting. I was able to replicate this on the latest GB trunk.
