### ISSUE TITLE
Not supporting PHP templates is going to be a nonstarter and deal breaker

### ISSUE THREAD

**Issue by Humanify-nl** [WordPress/gutenberg#38546]
Not supporting PHP templates is going to be a nonstarter and deal breaker
to the vast majority of the community. It’s a big enough deal breaker to
kill off FSE. The migration path without this would be cruel and painful,
and raises the barrier to entry super high.

_Originally posted by @tomjn in https://github.com/WordPress/gutenberg/issues/24313#issuecomment-669355131_

**Comment by tomjn** [comment]
I said that before hybrid universal themes were discussed on the Make blog
and theme shaper.org, this issue doesn’t make much sense in that context

**Comment by tomjn** [comment]
Especially when you can use block.json in a theme with no block templates
and then use a one liner to disable the template editor while still getting
all the goodies

**Comment by Humanify-nl** [comment]
Tom, im deeply sorry / ashamed this happend. I was trying to write an issue about documentation. And I apparently posted this on accident (I was trying to reference your comment , not post it!!). 

Please close / remove
