### ISSUE TITLE
Default Pullquote background overrules theme.json background color

### ISSUE THREAD

**Issue by justintadlock** [WordPress/gutenberg#38545]
### Description

When setting a background color for `core/pullquote` via `theme.json`, it gets overwritten by the high specificity in core's `pullquote/style.css` file.  The color is correct in the editor but gets overruled on the front end.

This is specifically caused by this code: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/pullquote/style.scss#L49-L52

### Step-by-step reproduction instructions

**Step 1:** Add the following to `theme.json`:

```
{
	"styles": {
		"blocks": {
                        "core/pullquote": {
                                "color": {
                                        "background": "#eeeeee"
                                }
			}
		}
	}
}
```

**Step 2:** Add a Pullquote block to a post and save.

**Step 3:** View Pullquote block on the front end and see no background.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by michaelbourne** [comment]
With `.is-style-solid-color` being depreciated, the offending CSS should simply be removed. This is affecting themes that aren't using theme.json as well, even setting a background color in the editor is overridden by this CSS.

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/pullquote/style.scss#L49-L52

**Comment by michaelbourne** [comment]
Fixed in https://github.com/WordPress/gutenberg/commit/0bedb1600aca1bd12c80aa1c374bad6ef2f0b295
