### ISSUE TITLE
How do plugins change the block editor icon?

### ISSUE THREAD

**Issue by carlomanf** [WordPress/gutenberg#38555]
### Description

I want to bundle an image in my (private) plugin, and use it as the icon that shows in the top-left corner of the block editor screen.

There is an [official filter](https://developer.wordpress.org/reference/hooks/get_site_icon_url/) for changing the site icon, but it is not used when resolving the block editor icon. Apparently, the only way to change the default icon is through an attachment post ID, which seems unnecessarily stringent.

Either the existing filter should be used here, or there should be a second filter specifically for the block editor icon.

I would appreciate this to be considered a high priority and considered a bug, not an enhancement. It should always be easy for plugins to disable the default branding.

### Step-by-step reproduction instructions

1. Install a hypothetical plugin that re-brands the admin without inserting new attachment posts
2. Continue to see the default icon in the block editor

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by carlomanf** [comment]
Although I didn't want to do this by setting a site icon through the customiser, I tried it anyway for the time being, and I am finding that I can't even change the block editor icon this way. Nothing I try will change the default icon.

Using core version 5.9 with all plugins deactivated.

**Comment by t-hamano** [comment]
How about using the [rest_index](https://developer.wordpress.org/reference/hooks/rest_index/) hook?

Like this:

```javascript
function register_site_icon_url( $response ) {
	$data                  = $response->data;
	$data['site_icon_url'] = get_theme_file_uri( 'icon.png' );
	$response->set_data( $data );
	return $response;
}
add_filter( 'rest_index', 'register_site_icon_url' );
```

**Comment by carlomanf** [comment]
Thanks for the code, it solves what I want to do. I did come across that hook in my research but couldn't spot how to use it. Still not sure why the customiser didn't work?

**Comment by t-hamano** [comment]
I haven't analyzed it in depth, so I don't know if the lack of functioning of the customizer is a specification or a bug.

I will look into it again if I have time.

**Comment by carlomanf** [comment]
> Although I didn't want to do this by setting a site icon through the customiser, I tried it anyway for the time being, and I am finding that I can't even change the block editor icon this way. Nothing I try will change the default icon.
> 
> Using core version 5.9 with all plugins deactivated.

[Confirmed to work](https://github.com/WordPress/gutenberg/issues/38575#issuecomment-1032366385) with the gutenberg plugin active, but not when inactive.

**Comment by carlomanf** [comment]
> How about using the [rest_index](https://developer.wordpress.org/reference/hooks/rest_index/) hook?
> 
> Like this:
> 
> ```js
> function register_site_icon_url( $response ) {
> 	$data                  = $response->data;
> 	$data['site_icon_url'] = get_theme_file_uri( 'icon.png' );
> 	$response->set_data( $data );
> 	return $response;
> }
> add_filter( 'rest_index', 'register_site_icon_url' );
> ```

I notice that [some code handling the site icon](https://developer.wordpress.org/reference/classes/wp_rest_server/add_site_icon_to_index/) that passes through this filter was only added in core version 5.9, which suggests that the regression might have happened in that version. On the other hand, I can't find anything in [version 5.8.3](https://github.com/WordPress/WordPress/blob/5.8.3/wp-includes/rest-api/class-wp-rest-server.php) to handle the site icon.

Does anyone know whether the icon replacement was ever possible in core, or only with the plugin active?

**Comment by carlomanf** [comment]
It looks like this was fixed by https://github.com/WordPress/wordpress-develop/pull/3157
