### ISSUE TITLE
Integrate media related patterns into the Media Library

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38558]
As work gets increasingly underway to integrate patterns into the creation experience (example: https://github.com/WordPress/gutenberg/issues/38529), the following idea was shared to include various media Patterns as part of the Media Library:

>Actually when you mention it. Patterns can also be linked in with the media library. Adding a pattern could be similar to adding an image. One goes to the media library to find media..:) Images, patterns, audio, etc. Having one consistent experience in dealing with all things media.

This came up as part of feedback for the [FSE Outreach Progam's All Things Media exploration](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2303).

The biggest drawback to this idea is that it could be terribly redundant -- imagine adding a pattern, replacing an image in the pattern by opening your media library, and being faced with similar patterns you just selected from. On the flip side, I could see this being a really neat entry point for patterns. You go to add an image, open your media library, select an image, and perhaps see quick options of what that image might look like in various patterns. Food for thought either way :)

**Comment by annezazu** [comment]
Adding even more good ideas from the exploration as I think it relates: 

> I did have a random tiny thought, what if you could preview different images in a particular pattern? I don’t know what would be good UI for that, but if there was an image in the pattern and you clicked to choose an image, somehow you could see the preview of the image IN that pattern without leaving the modal. That’d be insanely helpful just in general.

**Comment by youknowriad** [comment]
It seems to me that this issue is kind of addressed now that we have both "patterns" and "media" tabs in the inserter. They are consistent now. I'm closing but feel free to reopen if needed.

**Comment by annezazu** [comment]
Ah in this case, the suggestion is about having patterns related to Media available in the Media Library. I do think this experience has improved though and not much traction came from it so I'm okay with it remaining closed.
