### ISSUE TITLE
getPostTypes() does not return Custom Post Types in withSelect anymore

### ISSUE THREAD

**Issue by janwidmer** [WordPress/gutenberg#38563]
### Description

When building a custom gutenberg block with a Select dropdown to be able to select a post type, Custom Post Types are not Contained anymore.

My Site contains a custom post type `news_entry`.
 When using the REST API, I correctly get my custom post type back (See image)

When having the select dropdown in my custom block, I get all other wordpress related post types from the REST API Answer, but not my custom post type `news_entry` and `reference`.

This has been working correctly in Version 5.8.3.

### Step-by-step reproduction instructions

1. Create a custom post type and make sure to enable `supports: editor` and `show_in_rest: true`
2. Create a custom Gutenberg Block with a select element
3. Place the custom block on a page
4. Open the select element, it does not contain the custom post types anymore 

### Screenshots, screen recording, code snippet

Rest API Answer:
![152757239-a3c3ed02-d1ee-41c1-9ca2-80ac6fa5bc2d](https://user-images.githubusercontent.com/3381820/152761280-e0104e02-82de-4ede-b814-2c3b14f86ff2.jpg)

Usage of the React WithSelect:
```
edit: withSelect((select) => { const {getPostTypes} = select('core'); return { types: getPostTypes() }; }
```

### Environment info

- Wordpress 5.9, Gutenberg 12.5.3
- newest Chrome
- Macbook Pro M1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @janwidmer

Have you tried setting `per_page: -1`? See https://github.com/WordPress/gutenberg/issues/15413#issuecomment-581046829.

**Comment by janwidmer** [comment]
Hi @Mamaduka ,
Thanks for the quick reaction. Perfect, with adding that, it works as it should. I guess, with Wordpress 5.9, more Wordpress default Post Types came to the result, therefore I made it over the limit of those 10 without knowing this limit..
