### ISSUE TITLE
Columns block padding is not blanked after added once

### ISSUE THREAD

**Issue by NidhiDhandhukiya** [WordPress/gutenberg#38579]
### Description

In the theme twenty-twenty-two once you add padding to any column then after if you update that padding field blank then it should be not updated as blank.
similarly, we have width option in the column if we add particular width to the column and then if we don't want that width and make that field empty then that should be possible to make changes in that.
(so the issue is we can not make padding empty after adding it once.)

### Step-by-step reproduction instructions

1. select columns in any page or post.
2. choose any column dimention for example 50:50.
3.  apply padding to any column and then update the page.
4. Now remove that padding that you applied and then update your page.
5. So you can see you can not able to remove that padding once you applied it.

### Screenshots, screen recording, code snippet

i attached video for better understanding :- https://www.loom.com/share/92ce92ffcc51470da342bdbaf8a1b170

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Thanks for opening this! It matches a currently open issue so I'm going to close it out: https://github.com/WordPress/gutenberg/issues/36794 Keep reporting what you find though and know it's very appreciated. 

Of note, as mentioned in that issue above, "The value can be reset by clicking the three dots to the right of 'Dimensions' and then selecting the 'Reset All' option."

**Comment by NidhiDhandhukiya** [comment]
okay @annezazu 
Thanks for the update.
