### ISSUE TITLE
Installing Blocks from the Block Library doesn't always work 5.9

### ISSUE THREAD

**Issue by aurooba** [WordPress/gutenberg#38588]
### Description

Hallo! It looks like installing blocks from the Block Library search no longer works in cases that used to work before. But it _does_ work for some blocks. I haven't yet been able to figure out (more research required) what criteria is causing some blocks to fail.

I'm seeing two issues: 

1. Blocks that previously installed without any issues in 5.8.x now show an error registering blocks, here I'm testing with @richtabor's blocks, two don't install anymore, but the Share on Twitter block does:
<img width="351" alt="Screen Shot 2022-02-07 at 8 36 25 AM" src="https://user-images.githubusercontent.com/6925260/152820293-fe89f3cd-5096-4c73-9b40-40d4aa961940.png">

2. My block (which is really two blocks with a parent/child relationship) installs but shows an error. _However_, refreshing the page clears the error. There some conversation around this with @talldan [in Slack](https://wordpress.slack.com/archives/C02QB2JS7/p1643491586584039). The summary of the conversation is that one of the constants is undefined at initial run-time, however it shouldn't be because it has a default set in block.json, so it's still a mystery.

<img width="1157" alt="Screen Shot 2022-02-07 at 8 37 33 AM" src="https://user-images.githubusercontent.com/6925260/152820894-d06172cf-960c-4993-86d2-5ad55449e015.png">

-- 
Some blocks do install, I was able to install @KevinBatdorf's Wavy Divider block with no issue.

### Step-by-step reproduction instructions

1. Install WordPress 5.9
2. Open the Block Editor
3. Open the Block Library
4. Search for `Markdown comment`
5. Try installing Markdown Comment block
6. See the error
--------------------------------
1. Install WordPress 5.9
2. Open the Block Editor
3. Open the Block Library
4. Search for `Super List`
5. Install Super List Block by Aurooba
6. See the error in the Block Editor (and in the console).
7. Save the page/post.
8. Refresh the page and see that the block now asks to attempt recovery, and from then on functions normally.
9. Try adding another `Super List` block to the editor, and see that it works just fine.

### Screenshots, screen recording, code snippet

A quick video demonstration of the problem
https://user-images.githubusercontent.com/6925260/152823160-2ca73403-c4ee-463e-ada7-6b506179d726.mov

### Environment info

- WordPress 5.9, no Gutenberg plugin
- Chrome, Firefox, Safari
- Mac OS Monterey 12.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by KevinBatdorf** [comment]
This is related to https://github.com/WordPress/gutenberg/issues/38494

I got the Wavy Divider block to work by [merging in the block.json file](https://github.com/KevinBatdorf/wavy-divider/blob/main/src/index.js#L8).

**Comment by richtabor** [comment]
Yea, we figured out that the block requires the `title` within registerBlockType function, in order to work right off. I need to update a couple of the other blocks to do this — but I wasn't expected it would be needed.

**Comment by aurooba** [comment]
@richtabor I already had the title in `registerBlockType`, so it's not just the title. Looks like attributes with default values need to be included too.

I did however just test the attributes issue in #38494 and it 100% fixed the problem for Super List. My approach: https://github.com/WordPress/gutenberg/issues/38494#issuecomment-1031651337

**Comment by bph** [comment]
@aurooba @richtabor does this seem to be a documentation issue? 
Maybe @ryelle can help?

**Comment by bph** [comment]
I can definitely reproduce with certain blocks
Error message
![Screen Shot 2022-02-07 at 16 00 28](https://user-images.githubusercontent.com/39980/152871186-7973e601-22dd-4b79-8312-e93c3688cc5b.png)

**Comment by ryelle** [comment]
@bph Thanks for tagging me in. This might be a documentation issue regarding requirements for the wp.org block directory, but I'm not totally sure I understand the issue. It's different from the `title` issue in #38245?

@aurooba, can you explain the attributes issue a little more?

**Comment by aurooba** [comment]
@ryelle 

So in the case of the Super List Block, there is an attribute called `listStyle` which has the default value of `ul` defined in `block.json`. This default value is needed when you first initialize the block (since it's set as a default, the block assumes there's always a value). But because `block.json` doesn't seem to dynamically load, the default value isn't there. This leads to the block showing an error, which resolves itself when you reload the page.

I can just change my approach to always pulling in all `block.json` settings into `index.js`. But I wasn't aware I needed to do that, so if that's the assumption, then we definitely need some clarification in documentation.

**Comment by bph** [comment]
The [documentation for the Block Meta data](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/) and it shows Name as well as Title as required keys. 
I look at tabor/todo-list and it doesn't have a title.  So, it seem that error message is not accurate... 

I then your plugin @richtabor through the **Block Plugin Checker** and it displayed the following error message

> FATAL ERRORS
>   These issues must be fixed before this block can appear in the block directory.
>   
>   Issues found in block.json file.
>   [src/todo-item/block.json](https://plugins.trac.wordpress.org/browser/todo-list-block/trunk/src/todo-item/block.json)[](https://wordpress.org/)[](https://www.facebook.com/WordPress/)[](https://twitter.com/WordPress): block.json[script] At least one of the following properties must be present: script, editorScript

**Comment by ryelle** [comment]
> But because block.json doesn't seem to dynamically load, the default value isn't there.

I see, okay. So this is more-or-less the same root issue as #38245, which is that on a normal page load where the plugin is already active, the block.json is preloaded through some server-side code, and that populates all this info - the title, attributes, etc. When a block is loaded from the block directory, we don't have that server side info, which causes the issue you're having.

There's a suggestion (https://github.com/WordPress/gutenberg/issues/38245#issuecomment-1029932322) of using the data we have from the API request to preload the block metadata, I _think_ that would fix the attributes issue too.

**Comment by bph** [comment]
Thanks @ryelle for jumping in here :-)

**Comment by bph** [comment]
This seems to be a duplicate issue then @ryelle @aurooba and we can close it?

**Comment by aurooba** [comment]
Yes, let's go ahead and close it and I'll jump into the conversation in #38245. Thanks @bph!

**Comment by richtabor** [comment]
> I can just change my approach to always pulling in all block.json settings into index.js. But I wasn't aware I needed to do that, so if that's the assumption, then we definitely need some clarification in documentation.  

If this is the case, then create-block should be updated to do this for you too.

**Comment by aurooba** [comment]
Agreed! Tagging in @gziolo  but I think he's working on making it so we don't have to do this.

Edit: I _know_ he is working on this lol. https://github.com/WordPress/gutenberg/issues/38245#issuecomment-1032610426

**Comment by richtabor** [comment]
✅ I've updated my blocks to use the same method you've done @aurooba. Thanks for leading the charge here :)

**Comment by gziolo** [comment]
> > I can just change my approach to always pulling in all block.json settings into index.js. But I wasn't aware I needed to do that, so if that's the assumption, then we definitely need some clarification in documentation.
> 
> If this is the case, then create-block should be updated to do this for you too.

That's also an option to update create-block. If the block is registered on the server from `block.json` then metadata passed to `registerBlockType` as a first param will use only the `name` and ignore the rest. This is because we need to account for filters applied on the server that could modify block metadata. In general, I still find it confusing even though I authored API changes. It's become a really complex setup with all the extensibility considerations 😅
