### ISSUE TITLE
When appling theme.json, the option wide/full widths dissapears, on TOP LEVEL blocks

### ISSUE THREAD

**Issue by StelaStoykova** [WordPress/gutenberg#38580]
### Description

I am trying theme.json on my website ( running  WP 5.9. ) When I apply it to the theme, the option to set wide/full width on the top level blocks disappears. 

I am using the WordPress block editor without the Gutenberg plugin.

I have tested with default theme - Twenty Twenty-One and the same thing happened. 

This is the theme.json file content I am testing:

` {
	"version": 2,
	"settings": {

    "layout": {
			"contentSize": "960px",
			"wideSize": "1200px"
		},

	}
} `

Even if the theme.json has no settings at all, it still removes the wide/full with options in the block editor

**Expected behaviour:**

 I should be able to set a full width of top level blocks

### Step-by-step reproduction instructions

1. Set the theme to twenty-twenty one
2. Add a cover block
3. Add a theme.json file to the theme
4. The ability to set the width of each of those blocks to wide or full is not there

### Screenshots, screen recording, code snippet

![wide-full-width option-missing](https://user-images.githubusercontent.com/66879657/152800388-ffc54c4a-fac0-45c9-8c48-d3751b4a2614.jpg)

### Environment info

- WordPress 5.9 with Gutenberg block editor
- Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MyWebmasterD** [comment]
I have the same issue running WP 6.0. When adding a theme.json file, the full and wide width options disappear.

Has anybody found a solution to this?

**Comment by mdquer** [comment]
I do have the same issue as described above by @StelaStoykova.  Especially by adding an empty theme.json file full and wide options disappear.

**Comment by MyWebmasterD** [comment]
At the end mine is working, I had to set explicitally content and wide size:
"layout": {
      "contentSize": "1200px",
      "wideSize": "100%"
    }

**Comment by glendaviesnz** [comment]
This seems to be fixed in 6.2:
<img width="811" alt="Screenshot 2023-04-13 at 11 02 14 AM" src="https://user-images.githubusercontent.com/3629020/231604800-7d25f243-bd8c-4bd1-ba0d-10d212a074c6.png">

Closing for now, but feel free to reopen @StelaStoykova if still an issue for you.
