### ISSUE TITLE
Add consistency between AlignmentToolbar and BlockAlignmentToolbar?

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#3859]
## Issue Overview

While applying a new alignment, the alignment functionality differs between `blocks/AlignmentToolbar` and `blocks/BlockAlignmentToolbar`.

## Current Behavior
Main differences:

`blocks/AlignmentToolbar` does this:

```js
onClick: () => onChange( isActive ? null : align ),
```

`blocks/BlockAlignmentToolbar` does this:

```js
function applyOrUnset( align ) {
  return () => onChange( value === align ? undefined : align );
}

onClick: applyOrUnset( control )
```

It is not clear to me why these are different. Is there any possibility of consolidating the two, or do they serve widely separate use cases?

**Comment by youknowriad** [comment]
Agreed, we should probably do the same for both :)

**Comment by BE-Webdesign** [comment]
ColorPalette also shares similarities.
