### ISSUE TITLE
Floating toolbar should be in left white space margin

### ISSUE THREAD

**Issue by ostinatofreak** [WordPress/gutenberg#38592]
In the block editor, the floating horizontal toolbar is constantly covering up what I most recently wrote, which is annoying beyond words.  Achieving "flow" in writing involves constantly re-reading what you just wrote.  This means I'm constantly having to click on the previous paragraph in order to read it.

The floating toolbar should be placed in the left margin (currently unused white space) of the block editor as a vertical toolbar instead of a horizontal toolbar.  Perhaps smartphones don't have this white space (so the current horizontal floating bar would be a life saver for them), but honestly, how many people are writing blog articles using their iPhone?  I would wager that the vast majority of people using the block editor are using a desktop or laptop with a landscape-oriented device.  On such devices, there is a lot of wasted white space in both the left and right margins.

**Comment by bph** [comment]
Hi @ostinatofreak again :-) 
You can use the "TopToolbar" switch to pin the block toolbar to the top. 
Go to the 3-dot menu on the top right and click on "Top Toolbar"
Here is a short video that demos how it works:

https://user-images.githubusercontent.com/39980/152870000-6c369f23-da9f-43e0-a395-85fd7dfdab76.mp4

**Comment by ostinatofreak** [comment]
OK, that's helpful, thanks.  I do think though that it would be worth looking into giving users the option to do a vertical (white space) toolbar vs. a horizontal one that covers up text.  It's nice having the options close to where the mouse pointer already is.  But of course this would be a "luxury" low-priority feature request.  :)  Thanks again for your help.

**Comment by bph** [comment]
@ostinatofreak You are certainly welcome. Glad that it helps you past this initial 'covers my text' I think a vertical toolbar would certainly conflict with the left sidebar and the inserter there. The canvas would lose quite some real estate. 
If that's ok with you, I'll close this issue now.
