### ISSUE TITLE
Word count and estimated time to read

### ISSUE THREAD

**Issue by ostinatofreak** [WordPress/gutenberg#38593]
Sometimes I want to know how long my blog post really is, and I end up copying and pasting the text into Microsoft Word so that I can see word count.

Right now in Wordpress's right-hand column, under the Post tab, to the right of "Author" and "Move to trash" is unused space where Word Count could be added without any down side.  AND/OR in the same place, have an "estimated minutes to read" feature, giving the author the ability to change the base reading rate.  Different bloggers write for different audiences;  a theoretical physicist might use 350 words per minute, while an auto mechanic do-it-yourself blogger might want to use 250.  If it had to be a choice between the two, I'd honestly prefer the "minutes to read" feature over the "word count" feature.

**Comment by bph** [comment]
@ostinatofreak There is a word count in the block editor. It's not easy to discover, if you don't know it's there. 

On top of the editor,  there is a little `i` in a circle that gives you some stats about your current post, including word count. 
![Screen Shot 2022-02-07 at 15 34 30](https://user-images.githubusercontent.com/39980/152867680-7282ae38-aad7-447b-a3f3-4057d79ad764.png)

Would that suffice for now? There isn't a 'minutes to read' stat though.

**Comment by ostinatofreak** [comment]
Oh, I didn't know about that, thanks!  I even tried to be diligent and did a DDG search on "Wordpress word count" and didn't find anything.  But yeah, the "minutes to read" thing would be really cool.  I suppose the most logical place for it to go would be to the right of Words (word count), which would more logically put "Headings, Paragraphs and Blocks" all on one line.  But it might still be worth considering putting "minutes to read" where I originally suggested above just because this is something people might like to check often.
