### ISSUE TITLE
Unmerged tags on pasting from LibreOffice Writer

### ISSUE THREAD

**Issue by EldarAgalarov** [WordPress/gutenberg#38603]
### Description

When I paste formatted text from LibreOffice Writer into Gutenberg Editor and then save page and look at HTML code then i see unmerged tags. For example if sentence marked as bold its HTML markup should looks following:
`<strong>Hello World!</strong>`
But instead it looks following:
`<strong>H</strong><strong>ello</strong> <strong>World!</strong>`
It can be random but issue is common - insted of one merged tag there are multiple tags that can increase size of the HTML code of the page.

### Step-by-step reproduction instructions

I will add steps later if necessary.

### Environment info

Wordpress 5.8.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi,

Thanks for reporting; if you could add any steps or conditions that always trigger this behavior, that would be appreciated; using firefox 97.0.2, Gutenberg 11.7.2, and WordPress 5.9.2; I was unable to reproduce the issue; the text was formatted without the redundant markup tags that you described.

**Comment by EldarAgalarov** [comment]
> Hi,
> 
> Thanks for reporting; if you could add any steps or conditions that always trigger this behavior, that would be appreciated; using firefox 97.0.2, Gutenberg 11.7.2, and WordPress 5.9.2; I was unable to reproduce the issue; the text was formatted without the redundant markup tags that you described.

This is a LibreOffice issue, not a Gutenberg. So you can close this ticket. Thanks.
