### ISSUE TITLE
Group Block Alignment

### ISSUE THREAD

**Issue by kajalmultidots** [WordPress/gutenberg#38608]
### Description

When we select the group and choose the background colour for it then the block alignment changed into left alignment by default, which is not right. It should be stay as a Center alignment.

### Step-by-step reproduction instructions

Go to Group Block
Add some block as a Group
try to choose the background colour
for more information I have attached the video here

### Screenshots, screen recording, code snippet

https://www.loom.com/share/e0f19e9b581e4b4c9c8e40016073f6ca

### Environment info

WordPress version: 5.9
Gutenberg Plugin Version: 12.5.3

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
Thanks for the repot @kajalmultidots — looks like this is a Twenty Twenty Two issue, and is being tracked/worked on here: https://core.trac.wordpress.org/ticket/54944 🎉
