### ISSUE TITLE
Cursor not automatically inside submenu upon creation from parent Nav item

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#38617]
The other part of this is still when we add a submenu item and begin typing, the text goes before the parent item, not jumping the cursor to the submenu item. When I add the submenu item, I expect the cursor to go to that item. When I begin typing, I expect this to be in the submenu item. 

https://user-images.githubusercontent.com/5519705/152904521-c3b3de34-97e0-4e7d-abcc-98729a444262.mp4

Running 6.0-alpha-52690 nightly + Gutenberg Version 12.6.20220207

_Originally posted by @courtneyr-dev in https://github.com/WordPress/gutenberg/issues/36977#issuecomment-1032140062_

**Comment by getdave** [comment]
FYI @tellthemachines

**Comment by courtneyr-dev** [comment]
Just checking in with WP6.0 rc1 retesting this. No change yet where the cursor appears after inserting a child. I would expect the cursor to be in the child menu block. 

![child nav cursor prompt](https://user-images.githubusercontent.com/5519705/167257167-0916efec-3cfd-40d1-92c5-0aa0505c3165.gif)

**Comment by getdave** [comment]
I appreciate that this feels counter intuitive but I believe this follows the same logic as the top level nav items in that you cannot create a nav item simply by typing text.

The action is:

- click inserter to add Nav item
- create link
- then amend the text

When creating a submenu the same pattern applies. So when you click "Submenu" the text cursor remains in the only place available to it given that this is no text box to focus within the submenu.

I think if we want to change this then we'll need to revisit the flow of creating a Navigation so that you add the link _text_ first. But I believe the current flow was an intentional decision.

**Comment by getdave** [comment]
I don't see how we can move this forward. You must insert a block into the submenu to have a cursor within it. Therefore I'm going to close this out.
