### ISSUE TITLE
Search Block: Formatting applied to button text encoded in frontend

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#38644]
### Description

If formatting is applied to the Search block button, it appears as encoded html tags in the frontend.

Reported here https://core.trac.wordpress.org/ticket/55102

### Step-by-step reproduction instructions

- Add a Search block
- Apply 'Bold' formatting to the button text via the block toolbar
- Save post and view in the frontend

### Screenshots, screen recording, code snippet

![search-formatting-bug](https://user-images.githubusercontent.com/3629020/153082315-c25f0a6e-c920-4c32-a624-930f519acda6.gif)

### Environment info

WordPress 5.9, Gutenberg Trunk and TwentyTwentyTwo theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
In the label too by the looks of it:
![Screen Shot 2022-02-09 at 10 01 05 am](https://user-images.githubusercontent.com/677833/153107705-c4219ef2-e656-4b4f-b392-1b0baeab840f.png)

**Comment by Mamaduka** [comment]
This is probably a scaping issue on PHP.
