### ISSUE TITLE
Custom Block: Additional CSS shouldn't be added to the block wrapper 

### ISSUE THREAD

**Issue by erwinyusrizal** [WordPress/gutenberg#38648]
### Description

I have ACF block inside:
```
- rows
---- columns
-------- column
------------- MyACFBlock
```

when I add additional css for example `tailwind class w-1/2` , it's added to my block html which is I expected, but on preview mode, why the additional css added to the MyACFBlock wrapper too? it makes the layout broken, the additional css shouldn't be added to the block parents (see screenshot)

### Step-by-step reproduction instructions

- rows
---- columns
-------- column
------------- MyACFBlock

### Screenshots, screen recording, code snippet

![WhatsApp Image 2022-02-09 at 9 35 22 AM](https://user-images.githubusercontent.com/3752374/153111174-cfbd7187-f49e-45af-b285-cb53b0f9180e.jpeg)

Expected Preview
![Screenshot from 2022-02-09 09-32-01](https://user-images.githubusercontent.com/3752374/153111252-28b91d14-fa84-4784-b6a7-345d79ae11a2.png)

Preview I Got
![Screenshot from 2022-02-09 09-32-31](https://user-images.githubusercontent.com/3752374/153111302-8ba98ad2-0db2-4a29-92c0-82646baefe8d.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@erwinyusrizal This is probably a feature of the ACF blocks. I don't think it's something Gutenberg would do.

I would recommend reaching out to the developer of the ACF plugin as your first option. If they say it's a Gutenberg issue you can always return here.
