### ISSUE TITLE
Link Color: container link color is overwriting child link color on the frontend

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#38646]
### Description

On the frontend, a container's link color overrides the link color of its inner blocks.

Noted here: https://github.com/WordPress/gutenberg/pull/34027#issuecomment-1032160421

I've only noticed this on Block themes.

### Step-by-step reproduction instructions

1. Choose a Block Theme, e.g., TwentyTwentyTwo
2. Insert a Group Block and set the text colors (the link color mainly)
3. Insert a Paragraph Block within your new Group block and set the link color (make sure you include a link in your paragraph) text
4. Publish the post and compare the editor with the frontend.

### What I expected
The link colors to be the same

### What I'm seeing
The container's link color is overriding the inner block's link color on the frontend (not the editor)

#### Editor - Container block (group) text color values

<img width="700" alt="Screen Shot 2022-02-08 at 1 47 57 pm" src="https://user-images.githubusercontent.com/6458278/153099284-3cfd693f-1bc5-4348-97ca-9318aae74809.png">

#### Editor - Child block (paragraph)  text color values

<img width="700" alt="Screen Shot 2022-02-08 at 1 48 05 pm" src="https://user-images.githubusercontent.com/6458278/153099175-798ea2b9-70ec-4575-84ba-605e18be9183.png">

#### Frontend 
<img width="700" alt="Screen Shot 2022-02-08 at 1 48 13 pm" src="https://user-images.githubusercontent.com/6458278/153099177-c812f33f-65b3-474c-88be-48f2c5b2ee8e.png">

### Frontend styles
<img width="700" alt="Screen Shot 2022-02-08 at 1 49 04 pm" src="https://user-images.githubusercontent.com/6458278/153099179-2043aade-edc0-4183-aa58-fb85e74b97d4.png">

### Environment info

- Block Theme, e.g., TwentyTwentyTwo
- WP 5.9
- Gutenberg 12.5 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
Duplicate of https://github.com/WordPress/gutenberg/issues/37582 ?

**Comment by ramonjd** [comment]
> Duplicate of https://github.com/WordPress/gutenberg/issues/37582 ?

Thanks, yes. I swear I searched! :)
