### ISSUE TITLE
Search block icon-only button has no aria-label

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#38647]
### Description

This seems to be an issue in both the front-end and editor. When using a screen reader, the button isn't properly announced when focused.

### Step-by-step reproduction instructions

1. Add a search block
2. Use the icon button option form the toolbar
3. Using a screenreader, focus the button

Expected: The button is announced with default text as the aria label, like 'Submit search'
Actual: It doesn't get announced properly

### Environment info

- Mac OS / Safari / Voiceover
- Latest Gutenberg `trunk`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by alexstine** [comment]
@talldan Looks like this PR will fix this?

https://github.com/WordPress/gutenberg/pull/38136

**Comment by talldan** [comment]
@alexstine Thanks for connecting the dots I hadn't seen that PR. It looks like that PR added a label for the front-end output of the block. 

Do you think we also need the same for the submit button in the editor?

**Comment by alexstine** [comment]
@talldan Yes and I see you have already flagged it in the PR. If no response, I'll make a quick patch. I say quick and I haven't seen the code yet. 🤣

**Comment by tomasztunik** [comment]
This can be closed now, fixes got merged but relation was not tagged correctly.

**Comment by alexstine** [comment]
👍

**Comment by samharp** [comment]
Hello, late to the party - but it appears like this is still an issue (no `aria-label` on Search when selecting the "Icon only" option). I looked at the linked PR, but I couldn't find anything about if this edit was mistakenly walked back.?

**Comment by talldan** [comment]
I just tested and can still see the aria label.

In the editor:
<img width="396" height="35" alt="Image" src="https://github.com/user-attachments/assets/d915f462-f61c-47aa-a48d-eee831a77ef5" />

On the frontend:
<img width="356" height="50" alt="Image" src="https://github.com/user-attachments/assets/b8f1ccab-a2dc-4d03-9be3-be1b929dc4f0" />

**Comment by samharp** [comment]
Thank you for those confirmation screenshots! I'll have to double-check my theme files to make sure it isn't coming from inside the house.
