### ISSUE TITLE
style variations hurt the editing performance

### ISSUE THREAD

**Issue by derridHeidegger** [WordPress/gutenberg#38653]
### Description

i have style variations for different blocks. those are really great but when editing everything becomes slow untill the style variations previews are loaded. if you have the gutentberg plugin enabled, this problem doesn not exists since the previews are loaded only on hover on the style name. is this method is coming to core wordpress? is there a way to close the style variations by default?

### Step-by-step reproduction instructions

1. edit a post or a page
2. select a block that has like 5 to 8 style variations

### Environment info

- wordpress latest, gutenberg latest version

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @derridHeidegger

The new Styles panel design will be part of the WP 6.0 release.
