### ISSUE TITLE
Mobile: Cover block is empty after media is cleared

### ISSUE THREAD

**Issue by mchowning** [WordPress/gutenberg#38674]
## Description
On the mobile apps, after clearing media from a cover block, the block is empty instead of displaying the add media prompt.

## Step-by-step reproduction instructions
1. Add a cover block to a post on WPAndroid or WPiOS
2. Observe that the block has a prompt to Add Image or Video
3. Add media to the cover block
4. Remove the media from the cover block (block options cog -> Clear Media)
5. Observe that the cover block does not have the prompt to Add Image or Video

## Expected behaviour
After clearing media from a cover block, the UI should return to the same state it was in originally (with the Add Image or Video prompt).

## Actual behaviour
After clearing media from a cover block, it is empty.

## Screenshots or screen recording (optional)

| New cover block | After clearing media from a cover block |
| --- | --- |
| ![Screen Shot 2022-02-09 at 11 02 34 AM](https://user-images.githubusercontent.com/4656348/153240037-eb2c06b9-052c-46aa-9f8b-6f61859f4a09.png) |  ![Screen Shot 2022-02-09 at 11 03 35 AM](https://user-images.githubusercontent.com/4656348/153240125-a2de9377-9ba8-44f8-a824-a805e512f72d.png)

 

## WordPress information
Tested on a WordPress.com simple site with the "Blank Canvas" theme selected.

## Device information
- Device: iPhone Xr (14.7.1), Pixel 6 Pro (Android 12)
- WordPress app version: WPiOS test build (19.2.0.20220207), WPAndroid alpha-342

**Comment by geriux** [comment]
> After clearing media from a cover block, the UI should return to the same state it was in originally (with the Add Image or Video prompt).

Cover block contains inner blocks, so it shouldn't go back to the media placeholder when clearing the media once either a media or background was selected. Usually, it's a Paragraph block, but it can contain more than that. As it's in the web editor, if you clear the media you can still see the content of the block.

I recently worked on some Cover changes that changed this to have it consistent with the web editor, but let me know if you think we should revert this.

**Comment by mchowning** [comment]
Thanks for the context. I don't feel strongly at all, it just struck me as odd when I was working on it. I feel like there are better ways to handle this when the inner blocks are empty, but it's an edge case and, as you note, we're consistent with the web so I'll close this.
