### ISSUE TITLE
Global Styles: Setting font size for Paragraph impacts Quote Block

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38686]
### Description

Similar to this prior issue https://github.com/WordPress/gutenberg/issues/37388, if you change the font size in styles for the paragraph block, it impacts the quote block as well. This is likely due to how quotes include `<p>` within: 

`<blockquote class="wp-block-quote"><p>This is the quote</p><cite>And Cite</cite></blockquote>`

### Step-by-step reproduction instructions

1. Open to the site editor
2. Add a paragraph block.
3. Add a quote block with a caption.
4. Open Styles > Blocks > Paragraph > Typography > Change font size.
5. See both change. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/153308150-8278e26c-30ec-4df2-af74-bf55b7a74669.mov

### Environment info

- WordPress 5.9
- Happens with Gutenberg 12.5.4 and without
- MacOS
- TT2 
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by delowardev** [comment]
It's not only the 'Quote' block or 'Typography' settings; All the paragraph styles get applied to the `.editor-styles-wrapper p` selector, which means all `p` tags in the editor/page will get the same style. It's because of the selector (`__experimentalSelector`) for paragraph block is `p` instead of `.wp-block-paragraph` in `block.json`
https://github.com/WordPress/gutenberg/blob/9482dfa2f9d9820fa4177e4f4ece6c4c4c391b79/packages/block-library/src/paragraph/block.json#L54

https://github.com/WordPress/gutenberg/blob/9482dfa2f9d9820fa4177e4f4ece6c4c4c391b79/packages/block-library/src/paragraph/block.json#L35

https://user-images.githubusercontent.com/17360543/153757995-49e92ca5-34ce-486c-b1ec-9e7b32eac9bd.mov

**Comment by tomasztunik** [comment]
We can confirm this is affecting blocks in WooCommerce library as well (and any other) if they use `<p>` element anywhere. 
It also affects editor UI elements like the `Type / to choose a block`.  Also it is not just the font size - it would also affect color, background, font family and other Global Styles controlled styles. 

We believe that Paragraph block is not semantically equal to a `<P>` element and we should avoid using `__experimentalSelector: 'p'`. 

I can assume this was used to optimise paragraph blocks but as we move toward broader Global Styles and Full Site Editing WordPress adoption we should roll back this change or come up with an alternative (higher specificity ie. only direct children).

Also this issue will potentially affect any other core block that is overriding class selectors with element selectors ie. [the List block](https://github.com/WordPress/gutenberg/blob/eaa2e0a91a8ccac43fa2e39f60c37713bff165d7/packages/block-library/src/list/block.json#L62) or [Heading block](https://github.com/WordPress/gutenberg/blob/eaa2e0a91a8ccac43fa2e39f60c37713bff165d7/packages/block-library/src/heading/block.json#L56).

We can see this done in a way that would not affect other usage of these semantic elements in [Code block](https://github.com/WordPress/gutenberg/blob/eaa2e0a91a8ccac43fa2e39f60c37713bff165d7/packages/block-library/src/code/block.json#L18) or [Table block](https://github.com/WordPress/gutenberg/blob/eaa2e0a91a8ccac43fa2e39f60c37713bff165d7/packages/block-library/src/table/block.json#L159).

**Comment by ZebulanStanphill** [comment]
It's worth noting that, once the Quote block v2 becomes stable, Quote blocks will be using nested Paragraph blocks anyway, so it will make sense for the Paragraph font size control to affect the Quotes at that point. Of course, that doesn't solve the general issue.

**Comment by mtias** [comment]
This would be generally expected given paragraphs are represented as a general element.

**Comment by mtias** [comment]
Closing as expected. Quotes now use concrete paragraph blocks in a nested fashion.
