### ISSUE TITLE
Build fails when using @wordpress/scripts v20

### ISSUE THREAD

**Issue by imgerson** [WordPress/gutenberg#38687]
### Description

I found an issue trying to create a new block with this package.

If we roll back to use `@wordpress/scripts` v19 everything works great again.

### Step-by-step reproduction instructions

The build fails when creating a new block with the following command:
```bash
npx @wordpress/create-block stats
```

### Screenshots, screen recording, code snippet

The error looks something like this:
```bash
> wp-scripts build

[webpack-cli] HookWebpackError: Only file and data URLs are supported by the default ESM loader
    at makeWebpackError (/Users/username/github.com/imgerson/awesome-plugin/stats/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/username/github.com/imgerson/awesome-plugin/stats/node_modules/webpack/lib/Compilation.js:3057:12
    at eval (eval at create (/Users/username/github.com/imgerson/awesome-plugin/stats/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:50:1)
    at /Users/username/github.com/imgerson/awesome-plugin/stats/node_modules/webpack/lib/Compilation.js:508:26
    at /Users/username/github.com/imgerson/awesome-plugin/stats/node_modules/copy-webpack-plugin/dist/index.js:708:13
-- inner error --
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:724:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:50:40)
    at link (internal/modules/esm/module_job.js:49:36)
caused by plugins in Compilation.hooks.processAssets
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:724:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:50:40)
    at link (internal/modules/esm/module_job.js:49:36)
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I'm using [volta](https://volta.sh/) as a version control tool for node, and I tried the following three versions.
They all build without any problem on `@wordpress/scripts: v20.0.2`.

- v12.22.10
- v14.18.1
- v16.14.0

Could you tell me what OS and node version you are using?

**Comment by CandaceJohnsonDesigns** [comment]
I have also just experienced this when I used `$ npx @wordpress/create-block` and then `$ npm start` or `$ npm run build`.

Node Version: v14.4.0
OS: MacOS Big Sur 11.6

**Comment by imgerson** [comment]
> I'm using [volta](https://volta.sh/) as a version control tool for node, and I tried the following three versions. They all build without any problem on `@wordpress/scripts: v20.0.2`.
> 
>     * v12.22.10
> 
>     * v14.18.1
> 
>     * v16.14.0
> 
> 
> Could you tell me what OS and node version you are using?

@t-hamano I'm using MacOS Monterrey 12.2.1 and Node v16.14.0.

Something interesting is that I created a GitHub Action in order to rule out it was my system, and yes, everything pass. You can see the [results here](https://github.com/imgerson/codewars-for-wordpress/runs/5164028629?check_suite_focus=true). I wonder what's going on why our systems @CandaceJohnsonDesigns. :)

**Comment by CandaceJohnsonDesigns** [comment]
I solved it by updating Node, now v16.14.0. I don't know why that worked though when you are running that version too, @imgerson.

**Comment by t-hamano** [comment]
I changed the minor version of `node v14` and the major version of `@wordpress/scripts` and tested if it builds correctly.

- OS: Windows 11
- ✅ : The build succeeds.
- ❌ : Got the exact same build error as this issue.

|                           | @wordpress/scripts v19.2.3 | @wordpress/scripts v20.0.2 | @wordpress/scripts v21.0.1 |
| ------------------------- | -------------------------- | -------------------------- | -------------------------- |
| Node v14.0.0 ～ v14.13.0  | ✅                          | ❌                          | ❌                          |
| Node v14.14.0 ～ v14.19.0 | ✅                          | ✅                          | ✅                          |


In @CandaceJohnsonDesigns 's case, it might be due to the low minor version of Node v14.

However, it's strange that `node v16.14.0` can produce both successful and unsuccessful builds.

**Comment by gziolo** [comment]
That’s a bit concerning that you see build errors in some Node.js versions but the good part is that it generally works with the most recent versions for LTE Node.js line. Let’s close this issue for now and reopen if we see newer reports.
