### ISSUE TITLE
Feature request: Display both default duotones and custom duotones

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#38690]
## What problem does this address?

I received a support request asking why the default duotones are not available when you add custom duotones.
That the default duotones are not available when you add custom duotones is the opposite behavior of the color palette and the gradients, where you add a setting in theme.json if you want to hide them.

## What is your proposed solution?

Always display the default duotones unless they are disabled.
Add a new setting to not display the default duotones to theme.json, marching "defaultPalette" and "defaultGradients" booleans.

**Comment by Mamaduka** [comment]
The `defaultDuotone` PR - #38681.
