### ISSUE TITLE
Scroll event doesn't working

### ISSUE THREAD

**Issue by grogou** [WordPress/gutenberg#38692]
### Description

I am trying to create a block and for that I am using the lib, where I need to use some feature  witch fire windows scroll event, so the problem is `window.addEventListener('scroll', function(e){console.log(e)})` on the lib didn't works in editor, on the front end all is good. Is there any suggestion to solve problems like this.

### Step-by-step reproduction instructions

Just add `window.addEventListener('scroll', function(e){console.log(e)})` in console or use it on block editor js,  it is not working.

### Environment info

Wordpress and Gutenberg version is latest for current date.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
How about `document.addEventListener('scroll', function(e){console.log(e)})`?

**Comment by grogou** [comment]
@talldan same issue, nothing happens.

**Comment by grogou** [comment]
After some researches thoughts it can be happens because maybe editor have height : 100% or overflow-x: hidden maybe?

**Comment by t-hamano** [comment]
I also tried it and confirmed that the scroll event was indeed not fired.

However, it worked correctly when I followed [this issue](https://github.com/facebook/react/issues/5042) in the react repository and **specified `true` as the third argument** of the event listener.

In addition, some block editor instances are made up of iframes, so it may be better to register events in relative document objects.

The final sample code looks like this with these considerations.

### edit.js

```javascript
import { useBlockProps } from '@wordpress/block-editor';
import { useEffect, useRef } from '@wordpress/element';

export default function Edit() {
	const ref = useRef();

	useEffect( () => {
		// Get a relative document object from `ref`.
		const { ownerDocument } = ref.current;

		ownerDocument.addEventListener(
			'scroll',
			( event ) => {
				console.log('scrolled !')
				// do something...
			},
			true // This is necessary !
		)
	}, [] );

	return (
		<div  { ...useBlockProps( { ref } ) }>lorem ipsum</div>
	);
}
```


Please give it a try.

**Comment by grogou** [comment]
@t-hamano thank you for example, I will try it, but what about the npm libs where there use window event lisener? Is it that lib problem or ours?

**Comment by t-hamano** [comment]
@grogou 

Does that mean that the npm library itself has a scroll event listener that cannot be controlled from the block?

If that's the case, you may want to try using `create-react-app` or something similar to see if the scroll events work in a pure React environment to isolate the problem.

**Comment by grogou** [comment]
@t-hamano Yes you are right, it is interactive  animation lib and it is created for react I guess, because the documentation tell me about react and vue, I will try that case too and notice you.

**Comment by t-hamano** [comment]
@grogou

The [Make WordPress Core article](https://make.wordpress.org/core/2021/06/29/blocks-in-an-iframed-template-editor/) on how to integrate third-party libraries into blocks may be helpful.

**Comment by grogou** [comment]
@t-hamano thank you very much, you best))

**Comment by grogou** [comment]
@t-hamano after discusstions with lib author, he changed staff you have suggested and it is works for me. Thank you again, and we can close this ticket.
