### ISSUE TITLE
Reusable block keeps wanting to be saved

### ISSUE THREAD

**Issue by endresol** [WordPress/gutenberg#38718]
I have made some reusable blocks and some of them are "changed" just as I open a page that has used them. 
Just as I open the page the Update button is activated and the dot indicating it is a reusable block that needs to be saved appears. 

Any ideas what can cause this? its a site for a client and I have instructed them NOT to save the reuseable blocks...

Thanks

Endre

**Comment by glendaviesnz** [comment]
@endresol I wasn't able to replicate this on WP 5.9 with or without the latest version of Gutenberg plugin installed:

![reusable](https://user-images.githubusercontent.com/3629020/153537093-16fdbed7-8e75-4f86-bda4-577253d35c78.gif)

are you able to provide some details about which versions of WP and GB are being used, and maybe also some details about which blocks are contained within the reusable blocks?

**Comment by endresol** [comment]
Hello. 

I use the latest version of WP, 5.9. I don't have GB installed as a plugin, just the one that is with WP.
The block contains a block from the generatepress team, so it might be where the problem is. Is there any easy way to see the changes on a page before saving?

**Comment by glendaviesnz** [comment]
> I use the latest version of WP, 5.9. I don't have GB installed as a plugin, just the one that is with WP. The block contains a block from the generatepress team, so it might be where the problem is. Is there any easy way to see the changes on a page before saving?

Sorry about the delay in replying, have been AFK. It would be worth trying a new reusable block without the GeneratePress block included just to confirm that the issue only occurs with that block added.

Because the change seems to happen as soon as the block is loaded in the editor, the way to see what the changes are is to examine the raw post content, eg. [via the cli](https://developer.wordpress.org/cli/commands/post/get/), and then open the post in the editor and from the top right menu select `Code editor`, and compare the raw post content there with what you got from the cli.

**Comment by navewi** [comment]
I have the same issue. I'm not using blocks from generatepress but i have some own custom blocks made with Advanced Custom Fields in my reusable blocks. Everytime i open the editor there is this dot that indicates changes, but i have not made any. 

I made a screencast on my test site: 

![reusableBlock](https://user-images.githubusercontent.com/38751963/161943773-d310b813-3896-4c3d-8b68-cb1887f965ae.gif)

Is it possible that any blocks that aren't basic gutenberg blocks are causing this? With reusable blocks that only contain a heading and a text block this is not happening in the same wordpress installation. 

I have the latest versions of wordpress and all other plugins installed. This is also happening if i activate the gutenberg plugin. 

I use my parent theme + child theme. And the following Plugins: Timber, ACF & an own plugin (all three neccessary for the theme to work).

Please feel free to ask for more information or for clarification. 
I have this on a clients site as well so i really would like to fix this issue. Thank you.

This also happens on a wordpress installation where i use the WPML Plugin. There it seems to cause translated resuable blocks to be overwritten with default language content.

**Comment by endresol** [comment]
My issue was with GenerateBlocks. They have now fixed this and the problem is gone so I will close this issue. For those experiencing similar problem, look at the blocks you are using, the problem might be there, as it was in my case.
