### ISSUE TITLE
Scripts: "No entry files discovered in the "src" folder" with `entry` context in `webpack.config.js`

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#38739]
### Description

With 21.0.0 of @wordpress/scripts its no longer possible to use the `entry` context in `webpack.config.js` because the default config now uses an `exit()` call in https://github.com/WordPress/gutenberg/blob/29d123b5d75f9a7362b07263d1b759a3eb327df7/packages/scripts/utils/config.js#L271-L274

That's quite unfortunate and IMO not necessary. The exit should either be removed or first checked if an `entry` setting is set in `webpack.config.js`.

### Step-by-step reproduction instructions

1. Create a custom project with `@wordpress/scripts`
2. Create a `webpack.config.js` with a custom `entry` setting
3. Run `wp-scripts start`

### Screenshots, screen recording, code snippet

Example of a webpack config:

```js
const path = require( 'path' );
const defaultConfig = require( './node_modules/@wordpress/scripts/config/webpack.config' );

module.exports = {
	// https://github.com/WordPress/gutenberg/blob/master/packages/scripts/config/webpack.config.js
	...defaultConfig,

	// https://webpack.js.org/configuration/entry-context/#context
	context: path.resolve( __dirname, 'assets/js/src' ),

	// https://webpack.js.org/configuration/entry-context/#entry
	entry: {
		blocks: './blocks.js', // Entry for multiple block imports.
	},

	// https://webpack.js.org/configuration/output/
	output: {
		...defaultConfig.output,
		path: path.resolve( __dirname, 'assets/js/dist' ),
		filename: '[name].js',
	},
};
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
I have a fix ready for review and testing: #38737.

**Comment by gziolo** [comment]
`@wordpress/scripts@21.0.1` is available with the fix.

**Comment by shivapoudel** [comment]
@gziolo @ocean90 We do have `src` folder for PHP codes how can I get rid of this message. Still persisting in my environment with version `21.0.1`

![image](https://user-images.githubusercontent.com/3774827/153909043-c942e9c9-1245-4347-b55d-06a366560b5a.png)

Why is `getWebpackEntryPoints` called if I extend the config like this with extending `entry`:

```js
/**
 * External dependencies
 */
const path = require( 'path' );
const RtlCssPlugin = require( 'rtlcss-webpack-plugin' );

/**
 * WordPress dependencies
 */
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

module.exports = {
	...defaultConfig,
	context: path.resolve( __dirname, 'client' ),
	entry: {
		index: './index.js',
	},
	output: {
		...defaultConfig.output,
		chunkFilename: 'chunks/[name].js',
	},
	resolve: {
		...defaultConfig.resolve,
		modules: [ path.join( __dirname, 'client' ), 'node_modules' ],
	},
	plugins: [
		...defaultConfig.plugins,
		new RtlCssPlugin( {
			filename: '[name]-rtl.css',
		} ),
	],
};
```

**Comment by shivapoudel** [comment]
@gziolo Can you help me with the ^ comment? Thanks in advance!

**Comment by gziolo** [comment]
> @gziolo Can you help me with the ^ comment? Thanks in advance!

Yes, it still need a fix for your use case. I commented about a potential solution here: https://github.com/WordPress/gutenberg/pull/39618#discussion_r835647250. It’s only a message, your code should work correctly.
