### ISSUE TITLE
`TreeGrid`: write unit tests after recent a11y improvements

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#38735]
Hey folks, I noticed a few great accessibility fixes / improvements on `TreeGrid` recently!

It would be great if we could also add a few unit tests to make sure we don't introduce any regressions around these areas in the future— would that be possible?

_Originally posted by @ciampo in https://github.com/WordPress/gutenberg/issues/38679#issuecomment-1034744487_

**Comment by brookewp** [comment]
The author of the [a11y improvements](https://github.com/WordPress/gutenberg/pull/38679) mentioned here followed up with adding tests for those changes: https://github.com/WordPress/gutenberg/pull/39302. That was merged shortly after, so we can close this. 🎉
