### ISSUE TITLE
templateInsertUpdateSelection doesn't work with nested innerBlocks

### ISSUE THREAD

**Issue by aurooba** [WordPress/gutenberg#38766]
### Description

My plugin Super List Block is has the following set up

- Super List Block (parent container with innerBlock allowing only one kind of block)
  - Super List Item (child block, with innerBlocks that allows you to add as many blocks as you want)
     - default `core/paragraph` block upon insertion

On both `Super List Block` and `Super List Item` I've set `templateInsertUpdateSelection` to be true. My understanding is that by doing so, any innerBlocks inside would then get focussed. This works great for `Super List Block`, the focus is shifted to `Super List Item`, _but_ `Super List Item` also has innerBlocks, and I expected the `core/paragraph` block to be ultimately selected. However, the selected state stops at `Super List Item`.

I'm filing this as a bug, but it may just be something that doesn't (yet) work with nested innerBlocks. I'm also open to another method. I've been trying to do funky things with `selectBlock`, but I haven't found a reliable and performant way to make this happen yet. But the more I think about it, the more I think, `templateInsertUpdateSelection` should be able to handle this.

### Step-by-step reproduction instructions

1. Install [Super List Block](https://wordpress.org/plugins/superlist-block/advanced/)
2. Add Super List, and see that the Super List Item is selected, but not the paragraph inside it.

### Environment info

- WordPress 5.9
- have tested with and without the Gutenberg plugin installed
- Super List Block installed (to see the issue)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
Hi, @aurooba.

I took a look at the code for Super Lost Block, and it might be a typo.

`templateInsertUpdateSelection` -> `templateInsertUpdatesSelection`
(It seems that the "s" after `Update` is missing. )

I'm not sure if this fix will give you the desired behavior, but please give it a try.

**Comment by aurooba** [comment]
@t-hamano ..I cannot believe I missed that. Wowowow. Thank you SO MUCH. You rock. I have been banging my head against a wall for two days.

**Comment by aurooba** [comment]
It still doesn't work on _insertion_ though. Do you think it's _meant_ to @t-hamano? When I insert a new child block (superlist-item) it still doesn't change the focus to the automatically added paragraph. It only does this when you first add the entire _Super List Block_ to the document.

**Comment by t-hamano** [comment]
Hi . @aurooba 
Maybe you also need to `templateInsertUpdateSelection` for the innerBlockProps of the child blocks (`superlist-item`).
(I'm not sure...)

Please give it a try.

**Comment by jordesign** [comment]
Hey @aurooba  did you end up having any luck with this?

**Comment by jordesign** [comment]
With no further movement on this issue - I'll mark it as closed. But if the issue re-arises we can always open it again.

**Comment by montanna** [comment]
Hi @aurooba, did you end up figuring this out? I'm currently having a similar issue with a custom block using InnerBlocks. Mine has a group as a wrapper over the first three child elements so that they'll be displayed in a row. As a result, after setting `templateInsertUpdatesSelection: true`, the containing group ends up being focused rather than the first paragraph tag.

**Comment by t-hamano** [comment]
@montanna 

> Mine has a group as a wrapper over the first three child elements so that they'll be displayed in a row

Are you using the child **elements** rather than child **blocks**? In my understanding, the `templateInsertUpdatesSelection` option only works for the child **blocks**.
