### ISSUE TITLE
"Save as pending" and "Save draft" button labels duplicated when toolbar UI preference is set to show labels

### ISSUE THREAD

**Issue by nekohayo** [WordPress/gutenberg#38773]
### Description

When "Display button labels" is turned on, the toolbar shows "Save as draftSave as draft" or "Save as pendingSave as pending".

### Step-by-step reproduction instructions

1. Go to the post editor
2. Click the three-dots icon in the top-right, go to Preferences
3. Turn on "Display button labels"

### Screenshots, screen recording, code snippet

![Screenshot from 2022-02-13 18-49-36](https://user-images.githubusercontent.com/479401/153781178-601025e6-2940-42a7-b259-c266bab57ae9.png)

### Environment info

- Wordpress 5.9 with its built-in Gutenberg version
- Firefox on Fedora Linux

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
It looks like a regression after #34948.
