### ISSUE TITLE
Code block: default borders overlaps with custom border for code block

### ISSUE THREAD

**Issue by alanjacobmathew** [WordPress/gutenberg#38772]
### Description

When custom border is inserted for code blocks it overlaps with the existing default white border of the code block. This problem exists on the frontend and is not visible inside the editor. 

### Step-by-step reproduction instructions

1 Go to FSE, 
2 Insert a code block
3 Add border with rounded radius (50 px)
4 change the border colour and size  (optional for better visibility) 
5 Publish and view the page.

### Screenshots, screen recording, code snippet

![brave_oDEjvs6iKy](https://user-images.githubusercontent.com/33965848/153762497-91d893b6-351a-4b25-90aa-c907066cbee7.png)

### Environment info

WP 5.9 GB: 12.5.4 TT2
Browser Brave on Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Thanks for the clear, detailed issue. 
This might be resolved by https://github.com/WordPress/gutenberg/pull/38712 ?

**Comment by aaronrobertshaw** [comment]
I can confirm this issue has been resolved. 

Borders apply cleanly to the Code block in both the post & site editors as well as show correctly on the frontend.

<img width="781" alt="Screen Shot 2022-08-10 at 3 49 53 pm" src="https://user-images.githubusercontent.com/60436221/183825749-5efdde91-6e4e-4f66-b9fc-2c2ba8ba6c6c.png">

I'll close this issue however please feel free to re-open it if you disagree.
