### ISSUE TITLE
Site logo button should have a tooltip indicating that it is used to go back to the list of posts, or split into a standalone button

### ISSUE THREAD

**Issue by nekohayo** [WordPress/gutenberg#38789]
### Description

The "W" button in the editor lets you go back to the list of posts, which is nice, but not terribly discoverable. I'm thinking it would benefit from having a tooltip that says "Go back to the list of posts" (or pages, or articles, or whatever the current post type is), while being careful not to cause an odd issue like #38773; though arguably, maybe having this action be in the "W" wordpress logo icon is weird, and maybe that action should be its own "Go back" action button it the toolbar? Just an idea.

### Step-by-step reproduction instructions

1. Hover the mouse over the big "W" logo

### Environment info

- Wordpress 5.9 and its built-in gutenberg
- Latest Firefox on Linux

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for contributing, @nekohayo.

I think this makes sense. A similar logo button in Site Editor has the label.
