### ISSUE TITLE
Block Patterns for page creation.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#38787]
When creating new pages, the user is faced with an empty canvas that can be very hard to work with. We should explore showing a modal as you soon as you add a new page showing the different available block patterns similar to the modal we have when you click "explore" in the block patterns inserter.

Ideally, we'd have ways to mark "patterns" as "full page patterns".

<img width="1332" alt="Screen Shot 2022-02-14 at 3 11 17 PM" src="https://user-images.githubusercontent.com/272444/153880097-aa2f890e-82e3-40be-bbaf-ad8fee29e48e.png">

Also, the question here is what to do with "custom page templates" provided by themes. I think it would be cool to allow the user to pick from these templates as well.

One interesting related question as well is whether these patterns should fill the "post content" of the page, or a new "template" for the current page, or potentially both somehow and how to make that distinction when registering the patterns.

**Comment by jasmussen** [comment]
Not entirely related and needs more work, but [doodled a basic filtering interface here](https://github.com/WordPress/pattern-directory/issues/395#issuecomment-1040021653). [Here's the Figma](https://www.figma.com/file/aPjSgLkhV0qdSWV7mtHMPW/Filtering-Patterns?node-id=0%3A1) in case it can jump start better explorations.

**Comment by jorgefilipecosta** [comment]
> Ideally, we'd have ways to mark "patterns" as "full-page patterns".


I think patterns make most sense as a prefill for the content of a specific page. So it seems creating a page is almost a two-step process:
- 1 Selecting a template for the page. From the page templates the theme makes available.
- 2 Select a pattern to pre-fill the content of the page.

Full-page patterns may make sense in certain cases, for example as a subscribe form, a specific landing page, something very different from the rest of the theme and that does not include any of the theme UI.

I think if we support full-page patterns, we should have the concept of an "empty template" a template that just includes the page content, and when the user selects a full-page pattern we assign the empty template automatically. The pattern would be store as the page content.

But to promote the reusability of templates across pages we should promote the selection of a template.

**Comment by fabiankaegy** [comment]
This is a great enhancement that makes it much less daunting to start creating a new page.

Working with the current implementation from #40034 I noticed that the modal currently only appears to be available for the Page Post Type. I think this would be a great feature to also get support for custom post types. 

It would also be great to have a way to determine which patterns should get shown for which Post type. If I imagine a "Product" custom post type it would be super useful to only show various product-specific patterns that already use product CPT specific blocks in it. 

At the same moment, it would be really valuable to have some programmatic way to opt-in or out of the modal altogether for certain post types.

**Comment by getdave** [comment]
@jorgefilipecosta Is this not now complete? We could/should open a new Issue for @fabiankaegy's ideas.

**Comment by fabiankaegy** [comment]
@getdave i can create a new issue for the follow up feature request 👍

**Comment by fabiankaegy** [comment]
Created a new issue here: https://github.com/WordPress/gutenberg/issues/41304

**Comment by mtias** [comment]
@youknowriad I believe the bulk of this is covered with the post-content patterns?

**Comment by youknowriad** [comment]
Yes, I think @jorgefilipecosta had a PR that should have closed this issue.
