### ISSUE TITLE
Remove duplicate theme docs

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#38795]
## What problem does this address?

With the release of 5.9, theme developer documentation for block themes has been added to the theme developer handbook.
The exception are experimental features like the global style variations that require Gutenberg.

Duplicate content should be removed and the block editor handbook should point to the theme developer handbook.

## What is your proposed solution?

https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/
Remove the current content.
Move the section about global style variations from create-block-theme to this page.

https://developer.wordpress.org/block-editor/how-to-guides/themes/create-block-theme/
-Remove content and add a notice to direct people to the theme developer handbook. Remove the page from the table of content and menu.

https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/
**Question:** I believe this should be added to https://developer.wordpress.org/reference/functions/add_theme_support/, and then this page can add a notice to direct people there, and the page be removed from the toc and menu. But I am not sure how to update that reference page.

-----

https://developer.wordpress.org/block-editor/how-to-guides/themes/create-block-theme/
Replaced by https://developer.wordpress.org/themes/block-themes/ split over seperate pages.

https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/#what-is-the-structure-of-a-block-theme
Replaced by
https://developer.wordpress.org/themes/block-themes/block-theme-setup/#file-structure

https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/#what-is-a-block-template
https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/#how-to-write-and-edit-these-templates
https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/#edit-templates-within-the-appearance-section-of-wp-admin
Replaced by
https://developer.wordpress.org/themes/block-themes/templates-and-template-parts/

https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/#edit-templates-within-the-full-site-editor
Replaced by
https://developer.wordpress.org/themes/block-themes/templates-and-template-parts/
https://developer.wordpress.org/themes/block-themes/creating-new-themes-using-the-site-editor/

https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/#internationalization-i18n
Replaced by
https://developer.wordpress.org/themes/block-themes/internationalization/

https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/#classic-themes
Replaced by
https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#disabling-template-editor

https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/#accessibility
Replaced by
https://developer.wordpress.org/themes/block-themes/accessibility/

**Comment by carolinan** [comment]
@kafleg @TeBenachi @youknowriad @mkaz @oandregal for your thoughts.

**Comment by youknowriad** [comment]
I think we definitely should sort out the duplication.

That said, I really don't like that the documentation lives separately from the code. I guess this is a problem for all WP documentation aside the block editor one and I'd love for the WordPress docs to be "merged" with WordPress (and Gutenberg) that way it evolves hand in hand, there's so many benefits to this approach.

**Comment by TeBenachi** [comment]
I think this is a great idea!  Most of the pages have similar contents so I think it's safe to redirect. 
A few thoughts. 

> https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/ Remove the current content. Move the section about global style variations from create-block-theme to this page.
>
I think [theme.json](https://developer.wordpress.org/themes/advanced-topics/theme-json/)  have the similar content as  [Global style variations](https://developer.wordpress.org/block-editor/how-to-guides/themes/create-block-theme/#theme-json-global-styles). Maybe we should add a notice on [Block Theme on the Block Editor Hanbook](https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/)  to direct people to [Block themes on the Theme Handbook](https://developer.wordpress.org/themes/block-themes/).


> https://developer.wordpress.org/block-editor/how-to-guides/themes/create-block-theme/
Replaced by https://developer.wordpress.org/themes/block-themes/ split over seperate pages.
>
- [What is needed to create a block-theme?](https://developer.wordpress.org/block-editor/how-to-guides/themes/create-block-theme/#what-is-needed-to-create-a-block-theme)  -- Content should be updated to reflect with WordPress 5.9. And I think [Block theme setup.](https://developer.wordpress.org/themes/block-themes/block-theme-setup/)  is a good place to add. 

- [Example themes](https://developer.wordpress.org/block-editor/how-to-guides/themes/create-block-theme/#example-themes)  -- I think [Block themes](https://developer.wordpress.org/themes/block-themes/) page is a good place to add. 


I'm not sure how to redirect or update the references but please let me know if there is anything I can help 🙂

**Comment by carolinan** [comment]
I think the example themes link is a bad idea because these themes are not being updated. There are now more themes in the theme directory that are better examples.

**Comment by kafleg** [comment]
I agree with Carolina that examples themes are not properly maintained.

**Comment by carolinan** [comment]
The [global style variations or presets ](https://developer.wordpress.org/block-editor/how-to-guides/themes/create-block-theme/#global-styles-presets)(unsure, different names are used in different places) require Gutenberg and do not work with only WordPress 5.9, that is why I suggested that they are kept in the block editor handbook.

**Comment by TeBenachi** [comment]
That's explain why it didn't work on my block theme 😄
It makes sense to keep it in the block editor handbook.
