### ISSUE TITLE
Author autocomplete search can fail to return useful results, improve search logic

### ISSUE THREAD

**Issue by claudiulodro** [WordPress/gutenberg#38791]
### Description

Under certain circumstances, the author autocomplete search can fail to return the searched-for author. This is because of the way it's implemented. It uses the REST API author search and then filters those results by author name. Since the REST API author search also searches over the user email field, on sites with a lot of users having the same email domain, those email domain-related results can fill up all of the results in the API response, and the client-side filtering of the search results will say that nothing is found. The steps to reproduce explain this better and why it's an issue.

This issue mainly affects large sites with, for example, a few hundred users with `employe.name@example.com` email addresses and also a catch-all `Example.com` user account for posting things that don't fall under any specific author. The catch-all `Example.com` user account will not show up in the author autocomplete search in this situation (it will display nothing when searching for `Example.com`).

My recommendation would be to exclude email addresses in the REST API search that the author autocomplete uses.

### Step-by-step reproduction instructions

1. Generate 500 users. (`wp user generate --count=500 --role=author`). Give them all an `example.com` email address (`update wp_users set user_email = 'blah@example.com' where user_email = '';`). 

2. Go to the last page of the Users list in WP Admin and edit the 500th user. Change their nickname and display name to `User Example`:

<img width="1506" alt="Screen Shot 2022-02-14 at 10 40 09 AM" src="https://user-images.githubusercontent.com/7317227/153926002-88dda214-1661-4a17-9666-e6375e1039f3.png">
<img width="874" alt="Screen Shot 2022-02-14 at 10 40 30 AM" src="https://user-images.githubusercontent.com/7317227/153926147-1bda6114-1610-4dd0-9e74-4c6b14862a97.png">

3. Go to a post. Open the network inspector. Type in `example` as the author search. Observe that all of the REST API responses are generated users that have `example.com` in the email address, and the actual "User Example" user does not show up in the autocomplete -- in fact nothing shows up in the autocomplete, since none of the 50 users in the REST API response have `Example` in the name (they all have `example` in their email address though).
<img width="871" alt="Screen Shot 2022-02-14 at 10 43 42 AM" src="https://user-images.githubusercontent.com/7317227/153926611-ea76e057-6535-4c65-a4f0-e8da7694803c.png">

4. Type in `user example` as the author search. Observe that the result comes up nicely:

<img width="253" alt="Screen Shot 2022-02-14 at 10 47 31 AM" src="https://user-images.githubusercontent.com/7317227/153927241-3b72c456-0d5b-4036-bd40-9231745e3aa0.png">

### Screenshots, screen recording, code snippet

See steps to reproduce

### Environment info

Tested with WP 5.9, running the version of Gutenberg that shipped with it. Tested with a clean WP site running no additional plugins. Environment was MacBook Pro and Chrome, though that shouldn't affect this issue.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @claudiulodro

Currently, users' REST API endpoint doesn't give us the ability to specify search columns. Filtering this globally via plugin can cause unexpected issues.

I think changing columns via the [`user_search_columns`](https://developer.wordpress.org/reference/hooks/user_search_columns/) filter might be the best option before there's a REST API support.

**Comment by claudiulodro** [comment]
Oh good suggestion. Here's a snippet I created to "fix" the issue in the meantime:

```
/**
 * Don't search user emails in the REST API author search when in editor.
 *
 * @see https://github.com/WordPress/gutenberg/issues/38791
 * @param array $columns User fields to search over.
 * @return array Modified $columns.
 */
add_filter( 'user_search_columns', function( $columns ) {

	if ( ! defined( 'REST_REQUEST' ) || ! REST_REQUEST ) {
		return $columns;
	}

	if ( ! stripos( $_SERVER['HTTP_REFERER'], 'post.php' ) && ! stripos( $_SERVER['HTTP_REFERER'], 'post-new.php' ) ) {
		return $columns;
	}

	if ( 'authors' !== filter_input( INPUT_GET, 'who', FILTER_SANITIZE_STRING ) ) {
		return $columns;
	}

	$email_column = array_search( 'user_email', $columns );
	if ( false !== $email_column ) {
		unset( $columns[ $email_column ] );
	}

	return $columns;
} );

```

Works well so far in my testing. :)

**Comment by Mamaduka** [comment]
Hi, @claudiulodro

I'm going to close the issue. The project developers would be better suited to set the correct `user_search_columns` for their project. The block editor should maintain default behavior.

**Comment by claudiulodro** [comment]
@Mamaduka Who is "the project developers" in this case? This issue documents situations in the **core WP** author search where it fails to return the searched-for author with no plugins or additional code.

**Comment by Mamaduka** [comment]
@claudiulodro - anyone who wants to modify the default WP REST API behavior for user endpoint for their project.

If this is a request to improve the REST API search, the ticket should be opened on Trac - https://core.trac.wordpress.org/.
