### ISSUE TITLE
Group block and Row block borders overlapping on content

### ISSUE THREAD

**Issue by alanjacobmathew** [WordPress/gutenberg#38792]
### Description

Adding borders on group block and row blocks overlap on content

### Step-by-step reproduction instructions

1 Go to FSE,
2 Add a group block, and add a /para block and list block inside the group block
3 Add border to the group block with rounded corners
4 Change the border colour and size (optional for better visibility)
5 Publish and view the page
 

### Screenshots, screen recording, code snippet

![brave_KvWCCkfmKy](https://user-images.githubusercontent.com/33965848/153933118-69175e40-c704-4450-9527-b3d05fd03fcd.png)

### Environment info

WP 5.9  GB: 12.5.4 TT2
WP 5.9 GB: 12.5.4 TT2
Browser Brave on Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Isn't that because there's border radius?

You can add some padding to make sure the the text is fully inside the border.

**Comment by jordesign** [comment]
I'd agree with Dan's comment here - this seems to work as expected, with padding being able to be added as needed to suit.

With no further reports or details in over a year, I'll close this issue.
