### ISSUE TITLE
Image Block: Border settings don't work when cropping/rotating

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38801]
### Description

This came up as part of the [FSE Outreach Program's All Things Media exploration](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2324):

>When cropping or rotate tool is used/active, image border settings won’t work alongside. 

### Step-by-step reproduction instructions

1. Add an image block.
2. Activate the cropping tools.
3. Open block settings sidebar and try to change the radius. Notice you can change things like the block height and scale but not the radius. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/153992344-c3559803-eec5-4f06-9cc3-b2b5d1faac39.mov

### Environment info

- WordPress 5.9
- TT2
- Chrome & Chromium
- Gutenberg 12.5.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aaronrobertshaw** [comment]
Hi @annezazu 👋 

This issue will also be resolved as part of the introduction of more full-featured border support to images in https://github.com/WordPress/gutenberg/pull/31366.

**Comment by annezazu** [comment]
Amazing news! Thanks for connecting the dots.
