### ISSUE TITLE
Site Logo Block causing division by zero notice when image dimensions are not available

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#38807]
### Description

Please note that this is a report coming from Trac, and that `maximus80` deserves the props here.

Copy-paste from Trac:

Notice is
`Warning: Division by zero in wp-includes/blocks/site-logo.php on line 21`

This will happen when the dimensions of the image used inside the site logo block can't be retrieved for some reason. 

Example: SVG image being used. That will lead to the divisors being zero here: https://core.trac.wordpress.org/browser/branches/5.9/src/wp-includes/blocks/site-logo.php#L20

Easiest way to fix would be to replace line 17:
`if ( empty( $attributes['width'] ) || empty( $image ) ) {
`with
`if ( empty( $attributes['width'] ) || empty( $image ) || ! $image[1] || ! $image[2] ) {`

### Step-by-step reproduction instructions

1. Install a plugin to make sure you can upload SVGs to your website
2. Add a Site logo block
3. Use the SVGs
4. See the notice thrown by the block server-side rendering

### Environment info

- WordPress 5.9
- Random plugin to allow SVG uploads

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by maximus80** [comment]
Thanks for porting this over here @audrasjb :+1:
