### ISSUE TITLE
Site Editor: multi selecting blocks causes editor to jump to top

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38803]
### Description

This was found as part of the [FSE Outreach Program's All Things Media Exploration](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2324):

>Selecting few blocks below the fold takes the editor to the top.

This is quite disruptive and jarring, especially if you're simply trying to move a few blocks around. cc @andrewserong since I can see you're working on implementing multi select for List View: https://github.com/WordPress/gutenberg/pull/38314

**Of note: this only happens when using 5.9 alone. It does not happen with Gutenberg 12.5.4**. I checked for PRs related to multi select but couldn't find anything recent that was relevant (this was the only thing I could loosely find that might have been related for 5.9 https://github.com/WordPress/gutenberg/pull/37595). Either way though, it works in the current GB version so whatever fixed it needs to be backported. 

### Step-by-step reproduction instructions

1. Open the site editor
2. Add content so there is some below the editor view and you have to scroll down. 
3. Try to select multiple blocks below the top of the editor.
4. Notice the editor jumps to the top.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/153996864-0111f80d-9d41-41d2-9383-5cc03773700e.mov

### Environment info

- WordPress 5.9
- TT2
- Chrome
- MacOS
- Happens without GB 12.5.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Thanks for the ping, Anne! Unfortunately, from a quick skim through Gutenberg PRs, I couldn't find any recent changes that would obviously affect things, either. But, I also couldn't replicate the issue in 5.9 with Gutenberg deactivated 🤔... I'm testing in WP 5.9, Chrome, MacOS:

https://user-images.githubusercontent.com/14988353/154004788-b54f3f55-7259-4d1f-9786-4801780931ad.mp4

I wonder if there's anything else at play (or that I'm missing in my testing environment)?

**Comment by annezazu** [comment]
How strange! I pulled up a different test site (without Gutenberg) and could still replicate :/

**Comment by fwazeter** [comment]
Bizarre bug, I couldn't replicate it either in chrome or on Firefox (albeit on Ubuntu).

**Comment by alanjacobmathew** [comment]
Retested on Windows 10 with Brave, Firefox and Chromium

When PHP 8.0 was used I was able to replicate it in Chromium and Brave, but not in Firefox
When 8.1 version was used everything was working as expected in all 3 browsers.

In the gif below, the red background is version 8.0 and the white is 8.1

![8 0 vs 8 1 version](https://user-images.githubusercontent.com/33965848/154685328-5fb9356a-8fd0-4fba-a16f-9f47be64fd5a.gif)

**Comment by costdev** [comment]
OS: Windows 10
PHP: 7.4

**Issue reproduced**
- Brave | WordPress 5.9 | TT2 | Gutenberg not active
- Brave | WordPress 5.9 | TT1 Blocks | Gutenberg not active

**Issue not reproduced**
- Chrome | WordPress 5.9 | Gutenberg not active
- Brave | WordPress 5.9 | Gutenberg 12.2.0+ active
- Brave | WordPress 5.8.3 | Gutenberg 12.0.1 active

I haven't tracked down when this was introduced or fixed.

**Comment by Mamaduka** [comment]
I've removed "Backport to WP Minor Release"; we only use this label for PRs.

**Comment by youknowriad** [comment]
I'm not able to reproduce this. Can anyone confirm?

**Comment by annezazu** [comment]
Testing with 6.2 beta 3, I cannot replicate. Closing!
