### ISSUE TITLE
Add filter to `get_block_wrapper_attributes` function

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#38830]
## What problem does this address?

It is currently possible to add custom classnames to static blocks using the `blocks.getSaveContent.extraProps` filter in JS. This is super useful when working with custom block supports. And even core uses this system in js to add the classnames generated for for example the color classes. 

In PHP however for custom blocks this is all hardcoded in the `get_block_wrapper_attributes` function. Specifically inside the WP_Block_Supports Class here: https://github.com/WordPress/WordPress/blob/92f0b0cb48a3de660655cc658fc739695a393096/wp-includes/class-wp-block-supports.php#L93-L128

This approach makes it impossible for custom supports that plugins develop to apply to custom blocks. 

## What is your proposed solution?

This could be solved by adding a new hook in PHP to the `get_block_wrapper_attributes` function which should work the same as the `blocks.getSaveContent.extraProps` hook in js.

**Comment by fabiankaegy** [comment]
@youknowriad I'm curious about your thoughts here. Could this be solved by adding a `register_block_support` function in core that would essentially wrap this here: 

```php
WP_Block_Supports::get_instance()->register(
	'align',
	array(
		'register_attribute' => 'wp_register_alignment_support',
		'apply'                     => 'wp_apply_alignment_support',
	)
);
```

That way we would not need to add an actual filter which might be better for performance and longevity. 

Thanks in advance for your thoughts :) 

Here is how the block alignment support currently works in core. 
https://github.com/WordPress/wordpress-develop/blob/2eed880735c78dd98f18f718dd4e27c560f0b2f7/src/wp-includes/block-supports/align.php#L1-L65

**Comment by fabiankaegy** [comment]
Also since this change will likely need to get implemented upstream in WordPress core itself I have also created a track ticket here: https://core.trac.wordpress.org/ticket/55319

**Comment by youknowriad** [comment]
Hi there! thanks for the issue, `get_block_wrapper_attributes` is not automatically added to all blocks, meaning that even if you have a filter, you'll be relying on whether the block use it or not. Maybe you could just use `render_block` filter like we do in some things here https://github.com/WordPress/gutenberg/blob/39333d427000e3b7dcff16da842a14c109abc844/lib/block-supports/layout.php#L185-L226

**Comment by fabiankaegy** [comment]
@youknowriad whilst that is true, when you are in control of building blocks and want to do something similar to core with the block supports system that is much harder with `render_block` filters than it could be. 

I really appreciate the example of the `render_block` usage in core. 

I still think that it would be a great option to be able to register custom supports that generate custom class names. And I think that the `get_block_wrapper_attributes` is something that any custom block with a render callback that wants to work with any of the core supports needs anyways and therefore that could also be true for custom supports :)

**Comment by youknowriad** [comment]
I understand better. It's already possible to register custom supports that add random classnames and styles.

I think something like:

```php
WP_Block_Supports::get_instance()->register(
	'my-custom-support',
	array(
		'apply'              => function(  $block_type, $block_attributes ) {
                       return array( 'class' => 'my-custom-class' );
                 }
	)
);
```

Is this what you're looking for?

**Comment by fabiankaegy** [comment]
@youknowriad Yes exactly :) And that was the question that I wanted to ask you here: https://github.com/WordPress/gutenberg/issues/38830#issuecomment-1059203855 how you felt about a `register_block_support` function in core to make this a more developer-friendly API.

**Comment by youknowriad** [comment]
To be honest, I don't feel like the current API is not developer friendly but I wouldn't mind a helper function 🤷‍♂️

**Comment by fabiankaegy** [comment]
Thanks for all your input here :) This was super helpful!
