### ISSUE TITLE
Typing custom color names in the FSE color styles settings sidebar is extremely slow

### ISSUE THREAD

**Issue by nekohayo** [WordPress/gutenberg#38833]
### Description

Typing anything in the name fields for colors in the full-site editor is _excruciatingly_ slow, on Firefox on Linux (I didn't test with other browsers). It locks up the UI and types out every character at a rate of maybe 2-3 characters per second.

### Step-by-step reproduction instructions

1. Edit TwentyTwentyTwo's Homepage template
2. In the sidebar, go to "Colors"
3. In the last section, go to "Custom" colors (or custom gradients), choose to add some colors (or custom gradients)
4. Try to type a name for any of them

### Screenshots, screen recording, code snippet

This is the UI I'm talking about:

![super-slow-color-thing-typing](https://user-images.githubusercontent.com/479401/154161327-8b7e0d10-72f1-4173-aad6-8e9db30bd084.png)

This is what it looks like in the web dev console's "performance" tab where, as you can see, it's spamming the browser with so many function calls that the FPS drop from 60 to near zero in an instant:

![Screenshot from 2022-02-15 17-36-30](https://user-images.githubusercontent.com/479401/154161509-8860c362-9faf-41f7-9c1f-f4f89bb66dee.png)

### Environment info

- Wordpress 5.9 with its built-in Gutenberg version
- Firefox on Linux, X11/Xorg
- AMD R7 270 graphics, 8-cores Xeon processor, 24 GB of RAM

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
cc @jorgefilipecosta

**Comment by annezazu** [comment]
I can replicate this with WordPress 5.9.3 and Gutenberg nightly 13.0.20220404 with TT2: 

https://user-images.githubusercontent.com/26996883/161874056-1e1c84b3-eb97-4ab3-b524-3fa4a3265f01.mov

Adding this to the 6.0 board to raise awareness and see what might be going on!

**Comment by glendaviesnz** [comment]
@jorgefilipecosta I had a quick look and it appears to be this [onChange callback](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/palette-edit/index.js#L215) that is causing the issue as every keystroke causes the elements prop to be updated forcing a rerender. Adding a debounce to this call fixes the issue - there may be another option but I ran out of time to investigate further, will take another look tomorrow if someone else doesn't get to it.
