### ISSUE TITLE
HTML tag visible on Search Block

### ISSUE THREAD

**Issue by MartinWolfert** [WordPress/gutenberg#38847]
### Description

Using the Search Block and set the the label above the input field bold type the HTML Tags <strong>Some Input</strong> is visible.

### Step-by-step reproduction instructions

Have a look on the screenshot

### Screenshots, screen recording, code snippet

<img width="1088" alt="Bildschirmfoto 2022-02-16 um 08 53 38" src="https://user-images.githubusercontent.com/12369729/154221059-93e27393-b9c7-4fe2-a54a-38a9fbe59ea5.png">
<img width="1217" alt="Bildschirmfoto 2022-02-16 um 09 02 51" src="https://user-images.githubusercontent.com/12369729/154221477-9c4f3c59-74a8-44ce-a50a-b8bbf7114fb0.png">

### Environment info

WordPress 5.9, German language, Theme: Twenty Twenty-Two, no active plugins. Also Gutenberg is not installed, so I suppose, the bug may be in the Gutenberg core.

Checked with Safari, Chrome and Firefox with macOS Monterrey

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Soean** [comment]
This issue was already fixed in https://github.com/WordPress/gutenberg/pull/38649, it will be released in Gutenberg today in version 12.6 and later in WordPress 5.9.1.
