### ISSUE TITLE
InputControl: Replace `composeStateReducers()` with a standard implementation

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#38845]
There is a quirk in the current implementation of `composeStateReducers()`, in that it requires each reducer to [mutate](https://github.com/WordPress/gutenberg/pull/37164/files#r801084302) the original `state` object. It can cause bugs in the reducer chain if a reducer returns a fresh state object instead.

https://github.com/WordPress/gutenberg/blob/7a3e37a3e0f11e0a05eb2ab36d34427e1c0c5b4f/packages/components/src/input-control/reducer/reducer.ts#L51-L58

This can be confusing for people writing reducers to be composed by this, because it diverges from "standard" reducer-composing functions like `wp.data.compose()` (aka Lodash `flowRight`) or Redux `compose()`.

**Comment by stokesman** [comment]
I've long wanted to suggest `composeStateReducers` should be removed in favor of inline coupling of reducers. There's no instance of composing more than two at a time. Any reducer that allows extension can call the optional extending reducer as part of its process. I've tried such changes but figured it wasn't important enough to make a PR for it.

**Comment by stokesman** [comment]
Here's something that may as well be included in this issue. I found that reducers aren't ordered as I would expect. The order is fine for `NumberControl`:
<pre>input > number</pre>
yet for `UnitControl` it's:
<pre>input > unit > number</pre>
<details>
<summary>If anyone wants to confirm, this is a patch to log reducer order for `LineHeightControl` that should be applicable to trunk (at time of this comment).</summary>

```
diff --git a/packages/block-editor/src/components/line-height-control/index.js b/packages/block-editor/src/components/line-height-control/index.js
index 91c783fe47..0952d9135f 100644
--- a/packages/block-editor/src/components/line-height-control/index.js
+++ b/packages/block-editor/src/components/line-height-control/index.js
@@ -56,6 +56,7 @@ export default function LineHeightControl( {
 	};
 
 	const stateReducer = ( state, action ) => {
+		console.log('line height');
 		// Be careful when changing this — cross-browser behavior of the
 		// `inputType` field in `input` events are inconsistent.
 		// For example, Firefox emits an input event with inputType="insertReplacementText"
diff --git a/packages/components/src/input-control/reducer/reducer.ts b/packages/components/src/input-control/reducer/reducer.ts
index 618cd5a7ca..b3393344fe 100644
--- a/packages/components/src/input-control/reducer/reducer.ts
+++ b/packages/components/src/input-control/reducer/reducer.ts
@@ -73,6 +73,7 @@ function inputControlStateReducer(
 	composedStateReducers: StateReducer
 ): StateReducer {
 	return ( state, action ) => {
+		console.log('input');
 		const nextState = { ...state };
 
 		switch ( action.type ) {
diff --git a/packages/components/src/number-control/index.js b/packages/components/src/number-control/index.js
index 5068715190..2014ae35f0 100644
--- a/packages/components/src/number-control/index.js
+++ b/packages/components/src/number-control/index.js
@@ -62,6 +62,7 @@ export function NumberControl(
 	 * @return {Object} The updated state to apply to InputControl
 	 */
 	const numberControlStateReducer = ( state, action ) => {
+		console.log('number');
 		const { type, payload } = action;
 		const event = payload?.event;
 		const currentValue = state.value;
```
</details>
