### ISSUE TITLE
Cover block: text over image align center center doesn't work

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38869]
### Description

When adding an image block and using the "Add text over image", the option to set to "center center" does not properly work. It remains to the left. This came up as part of the [FSE Outreach Program's All Things Media exploration](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2324): 

>Using post editor, insert an image, click on ‘Add text over image’, centre centre aligns itself as centre left.

### Step-by-step reproduction instructions

1. Add image block.
2. Select "Add text over image".
3. Align it to "Center center". 
4. Notice nothing changes. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/154388521-5d8bb582-0903-4a55-9f5c-d9ae84591107.mov

### Environment info

- WordPress 5.9
- Gutenberg 12.6 (with and without the plugin)
- Chrome
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
👋 - I can see how this can be confusing but the controls actually work as designed, based on the `width` of the innerblocks container of Cover block. You can see that as the `center center` option still keeps the block in the center vertically.

What is the reason for the confusion though is that when we insert a new Cover block, a default template is used with a paragraph that is `center text aligned`. That prop was missing from Image and Video conversions to Cover that I'm adding in the linked PR.
