### ISSUE TITLE
Add helper text to Cover Block's min height field

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38875]
## What problem does this address?

If you add a Cover block and include an embed within it, you cannot make the minimum height smaller than the embed. This makes sense but there's no warning in place to tell you that. This was found as part of the [FSE Outreach Program's All Things Media exploration:](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2324)

>Insert a YouTube video or Imgur image. Click on the outer cover block. Adjusting the height on the cover doesn’t work.

## What is your proposed solution?

The text is terrible :) but just to show an idea -- we could have a similar warning you might see for contrast:

<img width="278" alt="Screen Shot 2022-02-16 at 8 42 13 PM" src="https://user-images.githubusercontent.com/26996883/154406681-22e72456-b7e4-4030-ae5e-42197aa295d2.png">

**Comment by jasmussen** [comment]
Perhaps there's a deeper question on the minimum height control. Technically it's working perfectly as intended: it's the _minimum_ height, and whatever content is inside is free to expand the container beyond that. But of course that isn't necessarily intuitive for most people who might think of it as a plain _height_ control, perhaps especially since the resize handle in the canvas suggests that to be the case.

I seem to vaguely recall @kjellr mentioning some issues related to height vs. min-height in context of Cover. I wonder if we should explore converting this to just _height_ 🤔

**Comment by ntsekouras** [comment]
>Technically it's working perfectly as intended: it's the minimum height, and whatever content is inside is free to expand the container beyond that

I agree with that and I don't think we can swap this with `height`. It will create a tons of issues and confusion since everything is responsive and will create scrollbars, might cause issues with the `fullscreen` toggle, etc...

Maybe what we need here is a `help` text explaining a bit what `min-height` is?

**Comment by annezazu** [comment]
Ohh a brief description might help. I still am strangely partial to having a warning of sorts to save the sidebar from getting even longer but that might be difficult to intelligently implement.

**Comment by justintadlock** [comment]
> I wonder if we should explore converting this to just height

Mostly just reiterating what @ntsekouras said.  That seems like a recipe for a lot of broken use cases currently in the wild and would fundamentally change how the Cover block works.  Fixed heights also rarely make sense in web design given that content needs to adjust to the screen size.  Maybe there should be helper text or a link that explains what min-height is.

**Comment by annezazu** [comment]
Updated the title of this issue to make the intent clearer :)

**Comment by rkg4412** [comment]
I am interested in contributing .... can you tell me what to do and how to do ????? @annezazu

**Comment by ntsekouras** [comment]
👋 @rkg4412 ! Thanks so much! You can see the contributor guide [here](https://developer.wordpress.org/block-editor/contributors/).

The actual change would be [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/cover/edit.js#L140) by using this existing `help` property of [BaseControl](https://developer.wordpress.org/block-editor/reference-guides/components/base-control/#help).

**Comment by loganwisniewski** [comment]
Hi there, I am a first time contributor and saw this was a Good First Issue and still Open. I'd like to use this task as an opportunity to get familiar with the Git workflow required to contribute. I appreciate the contributor guide posted above and plan to contribute this by no later than tomorrow if it's, indeed, alright that I use this task as my first contribution.

**Comment by loganwisniewski** [comment]
I just opened a PR ([here](https://github.com/WordPress/gutenberg/pull/40361)). Please let me know if I did any thing wrong or if I could improve upon anything.

**Comment by loganwisniewski** [comment]
My pull request had some failed tests. The failed tests don't appear to be related to my file change. Is there something I may have done wrong [here](https://github.com/WordPress/gutenberg/pull/40361)?

**Comment by jasmussen** [comment]
Thanks, @loganwisniewski for the PR! Code looks good and the test failures look unrelated, I've restarted them.

I want to voice a general concern with the help text as discussed, specifically that it gives _weight_ to the minimum height feature. Width and min-height controls is something I'd love to see come to more container blocks, including the Group block ([see also](#25973)). Especially for stack and row blocks that feature vertical alignment controls, it will be useful. As those controls expand, they naturally belong together, like so:

<img width="364" alt="group" src="https://user-images.githubusercontent.com/1204802/163528352-f667a7a1-398c-4e30-9d63-bdf45939df24.png">

With several lines of help text, this will not be possible. And ultimately, I still don't think it's needed, as "minimum" implies it already. I would love if we could seek alternatives, for example tooltips:
<img width="271" alt="Screenshot 2022-04-15 at 08 05 59" src="https://user-images.githubusercontent.com/1204802/163528563-5c13cd87-baa4-498e-9383-1c5059b03a1f.png">

**Comment by loganwisniewski** [comment]
Since "Minimum Height" is fairly self explanatory and as @jasmussen mentioned 

> And ultimately, I still don't think it's needed, as "minimum" implies it already.

 is there even a need for any sort of helper text? Perhaps this task should be closed?

**Comment by annezazu** [comment]
I'm game to close this out and can re-open if further feedback comes in. I do think that the minimum height option, when placed with other tools, will become clearer as well. Currently, having it as a one off dimension control _might_ be part of what's making a helper text feel advantageous.
