### ISSUE TITLE
Twenty Thirteen: Table color not reflect on the frontpage

### ISSUE THREAD

**Issue by umeshgupt** [WordPress/gutenberg#38879]
### Description

Twenty Thirteen: Table color not reflect on the frontpage

### Step-by-step reproduction instructions

    1.Switch theme to Twenty Thirteen
    2.Create Table and change color after update
    3.Check the frontpage

### Screenshots, screen recording, code snippet

Add the video Link below:
[https://www.loom.com/share/6ce4c74eb3314d7bb593b0e7173e637b](url)

### Environment info

Version: WordPress 5.9
Browser: Chrome

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
I couldn't reproduce this, the colors for the table were changing as expected on the front page as shown in the short video below:

https://user-images.githubusercontent.com/41231764/190623592-b0d676a3-290a-4a35-9bae-33fad1afe177.mov

I am going to close this issue for now. 

WordPress 6.0.1 
Gutenberg 14.1.0
Twenty Thirteen theme
