### ISSUE TITLE
Image Block: set to 100% but image changes size after selecting the 100% option

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38874]
### Description

After adding an image, it is set to 100% but if you select the 100% the size of the image changes. This only happens in the Post Editor but that might be due to some breakage in the site editor (https://github.com/WordPress/gutenberg/issues/38557). This was found as part of the [FSE Outreach Program's All Things Media exploration:](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2324)

>The default dimension is highlighted as 100% but in-fact if clicking on 100% again usually modifies the image size on the editor. It is a bit confusing

_Feel free to update this title - struggled to find a concise way to explain this_

### Step-by-step reproduction instructions

1. Add a new post.
2. Add an image block.
3. Notice the image dimension is set to 100%. 
4. Select the 100% option and notice the image changes size.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/154404537-85c4ec68-37b7-4ade-945b-712f04dce90f.mov

### Environment info

- WordPress 5.9
- Gutenberg 12.6 (with and without)
- Chrome
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
I think this might be a duplicate of #38381, which also has some good conversation. Specifically it seems like an editor-only issue that is related to the ResizableBox component.

The video here is excellent though, if you agree it's the same issue maybe it's worth copying the video over to the other thread?

**Comment by annezazu** [comment]
Ah ha! I managed to not find that issue in my search. On it and closing this out.
