### ISSUE TITLE
Uploading new image to Image block causes image to be inserted twice

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3889]
## Issue Overview
After adding a new image block, I clicked _Insert from Media Library_ and then uploaded a new image. After clicking _Select_ in the popup window to insert the image into the block, the image then appeared twice in my page. It appeared below the existing Paragraph block, where I actually inserted the image block and it also appeared above the Paragraph block.

![gutenberg-insertimage](https://user-images.githubusercontent.com/2078245/33793279-f5115746-dd08-11e7-960a-c3191bb498f9.png)

## Steps to Reproduce (for bugs)
1. Add new image block (I inserted mine below a paragraph block)
2. Click _Insert from Media Library_ and drag 'n drop a new image into the popup window to upload it
3. Select the image and click _Select_ to insert it into the block

## Expected Behavior
I would expect the image to only be inserted in the location where I added my Image block. It should only be inserted once, not multiple times.

## Current Behavior
Adds multiple images into the page, in various locations

_Firefox Quantum 57.0.1 (64-bit)
Gutenberg 1.8.1_

**Comment by Lewiscowles1986** [comment]
I Just tried this and although it seems to have a problem with me using my SVG upload plugin, I still only get a single image.

Tested on Firefox for Ubuntu 
![image](https://user-images.githubusercontent.com/2605791/33803801-3f59b460-dd90-11e7-8303-8af4a4192dc8.png)

![screenshot-single-image-upload-gutenberg](https://user-images.githubusercontent.com/2605791/33803831-d82e5010-dd90-11e7-868e-3ca23c89e653.png)

**Comment by danielbachhuber** [comment]
Hi @maddisondesigns,

Does this issue still reproduce for you? If so, can you try deactivating all of your plugins and then activating them one by one to see if it's a plugin causing the problem?

**Comment by Lewiscowles1986** [comment]
Hi @danielbachhuber it does not in Chrome, sorry for not sticking with it.

**Comment by danielbachhuber** [comment]
👌 Thanks for letting us know!

**Comment by maddisondesigns** [comment]
@danielbachhuber I just tried this again multiple times and the same thing occured at least once. The only plugins that I had activated were Gutenberg, ACF Pro and WooCommerce.

I then tried after deactivating ACF Pro and WooCommerce and wasn't able to replicate. Also tried after just reactivating ACF Pro and WooCommerce individually, and wasn't able to replicate. This seems to be a very random issue, but an issue all the same. I'll leave it up to you as to whether you want to reopen this.

Also, in future, if you specifically ask the person who raised the issue a question, can you please not close the issue based on someone elses answer. I've never used the SVG upload plugin that @Lewiscowles1986 mentioned, so my initial issue obviously didn't have anything to do with that plugin. Thanks

**Comment by Lewiscowles1986** [comment]
My bad, I thought it was my issue and suggested closing because I didn't want any more emails :worried:

**Comment by danielbachhuber** [comment]
> I then tried after deactivating ACF Pro and WooCommerce and wasn't able to replicate. Also tried after just reactivating ACF Pro and WooCommerce individually, and wasn't able to replicate. This seems to be a very random issue, but an issue all the same. I'll leave it up to you as to whether you want to reopen this, but there's obviously an issue there.

If you can provide exact reproduction steps, happy to look at it further. Without reproduction steps, it's much more difficult to track down the issue.

> Regardless of whether there were plugins activated at the time or not, this sort of thing shouldn't be happening.

I agree.

> It's up to Gutenberg to work with all/majority of existing major plugins. 

This is a pretty strong statement. Gutenberg will try its best to work with existing plugins (see some work I'm doing in https://github.com/WordPress/gutenberg/issues/4072), but it'd be impossible for us to guarantee.

> Also, in future, if you specifically ask the person who raised the issue a question, can you please not close the issue based on someone elses answer.

Yep, no problem. This was my fault.

**Comment by maddisondesigns** [comment]
@danielbachhuber The exact reproduction steps are outlined in the original issue. It didn't take much to cause this issue. All I tried to do was insert an image.

- Add new image block (I inserted mine below a paragraph block)
- Click Insert from Media Library and drag 'n drop a new image into the popup window to upload it
- Select the image and click Select to insert it into the block

Like a lot of Gutenberg issues, it doesn't happen all the time because Gutenberg is so unstable and inconsistent. I fully understand how hard trying to debug inconsistent issues like this are, but they can't be ignored. I dread to think how frustrated the average user is going to feel when they experience inconsistencies like this.

It's understandable that certain plugins wont work, or may need to be updated by the developer (eg. plugins specifically related to TinyMCE), but Gutenberg needs to work with the majority of plugins and more specifically, major plugins like ACF, Yoast, WooCommerce etc... It's not good enough to say that there's no guarantee that they will work. Considering Gutenberg still doesn't even work properly, and there's little to no documentation for developers, how can you expect developers to update their plugins before it's even released? And they shouldn't have to. By not supporting the majority of plugins and at the very least, major plugins that I mentioned above, you are going to cause hundreds of thousands of sites to break once this gets released. This is one of the main reasons why the majority of developers want to see this get released as a (working) plugin first, rather than just getting forced into core.
