### ISSUE TITLE
Typography settings are inconsistent and make editing slower and more confusing

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#38904]
### Description

When you first see the Typography settings, you're shown the Size selector by default, along with a `View and add options` Plus (+) icon.

<img width="393" alt="screenshot_165" src="https://user-images.githubusercontent.com/2078245/154640506-dd9a6388-62dc-42d3-8a8b-3354c51a384e.png">

After clicking the plus icon and adding a new option such as Letter case, the icon then changes to the 3-Dots `View options` icon.

<img width="421" alt="screenshot_166" src="https://user-images.githubusercontent.com/2078245/154640885-429277a3-e400-42a3-9175-ccbdeb9d4fac.png">

This is confusing. Why does it not continue to show the Plus icon, to indicate that you can add more options? If you're going to change what icon is displayed, then it should only change to the 3-Dots icon once there's no more options that can be added.

An even better solution would be to revert back to the old typography selection tools where everything is shown by default. Having to manually "add" an option like Line Height or Letter Spacing, before you can actually use it, is needlessly confusing and complicated in an already difficult to use editor, and makes editing content even slower. On top of that, you have to add these options on every single block that you want to use them on. They don't even default to being shown on other blocks within the same page. You're making content editing significantly more difficult and considerably slower with these UI changes. Why do you insist on hiding all these options under multiple layers of menus, icons, dropdowns, popups and toggles?

>- Hidden navigation is less discoverable than visible or partially visible navigation.
When navigation is hidden, users are less likely to use navigation.
If people use hidden navigation, they do so later in the task than if it were visible.
>- Hidden navigation provides a worse user experience than visible or partially visible navigation does, in both mobile phones and desktop user interfaces. This finding holds true across multiple UX metrics including users’ assessment of task difficulty, time spent on task, and task success.
>- On desktops, hiding navigation degrades the experience and the navigation discoverability more than it does on the phones.

Nielsen Norman Group
[Hamburger Menus and Hidden Navigation Hurt UX Metrics](https://www.nngroup.com/articles/hamburger-menus/)

### Step-by-step reproduction instructions

- Add a Paragraph block
- Change the Typography settings

### Screenshots, screen recording, code snippet

See screenshots above

### Environment info

WP 5.9
Twenty Twenty One
Firefox 97.0
macOS 12.1
No Gutenberg plugin, core only

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Sisanu** [comment]
Additionally, the letter-spacing cannot be controlled globally, if it relies on hardcoded values, and this generates inline styles for each of the occurrences. In my opinion, the letter-spacing should be controlled from the settings defined in the theme.json, just like the font size does.

**Comment by Thelmachido** [comment]
@maddisondesigns With the recent version, you will not see the plus icon isn't shown anymore. For these settings you will continue to see the 3-dots `components button` to view more options as shown below: 

https://user-images.githubusercontent.com/41231764/190625812-8e4aef2e-038d-4289-aa24-b33fef1e83b4.mov

I think this is more consistent and will avoid confusion, I will close this issue for now. 

WordPress 6.0.1 
Gutenberg 14.1.0
Twenty Twenty Two theme 

> Additionally, the letter-spacing cannot be controlled globally, if it relies on hardcoded values, and this generates inline styles for each of the occurrences. In my opinion, the letter-spacing should be controlled from the settings defined in the theme.json, just like the font size does.

@Sisanu Sounds like a suggestion about where letter spacing should be controlled. Can you please add this to a different new issue so that it can be properly tracked there?

**Comment by maddisondesigns** [comment]
@Thelmachido It's still a horribly designed and implemented UI. As I said in my original post, having to manually "add" an option like Line Height or Letter Spacing, before you can actually use it, is needlessly confusing and complicated and makes editing considerably slower. I've seen very few modern UI's that are worse than Gutenberg, with your constant need to hide every option beneath multiple layers of menus, icons and popups.
