### ISSUE TITLE
Color settings don't work properly

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#38903]
### Description

The (text) color settings on the Code Block don't do anything. Only the background color settings do something.

https://user-images.githubusercontent.com/2078245/154637165-847176f6-d8f8-4fb8-b77c-0fb1f5499b40.mp4

The new color selection tools are also worse to use than the previous ones. The new color selection tools take up considerably more vertical space, in what is already a very limited area. There's also no indication that you can actually click on that top color swatch, to select a custom color. To a new user, it looks like you only have the choice of the ten (round) colour swatches. The old color selection tools at least had a `Custom color` link, indicating that you can select a custom color. Whilst showing the hex color code in the swatch is a great addition, the size of the swatch causes these new color selection tools to take up way too much room in the sidebar.

### Step-by-step reproduction instructions

- Add Code Block
- Change Text Color
- See nothing happen

### Screenshots, screen recording, code snippet

See video above

### Environment info

WP 5.9
Twenty Twenty One
Firefox 97.0
macOS 12.1
No Gutenberg plugin, core only

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @maddisondesigns.

The problem of code block text color not being reflected has been resolved by the code block style refactoring in this PR #38712.

Please activate the Gutenberg plugin and see if the problem reappears.

**Comment by maddisondesigns** [comment]
Hi @t-hamano 

Yep, I can confirm that the latest Gutenberg plugin fixes the issue with changing the text color.

One other thing that is also changed though, is that there's no longer a `Clear` button to reset the color back to what it was 

Before:
<img width="1377" alt="screenshot_867" src="https://user-images.githubusercontent.com/2078245/156499320-cbd77c60-aab2-4bf2-bd07-38517fccec04.png">


After:
<img width="1388" alt="screenshot_865" src="https://user-images.githubusercontent.com/2078245/156499188-076b8e5c-5095-4a20-ab98-6d06055441ba.png">


Yes, after playing around, I finally realised that you can click the colour again to 'unselect' it, but that's nowhere near as intuitive as having a `Clear` button to reset the color. Also, what do you click if you've set a custom colour or gradient? There's no way to clear it unless you click one of the preset colours to remove the custom colour and change it back to one of the default colours, and then click it yet again to unselect the default colour. That's a really horrible UX.

**Comment by t-hamano** [comment]
> One other thing that is also changed though, is that there's no longer a Clear button to reset the color back to what it was

The problem with the clear button not showing up sould have been solved on #37791, but I can reproduce on my enviroment too.

So I updated my issue #37093, please see.

**Comment by t-hamano** [comment]
The problem with the text color not being reflected on code block has been solved, so I'll close this issue.

If you have any problem, please reopen or create new issue.
