### ISSUE TITLE
Add a filter to allow custom alignment settings

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#38912]
## What problem does this address?

Many layouts require a wider range of preset widths for elements than just narrow, wide and full. This will allow such layouts to be easier to achieve, by providing plugin or theme developers the means to specify additional alignment settings.

## What is your proposed solution?

Add a filter to the `supports` array, so that custom alignments (e.g. `alignxwide` or `alignmedium`) can be defined by the theme or plugin developer. These should ideally be reflected by outputting the appropriate CSS class names, which can then be defined in the theme/plugin CSS.

**Comment by markhowellsmead** [comment]
Any progress on this?

**Comment by markhowellsmead** [comment]
Any progress on this? @talldan?

**Comment by skorasaurus** [comment]
There's a bit of discussion about this at https://github.com/WordPress/gutenberg/issues/27629 ; does that fulfill what you're looking for (And if so, could we close the issue ?)

**Comment by markhowellsmead** [comment]
That issue is for the same functionality we’re trying to achieve.

**Comment by JiveDig** [comment]
+1
