### ISSUE TITLE
Schema: theme.json allows to set styles.blocks.*.spacing.blockGap

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#38929]
### Description

I was trying to set a default block gap styling via theme.json but that didn't work.

Example:

```
{
	"$schema": "https://schemas.wp.org/wp/5.9/theme.json",
	"version": 2,
	"styles": {
		"spacing": {
			"blockGap": "20px"
		},
		"blocks": {
			"core/navigation": {
				"spacing": {
					"blockGap": "8px"
				}
			}
		}
	}
}
```

Turns out that [this isn't supported](https://github.com/WordPress/wordpress-develop/blob/109953c1fbf8afeb227eae12466770620d8b1bc1/src/wp-includes/class-wp-theme-json.php#L475-L484). Another related comment: https://github.com/WordPress/gutenberg/pull/37360#issuecomment-1036283388

It would be nice if the schema could be adjusted to show an error if the `blockGap` property is set for block styles.

### Step-by-step reproduction instructions

1. Extend the theme.json from Twenty-Twenty Two with the example from above
2. Notice that the block gap is not used, neither in the settings panel nor in the CSS output on frontend.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mrleemon** [comment]
So, one cannot set a blockGap value in the styles section if blockGap is not enabled in the settings section? A theme developer would want to set a default blockGap but not let theme users change it.

**Comment by skorasaurus** [comment]
> So, one cannot set a blockGap value in the styles section if blockGap is not enabled in the settings section? A theme developer would want to set a default blockGap but not let theme users change it.

UPDATE: 

You can set a BlockGap value but prevent theme users from changing it by [following this example](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#what-is-blockgap-and-how-can-i-use-it): 
but instead 
set the blockGap value to false;

**Comment by skorasaurus** [comment]
Since this issue was made; blockGap on a per block basis was implemented In https://github.com/WordPress/gutenberg/pull/40875 

If you're having specific issue with the navigation block; please create a new issue.
