### ISSUE TITLE
Set custom size icon on Typography tools doesn't display tooltip

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#38931]
### Description

There's no tooltip displayed when you hover over the _Set custom size_ icon so there's no indication what the icon actually does.

https://user-images.githubusercontent.com/2078245/154830559-28445be1-1b0c-421d-9d32-163cf33cb93f.mp4

### Step-by-step reproduction instructions

- Click on a paragraph block
- Hover cursor over Set custom size icon
- No tooltip displays

### Environment info

WP 5.9
Twenty Twenty One
Firefox 97.0.1
macOS 12.1
No Gutenberg plugin, core only

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@ntsekouras, do you remember the reason why tooltips are currently hidden?

https://github.com/WordPress/gutenberg/blob/19d505a4f60fa717fbfa092323fc35090b905d60/packages/components/src/font-size-picker/index.js#L147

**Comment by ntsekouras** [comment]
>@ntsekouras, do you remember the reason why tooltips are currently hidden?

I can't think of any reason and especially since I was handling the message conditionally. Must have missed it 😄 . Opened a quick fix here: https://github.com/WordPress/gutenberg/pull/38985
