### ISSUE TITLE
Update documentation for theme.json

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#38935]
The current documentation for [Global Settings & Styles (theme.json)](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/) is a bit out of date.

It should get updated to include all the changes as announced in [the related dev note for WordPress 5.9](https://make.wordpress.org/core/2022/01/08/updates-for-settings-styles-and-theme-json/). I think all the examples should also be updated to use version 2.

**Comment by annezazu** [comment]
Noting that this has come up in the documentation team too :) https://github.com/WordPress/Documentation-Issue-Tracker/issues/87

**Comment by zutigrm** [comment]
Hi,
I went through the article and updated the referenced page for `theme.json` doc. Here is the pull request - #https://github.com/WordPress/gutenberg/pull/40005
