### ISSUE TITLE
Incorrect URL in block Metadata documentation

### ISSUE THREAD

**Issue by sanzeeb3** [WordPress/gutenberg#38940]
### Description

In the https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#icon

> Custom SVG icons are automatically wrapped in the [wp.primitives.SVG](https://developer.wordpress.org/block-editor/designers-developers/developers/packages/packages-primitives/src/svg/) component to add accessibility attributes (aria-hidden, role, and focusable).

The link for wp.primitives.SVG leads to a page not found.

### Step-by-step reproduction instructions

1) Go to the URL: https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#icon
2) Click on wp.primitives.SVG

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sanzeeb3** [comment]
Hi @ocean90 - this is a little bit different issue and I'm not sure what the correct URL would be unlike the PR #38941

**Comment by sanzeeb3** [comment]
@ntsekouras can we reopen this? It's incorrectly linked to PR which doesn't fix this particular issue.

**Comment by mburridge** [comment]
This issue was reviewed in today's Documentation Bug Scrub. We have been unable to replicate it. The link appears to work as expected. Therefore, I am going to close this issue. Please feel free to reopen this issue with additional information.

**Comment by SavPhill** [comment]
The link works, but worth noting the end url is different to the link. 'reference-guide' becomes 'reference-guides'. It is in fact redirected.

The link points to: https://developer.wordpress.org/block-editor/reference-guide/packages/packages-primitives

The final url in the address-bar is:

https://developer.wordpress.org/block-editor/reference-guides/packages/packages-primitives

**Comment by mburridge** [comment]
That part of the URL isn't in the source file, there's only a relative path - see [here](https://github.com/WordPress/gutenberg/blob/20c8e375bbd128df210ff01923b6e4f17fad9fb3/docs/reference-guides/block-api/block-metadata.md?plain=1#L258). I guess the redirect is happening at the `reference-guide`/`reference-guides` level.
