### ISSUE TITLE
render_block filter, attrs is empty

### ISSUE THREAD

**Issue by MarieComet** [WordPress/gutenberg#38943]
### Description

I'm using render_block filter on core/button block, and attributes is empty.

Example with :
```
add_filter( 'render_block', 'better_a11y_filter_blocks_render', 10, 2 );
function better_a11y_filter_blocks_render( $block_content, $block ) {
    error_log(print_r($block, true));
    return $block_content;
}
```
I expect to get block attributes as declared in block.json (url, text, linkTarget, etc.) but error_log give me an empty array for `attrs` : 
```
Array
(
    [blockName] => core/button
    [attrs] => Array
        (
        )

    [innerBlocks] => Array
        (
        )

    [innerHTML] => 
<div class="wp-block-button"><a class="wp-block-button__link" href="http://wp.lndo.site/wp-admin/" target="_blank" rel="noreferrer noopener">Coucou</a></div>

    [innerContent] => Array
        (
            [0] => 
<div class="wp-block-button"><a class="wp-block-button__link" href="http://wp.lndo.site/wp-admin/" target="_blank" rel="noreferrer noopener">Coucou</a></div>

        )
)
```
Am I missing something ?

### Step-by-step reproduction instructions

1. Paste this code in functions.php or a test plugin : 
```
add_filter( 'render_block', 'better_a11y_filter_blocks_render', 10, 2 );
function better_a11y_filter_blocks_render( $block_content, $block ) {
    error_log(print_r($block, true));
    return $block_content;
}
```

2. Edit a page or a post, insert a block button, visit the page and check your error.log

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
👋 @MarieComet 

>I expect to get block attributes as declared in block.json

`attrs` contain the current specific block attributes with their set values, if any. For example in your case if you added `width` to your button, your log would contain this attribute and its value.

In order to get the declared attributes for a block, you have to fetch the block type like this:

>$block_type = WP_Block_Type_Registry::get_instance()->get_registered( $block['blockName'] );
>var_dump( $block_type->attributes );

**Comment by MarieComet** [comment]
@ntsekouras thanks for your response.
`$block_type = WP_Block_Type_Registry::get_instance()->get_registered( $block['blockName'] );` give me declared attributes, but I'm looking for the attributes values defined for the current block (I'm in the `render_block` filter).
I don't understand why I can get `width` in `$attrs` but can't get `url`, `text`, etc.

**Comment by ntsekouras** [comment]
Ah... Okay. Some attributes depending on their source can be extracted/serialized by the js parser and this is the case for the `Button` [attributes](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/button/block.json#L12) you're referring to. Check `"source": "attribute",` etc..

**Comment by MarieComet** [comment]
I'm not sure to understand, but I'm in PHP, not JS to use the parser.

**Comment by ntsekouras** [comment]
>but I'm in PHP, not JS to use the parser.

Yes, so I think you should manually parse to extract some attributes like that. I don't believe there is some util or something in `core` code, but not 100% sure.

**Comment by MarieComet** [comment]
Yes, that's what I'm doing, parsing block content.
Thanks for your response.
