### ISSUE TITLE
Hyperlink popover partly disappears behind wp-admin sidebar

### ISSUE THREAD

**Issue by pwkip** [WordPress/gutenberg#38957]
### Description

When you highlight some text in a paragraph block, if the highlighted text is near the left side of the editor, the popover to enter the URL will be partly hidden by the left sidebar.

### Step-by-step reproduction instructions

1. Create a new post or page.
2. Make sure you resize the window so that the left edge of the editor container is close to the left sidebar. (Don't make it too narrow, because than the sider will switch to mobile view)
3. Type the word _test_ in a paragraph
4. Highlight the word _test_
5. Click the hyperlink icon
6. Observe that part of the popover disappears behind the sidebar

### Screenshots, screen recording, code snippet

<img width="533" alt="image" src="https://user-images.githubusercontent.com/1150196/154959651-5b91ac86-5f5c-47a1-b4d8-a5c27be80fcd.png">

### Environment info

This behaviour was observed both with Gutenberg plugin enabled and disabled.
- WP 5.9
- Gutenberg 12.6.0

Tested on:
- Browsers: Chrome 98 and Firefox
- OS: MacOS Big Sur and Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting this. There's an existing issue (https://github.com/WordPress/gutenberg/issues/38723), so I'll close this as a duplicate.
