### ISSUE TITLE
Image block won'tallow wide width and left justfication

### ISSUE THREAD

**Issue by LogicalHighs** [WordPress/gutenberg#38965]
### Description

I have been battling this one for a couple of weeks with no success. I have searched this forum and the internet in general with no luck.

When I set the group to wide width and want to text wrap around an image, the image will not go to the left side of the wide width setting, it stops at the default width and leaves empty space beside the picture.

### Step-by-step reproduction instructions

Select the group and set to wide width

Add an image block and insert a picture

Add a paragraph block and add text

Select the picture and use wide width OR left justify, but it won't allow both

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Thanks for opening this is issue! It seems like it's likely a duplicate of this: https://github.com/WordPress/gutenberg/issues/38802

Can you confirm? If so, I'll close this out :)

**Comment by LogicalHighs** [comment]
This is not a duplicate of that issue. The controls are there, but do not allow selection of both wide and left justification.

Chuck

**Comment by ndiego** [comment]
Hi @LogicalHighs, can you let me know which theme you are using? While the Editor does not allow you to select both "Wide" and "Align Left" on the Image block, you still should be able to accomplish the design you are looking for.  

I was able to accomplish this in the Twenty Twenty-Two theme. The steps I followed were:

1. Add a Group block and made sure "Inherit default layout" was not enabled. 
2. Set the Group block to align "Wide".
3. Added an Image block and then a Paragraph block with some content. 
4. Set the Image block to "Align Left".

Here is a screenshot with the result. 

![image](https://user-images.githubusercontent.com/4832319/155735056-d5ef0ce3-59db-4d20-986e-c3967967079f.png)

**Comment by LogicalHighs** [comment]
Hello Nick,
   I am using the twenty twenty one theme. It looks like did exactly what I am trying to do. Where do you turn off inherit default layout?

Chuck

**Comment by ndiego** [comment]
Hi Chuck, with the Group block selected, the setting is located in the sidebar. See the screenshot below. 

![image](https://user-images.githubusercontent.com/4832319/155737839-090e48eb-4a86-4cc1-8d97-d389de0cb46a.png)

**Comment by LogicalHighs** [comment]
Hello Nick,
	I do not have layout as a choice in the side bar. My Wordpress versions 5.9.1 and  I am using Twenty Twenty-One version 1.5 with the Twentig plugin. I deactivated the plugin to see if layout would come up, but that did not help either. I know this should simple, but it is fighting me hard. 

Thanks,
Chuck

**Comment by annezazu** [comment]
@LogicalHighs here's a quick video walking through the steps Nick provided above in case it helps :)


https://user-images.githubusercontent.com/26996883/156034810-fe34e82d-ff9d-4882-a887-14838b88ab3e.mov

**Comment by LogicalHighs** [comment]
I would say to just close the issue. I don’t know what else to say in it and no one has a solution.

Chuck

**Comment by adamwoodnz** [comment]
@LogicalHighs I managed to get something working similar to what you're after using Columns in Twenty Twenty-One:

![Screen Shot 2022-05-31 at 3 27 46 PM](https://user-images.githubusercontent.com/1017872/171087199-920e535e-6dc9-4f5c-ab7d-c2391921fdb5.png)

Hope this helps. If not please ask for more help in the [forums](https://wordpress.org/support/welcome/).

**Comment by LogicalHighs** [comment]
Thank you for the help. That will not allow text wrap to function. I did find a work around, I went to the site settings and made the text width and the wide width the same number. That forced the context to meet the wide width and the text wrap to look proper. If I need a page that will be more narrow, it will cause more issues, but at this point I don’t expect that to be an issue.

Chuck
