### ISSUE TITLE
Invalid block validation after save.

### ISSUE THREAD

**Issue by grogou** [WordPress/gutenberg#38978]
### Description

I am creating new block for me and after page save when I reload editor I get attempt block recovery.

When I click to resolve get this.

![image](https://user-images.githubusercontent.com/10712881/155113185-b7ce9e40-2bfd-4121-82a6-4cb9ec42335c.png)

Same thing on both sides.

### Step-by-step reproduction instructions

...

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aurooba** [comment]
Double check that your save function is saving things correctly. :)

**Comment by grogou** [comment]
@aurooba it is my `save.js` is there anything wrong?

```js
import {useBlockProps} from "@wordpress/block-editor";
import {Fragment} from "@wordpress/element";

export default ({attributes}) => {

    const {
        id,
        mode,
        url,
        link,
        link_external
    } = attributes;

    const renderBlock = () => {
        return (
            <Fragment>
                <lottie-player
                    id={id}
                    mode={mode}
                    src={url}
                />
            </Fragment>
        );
    }

    return (
        <div {...useBlockProps.save()}>
            <div className={'xp-lottie-wrapper'} data-attributes={JSON.stringify(attributes)}>
                {link &&
                    <a href={link} target={link_external ? '_blank' : '_self'}>
                        {renderBlock()}
                    </a>
                }
                {!link && renderBlock()}
            </div>
        </div>
    )
};
```

**Comment by talldan** [comment]
@grogou There should be more information about the problem in the browser console. Would you be able to share the console messages? Thanks.

**Comment by grogou** [comment]
@talldan the only message is validation error.
![image](https://user-images.githubusercontent.com/10712881/155478346-e79cde9c-0818-497b-9887-e24866ba60f6.png)

**Comment by grogou** [comment]
@talldan but when link attribute is not set, it works correctly, I just need to understand how this validation works, because resolve show me no conflict or something wrong.

**Comment by talldan** [comment]
> The only message is validation error

Yep, this is the information you need to figure out why your block is invalid.

It shows what was saved to post content at the bottom.

Invalid blocks happen when the block editor tries to take your block in the post content and parse it. It'll find (or source) each of the attribute values in that HTML. To test that it did that correctly it calls your save function again with those attributes it found in the HTML, and if everything worked correctly the output should be identical to what was saved in the post content.

In your case though it was different, the output when the block editor tried to parse your block and call save to test it is shown at the top of the error message.

There are two things that can cause the problem.
1) A non-deterministic save function. `save` should produce the same HTML every time if it's called with the same `attributes`.
2) The attributes couldn't be sourced from the HTML in the post content.

It's a bit hard to tell what your issue is, but it's probably the second issue. Can you share you attribute definitions?

**Comment by grogou** [comment]
@talldan yes sure.
```js
"attributes": {
    "id": {
      "type": "string",
      "default": "none"
    },
    "url": {
      "type": "string",
      "source": "attribute",
      "selector": "lottie-player",
      "attribute": "src"
    },
    "mode": {
      "type": "string",
      "default": "chain"
    },
    "state": {
      "type": "string",
      "default": "loop"
    },
    "type": {
      "type": "string",
      "default": "seek"
    },
    "count": {
      "type": "number",
      "default": 0
    },
    "speed": {
      "type": "number",
      "default": 1
    },
    "delay": {
      "type": "number",
      "default": 0
    },
    "visibility_start": {
      "type": "number",
      "default": 0
    },
    "visibility_end": {
      "type": "number",
      "default": 100
    },
    "visibility_start_single": {
      "type": "number",
      "default": 0
    },
    "loop_after_scroll": {
      "type": "boolean",
      "default": false
    },
    "link": {
      "type": "string",
      "default": ""
    },
    "link_external": {
      "type": "boolean",
      "default": false
    }
  },
```

**Comment by grogou** [comment]
Attempt block recovery happens only once, when I insert block and save it, after reload I get recovery, after recovery and save the next reloads render block correctly.

**Comment by grogou** [comment]
This is case when link attribute is not set, but when I set link attribute, recovery comes for every reload.

**Comment by grogou** [comment]
@talldan is there a way to debug validation process.

**Comment by grogou** [comment]
@taldan problem solved.

After save idk why in db I found this
![image](https://user-images.githubusercontent.com/10712881/155515775-8e7856e2-886c-4a82-af88-385cdf2e7183.png)

It is generated by someone idk how adn why xd.
So I added it to my save function and problem solved.
Thank you all for help

**Comment by talldan** [comment]
I'm glad you solved it. It looks like this might be related to the issue #39051 that was just created.
