### ISSUE TITLE
Theme Customizer Site Identity Widget Conflict

### ISSUE THREAD

**Issue by rielyncampbell** [WordPress/gutenberg#39001]
$wp_customize->remove_section( 'title_tagline'); 

This hides the Site Identity section of the customizer as I'd expect but it also breaks the widget menu in the customizer for the twenty twenty theme.  Haven't tested other themes.

With this code in place and Twenty Twenty theme installed, go to the theme customizer, click on widgets and either footer.  The block editor doesn't appear like it's supposed to.

![Screen Shot 2022-02-22 at 5 16 11 PM](https://user-images.githubusercontent.com/18360227/155229246-3ef12346-4866-40d3-9f68-8cb56f8188a3.png)

**Comment by Thelmachido** [comment]
I am not quite sure which code can be used to hide the site identity in Customiser, however, at the moment the code provided `$wp_customize->remove_section( 'title_tagline');` is breaking the site. I used the code snippet plugin to add the code, let me know if I am missing something. 

What I experienced can be seen below:

https://user-images.githubusercontent.com/41231764/190167112-be12e734-9c84-4d1a-a7d1-110d643f597e.mov

WordPress 6.0.2
Gutenberg 14.0.3
Twenty Twenty theme 

I will close this issue, for now, please feel free to re-open and add more information @rielyncampbell
