### ISSUE TITLE
Select multiple blocks on the List View

### ISSUE THREAD

**Issue by felipevelzani** [WordPress/gutenberg#39006]
## What problem does this address?

You are not able to select multiple blocks on the List View mode, so you need to select the blocks directly on the content editor if you want to select multiple blocks.

## What is your proposed solution?

Bring the option to select directly on the List View by using Shift or something like that.

**Comment by glendaviesnz** [comment]
Thanks for taking the time to suggest this. A [PR for this was merged 5 days ago](https://github.com/WordPress/gutenberg/pull/38314), so it should be available in the next release of the plugin.
