### ISSUE TITLE
Site Editor: undo/redo causes screen to jump

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#39000]
### Description

Undo/redo in the Site editor causes the editor to jump up in some situations when content is below the fold. This was found as part of the [FSE Outreach Program's All Things Media exploration.](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2346)

### Step-by-step reproduction instructions

1. Open site editor.
2. Add a header and a paragraph block below the fold above the footer.
3. Make minor changes (bold, italics, etc).
4. Hit undo and notice the editor jumps up higher each time you do.

### Screenshots, screen recording, code snippet

Here's a video from me replicating the problem: 
https://user-images.githubusercontent.com/26996883/155221788-91743f30-736c-45ce-98e4-18c65722792d.mov

Here's the originally reported video demonstrating the issue: https://app.koofr.net/links/481d3053-4fd1-4756-60ef-5db5b25d0ed2

>I tried to recreate the undo/redo issue on php 7.4, 8.0 and 8.1 with 5.9
8.1(peach background) 00:02
8.0(blue ) 00:40
7.4(green) 01:15
>Make sure the header block is active.
Have content longer than the fold.

>When GB inactive
>On 8.1 : Inconsistancy undo/redo
>On 8.0 : Block jump when applying undo/redo
>7.4 : Same as 8.0

>With GB active
>8.1 : No more issue with undo/redo
>8.0 and 7.4 Same issues, when GB is inactive

### Environment info

- WordPress 5.9.
- Happens with Gutenberg deactivated and with Gutenberg 12.6 activated. 
- MacOS
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by quakeboy** [comment]
This is ruining the writing experience. Is there a way you guys could add test cases to avoid such editor bugs?

**Comment by glendaviesnz** [comment]
I am not able to replicate this on trunk, are you still seeing it @annezazu ?

https://github.com/WordPress/gutenberg/assets/3629020/01535269-7dfe-40dd-b0fa-b59a6855372c

**Comment by annezazu** [comment]
It seems improved with 15.8.1!

https://github.com/WordPress/gutenberg/assets/26996883/466c8e92-663d-482d-991f-ec6845f2bb08

 If you can't replicate with trunk though, I'm curious what improved this experience so we can ensure it sticks :)

**Comment by annezazu** [comment]
Closing this out as I can no longer replicate with 16.1.
