### ISSUE TITLE
Global styles override block level element styles when in Editor

### ISSUE THREAD

**Issue by tomasztunik** [WordPress/gutenberg#39010]
### Description

If we have global styles applied for block color `text` and `link` and then provide local block style overrides by changing the color of the `link` the global styles take higher precedence because of css selector higher specificity and override local styles. 

Styles for block level selectors work fine, just element level styles fail to be resolved proeprly.

This is related to other styles (reset, global styles etc.) being prefixed with `.editor-styles-wrapper` class and I've found these changes started being introduced around [March 2021](https://github.com/WordPress/gutenberg/pull/30038/files) and persist until now ([1](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/layouts/utils.js), [2](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/hooks/duotone.js#L284), [3](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/editor-styles/index.js#L71) etc.)

Element level block styles do not have the prefixed class present causing element level style to be overwritten by global styles if present.

Possibly related to https://github.com/WordPress/gutenberg/issues/37262

### Step-by-step reproduction instructions

1. Go to `Site Editor`.
2. Edit `Global Styles` for `Paragraph` block - set custom color for text and link.
3. Add new `Page`.
4. Create a `Paragraph` - it should have global styles applied.
5. Create new `Paragraph` and edit its color styles using different text and link color.

- 🚫  Link color will be ignored when in Editor (Front-End works ok)
- ✅  Text color overrides correctly 

### Screenshots, screen recording, code snippet

![Screenshot 2022-02-23 at 09 56 57](https://user-images.githubusercontent.com/112270/155287859-c602842d-e700-49ac-8240-4e44a274e928.jpg)

### Environment info

- WordPress 5.9.1, Gutenberg 12.6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by davewhitley** [comment]
I believe this related issue is still a problem 

https://github.com/WordPress/gutenberg/issues/53801
