### ISSUE TITLE
The "Apply duotone filter" button jumps to the end after changing image alignment

### ISSUE THREAD

**Issue by pansamolot** [WordPress/gutenberg#39011]
### Description

When you paste or upload new image, the "Apply duotone filter" button is first in the row of buttons in a corresponding image's toolbar. When you change image alignment, it "jumps" to the end all buttons and becomes last in this toolbar.

_I have a weird feeling that I've already reported this and even more weird that it was already fixed, so it might be a kind of regression. But I can't locate the other ticket_.

### Step-by-step reproduction instructions

**Steps to reproduce**:

1. Paste any image. Observe that the "Apply duotone filter" button is first in a row
2. Click the "Change alignment" button and change image's alignment to i.e. center

**Expected behavior**: The "Apply duotone filter" button remains where it was.

**Actual behavior**: The "Apply duotone filter" button shifts back to the last position in toolbar.

### Screenshots, screen recording, code snippet

![duotone-button](https://user-images.githubusercontent.com/60975060/155290128-2128aecd-3257-48b1-b3a9-3e705cf8320b.gif)

### Environment info

- WordPress 5.9.1, Gutenberg 12.6.0, WR-Elite 1.6
- Microsoft Edge 98.0.1108.56 (64-bit)
- Microsoft Windows 10 Pro 10.0.19042 Build 19042

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment]
I can replicate this! Thanks for opening. cc @ajlende -- wonder what changed here?

**Comment by jasmussen** [comment]
This is mentioned in #31373, but as it has turned out this hasn't been a simple fix, nor the task of removing duotone from the setup state. I wonder if we should rename 31373 to be about removing duotone from the placeholder, and keep this one as a task to keep the duotone button placement consistent?

**Comment by pansamolot** [comment]
@jasmussen Thanks for mentioning #31373 because thanks to that I've managed to find my old report (#32981). I still however don't understand how GitHub failed to find that issue when searching for "Apply duotone" and caused me to create duplicate.

We keep opening new tickets and community here keeps closing them as duplicates of #31373, but the fact is that nothing is actually happening in that "master" ticket. I understand that the problem is complex. I understand that the issue is very low (just  a glitch in the toolbar), but still -- we are near 10th month since #31373 was reported by you. And it seems that not many things are happening to it.

Plus, I was always told that we should work agile, splitting tasks, bugs and problem to minimum portions, so rising a ticket like "Duotone enhancements" (#31373) to deal with many issues + many additional bugs seems a mistake. And maybe this is the key reason why this issue isn't still resolved.

So, yeah, go ahead. You can close current ticket as another duplicate of #31373 (as you did with #32981). That's your decision. I'd however suggest resolving bugs and issues one-by-one instead of grouping them into never-ending "big" tickets.

**Comment by jasmussen** [comment]
You misread me, actually I think we should keep this ticket open as more actionable than the other.

This is still a priority, but there are only so many hours in the day, and at the moment focus is on some more critical duotone bugs we need to address for 5.9.1. Outside of any volunteer PRs addressing the issue, we'll have to come back to the issue when bandwidth opens up.

**Comment by Mamaduka** [comment]
This is a general problem with SlotFills and will be fixed once we have a solution for https://github.com/WordPress/gutenberg/issues/15641.

I think we can close this. The issue can't be fixed separately.
