### ISSUE TITLE
Contributors not showing in the Author box on 5.9

### ISSUE THREAD

**Issue by adnanwk** [WordPress/gutenberg#39035]
### Description

All users must be displayed in Author box in new post, but only those who have publishing rights are being displayed.

I have updated my multi-author website twice on 5.9 from 5.8

On the first attempt, I was running php 7.3, upgraded to wp 5.9
On the second attempts after a month, I switched to php 7.4, upgraded to wp 5.9.1

In both attempts, in the author list (author box) of new post, I can see only those users who have publishing right. Contributors are missing from the list.
On the users tab of the dashboard, I can see all users.

I have cleared the cache, and rebooted the machine.

### Step-by-step reproduction instructions

Upgrade to wp 5.9 or 5.9.1 from 5.8
using php 7.3 or 7.4

Create new post in a multi-author website
In the author dropdown combo, see if contributors are being displayed or not. In my case, they are missing.

### Environment info

WP 5.9.1, Classic Editor.
Windows 10
Chrome/Brave/Opera/FireFox browsers

I have made some special user categories (Sub Editors with or without Publishing rights using User Role Editor by [Vladimir Garagulya]). I have tried upgrade with this plugin enabled and disabled. In both cases the result is the same.

Theme: Color Mag Pro.
Site Language: RTL (Urdu).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by CucumberKid** [comment]
I have exactly the same issue. When I try to change the author in the admin view, I only see the system administrators (those who have permission to publish) and not my other 350 users who have various use rights including editing. This is following an upgrade from 5.8 to 5.9.1. I have tried disabling all the plug-ins and the error still persists.  Downgrading to 5.8 using WP Downgrade resolved the problem.

**Comment by adnanwk** [comment]
Isn't it a bug? It is not request for a feature. A functionality that is working uptil version 5.8 is broken in 5.9.x

**Comment by adnanwk** [comment]
Is there any update on this? Is any one else facing this issue?

**Comment by adnanwk** [comment]
@grappler 
I am using the Classic Editor. I am not using GutenBerg.

**Comment by grappler** [comment]
@adnanwk Then this would be the wrong place to report the issue. The best place to get help would be https://wordpress.org/support/forum/how-to-and-troubleshooting/

Once the issue can be reproduced, then it may make sense to open a [trac ticket](https://core.trac.wordpress.org/).

You need to check that the Contributor have the `edit_posts` capability for them to be shown in the authors list.

**Comment by priethor** [comment]
Closing this as it's not an actionable Gutenberg issue.
