### ISSUE TITLE
Add preview link to snackbar notice when saving a draft

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#39037]
## What problem does this address?
When saving a draft, I can't easily view a preview of the post from the snackbar notice — it just says "Draft saved." Instead, I have to use the control within the editor header "Preview" dropdown. 

## What is your proposed solution?
When a post is a draft, add a "View Preview" link within the existing "Draft saved" snackbar notice. That way publishers may quickly opt to view a draft preview the same way they would view published changes. Adding a preview link to the snackbar would add a useful action to the snackbar. 

## Screenshots
 
Current snackbar notice, when saving a draft post: 
<img width="150" alt="CleanShot 2022-02-23 at 17 15 13@2x" src="https://user-images.githubusercontent.com/1813435/155418147-cb161166-8a55-41b6-883c-d99b542f2ff7.png">

Current snackbar notice, when saving a published post:
<img width="256" alt="CleanShot 2022-02-23 at 17 14 29@2x" src="https://user-images.githubusercontent.com/1813435/155418019-eda7e05b-2dab-4ca6-8ed1-2d8c0bd8060f.png">

Proposed snackbar notice, when saving a draft post: 
<img width="255" alt="CleanShot 2022-02-23 at 17 14 46@2x" src="https://user-images.githubusercontent.com/1813435/155418084-2678e8b0-7a9b-496c-9a5b-36a109822a2f.png">

**Comment by brookewp** [comment]
I'd like to take a look into this 🙂

**Comment by skorasaurus** [comment]
This was included in Gutenberg 12.9. thanks to @brookewp - https://github.com/WordPress/gutenberg/pull/39482
