### ISSUE TITLE
File blocks show error in editor when added in columns without file name

### ISSUE THREAD

**Issue by kerrynicl** [WordPress/gutenberg#39057]
### Description

When you add a File block inside of a column and leave the file name blank, returning to the editor shows an error "This block contains unexpected or invalid content" with a button to "Attempt Block Recovery"
<img width="804" alt="Screenshot on 2022-02-24 at 10-57-01" src="https://user-images.githubusercontent.com/83325600/155560085-7435e84f-d502-4e10-bb7b-83b3b46deb31.png">

What you expected to happen
The File block should show the same way it does when you add the block originally.

What actually happened
The block shows an error message: "This block contains unexpected or invalid content" with a button to "Attempt Block Recovery".

### Step-by-step reproduction instructions

1. Add a Columns block to a page
2. Add a File block inside one of the columns
3. Select a file either from the Media Library or upload
4. Remove the file name added next to the Download button
5. Save and reload editor page

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting this.

The issue happens for me regardless of whether the file is in a column or not:
![Screen Shot 2022-02-25 at 11 47 27 am](https://user-images.githubusercontent.com/677833/155649951-2950ca3b-725c-4d8c-a427-6ec4870ab722.png)

I see what's wrong, I've put together a fix in this pull request - https://github.com/WordPress/gutenberg/pull/39083.

**Comment by talldan** [comment]
@kerrynicl The fix will be released in Gutenberg plugin version 12.8. Thank you for reporting the bug!
