### ISSUE TITLE
Content deleted when pressing delete then enter

### ISSUE THREAD

**Issue by marcochiesi** [WordPress/gutenberg#39067]
### Description

After using the "Del" key to join two paragraph blocks, if you hit "Enter" or "Shift+Enter" the text after the cursor gets deleted unexpectedly.

It may be related to #34722

### Step-by-step reproduction instructions

1. Insert some text in a paragraph block
2. Hit "Enter" to generate a new paragraph block
3. Insert some text in the second paragraph block
4. Move the cursor to the end of the text of the first paragraph block
5. Hit the "Del" key so that the two blocks are joined
6. Hit "Enter" or "Shift + Enter" and the content is deleted instead of going to a new line

### Screenshots, screen recording, code snippet

![gutenberg-bug](https://user-images.githubusercontent.com/2298248/155580597-0efbae30-2fc9-4a2f-a711-0c4132f3e31f.gif)

### Environment info

- WordPress 5.9.1, Gutenberg 12.6.1, Twenty Twenty-Two 1.1
- Chrome and Firefox on Windows 10 desktop

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for contributing, @marcochiesi.

https://github.com/WordPress/gutenberg/pull/38991 fixes this issue. I also added E2E tests to avoid regressions in the future #39007.

The fix will be part of Gutenberg 12.7, which should be released next week.
