### ISSUE TITLE
Add visual cue when dragging a block into an empty Group block

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#39064]
While we actually can drag and drop another block into an empty Group block, **there's no visual** to indicate that its possible. 

## Proposal
Add a design visual when dragging another block over an empty group (or columns) block. We can use the same DropZone styling and animations to "fill" the empty inserter and add the + icon.

#### Proposal
https://user-images.githubusercontent.com/1813435/236552286-a1213d4c-0777-46a9-b5b8-dc146a754813.mp4

#### Current 
For reference, here is what we have today (no visual indicator):

https://user-images.githubusercontent.com/1813435/155576600-a40dc958-9c7a-4556-acb5-7bf00b1ae82f.mp4

**Comment by richtabor** [comment]
As an aside, we also need a drop indicator for when you're dropping a block into a closed Group/Columns block. It's possible today to do that, but there's no visual indicating it so. Adding this here as it's related design wise.

**Comment by paaljoachim** [comment]
Thanks for adding this issue Rich!
(There was an earlier issue related to drop zones but I am not able to locate it.)

We should use similar drop zones that exist in Gutenberg today. Looking at drag and drop of image.
![Screenshot 2022-04-04 at 15 17 05](https://user-images.githubusercontent.com/5323259/161552189-99128106-ba0e-4338-a502-04fd5fc74a72.jpg)

Here is an example where I only added the blue background color to the Group block.
![Drop zone](https://user-images.githubusercontent.com/5323259/161552273-f3aa78c2-84f4-4163-8d71-ed13f28c4ffb.jpg)

@annezazu 
I added a drag and drop as a comment here https://make.wordpress.org/test/2022/03/31/fse-program-testing-call-13-authoring-an-author-template/#comment-2394

**Comment by richtabor** [comment]
I also think it's a good idea to match the current drag-and-drop UX — I made a couple adjustments based on your feedback @paaljoachim: 

<img width="961" alt="group" src="https://user-images.githubusercontent.com/1813435/170712826-156b53fd-779f-4ee7-8386-0765017f3cfa.png">

**Comment by paaljoachim** [comment]
Looks good Rich!

Any additional feedback here @jasmussen Joen?

**Comment by annezazu** [comment]
@paaljoachim Joen is on sabbatical right now just so this doesn't hold things up.

**Comment by paaljoachim** [comment]
Great! Thanks for letting me know @annezazu 

The method we have right now is consistent with the current UX method for drag and drop.
I believe we can move forward and add the label "Needs dev" and get this drag and drop method for the Group block in place.

**Comment by nickfmc** [comment]
this will be nice to have, after training people for the past 2 years on Gutenberg when handing over sites, I can say the biggest complaint I get is how bad the drag and drop UX is.

**Comment by paaljoachim** [comment]
Hey @richtabor and @jasmussen 
Let's get movement in this issue.
It would be great to get a PR in place and get the visual cue in for the empty Group block.

**Comment by richtabor** [comment]
I updated the issue with more up-to-date visuals and its been added to the [Polish](https://github.com/orgs/WordPress/projects/96/views/2) board. Let's get this going. 🚀
