### ISSUE TITLE
Allow Group block to transform to the Row variation

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#39066]
## What problem does this address?
While uncovering ways to improve the Group block editing experience, I found that transforming between the standard vertical-oriented Group block, to the Row variant, is still a bit convoluted. 

This made be lean in to ask, **should variation transforms be treated any differently than block transforms in the UI**?

Is there a reason to not include the "Row" variant as an option in the typical transforms UI — instead of having a separate variation UI? 

## What is your proposed solution?
Consider allowing block variants within the transform UI, so that variants are more easily surfaced in existing UI patterns (instead of replying solely on a separate control to "Transform to variation". 

#### The Group block's row variation omitted from primary transform interaction
<img width="708" alt="CleanShot 2022-02-24 at 12 52 00@2x" src="https://user-images.githubusercontent.com/1813435/155579872-31c3908a-0774-4317-9fe9-8b48fe12e947.png">
 
#### Transform to variation UI (should this be treated differently than standard transforms?)
<img width="568" alt="CleanShot 2022-02-24 at 12 53 25@2x" src="https://user-images.githubusercontent.com/1813435/155580006-4b660a1b-894f-4aeb-8903-36b2fafb6f9f.png">

**Comment by skorasaurus** [comment]
Thanks for continuing the conversation; @youknowriad mentions it at https://github.com/WordPress/gutenberg/pull/36202#issuecomment-1032305085

**Comment by richtabor** [comment]
> Thanks for continuing the conversation; @youknowriad mentions it at [#36202 (comment)](https://github.com/WordPress/gutenberg/pull/36202#issuecomment-1032305085)

Yes, that exactly!

**Comment by jasmussen** [comment]
Good ticket. There's a potentially largish design exploration possible here. 

The transforms interface — the dropdown you get by clicking the block icon — has huge potential, and can become the go-to destination to check when inserting a new block, or looking for layout changes or options on an existing block:

- It could surface variations or alternate styles or layouts
- It could surface different block or pattern transforms (with previews) that can accomplish an interesting layout didn't think of
- It could potentially hold locking options (#29864)

In addition to this, as is also [discussed here](https://github.com/WordPress/gutenberg/pull/36202#issuecomment-1031311152
), there are currently multiple different interfaces that all feel related to transforming blocks. It'd be good to look at unifying these.

Exploring a holistic vision for a lovely singular card with a full range of transforms could be a fun task with a big mockup and prototype. That's not to say it needs to block smaller iterations; but it would be a good north star to keep in mind!

**Comment by mtias** [comment]
We could also consider exposing these in the group block toolbar directly, like we do for multi-select:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/548849/185640948-2b95aa5a-8040-464c-bcc1-d33e9c5da890.png">
