### ISSUE TITLE
jest-console does not work with `jest.retryTimes()`

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#39079]
### Description

If you use `jest.retryTimes(2);` and have a test like follows:

```
let test = 0;
describe('Test', () => {
    it('should print console messages', () => {
        console.log('Hello World', test);
        test++;
        expect(test).toBe(2);
    });
});
```

The result will be a passing test with `Hello World 0` and `Hello World 1` logged to the console.

And if you simplify it like so:

```
describe('Test', () => {
    it('should print console messages', () => {
        console.log('Hello World');
        expect(true).toBe(true);
    });
});
```

`Hello World` is logged once.

Now, as soon as you include `@wordpress/jest-console`, there will be no console output anymore at all. All console output is swallowed and the test passes.

### Step-by-step reproduction instructions

Use `@wordpress/jest-console` in combination with `jest.retryTimes()`. All console output is swallowed and the package does not work at all anymore.

### Environment info

- Jest 27.5.1
- `@wordpress/jest-console` 5.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MahendraBishnoi29** [comment]
@swissspidy @gziolo is it still open to working on?

**Comment by swissspidy** [comment]
Sure why not, nothing has changed since filing it, so AFAIK it‘s still an issue.

**Comment by MahendraBishnoi29** [comment]
@swissspidy can you please guide me on where and how to make these changes, I'm just new here.

**Comment by swissspidy** [comment]
The package lives here: https://github.com/WordPress/gutenberg/tree/trunk/packages/jest-console

But I don‘t know that particular code or what would need to be changed.

**Comment by MericKarabulut** [comment]
Hello, i'm also new around here. I did a small research on the package and i reproduced the scenario. I'm not very good at this but from what i understand this problem seems to be solved.

- Tests that contains `consolle.log()` are no longer passes without `expect( console ).toHaveLogged();`
- `console.error, console.info, console.log` and `console.warn` outputs are not swallowed they prints to the screen whether tests fails or not
- `jest.retryTimes()` works as expected

As mentioned in [npm readme section](https://www.npmjs.com/package/@wordpress/jest-console) of `@wordpress/jest-console` it enforces usage of one of the related matchers whenever tested code calls one of the mentioned (console.error(), console.info(), console.log(), console.warn()) console methods.

Exampe: 
```
jest.retryTimes(3);
let test = 0;
describe('Test', () => {
    describe('Test', () => {
        it('should print console messages', () => {
            console.log('Hello World', test);
            test++
            expect(test).toBe(2);
            expect( console ).toHaveLogged();
        });
    });
});
```
Output:
```
  console.log
    Hello World 0

      at console.<anonymous> (node_modules/jest-mock/build/index.js:723:23)

  console.log
    Hello World 1

      at console.<anonymous> (node_modules/jest-mock/build/index.js:723:23)

 PASS  ./test.js
  Test
    Test
      √ should print console messages (3 ms)                                                                                                                                            
                                                                                                                                                                                        
Test Suites: 1 passed, 1 total                                                                                                                                                          
Tests:       1 passed, 1 total                                                                                                                                                          
Snapshots:   0 total
Time:        0.736 s, estimated 1 s
Ran all test suites.
Ran all test suites.
```

**Comment by swissspidy** [comment]
This is for cases where there is unexoected console output, i.e. when you are deliberately *not* using toHaveLogged et al. In those cases this is still an issue AFAIK, since this package hasn‘t been updated in a while.

**Comment by MericKarabulut** [comment]
I just checked again without using `toHaveLogged()` , it works on my environment but issue can be caused by jest configs or other related codes. I will deep dive into this and research more to find any possible cause.  

Environment: 

"@wordpress/jest-console": "^7.9.0"
"jest": "^29.5.0"

Example: 

```
jest.retryTimes(3);
let test = 0;
describe('Test', () => {
        it('should print console messages', () => {
            console.log('Hello World', test);
            test++
            expect(test).toBe(2);
        });
});
```
Output:
```
  console.log
    Hello World 0

      at console.<anonymous> (node_modules/jest-mock/build/index.js:723:23)

  console.log
    Hello World 1

      at console.<anonymous> (node_modules/jest-mock/build/index.js:723:23)

  console.log
    Hello World 2

      at console.<anonymous> (node_modules/jest-mock/build/index.js:723:23)

  console.log                                                                                                                                              
    Hello World 3                                                                                                                                          

      at console.<anonymous> (node_modules/jest-mock/build/index.js:723:23)

 FAIL  ./test.js
  Test
    × should print console messages (6 ms)                                                                                                                 
                                                                                                                                                           
  ● Test › should print console messages                                                                                                                   
                                                                                                                                                           
    expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: 4

       5 |             console.log('Hello World', test);
       6 |             test++
    >  7 |             expect(test).toBe(2);
         |                          ^
       8 |         });
       9 | });
      10 |

      at Object.toBe (test.js:7:26)

  ● Test › should print console messages

    expect(jest.fn()).not.toHaveLogged(expected)

    Expected mock function not to be called but it was called with:
    ["Hello World", 3]

      at Object.assertExpectedCalls (node_modules/@wordpress/jest-console/build/@wordpress/jest-console/src/index.js:32:4)

Test Suites: 1 failed, 1 total                                                                                                                             
Tests:       1 failed, 1 total                                                                                                                             
Snapshots:   0 total
Time:        0.873 s, estimated 1 s
Ran all test suites.
```

**Comment by swissspidy** [comment]
Interesting, thanks for testing! Then yeah sounds like a Jest config issue or something, or maybe an issue that was resolved on the Jest side.

in that case closing :-)
