### ISSUE TITLE
Row Block not spacing inner blocks properly within editor

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#39090]
### Description

\- When you try to remove a Row Block it says "Remove Group". It's completely irrelevant whether you're inserting a Group Block in the actual code. As far as a regular user is concerned the "Row Block" is just another type of block. It's annoying and incredibly confusing when you have options like "Remove Group" on a Block that is called a "Row". You do this on multiple blocks because I've mentioned this problem on multiple issues.

<img width="693" alt="screenshot_171" src="https://user-images.githubusercontent.com/2078245/155694397-c1911d2d-31eb-4c18-8e04-9a90138b2486.png">

---

\- The alignment is all messed up in the editor but displays ok on the front-end
Editor
<img width="1438" alt="screenshot_170" src="https://user-images.githubusercontent.com/2078245/155693602-37cf0f2e-ea42-4cf8-9f84-98c8a8b07bcc.png">

Front-end
<img width="1440" alt="screenshot_169" src="https://user-images.githubusercontent.com/2078245/155692282-b47d3068-f4fa-45b3-bfec-bef517f0b997.png">

---
\- After you've entered a number in the Padding field, you can't remove it. When you delete the text and move away from the field, the same text reappears.

https://user-images.githubusercontent.com/2078245/155692700-bc2a8d54-eb28-4877-95b2-68d53516ec65.mp4

### Step-by-step reproduction instructions

- Add Row Block
- Add 3 paragraph blocks with dummy text
- Set alignment to "Space between items"
- View the messed up alignment
- Add a number in the Padding field and navigate away from field
- Highlight previously added number in Padding field and press delete/backspace to remove it and clear the field
- See number reappear when you navigate away from field

### Environment info

WP 5.9.1
Twenty Twenty One
Firefox 97.0.1
macOS 12.2.1
No Gutenberg plugin, core only

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for contributing, @maddisondesigns.

The last issue might not be related to the Group/Row block but a general bug with Dimensions control. I can reproduce the same bug on the Code block.

cc @aaronrobertshaw, @ciampo

**Comment by ciampo** [comment]
I'm probably not the better-suited person to have a look at this, and I think that Aaron is not going to be around next week. Cc'ing @andrewserong @ramonjd @glendaviesnz

**Comment by maddisondesigns** [comment]
Another issue to add to the list:

When you turn off `Allow to wrap to multiple lines`, blocks start overlapping each other.

<img width="1190" alt="screenshot_172" src="https://user-images.githubusercontent.com/2078245/155871894-6aa3edc7-7b1f-41b1-87d2-40f388869f29.png">

**Comment by andrewserong** [comment]
Thanks for the ping @ciampo (and for reporting the usability issues @maddisondesigns!)

> - After you've entered a number in the Padding field, you can't remove it. When you delete the text and move away from the field, the same text reappears.

For this one, you can currently commit the change by pressing ENTER before tabbing or clicking out of the field, but I agree, the behaviour here doesn't feel intuitive to me, either. I've opened up a PR (#39109) to look at the behaviour of clearing out an `InputControl` field that has `isPressEnterToChange`, which should then resolve the issue with the padding and margin controls 🤞.

**Comment by ramonjd** [comment]
> It's annoying and incredibly confusing when you have options like "Remove Group" on a Block that is called a "Row". You do this on multiple blocks because I've mentioned this problem on multiple issues.

I've taken a stab at displaying the block _display_ title in the remove "Remove x block" label over at https://github.com/WordPress/gutenberg/pull/39110

A "block _display_ title" might be a specific block variation title, or a reusable block group name.

<img width="578" alt="Screen Shot 2022-02-28 at 1 13 04 pm" src="https://user-images.githubusercontent.com/6458278/155917692-50cceaa7-de1f-4066-9ef2-f8da1b4040c6.png">

**Comment by skorasaurus** [comment]
Thanks for reporting all of these issues; a couple of have been reportedly been fixed since issue was made, the two issues that you've said are: 

- The alignment is all messed up in the editor but displays ok on the front-end

- [When you turn off Allow to wrap to multiple lines, blocks start overlapping each other.](https://github.com/WordPress/gutenberg/issues/39090#issuecomment-1053261909)

I'm not able to reproduce either of these in WordPress 6.0 and Gutenberg 13.5 activated; it appears like the following which isn't aesthetically pleasing but the image is resized smaller to prevent overlap.
![image](https://user-images.githubusercontent.com/955351/176022577-1ac2d66d-ac85-45e9-b9f7-9ea37bc2e21a.png)

Could you share if you're still experiencing this currently and give more detail about the alignment issue? 

The block markup that I'm using is https://gist.github.com/skorasaurus/bd4f2caa9b18ffad7d232db183ccc2b2

**Comment by maddisondesigns** [comment]
@skorasaurus I've just checked these issues...

- The alignment issue is still there (see the second green row in screenshot below)
- You can now remove the padding and tab (or click) away from the field and it stays removed 👍
- The "remove" label has been changed to "Remove Row" instead of "Remove Group" 👍
- The overlapping blocks issue appears to be fixed now as well 👍


<img width="2094" alt="screenshot_949" src="https://user-images.githubusercontent.com/2078245/176078240-e4c05b1e-0753-42af-b327-0438c98bfd9e.png">
 
I tested this with WP6.0 and Gutenberg 13.5.1

**Comment by skorasaurus** [comment]
Thanks for the update: Took me a second to figure out that you applied wide width to the block; I'm able to reproduce this as well; 
the issue being that in the editor; the row block does not properly space out inner blocks under certain conditions, which I specify below. The inner blocks are spaced out properly on the front-end. 

So, to reproduce: 

1. install a theme.json-less theme like twentytwentyone 
2. create row block, apply wide or full width to it; and set justification to equal spacing
3. create 3 blocks (paragraph or headers) inside row block 

@maddisondesigns if you could update the issue's title so others could find it easier, that'd be great. 

(EDIT: Corrected my notes as mentioned by @maddisondesigns )

**Comment by maddisondesigns** [comment]
@skorasaurus I think you have that around the wrong way. The issue is that the row block **doesn't** properly space out inner blocks in the Editor (this **does** happen on the front-end). i.e. it displays properly on the front-end but not in the editor.

I've also updated this issues title for better clarity.

**Comment by Mamaduka** [comment]
It looks like this lists a couple of issues, and I believe most were fixed.

@maddisondesigns, can you update the issue description and only leave the remaining one(s)?

**Comment by maddisondesigns** [comment]
@Mamaduka I think this one can probably be closed now. All the issues that I mentioned seemed to have been fixed, or at the very least, Gutenberg has changed enough so that they no longer apply.

**Comment by Mamaduka** [comment]
Thanks for the update, @maddisondesigns!
