### ISSUE TITLE
Do not reset image size in settings after replacing an image

### ISSUE THREAD

**Issue by Jugibur** [WordPress/gutenberg#39107]
## What problem does this address?
After replacing an image, the image size is reset.
Resetting the image size does not seem useful to me. Especially when you have prepared certain groups with blocks for editors with certain image sizes. It can be easy to forget to set the correct image size again afterwards. Not all editors immediately notice a visual difference. 

## What is your proposed solution?
The previously selected image size should be retained. I would consider an exception only if the image was smaller than the selected size.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; sorry your issue didn't get attention until now; there's already another issue - https://github.com/WordPress/gutenberg/issues/39457 that's been made requesting it and you can follow its progress there.
