### ISSUE TITLE
Bulleted / numbered lists items should have line breaks between them in the code generated by Gutenberg

### ISSUE THREAD

**Issue by nekohayo** [WordPress/gutenberg#39102]
### Description

When writing text in a list type block, Gutenberg generates codes like this:

```
<!-- wp:list {"ordered":true} -->
<ol><li>blah blah</li><li>hasoetuhsantohuea oeua eouao euaoeu</li><li>banana banana banana</li></ol>
<!-- /wp:list -->
```

...instead of something clean and human-readable like:

```
<!-- wp:list {"ordered":true} -->
<ol>
    <li>blah blah</li>
    <li>hasoetuhsantohuea oeua eouao euaoeu</li>
    <li>banana banana banana</li>
</ol>
<!-- /wp:list -->
```

Now, you might be thinking "who cares, this is just for geeks", but imagine the example above with a dozen long sentences... it becomes a huge unreadable blob of text. There are two real issues with the compacted generated code:

* It makes it hard to fix incorrect formatting
* It makes it nearly impossible to review someone else's work with the diffs in the revision editor, because everything sits one one monolithic line so it's nearly impossible to tell things apart and to read it as a list like it was meant to be read

So please make Gutenberg generate readable lists code, particularly so that I can read the revision diffs of collaborators.

### Step-by-step reproduction instructions

1. Write text in a list type block
2. Look at the resulting code, in HTML view or in the revisions comparison tool

### Environment info

- Wordpress 5.9.1, with the built-in Gutenberg
- Firefox on Fedora Linux

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment]
This was fixed by #42711. Thanks for the report!
