### ISSUE TITLE
Group Block alignment option not shows when used in reusable block

### ISSUE THREAD

**Issue by uniquesolution** [WordPress/gutenberg#39103]
### Description

When you use group block to insert other blocks inside it and let make it wide width or full width, then make that whole group a reusable block, the option to change alignment not shows. It should show even if we keep that group inside a reusable block.

### Step-by-step reproduction instructions

1. Go to block editor and insert a group block
2. You will see the alignment option for it (like wide width or full width) apply any.
3. Now click on group more settings and choose "Add to Reusable blocks" , give a name and save it as reusable block.
4. Now click on group block and see the top option of alignment gone away.

### Screenshots, screen recording, code snippet

![group-block-issue2](https://user-images.githubusercontent.com/17669646/155834891-e930f01d-b718-497d-9d5b-bddb0ad3d3f6.gif)

### Environment info

Wordpress version 5.9.1
Gutenberg Version 12.6.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ocean90** [comment]
Related/Duplicate: #8288

**Comment by Mamaduka** [comment]
Thanks for reporting. There are some existing bug reports (https://github.com/WordPress/gutenberg/issues/8288 and https://github.com/WordPress/gutenberg/issues/17640), so I'll close this as a duplicate.
