### ISSUE TITLE
addEventListener 'load' not working on FSE editor.

### ISSUE THREAD

**Issue by grogou** [WordPress/gutenberg#39114]
### Description

`ref.current.addEventListener('load')` not working on FSE editor, but it is working on standard editor.
Nothing on console, just listener don't fire.

### Step-by-step reproduction instructions

1. Create custom block and add some `load` listener on some `ref`

### Environment info

Wordpress 5.9.1
Gutenberg 12.6.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I think a window object would be appropriate for attaching the load event.

And I think useRefEffect would be a good choice based on [Make WordPress Core](https://make.wordpress.org/core/) article.

Like this:

```javascript
import { useRefEffect } from '@wordpress/compose';
import { useBlockProps } from '@wordpress/block-editor';

export default function Edit() {
	const ref = useRefEffect( ( element ) => {
		function someFunc() {
			// do something...
		}

		const { ownerDocument } = element;

		// Relative window object
		const { defaultView } = ownerDocument;

		defaultView.addEventListener( 'load', someFunc );

		return () => {
			// remove event listener.
			defaultView.removeEventListener( 'load', someFunc );
		};
	}, [] );

	const blockProps = useBlockProps( { ref } );

	return (
		<p { ...blockProps }>test</p>
	);
}
```

**Comment by grogou** [comment]
@t-hamano thank you for this, but is there some difference between standard editor and FSE editor?  and about window listeners, my case is not use window.addEventListener it fire event on ref.

**Comment by t-hamano** [comment]
@grogou 
Unlike a regular editor, the site editor is an iframe editor instance, so when binding events to the windows object, a relative window (`defaultView`) starting from ref must be used.
(I don't know why the load event is not fired in the site editor when the load event of `ref.current` is applied...)

**Comment by grogou** [comment]
@t-hamano thank you it is lot of help.

**Comment by grogou** [comment]
`useRefEffect` not working too. So the problem is site editor or idk, is someone know how can this issue will be fixed?

**Comment by t-hamano** [comment]
Perhaps the event is not attached because the document is already loaded in the site editor (iframe editor instance).

I think it would be better to do the processing directly within `useEffect` without attaching the event.

```javascript
import { __ } from '@wordpress/i18n';
import { useEffect, useRef } from '@wordpress/element';
import { useBlockProps } from '@wordpress/block-editor';

export default function Edit() {
	const ref = useRef( null );

	useEffect( () => {
		const { ownerDocument } = ref.current;

		// should show "complete", this means that the document has been loaded.
		console.log( ownerDocument.readyState );

		// Do something directly without using event listener.
	}, [] )

	const blockProps = useBlockProps({ ref });

	return (
		<p { ...blockProps }>
			{ __( 'Test Block – hello from the editor!', 'test-block' ) }
		</p>
	);
}
```

**Comment by annezazu** [comment]
Curious if @ryanwelcher has any insights here!

**Comment by grogou** [comment]
@annezazu anyway this is not working in my side, so if you can suggest anything for this I will by glad for that.
Or if there complex way to understand this cases with "iframes". Where I can read about that something?

Thank you!

**Comment by annezazu** [comment]
For iframing, I'd recommend checking out this issue @grogou: https://github.com/WordPress/gutenberg/issues/33346 Apologies for missing your ping earlier!
