### ISSUE TITLE
Set the default border style to "solid"

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#39123]
## What problem does this address?
When adding the border properties in theme.json, I might not include `"style": true`. I'll get all the other elements in the UI, but they are useless, because no default border style is defined and no border will be shown.
` "settings": {
    "border": {
      "color": true,
      "radius": true,
      "width": true
    },...`
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/17861443/155991626-c0469a68-3c68-440b-b2d4-778642846788.png">

Even if I set the style to be true, I think the border style should have a default fallback, because the UI isn't that inutivelty showing me that I also have to click on one style to activate it.
<img width="284" alt="image" src="https://user-images.githubusercontent.com/17861443/155991078-e06101cf-f8ee-45b9-991b-1d87e7265868.png">

## What is your proposed solution?
Either add a default border style in Gutenberg or give the option to define a default in the theme.json.

**Comment by aaronrobertshaw** [comment]
This issue relates to the old border controls, which were updated in [#37770](https://github.com/WordPress/gutenberg/pull/37770). That PR also [added additional default styles](https://github.com/WordPress/gutenberg/pull/37770/files#diff-96306a997c6ce5c61d0a2e5256ac17b8639613f598c02f5400a37a84f9ccd3ef) applying a `solid` border style to those added via [#33743](https://github.com/WordPress/gutenberg/pull/33743/files#diff-96306a997c6ce5c61d0a2e5256ac17b8639613f598c02f5400a37a84f9ccd3ef). 

These defaults aren't bulletproof as it's still possible for blocks or themes to define border styles with a higher specificity however I believe they mostly achieve the proposed solution here. 

Unfortunately, I don't think there is a way of determining when a block will have border color/width applied via theme.json or global styles CSS and then apply a default border style as well. In this scenario however, the theme author can still explicitly state the border style they are chasing.

```json
	...
	"styles": {
		"blocks": {
			"core/group": {
				"border": {
					"color": "cyan",
					"width": "0.5em",
					"style": "solid"
				}
			}
		},
	}
```

While testing this I found a bug preventing the disabling/hiding of the border style control within the current border UI. A separate fix for that is up in https://github.com/WordPress/gutenberg/pull/43109.

As this issue relates more specifically to "default" border styles, I'll close it for now. 

Thanks for reporting this @Hannesdev; please let me know if there are further tweaks we can make to the border support experience. 👍 

---

<details>
<summary>Click for demo of border support with style control disabled (using #43109)</summary>

<video src="https://user-images.githubusercontent.com/60436221/183834606-c2f021e3-e428-48c6-a79b-381d8585afe2.mp4" />

</details>
