### ISSUE TITLE
LinkControl titles

### ISSUE THREAD

**Issue by djave-co** [WordPress/gutenberg#39125]
## What problem does this address?
When selecting a link with the `LinkControl` component, a title attribute is passed if it is an internal link. This is not editable, and not passed if it is an external link. This makes it hard to use one component for internal and external links.

## What is your proposed solution?
The `LinkControl` should have the option to expose the title of the attributes that are returned, and have the option to show a text input to edit this.

**Comment by markdavies** [comment]
@djave-co - I'm also struggling with this - am I missing something? Noticed you closed this the day after opening it...

**Comment by djave-co** [comment]
@markdavies Hi Mark, I opened a better issue here — 
https://github.com/WordPress/gutenberg/issues/39160
