### ISSUE TITLE
Allow block search option on editor for global styles 

### ISSUE THREAD

**Issue by sagarnasit** [WordPress/gutenberg#39135]
## What problem does this address?
Currently, We have to scroll and find the specific block from the list of all the available blocks. There are no search options for a long block list.

https://user-images.githubusercontent.com/25276905/156142717-2f0f17ef-d67d-4514-ac8b-c870448d5add.mov

## What is your proposed solution?
There should be a search/filter option where users can type and search/filter the blocks. This will reduce the block search time it takes when having a long list of blocks.

**Comment by ntsekouras** [comment]
👋 - thanks for creating the issue! I [opened a PR](https://github.com/WordPress/gutenberg/pull/39117) about this yesterday.
