### ISSUE TITLE
Handle Taxonomy Errors in Block Editor with Error Message

### ISSUE THREAD

**Issue by TMFHokies** [WordPress/gutenberg#39130]
### Description

I originally brought this up in the [support forums](https://wordpress.org/support/topic/display-error-message-when-block-editor-term-validation-fails/#post-15397759), but I believe this is a bug. When the block editor fails to add a term, via the `/wp-json/wp/v2/{TAXONOMY}` endpoint it just silently fails. The term still persists in the form token field, but won't be saved along with the post. This is bad because there's no feedback to the user that it failed to add.

I stumbled upon this when adding custom validation with the `pre_insert_term` filter by way of returning a `WP_Error`. I believe the calling code should detect a non-2xx response, alert the user, and remove the term from the applicable form token field.

Moreover, a terms field breaks (custom taxonomy or otherwise) whenever `pre_insert_term` _modifies_ a new term submitted by the user. If the user submits "foo" and `pre_insert_term` returns "bar", editor.js errors.

<img width="551" alt="155799926-075c0956-bc79-4105-8f15-a9c3dc66208a" src="https://user-images.githubusercontent.com/25965752/156030918-dc809435-d986-4403-8c03-c7b49b5bdf87.png">

### Step-by-step reproduction instructions

Add this filter:

```php
add_filter('pre_insert_term', function ($term, $taxonomy) {
    return new \WP_Error('test_fail', 'Test fail!', [
        'status' => 400,
    ]);
}, 10, 2);
```

Then add a new tag from `wp-admin/post-new.php` with the block editor.

![EBzzpZN](https://user-images.githubusercontent.com/25965752/156031274-b9c894b8-2cd8-4241-96a1-a832878e18be.png)

The tag won't save, and the endpoint will return a 400 response code. However, the user won't be notified of the error, and when they save the post, the tag won't be saved either.

![UGMZfTf](https://user-images.githubusercontent.com/25965752/156030648-3225d812-a124-46e9-b1ae-44665ad290c1.png)

### Screenshots, screen recording, code snippet

Please let me know if you need more screenshots or a screen recording beyond what was posted above.

### Environment info

- WordPress 5.8.1 with Twenty Twenty-One theme
- Chrome
- MacBook Pro with macOS Big Sur

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @TMFHokies

This was partially solved in #53369. Now, the editor will display a notice when term creation fails.

I think the only remaining bug here is to remove the term from the token field.
