### ISSUE TITLE
File Block: Opening editor with File block causes its file ID to get updated automatically

### ISSUE THREAD

**Issue by devNigel** [WordPress/gutenberg#39154]
### Description

When you open a post or a page that contains a File block, it causes its file ID to get updated automatically. This triggers Update button to get activated automatically without the user making any edits on the page.

If the post or page does not contain File block, that does not happen.

### Step-by-step reproduction instructions

1. Create a post or page.
2. Add File block and add a PDF or another document to it.
3. Publish it.
4. Close the editor and open the same post or page editor.
5. You will notice that Update button is enabled despite not making any changes.

If you Update it and check the revision history, it shows that the file ID got updated.

### Screenshots, screen recording, code snippet

<img width="1595" alt="image" src="https://user-images.githubusercontent.com/33957570/156319844-96298845-7317-42e7-b1d0-0f691941e3cf.png">

### Environment info

- WordPress 5.9.1
- Gurenberg 12.6.1
- MacOS 12.1, Google Chrome 98.0.4758.109

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @devNigel

The issue should be fixed now on the trunk and will be part of the Gutenberg 12.8 release. See #39088.
