### ISSUE TITLE
Discussion settings are not respected when using inherit option in Comments Query Loop block

### ISSUE THREAD

**Issue by SantosGuillamot** [WordPress/gutenberg#39157]
### Description

Right now, when the “Inherit from Discussion Settings” option is enabled in the Comments Query loop, it doesn’t respect the setting “Break comments into pages with X top level comments per page and the last/first page displayed by default. Comments should be displayed with the older/newer comments at the top of each page.”

### Step-by-step reproduction instructions

1. Go to Discussion Settings and change the "Break comments into pages" to 1 top level comments. Keep it disabled.
2. Go to a post with more than 1 comment, using the Comments Query Loop block.
3. You can see that, even when the setting is disabled, it is still breaking the comments into pages with 1 comments. If it is disabled, it shouldn't create different pages.

### Screenshots

**_Discussion settings_**
<img width="804" alt="Screenshot 2022-03-02 at 10 56 43" src="https://user-images.githubusercontent.com/34552881/156339147-f7906bc3-3d9f-410b-a6e4-9851adfc737a.png">

**_Comments Query Loop inherit option_**
<img width="282" alt="Screenshot 2022-03-02 at 10 17 30" src="https://user-images.githubusercontent.com/34552881/156339213-ad2e80d2-bfd2-43c0-9755-40e015f18abd.png">

**_Current result_**
<img width="698" alt="Screenshot 2022-03-02 at 10 50 44" src="https://user-images.githubusercontent.com/34552881/156339284-fca2a222-6b3e-4f24-9a52-05bb21898bb9.png">

**_Expected result_**
<img width="335" alt="Screenshot 2022-03-02 at 10 57 44" src="https://user-images.githubusercontent.com/34552881/156339367-9333ccfa-bb0b-48a7-a91e-97e77f10449e.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by michalczaplinski** [comment]
Hey @DAreRodz was this supposed to be closed? 🙂 

https://github.com/WordPress/gutenberg/pull/39204 says that it's a partial fix and not fixing the issue with "newer/older". If yes, is there a new issue to track just fixing that?

**Comment by michalczaplinski** [comment]
Hey @DAreRodz was this supposed to be closed? 🙂 

https://github.com/WordPress/gutenberg/pull/39204 says that it's a partial fix and not fixing the issue with "newer/older". If yes, is there a new issue to track just fixing that?

**Comment by DAreRodz** [comment]
Good catch, @michalczaplinski. I think it was closed automatically after merging #39204.

_However_, I've tested it and everything seems to be fixed, I think because the `build_comment_query_vars_from_block()` function (modified in #39204) is used also inside the Comment Template block.

So, yeah, I guess we can leave the issue closed. 😃
