### ISSUE TITLE
Child Theme can't export templates

### ISSUE THREAD

**Issue by 9-tailed** [WordPress/gutenberg#39167]
### Description

I added a child theme for twenty twenty-two and started editing some templates. I then wanted to export that templates to make it the default template with my child theme. But the edit-site-export.zip can't be opened. Sometimes I even get an "An error occurred while creating the site export." and no file at all. When I activate the parent theme, the export is working fine. Switching back to my child theme, no export is working.

### Step-by-step reproduction instructions

1. Create a child theme for 2022 theme and activate it.
2. Try to export a template or template part from the editor. You either get a corrupted zip or an error message.

### Screenshots, screen recording, code snippet

![grafik](https://user-images.githubusercontent.com/66306592/156407560-059b3707-9288-4369-ad44-9562b91f1702.png)

### Environment info

WP: Version 5.9.1
Gutenberg: Version 12.6.1
Theme: Twenty Twenty Two Child 1.1
Windows 10 Pro
Firefox 97.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by 9-tailed** [comment]
I finally found the problem.
In the function.php there were some spaces after the ?> 
This did not show any errors except for exporting. 
The same applies to normal themes made from scratch, not only child themes.

**Comment by draganescu** [comment]
Hi @9-tailed was the [problem you found](https://github.com/WordPress/gutenberg/issues/39167#issuecomment-1058374201) connected to your child theme? If so may we close this issue?

**Comment by 9-tailed** [comment]
The problem is not directly connected to wordpress, so yes this can be closed.
It would have been nice to see any kind of error message, maybe when switching to the theme, but I think this is nothing for this issue. Thanks.
