### ISSUE TITLE
Improve discoverability of (and new location for) new menus system

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#39162]
## What problem does this address?

With WordPress 5.9 the `Menus` page will be removed for any site that uses a Block Theme. This has been replaced by the Navigation block and menus are now managed from with the editor.

Folks have been reporting that there is a lack of discoverability for this change. Here is [one such example from my YouTube channel](https://www.youtube.com/watch?v=BzDCCNjF9mg&lc=Ugw58rqqxbW8HBL5UPx4AaABAg):

> After using Wordpress for years, firing up an install & not being able to find Admin panel options that you're accustomed to is a really frustrating experience...
> Just installed Wordpress for the first time in some months and spent the last 25 minutes frustratingly trying to figure out where all the missing options like Menus were.  

I'm sure folk have other examples (cc @annezazu ).

## What is your proposed solution?

Perhaps we should consider one of the following

1. Reinstating the `Menus` screen and replacing the content with an explanation which signposts users to the new way of managing menus via the Nav block.
2. Adding a widget to the Dashboard to highlight the change to the menus system and signpost users.

Any other suggestions welcome.

**Comment by Humanify-nl** [comment]
I've always found it strange that the old menu screen was not brought in line with the new way of editing in the block itself. I guessed there were technical limitations and also assumed that this is in the works.

What would be great is to have one place to manage all the menu's. 

When I was playing around a bit with the menu block and tempate parts, there were somehow 5 different menu's created and I had no idea what was what anymore. This is when I missed my menu screen. I'm sure a clients experience would not be different and possibly worse because I am supposed to know what I'm doing as a WP dev.

**Comment by getdave** [comment]
Hi @Humanify-nl. Thank you for taking the time to feedback here.

The points you make are valid and the team working on the Navigation feature is very conscious of this.

There was originally the Navigation Editor screen but the currently feeling is that this is overly ambitious. What we're working towards now is providing somewhere to manage menus outside of the Navigaiton block whilst still remaining in the editor environment.

That might sound strange, but consider that the direct editing paradigm is key to Gutenberg. Therefore havuing a separate screen to manage menus would be the only place where content is managed outside of the editor.

I appreciate things aren't ideal right now but we are [listening working on improvements](https://github.com/WordPress/gutenberg/issues/38275).

If you'd like to find out more about the state of play around these things please check out [this episode of the WP Tavern podcast](https://wptavern.com/podcast/14-dave-smith-isabel-brison-and-joen-asmussen-on-the-new-navigation-block) where a few of the regular contributors to the Nav block discussed it at length.

Thanks again.

**Comment by Humanify-nl** [comment]
@getdave  I have been following WP's developments closely the last months, even digging into issues here and there and totally understand where you're getting at with the direct editing paradigm. To see how Gutenberg improves in great strides is impressive. Even though not all changes are what we expect or go against what we're used to (and what we're used to is not per se better). Possibly like the menu screen.


As someone who's been working a lot with ACF blocks (less and less however), the way they implemented the block settings to 'open' inside the editor, could be a great way to do a bit more menu editing. But I feel I'm a little out of place here to actually come up with a good solution. 

Alternatively, I see some potential in the current site editor (menu's could fit nicely in there).

![image](https://user-images.githubusercontent.com/82579622/156613845-2a6b95e3-76c7-4061-9a4d-207392c41506.png)

But I for sure trust that the team is working on a solution that is probably better fitting!

**Comment by getdave** [comment]
> Alternatively, I see some potential in the current site editor (menu's could fit nicely in there).

In which case you might like https://github.com/WordPress/gutenberg/pull/38600.

**Comment by annezazu** [comment]
Wanted to loop back finally to share some thoughts! Personally, I don’t think it makes sense to add an item back under Appearance that is just a sign post as that won’t help with the discoverability of the block itself when you’re in the Site Editor experience. Instead, I’d rather see us implement things like the [navigation structure UI](https://href.li/?https://github.com/WordPress/gutenberg/issues/36667) you mention above, [improved connections to patterns with the nav block](https://href.li/?https://github.com/WordPress/gutenberg/issues/28737), better importing experience of Classic menus, more robust /wp-admin/edit.php?post_type=wp_navigation section/integration with template focused part mode, etc. From there, in time, perhaps an entry point can be be considered that could open up the manage menu section depending on how things fit together at the time (perhaps as part of the W menu). I could see this especially being helpful for mega menu functionality.

In the short term, a blurb about menus/navigation block could be added to the [Welcome Guide though](https://href.li/?https://github.com/WordPress/gutenberg/issues/32844#issuecomment-967059100) as, to me, that would act as a sign post without taking up precious real estate/offering a consistent “dead end” to users. 

Either way, I do agree around discoverability _and_ am encouraged by the various in progress things in place to ease the tension.

**Comment by getdave** [comment]
@javierarce How would we go about commissioning a new entry for the Welcome Guide that covers Navigation? If I raise a PR and then ping you for some design assets does that work?

**Comment by beckej13820** [comment]
The comment above that resonated with me the most was @Humanify-nl 's comments on accidentally creating multiple menus because of the current state of the menu system. It would be nice if we could look at a list of menus, and be able to tell which ones are actually used, possibly linked to #42482 and be able to see if a menu is used in a template or template part. 

Menus are so integral to the WP building experience that I wonder if they shouldn't have a link underneath the template and template parts in the site editing screen.

**Comment by getdave** [comment]
[WP 6.2 has included a new Browse Mode sidebar in the Site Editor](https://www.youtube.com/watch?v=PKcMhSgBt40&t=9s). Unfortunately the Navigation aspect of this was pulled from the release in RC2 meaning it won't land until WP 6.3 at the earliest.

It is however available in the Gutenberg Plugin.

As a result I suggested we close this Issue.
