### ISSUE TITLE
FSE: Template Part fails to save if the name contains an emoji

### ISSUE THREAD

**Issue by edequalsawesome** [WordPress/gutenberg#39174]
### What you expected to happen

Emoji should either be supported in the Template Part's name or validation should be implemented for the Template Part name at the time of its creation.

### What actually happened

`Saving failed.` message is displayed.

### Step-by-step reproduction instructions

1.  Create a new Template Part via Site Editor > Template Parts > Add New
2.  Include an emoji (such as 🍟) in the name and click Create
3.  Add any block to the template part
4.  Click Save

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4000628/156450002-ac4c04e6-0338-497c-a90c-b975d7f3f737.mov

### Environment info

WordPress 5.9.1
Gutenberg 12.6.1
Twenty Twenty-Two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by zdenys** [comment]
This should be resolved as it's no longer happening on WordPress.com where it was initially reported https://github.com/Automattic/wp-calypso/issues/61052#issuecomment-1139425244

**Comment by ironprogrammer** [comment]
## Test Report

Confirmed this is resolved in WordPress core ✅ -- recommend **closing** issue.

### Environment
- OS: macOS 12.5
- Browser: Safari 15.6
- Server: nginx/1.23.1
- PHP: 7.4.30
- WordPress: 6.0.2-alpha-53697-src
- Theme: twentytwentytwo v1.2
- Gutenberg plugin NOT active 🔴

### Steps to Test
1. Navigate to _Appearance > Editor_, expand navigation and select _Template Parts_.
2. Click **Add New**.
3. In the "Name" field enter a title with an emoji character.
4. Click **Create**.
5. Add a block to the template and/or sample text and click **Save**.
6. Observe that no error occurs.
7. Navigate back to _Template Parts_ and the new part is displayed in the list (_Figure 1_).

### Screenshots

_Figure 1:_
<img width="800" alt="39174-template-part-emoji-in-name" src="https://user-images.githubusercontent.com/824344/184423291-1553a736-5cd9-4614-84cc-2810382ffe9e.png">

**Comment by ellatrix** [comment]
![template-part-emoji](https://github.com/WordPress/gutenberg/assets/4710635/a3f54382-e143-4738-aaeb-ba7678397619)

I can confirm this works correctly now. Let's close. Please reopen if we're mistaken. :)
