### ISSUE TITLE
FSE: Menu updates through the Customizer or Apperance > Menus section not reflected on site

### ISSUE THREAD

**Issue by edequalsawesome** [WordPress/gutenberg#39175]
### Description

If you select one of your already created Menus (under `Appearance > Customize` or `Appearance > Menus`) to be added to the Header section of FSE Header ->Navigation section, you will notice that this section doesn't update automatically when you make any additional changes to those sections -- you need to re-select the Navigation menu to be used from the Classic Menu section instead.

### Step-by-step reproduction instructions

1. Go to `Appearance > Customize > Menus` or `Appearance > Menus`
2. Create a menu for your site, and save it.
3. Go to `Appearance > Editor`
4. In the Header section, add the Navigation block and select the Menu you created in Step 1 above
5. Go back to `Appearance > Customize > Menus` or `Appearance > Menus` and edit the menu that you've selected in the FSE editor, and save those changes
6. Go back to `Appearance > Editor` and view the Header template you previously added that Navigation block to

### Environment info

WordPress 5.9.1
Gutenberg 12.6.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting.

The classic menus are migrated to a new menu format, and further edits will need to be made within the navigation block itself.

Some discussion has taken place on how the UI could be improved to convey that here - https://github.com/WordPress/gutenberg/issues/36307.

There's no plan to make classic menus directly editable from the navigation block. Given #36307 already discusses improvements I'll close this issue.
