### ISSUE TITLE
Wrong path - "vendor/plugins" subfolder missing

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#3919]
Seems as you forgot subfolder "plugins" in gutenberg-vendor folder ?
JS console gives a lot of errors and cannot find those files. Of course not possible. I just checked there is non subfolder "plugins".

Maybe just lefovers paths from version before.
I use 1.9 version.

Inside vendor folder should be several more subfolders. According to code and paths.

**Comment by StaggerLeee** [comment]
Better you make new 2.0 update.
With 19 JS files missing there is no point in Demo testing.

**Comment by StaggerLeee** [comment]
I added most plugins from TinyMce latest package. Some WP specific from WP core folders. Errors are gone, but do not know if everything will work well.

**Comment by youknowriad** [comment]
I think you're seeing the same issue mentioned here https://github.com/WordPress/gutenberg/issues/3512 and a fix here https://github.com/WordPress/gutenberg/pull/3840

(See the PR for why the fix is not merged yet)

Closing this as duplicate
