### ISSUE TITLE
Allow spacer block to set a width when inserted inside Row blocks.

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#39206]
## What problem does this address?

The use case for the horizontal space between blocks comes into the picture when we consider the Row block and its usage in the Header template in FSE.

To add more space between two blocks inside a row block, there is currently nothing that can be used other than an empty paragraph block.

## What is your proposed solution?

Just as we use Spacer block to add extra space (height) in the regular flow of blocks, I am requesting a Spacer block that would also help add space horizontally (width).

**Comment by talldan** [comment]
Thanks for creating the issue. This one is already reported in https://github.com/WordPress/gutenberg/issues/36197, so I'll close as a duplicate.
