### ISSUE TITLE
Commas in page atts panel

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#3921]
The page attributes panel contains some weird commas:

![page-atts](https://user-images.githubusercontent.com/583546/33843849-cb05920e-de9e-11e7-9712-ca4be7613c72.png)

**Comment by nosolosw** [comment]
cc @jasmussen because you probably know how to tag this issue in a way that helps with issue visibility and such.

**Comment by nosolosw** [comment]
Perhaps related to this (maybe some parsing error stripped them out and introduced the commas?): I cannot find where should I edit the _parent page_ and the _default template_.

**Comment by nosolosw** [comment]
Perhaps related https://github.com/WordPress/gutenberg/issues/991

**Comment by karmatosed** [comment]
Thanks for reporting, good catch and this is previously reported and fixed in https://github.com/WordPress/gutenberg/issues/3918.
