### ISSUE TITLE
The group block adds some inline styles that aren't validated properly via W3C validator

### ISSUE THREAD

**Issue by MaitreArt** [WordPress/gutenberg#39220]
### Description

When I add the core group block there are inline styles added to its class, such as:
```
<style>.wp-container-6222132642da3 .alignleft { float: left; margin-right: 2em; }.wp-container-6222132642da3 .alignright { float: right; margin-left: 2em; }</style>↩
<style>.wp-container-62221326443b4 .alignleft { float: left; margin-right: 2em; }.wp-container-62221326443b4 .alignright { float: right; margin-left: 2em; }</style>↩
<style>.wp-container-62221326449f2 .alignleft { float: left; margin-right: 2em; }.wp-container-62221326449f2 .alignright { float: right; margin-left: 2em; }</style>
```

And when we check it through https://validator.w3.org/ we have errors: 
`Element style not allowed as child of element body in this context. (Suppressing further errors from this subtree.)`

### Step-by-step reproduction instructions

1. Go to the page or post
2. Add group block, update the page or post
3. Check it through https://validator.w3.org/

### Screenshots, screen recording, code snippet

![Showing results for Nu Html Checker 2022-03-04 19-31-09](https://user-images.githubusercontent.com/92185985/156772347-9477a907-f2a6-46d7-ab89-0636d182127a.jpg)
![Showing results for Nu Html Checker 2022-03-04 19-30-44](https://user-images.githubusercontent.com/92185985/156772359-300af8ea-aa96-4296-bc70-46097adc42a6.jpg)

### Environment info

- WordPress version 5.9.1, from Twenty Twenty Eighteen (didn't check older version) to Twenty Twenty One themes
- All plugins are disabled

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MaitreArt** [comment]
Any updates??? The same issues happen with a Columns block

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/38917 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
