### ISSUE TITLE
Paragraph tags are stripped

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#3922]
A gif is worth a thousand words:

![reusable-block-paragraph](https://user-images.githubusercontent.com/583546/33844664-3c0a717a-dea1-11e7-9673-069a82539073.gif)

Steps to repro:

* I created a reusable block to insert breadcrumbs on certain pages - a paragraph that contains a link and some other text.
* I reused that block in a page. The markup seemed to be correct in the editor.
* When I publish the page, the reusable block doesn't contain the paragraph markup.

**Comment by nosolosw** [comment]
cc @noisysocks because I saw you did some work recently on reusable blocks.

**Comment by nosolosw** [comment]
When I go back to the page to edit this I got this message:

![editing-after](https://user-images.githubusercontent.com/583546/33845177-e038babc-dea2-11e7-88dd-cfcd027bb282.png)

And in the console:

![editing-after-errors](https://user-images.githubusercontent.com/583546/33845183-e5ca98ec-dea2-11e7-9f3f-a88af7c9f5bd.png)

**Comment by nosolosw** [comment]
I have 11 active plugins on my site (which is part of a WordPress network I manage):

* These are active at a network level: Akismet anti-spam, Blogger Importer, Categories to Tags Converter Importer, Force Strong Passwords, Jetpack by WordPress.com, Network Plugin Auditor, VaultPress, WordPress Importer.
* These are active on my site: Gutenberg, Official StatCounter Plugin, RSS Importer.

**Comment by nosolosw** [comment]
I've got another way to reproduce this error, so perhaps it hasn't anything to do with ReusableBlocks. Here's the gif:

![no-paragraphs](https://user-images.githubusercontent.com/583546/33931594-b7ff467a-dff0-11e7-9a5f-aa542a395ee1.gif)

Steps: 

* open an old published post that contains images and consecutive paragraphs
* convert to blocks
* publish

When I got back to the editor, the paragraph blocks cannot be processed by Gutenberg:

![no-paragraphs-editor-back](https://user-images.githubusercontent.com/583546/33931651-eb276da2-dff0-11e7-9dd8-3f357fe89067.png)

And this is what the console shows at that point:

![no-paragraphs-console-back](https://user-images.githubusercontent.com/583546/33931660-f1c83aec-dff0-11e7-9aca-7d7eb0f7592f.png)

**Comment by nosolosw** [comment]
I've tried deactivating Official StatCounter Plugin and RSS Importer and disconnecting Jetpack from my site as well. I've got the same result. Any other test I may do to help?

**Comment by aduth** [comment]
@nosolosw Can you try deactivating the Jetpack plugin instead of just disconnecting from WordPress.com?

**Comment by nosolosw** [comment]
Confirmed that I can reproduce this in Gutenberg 2.0.

**Comment by withinboredom** [comment]
I also had this same problem, however my layout was a bit different:

```html
<!-- wp:core/paragraph {"dropCap":true} -->
<p class="has-drop-cap">First Paragraph.</p>
<!-- /wp:core/paragraph -->

<!-- wp:core/paragraph -->

Second paragraph.

<!-- /wp:core/paragraph -->
```

All following paragraph blocks are missing `<p>` tags and were typed in the visual editor normally as writing a book. At the end, I added the drop cap to the first paragraph after editing the text in the block. Everything looked fine in the editor, however when I published, it was a massive block of text except for the first paragraph.

**Comment by withinboredom** [comment]
I should also add that I also had Jetpack connected, but disabling gutenberg resolved the problem.

**Comment by withinboredom** [comment]
I wonder if it has something to do with `wpautop`

**Comment by nosolosw** [comment]
I can confirm that after @aduth https://github.com/WordPress/gutenberg/pull/4874 I can only repro this with [these steps](https://github.com/WordPress/gutenberg/issues/3922#issuecomment-351335025) if I have the Jetpack's "write post/pages in markdown" option enabled when I convert an old post to Gutenblocks.

Perhaps this is worth labeling Plugin / Extension conflict?

**Comment by Ipstenu** [comment]
Well... that’s a pretty big conflict. I had to disable Gutenberg just to get content written in Gutenberg to show correct. The only other option was manually editing OUT the Gutenberg html comments in html edit mode.

**Comment by aduth** [comment]
Relevant problematic code in Jetpack's Markdown module, removing paragraph tags on save:

https://github.com/Automattic/jetpack/blob/c5aea23/modules/markdown/easy-markdown.php#L547-L548
https://github.com/Automattic/jetpack/blob/c5aea23/_inc/lib/markdown/gfm.php#L278-L285

**Comment by aduth** [comment]
Since Jetpack's Markdown module strips paragraphs prior to save, merely deactivating the Markdown module will not retroactively fix broken posts. However, since Gutenberg is [capable of "repairing" unwrapped paragraphs](https://github.com/WordPress/gutenberg/pull/4874), it _should_† be resolved if opening the post once more and saving it within Gutenberg.

In trying this myself, this works as expected, with one exception being that link tags (and I assume may apply to bold, italic, etc) showed the HTML as escaped and needed to be updated before saving. Unsure yet if this is also a conflict introduced with Jetpack's Markdown module.

**Comment by mkaz** [comment]
@nosolosw @Ipstenu The Jetpack Markdown and Gutenberg conflict should be resolved in 2.3.0 which was deployed yesterday.

Fixed in this PR: https://github.com/WordPress/gutenberg/pull/5288

**Comment by nosolosw** [comment]
With Gutenberg 2.3.0 and Jetpack 5.8 it is no longer an issue (tested following [this steps](https://github.com/WordPress/gutenberg/issues/3922#issuecomment-351335025)). :tada:

**Comment by aduth** [comment]
Great! Going to consider this closed unless the issue crops up again.
