### ISSUE TITLE
Navigation: Submenus not hidden on older browsers

### ISSUE THREAD

**Issue by ryelle** [WordPress/gutenberg#39230]
Originally reported to the WordPress.org header repo, https://github.com/WordPress/wporg-mu-plugins/issues/159. The navigation menu dropdowns use `:where` to hide the submenus, which does not work on Chrome 87 & below ([source: Can I use](https://caniuse.com/?search=%3Awhere)). Chrome 88 was released in Jan 2021.

You can see the issue in the following screenshots, on both the custom code for WordPress.org & the demo site for Twenty Twenty-Two (the "Sub-page" is visible like a top-level item).

| Chrome 87 | Firefox 97 |
|------------|------------|
| ![](https://user-images.githubusercontent.com/541093/156836398-f50e0ffd-e428-40b7-b02c-ef0e7cdb67ee.png) | ![](https://user-images.githubusercontent.com/541093/156836526-dec93eff-8aa1-44b5-badd-ab39d07962b2.png) |
| ![](https://user-images.githubusercontent.com/541093/156836400-931794eb-b220-4311-85c8-7c7d1c652c9d.png) | ![](https://user-images.githubusercontent.com/541093/156836529-370a1abb-9f30-4b7c-b499-1b818769efdb.png) |

While this does match with the supported browserslist, there was some discussion about whether this list should also apply to the frontend of sites ([discussion starts here](https://wordpress.slack.com/archives/C02RQBWTW/p1645043331818489)).

> @joyously The reason I brought it up is because there is a list of supported browsers for the WP product. But it seems to be the supported list for the .org site (and apparently all sites created by the WP product).
> Usually this list only affects the admin. Now it's starting to affect the front end of WP sites.

**Comment by iandunn** [comment]
There's a new discussion in #39621 about the larger problem

**Comment by jasmussen** [comment]
#42964 aims to fix this issue, and links out to 2 potential addons.

**Comment by jasmussen** [comment]
This should be fixed by #42967.
