### ISSUE TITLE
Add syntax highlighting to code editor

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3923]
This has come up a few times in testing. When you are in the code editor or a block that shows code, having syntax highlighting is something people are asking for. My question here is would there be a light weight highlighter we could use that doesn't harm performance?

**Comment by afercia** [comment]
@karmatosed there's already https://github.com/WordPress/gutenberg/issues/1733 open for this, with some good pros and cons argumentations already there 🙂

**Comment by westonruter** [comment]
For adding CodeMirror to the Custom HTML block in particular, see https://github.com/WordPress/gutenberg/pull/1625#issuecomment-336332382

**Comment by karmatosed** [comment]
Closing as we have #1733
