### ISSUE TITLE
Image Block: Image alignment breaks .is-style-rounded

### ISSUE THREAD

**Issue by supernovia** [WordPress/gutenberg#39242]
### Description

If I add an image and set the style to rounded, it works consistently. If I then align the block left, right, or center, it looks fine in the editor, but does not work properly on a live site.

### Step-by-step reproduction instructions

With the latest Gutenberg plugin enabled:

1. Create a post and add a new image with /image
2. Set the size to medium (just to be able to see alignment later) and style to rounded.
3. Copy that block three times. Leave the first copy without alignment, but go ahead and align the other three to left, right, and center.

Note it looks fine in the editor, but if I view it on the site, the rounding disappears. I have duplicated this on a handful of themes.

If I create a new post while Gutenberg is deactivated, the images align and round properly.

## Example posts made with and without Gutenberg active:
<img width="816" alt="twenty twenty one" src="https://user-images.githubusercontent.com/3476361/156944860-5e25af3f-37a5-4b00-9951-5514ac76aa89.png">

<img width="819" alt="Screen Shot 2022-03-06 at 3 30 02 PM" src="https://user-images.githubusercontent.com/3476361/156944882-4ebd7677-9b5f-4771-ab37-c0966541973b.png">

## The CSS:
```
.wp-block-image:not(.is-style-rounded)>a, .wp-block-image:not(.is-style-rounded) img {
    border-radius: inherit;
}
```

## HTML without current Gutenberg active; both classes are on the div, and it works:
```
<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-medium"><img width="250" height="300" src="https://i0.wp.com/veldavongutenberg.mystagingwebsite.com/wp-content/uploads/2022/03/what.jpeg?resize=250%2C300&amp;ssl=1" alt="" class="wp-image-784" srcset="https://i0.wp.com/veldavongutenberg.mystagingwebsite.com/wp-content/uploads/2022/03/what.jpeg?resize=250%2C300&amp;ssl=1 250w, https://i0.wp.com/veldavongutenberg.mystagingwebsite.com/wp-content/uploads/2022/03/what.jpeg?w=580&amp;ssl=1 580w" sizes="(max-width: 250px) 100vw, 250px"><figcaption>Medium, Rounded, Centered</figcaption></figure></div>
```

## HTML with current Gutenberg active. One class goes to the div, and the other goes to the figure, so the CSS negates the rounding.
```
<div class="wp-block-image">
<figure class=" aligncenter size-medium is-style-rounded"><img width="250" height="300" src="https://i0.wp.com/veldavongutenberg.mystagingwebsite.com/wp-content/uploads/2022/03/what.jpeg?resize=250%2C300&amp;ssl=1" alt="" class="wp-image-784" srcset="https://i0.wp.com/veldavongutenberg.mystagingwebsite.com/wp-content/uploads/2022/03/what.jpeg?resize=250%2C300&amp;ssl=1 250w, https://i0.wp.com/veldavongutenberg.mystagingwebsite.com/wp-content/uploads/2022/03/what.jpeg?w=580&amp;ssl=1 580w" sizes="(max-width: 250px) 100vw, 250px"><figcaption>medium, rounded, centered</figcaption></figure></div>
```

### Environment info

- On my .org test site, I'm using **WP 5.9.1**. Test posts were created with and without **Gutenberg Version 12.7.0** active. I tested in a handful of themes.  Images are from Twenty Sixteen and Twenty Twenty One. (My Twenty Twenty Two is too broken from experiments right now 😅 )

- WordPress.com is affected by the HTML issue, too. It seems to play out differently in different themes. Examples here are Independent Publisher, Livro (rounded but certainly not medium), and Twenty Twenty Two (same issue):
<img width="807" alt="Screen Shot 2022-03-06 at 3 30 18 PM" src="https://user-images.githubusercontent.com/3476361/156945329-222cb015-32d5-40bd-b0a8-64ec591d61f5.png">

First spotted [here](https://wordpress.com/forums/topic/rounded-corners-in-images-not-working/).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
Possibly related to this change https://github.com/WordPress/gutenberg/pull/38657 ?

**Comment by glendaviesnz** [comment]
@youknowriad I just did some testing and this issue was introduced by https://github.com/WordPress/gutenberg/pull/38657 - checking out the commit prior to this the `is-style-rounded` is still applied to the same `div` as `wp-block-image`, as these non-block themes are expecting, but it is moved to the `figure` element with this change.

For the rounded style it looks like it can be fixed by changing `&.is-style-rounded img` to `&.is-style-rounded img, .is-style-rounded img` [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/image/style.scss#L72), but the likes of TT1 also has its own image styles like `is-style-twentytwentyone-image-frame` which are also broken by this change. I ran out of time to see if there was an easy way to move these classes up a level for non-block themes on the frontend sorry.

**Comment by youknowriad** [comment]
>  I ran out of time to see if there was an easy way to move these classes up a level for non-block themes on the frontend sorry.

The change in https://github.com/WordPress/gutenberg/pull/38657 is supposed to impact only themes with theme.json, so this is block themes and a very small number of classic themes. So I don't expect the impact to be wide spread if we fix the issue for the core provided styles and default classic themes using theme.json. That change is needed though and will require a dev note.

**Comment by glendaviesnz** [comment]
There is a potential fix for the missing rounded style here https://github.com/WordPress/gutenberg/pull/39295, and for those sites that can added custom css it can be fixed by adding the following in the meantime:

```css
.wp-block-image .is-style-rounded img{
	border-radius: 9999px;
}
```

**Comment by glendaviesnz** [comment]
Have added [another issue ](https://github.com/WordPress/gutenberg/issues/39297) that covers the wider issue of other custom image styles in themes also being broken when applied in conjunction with alignment.

**Comment by youknowriad** [comment]
Thanks for the fix :)
