### ISSUE TITLE
__experimentalSetPreviewDeviceType is not working in Site Editor

### ISSUE THREAD

**Issue by awps** [WordPress/gutenberg#39248]
### Description

`wp.data.dispatch('core/edit-post').__experimentalSetPreviewDeviceType('Tablet')` and `wp.data.select('core/edit-post').__experimentalGetPreviewDeviceType()`

These two functions are experimental/unstable, I know. They are not working in the Site Editor. They still are working fine in the post editor.

What are the alternatives to trigger the preview resize programmatically in the Site Editor?

### Step-by-step reproduction instructions

Open dev console in WP-Admin in a post and run the following function: 
```wp.data.dispatch('core/edit-post').__experimentalSetPreviewDeviceType('Tablet')``` 

It will resize the window.

Do the same in Site Editor by going to Appearance->Editor. The preview will not be resized.
Calling this `wp.data.select('core/edit-post').__experimentalGetPreviewDeviceType()`, will return `Tablet`, but as mentioned earlier, the preview is not resized.

### Screenshots, screen recording, code snippet

🆗Working, post editor: 👇

https://user-images.githubusercontent.com/1436534/157016197-ba1b887f-4e9e-4843-9c58-d4b09df62482.mp4

⚠️ Not working, site editor:  👇

https://user-images.githubusercontent.com/1436534/157015394-51296d7c-25c0-4954-8484-598b40c3ae13.mp4

### Environment info

Clean install with Twenty Twenty-Two theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @awps

I think the following is the correct action for Site Editor:

```js
wp.data.dispath('core/edit-site').__experimentalSetPreviewDeviceType('Tablet')
```

**Comment by awps** [comment]
Hey @Mamaduka 
That's it! Tested and it's working. 
Thank you. :) 

------
**For reference:** 

Site editor: 
```
wp.data.dispatch('core/edit-site').__experimentalSetPreviewDeviceType('Tablet');
wp.data.select('core/edit-site').__experimentalGetPreviewDeviceType();
```

Post Editor: 
```
wp.data.dispatch('core/edit-post').__experimentalSetPreviewDeviceType('Tablet');
wp.data.select('core/edit-post').__experimentalGetPreviewDeviceType();
```
