### ISSUE TITLE
Gutenberg Ready theme

### ISSUE THREAD

**Issue by AshiqKiron** [WordPress/gutenberg#3925]
I'm thinking of build a basic blog theme to submit to w.org official theme repository by TGMA-ing Gutenberg plugin (until Gutenberg gets backed right into WP). All the tutorials I'm seeing is recommending "Gutenberg Boilerplate Plugin" by Awais can I bypass that and just use Gutenberg plugin for developing custom blocks, am I missing something ? I've gone thru the official gutenberg handbooks and Awais's tutorial. I'd be glad to get advice/direction for it before diving into.

**Comment by karmatosed** [comment]
I think we probably need to close this as it's not an issue of the project per say. You do not need that boilerplate to build a theme. There is a theme experiment here: http://github.com/WordPress/gutenberg-theme
