### ISSUE TITLE
Nav block: inner blocks are not copied when copying the markup of the block

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#39279]
### Description

When I have a Navigation block that has inner blocks, such as the page list one, those don't get copied if I use the "Copy" menu from the navigation block toolbar

### Step-by-step reproduction instructions

On a site that has a navigation block with a markup such as:

```
<!-- wp:navigation {"overlayBackgroundColor":"background","overlayTextColor":"foreground","layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"right","orientation":"horizontal"},"style":{"spacing":{"blockGap":"37px"}},"fontSize":"small"} -->
<!-- wp:page-list /-->
<!-- /wp:navigation -->
```

Go to the site editor, click on the navigation block, select "Copy" from the menu, you will get:

`<!-- wp:navigation {"ref":3084,"overlayBackgroundColor":"background","overlayTextColor":"foreground","layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"right","orientation":"horizontal"},"style":{"spacing":{"blockGap":"37px"}},"fontSize":"small"} /-->`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I've just re-tested this and can no longer recreate it in testing. It seems now if I copy the Navigation block it includes the reference - which does bring through inner blocks.

`<!-- wp:navigation {"ref":33} /-->`
