### ISSUE TITLE
The editor has encountered an unexpected error

### ISSUE THREAD

**Issue by Tabrisrp** [WordPress/gutenberg#3929]
## Issue Overview

Gutenberg 1.9 is displaying a box with this error and 3 buttons when other plugins adding metaboxes to the edit screen are activated at the same time.

Disabling the other plugins resolve the issue and Gutenberg displays correctly.

## Steps to Reproduce (for bugs)

1. Activate Gutenberg
2. Activate another plugin that adds metaboxes to the edit screen (personal example: SEOPress)
3. Try to add a new post/page or edit an existing one
4. Error in console is `TypeError: e.entries is not a function. (In 'e.entries()', 'e.entries' is undefined)` for `/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js` line 436

This was tested on Safari 11.0.2

## Expected Behavior
Gutenberg displaying and the metaboxes from the other plugins also.

## Current Behavior
Error visible in the screenshot below

## Screenshots / Video
https://imgur.com/Isr1iQi

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by TwisterMc** [comment]
I have this issue too but only in Safari oddly enough. Firefox works fine.

Error below. I replaced my actual site with site-removed.net

> value@https://site-removed.net/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513045208:6:14422
value@https://site-removed.net/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513045208:6:14191
value@https://site-removed.net/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513045208:6:13207
commitLifeCycles@https://site-removed.net/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:2:12700
c@https://site-removed.net/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:2:1679
k@https://site-removed.net/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:2:3490
Q@https://site-removed.net/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:2:3942
ed@https://site-removed.net/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:2:5980
enqueueSetState@https://site-removed.net/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:2:20382
setState@https://site-removed.net/wp-content/plugins/gutenberg/vendor/react.min.6b26329b.js:1:3453
onStateChange@https://site-removed.net/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513045208:1:97154
[native code]
notify@https://site-removed.net/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513045208:1:131864
notifyNestedSubs@https://site-removed.net/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513045208:1:132398
[native code]
onStateChange@https://site-removed.net/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513045208:1:97180
[native code]
notify@https://site-removed.net/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513045208:1:131864
notifyNestedSubs@https://site-removed.net/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513045208:1:132398
[native code]
onStateChange@https://site-removed.net/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513045208:1:97180
[native code]
l@https://site-removed.net/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513045208:1:98853
initializeMetaBoxes@https://site-removed.net/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513045208:1:171648
https://site-removed.net/wp-admin/post-new.php:2105:84
promiseReactionJob@[native code]

**Comment by youknowriad** [comment]
Yes, SEOPress works for me on Chrome but not on Safari, it looks like a browser specific issue

<img width="711" alt="screen shot 2017-12-12 at 08 32 24" src="https://user-images.githubusercontent.com/272444/33872408-0e2c2f0c-df17-11e7-9c47-9e93f87fcd5a.png">

**Comment by TwisterMc** [comment]
For clarification, I was not using SEOPress.

**Comment by hedgefield** [comment]
This just happened to me too on 4.9.1 + 1.9. I clicked on the `Categories & tags` section in the sidebar, and it crashed. `Attempt Recovery` does nothing, plus this same error now appears on ALL other posts AND when pressing Add New too.

When I disabled Yoast SEO, the error was gone (we do add stuff to that section).

Upon returning to the post, the `Categories & Tags` section was open. I wanted to try and reproduce it, so I collapsed the section, turned the plugin back on, returned to the post again, clicked on `Categories & Tags` again, got an error again.

cc @mtias

**Comment by youknowriad** [comment]
This happens systematically with any plugin adding meta boxes in Safari. The PR #3934 should fix it.

**Comment by hedgefield** [comment]
This happens to me in Chrome btw.

**Comment by youknowriad** [comment]
Works for me in Chrome, do you see the same JS error above? Can you try the PR branch?

**Comment by hedgefield** [comment]
Close, it says

`TypeError: e.types.indexOf is not a function
    at http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513071140:21:108930
    at http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513071140:6:50596
    at http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513071140:6:59931
    at o (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513071140:6:19682)
    at http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513071140:6:60061
    at o (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513071140:6:50576)
    at o (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513071140:6:15944)
    at o (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/editor/build/index.js?ver=1513071140:21:108891)
    at beginWork (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:133:69)
    at d (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:158:393)
    at f (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:214)
    at g (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:462)
    at t (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:167:3)
    at x (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:166:247)
    at batchedUpdates (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:169:173)
    at cc (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:26:56)
    at jc (http://src.wordpress-develop.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:35:5)`

**Comment by youknowriad** [comment]
Probably something else, could you create a separate issue, I'll investigate later?

**Comment by hedgefield** [comment]
PR seemingly did not work.

**Comment by hedgefield** [comment]
Sure thing.
