### ISSUE TITLE
Font color issue in pagination of Query loop block in editor side

### ISSUE THREAD

**Issue by aezazs-multidots** [WordPress/gutenberg#39305]
### Description

When I create a page and I use query loop block in it, then the issue is coming in font color of pagination of that block on the **backend** side. 

Whenever I am giving font color in pagination, then font color is being applied only on the **current** page number and **dots**. But when I set the background color in that pagination, then all the numbers of the pagination, that font color gets applied. So there is no consistency in the font color of Pagination, that's why there is an issue in the font color of Pagination on the backend side.

### Step-by-step reproduction instructions

1. Go to the backend of any page and post
2. Now select the query loop block of the Gutenberg blocks
3. and first of all change the font color of the pagination
4. If you change the font color of Pagination, then only dots and the current Pagination number will be applied to that font color.
5. Now in Pagination you select the background color. So after changing the background color, that font color will be applied to all the numbers of the pagination.

### Screenshots, screen recording, code snippet

I have added a video link of the pagination font color issue in the query loop block.

[https://www.loom.com/share/d869aae81ab944ca93c5779ecf103f73](https://www.loom.com/share/d869aae81ab944ca93c5779ecf103f73)

### Environment info

- WordPress v5.9.1
- Twenty Twenty-One Theme
- Chrome Browser ( Version 99.0.4844.51 )
- Mac OS

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I have tested this issue, and everything is working as expected now in the latest versions of Gutenberg and WordPress. Note that the "Text" color does not target the "Links" so they can be styled differently. If you want both to be the same color, you need to set them accordingly. 

![image](https://user-images.githubusercontent.com/4832319/184926725-a9d9062e-af10-4ad2-8989-c7bc6ae6f6b5.png)
