### ISSUE TITLE
Site Editor: Templates screen - add the ability to sort by recently updated, alphabetical, or type (adding additional columns).

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#39307]
## What problem does this address?

Anne originally added the comment to this issue: 
**Expand the types of templates that can be added in the Site Editor**
https://github.com/WordPress/gutenberg/issues/37407#issuecomment-1062444658
I am moving it into a new issue.

----

It would be helpful to add a sorting mechanism in the Templates screen. By adding the 
ability to sort by recently updated, alphabetical, or type.

## What is your proposed solution?

Original:
![Screenshot 2022-03-09 at 11 44 57](https://user-images.githubusercontent.com/5323259/157426491-9236bb48-3942-4bdc-8e8c-7594a1ef4281.jpg)

I will assume that we should add additional columns for updated and type. (This part will need another issue.)
From making the below mockup the screen becomes a bit busy. 

![Templates-screen-ability-to-sort-additional-columns](https://user-images.githubusercontent.com/5323259/157427968-2daab6ca-3c82-4716-8e05-8b304e48410a.jpg)

I believe we should have a method to show or hide columns. (Another issue)
In the Classic environment for All posts and All pages we have the Screen Options. To where the user can choose which columns to show or hide. 

![Screenshot 2022-03-09 at 11 58 24](https://user-images.githubusercontent.com/5323259/157428598-f4099a0f-60f9-415b-90df-34f8a7064d0e.jpg)

Thoughts and ideas? 
@jameskoster @annezazu

**Comment by annezazu** [comment]
Noting that the work around Data Views will impact this, allowing you to sort in various ways in the future https://github.com/WordPress/gutenberg/issues/55083

**Comment by youknowriad** [comment]
Right now, it's possible to sort the templates by author or by template alphabetically. It is possible to add more sortable fields but let's create dedicated issues at the moment.
