### ISSUE TITLE
In wordpress 5.9.1 add block button overlap with navigation menu in mobile device

### ISSUE THREAD

**Issue by minaldiwan** [WordPress/gutenberg#39304]
### Description

In wordpress 5.9.1 version getting issue when changing screen into small screen at that time navigation block last menu when we adding new menu using add block button same time block button overlap with menu.

### Step-by-step reproduction instructions

1.Go to page editor
2.Selecting mobile view using preview button
3.In mobile device click on hamburger button and slide-out navigation 
4.Click on menus to add new menu and also same time selection navigation block alignment in center and right end at the time add block button overlap issue occur with menu.

### Screenshots, screen recording, code snippet

below i have attached issue screen recording:
[https://www.loom.com/share/2ec8fe313ba341f58e6b5cd9abe6178b](https://www.loom.com/share/2ec8fe313ba341f58e6b5cd9abe6178b)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Heya @talldan @jasmussen - just circling back on this navigation-block-related item to see if there might be a way to move the related PR forward now that the reporter has replied – thanks! https://github.com/WordPress/gutenberg/pull/39338

**Comment by jasmussen** [comment]
Yes, editing the overlay is a pretty bad experience, and at this point honestly I think we need something like #43852 in order to fix it.

**Comment by getdave** [comment]
I tested this with WP 6.7 and I cannot replicate any overlap of the button:

https://github.com/user-attachments/assets/5b44cf46-fdc0-4f50-be3d-9b3c31719774


I will close this out but I'd be happy to take another look if someone can still replicate the original issue.
