### ISSUE TITLE
Implement a Select control

### ISSUE THREAD

**Issue by cr101** [WordPress/gutenberg#3931]
It would be great to have a Select field type in Gutenberg out of the box. The <select> component could be used to link two different CPTs (Books and Authors) or select multiple custom taxonomy terms.
This React Select control (https://github.com/JedWatson/react-select) is a great one.

**Comment by hadamlenz** [comment]
I just implemented react-select in [this component](https://github.com/hadamlenz/ncfgears-reference-block/blob/master/src/block/Select2.js) in my [first custom block](https://github.com/hadamlenz/ncfgears-reference-block).  Much of it is from the [githubusers](https://github.com/JedWatson/react-select/blob/master/examples/src/components/GithubUsers.js) example on [JedWatson's project](https://github.com/JedWatson/react-select)

Check out the edit statement [here](https://github.com/hadamlenz/ncfgears-reference-block/blob/master/src/block/block.js) to see how it works in `registerBlockType()`
