### ISSUE TITLE
Inline styles vs classes

### ISSUE THREAD

**Issue by vyskoczilova** [WordPress/gutenberg#39311]
Hi, 

With the 5.9 WP release we're facing an issue with disappearing CSS classes like is-content-justification-center and inline styles are used instead of it. 

Is there a way to prefer CSS classes instead of inline styles? To revert this "feature"? We're using theme.json because of Gutenberg configuration (and for example ability to kill duotones etc.) and this "enabled" us as well inline CSS.

Is there any filter or option to enable it? For custom coded templates, it's a disaster (same as removing the inner block from group block - not a big problem, but at least worth mentioning). Now we've added a few filters for rendering block, but this is just unsustainable. CSS classes need to stay unchanged.

I believe it's not just a matter of custom-coded templates but the fact, that you can't cache inline styles by browser and you're downloading them over and over again. You can customize them either by CSS.

Thanks!

**Comment by glendaviesnz** [comment]
Thanks for reporting this @vyskoczilova. There is [a wider discussion about the issues you raise here](https://github.com/WordPress/gutenberg/issues/38998), so I am going to close this in favour of that issue - please feel free to add an additional comment there if you don't feel that the points you raise are already adequately covered.

**Comment by benplum** [comment]
Is the answer that the some blocks no longer output the alignment classes in favor of inline style blocks? Where are changes like this documented? Developing WP is giving me serious whiplash, every update means spending weeks patching all client sites running Gutenberg.
