### ISSUE TITLE
Gallery block: Block is broken when returning from HTML edit mode to visual edit mode

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#39310]
### Description

In the new gallery block, when I select "Edit as HTML" and press the "Option" button, the block is broken.

I think that HTML editing should be prohibited in blocks that have child blocks (such as column blocks and group blocks).
But HTML editing is not prohibited in `v1` gallery block, so the process should be switched between `v1` / `v2`.

I found something even stranger, when I tried to resolve block , one of the comment delimiters in the image block was `wp:fimage` instead of `wp:image`.

![captrue](https://user-images.githubusercontent.com/54422211/157440767-11aa4890-52c8-487e-9935-fb4ae1a1e355.png)

### Step-by-step reproduction instructions

1. Insert gallery block.
2. Select images or upload images.
3. Insert the gallery without any particular editing.
4. Select "Edit as HTML" from Block Toolbar Option.
5. Do not edit the HTML, and press the option button shown in the upper left corner of the block.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/157439379-deba8d56-6ee7-4817-9554-10092f68d775.mp4

### Environment info

- WordPress version: 5.9.1
- Gutenberg version: latest(12.7.1)
- Browser: Google Chrome 99.0.4844.51
- OS：Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
It makes sense to disable HTML editing for Gallery v2, and I think we only need to declare `"html": false` in block supports.

**Comment by t-hamano** [comment]
@Mamaduka 

Since the gallery block is automatically migrated from v1 to v2, should I simply add `html:false` without considering v1?
If so, I would like to send a pull request 👍

**Comment by Mamaduka** [comment]
Correct, just add `html: false` to the block.json.
