### ISSUE TITLE
h2 is not taking it's own line

### ISSUE THREAD

**Issue by hazephase** [WordPress/gutenberg#3932]
I have make a video to show you what I am talking about, I add a H2 on the backend it does not show on it's own line in the frontend. https://www.screencast.com/t/OtmJRzq0JUc

**Comment by Soean** [comment]
@hazephase I can't start the Video in Chrome/Firefox/Safari on Mac OS. 
Message: `We're sorry, but we are unable to connect to this content. Please try refreshing the page or click here for more help.`

**Comment by hazephase** [comment]
@Soean  I am able to see the video, but basically what is the problem is that the header block is not a full-width element.Please take a look at the sceen below
![screen shot 2017-12-12 at 18 48 50](https://user-images.githubusercontent.com/7451130/33886635-37f3342e-df6d-11e7-994e-9c9ea5f3462a.png)

**Comment by Soean** [comment]
@hazephase Now I am able to see the video. 

This is not an Gutenberg related issue, it's your Theme.
You are unsing `display: flex;`for `.grid-x`, so the headlines are displayed inline.
```
.grid-x {
	display: -ms-flexbox;
	display: flex;
	-ms-flex-flow: row wrap;
	flex-flow: row wrap;
}
```
