### ISSUE TITLE
Allow setting margins for embeds

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#39339]
## What problem does this address?

If you want a design with some additional top and/or bottom spacing around embeds, for example a Youtube video,
you need to add spacing blocks or place the embed inside a container, and add the spacing to the container.

## What is your proposed solution?

Enable top and bottom margin controls for embeds and the video block.

**Comment by carolinan** [comment]
The reason why I am suggesting top and bottom margin only is that I am _assuming_ that if you are aligning multiple videos horizontally, you are more likely to already be using a column or row as a container, and you would use the container block gap to space the items.

**Comment by HILAYTRIVEDI** [comment]
Hi @carolinan, Thank you for this suggestion, I think we can also add the left and right margin if someone wants to add the embedded block without any column or container.

**Comment by KokkieH** [comment]
In terms of left/right margins, I have a case [in the forums](https://wordpress.org/support/topic/youtube-block-overlaps-text/) where text wrapping around a right-aligned Youtube embed goes right up to the edge of the embed. This enhancement should help prevent this type issue.

**Comment by HILAYTRIVEDI** [comment]
Hi @KokkieH, Thank you for the reference that's really helpful. I agree with your point, that allowing the left/right margin to be controlled will help the user to remove this kind of issue.

**Comment by skorasaurus** [comment]
this has been implemented in both the embed and video blocks in https://github.com/WordPress/gutenberg/pull/39384 and https://github.com/WordPress/gutenberg/pull/43365
