### ISSUE TITLE
Image style issue in gallery block

### ISSUE THREAD

**Issue by aezazs-multidots** [WordPress/gutenberg#39346]
### Description

When I created any one page in Twenty Twenty One theme and added gallery block to it. Then I selected 2 images in that gallery block. I selected 'rounded' in both the image styles, then in one image I added to add a caption, and in the other image, I did not add a caption. Then when I clicked on the image after adding the add caption, the style of the second image is not pure rounded in the backend and front end side.

### Step-by-step reproduction instructions

1. Go to the backend of any page and post
2. Now select the Gallery block of the Gutenberg blocks
3. Add 2 images to that gallery block and select that image's style **rounded**
4. Add a caption to one of these 2 images. And select the image in which the caption has been added
5. Now after selecting the image with the caption, the style of the second image it has will not be pure rounded in the backend and front end side

### Screenshots, screen recording, code snippet

I have added a video link of the Image style issue in the gallery block.

[https://www.loom.com/share/badbe604958a44abab76c2cf5bb47dae](https://www.loom.com/share/badbe604958a44abab76c2cf5bb47dae)

### Environment info

WordPress v5.9.1
Twenty Twenty-One Theme
Chrome Browser ( Version 99.0.4844.51 )
Mac OS

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@aezazs-multidots The gallery block has an option enabled by default - 'Crop images'.

That's what causes this. If you turn that option off your images won't be sized inconsistently.
