### ISSUE TITLE
Image left-align and right-align issue in group block.

### ISSUE THREAD

**Issue by Smit2808** [WordPress/gutenberg#39344]
### Description

When an image is added in a group block, we try to left or right-align the image. It's creating height issues in the group block. I am attaching 1 video in that you can clearly see it. 

I inspected it and found that when left or right-align is set then due to float in CSS, it's happening. Now I am trying to solve it.

### Step-by-step reproduction instructions

1. Add group block and set some background color to group block.
2. Add an image in the group block.
3. Set the image size to see the left and right alignment effects properly.
4. Now set the image in the left or right-align. And you will see the issue clearly.

### Screenshots, screen recording, code snippet

Video link: https://www.loom.com/share/1af8bccffeb34067af5906947fc05ed9

### Environment info

WP V5.9.1
Gutenberg trunk
Mac OS
Browser Chrome
Having fresh WordPress setup no external plugins and themes are installed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by HILAYTRIVEDI** [comment]
Hi @Smit2808, Thank you for the ticket. But I think it's a bit of a theme problem instead of Gutenberg. So the below code will fix the issue. As it is only appearing in the Twenty Twenty Two theme. 


```
.wp-site-blocks, body > .is-root-container, .edit-post-visual-editor__post-title-wrapper, .wp-block-group.alignfull, .wp-block-group.has-background, .wp-block-cover.alignfull, .is-root-container .wp-block[data-align="full"] > .wp-block-group, .is-root-container .wp-block[data-align="full"] > .wp-block-cover{

overflow: auto

}
```

**Comment by ndiego** [comment]
Thank you for the ticket @Smit2808. I am able to replicate the issue in other themes besides Twenty Twenty-Two. @HILAYTRIVEDI  is correct that a quick solution is to add the following CSS to your theme's style.css file. 

```
.wp-block-group {
    overflow: auto;
}
```

That said, this would probably also be good to add as a default to Gutenberg. I cannot think of a reason why not. Perhaps there is one, but I'll look into it. But in the meantime, the workaround above will solve the issue.

**Comment by Smit2808** [comment]
Hi, @ndiego I created the PR https://github.com/WordPress/gutenberg/pull/42910 and added the overflow auto CSS in the group block and now it is working in twenty twenty-two theme and other themes as well. As @JustinyAhin mentioned the issue https://github.com/WordPress/gutenberg/issues/40131. This issue #40131 is also happening due to the group block so by adding overflow auto it will be fixed.

**Comment by jordesign** [comment]
@Smit2808 just checking in on this older issue - do you still see it present with current versions of WordPress?

**Comment by jordesign** [comment]
With no further movement on this issue - I'm going to close it. We can always re-open if there is more information, or more reportable cases
