### ISSUE TITLE
Typo in test description for didPostSaveRequestSucceed

### ISSUE THREAD

**Issue by salcode** [WordPress/gutenberg#39356]
### Description

The `didPostSaveRequestSucceed` test description says

> should return true if the post save request has failed

but it should say

> should return false if the post save request has failed

https://github.com/WordPress/gutenberg/blob/499d5a887d6e5f2ce8821fb1b1d7f5a52472396f/packages/editor/src/store/test/selectors.js#L2154-L2162

### Step-by-step reproduction instructions

n/a

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by KAJALwp** [comment]
Hello @salcode, @karmatosed 

I have also crossed verified the text and yes it shows true instead of false.

Thank you.

**Comment by t-hamano** [comment]
@salcode

I also checked and found one more description where there is a discrepancy.
It should say `false`, not `true`.

https://github.com/WordPress/gutenberg/blob/d5915916abc45e6682f4bdb70888aa41e98aa395/packages/editor/src/store/test/selectors.js#L2176-L2184

Is it possible to submit a PR for these two descriptions if you would like?
