### ISSUE TITLE
Allow independent configuration of font-size of responsive navigation

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#39352]
## What problem does this address?
Currently, in order to have a different size font for the navigation "responsive" menu additional CSS has to be provided.

## What is your proposed solution?
Just as `overlayBackgroundColor` and `overlayTextColor` are available options to style the overlay menu separately from the "desktop" menu an `overlayFontSize` (and potentially other font-related attributes) could be available.

**Comment by jasmussen** [comment]
If we were able to implement complete customization of the contents of the modal overlay, as discussed in #39142, would that address it?

**Comment by kjellr** [comment]
> If we were able to implement complete customization of the contents of the modal overlay, as discussed in https://github.com/WordPress/gutenberg/issues/39142, would that address it?

Yes, I think so!

**Comment by pbking** [comment]
#39142 looks great.  Closing this in difference to that.
