### ISSUE TITLE
Aria attributes disappear during save

### ISSUE THREAD

**Issue by crs1138** [WordPress/gutenberg#39351]
### Description

We have the following custom block registered and for all users apart from _super administrator_ we get an error of invalid content when user with role other than _super administrator_ saves the page/post that contains the block. 

![image](https://user-images.githubusercontent.com/1313681/157666312-9f9b08e7-d6e3-4cb0-9a08-5d9b37ed8709.png)

We managed to narrow down the error to the aria attributes in the DOM structure returned by the _save_ function. It seems that if we use `aria-controls` and/or `aria-expanded` attributes these are not saved with the page. Using `data-controls` and `data-expanded` instead of the `aria-` attributes results in expected behaviour.

## How to reproduce

1. Create a new page
2. Insert the block
3. Save page
4. Refresh the page

## Simplified version of the block's code

```javascript
edit: function( props ) {
    const blockProps = useBlockProps();
    return (
        <>
            <div {...blockProps}>
                <button aria-controls="test">hello</button>
            </div>
        </>
    );
},
save: function( props ) {
    const blockProps = useBlockProps.save();
    return (
        <div {...blockProps}>
            <button aria-controls="test">hello</button>
        </div>
    );
}
```

## Content generated by block

```html
<!-- wp:cv-wp-gb-lib-blocks/collapse -->
<div class="wp-block-cv-wp-gb-lib-blocks-collapse"><button aria-controls="test">hello</button></div>
<!-- /wp:cv-wp-gb-lib-blocks/collapse -->
```

## Content saved into database

```html
<!-- wp:cv-wp-gb-lib-blocks/collapse -->
<div class="wp-block-cv-wp-gb-lib-blocks-collapse"><button>hello</button></div>
<!-- /wp:cv-wp-gb-lib-blocks/collapse -->
```

## Error in JS Console in editor

```
Block validation: Expected attributes [Array(3)]0: (3) ['aria-controls', 'test', true]length: 1[[Prototype]]: Array(0), instead saw []length: 0[[Prototype]]: Array(0).
```

```
blocks.js:3610 Block validation: Block validation failed for `cv-wp-gb-lib-blocks/collapse` ({name: 'cv-wp-gb-lib-blocks/collapse', icon: {…}, keywords: Array(2), attributes: {…}, providesContext: {…}, …}apiVersion: 2attributes: align: {type: 'string', enum: Array(6)}answer: {type: 'string', default: '', source: 'html', selector: '.cvgb-collapse__row'}className: {type: 'string'}id: {type: 'string', default: ''}isExpanded: {type: 'boolean', default: false}question: {type: 'string', default: '', source: 'html', selector: '.cvgb-collapse__question > span'}[[Prototype]]: Objectcategory: "cvgb-blocks"description: "Adds collapsable organism, e.g. FAQs"edit: ƒ Edit()icon: {background: 'rgba(255, 215, 190, 1)', src: {…}, foreground: '#191e23', shadowColor: 'rgba(255, 215, 190, 0.3)'}keywords: (2) ['collapse', 'faqs']name: "cv-wp-gb-lib-blocks/collapse"providesContext: {}save: ƒ Save()styles: []supports: {align: Array(2)}title: "Collapsible"usesContext: [][[Prototype]]: Object).

Content generated by \`save\` function:

<div class="wp-block-cv-wp-gb-lib-blocks-collapse"><button aria-controls="test">hello</button></div>

Content retrieved from post body:

<div class="wp-block-cv-wp-gb-lib-blocks-collapse"><button>hello</button></div>
```

## Tested on the following configurations

- Wordpress version 5.8.3
- Gutenberg plugin (not in use)
- Browser: [Chrome](https://www.whatismybrowser.com/w/HKHAYEB), [Brave](https://whatismybrowser.com/w/L4RJSZM)
- OS: Linux Ubuntu (kernel 5.14.0), Mac OS 10.15.7

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by crs1138** [comment]
We have now tried it using WP@5.9.1 and Gutenberg@12.7.1 and the same error occurs.

**Comment by ocean90** [comment]
WordPress only allows some ARIA attributes, see https://github.com/WordPress/wordpress-develop/blob/9ab0f766e73eb93896f684ff8961f6067836466b/src/wp-includes/kses.php#L2560-L2564 for the current list. The related ticket was https://core.trac.wordpress.org/ticket/30421. So you may want to open a ticket on Trac to request support for additional attributes.

**Comment by talldan** [comment]
@crs1138 As mentioned above, this isn't something the Gutenberg codebase has any control over, it's handled by WordPress core.

The bug tracker for WordPress core is here - https://core.trac.wordpress.org/. Are you happy to make a ticket there?

**Comment by ocean90** [comment]
A ticket has been created: https://core.trac.wordpress.org/ticket/55370
