### ISSUE TITLE
Post Date: Support to show modified date

### ISSUE THREAD

**Issue by yusuke-omae** [WordPress/gutenberg#39367]
## What problem does this address?
[The Post Date Block currently supports only the published date](https://github.com/WordPress/gutenberg/blob/984041993995227245467df98b1db53753610777/packages/block-library/src/post-date/index.php#L16-L35).
However, depending on site requirements (e.g., technical articles), the updated date may be important.

## What is your proposed solution?
Default is preferable to the published date/time, but it would be nice to be able to display the updated date/time as an option IMO.

Thank you for your time,

**Comment by Otto42** [comment]
This seems like a good enhancement to an existing block.

**Comment by daviedR** [comment]
+1

**Comment by carolinan** [comment]
This has been added as an option in the settings sidebar of the post date block.
