### ISSUE TITLE
In Gallery block image caption color palette not looks proper in mobile

### ISSUE THREAD

**Issue by minaldiwan** [WordPress/gutenberg#39375]
## Description
In Gallery block image caption color palette not looks proper as compare with desktop view.

## Step-by-step reproduction instructions
1. Added Group block inside group block selecting gallery block and added caption for it.
2. Click on caption and highlight caption using inline toolbar 
3. Then changes background and text color of caption.

## Expected behaviour
Need to add full width of color palette as shown in desktop.

## Actual behaviour
In mobile view color palette alignment and width are not looks proper.

## Screenshots or screen recording (optional)
[https://www.awesomescreenshot.com/video/7835927?key=66a974406a5b04bde6818ef39693c960](https://www.awesomescreenshot.com/video/7835927?key=66a974406a5b04bde6818ef39693c960)
## WordPress information
- WordPress version: 5.9.2
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme:Twenty twenty two theme

**Comment by hypest** [comment]
Thanks for opening this ticket! I will remove the `Mobile App - i.e. Android or iOS` as that label is only used for issues that happen in/due the mobile _apps_.

**Comment by aezazs-multidots** [comment]
Hello @minaldiwan 

I tried to reproduce this issue but I could not create any such issue.

WordPress information

- WordPress version: 5.9.2
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme:Twenty twenty two theme

and I have added the video link below.
[https://www.loom.com/share/d4255cb5315e476885071472541d9228](https://www.loom.com/share/d4255cb5315e476885071472541d9228)

Thanks

**Comment by theminaldiwan** [comment]
> Hello @minaldiwan
> 
> I tried to reproduce this issue but I could not create any such issue.
> 
> WordPress information
> 
> * WordPress version: 5.9.2
> * Are all plugins except Gutenberg deactivated? yes
> * Are you using a default theme:Twenty twenty two theme
> 
> and I have added the video link below. https://www.loom.com/share/d4255cb5315e476885071472541d9228
> 
> Thanks

Hi @aezazs-multidots 
i have again checking this issue in our local setup but same problem is happened.

**Comment by adamwoodnz** [comment]
Also not able to repro. Closing following triage policy.
