### ISSUE TITLE
Tracking: Improve development env on Windows OS

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#39388]
## Overview

I checked all scripts in `package.json`, and found that some scripts are not work correctly on Windows OS.

This tracking issue is targeted to fix npm scripts to allow for smooth development on Windows OS.

I would like to find out the detailed cause and send PR in several chunks.

I would appreciate your help in testing, both on Windows / Mac.

## Scripts that do not work on Windows OS

As far as I have tested, the following scripts did not work.

I also excluded scripts that may work correctly as a result of fix the following scripts.
( e.g. `dev`,  which depends on `dev:packages` )

| status | script name               | Error Logs / Error Details                                   | PR for  Fix |
| ------------------------- | ------------------------- | ------------------------------------------------------------ | ----------- |
| ✅ | `build:plugin-zip`        | `'.' is not recognized as an internal or external command, operable program or batch file.` |  #39739           |
| ✅ | `changelog`               | `'.' is not recognized as an internal or external command, operable program or batch file.` |     #39739        |
| ✅ | `test-unit:date`          | `'.' is not recognized as an internal or external command, operable program or batch file.` |     #39739        |
| ✅ | `test:create-block`       | `'.' is not recognized as an internal or external command, operable program or batch file.` |      #39739       |
|✅ | `check-local-changes`     | `'xargs' is not recognized as an internal or external command, operable program or batch file.` |       #41074 |
| ✅ | `dev:packages`            | File  modification not detected                              |       #40566      |
| ✅ | `lint-css / lint-css:fix` | `Error:  No files matching the pattern "'**/*.scss'" were found.` |    #39447         |
|✅  | `test-unit`               | Some tests fail with many errors                             |     #41070        |
| ✅ | `prelint-php`             | `/docker-entrypoint.sh: exec: line 24: 'install: not found`  |  #39447 |
| ✅ | `test-unit-php`           | `sudo: 'phpunit: command not found`                          |      #39447       |
| ✅ | `test-unit-php-multisite` | `×  Command failed with exit code 2`                         |    #39447         |

## What is the cause?

I think that one of the following is the cause.

- The path separator is not handled correctly
(e.g. #38326, #37189).
- unix command is used
(e.g. `xargs`)
- Single quotes are used in script commands.
(e.g. `phpunit` command is prefixed with a single quote)

**Comment by gziolo** [comment]
This is a great initiative. Thank you for opening this issue.

**Comment by gziolo** [comment]
I landed the first batch of changes. I tested them from the `trunk` branch on macOS to ensure it still works there :)

**Comment by t-hamano** [comment]
Thanks for confirming ! I will continue to work on another task 👍

**Comment by gziolo** [comment]
We could also look at standardizing names for scripts executed with `npm run` while we test all of them. See related issue: https://github.com/WordPress/gutenberg/issues/19949.

**Comment by gziolo** [comment]
I landed #39739. There are 3 commands left from the list 🎉

**Comment by gziolo** [comment]
I have just landed changes for `check-local-changes`. Does it mean we have only `test-unit` left? 😄

**Comment by t-hamano** [comment]
Oh, I must have put in the wrong PR number.
`test-unit` is already done with #41070.

So all issues are now resolved.
If I find any new OS-related issues in the future, I would like to submit a new issue.

Thank you for your cooperation!
