### ISSUE TITLE
Handbook is not synced

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#3938]
## Issue Overview
`Documentation is automatically synced from master to the Gutenberg Documentation Website every 15 minutes.`[Source](https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md)

Some pages are not at the current master version.

Example:
Docs:
https://github.com/WordPress/gutenberg/blob/master/docs/talks.md
Handbook
https://wordpress.org/gutenberg/handbook/outreach/talks/

**Comment by youknowriad** [comment]
cc @pento

**Comment by pento** [comment]
There was an issue where that page was alternating back and forth between the current version and an old version. I suspect a cron job had got stuck looking at an old branch. ~2000 automated post revisions later, it resolved itself a few days ago. 🙃

**Comment by Soean** [comment]
Same issue now on https://wordpress.org/gutenberg/handbook/outreach/meetups/. 
Two new revisions every 15 minutes.
