### ISSUE TITLE
Editor: Publish button rendered partially off the screen

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#3939]
## Issue Overview

I spent some time testing Gutenberg version 1.9.0 on my mobile device. This is a follow-up for #3197.

## Steps to Reproduce (for bugs)

Open Gutenberg on iPhone 6s in Safari, iOS 11.0.3.

## Expected Behavior

Everything should be displayed properly on mobile.

## Current Behavior

When trying to publish a post the dropdown is partially displayed off the screen, making it really hard to use it. 

![image 2](https://user-images.githubusercontent.com/699132/32100920-14568852-bb16-11e7-8e41-9b4d91a8178a.png)

**Comment by brandonpayton** [comment]
# Current

When running an iPhone 6S on the iOS Simulator, I'm seeing the same issue but with the menu off the left hand side.

![iphone-6s-publish-dropdown](https://user-images.githubusercontent.com/530877/34232133-33517fcc-e59c-11e7-97f2-479127c2fcf7.png)

# Options

Based on the screenshots with the menu off the left and right sides, it appears the popover is too wide to be aligned with the left or right of the Publish button. Ideally, what should we be seeing?

Should we keep the same menu style but shift the box horizontally to fit in the window?

Should we expand this menu for mobile instead as seen below? Please ignore the incorrect content width.

![iphone-6s-publish-dropdown-mobile](https://user-images.githubusercontent.com/530877/34232782-2ebbcdf2-e59f-11e7-9012-5024e2e137ca.png)
