### ISSUE TITLE
Editor: Inserter's popover needs polishing

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#3940]
## Issue Overview

I spent some time testing Gutenberg version 1.9.0 on my mobile device. This is a follow-up for #3197.

## Steps to Reproduce (for bugs)

Open Gutenberg on iPhone 6s in Safari, iOS 11.0.3.

## Expected Behavior

Everything should be displayed properly on mobile.

## Current Behavior

There are 2 issues here. When you click the inserter button it takes full screen but it is cut at the top. It also seems like the block items could have less space between them.

<img width="373" alt="screen shot 2017-12-12 at 10 32 16" src="https://user-images.githubusercontent.com/699132/33877211-fb8aa3ea-df27-11e7-9ce4-f9d86c43952f.png">

It also doesn't play well with the image that is aligned.

<img width="364" alt="screen shot 2017-12-12 at 10 24 21" src="https://user-images.githubusercontent.com/699132/33876748-ad4a3ebc-df26-11e7-9a9a-bf7867d8cb00.png">

**Comment by karmatosed** [comment]
Closing this as we have issues for the inserter around now. Thanks.
