### ISSUE TITLE
Post Comments Block doesn't match front-end

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#39403]
### Description

The Post Comments block looks completely different in the editor than what it does on the front-end.

Editor:
<img width="1440" alt="screenshot_175" src="https://user-images.githubusercontent.com/2078245/158010643-f24b8984-d4e3-4791-b004-bbeaf7256537.png">

Front-end:
![Gutenberg-Post-Comments-Block](https://user-images.githubusercontent.com/2078245/158010744-880f13ac-8088-42ed-9a15-6fb42b487864.jpg)

It also makes sense that there should be a switch to display/hide the avatar, among other options.

### Step-by-step reproduction instructions

- Add Post Comments Block (to Post with existing comments)
- Save page and compare editor to front-end

### Environment info

- WP 5.9.2 (Core only, no plugin)
- Twenty Twenty-One
- macOS Monterey (12.2.1)
- Firefox 97.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by KAJALwp** [comment]
Hello @maddisondesigns, @amustaque97 

I have tried to reproduce the same issue, and yes I am also facing the same issue, with and without Gutenberg plugin.

following are the version details
WordPress:- 5.9.2
Mac OS:- Monterey 12.2.1
Chrome:- Version 99.0.4844.84 (Official Build) (arm64)
Please review from your end and let me know if there is anything.

Thank you.

**Comment by kmadhak** [comment]
Hello @maddisondesigns, @amustaque97 

I have also tried to reproduce the same issue, and I am also facing the same issue.

WordPress:- 5.9.2
Gutenberg Plugin Version: 12.5.4
Mac OS:- 12.3.1

Please review from your end and let me know if there is anything.

Thank you.

**Comment by jordesign** [comment]
Closing this issue as the Legacy Comments block has been deprecated.
