### ISSUE TITLE
Issue with block latest posts when I use a link with a highlight (inline)

### ISSUE THREAD

**Issue by hagege** [WordPress/gutenberg#39402]
### Description

When I turn for a word of linking highlight (inline) in a post, the foreground color is set. This is also completely ok and also wanted.
However, when using the Latest Posts block for linking, the background is displayed in gray, for example, with the theme twenty seventeen, if I have set that the posts should be displayed fully.
Normally the link is displayed without background color if I don't use Highlight. Even if I remove the highlight, the background is displayed gray (for Twenty Twenty Seven).

### Step-by-step reproduction instructions

1. Create a post with a link
2. One word of the link should be displayed as a highlight (inline)
3. Use the "Latest Posts" block on a page or post
4. Set the properties of the block "Latests Posts" to "Full post"

### Screenshots, screen recording, code snippet

![inline_link_latest_posts](https://user-images.githubusercontent.com/27292550/158008990-a32cac9e-a553-454d-bf89-05bf53adb8c2.jpg)
![inline_link_latest_posts_1](https://user-images.githubusercontent.com/27292550/158008988-b325ae92-e476-46e6-a67a-b79561917a26.jpg)
![inline_link_latest_posts_2](https://user-images.githubusercontent.com/27292550/158008985-cf9540d2-5622-4cd7-b149-ad5ea0642c64.jpg)

### Environment info

WordPress 5.9.2, Gutenberg 12.7.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @hagege.
I have reproduced the same problem, so I submitted a revised PR #39488.

**Comment by t-hamano** [comment]
@hagege 
Sorry for the delay in addressing this issue.

I have submitted a PR, but for a more fundamental solution, I have submitted [a ticket and a fix patch to the core](https://core.trac.wordpress.org/ticket/56391).

Therefore, I would like to close this issue.
