### ISSUE TITLE
Switching Global Style Variations

### ISSUE THREAD

**Issue by hagege** [WordPress/gutenberg#39405]
### Description

Could it be that there is an issue switching the Global Style Variations? - The first time I switch the global style variations it works. But the second time it doesn't. I can exclude browser cache problem, because I tested this in incognito mode among other things. There is also no cache plugin installed.Please have a look at the following video. Website in a local development environment (I use Laragon). Using Block Theme Twenty Twenty-Two:
https://youtu.be/CorMjJBeyY4

Next one: I just installed WordPress 5.9 with activation of the Gutenberg plugin completely new. In addition, I have only included the folder styles in the root of theme twenty twenty-two.
I also tested this again on an instance on the server to rule out that this is due to my local development environment. I had the same issues there as well.
https://youtu.be/CnA_2mr5dic

Same issue when using block theme wabi. 
It was not successful either: define('ENABLE_CACHE', false); in wp-config.php

Please also have a look at the extensive thread with @annezazu
https://app.slack.com/client/T024MFP4J/C015GUFFC00/thread/C015GUFFC00-1646572663.387679?cdn_fallback=2)

### Step-by-step reproduction instructions

1. Create a folder styles below the root folder of TT2
2. Create some global style variations (*.json)
3. Choose a global style variation (see screenhot global_style_variations_1)
4. Show Website in Frontend (see screenhot global_style_variations_1_frontend)
5. Choose another global style variation (see screenhot global_style_variations_2)
6. Show Website in frontend, but in frontend the website may be shown **in this case** with the first announced design (see screenhot global_style_variations_1_frontend)
7. Choose a global style variation 
8. Show Website in frontend, but in frontend the website is shown **in any case** with the first (or second) announced design 

### Screenshots, screen recording, code snippet

![global_style_variations_1](https://user-images.githubusercontent.com/27292550/158011842-b9a33142-0bad-40d1-9705-28f0bffada0c.jpg)
![global_style_variations_1_frontend](https://user-images.githubusercontent.com/27292550/158011840-cda05fbc-4661-48e0-84d3-f923d4ba2db0.jpg)
![global_style_variations_2](https://user-images.githubusercontent.com/27292550/158011839-cc0e63af-1230-4e77-8ced-9e993fb7e863.jpg)
![global_style_variations_1_frontend](https://user-images.githubusercontent.com/27292550/158011840-cda05fbc-4661-48e0-84d3-f923d4ba2db0.jpg)
https://youtu.be/CorMjJBeyY4
https://youtu.be/CnA_2mr5dic

### Environment info

WordPress 6.0 (latest nightly 6.0-alpha-52922), Gutenberg Latest Nightly,  WordPress Betatester, Git Updater

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Noting that I wasn't able to replicate this per the slack thread mentioned above but am keen to see if others can. Thanks so much for reporting this in such a detailed way here either way! 

cc @kjellr in case you have time to try to replicate/any insights.

**Comment by hagege** [comment]
thanks @annezazu for answer
to clarify the issue again here is a short video I created today.
![issue_global_style_variations_3](https://user-images.githubusercontent.com/27292550/160330767-4da09f58-7400-4fe5-a3d9-b37b1b2fd1a2.gif)
