### ISSUE TITLE
How to get `X-WP-TotalPages` from `getRawEntityRecords`?

### ISSUE THREAD

**Issue by zeeene** [WordPress/gutenberg#39411]
### Description

Hi there, I'm new to Gutenberg, my apologies for the off-topic.

I found the `core-data` package is handy for accessing data from the backend, So I'm trying to use `getRawEntityRecords` for fetching posts and it works out of the box. I checked the documentation but looks like it doesn't provide all the data as REST API. I would really appreciate it if someone can help me to find out these mentioned points below:

- How can I access Response Header? ( I need `X-WP-TotalPages` to display pagination )
- Is there any option to invalidate the cache of `getRawEntityRecords` manually? 

### Step-by-step reproduction instructions

-

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
Hello, there is no high-level API to use at the moment that I would be aware of, but I can share an example in the codebase where a workaround exists:

https://github.com/WordPress/gutenberg/blob/cb63e4e88af991366703f01ef5831f8ed8359e3c/packages/block-library/src/comment-template/hooks.js#L105-L119

@adamziel, it's something that would be great to integrate in the `@wordpress/core-data` package.

**Comment by Mamaduka** [comment]
I think this was resolved via #55164.

**Comment by gziolo** [comment]
@youknowriad, can you confirm?

**Comment by annezazu** [comment]
👋🏼 doing a [sweep of high priority issues](https://wordpress.slack.com/archives/C02QB2JS7/p1702996696603749) to keep the label relevant and actionable. I've removed this label as it's not clear if this is still actionable and it's stalled for quite some time. If the label needs to be added back in, go for it but please add context as to why it's still relevant and relevant to the degree of needing quick mobilization across the project to address.

**Comment by youknowriad** [comment]
Yes, this is addressed with the `getEntityRecordsTotalPages` selector.
