### ISSUE TITLE
Table Block: table cells in thead are misaligned in table and mobile

### ISSUE THREAD

**Issue by fschtn** [WordPress/gutenberg#39421]
### Description

The "Table" Block is not working properly...

I think that, if I create a table and enable the "Header section" in the "Table settings" on the Block Settings, the cells in the thead should be aligned to the cells in the tbody, but it looks like it isn't like this on any other view than desktop.

### Step-by-step reproduction instructions

1. Create a new Post
2. Insert the "Table" Block
3. Write some text inside the body of the table
4. Open the Block Settings on the right column
5. Scroll down to the "Table settings" section
6. Enable the "Header section" checkbox
7. Write some text inside the header that has been created
8. Publish the post
9. Go check the post on a mobile

### Screenshots, screen recording, code snippet

![Immagine 2022-03-14 100520](https://user-images.githubusercontent.com/18397257/158140159-fb110aa5-8db0-4ece-9e19-987896182328.png)

### Environment info

- WordPress 5.9.2
- Theme: Divi
- Desktop browser: Google Chrome 99.0.4844.51 (developer tools > simulate mobile)
- Mobile browser: Google Chrome 99.0.4844.59

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@francescosche Thanks for creating the issue.

This might be a problem with the Divi theme.

I had a go at reproducing using some of the bundled WordPress themes (Twenty Twenty Two, Twenty Twenty One, Twenty Nineteen) and didn't have this issue.

Would you be able to try using a different theme to see if you still have the issue? If it's only an issue with Divi, you may want to reach out to their support.

**Comment by fschtn** [comment]
@talldan Yes, I just tried to use the Twenty Twenty Two theme and it works smootly...

Sorry 😒😅
