### ISSUE TITLE
Editor: Categories & Tags on Page edit

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#3943]
## Issue Overview
`Categories & Tags` should not be visible on the page edit screen, because pages don't have Categories & Tags.

## Screenshots / Video
![bildschirmfoto 2017-12-12 um 10 38 32](https://user-images.githubusercontent.com/695201/33877485-cc2c30f4-df28-11e7-881f-620954030a63.png)

**Comment by tkes** [comment]
Would suggest a more general approach here.

The title "Categories & Tags" should actually match the really existing taxonomies of the current post type.

Any theme/plugin can add categories to pages or to other post types, or also remove categories and/or tags from posts.

```
function testcase_register_unregister_taxonomies() {
    // remove tags & categories from "post"
    unregister_taxonomy_for_object_type( 'post_tag', 'post' );
    unregister_taxonomy_for_object_type( 'category', 'post' );
    // add categories to "page"
    register_taxonomy_for_object_type( 'category', 'page' ); 
}
add_action( 'init', 'testcase_register_unregister_taxonomies' );
```
Side effect with above code in a WP 4.9.1 Twenty Seventeen child theme: If you **both** unregister _category_ from _post_ **and** register _category_ to _page_ as in above example, it crashes Gutenberg 1.9 if editing a post or page, wtf? If only unregister **or** only register, no error...
