### ISSUE TITLE
Cannot select inner blocks in the Comments Query Loop block

### ISSUE THREAD

**Issue by michalczaplinski** [WordPress/gutenberg#39443]
### Description

Comments Query Loop block contains inner blocks like Comment Content, Comment Date, etc.

It is currently not possible to select those blocks after inserting the Comments Query Loop.

### Step-by-step reproduction instructions

1. Insert a new Comments Query Loop block.
2. Click on one of it's inner blocks like Comment Date.
3. The inner block does not get selected.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/5417266/158282398-bc2ce8f3-3112-4067-844f-6fe36dff94f4.mov

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by theminaldiwan** [comment]
Hi @michalczaplinski 
In which version of theme did you getting this issue and which theme activated?

**Comment by michalczaplinski** [comment]
Hi @theminaldiwan 👋 

This is appearing in WP 5.9.2 + Gutenberg 12.7. I'm using the Twenty TwentyTwo Theme, but the same problem appears in any FSE theme.

I'm actively working on fixing this issue at the moment.

**Comment by michalczaplinski** [comment]
This will be fixed in https://github.com/WordPress/gutenberg/pull/39472
