### ISSUE TITLE
Site editor - "wp_template" post meta

### ISSUE THREAD

**Issue by ihdk** [WordPress/gutenberg#39451]
### Description

Hello, first of all, I am sorry if it's not an issue that would be posted here as I am not absolutely sure if it's intended to work the way I expect.

For Pages or Posts we can create settings panel using `<PluginDocumentSettingPanel>` component to render wanted settings in editor and save them as post meta.
I am wonder if it's possible to do something like that in Site Editor while we are editing page template. For example (like on attached screenshot), while I am editing template for Single post, I'd like to have settings panel on the right side of editor to set some custom settings and store data as post meta of currently edited `wp_template` post Single.
Saved post meta for Single post template then can be used on all Single pages.

Using `@wordpress/edit-site` module It looks like there is no way to add settings panel using component `<PluginDocumentSettingPanel>`.
Could you please point me to right direction if it's possible to add settings in site editor?

Thank you for help and clarification.

### Step-by-step reproduction instructions

1. Add settings panel into Site Editor while template is edited.

### Screenshots, screen recording, code snippet

![2022-03-15_09-59-08](https://user-images.githubusercontent.com/36090254/158342503-4a6704ca-a244-40e1-954f-2a7af9c522e0.png)

### Environment info

- Latest version of WP
- Gutenberg plugin not installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tellthemachines** [comment]
Hi, I can confirm this is the right place to post that issue :)

I'm afraid we don't currently have a slot that allows for inserting panels in the Template sidebar. To add any type of panels to the site editor, you'd have to create your own sidebar with `<PluginSidebar>`.

I'm going to tag this as a feature request for a new `<PluginTemplateSettingPanel>` and see if we can get some feedback on it.

**Comment by youknowriad** [comment]
This is now possible. See https://make.wordpress.org/core/2024/06/18/editor-unified-extensibility-apis-in-6-6/
