### ISSUE TITLE
Right-align small images pinned to top-left of boxblock

### ISSUE THREAD

**Issue by GaryJones** [WordPress/gutenberg#3945]
GB 1.9.0

## Issue Overview
Images are pinned to the top-left of their containing blocks, even when set as right-aligned.

## Steps to Reproduce (for bugs)
1. Open demo content.
2. Resize an image to be smaller than the width of the image toolbar.
3. Right align image.
4. Toggle between selecting the image and not.

Notice the jumping image.

## Expected Behavior
If an image is right-aligned, keep the image pinned to the top right of it's container when the container needs to stay wide enough to allow for all of the tools.

## Current Behavior
Toggling selection of small right-aligned images gives a jarring jump, compared to small left-aligned images.

## Possible Solution
Pin right-aligned images to the right side of it's container.

## Screenshots / Video
![gb-right-aligned-jump](https://user-images.githubusercontent.com/88371/33883687-9523c9da-df34-11e7-8c8a-f09cb8e85145.gif)

## Related Issues and/or PRs
This issue is probably a more fundamental version of #3944 which reports on lack of pinning to the right of right-aligned images when resizing.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by harsh-barach** [comment]
@karmatosed @danielbachhuber @mtias @GaryJones I have solved the issue. ( https://github.com/WordPress/gutenberg/pull/5164 )
