### ISSUE TITLE
Partial multi selection: copy should only copy selected text

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#39455]
### Description

Follow up to #38892.

When you partially select, only the selected text should be copied, not the blocks as a whole.

### Step-by-step reproduction instructions

Partially select some paragraphs, then copy (Cmd+C).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I was going to open a new issue when I found this one. It seems as though multi-select is broken and it matches what is described here. I'm using WordPress 6.0 Beta 1 and TT2: 

https://user-images.githubusercontent.com/26996883/163079902-a09dc8c9-5e37-41b2-9df9-6d34eacd4dfe.mov

Going to add this to the 6.0 board as this seems important to resolve as it currently seems to break the multi-select functionality.
