### ISSUE TITLE
Reusable Heading changes font size

### ISSUE THREAD

**Issue by GaryJones** [WordPress/gutenberg#3946]
GB 1.9.0

## Issue Overview
Making a heading block into a reusable block changes the font size.

## Steps to Reproduce (for bugs)
1. Open demo content.
2. Make a heading into a reusable block via top-right block menu

## Expected Behavior
Font size should stay the same.

## Current Behavior
Font size seems to get smaller.

Also, shows the small size when a new instance of the reusable block is added in.

## Possible Solution
Possible a CSS selector issue?

## Screenshots / Video
![Animation showing reusable heading block getting smaller font size](https://user-images.githubusercontent.com/88371/33884161-8a264b6e-df36-11e7-83f8-bbf2f9b4fb82.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by afercia** [comment]
Yep seems heading blocks get their font size from CSS selectors tied to the block type, e.g.:
```
.editor-block-list__block[data-type="core/heading"] h2 {
    font-size: 1.6em;
}
```

so, once the block changes type, the original font size is gone.
