### ISSUE TITLE
Exported JSON loses 'appearanceTools' abstraction

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#39464]
### Description

When exporting the theme from the FSE the included theme.json is missing the appearanceTools attribute present in the theme's theme.json file and instead the attributes that abstracts are added instead. 

Missing attribute present in original theme.json:
`settings.appearanceTools`

Among added attributes:
`settings.color.custom`
`settings.color.customGradient`
`settings.color.link`
`settings.spacing.padding`
`settings.spacing.blockGap`
`settings.spacing.margin`

I expect this is because the "appearanceTools" attribute is flipping all of those values "true" without the need to provide them.  However it may be desirable to keep the original attribute in exported configuration so that if any additional attributes are enabled due to that value they are also included in the theme.

### Step-by-step reproduction instructions

Activate a theme that defines `settings.appearanceTools: true` in the theme.json file.
Export that theme from the FSE using the `hamburgerMenu>TOOLS>Export` tool.
Compare the theme.json exported to the theme.json provided by the theme.  Note that `appearanceTools` setting is absent while the values it represents are present.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by scruffian** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/39590
