### ISSUE TITLE
[Query loop block] Display an option to "Replace"

### ISSUE THREAD

**Issue by davipontesblog** [WordPress/gutenberg#39466]
### What

When accessing a template with the Query loop block already in place, there is no “Replace” option to pick different layouts, only “List” and “Grid” options. This makes the user need to remove and re-add to get more layout options. In contrast, the template parts Header and Footer show the "Replace" option in the block toolbar when selected.

<img width="699" alt="Screen Shot 2022-03-02 at 15 22 40" src="https://user-images.githubusercontent.com/31009008/156424252-8c6cfd39-11dc-404d-9ddd-602173996c9c.png">

### Why

To make it easier for users to choose a layout from the existing options available in the block:

<img width="762" alt="Screen Shot 2022-03-02 at 15 24 16" src="https://user-images.githubusercontent.com/31009008/156424463-c6d7ee4a-cc60-459c-8eb4-e267ad671e01.png">

**Comment by lwangdu** [comment]
You can click on  the "Start blank" or "Choose" blue button above right side of screen. So you can see different layout options.

**Comment by davipontesblog** [comment]
> You can click on the "Start blank" or "Choose" blue button above right side of screen. So you can see different layout options.

Hi @iwangdu 👋  The "Start blank" or "Choose" are only there when the block is first inserted - on a Pattern, or any theme default content already placed in the editor the option is no longer visible/accessible. Here is an example with the default Twenty Twenty-Two theme's home page patterns:

<img width="1711" alt="Screen Shot on 2022-03-16 at 12-02-34" src="https://user-images.githubusercontent.com/31009008/158621568-e254875f-9c60-4ea0-9d0c-0953a5e78e9a.png">

**Comment by lwangdu** [comment]
If you uncheck "inherit default layout toggle button" on right sidebar, you can see all options.

**Comment by mauriac** [comment]
@lwangdu when I uncheck the setup pattern does not get back. 
<img width="640" alt="Screenshot at Mar 18 21-59-36" src="https://user-images.githubusercontent.com/41555145/159082768-8ef9d6bf-1a42-4087-97f1-02204bdd7253.png">

<img width="640" alt="Screenshot at Mar 18 22-00-38" src="https://user-images.githubusercontent.com/41555145/159082776-c73917b5-4528-41d6-94ac-02e8d3cf7a0d.png">
if it's work on your side please let us know by providing may be a screenshot. thanks.

**Comment by paaljoachim** [comment]
Does this PR by @jorgefilipecosta cover the needs in this issue?

Update query block creation and replacement flows
https://github.com/WordPress/gutenberg/pull/38997

**Comment by jorgefilipecosta** [comment]
Yes, https://github.com/WordPress/gutenberg/pull/38997 should address this issue.

**Comment by priethor** [comment]
Fixed in #38997 since [Gutenberg 13.0](https://make.wordpress.org/core/2022/04/14/whats-new-in-gutenberg-13-0-14-april/).
