### ISSUE TITLE
Some RTL problems

### ISSUE THREAD

**Issue by DaNTaF** [WordPress/gutenberg#39465]
### Description

Hey
there is a bug in RTL language
there is no option to pic color or edit/paste color code.

### Step-by-step reproduction instructions

Selected text background color

### Screenshots, screen recording, code snippet

https://i.imgur.com/q2lcQd8.png

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/39106. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in that issue.
