### ISSUE TITLE
`PluginMoreMenuItem` implementation does not render `MenuItem` as expected

### ISSUE THREAD

**Issue by AnthonyLedesma** [WordPress/gutenberg#39474]
### Description

Using the following implementation - I expect the plugin menu item to be rendered as a [`MenuItem`](https://github.com/WordPress/gutenberg/tree/1da217e8a57803e2c9183316cdef3d09c618ffcb/packages/components/src/menu-item) as [indicated in the docs](https://github.com/WordPress/gutenberg/blob/8001881edc6236959bd83e3e8b1b47fd0bb967c7/packages/edit-post/README.md#pluginmoremenuitem) for the props.other declaration. Unfortunately, this approach is rendering only a basic `Button` dom element which seems to be the default for the `ActionItem` component.

```javascript
import { PluginMoreMenuItem } from '@wordpress/edit-post';

...
	return (
		<>
			<PluginMoreMenuItem onClick={ openModal }>
				{ __( 'Editor settings', 'coblocks' ) }
			</PluginMoreMenuItem>
			...
		</>
		)
```

I've found an alternate route that allows us to insert MenuItem components using the following:

```javascript
/**
 * WordPress dependencies
 */
import { ActionItem } from '@wordpress/interface';
import { compose } from '@wordpress/compose';
import { MenuItem } from '@wordpress/components';
import { withPluginContext } from '@wordpress/plugins';

export default compose(
	withPluginContext( ( context, ownProps ) => {
		return {
			as: MenuItem,
			icon: ownProps.icon || context.icon,
			name: 'core/edit-post/plugin-more-menu',
		};
	} )
)( ActionItem );

```

_By being able to use the `MenuItem` we gain the benefits of existing work done to handle aria attributes for example among other benefits such as styling consistency._ 

**Here are a few helpful links to the related codebase.** 
https://github.com/WordPress/gutenberg/blob/8001881edc6236959bd83e3e8b1b47fd0bb967c7/packages/edit-post/src/components/header/plugin-more-menu-item/index.js#L66-L69

https://github.com/WordPress/gutenberg/blob/58d74b6003337350200029299b3042b594d2a6f6/packages/interface/src/components/complementary-area-more-menu-item/index.js#L18-L28 (Show MenuItem implementation)
### Step-by-step reproduction instructions

This is a code related bug and is reproducible with the following example code

```javascript
import { PluginMoreMenuItem } from '@wordpress/edit-post';

...
	return (
		<>
			<PluginMoreMenuItem onClick={ openModal }>
				{ __( 'Editor settings', 'coblocks' ) }
			</PluginMoreMenuItem>
			...
		</>
		)
```

### Screenshots, screen recording, code snippet

![PluginMoreMenuItemBug](https://user-images.githubusercontent.com/30462574/158479246-69b23313-803e-4823-900c-c4dcad754d74.png)

### Environment info

WP 5.9.2
GB N/A
CoBlocks 2.22.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@AnthonyLedesma That's a good point. Given the component is named `MenuItem` it's probably a bit deceiving that it's not rendering a menu item.

As a temporary workaround are you able to do something like this in your plugin?
```jsx
import { MenuItem } from '@wordpress/components';
import { PluginMoreMenuItem } from '@wordpress/edit-post';

...
	return (
		<>
			<PluginMoreMenuItem as={ MenuItem } onClick={ openModal }>
				{ __( 'Editor settings', 'coblocks' ) }
			</PluginMoreMenuItem>
			...
		</>
        )
```

Your proposed fix makes sense to me, is that something you'd be willing to contribute in a PR? The only change I'd make is to have `MenuItem` as the default value, but still allow `as` to be overridden by the implementor. For example:
```jsx
export default compose(
	withPluginContext( ( context, ownProps ) => {
		return {
			as: ownProps.as ?? MenuItem,
			icon: ownProps.icon || context.icon,
			name: 'core/edit-post/plugin-more-menu',
		};
	} )
)( ActionItem );
```

**Comment by AnthonyLedesma** [comment]
Good call @talldan. It looks like passing in `as={ MenuItem }` as you have proposed in your example code does the job of rendering a `MenuItem` as expected.

I can work on a PR to make that MenuItem a default unless overridden.
