### ISSUE TITLE
Styles > Add Button Color to Elements

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#39473]
## What problem does this address?
Links are generally not the same as site button colors. 

## What is your proposed solution?
Add two sections to the Styles > Elements component for Button Text & Button Background.

**Comment by paaljoachim** [comment]
Hey @bradley2083 Brad

Here is an example where I selected the individual button. Color options: Text and Background.

![Screenshot 2022-03-30 at 17 32 36](https://user-images.githubusercontent.com/5323259/160873617-f35949bc-f912-4ed3-aa56-e5e0baca08e9.jpg)

Is there something else you are thinking about?

**Comment by bradhogan** [comment]
@paaljoachim Correct.  I'm proposing a global button color that can be set in the global Styles section (still leaving the individual button customization as-is).  Right now, there are only global styles for Background, Text and Links (I think Buttons and Headings - H1,H2,etc. should be added to this list).
<img width="271" alt="Screen Shot 2022-03-30 at 9 56 11 AM" src="https://user-images.githubusercontent.com/1781226/160878578-524c729f-0789-454a-a834-7dc055fb71de.png">

**Comment by paaljoachim** [comment]
That is a very good idea @bradley2083 Bradley!
@jorgefilipecosta I believe this is an issue you might be able to take a closer look at.

**Comment by annezazu** [comment]
Wanted to note that for this would likely be a big hit with theme authors considering these [previous theme design survey results](https://make.wordpress.org/test/2021/08/17/fse-program-theme-design-survey-results/) in the FSE Outreach program. It reflects how the button block was a top item that folks customized with per block settings or styles in theme.json.

**Comment by scruffian** [comment]
I think this was achieved in https://github.com/WordPress/gutenberg/pull/40260

**Comment by paaljoachim** [comment]
Thanks for seeing this Ben @scruffian 
Here is the result in Twenty Twenty Two with the Gutenberg plugin activated.

![Screenshot 2022-09-07 at 16 58 30](https://user-images.githubusercontent.com/5323259/188911187-b5b0789f-6aca-42bf-be1a-ceca6a371ed6.jpg)
