### ISSUE TITLE
Navigation Block - it's too easy to create lots of menus

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#39489]
## What problem does this address?
I think this was always a bit of a known issue, but it'd be good to find ways to reduce the number of menus that are created in the navigation block. It's quite easy to end up in this kind of state:
![Screen Shot 2022-03-16 at 4 50 06 pm](https://user-images.githubusercontent.com/677833/158552102-b224b3da-5e18-48cd-87c4-e85aa9e57a1d.png)

At the moment there are some options that always result in menu creation:
- Inserting a pattern with a navigation block can result in a new menu being created
- A theme's default template part content can result in a new menu being created

## What is your proposed solution?
There are probably some quick wins. For example, if a pattern contains the same hard-coded menu structure as another existing menu, that existing menu could automatically be used instead of creating a new one. This would solve the issue outlined in #38157.

I think there's also something deeper the two use cases mentioned above have in common. Patterns often represent semantic areas as do Template Parts (e.g. header, footer). If a site has an existing menu that has the same semantic meaning as the pattern or template part, that menu could be used in the navigation block within that template part or pattern by default. This also optimizes the workflow for the user, as they don't have to select a menu or create a menu at all in many cases.

Related #38157, #36307

**Comment by talldan** [comment]
I'm happy to close this, I think there are a number of other issues on the subject or related subjects already.

Here's a link to the Nav block tracking issue for anyone interested in keeping up with progress - https://github.com/WordPress/gutenberg/issues/38275.

**Comment by getdave** [comment]
I think the majority of the issues with accidentally creating too many menus have been resolved. There are still some outstanding however but I rarely get to the problem you highlighted in this Issue anymore as user interaction is required in order to create synced Navigation Menus.
