### ISSUE TITLE
FSE: Not able to resize header or footer templates

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#39490]
### Description

I am not able to figure out how to resize the header or footer in site Editing when using the theme Twenty Twenty Two.

![Screenshot 2022-03-16 at 10 19 50](https://user-images.githubusercontent.com/5323259/158557710-0fdc28f7-5367-41f1-b0b5-7811c6f4861b.jpg)

I expect to be able to resize the height of the header/footer.
Setting Padding to 0 makes it smaller, but I still want it smaller.

Use case.
Creating a slim header containing the site title and navigation block.

### Step-by-step reproduction instructions

Open the Site Editor.
Resize the header or footer.

### Screenshots, screen recording, code snippet

https://youtu.be/kZDCp4uSico

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

------

One possible solution is to add settings to template parts and have height as one of the options located in the sidebar settings area when a template is selected.

**Comment by paaljoachim** [comment]
Discussed during the Open Floor of Wednesdays Core Editor Slack meeting.
https://wordpress.slack.com/archives/C02QB2JS7/p1647441596700679

@jorgefilipecosta could you add some comments to this issue?
Thanks!

**Comment by paaljoachim** [comment]
Chrome dev tools - Elements. Checking the HTML and CSS.

Notice the element.style

```
element.style {
    padding-top: var(--wp--custom--spacing--small, 1.25rem); 
    padding-bottom: var(--wp--custom--spacing--large, 8rem); 
}
```

![Screenshot 2022-03-16 at 22 18 36](https://user-images.githubusercontent.com/5323259/158692960-a3b287ca-57a4-476e-8905-7d390cd86144.jpg)

Turning off the above resulted in a much smaller header.

![Screenshot 2022-03-16 at 22 18 51](https://user-images.githubusercontent.com/5323259/158693163-ad31ea57-c3c3-44be-b9a1-9686332fe843.jpg)

The question I remain with. Why is it added and how can it be through the UI turned off?

**Comment by Andrew-Starr** [comment]
Assuming this is the page.html template with the header.html part, and it looks like it from the screenshot.

Setting the padding of the ~~inner-most~~ inner group (row) - Header > Group > Row - to zero will remove the large top and bottom padding.

There is an issue in that because TT2 defines this padding with custom values `var(--wp--custom--spacing--small, 1.25rem)` and `var(--wp--custom--spacing--large, 8rem)` and these are not recognised by the block padding UI, the padding control appears empty.
So, entering 0 will zero out the padding here.

**Comment by Andrew-Starr** [comment]
Sorry not the inner-most group. There is actually another inner group (row) containing the site logo and title. It is the row above this.

**Comment by paaljoachim** [comment]
Thanks Andrew!

I have been coloring the various areas to see what each looks like.

![Screenshot 2022-03-18 at 06 53 42](https://user-images.githubusercontent.com/5323259/158945587-aabb8c73-1058-4c67-9242-6a0357e6a525.jpg)

Adding Padding 0 to the Site title row.

![Screenshot 2022-03-18 at 06 56 26](https://user-images.githubusercontent.com/5323259/158945750-f08d0862-c7cf-4e31-9d3c-edfd93764ff9.jpg)

Adding Padding 0 to Group -> Group (as in second Group block).
![Screenshot 2022-03-18 at 06 59 10](https://user-images.githubusercontent.com/5323259/158946086-f0e647e7-763b-4976-b230-311b61257d61.jpg)

Going to the frontend:
![Screenshot 2022-03-18 at 07 00 36](https://user-images.githubusercontent.com/5323259/158946225-adf0ab29-3fa6-472e-81a1-0a4c59870127.jpg)

Aligning Site Logo to the left then checking the frontend:
![Screenshot 2022-03-18 at 07 02 21](https://user-images.githubusercontent.com/5323259/158946398-cb2769a2-5bdc-44ab-910d-07f16b68bdd2.jpg)

Removing the coloring:
![Screenshot 2022-03-18 at 07 04 01](https://user-images.githubusercontent.com/5323259/158946559-39b487f7-27fa-4f0b-871b-985863230c68.jpg)

Well it looks like I was able to remove the various padding and get a slimmer header. 
BUT it was a messy process to get there.

This really needs to be cleaned up.

**Comment by paaljoachim** [comment]
I will close this issue. As it is really about adding settings to template parts. 
But one has to resize the Group block.
