### ISSUE TITLE
Buttons block - Opening the settings hides some of the formatting buttons

### ISSUE THREAD

**Issue by geriux** [WordPress/gutenberg#39491]
## Description
While testing another feature a bug was found in the `Buttons` block on **Android** where opening the block's settings would hide some of the formatting options once the Bottom sheet is closed.

Most likely the issue is around [this code](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/button/edit.native.js#L134-L143).

## Step-by-step reproduction instructions
- Open the app
- Add a `Buttons` block
- Open the block's settings
- Dismiss the Bottom sheet

## Expected behaviour
All of the formatting options should be visible after dismissing the Bottom sheet.

## Actual behaviour
Only the link option is visible.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/4885740/158565487-12b0f671-c306-4587-b965-a3135bb41b7c.mov

## Device information
- Device: Pixel 5 (Emulator)
- Operating system: Android 12
- WordPress app version: Latest

**Comment by hypest** [comment]
Marked as `[Priority] High` as it's a regression to basic functionality for a block.
