### ISSUE TITLE
List v2: splitting/merging

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#39519]
It should be possible to split list items (use RichText's `onSplit`).
When splitting an empty list item, the list as a whole should split.

It should also be possible to merge list items (use RichText's `onMerge` and and `merge` in the block type).
It should be possible to merge a paragraph into a list, but this could be done separately as it will require #39520.

**Comment by ellatrix** [comment]
This is done. Created #39877 to refine.

**Comment by ntsekouras** [comment]
This still needs to handle merge on blocks with innerBlocks that involve RichText API. It's not working as expected right now for example if you press `Enter` on a list item with innerBlocks.

**Comment by ellatrix** [comment]
It seems to work? Let's create new issues for polish it.

**Comment by ellatrix** [comment]
Opened #42499.

**Comment by htmgarcia** [comment]
> This still needs to handle merge on blocks with innerBlocks that involve RichText API. It's not working as expected right now for example if you press `Enter` on a list item with innerBlocks.

@ntsekouras I'm curious if there are any docs explaining how to add this behavior to innerBlocks: insert a new block when pressing enter
