### ISSUE TITLE
Need to add text color setting for post template pagination

### ISSUE THREAD

**Issue by theminaldiwan** [WordPress/gutenberg#39544]
## What problem does this address?
Need to add text color setting for post template pagination.Because there is only background color setting are given.if anybody wants to change text color of pagination then at that there is need for text color panel setting.

## What is your proposed solution?
Need to add color panel setting

<img width="1377" alt="pagination-screenshot" src="https://user-images.githubusercontent.com/38693713/158797779-68409c54-d38b-4fd8-ad3b-13c135ba25b5.png">

**Comment by carolinan** [comment]
Hi
You can change the text and link color by selecting the parent block (Pagination).

**Comment by kathrynwp** [comment]
As @carolinan mentioned, selecting the parent Pagination block gives you options to change the foreground, background, and link colour. I think that should take care of this issue, as I can't really see a need to change the Next/Previous link colours independently.

![Editor__beta__‹_Self-hosted_Test_—_WordPress_and_nvALT_and_Slack_____comet___A8C___1_new_item_and_Calendar](https://user-images.githubusercontent.com/7662449/192579106-3e6a0569-b893-4067-be87-d8aa47265d96.jpg)
