### ISSUE TITLE
Bug: Author role can't see image sizes drop-down on images uploaded by someone else

### ISSUE THREAD

**Issue by christincooper** [WordPress/gutenberg#39570]
### Description

Previously, I posted a [bug report](https://github.com/WordPress/gutenberg/issues/18510) on author role not being able to add a featured image uploaded by someone else: 

It was fixed [here](https://github.com/WordPress/gutenberg/pull/33567) by @Mamaduka 

However, upon investigation, it appears it is not properly resolved yet. 

Currently, users on author role can't see the image sizes drop-down on images **uploaded by someone else**:

<img width="263" alt="drop down" src="https://user-images.githubusercontent.com/51678143/158972109-ea656866-ae4d-407b-b010-cc0f253b04a5.png">

Maybe @Mamaduka or @gziolo would be interested in this one.

### Step-by-step reproduction instructions

1. As an **author** user, on the post editing screen, insert an image **uploaded by someone else**.
2. Click on the image so you focus into the image block. 
3. Now, bring your attention to the block panel on the right side. The image sizes drop down will never load up. 

### Environment info

WordPress 5.9.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for reporting the issue, @christincooper.

I will try to have a look at this next week.

**Comment by christincooper** [comment]
> Thanks for reporting the issue, @christincooper.
> 
> I will try to have a look at this next week.

Fantastic! As a sidenote, I believe there are other areas where it fails as well. For example, if the current user is an author, and we try to `.getMedia` on an image that they didn't upload, it will probably fail. You can use this to test (set `image_id` to an image the author user hasn't uploaded themselves):

`const mediainfo = wp.data.select('core').getMedia( image_id );`

I'm yet to confirm this particular issue on a vanilla installation, but I am 99% sure. And it is probably link to the bug discussed above. Fixing one should fix the other...

**Comment by Mamaduka** [comment]
I created PR for the Image block and will do an audit for other core media blocks next week.
