### ISSUE TITLE
Theme Export: Add missing schema attributes

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#39575]
### Description

The theme.json file is missing this from the original theme:

- The schema: "$schema": "https://schemas.wp.org/trunk/theme.json",
- "appearanceTools": true, inside settings

### Step-by-step reproduction instructions

1. Export a theme from the Site Editor
2. Check for the existence of the `$schema` and `appearanceTools` attributes in the `theme.json`.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by pbking** [comment]
#39464 was opened to address absent appearanceTools though $schema wasn't mentioned.

**Comment by scruffian** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/39590
