### ISSUE TITLE
Use component state data as value of createRegistry

### ISSUE THREAD

**Issue by rufus87** [WordPress/gutenberg#39578]
### Description

Hi there,

Regarding to official document [here](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#registryconsumer), `createRegistry`, `registryProvider`, `registryConsumer`, `useRegistry`, `withRegistry` are intruduced as custom implementation of React's `context API` in gutenberg, which is great: `createRegistry` method is an alternative implementation of `createContext`, `registryProvider` - of `Context.Provider` and so on. However, the value property of `registryProvider` component must be a registry created by `createRegistry` method. So, there is no possibility to pass dynamic data from one component (like component state or something else) as a value to `registryProvider`, as well as there is no possibility to pass dynamic data from component to `createContext`, which all are possible to do using react's context API.

What is the suggestion to solve this issue? 
Can you please provide an example how to implement dynamic data passing using `create registry`?

### Step-by-step reproduction instructions

1. Following code is from official documentation page at [https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#registryconsumer](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#registryconsumer)

```
import {
  RegistryProvider,
  RegistryConsumer,
  createRegistry
} from '@wordpress/data';
 
const registry = createRegistry( {} );
 
const App = ( { props } ) => {
  return <RegistryProvider value={ registry }>
    <div>Hello There</div>
    <RegistryConsumer>
      { ( registry ) => (
        <ComponentUsingRegistry
                { ...props }
              registry={ registry }
      ) }
    </RegistryConsumer>
  </RegistryProvider>
}
```

2. `const registry = createRegistry( {} );` is defined outside of `App` component.
3. There is no possibility to pass `App` component related data (like some state value) from `App` component to `ComponentUsingRegistry`

### Environment info

- WordPress version 5.9.2, Gutenberg version 12.8.0, and active theme `Twenty Twenty-Two v1.1`.
- Google Chrome Version 99.0.4844.51 (Official Build) (64-bit).
- Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
> Regarding to official document [here](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#registryconsumer), createRegistry, registryProvider, registryConsumer, useRegistry, withRegistry are intruduced as custom implementation of React's context API in gutenberg

@rufus87 Where did you read that?

Within this codebase, React's context is still commonly used.

The `wordpress/data` APIs are closer to redux, but supporting multiple named stores in a registry, which suits the way Gutenberg is divided up into packages.

**Comment by rufus87** [comment]
Hi @talldan ,

Many thanks for your answer. Based on it, we need to redux store to provide data to child components. But:

1. In case of using `<InnerBlocks />` - child blocks are not rerendered once store data is changed. 
2. Using useEffect in child block via `<InnerBlocks />` also fails, because parent block's some state value set as value for provider like `<Context.Provider value={parentStateValue}>` does not pass to child block ( only initial state value in `createContext` is available in child block)
3. Of course, it is possible to use blocks' `providesContext` attribute and use it in child block via `usesContext` but in case of complex blocks it is too hard to implement especially when it comes to bigger state structures and custom actions creators.

So the main problem are blocks rendered via `<InnerBlocks />`. It is impossible to use React commonly provided state management tools in child blocks.

What is the suggestion for this problem?

**Comment by talldan** [comment]
Are you using `useSelect` and `useDispatch` within your components to interact with the registry? Those React effects will ensure your blocks re-render any time data changes.

**Comment by rufus87** [comment]
Please look at the following example:

This is an edit function from parent block

```
const MyContext = createContext({ someKey: false });

const ParentBlockEdit = () => {
  const [state, setState] = useState(false);

  const myCustomHandler = () => {
    setState((prevState) => !prevState);
  };

  const ctxValue = {
    someKey: state,
  };

  return (
    <MyContext.Provider value={ctxValue}>
      <InnerBlocks />
      <button onClick={myCustomHandler}>Click Me</button>
    </MyContext.Provider>
  );
};
```

As you can see, once `Click Me` button is clicked, parent component's state value is switched to its opposite value. The context's provided value is an object looking like `{ someKey: TRUE | FALSE }`.

And this is an edit function from child block (a block rendered as an inner block of above parent block)
```
const InnerBlockEdit = () => {
  const { someKey } = useContext(MyContext);

  console.log(someKey); // this value is always FALSE

  return 'Hello World';
};
```

Value logged in is always false ( false - because it is the default context's value ). Provided (dynamic) value does not pass through `<InnerBlocks />`

On the other hand, if I try to use redux store instead of `useContext`, child component does not rerender once store is updated.

**Comment by talldan** [comment]
@rufus87 I took the time to implement your code and it works just fine:
![Screen Shot 2022-03-22 at 11 48 23 am](https://user-images.githubusercontent.com/677833/159404144-d0e3c848-0e0d-4f72-a3ae-36ef7b611789.png)

For my test implementation I used the buttons/button blocks. I pushed up the code in a pull request so that you can check it out and try it yourself - https://github.com/WordPress/gutenberg/pull/39624

`InnerBlocks` don't do anything special, they're rendered as React children. I'm not sure what the issue you're experiencing might be but I can assure you that context works just fine—if it didn't work, many core blocks also wouldn't work.

> On the other hand, if I try to use redux store instead of useContext, child component does not rerender once store is updated.

Again, this isn't true. Lots of the Gutenberg functionality depends on this, and there are plugins out there that also do the same. I'm happy to help you debug if you're experiencing issues.

**Comment by rufus87** [comment]
Hi @talldan ,

Many thanks for your efforts for helping me to solve described issue. I was able to fix it by using `useEffect`.

And here is a quick overview of how I did it.

I would not go into details of how to create a context provider and how to manage it state, however I am using `useState` for provider state management, but it works exactly the same if we try to implement `useReducer`

Let's assume that we already have a component `<ContextProvider>` which does following

```
const ContextProvider = (props) => {
     ...
     return <MyContext.Provider value={stateValue}>{props.children}</MyContext.Provider>
}
```

In the block edit component if we are going to use provided context's actual value we need to wrap block's `<Edit>` component into `<ContextProvider>` and this will provide possibility to grab actual context value via `useContext`

But, there is a one big problem: if there are some other blocks that are children of this block, then in parent block's `<Edit>` component  they are rendered via `<InnerBlocks>` component. But having `<InnerBlocks>` component DOESN'T mean that provided and available context from parent block will be transferred to its child blocks. So EVERY child block's `<Edit>` component MUST BE wrapped within `<ContextProvider>` and ONLY in that case child block's edit component will have access to provided context's actual (state) value using `useContext`.

This is a huge difference between how it works in pure React and how is it implemented in blocks.

**Comment by talldan** [comment]
> This is a huge difference between how it works in pure React and how is it implemented in blocks.

Everything in the block editor is implemented using normal React code. There isn't any difference. 😄

**Comment by rufus87** [comment]
@talldan , one additional question. I was able to implement what I needed using redux store or context API. However, could you please briefly explain what is `registry`, `createRegisty` and all related functionality created for and how to use it in some small example?

Thanks in advance.

**Comment by EmranAhmed** [comment]
@rufus87  I also tried to use useContext on inner block but no luck.
