### ISSUE TITLE
Block Gap: supplying a variable does not work in the view

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#39583]
### Description

If I supply a CSS variable value to the blockGap attribute for a block that supports gap, it is not respected in the view. It does in the editor.

### Step-by-step reproduction instructions

1. Using Twenty Twenty-Two, add the following markup containing a navigation and group (row) block using a CSS variable for `blockGap`: 

```
<!-- wp:navigation {"ref":160,"style":{"spacing":{"blockGap":"var(\u002d\u002dwp\u002d\u002dcustom\u002d\u002dspacing\u002d\u002dsmall)"}}} /-->

<!-- wp:group {"style":{"spacing":{"blockGap":"var(\u002d\u002dwp\u002d\u002dcustom\u002d\u002dspacing\u002d\u002dsmall)"}},"layout":{"type":"flex","allowOrientation":false}} -->
<div class="wp-block-group"><!-- wp:paragraph -->
<p>First item in the row</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Second item in the row</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

2. Check the editor, verify the variable values are respected:

<img width="1904" alt="Screen Shot 2022-03-18 at 11 03 55 AM" src="https://user-images.githubusercontent.com/5375500/159028321-ce6f7033-63a7-4d41-b738-d33db8b41c19.png">

3. Check the front-end, verify it falls back to the default blockGap value: 

<img width="1904" alt="Screen Shot 2022-03-18 at 11 03 16 AM" src="https://user-images.githubusercontent.com/5375500/159028270-6438278c-faa9-492d-97da-cd68b2741965.png">

### Environment info

- WP 5.9.2, Gutenberg `trunk`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mikachan** [comment]
I've spent some time looking at this, and I think I can see where the difference sits between how the editor handles the blockGap value and how it's output by layout based blocks.

In `lib/block-supports/layout.php`, we're using the following regex to reject certain blockGap values: `'%[\\\(&=}]|/\*%'` ([here](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/layout.php#L169)). This means that any CSS variable is disallowed (correctly, I think, from the changes in https://github.com/WordPress/gutenberg/pull/37360!)

However, the above is only applied on the front end. In the editor, it looks like the blockGap values are applied using `FlexLayoutStyle` in `packages/block-editor/src/layouts/flex.js` ([here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/layouts/flex.js#L93)), which doesn't filter the value at all.

To make this consistent, and assuming we don't want to allow CSS variables for blockGap, perhaps we should apply the same filter rule to the editor as well, within `FlexLayoutStyle`?

**Comment by andrewserong** [comment]
Support for using CSS variables for the blockGap value in block attributes was introduced across #43296 and #43466, via the form `var:preset|spacing|20` which will be output on the site frontend in the form `var(--wp--preset--spacing--20)`. For example, here's the markup for a Group block as edited in `trunk` by using the default spacing presets:

```
<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|80"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph -->
<p>A paragraph</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Another paragraph</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

I believe that resolves the issue described here, so I'll close this out. Thanks for reporting!
