### ISSUE TITLE
Inconsistent default display of link color option

### ISSUE THREAD

**Issue by luminuu** [WordPress/gutenberg#39598]
### Description

For blocks that have text and background color options, sometimes the link color option is shown by default and sometimes it's hidden behind the "View options" menu. This can be confusing for new users or even experienced users. While I do think it makes sense to hide away certain options, the link color should be available by default. 

Selection of blocks that hide the link color option by default:
- Paragraph
- List
- Group
- Row
- Query Loop
- Columns
- Column

Selection of blocks that show the link color option by default:
- Site Title
- Post Title
- Post Excerpt
- Post Date
- Pagination

### Step-by-step reproduction instructions

1. Switch to a block-based theme like Twenty Twenty-Two if not done already
2. Open the block editor or the site editor and search for one of the blocks listed above
3. If no color is explicitly set, the link color option is either hidden or shown.

### Screenshots, screen recording, code snippet

Row block:
<img width="677" alt="grafik" src="https://user-images.githubusercontent.com/7585600/159165177-0e62c28b-c74a-4de5-8d68-4d89e59ba7e9.png">

Post Title block:
<img width="677" alt="grafik" src="https://user-images.githubusercontent.com/7585600/159165213-e39f7e02-4cf4-4374-8de8-beb52837dca1.png">

### Environment info

- WordPress 5.9.2
- Gutenberg 12.8.1
- Twenty Twenty-Two 1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by theminaldiwan** [comment]
Hi @luminuu 
As we know we add only permalink for post term or navigation item or link
so here is link color option is properly given for post title block.
I think there is no confusing for anyone.

Thanks

**Comment by paaljoachim** [comment]
Good point! Thanks for adding the issue @luminuu Jessica.

@jasmussen might have some knowledge to share here.

**Comment by supernovia** [comment]
> While I do think it makes sense to hide away certain options, the link color should be available by default.

Agreed. If there were lot of other color options I could see hiding them, but link color changes are a pretty common ask.

**Comment by luminuu** [comment]
Closing this issue. I've checked the latest Gutenberg 13.9 and the mentioned blocks all have the links option now shown by default.
