### ISSUE TITLE
RangeControl: Does not support half step increments (i.e. 0.5)

### ISSUE THREAD

**Issue by metalandcoffee** [WordPress/gutenberg#39591]
### Description

I am using the RangeControl component and it doesn't support half steps (i.e. setting the `step` attribute to `0.5`)

``` 
<RangeControl
	label="Rating (0 - 10)"
	value={rating}
	onChange={onChange}
	min={minRating}
	max={maxRating}
	step={0.5}
/>
```

When I test the slider after making this update, the slider increments by 1, not by 0.5.

### Step-by-step reproduction instructions

1. Create a Gutenberg block.
2. Use the RangeControl component in your edit function and set the step attribute to 0.5.
3. Use RangleControl in Block Editor and see that it increments by 1, versus 0.5

### Environment info

- WordPress 5.9.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi, @metalandcoffee 

I have not been able to reproduce it.
Here is the code I used for the test:

```javascript
import { useState } from '@wordpress/element';
import { RangeControl } from '@wordpress/components';
import { registerBlockType } from '@wordpress/blocks';

const minRating = 0;
const maxRating = 10;

registerBlockType( 'create-block/gutenberg-test-block', {
	edit: () => {
		const [ rating, setRating ] = useState();

		const onChange = ( value ) => {
			setRating( value );
		}

		return(
			<RangeControl
				label="Rating (0 - 10)"
				value={ rating }
				onChange={ onChange }
				min={ minRating }
				max={ maxRating }
				step={ 0.5 }
			/>
		);
	},
	save: () => null,
} );
```

https://user-images.githubusercontent.com/54422211/159112241-4cb8894a-ea9e-43d2-919d-1c2c3420eadf.mp4

Could you try this code once ?

**Comment by metalandcoffee** [comment]
Hi @t-hamano ! Thank you for getting back to me. Testing your code made me realize that I had an issue with my block.

Here is my attribute:
```
attributes: {
	rating: {
		type: 'number',
		default: 0,
	},
},
```
And here is my onChange function is as follows:
```
function onChange(val) {
	setAttributes({ rating: parseInt(val) });
}
```

I was using `parseInt` to convert it from a string to a number but I missed the fact that it was converting it specifically to an integer, not a decimal point. So I updated the `onChange` function to the following and it worked: `setAttributes({ rating: parseFloat(val) });` 🎉🎉✨

![rating1](https://user-images.githubusercontent.com/20868511/159134567-11477a82-6bc7-41c4-a167-28ad7228c78a.gif)

**Comment by t-hamano** [comment]
Glad to see it resolved.
I will close this issue, so if you have any problems, please reopen or start a new issue.
