### ISSUE TITLE
Style variations: Add "Randomize" button

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#39629]
The Global Styles system has a new "style variation" system that allows you to add named copies of `theme.json` into a `styles` folder in your theme. For example, `twentytwentytwo/styles/blue.json`. These style variations are saved copies of a style configuration, meaning they can change colors, fonts, borders, radiuses, and more.

As the system gets refined, it would be interesting to leverage just how light-weight of a system this is, and showcase that through a "Randomize" button:

<img width="1600" alt="Global styles randomization" src="https://user-images.githubusercontent.com/1204802/159441108-615e47d4-6de1-4466-96fc-c77650315b6e.png">

_Note: the above mockup is missing aspects such as style-card improvements and saving custom variations. That's not an intentional omission, it'll be added when those solidify. See also #38333._

The button would not randomize _every_ property available, it would randomize a select few, such as:

* Background, text and link colors
* Font of paragraphs and headings

That could be a good starting point, and then we could expand the list once that feels solid, for example to include:

* Border radius of a few select blocks, such as Image, Featured Image and Site Logo
* Default duotones
* Anything else.

Where available, theme-provided presets (colors, duotones, fonts) should be chosen by the randomizer.

A key value both in choosing which initial properties and blocks to randomize is to ensure compelling results. If randomizing a specific property doesn't yield good variations, we should leave it out. There will always be new opportunites to expand randomization.

What do you think?

**Comment by jasmussen** [comment]
CC: @vcanales as I think you've been looking into some of this stuff.

**Comment by critterverse** [comment]
Awesome!! This seems to work well locked to the bottom of the panel. Also agree that the color and typography attributes identified above would be a great place to start 🚀

**Comment by shaunandrews** [comment]
So this wouldn't randomly choose one of the existing styles, but rather create a new styles with random values for some set of properties?

I do worry this would preset bad combinations more often than good ones, but could see it being a fun way to find a starting point for further tweaking.

I imagine a "Randomize" button wouldn't be used very often (if at all), which makes me question its existence in the UI.
