### ISSUE TITLE
More tag from classic editor displays warning in Gutenberg

### ISSUE THREAD

**Issue by bradyvercher** [WordPress/gutenberg#3963]
## Issue Overview

When opening a post with a more tag in Gutenberg that was originally created in the classic editor, a warning is displayed and block validation errors appear in the console.

## Steps to Reproduce (for bugs)

1. Create a new post in the classic editor with a more tag
2. Open the post in Gutenberg

## Expected Behavior

I expected to be able to view and edit my content without warnings.

## Screenshots / Video

<img width="750" alt="screen shot 2017-12-12 at 2 37 01 pm" src="https://user-images.githubusercontent.com/1302030/33912841-431d54fe-df4c-11e7-89f8-e96eebee08b2.png">

<img width="736" alt="screen shot 2017-12-12 at 2 39 39 pm" src="https://user-images.githubusercontent.com/1302030/33912850-492d20e0-df4c-11e7-9ddd-a33db14ffca6.png">

<img width="774" alt="screen shot 2017-12-12 at 2 54 18 pm" src="https://user-images.githubusercontent.com/1302030/33912882-64d5fec0-df4c-11e7-8967-275a17916467.png">

**Comment by danielbachhuber** [comment]
I can reproduce this issue in Gutenberg 2.0.0. When I open an existing classic editor post with `<!-- more -->` tag in Gutenberg, this is what I see:

![image](https://user-images.githubusercontent.com/36432/35167613-0965b74c-fd0b-11e7-8cc1-89d907fc5a1c.png)

**Comment by aduth** [comment]
Potentially related: #4038

**Comment by danielbachhuber** [comment]
@mcsf What was the resolution?

**Comment by mcsf** [comment]
#5061 substantially changed the way More tags are handled. There's room for refinement, but so far it seems that the current issue and its sibling #4038 no longer apply.
