### ISSUE TITLE
block.json default attributes aren't passed to PHP render callback

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#39646]
## What problem does this address?

If a block declares default attribute values like this:

https://github.com/WordPress/gutenberg/blob/3739bd76e236ff6ed5431022dbd5684fc7f93ade/packages/block-library/src/comment-author-avatar/block.json#L11-L18

...then it doesn't seem like it should have to duplicate them in the PHP logic like this:

https://github.com/WordPress/gutenberg/blob/3739bd76e236ff6ed5431022dbd5684fc7f93ade/packages/block-library/src/comment-author-avatar/index.php#L44-L45

That clutters the code with unnecessary ternary conditions, and creates opportunities for the hardcoded "default" value in PHP to get out of sync w/ the canonical value in `block.json`.

## What is your proposed solution?

I'd expect `$attributes` to contain all of the values from `block.json`, with their default values or the overriding value passed from the caller. That way you could always just use `$attributes['width']` without anything extra.

Doing that now might break back-compat, though, since 3rd-party blocks have code that depends on the current behavior, like `isset( $attributes['foo'] ) { ... }`.

So maybe the compromise would be to provide something like `$block->default_attributes`, so that devs could do something like `$foo = $attributes['foo'] ?? $block->default_attributes['foo'];`. That wouldn't de-clutter code, but would at least make sure the canonical value is always used.

**Comment by gziolo** [comment]
> That clutters the code with unnecessary ternary conditions, and creates opportunities for the hardcoded "default" value in PHP to get out of sync w/ the canonical value in block.json.

Yes, it looks like an obsolete step here when the default value is provided in `block.json`. In JavaScript, the default value would get automatically set for the attribute. Maybe, it also works this way in JavaScript.

I looked through PHP tests in WP core and it looks like it works the same in PHP:

https://github.com/WordPress/wordpress-develop/blob/d7f9f4405b30be28c026e6a3162b5e0b24f9c8e4/tests/phpunit/tests/blocks/wpBlockType.php#L203-L213

In that case, those checks are redundant and the fallback will never get applied and therefore go out of sync.

**Comment by iandunn** [comment]
Doh, you're right! We weren't registering the block correctly, so `block.json` wasn't recognized. Thanks and sorry for the invalid report!
