### ISSUE TITLE
Orientation Support: Not showing consistently across editors in Row block

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#39647]
### Description

It's been reported that the orientation settings are not showing consistently. For example using the skatepark theme and adding a row block in the post editor results in orientation settings now showing at all:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/1464705/159539314-0cfa0738-634b-4330-8adf-821a154f5851.png">

Skatepark does not have anything in theme.json to hide these settings.

### Step-by-step reproduction instructions

1. Activate the skatepark theme
2. Open the site editor
3. Add a row block
4. Notice that the orientation settings are unavailable.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mtias** [comment]
The block is actually being inserted with the flag set to false in some circumstances. It also seems this should be a block / theme config not a block attribute.

```
<!-- wp:group {"layout":{"type":"flex","allowOrientation":false}} -->
<div class="wp-block-group"></div>
<!-- /wp:group -->
```

**Comment by andrewserong** [comment]
Just following up, the fix that @youknowriad put together in #39650 ensures that it's hidden in all cases for the Group / Row block — it looks like the "Transform to variation" should be used to switch orientation in this case, as the Group block needs to support floated layouts.

As of https://github.com/WordPress/gutenberg/pull/39532 the visibility of the orientation control can be set per-block at the `block.json` level.

**Comment by mtias** [comment]
@apeatling @andrewserong @youknowriad thinking a bit more about this, I think the orientation should be showing for the Row block. There's nothing inherent about rows being purely horizontal, and there's value in a vertically organized flex container that do stuff like space-between, etc. Maybe we want the name of the block to change to "Stack" or something like that for extra clarity, but I feel we are lacking that option and Group on its own doesn't provide it, so the transform to variation menu doesn't make much sense.

**Comment by youknowriad** [comment]
@mtias I'm trying that in https://github.com/WordPress/gutenberg/pull/39690

**Comment by apeatling** [comment]
"Stack" is common across other platforms (for example interface builder for iOS), and comes without the assumption of orientation. Thumbs up for that.
