### ISSUE TITLE
Flex layout: Wrap multiple lines as default

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#39651]
### Description

With the row block and using orientation and justification in layout settings the "Allow to wrap to multiple lines" setting is set as off by default. This means the typical user experience will go like this:

https://user-images.githubusercontent.com/1464705/159545013-16a3038a-ec1a-4627-8410-671ae6574827.mov

By setting the wrap setting to on by default you'd automatically get something like this, which is I think what most users would expect:

<img width="1318" alt="image (1)" src="https://user-images.githubusercontent.com/1464705/159545146-fba755ae-c273-4fc4-b071-7be425a6f599.png">

Let's default this setting to on.

**Comment by youknowriad** [comment]
> Let's default this setting to on.

I think this means that we should also add a "column" variation to the "group" block. Changing the orientation of a row block should be the same as "transforming it to a column variation"

**Comment by glendaviesnz** [comment]
`Allow to wrap to mulitple lines` is set to on by default for me when adding a Row:

https://user-images.githubusercontent.com/3629020/159827429-7952f71d-077b-446a-9634-9692832c418b.mp4

Which [matches with the code](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/layouts/flex.js#L214). 

I wonder why it is showing off by default for you?

**Comment by apeatling** [comment]
This was straight from @mtias's report. I've tested this and can confirm it's turned on by default both in the post and site editor, with the Skatepark theme being used.

**Comment by mtias** [comment]
Interesting, not sure what happened there.

**Comment by apeatling** [comment]
Tested this again because it didn't make sense to me.

The problem is "wrap to multiple lines" is **on** by default not _off_ by default on the row block:

![2022-03-30 10 20 28](https://user-images.githubusercontent.com/1464705/160894419-eae0bbc1-9b9d-469e-83a6-37faa44ee673.gif)

When turned on, it is allowing wrapping of child blocks in the row. That's nothing to do with a paragraph child block wrapping text to multiple lines because of restricted space.

So -- this setting turned **_off_** by default actually provides the outcome you would expect with a row block, where child blocks stay on a single line.

**Comment by mtias** [comment]
Ah, good catch, that's what I had in mind — the behaviour where things fit on a single line by default, which is what you'd expect most often when choosing a Row. Otherwise if you have any line of text that is slightly long it'd seem like it's not working properly. Thanks for looking back :D

**Comment by youknowriad** [comment]
If we do change the behavior here. Let's make sure we don't regress on other blocks using "flex" where the "off" by default might not be the right call. (Navigation, buttons, social links, maybe others)
