### ISSUE TITLE
Metabox does not appear when $context parameter is omitted

### ISSUE THREAD

**Issue by ernilambar** [WordPress/gutenberg#3966]
## Issue Overview
Metabox does not appear when `$context` parameter is omitted in `add_meta_box()`

## Steps to Reproduce
```
add_meta_box(
	'theme-settings',
	esc_html__( 'Theme Settings', 'construction-base' ),
	'construction_base_render_theme_settings_metabox',
	'page'
);
```
Metabox wont appear in edit screen.
But this will work (when I pass `normal` value for `$context`).
```
add_meta_box(
	'theme-settings',
	esc_html__( 'Theme Settings', 'construction-base' ),
	'construction_base_render_theme_settings_metabox',
	'page',
	'normal'
);
```

**Comment by gonzomir** [comment]
For me meta boxes show only when the context is `normal`, `advanced` also doesn't work. I couldn't find the reason why even after digging into the code, probably I was looking at the wrong place...
