### ISSUE TITLE
List View: Multi-select follow ups (de-selecting blocks, accessibility wording)

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#39671]
Following on from #39272 where multi-select support was added to the List View for shift + Home and End keys, this issue tracks a few items of feedback that didn't make it in the scope of that PR, but would be good to follow-up on and implement.

## Issues to follow up on

* [ ] Allow blocks to be de-selected via keyboard. Currently you can hold the shift key down to select blocks with the up and down arrows and the home and end keys, however it's impossible to deselect all blocks via the keyboard. Is there a keyboard shortcut or other mechanism we can add to make it easy to deselect all the blocks?
* [ ] While we're at it, should we add in CMD / CTRL + A to select all blocks?
* [ ] Having the word "link" as part of the label is probably bad practice long term. Can we add description text instead?

```
Press Enter to jump to block.
```

We don't want to confuse users by making them think these items are links, we just need to communicate to users that you can select it to jump to a block.
* [ ] Possible to evaluate markup and see if there are any redundant attributes that can be removed?
* [ ] The label text for the highlighted block is confusing when announced via a screen reader. We can update the description in [getBlockPositionDescription](https://github.com/wordpress/gutenberg/blob/798484c90081ed498430e786a031c8be59036cd4/packages/block-editor/src/components/list-view/utils.js#L11). Due to using a tree grid, the announcement includes both the block description and the row column of the grid, which can be confusing. For example the following is announced when focusing on a selected paragraph block:

```
Paragraph  selected  Block 1 of 9, Level 1  row 1  column 1
```

---

Before we open up PRs to explore these issues, it would be good to get some feedback from folks on the desired wording and behaviour.

Thanks @alexstine for the suggestions!

**Comment by alexstine** [comment]
Added a couple suggestions but everything looks good here so far.

**Comment by andrewserong** [comment]
I believe most of the work tracked in this issue is now either complete, or in progress and tracked elsewhere, e.g. in #49563.

@alexstine do you mind if I close out this issue, and consolidate follow-ups elsewhere (i.e. in #49563)? Happy to keep it open if you're still using it.

**Comment by alexstine** [comment]
Sounds good. 👍
