### ISSUE TITLE
In development  mode, view.js script inside the build in the navigation block is not loaded in the browser

### ISSUE THREAD

**Issue by Trapsta** [WordPress/gutenberg#39696]
### Description

Stumbled across this while looking at #39585. Any changes made to `gutenberg/build/block-library/blocks/navigation/view.js` are compiled into the build but not reflected on the frontend. This is because the minified and bundled script in `/wp-includes/blocks/navigation/view.min.js` is the one that is loaded in the browser instead of the updated file inside the build. 

### Step-by-step reproduction instructions

1. Run plugin in dev mode `npm run dev`
2. Open a page / post 
3. Add a navigation block
4. View the page/post on the frontend
5. Open the network tab in the dev console
6. Observe that the browser is not loading the view.js script file from the build instead it's the minified file in `/wp-includes/blocks/navigation/view.min.js` that's loaded.

### Environment info

- Wordpress 5.9.2 and Gutenberg 12.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by amustaque97** [comment]
Hi :wave:, I followed the same reproduction steps as mentioned in the issue. I found that we're loading `view.min.js` file but from a different location. New path is `gutenberg/build/block-library/blocks/navigation/view.min.js`.

Screenshot:
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/21127788/162633197-54fb584e-dff5-4f44-ae7b-e212e5dede2d.png">


If I miss something, please let me know.
cc @Trapsta  @Mamaduka

**Comment by Trapsta** [comment]
Correct, I have confirmed that this is fixed in `v13.0.0-rc.2`. Closing the ticket. Thanks @amustaque97 for checking it out
