### ISSUE TITLE
BlockPreview not loading __unstableResolvedAssets

### ISSUE THREAD

**Issue by franmastromarino** [WordPress/gutenberg#39699]
### Description

Hello

The BlockPreview is not loading the block scripts declared in the __unstableResolvedAssets.scripts setting

Is working correctly in edit site and edit post iframes

`function test( $settings ) {

	$settings['__unstableResolvedAssets']['scripts'] .= '<script id="test-script" src="./test.js"></script>';
	$settings['__unstableResolvedAssets']['styles'] .= '<link href="./test.css" id="test-style" rel="stylesheet" media="all">';

	return $settings;
}

if ( function_exists( 'get_block_editor_settings' ) ) {
	add_filter( 'block_editor_settings_all', 'test', PHP_INT_MAX );
} else {
	add_filter( 'block_editor_settings', 'test', PHP_INT_MAX );
}`

### Step-by-step reproduction instructions

1. Copy PHP code
2. Past in the functions.php of theme
3. Create <BlockPreview blocks={ blocks } viewportWidth={ 800 } />
4. Check iframe head, all <styles> are included but not the <scripts>

### Screenshots, screen recording, code snippet

https://snipboard.io/xCLZwD.jpg

### Environment info

WordPress version: 5.9.2
Gutenberg version: 12.7.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by franmastromarino** [comment]
hello mate
thanks for your feedback
however this is not the same issue, this issue is related to the embed scripts in the BlockPreview

**Comment by franmastromarino** [comment]
hi, any updates on this?

**Comment by Mamaduka** [comment]
The issue still needs technical feedback. I am removing the "Needs Testing" label.

**Comment by ellatrix** [comment]
Hi! Please, you shouldn't override the `__unstableResolvedAssets` setting, it's meant for internal use only. These are the assets generated by the WP dependency resolver. Instead, please use the `enqueue_block_assets` hook, which will now also load assets in the iframe in WP 6.3 (#49655). Or use `block.json`. See https://make.wordpress.org/core/2023/07/18/miscellaneous-editor-changes-in-wordpress-6-3/#post-editor-iframed for more information. I will close this issue, feel free to reopen or create a new issues if you're having problems with `enqueue_block_assets`. Thank you!
