### ISSUE TITLE
[Styles] Webfonts enqueued using styles JSON files are not loaded

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#39702]
Webfonts declared in custom styles json files are not enqueued. No error is thrown, but the fonts are not loaded in. 

---

To reproduce: 

1. Add a style variation to emptytheme.
2. Add font file(s)
3. Declare the font using fontFace under `settings.typography.fontFamilies`.
4. Open the Site Editor.
5. Select the variation, notice that the correct font is not loaded.

Example PR here: https://github.com/WordPress/theme-experiments/pull/304

In the PR example, the same code works properly when pasted into `theme.json` instead of `styles/variation.json`. 

--- 

Screenshots:

![styles](https://user-images.githubusercontent.com/1202812/159760665-5e7f12f7-e1e0-4702-bfbb-fe9dd46fb6af.gif)

The correct font for the variation should be DM Sans. Instead, the default `sans-serif` fallback is being used, and no network call to the DM Sans font files is being made.  

<img width="809" alt="Screen Shot 2022-03-23 at 1 36 47 PM" src="https://user-images.githubusercontent.com/1202812/159761581-e7baeb96-4e72-4e30-ac4e-16b371f229ff.png">

**Comment by jasmussen** [comment]
@youknowriad @aristath @jorgefilipecosta have you worked with fonts, or have an idea what might be up here?

**Comment by youknowriad** [comment]
I guess we only load the fonts that are on the main theme.json and not the variations. It's going to be important to solve this in a way that lazy-loads these fonts. (In case variations will come from a directory later)

**Comment by aristath** [comment]
huh... tbh I wasn't even aware of the existence of `variation.json` files! 😬 
Where do we parse these? I can't seem to find any reference to `variation.json` in Gutenberg's code 👀

**Comment by kjellr** [comment]
👋 @aristath style variations were implemented over in https://github.com/WordPress/gutenberg/pull/35619

**Comment by aristath** [comment]
Thank you for the additional context @kjellr 👍 
I added a PR for this in https://github.com/WordPress/gutenberg/pull/39886
