### ISSUE TITLE
Add google maps as an embed

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3970]
This is a user request from the forums: https://wordpress.org/support/topic/great-new-tool/#post-9765086

**Comment by overclokk** [comment]
Maybe this is better in plugins and not in core bacause gmaps has a lot of customizations.

**Comment by aduth** [comment]
Related: #315

**Comment by iseulde** [comment]
We can do this without API keys or oEmbed. #4660 semi addresses this, but in addition to that we could create a proper embed block for Google maps where the user can paste the iframe embed code and the block just saves the iframe attributes and URL. A content filter could put this into an iframe similar to the way oEmbed works, so in other words, the Google Maps domain would be whitelisted to use iframes.

**Comment by iseulde** [comment]
Anything other than the iframe embed code would be plugin material though.

**Comment by mtias** [comment]
Duplicate of https://github.com/WordPress/gutenberg/issues/315.
