### ISSUE TITLE
Notifications should always display on the screen for saving and updating

### ISSUE THREAD

**Issue by davidlaietta** [WordPress/gutenberg#3971]
## Issue Overview
When a post is edited in Gutenberg and a draft is saved, published, or a published post is updated, a notification appears at the top of the post informing if it has successfully posted or has failed.

When a post is long enough that the top of the post is no longer visible on the screen this notification is still produced, but it occurs offscreen.

This could result in users saving a draft, believing that they have successfully saved, then closing the browser and losing work if there was an error.

## Steps to Reproduce (for bugs)
1. Create a draft post that is longer than the height of your browser
2. Save or update that post to get a success or failure notification

## Possible Solution
Make the notifications fixed, or place them outside of the flow of the document editor.

## Screenshots

<img width="882" alt="screenshot 2017-12-13 08 39 43" src="https://user-images.githubusercontent.com/1971070/33941736-9432ec38-dfe1-11e7-8f89-bd9786295345.png">
<img width="839" alt="screenshot 2017-12-13 08 40 03" src="https://user-images.githubusercontent.com/1971070/33941737-9447ef7a-dfe1-11e7-9347-169713a16746.png">

**Comment by karmatosed** [comment]
I agree that notifications should be always visible and that was the intent.. you've found a bug! Thanks for testing and let's get that fixed.

**Comment by jorgefilipecosta** [comment]
With the merge of https://github.com/WordPress/gutenberg/pull/4130, this should be fixed.Thank you for reporting this 👍
