### ISSUE TITLE
Playwright config path issue in Git Bash on Windows

### ISSUE THREAD

**Issue by sandeshjangam** [WordPress/gutenberg#39721]
### Description

Here is an error message.
`Error: Cannot find module '/C:/Users/Sandesh/Local%20Sites/gutenberg/app/public/wp-content/plugins/gutenberg/test/e2e/config/global-setup.ts'`

Full screenshot

![a6818792-507d-4111-9205-b540cc3dce21](https://user-images.githubusercontent.com/15683894/159926154-43a7061c-9a30-4e18-a44b-f988080e077d.jpg)

--------------------
Quick fix  - I have changed 2 lines in  `gutenberg\test\e2e\playwright.config.ts` to fix it temporary

`testDir: new URL( './specs', 'file:' + __filename ).pathname,` => `testDir: './specs',`

`globalSetup: new URL( './config/global-setup.ts', 'file:' + __filename ).pathname,` => `globalSetup: './config/global-setup.ts',`

### Step-by-step reproduction instructions

1. Start test env
2. Run `npm run test-e2e:playwright`
3. You will face this issue in Git Bash on windows

### Environment info

- Laptop with Windows 10
- Git Bash
- Node 14.16

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @sandeshjangam.

I'm Windows (11) user too, so I will test to see if it reproduces.
If it turns out to be a problem specific to WindwosOS, I would like to submit a PR for a fix.

**Comment by t-hamano** [comment]
Hi @sandeshjangam.

I found the cause and submitted a PR #39765.
If possible, could you check out the `e2e/playwright-cross-platform` branch and see if it works properly in your environment?
