### ISSUE TITLE
[RNMobile] Numbered list crashes with very large 

### ISSUE THREAD

**Issue by jhnstn** [WordPress/gutenberg#39727]
## Description

Adding a very large starting number to an numbered list crashes the editor. (cc @twstokes )

## Step-by-step reproduction instructions

1. Add a numbered list to a post
2. Open the block settings
3. Enter a very large number as the start value e.g. 10000000000 

## Expected behaviour

The editor should not crash.

## Actual behaviour

The editor crashes

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/744755/159963440-5fbafdb3-8ced-493f-b06a-9ea419515a4e.mp4

## WordPress information
- Gutenberg version: 1.72.0

## Device information
- Device: Pixel 6
- Operating system: Android 12
- WordPress app version: WPAndroid 19.5-rc-1

**Comment by jhnstn** [comment]
@hypest Looks like this is an integer overflow issue. Give `2147483647`(`(2^31)-1`) a try and it works, add 1 to get `2147483648` and 💥 
The error is [from this `toInt()` call](https://github.com/wordpress-mobile/AztecEditor-Android/blob/trunk/aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecOrderedListSpan.kt#L85) in Aztec.

2^31 works fine on an iPhone, guessing since they are 64bit. The UI does get a little weird at 1e+20 but the editor doesn't crash. It just resets back to 1.

**Comment by Thelmachido** [comment]
Hi @jhnstn there hasn't been much activity lately on this issue or the PR, just popping in to check if there’s still a plan to move this forward.

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub and just wanted to follow up on @Thelmachido's last comment. Any updates on the progress of the linked PR?

**Comment by jhnstn** [comment]
The linked PR was put on hold for higher priority work. I plan on picking it back up this week to clear this issue.

**Comment by Thelmachido** [comment]
Hi @jhnstn any plans for moving this forward?

**Comment by jhnstn** [comment]
Hi @Thelmachido yes, I was able to review the work done so far but haven't been able to make some requested updates. I should have time next week to look into it.

**Comment by jhnstn** [comment]
This issue is no longer reproducible. I suspect the move to [Android 12](https://github.com/wordpress-mobile/AztecEditor-Android/issues/1003) had something to do with the fix.
