### ISSUE TITLE
In Multi Purpose Block , under wrapper Tag settings two buttons not looks proper

### ISSUE THREAD

**Issue by RehanAlicharolia** [WordPress/gutenberg#39741]
### Description

In Multi Purpose Block , under wrapper Tag settings two buttons sticks to each other no spacing found.
Need to add some spacing between two buttons....

### Step-by-step reproduction instructions

1. Added Multipurpose Block in a page.
2. Click on wrapper tag settings
3. under wrapper tag settings , you will see two buttons (Header,Section)

### Screenshots, screen recording, code snippet

https://tinyurl.com/ycfq3cmk

### Environment info

- WordPress version: 5.9.2

- Are all plugins except Gutenberg deactivated? yes

- Are you using a default theme:Twenty twenty two theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @RehanAlicharolia

The "Multipurpose Block" isn't a core block. Please reach out to the plugin support - https://wordpress.org/support/plugin/multipurpose-block/
