### ISSUE TITLE
Avatar block alignment is not displaying correctly in the editors

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#39740]
### Description

When an avatar block is placed in the post editor, align center does not work in the editor, only on the front.
Left and right works correctly.

When the block is placed in the site editor inside a container block (group, or post template) no alignments work in the editor, all alignments work on the front.

### Step-by-step reproduction instructions

1. Create a new post or page.
2. Add an avatar block. Duplicate the block and change the alignment in the toolbar until you have one of each alignment.
3. Compare the position of the block in the editor and front.
4. Open the site Editor ( Appearance> Editor) 
5. Add a container block, -we need this container to enable the alignment options.
6. Repeat step 2 and 3.

### Environment info

Gutenberg current trunk
WordPress 5.9.2.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by HILAYTRIVEDI** [comment]
Hi @carolinan, I am not able to find this block. Can you please tell me where I can find it?

**Comment by carolinan** [comment]
It is available in the development version of Gutenberg.
https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/avatar

**Comment by HILAYTRIVEDI** [comment]
#39794 this is the PR that can fix this issue.

**Comment by carolinan** [comment]
I am closing this issue since it has been solved. Thank you.
