### ISSUE TITLE
gallery block spacing changes the size of images and ignores the column setting

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#39778]
### Description

With Gutenberg trunk, if you add a value to the block spacing setting in the gallery block, the size of the images change.
Instead of fitting the images inside the columns set in the gallery, the image size is drastically changed and the images are displayed one by one, vertically. The effect is the same no matter the number of columns that are set, or the image size.

### Step-by-step reproduction instructions

Test with a theme with support for blockGap.

1. Open the block editor
2. Add a gallery block with images
3. try to use the block spacing setting

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/7422055/160227304-0144f2c2-57af-4dc0-b0b9-cc1098d91f17.mp4

### Environment info

WordPress 5.9.2
Gutenberg trunk ( at https://github.com/WordPress/gutenberg/commit/41325b983feabcc46615cd6b1a8a5efe64c5a9f0)
Chrome, Windows 10, multiple block themes

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
@glendaviesnz 
As I continued testing this, I found a PHP warning in the editor. I am using PHP 7.4.1.
`Warning: preg_match() expects parameter 2 to be string, array given in gutenberg\build\block-library\blocks\gallery.php on line 51`

[Line 51](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/gallery/index.php#L51)

(-I did a dump of `$gap` and it is an array containing both the top and left spacing values.)

**Comment by ramonjd** [comment]
Looks like https://github.com/WordPress/gutenberg/commit/ce74a0d4924e34f6ca146834e4a5e52d148bb07b borked things. I'm looking into getting a fix in today. Thanks for flagging @carolinan and @glendaviesnz
