### ISSUE TITLE
Full site editing: Template set for a blog archive page is "Home" while it could be "Archive"

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#39785]
(Prefacing this report by saying it's more of a question than a bug; is the current behavior expected?)

### Description

On a site with Full Site Editing enabled, a page that's marked as the blog archive gets the "Home" template instead of the "Archive" template. The latter is ideal because it's an archive page designed to show blog posts, and is not the homepage of the site. The homepage is an entirely different page.

### Step-by-step reproduction instructions

- Start with a WordPress website and a core theme like Twenty Twenty-Two.
- Create two pages: one for the homepage and one for the blog archive. **Don't close these pages' editor view yet**
- See that both pages have "Page" template at the moment.
- On the Customizer, click on "Homepage Settings" and set one as the homepage and the other as the blog archive page. (see image below for how it's set up)
- Refresh the editor view of the page that you just marked as the blog archive page. Notice that the template is now `Home`

<img width="409" alt="image" src="https://user-images.githubusercontent.com/18581859/160286700-04bc3417-fb7e-4f90-a35d-2909bc57587a.png">

### Screenshots, screen recording, code snippet

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/18581859/160286726-e43794d3-5df1-4f6d-9642-c172da30f4c2.png">

### Environment info

- WordPress 5.9.2
- Not using standalone Gutenberg, using Gutenberg that comes with core WordPress install.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by paaljoachim** [comment]
@jameskoster I am thinking you might have some more information regarding this issue. Thanks.

**Comment by jameskoster** [comment]
This is [expected behaviour](https://developer.wordpress.org/themes/basics/template-hierarchy/#home-page-display). I agree that it's confusing though, we should probably attempt to give the `home` template a better name. Perhaps something like "Blog" or "Blog home"?

**Comment by arunsathiya** [comment]
Thanks for that link! Makes sense why it's called `Home` now. If it's renamed to `Blog home`, that wouldn't work for a static page homepage. So, maybe `Home` is appropriate after all.

**Comment by jameskoster** [comment]
Closing this issue. I'll open a new one to discuss the name of the Home template.
