### ISSUE TITLE
Certain colors are not reflected in classic themes without theme.json

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#39783]
### Description

In classic themes without `theme.json`, certain colors are not reflected on the frontend.
This occurs when a HEX color defined in the core `theme.json` is used.

If the editor uses that custom color, the block will be given its own class name.
(e.g. `#0693e3` to `vivid-cyan-blue` class name)
However, colors are not reflected because inline styles like `.has-vivid-cyan-blue` are not generated for classic themes without `theme.json`.

This occurs when the gutenberg plugin is enabled.

### Step-by-step reproduction instructions

- Enable classic theme without theme.json ( e.g. Twenty Twenty One).
- Change paragraph text and background colors to custom color that is defined as the core color palette.
(e.g. Vivid cyan blue: `#0693e3`, Pale pink: `#f78da7`)
- Change the editor to code editor mode, and confirm that color class is added to the block attribute. 
- Save the post, and confirm that the color is not reflected on the frontend. 

(Additional)
- add blank `theme.json`  with an empty object to the active theme directory.
- Reload the browser, and confirm that the color is reflected on the frontend. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/160268797-addf32be-9f19-483d-aa61-c0d1eaa2b37f.mp4

### Environment info

- WordPress version: 5.9.2
- Gutenberg version: 12.9.0-rc.1
- Theme: Twenty Twenty One (version1.5)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
Looks like this is no longer an issue, the vivid cyan blue is rendered on the front end as shown in the video below. 

https://user-images.githubusercontent.com/41231764/190671668-269345aa-c64e-4dda-bf13-1eb8fa77d9e9.mov

WordPress 6.0.1 
Gutenberg 14.1.0
Twenty Twenty One theme

**Comment by t-hamano** [comment]
Thanks for checking, @Thelmachido !
I have confirmed that it does not reproduce in my environment too.
