### ISSUE TITLE
Master branch points 1.9.0 not 1.9.1

### ISSUE THREAD

**Issue by idpokute** [WordPress/gutenberg#3979]
## Issue Overview

Current master branch points version 1.9.0, but the latest version of the plugin in wordpress plugin directory points 1.9.1

**Comment by aduth** [comment]
The 1.9.1 release was a cherry-picking of commits from master. Specifically, the [v1.9.1 tag](https://github.com/WordPress/gutenberg/tree/v1.9.1) points to 369e94834769ec5ccf2ab7d5548c753fda1c2caf of the [release/1.9.1 branch](https://github.com/WordPress/gutenberg/compare/release/1.9.1).

It may still be sensible to merge this commit to master.

**Comment by karmatosed** [comment]
Closing as this is a known issue and something that may change later but right now isn't an issue.
