### ISSUE TITLE
Card: Add story and description to highlight `CardMedia` usage

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#39830]
## What problem does this address?

An important feature of the `CardMedia` component is that it is `overflow: hidden`, meaning that it will make its content nicely match the border-radius of its parent `Card`. This can be hard to discover for a couple reasons:

- The user is not necessarily looking to wrap "media" like images or video. Sometimes it is just content with a background color (related: the "smooth the corners" issue in #38934).
- The Storybook story for `Card` includes a usage of `CardMedia`, but it does not show rounded corners because it's placed in the middle of the card.

## What is your proposed solution?

- The non-media use case should at least be mentioned in the lede of the `CardMedia` readme.
- There should be a story that makes it obvious that by using `CardMedia`, corners will be rounded to match the `Card`.

**Comment by kathrynwp** [comment]
Heya @mirka, I'm just popping round to check whether this is still an active/planned feature, and if so, whether there's anything that can be done to move it along. Thanks for having a look! (I've left the automatically added "Needs Testing" label for now.)

**Comment by mburridge** [comment]
What needs doing here? What should be added to the [readme](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/card/card-media)? Happy to action this with some guidance from the component authors or other interested parties.

**Comment by mirka** [comment]
@mburridge Thanks for the nudge, I went ahead and added the changes in #50074.
