### ISSUE TITLE
Avatar block sidebar has some small design issues in Safari.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#39843]
### Description

<img width="296" alt="Screen Shot 2022-03-29 at 10 10 29 AM" src="https://user-images.githubusercontent.com/272444/160577183-a58973be-1353-4dd5-8250-92bc725593b1.png">

The screenshot above represents the sidebar of the "avatar" block in Safari. I see two issues there:

 - The "Dimensions" panel doesn't have the right padding. 
 - The Range Control input is not visible (probably need a flex-shrink config there)
 

### Step-by-step reproduction instructions

1- Insert an avatar block
2- Open the block inspector

### Screenshots, screen recording, code snippet

This is how it should look like (Chrome screenshot)

<img width="282" alt="Screen Shot 2022-03-29 at 10 16 06 AM" src="https://user-images.githubusercontent.com/272444/160578090-261b84d1-d063-423e-9636-c076d63c8658.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Soean** [comment]
I can't reproduce the issue. Tested in Safari 15.4 on macOS 12.3

<img width="301" alt="Bildschirmfoto 2022-03-29 um 13 06 12" src="https://user-images.githubusercontent.com/695201/160598220-8e3273c1-77c9-480e-9284-b29a3657edf5.png">

**Comment by youknowriad** [comment]
Weird, I can't reproduce either :) Thanks for checking @Soean
