### ISSUE TITLE
Embed block shows error when viewing github Gists

### ISSUE THREAD

**Issue by snovosel-godaddy** [WordPress/gutenberg#39859]
### Description

When adding a Gist to the embed block, and clicking "view raw" within the editor an error appears within the block.

### Step-by-step reproduction instructions

1. add Embed block
2. add URL for public Github Gist
3. enter
4. click "view raw"
5. view error within block

### Environment info

5.9.2 WP

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by paaljoachim** [comment]
Hi @snovosel-godaddy 

This is what I see when pasting in the URL of a Gist.
Example.  https://gist.github.com/paaljoachim/bf17215e61ab1a6af6a436ee2cd6970e
![Screenshot 2022-03-30 at 17 09 12](https://user-images.githubusercontent.com/5323259/160868620-26c7d7e2-6c21-4190-ba12-459bdf5f7cee.jpg)

There is a Trac ticket for embedding a Github Gist here:
https://core.trac.wordpress.org/ticket/41206

Btw I dug up my old e-mail and sent a reminder email to Github in regards to supporting Embedding a Gist into WordPress.

**Comment by annezazu** [comment]
Going to close this out since there's a trac issue for this :) Let me know if that's wrong - happy to reopen.
