### ISSUE TITLE
Auto select first Nav Menu in Nav block if only a single `wp_navigation` exists

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#39854]
Currently when switching to a new Theme the Nav block requires the user to select the Nav Menu they wish to use in the Nav block. This is because there is no mechanism to decide on the most "appropriate" Nav Menu to use.

In order to optimise for the 80% use case where the user has a single Navigation Menu, let's update the block to automatically use the first Navigation Menu _if_ there is only a single `wp_navigation` post.

cc @mtias @scruffian

**Comment by mtias** [comment]
To contextualize a bit more this idea, the general aim is to make the navigation renderer _just work_ with the user's stored menu. The assumption being that if there is a single menu on a site we should try to use it.

**Comment by getdave** [comment]
This Issue has been completed by https://github.com/WordPress/gutenberg/pull/42735 and others. Closing as complete.
