### ISSUE TITLE
Demo - white screen, white page

### ISSUE THREAD

**Issue by ian72** [WordPress/gutenberg#3985]
Gutenberg 1.9.1
-----------------
WordPress  4.9.1
Multisite
other plugins off

So far, this plugin has never worked in Multisite.
No version works.

**Comment by tharsheblows** [comment]
This is working for me with subdomains and subdirectories both on WP 4.9.1. Are you using the Twenty Seventeen theme? Also, are all the js files loading properly?

**Comment by youknowriad** [comment]
Als,o #4122  Just landed and it might fix some multisite issues. Would you be able to try using the master branch?
