### ISSUE TITLE
Nav Sidebar: move to left hand side "W" menu and use "dark UI"

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#39856]
In https://github.com/WordPress/gutenberg/pull/39290 we introduced the Navigation Sidebar as a dedicated UI to expose the Navigation structure outside of the block.

As per https://github.com/WordPress/gutenberg/issues/36667 we should now look to move this sidebar to the left hand sidebar and use the "dark" UI.

The latest prototype for this is in [the following Figma file](https://www.figma.com/file/phx9jrGQVR7iJV5L6rjPjy/Site-Editor-Nav-Stuff?node-id=342%3A15537).

https://user-images.githubusercontent.com/1204802/161579413-cd0ed368-3ac8-4cc2-a4d4-75c484c8f74e.mp4

**Comment by getdave** [comment]
@javierarce @SaxonF If we have more up to date designs for this now then would it be possible for you to update the Issue description and link up any Figma files? Much appreciated.

**Comment by annezazu** [comment]
Is this still relevant or can we close it out with the navigation added? https://github.com/WordPress/gutenberg/pull/46436

**Comment by getdave** [comment]
Seems like it's completed as part of the addition of Navigation to the Browse Mode for Gutenberg Plugin (though _not_ in WP 6.2).
