### ISSUE TITLE
Feature Request: Auto-Detect Hashtag for Hex code & Remove in Styles Editor

### ISSUE THREAD

**Issue by samxmunoz** [WordPress/gutenberg#39851]
**Issue**
When copying & pasting a hex code into the Styles Editor you must currently do it without the hashtag/pound sign in the beginning. It is cumbersome to remove the hashtag when copying from a tool like AdobeXD.

![Screen Shot 2022-03-29 at 8 57 19 AM](https://user-images.githubusercontent.com/43501707/160618504-753b4777-6ad7-4adb-a457-a54fc235b437.png)

**Proposed Solution**
Auto-detect that a hashtag is present when copying & pasting in and strip it to allow for pasting with or without the hashtag.

**Comment by fabiankaegy** [comment]
I believe this was already added in https://github.com/WordPress/gutenberg/pull/38335 

So it should be available in the Gutenberg plugin 12.7 or higher :)

**Comment by annezazu** [comment]
^ Can confirm this is correct. Here's a quick video showing the current flow with Gutenberg 12.9.

https://user-images.githubusercontent.com/26996883/161457881-45b49e88-f8dc-474b-bf1b-06b84c825029.mov

Going to close this out as a result! Thank you for reporting and for your first ever reported issue <3 Doing so only helps Gutenberg evolve. If you experience other issues, please continue to report them here and know it's appreciated.
