### ISSUE TITLE
Set text background highlight color, then try Edit as HTML, block gives error

### ISSUE THREAD

**Issue by andrea-calligaris** [WordPress/gutenberg#39861]
### Description

Setting the background color (using the highlight function), and then trying to edit the paragraph as HTML, gives the error:
`This block has encountered an error and cannot be previewed`
and the block is not recoverable, unless by copy pasting and removing the mark tag.
This does not happen with the foreground / actual text color.

Not the same problem of https://github.com/WordPress/gutenberg/issues/36532

### Step-by-step reproduction instructions

1. Create a new page/post or edit one.
2. Write a paragraph.
3. Try to do _Edit as HTML_. It does work.
4. Now go back to the normal visual.
5. Highlight all or part of the text with any background color.
6. Save the page or not, save and reload the page or not, doesn't matter.
7. Try again to do _Edit as HTML_ (update: while the text cursor is inside the highlighted area). It says:
`This block has encountered an error and cannot be previewed`
and it's not recoverable.

### Screenshots, screen recording, code snippet

```
<!-- wp:paragraph -->
<p><mark style="background-color:#f4ca16" class="has-inline-color">Blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah.</mark></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Another paragraph.</p>
<!-- /wp:paragraph -->
```

### Environment info

Last version 5.9.2
Tried with no plugins.
Firefox 98.0.2, 64bit.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I have tested this and I am able to replicate it. The issue also occurs with the latest version of Gutenberg. 

I do want to note that the error only occurs when the cursor is placed inside of the highlighted text prior to clicking "Edit as HTML". If you place the cursor in unhighlighted text, you are able to edit the HTML as expected. See the gif below. 

![highlight-error](https://user-images.githubusercontent.com/4832319/160715413-13e68bf7-e459-466f-9519-b5feabaa19b1.gif)

**Comment by andrea-calligaris** [comment]
@ndiego Thank you, nice to know there's a workaround. It also works if you highlight the entire paragraph but you put the cursor at the very end or the very start of it.

**Comment by andrea-calligaris** [comment]
Still relevant.

**Comment by Thelmachido** [comment]
Hi @andrea-calligaris I wasn't able to reproduce this as shown in the video below: 

https://user-images.githubusercontent.com/41231764/192802492-914a8ee4-bfe7-4bc4-942b-d75509f35760.mov

Please feel free to re-open if the steps taken to reproduce are not correct. 

WordPress 6.0.2
Gutenberg 14.1.1
