### ISSUE TITLE
Select text and apply changes: sometimes some rows/characters are left out

### ISSUE THREAD

**Issue by andrea-calligaris** [WordPress/gutenberg#39878]
### Description

Sometimes, selecting a text and then applying changes e.g. italic, doesn't apply the change to all the selected text, but a few characters at the start of the selection are left out, or entire rows are left out.

I haven't been able to find out the exact mechanism that triggers the bug, but it happens often enough (like 1 time out of 3) that it's easy to reproduce.

### Step-by-step reproduction instructions

1. Select some text
2. Apply italic
3. Sometimes some characters at the start are left out, or entire rows of text are left out; if you selected from top-left to bottom-right, it will happen at the end of the selection, otherwise vice versa.

### Screenshots, screen recording, code snippet

![selection-bug](https://user-images.githubusercontent.com/10872697/160787843-30483ad8-5e97-445f-9852-bca2e3fbb456.jpg)

### Environment info

WordPress latest 5.9.2
Firefox 98.0.2 64-bit
Ubuntu latest 64-bit

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrea-calligaris** [comment]
Still relevant.

**Comment by Thelmachido** [comment]
Hi @andrea-calligaris I am not able to reproduce this with the latest version of WP & Gutenberg as shown below: 

https://user-images.githubusercontent.com/41231764/192803485-6c8af4b2-fa4a-43ed-af88-fbd304730dcd.mov

Are you able to provide more information about your experience and your testing environment? 

WordPress 6.0.2 
Gutenberg 14.1.1
