### ISSUE TITLE
List v2: better paste handling

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#39887]
Pasting a list or other content should ideally not split the list block.

* Pasting another list block into a second list blocks should insert list items at the level they were inserted.
* Pasting a non Gutenberg list should do the same thing.
* Pasting something simple like paragraphs in a list block should probably convert the paragraphs to list items?
* Anything more complex should still split the list block.

Cc @jorgefilipecosta @mtias

**Comment by mtias** [comment]
Pasting something like:

```
- One
- Two
- Three
```

Should also respect the indent level you are currently at and not change it.

**Comment by annezazu** [comment]
This came up in the[ fourteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/04/28/fse-program-testing-call-14-rallying-recipe-reviewers/#comment-2467) with the List V2 as a requested item since part of the test included copy/pasting from a different site:

> It would be nice if I could copy and paste a list and have it automatically detect that and make it a list.

**Comment by ellatrix** [comment]
@mtias I created a [PR](https://github.com/WordPress/gutenberg/pull/42524). Indentation level is also preserved.

**Comment by mtias** [comment]
Great, thanks!
