### ISSUE TITLE
ColorPicker not updating current color value

### ISSUE THREAD

**Issue by arl1nd** [WordPress/gutenberg#39896]
### Description

I am using ColorPicker component outside the Blocks Editor and I am having an issue with it, firstly I thought it is related to me but I think the problem is related more at the component itself.

Is there any fix for this?

### Step-by-step reproduction instructions

1. Create a page or edit an existing one on WordPress admin
2. Add the following code in JavaScript Console:

````
jQuery( '.my-test-colorpicker' ).remove();
jQuery( '<div class="my-test-colorpicker" style="position: fixed; top: 50%; left: 50%; width: 300px; height: 300px; background: #fff; border: 5px solid #ccc; transform: translate(-50%,-50%);"></div>' ).appendTo( 'body' );

var myTestColorpicker = document.querySelector( '.my-test-colorpicker' );

// Init ColorPicker
var el = wp.element.createElement( wp.components.ColorPicker, {
    color: '#ff00bb',
} );

// Render
wp.element.render( el, myTestColorpicker );
````

In this case the color value is not updated on update. See the example: [https://d.pr/v/ONm7m1](https://d.pr/v/ONm7m1)

I am using this component in Customizer for your information.

### Screenshots, screen recording, code snippet

```
jQuery( '.my-test-colorpicker' ).remove();
jQuery( '<div class="my-test-colorpicker" style="position: fixed; top: 50%; left: 50%; width: 300px; height: 300px; background: #fff; border: 5px solid #ccc; transform: translate(-50%,-50%);"></div>' ).appendTo( 'body' );

var myTestColorpicker = document.querySelector( '.my-test-colorpicker' );

// Init ColorPicker
var el = wp.element.createElement( wp.components.ColorPicker, {
    color: '#ff00bb',
} );

// Render
wp.element.render( el, myTestColorpicker );
```

### Environment info

- WordPress 5.9.2, default blocks editor included in 5.9.2, Any theme
- Chrome Version 99.0.4844.84 (Official Build) (x86_64)
- Desktop with MacOS Monterey 12.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by KAJALwp** [comment]
Hello @arl1nd & @karmatosed,

I have tried to reproduce the same issue, and yes I am also facing the same issue, with and without Gutenberg plugin.

following are the version details
WordPress:- 5.9.2
Mac OS:- Monterey 12.2.1 
Chrome:- Version 99.0.4844.84 (Official Build) (arm64)

Please review from your end and let me know if there is anything.

Thank you.

**Comment by Anjali29dots** [comment]
Hello @arl1nd & @karmatosed,

I have tested this as well but it is not working with Gutenberg plugin.

System Specification:
WordPress:- 5.9.2
Mac OS:- Monterey 12.2.1
Chrome:- V Version 99.0.4844.84 (Official Build) (arm64)
Video: https://www.awesomescreenshot.com/video/8162481?key=653f7b87d7b29571e6835f65bcc917ad

Please review from your end and let me know if there is anything.

Thank you.

**Comment by stokesman** [comment]
In the video you posted it seems you've noticed that by commenting out the `color` property the color picker begins updating the colors as you interact with it. This is how it's expected to behave and if you want to get the picked color out of it you can pass an `onChange` callback in:
```javascript
// Init ColorPicker
var el = wp.element.createElement( wp.components.ColorPicker, {
    onChange: v => console.log('new color', v),
} );
```
The color picker can also be made to update when it is provided a `color` property but it must be rendered again when the color updates. E.g. Wrap it in a stateful component:
```javascript
jQuery( '.my-test-colorpicker' ).remove();
jQuery( '<div class="my-test-colorpicker" style="position: fixed; top: 50%; left: 50%; width: 300px; height: 300px; background: #fff; border: 5px solid #ccc; transform: translate(-50%,-50%);"></div>' ).appendTo( 'body' );

var myTestColorpicker = document.querySelector( '.my-test-colorpicker' );

// Init ColorPicker
function PickerOfColor(){
    const [color, setColor] = wp.element.useState('#ff00bb');
    return wp.element.createElement(
        wp.components.ColorPicker,
        { color, onChange: setColor }
    );
}

// Render
wp.element.render(
    wp.element.createElement(PickerOfColor),
    myTestColorpicker
);
```

**Comment by arl1nd** [comment]
@stokesman this works great! Thank you very much for the proposed solution.
