### ISSUE TITLE
Many blocks appears in sidebar for CPTs that do not support certain features

### ISSUE THREAD

**Issue by greatislander** [WordPress/gutenberg#3989]
## Issue Overview

I created a custom post type for testing. Although the custom post type did not support featured images, excerpts, tags, categories, comments, or pingbacks, the blocks for these appeared in the Gutenberg sidebar.

## Steps to Reproduce (for bugs)

1. Register a custom post type without support for featured images, excerpts, tags, categories, comments, or pingbacks. Mine has the following `$args`:

```
$args = array(
	'labels'            => $labels,
	'public'            => true,
	'hierarchical'      => false,
	'show_ui'           => true,
	'show_in_nav_menus' => true,
	'supports'          => array( 'title', 'editor' ),
	'has_archive'       => true,
	'rewrite'           => true,
	'query_var'         => true,
	'show_in_rest'      => true,
	'rest_base'         => 'example',
	'rest_controller_class' => 'WP_REST_Posts_Controller',
);
```
2. Open a new post of the `example` custom post type for editing using Gutenberg.

[Safari/Chrome, macOS High Sierra, WordPress 4.9.1, Gutenberg 1.9.1]

## Expected Behavior
The blocks for featured images, excerpts, tags, categories, comments, or pingbacks do not appear in the Gutenberg sidebar.

## Current Behavior
The blocks for featured images, excerpts, tags, categories, comments, and pingbacks appear in the Gutenberg sidebar. However, WordPress does not reflect settings added via these blocks in Gutenberg on the front end as the post type does not support them.

## Possible Solution
Gutenberg should only show these blocks in the sidebar if the current post type supports them, which necessitates access to `post_type_supports()` data for any given custom post type.

## Screenshots / Video
Gutenberg:
![screen shot 2017-12-13 at 11 18 09 pm](https://user-images.githubusercontent.com/605361/33973916-f5ef737c-e05b-11e7-8e2a-e2330a038913.png)

Classic Editor:
![screen shot 2017-12-13 at 11 12 24 pm](https://user-images.githubusercontent.com/605361/33973778-27087900-e05b-11e7-9540-05a92314041a.png)

## Related Issues and/or PRs
Semi-related: https://github.com/WordPress/gutenberg/issues/2523

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by Soean** [comment]
Related to tags & categories #3943
