### ISSUE TITLE
List v2: indent/outdent multiple list items

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#39893]
When I select multiple list items and try to indent or outdent, only the first one is changed. All selected list items should change. Cc @jorgefilipecosta

**Comment by jorgefilipecosta** [comment]
Ident seems to work well outdent still does not work as expected.

**Comment by jorgefilipecosta** [comment]
Ident seems to work well outdent still does not work as expected.

**Comment by ntsekouras** [comment]
>outdent still does not work as expected.

That's true Jorge! I started working on this a while ago but never finished. Feel free to pick this up if you find some time.
