### ISSUE TITLE
Cover Image, Paragraph and Quote still appear next to the inserter even if they have been removed from the inserter via the allowed_block_types filter

### ISSUE THREAD

**Issue by greatislander** [WordPress/gutenberg#3990]
## Issue Overview
In testing the `allowed_block_types` filter, it appears that the Cover Image, Paragraph and Quote blocks still appear next to the inserter when they have been removed from the inserter's list of allowed block types.

## Steps to Reproduce (for bugs)
1. Add this filter in your theme's `functions.php`:

```
add_filter( 'allowed_block_types', function() {
  return [ 'core/verse' ];
} );
```
2. Edit a post in Gutenberg.

[Safari/Chrome, macOS High Sierra, WordPress 4.9.1, Gutenberg 1.9.1]

## Expected Behavior
The inserter should only show available block types next to it.

## Current Behavior
The Cover Image, Paragraph and Quote blocks appear next to the inserter even if they have been removed as allowed block types. Note that when all block types are removed they still appear, even though the inserter itself is gone.

## Possible Solution
If any one of the Cover Image, Paragraph or Quote blocks are removed from the inserter, the slots next to the inserter button should be filled with others (perhaps via the same mechanism that populates the Recent Blocks tab).

## Screenshots / Video
With this filter in place:

```
add_filter( 'allowed_block_types', function() {
  return [ 'core/verse' ];
} );
```

![screen shot 2017-12-13 at 11 39 51 pm](https://user-images.githubusercontent.com/605361/33974477-f6099146-e05e-11e7-828f-d900ed05c56b.png)

With this filter in place:
```
add_filter( 'allowed_block_types', `__return_false` );
```

![screen shot 2017-12-13 at 11 41 17 pm](https://user-images.githubusercontent.com/605361/33974509-279f48b8-e05f-11e7-8017-e4e3401676fa.png)
_Note that the insert button is absent._

## Related Issues and/or PRs

https://github.com/WordPress/gutenberg/issues/3968
https://github.com/WordPress/gutenberg/pull/3988

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/pull/4497 fixed this.

<img width="818" alt="screen shot 2018-04-26 at 16 40 39" src="https://user-images.githubusercontent.com/612155/39289747-b923aeb2-4970-11e8-8c62-04e248692d1f.png">
