### ISSUE TITLE
Block Editor Styles not loading in the Site editor (beta)

### ISSUE THREAD

**Issue by pixelprogrammer** [WordPress/gutenberg#39912]
### Description

When I use `enqueue_block_editor_assets` the block editor styles load when editing pages. However, when I am in the site editor, these styles load in the main document, but all of the blocks are loaded in an `iframe` and the styles are not loaded there.

Is this the expected behavior? Posting someone elses stackexchange question as it is the same issue I am having:

https://wordpress.stackexchange.com/questions/402037/enqueue-styles-in-new-site-editor-in-wordpress-5-9

### Step-by-step reproduction instructions

- enqueue styles with the `enqueue_block_editor_assets`
- Edit pages to see if it loads (should load normally)
- Edit site in Appearance > Editor (beta)
- Select a template part that has your custom blocks styles
- Stylesheet is loaded in the main document but not in the iframe document that has the blocks

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by chthonic-ds** [comment]
Try using `add_editor_style()`, more detail in [this support thread](https://wordpress.org/support/topic/how-do-we-attach-a-style-sheet-into-fses-iframe-location/).

**Comment by pixelprogrammer** [comment]
> Try using `add_editor_style()`, more detail in [this support thread](https://wordpress.org/support/topic/how-do-we-attach-a-style-sheet-into-fses-iframe-location/).

Thank you. That worked.

My styles already wrapped my classes in `.editor-styles-wrapper` so it was not working at first. I have to build two separate editor styles now but at least its working.
