### ISSUE TITLE
Try an outlined lock icon for block locking

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#39916]
## What problem does this address?

In excitedly testing block locking with GB 12.9, I noticed that the icon itself is quite heavy for lack of a better term and my eye was immediately drawn to it every time.  It was to the point that I worry we might be overemphasizing the feature in a way that doesn't reflect the usage it likely should have:

<img width="520" alt="Screen Shot 2022-03-30 at 10 44 15 AM" src="https://user-images.githubusercontent.com/26996883/160924852-44cd4902-2e8a-4cb9-a420-50061b490e18.png">

## What is your proposed solution?

In chatting with @jameskoster for a confidence check on this, he shared the possibility of using an outline:

<img width="245" alt="Screenshot 2022-03-30 at 19 04 04" src="https://user-images.githubusercontent.com/26996883/160925050-90dbc539-0755-4ea2-88f0-c8c35d51841d.png">

Here's what this would loosely look like:

<img width="872" alt="Screen Shot 2022-03-30 at 1 29 46 PM" src="https://user-images.githubusercontent.com/26996883/160925364-ed9ac2a7-8677-40b8-83ab-245a4f89aef3.png">

I think it strikes the right balance and matches the other icons/visuals in the menu.

**Comment by jameskoster** [comment]
@jasmussen made a good point that the icon should probably have some heft to it – it is a lock after all! :)

Another option we [explored before](https://github.com/WordPress/gutenberg/pull/39252#issuecomment-1063959066) was adding a keyhole:

<img width="69" alt="Screenshot 2022-03-31 at 09 40 59" src="https://user-images.githubusercontent.com/846565/161014334-9a88813b-c207-47ed-ad72-1c93f624cb2c.png">

Perhaps this is a good compromise? It adds a little character to make the icon feel more aligned with others in the set, whilst maintaining most of the weight.

**Comment by annezazu** [comment]
Another item to consider: using the full lock when all options are checked vs using an outline to represent a passive state without any locking in place.

**Comment by jasmussen** [comment]
> Another item to consider: using the full lock when all options are checked vs using an outline to represent a passive state without any locking in place.

A third option 😅 : show the outlined option in the ellipsis menu for when the action is passive, and show the heavy duty lock when a block is locked. The bespoke lock/unlock icons still make sense to me.

In any case, here's a new outlined icon for implementation:
<img width="373" alt="Screenshot 2022-04-06 at 09 02 17" src="https://user-images.githubusercontent.com/1204802/161915782-287ae275-243e-4f3d-8de8-ccd962953528.png">

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="enable-background:new 0 0 24 24" xml:space="preserve"><path d="M17 10h-1.2V7c0-2.1-1.7-3.8-3.8-3.8-2.1 0-3.8 1.7-3.8 3.8v3H7c-.6 0-1 .4-1 1v8c0 .6.4 1 1 1h10c.6 0 1-.4 1-1v-8c0-.6-.4-1-1-1zM9.8 7c0-1.2 1-2.2 2.2-2.2 1.2 0 2.2 1 2.2 2.2v3H9.8V7zm6.7 11.5h-9v-7h9v7z" style="fill:#1e1e1e"/></svg>
```

**Comment by ndiego** [comment]
Hi folks, this issue came up in today's Editor Bug Scrub. Just wanted to check in and see what the next steps might be. I personally like the outlined version, but that's just me 😅

**Comment by jameskoster** [comment]
I think Joen's suggestion is a good one – outlined version in the ellipsis menu, filled version when indicated a block is locked (IE in List View and the block toolbar). It's a low-priority item though.
