### ISSUE TITLE
If all embed blocks have been removed via wp.blocks.unregisterBlockType(), the Embeds tab should not appear in the inserter

### ISSUE THREAD

**Issue by greatislander** [WordPress/gutenberg#3992]
## Issue Overview
In certain use cases, a developer may need to disallow all embedded content. When all `core/embed` blocks are removed using `wp.blocks.unregisterBlockType()`, the Embeds tab still appears in the inserter, which is confusing.

## Steps to Reproduce (for bugs)
1. Unregister all embed blocks like so:

```
wp.blocks.unregisterBlockType("core/embed");
wp.blocks.unregisterBlockType("core-embed/twitter");
wp.blocks.unregisterBlockType("core-embed/youtube");
wp.blocks.unregisterBlockType("core-embed/facebook");
wp.blocks.unregisterBlockType("core-embed/instagram");
wp.blocks.unregisterBlockType("core-embed/wordpress");
wp.blocks.unregisterBlockType("core-embed/soundcloud");
wp.blocks.unregisterBlockType("core-embed/spotify");
wp.blocks.unregisterBlockType("core-embed/flickr");
wp.blocks.unregisterBlockType("core-embed/vimeo");
wp.blocks.unregisterBlockType("core-embed/animoto");
wp.blocks.unregisterBlockType("core-embed/cloudup");
wp.blocks.unregisterBlockType("core-embed/collegehumor");
wp.blocks.unregisterBlockType("core-embed/dailymotion");
wp.blocks.unregisterBlockType("core-embed/funnyordie");
wp.blocks.unregisterBlockType("core-embed/hulu");
wp.blocks.unregisterBlockType("core-embed/imgur");
wp.blocks.unregisterBlockType("core-embed/issuu");
wp.blocks.unregisterBlockType("core-embed/kickstarter");
wp.blocks.unregisterBlockType("core-embed/meetup-com");
wp.blocks.unregisterBlockType("core-embed/mixcloud");
wp.blocks.unregisterBlockType("core-embed/photobucket");
wp.blocks.unregisterBlockType("core-embed/polldaddy");
wp.blocks.unregisterBlockType("core-embed/reddit");
wp.blocks.unregisterBlockType("core-embed/reverbnation");
wp.blocks.unregisterBlockType("core-embed/screencast");
wp.blocks.unregisterBlockType("core-embed/scribd");
wp.blocks.unregisterBlockType("core-embed/slideshare");
wp.blocks.unregisterBlockType("core-embed/smugmug");
wp.blocks.unregisterBlockType("core-embed/speaker");
wp.blocks.unregisterBlockType("core-embed/ted");
wp.blocks.unregisterBlockType("core-embed/tumblr");
wp.blocks.unregisterBlockType("core-embed/videopress");
wp.blocks.unregisterBlockType("core-embed/vine");
wp.blocks.unregisterBlockType("core-embed/wordpress-tv");
```
(Following [this guide](https://wordpress.org/gutenberg/handbook/extensibility/#using-a-blacklist))

2. Click the inserter button while editing.

[Safari/Chrome, macOS High Sierra, WordPress 4.9.1, Gutenberg 1.9.1]

## Expected Behavior
The Embeds tab should disappear from the Inserter modal.

## Current Behavior
The Embeds tab is present, but empty.

## Possible Solution
Uncertain of the implementation, but the Embeds tab should only be loaded if it has blocks to populate it.

## Screenshots / Video
![screen shot 2017-12-14 at 12 04 31 am](https://user-images.githubusercontent.com/605361/33975052-7edecf88-e062-11e7-8466-2f35f70da95f.png)

## Related Issues and/or PRs
None that I can find.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by gziolo** [comment]
This issue was fixed together with UI refinements introduced in https://github.com/WordPress/gutenberg/pull/6636:
![screen shot 2018-06-12 at 08 29 56](https://user-images.githubusercontent.com/699132/41273740-f8ca1550-6e1a-11e8-813c-711fe2b2b860.png)

Thanks for opening this issue.

**Comment by greatislander** [comment]
Thanks @gziolo!
