### ISSUE TITLE
Site icon is not removed from the Navigation Sidebar

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#39922]
### Description

If the logo image is reset or the site logo option "Use as site icon" is toggled off, the site icon is still used in the navigation sidebar in the site editor.

### Step-by-step reproduction instructions

With a full site editing theme active:

1. Upload a site logo.
2. Enable it as the site icon, save.
3. Refresh and see that the site icon replaces the WordPress logo in the navigation sidebar.
4. Disable the "Use as site icon" option, save.
5. See that the site icon still replaces the WP logo.
6. Reset the site logo image from the block toolbar, save.
7. See that the site icon still replaces the WP logo.

### Environment info

WordPress 5.9.2
Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Smit2808** [comment]
hi @carolinan, I tested this.

My environment info: 
1. WP V5.9.2
2. Gutenberg V12.9.0
3. Browser Chrom
4. MAC OS

Steps: 
1. Opened the FSE and uploaded the site logo and save it.
2. Refresh it and the site logo which I uploaded is reflected in navigation and in the site logo block. So this case is working.
3. After this I replace the old logo with a new logo the site logo is changed but in the navigation sidebar, it is not changed. 

Attaching an image of replaced logo issue.
<img width="1440" alt="Screenshot 2022-03-31 at 5 32 20 PM" src="https://user-images.githubusercontent.com/64188895/161050355-5c63142f-29f9-4148-8a34-955efed4d897.png">
