### ISSUE TITLE
Reduced UI: Further reduce the top bar

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#39934]
If you enable reduced ui in the preferences parts of the top bar disappear until hovered:

https://user-images.githubusercontent.com/846565/161017645-c62c7858-de6a-4bbe-87b8-eafa50f9be01.mp4

I wonder if we could go a step further and hide the top bar altogether in this mode, and reveal it only when the cursor approaches the top of the viewport:

https://user-images.githubusercontent.com/846565/161017787-d498af3f-caaa-4816-af29-41ca5973f48d.mp4

**Comment by mtias** [comment]
Related #38928.

**Comment by draganescu** [comment]
Super happy this is in folks mind 👏🏻  @jameskoster This is what I originally had in mind with the top toolbar in #38928. I need to get my CSS superpowers from wherever i left them. 

I'll try to see if the toolbar could use a helper component for that behavior.

**Comment by Thelmachido** [comment]
Looks like the work for this one is being continued here: https://github.com/WordPress/gutenberg/pull/41740

@draganescu is there a plan to merge this one?

**Comment by draganescu** [comment]
I think https://github.com/WordPress/gutenberg/pull/41740 will close this one as well. As for merging I think I am pretty close.

**Comment by Mamaduka** [comment]
@jameskoster, @draganescu, now that "Distraction Free Mode" is merged, can we close this issue?
