### ISSUE TITLE
Search Block: Button-position: inside, variant width grows beyond 100%

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#39946]
### Description

Width of the search block grows with an extra value (of x-padding) when the button position is inside.
It grows because of the extra padding in this option.

block should have `box-sizing: border-box;` for the right width.

### Step-by-step reproduction instructions

* Add a search block in the page
* give it a 100% width
* Change the button position to `inside`
* observe that total effective width is more than 100%

### Screenshots, screen recording, code snippet

<img width="438" alt="image" src="https://user-images.githubusercontent.com/1935113/161042872-0a521560-334a-4842-b2f7-01b9189d42db.png">

### Environment info

- Latest GB

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by LukaszJaro** [comment]
Great, thanks for fix. I noticed this as well, seems to happen in my header which is wrapped in just a group but in body it is okay. Body search has group plus columns so maybe that is limiting the input from stretching beyond.
