### ISSUE TITLE
Missing empty state when inserting a Reusable Block

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#3994]
Nothing at all shows up when clicking on the 'Saved' tab in the inserter for the first time:

<img width="323" alt="resizeist doist com" src="https://user-images.githubusercontent.com/612155/33977244-14fd71a0-e0ee-11e7-9ace-23e8cbe32afa.png">

Ideally, we would use this chance to teach the user about how to create a Reusable Block.

Steps to reproduce:

1. Install Gutenberg on a fresh WordPress install, or run `wp site empty` on your test site to delete all content
2. Open the inserter
3. Click on the 'Saved' tab

cc. @jasmussen @karmatosed

**Comment by jasmussen** [comment]
Great catch.

Can we simply show a message like this?

_No saved blocks._

Centered, and either vertically centered or a couple of lines down from the top.
