### ISSUE TITLE
In WP 5.9.2 content block duplication issue in post

### ISSUE THREAD

**Issue by theminaldiwan** [WordPress/gutenberg#39947]
### Description

In WP 5.9.2 content block duplication issue occure while adding wp block in post editor.

### Step-by-step reproduction instructions

1.Create new post
2.Adding post image and title and edit single post template
3.Adding WP any block inside editor and update it.

### Screenshots, screen recording, code snippet

Recording:
https://www.loom.com/share/105e870aadb54dfbac3b6db9f5db4eb7

### Environment info

WP - 5.9.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by anamwp** [comment]
Hello @theminaldiwan 
I think, you need to insert your content inside the content area when you editing single post template. 
Otherwise it will be outside of the content. 

Check below screenshot. 
https://monosnap.com/file/EcCQOCMF17cYxo1CPj3z3zIx8WZGoU

Correct me If I am wrong. 
Thanks.

**Comment by theminaldiwan** [comment]
Hi @anamwp 
Yes ,its working but in case anybody having first time visit its difficult to identify the adding block inside post content block.So anybody can adding block anywhere but block will be nested at a particular page.It should not be affecting the other pages.
Thanks

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. Thank you for submitting. I agree that the user interface could be clearer when editing a page template, as opposed to the page/post content itself, but everything appears to be working as intended. Therefore I am going to close out this issue.
