### ISSUE TITLE
Categories are Blank & Featured Image selection missing in editor

### ISSUE THREAD

**Issue by Tirjasdyn** [WordPress/gutenberg#39962]
### Description

I went to write a post and my categories section is empty and the feature image block is missing from the sidebar.
![Screenshot 2022-03-31 170607](https://user-images.githubusercontent.com/10961682/161163877-be0ad536-1cc6-4d74-bd2f-492adb1d4493.JPG)

I turned off all plugins and the problem persists, even with a default theme. I can see categories in quick edit. 

In the console i see this: 

Uncaught (in promise) 
Object { code: "invalid_json", message: "The response is not a valid JSON response." }
2
Uncaught (in promise) TypeError: can't access property 0, r is null
    pt https://www.michellejnorton.com/wp-includes/js/dist/core-data.min.js?ver=a2bea1a5333f4e9d2ea07429a9924da0:2
[core-data.min.js:2:38755](https://www.michellejnorton.com/wp-includes/js/dist/core-data.min.js?ver=a2bea1a5333f4e9d2ea07429a9924da0)
Uncaught (in promise) 
Object { code: "invalid_json", message: "The response is not a valid JSON response." }

Several others have posted this issue in similar closed issues. Any help would be appreciated. 
 

### Step-by-step reproduction instructions

1. Click New Post
2. or open old post

### Environment info

WordPress 5.9.2 running [Garuda](https://www.michellejnorton.com/wp-admin/themes.php) theme. I'm using the built in Gutenberg. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Tirjasdyn** [comment]
Update. I found an old post here: which resolved the issue by deleting a User defined apache handleer. https://wordpress.org/support/topic/page-post-updating-failed-wordpress-5-2-rest-api-context-query-parameter/page/2/

I did have one and deleted it, this brought back feature image in the editor but not the categories.

**Comment by Tirjasdyn** [comment]
Cleared my cache (browser) after doing this and it's now working. 

Steps to fix:
Log into hosting and cpanel 
Go to Apache Handlers
Delete Handler with .php in it
Clear Cache and reaload site.

**Comment by ndiego** [comment]
Hi @Tirjasdyn, thank you for submitting a ticket and for providing detailed instructions for others that might run into this issue. It looks like it's resolved now, so I am going to close out the ticket. If this is not the case, just let me know and I'll reopen. Thanks!
