### ISSUE TITLE
Improve the search for tags when a substring doesn't appear in the first 20 results.

### ISSUE THREAD

**Issue by costdev** [WordPress/gutenberg#39964]
## What problem does this address?
See Trac ticket: [55511](https://core.trac.wordpress.org/ticket/55511).

**Comment by rodrigocarlos** [comment]
I want to share an idea that might be the solution. Maybe you could put in the link search window, tabs that would filter by type of post (posts, tags, pages, categories, ...). So by default it can have the **All** tab and the search result will be for all post types (as it is currently). But if we want the result to be just a tag, then just click on the **Tags** tab and only tags related to the research we did will appear. If we want the result to show only categories, then just click on the **Categories** tab and it will only show categories related to the search term.

For example, I want to find all tags that have the word "netflix", so I just type the word "netflix" in the search bar and then click on the **Tags** tab, and the result will show only tags (ex.: /tag/netflix, /tag/netflix-movies, /tag/netflix-series, ...)

Here's an example of what these tabs could look like: https://prnt.sc/jgQUfLYBKek6

Thank you!

**Comment by Mamaduka** [comment]
Still relevant.

**Comment by sakirsensoy** [comment]
Issue was opened exactly 2 years ago but the problem still persists :/

**Comment by noisysocks** [comment]
Closing as a dupe of https://github.com/WordPress/gutenberg/issues/56478 as it has a better description.

A PR https://github.com/WordPress/gutenberg/pull/62397 is open which will fix this.
