### ISSUE TITLE
Show/Hide on blocks on different device/screen types

### ISSUE THREAD

**Issue by Greatdane** [WordPress/gutenberg#39968]
### What

I would like to have the option for every single block that would allow to hide/show the block based on device type in the FSE and the regular blocks.

### Why

This will give more control to the user to manage the content on the website. This way, they can decide to hide the content that may not be suitable for mobile viewers from being viewed when the site is viewed on mobile and vice versa.

Additionally, they can decide to create multiple variations of the same content by choosing to display one set for the mobile viewers and another only for desktop and tablet viewers.

Overall, it will enhance the website development experience to a whole new level with precise control on the block elements based on the device types.

### How

For example, see this image.  
[![hide-show](https://user-images.githubusercontent.com/8070771/155530408-234dc4ab-2db4-4678-9a5b-085b6eeae59c.png)](https://user-images.githubusercontent.com/8070771/155530408-234dc4ab-2db4-4678-9a5b-085b6eeae59c.png)

**Comment by ndiego** [comment]
HI @Greatdane, thank you for submitting this issue. This would be a very useful feature. That said, there are many great free plugins that already include this functionality, which traditionally has been something WordPress Core has avoided implementing directly and left to plugins. I have included a list of options below. Full disclosure, I built Block Visibility.

- [EditorsKit](https://wordpress.org/plugins/block-options/)
- [If-So Dynamic Content Personalization](https://wordpress.org/plugins/if-so/)
- [Conditional Blocks](https://wordpress.org/plugins/conditional-blocks/)
- [Block Visibility](https://wordpress.org/plugins/block-visibility/)

For a simpler solution, in one of my themes, I have created helper CSS classes that I can add as needed to each block under the Advanced section (see screenshot below).

![image](https://user-images.githubusercontent.com/4832319/161462245-225b0a2c-f5eb-4aea-85ff-4e48384c1135.png)

I know this is not the answer you were looking for, but I hope this info is at least helpful. 🙏

**Comment by syhussaini** [comment]
I request to have this feature considered especially for the Simple Sites as these sites does not have the option to add Plugins.
