### ISSUE TITLE
 wp.data.dispatch('core/edit-post').openModal(); Not Working

### ISSUE THREAD

**Issue by walter74ucla** [WordPress/gutenberg#39963]
### Description

[openModal](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-edit-post/#openmodal)
Returns an action object used in signalling that the user opened a modal.

Parameters
**name string: A string that uniquely identifies the modal.**
Returns
Object: Action object.

### Step-by-step reproduction instructions

1. Go to the Edit Article Screen
2. Click on the three dots on the upper right hand corner (Options)
3. Scroll down to the TOOLS section and click on Block Manager
4. Go to DevTools Console and enter this:   wp.data.dispatch('core/edit-post').openModal();
5. The Block Manager modal will close
6. Go to DevTools Console and enter this:   wp.data.dispatch('core/edit-post').openModal();
7. The Block Manager modal does not open and the Promise is fulfilled

I also tried the following with no luck:
wp.data.dispatch('core/edit-post').openModal('frame_ModalFrame');
wp.data.dispatch('core/edit-post').openModal('Block Manager');
wp.data.dispatch('core/edit-post').openModal('BlockManager');
wp.data.dispatch('core/edit-post').openModal('modal-open');
wp.data.dispatch('core/edit-post').openModal('ManageBlocksModal');
wp.data.dispatch('core/edit-post').openModal('edit-post-manage-blocks-modal');

### Environment info

WordPress 5.8.4 running Southern California News Group theme.
Gutenberg 10.0-10.7 or 10.8-11.9
Google Chrome
Desktop with Mac OS Catalina v10.15.7

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
> Scroll down to the TOOLS section and click on Block Manager

@walter74ucla Thanks for reaching out. The block manager has been in the Preferences Modal since Gutenberg 10.9 - https://github.com/WordPress/gutenberg/pull/32166.

You can use this snippet to open the preferences modal, but I don't think there's a way to open the blocks tab:
```js
wp.data.dispatch( 'core/edit-post' ).openModal( 'edit-post/preferences' )
```

Gutenberg is now on v12.9, unfortunately versions as old as the ones you reference are not actively supported.

**Comment by walter74ucla** [comment]
thanks @talldan Your reply led to this:  wp.data.dispatch( 'core/edit-post' ).openModal( 'edit-post/manage-blocks' )
And it works as expected!
