### ISSUE TITLE
Gallery/Image blocks images attributes not updated properly

### ISSUE THREAD

**Issue by JoomUnited** [WordPress/gutenberg#3997]
## Issue Overview

The attributes of the images did not update correctly when edited from Media Manager window

## Steps to Reproduce (for bugs)

1. Create image/ gallery block.
2. Insert images to the block.
3. Click pen icon to edit images.
4. Change the attributes of image (like caption, alt text...)
5. Close the Media manager window.

## Expected Behavior

The attributes will updated in the block.
The save button appear and can click to save.

## Current Behavior

Block is not updated. Even the "Saved" text shown in Media manager window.
The save button still disable. Cannot click to save the content.

## Possible Solution

You have to re-insert images to the block to make it update.
But better if the attributes is updated after edit it.

**Comment by jorgefilipecosta** [comment]
Hi @JoomUnited thank you for reporting this issue 👍  I'm not being able to reproduce this on the master branch. Is this problem still happening to you?

**Comment by JoomUnited** [comment]
Seems like the 1.9.1 fixed something? I'm not able to reproduce it now. Thanks!
