### ISSUE TITLE
Determine canonical way to declare optional dependency on store from another package.

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#39987]
## What problem does this address?

In several places of the codebase, you can see something like this:

https://github.com/WordPress/gutenberg/blob/6821d2968a9223f7f97a97e6427d7cc09300eb05/packages/block-library/src/calendar/edit.js#L51-L54

Technically, there's no bug to "fix" in this exact use case. `editorSelectors` will simply be `null` when the `core/editor` store is not available, and the code that follows handles the null case.

Still, it is awkward to access the store via string literal rather than an imported store object, and one would think that the former should be deprecated eventually. It seems like the ideal solution would be to somehow declare an optional dependency on the `@wordpress/editor` package, importing its `store` export if available, and defaulting to `null` (or `undefined`) otherwise.

But how would this be done in practice? A normal ESM import declaration doesn't handle optional dependencies.

## What is your proposed solution?

[Dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports) exist, and it looks like they may be the solution. However, I do not know if our current build tooling would work with them, and them being async may pose a problem. I picture using them like so:

```js
// This will either be the store or null.
const editorStore = await import('@wordpress/editor')
	.then(result => result.store)
	.catch(_err => null)
```

I'm curious what other people think of this idea.

**Comment by gziolo** [comment]
Hello, there already is a similar issue tracked in the repository: https://github.com/WordPress/gutenberg/issues/32842.

The other reason we use strings when referencing stores is to avoid explicitly declaring a dependency which would create cyclic dependencies between packages. However, in that case, it’s an issue with the code architecture.
 
For the case, you explicitly described, one way to resolve the issue would be to decouple context-based dynamic values from the block. One idea that might help “dynamic tokens” is coming from @dmsnell. You can check the related discussions at https://github.com/WordPress/gutenberg/discussions/39831.

**Comment by ZebulanStanphill** [comment]
Thanks, I couldn't find the aforementioned issues by searching. Good to know I'm not the first to bring this up, haha.

**Comment by gziolo** [comment]
It still would be valuable to get your feedback on the issue I shared. Thank you for opening the issue. I know it’s getting harder to locate previously reported issues.

**Comment by dmsnell** [comment]
> one would think that the former should be deprecated eventually

one would think correctly 😉 not sure when, but I believe we already want to have people pass in the store object itself already.
