### ISSUE TITLE
@wordpress/scripts: Add option to build unminified versions of CSS/JS files

### ISSUE THREAD

**Issue by ofry** [WordPress/gutenberg#39996]
## What problem does this address?
build command on @wordpress/scripts can't only merge file without minifying

## What is your proposed solution?

Should be available "unminified" option like this syntax:
`wp-scripts build --unminified includes/js/src/index.js --output-path=includes/js`

**Comment by gziolo** [comment]
There is`wp-scripts start` command that doesn’t minify the code. Can you explain the reasoning and potential benefits of adding a new flag to `wp-scripts build`?

**Comment by ofry** [comment]
Thank you. Sorry for disturbing.

**Comment by Thaval** [comment]
I would also like to know this. Im currently running a plugin in wordpress docker and I want to debug it, but i only see the minified code of the plugin. (from the build directory). 
Is there a way I can tell wordpress to use the src folder?
