### ISSUE TITLE
Social link color panel does not have a reset all option

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#39990]
### Description

The color panel for the social links block does not have a "reset all" option.

### Step-by-step reproduction instructions

1. Add a social icons block
2. Open the block settings sidebar and expand the color section.
3. Select colors.
4. Try to reset the colors. Notice that the "Reset all" option is not available.

### Environment info

WordPress 5.9.2
Gutenberg current trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aezazs-multidots** [comment]
Hello @carolinan 

I have tried to reproduce the same issue, and yes I am also facing the same issue, with and without the Gutenberg plugin. The social link color panel does not have a reset-all option.

Following are the version details

WordPress:- 5.9.2
Mac OS:- Monterey 12.2.1
Chrome:- Version 100.0.4896.75 (Official Build) (arm64)
Please review from your end and let me know if there is anything.

Thank you.
