### ISSUE TITLE
Text format pop-over displays over block selector menu

### ISSUE THREAD

**Issue by JDGrimes** [WordPress/gutenberg#40]
It is especially weird when I selected some of the text on the menu itself and the pop-over displayed as if I could edit that:

![editor_blocks_-_2017-02-09_15 20 59](https://cloud.githubusercontent.com/assets/4005415/22801609/870fbb8c-eedb-11e6-9bfc-0a5ae3c17b4a.png)

(Sorry if my terminology is bad, couldn't remember exactly what the pop-over is called.)

**Comment by jasmussen** [comment]
This was fixed in #68.
