### ISSUE TITLE
FSE Link Styles: can we have an option to control underlines?

### ISSUE THREAD

**Issue by supernovia** [WordPress/gutenberg#40002]
## What problem does this address?
Sometime site owners like their links to be underlined. Others want to turn underlines off. I would expect this option to be under Styles > Typography > Links, and there is an Appearance option there, but it seems to just be font weights. Currently underline is handled by the theme itself, and themes aren't consistent in this. Telling someone to just switch to another FSE theme, and lose all of their customizations, is suboptimal.

## What is your proposed solution?
We have a Links appearance option under Colors, and another under Typography. Typography could have something as simple as a checkbox to underline links.

I would hope to be able to set this for the a full-site style as well an option to override it for some blocks (so we can underline in entry-content without having to underline in buttons or in nav, for example).

Here's a screenshot of where I thought the option would be. An underline checkbox above it would probably do.
<img width="266" alt="Screen Shot 2022-04-03 at 12 10 23 PM" src="https://user-images.githubusercontent.com/3476361/161442062-4b9d9c49-ec14-4b60-8aad-b64f50de2501.png">
.

**Comment by masteradhoc** [comment]
+1

**Comment by iwasthesword** [comment]
It would be great to have this, but I'd suggest going the long way and have this be added as "Decoration" (from css: `text-decoration`) as to support everything this css property has which includes underline, overline and line-through, as well as color, style and thickness

**Comment by supernovia** [comment]
I'm realizing from this case that decoration may be important for this to be an option for individual links, too:
https://wordpress.com/forums/topic/making-groups-clickable/

**Comment by paaljoachim** [comment]
Check out this issue:
https://github.com/WordPress/gutenberg/issues/30701
