### ISSUE TITLE
Image alignment in Gutenberg

### ISSUE THREAD

**Issue by justnorris** [WordPress/gutenberg#4000]
## Issue Overview
I noticed that if an image is aligned to either side - in Gutenberg it appears to be 50/50 with text, when in the front-end the `(image width) / (text width)` ratio depends solely on the image width. 

If the user has selected a "full", or even "large" sized image, they might expect this:
![expectation](https://user-images.githubusercontent.com/988095/33993127-eb8c36ae-e0dd-11e7-8551-021a9ce34cc6.png)

But instead get this:
![reality](https://user-images.githubusercontent.com/988095/33993126-eb51d3ba-e0dd-11e7-9d61-b31d9c912003.png)

## Possible Solution
Build in real columns support for Gutenberg
or
Represent the image as it would appear on the front end. 50/50 layout certainly wont do.

**Comment by mtias** [comment]
Thanks for the feedback. Closing as we have Columns support and improvements to floats have already been merged.
