### ISSUE TITLE
"Add to reusable blocks" menu item should use the reusable block icon.

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40017]
It currently displays the transform icon:

<img width="296" alt="Screenshot 2022-04-04 at 10 14 08" src="https://user-images.githubusercontent.com/846565/161512907-9dd5f624-0779-4d46-9fe9-9ac8e7579b0c.png">

Proposal:

<img width="294" alt="Screenshot 2022-04-04 at 10 14 57" src="https://user-images.githubusercontent.com/846565/161513055-b55138d9-0165-4ccc-809b-4c5b96d38b66.png">

**Comment by Mamaduka** [comment]
Fixed via #40020.
