### ISSUE TITLE
Transforms between Heading & Cover Image

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#4003]
## Issue Overview

This issue seeks to ask:
1. Does it conceptually make sense to offer transforms between Heading and Cover Image blocks?
2. If so, what does that exactly look like?

To better frame question 2, it's worth noting that Cover Image currently only has two visual states:
- No background image URL has been provided and we get the placeholder state prompting us to pick an image from the media library.
- An image has been picked, and we see it in the background, with an Editable placed over it.

I gave this a quick try. Merely transforming from Heading to Cover Image with default attributes (only providing the text) was quite awkward because of the points above: transforming would result in a Cover Image in placeholder state, and only after picking the image would you see the original Heading's text had been ported too:

![gutenberg-heading-cover-image-awkward](https://user-images.githubusercontent.com/150562/33995803-041caa48-e0d7-11e7-8e4c-6a181e3ee96e.gif)

So my next try was to support a state where we have text but no image. With that, this is how the transformations look like, both ways:

![gutenberg-heading-cover-image](https://user-images.githubusercontent.com/150562/33995828-1c3f6e44-e0d7-11e7-8638-29674b1384c5.gif)

Obviously, the gray background looks clunky, but it may hint at how to provide a better alternative to the former behavior.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
I like this. We probably want to work out if the grey background as you say, I do like it as an option though. Transitioning between blocks should be easy and this helps a lot avoid a visual hitch.

What about this?

![artboard](https://user-images.githubusercontent.com/253067/34009141-a59fb02c-e0ff-11e7-9ebd-2904c3fa004e.png)

**Comment by mcsf** [comment]
Yeah, I like that better. What could it look like if we wanted to preserve the style of the normal placeholder state?

**Comment by karmatosed** [comment]
![coverimage](https://user-images.githubusercontent.com/253067/34222260-e117c61e-e5b2-11e7-9fd6-8ad0dc520e10.png)

What about the above @mcsf ?

**Comment by mcsf** [comment]
Looks good to me! :)
