### ISSUE TITLE
Spacer block - Crashes when changing the height value using the text input

### ISSUE THREAD

**Issue by geriux** [WordPress/gutenberg#40045]
## Description
Changing the height value of the Spacer block crashes the app.

## Step-by-step reproduction instructions
1. Open the app
2. Create a post or page
3. Add a `Spacer` block
4. Open the block's settings
5. Change the height value using the keyboard

## Expected behaviour
You should be able to change the value using the keyboard

## Actual behaviour
The app crashes when trying to edit the value

## Screenshots or screen recording (optional)
<kbd><img src="https://user-images.githubusercontent.com/4885740/161750763-543f8467-da86-4e99-a769-c8e44d28f044.gif" width="300" /></kbd>

## WordPress information
- WordPress version: Latest version
- Gutenberg version: Latest in trunk
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: iPhone 12 Pro
- Operating system: 15.3
- WordPress app version: 19.6

**Comment by fluiddot** [comment]
I've just followed the reproduction instructions with the WP-Android beta version `19.6-rc-1` and managed to reproduce the crash.

Here is the Sentry event related to the crash:
https://sentry.io/share/issue/f69cf2cbf05f4064a66748d515cab007/

**Comment by fluiddot** [comment]
Looks like the issue was introduced in https://github.com/WordPress/gutenberg/pull/39577. The import of `MIN_SPACER_SIZE` constant is pointing to the native version of the `edit` file (i.e. `edit.native.js`), however, the constant is defined in the web version (`edit.js`). Simply updating the import statement should address the issue.
