### ISSUE TITLE
[Only Android] Unsupported block editor: Unable to load error message is not visible with dark mode

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#40044]
## Description

On Android with the dark mode enabled, the "Unable to load the block editor right now" error message related to this [test case](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#editing-unsupported-blocks-is-disallowed-on-classic-enabled-atomic-sites) is not visible.

## Step-by-step reproduction instructions

1. On an Android device, turn dark mode on.
2. Follow the instructions of the [test case "Editing unsupported blocks is disallowed on Classic-enabled Atomic sites"](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#editing-unsupported-blocks-is-disallowed-on-classic-enabled-atomic-sites).
3. Observe that the error message `Unable to load the block editor right now` is not visible.

## Expected behaviour

Error messages should be visible within the Unsupported block editor when dark mode is on.

## Actual behaviour

Error messages aren't visible within the Unsupported block editor when dark mode is on.

## Screenshots or screen recording (optional)

Android|iOS
--|--
<img src=https://user-images.githubusercontent.com/14905380/161736960-cb8b3d4f-ed7a-45ba-a6b2-575f30534a88.jpg width=300>|<img src=https://user-images.githubusercontent.com/14905380/161737420-f0357ddf-779a-46fc-ae03-0a2e12ab814c.jpeg width=300>

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: Samsung Galaxy S20 FE 5G
- Operating system: Android 11
- WordPress app version: WordPress-Android 19.6-rc-1

**Comment by hypest** [comment]
👋 @fluiddot , I think this is essentially the same ticket as https://github.com/wordpress-mobile/gutenberg-mobile/issues/4680. Perhaps we can close one or the other? Also, we probably need to add it to the "Known issues" for that manual testcase as well, wdyt?

**Comment by fluiddot** [comment]
> 👋 @fluiddot , I think this is essentially the same ticket as [wordpress-mobile/gutenberg-mobile#4680](https://github.com/wordpress-mobile/gutenberg-mobile/issues/4680). Perhaps we can close one or the other? 

Good catch, I'm afraid that I overlooked that issue when I look for duplicates. I'll close this one in favor of https://github.com/wordpress-mobile/gutenberg-mobile/issues/4680.

> Also, we probably need to add it to the "Known issues" for that manual testcase as well, wdyt?

Good idea, I'll open a PR to include this 👍 .
