### ISSUE TITLE
Clear theme.json cache after saving Styles in FSE

### ISSUE THREAD

**Issue by SergeGusev** [WordPress/gutenberg#40048]
## What problem does this address?

It is taking too long (for development) waiting for site's style changes after setting background color, for example. This is a video - https://drive.google.com/file/d/1h1Nn71QtCviAdPoruufSkC1rmKck_pON/view

## What is your proposed solution?

You can clear all caching after pressing Save button on Styles tab (well, on whole page too, I thinks)

**Comment by bradhogan** [comment]
+1 on this.  Frustrating that multiple hard refreshes don't show global style updates in some cases.  Not a great UX when the idea is to make things instantly visually in the editor but not on the actual site.

**Comment by nick6352683** [comment]
Same problem here... This should have a priority for WP 6.0 !

**Comment by mrleemon** [comment]
This is a pain in the neck. The theme,json cache should be refreshed when a change in the file is made.

**Comment by kauaicreative** [comment]
`define( 'SCRIPT_DEBUG', true );` or `define( 'WP_DEBUG', true );` in wp-config.php should fix the issue with theme.json
But I find styles unusable e.g. /styles/theme.json unusable. The cache never clears on my local environment.

**Comment by nick6352683** [comment]
Thanks I'll give it a shot - although it will be in a localhost Xampp php 7.4 environment.

**Comment by oandregal** [comment]
Closing as duplicate of https://github.com/WordPress/gutenberg/issues/43914

It's been fixed at https://github.com/WordPress/gutenberg/pull/45679
