### ISSUE TITLE
Preset colors not working on classic themes

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#40043]
### Description

On classic themes, colors that are defined in core's color palette won't show on the frontend unless the theme defines them.

### Step-by-step reproduction instructions

1. Activate Twenty Thirteen.
2. Add a Group block, make the background black (#000000 on the color picker)
3. Check the frontend, there's no background color applied

In the editor, we can see the color set as an inline style. In the editor, the class `has-black-background-color` is applied instead and since it's not a block theme, that class is doing nothing.

/cc @WordPress/block-themers 

### Screenshots, screen recording, code snippet

Editor:

<img width="1098" alt="Screenshot 2022-04-05 at 11 19 01" src="https://user-images.githubusercontent.com/3593343/161722412-ac6304f0-a160-4d24-be3e-3350b0f01ded.png">

Frontend:

<img width="897" alt="Screenshot 2022-04-05 at 11 19 06" src="https://user-images.githubusercontent.com/3593343/161722438-65682f02-d167-4d42-a3bc-e9b13ecfb3ef.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by draganescu** [comment]
Somehow I was not able to repro. What am I missing?

https://user-images.githubusercontent.com/107534/167258000-31cc5582-43ca-46e1-9fb5-1f60ec8754e8.mp4

**Comment by MaggieCabrera** [comment]
yeah, something must have changed, I can't reproduce anymore! Closing
