### ISSUE TITLE
Navigation block: Delay creating entities until changes are saved

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#40050]
## What problem does this address?
Following on from https://github.com/WordPress/gutenberg/pull/39883 it would be great if changes to navigation menus weren't converted to entities until the "Save" button in the Site Editor is clicked. This will avoid creating new navigation menus when the user is just making changes for testing, which should not be saved.

**Comment by getdave** [comment]
@scruffian Can we close this one?

**Comment by scruffian** [comment]
Yeah I think we've got a better path forward.
