### ISSUE TITLE
Apply duotone filter to placeholders for Site Logo & Post Featured Image blocks

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40061]
## What problem does this address?

When applying a duotone filter to a Site Logo or Post Featured Image placeholder, there's no visual indication that anything has been applied. This was [found during the 6.0 walkthrough](https://make.wordpress.org/core/2022/03/30/6-0-product-walk-through/).

https://user-images.githubusercontent.com/26996883/161873235-43729065-a0b4-4174-afbf-a07ac7d5a0cc.mov

## What is your proposed solution?

This was previously discussed here https://github.com/WordPress/gutenberg/pull/36517#issuecomment-970660514 but it doesn't seem this was ever implemented and/or a regression might have happened. cc @ajlende @jasmussen for more context.

In that discussion, it was noted that a good alternative would be to apply it to the outline and upload button as well (this button only shows when one is adding a post featured image block to a Post or Page rather than at the template level):

<img width="765" alt="Screenshot 2021-11-16 at 21 34 01" src="https://user-images.githubusercontent.com/1204802/142061413-032a0c00-e5c5-40a1-b8e1-e5071a2a6e0b.png">

It could also just be added to the dashed border:

<img width="810" alt="Screenshot 2021-11-16 at 21 31 02" src="https://user-images.githubusercontent.com/1204802/142061505-5275159e-c6e8-4c61-989f-5a426ca83b8c.png">

Note that the above placeholder was updated https://github.com/WordPress/gutenberg/pull/36712 so I'm pulling in old screenshots :)

**Comment by jasmussen** [comment]
Yes, this used to work. If we're okay with the upload button being colored when a duotone filter is selected — I think it's fine until further optimizations — then this could potentially be a quick win.
