### ISSUE TITLE
Multi-Select: hide grouping controls for when selecting text only blocks

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40063]
## What problem does this address?

When using multi-select, the block toolbar still displays the tooling to group/row/stack blocks:

https://user-images.githubusercontent.com/26996883/161875269-82bfb730-d2b7-4b5b-aa7e-03defac0f14a.mov

This was [found during the 6.0 walkthrough](https://make.wordpress.org/core/2022/03/30/6-0-product-walk-through/).

## What is your proposed solution?

When using multi select with text only blocks (header, paragraph, etc), hide the controls for group/row/stack options:

<img width="335" alt="Screen Shot 2022-04-05 at 6 10 21 PM" src="https://user-images.githubusercontent.com/26996883/161875793-c27bf023-9385-4bb6-bb71-8cef3b8673cc.png">

**Comment by andrewserong** [comment]
Interesting idea! Why do we want to hide the controls when text blocks are selected? Grouping text blocks can be useful if there are paragraphs and headings that someone wants to highlight together:

![highlighting-paragraphs](https://user-images.githubusercontent.com/14988353/161903070-d3a15bba-b0a6-45cb-80e3-ef959f37afcd.gif)

Or was it more about if text is only partially selected, then we should hide it 🤔

Apologies if the context is clearer from the 6.0 walkthrough, I didn't manage to catch it! 🙂

**Comment by annezazu** [comment]
Ah to be clear, this is to hide the controls when using the new multi-select feature where you can select text across multiple blocks. At least, this was my interpretation as having all of these controls while using multi select feels like overkill.

Current:

<img width="414" alt="Screen Shot 2022-04-06 at 10 45 47 AM" src="https://user-images.githubusercontent.com/26996883/162036372-ee794496-35bf-4b7d-8d65-5c19eaa467fc.png">

Proposed:

<img width="305" alt="Screen Shot 2022-04-06 at 10 45 57 AM" src="https://user-images.githubusercontent.com/26996883/162036399-f6289a05-3511-46b7-bec2-644ed04fb71e.png">

**Comment by andrewserong** [comment]
Thanks for clarifying! I see, yes, looks like we've got two slightly different use cases to look after:

1. As a user, I want to select multiple text blocks to group them / re-arrange them in a particular way (add spacing / background colours, etc).
2. As a user, I'm editing the content I'm currently writing, and I only want the controls relevant to me as I copy / paste / cut / rearrange text.

Adding some kind of logic that hides the controls when there's a partial selection of text within heading / paragraph blocks sounds good to me 👍

**Comment by ntsekouras** [comment]
Someone could argue that the block toolbar and block actions menu are more about handling blocks as whole.. [This is the approach we will take](https://github.com/WordPress/gutenberg/pull/40098#discussion_r844784257) regarding the `Copy` button in block actions, even if we have partial selection. Personally I don't have a strong opinion on this, but I'm leaning to leaving it as is.

**Comment by andrewserong** [comment]
> Personally I don't have a strong opinion on this, but I'm leaning to leaving it as is.

I think I'm leaning slightly that way, too, since it can be difficult to predict intent just from the existence of a partial selection.

**Comment by annezazu** [comment]
Closing this out as two years on we don't have a way forward.
