### ISSUE TITLE
tinyMCE.editors object is empty after a new paragraph block is inserted

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#4006]
When inserting a paragraph block inside the editor, the `tinyMCE.editors` object is empty and the `tinyMCE.activeEditor` is null.

If I'm not completely wrong, these should include the tinyMCE instance of the paragraph block that was just added.

**Comment by danielbachhuber** [comment]
Thanks for the report @kmgalanakis. I'm not sure how much feature parity we're going to keep with the Classic Editor JavaScript events, but we can keep this open until a decision is made and documented.

Related #4151

**Comment by danielbachhuber** [comment]
Closing on favor of https://github.com/WordPress/gutenberg/issues/6648, which has a bit more detail on this topic.
