### ISSUE TITLE
Previews for custom block styles are not showing in the Site Editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#40064]
### Description

I apologize if this has already been reported, it was not easy to search for these keywords in the GitHub repository.

In the block editor, if a block has a custom style registered, you can hover over the options in the style section to see a  modal/popup with a preview of the style.

But this preview is not present in the Site Editor. Nothing happens when you hover over the style.

And because the style names are truncated, it is difficult to know what the style does.
For example, if I have a button block style called "Button with shadow", the name would have been self explanatory even without a preview: But because the full name is not displaying and instead showing as "Button with...", it is difficult to identify what the style does.

### Step-by-step reproduction instructions

1. Activate a full site editing theme
2.  Open the Site Editor
3. Add a block with a style, for example an image block or a button block.
4. In the block setting sidebar, find the "Styles" section
5. Hover over the different options and see that there is no preview.

### Screenshots, screen recording, code snippet
Site Editor:
![Animation of mouse hovering over the style setting and no preview showing](https://user-images.githubusercontent.com/7422055/161876449-45a931a8-4cd4-4031-9e50-2da74b094683.gif)

Post editor, and expected result:
![Animation of mouse hovering over the style setting and preview is showing](https://user-images.githubusercontent.com/7422055/161877809-2529276a-2ea2-4317-aae0-d0c8a346e49e.gif)

### Environment info

WordPress 5.9.3 Rc1
Gutenberg current trunk
Beta tester plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please

 confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment]
I can replicate this with! Adding as a bug.

**Comment by ndiego** [comment]
Yes, I can replicate it as well.

**Comment by Andrew-Starr** [comment]
Just want to mention https://github.com/WordPress/gutenberg/issues/39944 in case there is any chance it could be related.

Not too sure what components (if any) are shared across site editor and post editor in regard to block style previews.
