### ISSUE TITLE
Allow for partial selection of Style Variations

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40068]
## What problem does this address?

[During the 6.0 walkthrough](https://make.wordpress.org/core/2022/03/30/6-0-product-walk-through/), the option to partially select Style variations was raised, since currently the options are all or nothing when switching between. 
 
## What is your proposed solution?

Provide the ability to only partially select Style variations rather than the entire variation. I imagine this will tie in nicely with the recent exploration from @critterverse for more granular information with multi-entity saving when changing up Styles: https://github.com/WordPress/gutenberg/issues/29388#issuecomment-1089507879

**Comment by critterverse** [comment]
I'm going to close this issue out because style variations could utilize the same Saving panel UI proposed in https://github.com/WordPress/gutenberg/issues/29388#issuecomment-1089507879. IMO, it can start to feel like competing/duplicated UI with the Saving panel when you start recreating these options elsewhere!

**Comment by beckej13820** [comment]
Hi,

This was closed as duplicate, but I wonder if it could be reconsidered. It seems to me that the ability to save changes to styles might be very different than the ability to divide styles in meaningful ways that can help site creators.

The example that I have in my head comes from an older "customizer" style theme named Go from GoDaddy. The creators made two simple choices, "Style" which they defined as Typography, spacing, block options and "Color" which was the color palettes that could be changed independently from the Style.

So from their customizer screen, there were 20 variations of theme. 5 typography and spacing styles, and 4 unique color palettes for each variation.

From experience I can say that the ability to change parts at a time is very convenient. And picking a quick set vs saving my personal/custom settings seems different to me.

![Screen Shot 2022-04-26 at 2 40 10 PM](https://user-images.githubusercontent.com/29982981/165401902-aa8c640a-32a5-42f3-b364-f7874de6dd2c.png)
