### ISSUE TITLE
List View: disable dragging if a block is locked

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40072]
## What problem does this address?

Currently, if a block is locked, you can still begin to drag and drop it in List View. The dropping doesn't actually occur but this experience feels confusing since it allows you to begin the process:

https://user-images.githubusercontent.com/26996883/161881875-2f9b795a-83dd-447a-b267-1417410926c4.mov

[This came up during the 6.0 walk through](https://make.wordpress.org/core/2022/03/30/6-0-product-walk-through/).

## What is your proposed solution?

Disable dragging and drop in list view when block is locked.  cc @andrewserong once more!

**Comment by andrewserong** [comment]
Good catch! I wonder if there should be a locked icon potentially in the list view, too? (Might need some design feedback, if so). Also CC: @Mamaduka has been doing a bunch of work with the locking behaviour, too 🙂

**Comment by annezazu** [comment]
> I wonder if there should be a locked icon potentially in the list view, too?

Opening too many issues and forgot to cross link ;)  https://github.com/WordPress/gutenberg/issues/40070

**Comment by Mamaduka** [comment]
Thanks for creating the issue, @annezazu.

This is on my to-do list, so going to assign it to myself :)

**Comment by andrewserong** [comment]
> Opening too many issues and forgot to cross link ;)

Ah, perfect. Thanks, I missed that one!
