### ISSUE TITLE
List View: Show lock status 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40070]
## What problem does this address?

Currently, if a block is locked, it's not obvious or visible in List View. This causes confusion when, at a glance, it's not clear what might be locked down. [This came up during the 6.0 walk through](https://make.wordpress.org/core/2022/03/30/6-0-product-walk-through/).

## What is your proposed solution?

Pulling from this overview issue https://github.com/WordPress/gutenberg/issues/29864:

![111139473-75e2b800-8581-11eb-8fd1-43ab980cb7a9](https://user-images.githubusercontent.com/26996883/161880784-e24ef113-3f87-412a-89e4-60795e80dba4.png)

Of note, it'll be important to explore design options for locking at scale when many blocks are locked, especially if the ability to apply locking to children blocks comes up https://github.com/WordPress/gutenberg/issues/40069. Finally, there's some discussion around changing the icon to show a partial lock potentially that would be important to ensure corresponds here too https://github.com/WordPress/gutenberg/issues/39916

**Comment by courtneyr-dev** [comment]
Updated. When https://github.com/WordPress/Learn/issues/739 is published, add an internal link within each other. On List View lesson plan, at the bottom add a link to the bullet point about Lock
