### ISSUE TITLE
Prevent site editor inception with latest posts block

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40075]
### Description

After adding a latest posts block to the Site editor, if you click on one of the latest posts, the editor begins to load within itself but stops short. In the case of the person who found this, it loaded all the way through. This was found as part of the [thirteen call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/03/31/fse-program-testing-call-13-authoring-an-author-template/#comment-2393). Previous similar report for context: https://github.com/WordPress/gutenberg/issues/30647

### Step-by-step reproduction instructions

1. Open the site editor.
2. Add a latest posts block
3. Click on the post title link/open the link and see that the post starts to load in the editor. 

### Screenshots, screen recording, code snippet

Begins to load:
https://user-images.githubusercontent.com/26996883/161885574-a02dab1c-413f-49b7-90c9-856123035d7e.mov

Loads:

![issue_testing_call_13](https://user-images.githubusercontent.com/26996883/161885607-a1681277-4ad2-4c56-9a90-a6c4333bf25c.gif)

### Environment info

- WordPress 5.9.3
- Gutenberg nightly 13.0.20220404
- TT2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
This is a great find. I am able to replicate in WP 5.9 with and without Gutenberg active.
