### ISSUE TITLE
Disable Navigation Menu Sidebar from WP 6.0 - retain in Plugin

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#40080]
Given the number of outstanding Issues relating to the Nav Sidebar, and the lack of time for contributors to test and feedback on this feature it should probably not be included in WP 6.0.

We should

- ensure it is not included in code that will land in 6.0
- ensure it _is_ retained in the Gutenberg _Plugin_.

We can use info here https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/feature-flags.md

cc @mtias @priethor

**Comment by ndiego** [comment]
@getdave can this issue be closed since #40083 has been merged?

**Comment by talldan** [comment]
@ndiego I don't think Dave is around at the moment. I agree it can be closed. I did a double-check over the PRs to make sure there were no new APIs being exported that also needed to be made plugin only, and I couldn't see any.
