### ISSUE TITLE
Click/dragging in inspector deselects blocks

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#40091]
The inspector shows up when you select a block. But if you click and drag anywhere inside the inspector, such as to select text, the block gets deselected, as showin in this GIF:
![deselect](https://user-images.githubusercontent.com/1204802/161956713-1276d6ea-18f4-413a-9a8b-9024ac448bd8.gif)

Steps to reproduce:

* Select a block
* Click and drag anywhere in the inspector

Observe that the block gets deselected.

**Comment by ndiego** [comment]
I just confirmed this bug.

**Comment by jasmussen** [comment]
Just to add: this issue happens if you click and drag inside block toolbar submenus as well:
<img width="340" alt="Screenshot 2022-04-19 at 11 02 52" src="https://user-images.githubusercontent.com/1204802/163969478-592693ce-95ef-43b1-b9fe-4f23ed3dd2cb.png">

**Comment by fabiankaegy** [comment]
Just noting here that this issue is also present in WordPress 6.0 Beta 1

**Comment by ndiego** [comment]
This is an issue we really should try and get resolved for 6.0. This might be related to the new functionality that lets you select text across multiple blocks 🤔

cc @annezazu @priethor

**Comment by talldan** [comment]
I've put together a fix at #40604.
