### ISSUE TITLE
Improvements to Header pattern category to better clarify and guide usage

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40116]
## What problem does this address?

In a discussion in post status slack, Brin Wilson and I discussed the current categorization of Header Patterns in the Inserter, pattern directory, etc. It became clear that the current Header category including both items related to a Header for your site _and_ something more akin to Headings proved confusing.  In general, there are two problems:

- Inconsistency in how patterns are prioritized in the Inserter based on editor. Site editor prioritizes patterns for site headers, post editor prioritizes more of a style of "heading" patterns, and template editor matches the post editor despite it likely needing to match the experience of the site editor in prioritizing header patterns. 
- Grouping together of both more classically thought of Headers for the top of a site and more "heading" style sections all within the same category. These serve different purposes so it feels odd to include both. 

Here's a quick video discussing this:

https://user-images.githubusercontent.com/26996883/162061438-a00229ad-003f-49ee-a3fd-54fe5c50abf4.mov

## What is your proposed solution?

A few ideas!

- Consider creating a new category for Headings to separate out patterns that don't carry the same meaning as Header. This will also help as patterns are integrated into the experience more. For example, I might have a more Heading like pattern that I don't want to show up when someone is looking for Headers when adding a new template part. 
- Create consistency in the Inserter experience by having the Template Editor match the Site Editor experience. 

In my opinion, I think it makes sense to branch off a new category of patterns that reflects more of the Heading style patterns where you might want to draw attention to/differentiate a section. This seems like it will most set folks up for success in using these various patterns correctly as well as align nicely with how work is underway to integrate patterns into the experience of doing things like adding a new template part or creating a new template from scratch.

**Comment by mtias** [comment]
Would "Titles" or "Headings & Titles" be better to disambiguate?

**Comment by annezazu** [comment]
With the implementation of bundled Header and Footer patterns https://github.com/WordPress/gutenberg/pull/43157, this issue becomes more important to address IMO. For example, right now the Header patterns are buried beneath the other patterns categorized also as "header" as pointed out by @beafialho in the [original PR](https://github.com/WordPress/gutenberg/pull/43157#issuecomment-1216502943):

https://user-images.githubusercontent.com/26996883/188715360-b6972ed0-b8c0-4347-91e8-17e0c8220f5e.mov

This isn't ideal and it's clear some category separation needs to happen.

**Comment by annezazu** [comment]
As a next step to move this forward, I'm not sure what technically needs to be done here but essentially we want to end up with a new Titles category to house the current "header" patterns and for the "header" category to now contain truly header specific content like these bundled patterns https://github.com/WordPress/gutenberg/pull/43157  We'll also need to update the pattern directory appropriately: https://wordpress.org/patterns/categories/header/

cc @mcsf @ryelle for technical thoughts and to see if either of you can help make this happen ahead of 6.1 :)

**Comment by mcsf** [comment]
cc @carolinan, who has also contributed in this area (e.g. adding a new category for Footer patterns in [t56416](https://core.trac.wordpress.org/ticket/56416)).

***

I can't comment on the pattern directory parts. For the rest, we can easily add a pattern category, both here in Gutenberg in the compat layer and in Core. I opened #44203, have a look.

**Comment by ryelle** [comment]
We can easily add a new "Headings & Titles" category to the Pattern Directory. It wouldn't change any existing patterns though, [anything currently tagged "Header"](https://wordpress.org/patterns/categories/header/) would stay that way. If that's a problem, we could probably write a script to update them, it would just take a little more time.

**Comment by mtias** [comment]
I think we should create a Hero or Banners category and move everything we used to have into it and leave the actual new headers in Headers.
