### ISSUE TITLE
Can't prevent addition of skip-link using PHP

### ISSUE THREAD

**Issue by ClarusDignus** [WordPress/gutenberg#40118]
### Description

I'm creating a block theme from scratch using FSE.

I'm trying to understand how the skip-link is added: https://github.com/WordPress/gutenberg/pull/30336#issuecomment-810094082.

I want to stop the skip-link's script and style being added to each page.

I've tried the following in functions.php:

```
// Attempt 1
remove_action( 'wp_body_open', 'gutenberg_the_skip_link' );

//Attempt 2
remove_action( 'init', 'gutenberg_the_skip_link' );

// Attempt 3
remove_action( 'wp_body_open', 'the_block_template_skip_link' );

// Attempt 4
remove_action( 'init', 'the_block_template_skip_link' );
```

I’m not removing the skip-link; I’m replacing it because I need to wrap it in a div and change the link text to title case:

```
add_action( 'wp_body_open', 'custom_skip_link' );

function custom_skip_link() {
    echo '
    <div class="custom-skip-link-container">
        <a class="custom-skip-link" href="#content">Skip to Content</a>
    </div>
    ';
}
```

I can remove the skip-link using jQuery but I’d prefer to stop it being added in the first place using PHP.

```
(function($) {
    $(document).ready(function() {
        $("a.skip-link, style#skip-link-styles").remove();
    })
})(jQuery);
```

### Step-by-step reproduction instructions

1. Open functions.php.
2. Try to prevent addition of skip-link by removing one of the following actions: gutenberg_the_skip_link() or the_block_template_skip_link().

### Screenshots, screen recording, code snippet

- [gutenberg_the_skip_link()](https://github.com/WordPress/gutenberg/pull/30336#issuecomment-810094082)
- [the_block_template_skip_link()](https://developer.wordpress.org/reference/functions/the_block_template_skip_link/)

### Environment info

- WordPress 5.9.2 using custom block theme created using FSE
- Gutenberg 12.9.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Gierand** [comment]
@ClarusDignus try this:
`remove_action( 'wp_footer', 'the_block_template_skip_link' );`

**Comment by ClarusDignus** [comment]
> @ClarusDignus try this: `remove_action( 'wp_footer', 'the_block_template_skip_link' );`

That worked. Thanks. My bad. I didn't consider wp_footer(). I incorrectly assumed the_block_template_skip_link() was being applied to wp_body_open() because of the skip-link's position in the page.

I can see now that the skip-link's position is determined in relation to the site wrapper using JavaScript:	

```
// Get the site wrapper.
// The skip-link will be injected in the beginning of it.
sibling = document.querySelector( '.wp-site-blocks' );
```
