### ISSUE TITLE
Floated block appears above next contextual toolbar

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#4012]
## Issue Overview

When a block is floated (e.g. image, button) and the user has activated contextual toolbars (from settings dropdown), selecting the block immediately following the floated block will cause the floated block to appear above the contextual toolbar.

## Steps to Reproduce (for bugs)

Prerequisite: Set "Fix toolbar to block":

![Fix toolbar to block](https://user-images.githubusercontent.com/1779930/34008920-f248bf98-e0d4-11e7-8b9a-a74bf231b080.png)

1. Navigate to Posts > New Post
2. Insert a button block
3. Float the button block left
4. Insert a paragraph block

## Expected Behavior

Toolbar appears above floated block.

## Current Behavior

Floated block appears above toolbar.

## Possible Solution

Problematic styles occur here:

https://github.com/WordPress/gutenberg/blob/79c3f3448118fd8ab5f953138df033b25edfd77d/editor/components/block-list/style.scss#L116-L122

It appears the `z-index` was added originally to resolve selectability issues of floated content.

## Screenshot

![Screenshot](https://user-images.githubusercontent.com/1779930/34008871-c0cd571c-e0d4-11e7-9e8c-f174db715a74.png)

**Comment by noisysocks** [comment]
I'm not able to reproduce this. It looks like the toolbar now shifts over to accomodate the button.

![button](https://user-images.githubusercontent.com/612155/34806196-b7397732-f6d5-11e7-9a39-f715ba77aff1.gif)
