### ISSUE TITLE
It is not clear that the title and excerpt field in the Summary panel can be edited

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#40124]
## What problem does this address?
In the new summary panel in the document settings, it is not obvious that the title and excerpt are editable fields.
They look like plain text.

![two paragraphs of plain text are visible below the featured image input field.](https://user-images.githubusercontent.com/7422055/162119965-47b84bf7-e41e-4740-9264-436ee3b98782.png)

## What is your proposed solution?

Please re-consider the usability impact that removing visible and recognizable input fields have for users.

Please re-add a visible border or outline so that the fields can be recognized as editable input fields.

It is also not clear how to resize the excerpt field. It does accept more than one line, but it is not clear that it only expands when you write a text that is long enough.

**Comment by Mamaduka** [comment]
Cc @javierarce @jasmussen

**Comment by jasmussen** [comment]
This is one of the main take-aways in the summary I just wrote on the [revert PR](https://github.com/WordPress/gutenberg/pull/40128#issuecomment-1091114713). The short of it is, as a summary generated based off metadata, the panel can be useful. But the method for adding this metadata is probably not possible to absorb into the same panel, and requires more thought. In that light, this brief time it had in trunk can help inform #39082.
