### ISSUE TITLE
The row group block variation does not display its own icon in the list view

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#40137]
### Description

There is room for a small enhancement here, the stack variation displays its own icon in the list view, but the row variation shows the group block icon.

### Step-by-step reproduction instructions

Add two group blocks, one with a row variation and one with a stack variation.
Open the list view and compare the icons.

### Screenshots, screen recording, code snippet

![the list view shows two icons, one for the stack and an incorrect icon for the row](https://user-images.githubusercontent.com/7422055/162172060-cb2a26c1-3777-4f5d-9494-32ab681ae03e.png)

### Environment info

WordPress 5.9.3
Gutenberg current trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Oh, and the name 😄

**Comment by Mamaduka** [comment]
Maybe I'm missing something, but I couldn't reproduce the issue when adding Row/Stack from the inserter.

![CleanShot 2022-04-07 at 15 16 23](https://user-images.githubusercontent.com/240569/162187132-ad3cb2fd-8f49-49ad-9dbd-a42a99d664bf.png)

**Comment by carolinan** [comment]
I also can no longer reproduce this issue.
