### ISSUE TITLE
Polish the flow to set the featured image as the cover background

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40156]
This is an awesome feature, but the design could perhaps use a little polish. Here's the current implementation:

<img width="400" alt="Screenshot 2022-04-07 at 15 29 03" src="https://user-images.githubusercontent.com/846565/162223069-d8aed910-0a68-4c75-b1f7-cfd3fe8dcaab.png">

I didn't spot it at first – my eye mistook the "[icon] Add media" area of the toolbar for a single button. 

An alternative would be to add an option in the "Add media" (and subsequent "Replace") popover:

<img width="292" alt="Screenshot 2022-04-07 at 15 34 00" src="https://user-images.githubusercontent.com/846565/162224211-2ed31818-a7f4-48cd-a9f7-c4b4c678d4a4.png">

I think the label can be helpful here. Additionally we might surface the option in the placeholder state:

<img width="553" alt="Screenshot 2022-04-07 at 15 34 52" src="https://user-images.githubusercontent.com/846565/162224271-b4e4b291-9233-48a4-914c-7663ac1f148b.png">

The description should be updated too :)

---

Finally, in the site editor it would be nice to have some visual feedback on the canvas when the featured image is set to be used by a Cover block. At the moment it looks empty:

<img width="1030" alt="Screenshot 2022-04-07 at 15 38 22" src="https://user-images.githubusercontent.com/846565/162225038-c41cf6a0-788d-4c8b-bcd6-95128beaf5cf.png">

Perhaps we can re-use the Featured Image placeholder treatment:

<img width="958" alt="Screenshot 2022-04-07 at 15 39 23" src="https://user-images.githubusercontent.com/846565/162225168-4ae78e61-679d-4f9f-8d6a-f73762bff7a9.png">

**Comment by jasmussen** [comment]
One of the design solutions we [explored](https://github.com/WordPress/gutenberg/pull/39410#issuecomment-1066763242) was this one:
<img width="3440" alt="158177703-2eca393c-96c2-4a23-a4a6-90f8d86b57c7" src="https://user-images.githubusercontent.com/1204802/162672239-3f22aca9-468e-4de2-954d-034c8ef51d4b.png">

Essentially:

* If a featured image is set in the inspector, then the replace button will show the toggle
* If you untoggle, the image is just removed

The benefit of this approach is that it doesn't expand the block toolbar (despite being in the mockpus, I don't think we should change the "Replace" label), and it would scale for any media block that has a "Replace" in the toolbar.

**Comment by jameskoster** [comment]
Oh yeah, that's virtually the same idea :D I don't know that we need to hide the other options (upload / open media lib) when the featured image is being used though?

**Comment by jasmussen** [comment]
> I don't know that we need to hide the other options (upload / open media lib) when the featured image is being used though?

I like them hidden, because it simplifies what happens if you choose any of those options. I.e. what happens to the toggle if you upload an image?

**Comment by jameskoster** [comment]
> what happens to the toggle if you upload an image?

I don't think anything needs to happen? 

The popover is exposed in two flows: 1. Choose media, 2. Replace media. In both flows I would expect to see all options immediately. Incidentally this is how these flows work currently, and I'm not sure that the introduction of the featured image option warrants any changes 🤔

**Comment by jasmussen** [comment]
Well the toggle would need to be untoggled, if you replaced the featured image with a single one, right?

One additional gotcha we ran into on the PR, is that we can't necessarily "remember", at least beyond a single-session basis, what image was set before the toggle was flipped. So in some most cases, doing so will just remove the image, reverting to a setup state or solid Cover bg color.

**Comment by jameskoster** [comment]
> Well the toggle would need to be untoggled, if you replaced the featured image with a single one, right?

I'm probably missing something obvious but why is that a problem?

> So in some most cases, doing so will just remove the image, reverting to a setup state or solid Cover bg color.

Doesn't this issue exist with the current implementation as well? In any case I think that's a symptom of the featured image option behaving as a toggle. Maybe it doesn't need to. Another option would be to include a 'Clear media' option in the 'Replace' popover.

<img width="305" alt="Screenshot 2022-04-11 at 10 30 33" src="https://user-images.githubusercontent.com/846565/162709977-7e0d1926-efcf-4b9b-83a3-79087b2d5b3c.png">

**Comment by jasmussen** [comment]
> I'm probably missing something obvious but why is that a problem?

It might not be in practice! I feel like it might confuse you with the ability to _upload a new featured image_ from there. It seems like if that's a flow we want to enable, the dropdown (and initial setup state) likely needs additional context and a rearrangement to handle that.

**Comment by jameskoster** [comment]
Perhaps It should only be possible to instruct the Cover to use the featured image when one has already been set. In fact that highlights another issue with the current implementation:


https://user-images.githubusercontent.com/846565/162714691-ce44cd45-471a-4854-ab65-e540402ad337.mp4


In the video above I can't edit the contents of the cover after setting it to use the featured image, because a featured image hasn't been set yet.

I suppose another option would be to trigger a "choose a featured image" UI.

**Comment by jasmussen** [comment]
> Perhaps It should only be possible to instruct the Cover to use the featured image when one has already been set. In fact that highlights another issue with the current implementation:

Yes, the challenge there is using the Cover for featured images in archive templates where it will only be filled out in the right contexts. Another option is to show dashed lines to indicate the state:
<img width="3440" alt="Set Media   Text as featured image" src="https://user-images.githubusercontent.com/1204802/162715876-4e7d2211-556f-49ed-8b70-b20406a71e8d.png">

_That's Media & Text instead of Cover, but the principle would be the same._

**Comment by jameskoster** [comment]
Yep, I think that makes sense. We might even do something similar in the post editor if you set the cover to use the featured image, but one isn't set yet...

Here are some prototypes.

### Post editor, featured image is set
https://user-images.githubusercontent.com/846565/162721861-c0a50375-3ea3-4670-a093-d321a14d8a31.mp4

### Post editor, featured image is not set

https://user-images.githubusercontent.com/846565/162722756-a17101c7-1989-4e11-989f-fda53d1f0e6e.mp4

An alternative to the dashed placeholder here would be to simply open the media library and ask the user to select or upload a featured image.

### Site editor

https://user-images.githubusercontent.com/846565/162722851-2f926ec4-4cc8-4e64-ae2d-fc3369503e2a.mp4

Try the prototypes [here](https://www.figma.com/proto/Wm9Ae955IejY1MNJlrA6xl/Cover-featured-image?page-id=0%3A1&node-id=1%3A491&viewport=376%2C48%2C0.47&scaling=scale-down&starting-point-node-id=1%3A491&show-proto-sidebar=1).

**Comment by jasmussen** [comment]
> An alternative to the dashed placeholder here would be to simply open the media library and ask the user to select or upload a featured image.

The problem with this is that if you save the page in this state, then reload, the media library will pop up for every block that has this state. Unless we build gnarly smarts.

I like your prototypes! I'd keep a singular "Replace" word instead of "Replace media", though.

**Comment by jameskoster** [comment]
> The problem with this is that if you save the page in this state, then reload, the media library will pop up for every block that has this state. Unless we build gnarly smarts.

Oh no, I meant that the modal would appear when you actively click "Use featured image". If you were to then exit the media library without setting a featured image the block would simply remain unchanged. Just for completeness, here's a video:


https://user-images.githubusercontent.com/846565/162734151-29e5fe6c-7bce-4033-aff3-94b117e29c8b.mp4

**Comment by draganescu** [comment]
@javierarce one issue with the media replace flow integrating the use featured image option is that use featured image is a toggle menu item, while the others are normal menu items that action something else. That means the only item that gets a pressed state is this one, while the others never are pressed.

**Comment by jameskoster** [comment]
Why is that a problem? 🤔 

I'd expect the menu to look something like this:

<img width="1031" alt="Screenshot 2022-06-07 at 17 08 41" src="https://user-images.githubusercontent.com/846565/172429453-7f06f5ce-9022-410d-a6c0-c17bbf422ca4.png">

Clicking the "Use featured image" menu item would toggle the option off – effectively its the same as clicking "Clear media".

Choosing either of the other options would also toggle the "User featured image" option off after uploading / choosing an alternative from the media library.
