### ISSUE TITLE
Embed block strips fragments from URLs

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#40166]
### Description

Pasting a URL with a fragment -- _eg, `https://make.wordpress.org/core/2022/02/21/editor-chat-agenda-february-23rd-2022/#comment-42611`_ -- into the editor wipes out the fragment.

When I intend to link to a _comment_, the block links to the _post_ instead.

The saved markup does contain the fragment, but the rendered block strips it out.

```html
<!-- wp:embed {"url":"https://make.wordpress.org/core/2022/02/21/editor-chat-agenda-february-23rd-2022/#comment-42611","type":"wp-embed","providerNameSlug":"make-wordpress-core"} -->
<figure class="wp-block-embed is-type-wp-embed is-provider-make-wordpress-core wp-block-embed-make-wordpress-core"><div class="wp-block-embed__wrapper">
https://make.wordpress.org/core/2022/02/21/editor-chat-agenda-february-23rd-2022/#comment-42611
</div></figure>
<!-- /wp:embed -->
```

It does the same thing with query parameters -- _eg: `https://make.wordpress.org/core/2022/02/21/editor-chat-agenda-february-23rd-2022/?foo=bar`_ -- although I can't think of a practical problem there off the top of my head.

Ideally it should also embed the content of the _comment_ rather than the _post_, but that may be for another issue.

### Step-by-step reproduction instructions

1. Paste `https://make.wordpress.org/project/2021/09/10/suggested-iterations-for-the-five-for-the-future-program-and-tool/#comment-24` into the editor
1. Wait for the Embed block to render
1. Hover over the title link, observe that it's missing the fragment

If you publish the post and visit it on the front end, it also has the fragment stripped out.

### Environment info

* Core `6.0-alpha-53087`
* Gutenberg `12.9.0`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@iandunn I think this is possibly a WordPress core issue, testing the classic editor I see the same behavior. Perhaps the fragment is being stripped by the embed handler server side.

edit: I found this, it seems like the same issue https://core.trac.wordpress.org/ticket/49682.

**Comment by iandunn** [comment]
Ah, good find! I'll close this then 👍🏻
