### ISSUE TITLE
Make focus mode accessible from the template editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40184]
In the Site Editor it's possible to edit template parts in isolation like so:

https://user-images.githubusercontent.com/846565/162429505-8be90a95-22c2-4deb-b79a-3aecd3120540.mp4

However it's not possible to access this mode in the template editor (Edit post > Open 'Template' Inspector panel > click 'Edit'), should it be?

**Comment by jameskoster** [comment]
Still relevant

**Comment by mtias** [comment]
This is possible now from the post editor > template editor flow:

<img width="1524" alt="image" src="https://github.com/user-attachments/assets/5af2c246-70ac-49b0-9f6b-37364f09cc22">
