### ISSUE TITLE
Is Dragging CSS is only needed for the editor not front-end.

### ISSUE THREAD

**Issue by turtlepod** [WordPress/gutenberg#40190]
I think this CSS `.is-dragging` is for editor.scss and not for style.scss?

https://github.com/WordPress/gutenberg/blob/5d0940dfcc142f13696963ee2e0de6a49e7b1065/packages/block-library/src/gallery/style.scss#L145

**Comment by glendaviesnz** [comment]
Thanks for reporting. This was [removed here](https://github.com/WordPress/gutenberg/pull/38164/files#diff-41629d44df4cc8609f305c127f4f22111c6853e357645e1b3eb88a1d906360b0L144), and this change went out in the 12.9 release.
