### ISSUE TITLE
Introduce "Caption" as a new element

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#40205]
Hinted at in #34574.

It's time to move towards introducing some new elements to the Elements API. Captions are used across blocks (images, embeds, videos, etc) and a prime example of what we have called elements in the global styles' sense. Right now core registers some default styles for captions through `wp-block-styles`, which we should transition to this system.

Captions would become a new element alongside Links in the interface, and can be defined globally or per block type.

At the block level, we should probably introduce a new component to encapsulate the definition, class, CSS variables, etc. Blocks can use this component like they use `RichText` (it'd be a wrapper around RichText anyways).

**Comment by scruffian** [comment]
Related: https://github.com/WordPress/gutenberg/issues/41966

**Comment by scruffian** [comment]
This was closed by https://github.com/WordPress/gutenberg/pull/41140

**Comment by mtias** [comment]
@scruffian can we add a follow up to add the UI for it in global styles?

**Comment by MaggieCabrera** [comment]
I created the issue [here](https://github.com/WordPress/gutenberg/issues/44071)

**Comment by mtias** [comment]
Thanks!

**Comment by aaronrobertshaw** [comment]
I'm a bit late to this party but thought it worth noting that while https://github.com/WordPress/gutenberg/pull/44094 introduces UI controls for the new caption element, it does differ a little from what the RichText component for individual block captions currently offers.

> At the block level, we should probably introduce a new component to encapsulate the definition, class, CSS variables, etc. Blocks can use this component like they use RichText (it'd be a wrapper around RichText anyways).

This part of the issue suggests to me that we still need to address the gaps and this isn't fully closed?

Things that can be configured through the element API and Global Styles (as of #44094)  but not at the individual block level are:
- Font family
- Font size
- Line height
- Font weights other than bold or normal

A [standalone block for captions](https://github.com/WordPress/gutenberg/pull/31823) might be worth revisiting. What do you think?
