### ISSUE TITLE
Undo and redo can cause undesired page scrolling in the visual editor

### ISSUE THREAD

**Issue by ParticleMon** [WordPress/gutenberg#40203]
### Description

Visual editor undo/redo may scroll the page when an edit is off-screen.

This applies only to the visual editor, not the code editor.

This behavior is exhibited at least in Chromium-based browsers. Although I haven't tried browsers based on Firefox or WebKit, it is expected to be browser engine agnostic.

This behavior has been present for years--from the first version of WordPress I used through the latest. Its presence compels me to use my text editor of choice instead and then copy/paste into the visual editor.

Expected: Visual editor undo/redo matches that of the code editor, in which the page is scrolled only when the edited block is off-screen.

Expected: Edit history is not lost when switching between the visual editor and the code editor, which one might try, in part, to work around the undesired scrolling that may be caused by visual editor undo/redo.

### Step-by-step reproduction instructions

It depends.

### Environment info

WordPress 5.9.3 and earlier
Chromium-based browsers
Linux desktop

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg and WordPress. Therefore, I am going to close this issue. If anyone can replicate it in the future, please feel free to reopen this issue with additional information.
