### ISSUE TITLE
Allow transforming from Group to Cover

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#40209]
This is a transformation we really need to offer. Right now if you want to transition a set of blocks into a cover you need to jump through some hoops.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/548849/162616913-986e0c1e-42d2-46d4-be58-b3eadd09b9f3.png">

One consideration to make, particularly for group variations (stack / row): should the transform modify the container block to cover or should it preserve the group and add a cover as an extra wrapper?

cc @apeatling @andrewserong

**Comment by Mamaduka** [comment]
This transformation is already supported - #30890, but there's a very specific `isMatch` check, so the option isn't always visible.

https://github.com/WordPress/gutenberg/blob/7f2978aea1e9a146ba6e05cee4aa9b588e24b862/packages/block-library/src/cover/transforms.js#L63-L77

Edit: I think there's no need to require background color after #31402.

**Comment by mtias** [comment]
Right! Seems it should be an irrelevant condition now.

**Comment by andrewserong** [comment]
Nice idea! I think I've got something working okay, I'll open up a PR shortly.

**Comment by andrewserong** [comment]
I've opened up a PR in #40212 — there was a bit of a decision involved in figuring out a default `dimRatio` that works well enough so that it's clear what's going on once a user starts interacting with adding images or background colors to the Cover block. Happy for any feedback over on that PR!
