### ISSUE TITLE
 Add image brakes page in backend

### ISSUE THREAD

**Issue by ToniGuga** [WordPress/gutenberg#40200]
### Description

 Hello there,
i've problems with adding images using the default block and acf add image functions. After clicking no modal appears anche the page brokes and i have to reload the page. I did a downgrade to 5.9.0 and everything works greate. I've the same issue with the default wp image block

Hope this helps

### Step-by-step reproduction instructions

![Screenshot 2022-03-01 at 14-21-51 Modifica pagina “Test Pagina Marco” ‹ Playground - Stage   Learn — WordPress(1)](https://user-images.githubusercontent.com/9418869/162564475-97b3b008-7a7e-40da-b944-9611d78994a1.png)

### Environment info

wp 5.9.3
laptop win 11 latest version, using firefox latest version

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ALJ** [comment]
Hi @ToniGuga I have seen a problem like that and it was solved by upgrading ACF to version 5.12 or higher. [The ACF changelog](https://www.advancedcustomfields.com/changelog/) has it listed as:
> 5.12: Fixed an issue with the media library not working correctly in ACF Blocks in WordPress 5.9.1

**Comment by amustaque97** [comment]
Hi @ALJ , thank you for your input. Looks like this issue is related to **ACF**.  Closing this issue in favour of [comment](https://github.com/WordPress/gutenberg/issues/40200#issuecomment-1094161469).  If this issue still persist. Feel free to reopen.
