### ISSUE TITLE
Link-text highlight-color issue in paragraph and Heading block 

### ISSUE THREAD

**Issue by KAJALwp** [WordPress/gutenberg#40214]
### Description

When I try to add a highlight color for link text in paragraph and heading block it is working properly, but when I edit the link text then the highlight color is removed and link text shows the default color.
For more information I provide the video attachment link.

### Step-by-step reproduction instructions

1. Go to editor
2. add paragraph or heading block
3. enter text and select text for link
4. add link for text
5. choose highlight color for link text
6. edit the link text

### Screenshots, screen recording, code snippet

https://screencast-o-matic.com/watch/c3fX1aVqd4l

### Environment info

WordPress version: 5.9.3
Google chrome version: Version 100.0.4896.75 (Official Build) (arm64)
OS Version: Mac 12.3.1
Gutenberg Plugin Version: 12.9.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Greatdane** [comment]
Note, this seems to only happen if you first select a block color as well. 

1. Add paragraph block.
2. Enter text
3. Give paragraph block a color via block settings
4. Give some text a hyperlink
5. Highlight on the hyperlinked text will not work.

**Comment by annezazu** [comment]
I couldn't replicate this with 6.6.2 and GB 19.1! I'm going to close this out as a result but, if anyone can still replicate, happy to reopen:

https://github.com/user-attachments/assets/c10b53a6-cf3e-458d-9fcc-feb2b97b1f4c
