### ISSUE TITLE
For blog post, although 3 columns is selected, showing up as 2.

### ISSUE THREAD

**Issue by lisastriker** [WordPress/gutenberg#40218]
### Description

On the blogpost page, i select POSTS and i put columns as 3. However on the front-end page, i only see 2 columns. When i inspect the elements. i notice that the `<ul class="wp-container-19 is-flex-container columns-2 alignwide wp-block-post-template></ul>`

When i change the class to columns-3 in the inspector, the columns then show up on my front-end correctly. This means that the class columns-2 is not being changed to columns-3 by the editor. This seems to be a bug that i can't seem to fix. Adding classes to post also does not affect the `<ul> as it is nested. `Any ideas on how to solve this?

I have deactivated all my plugins and still have this problem.

### Step-by-step reproduction instructions

Go to blog page. 
Click Blocks, select Posts.
Set it to Grid. Select 3 as column.

### Screenshots, screen recording, code snippet

![gutenberg post2](https://user-images.githubusercontent.com/18165904/162690286-76298037-9680-431f-a783-ea7e0fb40333.jpg)
![gutenberg post](https://user-images.githubusercontent.com/18165904/162690296-7d3f532b-05d9-4e7f-9cdd-e7689e768987.jpg)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
👋 Thanks for the issue! I couldn't reproduce this. Can you share a small video with the problem you're facing?

**Comment by aurooba** [comment]
Hi @lisastriker! Thanks for the bug report! From your screenshot in the block editor (very helpful, thank you!), it looks like the block you are using is not a default WordPress block, but rather a custom block that likely came with a plugin or theme you have active. The core Columns block that comes with WordPress has the following icon:
<img width="136" alt="screenshot of the columns icon for the core/columns block in WordPress" src="https://github.com/WordPress/gutenberg/assets/6925260/8adeca6c-5538-4491-bdcf-14ecaccf19fe">

You'll want to check with the plugin or theme author that created that custom block and report the bug to them.
