### ISSUE TITLE
Edit button doesn't do anything when editing an Audio block

### ISSUE THREAD

**Issue by bradyvercher** [WordPress/gutenberg#4021]
## Issue Overview

After inserting an audio block, the Edit button is visible in the BlockControls toolbar, but doesn't actually do anything when the block is an editing state.

## Steps to Reproduce (for bugs)

1. Insert an Audio block
2. Click the Edit button (pencil icon) in the toolbar
3. Nothing happens

## Expected Behavior

I would expect the button to not be available when the placeholder is visible. Or it could open the media modal to select an audio file like the Image and Video blocks do.

## Screenshots / Video

<img width="688" alt="screen shot 2017-12-14 at 4 16 34 pm" src="https://user-images.githubusercontent.com/1302030/34020648-3beffa70-e0ea-11e7-9cb4-c9e21a01486b.png">

**Comment by Soean** [comment]
In the Audio block you can insert an URL or select a file. So the edit button should bring back the placeholder, to change the URL or select another file. To solve this issue I would hide the edit button when the placeholder is visible.

The Video block has no URL option yet, but there is a ticket #3386. So this Block should get the same behavior.

**Comment by aduth** [comment]
Fixed by #5431

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521135853000146)._
