### ISSUE TITLE
Full site editing: Wrong navigation active link when for post page.

### ISSUE THREAD

**Issue by PatelUtkarsh** [WordPress/gutenberg#40222]
### Description

When adding post page in full site editing navigation page (WP core settings -> readiung -> Your homepage displays -> posts page). 

In frontend, active link has wrong global `$post` reference causing [wrong active state. ](https://github.com/WordPress/gutenberg/blob/6d1496a88b92c751ef5322361a53b889ab97c03e/packages/block-library/src/navigation-link/index.php#L153)

### Step-by-step reproduction instructions

1. Make sure **post page** exists or add new blank page and configure post page. (WP core settings -> reading -> Your homepage displays -> posts page) 
1. Go to full site edit -> Template part -> Header. 
1. Remove navigation.
1. Add random page link as first item.
1. Add second item as from page created in point 1. 
1. Open frontend and click on the second link from the menu. 
1. See active state is still first item. (Expected to be 2nd one). (Expected to have class `current-menu-item`)

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/5015489/162725803-57fb2928-5e49-4c6d-8ba9-172e5b2e8006.mp4

### Environment info

1. WP: 5.9.3
1. Twenty Twenty-Two as active themes.
1. Gutenberg: not installed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aezazs-multidots** [comment]
Hello @PatelUtkarsh 

I have tried to reproduce the same issue, and yes I also got the issue of the Wrong navigation active link.

**Following are the environment info**
WordPress:- 5.9.3
Active Theme:- Twenty Twenty-Two
Mac OS:- Monterey 12.2.1
Chrome:- Version 99.0.4844.84 (Official Build) (arm64)

Please review from your end and let me know if there is anything.

Thank you.

**Comment by KAJALwp** [comment]
Hello @PatelUtkarsh, @carolinan 

I have tried to reproduce the same issue, and yes I am also facing the same issue, with and without Gutenberg plugin.

Following are the version details
WordPress:- 5.9.3
Theme: Twenty Twenty-Two
Gutenberg Plugin:- 13.1.0
Mac OS:- Monterey 12.3.1
Chrome:- Version 99.0.4844.84 (Official Build) (arm64)

Thank you.

**Comment by Mamaduka** [comment]
I believe this issue was fixed by @carolinan in #43800.

I can no longer reproduce it with Gutenberg 14.1 or the current trunk.
