### ISSUE TITLE
Ensure new template options aren't empty (author, date, taxonomy, category, tag)

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40238]
## What problem does this address?

The emptiness of the various new templates for 6.0 has come up twice now in pieces of [FSE Outreach Program feedback for the thirteenth call for testing: ](https://make.wordpress.org/test/2022/03/31/fse-program-testing-call-13-authoring-an-author-template/)

>Author template starts out all naked/blank. Here I expected to have some kind of placeholder, guidance/hand holding or perhaps a question asking if I want to include the Header and Footer I have used for pages.

>The empty template would make sense if I was building something from scratch. However, this is not a from-scratch project. It was built from a theme with existing archive.html and index.html files, ancestors in the template hierarchy. Since the author template is merely a more specific version of the archive template, it should be a copy of its “parent” in the hierarchy.

>I would like the header/footer from front page automatically added to the inheriting templates

## What is your proposed solution?

For each new template being added, ensure where possible there are some basic template parts added (header & footer) and/or reusing what's in place for the "ancestors in the template hierarchy". I understand work is [underway to add patterns when creating a new template](https://github.com/WordPress/gutenberg/pull/39147) but this seems separate and important to have in place ideally for 6.0. For context, when creating a brand new template via the Post Editor, the template there isn't completely blank either. It seems we should keep that consistent.

**Comment by jameskoster** [comment]
https://github.com/WordPress/gutenberg/pull/37258 would fix this.

**Comment by annezazu** [comment]
Closing out in favor of https://github.com/WordPress/gutenberg/issues/41060
