### ISSUE TITLE
[Block] Highlight (show first) in the Block Inserter those child blocks specifically related to a parent over the “generic” blocks

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#40233]
## What problem does this address?

As per this [contributor's feedback](https://make.wordpress.org/test/2022/04/08/help-test-the-comments-blocks-for-wordpress-6-0/#comment-2407)

> I do see one problem in relation to all the smaller inner blocks. As the Block Inserter can be filled up with blocks making it more difficult in finding the blocks one needs. This means creating a better organized block library. There is an issue for it somewhere on the Gutenberg repo that brings this up.

## What is your proposed solution?

It would be great if the Block Inserter could highlight/promote those child blocks that are specific to a parent block over the “generic” blocks

For example, as explained in this [Call for Testing post ](https://make.wordpress.org/test/2022/04/08/help-test-the-comments-blocks-for-wordpress-6-0/) the [_Comments Query Loop_](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/comments-query-loop) works with a set of child blocks like [_Comment Author Name_](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/comment-author-name) or [_Comment Date_](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/comment-date). By default, these Comments child blocks should appear in first place in the Block Inserter inside the _Comments Query Loop_

**Comment by paaljoachim** [comment]
Associated:
Making inner blocks easier to locate.
https://github.com/WordPress/gutenberg/issues/38578

**Comment by youknowriad** [comment]
If I'm not wrong this is already the case now. For instance if you insert the "buttons" block, and select it, the "button" block will always be highlighted at the top. Let me know if I'm missing anything.
