### ISSUE TITLE
[Block] Comments Query Loop block not splitting comments into initial written paragraphs

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#40248]
## What problem does this address?

I noticed that adding lots of text in paragraphs, shows all the text lumped together into one text.

Result:
![Screenshot 2022-04-12 at 08 38 37](https://user-images.githubusercontent.com/5323259/162896897-513217ef-f945-4964-a192-f9767923c366.jpg)

## What is your proposed solution?

Have it split into the paragraphs it was written in.
![Screenshot 2022-04-12 at 08 39 39](https://user-images.githubusercontent.com/5323259/162896903-a0d686c7-a242-404c-bc87-213d27124e33.jpg)

**Comment by costdev** [comment]
## Test Report

### Environment
* Server: Apache (Linux)
* WordPress: 6.0-beta3-53290-src
* Browser: Chrome 100.0.4896.127
* OS: Windows 10
* Theme: Twenty Twenty-Two
* Plugins:
  * Gutenberg (trunk)

### Steps
1. Post three comments: 1) A single line comment. 2) A multiline comment. 3) A comment with multiple paragraphs.
2. Notice that the line breaks are not respected. Wall of text.
3. Apply #40667.
4. Run `npm run build`.
5. Refresh the page.
6. Notice that the line breaks are now respected.

### Results
1. Original issue reproduced. ✅
2. #40667 resolves the issue. ✅

### Notes
Once the tests are passing, this looks good to me for merging.

### Screenshot
![image](https://user-images.githubusercontent.com/79332690/165663982-32949770-45c3-4627-8471-6604f537a78d.png)
