### ISSUE TITLE
When editing a link in a button block, linkTarget is reset even though only the url is changed.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#40243]
### Description

https://user-images.githubusercontent.com/31400297/162871564-3a4a2d94-fc2a-47cf-8615-ad60b2229ea8.mp4

### Step-by-step reproduction instructions

1. Set up a button block.
2. Set the URL for the link and turn on "Open in new tab".
3. Edit the URL using the "Edit" button and click the "Submit" button to save.
4. Then "Open in new tab" will be turned off.

### Environment info

- WordPress 5.9.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hz-tyfoon** [comment]
Looks like This issue is simillar to (issue: #42032)
And can be fixed also by (PR #42073)
