### ISSUE TITLE
Buttons in Quote block toolbar randomly shift position

### ISSUE THREAD

**Issue by bradyvercher** [WordPress/gutenberg#4024]
## Issue Overview

When working with the Quote block, the buttons in the toolbar randomly shift position depending on which field is focused.

## Steps to Reproduce (for bugs)

1. Insert a quote block
2. View the position of the buttons in the toolbar
3. Focus the citation field (the buttons shift position)
4. Deselect the block and reselect it (the buttons shift again)

## Expected Behavior

I expect the buttons to always appear in the same order.

## Screenshots / Video

![quote-block](https://user-images.githubusercontent.com/1302030/34021727-35485a72-e0f0-11e7-91b5-095a2cdecf58.gif)

**Comment by danielbachhuber** [comment]
Weird! It looks like the "randomness" is that the initial toolbar is different than the focused one:

![image](https://user-images.githubusercontent.com/36432/35302965-3f5bb2ce-0045-11e8-8aaf-7c9aaf0fff0d.png)

![image](https://user-images.githubusercontent.com/36432/35302995-5b5efdd2-0045-11e8-983b-b069f6d6fcae.png)

I'm not sure where this variation is located though.

**Comment by rahulsprajapati** [comment]
yes, this seems like the way we are appending `components-toolbar` into `editor-block-toolbar`. The initial toolbar ( when we select the blog ) and when we try to focus on editor toolbar is adding different way.

The initial toolbar and when we transform into another block.

![screen shot 2018-01-24 at 5 36 43 pm](https://user-images.githubusercontent.com/10358350/35331521-bc645738-012d-11e8-8ce0-1e47e2d548fd.png)

When we focus on another text in the block.

![screen shot 2018-01-24 at 5 37 16 pm](https://user-images.githubusercontent.com/10358350/35331533-ca9b1080-012d-11e8-9527-4c3a413f6cda.png)

I think this is located in block-toolbar component. Still couldn't find the place where this switch the position yet.
 https://github.com/WordPress/gutenberg/blob/master/editor/components/block-toolbar/index.js#L24-L27

and rendered with "Formatting.Toolbar" fill
https://github.com/WordPress/gutenberg/blob/master/blocks/editable/index.js#L866

**Comment by mtias** [comment]
This is fixed for me.
