### ISSUE TITLE
[Block] Comment Template -> Columns -> change parent and inner blocks text colors

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#40257]
### Description

1.  Comment Template -> Columns. Change the text color to white.
2.  Click Comment Date/Comment Author. Change the text color to green.

Which should decide the color of the Comment Date/Comment Author?
Parent or the inner block itself?

 

### Step-by-step reproduction instructions

See above.

### Screenshots, screen recording, code snippet

Backend Columns selected.
Notice Color:
Text is white
Background has a gradient.
![Screenshot 2022-04-12 at 10 03 19](https://user-images.githubusercontent.com/5323259/162911685-a5e676fc-7a01-4831-9e2b-f182b98e8e8c.jpg)

Selecting Comment Author.
Notice Color: 
Text changed to orange.
![Screenshot 2022-04-12 at 10 05 22](https://user-images.githubusercontent.com/5323259/162912015-76ef001e-025b-44a2-9291-001eb96e6681.jpg)

Frontend (no change to Comment Author color is seen)

![Screenshot 2022-04-12 at 10 06 22](https://user-images.githubusercontent.com/5323259/162912313-a5bc29a3-6886-4951-9150-6a8d825d95fa.jpg)

### Environment info

WP 5.9.3
Gutenberg plugin 13.0RC2
Twenty Twenty Two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

Associated issue:
[Block] Comment Template -> Columns - change text colors does not affect Edit and Reply text
https://github.com/WordPress/gutenberg/issues/40255

**Comment by carolinan** [comment]
The inner block setting should always be applied, if it is set. If it is not set, then it should use the parent block setting.

The comment author should only be colored by the text color setting if the option "link to authors URL" is toggled off. When it is on, which is the default, it is colored by the link color setting.

**Comment by paaljoachim** [comment]
Resting.
WP version 6.0.1
Gutenberg plugin: 13.7.2
Twenty Twenty Two

Going to Editor. Home template.
Just above the Footer. I added a Comments block.
Clicked Comment Content (Comments > Comment Template > Columns > Column > Comment Content) 
and changed the color to red: Link.

Clicked Comment Author ( Comments > Comment Template > Columns > Column > Comment Author Name)
and changed the color to red: Link.

It looks good here so I am closing this issue.
