### ISSUE TITLE
Can't tab between cells in table block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4025]
## Issue Overview
After inserting a table block, I expect to be able to tab between each of the table cells. Anyone who's ever used Excel or any kind of spreadsheet software, knows that you primarily move between cells after entering data, by hitting tab or by using the arrow keys.

Using the arrows keys in the Table block is also very frustrating because it simply moves the cursor past a single character, rather than between cells.

Having to individually click on every single table cell is extremely frustrating and tedious, when entering data.

## Steps to Reproduce (for bugs)
1. Insert table block
2. Enter data in first cell
3. Hit tab key and you're taken out of the block

## Expected Behaviour
I would expect tab to take me to the next cell

## Current Behaviour
Hitting Tab takes me out of the Table block

_Gutenberg 1.9.1
Firefox Quantum 57.0.1 (64-bit)_

**Comment by gibrown** [comment]
Ya agreed, muscle memory here from other programs makes me strongly want to tab between cells.

**Comment by karmatosed** [comment]
Closing as including in master table issue to get tables resolved: https://github.com/WordPress/gutenberg/issues/6923
