### ISSUE TITLE
[Block] Comment Author Name block - changing alignment or color has no effect on frontend

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#40251]
### Description

I noticed that adjusting the alignment and color the change will be seen on the backend but not the frontend.

### Step-by-step reproduction instructions

1. Add the Comments Query Loop block.
2. Select the Comment Author Name block.
3. Change the alignment and color.
4. Check the frontend to see the changes. I noticed no change.

### Screenshots, screen recording, code snippet

Backend:
Alignment right.
Text Color violet.
![Screenshot 2022-04-12 at 09 28 07](https://user-images.githubusercontent.com/5323259/162905203-bbf6b55b-6e1f-44aa-9280-2024ec4b4f2c.jpg)

Frontend:
Alignment default.
Text Color default.
![Screenshot 2022-04-12 at 09 29 44](https://user-images.githubusercontent.com/5323259/162905275-af14e7bf-b253-425a-8dae-f33a05d8be61.jpg)

### Environment info

WordPress 5.9.3
Gutenberg plugin 13.0.0 RC2
Twenty Twenty Two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Is this something we need to fix before the new generic "name" block is created?

**Comment by cbravobernal** [comment]
> Is this something we need to fix before the new generic "name" block is created?

That would be great, as I guess `Comment Author` will land before the generic `Author` (we can create an automated migration later)
