### ISSUE TITLE
Query Loop Block: Grid style preview improperly displays the layout styles

### ISSUE THREAD

**Issue by formosattic** [WordPress/gutenberg#40261]
### Description

In the editor, the Query Loop block doesn't properly display some of the layout styles of the Grid view.
This was brought up in https://github.com/Automattic/wp-calypso/issues/62289

### Step-by-step reproduction instructions

* Add a Query Loop block on a page.
* Select the Grid View.
* Scroll down to see the preview of each style.

### Screenshots, screen recording, code snippet

Here are some affected styles, and how they look with Gutenberg OFF and ON:

* Image at left
* Small image and title
* Offset

| Gutenberg OFF  | Gutenberg ON |
| ------------- | ------------- |
| ![image2](https://user-images.githubusercontent.com/15944096/162925385-46ce5894-77e2-438f-a662-a00ac279473f.png)  | ![image](https://user-images.githubusercontent.com/15944096/162925125-b60d1f6e-2f63-4c25-9f57-ff1cf719fedc.png)  |
| ![image1](https://user-images.githubusercontent.com/15944096/162925422-8a2c5840-d6c3-4aeb-8346-eed36997b68c.png)  | ![image](https://user-images.githubusercontent.com/15944096/162925094-6618e5b8-3cd4-437b-845d-f25edae620c8.png)  |

### Environment info

* WordPress 5.9.3
* Gutenberg 12.9.0 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, I believe the grid style preview (when you select a query loop style) was removed in https://github.com/WordPress/gutenberg/pull/47366 ; please reopen if you're still experiencing this issue.
