### ISSUE TITLE
Comments: Make it possible to create a "X replies to `post title`" heading

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40264]
You can kind of hack it with a Row containing Paragraphs, Post Comments Count, and Post Title blocks:

<img width="864" alt="Screenshot 2022-04-12 at 11 00 25" src="https://user-images.githubusercontent.com/846565/162934837-b9d6fc94-1db3-4cfc-a01f-59a6bf6a1eb0.png">

There are a couple of issues with this approach: 

1. Typography controls across blocks are inconsistent, so it's difficult to create a harmonious appearance
2. It's not possible to conditionally pluralise reply/replies in order to avoid the awkward "There are 1 comments" / "There are 32 comment".

It would seem relatively simple to address these issues. For example we could update the Post Comments Count block to include an option to also display a label so that the pluralisation logic is built into that block.

Alternatively we might consider a dedicated Comments Heading block.

**Comment by justintadlock** [comment]
I put together a rough block plugin for this: https://github.com/x3p0-dev/x3p0-comments-title

It needs an icon.  I'd be happy to test out variations on it.

**Comment by cbravobernal** [comment]
Hi @justintadlock

I added a PR to add the block in Core. I will take some code from your plugin. Feel free to edit or add comments to the PR!
