### ISSUE TITLE
[Block] Comments Query Loop block - alignments

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#40269]
### Description

I began experimenting with alignments in the toolbar of the Comments Query Loop block.
Frontend:

![Wide comments query loop block](https://user-images.githubusercontent.com/5323259/162947639-98638edb-a73c-407f-b830-67a6fb986754.jpg)

It is not clear to me what the alignment does. As I could not notice any difference between selecting the various.
None, Align left, Align center, Align right.

It would also be helpful to add in additional alignments.
Example from the Post Title block.
![Screenshot 2022-04-12 at 13 13 35](https://user-images.githubusercontent.com/5323259/162948025-f2d30246-6a70-48b0-83ee-fd618bc74dde.jpg)

### Step-by-step reproduction instructions

1. Add the Comments Query Loop block.
2. Test out the various alignments.
3. Do you see a change?

### Screenshots, screen recording, code snippet

See above.

### Environment info

WP 5.9.3
Gutenberg plugin 13.0 RC2
Twenty Twenty Two
Chrome
OSX

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Did you mean the alignments on the comments query loop, or on the inner blocks?
When I test the block today, I see the wide and full width alignments on the comments query loop, but the left/right/center alignment on the comment template, and text alignments on the inner text based blocks.

**Comment by paaljoachim** [comment]
Thanks for asking Carolina!
Ahhh. Looking at this again. I believe I was talking about the inner block "Comment Template".
As it has the None, Align left, Align center, Align right alignment options.
The backend and frontend shows no adjustments switching between these alignments.

**Comment by carolinan** [comment]
I tested this again today with different themes.
In Twenty Twenty-Two, the comment template is aligned to the right, center and left, but only in the editor.
In Twenty Twenty-One, the theme adds CSS for the classnames `alignright` etc separately, and the block is aligned in the editor and the front.
