### ISSUE TITLE
Table cells shouldn't use fixed pixel widths

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4027]
## Issue Overview
The html for the table block is using pixels for the width of the cells. You should never specify a width using a fixed number of pixels. It should be using percentages.

![screenshot_553](https://user-images.githubusercontent.com/2078245/34022552-13bd8180-e194-11e7-966b-025b4d74469a.png)

This just shows one of the many issues with using pixels widths to resize table cells...

![screenshot_555](https://user-images.githubusercontent.com/2078245/34022772-4b8d6066-e195-11e7-9249-7f00869e8028.png)

## Steps to Reproduce (for bugs)
1. Insert table block
2. Insert new column
3. View table html

## Expected Behaviour
I would expect the table cell widths to be using percentages, not fixed pixel widths

## Current Behaviour
Table html is using pixels to specify the width of the cells rather than percentages

_Gutenberg 1.9.1
Firefox Quantum 57.0.1 (64-bit)_

**Comment by danielbachhuber** [comment]
@maddisondesigns How did you end up with variable width columns? I don't see any corresponding controls:

![image](https://user-images.githubusercontent.com/36432/35303190-f44462a8-0045-11e8-8973-f527505d638d.png)

I can verify widths are included in the markup:

![image](https://user-images.githubusercontent.com/36432/35303218-093faac8-0046-11e8-9c3d-569c17abbd0c.png)

**Comment by maddisondesigns** [comment]
@danielbachhuber I presume you found the answer to your question in my other issue that I raised (#4026). They're different sizes in my example, because the block doesn't work properly and resize the columns automatically. The fact that there's also no controls to help you resize columns is equally annoying.

**Comment by danielbachhuber** [comment]
> I presume you found the answer to your question in my other issue that I raised

Indirectly, yes.

> They're different sizes in my example, because the block doesn't work properly and resize the columns automatically. The fact that there's also no controls to help you resize columns is equally annoying.

Yeah, weird behavior.

**Comment by helen** [comment]
Possibly related - while I wasn't getting pixel widths defined on the front end, the whole layout was messed up because there's `display: block` on `.wp-block-table`. Table CSS is fragile, changing that from the default of `display: table` seems like a bad idea.

**Comment by maddisondesigns** [comment]
@SuperGeniusZeb Nope, it's not fixed yet. Just updated to Gutenberg 3.1.1 and inserted a new table and it's still producing fixed width pixels in the markup. The columns also still don't auto-resize themselves when you insert a new column.

![screenshot_709](https://user-images.githubusercontent.com/2078245/42070558-55d03144-7b9a-11e8-8f16-8af1d77b0e2c.png)

**Comment by SuperGeniusZeb** [comment]
@maddisondesigns Have you tested in `master`? I did not see any fixed pixel widths when I tested there.
![image](https://user-images.githubusercontent.com/19592990/42092600-162e23fa-7b6f-11e8-89ea-dfa883e82c29.png)

**Comment by karmatosed** [comment]
Closing as bringing into a master issue : https://github.com/WordPress/gutenberg/issues/6923
