### ISSUE TITLE
[Block] Comments Query Loop block - Comment Template - Row - Change vertical alignment

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#40272]
### Description

I am now testing the Comments Query Loop > Comment Template > Columns > Column > Row.
Change vertical alignment.
Align top moves the Edit link and not the Comment Date.

![Screenshot 2022-04-12 at 13 31 16](https://user-images.githubusercontent.com/5323259/162950909-1e4a52bf-42e3-46b5-a7af-dce14768ed05.jpg)

Edit is only seen by the user who is logged into the site, but the Comment Date is seen by everyone.
The Comment Date should be affected by the Change vertical alignment instead of the Edit link.

### Step-by-step reproduction instructions

1. Select Row inside Comments Query Loop.
2. Change vertical alignment to top and notice the Edit link is moved. 

### Screenshots, screen recording, code snippet

--

### Environment info

WP 5.9.3
Gutenberg plugin 13.0 RC2
Twenty Twenty Two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by KAJALwp** [comment]
Hello @paaljoachim,

When I tried to change align to top, middle and bottom. it is not reflecting with edit link or date. 
For better understanding I have provide video attachment link.
https://screencast-o-matic.com/watch/c3hnQMVYG4V

Following are the version details
WordPress:- 5.9.3
Theme: Twenty Twenty-Two
Gutenberg Plugin:- 13.1.0
Mac OS:- Monterey 12.3.1
Chrome:- Version 99.0.4844.84 (Official Build) (arm64)

Thank you.

**Comment by carolinan** [comment]
I am not able to reproduce this with current Gutenberg trunk.

I first tested this in Empty theme without making any changes to the default comment blocks.
There is no space for the items to move up or down, so even though the CSS is applied, the blocks have no where to move:

![The row is a single line, only as tall as the letters in the text.](https://user-images.githubusercontent.com/7422055/175250981-27a57ad2-1e99-451c-b062-783da9276061.png)

If I add a spacer block to the row to adjust the height, the alignments are working for me:
https://user-images.githubusercontent.com/7422055/175252419-887ac28e-1ce6-496a-b608-f9ef2b6945f1.mov

**Comment by paulopmt1** [comment]
> I am not able to reproduce this with current Gutenberg trunk.
> 
> I first tested this in Empty theme without making any changes to the default comment blocks. There is no space for the items to move up or down, so even though the CSS is applied, the blocks have no where to move:
> 
> ![The row is a single line, only as tall as the letters in the text.](https://user-images.githubusercontent.com/7422055/175250981-27a57ad2-1e99-451c-b062-783da9276061.png)
> 
> If I add a spacer block to the row to adjust the height, the alignments are working for me: https://user-images.githubusercontent.com/7422055/175252419-887ac28e-1ce6-496a-b608-f9ef2b6945f1.mov

Following @carolinan's suggestion of adding a spacer block, I got the same result as her, it worked as expected :)

**Comment by paaljoachim** [comment]
Thank you for the feedback everyone!

I am retesting and seeing that this is now working as it should.
The Edit link is not affected when changing the Alignment.

![Screenshot 2022-07-16 at 10 57 34](https://user-images.githubusercontent.com/5323259/179348197-2ee06c99-a7f3-41cd-ba35-c63556ea9f16.jpg)

Closing issue.
