### ISSUE TITLE
Hijack the browser's right-click contextual menu when right-clicking on any part of the items in the FSE / Gutenberg post's blocks hierarchy list view sidebar

### ISSUE THREAD

**Issue by nekohayo** [WordPress/gutenberg#40287]
## What problem does this address?

With the list view sidebar activated on the left side of the Gutenberg editor, whether for posts/pages or for the FSE, I'm always annoyed when I right-click those items in the list and end up with my browser's (Firefox's) contextual right-click menu full of options irrelevant to my intended action regarding that interactive non-content widget (the list view), which was to get the item-specific actions that Gutenberg offers in its "three dots" menu for that item.

Currently I have the intuitive habit of right-clicking the items anywhere, getting the useless browser menu, having to left-click to dismiss it, then having to left-click the three dots to get the correct menu. I shouldn't have to aim for the tiny three-dots menubutton to get that menu, I should be able to right-click anywhere on that item's row. Fitt's law, etc., for a more efficient and native-feeling/integrated application UX.

## What is your proposed solution?

Please hijack the browser's right-click event to show the three-dots contextual menu of Gutenberg actions when clicking on a block item, particularly in the list view sidebar. If Google Drive and GMail can do it, so can WordPress.

Comparison of the current¹ vs suggested behavior when right-clicking anywhere on a row/item in the list view:

![wordpress gutenberg FSE suggestion to hijack right-click menus](https://user-images.githubusercontent.com/479401/163080071-fdec8ca3-1ebe-4759-a68d-85f4183d12d1.png)

¹: Tested with the stable versions bundled with WordPress 5.9.3 and the TwentyTwentyTwo theme, on Firefox 99 on Linux.

**Comment by andrewserong** [comment]
I thought I might have a go at implementing this. I know right-click override behaviour can be a bit contentious for some folks, so in #41041 I've explored implementing this feature plus an editor settings (defaulting to `true`) so that folks can opt-out of right click overrides if they want to.

**Comment by andrewserong** [comment]
A new(er) attempt at implementing this is ready for testing over in #50273.

**Comment by BenceSzalai** [comment]
Is there a reason this was not added to the main editor canvas, just the List View?
