### ISSUE TITLE
Adding additional templates types (author, date, taxonomy, etc) flashes default template content

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40286]
### Description

When adding new template types thanks to this PR https://github.com/WordPress/gutenberg/pull/39353, the content of the default template flashes before showing a blank template. 

### Step-by-step reproduction instructions

1. Open the Site Editor.
2. Go to the Template List.
3. Click "Add" and select one of the new template types (date, taxonomy, author, etc).
4. Notice the problem.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/163068361-5ced79b7-7153-4079-8670-36639f4f5c50.mov

### Environment info

- WordPress 6.0 Beta 1.
- TT2.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
This was replicated by a participant in the[ thirteen call for testing for the FSE Outreach Program:](https://make.wordpress.org/test/2022/03/31/fse-program-testing-call-13-authoring-an-author-template/#comment-2436)

> I saw the blip of the other template as well on first load.

**Comment by annezazu** [comment]
cc @scruffian since it seems you worked on implementing the additional template types in case you can help move this forward: https://github.com/WordPress/gutenberg/pull/39353

**Comment by Mamaduka** [comment]
Create PR to fix this issue - #40841.
