### ISSUE TITLE
e2e - file names are too long on windows

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#40291]
## What problem does this address?

@JustinyAhin I believe this is related to the switch to Playwright. Either way it is a recent issue.
When I try to work with Gutenberg changes and for example stash my local changes, I get errors like these:

```
PS D:\sites\basicwordpresstest\app\public\wp-content\plugins\gutenberg> git stash
error: lstat("test/e2e/specs/editor/various/copy-cut-paste-whole-blocks.spec.js-snapshots/Copy-cut-paste-of-whole-blocks-should-respect--957b6-opy-in-places-like-input-fields-and-textareas-2-chromium.txt"): Filename too long
fatal: Unable to process path test/e2e/specs/editor/various/copy-cut-paste-whole-blocks.spec.js-snapshots/Copy-cut-paste-of-whole-blocks-should-respect--957b6-opy-in-places-like-input-fields-and-textareas-2-chromium.txt
Cannot save the current worktree state
```
I have already moved my installation to a shorter path, but it is still too long.
` test/e2e/specs/editor/various/copy-cut-paste-whole-blocks.spec.js-snapshots/Copy-cut-paste-of-whole-blocks-should-respect--957b6-opy-in-places-like-input-fields-and-textareas-2-chromium.txt`
alone is 189 characters.

## What is your proposed solution?

Is it possible to use shorter paths and filenames?

**Comment by JustinyAhin** [comment]
~~@carolinan oh this is because when we migrate a new test to Playwright, we delete the original one. This error in particular should be related to https://github.com/WordPress/gutenberg/pull/39807.~~

cc @kevin940726

**Comment by kevin940726** [comment]
Oh wow, I didn't know that there's a file name limit on Windows. I'll see what I can do.

**Comment by kevin940726** [comment]
Possible temporary solution: https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows

**Comment by kevin940726** [comment]
Opened a PR in https://github.com/WordPress/gutenberg/pull/40336, LMK if it solves the problem!

**Comment by kevin940726** [comment]
#40336 is merged, I'll close this now but feel free to re-open if it doesn't solve the issue :)
