### ISSUE TITLE
Link Color Option Missing for Header and Paragraph Text

### ISSUE THREAD

**Issue by aezazs-multidots** [WordPress/gutenberg#40299]
### Description

When we use any WordPress default theme other than **Twenty Twenty Two** and when we use heading and paragraph block in it, then the link color option is missing in the color option of its text.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/72435501/163119799-715598e6-5643-4312-a361-bb10423b2826.png">

And when we use the **Twenty Twenty Two** theme and use Heading or Paragraph block in it, then we get the option of link color.

![image](https://user-images.githubusercontent.com/72435501/163119964-77b0d656-61a5-4f1f-b6e7-ed26884516c7.png)

### Step-by-step reproduction instructions

1. Go to the backend of any page and post
2. Now select the Heading or Paragraph block of the Gutenberg blocks
3. Now adds text to it.
4. Look in the right side color panel link color option will be missing

### Screenshots, screen recording, code snippet

We have made a video of the issue and have added its link below.

[https://somup.com/c3fIibOYXV](https://somup.com/c3fIibOYXV)

### Environment info

WordPress version: 5.9.3
Theme: Twenty Twenty One
Google Chrome version: Version 100.0.4896.75 (Official Build) (arm64)
OS Version: Mac 12.2.1
Gutenberg Plugin Version: 12.9.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Andrew-Starr** [comment]
The link color option is opt-in through the theme's `theme.json` file with either `settings.color.link:true` or `settings.appearanceTools:true`

Twenty Twenty One does not opt-in to this, while Twenty Twenty Two does.

**Comment by ndiego** [comment]
@aezazs-multidots thank you for opening this issue. As @Andrew-Starr mentioned, this is functionality that needs to be enabled by the theme. Since this is not directly related to an issue in Gutenberg, I am going to close this issue, but please let me know if I can answer any additional questions!
