### ISSUE TITLE
Open Graph Data with Gutenberg

### ISSUE THREAD

**Issue by gidgey** [WordPress/gutenberg#4030]
## Issue Overview
On my site, using the Bookmark Theme, Gutenberg, and Yoast, I have tried to pull the correct open graph data for social sharing on both Facebook's Object Debugger (https://developers.facebook.com/tools/debug/)  and with Twitter's Card Validator (https://cards-dev.twitter.com/validator) tools for my home page.

It works on a blog post.

## Steps to Reproduce (for bugs)

On the published page, the source shows that og:image is correct which is the featured image I chose for the page at gutenbridget.com (home page).

<img width="1225" alt="og-image-featured-image-code-121417" src="https://user-images.githubusercontent.com/22923622/34027670-1442d5f0-e113-11e7-81ba-dafe9eb7f803.png">

## Expected Behavior

Given that the code is in view source, I would expect that Facebook could scrape this data.

## Current Behavior

The Card Validator and Object Debugger show the screenshot and is also not pulling the meta data from Yoast.

<img width="1175" alt="twitter-card-validator-unable-to-read-card" src="https://user-images.githubusercontent.com/22923622/34027683-2c806650-e113-11e7-9297-d914be70d071.png">

<img width="1032" alt="fb-objectdebugger-og-image-121417" src="https://user-images.githubusercontent.com/22923622/34027687-31cb4e40-e113-11e7-9dc4-2f29a77c2a66.png">

<img width="964" alt="fb-objectdebugger-meta-121417" src="https://user-images.githubusercontent.com/22923622/34027691-3761a232-e113-11e7-8451-67a102c5eb18.png">

## Possible Solution

With all of my being I wish I knew enough code to offer a possible solution. But it's an error that matters to anyone who publishes, so I thought it was worth bringing up.

Thank you so much for your attention.

**Comment by Soean** [comment]
There is no og data in the source code of https://gutenbridget.com/. Maybe a cache problem?

How should this problem be connected to Gutenberg?

**Comment by gidgey** [comment]
@Soean In my screenshot above it shows og:image. 

That's how I normally check but maybe I'm missing something. 

Q: How should this problem be connected to Gutenberg?

A: My presumption is that on a fresh site with the plugins I usually use, Gutenberg is the only differentiating factor.

I'd love to be wrong. But I thought it was worth creating an issue in case it really is a bug.

Thank you so much for responding. I appreciate your time.

**Comment by kathrynwp** [comment]
When I run https://gutenbridget.com/ through the [Facebook Open Graph debugger](https://developers.facebook.com/tools/debug/), I get this error:

> Unknown Image Error
> Provided og:image URL, https://gutenbridget.com/wp-content/uploads/2017/12/Welcome-to-Gutenbridget.png encountered an unknown error.

That may be why the Twitter card isn't picking it up. To rule out Gutenberg as a factor, you could try the same image on a non-Gutenberg site (or with the plugin deactivated temporarily) and see what you get after asking the FB debugger to "scrape again."

**Comment by gidgey** [comment]
Thanks @kathrynwp It appears it works now. 

![screen shot 2017-12-15 at 5 35 47 pm](https://user-images.githubusercontent.com/22923622/34066076-72e75094-e1be-11e7-8cc3-afe1d5019175.png)
