### ISSUE TITLE
Locked (restrict editing) reusable block is still editable

### ISSUE THREAD

**Issue by MarieComet** [WordPress/gutenberg#40309]
### Description

With WP 6.0 beta 1.
A locked reusable block (with "restrict editing") text content is still editable.
From my tests, it's happening only for blocks containing text (paragraph and list block for example). 
([See video for example](https://mariecomet.fr/wp-content/uploads/2022/04/locked-reusable-block.mp4)).

### Step-by-step reproduction instructions

1. Insert a paragraph or list block, enter some text
2. Add it to reusable blocks
3. Lock it (with "restrict editing" option)
4. Click on the text, I can edit it

### Screenshots, screen recording, code snippet

Démo : https://mariecomet.fr/wp-content/uploads/2022/04/locked-reusable-block.mp4

### Environment info

- WP 6.0 beta 1
- Gutenberg plugin not active
- Twenty Twenty-One Version: 1.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MarieComet** [comment]
Note : I don't know why, the linked video doesn't load on Firefox, please use Chrome to watch it.

**Comment by Mamaduka** [comment]
Thanks again, @MarieComet, for contributing.

I just tried to reproduce the issue, but I cannot select block inside Reusable block when editing is locked. Posting my env and screencast. Let me know if I'm missing something.

cc @paaljoachim

**Environment**
* WP 6.0 Beta 1
* Gutenberg plugin not active (tested with the plugin as well).
* TT1 theme.
* MacOS/Chrome

https://user-images.githubusercontent.com/240569/163173211-6061e485-fbb3-41e6-9036-75b4d930d962.mp4

**Comment by MarieComet** [comment]
Yes, it's working on Chrome, can you test on Firefox ?

**Comment by MarieComet** [comment]
After some tests, it's looks like removing `pointer-events: none;`  here fix the bug : 

```
.block-editor-block-content-overlay.overlay-active::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: transparent;
    border: none;
    border-radius: 2px;
    z-index: 10;
    /* pointer-events: none; */
}
```

**Comment by Mamaduka** [comment]
I can confirm that the overlay works in Chrome and Safari but fails with Firefox.

**Comment by paaljoachim** [comment]
Testing.
Local site.
WP 6.0 Beta 1.
Twenty Twenty Two.

Chrome.
Overlay works. Locking works. 

Firefox.
Overlay not working. First click goes straight through to inner blocks. First click should only select the overlay. Second click should go through as long as Restrict editing lock is not activated.
Activating locking Restrict editing not working.
Fix the overlay and Restrict editing might also work as it should.

Opera.
Overlay works. Locking works. 

Safari
Overlay works. Locking works.

**Comment by talldan** [comment]
> After some tests, it's looks like removing pointer-events: none; here fix the bug

Lets try that out. From what I can tell that also helps with #35079, though that particular issue is still broken in Safari.

I made a PR - https://github.com/WordPress/gutenberg/pull/40339.

**Comment by talldan** [comment]
The 'Backport to WP Beta/RC' label is just for PRs, not for issues, so I've removed it.

**Comment by ndiego** [comment]
Given that the "edit locking" functionality is not going to make it into 6.0 (see #40498), I am going to remove this from the 6.0 Project Board.

**Comment by Mamaduka** [comment]
I'm no longer able to reproduce the issue on the current trunk. It might be related to the recent change of using the `inert` attribute in `useDisabled`. See #44865.

**Comment by Mamaduka** [comment]
Hi, @MarieComet

Could you let me know if you can still reproduce this issue?

**Comment by MarieComet** [comment]
Hi @Mamaduka,

I can't reproduce this issue 👍 
Testing with WP 6.2-RC2-55551, Chrome and Firefox.
