### ISSUE TITLE
Gutenberg fails to load

### ISSUE THREAD

**Issue by withinboredom** [WordPress/gutenberg#40326]
### Description

Cannot use the editor at all since upgrading to WP 5.9.3 and I've had to disable it using an anti-Gutenberg plugin.

```
TypeError: Cannot read properties of undefined (reading 'show_ui')
    at https://withinboredom.info/wp-content/plugins/gutenberg/build/editor/index.min.js?ver=2f0e5e9ca612a0497253ffdd2dec7f02:33:2895
    at i (https://c0.wp.com/c/5.9.3/wp-includes/js/dist/vendor/lodash.min.js:10:88)
    at lf (https://c0.wp.com/c/5.9.3/wp-includes/js/dist/vendor/lodash.min.js:84:172)
    at https://withinboredom.info/wp-content/plugins/gutenberg/build/editor/index.min.js?ver=2f0e5e9ca612a0497253ffdd2dec7f02:33:2875
    at ft (https://withinboredom.info/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:43451)
    at ts (https://withinboredom.info/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:111300)
    at Fr (https://withinboredom.info/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:77758)
    at Dr (https://withinboredom.info/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:77686)
    at Rr (https://withinboredom.info/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:77549)
    at Nr (https://withinboredom.info/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:74544)
```

All plugins are deactivated. This is a multi-site installation.

### Step-by-step reproduction instructions

1. Try to write a new post.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/1883296/163255858-92e98eb2-b69b-43a7-86d9-ded9f99127f1.png)

### Environment info

- All browsers and OS
- Tested with whatever shipped with 5.9.3
- Tested with Gutenberg plugin version 12.9.0
- Tested via WordPress.com and wp-admin (note, this blog is self-hosted)
- Theme: Neve

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@withinboredom I wasn't able to replicate this on a single site or multisite using Gutenberg 12.9 and WordPress 5.9.3 with all other plugins disabled. Do you have any custom taxonomies in place or anything particular with this multisite setup?

**Comment by withinboredom** [comment]
No special taxonomies. Looks like whatever path the code takes to get there, the "visibility" key on the object is simply missing /shrug/

![image](https://user-images.githubusercontent.com/1883296/163282843-4601f0cc-8ced-462c-a90b-90eac1f312ce.png)

**Comment by talldan** [comment]
This is the line of code that triggers the error - https://github.com/WordPress/gutenberg/blob/33d4729068cc3152ecfc720ee11e000f7abcd427/packages/editor/src/components/post-taxonomies/index.js#L31

**Comment by glendaviesnz** [comment]
I was only able to replicate this by manually setting a taxonomies visibility property to undefined. I have a [fix here for it](https://github.com/WordPress/gutenberg/pull/40532) - even though it is hard to replicate, and it would be good to know how a taxonomy could end up in this state, I don't think there are any downsides to just including this defensive patch in the meantime.

**Comment by withinboredom** [comment]
This blog is 10 years old... so anything could have happened.
