### ISSUE TITLE
DS_Store included in FSE export

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#40327]
### Description

When I export a theme from FSE the Mac `DS_Store` files (and other hidden Mac system files) are included. I think these should be removed.

Many people who use the theme exporting will be working locally rather than on a live website, and so there's a high likelihood they will be saving hidden system files in the zip exports.

### Step-by-step reproduction instructions

1. Open a theme locally, in WordPress, on a Mac
2. Go to the site editor
3. Export the current theme
4. Open the saved zip and check out the contents.

You may need to browse the theme directory on the local file system because this is how the files get created. If the files are entirely generated through scripts then they may not appear.

### Screenshots, screen recording, code snippet

I spotted the problem when exporting the files for the theme I am currently working on

<img width="268" alt="Screenshot 2022-04-13 at 21 51 52" src="https://user-images.githubusercontent.com/1004130/163268337-36d659c9-a29e-4e4e-abfb-e7c29fb16a8e.png">

### Environment info

Latest WP and Gutenberg
Running locally through MAMP on a Mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
cc @scruffian

**Comment by scruffian** [comment]
Fix here: https://github.com/WordPress/gutenberg/pull/40539
