### ISSUE TITLE
Top Toolbar + Navigation + Undo = Ghost block

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40346]
If you have Top Toolbar mode enabled, add a link to a navigation menu then undo, an ellipsis menu is accessible from the toolbar. But that ellipsis menu does not seem to be associated with any block.

https://user-images.githubusercontent.com/846565/163363834-1b7c73d4-ab63-4d0c-8d00-0b4e9395758b.mp4

It seems like the undo action undoes the link destination selection, leaves the empty Link block, but doesn't return focus to it.

I'm not sure of the best approach here, but my intuition was that the undo action would simply remove the block I just added.

**Comment by kathrynwp** [comment]
I was able to replicate this with:

WordPress 6.0.2
No plugins active
Twenty Twenty-Two 1.2

I can't seem to replicate this with Gutenberg 14.2 active, however, perhaps because the Navigation block has been reworked. @jameskoster would you be able to check again with the latest Gutenberg active and let me know if you can still replicate? Thanks!

**Comment by jameskoster** [comment]
It's still happening for me. Undoing the addition of a link produces the following:

<img width="782" alt="Screenshot 2022-10-12 at 10 25 31" src="https://user-images.githubusercontent.com/846565/195305062-b38ff822-6895-41ea-918e-302c77942fa1.png">

As you can see in List View, the "Custom Link" block remains, but it is unselected. The Top Toolbar continues to display an ellipsis icon button. 

Undoing _again_ deletes the block, but still, the ellipsis button for the `null` block remains:

<img width="641" alt="Screenshot 2022-10-12 at 10 27 07" src="https://user-images.githubusercontent.com/846565/195305367-b6e26aef-2997-4856-ae5f-fcf4dba533d0.png">

**Comment by Mamaduka** [comment]
The original issue was fixed via #58979.
