### ISSUE TITLE
Responsive image gallery block

### ISSUE THREAD

**Issue by justnorris** [WordPress/gutenberg#4035]
## Issue Overview
Galleries alignment is off on mobile devices:

![alignment](https://user-images.githubusercontent.com/988095/34038436-0b1055ca-e195-11e7-8cd5-6bd71f4daac1.png)

Caused by:
```
	margin: 0 16px 16px 0;
```

at `.wp-block-gallery.aligncenter .blocks-gallery-image, .wp-block-gallery.alignleft .blocks-gallery-image, .wp-block-gallery.alignright .blocks-gallery-image, .wp-block-gallery .blocks-gallery-image`

## Possible Solution
Maybe use CSS Grid instead of Flexbox? People with CSS grid will get a column of images, which isn't all that bad. By using grid margin could be replaced with `grid-gap` - this seems like the exact thing the grid spec was designed for.

If CSS Grid isn't an option - that margin needs to be cleared up so that the gallery causing an unsymmetrical 16px gap on the right.

**Comment by karmatosed** [comment]
CSS Grid is planned to be used @justnorris, so a great idea to bring it in for this.

**Comment by jasmussen** [comment]
I'll take this one.

**Comment by jasmussen** [comment]
This issue is fixed by #5217.
