### ISSUE TITLE
Z-index bug on freshly editted block

### ISSUE THREAD

**Issue by lucprincen** [WordPress/gutenberg#4036]
## Issue Overview
After changing the background-color of a regular textblock and trying to add another block above it, the popup-modal stays behind the freshly editted block.

## Steps to Reproduce (for bugs)
1. Edit a text block (the screenshot below is from the demo page)
2. Try to add a block above it, using the contextual (+) button above each block
3. See the modal fall behind (see screenshot)

## Browser:
Latest stable of chrome (62.0.3202.94)

## Expected Behavior
I expect this modal to be on top of the block I just editted

## Current Behavior
The block is below it

## Possible Solution
I'm not saying use "z-index: 9999", but it might be a good start XD

## Screenshots / Video
<img width="691" alt="schermafbeelding 2017-12-15 om 11 13 37" src="https://user-images.githubusercontent.com/3257545/34043005-717488ea-e19f-11e7-8494-200b75651d20.png">

## Related Issues and/or PRs
I've looked, but none I'm aware of.

**Comment by Soean** [comment]
Can't reproduce the bug in master and 1.9.1. Tested on Mac / Chrome 63.0.3239.108.
Z-index is `10000`

![4036](https://user-images.githubusercontent.com/695201/34043813-f009d0ea-e1a2-11e7-87c3-802e4bf93248.png)

**Comment by lucprincen** [comment]
You can go ahead and close this issue. Seems to be fixed in 1.9.1, thank you! 👍
