### ISSUE TITLE
A part of a string of one Post Featured Image block setting is not translatable

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/gutenberg#40375]
### Description

In the settings of the "Post Featured Image" block, a string of an option cannot be correctly translated.

### Step-by-step reproduction instructions

1.Choose for example "fr_FR" to set the site language or 
2.In a post, create a Post Featured Image block.
3.See in the sidebar, the link settings : "Lien vers post".

This string corresponds to:
https://translate.wordpress.org/projects/wp/dev/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=18942&filters%5Btranslation_id%5D=70604887

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/75045144/163557323-3adaf515-d71a-4e59-b293-cf59167fb494.png)

### Environment info

WordPress 5.9.3 without the Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
Thanks for contributing, @jennydupuy. The issue should be fixed now and will be backported in WP 6.0 beta 2.
