### ISSUE TITLE
Blocks (Category, Featured Image) not loading properly on Post Page

### ISSUE THREAD

**Issue by henriqueiamarino** [WordPress/gutenberg#40377]
### Description

In the settings of Post, some blocks are not loaded properly with the page — in general “Categories” and “Featured Image”.
As this happens inconsistently I couldn't replicate it but attached a screenshot to illustrate the missing blocks (on B).

The following topics are pointing out to the same issue:
[Category missing in right sidebar](https://wordpress.org/support/topic/category-missing-in-right-sidebar/)
[Editor availability is inconsistent](https://wordpress.org/support/topic/editor-availability-is-inconsistent/#post-15557154)

### Step-by-step reproduction instructions

With its uncertain occurrences t was not possible to reproduce it

### Screenshots, screen recording, code snippet

![document-settings_inconsistent](https://user-images.githubusercontent.com/103748085/163567627-c1459b22-c416-461e-950d-95858fa881d2.png)

### Environment info

- WordPress 5.9.3
- Google Chrome
- Desktop with MacOS Monterrey 12.2.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I can sort of reproduce this: both fields load for me, but it does take longer than I would expect.

**Comment by ulfemsoy** [comment]
Not working for me. Both Featured Image, Categories and Tags don't show.
I have disabled all plugins. Running version WP 6.

**Comment by skorasaurus** [comment]
Thanks for opening, a couple questions: 

How many categories and tags do you have on your website? 

Are you still experiencing this with the latest version of WordPress and have you installed and activated the newest version of Gutenberg that is available through [the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/)? 

Possibly related to https://github.com/WordPress/gutenberg/issues/10169 but in that report the categories do load, just slowly.

**Comment by ulfemsoy** [comment]
I am running Wordpress 6.0.2. The catories now show (18 of them). I have removed all tags, but when adding a new tag, it is automatically deleted when pressing enter.

**Comment by carolinan** [comment]
Automatically delete from where? That seems like a separate issue.

**Comment by ulfemsoy** [comment]
Yes, it is probably another issue.

**Comment by aurooba** [comment]
Hi @henriqueiamarino, are you still able to reproduce this issue with WordPress 6.2?

**Comment by jordesign** [comment]
With no further movement on this issue, or more report in 6.2 or 6.3 I'll close it.

We can reopen if we receive further reports.
