### ISSUE TITLE
Content with only "More" block reloads as invalid

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#4038]
## Issue Overview

When saving a post with only the "More" block, reloading the post reveals multiple invalid blocks.

![Invalid](https://user-images.githubusercontent.com/1779930/34044642-c4e19832-e173-11e7-85be-9805d45210cf.png)

## Steps to Reproduce (for bugs)

1. Navigate to Posts > New Post
2. Insert a More block
3. Save the post
4. Reload the page

## Expected Behavior

The post is shown as it did prior to reload.

## Current Behavior

The post is shown with multiple invalid blocks.

## Possible Solution

This appears to be a conflict with `autop` behaviors. Specifically:

```php
wpautop( '<!--more-->' ) === '<p><!--more--></p>';
```

The Gutenberg content parser treats this as three blocks:

- Freeform block with `innerHTML` `<p>`
- More block
- Freeform block with `innerHTML` `</p>`

The two freeform blocks are marked as invalid because reserializing will restore the missing closing / opening tags respectively.

A few options here:

- The "More" tag, if considered a proper block, could be exempted from `wpautop` as other blocks
- The grammar could be made more lenient to consider `<p>` wrapping tag for a More block
- The grammar could be made more strict to not consider More block if wrapped by `<p>`

**Comment by bobbingwide** [comment]
I got the same problem when selecting a post that was created in the Classic Editor. Switching to the Code editor reveals the changed source. There were no p tags in the original. 

```
<p>Same problem happens when there's content.

<!--more-->

No line feeds here.</p>
```

**Comment by aduth** [comment]
Related: #4005

>Switching to the Code editor reveals the changed source.

With the above #4005, this will produce a slightly different result, but still not quite right:

```html
<p>Same problem happens when there\'s content.</p>
<p><!--more--></p>
<p>No line feeds here.</p>
```

**Comment by mcsf** [comment]
Should be fixed by now.
