### ISSUE TITLE
[Fonts API] enqueue programmatically fonts picked in block settings

### ISSUE THREAD

**Issue by zaguiini** [WordPress/gutenberg#40386]
## What problem does this address?

Picking a programmatically registered font in the block settings does not enqueue it, unless it's been allow-listed in `theme.json[settings][fontFamilies]`.

## What is your proposed solution?

We need to introspect block settings on render and look for font families. Once a family is found, and that font is registered, enqueue it. 

## Blockers 

We only want to work on this after https://github.com/WordPress/gutenberg/issues/40362, so only a subset of programmatically registered webfonts show up in the block settings.

**Comment by Addison-Stavlo** [comment]
> enqueue programmatically webfonts picked in block settings

Remembering @mtias 's comments (please correct me if wrong) from last week, IIRC we do not want this to be the case.

From my understanding programmatically registered webfonts should not show up in the block settings options (and we should create an issue to fix this), only global styles. Only theme fonts should show up in the block settings pickers, and the enqueuing for those should already be handled.

**Comment by hellofromtonya** [comment]
Hmm, I think this issue is not an issue after #40362 gets resolved.. Why? The intent is to populate typography pickers with only enqueued fonts.
