### ISSUE TITLE
New Block: Last Modified Date

### ISSUE THREAD

**Issue by bhubbard** [WordPress/gutenberg#40388]
## What problem does this address?
Right now there is a block to display the Post Date, but we don't have to display the last modified date.

## What is your proposed solution?
A new block for last modified date. As a bonus it might be nice to have a setting or separate block to display who last modified it.

**Comment by talldan** [comment]
I suppose this could alternatively be a setting of the Post Date block. It could default to displaying the publish date, but have a setting that causes it to show the modified date.

**Comment by bhubbard** [comment]
@talldan Making it an option in the same block would work.
