### ISSUE TITLE
Components: Clean up `utils/colors-values.js` file

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#40392]
## What problem does this address?

The bloated colors file is currently a pain point. It's blocking the work we'd like to do to migrate to a more CSS variables-centric approach, which then could enable theming.

We should be able to greatly simplify the colors file following @jasmussen's [guidance](https://github.com/WordPress/gutenberg/issues/40113#issuecomment-1091161656):

> We definitely want to retire #050505, and #000000 is a color we should very rarely use — mostly for shadows, not for UI elements.
> 
> To an extent, the whole list of colors in [this file](https://github.com/WordPress/gutenberg/blob/30f900ec5e925bdd218a8845db533765834e9e0b/packages/components/src/utils/colors-values.js) is wrong and outdated, and exists — I believe — mainly due to it being created at a time in the development where much of the design refresh from #18667 was still underway. In that light, I would consider lines 6-15 from [the sass file](https://github.com/WordPress/gutenberg/blob/trunk/packages/base-styles/_colors.scss?rgh-link-date=2022-04-07T07%3A13%3A52Z) as the canonical and single list of grayscale colors we should support in the component set, with `var(--wp-admin-theme-color)` rounding out the spot color.
> 
> If I had my way, I'd rename the `G2` color palette to something more sensible, it was just a temporary codename. I'd also retire all the other palettes, `DARK_GRAY`, `DARK_OPACITY`, `DARK_OPACITY_LIGHT`, `LIGHT_GRAY`, `LIGHT_OPACITY_LIGHT`, and `BLUE`. No-one should use those colors, and if we need to maintain them for backwards compatibility, we should seek out a way to clearly communicate they are deprecated.

## What is your proposed solution?

Let's clean up the file in small iterative steps, starting off by removing unused colors, consolidating duplicated references, etc.

**Comment by ciampo** [comment]
As we work on this, we should also go through the steps highlighted in https://github.com/WordPress/gutenberg/pull/40526#discussion_r856006044 regarding border colors

**Comment by mirka** [comment]
> As we work on this, we should also go through the steps highlighted in [#40526 (comment)](https://github.com/WordPress/gutenberg/pull/40526#discussion_r856006044) regarding border colors

I moved this task to #39425

**Comment by ciampo** [comment]
Are the [colors defined in the `UI` object ](https://github.com/WordPress/gutenberg/blob/95816949e28a6ec1c6fc0bdc3c31432c98a22e44/packages/components/src/utils/colors-values.js#L46-L60) still relevant, or do they need some cleanup too?

**Comment by mirka** [comment]
> Are the [colors defined in the `UI` object ](https://github.com/WordPress/gutenberg/blob/95816949e28a6ec1c6fc0bdc3c31432c98a22e44/packages/components/src/utils/colors-values.js#L46-L60) still relevant, or do they need some cleanup too?

I'm not exactly sure, but I think we'll be doing inventory/cleanup work on the `UI` object when we start to make those items themeable, starting with the border colors. I'm fine with leaving it for now (and it being continued to be used in new places) because it captures some semantic meaning that will likely be useful when doing any future refactor work (including theming).
