### ISSUE TITLE
Create Block: Continue even when Node not detected correctly

### ISSUE THREAD

**Issue by nextgenthemes** [WordPress/gutenberg#40403]
### Description

Ubuntu 21.10
Snap verson of Node. Tried 12, 14, 16, 17 same issue with all of them. Detection fails And it claims I do not  have it correct version installed.

This may be an issue with the snap version of node and/or the library you are using for the detection. It worked perfectly fine, until now. A simple switch to just skip the version detection would be a good workarround I think.

```sh
node -v
v16.14.0

npx @wordpress/create-block                                                                    
Minimum system requirements not met!

Error: Wanted node version >=12 (>=12.0.0)
/home/name/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/check-system-requirements.js:26
					check.PROGRAMS[ name ].getInstallInstructions( wanted.raw )
					              ^

TypeError: Cannot read properties of undefined (reading 'node')
    at /home/name/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/check-system-requirements.js:26:20
    at /home/name/.npm/_npx/0890e296436e9575/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/name/.npm/_npx/0890e296436e9575/node_modules/lodash/lodash.js:3032:24)
    at /home/name/.npm/_npx/0890e296436e9575/node_modules/lodash/lodash.js:4936:18
    at forEach (/home/name/.npm/_npx/0890e296436e9575/node_modules/lodash/lodash.js:9410:14)
    at checkSystemRequirements (/home/name/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/check-system-requirements.js:20:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/home/name/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/index.js:73:4)
```

### Step-by-step reproduction instructions

1. sudo snap refresh node --classic --channel=16/stable
2. npx @wordpress/create-block

### Environment info

Ubuntu 21.10
Snap verson of Node. Tried 12, 14, 16, 17 same issue with all of them. Detection fails And it claims I do not  have it correct version installed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes, No

**Comment by gziolo** [comment]
https://github.com/WordPress/gutenberg/blob/ec43ad66dc1719075ad23c89cb9e369cc30a8cf3/packages/create-block/package.json#L36

There is a newer version of https://www.npmjs.com/package/check-node-version v4.2.1, maybe that would help?

**Comment by gziolo** [comment]
I see now that it’s an issue with `snap` according to https://github.com/nodejs/snap/issues/31#issuecomment-1102121422. It doesn’t look like it can get fixed.

We could add a prompt asking if you want to proceed anyway with a message that it didn’t detect the correct version of Node.js.

**Comment by t-hamano** [comment]
I've never used snap, but I can reproduce this error by intentionally specifying a lower node version using the node management tool.
About adding a prompt to proceed or confirm anyway when the node version is low or not detected correctly, I would like to try because I think it doesn't require a major code change 👍

**Comment by gziolo** [comment]
> About adding a prompt to proceed or confirm anyway when the node version is low or not detected correctly, I would like to try because I think it doesn't require a major code change 👍

@t-hamano, that would be great if you give it a try 💯
