### ISSUE TITLE
Using PHP template file in block theme: Inline theme CSS not included in HTML head 

### ISSUE THREAD

**Issue by dschmidtke** [WordPress/gutenberg#40401]
### Description

Building a block theme on Wordpress 5.93, I hat to resort to a PHP template file in order to display a custom post type with custom fields. While the template renders fine, the CSS inlined in the HTML head is missing. It should be included just like it is when using standard html template files.

From what I read, the wp_maybe_inline_styles hook in wp_head() is responsible for adding the styles. Since my php template code calls wp_head() my wild guess is, that the hook is not called when using a php template as part of a block theme.

Expected behaviour is that the styles are inlined as they do when using standard html template files.

### Step-by-step reproduction instructions

1. For a custom "tour" post type i placed a template file single-tour.php in the root folder of my theme.
2. The PHP template calls wp_head() - see the attached code snippet.
3. The template is rendered fine for "tour" pages - however the inline styles are missing.

### Screenshots, screen recording, code snippet

&lt;!doctype html&gt;
&lt;html &lt;?php language_attributes(); ?&gt;&gt;
&lt;head&gt;
	&lt;meta charset=&quot;&lt;?php bloginfo( 'charset' ); ?&gt;&quot;&gt;
	&lt;?php wp_head(); ?&gt;
&lt;/head&gt;
&lt;body &lt;?php body_class(); ?&gt;&gt;
&lt;?php wp_body_open(); ?&gt;
&lt;div class=&quot;wp-site-blocks&quot;&gt;
&lt;?php
echo do_blocks( '&lt;!-- wp:template-part {&quot;slug&quot;:&quot;header&quot;,&quot;theme&quot;:&quot;mytheme&quot;,&quot;tagName&quot;:&quot;header&quot;,&quot;className&quot;:&quot;site-header&quot;} /--&gt;' );
// remainder is omitted

### Environment info

- Wordpress 5.9.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi,
I am closing this issue as a duplication of  https://github.com/WordPress/gutenberg/issues/40018

There is a temporary(?) solution in https://github.com/WordPress/gutenberg/issues/39207#issuecomment-1087347901

You need to place your content (`'<!-- wp:template-part {"slug":"header",",...`) before `wp_head()`;
And then echo it in the body after wp-site-blocks where you want to output it.
