### ISSUE TITLE
Button block opens new tab after setting link with enter key in Firefox

### ISSUE THREAD

**Issue by coreyworrell** [WordPress/gutenberg#40449]
### Description

After typing or selecting a link for a button, hitting the enter key opens that link right away. It should simply save the link and allow you to continue editing.

### Step-by-step reproduction instructions

1. Insert Buttons block
2. Click the link icon for the button
3. Type out a URL
4. Hit enter key

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/162595/164058905-2544765f-632d-4a36-8f6b-6c4538af3457.mp4

### Environment info

- WordPress 5.9.3
- Firefox 99.0
- Ubuntu 20.04

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@draganescu, do you think this is related to #38950.
