### ISSUE TITLE
Native oEmbed Support While Writing Content

### ISSUE THREAD

**Issue by gidgey** [WordPress/gutenberg#4044]
## Issue Overview

Embedding Tweets, and other links through oEmbed without Gutenberg is an ease. Instead of just pasting a Twitter URL on a hard break on my page, I had to choose a Twitter embed block and enter the url of the tweet, to show my tweet. That is a significant impact to my workflow as a content creator.

It seems like a small thing but one of the reasons why this matters is that writers like myself often compose text and then enter Tweets, Instagram Posts, and YouTube video links to support the text. When I ran a Twitter chat, I posted a recap with 5 embedded Tweets with each question (7-10 questions). With the demise of Storify, it's even more important that we, as WordPress get this right.

Matías asked me to open an issue.

https://twitter.com/matias_ventura/status/941722152386080770

## Steps to Reproduce (for bugs)

Instead of just pasting a Twitter URL on a hard break on my page, I had to choose a Twitter embed block and enter the url of the tweet, to show my tweet. 

This behavior is on my home page of gutenbridget.com.

I am using Bookmark Theme from the repo. 

https://wordpress.org/themes/bookmark/

Plugins: Gutenberg, Caldera Forms, Yoast, Real Simple SSL, Google Analytics Dashboard for WP, Jetpack.

![gutenbridget-plugins](https://user-images.githubusercontent.com/22923622/34175318-eedfe9b4-e4b0-11e7-94c0-ec64302feee8.jpg)

![screen shot 2017-12-13 at 6 30 26 pm](https://user-images.githubusercontent.com/22923622/34055777-949f4eb4-e185-11e7-9f49-c2de55d4c804.png)

![screen shot 2017-12-13 at 6 30 35 pm](https://user-images.githubusercontent.com/22923622/34055776-948d3c92-e185-11e7-9ac8-98bd3b2bf890.png)

<img width="700" alt="screen shot 2017-12-15 at 10 50 35 am" src="https://user-images.githubusercontent.com/22923622/34055851-d3f58efc-e185-11e7-9f5b-bce2e7d2099b.png">

## Expected Behavior

I expected to paste in the link, press enter, and keep typing and the tweet to render as it does now in WordPress.

## Current Behavior

Currently, I had to choose an embed block, paste the link, and then start a new paragraph block for the rest of the article I was composing.

## Possible Solution

I wish I knew what the possible solution was. 

Thanks for your time and attention.

**Comment by aduth** [comment]
Can you provide an example link that you tried to paste unsuccessfully? In my brief testing, this works as expected; pasting the Tweet URL from your report into a new blank paragraph block transforms to a Tweet embed automatically.

Related code occurs here:

https://github.com/WordPress/gutenberg/blob/6a287a4efa4b0ab8aea05d4abb23717bcfb9c9bd/blocks/library/embed/index.js#L249-L261

**Comment by gidgey** [comment]
Hi @aduth.

The example link is in the screenshot but it's here:

https://twitter.com/YouTooCanBeGuru/status/941069980589682688

My point is that I wouldn't think to make a brand new block to paste.

But I did press "return" then paste then "return." It didn't render.

The Page is gutenbridget.com.

Thanks.

**Comment by aduth** [comment]
>My point is that I wouldn't think to make a brand new block to paste.
>
>But I did press "return" then paste then "return." It didn't render.

Okay, I'd expect this flow to work correctly. By "brand new block", I'd expect this to work when starting a new post and clicking within "Write your story", or from an existing paragraph pressing Enter to create a new paragraph block then pasting a link.

Can you confirm from which block you had pressed Enter? Was it the image caption, or the preceding paragraph?

**Comment by gidgey** [comment]
@aduth 

Andrew, I feel like I'm not doing a good job translating my behavior into something a developer can understand.

From view source, here's the code.




<figure class="wp-block-image alignleft"><img src="https://gutenbridget.com/wp-content/uploads/2017/12/cropped-bridget-wcroc-111617-sq-1.jpg" alt="" />
  | <figcaption>This is a photo Michelle Ames took of me.</figcaption>
  | </figure>
  |  
  |  
  |  
  | <p>I figured if I wanted to help spread the word about Gutenberg Project being Merged into Core in the Spring of 2018, I&#x27;d test it out for myself.</p>
  |  
  |  
  |  
  | <p>I plan on curating news and resources for Gutenberg here.<br/><br/>https://twitter.com/YouTooCanBeGuru/status/941069980589682688<br/></p>
  |  
  |  
  |  
  | <figure class="wp-block-embed-twitter aligncenter">
  | <blockquote class="twitter-tweet" data-width="550" data-dnt="true"><p lang="en" dir="ltr">Okay. I just bought <a href="https://t.co/fKyrDUiHY9">https://t.co/fKyrDUiHY9</a> from <a href="https://twitter.com/GoDaddy?ref_src=twsrc%5Etfw">@godaddy</a> and getting a hosting plan with <a href="https://twitter.com/bluehost?ref_src=twsrc%5Etfw">@bluehost</a> to try <a href="https://twitter.com/hashtag/Gutenberg?src=hash&amp;ref_src=twsrc%5Etfw">#Gutenberg</a> for myself. <br><br>Pray the DNS gods love me. <a href="https://twitter.com/hashtag/NotADev?src=hash&amp;ref_src=twsrc%5Etfw">#NotADev</a> <a href="https://twitter.com/hashtag/WordPress?src=hash&amp;ref_src=twsrc%5Etfw">#WordPress</a> <a href="https://twitter.com/hashtag/MoneyWhereMyMouthIs?src=hash&amp;ref_src=twsrc%5Etfw">#MoneyWhereMyMouthIs</a></p>&mdash; Bridget Willard (@YouTooCanBeGuru) <a href="https://twitter.com/YouTooCanBeGuru/status/941069980589682688?ref_src=twsrc%5Etfw">December 13, 2017</a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  | </figure>
  |  
  |  
  |  
  | <p style="font-size:26px" class="aligncenter">So, instead of just pasting a Twitter URL, I had to choose a Twitter embed block to show my tweet. That&#x27;s a bummer. I&#x27;d love native oEmbed support. Maybe that&#x27;s already an<a href="https://github.com/WordPress/gutenberg"> issue on Github</a>.</p>
  |  
  |  
  |  
  | <figure class="wp-block-image"><img src="https://gutenbridget.com//wp-content/uploads/2017/12/Screen-Shot-2017-12-13-at-6.30.26-PM.png" /></figure>

**Comment by brandondove** [comment]
@gidgey it might help the devs track this down if they had the information about your theme and plugins that you gave me last night on twitter. I'm linking to your setup below.

https://twitter.com/youtoocanbeguru/status/943005958715748352

**Comment by gidgey** [comment]
Ooops, @brandondove I'll append.

**Comment by mtias** [comment]
> But I did press "return" then paste then "return." It didn't render.

@gidgey this does work for me in my testing:

![pasting-oembed](https://user-images.githubusercontent.com/548849/34576360-fe33c3ac-f17d-11e7-9d60-cd01a5e31dc6.gif)

**Comment by gidgey** [comment]
Thank you for responding @mtias especially with the gif. 

When I start a block and only paste the Twitter link, it works. Perfect.

When I create a new paragraph block, type, press enter, then paste, it isn't working. Maybe I'm doing something wrong. 

I'm not sure if it matters, but this is a live site, hosted on Bluehost. It's not a testing environment.


![oembed-gif-issue-github](https://user-images.githubusercontent.com/22923622/34585326-17edc01a-f154-11e7-8f04-7add3045b4ac.gif)


Here is my gif of what I'm doing. 

http://g.recordit.co/1ODekSBAtj.gif

**Comment by notnownikki** [comment]
Hi, taking a look at this as I know a bit about the embed blocks :)

I can't replicate it here, so could you show the "Edit as HTML" view for the block that just contains the twitter URL please? I'm wondering if there are other characters in there that are stopping the transformation to an embed block.

**Comment by notnownikki** [comment]
I took a look at gutenbridget.com and the twitter URL that hasn't been transformed by oEmbed isn't in the format that oEmbed expects.

The HTML for that part of the post looks like this:

```
<p>
I plan on curating news and resources for Gutenberg here.
<br>
<br>
https://twitter.com/YouTooCanBeGuru/status/941069980589682688
<br>
</p>
```

It looks like the `<br>`s were inserted by holding shift and pressing enter, then the URL was pasted, and shift+enter was pressed again. The current editor gives the same behaviour - the URL appears by itself on a line and the content is not embedded.

Here's how it works in the current editor, with enter, and shift+enter:

![enter](https://user-images.githubusercontent.com/3314354/35614433-05552542-0667-11e8-85d3-e2e33d0daf03.gif)

![shift-enter](https://user-images.githubusercontent.com/3314354/35614439-0b65f98e-0667-11e8-90e9-75e1e0fbf037.gif)

So Gutenberg works in the same way as the current editor for this as far as I can see, and the only way I can think of for you to get those `<br>`s is to press shift+enter instead of just enter. Could you test again?
