### ISSUE TITLE
Display HTML anchor link for Group block in List View

### ISSUE THREAD

**Issue by inaikem** [WordPress/gutenberg#40456]
## What problem does this address?

Improving consistency and user experience in the List View.

Currently HTML anchor text is shown as a grey label in the List View for only some blocks (eg Heading, Spacer), but not others. See below:
&nbsp;

![Annotation on 2022-04-20 at 10-37-08](https://user-images.githubusercontent.com/66711744/164135969-f19e3328-3756-4e97-9e7e-d4f2f037b047.png)

## What is your proposed solution?

I'd like to request we display any HTML Anchor text set by users in the List View for _all_ blocks.

**Comment by annezazu** [comment]
This _might_ be able to be closed out since it overlaps so much with the following two issues: https://github.com/WordPress/gutenberg/issues/16296 https://github.com/WordPress/gutenberg/issues/33583 What do you think? Adding labels to be safe either way :)

**Comment by inaikem** [comment]
#33583 especially looks super interesting! This request might well be superseded but it's a nice to have in the interim if its an easy enough addition to make 🤞

**Comment by Mamaduka** [comment]
I think this is a bug. I can confirm that Group doesn't display anchor, while other blocks do. The original feature was added via #31992.

**Comment by annezazu** [comment]
Great sleuthing per usual @Mamaduka! Thanks for a PR as well <3 Updating the title to reflect the bug too.
