### ISSUE TITLE
The wp:pattern is not expanded in the modal iframe.

### ISSUE THREAD

**Issue by inc2734** [WordPress/gutenberg#40459]
### Description

The wp:pattern is not expanded in the modal that "Replace" the template part, so the content of that part is not displayed.

### Tried and tested environment
- WordPress version: 6.0 beta2
- WordPress version: 6.0 beta2 + Gutenberg 13.0.0

### Step-by-step reproduction instructions

1. Activate TwentyTwentyTwho
2. Go to "Site Editor"
3. Click header template part.
4. Click "Replace" in toolbar.

### Screenshots, screen recording, code snippet

<img width="1275" alt="スクリーンショット 2022-04-20 15 26 39" src="https://user-images.githubusercontent.com/1094306/164165312-f60fe38c-72e3-42e0-9ea5-944bc5b14f4f.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for reporting the issue, @inc2734.

I think this is a duplicate of #39732.

**Comment by inc2734** [comment]
Wow, thank you, I was not aware of the existing issue. I am closing this issue.
