### ISSUE TITLE
Buttons: wp-block-button__link   not showing link button text in  Safari + IOS

### ISSUE THREAD

**Issue by Collie-IT** [WordPress/gutenberg#40465]
### Description

If wp-block-button__link  is used the link text is disapearing because of not hornering the display settings in Safari + IOS.
 

### Step-by-step reproduction instructions

Add a link button to the page.
Show page in Safari.

### Screenshots, screen recording, code snippet

Looks in Safarie/IOS so:

![2022-04-20_11h54_38](https://user-images.githubusercontent.com/40590185/164204131-418f3b14-c56f-4612-a6ae-bbd3bd61651a.png)

Button in backend
![2022-04-20_11h57_28](https://user-images.githubusercontent.com/40590185/164204145-2b60da9f-1404-4d2c-be0a-923782b515f9.png)

HTML in Safari developer :
![2022-04-20_11h56_53](https://user-images.githubusercontent.com/40590185/164204141-d118df6a-ec63-4350-b2a4-521fe46661e7.png)

CSS button
![2022-04-20_11h56_40](https://user-images.githubusercontent.com/40590185/164204527-efad0a9e-69cd-4ec6-8e28-08c012088545.png)

### Environment info

Wordpress  5.9.3
Gutenberg (includiert in Wordpress 5.9.3)
Suki 1.3.7

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ellatrix** [comment]
What theme are you using, and could you provide the exact steps to reproduce?

**Comment by jordesign** [comment]
Hi @Collie-IT - just checking in again to see if you have further details of recreating this? Is it still present for you in WP6.3?

**Comment by karmatosed** [comment]
Thank you for reporting this, @Collie-IT. I admit I am struggling a little to recreate this for you, so I am going to close this for now. That doesn't mean that if you are still experiencing the issue, this can't be reopened. If you can provide some more details, then we can change that back to open.
