### ISSUE TITLE
wp_enqueue_block_style no longer adds styles in the site editor if Gutenberg 13.0 is active

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#40469]
### Description

In WordPress 5.9x, a block theme can use [wp_enqueue_block_style](https://developer.wordpress.org/reference/functions/wp_enqueue_block_style/) to add additional stylesheets to blocks.

But when Gutenberg 13.0 is active, the styles are no longer applied in the site editor or template editor, only in the block editor and the front.

### Step-by-step reproduction instructions

Activate a theme that uses wp_enqueue_block_style.

1. In the site editor, add one of the styled blocks.
2. Save and view the front.
3. Compare the Site Editor and front and see that the styles do not match.

### Environment info

WordPress 5.9.3
Gutenberg 13.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I confirmed that this is still happening with 6.0-beta2-53249 and current Gutenberg trunk.
Does not happen with 6.0-beta2-53249 only.
Does not happen on 6.0-beta2-53249 or 5.93 with Gutenberg 12.9.

Can someone confirm if this was an intentional change or a bug?
I don't know who to ask, @Mamaduka?

**Comment by Mamaduka** [comment]
Pinging @adamziel and @gziolo.

I’m offline today, but can have a look tomorrow.

**Comment by gziolo** [comment]
> Does not happen with 6.0-beta2-53249 only.

It doesn't look like it's an issue with WordPress core.

**Comment by Mamaduka** [comment]
I am marking this as a regression. I will try to debug the issue later this week.

**Comment by Gierand** [comment]
@carolinan, @Mamaduka when enqueueing stylesheets via add_editor_style, they are also noticeably absent.

**Comment by ndiego** [comment]
Just confirmed this no longer works in 6.0 RC1 (without Gutenberg active). I'm elevating this issue as it's a breaking change.

**Comment by ndiego** [comment]
cc @annezazu @priethor @gziolo @adamziel Unfortunately, this is another one. It's a significant breaking change that we need to get fixed before the 6.0 release.

**Comment by gziolo** [comment]
As noted in https://github.com/WordPress/gutenberg/issues/40562#issuecomment-1117170676. It must be something with passing styles to the iframed editor. The following sentence is a great confirmation of that:

> But when Gutenberg 13.0 is active, the styles are no longer applied in the site editor or template editor, only in the block editor and the front.

**Comment by carolinan** [comment]
Possibly related:
https://github.com/WordPress/gutenberg/issues/40603

**Comment by ndiego** [comment]
@carolinan yup, that looks to be the same issue. So it appears this was introduced in 13.0, I'm going to start going through the changelog there.

**Comment by carolinan** [comment]
wp_enqueue_block_style uses enqueue_block_assets to add editor styles, Gutenberg active, I need to combine wp_enqueue_block_style with add_editor_style to add CSS to the site editor.

**Comment by carolinan** [comment]
:/ OK adding add_editor_style no longer works with 6.0 Rc1. It did work in beta 2.

**Comment by gziolo** [comment]
A potential fix is ready for testing: #40842.
