### ISSUE TITLE
Global Styles panel: iterating on the "Browse styles" button

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#40478]
This issue is an offshoot of https://github.com/WordPress/gutenberg/issues/38934

One topic that came up in the recent [6.0 walkthrough](https://make.wordpress.org/core/2022/03/30/6-0-product-walk-through) is that the "Browse styles" button placement on the main Global Styles panel currently feels a bit out of place. See https://github.com/WordPress/gutenberg/issues/38934#issuecomment-1089642706

I wanted to share a couple of low-hanging fruit ideas about how this panel could be reorganized with small tweaks:

<img alt="browse-styles" src="https://user-images.githubusercontent.com/77359364/164794059-ca03c239-5ebe-4efd-933b-5a81d012e7bb.png">

**Left:**
This version creates a distinct top and bottom section, with the "Browse styles" button grouped at the top with the preview.

**Right:**
This version displays the "Browse styles" button alongside other options for Typography, Color, etc. 

In both versions above, the "Blocks" item is no longer treated as its own separate section and is grouped together with the other options.

Props to @jasmussen for helping brainstorm!
CC @pablohoneyhoney

**Comment by annezazu** [comment]
Thank you for splitting this off and providing a few directions <3

**Comment by critterverse** [comment]
Closing this issue based on feedback received in https://github.com/WordPress/gutenberg/pull/41574#issuecomment-1161763713:

> but this iteration seems to mix the information architecture in ways that are more confusing. It's important to keep the Blocks panel separate from the style elements, and the "browse styles" exists at an entirely different level. This design fails to communicate this in any meaningful way.

This will need to be revisited with a new approach!
