### ISSUE TITLE
Compatibility - Feedback for Gutenberg update 

### ISSUE THREAD

**Issue by Dentalicious** [WordPress/gutenberg#4047]
I watched the Wordcamp videos on the Gutenberg where it was encouraged that new users of Wordpress should give feed back.

I migrated from Squarespace and am loving Wordpress, I use Elementor which I believe is a wonderful page builder, better than what I used at squarespace and wix, however one of the major obstacles I have discovered and face by migrating to Wordpress is that not all themes are compatible with all plugins and vice versa, this becomes an huge irritant and crawls the process and sometimes no solutions can be found other than to hire a developer.

I am an end user, with no coding know how, however I have built a pretty decent website for myself using Elementor & Uber Menu as the central elements, of course with other plugins.

Suggestion: Everything should work with everything else, without ever changing or touching code. Easier said than done but if it happens, there would be many more users like me (non-coders) who would have the ability to migrate to Wordpress without having to worry about PHP, HTML, CSS or some other code.

**Comment by Soean** [comment]
Hey @Dentalicious,
thanks for your feedback. We develop for end users like you. Gutenberg is developed in such a way that no PHP or HTML knowledge is required.  The goal is to have as few problems with existing plugins and themes as possible. But that will not be completely avoidable.

Have you tested the new editor yet? You okay with that? For bugs that you find or if you have any functional ideas, you can open issues here. For general discussion there is a Gutenberg support forum: https://wordpress.org/support/plugin/gutenberg

**Comment by alexanderbiscajin** [comment]
I have also gone through several features of WordPress Gutenberg watching videos and tutorials https://www.wpblog.com/wordpress-gutenberg/. It has some problems integrating with WordPress plugins. Now this will be difficult for me to shift to WordPress 5.0 editor. I have gone through several communities and i have seen everywhere that people indicating some issues but i love WordPress, it's easy to manage for me.
