### ISSUE TITLE
ZIP files for Pull Requests are no longer made 

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#40483]
### Description

In https://github.com/WordPress/gutenberg/pull/26746 ; build tooling was adopted so that a zip file of Gutenberg for every Pull request changes were created for each pull request. 

**The zip contains the gutenberg plugin built and ready for use,** 

- This greatly lowers the barriers & obstacles for users to test out pull requests: 
- git and extensive configuration is no longer needed

To test out a pull a request, a user downloads the zip in their plugins directory, extract the folder and files, and activate the plugin; just like any other plugin. 

I've noticed for some time that these are no longer being generated 
(examples: https://github.com/WordPress/gutenberg/pull/40410 https://github.com/WordPress/gutenberg/pull/40136 https://github.com/WordPress/gutenberg/pull/36590  https://github.com/WordPress/gutenberg/pull/33496

and hadn't found any issues stating why this was removed. 

### Step-by-step reproduction instructions

1. Visit [any open pull request](https://github.com/WordPress/gutenberg/pulls)
2. go towards bottom of pages where the builds, checks are occurring; 
3. read that the build zip was skipped
![image](https://user-images.githubusercontent.com/955351/164273235-f81bb4db-8c97-4dc9-b703-8013e58fbd8a.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I am not sure why the jobs are showing as skipped on the likes of [#40410](https://github.com/WordPress/gutenberg/pull/40410), but the zip file is still available under the Checks tab:

https://user-images.githubusercontent.com/3629020/164350009-e83411f7-f26f-4931-a1df-633f36ea3fee.mp4

**Comment by talldan** [comment]
It's a bit confusing because there are multiple 'build plugin' jobs and some are skipped because they're only triggered as part of the actual release workflow. I'm not sure if there's a way to hide them given they're irrelevant for most PRs. 

On all of those PRs linked there's still a 'Build Gutenberg Plugin Zip / Build Release Artifact (pull_request)' job that's required. It's near the bottom, and if you click 'Details' and then click 'Summary', the zip is available that way too:
![Screen Shot 2022-04-21 at 11 00 20 am](https://user-images.githubusercontent.com/677833/164363254-55b4cbcd-bbd0-4800-8b79-628a11f50b2b.png)

Maybe there docs that can be updated to clarify this.

**Comment by skorasaurus** [comment]
> I am not sure why the jobs are showing as skipped on the likes of [#40410](https://github.com/WordPress/gutenberg/pull/40410), but the zip file is still available under the Checks tab:
> zip.mp4

Thanks @glendaviesnz ; I didn't look there. I don't know whether this feature (getting zips of pull requests for easy testing!) 
has been documented anywhere or where the best place would be to document this; maybe @ryanwelcher or @annezazu would have ideas; otherwise, I'll close this.

**Comment by stevebab** [comment]
@skorasaurus , you are a blessing. Thank you, it works beautifully. I wish we could get this into a "Gutenberg Settings" feature at some point, but this is is exactly what most of my agency's workload requires.  
Now to figure out how to disable the "Download" button by default!
