### ISSUE TITLE
Posts Written In Gutenberg Are Not Sent to Telegram App

### ISSUE THREAD

**Issue by TheJeffr0** [WordPress/gutenberg#4048]
When a post is written and published from Gutenberg, the post is not sent out to Telegram subscribers. However, the post is sent through Jetpack's Publicize to Twitter and Facebook subscribers. 

When a post is written and published in the classic editor, it's sent out to Telegram Subscribers. 

Using the [Telegram for WordPress](https://wordpress.org/plugins/telegram-for-wp/) plugin version 1.6.1. WordPress 5.0-alpha-42393, and Gutenberg 1.9.1.

**Comment by nowliveit** [comment]
Are there plans to add the Telegram option to Gutenberg. For me, this is helpful to send to all social media sites it supports. Thanks. I like the editor as I play with it but will use Classic Editor for now.

**Comment by TheJeffr0** [comment]
Yep, it eventually was fixed.

**Comment by danielbachhuber** [comment]
Cool, thanks for the update.
