### ISSUE TITLE
Webfonts: Multiple Typeface resources not loaded

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#40487]
### Description

As noted elsewhere when multiple targets are defined via theme.json for the webfonts API only the first is loaded.  This seems to be true both for italic variations as well as typefaces for various font weights.

### Step-by-step reproduction instructions

With the following fonts defined in theme.json:

```
...
		"typography": {
			"fontFamilies": [
				{
					"fontFamily": "Inter, sans-serif",
					"slug": "body-font",
					"name": "Body",
					"fontFace": [
						{
							"fontDisplay": "block",
							"fontFamily": "Inter",
							"fontWeight": "100",
							"fontStyle": "normal",
							"fontStretch": "normal",
							"src": [
								"file:./assets/fonts/Inter-Light.ttf"
							]
						},
						{
							"fontDisplay": "block",
							"fontFamily": "Inter",
							"fontWeight": "500",
							"fontStyle": "normal",
							"fontStretch": "normal",
							"src": [
								"file:./assets/fonts/Inter-Regular.ttf"
							]
						}
				}
			],
		}
...
```

Note that only the following is rendered:
```
<style id='webfonts-inline-css'>
@font-face{font-family:Inter;font-style:normal;font-weight:100;font-display:block;src:local(Inter), url('/wp-content/themes/themes/pendant/assets/fonts/Inter-Light.ttf') format('truetype');font-stretch:normal;}
</style>
```

whereas entries for both Inter-Light and Inter-Regular are expected.

### Environment info

- WordPress 5.9
- Gutenberg Trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
thanks for reporting; it's a duplicate https://github.com/WordPress/gutenberg/issues/40453 ; so I'm closing this to consolidate discussion.
