### ISSUE TITLE
[RNMobile] Pasting HTML content with inline data URL results in blank Post

### ISSUE THREAD

**Issue by twstokes** [WordPress/gutenberg#40485]
## Description
Pasting HTML content that contains an inline data URL:

```
<img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD...
```

May render fine in the block editor but result in blank content when published. No error is shown to the user when publishing.

## Step-by-step reproduction instructions
This was tested on a .com Simple site:

1. Start a new post in WPiOS
2. Copy the [content from this gist](https://gist.githubusercontent.com/twstokes/c648081ef9fec252c7aca57a75307b30/raw/382322543a74a767c40e9b89a4c819fc30ae32b0/gistfile1.txt) 
**⚠️ Important:** The source app that this content is copied from is a factor. Copying the gist from Google Chrome may not work. 
**Flows that cause the issue**: Saving the gist and copying from VS Code into Simulator. Copying content from Microsoft OneNote.
3. Paste it into the block editor
4. Observe that the content renders correctly in the mobile block editor
5. Tap Publish
6. Observe that the published post is empty on the web

Examining the HTML source shows that the content isn't in the post (so it's probably not a web rendering problem).

## Expected behaviour
Either an error is shown that the post can't be published or perhaps elements with [inline data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) are stripped (or shown as unsupported).

## Actual behaviour
User is able to publish the post without error. The post is empty on the web.

## Screenshots

| Mobile Editor | Published Post on Web |
| - | - |
| ![Simulator Screen Shot - iPhone 13 - 2022-04-20 at 12 52 21](https://user-images.githubusercontent.com/2092798/164282830-714190f7-641e-48d0-9af2-3d79c8f3879c.png) | <img alt="Web screenshot" src="https://user-images.githubusercontent.com/2092798/164277077-56bf2881-898e-449a-bc7e-50a5e2332a06.png"> |

## WordPress information
- WordPress version: .com Simple Site
- Gutenberg version: [.com Simple Site version]
- Are all plugins except Gutenberg deactivated? Plugins aren't available.
- Are you using a default theme? Farrow

## Device information
- Device: iPhone 13
- Operating system: iOS 15.4
- WordPress app version: 19.7

**Comment by hypest** [comment]
I'm seeing the same "empty published post" behavior when pasting the gist content via the web block editor on a WPCOM Simple site so, my current understanding is that this is not a mobile app specific issue.

### More context

Reproduced on WPCOM Simple using
Gutenberg: v13.1.0
Editing Toolkit: 3.32212
WP AMP: 2.0.5
CoBlocks: 2.18.1-simple-rev.1

_Not_ reproduced on a Pressable selfhosted site using Gutenberg plugin v12.6.0.

**Comment by dcalhoun** [comment]
Reviewing this in an effort to help with a [call to review](https://wordpress.slack.com/archives/C02RQC4LY/p1703002380170619) high priority issues. There appear to be a few separate issues occurring in this report, some of which have likely changed over time. I suggest we separate them to prioritize them each appropriately. 

* https://github.com/Automattic/wp-calypso/issues/44728 
* https://github.com/WordPress/gutenberg/issues/57264
* https://github.com/WordPress/gutenberg/issues/57265

With that, I am closing this issue, but feel free to re-open if desired.
