### ISSUE TITLE
FSE: Image block in Site Editor looses alignment options unless in a another block

### ISSUE THREAD

**Issue by Greatdane** [WordPress/gutenberg#40500]
### Description

When I add an image on an FSE theme (in Editor or in pages/posts) the image toolbar does not show the control to edit the alignment. This only changes when the image is added to a group.

### Step-by-step reproduction instructions

1. Start with FSE theme
2. Add image to page.
3. To add the missing alignment command, add the block to a group.

### Screenshots, screen recording, code snippet

Image block in Site Editor: 

<img width="1889" alt="Markup 2022-04-21 at 15 09 24" src="https://user-images.githubusercontent.com/5075840/164385882-0e50a7ad-56c4-4c3b-ae7f-62fc98acbedf.png">

Image block nested in a Group block in Site Editor: 

![Annotation on 2022-04-21 at 15-10-52](https://user-images.githubusercontent.com/5075840/164385908-4f2fa8d6-b128-4fd0-a555-4fc7713246c1.png)

Video;

https://user-images.githubusercontent.com/5075840/164385968-65806929-4313-4bab-b6cb-c4e7fb04c2ad.mp4

### Environment info

WordPress 5.9
Gutenberg 13.0.0
Theme; Zoologist

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @Greatdane

It is intended behavior. The following comment explains the reasoning behind it - https://github.com/WordPress/gutenberg/issues/38802#issuecomment-1040353976.
