### ISSUE TITLE
add_editor_style should perform wp_remote_get with headers

### ISSUE THREAD

**Issue by SilverMira** [WordPress/gutenberg#40520]
### Description

Faced a minor annoyance with the block editor.

While developing a new theme using Vite to compile the editor styles, I can link the dev server URL of the css directly with `add_editor_style('http://localhost:3000/src/editor-styles.scss')`. Normally, it will fetch the css content from the dev server and embed it in the `wp.editPost.initializeEditor()` js function in the block editor. 

This is where an unique interaction with Vite's dev server happens, the dev server expects the incoming request to have a header of `Accept: text/css` to fetch the raw compiled css, else it will respond a js version of the css with HMR code.

Currently, `add_editor_style` is performing a `wp_remote_get` without sending this header. Adding the header when performing the request shouldn't be a breaking change either.

```
//block-editor.php:536
$response = wp_remote_get( $style , array( 'headers' => array( 'Accept' => 'text/css' ) ) );
```

Vite is the only one having this problem at this moment, tested with Webpack without any issues. Still, having the header is probably more accurate when fetching for a remote css.

### Step-by-step reproduction instructions

1. Set up a Vite dev server for a theme
```
// vite.config.js
export default defineConfig({
    base: './',
    build: {
        outDir: 'dist',
        emptyOutDir: true,
        manifest: true,
        cssCodeSplit: true,
        rollupOptions: {
            input: [
                'src/editor-styles.scss'
            ],
        }
    }
})
```

```css
/* src/editor-styles.scss  */

body{ background-color: black; }
```
```
npx vite dev
```
2. In theme `function.php`
```
add_editor_style('http://localhost:3000/src/editor-styles.scss');
```
3. Go to block editor

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/66930495/164479608-bfcdcdc3-e37d-4b13-9f70-0c5817fdd452.png)

Vite's compiled css with HMR code fetched and embedded to the browser instead
![image](https://user-images.githubusercontent.com/66930495/164480167-34f76fbd-7926-4747-afd4-249b3b3105d1.png)

### Environment info

- Wordpress 5.9.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment]
`add_editor_style` is pretty much a legacy API at this point, which is very unlikely to change. I'd recommend using the `enqueue_block_assets` hook instead, where you can enqueue anything you want. These styles will also be loaded in the editor.

For more info, check out: https://make.wordpress.org/core/2023/07/18/miscellaneous-editor-changes-in-wordpress-6-3/#post-editor-iframed

**Comment by ellatrix** [comment]
And if you can't use `enqueue_block_assets` for some reason, maybe using a CSS @import?
