### ISSUE TITLE
Button: Inconsistent behaviour when adding a URL

### ISSUE THREAD

**Issue by mikeyarce** [WordPress/gutenberg#4053]
## Issue Overview
When creating a new Button block and adding the URL, sometimes when you hit "return" it will actually give you a different link.

## Steps to Reproduce (for bugs)

1. Create a new button block
2. Start typing `http://` and you will see some suggestions
3. Type something external, and press "Return" on your keybaord
4. The first suggestion will show as the URL instead of the actual URL you just typed

Chrome 63.0.3239.84 / MacOS Sierra

## Expected Behavior
I expected that when I hit "Return" I would get some kind of confirmation that my link was added properly.

## Current Behavior
Instead, a different link was added

## Screenshots / Video
![button-link](https://user-images.githubusercontent.com/3220162/34068286-12faa774-e1ed-11e7-88ac-944933e94819.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
I was able to reproduce this on `master`:

![incorrectlink](https://user-images.githubusercontent.com/36432/35304825-cd1ec8e8-004b-11e8-800c-6e5b2bf93dc8.gif)

**Comment by danielbachhuber** [comment]
I took a brief look at the underlying code and discovered a couple of options:

### 1. Disable `onKeyDown` handling when there's an outstanding `this.suggestionsRequest`

![image](https://user-images.githubusercontent.com/36432/35305456-2ea04d1a-004e-11e8-81e6-387c7017309b.png)

Given the suggestion is just about to change, I don't think it makes sense for Gutenberg to handle a keyboard event that touches the suggestionlist.

### 2. Disable suggestions when `http://` or `https://` are entered in the value

![image](https://user-images.githubusercontent.com/36432/35305554-88654472-004e-11e8-8612-2f81533a65f7.png)

It's less likely the user would want a suggestion when they're manually typing in an URL.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521136033000325)._

**Comment by danielbachhuber** [comment]
This was addressed by #4649
