### ISSUE TITLE
Comments Title: Count toggle working in 'Singular' editing mode

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40541]
Best explained with a video:

https://user-images.githubusercontent.com/846565/164689000-3ea49e5c-ba96-42cd-8dea-2e43a878d6db.mp4

**Comment by cbravobernal** [comment]
I'm thinking about the best way to approach this fix and, as 'One response' is a just placeholder sentence, editable, which option could be better?

 - Add different placeholder depending on Show Comments Count (One response vs Response or whatever word). We would add a new string (we are in string freeze), and we would just change the default placeholder regarding showing the comment or not.
 - Hide "Show comments Count" if Singular mode is enabled.

What do you think @jameskoster ?

I guess the first option is easier for UX, but I cannot find any word for a singular title with no comments count right now 😅 

cc: @carolinan @paaljoachim @justintadlock
