### ISSUE TITLE
Add option in editor settings to show open list view as default

### ISSUE THREAD

**Issue by ennohyttrek** [WordPress/gutenberg#40565]
## What problem does this address?
For people (like me) who work with the list view in the editor all the time, it could be very helpful and a time saver, if there was a setting to make an open list view the default setting when entering the editor.

## What is your proposed solution?
Add an option to options > settings to have the list view open by default

**Comment by ramonjd** [comment]
I've thrown up a [PR](https://github.com/WordPress/gutenberg/pull/40757) for this. 

I'm not sure what the appetite for it is, so let's see 😄  It's something I'd personally find useful.
