### ISSUE TITLE
Style Variations: Add warning when custom styles will be lost

### ISSUE THREAD

**Issue by clubkert** [WordPress/gutenberg#40561]
## What problem does this address?

If a user creates a custom style and then switches to another style variation, the previous customizations are lost.

In the below video, I switch the background color to a gradient. However, if I then try out different style variations, my previous settings are lost with no warning.

https://user-images.githubusercontent.com/2229643/164800702-2905ca70-c6f8-4565-a4c6-dd8a8b1f16d4.mov

## What is your proposed solution?

If I've made changes to my style settings, I'd expect a warning before switching to another variation letting me know that I'll lose my changes if I don't save the page first.

This might be related to saving style variations (https://github.com/WordPress/gutenberg/issues/38333)

**Comment by annezazu** [comment]
Closing this out in favor of this overall issue that references this problem as something to solve: https://github.com/WordPress/gutenberg/issues/45371 Thank you for opening this!
