### ISSUE TITLE
Content loss when switching between code and visual editor with the keyboard shortcut (Ctrl+Shift+Alt+M)

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#40575]
### Description

As @angelxube reported on [Trac 49795](https://core.trac.wordpress.org/ticket/49795):

> When using keyboard shortcut Ctrl+Shift+Alt+M to switch from code editor back to visual editor all text will be lost. Pressing top right link or switching throught options menu works without problem. I consider this as a bug, because user will lost any change he put to code editor unless he previously save his work or click on link "Back to the visual editor"

### Step-by-step reproduction instructions

1. Create a new post or page.
2. Switch to Code view (on PC, `Ctrl + Shift + Alt + M`).
3. Start typing in the post content area.
4. Use the keyboard shortcut again to exit Code view.
5. Notice that what you typed is gone.

### Screenshots, screen recording, code snippet

@afercia's graphic from the Trac ticket:

![animated graphic of content loss when exiting Code view](https://core.trac.wordpress.org/raw-attachment/ticket/49795/content%20loss%20switching%20mode..gif)

### Environment info

[Trac 49795](https://core.trac.wordpress.org/ticket/49795) reported it as early as WordPress 5.4.

WordPress versions I used:
- 5.9 without Gutenberg
- 5.9 with Gutenberg 13.0.0
- 6.0 beta 2, without Gutenberg

Browser/OS:
Firefox 99.0.1/Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sabernhardt** [comment]
@Otto42's comment:

> It appears that clicking anywhere outside of the content block makes it "stick" when you switch. It only loses content when you switch with the keyboard without ever leaving the text block.
>
> Seemingly anything that causes that text box in the code editor to lose focus will save it, and then it will be there after the switch.

**Comment by ndiego** [comment]
I have confirmed this. While we need to fix this bug, at this point in the release process, I think we should hold off trying to include in 6.0. We could always include in a minor release. Thoughts @Mamaduka @gziolo?

**Comment by gziolo** [comment]
Content loss is always a critical issue that should have maximum priortity.

**Comment by Mamaduka** [comment]
I will try to have a look at this issue in a bit 👍
