### ISSUE TITLE
Post comments form text alignment does not work

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#40576]
### Description

The text alignment setting on the post comments form block does not work correctly. I believe this is a regression after #40368.

In the editor, the heading "Leave a reply" remains aligned to the left (not tested on rtl!),
The label and button below the form are aligned according to the setting.

On the front, none of the text is aligned anymore.

### Step-by-step reproduction instructions

1. Add a post comments form in the block editor
2. Use the text alignment option in the block toolbar.
3. Confirm if the heading aligns or not.
4. Save and view the front of the website.
5. Compare the text alignments.

### Screenshots, screen recording, code snippet

# 13.0.0
Editor:
![Editor place holder is centered](https://user-images.githubusercontent.com/7422055/165034387-10eb61e1-f541-466e-b73b-edf2ba296bf3.png)
Front:
![the text in the form is centered](https://user-images.githubusercontent.com/7422055/165034483-d63707bb-4eb7-4b4d-a957-f274c449cb05.png)

# Gutenberg trunk
Editor:
![the heading above the form is not aligned according to the setting](https://user-images.githubusercontent.com/7422055/165034662-9f96de53-0fa2-4a49-bee7-cb70afb95df6.png)
Front:
![None of the text is aligned according to the setting](https://user-images.githubusercontent.com/7422055/165034787-1a919f6c-1a41-4cbb-984d-810cae97ac2c.png)

### Environment info

WordPress 6.0-beta2-53249
Beta tester plugin is installed
Compared between Gutenberg current trunk and Gutenberg 13.0.0.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by carolinan** [comment]
Is it worth solving this before the block is [split into its inner blocks](https://github.com/WordPress/gutenberg/issues/38107)?

**Comment by cbravobernal** [comment]
> Is it worth solving this before the block is https://github.com/WordPress/gutenberg/issues/38107?

I guess it is!

**Comment by carolinan** [comment]
This has been solved, so I am closing the issue
