### ISSUE TITLE
Shortcut Ctrl-Alt-Shift-M does not work in editor

### ISSUE THREAD

**Issue by axadr** [WordPress/gutenberg#40577]
Page editor - wp/wp-admin/post.php?post=1234&action=edit
Hot key to switch the editor mode Ctrl-Alt-Shift-M works only if you take a mouse and click on the edit area.
Moreover, after the trigger, it does not work again.

**Comment by Mamaduka** [comment]
Hi, @axadr

I can no longer reproduce this issue when testing with the latest WordPress. The keyboard shortcuts work even after the focus loss.

I will close the issue; feel free to re-open it if you're still experiencing the bug.
