### ISSUE TITLE
Title Block undo/redo goes letter by letter

### ISSUE THREAD

**Issue by jaschaio** [WordPress/gutenberg#4057]
I think the history undo and redo buttons for the title block should work like within the paragraph block. The state should only change once the user stops typing and not after each letter. 

Wrong Behaviour:
![title](https://user-images.githubusercontent.com/11058666/34096471-b5dcc3ac-e3d5-11e7-92c5-6480ecde6bc9.gif)

Correct Behaviour:
![text](https://user-images.githubusercontent.com/11058666/34096467-b489a772-e3d5-11e7-8b61-12e26d60a53d.gif)

**Comment by aduth** [comment]
Related: #2932
Slated to be fixed by #4008

**Comment by afercia** [comment]
Hm, I'm not sure I agree. Ideally, the undo/redo behavior should work exactly like in the current editor because that's what users would expect. I know that under the hood, things work differently in utenberg and I'm not sure if that's feasible.

**Comment by aduth** [comment]
>Hm, I'm not sure I agree. Ideally, the undo/redo behavior should work exactly like in the current editor because that's what users would expect. I know that under the hood, things work differently in utenberg and I'm not sure if that's feasible.

Not clear what you disagree with. The behavior of the classic editor is in line with what's being suggested by the original comment

![undo](https://user-images.githubusercontent.com/1779930/35578910-58faf65e-05b3-11e8-9a4e-a70e87db9270.gif)

**Comment by afercia** [comment]
Sorry I misread the issue.

**Comment by mtias** [comment]
@aduth removing in progress label as it doesn't seem we have open PRs for it anymore.

**Comment by aduth** [comment]
The changes in #4956 set a foundation for this to occur in that, similar to how we batch sequential block updates, we can batch sequential post updates for the same property (i.e. `edits.post_title`).
