### ISSUE TITLE
Cannot change alignment of Media & Text block in Widgets

### ISSUE THREAD

**Issue by kangabell** [WordPress/gutenberg#40597]
### Description

When editing a post I can change the alignment (e.g. "Wide width", "None") of a Media & Text block, but in Widgets the control to do this is missing. This makes any of these blocks stuck forever on "wide width" which is the default and I can't find any way to change it.

### Step-by-step reproduction instructions

1. Go to Appearance -> Widgets.
2. Add a Media & Text block.

### Screenshots, screen recording, code snippet

Widgets:
![widgets](https://user-images.githubusercontent.com/5122304/165167441-0888dd84-1a25-47da-ac9f-c2e6000b8f11.png)

Post Editor:
![post-editor](https://user-images.githubusercontent.com/5122304/165167456-a300931d-3f95-42ea-b367-eec05223a2fe.png)

### Environment info

- WordPress Version 5.9.3
- Gutenberg Version 13.0.0
- Theme: Twenty-Twenty
- Tested in Firefox on desktop on MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kangabell** [comment]
linking https://github.com/WordPress/gutenberg/issues/20941 as it would be helpful in this situation.

**Comment by kangabell** [comment]
https://github.com/WordPress/gutenberg/issues/35468 would help too.

**Comment by gamebits** [comment]
Similar issue https://github.com/WordPress/gutenberg/issues/36967 indicates that the alignment options also disappear when the block is in a column.

**Comment by strarsis** [comment]
+1, `Media & Text` block alignment option is (also) missing when it is inside a `core/group` block.
Also in editor the alignment class (`alignwide`/`alignfull`) is missing, causing formatting inconsistencies.

**Comment by carolinan** [comment]
Currently, no blocks on the widget screen seems to support wide and full width, I do not think this is limited to the Media & text block. Please see
https://github.com/WordPress/gutenberg/issues/41418
https://github.com/WordPress/gutenberg/issues/35468

**Comment by twobyte** [comment]
Issues like this make the block editor very difficult to use.

A workaround I have found is to create the Media & Text block at the top page level, set the alignment to normal, then copy and paste the block with the correct width into your columns or group.

**Comment by jordesign** [comment]
Agreed the ability to set a width on blocks in the widget screen is important. As it affects multiple blocks (not just Media/Text) I'll close this issue in favour of https://github.com/WordPress/gutenberg/issues/35468
