### ISSUE TITLE
Post author: Byline encourages HTML but it is sanitised

### ISSUE THREAD

**Issue by dsas** [WordPress/gutenberg#40600]
### Description

The post-author block allows entering a byline using a `RichText` component. When entering a byline I have buttons for emphasis, strong and so on. 

When viewing a byline these tags are escaped.

In Gutenberg I have this mark-up:
```
<!-- wp:post-author {"byline":"my \u003cem\u003eawesome\u003c/em\u003e byl\u003cstrong\u003ein\u003c/strong\u003ee"} /-->
```

which looks like this in Gutenberg:
![image](https://user-images.githubusercontent.com/93301/165189334-5fa4df56-4eb0-4068-913b-53b69b14e774.png)

and looks like this on the front end:
![image](https://user-images.githubusercontent.com/93301/165189378-fe5372ba-301a-4ca5-bc9a-cbdc653ed246.png)

I expect what I see on the front-end to look like what I see in Gutenberg

### Step-by-step reproduction instructions

 1. Create a new post, I did it as an admin, though user level shouldn't matter
 2. Insert the Post Author block
 3. Type in a byline, using some of the formatting buttons e.g. to emphasise or bold some of the text
 4. Save the post
 5. View the post

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/93301/165190001-7ee02bae-bcac-48c8-be5c-82a9ebd35546.mp4

The data is escaped here:
https://github.com/WordPress/gutenberg/blob/c5b9ca14e68ad6ee2aefa2973589f36cac388a7e/packages/block-library/src/post-author/index.php#L42

### Environment info

Using the Gutenberg development docker image, `a0e1728bc` is my current HEAD

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Thanks for opening up an issue for this one! It looks like the common / desired way to server-render attributes that are set via `RichText` components in the editor is to use `wp_kses_post` to sanitize output instead of escaping the HTML characters (based on earlier discussion in https://github.com/WordPress/gutenberg/pull/38649#pullrequestreview-876867685). I've opened up a small PR in #40776 to fix this up for the Post Author block.
