### ISSUE TITLE
Allow changing a table rows/columns number using arrow keys

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#40608]
### Description

While creating a table block, when defining the number of rows and columns, it is not possible to change the inputs using the arrow keys on the keyboard.

### Step-by-step reproduction instructions

1. Create a new post
2. Add a new table block
3. Try to change the number of rows or columns in the inputs using the arrows keys
4. Notice that this does not work

### Environment info

- WordPress 6.0-alpha-52931
- Gutenberg 13.1.0-rc.1
-  Chromium 100.0.4896.127 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by dsas** [comment]
I _think_ this is might be a general focus issue that happens to effect the Table block, rather than a problem with the Table block per se.

https://github.com/WordPress/gutenberg/issues/38548 looks to be a similar issue with the `ComboboxControl` component and possibly more widespread.
