### ISSUE TITLE
Warn users prior to removal of critical blocks in blog templates

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40618]
In the site editing context there are certain blocks that you shouldn't delete outside of edge cases – Post Content and Query Loop can cause a lot of damage if removed. It would be good to display a confirmatory modal when the user attempts to remove them. 

<img width="788" alt="Screenshot 2023-05-19 at 15 41 22" src="https://github.com/WordPress/gutenberg/assets/846565/ddd57e93-3344-4457-9ec2-8d36426f9f94">

To begin with we can display this when editing a blog template (Index / Home). But it would be good to expand that to include archive and singular templates after.

**Comment by fabiankaegy** [comment]
This feature would also be great for 3rd party blocks.

I can think of 2 different ways of approaching it. 

### 1. On a Block Level
The first thing that came to mind was building this out as a block support property that blocks can define. 

`block.json`
```json
{
    "supports": {
        "warnBeforeRemoval": true
    }
}
```

```json
{
    "supports": {
        "warnBeforeRemoval": [ 'single-post', 'single-page' ]
    }
}
```
_Note: Not an actual API. Just as an example

### 2. On a Template Level
Another option is to expose this level of control on the template level. 
Maybe a Template could define blocks that are recommended and the warning gets shown when these recommended blocks are removed.

In either case, it should be filterable by theme / plugin authors. For the Post Title for example there are also other 3rd party blocks that save to the post title field and therefore are an actual replacement and it can make sense to have other recommended blocks than vanilla core would have :)

**Comment by jameskoster** [comment]
The block level approach sounds good as it would allow us to cover things like removing Post Template from Query Loop – something that can happen in both the site editor and the post editor.

**Comment by talldan** [comment]
> The block level approach sounds good as it would allow us to cover things like removing Post Template from Query Loop – something that can happen in both the site editor and the post editor.

Could it also be locked, or is there a use case for removing Post Template?

**Comment by jameskoster** [comment]
> or is there a use case for removing Post Template?

Perhaps edge cases like elaborate designs where you want pagination in a different location to the posts list? 🤔

**Comment by mtias** [comment]
I think this is a good opportunity to communicate the more intricate aspects of templates and content management, so we should be more forthcoming on why something is not advised — "this block is what displays the content of your posts, removing it would mean all your posts show empty in their permalink" or something.

**Comment by annezazu** [comment]
Based on experience with the FSE Outreach Program, I think this would go a long way towards guiding folks towards interacting with the pieces of the site editor/site editing experience appropriately/in a way that will lead to the outcomes they might want. Keen to get something in place and do a round of testing!

**Comment by jameskoster** [comment]
There's quite a lot of nuance to consider here. Removing a Query block from the Home template might yield a different message to removing it from the Index, Front Page, or Tag template. If comments are disabled for a particular post / post type, then we don't need to display a warning.

The first step is probably to identify which blocks prompt a warning, and then come up with generic-but-useful messages for each of them, and the basic conditions upon which they appear.

**Comment by ntsekouras** [comment]
Should we consider custom handling to just a few of these blocks for now before looking at an abstraction(like supports)?

**Comment by jameskoster** [comment]
It would be good to handle some of the more important cases. Post Content on Singular templates, and Query Loop on archive templates spring to mind.

**Comment by fabiankaegy** [comment]
I agree there are some core blocks that really should get this sooner than later so it might make sense to add a custom solution for them first. 

But I do want to also make the case that third-party blocks are very much in need of this as a standardized API. So it would be great if custom solutions don't mean that we never get a public API for it :)

**Comment by mtias** [comment]
Let's start with custom handling until the UX is sorted out and proven.

**Comment by mtias** [comment]
Can we start just with post content and query blocks in blog templates?

**Comment by richtabor** [comment]
> I think this is a good opportunity to communicate the more intricate aspects of templates and content management, so we should be more forthcoming on why something is not advised — "this block is what displays the content of your posts, removing it would mean all your posts show empty in their permalink" or something.

This is important; including the "why".
