### ISSUE TITLE
Separator block doesn't render as in the editor

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#40624]
### Description

The separators in the editor look different from the public version rendered.
If you add a custom color to a wide separator, you lose the height defined in `theme.json,` and you always get a line of 1px tall.

Example from `theme.json`
```
"core/separator": {
  "color": {
    "text": "var(--wp--custom--color--foreground)"
  },
  "border": {
    "width": "0 0 3px 0"
  }
},
```

### Step-by-step reproduction instructions

1. Go to the admin
2. Create a new post
3. Add a separator block
4. Activate the wide option of the separator block
5. Add a custom color to the block
6. Publish the post
7. View and compare the public version with the editor one.

### Screenshots, screen recording, code snippet

In these videos, you will see that if you add a custom color to a wide separator, you lose the height defined in theme.json.

Using TT2 theme:

https://user-images.githubusercontent.com/1310626/165323916-34472377-fc38-4b71-b4e3-6946bf1ec131.mp4

Using Skatepark theme:

https://user-images.githubusercontent.com/1310626/165323865-ff26da21-bb3a-472e-8a53-1e2ee5971a56.mp4

### Environment info

- WordPress  5.9.3
- Latest Gutenberg dev version

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
This is because of the following

```css
.wp-block-separator.has-background:not(.is-style-dots) {
  border-bottom: none;
  height: 1px;
}
```

in the separator [theme.scss](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/separator/theme.scss#L19). Do you know what the reasoning is behind resetting the height like this when there is a background color set @scruffian ?

**Comment by scruffian** [comment]
By default the color of a separator is applied to the border. When we set a color for a separator block we apply it to the background and remove the border. This inconsistency fees like its going to cause more problems in the future, so I'll see if we can change the approach.

**Comment by scruffian** [comment]
I found a very old PR that makes the height of the separator an attribute: https://github.com/WordPress/gutenberg/pull/26764

This raises more questions though - if we make height a block attribute then there's no way to modify it using theme.json. Would it be better to make height part of the theme.json spec so that it can be modified in that way?
