### ISSUE TITLE
Block Patterns unavailable on Gutenberg latest

### ISSUE THREAD

**Issue by johnstonphilip** [WordPress/gutenberg#40626]
### Description

Block patterns are not available for me on Gutenberg latest trunk.

When I deactivate gutenberg, block Patterns are available again

### Step-by-step reproduction instructions

1. Install Gutenberg v13.0.0
2. Go to "Posts" > "Add New", and try to insert a block pattern.
3. It should work fine. 
4. Pull gutenberg latest on `trunk`
5. Refresh your post in the editor from step 3.
6. Notice you cannot see any block patterns when attempting to insert a pattern anymore.

### Screenshots, screen recording, code snippet

<img width="1296" alt="Screen Shot 2022-04-26 at 10 31 21 AM" src="https://user-images.githubusercontent.com/7538525/165324492-13fe5a5c-7097-444d-8d28-dd7d4141b086.png">
<img width="1148" alt="Screen Shot 2022-04-26 at 10 31 40 AM" src="https://user-images.githubusercontent.com/7538525/165324503-daff3c3a-2ae2-4b0b-ad21-d155313a5dce.png">

### Environment info

- WP: Version 5.9.3 and also 6.0-beta2-53224
- Gutenberg 13.0.0 (works). Gutenber trunk latest (broken)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @johnstonphilip

The example code to reproduce the issue is missing from the description.

**Comment by johnstonphilip** [comment]
@Mamaduka Hey - there is no example code required to reproduce this.

**Comment by Mamaduka** [comment]
Sorry got confused by this step - `Add the above code to a plugin or theme to register a block pattern.`.

I'm not able to reproduce the issue on the latest trunk (2bbbcf58f1a05113267030f0ac884f6b814d5a85).

## Screenshot
![CleanShot 2022-04-26 at 20 24 50](https://user-images.githubusercontent.com/240569/165348045-45ff1ceb-a216-45c6-b308-65310146a59f.png)

**Comment by johnstonphilip** [comment]
Ah yeah I left that in by mistake! 

I just pulled latest again and the patterns are loading again, so something in a recent commit must have resolved the issue. Closing, thanks for testing.

**Comment by johnstonphilip** [comment]
@Mamaduka This is showing itself for me again, though only for my own custom patterns. It looks like this change might have been the cause:

https://github.com/WordPress/gutenberg/pull/39493/files

I was adding my block patterns on the `current_screen` hook, which means they are now being loaded too late.
