### ISSUE TITLE
Clarify next steps when a block is installed from the editor

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#40632]
### Description

When a block is installed from wordpress.org using the add block interface in the editor, I expect it to be immediately available for use.

If the block is not immediately available for use, I expect to see instructions with the next action I should take to use the block.

When a block is installed now, it is immediately added to content and an error message appears:

> Your site doesn't include support for the "block-prefix/block-name" block. You can leave this block intact or remove it entirely.

Ideally, the script required for the block would be automatically loaded. If not, then the error message should also provide instructions to refresh the editor.

### Step-by-step reproduction instructions

1. Add a new post or page
2. Add a block that is not currently installed on the site
3. See error

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/286171/165362769-e87fbd0e-7ad2-44f3-a8cc-03606f5518a5.mov

### Environment info

- WordPress 5.9.3, Gutenberg 13.0.0, a child theme of TwentyTwentyOne
- Firefox 99.0
- Laptop with Mac OS 12.3.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by talldan** [comment]
> When a block is installed now, it is immediately added to content and an error message appears:

When I read this, my impression was that this happens for every block and it sounded like a really bad bug. But I tested and other blocks seem to work ok, like the first Todo List block and that 'SV Block for Twitch'.

Would you be able to update the description?

> Ideally, the script required for the block would be automatically loaded. If not, then the error message should also provide instructions to refresh the editor.

I'm not sure if this is just an issue with that one plugin. A different error message for block directory blocks does sound like a good idea.
