### ISSUE TITLE
Selecting multiple non-text blocks using the shift key is no longer possible

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#40636]
### Description

Previously, you could hold down the shift key and select multiple blocks at once. This still works if you "start" with a paragraph or similar text-based block. However, if you try and select two non-text blocks using the shift key, such as two images, it is no longer possible. This is a bit hard to explain, so see the video below. 

I believe this may be related to the new functionality that allows you to select text across multiple blocks. As such, we should really try and get this resolved for 6.0. 

### Step-by-step reproduction instructions

1. Use the latest version of Gutenberg and 6.0 Beta 3 and Twenty Twenty-Two
2. Add two image blocks to the Editor
3. Hold down the shift key and try to select both, it **won't** work
4. Now revert to 5.9.3 and disable Gutenberg
5. Add two image blocks to the Editor
3. Hold down the shift key and try to select both, it **will** work

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4832319/165428766-24e596fc-d895-4ead-b34d-958b7c5c1b7a.mp4

### Environment info

- WordPress 6.0 Beta 3
- Gutenberg 13.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
@annezazu @priethor @gziolo @adamziel sorry for the ping, but wanted to get more eyes on this given how tight we are getting on time.

**Comment by annezazu** [comment]
Testing with just WordPress 6.0 beta 3 and can confirm the above. Here are some specific use cases to save some time:
- Selecting an image + holding down shift > can only select other text blocks (can't select another image, cover, or group block)
- Selecting a group block + holding down shift > can only select other text blocks (can't select another image, cover, or group block)
- Selecting a cover block at the bottom of List view + holding down shift + selecting a paragraph at the top of list view > selects everything in between.

Reverting back to 5.9.3, this is the prior behavior -- note though that I could replicate the above problem before reloading the page 🤔 Not sure what's going on there: 

https://user-images.githubusercontent.com/26996883/165433909-81aa7333-5992-442f-aa3c-245b385c6ff3.mov

**Comment by fabiankaegy** [comment]
Could this possibly be related to the changes in #40604 ?

**Comment by talldan** [comment]
> Could this possibly be related to the changes in https://github.com/WordPress/gutenberg/pull/40604 ?

I just gave the code from before that commit a test, and the bug was still present, so I don't think it's related to that.

From what I can tell, multi-selecting blocks now only seems to work when clicking on text.

**Comment by priethor** [comment]
Thanks for the thorough testing and detailed instructions. I did some of my own and I agree it seems related to the partial block multiselection.

One extra use test case:
- Partially select text in a paragraph -> Shift+click on an Image/Cover block that has an image -> it doesn't work
- Partially select text in a paragraph -> Shift+click on an **empty** Image/Cover block -> it works

It's also worth mentioning that selecting by dragging instead of using `Shift` works, as well as using `Shift` in the list view after selecting partial text, so it only seems related to using `Shift` in the canvas.
