### ISSUE TITLE
Documentation: Storify is shutting down - do you want to save the Storify in articles.md

### ISSUE THREAD

**Issue by rosswintle** [WordPress/gutenberg#4064]
docs/articles.md contains a link to https://storify.com/bph/wordpress-gutenberg-early-comments

Storify is shutting down. https://storify.com/faq-eol

You may want to archive this content elsewhere and change the link. Or maybe it will no longer be needed by the time Storify shuts down in May.

**Comment by bph** [comment]
Thank you for raising the issue! I am the owner of the mentioned Storify and I was not aware that it was listed in the document. I know a couple of people working on a solution to import storifies into WordPress. Once such an import is available I'll migrate the information to its permanent home, and share the link.
