### ISSUE TITLE
Navigation Block - submenu menu font styles appear incorrectly when switching to "Open on click"

### ISSUE THREAD

**Issue by hagege** [WordPress/gutenberg#40669]
### Description

There seems to be an issue with the navigation block: If I switch SUBMENUS to "Open on click" in the properties on the right, the set Appearance is obviously not taken into account, see the following video. 

### Step-by-step reproduction instructions

I think in the video you can see the issue very well

### Screenshots, screen recording, code snippet

![issue_navigation](https://user-images.githubusercontent.com/27292550/165676084-49a306b1-8ba5-4913-826f-d430c8f66719.gif)

### Environment info

- WordPress 6.0-beta3-53297
- Gutenberg Version 13.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Ye
![Uploading issue_navigation.gif…]()
s

**Comment by talldan** [comment]
> I think in the video you can see the issue very well

@hagege It's always helpful to include text instructions as there are contributors to this project that have visual impairment and may be unable to see the video.

Anyway, I tested and can confirm the bug, though with slightly different results. I guess it may differ depending on the active theme. In Twenty Twenty Two, the font weight looks ok in the editor, but on the front-end it's broken like your example.

**Comment by carolinan** [comment]
I can reproduce this. When we enable open on click, the menu item is a button, not a link text, and it looks like the browser /user agent styles for the button is overriding the inline _appearance_ styles which are on the parent `<nav>` item.

Chrome, PC

**Comment by hagege** [comment]
sorry, I will add a description next time 😓

**Comment by talldan** [comment]
> sorry, I will add a description next time 😓

Thank you for reporting the issue though, I don't mean to sound ungrateful!

**Comment by annezazu** [comment]
I can also reproduce this. Thanks so much for finding and opening this issue!
