### ISSUE TITLE
Full-site-editing: Allow to add text to site logo block

### ISSUE THREAD

**Issue by LukaszJaro** [WordPress/gutenberg#40688]
I wanted to add just plain text to the site logo block instead of an actual image. I could probably just use a paragraph or heading block but then you lose the markup like aria-current, rel=home and custom logo link class plus potentially other hooks not working with custom logo.

I wanted something like this:

`<div class="wp-block-site-logo"><a href="https://home.test/" class="custom-logo-link" rel="home" aria-current="page">MY TEXT LOGO</a></div>`

## What is your proposed solution?

- Include two types of site logo blocks, one is image logo block and the other is text logo block.
- Or offer option in existing block to use text logo but it would require the removal of some settings like 'image width' and 'use as site icon'

**Comment by ntsekouras** [comment]
Could the alternative of using a `Navigation` block with the `Home Link` work for you? It has `rel="home"` as well. It adds an extra layer for sure, but Site Logo is about having a logo and not text. IMO it could create more confusion if there was some kind of text version.

**Comment by LukaszJaro** [comment]
There's numerous WordPress sites I encountered that have just text based logo, so that's why I think some input on this would be good and to set a standard.

https://davidhoywp.com/
https://billbennett.co.nz/category/computing/

Maybe navigation block would do. I'm not sure how in demand something like this is but I do see it out in the wild.

**Comment by LukaszJaro** [comment]
Site title block can also be used:

https://fullsiteediting.com/site-creators/what-is-a-full-site-editing-template/
https://andersnoren.se/themes/miyazaki/2014/08/03/alfred-magazine-rack/

**Comment by annezazu** [comment]
@LukaszJaro thanks for opening this! Is there a reason why the Site Title or Site Tagline block won't work for you? Curious to hear more about this use case.

**Comment by LukaszJaro** [comment]
@annezazu I think site title is one of the best solutions to this. I'll close this off and can be used for reference, thanks!
