### ISSUE TITLE
Latest Posts: Incorrect tab-order when featured image is linked and floated right

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#40686]
Steps to reproduce:

* Have several published posts each with a featured image attached
* Insert a latest posts block
* Toggle showing featured images, linking featured images, and floating those featured images right

Observe in the above case that the tab order goes to the featured image first, then the title, which is a tab order that doesn't match the dom order.

Potential solutions:

* Move the featured image location in the DOM when toggling float right
* Have the link toggle affect the ENTIRE list item/row as a single link instead of one for title, one for featured image
* Disable/gray the featured image link toggle when floated right. This can potentially be paired with help text explaining why it's grayed.

**Comment by LukaszJaro** [comment]
Just adding this as it's related with incorrect tab order, hopefully shared solution can be found https://github.com/WordPress/gutenberg/issues/38537

**Comment by carolinan** [comment]
The two blocks have different markup. But there needs to be a discussion about not moving elements with CSS only.

**Comment by jasmussen** [comment]
Coming back to this one, it seems to be an issue not just with the featured image block, but indeed with _any block that can be linked and floated_. I.e. if a block can be linked, and floated rigth, then the tab-order will go to what's in the DOM first, even if visually it isn't in the right place.

Because this seems an editorial responsibility, I think the best we could theoretically do is show a _warning notice_ in the inspector which appears if a block is linked and floated right. But since this is not very trivial to do at all, given the many permutations of those two properties you can have, I'm going to close this one as is. 

If someone comes around with a great idea, we can reopen, or open a new issue.
