### ISSUE TITLE
React 18 support in React Native

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#40695]
# Description

[React 18](https://reactjs.org/blog/2022/03/29/react-v18.html) is not supported yet by React Native, however, the web version might use it soon. The purpose of this issue is mainly to collect information around this topic and open discussion about the better way to proceed.

## Option 1 - Use React 18 in current RN version
The new React version comes with a React 17 mode in case the new concurrent rendered is not used ([reference](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis)). This feature might allow us to use React 18 with the current React Native version.

In any case, the new APIs won't be available so we'd need to provide a mechanism to identify if these APIs are used in the code shared between platforms. This most likely could be achieved using unit tests and mocking the new APIs so they raise exceptions when they are used.

**As a first step to validate this approach, we would need to upgrade React to version 18, and perform a test on the app to identify potential breakages.**

## Option 2 - Have two React versions
The idea would be to support both React versions 17 and 18 until React Native provides support for React 18. Therefore, each platform will use a different React version:
- **Web version:** React 18
- **Native version:** React 17

**In order to accomplish this approach, we would need to explore how to have both versions in the Gutenberg repository.**

**Comment by fluiddot** [comment]
This issue will be addressed when React Native version is upgraded to 0.68 ([reference](https://reactnative.dev/blog/2022/06/21/version-069)).

**Comment by geriux** [comment]
FYI we are [currently working](https://github.com/WordPress/gutenberg/pull/43485) on the React Native upgrade that adds support for React 18. We will need to coordinate with the web team to align with these changes.

**Comment by fluiddot** [comment]
Closing this issue as React 18 support was incorporated in [this PR](https://github.com/WordPress/gutenberg/pull/45235).
