### ISSUE TITLE
Gutenburg plugin breaks buttons url entry space for GenerateBlocks Button Block

### ISSUE THREAD

**Issue by jhanten** [WordPress/gutenberg#40693]
### Description

When using GenerateBlocks Version 1.4.2 and Gutenberg Version 13.1.0 are activated together the generate button block url area seems to become read only and inaccessible.

### Step-by-step reproduction instructions

1. Fresh install of WordPress with GenerateBlocks 1.4.2 and Gutenberg 13.1.0.
2. Add a Page
3. Add a GenerateBlocks Button block
4. No matter what you do you can't add a URL, but can type in the button text area.
5. Disable the Gutenberg plugin
6. You can then change the URL in the button block.

### Screenshots, screen recording, code snippet

<img width="431" alt="Screen Shot 2022-04-28 at 11 46 10 AM" src="https://user-images.githubusercontent.com/7514905/165792684-bd583a96-6301-41f2-a880-145e5f60bd44.png">

### Environment info

WordPress 5.9.3
Gutenberg 13.1.0
GenerateBlocks 1.4.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by adamwoodnz** [comment]
Hi I've just tested this with

Wordpress 6.0
Gutenberg 13.3.0
GenerateBlocks 1.4.3

I'm unable to reproduce with these versions so perhaps a recent update has fixed the issue. Could you try upgrading?

![Screen Shot 2022-05-30 at 2 52 09 PM](https://user-images.githubusercontent.com/1017872/170908817-ab5615cd-d867-4e4c-865a-e5108fb8afc8.png)

Please close unless the issue persists 🙏
