### ISSUE TITLE
Global Styles: Typography > Text > Font Size animates when appearance is selected.

### ISSUE THREAD

**Issue by costdev** [WordPress/gutenberg#40708]
### Description

Originally reported on [Trac 55626](https://core.trac.wordpress.org/ticket/55626).

There is a minor CSS bug caused by the dynamic width set on the Font size button within the Typography -> Styles section.

Suggested fix from @igorradovanov: Switch from percentage width to fixed-width (like vw or px) resolves the issue.

### Step-by-step reproduction instructions

1. Go to Styles.
2. Typography -> Text.
3. Change the Appearance from the dropdown.
4. The active font size will jump on the screen from right to left and back.

### Screenshots, screen recording, code snippet

(from @igorradovanov)
Before suggested fix: https://www.dropbox.com/s/5pwvsbn73askodt/Animation.gif?dl=0
After the suggested fix: https://www.dropbox.com/s/dgfjut05t7wq95i/Animation-2.gif?dl=0

### Environment info

(costdev):
I have tested this on:
- WordPress 5.9, 5.9.1, 5.9.2, 5.9.3, 6.0-trunk.
- Gutenberg: With and without 13.1.0 activated.
- Browser: Chrome 100.0.4896.127
- Device: Desktop with Windows 10
- Environment: WSL2 with Apache

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by akasunil** [comment]
Hello Team,

I have fixed the issue in PR [41271](https://github.com/WordPress/gutenberg/pull/41271). Please review it.

Thanks.

**Comment by youknowriad** [comment]
Looks like this was fixed. Thanks
