### ISSUE TITLE
Documentation: Reference: Attributes code samples should show save callbacks

### ISSUE THREAD

**Issue by Shelob9** [WordPress/gutenberg#4071]
The reference page for attributes shows how to register attributes so they are de-serialized from the saved HTML. The examples do not show the corresponding save() callbacks making it harder to understand the concept.
https://wordpress.org/gutenberg/handbook/reference/attributes/

For instance the first example `Example: Extract the src attribute from an image found in the block’s markup.` shows how to extract from a saved image, but doesn't show how to save an image. That's actually how it's done here: https://wordpress.org/gutenberg/handbook/blocks/introducing-attributes-and-editable-fields/ and that is much better at illustrating the relationship between saving and using attributes.

**Comment by mtias** [comment]
Combining with #4070.
