### ISSUE TITLE
Add new block overlaps existing blocks

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#40738]
### Description

I started noticing this when I added a spacer with VW units, but now I'm noticing it regardless even on the default install Sample Page with no plugins other than Gutenberg installed.  The + icon to add a new block overlaps whatever block is before it.  Seems to happen if you click just below a block.  

### Step-by-step reproduction instructions

Better to see if you watch the video.  Basically open a page with content, click just below a block (paragraph for example), then see the + icon to add a new block overlap the previous block.

### Screenshots, screen recording, code snippet

Here's a quick video > https://soapbox.wistia.com/videos/3fXO3lIsnL

### Environment info

- WP 5.9.3
- Gutenberg 13.1.0
- MacOC
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by trenzterra** [comment]
I have this issue too and it's bugging me to no end.

**Comment by talldan** [comment]
I see this was reported in the calypso repo, and https://github.com/WordPress/gutenberg/pull/40441 was highlighted as potentially where this was introduced.

I managed to reproduce this in the Gutenberg demo post, it seems to happen more reliably with content lower down in the post.

**Comment by youknowriad** [comment]
I've opened #40919 which solves the issue in my testing but I'd appreciate help confirming that.
