### ISSUE TITLE
enqueuing a block via block.json's `editorScript` property doesn't work in a theme

### ISSUE THREAD

**Issue by jakeparis** [WordPress/gutenberg#40744]
### Description

In a theme I'm building, I am attempting to use the `editorScript` key in `block.json` to automatically enqueue my block's assets. 

However, that is resulting in messed up asset urls like: _https://example.loc/wp-content/plugins/shared/httpd/htdocs/wp-content/themes/jmc/build/blocks/myblock/index.js_, where the script _path_ is concatenated after the plugins url. 

After some investigation, it seems the problem is that `register_block_type()` function uses `register_block_script_handle()`, which, in [`wp-includes/blocks.php:112`](https://core.trac.wordpress.org/browser/tags/5.9/src/wp-includes/blocks.php#L112) is calling `plugins_url( $script_path, $metadata['file'] );` 

Is there really no way to use this method to queue up blocks in a theme based on a block.json?

### Step-by-step reproduction instructions

Here's my block.json.

**block.json**
```
{
  ...
	"editorScript": "file:./index.js",
	"editorStyle": "file:./index.css",
	"viewScript": "file:./public.js",
	"style": "file:./public.css"
 }
```

I'm loading all the block.json files in a loop like so:

**registration.php**
```php
foreach ( glob( get_stylesheet_directory() . "/build/blocks/*/block.json" ) as $file ) {
    register_block_type( $file );
}
```

My `src` directory is structured like so:
```
themedir
| - src
| - | - blocks
| - | - | - jake
| - | - | - | - block.json
| - | - | - | - index.js
| - | - | - | - index.scss
                 ...
| - build
| - | - blocks
| - | - | - jake
| - | - | - | - block.json
| - | - | - | - index.js
| - | - | - | - index.css
                 ...
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
This is going to be possible to register blocks a the theme in a way you presented as of WordPress 6.0. See related commit https://core.trac.wordpress.org/changeset/53091 and PR https://github.com/WordPress/wordpress-develop/pull/2494 for full context. @fabiankaegy might provide you an example of a useful filter you can use if you need it earlier.

**Comment by timsinc** [comment]
@gziolo It appears that this does not work in 6.0 if a child theme is activated. Is that the intended behavior?

**Comment by land0r** [comment]
@gziolo in child theme it still doesn't work. Can you reopen the issue or create a new one?

**Comment by gziolo** [comment]
The functionality was added directly to WordPress core with https://github.com/WordPress/wordpress-develop/pull/2494 so it would be best to open a Trac ticket to address that issue. Previous Trac tickets:
- https://core.trac.wordpress.org/ticket/54647
- https://core.trac.wordpress.org/ticket/55513
