### ISSUE TITLE
Comments Query Loop: SQL error for post with no comments

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#40758]
### Description

With a certain comments pagination setting, the Comments Query Loop block produces an SQL error when viewing a post with no comments:

> **WordPress database error:** [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-50,50' at line 6]
> `SELECT SQL_CALC_FOUND_ROWS wp_comments.comment_ID FROM wp_comments WHERE ( ( comment_approved = '1' ) OR ( user_id = 1 AND comment_approved = '0' ) ) AND comment_post_ID = 264 AND comment_parent = 0 ORDER BY wp_comments.comment_date_gmt ASC, wp_comments.comment_ID ASC LIMIT -50,50`

### Step-by-step reproduction instructions

1. Go to `wp-admin/options-discussion.php`
2. In the "Other comments setting" section, enable (and set) "Break comments into pages with 50 top level comments per page and the last page displayed by default":
![Bildschirmfoto 2022-05-02 um 14 08 01](https://user-images.githubusercontent.com/96308/166231224-be836851-4e04-4672-91bd-aab99a7ad495.png)
3. In the Site Editor, edit the "Single post" template, and insert the Comments Query Loop block.
4. Create a new post, publish, and view it.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ockham** [comment]
The syntax error is the negative integer in `LIMIT -50,50` — that doesn’t seem to be valid SQL. And that’s coming from pagination:

https://github.com/WordPress/gutenberg/blob/d0b600f44406d48fa8950fb3d519630aaf6bfea6/lib/compat/wordpress-6.0/blocks.php#L178-L180

The "and the last page displayed by default" setting is what sets `$default_page` to `"newest"`, which makes the above clause kick in. Since there are no comments, there are also no pages (`max_num_pages`), so `$comment_args['paged']` is set to `0`.

But IIUC, `paged` needs to be `>= 1` ([docs](https://developer.wordpress.org/reference/classes/wp_comment_query/__construct/#parameters)).

**Comment by ockham** [comment]
Note that this code has already been backported, so we'll also have to fix it in Core: https://github.com/WordPress/wordpress-develop/blob/e0837a8b18f2cee14af38051be12e6ebc5bacf2a/src/wp-includes/blocks.php#L1327-L1329

**Comment by ockham** [comment]
We already have some unit test coverage for the relevant function (`build_comment_query_vars_from_block`), so we should add coverage for this situation (to make sure `paged === 1` rather than `0`).

**Comment by luisherranz** [comment]
I was able to reproduce the problem 👍
