### ISSUE TITLE
Allow quickly opening "Preview in new tab..." by using modifier keys to change button behavior

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#40756]
## What problem does this address?

One of the most common actions when trying to preview your content is to click the "Preview in new tab..." button. This currently takes two clicks to do. That isn't bad but it would be nice to get some way of reducing that to just one click. 

## What is your proposed solution?

As a power user feature, it would be cool to introduce the idea of modifier keys. Having the ability to click `CMD / CTRL` whilst clicking on the button could immediately open the preview in a new tab. Allowing you to skip the dropdown.

**Comment by ramonjd** [comment]
This is something that's irked me as well. 😄 It would be very handy just to preview work in a new browser tab and let the user manually control viewport widths there.

So I took a quick look at the components: [DevicePreview](https://github.com/WordPress/gutenberg/blob/4834fad30e39e47d71a93e2e08d31b3b856711e1/packages/edit-post/src/components/device-preview/index.js) ➡️  [PreviewOptions](https://github.com/WordPress/gutenberg/blob/9df736c678b2e8ef00c355e6cc9fb8092fe25484/packages/block-editor/src/components/preview-options/index.js) ➡️ [PostPreviewButton](https://github.com/WordPress/gutenberg/blob/4834fad30e39e47d71a93e2e08d31b3b856711e1/packages/edit-post/src/components/device-preview/index.js)

```jsx
<DevicePreview>
    { /* DropDownMenu component */ }
    <PreviewOptions> 
         { /* the preview in new tab button */ }
        <PostPreviewButton />
    </PreviewOptions>
</DevicePreview>
```


There's a lot going on in PostPreviewButton, and it require access to the editor store. PreviewOptions, on the other hand, is a stand alone component.

The challenge will be to prevent the DropDownMenu panel opening up while reproducing the behaviour of the PostPreviewButton.

I tried a couple of things: it's possible to capture clicks and keyboard events on the DropDownMenu's button. Hiding the DropDownMenu panel is difficult as the event is bubbling up, and the callbacks are fired _after_ the [panel toggle has taken place](https://github.com/WordPress/gutenberg/blob/1620d517274476321fdbc65fc1eeca0ef985ad39/packages/components/src/dropdown-menu/index.js#L103).

Even if we ignore the panel opening up, we need to reproduce the behaviour of PostPreviewButton, or inject the component at the top level somewhere.

I also tried replacing the entire DropDownMenu with the PostPreviewButton component in DevicePreview if the Ctrl/Cmd key is activated, but it's pretty janky.

![2022-05-05 11 48 23](https://user-images.githubusercontent.com/6458278/166853093-9b72623e-0161-4338-be98-804b314c108a.gif)

My 2c is that I think it's something worth pursuing, but we might need an alternative UI and/or UX proposition, possibly with separate controls at the top level for devices and a general preview button.

<img width="526" alt="Screen Shot 2022-05-05 at 11 55 04 am" src="https://user-images.githubusercontent.com/6458278/166853464-15e3bac1-d3af-4d54-b179-0c910db85056.png">

**Comment by fabiankaegy** [comment]
With the restructured device preview / external preview buttons in Gutenberg 15.7 this no longer is an issue :)
