### ISSUE TITLE
Consider overlap tool for text and images

### ISSUE THREAD

**Issue by beafialho** [WordPress/gutenberg#40762]
## What problem does this address?

Overlapping elements is an interesting and recurring design choice that adds an extra layer of refinement not only to theme designs and patterns, but it is also used across many websites. I believe that currently there isn't such feature in Gutenberg, unless we use custom code or plugins.

## What is your proposed solution?

It would be great if there was an "overlap" option we could set to blocks such as Images, Post Featured Image, Galleries, Cover and Query Blocks.

The Twenty Twenty One default theme actually included the option that I have in mind to its patterns:

<img width="279" alt="Captura de ecrã 2022-05-02, às 16 19 31" src="https://user-images.githubusercontent.com/65220155/166259947-3a55def1-67c5-4c22-a8ca-0e785258340d.png">

Here are a few ideas we've tried while iterating and found this could be a really useful tool:

<img width="639" alt="Captura de ecrã 2022-05-02, às 15 26 49" src="https://user-images.githubusercontent.com/65220155/166252474-134b1e7e-59b5-4bea-a85a-d60cdf031f84.png">
<img width="631" alt="Captura de ecrã 2022-05-02, às 15 27 03" src="https://user-images.githubusercontent.com/65220155/166252527-4529cc5e-4160-4025-b1df-0f89c51f0ac9.png">
<img width="1277" alt="Captura de ecrã 2022-05-02, às 15 27 28" src="https://user-images.githubusercontent.com/65220155/166252535-d9dceb63-9797-41d8-9bc5-5782a3cb06ba.png">
<img width="1430" alt="Captura de ecrã 2022-05-02, às 15 28 21" src="https://user-images.githubusercontent.com/65220155/166252558-dcfb8f77-1987-415c-98c3-af0aadc193db.png">
<img width="1273" alt="Captura de ecrã 2022-05-02, às 15 55 19" src="https://user-images.githubusercontent.com/65220155/166256021-a76a25f9-fb87-455d-b178-244cbe7e1ee0.png">

**Comment by carolinan** [comment]
Is this solved with the introduction of negative margins?

**Comment by beafialho** [comment]
I believe we can close it, yes!
