### ISSUE TITLE
Feedback on sibling inserter experience in List V2

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40769]
## What problem does this address?

This came up as part of the [fourteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/04/28/fse-program-testing-call-14-rallying-recipe-reviewers/#comment-2467):

>If in a list block, it is confusing how to add a new block because the sibling inserter + icon is there

Specifically, the sibling inserter seems to look like the quick inserter and, at a glance, it seems like you could use it in order to add a new block below the list block. 

https://user-images.githubusercontent.com/26996883/166332301-133c7164-5dd5-40ff-9022-f8f1265d8935.mov

## What is your proposed solution?

This ties into a larger conversation around the + button in general that can be seen here https://github.com/WordPress/gutenberg/issues/26404 but I wanted to open a specific issue on this experience since more blocks are adding support for child blocks and we'll likely see this specific point of confusion increase. 

One possible solution is noted on the issue above around: "Explore alternates solution for triggering in-between inserter; Sometimes its too hard to trigger, and sometimes its too easy to trigger."

**Comment by courtneyr-dev** [comment]
It becomes more confusing when the list block is the last thing in the post editor and hitting enter 2x to get out of the list doesn't work like other word processors. 

https://videopress.com/v/4rbvJtcS?at=2545

**Comment by annezazu** [comment]
For the latter point @courtneyr-dev mentions, this also came up with [Justin's review on WP Tavern](https://wptavern.com/fse-outreach-14-building-recipe-posts-with-lists-and-quotes):

>It also seems impossible to escape the List and into a new Paragraph block. In the past, this could be accomplished by hitting the Enter key twice while on the final list item. That action now creates a nested list.

This seems like table-stakes at this point. cc @ntsekouras since you seem to be helping in this area <3 as a head up.

**Comment by annezazu** [comment]
More feedback on this current experience from a [prior call for testing that just came in](https://make.wordpress.org/test/2022/04/28/fse-program-testing-call-14-rallying-recipe-reviewers/#comment-2595):

>I really wanted the list block to indent with tab. I didn’t notice the + sibling inserter until I read about it in the instructions.

I understand though that there's context for why tab works the way it does but wanted to note how the + sibling inserter was hard to grasp in light of that: https://github.com/WordPress/gutenberg/issues/7051

**Comment by ellatrix** [comment]
> It becomes more confusing when the list block is the last thing in the post editor and hitting enter 2x to get out of the list doesn't work like other word processors.

@courtneyr-dev This works. You can press Enter twice to exit the list block and inter a paragraph after it.

**Comment by ellatrix** [comment]
We removed this inserter in #43954.
