### ISSUE TITLE
Quote V2: show citation block at all times

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40768]
## What problem does this address?

Currently, when using the v2 of the quote block, if you add in child blocks to the quote (ie like a list block), the citation isn't visible until you select the overall quote block once more. Here's a quick video:

https://user-images.githubusercontent.com/26996883/166330440-0c79544b-89bd-4dc6-8c4b-49ff8f2e7f27.mov

## What is your proposed solution?

Show the citation block at all times.

**Comment by annezazu** [comment]
cc @oandregal  based on your work with the quote block v2. Seems there's talk of having the citation block as a separate inner block but that hasn't yet been pursued so noting this for now :)

**Comment by ellatrix** [comment]
@annezazu In my testing the it works as expected now. Feel free to reopen if I'm mistaken.

<img width="358" alt="Screenshot 2022-07-14 at 15 16 24" src="https://user-images.githubusercontent.com/4710635/178991249-e75bfe4d-dbb0-4641-a637-ef430ea163f8.png">

**Comment by annezazu** [comment]
Woohoo! I just did a quick test and can confirm it's now working too. Leaving closed.
