### ISSUE TITLE
Feedback on return keyboard behavior for List V2

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40767]
## What problem does this address?

As part of the [fourteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/04/28/fse-program-testing-call-14-rallying-recipe-reviewers/), it was noted in a group call for testing that entering twice would be expected to outdent rather than indent.

## What is your proposed solution?

Consider having entering twice match what one experiences in other word processors (like google docs). In both videos below, I'm hitting the return keyboard key. 

Block Editor:

https://user-images.githubusercontent.com/26996883/166315661-dee8691d-000e-45ec-9209-8859da17ebe5.mov

Google doc:

https://user-images.githubusercontent.com/26996883/166315873-8331b0ee-9c96-4443-8820-f22685ce579f.mov

**Comment by ntsekouras** [comment]
Resolved by this one: https://github.com/WordPress/gutenberg/pull/40939. Small naming mix up 😄
