### ISSUE TITLE
@wordpress/scripts requires block.json to live inside 'src' folder

### ISSUE THREAD

**Issue by alexdelgado** [WordPress/gutenberg#40771]
### Description

It's not entirely clear that if you're using `block.json` to create a Gutenberg block with `wp-scripts` that the `block.json` file MUST live inside the `src` folder as [defined here](https://github.com/WordPress/gutenberg/blob/ac5dd04c289977baf2a2fe37e8a9ed10f4e67b36/packages/scripts/utils/config.js#L200) in order for multiple and/or non-default entry points to be picked up (i.e. editorScript, viewScript).

The documentation says: "When using the start or build commands, the source code directory ( the default is ./src) and its subdirectories are scanned for the existence of block.json files. If one or more are found, they are treated a entry points and will be output into corresponding folders in the build directory." So it would stand to reason that `block.json` could (and should) live outside the `src` folder.

If you look at the [Gutenberg Examples repo](https://github.com/WordPress/gutenberg-examples) they have several instances (e.g. [01-basic-esnext](https://github.com/WordPress/gutenberg-examples/tree/trunk/01-basic-esnext), [03-editable-esnext](https://github.com/WordPress/gutenberg-examples/tree/trunk/03-editable-esnext), [04-controls-esnext](https://github.com/WordPress/gutenberg-examples/tree/trunk/04-controls-esnext)) where block.json lives outside of the `src` folder

**Desired Outcome**
The `block.json` file should be able to live above/outside the `src` folder so that the `src` file actually contains just "source" files. 

### Step-by-step reproduction instructions

# Using Gutenberg Examples

## When not using `src/index.js` as entry point
1. Clone [Gutenberg Examples](https://github.com/WordPress/gutenberg-examples/blob/trunk/01-basic-esnext/package.json)
2. Rename `src/index.js` to `src/app.js`
3. Run `wp-scripts build`
4. Validate that the `build` folder doesn't have `app.js`

## When adding additional entry point
1. Clone [Gutenberg Examples](https://github.com/WordPress/gutenberg-examples/blob/trunk/01-basic-esnext/package.json)
2. Run touch `src/view.js`
3. Add  `"viewScript": "file./src/view.js"` to `block.json`
4. Run `wp-scripts build`
5. Validate that the `build` folder doesn't have `view.js`

# Using any Gutenberg Block
1. Move `block.json` outside of `src` folder
2. Run `wp-scripts build`
3. Validate `build` folder doesn't update

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ryanwelcher** [comment]
Historically, the `src` directory was intended to contain all of the block files at its root with the block.json defining the files that need to be generated i.e `index.js`,`index.css`,`style-index.css` etc.  A lot of work has been done to allow developers to create multiple blocks with a single build process without needing to create a custom `webpack.config.js`. This is done by looking in the `src` directory and any subdirectory containing a `block.json` file is treated as a separate block and the existence of that file is the marker that triggers this functionality. 

It is completely possible to have the `block.json` file outside of the `src` directory but the trade-off is having to manage the entry points yourself, which we've tried to avoid for the sake of simplicity and having the package "just work"

It is also possible to customize the name of the directory that is being scanned using the ---webpack-src-dir flag as we do in the examples repo h[ere](https://github.com/WordPress/gutenberg-examples/blob/trunk/package.json#L27)

**Comment by alexdelgado** [comment]
Thanks for the explanation @ryanwelcher! If you were "to create multiple blocks with a single build process without needing to create a custom `webpack.config.js`," what would that look like from a file directory and command-line perspective?

**Comment by ryanwelcher** [comment]
@alexdelgado here is a basic example I set up last week for a live stream I was doing - https://github.com/ryanwelcher/twitch/tree/trunk/plugins/native-multiple-blocks.

Please note that I have customized the `src` directory using the flag I mentioned above but if you remove that flag and rename the 'blocks' directory back to `src`, it will work as expected.

If you're interested, [here is the accompanying video of the stream ](https://www.youtube.com/watch?v=SjaBjNmewPQ)( sorry for the shameless self-promotion here )

**Comment by gziolo** [comment]
Is there anything we could add to the documentation to make it more obvious that it's possible to customize the directory where blocks live when using `@wordpress/scripts`? I see `--webpack-src-dir` flag referenced in the README file of the package in a few places.

**Comment by karstengresch** [comment]
Genereally this works as expected, but I wonder if an n-depth subdirectories structure could be supported (or at least one).

Following the tutorial from [https://www.youtube.com/watch?v=O_4loYiEcbg](https://www.youtube.com/watch?v=O_4loYiEcbg),  I easily could setup a 

```
/src/
--/block_a
--/block_b
```

structure, but I actually would love to use 

```
/src/
--/blocks/
----/block_a
----/block_b
```
 
Would that be feasible at all with an auto-scanning approach? 

Thanks anyway, there's so much great progress everywhere 🥇
