### ISSUE TITLE
Mobile inserter flow and iterations to the top bar

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4077]
Right now the inserter flow and appearance is like this on mobile and it's not great:

![issues-inserter](https://user-images.githubusercontent.com/253067/34152484-a6688a88-e4a6-11e7-96bc-12f0278fdcc8.png)

I am proposing an iteration to the inserter and flow that sees it adapt to the mobile experience.

![inserter-flow-02](https://user-images.githubusercontent.com/253067/34204464-99fd715c-e576-11e7-8d80-4b59f3724aae.png)

A few points to bring out here:

- The '+' inserting icon will on mobile only appear in the top bar. This will stay fixed to the top in order to allow this to be visible at all times. These top bar changes shown here are essential to this new flow. See 
- When clicking the '+' a modal will pop up (similar to now) with some visual changes.
- The modal will have a white header and in it a shortened (with '...') title of the post being written. This hooks it back to the original content.
- The inserter will be 3 columns (issue for desktop in #4080 ).
- The inserter will have center titles with lines to separate.
- Search highlights the input field to make sure the keyboard is connected to the focus area.

You can see the flow in the outlined mock.

**Comment by hedgefield** [comment]
Could you also expand on the changes to the toolbar that you mentioned in #4517 and #4518? I'm only seeing changes to the inserter outlined in this issue :)

**Comment by karmatosed** [comment]
Yes we're fixing the toolbar to the top which avoids a lot of those issues. I think it is important to get in these changes and iterate from that point.
