### ISSUE TITLE
Ability to exclude the blocks from Post Editor but include them in the Template Editor

### ISSUE THREAD

**Issue by dinhtungdu** [WordPress/gutenberg#40780]
## What problem does this address?

In https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/6342, the Mini Cart block is excluded from the Post Editor and included in other screens. But if the store admins edit a page template using the edit link in the Templates Panel (which opens a Template Editor), the popup editor doesn't include the Mini Cart block because the screen is still the post edit screen.

I tried using the editor context with the `allowed_block_types_all` filter to register blocks conditionally but it doesn't work with the embedded Template Editor, the filter is only fired for the initial load when the admins edit a post/page.

## What is your proposed solution?

A way to filter the blocks list for the embed Template Editor inside Post Editor.

**Comment by gziolo** [comment]
@dinhtungdu, a similar issue #46900 exists that proposes an option to register a block only in a specific editor. Is there anything unique in this proposal, or can we close it and add your use case and findings about `allowed_block_types_all` as a comment?

Edit: I see this one was filed earlier, but the other one gained more feedback so we would have to at least connect those two items together.

**Comment by dinhtungdu** [comment]
> Is there anything unique in this proposal, or can we close it and add your use case and findings about `allowed_block_types_all` as a comment?

Make sense, closing in favor of #46900
