### ISSUE TITLE
Settings on mobile iteration

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4078]
The settings panel on mobile needs some work and this is a proposal to iterate there. Right now we have the following:

![settings mobile](https://user-images.githubusercontent.com/253067/34152803-be4949de-e4a7-11e7-894b-37872f3990d3.png)

The suggestion is for:

![settingsiterations](https://user-images.githubusercontent.com/253067/34153045-8d86a91c-e4a8-11e7-8fbd-a6989d270c2e.png)

What this does is bring it with #4077 and add in the header from that showing the title and being white. It also assumes the fixed header and inserter changes.

**Comment by hedgefield** [comment]
Yeah seems fine. There's not a lot to say about this small change :) showing the post title is a nice reminder of what you're working on, and the consistency with the inserter is cool.
