### ISSUE TITLE
Template Part replacement modal – make results searchable

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40791]
When there are many options in the replace modal it can be difficult to find a specific template part you have in mind. This is already an issue in Twenty Twenty-Two:

https://user-images.githubusercontent.com/846565/166451322-69654855-b8eb-4c8f-8039-a130201552e8.mp4

Making the list searchable can help ease this pain point.

https://user-images.githubusercontent.com/846565/166452768-617fd330-6502-4b1f-af4d-bf263a59b90d.mp4

**Comment by shaunandrews** [comment]
If you know the name of the template part, this might help. It would be nice to only show the search input if there are more than a few template parts.

Maybe, instead of a search box there were display options to show template parts in different views. For example, instead of just a stacked display of large previews you could switch to a grid of thumbnails, or a simple list with a focus on the label.

**Comment by jameskoster** [comment]
Good points. The display options are posed in https://github.com/WordPress/gutenberg/issues/39308, but still need some design exploration.

**Comment by Mamaduka** [comment]
@jameskoster, is anyone working on this issue?

**Comment by jameskoster** [comment]
@Mamaduka not that I am aware of. If you're thinking about picking it up, it may be worth taking a look at https://github.com/WordPress/gutenberg/issues/39308 first (https://github.com/WordPress/gutenberg/issues/39308#issuecomment-1133086932 specifically), for an idea of the overall direction for these pattern modals. Just in case that informs any implementation details here :)

**Comment by Mamaduka** [comment]
Thanks, I will do.

**Comment by Mamaduka** [comment]
@jameskoster, I was wondering if moving template part replacements into Block actions dropdown would make this modal obsolete.

P.S. Do we have mockups of how replacements should look in the block actions dropdown - https://github.com/WordPress/gutenberg/issues/40208#issuecomment-1180999591?

**Comment by jameskoster** [comment]
Because we can't account for the appearance or quantity of headers I still think the modal makes sense. 

Perhaps something like this could work:

<img width="434" alt="Screenshot 2022-07-13 at 12 09 24" src="https://user-images.githubusercontent.com/846565/178720191-874ad738-4bab-4f31-8691-d0075a48e09c.png">

**Comment by Mamaduka** [comment]
@jameskoster, do we want to hide SearchComponent if there're fewer than X items (#42337)?

**Comment by jameskoster** [comment]
Good question. I don't know if it's so important to hide the search component here... if the previews happen to be very tall, you may still want to search to avoid scrolling, even if there are only a few options.
