### ISSUE TITLE
Make inserter have 3 not 2 columns

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4080]
A 3 column inserter both works better for mobile and also desktop:

![inserter-nonmobile](https://user-images.githubusercontent.com/253067/34153227-33016f76-e4a9-11e7-99e1-94dc5ac4b2dc.png)

This uses up space and also with this change we should bring in left aligned titles with a separator.

**Comment by gziolo** [comment]
Related #3940. @karmatosed you might to close my issue and add the part about mobile glitches in the header of this popover.

**Comment by karmatosed** [comment]
@gziolo 👍 thanks, closing.

**Comment by karmatosed** [comment]
Noting after discussion in PR, we are making the title centre aligned again.

**Comment by jwold** [comment]
I like the direction of this. The three column has a bit more balance to it. Only concern would be character length for titles in English/other languages. Would we just have the text bump down to two lines?

**Comment by youknowriad** [comment]
closed by #4095
