### ISSUE TITLE
Not possible to create single/singular template in site editor

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#40814]
### Description

Maybe it is the wanted behavior, or I do something wrong, but I wonder why it is not possible to create a template for the single view of posts (single/singular template) directly from the site editor. I searched and found that it was possible to add the `single-post` template, but that was removed in https://github.com/WordPress/gutenberg/pull/29668 (the `single-post` entry is still part of the templates array in the `edit-site.js`), and it seems that there was no replacement added.

### Step-by-step reproduction instructions

1. Activate a block template and, if it has a single/singular template file, remove that from the `templates` folder.
2. Go to the templates list in the site editor and try to add a single/singular template

### Environment info

WordPress 6 RC1, without Gutenberg plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by paaljoachim** [comment]
Hey @florianbrinkmann 

This issue might be associated to what you are talking about: 
Site Editor: Add New - Custom/General template
https://github.com/WordPress/gutenberg/issues/36860

**Comment by florianbrinkmann** [comment]
Hi @paaljoachim,

thanks for the link! As far as I understand, your ticket is about the creation of custom page/post templates? I mean the template that is used for single posts by default (singular.php or single.php in Classic Themes).

**Comment by paaljoachim** [comment]
Gotcha. The issue I made is mostly about creating custom templates, but it also crosses lightly into the single post default templates.
