### ISSUE TITLE
Navigation Block: "Start empty" produces "Failed to create Navigation Menu" error.

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40820]
Here's my experience inserting a Navigation block on a fresh install with no menus present:

https://user-images.githubusercontent.com/846565/166692554-245c811f-4a41-4d52-a293-ba9d4d4433cd.mp4

**Comment by scruffian** [comment]
I can't replicate this. What versions of Gutenberg and WordPress are you running?

**Comment by jameskoster** [comment]
Latest stable version of WP, latest Gutenberg trunk. It doesn't seem to be happening now though, so perhaps we can close this.

**Comment by andybrice** [comment]
I am having this same issue with WordPress 6.0.
And trying to select an existing menu crashes the entire virtual machine and requires a reboot.
It started happened when I installed the _Blockbase_ theme, and has persisted since switching back to _Twenty Twenty Two_.

**Comment by andybrice** [comment]
I eventually resolved this issue by using phpmyadmin to remove all templates, template parts, menus, and theme customisation from the wp_posts table in the database.
