### ISSUE TITLE
Multiple Search blocks on same page with icon causing duplicate id with svg icon

### ISSUE THREAD

**Issue by LukaszJaro** [WordPress/gutenberg#40823]
### Description

Adding multiple search blocks with icon displaying on same page causes duplicate ID.

![image](https://user-images.githubusercontent.com/10998875/166723146-b68849b6-ee2e-46b9-8002-4cd807a15c6f.png)

`<svg id="search-icon" class="search-icon" viewBox="0 0 24 24" width="24" height="24">`

### Step-by-step reproduction instructions

1. Add search block from inserter
2. Select use button with icon from search block toolbar
3. Duplicate said block
4. Save and view on front-end
5. Inspect search icon with dev tools or run Axe dev tools

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/10998875/166723146-b68849b6-ee2e-46b9-8002-4cd807a15c6f.png)

### Environment info

WP 5.9.3
Gutenberg 13.1
Twenty Twenty two theme
Chrome browser on windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by amustaque97** [comment]
I'm able to reproduce the issue. Indeed I can see `id` attribute value as `search-icon` for multiple search blocks. As per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id), `id` must be unique in the whole document.  

Thank you for reporting 👏🏻

**Comment by amustaque97** [comment]
After looking into the code I found issue is here 
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/search/index.php#L89


My 2 cents would be to either remove `id="search-icon"` or append some random string/number at the end of id value. For example: `id="search-icon-ABC"` and `id="search-icon-DEF"`.

**Comment by alexstine** [comment]
@amustaque97 Maybe you could use the index starting from 0?

* search-icon-0
* search-icon-1
* search-icon-2
This will ensure the id attribute is always unique. Other than that, you might be able to get away with using the wp_rand() function.
https://developer.wordpress.org/reference/functions/wp_rand/

One could make the argument that the max integer would not be enough but I think I would worry more about performance concerns with having that many search forms.

**Comment by amustaque97** [comment]
@alexstine, thank you so much for your input. I would love to understand more about performance concerns. Request you to please share some light on it.

**Comment by alexstine** [comment]
@amustaque97 My point was this.

```
wp_rand( 0, 999 );
```

This usage is fine. What I am getting at is how would performance be effected if someone actually added 999 search blocks to one page/post? Seems like performance would be the bigger issue here than say having 2,000 unique id attributes. It might be best to research if the search block is limited in anyway by how many times it can exist on a single page/post.

**Comment by amustaque97** [comment]
First approach is simpler and faster as compared to `wp_rand` function. Also, it doesn't depend on the max number of search blocks. I will start working on draft PR and let's keep the discussion going there if required. Thank you once again for your input.
