### ISSUE TITLE
Navigation block: Convert to links not creating a menu

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40821]
To reproduce:

* Fresh site with no menus (unsure if this is necessary)
* Insert Navigation block with Pages List block inside, select Pages List
* Click "Edit" in the toolbar to invoke the "Convert to links" Dialog
* Save

At no point am I asked to save the navigation as a menu. And even after saving, no navigation menu is created. Here's a video:

https://user-images.githubusercontent.com/846565/166702907-f7cf03b0-38c9-43b4-8022-b53d2306d927.mp4

The result is that the Navigation panel states that no menus exist.

It might be better than the menu gets created as soon as you convert to links, that way the Navigation panel could become immediately functional.

**Comment by scruffian** [comment]
I also can't replicate this one. I see this once I convert to a navigation...
<img width="289" alt="Screenshot 2022-05-05 at 13 33 44" src="https://user-images.githubusercontent.com/275961/166923837-b84bd00f-f431-4018-a7f5-4f918dd305f4.png">

**Comment by jameskoster** [comment]
Seems to be working for me now as well 🤷‍♂️
