### ISSUE TITLE
Rethink movers/trash/ellipsis on mobile

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#4084]
To the left and right of a selected or hovered block, we have some quick tools. The mover, on the left, lets you move a block up or down. The ellipsis on the right holds more advanced tools, such as a shortcut to settings or editing the HTML of a block.

On mobile, we do not have room to show these on the side of a block, and there's no hover either. Currently in master, we solved this by putting those tools inside an ellipsis menu. But this is inelegant — there are already ellipses elsewhere, and more importantly this ellipsis behaves differently than the one you see on the desktop. That's not a good interface.

Let's consider a different interface for showing these quick-tools on mobile. This is inspired by a concept by @iamthomasbishop (Thank you! 🏅 )

**Mockups**

When viewing text, you'd see this:

![mobile block unselected](https://user-images.githubusercontent.com/1204802/34155549-1499470a-e4ba-11e7-9b05-771e2145a705.png)

Tapping a block, you'd then _pop out_ the mover, a trash button, and an ellipsis button below the contents of the block itself, same as how a caption field pops out when you select an image:

![mobile block selected](https://user-images.githubusercontent.com/1204802/34155570-2c85dc84-e4ba-11e7-88cf-7b62bc18fe0f.png)

When you tap the ellipsis in that situation, you could see a modal popover instead of the flyout menu:

![mobile ellipsis pressed](https://user-images.githubusercontent.com/1204802/34155598-44b35db8-e4ba-11e7-93ff-bbeeccf46a42.png)

☝️  that last part, the modal popover, would be an optional enhancement. The key here is the mover, the trash button, and the ellipsis appear _on tapping the block_.

**Comment by karmatosed** [comment]
+1 to getting this in. It's important that we improve the experience on mobile. I like all of this 🚢 it :)
