### ISSUE TITLE
Build failure due to missing package `caniuse-lite`

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#40856]
### Description

The plugin was failing to build for me because of a missing package: `caniuse-lite`.

### Step-by-step reproduction instructions

1. `rm -rf node_modules`
2. `nvm use`
3. `npm i && npm run dev`

Consistently resulted in the following for me:

`Error: Cannot find module 'caniuse-lite/...'`

Manually installing the package (`npm i caniuse-lite`) fixed the issue for me.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by amustaque97** [comment]
Hi there, I tried twice but still not able to reproduce the error.

**Comment by jffng** [comment]
Okay, I'll close this one out unless someone else can recreate it.
