### ISSUE TITLE
Cannot add tags to post

### ISSUE THREAD

**Issue by Naoell** [WordPress/gutenberg#40850]
### Description

When trying to add a new tag, the tag disappears and won't be added.

When adding a tag the app send a XHR-request to check if the tag exists. 
If this is true, then it does a search for that tag name.
The search has "per_page" set to 20.
![image](https://user-images.githubusercontent.com/9252222/166941729-d6ffda29-c818-4a07-8cd5-1590a81a5758.png)

If there are more than 20 results and no results match the tag, the client throws the error: 
![image](https://user-images.githubusercontent.com/9252222/166941879-f5f535d4-5dae-4b1c-a215-f2a4907904a3.png)

"Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at er (editor.min.js?ver=8d4a298f55ea5a97c9e5147f9e132d82:7:59863)
    at async Promise.all (/wp-admin/index 0)"

And the tag won't be added.

### Step-by-step reproduction instructions

1. Create a new Wordpress site
2. Add the following tags:
amybug,bmybug,cmybug,aamybug,abmybug,acmybug,aaamybug,aabmybug,aacmybug,abamybug,abbmybug,abcmybug,acamybug,acbmybug,accmybug,bamybug,bbmybug,bcmybug,baamybug,babmybug,bacmybug,bbamybug,mybug
3. Create a new post, and try to add the tag "mybug"
5. Press "Publish" or "Update".
6. Refresh the page, and the tag will disappear.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/9252222/166945209-9b1645f6-f4b0-4a7e-a318-22351f41ddc2.mov

### Environment info

- Wordpress 5.9.3
- Using Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by amustaque97** [comment]
Hi @Naoell, thank you for reporting issue. I'm not able to reproduce the issue. I'm sharing my screen recording here! Let me know If I miss something. 
Thank You

https://user-images.githubusercontent.com/21127788/167002014-cb96624c-5123-44dc-8bcc-296e04fc212a.mov

**Comment by Naoell** [comment]
@amustaque97 Hi, thanks for replying.

For the issue to appear the tag must be out of bounds of the 20 search-results.
If the tag is more in use than the other tags, it will get higher up in the search results.

If you look at the XHR-request "tags?per_page=20..." request, you will see if the tag is in the search results.

Best regards. =)

**Comment by amustaque97** [comment]
> @amustaque97 Hi, thanks for replying.
> 
> For the issue to appear the tag must be out of bounds of the 20 search-results. If the tag is more in use than the other tags, it will get higher up in the search results.
> 
> If you look at the XHR-request "tags?per_page=20..." request, you will see if the tag is in the search results.
> 
> Best regards. =)

I tried again with the latest trunk branch. Still no luck. I don't see any issue. Thus not able to reproduce the error.
Attaching screenshot for reference.

<img width="1792" alt="Screenshot 2022-05-29 at 2 33 43 AM" src="https://user-images.githubusercontent.com/21127788/170842816-c3d2e634-f7a7-4c8c-baed-eba79cf27ea0.png">

**Comment by t-hamano** [comment]
I was able to reproduce it.
The detailed procedure is as follows:

- Confirm that the tags are empty.
- Create 3 posts.
- Add the following tags in the first post:
`aaamybug,aabmybug,aacmybug,abamybug,abbmybug,abcmybug,acamybug,acbmybug,accmybug,baamybug,babmybug,bacmybug,bbamybug,bbbmybug,bbcmybug,bcamybug,bcbmybug,bccmybug,caamybug,cabmybug,cacmybug,cbamybug,cbbmybug,cbcmybug,ccamybug,ccbmybug,cccmybug,mybug`
- Add the following tags to the second post:
`aaamybug,aabmybug,aacmybug,abamybug,abbmybug,abcmybug,acamybug,acbmybug,accmybug,baamybug,babmybug,bacmybug,bbamybug,bbbmybug,bbcmybug,bcamybug,bcbmybug,bccmybug,caamybug,cabmybug,cacmybug,cbamybug,cbbmybug,cbcmybug,ccamybug,ccbmybug,cccmybug`
- On the tags page, Confirm that the number of posts associated with `mybug` is lower than the other tags.
- Open the third post in the block editor and add the tag `mybug`.
- Confirm that an error is displayed in the console.
- Save the post and reload the browser, and confirm that the tag is not saved.

I think the point is to **lower the priority (number of articles related to it) of the tag** to be added.

https://user-images.githubusercontent.com/54422211/170850748-f0bdbcad-ba20-4fd0-b4b0-4bb0eb663297.mp4

**Comment by fullofcaffeine** [comment]
I've just stumbled upon this error. Seems to be an edge case and I couldn't reproduce consistently though.

**Comment by fullofcaffeine** [comment]
I've debugged this a bit further, and this exception originates in `unescapeTerm` function ([here](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/utils/terms.js#L58)). It seems that some client code is calling `unecapeTerms` and passing a `terms` argument that includes `undefined` values. While it shouldn't receive an array with `undefined` values, I think a good workaround is to make sure it handles those values. I've prepared a PR [here](https://github.com/WordPress/gutenberg/pull/43728). Let me know what you think.

**Comment by kabyanil** [comment]
I'm having the same issue. I'm on WordPress version 5.9.3.

**Comment by Mamaduka** [comment]
@kabyanil, the issue was fixed and the fix will be part of WP 6.1.

**Comment by BinarniyKot** [comment]
@Mamaduka hi, the issue is reproduced, on the version WP 6.1.1 
<img width="1500" alt="Screenshot 2023-01-25 at 23 59 23" src="https://user-images.githubusercontent.com/26786441/214701085-32b99f38-1101-48e2-a65e-c6e33879a2ed.png">

**Comment by stefanche** [comment]
Hello, I'm having the same issue on WordPress version 6.4.2

**Comment by ThinkIrreverent** [comment]
Same

**Comment by keenode** [comment]
I am on WordPress version 6.4.2 using the Gutenberg editor and am running into this issue as well. 

When trying to add an already existing tag to a post that DOES NOT appear within the autocomplete dropdown, I get the undefined error as mentioned in the initial comment from 2022. For this particular website we have many tags that contain the same string match so often times we have tags that we are trying to add that are not within the limit of 20 items returned. 
It appears that the code within editor.js attempts to create a NEW tag ( POST to /wp-json/wp/v2/tags ), but results in a 400 error (Bad Request) because a tag can already exist. 

It appears that the issue is still going on and am wondering if there is a proposed solution or somehow the fix for this regressed in a later version of WordPress.

**Comment by fcenteno** [comment]
In version 6.5.3, the error persists. Just as mentioned in the previous message, we have many tags, and we are unable to use them because we receive the same error. We have had to stay on an outdated version of WordPress. Is there any way you can help resolve this bug?

**Comment by Mamaduka** [comment]
@fcenteno, is this the same error as described in #60791?

**Comment by fcenteno** [comment]
> @fcenteno, is this the same error as described in #60791?

Yes, it is the same error. And the error started after version 6.2.4. In version 6.2.4, there was always a limit of 20 tags, but the display order started from the first written word, and this avoided the error. If there are phrases that contain one of the tags, they are displayed in alphabetical order and do not take the first written word as the first option.
Example: 

- These tags exist: music, rock music, pop music, ballad music, salsa music, radio music, play music, a music, b music
- When adding a new post and add the tag **music** the list start: 
- a music
- b music
- ballad music... and continue... 20 existing tags are displayed, but I never find the tag "music". But if I press enter to add it, I get the 400 error described in the bug.

**Comment by Mamaduka** [comment]
Thanks for the additional feedback, @fcenteno!

There's a plan to remove the search limit for tags, and based on feedback, result sorting also needs some fine-tuning.

Can you share the number of tags on the website? I would like to match it when running tests.

**Comment by fcenteno** [comment]
With pleasure. I would be delighted to help. The site has a total of 753 tags.
