### ISSUE TITLE
Shortcode block breaks when archive or category blocks used in header block

### ISSUE THREAD

**Issue by itsthex** [WordPress/gutenberg#40869]
### Description

When using the new theme editor for twenty twenty two, adding the category or archive blocks to the header block causes template shortcode blocks to not get parsed. Raw shortcode is printed to the page and ignored, even on vanilla theme. 

### Step-by-step reproduction instructions

1. Add shortcode block to theme page (using caption code is good)
2. Add archive or category block to Header block
3. Save and view website. Shortcode is not parsed.  

### Environment info

WP 5.9.3**, twentytwenty two latest theme update. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

EDIT: Updated with proper info. WP 5.9.3 **

**Comment by justintadlock** [comment]
I was unable to replicate this issue when adding the Archives block inside the Header template part and the `[gallery]` shortcode or the `[caption]` shortcodes within the default Page template on WordPress 6.0-rc4 with Gutenberg 13.2.2.

I tried the shortcode in various places.  I put it in the Header template part, in the Page template, and within the page content itself.

@itsthex Can you provide more detailed steps to reproduce the issue?

**Comment by jordesign** [comment]
With no further discussion on this issue in over 12 months, and no further testing details, I'll close this issue.

@itsthex If you still see this issue in place with WP6.3 please open a new issue with updated testing instructions.
