### ISSUE TITLE
Symbolic link to site files for easier access to Filesystem from .wp-env directory

### ISSUE THREAD

**Issue by flexseth** [WordPress/gutenberg#40866]
## What problem does this address?

Currently, when you spin up an installation in the terminal, it gives you the option to admin the website. You can access the filesystem by clicking **Open In Visual Studio Code** in Docker, it takes a minute to mount, and you can see the files in VS Code. And I believe to be an obfuscated process (took a while to figure out where the `.wp-env` files were, to start...)

Recently I was trying to clean up some older `wp-env` sites, but I think I may have deleted work-in-progress, because you can't see the files directly from the installation directory (.`wp-env/2832023923892302309`) - or whatnot. 

When looking at the **.wp-env** folder, you see a ton of instances, but have to boot them before being able to open the filesystem by doing Docker > Open in VS Code. So I have actually deleted development work, thinking no work had been done but really the files are stored elsewhere and it's fairly unclear. I thought the sites were fresh installs of TwentyTwenty Two, but in reality, needed to run ``npm start`` to see I was working on a block.. before the plugin will correctly register and show up in the admin?

Is there a way to provide a symbolic link to the root folder, or some type of instruction (open files in Finder!) - so when I'm looking at a few of these environments, I can know what work has been done on one or the other? Or does it have to be fully booted in Docker, in order to be able to even access the files? Feel like the latter is not true... however... 

## What is your proposed solution?
Provide a symbolic link to the folder so you could `cd` in, and then `open .` - which shows you the files, or more verbose instructions as to where the actually files to work on, live. 

Screenshot of how it looks now, with `wp-env` booted from scratch
<img width="400" alt="filesystem" src="https://user-images.githubusercontent.com/3792502/167046167-a7a3cbe3-98de-473d-a985-4f2c37820d57.png">

**Comment by noahtallen** [comment]
Hmm, yeah. So the idea is to avoid using the hidden files most of the time. If you need to access them to do work, I'd suggest loading the files a different way. For code that you need to work on daily, you should have the config load from local directories that you manage. You can even pull a copy of WordPress-develop and load that as a relative path under "core", and the you can do whatever you want to it!

The idea is that things under `~/.wp-env` are things that wp-env should be managing, and if you need to manage that thing instead, you might want to map it yourself. (such as wp-config.php, the wordpress source code, etc) And especially local plugins and themes are meant to be mapped via local paths and not downloaded to `~/.wp-env`

If you're in a project directory, you can now see the wp-env dir with `npx wp-env install-path`, and you can clean things up with `npx wp-env --destroy`
