### ISSUE TITLE
Reuseable block content is invisible to search

### ISSUE THREAD

**Issue by kraftner** [WordPress/gutenberg#4086]
## Steps to Reproduce (for bugs)

1. Create a paragraph block containing "Lorem ipsum"
2. Search for "Lorem ipsum" => The post is found
3. Turn this block into a reusable block.
3. Search again for "Lorem ipsum" => The post is NOT found

## Expected Behavior

I'd expect reusable block content to be searchable just like any other block content.

## Current Behavior

Reusable blocks are "invisible" to search as their content isn't stored in `post_content`

## Possible Solution

The only idea I have is doing a secondary query for each search that first looks for the search term in all reusable blocks and then alters the main search query so that it also looks for all matching reusable blocks.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by pento** [comment]
Thank you for the report, @kraftner!

I agree that your proposed solution is the most viable option, but it would be a fairly expensive and tricky thing to get right. I think this is a case where Core's search won't necessarily produce the best or correct results, much like it currently doesn't search through content produced by shortcodes, for example.

If that level of accuracy is important to you, then you'll need to configure a more advanced search server, such as Elasticsearch.

**Comment by kraftner** [comment]
I am aware that Core's search is already severely lacking, but at least it has been like that consistently for a long time. Making it even more lacking is not going to help with the adoption of Gutenberg.

Also I'd assume that for a user it is way easier to understand that WP kind of only sees what the user can see in the editor (so no shortcode output) than grasping how some blocks are searched and some aren't while they all look the same in the editor.

I can understand how this is hard to fix and therefore not viable in 1.0 but I also don't think it is a great decision to close this as "Won't fix".
