### ISSUE TITLE
Optimize for the majority of WordPress users able to use Gutenberg on day one

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#4087]
Ideally, some large percentage (say, 95%) of WordPress users _should be able to_ use Gutenberg on day one (being excited to is another discussion).

By "should be able to", I mean:

* If one of their 10 active plugins disables Gutenberg, then they'll unexpectedly end up in the Classic Editor.
* If one of their 10 active plugins breaks Gutenberg, then they'll unexpectedly have JavaScript soup on their edit screen.
* If one of their 10 active plugins doesn't work with Gutenberg, then they'll be presented with a hard choice: to use or not to use.
* Etc.

It'd be great to actually measure this! Specifically:

* What percentage of WordPress installations are compatible with Gutenberg?

We'd derive this number from:

* How many total plugins does each WordPress installation have?
* Which plugins are most likely to be installed? In what combinations are they likely installed?
* What plugins are incompatible with Gutenberg? And, so we can help address, what are those incompatibilities? See #4072

**Comment by tn3rb** [comment]
> How many total plugins does each WordPress installation have?

completely subjective, but my observation is that most business sites appear to be using about 500 plugins!

**Comment by StaggerLeee** [comment]
I would like to see "revert" option togehther with WP 5.0 version.
If it screws things one click on button would revert it back to previous version. With all database changes.

**Comment by cedon** [comment]
@danielbachhuber - Plugins shouldn't be able to disable Gutenberg completely. There are flags that plugin authors can use for things like Custom Post Types that will force WP to use the classic editor instead as Gutenberg may not be compatible or suited with those CPTs at the moment like a plugin I am currently writing. But this should only affect those CPTs and the like. If you create a standard post or page Gutenberg should not be affected.

@StaggerLeee - Maybe not so much as a "revert" option but rather a means to globally switch the editor back to classic.

**Comment by danielbachhuber** [comment]
> But this should only affect those CPTs and the like. If you create a standard post or page Gutenberg should not be affected.

@cedon Do you know this definitively, or is this an assumption?

**Comment by cedon** [comment]
Yes. It is a filter that was committed back in October that allows Gutenberg to be disabled per post type.

https://github.com/WordPress/gutenberg/commit/2c418352216c27bebde93ab4de13fed410553e93

Also, while Gutenberg has added support for Meta Boxes, there is a flag that can be added to `add_meta_box()` that will declare it incompatible with Gutenberg as well. That is available in [the handbook](https://wordpress.org/gutenberg/handbook/reference/meta-box/#testing-converting-and-maintaining-existing-meta-boxes).

**Comment by gschoppe** [comment]
@cedon all that means is if a plugin modifies post or page, and won't work with Gutenberg, they will just include `add_filter( 'gutenberg_can_edit_post_type', __return_false );`, and Gutenberg will go away for everything.

**Comment by tofumatt** [comment]
Our aim in shipping release candidates and doing wider testing is that more and more websites work with Gutenberg, but I don't see anything in this issue right now that is very actionable. I agree with the idea but notably it requires a lot of data that I'm not sure we have access to.

Users can return to the Classic Editor with a plugin if needed, so I think right now this issue is covered as best as it can be. I'm going to close it because it doesn't fit the idea of an actionable, discrete issue. But the point is valid and I think we're aiming to do this for the project in general.

If I'm wrong let me know 😄
