### ISSUE TITLE
Navigation Panel: List pages not in the currently selected menu too

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40884]
## What problem does this address?
Two things:

1. It's not currently possible to add existing pages to menus directly in the Navigation Panel
2. In the future the Navigation panel will likely have a secondary function that enables folks browse the site inside the Editor. (See https://github.com/WordPress/gutenberg/issues/36667). But only pages present in the menu will be accessible which is a significant drawback.

## What is your proposed solution?
We can solve both of these issues by listing pages not in the current menu in the Navigation panel too. When #36667 is implemented a click will take you to that page. In the mean time we can make it trivial to add these pages to a menu using drag and drop:

https://user-images.githubusercontent.com/846565/167116341-6cef5098-b101-4945-9e30-8cd5bd713b30.mp4

In the future we can provide shortcuts to draft new pages here as well.

**Comment by getdave** [comment]
@jameskoster Thanks for the Issue. I understand the Navigation sidebar being for the purpose of managing menus rather than a "Site Navigator" interface.

It sounds like the higher level goal behind your request is to make this interface be able to add/remove/edit menus. That is indeed it's purpose, but it has yet to be implemented.

I believe there are other issues which cover that off.

I may have misunderstood however, so please feel free to put me straight 🙇‍♂️

**Comment by jameskoster** [comment]
I appreciate the browse component isn't functionality we have in mind for the navigation panel. 

But given that menu editing is, it seems reasonable to provide a way to add menu items?

There's no way for me to add a link to this menu from within the panel:

<img width="280" alt="Screenshot 2022-08-25 at 11 03 31" src="https://user-images.githubusercontent.com/846565/186636671-131cca0b-491a-4b26-8be7-178520e26197.png">

It doesn't necessarily have to be the solution proposed in the OP (listing all unliked pages for drag and drop). We might just append a "+ Add link" row beneath the last menu item. 

If there's already an issue for this, then we can probably close this one out 👍

**Comment by jordesign** [comment]
@jameskoster is this resolved with the current state of the Navigation Block sidebar?

<img width="539" alt="Screenshot 2023-09-14 at 1 06 02 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/74003749-4645-4085-a925-75cfe18986e3">

**Comment by jameskoster** [comment]
Yes, good catch :)
