### ISSUE TITLE
Template Editor: Update "Delete template" to "Clear customizations" when appropriate

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40885]
Related to https://github.com/WordPress/gutenberg/pull/40881.

## What problem does this address?
If you have customised a theme template, then open that template in the Template Editor, the UI suggests that template can be deleted (and the padding is messed up):

<img width="391" alt="Screenshot 2022-05-06 at 11 44 59" src="https://user-images.githubusercontent.com/846565/167117640-12ad7cd6-57d7-4dc7-a647-62bdbfe48246.png">

Clicking "Delete template" will clear your customisations but not delete the template.

## What is your proposed solution?
Update the label to use the "Clear customizations" language from the Site Editor:

<img width="294" alt="Screenshot 2022-05-06 at 11 48 45" src="https://user-images.githubusercontent.com/846565/167117845-94145611-b81d-41e0-b70d-96682887e979.png">

**Comment by Mamaduka** [comment]
I think this was mentioned in the original PR as well, but I forgot to do a follow-up.

I will assign this issue to myself and push an update next week.
