### ISSUE TITLE
New links get removed when setting the link to open in a new tab

### ISSUE THREAD

**Issue by joashrajin** [WordPress/gutenberg#40892]
### Description

I am not sure if this is related to https://github.com/WordPress/gutenberg/issues/40243 and could not find any other similar reports. 

While working on some P2 sites and making alterations, I noticed then whenever I change a link and then set it to open in a new tab, the link that I updated it to is removed. It looks like the changes aren't saved, and when we press 'Open in a new tab' the popup closes and removes any changes we make. 

It would be nice if the popup does not close when we press 'Open in a new tab' so that we can press enter to save the link change. This should improve efficiency. 

### Step-by-step reproduction instructions

1. Add a link to word a paragraph 
2. Make sure that it is not set to open in a new tab
3. Try to edit that link and then set it to 'Open in a new tab'
4. You should then notice that the new link you added was removed and the old one is set

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/16253818/167153002-d0fe9d50-711d-4053-a90e-64ee5321e9ac.mp4

### Environment info

- WordPress 5.9.3
- Chrome Version 101.0.4951.54 on MacOS 12.3.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by justintadlock** [comment]
I believe what I'm seeing in the video is the "correct" behavior.  After editing an existing link, you must either hit the `Enter` key or click the "submit" (curved arrow) button.  Otherwise, the link edit will not take.

Admittedly, this is not particularly evident from the UI and probably needs some refinement.

Can you give it a try while taking the submit action before clicking the "open in new tab" toggle?

**Comment by joashrajin** [comment]
Hi @justintadlock 👋

Thank you for looking into this. The Curved Arrow and Enter key does work, but whenever either of them are pressed, the link popup closes, so you need to re-open the popup to set the link to open in a new tab. 

To explain my use case, I have a large P2 page with multiple links that aren't set to open in a new tab. I am updating the links and setting them to open in a new tab. With the current way that it works, it means me (1) Updating the Link, (2) Pressing Enter, and (3) Re-opening the link popup to set it to open in a new tab. 

It would be nice if this could be adjusted for cases like this - I am sure that many other may also face this problem  :)

**Comment by justintadlock** [comment]
Thanks for the update. It sounds like the issue underneath all of this is that the popup closes after editing the link URL instead of remaining open for edits to other options. Here's an existing ticket for that: https://github.com/WordPress/gutenberg/issues/35795

**Comment by getdave** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/43144 as that Issue has more discussion
