### ISSUE TITLE
Border Tool: "Reset to default" appearing when unnecessary

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#40895]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/191598/167168787-c311f5f8-d775-49ff-a9ba-e0cc294e7dfd.png">

When editing a Border color this popover appears letting you select a color. At the bottom of this popover is a button to "Reset to default." This button appears all the time, even if the colors _are already set to the default_. In this state the button appears to do nothing.

It would be better if the button was hidden when the value is already set to the default.

**Comment by aaronrobertshaw** [comment]
Thanks for creating an issue to track this. I've put up a fix in https://github.com/WordPress/gutenberg/pull/40917
