### ISSUE TITLE
Border Tool: Inconsistent with other inspector inputs

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#40893]
The (new-ish) border tools are pretty cool, and really open the door to creating some nice patterns and designs. I did notice that they look different from other inputs in the editor's Inspector sidebar. Here's a comparison between the Border tool and the Radius tool:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/191598/167167631-f8182e3d-51ec-4053-8a3a-ecdf5f93978f.png">

The Border input is taller and has a lighter colored border. This appears unintentional and should be updated to match the other inputs.

**Comment by aaronrobertshaw** [comment]
I've created two separate PRs to tackle this as how best to control the component height might change with a possible move to `36px` default height in the near future.

Updating height: https://github.com/WordPress/gutenberg/pull/40920
Updating border color: https://github.com/WordPress/gutenberg/pull/40921

**Comment by javierarce** [comment]
I couldn't find the designs for this tool, so I created a proposal in the [Design Library](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=33859%3A24539).

![image](https://user-images.githubusercontent.com/4933/167393646-def1a1d6-2d1d-4fb5-b192-dce5d8c157b9.png)

**Comment by aaronrobertshaw** [comment]
> I couldn't find the designs for this tool

@shaunandrews is probably the best person to point to any official designs. You might find some extra details within https://github.com/WordPress/gutenberg/issues/35602 though.

**Comment by javierarce** [comment]
@aaronrobertshaw thanks! I actually used some of those designs to create the components above. I just wanted to mention that those components exist now in the library.

**Comment by mtias** [comment]
It seems that things should be adjusted the other way, not going down to 30px but increasing to 40px, which is where we have settled for the new tool controls:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/548849/174545138-bacefd5a-3095-4165-93ac-a92cb445ff71.png">

**Comment by mtias** [comment]
This also goes for the border radius control:

<img width="884" alt="image" src="https://user-images.githubusercontent.com/548849/174645373-02b4f093-5ede-4464-8a61-7697d7781daa.png">

**Comment by aaronrobertshaw** [comment]
Thanks for the direction @mtias on which way we should be moving these controls.

Can you clarify if we should be migrating these controls directly to a `40px` height now, or update them such that the `40px` height can be toggled on whenever all the other controls in the sidebar are ready for the same height?

In other words, are we OK with the border controls being at `40px` even though other controls in the sidebar are shorter?

<details>
<summary>Example screenshots</summary>

| Global Styles | Inspector Controls |
|---|---|
| <img width="302" alt="Screen Shot 2022-06-22 at 5 30 27 pm" src="https://user-images.githubusercontent.com/60436221/174973422-b08b8bcd-8c32-4ff9-aa53-78a7cfc3b3e8.png"> | <img width="305" alt="Screen Shot 2022-06-22 at 4 52 15 pm" src="https://user-images.githubusercontent.com/60436221/174973450-9fd31d66-a19c-4325-a3cb-a5aae1908967.png"> |

</details>
 
 I've put together a quick draft PR (https://github.com/WordPress/gutenberg/pull/41860) adding a `__next40pxDefaultSize` prop to the border control components allowing for their height to be toggled to `40px` via the patch included in that PR's description. If we decide to update the controls directly to `40px` now instead, I'll update that PR accordingly.

**Comment by mtias** [comment]
We need to be updating all the controls gradually and systematically. For example, the layout content/wide setting is set at 40px in the global styles designs:

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/548849/175003919-2ae0dad2-65e9-423a-94b2-908555002091.png">

**Comment by aaronrobertshaw** [comment]
I'm not sure I'm following your last comment 100% sorry.

> We need to be updating all the controls gradually and systematically.

Does gradually here mean we are happy to have inconsistent control heights (maybe just between panels) for however long it may be until we update all controls? Or, does systematically mean we want to update all controls together so we avoid that inconsistency? 

The latter was the thinking behind https://github.com/WordPress/gutenberg/pull/41860 and the end of my [earlier comment](https://github.com/WordPress/gutenberg/issues/40893#issuecomment-1162803113).

**Comment by mtias** [comment]
@aaronrobertshaw sorry missed the ping — I'm fine with some inconsistency as we work through it. By systematically I mean not abandoning it or trying to do it in one go, which is unlikely to happen. We should focus one panel at a time and get it to match the designs as soon as possible.

**Comment by aaronrobertshaw** [comment]
Thanks for the clarification @mtias, I'll revisit this and update https://github.com/WordPress/gutenberg/pull/41860 as soon as possible.

**Comment by aaronrobertshaw** [comment]
Closing this issue as I believe all the tweaks to the controls sizing, focus, etc. have been resolved now #41860 has been merged.
