### ISSUE TITLE
Template Editor: Hide confusing 'switch to draft' button

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40891]
When you engage the template editor, assuming the document you were editing previous was published, the "Switch to draft" button persists in the top bar:

<img width="1449" alt="Screenshot 2022-05-06 at 14 22 20" src="https://user-images.githubusercontent.com/846565/167143930-8e17f85e-04b7-4da4-8413-58c5a9d2a6fd.png">

This could easily mislead folks into assuming they can make their template a draft, which is not the case. 

I think the simplest solution would be to hide this button in the template editor.

**Comment by mtias** [comment]
Should we move this to the sidebar in general (also for the post editor)?

**Comment by jameskoster** [comment]
Yes, it's probably a bit too prominent for a task that is fairly uncommon. Moving it to the Inspector would resolve this issue too. Perhaps it can be part of the work in https://github.com/WordPress/gutenberg/issues/39082.

**Comment by mtias** [comment]
If that takes too long it might be good to just move it in the meantime

**Comment by noisysocks** [comment]
From https://github.com/WordPress/gutenberg/pull/40971#issuecomment-1169524721:

> Maybe it could go into the meatball (⋮) menu that's proposed in https://github.com/WordPress/gutenberg/issues/39082?
> 
> ![Menu](https://user-images.githubusercontent.com/612155/176352683-f5fe7dae-2b6b-44d8-a12c-d7065b6562cf.png)

**Comment by youknowriad** [comment]
This button is not in the header anymore.
