### ISSUE TITLE
Non-existent time in Block Library (String error in WordPress 6.0 RC)

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/gutenberg#40916]
### Description

The cherry-picked Gutenberg blocks for WordPress 6.0 include the following string:
`January 1, 2000 at 00:00 am`

Note that IF am/pm is used, then there is no hour "00", but should be 12:00 am.
If this string is only displayed, then this is mostly a cosmetic problem, but if the string is going to be construed by software, then this might raise warnings and/or eyebrows.

I found string while checking translations for WordPress 6.0. The source reference is https://build.trac.wordpress.org/browser/trunk/wp-includes/js/dist/block-library.js?marks=31215#L31215

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I think it was introduced here - https://github.com/WordPress/gutenberg/pull/40484

cc @luisherranz

**Comment by luisherranz** [comment]
> If this string is only displayed, then this is mostly a cosmetic problem

Yes, it's just for a placeholder, but I'll add a PR to fix it. Thanks for the heads up 🙂

**Comment by luisherranz** [comment]
PR opened: https://github.com/WordPress/gutenberg/pull/40929
