### ISSUE TITLE
"couldn't find remote ref master" when `wp-env start` with plugin's github repo

### ISSUE THREAD

**Issue by imjlk** [WordPress/gutenberg#40928]
### Description

[New repositories use main as the default branch name](https://github.com/github/renaming#new-repositories-use-main-as-the-default-branch-name)

According to above link, Github repo's default branch name is main.

However, `wp-env` only works with the master branch. It seems that need to adding condition to find the main.

### Step-by-step reproduction instructions

1. Install wp-env(@wordpress/env) globally or locally
2. Create .wp-env.json file
3. fill contents with below lines

```json
{
  "plugins": [
    "wpengine/atlas-content-modeler"
  ]
}
```

> Or you can replace it other plugin with having not master branch

4. run with `wp-env start` then you can see the error

```shell
> your-package-name@1.0.0 wp-env
> wp-env "start"

✖ fatal: couldn't find remote ref master

GitError: fatal: couldn't find remote ref master

    at Object.action (C:\path\your-package-name\node_modules\simple-git\dist\cjs\index.js:1194:25)
    at PluginStore.exec (C:\path\your-package-name\node_modules\simple-git\dist\cjs\index.js:1229:29)
    at C:\path\your-package-name\node_modules\simple-git\dist\cjs\index.js:1590:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (C:\path\your-package-name\node_modules\simple-git\dist\cjs\index.js:1588:16)
    at GitExecutorChain.<anonymous> (C:\path\your-package-name\node_modules\simple-git\dist\cjs\index.js:1572:44)
    at Generator.next (<anonymous>)
    at fulfilled (C:\path\your-package-name\node_modules\simple-git\dist\cjs\index.js:55:24) {
  task: {
    commands: [ 'fetch', '--tags', 'origin', 'master' ],
    format: 'utf-8',
    parser: [Function: parseFetchResult]
  }
}
```

### Environment info

"@wordpress/env": "^4.6.0"

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @imjlk,

You can specify a Github repository `ref` as described in [the document](https://github.com/WordPress/gutenberg/tree/trunk/packages/env#wp-envjson).

The following statement will make `wp-env` work properly:

```json
{
	"plugins": [
		"wpengine/atlas-content-modeler#main"
	]
}
```

_*Note: Since the repository is not built automatically, the plugin's settings page will probably result in an error._

The specification of `wp-env` seems to refer to `master` if no ref is specified, but it cannot be read from the document.
Therefore, I will consider submitting a PR to update the documentation.

**Comment by glendaviesnz** [comment]
I have put up a [PR for this](https://github.com/WordPress/gutenberg/pull/41043). Given that `master` is not the default anymore in WordPress, Gutenberg, or Github it probably makes sense to change the fallback to `main` as well as updating the docs.

It is not working yet though, and have run out of time to finish, will hopefully complete it early next week.
