### ISSUE TITLE
Message to clear empty blocks

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4092]
An interesting bit of feedback from the form:

"When saving or publishing a post, perhaps offer an option to be able to clear or prompt the user to empty blocks accidentally left in the editor."

This is a good idea and at minimum saying on publish would be good. Because of placeholders I don't think we can delete or clear.

**Comment by mrjarbenne** [comment]
I wonder if empty blocks are merely an artifact of early use. When I first started using Gutenberg I found I was creating empty blocks, but now that I better understand the workflow, I'm avoiding creating them, or attending to them immediately. 

In my experience, empty blocks occur as you are exploring the functionality of the workflow, but are much more rare when you switch from kicking the tires to driving the car.

**Comment by karmatosed** [comment]
@mrjarbenne maybe but we should make sure early users get the best experience they can. This could go a little way to doing that.

**Comment by mrjarbenne** [comment]
I wonder if the Table of Contents could be utilized in some way to attend to this. If each block was listed in the TOC in a fashion where it indicated whether the block was populated or not, you could navigate to them and delete them. It would also present as a skeleton view to quickly look over placeholder structure.

**Comment by karmatosed** [comment]
I am going to close as this hasn't really come up lately and there is being discussed removing things like stray blocks. Perhaps one to look into as we get more and more testing feedback once in merge.
