### ISSUE TITLE
Gallery block: the CSS generated for the block spacing is printed at the end of the page unlike other blocks

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#40936]
### Description

Using a block theme, the inline CSS generated by a block is printed in the `<head>` of the page using `gutenberg_enqueue_block_support_styles()`
https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-5.9/script-loader.php#L63-L74

For example, when you insert a Columns block, the following CSS is printed in the `<head>`:
```
.wp-container-1 {
    display: flex;
    gap: var( --wp--style--block-gap, 0.5em );
    flex-wrap: nowrap;
    align-items: center;
} 
```

However, for the Gallery block, the CSS is printed just above the closing `</body>` tag, which creates a flash of unstyled content: 
```
.wp-block-gallery-1 {
    --wp--style--unstable-gallery-gap: 20px;
    gap: 20px;
}
```

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/gallery/index.php#L66-L71

Is there a reason to use the `wp_footer` hook instead of `wp_head` for the gallery block?

### Step-by-step reproduction instructions

1 Insert a Columns block.
2. Insert a Gallery block.
3. View the page source. 
4. Observe that the CSS for the columns is printed inside the `<head>` while the CSS for the gallery is printed just above the closing `</body>` tag.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I am working on a potential fix for this here https://github.com/WordPress/gutenberg/pull/41015, which will load the styles in the header for block themes

**Comment by markhowellsmead** [comment]
@glendaviesnz Additional: the gap is a fixed size in the generated inline CSS: `gap: 0.5em` instead of a custom CSS property

**Comment by 3000nz** [comment]
> @glendaviesnz Additional: the gap is a fixed size in the generated inline CSS: `gap: 0.5em` instead of a custom CSS property

I need to make the value `0` instead of `0.5` for a specific page (at the end). BUT wordpress overrides my in-line page css injection of 0 because the wordpress CSS is last on the page load (it's overriding my 0). Is there a solution? 

all this needs to be 0

```
:where(.is-layout-flex) {
    gap: 0.5em;
}


.wp-block-gallery.wp-block-gallery-1 {
    --wp--style--unstable-gallery-gap: var(--wp--style--gallery-gap-default, var(--gallery-block--gutter-size, var(--wp--style--block-gap, 0.5em))); */
     gap: var(--wp--style--gallery-gap-default, var(--gallery-block--gutter-size, var(--wp--style--block-gap, 0.5em))); 
}
```
