### ISSUE TITLE
Unable to manually enter eight-digit hex color value in the color picker

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#40943]
### Description

The hex value #ffffff50 is valid, but the color picker doesn't allow this to be entered in the manual color value field.

### Step-by-step reproduction instructions

1. Try to add #FFFFFF50 (or any eight-digit hex value) in the manual color value field of the color picker.

### Environment info

- WordPress 5.9.3 without plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi @markhowellsmead ; 

I am not able to reproduce this on Gutenberg 13.7.3; I am able to enter 8 digit hex values in the color picker =) 

Please reopen if you're still experiencing this. 

![image](https://user-images.githubusercontent.com/955351/182232752-313fafe5-92d0-43e4-9e6b-84c555a67b5a.png)

**Comment by markhowellsmead** [comment]
Confirmed: works in WordPress 6.0. Thanks!
