### ISSUE TITLE
Remove opinionated styles on the front end

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#4094]
I have been testing Gutenberg from a themers perspective and one of the things I have noticed is that Gutenberg adds some default styles to things.

I can understand that some things are required but I think that, where possible, the theme should be the one to set these things.

For example, blockquotes change the font to a system font and don't respect the theme font which would normally be inherited, even if there's no font set for blockquotes.

I have seen the suggestion that themers should dequeue the default styles - and that is certainly an option - however I think that would be a pain to maintain since styles for new blocks would then need to be added to the theme as well. Currently I like that blocks like the cover image block 'just work', and I don't want to have to maintain that css.

If the styles were less opinionated then we could keep the gutenberg specific css and let the theme take care of the other bits.

The things I think should be left to the theme include, font-face, border styles, background colours. Anything that involves colour or size.

Another suggestion, would be to have two separate gutenberg stylesheets. One that takes care of layout elements of block design (such as the cover image or button stuff), and one that takes care of colours, sizes etc. Themers can then dequeue, or maybe opt out in the Gutenberg theme support, from the design stylesheet and still keep the layout elements.

**Comment by mtias** [comment]
@BinaryMoon looked at the quote blocks and it seems only pullquote is adding font-family styles, which looks like a bug since we are not applying the styles on the editor because of the selector (`> p`).

**Comment by mtias** [comment]
If there are other specific items that you think problematic, please, open separate issues. The case of quote-source having a gray color is tricky. We might want to preserve in editor context but not front-end, but then it deviates. This is also the case with the quote border which we don't render on the front, but a theme might want to inherit basic styles from the editor still.

**Comment by BinaryMoon** [comment]
@mtias thanks. That certainly helps.

I've just checked and it looks like the styles I was referring to may have been changed or removed. I shall do some more testing and make some proper tickets. Might even do a pull request or two.

**Comment by BinaryMoon** [comment]
Now that I know where the css is I've been going through the colours and there's a lot of them. And they all assume the theme uses a light background. I still think there's quite a lot to change to make this easily editable.

For example

> The case of quote-source having a gray color is tricky

I would suggest not using colours and instead using a 50% opacity. The text can then inherit the themes colour and will work whatever the background colour.

> but then it deviates

I don't think deviating is a bad thing. In fact not deviating could be a bad thing for example if the theme has a grey background then the grey color being forced on users will now be hidden.

I think the best thing to do is to make it as easy as possible for people to override the editor styles so they fit the look of the theme.

**Comment by mtias** [comment]
Yes, by deviation I mean under the assumption the editor could be styled light-on-dark by the theme.

> I would suggest not using colours and instead using a 50% opacity.

This might be interesting to explore. Would you be up for creating a PR and showing how it could look in different contexts?

Wonder if we could add a dark scheme for the editor pending full theme customization. cc @jasmussen @karmatosed

**Comment by karmatosed** [comment]
I would caution using opacities, you get a lot of issues with different colour combinations and stacking. We can explore but it could cause a lot of issues once people start customizing.

> Wonder if we could add a dark scheme for the editor pending full theme customization.

I would really like to see a dark scheme explored. I'd be up for doing that also myself. Making an issue to explore #4302, noting it's an experiment.

**Comment by karmatosed** [comment]
> Both have negatives for sure - but my gut says that a solution using opacity would have fewer issues than overriding a themes default settings.

@BinaryMoon totally both do, in my experience though opacity has had far more than the non-opacity route.

> I'm not sure a dark theme is a good idea. I think there's too much being prescribed by Gutenberg that is essentially saying 'your theme should look like this' removing the choices and creativity of theme design.

Consider the dark theme an experiment not one that would get in, although if it did it would answer some strong accessibility reasons. Little side point, but to have a really accessible interface to people like those with dyslexia and other variations, having a light, dark and sepia (non white background) option would be the best possible outcome. In doing the dark theme it shows how a style could be done, it's an exercise.

> I am considering making some pull requests (I am making a list of things that I think need work from a themers perspective) but am not sure it's worth the effort.

I would encourage you to make them as we can always discuss in ticket and come to outcomes there. It's hard to say yes or no without there being issues.
