### ISSUE TITLE
Latest Posts block: Posts link wants to redirect in editor as well

### ISSUE THREAD

**Issue by imnavanath** [WordPress/gutenberg#40953]
### Description

When Latest Posts block drag dropped in editor it triggers post links. In editor opening posts links is not UX.
Issue reproducible in - v5.9.3, 6.0.rc
With theme - All default themes

### Step-by-step reproduction instructions

1. Take Latest Posts block in editor.
2. Try clicking on title.

### Screenshots, screen recording, code snippet

Screencast for the issue - https://share.bsf.io/v1ugXbXN
Comparison with Elementor - https://share.bsf.io/JruO242r

### Environment info

- WP-6.0RC1
- Active theme - 2022
- Plugins - None
- Browser - Chrome
- System - Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
The issue was fixed recently #40593.
