### ISSUE TITLE
Gallery Block "Link To" Setting Not Creating Links for Images

### ISSUE THREAD

**Issue by mdrockwell** [WordPress/gutenberg#40968]
## Description
If you change a gallery's "Link To" setting to either "Attachment Page" or "Media File", neither is respected when viewing a preview or after publishing.

## Step-by-step reproduction instructions
1. Add a Gallery block to a post or page.
2. Add a number of images to the block.
3. Use the gallery block's gear icon to access it's settings (not an individual image, the whole block).
4. Change the "Link To" setting to either "Attachment Page" or "Media File".
5. Save as draft and preview or publish and view the post/page.

## Expected behaviour
The images would all have the appropriate link added to them.

## Actual behaviour
None of the images include a link.

## WordPress information
WordPress Version: Tested on a WordPress.com Business plan site.
- Are all plugins except Gutenberg deactivated? No plugins installed at all.
- Are you using a default theme (e.g. Twenty Twenty-One)? No — Independent Publisher 2

## Device information
- Device: iPhone 13 Pro
- Operating system: iOS 15.4.1
- WordPress app version: 19.8.0.0

**Comment by SiobhyB** [comment]
👋 @mdrockwell, I coincidentally _just_ merged a fix for this bug in https://github.com/WordPress/gutenberg/pull/40947. :D The fix should be available in the beta for the upcoming release (19.9) next week.

**Comment by hypest** [comment]
Closing as per @SiobhyB 's comment above, please feel free to reopen if still occurring after fix gets to production. Thanks!
