### ISSUE TITLE
Gutenberg dev env fails to npm install when using Python 3.x

### ISSUE THREAD

**Issue by ryo-utsunomiya** [WordPress/gutenberg#4096]
## Issue Overview

When system's default python is v3.x, running `npm install` in WorePress/gutenberg repository fails. This error is caused by `node-gyp rebuild`.

```
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Users/ryo/anaconda/bin/python" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/Cellar/node/8.9.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ryo/src/wordpress/gutenberg/node_modules/weak
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

## Steps to Reproduce (for bugs)

1. Install python 3.x and set system default python as 3.x
2. `cd /tmp`
3. `git clone git@github.com:WordPress/gutenberg.git`
4. `cd gutenberg`
5. `npm install`

My environment:

- macOS 10.13.2
- Node.js 8.9.1
- Python 3.6.1

## Expected Behavior

Successes to install.

## Current Behavior

Fails to install.

## Possible Solution

1. Install Python 2.7
2. `npm config set python /path/to/python`
3. `npm install`

FYI: Some UNIX systems(like macOS, Ubuntu) has Python 2.7 at `/usr/bin/python`.

## Screenshots / Video

N/A

## Related Issues and/or PRs

N/A

## Todos

- [ ] Should add troubleshooting memo to documentation?

**Comment by youknowriad** [comment]
Do you know which dependency is causing this? I think this issue is better raised in their issue tracker.

**Comment by karmatosed** [comment]
Closing as agree this is better to raise in issue tracker for the dependency.
