### ISSUE TITLE
List v2: convert markdown based lists to list blocks

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40980]
## What problem does this address?

When using the List v2 experiment, it doesn't convert markdown to the list block automatically. This came up as part of the [fourteenth call for testing for the FSE Outreach program](https://wptavern.com/fse-outreach-14-building-recipe-posts-with-lists-and-quotes):

>Markdown-based lists are also not transformed into a List block when pasted into the editor. The formatting is lost, and each item gets absorbed into a Paragraph block.

This includes ordered and unordered list. I tested by copying examples [from here](https://www.markdownguide.org/basic-syntax/#ordered-lists):

https://user-images.githubusercontent.com/26996883/167723309-c858f4d4-240e-4cde-953f-6e88ec744fcf.mov

## What is your proposed solution?

Add some markdown support for when pasting into the editor. cc @ntsekouras

**Comment by ellatrix** [comment]
This works now with #42524. This is the content I tried:

```
1. First item
2. Second item
3. Third item
    1. Indented item
    2. Indented item
4. Fourth item
```
