### ISSUE TITLE
Click inside Buttons block : focus go to random inner Button block

### ISSUE THREAD

**Issue by MarieComet** [WordPress/gutenberg#40997]
### Description

When I click inside Buttons block, the focus is immediately going on a random child Button block. 

### Step-by-step reproduction instructions

(Video screenshot below)
Insert a Buttons block, create Button blocks inside of this block.
Click elsewhere in the editor, and click again on the Buttons block.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/7976501/167844906-21216cb3-62b5-45e8-b487-1ff34a3e3c8e.mp4

### Environment info

- WordPress 6.0-RC2
- Firefox 99.0 (64 bits)
- Ubuntu 20.04.4 LTS 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi!
In my test, I used "Emptytheme", and I placed buttons inside a column block just to make sure they wrap to two lines.
When I click in different places close to the buttons, focus moves to the button that it closest, and I think that is reasonable?
-What was your expected result?

https://user-images.githubusercontent.com/7422055/176907715-e0f4b553-4694-4cb8-bd36-44c38c8a0b2a.mov

**Comment by jordesign** [comment]
Testing this again - I also get the focus moving to the button that is closest. I'd agree this seems reasonable behaviour - and given the lack of other activity on this issue I'll close it.
