### ISSUE TITLE
Post Featured Image block: Alt text from media library is not returned

### ISSUE THREAD

**Issue by luminuu** [WordPress/gutenberg#40999]
### Description

When selecting a featured image from the media library, you can add an alt text for the given image. However on the frontend, only the name of the post or page is returned in the alt text of the featured image, instead of the saved alt text from the media library.

### Step-by-step reproduction instructions

1. Make sure to have a block theme active.
2. Go to a post or page where you have a featured image, or create a new post or page and add a featured image.
3. Make sure you have set an alt text when selecting the featured image from the media library.
4. Save the post or page.
5. Go to the frontend and check the alt text of the featured image. It should contain the post or page title instead of the alt text from the media library.

### Environment info

- WordPress 6.0 RC2
- Gutenberg plugin 13.1.0
- Wabi Theme, but same behaviour on Twenty Twenty-Two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I believe the alt text is only intended to be the post or page title if the image is linked. I was able to confirm that it is used when the image is not linked. @aristath
https://github.com/WordPress/gutenberg/pull/39634

**Comment by aristath** [comment]
Thank you for reporting this @luminuu, and for bringing it to my attention @carolinan.
This was introduced in https://github.com/WordPress/gutenberg/pull/39634, and a PR that fixes this can be found in https://github.com/WordPress/gutenberg/pull/41775. 👍
