### ISSUE TITLE
Default 'Title Placeholder' will remains when we don't use space

### ISSUE THREAD

**Issue by man4toman** [WordPress/gutenberg#40992]
### Description

When we start typing the main title, the default title placeholder will remains until we use space in the title.
Please check the video.

### Step-by-step reproduction instructions

1- Go to add new post
2- Start typing the title without space

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/935397/167815105-3b4d7aea-978c-4ec5-9468-b0e196e10419.mp4

### Environment info

- WordPress 5.9.3
- Google Chrome 101.0.4951.41
- Android 9 Pie, Samsung Galaxy A20s 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. Are you able to reproduce this on the newest version of WordPress (6.1)? 

Do you also experience this after you have deactivated all other plugins on your installation?

**Comment by priethor** [comment]
Let's close this issue, as it needs more info to be actionable. Please feel free to reopen again if there is more information. 🙏
