### ISSUE TITLE
Query block: is not respecting perPage attribute in inherited context

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#40996]
### Description

In the query block, when `inherit` is set to `true`, query block always shows `10` posts and doesn't respect the `perPage` value.

### Step-by-step reproduction instructions

The following query with `inherit: false` shows 3 posts.
```
<!-- wp:query {"queryId":18,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false}} -->
```

Same query with `inherit: true` shows 10 posts.

```
<!-- wp:query {"queryId":18,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":true}} -->
```

### Environment info

- Latest GB

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
When the query inherits the context, it uses the WordPress "Blog pages show at most" global reading setting, and I believe this is working as intended. 

How to communicate that this is intended, when it is not expected, is something that needs to be solved 🤔

**Comment by priethor** [comment]
@carolinan if I'm understanding correctly, the `perPage` setting will be ignored whenever the `inherit` option is enabled as it will ultimately be overridden by the global setting, is that so? In that case, the `perPage` setting should be hidden when when `inherit` is enabled.

**Comment by carolinan** [comment]
That is my understanding.
The per page setting is already hidden when inherit is enabled. It is removed from the toolbar.

<del>I think it would be good of these two per page values always matched.</del> 
Oh never mind, they can't match because different queries need to be able to have different numbers.

**Comment by ntsekouras** [comment]
Thanks for the issue @madhusudhand!

>When the query inherits the context, it uses the WordPress "Blog pages show at most" global reading setting, and I believe this is working as intended.

That is intended and should be that way, as we have explicitly set the `Query` to inherit the global query. It's also true that if we toggle to `inherit`, we hide the `per_page` settings in the block toolbar. We also have logic in the block to get the value from settings if we create a new `Query` and the `per_page` option is not set and the `inherit` is `true`, but with the existing block variations(all set `inherit:false`), this is only possible from patterns with these settings.

Maybe the solution here could be to update the `per_page` to the site's setting when we set `inherit:true` to be more indicative in the editor. In general there are still some nuances of having a good preview in the editor of an `inherited` Query Loop block and a simple example would be the `index` template. We don't know what to show in the editor as the `index` is a fallback for everything 😄 .

**Comment by madhusudhand** [comment]
Thanks @carolinan @ntsekouras for the inputs and details of the behaviour 😄. This helps resolving my issue.
Please consider it as resolved.
