### ISSUE TITLE
Inline controls not working

### ISSUE THREAD

**Issue by lisaleague** [WordPress/gutenberg#41]
Bold, Italic, Link, Strikethrough, etc not working for me on Chrome Version 55.0.2883.75 (64-bit) on OSX El Capitan

**Comment by JDGrimes** [comment]
I'm guessing that this just hasn't been implemented yet, as it's not working for me either (Firefox 51.0.1 (64-bit) and macOS Sierra 10.12.3). Didn't see a ticket for it yet though.

**Comment by jasmussen** [comment]
@JDGrimes is right, it's simply not been implemented. 

Initially this was meant only to be a UI prototype, with mostly dummy controls, just to get a feel for how the concept might work. However it could be growing into something more. We'll be exploring prototypes that use TinyMCE as the parent container for all blocks, and one that uses TinyMCE as a child of each block. Perhaps this prototype can grow into one of them? @mtias ?

**Comment by mtias** [comment]
![image](https://cloud.githubusercontent.com/assets/548849/22827844/405f8630-ef9a-11e6-9f5c-26ee4f03d41d.png)

Adding a message about them.
