### ISSUE TITLE
Site Editor: improve flow for creating a new template part

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#41008]
## What problem does this address?

Currently, when you head to the Site Editor > Template Parts > Add New, you are dropped into an empty experience without even a + button to orient you. This feels like a fairly jarring and underwhelming UX:

https://user-images.githubusercontent.com/26996883/167932393-e2703eaa-fecc-4bd8-90a1-322756d533f7.mov

## What is your proposed solution?

- Consider prioritizing patterns in the quick inserter when creating new template parts. This would build on previous efforts to prioritize patterns in the quick inserter: https://github.com/WordPress/gutenberg/pull/38709 
- Ensure there's a clear + button experience when creating a new template part, similar to what you would see when creating a new post when you land in the new template part. This might be a bug:
<img width="720" alt="Screen Shot 2022-05-11 at 12 42 10 PM" src="https://user-images.githubusercontent.com/26996883/167932554-ad69ca22-39be-4445-8c55-aa030a52d5ca.png">

**Comment by annezazu** [comment]
cc @jameskoster since you have other explorations on creating new template parts and @jorgefilipecosta since you've worked on the quick inserter piece of this and might have thoughts.

**Comment by jameskoster** [comment]
We can prioritise patterns for semantic template parts, but I'm not sure about general ones. The scope is vast which makes it difficult to provide helpful suggestions.

In general I agree that we can re-use elements of the existing empty header / empty footer block experience. It may need some adjustments though – perhaps pattern selection can occur in the initial modal when you input the template part name and select the area.

**Comment by carolinan** [comment]
I feel that short term we should re-enable the inserter

**Comment by carolinan** [comment]
Also see https://github.com/WordPress/gutenberg/issues/37524

**Comment by jameskoster** [comment]
Agreed, if users elect to create a general template part they will see a blank canvas, and even if they select header / footer they can still 'start blank'.

**Comment by jameskoster** [comment]
I think we can combine:

* The [latest designs for creating regular templates](https://github.com/WordPress/gutenberg/issues/37407#issuecomment-1075247090).
* The freshly implemented [option to pick a pattern on page creation](https://github.com/WordPress/gutenberg/pull/40034).

https://user-images.githubusercontent.com/846565/168093820-d0a009da-33b2-4747-992e-fa8054d922a7.mp4

You'll notice the "choose a name" step is omitted. If the user selects a pattern we can probably go ahead and use the pattern name for the template part. If they don't, placeholders like "Untitled Template Part" are probably fine because requiring a name up front adds a lot of unnecessary friction.

**Comment by annezazu** [comment]
Whew that feels LOADS better, @jameskoster. Thank you. The lack of inserter is present in 6.0 RC2 and it feels pretty important to fix. I'll comment on the PR from @carolinan to see if we can get that in.

**Comment by jameskoster** [comment]
https://github.com/WordPress/gutenberg/pull/41024 Partially resolves this. https://github.com/WordPress/gutenberg/issues/41060 will handle the suggestion of patterns on creation. I'll create a new issue to align the "New template" menu with regular templates.
