### ISSUE TITLE
Block Styles: default style picker gone(?)

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#41017]
### Description

I went through the options of the `block.json` and noticed the one that allows to hide the block style default picker. I was not sure where that picker was displayed, so I opened the editor, selected a block with a block style (quote block) and was not able to find the select option. I searched if that was removed somewhere, but only found a PR from November where it was still there (https://github.com/WordPress/gutenberg/pull/36976)

### Step-by-step reproduction instructions

1. Go to the block editor
2. Select a block with styles (quote, for example)
3. Search for the default style select in the block sidebar

### Screenshots, screen recording, code snippet

![grafik](https://user-images.githubusercontent.com/2310924/168001035-6ecafb61-ad38-4ccf-a939-60045482ff71.png)

### Environment info

- WordPress 6 RC 2, no Gutenberg plugin enabled.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aristath** [comment]
I just noticed the same thing a few minutes ago and was wondering what happened... 
I can confirm that the default block-style selector is no longer there (using Gutenberg trunk)

**Comment by Mamaduka** [comment]
cc @ramonjd

**Comment by ramonjd** [comment]
Thanks for the ping!

Removing the default style picker was a deliberate measure. See this comment from @mtias : 

> Let's skip the "make default" for now as we need to reintroduce it better with global styles anyways. The current behaviour is in itself odd since it doesn't change existing styles but modifies what gets inserted as a default going forwards. It predates global styles which is a better layer of abstraction there. We'll need mechanisms for making any set of customization to block supports work globally from the local context, so when we get into that we can develop a more comprehensive design. For now let's try removing that functionality.

Source: https://github.com/WordPress/gutenberg/pull/34522#issuecomment-929008566
Related design comment: https://github.com/WordPress/gutenberg/pull/34522#issuecomment-928167469

The intention was to hook block style defaults into global styles, though I can't find any progress on that. Would it be something folks are interested in pursuing?

Of course reinstating the dropdown is another course of action if people miss the functionality, and think it's worth adding back in.

Cheers!

**Comment by florianbrinkmann** [comment]
Thanks for the info! Just wanted to make sure it is not a regression :)

**Comment by mtias** [comment]
Yes, it's something we need to revisit but as part of global styles (the per block section). The default style felt too much like a hack and was confusing people. In the future we should be able to jump from local styles into global styles, and promote any local styles as "I want these to be the styles applied to all blocks of this type". A lot of things to pursue there.
