### ISSUE TITLE
Deleting new word on split RichText block does not merge blocks

### ISSUE THREAD

**Issue by jhnstn** [WordPress/gutenberg#41012]
## Description
[TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - merge after selection is failing on Android only

## Step-by-step reproduction instructions

Follow the TC002 test case linked above

## Expected behaviour

The split blocks should merge.

## Actual behaviour

The split blocks do not merge.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/744755/167980131-ce245fbe-bac6-42bf-b3e8-c8db913b3274.mp4

## WordPress information
- WordPress version:  WordPress.com Simple Site
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Pixel 6
- Operating system: Android 12
- WordPress app version:  19.8-rc-2

**Comment by fluiddot** [comment]
@jhnstn I could only reproduce this issue by using the Gboard keyboard, using the OS one (in my case, the Samsung Keyboard) seems to work. I found out that we already have [an issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375) that describes a quite similar behavior, so we might consider this as a duplicate issue, wdyt?

**Comment by jhnstn** [comment]
You're right , closing in favor of the prior issue
