### ISSUE TITLE
Alignment issue in Latest Comments block

### ISSUE THREAD

**Issue by KAJALwp** [WordPress/gutenberg#41027]
### Description

When we select the Latest Comments block in our post or page and apply the alignment for that, it is not showing proper in front-side. when we choose Align center for latest comments block it is not reflected in front-side.

For better understanding I have attached video link.

Thanks

### Step-by-step reproduction instructions

1. Go to editor
2. Add latest comments block
3. choose alignment option
4. see changes in front-side

### Screenshots, screen recording, code snippet

https://share.cleanshot.com/7nT682BkvHK3C4V1F0BX

### Environment info

WordPress:- 5.9.3
Mac OS:- Monterey 12.3.1
Chrome:- 101.0.4951.54 (Official Build) (arm64)
Theme: Twenty Twenty
Gutenberg Plugin: 13.2.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I'm unable to recreate this in WP6.3 - so it appears resolved.
