### ISSUE TITLE
Make pattern modal views more consistent

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#41033]
## What problem does this address?

Now that we have a number of pattern experiences within core, we should consider where there are inconsistencies that can be brought closer together. I've outlined the three pattern modal experiences from a block selection (__experimentalBlockPatternSetup), add new page, and pattern explorer:

### From the Query loop block's pattern selector: 
<img width="1590" alt="CleanShot 2022-05-12 at 11 06 37@2x" src="https://user-images.githubusercontent.com/1813435/168107363-b9be1176-6351-4d7b-99ee-5823d40c88ed.png">

### From the new 6.0 core/post-content Add new modal:
( I just added two random patterns to the blockType, so we could see these here)
<img width="1108" alt="CleanShot 2022-05-12 at 11 04 48@2x" src="https://user-images.githubusercontent.com/1813435/168107159-a18629ee-d6ec-4469-80f8-cc6c5517eb85.png">

### From the Pattern Explorer: 
<img width="1590" alt="CleanShot 2022-05-12 at 11 05 02@2x" src="https://user-images.githubusercontent.com/1813435/168107112-9eeaac45-667a-4501-8537-97cc4545b066.png">

### 1. Remove single-view from __experimentalBlockPatternSetup
Take the block pattern selector (__experimentalBlockPatternSetup) and make it back to a grid view (not the current single pattern view). Consider even removing the single view entirely (not sure how helpful that is). 

### 2. Make pattern modal UI consistent
Make the modal UI consistent across all three experiences (width, columns, modal headers, etc). 

### 3. Possibly add another level of categorization for blockTypes
Consider adding a sub-categorization layer to blockTypes, which could be very similar to the current Pattern Explorer UI does (sidebar with search + category)). This would be particularly useful for the "Add new" pattern view, where I could select the type of page to add, instead of seeing an uncategorized list of page patterns. 

This could also be interesting for the Query block's __experimentalBlockPatternSetup use case as well, where the query patterns could be categorized by column count, featured images, grid, etc. (If this is interesting, we should probably spin up another issue relative to this). 

Thoughts? 🤔

**Comment by annezazu** [comment]
Thanks for opening this up @richtabor! At a glance, this seems wildly similar to this issue: https://github.com/WordPress/gutenberg/issues/39308 Mind consolidating feedback there and perhaps closing this one out instead?

**Comment by richtabor** [comment]
Good catch, will do.
