### ISSUE TITLE
Font size control: Try 'Tshirt sizing' labels for variable values

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#41049]
If a theme supplies font size values that are variable they are represented as a 1 - x scale on the control:

<img src="https://user-images.githubusercontent.com/846565/167850359-232d5b55-c9bb-4690-9e72-a783e9420d5b.png" />

This is perhaps suboptimal:

* The most intuitive label is hidden in a tooltip
* The labels in the control feel arbitrary. Are they associated with units? Is "1" small or large?

In https://github.com/WordPress/gutenberg/issues/34345#issuecomment-926577197 'Tshirt sizing' was suggested as an option:

<img width="302" alt="Screenshot 2022-05-13 at 11 04 37" src="https://user-images.githubusercontent.com/846565/168261506-dc907a41-ca62-4c69-917c-25a5a32e7d4f.png">

Assuming it works from an i18n perspective it would be good to try implementing this as it solves the issues above, and feels more familiar.

**Comment by annezazu** [comment]
Can this be closed with this PR merged? https://github.com/WordPress/gutenberg/pull/43074
