### ISSUE TITLE
Empty toolbar element is visible when editing template parts in isolation

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#41047]
### Description

When you create a new template part or edit a template part in isolation, and reduce the browser window width,
there is an empty element with the class ".block-editor-block-contextual-toolbar" at the top of the editable area/ canvas, _inside_ the dark grey border.

Because it is inside the dark grey border, it looks like it is in the editable area and the elements visible border is confusing.

In comparison, when editing a template in isolation in the template editor, this element is _above_ the dark grey border.
When editing a template in the Site Editor, the element is above the canvas.

### Step-by-step reproduction instructions

1. Activate a block theme
2. Go to the Site Editor and select a template part and choose "Edit". Or, create a new template part.
3. Once in the template editor, reduce the browser window width.
4. See that there is a border showing at the top of the editable area.

(In Twenty Twenty-two, using a dark header template part, it will show as a white field above the dark header)

### Screenshots, screen recording, code snippet

Template part:
![image](https://user-images.githubusercontent.com/7422055/168234071-b0603bc9-2846-40ae-9d3d-8fc2ed0cdaf7.png)

Template in template editor:
![image](https://user-images.githubusercontent.com/7422055/168234295-fdcb58c6-1166-4d23-b58c-396d043f5653.png)

Template in Site Editor:
![image](https://user-images.githubusercontent.com/7422055/168234419-83b95ab1-9083-406a-8bcf-90ee0997154c.png)

### Environment info

6.0 RC 2.
With and without Gutenberg trunk
beta tester plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by carolinan** [comment]
Perhaps instead of having the bottom border on block-editor-block-contextual-toolbar, perhaps on this screen, it could be added to the inner element that is only present on the page when the toolbar is populated?

**Comment by ramonjd** [comment]
This is even more obvious now in the site editor "view" canvas mode:

<img width="1606" alt="Screen Shot 2022-12-05 at 1 03 43 pm" src="https://user-images.githubusercontent.com/6458278/205533486-6b01c487-5ead-4c93-9208-043d3627c4ec.png">

> only present on the page when the toolbar is populated?

What about hiding it where no blocks are selected?  Trying that out here: https://github.com/WordPress/gutenberg/pull/46298

**Comment by carolinan** [comment]
@ramonjd If I understood the discussions in the PR correctly it was a partial fix, should this issue be reopened?

**Comment by ramonjd** [comment]
Thanks @carolinan Yeah it ended up targeting the site editor view mode only. I'll reopen.

Maybe https://github.com/WordPress/gutenberg/issues/40450 will go some way to address this issue

**Comment by carolinan** [comment]
I can not reproduce this in 6.3 RC1.
