### ISSUE TITLE
@wordpress/env start command fails when WordPress version is lower than 5.1

### ISSUE THREAD

**Issue by tschortsch** [WordPress/gutenberg#41055]
### Description

When running `wp-env start` with a WordPress core version lower than 5.1 the startup fails with the following error:
```
Error: Could not process the 'wp-config.php' transformation.
Reason: Unable to locate placement anchor.
1
```

The reason for this is that the `--anchor` param used to set the config values is set to `define( 'WP_DEBUG` here https://github.com/WordPress/gutenberg/blob/trunk/packages/env/lib/wordpress.js#L70. This constant was defined without a space in WordPress versions < 5.1 (like this `define('WP_DEBUG` / see: https://github.com/WordPress/WordPress/blob/5.0-branch/wp-config-sample.php#L80) and should be conditionally set depending on the WordPress version used.

### Step-by-step reproduction instructions

1. run `wp-env start` with the following `.wp-env.json` config:
    ```
    {
	    "core": "WordPress/WordPress#5.0"
    }
    ```
1. The step `Configuring WordPress.` fails with the following error:
    ```
    Error: Could not process the 'wp-config.php' transformation.
    Reason: Unable to locate placement anchor.
    1
    ```

### Environment info

- @wordpress/env: 4.6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I tested with `create-block` and could not reproduce it.
The steps are as follows:

- create plugin template: `npx @wordpress/create-block gutenpride --wp-env`
- `cd gutenpride`
- Update .wp-env.json:
```json
{
  "core": "WordPress/WordPress#5.0",
  "phpVersion": "5.6",
  "plugins": [ "." ]
}
```

- In `gutenpride.php`, comment out `register_block_type` (Because the code generated by the latest `create-block` is not compatible with WordPress 5.0.):
```php
function create_block_gutenpride_block_init() {
  // register_block_type( __DIR__ . '/build' );
}
add_action( 'init', 'create_block_gutenpride_block_init' );
```

- `npm run env start`

![wp5 0](https://user-images.githubusercontent.com/54422211/178113210-4bc376f5-d1db-48c0-ba7d-3c55dd594ad4.png)

**Comment by ndiego** [comment]
Using @t-hamano's testing steps, I have been unable to replicate the original issue. @tschortsch are you able to retest using the latest version of Gutenberg to see if this issue still exists?

**Comment by tschortsch** [comment]
Sorry for the late answer. I updated the `@wordpress/env` package to the latest version `5.2.0` and the error seems to be gone. I tried to find the change which fixed it but without luck. So I guess it's all good now, thanks for your investigation!
