### ISSUE TITLE
Documentation: Broken Link in tutorial

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#41069]
### Description

Thank you, @SavPhill for recording this. A great find! 
Originally reported on [trac ticket 55731](https://core.trac.wordpress.org/ticket/55731) 

There are 2 broken links within the ‘Create a basic block’ tutorial in the developer docs:
https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/writing-your-first-block-type/
Both links direct to a 404 page on GitHub.com.
Link Title: **Basic example with JSX build**
Link URL: https://github.com/WordPress/gutenberg-examples/tree/trunk/01-basic-esnext

Link Title: **Basic example plain JavaScript**
Link URL: https://github.com/WordPress/gutenberg-examples/tree/trunk/01-basic

After research, I might have found the right URLs: 
Basic Example ESNext: https://github.com/WordPress/gutenberg-examples/tree/trunk/blocks-jsx/01-basic-esnext
Basic Example Plain JS: https://github.com/WordPress/gutenberg-examples/tree/trunk/blocks-non-jsx/01-basic

### Step-by-step reproduction instructions

n/a

### Screenshots, screen recording, code snippet

n/a

### Environment info

n/a

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by SavPhill** [comment]
Thank you Birgit. I have created a pull request using the links provided.
https://github.com/WordPress/gutenberg/pull/41071#issue-1236074069

**Comment by bph** [comment]
Thank you for getting right on it! And thanks for the first Gutenberg contribution! 🚀   🙌

**Comment by Soean** [comment]
The structure was changed in this PR: https://github.com/WordPress/gutenberg-examples/pull/195

Maybe there are other link which should adjusted, too.

**Comment by gziolo** [comment]
Resolved with https://github.com/WordPress/gutenberg/pull/41071.
