### ISSUE TITLE
Allow setting a Default Opacity for the Cover Block in theme.json

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#41061]
## What problem does this address?
We've found 50% opacity for the Cover block to be too much (too dark of an image). We are always adjusting the opacity down. I was hoping to be able to set a default value for this in theme.json, but it doesn't seem possible.

## What is your proposed solution?
Allow theme.json to set a default Opacity for the Cover Block.

**Comment by mtias** [comment]
Closing as duplicate of #27809.
