### ISSUE TITLE
After inserting gallery from existing images `src` does not match selected image size

### ISSUE THREAD

**Issue by rob006** [WordPress/gutenberg#41072]
### Description

Galleries created from existing images have incorrect URLs - they should have have URL to "large" thumbnail (500x500px) as `src`, but they have link to "full" size.

### Step-by-step reproduction instructions

1. Insert new gallery block using existing images from media library (images are quite large).
2. After inserting gallery, in sidebar settings panel size of image is correct ("duży" = "large"):
![ebff53d2](https://user-images.githubusercontent.com/5972388/168429909-3186bf1e-d141-4c43-be63-ff6890a6b9de.png)
3. However if you check source, inserted images are using URL to full size images, contrary to size displayed in sidebar:
![1e15fd33](https://user-images.githubusercontent.com/5972388/168442785-42c9245e-fd73-4f58-811e-b68861fe0f41.png)
4. If I change size in sidebar to any other size and then go back to "large", URLs are fixed:
![378131c1](https://user-images.githubusercontent.com/5972388/168442826-88495e16-a7e4-4fbe-8a0d-d145ff29166a.png)

Problem affects only galleries from existing images, if I upload new images to gallery, they have correct URLs.

### Environment info

WordPress version: 5.9.3
Gutenberg version: 13.2.0
Browser: Firefox 100

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I was able to replicate this on latest GB trunk.
