### ISSUE TITLE
Post Date popover doesn't respect 'Week Starts On' setting

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#41078]
### Description

The calendar component in the Post Date popover does not respect the 'Week Starts On' WordPress setting.

### Step-by-step reproduction instructions

1. Go to WP Admin → Settings → General.
2. Change 'Week Starts On' to e.g. Monday.
3. Save changes.
4. Create a new post.
5. Open the sidebar and click on _Immediately_ next to _Publish_ to open the Post Date popover.

The calendar component has Sunday as the first day of the week, regardless of the setting that you chose.

### Screenshots, screen recording, code snippet

<img width="387" alt="Screen Shot 2022-05-16 at 11 27 13" src="https://user-images.githubusercontent.com/612155/168504846-374ebcb9-a73c-4b51-a758-4b7170fcdfe3.png">
<img width="366" alt="Screen Shot 2022-05-16 at 11 27 09" src="https://user-images.githubusercontent.com/612155/168504849-4ecc0543-d460-4553-ab4a-d5683fc11955.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sabernhardt** [comment]
This was also [reported on Trac](https://core.trac.wordpress.org/ticket/55826) with WordPress 6.0, and the behavior apparently changed between 5.8 and 5.9 (without the Gutenberg plugin).

* WordPress 5.8: The datepicker week started according to my setting (I tried both Monday and Wednesday).
* WordPress 5.9: The datepicker week started on Sunday when I set it to Monday.

The bug is probably still worth fixing in a minor version.

**Comment by noisysocks** [comment]
From memory, the `react-dates` component we use has a `weekStartsOn` property, so this should hopefully just be a matter of hooking that up to the setting we get from `__experimentalGetSettings()` in `@wordpress/date`.

**Comment by goaround** [comment]
@noisysocks Any chance to get the fix into WordPress 6.0.2? I thought it will be in 6.0.1 but unfortunately, it's not.

**Comment by noisysocks** [comment]
I think it's best to wait until WordPress 6.1 to release this as the fix is not trivial (there are some Core changes that need to be applied at the same time) and the bug is not a recent regression.
