### ISSUE TITLE
React warning when using the DateTimePicker component

### ISSUE THREAD

**Issue by imath** [WordPress/gutenberg#41076]
### Description

When you edit the post date clicking on the post date into the Post sidebar, you get this warning when the DateTimePicker is loaded: 

```
Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: withStyles(CalendarDay), withStyles(CalendarMonth), withStyles(CalendarMonthGrid), withStyles(DayPicker), withStyles(DayPickerNavigation)
```

### Step-by-step reproduction instructions

1. Start a new post
2. Click on the Publish date/mention of the Post sidebar

### Screenshots, screen recording, code snippet

![Capture d’écran 2022-05-15 à 19 46 46](https://user-images.githubusercontent.com/1834524/168486753-de7b65e6-6146-4bd1-a230-9491b8e6d06f.png)

### Environment info

- WordPress 5.9.3
- Chrome 101.0.4951.64

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @imath

The warning probably comes from the library we use for `DateTimePicker`. I can find any references to `withStyles` in the Gutenberg codebase.

Cc @noisysocks

**Comment by noisysocks** [comment]
That's correct @Mamaduka. Here's the upstream `react-dates` issue: https://github.com/react-dates/react-dates/issues/1748

**Comment by Mamaduka** [comment]
Thanks for the confirmation, @noisysocks.
