### ISSUE TITLE
When the navigation block only contains a page list, there are no color options

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#41080]
### Description

Using Wordpress 6.0 RC2, without or without Gutenberg current trunk,
I am seeing a regression in Twenty Twenty-two where the navigation block does not have color options if it only contains the page list block.

This is a problem because it means we cannot change the link color, and because there is a problem with the link color inheritance that makes the submenu item have white text on white background:
https://github.com/WordPress/gutenberg/issues/40908

First I would appreciate a sanity check to confirm if this can be reproduced.

### Step-by-step reproduction instructions

1. Install the WordPress 6-0 nightly using the beta tester
2. Open the Site Editor
3. Select the navigation block: Don't customize the block, it should fall back to the markup in TT2:
```
<!-- wp:navigation {"layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"right"}} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->
```
4. View the block settings sidebar, notice that the color options are missing.

### Screenshots, screen recording, code snippet

![Block sidebar settings, but without the color panel](https://user-images.githubusercontent.com/7422055/168524965-038b79c9-03ad-41ca-9b67-bb26a806d8fe.png)

### Environment info

- WordPress 6.0-RC2-53389
-beta tester plugin
With or without Gutenberg current trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by carolinan** [comment]
Actually there are more panels missing than the colors.
-If I add a link menu item, and then remove it, the missing panels re-appear.

**Comment by draganescu** [comment]
I tested this and it seems the color panel is missing only when the dafault markup menu is selecte. The same configuration manually built (a navigation block with a single page list block child shows the color options.

Later edit: the unsaved blocks output does not place the controls in the inspector. Working on a PR.
