### ISSUE TITLE
Issue in Post Comments Form Block

### ISSUE THREAD

**Issue by KAJALwp** [WordPress/gutenberg#41085]
### Description

When we select Post Comments Form block in post or page, It is display properly in editor-side but it is not showing in front-side. It is happening in all three default themes which is twenty-twenty theme, twenty twenty-one theme and twenty twenty-two theme. I think this block is not supported in latest WordPress.

For better understanding I provide video attachment.

Thanks

### Step-by-step reproduction instructions

1. Go to editor
2. open page or post
3. Add Post Comments Form Block
4. save page or post
5. see preview in front-side

### Screenshots, screen recording, code snippet

https://share.cleanshot.com/pwzlebgkzyyx2mzBRiJ1

### Environment info

WordPress:- 5.9.3
Mac OS:- Monterey 12.3.1
Chrome:- 101.0.4951.54 (Official Build) (arm64)
Theme: Twenty Twenty, Twenty Twenty-one, Twenty Twenty-two
Gutenberg Plugin: 13.2.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi!
Does the post have comments enabled? if not, the form will not show.

**Comment by KAJALwp** [comment]
Hello @carolinan ,

Yes, the post have comments enabled.
I am not able to reproduced the same issue with latest Gutenberg plugin. I think it is resolved with latest version of Gutenberg.

**Environment info**

WordPress:- 5.9.3
Mac OS:- Monterey 12.4
Chrome:- 104.0.5112.79 (Official Build) (arm64)
Theme: Twenty Twenty, Twenty Twenty-one, Twenty Twenty-two
Gutenberg Plugin: 13.9.0

Thanks.
