### ISSUE TITLE
Published posts should autosave

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/gutenberg#4112]
## Issue Overview

When editing a published post, Gutenberg should perform a periodic autosave, matching the behavior of core's wp.autosave: https://github.com/WordPress/wordpress-develop/blob/1b5554e8188f24a0b522d82a2eccb7d098b878bb/src/wp-includes/js/autosave.js#L33

## Expected Behavior
When  editing a published post, the editor should autosave my changes into an autosave revision, matching the behavior of the classic editor. One autosave per user should be created.

The status indicator should also be visible:
![](https://cl.ly/3y3o073h3N3w/Screen%20Recording%202017-12-20%20at%2012.01%20PM.gif)

https://codex.wordpress.org/Revisions#Autosaves

## Current Behavior
Published posts do not autosave.  

## Possible Solution
Hook in early to the save process, and call  `wp_create_post_autosave` when autosaving.

Having autosaves may also be helpful addressing previewing changes on published posts not working.

## Related Issues and/or PRs
https://github.com/WordPress/gutenberg/issues/1773
https://github.com/WordPress/gutenberg/issues/3656
https://github.com/WordPress/gutenberg/issues/4099

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jwold** [comment]
@adamsilverstein one consideration from a user perspective could be to have the status go from:

Save Draft
Saving...
Saved √

That could help with providing confirmation that it's taking care of things in the background.

**Comment by adamsilverstein** [comment]
@jwold thanks for the feedback! 

it actually does that currently- its hard to see because it happens pretty quickly in my screen capture. I'm a little unsure about the language here for published posts. it is not really 'save draft' - for published posts autosaves maybe it should show 'save...saving...saved'?

**Comment by jwold** [comment]
> it actually does that currently

Ahh I missed that! 

> for published posts autosaves maybe it should show 'save...saving...saved'?

If "save" is an action I can click, then yes I think those steps could make sense.

**Comment by adamsilverstein** [comment]
Autosaves are working correctly for drafts and published posts in my branch, but some issues are outstanding:

* We need an autosave message when the page loads and an autosave is available, this would include a link into the revisions screen where the autosave can be restored, similar to the classic editor
* Autosaves should work with localstorage and when the network is not available
* This is a bit of a kludge, a dedicated autosave endpoint might make more sense
* Change the response code so save appears as success

**Comment by adamsilverstein** [comment]
See https://github.com/WordPress/gutenberg/pull/4156

**Comment by danielbachhuber** [comment]
Related #4644

**Comment by danielbachhuber** [comment]
Prior to shipping 3.0, we need to do another pass at addressing feedback in #6257

**Comment by tofumatt** [comment]
My experience of this, testing it out locally is that once published, posts don't autosave until the page is navigated away from, and while there is an autosave then, it isn't loaded when the user returns to the editor.

And actually, while I did get it to autosave again for the screencap, it just didn't do anything:

![2018-06-01 00 20 11](https://user-images.githubusercontent.com/90871/40791155-c18501aa-6531-11e8-971a-a965e8f25e05.gif)

**Comment by adamsilverstein** [comment]
@tofumatt did you test out making some additional changes to the post? it won't save if there are noi changes.

**Comment by aduth** [comment]
>And actually, while I did get it to autosave again for the screencap, **it just didn't do anything:**

Guessing this is mainly the lack of the UI to prompt the user to restore the autosave. See #4218. You can see the autosave did happen if you load the post in the classic editor.

In the process of testing this myself, I also surfaced a related issue #4099.

**Comment by youknowriad** [comment]
I'm closing this one. We can polish the auto-saving experience on smaller issues. 

👏 🎉

**Comment by aduth** [comment]
A couple such issues:

- #7124 State: Autosave should be treated as regular save for same-user draft post 
- #7123 Post Editor: BrowserURL should be resilient to post save failure 
  - Not entirely related to autosave, but came up as part of its implementation
