### ISSUE TITLE
Change the `add_theme_support` feature name for wide images

### ISSUE THREAD

**Issue by justnorris** [WordPress/gutenberg#4113]
Currently to add wide-image support theme developers have to do this:
```
    add_theme_support(
        'gutenberg',
        array(
            'wide-images' => true,
        )
    );
```

That should probably be renamed to something like:

```
add_theme_support('align-wide')
// or
add_theme_support('wide-alignments')
```

cc @youknowriad, @jasmussen

**Comment by youknowriad** [comment]
Two reasons behind this:

 - Avoid the "gutenberg" code name in production
 - The "wide-images" option is not only for images but all blocks supporting wide alignments.

**Comment by justnorris** [comment]
Thanks for the clarification 👍

**Comment by Luehrsen** [comment]
Just to add to the conversation: 

There are a lot of cases, where the availability of wide-alignments cannot be set globally. Sometimes we provide extra Page Templates for that functionality, sometimes it's special post types. 

So having the ability to narrow availability down would be great.

**Comment by maddisondesigns** [comment]
I also mentioned something similar in #2823 a few months ago, that it would be a good idea to rename these, as it's confusing that 'adding support' for 'wide-images' also does the same thing for tables as well.
