### ISSUE TITLE
"Post author name" block not visible on the frontend of a site, on Gutenberg 13.2.0 and higher

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#41135]
### Description

"Post author name" block is not visible on the frontend of a site, on Gutenberg 13.2.0 and higher. I can see it fine on Gutenberg 13.1.0 and Gutenberg 13.0.0. Tested with various themes.

### Step-by-step reproduction instructions

- On a site with Gutenberg 13.2.0, add the `Post author name` block to a page.
- Optionally, mark that block to link out to the author archive.
- Publish the page.
- See that the block is not visible on the live page.

### Screenshots, screen recording, code snippet

`demo` is the author name. Here's how we see it on Gutenberg 13.1.0:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/18581859/169026996-441d9bb8-74db-498f-afe6-02e290d4d4d2.png">

And on Gutenberg 13.2.0:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/18581859/169027031-3829d183-de8b-44d0-a0b3-cb4d2f8c413e.png">

### Environment info

- WordPress 5.9.3
- Gutenberg 13.2.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for reporting the issue, @arunsathiya.

I just followed you're reproduction setups, and I can see the "Post Author Name" block on posts/page. Am I missing something?

**Comment by arunsathiya** [comment]
Thanks for testing, @Mamaduka. Is it visible on the frontend of the post/page for you? It's available on the backend/Gutenberg editor as expected, but it's missing on the frontend after publishing the post/page.

**Comment by Mamaduka** [comment]
> Is it visible on the frontend of the post/page for you?

Correct. Here's the recording:


https://user-images.githubusercontent.com/240569/169040865-7d525a73-4058-4127-a119-d808d0978b51.mp4

**Comment by arunsathiya** [comment]
That's interesting. 🤔 Here's what I see on a site with WordPress 5.9.3 with Gutenberg 13.1.0 (initially) and Gutenberg 13.2.1 (latest version). We can spot that the block is visible while on Gutenberg 13.1.0 but is missing on update to Gutenberg 13.2.0 or higher.

https://user-images.githubusercontent.com/18581859/169043520-0a0eb280-4f56-47bc-96c4-0cd759930e85.mov

**Comment by chad1008** [comment]
I'm also not able to reproduce this. The author block renders on the front end for me regardless of what version I have installed.

This feels very similar to
- https://github.com/WordPress/gutenberg/issues/41067 

In both cases, something related to rendering posts, or parts of a post are working fine in the editor, but not rendering on the front end, and aren't able to be reproduced consistently.

Could be coincidence, but I wonder if there's a trigger somewhere.

**Comment by annezazu** [comment]
cc @tinjure20 perhaps this does match the issue you reported :)

**Comment by tinjure20** [comment]
cc @annezazu, indeed it does!

**Comment by andrewstaffell** [comment]
Also having this issue (as well as the query loop taxonomy filters).

**Comment by tinjure20** [comment]
In my further testing, **Post Author block** is displayed correctly both on the editor and front end. I am still having problem displaying **Post Author name** block on the front end. See screenshots below:

**Editor** (post author name is displayed):
![author-name-block-1](https://user-images.githubusercontent.com/59660253/169288177-eaacf836-aa14-4a1d-a215-edf392bf1e4a.png)

**Front end** (post author name is empty):
![author-name-block-2](https://user-images.githubusercontent.com/59660253/169288346-af9dbcad-f054-440a-8653-7992fb89d782.png)

**Comment by alyssabhogan** [comment]
@tinjure20 Yes, that is true. I originally reported this bug on the WordPress.com forums which (I believe) led to this Gutenberg issue report. The "Post Author" block, with avatar and byline blank, would otherwise be a somewhat suitable work-around for the task of displaying an author's name, except that it doesn't support the "isLink" attribute that the "Post Author Name" block has. This, in effect, leaves no way for sites using only the site editor/FSE (ie: wp.com) to link to an author's archive.

**Comment by Mamaduka** [comment]
I was able to reproduce the issue on my different installation.

#41122 should fix the bug. Props to @dd32.

@annezazu, @chad1008, do you think we should do a minor release that includes this fix?

**Comment by andrewstaffell** [comment]
Thank you! Please do publish the minor release :)

Do we think this will fix #41067? too?

**Comment by Mamaduka** [comment]
Hi, @andrewstaffell

Just tested #41067 and it's fixed as well  🎉

**Comment by andrewstaffell** [comment]
Wow! Awesome! Thanks!

**Comment by alyssabhogan** [comment]
Thank you all!

**Comment by chad1008** [comment]
That's awesome, thanks @Mamaduka! I agree, a minor release sounds like a good idea :)

**Comment by annezazu** [comment]
I think a minor sounds like a good idea (assuming you are talking about a minor GB release in this case). I'm concerned this is happening in RC4 as well based on the previous info that @tinjure20 shared https://github.com/WordPress/gutenberg/issues/24952#issuecomment-1129321450 Going to add this to the 6.0 minor release milestone as a result.

**Comment by Mamaduka** [comment]
The Gutenberg 13.2.2 was released last night. Props to @chad1008.

@annezazu, there's no need to backport the changes into WP. It was only a bug in the Gutenberg plugin.

**Comment by andrewstaffell** [comment]
@Mamaduka @annezazu just for clarification – is Post Author Name supposed to be available in WordPress 6.0?

**Comment by Mamaduka** [comment]
@andrewstaffell, Post Author Name block should be available in WordPress 6.0.

**Comment by andrewstaffell** [comment]
Thank you @Mamaduka for the swift response. That’s what I thought too – it’s been in Gutenberg for ages, and I thought that I had seen that it was going to be in an even earlier release of core – but it seems to be missing from the latest RC.

What’s the best way to check / who’s the best person to ask if this is a simple oversight that can be sorted for the release?

The normal Post Author block doesn’t offer the option to link to the author page so it feels quite important to me that this is released!

**Comment by andrewstaffell** [comment]
Screenshot of 6.0 RC3 files... Post Author Biography is included but Post Author Name is missing. Surely a mistake?!

<img width="502" alt="Screenshot 2022-05-20 at 09 55 52" src="https://user-images.githubusercontent.com/696154/169481502-c2d004ef-2d48-4b28-ab2a-8b056bd2757a.png">

**Comment by Mamaduka** [comment]
@andrewstaffell, that's odd. Based on the Gutenberg version, the block was introduced, it should be included in 6.0.

Unless it was excluded for some specific reason. @annezazu might have more details.

**Comment by andrewstaffell** [comment]
Yes, exactly, the versioning suggests it should be there too. Some oversight or glitch in the build? Any chance of resolving, @annezazu? Thanks both!

**Comment by annezazu** [comment]
Hey all! Check out this convo here about this exact problem/situation:

https://github.com/WordPress/gutenberg/issues/24952#issuecomment-1104550386

>The normal Post Author block doesn’t offer the option to link to the author page so it feels quite important to me that this is released!

You'll see a comment from yours truly there advocating the same as well as context for why the call was made.

**Comment by andrewstaffell** [comment]
@annezazu thanks! I had read that thread, but unless I’m missing or misinterpreting something, there’s no actual explanation of why it’s been omitted, just observation of that fact. Even from the quote from @adamziel.

Considering that Post Author Biography has made it in, are we sure this isn’t just a simple oversight? As @Mamaduka said, the versioning suggests it should be there. 

Who would be the authority on this? Is it possible to double check it ahead of the 6.0 release?

If there is a technical reason for it, fair enough, but I’m yet to find/read one!

**Comment by annezazu** [comment]
I do not have any additional information other than what was in the thread. From my vantage point, this was not included due to lack of a plan forward for blocks that overlap with each other and the fact that these are still seen as experimental (some blocks can exist in the plugin and still not get merged into Core): https://github.com/WordPress/gutenberg/issues/24952#issuecomment-1088681428

>Who would be the authority on this? Is it possible to double check it ahead of the 6.0 release?

This was double checked ahead of the release (that's the convo you see there)! I'll cc @priethor (the other co-release coordinator for 6.0) but, at this point, this was a known decision early on in the release cycle and new features, including new blocks cannot be added in at this stage.

**Comment by andrewstaffell** [comment]
OK! Understood. Thanks for the extra clarification.
