### ISSUE TITLE
Tags not saving until you try 2-4 times

### ISSUE THREAD

**Issue by az4vlad** [WordPress/gutenberg#41163]
### Description

I cannot find a fix for this anywhere. When I insert tags for an article, they pop right back out most of the time without saving. I usually have to type them in 2-4 times to get them to save. And that's after waiting 5-10 seconds first on each one - once I see the similar tags pop up, then I know I can start trying to enter them; if I don't wait, they will never be accepted. It may be endemic to the Wordpress block editor if I had to guess, since it doesn't happen on another site I use that has the classic editor. 

### Step-by-step reproduction instructions

Go to tags on the right side of the Wordpress editor.
Type one in and hit enter or put a comma at the end of it.

### Environment info

Laptop with Windows 10
Wordpress 5.8.4
Popup Themes
Not using Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by jordesign** [comment]
Hi @az4vlad - just checking on this to see if you still see it as an issue when testing with WP6.3?

**Comment by jordesign** [comment]
With no reply and no further reports - I'm going to close this for now. If it does prove to still be a current issue, we can re-open
