### ISSUE TITLE
Keyboard shortcut for selecting text across multiple blocks is missing

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#41168]
### Description

Feature Introduced in https://github.com/WordPress/gutenberg/pull/38892; 

the Keyboard shortcut for selecting text across multiple blocks (without selecting all of the blocks' text) should appear in the [FAQ as MD](https://github.com/WordPress/gutenberg/blame/trunk/docs/explanations/faq.md), [as reference, the FAQ rendered](https://developer.wordpress.org/block-editor/explanations/faq/#are-there-keyboard-shortcuts-for-gutenberg) well as the KeyboardShortcuts modal (triggered in the editor by shift+alt+h) 

As of this writing, it is found in neither the modal or the FAQ. 

- Where should this Keyboard shortcut for the modal live? 
I found some in https://github.com/WordPress/gutenberg/blame/trunk/packages/block-editor/src/components/keyboard-shortcuts/index.js but not all are there and I don't know where else would be more appropriate. 

- For the FAQ, should it live in the [selection shortcuts ](https://github.com/WordPress/gutenberg/blob/trunk/docs/explanations/faq.md#selection-shortcuts)? 

To fix: 

- [ ] Add the shortcut to the FAQ
- [ ] Add the shortcut to the KeyboardShortcuts modal

### Step-by-step reproduction instructions

1. open editor 
2. shift+alt+h 
3. look for that shortcut
### Environment info

gutenberg 13.2.1 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by markhowellsmead** [comment]
Shift + down used to select all blocks sequentially; since 6.0, this is no longer possible.

**Comment by bengreeley** [comment]
Created a PR that adds the missing documentation at https://github.com/WordPress/gutenberg/pull/43164

**Comment by ryanwelcher** [comment]
@bengreeley it looks like the PR is ready to be merged. Is there anything blocking moving it forward?

**Comment by ellatrix** [comment]
Look like this has been address in https://github.com/WordPress/gutenberg/pull/43164. Please reopen if I'm misunderstanding or mistaken. :)
