### ISSUE TITLE
Text formatting for selected text across blocks reverts when block is clicked (6.0 RC3)

### ISSUE THREAD

**Issue by blogtutor** [WordPress/gutenberg#41164]
### Description

I just installed 6.0 RC3 on a dev site, and tested out the new feature that allows us to select text across multiple blocks at once.
When I select text, and then press CTRL-b to bold it, it all looks bold while it's selected. Once I then click back into either block, the bold disappears in that block.

I also see similar behavior with CTRL-i for italic.

(This behavior is on Chrome. On Firefox, Ctrl-b opens bookmarks and ctrl-i opens Page Info and does not change the formatting at all.)

### Step-by-step reproduction instructions

1. Create two paragraph blocks with text, in the Chrome browser.
2. Using the mouse, click+drag to select text across both paragraphs.
3. Press `ctrl-b` or `ctrl-i` to change the text formatting.
4. Click in either text block, outside the selected area. That will undo the formatting; click in the other text block and it will undo the formatting in that block.

### Screenshots, screen recording, code snippet

Here's a video that I hope is helpful: https://share.nrdp.rs/ApuXBrEq

### Environment info

Tested on 6.0 RC3 with the Twenty Twenty-Two Theme, and no active plugins. Chrome browser Windows 10.

I do not have the Gutenberg plugin installed; this is just 6.0 RC3.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
Thanks for reporting this @blogtutor! We don't have a good way to handle this properly right now as multi block selection might include other non text blocks. The resolution for now is to disable the shortcuts.

**Comment by blogtutor** [comment]
Thanks @ntsekouras.  So I'm curious then, what's the point of being able to do partial selections across multiple blocks?  Seems to me the most common use case would be selecting text across two paragraph blocks, but maybe I'm missing something?  (and if that's the case, maybe shortcuts could be disabled for other blocks, but not paragraphs?)

**Comment by ntsekouras** [comment]
>So I'm curious then, what's the point of being able to do partial selections across multiple blocks? Seems to me the most common use case would be selecting text across two paragraph blocks

Actually the restriction right now is about formatting and this is a quite complex issue that we're going to find a solution soon. With partial selection you can still `cut/copy` the partial selected blocks with anything in between, you can press `delete, enter, etc..` and merge blocks if eligible (the first selected block should be able to merge with the last selected block).

Also after debugging this (for a while now 😅 ) it's not about shortcuts, but it's about browser default behavior on some shortcuts.

**Comment by blogtutor** [comment]
Ah! Very cool; I definitely hadn't considered all those functions.

And I'd imagine the different browser behaviors is infuriating!  But sounds like you're closing to cracking that, which is awesome. Thanks!
