### ISSUE TITLE
Can't retrive my block's attribute when using server-side rendering 

### ISSUE THREAD

**Issue by sycatsce** [WordPress/gutenberg#4117]
## Issue Overview

The $attributes parameter of my block server-side rendering function keeps returning me an empty array, even after saving the block in the editor.

Wordpress : v4.9.1
Gutenberg : v1.9.1
## Expected Behavior

I expected to retrieve my block's attributes from the $attributes parameter.

## Current Behavior

The $attributes parameter returns an empty array

## Possible Solution

It looks like the callback function is called before the block is actually saved in the editor.

## Code 

**block.js**
```
var el = wp.element.createElement;
var registerBlockType = wp.blocks.registerBlockType;
var Editable = wp.blocks.Editable;

registerBlockType( 'some/block', {
	title: 'Header',
	icon: 'universal-access-alt',
	category: 'layout',
	attributes:
	{
		title: {
			type: 'array',
			source: 'children',
			selector: '.parTitle'
		},
		test: { value : "17" }
	},

	edit: function( props ) {
		
		return ( 
			el('div', { className:  props.className },
				el('h2', {}, 'Title'),
				el( Editable,
					{
						tagName: 'div',
						className: 'parTitle',
						placeholder: 'Write title here...',
						value: props.attributes.title,
						onChange: function( value ){ props.setAttributes( { title: value } )},
				        })
			)
		)
	},
	save: function( props ){
		return null;
	}
})
```

**index.php**
```
function gb_block_header_render( $attributes ) {
	return count($attributes); 
}

register_block_type( 'some/block', array (
	'render_callback' => 'gb_block_header_render',
));
```

**Comment by youknowriad** [comment]
The attributes serialized into the block's content are not parsed server-side. Only the comments attributes are. There are some explorations about moving all the parsing server-side. I'm closing this as duplicate fo #2751

**Comment by ngdangtu-vn** [comment]
> Only the comments attributes are

I don't understand what do you mean about the "comments attributes". But I fix my problem by make sure do not use `source` & `selector` in each attribute. Seems like what you said, any attribute with `source` & `selector` will be serialized to post_content. So the best way if anyone needs the block to be render from server side is using only `type`, `default`. (I haven't tried `enum` so I'm not sure)
