### ISSUE TITLE
Gallery block: allow setting separate row and column gap

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#41174]
## What problem does this address?

With the changes in #41125 it is now possible to set the row and column gap settings independently in the block style attributes  so it would be good to enable this option in the block styles UI 

An [example of this working in the UI can be seen here](https://github.com/WordPress/gutenberg/pull/41125#issuecomment-1131142120).

**Comment by andrewserong** [comment]
I've opened up a PR to opt-in to the separate row / column values in: https://github.com/WordPress/gutenberg/pull/41175
