### ISSUE TITLE
[Documentation] Incorrect URL 

### ISSUE THREAD

**Issue by SavPhill** [WordPress/gutenberg#41187]
### Description

In the following documentation page regarding Coding Guidelines:

https://developer.wordpress.org/block-editor/contributors/code/coding-guidelines/  

Under the section Coding Guidelines, the link titled WordPress Coding Standards points to the WordPress Coding Standards for _JavaScript_ subdirectory:

https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/ 

The correct url would be the previous directory as shown in the breadcrumbs:

https://developer.wordpress.org/coding-standards/wordpress-coding-standards/

### Step-by-step reproduction instructions

Visit https://developer.wordpress.org/block-editor/contributors/code/coding-guidelines/  

Under the section Coding Guidelines, follow the link titled WordPress Coding Standards 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by alexstine** [comment]
Merged the fix.
