### ISSUE TITLE
Toggle indicator Button on  Document Panel Tab

### ISSUE THREAD

**Issue by monika-12** [WordPress/gutenberg#4120]
**Issue Overview**
On Document Panel Tab - "Right Toggle" indicator button added to display content but I think it should "Down Toggle" indicator button because the content(area) expanded below the title so the arrow is pointing wrong.

**Steps to Reproduce (for bugs)**
1. Go to Edit Page section
2. Click on Document Tab
3. Check Toggle Indicator Button on any Panel Body
4. It is pointing Right Arrow instead of Down Arrow

Provide what browser you are using and any other specifics to your setup
I am using Firefox Browser.

**Expected Behavior**
It should display "Down" toggle indicator button because the content expanded below the heading not the right so it should be down arrow.

**Current Behavior**
Currently it display "Right Toggle" indicator it means it should expanded content right to the heading panel.

**Screenshots / Video**

1.Current Behavior
![toggle-indicator-current](https://user-images.githubusercontent.com/17018981/34253571-324935f2-e66e-11e7-9e66-81ede93a0bf1.png)

2.Expected Behavior
![toggle-indicator-expected](https://user-images.githubusercontent.com/17018981/34253569-31fa2660-e66e-11e7-9963-130335f6f694.png)

**Comment by karmatosed** [comment]
The section that is open isn't the status and visibility, so it makes sense that it shouldn't be open.

![2018-01-04 at 11 34](https://user-images.githubusercontent.com/253067/34561723-52f888ae-f143-11e7-95d5-9d105e21545c.png)

The above is what I see and this makes sense. For now, I am going to close this.

**Comment by monika-12** [comment]
Hey @karmatosed 
I am not mentioning about status and visibility tab. It's about all tabs and mentioned here about "Toggle Indicator" not the particular tab.

**Comment by karmatosed** [comment]
I am referring to the section you highlighted. I do understand what you are suggesting but in this case I think it's valid as a pattern.
