### ISSUE TITLE
Duplicate query in render_block_core_post_template

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#41200]
### Description

In `render_block_core_post_template` function, if using `use_global_query`, an unnecessary query is run. The code should try and reuse the global wp_query where possible. 

https://github.com/WordPress/gutenberg/blob/57a1daf7edad34c842181e28a60efbeab14b8fc1/packages/block-library/src/post-template/index.php#L43-L63

### Step-by-step reproduction instructions

Active block theme. 
View query monitor. 

### Screenshots, screen recording, code snippet

<img width="1134" alt="Screenshot 2022-05-20 at 12 40 25" src="https://user-images.githubusercontent.com/237508/169521059-4166f0e1-8d7d-4011-a85f-993c6e90776d.png">
<img width="1132" alt="Screenshot 2022-05-20 at 12 40 14" src="https://user-images.githubusercontent.com/237508/169521063-950eb70b-1b03-4305-973d-bbee54909385.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by danieldudzic** [comment]
Hey @spacedmonkey,

I'm trying to replicate this, and indeed I got the Query Monitor plugin to flag `render_block_core_post_template` as a 'potential troublemaker', but I'm struggling to understand where the duplication is happening. Would you mind elaborating a bit more on the nature of the issue? I'd really appreciate it 🙏

**Comment by spacedmonkey** [comment]
@danieldudzic The issue is this line 

https://github.com/WordPress/gutenberg/blob/57a1daf7edad34c842181e28a60efbeab14b8fc1/packages/block-library/src/post-template/index.php#L63

Another `WP_Query` instance is being created, when it does not need to. There is one created as a `global $wp_query;` with the query already run.  So if we did this. 

```
if ( $use_global_query ) {
		global $wp_query;
		...
               $query = $wp_query;
} else{
	$query = new WP_Query( $query_args );
}

if ( ! $query->have_posts() ) {
	return '';
}
```

It would avoid it being re-run.

**Comment by danieldudzic** [comment]
Hi @spacedmonkey,

Thank you for clarifying.

I have tried the following:

```
	if ( $use_global_query ) {
		global $wp_query;
		if ( $wp_query && isset( $wp_query->query_vars ) && is_array( $wp_query->query_vars ) ) {
			// Unset `offset` because if is set, $wp_query overrides/ignores the paged parameter and breaks pagination.
			unset( $query_args['offset'] );
			$query_args = wp_parse_args( $wp_query->query_vars, $query_args );

			if ( empty( $query_args['post_type'] ) && is_singular() ) {
				$query_args['post_type'] = get_post_type( get_the_ID() );
			}
		}
		$query = $wp_query;
	} else {
		$query = new WP_Query( $query_args );
	}

	if ( ! $query->have_posts() ) {
		return '';
	}
```

But it didn't really take care of the 'potential troublemaker' warning in the Query Monitor. 🤔

**Comment by spacedmonkey** [comment]
@danieldudzic In my testing, it did get rid of two queries on the page. There are a number of other places that generate duplicate queries, which I am also working on in core. 

See this screenshot. 

#### Before
<img width="179" alt="Screenshot 2022-06-23 at 19 09 54" src="https://user-images.githubusercontent.com/237508/175527304-39042b58-b19f-42db-bd5f-a30cd570dcf6.png">

#### After
<img width="210" alt="Screenshot 2022-06-23 at 19 08 29" src="https://user-images.githubusercontent.com/237508/175527386-c693306e-ce70-40d0-b8bd-30a45624607e.png">

I have created a PR for this issue - https://github.com/WordPress/gutenberg/pull/41943

**Comment by spacedmonkey** [comment]
Closing as this duplicate queries have been fixed upstream.
