### ISSUE TITLE
Search Block: Add flexible query attributes

### ISSUE THREAD

**Issue by LukaszJaro** [WordPress/gutenberg#41204]
## What problem does this address?

I can't do simple things like:

- Exclude/include categories, posts, etc
- Set post type (page, post, custom post type, etc)
- Order of search results

Not so simple things:

- Search by post title only
- Search published date(i.e, May 20th)
- Control whether to search in title, content, meta or all

## What is your proposed solution?
Add these settings in the block settings panel.

**Comment by Mamaduka** [comment]
Hi, @LukaszJaro

You can create search block variations and preset query attributes. See #40585 for more details.

@tomasztunik, is there a general tracking issue for search query attribute UI and improvements?

**Comment by tomasztunik** [comment]
@Mamaduka I was planning to set it up when I'm back from my trip next week - if it was more pressing someone would have to take it over.

And whoa! what were the odds that someone would post a related issue right after getting the first step for this in! :) 

@LukaszJaro - the ability to control query params via block variations will go live with Gutenberg 13.4. Also, it will be later easy to convert these custom variations to regular search blocks once UI for these features goes live. Variations are 100% compatible with their parent block and once you unregister the variation, the variation block simply becomes the parent block with the given variation attributes set.

**Comment by LukaszJaro** [comment]
Wow that's great, thank you @Mamaduka and @tomasztunik 

Looks like June 1st is release date for 13.4 so I'll be sure to test this out then, thank you for the great work!

**Comment by ndiego** [comment]
Just stumbled upon this issue. Can this now be closed since https://github.com/WordPress/gutenberg/pull/40585 is merged?

**Comment by Mamaduka** [comment]
There's also a new article on extending the query block - https://make.wordpress.org/core/2022/10/10/extending-the-query-loop-block/.

**Comment by LukaszJaro** [comment]
Thank you for this addition, has been very useful! The accompanying article is also very informative. Looking forward to the interface to add these options.
