### ISSUE TITLE
Create a control to make Archives block's dropdown label invisible

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#41208]
Follow-up to #11002, as suggested on [Trac #54962](https://core.trac.wordpress.org/ticket/54962#comment:4)

## What problem does this address?

Some people may not want the label showing, and it had not been visible with WordPress 5.8. (The Categories dropdown still does not show the label.)

## What is your proposed solution?

Create an _option_ to add the `screen-reader-text` class to the label.

![Archives block options, with dropdown selected](https://user-images.githubusercontent.com/17100257/169568864-a3adac4b-1ad9-4cb9-91d6-bd1ff484df6a.png)

**Comment by carolinan** [comment]
Should this use a similar toggle in the toolbar as the search block?
![The search block has an option named "toggle search label", which is in the block toolbar](https://user-images.githubusercontent.com/7422055/176373695-809eed70-61c7-4cbf-aa4c-0b66a438c76b.png)

**Comment by sabernhardt** [comment]
That might work, though I think I would prefer an option in the sidebar. 

This toggle would require selecting "Display as dropdown" first, then the user would choose whether to show the label. Placing the conditional option in the sidebar, near the option they selected, is probably better than returning eyes/focus to the block toolbar to notice what changed.
