### ISSUE TITLE
Typography tools: make it possible to customize paragraph spacing and indent

### ISSUE THREAD

**Issue by beafialho** [WordPress/gutenberg#41227]
In the context of style variations (_Related: #40988 and #35619_), considering elements that can vary between them, it would be nice to have a way to customize paragraph spacing and indent in the editor, as they can be a differentiator element between variations.

https://user-images.githubusercontent.com/65220155/169794366-b24b1444-d4a5-469b-a1b8-d760b51d28a3.mp4

**Comment by mtias** [comment]
I think we have this covered in #37462.

**Comment by beafialho** [comment]
Closing as it's duplicated.
