### ISSUE TITLE
Styles welcome guide's button styling is not consistent

### ISSUE THREAD

**Issue by juhi123** [WordPress/gutenberg#41226]
### Description

I couldn't understand the logic behind having different styling for `Previous` and `Get Started` button than `Next` button, I believe buttons should have the same styling,
The next button has color `1386bf` and font is bold, raised a PR to fix that

### Step-by-step reproduction instructions

1. Go to `Site Editor`
2. Click on `Styles`
3. In the sidebar panel, click on `Welcome Guide`

### Screenshots, screen recording, code snippet

![previous-getstarted-button](https://user-images.githubusercontent.com/8724401/169791899-339c628b-4ca6-40f1-a828-94b932deb5e8.png)

![next-button](https://user-images.githubusercontent.com/8724401/169791921-cca6c416-202b-407d-8a78-640748687bd0.png)

### Environment info

- WordPress 6.0 RC 4
- macOS Monterey

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
This is no longer reproducible in WP6.3 - I'm seeing different button style now.

<img width="309" alt="Screenshot 2023-09-05 at 2 45 09 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/c8f76906-8f44-4484-880d-982acc6a919f">

To my mind this is a deliberate stylistic/focus difference so I think this can be closed.
