### ISSUE TITLE
Site editing: Make it possible to edit site in different screen sizes

### ISSUE THREAD

**Issue by beafialho** [WordPress/gutenberg#41238]
Currently, it is not possible to edit styles and layout specifically for tablet/mobile, settings will always be the same as in desktop.

While our site/theme should automatically adapt to mobile, it would be great to be able to:
- adjust typography sizes and layouts for individual breakpoints as needed
- set mobile typography styles site-wide so we don't have to do it in every page

Related and relevant here as well: #40870 and #41237

**Comment by mtias** [comment]
There are already a couple issues describing this:

- #19909.
- #20244.
