### ISSUE TITLE
Add font families to Global Styles + consider a design stylesheet

### ISSUE THREAD

**Issue by beafialho** [WordPress/gutenberg#41237]
@henriqueiamarino and I were chatting earlier about how when we access styles we can see “Typography”, “Colors” and “Layout”, but when we click the first one, we can’t select different type families. That's only possible if you travel back to the Customizer, which is already omitted in some themes.

Additionally, it would be nice to see some sort of visual stylesheet where we could edit all parameters and save these styles in order to build themes faster. Seeing all your headings and paragraphs settings in one place would help tremendously when we're building a theme in the editor. 

Here’s a reference of what [Semplice](https://www.semplice.com/custom-typography) does to manage typography:

https://user-images.githubusercontent.com/65220155/169816487-05eef522-a793-4764-8e18-81398aab9e65.mp4

Likely related to #38534

**Comment by jasmussen** [comment]
I wonder if the esign stylesheet is partially addressed by the Style Book?

**Comment by beafialho** [comment]
Yes @jasmussen, it is in part. I do see a few problems with the Style Book as it is, but maybe I can mention them in another issue.

**Comment by beafialho** [comment]
Closing this as it has been addressed.
