### ISSUE TITLE
The Theme Details Page Options Need to be Streamlined

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#41247]
## What problem does this address?

It is difficult for new users to spot all the options available to manage a theme on the theme details page.

## What is your proposed solution?

![image](https://user-images.githubusercontent.com/12677420/169863773-a273c401-78a7-4ecb-bb33-57ec45f320ee.png)

- Put all theme management options in a single location in the UI instead of having them multiple locations. This will help users locate the option they are looking for quicker. The suggested area of placement for the options is the blue area in the image.

**Comment by justintadlock** [comment]
This is a core WordPress issue and unrelated to Gutenberg.  Please open a new ticket on Trac so that it gets in front of the right people: https://core.trac.wordpress.org/

**Comment by deborah86** [comment]
@justintadlock I created the ticket here: https://core.trac.wordpress.org/ticket/55823#ticket

**Comment by justintadlock** [comment]
Thanks! Closing this one out since it's now listed as a ticket on Core Trac.
