### ISSUE TITLE
Add the Ability to Delete Multiple Themes on the Themes Page

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#41248]
## What problem does this address?

A user might have multiple themes installed. Clicking on each theme to delete it might be tedious.

## What is your proposed solution?

Add the ability to delete multiple themes on the themes page.

**Comment by justintadlock** [comment]
This is a core WordPress issue and not related to Gutenberg.  Please open a new ticket on Trac so that it gets in front of the right people: https://core.trac.wordpress.org/

**Comment by deborah86** [comment]
@justintadlock I created the ticket here: https://core.trac.wordpress.org/ticket/55822#ticket

**Comment by justintadlock** [comment]
Thanks. Closing this ticket in favor of the core issue.
