### ISSUE TITLE
The Manage Themes Screen Needs to Indicate Clear User Actions

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#41244]
## What problem does this address?

A new user might not understand the difference between uploading a theme and browsing the theme repository. To make it easier for new users to use WordPress, user actions should be clearer.

## What is your proposed solution?

![image](https://user-images.githubusercontent.com/12677420/169856139-bdf7efe4-599f-4bf2-8184-7a1388c679d4.png)

- The Add New isn't descriptive of the action the user should it. The text on the button should be changed to "Browse WordPress Themes".
- Manage Themes should be changed to My Themes to indicate to the user these are the themes they have installed on their website.
- A button should be added that allows the user to upload a theme. It should say "Upload Theme".
- The button that says "Add New Theme" should be changed to "Browse WordPress Themes" so the user understands the button is not for uploading WordPress themes but to browse themes.

**Comment by justintadlock** [comment]
This repository is for Gutenberg tickets.  I recommend adding this ticket to the WordPress Trac system: https://core.trac.wordpress.org/

**Comment by adamwoodnz** [comment]
@deborah86 please raise a ticket with https://core.trac.wordpress.org/ and close this, or respond if you disagree

**Comment by deborah86** [comment]
I created the ticket here: [The Manage Themes Screen Needs to Indicate Clear User Actions](https://core.trac.wordpress.org/ticket/55878#ticket)
