### ISSUE TITLE
Fix the WordPress Status Bar to Make Actions Clearer to the User

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#41243]
## What problem does this address?

New users might not understand what the buttons mean on the status bar because they are unclear. The buttons should be labeled properly to make them easier to understand.

## What is your proposed solution?

![image](https://user-images.githubusercontent.com/12677420/169851851-647601cc-56b3-43a5-bbff-ae100ac042d4.png)

- Next to the Dashboard icon, the menu should be removed and it should just say Dashboard
- The website name should be moved in front of the dashboard icon not behind it
- To keep consistency, the word "Comments" should be placed behind the picture of a speech bubble instead of just the number. This will also make it clearer to the user that clicking will take the user to the Comments section.

**Comment by justintadlock** [comment]
Features/Bugs related to the admin toolbar should be posted over on the WordPress Trac: https://core.trac.wordpress.org/

Leaving this ticket open, pending feedback from the OP if there is something specific to Gutenberg or block editor toolbars.

**Comment by deborah86** [comment]
@justintadlock I posted the suggestion here:  https://core.trac.wordpress.org/ticket/55795#ticket

**Comment by justintadlock** [comment]
Thanks! I'm closing this ticket since it's specific to WordPress core and there is a new one in the right place.
