### ISSUE TITLE
Site Editor & Templates Roadmap

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#41241]
![image](https://user-images.githubusercontent.com/548849/152579101-53290df4-3067-45bd-b5f6-b7b5eca964ce.png)

---

The largest amount of work is around clarifying the user experience of editing global concepts (styles, templates, navigation) from specific site content. To address some of these issues a few explorations are underway:

- [x] #36667
- [x] #37001 (Needs discussion.)
- [x] #39293

This is connected with the introduction of a view mode that allows the user to navigate around the site instead of selecting blocks:

- [x] #23328

Finally, we need to introduce a better loading flow for the site editor to avoid waterfall effects and the feeling of fragility.

 - [x] #35503 ⚠️

## Creating Templates & Parts

Expanding the ability to create and manage templates is also a crucial component.

- [x] #42520 ⚠️
- [x] #37407 ⚠️
- [x] #41060 
- [x] #40791 ⚠️
- [x] #27597
- [ ] #42088
- [ ] #41947
- [x] #42130

## Interface

- [x] #50392
- [x] #36951
- [x] #44710
- [x] #37220 
- [x] #36303
- [x] #29296.
- [ ] #29295.
- [x] #41437.
- [x] #34737.
- [ ] #41947.
- [x] #32163
- [x] #31748
- [ ] #41399
- [x] #42154
- [x] #42226
- [x] #30029

## Editing Flows

This includes the perspective of editing templates from the post-editor.

- [ ] #19259
- [x] #27847
- [x] #27848
- [x] #41258
- [ ] #41257
- [x] #41452
- [x] #41449
- [x] #42767
- [x] #40184
- [ ] #48377

## wp-admin

We can begin to provide access to template editing from existing wp-admin management views

- [x] #17099
- [x] #41714
- [ ] #41715
- [ ] #41716

**Comment by zteil** [comment]
#46345

**Comment by ghorivipul97** [comment]
Hello @mtias @annezazu  anyone assign task to me? 
I' ready to start to work on it.

**Comment by annezazu** [comment]
Hi @ghorivipul97! I recommend diving into these tasks to start: https://github.com/orgs/WordPress/projects/96/ Everything listed for needs dev should be straightforward to address. Feel free to ping me on WordPress slack if you want to chat further. I'm also @annezazu there.

**Comment by mtias** [comment]
Closing this milestone and set of iterations.
