### ISSUE TITLE
Initial Social Media Block Not Changing When Default is Changed

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#41256]
### Description

The initial social media block does not change its settings when the default settings are updated. Subsequent social media blocks work fine.

### Step-by-step reproduction instructions

1. Add the social media block to the page
2. Add the icon to the block
3. Change the default style of the block

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/12677420/169880950-ab973f59-907b-447b-8586-03df9717f424.png)

### Environment info

- WordPress Current version: 5.9.3, Gutenberg is not installed, 2022
- Microsoft Edge
- Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by justintadlock** [comment]
The default style picker has been removed (won't be in WP 6.0) and is planned to be reintegrated into the Global Styles feature in the future.  See: https://github.com/WordPress/gutenberg/issues/41017

**Comment by Mamaduka** [comment]
I think we can close this issue. Like @justintadlock mentioned, the default styles will be part of the Global Styles in the future.
