### ISSUE TITLE
Site editor: Align template part creation with regular template creation

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#41255]
Currently template and template part creation UIs do not match:

### Add template
This flow uses a dropdown menu:
<img width="1326" alt="Screenshot 2022-05-23 at 18 58 50" src="https://user-images.githubusercontent.com/846565/169879461-9c54a9a4-ec97-48a0-9947-dffa91b875d3.png">

### Add template part
This flow goes directly into a modal:
<img width="1402" alt="Screenshot 2022-05-23 at 18 59 13" src="https://user-images.githubusercontent.com/846565/169879541-7c89dcf9-3588-4337-a6fa-3dbb45244bd0.png">

We should update the template part creation flow to match the template creation one like so:

<img width="965" alt="Screenshot 2022-05-23 at 19 00 45" src="https://user-images.githubusercontent.com/846565/169879733-bac6e3cc-db92-489b-b407-a211fde9e3b4.png">

Asking the user to immediately name the template part is an unnecessary friction. Depending how they choose to proceed when presented with patterns we can either: 

1. Use the name of the selected pattern as the template part name.
2. Use "Untitled Header" when they elect to start blank.

**Comment by jameskoster** [comment]
Just noting that this may not be necessary if we implement https://github.com/WordPress/gutenberg/issues/36613.

**Comment by jordesign** [comment]
As of WP6.3 both Template Part/Pattern and Template Add flows use a modal - so I'll close this as resolved.
