### ISSUE TITLE
Add the Ability to Allow/Disallow Auto-Update for Multiple Themes on the Theme Page

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#41250]
## What problem does this address?

Right now, a user has to click on each individual theme to allow auto-update. If the user has multiple themes installed, this can be tedious.

## What is your proposed solution?

My proposed solution is to have the option to allow/disallow auto-update for multiple themes on the theme page.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for requesting! This issue affects all WordPress installations not just ones using Gutenberg so it would be more appropriate to post on [Trac, the general WordPress issue tracker](https://make.wordpress.org/core/handbook/contribute/trac/). 

Fortunately, there is already an [issue made for this](https://core.trac.wordpress.org/ticket/55321) although it is poorly named and the issue's author suggested the feature of setting auto-update for multiple themes at a time [in this comment](https://core.trac.wordpress.org/timeline?from=2022-03-15T23%3A09%3A51Z&precision=second). 

You can comment in that issue and follow progress if you login to your wordpress.org account. 

(And thanks for noting; I hadn't known that you could enable a theme to auto-update!)

**Comment by deborah86** [comment]
I created the ticket here: [Add the Ability to Allow/Disallow Auto-Update for Multiple Themes on the Theme Page](https://core.trac.wordpress.org/ticket/55879#ticket)
