### ISSUE TITLE
How to convert old posts content portions to Gutenberg blocks?

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#4126]
Noticed during WordCamp Rome contributor day users testing session. /cc @johnbillion 

Not sure if this has been already discussed of if there's already an issue about it. Please do feel free to close if I've missed it.

When editing an old (pre-existing, created with the classic editor) post with Gutenberg, all the content is within a "Classic" Gutenberg block. This is a wise move to preserve existing content integrity: that content was created with TinyMCE and it makes perfectly sense to edit it with TinyMCE by default.

However, seems there's no easy way to convert _single portions_ of a Classic block to other Gutenberg blocks. As far as I see, there's only one "Convert to blocks" option in the ellipsis menu:

![screen shot 2017-12-21 at 15 00 43](https://user-images.githubusercontent.com/1682452/34258883-4ad87492-e660-11e7-915c-33a6ddffcef6.png)

which has two issues:
- it's not so discoverable (we haven't found this option during the users testing session)
- it parses and converts _all_ the content in separate blocks: there's no way to convert single pieces of content

As a user, I might want, for example, to split a single paragraph in a paragraph block to take advantage of the new formatting features. Or split a single image in an image block to make it full width, etc.

As far as I can see, the only option now is to manually cut and paste single pieces of content in new blocks. 

At the very least, I'd propose to make the "Convert to blocks" option easily discoverable. Maybe put it in the TinyMCE toolbar? (maybe as a TinyMCE custom button?)

I'd also propose to consider a way to convert _sngle pieces_ of a Classic block in separate blocks, thus leaving to users the choice about what to convert and what not.

**Comment by mtias** [comment]
> At the very least, I'd propose to make the "Convert to blocks" option easily discoverable. Maybe put it in the TinyMCE toolbar? (maybe as a TinyMCE custom button?)

Definitely, the main point was adding the functionality, now we need to figure out the best ways to present it. There have been discussions about showing a notice to convert an old post, doing it automatically, etc. I want to be a bit more confident in the transformation before exposing it more, but definitely something that needs to be more visible.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1516901018000312)._

**Comment by danielbachhuber** [comment]
> I'd also propose to consider a way to convert sngle pieces of a Classic block in separate blocks, thus leaving to users the choice about what to convert and what not.

Does the user _need_ this option? Given the UX and technical complexity of producing such a feature, couldn't you convert the entirety into blocks, and then change each created block individually as you see fit?

**Comment by jasmussen** [comment]
Per Daniel's comment, I'm going to close this ticket for now. The behavior has been in master for a while, and though there are separate actionable issues for issues that have popped up (like #4926 and #4859). We can revisit if the issue reappears.
