### ISSUE TITLE
Gallery block - adding 7 images in 7 columns full width and block spacing 1 - bug

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#41275]
### Description

I noticed that in the Gallery block when adding 7 images in 7 columns, full width having the images side by side it looks like this with the default block spacing.

Frontend.
![Screenshot 2022-05-24 at 10 50 27](https://user-images.githubusercontent.com/5323259/169991336-8d2f043a-7547-47d8-be3b-37202cfe12df.jpg)

Changing block spacing to 1. 
Backend.
![Screenshot 2022-05-24 at 10 49 06](https://user-images.githubusercontent.com/5323259/169991988-9643223c-b441-455d-9016-b910d0603f8c.jpg)

Frontend does not show the correct block spacing and one image is added below the other gallery images.
![Screenshot 2022-05-24 at 10 51 58](https://user-images.githubusercontent.com/5323259/169991733-1bd9d95e-13fc-4c69-ab8b-823eb5e9c27d.jpg)

@glendaviesnz 

### Step-by-step reproduction instructions

1. Add a Gallery block.
2. Add 7 images.
3. Add 7 columns.
4. Change alignment to full width.
5. See the result on the backend and frontend.
6. Add block spacing of 1.
7. See the result on the backend vs frontend.

### Screenshots, screen recording, code snippet

-

### Environment info

WordPress 5.9.3
Gutenberg plugin 13.2.2
Theme: Twenty Twenty Two.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I wasn't able to replicate this on WP 6.0 and GB 13..3
<img width="652" alt="Screen Shot 2022-05-30 at 2 47 58 PM" src="https://user-images.githubusercontent.com/3629020/170908173-024546c9-14ee-41b7-a42e-2fa8ab10d34d.png">

Do you get the same issue in 6.0?

**Comment by paaljoachim** [comment]
Thanks for checking Glen!

Hmm I am still getting this in 6.0. I got to check more into it, and see if I figure out what is going on.

**Comment by paaljoachim** [comment]
I will close this issue for now.
