### ISSUE TITLE
When removing core pattern, allow theme.json pattern slugs to be listed in inserter

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#41282]
## What problem does this address?
At the moment, `remove_theme_support( 'core-block-patterns' ); is an all or nothing with allowing pattern directory patterns to be viewed in the inserter. 
Being able to still use the theme.json registration of pattern via slugs from the pattern directory, allows a curated list of patterns and more granular control. 

## What is your proposed solution?
The theme developer would set in functions.php `remove_theme_support( 'core-block-patterns' );` 
and set in theme.json the list of pattern allowed: `"patterns": [ "short-text-surrounded-by-round-images", "partner-logos" ]`

There could be a check that if there is a theme.json pattern setting, it would allow them to be visible in the Inserter. 
Instead an "Disallow all" it should be an explicit allow. 

With the growing number of pattern in the directory, a curation would help with the exposure of patterns in the editor. The more patterns there are the more theme developer would want to restrict the visiblity. This feature would give them the means instead of just blocking all patterns from the directory, select the few that should work well.

**Comment by ndiego** [comment]
Yes, I have confirmed the current functionality, and agree with this proposal. 

While I still think many themes will register their own patterns and use `remove_theme_support( 'core-block-patterns' );`, they may also was to pull a few curated patterns into the theme from the Pattern Directory. Alternatively, the theme author might want to submit all their theme patterns to the Directory, and then only pull their own patterns into the theme. The existing setup does not seem to support these use-cases.

**Comment by carolinan** [comment]
I agree, I think it would make it easier for theme authors to select exactly which patterns they want to feature from the directory.
And loading "your" patterns from the directory would reduce the amount of repetition and number of files in the theme. Especially if you have a set of themes all using the same patterns.

**Comment by ndiego** [comment]
@bph and @carolinan are you testing with Gutenberg active? I have been trying to diagnose this today and think I found a solution, but it depends on #40824 being resolved. There were changes made in core that have not yet been backported to Gutenberg. 

I will write up a PR, but if you have a chance to test, can you try the following?

1. Setup a local site with 6.0 and Twenty Twenty Two installed (do not activate Gutenberg)
2. Add `remove_theme_support( 'core-block-patterns' );` on line 30 of the `functions.php` file
3. Confirm that the core patterns do not display in the inserter, only the theme patterns
4. Add `"patterns": [ "short-text-surrounded-by-round-images", "partner-logos" ]` to the `theme.json` file
5. Confirm that the patterns do not show in the inserter
6. Open the `wp-includes/block-patterns.php` file in your local install
7. Comment out lines 136-143
8. Confirm that the patterns added via `theme.json` now display in the inserter

Let me know if you run into any issues. Thanks! 🙏

**Comment by bph** [comment]
@ndiego I just followed [your instructions](https://github.com/WordPress/gutenberg/issues/41282#issuecomment-1145284351) and the patterns from the directory showed up nicely.

**Comment by richtabor** [comment]
> Alternatively, the theme author might want to submit all their theme patterns to the Directory, and then only pull their own patterns into the theme. 

I'm thinking this may be the norm one day. Instead of including them in a single theme, having the patterns available within the theme — but also for everyone else.

**Comment by ndiego** [comment]
This was closed incorrectly, reopening.

**Comment by fklein-lu** [comment]
Tried the PR, and looks good. 👍

**Comment by ndiego** [comment]
This fix will be included in WordPress 6.0.2, and I just added https://github.com/WordPress/gutenberg/pull/43634 to fix the 6.0 compat file in Gutenberg.
