### ISSUE TITLE
Notices not visible when the page is scrolled

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#4128]
Noticed during WordCamp Rome contributor day users testing session. /cc @johnbillion

I _think_ this has already been discussed but I'm not sure there's a specific issue about it. Thought to open one, just in case.

The notices that appear at the top of the Gutenberg page, e.g. the "published" or the "updated" ones...

![screen shot 2017-12-21 at 15 39 37](https://user-images.githubusercontent.com/1682452/34260443-4d6af8d2-e666-11e7-9b71-a3fa65d018e5.png)

...are not visible when the page is scrolled. Scrolling the page for just a few pixels is enough to make them scroll out of view. When working on a post longer than a few, short, blocks, it's very likely this ends up in a total lack of _visual_ feedback for users.

Accessibility note: these notices should be paired with audible messages for screen reader users.

In a traditional submit/post request/page reload world, the feedback is very clear for everyone: the page reloads 😄  I'm all for "live" saving, whether it's AJAx or REST API or whatever, but then the feedback after an user action should always be very clear and never leave users in doubt about what happened.

Ideally, these notices should always be clearly visible, even in the responsive view. From an a11y perspective, they should be paired with an audible message.

**Comment by youknowriad** [comment]
duplicate of #3777 ?

**Comment by afercia** [comment]
Thanks, yes. Closing in favor of #3777
