### ISSUE TITLE
Query Loop Block: Cannot choose grid pattern

### ISSUE THREAD

**Issue by KokkieH** [WordPress/gutenberg#41297]
### Description

When inserting a query loop block there's a prompt to choose a pattern for the block. The subsequent modal has icons for list and grid views at the bottom, but if you click the grid icon, the Choose button disappears so the pattern cannot be selected.

### Step-by-step reproduction instructions

1. Create a new page or page template
2. Insert the Query Loop block
3. Click Choose to select a pattern
4. Click the Grid icon at the bottom of the modal
5. Note that the "Choose" button that was visible on the List view, disappears when switching to Grid view

### Screenshots, screen recording, code snippet

![Editor__beta__‹_My_Core_Sandbox_—_WordPress](https://user-images.githubusercontent.com/11873759/170189746-447337f3-b8e6-4ce6-8e94-3fdf16c7ca30.png)

![Editor__beta__‹_My_Core_Sandbox_—_WordPress](https://user-images.githubusercontent.com/11873759/170189842-a65db698-cfa7-48e2-ac64-b6e34afaca75.png)

### Environment info

- WordPress 6.0, Twenty Twenty-Two v1.2
- Can replicate with and without Gutenberg v13.2.2 activated
- Firefox 100.0.2 on MacOS 12.3.1
- Reported by a WordPress.com user with Chrome 101 on Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hello, @KokkieH

Clicking on the pattern in the grid view will select it.

I think we should make this action clear. Cc @jameskoster.

**Comment by KokkieH** [comment]
Ah, now I get it, @Mamaduka. It's not list-patterns and grid-patterns, but a list-view and grid-view of the available patterns. The user who reported this on WordPress.com and I both got this wrong, so yeah, it would be good if that could be a bit more clear :D

**Comment by jameskoster** [comment]
Thanks for the ticket (and mention)!

I shared some designs in https://github.com/WordPress/gutenberg/issues/39308 which eliminate the "Choose" button altogether.

**Comment by priethor** [comment]
@KokkieH thanks for reporting!

Do you mind if we close this issue and consolidate the work in #39308, as it will solve the problem?

**Comment by KokkieH** [comment]
@priethor that's absolutely fine, yes. Thank you :)
