### ISSUE TITLE
Avatar block throws encountered error if the Avatar Display turned off from the Discussion settings

### ISSUE THREAD

**Issue by abid112** [WordPress/gutenberg#41308]
### Description

If the Avatar Display turns off from the Settings > Discussion > Show Avatars(checkout): https://i.imgur.com/60w37sA.png
Avatar block still shows on Gutenberg blocks(which should not be shown): https://i.imgur.com/OYMqWaX.png
And if the Avatar block takes on an editor, it throws encountered error: https://i.imgur.com/y9LSwER.png

### Step-by-step reproduction instructions

1. Turn off Show Avatars from the **Settings > Discussion > Show Avatars(checkout)**: https://i.imgur.com/60w37sA.png
2. Go to Gutenberg editor and take Avatar block which will throws the error: https://i.imgur.com/y9LSwER.png

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by cbravobernal** [comment]
Closing this issue as it is fixed in #41354
