### ISSUE TITLE
Clicking the WordPress Icon in the Site Editor Should Go to the Dashboard

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#41315]
## What problem does this address?

When you click on the WordPress in the icon in the post/page editor it takes you to the dashboard. In the site editor it brings up an additional menu. The workflow is not consistent. The user should have the same workflow in both editors.

## What is your proposed solution?

My solution is to move the menu somewhere else.

![image](https://user-images.githubusercontent.com/12677420/170260782-84994454-ee56-45b4-ae73-3837f0c8d37b.png)

**Comment by annezazu** [comment]
Noting that a similar issue was previously opened and later closed: https://github.com/WordPress/gutenberg/issues/36021 However, the PR that closed that issue has since evolved and the behavior has returned. Most recently, this came back up in the FSE Outreach Program's fifteenth call for testing:

> In the site editor, I always expect clicking the W to have the same behavior as when in the page editor (take me back to the dashboard). It sometimes feels like I am “trapped” in the site editor without an easy way to get back to the dashboard. One suggestion would be having a dropdown to select whether I want to go back to the dashboard vs. see Site/Template/Template part editor. Similarly, I sometimes wish there was a “view site” option from the site editor. Again, I feel trapped

I'm not quite sure how best to reconcile this, considering how much the W menu is in use and is needed for other pathways to edit templates, template parts, potentially styles, etc. I lean towards seeing this as a pain point but not something that can be fixed per say. @jameskoster curious what you think?

**Comment by jameskoster** [comment]
I think there's conceptual consistency between the behaviors in the sense that in both cases you exit editing context and enter management context. We have quite some way to go in terms of aligning the UX though. Take a look at https://make.wordpress.org/design/2022/06/13/thinking-through-the-wordpress-admin-experience/ for a glimpse of where we might be headed in that regard.

**Comment by annezazu** [comment]
This was once more brought up in the [FSE Outreach Program's Site Editor Sneak Peek exploration](https://make.wordpress.org/test/2022/11/13/fse-program-exploration-site-editor-sneak-peek/#comment-2765) by a few folks when exploring browse mode, which seems to be making this feeling "worse":

>It’s odd to me that clicking the W when editing a template takes you to the site editor page, but clicking the W with the sidebar already open takes you back to wp-admin. I might have given similar feedback before (don’t remember). But it still confuses me every time I click it.

>The < Dashboard link should still be present in the new browse mode, as it gives a clear signal that clicking it will return to the Dashboard. Or Atleast have a Hover over the W (site identity) showing the tooltip that says "Return to Dashboard"

>I still think that getting back out to the Dashboard could be more obvious. I’ve been working in it for a while now so I know that clicking the W gets you there, but if I was just encountering this for the first time, I would be looking for a “Dashboard” button or link."

>Reflecting the sentiment of the previous commenter, it isn’t immediately obvious (to a user new to WordPress, specifically) that the “W” logo is the way to exit the editor."

For now, I can imagine this will continue to be a point of feedback but agree that in time it'll be smoothed over. I'm not sure what/if we should explore an interim solution to ease the confusion though! This was also noted in the [design discussion](https://github.com/WordPress/gutenberg/discussions/45346#discussioncomment-4240854).

**Comment by annezazu** [comment]
This was brought up in the latest [FSE Outreach Program's nineteenth call for testing once more:](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2836)

>It bothers me that the role of the “W” logo in the top-right seems to change. Historically the WordPress logo takes you to the Dashboard, but when editing it takes you back a step. I found this confusing.

**Comment by youknowriad** [comment]
I think there's still some reasonable confusion happening but I don't think this issue is actionable. The site editor is a big application today and we can't just restore a link to dashboard. I'm hopeful the situation will improve when we advance more in the redesign project.
