### ISSUE TITLE
Vertical alignment of flex containers incorrect on front end

### ISSUE THREAD

**Issue by justintadlock** [WordPress/gutenberg#41324]
### Description

When adding a Row block or a Buttons block, the vertical alignment of the nested blocks is correctly applied in the editor.  However, on the front end, the blocks are always aligned in the center.  Issue reported here: https://wordpress.org/support/topic/6-0-rc4-layout-for-row-block-is-always-align-items-center/

In the editor, the container is given `align-items: flex-start;`.  On the front end, the container is give `align-items: center;`.

Issue #35849 seems to be a related ticket, but it is suggesting that we add vertical alignment controls.  However, these controls are already present.

### Step-by-step reproduction instructions

1. Add a Row block
2. Add two or more nested blocks
3. Select "align top" from the toolbar
4. Save and check the front-end view

### Screenshots, screen recording, code snippet

**Editor view:**

![row-align-top-editor](https://user-images.githubusercontent.com/1816309/170271822-23ad3b23-a028-4e68-b4a3-026236ae87bf.jpg)

**Front-end view:**

![row-align-top-front](https://user-images.githubusercontent.com/1816309/170271844-67904cec-9fba-4fe0-aa89-15a87f8192c6.jpg)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by justintadlock** [comment]
Actually, this seems to work in Gutenberg 13.2.2.  It doesn't in WordPress 6.0.  Closing for now.

**Comment by britweb-tim** [comment]
This seems to be an issue when upgrading sites using gutenberg to WP 6.0.  The "core/columns" block now falls back to verticalAlign center if it's not explicitly set, but the editor shows them as "top" aligned.  Cannot override this fallback on a theme.

**Comment by justintadlock** [comment]
I believe I have tracked down the vertical alignment issue with flex layouts.  It looks like the PHP change from `/lib/block-suports/layout.php` was not ported over to WordPress into `/wp-includes/block-supports/layout.php`.

Here's the original PR: https://github.com/WordPress/gutenberg/pull/40013

Current code in Gutenberg trunk: https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/layout.php#L117-L131

Current code in WordPress 6.0 branch: https://github.com/WordPress/WordPress/blob/6.0-branch/wp-includes/block-supports/layout.php#L117-L126

@adamziel - Pinging you here as requested to find the best way forward.

**Comment by ndiego** [comment]
I just added this to the [6.0.1 Project Board](https://github.com/orgs/WordPress/projects/31).

**Comment by Stephan66** [comment]
This issue has NOT been resolved with WordPress 6.0.1, the frontend still behaves as Justin described.

**Comment by devboldium** [comment]
> This issue has NOT been resolved with WordPress 6.0.1, the frontend still behaves as Justin described.
Can confirm this is still happening in 6.0.1.

**Comment by adamziel** [comment]
cc @ockham who'll lead the next Core Editor merge.

**Comment by ockham** [comment]
> cc @ockham who'll lead the next Core Editor merge.

Thanks! Added to the (newly created) WP 6.1 Editor Tasks board 👍

**Comment by shanemac10** [comment]
Just updated to Version 6.0.2 and this is still happening. Please address this. 

Can we just have alignment based classnames dynamically added to the block so us devs can add style overrides? This dynamic `wp-container-<number>` classname and dedicated style tag generation thing that's going on is not helpful for building on top of Wordpress.

**Comment by llslim** [comment]
Can confirm  this is not fix in 6.0.2 temporary  workaround until fix ..

// remove layout support styles until vertical align gets updated in wp 6.1
// SPECIFIC_BLOCK_NAME == core/group

function ussaac_remove_group_layout_support_flag($block_content,$block) {
	if (('SPECIFIC_BLOCK_NAME' === $block['blockName']) && is_page('YOUR PAGE')) {
	  remove_filter( 'render_block', 'wp_render_layout_support_flag', 10, 2 );
		remove_filter( 'render_block', 'gutenberg_render_layout_support_flag', 10, 2 );
	}
	return $block_content;
}

add_filter('render_block','ussaac_remove_group_layout_support_flag', 9, 2);

**Comment by tellthemachines** [comment]
The updated layout code has now been backported to Core and testing shows it working correctly in trunk:

<img width="1160" alt="Screen Shot 2022-09-27 at 5 01 20 pm" src="https://user-images.githubusercontent.com/8096000/192456406-8b3957cc-e439-4ff0-bfae-32c78008c4f8.png">

I'm going to go ahead and close this issue for now.
