### ISSUE TITLE
Inserting a Classic block with the slash inserter crashes the editor if the sidebar is open

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#41321]
### Description

When adding a Classic block in an empty post, the editor crashes.

### Step-by-step reproduction instructions

1. Create a new post
2. Open the sidebar
3. Add a Classic block through the slash inserter

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/27339341/170268220-2fa79da4-4e4d-4218-9fc7-ea898916bf22.mov

### Environment info

- WordPress 6.0, or WordPress < 6.0 + Gutenberg version >= 13.0
- Firefox & Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
I don't seem to be able to reproduce the issue here. Is there some other variable at play here?

**Comment by priethor** [comment]
I'm trying to isolate the issue even more. I've just spun up a brand new site using Local and it crashes too. Not only when adding a new post but when adding it to the `Hello world!` existing one.

This is the error thrown in the console:

```TypeError: Cannot read properties of null (reading 'forEach')
    at block-editor.min.js?ver=39c7981dd22ec80281080455892940e6:formatted:22781:26
    at Object.Mt [as useMemo] (react-dom.min.js?ver=17.0.1:9:48138)
    at e.useMemo (react.min.js?ver=17.0.1:9:10749)
    at lk (block-editor.min.js?ver=39c7981dd22ec80281080455892940e6:formatted:22779:23)
    at ct (react-dom.min.js?ver=17.0.1:9:43430)
    at Bt (react-dom.min.js?ver=17.0.1:9:50249)
    at os (react-dom.min.js?ver=17.0.1:9:112112)
    at Ur (react-dom.min.js?ver=17.0.1:9:77643)
    at Ir (react-dom.min.js?ver=17.0.1:9:77571)
    at Dr (react-dom.min.js?ver=17.0.1:9:77434)
rr @ react-dom.min.js?ver=17.0.1:9

**Comment by priethor** [comment]
Testing with previous Gutenberg versions shows:
- If GB <=12.9, the Classic block works fine.
- If GB >= 13.0 (which is the last GB version included in WP 6.0), the issue reproduces.

**Comment by Mamaduka** [comment]
I'm not able to reproduce the issue. Tested with the following setups on Chrome.

* WordPress 6.0 with and without Gutenberg 13.2.2.
* WordPress 6.0 with current Gutenberg trunk.

@priethor, do you have any other plugins active?

**Comment by priethor** [comment]
> @priethor, do you have any other plugins active?

I don't, no plugins installed at all.

**Comment by mcsf** [comment]
@priethor:

1. Can you consistently repro?
2. Can you pinpoint the location in the minified source (e.g. "prettify" the source)?

**Comment by ryanwelcher** [comment]
@priethor I was able to reproduce this in the Site Editor using TwentyTwentyTwo:

1. Open the Single Post template
2. Insert a Classic Block

https://user-images.githubusercontent.com/1259027/170276002-439cee9f-c135-4a07-9eb5-d521e6eeaf2d.mov


Console outputs the error below.
```
react-dom.min.js?ver=17.0.1:9 TypeError: Cannot read properties of undefined (reading 'tinymce')
    at block-library.min.js?ver=016c65731f009ca1e5b5974727017d18:14:63022
    at $r (react-dom.min.js?ver=17.0.1:9:83333)
    at unstable_runWithPriority (react.min.js?ver=17.0.1:9:7431)
    at xn (react-dom.min.js?ver=17.0.1:9:29950)
    at Qr (react-dom.min.js?ver=17.0.1:9:82796)
    at Pr (react-dom.min.js?ver=17.0.1:9:74334)
    at react-dom.min.js?ver=17.0.1:9:30173
    at unstable_runWithPriority (react.min.js?ver=17.0.1:9:7431)
    at xn (react-dom.min.js?ver=17.0.1:9:29950)
    at Nn (react-dom.min.js?ver=17.0.1:9:30118)
```

**Comment by Mamaduka** [comment]
@ryanwelcher, the Classic block isn't supported in Site Editor at the moment - #23086. Also, based on the @priethor screencast, the error isn't caught by the block error boundary.

**Comment by ryanwelcher** [comment]
@Mamaduka @priethor I think we're looking at two separate issues. Mine seems to be known already so disregard my report. I can't reproduce this happening in the post editor.

**Comment by priethor** [comment]
> Can you consistently repro?

Yes, every single time.

> Can you pinpoint the location in the minified source (e.g. "prettify" the source)?

Sure, the error is thrown at the `return l.forEach` in the closure after `a.useMemo`

```javascript class:"lineNo"
           var lk = function(e) {
            let {blockClientId: t} = e;
            const {updateBlockAttributes: n} = (0,
            m.useDispatch)(qn)
              , {activeBlockVariation: o, variations: l} = (0,
            m.useSelect)((e=>{
                const {getActiveBlockVariation: n, getBlockVariations: o} = e(r.store)
                  , {getBlockName: l, getBlockAttributes: i} = e(qn)
                  , a = t && l(t);
                return {
                    activeBlockVariation: n(a, i(t)),
                    variations: a && o(a, "transform")
                }
            }
            ), [t])
              , i = null == o ? void 0 : o.name
              , s = (0,
            a.useMemo)((()=>{
                const e = new Set;
                return l.forEach((t=>{
                    t.icon && e.add(t.icon)
                }
                )),
                e.size === l.length
            }
            ), [l]);
            if (null == l || !l.length)
                return null;
            const c = s ? ok : rk;
            return (0,
            a.createElement)(c, {
                className: "block-editor-block-variation-transforms",
                onSelectVariation: e=>{
                    n(t, {
                        ...l.find((t=>{
                            let {name: n} = t;
                            return n === e
                        }
                        )).attributes
                    })
                }
                ,
                selectedValue: i,
                variations: l
            })
        }

**Comment by youknowriad** [comment]
@priethor that helps, so I can reproduce now and it's related to this PR https://github.com/WordPress/gutenberg/pull/40036

Basically, you need to have the sidebar open before adding the block to reproduce the issue :)

**Comment by priethor** [comment]
@youknowriad great context, I can confirm the sidebar needs to be open.

Furthermore, testing with @ryanwelcher showed it only crashes when using the slash inserter; when using the normal inserter or the appender it works fine.

**Comment by nickfmc** [comment]
I can also replicate this issue every time when adding the classic editor on a new page! However I found this post searching for an explanation to why I am seeing other blocks have unexpected errors, the other ones I can't find a way to replicate them yet the way you have with the classic editor. 

EDIT - One thing to clarify is that by "sidebar" @priethor is referring to the "Settings pane" NOT whether or not you are in "full screen mode" or not so the RIGHT sidebar, settings pane needs to be open to reproduce.
