### ISSUE TITLE
Remove Document Outline Menu

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#41330]
## What problem does this address?

The document outline feature is a redundant feature that should be part of the list view. When several options are added the details box gets way too long.
## What is your proposed solution?

This feature should be removed from the details menu and merged with the list view feature.

![image](https://user-images.githubusercontent.com/12677420/170285486-5bc941ae-7ff9-4104-9ffc-1b4f9c7a8b00.png)

**Comment by priethor** [comment]
There is further context about this in [#5301 (comment)](https://github.com/WordPress/gutenberg/issues/5301#issuecomment-677636469).

Considering the List View displays all blocks and the Heading blocks might be inside structural ones (columns, groups), the biggest challenge of a "Document Outline" mode for the List View, would be to determine where in the block hierarchy the drag&dropped headings would land. 🤔 

For example, if there are three Heading Blocks (A,B, C), each of them in a different column, if a user drags&drops heading A between B & C, it is unclear at first glance in what column heading A would sit.

**Comment by Mamaduka** [comment]
@priethor, can we close this now that List View and Outline sidebars are consolidated?
