### ISSUE TITLE
Filter (duotone) setting set to a block type in theme.json is rendered to the wrong elements on server side

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#41333]
### Description

When you define a block filter in `theme.json`, the output CSS is not written using the right selectors, so the filter ends up applied to the main block element instead the one indicated in `block.json`.

This causes several problems, for example:
- Discrepancies between what is shown in the editor and the public version of the post.
- Overriding the default filter/duotone using the editor has an unexpected result.

### Step-by-step reproduction instructions

1. Use `Skatepark` or another theme with default duotone filters applied to some blocks such as `Image` and `Cover`.
2. Create a new post and add an Image block, and also a Cover Block.
3. Select a different duotone filter for each of those blocks recently added.
4. Save and see the public version of the post (pay attention to the discrepancies between the editor and the public version).

### Screenshots, screen recording, code snippet

Comparison. To the left is the editor and to the right is the public version of the post:

![image](https://user-images.githubusercontent.com/1310626/170288327-63bd683c-6e16-474a-ba4c-64dd63526b83.png)

Step by step video:

https://user-images.githubusercontent.com/1310626/170289056-732462f1-7394-4795-92f6-0bc70d63d37d.mp4

### Environment info

- Wordpress 6.0
- Latest Gutenberg trunk branch

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by matiasbenedetto** [comment]
Potential fix here: https://github.com/WordPress/gutenberg/pull/41335

**Comment by annezazu** [comment]
@matiasbenedetto looks like your fix was merged! I'm going to close this issue as a result. Let me know if this needs to be reopened.
