### ISSUE TITLE
Can't paste content into Text Columns Block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4135]
## Issue Overview
I tried pasting some text into the Text Columns block and it wont paste

![gutenberg-multicolumnblock](https://user-images.githubusercontent.com/2078245/34285905-4a85511e-e731-11e7-9bfa-43eba70746bb.gif)

I have multiple instances of the Text Columns block on the page and in some instances text will paste ok, and in others, it wont paste at all, as seen in the above gif.

## Steps to Reproduce (for bugs)
1. Insert Text Columns block
2. Add text into first column and then copy the text
3. Try Pasting the content into the second column

## Expected Behavior
Copy/Paste should work as expected.

## Current Behavior
Pasting content into the block is very inconsistent

_Gutenberg  1.9.1
Firefox Quantum 57.0.1 (64-bit)
WordPress 4.9.1_

**Comment by karmatosed** [comment]
I can do this at will in Firefox, Chrome and Safari. Either something has been fixed or we need to dig into more why you are getting this.

![2018-01-03 at 14 52](https://user-images.githubusercontent.com/253067/34525113-c700da70-f095-11e7-8f14-555c0b8a6c95.png)

I am closing until we get confirmation this is still an issue.
