### ISSUE TITLE
`CustomGradientPicker`: `ColorPicker` popover is glitchy (size and position)

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#41353]
The popover containing the `ColorPicker` opens in unexpected positions (and sometimes with a smaller size than expected) in the `CustomGradientPicker` component:

https://user-images.githubusercontent.com/1083581/170356848-6d62166e-0746-4868-9d9d-8303d4e917d3.mp4

This could be related to the recent refactor of the `Popover` component in #40740

**Comment by andrewserong** [comment]
I've opened a potential fix in #41361
