### ISSUE TITLE
Columns Block, enable gap between columns to be adjusted

### ISSUE THREAD

**Issue by I-GW-I** [WordPress/gutenberg#41357]
## What problem does this address?

The Columns block does not allow you to adjust the space between columns

## What is your proposed solution?

Have an option in the Column block to allow for the gap between columns to be adjustable.

**Comment by justintadlock** [comment]
Testing with WordPress 6.0 or Gutenberg 13.3.0 shows the Block Spacing option (gap) support for Columns for me.  @I-GW-I Can you verify that the "Block Spacing" option is not available in the "Dimensions" dropdown when clicking on the vertical ellipsis icon?

![columns-gap](https://user-images.githubusercontent.com/1816309/170539894-b03293d1-69ea-4587-983e-1842c2ed966d.jpg)

**Comment by I-GW-I** [comment]
Sorry, you are correct, it is my theme that is the issue.  I am seeking help from the theme developers.

**Comment by justintadlock** [comment]
Thanks for the additional info.  Closing since this is a theme issue.
