### ISSUE TITLE
 Query Block & Post Categories block not outputing terms IDs

### ISSUE THREAD

**Issue by Julianoe** [WordPress/gutenberg#41352]
Hello!
I'm working wit the Query Loop Block and I was surprised it does not output the terms IDs in the DOM. WordPress has quite a consistent way of attributing classes to elements that match content elements: posts, terms, archive pages etc all have a way to target them in the DOM by outputting their classes in the default post_class() and other equivalent functions.

It does not seem to be the case for the Post Categories Block terms.

It there a way I can fix that?

Example use case: I target each term with a color in CSS to change the text color. I can't do it using this block.

Thanks

**Comment by justintadlock** [comment]
Just to clarify, you are asking for a class attached to individual category links within the Post Categories block, correct?  Something like this?

```html
<div class="taxonomy-category wp-block-post-terms">
	<a class="category-class-here" href="http://localhost/wp/category/classic/" rel="tag">Classic</a>
</div>
```

For a bit of a workaround, you can target specific category links with:

```css
.wp-block-post-terms a[href*=example-slug] {
}
```

Of course, that is not ideal, but it might do in a pinch.

**Comment by Julianoe** [comment]
Yes that was what I was thinking about. In the same manner the posts are displayed like : 
`<li class="wp-block-post post-POSTID">`

It helps to be able to target specific elements from the data structure (posts, terms, etc)

Something like you show this would be great, since it is not easy for end user to change templating for the blog output. Tech saavy people will find work around but detailed class would help website users with even very basic CSS knowledge to customize those blocks outputs

**Comment by carolinan** [comment]
If we want to do this, it is a small code change, but I'd like there to be consensus before working on it...

**Comment by ntsekouras** [comment]
Thanks for the issue @Julianoe ! I think @justintadlock 's suggestion(`.wp-block-post-terms a[href*=example-slug]`) is fine and we shouldn't add any css class, since there is a workaround. I mean having an extra class with the `id`, still requires someone somewhat tech savvy to figure out the `ids` etc..

I'll close this for now, but feel free to reopen if there are is the need.
