### ISSUE TITLE
Button Block cursor position not aligned correctly

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4140]
## Issue Overview
When you first insert a Button block, the cursor position doesn't align to the centre of the button correctly, or the placeholder text

![gutenberg-buttonblock](https://user-images.githubusercontent.com/2078245/34286989-503d3c8c-e738-11e7-9461-6cfac10fc810.gif)

## Steps to Reproduce (for bugs)
1. Insert button block

## Expected Behavior
The Cursor should align with the placeholder text, which is vertically centre aligned

## Current Behavior
Cursor alignment overlaps edge of button

_Gutenberg 1.9.1
Firefox Quantum 57.0.1 (64-bit)
WordPress 4.9.1_

**Comment by youknowriad** [comment]
Mmm, can't reproduce this, I'm using `Firefox 58`. Could this be a meta box style conflict or something?

**Comment by maddisondesigns** [comment]
@youknowriad I'm going to close this one. It seems to be behaving properly now. Not sure why as Gutenberg hasn't been updated since I wrote this issue and I haven't activated/deactivated any plugins. I'll create a new issue if it happens again and I can successfully reproduce
