### ISSUE TITLE
HTML anchor: Smooth scrolling to receiving end.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#41403]
## What problem does this address?

Right now clicking an internal same page link using a HTML anchor jumps directly to the receiving block.
It feels choppy.

## What is your proposed solution?

Add smooth scrolling when clicking a HTML anchor, so it has a softer transition going to the receiving end.

Associated issue:
https://github.com/WordPress/gutenberg/issues/29352

**Comment by mtias** [comment]
While I can see something like this be alright for list view selection, it doesn't make a lot of sense for anchors — anchors are part of the front-end experience as well, and being uniform with how it works is more important. Also for navigating a table of contents, jumps seems better than scrollings of varying speeds.

**Comment by JPBarringer** [comment]
Just a quick comment here in case anyone is looking for a solution (as I was)

Add this to your custom CSS:
```
/* smooth scroll for anchors */
html {
	scroll-behavior: smooth;
}

/* respect users' motion preferences */
@media screen and (prefers-reduced-motion: reduce) {
	html {
		scroll-behavior: auto;
	}
}
```

There are cases where this is not ideal, as mentioned above, but it is also desirable at times. In my case it was having a button scroll the user to a form somewhere else on the page. The non-smooth "jump" can be jarring, just like the content flash on font or image load. IMO, it would be nice to have link and button elements surface a toggle for smooth scrolling when linking to an anchor. But at least it's not too hard to accomplish via custom CSS.
