### ISSUE TITLE
Saving widgets results in error.

### ISSUE THREAD

**Issue by grmrgecko** [WordPress/gutenberg#41419]
### Description

Doing any edits would result in error:

```
There was an error. e(...).getEditedEntityRecord(...).blocks is undefined
```

### Step-by-step reproduction instructions

1. Select widget
2. Remove widget
3. Click update

1. Select HTML widget
2. Convert to block
3. Click update

### Screenshots, screen recording, code snippet

![Screen recording](https://i.imgur.com/b9XDtPD.gif)

### Environment info

WordPress 6.0 running Hemingway theme gutenberg 13.3.0
Firefox 100.0.1 and Chrome 102.0.5005.61
MacOS 12.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi
I have not been able to reproduce this using Gutenberg 13.4.0. Can you provide any more information about the legacy widget contents?

**Comment by rodrigodagostino** [comment]
I wasn’t able to find a proper solution to this problem, but installing the Gutenberg plugin allowed me to save the widgets content, which seemed to override what was causing the issue. After that I uninstalled the plugin and was able to normally save the widgets content.

Hope this can still be useful to someone out there :)

**Comment by grmrgecko** [comment]
Still happens to me, what can I do to get you more information?

**Comment by grmrgecko** [comment]
I just ended up going into wp_options and removing all widgets.

**Comment by frabulator** [comment]
I just ran into the same issue... as well as others. Basically, all my widgets got messed up bad. 

I installed "Disable Gutenberg" and everything was fixed instantly. 

I hope that helps!
