### ISSUE TITLE
Can't select or move Button blocks properly when multiple button blocks are next to each other

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4141]
## Issue Overview
I inserted multiple Button blocks to test what each option did and when I tried to move a Left Aligned button past another button, I end up being unable to select the actual button that I want to move.

![gutenberg-buttonalignmentblock](https://user-images.githubusercontent.com/2078245/34287251-25bf2c98-e73a-11e7-9ed7-46e39a5d99b4.gif)

The particular button in this gif that I attempted to move past, had the clearfix option selected, but I still had the same issues when trying to move past other buttons that were centered or right aligned

## Steps to Reproduce (for bugs)
1. Insert multiple Button blocks
2. Attempt to move lower button past button above it

## Expected Behavior
I should be able to move a button block up and down past other button blocks, without losing focus of the actual block that I'm moving

## Current Behavior
Moving Button blocks past other buttons blocks is extremely difficult as you end up not being able to select the button that you actually want to move

_Gutenberg 1.9.1
Firefox Quantum 57.0.1 (64-bit)
WordPress 4.9.1_

**Comment by karmatosed** [comment]
I just tested and can't replicate, for now closing but we totally can reopen if you happen to still have this occur. Thanks.

**Comment by maddisondesigns** [comment]
@karmatosed Please reopen this. This is still an issue. Here's another gif that I just created with the current version of Gutenberg (2.3.0).

Not only do the arrow buttons not work, but they don't even display unless you actually click on the button to select it. If you just hover over the button, the arrows appear but as soon as you try to move the cursor to an arrow to click on it, they disappear, which means you can't move it unless you actually select it. And even then, they still don't move properly.

![gutenberg-cantmovebuttons](https://user-images.githubusercontent.com/2078245/37248641-b9d257fa-252b-11e8-8a45-ce9d38d4b61a.gif)

**Comment by karmatosed** [comment]
Is this only in Firefox for you? I ask as not able to recreate in Firefox. I'll reopen but we probably need to dig a bit into recreation steps.

**Comment by maddisondesigns** [comment]
I just tested Chrome (Version 64.0.3282.186) and it acted in the same way.

All I did yesterday when I created that GIF was added three buttons. First (top) one was left aligned and the other two were right aligned.

**Comment by danielbachhuber** [comment]
Closing in favor of #6634 and #5885
