### ISSUE TITLE
WP6.0: enable to select parts of multiple paragraphs in Classic Block

### ISSUE THREAD

**Issue by Julianoe** [WordPress/gutenberg#41432]
### Description

I can't select parts of paragraphs of the Classic Editor.

### Step-by-step reproduction instructions

- in Block Editor, create/edit a "Classic" block
- type multiple paragraphs of content
- try to select part of the first paragraph and part of the second paragraph
- it immediately unselects the text

If you do select an entire unique paragraph it does not happen.
I'm suspecting it comes from the new WP feature on paragraph selection.

### Environment info

WP 6.0
Tested on troubleshooting mode with Twenty-Twenty-One and 0 plugin enabled on both Chromium and Firefox (Linux Manjaro)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
I'm able to reproduce this on gutenberg 13.3 ; were you previously able to select text partial paragraphs in the classic block on WordPress 5.9? 

https://user-images.githubusercontent.com/955351/172217137-d01a4fd6-c0ca-4b64-952a-40ba461ea7ef.mp4

**Comment by Julianoe** [comment]
I don't know for WP 5.9 but in 5.8 yes, there is no bug.

**Comment by cuemarie** [comment]
I can still replicate this today when using Classic Themes:

- Theme: Twenty Twenty One (also replicated in Twenty Nineteen and Twenty Twelve)
- WP: 6.3.1
- Gutenberg version 16.5.1

https://github.com/WordPress/gutenberg/assets/27249804/c3995f90-31fc-4db5-b554-fa477ad449b9

**Comment by annezazu** [comment]
Hey folks! Using this [Playground Instance](https://playground.wordpress.net/#{%20%22steps%22:%20[%20{%20%22step%22:%20%22login%22%20},%20{%20%22step%22:%20%22installTheme%22,%20%22themeZipFile%22:%20{%20%22resource%22:%20%22wordpress.org/themes%22,%20%22slug%22:%20%22twentytwenty%22%20},%20%22options%22:%20{%20%22activate%22:%20true,%20%22importStarterContent%22:%20true%20}%20}%20]%20}), I installed Twenty Twenty, added a classic block, and added in 5 paragraphs. I found I can select across paragraphs, copy the text, and paste it elsewhere. Here's a video:

https://github.com/user-attachments/assets/cef266c0-d640-4c83-99f6-f2d6ed9237e4




Can anyone else still replicate this? 

For now, I'm going to close this out but please let me know if this needs to be reopened! It would be a great one to resolve.
