### ISSUE TITLE
Template Part: Swap 'Edit' and 'Replace' action placement

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#41437]
Currently 'Replace' is a primary action, present in the template part block toolbar, while 'Edit' is hidden away in the ellipsis menu:

<img width="604" alt="Screenshot 2022-05-30 at 15 33 53" src="https://user-images.githubusercontent.com/846565/171019876-e27dbc8a-3631-491e-8301-f883d7af63e4.png">

In most cases it's more likely that you'd want to edit the selected template part, so that should be the primary action. Replacing should be secondary.

Suggested revision:

<img width="588" alt="Screenshot 2022-05-30 at 16 38 07" src="https://user-images.githubusercontent.com/846565/171025012-0248c624-9b12-4c3d-aaa3-9eabc504d6c6.png">

There may even be an argument that having the Edit button in the toolbar is too prominent since you can already directly manipulate the template part contents. But since the toolbar has very few actions, I think it might be ok to try, especially as focus mode may be the preferred editing mode for some users.

**Comment by carolinan** [comment]
The EditTemplatePartMenuButton is a component under edit site, I do not know what the best practice is for making it available in the top level of the block toolbar?
If it is not going to be used in the block settings menu anymore, do we re-create it, but in a utility file for the specific block?

**Comment by Mamaduka** [comment]
@jameskoster started working on this issue; I'll have PR ready for testing before the end of the week.

Question: I don't think we have Slot in the "Remove block" menu group. Is it okay to add "Replace" where we currently have the "Edit" menu item?

## Screenshot
![CleanShot 2022-07-06 at 15 02 36](https://user-images.githubusercontent.com/240569/177536834-acd55bf9-8e82-4fe3-9794-ec7712cecc43.png)

**Comment by jameskoster** [comment]
@Mamaduka yes I think that's fine :)
