### ISSUE TITLE
Gallery Block docs update: 'Edit as HTML' option no longer supported in 6.0

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/gutenberg#41448]
The [docs for the Gallery Block](https://wordpress.org/support/article/gallery-block/) still include an `Edit as HTML` option, however this has been removed from the editor in 6.0, see PR https://github.com/WordPress/gutenberg/issues/39310.

Docs entry:
![Screen Shot 2022-05-31 at 4 52 17 PM](https://user-images.githubusercontent.com/1017872/171095401-ffc3cccb-ca3e-43be-813d-c4af5b965aef.png)

No Edit as HTML option in dropdown:
![Screen Shot 2022-05-31 at 4 54 53 PM](https://user-images.githubusercontent.com/1017872/171095666-32782d3a-30f2-455d-80c1-a13112b1b8eb.png)

The option should also be removed from the docs.

**Comment by adamwoodnz** [comment]
Maybe should be covered in https://github.com/WordPress/Documentation-Issue-Tracker/issues/276

**Comment by t-hamano** [comment]
This document is covered by [WordPress Documentation Issue Tracker](https://github.com/WordPress/Documentation-Issue-Tracker#coverage) and does not appear to be under the gutenberg repository.

How about closing this issue and leaving a comment on [#276](https://github.com/WordPress/Documentation-Issue-Tracker/issues/276) about this?
