### ISSUE TITLE
FormTokenField: Styling is broken when `isBorderless`

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#41447]
When the `isBorderless` prop is `true`, the styling of the tokens are broken. The "delete" icon is jammed too close.

## Screenshot

<img width="46" alt="Broken borderless token styling" src="https://user-images.githubusercontent.com/555336/171091131-92cf6c99-d9b8-4564-bf14-933245bc4424.png">

## Screen recording

https://user-images.githubusercontent.com/555336/171091093-9f1c4fa6-5008-40d9-8259-d6d1160bebe8.mp4

**Comment by akasunil** [comment]
Hello @mirka 

I have fixed this issue in PR [41556](https://github.com/WordPress/gutenberg/pull/41556). Please review and let me know if there is any feedback.

Thanks.
