### ISSUE TITLE
Template panel: "Default template" can be a confusing option label

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#41449]
<img width="296" alt="Screenshot 2022-05-31 at 09 14 20" src="https://user-images.githubusercontent.com/846565/171125794-2df80385-1d5a-4f5d-94e1-2e76ef3f33ae.png">

All options in the dropdown explicitly use the template name as the label, except for the "Default template" option. This can be confusing if you then go to the Site Editor to edit this template, only to find that "Default template" doesn't exist. 

Suggestion:

Update the default template option to state the template name, with '(default)' appended.

<img width="291" alt="Screenshot 2022-05-31 at 09 17 30" src="https://user-images.githubusercontent.com/846565/171126421-2e5572a9-cc55-479a-b5f5-0056f3fd677a.png">

**Comment by Mamaduka** [comment]
@jameskoster, with recent refactoring (#41925), what do you think if we display the template name as a button label, but leave "Default template" in the drop down?

![CleanShot 2022-07-01 at 11 38 03](https://user-images.githubusercontent.com/240569/176848248-4ef246d7-e063-4c0c-9e05-507ec22dee13.png)

**Comment by jameskoster** [comment]
Personally I think that's a bit confusing – two elements in the UI seem to be telling me different things. Appending "(default)" to the default template name still seems the best way to provide clarity imo.

**Comment by annezazu** [comment]
Noting that feedback came in from the [fifteenth call for testing from the FSE Outreach Program](https://make.wordpress.org/test/2022/07/11/fse-program-testing-call-15-category-customization/#comment-2632) about how confusing this current experience is: 

>So I would prefer if it said “Template Single” instead of “Template Default Template”. Or maybe “Template Single (Default)”, though I don’t see how being shown Single is the default is really helpful at that moment.

**Comment by priethor** [comment]
I'm unassigning the issue since Jorge is not currently available so that somebody else can pick it up 🙂

**Comment by jorgefilipecosta** [comment]
I had a PR that fixed this issue https://github.com/WordPress/gutenberg/pull/45865/. Fixing this issue is not something simple and involves computing the template that would be used if there was no template currently assigned to a post. Which is a special template resolution case and replicates some logic already existing in the core that is not extracted and reusable. At the time @youknowriad  referred the added complexity to the codebase may not be worth the UX improvement and so the PR was closed. I don't think the situation changed meanwhile.

**Comment by jordesign** [comment]
Ah - that definitely makes it more complicated - thanks for the additional context @jorgefilipecosta

**Comment by MikeG14** [comment]
I don't know where this went after the discussion, but -  I'm new to Wordpress and I have to agree that seeing "Default Template" in drop-downs for selection, and then looking for "Default Template" in the template list and not finding it, is frustrating and confusing.  Is there any mechanism that can be used to identify which template is the "Default Template"?

**Comment by annezazu** [comment]
Hey @MikeG14 thanks for chiming in on this discussion and for taking the time to find it. It's very helpful to hear feedback from folks like yourself. In terms of finding the default, I've heard recommendations from folks to try leaving a paragraph block with the word "test" or something similar in templates to help determine which is the default. After leaving some "test" text in the template you think is likely the default, you can then confirm if that properly shows up.

Of note, there's a new experience coming to WordPress 6.5 around swapping templates that you might be interested in:

https://github.com/WordPress/gutenberg/assets/26996883/908b2738-8940-4716-9676-ec05f9d4a4c3

There's some discussion around the phrasing there too in case you have any thoughts: https://github.com/WordPress/gutenberg/issues/56845

If you're on WordPress.org slack, feel free to message me there (I'm @annezazu) and I can dig into your theme to figure it out for you too.

**Comment by youknowriad** [comment]
The applied template is now rendered properly. It seems this issue is fixed unless I'm missing something.

![Image](https://github.com/user-attachments/assets/9d57dc30-5d23-4490-a675-81334b44cbcb)
