### ISSUE TITLE
Separate Page Editor from Blog Post Editor

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#41442]
## What problem does this address?

New users find it difficult to get blog posts out quickly because of all the options available in the Gutenberg editor. The options available are geared towards creating a well-designed page rather than writing blog post content. It is easier for a user to create a blog post on a website like Medium than it is for them to create a blog post on WordPress.
## What is your proposed solution?

A solution would be to have a simple editor like the one present in Webflow that allows users to type of blog posts. The editor will only have the tools necessary fields to generate content. Having this type of structure will make it easier and faster for content to be generated.
![image](https://user-images.githubusercontent.com/12677420/171054673-a2eef206-943c-45f9-9f1f-d17ada746a25.png)
![image](https://user-images.githubusercontent.com/12677420/171054955-4782e9a2-f63e-4f86-a2bc-017ad5d69c4e.png)

**Comment by annezazu** [comment]
Hey there! I'm going to close this out as the premise of having yet another editor is unlikely for the project. However, you might appreciate this work in progress PR to offer a fairly robust distraction free mode: https://github.com/WordPress/gutenberg/pull/38928 I think it'll accomplish what you're looking for :)

**Comment by annezazu** [comment]
>This is a poor excuse for what I was suggesting. I was asking for an editor without blocks. This still has blocks. Please allow the user to disable the blocks and just type like in my screenshots.

Copying over what you shared in the PR ^. Right now, WordPress is and has been pursuing a block based approach so I'm afraid to accomplish specifically what you're looking for (no blocks), you'll likely need to pursue a plugin. Otherwise, the reduced interface, in my mind, does address some of what you described here:

>New users find it difficult to get blog posts out quickly because of all the options available in the Gutenberg editor.

I'm bummed you don't see it the same way but wanted to ensure you were aware that various options are being explored :)
