### ISSUE TITLE
Post editor: Template panel should adapt when explicit template exists

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#41452]
Follow up to https://github.com/WordPress/gutenberg/pull/41189.

When a template exists that automatically resolves to display a specific post or page (e.g. `single-post-$slug`), the Template panel in the post editor will need some adjustments when editing the corresponding post:

* It should not be possible to create a new template – this is misleading as it suggests the new template could be applied to the current post.
* The template dropdown should be hidden since it isn't possible to change the template.
* Some text explaining the above could eliminate potential confusion.
* We might consider adding a way to delete the explicit template.

<img width="293" alt="Screenshot 2022-05-31 at 10 51 02" src="https://user-images.githubusercontent.com/846565/171146284-715b742a-8859-4b05-910a-9a112e099fde.png">

If we added a delete action it should invoke a confirmation modal that explains which template will be used after deletion.

Edit: To clarify, the explicit template is only applied automatically if a `$custom` template has not been applied previously. So the UI above should only be presented when no `$custom` templates exist at all.

**Comment by jameskoster** [comment]
This pretty much feels like a bug at the moment. 

After creating a template for a specific post I can actually change which template is applied when editing that post, which undermines the specific template logic altogether.

**Comment by carolinan** [comment]
I tried to solve this in [components> sidebar > post-template](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-post/src/components/sidebar/post-template/index.js) but I got stuck because the `template slug` is not defined for the "Default" template:
I am not sure how to differentiate single.html from single-post-$slug.html, because they would both have no template slug value and both would be valid defaults? The options should only change if single-post-$slug.html is available.

**Comment by jameskoster** [comment]
@noisysocks has been working with the template panel recently, perhaps it's something he can look into? 🙏

**Comment by noisysocks** [comment]
What happens if the post already has a template that was created using the post editor sidebar?

**Comment by jameskoster** [comment]
That is a very good question, and I am once again humbled by the template hierarchy 🙈 

Currently templates created in the post editor are `$custom` and therefore _above_ specific templates (such as `single-post-hello-world`) in the hierarchy. I mistakenly thought it was the other way around.

So actually the current behavior of the template panel is correct – I am able to select a $custom template, _or_ the template that was created for that specific post. 

The flow of creating a template for a specific post and _not_ applying it feels a bit strange, but that's something to explore separately. I'll close this issue.

**Comment by noisysocks** [comment]
It's definitely confusing 😅 I don't really like that we have two flows to accomplish what amounts to the same thing.

**Comment by jameskoster** [comment]
Turns out the explicit template _is_ applied automatically, but _only when a custom template hasn't been applied_. Re-opening and updating the OP :D

**Comment by youknowriad** [comment]
Maybe I'm missing something here. But here's what I did:

 - I created a custom template for the specific page in the site editor => template applied
 - I went to the "page editor", and I created a custom template from the panel => that newly created and assigned template is used.

So things are working as they should for me. Can you clarify what's the confusing behavior here?

**Comment by jameskoster** [comment]
The confusing part was my interpretation of the template hierarchy :) Agree this is working as intended.
