### ISSUE TITLE
Block attributes docs: missing `Saved content` code block in example of `multiline` prop usage

### ISSUE THREAD

**Issue by vasartam** [WordPress/gutenberg#41469]
## What problem does this address?

In the [html section of Block Attributes page](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-attributes/#html) there is a "Saved content" code block missing. Because of that, for a person who is at the stage of researching the Gutenberg capabilities it is unclear what `multiline` prop does when using `source: 'html'` in block attribute definition:

https://github.com/WordPress/gutenberg/blob/0897b1723d37030f7a8e6f3e84be98970c9f16c6/docs/reference-guides/block-api/block-attributes.md?plain=1#L276-L292

## What is your proposed solution?

There should be a "Saved content" code block example just before the attribute definition example, as it's done in the example right above:

https://github.com/WordPress/gutenberg/blob/0897b1723d37030f7a8e6f3e84be98970c9f16c6/docs/reference-guides/block-api/block-attributes.md?plain=1#L249-L274

I would have created this code block myself in the PR #41468, but I myself don't exactly know how this feature works.

**Comment by t-hamano** [comment]
@vasartam

Thank you for submitting the issue.
I have submitted a PR at #43075 for consistency, including the points you raised.
