### ISSUE TITLE
Add title tag to Gutenberg handbook on WordPress.org

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#4149]
It would be helpful if each handbook page rendered the correct title tag:

![image](https://user-images.githubusercontent.com/36432/34301081-cb936324-e6df-11e7-973c-c43a48a38141.png)

**Comment by sriikanth** [comment]
@danielbachhuber Is the issue still open?
Shall i take it?

**Comment by youknowriad** [comment]
@sriikanth Yes it's still open but this has to be fixed outside of the Gutenberg repo. The Gutenberg repo contains only the markdown doc files. cc @pento (Maybe this should be fixed in https://github.com/WordPress/gutenberg-theme)

**Comment by sriikanth** [comment]
@youknowriad I will try doing as you said!
Thanks.

**Comment by pento** [comment]
w.org has forked that theme, as we had to add too much w.org-specific stuff to it. I'll fix it.

**Comment by pento** [comment]
[Fixed](https://meta.trac.wordpress.org/changeset/6307).
