### ISSUE TITLE
Screenshots of components should look equally

### ISSUE THREAD

**Issue by evrpress** [WordPress/gutenberg#41501]
## What problem does this address?

Whenever you need the documentation of a component you most often like to see a preview of it. Since many components still have no screenshot at all I propose a standardized way to display screenshots.

Since block elements often lack of a visual border a mockup with an artificial border could help.

Without any padding the element often look plain and not recognizable:

![Quote](https://user-images.githubusercontent.com/881729/171612383-c9b5bd2c-4230-4b73-8ba5-5d473ce91a21.png)

## What is your proposed solution?

Adding an artificial border to the element makes them better recognizable.

![Quote with BG](https://user-images.githubusercontent.com/881729/171613313-dc30fecf-ef39-4da3-b773-96af4a20c2c7.png)

### Steps to create the screenshot

Make sure you use a standard theme so all blocks look in the same fashion.

1. Add an element to the Block editor content area.
2. Capture the Block (DOM node) with Chromes or Safari built in screen shot tools.
3. Prepare the screenshot with a third party service (needs some research) - or even better automate that with GitHub workflow
4. Upload the screenshot to the documentation.

To create screenshots Google Chrome as well Safari come with a built in screenshot tool to capture single DOM elements (block).

**Comment by mtias** [comment]
Screenshots are not a great way to represent blocks since it cannot easily be kept in sync. Previewing blocks should be approached in a more dynamic way, like the [BlockBook](https://youknowriad.github.io/blockbook/), which allows real previews and even checking against different themes.
