### ISSUE TITLE
Highlight text: Highlight color is still applied when typing after reseting color

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#41510]
## Description

After setting a color to highlight text, if the color is reset (i.e. sets the default text color), typing more text is displayed with the highlight color instead of the default.

## Step-by-step reproduction instructions

1. Open a post/page.
2. Add a Paragraph block.
3. Tap on the Highlight text button located in the toolbar (i.e. the (A) button).
4. Select a color.
5. Type some text.
6. Observe that the color is displayed with the selected color.
7. Tap again on the Highlight text button located in the toolbar (i.e. the (A) button).
8. Tap on the "Reset" button.
9. Type more text.
10. Observe that the text is still displayed with the previously selected color, instead of the default one.

## Expected behaviour

Text typed after the highlight color has been reset should be displayed with the default text color.

## Actual behaviour

Text typed after the highlight color has been reset is still displayed with the previously selected color.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/171646608-8fb2ae17-51c5-4c36-93f1-c32e4a52a181.MP4

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty-One

## Device information
- Device: iPhone 11
- Operating system: iOS 15.4
- WordPress app version: WordPress-iOS 19.9

**Comment by dcalhoun** [comment]
Sharing that the reset behavior does not appear to function at all, not just for newly typed text. It is not possible to use the "Reset" button to clear text color for existing text or newly typed text. 

<details><summary>Screen recording: clearing existing text color</summary>

https://github.com/WordPress/gutenberg/assets/438664/a24dd30d-42d4-4d8a-a92e-354bf4cfa4f9

</details>
