### ISSUE TITLE
Document WordPress classic editor integration points and Gutenberg equivalents

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#4151]
As a WordPress developer, it would be helpful to have a reference guide to:

* <del>All</del><ins>Most</ins> of the ways a theme, plugin or third-party code can integrate with the WordPress classic editor.
* Recommendation to achieve equivalent functionality with Gutenberg.

I've started working on such a document, [WordPress Editor Integration Points](https://paper.dropbox.com/doc/WordPress-Editor-Integration-Points-0aqeaKURPVxVyWvtdMBCe), and can grant contributor access to whomever is interested. Alternatively, please leave comments on this issue with existing classic editor integrations that I don't yet have documented.

Once the document is more substantive, we can put it in a public place.

Related:

* Optimize for the majority of WordPress users able to use Gutenberg on day one #4087
* Quantify plugin and theme compatibility with Gutenberg #4072
* Document known changes in editor behavior #4186

**Comment by youknowriad** [comment]
related https://github.com/WordPress/gutenberg/issues/1316#issuecomment-348304599

**Comment by mboynes** [comment]
Related #1352, especially [this list of current pluggable areas](https://github.com/WordPress/gutenberg/issues/1352#issuecomment-310842184) and [this wishlist of pluggable areas in gutenberg](https://github.com/WordPress/gutenberg/issues/1352#issuecomment-310645792).

**Comment by aaronjorbin** [comment]
Also related: a discussion around pluggability from WordCamp for
Publishers:
https://daily.jorb.in/2017/08/gutenberg-and-publishers-unconference-notes-from-wordcamp-for-publishers/

http://aaron.jorb.in
twitter: twitter.com/aaronjorbin

**Comment by danielbachhuber** [comment]
I have a pretty good work in progress set of documentation here: https://github.com/danielbachhuber/gutenberg-migration-guide

I'll keep adding to that as new examples come up and the project progresses.

**Comment by dankirshner** [comment]
I'm trying to figure out a Gutenberg equivalent to php

   add_action ('admin_footer-post.php', ...);

Is there one?  Thanks.

**Comment by codebard** [comment]
Similar: Looking for any action that is still valid for doing things in admin_footer or the like - or any Gutenberg hook/filter. I read this thread, and the document references within this thread do not provide sufficient info. Nothing tangible comes up from Google searches and WP documentation pages either.
