### ISSUE TITLE
Gallery Block: One column layout turns to two on mobile

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/gutenberg#4152]
## Issue Overview
On mobile devices, all galleries display as two columns -  totally makes sense for higher column counts, to make sure the images aren't teeny-tiny, but it also affects the one column layout, which caught me off guard.

## Steps to Reproduce (for bugs)
1. Add a Gallery Block to a post and set it to one column.
2. View on a mobile device, or narrow browser window.

## Expected Behavior
The gallery would still display with the one column layout.

## Current Behavior
The gallery displays in two columns.

## Screenshots / Video
![Image](https://cldup.com/kc45lvlfq_-3000x3000.png)

## Related Issues and/or PRs
There's some related discussion about responsive Gallery styles in #1433.

**Comment by nielslange** [comment]
@laurelfulford Is it possible that this issue is caused by the CSS of your theme? I'm unable to reproduce this issue on https://nielslange.nl/2017/12/25/gallery-test/ using the theme [Radcliffe 2](https://wordpress.com/theme/radcliffe-2).

**Comment by laurelfulford** [comment]
Thanks for double-checking @nielslange!

It looks like it might have been some weirdness on my part when I was testing the block. When I tried adding a one column gallery in a new post with the same theme, and it's displaying as expected. 

I'm not sure what I did the first time, but it seems like a one-off that was all me 😄 closing!
