### ISSUE TITLE
ToolsPanel: The ToolsPanel menu gets in the way of seeing what selected options look like

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#41545]
Prior: https://github.com/WordPress/gutenberg/issues/41376

### Description

When using the ToolsPanel to select different design tool options, the ToolsPanel menu obscures the content behind. This means you can't select a design tool and get an idea of what it actually does without closing the menu first.

![2022-06-03 10 12 17](https://user-images.githubusercontent.com/1464705/171913433-7971108d-faa0-4c82-9b1e-01ee60deb5c9.gif)

**Comment by apeatling** [comment]
Using Figma as a reference, their equivalent menus are position initially to the side. We already have prior art there in the form of the color selection controls.

Figma also allows you to drag around the menu and position it wherever you'd like. I think this is interesting, but an obvious first iteration would be to move it to the side.

My one concern there is the disconnect from the button you've clicked. It feels less like a menu, perhaps the reason Figma treats it more like a draggable popup box with a close button. We should discuss if this is an issue for Gutenberg.

![2022-06-03 10 30 55](https://user-images.githubusercontent.com/1464705/171916502-a6837c30-70d2-41e1-8191-85601de8659d.gif)

**Comment by fotisps** [comment]
In our case, most of the fix menus are on the sidebar so using figma as a paradigm, I think it's not the best solution. I would just add a close text and icon as a button in order to close the window, in case the user needs to see all the options that are available after making his/her choice.

**Comment by jameskoster** [comment]
As an interim, perhaps we could reduce the menu width, and open it from the bottom-left of the ellipsis?

| Before | After |
| --- | --- |
| <img width="444" alt="Screenshot 2022-06-08 at 14 17 07" src="https://user-images.githubusercontent.com/846565/172626227-8cb2f0e0-7dd0-41f4-b3a0-71b60f373b01.png"> | <img width="526" alt="Screenshot 2022-06-08 at 14 17 16" src="https://user-images.githubusercontent.com/846565/172626261-4065119f-75b9-4b2d-8acc-aded3327d81d.png"> |

I appreciate it won't always be possible to do this, but I believe we could make these changes with relative ease, and that they would improve the quality of life while we work on a more holistic solution.

**Comment by mtias** [comment]
Can we just self close it? We have many menus that perform actions and self close.

**Comment by apeatling** [comment]
Finding out more via https://github.com/WordPress/gutenberg/issues/41546#issuecomment-1175219481

**Comment by ciampo** [comment]
Hey folks, in the context of [potentially stabilizing the `ToolsPanel` component](https://github.com/WordPress/gutenberg/issues/67954), could y'all help understand whether this issue is still relevant?

**Comment by jameskoster** [comment]
The menu has opened to the left of the Inspector for a while now:

<img width="583" alt="Image" src="https://github.com/user-attachments/assets/6d7966de-33ca-43e8-b6e9-c85f534f003a" />

So we can probably close this issue :)
