### ISSUE TITLE
export React's useId hook

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#41559]
I propose to surface `useId` hook from React, so it is available in block development.

**Comment by Mamaduka** [comment]
Hi, @Lovor01

The new hook will be exported after [React 18 update](https://github.com/WordPress/gutenberg/pull/32765). Meanwhile, you can use [`useInstanceId`](https://github.com/WordPress/gutenberg/blob/trunk/packages/compose/src/hooks/use-instance-id/README.md).
