### ISSUE TITLE
Can't type or add blocks in the WordPress editor

### ISSUE THREAD

**Issue by ruchikothariinformatics** [WordPress/gutenberg#41562]
### Description

I'm currently on WordPress version 6.0, using Block Theme on Google Chrome.

When I try to add/edit a page/post, the following occurs.

Added text appends before the placeholder "Add Title" in the title.

The editor does not allow typing in the "Type / to choose a block" part, but if I click below it, I can add text that is appended to the muted text.

Third-party cookies and JavaScript are both enabled. I also tried clearing the entire time cache but was unable to address the problem.

I have also deactivated all the plugins but the problem persists.

It does, however, work flawlessly in Firefox. But I'm stumped as to why on Chrome it isn't working.

Thanks in advance!

### Step-by-step reproduction instructions

1. Go to 'Add new page'.
2. Try to add content on the editor

### Screenshots, screen recording, code snippet

![Wordpress_issue](https://user-images.githubusercontent.com/76043719/172106072-d78746d5-e8e5-42d1-bab0-1e738d14e4a6.png)

### Environment info

- WordPress 6.0
- Chrome Browser
- Using a Custom block theme
- Windows 10 and above

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. To better understand the problem and find its source: 

- Are you able to reproduce this after you have installed and activated the newest version of Gutenberg that is available through [the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/)?

- Could you share what block theme that you're using? 

- Open the browser's console (by typing control+shift+j) and including any error messages that appear there?

**Comment by carolinan** [comment]
Do you have any browser extensions enabled on Chrome but not Firefox, that may be interfering?

**Comment by apeatling** [comment]
Closing because of no response. If more info comes to light please reopen.
