### ISSUE TITLE
FSE - Homepage is displayed with "Page" instead of "Home" template 

### ISSUE THREAD

**Issue by jbonlinea** [WordPress/gutenberg#41586]
### Description

I'm using TwentyTwentyTwo.

I have selected a static page as home page.

Navigating to the site homepage in the broswer do display the expected page

however it use the "page" template and not the "home" template (my site is in french and the exact tempalte name is "accueil".

In FSE, when I try to edit the "home" template, I have something totally different from my actual homepage, and there is only written "home" in fse header, and not "home - page" with page in a grey box, as I have seen on some videos.

### Step-by-step reproduction instructions

That's a tricky question as I'm migrating from Gantry to Gutenberg/FSE, so there are many preceding, unrelated, steps. 

### Screenshots, screen recording, code snippet

![fsepage](https://user-images.githubusercontent.com/23659411/172486327-5507b869-1031-499b-8689-61f352609ab5.PNG)
![fsehome](https://user-images.githubusercontent.com/23659411/172486335-388c6b9c-4f9a-479f-9500-0c4e94e53edb.PNG)

### Environment info

WP 6.0
Gutenberg 13.3.0
theme TwentyTwentyTwo

Firefox or Chrome

PC on win10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi!
When you assign a static page as the homepage, the `home` template is used to display the blog, the list of latest posts.
This is for historical reasons, it can't be changed now without breaking sites. This behavior is the same in classic themes and FSE themes.
You can read more about it here: [Template hierarchy.
](https://developer.wordpress.org/themes/basics/template-hierarchy/#home-page-display)

You will see the `page` template if the page that you selected as the static page _uses that template._
If you had a custom template called "my-home" or similar, and you assigned that template to the selected page, you would see "my-home".

**Comment by jbonlinea** [comment]
Hi there, 

Thank's for your quick reply ! 

> Hi! When you assign a static page as the homepage, the `home` template is used to display the blog, the list of latest posts. This is for historical reasons, it can't be changed now without breaking sites. This behavior is the same in classic themes and FSE themes. You can read more about it here: [Template hierarchy. ](https://developer.wordpress.org/themes/basics/template-hierarchy/#home-page-display)
> 

Humm, you mean that with FSE, the home template will always be use to display the blog, weather I have chossen blog or static page as a home page ???



> You will see the `page` template if the page that you selected as the static page _uses that template._ If you had a custom template called "my-home" or similar, and you assigned that template to the selected page, you would see "my-home".

So you mean that if 
- I select a static page as homepage
- and want this page to use a specific template
--> I have to create "new" dedicated template for that page and select it in the page editor ???


OK OK, it works this way 

I'm just wondering why this "home" tempalte is named home, and not blog then ?! 
We would understand that this is not a template for the home page, but a normal template which has a post-loop 


---

side question, 

do the above only applies to pre FSE site that were migrated to FSE ? 
or all wp sites, event the ones which fresh install were on wp 5.9 or above with 2022 as default template ? 

thank's again

**Comment by carolinan** [comment]
_As far as I know,_ it is called home for historical reasons because when WordPress was first developed, the homepage was the blog.

The template hierarchy is the same in classic themes.

 
> I select a static page as homepage
>  want this page to use a specific template
> -> I have to create "new" dedicated template for that page and select it in the page editor ???

You can select an existing template from the select list in the Template section in the block editor, or create a new template.

When you want the page to **use a specific template**, the difference between a classic theme and FSE theme is that with FSE you can create new templates from within WordPress, without code.

**Comment by carolinan** [comment]
Please see https://learn.wordpress.org/workshop/creating-a-front-page-for-a-block-theme/

**Comment by annezazu** [comment]
I'm going to close this out as this isn't a bug or an active issue :)
