### ISSUE TITLE
Integrate Block Inspector sidebar with List View sidebar

### ISSUE THREAD

**Issue by johnstonphilip** [WordPress/gutenberg#41582]
## What problem does this address?
Right now there are 2 sidebars that I typically have open when using the block editor:
- The Block Inspector sidebar (on the right)
- The List View sidebar (on the left)

This ends up taking up a lot of screen space, and requires me to jump around a lot.

## What is your proposed solution?
Show the block inspector with the list view, toggling it open for the currently selected block:

## When no block is selected:
<img width="1792" alt="Screen Shot 2022-06-07 at 2 04 22 PM" src="https://user-images.githubusercontent.com/7538525/172451894-1804ab6e-9932-4a09-8133-a4b33fffd157.png">

## When block is selected
<img width="1792" alt="Screen Shot 2022-06-07 at 2 03 40 PM" src="https://user-images.githubusercontent.com/7538525/172451808-a4520d99-21eb-47e8-ad8e-730e61da93ad.png">

**Comment by ndiego** [comment]
I use the List View heavily to manage blocks, i.e. reorder them, copy/duplicate, etc. This is an interesting approach, and I can see the benefit, but I just wouldn't want it to negatively impact block management in any way. Might also get tricky with heavily nested blocks, and blocks with lots of settings. Once you install a couple of block extension plugins, those block setting sidebars get mighty long 😅

**Comment by johnstonphilip** [comment]
@ndiego I can definitely see that! 

My initial thoughts:

- Nesting isn't really a problem because you still only ever have one block selected at any given time. The indentation of the block settings doesn't have to increase just because it's nested.
- I'm not sure sidebar length is really an issue either because it's either long on the right or long on the left.

**Comment by critterverse** [comment]
I agree with @ndiego about the List View being a location primarily for block management and needing to be legible as an overall document outline. Going to close this issue out since allowing folks to edit visual attributes from this location seems confusing and seems like it would interfere with the intended use of the List View.

**Comment by johnstonphilip** [comment]
I'd like to get a few more opinions if that's ok!

**Comment by johnstonphilip** [comment]
I may also work up a PR for this

**Comment by johnstonphilip** [comment]
On second thought, I don't want to fight an uphill battle. Re-closing 🙂
