### ISSUE TITLE
Extra spaces in search block / button markup

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#41608]
### Description

Presumably with the addition of https://github.com/WordPress/gutenberg/pull/40260, an extra space is added before the wp-element-button class on buttons found in the search block:

### Step-by-step reproduction instructions

1. Go to front end of website
2. Inspect search form button
3. See below

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/486261/172698938-20e733c4-5ff0-4afe-8719-7e486d1d220f.png)

### Environment info

WordPress 6.0, Gutenberg 13.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bgardner** [comment]
Noting that in the screenshot above, there are other instances of spaces after class names as well.

**Comment by skorasaurus** [comment]
I think the cause of the extra space is from https://github.com/WordPress/gutenberg/blob/5bc74faca3458108d3dbd1af315ff38765a159e6/packages/block-library/src/search/index.php#L105 made by @scruffian ; maybe he has an idea whether it was intentionally included or if it's an accident.

**Comment by scruffian** [comment]
This was an accident. Feel free to raise a PR to remove it!

**Comment by scruffian** [comment]
There's a fix here: https://github.com/WordPress/gutenberg/pull/41746
