### ISSUE TITLE
Page templates are no longer displaying in editor

### ISSUE THREAD

**Issue by DeoThemes** [WordPress/gutenberg#41617]
### Description

Before Gutenberg 13.4 update we were able to choose page templates from the dropdown.
![_220609135830](https://user-images.githubusercontent.com/16485360/172775051-760e097b-c3c2-4c54-8798-d7d0ecf46c5c.png)

Now it's no longer working, page templates are not recognized by the editor.
![_220609140837](https://user-images.githubusercontent.com/16485360/172776563-88973590-e278-4889-8f16-178b0575b82e.png)

Page template created like so and placed in **page-templates** directory.
```
<?php
/**
 * Template Name: Full-width Contained
 */
```

This is happening in there is **block.json** file present in the theme directory.

### Step-by-step reproduction instructions

1. Activate Gutenberg 13.4
2. Edit any page
3. No page template dropdown displayed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
Thanks for creating the issue @DeoThemes! I'll look into this.

**Comment by skorasaurus** [comment]
Thanks for the quick repair on this; this has been affecting me as well.
