### ISSUE TITLE
Add method to name custom entity props 

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#41637]
## What problem does this address?
When `useEntityProp( 'root', 'site', 'title' )` is used, the entity is named "Title" within the confirmation step when saving changes. 

Is there a method for naming custom entity props, to improve the UX of editing/saving them? Currently the `option_name` displays, instead of using a proper title, which makes it less clear what's actually being saved.   

## What is your proposed solution?
Have a method for assigning a name/title that displays when saving an entity prop, instead of the option_name.

#### Modifying the site title entity, displays as "Title"
<img width="280" alt="CleanShot 2022-06-09 at 12 11 01@2x" src="https://user-images.githubusercontent.com/1813435/172894386-db7f679a-3359-43b5-8d92-36be282440ef.png">

#### Modifying a site option entity, displays the `option_name`
![CleanShot 2022-06-09 at 12 07 18@2x](https://user-images.githubusercontent.com/1813435/172894514-9b3c671b-2b1a-4192-982f-a942e27a3e88.png)

**Comment by adamziel** [comment]
It looks like each Site property is listed separately in that sidebar:

https://github.com/WordPress/gutenberg/blob/56df22dd163cd1823bcef7cbdfb8679eac8507b4/packages/editor/src/components/entities-saved-states/index.js#L57-L64

The culprit is that some properties use a human-readable label such as "Title", but the other ones are just passed verbatim, which is what you see. I wonder what a solution would look like, aside of course of allowing the developer to specify that 🤔

**Comment by adamziel** [comment]
To document some thoughts from slack,

Rich said:

> If I'm updating a site setting. Then having it say a human readable title would be better than the option name

To which Adam replied:

> A larger list of hardcoded labels would be an easy step to making it better. Ideally it would cover all the site options shipped with core. Then,  there are custom options provided by plugins, I guess plugins would have to provide these labels.

**Comment by adamziel** [comment]
A minimal improvement would be adding more settings to this list:

https://github.com/WordPress/gutenberg/blob/56df22dd163cd1823bcef7cbdfb8679eac8507b4/packages/editor/src/components/entities-saved-states/index.js#L23-L30

Then, to allow plugin authors to supply their own labels, we'd likely need to create a new filter and then apply it to that list using `applyFilters` from `@wordpress/hooks`. Perhaps around the following line?

https://github.com/WordPress/gutenberg/blob/56df22dd163cd1823bcef7cbdfb8679eac8507b4/packages/editor/src/components/entities-saved-states/index.js#L61

**Comment by Mamaduka** [comment]
Maybe `labels` can be a part of the [`register_setting`](https://developer.wordpress.org/reference/functions/register_setting/) API. It currently supports the `description` argument. Then we'll need to figure out how to load this data for setting entities.

**Comment by ghost** [comment]
Subscribed. Would really like to see this feature in an upcoming update.
