### ISSUE TITLE
Responsive images and image linking

### ISSUE THREAD

**Issue by trenzterra** [WordPress/gutenberg#4163]
## Issue Overview
In Gutenberg, when inserting an image block, there does not seem to have an option to link to the original media file, as with the classic editor.

A more concerning problem is that Gutenberg does not seem to work at all with responsive images and srcset as implemented in WordPress 4.4. A post created with Gutenberg will always load the full size image regardless of viewport size.

## Expected Behavior
Gutenberg should implement an option to link to original media file or attachment page, as per the classic editor. Currently, the gallery block does this.

In addition, responsive images should work as per the classic editor.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mtias** [comment]
See #869 for responsive images.

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/pull/4898 did this.

**Comment by hvianna** [comment]
I see this has been closed a while ago, but couldn't find any further mention of the option to link the image to the original media file or attachment page. Does anyone care to comment on whether this is a planned feature?
