### ISSUE TITLE
PostTaxonomiesHierarchicalTermSelector in filter create infinite loop

### ISSUE THREAD

**Issue by yanmorinokamca** [WordPress/gutenberg#41661]
### Description

In packages/editor/src/components/post-taxonomies/README.md, 
the last example says to use wp.editor.PostTaxonomiesHierarchicalTermSelector in the editor.PostTaxonomyType

While testing, I got infinite loop. I think the problem is that PostTaxonomiesHierarchicalTermSelector was exported as a wrapped component with withFilters('PostTaxonomyType') and seems to call the hook in a infinite loop.

It doesn't happen with OriginalComponent because this one is not wrapped.

### Step-by-step reproduction instructions

1. Use last example of post-taxonomies README
2. Open a page with gutenberg 12.6+ and the custom taxonomy
3. experience infinite loop...

### Environment info

wordpress 5.9 with gutenberg 12.6 or 13.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
Related #38419.
