### ISSUE TITLE
Cover block HTML error using featured image, fixed background, minimum height

### ISSUE THREAD

**Issue by room34** [WordPress/gutenberg#41660]
### Description

When a cover block uses the featured image, is set to fixed background, and has a minimum height, the minimum height is ignored because the block is generating invalid HTML.

In this scenario, the front end `<div class="wp-block-cover">` tag contains two `style` attributes. This is because the editor inserts `style="min-height:nnnpx"` with “Minimum height of cover”, and the **cover.php** file is inserting a second one, containing `style="background-image:url(https://example.com/image.jpg)"` with the `preg_replace()` call in lines 46-51. That `preg_replace()` call erroneously assumes there's not already a `style` attribute in the HTML tag.

This could be fixed either with a much more complex regular expression, or by adding a conditional that first checks for the presence of `style="` in the string and then two different regular expressions.

### Step-by-step reproduction instructions

1. Create a Cover block.
2. Set the block to “Use featured image”.
3. Turn on “Fixed background” under “Media settings”.
4. Set a “Minimum height of cover” under “Dimensions”.
5. View the front end page.

### Environment info

WordPress 6.0. Not using Gutenberg plugin, but I've verified this code is unchanged in the latest release version of the plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by akasunil** [comment]
I have fixed this issue in PR [41693](https://github.com/WordPress/gutenberg/pull/41693). Request for review.

Thanks.

**Comment by room34** [comment]
Thanks! Looks to me like that should resolve the issue. I'm not authorized to review but I take it that will get sorted out so Im closing this issue.
