### ISSUE TITLE
target="_blank" is causing bug on "Attempt Block Recovery"

### ISSUE THREAD

**Issue by KoichaDev** [WordPress/gutenberg#41677]
### Description

It seems like using the RichText Component `target="_blank"` is causing to crash for some odd reason.  Is there any reason why this is happening?

### Step-by-step reproduction instructions

A simple example here applies to the Edit and Save component:

```
<RichText
   target="_blank" 
 />
```
             

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I tested the following code, and the `target` attribute was correctly assigned and the component was not broken:

```javascript
import { useBlockProps, RichText } from '@wordpress/block-editor';

export default function Edit() {
	return (
		<RichText
			{ ...useBlockProps() }
			target="_blank"
		/>
	);
}
```

We may be able to give you specific advice if you let us know with the following points:

- What error messages are displayed in the browser console?
- Why do you want to give the `RichText` component `target` attribute?

**Comment by KoichaDev** [comment]
> I tested the following code, and the `target` attribute was correctly assigned and the component was not broken:
> 
> ```js
> import { useBlockProps, RichText } from '@wordpress/block-editor';
> 
> export default function Edit() {
> 	return (
> 		<RichText
> 			{ ...useBlockProps() }
> 			target="_blank"
> 		/>
> 	);
> }
> ```
> 
> We may be able to give you specific advice if you let us know with the following points:
> 
> * What error messages are displayed in the browser console?
> * Why do you want to give the `RichText` component `target` attribute?

Hi @t-hamano! 👋

I actually found out I had to write it this way:

```js
<RichText
    target="_blank" rel="noreferrer noopener"
/>
```

Is there any specific reason why I had to write it like `target="_blank" rel="noreferrer noopener"` in order to work? 

1.  I didn't check the browser console (I will check it later since I don't have my work in front of my computer when I'm typing this message)

2. That is because I have created my own custom button block. The core/button block was lacking one of the functionality for example moving the button block element to the left, center, or right

**Comment by t-hamano** [comment]
One thing I am wondering is that `target` attribute does not need to be rendered on the editor, but should just be saved as an attribute.
This is because when you click on a block on the editor, a new window opens.

I think the rendering of `a` tag and `target` attribute should be defined in the `save` function.

The code for the button block might be helpful:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/button/save.js#L65-L74

**Comment by KoichaDev** [comment]
Adding the `target` attribute on the RichText editor doesn't open a new window which is a good thing!

Most definitive by looking at the official WP Button block library! I will take a look at it! Thanks for the help @t-hamano!

**Comment by t-hamano** [comment]
I'm glad to hear that I was able to help you.
I will now close this issue as resolved.
If you have any problems, please reopen.
