### ISSUE TITLE
Editor preferences not saving as expected

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#41676]
### Description

- Editor preferences are saved on the WordPress server since Gutenberg 13.2.0 but I am not able to get it working so far: https://github.com/WordPress/gutenberg/pull/39795 
- I have tested several websites, all without plugins. 

### Step-by-step reproduction instructions

- Start on a page and make changes to the editor settings, like enabling the "Top toolbar" or "Spotlight mode"
- Save the page as a draft.
- Visit the same page on another browser on another computer.
- Notice that the settings configured on the first computer are not visible here.

### Screenshots, screen recording, code snippet

Here's how I see it on my first computer:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18581859/173197925-daac5112-1e56-4f55-a9ea-c2fa8c33dd2f.png">

And here's how I see it on my other computer:

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/18581859/173197931-38150efe-00ba-4a04-a7a2-5a49a05a6249.png">

I tested on the "Site Editor" as well, but that has the same behavior. 

Here's how I see it on the first computer:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18581859/173198034-2b8de5c3-efba-4016-a0d3-210dd8fb38ec.png">

And on the second:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/18581859/173198048-c599ffbd-f636-40dd-9173-69cd77cb0a07.png">

### Environment info

- WordPress 6.0
- Gutenberg that's shipped with core WordPress.
- Firefox 101.0.1 on Mac 12.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by arunsathiya** [comment]
This is my first time using this feature, so I am not too sure if something changed between the announcement and recent releases.

Including keyword for search reasons: "save editor preferences"

**Comment by arunsathiya** [comment]
Just realized I have been testing this incorrectly. I was working with Gutenberg that ships in core WordPress, not the plugin version of Gutenberg. I tested the plugin version, and with Gutenberg 13.4.0, I see editor preferences save as expected. 

First computer:

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/18581859/173801743-0c2b9ee9-f9f4-4c6f-9723-ca59f7ff5dd3.png">

Second computer:

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/18581859/173801900-64e9b879-a04b-41b2-b42a-d6ba5001863f.png">

Closing as this is not a bug. @kathrynwp, could you help remove the bug label? Thanks!

**Comment by kathrynwp** [comment]
@arunsathiya Done!
