### ISSUE TITLE
Woo commerce product gallery issues

### ISSUE THREAD

**Issue by prasidhda** [WordPress/gutenberg#4168]
Woo commerce gallery products are not saving. All other external plugins are deactivated. 
WordPress version : 4.9.1
WooCommerceversion : 3.2.6
Gutenburgversion : 1.9.1

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by aduth** [comment]
Can you clarify whether this is still an issue?

Can you include any relevant error messages that you see? Is it that the content is simply not saved?

**Comment by aduth** [comment]
This was discussed in the Slack #core-editor weekly triage meeting: https://wordpress.slack.com/archives/C02QB2JS7/p1522944679000161

**Comment by prasidhda** [comment]
Woo commerce gallery is working fine now. 
Thanks for the great work.
