### ISSUE TITLE
Columns block with one-third/two-thirds split is labeled as "30/70"

### ISSUE THREAD

**Issue by room34** [WordPress/gutenberg#41699]
### Description

The description when hovering over the option says "Two columns; one-third, two-thirds split" and the actual percentages inserted with the block are 33.33% and 66.66%, but the icon for the option is labeled as "30/70". (Same goes for the reverse.)

### Step-by-step reproduction instructions

Insert a Columns block and observe the labels under "Select a variation to start with."

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
@WordPress/gutenberg-design there doesn't seem to be any indication on [the PR](https://github.com/WordPress/gutenberg/pull/19789) that introduced these labels as to why `30/70` was chosen, but at a guess rounding this way might have seemed to give a better at a glance indication of split than rounding to `33/67`.

It seems like rounding it to `33/66` gives a reasonably good indication of `one third/two thirds`, and removes the confusion of the difference between the button and the actual percentages applied to the block. Do you have any thoughts about updating the block from `30/70` to `33/66` ?

**Comment by room34** [comment]
I definitely think that would be an improvement. If it were possible to fit 33.33/66.66 it would probably be best, since those are the exact values being used. But I think anything that reasonably conveys 1/3 and 2/3 is appropriate, whereas I do not read 30/70 as that at all.

**Comment by jameskoster** [comment]
Here's what we're talking about for reference:

<img width="637" alt="Screenshot 2022-06-14 at 10 11 40" src="https://user-images.githubusercontent.com/846565/173540553-5c865e00-8ec1-4179-b428-6cd386195e39.png">

My first question is: do we actually need to display these labels? The icons alone seem fairly clear to me, while the labels add noise and potential for confusion. Obviously it needs to be accessible, but I believe that is handled by the `aria-label`.

Edit: I just checked the original PR and see the labels were originally added to make things clearer, haha. For me, it's not very successful for the columns block, but I'm keen to hear thoughts from other designers.

**Comment by room34** [comment]
Well now that I look at the whole thing without being so singularly focused, I see the even thirds are labeled “33/33/33” so I think it makes sense to do “33/66” or “33/67” for the ones we’re talking about here.

I see the appeal of removing the numbers altogether, but I think the icons alone may not be clear enough, since it’s a bit hard to discern the visual difference between the icons for 33/33/33 and 25/50/25. Also for accessibility we need to consider the labels regardless of whether they’re displayed for all users or not.

**Comment by jameskoster** [comment]
In the future it might be nice to combine the labels with the icons somehow:

<img width="714" alt="Screenshot 2022-06-14 at 13 03 23" src="https://user-images.githubusercontent.com/846565/173572711-769b3543-b9bc-4a1f-8775-906417bd13bd.png">


In any case for now I agree that updating "70 / 30" to "66 / 33" seems like a fair adjustment.
