### ISSUE TITLE
Notifications in editor cover the block tools

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#4172]
## Issue Overview

I updated a post in Gutenberg, and received the green success notification at the top. When I clicked on my top most block to edit it, the tools for editing that block were hidden under the notification bar.

## Steps to Reproduce (for bugs)

1. Update a post.
2. Click on top most block.
3. See the block tools hidden under success message.

Tested on Firefox Quantum.

## Expected Behavior

I expected enough space below the notification bar to see the block tools.

## Possible Solution

Add more space above the top block when a notification is present.

## Screenshots / Video

![g-overlay-notification](https://user-images.githubusercontent.com/617986/34359248-1d3240f0-ea0b-11e7-8c8e-4ccf93042b15.gif)

**Comment by youknowriad** [comment]
While we can add space there, It's possible to show several notifications at the same time and it won't be possible to make space for all of them.

**Comment by mapk** [comment]
@youknowriad, good point. Could each notification be inline with the content? So as each one appeared the content would just get pushed farther down? 

Then as each notification is closed by the user, the content moves up a bit. I think that would feel better than losing access to the block tools (and content) because they are hidden behind the msg. 

With the addition of more notifications, does more of the content get hidden behind them?

I haven't done any case studies so I'm not sure what's common practice out there right now. But the way it works currently felt odd to me.

**Comment by youknowriad** [comment]
> @youknowriad, good point. Could each notification be inline with the content? So as each one appeared the content would just get pushed farther down?

Well, this also has its drawbacks. If you scroll the page and submit the post for instance, you won't see the notification as hidden at the top (Granted we have the same issue now but we also have a PR fixing it)

**Comment by karmatosed** [comment]
I think it's important to consider this is a notification message and not a permanent UI element we're considering. When considering this we can in theory expect people to click to close to use tools. However, maybe what we need to add in is a timeout?

Inline has a lot of issues on 'not desktop' devices and for non-English languages. Inline also could impact other UI elements heavily. The flipside is having one place for notices can lead to ignoring by users. Right now tests are not showing that, but it's important to be observant about.

I would for now say let's not go inline and if I may close this issue. We can potentially increase the timing, but actually having a conscious click to close isn't that awful a behaviour, it means people will be seeing the message.
