### ISSUE TITLE
no Featured Image setting in Block Editor

### ISSUE THREAD

**Issue by Ken-theGrump** [WordPress/gutenberg#41727]
### Description

When publishing a post or a page, the Block Editor does not have the option of assigning a featured image to the document. I have to switch over to the classic editor to attach a featured image, then back to block editor for tuning the document. Often after doing that, the block editor finds elements that it has to "recover" to continue editing - depends on what blocks are in the document.

This behavior is the same regardless of which of several themes is activated on WP 6.0.

### Step-by-step reproduction instructions

Edit any post or page.
Save draft or publish the document.
Subpanel entry field is there for page extract, but no option for attaching a featured image.

### Environment info

- WP 6.0, Gutenberg 16.4.0, theme Charta (child), though the same thing happens in vanilla twenty-twenty-two
- 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by skorasaurus** [comment]
Does the featured image panel not display for you as indicated in the screenshot ? 
![image](https://user-images.githubusercontent.com/955351/173682657-b5ee3ed2-af10-4b0c-824e-9a98a7bca834.png)

Also does this happen when you are an administrator user or only as a different user?

**Comment by Ken-theGrump** [comment]
It displays like that in the clasic editor but not in the block editor. I will try disabeling all other plugins again and try to test more carefully.

**Comment by Ken-theGrump** [comment]
Oh whoops! Did Gutenberg update today or yesterday? It is now working as expected. Two days ago it was not.

I went in and started setting up to test by disabling other plugins just minutes ago. Before I disabled any others I looked to confirm the issue in the site's current working state. That featured image is now where it should be on both page and post edits.

But is response to [skorasaurus](https://github.com/skorasaurus)'s query - as administrator. That is the only role that edits anything on my two WP sites.

This thread can now be closed as solved.

**Comment by Mamaduka** [comment]
Thanks for the update, @Ken-theGrump.

**Comment by AhmadRaza9** [comment]
@Ken-theGrump 
I'm facing an issue:
Gutenberg image block setting showing on Page not showing in Post.
Please have a look at below images:

![image](https://github.com/user-attachments/assets/a38533eb-e463-477d-b2dc-b4e4cedba0a7)
![image](https://github.com/user-attachments/assets/795c64a5-9311-4cc6-950b-63f9cc9bac6f)
