### ISSUE TITLE
Documentation: Block Example Category Media Doesn't Exist

### ISSUE THREAD

**Issue by LukePettway** [WordPress/gutenberg#4174]
## Issue Overview
On the documentation page for Blocks, one of the example custom blocks uses the `media` category however it doesn't seem to work. From my understanding the current categories are (formatting | common | layout | widgets | embeds).  I wasn't sure if this was a piece of remaining code that needed to be updated, or that I simply missed a step or explanation of it. 

Here is the line:
```
	blocks.registerBlockType( 'myplugin/random-image', {
		title: 'Random Image',

		icon: 'format-image',

		category: 'media',

		attributes: {
			category: {
				type: 'string',
				source: 'attribute',
				attribute: 'alt',
				selector: 'img',
			}
		},
```
## Steps to Reproduce (for bugs)
1. Create a custom block javascript file
2. Set the category to `media` in the blocks.registerBlockType method
3. Go to add the custom block on the Gutenberg editor
4. The block does not appear

WP Version: 4.9.1
Gutenberg Version: 1.9.1

**Comment by youknowriad** [comment]
Good catch, we should probably use one of the available categories 👍
