### ISSUE TITLE
Query Loop Block: Unwanted Block Gap on Column

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#41756]
### Description

When a Columns block is used inside a Query Loop block, all the columns except the first one have an unwanted block gap that makes the content misaligned. The unwanted top margin can be seen only in the front end, but it doesn't seem to be a theme-specific issue.

### Step-by-step reproduction instructions

1. Go to the editor.
2. Add a Query Loop block
3. Add a Columns block and have that with more than 1 column
4. Add a post content(s) to each column
5. See that in the front-end 

### Screenshots, screen recording, code snippet

![Screenshot 2022-06-15 at 23 07 50](https://user-images.githubusercontent.com/908665/173940668-27f2f273-ee04-488e-b114-4044b139d9e4.jpg)

When you inspect the column we can see the following.
![Screenshot 2022-06-15 at 23 08 17](https://user-images.githubusercontent.com/908665/173940683-ae722e87-fd57-42e7-b917-12438ae975b8.jpg)

### Environment info

- WordPress 6.0, Gutenberg 13.4.0, Twenty Twenty Two, Block Canvas, Blockbase etc.
- Chrome, Mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
I think https://github.com/WordPress/gutenberg/pull/41827 will fix this.

**Comment by skorasaurus** [comment]
Closing since this should be fixed by #41287 ; please reopen if you are still experiencing this.
