### ISSUE TITLE
Default FSE template not workingby naming convention

### ISSUE THREAD

**Issue by galbaras** [WordPress/gutenberg#41759]
### Description

Before full site editing, WordPress determined the meaning of "default template" by the post type, post ID, post slug and the standard naming convention, e.g. single-product-slug.php > single-product.php > single.php > singular.php > index.php.

Full Site Editing should work the same, selecting templates according to the slugs in the order single-product-slug > single-product > single > singular > index.

This doesn't seem to be the case.

### Step-by-step reproduction instructions

1. Add a custom post type (`btp_work`, in my case)
2. Add a custom template to theme.json with the name `btp_work`
3. Create the theme file templates/single-btp_work.html with the appropriate block markup
4. Verify the template in the Full Site Editor
5. Check a page of type `btp_work`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by carolinan** [comment]
Hi!
I have not been able to reproduce this; can you add any more information about what your result is when you "check a page of type btp_work". ?

**Comment by galbaras** [comment]
Well, you would have to define the custom post type first. The particular post type probably doesn't matter, but here's the code I'm using:

```
register_post_type( 'btp_work', [
	'label'		=> 'Products',
	'labels'	=> [
		'name'					=>  'Products',
		'singular_name' 		=>  'Product',
		'add_new' 				=>  'Add new',
		'all_items' 			=>  'All Products',
		'add_new_item' 			=>  'Add new Product',
		'edit_item' 			=>  'Edit Product',
		'new_item' 				=>  'New Product',
		'view_item' 			=>  'View Product',
		'search_items' 			=>  'Search Products',
		'not_found' 			=>  'No Products found',
		'not_found_in_trash'	=>  'No Products found in Trash',
		'parent_item_colon' 	=>  'Parent Product', 
		'menu_name'				=>  'Products',
	],
	'public'				=> true,
	'publicly_queryable'	=> true,
	'exclude_from_search'	=> false,
	'show_ui'				=> true,
	'show_in_menu'			=> true,
	'show_in_rest'			=> true,
	'hierarchical'			=> false,
	'supports'				=> [ 'title', 'editor', 'author', 'excerpt', 'custom-fields', 'thumbnail', 'revisions', 'page-attributes' ],
	'has_archive'			=> true, 				
	'rewrite'				=> [ 'slug' => 'product', 'with_front' => true ],
	'query_var'				=> 'btp_work',
	'can_export'			=> true,
	'show_in_nav_menus'		=> true
] );
```

**Comment by carolinan** [comment]
Hi!
Full site editing themes use the same template hierarchy as classic themes.

I tried your code, and this is what I found:

- On first view of the custom post type on the front, I saw a 404.
- After saving permalinks, the template worked.

Is that the issue? It is not clear from the description, which is why I asked for more information.

**Comment by galbaras** [comment]
Sorry, I forgot to mention the permalink update, which is required due to the new rewrite rules in the type registration.

The issue is that with Twenty TwentyTwo, pages get the "Page" template, posts get the "Single Post" template, etc, and I want my custom post type to get the "Product" template by default, without having to assign it to each product.

I'm using a child theme of Twenty TwentyTwo. The "Product" template is defined in theme.json under "customTemplates" with

```
"name": "btp_work",
"title": "Product",
"postTypes": [
	"btp_work"
]
```

And in the subdirectory "templates", there's a file called btp_work.html (sorry, the file name was incorrect in my original post), which was loaded correctly into FSE and can be assigned manually to products (`btp_work` posts), but I can't find a way to make it the default for this post type.

**Comment by carolinan** [comment]
I am still not able to reproduce it, the correct template is showing for me,
I did not assign it to the new "product" that I created, I just viewed the front and confirmed that the test content I added to the HTML file showed.

Are you trying to add default blocks that show in the block editor? As opposed to the *template* editor?

**Comment by carolinan** [comment]
I think you still need to name it single-btp_work.html.
As far as I can tell, the correct template is used:
<img width="279" alt="Template section in block editor shows that the product is using single-btp_work" src="https://user-images.githubusercontent.com/7422055/174612739-6aa59311-8f18-4fbf-9324-7e50ca453c82.png">

**Comment by galbaras** [comment]
OMG, I was sure I'd tried that, but maybe not. This now works. Thank you so much!
