### ISSUE TITLE
New Block: Post Comments Numbers

### ISSUE THREAD

**Issue by daviedR** [WordPress/gutenberg#41757]
## What problem does this address?

In classic themes, we often see `x Comments` info or `Leave comments` link in the blog post entry meta. This info are usually created using the `comments_popup_link` function.

In Gutenberg, we can't find a block that works like that. I tried the `Post Comments Title` block, but it has few issues:

- It's a heading tag.
- Text are default to `x responses`.

## What is your proposed solution?

As we already have `Post Author`, `Post Date`, `Post Categories`, `Post Tags` block, we might want to add a new block for the comments info.

**Comment by akasunil** [comment]
Post comment count block already exists. Check with latest Gutenberg pull. 

<img width="849" alt="CleanShot 2022-06-16 at 13 30 28@2x" src="https://user-images.githubusercontent.com/61308756/174022254-fbfc57b8-86d9-4d4d-8551-4796efebdea6.png">

**Comment by daviedR** [comment]
Thanks @sunil25393 I'll check them out. Any idea when this will be released in WordPress core?

**Comment by akasunil** [comment]
Next release probably. Not sure.

**Comment by daviedR** [comment]
Okay, thanks!

**Comment by TonyGravagno** [comment]
Not in 14.2.0 as of this date
