### ISSUE TITLE
Post title missing from Table of Contents & Document Outline

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#4177]
## Issue Overview
The post title is missing in the _Table of Contents_ & _Document Outline_.

Tested in Gutenberg v. 1.9.1

## Expected Behavior
_Table of Contents_ & _Document Outline_ should describe all headings, including the post title.

## Possible Solution
Display the post title as an `h1` in the _Table of Contents_ & _Document Outline_.

**Comment by mtias** [comment]
This would be good to add.
