### ISSUE TITLE
Color popovers: inconsistent styling

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#41787]
Here are the color palette, and custom color picker popovers:

<img width="832" alt="Screenshot 2022-06-17 at 12 50 49" src="https://user-images.githubusercontent.com/846565/174292937-4510cfc3-7147-43be-b3a8-a2b5165a01b9.png">

As you can see, they both have different shadow styles, and the custom color popover has no border while the color palette one does. It would be nice to align the appearance:

<img width="555" alt="Screenshot 2022-06-17 at 12 54 51" src="https://user-images.githubusercontent.com/846565/174293607-026190c8-a6df-483f-8a9a-2db68617cc50.png">

The padding is slightly different too, so we might consider correcting that as well.

**Comment by mirka** [comment]
This should be pretty simple.

1. Wrap it with `<DropdownContentWrapper paddingSize="none">`.
2. Remove these style overrides:

    https://github.com/WordPress/gutenberg/blob/12b7960010a858d3c97caf2641222ba1f255d34d/packages/components/src/color-palette/style.scss#L35-L40
