### ISSUE TITLE
Add keyboard shortcut for inline code

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#41796]
## What problem does this address?

Sometimes wrapping a string in backticks is inconvenient, and it'd be easier to have a keyboard shortcut. For instance, when you want to double click on a single word and then use a shortcut. Moving the cursor back and forth takes longer and more effort. 

Backticks also only works in the forward direction, see #40347.

The shortcut existed in the Classic editor, with `ctrl-alt-x`.

## What is your proposed solution?

Add a keyboard shortcut using `ctrl-alt-x`

**Comment by stefanrows** [comment]
Yea, I'm absolutely for it. I write a ton of programming content where I need to set single words, for instance, something like _print()_ to inline-code formatting, but doing it the default way with clicking is very cumbersome and time-consuming.
