### ISSUE TITLE
Additional CSS class(es) not loading properly for Embed-block in wp-admin

### ISSUE THREAD

**Issue by OlaAlsaker** [WordPress/gutenberg#41813]
### Description

The value in the "Additional CSS class(es)"-field on Embed-blocks is not loaded correctly in wp-admin. If you add a value to the field, publish the page (or save it as draft), and then refresh, the custom class will be missing. The value is stored in the database, and is shown when visiting the frontend, but as soon as you do some changes to the page and update it, the custom class will be overwritten. The additional CSS classes will then be gone.

### Step-by-step reproduction instructions

1. Create a new post in wp-admin
2. Add the Vimeo- or YouTube-block to the page, and put in a valid URL (e.g. `https://vimeo.com/253989945`)
3. Select the block, go to the options panel, and open up "Advanced"
4. Add a random class to "Additional CSS class(es)", e.g. `test-class-123`
5. Publish the page
6. Refresh the edit-page in wp-admin
7. Find the "Additional CSS class(es)"-field - the class you added should now be missing
8. If you try to leave the page, it will tell you that you have unsaved changes

### Environment info

- WordPress version: 6.0
- Gutenberg plugin version: 13.4.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Thank you for this bug report. I was able to replicate this issue with embed blocks and WP 6.0, but only with the Gutenberg plugin (v. 13.6.0) active.

With Gutenberg deactivated, the additional CSS class is preserved.

@ramonjd - was wondering if you might be able to take a peek at this since it looks like you're working on block-editor styles, and perhaps there's been a regression somewhere? Thanks!

**Comment by ramonjd** [comment]
> @ramonjd - was wondering if you might be able to take a peek at this since it looks like you're working on block-editor styles, and perhaps there's been a regression somewhere? Thanks!

Thanks @kathrynwp 

Looking at the code, I believe [this line](https://github.com/WordPress/gutenberg/pull/35326/files#diff-ef12826bc6a57e80852c9800c4bb8db0157db2b1f1418686fc85088e5438bb78R150)  is affecting custom classnames. 

When refreshing the editor, `getMergedAttributes( true )` strips existing classnames and makes the post dirty, even if there aren't any changes. Saving the post will remove any previous custom classnames.

@fluiddot I don't have much context on the change in https://github.com/WordPress/gutenberg/pull/35326. 

Is there any way to persist custom classnames in the field?

**Comment by fluiddot** [comment]
> @fluiddot I don't have much context on the change in #35326.
> 
> Is there any way to persist custom classnames in the field?

Hey @ramonjd, thanks for the ping 🙇 . I have low bandwidth currently to check this, but let me try to spare some time in the next few days for giving a quick look and posting a new comment with my findings.

**Comment by carolinan** [comment]
I can confirm that because the CSS class is removed, it also breaks custom block styles registered with [`register_block_style()`](https://developer.wordpress.org/reference/functions/register_block_style/)

This has also been reported on [trac 57461](https://core.trac.wordpress.org/ticket/57461):

> Registering a block style for the core Embed or Video block works as expected initially and the block style class is applied (e.g. is-style-test-custom-block-style). When opening a page in the editor that contains one of these styled blocks, the class associated with the block style is removed without any user interaction.

> The issue can be replicated using a vanilla install of WordPress 6.1.1 with the Twenty Twenty-Two theme active, though it will likely happen with any other built-in theme as well. Add a child theme or a simple plugin to register a block style for the core/embed block. Create a page, embed something using the core embed block, and apply the registered block style. Save and preview, you should see the class associated with the block style in the HTML source. Now edit that same page and the class associated with the block style will be removed.

**Comment by exonianp** [comment]
I can confirm that this is also occuring to me.

**Comment by bahia0019** [comment]
Looks like this is still an issue. I just got off a zoom call with a client demonstrating the behavior.
However this was without the Gutenberg block activated unlike the experience @kathrynwp had.

@fluiddot Is this something you can have a look at for a potential fix?

**Comment by fluiddot** [comment]
> Looks like this is still an issue. I just got off a zoom call with a client demonstrating the behavior. However this was without the Gutenberg block activated unlike the experience @kathrynwp had.
> 
> @fluiddot Is this something you can have a look at for a potential fix?

@bahia0019 sorry for the delay in checking this issue, I had it in my backlog but couldn't devote time to work on it 🙇. I still don't have too much bandwidth to check it but I'll try to prioritize it. I hope I can share a potential fix in between this and next week 🤞 . Thanks!

**Comment by twstokes** [comment]
👋 Hey @derekblank - would you mind taking the baton from @fluiddot on this one? Thank you!

**Comment by derekblank** [comment]
I was able to replicate the issue with Embed blocks on WordPress 6.1.1, both with and without the Gutenberg 15.2.4 plugin activated. In both cases I noted that any custom classes that were added did appear in the HTML source code of the actual post itself, but not within the input of the Advanced options in the editor.

I also tested on the Mobile Gutenberg editor using WordPress iOS 21.7.2, and experienced similar behavior where any input is not persisted in HTML mode:

1. Create a new post using the mobile editor using the WordPress iOS or Android app
2. Add the Embed-, Vimeo-, or YouTube-block to the page with a valid video URL
3. Switch to HTML mode using the Options menu (three dots, top right)
4. Add a custom class to the `class` attribute of the parent element, e.g.: `<figure class="test-class-123 ...">`
5. Press Publish
6. Note that the custom class that was just added disappears before the post is published

I've created a companion issue for this behavior (with a video example) on the Mobile Gutenberg project as the Embed block logic is shared between the two projects: https://github.com/wordpress-mobile/gutenberg-mobile/issues/5527

I believe @ramonjd is correct in [this comment](https://github.com/WordPress/gutenberg/issues/41813#issuecomment-1176863750) that `getMergedAttributes( true )` is removing custom input [here](https://github.com/WordPress/gutenberg/pull/35326/files#diff-ef12826bc6a57e80852c9800c4bb8db0157db2b1f1418686fc85088e5438bb78R150). I'll investigate further on the context of this change with @fluiddot and find the best place to provide a patch without affecting the intended behavior of that change.

**Comment by fluiddot** [comment]
I recently reviewed [a PR](https://github.com/WordPress/gutenberg/pull/41141) that fixes a [similar issue](https://github.com/WordPress/gutenberg/issues/29641) to this one. In fact, using the changes from [that PR](https://github.com/WordPress/gutenberg/pull/41141) I couldn't reproduce this issue, so it will also address this one 🎊.

**Comment by giandomaca** [comment]
I think the problem is not solved. I have an Embed block inside a column and every time the page is reopened to be edited, the block loses the additional classes.

- I tried reinserting the block from scratch but it didn't work.
- I have tried on multiple Wordpress installations, locally and in production, and the problem persists.

### Environment info
WordPress version: 6.2.2

**Comment by fluiddot** [comment]
> I think the problem is not solved. I have an Embed block inside a column and every time the page is reopened to be edited, the block loses the additional classes.
> 
> * I tried reinserting the block from scratch but it didn't work.
> * I have tried on multiple Wordpress installations, locally and in production, and the problem persists.
> 
> ### Environment info
> WordPress version: 6.2.2

@giandomaca I tried to reproduce this issue by adding an Embed block inside a column of a Column block, but I can't reproduce it. The additional classes I added persist after reopening the post/page. I'm wondering if you could share the Gutenberg version you are using, in case it doesn't include this fix (it was released in Gutenberg 15.4). Thanks 🙇 !

**Comment by shanemac10** [comment]
I am currently experiencing this issue with a custom container block I created, that uses `<InnerBlocks />`. The block is being registered with ACF Pro's `acf_register_block` using the the `'supports'`  option set with the `'jsx'   => true`. I don't believe this is an ACF issue, but if I need to redirect to them, let me know. 

All of my nested blocks are missing their Advanced options, now that the page had been reloaded. The `Additional CSS class(es)` that were added previously, are being displayed on the front end.

@fluiddo Thank you 🙏

Current WordPress Version 6.3.1
ACF Pro is up to date as well

---
UPDATE: I just discovered that if the parent container block is in "Preview" mode, the inner child blocks have their full options available, and you can drag and drop, rearrange, duplicate, etc. But if the parent container block is in "Edit" mode, then all the child blocks get stripped of most of their options and appear to be locked down. This might be by design for some reason, and if so, then perhaps this is a serious UX issue, because this was not intuitive for me... at all.
