### ISSUE TITLE
Padding visualizers do not work properly in the Site Editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#41823]
### Description

In the site editor blocks that use the placeholder illustration (see `PostFeaturedImage` and `Cover`) have an off-center bug for the dimensions visualizer.

### Step-by-step reproduction instructions

1. Use 13.5 RC1
2. Add a cover block
3. Set the cover block to use a featured image
4. Add padding and notice the visualizer is off

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/174665454-c9fc4dbd-1932-4ffc-870b-dff65877e629.mov

### Environment info

- GB 13.5RC1
- WP 6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by draganescu** [comment]
I am looking into this.

**Comment by draganescu** [comment]
I cannot reproduce on trunk @annezazu - what am I doing wrong?

https://user-images.githubusercontent.com/107534/174811476-6e4f6806-f1a1-42b4-befb-9719af4487af.mp4

**Comment by annezazu** [comment]
@draganescu try doing it in the Site Editor rather than Post Editor! I find it only happens in the Site Editor upon further testing.

**Comment by draganescu** [comment]
Yes, in the site editor it seems the visualizer has a problem as the same can be seen with the post featured image block as well, so it does not look like a cover block issue.

**Comment by annezazu** [comment]
Ah ha. I'll update the title of this issue :)

**Comment by jasmussen** [comment]
I left [some additional comments here](https://github.com/WordPress/gutenberg/pull/42085#issuecomment-1239176927), and it seems as if the `useRootPaddingAwareAlignments` property might play a factor as well.
