### ISSUE TITLE
WP HTML Templates - Any way to get bloginfo() or the path to the theme folder?

### ISSUE THREAD

**Issue by fredy31** [WordPress/gutenberg#41846]
So in our new architecture for themes, we want to use Gutenberg themes with html templates.

Problem is, when we need to call anything from the theme folder, we have to use the full URL. So if the folder name would be to change for any reason (and we might change it) well, every image loaded from the template breaks.

In PHP, you can simply run the function `bloginfo()` to get that. But is there the same thing in HTML templates?

Example:
````html
    <!-- wp:template-part {"slug":"top","tagName":"div","align":"full","className":"l-top","layout":{"inherit":true}} /-->
    <!-- wp:template-part {"slug":"header","tagName":"header","align":"full","className":"l-header","layout":{"inherit":true}} /-->
    <!-- wp:group {"tagName":"main","align":"full", "className":"l-main t-page", "layout":{"inherit":true}} -->
    <main class="wp-block-group alignfull l-main t-page">

        <!-- wp:cover {
            "url":"/wp-content/themes/base-theme/assets/img/default-cover.jpg",
            "dimRatio":0,
            "isDark":false,
            "align":"full",
        } -->
        <div class="wp-block-cover alignfull is-light is-style-title-banner">
            <span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span>
            <img class="wp-block-cover__image-background" alt="" src="/wp-content/themes/base-theme/assets/img/default-cover.jpg" data-object-fit="cover"/>
            <div class="wp-block-cover__inner-container">
                <!-- wp:post-title {"level":1} /-->
            </div>
        </div>
        <!-- /wp:cover -->
        <!-- wp:yoast-seo/breadcrumbs /-->
        <!-- wp:post-content {"className":"wp-container__inner","layout":{"inherit":true}} /-->

    </main>
    <!-- /wp:group -->
    <!-- wp:template-part {"slug":"footer","tagName":"footer","align":"full","layout":{"inherit":true}} /-->
````

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; as far as I understand, it is not yet possible. :( 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/20966. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

Please reopen if that issue does not address what you're looking for.
