### ISSUE TITLE
Make it easier to unset a color value

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#41866]
When you set a color, it currently requires two clicks to reset it:

https://user-images.githubusercontent.com/846565/175000591-82c0d1a2-6d6d-4afd-ba76-aa33ddfb574a.mp4

This feels like an operation that might be better served by a single-click procedure. Perhaps we could add the reset (-) icon to the color button?

<img width="302" alt="Screenshot 2022-06-22 at 10 59 06" src="https://user-images.githubusercontent.com/846565/175001835-b0ea1cec-d7f1-4085-be1d-f2e0de7de90f.png">

While we're here, it might also be good to reduce the vocabulary. Notice how the popover has a "Clear" action, while the design tools popover talks about "Reset"ing.

**Comment by jasmussen** [comment]
Could the minus appear on hover/focus?

**Comment by jameskoster** [comment]
Totally.

**Comment by mirka** [comment]
Should we be concerned that a basically identical pattern (and icon) is being used as a "Remove" button for PaletteEdit? I wonder if we should have separate icons for Clear/Reset things vs. Remove/Delete things.

**Comment by jasmussen** [comment]
Conceptually the fact that they are the same aids understanding. In both cases you are removing a customization.

**Comment by Divyesh71** [comment]
Hello Folks,

I am testing WordPress 6.8 Beta 1, and I suggest adding a "RESET" link/button here instead of the "-" icon.  

Please see the attachment for reference.  

Thanks!

![Image](https://github.com/user-attachments/assets/db9e74b1-e471-45c0-bcda-c3a8f113c0e4)

**Comment by SAndrrew** [comment]
![Image](https://github.com/user-attachments/assets/0242c1f4-514a-4c94-afb3-fbf748054cb8)

I have tried out this but am suggesting whether it's possible to look into having the reset word instead of a minus (-).
Like some of the tools like Padding, the margin have the reset, so I believe it would be easily seen.
