### ISSUE TITLE
Color palettes: Custom colors only appear in the Site Editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#41867]
### Description

Upon opening the color palette popover, I only see my Custom colors in the site editor.

| Post Editor | Site Editor |
| --- | --- |
| <img width="603" alt="Screenshot 2022-06-22 at 11 22 00" src="https://user-images.githubusercontent.com/846565/175007914-43c2b1f2-86e0-42dd-8322-8d7b12efb98b.png"> | <img width="599" alt="Screenshot 2022-06-22 at 11 22 14" src="https://user-images.githubusercontent.com/846565/175007928-5928e3bd-938e-4f96-81d7-7c77507ea4c2.png"> |

### Step-by-step reproduction instructions

1. In the Site Editor create at least 1 custom color
2. Select a block on the canvas and change a color – notice that the custom color palette is present
3. Edit a post or page, and select a block
4. Change a color – notice that the custom color palette is _not_ present.

**Comment by talldan** [comment]
@jameskoster I tested and it seems to be working ok for me:
![Screen Shot 2022-06-28 at 4 37 48 pm](https://user-images.githubusercontent.com/677833/176134088-871f6309-0f8d-4f0c-96cd-07f06f9f28c2.png)

Had you definitely saved the custom color in the site editor before loading the post editor?

**Comment by jameskoster** [comment]
Hah, maybe not because it seems to be working now.
