### ISSUE TITLE
Cover Block missing margin in dimensions panel

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#41879]
### Description

The cover block has padding, but not margin.  It's helpful to eliminate the margin above and/or below a cover block in certain design cases.  For example, if you have multiple cover blocks in a row with different background colors, it looks odd if you have the default theme blockgap in between each.  For now, I add a class mt-0 or mb-0 but would love to see Margin added to the Dimensions panel.

Thanks!

### Step-by-step reproduction instructions

1. Add cover block with a black background
2. Add second cover block right after with a red background
3. Notice space in between with no way to remove the margin

### Screenshots, screen recording, code snippet

<img width="300" alt="Screen Shot 2022-06-22 at 9 43 55 AM" src="https://user-images.githubusercontent.com/1781226/175075428-c5465381-86d3-4463-8f83-597c13e42bb0.png">
<img width="730" alt="Screen Shot 2022-06-22 at 9 48 12 AM" src="https://user-images.githubusercontent.com/1781226/175075578-ac580733-b034-4f5c-9120-a1ed38db9ae6.png">

### Environment info

- WP 6.0
- Gutenberg 13.4.0
- Mac
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by akasunil** [comment]
Block dimension are used to manipulate block inner design, we cant set margin around the block with block setting. it should be handled by custom class as you have did.

**Comment by bradhogan** [comment]
@sunil25393 Headings have a margin option as well which is not an inner design.  I have to imagine I'm not the only designer who uses consecutive cover blocks and while it's easy for me to add a class like mt-0 or mb-0 in the Advanced panel, it's not intuitive for an end-user without design/dev experience to do so.

**Comment by HILAYTRIVEDI** [comment]
I think it's an easy feature addition as in the latest versions of the Gutenberg by only adding the support for the Gutenberg in the block.json file will do the work. I tested that.

`"spacing": {
			"padding": true,
			"__experimentalDefaultControls": {
				"padding": true
			},
			"margin": true
		}`


This will do the work.

**Comment by akasunil** [comment]
@bradley2083 please check [33835](https://github.com/WordPress/gutenberg/pull/33835) for more details.

**Comment by bradhogan** [comment]
@HILAYTRIVEDI can you share your full block.json code?  Where are you placing that, just in the main theme directory along with theme.json?

**Comment by bradhogan** [comment]
@sunil25393 Yes, it seems as those multiple people were in favor of adding margin, then it got put on hold.  Again, this is a UI issue when adding multiple / consecutive cover blocks.  Most modern designs include this at some point in a design so it's odd that we wouldn't want to give WordPress creators an easy solution to preventing an odd margin between two heros/covers.

**Comment by ramonjd** [comment]
Hi folks!

As @sunil25393 mentioned, there was a previous PR to implement margins for cover block. There was, however, some uncertainty with how it would co-operate with the [UI controls](https://github.com/WordPress/gutenberg/pull/33835#issuecomment-947397161). 

@jasmussen What do you think? Are those concerns still valid? Or does the benefit of controlling the top and bottom margins of cover blocks outweigh them at this stage?

It looks like the visualizer is looking better since https://github.com/WordPress/gutenberg/pull/40505

![2022-06-27 12 09 35](https://user-images.githubusercontent.com/6458278/175847115-3ccd1c5d-db8a-4775-9ed3-2da68ca874fe.gif)

I've optimistically added a PR to add it back in https://github.com/WordPress/gutenberg/pull/41963 😄

**Comment by bradhogan** [comment]
Definitely not ideal, but here's what I'm adding to my theme for the time being until this gets added (fingers crossed).

```
.wp-block-cover + .wp-block-cover {
	margin-top: 0 !important;
	margin-bottom: 0 !important;
} 
```
