### ISSUE TITLE
"Move to" not showing when there's only one block at top level

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#41889]
### Description

"Move to" in the block settings dropdown only shows if there is more than one top-level block. For example, if all the post content is contained inside a Columns block, it is not possible to use the "Move to" feature on any of its inner blocks.

### Step-by-step reproduction instructions

1. In a post, add a Group block, and add multiple blocks inside it.
2. Verify that "Move to" doesn't show in the block settings dropdown for any of those blocks inside the Group block.
3. Add another block outside of the Group block.
4. Now "Move to" should show for all blocks.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Related #33158.
