### ISSUE TITLE
State Value is Resetting on setPreviewDeviceType Update to Desktop

### ISSUE THREAD

**Issue by pickplugins** [WordPress/gutenberg#41888]
### Description

I am not sure if it's a known issue or not. 
Facing this issue when I try to change the preview **Desktop** from another device type(Mobile, Tablet) **state** value is resetting to default, I have tested other states, but happening the same.

Please note this is happening for Desktop only not for other devices. 

Here is the video
https://youtu.be/lkMzkKjGGPw

I have also tested by **setPreviewDeviceType** method and default preview button at the top, the same things happening.

`const { __experimentalSetPreviewDeviceType: setPreviewDeviceType,} = wp.data.dispatch('core/edit-post')
setPreviewDeviceType(screen);`

### Step-by-step reproduction instructions

Check the video on screenshot

### Screenshots, screen recording, code snippet

https://youtu.be/lkMzkKjGGPw

### Environment info

WP -6.0 Gutenberg - 
Chrome
Desktop on Windows10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Unlike Desktop preview, Tablet / Mobile preview is rendered as iframe editor.
I believe this is why the state is not inherited.

I think that you will be able to share state through the store if you create [a custom store](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#register).

Or, if you are developing a block and expect to save the value in the block, I think attirbutes could solve that.

**Comment by pickplugins** [comment]
@t-hamano [t-hamano](https://github.com/t-hamano) Thank you for your reply, 

yes, I am working on the block. we have already moved to attirbutes way to solve our issue, but I guess this is not a proper solution because we may need to solve it by creating a custom store.

**Comment by t-hamano** [comment]
If you use the value on the front end, attributes would be appropriate.
Otherwise, it is better to control them via a custom store.

In any case, I think this isn't gutenberg bug, so I'll close this issue.
If you find another problem, please feel free to submit a new issue.
