### ISSUE TITLE
Cover block should have an "Insert from URL" like Video Block does.

### ISSUE THREAD

**Issue by kauaicreative** [WordPress/gutenberg#41880]
## What problem does this address?
Cover block should have an "Insert from URL" like Video Block does.
Link to external resources without opening code view

**Comment by Mamaduka** [comment]
Probably a duplicate of #10853.

**Comment by akasunil** [comment]
@kauaicreative please check PR [41908](https://github.com/WordPress/gutenberg/pull/41908)
