### ISSUE TITLE
Post content deleted when adding column to template

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#41887]
### Description

When editing a post template in the single template editor by wrapping the Post Content block inside a Columns block, the content of Post Content gets deleted (just the content, not the block itself).

### Step-by-step reproduction instructions

1. Add content to a post, save and publish.
2. In the post sidebar, go to Template section and create a new template
3. Locate the Group block that contains Post Content, and wrap it in a Columns block.
4. Add a second column to the Columns block.
5. Save and view post; verify the content is not longer there

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mtias** [comment]
Marking as high because of potential content loss.
