### ISSUE TITLE
Add a 'Compatibility' or 'What's Changed' page to the handbook

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#4190]
It would be nice to have a dedicated page or section in the handbook that documents all of the potentially breaking changes between the Classic Editor and Gutenberg.

Some things that this page might cover:

* Changes to the editor UI that are intentional – see https://github.com/WordPress/gutenberg/issues/4186
* Gutenberg equivalents for each of the Classic Editor extensibility endpoints – see https://github.com/WordPress/gutenberg/issues/4151
* Introduction of the `wp_blocks` Custom Post Type and `/wp/v1/blocks` endpoint – see https://github.com/WordPress/gutenberg/pull/4137#pullrequestreview-85633350

**Comment by karmatosed** [comment]
http://wordpress.org/gutenberg is a good start with the section on compatibility. That's not saying we shouldn't have a handbook section, but we can begin there.

**Comment by mtias** [comment]
Let's fold this into #4186.
