### ISSUE TITLE
Inline inserter too narrow and illegible on small screen devices

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#41917]
### Description

On smaller screens, the inline block inserter does not expand wide enough, which causes the block title within it to be illegible. 

### Step-by-step reproduction instructions

1. Create a new post with a small screen device, e.g. mobile phone. 
1. Click/tap a + button within within the post content (e.g. within a Group block) to open the inline inserter. 

### Screenshots, screen recording, code snippet

<details><summary>Recording: Gutenberg 13.5.0</summary>

https://user-images.githubusercontent.com/438664/175349621-6755f39a-0fe2-4727-9d8a-30db4c98c0f5.mov

</details>

<details><summary>Recording: WordPress 6.0</summary>

https://user-images.githubusercontent.com/438664/175349594-ef6c45f7-fd36-48a9-83be-6c38c4763d74.mov

</details>

<img width="323" alt="Inline inserter opened on a small screen contains illegible content because the inserter is too skinny" src="https://user-images.githubusercontent.com/438664/175351432-06d8add8-14c8-4ff3-b7e9-83579193f0b7.png">

### Environment info

- WordPress 6.0
- Gutenberg 13.5.0
- Theme: Twenty Twenty-Two
- iPhone SE (iOS 15.6)
- Safari

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
Can't reproduce this issue anymore.
