### ISSUE TITLE
Site Editor doesn't apply block conversions upon template load

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#41944]
### Description

Unlike the Post Editor, the Site Editor doesn't apply block conversions to the template content immediately upon loading.

By block conversions, I mean the sort of conversions done in [`convert-legacy-blocks.js`](https://github.com/WordPress/gutenberg/blob/fe7e96290ac41408d4f7a2ce4282a51f0357f7c1/packages/blocks/src/api/parser/convert-legacy-block.js) -- which typically involve changing a legacy block ID to a new one.

In the _Post_ Editor, those are run right upon loading, and are applied to the post content, as can be inspected in the Code Editor.

In the _Site_ Editor OTOH, while they _are_ applied upon loading, they are _not_ applied to the template content (as is once again reflected in the Code Editor). Instead, they're only applied once the template is saved (which typically needs at least one modification by the user in order to enable the Save button). This seems to have the potential for [unwanted side effects](https://github.com/WordPress/gutenberg/pull/40506#issuecomment-1164655191).

[Discovered](https://github.com/WordPress/gutenberg/pull/40506#pullrequestreview-957660031) while working on #40506.

### Step-by-step reproduction instructions

Try e.g. with #40506 

- On `trunk`, edit the "Single" template in the Site Editor to add the "Comments" block.
- Switch to the Code Editor and verify that the block's ID is `wp:comments-query-loop`.
- Switch back to the Visual Editor.
- Switched to this branch, and reload the template in the Site Editor.
- Open your browser console, and verify that it contains an "Updated blocks: core/comments` message.
- Switch to the Code Editor. Verify that the block ID is still `wp:comments-query-loop` there ❌ 
- Switch back to the Visual Editor.
- Make a minor change to enable the 'Save' button, and save.
- Switch to the Code Editor. The block ID should now be `wp:comments`.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ockham** [comment]
cc/ @c4rl0sbr4v0 and @DAreRodz 

I thought that we might debug this by comparing stack traces for this when run from the Site Editor vs. the Post Editor.

For starters, I tried this:

```diff
diff --git a/packages/blocks/src/api/parser/index.js b/packages/blocks/src/api/parser/index.js
index 21bc8a952c..a9ab4f1893 100644
--- a/packages/blocks/src/api/parser/index.js
+++ b/packages/blocks/src/api/parser/index.js
@@ -272,6 +272,7 @@ export function parseRawBlock( rawBlock, options ) {
                        updatedBlock.originalContent
                );
                console.groupEnd();
+               console.trace();
                /* eslint-enable no-console */
        } else if ( ! validatedBlock.isValid && ! updatedBlock.isValid ) {
                validationIssues.forEach( ( { log, args } ) => log( ...args ) );
```

which for the Site Editor got me:
![Bildschirmfoto 2022-06-24 um 13 06 55](https://user-images.githubusercontent.com/96308/175529375-0b7f8011-a05b-4485-b838-76527fef9ad8.png)

(excerpt, the strack trace is much longer)

So it's apparently called from here: https://github.com/WordPress/gutenberg/blob/fe7e96290ac41408d4f7a2ce4282a51f0357f7c1/packages/core-data/src/entity-provider.js#L174

Let's try the same for the Post Editor 😄

**Comment by cbravobernal** [comment]
I hope this information can help with the debugging:

In serializer file, line 140
https://github.com/WordPress/gutenberg/blob/9161c288471b309d5798a96a50e2524170efe633/packages/blocks/src/api/serializer.js#L140

I tested using the same block structure in both post Editor and Site Editor. 
`innerBlocks` variable is empty on Site Editor, while on Post Editor returns an Array with blocks.

**Comment by ockham** [comment]
I've tried to debug this a bit more, but haven't been very successful so far 😕

One theory I had was that maybe the Site Editor's code editor simply doesn't reflect the updated blocks, but I had a hard time verifying -- the way that the respective editors are connected (and how they relate to `useEntityBlockEditor`, `EditorProvider`, etc.) is rather complex, and I'm not too familiar with the relevant code.

@Mamaduka @kevin940726 Judging from git blame, y'all might be a bit more familiar with this 😬 Do y'all maybe have an idea where this issue might stem from?

**Comment by ockham** [comment]
Digging a bit deeper.

The Site Editor's Code Editor gets its content here: https://github.com/WordPress/gutenberg/blob/2941a10db6bb51dac420dedbbe259973c3b3539a/packages/edit-site/src/components/code-editor/index.js#L26-L38

```html
<!-- wp:comments-query-loop -->
<div class="wp-block-comments-query-loop"><!-- wp:comments-title /-->
```

etc.

However, `blocks` is actually set properly by `useEntityBlockEditor`: https://github.com/WordPress/gutenberg/blob/2941a10db6bb51dac420dedbbe259973c3b3539a/packages/core-data/src/entity-provider.js#L155-L185

![image](https://user-images.githubusercontent.com/96308/176741305-e34eaa6a-ba8a-47af-9028-b8b6b27509ca.png)

Edit: In the above code, `contentStructure instanceof Function` is `false`, and thus, `content` is set to `contentStructure`, which is obtained here: https://github.com/WordPress/gutenberg/blob/2941a10db6bb51dac420dedbbe259973c3b3539a/packages/edit-site/src/components/code-editor/index.js#L26-L30.

Note that that `content` isn't updated by `useEntityBlockEditor` after parsing (and converting) blocks.

**Comment by ockham** [comment]
The Post Editor's Code Editor OTOH obtains `content` via `getEditedPostContent`: https://github.com/WordPress/gutenberg/blob/2941a10db6bb51dac420dedbbe259973c3b3539a/packages/editor/src/components/post-text-editor/index.js#L22-L25

![image](https://user-images.githubusercontent.com/96308/176751148-474a60a9-5adf-4b0a-a7b4-c4416c66bbf4.png)

I believe that the main difference w.r.t. the Site Editor's Code Editor (and `getEditedEntityRecord `) is the fact that `getEditedPostContent` uses the `blocks` as the source of truth for the content: https://github.com/WordPress/gutenberg/blob/2941a10db6bb51dac420dedbbe259973c3b3539a/packages/editor/src/store/selectors.js#L897-L898

**Comment by ockham** [comment]
In conclusion:

Both the Post Editor and Site Editor use `useEntityBlockEditor` to parse content into blocks. That parsing also applies legacy block conversions and deprecations. However, they are not automatically applied to `content` state.

The Post Editor's Code Editor gets its content via `getEditedEntityRecord`, which checks if it has been parsed into blocks, and if yes, returns new content based on those blocks. The Site Editor's Code Editor OTOH uses `content` state at face value (via `useEntityProp`).

The obvious fix is to make the Site Editor's Code Editor use `content` as obtained from parsed blocks. 

There's a chance that there are other parts of the Site Editor that erroneously use `content` state (rather than parsed blocks, once available ) as their source of truth; those might be subtle to find. I'm not 100% sure if [this side effect](https://github.com/WordPress/gutenberg/pull/40506#issuecomment-1164655191) (colliding class names) is due to this, or due to other reasons.
