### ISSUE TITLE
Saving a Draft post with an identical URL Slug breaks published post

### ISSUE THREAD

**Issue by raamdev** [WordPress/gutenberg#41953]
### Description

When the permalink structure is set to "Post name", it's possible for Gutenberg to save a draft post and populate the `post_name` field with a value that matches the `post_name` of a published post. 

This results in the published post returning a 404 error for logged-out visitors. For logged-in users viewing the published post, it results in the query for the published post including the draft post.

## Step 1
Set Permalink structure to `Post name` in Settings → Permalinks

![permalink-settings-post-name](https://user-images.githubusercontent.com/53005/175703896-1eba3ec5-b23e-4881-a899-05d78cda5a0c.png)

## Step 2
Publish a post with a slug `hello-world`; as expected `post_name` is assigned a slug of `hello-world`:

```
wp post get 1 --fields=ID,post_name,post_status
+-------------+-------------+
| Field       | Value       |
+-------------+-------------+
| ID          | 1           |
| post_status | publish     |
| post_name   | hello-world |
+-------------+-------------+
```

## Step 3
Create a new post with the same slug `hello-world` and save it as a Draft; as expected, no slug is assigned to `post_name`:

```
wp post get 20 --fields=ID,post_name,post_status
+-------------+-------+
| Field       | Value |
+-------------+-------+
| ID          | 20    |
| post_status | draft |
| post_name   |       |
+-------------+-------+
```

## Step 4
After saving the draft post, and without navigating away and coming back, place the cursor in the Permalink URL Slug field, press the TAB key, then click 'Save Draft' a second time:

![re-saving-permalink](https://user-images.githubusercontent.com/53005/175719180-ec95ab3a-74ba-473a-8b69-376a1f495520.gif)

Now `post_name` is populated with a slug that matches the published post:

```
wp post get 20 --fields=ID,post_name,post_status
+-------------+-------------+
| Field       | Value       |
+-------------+-------------+
| ID          | 20          |
| post_status | draft       |
| post_name   | hello-world |
+-------------+-------------+
```

With the draft post updated (incorrectly) to include a `post_name` value of `hello-world`, it now conflicts with the existing published post and creates these problems:

- For logged-out users, the original published post returns a 404
- For logged-in users, the query for the original published post includes the draft post (if you visit the original published post, you'll see the draft post + the published post displayed)

### Environment info

- WordPress 6.0, Twenty Twenty One (also confirmed bug exists in WP 5.9.3)
- Google Chrome v102.0.5005.115 (Official Build) (arm64), Safari v15.5 (17613.2.7.1.8)
- Macbook Pro with macOS 12.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting the issue. I think I found a report of this in a trac ticket here - https://core.trac.wordpress.org/ticket/52422. @raamdev does that look like the same issue?

I think a fix for this belongs in WordPress core—the issue has likely arisen because since the block editor was launched the REST API is now being used to save post data, so it might be that some validation is missing.

It looks like a fix will soon be committed on that trac ticket. Are you happy for me to close this issue in favor of the ticket, @raamdev?

**Comment by raamdev** [comment]
@talldan Thanks for finding that Trac ticket! That is exactly the same issue. After reviewing and testing the associated patch I can confirm that it fixes this bug. I'll go ahead and close this issue as a duplicate of https://core.trac.wordpress.org/ticket/52422.
