### ISSUE TITLE
Allow creating more specific templates from header dropdown

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#41958]
With #37407 partially accomplish, we should start looking at other relevant pathways to creating more specific templates. For example, from the "Archive" template you should be able to spin off a more specific date archive:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/548849/175780559-583e3801-2e50-4ac8-8c8c-b18c3a236ad4.png">

From the generic category template you should be able to create a more specific category-{slug} template, and so on.

Alternatively, or in addition to it, we could use the "template" sidebar panel for this purpose.

**Comment by jordesign** [comment]
Closing this issue as the top header dropdown is no longer used.
