### ISSUE TITLE
Global Styles: Heading element UI controls

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#41974]
## What problem does this address?
Heading elements cannot be edited using the Global Styles UI.

## What is your proposed solution?
It would be good to add heading elements to the list of elements that can be customized in the Global Styles UI:

<img width="281" alt="Screenshot 2022-06-27 at 13 15 32" src="https://user-images.githubusercontent.com/275961/175938916-7fc673f3-2ad0-4641-b604-353544926438.png">

In addition, it would be good to have more granular control over heading (h1, h2, h3, h4, h5, h6) elements. Right now it's impossible to set rules for these elements via the UI, it can only be done via theme.json.

There is an older issue for when this was possible at a block level: https://github.com/WordPress/gutenberg/issues/31695

**Comment by mtias** [comment]
Headings should show up like this:

<img width="942" alt="image" src="https://user-images.githubusercontent.com/548849/175946219-0033064c-b820-4edc-a25f-6ce1d9bfc465.png">

Within the panel you should be able to select a more granular h1-h6.

**Comment by scruffian** [comment]
Thanks for the mockup @mtias

**Comment by scruffian** [comment]
This is dependent on https://github.com/WordPress/gutenberg/pull/41981

**Comment by carolinan** [comment]
Is there a design for the heading level selection?

**Comment by carolinan** [comment]
A toggle group works pretty well?
(What I don't like is the mix of different font weights and capitalized texts)

![Screen Shot 2022-07-06 at 08 23 34](https://user-images.githubusercontent.com/7422055/177482858-54278e12-fc06-4804-914a-c43f6bb4048a.png)
