### ISSUE TITLE
Buttons created with Gutenberg enabled creates block validation errors when Gutenberg is deactivated

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#41996]
### Description

Originally reported by @kafleg:
Buttons created with Gutenberg active, causes a block validation error in the editor because the miss match of CSS classes when Gutenberg is deactivated:

```
Content generated by `save` function:

<div class="wp-block-button"><a class="wp-block-button__link">fdsfsdf</a></div>

Content retrieved from post body:

<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">fdsfsdf</a></div>
```

### Step-by-step reproduction instructions

1. Activate Gutenberg 13.4 or newer, or Gutenberg trunk.
2. In the block editor, create a post or page and add some button blocks.
3. Deactivate Gutenberg.
4. View the post or page you just created and check if there are block validation errors for the buttons.

### Environment info

WordPress 6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Probably related to #40260. The Button block will need a deprecation.

cc @scruffian.

**Comment by talldan** [comment]
I don't think a block deprecation would be possible though, as it would need to be added to an already released version of WordPress core.

TBH, it's possible to get this issue with any block whenever content is created in a newer block editor and then loaded in an older one.

**Comment by t-hamano** [comment]
I believe this issue is also related to #41140.
For blocks with `__experimentalGetElementClassName`, disabling Gutenberg after saving the content will break the block.

This is the list of blocks to which `__experimentalGetElementClassName` is applied:

- `core/audio`
- `core/button`
- `core/embed`
- `core/file`
- `core/gallery`
- `core/image`
- `core/table`
- `core/video`

**Comment by draganescu** [comment]
It's like @talldan said unlikely to have a solution via a deprecation and also hard to solve: content created with newer editors can become invalid in older editors **for editing**. Gutenberg guarantees the content itself is independent of Gutenberg and via it's universal format and invisible markup does not depend on WordPress to be consumed. But editing blocks in older versions will be problematic.

I think a cool thing would be if we can detect that the user needs a newer editor and inform them.

**Comment by carolinan** [comment]
I am not sure that the benefits of this change to button _elements_ outweigh this issue.
