### ISSUE TITLE
Styles: audit utility classes generated on the frontend

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#41993]
For auditing and to kick off a discussion, here is a (probably incomplete) list of styles Gutenberg generates for frontend code:

| Classname  | Variations | Description  | Status |
| ------------- | ------------- | ------------- | ------------- |
| `is-${ orientation } `  |  vertical, horizontal | layout |  [current](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/layout.php) |
| `is-content-justification-${ justification } `  | center, left, right  | layout |  [current](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/layout.php) |
| `is-nowrap`  |  - | layout |  [current](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/layout.php) |
| `is-layout-${ layout }`  |  flex, ~flow~ constrained |  layout |  [current](https://github.com/WordPress/gutenberg/pull/40875) [updated](https://github.com/WordPress/gutenberg/pull/42763) |
| `has-background`  |  - | block supports |  [current](https://github.com/WordPress/gutenberg/blob/trunk/packages/style-engine/class-wp-style-engine.php) |
| `has-${ preset }-background-color`  |  Any color preset slug | block supports |  [current](https://github.com/WordPress/gutenberg/blob/trunk/packages/style-engine/class-wp-style-engine.php) |
| `has-${ preset }-gradient-background`  |  Any gradient preset slug | block supports |  [current](https://github.com/WordPress/gutenberg/blob/trunk/packages/style-engine/class-wp-style-engine.php) |
| `has-border-color`  |  - | block supports |  [current](https://github.com/WordPress/gutenberg/blob/trunk/packages/style-engine/class-wp-style-engine.php) |
| `has-${ preset }-border-color`  | Any color preset slug  | block supports |  [current](https://github.com/WordPress/gutenberg/blob/trunk/packages/style-engine/class-wp-style-engine.php)  |
| `has-${ preset }-font-size`  | Any font size preset slug  |  block supports |  [current](https://github.com/WordPress/gutenberg/blob/trunk/packages/style-engine/class-wp-style-engine.php) |
| `has-${ preset }-font-family`  |  Any font family preset slug | block supports |  [current](https://github.com/WordPress/gutenberg/blob/trunk/packages/style-engine/class-wp-style-engine.php) |
| `has-text-color`  |  -  | block supports |  [current](https://github.com/WordPress/gutenberg/blob/trunk/packages/style-engine/class-wp-style-engine.php) |
| `has-${ preset }-color`  |  Any color preset slug | block supports |  [current](https://github.com/WordPress/gutenberg/blob/trunk/packages/style-engine/class-wp-style-engine.php) |
| `has-text-align-${ alignment }`  |  center, left, right | text blocks |  current |
| `has-inline-color`  |  text blocks |  |   |
| `has-${ spacing }-spacing-size `  |  Any spacing preset slug | block supports | [current](https://github.com/WordPress/gutenberg/pull/41527)  |
| `has-icon`  |  - | icon |  current |
| `wp-elements-${ unique_id } ${ element_tag }`  |  Unique id + element tag name selector, e.g., .wp-elements-123 a |  block supports |  [current](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/elements.php) |
| `wp-container-${ unique_id }`  |  Unique id | layout |  [current](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/layout.php) |
| `wp-duotone-${ filter_id } img`  |  The id is a reference to the duotone filter id | block supports |  [current](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/duotone.php) |
| `wp-block-${ block_name }`  |  The block name without `core/` prefix | blocks | current  |
| `wp-site-blocks`  |  - |  template wrapper | current  |
| `wp-element-caption`  |  - | elements | current  |
| `wp-element-button`  |  - | elements | current  |

cc @apeatling @mtias

**Comment by ramonjd** [comment]
An issue that raises the possibility for `is-row` etc for manifestations of the Group block
- https://github.com/WordPress/gutenberg/issues/38126

**Comment by andrewserong** [comment]
One of the ideas in https://github.com/WordPress/gutenberg/issues/39336 from @cbirdsong is to use `.is-layout-row` and `.is-layout-stack` classes for the horizontal and vertical variations of the `flex` layout type. So if we went that route, someone could potentially target a Row group block variation via `.wp-block-group.is-layout-row`?

**Comment by carolinan** [comment]
This list is missing `has-link-color`, is there a reason?

**Comment by ramonjd** [comment]
Closing as stale.

The list needs refreshing. We can return when there's progress on classnames

**Comment by yratof** [comment]
Is there an out of the box standard for things like 'is-vertical'? just a utility css for all the flex layouts

**Comment by ramonjd** [comment]
I noticed there is a `is-vertical` classname added to stacked containers, e.g., 

```html
<div class="wp-block-group is-vertical is-layout-flex wp-container-core-group-is-layout-1 wp-block-group-is-layout-flex">
<p>Test</p>
</div>
```

But it doesn't have any corresponding CSS. 

Looks like the classname is there for backwards compatibility:

https://github.com/WordPress/gutenberg/blob/8dc36f6d30cc163671bdaa33f0656fdfe91f1447/lib/block-supports/layout.php#L746-L746

**Comment by cbirdsong** [comment]
I used this as a jumping off point for a discussion: 
- https://github.com/WordPress/gutenberg/discussions/61417
