### ISSUE TITLE
Keep track of the focused block in the state

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#420]
For different reasons like : 

 - Making the undo/redo work properly
 - Hiding elements when a block is not focused

We need to track the focused block in the state and provide an `isFocused` property to the blocks.

When we'll try to handle keyboard navigations, Enter/Backspace ... we'll probably need a way to update the focus config as well (block focused + position inside the block)

The multi-instance prototype do this by saving a `focusedUID`  and a `focusConfig` which is an object shaped and understood separately by each block.

**Comment by iseulde** [comment]
What's the difference between `isSelected` and `isFocussed`?

**Comment by youknowriad** [comment]
`isSelected` is cleared when we start typing inside the block

**Comment by iseulde** [comment]
The naming might be slightly confusing, because the block is still selected even if you start typing. Just the UI is hidden.

**Comment by aduth** [comment]
>The naming might be slightly confusing, because the block is still selected even if you start typing. Just the UI is hidden.

This is a good point to raise. Do you have any suggestions on how we might better distinguish the "is typing" state instead of conceptually separating "selected" and "focused"?
