### ISSUE TITLE
LinkControl UI goes off screen

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#42003]
### Description

Because the LinkControl popover appears horizontally centered relative to the link it modifies, in some cases (like editing the first item of a Navigation block), the interface appears out of the screen, making it very difficult to use.

In cases like this, the LinkControl popover should appear left-centered under the link (or right-aligned, in case the user is editing a link that is next to the right border of the screen)

### Step-by-step reproduction instructions

1. Add a blank navigation menu on top of a template
2. Add a link
3. Without having the List view open, click on the link

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4933/176160522-54c53653-e27f-40aa-a29a-82ba35d018f2.mov

### Environment info

- WordPress 6.0, Gutenberg 13.5.1
- Tested in Chrome, Firefox, and Safari for mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by javierarce** [comment]
Related:
- https://github.com/WordPress/gutenberg/issues/35073

**Comment by talldan** [comment]
The same thing seems to have been encountered in the widget editor - https://github.com/WordPress/gutenberg/issues/41739.

**Comment by carolinan** [comment]
Can also reproduce this with other blocks than the navigation block.
