### ISSUE TITLE
Buttons Block: Open in new tab option de-selects itself when adding link

### ISSUE THREAD

**Issue by Greatdane** [WordPress/gutenberg#42032]
### Description

When adding a link to a button in the Buttons block, confirming the link can de-select the "Open in new tab" option if it was already selected.

### Step-by-step reproduction instructions

1. Create a page or post and add a Buttons block to it. Add some text to the button.
2. Click on the "link" icon in the toolbar to choose what the button links to.
3. Paste or type in a link or page name, but don't click any of the options to confirm it/the suggested pages yet.
4. Toggle on the "Open in new tab" option.
5. Press the "return"/"curved arrow" button to confirm that you'd like to use the page/link you entered.

### Screenshots, screen recording, code snippet

The link is added to the button, but the "Open in new tab" option visibly turns itself off.

GIF:
![button-link-bug](https://user-images.githubusercontent.com/82622339/174418652-82ab3099-811a-46c7-9d02-a484840d9a45.gif)

### Environment info

Gutenberg: v13.5.1
WP: v6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hz-tyfoon** [comment]
I can also confirm this bug exist. 
This bug is not only the 'buttons' block but in the 'link-control' component. I found this bug also exist when 'linking any text' in the paragraph block.

pushed a fix it in this PR: #42073

**Comment by hz-tyfoon** [comment]
I think this issue should be closed as It's fixed by #42073
