### ISSUE TITLE
Can't create a block with @wordpress/create-block

### ISSUE THREAD

**Issue by drskullster** [WordPress/gutenberg#42047]
### Description

When running `npx @wordpress/create-block` with the latest version (3.5.0) I get this error : 

```
Creating a new WordPress plugin in the "yest" directory.

Creating a "block.json" file.

Creating a "package.json" file.
/Users/john/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/init-package-json.js:102
		if ( npmDevDependencies.length ) {
		                        ^

TypeError: Cannot read properties of undefined (reading 'length')
    at module.exports (/Users/john/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/init-package-json.js:102:27)
    at async module.exports (/Users/john/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/scaffold.js:110:2)
    at async Command.<anonymous> (/Users/john/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/index.js:143:6)
```

Running `npx @wordpress/create-block@3.4.0` works fine.

### Step-by-step reproduction instructions

1. Run `npx @wordpress/create-block test`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
I can confirm that the issue exists. Tested with:

```
$ node --version
v16.13.0
$ npm --version
8.3.1
```

**Comment by gziolo** [comment]
It looks like it's related to the changes applied in https://github.com/WordPress/gutenberg/pull/41810.

**Comment by tyxla** [comment]
Oops, that's on me. Fix incoming soon!

**Comment by tyxla** [comment]
Fix here: https://github.com/WordPress/gutenberg/pull/42049

**Comment by gziolo** [comment]
It should work correctly as of `v3.5.1` that has just got published to npm. I can confirm it works for me.

**Comment by tyxla** [comment]
Thanks @gziolo 🙌

**Comment by drskullster** [comment]
Working here, thanks for the fix !

**Comment by gziolo** [comment]
@drskullster, thank you so much for the report 🙇🏻
