### ISSUE TITLE
Reusable blocks don't allow editing of HTML

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4204]
If you click to edit HTML on a reusable block you get this:

![issue-edithtml-reusableblock](https://user-images.githubusercontent.com/253067/34442924-713d7228-ecbd-11e7-85f5-62f92ddb29a4.png)

I would suggest we just disable this functionality if it's unable to be used. Ideally we would be able to edit HTML on a reusable block. Maybe if we can only do that when in 'edit mode' of a reusable block, we disable when not in that state?

**Comment by mtias** [comment]
I thought we had already disabled this. It's just a flag on the block registration.
