### ISSUE TITLE
Global Styles: Elements: Link style rules are being applied to buttons

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#42055]
### Description

Link rules that are set via theme.json also bleed into button elements on the _front end_ of the site. To overcome this I think we might need to add `:not(.wp-element-button)` to the link element selector.

### Step-by-step reproduction instructions

1. Switch to emtpytheme
2. Add this to your theme.json file under `elements`
```
			"link": {
				"border": {
					"color": "grey",
					"radius": "1px",
					"width": "5px",
					"style": "solid"
				},
				"color": {
					"background": "lightblue",
					"text": "red"
				},
				"spacing": {
					"padding": "10px"
				},
				"typography": {
					"fontFamily": "sans-serif",
					"fontSize": "20px",
					"textDecoration": "none"
				},
				":hover": {
					"border": {
						"color": "black",
						"radius": "10px",
						"width": "5px",
						"style": "solid"
					},
					"color": {
						"background": "red",
						"text": "black"
					}
				}
			}
```
3. Add some buttons blocks
4. Switch to the front of your site.
5. Notice that some of the link and hover rules are applying to buttons as well as to links

### Screenshots, screen recording, code snippet

<img width="837" alt="Screenshot 2022-06-29 at 16 54 24" src="https://user-images.githubusercontent.com/275961/176486494-a35d482e-5c1b-480a-8f3f-f1a0e3c1d34f.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by draganescu** [comment]
Tested this, it is visible on the front end.

**Comment by draganescu** [comment]
Tested this, simply adding `:not(.wp-element-button)` to `ELEMENTS['link']` breaks the hover behavior and the generated style for `a:not(.wp-element-button):hover` is the same as for `a:not(.wp-element-button)`.

**Comment by getdave** [comment]
Ok this is an interesting bug. I will look into it now.

**Comment by getdave** [comment]
I have a suggested fix in https://github.com/WordPress/gutenberg/pull/42072. Not sure if the `:not()` selector route is sustainable in the long term however.
