### ISSUE TITLE
Global Styles: Elements: Captions text color not respected in front end.

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#42054]
### Description

When I try to set the caption text color, the CSS overwrites it, when a theme opts in to opinionated styles.

This happens when theme opt in to opinionated CSS, using the `wp-block-styles` theme support:
`add_theme_support( 'wp-block-styles' );`

To solve this we should move this CSS into the block.json file so that the user settings override it. However this is complex because the CSS comes from the theme.css file, not the standard block file. We might need to introduce a new key to block.json for opinionated block styles.

cc @adamziel @draganescu @getdave  

### Step-by-step reproduction instructions

1. Switch to empty theme
2. Add this to the theme.json under `elements`. Note that the text should be white:
```
			"caption": {
				"border": {
					"color": "grey",
					"radius": "10px",
					"width": "5px",
					"style": "solid"
				},
				"color": {
					"background": "limegreen",
					"text": "white"
				},
				"spacing": {
					"padding": "10px"
				},
				"typography": {
					"fontFamily": "sans-serif",
					"fontSize": "20px"
				}
			},
```
3. Add a table block with a caption.
4. Notice that in the front end the color of the text on captions is still grey

### Screenshots, screen recording, code snippet

<img width="893" alt="Screenshot 2022-06-29 at 16 46 11" src="https://user-images.githubusercontent.com/275961/176480168-af7c8fcc-8244-4f5e-9073-a7a1389e3c54.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by scruffian** [comment]
One suggestion is that this could be expected behaviour, since the theme is opting in to opinionated styles using the theme support (add_theme_support( 'wp-block-styles' );)

If we go this route then:
1. We should document it somewhere
2. We would gradually expect block themes to stop using the `wp-block-styles` theme support.

@WordPress/block-themers - does this approach make sense to you?

**Comment by carolinan** [comment]
I fully expect to stop using wp-block-styles. The main reason why I still use it is because of the .has-background padding, not the captions.

I'd happily get rid of it completely but I don't know how to solve it for older themes.

**Comment by pbking** [comment]
Not using `wp-block-styles` indeed makes the most sense; I don't see that being helpful for block themes moving forward.  To me that says "I'm going to be customizing CSS in this theme and I'm keen to start with some extra".  I'm sure there are other areas where the opinionated CSS clobber Global Styles and I would rather see the use of the support phased out rather than building exceptions for them.

I think those things that are more generally helpful and opinionated, though not currently configurable (like .has-background padding which is a great example) should instead be surfaced another way (as a configurable block attribute or added in the theme's CSS).

**Comment by scruffian** [comment]
See also the comment here: https://github.com/WordPress/gutenberg/pull/41140#issuecomment-1176574557

**Comment by scruffian** [comment]
I'm closing this on the understanding that we expect the opinionated block styles to override the styles set in theme.json.

**Comment by carolinan** [comment]
Is it really logicall that theme.json overrides all but one specific stylesheet?
Does it also override users global styles?

**Comment by justintadlock** [comment]
Just ran into this issue with Gallery > Image font sizes.  Even drilling down with both of these options, and they are still overruled for gallery images:

```json 
"core/gallery": {
	"elements": {
		"caption": {
			"typography": {
				"fontSize": "var( --wp--preset--font-size--sm )"
			}
		}
	}
},
"core/image": {
	"elements": {
		"caption": {
			"typography": {
				"fontSize": "var( --wp--preset--font-size--sm )"
			}
		}
	}
}
```

**Comment by scruffian** [comment]
Since the load order of global styles CSS was changed this is no longer an issue.
