### ISSUE TITLE
Unique templates can be applied to any post

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#42066]
### Description

It's currently possible to apply a template that was created for one specific post to any post. 

### Step-by-step reproduction instructions

* In the Site Editor navigate to the templates list and create a template for one specific post
* From wp-admin > posts list navigate to a different post to the one you created the template for in the preview step
* In the post inspector open the template dropdown and notice that you can apply the template you created in step 1 to the post you are currently editing

cc @ntsekouras 

### Screenshots, screen recording, code snippet

<img width="1701" alt="Screenshot 2022-06-30 at 10 54 22" src="https://user-images.githubusercontent.com/846565/176649742-ab514813-0d07-4153-8ff8-830a6a894759.png">

**Comment by ntsekouras** [comment]
@jameskoster is it possible the template you created was from Bernie's PR for fallback content on creation? Because on that PR the creation with the post_meta added was removed. Can you try with a template created in trunk?

**Comment by jameskoster** [comment]
Ah, possibly. I checked out trunk and deleted all templates. Then created a new template for "Hello World", but I am not seeing that template as an option in the template dropdown. Could that be related to the PR you mentioned as well? 🤔 

<img width="1400" alt="Screenshot 2022-06-30 at 19 18 16" src="https://user-images.githubusercontent.com/846565/176749743-267c71e4-ce6f-4889-8996-03d39320b55d.png">
<img width="1000" alt="Screenshot 2022-06-30 at 19 18 27" src="https://user-images.githubusercontent.com/846565/176749758-e6a5f85c-2a48-4872-98c9-ffaf6072308a.png">

**Comment by Mamaduka** [comment]
Unique templates take precedence before standard templates, correct? In that case, we might want to display a message that the post/page uses a specific template and hide the drop-down. Like we do for "Page for Posts."

**Comment by ntsekouras** [comment]
Hm... Where can I see that @Mamaduka? Do we have some similar handling elsewhere?

**Comment by Mamaduka** [comment]
@ntsekouras, this is how we handle the "Page for Posts" case.

https://github.com/WordPress/gutenberg/blob/f2888ed55f5aeae667d1cacc7c3ec22740f8952c/packages/edit-post/src/components/sidebar/post-template/form.js#L107-L125

P.S. It might be a good idea to double-check in template hierarchy logic for unique templates.

**Comment by ntsekouras** [comment]
Yeah, we could probably display something similar.. Would it make sense to also add the specific template in the list as an alternative? 🤔

**Comment by Mamaduka** [comment]
I just followed my own advice and double-checked things 😄

It looks like unique template `post-{postSlug}` is only served if a post has no template specified.

**Comment by jameskoster** [comment]
> It looks like unique template post-{postSlug} is only served if a post has no template specified.

It's served _automatically_? If that's the case we'll need to re-open and address https://github.com/WordPress/gutenberg/issues/41452 (albeit conditionally) :D 

https://github.com/WordPress/gutenberg/issues/42088 will also be affected.

**Comment by jameskoster** [comment]
Going to close this since the original issue seems to have been due to contamination from another PR. I would appreciate if one of y'all could check this as well though, just to make sure:

> Then created a new template for "Hello World", but I am not seeing that template as an option in the template dropdown

(https://github.com/WordPress/gutenberg/issues/42066#issuecomment-1171535774)

**Comment by Mamaduka** [comment]
> It's served automatically?

Here is how the current WP template resolution works for this case:

* The unique post template is served as "Default Template" when a post has no custom template set.
* WP will start using the custom template if the user sets it from the dropdown.

> Then created a new template for "Hello World", but I am not seeing that template as an option in the template dropdown

WP would refer to this unique template as "Default Template."

**Comment by jameskoster** [comment]
Ah, sorry I meant could y'all check that it's working as intended. On my local when I create a unique template (e.g. for "Hello World" post) I do not see it in the template dropdown as an option.
