### ISSUE TITLE
Add ability to add class and alignment to seperator

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4206]
In using this myself with a theme, I found that I really wanted to have a class and alignment ability on the separator block.

![issue-align-hr](https://user-images.githubusercontent.com/253067/34443764-452c6050-ecc1-11e7-9050-5b8be30173d8.png)

**Comment by youknowriad** [comment]
Is it really a good idea to have alignment here? I'm asking because some themes could consider the separator block as being "full width" always. In that case, having alignment doesn't make sense.

**Comment by karmatosed** [comment]
The thing is that separator had a lot of Gutenberg styling it outputs on front already. I think it's perfectly fair to say it should have a class and alignment.

**Comment by iseulde** [comment]
Do you mean aligning the block itself or aligning the line?

**Comment by monika-12** [comment]
I think separator should have styling options like color and width.

**Comment by karmatosed** [comment]
Closing as we probably want this to be more theme side, we are moving to more and more being up to the theme and this fits.
