### ISSUE TITLE
Add ability to add class to main title

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4207]
We can add a class to most other elements, but not the top title. It would be great to do this as then allows more control. Imagine a theme with styling that a user could then apply to any element. The title could for example have an animation or something happen on load with this. I found myself wanting to do this recently.

**Comment by youknowriad** [comment]
Well, this is not really possible as it's the responsibility of the theme to render the post title. This could be done in the customization focus though (page building).

**Comment by karmatosed** [comment]
I still think having the ability for as much to have classnames opens up possibilities to end users and themers.

**Comment by mtias** [comment]
We should only do this once post title is a real block. At the moment, we have no control over what sort of markup a theme chooses (h1, h2, etc) to render a title.

**Comment by karmatosed** [comment]
Closing for now as the title block needs to be in place first.
