### ISSUE TITLE
'open in new tab' option gets auto unchecked when editing the link of the 'linkeded text' in 'paragraph block'

### ISSUE THREAD

**Issue by hz-tyfoon** [WordPress/gutenberg#42080]
### Description

When using the paragraph block. If I make some text in the paragraph 'linkable' and make the link 'open in new tab' checked, then after I decide to change the link url and hit the 'submit button/curved arrow' then the link's 'open in new tab' option gets auto unchecked.

See the 'Step-by-step reproduction instructions' & the 'screen recording' for more details.

### Step-by-step reproduction instructions

1. Take the paragraph block with some texts.
2. Select some text from the paragraph & from the options over the selected texts click the 'link' button (located in between the 'italic' (_I_) and the 'more'/'arrow down' button) to make the selected text linkable.
3. give any url in the poped up input field and 'check' the 'open in new tab' option and save it by clicking the submit (the curved arrow on right side of the input field) button
4. now click somewhere else (or update the page then reload the page) and then the click the linked text again to edit the url
5. now change the url and press the submit button again.
6. Now U'll see that the link's 'open in new tab' option is also unchecked if U click the linked text again

See the video for better understanding

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/59374562/176734927-12145eaa-f83c-4347-ad2d-fe155eabf8f3.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hz-tyfoon** [comment]
### PR: [#42073](https://github.com/WordPress/gutenberg/pull/42073) fixs this issue

**Comment by talldan** [comment]
This was previously reported (https://github.com/WordPress/gutenberg/issues/40243), so I'll close this.
