### ISSUE TITLE
Blocks break when changing URL

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4208]
This is a super stress case, not at all usual.. but I think it's worth reporting. I was resetting up my dev environment today and changed .dev to be .test. As a result my Gutenberg test site blocks blew up. I had lost them all and got this:

![issue-changedomain-brokenblocks](https://user-images.githubusercontent.com/253067/34443147-243bf998-ecbf-11e7-8c48-a0d3febb6f98.png)

I only got the demo blocks back through rebuilding Gutenberg. Not exactly a solid end user solution :/

Whilst yes, not many are going to do what I did.. it got me thinking is this a pointer to breaking on importing? Is there something here we should fix as well someone can always change their URL.

**Comment by noisysocks** [comment]
I'm having trouble reproducing this. Could you please list the exact steps that caused this? Any errors that appear in your console would be really helpful, too.

Here's what I did:

1. Changed my _Site Address_ and _WordPress URL_ to `http://local.wordpress.dev/`
2. Ran `npm run build`
3. Navigated to _Gutenberg > Demo_
4. Changed my _Site Address_ and _WordPress URL_ to `http://local.wordpress.test/`
5. Navigated to _Gutenberg > Demo_

In both steps (3) and (5) the demo content rendered correctly.

**Comment by karmatosed** [comment]
Hmm interesting, I added an npm install to the mix, but apart from that those are exactly the same steps I did @noisysocks. If this is just something on my setup I would be super happy about that and we can close.

**Comment by jorgefilipecosta** [comment]
Hi @karmatosed, at the time this issue was created, tinymce cdn was down. It caused all blocks to fail in a situation very similar to the one described here. I think this may have been the root cause of the problem described here. The problem got solved by changing the cdn we use https://github.com/WordPress/gutenberg/pull/4201.

**Comment by karmatosed** [comment]
Ah ha! That explains it @jorgefilipecosta, closing this issue now, thanks!
