### ISSUE TITLE
Button element settings in theme.json breaks the Fill/Outline button functionality

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#42097]
### Description

If you set border settings for the button element, the Fill/Outline functionality works not consistently.

### Step-by-step reproduction instructions

1.  Activate `emptytheme` to discard theme interferences
2. Add this  snippet to `theme.json`

```
{
	"styles": {
		"elements": {
			"button": {
				"border": {
					"color": "red",
					"style": "solid",
					"width": "10px"
				},
				"color": {
					"background": "orange",
					"text": "blue"
				}
			}
		}
	}	
}


```
3. Add a button element
4. Try to set outline style and change the button colors as in the video

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1310626/176916956-11f2fdf0-7baa-4f40-837d-710fec12be72.mp4

### Environment info

- Wordpress 6.0
- Gutenberg 13.5.1WordPress

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MaggieCabrera** [comment]
After looking into this, I think part of the solution requires that we express [block styles variations differently](https://github.com/WordPress/gutenberg/issues/42297).

**Comment by bradhogan** [comment]
Not sure if this is related or not but the latest version of WP and/or Gutenberg prevents the outline button from displaying the border only in Gutenberg.  The front-end works ok.  Here's a quick video demoing the issue. Notice there is no border when viewing the button in Gutenberg.  This demo uses only default Twenty Twenty Two and Gutenberg. 

https://soapbox.wistia.com/videos/058cz5NVAZ

**Comment by eric-michel** [comment]
A related problem: defining `blocks.core/button.spading.padding` breaks the equalizing padding provided to regular buttons to keep them the same size as outlined buttons.

With no customization:
![image](https://user-images.githubusercontent.com/45110062/183502976-f8beaad7-b29e-44ed-b2f7-1f42672d63e6.png)
Padding for the outlined buttons is: `.667em 1.333em;`
Padding for the regular buttons is: `calc(0.667em + 2px) calc(1.333em + 2px);`, which adds `2px` of padding on all sizes to equalize the `2px` border on the the outlined button

With the spacing customization in `theme.json` of:
```
"spacing": {
	"padding": {
		"top": "0.5rem;",
		"right": "1rem",
		"bottom": "0.5rem",
		"left": "1rem"
	}
}
```
![image](https://user-images.githubusercontent.com/45110062/183503807-ca575f68-64a9-4152-9981-aa86c2d9a235.png)

The new padding of:
```
padding-top: 0.5rem;
padding-right: 1rem;
padding-bottom: 0.5rem;
padding-left: 1rem;
```
overrides both the outline and regular button padding options, resulting in uneven button heights.
