### ISSUE TITLE
Link overlay confusion

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4209]
This is a more general issue as I would love us to explore a better adding a link experience. To be blunt, I had a lot of issues adding a link and overlaying was rife, for example:

![issue-link-overlay](https://user-images.githubusercontent.com/253067/34443566-f25d36fc-ecbf-11e7-9cce-6b17ebc1c93f.png)

The issues were more it felt clumsy and just not the best. I don't come offering a better solution right now, however I think we need to bring our focus to this after we have iterated on the other experience hitches. Right now, it's not as good as it could be.. so let's make it better.

I think a good start is to begin looking at other implementations, what do other products do and how can we learn? Also, does anyone have any ideas in the form of sketches for now - keep the low-fi and let's think about this issue before diving in.

**Comment by karmatosed** [comment]
Noting another issue we have right now with the link overlay is #3637, I am merging that issue into this. The link overlay right now can appear to be hidden. We have a few issues we need to resolve and a bit of a crossroads.

**Issues:**
- The adding behaviour isn't consistent and can be clumsy to experience.
- Chrome can hide the link overlay. An issue of z-index but one that keeps cropping up.
- Plugins and other cursor additions clash with the link. A lesser point but important one for accessibility.

The crossroads is our approach to linking. Should it be contextual or should it be consistently in one place. I don't think we can have it always top or bottom, that feels like you'd miss the interface. But is there another option?

Again, we should explore by looking at what other options do.

**Comment by afercia** [comment]
There are several open issues about the link "overlay", see for example:

- Cmd/Ctrl+K shortcut (and maybe also one to unlink) mentioned in: Keyboard shortcuts support #71
- Insert link warning (button block) and usability - consistency #1670
- Insert link: validation and feedback #1838
- Insert / edit link inconsistencies across blocks #2216
- The link modal "moves" together with the caret #3349
- Improve keyboard navigation for the "link modal" popups #3350

**Comment by karmatosed** [comment]
Google does this:

![2018-01-10 at 11 48](https://user-images.githubusercontent.com/253067/34771359-36ce7e32-f5fc-11e7-8338-bb23206cf5ba.png)

![2018-01-10 at 11 48](https://user-images.githubusercontent.com/253067/34771378-4f068134-f5fc-11e7-909b-1cd381273a56.png)

**Comment by karmatosed** [comment]
I am closing this to make one issue that looks for design feedback on several link changes.
