### ISSUE TITLE
Alternative to dangerouslySetInnerHTML in block `save`

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#421]
Related: https://github.com/WordPress/gutenberg/pull/419#discussion_r111410525

By default, React escapes string children, converting HTML tags to their encoded equivalents. On the web, this is considered a "good thing" in helping avoid unintentional cross-site scripting attacks. However, in the serialization step of converting a block to its string form, this complicates the block's `save` function where we need to be able to include raw HTML in the generated output to be saved for `post_content`. The block's save function is never truly rendered, only ever passed through [`ReactDOMServer.renderToStaticMarkup`](https://facebook.github.io/react/docs/react-dom-server.html#rendertostaticmarkup) to generate the composed content of the post. In order to include HTML in the serialized content, a developer must use the special [`dangerouslySetInnerHTML` prop](https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml).

__What's the problem?__ It's not obvious that a developer would need to use `dangerouslySetInnerHTML` to include arbitrary markup in the saved post content. Additionally the property name is very intentional in its scariness, which is likely off-putting for our legitimate use-case.

__Why do we need it?__ We may consider exploring alternatives, but for the moment particularly the `Editable` (TinyMCE) component is affected by this in its value being reflected as raw HTML.

**Comment by aduth** [comment]
A few ideas:

- Could we disable default string escaping in our `ReactDOMServer.renderToString` abstraction?
- Could we traverse the tree of virtual DOM nodes to automatically convert string children to a `dangerouslySetInnerHTML` prop?
- Do we find another solution than to accommodate the Editable component's value as raw HTML? Perhaps some compatible tree structure?

**Comment by youknowriad** [comment]
> Could we traverse the tree of virtual DOM nodes to automatically convert string children to a dangerouslySetInnerHTML prop?

This could confuse block authors. If they're familiar with React, maybe they explicitly expect their content to be escaped and it won't be the case.$

> Do we find another solution than to accommodate the Editable component's value as raw HTML? Perhaps some compatible tree structure?

Seems like a good idea to explore, though, it won't be possible to reuse elements from the `edit` method.
