### ISSUE TITLE
Search block button always displays default cursor (arrow)

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#42100]
### Description

The search block button always displays the default cursor (arrow). It should use the same cursor as for other buttons or text inputs.

### Step-by-step reproduction instructions

1. Add a search block
2. Check the cursor in the editor and the rendered version

## Before:
Editor text:
![image](https://user-images.githubusercontent.com/1310626/176934634-cbf23715-221e-4106-97a0-c3b3dbb85102.png)

Editor icon:
![image](https://user-images.githubusercontent.com/1310626/176934706-05c19340-d641-4321-9c04-2c85331b5bd4.png)

Public:
![image](https://user-images.githubusercontent.com/1310626/176934755-c93205d1-c49e-4da8-8b46-a3ac6d6da044.png)

### Environment info

- WordPress 6.0
- Gutenberg 13.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mcliwanow** [comment]
Looks like it was addressed here: https://github.com/WordPress/gutenberg/commit/301dec6c4bedf3d775d2ce37411e6361dd862c52#diff-6821ffba0c3021ef82a479542bb166a00ed2ae278c40667dd2cc71eca4b1703cR4

When using Gutenberg 13.6.0 the cursor is there: 
<img width="719" alt="Screenshot 2022-07-07 at 20 25 48" src="https://user-images.githubusercontent.com/4765119/177843440-641a088d-dd03-475e-83db-178a2e4f7f52.png">

Checked on a website running nothing else than Gutenberg.

**Comment by BE-Webdesign** [comment]
I think this can be closed out as it is fixed in trunk branch.

**Comment by paulopmt1** [comment]
Tested here, and it worked as well:

![image](https://user-images.githubusercontent.com/1044309/182210807-fd16cb7c-0f30-49d6-89d3-acd9c9e79c1b.png)

Same for custom buttons with text:

![image](https://user-images.githubusercontent.com/1044309/182211234-08faeb7b-d58a-4740-aea9-75d057129cd7.png)

**Comment by paaljoachim** [comment]
Closing issue. As this issue is not valid any longer.
It can of course be reopened if need be.
