### ISSUE TITLE
Lists don't wrap on second line

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4210]
Right now we have this:

![issue-listwraps](https://user-images.githubusercontent.com/253067/34443777-5a725c58-ecc1-11e7-83da-68fbeec61912.png)

We can potentially fix with:

`list-style-position: outside;`

Maybe some margin/padding may also be needed.

**Comment by afercia** [comment]
Worth reminding Twenty Seventeen, Twenty Sixteen, and Twenty Fifteen, they're all designed to use [hanging punctuation](https://www.markboulton.co.uk/journal/five-simple-steps-to-better-typography-part-2) for list bullets. See https://core.trac.wordpress.org/ticket/30374

<img width="648" alt="screen shot 2018-01-02 at 14 37 03" src="https://user-images.githubusercontent.com/1682452/34485520-690f07c2-efcb-11e7-99a0-6ca98bdcb341.png">

Wondering if the List block should offer this as a formatting option.
