### ISSUE TITLE
Ability to set reusable attributes

### ISSUE THREAD

**Issue by M4N0JKUM4R** [WordPress/gutenberg#42110]
## What problem does this address?

Currently, I do not see any way to set reusable attribute for all blocks not limited to current page or post but to a particular namespace.

This may be useful in a scenario like this: 

https://wordpress.stackexchange.com/questions/407324/setting-global-block-attribute-value

## What is your proposed solution?

Ability to set something like reusable attribute in supports object. Pseudocode:

```
registerBlockType("namespace", {
  attributes: {
      attribute1: value,
  },
  supports: {
      reusableAttributes: attribute1
  },
```

It would be good to know if this feature already exists and that I missed it.

**Comment by talldan** [comment]
@M4N0JKUM4R I'm not sure I completely understand the idea of a reusable attribute. Could you explain how that would work some more?

Reading through the stackexchange post, that sounds like a situation where a block attribute shouldn't be used. For static blocks, the attribute value would be serialized in a post, and then there's a risk that an outdated API key is stored.

Instead I think if the value is something that's global, it should be stored somewhere in the WordPress database, maybe as an option or as user meta. There's a good tutorial here about using the JavaScript data APIs - https://developer.wordpress.org/block-editor/how-to-guides/data-basics/.

**Comment by M4N0JKUM4R** [comment]
@talldan Yes, I understand that. I even wanted to create an options page where the API key is submitted on click but I did not want an extra page just for a single input field whereas the Inspector controls are more than enough for the purpose.

![image](https://user-images.githubusercontent.com/11471878/177269694-428b2fdb-a1f0-4b6d-81b4-da0eaa459dee.png)


I did get a solution for this: https://wholesomecode.ltd/using-options-to-store-data-in-the-wordpress-block-editor-gutenberg I implemented it in my functional component and was working but what I see is that this hassle can be converted to a single line of code if possible.

**Comment by talldan** [comment]
I don't think you need to make a separate page for the setting. You can still update the value through the block interface. Those values in the sidebar don't have to be block attributes. 

This isn't something that's new. For a while there have been blocks that update post meta. There are also now Full Site editing blocks that might interact with data that isn't a block attribute - for example editing the site title block updates the actual site title rather than an attribute:
https://github.com/WordPress/gutenberg/blob/1c4dfcca89ba16952322badea7842cc05c66493c/packages/block-library/src/site-title/edit/index.js#L34

----

> I did get a solution for this: https://wholesomecode.ltd/using-options-to-store-data-in-the-wordpress-block-editor-gutenberg I implemented it in my functional component and was working but what I see is that this hassle can be converted to a single line of code if possible.

I did read that link, but I was confused when it mentioned `@wordpress/api`, I don't know what that is. It doesn't seem to be a package published by WordPress.

**Comment by M4N0JKUM4R** [comment]
That's surprising. When I check it, it looks official like the other ones `@wordpress/element`, `@wordpress/components`. Is it not?

![image](https://user-images.githubusercontent.com/11471878/177278448-1a429d3f-1526-4e20-b12b-99bf4f40459b.png)

**Comment by talldan** [comment]
I'm not sure what it is, I don't see that on my WordPress install, but maybe it needs to be enqueued, or a plugin you use is enqueuing it for you:
![Screen Shot 2022-07-05 at 4 08 37 pm](https://user-images.githubusercontent.com/677833/177281386-e6468e64-9ec9-49ba-995e-ad49788392e3.png)

It was mostly this part from the article confused me:
```
import api from '@wordpress/api';
```

There isn't a `@wordpress/api` on npm - https://www.npmjs.com/search?q=%40wordpress%2Fapi. 🤔

**Comment by M4N0JKUM4R** [comment]
```
import api from "@wordpress/api";
 
api.loadPromise.then(() => {
    let settings = new api.models.Settings();
    settings.fetch().then((response) => {
        console.log(response);
      });
  });
```

As per the article, there is more to include to get the data.

**Comment by talldan** [comment]
It must be a WordPress core thing. I haven't seen it before.

There are newer ways that have been developed that might work better with React, they're mentioned in that data tutorial I linked to above.

But definitely use what you're most comfortable with 👍

**Comment by ocean90** [comment]
`wp-api` is the [Backbone JavaScript Client](https://developer.wordpress.org/rest-api/using-the-rest-api/backbone-javascript-client/) for the REST API.
And the import line probably just works due to some Webpack config handling the mapping to the `wp` global.

**Comment by aurooba** [comment]
Hi @M4N0JKUM4R, are you still looking for more information on this issue?

**Comment by M4N0JKUM4R** [comment]
> Member

Since it's a year old, I am not that desperate now as I am working on other things :D But if you got any information, feel free to share, please.

**Comment by M4N0JKUM4R** [comment]
> Hi @M4N0JKUM4R, are you still looking for more information on this issue?

Since it's a year old, I am not that desperate now as I am working on other things :D But if you got any information, feel free to share, please. @aurooba

**Comment by aurooba** [comment]
@M4N0JKUM4R To expand on what @talldan mentioned, you can absolutely set "global" settings from the block editor interface, using `useEntityProp`. If you registered a global setting using [`register_setting()`](https://developer.wordpress.org/reference/functions/register_setting/), then you could set and access it with `useEntityProp`.  Take a peek [at the code for the `useEntityProp` function](https://github.com/WordPress/gutenberg/blob/1c4dfcca89ba16952322badea7842cc05c66493c/packages/core-data/src/entity-provider.js#L102) to get a solid idea on how you can use it.

I hope that helps! If this is no longer something you need or if that answers your question, please feel free to close the issue. :)
