### ISSUE TITLE
Should we ignore package-lock.json file in repo?

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4212]
Pretty much every time I run/build I get this json file change that 'wants to be committed'. Can we just add a .gitignore?

**Comment by aaronjorbin** [comment]
`package.json` is needed in order ensure everyone has the correct dependencies.

**Comment by Soean** [comment]
Maybe you mean `package-lock.json`?
related: #2512

**Comment by youknowriad** [comment]
Both these files shouldn't be ignored. It's annoying that `npm` updates the `package-lock.json` constantly but it's normal behavior that npm updates dependencies of dependencies. the `package-lock.json` is not a full lock.

Also, I noticed it can change if we do not use the same npm version consistently.
I'm afraid we can't do anything about it. Maybe we could just decide to git ignore it but we'll lose locking in this case. (performance and ensure similar first level dependencies' versions)

**Comment by karmatosed** [comment]
Yes sorry it is package-lock.json and changed title to reflect this, thanks.

**Comment by karmatosed** [comment]
Closing as seems we can't do anything about this it seems.
