### ISSUE TITLE
tell me about the block anchor support?

### ISSUE THREAD

**Issue by sharazghouri** [WordPress/gutenberg#4214]
## Issue Overview
i don't know how anchor work.

## Steps to Reproduce (for bugs)

1.
2.d
3.
4.

## Current Behavior

d

## Screenshots / Video
![image](https://user-images.githubusercontent.com/17900945/34453276-af9c4d96-ed71-11e7-8b7d-de34d74088d3.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by Soean** [comment]
You can activate the anchor function in the `supports` parameter.

> Anchors let you link directly to a specific block on a page. This property adds a field to define an id for the block and a button to copy the direct link.

https://wordpress.org/gutenberg/handbook/block-api/#supports-optional

**Comment by sharazghouri** [comment]
Hello @Soean 

Thanks for responding.

after giving id to block not show any button for copy link.
![image](https://user-images.githubusercontent.com/17900945/34453459-d14942ea-ed77-11e7-9291-3f65f61beb51.png)
at the end i see id on my block.
![image](https://user-images.githubusercontent.com/17900945/34453467-ee93a0d4-ed77-11e7-9350-0410d78f692b.png)

**Comment by mtias** [comment]
@sharazghouri it means you can link to your post and add `#sharazghouri` at the end of it to scroll to the block.
