### ISSUE TITLE
"Convert into Blocks" breaks image with captions

### ISSUE THREAD

**Issue by jordymeow** [WordPress/gutenberg#4215]
Hi,

WordPress core editor allows inserting images with captions into posts. It's pretty standard to WordPress since the beginning but it seems that Gutenberg fails to convert this into a proper block. Instead, it creates 3 blocks for it, the beginning of the caption shortcode, the image block (which is fine) and another block for the end of the caption shortcode. I think that could and should be handled nicely by Gutenberg. Cheers :)

**Comment by mtias** [comment]
Assigning the copy / paste label as we should be handling it correctly for both cases.

**Comment by iseulde** [comment]
@jordymeow I'm failing to reproduce this. Could you provide some more information about this issue? I assume the content is in a "classic" block? Could you provide the contents of this block (three dots on the right side, then "edit HTML")? 

I created a post in the old editor, copied the contents, pasted into Gutenberg, and everything is fine. I also created a "classic" block with the following, then converted into blocks, and everything is fine as well.

```HTML
Welcome to WordPress. This is your first post. Edit or delete it, then start writing!

[caption id="attachment_#" align="alignnone" width="#"]<img class="size-medium wp-image-#" src="http://example.com/test.png" alt="" width="#" height="#" /> Test[/caption]

Test

**Comment by jorgefilipecosta** [comment]
Based on the inputs provided in issue https://github.com/WordPress/gutenberg/issues/4219, I was able to reproduce this problem with the following code:
```
<div>
[caption id="attachment_915" align="aligncenter" width="400"]<a href="/another-page/"><img src="https://dummyimage.com/400x400/333333/09f09f.jpg&amp;text=image+1" alt="“My alt” alt 1" width="400" height="400" /></a> “My caption” caption 1[/caption]
</div>
<div>
[caption id="attachment_936" align="aligncenter" width="400"]<a href="/another-page/"><img src="https://dummyimage.com/400x400/000000/ffffff.jpg&amp;text=image+2" alt="“My alt” alt 2" width="400" height="400" /></a> “My caption” caption 2[/caption]
</div> 
```
A problem happens when copy pasting and converting from classic to blocks.
