### ISSUE TITLE
Consider removing adding option in toolbar

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4216]
If you have the block actions beside them you get 3 ways to insert blocks in a page. This feels somewhat too many. I suggest we remove the '+' on the top toolbar.

![insert-toolbar](https://user-images.githubusercontent.com/253067/34461569-5c679bda-ee25-11e7-83bf-d2a11ac3438f.png)

If someone has the block actions docked to the toolbar then maybe we can have this brought back, I think though having it by the content is better.

On mobile, let's leave the actions just in toolbar - this change shouldn't be made for that.

**Comment by ElectricFeet** [comment]
Agreed! 

I just posed #4219 which suggests more logical way to manage all the screen areas &mdash; and in particular, it removes this icon from this toolbar.

**Comment by karmatosed** [comment]
In testing this doesn't seem to be an issue, we aren't getting much feedback to remove anymore ways to add blocks, in-fact people want more options if anything - we just brought back sibling adding. In light of that closing this for now, we can always revisit.
