### ISSUE TITLE
Paragraphs in Classic block lose classes during conversion

### ISSUE THREAD

**Issue by galbaras** [WordPress/gutenberg#42172]
### Description

The following code in a Classic block

```
<p class="teaser">Get value for money now. Click the button and contact us for a high-quality, used copier that works like new, but costs a lot less.</p>
```

Is converted into this code

```
<!-- wp:paragraph -->
<p>Get value for money now. Click the button and contact us for a high-quality, used copier that works like new, but costs a lot less.</p>
<!-- /wp:paragraph -->
```

Since there's some styling based on the `teaser` class, this conversion makes the page lose that styling.

The expected behaviour, of course, is to retain the class, either in the tag or in the block definition, and rendering it correctly at the front-end.

Seems related to #5028 (closed) and #11211 (open). Maybe paragraph conversion should be revisited holistically.

### Step-by-step reproduction instructions

1. Create a Classic block with the above example
2. Convert it to blocks
3. Check the code

### Environment info

- WordPress 6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by galbaras** [comment]
It's not an enhancement if the plugin is doing the wrong thing. Removing details isn't part of properly converting anything. The idea is to have the exact same thing rendered on the front end, and that's not happening, so this is a bug.

Personally, I can't trust this conversion with my large sites, so I'm still using the classic editor, and that's probably not what you want either.

**Comment by galbaras** [comment]
Further testing shows that classes are removed from other elements, too. I really don't get how this can be ignored. The block editor keeps getting new features, but basic issues like converting elements correctly don't get resolved?

In fact, it should be a priority to ensure that converted pages aren't messed up in general, so that users can change them afterwards _if they want to_, but they stay exactly the same otherwise.

**Comment by ndiego** [comment]
This issue came up in today's Editor Bug Scrub. We can confirm this issue exists in the latest version of Gutenberg. It appears that there have been many other issues in the past on the same issue. @galbaras, as you indicate, this issue definitely impeeds the adoption of a block-based approach to WordPress. 

@youknowriad do you have any insight into this? Based on the comments, it appears that the issue was perhaps fixed in #5028?

**Comment by galbaras** [comment]
@youknowriad wrote on Feb 15, 2018 (4 years, 11 months and 8 days ago):
> Converting to blocks can be a bit destructive because it's very hard to ensure all kind of markup is transformed properly, that's one of the reasons it's an explicit action instead of an automatic migration. so I'm considering this as an enhancement.

What's so difficult in matching `(class|id)="([^"]+)"`, and then setting the block's `$1` to `$2`?

**Comment by youknowriad** [comment]
Doesn't seem difficult, but there are thousands of issues like that. Would you like to give it a try?

**Comment by galbaras** [comment]
Sorry, it's not something I can do.

If by "issues", you mean "open GitHub issues", I can see why you'd need help with this, but maybe what's needed is a different approach to quality control, which clears quality issues before adding features?

**Comment by galbaras** [comment]
This happens with other tags besides paragraphs, e.g. headings, so the scope is wider than "[Block] Paragraph".

@ndiego Any progress since Jan 25?

**Comment by galbaras** [comment]
We are nearing this issue's first birthday, despite it being relatively simple to fix and likely in the way of more site owners adopting the block editor (like ... me).

**Comment by galbaras** [comment]
It's amazing how this project keeps plugging along with new features, leaving bugs behind. This compatibility issue was opened over 2 years ago, yet even its scope hasn't been labeled properly, not to mention fixed.

> Doesn't seem difficult, but there are thousands of issues like that

This only makes it worse. There shouldn't be ANY open quality issues that are easy to resolve. They should be resolved before adding features, if only to prevent retrofitting work afterwards.

**Comment by galbaras** [comment]
@jordesign Thank you for trying to help. Alas, no changes yet on most of the issues you collected.

So it's nice to have a shiny new font manager, but if it works as well as converting classic to blocks (and the other things mentioned in #54266), it may explain the poor reception of the block/site editor among professionals.

**Comment by youknowriad** [comment]
cc @ellatrix just in case this is something that we can quickly fix.

**Comment by ellatrix** [comment]
Sure, this is easy: #60331

**Comment by galbaras** [comment]
Thank you for adding `class` handling, @ellatrix. It would be good to add handling for `id`, even if only for the sake of completion, but possibly for actual value. It would also be good to confirm that classes and IDs aren't stripped from (inline) elements **within** block-level ones, e.g. `span` or `a` tags within paragraphs, list items, blockquotes, etc.

**Comment by galbaras** [comment]
Any idea when this will make its way into WordPress core?

**Comment by ellatrix** [comment]
Could you create a new issue?

**Comment by galbaras** [comment]
For this one question? Nah, I'll just wait and read changelogs.

**Comment by ellatrix** [comment]
No, you asked for ID handling
