### ISSUE TITLE
Elements heading styles are not applied in the Site Editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#42177]
### Description

When applying styles to elements.heading (as opposed to elements.h1 etc), the styles are applied on the front and in the block editor, but not in the Site Editor.

### Step-by-step reproduction instructions

1. Activate Gutenberg trunk
2. Activate a full site editing theme, for example emptytheme.
3. In theme.json, add:
```
"styles": {
	"elements": {
		"heading": {
			"color": {
				"text":"white",
				"background": "blue"
			}
		}
	}
}
```
4. In theme.json, also delete any other styling to heading blocks.
5. Go to the site editor and add a few heading blocks of different level. Do not change any color options.
6. Confirm that the blocks do **not** have the colors you added in theme.json.
7. Save and view the front of the website. Confirm that the colors are used. Optionally view source to see that the style is added:
```
h1, h2, h3, h4, h5, h6 {
    background-color: blue;
    color: white;
}
```
8. Optionally, add a few heading blocks in the block editor and confirm that the colors are visible.

### Environment info

WordPress 6.0
Gutenberg current trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I have confirmed that the same problem occurs in the caption element as well as the button block.
I believe #42479 will solve the problem 👍

**Comment by bgardner** [comment]
@t-hamano Circling back to confirm that https://github.com/WordPress/gutenberg/pull/42479 solves the issue with captions.
