### ISSUE TITLE
Comunicate Gutenberg Version Requirements

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#42199]
## What problem does this address?

Some of the newer themes leverage features of Gutenberg that are not yet available in WordPress core.  This isn't communicated in the WordPress.org directory and the theme might seem broken.

## What is your proposed solution?

Those themes should be identified and that dependency communicated, likely in the readme.txt file.  While it's expected that every thing should WORK without the plugin it's reasonable that not every feature implemented will work as expected without the plugin activated.

A good example of this is the "elements" api changes that allow us to define styles for state selectors.  This is a particular boon for buttons and links and allows a lot less CSS to be used.  However the result is that unless Gutenberg is activated those styles won't be used.  

This situation should be communicated to anyone using the theme in the WordPress.org space.

Previously we tinkered with the idea of programmatically testing for the plugin, or testing for features and communicating that once the theme is activated (in wp-admin).  This was both heavy handed and didn't well communicate the situation.

Suggestion for inclusion in the theme `readme.txt` file:

```
This theme was developed using the Gutenberg plugin v13.0.0, some elements may not work or appear as expected without that version or higher installed
```

This could be removed once the latest version of WordPress contains the features.

**Comment by carolinan** [comment]
I understand the problem, but I am not sure if it is relevant as an issue in the Gutenberg GitHub directory? Did you mean to post this at Automattic themes repo?

There is an open Trac issue for displaying plugin information in the WordPress.org theme directory.
[#3863](https://meta.trac.wordpress.org/ticket/3863)

**Comment by pbking** [comment]
Doh!
This was supposed to go into the Automatic/Themes project.
My apologies!  I went too fast.

Thank you @carolinan for pointing that out and for pointing me to that trac ticket as well!
