### ISSUE TITLE
Consider more approachable copy for "Transform to" 

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#42202]
## What problem does this address?
"Transform" is a more technical/less approachable term. I know technically they're called block transforms, but perhaps we should make the copy more approachable, say something like "Turn into". 

It's a very small adaptation, but "Turn a paragraph into a heading" is much friendlier/approachable that "Transform a paragraph...". 

## What is your proposed solution?
Change "Transform to" to "Turn into":

<img width="1064" alt="CleanShot 2022-07-06 at 16 35 42@2x" src="https://user-images.githubusercontent.com/1813435/177638449-8b3eaf96-a81a-4590-a421-fb53f33f88be.png">

**Comment by apeatling** [comment]
Closing this based on https://github.com/WordPress/gutenberg/pull/54432. Feel free to re-open if there's a different direction. 👍
