### ISSUE TITLE
Reusable blocks don't keep named styles

### ISSUE THREAD

**Issue by amandablum** [WordPress/gutenberg#4220]
## Issue Overview

Reusable blocks do not save the style attached to them. Saving a block results in having to edit it to reinsert the style. When you insert the reusable block, it inserts without the style. This seems to be to be counterproductive to the point of a reusable block. 

## Steps to Reproduce (for bugs)

1. Create a reusable block. Add a style class. 
2. Save usable block. 
3. Edit reusable block to add block name and add style class, again. 
4. Save block. 
5. Insert reusable block via inserter.

## Expected Behavior

Expected upon saving of block to "reusable" it would retain style class. Expected upon insertion of reusable block with style, new block would have saved style class. 
## Current Behavior

Reusable blocks do not save style classes upon creation, and ignore saved style classes on insertion. 
## Possible Solution

Save style classes when creating blocks.  Make style classes part of the reusable block on insertion. Keep location of style class field consistent throughout the process. 
## Screenshots / Video

created a new block. added a style class
![step1](https://user-images.githubusercontent.com/2366499/34470324-df580aa2-eee3-11e7-9572-bd4f819aeb2a.png)
saved block as reusable. style class is now gone. 
![step2](https://user-images.githubusercontent.com/2366499/34470323-df4635ac-eee3-11e7-8a68-5ef5030b89a6.png)
edited reusable block to add block name and put style back in. saved. 
![step3](https://user-images.githubusercontent.com/2366499/34470322-df330dce-eee3-11e7-8f90-a169f6c14907.png)
style class is now saved on the reusable block. 
![step4](https://user-images.githubusercontent.com/2366499/34470321-df1e46aa-eee3-11e7-9485-92046004303b.png)
insert reusable block via inserter... style class is not attached. 
![step5](https://user-images.githubusercontent.com/2366499/34470320-df0a4740-eee3-11e7-8562-2df350a5f34b.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
+1 I can recreate this and see this myself as an issue.

**Comment by noisysocks** [comment]
This seems to work OK for me—or perhaps I'm misinterpreting something?

![reusable](https://user-images.githubusercontent.com/612155/34806534-a3151480-f6d7-11e7-8437-2b92cf65c32e.gif)

**Comment by youknowriad** [comment]
This was probably fixed by #4165
