### ISSUE TITLE
Group block "outline" does not show the correct width when the layout setting is toggled

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#42216]
### Description

In the block editor, if I add a group block and toggle "Inner blocks use full width" off, I can not see the width of the block.

When I select wide or full width alignment, the toolbar moves, but there is no visible line that shows how large the block actually is.
Because focus moves from the block to the toggle and then to the width option, the blue border is not present.
Only the placeholder for content inside the group shows, indicating the width of the inner content but not the group itself.

Please see the screenshots below.

### Step-by-step reproduction instructions

- Create a new post or page and add a group block.
- Toggle the layout option.
- Change the width of the group.

### Screenshots, screen recording, code snippet

Wide:
![group with wide align, toolbar is not positioned over the block placeholder](https://user-images.githubusercontent.com/7422055/177723836-a9686e97-1d52-4076-8819-1707a0572762.png)

Full:
![group with full align, toolbar is positioned far from the block placeholder](https://user-images.githubusercontent.com/7422055/177723875-098f23ed-44cd-47ba-bbee-bdf80c4ea72e.png)

The actual block width is only visible if a background is added:
![group with background shows the size of the block](https://user-images.githubusercontent.com/7422055/177724067-eb0621c4-e195-4095-9a18-876299bcb415.png)

### Environment info

WordPress 6.0
Current Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mt8** [comment]
Our team has tested this issue.

environment
WordPress: 6.4.2
GB: trunk

Add group block

However, unlike 6.0, the layout selection is displayed here.
![1](https://github.com/WordPress/gutenberg/assets/2771396/b7077cd0-133a-4cb3-b346-16be2d9c63f4)

Therefore, select "Group: Gather blocks in a container." and turn off "Inner blocks use content width".
![2](https://github.com/WordPress/gutenberg/assets/2771396/630f314c-c5ed-4fc8-b367-e908b58e5677)

In this state, the background is no longer selected even if the width is set to full width or none.
![3](https://github.com/WordPress/gutenberg/assets/2771396/1e9abcc6-a4ef-4f5e-82fd-3c2b5f7df5e4)
![4](https://github.com/WordPress/gutenberg/assets/2771396/8a7cda65-b4d5-4fbb-ba39-3cea172fce0a)

The behavior is unified and there seems to be no problem at present.

**Comment by carolinan** [comment]
The problem is that the full and wide "inserter button"  or placeholder if you like, always shows as the default width, as seen in the updated screenshots.
