### ISSUE TITLE
Opinion: Having every paragraph as a block is confusing and creates too many controls

### ISSUE THREAD

**Issue by rosswintle** [WordPress/gutenberg#4222]
Hi,

This is an/my opinion.  I've searched a few pages of issues to see if it's anywhere else, but I couldn't find anything in the pages that I looked at (and there were a lot to wade through).

I've been using Gutenberg today to write a big post with lots of paragraphs. I did it partly on an iPad, and then, in frustration, switched to my desktop.

My opinion is this: having every paragraph as a separate block is confusing and creates too much pop-up user-interface/controls.

This was hard on an iPad because the combination of taps required to select some text in a different paragraph was really tricky (and it's different to selecting text in a different paragraph then it is to select text in the current paragraph), and just because there were so many controls appearing and disappearing as I moved around that it really got in the way of the writing experience.

I find myself wondering why every paragraph needs to be a block, and whether multi-paragraph blocks were tried at any point and rejected?

**Comment by atimmer** [comment]
See #3629 for some context. @jasmussen has written down some history in that comment thread: https://github.com/WordPress/gutenberg/issues/3629#issuecomment-346840261.

**Comment by karmatosed** [comment]
I think we should close this and add the conversation to #3629. Thanks for reporting and I hope you continue your insights on that issue @rosswintle.
