### ISSUE TITLE
Add a keyboard shortcut to create group

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#42227]
A common pattern in design software is that selected frames can be converted to a group via <kbd>CMD</kbd>+<kbd>G</kbd> (or similar) keyboard shortcut.

Now that site editing (where grouping is common) is becoming more prevalent it's worth considering adding a shortcut to do perform this action.

**Comment by talldan** [comment]
Just to add some history - my recollection is that there was a desire to do this before when grouping was first introduced, but the problem is Cmd+G is already a browser shortcut for 'Find Next'. Cmd+Shift+G is also 'Find Previous', and usually it's good not to override browser shortcuts.

It's a shame as I would usually expect Cmd+G to group. I'm not sure another shortcut would be quite as understandable.

**Comment by jameskoster** [comment]
Thanks for the context @talldan. Not sure if this is a good idea or even possible, but I wonder if it would be acceptable in this case assuming that cmd+g still behaved as 'Find Next' when the search box (cmd+f) is open.

Also curious about the principles for overriding shortcuts, because we do have things like cmd+s already.

**Comment by pagelab** [comment]
A shortcut for grouping blocks would be quite relevant. It's one of those actions that you do a lot while composing a page, post or template. 

I also don't think it's a good idea to override the default search-related browser shortcuts, as they are already useful in the context of the editor.

Maybe `⌃`  `⌥`  `G`  (Control + Alt/Option + G) is a good alternative, as several other shortcuts use `⌃`  `⌥`  as modifiers, and `⌃`  `⌥`  `G` it's not being currently used by most browsers. 

`⌃` `⌥` `H` – Display keyboard shortcuts. 
`⌃` `⌥` `O` – Open the block list view.
`⌃` `⌥` `N` – Navigate to the next part of the editor.
`⌃` `⌥` `P` – Navigate to the previous part of the editor.
`⌃` `⌥` `Z` – Remove the selected block(s).
`⌃` `⌥` `D` – Strike through the selected text.
`⌃` `⌥` `X` – Make the selected text inline code.

But testing in Safari (on a Mac), `⌃`  `⌥`  `G` adds a control character `<0x07>` to the content itself (for some weird reason). So I don't know if it can be actually overridden.

![2022-08-09 20 50 13](https://user-images.githubusercontent.com/1451087/183781037-faec506b-eaf1-4dba-9339-186b5b8890ec.gif)

**Comment by bissy** [comment]
I need ⌥+⌘+G for group block🥺

**Comment by t-hamano** [comment]
I have listed all the combinations of the character `G` and [the modifier which @wordpress/keycodes supports](https://github.com/WordPress/gutenberg/blob/980100c2546213237ae88f783ce6ac7fbb986346/packages/keycodes/src/index.js#L157-L169).

I am a Windows user, so if there are any errors in the Mac, please feel free to update.

| Modifier Name  | Mac combination                          | Windows combination            | Action                                   |
| -------------- | ---------------------------------------- | ------------------------------ | ---------------------------------------- |
| `primary`      | `⌘ command` + `G`                        | `ctrl` + `G`                   | Find Next                                |
| `primaryShift` | `⌘ command` + `Shift` + `G`              | `ctrl` + `shift` + `G`         | Find Previous                            |
| `primaryAlt`   | `⌘ command` + `⌥ option` + `G`           | `ctrl` + `alt` + `G`           |                                          |
| `secondary`    | `⌘ command` + `shift` + `⌥ option` + `G` | `ctrl` + `shift` + `alt` + `G` |                                          |
| `access`       | `^ control` + `⌥ option` + `G`           | `shift` + `alt` + `G`          | Print a control character (on Safari/Mac) |
| `ctrl`         | `^ control` + `G`                        | `ctrl` + `G`                   | Find Next (on Windows)                   |
| `alt`          | `⌥ option` + `G`                         | `alt` + `G`                    |   print © (on Mac)                                       |
| `ctrlShift`    | `^ control` + `shift` + `G`              | `ctrl` + `shift` + `G`         | Find Previous (on Windows)               |
| `shift`        | `shift` + `G`                            | `shift` + `G`                  | Enter capital G                          |
| `shiftAlt`     | `shift` + `⌥ option` + `G`               | `shift` + `alt` + `G`          |    print `˝` character ( on Mac)                                       |

This table shows that if we don't override the browser's shortcut, the choices are limited.
In addition, many design tools support ungrouping (unwrapping).

Given that, how about either of the following patterns?

- Group by `primaryAlt`, unwrap by `secondary`
- Group by `alt`, unwrap by `shiftAlt`

**Comment by talldan** [comment]
Option + G prints © for me. 

Shift + Option + G seems to print a ` ˝ ` character.

I think that leaves `primaryAlt` or `secondary` as the only options. There has been some pushback on Ctrl+Alt before as that's usually used for windows OS level features.

> Group by primaryAlt, unwrap by secondary

If unwrap is needed, then that seems like the only option.

**Comment by t-hamano** [comment]
@talldan 

Thanks for the info. It seems to us that the only option is `primaryAlt` if we were to use `secondary` for unwrapping in the future.

According to the following page, this combination is used in several applications.

- Mac: [What does the Cmd + Option + G keyboard shortcut?](https://defkey.com/what-means/command-option-g)
- Windows: [What does the Ctrl + Alt + G keyboard shortcut?](https://defkey.com/what-means/ctrl-alt-g)
