### ISSUE TITLE
Navigation List View: Introduce navigation editable tree view in the inspector controls

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#42257]
Building a custom navigation menu is fiddly. We have in various versions explored surfacing a List View interface for managing and building the contents of your navigation. Let's surface the list view in the inspector.

**When no menus exist**

In this state, all pages (Page List) is shown:

<img width="3120" alt="Navigation_ No menus" src="https://user-images.githubusercontent.com/1204802/183074208-8003f19a-6683-4ff6-ba4e-9636863fa462.png">

**A single menu exists**

In this state, this one menu is loaded by default:

<img width="3120" alt="Navigation_ One menu" src="https://user-images.githubusercontent.com/1204802/183074316-0bdd703b-bcc7-4bb7-bf77-864ff315849e.png">

**Multiple menus exist**

In this state, the context defines which menu is loaded by default. If the navigation block is inside the Header template part, "Header navigation" is loaded by default, even if "Navigation" and "Navigation 2" also exist. 

<img width="4640" alt="Navigation_ Multiple menus" src="https://user-images.githubusercontent.com/1204802/183075028-18ea541f-6454-4c75-94d4-5ce0f1accbaf.png">

To facilitate discoverability of this inspector interface, we should try to **enable the click overlay on the navigation block**, just like it is for template parts in the site editor. That way the first click on your navigation will always select the full block, and surface the inspector interface.

See also #40204 for an adjacent effort to divide the inspector into tabs, which will be useful for 30+ items in a navigation block.

---

This issue was updated Sep. 28.

<details>
<summary>See initial proposal</summary>

## What problem does this address?
Many users, both new and existing, have found the navigation block difficult to use. For new WordPress users, there are certain UI quirks that get in the way and jumping from parent to child blocks is challenging. For existing WordPress users who are new to FSE, there is a unique mix of directly editing the nav block (which is a new paradigm) and editing menus globally using the navigation sidebar.

<img width="929" alt="image" src="https://user-images.githubusercontent.com/1072756/177929386-33a55023-95c5-490a-9336-c494fd0e5fe3.png">

## What is your proposed solution?

https://user-images.githubusercontent.com/1072756/177929562-bec50ae8-5cf1-47ff-93d6-f74ac86b33cb.mp4

Id like to propose that we simplify by leaning more heavily into editing menus locally/on canvas via the navigation block and emphasise template parts / re-usable blocks / synced patterns as the primary way of editing site elements globally. 

A quick way of moving in this direction is simply moving the menu management experience into the navigation block settings sidebar, and removing the existing global navigation sidebar. We'd also enable adding navigation menu items from this management experience which removes the need to jump in and out of child blocks. Adding menu items makes use of the existing add menu item dialog. Menu editing can still be done directly on canvas, in this case I think the redundancy is fine.

The video shown here makes use of some of the ideas found [here](https://github.com/WordPress/gutenberg/issues/41717), namely surfacing child layers within patterns (e.g. header) which may be a more accessible way of selecting the navigation block for low tech users.

On top of the above change, a few other optimisations to make:
- The add menu item dialog removes the ability to transform from the menu item selection stage and instead adds a back button
- As seen in the screenshot above, the navigation toolbar can block menu selection when in an empty state
- It also partially covers up the new block button as shown below

<img width="608" alt="image" src="https://user-images.githubusercontent.com/1072756/177934325-18a35fb5-87e7-4569-93db-f5f9844f943e.png">

- This may just be a me issue but I've found the current state very buggy. Selecting the navigation block sometimes puts the editor into an unusable state, preventing me from selecting any other layer. Video attached.

https://user-images.githubusercontent.com/1072756/178391778-9a619e5a-2383-4e15-885e-78742bf30a16.mp4

I realise this contradicts from [this issue](https://github.com/WordPress/gutenberg/issues/36667) somewhat but if we introduce the idea of browsing/searching content in the sidebar then a dedicated UI for editing menu's becomes less important. We could still provide a way for managing menus outside the editor if there is value beyond just not having to enter the editor.

</summary>

**Comment by getdave** [comment]
@SaxonF Thank you for raising this Issue. I think it's a really nice idea to expose the structure of the current Navigation in the block's inspector controls.

------

A quick note about Nav block Issue management...

I recognise the need to track and collate the high level concerns around the Nav block.

As you can imagine, given its complexity, there are a lot of Issues about the problems with the block. Therefore I'd like to avoid creating another "overview" type Issue here.

Therefore, I trust you won't object if I rename this Issue to be specifically about moving the Navigation structure into the inspector controls?

I will then add it to the Tracking Issue under `High Priority` in order that we can have a central source of truth for everything and enable the community to more easily keep track of progress and priorities.

> On top of the above change, a few other optimisations to make:
Issues already tracked in the [Tracking Issue](https://github.com/WordPress/gutenberg/issues/38275) I'm going to normalize them there and raise dedicated Issues for any of the items that don't yet exist.

> The add menu item dialog removes the ability to transform from the menu item selection stage and instead adds a back button

@SaxonF Could you please explain this in a little more detail? I'm not following this one.

> As seen in the screenshot above, the navigation toolbar can block menu selection when in an empty state
> It also partially covers up the new block button as shown below

Tracked in https://github.com/WordPress/gutenberg/issues/42010

-----


If you have any concerns re: what I've done above please reach out. Happy to discuss 🙇‍♂️

**Comment by mtias** [comment]
Modified the title so that there's no confusion with the site structure work — this one should be about adding a way to edit the navigation block as a list in the block inspector.

**Comment by SaxonF** [comment]
@getdave I believe the current add new link dialog has a transform section at the bottom after selecting link type. I'm suggesting we remove that and just provide a way to go "back" to link type selection instead. I could be missing something here though so will leave it up to @javierarce to decide how to best move forward.

![image](https://user-images.githubusercontent.com/1072756/180721573-9ca68dc6-e5ae-467c-9c35-7ebcd8dc1efc.png)

**Comment by javierarce** [comment]
What I would probably add in that dialog is the possibility to filter by content type and a way to insert several links at once using checkboxes, which would give us the bulk inserting feature we missed from wp-admin (#31667)

![image](https://user-images.githubusercontent.com/4933/181302892-688ebdde-cdfc-4ff0-81c1-3927d35af825.png)

PS: I'm closing #42626 because I think it shares the same goals as this issue.

**Comment by javierarce** [comment]
Sorry, I deleted my previous comment which was:

> What I would probably add in that dialog is the possibility to filter by content type and a way to insert several links at once using checkboxes, which would give us the bulk inserting feature we missed from wp-admin (#31667)

![image](https://user-images.githubusercontent.com/4933/181310157-c93f678f-fda0-402c-aae4-104ae4c6bb07.png)

> PS: I'm closing #42626 because I think it shares the same goals as this issue.

What I missed was the option to create custom links, which the filter interface of the search bar I designed would make confusing. 

I think we can probably keep using the current Link Control UI (minus the transform section), so users can also add other types of content as they do now.

**Comment by jasmussen** [comment]
Love this ticket, beautiful work all around. Inspired by the work shared, and by [Matías comment on focusing in](https://github.com/WordPress/gutenberg/issues/42257#issuecomment-1193635735), I took a quick stab at extracting the ideas presented into a near-term version. Here are mockups of the navigation block as it exists today, but with the new Menu panel.

**No menus are defined**

In this state, all pages (Page List) is shown:

<img width="3120" alt="Navigation_ No menus" src="https://user-images.githubusercontent.com/1204802/183074208-8003f19a-6683-4ff6-ba4e-9636863fa462.png">

**One menu is defined**

In this state, this one menu is loaded by default:

<img width="3120" alt="Navigation_ One menu" src="https://user-images.githubusercontent.com/1204802/183074316-0bdd703b-bcc7-4bb7-bf77-864ff315849e.png">

**Multiple menus are defined**

In this state, the context defines which menu is loaded by default. If the navigation block is inside the Header template part, "Header navigation" is loaded by default, even if "Navigation" and "Navigation 2" also exist. 

<img width="4640" alt="Navigation_ Multiple menus" src="https://user-images.githubusercontent.com/1204802/183075028-18ea541f-6454-4c75-94d4-5ce0f1accbaf.png">

Those are the basic states with the new panel. We will likely find that for menus that have 30+ items, this panel will become a bit tricky. Something to explore separately could be to section the inspector further.

**Tabbed inspector**

In this, the inspector for blocks becomes split in two, Settings | Styles, or for the navigation block, Menu | Settings | Styles:

<img width="1600" alt="Navigation_ Tabbed inspector" src="https://user-images.githubusercontent.com/1204802/183075314-a6354ba7-e776-4203-b66e-98dd7978278a.png">

**Comment by jasmussen** [comment]
Reopening this one as it was closed by mistake.

**Comment by jasmussen** [comment]
A thought:

* Building your menu in the inspector is likely a better experience in most cases. We should probably disable clickthrough on the nav block itself, so that you always select the whole navigation block by default, surfacing the inspector controls.

**Comment by getdave** [comment]
> We should probably disable clickthrough on the nav block itself

Unfortunately the expectations seem to be different depending on context. We spent a while recently allowing for click-through to happen on inner blocks.

I wonder whether we could surface the controls _even if_ you select an inner Navigation block?

**Comment by jasmussen** [comment]
The "clickthrough" term causes me to stumble more often than not 😅 so just to be super clear about the idea, I mean this:

![clickthrough](https://user-images.githubusercontent.com/1204802/190081522-39299ca2-782f-432e-9f33-d44aff5b9249.gif)

Shown here, the first click on the Header selects it, and the entire block is the hit area. As soon as it's been selected, it's "unlocked" and you can select inner-blocks if you want to. My hope was that this behavior would be easy to enable on the navigation work, since it's a feature that already exists, but maybe it's not so simple? 

Surfacing the inspector controls immediately on first click would offer an ergonomic way to build your menu, but without blocking you from selecting inner blocks. Surfacing top level controls is something that's been explored in a few ways (content-lock, controls absorbtion), but those features are still somewhat immature. 

_I'm aware there was an issue with selecting the Page List block inside, sometimes requiring a double click. I _think_ that was an unintended bug._

**Comment by getdave** [comment]
> I'm aware there was an issue with selecting the Page List block inside, sometimes requiring a double click. I _think_ that was an unintended bug.

That what was I was remembering. Yes all good. We should aim for consistency with other blocks that exhibit similar behaviour and requirements.

**Comment by jasmussen** [comment]
For folks subscribed to this issue, I have updated the main body with mockups for next steps, adjusted tags, and hidden resolved or outdated comments. (If I hid a comment you find to still be relevant, please feel free to unhide it!)

This issue can have a big impact on improving the usability of the navigation block, so it would be great if someone could pick it up. Thank you! 🙏

**Comment by draganescu** [comment]
@jasmussen could you update the modals to include the manage menus link? We'd need to consider this is a very similar looking element and it needs some space or to be more delimited from the list view.

**Comment by jasmussen** [comment]
Can we include the "Manage menus" link inside the menu dropdown? It feels contextual to that, since the link itself only makes sense if you have more than 1 menu created.

**Comment by draganescu** [comment]
We just removed the manage menus from that drop down. It was extremely out of context and also did a very surprising action for that dropdown, navigating away to a new admin page - while all other options act on the selected navigation block. Let's try something else :)

Also on the idea of a "create new" item, should this be a property of the list view in general? Right now, one has to add before/after using the more menu. Should we come up with such an always on last leaf list view appender?

**Comment by jasmussen** [comment]
To me the placement is about managing prominence. Ideally managing multiple menus is something you should not be doing 80% of the time. So wherever it should sit should be easily findable, but not a primary action. I do agree it being an external link is one challenge, another is the experience of landing on that page where it looks like multiple posts: it's not a good place to edit your menus. If anything I'd be tempted to hide the link altogether because it isn't a good experience yet. As an alternative to living inside the dropdown, should it live under "Advanced", in context of the menu deletion button?

**Comment by jasmussen** [comment]
I'm not convinced in the following since it isn't a pattern we've used elsewhere. But an alternative is a settings button to the right of the dropdown:

<img width="364" alt="Frame 490" src="https://user-images.githubusercontent.com/1204802/193000605-ad038b43-525b-4140-930b-4781bc603556.png">

**Comment by draganescu** [comment]
I think moving it to the advanced area makes sense, under the delete menu button.

**Comment by draganescu** [comment]
@jasmussen what should we do about the always expanding nature of the nested list view:


https://user-images.githubusercontent.com/107534/193082775-f180abed-9b2c-49b8-9d1f-86cbb2ce9090.mp4

Edit: we could at least limit the overflow to the list view's container and leave the rest of the inspector solid.

**Comment by draganescu** [comment]
Playing more with this, I find that we really need to think this through IMO - any action is weird in this context. For instance, duplicating a link block would select the block. We can't disable this normal behavior all over:

- either we figure out a cool UX which neatly balances items with parent mantaining the list view in the inspector
- or we dont reuse the ListView
- or we somehow have to bloat the ListView with soft toggles all over.

It feels the endeavour to "add a list view to the navigation block's inspector" is not enough :) a deeper exploration of the effects would be great I think.

**Comment by jasmussen** [comment]
Just to respond to the question of the expanding list view, there was some conversation in #35605 around how to address that, which I extracted into a separate issue in #44603. 

Zooming out for a bit, the purpose here is to provide a convenient building interface for nested and complext menu structures, as an alternative to the canvas itself which has proven complex. The list view was suggested as it contains the tree structure and much of the drag and drop behavior already added. 

I understand the challenge: the component was built to be permanently visible and to select blocks. When visible in context of _a block_, then selecting _another block_ would replace the inspector. As a basic question: what would we miss if we simply hide the ellipsis on a list view item? Omitting "Remove" would be a problem, but I like to think this action could be surfaced contextually as it has higher value than being hidden in the menu.

**Comment by mtias** [comment]
@draganescu did you consider leveraging some of the same mechanisms of the new content-lock? It seems the absorbing of the list view would be fairly close in interactions there.

**Comment by draganescu** [comment]
I will add some things discussed in a separate chat with @jasmussen @SaxonF @jameskoster and @mtias 👍🏻 

- the inspector tree for the navigation block should be seen more than a "list view" adaptation, but instead a way to manage a list of child blocks without touching the canvas, a feature with its own challenges but which can take inspiration from:
  - the content only editing template lock
  - the tree management of the list view
  - the drill down panel navigation of global styles
 
- [ ] a design exploration of how to combine drag and drop reordering of items and the drill down mechanics for individual editing of items is needed at this point
- the implementation of the editable tree view of the navigation block would:
  - [ ] reduce the white space of list view items and use wrapping so that we don't horizontally scroll the inspector until more than three nesting levels exist
  - [ ] be the 1st iteration of the tabbed interface ideas in https://github.com/WordPress/gutenberg/issues/40204 to allow for a better experience with horizontal scrolling
  - [ ] implement inserting new blocks via fake leaf buttons
    - [ ]  reusing the logic where it inserts navigation links if the menu only has this type of child block
    - [ ] but also opening a sort of new kind of quick inserter in a pop over or modal for the other case (this could work with the quick inserter in a modal that should bring it over to distraction free mode)
    - [ ] allow inserting anywhere in the tree by showing the fake leaf at the bottom of the immediate content of the currently open leaf
  - [ ] the editable tree view of the navigation block would share the same items in the more menu with the list view, plus an eventual edit item that could trigger the "drill down" operation
    - which selects the block in the canvas and shows its inspector but allows to get back to parent a la global styles
 
We'd need to keep the Listview as the underlying component since it solves so much of the interaction model and it implements the best practices required for this kind of item navigation model.

**Comment by SaxonF** [comment]
Latest prototype attached. Still working through some little details but I don't think those details will block build. A couple notes
- auto-menu is just an attempt at rebranding pages list. This is something we can think on and don't need to act on right now.
- Its not reflected in the prototype but selecting a menu item should also select on canvas

https://user-images.githubusercontent.com/1072756/196836049-e23cb250-b423-4977-a657-8922feb8b3c2.mp4

**Comment by draganescu** [comment]
This mention:

> Its not reflected in the prototype but selecting a menu item should also select on canvas

has the caveat that selecting the block in the canvas moves the block inspector to that block's inspector. Editing a menu item will select it in the canvas (clicking on the pen icon).

Also, not visible in the mockup, but to be useful for navigation off canvas editing the list view should:

- support automatically converting a navigation link into a submenu when menu blocks are dragged and nested
  - there will also be a _functioning_ "move to" action in the kebab menu that achieves the same outcome
- support fake "add menu item" leafs to expand from nevigation link and submenu blocks

This will require some interesting updates as currently we're leaning into inner blocks to decide if nesting drag and  dropping is even possible.

**Comment by talldan** [comment]
@SaxonF I noticed the demo above adds a new pencil icon to open the settings of a link, but clicking on the block itself in this new version of List View doesn't do anything. Was just wondering about the reasoning behind that and whether the pencil is needed?

It might be an easier implementation if clicking the block itself opened the settings and [it should align more closely with the content locking UI - outlined here](https://github.com/WordPress/gutenberg/pull/42684#issuecomment-1199621547), which this has some similarity to.

**Comment by getdave** [comment]
I like the idea of synergy with the interactions in content-lock mode. As this view is more interactive than content-locking mode do we need to consider whether this "click to edit" will impact drag and drop or access to the 3 dots menu?

**Comment by jasmussen** [comment]
> do we need to consider whether this "click to edit" will impact drag and drop or access to the 3 dots menu?

You mean for individual items in the canvas? 

The in-canvas interactions are fiddly and need love, but hopefully this inspector interface can provide near-future navigation usability, while we make those improvements. So I wouldn't emphasize in-canvas interactions too much in the now.

**Comment by talldan** [comment]
> You mean for individual items in the canvas?

I mean the block in List View. (edit: oh wait, this wasn't in response to me, now I'm a bit confused 😄 )

> As this view is more interactive than content-locking mode do we need to consider whether this "click to edit" will impact drag and drop or access to the 3 dots menu?

I don't think this would cause an issue, it works in the main List View.

**Comment by draganescu** [comment]
The problem with clicking the list view item to edit is that it immediately replaces the inspector with the inspector of the newly selected block hiding the list view in the process. A slow drag and drop will also get this. Hence the idea to use an explicit action for edit in this case.

**Comment by talldan** [comment]
> The problem with clicking the list view item to edit is that it immediately replaces the inspector with the inspector of the newly selected block hiding the list view in the process.

My idea is to replace the primary action of the item. Show the inspector controls for the block when clicking the item. There would be no way to select a block.

> A slow drag and drop will also get this.

😕 What's a slow drag and drop? This sounds like a bug that should be fixed.

**Comment by draganescu** [comment]
A slow drag and drop is when the drag comes a bit too late after the mouse down, like... a batter name would be a failed drag and drop. And if you want to drag and fail and that causes the context to change is too jarring.

BUT I like the idea to _replace_ the action from canvas block selection to navigation. It could work and definitely should be tested. I think if this works it is better than cluttering that tiny space with yet another icon. 👏🏻

**Comment by draganescu** [comment]
@SaxonF @mtias @javierarce  are we set on that "edit menu" button in the navigation block's toolbar? I ask because:

- that action is replicating More menu > Show more settings
- the action does not do what it says (no editing is happening)
- did we decide the menu is read only in the canvas? If no, why would we have an edit menu button?
- it's a poor fit for the block toolbar in this shape, because it resembles "edit template part" which has a completely different effect.

As https://github.com/WordPress/gutenberg/pull/45772 started to implement this I'd like to be sure this is really an intention and wasn't merely an exploration.

**Comment by draganescu** [comment]
@jasmussen @SaxonF given the progress in #[45785](https://github.com/WordPress/gutenberg/pull/45785) do we want the manage menus thing to move _out of the advanced area_ and into the menu selector? I ask because:

- I believe the goal was to de-prioritize that action, as it really is an advanced situation
- The manage menus action _was_ in the menu selector when the selector was in the block toolbar and we intentionally moved it out when repositioning the navigation selector in the block's inspector.

**Comment by jasmussen** [comment]
I left some feedback on the "manage menus" in https://github.com/WordPress/gutenberg/pull/45785#issuecomment-1318324861, but also noted that it's not a strong opinion. Exactly for the reason you mention, the feature should not have prominence, they key bit here not being a blue link in the main panel.

**Comment by priethor** [comment]
@draganescu @getdave @scruffian, is there any remaining follow-up left before considering a v1 of this feature ready and closing this issue?

**Comment by getdave** [comment]
Yes I think the v1 is ready. It's just landed in the Plugin as non-experimental as well.

I think a final review by @WordPress/gutenberg-design would be useful. But otherwise we've paused work on any new features for the v1 of this effort and are now focused on bugs.

**Comment by paaljoachim** [comment]
Is there a specific PR (multiple PRs?) that I should take for a spin?

**Comment by scruffian** [comment]
@paaljoachim you should be able to see it in trunk now.
