### ISSUE TITLE
[Cover Block] When used in a Query Loop, make it possible to turn the Cover block into a link to the post

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#42252]
## What problem does this address?
It's great that the Cover block can be used to display the featured image of a post when used inside a Query Loop block, but it would also be really useful if we could make the entire Cover block a link that points to the post the featured image belongs to. 

Currently, you'd need to add a Post Title block with "Make title a link" selected, but that results in a very small area of the cover being clickable. It would be reasonable for visitors to try and click anywhere on the Cover block to go to the post.

Related to https://github.com/WordPress/gutenberg/issues/12684.

## What is your proposed solution?
When the Cover block is used in a Query Loop, add a setting that allows users to turn the Cover block into a link that points to the post.

**Comment by masteradhoc** [comment]
+1

**Comment by sophiegyo** [comment]
Within the context of a Query Loop, I'd love this. I made [a terrible hack (screenshot)](https://github.com/WordPress/gutenberg/assets/36608681/f757af8f-f38a-4be0-8343-04120535e141) using a Read More block which I set to 0 opacity in the text colour setting, and increased the padding so it took up the full area of the cover but I'm fairly sure that's not particularly accessible.

Being able to properly link the cover block within the context of the Query Loop (IMO it doesn't even need to be linkable outside a Query Loop) would be very nifty.

**Comment by jordesign** [comment]
This is a great suggestion - and one that extends beyond cover blocks to also include Group blocks or Column blocks. There's an issue open discussing that broader implementation - so I'll close this one in favour of that.
https://github.com/WordPress/gutenberg/issues/53052

**Comment by adovgun** [comment]
Since this was closed as not planned — for anyone who still needs a Cover block with a featured image to link to its post inside a Query Loop, I built [4WP Smart Link](https://wordpress.org/plugins/4wp-smart-link/) to solve exactly this. It makes the whole Cover block clickable inside Query Loop cards while keeping inner links (post title, buttons) working correctly.

Wrote up the case that led to it: https://4wp.dev/4wp-smart-link-open-source-plugin/
