### ISSUE TITLE
Remove extraneous step to edit the theme color palette via Global Styles

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#42274]
## What problem does this address?

Currently there's an extraneous step to edit the site color palette. 

To get there you: 
1.  Open Global Styles
2.  Click on "Colors"
3.  Click on "Palette"
4.  Click on the vertical ellipsis menu icon
5.  Click "Edit colors"

The Palette view is what is currently redundant. You can't actually do anything other than edit colors (either the theme, default) or add new colors. 

## What is your proposed solution?

I suggest we skip this step and have the theme's palette already in the "Edit" mode, bringing the main action of editing your site/theme's color palette front-and-center, instead of requiring another two interactions to actually edit the colors. 

We also wouldn't need the vertical ellipsis  or the "Done" UX (at least for the Theme palette). 

<img width="737" alt="CleanShot 2022-07-08 at 10 48 00@2x" src="https://user-images.githubusercontent.com/1813435/178016469-013f1e7b-4cd4-4aa2-96ba-517fa8899bca.png">

<img width="734" alt="CleanShot 2022-07-08 at 10 53 43@2x" src="https://user-images.githubusercontent.com/1813435/178017180-7bafd796-d9a9-495f-adb6-1e1521d81bc1.png">

### Here's a screen recording of the current flow:
https://user-images.githubusercontent.com/1813435/178014843-f0bfe855-5376-4f7d-9168-5ce616bb3062.mp4

## Notes & Thoughts
- I'm curious if users are actually editing the "Default" colors
- I'm not convinced we need to separate the theme/custom colors so much (especially given the currently UI priority to "Default" above "Custom" colors). I know technically it matters - but perhaps "Theme" could be renamed "Site" and if you add a color to your site palette; it's technically a custom color, but alongside your other site colors. They don't have to be a whole separate idea. Perhaps I'll draw up something and pitch it in another issue.

**Comment by jordesign** [comment]
In my testing - the colors in the Palette view are now directly editable - so I'll close this issue as no longer reproducible.
