### ISSUE TITLE
Ancestor block setting (metadata) not implemented

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#42277]
### Description

In [Block editor handbook](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/) a new block setting is mentioned, "ancestor". However, when registering a block with this setting, desired functionality (block should appear in inserter only if one of his ancestors is mentioned in array of ancestors in block.json) can not be observed. Further, upon inspection of block type (`wp.blocks.getBlockType('prefix/block-name')` in console when block editor is open), it seems that this setting does not get registered at all, it is not in the list of properties.

### Step-by-step reproduction instructions

1. Create parent block
2. Create child block, with setting in block.json `ancestor: ["parent-block-name"]`
3. Open block editor, try inserting child block when there is no ancestor block. It still appears in the inserter and it is possible to insert it, while it should not be.

### Screenshots, screen recording, code snippet

block.json:
```
{
	"$schema": "https://schemas.wp.org/trunk/block.json",
	"apiVersion": 2,
	"name": "makeiteasy/block-input",
	"version": "0.1.0",
	"title": "Input control",
	"category": "makeiteasy-block",
	"keywords": ["input", "control"],
	"icon": "forms",
	"description": "Input button - various formats",
	"supports": {
		"anchor": true,
		"align": true,
		"color": {
			"text": true
		},
		"spacing": {
			"margin": true,
			"padding": true,
			"blockGap": true
		},
		"typography": {
			"fontSize": true,
			"lineHeight": true
		}

	},
	"textdomain": "domain",
	"editorScript": "file:./index.js",
	"editorStyle": "file:./index.css",
	"style": "file:./style-index.css",
	"parent": ["makeiteasy/block-ancestor"],
	"ancestor": ["makeiteasy/block-ancestor"],

	"attributes": {
		"value": {
			"type": "string",
			"source": "attribute",
			"attribute": "placeholder",
			"selector": "input"
		},
		"label": {
			"type": "string",
			"source": "html",
			"selector": "label"
		},
		"type": {
			"type": "string",
			"source": "attribute",
			"attribute": "type",
			"selector": "input",
			"default": "text"
		},
		"name": {
			"type": "string",
			"source": "attribute",
			"attribute": "name",
			"selector": "input"
		},
		"nameAutoSet": {
			"type": "boolean",
			"default": true
		},
		"align": {
			"type": "string",
			"default": "left"
	  }
	}
}
```

Example of console output:
```
wp.blocks.getBlockType('makeiteasy/block-input')

{
  "name": "makeiteasy/block-input",
  "icon": {
    "src": "icons"
  },
  "keywords": [
    "input",
    "control"
  ],
  "attributes": {
    "value": {
      "type": "string",
      "source": "attribute",
      "attribute": "placeholder",
      "selector": "input"
    },
    "label": {
      "type": "string",
      "source": "html",
      "selector": "label"
    },
    "type": {
      "type": "string",
      "source": "attribute",
      "attribute": "type",
      "selector": "input",
      "default": "text"
    },
    "name": {
      "type": "string",
      "source": "attribute",
      "attribute": "name",
      "selector": "input"
    },
    "nameAutoSet": {
      "type": "boolean",
      "default": true
    },
    "align": {
      "type": "string",
      "default": "left"
    },
    "lock": {
      "type": "object"
    },
    "style": {
      "type": "object"
    },
    "backgroundColor": {
      "type": "string"
    },
    "textColor": {
      "type": "string"
    },
    "className": {
      "type": "string"
    },
    "fontSize": {
      "type": "string"
    },
    "anchor": {
      "type": "string",
      "source": "attribute",
      "attribute": "id",
      "selector": "*"
    }
  },
  "providesContext": {},
  "usesContext": [],
  "supports": {
    "anchor": true,
    "align": true,
    "color": {
      "text": true
    },
    "spacing": {
      "margin": true,
      "padding": true,
      "blockGap": true
    },
    "typography": {
      "fontSize": true,
      "lineHeight": true
    }
  },
  "styles": [],
  "variations": [],
  "apiVersion": 2,
  "title": "Input control",
  "description": "Input button - various formats",
  "category": "makeiteasy-block",
  "parent": [
    "makeiteasy/block-ancestor"
  ]
}
```

### Environment info

WordPress 6.0

- it is possible to reproduce the issue with WP 6.0 or with activated Gutenberg plugin (v. 13.6.0)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Lovor01** [comment]
On further investigation, it seems that it does not work only when defined in block.json; if it is defined as object property when registering block with `registerBlockType` then it works. Conclusion is that something about parsing that property from block.json is broken.

**Comment by Lovor01** [comment]
I discovered that issue exists only when block is registered from php, and the cause is missing mapping of property in blocks.php, in function `register_block_type_from_metadata`. I will suggest a fix in official repository! I believe I can close this.

**Comment by Lovor01** [comment]
I opened a trac with patch [#56184](https://core.trac.wordpress.org/ticket/56184), I hope it will be resolved soon?

**Comment by annezazu** [comment]
@gziolo perhaps you might have some insights here?

**Comment by gziolo** [comment]
@Lovor01, thank you for opening the patch in WordPress Trac. I will review and land next week ❤️

**Comment by Lovor01** [comment]
Glad to be of help - I am clossing this issue now.

**Comment by gziolo** [comment]
It's now resolved in the `trunk` in WordPress core. I'm checking how to propose it for inclusion in the potential 6.0.2 patch release.
