### ISSUE TITLE
Block styles, but defined by theme

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#42291]
## What problem does this address?

I want to set my blocks in accordance with my style guide in a single click.

For example, my brand uses two different paragraphs styles:

* A larger one with line-height of 1.6
* A smaller one with line-height of 1.8

As seen on the screenshot below:

<img width="776" alt="CleanShot 2022-07-10 at 13 24 59@2x" src="https://user-images.githubusercontent.com/205419/178142901-80c27a6b-e052-4131-8193-c24df8932155.png">

Right now I have to manually select all the typography settings from the block inspector for each paragraph.

What I want is a one-click UI like this:

<img width="297" alt="CleanShot 2022-07-10 at 13 21 28@2x" src="https://user-images.githubusercontent.com/205419/178142782-3be401b0-0597-4c6d-8722-5781cdefe72f.png">

It's similar to block styles, but it would have to be shipped by the theme.

cc @WordPress/block-themers @scruffian

**Comment by carolinan** [comment]
I did not understand -block styles can already be defined by the theme, with the UI in the screenshot.
https://developer.wordpress.org/block-editor/reference-guides/block-api/block-styles/

**-What it does not do**, is change the visible value of the control, in this case, the line height. It adds the CSS that you define for the style.

**Comment by scruffian** [comment]
I suggested @adamziel add this as I was under the impression that themes shouldn't specifying their own block styles. However I was mistaken. I think @carolinan is right, this seems like a perfect case for themes to specify their own block styles.
