### ISSUE TITLE
Button elements: text decoration isnot applying in the frontend on the button block

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#42292]
### Description

The text decoration settings for the button elements are not applying for the Button block on the frontend (they work on the editor).

### Step-by-step reproduction instructions

Add this to theme.json inside styles:

```
"elements": {
	"button": {
		"typography": {
			"textDecoration": "underline"
		}
	},
}
```

Insert a button and check the editor and the frontend. Empty theme works fine for this.

### Screenshots, screen recording, code snippet

Editor

<img width="770" alt="Screenshot 2022-07-10 at 13 26 01" src="https://user-images.githubusercontent.com/3593343/178143003-51d95a72-77a7-4ddf-b8e3-f46be6585d7f.png">

Frontend

<img width="746" alt="Screenshot 2022-07-10 at 13 26 08" src="https://user-images.githubusercontent.com/3593343/178143000-20c3b289-6fa0-409b-9d30-93031e491c7f.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
When I add the typography setting above I see:
Comments form button -no underline on front
Search button -underline on front
Button block -no underline on front

**Comment by t-hamano** [comment]
The problem seems to be that `.wp-block-button__link` styles override the style by `theme.json`.
It may be effective to use `:where` to set the specificity to zero.

![button](https://user-images.githubusercontent.com/54422211/179900657-233e73cb-17ae-40b7-8e90-0f9744b22616.png)
