### ISSUE TITLE
Opinionated block styles applying in the editor but not on the frontend

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#42300]
### Description

A theme that doesn't add the opinionated block styles will still see some of them in the editor, creating a disconnect between what's on the editor and on the frontend.

### Step-by-step reproduction instructions

Install a theme that doesn't add support for `wp-block-styles` (or remove `add_theme_support( 'wp-block-styles' );` from functions.php), insert a group block with some content and add a background color to it. 

You will see that the editor shows a padding on the group block that is missing from the frontend.

### Screenshots, screen recording, code snippet

Frontend:

<img width="943" alt="Screenshot 2022-07-10 at 18 26 40" src="https://user-images.githubusercontent.com/3593343/178153437-91cb3412-8eb9-472b-b2f7-9359f37a522a.png">

Editor:

<img width="1062" alt="Screenshot 2022-07-10 at 18 26 34" src="https://user-images.githubusercontent.com/3593343/178153438-da6a16b2-4ba5-49e0-8105-f48d247c2a44.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi
I have not been able to reproduce this.
Using emptytheme, there is no extra padding.
Using Twenty Twenty-two there is padding, but because the theme adds left and right padding in style.css.

**Comment by MaggieCabrera** [comment]
> Hi I have not been able to reproduce this. Using emptytheme, there is no extra padding. Using Twenty Twenty-two there is padding, but because the theme adds left and right padding in style.css.

Emptytheme does[ include the support for the block styles](https://github.com/WordPress/theme-experiments/blob/bced81dbd0c17f15d70d4ecdcf9666641390c1cb/emptytheme/functions.php#L7), did you try removing it?

**Comment by carolinan** [comment]
Yes I removed it. Tested both with and without Gutenberg trunk active.

**Comment by draganescu** [comment]
I **cannot** repro this using a very minimalist block theme (Ames).

**Comment by MaggieCabrera** [comment]
Closing this, can't reproduce anymore, it might have been something weird with my environment.
