### ISSUE TITLE
Site Editor: Add a link to view the site

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#42316]
To go from the site editor to viewing the frontend of your site is a long-winded exercise. It would be nice if there was a more direct pathway.

A couple of options:

**Add a link to the site title in the navigation panel**

<img width="383" alt="Screenshot 2022-07-11 at 10 05 53" src="https://user-images.githubusercontent.com/846565/178229021-88a77bf2-d8e6-4f50-a0e1-36c89a2b2dfb.png">

**Add a link to the 'Preview' menu**

<img width="294" alt="Screenshot 2022-07-11 at 10 06 22" src="https://user-images.githubusercontent.com/846565/178229094-51a1b318-5e58-486b-a454-fad8a2017325.png">

With this second option, we might consider [updating the button label](https://github.com/WordPress/gutenberg/pull/29151) since we do not have drafting functionality for templates / styles just yet, and so 'Preview' is a bit of a false promise.

**Comment by mtias** [comment]
I think we should rename "Preview" to "View" in the site editor and add a section beneath desktop/tablet/mobile that is "View Site ->".

**Comment by carolinan** [comment]
I believe the second option, the preview/view menu, is what has been requested by users.
