### ISSUE TITLE
Theme style variations work inconsistently

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#42323]
### Description

Switching between style variations, mixes the styles from both variations.
It gets few styles from the previous style variation and few from current style variation.

This is happening in both **.wordpress.com** site and a local WordPress setup.
Behaviour is observed inconsistently, sometimes for the first change, and sometimes after 2nd or 3rd change of style variation.

### Step-by-step reproduction instructions

Activate a theme which has multiple style variations such as [Pendant](https://wordpress.org/themes/pendant/) or [Remote](https://wordpress.org/themes/remote/).
Open the WordPress site and observe that theme with default style variation is applied and working good.

Click **Edit site** and go to global styles > browse styles > Choose a variation (such as Electric blue for Pendant)
Style variation change reflects in the editor and frontend (the first time)
<img width="581" alt="image" src="https://user-images.githubusercontent.com/1935113/178244656-8563e69b-71eb-4e61-86b7-7090eaf4ed21.png">

* Now again choose a different style variation from the same theme (Pendant as example, choose Pink)
* Now observe that mix of both Electric blue and Pink styles are applied.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/1935113/178245774-f1bc1701-d654-4925-9505-03e8f43974e8.png">

**Expected Result:**
<img width="581" alt="image" src="https://user-images.githubusercontent.com/1935113/178246877-054150df-2e70-41a7-8967-6bf274d794b1.png">

### Screenshots, screen recording, code snippet

![pendant-styles](https://user-images.githubusercontent.com/1935113/178248524-d81b4528-986a-43ee-ab71-59c1d515c8cf.gif)

### Environment info

- Wordpress Latest (6.0)
- Gutenberg latest (13.6)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi, can this be reproduced outside wordpress.com, on a standalone WordPress install? I am not sure how else we can determine if it is a Gutenberg, theme,  or WordPress.com bug?

**Comment by madhusudhand** [comment]
I also have tested it with a local WordPress install, and the issue reproduced with our without enabling Gutenburg plugin.

Also, when the style variation is in inconsistent state, toggling (enable/disable) the Gutenburg plugin, and reloading frontend fixes everything. Style variation applies correctly.
And this behaviour is observed with multiple themes.

So, It should be a WordPress or Gutenberg bug, not a theme or WordPress.com specific bug.

**Comment by Andrew-Starr** [comment]
@madhusudhand I took a go at trying to recreate this issue but was unable to see any problems when switching styles.

You say that you tested with the Pendant and Remote themes, but as far as I can see these two themes do not have any style variations available to select.
See empty 'styles' directory in Pendant: https://themes.svn.wordpress.org/pendant/1.0.4/styles/ and same with Remote: https://themes.svn.wordpress.org/remote/1.0.6/styles/

I'm curious where are the Electric Blue and Pink styles from?
Could the issue be with those additional `style-name.json` files if they are from somewhere else, and not included with the theme?

**Comment by Andrew-Starr** [comment]
Ahhh now I see the wordpress.com versions of those themes do indeed have style variations whereas the wordpress.org versions as linked in the repro instructions do not.

**Comment by madhusudhand** [comment]
Ah! Thanks for pointing. It must be an issue with publish script.
Please use the themes from source to test in local install. https://github.com/Automattic/themes/tree/trunk/remote

**Comment by kathrynwp** [comment]
@madhusudhand Could you please confirm whether you're able to reproduce this issue on a self-hosted install with **non-WordPress.com themes** that have style variations, such as Twenty Twenty-Two?

**Comment by madhusudhand** [comment]
@kathrynwp I tested the same scenarios on self-hosted install. Style changes between variations are working properly.

**Comment by kathrynwp** [comment]
@madhusudhand Thanks for reporting back. Since this is only happening with WordPress.com themes and can't be replicated otherwise, I'm going to go ahead and close out this issue, as it does seem to be specific to WP.com themes and not a WP-wide issue.
