### ISSUE TITLE
Site Title: Impossible to override theme.json setting with an instance of the block.

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#42330]
### Description

It is impossible to override theme.json setting with an instance of the Site Title block.

### Step-by-step reproduction instructions

Add this to your theme.json file:

```
			"core/site-title": {
				"elements": {
					"link": {
						"color": {
							"text": {
								"ref": "styles.color.text"
							}
						}
					}
				}
			}
```

Now add the site title block to a template/post and modify the color of the link. The setting from theme.json takes priority still.

### Screenshots, screen recording, code snippet

<img width="1417" alt="Screenshot 2022-07-11 at 16 23 21" src="https://user-images.githubusercontent.com/275961/178286842-9bf188cd-e01b-4c73-be58-98db5147c5c0.png">
<img width="1211" alt="Screenshot 2022-07-11 at 16 23 54" src="https://user-images.githubusercontent.com/275961/178286960-3ca9a40a-92b6-4faf-80e2-01149ee21786.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I am not able to reproduce this with current Gutenberg trunk (14.0 rc).
The resulting CSS is:

```
.wp-elements-8d95b57417310fb18a39fe4e32abf24b a {
    color: var(--wp--preset--color--luminous-vivid-orange); // block style selected in editor, shows
}

.wp-block-site-title a:where(:not(.wp-element-button)) {
    color: green; //theme.json site title elements link, overwritten
    text-decoration: none;
}
a:where(:not(.wp-element-button)) {
    color: var(--wp--preset--color--contrast); // theme.json root level elements link, overwritten
    text-decoration: underline;
}
```

_I did not use ref_

**Comment by scruffian** [comment]
I can confirm this is no longer happening for me.
