### ISSUE TITLE
Button Align Center Width

### ISSUE THREAD

**Issue by Nullception** [WordPress/gutenberg#42338]
For some reason, this CSS property is changing the width of a button block that is centered.

https://github.com/WordPress/gutenberg/blob/0b93618903e360b19ac14967dda7cdfeb0432447/packages/block-library/src/button/style.scss#L47

This is what it looks like in the block editor.
![image](https://user-images.githubusercontent.com/6423675/178313611-7353fb46-1d48-4625-a024-da5c5e93f076.png)

When you go to view the page on the site it looks like this.
![image](https://user-images.githubusercontent.com/6423675/178313920-6d5daff3-c7dc-4b64-98fa-0cc50e3a8302.png)

While investigating the cause I saw this CSS property was the culprit.
`/wp-includes/css/dist/block-library/style.min.css?ver=6.0`
![image](https://user-images.githubusercontent.com/6423675/178314070-1cc799ff-cff4-40cb-b2c9-39eb3e3491fb.png)

I am running the latest version of WP. I will gladly update this ticket with any information you might still need.

**Comment by kathrynwp** [comment]
Hi @Code-Bear - thanks for the report.

I haven't been able to replicate this yet with Twenty Twenty-Two and WP 6.0, with Gutenberg 13.6.0 either active or inactive.

Could you please let me know:

- If you have the standalone Gutenberg plugin active, and if so, what version is it?
- Is the issue present with all your plugins temporarily deactivated? You can use the Health Check plugin for this, which will not change your live site – https://wordpress.org/plugins/health-check/
- What theme are you running? Is the issue present with a default theme like Twenty Twenty-Two? Again, you can use the Health Check plugin for this. 
- Are you taking any extra steps in the editor after adding the Buttons block, and if so, could you please list them out in detail? For example, are you changing any of the default Buttons block settings, and if so, how?
- Could you provide a link to a page or post on your site where I can see the issue directly?

Thanks!

**Comment by ndiego** [comment]
Hi @Code-Bear, this issue came up in this week's Editor Bug Scrub meeting. Attendees were unable to replicate with the latest version of Gutenberg and the Twenty Twenty-Two theme, so our thought is this might be a theme issue 🤔 The `width: 100%` style exists in Gutenberg, but does not generate the result you are seeing.

Would you be able to provide some more info regarding your setup?

**Comment by Nullception** [comment]
I can no longer reproduce it myself, so maybe there was some kind of caching issue. Sorry to set up a ticket for a non-issue.
