### ISSUE TITLE
Search block generates duplicate IDs for search-icon if used multiple times

### ISSUE THREAD

**Issue by MatzeKitt** [WordPress/gutenberg#42347]
### Description

Assume that you want to have two or more search bars on your page, e.g. one in the header and one in the content. If you use the search block both times, the search icon generates the identical ID `search-icon` both times if you use the icon button of the search button.

### Step-by-step reproduction instructions

1. Add a search button to the content.
2. Enable "Use button with icon" in the search button.
3. Duplicate the button.
4. Look at the source code or validate the frontend page's HTML.

### Screenshots, screen recording, code snippet

<img width="897" alt="Bildschirmfoto 2022-07-12 um 07 12 09" src="https://user-images.githubusercontent.com/1018979/178414113-d6c23669-0aa6-469b-ab99-835c1213fd06.png">

### Environment info

WordPress 6.0
No Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @MatzeKitt

I think this was fixed via #40828.

**Comment by MatzeKitt** [comment]
Ah yes, it looks like this!
