### ISSUE TITLE
Return to editor link on Revisions page takes me back to Classic Editor

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4237]
## Issue Overview
On the Compare Revisions page, the _Return to editor_ link takes me back to the editor page, but puts me in the Classic Editor instead of Gutenberg

## Steps to Reproduce (for bugs)
1. Edit page
2. Click on the link to view your page revisions
3. Click the _Return to editor_ link at the top of the revisions page

## Expected Behavior
Return to editor should take me back to the page using the editor that the page was created in. I.E. If the page was created using Gutenberg, take me back to the Gutenberg Editor. Alternatively, if the page was created using the Classic Editor, then return to the Classic Editor page.

## Current Behavior
Automatically puts me in the Classic Editor regardless of the editor that that the page was created in.

_Firefox Quantum 57.0.3 (64-bit)
Gutenberg 1.9.1_

**Comment by youknowriad** [comment]
I believe this is already fixed in master (see #3511). It should be released pretty soon.
