### ISSUE TITLE
Full-width aligned blocks are no longer full-width

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#42374]
### Description

It looks like full-width aligned blocks are no longer full-width with the trunk. If I deactivate the plugin, it becomes full-width as expected. I remember full-width aligned blocks aren't full width in the editor for quite some time, and now the front of the site also displays it as non-full width. I tested with Twenty Twenty-two, but this is not a theme-specific issue.

### Step-by-step reproduction instructions

1. Go to the editor
2. Add a block and set it as full-width.
3. See it on the front of the site.

### Screenshots, screen recording, code snippet

| Without plugin      | with plugin |
| ----------- | ----------- |
|   ![Screenshot 2022-07-12 at 15 15 40](https://user-images.githubusercontent.com/908665/178511707-915a82f2-2746-4de3-8011-daace7cf6e7b.jpg)    |   ![Screenshot 2022-07-12 at 15 15 19](https://user-images.githubusercontent.com/908665/178511762-e7ec18a4-d89b-490a-9cc2-b98cf954d4db.jpg)    |

**Editor**
![Screenshot 2022-07-12 at 15 16 10](https://user-images.githubusercontent.com/908665/178511805-672f56b8-aa7c-45cd-ae4f-6f583f4ac7af.jpg)

### Environment info

- WordPress 6.0, Gutenberg trunk, Twenty Twenty-Two
- Chrome Mac.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
I'm unable to reproduce this on my end. 

I checked this on [this test page](https://thelmatest.mystagingwebsite.com/sample-page), with the TT2 theme. I added a cover block and it was full width both when Gutenberg it active and deactivated.

<img width="1756" alt="Untitled 2" src="https://user-images.githubusercontent.com/41231764/179234066-a63952e8-c74a-4c23-ae3e-894e4ace6c3b.png">

**Environment:**

- WP 6.0 

- Twenty Twenty Two theme 

- Chrome Mac

**Comment by iamtakashi** [comment]
Thanks, @Thelmachido I can confirm this is no longer issue at this time. It seems the issue was fixed somewhere yesterday.

**Comment by kauaicreative** [comment]
This is an issue again after the update Gutenberg 13.7.1

With Gutenberg on left, without on right.

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/127033/180227612-d13737d5-d345-452e-ab03-7b3b6a4aa414.png">
