### ISSUE TITLE
Storybook: CSS resets intended for the Block Editor Playground are leaking

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#42414]
The [CSS reset file](https://github.com/WordPress/gutenberg/blob/trunk/storybook/stories/playground/reset.scss) intended for the [Block Editor Playground story](https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default) is not sufficiently scoped, therefore leaking into all other component stories. This doesn't allow us to check if a component's styles are sufficient in isolation.

**Comment by ciampo** [comment]
😱
