### ISSUE TITLE
Show status of page

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4241]
From @ElectricFeet in testing:

> In the document tab, the first menu item is called "Status and Visibility", yet the traditional WordPress "status" is not shown. In particular, I have no way to see that my post/page is in draft, apart from noticing that it says "Publish", rather than "Update". This is not clear enough.

> Suggestion: The status should be shown, using the same interface as "Visibility" does — a drop-down with radio buttons for "Draft" and "Published". When the "Draft" radio button is clicked, the "Pending review" toggle should appear, as now.

**Comment by karmatosed** [comment]
I am closing this as we've not had any other feedback that this is wanted. There have been a number of enhancements to the publishing flow that probably are making things better here.

This all said if we do get feedback that this is required, we can reopen.

**Comment by davilera** [comment]
If we only had three statuses (_Draft_, _Pending_, and _Published_), it might make sense, as the buttons in the UI somehow let you know the status:

a) If the post is _Draft_/_Pending_:
* The main action button is _Publish_
* There's an action to _Save Draft_/_Save as Pending_

b) If the post is _Published_:
* The main action button is _Update_
* There's an action to _Switch to Draft_

Unfortunately, we have one more status: _Scheduled_. And in this particular case, the UI is extremely confusing:

c) If the post has a _Publish_ date but is not yet _Scheduled_:
* The main action button is called _Schedule..._ (with ellipsis)
* There's an action to _Save Draft_/_Save as Pending_

d) If the post is already _Scheduled_
* The main action button is called _Schedule_ (without ellipsis)
* There's an action to _Switch to Draft_

In this latter scenarios (c and d), discovering the status the post is in is complicated: one has to know all the possible combinations of this buttons to "guess" what's going on.

Can't we think of a better solution? The easiest one I can think of is including the _Current Status_ field in the _Status & Visibility_ section (or add it somewhere else, where it's prominent and clear) and probably call the _Status & Visibility_ section differently.
