### ISSUE TITLE
Categories block has incorrect name in block editor tooltip

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#42416]
When adding a categories block in the block editor, the name of the block shows "Post Terms" instead of "Categories" in the tooltip.

<img width="816" alt="Screen Shot 2022-07-14 at 11 07 58 AM" src="https://user-images.githubusercontent.com/5129775/178947239-63dd4b0e-c95c-4944-9753-1fc64180dc30.png">

**Comment by t-hamano** [comment]
I think this problem has been resolved in the latest Gutenberg. I would expect #39837 to have solved this problem.
However, we have created #44249 because we found some labels were not displayed properly.

Therefore, I would like to close this issue.
