### ISSUE TITLE
Nested usage of RichText component

### ISSUE THREAD

**Issue by sweber83** [WordPress/gutenberg#42434]
## What problem does this address?
We have a use case, where we need to render a nested instance of the RichText component inside the Edit component of a custom rich text format.
Trying to select such a nested RichText instance causes it to disappear immediately, because the selection changes to the nested instance, which causes the outer instance to stop rendering the FormatToolbar component, where the Edit components of the individual formats are rendered.
The root of the problem is, that there is always only one selection, which is kept in the block editor redux store.

## What is your proposed solution?
I propose to introduce a new prop, which tells the RichText component to keep its own state, independent of the block editor store.
Since i'm not terribly familiar with the implementation details, a different approach could be preferable.

**Comment by talldan** [comment]
@sweber83 Would you be able to expand on this, as I'm not sure what you mean by 'nested' here. Do you mean inner blocks?

Adding some pseudocode to the issue might be helpful. Thanks.

**Comment by sweber83** [comment]
I'll add an example soon.

**Comment by sweber83** [comment]
@talldan 
Finally, I found the time to implement an example, which illustrates the issue.
The example implements a custom rich text format, that opens a popover, inside which a `RichText` component is rendered.
When one clicks on the rich text field inside the popover, the component `EditCustomFormat` is unmounted immediately by the outer `RichText` component.
This happens, because the selection moves to the inner `RichText` component.

```JavaScript
import React, { useEffect, useState } from 'react';
import { RichText, RichTextToolbarButton } from '@wordpress/block-editor';
import { Popover } from '@wordpress/components';
import { registerFormatType } from '@wordpress/rich-text';

const name = 'my-namespace/custom-format';
const title = 'Custom Format';

const customFormat = {
	title,
	tagName: 'a',
	className: 'custom-format',
	edit: EditCustomFormat,
};

function EditCustomFormat( editProps ) {
	const { isActive } = editProps;
	const [ isModalOpen, setIsModalOpen ] = useState( false );
	const openModal = () => setIsModalOpen( true );

	useEffect( () => {
		console.log( 'mount EditCustomFormat' ); //eslint-disable-line no-console
		return () => console.log( 'unmount EditCustomFormat' ); //eslint-disable-line no-console
	}, [] );

	return (
		<>
			<RichTextToolbarButton
				title={ title }
				onClick={ openModal }
				isActive={ isActive }
			/>
			{ isModalOpen && (
				<Popover focusOnMount={ false }>
					<RichText placeholder="rich-text..." />
				</Popover>
			) }
		</>
	);
}

registerFormatType( name, customFormat );
```

**Comment by talldan** [comment]
Thanks for the example. If you don't need formatting for the Popover's text field, you could try another component as an alternative to RichText, like a `PlainText` (also from the block editor package).

If you do need formatting then I unfortunately don't have any solutions.

I guess that may also be a bit unusual as you'd be able to apply the custom format to the popover's RichText and continue doing so infinitely. The format would need to be disabled.

**Comment by sweber83** [comment]
@talldan 
Thanks for your help!
For now we will use a plain text input.

Maybe at some point in the future we will implement a PR, but not at this time.
