### ISSUE TITLE
[Video block] Showing the play button after inserting URL that doesn't exist

### ISSUE THREAD

**Issue by RenanLukas** [WordPress/gutenberg#42443]
## Description
When inserting a URL that doesn't exist to the video block, the play button can still be tapped (but nothing loads, since the URL doesn't exist).

## Step-by-step reproduction instructions

1 - Open a post or a page
2 - Add a video block
3 - Select the option "Insert from URL"
4 - Insert a URL that doesn't exist (e.g. `https://www.thisisnotavalidurl.com.br`) and tap "Apply"
5 - Observe the video block

## Expected behaviour

The video block shows the "ADD VIDEO" button and doesn't load anything (this happens if I insert an invalid URL, such as `"aaaaaaa"`).

## Actual behaviour

The video block shows the play button and let's us play the video, even though it never loads since the URL doesn't exist.

## Screenshots or screen recording (optional)

Uploading gutenberg_video_block.mov…

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: iPhone SE 
- Operating system: iOS 15.4
- WordPress app version: 20.3

**Comment by derekblank** [comment]
Confirmed as part of a few known issues related to displaying poster images and thumbnails within the video player. Also related:
- https://github.com/wordpress-mobile/gutenberg-mobile/issues/1152
- https://github.com/WordPress/gutenberg/issues/30987
- https://github.com/wordpress-mobile/gutenberg-mobile/issues/965
- https://github.com/wordpress-mobile/gutenberg-mobile/issues/1493
- https://github.com/WordPress/gutenberg/issues/42515

**Comment by derekblank** [comment]
This issue is resolved via #49858.
