### ISSUE TITLE
It's possible to create template parts with duplicate names

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#42473]
### Description

When creating a template part, either manually or via one of the automatic flows like inserting a header pattern, it's possible for duplicate names to be used. 

### Step-by-step reproduction instructions

1. Create a template part and give it a name
2. Create another template part and give it the same name

### Screenshots, screen recording, code snippet

<img width="1070" alt="Screenshot 2022-07-15 at 15 01 20" src="https://user-images.githubusercontent.com/846565/179240966-a0d0f011-7285-4a1a-a1b0-097fb2b7cdd9.png">

**Comment by jameskoster** [comment]
When creating manually, there should probably be some validation on the name input which prohibits the creation of template parts with duplicate names.

In the automatic flows, we might consider appending `-1` to the end of the new template part name.

cc @WordPress/gutenberg-design

**Comment by paaljoachim** [comment]
Adding a 1 or 2 etc at the end of the template part name would be similar to creating a folder etc on the computer and is something we are just used to seeing. Here is an example of creating two folders with the same name on OSX.

![Screenshot 2022-07-16 at 11 12 19](https://user-images.githubusercontent.com/5323259/179348629-fcd4aa41-41d4-4ec4-9937-602f801748e6.jpg)

So we could do the same thing as seen on OSX.

**Comment by apeatling** [comment]
Confirmed this is still the case in trunk:

<img width="555" alt="Screenshot 2023-01-09 at 12 11 45 PM" src="https://user-images.githubusercontent.com/1464705/211399038-902effb5-dfae-4edb-8006-bce93abe0a2d.png">

I'll work on a PR that will add an iterating trailing number to duplicate template part names.
