### ISSUE TITLE
Chrome: Publish sidebar toggle state persists between page loads

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#4248]
## Issue Overview

If the Publish menu is opened, it will remain open in subsequent editor sessions.

## Steps to Reproduce

1. Navigate to Posts > Add New
2. Enter a title
3. Press Publish in the editor header
4. Navigate to Posts > Add New
   - Ignore the prompt about unsaved changes and continue navigation

## Expected Behavior

In the new editor session, the Publish sidebar is not visible.

## Current Behavior

The Publish sidebar is visible, including after subsequent refreshes.

## Possible Solution

Sidebar toggle state is [managed in preferences state](https://github.com/WordPress/gutenberg/blob/38b60d6ec3c902bd552592d0b61cee0179bd92c2/editor/store/reducer.js#L495-L570) which is persisted between editor loads. Is this meant to be a preference? And if so, do we need to implement some behavior for the preferences reducer to allow specific values to be persisted vs. others? Maybe [as with the `REDUX_REHYDRATE` action](https://github.com/WordPress/gutenberg/blob/38b60d6ec3c902bd552592d0b61cee0179bd92c2/editor/store/persist.js#L32-L66), we need a complementing persist action which allows the reducer to define which values should be included in that state?

**Comment by noisysocks** [comment]
cc. @youknowriad who worked on this in https://github.com/WordPress/gutenberg/pull/4119.

Looking at [the Layout class](https://github.com/WordPress/gutenberg/blob/master/editor/edit-post/layout/index.js#L38), it looks like we could avoid using Redux altogether in lieu of a simple `setState()`.

**Comment by youknowriad** [comment]
I think there's still value in using Redux to handle the sidebars state similarily between the different sidebars (default sidebar, publish sidebar, plugins sidebar to come). We need to know if there's an open sidebar to apply the styling and we need the default sidebar in state (used in several components and persisted)
