### ISSUE TITLE
Site Editor Inserter(s): Prioritise Template Parts over Patterns, and indicate the difference between the two

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#42501]
The quick inserter currently surfaces patterns, both by default and when you search:

<img width="429" alt="Screenshot 2022-07-18 at 12 00 00" src="https://user-images.githubusercontent.com/846565/179497745-37caad28-2b09-4833-bf33-8875d8ad15ed.png">

But it's not always clear whether the options (like in the screenshot above) are template parts or patterns, which can lead to folks mistakenly inserting a pattern where a template part would be preferable.

This issue can be partially fixed by https://github.com/WordPress/gutenberg/issues/41397, but it might be best to establish some visual distinction to cover cases where patterns and template parts share a name. There are a couple ways to do this, one solution would be to simply list them separately:

<img width="446" alt="Screenshot 2022-07-18 at 12 41 15" src="https://user-images.githubusercontent.com/846565/179503831-5f037f20-dd96-421a-89e5-1bab55ac2ced.png">

This would be similar to what you find in the current implementation of the template part replacement modal:

<img width="932" alt="Screenshot 2022-07-18 at 12 05 55" src="https://user-images.githubusercontent.com/846565/179498632-6043c79c-6fd5-4530-975d-55443e847ea7.png">

Another option would be to list them together but use the template part icon to distinguish between patterns and things like headers / footers. Rough example:

<img width="474" alt="Screenshot 2022-07-18 at 12 39 38" src="https://user-images.githubusercontent.com/846565/179503632-f20eb73e-7736-4968-8c98-660c081630c2.png">

**Comment by DaisyOlsen** [comment]
I can see merit in both the icon indicators and the separate sections. I'd lean toward separation because template parts and patterns are functionally different so a more obvious separation might be helpful. I also think that, in most cases, parts would be used more frequently in the site editor than patterns.

**Comment by carolinan** [comment]
I would prefer the icon because I feel a bit overwhelmed by the size of the inserter in the example.

**Comment by jameskoster** [comment]
I don't have a strong opinion, but do lean slightly towards the separation approach purely because it is consistent with other UIs that present the same content. We can explore how we might improve the experience holistically as a dedicated effort, rather than having several of different versions of essentially the same thing across the editor.

**Comment by mtias** [comment]
Where did we end up with this?

**Comment by jameskoster** [comment]
Seems we're looking for consensus on how to present everything. These are the options we have atm:

<img width="1052" alt="Screenshot 2022-09-12 at 10 10 13" src="https://user-images.githubusercontent.com/846565/189616200-3e2b2c64-04f8-4452-8bf8-4e21cdee60eb.png">

Now that I think of it, another option would be: Clicking the root-level inserter engages the zoomed-out view with the main Inserter panel open. The separation of template parts / patterns is handled therein.

**Comment by jordesign** [comment]
I'm not seeing the pattern/part preview within the quick inserter any more - is this issue still relevant @jameskoster

**Comment by jameskoster** [comment]
It's still there, but only at the document root by the looks of things:

<img width="446" alt="Screenshot 2023-09-05 at 10 02 40" src="https://github.com/WordPress/gutenberg/assets/846565/eda093a4-e1a6-465c-ab3b-ed9d540dc304">

> Seems we're looking for consensus on how to present everything.

The Pattern management view didn't exist when we last looked at this, and I think it sets a precedent that can inform the direction here:

<img width="1065" alt="Screenshot 2023-09-05 at 10 05 28" src="https://github.com/WordPress/gutenberg/assets/846565/78458830-bb8c-419b-b80c-59469eab10ec">

It uses the icon approach above to communicate the synced nature of a given pattern. This is probably adequate on its own (no need to re-order). I'll update the OP. 

Edit: It seems that when the quick inserter is set to display patterns it will only return unsynced ones (IE no template parts), even when you search. So _this_ issue doesn't really exist any more, but the quick inserter should be updated to include synced patterns. I'll open a new issue for that one.
