### ISSUE TITLE
Update Gutenberg plugin release documentation

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#42516]
Current documentation: https://developer.wordpress.org/block-editor/contributors/code/release/

Gaps discovered during Gutenberg 13.7 release in collaboration with @priethor 

- [x] add: How to map label changes for the changelog creator script
- [x] add: designer rotation: connect to design team to request assets for the release post. (_share draft release post with the highlighted items.)_
- [x] Q A on curating the Changelog 
- [x] Add a checklist for stable release. (announcement in #core-editor channel, cherry-pick, testing etc)
- [x] [cherry-pick section](https://developer.wordpress.org/block-editor/contributors/code/release/#creating-release-candidate-patches-done-via-git-cherry-pick) could use some visuals
- [x] re stable release: replace "Once the stable version is released, the release post is published, including a [performance audit](https://developer.wordpress.org/block-editor/block-editor/contributors/testing-overview/#performance-testing)." with "The performance audit runs automatically, but the numbers need to be pulled and included in the release post.
In case the GitHub Action fails, the performance audit needs to be run manually."
Add a link to the Performance audit section. - _[also see screenshots below](https://github.com/WordPress/gutenberg/issues/42516#issuecomment-1189596230)_
- [x] Add a note about using the label [`Backport to Gutenberg RC`](https://github.com/WordPress/gutenberg/labels/Backport%20to%20Gutenberg%20RC) for PRs, that were merged after RC 1 but before stable. They need to be cherry-picked before the release. 
- [x] [Update Performance test section](https://developer.wordpress.org/block-editor/contributors/code/release/#4-running-the-performance-tests)
Time to the first block = first block
KeyPress Event (typing) = type
Add something like this  "All metrics should be picked from the same job that calculates the latest metrics. Otherwise, it might be biased by the type/load/performance on the servers used in the past. In general, you compare using the same machine to run all tests."

**Comment by bph** [comment]
- [ ] replace "Once the stable version is released, the release post is published, including a [performance audit](https://developer.wordpress.org/block-editor/block-editor/contributors/testing-overview/#performance-testing)." with "The performance audit runs automatically, but the numbers need to be pulled and included in the release post."
In case the GitHub Action fails, the performance audit needs to be run manually. 
Add a link to the Performance audit section.

**Comment by bph** [comment]
When releasing the stable version, a special GitHub action is executed running the performance suite for this GB version, the previous one, and the current WP version. 

The performance audit rund approximately 50 minutes

Use rows `firstBlock` and `type` from the results. 

**- Time to the first block = firstBlock
- KeyPress Event (typing) = type**

Performance audit results example: 
([13.6](https://github.com/WordPress/gutenberg/runs/7218184433?check_suite_focus=true#step:6:131))
**Post Editor**
![Screen Shot 2022-07-19 at 18 03 24](https://user-images.githubusercontent.com/39980/179856354-0c3e25de-4438-4e11-a1c2-4449ab5875bc.png)
![Screen Shot 2022-07-19 at 18 07 36](https://user-images.githubusercontent.com/39980/179856917-30fc71c7-85e2-48e9-a522-0b6328ef9bd4.png)


Table in the [release post:](https://make.wordpress.org/core/2022/07/07/whats-new-in-gutenberg-13-6-6-july/) 
![Screen Shot 2022-07-19 at 18 06 00](https://user-images.githubusercontent.com/39980/179856565-f7d88a3f-081a-4c8b-b700-c2e9eb01fb3a.png)

![Screen Shot 2022-07-19 at 18 13 43](https://user-images.githubusercontent.com/39980/179857534-4019e8ac-feb2-460f-9d8c-dc17597e37b5.png)

**Comment by bph** [comment]
⭐️ @Mamaduka updated the Performance test section via https://github.com/WordPress/gutenberg/pull/43015 👏

**Comment by bph** [comment]
I also wrote how to [run Performance test](https://icodeforapurpose.com/gutenberg-release-how-to-run-plugin-performance-test-locally/) for the release locally.

I don't know how this would fit into the documentation, though

**Comment by ryanwelcher** [comment]
@bph is this issue still relevant now that we have the issue template for GB releases in place?

**Comment by bph** [comment]
Good point, @ryanwelcher! Certain aspects of it are indeed relevant. I'll update it [after the 15.7 release](https://github.com/WordPress/gutenberg/issues/50092) cycle.

**Comment by bph** [comment]
Performance test were removed from the release workflow and documentation. https://github.com/WordPress/gutenberg/pull/50345

**Comment by bph** [comment]
The Gutenberg Release documentation has been updated by @ndiego a while ago.
