### ISSUE TITLE
FormTokenField: Suggestion is expanded on load when `__experimentalExpandOnFocus` is set to `true`

### ISSUE THREAD

**Issue by dinhtungdu** [WordPress/gutenberg#42528]
### Description

If `__experimentalExpandOnFocus` is set for `<FormTokenField>` component, the suggestion list is expanded after page load without any user interaction.

### Step-by-step reproduction instructions

1. Add the following story to `packages/components/src/form-token-field/stories/index.tsx`:
```
export const ExpandOnFocus: ComponentStory< typeof FormTokenField > =
	DefaultTemplate.bind( {} );
ExpandOnFocus.args = {
	...Default.args,
	__experimentalExpandOnFocus: true,
};
```
2. See suggestion list is expanded without focusing on the token input field.

Note: The `DropdownSelector` story in #42527 can be used for testing this issue.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/5423135/179731002-271d00c5-e27d-4e31-9270-09597e16dd3a.mov

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mirka** [comment]
Confirmed, the bug is [here](https://github.com/WordPress/gutenberg/blob/ca9ece20cd7a4c954845034f18a505a10e745025/packages/components/src/form-token-field/index.tsx#L529-L530).

**Comment by dinhtungdu** [comment]
> Confirmed, the bug is [here](https://github.com/WordPress/gutenberg/blob/ca9ece20cd7a4c954845034f18a505a10e745025/packages/components/src/form-token-field/index.tsx#L529-L530).

@mirka Tracing the history, I found that this issue is a regression introduced in https://github.com/WordPress/gutenberg/pull/41216.

**Comment by hbhalodia** [comment]
Hi @mirka, checked current story book, the issue is not reproducible yet. See here.


[expandOnFocus.webm](https://user-images.githubusercontent.com/58802366/219555503-3cf2c951-722f-4202-ab10-06bd4e2d6dbe.webm)

**Comment by mirka** [comment]
Great, thank you for looking into it!
