### ISSUE TITLE
New Block: Time to Read

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#42542]
A  **Time to Read** block would allow for site owners and theme builders to display the estimated time to read of the particular post or page to the frontend on single post templates or from within query loops in Archive templates. 

Maybe the [existing information form the table of contents panel](https://github.com/WordPress/gutenberg/pull/41611) can be stored into post meta key/value on save/publish action. 
![Screen Shot 2022-07-14 at 18 54 08](https://user-images.githubusercontent.com/39980/179854954-4c5d8309-8cf7-41e5-be41-43ba42b8fdf8.png)

And then the **Time To Read** block displays the value, similar to the Post date or the post author.

**Comment by mtias** [comment]
Let's do it!

**Comment by t-hamano** [comment]
If this block is expected by many, can I try to develop?
Technically, I believe this can be accomplished with a basic dynamic block implementation like [Post Author Name block](https://github.com/WordPress/gutenberg/pull/36001/files#diff-55c58e4b84af8878c1e4c4870117cdd59990fe3e2c89725a290550c9c4c3e0cb) 
If you see any potential problems in developing it, please advise me.🙂

**Comment by mtias** [comment]
That'd be great, feel free to start a branch and submit a proposal!

**Comment by t-hamano** [comment]
Thank you!
Once the prototype is ready, I'd like to submit a PR as a proposal.

**Comment by t-hamano** [comment]
I am working on developing a block and have hit a major problem.
The Time To Read shown in the table of contents panel is a very complex process to calculate the time by `count` function from [@wordpress/wordcount](https://github.com/WordPress/gutenberg/blob/trunk/packages/wordcount/src/index.js).

I think this block should be a dynamic block, so to match the numbers on this panel exactly, the same logic processing would need to be implemented in PHP.

Does anyone have any good ideas on this point?

**Comment by bph** [comment]
@t-hamano It would be great if you could take on this new block.
I could see it to be a dynamic block, too, reading the value from  post meta.  
The Time-to-read information is calculated in the [time-to-read component](
https://github.com/WordPress/gutenberg/blob/bc071fcc0d802e06e92e309154093a2adc2cc65a/packages/editor/src/components/time-to-read/index.js)
Your block should be able to use the "minutesToReadString" and store in the post_meta table of the database before it's used for display? 

Maybe this helps to get started?

**Comment by t-hamano** [comment]
@bph 

Thanks for the advice!
Using the minutes calculated in the @wordpress/wordcount component in attributes would be a great way to match the calculated values with the info panel and block, or it would be very simple to implement.and block.

But, as was [the concern with the ToC block](https://github.com/WordPress/gutenberg/pull/29739), it cannot calculate dynamic time at render time. In other words, it would not work in the site editor (i.e., post templates such as single.html), but only in the post editor.

If we can accept this disadvantage, I would like to restart development 🙂

**Comment by phil-sola** [comment]
I came here today checking to see if this had already been requested or not. 

Such a simple block, and very easy to implement I would imagine given the time to read component linked to above by @bph 

+1 for this block!

**Comment by masteradhoc** [comment]
@t-hamano thanks for your work! Hope this gets added soon!
