### ISSUE TITLE
Can't add description to ToolsPanel as per readme example

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#42543]
### Description

When adding a description inside the ToolsPanel component, using the syntax provided in the [component readme example](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/tools-panel/tools-panel/README.md#usage), the layout appears broken:

<img width="277" alt="Screen Shot 2022-07-20 at 11 54 31 am" src="https://user-images.githubusercontent.com/8096000/179878921-40ec823c-32c5-4da3-a87e-c5b77583fc60.png">

`ToolsPanel` is defining a 2 col grid style, with `ToolsPanelItem`s styled to span both columns, but any other element inserted in the `ToolsPanel` will automatically be assigned to a single column. I came across this while working on #42309, in which I'm also using a `Flex` component to wrap a couple of `ToolsPanelItem`s so they stay on the same line. That works as long as `Flex` is the only child of `ToolsPanel`; once I add the paragraph the layout breaks as shown above. But it still looks broken even if the other children span both cols:

<img width="275" alt="Screen Shot 2022-07-20 at 11 47 35 am" src="https://user-images.githubusercontent.com/8096000/179878224-d2751e3c-de0b-43e7-8e8b-c0c6421e16d3.png">

Ideally, the `ToolsPanel` should provide a way to render a semantic description for the controls. Could we perhaps leverage `fieldset` and `legend` here?

But the styling issue should also be looked into: do we really need it to be a grid if its contents always span both columns?

### Step-by-step reproduction instructions

1. Add a paragraph directly inside a `ToolsPanel` component with one or more `ToolsPanelItem`s.
2. Verify that layout appears broken.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aaronrobertshaw** [comment]
I believe the readme issue was addressed in https://github.com/WordPress/gutenberg/pull/42615, so closing this. 

The two-column grid was desired to allow layouts such as that in the typography panel as the most common case. The ToolsPanel design is being revisited so any changes to the default layout would be wrapped up in that if needed.
