### ISSUE TITLE
Remove block placeholder in favour of list of Pages as fallback state

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#42563]
We are [aiming to normalise the behaviour of the Navigation block across both the Editor and the front of the site](https://github.com/WordPress/gutenberg/issues/38291#issuecomment-1171582948).

Many Themes utilise the Page List block (as an inner block) as a _fallback_ experience to ensure the user sees some content if a `wp_navigation` is not assigned to the block.

In https://github.com/WordPress/gutenberg/pull/42182 however, we are updating the block to always respect and render inner blocks if they are provided by the block.

This means that [any Themes that include the Page List block as part of their default Nav block](https://github.com/WordPress/twentytwentytwo/blob/27054dbcb95f5d72cd943a0f3318c3ad97599f85/parts/header.html#L9-L11) within their template parts will cause the page list block to be rendered over all other possible content (e.g. `wp_navigation` posts .etc).

Most Themes will likely want to remove the inner blocks because it will mean they are unable to take advantage of future work to enable _automatic_ selection of menus (based on various heuristics).

As a result we need to update the block to ensure it provides appropriate fallback content. The front of the site already does this by rendering a list of pages. We now need to update the editor implementation to mirror this. 

Therefore instead of rendering a placeholder as a default _fallback_, the block should instead render a Page List block.

As part of this effort we should also tackle https://github.com/WordPress/gutenberg/issues/42602 as this will help avoid cluttering the UI.

**Comment by draganescu** [comment]
I have mistakenly rebased https://github.com/WordPress/gutenberg/pull/42735 on trunk and getting it back is a pain. If eventually that goes in I'll figure out the authors thing as the PR is branched from this one originally.
