### ISSUE TITLE
PluginSidebar is not working in FSE environment 

### ISSUE THREAD

**Issue by wpsoul** [WordPress/gutenberg#42560]
### Description

I believe that [Sidebar plugin](https://developer.wordpress.org/block-editor/reference-guides/slotfills/plugin-sidebar/) should work on all Gutenberg pages, but currently it's working only on post types. 

In the same time, I didn't find any documentation how to add plugins to FSE pages. 

### Step-by-step reproduction instructions

1. Use [Sidebar plugin](https://developer.wordpress.org/block-editor/reference-guides/slotfills/plugin-sidebar/) in plugin or theme
2. Open Appearance - Site editor
3. There are no new plugins or icons in the top toolbar

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
If used on full site editing, `PluginSidebar` must be imported from another package.

```javascript
import { PluginSidebar } from '@wordpress/edit-post';
// to...
import { PluginSidebar } from '@wordpress/edit-site';
```

#34460 is the PR for this.

However, it isn't mentioned in the documentation and may be worth improving:
https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/slotfills/plugin-sidebar.md#example

This is also true for other plugin support documentation.

**Comment by wpsoul** [comment]
> If used on full site editing, `PluginSidebar` must be imported from another package.
> 
> ```js
> import { PluginSidebar } from '@wordpress/edit-post';
> // to...
> import { PluginSidebar } from '@wordpress/edit-site';
> ```

Unfortunately, it's not working for me. console.log shows me PluginSidebar in wp.editSite, but when I import it, it's undefined. Also, it's still not allowing me to modify iframe elements because script is posted outside iframe and there is no hook to add it in iframe of FSE.

**Comment by t-hamano** [comment]
> but when I import it, it's undefined.

Did you add `wp-edit-site` as a dependency?
It worked correctly in my environment.

> it's still not allowing me to modify iframe elements because script is posted outside iframe and there is no hook to add it in iframe of FSE.

As this is a separate issue from this issue, please refer to the following issue.

- #38673
- #41065

**Comment by wpsoul** [comment]
> Did you add `wp-edit-site` as a dependency?

You are a hero. Yes, now, it's working correctly. 

It's bad that question from February about scripts in iframe was not resolved.

**Comment by t-hamano** [comment]
I am glad to hear that the problem has been resolved.

> It's bad that question from February about scripts in iframe was not resolved.

Each contributor may have a huge task at hand and may not be able to respond immediately.
However, additional discussion and PR are welcome.
