### ISSUE TITLE
Blocks that have `supports.className` set to false still render block class name in editor

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#42566]
### Description

Gutenberg has supported opting out of the auto-generated block name class name by setting the `supports.className` option to false. This is the mechanism core uses to not add the `wp-block-heading` or `wp-block-list` class names. 

It also is very useful when you are doing very custom things with your markup and want to be in control over the class names.

I recently noticed that the editor does not match the saved markup in this instance. Even with the `supports.className` option set to false the block still gets the class generated in the editor state. This leads to an inconsistency between the editor markup and saved markup.

### Step-by-step reproduction instructions

- Go to the editor
- Insert a Heading block
- Open the browser inspector and inspect the heading block
- notice that the block has the `wp-block-heading` classname
- save the post 
- view it on the frontend 
- inspect the heading
- notice that the classname is not there

Ideally, it should also not be there in the editor.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by michaelmcandrew** [comment]
Not sure that this is a bug as the API doesn't make any promises about markup in the editor - just when it is saved, see https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#classname states 

> By default, the class .wp-block-your-block-name is added to the root element of your **saved markup**. This helps having a consistent mechanism for styling blocks that themes and plugins can rely on. If, for whatever reason, a class is not desired on the markup, this functionality can be disabled.

(and of course there are plenty of other classes that don't make it into the saved markup.

What specifically are you trying to achieve here? Might be that there is another approach to consider.
