### ISSUE TITLE
Weird transition effect when browsing the patterns carousel

### ISSUE THREAD

**Issue by dsas** [WordPress/gutenberg#42593]
### Description

When using the Query Loop block and scrolling through the available patterns, there is a weird glitch when moving between patterns. This is most pronounced when scrolling backwards. When navigating backwards from current pattern n, it temporarily shows n+1 before correctly going to n-1.

This also happens on other blocks using the pattern selector, it's probably not a Query Loop specific thing.

### Step-by-step reproduction instructions

1. Add Query Loop block
2. Press Choose to launch the pattern selector
3. Use the buttons to scroll forwards through the patterns
4. Use the buttons to scroll backwards

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/93301/180195041-c1277c4e-2e24-4f14-b7c3-ff139bd66ac3.mp4

### Environment info

WordPress 5.9.1 and WordPress 6.0.1 using today's Gutenberg trunk with the default theme on Firefox desktop (OSX)

While working on https://github.com/Automattic/jetpack/pull/24914 I have also encountered the same issue in Chrome desktop (OSX) while using Gutenberg v13.6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I'm not seeing the pattern carousel in use any more (Query Loop only offers the thumbnail view) so closing this issue as no longer reproducible.
