### ISSUE TITLE
Automatically utilise classic menu when switching from classic Theme

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#42600]
## What problem does this address?

When switching from a Classic Theme (with a Menu assigned to a Menu Location) to a Block Theme with a Navigation block, the block is currently empty.

This provides a suboptimal UX and could be improved.

## What is your proposed solution?

On theme switch, the block should:

1. Attempt to find the classic Menu that was assigned to the `primary` Menu Location.
2. Convert the Menu into a block Navigation Post `wp_navigation`.
3. Automatically use the new Navigation Post in the block.

This should happen without user interaction and s**hould work in the same way** across both the Editor and the front of the site.

Note however, that this should be considered part of the auto-assignment mechanic. Therefore, if the block detects that a `wp_navigation` already exists in the database, it should prefer that over converting the classic menu. This is however, likely to be an edge case.

**Comment by getdave** [comment]
Related https://github.com/WordPress/gutenberg/issues/42601

**Comment by annezazu** [comment]
Noting that this current experience came up as a pain point a few times in the [seventeenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/09/15/fse-program-testing-call-17-guiding-the-gutenberg-gallery/): 

>I noticed that when I switched from Twenty Twenty One to Twenty Twenty Two the navigation changed and lost the previous menu. That’s unexpected and not great. I also noticed that the menu turned into a page list block. I guess this is the “most likely fallback” mentioned earlier in the call for testing description?

>Click to make sure an individual link is selected. Then an Edit link is seen in the toolbar. Converting links. Ahh it converts all the links at the same time. Clicking into the various links I do not see the edit link any longer. I found this process a little confusing. Why do I need to convert links in the menu?

>I feel like novice users likely don’t know the implication of what will change with their theme. They might assume that the colors/styles may change, but not necessarily structural changes (like having to re-do the menu).

I've added it as part of the theme switching flows tracking issue as this latest call for testing showed how impactful it would be to resolve. 

P.S. it's not clear to me necessarily how this relates to this recent merged PR: https://github.com/WordPress/gutenberg/pull/44173 It seems like issue is likely broader in scope than that specific use case.

**Comment by getdave** [comment]
@annezazu I believe https://github.com/WordPress/gutenberg/pull/44173 does partly solve this issue as it will import the most _recent_ classic menu if no block-based menus exist.

It does not import based on `primary` though so that's something to look out for. 

In the future we might make it import from `primary` or explore other heuristics to try to ensure the "correct" menu is utilised in the block.

**Comment by strarsis** [comment]
@getdave: Is it possible to make a Gutenberg navigation menu the primary menu, or have slots, similar to what Block part areas do? Currently when I use a block part for the site header I have to manually select the primary menu for the first time, otherwise it shows the last menu that was added.

Currently a `core/navigation-menu` block would use an ID to reference to a specific Gutenberg menu:
````
<!-- wp:navigation {"ref":87
````

This would be much more robust and avoid the need to set the proper primary menu after a block part reset or initial setup:
````
<!-- wp:navigation {"ref":"primary or menu area slug or some other mechanism"
````

Related issue comment: https://github.com/WordPress/gutenberg/issues/38166#issuecomment-1020730015

Edit: Apparently these kinds of "navigation areas" were deprecated: https://github.com/WordPress/gutenberg/issues/36524#issuecomment-1005514171

**Comment by getdave** [comment]
@strarsis Absolutely. [Your request is already on the roadmap for 6.2](https://github.com/WordPress/gutenberg/issues/45512) 🤞

**Comment by getdave** [comment]
The auto import of a Classic Theme has been implemented. Closing.
