### ISSUE TITLE
Patterns carousel displays stacked patterns in some themes

### ISSUE THREAD

**Issue by dsas** [WordPress/gutenberg#42608]
### Description

When using the Pattern chooser carousel it displays all of the patterns on top of each other when using certain themes which looks like a mess. It happens in:
 * Twenty Twenty
 * Twenty Nineteen
 * Twenty Sixteen
 * [Skatepark](https://en-gb.wordpress.org/themes/skatepark/)

It doesn't happen on:
 * Twenty Twenty Two
 * Twenty Twenty One

I filed https://github.com/WordPress/gutenberg/issues/42593 earlier today, I think these are separate issues but perhaps they're related.

### Step-by-step reproduction instructions

1. Activate Twenty Twenty (or 2019, 2016 etc) theme
2. Open Gutenberg
3. Add a query block
4. Use 'Choose' to open the selector
5. Ensure you're in the Carousel view
6. Notice the preview looks messy

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/93301/180272303-6512a9cc-6096-48a5-80cd-a9388af91272.png)

Left is when the 2019 theme is activated, right is the 2022 theme.

### Environment info

WordPress WordPress 6.0.1 using today's Gutenberg trunk with the default theme on Firefox desktop (OSX)

While working on https://github.com/Automattic/jetpack/pull/24914 I have also encountered the same issue in Chrome desktop (OSX) while using Gutenberg v13.6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mmtr** [comment]
I think we can close this one out, since the issue was specific to the environment where we were testing this (see https://github.com/Automattic/jetpack/pull/24914#issuecomment-1199067545).
