### ISSUE TITLE
Move block Menu selection and "Start Empty" actions to inspector controls

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#42602]
## What problem does this address?

When displayed on the editor canvas, the goal should be that the Navigation block should - as far as is possible - remain 1:1 with what is displayed on the front of the site.

[An effort is underway to improve the fallback states for the block ](https://github.com/WordPress/gutenberg/issues/42563)so that they mirror what is displayed on the front of the site and require no user interaction to "just work".

## What is your proposed solution?

Therefore to reduce UI clutter and noise we should move secondary block actions for `Select Menu` and `Start empty` to the inspector controls.

This will allow the block fallback states to remain 1:1 with the front of the site whilst also still affording the ability to take actions to force the block to a specific state if required.

Note that this effort is important because [when displaying a list of Pages as a fallback](https://github.com/WordPress/gutenberg/issues/42563), it would be difficult to show the block actions alongside the Page List block in the canvas.

**Comment by getdave** [comment]
@javierarce Would it be possible to look into the design of this?

**Comment by javierarce** [comment]
A bit of a tangential question related to #42563 and this issue: what would happen if a user with no pages and no other menus adds a navigation block? Should we render an empty navigation with an inserter or do we fall back to a placeholder state?

**Comment by javierarce** [comment]
Here are a couple of ideas:

The first one uses a custom dropdown that includes the list of menus and an option to create an empty new one.

![image](https://user-images.githubusercontent.com/4933/183404928-c30563a8-b15a-4f38-896e-f5119d3e77fc.png)

The second idea is to present a regular dropdown and show the option to create menus directly on the sidebar along with the link to manage the menus.

![image](https://user-images.githubusercontent.com/4933/183405084-8c512bea-04d6-4466-9e54-cbdc414e9241.png)

**Comment by getdave** [comment]
Thank you for this design @javierarce  🙇‍♂️ 🙇‍♂️ 🙇‍♂️ 

> The first one uses a custom dropdown that includes the list of menus and an option to create an empty new one.

This has a least visual "noise". The create empty action is likely a 20% use case and so probably doesn't need to be visible at all times.

**Comment by draganescu** [comment]
I am picking up this one. I erroneously based https://github.com/WordPress/gutenberg/pull/42987 on different designs but now I'm on the right track :D

**Comment by scruffian** [comment]
This was closed by  https://github.com/WordPress/gutenberg/pull/42987
