### ISSUE TITLE
Provide means to delete classic menus from within a Block Theme

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#42601]
## What problem does this address?

Currently when you are using a Block Theme there is no way to remove an existing Classic Menu. Whilst this might seem like an edge case, it is surprisingly common.

For example, notice how when you have a Classic Menu it will remain in the block's `Select Menu` dropdown even after you have selected it to be converted into a block menu. Whilst this is intentional, it can be unintuitive. Moreover, once you've decided to commit to using your Block Theme you probably don't want to have you Classic Menus lying around forever more.

## What is your proposed solution?

We should provide a means to remove the Classic Menu without having to 

- switch back to a Classic Theme
- manipulate the database directly, use WPCLI...etc

One idea might be to utilise the Navigation Sidebar. The functionality could/should be afforded a lower priority in the UI, but it should be possible to select from a list of Classic Menus and delete them.

@javierarce Might you be able to consider a visual exploration of how this might work?

**Comment by getdave** [comment]
I don't see this as something we should look at. Once https://github.com/WordPress/gutenberg/issues/43856 is resolved then much of the confusion here is removed. 

If folks want to remove Classic Menus, switching back to a Classic Theme and deleting is a good option. Adding UI into the block editor to manage Classic Menus seems like a step backward.

Closing for now but open to folks disagreeing.

**Comment by Marc-pi** [comment]
@getdave 
yep, i hesitate to switch back to classic theme just to clean my classic menus
what about the custom block theme css ? kept ?
