### ISSUE TITLE
A better clarity to adding menu links to the Nav block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#42626]
## What problem does this address?

If one compares the Appearance -> Menus to the Navigation block.

The biggest difference as I see it is the Add menu items section.
![Screenshot 2022-07-22 at 12 31 30](https://user-images.githubusercontent.com/5323259/180421074-19fde26d-e104-4594-aacd-c16ebd3b6fab.jpg)

Comparing "Add menu items" to the one we see in the Nav block.

The Nav block has this to add links.
![Screenshot 2022-07-22 at 12 32 42](https://user-images.githubusercontent.com/5323259/180421328-2c701359-8226-4447-a7d1-ce9b8939118d.jpg)

Adding links in the Nav block.
- I assume the most recently 3 posts/pages are seen. One can not scroll to look at additional Posts/Pages/Categories etc.
- No logical way to add only pages, posts or categories.
- Adds additional information such as Open in new tab and Transform which I do not need at this stage where I am just wanting to add various pages/post or categories. 

## What is your proposed solution?
(A rough sketch) Nav settings should show options based on context. Change depending on the stage one is at.
Clicking Add link or the + icon seen inside a black square could instead open the Block sidebar (if closed) showing something like this:

![Add menu items sidebar option](https://user-images.githubusercontent.com/5323259/180426452-c483bc36-4ad6-45d5-8042-076dc7fb243f.jpg)

![Add menu items sidebar option open](https://user-images.githubusercontent.com/5323259/180426511-aa59f01c-6601-433b-adc3-555b943f0062.jpg)

Here is a video I made.
https://youtu.be/6ViGzqkMNC8

@getdave @javierarce

**Comment by getdave** [comment]
@paaljoachim I know that @javierarce has been thinking about this so I'll allow him to respond here.

I've added to [the Tracking Issue](https://github.com/WordPress/gutenberg/issues/38275).

**Comment by javierarce** [comment]
Yes, I've been exploring several ideas to add content to navigation menus, with the goal to add the missing bulk insertion feature ([original issue](https://github.com/WordPress/gutenberg/issues/31667)).

My first impulse was to offer this functionality through a modal (here are [a couple of prototypes](https://www.figma.com/proto/mlOogoixVzCoGc4O5Qos1j?page-id=662%3A19842&node-id=662%3A19842&scaling=min-zoom&starting-point-node-id=692%3A13696&show-proto-sidebar=1) and here's [a design breakdown with some notes](https://www.figma.com/file/mlOogoixVzCoGc4O5Qos1j/Navigation-block-improvements?node-id=662%3A19842)), but after sharing my designs and seeing the work of @SaxonF [here](https://github.com/WordPress/gutenberg/issues/42257) I thought of exploring a different avenue and follow his lead.

Similar to what you proposed, @paaljoachim, we could use a popover to add content. The main difference is that my version uses a modified LinkControl component with a filtering functionality inside the search bar.

![image](https://user-images.githubusercontent.com/4933/180787594-5cc8edc1-b1ee-4add-888c-4da51fd32fcf.png)

![image](https://user-images.githubusercontent.com/4933/180788085-aa042c50-96b7-4602-b11d-311307fb8ca1.png)

The other important distinction (which comes directly from @SaxonF's proposal), is the inclusion of the navigation menu in the sidebar, making it very easy to modify the navigation or switch to a different menu. 

![image](https://user-images.githubusercontent.com/4933/180832824-a10ab0ec-aadd-4d5a-bc3d-f0e03d3bfdf6.png)

These designs are still WIP, and I'm working on them [here](https://www.figma.com/file/mlOogoixVzCoGc4O5Qos1j/Navigation-block-improvements?node-id=784%3A20783).

PS: Would it make sense to move this conversation over to https://github.com/WordPress/gutenberg/issues/42257? The goal and ideas of this one seem to be very aligned with the other.

**Comment by paaljoachim** [comment]
I have in the back of my mind the Appearance -> Menus.
Having the popover one can scroll through to see all of the pages/posts/categories/etc will be very helpful.
Also having the navigation in the sidebar will also be of help.

It is totally fine to move for instance your comment @javierarce  directly to #42257 and close this issue, and just mention this issue. Btw the video I also mentioned having contextual sidebar settings based on where one is in the flow of things.
