### ISSUE TITLE
Table of Contents: generate links with just the anchor instead of the full address

### ISSUE THREAD

**Issue by ricjcs** [WordPress/gutenberg#42636]
When creating a Table of Contents, the links have the full address. Example: website.com/post-title/#anchor

Wouldn't it be better if the link was only with "#anchor", as is usually done manually, since it's enough to work and the rest is unnecessary? Is it not technically possible?

The full address causes problems. If the URL is changed in the editor, the link is generated. But if it is changed in the dashboard's list of articles, it will cause problems, even if the old address redirects to the new one, there will be a small jump. And if the permalinks are changed, the links in the table of contents will not work. Also, the full address doesn't work in preview mode, before the post is published. The link with only the anchor solved all these problems.

**Comment by t-hamano** [comment]
Hi @ricjcs,
I think these two comments are helpful in explaining why the TOC block holds absolute paths rather than anchors.

- https://github.com/WordPress/gutenberg/pull/29739#issuecomment-1083463587
- https://github.com/WordPress/gutenberg/pull/29739#issuecomment-1083479563

**Comment by ricjcs** [comment]
Hi @t-hamano , thank you very much for your reply.

**Comment by t-hamano** [comment]
@ricjcs

I'm glad you found it helpful.
I would like to close this issue, but if you have something to discuss, please re-opening it.
