### ISSUE TITLE
Top-level patterns

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#42632]
## What problem does this address?
Some patterns, like headers, footers and fullscreen hero areas are not meant to be placed within a parent block. 

It's easy to forget to add a blank paragraph block, or hit "Insert after" before adding another pattern — which can lead to unintended placement of these patterns that meant to be placed at the top-level of a page.

## What is your proposed solution?
What I'd like to reduce is the instances where you have to undo adding a pattern, find a better insertion point, find your pattern again, and add it again.  Perhaps this could be achieved by adding a method to indicate a pattern should be added top-level from the pattern registration. 

## Screenshot

Here's what an incorrectly placed top-level pattern may look like: (A header added within a column)  

<img width="1402" alt="CleanShot 2022-07-22 at 10 29 09@2x" src="https://user-images.githubusercontent.com/1813435/180461254-c6acecda-fabd-476a-abfd-0e97dad5015c.png">

**Comment by mtias** [comment]
This is extremely related to https://github.com/WordPress/gutenberg/issues/39281
