### ISSUE TITLE
Tracking issue for adding `font-family` support to all Core blocks with typography controls

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#42646]
The goal of this tracking issue is to improve the consistency of typography support across core blocks, specifically `font-family`. `font-family` is impacted by the Web Fonts API and has been left off many blocks that already support some form of typography control. The ultimate goal is for all blocks with typography control to also support `font-family`.

Blocks with current PRs to add `font-family` support will be listed below. 

### ✅ Blocks **with** `font-family` support as of Gutenberg 13.7.2:

- Comment Author Name
- Comment Content
- Comment Date
- Comment Edit Link
- Comment Reply Link
- Comments Title
- Heading
- List
- Navigation
- Next Post
- Post Author Biography
- Post Author Name
- Post Date
- Post Title
- Previous Post
- Query Title (Archive Title)
- Read More
- Site Tagline
- Site Title
- Verse

### ❌ Blocks **without** `font-family` support but with other typography supports:

- Button
- Code
- Group
- Next Page
- Page Numbers
- Paragraph (#39642)
- Post Author
- Post Comments Count
- Post Comments Form (probably not needed since the form includes headings, content, and buttons)
- Post Comments Link
- Post Excerpt
- Post Terms (Tags and Categories)
- Preformatted
- Previous Page
- Pullquote
- Quote
- Table
- Term Description

**Comment by Andrew-Starr** [comment]
Shouldn't the Button block be in the _with_ list?

**Comment by ndiego** [comment]
I am closing this out in favor of #43242 as it's a LOT more comprehensive. 🙌
