### ISSUE TITLE
UnitControl: Unit dropdown text is not centered in Safari

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#42650]
Due to a [bug in Safari ](https://bugs.webkit.org/show_bug.cgi?id=40216)where `text-align` does not work on `<select>` elements, the unit text is not center aligned as expected.

## Screenshots

<img width="126" alt="The 'px' text is not centered in the dropdown button" src="https://user-images.githubusercontent.com/555336/180582140-f9223f99-4afe-419c-8b1e-7910a6bf4cfd.png">

**Comment by brookewp** [comment]
@mirka can you still replicate this? In Safari 16.6, I am seeing it is centered: 

<img width="130" alt="Screenshot 2023-08-30 at 6 02 11 PM" src="https://github.com/WordPress/gutenberg/assets/35543432/8bd5eb6c-160e-4c0c-9ed6-3445af14c782">

**Comment by mirka** [comment]
Yes, strange that the original Safari bug isn't closed, but it does seem like our issue has resolved itself. Let's close then!
