### ISSUE TITLE
Changes made to a duplicated block with attribute type of array affects the original block.

### ISSUE THREAD

**Issue by giannis-koulouris-bb** [WordPress/gutenberg#42667]
### Description

I have created a custom block that has an attribute with type of array. Everything works correctly except when I'm duplicating that block, the changes I make to that array attribute on the new block affects the original block as well. It doesn't happen if I copy & paste the block, only if I duplicate it.

### Step-by-step reproduction instructions

1. Create a custom block containing attribute type of 'array'
2. Add some values to that array attribute
3. Duplicate block and make changes to the same attribute
4. You will see the changes affecting the array on the original block.

### Screenshots, screen recording, code snippet

Attributes on block.json
```
"attributes": {
    "enableShapes": {
      "type": "boolean",
      "default": false
    },
    "shapes": {
      "type": "array",
      "default": []
    },
  }
```

Update array attribute function
```
  const updateShapeOption = (index, key, newValue) => {
    const newShapes = [...shapes];
    newShapes[index][key] = newValue;
    setAttributes({ shapes: newShapes });
  }
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
It is probably related to #41565 but needs testing.

**Comment by giannis-koulouris-bb** [comment]
For me it doesn't occur if I just add another instance of that block, or if I copy/paste the block. It **only** occurs when I duplicate the block.

**Comment by Mamaduka** [comment]
@giannis-koulouris-bb, I could reproduce both issues with the example plugin @AdamWills However, itovided. It only happens if the values of the array attributes are the same for blocks.

I'm going to close this issue and let's continue the discussion in #41565.

Thanks for contributing!
