### ISSUE TITLE
Query Loop: show correct posts after setting "Inherit query from template"

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#42675]
### Description

After creating one of the new templates (categories, tags, date, author, etc), adding a Query Loop block, and setting it to "Inherit query from template", it's not clear that the query loop will correctly show posts based on the template. Instead, nothing changes in the editor (same posts are shown), despite the query loop working correctly on the front end. I understand this might be intentional for a template like Author or Date since that'll depend on which author is being viewed but for templates around categories or tags this proves to be confusing. 

This was found as part of the [fifteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/07/11/fse-program-testing-call-15-category-customization/).

### Step-by-step reproduction instructions

1. Go to Appearance > Editor > Templates > Add New
2. Create a new category template for a specific category of posts. 
3. Add a query loop block.
4. Toggle on "Inherit query from template" in the block sidebar settings.
5. Notice no change to what posts are displayed in the editor but notice that if you view the category page the template shows correctly. 

### Environment info

- WP 6.0.1
- GB 13.7.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mjsdiaz** [comment]
I see this issue too.

**Comment by ntsekouras** [comment]
That's a quite hard problem.. For example if we have a Query Loop block in `index.html` what would be the correct posts? `index` is the fallback to everything and could be different in so many scenarios. Same goes for `category.html` etc... Maybe we could do something for more specific templates.. Also we could add a message about this when we inherit maybe? 🤔

**Comment by annezazu** [comment]
Yeah, this seems really tricky to think through. I'd be keen to hear from @WordPress/gutenberg-design in this sense as it does feel like a design problem almost. How do you indicate something has changed but that it might not perfectly reflect what you're seeing in the editor, especially when it aims to be WYSIWYG?

**Comment by jameskoster** [comment]
Related: https://github.com/WordPress/gutenberg/issues/42554, https://github.com/WordPress/gutenberg/issues/41947

> Maybe we could do something for more specific templates

I think this would be a good start.

**Comment by jameskoster** [comment]
Similarly it would be nice if the Archive Title block displayed a more contextual placeholder. E.g. in the `category` template it might display 'Category name'. In `category-recipes` it would display 'Category: Recipes', etc. This would be a lot more intuitive than the current generic 'Archive Title'.

**Comment by annezazu** [comment]
This is still a problem with WordPress 6.2.

**Comment by jorgefilipecosta** [comment]
Hi @annezazu, I think this issue has been fixed and we missed closing it. Can you confirm if things now work well for you? Thank you in advance 😊

**Comment by annezazu** [comment]
It works! Here's a video: 

https://github.com/WordPress/gutenberg/assets/26996883/9dd829f8-6df6-4915-9740-7f6690aa1fc7
