### ISSUE TITLE
Adding or Editing Posts or Pages Displays Two Notification Bubbles Next to The Feedback Menu Item

### ISSUE THREAD

**Issue by TheJeffr0** [WordPress/gutenberg#4267]
I'm using Gutenberg 1.9.1 with Jetpack 5.7 and WordPress 5.0 Alpha. When adding or editing posts or pages, there are two notification bubbles next to the Feedback Menu item. The Feedback Menu is tied to Jetpack's Contact Form module. 

![twofeedbacknotifications](https://user-images.githubusercontent.com/6315977/34534648-fbb2fdce-f08c-11e7-965d-d0b093420429.png)

**Comment by karmatosed** [comment]
This isn't part of Gutenberg, it would be an error with Jetpack. I would suggest reporting it to Jetpack for now and see if it can be fixed there. You can report any issue here: https://jetpack.com/contact-support/?rel=support.
