### ISSUE TITLE
Site Editor: interface shift when tabbing to main editing area

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#42682]
### Description

After creating a new template and tabbing through to add a block, the prompt to use the slash inserter shifts upon focus. This was found as part of the [fifteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/07/11/fse-program-testing-call-15-category-customization/#comment-2646). Feel free to rename this issue -- I struggled to come up with a concise way of describing it!

### Step-by-step reproduction instructions

1. Head to Site Editor > Templates > Add New
2. After creating a new, empty template tab to the main editor.
3. Notice interface shift

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/180832534-50b9abaa-1ebd-44e2-80a9-63f75a4daa4c.mov

### Environment info

- WordPress 6.0.1
- Gutenberg 13.7.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
Is this still an issue? I couldn't reproduce...

I also noticed that there have been some changes to the Popover since the creation of this issue, so it might have been related? 🤔

**Comment by annezazu** [comment]
I can't replicate either! Going to close out. Thanks for looping back.
