### ISSUE TITLE
ColorPalette: Transparent checkered pattern doesn't adhere to 4px grid

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#42687]
## What problem does this address?

The `background` pattern isn't adhering to the 4px grid system (the squares are 25px). This can cause the pattern to be cut off at rather awkward positions when the container size adheres to the 4px grid:

<img width="407" alt="The checkered pattern being cut off awkwardly in a color picker popover" src="https://user-images.githubusercontent.com/555336/180876554-e425d5e7-4afb-4b63-8194-efcc7ac6266b.png">

(Encountered in #41900)

## What is your proposed solution?

Make the square size adhere to the 4px grid, for example 24px.

**Comment by richtabor** [comment]
Related https://github.com/WordPress/gutenberg/issues/42278

**Comment by ciampo** [comment]
> Make the square size adhere to the `4px` grid, for example `24px`.

This sounds like the correct and most sensible solution

**Comment by mirka** [comment]
Fixed by #45295
