### ISSUE TITLE
Color Panel: Add Clear option to Text and Background Color Panels

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#42689]
## What problem does this address?

Lack of consistency.
Example from Text Color Panel in TT1 in the Side Editor. (WP 6.0 and Gutenberg plugin 13.7.2)

Color Panel: Text
![Screenshot 2022-07-26 at 08 53 22](https://user-images.githubusercontent.com/5323259/180942668-e4ca08e0-88c8-4af4-aa50-369d5e9bb917.jpg)

Color Panel: Link.
![Screenshot 2022-07-26 at 08 53 42](https://user-images.githubusercontent.com/5323259/180942721-4e7db2e7-564f-4af8-a10e-609fef0277dd.jpg)

The Link Panel has a Clear option while Text and Background color panels do not.

## What is your proposed solution?

Add the Clear option to ALL Color panels. Inside the Site Editor and also in the Post Editor.
@jameskoster @javierarce

**Comment by richtabor** [comment]
Confirmed this is still the case. 

Do you think we _need_ a "Clear" action there? I haven't noticed it missing from the background and text controls myself. Curious what others think.

**Comment by javierarce** [comment]
Since we have a reset option in the ellipse menu that has the same effect, I think we could remove the Clear action from there.

<img width="280" alt="Screenshot 2022-12-13 at 09 44 35" src="https://user-images.githubusercontent.com/4933/207268563-ac7d7eb8-25e8-4b99-b9fd-00f05bea6a24.png">

**Comment by paaljoachim** [comment]
One method that is good to keep in place is click color to select. Click it again to deselect.
This does not work when creating a custom color.

The clear option might be a redundant, but at the same time it is also very obvious.
Reset options inside the 3 dot contexual menu feels like a good place to reset various options. As in the example that can be seen which is shared by Javier.

**Comment by richtabor** [comment]
> This does not work when creating a custom color.

Not quite following here. Is there a separate issue indicating this? Select/deselect should would on every color/gradient control.

**Comment by paaljoachim** [comment]
**EDIT: NB! My mistake. Retesting in next post.**

Example.
Clicking Background color. Clicking into custom color area so the transparent area is filled in with a color.
![Screenshot 2022-12-14 at 09 39 18](https://user-images.githubusercontent.com/5323259/207625422-fd7b171c-f69a-4028-9513-c82133f28f56.jpg) There is no clear button.

Btw I checked again and I am not able to see the Clear button at all using Gutenberg plugin 14.7.1 and TT1 theme. As it uses the 3 dot drop down menu with the reset option.

![Screenshot 2022-12-14 at 09 48 07](https://user-images.githubusercontent.com/5323259/207627495-4c1f2c5b-1f09-4c85-a976-0d95826f4174.jpg)

**Comment by paaljoachim** [comment]
Retesting.
Gutenberg plugin 14.7.3. (The only plugin which is active.)
WordPress 6.1.1

Varies themes.
Testing environment is an online development site in the Brave browser.
Using a Heading block.

--------

TT1.
Index template.
Added Heading block.

Added colors to Text, Background and Link.
Text color: from Theme.
Background color: from Custom.
Link color: from default.

Link color is showing a Clear button. 
![Screenshot 2022-12-14 at 23 02 11](https://user-images.githubusercontent.com/5323259/207769718-1c023b83-826c-48d3-8875-7bd703080c58.jpg)

Text and Background does not have a Clear button.

---------

**Twenty Twenty-Two**

Index template.
Added Heading block.
Added colors to Text, Background and Link.

Link color is showing a Clear link.

-----

**Twenty Twenty Three**

Index template.
Added Heading block.
Added colors to Text, Background and Link.

Link color is showing a Clear link.

--------

After chasing my own tail for a few rounds I am now back again.
It seems natural to remove the Clear link as [Javier mentioned](https://github.com/WordPress/gutenberg/issues/42689#issuecomment-1347940922).
