### ISSUE TITLE
Copy command doesn't copy selected text when a block is focused

### ISSUE THREAD

**Issue by bradyvercher** [WordPress/gutenberg#4268]
## Issue Overview

When trying to copy text from a field in the block inspector or the media modal, the block content itself is copied to the clipboard instead of the selected text.

## Steps to Reproduce (for bugs)

1. Insert a block and open the block inspector
2. Add some text to the "Additional CSS Class" field
3. Copy the text in that field
4. Paste the copied text in a text editor

## Expected Behavior

I expected the text I selected in the field to be copied.

## Current Behavior

The contents of the block are copied instead.

## Screenshots / Video

![copy-paste](https://user-images.githubusercontent.com/1302030/34538798-bb3dd4da-f082-11e7-849d-364770fb3554.gif)

**Comment by aduth** [comment]
Relevant logic:

https://github.com/WordPress/gutenberg/blob/2d559e38467dba90e770ed1db04dabcf88e02bd3/editor/components/block-list/index.js#L111-L129

**Comment by aduth** [comment]
Related: #4037

cc @iseulde

**Comment by aduth** [comment]
Do these need to be document-bound events?

https://github.com/WordPress/gutenberg/blob/2d559e38467dba90e770ed1db04dabcf88e02bd3/editor/components/block-list/index.js#L62-L63

Or could they be applied to the returned element of `BlockList`, or at least bound to the `ref` of the node it renders?

**Comment by iseulde** [comment]
As far as I can see, this would be unreliable right now, e.g., in Chrome, if the first thing I select is an image (no input field), the event target would be the post title. Unsure why because the active element is the block node... Looking further.

**Comment by iseulde** [comment]
Turns out the `isInputField` check is broken.
