### ISSUE TITLE
Quotes sentences spanning multiple lines display large, incorrect line height

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#42713]
## Description
Quotes with sentences long enough to wrap multiple lines result in a line height that is far larger than expected. This only occurs for block themes (e.g. Geologist), where the editor renders type matching the font size for the theme. It would appear that the Quote block began displaying the theme's font size in the 20.4 release, leading to the outlined line height issue. 

## Step-by-step reproduction instructions
1. Create a new post with a block theme enabled (e.g. Geologist). 
1. Insert a Quote block. 
1. Type a long enough sentence in the Quote so that the text wraps to multiple lines. 

## Expected behaviour
The line height is an appropriate height and the quote is legible. 

## Actual behaviour
The line height is an incorrect height causing the quote to be illegible as each line is separated by a large amount of vertical space. 

## Screenshots or screen recording (optional)

<details><summary>UX Recording</summary>

https://user-images.githubusercontent.com/438664/181091016-6eef4a11-3133-497a-be27-b3035eacd20c.mp4

</details>

| 20.3 | 20.4 |
| - | - |
| ![Quote with long sentence displays correct line height](https://user-images.githubusercontent.com/438664/181091014-32299366-5e34-44ab-bcc0-a6d043cf1e0b.jpeg) | ![Quote with long sentence displays incorrect line height](https://user-images.githubusercontent.com/438664/181091027-5f2a24d7-b6c4-479f-8fb5-0287507b6566.jpeg) |

## WordPress information
- WordPress version: 6.0
- Gutenberg version: 13.7.3
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Geologist

## Device information
- Device: iPhone SE, Samsung Galaxy S20
- Operating system: iOS 15.6, Android 12
- WordPress app version: 20.4

**Comment by fluiddot** [comment]
> It would appear that the Quote block began displaying the theme's font size in the 20.4 release, leading to the outlined line height issue.

Looks like this issue is in fact related to the Quote block V2, which as far as I tested, is only available starting in version 20.4.

Marking this issue as a High priority because it breaks the experience of the Quote block.

**Comment by geriux** [comment]
It looks like this is happening for the Geologist and Quadrat themes. A line height value of `40px` is set for the Quote block in their [theme.json](https://github.com/Automattic/themes/blob/72d666fa7f218644672e3ad7dd85d5797c0fd16d/geologist/theme.json#L227) file, usually, there are only unit-less values so it can calculate the line height using the font size value. I've asked internally if this is expected or if its a bug. If it is expected, we'll need to take into account this cases.

I've tested other themes and the Quote block V2 is working correctly in those.

**Comment by fluiddot** [comment]
Thanks @geriux for taking a look and providing the findings 🙇 , let's see if this can be fixed in the themes 🤞. However, I understand that if there are themes that already use units in the line height value, eventually, we might encounter the same issue on others themes in the future. Hence, it would be great to address this sooner than later. Being this said, I'd advocate keeping this a high priority.

As an additional note, I did a search in the [themes repository](https://github.com/Automattic/themes) and found that the issue will affect the following themes:

- geologist
- geologist-blue
- geologist-cream
- geologist-slate
- geologist-yellow
- quadrat
- quadrat-black
- quadrat-green
- quadrat-red
- quadrat-white
- quadrat-yellow
- zoologist

**Comment by geriux** [comment]
This will be fixed once [these theme changes](https://github.com/Automattic/themes/pull/6290) are merged and released.

**Comment by dcalhoun** [comment]
I am not longer able to reproduce this. Feel free to re-open if it is reproducible.
