### ISSUE TITLE
Storybook: Write add-on to simulate effects of `forms.css` file

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#42717]
## What problem does this address?

When components are used in a WordPress context, they will be affected by a lot of broadly scoped styles in the [`forms.css`](https://wordpress.org/gutenberg/wp-admin/css/forms.min.css) file, which is loaded in wp-admin pages. But as a component library, the presence of the forms.css file in any given use case is not guaranteed.

## What is your proposed solution?

Similar to how we implemented a LTR/RTL switcher to the Storybook, we should implement a switcher to load/unload the forms.css file so component styles can be tested in both environments.

**Comment by ciampo** [comment]
I'm starting to run out of emojis
