### ISSUE TITLE
Button alignment issue after update 13.7.2

### ISSUE THREAD

**Issue by Johanwalter** [WordPress/gutenberg#42720]
### Description

After update Gutenberg to 13.7.2, button alignment on front end does not work
It is different than back end

### Step-by-step reproduction instructions

On front end buttons are always aligned left and cannot be changed whatever is settings on back end
On back end alignment is correct, center and change if we modify settings

FRONT END https://ibb.co/5TWTH42
BACK END https://ibb.co/FYP3dJp

FRONT END https://ibb.co/BKXxd2r
BACK END https://ibb.co/y8w36qN

Buttons alignment were correct before update on 13.6.0

 have managed to fix issue with the following custom css

[class*=wp-block-] [class*=wp-block-] {
	text-align:center;
}
This CSS applies to all buttons, by chance all my button are centered.

I have updated this morning 13.7.3 it didn’t change anything

I have a stagging website that I always update before updating prod website, issue didn’t happen on stagging website, only on prod website.
I have an other website with same template, issue didn’t happen on this website (prod or stagging) but issue did happen on this other website on stagging website when updating Gutenberg 13.7.0. I edited page, saved page and it solved issue.
That’s first thing I have tried yesterday but it didn’t work.
I have also tried to place !important after align-items in .wp-block-buttons.wp-container-1, it didn’t work. It is like button block is “frozen” on front end and does not accept any css change.

.wp-block-buttons.wp-container-1 {
    align-items: center !important;
}

### Environment info

Wordpress 6.0.1
Gutenberg Version 13.7.3
Issue is on all browser

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by paaljoachim** [comment]
Originally reported here: https://wordpress.org/support/topic/button-alignment-issue-after-update-13-7-2/

Testing as I understand it. Please adjust @Johanwalter 

WordPress 6.0.1
Gutenberg plugin 13.7.3
Theme: Twenty Twenty One

1. Went to a current page.
2. Added two buttons.
3. In the top parent Buttons block I aligned right.
![Screenshot 2022-07-27 at 09 52 13](https://user-images.githubusercontent.com/5323259/181193061-2b1b9696-bf5f-4117-bd89-b9ca22828a11.jpg)

4. Checked the frontend and both buttons are aligned right.
![Screenshot 2022-07-27 at 09 52 37](https://user-images.githubusercontent.com/5323259/181193082-5cf308b9-f280-49bc-9964-8627de2160be.jpg)

I assume there are some steps that I am missing so I need you to write a step by step test instructions so that I can figure out what is going on.

**Comment by Johanwalter** [comment]
You did testing right
Issue happened after update from 13.6 to 13.7.2 on my prod website
On my stagging website, I updated from 13.6 to 13.7 to 13.7.1 to 13.7.2, I didn't have the issue

On an other website with same template and WP + Gutenberg version,  I had issue on stagging website when updating from 13.6 to 13.7
issue disappeared when I edit the page and saved it.
On this other website, when updating from 13.6 to 13.7.2, issue didn't happen

I have noticed this issue only from 13.7 and it happens just after update and not on all websites, no issue before 13.6
Back end shows correctly, front end does not show like back end.

Which modification have been made on button block between 13.6 and 13.7 ?
text-align:center in custom CSS solve issue, why do I need to add text-align now?

**Comment by getdave** [comment]
@Johanwalter Please can you try the same thing on a test site with another Theme installed? For example Twenty Twenty Two. 

Also it's highly likely that this is a Plugin related Issue so I would also try (in a test environment) disabling Plugins and renabling one by one to identify the culprit.

**Comment by Johanwalter** [comment]
Issue happened right after update from 13.6 to 13.7.2, no issue while on 13.6 so issue is from  Gutenberg update

**Comment by paaljoachim** [comment]
What is sometimes difficult is that different sites with the same setup can behave differently.
As we are working on figuring out where the error is. It would be helpful to get feedback if you test with another theme, and also deactivate all plugins and then reactivate the Gutenberg plugin. Then check the results.

**Comment by kathrynwp** [comment]
I was **not** able to replicate the issue with:

WordPress 6.0.1
Gutenberg 14.1.0 active or inactive
No other plugins active
Twenty Twenty-Two 1.2

@Johanwalter Are you able to replicate the issue with the same settings above?

**Comment by Johanwalter** [comment]
No I cannot replicate the issue.
I have another website with same plugin and template, I don't have the issue.
On demo of website, I don't have the issue, issue is only on prod.
I m still looking where issue can come from
I found that on this website I have 2 scheduled tasks that failed which are not failed on any other website
woocommerce_run_product_attribute_lookup_update_callback
adjust_download_permissions

Not sure if can be the cause

<br class="Apple-interchange-newline">
--


<br class="Apple-interchange-newline">

**Comment by kathrynwp** [comment]
@Johanwalter Thanks for re-testing and letting us know that you cannot replicate the issue.

Since it's not a theme-specific issue, I'm going to go ahead and close this out, but you're welcome to post in the WordPress.org support forums if you'd like further help with troubleshooting.
