### ISSUE TITLE
Theme Export: Strip out site specific details

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#42730]
### Description

The theme export process already removes theme slugs from template parts, as when templates come from files these aren't needed. Similarly we should remove other site/implementation specific details from templates on export, including:

- Removed the ref id on the Navigation block
- Remove IDs from the image block
- Remove IDs from the query block

There may be more like this that we need to remove.

### Step-by-step reproduction instructions

1. Add some items to the navigation block in your theme
2. Export your theme using the site editor
3. You will see a "ref id" in the template for the navigation block - this won't have any meaning on another site.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Adding the dev documentation label because once this is solved this page in the theme developer handbook can be updated:[Creating new themes using the Site Editor](https://developer.wordpress.org/themes/block-themes/creating-new-themes-using-the-site-editor/)

**Comment by Mamaduka** [comment]
Maybe we can make this part of the `_remove_theme_attribute_in_block_template_content` so we don't have to parse template content multiple times during the export.

**Comment by jffng** [comment]
I opened a PR for this in wordpress-develop: https://github.com/WordPress/wordpress-develop/pull/3899

Let me know if that's not a good approach. I wasn't sure how best to do this in Gutenberg, since it's a utility function and not a part of a class, I can't overwrite it like we handle the backports and class overloading for global styles, etc.

**Comment by jffng** [comment]
> Remove IDs from the query block

Just an update that based on [this feedback](https://github.com/WordPress/wordpress-develop/pull/3899#discussion_r1104638014), we should leave the queryIds in the query markup.

**Comment by carolinan** [comment]
@WordPress/block-themers Is this still something we want to do? Does it cause any errors?, or is it only confusing?
If it is only confusing, perhaps this issue could be closed?

**Comment by t-hamano** [comment]
As far as I know, the site-specific information contained in the blocks is at least the following. There may be more.

- Audio block: `id`, `src`
- Cover block: `id`, `url`
- File block: `id`, `href`, `fileId`, `fileName`
- Gallery block: `url`, `fullUrl`, `link`, `id`, `ids`
- Image block: `url`, `id`,
- Page List Item: `id`
- Video: `id`, `src`

More site-specific information may be added to existing or new blocks in the future. Also, we have no control over the site-specific information contained in custom blocks. So, it can be hard to process all this information.

If we want to implement such functionality, the Create Block Theme plugin may be a better choice.

**Comment by MaggieCabrera** [comment]
> [@WordPress/block-themers](https://github.com/orgs/WordPress/teams/block-themers) Is this still something we want to do? Does it cause any errors?, or is it only confusing? If it is only confusing, perhaps this issue could be closed?

I'd agree with @t-hamano that this is better solved via CBT. The site specific info still makes sense for the use case of a backup of the same site. I'd say it's ok to close or if we still consider this to be interesting to do in core, make it an option

**Comment by mikachan** [comment]
I agree that we can close this, even if just to deprioritise it for now. Create Block Theme already handles a lot of these site-specific details as of this PR: https://github.com/WordPress/create-block-theme/pull/522 (included in version 2.0.0 of the plugin).

**Comment by t-hamano** [comment]
Thank you everyone for your feedback. Let's close this issue for now. 

Feel free to reopen it if you think it would be ideal to have this issue resolved in core.
