### ISSUE TITLE
DRY up 'No saved blocks' and 'No blocks found' messages

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#4273]
There's some unnecessary duplication between the 'No saved blocks' message added in https://github.com/WordPress/gutenberg/pull/4182 and the 'No blocks found' message added in https://github.com/WordPress/gutenberg/pull/4040.

| No saved blocks | No blocks found |
| --- | --- |
| ![](https://user-images.githubusercontent.com/612155/34369712-57623ebc-eb12-11e7-9e2c-c3847f2badae.png) | ![](https://user-images.githubusercontent.com/1779930/34047627-e2346cb0-e17e-11e7-9d75-695f0382994c.png) |

These two messages should look similar, use the same component, and re-use the same code.

See https://github.com/WordPress/gutenberg/pull/4182#issuecomment-355057004.

**Comment by ronakganatra9** [comment]
Issue is solved under #4570 
Fixes: #4282
Pr #4570
