### ISSUE TITLE
Use username and password from shared config in call to `login` on `@wordpress/e2e-test-utils`

### ISSUE THREAD

**Issue by rafaelzaleski** [WordPress/gutenberg#42742]
### Description

E2E tests fail in environments where the default username and password are not `admin` and `password` because [these values are hardcoded in the login function](https://github.com/WordPress/gutenberg/blob/3595cc02fd5a3295c7db2b5a75d2a06314945b36/packages/e2e-test-utils/src/rest-api.js#L40). We need to use the values from the [shared config](https://github.com/WordPress/gutenberg/blob/3595cc02fd5a3295c7db2b5a75d2a06314945b36/packages/e2e-test-utils/src/shared/config.js) (because they can be overridden in the env variables) instead of hardcode it in the login function.

### Step-by-step reproduction instructions

1. Try to run tests in an E2E environment with the admin user username and password other than `admin` and `password`.
2. Call the `login` function from the issue description inside a test case.
3. There should be an error in your test case: _`Fetch api call failed for ${ apiFetch.nonceEndpoint }: ${ response.status }`_

### Environment info

- @wordpress/e2e-test-utils 7.9.0
- Latest version of WordPress

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
It is current possible to define `WP_USERNAME` and `WP_PASSWORD` env variables when using puppeteer test utils  and it's possible to pass a user to the playwright test utils.
