### ISSUE TITLE
Custom React block saves different HTML according to user role

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#42741]
### Description

_The code for this issue is in a Gist at https://gist.github.com/markhowellsmead/d9c4e0dc13292c8cdb88d0f2be6bfbee._

I have the following two components in custom React block code.

```
const srcSetAttribute = srcset => {
    return Object.entries(srcset)
        .map(([key, entry]) => <code>${entry} ${key}w</code>)
        .join(", ");
};

const FigureWithImage = ({ classNameBase, image, lazy = true, key, sizes }) => {
    if (!image.id) {
        return "";
    }

    const { org, srcset, attributes } = image;
    const { width, height, alt } = attributes;

    const srcSetString = srcSetAttribute(srcset);

    return (
        <figure className={<code>${classNameBase}__figure</code>}>
            <img
                key={key}
                src={org[0]}
                srcSet={srcSetString}
                sizes={sizes}
                alt={alt}
                className={`${classNameBase}__image`}
                width={width}
                height={height}
                loading={!!lazy ? "lazy" : "eager"}
            />
        </figure>
    );
};
```
These are then used in the save function to render the content to be saved to the database.

```
{!!image.id && (
    <FigureWithImage
        key={image.id}
        classNameBase={classNameBase}
        image={image}
        lazy={true}
        sizes={'(min-width:1140px) 1140px, 100vw'}
    />
)}
```

If I save the post using an administrator role, the HTML is saved correctly and contains all of the attributes. If I save the post using a user with an editor role, then the HTML is saved but only has the attributes `src`, `alt`, `class`, `width`, `height` and `loading`.

### Step-by-step reproduction instructions

1. Add the block to the page
2. Select an image and save the post using an administrator account.
3. Re-save the same post using an editor account.
4. Review the HTML saved to the database, which differs from the version which the administrator account saved.

### Environment info

- WordPress 6.01 without Gutenberg plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by markhowellsmead** [comment]
Per https://wordpress.org/support/topic/gutenberg-custom-block-saves-different-html-according-to-user-role/#post-15864722: the issue may be related to the unfiltered_html capability. This is a multisite installation.

**Comment by talldan** [comment]
@markhowellsmead It looks like this has been reported in core trac. Originally reported 8 years ago and unfortunately still no resolution - https://core.trac.wordpress.org/ticket/29807. There are a few tickets for other html elements and attributes too.

There isn't anything that can be done in the Gutenberg codebase, so I'll close this issue.

**Comment by markhowellsmead** [comment]
Thanks @talldan. For anyone else encountering this issue: using https://gist.github.com/kellenmace/9e6a6fbb92ec75940f23d2a6f01c9b59 as a workaround seems to resolve the problem.
