### ISSUE TITLE
Button Block Stand on a line option doesn't save

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4275]
## Issue Overview
When I change the _Stand on a line_ option for a button block, to On, and then update the page, the option doesn't get saved. If I close the page then re-edit it again, this button option is turned Off.

## Steps to Reproduce (for bugs)
1. Insert Button block
2. Click the _Stand on a line_ toggle to On
3. Update Page
4. Exit page
5. Re-edit page and check _Stand on a line_ option again and it is still off

## Expected Behavior
After changing an option and then Updating my page, that option should get saved 

## Current Behavior
_Stand on a line_ option for a button block isn't saving

_Gutenberg 1.9.1
Firefox Quantum 57.0.3 (64-bit)
WordPress 4.9.1_

**Comment by maddisondesigns** [comment]
Have updated to v2.0.0 and this option still doesn't save.

**Comment by designsimply** [comment]
Closing because I tested with Gutenberg 3.1.1 and I don't see a "Stand on a line" toggle for the button block. If I have missed something, please reopen with a screenshot and I will take another look!
