### ISSUE TITLE
Block Transform: Some attributes aren't carried successfully between image and gallery block

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#42755]
### Description

When images with a custom size are converted to a gallery block, images may overflow because the custom size of images is retained.
Also, images in a gallery block don't allow resizing, so the size cannot be reset.

On the other hand, the custom size will be removed if images are converted to image blocks again.

I think the custom size should be removed when converting image blocks to a gallery block.

### Step-by-step reproduction instructions

- Add an image block.
- Set the custom size.
- Transform to a gallery block.
- Confirm that the image has the custom size.
- Transform back to an image block.
- Confirm that the image doesn't have the custom size.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/181421180-f4849a4a-904a-4db5-9e22-af12d7c7bb71.mp4

### Environment info

- WordPress 6.1-alpha-53766
- Gutenberg 13.8.0-rc.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I have discovered that there are other attributes that are not kept  in the transformation between the image block and the gallery block.

| | Are attributes keeped? - Image to Gallery | Are attributes keeped? - Gallery to image |
| ---------------- | ----------------------------------------- | ----------------------------------------- |
| align | Yes (It will be carried as an attribute of the gallery block if all images have the same value) | Yes |
| url | Yes | Yes |
| alt | Yes | Yes |
| caption | Yes | Yes |
| title | Yes | ⚠ No |
| rel | ⚠ No | ⚠ No |
| linkClass | Yes | ⚠ No |
| anchor | Yes | ⚠ No |
| width | ⚠Yes (not expected) | No |
| height | ⚠Yes (not expected) | No |
| sizeSlug | Yes (It will be carried as an attribute of the gallery block if all images have the same value) | Yes |
| linkDestination | Yes | Yes |
| linkTarget | ⚠ No | Yes |
| Additional CSS | Yes | ⚠ No |

**Comment by glendaviesnz** [comment]
I started looking at this here, but ran out of time to work through the full list of attributes that are/are not being carried across successfully. @t-hamano feel free to add to that PR if you have time, otherwise I will have another look at it next week.

**Comment by t-hamano** [comment]
@glendaviesnz 

Thank you for submitting PR.
I was also in the process of working on how to respond to this issue.

Ideally, I think the attributes of each block should be carried over in the block transformations.
(except that the `sizeSlug` should be unified when converting images to gallery blocks)

I will add it to that PR if I find a good way to handle this.

**Comment by t-hamano** [comment]
I may not have done enough testing on how the attributes are inherited, so I will test again.
