### ISSUE TITLE
SetNonce defaulting to admin and password as credential.

### ISSUE THREAD

**Issue by sfgourav** [WordPress/gutenberg#42761]
### Description

The setNonce function in rest-api.js, is making a login fetch request with defaulted credentials. Because of which we wish to run test on an environment where we don't have such user, the tests are failing.

### Step-by-step reproduction instructions

run the command in the following sequence.
1. Run a wordpress environment, serving on the hostname 'localhost:8080'
2. Make sure there is no user with name admin and password in the above environment.
3. run wp-scripts test-e2e command with login credentials passed as environment variable.
`WP_BASE_URL=http://localhost:80  WP_USERNAME=admin_1  WP_PASSWORD=password_1 wp-scripts test-e2e`

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/81237364/181444014-8bf53698-9d77-40a6-bb7c-acffb3cadf48.png)

### Environment info

- Wordpress v6.01
- e2e-test-utils v7.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I can confirm that values are hardcoded in the `login` method. Hence, removing the `Needs Testing` label and marking this as an enhancement.

https://github.com/WordPress/gutenberg/blob/2c29bff14b4f6503ecb40ad5dc97b3f8bf18a192/packages/e2e-test-utils/src/rest-api.js#L38-L41
