### ISSUE TITLE
Template Editing: make content edit-ability consistent

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#42767]
In the site editor, it is not possible to edit dynamic content pulled into Query blocks. You can move the blocks around, but not edit their contents. However, you _can_ edit dynamic content for pages (for example if you have a static home page). The same is true in the template editor – you can edit template and content simultaneously.

This can lead to confusing experiences where users struggle to tell where the template ends and the page content begins. 

It would be good to try making things consistent here, that is to say: make all dynamic content un-editable when the template is the focus.

**Comment by jasmussen** [comment]
Connecting some dots here, it would be good to think of enabled/disabled elements in the editor also in context of conversations around overlay mode. See also comments [here](https://github.com/WordPress/gutenberg/pull/40664#issuecomment-1112524333) and [here](https://github.com/WordPress/gutenberg/issues/32163#issuecomment-1110859404).

**Comment by jameskoster** [comment]
Good point. There's also lock status to consider. Another approach here could be to 'content lock' these blocks by default. 

That way the initial experience would (hopefully) give a clearer definition between content and template, but more experienced users can still edit everything without having to switch context entirely.

**Comment by jameskoster** [comment]
I think this is no longer an issue given all the changes around content editing in the site editor.
