### ISSUE TITLE
Query block creates 3 WP_Query's by default

### ISSUE THREAD

**Issue by rmorse** [WordPress/gutenberg#42779]
### Description

When working with pre_get_posts and the query block, I noticed that 3 queries were being fired.

After some more digging, I realised the pagination blocks (numbered, and prev/next) consume the block attributes and create a new WP_Query, just get to get  `max_num_pages` from the query.

I realise if a server has object caching this wouldn't be a huge performance hit, but in other scenarios this adds a lot of overhead.

### Step-by-step reproduction instructions

- Add the query monitor plugin.
- Add the query block to a page and save.
- Check the frontend and you can find 3 queries run with the same args
- Remove the pagination from the query block results in only 1 query.

### Screenshots, screen recording, code snippet

Check the 2 query block pagination php files:
- `wp-includes/blocks/query-pagination-numbers.php`
- `wp-includes/blocks/query-pagination-next.php`

And you can see the WP_Query's in question.

_I do see something where the global `$wp_query` is used, not sure how that logic is triggered (and would it work if we're using mutliple query blocks on a page), but default behaviour seems to fire off these additional queries._

I think in an ideal scenario, the query block would generate the query (not the post template as it is now), and then this would pass down the single query instance into its children (post template and pagination blocks).

### Environment info

All gutenberg versions

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
@ntsekouras @spacedmonkey Would you have any insight on this one?

**Comment by Thelmachido** [comment]
There hasn't been much activity on this issue in a while, @ntsekouras & @spacedmonkey are you able to check and confirm if this is an issue at the moment?

The issue was been marked stale for a while, it might end up being closed.

**Comment by rmorse** [comment]
I think considering use of the query block is starting to really take off, that this is a fairly important issue to investigate as it adds a lot of unnecessary overhead 🙏

**Comment by rmorse** [comment]
It still exists, let's keep this open

**Comment by getdave** [comment]
Let's keep this one open for further testing and possible future fix.

**Comment by Thelmachido** [comment]
Due to what @getdave mentioned, I have removed the stale label

**Comment by spacedmonkey** [comment]
@rmorse Is this still an issue?

**Comment by getdave** [comment]
@ndiego Could we possibly take a look at this on the next triage session 🙏

**Comment by rmorse** [comment]
@spacedmonkey hmmm *possibly*, although I can observe some things have changed since initially reporting:

- When using query monitor, I'm no longer seeing duplicate queries (could that be due to the query optimisation work you did in 6.1?)
- The pagination blocks as well as the query block, still do run a `new WP_Query()`  - references to their locations are in the original post, I've double checked this with the latest Gutenberg plugin too.
- It seems the query loop presets no longer include pagination (not sure if this is a new observation or not) - but the only way I've managed to get the query block to display with pagination (today), is to select "Choose blank" after inserting the block

My current assumption is that the WP_Query optimisation work in 6.1 prevents a new query being created/run if the same arguments are passed and it instead re-uses the existing query matching the arguments.

In that case, the performance issue might be solved due to the improvements in 6.1...

I wonder, is it still a good idea to be running multiple `new WP_Query()` when instead we should probably be re-using the result of only one instance?

**Comment by spacedmonkey** [comment]
Running multiple WP_Query is not less of an issue, now that these requests are cached. I am not seeing repeated database requeries in my profiling. Where possible the global WP_Query object is being re-used, as I not sure I can currently see the issue.

**Comment by rmorse** [comment]
@spacedmonkey 

Please take a look:
<video src='https://user-images.githubusercontent.com/853547/203830293-2981fb85-cc98-4010-940f-7251b219e3cb.mp4' />


Adding some logging before the WP_Query itself in those files shows on the frontend (so I'm assuming they must be run in some way), but for some reason it does not appear as a duplicate in query monitor :/

**Comment by rmorse** [comment]
Tagging @ntsekouras for additional input as we briefly discussed this issue on slack (the outcome of that was that it needs more investigation)

**Comment by spacedmonkey** [comment]
@rmorse To not create a new WP_Query, you need only click on "Inheit query from template". This use the only setup WP_Query on page load. 

There is issue here, but i think it is caching in core.

**Comment by rmorse** [comment]
Yeah, although the inherit query from template is only useful in FSE on things like archives and search (I believe), if you want to embed this on a regular page I think most people won't want to toggle that option so they get access to the query builder controls in the inspector

**Comment by spacedmonkey** [comment]
In WordPress 6.1, caching was added in to WP_Query, making this much less of a problem - https://make.wordpress.org/core/2022/10/07/improvements-to-wp_query-performance-in-6-1/

Otherwise, there is no easier way to pass data before block like this.

**Comment by rmorse** [comment]
That was my understanding, to solve this requires some other mechanism for passing data between blocks (or down, hierarchically) that doesn't exist yet.

Perhaps the context system could be leveraged but I'm doubtful

**Comment by aristath** [comment]
@rmorse does https://github.com/WordPress/gutenberg/pull/46356 improve things?

**Comment by rmorse** [comment]
@aristath I see it was closed, is this because there is now caching in core so the same query won't be run twice (as described on previous comments)?

**Comment by aristath** [comment]
Yes, it turns out this is no longer an issue. I think it would be safe to close this issue as well 👍

**Comment by ntsekouras** [comment]
I closed this based on the above two comments([1](https://github.com/WordPress/gutenberg/issues/42779#issuecomment-1345401078),[2](https://github.com/WordPress/gutenberg/issues/42779#issuecomment-1346366092)). Feel free to reopen if there is the need to.
