### ISSUE TITLE
Left/right aligned audio block not displaying properly in Chrome

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#4278]
## Issue Overview
Left/right aligned audio player is not displaying properly in Chrome (tested in Chrome 62.0.3202.94/ macOS High Sierra 10.13.1 & Twenty Seventeen theme).

Frontend:
![image](https://user-images.githubusercontent.com/4550351/34550819-f5afacac-f167-11e7-9ba0-84652f79b70e.png)

Backend:
![image](https://user-images.githubusercontent.com/4550351/34550828-0b89c92c-f168-11e7-809e-5ee3b9a93512.png)

## Steps to Reproduce (for bugs)
1. Create a new post using Chrome browser and add three audio blocks.
2. Set the alignment of the first one to "left".
3. Don't set the alignment on the second one or set it to "center".
4. Set the alignment of the third one to "right".
5. Publish post and view it on the front end.

## Expected Behavior
For the left and right aligned audio players to display according to alignment settings, as it happens in Firefox (tested in 57.0.1):
![image](https://user-images.githubusercontent.com/4550351/34550895-b0d2a93a-f168-11e7-820c-54b997d42ff0.png)

## Current Behavior
The audio player is not displaying properly (missing controls) in the Chrome browser when it's left/right aligned.

## Possible Solution
I tracked this down to this piece of CSS in Gutenberg's style.css:
`.wp-block-audio audio { width: 100%; }`

Disabling this rule seems to fix the left/right aligned audio players, so adding a more specific rule targeting left/right aligned items like so: 
`.wp-block-audio.alignright audio, .wp-block-audio.alignleft audio` 
seems like a good place to start.

**Comment by jorgefilipecosta** [comment]
Hi @alaczek thank you a lot for reporting this problem. I have seen this behavior in the past but now I did a set of tests in different themes and it looks like this problem is not happening. Probably it was solved during some refactoring. I will close the issue for now if the problem still happens to you when testing on master feel free to reopen it.
