### ISSUE TITLE
List Block: Editing a copy of a link applies changes to the first link, not the copy

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#42784]
### Description

When you try to edit a link on a copied list item, it updates the link that was copied, not the pasted new link.

### Step-by-step reproduction instructions

1. Using the List block, add one list item with a link
2. Copy that first item and create a second one with it
3. Edit the link on the second item

### Screenshots, screen recording, code snippet

![Screen Capture on 2022-07-28 at 10-07-42](https://user-images.githubusercontent.com/27249804/181598497-34b79c56-d5cb-43fe-a88c-59f129deb8a9.gif)

### Environment info

Originally reported 7 days ago. Tested again today on the following:

- WordPress 6.0.1
- Gutenberg 13.7.3 
- Theme: Twenty Twenty-Two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @cuemarie

Does this happen only when editing links in the List block?

**Comment by talldan** [comment]
I think this was already reported in https://github.com/WordPress/gutenberg/issues/41771.
