### ISSUE TITLE
Reusable blocks fail to load when used in a template

### ISSUE THREAD

**Issue by intelligence** [WordPress/gutenberg#42787]
### Description

Setting up a post template to include reusable blocks works at first save, but when the edit page is reloaded, the block fails to load. Same reusable block added regularly (not via template) works fine. 

Related:
https://github.com/WordPress/gutenberg/issues/15542
https://github.com/WordPress/gutenberg/issues/14127

### Step-by-step reproduction instructions

Create reusable block, include in post template:
```
function myplugin_register_template() {
	$post_type_object = get_post_type_object( 'page' );
	$post_type_object->template = array(
		array( 'core/block', array( 
			'ref' => '720', <-- Switch ID
		) ),
	
	);
}
add_action( 'init', 'myplugin_register_template' );
```

Create new post, publish, reload. Block fails to load with `Block has been deleted or is unavailable.` as error message.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/756582/181638129-5868892e-58ee-4718-aedd-5e6310e8aac3.mov

### Environment info

6.0.1, Gutenberg 13.7.3 (tried both with it on and off), Twenty Twenty-Two
Chrome
MacOS 12.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
There's a subtle issue in your code - the problem happens because the correct type for `ref` needs to be used. The block.json defines the attribute as a number, but you're using a string.

The block is saved with a string for `ref`, but parsing of the attribute fails when reloading the editor.

**Comment by intelligence** [comment]
Ah, thank you for clarifying!
