### ISSUE TITLE
Nested blocks

### ISSUE THREAD

**Issue by joyously** [WordPress/gutenberg#428]
In #409 there was a comment
>  I'm also operating under the assumption that a block will be "root level" for the foreseeable future - i.e. it will be a direct child of the article.post element that holds the post content.

It appeared that all (_block type_)HTML elements were becoming blocks. But a lot of HTML elements can be nested, so it follows that blocks could be nested. How could they be previewed correctly if they are not?

Nested lists come to mind immediately. The theme test data contains several nested lists.
An image is a block, right? And can you put it in a paragraph? Even one with a caption.
I was told that the heading hierarchy needed for accessibility could be bypassed by using a figure to hold HTML examples my imagined blogger was writing about.
Blockquotes are for referencing whatever HTML is from an outside source, not just paragraphs.
Tables can have images and paragraphs.
I just wrote issue #427 about being able to put wrapper blocks around other blocks for styling.

**Comment by jasmussen** [comment]
Nesting will be critical to the customization focus later in the year. I suspect the editor will have to deal with nested content, but perhaps not optimize the UI towards this.

**Comment by strarsis** [comment]
So a plugin that provides a block could also offer a Gutenberg-editor for block contents - which in turn could again contain another Gutenberg-editor with more blocks?

**Comment by jasmussen** [comment]
> So a plugin that provides a block could also offer a Gutenberg-editor for block contents - which in turn could again contain another Gutenberg-editor with more blocks?

It's more of an ability to insert a block into another. For example you might have a block that creates two columns. You could then insert text and images into either column.

**Comment by strarsis** [comment]
@jasmussen: I see potential in some plugins. For example, a plugin may provide a space where user can put content. Or even multiple spaces. The plugin could show them as blocks directly in editor where the block of the plugin is used - or instead in an option page, isolated from the main editor.

**Comment by maddisondesigns** [comment]
I mentioned in #1281 that it's currently impossible to add inline images into Text blocks. This makes it impossible to do something like the below image. This is critical. You **need** to be able to add images inline with your text.

![gutenberg-inlineimages](https://user-images.githubusercontent.com/2078245/28952821-2d320a86-7917-11e7-894f-08663f9fccdc.png)

**Comment by jasmussen** [comment]
@maddisondesigns See also #2042

**Comment by jasmussen** [comment]
One challenge that comes with nested blocks is the UI for the side controls — the movers, and the ellipsis. This is because those side controls either overlap or stack or create other unpredictable behavior, when they are floated or nested. See #3725, #3868.

**Solution idea 1**

First off — only allow the side controls to appear when the block has first been selected.

![nested block selected](https://user-images.githubusercontent.com/1204802/34555658-39a35236-f133-11e7-8fb3-a8db2f0ab3ee.png)

If we implement the hovering proposed in #3044, we could then show the movers and ellipsis when you hover near each side of the block:

![nested block hover left](https://user-images.githubusercontent.com/1204802/34555685-586fdc84-f133-11e7-9a92-ad5ed5e946f7.png)

![nested block hover right](https://user-images.githubusercontent.com/1204802/34555690-5b7a7b78-f133-11e7-86b8-0d83a394665a.png)

**Solution idea 2**

Mobile has a similar challenge to nested blocks in that it doesn't have room for side controls at all. For mobile we simply show those controls below the content of the blocks. We could do the same for nested blocks?

![nested block alternative](https://user-images.githubusercontent.com/1204802/34555844-31953360-f134-11e7-8bfb-6db3c570b8ab.png)

**Comment by melchoyce** [comment]
I like Solution 2 — feels cleaner overall.

Does the dark border denote a nested block?

**Comment by jasmussen** [comment]
Solution 2 would then be for _mobile_ and _nested blocks_, and only appear on select. I'm a fan too.

**Comment by melchoyce** [comment]
Thanks for clarifying 👍 From your mockups, the only difference would be the block controls. Can you talk a bit about your thoughts re: visually identifying which blocks are standalone, and which are nested? Do you have any plans to explore any additional visual indicators?

**Comment by jasmussen** [comment]
>  Can you talk a bit about your thoughts re: visually identifying which blocks are standalone, and which are nested? Do you have any plans to explore any additional visual indicators?

By "standalone" do you mean "top-level"? In any case, that's about as far as I've thought. All blocks in Gutenberg right now are top-level, but as soon as nesting lands, and the List block is rewritten to be a list block with nested list items, there's obviously UI challenges as discussed on this thread. I've also thought about how selecting and arrow-keys would work, and there's a bit on it on this new ticket: https://github.com/WordPress/gutenberg/issues/4382

Does that help?

**Comment by melchoyce** [comment]
> By "standalone" do you mean "top-level"? 

By "standalone," I meant a block that is not nested.

That helps, thanks 👍

**Comment by chrisvanpatten** [comment]
@ryancwalsh our [Text Accordion block](https://github.com/TomodomoCo/gutenberg-block-text-accordion) offers something like that. Take a look at the [editor](https://github.com/TomodomoCo/gutenberg-block-text-accordion/blob/master/src/block/editor.js#L41) and [render](https://github.com/TomodomoCo/gutenberg-block-text-accordion/blob/master/src/block/render.js#L44) components in particular. You could just replace the RichText with your non-editable title.

**Comment by ryancwalsh** [comment]
@chrisvanpatten That sounds promising, so thank you. I currently only know basic Javascript and don't recognize what I'm seeing [here](https://github.com/TomodomoCo/gutenberg-block-text-accordion/blob/df4bf6a9df0e4e41867062457a6f500fdf73db95/src/block/editor.js#L44) with these tags that aren't within strings. Is there some kind of special compiling setup I need? Does WordPress itself somehow handle these odd-looking JS files? Thanks.

**Comment by chrisvanpatten** [comment]
@ryancwalsh The example I sent uses JSX, which needs to be compiled (the instructions are in the README in that repo). Gutenberg does provide some back-compat for older JavaScript with the `el` function but I'm not super well-versed on the specifics of that. This might be a good place to start examining: https://github.com/WordPress/gutenberg-examples/blob/master/05-recipe-card/block.js

**Comment by ryancwalsh** [comment]
@chrisvanpatten Ok thanks. I'll read up at https://reactjs.org/docs/introducing-jsx.html.
