### ISSUE TITLE
Media & text block validation error from blocks in the pattern directory

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#42805]
### Description

Since https://github.com/WordPress/gutenberg/pull/40806 there is a block validation error for media & text block created before the pull request was merged. But the errors are specifically for media & text blocks in the pattern directory, and I am not able to reproduce it with local blocks.

### Step-by-step reproduction instructions

I used this method to test "local" blocks:

1. Deactivate Gutenberg. Activate Twenty Twenty-Two.
2. Using WordPress 6.0 or newer, go to either editor and add two media and text blocks:
one with media on the left, and one to the right. Save.
3. Activate Gutenberg trunk.
4. Refresh the editor where you placed the blocks.

You should see errors for block patterns in the block pattern directory if you open the browser developer tools console, but not for any of the blocks that are placed in the editor.

### Screenshots, screen recording, code snippet

[See screenshots in the discussion on the pull request.](https://github.com/WordPress/gutenberg/pull/40806#issuecomment-1193958784)

### Environment info

WordPress 6.0.1
Gutenberg current trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I think this is the issue with deprecation(s). Maybe they're not correctly applied in some cases.
