### ISSUE TITLE
Language and use of icons for template part and reusable block creation is inconsistent

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#42813]
<img width="288" alt="Screenshot 2022-07-29 at 12 50 45" src="https://user-images.githubusercontent.com/846565/181752826-4079a937-776b-4966-8472-8c0283e81516.png">

They should probably both (or neither) use an icon. 

Likewise we should use one of either "Add to...", or "Make...", for both. Or maybe try something else altogether like "Create...", "Add new...", etc.

**Comment by Mamaduka** [comment]
I like "Create..." and this will also match what the modal titles say.

**Comment by jameskoster** [comment]
This is fixed now :)
