### ISSUE TITLE
I think better to add code mirror in html Block .

### ISSUE THREAD

**Issue by sharazghouri** [WordPress/gutenberg#4281]
## Issue Overview

 word press providing us code mirror functionality  why we not add this functionality  in html block.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
Thanks for the suggestion, we already have this slated in #1733. I'll close this now and reference in that issue.
