### ISSUE TITLE
Block editor toolbar interferes with navigation editing(can't add links)

### ISSUE THREAD

**Issue by LukaszJaro** [WordPress/gutenberg#42822]
### Description

When I have the mobile menu always on and try to click it to open it and add links I am unable to. The block editor toolbar hovers on the mobile menu blocking the click event from occurring and obscures the view of the mobile menu. This also impacts other elements which are near the 'editor top bar' like the logo.

### Step-by-step reproduction instructions

1. Add navigation to very top of page
2. Select overlay menu to always
3. Remove any padding to bring the navigation close to the editor top bar(may not have to do this)

Note: This does not happen in the template part editor, only when trying to edit on a template editor

Relevant markup

`
<div class="wp-block-group has-primary-background-color has-background" style="padding-bottom:10px">
<div class="wp-block-group alignwide">

</div>

<div class="wp-block-group alignwide"></div>
</div>
`

### Unusable in template editor(can't click on mobile menu):

![image](https://user-images.githubusercontent.com/10998875/181787596-0e3a266e-6bbf-4b83-9bbe-c3e80b20f6c5.png)

### Usable in template PART editor:

![image](https://user-images.githubusercontent.com/10998875/181787812-9e11d771-808b-4516-9eb4-3648619c7390.png)

### Environment info

- WordPress 6.0.1
- Gutenberg plugin 13.7.1
- Windows 10, chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting, the problem was already flagged in #41575, so I'll close this as a duplicate.
