### ISSUE TITLE
Adding feature to control the button design when hovered

### ISSUE THREAD

**Issue by dev-sabbir** [WordPress/gutenberg#42829]
## What problem does this address?

At this point, we don't have any option to change the color of a button text/background on hover. We can add this feature to make the buttons more interesting.

## What is your proposed solution?

We can add a new section under the Color settings to control the colors when the button is being hovered.

**Comment by talldan** [comment]
Thanks for reporting this. Hover styles are being considered for most or all blocks. There's a discussion on https://github.com/WordPress/gutenberg/issues/27075, but actually probably more updates in https://github.com/WordPress/gutenberg/issues/38277.

I don't think it makes sense to open separate issues for individual blocks so I'll close this as a duplicate.
