### ISSUE TITLE
Popover arrow not working properly in the latest versions

### ISSUE THREAD

**Issue by renatho** [WordPress/gutenberg#42820]
### Description

Popover arrow is working well on WP 6.0, but when I activate the Gutenberg plugin (from the repository), it's not working properly anymore.

### Step-by-step reproduction instructions

The way to reproduce is through code.

1. In the editor, add a popover with the prop `noArrow={true}`.
2. Open it in an env with WP 6.0 and see it working properly.
3. Open it in an env with WP 6.0, and Gutenberg plugin ([trunk](https://github.com/WordPress/gutenberg/tree/ed5813c1325b8d6a09df7dd1bda00a8d90faf820)) activated, and see that it doesn't work properly anymore.

### Screenshots, screen recording, code snippet

Using WP 6.0 with Gutenberg plugin deactivated (working):

![](https://user-images.githubusercontent.com/876340/181547181-1d28cc44-a202-43ee-8573-56b7db2f7b09.png)

With Gutenberg ([trunk](https://github.com/WordPress/gutenberg/tree/ed5813c1325b8d6a09df7dd1bda00a8d90faf820)) plugin activated (not working):

![](https://user-images.githubusercontent.com/876340/181549113-9e4ea5da-9b87-49dd-8614-e12738cfb32f.png)

A case with Gutenberg plugin activated, with the Popover opening in the bottom (the arrow appears, but in a weird way):

<img width="442" alt="Screen Shot 2022-07-29 at 10 46 23" src="https://user-images.githubusercontent.com/876340/181774099-8c9644d9-7c1c-4b08-8ca1-fcf873a4f434.png">

A code snippet to test:

```js
<Popover noArrow={ false }>
  <div style={ { width: '400px', height: '400px' } }>
    Lorem ipsum
  </div>
</Popover>
```

### Environment info

- WordPress 6.0 with Gutenberg plugin activated ([trunk](https://github.com/WordPress/gutenberg/tree/ed5813c1325b8d6a09df7dd1bda00a8d90faf820)) in Chrome.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mirka** [comment]
Confirmed as a regression introduced in #40740.

This is reproducing in Storybook, as well as the only place in the Gutenberg codebase where `noArrow: false` is used, which is the Add New Template popover in the Site Editor (go to `/wp-admin/site-editor.php?postType=wp_template` and click the Add New button in the top right)

## Add New Template popover

### Before

<img width="408" alt="The popover arrow is styled correctly (white)" src="https://user-images.githubusercontent.com/555336/182060058-c240c365-1f40-4165-8e83-001a5069d410.png">

### After

<img width="362" alt="The popover arrow is styled incorrectly (grey and too small)" src="https://user-images.githubusercontent.com/555336/182060073-727cfb95-be50-45de-ba6f-027ec8577d1c.png">

**Comment by ciampo** [comment]
Tentative fix opened https://github.com/WordPress/gutenberg/pull/42874
