### ISSUE TITLE
LIST VIEW - option to keep it open toggle on off

### ISSUE THREAD

**Issue by TomasHurtz** [WordPress/gutenberg#42836]
Hey there

I find List View in the block editor extremely useful - and actually - pretty much essential to be able to clearly see where elements are sitting and interacting - so first off, 'good job' for having that feature, thank you.

However, I find that it randomly closes when executing certain tasks (for example, adding a new row) and it is rather annoying to keep having to re-enabling it.  

Could it be possible to have an option for the List View to remain 'permanently on' until toggled off?

**Comment by ramonjd** [comment]
Could you provide a screenshot/screencast that demonstrates the random closing? I can't seem to replicate it.

Just in case you didn't know, since https://github.com/WordPress/gutenberg/pull/40757 you can set a preference for the list view to open by default when you enter the editor.

**Comment by Thelmachido** [comment]
From what I could see the List View option only closes if you click on X on the top-right of the banner.

More information wasn't provided to see what the issue is exactly, I will close this issue for now.
