### ISSUE TITLE
Navigation block: New menu list view inconsistent

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#42856]
### Description

When I "create new menu" the links in the list view aren't updated:
<img width="1440" alt="Screenshot 2022-08-01 at 14 35 40" src="https://user-images.githubusercontent.com/275961/182159970-003dafbc-3672-4491-abe9-42a16a0fb8a7.png">
<img width="1440" alt="Screenshot 2022-08-01 at 14 35 31" src="https://user-images.githubusercontent.com/275961/182159981-99eca27e-90aa-42cd-af2d-4d7c0b784f5d.png">

### Step-by-step reproduction instructions

In a block theme with a navigation block,
- Open the list view so that you can see the list of items in the navigation block
- Click on "Create new menu" in the nav block
- Confirm that you still see the old nav items in the list view

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
https://user-images.githubusercontent.com/444434/189162332-b0c8535a-c0d1-4491-a799-c00008f4d75f.mp4

@scruffian I tested this and wasn't able to replicate. The List View updates perfectly.

**Comment by scruffian** [comment]
I can confirm this is now fixed.
