### ISSUE TITLE
Image and table block caption styles overrides theme.json elements.caption

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#42896]
### Description

If you style the caption element using theme.json, the styles work in the Site Editor but not on the front.
On the front, captions used with the image block and the table block displays with the default block styles.

### Step-by-step reproduction instructions

Add the following to theme.json, for example using Emptytheme:
```
{
	"version": 2,
	"styles": {
		"elements": {
			"caption": {
				"color": {
					"text": "red"
				},
				"typography": {
					"fontSize": "40px",
					"lineHeight": ".7"
				}
			}
		}
	}
}
```

1. In the site editor, add a table block with a caption and an image block with a caption. Do not change any other settings for the blocks.
2. Confirm that the correct color and size is used.
3. Next, please save and view the front.
4. Confirm that the block's default colors are used.

### Environment info

WordPress 6.0.1
Gutenberg current trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
The history of this issue is discussed in detail in #42054 and is still open.
Let's close this issue and focus the discussion on #42054 👍
