### ISSUE TITLE
Dynamic references in `theme.json` are not resolved in the site editor

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#42890]
### Description

We've introduced a new mechanism to refer to a different style dynamically at https://github.com/WordPress/gutenberg/pull/41696 which allows us to do things such as:

```json
"styles": {
    "color": {
        "background": { "ref": "styles.color.text" },
        "text": "yellow"
    }
}
```

In the example, the result would be that the text and background colors are the same (yellow).

![Captura de ecrã de 2022-08-02 12-29-40](https://user-images.githubusercontent.com/583546/182353781-3edcd351-ab71-44bc-a431-37ea35dbbf6f.png)

While this works in the front-end it doesn't in the site editor:

- the styles box does not render the background
- the color tools do not render the background
- the site editor breaks if the user tries to edit the background color 

| Styles | Color tools | Site editor
| --- | --- | --- |
| ![Captura de ecrã de 2022-08-02 12-28-19](https://user-images.githubusercontent.com/583546/182354271-0ca1b1b8-f1f4-4c66-9bb0-f423ceeb0dba.png) | ![Captura de ecrã de 2022-08-02 12-28-28](https://user-images.githubusercontent.com/583546/182354309-fd9c7310-baf0-46e8-a122-754c0e77804b.png) | ![Captura de ecrã de 2022-08-02 12-28-36](https://user-images.githubusercontent.com/583546/182354390-2c88d257-7d79-4d77-aeee-5e718fd7a13b.png) |

### Step-by-step reproduction instructions

- Use TwentyTwentyTwo theme and update the styles.color values to be: 

```
"background": { "ref": "styles.color.text" },
"text": "yellow"
```

- Go to the front-end and verify that it works as expected.
- Go to the site editor and open the Global Styles Toolbar. Click on Colors and then in the Backgound element. It'll throw an error.

### Environment info

I can reproduce this is `trunk`.

**Comment by oandregal** [comment]
A mechanism like this one should aim to expose the design links to the users. They need to understand where the value comes from so if they decide to "break" it it'll be a conscious decision. I ellaborated about this more at https://github.com/WordPress/gutenberg/pull/39432#issuecomment-1067964350

Though a first step is just to render the proper value and make the site editor look like the front-end.

**Comment by oandregal** [comment]
cc @scruffian

**Comment by Gierand** [comment]
A similar problem with the rendering of colors in the site editor occurs when you add root padding support in the settings.

```
"settings": {
   "useRootPaddingAwareAlignments": true
}
```
No error is generated, but no change is made during editing.

**Comment by Mamaduka** [comment]
Oh hey, @oandregal 👋 

I see that @scruffian has also created an issue for this bug - #42884. So let's close one of these.

**Comment by ndiego** [comment]
> A similar problem with the rendering of colors in the site editor occurs when you add root padding support in the settings.

I was able to replicate @Gierand's comment and have created an issue: #43033
