### ISSUE TITLE
Issue with backticks

### ISSUE THREAD

**Issue by JasonHoffmann** [WordPress/gutenberg#4290]
## Issue Overview
I'm running into an issue with the triple backtick (```) shortcut / fenced code blocks. In a paragraph block, if I type three backticks, it causes a bug where the backticks are overwritten by content, and do not create a code block. However, if I type three backticks (only one of which appears), then press "Enter" then "Backspace" a code block is created. A GIF is included below for clarity.

I didn't see this issue elsewhere, so I'm posting it.

## Steps to Reproduce (for bugs)
1. Create a new paragraph block
2. Try typing backticks, then other content to see issue with backticks and content
3. Create a new paragraph block again
4. Type the backtick three times. Hit "Enter". Hit "Backspace". A codeblock will be created but not focused.

This is on version 1.9.1 of the plugin. I've tested it in Firefox and Chrome on a Mac.

## Expected Behavior
Three backticks creates a code block.

## Current Behavior
A backtick causes issues with formatting instead.

## Screenshots / Video
http://g.recordit.co/ABMPrG7ifI.gif

## Related Issues and/or PRs
https://github.com/WordPress/gutenberg/issues/703

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521134738000759)._

**Comment by jorgefilipecosta** [comment]
Thank @JasonHoffmann for reporting this issue, the merge of https://github.com/WordPress/gutenberg/pull/5762 should fix it.
