### ISSUE TITLE
Gutenberg 13.7.3 - Smaller editor font size for some themes

### ISSUE THREAD

**Issue by masperber** [WordPress/gutenberg#42902]
### Description

In Gutenberg 13.7.x, the editor font size has been changed for some themes. (This does not affect font sizes on the live site.)

For example, in the Dara theme, the editor font size is now 16px, where it was previously 18px. It looks like the 18px size was previously being set by .editor-styles-wrapper  in 13.6.0, but that isn't the case in 13.7.x. The editor also isn't showing the correct font any more.

This has not yet been reproduced in another theme.

### Step-by-step reproduction instructions

1. Create a site on WordPress 6.0.1 and Gutenberg 13.7.3 using Dara theme and all default font settings
2. Editor font size is smaller in comparison to editor font size on Gutenber 13.6.0.

### Environment info

WordPress 6.0.1 (WordPress.com)
Gutenberg 13.7.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by dd32** [comment]
> This has not yet been reproduced in another theme.

Just noting that I've confirmed this on Make.WordPress.org, as a change between Gutenberg 13.6.0 & 13.7.0.
As reported here: https://wordpress.slack.com/archives/C02QB8GMM/p1659448511556299

**Comment by andrewserong** [comment]
Thanks for reporting!

Looks like the styles that aren't being output are the default editor styles, which are defined here: https://github.com/WordPress/gutenberg/blob/1ad7a0ba48358ae2b6ec340f9472defa0d112910/packages/block-editor/src/default-editor-styles.scss#L8 and then are flagged for output here: https://github.com/WordPress/gutenberg/blob/9f0e6be1c2ded47186ac4c009c798fa50d005177/packages/edit-post/src/editor.js#L178

As of https://github.com/WordPress/gutenberg/pull/40875, the base layout styles are now being output as part of the global styles output, so I believe we might need an updated check here to determine whether or not the `defaultEditorStyles` should be output? Not sure if that's the only thing going on with this issue.

I'll do a bit more digging, thanks to @glendaviesnz for flagging that it was related to that PR!

**Comment by andrewserong** [comment]
I think we can fix this on the PHP side when we output base layout styles for Classic themes. I've opened up a PR in #42906 with a potential fix.
