### ISSUE TITLE
Global Styles: display inline preview on per-block settings

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#42919]
When editing the global settings for a block in the "per block" section of styles, it'd be useful to render a preview at the top of the sidebar panel including the block example and how it's affected by the settings. This is relevant because global styles allows editing blocks that might not be present on the current page being previewed.

It currently looks like this:

<div align="center">
<img width="422" alt="image" src="https://user-images.githubusercontent.com/548849/182577122-89f496dc-4f16-4639-a26e-eb186ef96964.png">
</div>

Here's what a preview for Paragraph & Image could look like:

<img width="1032" alt="GS _ Blocks" src="https://user-images.githubusercontent.com/1204802/182621405-12247c5d-1e7f-45cc-87a5-57578b9b82f3.png">

* Same 152px height for the top level preview as that of the GS style card
* Uses the example content added for each block, but in cropped or curated (rather than zoomed) ways to show the correct font sizes applied

Upon diving deep into the structure, we can add a small preview button — the eye — to let you see a preview just like they work for style variations:

<img width="1032" alt="GS _ Blocks-1" src="https://user-images.githubusercontent.com/1204802/182621707-dfb9ea87-3635-40e1-abe4-ff5bf63fc8a1.png">

---

Issue was updated Sep. 28

**Comment by jasmussen** [comment]
A couple of quick mockups to start off the conversation: Paragraph & Image:

<img width="1032" alt="GS _ Blocks" src="https://user-images.githubusercontent.com/1204802/182621405-12247c5d-1e7f-45cc-87a5-57578b9b82f3.png">

* Same 152px height for the top level preview as that of the GS style card
* Uses the example content added for each block, but in cropped or curated (rather than zoomed) ways to show the correct font sizes applied

Upon diving deep into the structure, we can add a small preview button — the eye — to let you see a preview just like they work for style variations:

<img width="1032" alt="GS _ Blocks-1" src="https://user-images.githubusercontent.com/1204802/182621707-dfb9ea87-3635-40e1-abe4-ff5bf63fc8a1.png">

**Comment by jasmussen** [comment]
For anyone subscribed, this issue has been updated with design ready for a dev to pick up!

**Comment by noisysocks** [comment]
I'll plop this on my todo list since it's near to what I've been working on 🙂

**Comment by annezazu** [comment]
@noisysocks are you still planning to dig in here? Just doing a sweep of the various items on the phase 2 issue and wanted to ensure this was still assigned 💪🏼

**Comment by noisysocks** [comment]
Yes it's next on my list. Realistically I won't be able to start on it until 21 November. If there's a dev who has more immediate availability feel free to take it from me.

**Comment by priethor** [comment]
Thanks, @noisysocks ! I'm unassigning the issue for now so that it doesn't appear as taken pm the [Phase 2 board](https://github.com/orgs/WordPress/projects/56/views/1); feel free to reassign when you can start on it!

**Comment by madhusudhand** [comment]
@noisysocks @priethor I have created a very primitive version of the component here #45507 to demo box-shadow in live action. I will extract the code and create a Draft PR here.

**Comment by madhusudhand** [comment]
While #45719 addresses the Block Preview at Level 1, how shall it behave upon diving deep into the block structure?

<img width="754" alt="image" src="https://user-images.githubusercontent.com/1935113/201872010-6ef0c600-c0e1-4f4d-8f07-2372ddd191ae.png">

Questions to design: 
* Is it a pop over on click of 👁️  icon?
* if so, can it be pinned? 
(in scenarios such as box-shadow, having a live preview always visible is important to set right shadow values)

CC: @WordPress/gutenberg-design

**Comment by jasmussen** [comment]
Good question. In your box-shadow example ([fresh designs herer](https://github.com/WordPress/gutenberg/issues/44651#issuecomment-1313770873)), but also for a recent style variation example in #44417, it's actually useful to have that same top preview present not just on level 1 but on all levels. 

Would it be possible to keep this preview on all those sub-levels as a starting point, omit the eye for now, and then we can evaluate how that works and see if we need the eye after all?

**Comment by mtias** [comment]
> Would it be possible to keep this preview on all those sub-levels as a starting point, omit the eye for now, and then we can evaluate how that works and see if we need the eye after all?

Let's get the preview for the top level first merged, then follow up with the sub-levels.
