### ISSUE TITLE
Wide/full alignment controls always show in post editor even if Post Content block has no content width

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#42911]
### Description

If a Post Content block has no content width set, its direct children, the top-level blocks in the post editor, should not show the 'wide' and 'full' alignment controls. Currently, these are shown for all top-level blocks, regardless of whether Post Content has content width set or not. 

If Post Content has no content width set, a top-level block set to wide width in the post editor will seem to display correctly, because core editor styles are applied, but it will look broken in the front end.

The issue seems to be that the post editor doesn't have an awareness of the settings of the parent block where the post content will be rendered, so instead it looks at whether `themeSupportsLayout` to decide what layout settings to give to its children. 

### Step-by-step reproduction instructions

1. Enable Empty Theme;
2. In the Site Editor, go to the Singular template;
3. In the Post Content block, toggle on "Inner blocks use full width" in the sidebar Layout section;
4. Save and go to post editor;
5. Add a new block with alignment (e.g. Group) to a post;
6. Verify that "full" and "wide" alignment options appear for that block;
7. Set the block alignment to "wide", save and compare editor appearance with front end.

### Screenshots, screen recording, code snippet

Editor:
<img width="1174" alt="Screen Shot 2022-08-03 at 6 02 02 pm" src="https://user-images.githubusercontent.com/8096000/182558367-100f0443-2777-40b1-b37d-6db41e136c54.png">

Front end:
<img width="1252" alt="Screen Shot 2022-08-03 at 6 03 15 pm" src="https://user-images.githubusercontent.com/8096000/182558418-371154f2-8e7d-41b3-82bb-434a6edbced7.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
There is a related issue open in https://github.com/WordPress/gutenberg/issues/44110 for the justification of post content.

I'm wondering if an ideal fix for both of these issues would be to see if it's possible to (somehow) extract the Post Content block that is in use in the currently selected template for the post being edited, and use those attributes in the styling of the post editor. That way, if a site has many different kinds of templates, switching between them could (in theory) update the presentation of the block editor to more closely align to how the post will look on the site frontend. This would only apply for blocks-based themes, of course.

Not sure how do-able that is (or performant if it means parsing the template), but might be worth exploring!
