### ISSUE TITLE
Navigation block: Move "Select Menu" to the sidebar

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#42924]
Once https://github.com/WordPress/gutenberg/pull/42735 merges we should move the old placeholder functionality (Create new menu and select menu) to the sidebar.

<img width="876" alt="Screenshot 2022-08-03 at 12 15 20" src="https://user-images.githubusercontent.com/275961/182595137-ac26ef16-e4a0-42c1-859e-dcb85aa621c1.png">

The "Select menu" option should also move to the sidebar:

<img width="1440" alt=" " src="https://user-images.githubusercontent.com/275961/182594599-ee98c4e4-f12c-43b0-99da-e60f63562b49.png">

**Comment by getdave** [comment]
Seems duplicate of https://github.com/WordPress/gutenberg/issues/42602 @scruffian

**Comment by scruffian** [comment]
Yes, sorry, closing.
