### ISSUE TITLE
Block columns markup broken in Wordpress 6

### ISSUE THREAD

**Issue by AndyTyZed** [WordPress/gutenberg#42923]
### Description

Hi. My website is made up of 2 and 3 columns. It's written in the code editor using valid markup taken directly from Guttenberg visual editor. 

But ever since Wordpress 6, the styling for block columns no longer works. This is despite source code showing that the  `<link rel='stylesheet' id='wp-block-library-css'...`  is being fetched.

 This breaks my entire site of over 300 articles by merging all columns into one big mess. The markup I used was taken directly from the block editor and worked in several previous Wordpress versions. 

### Step-by-step reproduction instructions

Here is a test page which demonstrates the issue https://www.washerhelp.co.uk/columns-issue_test/

Note this is not the site affected because I have had to revert back to Wordpress  5.9.3 and cannot udate Wordpress until this is resolved. This is another of my sites running wordpress 6 that is unnafected because it only has one page.

### Environment info

- Wordpress 6 running Astra Pro theme 3.9.1
- Problem occurs in 4 different themes, Twenty Twenty-Two, Astra, plus 2 Genesis themes. Also, with all plugins disabled, and all caches cleared.
- Tried adding block column css into custom CSS and child theme's css, but for some reason Wordpress doesn't use it
- Source code of affected pages also show that `<link rel='stylesheet' id='wp-block-library-css'` is being called 

The markup I use, is markup directly generated by Guttenberg block editor in previous versions of WordPress. I went to the visual editor, created 2 columns, and then switched to code editor, and copied the following markup -

```<div class="wp-block-columns">
<div class="wp-block-column">

</div>
<div class="wp-block-column">

</div>
</div>
```

I then just built all future pages, pasting that into code editor and adding content. It works in all previous versions of WordPress - but not in 6. So something has changed that breaks previously valid markup.

What I have noticed is that current markup created by wordpress for columns encloses all the previous markup in <!.. remarks. And it is _specifically_ the omission of these remarks that breaks the pages.

However, I believe WordPress would never have deliberately done this? 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by AndyTyZed** [comment]
For some reason the markup I quoted isn't showing despite enclosing it into the code markup but it can of course be seen in the source code of the example page I linked to.

**Comment by carolinan** [comment]
Hi!
The markup you have copy pasted into the issue does not include the CSS classes that WordPress relies on for styling. Secondly the HTML tags are not nested correctly. _I don't think this example HTML matches what is on the example link._

The problem with copying the markup instead of using the block is that the markup is missing the unique CSS class that WordPress **generates for each block** and then uses to apply the CSS.
The markup is not intended to be used that way.
Is there a reason why you can't use the actual block instead of using custom HTML? I'd like to understand.

This is the markup for a columns block created today:

```
<div class="wp-container-3 wp-block-columns">
<div class="wp-container-1 wp-block-column"></div>
<div class="wp-container-2 wp-block-column"></div>
</div>
```
The `wp-container-number` is the unique identifier for the block. This class is missing from your HTML, and it is the class WordPress applies the CSS to, depending on the block settings:

```
.wp-container-3 {
    display: flex;
    gap: 2em;
    flex-wrap: nowrap;
    align-items: center;
}
```

**Comment by AndyTyZed** [comment]
Many thanks for your prompt reply. Something went wrong with the example that I tried to paste in, it's not showing it all fully.  Please see instead attached screenshot - 
![Block columns markup broken in Wordpress 6](https://user-images.githubusercontent.com/110168327/182622496-58ccc34f-4f59-45fe-969c-ab2b121331d8.png)

I have 300 articles on my main site (the one that I am unable to update to WordPress 6), and every single article uses the exact same markup. I've used this markup for at least 18 months. It still works perfectly okay in WordPress 5.9.3, and all previous versions.

This is just one example that is currently live, and columns are padded and spaced perfectly fine -
https://www.whitegoodshelp.co.uk/white-goods-right-to-repair/

I'd like to reiterate that this entire markup was generated by WordPress. All I did was copy it, and then paste into new articles, building them up using the code editor. Surely the point of the code editor is for people to build pages by typing in markup old school style? :)

When I create new pages, I use the visual editor. But my major problem is that I have these 300 live articles that are still using this older columns markup and I can't see how I can "fix" them all, and therefore upgrade to WordPress 6.

I hate to make a long post, but maybe an explanation as to how I got into this mess may be helpful? My websites have been on WordPress since 2007. I historically always used Genesis. And to create my 2, and 3 column pages I used markup that was provided by Genesis. 

About a year or so back, I ditched Genesis in favour of Astra Pro. However, when I installed Astra Pro, the markup for 2 and 3 columns that was proprietary to Genesis no longer worked. In effect, I had exactly the same problem that I have now. The only way I could think to fix it, was to create a new page using Gutenberg editor in visual mode. I created 2 columns, and then underneath it I created 3 columns..

I then switched to code editor, and there was the markup that WordPress had created (exactly as shown in my screenshot above). So I was able to use a search and replace plug-in to simply replace all of the previous Genesis markup, with this new markup created by WordPress.

It worked a treat, and as you can see from my link above, it is still working today, but only on WordPress 5.9.3.

The reason I cannot use the same fix this time, is that the only fix I can find is to replace all of the previous WordPress markup with the markup that currently uses loads of <!..> remarks, and it is much more complicated to try and search and replace because it would involve searching for end divs markup and encasing them in the remarks but of course not every end div on my pages is related to a column. 

![Block columns NEWER markup](https://user-images.githubusercontent.com/110168327/182626819-ba3281af-a16c-4ac1-884b-1cc76c4761fb.png)

So what I am completely at a loss to is what has changed in WordPress 6 that prevents pages rendering with styling for columns if it is not all encased in these remarks, which Wordpress did not use before, and I always believed were purely remarks and not actual code. It makes no sense that styling for valid markup is only carried out if it has remarks surrounding it?

And of course is this something that WordPress will fix? Or is there a clever workaround? 

Andy

**Comment by carolinan** [comment]
You can add custom CSS to the wp-block-columns and wp-block-column classes, and that might work, but I think you will keep running into this problem with each WordPress update.

**Comment by carolinan** [comment]
What CSS to add depends on what settings you used when you created the block that you copied from.

**Comment by AndyTyZed** [comment]
> You can add custom CSS to the wp-block-columns and wp-block-column classes, and that might work, but I think you will keep running into this problem with each WordPress update.

Many thanks. My intention is that once I have found a workaround, I can upgrade to WordPress 6, and then over a period of months slowly recreate every page using WordPress visual editor.

Do you have any idea why  wp-block-columns work perfectly okay in WordPress 5, but has no styling in WordPress 6 unless the markup is enclosed in <!...> remarks?
I'm convinced this is an unexpected consequence of some changes that were made in WordPress 6? And that I am very much in a minority in having been affected by it because of the unusual circumstances I described in my last reply?

Someone suggested that I add the following CSS to custom CSS, which I have done, and expected to work, but it doesn't.

`.wp-block-columns {
  display: flex;
  margin-bottom: 1.75em;
  box-sizing: border-box;
  flex-wrap: wrap !important;
  align-items: initial !important;
}
@media (min-width: 782px) {
  .wp-block-columns {
    flex-wrap: nowrap !important;
  }
}
.wp-block-columns.are-vertically-aligned-top {
  align-items: flex-start;
}
.wp-block-columns.are-vertically-aligned-center {
  align-items: center;
}
.wp-block-columns.are-vertically-aligned-bottom {
  align-items: flex-end;
}
@media (max-width: 781px) {
  .wp-block-columns:not(.is-not-stacked-on-mobile) > .wp-block-column {
    flex-basis: 100% !important;
  }
}
@media (min-width: 782px) {
  .wp-block-columns:not(.is-not-stacked-on-mobile) > .wp-block-column {
    flex-basis: 0;
    flex-grow: 1;
  }
  .wp-block-columns:not(.is-not-stacked-on-mobile) > .wp-block-column[style*=flex-basis] {
    flex-grow: 0;
  }
}
.wp-block-columns.is-not-stacked-on-mobile {
  flex-wrap: nowrap !important;
}
.wp-block-columns.is-not-stacked-on-mobile > .wp-block-column {
  flex-basis: 0;
  flex-grow: 1;
}
.wp-block-columns.is-not-stacked-on-mobile > .wp-block-column[style*=flex-basis] {
  flex-grow: 0;
}
:where(.wp-block-columns.has-background) {
  padding: 1.25em 2.375em;
}
.wp-block-column {
  flex-grow: 1;
  min-width: 0;
  word-break: break-word;
  overflow-wrap: break-word;
}
.wp-block-column.is-vertically-aligned-top {
  align-self: flex-start;
}
.wp-block-column.is-vertically-aligned-center {
  align-self: center;
}
.wp-block-column.is-vertically-aligned-bottom {
  align-self: flex-end;
}
.wp-block-column.is-vertically-aligned-top, .wp-block-column.is-vertically-aligned-center, .wp-block-column.is-vertically-aligned-bottom {
  width: 100%;
}

`

It makes no sense because that CSS _is_ styling the wp-columns?

**Comment by carolinan** [comment]
I don't understand. I don't think it will be possible for me to help you any further without seeing the actual code and the site.
You may need to contact Astra support again because it is difficult to know what code you are actually using.

Are you saying that adding the comment `<!...>` to the HTML in your PHP template file solves the issue on the front?

**Comment by carolinan** [comment]
The block editor uses the comment to store block data, block settings, in JSON format. That format is then parsed and not printed on the front.
But I am not aware of markup being parsed **as a block** for the front unless you are actually using the do_blocks() function for your HTML in your PHP template.
https://developer.wordpress.org/reference/functions/do_blocks/

**Comment by Humanify-nl** [comment]
@AndyTyZed I've been reading through this and I have a few thoughts:

**Copy-pasting editor code**
You state here that you copied the block code from the editor and pasted it just 'as is'. 

> I then switched to code editor, and there was the markup that WordPress had created (exactly as shown in my screenshot above).

This is a little hard to believe because it should have included the WP markup, which I don't see in your example. This markup has been there earlier, before 6.0. So unless you did this way before 5.8, something went wrong.

Example of pasted block markup for a columns block:
```
<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"backgroundColor":"grey-light"} -->
<div class="wp-block-column has-grey-background-color has-background"><!-- wp:heading {"level":3} -->
<h3>Col-50</h3>
<!-- /wp:heading --></div>
<!-- /wp:column -->
```
I'm pretty sure something went wrong if only the 'html' markup is pasted without the `<!-- -->` Without this, the editor can't properly parse your columns and can not add the CSS needed, or have access to changing stuff with the block controls.

> Surely the point of the code editor is for people to build pages by typing in markup old school style? :)

This assumption is wrong. Block markup should not be typed manually without knowing exactly what to do. The code editor is there to fix errors in the code or remove things that the editor didn't put there in the first place.

The fact that 'it worked' in earlier versions is lucky at most. The workings of block markup are well documented, so expecting it should work differently is not helping you.

**What is not working?**
What is the actual problem on your columns? Obviously the block spacing is wrong (but what else?). In WordPress 6, the columns have had changes in their spacing, which is now done by gap instead of adding margins.

Try add this to your CSS to make your temp solution work.

```
.wp-block-columns {
  gap: var(--wp--style--block-gap);
}
```

Lastly, and please don't take this the wrong way. Doing 300 pages with block editor and using search-replace to replace quite sensitive code, is - from a developer perspective - bad practice. Especially with a new block editor and limited knowledge of how this thing works.

If this doesn't work, I'd advise hiring a WordPress developer to come up with a solution that works for you _and_ with the new block editor paradigm. Because as @carolinan already stated: This problem is not going away and painstakingly fixing 300 pages manually and then having to do it again next update is the full reason why developers exist.

**Comment by carolinan** [comment]
OK, I am definitely confused what you copied the code *into*.

If you copied it from the code editor to the code editor without including the comment, it will be interpreted as a custom HTML block and it will not work as a column, just a div.

**Comment by carolinan** [comment]
There are two code editors.
One in the block editor, for the individual post or page that you have open. Here you need to include the code comment, and everything is a block.

And the "theme file editor" under the tools menu. Formerly this editor was under the appearance menu. Here you change the themes css files, JS files, and templates like index.php.

**Comment by AndyTyZed** [comment]
Many thanks for all your replies. It's very much appreciated..

I can confirm that yes, I definitely created the 2 and 3 columns in the WordPress block editor about 9 months ago. I then switched to code editor (in the block editor) and copied the markup, which definitely did not contain _any_ remarks at all. I used this markup successfully until Wordpress 6 and it is still working in Wordpress 5.9.3 - despite the fact that Wordpress 5.9.3 also creates the columns markup with those remarks. It just still process it OK without the remarks.. 

I started my website 22 years ago, and hand coded it in HTML and CSS. I then moved over to WordPress in 2007, and I have 4 WordPress websites, so I have quite a lot of experience working inside WordPress too. So I'm not an expert in WordPress, nothing like you guys, but I am relatively experienced.

Thanks for the information about JSON. That's the first time I've had any explanation as to why the styling is not used without the remarks. However, I still don't have an explanation as to how doesn't seem possible for me to just add the styling inside custom CSS and let WordPress treat my markup as custom div's with the block columns styling?

On that note, I am speculating that maybe it is for some reason related to the fact that I am using the official `wp-block-columns` divs name. I wonder if I changed their names to something like `MY-block-columns` then WordPress would respect my markup and styling? I could easily do that with my search and replace plugin.

**Comment by Humanify-nl** [comment]
The CSS supplied by your theme works. All that is not working is the gaps. Right?

Using gap in custom CSS should work (as I supplied it above).

![column-gap](https://user-images.githubusercontent.com/82579622/182819056-e9e1153b-8ded-4b97-903d-abdc4046213d.gif)

I would not change it to `my-block-columns` because then everything breaks (max-width, margins etc), that is supplied by your theme css.

**Comment by AndyTyZed** [comment]
> The CSS supplied by your theme works. All that is not working is the gaps. Right?
> 
> Using gap in custom CSS should work (as I supplied it above).

Yes, thank you, it's only the gap between columns that is lost. So if I do a search and replace for all references of `<div class="wp-block-columns"` and change it to  `<div class="wp-block-columns" style="gap: 2rem;">` that should do it?

**Comment by Humanify-nl** [comment]
That could work.

Although it's recommended to use the 'regular' CSS way by adding it to the bottom of your style.css stylesheet. So you have an easy way to change this if needed without touching the actual html, and without the need to search/replace.

```
.wp-block-columns {
  gap: var(--wp--style--block-gap);
}
```

**Comment by AndyTyZed** [comment]
> That could work.
> 
> Although it's recommended to use the 'regular' CSS way by adding it to the bottom of your style.css stylesheet. So you have an easy way to change this if needed without touching the actual html, and without the need to search/replace.

It works! Many thanks. I tried both methods and both work, but your CSS one is much better. I can also see why adding the previous css to custom CSS didn't work, because it didn't have the "gap" element.

This is still surely an oversight in Wordpress 6 though? It's not retro supporting its own previously valid markup before they changed to relying on the remarks?

**Comment by AndyTyZed** [comment]
I just added the CSS, and then upgraded to Wordpress 6. Everything seems OK :) Many, many thanks.

I'm just wondering how long has Wordpress been relying on all of the remarks to process markup properly? I'm wondering if by any chance I did remove the remarks and just forgot that I did? In writing HTM and XHTML for over 20 years, I'd never heard of remarks being anything other than "remarks" to clarify the markup. I still find it bizarre that they are processed like markup in Wordpress but I can see that it is now. 

So it's possible I would have been so convinced they were not needed but honestly dont remember. It still stands though that WordPress 5.9.3 renders the columns perfectly OK without the remarks, but Wordpress 6 does not.

**Comment by Humanify-nl** [comment]
You're welcome!

The block editor is currently very in development and breaking changes are expected, especially if you make a big jump from before 5.8 to 6. 

Here is the explanation of parsing by html comments. It is actually very smart and allows a lot of cool stuff.
https://developer.wordpress.org/block-editor/explanations/architecture/data-flow/#serialization-and-parsing
