### ISSUE TITLE
Navigation block: Use a standard inserter

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#42922]
### Description

The block inserter on the navigation block looks quite different to other blocks:
<img width="1099" alt="Screenshot 2022-08-03 at 11 47 01" src="https://user-images.githubusercontent.com/275961/182590587-e019a60b-0be7-4b52-8ece-b6b0c406b28b.png">

It should probably look consistent with other blocks, like this:
<img width="1097" alt="Screenshot 2022-08-03 at 11 50 54" src="https://user-images.githubusercontent.com/275961/182590885-cf58cd94-58c7-40cd-8f32-86672f213da7.png">

### Step-by-step reproduction instructions

1. Add a navigation block
2. Click on Select Menu > Create new menu

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by javierarce** [comment]
After https://github.com/WordPress/gutenberg/pull/43115 the inserter looks like this now:

<img width="694" alt="Screenshot 2022-08-24 at 14 34 30" src="https://user-images.githubusercontent.com/4933/186419469-5fd24493-2ccc-4f30-9824-64d9964a328a.png">
