### ISSUE TITLE
Site Logo Block: when set as Site Icon, W menu doesn't update

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#42943]
### Description

After updating to 13.8, when adding a site logo block, adding a logo, and setting it to "use as site icon" the W menu doesn't reflect the change. Instead, it continues to just show the WordPress logo. cc @priethor @Mamaduka

### Step-by-step reproduction instructions

1. Go to Appearance > Editor.
2. Add a Site Logo block.
3. Add a logo.
4. In the block settings for the Site Logo block, toggle on the "Use as site icon" option.
5. Notice that the site icon updates but the W menu/navigation component doesn't update. 

### Screenshots, screen recording, code snippet

<img width="1443" alt="Screen Shot 2022-08-03 at 11 41 47 AM" src="https://user-images.githubusercontent.com/26996883/182651189-686ec218-b9bf-458c-bdde-81b48a9186b9.png">

### Environment info

- WordPress 6.0.1
- Gutenberg 13.8

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I can reproduce the same issue on 13.7, so probably not a new regression.

**Comment by carlomanf** [comment]
We discussed this in #38555 and #38575 and discovered that this same issue occurred when the Gutenberg plugin was inactive. Can someone confirm whether the work here has any impact on that?

**Comment by Mamaduka** [comment]
@carlomanf, the issue exists in WP 6.0 as well. This change needs to be backported into the core for a fix.

**Comment by carlomanf** [comment]
We were finding the issue in version 5.9 actually. Just want to verify if that is also your understanding?

**Comment by annezazu** [comment]
@gziolo want to flag this as consideration for 6.0.2. @carlomanf curious to hear more about what you were/are seeing with 5.9?

**Comment by carlomanf** [comment]
@annezazu According to https://github.com/WordPress/gutenberg/issues/38575#issuecomment-1032366385 the site icon failed to show up in core version 5.9 if the gutenberg plugin was inactive, and only showed up if the gutenberg plugin was active. Not sure of the behaviour pre-5.9.

**Comment by annezazu** [comment]
Ah thank you! This should make it into 6.0.2 so hopefully we can get this fixed once and for all :)
