### ISSUE TITLE
 Full-width blocks alignment don't match in the editor

### ISSUE THREAD

**Issue by renata-franco** [WordPress/gutenberg#42945]
### Description

When adding several blocks inside the editor and changing them to Full-Width, some of the blocks show padding on the sides. 

### Step-by-step reproduction instructions

1. On a Jetpack-connected site install and activate the Twenty Twenty Two (or Blockbase, or Twenty Nineteen) theme.
2. Add a Cover block, Slideshow block and Gallery block to a new post (using the wp-admin post editor or the WordPress.com editor)
3. Set the alignment within all three blocks to full-width.
4. The display should look fine on the live post or in preview, but in the editor there is some padding to the left and right of the Cover and Gallery blocks, but not the Slideshow block.
5. Change the theme to Twenty Twenty, and check the post editor. There should now be some padding to the left and right of the Slideshow block, but not the other two blocks.

### Screenshots, screen recording, code snippet

This is on a self-hosted site, with Twenty Twenty-Two theme, looks like this:

![image](https://user-images.githubusercontent.com/81378719/182656145-ba1a145e-f7e2-4695-8121-92aaa1b8621e.png)

### Environment info

- WordPress 6.0.1
- Gutenberg 13.8.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Thanks for the report, @renata-franco! Could you please confirm that Jetpack is only needed to repro the issue with the Slideshow block, otherwise Jetpack is not needed to repro the issue with the Cover & Gallery blocks? Thanks!

**Comment by renata-franco** [comment]
> Thanks for the report, @renata-franco! Could you please confirm that Jetpack is only needed to repro the issue with the Slideshow block, otherwise Jetpack is not needed to repro the issue with the Cover & Gallery blocks? Thanks!

It needs to have Jetpack connected because the Slideshow Block is not available if Jetpack is not active. I just tested this on a self-hosted site that does not have Jetpack active and Slideshow is not available to try it out. The test on this site was with the same theme, Twenty Twenty-Two and the padding looks normal: 

![imagen](https://user-images.githubusercontent.com/81378719/183286849-a76b4e79-e9d3-4364-a68a-3eac28f44601.png)

**Comment by ramonjd** [comment]
It looks the editor and frontend match when setting the width to 'full' for the Cover block and Gallery block. The Slideshow block is added by Jetpack and the issue has been reported there. https://github.com/Automattic/jetpack/issues/25305
