### ISSUE TITLE
WP-Scripts: Do not apply jest eslint rules if cypress is installed.

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#42952]
## What problem does this address?

Using WP-Scripts in combination with Cypress for E2E testing will result in false positives for Jest related rules as the Jest config is unable to pick up Cypress assertions.

## What is your proposed solution?

Test for Cypress and disable to Jest rules if the package is installed. This is a similar approach to that taken for Playwrite 

https://github.com/WordPress/gutenberg/blob/88899c885e44757f7554b7a8d01f3d20650deb0c/packages/eslint-plugin/configs/recommended-with-formatting.js#L49-L52

### Alternative

A configuration option in `package.json` or `eslintrc.json` to prevent the Jest config from being included. This will allow the package to be managed generally rather than via snowflake rules for various set ups.

For the time being I have added the following to my config file but it doesn't seem optimal:

```json
{
  "extends": [ "plugin:@wordpress/eslint-plugin/recommended" ],
  "rules": {
		"jest/no-disabled-tests": 0,
		"jest/no-focused-tests": 0,
		"jest/no-identical-title": 0,
		"jest/prefer-to-have-length": 0,
		"jest/valid-expect": 0,
		"jest/expect-expect": 0
  }
}
```

**Comment by gziolo** [comment]
At the moment, the Gutenberg project uses both Jest and Playwright for e2e tests. I see that other projects might use other tools, so I believe the best way to move forward would be to make that support fully optional. In effect, we would have to remove those lines:

https://github.com/WordPress/gutenberg/blob/eb6b3ff23a58c18019b66814606f594e86711c85/packages/eslint-plugin/configs/recommended-with-formatting.js#L59-L63

We should also document better existing rulesets in case someone wants to use the one for e2e we are about to disable:

https://github.com/WordPress/gutenberg/tree/trunk/packages/eslint-plugin#rulesets

**Comment by gziolo** [comment]
#43272 should resolve the issue.
