### ISSUE TITLE
Navigation Block: user set styles doesn't work consistently in editor and live site

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#42963]
### Description

User changes to Navigation menu are not properly applied in editor and live site.
It happens for the properties that are defined in `theme.json` for `core/navigation-link` because they gain higher specificity in some cases.

## Initial observations

| Category | Property |  Editor | Frontend |
| --- | --- | --- | --- |
| Colors | background | styles applied because the variables are given `!important` | styles applied |
|  | text color | styles applied | styles applied |
| Typography | font-size | doesn't apply | styles applied because the variables are given `!important` |
|  | font-family | styles applied only to menus having submenu | styles applied only to menus having submenu |
|  | text transform | styles applied only to menus having submenu | styles applied only to menus having submenu |

### Step-by-step reproduction instructions

Define the theme.json for navigation link as follows.

```
"core/navigation-link": {
  "typography": {
	"fontFamily": "var(--wp--preset--font-family--jost)",
	"letterSpacing": "0.05em",
	"fontSize": "var(--wp--preset--font-size--tiny)",
	"textTransform": "uppercase"
  }
}
```

Try to override these settings in the editor such as `font-size`, `font-family` or `case`

**Editor**
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/1935113/182791483-1e503235-2812-4edb-ae8f-cdc82ff00207.png">

**Live Site**
<img width="916" alt="image" src="https://user-images.githubusercontent.com/1935113/182792473-06989abd-66f2-4524-b27d-a8b6e56a38ce.png">

Observe that the they both look different.

### Environment info

- WP 6.0
- Gutenberg: 13.8
- Theme: any

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
The setting in the screenshot is only for the navigation block. As far as I understand it is correct that if the navigation link is styled, then the settings on the parent must not override the navigation link styles.

>Try to override these settings in the editor such as font-size, font-family or case

I am not 100% **when** the options were added to the navigation link block, it might have been after you created this issue. Would you be able to test this again? But with the correct navigation link block selected, not the parent navigation block.

**Comment by ndiego** [comment]
Hi @madhusudhand. This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg and WordPress. Would you be able to try retesting, there have been a bunch of improvements made to the Navigation blocks in the last few months. 

That said, I also wanted to note the difference between the `core/navigation-link` and `core/navigation-submenu` blocks in theme.json. For link visual consistency across a navigation menu, it's often a lot easier to just apply typography settings to the parent block, which in this case would be `core/navigation`. Hope that helps.

**Comment by madhusudhand** [comment]
Hi @ndiego, Thanks for details on the context. 
I verified the issue again with latest Gutenberg and it is working as per the given expectations.

However I have the following perspective on how the menus and sub-menus should be working.

| Current | expectation (My perspective) |
| --- | --- |
| <img width="834" alt="image" src="https://user-images.githubusercontent.com/1935113/199914348-0f11fde7-f5a9-4c11-8aab-dfe9e12cc76f.png"> | <img width="834" alt="image" src="https://user-images.githubusercontent.com/1935113/199914530-a4faff60-6a51-4001-aed8-1ed7da0da03b.png"> |

To me it feels like, everything from L1 should always behave as a link. 
One of the link might have more links under it and the container holding all those links is the sub menu. 
Any styling applied to submenu, I would expect them to get applied to the containing links not the parent link itself.

I would like to imagine a scenario where my website has only flat menu first, and then I decide to include nested levels.
In this case I wouldn't expect my main links to get effected by any theme styles, because it is a data change.

However when theme has styles defined for `nav-link`, that one link having sub-links looks different and it forces me to define styles for submenu to match.

This is still an issue with the above expectation is the right way for the navigation. 
Otherwise with the current behaviour, I can confirm it works good.

**Comment by bph** [comment]
@madhusudhand Glad that your issue seems to be resolved. 

Your discussion on sub-menus is quite interesting and valid. Nice comparison and visuals!  
It probably should be separate into a new issue, so it gets more developers to chime in. The navigation blocks seem to be still in flux and your thoughts would be worth discussing. 
I am afraid, no many people will see beyond. "It's fixed with latest Gutenberg".

**Comment by madhusudhand** [comment]
> It probably should be separate into a new issue, so it gets more developers to chime in.

Created #45878 to discuss further on the sub-menu behaviour. closing this as resolved.
