### ISSUE TITLE
Social icons block: add rel=me option

### ISSUE THREAD

**Issue by Ainali** [WordPress/gutenberg#42977]
## What problem does this address?
A common way to self verify that you are the owner of a linked website on some social media (for example on Mastodon) is to add the attribute rel=me on the links to that platform from the website. It would be very nice to have that as an option in the social icons block.

## What is your proposed solution?
In the **Link settings** on the Social icons block, add a switch that, when enabled, adds the attribute `rel="me"` to the links.

**Comment by skorasaurus** [comment]
thanks for reporting; rel customization has been requested at https://github.com/WordPress/gutenberg/issues/38630

Please follow that issue and subscribe for further updates.

**Comment by georgeh** [comment]
I've created #45469 to address this
