### ISSUE TITLE
Categories List block: CSS classes inconsistency in the list

### ISSUE THREAD

**Issue by dashkevych** [WordPress/gutenberg#42984]
### Description

The editor displays the following CSS classes in the list of the block:

`wp-block-categories__list wp-block-categories__list-level-0`

The website displays the following CSS classes in the list of the block:

`wp-block-categories-list wp-block-categories`

### Step-by-step reproduction instructions

1. Go to the Widgets screen
2. Add Categories block
3. Publish changes

I used default WordPress theme with support for widget areas: Twenty Twenty One

### Screenshots, screen recording, code snippet

Editor:
![Category block in the editor](https://i.snipboard.io/HRED7w.jpg)

Website:
![Category block on the actual website](https://i.snipboard.io/9TVqBO.jpg)

### Environment info

Fresh WordPress installation:
 
- Twenty Twenty One theme (Version: 1.6)
-  WordPress (Version:  6.0.1)

No plugins.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@dashkevych 
Thank you for submitting the issue.
I have submitted #43666 to bring the markup on the block editor in line with the front end.
I believe this PR will solve the problem.
