### ISSUE TITLE
Enhancement: set border-color as a variable instead of hex code in Code Block

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#42995]
## What problem does this address?
Similar to: https://github.com/WordPress/gutenberg/issues/36462

In WordPress 6.0.1, when you choose one of the colors from the color palette to set it as the `border-color` of the Code Block,

1. in the Editor, the `border-color` is set as a **variable** in the Code Block. ✔️

![image](https://user-images.githubusercontent.com/90872910/182956241-ba0415f7-f8ff-479e-b4cf-f170314f339a.png)

2. in Global Styles, the `border-color` is set as a **hex color** in the Code Block. ❌

![image](https://user-images.githubusercontent.com/90872910/182956305-310001f2-cd68-4765-890d-e3d9f5f33a18.png)

## What is your proposed solution?
Border-color coming from Global Styles to be set as a CSS variable in the Code Block.

**Why?**
Allows full site editing to change border-colors without needing to individually change every instance of the Code Block to update to the new border-color.

### Please confirm that you have searched existing issues in the repo.

Yes

**Comment by glendaviesnz** [comment]
If you add a custom color to your palette in global styles and use this to set the border color this will be applied as a variable:

<img width="1027" alt="Screenshot 2023-04-13 at 11 27 06 AM" src="https://user-images.githubusercontent.com/3629020/231607694-6e4f2887-fd0e-407e-a647-484645aa4b41.png">

Going to close for now as reporting user has been deleted.
