### ISSUE TITLE
Enhancement: solid colors from the palette in gradient control points

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#43006]
## What problem does this address?
Currently, it is not possible to choose solid colors from the palette when editing a gradient control point.

The benefit of doing this would be to inherit the solid colors CSS variables inside the gradient value:
`background: linear-gradient(135deg, var(--wp--preset--color--black) 0%, var(--wp--preset--color--white) 100%)`

Themes achieve this scenario via theme.json, and it remains impossible via the Editor.

## What is your proposed solution?
Possibility to set solid colors from the palette in gradient control points.

![image](https://user-images.githubusercontent.com/90872910/182995646-e455465a-b6b8-47f8-a6c2-abb760a3634c.png)

### Please confirm that you have searched existing issues in the repo.

Yes

**Comment by glendaviesnz** [comment]
Verified that this still is not possible in the editor.

**Comment by glendaviesnz** [comment]
Going to close for now as the suggesting user has been deleted and I am not sure how critical this is as it can be handled from theme.json. Feel free to re-open if you think it is an enhancement worth keeping in the backlog.
