### ISSUE TITLE
Support for RustLang on Codeblocks

### ISSUE THREAD

**Issue by nednoodlehead** [WordPress/gutenberg#43001]
There is a large amount of languages supported, some even obscure, I find it mildly disappointing that there is no support for one of the most important languages in the next few years: Rust.

**Comment by carolinan** [comment]
Hi!
Did you mean a third party block?
The WordPress code block does not support or validate any language, it only "Display code snippets that respect your spacing and tabs."

**Comment by nednoodlehead** [comment]
I mean the syntax highlighting in code blocks, I forgot to mention that in the original request. My bad

**Comment by carolinan** [comment]
The code block does not support any syntax highlighting.

**Comment by talldan** [comment]
@nednoodlehead As mentioned, the features are most likely added by a plugin, I'd recommend working out which one and making an enhancement request to the plugin developer. 👍
