### ISSUE TITLE
Tag cloud block alignment issue in editor as well as front end side 

### ISSUE THREAD

**Issue by theminaldiwan** [WordPress/gutenberg#43016]
### Description

In twenty twenty two theme when we add Tag cloud block And set the center alignment to block but taxonomies are still in left alignment but center alignment not working.

### Step-by-step reproduction instructions

1)Activate the Twenty Twenty-Two theme.
2)Add the tag cloud block and select taxonomies from list
3)Now set the center alignment. You can see it will not be in center alignment.

### Screenshots, screen recording, code snippet

![CleanShot 2022-08-05 at 13 06 15](https://user-images.githubusercontent.com/38693713/183026752-b81fa6ac-2425-48e1-b958-46c3b37c72fb.jpeg)

### Environment info

- WP : 6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi!
I am not able to reproduce this. I tested in WordPress 6.0.1 with and without Gutenberg active.
How are you providing the custom taxonomy?
Asking because you mentioned that there were no other plugins active. Can you provide any more details on how to reproduce this?

**Comment by carolinan** [comment]
**_Aha_** -can you test if you see any difference if you choose the default style instead of "outline" ?
