### ISSUE TITLE
Explore a dark style for the editor

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4302]
I'm making this issue and self assigning as going to explore what a dark option could look like. We may not add this, it's just an experiment.

**Comment by danieltj27** [comment]
This is something that we've [branched off](https://github.com/danieltj27/Dark-Mode/tree/gutenberg) for the Dark Mode feature-plugin. Do you think it's better to explore this in the Dark Mode plugin or leave it to Gutenberg? Both are hookable so it's either or I suppose. Just wanted to let you know this is something I prepared for as I knew this would be something to discuss at some point.

The issue to track [a darker Gutenberg style](https://github.com/danieltj27/Dark-Mode/issues/43) was also created for discussion. Let me know what you think. Would like to contribute to this in some way if I can.

**Comment by karmatosed** [comment]
I think I'd like to also explore this to run a test in how needy our CSS is. However, having options with what others are doing is always most welcome. Thanks for working on the dark mode plugin.
