### ISSUE TITLE
Use the underlying block icon for reusable blocks in the inserter

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#4303]
Currently, reusable blocks appear in the inserter with a mosaic icon:

<img width="364" alt="screen shot 2018-01-05 at 09 47 31" src="https://user-images.githubusercontent.com/612155/34587701-8b097220-f1fd-11e7-9a01-86ab0b067d99.png">

It would be nicer if they appeared with the icon of the block that was converted:

<img width="367" alt="screen shot 2018-01-05 at 09 46 44" src="https://user-images.githubusercontent.com/612155/34587722-a9f46672-f1fd-11e7-82ff-28d4740eaff5.png">

**Comment by karmatosed** [comment]
This is a good improvement we can make. It stops the default iconitis we are suffering from in certain areas.
