### ISSUE TITLE
useRootPaddingAwareAlignments prevents color changes in Global Styles from displaying in the Site Editor

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#43033]
### Description

When you enable the new `"useRootPaddingAwareAlignments": true` feature, changing colors in the Site Editor are no longer actually reflected in the Site Editor. They do appear on the frontend.

### Step-by-step reproduction instructions

1. Use Twenty Twenty-Two and Gutenberg 13.8+
2. Set `"useRootPaddingAwareAlignments": true` in theme.json
3. Change the background color of the site in Global Styles to another color. See that the color does not change in the Site Editor. 
4. Save your changes and see that the color has been changed on the frontend. 

### Environment info

- WordPress 6.0.x 
- Gutenberg 13.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Gierand** [comment]
@ndiego Please check https://github.com/WordPress/gutenberg/issues/42913

**Comment by ndiego** [comment]
Ahh, thanks @Gierand. Completely missed that!
