### ISSUE TITLE
Colors with opacity values not editable in Styles

### ISSUE THREAD

**Issue by ellenbauer** [WordPress/gutenberg#43041]
### Description

Block themes can set rgba or hex color with opacity (Hexadecimal colors) in theme.json.

In the block editor these color values can be edited as the color picker has the opacity setting, as seen in the screenshot below.

<img width="588" alt="Screen Shot 2022-08-06 at 11 57 07 AM" src="https://user-images.githubusercontent.com/17613630/183224834-430a031a-26a1-4b84-ad97-1a7c91b201e7.png">

In Styles the color values can not be edited, which can be considered a bug, I feel. The opacity setting is not available and it is not possible to add the needed 8 values to the hex color settings, e. g. #FF000033 for the color red with 20% opacity.

Before editing the color in Styles:

<img width="382" alt="Screen Shot 2022-08-06 at 11 58 25 AM" src="https://user-images.githubusercontent.com/17613630/183224901-56c4f94d-7ee6-42ab-8628-a338765ef44d.png">

After trying to change the color value but keeping the 33 for opacity:

<img width="470" alt="Screen Shot 2022-08-06 at 11 59 27 AM" src="https://user-images.githubusercontent.com/17613630/183224978-7518f8e2-7aed-4a2b-89a0-e412c2d6a48b.png">

### Step-by-step reproduction instructions

1. I would expect the same color settings in both editors.

2. At least the hex value could allow 8 numbers, so the opacity could be maintained in the color value.

### Environment info

Wordpress 6.0.1
Theme Aino
Gutenberg plugin 13.8.1 
Gutenberg plugin deactivated causes the same behaviour

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by marceloaof** [comment]
https://github.com/WordPress/gutenberg/issues/42999

**Comment by ndiego** [comment]
@ellenbauer and @marceloaof when you have a chance, give #43045 a test and see if that resolved these issues. Thanks!

**Comment by ellenbauer** [comment]
@ndiego Amazing, Nick, I will test tomorrow, so exciting!!!

**Comment by ellenbauer** [comment]
This works for me 😍 thanks so much for providing this solution @ndiego
