### ISSUE TITLE
Will there ever be a field to write your custom styles on each block?

### ISSUE THREAD

**Issue by dan-zakirov** [WordPress/gutenberg#43043]
I’ve seen such a plugin, like this [https://gutenberghub.com/wp-content/uploads/2020/08/Image-2020-08-03-at-5.56.41-PM-1024×508.png](https://gutenberghub.com/wp-content/uploads/2020/08/Image-2020-08-03-at-5.56.41-PM-1024x508.png), but I would like to see this functionality in Gutenberg itself

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/30142 (specifically https://github.com/WordPress/gutenberg/issues/30142#issuecomment-1199112589) . Feel free to [add your reaction](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/participating-in-a-discussion#about-participation-in-a-discussion) and follow its progress in the issue.
