### ISSUE TITLE
The "Fix toolbar to block" option is a bit unclear

### ISSUE THREAD

**Issue by WPprodigy** [WordPress/gutenberg#4306]
## Issue Overview

The terminology on this setting seems a bit strange to me. Enabling the option called "Fix toolbar to block" ends up removing the contextual toolbars, while disabling it (when there is no checkbox next to the setting) adds in the toolbar above blocks.

I would expect an option with this name to enable contextual toolbars, not remove them.

I see there were previously some string changes discussed in https://github.com/WordPress/gutenberg/pull/3311#issuecomment-341404278 and later implemented, but the master branch at least doesn't include these: https://github.com/WordPress/gutenberg/blob/master/editor/edit-post/header/fixed-toolbar-toggle/index.js#L27

I tried re-adding the quick fix changes, but it still doesn't feel quite right. Clicking "Fix toolbar to block" when it already has a checkmark by it seems like that's the setting already enabled: http://cld.wthms.co/F0rLz3

So I'm thinking the best quick fix would really just be to use one set of text and make sure the icon shows up in a logical way. Either reversing when the icon shows up now, or going with the actual name of the feature which would be "Fix toolbar to top".

## Steps to Reproduce
<img width="264" alt="settings1" src="https://user-images.githubusercontent.com/8536129/34592556-f31c1cb6-f192-11e7-9200-2d6bec6d6884.png">

and 

<img width="303" alt="settings2" src="https://user-images.githubusercontent.com/8536129/34592557-f32cd13c-f192-11e7-8986-daa683e3f918.png">

**Comment by sampatronak** [comment]
Hey
