### ISSUE TITLE
Upgrade @wordpress/element to React 18

### ISSUE THREAD

**Issue by mdmag** [WordPress/gutenberg#43077]
Hi WordPress team,
We built [Quill Forms](https://github.com/quillforms/quillforms) project as an open source Typeform alternative for WordPress based on React and Typescript.
We have a lot of inspiration from Gutenberg project especially with the blocks concept.
We support React community as well but recently, we have issues from our users that our form doesn't work with React 18.
When I investigated the issue, I found that the reason for that is that there are 2 versions of React. React 18 and `@wordpress/element` comes with React 17. 
Would it be a problem if WordPress team upgraded React to version 18?
There shouldn't be any breaking change.
Hopefully, the team could consider this.

**Comment by Mamaduka** [comment]
Here's an in-progress PR #32765, but we're waiting for the mobile team #40695.

**Comment by masteradhoc** [comment]
@Mamaduka this seems to be done right? Think could be closed :)
