### ISSUE TITLE
[Documentation] Broken Internal Link

### ISSUE THREAD

**Issue by SavPhill** [WordPress/gutenberg#43078]
### Description

Broken internal link in the documentation when visiting https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#icon at line 254.

### Step-by-step reproduction instructions

Go to: https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#icon
Click on internal url titled: wp.primitives.SVG which leads to: https://developer.wordpress.org/block-editor/reference-guide/packages/packages-primitives/src/svg/.

This leads to a 404 page. 

Is there an alternative page we can use as a replacement? or should we remove the link temporarily.

Looking for a solution, I could only find: https://developer.wordpress.org/block-editor/reference-guides/packages/packages-primitives/ as the closest replacement

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for contributing, @SavPhill.

The suggested URL looks like a suitable replacement 👍
