### ISSUE TITLE
5.0

### ISSUE THREAD

**Issue by EUFELIPEPIMENTEL** [WordPress/gutenberg#43097]
### Description

up

### Step-by-step reproduction instructions

ok

### Screenshots, screen recording, code snippet

ok

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, there is not enough information in the post to act upon; could you please edit with the relevant information?

**Comment by talldan** [comment]
I'll close this. Feel free to submit a new issue if you can provide more information.
