### ISSUE TITLE
Cover image as featured image + "Fixed background" duplicates the style element.

### ISSUE THREAD

**Issue by Gierand** [WordPress/gutenberg#43092]
### Description

Adding a cover image as featured image with the "Fixed background" option duplicates the style element, which will result in the following code on the frontend:

`<div class="wp-block-cover is-light has-parallax" style="background-image:url(PATH_TO_IMAGE);" style="margin-top:111px">`

### Step-by-step reproduction instructions

1.  Create a new post.
2. Add featured image.
3.  Add cover block as featured image.
4. In Media settings check "Fixed background".
5. Add any custom styles (margin or padding).

### Environment info

WordPress version: 6.0.1 and 6.1-alpha-53771
Gutenberg version: 13.8.1 and 13.9.20220808
Theme: TT2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by draganescu** [comment]
This is where the solution in #42128 shines and the discussion in #42485 is a turning point for this: having one way to handle block rendering (with a tokenizer or not) would prevent these mistakes.

Also: tested and confirmed the bug. Wish I'd have tested this earlier :)

**Comment by akasunil** [comment]
Cant regenerate it now. I believe this issue is resolved. @draganescu Can we close this issue ?

**Comment by draganescu** [comment]
@sunil25393 I can't repro this either. @Gierand I'll close this but feel free to reopen if the problem persist for you.
