### ISSUE TITLE
FSE: Navigation with sticky header as option

### ISSUE THREAD

**Issue by hagege** [WordPress/gutenberg#43108]
## What problem does this address?
For most users it is difficult and also not in the sense of FSE, if you create a sticky header with CSS e.g. at the navigation at a block theme like TT2. Sticky header we already use frequently on some WordPress instances we created as development environment. 
See also the survey by Brian Gardner here: https://twitter.com/bgardner/status/1555990916812398592

![sticky_header](https://user-images.githubusercontent.com/27292550/183830160-9feaf20d-e99f-4147-8413-50263dde513e.jpg)

## What is your proposed solution?
This should - if possible - better be offered as an option at the navigation block.

**Comment by talldan** [comment]
There's some discussion already about fixed/sticky headers/footers/navigation in https://github.com/WordPress/gutenberg/issues/30121.

I'll close this as a duplicate.

**Comment by hagege** [comment]
sorry - I must have overlooked that, although I was looking for it.

**Comment by paaljoachim** [comment]
Hey @hagege 

It is very easy to overlook this specific Navigation block sticky feature as the title of the issue I added it to says: [Fixed Position Header and Footer Template Parts](https://github.com/WordPress/gutenberg/issues/30121#issuecomment-1190118058). 
@critterverse perhaps we should rename the issue to focus more on general fixed/sticky options in the Block editor?
