### ISSUE TITLE
 Gutenberg: long HTML anchors make the list view take a lot of space 

### ISSUE THREAD

**Issue by renata-franco** [WordPress/gutenberg#43125]
### Description

When adding long HTML anchors to a block in the Advanced settings, the list view in the editor takes more and more space on the screen. Originally reported here: https://github.com/Automattic/wp-calypso/issues/66300

### Step-by-step reproduction instructions

1. Add a block
2. Open the list view
3. Go to block settings > Advanced > HTML anchor
4. Add a long anchor text
5. Notice the width of the list view getting bigger

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/81378719/183943195-d310c95e-4c81-4040-a9e6-a494a334a210.mp4

### Environment info

- Gutenberg Version 13.8.0.
- WordPress  6.0.1.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I think this is a regression after #41855. Probably this line:

https://github.com/WordPress/gutenberg/blob/c3f19c4a6cc16dce050855b49cea1421bbb46e3d/packages/block-editor/src/components/list-view/style.scss#L320

cc @andrewserong

**Comment by andrewserong** [comment]
Oh, thanks @Mamaduka, I'll take a closer look.

**Comment by andrewserong** [comment]
I've opened up a potential fix in #43134
