### ISSUE TITLE
Multi-select seems harder to invoke

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#4312]
This seems to have worked very well in the past, but feels like it's regressed, not quite sure. But it seems like it's harder to invoke multi select across paragraphs. More notably so when many of those paragraphs are empty placeholders:

![multi select from placeholder](https://user-images.githubusercontent.com/1204802/34605069-4aca03ac-f20a-11e7-9920-6b29a2adecf0.gif)

It seems like any mouse dragging operation on the page should _always_ invoke multi select when started from a non-focused textarea, and if a textarea has focus it should invoke after dragginb across the boundaries.

**Comment by mtias** [comment]
This seems to be just an issue with the sibling inserter grabbing the event.
