### ISSUE TITLE
Schema for theme.json uses Gutenberg version for Core

### ISSUE THREAD

**Issue by johnstonphilip** [WordPress/gutenberg#43128]
### Description

The schema at https://schemas.wp.org/trunk/theme.json seems to be redirecting to Gutenberg's schema. 

That means there are things in the "core" schema that aren't actually released yet, like `fluid` currently, for example. 

These 2 should probably be separate so that beta/unreleased features in gutenberg are not shown as being available/stable when they are not. 

### Step-by-step reproduction instructions

1. Go to https://schemas.wp.org/trunk/theme.json
2. Notice it redirects you to https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/theme.json

**Comment by johnstonphilip** [comment]
Am I incorrect in thinking that "trunk" does not include Gutenberg?

**Comment by Mamaduka** [comment]
The `trunk` will always point to the latest version of the schema, including new features that are only shipped with the Gutenberg plugin.

To target specific WP versions, you can use the following URLs:

* https://schemas.wp.org/wp/5.9/theme.json
* https://schemas.wp.org/wp/6.0/theme.json

Related issue: #37974.

**Comment by johnstonphilip** [comment]
@Mamaduka Cool. #37974 Covers my concerns here. Closing.
