### ISSUE TITLE
Blue inserter line does not appear before first block or after last block

### ISSUE THREAD

**Issue by aaronjbaptiste** [WordPress/gutenberg#43127]
### Description

When trying to drag a block before the first or last in a list no blue inserter line is visible, even though the drop/move is applied.

This applies to both the root container and other containers such as horizontal orientation column layouts.

This was previously reported here #32880 and I believe fixed in #33024, but has possible regressed.

It's particularly troublesome on Gutenberg's implementation on Tumblr when managing image layouts.

### Step-by-step reproduction instructions

1. Create three paragraph blocks - Item A, Item B, Item C.
2. Try to drag item B above item A - notice there's no blue indicator line.
3. Try to drag item B below item C - also no indicator.

### Screenshots, screen recording, code snippet

On Wordpress:
![dragging](https://user-images.githubusercontent.com/3449340/183944761-ffa55b46-1b0c-4258-8dde-71c950264dac.gif)

On Tumblr:
![topbottom](https://user-images.githubusercontent.com/3449340/183948615-51f03dcb-abc0-4c18-b6e7-c3661df01a0b.gif)

Horizontal containers on Tumblr:
![image-layouts](https://user-images.githubusercontent.com/3449340/183947838-55eca2a7-f583-43ae-bf09-1b5704333e3b.gif)

### Environment info

Mac OS 12.4
Chrome 103.0.5060.134 

Wordpress:
Gutenberg: v13.8.1
Editing Toolkit: 3.38921
WP AMP: 2.0.5
CoBlocks: 2.18.1-simple-rev.2 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting. This has already been reported in #32880, so I'll close this one as a duplicate.

**Comment by talldan** [comment]
> This was previously reported here https://github.com/WordPress/gutenberg/issues/32880 and I believe fixed in https://github.com/WordPress/gutenberg/pull/33024, but has possible regressed.

Just read this. I think it's fine to still use #32880 and leave a comment on there mentioning it has regressed.

**Comment by talldan** [comment]
Issue should be fixed as of #43135
