### ISSUE TITLE
Theme.json: dynamic references, avoid recursive references

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#43154]
### Description

[Pointed out](https://github.com/WordPress/gutenberg/pull/42976#issuecomment-1209582853) in #42976, the editor crashes when there's a recursive reference in place.

### Step-by-step reproduction instructions

In theme.json add:

```
"color": {
    "background": { "ref": "styles.color.text" },
    "text": {"ref": "styles.color.background" }
},
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
I have a fix for this. Just writing some tests and will push a PR soon.
