### ISSUE TITLE
Permalinks displaying post IDs when in drafts and scheduled.

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#43161]
### Description

Permalinks are displaying the plain post ID instead of the edited URL in drafts and when scheduled to be published at a later date.

Is there a way to display the URL without clicking on "URL" to preview it?

### Step-by-step reproduction instructions

1. Create a new post.
2. Add a new title and then save it in draft, or schedule to publish at a later date.
3. Click on the URL to edit the permalink.
4. URL still shows the post ID instead of the permalink.

### Screenshots, screen recording, code snippet

![Markup on 2022-08-11 at 10:47:07](https://user-images.githubusercontent.com/27249804/184202396-149f0d12-3853-460b-9e26-bf32d8332967.png)

### Environment info

- WordPress Version 6.0.1
- Gutenberg Version 13.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
Should we do something like this: https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-url/index.js#L105? 

@noisysocks, @Mamaduka do you remember if there was a reason for not handling these two url in the same way?

**Comment by Mamaduka** [comment]
I can't recall any specific reason, but I agree that the matching button and popover link labels make sense.

I'm going to assign it to myself and push updates shortly.

**Comment by Mamaduka** [comment]
The PR is ready for review #43600.
