### ISSUE TITLE
get_current_screen in "current_screen" action has incorrect post type

### ISSUE THREAD

**Issue by vuvvn** [WordPress/gutenberg#4317]
There is a function "gutenberg_collect_meta_box_data" in gutenberg/lib/register.php that calls set_current_screen. That sets the current screen to be of "post" type. That call overrides the "get_current_screen" function results and initiates "current_screen" action. And within that action the current screen is of "post" type, not the original type of the post currently being edited. So within the other post types (e.g. attachments) the current_screen thing provides false information.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1516901860000468)._

**Comment by bobbingwide** [comment]
I believe this is the same as #4772  for which there is an open PR.

**Comment by youknowriad** [comment]
Closing as duplicate, let's consolidate in #4772
