### ISSUE TITLE
Compiled block styles contain a lot of trash

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#43173]
### Description

All block styles contain ~75 lines of comments which are not needed. For example you can take a look at https://github.com/WordPress/WordPress/blob/master/wp-includes/blocks/buttons/style.css
These comments get added to all non-minified stylesheets and they don't make any sense.

We should remove comments when these styles are getting compiled.
These files should not be minified, but all comments should still be getting removed.
I think we'll be able to do that by changing this function a bit... https://github.com/WordPress/gutenberg/blob/eb6b3ff23a58c18019b66814606f594e86711c85/tools/webpack/shared.js#L73-L94

The result would be smaller styles in the WordPress package, and easier to read/debug source code in pages

**Comment by aristath** [comment]
From my testing this seems to work:
```js
const stylesTransform = ( content ) => {
	return postcss( [
		require( 'cssnano' )( {
			preset: [
				'default',
				{
					discardComments: {
						removeAll: true,
					},
					normalizeWhitespace: mode === 'production',
				},
			],
		} ),
	] )
		.process( content, {
			from: 'src/app.css',
			to: 'dest/app.css',
		} )
		.then( ( result ) => result.css );
};
```

What do you think @gziolo ?

**Comment by Mamaduka** [comment]
This is odd. In plugin I see the stylesheets correctly compiled in the `build/block-library` directory.

Maybe this is an issue with core side transformations.

**Comment by aristath** [comment]
> This is odd. In plugin I see the stylesheets correctly compiled in the `build/block-library` directory.
> 
> Maybe this is an issue with core side transformations.

When running `npm run build` they get minified, yes. But when running `npm run dev`, they have the extra comments - and all those somehow get ported to Core 🤷

**Comment by gziolo** [comment]
Does it mean that we run CSS processing for usage with WordPress packages in development mode?

I don't know that part of the workflow that well so whatever you figure out to fix the issue in core is fine.

**Comment by Mamaduka** [comment]
I think we should set `discardComments` config here - https://github.com/WordPress/wordpress-develop/blob/trunk/tools/webpack/shared.js#L62-L64

**Comment by gziolo** [comment]
For some styles, we should keep the comments with licenses when code was copied from other projects. Example:

https://github.com/WordPress/gutenberg/blob/c416bf8f028974d56de902d597fa6bc2b814f9a9/packages/components/src/date-time/date/datepicker.scss#L1-L28

**Comment by Mamaduka** [comment]
We can use `!` marker for those comments - https://cssnano.co/docs/optimisations/discardcomments/.

**Comment by aristath** [comment]
Thank you both for the feedback!
I opened https://core.trac.wordpress.org/ticket/56388 and added a patch there :+1:

**Comment by Mamaduka** [comment]
I'm going to close this in favor of the core ticket.

**Comment by aristath** [comment]
Reopening this one. The Gutenberg PR on https://github.com/WordPress/gutenberg/pull/43177 needs to be merged in order for the tests to stop failing in the Core PR 😅
