### ISSUE TITLE
Global styles: Heading color options present in Button styles panel

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#43192]
If you navigate: Styles > Blocks > Button > Colors, you will see options to set the text/background color of Headings. Since you cannot place Headings inside Buttons this feels a bit out-of-place.

https://user-images.githubusercontent.com/846565/184385263-038fa302-d457-4651-b7c0-6bb024cefc52.mp4

**Comment by carolinan** [comment]
It is not only on the button but on [any block that has color options.](https://github.com/WordPress/gutenberg/pull/42176#issuecomment-1201060165)

**Comment by carolinan** [comment]
How can we improve this? 
Is there a way to create an allowed list, and only include the option if the block is on that list?
And can that list be automated, so that we do not need to update it repeatedly?
Or perhaps a check if the block allows inner blocks?

**Comment by jameskoster** [comment]
This is no longer an issue :)
