### ISSUE TITLE
Pullquote block: font settings from theme.json are overriden by block styles

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#43194]
### Description

The font settings from a theme's theme.json file such as font size and line height are being overridden by the default block styles.

### Step-by-step reproduction instructions

1. Set emptytheme to discard other styles problems.
2. Add a pullquote block to a post
3. Change the font settings for the pullquote block in your theme `theme.json` file
```
	"styles": {
		"blocks": {
			"core/pullquote": {
				"typography": {
					"fontSize": "3rem"
				}
			}
		}
	}
```
4. Check that the font size is not applied because is overridden by the default CSS definition of the block.
	

### Environment info

- WordPress 6.0.1
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by justintadlock** [comment]
This also affects the line-height.

For more context, the font-size is used, but the inner `<p>` style uses a relative unit for it:

```css
.wp-block-pullquote p {
	font-size: 1.75em;
	line-height: 1.6;
}
```

Right now, theme authors have to kind of "hack" this by calculating what `1.75em` is relative to whatever size that they actually want and defining that in `theme.json`.

**Comment by matiasbenedetto** [comment]
@justintadlock This recently merged PR (https://github.com/WordPress/gutenberg/pull/4319) should fix this, so I'm closing this issue. Feel free to re-open it if this is still a problem using the latest Gutenberg trunk version.

**Comment by justintadlock** [comment]
@matiasbenedetto Thanks for the update.  I'm pretty sure you meant to reference #43195.  It definitely seems to be working now.
