### ISSUE TITLE
Query loop infinite loop when inheriting query from template

### ISSUE THREAD

**Issue by ebinnion** [WordPress/gutenberg#43198]
### Description

This originally presented as a bug on WordPress.com where pages would not load at all in some occasions and was reported here:

https://github.com/Automattic/wp-calypso/issues/66270

High-level, the issue is that in #40656 we changed how we handled the inherit query from template logic. Instead of pulling args out of the template query and then creating a new query object. We actually began to use the template query.

When we then call `have_posts` and hit the end of the loop within the block rendering, this resets the query while we're still in the block, and we're never able to pass the `have_posts` check in the template.

### Step-by-step reproduction instructions

See https://github.com/Automattic/wp-calypso/issues/66270#issuecomment-1209752872

### Environment info

- Tested against most recent 13.8.1 as well as 13.8.0
- Presents in WordPress.com and self-hosted sites.
- Presents when using the Gutenberg plugin combined with a non site editor theme, such as TwentyTwentyOne

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by priethor** [comment]
I can consistently reproduce the issue in a self-hosted site with WordPress 6.0.1, Gutenberg 13.8.2, and different classic themes.

**Comment by priethor** [comment]
I'm leaving myself a reminder to add the `Backport to WP minor release` label to future PRs that solve this issue. ✍️
