### ISSUE TITLE
wp-env Including Plugins with Query Parameters Causes Error

### ISSUE THREAD

**Issue by titusdmoore** [WordPress/gutenberg#43199]
### Description

Including plugins from outside URL that includes Authentication string (aws) causes `Invalid or unrecognized source: ...` error when starting the environment. This is caused when using download strings with authentication query parameters post `.zip` in the url.

### Step-by-step reproduction instructions

1. Create `wp-env.json` file in a valid WordPress Project
2. Add url under plugins with authentication query parameters (mine is gravity forms)
3. Run wp-env start

### Screenshots, screen recording, code snippet

```
{
  "core": null,
  "port": 8383,
  "phpVersion": "8.0",
  "themes": ["."],
  "plugins": [
    "https://downloads.wordpress.org/plugin/custom-post-type-ui.1.12.1.zip",
    "https://s3.amazonaws.com/gravityforms/releases/gravityforms_2.6.5.zip?AWSAccessKeyId={tokenHere}&Expires={expires}&Signature={signature}"
  ],
  "env": {
    "tests": {
      "port": 8384
    }
  }
}
```

### Environment info

- Node 14.20.0 && Node 16.15.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by noahtallen** [comment]
By the way, this is now available in wp-env v5.2.0
