### ISSUE TITLE
Classic Block: Switch to HTML and again to Visual Mode Converts Content to Blocks

### ISSUE THREAD

**Issue by La-Geek** [WordPress/gutenberg#43209]
### Description

Switch back to "Edit Visually" brings you not back to Block Classic but converts the content so several blocks.

### Step-by-step reproduction instructions

1. New post
2. Insert Block Classic
3. Write or paste content with more than 1 paragraph
4. Switch Block Classic to `Edit as HTML`
5. Click now on `Edit visually`
6. The Block Classic is gone instead the content is converted to blocks
7. Hit undo/redo and click in the content field
8. The content is absolutely deleted

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1585416/184506958-3225bc8e-a84c-4d0e-9cb8-75e4afbd84cb.mp4

### Environment info

WP 6.0.1
Gutenberg 13.8.2
Theme 2022

Nothing else installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
From my testing, it seems to only happen when clicking the 'Edit visually' option on the toolbar.

If you click the 'Edit visually' option in the dropdown, that works ok:
![Screen Shot 2022-08-15 at 11 55 23 am](https://user-images.githubusercontent.com/677833/184574556-2d671f47-9819-4f1e-ad85-583aa1d270d7.png)

I'm not sure why there are two options.

Does that match with what you're seeing @La-Geek?

**Comment by talldan** [comment]
I've put a fix together in https://github.com/WordPress/gutenberg/pull/43219.

**Comment by La-Geek** [comment]
@talldan 
yes, the option exists twice.
