### ISSUE TITLE
register_block_style: `inline_css` not loaded into iframe editor instance

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#43250]
### Description

The inline style is defined with `register_block_style`, its CSS is not loaded in iframe editor instance.

### Step-by-step reproduction instructions

- Defines the following code in `functions.php`:
```php
register_block_style(
	'core/button',
	array(
		'name'         => 'test',
		'label'        => 'Test',
		'inline_style' => '.wp-block-button.is-style-test { border: 2px red solid }',
	)
);
```

- Open the post editor and insert the button block.
- Apply "Test" style and confirm that a red border has been applied to the button.
- Confirm that the style disappears when you change to mobile tablet view.
- Confirm that the same problem is occurred in the site editor.

### ✅ Frontend

![frontend](https://user-images.githubusercontent.com/54422211/184826603-535c5995-06d5-4977-847e-05e9521070ca.png)

### ✅ Post Editor

![post-editor](https://user-images.githubusercontent.com/54422211/184826669-625546ba-2f14-497b-8457-c3272f7c5ad3.png)

### ❌Post Editor (Mobile/Tablet View)

![post-editor-mobile](https://user-images.githubusercontent.com/54422211/184826858-735c5ed6-90ea-4117-b447-1d3191ea4a24.png)

### ❌ Site Editor

![site-editor](https://user-images.githubusercontent.com/54422211/184826903-6172b64a-bc9c-4878-bd64-28cf3735baa5.png)

### ✅ Post Editor

The style defined in `inline_css` is correctly added as `wp-block-library-inline-css`.

![post-editor-css](https://user-images.githubusercontent.com/54422211/184827272-05f7b41a-0d16-4c5b-86c4-c638c00b4842.png)

### ❌ Site Editor

Styles defined in `inline_css` aren't added to `wp-block-library-inline-css`.

![site-editor-css](https://user-images.githubusercontent.com/54422211/184827427-f1d8f944-31e8-4fc3-afea-537a1c19956a.png)

### Environment info

- WordPress Version: 6.0.1
- Gutenberg Version: 13.9.0-rc.3
- OS: Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Andrew-Starr** [comment]
Possibly related issue - https://github.com/WordPress/gutenberg/issues/39944

**Comment by Mamaduka** [comment]
Thanks for the comment, @Andrew-Starr.

It is the same issue. The `inline_style` aren't loaded in iframed editors, which is also used by Block Preview pop-ups.

@t-hamano, tet's close this as a duplicate and copy your comment into the original issue.
