### ISSUE TITLE
Consistency of tooltips text

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#4325]
Splitting this out from #4318 

1
More related to design/consistency /cc @jasmussen : some tooltips have title-cased text, some not. Regardless of language-specific preferences (as far as I know title-case is preferred in English, but it's not in many other languages), there should be some consistency. Since these are tooltips and not button labels, I'd go for no title-casing. Some example of the current tooltips:
```
Insert block
Change block type
Align left
Move Up
Move Down
Edit Gallery
Edit image
Remove Image
Grid View
List View
Edit Table
```

2
When I insert an image, by default it has no link. However, the link button says "Edit link". In the classic editor, the link button always says "Insert/edit link" to avoid this issue.

**Comment by karmatosed** [comment]
I would +1 to non title casing. Title casing has a lot of accessibility issues for reading variations.

**Comment by ggwicz** [comment]
@karmatosed Can you elaborate a bit on/provide examples of the accessibility issues you mention with title casing? I'm trying to find resources on that but [am finding stuff about all-caps lettering](https://github.com/humanmade/hm-pattern-library/issues/75), not title case per se.

**Comment by afercia** [comment]
It's a minor issue but screen readers tend to read out uppercase letters with a higher voice pitch, especially when reading a word one character at a time.
