### ISSUE TITLE
Display snackbar confirmation upon template creation

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#43269]
It's not immediately obvious that templates are published immediately upon creation. This can potentially lead to confusion when folks are familiar with working on drafts before publishing.

When you create a new navigation menu via the Navigation block, a Snackbar appears to confirm the menu was created. We can probably do the same thing with templates.

**Comment by annezazu** [comment]
Related: https://github.com/WordPress/gutenberg/issues/31565
