### ISSUE TITLE
Registered block styles inline_styles not loading within BlockPreview

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#43276]
### Description

Registered block styles `inline_styles` are not loading within the BlockPreview. 

### Step-by-step reproduction instructions

1. Register a block style in Twenty Twenty Two, like the following, to the ` twentytwentytwo_support()` function: 
```
register_block_style(
      'core/quote',
          array(
            'name'         => 'blue-quote',
            'label'        => __( 'Blue Quote', 'textdomain' ),
            'inline_style' => '.wp-block-quote.is-style-blue-quote { color: blue; }',
       )
);
```
2. See the block style in the editor on the quote block; it is blue. 
<img width="1259" alt="CleanShot 2022-08-16 at 10 56 28@2x" src="https://user-images.githubusercontent.com/1813435/184912020-4f76b131-7231-4b14-886a-d75ccf176f67.png">

3. Add a pattern to Twenty Twenty Two using the quote block with the blue-quote style from above applied. I used this pattern content: 
```
<!-- wp:quote {"className":"is-style-blue-quote"} -->
<blockquote class="wp-block-quote is-style-blue-quote"><!-- wp:paragraph -->
<p>This is supposed to be blue</p>
<!-- /wp:paragraph --><cite>Rich</cite></blockquote>
<!-- /wp:quote -->
```

4. Search for the pattern in the pattern library UI; it is not blue. 
<img width="1254" alt="CleanShot 2022-08-16 at 11 00 46@2x" src="https://user-images.githubusercontent.com/1813435/184912577-7bdb2179-d303-45a7-bc55-13dc38eb3837.png">

5. Add the pattern to the page; it is blue again.
<img width="1261" alt="CleanShot 2022-08-16 at 11 01 36@2x" src="https://user-images.githubusercontent.com/1813435/184912729-a39c812d-cc0d-48e8-be7b-271a59046309.png">

### Environment info

WordPress 6.0.1
Gutenberg dev

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
Very related to #43250 — likely one solution to solve both.

**Comment by Andrew-Starr** [comment]
Could this also be related to the inline styles not applied when hovering the style selection button in the sidebar? - https://github.com/WordPress/gutenberg/issues/39944

**Comment by Mamaduka** [comment]
It is the same issue as in #39944 and #43250.

@richtabor, going to close this as a duplicate.
