### ISSUE TITLE
Documentation of useBlockProps: Add examples and clarify some common use cases with its API

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#43281]
## What problem does this address?

[useBlockProps](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/#useblockprops) seems to be one of the most used hooks to create a block but its documentation is not clear and doesn't clarify the potential of this hook

## What is your proposed solution?

Improve the documentation of this hook to clarify things such as passing a style object to the useBlockProps hook and some other use cases.  Adding examples would clarify the type of things that can be done with this hook.

**Comment by mburridge** [comment]
Closed by #53646
