### ISSUE TITLE
Dropzone blue line indicators not appearing consistently

### ISSUE THREAD

**Issue by chriskmnds** [WordPress/gutenberg#4329]
## Issue Overview

There is some inconsistency with the editor dropzone indicators: When dragging an image over the blocks, you sometimes need to pass over the **top/bottom** ends of the editor twice for the blue line indicators at the top or bottom to appear. This is not related to speed - the situation is the same whether dragging slowly or fast.

## Steps to Reproduce (for bugs)

1. Create a post with a couple of blocks.
2. Grab an image from the desktop and drag over the blocks list top to bottom a couple of times (see gif below).

Borwsers: IE11, Firefox, Chrome, Safari.

## Expected Behavior

The top/bottom horizontal blue lines should always appear when dragging an image over the top/bottom blocks.

## Current Behavior

The top/bottom blue horizontal lines either appear randomly or when the dragged image passes over them twice.

## Screenshots / Video

![dropzone-indicators](https://user-images.githubusercontent.com/1705499/34616161-fe04e06a-f23f-11e7-9c68-2085548be1d4.gif)

This happens regardless of drag speed (the gif above is somewhat misleading in that regard).

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1516902115000405)._
