### ISSUE TITLE
[Block] Paragraph - When added as a Widget, missing Justify and Underline tools 

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#43292]
### Description

A Paragraph block added to a widget area via the Customizer is missing 2 options from the floating toolbar's **More** menu: `Justify`, and `Underline`. These options are available when a Paragraph block is added to a page or post on the same site.

### Step-by-step reproduction instructions

1. Activate a non-FSE theme that offers Widget areas, such as Twenty Twenty-One
2. Under Appearance > Customize > Widgets, add a paragraph block with some text.
3. Select the `v` More dropdown menu, and find those 2 options are missing.

### Screenshots, screen recording, code snippet

**Page Editor**
![Markup on 2022-08-16 at 19:12:59](https://user-images.githubusercontent.com/27249804/185020019-710af59b-2106-4ab1-a435-89d89891bc90.png)

**Customizer's Widgets**
![Markup on 2022-08-16 at 19:13:53](https://user-images.githubusercontent.com/27249804/185020023-6e9cabff-9cc4-4254-ba0a-5bb17497ca35.png)

### Environment info

- WordPress 6.0.1
- Gutenberg 13.8.2
- Theme: Twenty Twenty-One

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@cuemarie Justify and Underline aren't formatting options in WordPress core, these are the options that are provided in the post editor and other editors by default:
![Screen Shot 2022-08-17 at 3 05 27 pm](https://user-images.githubusercontent.com/677833/185056198-1c08542c-9186-458b-9273-125dc66858a9.png)

You're possibly seeing these added by a plugin, it may be a bug that needs to be solved in that plugin.

**Comment by cuemarie** [comment]
Thanks for pointing that out @talldan ! 👍
