### ISSUE TITLE
Site title font weight doesn't after updated Gutenberg 13.9

### ISSUE THREAD

**Issue by lwangdu** [WordPress/gutenberg#43336]
### Description

After I updated Gutenberg 13.9 site title font weight doesn't work. When I change the font weight to regular or bold they stay same both in the site editor and front end.

### Step-by-step reproduction instructions

Add site title and change font weight to regular or bold the font weight stay the same in the site editor and front end.

### Environment info

WP 6.1, Gutenberg version 13.9 Theme TT2
Browser chrome
Mac book pro

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I was unable to reproduce it.
The font weight was applied correctly from both the block and global styles.
The same is true on the front end.

Is my test procedure wrong?

![site-title](https://user-images.githubusercontent.com/54422211/185279235-6776c95f-481e-4df7-bdcd-282e7d21a1cd.png)

**Comment by lwangdu** [comment]
Thanks for checking on this issue. @t-hamano That's very wired. Here is the screen shot. The font weight set 700 but I don't see bold in the editor. Do you know what overwriting the style?
![Screen Shot 2022-08-18 at 7 05 53 AM](https://user-images.githubusercontent.com/24829573/185415907-45d86c3f-d925-4655-983e-9fc225cb7560.png)

**Comment by t-hamano** [comment]
You are using a template part called `header-large-blue`, but I think it is not included in TT2.
Does font-weight work when you insert the site title block in the default template part or elsewhere in the content?

If so, could you provide the HTML for the entire template part, as the problem may be due to a combination of blocks?
If you select the entire block and copy it, the HTML should be saved to the clipboard.

**Comment by lwangdu** [comment]
@t-hamano Here is header-large-blue html

<div class="wp-block-cover is-light"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-20 has-background-dim"></span><img class="wp-block-cover__image-background wp-image-13" alt="Sierra Nevada Aquatic Research Laboratory" src="https://snarl.nrs.ucsb.edu/wp-content/uploads/2022/06/SNRAL-sunset.jpg" style="object-position:52% 63%" data-object-fit="cover" data-object-position="52% 63%"/><div class="wp-block-cover__inner-container">
<div class="wp-block-group alignfull has-background-color has-text-color has-link-color" style="padding-top:0px;padding-bottom:var(--wp--custom--spacing--large, 8rem)">
<div class="wp-block-group alignfull" style="padding-top:0px;padding-bottom:0px">
<div class="wp-block-group alignwide" style="padding-top:10px;padding-bottom:var(--wp--custom--spacing--large, 8rem)">
<div class="wp-block-group">


<div class="wp-block-group">

</div>
</div>



<div class="wp-block-group has-medium-font-size" style="font-style:normal;font-weight:700"></div>
</div>
</div>



<div style="height:40px" aria-hidden="true" class="wp-block-spacer"></div>



<h2 class="alignwide has-text-align-center has-produkt-regular-font-family has-source-serif-pro-font-family" style="font-size:60px">Sierra Nevada Aquatic Research Laboratory</h2>



<div style="height:40px" aria-hidden="true" class="wp-block-spacer"></div>



<div class="wp-block-buttons alignwide">
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-secondary-background-color has-background wp-element-button"><strong>Plan your visit</strong></a></div>
</div>
</div>
</div></div>

**Comment by Thelmachido** [comment]
I am also not able to reproduce this using the default header part, I am closing this issue for now.
