### ISSUE TITLE
No default padding for Page List inside Navigation Block [Gutenberg 13.9.0]

### ISSUE THREAD

**Issue by slpy9** [WordPress/gutenberg#43348]
### Description

The default padding on page list sub-menus disappeared after updating to Gutenberg 13.9.0, I believe it's related to https://github.com/WordPress/gutenberg/pull/42967.

### Step-by-step reproduction instructions

1. Create pages with hierarchy (parents)
2. Add a navigation block
3. Add page list to the navigation block

### Environment info

- WordPress 6.0.1, Gutenberg 13.9.0, Twenty Twenty-Two
- Chrome / Firefox
- Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
cc @jasmussen

**Comment by jasmussen** [comment]
Thank you for the report + ping, I have a fix in #43358.
