### ISSUE TITLE
Improving placeholder visibility

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#43364]
The placeholder that has been implemented for the Featured Image, Site Logo, Cover, and soon Image block is a nice step forwards:

<img width="703" alt="Screenshot 2022-08-18 at 10 07 47" src="https://user-images.githubusercontent.com/846565/185356970-9f658ac3-ef99-4b40-8341-39cbf0db5713.png">

But there are a couple of scenarios where clarity can be an issue. For example if it appears on a noisy background:

<img width="949" alt="Screenshot 2022-08-18 at 10 12 28" src="https://user-images.githubusercontent.com/846565/185357985-48050b3c-40a5-4b5c-a164-4f875f924fd9.png">

Or when they overlap (e.g. a Featured image in a Cover):

<img width="656" alt="Screenshot 2022-08-18 at 10 03 50" src="https://user-images.githubusercontent.com/846565/185358055-39cec72e-7d62-4ad2-94c5-2201cee70790.png">

Is there anything we can do to make this more visually robust?

**Comment by jasmussen** [comment]
#43379 makes great progress in making this work. Let me know what you think!
