### ISSUE TITLE
default Duotone disabling by theme.json not applied by Site Editor

### ISSUE THREAD

**Issue by via-lars** [WordPress/gutenberg#43384]
### Description

disabling default duotones in theme.json as per https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/:

```
{
    "$schema": "https://schemas.wp.org/wp/6.0/theme.json",
    "version": 2,
    "settings": {
        "color": {
            "defaultDuotone": false
	}
    }
}
```

still lets them be offered by Site Editor:

see screenshot

note: the theme.json in use by Site Editor in above screenshot also disables default gradients.

### Step-by-step reproduction instructions

1. disable defaultDuotones in theme.json
2. open Site Editor Templates Styles pane Gradients tab
3. see duotones still offered

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/23217105/185406551-5e8dcd20-60f4-4f5f-b1ac-60c9a674b911.png)

### Environment info

WordPress 6.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I was also able to reproduce it.
When I open the duotone picker from the block toolbar in the image, the default duotone is not shown.
But it is always visible in the global style panel.

Furthermore, I think it odd that the duotone palette is in the global style gradient panel. Duotones and gradients are two different things.

This is an improvement suggestion not related to this issue, but I think it should appear on the color screen as follows:

![global-style](https://user-images.githubusercontent.com/54422211/187059472-b642ea36-2a4d-422a-9954-ffdd7232a87e.png)
