### ISSUE TITLE
disabled default color features still output as CSS variables in DOM

### ISSUE THREAD

**Issue by via-lars** [WordPress/gutenberg#43385]
### Description

disabling color features such as default pallette by theme.json lets their values still be output in DOM by WordPress as CSS variables

### Step-by-step reproduction instructions

1. ```{
    "$schema": "https://schemas.wp.org/wp/6.0/theme.json",
    "version": 2,
    "settings": {
        "color": {
            "defaultPalette": false,
            "defaultGradients": false,
            "defaultDuotone": false
	}
    }
}```
2. see debugger

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/23217105/185408246-d3cea7ba-7b0f-4ac1-b71f-da0afb54f1f7.png)

### Environment info

WordPress 6.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thank you for your request. 

The default color palette is still loaded so those variables can by other plugins in the WordPress Ecosystem (as explained at https://github.com/WordPress/gutenberg/issues/24684#issuecomment-900083774) 

Discussion is ongoing in https://github.com/WordPress/gutenberg/issues/29568 and you can share your comments in there. 

Regarding the removal of the duotones and gradients: 
This has been requested in https://github.com/WordPress/gutenberg/issues/38299
