### ISSUE TITLE
Element Font Family values written as values instead of variables

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#43397]
### Description

When setting the Font Family for elements (Links, Headings and Buttons) the value written to the user Global Styles is the VALUE rather than the VARIABLE.  When the same action is performed on a block (for example the Button Block) or the base font family the VARIABLE is used instead.

This is a problem for Web Font Providers (like Jetpack's Google Font Provider and what Blockbase is simulating locally) which are inspecting these values to determine if the fonts should be enqueued and loaded.  Should a user set the font exclusively in the element typography panel that font will not be enqueued and loaded.

### Step-by-step reproduction instructions

Load a theme that relies on a Web Font Provider (such as Blockbase or one of its children or any other Block theme running on WordPress.com which is leveraging JetPack's Google Fonts Provider).

Assign a unique font to the `Link` element and save.
<img width="287" alt="image" src="https://user-images.githubusercontent.com/146530/185507518-531687c2-4cb8-4058-9435-3ac48700b21a.png">

Load a view that has a link.  Note that the font selected isn't enqueued and used (only the fallback system font is used instead).

Observe the user's Global Styles values (export the theme where they are merged with the theme values or use some other method).  Note that the font family values for the elements differ from elsewhere.

### Screenshots, screen recording, code snippet

Exported user Global Styles after assigning font family values:

```
{
    "styles": {
        "elements": {
            "link": {
                "typography": {
                    "fontFamily": "'Space Mono', sans-serif"
                }
            },
            "heading": {
                "typography": {
                    "fontFamily": "Arvo, serif"
                }
            },
            "button": {
                "typography": {
                    "fontFamily": "Cabin, sans-serif"
                }
            }
        },
        "typography": {
            "fontFamily": "var:preset|font-family|domine"
        },
        "blocks": {
            "core\/button": {
                "typography": {
                    "fontFamily": "var:preset|font-family|fira-sans"
                }
            }
        }
    },
    "version": 2
}
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by cat-og** [comment]
Seem to be a similar issue with zd-5777743. I'm not familiar enough with coding to determine if it is an exact match to the issue, but they are unable to save and apply changes to the fonts on their live site while using a Blockbase theme.

**Comment by syhussaini** [comment]
Sent a follow-up on #5777743-zen.
