### ISSUE TITLE
Display homepage settings in the front-page Template Inspector

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#43418]
The front-page template is unique in that it will always display the homepage regardless of what the homepage is set to display in the reading settings.

Therefore we might consider pulling the homepage display settings directly into the Inspector panel for this template. Here's a rough example of how this could work:

https://user-images.githubusercontent.com/846565/185600840-c5f9cf7d-9c1d-420e-912d-edcb8e152296.mp4

I think this could potentially elevate the perception of this template, which is otherwise a bit confusing.

Related: https://github.com/WordPress/gutenberg/issues/42554

**Comment by jffng** [comment]
> directly into the Inspector panel for this template

Do you think it makes sense to surface these settings just for front-page? I think there are other cases or templates where it could be useful to surface the reading settings in the site editor.

**Comment by jameskoster** [comment]
It's a bit tricky. We might surface posts-per-page settings in the Archive template, but since that setting can affect _other_ templates it might be confusing? 

That's the nice thing about homepage settings and the front-page template – it's totally self-contained. When front-page exists it will always display the homepage. 

Did you have anything specific in mind?

**Comment by jffng** [comment]
I was thinking that it could make sense to display these settings for `index`, or `home` since depending on what templates are provided, these settings could have an impact. But I see what you mean, I don't think it would make sense to display these settings in those templates since they are not always relevant.  

What's still tricky about adding these settings to front-page — would it require by convention a query block to exist in the template for the expected result?

**Comment by jameskoster** [comment]
Yes good point, a Query (that inherits from the template) is mandatory for the settings to have any effect. 

I suppose another option could be to surface these settings on the Query block itself, but only when situated in the front-page template, and only when it inherits. That sound a bit finicky though.

**Comment by annezazu** [comment]
I'm going to close this out in favor of https://github.com/WordPress/gutenberg/issues/49597 as that has more context and momentum right now while still covering the same issue at hand. 

Feel free to reopen if I'm missing something though!
