### ISSUE TITLE
Improving intuition of the 'Query' pattern category

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#43427]
<img width="291" alt="Screenshot 2022-08-19 at 13 52 17" src="https://user-images.githubusercontent.com/846565/185622456-bc221979-83eb-4f00-af8c-ff78afcd2eaa.png">

One of these is not like the others. Unless you're familiar with the inner workings of WordPress, 'Query' is probably going to sound a bit alien. 

Ideally Query variations should be dynamically built based on existing post types (https://github.com/WordPress/gutenberg/issues/40941). Then we can use similar logic to populate the category list in the Patterns tab. For example when a `product` post type exists I should find a 'Products' pattern category, and a 'Products List' Query variation. 

But until such logic has been installed, we might consider renaming this category to 'Posts'.

**Comment by mtias** [comment]
100%, it's really unfortunate we still have this category exposed to users. Maybe Blog Posts for clarity or are we fine with just Posts?

**Comment by jameskoster** [comment]
Yes I would be in favor of that. Appending/Prepending instances of "posts" with "Blog" is likely to be a requirement in other areas of the site editing UI to contextualise between generic 'posts', and the `post` post type.

**Comment by antonyjsmith** [comment]
But it's describing it for what it is, a query and the term can encompass multiple post types already without the need for additional logic. Feels like complexity for the sake of it rather than trying to educating a user.

Plus you need a pretty good grasp of Wordpress to get the best out of Gutenberg anyway and this'll be another one of those annoying changes that then change again.

**Comment by jameskoster** [comment]
Yes but patterns are generally designed with a certain post type in mind. If a user wants to insert a Products grid, it's not helpful that they have to sift through patterns designed for projects, recipes, blog posts, and so on. 

So there's two approaches – have subcategories beneath 'Query', or just elevate those 'sub' categories to the top level and hide the generic 'Query'. I don't have a strong opinion either way, the most important thing imo is to present categories that resonate more with less technical users.

**Comment by antonyjsmith** [comment]
Are they? In my experience patterns are generally agnostic. Plus only one pattern category in that drop down is for a specific post type and that's pages e.g buttons, gallery, columns etc can be used anywhere and not for a specific post type, under the assumption 'everything a block' so all patterns should work anywhere.

Finally, returning to the original rational, post type is a Wordpress concept, so to understand post type is to understand the workings of Wordpress.

**Comment by annezazu** [comment]
Removing from 6.1 editor tasks as we've entered feature freeze.

**Comment by annezazu** [comment]
Curious if this can be closed or what remains after this recent PR merge that included renaming Query to Posts: https://github.com/WordPress/gutenberg/pull/45244#pullrequestreview-1159641791

**Comment by jameskoster** [comment]
Certainly!
