### ISSUE TITLE
Group: Add setup state to allow picking a variant (default/row/stack)

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#43433]
The Row and Stack blocks are variants of the group block. The group is for standard flow based content, Row flexes horizontally, Stack flexes vertically. You can transform between the variants in the inspector, and transform into one of these variations when selecting multiple blocks:

<div align="center">
<img width="340" alt="block toolbar" src="https://user-images.githubusercontent.com/1204802/185643696-efcc41dd-62ca-471a-9f2b-c98180f3520d.png">
</div>

In most flows, you will arguably encounter the trio of container blocks having entered your content from from a pattern, or by selecting a few blocks and clicking the group toolbar button. In that light, when you explicitly choose to insert an empty group block from the inserter, it can be considered an intent to "build layouts". We can build on that intent and offer them in a basic Group block setup state:

<img width="860" alt="Group setup state" src="https://user-images.githubusercontent.com/1204802/185644454-cef54532-21a9-4ca1-b798-6baa9690bca7.png">

Picking one would lead to the setup state we have today:

<img width="1640" alt="Row" src="https://user-images.githubusercontent.com/1204802/185644006-fb793377-6a44-4d07-8f30-f35964fcebeb.png">

There's also an opportunity here to offer additional layout wireframes as shortcuts, such as a column-layout based on Stack blocks inside a Row. But this is someting to explore separately, and for the initial version, Group, Row and Stack variations would be sufficient.

<details>
<summary>SVG graphics for the shortcuts</summary>

No need to add the following illustrations to the icon library, these can exist just for the Group, for example in a `variations.js` file.

Stack:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44 32" style="enable-background:new 0 0 44 32" xml:space="preserve"><path d="M42 0H2C.9 0 0 .9 0 2v12.5c0 .6.4 1 1 1h42c.6 0 1-.4 1-1V2c0-1.1-.9-2-2-2zm1 16.5H1c-.6 0-1 .4-1 1V30c0 1.1.9 2 2 2h40c1.1 0 2-.9 2-2V17.5c0-.6-.4-1-1-1z" style="fill:#ccc"/></svg>
```

Row:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44 32" style="enable-background:new 0 0 44 32" xml:space="preserve"><path d="M42 0H23.5c-.6 0-1 .4-1 1v30c0 .6.4 1 1 1H42c1.1 0 2-.9 2-2V2c0-1.1-.9-2-2-2zM20.5 0H2C.9 0 0 .9 0 2v28c0 1.1.9 2 2 2h18.5c.6 0 1-.4 1-1V1c0-.6-.4-1-1-1z" style="fill:#ccc"/></svg>
```

Group:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44 32" style="enable-background:new 0 0 44 32" xml:space="preserve"><path d="M42 0H2C.9 0 0 .9 0 2v28c0 1.1.9 2 2 2h40c1.1 0 2-.9 2-2V2c0-1.1-.9-2-2-2z" style="fill:#ccc"/></svg>
```

</details>

[Figma](https://www.figma.com/file/hRcrIXVmDEEvK7E7jnEHjx/Group%2C-Row%2C-Stack-icons-and-setup-states?node-id=0%3A1).

---

Issue updated Sep. 28.

<details>
<summary>Initial proposal</summary>
The Row and Stack blocks are variants of the group block. The group is for standard flow based content, row flexes horizontally, stack flexes vertically. These three blocks come with setup states to subtly indicate their direction:

![group row and stack](https://user-images.githubusercontent.com/1204802/185643139-a6dcd9de-20dd-4ca7-81e7-77c5fee8b4b9.gif)

You can transform between the variants in the inspector:
<img width="281" alt="transform" src="https://user-images.githubusercontent.com/1204802/185643190-fbf43fc4-e6f9-452a-848c-9c921cd3c1f6.png">

And you can transform into one of these variations when selecting multiple blocks:

<img width="340" alt="block toolbar" src="https://user-images.githubusercontent.com/1204802/185643696-efcc41dd-62ca-471a-9f2b-c98180f3520d.png">

Despite these affordances, it may still not be entirely clear what to do with an empty group, stack, or row. It might make sense to have a first step of that setup state be a basic picker allowing you to choose the layout in a more visual way:

<img width="860" alt="Group setup state" src="https://user-images.githubusercontent.com/1204802/185644454-cef54532-21a9-4ca1-b798-6baa9690bca7.png">

Picking one would lead to the setup state we have today:

<img width="1640" alt="Row" src="https://user-images.githubusercontent.com/1204802/185644006-fb793377-6a44-4d07-8f30-f35964fcebeb.png">

Such an initual setup state we should also follow up on with more concrete layouts in the future, like different width of columns once we support that.
</details>

**Comment by ntsekouras** [comment]
The plan here is to show this setup on all variations(group. stack, row) or just expose the `Group` in the inserter? Also if a user has clicked in one option from the placeholder and doesn't add anything at that moment, what would be the expected output on refresh? Should we show again the setup state?

**Comment by jasmussen** [comment]
This setup should mainly (only probably) show on the Group variation, and only when it's empty. It's a good layout starting point. 

> Also if a user has clicked in one option from the placeholder and doesn't add anything at that moment, what would be the expected output on refresh? Should we show again the setup state?

If you just click "Group" in the flow illustrated, you should get the group as it exists today, i.e. with the inserter. If you then don't add any blocks inside and deselect, we can revert back to the setup state as shown. Does that make sense?

In most flows, I would expect the group (and row/stack variations) to mainly enter your content from from a pattern, or by selecting a few blocks and clicking the group toolbar button. In that light, when you explicitly choose to insert an empty group block, it can be considere an intent to "build layouts". In that light, I could see us adding additional shortcut buttons to this state, to let you create layout primiteves such as flex based columns and otherwise. These would almost be wireframe pattern shortcuts. But this would be something to explore in the future: just sharing as context for why the empty group is special in this regard.

**Comment by jasmussen** [comment]
See also #43496 which is some initial work to address this issue.

**Comment by ramonjd** [comment]
Resolved by https://github.com/WordPress/gutenberg/pull/43496
