### ISSUE TITLE
WordPress API error when trying to add tags

### ISSUE THREAD

**Issue by soumitra2021** [WordPress/gutenberg#43464]
### Description

In this video- https://www.loom.com/share/6671fc834c624e37940ba9ecf0398389 you can see that, even with all plugins deactivated and with a default theme, there is an error whenever we tried to add a new tag. As you can see in the video, there is a 400 server error related to the WordPress API.

WordPress API error when trying to add tags that already exist to a existing post or within site.
I’ve run into an error in the browser console whenever I try to add tags (that already exist on the site) to a post.

I was able to reproduce this error on a completely new WordPress 6.0.1 install.
We then tried to reproduce this issue on a completely new WordPress installation with no plugins and we managed to reproduce this problem. It looks like this is a problem in WordPress core and not in a plugin. The error seems to be triggered only when you try to add a tag that already exists on the site.

### Step-by-step reproduction instructions

To reproduce this, please try the following steps:
1) Create a few tags (around 5-6) under Posts > Tags.
2) Create a new post.
3) With the browser console open, start adding your tags to the new post.
4) You should see a 400 Bad Request error for /wp-json/wp/v2/tags?_locale=user

### Screenshots, screen recording, code snippet

New WordPress installation without any plugins - https://www.loom.com/share/495245005a344c9992177b6e8dd81ca4/

As shown in the video, to reproduce this, please try the following steps:
1) Create a few tags (around 5-6) under Posts > Tags.
2) Create a new post.
3) With the browser console open, start adding your tags to the new post.
4) You should see a 400 Bad Request error for /wp-json/wp/v2/tags?_locale=user

I've attached the site info output from Health Check below.
[siteinfo.txt](https://github.com/WordPress/gutenberg/files/9391302/siteinfo.txt)

### Environment info

WordPress 6.0.1 install
Google chrome browser
Desktop
Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aatanasovdev** [comment]
@soumitra2021 I've tried reproducing the issue following the provided steps but adding tags works as expected without any WordPress REST API errors on my side.

Considering the error of the response shown on your videos, something happens on the server side. Can you please provide the following details:
- The headers of the response (available in the [Headers](https://wd.imgix.net/image/BrQidfK9jaQyIHwdw91aVpkPiib2/Hy3k9tz8CnW3RrzeMPch.png?auto=format&w=1600) tab of the particular request inside the browser network area);
- The body of the response (available in the [Response](https://wd.imgix.net/image/BrQidfK9jaQyIHwdw91aVpkPiib2/x94xMX1owJR5M3Pm71ln.png?auto=format&w=1600) tab);
- If there are any server errors related to these API requests.

These details should help find the root of the problem.

Before going through the steps, please enable [the WordPress debug mode ](https://wordpress.org/support/article/debugging-in-wordpress/) on your local instance. If there are any reported errors, please provide them as well.

**Comment by suascat** [comment]
Hi, 

I was also able to replicate the issue as per the steps provided. The error basically seems to occur when trying to add already created tags (not at least for categories).



### **Headers**

Request URL: http://dev2.local/wp-json/wp/v2/tags?_locale=user
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 35.209.87.45:80
Referrer Policy: strict-origin-when-cross-origin
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type
Access-Control-Allow-Methods: OPTIONS, GET, POST, PUT, PATCH, DELETE
Access-Control-Allow-Origin: http://dev2.local
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages, Link
Allow: GET, POST
Cache-Control: no-cache, must-revalidate, max-age=0
Connection: keep-alive
Content-Type: application/json; charset=UTF-8
Date: Fri, 26 Aug 2022 07:43:07 GMT
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Host-Header: 8441280b0c35cbc1147f8ba998a563a7
Link: <http://dev2.local/wp-json/>; rel="https://api.w.org/"
Server: nginx
Transfer-Encoding: chunked
Vary: Origin
X-Content-Type-Options: nosniff
X-Httpd: 1
X-Proxy-Cache-Info: DT:1
X-Robots-Tag: noindex
X-WP-Nonce: 4e60c2dbce
Accept: application/json, */*;q=0.1
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,hi;q=0.8,nb;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 14
Content-Type: application/json
Cookie: wordpress_test_cookie=WP%20Cookie%20check; tk_ai=woo%3A%2Bc01VrEE45BiPUU8S2yTq7dT; wp-settings-1=libraryContent%3Dbrowse; wp-settings-time-1=1661002592; wordpress_logged_in_70345b1c983e21a81c303e28f90b7afe=aromaxtend%7C1661667131%7CYUdakHZifUB7dlMQoDkllyGMDvasbheOAAZnYFiijn3%7Cbbf575baeaf1f57b4b334e11cf3d2e74c952b03bd2470cd5c58b4007747281aa
Host: dev2.local
Origin: http://dev2.local
Pragma: no-cache
Referer: http://dev2.local/wp-admin/post.php?post=2418&action=edit
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
X-WP-Nonce: 4e60c2dbce


### Response1

`{"code":"term_exists","message":"A term with the name provided already exists in this taxonomy.","data":{"status":400,"term_id":32},"additional_data":[32,32]}`

![response](https://user-images.githubusercontent.com/9716719/186853863-7ae67155-3ed2-4c6c-b69b-4f8a46ebe71b.png)

### Response2 When trying to autosave

{"code":"rest_autosave_no_changes","message":"There is nothing to save. The autosave and the post content are the same.","data":{"status":400}}

![response2](https://user-images.githubusercontent.com/9716719/186854216-65d751ee-de39-4c90-9ada-e8a0bcff0a55.png)

Looks like this issue matches with https://core.trac.wordpress.org/ticket/15741

**Comment by rmarcano** [comment]
This issue was also reproduced in the WordPress Core tracker [here](https://core.trac.wordpress.org/ticket/56410#comment:5):

_To reproduce it, you must quickly validate the entry of new tags before
the list of proposals appears. A solution I would suggest would be to
block any new request as long as there is an old one that is not
completed._

**Comment by aatanasovdev** [comment]
Indeed, I was able to reproduce the issue while typing too fast and submitting an existing tag (before the tags list Ajax request completes). Preventing the submit action until the tags list is presented sounds like a good solution.

**Comment by aatanasovdev** [comment]
After looking into the code, it appears the error is intended because it was handled here: https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-taxonomies/flat-term-selector.js#L69-L81

Even though there is a 404 response, another API request fetches the existing tag -- then it is assigned to the post. Perhaps the reason behind this is that the suggestions and the tags are isolated.

On my side, the tags were assigned correctly. However, reviewing the first video provided by @soumitra2021, the tags weren't added to the post.

@soumitra2021  can you please test if the tags are assigned to the particular post when using a fresh WordPress instance? 

If the tags are assigned correctly, and there are no user experience issues, I think we can keep the current solution (when there is an existing tag to fetch it).

**Comment by soumitra2021** [comment]
@azouamauriac
> To reproduce it, you must quickly validate the entry of new tags before the list of proposals appears. A solution I would suggest would be to block any new request as long as there is an old one that is not completed.

As mentioned by @rmarcano This issue was also reproduced in the WordPress Core tracker - 
https://core.trac.wordpress.org/ticket/56410#comment:5

@aatanasovdev
> Indeed, I was able to reproduce the issue while typing too fast and submitting an existing tag (before the tags list Ajax request completes). Preventing the submit action until the tags list is presented sounds like a good solution.

No, If typing slowly and submitting any new or existing tags, even after waiting for the tags list Ajax request completes, and/or waiting to show existing tags in drop-down list, and selecting from dropdown tag lists for existing tags, that process also does not work, tags were not saved. It happened with version: 6.0.1.

And now after updating to WordPress 6.0.2, Now when typing tags for new and/or, selecting existing from dropdown list, after adding 3-6 tags, showing "updating failed" then we have to press "Update Button" upper right corner and again enter more tags (Need to follow same process after entering certain numbers of tags).
![updating failed](https://user-images.githubusercontent.com/84924153/187672168-a94d2661-a21d-44c1-9d4e-c781450a9699.png)

**Comment by aatanasovdev** [comment]
I prepared a video that shows how I could add existing and new tags. 

During the video, I tested the following scenarios:
 - Adding new tags
 - Adding existing tags slowly
 - Selecting existing tags from the autocomplete list
 - Adding existing tags while typing quickly to force the existing tag error.

All tags were assigned correctly to the post without the `Updating failed` error.

[Testing-tags.webm](https://user-images.githubusercontent.com/38669058/187974285-c055bc31-78c5-4610-a052-acc91cbb16c6.webm)

During testing, I used the latest WordPress version.

If someone else could also share some testing results, that would be helpful.

**Comment by Mamaduka** [comment]
Those errors are correct, and there's nothing wrong with them.

Using enter key or using a comma after a text in the "Add New Tag" field will try to create a new tag. If the tag with the same name already exists (returned as 400 error), the editor will assign that tag to a post.

https://github.com/WordPress/gutenberg/blob/8aa2aa23124670e4081408a64e6cd5d0072b8553/packages/editor/src/components/post-taxonomies/flat-term-selector.js#L65-L73

**Comment by jonkurtis** [comment]
I was able to reproduce the issue (returned a 400 error) when there are more than 20 tags that contain the same word. For instance, I have  more than 20 tags that contain "UF Health" because I have tags for guest authors with "UF Health" at the end like a byline. Because I have more than 20 tags that contain this phrase, and the autocomplete only contains 20  existing tag suggestions, it does not show the simple "UF Health" tag in the list, so I am forced to hit enter or insert a comma which attempts to create a new tag instead of adding the existing tag.

**Comment by Mamaduka** [comment]
Thanks for the feedback, @jonkurtis!

Receiving the 400 error is okay in that situation. It means that WP found an existing tag matching the name and assigned it to the post instead of creating a new one.

**Comment by jonathan-cfmp** [comment]
@Mamaduka, Sorry I should have mentioned that the tags are not saving to the post. I get the 400 error, then after saving the post and reloading, the tags are not applied.

**Comment by Mamaduka** [comment]
Thanks for the additional details, @jonathan-cfmp!

**A few more questions:**
* What version of WordPress and Gutenberg plugins are you using?
* Does your site have multiple tags (more than 20) with similar names?

**Comment by jonathan-cfmp** [comment]
@Mamaduka,

- WordPress version is 6.0.3. No Gutenberg plugin, just the core WordPress Gutenberg integration.
- Yes, we have more than 20 tags with similar names.

The issue only occurs when trying to add tags with more than 20 similar tags, which prevents me from selecting the tag from the autosuggest dropdown.

**Comment by Mamaduka** [comment]
Thank you, @jonathan-cfmp!

I recently fixed related issue #43766. The fix is available in Gutenberg 14.1 ( or later) and will also ship with WP 6.1, which will be released next week.

**Comment by jonathan-cfmp** [comment]
Thank you @Mamaduka. I look forward to testing it out when it is released.

**Comment by Mamaduka** [comment]
Hi, @jonathan-cfmp

I just wanted to check in to see if you got a chance to test the fix that shipped with WP 6.1.

**Comment by jonathan-cfmp** [comment]
Everything seems to be working correctly now @Mamaduka. I added the tag and got the 400 error because the tag already existed, but the tag saved even though it was not in the autosuggest list. Thanks for fixing the issue.

**Comment by Mamaduka** [comment]
Thanks for the confirmation, @jonathan-cfmp!

I will close the issue as the fix was confirmed in WP 6.1.

**Comment by Kojimo** [comment]
Hi @Mamaduka,

I found a very similar problem with the same error code with the same endpoint in version 6.0.X
The only difference is that after some errors 400 starts to fire errors 500, with the same endpoint.
So i updated to 6.1.1 and I have that problem even after, on multiple installation even in diagnostic mode or on a fresh wordpress installation.

If i try to add multiple tags fast, the editor in the seconds after losts some of them. I have to wait a moment and select one of them or confirm with enter a custom one to make it work.
I guess it is related to the "_To reproduce it, you must quickly validate the entry of new tags before the list of proposals appears._"

I will attach the error log from Chrome Console of one of the 400 call from one of the installations where i found the problem.

Good note: before the update the site went down when the multiple errors where fired, and saving on the editor stopped working with the "Updating failed." error stated before in this thread. Now "only" doesn't save tags.

P.S. Do you feel is better to reopen this thread or create a new one?
Thanks and sorry if i did something wrong.

[addingtagserror.txt](https://github.com/WordPress/gutenberg/files/10812090/addingtagserror.txt)

**Comment by Mamaduka** [comment]
Sorry for the late reply, @Kojimo.

Can you share the response message from a 400 request?  You can view them using the Network panel in the DevTools.

## Screenshot
![CleanShot 2023-03-08 at 08 53 10](https://user-images.githubusercontent.com/240569/223623190-8c44c2b2-9c74-40a5-8fe4-dfe988050d76.png)

**Comment by Kojimo** [comment]
Hi, sorry for my late reply too @Mamaduka 

Here is the screenshot you requested.

![image](https://user-images.githubusercontent.com/33292341/226310241-09d14820-2f28-4328-be3e-717a02211019.png)

**Comment by Mamaduka** [comment]
Sorry for the late reply, @Kojimo.

As I mentioned above, 400 errors ( are expected. The catches then and adds the correct tag.

Unfortunately, I'm not able to reproduce the 500 server error. The `Updating failed.` notice is usually displayed when there's a fatal error on the server, but I don't see how that could be related to tags creation.

**Comment by amon-ra** [comment]
Same error on Wordpress 6.4.1, if searched tag not in list results, 400 error is fired but tag is not added.
Please reopen

**Comment by fcenteno** [comment]
In version 6.5.3, the error persists. Just as mentioned in the previous message, we have many tags, and we are unable to use them because we receive the same error. We have had to stay on an outdated version of WordPress. Is there any way you can help resolve this bug?

**Comment by eugenchio** [comment]
It looks like the error object which arrives [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-taxonomies/flat-term-selector.js#L168) has no necessary information inside. The `error.code` and `error.data` are `undefined`.

```javascript
	async function findOrCreateTerm( term ) {
		try {
			const newTerm = await saveEntityRecord( 'taxonomy', slug, term, {
				throwOnError: true,
			} );
			return unescapeTerm( newTerm );
		} catch ( error ) {
			if ( error.code !== 'term_exists' ) {
				throw error;
			}

			return {
				id: error.data.term_id,
				name: term.name,
			};
		}
	}
```

**Comment by Mamaduka** [comment]
@eugenchio, the error reported here: https://github.com/WordPress/gutenberg/issues/43464#issuecomment-1475959205 has correct data, and the code will safely handle it.

It would be impossible to anticipate correctly when a plugin or site changes REST API error responses and removes required information.

Do you mind sharing the same data if you can reproduce the issue?

**Comment by eugenchio** [comment]
@Mamaduka The network response is as expected
![image (2)](https://github.com/WordPress/gutenberg/assets/24696845/68db1211-03a1-4de3-b291-b900b4e5186d)
But the error object is missing necessary fields
![image-1-](https://github.com/WordPress/gutenberg/assets/24696845/2915ab2e-98c8-4766-94f6-12388d8876dc)

Reproducing on WP 6.4.2

**Comment by Mamaduka** [comment]
@eugenchio, I'm getting correct that when logging the error object. Have you tried testing with the latest WP or Gutenberg versions?

## Screenshot
![CleanShot 2024-07-11 at 17 04 20](https://github.com/WordPress/gutenberg/assets/240569/674156c8-4bec-479f-ba29-b867986f8572)

**Comment by eugenchio** [comment]
@Mamaduka Alright, my bad. I've tested it now with all plugins disabled. First of all, it was undefined due to my custom plugin.
Nevertheless it didn't work with it disabled right away, because the error message was still different that normally and it is due to the Yoast Seo Premium plugin (with yoast premuim disabled everything works as expected, also with all plugins disableed and just yoast seo enabled it is the same):
![Screenshot-from-2024-07-12-11-36-33](https://github.com/user-attachments/assets/ca1d1163-6266-4d2f-9f00-a37a7b339934)

Thank you for the support!

**Comment by Mamaduka** [comment]
Thank you, @eugenchio!

I've seen the Yoast SEO plugin mentioned in another similar issue.

Just to clarify, everything works as expected as soon as you disable the Yoast Seo Premium plugin. Is this correct?

**Comment by eugenchio** [comment]
@Mamaduka Yes, that's right!

**Comment by Mamaduka** [comment]
@eugenchio, can you share the Yoast SEO and premium plugins version?

**Comment by eugenchio** [comment]
@Mamaduka `"wordpress-seo-premium": "20.12"`, `"yoast/wordpress-seo": "20.12"`

**Comment by enricobattocchi** [comment]
Hey @eugenchio, sorry for the problem you are experiencing. 
In [Yoast SEO Premium 22.7](https://developer.yoast.com/changelog/yoast-seo-premium/22.7/) we shipped a fix for an issue that could be related, so there is a high chance that upgrading would solve it. If you happen to test a more recent version, can you let me know whether you can still reproduce?

**Comment by eugenchio** [comment]
@enricobattocchi Thank you. Tested with 23.0 and the issue disappeared!
