### ISSUE TITLE
Database Block

### ISSUE THREAD

**Issue by bhubbard** [WordPress/gutenberg#43462]
## What problem does this address?

It would make it possible for end-users to create custom databases without any coding knowledge.

## What is your proposed solution?
I have been testing notion (uses blocks) a lot recently and noticed that a lot of its power comes from the concept of a database block, and I think WordPress has the power to do the same. User would choose the block, and as they choose columns (view would be similar to table) etc, this would actually create a mysql table. Of which they can actually start to populate there on the screen within gutenberg.

**Comment by glendaviesnz** [comment]
Thanks for the suggestion, this is probably [outside the scope of core Gutenberg](https://make.wordpress.org/core/handbook/about/philosophies/#design-for-the-majority) and something for plugin developers to pick up, so closing for now.
