### ISSUE TITLE
Allow to change the default font size in editor.

### ISSUE THREAD

**Issue by ayophanz** [WordPress/gutenberg#43467]
## What problem does this address?

In gutenberg Editor it would be nice to have capability to change the default font size. 

## What is your proposed solution?

It would be great to `add_action` or `add_filter` in functions.php for this small enhancement.

**Comment by t-hamano** [comment]
Thank you for submitting the issue.
You can change the default font size in the following way:

## On Classic Theme

Register a style sheet describing the following style via `add_editor_style()`.

```css
body {
  font-size: 20px;
}
```

## On Block Theme

You can configure this in theme.json.

```json
{
  "version": 2,
  "styles": {
    "typography": {
      "fontSize": "20px"
    }
  }
}
```

**Comment by Mamaduka** [comment]
I think this issue is more suitable for [Discussions](https://github.com/WordPress/gutenberg/discussions).
