### ISSUE TITLE
Setting 'Border' styles separately

### ISSUE THREAD

**Issue by henriqueiamarino** [WordPress/gutenberg#43471]
## What problem does this address?
I'm always frustrated when I try to set border styles as design elements. To design strokes sitting next to other components I end up creating columns or rows and use images to emulate the image below. **As we’re currently developing a theme where this tool would be essential to achieve the design** I believe Gutenberg could benefit on a simple solution here.

<img width="562" alt="heading-element" src="https://user-images.githubusercontent.com/103748085/185884324-d557b6f0-d7c3-42ce-bc03-c73e103d5df3.png">

## What is your proposed solution?
What If we could expand our 'Border' panel and allow styling to be added separately? **Webflow site builder** has implemented this idea and I believe the same approach would fit perfectly into our settings arrangement. Four different border settings allowed.

<img width="1374" alt="webflow-solution" src="https://user-images.githubusercontent.com/103748085/185883429-5fd91758-744b-4950-839b-287d44b57062.png">

**Comment by t-hamano** [comment]
In the latest Gutenberg, #37770 introduces a new `BorderBoxControl` component in block support that allows for individual adjustments.
Paragraph and heading blocks are not supported, but wrapping in group blocks should work.
Is this your solution?

https://user-images.githubusercontent.com/54422211/185955805-c65d9765-1b5d-42aa-b36d-822487e2e03a.mp4

**Comment by henriqueiamarino** [comment]
Thanks @t-hamano that indeed solves the problem.
