### ISSUE TITLE
Navigation: pseudo states do not apply to parent items that are buttons

### ISSUE THREAD

**Issue by mikachan** [WordPress/gutenberg#43487]
### Description

In the navigation block, with the 'Open on click' option enabled, parent menu items that have sub-menus cannot have their pseudo states styled via theme.json. 

There is a specific example described [here](https://github.com/WordPress/twentytwentythree/pull/83#issuecomment-1221953299), using Twenty Twenty-Three.

> Parent items that have sub menus are not underlined on hover anymore -they are buttons. As a user I would expect the menu to look the same when I enable this option.

When the 'Open on click' option is disabled, the parent items are links, and can successfully have their pseudo states controlled via theme.json.

### Step-by-step reproduction instructions

1. Activate a theme that configures pseudo states for the navigation block via theme.json (Twenty Twenty-Three is an example)
2. In the Side Editor, enable the 'Open on click' option for the navigation block. This should turn the parent menu items into buttons instead of links.
<img width="271" alt="image" src="https://user-images.githubusercontent.com/1645628/185955051-f75e56c5-9dba-4615-956a-e08fd2aead44.png">

3. Add the following to the theme.json:

```
"styles": {
		"blocks": {
			"core/navigation": {
				"elements": {
					"button": {
						":hover": {
							"typography": {
								"textDecoration": "underline"
							}
						},
						":focus": {
							"typography": {
								"textDecoration": "underline"
							}
						},
						"typography": {
							"textDecoration": "none"
						}
					},
			},
...
```

4. Notice that the button pseudo state styles are not applied to the parent menu items.

### Environment info

- WP 6.0.1, GB trunk, Twenty Twenty-Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
@mikachan Does this still happen for you?

**Comment by mikachan** [comment]
No, it looks like the parent item is styled as expected now. I think this can be closed 👍
