### ISSUE TITLE
Consider offering a visual indicator post block transform

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#43490]
## What problem does this address?

When you transform a block to columns, it's fairly subtle that a change occurred. While the icon on the block changes and the block settings change, it's a bit strange that you can continue to just transform to columns. This was noted during the [sixteenth FSE Outreach Program call for testing](https://make.wordpress.org/test/2022/08/13/fse-program-testing-call-16-back-to-basics/): 
>The transform to columns on multiple clicks of it ended up creating many many columns blocks wrapped inside each other. It was not clear why columns was an option to transform to, but now I am assuming it is so that you can quickly wrap an element into a columns block.

https://user-images.githubusercontent.com/26996883/185976044-4297ce6b-7bf5-4f2f-9e5f-39eed5f983fe.mov

## What is your proposed solution?

This feels fairly edge but wanted to note. Perhaps an animation could be added post transform (block icon bounces showing the change completed) or, after transforming to one block, that block is then de-emphasized to indicate you just switched to it (why would we list Columns as the number 1 transform for columns?). I'll leave it for @WordPress/gutenberg-design  to consider :)

**Comment by jasmussen** [comment]
Good ticket. I would tend to think the simplest solution is to not allow a columns block to be transformed into a columns block. You can still insert a nested columns block inside. But transforming caters to an edgecase that doesn't seem worth optimizing for.

**Comment by ndiego** [comment]
> I would tend to think the simplest solution is to not allow a columns block to be transformed into a columns block. 

I will take a stab at a PR this week.
