### ISSUE TITLE
Various typography changes reset after moving paragraph block out of quote block

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#43491]
### Description

If you set some typography changes to a paragraph block, like font size or letter spacing, drag it into a quote block, and then drag it back out of the quote block, those changes are lost. This seems to happen with letter spacing and font size but not with letter case, appearance, or line height.  I can't quite tell if this is a problem with the quote block, paragraph block, typography controls, drag and drop, etc. 

This was found as part of the [sixteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/08/13/fse-program-testing-call-16-back-to-basics/#comment-2680). 

### Step-by-step reproduction instructions

1. Customize a paragraph block by changing font size or letter spacing.
2. Drag it into a quote block (v2).
3. Notice the changes remain.
4. Drag the paragraph block outside of the quote block.
5. Notice changes to font size and letter spacing are lost. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/185985673-4d82bddc-fa4d-494d-9c58-674f3057c90d.mov

### Environment info

- WordPress 6.0.1
- Gutenberg 13.9
- TT2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by marko-srb** [comment]
I have also tested and it seems like two additional conclusions may help when looking into the issue:

01. ‘Letter spacing’, ‘Size’, and ‘Drop cap’ are resetting to default and they aren’t shown when text is re-selected.
02. The ‘Cmd+z’ shows that resetting of the text features happened outside of the ‘quote block’
Check [this video](https://share.cleanshot.com/fHF5x7) for clarification.
