### ISSUE TITLE
Usability feedback: block can only be used once per post

### ISSUE THREAD

**Issue by Rahmon** [WordPress/gutenberg#4353]
## Issue Overview
When a block can only be used once per post there is no message that inform this to user

## Steps to Reproduce (for bugs)
1. Create a block with [useOnce](https://wordpress.org/gutenberg/handbook/block-api/#useonce-optional) attribute set to true
2. Insert the block
3. Try insert the block again

## Expected Behavior
A message that inform that the block can be only used once per post

## Current Behavior
The block is disabled but with no message.

![screenshot from 2018-01-08 08-54-44](https://user-images.githubusercontent.com/6010232/34667814-c9656e56-f451-11e7-8a6d-9f929723aead.png)

**Comment by karmatosed** [comment]
From an end user perspective a message would be better. It's worth noting that disabling is very like the enabled and it's easy to not even notice it's disabled :(

**Comment by karmatosed** [comment]
I think for now having this disabled works but we can come back to this if we need to. I am closing but we can of course always reopen.

**Comment by BrianLaughlan** [comment]
In my opinion, simply having this disabled is not enough. 

Even a tooltip would be great: **"You have already added this block type, it can be only added once."**
