### ISSUE TITLE
Ghost headings

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4354]
This is a weird visual one. I was typing a post and got some ghost headings. I was adding a header before content, wrote it and hit return. This appeared:

![2018-01-08 at 11 18](https://user-images.githubusercontent.com/253067/34668549-ce1793d4-f465-11e7-890c-1f3e9ce350e9.png)

**Comment by iseulde** [comment]
I'm unable to reproduce. Would it be possible to give more detailed steps? Which browser is this? I created a heading, typed something in it, then hit return. All works as expected. Also, I'm not seeing an empty paragraph from the return in your screenshot?

**Comment by karmatosed** [comment]
It's Chrome but in past I have seen this in Safari. I can't recreate at will, it's definitely something that seems to appear randomly but has happened more than once with me. I was really hoping to have a screenshot before. Interestingly this is what the screenshot had over an empty paragraph. Could that indicate the issue?

A few things that may be hints are reasons:
- I had copy and pasted from Google the document
- My Google document had images in (just incase this is bug from that)

**Comment by Soean** [comment]
Related to #2865

**Comment by afercia** [comment]
See also #3784

**Comment by karmatosed** [comment]
Closing as we have reported.

**Comment by iseulde** [comment]
@karmatosed Has this been resolved? Unsure why it's closed now. :)

**Comment by karmatosed** [comment]
I closed it because of #2865 and #3784 duplicating. I figured it likely is the same thing. Apologies if in error though @iseulde - happy to reopen.

**Comment by iseulde** [comment]
@karmatosed I don't know, it may be different if this is still happening in the master branch.

**Comment by karmatosed** [comment]
I haven't seen it in a while. I'll try and break it a little more see if I can make it do it again :)

**Comment by karmatosed** [comment]
I still can't replicate so for now closing.

**Comment by karmatosed** [comment]
I tried to recreate again and I can't on latest branch.
