### ISSUE TITLE
Block templates with specific postTypes that have been edited by the user can be selected for any other post type

### ISSUE THREAD

**Issue by Aljullu** [WordPress/gutenberg#43557]
### Description

I originally opened [this issue in Trac](https://core.trac.wordpress.org/ticket/55881), but moving it here for better visibility.

When a block template provided by a theme has been edited by the user, the `postTypes` argument is ignored, so the template is available for the wrong post types.

### Step-by-step reproduction instructions

1. With a block theme (I used Twenty Twenty Two), create two templates and add them to theme.json:
```JSON
{
	"version": 2,
	"customTemplates": [
		....
		{
			"name": "custom-single-post-template",
			"title": "Custom Single Post template",
			"postTypes": [
				"post"
			]
		},
		{
			"name": "custom-single-post-template-not-modified",
			"title": "Custom Single Post template (not modified)",
			"postTypes": [
				"post"
			]
		}
	],
	...
}
```
2. Go to Appearance > Editor > Templates and make a modification to _Custom Single Post template_.
3. Now, create a new page.
4. Notice in the Template panel in the sidebar, _Custom Single Post template_ is available while _Custom Single Post template (not modified)_ isn't.

### Expected behavior

If the user modifies a template in the Site Editor, that shouldn't affect which post types that template is available for.

### Additional info

I think the issue is caused by [`_build_block_template_result_from_post()`](https://github.com/WordPress/wordpress-develop/blob/91dc2d1b42d8208f257947b9379a37d4df514747/src/wp-includes/block-template-utils.php#L550) not setting a post_types attribute to the returned templates. `_build_block_template_result_from_post()` [is used by `get_block_template()`](https://github.com/WordPress/wordpress-develop/blob/91dc2d1b42d8208f257947b9379a37d4df514747/src/wp-includes/block-template-utils.php#L791).

We identified that issue when working on WooCommerce templates. See [woocommerce/woocommerce#42630](https://github.com/woocommerce/woocommerce/issues/42630).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Aljullu** [comment]
PR created in wordpress-develop: https://github.com/WordPress/wordpress-develop/pull/3131

**Comment by Mamaduka** [comment]
Thanks for the core PR, @Aljullu.

I had a WIP branch for the plugin, which is slightly different from your patch. So I will try to create PR tomorrow morning.
