### ISSUE TITLE
Error in calculateClientWidth function

### ISSUE THREAD

**Issue by tmatsuur** [WordPress/gutenberg#43562]
### Description

When the block inserter is displayed and the mouse pointer is moved from the Columns block to the Buttons block in the DESIGN category, the following error is output to the console.

`block-library.js?ver=dcc9ded9544ed588a6ecc6aee441005c:19989 Uncaught TypeError: Cannot read properties of null (reading 'clientWidth')
    at calculateClientWidth (block-library.js?ver=dcc9ded9544ed588a6ecc6aee441005c:19989:34)`

### Step-by-step reproduction instructions

1. Open a new post page.
2. Open the block inserter.
3. Scroll to where the Design Category is visible and move the mouse pointer over the Columns block.
4. Move the mouse pointer over the Buttons block.

### Environment info

WordPress 6.0.1
Browser: Chrome 104.0.5112.82
OS: Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tmatsuur** [comment]
The relevant source code is as follows:

packages/block-library/src/image/use-client-width.js L10
`	function calculateClientWidth() {
		setClientWidth( ref.current.clientWidth );
	}`

If ref.current is null, the setClientWidth function should not be called to avoid an error.

**Comment by Mamaduka** [comment]
Thanks for reporting the issue. It's a bit hard to reproduce constantly, but I've seen this error before.

I'm going to submit the fix shortly.

**Comment by tmatsuur** [comment]
Thanks @Mamaduka 

I am thrilled with the quick response.
