### ISSUE TITLE
Adding padding to the body in theme.json adds scrollbar to the style variation preview

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#43572]
### Description

When theme.json adds padding to the body (spacing.padding), the padding is visible in the style variation preview in the global styles sidebar.

### Step-by-step reproduction instructions

1. Activate [Twenty Twenty-Three](https://github.com/WordPress/twentytwentythree)
2. In theme.json, add padding to the body (see example below)
3. Open the Site Editor and the styles sidebar

### Screenshots, screen recording, code snippet

100px top padding:

```
		"spacing": {
			"blockGap": "1.5rem",
			"padding": {
				"top": "100px",
				"right": "var(--wp--preset--spacing--30)",
				"bottom": "0px",
				"left": "var(--wp--preset--spacing--30)"
			}
		},

```
![The style variation in the styles sidebar has a scrollbar and does not show the lettering example or colors.](https://user-images.githubusercontent.com/7422055/186398690-a5be71ba-98b9-4a4a-920c-b74268114d12.png)
And on browse styles:
![The browse styles panel preview also shows the padding](https://user-images.githubusercontent.com/7422055/186400194-f4bcd6c0-37a9-4347-8760-7fcc52ef5ba9.png)

### Environment info

WordPress 6.0.1
Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Perhaps related to this issue, it also reproduces in the active style variation preview.

- Open global styles panel.
- Add Padding from layout menu.
- If you go back one step, a scroll bar will appear in the style variation preview.

https://user-images.githubusercontent.com/54422211/186613683-792c7fc6-0720-4f5b-8f10-097ff4809182.mp4
