### ISSUE TITLE
Table Block Edit as HTML converts to HTML Block when Edit Visually is clicked

### ISSUE THREAD

**Issue by flexerd** [WordPress/gutenberg#43582]
### Description

Added a Table block, selected 'Edit as HTML' then 'Edit Visually' Block becomes a 'Custom HTML'  block even if no changes are made to the code.

Old closed issue - https://github.com/WordPress/gutenberg/issues/23511

 With Gutenberg disabled this does not happen and the block behaves normally

### Step-by-step reproduction instructions

1. Add Table Block
2. Add some copy to cells (or not)
3. Click "Edit as HTML"
4. Click "Edit Visually"

### Screenshots, screen recording, code snippet

![edit as html](https://user-images.githubusercontent.com/15328506/186454083-f01b6ee6-4302-4831-8a55-7d997300180c.PNG)
![tabel block before](https://user-images.githubusercontent.com/15328506/186454087-b0d1bd34-bff4-4287-b116-d880df52b19a.PNG)
![table block click visually converts to HTML](https://user-images.githubusercontent.com/15328506/186454090-8af036ec-d4e3-4611-ad1a-90ef5a12634d.PNG)

### Environment info

- Wordpress 6.0.1 Gutenberg - Version 13.9.0  - Custom Theme
- Chrome latest, Firefox latest
- Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting this. It should be fixed by https://github.com/WordPress/gutenberg/pull/43219, which will be in the upcoming Gutenberg v14.
