### ISSUE TITLE
Block pattern stops showing dynamic content after the page template update

### ISSUE THREAD

**Issue by rku4er** [WordPress/gutenberg#43591]
### Description

I am using a block pattern for showing a search query in a search page title. It does work well until I make any style changes to the search template in the site editor. After I save the page it starts showing the static placeholder value. The only way to fix that is to clear customizations via the top menu.

### Step-by-step reproduction instructions

1. Create a block pattern with the code snippet below and put in /your-theme/patterns/ directory to get this loaded automatically.
2. Insert this block pattern in a search page template above the search block. Typically via .
3. Refresh the page and you will see the search query in the page title.
4. Make any changes to any element of that page template in the site editor and hit "save".
5. Refresh the page and you will see the placeholder like for the empty search query.

### Screenshots, screen recording, code snippet

Here is my block pattern code:
```
<?php
/**
 * Title: Search page block pattern
 * Slug: avrw/search
 * Categories: featured
 * inserter: no
 *
 * @package avrw
 * @since 1.0.0
 */

?>
<!-- wp:heading {"className":"is-style-default","fontSize":"x-large"} -->
<h2 class="is-style-default has-x-large-font-size">
<?php
if ( isset( $_GET['s'] ) ) {
	$search_term = sanitize_text_field( wp_unslash( $_GET['s'] ) );
	echo isset( $search_term ) ? sprintf( esc_html__( 'Search results for "%s"', 'avrw' ), esc_html( $search_term ) ) : __( 'Search results', 'avrw' );
} else {
	echo __( 'Search results placeholder title', 'avrw' );
}
?></h2><!-- /wp:heading -->
```

There is a screenshot of the expected behavior: 
![Search-Results-for-“hello”](https://user-images.githubusercontent.com/5741713/186561698-360a049c-6bcb-41de-9821-9701fb3c0adc.png)

There is a screenshot of what I get when I make any minor change and hit "save":
![Search-Results-static-placeholder](https://user-images.githubusercontent.com/5741713/186561793-1a4789bd-a187-4934-8f64-782094ae4013.png)

### Environment info

Wordpress 6.0.1, the theme was generated here - https://fullsiteediting.com/block-theme-generator/

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Once saved, it is only a plain heading block.
_Did you know that there is a search title variation of the query title?_

**Comment by rku4er** [comment]
Oh, I didn't know that, thanks Carolina! But I still can't find how to use that search title variations. Is that something that is available out of the box or I need to add some code to enable such variation for the query title block?

Also I can't find the query title block among the available blocks. I am trying to customize a search page template. Is it available there?

**Comment by Andrew-Starr** [comment]
@rku4er, the default markup for the query title is:
```
<!-- wp:query-title {"type":"archive"} /-->
```

To use it as a dynamic search title, change the `type` attribute to `search` like so:
```
<!-- wp:query-title {"type":"search"} /-->
```

There is no control in the block toolbar to change the query title from archive to search.
Instead the two variations are available in the block inserter as two separate blocks: **Archive Title** and **Search Results Title**.

**Comment by rku4er** [comment]
Thanks Andrew! It's clear now. I just installed the latest Gutenberg 13.9.0 as a separate plugin and now I have that search results title block :) I haven't realized that it's not bundled with WP 6.0.1. I think we can close this ticket.
