### ISSUE TITLE
Transition for TinyMCE styleselect with custom styles

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#4360]
## Issue Overview
With the classic editor, we can add [custom styles into a dropdown](https://codex.wordpress.org/TinyMCE_Custom_Styles) to facilitate the use of custom styles for the user.

![capture d ecran 2018-01-08 a 23 04 41](https://user-images.githubusercontent.com/1521015/34694716-6059a0e0-f4c8-11e7-945c-0101ae0dab03.png)

What will happen to these custom styles?
Will they be automatically converted in some way to blocks or will it be a manual work?

## Current Behavior
In the _Classic Text_ block, there's a style conflict with the _Formats_ dropdown.

![capture d ecran 2018-01-08 a 23 05 43](https://user-images.githubusercontent.com/1521015/34694806-b1bb81ba-f4c8-11e7-946e-d8566f39708a.png)

When we open the dropdown, there are no styles available.

![capture d ecran 2018-01-08 a 23 07 46](https://user-images.githubusercontent.com/1521015/34694826-c98f3ad4-f4c8-11e7-82e2-8c7dafb6e521.png)

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1516902290000016)._
