### ISSUE TITLE
Remove the Navigation Editor Screen

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#43620]
We should remove the code that comprises the experimental Navigation Editor screen (i.e. `@wordpress/edit-navigation` package).

> @getdave, if the Navigation Screen has been removed, does that mean we could review and close pretty much all the open [related issues](https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Navigation%20Screen)?

I think that's reasonable.

_Originally posted by @getdave in https://github.com/WordPress/gutenberg/issues/40878#issuecomment-1227694458_

**Comment by getdave** [comment]
What do you think @draganescu @talldan @scruffian?

**Comment by draganescu** [comment]
I am all for this. It is very likely that we'll never use this as a basis for whatever ends up as being a stand alone editor for the navigation block.

**Comment by getdave** [comment]
cc @mrfoxtalbot @annezazu

**Comment by annezazu** [comment]
Noting that I've already moved this to "inactivate" for the[ feature projects page](https://make.wordpress.org/core/features/) and can always list at as closed too.

**Comment by scruffian** [comment]
I agree, let's remove.
