### ISSUE TITLE
npx @wordpress/create-block stops with "Unexpected token '.'"

### ISSUE THREAD

**Issue by flxspr** [WordPress/gutenberg#43623]
### Description

When running the npx @wordpress/create-block script it just returns "Unexpected token '.'" 

I rolled back to version 3.8.0 and it worked so I think the issue was introduced recently.

### Step-by-step reproduction instructions

1. run 'npx @wordpress/create-block'

### Screenshots, screen recording, code snippet

npx @wordpress/create-block --template ../../../assets
npx: installed 126 in 4.949s
Unexpected token '.'

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thank you for submitting the issue, but I couldn't reproduce it with or without the template option.
Can you please provide us with the following information?

- Do you know the Node version? ( `run node -v` )
- If you don't use `--template` option, does it work correctly?
- What is your OS?

**Comment by flxspr** [comment]
Thank you for the quick reply which immediatly made me recognize the source of the error. I was still using Node v. 12.22.12 which I had to switch to for a legacy project and forgot about switching back via nvm.

Sorry for taking up your time and thank you for the assistance!
