### ISSUE TITLE
Preformatted block maintains border

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4365]
When you are typing the border on blocks goes, see paragraph and pullquote for example. On the preformatted block the border stays:

![2018-01-09 at 10 30](https://user-images.githubusercontent.com/253067/34716596-3ec2da40-f528-11e7-8a84-ae4539b05f34.png)

This is one area we can improve the experience by being consistent.

**Comment by mtias** [comment]
This was the intended design for this block in looking like a code block.

**Comment by karmatosed** [comment]
Hmm, it seemed unusual to me. Ok closing if intended :)

**Comment by mtias** [comment]
We might want to change it. It's also another thing where we should not be too opinionated, deferring to the theme.
