### ISSUE TITLE
Add justification option to Post Content block (and potentially other containers)

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#43650]
I'm attempting to create the following layout in my single post template:

<img width="816" alt="Screenshot 2022-08-26 at 18 48 56" src="https://user-images.githubusercontent.com/846565/186962982-68e9cb2f-3954-4e2c-8978-12db0d76ae26.png">

Note how everything is left-aligned, and the 'wide' width image stretches outwards to the right. 

To do this I have:

* Set 'content' and 'wide' width values in global styles
* Placed a Post Content block at the root of my template, and toggled "Inner blocks respect content width" on

Here's the result:

<img width="814" alt="Screenshot 2022-08-26 at 18 57 13" src="https://user-images.githubusercontent.com/846565/186964149-0b6f210d-18d5-4c43-9b12-4678a47ab8aa.png">

It would be nice if we could bring the Justification option from the Row block to the Post Content block (and probably other containers as well).

**Comment by mtias** [comment]
I've also ran into this. There's also no access to margins so the centered layout cannot be reset. It'd be great to figure out a way to address this, it really hinders the expression you can achieve on themes.
