### ISSUE TITLE
Legacy widgets preview: `Cannot read properties of null (reading 'offsetHeight')`

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#43661]
### Description

This is a tough one to reproduce, and to be honest, I couldn't do it myself yet. However, we've seen thousands of reports captured by Sentry for our WP+GB 13.9.0 instance. 

The exception originates in one of these lines here: https://github.com/WordPress/gutenberg/blob/trunk/packages/widgets/src/blocks/legacy-widget/edit/preview.js#L63-L66,  and happens when users access `wp-admin/widgets.php` and seem to happen when users preview a legacy widget.

Since I couldn't reproduce it yet, I'm documenting it here in hopes core devs might know what's happening or how to reproduce it, or maybe add some additional `null`-resiliency to the code, like @Mamaduka added recently to another function: https://github.com/WordPress/gutenberg/pull/43585.

FWIW, this doesn't seem like a critical issue at the moment - so sit back and relax :) - but I thought I'd track it here sooner than later.

### Step-by-step reproduction instructions

The exception originates in one of these lines here: https://github.com/WordPress/gutenberg/blob/trunk/packages/widgets/src/blocks/legacy-widget/edit/preview.js#L63-L66,  and happens when users access `wp-admin/widgets.php` and seem to happen when users preview a legacy widget. This is all I have for now.

### Environment info

- Wordpress 6.0.1
- Gutenberg 13.9.0
- Chrome 104.0.5112 (among others) 
- Windows 10 (among others)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
@talldan worked recently with iframe resizers for Site Editor; maybe some of the safeguards can also be adopted here. PR #43408.

**Comment by Thelmachido** [comment]
Hi @talldan any chance you might be able to take a look at this one, there hasn't been much activity on it.

**Comment by talldan** [comment]
I also wasn't able to reproduce any problems with legacy widgets, but I've put together a PR (#44635) that adds some extra guarding to the code.

It may not be perfect, there's a good chance other parts of this code may also throw errors, but I think it's ok to wait and see and tackle that if it happens.

The problem is likely being caused by a specific plugin, so if there's any way to find out which plugin that would be helpful.
