### ISSUE TITLE
Adding a link to a cover image causes you to be unable to read it

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4366]
On the cover image the link styling means this happens:

![2018-01-09 at 10 34](https://user-images.githubusercontent.com/253067/34716774-c4608fb2-f528-11e7-9605-250697f3d0f5.png)

**Comment by rileybrook** [comment]
@karmatosed I believe this might be fixed now  (SS below)

<img width="624" alt="screen shot 2018-01-31 at 6 56 12 pm" src="https://user-images.githubusercontent.com/7691812/35657193-7f8237a0-06b8-11e8-9256-488f3f08804c.png">

**Comment by karmatosed** [comment]
Yes this seems fixed now, great. Thanks for testing @rileybrook.
