### ISSUE TITLE
Post Featured Image block: Enable gradient overlay

### ISSUE THREAD

**Issue by luminuu** [WordPress/gutenberg#43676]
## What problem does this address?

While creating a design for Twenty Twenty-Three, I noticed it's not possible to add a gradient overlay to the featured images of posts, as the Post Featured Image block is used, where this feature is not available. It would be possible with using a Cover block, which can also display the featured image; however it's not intended to change the markup of Twenty Twenty-Three.

## What is your proposed solution?

To enhance the Post Featured Image block, the overlay feature from the Cover block should be made available. This would enable more design possibilities using this block, without having to rely on the Cover block instead.

**Comment by luminuu** [comment]
The style variation I was working on where I discovered this issue (Figma only atm): https://github.com/WordPress/twentytwentythree/issues/134

**Comment by RahiDroid** [comment]
Hi @luminuu 👋 

Came here tracking down conversations from TT3. I think I might be able to help with this one. I have a work-in-progress PR ready with some base. I had a question though, should the overlay settings be applied to the placeholder too? Checkout the screencast in PR https://github.com/RahiDroid/gutenberg/pull/1

**Comment by luminuu** [comment]
> Hi @luminuu 👋
> 
> Came here tracking down conversations from TT3. I think I might be able to help with this one. I have a work-in-progress PR ready with some base. I had a question though, should the overlay settings be applied to the placeholder too? Checkout the screencast in PR [RahiDroid#1](https://github.com/RahiDroid/gutenberg/pull/1)

Thank you @RahiDroid for your work on this! I don't know if it's possible to set a default overlay via theme.json, I haven't tested it at the Cover block so far. If this would be possible it would be very nice to have it at the Post Featured Image block, so the design is reflected even if there are no images uploaded yet to the site. Makes sense to me.

**Comment by RahiDroid** [comment]
Heyya @luminuu  👋 

I did some testing and research, and it doesn't seem possible to set a default overlay color using `theme.json`. Regardless, I applied the overlay settings on the placeholder, too.

I have raised PR #43838 for this issue.
