### ISSUE TITLE
If you publish a post with <script> in the title, the block editor will crash on next reload

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#43695]
### Description

if you publish a post with `<script>` or `<img src=''>` in the title, the block editor will crash on next reload.

### Step-by-step reproduction instructions

1. Create a new post. with title `Test with <script>`.
2. Publish the post
3. Refresh the page

**Comment by t-hamano** [comment]
I would like to close this issue as I believe it is the same as #41581.

**Comment by aristath** [comment]
You're right, it's the same issue. I just didn't find it when looking prior to creating this ticket. 
Thanks!
