### ISSUE TITLE
Enable copy/cut shortcut on the site editor

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#43709]
## What problem does this address?
I was testing shortcuts on Windows in #43352 and found that the copy/cut shortcut doesn't work only in the site editor.
This does not seem to be an OS issue.

Personally, I feel it is very inconvenient that this shortcut is not available in the site editor.

## What is your proposed solution?
Unless there is a clear reason not to opt-in to this shortcut in the site editor only, I believe the shortcut should be added like any other editor.

As a test, I merged the `useClipboardHandler` into the following ref, and the shortcuts seem to work on the site editor:

https://github.com/WordPress/gutenberg/blob/1d778aa5e7506390c4d1a89974ec69088026855a/packages/edit-site/src/components/block-editor/index.js#L122

## Screencast

https://user-images.githubusercontent.com/54422211/187456903-2fa72e47-468f-4664-b1f9-82846a32e0cb.mp4

**Comment by noisysocks** [comment]
Hi @t-hamano I unassigned you as I can't see that you're working on this. Re-assign yourself if I'm mistaken 😀

**Comment by t-hamano** [comment]
@noisysocks 
Sorry, I forgot to address this issue. I hope to submit a PR soon.
