### ISSUE TITLE
Home link: Missing closing tag

### ISSUE THREAD

**Issue by Gierand** [WordPress/gutenberg#43705]
### Description

Block doesn't have a valid closing `</li>` tag.

### Step-by-step reproduction instructions

[Source.](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/home-link/index.php#L131)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for contributing, @Gierand.

This was a regression I missed during the recent refactor. I will create PR shortly.
