### ISSUE TITLE
Add Gutter/Spacing option on Gallery Block

### ISSUE THREAD

**Issue by monika-12** [WordPress/gutenberg#4375]
## Issue Overview

There should be gutter/ spacing option on gallery block on reduce/ remove spacing between blocks.

## Steps to Reproduce (for bugs)
1. Add gallery block
2. Add Columns
3. No spacing Option

## Expected Behavior
 spacing option should be there to add spacing between columns.

**Comment by karmatosed** [comment]
In this case spacing should be up to the theme. An example of what a theme could have is like this:

![2018-01-10 at 11 12](https://user-images.githubusercontent.com/253067/34769938-4714f65e-f5f7-11e7-9785-0d4a3e8647b2.png)

Within the editor you see by default:

![2018-01-10 at 11 13](https://user-images.githubusercontent.com/253067/34769953-518a37a2-f5f7-11e7-8005-7cd4667aadf5.png)

For now, closing this as guttering and spacing within Gutenberg is going to be down to the theme on presentation. 

That all said, if you do not see what I do then please provide a screenshot and what browser you are using - we totally may have a bug in that case.

**Comment by gfrow** [comment]
I'm also having the same issue. I've tried multiple themes and I still can't remove the gutters.

**Comment by karmatosed** [comment]
@gfrow are you using a particular theme or browser? I would love to get to the bottom of why this problem appears.
