### ISSUE TITLE
Block editor: Text goes edge-to-edge with Gutenberg 14.0.0 on some themes

### ISSUE THREAD

**Issue by aisajib** [WordPress/gutenberg#43752]
### Description

With Gutenberg 14.0.0 installed, there's an issue that's causing text in the block editor to go edge-to-edge. The frontend remains unaffected (when you preview or publish the post). 

Additionally, the issue is only present on classic (non-FSE) themes. 

### Step-by-step reproduction instructions

1. Install the latest version of Gutenberg (v14.0.0).
2. Install and activate a classic theme ([Twenty Twenty](https://wordpress.org/themes/twentytwenty/), for example)
3. Go to Posts → Add New. 
4. Type some text and notice that the text is edge-to-edge. 

### Screenshots, screen recording, code snippet

Here's a screenshot with Twenty Twenty active but Gutenberg v14.0.0 deactivated. (The expected result) 

<img width="1408" alt="Screen Shot 2022-09-01 at 4 00 30 AM" src="https://user-images.githubusercontent.com/2541844/187792929-11e8ae1c-858a-4382-b11b-a4a224e77a77.png">

Here's with Twenty Twenty and Gutenberg v14.0.0 both active. 

<img width="1405" alt="Screen Shot 2022-09-01 at 3 59 53 AM" src="https://user-images.githubusercontent.com/2541844/187792824-333c7fde-71b7-47d8-87f7-2a6eca8d24f8.png">

### Environment info

Tested this on:
* WordPress 6.0.2
* Gutenberg v14.0.0
* macOS 12.5.1
* Google Chrome 104.0.5112.101 (Official Build) (arm64)

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by priethor** [comment]
I can reproduce the issue as well. It's also affecting make.wordpress.org blogs.
