### ISSUE TITLE
[GB 14.0.0] Bug: Pasting block markups with an empty List block crashes the editor

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#43753]
### Description

Pasting a block markup with an empty List block results in an uncaught exception that WSODs the editor. Not sure if it's specific to the List block or something more far-reaching that could affect other blocks, though. and

### Step-by-step reproduction instructions

1. Clone GB locally and checkout the `v14.0.0` tag;
2. Build it: `npm ci && npm run dev`;
3. Start `wp-env`: `npx wp-env start .`;
4. Login to your local `wp-env` instance, make sure `v14.0.0` is activated and start a new Post;
5. Paste the following block markup in the code editor:

```
<!-- wp:list -->
<ul><li></li></ul>
<!-- /wp:list -->
```

6. You'll see a WSOD (though the left sideber will still be visible), you'll notice an exception in the JS console:

```
Uncaught TypeError: can't access property "tagName", nestedList is undefined
    innerBlocks utils.js:33
    createListBlockFromDOMElement utils.js:22
    migrateToListV2 utils.js:78
    applyBlockDeprecatedVersions apply-block-deprecated-versions.js:107
    parseRawBlock index.js:250
    parse index.js:311
    parse index.js:310
    stopEditing index.js:64
```

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/81248/187809756-78f57346-f3e6-49b7-a8f4-3a8924c2fa8e.mp4

### Environment info

- Wordpress 6.1-alpha-54044
- Gutenberg 14.0.0
- Firefox 105.0b5 (Linux 64-bit)
- Ubuntu Linux 18.04

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by oandregal** [comment]
Got a fix at https://github.com/WordPress/gutenberg/pull/43761
