### ISSUE TITLE
Heading Tag Inconsistency on Heading Block

### ISSUE THREAD

**Issue by monika-12** [WordPress/gutenberg#4376]
## Issue Overview
There is inconsistency on Heading in inline editor setting and block settings. In Inline Editor only H2, H3, H4 heading tag displayed but in block setting all Heading tag from H1 to H6 displayed properly so keep consistency between inline-editor and block settings.

## Steps to Reproduce (for bugs)
1. Add Heading 
2. There is H2, H3, H4 tag option displayed
3. Check Block settings options are H1 to H6

## Screenshots / Video
Inline Editor
![inline-editor](https://user-images.githubusercontent.com/17018981/34764353-39c66be6-f614-11e7-8434-d2a64b55976d.png)

Block 
![block](https://user-images.githubusercontent.com/17018981/34764352-398687c4-f614-11e7-86b7-497859736362.png)

**Comment by Soean** [comment]
He @monika-12,
thanks for your issue, we already have a ticket for this issue in #2244
You can comment there, why we should add the missing options.
