### ISSUE TITLE
Gutenberg is not compatible with PressThis

### ISSUE THREAD

**Issue by barbayellow** [WordPress/gutenberg#4377]
## Issue Overview

gutengberg is not copmpatible with the Pressthis plugin (which used to be in wp core)  : when publishing a post using pressthis, once I come back to the Gutenberg editor, I can't access to the body of my post. Unless I switch to the code editor mode.
## Steps to Reproduce (for bugs)

1. Install the PressThis plugin
2. Select an interesting article and publish it using the PressThis bookmarklet
3. In the Gutenberg editor, try to edit the post
3.
4.

Firefox Quantum, 57.0.4 64bits, Gnome Ubuntu

## Expected Behavior

The Gutenberg editor should allow me at least to turn the post I created using pressthis into blocks

## Current Behavior

It does not. I have to edit it in code mode.
## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ajitbohra** [comment]
Works as expected on master / v3.2

**Comment by StaggerLeee** [comment]
After some intensive usage I can say only who needs PressThis in Gutenberg. Amazing how identical copy of a web Page Gutenberg makes. Copy Page, paste it in Gutenberg Paragraph block, and it is almost identical as original. Never before I had such good end results with PressThis or plugins with similar functionality.
