### ISSUE TITLE
Alignment not working on Quote Citation

### ISSUE THREAD

**Issue by monika-12** [WordPress/gutenberg#4378]
**## Issue Overview**
Alignment option on Quote Citation not working it only works on Paragraph.
 
**## Steps to Reproduce (for bugs)**
1. Insert Quote Block
2. Enter paragraph and citation
3. Apply alignment option

**## Expected Behavior**
Alignment option should works on Citation with Paragraph.

**## Current Behavior**
Alignment option only working on Paragraph

**## Screenshots / Video**
![quote-alignment](https://user-images.githubusercontent.com/17018981/34765427-7fb9d6da-f617-11e7-9273-594b6913273f.png)

**Comment by karmatosed** [comment]
I agree, it should either align everything or not align anything. My suggestion is we align everything.
