### ISSUE TITLE
Template lock: Apply selected state to container block in list view

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#43780]
Something we missed in https://github.com/WordPress/gutenberg/pull/43037. When any block within a container is selected, the parent should also be selected in List view. At the moment it is not:

<img src="https://user-images.githubusercontent.com/846565/187882941-84f8e06d-0d7e-4c7b-8fae-98b590018187.png">

cc @jorgefilipecosta

**Comment by jorgefilipecosta** [comment]
Thank you for reporting this issue @jameskoster a PR with the fix is available at https://github.com/WordPress/gutenberg/pull/43918.
