### ISSUE TITLE
showPrefix in Query title Block not working

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#43788]
### Description

If using `<!-- wp:query-title {"type":"archive","showPrefix":"false"} /-->` in the index.html template file, the word "Category" or "Tag" still appears when viewing an individual taxonomy page.

### Step-by-step reproduction instructions

1. In the default WP theme, add `<!-- wp:query-title {"type":"archive","showPrefix":"false"} /-->` to the index.html and archive.html templates
2. Create a post with a category and a tag
3. View the category and tag archive pages
4. See the word "category:" and "tag:" still present

### Environment info

- WP 6.0.2
- Gutenberg 14.0.2
- Chrome
- Mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi!
I did not understand the description. I am reading it as "If you add the block to the _index_,  the text still appears on the _archive_"  I mean, that would be correct, if you did not update the archive? I'm lost :) 
Are you viewing the index or the taxonomy page?

**Comment by bradhogan** [comment]
Sorry for the confusion, here's a quick video that should help show the issue > https://soapbox.wistia.com/videos/ZQzchV12N6

**Comment by t-hamano** [comment]
Hi @bradley2083,

Please try `"showPrefix":false`, not `"showPrefix":"false"`.
I think boolean values should not be enclosed in double-quotes.

**Comment by bradhogan** [comment]
Tried both neither seems to work unfortunately.

**Comment by carolinan** [comment]
Yes it should be false without the quotes.
I am not able to reproduce this. WordPress 6.0.2, Gutenberg 14.0.2, no other plugins active, Chrome on mac, PHP 8.0.0, nginx.

Did you check if there are block validation errors in the Site Editor, and if the site editor shows the block correctly?
No other plugins that are filtering the title?

**Comment by bradhogan** [comment]
Seems to be working.  Not sure what the issue was (maybe Local caching).  Thanks!
