### ISSUE TITLE
babel-plugin-makepot: "translations is not iterable"

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#43793]
### Description

After I updated a project's `@wordpress/babel-plugin-makepot` dependency to 5.0.0, its build started showing a TypeError with the message "translations is not iterable".

I looked at the commit history for the package and while the [release notes show an upgrade to Node 14](https://github.com/WordPress/gutenberg/blob/95f71eda35d96a29fe52600994ee058d1765c604/packages/babel-plugin-makepot/CHANGELOG.md) as a breaking change, [a commit was included](https://github.com/WordPress/gutenberg/commit/6f94c67f05cdd50ab7fb505ab7e6973affe3996a) that replaces the use of Lodash's `sortBy()`.

I am not an expert by any means, but from what I can tell, Lodash's `sortBy()` [expected either an array or an object to be passed](https://docs-lodash.com/v4/sort-by/). The new `sortByReference()` added to babel-plugin-makepot as a replacement expects and handles only arrays even though the translations passed to it by babel-plugin-makepot are always objects.

I can't find an example of how Gutenberg or WordPress are using this package, so I'm not completely confident that I'm not doing something wrong, but I've reproduced the issue in a simple package and have found [at least one example on GitHub of another project using this package](https://github.com/myrotvorets/wp-plugin-identigraf/runs/8127714999?check_suite_focus=true) with the same error.

### Step-by-step reproduction instructions

1. Check out https://github.com/jeremyfelt/babel-bug/tree/wp-babel-5.0.0
2. `npm install`
3. `npm run build`

If you check out the `wp-babel-4.0.0` branch on that project, there is no error.

### Environment info

* Node 16.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Cc @tyxla

**Comment by tyxla** [comment]
Thanks for reporting @jeremyfelt 🙌 .

For some odd reason, this never came up in my testing or in the review of the related PR - https://github.com/WordPress/gutenberg/pull/43479. I must have been testing it the wrong way.

Fix incoming shortly.

**Comment by tyxla** [comment]
Fix in #43797.

This will obviously need a point release after merging.

**Comment by jeremyfelt** [comment]
Works great, thanks for the quick fix @tyxla!
