### ISSUE TITLE
Full width and overflow problem

### ISSUE THREAD

**Issue by Gierand** [WordPress/gutenberg#43795]
### Description

The situation occurs as we set the horizontal padding to 0px in the parent block (group block).

### Step-by-step reproduction instructions

1. Add a group block.
2. Add a image block to inner group block.
3. Set the group and image blocks to full width.
4. In the group block, set the padding dimensions to 0px (left, right).

### Screenshots, screen recording, code snippet

![screen](https://user-images.githubusercontent.com/1615208/188063730-2a339255-c987-4142-9957-34fd5abffead.jpg)

### Environment info

WordPress version: 6.0.2 and 6.1-alpha-54058
Gutenberg version: 14.1.20220901
Theme: TT2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I believe this is a theme-specific issue. This is not reproduced in Twenty Twenty or Twenty Twenty One.
In TT2, negative margins are used to represent full-width, but this seems to occur when full-width blocks are nested.
