### ISSUE TITLE
Consider providing spacing presets for height of spacer block

### ISSUE THREAD

**Issue by mikachan** [WordPress/gutenberg#43816]
## What problem does this address?

When adding a spacer block, the height can currently only be set using the manual height control:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/1645628/188143264-59c67c76-934d-4d11-bc8c-b1e1ea796870.png">

## What is your proposed solution?

It would be nice if the height could also be set using any available spacing presets, similar to how margin, padding, and block gap settings now work:

<img width="284" alt="image" src="https://user-images.githubusercontent.com/1645628/188143481-bb5ddf1e-41d1-4a43-802b-64c34b1c2582.png">

Related PRs:
https://github.com/WordPress/gutenberg/pull/42173
https://github.com/WordPress/gutenberg/pull/43466
https://github.com/WordPress/gutenberg/pull/43246

**Comment by richtabor** [comment]
Agreed! No reason why it should adopt the same model imo.

**Comment by richtabor** [comment]
@mikachan This looks to be a duplicate of #43815 — accident?

**Comment by mikachan** [comment]
> This looks to be a duplicate of https://github.com/WordPress/gutenberg/issues/43815 — accident?

Ugh yes thanks, I think I hit a shortcut to save the issue before I was ready! 🙈

**Comment by bgardner** [comment]
Huge fan of this—great suggestion @mikachan!

**Comment by glendaviesnz** [comment]
Have added to the [Spacing presets tracking issue](https://github.com/WordPress/gutenberg/issues/39371).

<img width="284" alt="image" src="https://user-images.githubusercontent.com/1645628/188143481-bb5ddf1e-41d1-4a43-802b-64c34b1c2582.png">

@mikachan do you always see the white segment square displaying over the range control thumb? Does it disappear if you do a hard refresh? Seems to happen intermittently for some people so would be good to try and track down why sometimes the correct z-index is not applied.

**Comment by mikachan** [comment]
Thanks for adding this to the tracking issue!

> do you always see the white segment square displaying over the range control thumb? Does it disappear if you do a hard refresh?

Yes, it seems to have disappeared after a hard refresh (I've also just pulled the latest trunk, although I was only 6 commits behind).

<img width="272" alt="image" src="https://user-images.githubusercontent.com/1645628/188416017-b99821a1-4b97-4755-91b9-a19754050cd8.png">

I'm not sure if I've always seen it.. I'll keep my eye on it and see if it seems intermittent for me.

**Comment by mikachan** [comment]
Closing this as https://github.com/WordPress/gutenberg/pull/44002 should address it 🎉
