### ISSUE TITLE
Search Block : Concatenation issue for increament operator.

### ISSUE THREAD

**Issue by haritpanchal** [WordPress/gutenberg#43819]
### Description

Increment and decrement operators must be bracketed when used in string concatenation.

### Step-by-step reproduction instructions

1. File path: /wp-includes/blocks/search.php
2. Line: 30.

### Screenshots, screen recording, code snippet

Diff file 

diff --git a/src/wp-includes/blocks/search.php b/src/wp-includes/blocks/search.php
index 94ec6fc4ac..b5153e46f6 100644
--- a/src/wp-includes/blocks/search.php
+++ b/src/wp-includes/blocks/search.php
@@ -27,7 +27,7 @@ function render_block_core_search( $attributes ) {
 		)
 	);
 
-	$input_id         = 'wp-block-search__input-' . ++$instance_id;
+	$input_id         = 'wp-block-search__input-' . ( ++$instance_id );

### Environment info

WordPress version: 6.0.1
Gutenberg version: 13.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I would like to close this issue as the points you reported have been fixed in part #41147.
Thank you for your contribution 👍
