### ISSUE TITLE
Custom HTML block - Extremely Slow when loading editor styles

### ISSUE THREAD

**Issue by cb911nr** [WordPress/gutenberg#43820]
### Description

For some reason the HTML Block widget, is extremely slow to type into when you're loading editor styles, the more you load the even slower it gets. 

You can kind of see this with the Twenty Twenty One theme, compared to the Twenty Twenty Two, and then when we use our theme which loads even more editor styles, it is extremely bogged down..

Any ideas on how to stop that from bogging down based on the editor styles being loaded?

### Step-by-step reproduction instructions

1. Activate a theme that loads editor styles
2. Add HTML Block widget
3. Type into the HTML Block to see the performance differences

### Screenshots, screen recording, code snippet

Twenty Twenty Two Theme (fastest, great):
![twentytwentytwo](https://user-images.githubusercontent.com/38040900/188175991-441f57af-11e9-4760-bb52-e11c1308eee4.gif)

Twenty Twenty One Theme (slower):
![twentytwentyone](https://user-images.githubusercontent.com/38040900/188175861-ddf45818-f117-4040-b444-bd37eac5bd8d.gif)

Our Theme (even slower) (I was actively typing, so when all the text pops in that was not a copy and paste haha):
![ourtheme](https://user-images.githubusercontent.com/38040900/188176042-736b6b3b-80bb-4c18-8662-6c5ca5de1f04.gif)

For fun here's our theme again, but I removed add_editor_style() css sheet we were loading. Way faster.
![editorstylesremoved](https://user-images.githubusercontent.com/38040900/188178259-a21ffff5-f3ca-40dd-a88f-d92ac52b0a88.gif)

### Environment info

- Wordpress Version 6.0.2
- Whatever Gutenberg version comes with that above

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
The issue was recently fixed via #42026. The fix will be available in WP 6.1.
