### ISSUE TITLE
More granular control of wide/full block alignment options

### ISSUE THREAD

**Issue by mattheu** [WordPress/gutenberg#4383]
Currently, you can opt-in to the wide and full width block alignment options using `add_theme_support( 'align-wide' )`, however this assumes that all pages on your site either support this, or not.

My use case is that for posts I have a template with a sidebar, but for pages, the template can support full width blocks.

Theme support is a good catch all, but I suspect a common requirement would be for more granular control of this. Certainly at a post type level and a page template level (once implemented).

Perhaps this is already possible, or a duplicate of an existing ticket although I couldn't see one.

**Comment by youknowriad** [comment]
Hi @mattheu that's a valid concern. However, we already discussed these APIs (can't find the issue unfortunately) and we settled on not being too granular but this will only create APIs not useful for most use-cases. 

For example, some could argue that the support should be per block, others per CPT or even per CPT's template.

The concern was that we'll end up with hundreds of unused APIs.
