### ISSUE TITLE
Current menu item doesn't work with custom homepages

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#43843]
The Navigation block's current menu item class doesn't seem to work for the blog when the home page is set to a static page. i.e. If the blog itself is actually a page, the navigation menu doesn't get the current-menu-item class added to it. 

__Originally posted by @timnicholson in https://github.com/WordPress/gutenberg/issues/19993#issuecomment-1235961805__

**Comment by carolinan** [comment]
This is solved in https://github.com/WordPress/gutenberg/pull/43800
