### ISSUE TITLE
Unable to redo text entry for List block

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#43875]
## Description
When using undo and redo actions, it is not possible to add once removed list items back to the list.  If the _List_ block itself is not removed, then the bug does not occur. 

## Step-by-step reproduction instructions
1. Insert a _List_ block with the native editor.  
1. Add several list times. 
1. Tap the "undo" button to remove all the items _and the list_. 
1. Tap the "redo" button several times. 

## Expected behaviour
The _List_ block is returned to the editor with all of the original list items. 

## Actual behaviour
An empty _List_ block is placed in the editor. The "redo" button is disabled. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/438664/188504475-22a7aecd-e7be-4792-87b8-cafd42fead66.MP4

## WordPress information
- WordPress version: 6.1
- Gutenberg version: 14.0.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Geologist

## Device information
- Device: iPhone SE
- Operating system: iOS 16 beta 6
- WordPress app version: 20.7

**Comment by fluiddot** [comment]
I confirm this issue can also be reproduced in the web version, I opened a [GitHub issue as a follow-up](https://github.com/WordPress/gutenberg/issues/44196).

**Comment by fluiddot** [comment]
I tried to debug the issue and shared the results in [this comment](https://github.com/WordPress/gutenberg/issues/44196#issuecomment-1248364548). I haven't managed to find a workaround yet, probably I'll try to reach out to contributors that have more experience with the undo/redo mechanism, in case they could provide further guidance on how to approach it.

**Comment by geriux** [comment]
I've just checked this and I can confirm it is working now as expected on both the app and the web editor, there were some improvements done to this block and how it works inserting list items so I'm guessing one of those improvements solved this problem. I'll close this issue.
