### ISSUE TITLE
Code block: Add option to transform back to Paragraph 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#43879]
## What problem does this address?

Currently, one can transform from a paragraph block to a code block but, in order to transform back to a paragaph block, one must first transform from code to pre-formatted and then an option for a paragraph block appears. This was found as part of the [sixteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/08/13/fse-program-testing-call-16-back-to-basics/#comment-2700): 

>Changing a paragraph into any blocks can easily be reverted back into a Paragraph Block, except when it is changed to a Code Block. While one can easily unwrap a quote back to a paragraph, or revert a pullquote, a preformatted, a verse, a heading, or a list back to paragraph block. The same effortlessness is gone once the paragraph is transformed to a Code Block. Here one is faced with unintuitive options to operate on the Code Block (quote, preformatted, group, columns, custom HTML). To transform the Code Block into a paragraph, it needs to be changed into a Preformatted Block first.

https://user-images.githubusercontent.com/26996883/188517189-f52bfd70-1b60-470c-811a-10ea4a515dda.mov

## What is your proposed solution?

Add the option to transform to a paragraph block to the code block's transform menu:

<img width="778" alt="Screen Shot 2022-09-05 at 3 31 30 PM" src="https://user-images.githubusercontent.com/26996883/188517610-058c2901-083a-4aeb-8c36-00a7db443ffe.png">

**Comment by annezazu** [comment]
The option to switch from Paragraph to Code was originally implemented here: https://github.com/WordPress/gutenberg/pull/38295 The reverse just wasn't done :)

**Comment by Mamaduka** [comment]
Happy to handle this one.
