### ISSUE TITLE
Unable to split List V2 block from middle of list

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#43873]
## Description
When the cursor is placed at the end of a list item position in the middle of the list, it is not possibly to split the list block by pressing the <kbd>Return</kbd> key twice. This appears to have begun occurring with List V2 blocks enabled using inner blocks. 

## Step-by-step reproduction instructions
1. Insert a _List_ block with the native editor.  
1. Add at least three items to the list. 
1. Place the cursor at the end of one of the items in the middle of the list. 
1. Press the <kbd>Return</kbd> twice. 

## Expected behaviour
The _List_ block is split in half. The editor contains: 

1. A _List_ block with the first half of list items. 
1. An empty _Paragraph_ block with cursor focus. 
1. A _List_ block with the second half of list items. 

## Actual behaviour
The editor contains a single _List_ block with an item list item in the middle of the list. 

## Screenshots or screen recording (optional)

<details><summary>Expected</summary> 

https://user-images.githubusercontent.com/438664/188503552-7966b3d7-a5a5-4bf7-ac30-2b593163acca.MP4

</details>

<details><summary>Actual</summary> 

https://user-images.githubusercontent.com/438664/188503537-ecb33e65-e18d-4a81-a84a-0b9cfc32b7dd.MP4

</details>

## WordPress information
- WordPress version: 6.1
- Gutenberg version: 14.0.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Geologist

## Device information
- Device: iPhone SE
- Operating system: iOS 16 beta 6
- WordPress app version: 20.5

**Comment by geriux** [comment]
Closing since the fix was already addressed and we will track adding E2E tests in this issue https://github.com/WordPress/gutenberg/issues/44113
