### ISSUE TITLE
Unlinking Submenu block causes empty `href` attribute on front of site

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#43897]
### Description

Unlinking Submenu block causes empty `href` attribute on front of site.

### Step-by-step reproduction instructions

1. Add Nav block.
2. Add Submenu with a link and add one item inside the submenu.
3. Click on Submenu block and click the link icon.
4. Remove the link from the block using the "Unlink" icon in the Link UI.
5. Publish post.
6. Switch to front of site and see empty `href` on the submenu item in the Nav.

### Screenshots, screen recording, code snippet

<img width="980" alt="Screen Shot 2022-09-06 at 10 27 53" src="https://user-images.githubusercontent.com/444434/188599569-622b9443-e290-455a-81c6-ad87c697d15c.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi,
What is the expected result? I mean, what change needs to be implemented, should the whole link be removed, and only text displayed?

**Comment by getdave** [comment]
I don't have the answer to that at this stage. An empty `href` is invalid so we'd need to decide on the most appropriate markup and / or behaviour.

**Comment by aristath** [comment]
Hmmm if empty we could make it `#`. Would that make sense?

**Comment by getdave** [comment]
I looked into this some more. I turns out it's [valid to have `a` elements without an `href`](https://html.spec.whatwg.org/multipage/links.html#links-created-by-a-and-area-elements).

> The [href](https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-href) [a](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element)ttribute on a and [area](https://html.spec.whatwg.org/multipage/image-maps.html#the-area-element) elements is not required; when those elements do not have [href](https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-href) attributes they do not create hyperlinks.

I've created a PR which conditionally adds the `href` depending on whether it's not empty.

https://github.com/WordPress/gutenberg/pull/44337
