### ISSUE TITLE
Inconsistent Naming

### ISSUE THREAD

**Issue by travislopes** [WordPress/gutenberg#4390]
With recent changes to Gutenberg, there are naming inconsistencies surrounding the Block sidebar settings.

In the ellipses drop down next to a block, there is a "Hide/Show Advanced Settings" link. Clicking on the link focuses the "Format" (formally "Block") sidebar tab.

This can cause confusion in multiple ways.

We're currently building out a (soon to be released) Gravity Forms block to allow customers to display their forms within their posts and pages with more in-depth configuration options.

![screen shot 2018-01-10 at 4 41 10 pm](https://user-images.githubusercontent.com/12767/34800607-8b8f93b2-f632-11e7-9fb1-90d274c630e2.png)

Within the list of block settings, there are a group that are hidden within an "Advanced Settings" accordion. These are both settings not frequently used and attributes previously available through the Gravity Forms shortcode that need to exist for backwards compatbility. Clicking on the "Show Advanced Settings" ellipses drop down link is now taking you to a sidebar that contains another "Advanced Settings" section.

![screen shot 2018-01-10 at 4 41 33 pm](https://user-images.githubusercontent.com/12767/34800609-8b9c1966-f632-11e7-9c38-f8090c37e42b.png)

The sidebar tab name being "Format" is also confusing as none of the settings displayed in this block are formatting related; they all center around controlling the content displayed within the block.

Naming both the ellipses drop down link and the sidebar tab "Settings" or allowing developers to define both the drop down link and sidebar tabs names at the block level would resolve the confusion.

**Comment by carlhancock** [comment]
Making the labels for everything pluggable is the solution and it is something that should be done for extensibility.

Everything needs to be customizable. Plugins should be able to control their block, including what UI elements are called and their related settings.

People also use WordPress to build custom platforms and even web apps. They are going to want to be able to customize things like the labels and what things are called. The end result may not even be promoted as being WordPress. For example a hosted web site solution for restaurants. Or a hosted service for tour guide web sites. This is one of many ways that WordPress is used.

For those reasons making the labels customizable via code is something that should be possible.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1516902709000831)._

**Comment by danielbachhuber** [comment]
@travislopes @carlhancock Are there any remaining actionable items in this issue, or can it be closed?
