### ISSUE TITLE
Styles sidebar: Comment pagination inner blocks have the same button text as Query pagination inner blocks

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#43907]
### Description

In the global styles sidebar in the site editor, the inner blocks of the comment pagination and the query pagination have the same button text, so it is difficult to tell them apart.
For example, both the query pagination next and comment pagination next have the button text "Next Page".

### Step-by-step reproduction instructions

1. Activate a theme with support for the site editor
2. Go to the site editor and open the styles sidebar. Select blocks.
3. In the search field, enter "next". See that there is more than one block with the same button text.

### Screenshots, screen recording, code snippet

<img width="287" alt="The styles sidebar with a list of blocks that has the same button text" src="https://user-images.githubusercontent.com/7422055/188638463-4745ce4a-3633-40ca-9063-a589f5484063.png">

### Environment info

WordPress 6.0.2
Gutenberg current trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@ockham wanted to flag for you :) Would be great to get this quickly renamed/cleared up for the comments block.

**Comment by ockham** [comment]
Thanks for flagging! Should be easy enough to rename 😄 Just to clarify, this is the block name, so it'll also change e.g. in the block inserter.

What should we call it? 

Some ideas: 
- "Next Comments Page"
- "Comments: Next Page"
- "Comments Next Page" (no colon -- more consistent with "Comment Pagination", but kinda ugly IMO)

Do we have precedent for something like this? I.e. naming "subordinate" (inner) blocks for a parent block? 🤔

**Comment by annezazu** [comment]
I'm not sure if we do! I'd recommend asking in Core Editor to see if anyone might have some insights there. I'm afraid I don't have capacity to dive in deeper this week.
