### ISSUE TITLE
List v2: New keyboard shortcut "[[" doesn't work with new list block 

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#43923]
### Description

In a list I tried to use the "[[" shortcut to create a link from the site. It didn't work in a list item block. 
Below you find a short video when [[ works and when it doesn't. 

It worked with List Block V1, though. 

### Step-by-step reproduction instructions

- Create post
- Add a list block
- try to add an internal link with by typing [[

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/39980/188723992-04e7c8ee-34f7-4f31-8ca4-ce458767707b.mp4

### Environment info

WP 6.0.2  and WordPress 6.1-alpha-54064
Gutenberg Nightly 
Chrome 104.0.5112.101 (Official Build) (arm64)
MacOS 12.5.1 (M1)

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
cc @ellatrix  in case you might have any insights based on your work with the List v2.

**Comment by ellatrix** [comment]
Looking into it
