### ISSUE TITLE
Navigation: root padding takes precedence over navigation block padding

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#43931]
### Description

Root padding gains higher specificity over the padding set for `core/navigation` block.
Because of this it is not possible to override the padding of navigation block.

Similar issue also with margin.

### Step-by-step reproduction instructions

Set a root padding in `theme.json`

```json
{
    "styles": {
        "spacing": {
            "padding": {
                "bottom": "2rem",
                "left": "2rem",
                "right": "2rem",
                "top": "2rem"
            }
        }
    }
}
```

Now set a different padding for navigation block.

```
"core/navigation": {
    "spacing": {
        "padding": {
            "left": "0.5rem",
            "right": "0.5rem"
        }
    }
}
```

Observe that navigation padding still set to `2rem` instead of `0.5rem`.

### Screenshots, screen recording, code snippet

**Styles applied:**

<img width="582" alt="image" src="https://user-images.githubusercontent.com/1935113/188798590-98ee572c-97cd-4fa6-be91-be634beff61e.png">

<img width="537" alt="image" src="https://user-images.githubusercontent.com/1935113/188798706-8dea096f-48a9-48c8-8cab-269abbfcef96.png">

### Environment info

- WP 6.0 (latest trunk)
- Gutenberg 14

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hey @madhusudhand  - just wanted to check in to see if this error still occurs for you when testing?

**Comment by madhusudhand** [comment]
Tested with Gutenberg 17.0.0 and it is no longer an issue. Hence closing.
