### ISSUE TITLE
Columns block: Add both horizontal and vertical block spacing support

### ISSUE THREAD

**Issue by briceduclos** [WordPress/gutenberg#43942]
Currently, we can change the block spacing for the columns block, but we can't differentiate the horizontal and vertical spacing. Other blocks like Gallery and Buttons have this capability. This feature would be useful for creating columns with different vertical and horizontal spacing (which is a common case).

So adding horizontal and vertical block spacing support to the Columns block would be great.

**Comment by andrewserong** [comment]
Updated in #44101, thanks to @ndiego!
