### ISSUE TITLE
Image block: Add margin support

### ISSUE THREAD

**Issue by briceduclos** [WordPress/gutenberg#43940]
Currently, the Image block doesn't support margin, while the Post Featured Image does. For consistency, adding margin support to the Image block would be great.

**Comment by glendaviesnz** [comment]
Thanks for raising this @briceduclos We are currently in the process of adding consistent support across blocks for margin. This is [being tracked here](https://github.com/WordPress/gutenberg/issues/43243), and Image block is listed there as needing this support added, so I am going to close this issue in favour of that tracking issue.
