### ISSUE TITLE
Spotify Block displaying playlist's different on mobile view

### ISSUE THREAD

**Issue by Thelmachido** [WordPress/gutenberg#43961]
### Description

 Spotify playlist embed is displayed differently on mobile view for different themes. 

On certain themes for example Twenty Twenty-Two and [Kadence Virtue Premium theme](https://www.kadencewp.com/product/virtue-premium-theme/), you can view the entire playlist while scrolling on desktop, tablet, and mobile landscape mode. But mobile portrait mode only shows the play button and album art without the playlist beneath it as shown in this screenshot. 

<img width="372" alt="image" src="https://user-images.githubusercontent.com/41231764/188934923-3577f203-b43b-42d4-aa3d-b78959ccd0e2.png">

However, on the Blockbase theme, the playlist is showing the whole playlist as shown below :

https://user-images.githubusercontent.com/41231764/188935584-5bf8980b-fa67-4e3a-af4f-a3e3efa7d762.mov

If you add the embed using the Custom HTML block the playlist looks as expected on every view. Because of what I shared above, I don't think this was theme related, let me know if I should move this. 

### Step-by-step reproduction instructions

1. Go to any site 
2. Add the Twenty twenty-two theme 
3. Use Gutenberg blocks, add the Spotify block to any page. 
4. Within the Spotify block paste a Spotify playlist. 

You will see what I shared above, a playlist that is only showing a play button and album art. This was [reported here](https://wordpress.org/support/topic/spotify-block-responsiveness-issues/?view=all) initially I thought it was theme related but we had different results on different themes. 

### Environment info

- WordPress version 6.0.2
- Gutenberg version 14.0.2
- Twenty Twenty-Two theme and others 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @Thelmachido

I think this is an issue with Spotify embeds and not something we can fix on our end.

Spotify will stop rendering playlist items for window width < 400px.
