### ISSUE TITLE
Gutenberg is Not Compatible with WP Log Viewer

### ISSUE THREAD

**Issue by misfist** [WordPress/gutenberg#4397]
## Issue Overview

Post editor screen is blank when Gutenberg (https://github.com/WordPress/gutenberg) and WP Log Viewer (Version 1.2.1) are both active.

## Steps to Reproduce

* Install and activate WP Log Viewer (https://github.com/allbitsnbytes/wp-log-viewer/)
* Install and activate Gutenberg
* Go to post editor screen (Posts > New Post or Posts > All Posts > {Any Post})

## Expected Behavior

Post editor should appear with new Gutenberg interface.

## Current Behavior

* Post editor screen is blank.

![add new post tomdispatch com wordpress - WP Log Viewer active](https://user-images.githubusercontent.com/709248/34810660-ba5b3f24-f66a-11e7-9934-6d3dca140874.png)

* JS console displays the following error

```
TypeError: Cannot call a class as a functionhttp://tomdispatch.dev/wp-content/plugins/gutenberg/editor/build/index.js line 11
```

## Possible Solution

Deactivating WP Log Viewer resolves issue.

### When WP Log Viewer is Active

![add new post tomdispatch com wordpress - WP Log Viewer active](https://user-images.githubusercontent.com/709248/34810660-ba5b3f24-f66a-11e7-9934-6d3dca140874.png)

### When WP Log Viewer is NOT Active

![new post add new post tomdispatch com wordpress - WP Log Viewer inactive](https://user-images.githubusercontent.com/709248/34810743-381a5bb6-f66b-11e7-8127-d11085a451ad.png)

## Related Issues

https://github.com/allbitsnbytes/wp-log-viewer/issues/1

## Environment

Ubuntu 16.04
Firefox 57.0.4 (64-bit)
WP Log Viewer Version 1.2.1
Gutenberg Version 1.9.1

**Comment by ajitbohra** [comment]
Works as expected on master / v3.2
