### ISSUE TITLE
Categories block doesn't inherit css from style.css on the Editor

### ISSUE THREAD

**Issue by SGr33n** [WordPress/gutenberg#43999]
### Description

Hi!
Defining a custom style for the categories core block doesn't affect that style on the editor.
The style works, on the other hand, on the page list block (pretty similar to the categories one).

### Step-by-step reproduction instructions

Add a categories list block and a page list block.
Add the following code on your styles.css

```
.wp-block-categories-list,
.wp-block-page-list {
	list-style-type: none;
	padding-left: 0;
}
```

both are working on the frontend, while only the page list block is getting the correct style.

This looks a problem on the Editor's class names:
block-editor-block-list__block wp-block wp-block-page-list on the block pages list.
wp-block-categories__list wp-block-categories__list-level-0 on the categories list block.

the second one should probably be:
block-editor-block-list__block wp-block wp-block-categories-list

### Environment info

WordPress: 6.0.2
Gutenmberg: latest trunk
Theme: TwentyTwenty-two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi!
Style.css in themes is not added to the editor by default. The theme needs to use an editor style. I mention this because it is not clear from the issue description, how the style.css is added. Sorry if this is obvious.

**Comment by SGr33n** [comment]
It's on twentytwenty-two, on the theme main stylesheet, it's correctly added to the Gutenberg editor:

Frontend:

![Immagine 2022-09-09 125606](https://user-images.githubusercontent.com/882463/189335522-78fc1993-b1f8-49b5-87c9-ad8b6a5cc656.png)

Gutenberg:

![Immagine 2022-09-09 125701](https://user-images.githubusercontent.com/882463/189335844-cde68f1a-7d22-486d-b44e-621011ff90b7.png)

**Comment by carolinan** [comment]
Are you able to test if your CSS works with this PR? https://github.com/WordPress/gutenberg/pull/43666

**Comment by SGr33n** [comment]
Sorry i forgot to mention that this test was made on the latest Gutenberg trunk, so this PR should already be in.

**Comment by t-hamano** [comment]
@SGr33n 
Thank you for submitting the Issue.
Issue #43666 was not merged at the time you commented, so it was not reflected in the latest `trunk`.
I have just merged it and would like to close this issue.

If you pull the latest `trunk`, you should see that this issue has been resolved.
If the issue has not been resolved, please do not worry about it and reopen.

**Comment by SGr33n** [comment]
Thanks @t-hamano and @carolinan!

**Comment by SGr33n** [comment]
I can confirm, #43666 solved this.
Thanks!
