### ISSUE TITLE
List blocks can't be transformed into Task block anymore (since List V2?)

### ISSUE THREAD

**Issue by AliSoftware** [WordPress/gutenberg#44000]
### Description

Until recently, when pasting a List block in a post or comment, then selecting the List Block, we were able to turn it into a Task block, but it seems it's not possible anymore.

We use that feature to turn list blocks into task blocks — and thus make it a checklist — constantly in our team to handle our Release Scenarios: those scenarios contain a List block to describe the steps to go through to do a new beta, and when we need to do one, we copy those steps from the List block, paste them in a new comment, and transform them into a Task list, then execute those tasks one by one.

So the fact that this doesn't work anymore is very annoying for us 😢  (cc @mokagio who first experienced this issue recently)

### Step-by-step reproduction instructions

1. Create a List Block in a post or post comment
2. Add some list items to it
3. Select the whole List block
    * (we used to be able to do this via Command-A on the list, but with List V2 the only way I found to do that was to use the tree view of the blocks in the comment)
4. Click on the top-left button of the toolbar to change the block type ("Transform To" dropdown)
5. In that "Transform To" dropdown, choose to transform it to a "Task" block type

#### Expected Behavior

Each item in the List block should be retained and turned into the same items but in a Task block.

(This is how it worked until recently, before List V2)

#### Actual Behavior

The whole List Block is replaced with an **empty** Task block, removing all the items that were previously in the List block

### Screenshots, screen recording, code snippet

Existing List Block: even via Command-A or other selection methods I tried, I was not able to select the whole List block easily (as we used to with previous version of the List block). Instead it selected all the list items individually, but not the list block itself.
<img width="685" alt="image" src="https://user-images.githubusercontent.com/216089/189226178-b2d00f75-9fbb-46ad-9784-65e7f55c1da6.png">

_Note: only way I found to select the whole List block itself was to use the list/tree view of the blocks to select it; this aspect is not the end of the world, but not as easy as it used to before List V2, when we didn't need to use the tree view; so figured I'd mention it in passing._

<img width="690" alt="image" src="https://user-images.githubusercontent.com/216089/189226557-56c12b29-1945-4e98-a17a-3c9056edaf68.png">

Then once we finally selected the whole List Block, if we try to choose "Transform To" > "Task":

<img width="327" alt="image" src="https://user-images.githubusercontent.com/216089/189226800-bf3078f4-feef-41be-b8f1-c5fbfb04a49f.png">

Then that's when it's replacing the whole List block with an empty Task list instead of transforming the list items to task items.

### Environment info

 - Tested on Google Chrome 105.0.5195.102

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment]
Hey there! Thanks for opening this issue. A task block does not exist in Core WordPress so this issue is outside the scope of the project to address. 

If you find a specific issue with the v2 of the List block, please do open a new issue though. For now, I'm closing this out.
