### ISSUE TITLE
RangeControl has bad styling inside PanelRow

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#4402]
When the Range Control is inside a PanelRow, its styling is messed up

![rangecontrol](https://user-images.githubusercontent.com/1268089/34821284-de2b0c52-f6cb-11e7-8232-09cc88ecf617.png)

The code I used

```
<PanelBody title = { __( 'Override View basic settings' ) } >
	<PanelRow>
		<RangeControl
			label={ __( 'Limit' ) }
			value={ props.attributes.limit }
			onChange={ props.onChangeLimit }
			min={ -1 }
			max={ 999 }
		/>
	</PanelRow>
</PanelBody>
```

**Comment by karmatosed** [comment]
@kmgalanakis is this for your own custom block? If so you will have to provide your own custom CSS for that.

**Comment by kmgalanakis** [comment]
@karmatosed even though this won't be a problem for me, I strongly believe that this style should be included inside the Gutenberg codebase. 

`PanelRow` and `RangeControl` are both default inspector controls and should play nice even when they are combined, the same way `PanelRow` plays nice with the `TextControl` or the `SelectControl`.

Do you think it could help if I submit a PR for that?

**Comment by karmatosed** [comment]
I don't think if we're not using it that just adding should happen, no. In this case I think only if we use in Gutenberg. Thanks for suggesting though.
