### ISSUE TITLE
Add reading settings to front-page template inspector

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44074]
This has come up tangentially in a couple of larger issues already, but may be worth tackling in isolation.

When editing the front-page template, it would be useful to offer manipulation of the reading settings via the Inspector:

<img src="https://user-images.githubusercontent.com/846565/180195127-fd119dc7-dcca-4ca9-928a-d700682be7ee.png">

This can pave the way for other template-based query manipulation, e.g. changing the number of posts per page in the `archive` template.

**Comment by mtias** [comment]
Should we include access to the "latest posts" setting in the index / archive / home templates?

**Comment by jameskoster** [comment]
Closing as this is a duplicate of https://github.com/WordPress/gutenberg/issues/43418
