### ISSUE TITLE
 Global Styles: add Caption element UI controls

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#44071]
https://github.com/WordPress/gutenberg/pull/41140 Introduced the Caption element to be controlled via theme.json, we should [introduce a UI in Global Styles](https://github.com/WordPress/gutenberg/issues/40205#issuecomment-1242705814) so it can be editable by users too, the same way we did for the [heading](https://github.com/WordPress/gutenberg/pull/42176) and button elements.

**Comment by richtabor** [comment]
Just chiming in that I ran into this limitation while experimenting with theming in the editor.
