### ISSUE TITLE
Allow themes to add custom templates description

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#44097]
Themes can add custom templates, but there doesn't seem to be a way to add descriptions. @jffng kindly looked into this for me, and it seemed like `name`, `title`, and `postTypes` are allowed at the moment. https://github.com/WordPress/gutenberg/blob/40efcbe548e7579a436912bd12740212cf305cdc/schemas/json/theme.json#L1559 

The screenshot was from a site with Twenty Twenty-Two, but many other themes also have no way of clarifying the custom template. The description will help theme builders to communicate with the user what the custom templates are for.

I've briefly looked for a request opened before but couldn't find it. If there is somewhere, kindly point me to the conversation. Thanks in advance!
 
![Screenshot 2022-09-12 at 17 01 06](https://user-images.githubusercontent.com/908665/189713163-757f51a0-f82a-44eb-ba89-325932956ef1.jpg)

**Comment by iamtakashi** [comment]
Thanks, @talldan, for removing the stale tag.

I still think it'd be helpful for both themers and users if we could add descriptions to custom templates.

**Comment by mikemcalister** [comment]
As we see more work happening on the Site Editor view, it would be great to see these descriptions added to help with consistency in the Template view.

Further, the ability to easily create templates within the admin means users may add more templates than they have historically. Having a way to describe these templates for themselves and other users will be a necessity.

**Comment by talldan** [comment]
Also related - [Browse mode: Consider adding in descriptions of template after selection #46640](https://github.com/WordPress/gutenberg/issues/46640).

**Comment by fabiankaegy** [comment]
Actually after investigating this a bit more the `customTemplates` key in `theme.json` isn't actually whats used for the title / description here. Instead it is this filterable list here: https://github.com/WordPress/wordpress-develop/blob/ca0260b5beaab6666e8f9fe0a9bff0ca8f6ac228/src/wp-includes/block-template-utils.php#L109-L184

So you can add your custom templates including description like so:

```php
add_filter( 'default_template_types', 'add_custom_template_types', 10, 1 );

/**
 * Add custom template types.
 *
 * @param array $templates The default template types.
 *
 * @return array The modified template types.
 */
function add_custom_template_types( $templates ) {

	$templates['single-podcast'] = [
		'title'       => __( 'Single Podcast', 'namespace' ),
		'description' => __( 'A single podcast post.', 'namespace' ),
	];

	return $templates;
}

```

**Comment by strarsis** [comment]
@fabiankaegy, @talldan, @mikemcalister, @iamtakashi: Trying to have a follow up on this: Would the `description` field be now supported in `customTemplates` in `theme.json`, or does it have to be set inside a PHP filter instead?

**Comment by lxbdr** [comment]
> Actually after investigating this a bit more the `customTemplates` key in `theme.json` isn't actually whats used for the title / description here. Instead it is this filterable list here: https://github.com/WordPress/wordpress-develop/blob/ca0260b5beaab6666e8f9fe0a9bff0ca8f6ac228/src/wp-includes/block-template-utils.php#L109-L184
> 
> So you can add your custom templates including description like so:
> 
> add_filter( 'default_template_types', 'add_custom_template_types', 10, 1 );
> 
> /**
>  * Add custom template types.
>  *
>  * @param array $templates The default template types.
>  *
>  * @return array The modified template types.
>  */
> function add_custom_template_types( $templates ) {
> 
> 	$templates['single-podcast'] = [
> 		'title'       => __( 'Single Podcast', 'namespace' ),
> 		'description' => __( 'A single podcast post.', 'namespace' ),
> 	];
> 
> 	return $templates;
> }

When adding the description this way the custom template no longer shows in the "Switch template" dialog for a post/page. Anyone experiencing the same?

**Comment by isuke01** [comment]
I'm getting same issues as @lxbdr.

WP: **6.8.1**

**Comment by WORX-Developer** [comment]
Still the same issue as @lxbdr with WP 6.9.1

**Comment by mad0x20wizard** [comment]
Would be really awesome if "description" would be a possible key in the theme.json, so that we don't have to install a custom filter just for setting the description...
