### ISSUE TITLE
Query Loop: Carousel pattern selector is confusing to use

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#44102]
Potentially related - #41379 (I'm not sure if the Query Loop block is in that issue's scope).

## What problem does this address?
The Query Loop carousel pattern selector is a little confusing to use, as it works differently to every other similar interface in the editor.

At first I thought the interface was broken (and I ran it past a couple of other people who thought the same thing):
![Screen Shot 2022-09-13 at 11 29 54 am](https://user-images.githubusercontent.com/677833/189801541-1eb128f4-cde7-4a40-bb40-775bebe588c3.png)

In every other block pattern UI (Template part picker, inserter) the pattern itself can be clicked to insert, but that's not possible here.

The left/right arrow buttons and the Choose button are incredibly small compared to the pattern itself, and I didn't really clock that they were present and played such an important role.

Usually in most interfaces like this, the left right arrow buttons are either side of an image and much bigger. This seems to be a case of using a very unfamiliar and unexpected UI for what usually a common pattern (a gallery lightbox).

It's also worth comparing this to the Grid view, which works completely differently, but I think also has its own problems (In Twenty Twenty Two it's really hard to see the boundaries of patterns, and there are no labels)

## What is your proposed solution?
- Make the patterns clickable.
- Make the arrow buttons much bigger and move them either side of the pattern preview.
- Show how many patterns there are (e.g. '1/4')

Alternatively, add a smaller thumbnail view to the bottom of the modal like this gallery lightbox does:
![Screen Shot 2022-09-13 at 11 46 44 am](https://user-images.githubusercontent.com/677833/189803217-1443781e-39fe-4908-9d5b-2f9693ea73c6.png)

**Comment by annezazu** [comment]
Just found this but I've been leaving loads of feedback on this issue: https://github.com/WordPress/gutenberg/issues/33202

Perhaps this is a duplicate? What do you think, @talldan? I'd love to consolidate around the above if possible.

**Comment by apeatling** [comment]
I posted some thoughts over on https://github.com/WordPress/gutenberg/issues/33202, plus all the feedback there I think we can close this one since the feedback here is referenced there as well. @talldan feel free to reopen if you disagree. :)
