### ISSUE TITLE
Pasting lists with asterisks for bullet points doesn't work

### ISSUE THREAD

**Issue by hamishmb** [WordPress/gutenberg#44117]
### Description

Pasting lists with asterisks for bullet points doesn't work - instead of a nicely formatted list (like you get when you paste a list with dashes for bullet points), I get the message:

"Block has encountered an error and cannot be previewed."

I cannot really test without gutenburg unless I set up a second wordpress install, as this issue is on my production site. I think it is pretty unlikely this is caused by my setup, but I could be wrong.

### Step-by-step reproduction instructions

1. Create a new post or page.
2. Try to paste in a list that uses asterisks for bullet points.
3. Observe the issue

### Screenshots, screen recording, code snippet

The list I created to paste in:

![wpbugreport-1](https://user-images.githubusercontent.com/16725441/189879026-34edf82d-32ed-476a-9ad2-7c07715a3481.png)

The result:
![wpbugreport-2](https://user-images.githubusercontent.com/16725441/189879038-64bfe958-830f-405c-a8f5-e4949e2ee00d.png)

### Environment info

- Wordpress 6.0.2 (fully up to date at time of writing)
- Gutenburg version ??? (not specified at https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/)
- Active theme is Mantra 3.3.1 (https://www.cryoutcreations.eu/wordpress-themes/mantra)

- Browser: Firefox 104.0.2 On Linux Mint 20.3 Cinnamon (X11)
- Device: Desktop PC, kernel Linux 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by artemiomorales** [comment]
Hello, I'm unable to replicate this issue using Wordpress 6.0.2. This test was done on a clean local installation. I also tested with the Mantra theme and it still worked as expected.

https://user-images.githubusercontent.com/5360536/190517582-7e2c4998-fba5-4cf1-b8bf-a889788818fb.mov

Do you have any plugins that may be causing a conflict, or perhaps it's the text editor you're using that may be causing an issue?

**Comment by hamishmb** [comment]
Hmm, okay, I'll give it another shot soon.

I'm using Xed from Linux Mint as my text editor. I'll try a different text editor and then I'll try with a local install and add my plugins one by one.

If this does turn out to be plugin-related, is it going to be possible to fix it?

**Comment by hamishmb** [comment]
I will try again soon, in a test environment.

**Comment by hamishmb** [comment]
I can't reproduce this any more, so whatever the problem was, it has gone away.
