### ISSUE TITLE
Post Editor doesn't reflect justification on the Post Content block

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44110]
With https://github.com/WordPress/gutenberg/pull/44065 merged it's possible for Post Content layout to be inherently more expressive. 

Here's my single template:

<img width="1529" alt="Screenshot 2022-09-13 at 09 38 18" src="https://user-images.githubusercontent.com/846565/189854026-3ad14b15-0a96-48b5-9eb5-fc9039a6eaa9.png">

Notice how all blocks within the post content are left-justified. This is accurately reflected in the Site Editor:

<img width="1259" alt="Screenshot 2022-09-13 at 09 39 08" src="https://user-images.githubusercontent.com/846565/189854249-dd6e72d9-8705-47f7-acfc-38bb78db524a.png">

However, in the Post Editor everything remains centrally aligned:

<img width="1286" alt="Screenshot 2022-09-13 at 09 39 41" src="https://user-images.githubusercontent.com/846565/189854402-1c6858c3-396e-4428-a2cc-b3e3bd2dd9c2.png">

It would be nice to fix this so that the Post Editor gives a more accurate portrayal of the frontend. 

cc @andrewserong

**Comment by andrewserong** [comment]
Thanks for writing up this issue and including the screenshots @jameskoster! The fix for this will likely also be a fix for https://github.com/WordPress/gutenberg/issues/42911, so we may want to consolidate the issues.

**Comment by andrewserong** [comment]
Just closing this one out now, too, since it's resolved as of #44258. Thanks @tellthemachines!
