### ISSUE TITLE
Add E2E tests for List V2 block

### ISSUE THREAD

**Issue by geriux** [WordPress/gutenberg#44113]
**Related issues**: https://github.com/WordPress/gutenberg/issues/43873

Now that we have the new List V2 block enabled by default we need to update the E2E tests since we had to [disable the old ones](https://github.com/WordPress/gutenberg/pull/43648) since were breaking CI.

We also need to add a test to take into account pasting an empty list block in the editor, to cover a possible edge case that could break the editor.

**Comment by dcalhoun** [comment]
@geriux closing this as it appears irrelevant now with the merge of https://github.com/WordPress/gutenberg/pull/46583. Please reopen if I am mistaken. 🙇🏻 

> We also need to add a test to take into account pasting an empty list block in the editor, to cover a possible edge case that could break the editor.

The above quote caused me hesitation. Is there a specific test case we need to cover? If so, let's capture it as a [test case](https://github.com/wordpress-mobile/test-cases) and add it to our test automation spreadsheet. Can it be automated as an integration test instead?
