### ISSUE TITLE
Unable to remove margin in Pullquote

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44129]
The Pullquote block outputs a `blockquote` inside a `figure`. The issue is that the `blockquote` inherits a default margin, and since the editor does not allow you to target it specifically, it's not possible to remove that margin. Here's the result:

<img width="1515" alt="Screenshot 2022-09-13 at 16 32 52" src="https://user-images.githubusercontent.com/846565/189944368-3352a307-c9d2-4ca8-8877-c8aba4f7782e.png">

Ideally it should be possible to make the text of the pullquote align with the paragraph before and after it.

**Comment by t-hamano** [comment]
I've submitted #45731 to add spacing supports to the Pullquote block.

Once margins are controllable, the default margin for blockquote will no longer be necessary, so I've added a style to reset the default margin at the same time.
