### ISSUE TITLE
Blocks: "Format" options not shown when editing as HTML

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#4413]
This is more a question as opposed to a bug report: Is it expected that the "Format" (Advanced Settings) controls for a block should be shown when editing as HTML?

__Steps to Reproduce:__

1. Navigate to Posts > Add New
2. Insert a Paragraph block
3. In the block ellipsis menu, click "Show Advanced Settings"
4. Note that Format settings are shown in the sidebar
5. In the block ellipsis menu, click "Edit as HTML"
6. Note that Format settings have disappeared from the sidebar

**Comment by mtias** [comment]
I think we should show all inspector settings when editing as HTML.

**Comment by tofumatt** [comment]
That makes sense... I spoke to @mcsf about this earlier today and we weren't sure which settings should be displayed, but it seems like we should indeed show everything.

For what it's worth, it was a bit difficult to track down exactly what controlled the display of block options based on editing mode... but now I have an idea of where it is so I'm working away at this one. 👍
