### ISSUE TITLE
Global Styles: Can't open Colour Picker by clicking on colour circle

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#44138]
### Description

In Global Styles one can't open the Colour Picker by clicking on the colour circle. You need to first click on the ellipsis and then press Edit which is confusing since the colour circles are interactive but do nothing. It's okay for editing the name to be buried but changing the colour should be quicker.

### Step-by-step reproduction instructions

1. Go to Site Editor → Global Styles
2. Click _Colors_
3. Open a pallette
4. Click on one of the colour circles

Expected result: The colour picker should open.
Actual result: Nothing happens.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/612155/190030765-29cedc2d-25e8-4e32-b0ec-e9f7dd2349fa.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by noisysocks** [comment]
@ramonjd said this might be due to dynamic ref resolution in theme.json which he was looking at in https://github.com/WordPress/gutenberg/pull/43249.

**Comment by ramonjd** [comment]
> @ramonjd said this might be due to dynamic ref resolution in theme.json which he was looking at in https://github.com/WordPress/gutenberg/pull/43249.

Actually, looking at this again, I was thinking of an entirely different case. So I don't think this is a bug.

This would be a good feature enhancement however. 

While backtracing I noticed that the onChange event for palette options is empty: https://github.com/WordPress/gutenberg/blob/1a108a456c9b42f8c2d9eafb8dc0c77001bcdf70/packages/components/src/palette-edit/index.js#L466

Maybe there's a good place from which to trigger the ColorPicker component?

**Comment by ramonjd** [comment]
I know @pbking has [a PR up](https://github.com/WordPress/gutenberg/pull/45657) to enable edit mode all the time.

Just in case, I have an alternative that opens edit mode and selects the color over at https://github.com/WordPress/gutenberg/pull/45681

![2022-11-10 10 11 43](https://user-images.githubusercontent.com/6458278/200963094-501708f7-d437-4e15-8476-525c4635a7e7.gif)

Happy to close mine. Sorry I didn't see #45657 before starting.
