### ISSUE TITLE
Gutenberg: Double Click after using Block Inserter 

### ISSUE THREAD

**Issue by Joshgrygiel** [WordPress/gutenberg#44132]
### Description

You have to click twice to access the block's settings after adding to the editor through the block inserter, the layout also moves on your first click.

### Step-by-step reproduction instructions

To replicate:

1. Click on the + icon from the Block Inserter on the top left
2. Click on a block to add it - you will notice that the Block Inserter won't close
3. Try using an option on the block itself, such as clicking on an alignment option on its toolbar
4. You will notice that the option won't open, instead, the Block Inserter panel closes
5. You have to click on the block's option again to get what you need

### Screenshots, screen recording, code snippet

Here's an example - after adding the block, you can see that the first click on the option closes the Block Inserter, and the second click that actually opens the block's options:

![block-inserter-double-clicking](https://user-images.githubusercontent.com/16104522/189746747-ce4e2348-8116-4432-a471-0f68987b37fe.gif)

I triaged the original report and was able to confirm this functionality on Self-hosted:

https://user-images.githubusercontent.com/88345647/189960502-8d359481-2455-43e4-8681-d40a57614a41.mov

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I think this is fairly common across the web and other applications, and not necessarily something that needs fixing. The first click dismisses the sidebar and after that the user is free to click elsewhere.

The same thing exists in github:

https://user-images.githubusercontent.com/677833/190040393-0e291f09-876c-422f-97af-0768e421d058.mp4

And I see the same in slack and Mac OS too.

**Comment by jordesign** [comment]
I'm going to close this issue to consolidate it with this newer issue with more activity.
https://github.com/WordPress/gutenberg/issues/51678
