### ISSUE TITLE
Selecting a pattern in the Template Part replacement flow is editing rather than replacing

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44147]
In the template part replacement flow, if you select an _existing template part_ then the original one is replaced as expected. However, if you _select a pattern_ then the original template part is _edited_ which feels unexpected. Here's a video demo:

https://user-images.githubusercontent.com/846565/190099050-314cad43-b5bf-4510-91fd-44ddc2c3c822.mp4

@talldan I'm sure we merged a PR that enabled the creation of template parts directly from patterns. Did I mis-remember? Or is it possible that this flow was accidentally overlooked?

**Comment by talldan** [comment]
> In the template part replacement flow, if you select an existing template part then the original one is replaced as expected. However, if you select a pattern then the original template part is edited which feels unexpected. 

I think the template part replace flow has been like this from very early on, so it's probably something that was overlooked.

Choosing another template part swaps the template part being used. Choosing a pattern replaces the template part's inner blocks. I see how it can be misleading given both are presented as part of the same flow, and the latter could be quite disruptive for template parts being used in other templates. Pattern selection could alternatively create a new template part and swap the template part being used. I think that would be a pretty straightforward change.

> @talldan I'm sure we merged a PR that enabled the creation of template parts directly from patterns. Did I mis-remember? Or is it possible that this flow was accidentally overlooked?

When adding a template part block from the inserter? It hasn't been merged. I haven't been able to give it much attention lately, though I do have some better ideas in terms of the API.

**Comment by talldan** [comment]
It looks like you mentioned a similar thing here about creating a new template part when replacing with a pattern -https://github.com/WordPress/gutenberg/issues/41397#issuecomment-1185543233

**Comment by jameskoster** [comment]
Oh yes, I'll close this issue in favor of #41397. It would be really good to solve this particular portion as it feels very confusing to use at the moment 🙈

**Comment by talldan** [comment]
PR to fix this at #44221
