### ISSUE TITLE
Post Template block errors after creating a template for a specific category

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44156]
To reproduce:

1. Have a functioning Archive template
2. Have a category that contains some posts
3. From the Templates list in the Site Editor click Add New -> Category
4. Choose a specific category
5. Observe the following result:

<img width="1249" alt="Screenshot 2022-09-14 at 14 53 51" src="https://user-images.githubusercontent.com/846565/190173995-dd22ca67-bb53-4095-b1f4-871a035676de.png">

**Comment by annezazu** [comment]
Just ran into this and can confirm the same problem.
