### ISSUE TITLE
Improve reading experience of docs by replacing text of "Top ↑" links with just "↑"

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#44162]
## What problem does this address?

Better experience reading the docs

## What is your proposed solution?

Replace the text of "Top ↑" links with just "↑". These links could optionally display the full "Top ↑" text only when hover on these links

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Docs Scrub. Given the upcoming redesign of the Block Editor Handbook, we have decided to close this issue. Any design issues should also be added to the [Developer.WordPress.org Theme](https://github.com/WordPress/wporg-developer) repo.
