### ISSUE TITLE
Language around transformations inconsistent

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#4416]
## Issue Overview

While writing a bit in Gutenberg I saw that the language for transforming a block into something else is a bit inconsistent. We use "transform into", "turn into" and "convert to" in the UI around the block.

<img width="259" alt="screen shot 2018-01-11 at 22 15 35" src="https://user-images.githubusercontent.com/4710635/34847902-2c38e3b4-f71d-11e7-9a1e-46a591a661d2.png">

<img width="263" alt="screen shot 2018-01-11 at 22 15 58" src="https://user-images.githubusercontent.com/4710635/34847906-2f7bb682-f71d-11e7-94b3-b012cc6eeae6.png">

What would be the best word to use for all of these?

There's also a difference between the two list where one repeats "turn into" and the other only has "transform into" on the top.

**Comment by rileybrook** [comment]
In my opinion, "Turn into" is easier to understand than "Transform into."  - but I am only one person. 

>There's also a difference between the two list where one repeats "turn into" and the other only has "transform into" on the top.

I think the copy (ex. "Turn into") at the top of the list only makes more sense than repeating it multiple times @iseulde 

Would be interested to see opinions from others.

**Comment by rileybrook** [comment]
Discussed this in WP design channel weekly meeting. Consensus from roundtable was "Transform into" was more descriptive and easier to translate to other languages as opposed to "Turn into".

This issue, along with others, will be covered during a general content review that will be conducted at a later date.

**Comment by mtias** [comment]
We have consolidated transformations in the block switcher menu and it reads "Transform To".
