### ISSUE TITLE
Add in ability to chose image size in gallery

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4417]
In the classic editor you can select the image sizes:

![2018-01-11 at 22 04](https://user-images.githubusercontent.com/253067/34849740-62092d5c-f71b-11e7-8d55-51a90aed5b52.png)

Right now in Gutenberg you can't. We probably want to just have a single setting as being per image is a little odd when you can't have different sizes.

**Comment by jeherve** [comment]
This seems to be a duplicate of #1450

**Comment by karmatosed** [comment]
Closing as duplicate, thanks.
