### ISSUE TITLE
Justification icons on containers appear disabled

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44183]
<img width="256" alt="Screenshot 2022-09-15 at 10 56 52" src="https://user-images.githubusercontent.com/846565/190375089-dc233e68-7710-4042-8cf2-f4c3898c8159.png">

The lighter-grey icons we find here do not match all the other icon buttons in our UI. This gives an impression that they are disabled. Ideally they should use the darkest grey color (`gray-900`).

**Comment by t-hamano** [comment]
I believe this issue has been resolved by #44575 and would like to close it.
