### ISSUE TITLE
Duotone: image border also gets the set duotone

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#44184]
### Description

When an image is given a border and duotone, the border color gets effected.

#### Expected:

Duotone should only apply to image, but not to border.

### Step-by-step reproduction instructions

1. define a duotone.
2. Set it to blocks such as `core/image`, `core/post-featured-image`.
3. Also set a border (2px blue, in the below example) to the same block.
4. Observe that the duotone is also applied to border.

### Screenshots, screen recording, code snippet

| Current | Expected |
| --- | --- |
| <img width="443" alt="image" src="https://user-images.githubusercontent.com/1935113/190393149-90b4837f-ed61-48d1-9118-760a9d5ea223.png"> | <img width="443" alt="image" src="https://user-images.githubusercontent.com/1935113/190393096-b31b27ec-c025-45a7-afca-d4c7ae014366.png"> |

### Environment info

- Wordpress 6.0.2
- Gutenberg 14

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aaronrobertshaw** [comment]
Thanks for raising this issue @madhusudhand 👍 

It appears to be a duplicate though as it has already been flagged in https://github.com/WordPress/gutenberg/issues/43295. 

Unfortunately, it is a tradeoff we've had to make, for now, given the border needs to be applied to the `img` element. A more detailed explanation can be found in this [comment](https://github.com/WordPress/gutenberg/issues/43295#issuecomment-1220579766).

I'll close this along the same lines as https://github.com/WordPress/gutenberg/issues/43295.
