### ISSUE TITLE
Global Styles: Focus moved to back button when inputting number value

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#44191]
When inputting a number value in for example Blocks > Image > Layout > Radius, after inputting the first number, focus is immediately transferred to the back button, as shown in this GIF:

![focus loss](https://user-images.githubusercontent.com/1204802/190409592-889502eb-5d23-4410-9e57-b1912c66f810.gif)

Focus should remain in the selected input field.

**Comment by BE-Webdesign** [comment]
#44239  Should fix this.
