### ISSUE TITLE
Image border radius missing after Scale:Cover

### ISSUE THREAD

**Issue by henriqueiamarino** [WordPress/gutenberg#44194]
### Description

Every time I set my images to have a fixed height and **Scale/Cover** is activated the round corners determined by the radius value are gone. I believe this is related to **Scale/Cover** because if I toggle **Cover** off the round corners are back again, but the images are not adjusted the way I expect.

### Step-by-step reproduction instructions

1. On a page/post just create a 'Query Loop' with 'Post Featured Images'
2. In **Dimensions** panel set any specific 'Height' value
3. In **Scale** pick Cover
4. In **Border** set border radius different from 0
5. Publish the page and check round corners on your final results

### Screenshots, screen recording, code snippet

#1 shows the Site Editor and #2 the frontend published

![image-covermode-noradius](https://user-images.githubusercontent.com/103748085/190415501-d0640577-11c4-41af-accb-d0f7709a21f5.png)

### Environment info

- Wordpress 6.0.2 with Gutenberg Nightly (Wordpress Latest)
- Staging site loaded by Pressable
- Desktop / macOS Monterey - Version 12.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Cc @ntsekouras @aaronrobertshaw do you know what might be up here? Thank you for looking!

**Comment by aaronrobertshaw** [comment]
It looks like when height is set on a post featured image the inner `img` element's style attribute gets overwritten so it loses the block support inline styles. In this case, that's the border-radius along with border width, style, and custom colors.

I'll put up a draft PR fix for this shortly.

**Comment by aaronrobertshaw** [comment]
Potential fix is up in: https://github.com/WordPress/gutenberg/pull/44213
