### ISSUE TITLE
Theme Switching: automatically set blog page in reading settings after switching to a block theme

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#44211]
## What problem does this address?

Currently, when switching from a classic theme (twenty twenty one) to a block theme (twenty twenty two), the blog page that was originally automatically set up in twenty twenty one becomes empty after switching. To fix, one has to go to Settings > Reading and set the page to the blog page once more (or add a query loop block). 

## What is your proposed solution?

Either place a query loop block automatically in the page that's now empty or set it automatically in the settings for the site post switch.

**Comment by carolinan** [comment]
I am not able to reproduce this, can you add any more details about the settings?
Maybe I misunderstood:

In any classic theme ( I used Twenty Seventeen)
Create two pages.
Go to Settings > reading.
Select "Your homepage displays A static page"
Assign one of the pages to the Homepage, and one to the posts page.

Switch to another classic theme, for comparison, and confirm that the homepage and the posts page are still correct.

Switch to a theme with support for the site editor:
I switched to "Jace" from the theme directory.
The homepage is correct. The blog page is correct and displays the posts.
When I open the page selected as the blog page in the editor, There is a notification that says: "You are currently editing the page that shows your latest posts."

Next I switched to Twenty Twenty-Two:
The homepage is correct. The blog page is correct and displays the posts.
When I open the page selected as the blog page in the editor, There is a notification that says: "You are currently editing the page that shows your latest posts."

**Comment by annezazu** [comment]
How strange. I just tried to replicate and couldn't. I'll close this out and see if anyone else runs into it with the FSE Outreach program :)
