### ISSUE TITLE
Represent default font size in slider

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#44229]
Now that we have more concrete mechanisms for knowing what is the default font size coming for text from the global styles tree, can we represent it on the segmented control if it matches one of the preset sizes?

<img width="470" alt="image" src="https://user-images.githubusercontent.com/548849/190631946-729972bf-d948-48e8-8e78-54e2e1b50954.png">

I'd imagine we would use a lighter gray for these cases.

**Comment by jasmussen** [comment]
Here are a few options including a lighter gray:

<img width="1172" alt="Known but not explicitly set" src="https://user-images.githubusercontent.com/1204802/191193306-e529a9fa-31e4-42b5-8fbc-a1396aafcb29.png">

Another option is to show a little asterisk or other indicator:

<img width="1172" alt="Known but not explicitly set" src="https://user-images.githubusercontent.com/1204802/191193626-8332c7df-dc56-4a62-81b4-9d4f8d67d984.png">

Or a combination?

<img width="444" alt="Known option 3" src="https://user-images.githubusercontent.com/1204802/191193732-35821b27-feef-4e83-8d23-583c7719bfd4.png">

None of these seem a clear win, though I'd tend to agree the light gray background is probably best out of these.

**Comment by jameskoster** [comment]
Isn't the label alone adequate? It seems more important for the default size _to be selected_ when the control is present?

![label](https://user-images.githubusercontent.com/846565/193024856-a578891d-c8e6-4be7-a603-bd491184da0a.gif)

**Comment by jasmussen** [comment]
Oh interesting, I read the brief as _when no font size is set, suggest which point on the slider it would match_. 🤔

**Comment by jameskoster** [comment]
If no font size is set (it is inherited from css), then we can't determine which value it would match? 🤔  

I saw this as more about connecting the setting in global styles to the control we find when editing locally. Apologies if that's separate.

**Comment by jasmussen** [comment]
The font size can be set in Global Styles, in which case we would know whether it matched a given notch in the slider.

**Comment by jameskoster** [comment]
We should. But it hasn't been implemented here. I think that's the issue? 

As an example, here's my font size setting from the Typography section of global styles:

<img width="280" alt="Screenshot 2022-09-29 at 14 45 58" src="https://user-images.githubusercontent.com/846565/193049022-e20780c9-54ac-432c-9b84-e476d7f427a4.png">

But when I go to edit the Paragraph block in global styles, or just select a paragraph while editing a post, here's what I see:

<img width="285" alt="Screenshot 2022-09-29 at 14 45 44" src="https://user-images.githubusercontent.com/846565/193049142-b8208d3d-e466-4a7c-82d1-3b6a85fbaa1e.png">

The label tells me the default size is set, but the corresponding segment (M) isn't highlighted.

**Comment by jasmussen** [comment]
Right, that's the baseline, and works okay, I think the question is whether we need more than that.

**Comment by jameskoster** [comment]
Indeed, and my suggestion was that if the correct value is highlighted in the control, isn't the label denoting the default adequate? So if I select a paragraph in a post, I see this in the Typography panel:

<img width="278" alt="Screenshot 2022-09-29 at 15 03 55" src="https://user-images.githubusercontent.com/846565/193053192-c601f85a-0118-40e7-adc2-e9941e90b6f2.png">

**Comment by mtias** [comment]
Selecting M explicitly for a paragraph is not the same as M being the inherited default when nothing is locally set but M is the most immediate value passed in the tree.

**Comment by jameskoster** [comment]
I believe https://github.com/WordPress/gutenberg/issues/49278 captures this in a more holistic way. All controls need a solution to this problem.
