### ISSUE TITLE
Mover control: Block toolbar no longer sticks to block that's being moved until you scroll

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#44220]
Steps to reproduce:

* Insert several paragraphs
* Select a paragraph and click the mover control to move it

Observe that the block toolbar scrolls out of view and stays in place, until you scroll the page.

![mover](https://user-images.githubusercontent.com/1204802/190592230-e0790bc0-bd59-4e0c-9aac-7ee4d049face.gif)

**Comment by talldan** [comment]
I can reproduce it. It seems to work ok if there's not enough content to result in a scrollbar, though it does look a little glitchy at times:

https://user-images.githubusercontent.com/677833/190982003-33ce7643-5a28-495f-b030-72e67756725a.mp4

But when I try the Gutenberg demo post, it's easily reproducible (it looks the same as the screen cap in the description, so I won't add another).

I think this should be fixed for 6.1, so I'm adding it to the board.
