### ISSUE TITLE
Partially locked template wrongly shows notice about template mismatch

### ISSUE THREAD

**Issue by kraftner** [WordPress/gutenberg#44231]
### Description

If a template of a post is only partially locked only the locked sections should be compared with the template for mismatches.

An example:

We have a custom post type with a template and a locked root via `'template_lock' => 'all'`. But a group block inside that post is unlocked by e.g. setting `'templateLock' => false`.

As soon as another block is added inside that group the block editor thinks the content doesn't match the locked template and shows this notice:

![grafik](https://user-images.githubusercontent.com/2428517/190660348-34954e85-db1b-479d-9f43-f23e774b41a7.png)

But if a template intentionally makes some inner block areas editable changes to that area should be fine.

---

The problems seems to be that [on the top level unlocked templates are considered](https://github.com/WordPress/gutenberg/blob/c1cf175c962ac2239020b80fb6a02341f7205f0b/packages/block-editor/src/store/actions.js#L72-L100).

https://github.com/WordPress/gutenberg/blob/c1cf175c962ac2239020b80fb6a02341f7205f0b/packages/block-editor/src/store/actions.js#L86-L87

But this same behavior [is not implemented in nested blocks](https://github.com/WordPress/gutenberg/blob/c1cf175c962ac2239020b80fb6a02341f7205f0b/packages/blocks/src/api/templates.js#L13-L32).

I'd assume that at this point

https://github.com/WordPress/gutenberg/blob/c1cf175c962ac2239020b80fb6a02341f7205f0b/packages/blocks/src/api/templates.js#L26-L29

additional checks for unlocked blocks (e.g. for `block.attributes.templateLock === false`) should be added, ignoring everything inside unlocked blocks.

### Step-by-step reproduction instructions

1. Register a custom post type with 
   - a template
   - `template_lock` set to `all`
   - unlock a block with inner blocks (e.g. `core/group`) inside the template by setting `'templateLock' => false` on it
2. Create a new post of that custom post type
3. Add new blocks inside the unlocked block
4. Save
5. Reload
6. See the notice which doesn't make sense

### Environment info

- WordPress 6.0.2 (without Gutenberg)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
Hi @kraftner thank you for giving a detailed report on this one, can you please confirm that the issue is persistent on the recent version of WordPress and Gutenberg?

**Comment by kraftner** [comment]
@Thelmachido Yes.

I just tried it with WordPress 6.0.2 and Gutenberg 14.1.1 on a fresh install. Same issue. 

(Wasn't expecting anything else since the current code referenced above still has the issue.)

**Comment by kraftner** [comment]
I just wanted to bump this and confirm that the issue still exists at least in WP 6.3.3. Looking at the code that hasn't changed since I reported this issue I am assuming it is also still present in the 6.4 branch and trunk.

**Comment by kraftner** [comment]
Again, confirming this issue is still there in WP 6.6.1

**Comment by kraftner** [comment]
I just realized this is a duplicate of #11681 hence closing this.
