### ISSUE TITLE
Navigation color settings not working for submenus using classic menus

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#44235]
### Description

Navigation color settings not working for submenus using classic menus

### Step-by-step reproduction instructions

- Import the content from [theamdemo](https://theamdemo.wordpress.com/)
- Activate TT2 or any other block theme
- Select a background and text color for the navigation overlay and submenu items
- Check that the overlay is working as expected but the submenus don't have the colors selected applied.

In the video recording you will be able to see this behavior:

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1310626/190712386-92b9262e-7354-47bf-aa2c-f67333d6ad31.mp4

### Environment info

- WordPress 6.0.2
-  Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting this. Discovered a fix in #44283.
