### ISSUE TITLE
Scrolling down in the menu that has three vertical dots

### ISSUE THREAD

**Issue by zero2webmaster** [WordPress/gutenberg#44236]
### Description

Scrolling down often does not work.

### Step-by-step reproduction instructions

At the top right of a post, click the three dots to get a drop down menu. Try to scroll down to see options that begin too far down to be in view.

### Screenshots, screen recording, code snippet

https://www.loom.com/share/7229e8165cfe4953873303d0dc3743a1

### Environment info

MacOS, Any browser

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Uploading the screencast directly to GitHub:

https://user-images.githubusercontent.com/7662449/191826307-837962de-aba1-4ecf-92ef-e6909be83d95.mp4

**Comment by kathrynwp** [comment]
Thanks for the report and screencast!

So far I haven't been able to replicate this with:

WordPress 6.0.2
Gutenberg 14.1.1 active or inactive (no other plugins active)
Twenty Twenty-Two 1.2

Your screencast shows quite a few plugins active. @zero2webmaster is this issue also happening with **all plugins deactivated**?  I know you answered yes above, but just wanted to double-check. Thanks!
