### ISSUE TITLE
Add Search icon Navigation area

### ISSUE THREAD

**Issue by lwangdu** [WordPress/gutenberg#44246]
## Right now there is no way add search icon easily on the navigation area
I am trying to add search icon navigation area. Right now you can't add search icon easily
![Screen Shot 2022-09-18 at 4 42 59 PM](https://user-images.githubusercontent.com/24829573/190933622-79dd5c1b-92ac-453a-8ef5-80350e3d71aa.png)
.

## What is your proposed solution?
If you click on the show icon button, it would be nice to have search icon. So you can add search icon easily.

**Comment by talldan** [comment]
@lwangdu It looks like you have a search block, but it's in a separate navigation menu that's configured to show the overlay.

I think the option to show an icon only search would be added to the search block. There's already a github issue for it here - https://github.com/WordPress/gutenberg/issues/31128.

So I'll close your issue as a duplicate.
