### ISSUE TITLE
Featured Image Option Not Visible on Specific Taxonomy

### ISSUE THREAD

**Issue by HasaanCh** [WordPress/gutenberg#44253]
### Description

Hi there,
I came across a very weird bug. 
If you have a custom taxonomy registered with the name "themes" the Featured Image option will not be visible while editing posts.

### Step-by-step reproduction instructions

To recreate this there are two ways:
A-> 
1) Install CPT plugin.
2) Create a custom taxonomy of the name "themes" and register it to any of the post types (either core or custom)
3) You can see the featured image option is not visible.

B-> 
1) Add the following code to your functions.php file

```
function wpdocs_register_private_taxonomy() {
 	$args = array(
		'label'        => __( 'Theme', 'Themes' ),
		'public'       => true,
		'hierarchical' => false,
        'show_in_rest'      => true,
        'has_archive'       => true,
        'show_admin_column' => true,
		'rewrite' => [
            'slug'  => 'themes',
        ],
	);
	
	register_taxonomy( 'themes', 'post', $args );
}
add_action( 'init', 'wpdocs_register_private_taxonomy', 0 );
```

### Environment info

- I have tried on multiple themes including the latest version of Twenty Nineteen (Version: 2.3 )
- WordPress 6.0.2 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I think 'themes' should be considered a reserved word. Registering it seems to override the REST endpoint that uses the same word - https://developer.wordpress.org/rest-api/reference/themes/.

This endpoint usually returns a list of features supported by the theme:
![Screen Shot 2022-09-19 at 3 42 44 pm](https://user-images.githubusercontent.com/677833/190971166-e3632b19-90aa-4e5b-9260-a16fe20c293b.png)

`post-thumbnails` is the one that determines whether feature image works, and that's one of the things the block editor uses to determine if the feature should be shown. When the endpoint is overridden it's considered not supported.

Hopefully that explains everything. I'll close the issue. If you want to follow up, this should be considered a WordPress core issue, as the block editor is just a consumer of the REST API - https://core.trac.wordpress.org/. There isn't anything that can be done in the Gutenberg codebase to change how that works.

**Comment by HasaanCh** [comment]
Hi Daniel,
The featured image in Classic editor is working perfectly fine.
And even after changing Featured image in Classic editor and later on
editing the page with block editor the Featured image works fine. The only
problem is with the featured image option which does not appear.
Can you please explain this when you have time ?

**Comment by talldan** [comment]
@HasaanCh The classic editor didn't use the WordPress REST API, which is why it works.

The block editor uses the REST API and depends on the existence of the `themes` endpoint for the featured image. When you register a taxonomy with the id 'themes' it overrides the REST API's `themes` endpoint, and the block editor no longer works correctly.
