### ISSUE TITLE
Comments block: The setting for "Enable threaded (nested) comments" is ignored

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#44257]
### Description

If you uncheck the "Enable threaded (nested) comments" in Settings → Discussion, block themes still display threaded/nested comments. This is different from classic themes, in which threaded comments are displayed without nested lists when the setting is unchecked.

### Step-by-step reproduction instructions

1. Create a post with threaded comments.
2. Disable the "Enable threaded (nested) comments" setting in Settings → Discussion.
3. Activate a block theme.
4. Visit the post. The list is still output with threaded comments.
5. Switch to classic theme.
6. Visit the post again, and the list is now flat, without nested list elements.

### Screenshots, screen recording, code snippet

Running Twenty Twenty-Three:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/8181091/190968293-b26218c7-872c-4660-ae75-01b139eb2034.png">

Running Twenty Nineteen:
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/8181091/190968408-3cd67583-9def-41e5-874b-8ea1e76540f5.png">

### Environment info

WP 6.0.2
Gutenberg 14.1.0
Twenty Twenty-Three and Twenty Nineteen

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by artemiomorales** [comment]
I was able to replicate this with WP 6.0.2 and Gutenberg 14.1.0 using the Twenty Twenty-Three theme.

However, I was unable to replicate it in Twenty Twenty-Two, where the comments appear as expected:

<img width="735" alt="Screen Shot 2022-09-19 at 5 27 03 PM" src="https://user-images.githubusercontent.com/5360536/191122745-4fa7ab64-2b9c-49b3-81e9-e9115a35e473.png">

Perhaps this issue should be opened in the [Twenty Twenty-Three repo](https://github.com/WordPress/twentytwentythree/issues)?

**Comment by andersnoren** [comment]
Twenty Twenty-Three uses the new `<!-- wp:comments -->` block, while Twenty Twenty-Two uses the deprecated `<!-- wp:post-comments /-->` block. 

It's possible that this was working in the old version of the comments block, but is not working in the new one.

Edit: I tried inserting both the deprecated `<!-- wp:post-comments /-->` and the new Comments block in one of my own themes, and the first adheres to the "Enable threaded (nested) comments" while the latter doesn't. Old to the left, new to the right.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/8181091/191190203-691ed3a9-9eb9-4828-9c80-d88f5639b58a.png">

**Comment by annezazu** [comment]
Thanks so much for reporting and replicating. @poliuk as a heads up.

**Comment by carolinan** [comment]
When I disable the nested comments option, I also see a repetition, the comments are both on the first level, and nested.
Front:
![image](https://user-images.githubusercontent.com/7422055/191430961-dabda53d-2f8f-4fd1-8ba4-88c63fc65625.png)

**Comment by carolinan** [comment]
In the editor, when I disable the nested comments, I only see 1 comment, the replies that were created as replies to the first comment, does not show as top level comments.
Even though only one comment shows, the comment reply title says there are 3 comments.

**Comment by SantosGuillamot** [comment]
Thanks a lot for filing the issue and testing it 🙂 

I have just created [this Pull Request](https://github.com/WordPress/gutenberg/pull/44351) with a potential solution to fix it. I am not 100% familiar with the code so I am not sure it is the best approach. I've asked @c4rl0sbr4v0 and @DAreRodz to take a look at it because they were more involved in the Comments blocks code.
