### ISSUE TITLE
Performance drop 16.21% after upgrade to version 6.0.x from 5.9.3

### ISSUE THREAD

**Issue by dylan2intel** [WordPress/gutenberg#44255]
### Description

Performance drop 16.21% after upgrade to version 6.0.x from 5.9.3

Using siege benchmark client to stress wordpress, the primary kpi dropped after upgrading version to latest 6.0.0

previous v5.9.3
![image](https://user-images.githubusercontent.com/90298893/190954479-4f32e7f3-6c50-48ee-8cdb-dc1a6b1e414d.png)

currently v6.0.0
![image](https://user-images.githubusercontent.com/90298893/190954520-3f585e69-2292-49f8-a5aa-bc0864695598.png)

only version change, no other code change or configuration change 

Using perf tool to capture the call stack and address below info:

sudo perf diff perf.data.5mt_5.9.3 perf.data.5mt_6.0.0 |grep php-fpm |head -n 10
     4.27%     +0.69%  php-fpm                       [.] zend_hash_find
    10.38%     -0.61%  php-fpm                       [.] zend_cpu_supports
     3.13%     +0.49%  php-fpm                       [.] zend_assign_to_typed_ref
    24.82%     -0.45%  php-fpm                       [.] execute_ex
     1.64%     +0.34%  php-fpm                       [.] zend_array_destroy
     0.05%     +0.23%  php-fpm                       [.] zend_get_compiled_variable_value
     0.67%     +0.20%  php-fpm                       [.] php_json_parse
     0.76%     -0.19%  php-fpm                       [.] zend_string_equal_val
     0.76%     -0.18%  php-fpm                       [.] zend_hash_update
     0.51%     -0.18%  php-fpm                       [.] php_string_tolower

sudo perf diff perf.data.5mt_5.9.3 perf.data.5mt_6.0.0 |grep php-fpm |grep '+' |head -n 5
     4.27%     +0.69%  php-fpm                       [.] zend_hash_find
     3.13%     +0.49%  php-fpm                       [.] zend_assign_to_typed_ref
     1.64%     +0.34%  php-fpm                       [.] zend_array_destroy
     0.05%     +0.23%  php-fpm                       [.] zend_get_compiled_variable_value
     0.67%     +0.20%  php-fpm                       [.] php_json_parse

It seems that v6.0.0 with more invocation on above functions

### Step-by-step reproduction instructions

Deploy a wordpress docker container using official image
ARG WORDPRESS_VER="6.0.0" # previous is 5.9.3
ARG WORDPRESS_IMAGE="wordpress"

ARG PHP_VER="7.4"
ARG PHP_PACKAGE="php"

FROM ${WORDPRESS_IMAGE}:${WORDPRESS_VER}-${PHP_PACKAGE}${PHP_VER}-fpm

Deploy a siege benchmark client container
Run siege command in container: siege -c 100 -t 60S -b -f urls.txt # simulate 100 concurrent user to stress 1 minutes

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by talldan** [comment]
@dylan2intel Is that report specifically testing Gutenberg?
