### ISSUE TITLE
Block toolbar does not display if wrapping element has `display: contents;`

### ISSUE THREAD

**Issue by JiveDig** [WordPress/gutenberg#44275]
### Description

When our blocks use `innerBlocks`, WP adds extra wrapping divs which makes CSS flexbox/grid difficult to match styling in the editor. Using `display: contents;` makes things _much_ easier to manage, however, we lose the toolbar if the wrapping element(s) have `display: contents;`.

### Step-by-step reproduction instructions

1. Add a new paragraph block.
2. In the browser, add `display: contents;` to the `p` element, which has the `.block-editor-block-list__block`.
3. The toolbar is now hidden/missing.

### Environment info

Currently testing with:
WP 6.0.2

The issue happens in core and with or without Gutenberg 14.1.1 active.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by seothemes** [comment]
Have run into this many times, the trick is to use `innerBlocksProps.children`:

```tsx
import {
	useBlockProps,
	InnerBlocks,
	// @ts-ignore
	__experimentalUseInnerBlocksProps as useInnerBlocksProps,
} from '@wordpress/block-editor';
import { registerBlockType } from '@wordpress/blocks';
import metadata from "./block.json";

registerBlockType( metadata, {
    edit: props => {
        const blockProps       = useBlockProps();
        const innerBlocksProps = useInnerBlocksProps( blockProps, {
            allowedBlocks: [ 'core/paragraph' ],
            template: [
                [ 'core/paragraph' ],
            ]
        } );

        return (
            <div { ...innerBlocksProps }>
                { innerBlocksProps.children }
            </div>
        );
    },
    save: () => {
        const blockProps = useBlockProps.save();

        return (
            <div { ...blockProps }><InnerBlocks.Content/></div>
        );
    }
} );
```

**Comment by ZebulanStanphill** [comment]
Actually, the correct way to do it is more like how it's done in the [Buttons block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/buttons/edit.js). You want to spread the entire `innerBlocksProps` on the container element.

**Comment by seothemes** [comment]
@ZebulanStanphill yes, that's cleaner. This example was taken from a block where the parent needed some different props. Does the same thing.

**Comment by ZebulanStanphill** [comment]
@seothemes If you use the `children` prop separately, you must still use the other props somewhere, or else things might break. In other words, if you need to use the `children` prop separately, you should do something like:

```jsx
const blockProps = useBlockProps();
const {
	children: innerBlocksChildren,
	...otherBlockProps,
} = useInnerBlocksProps( blockProps, {} );

return (
	<div { ...otherBlockProps }>
		{ innerBlocksChildren }
	</div>
);
```

The reason you should do this is that `useInnerBlocksProps` returns altered `className` and `ref` props in addition to the `children` prop:

https://github.com/WordPress/gutenberg/blob/04d57b34b8574e1f25de0f0bc5862e3da045c6ac/packages/block-editor/src/components/inner-blocks/index.js#L197-L204

**Comment by seothemes** [comment]
Yes you are right, and that’s how it’s done in the block I copied this example from.

I know that Mike is most likely using ACF for registering blocks, so this won’t work anyway, I just wanted to highlight the use of InnerBlocksProps.children.

Since others will see this issue, I’ll update it when I get home to a working example. Basically the same as yours above, just destructured slightly differently.

**Comment by JiveDig** [comment]
Both of those solutions seem to be aimed at removing the extra elements, right? From my understanding, there will still be at least one div necessary so the block editor toolbar and other things can work properly, so `display: contents;` will often be an elegant solution for layout here.

I think my hope is that it would be possible to use display contents on the element while still having the toolbar work. Seems the simplest solution, if at all doable.

**Comment by seothemes** [comment]
I think the issue there is that when setting a top level block to `display:contents`, it loses its positioning, so the toolbar will instead use the position of the parent element (`is-root-container`). That causes the toolbar to be hidden behind `edit-post-header` because of the negative `top` value. To make it visible again for testing you can add this CSS:

```css
.components-popover.block-editor-block-list__block-popover {
    top: 0 !important;
}
```

It's possible to add some JS to change the top positioning of the toolbar depending on the selected block, and check whether it has display:contents, but that feels a bit hacky. Maybe there's an easier way that I'm missing.

I assumed that removing the extra wrapping div would also remove the need for display contents altogether, since that reduces the level of nesting to this:

```html
<div class="is-root-container">
    <div class="wp-block parent-block grid">
        <div class="wp-block inner-block grid-item"></div>
        <div class="wp-block inner-block grid-item"></div>
    </div>
</div>
```

Would that solve the issue? I'm guessing you are wanting to create custom grid layouts for query loops?

**Comment by JiveDig** [comment]
In my scenario (ACF Blocks), and likely other native block situations, I'm not sure it's possible to remove the extra div. That would be ideal but I don't think it's always possible. Adjusting top positioning could help, I must have missed that in my debugging. I'll have to test and see how solid that fix will be for the ever changing block editor styles and markup.

**Comment by seothemes** [comment]
Here's another workaround, and probably a better way. You can set the block toolbar to always display at the top of the editor. I wonder if there's a way to force this for specific blocks:

<img width="640" alt="block editor top toolbar" src="https://user-images.githubusercontent.com/24793388/191647095-bfff9a12-8924-4de6-bdb0-b5be9d836270.png">

**Comment by annezazu** [comment]
Wow! What a great community effort here to help address the problem. Since multiple solutions have been shared and there hasn't been activated for a few weeks, I'm going to close this out. Happy to re-open if needed of course :)
