### ISSUE TITLE
Remove colon (:) from Video and Audio blocks placeholder text

### ISSUE THREAD

**Issue by monika-12** [WordPress/gutenberg#4427]
**## Issue Overview**
 On video and audio blocks  - there is colon after the text "Select a video file from your library:" remove this colon from text. There should be consistency with other block like Image, Gallery, Cover Image.

**## Steps to Reproduce (for bugs)**
1. Insert Video Block
2. Check colon after placeholder text
3. Insert Other block like Image, gallery
4. No colon after  placeholder text

I am using Google Chrome on Windows 10.

**## Expected Behavior**
 Placeholder Text ended without colon.

**## Current Behavior**
 Placeholder Tex ended with colon.

**## Possible Solution**
Remove colon from  placeholder text.

**## Screenshots / Video**
![video-placeholder-text](https://user-images.githubusercontent.com/17018981/34873637-e08d9000-f7bb-11e7-96f7-2c59dbec6c83.png)
![audio-text](https://user-images.githubusercontent.com/17018981/34874075-9009348e-f7bd-11e7-9087-4a42fe39de1d.png)

**Comment by Soean** [comment]
All media blocks:
![media](https://user-images.githubusercontent.com/695201/34875608-45335f6c-f79e-11e7-9dca-21b898a0606d.png)
