### ISSUE TITLE
Cover block top spacing issue TT3 theme

### ISSUE THREAD

**Issue by lwangdu** [WordPress/gutenberg#44274]
### Description

Is there any way you can disable spacing -top if we use cover block with navigation menu on specific template? If you look at the screen shot current tt3, white space looks wired to me.

body {
		     --wp--style--root--padding-top: var(--wp--preset--spacing--40);

}

### Step-by-step reproduction instructions

create cover block with navigation menu on the home page tt3.
go to frontend. there is white space
![Screen Shot 2022-09-19 at 12 52 05 PM](https://user-images.githubusercontent.com/24829573/191110882-6162f967-4d0f-499e-93d1-ebcfb89fcf86.png)

### Environment info

Wordpress version 6.2.0
Gutenberg version 14.1 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@lwangdu thanks for opening this issue! I couldn't replicate. Here's my view with the list view open:

<img width="1466" alt="Screen Shot 2022-09-20 at 2 54 27 PM" src="https://user-images.githubusercontent.com/26996883/191341180-e1f0747b-407f-4475-ba7e-3b076d57508b.png">

Can you drop the markup in here so I can try to replicate?

**Comment by lwangdu** [comment]
Thank you @annezazu checking one this. If you add cover image and menu in a group, that creates the white space above the cover image. If I take theme out the group, the space goes away. I think this is my user error.

**Comment by annezazu** [comment]
Ah okay. Thanks for following up and confirming. I'll close this out in that case since this should indeed work. I also tested with a cover block in a template part and wasn't able to replicate. Thanks for using WordPress :)
