### ISSUE TITLE
Patterns: Consider changing "Text" and "Buttons" categories

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#44280]
## What problem does this address?

Right now, text and button are two categories in the pattern directory. They aren't terribly descriptive around what you're actually going to get when you choose from either due to the simplicity in the naming. If you click through each category, you'll find there's often great overlap too. 

## What is your proposed solution?

Consider evolving these categories into something a bit more meaningful. For a quick idea for text, could rename to "Sections" and for buttons could try "Call to action" since that's usually what buttons are for. My creativity is failing me right now so please share ideas :)  I also think there might be an argument made for potentially merging them into something more comprehensive ("Sections" altogether?). 

_I was torn about whether to separate these out into two different issues since the root problem is the same. If it's easier to do so, say so and I will create a new issue!_

**Comment by jasmussen** [comment]
I think we can close this one in favor of #44501, as that omits text and button categories. What do you think?

**Comment by annezazu** [comment]
Let's do it.
