### ISSUE TITLE
Block toolbar sometimes positioned incorrectly after dragging and dropping a block

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#44281]
### Description

Sometimes when dragging and dropping a block the block toolbar will be positioned incorrectly

### Step-by-step reproduction instructions

1. Add some blocks
2. Drag and drop a few times
3. Observe that sometimes after dropping the block, the toolbar isn't visible. Other times it'll be positioned incorrectly

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/677833/191158525-0d08d0a7-9f0f-4e01-be50-79b1cd180a1d.mp4

### Environment info

Gutenberg trunk

Mac OS / Brave

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ciampo** [comment]
#44301 Fixes the incorrect positioning.

The disappearing will need a separate fix — I will look into it and see what I can discover

**Comment by glendaviesnz** [comment]
@talldan with #44301 [cherry picked into 6.1](https://github.com/WordPress/gutenberg/pull/44301#issuecomment-1258336609) do you think we can close this one now, and open a new one for the disappearing if needed?

**Comment by talldan** [comment]
Yeah, I'm happy with that. IMO, the disappearing thing is very low priority. I don't think most people will notice it.
