### ISSUE TITLE
Latest Posts block fails, probably due to docker or nginx REST issue

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#4430]
Steps to reproduce:

- Use [WP Docker](https://github.com/10up/wp-local-docker) for a local environment
- Insert a Latest Posts block and verify that it just keeps spinning

Screenshots

![screen_shot_2018-01-12_at_13 14 31](https://user-images.githubusercontent.com/1204802/34875291-f614dea2-f79c-11e7-98f4-66209531fec6.png)

![network](https://user-images.githubusercontent.com/1204802/34875294-f7960256-f79c-11e7-9750-5f628479155e.gif)

Note that the Categories block is working fine. 

In the past there were issues with the core REST API on similar environments (nginx), if permalinks weren't "fancy" — it could be related, as the presence of query strings seem to be the biggest difference between the request that 404 fails and the request that 200 works. See this old ticket for more info: https://core.trac.wordpress.org/ticket/40886

This ticket should potentially also be tagged with WP Core Bug, but I'll let you do that. CC @jorgefilipecosta

**Comment by jorgefilipecosta** [comment]
Hi @jasmussen, as we discovered at the time the issue gets resolved by changing to "Day and name" permalink structure, or other custom structure, so it is a know rest API problem already described in https://github.com/WordPress/gutenberg/issues/2596. I'm closing this issue as I think it's duplicate. If the issue does not gets resolved by changing the permalink structure feel free to reopen it so we can debug further.
