### ISSUE TITLE
Video Block: Change block description

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#4432]
## Issue Overview
To make the description of the video block more meaningful and consistent, I would suggest the following change:

**Current Video block description:**
`Video, locally hosted, locally sourced.`
![video](https://user-images.githubusercontent.com/695201/34875833-38d0d212-f79f-11e7-864c-6ab868054f12.png)

**Current Audio block description:**
`The Audio block allows you to embed audio files and play them back using a simple player.`
![audio](https://user-images.githubusercontent.com/695201/34875834-3a66c230-f79f-11e7-9bf7-39965b262f6a.png)

**Proposed Video block description:**
`The Video block allows you to embed video files and play them back using a simple player.`

**Comment by karmatosed** [comment]
Closing as merged solution, thanks!
