### ISSUE TITLE
Cover image: Hide Settings if no image is selected.

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#4433]
## Issue Overview
The Cover image settings of the Cover image block should be hidden, if no image is selected, like in the image, gallery, audio and video block.

## Screenshots / Video
![cover-image-settings](https://user-images.githubusercontent.com/695201/34876345-65471444-f7a1-11e7-8f7d-3f1fe44165df.png)

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521134655000876)._
