### ISSUE TITLE
Media & Text block: Change default value from Wide with to None.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#44352]
### Description

I am adding this as a bug, but it is a default behavior which would be helpful to change.

I noticed on a client site that the Media & Text block width was on Wide width and did not align with the content above it.
The client had not discovered the width icon option in the toolbar.

Here is an example.
![Screenshot 2022-09-22 at 11 05 18](https://user-images.githubusercontent.com/5323259/191706358-eb60a8f7-f871-4580-ba2f-7d27d925b31b.jpg)

It would be helpful to begin with no alignment option active and let the user discover the option to adjust alignment.

### Step-by-step reproduction instructions

1. Insert a Media & Text block.
2. Notice it does not align with text blocks above or below.

### Screenshots, screen recording, code snippet

Screenshot added above.

### Environment info

WordPress 6.0.2
Gutenberg plugin 14.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
Is this similar to the previous issue, #20941?

**Comment by paaljoachim** [comment]
Ahhh yes. I knew I recognized it..:)
I even made the issue that time.
Closing this issue....

Thanks George..:)

**Comment by paaljoachim** [comment]
Reopened the other issue.
