### ISSUE TITLE
Nav block Page List fallback displays too many Pages

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#44360]
By default the Nav block falls back to a Page List. However on a site with a lot of pages this is overwhelming.

<img width="1049" alt="Screenshot 2022-09-22 at 10 52 31" src="https://user-images.githubusercontent.com/444434/191716664-3f45d0d3-6681-4249-abcd-e1c1df1ca71a.png">

The Page List does have an `__unstableMaxPages` attribute but this doesn't appear to be respected by Page List even though the Nav block `index.php` creates the block with this attribute.

This is strange as it was added in https://github.com/WordPress/gutenberg/pull/36877/.

We should make the Page List respect the limit.

**Comment by getdave** [comment]
Noting that the Nav block currently specifies `4` as the fallback

https://github.com/WordPress/gutenberg/blob/42874766e492aacdee1fb73dd94dd7938acbf2a9/packages/block-library/src/navigation/index.php#L311

**Comment by draganescu** [comment]
The problem here is that the `'__unstableMaxPages'` is used only when rendering the block, but not in the editor.

**Comment by carolinan** [comment]
Aside, I have had users asking why this is limited to four in support requests, asking for this number to be increased.
So I think it can be confusing if not all pages show.

**Comment by getdave** [comment]
I've had a think about this overnight. I'm asking myself how many users will actually have this many top level pages? Answer is very few.

Let's optimise for the 80% use case here and avoid limiting the number of items shown. I'll raise a PR to remove the attribute from the Page List and another to remove the functionality from the Nav block.

Does that sound like a good course of action?

**Comment by getdave** [comment]
OK folks I [raised a PR that will remove the max limit attribute from the Page list block](https://github.com/WordPress/gutenberg/pull/44415). Please take a look and let me know if we're happy to accept that if we merge the Navigation block fallback will render unlimited numbers of Pages.

**Comment by jasmussen** [comment]
I [left a comment on the PR](https://github.com/WordPress/gutenberg/pull/44415#issuecomment-1257719117), but should've probably left it here. So copying it over:

> Hey, thanks for this PR! Just catching up on the context, I would agree that the default hard lock of 100 captures edge-case sites. But also with the main purpose of this PR, to have just that, and no additional limits. The page list block is mainly created for that purpose, to just list all of your blocks. When used in the navigation block and especially with the recent fallback behaviors, can provide an default behavior for most users. 
> 
> I would argue that if you have a lot of pages, too many for the menu, you're likely better served by pressing "Edit" to convert the menu to a fully customizable one. This is even despite the fact that custom menu editing still isn't the most intuitive, which is to say we have work there. I like to think that https://github.com/WordPress/gutenberg/issues/42257#issuecomment-1206379911 can play a key factor there.
