### ISSUE TITLE
Global Styles: Invoke zoomed-out view when selecting a style variation

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44419]
Now that we have the [Zoomed-out view](https://github.com/WordPress/gutenberg/pull/41156), we can consider some different ways in which this mode can be automatically invoked based on the current user action.

One such action is choosing a style variation. Zooming out helps give a better idea of the overall affect of the selected style. Observe a comparison below:

https://user-images.githubusercontent.com/846565/191962091-e7af93f2-4a30-479a-8c75-3fd343bdd570.mp4

In the future we can potentially zoom out further to include additional templates, but for now this seems like a nice low-hanging fruit.

**Comment by jasmussen** [comment]
Excellent! The idea has already been brought up in a few disparate comment threads, that a specific button to invoke the zoom mode is a temporary affordance, and things like invoking it automatically when the context shifts (browse styles, or insert pattern) is a better contextual way to do it. 

Let's try it!
