### ISSUE TITLE
Global styles: Offer a way to view a document containing all blocks and styles

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44420]
It's not uncommon to find yourself styling a block in Global Styles without that block being present on the canvas. Consequently you're left unsure as to whether the desired outcome is achieved. 

One solution to this could be providing a dedicated document containing all blocks, that users can observe on demand. Here's a crude example:

<img width="1305" alt="Screenshot 2022-09-23 at 14 26 00" src="https://user-images.githubusercontent.com/846565/191970523-8507d2a1-39d3-405e-9df1-b5cac16c6a70.png">

Such document could be interactive so that clicking a block would take you to the styles panel for that block. Vice versa, navigating to style a block could scroll you to that block on the canvas. In the future you could possibly drill in to one block to view and manage its states and styles.

**Comment by dannyreaktiv** [comment]
Could be a block pattern or part of the Theme Unit Test, unless you mean it to be something dynamic that loads everything available to the editor.

**Comment by annezazu** [comment]
Noting that this feels very similar to this prior issue: https://github.com/WordPress/gutenberg/issues/32682

**Comment by jameskoster** [comment]
I think #32682 is more architectural / high level. 

> unless you mean it to be something dynamic that loads everything available to the editor

That's the sort of thing I had in mind. Blocks added by plugins etc should be included.

**Comment by carolinan** [comment]
This seems related to the suggestion to add a "style guide":[ Block pattern directory: Consider adding a Style Guide category](https://github.com/WordPress/pattern-directory/issues/483) 
@colorful-tones

**Comment by carolinan** [comment]
Also related is that the accessibility team is asking for a post with all the blocks -but they need it to be published, available on the front for testing.
Perhaps it could be an actual post that can be published, like the Gutenberg demo ( wp-admin/post-new.php?gutenberg-demo)

**Comment by javierarce** [comment]
I love this idea! And I know that the image above is a concept but if users can interact with the right sidebar, showcasing the examples on a modal could be weird since, in any other context, modals get closed when clicking outside. 

I can see this working more similarly to a focus mode, where the example document is embedded in the canvas. 

In any case, this will be super helpful.

**Comment by jameskoster** [comment]
Absolutely, the focus mode would work much better. It could even trigger automatically when you open the Styles panel and offer a switcher UI in the dark canvas area.

**Comment by annezazu** [comment]
@javierarce  are you still planning to jump in here to share some designs? We're coming up on a few weeks since you commented and I remember seeing that you would be so wanted to check in :)

**Comment by mtias** [comment]
Approaching it from a demo post perspective makes sense to me, though I'd also consider it being a virtual page using the `example` definition from blocks.

**Comment by fabiankaegy** [comment]
I love the idea of this and it would be very useful for thinks like VRT testing and also client demos where they have one "Kitchensynk" that contains everything that is available to them.

I really liked the [blockbook](https://github.com/youknowriad/blockbook/) exploration @youknowriad did a few years ago. Especially the concept of ["Block Stories"](https://github.com/youknowriad/blockbook/blob/master/example/.blockbook/stories/cover.js)

Some block have very different visual appearances depending on the settings provided. And I worry that limiting this to only showing the `example` of each blocks will not really represent the breath of options users have. 

Having a system such as the "Block Stories" in blockbook would allow you as the theme author to define additional configurations on top of the `example` that should get shown in this design guide page.

**Comment by javierarce** [comment]
@annezazu I've been a bit busy with other things lately, but I'll take a stab at this. Thanks for the ping.

**Comment by ramonjd** [comment]
I hacked something together using example content in packages/edit-site/src/components/block-editor/index.js, just to explore possibilities.


https://user-images.githubusercontent.com/6458278/202622257-8f2824bc-bdd8-4c48-9832-f8cb7becaf65.mp4

It temporarily replaces the blocks value in `BlockEditorProvider`

It assumes there's a better UI control somewhere to "toggle" example preview on. 😄 

Code here: https://github.com/WordPress/gutenberg/pull/45929

For Global styles there could be a default template using some base blocks, but I was thinking that, for individual blocks, it would be great to be able to fetch the navigation context from [GlobalStylesNavigationScreen](https://github.com/WordPress/gutenberg/blob/647dcd6435786e81158f7420977f2f5f4f4268dd/packages/edit-site/src/components/global-styles/ui.js#L28). 

That way, maybe, it would be possible to render an example block on the fly based on the global styles menu position, e.g., `/blocks/menu-block-core-audio`

There are inline previews planned over in:

- https://github.com/WordPress/gutenberg/issues/42919

An example/demo page would rather demonstrate how styled blocks behave in the context of a page, so I see usefulness in both approaches.

**Comment by javierarce** [comment]
Here's a first idea for this functionality: 


https://user-images.githubusercontent.com/4933/203119122-b1dbebea-32f7-458d-ac18-78dcb095b1ca.mov


- The functionality could be called "style book" (typographers usually call this type of guide Specimen book, but that's a name too obscure to use)
- I'm not sure what's the best placement to invoke this functionality from, but I considered several places including the site header at the top of the screen. The ellipsis menu, like in @ramonjd's prototype, could be a good spot. Ultimately I decided to try the sidebar because this could be an important customization feature.
- In terms of functionality, the video shows how you can pick a block and customize it on the right sidebar or go the other way around: pick a block from the list and highlight it on the canvas.
- The labels next to each block shouldn't be affected by the customization.
- Blocks use the content from their internal examples.
- The tabs on top of the screen follow [this categorization](https://wordpress.org/support/article/blocks).
- I haven't addressed the demo post idea, but I imagine this could be a post users would publish once through a button in the sidebar.

Here's a list of unanswered questions I have:

- Where should we display the blocks added by plugins? Should they appear in a different category or could we place them inside the 6 categories? Should we display them differently?
- Should we allow modifying the content of the block? In that case, what happens if a user wants to reset their changes?


[Figma file](https://www.figma.com/file/3CtpCjdXvt1ZQLu7P1m13k/Global-styles-summary-view-for-blocks-and-styles?node-id=1%3A2) with the designs and the prototype from the video.

**Comment by noisysocks** [comment]
I can work on this.

> Should we allow modifying the content of the block? In that case, what happens if a user wants to reset their changes?

In my mind the style book would be powered via the existing `example` content that each block specifies and so modifying the content isn't allowed. Clicking on a block would open up the appropriate panel in Global Styles, not select the block or insert a cursor. 

> Where should we display the blocks added by plugins? Should they appear in a different category or could we place them inside the 6 categories? Should we display them differently?

The simplest thing to do I think is to completely mirror the block inserter. Whatever categories appear in the block inserter would appear as tabs in the style book. For example if you activate the Jetpack plugin you'd see _Earn_, _Grow_ and _Jetpack_ tabs.

**Comment by carolinan** [comment]
Follow up on that, is there a list of blocks that needs examples added?

**Comment by jameskoster** [comment]
> The simplest thing to do I think is to completely mirror the block inserter.

+1.

@javierarce I'm not sure about the switch – with this appearance it kind of looks like a setting. An alternative idea (feel free to disregard) could be to have the document title + Style Book act as tabs when the Styles panel is open: 

<img width="876" alt="Screenshot 2022-11-22 at 10 27 35" src="https://user-images.githubusercontent.com/846565/203291075-a6c4e58a-e1af-4eeb-acdf-36391ed20eef.png">

That way we can avoid the `<- Back` button which is always a bit awkward, and the Style Book can be toggled regardless of how far you drill into styles. 

For the empty space around the Style Book, should we use the same dark grey as focus mode?

**Comment by javierarce** [comment]
> @javierarce I'm not sure about the switch – with this appearance it kind of looks like a setting. An alternative idea (feel free to disregard) could be to have the document title + Style Book act as tabs when the Styles panel is open:

Thanks! That would definitely solve the issue with the back button… my only doubt is how to render the different states when you have an area selected so that it's clear that you can switch between modes:

![image](https://user-images.githubusercontent.com/4933/203299487-8007ce44-ec67-4b6a-80fd-91e8030d787e.png)

> For the empty space around the Style Book, should we use the same dark grey as focus mode?

I discarded that idea because it would make it difficult to see which tab is selected. We could solve that by integrating the navigation inside the panel as you did in your original design… the only issue would be that if we allow resizing the canvas, it could break the navigation.

**Comment by javierarce** [comment]
> Thanks! That would definitely solve the issue with the back button… my only doubt is how to render the different states when you have an area selected so that it's clear that you can switch between modes:

Maybe instead of tabs it could be a button that launches this special view 🤔

https://user-images.githubusercontent.com/4933/203305207-7957c509-fd23-4a4a-b818-606db647ac59.mov

**Comment by jameskoster** [comment]
My thinking was that since the focus shifts to styles, things like block selection and document meta/actions can take a back seat. That's why I removed the chevron. Maybe there are other appearance options to explore 🤔 

One other consideration here is mobile, where it's not possible to view the canvas and the styles panel simultaneously. _Should_ it be possible to invoke the Style Book in that context? If not, that may be another argument for placing the button in the top toolbar because it will inherently be hidden on small screens.

**Comment by noisysocks** [comment]
I think I would miss the Style Book button if it were in the editor toolbar because I'd be looking at the Global Styles panel in order to complete my task of "change the styles".

**Comment by jameskoster** [comment]
One other option might be to zoom out slightly when you enter Styles, and place the tabs on the empty space. Prettier than this, but you get the idea:


https://user-images.githubusercontent.com/846565/203533478-a1d596f8-8acb-49fb-85a3-eeb902d574f0.mp4

Figuring out how we want this to work on mobile will likely be pivoltal in getting the entry-point right.

**Comment by noisysocks** [comment]
> Figuring out how we want this to work on mobile will likely be pivoltal in getting the entry-point right.

That's a good point. On mobile, the Global Styles panel fills the entire screen. If the Story Book button were in the block editor toolbar you wouldn't see it on mobile as it would be beneath the Global Styles panel.

On mobile I imagine the Story Book would be modal. One would make changes, open the story book, close, make more changes, open the story book, close, and so on.

This makes me think that the Story Book button needs to live in a persistent part of the Global Styles panel. Perhaps the toolbar? Maybe we steal the eye 👁️ icon in https://github.com/WordPress/gutenberg/issues/42919? Just spitballing 😀

![](https://user-images.githubusercontent.com/1204802/182621707-dfb9ea87-3635-40e1-abe4-ff5bf63fc8a1.png)

**Comment by jameskoster** [comment]
> On mobile I imagine the Story Book would be modal. One would make changes, open the story book, close, make more changes, open the story book, close, and so on.

It's an option, but that flow sounds a bit convoluted to me. Especially once #42919 lands and a visual preview of the block is already present within the panel itself. 

The main benefits of the Style Book seem to be the interactions (clicking a block to go directly to its associated panel), and the ability to see changes in 'real time' as you manipulate the controls – particularly foundational things like typography, colors, and spacing / layout. Neither of these are going to work very well on mobile, so it might be worth considering it a desktop-only feature?

None of this prohibits placing the button in the panel, I suppose we'd just need to hide it on mobile.

**Comment by mtias** [comment]
We had included it here in the global styles design from a couple years ago:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/548849/203777675-1e786ae0-4aa8-4166-8cab-59889198207d.png">

The top of the panel also seems fine given the ellipsis menu sits there.

**Comment by noisysocks** [comment]
I'm not quite finished with https://github.com/WordPress/gutenberg/pull/45960 yet but it's probably ready enough for some early design feedback. There's a video in the PR description.

**Comment by javierarce** [comment]
> One other option might be to zoom out slightly when you enter Styles, and place the tabs on the empty space. Prettier than this, but you get the idea:

I prefer this solution to the use of the eye icon (which, to me, feels a bit obscure to decipher in this context).

In case we can consider other ways to present this feature, I've tried a variation that keeps the tabs on top and uses a dropdown to select the block categories.

https://user-images.githubusercontent.com/4933/204010145-dd1b0d61-d034-4c00-8587-3f7a7853fec0.mov

**Comment by noisysocks** [comment]
I like the "zoom out when Styles is open" behaviour. It illustrates the strong relationship between Style Book and Styles. Not sure about the dropdown. It looks a little out of place. Could a vertical tab bar on the left similar to the pattern inserter work?

**Comment by noisysocks** [comment]
I'm just about ready to put final touches on https://github.com/WordPress/gutenberg/pull/45960 so need to know what the decision is re. design. Could you confirm what design I should implement as a first iteration? We can always change things later 🙂

**Comment by jameskoster** [comment]
Thinking a bit more long term, I think the tabs make more sense. When Styles become a discrete feature, the Style Book / Template tabs can be more literal UI elements that update the 'frame':

<img width="1280" alt="Screenshot 2022-11-28 at 10 41 07" src="https://user-images.githubusercontent.com/846565/204258325-b0a1f93f-90e9-4e03-a04c-9a84b60b3455.png">

For more context see https://github.com/WordPress/gutenberg/pull/44770
