### ISSUE TITLE
List v2: Can't merge two consecutive List blocks

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#44436]
### Description

See #42711, in which the List block was upgraded to support nested blocks and which was the starting point to subsequent fixes.

Now, merging two simple lists via <kbd>Backspace</kbd> or <kbd>Delete</kbd> doesn't produce a condensed list.

### Step-by-step reproduction instructions

1. In an empty editor, create a simple list by typing "- a", then Enter, then "b"
2. Press Enter twice to break out of the list and start in a new block
3. Input "- c", then Enter, then "d" to create the second list
4. Move the caret to the left of "c" and press Backspace
5. OR Move the caret to the right of "b" and press Delete

Expected: a single list of "a", "b", "c", "d"
Observed: one list left intact, the other one converted into several paragraphs.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/150562/192120265-64bd20d0-1538-4377-af6f-58bac058051c.mov

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mcsf** [comment]
(cc @ellatrix)

**Comment by ellatrix** [comment]
@mcsf There's an old PR that fixes this :) #43181
