### ISSUE TITLE
Paragraph block can't be transform into Quote block

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#44452]
## Description

The Paragraph block in the web version can be transformed into a Quote block, however, this option is not available in the native version.

## Step-by-step reproduction instructions

1. Add a Paragraph block.
2. Type some text.
3. Tap on the "..." button to open the block settings.
4. Tap on "Transform block..." option.
5. Observe that the option for Quote is not displayed.

## Expected behaviour

The Paragraph block can be transformed into a Quote block.

## Actual behaviour

The Paragraph block CAN'T be transformed into a Quote block.

## Screenshots or screen recording (optional)
Web version|Native version
--|--
<img width="354" alt="Screenshot 2022-09-26 at 10 23 06" src="https://user-images.githubusercontent.com/14905380/192229310-41346375-737d-4f0b-ba0d-d399ae59a989.png">|<img width="354" src=https://user-images.githubusercontent.com/14905380/192229322-c10f0e83-a314-4624-bfdb-37df3d42b2d3.PNG>

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 11
- Operating system: iOS 15.4.1
- WordPress app version: WordPress-iOS 20.7.0.4

**Comment by fluiddot** [comment]
I debugged this issue and found that was introduced when Quote V2 was introduced, specifically when the transforms logic was updated due to using inner blocks ([reference](https://github.com/WordPress/gutenberg/pull/25892/files#diff-aae5b36f45a467214ca6c674e0c40aa6d67afb6886af52bccac00d78d56d79db)). In Quote V1, we had a `from` transform for `core/paragraph` block, now that block is transformed using the wildcard `from` transform:
https://github.com/WordPress/gutenberg/blob/9580611aaa63b80a3ac490c11dfa83db52b923e5/packages/block-library/src/quote/transforms.js#L62-L91

The problem is that when we introduced the block transformation feature in the native version, we explicitly disabled support for wildcard block transform ([reference](https://github.com/WordPress/gutenberg/pull/28453/files#diff-3fbd4c0db6cff0321f313fd5d26d509a897408e2af0d95b488e3fa8c2fb66e8bR232-R238)). Nevertheless, it's not clear to me why we decided to do this based on the [original PR](https://github.com/WordPress/gutenberg/pull/28453) and [issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2814) 🤔.

I tried enabling support for wildcard block transform, by removing this part, and now I can transform the Paragraph block to the Quote block. However, this also enables other transformations like _Paragraph block => Group block_ that were originally disabled. As far as I tested, all transformations work as expected and match the web version's behavior, so I'm wondering what exactly prevented us to enable all transformations ❓.

Following [the original issue](https://github.com/WordPress/gutenberg/pull/28453), I see some comments about not supporting all transformations ([comment reference](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2814#issuecomment-729275760)) because some of them could be confusing to the user (e.g. _Paragraph block => Columns block_). However, I haven't found any technical argument that discouraged enabling all transformations, apart from not including the blocks that are unsupported in the native version. Being this said, maybe this is good timing to enable all missing transformations to users, wdyt?

cc @iamthomasbishop as was involved in [the original issue's discussion](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2814).

**Comment by SiobhyB** [comment]
> However, I haven't found any technical argument that discouraged enabling all transformations, apart from not including the blocks that are unsupported in the native version. Being this said, maybe this is good timing to enable all missing transformations to users, wdyt?

I agree that enabling the missing transformations seems like a good path, so that we're matched up to the web as closely as possible. I think users would expect the functionality to work the same across platforms.

If we feel that some transforms are illogical or confusing, I think it'd be best to open issues for wider community discussion, rather than diverging in the apps.

**Comment by fluiddot** [comment]
> I agree that enabling the missing transformations seems like a good path, so that we're matched up to the web as closely as possible. I think users would expect the functionality to work the same across platforms.

My only concern about this change is that we'd need to check all transform combinations in case there are any unsupported or lead to errors. Apart from this, I agree that this seems like a good path.

> If we feel that some transforms are illogical or confusing, I think it'd be best to open issues for wider community discussion, rather than diverging in the apps.

Good point! I think we haven't reviewed the UX of transforming blocks since [the original change](https://github.com/WordPress/gutenberg/pull/28453) was released. But definitely, if we identified some transform confusing we should open the discussion to the Gutenberg community and collect feedback there instead disabling the features in the app 👍 .
