### ISSUE TITLE
Improve the Group placeholder

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44465]
<img width="727" alt="Screenshot 2022-09-26 at 13 56 23" src="https://user-images.githubusercontent.com/846565/192282142-45a3437d-32e2-43a4-bfbf-16fcd03b2808.png">

When we think of the Group as an empty container, it fair to assume that the user will want configure some kind of layout with the blocks they place inside it, the current placeholder doesn't facilitate this very well. We can surface shortcuts to create rows/stacks/columns here, but there's potential for more elaborate layout configurations to be suggested as starting points too.

**Comment by jasmussen** [comment]
There's a design for this in #43433 👌
