### ISSUE TITLE
Gutenberg: Function to refresh a server-side-render block without altering its contents

### ISSUE THREAD

**Issue by mtoensing** [WordPress/gutenberg#44469]
## What problem does this address?

I currently refresh my server side rendered block by passing the current timestamp as an attribute. I do this when the post is saved to reload some data. That leads to the issue that the editor thinks that there is some changed content in the post.  The changed attribute results in a changed post and triggers the message "Changes you made may not be saved." How can I force a reload of my SSR block without passing attributes and changing its contents? Is there another way? 

```
 const blockProps = useBlockProps();
/* Update SimpleTOC if the post is saved successfully.          */
  /* Source: https://github.com/WordPress/gutenberg/issues/17632  */
  const { isSavingPost } = select( 'core/editor' );
  const [isSavingProcess, setSavingProcess] = useState(false);
  const advpanelicon = 'settings'; 
  const updatePost = function () {
    if( attributes.autorefresh === true ) {
      setAttributes({ updated: Date.now() 
    }
  };
```

## What is your proposed solution?
A function to simply refresh the server response of a server side rendered block without setting a random attribute.

**Comment by t-hamano** [comment]
I think this is a question and I will convert it to a discussion.
