### ISSUE TITLE
Should Gutenberg continue to automatically add <p> paragraph tags?

### ISSUE THREAD

**Issue by cr101** [WordPress/gutenberg#4446]
I'm using Gutenberg 2.0.0 Code Editor

When I open a CPT that I created with the Classic Text Editor the post content is automatically wrapped with `<p>` tags.
Is there a way to tell Gutenberg to not automatically wrap the content in `<p>` tags as I don't want any html tags in the database?

Since I'm using the Code Editor instead of the Visual Editor I except to have full control over the use of HTML tags.

**Comment by bobbingwide** [comment]
See https://github.com/WordPress/gutenberg/issues/4672#issuecomment-360530537

**Comment by bobbingwide** [comment]
You may wish to add why you can’t use the other block types to achieve what you could happily do in the Classic text editor. I recently discovered, though I’ve not raised an issue yet, that the Custom HTML editor has its own ideas about what you can do!

**Comment by cr101** [comment]
> You may wish to add why you can’t use the other block types to achieve what you could happily do in the Classic text editor.

I have over 10,000 CPTs that have been created using the Classic text editor. The issue is that when I activate Gutenberg and then open one of the CPTs the `<p>` tags are automatically created. Going through 10k CPTs to remove all the `<p>` tags and then use a different block type is a massively time consuming job.

Users should be given a third option as to which editor they would like to use: Visual Editor, Code Editor or **Classic Text Editor** (as in New lines remain as new lines, they do not get converted into `<br />` tags or spaces and No automatic creation of `<p>` or `<br />` tags.)

Not everyone uses WordPress for blogging!

**Comment by aduth** [comment]
Can you verify whether this is the same issue described at #3901 ?

**Comment by cr101** [comment]
@aduth I'm not sure that it is the same.
To fully understand my issue see the steps below:

1. Create a post using the **Classic Text Editor**
![screenshot_66](https://user-images.githubusercontent.com/4064582/38131212-ce9978d0-3462-11e8-9728-36fa3417bb52.jpg)

2. Enable the Gutenberg plugin and then edit the post using the **Code Editor**. As you can see all the paragraphs were automatically wrapped in `<p>` tags which is annoying.
![screenshot_67](https://user-images.githubusercontent.com/4064582/38131677-7bf84cbc-3464-11e8-9447-f743a79e0081.jpg)
 
I personally never use the Visual Editor and I'd like to have full control over what HTML I use in my posts.

**Comment by aduth** [comment]
Okay, so I believe I understand better now. This is expected in current incarnation of Gutenberg, as it does not perpetuate the classic editor's assumptions of [`wpautop`](https://codex.wordpress.org/Function_Reference/wpautop). Arguably, if your goal is to have full control over HTML in your posts, this is a more accurate representation. The paragraphs would have been applied previously, but _magically_ so. This magic has been removed here: the tags are displayed as they will be effected on the front end of a site.

Whether we still want to add wpautop as an optional support is another question. I could, for example, imagine a separate mode which is not strictly HTML, but this mixed wpautop behavior.

**Comment by SuperGeniusZeb** [comment]
Personally, I always really disliked the magic invisible paragraph tags of `wpautop` in the Classic Editor. If the editor was going to add paragraph tags, I wanted to be able to see them. It always seemed inconsistent and weird that paragraph tags were invisible while every other tag was not.

**Comment by cr101** [comment]
This also has implications when hiding/showing more text within a certain length on the front-end if the post content is wrapped with `<p>` paragraph tags. Please keep in mind that some of us use WordPress as a CMS instead of a blog.

**Comment by SuperGeniusZeb** [comment]
@cr101 Presumably, shouldn't something that counts content length in a post ignore HTML tags? At least, that seems like the way that it should be done. Adding/removing `<strong>`, `<em>` or other tags to your content should not change the size of an automatically-generated excerpt.

**Comment by cr101** [comment]
We are building a headless WordPress web app using React and the WordPress API. 
When a post is created from within the WordPress Admin the post content will have `<p>` tags wrapped around it but when the post content is created from the front-end and pushed through the WordPress API the content will not have the `<p>` tags.
 
Therefore, displaying the content on the front-end will not be consistent.

**Comment by aduth** [comment]
>when the post content is created from the front-end and pushed through the WordPress API the content will not have the `<p>` tags.

Which front-end editor are you referring to? To be clear, you _could_ pass `<p>` and they'd be respected. It's correct to note that if you choose not to, the default behavior of [`wpautop`](https://developer.wordpress.org/reference/functions/wpautop/) will take effect unless block demarcations are detected within the post's content.

**Comment by danielbachhuber** [comment]
> Should Gutenberg continue to automatically add `<p>` paragraph tags?

At this point, the answer is yes: paragraph tags will continue to be added around text that's historically been magically transformed by `wpautop`. There is a non-zero number of bugs with this right now though. We'll continue to fix the bugs as they come up.

**Comment by cr101** [comment]
@danielbachhuber From a consistency point of view, will the content of a post created through the WP REST API be automatically wrapped in `<p>` paragraph tags as well?

**Comment by danielbachhuber** [comment]
> From a consistency point of view, will the content of a post created through the WP REST API be automatically wrapped in `<p>` paragraph tags as well?

This is something we could consider if you'd like to open a core Trac ticket.

**Comment by rstmsn** [comment]
Any updates on this ? 

The fact that Gutenberg elects to add <p> tags when rendering content on the front end, that are hidden when editing using the 'View as HTML' editor on the backend, is rather frustrating and seemingly confused.

**Comment by cr101** [comment]
@rstmsn That's exactly the frustration I've been having with using Gutenberg. The `<p>` tags are forced on you, are hidden and can't get rid of them. 
Gutenberg should allow users to have full control over HTML in their posts when in "Code Editor" mode or "Edit as HTML".

**Comment by rstmsn** [comment]
@cr101 agreed. Is this being discussed elsewhere ? Seems like a rather glaring issue to me...

**Comment by aduth** [comment]
> The fact that Gutenberg elects to add `<p>` tags when rendering content on the front end, that are hidden when editing using the 'View as HTML' editor on the backend, is rather frustrating and seemingly confused.

Can you clarify in what cases you see no `<p>` when using "View as HTML" ? Is this the block's "Edit as HTML" mode? Is it for a Paragraph block or for a Classic block?

For paragraphs, I cannot reproduce the missing `<p>`. They are shown:

![image](https://user-images.githubusercontent.com/1779930/49829868-9649b980-fd5d-11e8-8870-3766a7db9524.png)

For classic block, the block mimics pre-5.0 behavior, where the omission of paragraph tags has existed since 2003 (the "autop" behavior). 

See: https://developer.wordpress.org/reference/functions/wpautop/

**Comment by emfluenceindia** [comment]
> > The fact that Gutenberg elects to add `<p>` tags when rendering content on the front end, that are hidden when editing using the 'View as HTML' editor on the backend, is rather frustrating and seemingly confused.
> 
> Can you clarify in what cases you see no `<p>` when using "View as HTML" ? Is this the block's "Edit as HTML" mode? Is it for a Paragraph block or for a Classic block?
> 
> For paragraphs, I cannot reproduce the missing `<p>`. They are shown:
> 
> ![image](https://user-images.githubusercontent.com/1779930/49829868-9649b980-fd5d-11e8-8870-3766a7db9524.png)
> 
> For classic block, the block mimics pre-5.0 behavior, where the omission of paragraph tags has existed since 2003 (the "autop" behavior).
> 
> See: https://developer.wordpress.org/reference/functions/wpautop/

When I disable visual editor and code editor is my only option. I have the following two paragraphs written in code editor:

```
<p>The P tag disappears when I take the focus out of this editor</p>
<p style="font-weight: bold;">The P tag does not disappears even when I take the focus out of this editor if the P tag has an attribute</p>
```

**Comment by ericbhanson** [comment]
My team is also affected by this decision, as it happens when they switch between the Code and Visual editors in the Classic block in Gutenberg. I would also like to be able to prevent the <p> tags from being added in the first place.
