### ISSUE TITLE
Unable to get `core-editor` data in Site Editor for Templates or Template Parts

### ISSUE THREAD

**Issue by ALJ** [WordPress/gutenberg#44477]
### Description

I regularly use `select('core/editor').getCurrentPostType()` to read the type of post currently being edited in the block editor. I use this to tailor the editor and allow certain blocks for ease of editing. This works wonderfully on `post`, `page`, and any custom post type. But, this does not work in the Site Editor when editing a **Template** or **Template Part**.

I'm eager to find out if there is any way to identify exactly _which_ Template or Template Part is currently being edited.

Without that data, I can't streamline the editor to, e.g., provide a footer-specific block in the "Footer" Template Part only. Without this, the otherwise excellent https://github.com/WordPress/gutenberg/pull/42729 isn't as useful as custom post types are to let us simplify the experience for content editors.

### Step-by-step reproduction instructions

The following examples use WordPress@6.0.2 with the TwentyTwentyTwo theme active. I have tried with and without Gutenberg@14.1.1 active, and the results are the same.

#### Baseline example on a `post` (i.e. working data stores providing good data)

1. Open a post in the block editor
2. In the browser's console, run `wp.data.select('core/editor').getCurrentPostType()`
    ✅ See `"post"` returned, which is what I expect
3. Run `wp.data.select('core/editor').getCurrentPostId()`
    ✅ See `837` (or whatever ID you have) returned, which is what I expect

#### Non-working example in the Site Editor

1. Open the Site Editor through `Appearance` > `Editor`
2. Edit the site's `Home` template
3. In the browser's console, run `wp.data.select('core/editor').getCurrentPostType()`
    ❌ See `null` returned, which is surprising. I expect to see `wp_template` (or `wp_template_part` when editing a Template Part).
4. In the browser's console, run `wp.data.select('core/editor').getCurrentPostId()`
        ❌ See `null` returned, which is surprising. I expect to see `twentytwentytwo//home` (or `twentytwentytwo//header` when editing the Header Template Part).

### Environment info

- WordPress@6.0.2
- TwentyTwentyTwo theme active
- Gutenberg@14.1.1 active (or non-active, doesn't matter)
- Firefox@104.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@ALJ There are some different selectors in the site editor:
```js
const templateType = wp.data.select( 'core/edit-site' ).getEditedPostType();
const templateId = wp.data.select( 'core/edit-site' ).getEditedPostId();
```

If you're working on a block and trying to make it work in both the post editor and site editor, that may be a bit challenging.

You can probably check for the availability of 'core/edit-site' selectors:
```js
if ( wp.data.select( 'core/edit-site' ) ) {
    // This is the site editor
}
```

**Comment by ALJ** [comment]
Thank you @talldan, that's exactly what I was looking for. I missed that data store in the documentation.

**Comment by merijnponzo** [comment]
thanks @talldan 
Do you know if this will be supported ? I have found some links about using 'core/edit-site') with for example getBlocks which is marked as deprecated.



i was thinking to use your example to save some additional content whenever the site-editor.php is used on template parts
```
const templateType = wp.data.select( 'core/edit-site' ).getEditedPostType();
const templateId = wp.data.select( 'core/edit-site' ).getEditedPostId();
```
I checked the functions of core/edit-site
 
<img width="465" alt="Screenshot 2023-08-04 at 14 52 05" src="https://github.com/WordPress/gutenberg/assets/23075300/c534aecd-0458-410a-bf03-3978e41d433c">

But none the functions would return the actual post id of the wp_template_part within the wp_posts table.
Instead it returns the template parts name as an id like **ponzotheme//footer**

I could try to use wp-json like
```
http://sitename.test/wp-json/wp/v2/template-parts/ponzotheme//footer
```
but i suppose i would get the content of before the save instead of after the save 

Any ideas on how to get the actual id and context of the template part within

```
document.addEventListener("DOMContentLoaded", function () {
  if (typeof wp !== "undefined") {
    if (wp.data !== undefined) {
      const { dispatch } = wp.data;
      wp.data.subscribe(() => {

        // is within site editor
        if ( wp.data.select( 'core/edit-site' ) ) {
            
          const templateType = wp.data.select( 'core/edit-site' ).getEditedPostType();
          const templateId = wp.data.select( 'core/edit-site' ).getEditedPostId();
          const templateContent = wp.data.select( 'core/edit-site' ).getEditedPostContext();
          console.log(wp.data.select( 'core/edit-site' ), templateType, templateId, templateContent)
        }

      
  ````

thanks

**Comment by merijnponzo** [comment]
this is also discussed within https://github.com/WordPress/gutenberg/issues/53230
