### ISSUE TITLE
Query block doesn't display sticky posts when inheriting from template

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44471]
## Description
Here's my home page on the frontend:

<img width="869" alt="Screenshot 2022-09-26 at 17 50 49" src="https://user-images.githubusercontent.com/846565/192335751-850fea90-aa0a-4b9a-8270-99ecf4ff20a1.png">

Note the sticky post. It doesn't appear in the Query loop in the Site Editor:

<img width="1575" alt="Screenshot 2022-09-26 at 17 51 11" src="https://user-images.githubusercontent.com/846565/192335798-0368fddb-289c-478b-a807-894894c7b6c7.png">

## Step-by-step reproduction instructions
1. Make a post sticky
2. Ensure your home page is set to display latest posts
3. Open the site editor
4. Observe the missing sticky post

## Expected behaviour
I expected the sticky post to appear.

**Comment by annezazu** [comment]
@jameskoster does this occur with 6.1 beta 1? Wondering if we need to add it to the project board.

**Comment by jameskoster** [comment]
> does this occur with 6.1 beta 1? 

Yup, same experience on 6.1 beta 1.

**Comment by tellthemachines** [comment]
Was this ever working before? A quick test shows it doesn't work in 6.0.2.

**Comment by jameskoster** [comment]
I'd never checked until now, so I don't know. I'm surprised it never came up 🤔

**Comment by Mamaduka** [comment]
I think this is a Core REST API issue.

> The current solution for sticky posts is to not give them special treatment by default, but to provide a ?sticky= parameter to explicitly exclude them or to return only stickies, added in https://github.com/WP-API/WP-API/pull/2708.

Source: https://github.com/WP-API/WP-API/issues/2764

Trac ticket: https://core.trac.wordpress.org/ticket/35907

**Comment by cbravobernal** [comment]
Removing this issue from the 6.1 dashboard.

**Comment by AllTerrainDeveloper** [comment]
I can't replicate the issue, using latest version up to today.

1. I've created a bunch of new posts.
2. I've checked that all of them are showing in the main page (even there is a button to show "older posts")
3. I've went ahead and edited one of the first post that were shown when viewing "older posts"
4. I've checked the sticky post option
5. I've updated the post
6. I've checked that the post was the first one in the latest posts.

**Comment by tellthemachines** [comment]
@AllTerrainDeveloper are you looking in the front end? This issue is only reproducible within the Query block in the site editor.

**Comment by AllTerrainDeveloper** [comment]
Oops! You are right, I didn't test it in the proper way!

**Comment by richtabor** [comment]
> I think this is a Core REST API issue.

@Mamaduka is there a path forward for this? There are a few efforts to clean up the Query Loop block and this is one that sticks out as a missed expectation when using sticky posts.

**Comment by Mamaduka** [comment]
@richtabor, there's been no updates for the REST API issue, which is the current blocker here.

**Comment by ntsekouras** [comment]
Should we close this one as is a core issue and tracked here: https://core.trac.wordpress.org/ticket/35907?

**Comment by Mamaduka** [comment]
@ntsekouras, yes. I think we can close the issue here. It's not actionable on the editor side and needs a REST API fix.
