### ISSUE TITLE
Unable to add link in the table first column. 

### ISSUE THREAD

**Issue by aniljadhavmca** [WordPress/gutenberg#4447]
## Issue Overview

Unable to add link in the table first column. If we add link on the second column text it's work fine.
But for the first column add link seems have z-index issues here is the detail screen recording - https://goo.gl/HWF9gm

Gutenberg version - 2.0.0

## Steps to Reproduce (for bugs)
1. Add Three column table 
2. Add link to the first row's of all three columns
3. First columns link have some z-index issue

Google Chrome 

## Screenshots / Video
 https://goo.gl/HWF9gm
 https://goo.gl/LZUoMc

**Comment by joaodfmota** [comment]
Remove `overflow-x` from `\blocks\library\table\style.scss` work's like a default text block.

![capture002](https://user-images.githubusercontent.com/3788221/34943822-71e4b842-f9e4-11e7-9e53-a6c57f13a698.JPG)


```css
.wp-block-table {
    overflow-x: auto; /* Remove this line */
    display: block;
}
```

But I think this something like this should be better:

![capture001](https://user-images.githubusercontent.com/3788221/34943834-78a71486-f9e4-11e7-976a-84924f9d7298.JPG)

**Comment by aniljadhavmca** [comment]
@joaodfmota Thanks for the reply, Second option link box inside the table tr will looks good.

I am sending PR for this fix.

**Comment by amychan331** [comment]
It seems like this haven't been work on since January. Can I try this as my first bug?
