### ISSUE TITLE
Microsoft Forms embedding fails

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#44495]
### Description

When you copy and paste an embed copy of a Microsoft Form, it fails. It shows the url and doesn't embed the form with the embed block. If you use a Custom HTML block and input the HTML code there, it does work. 

### Step-by-step reproduction instructions

1. Copy the embed code of a MS Forms form.
2. Just paste it in Gutenberg and it will change into the embed block.
3. Publish and it won't work.

The embedblock made from:
<iframe width="1100px" height="500px" src="****" frameborder="0" marginwidth="0" marginheight="0" style="border: none; max-width:100%; max-height:100vh" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>

This;
<figure class="wp-block-embed"><div class="wp-block-embed__wrapper">
**LINK**
</div></figure>

Which only shows the URL on the page.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Whether this is supported or not depends on whether Microsoft supports the oEmbed protocol (https://oembed.com/). oEmbed is the only protocol that WordPress supports for embedding via URLs.

I'd recommend creating a support ticket with Microsoft to ask whether they support that. I couldn't find any information on it when searching the internet.

For now, using the HTML block is an absolutely fine solution (and that's the intended way to add embeds for services that don't support oEmbed).

**Comment by jordesign** [comment]
Given there are requirements from Microsoft's end on this issue - I'll close it for now. We can re-open (or open a new issue) if need be in the future
