### ISSUE TITLE
Error converting page with several images to blocks

### ISSUE THREAD

**Issue by ChemicalSailor** [WordPress/gutenberg#4449]
I opened up an old page with several inline images in gutenberg which shows it as a classic block. Used the convert to blocks option. Each paragraph and image gets converted to their own blocks BUT the src for every image points to the first one found. I also loose alignment, but I can see that may be theme related.

**Comment by spencerfinnell** [comment]
I have also seen this occur when converting an old post to blocks.

**Comment by spencerfinnell** [comment]
Saw this in 1.9.x and 2.0

**Comment by jorgefilipecosta** [comment]
This issue should be fixed in master now.
