### ISSUE TITLE
Template inspector: Surface revisions panel

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#44503]
Templates and template parts [support revisions](https://github.com/WordPress/wordpress-develop/blob/b4acf193d1cac4b287492b762dfc2344b0942cbe/src/wp-includes/post.php#L388). We should surface these in the inspector for Templates and Template Parts, especially because those inspectors are already so empty.

It could be surfaced in the same way as it is in the post editor, just as a link to the revisions page:

<img width="1600" alt="Revisions in template inspector, just a link" src="https://user-images.githubusercontent.com/1204802/192533772-06990cc4-9694-4f7f-a34e-2d7c066e5e1d.png">

**Comment by carlomanf** [comment]
This was already requested at #36060

**Comment by mtias** [comment]
This is a quick win given revisions are already enabled just not exposed. A link to the revisions interface would provide a lot of value.

**Comment by priethor** [comment]
Should revisions be shown in during Template Editing Mode in the Post Editor? That might be a bit less direct than just adding revisions to the Site Editor sidebar, as during Template Editing Mode, [the hidden sidebar](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-post/src/components/sidebar/settings-sidebar/index.js#L84) belongs to the post context.

**Comment by mtias** [comment]
It should be added on the template tab, whenever that is displayed.

**Comment by georgeh** [comment]
I'll take a look at this one

**Comment by georgeh** [comment]
It looks like the REST API is not returning links to the previous revisions of template parts, so we will have to add that before we can add this button. I'm looking into adding that

**Comment by georgeh** [comment]
This is mostly ready to go, but is blocked by [a bug in the REST routes for template revisions](https://core.trac.wordpress.org/ticket/56922). The CSS on #45215 could use some cleanup, though.

**Comment by jordesign** [comment]
Just checking in on the progress of this? Having these revisions surfaced in the Inspector would be fantastic!

**Comment by spacedmonkey** [comment]
@draganescu @georgeh @priethor @ramonjd @Mamaduka Core patch is ready and needs code review before it get merged in WP 6.4 beta 3. Please can a look and test!
