### ISSUE TITLE
theme.json: Add support for description in customTemplates

### ISSUE THREAD

**Issue by dashkevych** [WordPress/gutenberg#44514]
Default templates, such as Single, Page, Index, ect, come with a description text, while custom templates do not have such text.

<img width="581" alt="editor-tempaltes" src="https://user-images.githubusercontent.com/3655965/192598880-4981409b-cae5-4c27-8180-c76be663f1fd.png">

It would be great if we were able to display a description text in custom templates, set via `theme.json`, to provide more information about the custom template.

For instance:

```js
"customTemplates": [
    {
        "name": "blank",
        "postTypes": [
            "page",
            "post"
        ],
        "title": "Blank",
        "description": "Empty template."
    },
}
```

**Comment by t-hamano** [comment]
@dashkevych
Thanks for the suggestion.
I think this is the same as #44097, so let's close this issue and focus the discussion on #44097.
