### ISSUE TITLE
Feedback on Plugin/PR to Expose JS Tree via REST API

### ISSUE THREAD

**Issue by marcato15** [WordPress/gutenberg#4451]
## Issue Overview
I'm looking into the possibility of using Gutenberg in conjunction with the library of React Components we've amassed at our company for building Single Page Apps. I've looked through the documentation for building custom Blocks for Gutenberg and I don't think it'd be too difficult to convert a number of our React Components to Gutenberg blocks. However, as a SPA we only need the structured data from the REST API, but currently the only thing returned is the generated HTML. I was wondering if there has been any discussion about exposing [the JSON tree ](https://wordpress.org/gutenberg/handbook/language/#a-tree-of-blocks)that the editor creates when you load a page in the backend, via the REST API so I could reconstruct things on the front end without having to rely solely on the generated HTML. I'll plan to build this as a standalone plugin for now, but I wonder if I'm not the only one who might benefit from such an addition to the API.

**Comment by jasmussen** [comment]
Questions like this are, unfortunately, likely to get lost in this repo. For visibility your best bet is to ask in the [WordPress core slack](https://make.wordpress.org/chat/), channel #core-editor. 

However (and note that my dev chops aren't superb like those of my friends also lurking here, but busy) — your use case sounds perfectly valid. I think it'll make a great plugin, but if you like you can submit as a pull request. It may be a fit for Gutenberg. 

Closing for now, but feel free to ask more in the slack if you like! Thanks.
