### ISSUE TITLE
Clicking the 'Open list view' button on the Navigation block feels broken when list view is already open

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44512]
https://user-images.githubusercontent.com/846565/192582778-1ce51ef2-f611-4ff7-bbf9-3fb1f3a23940.mp4

Should we make it a toggle so that it opens _and_ closes list view?

**Comment by ntsekouras** [comment]
>Should we make it a toggle so that it opens and closes list view?

Is this what we want or needs discussion/decision? If it would be a toggle, it should have an 'active' state, right?

**Comment by jameskoster** [comment]
> Is this what we want or needs discussion/decision?

Yes.

> If it would be a toggle, it should have an 'active' state, right?

Yeah, I think the normal on/off states for toolbar buttons (like making text bold) could be adequate.
