### ISSUE TITLE
@wordpress/env: unable to launch wp-env start

### ISSUE THREAD

**Issue by Romaixn** [WordPress/gutenberg#44513]
### Description

Hello, when I launch wp-env start I have this error : 

```
wp-env start
✖ spawn docker-compose ENOENT
Error: spawn docker-compose ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn docker-compose',
  path: 'docker-compose',
  spawnargs: [
    '-f',
    '/home/user/.wp-env/30b8183d6cf815f19db8a6d137712b0d/docker-compose.yml',
    'down'
  ]
}

```

I just have a wp-env.json with that inside : 
```json
{
  "core": null,
  "phpVersion": "7.4",
  "plugins": ["."]
}
```

I thought it might be due to the update of docker compose and its integration into the new version of Docker.

When I enter the generate folder in .wp-env and run the docker compose up -d command, everything launches correctly.

### Step-by-step reproduction instructions

1. Go to random plugin folder
2. Create .wp-env.json given
3. Launch wp-env start 

### Environment info

- wp-env 5.3.0
- Docker 20.10.18
- Docker Compose 2.10.2
- Pop!_OS 22.04 (eq Ubuntu 22.04)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @Romaixn,
What is the version of wp-env? I believe this problem was fixed in version 5.1.1.

https://github.com/WordPress/gutenberg/blob/trunk/packages/env/CHANGELOG.md#511-2022-08-16

**Comment by Romaixn** [comment]
Hi @t-hamano, 5.3.0 !

EDIT: I added it to description of issue

**Comment by t-hamano** [comment]
Sorry I could not reproduce it, although it is a little different from your environment.
I will wait for others to test.

- OS: Ubuntu 20.04.4 LTS (on Windows WSL2)
- Docker version: 20.10.17
- Docker Compose version v2.10.2
- wp-env version: 5.3.0

**Comment by talldan** [comment]
> 5.3.0 !

@Romaixn Is that a local version of the package? If so, there's a chance you could have a global version installed that's an older version.

**Comment by Romaixn** [comment]
@talldan It's the version installed with npm -g : 

![Capture d’écran du 2022-09-29 11-09-58](https://user-images.githubusercontent.com/18333296/192991296-53ea38f0-a864-4227-94a8-b14cfa4e70d7.png)

So I think it's the good version..

**Comment by MildMaro** [comment]
I got the same error.

- wp-env 5.4.0
- Docker 20.10.18
- Docker Compose 2.10.2
- Ubuntu 22.04.05
```
Error: spawn docker-compose ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn docker-compose',
  path: 'docker-compose',
  spawnargs: [
    '-f',
    '/wp-env/4316fabe0f937d71032824b8a712ad16/docker-compose.yml',
    'down'
  ]

```
I was using docker compose, so i installed docker-compose and tried it and got a different error
```
 Error while running docker-compose command.
Couldn't connect to Docker daemon at http+docker://localhost - is it running?
```
the problem was solved by Enable Docker Compose V1/V2 compatibility mode in the Settings section of Docker Desktop.

**Comment by Mamaduka** [comment]
Hi, @Romaixn

Did you get a chance to test the solution provided by @MildMaro?

**Comment by Romaixn** [comment]
Hi ! Yes sorry I forgot to answer! Indeed by activating the compatibility in the settings of Docker Desktop it works!  Thanks a lot @MildMaro

**Comment by Aljullu** [comment]
While I know this issue has been closed for some time now, posting an alternative solution for reference.

If you are using docker directly from the command line instead of Docker Desktop, you can create a `/usr/bin/docker-compose` executable that forwards all calls to `docker compose`. It's explained in detail here:

https://stackoverflow.com/questions/72099653/how-to-alias-docker-compose-to-docker-compose/72187587#72187587

**Comment by rdundon** [comment]
What worked for me is burninating the global package (e.g `npm -g uninstall wp-env`), and relying on a locally-installed version in my plugin repo.
