### ISSUE TITLE
TT3 Style Variations show a scrollbar for one variation

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#44515]
### Description

When using 6.1 beta 2 with the new TT3 theme, one of the style variations shows a scrollbar in chrome. FYI @ndiego . 

### Step-by-step reproduction instructions

1. Use beta 2 for 6.1
2. Activate TT3
3. Open Site Editor
4. Open Styles
5. Notice whisper variation has a scrollbar

### Screenshots, screen recording, code snippet

<img width="288" alt="Screen Shot 2022-09-27 at 2 00 25 PM" src="https://user-images.githubusercontent.com/26996883/192602328-2bb446d0-a3e0-410d-b901-d76ab2985ab9.png">

### Environment info

- WordPress 6.1 beta 2
- TT3
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Yes I can confirm. The reason is that variation has a site border, which is reflected in the Global Styles preview. 

![image](https://user-images.githubusercontent.com/4832319/192603182-d39423fd-eb7c-4fef-9c46-64197803ec26.png)

![image](https://user-images.githubusercontent.com/4832319/192603251-2f877cd3-fcea-423d-aa3b-0395045ebb97.png)

**Comment by talldan** [comment]
I think a developer may need design feedback on the right way to fix this, so I've added the label.

Should the preview show the variation's border? I suppose that's possible but it might be difficult to account for any border and still fit the contents of the preview neatly in the rectangle.

Possibly a better option would for the border not to be shown, the preview iframe could have a reset for any border (as well as margin if that isn't already in place).

**Comment by ndiego** [comment]
> Possibly a better option would for the border not to be shown, the preview iframe could have a reset for any border (as well as margin if that isn't already in place).

Yeah I agree with this approach. Likely the easiest to implement and the best way to ensure consistency in the variation previews.

**Comment by t-hamano** [comment]
I was just investigating this issue as well, and I think `useResizeObserver` is not getting a width that takes borders into account.

https://github.com/WordPress/gutenberg/blob/cbaa18495869932e04eaa1cac82b86001053d352/packages/edit-site/src/components/global-styles/preview.js#L98-L109

I also agree with not displaying borders in the preview, as a very thick border would squash the preview area.
