### ISSUE TITLE
Why Page Template option is not available under Page Attributes?

### ISSUE THREAD

**Issue by rajuahmmedbd** [WordPress/gutenberg#4454]
Hello,

I can't find page template option under Page Attributes with gutenberg. I this this thing is missed or some how is not showing for me.

## Screenshots
With Classic Editor
![screenshot](https://user-images.githubusercontent.com/28896200/34912681-5f8e9614-f911-11e7-9d80-cbf2e6f20b11.png)

With gutenberg
![screenshot_3](https://user-images.githubusercontent.com/28896200/34912686-68dcb39a-f911-11e7-882b-a3596981090f.png)

**Comment by mtias** [comment]
Hi. See https://github.com/WordPress/gutenberg/issues/991 for more information. Closing as duplicate.

**Comment by burtonkent** [comment]
> Hi. See #991 for more information. Closing as duplicate.

It's not a duplicate. That page discusses the exact field that this issue says is missing.

**Comment by KhoaVT** [comment]
I got the same problem, the drop-down template missing. I found out that I moved the style.css to my-custom-css folder in my child theme. I had to move it back to the theme (in my case I use child-theme) folder, then it works well.

**Comment by ethanclevenger91** [comment]
Commenting here since this is the top Google result for this:

WordPress 6.0.2
Gutenberg 14.2

The template picker was moved here:

![image](https://user-images.githubusercontent.com/2623646/195192305-4c1b7ecf-bca8-4ecc-942a-74fcc60c2617.png)

**Comment by parimal100** [comment]
> Commenting here since this is the top Google result for this:
> 
> WordPress 6.0.2 Gutenberg 14.2
> 
> The template picker was moved here:
> 
> ![image](https://user-images.githubusercontent.com/2623646/195192305-4c1b7ecf-bca8-4ecc-942a-74fcc60c2617.png)
 
Man that was so helpful. Such a small thing but had almost half an hour scratching my head over it. Thanks once again.
