### ISSUE TITLE
When I'm trying to use Query Loop block, it is not giving me any option to filter via custom field.

### ISSUE THREAD

**Issue by muhammadharoonbro** [WordPress/gutenberg#44577]
### Description

When I'm trying to use Query Loop block, it is not giving me any option to filter via custom field.

### Step-by-step reproduction instructions

Try using Query Loop block and you will see it for yourself. Because I'm trying to fetch all results where students' subject is English (acf field).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Duplicate of #31390
