### ISSUE TITLE
Zoom out view when the "Patterns" in the Inserter is selected

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44585]
Related to https://github.com/WordPress/gutenberg/issues/44419

When inserting patterns, particularly via drag-and-drop, it feels a bit cumbersome if you want to place the pattern towards the bottom of the document. We can potentially fix this by invoking the [zoomed-out](https://github.com/WordPress/gutenberg/pull/41156) view automatically when you navigate to the Patterns tab in the Inserter. 

Here's a demo:

https://user-images.githubusercontent.com/846565/193071402-89b55800-4080-427f-9b64-058dc00f2a6b.mp4

There may even be an argument to zoom out when inserting regular blocks too, but Patterns feels like a good place to start.

**Comment by jasmussen** [comment]
Love it. As I said on #44419, this feels like an excellent small iteration to graduate the experiment. Let's try it!

**Comment by annezazu** [comment]
Updated the title to say "inserter" as I think that's what you meant :) Feel free to update if I got that wrong.

**Comment by ntsekouras** [comment]
What happens if the zoom out view is invoked and then we want to navigate to the `blocks` tab in the inserter(or any other tab or search)? Stays that way or we toggle again? It might feel a bit weird, no?

**Comment by jameskoster** [comment]
The zoom would be linked to the Patterns tab active state I think, so yes if you navigate to blocks it would zoom in again. Given the work you're doing in https://github.com/WordPress/gutenberg/pull/45203 searching should be covered. 

> It might feel a bit weird, no?

It might do :) We need to try it to tell for sure.
