### ISSUE TITLE
Surface related patterns in the template inspector

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44582]
When editing a template or template part, it would be nice to find associated patterns in the Inspector. 

For template parts that might look something like:

![template](https://user-images.githubusercontent.com/846565/193064234-81da73ae-3d60-4746-a7d2-343f938f055e.gif)

It could work the same for templates too, but we'd need a way for patterns to be associated with specific templates. For example it wouldn't be helpful to be suggested 404 patterns while editing the Archive template.

**Comment by carolinan** [comment]
love this!

**Comment by jasmussen** [comment]
Plus one. Love it! Let's make it happen. (Though maybe I'd have a separator between the inspector header and patterns, perhaps even a subheading for the patterns).

**Comment by annezazu** [comment]
Noting that this matches this prior feedback that came in: https://github.com/WordPress/gutenberg/issues/39864 For consistency/to consolidate, I'm going to close mine out but wanted to be sure that the inability to do this has been noted as a pain point in the past.

**Comment by oandregal** [comment]
I'm going to investigate this. I remember having seen a mention or a sketch for having the ability to switch whole sections in the zoom-out view as well (or was it the site editor?), though I can't find it now. I guess both things are related. Would anyone have a link/sketch handy?

**Comment by oandregal** [comment]
I am reading through prior art and ran into this use case:

- We allow patterns to declare which block types they support ([blockType](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/#block-patterns-contextual-to-block-types-and-pattern-transformations)). These patterns will be surfaced in the block toolbar as any other transformation.
- The same works for _many selected blocks at once_. Though, note the inspector in this case: it's empty.

![Captura de ecrã de 2022-10-19 16-18-23](https://user-images.githubusercontent.com/583546/196717332-05e05c72-cf27-449f-9388-c71146122a8b.png)

Letting this here as another potential place to surface patterns a set of blocks can be transformed into.

**Comment by jameskoster** [comment]
> I remember having seen a mention or a sketch for having the ability to switch whole sections in the zoom-out view as well

This is still a WIP, but yes I would say that both are related. 

There's also the [shuffle concept](https://github.com/WordPress/gutenberg/issues/44581) for templateLock:contentOnly blocks which is similar. Indeed this could drive the transforms you mention. IE if you select a heading and a paragraph the transform menu could expose patterns that are made up of those content blocks specifically.

**Comment by oandregal** [comment]
Raw prototype at https://github.com/WordPress/gutenberg/pull/45285 It should be enough to clarify some questions.

**Comment by paaljoachim** [comment]
I believe the other solution to add a cycle icon in the Pattern Group block toolbar to show various patterns directly in the canvas is an even better way to go: 
https://github.com/WordPress/gutenberg/issues/44581

Because:
-- It would show the pattern in it's native place.
-- It could create a broader solution between Patterns and Group blocks in which I brain stormed in this comment:
https://github.com/WordPress/gutenberg/issues/44581#issuecomment-1500591327
(Basically a Pattern is a special Group block. Just like row, stack or grid.)

**Comment by annezazu** [comment]
@oandregal checking in here to ensure this is still on your list to move forward as it's been a few months since active work was completed on the PR.

**Comment by oandregal** [comment]
> checking in here to ensure this is still on your list to move forward as it's been a few months since active work was completed on the PR.

Oh, thanks for checking. This slip through the cracks, sorry about that. I had https://github.com/WordPress/gutenberg/pull/45285 and https://github.com/WordPress/gutenberg/pull/47507, but I no longer know whether they are in a good state to be merged or how long they'll require.

I have some upcoming AFK and some threads I'm involved in, so I'd rather free this one up for anyone to take. I may be able to come back at this in a couple of weeks if I manage to wrap up the other work.

**Comment by jameskoster** [comment]
Like shuffling (https://github.com/WordPress/gutenberg/issues/44581), the full scope of where related patterns can be surfaced will be exposed as a part of https://github.com/WordPress/gutenberg/issues/27575.

**Comment by mtias** [comment]
@jameskoster I'm not sure we are capturing this specific flow in that issue. I think the templates sidebar is an ideal place to get something going. Could be a collapsible panel with patterns of a relevant category to start.

**Comment by SaxonF** [comment]
Not sure about using the inspector for this as I could accomplish the same thing via inserter. Could we add a "recommended" or "switch" category at the top of the patterns inserter that will work for all scenarios? e.g. replacing similar patterns

**Comment by jameskoster** [comment]
@SaxonF we could do both. Is there a specific reason you had in mind for not using the Inspector?

**Comment by mtias** [comment]
Yeah, this doesn't take away from other flows that might become, in time, more intuitive. But right now the inspector is completely empty and missed opportunity for discovering existing relevant patterns in context.

**Comment by MaggieCabrera** [comment]
This is very important for TT4. Right now it's easy to swap from the post editor, but that is not good for certain templates like archive.html. This will surface those patterns so much better.

**Comment by MaggieCabrera** [comment]
This is very important for TT4. Right now it's easy to swap from the post editor, but that is not good for certain templates like archive.html. This will surface those patterns so much better.

**Comment by annezazu** [comment]
Adding this back to 6.4 after seeing the above note about this being important for TT4, which is a blessed task.

**Comment by richtabor** [comment]
If we're concerned about performance, we could potentially add these to a panel, have it closed initially perhaps as well. At least until https://github.com/WordPress/gutenberg/issues/54999 is explored further. 

Also, we could set a max number of rendered previews with a “View all” button to open the modal, similar to how the pattern explorer is set within the inserter.

**Comment by scruffian** [comment]
I've made a start on this: https://github.com/WordPress/gutenberg/pull/55091

**Comment by annezazu** [comment]
With just over a week until beta 1, punting this out of 6.5 as the associated PR hasn't yet been merged and this wasn't a strong focus for the release.
