### ISSUE TITLE
Separator block does not render correctly inside a Query Pagination block

### ISSUE THREAD

**Issue by mikachan** [WordPress/gutenberg#44587]
### Description

I want to add a nested Separator Block to a Query Pagination block so that the Separator conditionally displays based on the Query Pagination.

However, when I try this, on the front end, the `hr` renders with 0px width and height. I believe this is because the Query Pagination block uses `display: flex`, so I'm wondering if there's some CSS we could add to the Separator Block to ensure it always shows with the correct width.

Also, I'm not sure if this is the intended functionality yet, so maybe this is more of a feature request...

### Step-by-step reproduction instructions

1. Insert a Query Pagination block
2. Insert a Separator block inside the Query Pagination block
3. Notice how the `hr` element for the separator block does not render on the front end

Here's some sample markup:

```
<!-- wp:query-pagination {"paginationArrow":"arrow","align":"wide","layout":{"type":"flex","justifyContent":"space-between"}} -->
	<!-- wp:separator {"align":"wide"} -->
	<hr class="wp-block-separator alignwide has-alpha-channel-opacity"/>
	<!-- /wp:separator -->
	<!-- wp:query-pagination-previous {"label":"Newer Posts"} /-->
	<!-- wp:query-pagination-next {"label":"Older Posts"} /-->
<!-- /wp:query-pagination -->
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Randomly ran into this while troubleshooting an unrelated issue with my theme. 

Under my conditions, only the 'wide line' block style were invisible on the front end; the other styles that are included by default with gutenberg; did display. 

In my test case, the width of the separator is 0; rendering it invisible to the naked eye on the front end. 

to reproduce: 
1. create a row block 
2. insert separator block as first child item of it; apply wide-line block style 
3. add some other content inside the row block 
4. publish

**Comment by carolinan** [comment]
I don't think it is intended for the separator to be inside the query pagination block. 
It is not possible to place it inside the query pagination in the block editor.

**Comment by mikachan** [comment]
I think this is the same issue as described in https://github.com/WordPress/gutenberg/issues/47993, happy to close this in favour of that issue, as it's more generic.
