### ISSUE TITLE
Gutenberg Attributes not showing when using default

### ISSUE THREAD

**Issue by marshallshelly** [WordPress/gutenberg#44586]
### Description

I used attributes in blocks I made for Gutenberg. The attributes had default values. It works perfectly in the editor but after clicking save, it does not show up in the PHP rendered save block (in `$attributes`)

First block
```jsx
registerBlockType("mr/companies", {
  title: "Companies",
  attributes: {
    images: { type: "array", default: [] },
    variant: {
      type: "string",
      default: "boxed",
    },
  },
  edit: EditComponent,
});
```
To see if all the attributes are rendering correctly, I tried rendering them to UI in PHP save block.
```php
<code><?php echo json_encode($attributes) ?></code>
```
But only the `images` attributes show up, the `variant` won't show up UNLESS I remove the default or select any other variant that is not the default.

Please advice.

### Step-by-step reproduction instructions

```js
import { PanelBody, PanelRow, Button } from "@wordpress/components";
import {
  InspectorControls,
  MediaUpload,
  MediaUploadCheck,
} from "@wordpress/block-editor";
import { registerBlockType } from "@wordpress/blocks";
import { RadioControl } from "@wordpress/components";
import Companies from "./variants/companies";

registerBlockType("mr/companies", {
  title: "Companies",
  attributes: {
    images: { type: "array", default: [] },
    variant: {
      type: "string",
      default: "boxed",
    },
  },
  edit: EditComponent,
});

function EditComponent({ attributes, setAttributes }) {
  return (
    <>
      <InspectorControls>
        <PanelBody title="Images" initialOpen>
          <PanelRow>
            <MediaUploadCheck>
              <MediaUpload
                onSelect={(files) =>
                  setAttributes({
                    images: files.map(({ alt, id, url }) => {
                      return { alt, id, url };
                    }),
                  })
                }
                allowedTypes={[
                  "image/png",
                  "image/jpeg",
                  "image/svg+xml",
                  "image/webp",
                ]}
                multiple
                value={attributes.images}
                render={({ open }) => (
                  <Button onClick={open}>Choose Images</Button>
                )}
              />
            </MediaUploadCheck>
          </PanelRow>
        </PanelBody>
        <PanelBody title="Variants" initialOpen>
          <PanelRow>
            <RadioControl
              label="Variants"
              hideLabelFromVision
              selected={attributes.variant}
              options={[
                { label: "Boxed", value: "boxed" },
                { label: "Borderless", value: "borderless" },
              ]}
              onChange={(value) => setAttributes({ variant: value })}
            />
          </PanelRow>
        </PanelBody>
      </InspectorControls>
      <Companies {...attributes} />
    </>
  );
}
```

The save block looks like this for now
```php
<code><?php echo json_encode($attributes) ?></code>
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
> To see if all the attributes are rendering correctly, I tried rendering them to UI in PHP save block.

@CodingXD Do you have some more info on your PHP implementation? If you could share an expanded code snippet that would be good.

**Comment by marshallshelly** [comment]
Its just some HTML with tailwind classes
```php
<div class="w-full p-10 bg-[#101010] flex flex-col justify-center items-center space-y-4">
    <h4 class="text-white text-xl">You are in a <?php echo $attributes['variant'] ?> variant</h4>
    <div class="border-t border-b py-3 flex flex-row flex-wrap items-center justify-evenly gap-x-5 w-4/5">
        <?php
            if ($attributes['images']) {
                foreach($attributes['images'] as $attr) {
                    echo '<img src="'.$attr["url"].'" class="w-28 h-auto" alt="'.$attr["alt"].'" loading="lazy">';
                }
            }
        ?>
    </div>
</div>
```

**Comment by talldan** [comment]
@CodingXD Ah, I was more interested in the surrounding code though for your render callback. How is it registered?

**Comment by marshallshelly** [comment]
Ah, you meant this
```php
class JSXBlock
{
    public function __construct($name, $renderCallback = null)
    {
        $this->name = $name;
        $this->renderCallback = $renderCallback;
        add_action('init', [$this, 'onInit']);
    }

    public function ourRenderCallback($attributes, $content)
    {
        ob_start();
        require get_theme_file_path("/blocks/{$this->name}.php");
        return ob_get_clean();
    }

    public function onInit()
    {
        wp_register_script($this->name, get_stylesheet_directory_uri() . "/build/{$this->name}.js", array('wp-blocks', 'wp-editor'));

        $ourArgs = array(
            'editor_script' => $this->name,
        );

        if ($this->renderCallback) {
            $ourArgs['render_callback'] = [$this, 'ourRenderCallback'];
        }

        register_block_type("mixrank/{$this->name}", $ourArgs);
    }
}

new JSXBlock('card');
new JSXBlock('companies', true);
```

**Comment by talldan** [comment]
I think it's related to `register_block_type`. If you have your attributes in a block.json file, the code for this function will load it and so know what the default value of attributes is if it can find the file:
https://github.com/WordPress/wordpress-develop/blob/1fe666f574bd57050d13eee489ce62f2e9c16174/src/wp-includes/blocks.php#L524-L530

But because your attributes are declared in a JavaScript file, PHP doesn't have any way to read the default values.

I think you should be able to fix it in one of two ways. The first is switch to using a `block.json` file. For this you may want to use `register_block_type_from_metadata` instead of `register_block_type` as it will allow you to pass it the path to your block.json. This would probably be the recommended way. There may be tutorials out there, but the easiest option is to reference one of the core blocks, tag cloud is pretty straightforward - https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/tag-cloud.

Alternatively I believe you can add your attribute declarations in your `$ourArgs` array—add an `attributes` property that's an associative array and has the same shape as your JavaScript attributes.

I'll close the issue for now, but will keep an eye for replies. Let me know how you get on!

**Comment by marshallshelly** [comment]
Thanks for the assist @talldan 
After going through some comments in `register_block_type_from_metadata`, I see that the `register_block_type` now supports adding `block.json` since Wordpress 5.8.
