### ISSUE TITLE
Navigation block: Submenu issues when Open on click is enabled

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#44591]
### Description

This affects the editors only.
When the option Open on click is enabled in the navigation block:

- **Page list** submenus with more than one level can not be expanded. If the page list has more than one level of child pages, the first submenu item displays the arrow button, but clicking on it closes the whole submenu instead of displaying the next page. This behavior is different from the submenu block, where all nested items can be expanded.
(In the video you can also see that I'm miss clicking the arrows several times, or nothing happens when I believe I have clicked the submenu arrows.)

https://user-images.githubusercontent.com/7422055/193176059-f422ee12-f94c-4213-9c6a-d0a4176b42ae.mov

- In both the submenu block and the page list submenus, the first item in the submenu is missing spacing (padding?)
<img width="703" alt="Screen Shot 2022-09-30 at 04 15 25" src="https://user-images.githubusercontent.com/7422055/193175652-0d0239f8-cb4a-441f-826a-f1eec3b43e41.png">

### Step-by-step reproduction instructions

On your WordPress install, you need at least 3 pages and 3 posts.
Add two of the pages as child pages, so that there are 3 levels, parent, child, "grandchild"

In either editor, add a navigation block.
Enable "Open on click"
Add the page list with the nested pages to the navigation.
Add a navigation link with 2 submenu levels -(submenu block)

Try to expand all submenu items, compare the page list and the submenu block.
Confirm if the first item in the submenu has the expected spacing.

### Environment info

Only tested on 6.1-beta2-54361 with current Gutenberg trunk and the beta tester plugin.
Chrome.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by carolinan** [comment]
I Retested this today and grand child pages in the page list block submenu can still not be expanded. Clicking on the arrow that is on the child page level does nothing; it no longer closes the whole submenu as described in the issue.

**Comment by getdave** [comment]
> In both the submenu block and the page list submenus, the first item in the submenu is missing spacing (padding?)

I can no longer replicate this.

> Page list submenus with more than one level can not be expanded.

This is still an Issue and has more discussion in https://github.com/WordPress/gutenberg/issues/60738.

For practicality, unless the first issue still exists, I propose we close this issue in favour of those. Do you agree @carolinan?
