### ISSUE TITLE
Slash command, to add an inner block, in "Add Citation" section of Quote Block is still allowed

### ISSUE THREAD

**Issue by jpollock** [WordPress/gutenberg#44617]
### Description

In the Quote Block, in Add Citation field, the slash command is showing up when it should not.

### Step-by-step reproduction instructions

1. Create a new post
2. Add a Quote block.
3. Place cursor in the "Add citation" section of the Quote block.
4. Type "/".
5. Select one of the available blocks.

### Screenshots, screen recording, code snippet

![issue_with_quote_add_inner_block](https://user-images.githubusercontent.com/656561/193316131-0720ef34-0cdd-4a33-978f-e4d21e76132c.gif)

### Environment info

WordPress version: WordPress 6.1-beta2 (running in Local)
Gutenberg version: N/A
Are all plugins except Gutenberg deactivated? No; using WordPress Beta Tester plugin
Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty-Three
OS: macOS Monterey 12.6
Browser: tested in Chrome, Firefox and Safari

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I can confirm this. As the new Quote block is a primary feature of 6.1, I think we need to get this fixed before release.

**Comment by glendaviesnz** [comment]
[This seems to fix it](https://github.com/WordPress/gutenberg/pull/44634) - it looks like `__experimentalSlashInserter` support was added before the v2 of the block so shouldn't be needed now.
