### ISSUE TITLE
[WP 6.1] Block Styles in theme.json do not appear in the Editor or Frontend

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#44619]
### Description

When Gutenberg is not active, block styles in theme.json are not getting rendered in the Editor or Frontend in WordPress 6.1 Beta 2. Activating Gutenberg solves this, so perhaps something has not been properly ported back to Core. 

Also seems like it might be related to: https://github.com/WordPress/gutenberg/issues/44434

### Step-by-step reproduction instructions

1. Use WordPress 6.1 Beta 2 and the new TT3 theme
2. Ensure Gutenberg is not active
3. Add the sample code to block styles in theme.json (not needed but makes the issue more clear)
4. Add a new page and add a Code, Group, and Pullquote
5. See that the custom block styles in theme.json are not applied in both the Editor and Frontend
6. Now activate Gutenberg and see that everything works correctly

```
"core/code": {
	"color": {
		"background": "var(--wp--preset--color--secondary)",
		"text": "var(--wp--preset--color--base)"
	},
	"spacing": {
		"padding": {
			"bottom": "var(--wp--preset--spacing--30)",
			"left": "var(--wp--preset--spacing--30)",
			"right": "var(--wp--preset--spacing--30)",
			"top": "var(--wp--preset--spacing--30)"
		}
	},
	"typography": {
		"fontSize": "var(--wp--preset--font-size--small)"
	}
},
"core/group": {
	"color": {
		"background": "var(--wp--preset--color--secondary)",
		"text": "var(--wp--preset--color--base)"
	},
	"spacing": {
		"padding": {
			"bottom": "var(--wp--preset--spacing--30)",
			"left": "var(--wp--preset--spacing--30)",
			"right": "var(--wp--preset--spacing--30)",
			"top": "var(--wp--preset--spacing--30)"
		}
	},
	"typography": {
		"fontSize": "var(--wp--preset--font-size--small)"
	}
},
```

### Screenshots, screen recording, code snippet

**Without Gutenberg active:**
![image](https://user-images.githubusercontent.com/4832319/193323890-34377d20-cfe1-409a-a6df-50b5387742b5.png)

**With Gutenberg active:**
![image](https://user-images.githubusercontent.com/4832319/193324090-2c5d2e2d-7aa3-4e53-a33d-439052b19baa.png)

### Environment info

- WordPress 6.1 Beta 2
- Gutenberg **NOT** active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bph** [comment]
@ndiego I can confirm this bug with a clean installation of the WordPress 6.1 beta 2 version.

**Comment by mikachan** [comment]
I can also replicate this with TT3 and another theme called Archeo, using the same test instructions above.

**Comment by andrewserong** [comment]
> Also seems like it might be related to: https://github.com/WordPress/gutenberg/issues/44434

Just confirming that yes, I think this is the same underlying issue — just noticed from a different perspective 🙂
I believe the proposed fix in https://github.com/WordPress/wordpress-develop/pull/3373 should resolve both issues.

**Comment by ockham** [comment]
If I'm not mistaken, this can also be reproduced with TT2 (with no changes to `theme.json`).

To test, insert some button blocks and view on the frontend. [They should be rectangular, with a dark green background](https://github.com/WordPress/wordpress-develop/blob/c819764c81c8b14de9104f5488a88c949e715b25/src/wp-content/themes/twentytwentytwo/theme.json#L224-L237) (rather than round and black).

| Actual (broken) | Expected (correct) |
| --- | --- |
| <img width="1136" alt="image" src="https://user-images.githubusercontent.com/14988353/192704978-e43957d7-8868-490c-814d-83c6fe24fae1.png"> | <img width="1136" alt="image" src="https://user-images.githubusercontent.com/14988353/192704825-6cc455bc-dde5-45ba-b94d-b4e584e92e9e.png"> |

(via https://github.com/WordPress/wordpress-develop/pull/3352)

**Comment by ockham** [comment]
I've filed https://core.trac.wordpress.org/ticket/56736 to reflect this issue in Core.

**Comment by ockham** [comment]
I've filed a tentative fix over at https://github.com/WordPress/wordpress-develop/pull/3408.

**Comment by oandregal** [comment]
I cannot longer reproduce this bug with latest `trunk`.

**Comment by ockham** [comment]
> I cannot longer reproduce this bug with latest `trunk`.

Thank you for verifying @oandregal!

Closing, as this has now been fixed by https://github.com/WordPress/wordpress-develop/pull/3408.
