### ISSUE TITLE
How to parse_blocks in a widgetized area

### ISSUE THREAD

**Issue by xconsau** [WordPress/gutenberg#44616]
## Use case
I have created a block plugin (using ServerSideRender) which outputs inline styling and Google Fonts URL to be sent to the wp_head. Since there is no way of adding an action to the wp_head from within the render_callback function, I need to parse blocks on frontend using parse_blocks( $post->post_content ). And then I process style attributes and send them to the wp_head using add_action.

## The problem
The above method works fine as long as the block is inside the post content. But it doesn't work when the block is inside a widget area. I am unable to find any method using which I can parse blocks in a widget area.

## What is your proposed solution?
I am not sure if any such function or procedure exists. But if possible, I propose a function for getting all the content of widget areas which can be parsed using parse_blocks and contains all attributes which can be used further. 

Important: If add_action( 'wp_head', '...' ) can be made work inside a render_callback, the above feature may not be needed. I tried adding an action using the function closure like below:

<pre>
add_action( 'wp_head', function() use ( $attributes['some_name'] ) {
    - styles to be sent to the head -
});</pre>

This doesn't work due to the execution sequence or priority. So what I am looking for is either a way to parse blocks in a widget area, or ability to add action to head from within render_callback. A [similar unanswered post](https://wordpress.stackexchange.com/questions/398277/is-there-any-way-to-parse-blocks-inside-widget-area) is there on the WordPress StackExchange.

Any help or guidance will be very much appreciated.

**Comment by talldan** [comment]
I think it should be possible, hopefully using existing APIs, but I'm personally not very familiar with those APIs. 

Blocks are stored in widget areas as widgets. There's a specific type of widget for block-based content:
https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/widgets/class-wp-widget-block.php

The widgets block editor itself uses the REST API to fetch widgets and converts them to blocks using client side JavaScript.

If you're looking to achieve the same using PHP, I think you could do something as follows:
1. Get all widgets for the specific sidebar (possibly using a function like `wp_get_sidebars_widgets`. I'm not sure what kind of data this returns, the docs are light on details - https://developer.wordpress.org/reference/functions/wp_get_sidebars_widgets/)
2. Loop through that list, if the widget is of type 'block', parse its content using `parse_blocks`.
3. Check the block type of the first block returned by parsed blocks. If it's your particular block type you can handle adding styles to head.

Also cc'ing @noisysocks, who may have a better answer to this.

**Comment by xconsau** [comment]
Hello Daniel,

Thanks very much for the reply. I had previously tried <code>wp_get_sidebar_widgets</code>, but unfortunately it only returns block widget instance ID and the list of available widget areas. For example:

<pre>Array
(
    [wp_inactive_widgets] => Array
        (
            [0] => block-8
            [1] => block-4
            [2] => block-5
            [3] => block-6
        )

    [default-sidebar] => Array
        (
            [0] => block-3
            [1] => block-7
        )

    [sidebar-b] => Array
        (
        )

)</pre>

Maybe something can be achieved from `class-wp-widget-block.php`; either through the `widget_block_content` filter or by getting `$instance['content']` from a widget. But not sure how to get that outside of a widget. Looking forward to get some guidance from @noisysocks .

**Comment by talldan** [comment]
I'm sure it must be possible to get the widget's data from those Ids.

There are some functions that might help, but again I'm not sure what they return as the docs are not informative:
- `wp_render_widget` (https://developer.wordpress.org/reference/functions/wp_render_widget/)
- `$wp_widget_factory->get_widget_object` (https://developer.wordpress.org/reference/classes/wp_widget_factory/get_widget_object/), for this one you'll need to use `wp_parse_widget_id` to get the `id_base`.

I found these by looking at how the REST API pieces together the data it returns, there might be more inspiration there for you - https://github.com/WordPress/wordpress-develop/blob/389a78ecc453036f144b6d510cc2423f41bc9dd1/src/wp-includes/rest-api/endpoints/class-wp-rest-widgets-controller.php#L693-L721

The REST API also uses `wp_get_sidebar_widgets`, btw - https://github.com/WordPress/wordpress-develop/blob/389a78ecc453036f144b6d510cc2423f41bc9dd1/src/wp-includes/rest-api/endpoints/class-wp-rest-widgets-controller.php#L138-L163

**Comment by xconsau** [comment]
Thanks very much, Daniel. Those references were very helpful and it finally worked. The `global $wp_widget_factory` reference from the [WP_REST_Widgets_Controller](https://developer.wordpress.org/reference/classes/wp_rest_widgets_controller/prepare_item_for_response/) code was the one I was looking for. The final code which returns all the block data from available widget areas on frontend is the following:

<pre>// Get all available widgets in the widget areas
$widgets = wp_get_sidebars_widgets();

if ( isset( $widgets ) && is_array( $widgets ) ) {
    
    global $wp_widget_factory;
    
    $blocks_array = [];
    
    foreach( $widgets as $key => $value ) {
        
        // Skip for inactive widgets
        if ( $key == 'wp_inactive_widgets' ) {
            continue;
        }
        
        if ( isset( $value ) && is_array( $value ) && ! empty( $value ) ) {
            
            foreach( $value as $widget_id ) {
                
                $parsed_id = wp_parse_widget_id( $widget_id );
                $widget_object = $wp_widget_factory->get_widget_object( $parsed_id['id_base'] );

                if ( $widget_object && isset( $parsed_id['number'] ) ) {
                    $all_instances                   = $widget_object->get_settings();
                    $instance                        = $all_instances[ $parsed_id['number'] ];
                    $serialized_instance             = serialize( $instance );
                    $prepared['instance']['encoded'] = base64_encode( $serialized_instance );
                    $prepared['instance']['hash']    = wp_hash( $serialized_instance );

                    if ( ! empty( $widget_object->widget_options['show_instance_in_rest'] ) ) {
                        // Use new stdClass so that JSON result is {} and not [].
                        $prepared['instance']['raw'] = empty( $instance ) ? new stdClass : $instance;
                        $blocks_array[] = parse_blocks( $prepared['instance']['raw']['content'] );
                    }                                
                }
            } // inner foreach
        } // isset $value
    } //foreach
    
    // This is the complete blocks data with attributes and other settings
    print_r( $blocks_array );

} // all widgets</pre>

The `$blocks_array` will have all necessary data to be processed and applied further.

Thanks very much once again. You are the star. :)

**Comment by talldan** [comment]
Glad to be able to help!
