### ISSUE TITLE
Alignment is removed site-logo from header

### ISSUE THREAD

**Issue by andowt** [WordPress/gutenberg#44623]
### Description

Using twenty twenty two theme and adding a site-logo to the header alignment none or center work as expected (site logo is seen in header with black background)

When using left or right align the site logo is pushed out of the header (black background is gone)

Expected behaviour would be for the site logo to still be within the header (black background area) but positioned left or right

### Step-by-step reproduction instructions

1. Install twenty twenty two theme
2. Add site logo to header
3. Change alignment from center to left or right

### Screenshots, screen recording, code snippet

![alignment](https://user-images.githubusercontent.com/90341234/193342988-eebd9375-315c-4ed2-a710-50690001a1d2.gif)

### Environment info

Wordpress version 6.0.2
Issue happens with built in site editor or gutenberg plugin
Web browser Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hi @andowt  - I'd love to know if you still have this issue occuring in WordPress 6.2.2

**Comment by karmatosed** [comment]
Thank you for reporting this @andowt. Unfortunately, I am unable to replicate this myself. I am going to close this for now. However, if you are still experiencing this with the latest version of Gutenberg and WordPress, we can explore it with more information. Thank you again.
