### ISSUE TITLE
[WP 6.1] Navigation overlay menu does not open

### ISSUE THREAD

**Issue by mikachan** [WordPress/gutenberg#44638]
### Description

When Gutenberg is not active, the overlay menu does not open when you click the 'Open menu' button.

When Gutenberg is active, the overlay menu opens successfully.

This was mentioned in the TT3 repo here: https://github.com/WordPress/twentytwentythree/issues/214

### Step-by-step reproduction instructions

1. Activate a theme that uses the overlay menu (e.g. Twenty Twenty-Three)
2. Deactivate the Gutenberg plugin
3. View the front end at a small resolution
4. Attempt to open the overlay menu by clicking the 'Open menu' button

### Environment info

WordPress 6.1 Beta 2
Gutenberg not active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I have confirmed this.

**Comment by cbravobernal** [comment]
Changing the order of `viewScript` files loaded in array in the `blocks-json.php` files to `"viewScript": ["file:./view-modal.min.js" , "file:./view.min.js" ]` seems to do the trick. Otherwise, view-modal.js is not being loaded on the site.

@aristath worked on allowing multiple files on this field, could you please provide any feedback about why this could happen?

**Comment by aristath** [comment]
Where was this backported to Core? 👀 Maybe something was missed there?

**Comment by cbravobernal** [comment]
It seems that it was backported here: https://github.com/WordPress/wordpress-develop/pull/3108/
Edit: although we have an array with `navigation-view-js` and `navigation-view-js-2` on the settings part. We are not loading both scripts on the Site. Taking a look at it 👀 


![Screenshot 2022-10-03 at 15 58 39](https://user-images.githubusercontent.com/37012961/193596187-406cd90f-1fbc-4fb7-949f-353676a33820.jpg)

**Comment by aristath** [comment]
Patch on https://github.com/WordPress/wordpress-develop/pull/3395

**Comment by glendaviesnz** [comment]
Tested latest trunk from wordpress-develop and this is fixed by https://github.com/WordPress/wordpress-develop/pull/3395
