### ISSUE TITLE
wp-block-group__inner-container markup is missing on new default Group blocks

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#44636]
### Description

In https://github.com/WordPress/gutenberg/pull/42763 and https://github.com/WordPress/gutenberg/pull/44176, the "constrained" layout was set as the default for the Group block and the default variation used when inserting a Group block into content was updated.

I believe the reasoning for this was to preserve existing "default" Group blocks—these have an inner container injected on the front-end in classic themes for backward compatibility—while also changing some other defaults about the Group block itself. (It's late and I didn't really parse everything, but #42763 is a very nicely documented PR!). 😄 

This change doesn't immediately break backward compatibility in that existing groups remain as is and have the same markup on the front-end.

However, any new Group blocks inserted into content on an existing site have different markup and may now appear broken on the front-end, even though a person maintaining their site has used the same process for years.

If `<!-- wp:group {"layout":{"type":"constrained"}} -->` is the new "default" Group block, then it makes sense from a user experience perspective (IMO) to include it as [one of those in which an inner container is injected](https://github.com/WordPress/wordpress-develop/blob/97218bbfd336035edc9293274fea0f7bd3da85d7/src/wp-includes/block-supports/layout.php#L256) in classic themes.

### Step-by-step reproduction instructions

1. On WordPress 6.0.2, add a new page, add a group block, view the markup: see an inner container.
2. With Gutenberg 14.2 added, do the same: see no inner container.

### Environment info

- WordPress 6.0.2
- Gutenberg 14.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
cc @tellthemachines, @youknowriad
