### ISSUE TITLE
Content breaks after updating to 2.0.0

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4463]
## Issue Overview
After updating Gutenberg (to v2.0.0), I edited one of my pages to check if another issue had been fixed.

After clicking on a button block, I turned on the _Wrap text_ option in the sidebar. I then updated the page. After the page reloaded, I now have numerous blocks that no longer display properly and instead, show the error message _"This block appears to have been modified externally. Overwrite the external changes or Convert to Classic or Custom HTML to keep your changes."_ even though those blocks were never even touched.

![gutenberg-brokencontent](https://user-images.githubusercontent.com/2078245/34924807-c50c59c0-f9f9-11e7-904b-52c467f9cc14.png)

_Gutenberg 2.0.0
Firefox Quantum 57.0.4 (64-bit)
WordPress 4.9.1_

**Comment by karmatosed** [comment]
I am having trouble recreating this. Not saying it's not an issue because obviously it happened to you, however recreating isn't proving easy. Did you have any custom code in that block by any chance? Had you edited it?

**Comment by maddisondesigns** [comment]
Nope. There was no custom code anywhere on the page. Each block just had dummy text content.

Looking at the screenshot, all the blocks that had issues appear to be Text Column blocks.

**Comment by karmatosed** [comment]
Are you on mac or windows? I really would love to track down why you get this.

**Comment by maddisondesigns** [comment]
I'm on a Mac - macOS Sierra 10.12.1

**Comment by karmatosed** [comment]
I am still unable to recreate this. For now, I am going to close this. I would however encourage you if you still are experiencing this to report back and we can dive a little more into this. Closing an issue doesn't mean we can't reopen it.
