### ISSUE TITLE
WP6.1 Button block  Themes based on block-library css will have a different style

### ISSUE THREAD

**Issue by shimotmk** [WordPress/gutenberg#44659]
### Description

The theme based on block-library css changes the style of button block.

Perhaps this is due to the fact that the css has been removed by this pull request.
https://github.com/WordPress/gutenberg/pull/34180/

Is this something that has to be handled on the theme side?

### Step-by-step reproduction instructions

1. Theme will be [Twenty Ten](https://wordpress.org/themes/twentyten/).
2. Place the button block in WordPress 6.0.
3. Update to WordPress 6.1.
4. Look at the page you created in 2.

### WordPress6.0 Style
![6 0](https://user-images.githubusercontent.com/42362903/193713052-f7e57e9f-d00d-42ab-a118-8a5ae08ccc16.png)

### WordPress6.1 Style
![6 1](https://user-images.githubusercontent.com/42362903/193713070-54c2dc17-eb55-4f38-af9b-e8a2496588f8.png)

### Environment info

-  WordPress 6.1
-  Themes Twenty Ten

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Some of the styles then were restored in #41934.

**Comment by ockham** [comment]
I thought https://github.com/WordPress/wordpress-develop/pull/3331 had fixed this 🤔 

I just tried on `wordpress-develop` `trunk` and can't seem to repro:

![image](https://user-images.githubusercontent.com/96308/194044219-3cb16bd8-0b1e-46ed-972b-031ff24d340c.png)

@shimotmk Did you test this with [WP 6.1 Beta 3](https://wordpress.org/news/2022/10/wordpress-6-1-beta-3-now-available/) (or an earlier Beta, or `trunk`)? If you haven't tried with Beta 3, would you mind trying it there to see if the issue has been fixed?

cc/ @scruffian

**Comment by shimotmk** [comment]
@ockham
Thanks for the comment!
I can confirm that it's fixed on the front screen in beta3!

However, it doesn't seem to be fixed in the block editor.💦
![beta3](https://user-images.githubusercontent.com/42362903/194049018-6bbdfee0-c18b-4893-af67-c35d533e73eb.png)

The theme is Twenty Ten.

I think if you add the following code, the css will load on the edit screen.
`wp_add_inline_style( 'wp-edit-blocks', file_get_contents( gutenberg_url( 'build/block-library/classic.css' ) );`

**Comment by ockham** [comment]
I can repro this -- it's still present in the editor 😕 

@scruffian Could you look into fixing this? 🙏 😊

**Comment by scruffian** [comment]
I see that the CSS file is loaded, but the CSS itself isn't present. It's trying to be loaded from /wp-includes/css/dist/block-library/classic.css?ver=1, but there's nothing at that location. Is this connected to the package building process?

**Comment by ockham** [comment]
Hmm, I see that file both in my local build, and in https://wordpress.org/wordpress-6.1-beta3.zip, as well as in a Beta 3 test install 🤔

**Comment by scruffian** [comment]
I have an idea for a fix here: https://github.com/WordPress/gutenberg/pull/44731

**Comment by ockham** [comment]
Update: https://github.com/WordPress/gutenberg/pull/44731 was merged and included in [WP 6.1 RC1](https://wordpress.org/news/2022/10/wordpress-6-1-release-candidate-1-rc1-now-available/).

@shimotmk Could you check if [the issue](https://github.com/WordPress/gutenberg/issues/44659#issuecomment-1268305786) is fixed in RC1? 😊

**Comment by ockham** [comment]
I just tested this myself by newly inserting a Buttons block into a post created with current Core `trunk` (and a freshly reset database):

## Editor:

![image](https://user-images.githubusercontent.com/96308/195579873-d921536e-a363-4a7e-a8f2-ae66229af055.png)

❌ 

## Frontend:

![image](https://user-images.githubusercontent.com/96308/195579953-8b8399f5-9018-44c6-98fc-3604c7d1b50e.png)

✅ 

@scruffian Can you have another look what might cause the almost-invisible button label in the editor?

**Comment by ockham** [comment]
@scruffian pointed out to me that #44731 didn't make it into Core -- it's a PHP change, so it will need a manual backport 😅

**Comment by ockham** [comment]
> @scruffian pointed out to me that #44731 didn't make it into Core -- it's a PHP change, so it will need a manual backport 😅

https://github.com/WordPress/wordpress-develop/pull/3481

**Comment by ockham** [comment]
https://github.com/WordPress/wordpress-develop/pull/3481 has been committed, and will be included in WP 6.1 RC3.

Please test RC3 once it's released, so we can close this issue if it has been fixed 😊

**Comment by shimotmk** [comment]
@ockham
Sorry for the late reply.
I checked with WP6.1RC3 and it seems that the color is not hit when hovering the button.
I think you need to add the css that was removed in this pull request to classic-themes.css.
https://github.com/WordPress/gutenberg/pull/43553


![button](https://user-images.githubusercontent.com/42362903/197905868-d410dbd0-cede-4008-89c6-f3fcaff30b41.png)

Themes Twenty Ten

**Comment by cbravobernal** [comment]
Hi @shimotmk !

Now that 6.1 has been released, could you please check if the issue has been solved? 

Thanks!

**Comment by edent** [comment]
6.1 forces a "classic-themes" stylesheet which overrides the user's theme.  This is rather annoying.  Would it be possible to either revert this change, or make it so that it respects any theme set up by the user?

There's a brief discussion about how to reverse this change at https://wordpress.stackexchange.com/questions/410983/dequeue-classic-themes-min-css

**Comment by scruffian** [comment]
These rules were also present previous to 6.1, as they were in the button block. The aim of this CSS is to ensure that blocks that were relying on the default styles are still given the same defaults, but your theme should be able to override them in CSS still. What theme are you seeing a problem with?

**Comment by edent** [comment]
I built my own theme. Prior to 6.1 the "Subscribe" widget's button was controlled by my theme. This morning, after I upgraded, it had a different colour - set by classic-themes.

**Comment by shimotmk** [comment]
@c4rl0sbr4v0
I checked with 6.1 and some styles were not reflected.

Can you please check the pull request I made?
#45570

**Comment by glendaviesnz** [comment]
@scruffian It looks like this is still an issue with some themes unless the block content is resaved in the editor https://core.trac.wordpress.org/ticket/57126#comment:2

**Comment by shimotmk** [comment]
Yes, I have.
Some styles were added in this branch, but we forgot to add `&:hover,&:focus,&:active,&:visited` etc. https://github.com/WordPress/gutenberg/pull/44334

**Comment by scruffian** [comment]
I believe `&:hover,&:focus,&:active,&:visited` were removed in https://github.com/WordPress/gutenberg/pull/43553. @jasmussen do you think this is worth reconsidering?

**Comment by jasmussen** [comment]
It would be ideal if we didn't reintroduce that hardcoded white, the fewer such styles, the better. If need be, we could put it in `/wp-includes/css/classic-themes.min.css` perhaps? The tricky bit here is that the pseudo styles appear unable to inherit from their main element.

**Comment by scruffian** [comment]
Maybe the best thing is to ask themes that are experiencing issues to add their own styles for this, if not too many are impacted?

**Comment by chthonic-ds** [comment]
> I built my own theme. Prior to 6.1 the "Subscribe" widget's button was controlled by my theme. This morning, after I upgraded, it had a different colour - set by classic-themes.

Similar situation and outcome here: theme button styles have been overridden when upgrading a bunch of sites to WP 6.1.1. These are sites that use blocks but were created before theme.json was introduced.

> The aim of this CSS is to ensure that blocks that were relying on the default styles are still given the same defaults

The `classic-themes.min.css` stylesheet is overwriting theme styles in themes that have opted out of using core CSS.

**Comment by tmanolov** [comment]
> > I built my own theme. Prior to 6.1 the "Subscribe" widget's button was controlled by my theme. This morning, after I upgraded, it had a different colour - set by classic-themes.
> 
> Similar situation and outcome here: theme button styles have been overridden when upgrading a bunch of sites to WP 6.1.1. These are sites that use blocks but were created before theme.json was introduced. The `classic-themes.min.css` stylesheet is overwriting theme styles in themes that have opted out of using core CSS.

This was mentioned above, it works for me. 
https://wordpress.stackexchange.com/questions/410983/dequeue-classic-themes-min-css

**Comment by shimotmk** [comment]
Okay, if there is a rule that the core (Gutneberg) removes styles that the theme side adds, that is fine.

As far as I know, some themes have changed their look by not adapting this style, and some confusion was caused by the style being added by another file.

I think there should have been an announcement post or something in advance.

This issue is closed for now.
Please reopen again if you have any questions.
