### ISSUE TITLE
Zoomed out view: increase outline width/consider adding overlay from click through pattern

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#44654]
## What problem does this address?

Currently, when using list view with the zoomed out view, it's very difficult to see which container block is being selected. This is feedback from the [FSE Outreach Program's seventeenth call for testing](https://make.wordpress.org/test/2022/09/15/fse-program-testing-call-17-guiding-the-gutenberg-gallery/#comment-2730):

>When I edit the template in zoomed out mode and have selected a Group block or Header/Footer via the List View, the blue lines surrounding the selected group are very thin and almost not visible.

https://user-images.githubusercontent.com/26996883/193639416-69a888df-2367-4b77-9a43-bc81e03a7166.mov

## What is your proposed solution?

Either increase the outline border width or perhaps even use the overlay from the click through pattern that appear when you're using the zoomed out view:

<img width="755" alt="Screen Shot 2022-10-03 at 1 18 08 PM" src="https://user-images.githubusercontent.com/26996883/193639524-5e3f102b-aa63-4674-b296-3d268a400f53.png">

This would also create more alignment in general between the mode and using list view considering when you click a top level container block currently it does this and is reflected in list view:

https://user-images.githubusercontent.com/26996883/193640116-1ae9752a-abcb-4cce-a34c-19fd617fadef.mov

**Comment by jasmussen** [comment]
Great issue, thanks: the outlines are scaled down just like the canvas itself. Since the zoom view isn't going to be a place to move around anything but top level blocks, and everything will be in-editable, It seems like there's a fun design opportunity here to rethink the selected state beyond just changing the border and appearance. CC: @WordPress/gutenberg-design

**Comment by jameskoster** [comment]
A thicker stroke could be an easy one to try. I think it helps to suggest the higher level (root-level only) activity available in this view.

<img width="1232" alt="Screenshot 2022-10-10 at 12 53 29" src="https://user-images.githubusercontent.com/846565/194862637-041e38f1-43af-4443-97ab-d8406bc4a4cb.png">

**Comment by youknowriad** [comment]
Is this still relevant, I feel like this is pretty settled at the moment but maybe I'm wrong.

**Comment by annezazu** [comment]
I think it can be closed out.
