### ISSUE TITLE
Zoomed out view: make toolbar more visible against a dark background

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#44657]
This came up as feedback as part of the [seventeenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/09/15/fse-program-testing-call-17-guiding-the-gutenberg-gallery/#comment-2732):

>When I clicked on the header, the toolbar to move it up or down was in the border section, which was a dark background. The dark toolbar got kind of lost.

At an extreme, if your background is the same as the zoomed out view toolbar, it blends right in: 

<img width="655" alt="Screen Shot 2022-10-03 at 6 30 55 PM" src="https://user-images.githubusercontent.com/26996883/193697556-4d403605-7f2c-4475-a618-32f0250835f6.png">

I remember seeing designs for the toolbar options to be off to the side so this might make more sense to pursue to have better control over visibility or to add some sort of border, similar to the usual block toolbar, to make it stand out.

**Comment by youknowriad** [comment]
I think right now, we don't have any dark toolbar but this might become relevant again if we introduce again a new dark toolbar for write mode.
