### ISSUE TITLE
Block "More options" overflow menu sometimes gets hidden from view

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [WordPress/gutenberg#4467]
## Issue Overview

Version of gutenberg : 2.0.0

The more options overflow menu sometimes gets hidden from view, and there is no way to access the menu options hidden from view. In the screenshots below, you can see two blocks one below the other. The first block shows the menu options top-down, and the last couple of options get hidden from view. 
![screen shot 2018-01-15 at 2 34 51 pm](https://user-images.githubusercontent.com/1269602/34934965-4527439c-fa02-11e7-8039-fe1ea75d20da.png)

The second block shows the menu options bottom-up, and the first few menu options are hidden from view.

![screen shot 2018-01-15 at 2 33 20 pm](https://user-images.githubusercontent.com/1269602/34934863-f58b2ed4-fa01-11e7-9db5-cc170d12b155.png)

## Steps to Reproduce (for bugs)

1. Add any two blocks
2. Click the More options overflow menu

Browser : Chrome version (63.0.3239.84)
System : macbook pro (non-retina) macOS High Sierra

## Expected Behavior
1. The options should not get hidden from view
2. We should be able to scroll through the options using up/down arrows on the keyboard. Presently, this isn't possible. Scrolling through the options should automatically show the hidden menu options.

**Comment by niranjan-uma-shankar** [comment]
Update : 
I face the same issue in Firefox (version 57.0.4), Opera (version 49.0) and in Safari (version 11.0.1)

**Comment by niranjan-uma-shankar** [comment]
I suggest fixing a max-height for the block settings popover menu. The menu can show a scroll bar to navigate to the overflow options. Representation of the recommendations below : 

Block settings menu with a max-height value set will look something like this : 

![screen shot 2018-02-02 at 1 23 49 am](https://user-images.githubusercontent.com/1269602/35700198-4b81476a-07b8-11e8-84c6-adcbfca263a2.png)

Inside the menu, a scroll bar to navigate to the other options : 

![scroll](https://user-images.githubusercontent.com/1269602/35700255-79d50bce-07b8-11e8-9d80-34cda681a541.png)

**Comment by austinginder** [comment]
I have run into this issues a few times using the latest Gutenberg 2.4.0. I seem to stumble on it more often went on lower resolution displays (like when using a projector) or smaller height browsers. To simulate simply reduce the browser height and attempt to select a more block near the top of the screen. See here for screencast walkthrough: [https://vimeo.com/261165826/5ec41fc897](https://vimeo.com/261165826/5ec41fc897)

**Comment by youknowriad** [comment]
This is not the case anymore, this has been fixed by the popover refactoring.
