### ISSUE TITLE
Author block settings only shows 10 authors.

### ISSUE THREAD

**Issue by MastaBaba** [WordPress/gutenberg#44688]
### Description

The Author block settings let's me select from a list of only 10 authors. Two sites on which I've reproduced this have a few hundred authors, making this a problem if I want to change the displayed author.

### Step-by-step reproduction instructions

1. Create a post.
2. Insert an author block.
3. Check the Block settings.
4. See that only 10 authors are available in the dropdown.

### Environment info

Wordpress 6.02. All browsers, all OSs.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by noisysocks** [comment]
Hey @Mamaduka can't see that you're working on this so unassigned you. Re-assign yourself if I'm mistaken!

**Comment by danielbachhuber** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/45640
