### ISSUE TITLE
Margin visualizer incorrectly shows inwards

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#44693]
Extracting from https://github.com/WordPress/gutenberg/pull/44484#issuecomment-1266552422: there appears to be an issue with the margin visualization, where if you apply margin to, for example, a group block, the visualization resizes inwards as if to indicate padding, instead of outwards. GIF showing this:

![bug](https://user-images.githubusercontent.com/1204802/193766437-72b856c9-ddc3-4ea4-befe-c4198aa1033d.gif)

In an older iteration, this worked as intended:

![before](https://user-images.githubusercontent.com/1204802/193766336-0c7594d3-69aa-407c-8364-f01ac9f36576.gif)

It isn't clear when this regression happened. I've seen it work prior to #44323, but it isn't clear that PR introduce the regression either, please see [additional context here](https://github.com/WordPress/gutenberg/pull/44484#issuecomment-1267964759).

**Comment by talldan** [comment]
It is a bug in 6.1 so I've added it to the project board. It's most noticeable for me when adjusting the margin on the group within TT3's header.

**Comment by glendaviesnz** [comment]
This seems to be related to the `clamp` values that TT3 is using for spacing sizes, eg. `clamp(7rem, 14vw, 11rem)`. If I replace these with simple `rem` values the margin visualiser works as expected. I will take a closer look and see if there is anyway of getting the clamp values into the format that the visualiser can cope with.
