### ISSUE TITLE
Sibling inserter displays at the wrong time

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#44694]
I've been meaning to report this for a while. Under some conditions — relatively easy to reproduce — the sibling inserter can be triggered by hovering over other elements, such as a template part, instead of the actual in-between blocks area in the site editor.

https://user-images.githubusercontent.com/548849/194011952-0a958b22-7a53-4643-881b-29859e03af51.mov

**Comment by jasmussen** [comment]
CC: @ramonjd, I think I recall you making a wonderful improvement to the sibling inserter a while back. Do you have any insights?

**Comment by ramonjd** [comment]
Now you're testing my memory. 

I think you mean this PR from November 2021:

- https://github.com/WordPress/gutenberg/pull/36798

Is the bug that old? I wonder if something has changed in the meantime. cc @youknowriad just in case the recently-merged https://github.com/WordPress/gutenberg/pull/44325 is related.

**Comment by jasmussen** [comment]
That was the improvement I was thinking of, yes! As I recall, it greatly improved the inserter to appear more when you needed it, and it feels like it's regressed a bit. Thanks for the context.
