### ISSUE TITLE
"Block unavailable" message when reusable blocks is selected

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [WordPress/gutenberg#4469]
## Issue Overview
Gutenberg version : 2.0.0

I converted a few blocks to Reusable blocks, and later deleted all of them. In "Recent" block options, I now see an options called "Reusable block" as seen below : 

![screen shot 2018-01-15 at 3 54 40 pm](https://user-images.githubusercontent.com/1269602/34937932-834eaa5c-fa0c-11e7-8561-1f21f9880819.png)

However, clicking doesn't do anything useful. I get the following message : 

![screen shot 2018-01-15 at 3 42 18 pm](https://user-images.githubusercontent.com/1269602/34937809-1c18ead2-fa0c-11e7-82c1-cdf66f6018d9.png)

Next, I created a new reusable block : 

![screen shot 2018-01-15 at 3 42 55 pm](https://user-images.githubusercontent.com/1269602/34937835-369eb1ac-fa0c-11e7-8698-98ae90f5aac8.png)

However, I still get the "Block has been deleted or is unavailable" message if I click the reusable block option. Why am I getting this block unavailable message, and how do I make it not show up again.

**Comment by Soean** [comment]
Thanks for your report, we already have a ticket for this issue: #3793
