### ISSUE TITLE
Confirmation panel still shown in new edits after publishing

### ISSUE THREAD

**Issue by wsydney76** [WordPress/gutenberg#4470]
## Issue Overview

After publishing a post and opening a new one, the confirmation panel on the right is still shown in some cases.

## Steps to Reproduce (for bugs)

1. Publish a post, confirm
![image](https://user-images.githubusercontent.com/25308802/34940262-21506c40-f9ef-11e7-9d4b-9e3511bde575.png)

2. Do not close the panel.
3. Click "Add new Post"
4. The panel is still shown
![image](https://user-images.githubusercontent.com/25308802/34940353-8875c370-f9ef-11e7-8cee-8060a222fe2c.png)

Newest Chrome

**Comment by jorgefilipecosta** [comment]
Hi @wsydney76 thank you for reporting this bug. I'm not being able to reproduce. The publish panel and its state suffered lots of changes and probably during this changes the problem was fixed. If the problem persists feel free to reopen the issue and I will look further.
