### ISSUE TITLE
Nav > mobile > blured svg default icons

### ISSUE THREAD

**Issue by Marc-pi** [WordPress/gutenberg#44706]
### Description

Actually, we cannot set from the block settings the navigation icon size (see https://github.com/WordPress/gutenberg/issues/37930). The default icon size is 24x24px (see source, the svg is inlined).

> If we enlarge it with css to 50x50px, it is blured. 

Seems to be a png file converted to svg. the same for the other icon (burger with 2 or 3 lines = same)
Maybe the design team can generate a cristal clear code to replace the 2 actual default icons
**for WP6.1 final !**

### Step-by-step reproduction instructions

Just set your nav and active the burger icon for mobile. 
change the default css, for instance to 50px
![image](https://user-images.githubusercontent.com/919332/194050196-40a06b9c-1c4b-46bd-a13b-3a53c8e8f153.png)

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/919332/194049503-b699fb74-f72c-458d-aab4-4d99cc19ac3f.png)

### Environment info

WP6.0.2 with Gutenberg plugin 14.2.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Hey, thanks for the issue. Can you try and make the icon 48x48? That would be a 2x integer scale from the 24x24px base icon, and should remove any blur you see.

**Comment by Marc-pi** [comment]
hum, first time i notice this with svg (using interger multiple is needed) , works better, thanks for your help
i close

**Comment by jasmussen** [comment]
Glad that worked!
