### ISSUE TITLE
Double clicking on a pattern in zoomed out view should go into focus mode

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#44710]
On the zoomed out view, double clicking on a pattern should probably get you into the focused template part mode to edit.

**Comment by draganescu** [comment]
@richtabor @jeryj any ideas on how this can work with the keyboard? Should we have a focus button in the new toolbar (the one that will exist vertically in zoom out)?

**Comment by jeryj** [comment]
> Should we have a focus button

I'd think either an edit button or make the current pattern a tabstop on the page an aria-labelled edit pattern button. Or both. In general, the UX is better when there's a visible and labelled button, so  a dedicated edit button on the toolbar will likely make it easier for everyone to understand.

**Comment by richtabor** [comment]
It'll be a delicate balance navigating in and out of zoom out, without focus mode in there as well. I think as we explore interactions to flow between those views, we may find ways to go "deeper" another level, focusing on a specific pattern. But I'd consider that a secondary effort. 

That saying, if we can select template parts in zoom out, we can just use the existing "Edit" button, we already have (for template parts):


![CleanShot 2024-04-12 at 16 34 07](https://github.com/WordPress/gutenberg/assets/1813435/c999f8d2-8fc9-4ffc-8b79-9292c8f70c2a)

**Comment by draganescu** [comment]
> we can just use the existing "Edit" button, we already have (for template parts):

Will this button be in the incoming vertical toolbar to be tried (as the original assembler mockup shows)?

**Comment by draganescu** [comment]
@richtabor this will only work for partially / synced patterns as the others don't have their id saved so there is nothing to focus? Would having this in - out UX available for parts of the layout and not for others be nice?

**Comment by mtias** [comment]
I think we don't want to do this anymore, and instead double clicking zooms back in. I think it might still be good to provide a way to edit in focus mode, but it might be in addition to zooming in.
