### ISSUE TITLE
Navigation block in FSE: Adding a Font Awesome icon will affect menu item's styling

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#44725]
### Description

I have this tutorial:
https://easywebdesigntutorials.com/adding-icons-to-your-menus/#site-editor

Where I explain how to use Font Awesome by adding an icon to FSE - Twenty Twenty Two.
As the icon is added it affects the menu item it is next to.

### Step-by-step reproduction instructions

Follow the tutorial for adding a Font Awesome icon.
https://easywebdesigntutorials.com/adding-icons-to-your-menus/#site-editor

The result looked like the below screenshot. As it seems the menu item picked up the font awesome icon styling.

### Screenshots, screen recording, code snippet

![Full-Site-Editing-Navigation-block-WordPress-adding-Font-Awesome-Icon-Frontend](https://user-images.githubusercontent.com/5323259/194248239-a59d4ed1-6da1-4d1e-9915-60262419b0b5.jpeg)

### Environment info

WordPress 6.0.2
It might have been Gutenberg plugin version 14.0...(not sure)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by mtias** [comment]
This is a problem with what classes you are using, unrelated to the editor. You seem to be adding a `.fa-brands` class which does this `.fa-brands,.fab{font-family:"Font Awesome 6 Brands"}`, that will force your font family selection on the entire element, not on the `::before` or `::after` pseudo elements.
