### ISSUE TITLE
Navigation block: Adding submenu to black header adds white text with white background.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#44726]
### Description

I noticed that when adding a Navigation block in Twenty Twenty Two FSE theme and then adding a sub menu will show white text in a white box when there is a black header background.

### Step-by-step reproduction instructions

1. Activate Twenty Twenty Two.
2. Go to the Site Editor.
3. Be sure to use a black header.
4. Add a sub menu to the Block Navigation.
5. Notice the text can not be seen.

### Screenshots, screen recording, code snippet

Result of adding a sub menu when a black header is present.
I highlighted the hidden white text.

![Screenshot 2022-10-06 at 09 59 29](https://user-images.githubusercontent.com/5323259/194255235-556420b2-fe8d-4283-8939-15bdae733f85.jpg)

Here is a white header background.
![Screenshot 2022-10-06 at 10 02 12](https://user-images.githubusercontent.com/5323259/194255573-b498814f-3b42-461a-8509-fd48b7e40e79.jpg)

### Environment info

WordPress 6.0.2
Gutenberg plugin 14.2.0
Brave browser

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi, this was fixed in [44678](https://github.com/WordPress/gutenberg/pull/44578) and will be in the next plugin release

**Comment by paaljoachim** [comment]
Great! Thank you Carolina!
Closing this issue.
