### ISSUE TITLE
How to deal with functionality like in "Secondary Title" plugin

### ISSUE THREAD

**Issue by wsydney76** [WordPress/gutenberg#4472]
## Issue Overview

Making intense use of the secondary title plugin, we are wondering how that kind of functionality will be supported in Gutenberg.

![image](https://user-images.githubusercontent.com/25308802/34941809-960aea8c-f9f5-11e7-8acb-ee9b83d341a9.png)

Is this in scope of the backwards compatibility efforts in Gutenberg, as it is obviously not a meta box?

How can this be implemented in Gutenberg?

PS.
I get that there is a workaround by creating a block mapped to a custom field, but that would require user action to add it, and would appear in the wrong place.

**Comment by danielbachhuber** [comment]
Related #4151 

> Is this in scope of the backwards compatibility efforts in Gutenberg, as it is obviously not a meta box?

Not sure, to be honest. I'd _think_ it'd be out of scope but I also don't know that it's impossible to provide compatibility for.

> How can this be implemented in Gutenberg?

Conceptually, it seems like it should be able to map a block to a fixed location in Gutenberg.

**Comment by mellis32** [comment]
This and other custom fields are my main gripe with gutenberg. I wish this can be addressed so we don't loose native UI support for all of these custom field plugins.

**Comment by benhuson** [comment]
@danielbachhuber Also note that defined a fixed, required block using a template for a post type at the moment will not automatically add that block placeholder to existing posts. See #4476

**Comment by designsimply** [comment]
Noting the link for the plugin mentioned for reference: https://wordpress.org/plugins/secondary-title/

Now that Gutenberg has a subheading block and https://github.com/WordPress/gutenberg/issues/4476 has been fixed, do you still need answers here? If yes, could we work together to make the plugin title more actionable and relevant and could you describe in a bit more detail inside this issue about what functionality you're requesting? Once we have more detail, we can reopen the issue.

**Comment by wsydney76** [comment]
@designsimply Thanks, personally i am fine with closing this issue, as i am no longer involved in Wordpress and Gutenberg.  So just a few thoughts:

- the subheading block is part of the content and describes itself as 'Smaller than a headline, bigger than basic text.' That's fine, but not what we want here.
- whereas a secondary title is not part of the content but attached to the title itself.
- it appears above/below/beneath the title not only in the post's full view, but also in archives and widgets like 'recent posts', and in custom templates like a magazine's home page.
- so from a plugin authors point of view, there is a need to add something (a text control) above or below the title. (The same spot as on the front end for good UX).
- and the need to grab the value in a simple way (meta attribute?) without parsing the whole content for a subhead block.

As i am not at all up-to-date with Gutenberg's extensibility right now, this may allready be possible.
