### ISSUE TITLE
Post Editor: Preview button was removed by a Site Editor change

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#44738]
### Description

In #42331 the site editor was improved by changing the preview button to a view button. However this change wasn't just applied to the site editor, it was applied to _all_ editors. I can understand why the change was made for the site editor, but it's a major regression for the post editor and other block interfaces.

This on its own will create tens of thousands of hours of support requests and problems.

It also heavily implies that you can no longer preview your changes, and that changes are applied immediately rather than on update.

### Step-by-step reproduction instructions

 - Open a draft post
 - Make changes
 - Attempt to preview the changes
 - Notice that there is no preview button

_( unless you are told that the view button can be used to preview the changes, how would you know? )_

### Screenshots, screen recording, code snippet

<img width="1350" alt="Screenshot 2022-10-06 at 13 47 38" src="https://user-images.githubusercontent.com/58855/194316986-9ab43bae-59fc-4132-adb4-52a71b0f012e.png">

### Environment info

 - WordPress 6.0
 - Gutenberg 14.2.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by dream-encode** [comment]
This one looks like it needs a fix before 6.1 RC.

CC @ndiego @ockham @c4rl0sbr4v0 @annezazu

**Comment by annezazu** [comment]
cc @jameskoster / @jasmussen / @richtabor for a design point of view. I can see an argument that this creates consistency across the editors and I can see an argument for having nuance in each. In the original PR that implemented this, it seems like there wasn't necessarily certainty there either https://github.com/WordPress/gutenberg/pull/42331#issuecomment-1181536147 

For now, adding to the 6.1 board for consideration.

**Comment by jasmussen** [comment]
Personal opinion: I like keeping it "View". The canvas itself is already a preview, and the View toggle offers query based sizes, and an option to view in a new tab.

**Comment by bobbingwide** [comment]
My personal opinion. I don't use Preview. I much prefer to Update and View Post. WIBNI if the View menu actually included the option to actually view the post.

**Comment by tomjn** [comment]
> Personal opinion: I like keeping it "View". The canvas itself is already a preview, and the View toggle offers query based sizes, and an option to view in a new tab.

This is only true on well built block themes which make up a tiny slither of the current install base. The idea that the canvas is itself the preview is inaccurate on the majority of sites, as well as many of your own companies main offerings such as WooCommerce. Most custom and 3rd party blocks don't follow the WYSIWYG rule either. E.g. how would you preview an ACF interface.

It's also not possible to preview the canvas at breakpoints other than the 3 predefined desktop/tablet/mobile, as well as testing that the post behaves correctly with 3rd party scripts and assets that aren't loaded in the editor. For these preview is required, and removing the wording removes the feature for most users.

This **will** cause a large amount of support/customer/client confusion, removing the word "preview" is a regression.

**Comment by tomjn** [comment]
Also the site editor doesn't behave the same way that the post editor behaves, in the site editor viewing the site doesn't trigger the preview functionality, it actually views the site. That's not the case for posts.

A user may make changes, click view expecting to see the unmodified site, see their changes, and think that their changes were saved and applied, only to be confused when they later visit and their changes are missing.

Users who don't use the preview feature can continue to not use the preview feature, but I can see the value of the preview button changing to a view button if the current document has no changes

E.g.

```
if post is saving
    disable button
else
  if post is dirty
      display preview
  else
      display view
```

**Comment by getsource** [comment]
> A user may make changes, click view expecting to see the unmodified site, see their changes, and think that their changes were saved and applied, only to be confused when they later visit and their changes are missing.

Just thought I'd leave a note that I agree that it's confusing to change it globally to "View".

I like the solution suggested by @tomjn re: different state depending on the post's status.

**Comment by dlh01** [comment]
Please also note that there's already a link labeled "View" in the post editor, in the admin bar, which does something different than the button: It goes to the published post on the frontend.

<img width="1385" alt="Screen Shot 2022-10-13 at 2 04 30 PM" src="https://user-images.githubusercontent.com/697432/195673347-a9d8cfe2-1824-484f-b7e4-e561015c54fd.png">

With this change, there are arguably two "View" links that do different things.

I'm sympathetic to the reasons for labeling the button "View" everywhere, but I hope that what @tomjn says takes precedence. This is going to be a disruption for many users and the teams that support them. If it's going to happen, then, IMO, it deserves to happen deliberately and to get attention in a dev note and the field guide. It's too significant to happen as a side effect of a change to the site editor, which is a feature that a small number of users will ever see relative to the number of users with the ability to publish content.

**Comment by annezazu** [comment]
For context, this was initially done in the Site Editor (view) and ported over to the Post Editor. While I think it's good to have consistency, I can also understand where keeping preview makes sense, especially while previewing isn't possible: https://github.com/WordPress/gutenberg/issues/28208 Since the functionality does exist in the Post Editor, it seems wise to have separation there and keep "preview" for now. In the future when there's more shared functionality, I could see having consistency between the two, especially when content is available in the site editor https://github.com/WordPress/gutenberg/issues/44461

**Comment by annezazu** [comment]
Update for folks here. Thanks to everyone who chimed in, offered feedback, and shared context around this initial implementation. Based on what's been shared, a PR was completed to add back in the "Preview" button to the post editor: https://github.com/WordPress/gutenberg/pull/45074 I'm working to ensure it's backported for 6.1 and am going to close this issue out for now!
