### ISSUE TITLE
Templates: Prevent users from messing up styling

### ISSUE THREAD

**Issue by wsydney76** [WordPress/gutenberg#4474]
Evaluating using Gutenberg for a future project, a few issues came up that made the current implementation of templates useless for the client. 

Although the client already dropped WordPress, I will open a few issues to document the minimal requirements. 

Although users may not add blocks, they can still change all the attributes (Colors, font sizes, alignments), messing up the layout.

There should be an option to restrict users to edit the pure content (Text, Image)

**Comment by youknowriad** [comment]
I guess you can try to extend the existing blocks and remove these options. Or you can decide to unregister the default blocks and provide your own "controlled" blocks.

**Comment by mtias** [comment]
This is possible in a general sense already between `add_theme_support`, locking mechanisms, etc. If there are other specific let's write them on new issues.
