### ISSUE TITLE
enjoycart

### ISSUE THREAD

**Issue by 1j0ysweet** [WordPress/gutenberg#44756]
## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- WordPress app version:

**Comment by skorasaurus** [comment]
Hi,

There is not enough information to act on this.
Please add additional context by each of the prompts and reopen the issue.
