### ISSUE TITLE
Possible confusion in menu's with the "More" block.

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#44751]
Reported on Slack by Jaap Wiering

If you work in the block editor and have added the block "More", and then want to change things with the 3 dots menu, you get some confusing phrases. "Hide more settings" and "Remove More" are already confusing in English. But if you translate this string in for example Dutch you lose track (especially with new people). Could we use - instead of "More" - the term "More block", "Read more block" or something less confusing here?

![image](https://user-images.githubusercontent.com/4569581/194340490-841233b8-54cd-4f56-bc9f-b23b52625bda.png)

**Comment by jasmussen** [comment]
Good issue. Some quick thoughts:

* Do we actually need the "Hide more settings" button at all? It used to exist in order for keyboard users to navigate from the block to the inspector. But since you can just press Tab now, it seems like we can remove that menu item entirely?
* Can we rephase the "Remove More" to just be "Remove"?

**Comment by NekoJonez** [comment]
> Good issue. Some quick thoughts:
> 
> * Do we actually need the "Hide more settings" button at all? It used to exist in order for keyboard users to navigate from the block to the inspector. But since you can just press Tab now, it seems like we can remove that menu item entirely?
> * Can we rephase the "Remove More" to just be "Remove"?

For the first, it all depends on how clear the UI will be then. Also, does that mean we barely can use tab in the editor? Maybe I am reading it too extreme.

For the second, its a double edged sword. Since the fact the block name is there, is good for the user so they are sure they selected the right block. I'd make the string "Remove this %s block" where %s is the block name. Thats my two cents.

**Comment by NekoJonez** [comment]
Also, here is some food for thought.

I think this whole issue can be sidestepped if we ask the question... Whats the biggest reason for a more block? What else does it do compared to a read more block?

Does it make a page be divided in more pages? Like a next button in a tutorial?

Another possible answer is renaming the block if possible. 

Maybe we should focus on that, since the alternative might involve remaking those dropdown menu's which might cause a whole slew of inconsistencies.

**Comment by jasmussen** [comment]
> For the first, it all depends on how clear the UI will be then. Also, does that mean we barely can use tab in the editor? Maybe I am reading it too extreme.

I'm not suggesting any changes to how tabbing works: try pressing tab in a selected block, it takes you to the inspector.

Previously, this did not work, and the "Show more options" menu item was meant to move focus there. This doesn't work anymore either. Which means the option itself is just an extra toggle for the inspector:

![tab](https://user-images.githubusercontent.com/1204802/194815817-814348b1-8b81-4984-8eaf-f0c6873fcbab.gif)

I'm not sure how useful that is, that's all I'm suggesting.

**Comment by jordesign** [comment]
The new design/options in that dropdown no longer have the same options (or word them differently) so it looks as thought his isn't an issue any longer.

<img width="577" alt="Screenshot 2023-08-02 at 10 19 18 am" src="https://github.com/WordPress/gutenberg/assets/1842363/5788d3d3-2b97-4ab3-a343-c41e3360c468">

I'll close this issue - but please re-open if needed.
