### ISSUE TITLE
Templates: Check required values

### ISSUE THREAD

**Issue by wsydney76** [WordPress/gutenberg#4475]
In the current implementation of templates, it is possible to save the post without filling out any content.

It should be possible to declare values as mandatory, and check this before saving.

**Comment by youknowriad** [comment]
That's the responsibility of the block IMO. Current CPTs can be created with empty meta and post_content. Gutenberg doesn't change that.

**Comment by wsydney76** [comment]
@youknowriad When building your CPTs with ACF, Pods or alike, this can be done, and thats the behavior the user expects.

> That's the responsibility of the block IMO
How can that be done? Is there a javascript callback called before saving or something like that?

**Comment by aduth** [comment]
Noting that to me, this is a problem which could be extrapolated to "post is valid" logic generally, to which a template conformance could be a condition.

See also: #7020

**Comment by youknowriad** [comment]
With the lock/unlockPostSaving actions this can be performed. The missing aspect is to trigger validation right before saving. This is tracked here #13413
