### ISSUE TITLE
Choose a block menu showing over the modal

### ISSUE THREAD

**Issue by imanish003** [WordPress/gutenberg#44767]
### Description

As you can see in the screenshot below, choose block menu appears over the Patterns modal.
![image](https://user-images.githubusercontent.com/16707866/194487925-513a9666-00bd-40c0-a96c-35a6c46d92bb.png)

#### Expected behavior
The choose a block menu should be behind the modal, in this case, the patterns modal.

### Step-by-step reproduction instructions

1. Edit any post & type `/woo`, and the following menu will appear:
![image](https://user-images.githubusercontent.com/16707866/194487458-20bd710a-0a4f-4d78-80d3-bde34ceb2c43.png)

2. Click on the plus button available in the top left corner
![image](https://user-images.githubusercontent.com/16707866/194487499-836e063f-02a9-4761-bc34-d7643aa42d79.png)

3. Go to the patterns tab and click on Explore button while choose a block menu is still open.
![image](https://user-images.githubusercontent.com/16707866/194487583-8a81664c-db2c-45f3-938b-7eac8bd892cf.png)
and you will see the issue
![image](https://user-images.githubusercontent.com/16707866/194487737-6f5f1c77-6e89-47a9-812a-0068001f6952.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by BE-Webdesign** [comment]
Can replicate, unfortunately this probably can't be fixed with just some CSS as it seems on purpose that `components-popover` has a higher z-index than `components-modal__screen-overlay`. I will make a PR that fixes this with a click outside for the popover.

```
// Show modal under the wp-admin menus and the popover
".components-modal__screen-overlay": 100000,

// Show popovers above wp-admin menus and submenus and sidebar:
// #adminmenuwrap { z-index: 9990 }
".components-popover": 1000000,
```
