### ISSUE TITLE
Templates: Behaviour when adding blocks to an existing template

### ISSUE THREAD

**Issue by wsydney76** [WordPress/gutenberg#4476]
Scenario: Create a locked template (like books in the documention), and add a few posts.

Later it will be necessary to add some fields, like a book number.

When adding this to the template, it will be shown for new posts, but it is impossible to add this information to existing posts.

When editing existing posts, the existing structure should be compared to the current template, new blocks should be added.

(No idea how to handle conflicts)

**Comment by benhuson** [comment]
I have also discovered this issue in my testing.

**Comment by benhuson** [comment]
Surely this is a pretty big blocker in terms of transitioning functionality an existing sites to Gutenberg?

Imagine you have an established site with a custom post type with comprehensive meta data such as a property site and you want to try to transition some of the meta data to be managed Gutenberg blocks, probably as required and useOnce blocks.

Defining a Gutenberg template will not automatically add any required blocks to existing posts so you won't be able to edit the new block meta?
