### ISSUE TITLE
Templates: Allow adding free content

### ISSUE THREAD

**Issue by wsydney76** [WordPress/gutenberg#4477]
Requirement here: Create a template for fixed content at the top of the post (eg. a journey: destination, time of travel, costs, visa requirements), and then allow user to add a description using the full power of the editor, adding blocks (images, galleries etc) as wanted.

So there should be a lock option that disallows the user to change the block structure of the template part, but also allows him to add any blocks below (or at a specified position?).

Also there should be an option to wrap the template part in some html to apply some specific styling, like html_before_template: '<div class="xxx"'>, html_after_template: '</div>'

**Comment by mtias** [comment]
This will be possible with nesting. You can already lock a template down with `'template_lock' => 'all'`. You'd then define a nested area below your other blocks where the user can add content.

**Comment by benhuson** [comment]
@mtias Are there any code examples of nesting at the moment or is it work in progress?

**Comment by mtias** [comment]
@benhuson nesting is already implemented at the foundational level — parser and state tree —, but not consumed by the UI or any block at the moment.

See https://github.com/WordPress/gutenberg/pull/3745 for the final work in progress.

**Comment by noisysocks** [comment]
This should be possible now with a combination of `InnerBlocks` and `template_lock`.

```php
function myplugin_init() {
	register_post_type( 'test', array(
		'label' => 'Test',
		'public' => true,
		'show_in_rest' => true,
		'template' => array(
			array( 'test/content', array() ),
		),
		'template_lock' => 'all',
	) );
}
add_action( 'init', 'myplugin_init' );
```

```js
( function() {
	var registerBlockType = wp.blocks.registerBlockType;
	var InnerBlocks = wp.blocks.InnerBlocks;
	var el = wp.element.createElement;

	registerBlockType( 'test/content', {
		title: 'Content',
		icon: 'carrot',
		category: 'common',

		edit: function() {
			return el( 'div', null,
				el( 'div', null,
					el( 'p', null, 'Fixed HTML content')
				),
				el( InnerBlocks )
			);
		},

		save: function() {
			return el( 'div', null,
				el( 'div', null,
					el( 'p', null, 'Fixed HTML content')
				),
				el( InnerBlocks.Content )
			);
		},
	} );
} )();
```
