### ISSUE TITLE
Performance regression in WP 6.1 for `theme.json` processing

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#44772]
### Description

I'm currently trying to improve performance in WP-Core, and the thing that currently stands out as a bottleneck is the `WP_Theme_JSON::remove_keys_not_in_schema` method.
Posting a screenshot of a webgrind analysis below:

<img width="1045" alt="Screenshot 2022-10-07 at 11 15 06 AM" src="https://user-images.githubusercontent.com/588688/194519105-cb105115-63ee-4c47-a1a9-e61c5a0a9c01.png">

`WP_Theme_JSON::remove_keys_not_in_schema` runs 38228 times, and consumes 14.36% of resources/server-time.

### Step-by-step reproduction instructions

I'll just post instructions on how I setup `webgrind` on my localhost using wp-env, so hopefully others can also test and debug performance issues:
1. I use the https://github.com/WordPress/wordpress-develop repo, but I think the same would apply for this one. Edit the `.env` file. Set `LOCAL_PHP_XDEBUG=true`, and `LOCAL_PHP_XDEBUG_MODE=develop,debug,profile`.
2. Download or clone https://github.com/jokkedk/webgrind locally. I do it in `wp-content/plugins/webgrind` but all that matters is you put it somewhere you can access it from a URL.
3. start wp-env normally. Xdebug will now be available and profiling will run. Which also means that page-loads will be significantly slower due to all the profiling happening in the background.
4. Visit your site, login, then refresh the frontend a few times. Doing multiple runs will allow you to get some more stats and you can ensure that the stats you see later are not a fluke but consistent between all your page-loads.
5. Visit the URL where you copied webgrind, and examine the results. In my case that's on `http://localhost:8889/wp-content/plugins/webgrind/` but it will vary depending on where you copied the files etc.

### Environment info

* WordPress trunk
* No plugins activated
* Happens with and without the Gutenberg plugin active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aristath** [comment]
I'm trying to understand why `remove_keys_not_in_schema` is necessary... 🤔 
I understand that it cleans up the parsed JSON, but is there any actual problem if the JSON has some extra things in it? 
Do extra/unused items in the json cause any problems? Or do we just use that function because we want to keep things tightly controlled & limited?

cc @getdave, if I'm not mistaken that was added in the `sanitize()` method in https://github.com/WordPress/gutenberg/pull/41786 ?

**Comment by oandregal** [comment]
We merged two recent PRs in `wordpress-develop` that made the caching only be available for _reading the JSON file_ from the file system, and removed the other processing we did before. 

- https://github.com/WordPress/wordpress-develop/pull/3408
- https://github.com/WordPress/wordpress-develop/pull/3359

The rationale for this is that the theme.json classes are now used before all the blocks are registered (aka get template data, etc.), hence, the caching wasn't working as expected. See https://github.com/WordPress/gutenberg/issues/44434 and https://github.com/WordPress/gutenberg/issues/44619

I'd like to have a better understanding of a baseline before/after these PRs to see what's the impact and whether it's something we need to act for 6.1 or can do later.

**Comment by aristath** [comment]
Update: It looks like this commit is the culprit: https://github.com/WordPress/wordpress-develop/commit/a93789208fdbca326a4c53c883baac9f6183483d
Reverting that commit fixes the issue locally.

Props @ockham and @oandregal for pointing me to that direction 👍

**Comment by ockham** [comment]
Thank you for tracking this down, @aristath. I had left a comment on the originating PR with some suggestions for more caching: https://github.com/WordPress/wordpress-develop/pull/3408#issuecomment-1268457840. Maybe applying these could mitigate the issue?

Unfortunately, I'll only have limited availability myself until Tuesday. Pinging @oandregal @andrewserong @ajlende @talldan @glendaviesnz who were involved in the [original research](https://github.com/WordPress/gutenberg/issues/44434) for assistance 😅

**Comment by ockham** [comment]
> I had left a comment on the originating PR with some suggestions for more caching: https://github.com/WordPress/wordpress-develop/pull/3408#issuecomment-1268457840. Maybe applying these could mitigate the issue?

Ah, that might not cut the mustard 😕 (I had missed these two comments: https://github.com/WordPress/gutenberg/issues/44772#issuecomment-1271356760 and https://github.com/WordPress/gutenberg/issues/44772#issuecomment-1271447927.)

**Comment by aristath** [comment]
Posting 2 screenshots with the stats with and without that commit.

With the commit applied:

<img width="991" alt="Screenshot 2022-10-07 at 1 17 12 PM" src="https://user-images.githubusercontent.com/588688/194541197-c9142a6d-a9bf-472c-9937-b105eeffd9bb.png">

When reverting the commit:

<img width="991" alt="Screenshot 2022-10-07 at 1 16 22 PM" src="https://user-images.githubusercontent.com/588688/194541166-578dbd9f-85a9-405a-9216-903f37bc2ded.png">

The times shown there are all in milliseconds, and keep in mind that Xdebug + profiling slow down the site **a lot**. However, the differences are an indication of the commit's impact.
Reverting the commit reduces the time from 9473ms to 7528.
The `WP_Theme_JSON::sanitize()` method was called 633 times, and reverting the commit makes that number go down to 251. I believe that is the main issue... The sanitize method is what calls `remove_keys_not_in_schema`, so all those extra calls just make processing slower.

**Comment by ockham** [comment]
Thank you Ari!

@oandregal Can we cache `sanitize` based on the 2nd and 3rd argument (list of valid blocks and elements, respectively)? The keys of those arrays (block and element _names_) should be hopefully enough.

**Comment by oandregal** [comment]
I've started to implement and track some improvements in https://github.com/WordPress/wordpress-develop/pull/3418

**Comment by oandregal** [comment]
The current state of https://github.com/WordPress/wordpress-develop/pull/3418

![Captura de ecrã de 2022-10-08 00-58-51](https://user-images.githubusercontent.com/583546/194673335-1a5dd5e0-623e-4dfb-a32f-016b01e6a937.png)

**Comment by spacedmonkey** [comment]
I did some profiling with blackfire. These are the results. 

<img width="437" alt="Screenshot 2022-10-08 at 01 16 36" src="https://user-images.githubusercontent.com/237508/194677850-e615bec4-971b-42b9-a690-e92ef67a2ef5.png">

Can't think of a good reason why the method `remove_keys_not_in_schema`. 

I believe this line is the issue. 

https://github.com/WordPress/wordpress-develop/blob/e89286a4a74b75f41cc89a1aa7372992146f8b7f/src/wp-includes/class-wp-theme-json.php#L813


`remove_keys_not_in_schema` calls itself recurrively and results in a loop somehow. Do we have unit tests for this code?

**Comment by getdave** [comment]
> cc @getdave, if I'm not mistaken that was added in the `sanitize()` method in #41786 ?

Sorry for late reply I've been AFK. Based on [my comment](https://github.com/WordPress/gutenberg/pull/41786/files#r900030220) here it looks as though the method _already_ existed as I was having to work _around_ it by adding pseudo selectors to the schema so they didn't get stripped by this method.

**Comment by oandregal** [comment]
https://github.com/WordPress/wordpress-develop/pull/3418 has landed bringing numbers back to 6.0 baseline.

I'm still investigating this to squeeze more ms and have prepared https://github.com/WordPress/wordpress-develop/pull/3441 as a modest improvement from 6.0 numbers.

**Comment by aristath** [comment]
Since the issue was addressed in Core, I'll go ahead and close this one.
Thank you everyone who worked on this! ❤️
