### ISSUE TITLE
About the correction of the Kurdish language code

### ISSUE THREAD

**Issue by CrowdsourceKurdish** [WordPress/gutenberg#44786]
### Description

Currently, the Worpress localization center uses the language code **"kmr"** for the **Kurdish (kurmanji)** language.

![kurdish code](https://user-images.githubusercontent.com/72891963/194580772-7e7f5757-7d32-450f-8d05-065d1b9b021e.jpg)

We want this to be changed because it says that according to Unicode standards, the language code **"ku**" should be used for **Kurdish (kurmanji)**.
Check for source: https://cldr.unicode.org/index/cldr-spec/picking-the-right-language-code#h.lc35xrlj4da6

![macro language](https://user-images.githubusercontent.com/72891963/194580886-521317ea-7ae1-494e-bcc0-9e508392a152.jpg)

Google and other major companies use the language code **"ku"** for **Kurdish (kurmanji)** in accordance with Unicode standards.
We demand that the necessary corrections be made.

Best Regards

**Kurdish Language Community**

### Step-by-step reproduction instructions

https://translate.wordpress.org/

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @CrowdsourceKurdish

The issue isn't related to the Gutenberg plugin or something we can fix on our end. Please report the problem on meta Trac - https://meta.trac.wordpress.org/.
