### ISSUE TITLE
Expand documentation to include InspectorControls code examples

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#4478]
I'm working on a demo ES5 Countdown Timer block at the moment. It needs two control elements: `label` and `countdown_date`.

Because the latter is a computed value, I want to create a TextControl (or similar) to input the date. However, only `BlockControls` are documented so I spent a fair amount of time in confusion until I realized there's an `InspectorControls` API too. It would be nice to have this documented.

**Comment by chrisvanpatten** [comment]
This should be an easy one — we have the documentation already, just need some code examples.

Possibly volunteering @ajitbohra for this one, if you're interested? 😅

**Comment by ajitbohra** [comment]
@chrisvanpatten will do documentation sprint in the next couple of day will add this to my list.

Seems like probably have worked on this but forget to push!
