### ISSUE TITLE
Templates: add a way to create a non-editable block without code

### ISSUE THREAD

**Issue by wsydney76** [WordPress/gutenberg#4479]
The user should be unable to edit the content of some blocks in the template (e.g Sub headlines, disclaimers)

**Comment by mtias** [comment]
Have you tried the `template_lock => 'all'` property?

**Comment by mtias** [comment]
@wsydney76 ah, so what you seek specifically is to set a block with already defined content but that the user cannot in any way edit or add data to?

**Comment by wsydney76** [comment]
@mtias Yes, sorry for being unclear. For example, you may want to define a heading block setting the content  attribute to 'Visa Requirements' with a following list block. The user should not be able to edit the heading to 'My favourite bars' , because that would break the required semantics.

Technically possibly related to #4474, as the content is just another attribute to lock.

**Comment by youknowriad** [comment]
> @wsydney76 

Just a create a non-editable block  in this case. Isn't this enough?

**Comment by wsydney76** [comment]
> Just a create a non-editable block in this case. Isn't this enough?

@youknowriad Yes, it would be if you are familiar with coding blocks, but the experiment was about using only standard blocks.

**Comment by youknowriad** [comment]
Do you think we should offer everything with standard blocks? I don't we should do so, the possibilities are endless and the ressources not. 

Creating a static block is as simple as:

```js
var myelement = wp.element.createElement( 'h2', {}, 'static content' );
wp.blocks.registerBlockType( 'myplugin/myblock', {
 title: 'My block',
 category: 'common',
 edit: () => myelement,
 save: () =>myelement,
} );
```

Trying running this in a gutenberg console

**Comment by designsimply** [comment]
Closing this request as won't fix for now based on the latest reply noting it would create problems in terms of resources. Thank you for the suggestion and discussion!
