### ISSUE TITLE
PHP Deprecated:  strncmp(): Passing null to parameter #1

### ISSUE THREAD

**Issue by uuroveits** [WordPress/gutenberg#44792]
### Description

I´m using Gutenberg 14.2.0
WordPress is creating a log-file (https://www.abu-sgbu.de/wp-content/debug.log)
There occurs concerning Gutenberg:
PHP Deprecated:  strncmp(): Passing null to parameter #1 ($string1) of type string is deprecated in /is/htdocs/wp12019806_ZQF75OIS9W/www/abusgbu/wp-content/plugins/gutenberg/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php on line 1064
Question: is this a bug of WP RSS Aggregator or can I as user of WP RSS Aggregator solve this problem?
Reg
Jochen

### Step-by-step reproduction instructions

1. Using Gutenberg
2. error-message in https://www.abu-sgbu.de/wp-content/debug.log

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for creating the ticket. I believe this code needs to be updated in Gutenberg to meet PHP compatibility standards. I also noticed the warnings when trying to get the Gutenberg unit tests running on PHP 8.1 - https://github.com/WordPress/gutenberg/pull/44566.
