### ISSUE TITLE
Export DateTimePicker as an InspectorControl

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#4480]
Because `<input type="datetime-local" />` isn't supported in all browsers, it would be helpful to have `DateTimePicker` exported as some type of control that can be used in blocks.

**Comment by youknowriad** [comment]
@danielbachhuber DateTimePicker is already available as a generic component in `wp.components.DateTimePicker`. 

Actually, I think the Inspector controls should be moved to the `wp.components` module because they are generic components not tied to the editor. (We already have an issue for this... I think)

**Comment by phpbits** [comment]
Tried :

```
el(
			        wp.components.DateTimePicker,
			        {
			            currentDate: moment(),
			        },
		    	),
```

And it's not working. Did anyone made it work perfectly? Thanks!

**Comment by phpbits** [comment]
@youknowriad @danielbachhuber Have you figured out how the DateTimePicker works? Thanks!

**Comment by youknowriad** [comment]
@phpbits Yes, I've just used it in a third party plugin see here https://github.com/youknowriad/gcf/pull/19

**Comment by youknowriad** [comment]
The "locale" prop may be required.

I'm going to close this ticket as the DateTimePicker is already usable as an inspector control.

**Comment by phpbits** [comment]
@youknowriad Thanks! Do you know when will this be added on : https://wordpress.org/plugins/gutenberg/ ? Thanks!

**Comment by phpbits** [comment]
@youknowriad I'm using ES5, any clue on how I can show the datepicker on text input click? THanks!

**Comment by youknowriad** [comment]
@phpbits you can add an event handler `onClick` on your input and show a popover or something containing this component. All the components to build this behavior are available in wp.components (Popover, DatePicker, Button)

**Comment by phpbits** [comment]
@youknowriad Thanks! I'll check how the PopOver works.

**Comment by phpbits** [comment]
@youknowriad Sorry for bothering you too much but I can't seem to make the popover work. I'm trying to convert this to ES5 : https://github.com/WordPress/gutenberg/blob/2bb48d5ee6cb31d137c96bd3660e86bde2ec30d6/components/popover/README.md but it's not working. Thanks!

**Comment by zrubinrattet** [comment]
@phpbits did you ever end up figuring it out with ES5? I'm having the same issue as you. Thanks!

**Comment by phpbits** [comment]
@zrubinrattet Yes. I've added `locale: 'en'` as per @youknowriad 's instruction above ;)

**Comment by zrubinrattet** [comment]
I know this is closed but I also want to add that in order to get the datepicker to work I had to also make sure the ```onChange``` and ```selected``` keys are added:

```
el(
	DatePicker,
	{
		currentTime : moment(),
		locale : 'en',
		onChange : datecreatedPickerOnChange,
		selected : props.attributes.datecreatedPicker
	}
),
```
where the ```onChange``` callback sets ```props.attributes.datecreatedPicker``` and the key in the attributes array is configured like:

```
datecreatedPicker : {
	type : 'array'
},
```
