### ISSUE TITLE
Site logo block: upload button is clickable even when not visible

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#44815]
### Description

When site logo block is on a page, the upload button is clickable even when it isn't visible.

### Step-by-step reproduction instructions

1. Create new page
2. Add site logo block
3. When block is unselected, hover over it. Note hand cursor and clickable area in the middle.
4. Select the block and now the button is visible

### Screenshots, screen recording, code snippet

<img width="382" alt="image" src="https://user-images.githubusercontent.com/87168/194858230-d16b6e13-8701-4924-a5a6-fb9111272e49.png">

https://user-images.githubusercontent.com/87168/194858240-9c29006d-d97a-49af-9bc2-731d5f5cffc2.mov

### Environment info

- Gutenberg 14.2.0
- Twenty Twenty two theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
It seems [we can't use](https://github.com/WordPress/gutenberg/pull/43323) `visibility` and have to find an alternative here.. --cc @jasmussen
