### ISSUE TITLE
Inserter: new Header, Footer, and Banner patterns not listed

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#44843]
### Description

In testing 6.1 Beta 3, I noticed that the Header category includes the prior patterns, the Footer category doesn't list the new patterns, and the inserter doesn't list the new "Banner" patterns despite prior work done leading up to the release cc @mcsf https://github.com/WordPress/gutenberg/pull/44203 & https://github.com/WordPress/gutenberg/pull/43157 This is causing the header template part to not have the option to be replaced, since it seems those patterns are missing. cc @ndiego @ironprogrammer can ya'll replicate? 

Of note, there's a separate issue here which is interfering with my ability to even find the Header patterns https://github.com/WordPress/gutenberg/issues/44842 

### Step-by-step reproduction instructions

1. Use 6.1 beta 3.
2. Open Appearance > Site Editor.
3. Open Inserter > Patterns.
4. Select the Header or Footer options. Notice it's missing a bunch of patterns. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/194965725-b307e124-fe03-47e5-8a02-7af932223494.mov

### Environment info

- WP 6.1-beta3-54428
- No GB
- TT3
- Chrome 106.0.5249.61

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
If I activate the latest version of Gutenberg, I can see them listed (and they include the headings that should be in a banner category):


https://user-images.githubusercontent.com/26996883/194966504-e02b3593-12a6-4f38-89ca-d82575b522c5.mov

**Comment by ironprogrammer** [comment]
Hi, @annezazu -- I can replicate this behavior as well.

## Reproduction Report

### Environment
- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 12.6
- Browser: Safari 16.0
- Server: nginx/1.23.1
- PHP: 7.4.32
- WordPress: 6.1-beta3-54390-src
- Theme: twentytwentythree v1.0

### Actual Results
- ✅ New Banner pattern list is not displayed in inserter.
- ✅ Header and Footer pattern inserter lists are missing expected patterns.

With Gutenberg 14.3.0-rc.1 active, the expected patterns in Header and Footer appear. However, the Banner category is still not displayed.

**Comment by priethor** [comment]
I can reproduce as well.

### Reproduction Report
**Environment**
- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 12.6
- Browser: Chrome 105
- Server: nginx/1.16.0
- PHP: 7.4.1
- WordPress: 6.1-beta3
- Theme: twentytwentythree v1.0

Regarding the banners category itself, as far as I see, #44203 registered the new `Banner` pattern category, but as of today, none of the [existing bundled patterns](https://github.com/WordPress/gutenberg/commits/5d417cc7b989d48f7010913296443869ab9992e6/lib/compat/wordpress-6.1/block-patterns) have been moved to the new category (see @mcsf's [comment here](https://github.com/WordPress/gutenberg/pull/44203#issuecomment-1249162165)). Therefore, the `Banner` category is not shown in the Inserter, which I don't think is failing per se.

**Comment by priethor** [comment]
Action items:
- [ ] Backport the bundled patterns from #43157 to WP core, as per [this comment](https://github.com/WordPress/gutenberg/pull/43157#issuecomment-1215204128)
- [ ] Reclassify patterns to the `Banner` category? @beafialho can you help clarify this part?

**Comment by annezazu** [comment]
Flagged this up in the 6.1 release channel to get help. This is an important, high impact feature to have in for 6.1 and I'm not sure where things went wrong with including the backports here.

**Comment by annezazu** [comment]
[Decision was made not to include this in 6.1](https://wordpress.slack.com/archives/C03LZ88NX6G/p1665513781772549) and it has been pushed to a future release. Moving this to bumped to 6.2 as a result. 

>With Gutenberg 14.3.0-rc.1 active, the expected patterns in Header and Footer appear. However, the Banner category is still not displayed.

Noting that in particular the former "heading" patterns are still available under the "Header" category and no banner category is in place for these prior patterns to live. Tied to this, I don't see a banner category in the Pattern directory. I'm going to leave this open even though this won't be going into 6.1.

**Comment by priethor** [comment]
> Backport the bundled patterns from https://github.com/WordPress/gutenberg/pull/43157 to WP core, as per https://github.com/WordPress/gutenberg/pull/43157#issuecomment-1215204128

To clarify the action item above, can Editor Tech Leads confirm [the patterns contained in lib/compat](https://github.com/WordPress/gutenberg/tree/wp/6.1/lib/compat/wordpress-6.1/block-patterns) have not been backported to WP core, as they are not available in `wp-includes/block-patterns`? 🙏 

If so, as this has been punted to 6.2, let's move the patterns to the corresponding `lib/compat/6.2` to avoid confusion and ease future merges.

cc @ockham @michalczaplinski @c4rl0sbr4v0

**Comment by beafialho** [comment]
> Reclassify patterns to the Banner category? @beafialho can you help clarify this part?

I can see the bundled header and footer patterns but can confirm I see banner patterns in the `Headers` category. As mentioned in [this comment](https://github.com/WordPress/gutenberg/pull/43157#issuecomment-1212201440), the following patterns should be in that category:
- Large header with left-aligned text
- Large header with text and a button
- Media and text in a full height container
- Media and text with image on the left
- Media and text with image on the right
- Event

The ones with the word "header" in them should also probably be renamed. Maybe replacing the word "header" with the word "banner".

**Comment by mcsf** [comment]
> the following patterns should be in that category:
> 
> * Large header with left-aligned text
> * Large header with text and a button
> * Media and text in a full height container
> * Media and text with image on the left
> * Media and text with image on the right
> * Event

Just a reminder that these live in the pattern directory and so should be fixed there, not in the code-bundled patterns.

**Comment by ryelle** [comment]
The original issue that forced Gutenberg to bundle the patterns instead of use the Pattern Directory was fixed, so you should be able to build these in the Pattern Directory and load them from there (either with a new API request with specific slugs, or by adding these to the featured category to auto-load them on all sites). If that's not the case and there are other issues trying to create these on w.org/patterns, please [open an issue](https://github.com/WordPress/pattern-directory/issues) so we can get it fixed 🙂

**Comment by annezazu** [comment]
Closing this out as I now see the bundled patterns for headers & footers in the latest version of Gutenberg with this work https://github.com/WordPress/gutenberg/pull/45620. Thanks, folks!

Going to open a new issue around ensuring the Pattern Directory's API is used going forward now that an interim solution is in place.
