### ISSUE TITLE
Clarify template part revert process

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#44841]
Currently, when you revert a template part, a few aspects of the experience make it feel a bit janky/unpredictable:

- After reverting, the template part order changes.
- Upon entering the site editor, you are met with two notices (a bit overwhelming).
- The top level notice says "template reverted" which feels jarring when you only reverted a template part. 
- The second notice says "entity reverted" in a completely separate part of the experience. 

Here's a video showing the current experience with 6.1 beta 3:

https://user-images.githubusercontent.com/26996883/194964565-dc57925a-93d4-486c-9c51-a1c4ee42fc72.mov

To improve this, I think we need to keep the order of template parts the same and simplify the notices. For example, I know that technically speaking a _part_ of the template was reverted and the notice should be clearer to prevent confusion. cc @WordPress/gutenberg-design

**Comment by jameskoster** [comment]
Agreed with all of this :)

The green "Template reverted" notice can be deleted – we should use Snackbars for confirmation of this action. 

Speaking of which, navigating away from the current view should probably hide any visible Snackbars, it's a bit strange how they stack and persist currently.

Snackbar content should include the entity name: "Index reverted", "Header reverted".

**Comment by jasmussen** [comment]
>  it's a bit strange how they stack and persist currently.

They also stay for a long time! Most snackbars disappear too quickly, ours stays for maybe a second or two too long, IMO 😅

**Comment by methlox** [comment]
Hey, I'd like to help solve this issue, please tell me where I should start

**Comment by jameskoster** [comment]
Sorry for the late reply @methlox, here's some reading material that should be helpful: https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/README.md

**Comment by apmatthews** [comment]
I spent some time looking into this a couple of weeks ago and found that much of the relevant code is shared between the Templates and Template Parts screens (now "Manage all templates" and "Manage all template parts"). Is it acceptable for the changes proposed here apply to both screens or do template parts need to be treated differently?

**Comment by jameskoster** [comment]
I don't see any need for them to be treated differently during this process.

**Comment by priyomukul** [comment]
Seems like the template part revert process or should I say the message after reverting is clarified more by "**Template reverted**" 

BTW, I was looking at it from the trunk branch. 

👍🏻
