### ISSUE TITLE
Inserter: some Pattern categories lead to the screen breaking/overflow

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#44842]
### Description

When browsing parts of the Inserter > Pattern section, I noticed some categories led to massive white space/the screen breaking, for lack of a better term. Feel free to update the title. This was hard to explain. 

### Step-by-step reproduction instructions

1. Open Appearance > Site Editor.
2. Open Inserter.
3. Head to Patterns. 
4. Scroll through categories and notice for some the screen overflows (featured, headers).

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/194965224-650c984d-fbf4-4785-ab98-35fca8e99291.mov

### Environment info

- WP 6.1-beta3-54428
-  No GB
- TT3
- Chrome Version 106.0.5249.61 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
This also occurs with the latest version of GB installed:


https://user-images.githubusercontent.com/26996883/194966521-11d2cebb-7c02-451c-a1e5-2113379046a5.mov

**Comment by ironprogrammer** [comment]
I was able to reproduce this issue. The size of the selected Patterns list appears to be consistent with the amount of scroll overflow past the bottom of the editor (i.e. longer lists = more unexpected white space below editor).

## Reproduction Report

### Environment
- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 12.6
- Browser: Safari 16.0
- Server: nginx/1.23.1
- PHP: 7.4.32
- WordPress: 6.1-beta3-54390-src
- Theme: twentytwentythree v1.0
- Gutenberg: both active and inactive

### Actual Results
- ✅ When the Patterns inserter list is taller than the viewport (e.g. "Featured"), scrolling to the end of the list is followed by unexpected overflow scrolling of the entire editor page.

**Comment by talldan** [comment]
What seems to be happening is that the patterns are causing an overflow. I don't know why but it's having the result of making the editor interface's body show a scrollbar. In this screenshot you can see I have double scrollbars on the right (my OS is configured to always show scrollbars):
![Screen Shot 2022-10-11 at 12 28 28 pm](https://user-images.githubusercontent.com/677833/194997268-a8633e48-c17e-4fd8-be84-5263bcd8e1c2.png)

It's this style `overflow: auto` rule that results in the additional scrollbar:
https://github.com/WordPress/gutenberg/blob/63d83dd80023223f574ac93200c6d73cc19ba97e/packages/interface/src/components/interface-skeleton/style.scss#L45-L64

Setting this to `overflow: hidden` resolves things but might cause other issues. This CSS was added in #18686, so @jasmussen might have some insights into whether this is still required. If it's possible to remove this that's one way to fix the bug. It might also be possible to make this rule only active at mobile breakpoints.

The other possible fix is changing this `overflow: visible` rule to `overflow: hidden`:
https://github.com/WordPress/gutenberg/blob/0167f9eae6c134691c44c8c71bb899b6b2f2eaf1/packages/block-editor/src/components/inserter/style.scss#L87-L91

That's from #20951, but I'm not sure why it's needed. Maybe @youknowriad can recall.

Setting `.block-editor-inserter__main-area` to `overflow: hidden` also works and may be another way to fix it.

**Comment by talldan** [comment]
<s>> The other possible fix is changing this overflow: visible rule to overflow: hidden:

I've put together a PR that does this - [Fix overflowing patterns by using overflow:hidden](https://github.com/WordPress/gutenberg/pull/44853#top)</s>

edit: Have a better fix now on the same PR - https://github.com/WordPress/gutenberg/pull/44853
