### ISSUE TITLE
Add option to duplicate taxonomy template in FSE editor - WP 6.1

### ISSUE THREAD

**Issue by dansdev** [WordPress/gutenberg#44851]
## What problem does this address?

In 6.1 we can now add/edit taxonomy templates YAY!!

One thing that I found that might be useful - is having an option to duplicate an existing template for a "specific item". This would allow users to build a set template structure/style and allow them to quick copy across to other items in the taxonomy. 

Correct me if I am wrong, but if I was to create a template for all items in a taxonomy, I would still need to manually setup from scratch a template for a specific item within that same taxonomy?

## What is your proposed solution?

A "Duplicate template" option could be housed in the add template layer after selecting either "All items" or "Specific item"?
<img width="565" alt="duplicate-1" src="https://user-images.githubusercontent.com/87308680/194995733-a9467c29-f550-4b17-be6b-03bd55e0a8a2.png">

Or perhaps, once a template has been created, clicking the three dots would show options "Duplicate", "Delete" 
<img width="1188" alt="duplicate-2" src="https://user-images.githubusercontent.com/87308680/194994832-8b7b1b8f-d006-4deb-ab15-e5146725843a.png">

**Comment by annezazu** [comment]
Hey there! Thanks for the excitement and for opening this issue. When reading through this, my brain immediately thought of this related issue: https://github.com/WordPress/gutenberg/issues/41060 I'd prefer if we can continue discussing options there and close this one out to reduce duplicated conversations. Is that okay with you?

**Comment by dansdev** [comment]
> Hey there! Thanks for the excitement and for opening this issue. When reading through this, my brain immediately thought of this related issue: #41060 I'd prefer if we can continue discussing options there and close this one out to reduce duplicated conversations. Is that okay with you?

Hey @anneazu, 

Yeah sure thing, makes total sense. Exciting to see that something similar is already being discussed. Thank you!
