### ISSUE TITLE
Site editor: Patterns tab in block library appears after a delay and can interrupt the user or cause a focus loss

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#44893]
### Description

The way the block library patterns tab in the site editor loads in is a bit jarring.

It can also result in issues with drag and drop being interrupted and focus losses.

Ways to remediate:
- Preload patterns
- Show a loading spinner until patterns are loaded

### Step-by-step reproduction instructions

1. Open the site editor
2. Open the block library
3. Try dragging and dropping a block before the patterns tab is visible
4. Alternatively try keyboard navigating through blocks before the patterns tab is visible

#### Drag and drop interruption (block is still inserted, but the 'draggable chip' disappears)

https://user-images.githubusercontent.com/677833/195298296-ebde5e17-abeb-41f7-a104-e1d30da6783b.mp4

#### Focus loss

https://user-images.githubusercontent.com/677833/195298661-04f43cd1-1b7b-498f-979d-cabccc349621.mp4

### Environment info

WordPress 6.1

Mac OS / Brave

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Another annoyance is that the block inserter appears empty when there are no featured patterns for the given context:
![Screen Shot 2022-10-12 at 5 18 33 pm](https://user-images.githubusercontent.com/677833/195303584-2185a21b-b510-4d81-8fc1-568694adb5c1.png)

This was opening the inserter in the context of the navigation block. Empty pattern categories probably shouldn't be shown in the dropdown.

**Comment by cbirdsong** [comment]
This also occurs in the post editor with the reusable blocks tab.

**Comment by talldan** [comment]
It doesn't seem to happen any more, so I'll close this.
