### ISSUE TITLE
Edit and Restructure Blocks in "Post Content" when creating a Custom Template

### ISSUE THREAD

**Issue by kirkvin** [WordPress/gutenberg#44897]
## The "Post Content" currently extremely limit what can be done when creating a "Custome Template"

It is both frustrating and difficult to restructure and create a proper custom temple, when all we get is a "post content" with no editable options to rearrange where this image should go, where this video should go, where this text should go.

Note: I am talking a creating a "Custom Template" that can be applied to all/some posts or pages.

## Let the "Post Content" block be editable

If would be great if we could have a Dynamic "short description field" and a Dynamic "long description field".
Just like WooCommerce, but it just that this would be block based.
Let blocks in the "Post Content" be rearrangeable so that a truly custom template can be made.
Also, let the "Custom Html" and "Code" blocks also be rendered Dynamically.
Let feature image be replaceable with a feature video or audio.
Add Show more and Show Less to hide to Dynamically hide parts of content for all posts or pages.

**Comment by youknowriad** [comment]
Hi thanks for creating this issue and sorry for replying this late. It's very unclear to me how "create custom template" is not rearrangeable. You can use any blocks when creating templates (post content) for the long full content and post excerpt block for the summary/excerpt.

For feature video, AFAIK Core doesn't fully support these (unless I'm missing something), we might want to raise this on [Core trac](https://core.trac.wordpress.org)

Please let me know if this is still relevant and maybe create separate issues for each feature instead, it would simplify feedback and discussions.
