### ISSUE TITLE
`ColorPalette`: review `colord` support when using CSS variables

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#44904]
> From the recent discoveries while working on #44668 I also realized that `colord` will silently fail while parsing CSS variables and fallback to `#000000`, which means that all the checks / features based on `colord` are not really working for CSS variables. We should investigate this separately (cc @mirka @chad1008 )

_Originally posted by @ciampo in https://github.com/WordPress/gutenberg/pull/44632#discussion_r993507561_

**Comment by mirka** [comment]
Related: #41459

**Comment by ciampo** [comment]
With #47181 merged, and #41459 tracking the contrast check bug, I think we treat this issue as a duplicate and close it.
