### ISSUE TITLE
Error when reloading a post containing a block with Editable saved in html comments

### ISSUE THREAD

**Issue by wsydney76** [WordPress/gutenberg#4490]
## Steps to Reproduce (for bugs)

1. Setup a block as described in #4489, see https://gist.github.com/wsydney76/8288604d8fe3a1c135a0af67502a5d47

2. Publishing a post and rendering it serverside works as expected.
3. Reload the post

![image](https://user-images.githubusercontent.com/25308802/34953708-f315f424-fa1d-11e7-9485-d5034e642d9d.png)

https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D&args[]=

**Comment by mtias** [comment]
Closing this as we have a new shape of RichText coming which should make it obsolete. If in retesting something comes up, please open again.
