### ISSUE TITLE
TYPO: The word ocurred is used at multiple instances instead of the word occurred

### ISSUE THREAD

**Issue by alanjacobmathew** [WordPress/gutenberg#44915]
### Description

- One such error was earlier mentioned in the trac ticket : [https://core.trac.wordpress.org/ticket/56814#ticket](https://core.trac.wordpress.org/ticket/56814#ticket)

- Another typo noticed : [here](https://github.com/WordPress/gutenberg/blob/cedbd43824a0e3494d61467d1ee9890737270d7a/packages/edit-navigation/src/store/actions.js)  

### Step-by-step reproduction instructions

-

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thank you for submitting the issue. I believe it has been resolved by the mentioned PR, so I will close it.
