### ISSUE TITLE
Gallery block: editing a gallery uses "Insert gallery" button

### ISSUE THREAD

**Issue by jeherve** [WordPress/gutenberg#4491]
## Issue Overview
Editing a gallery block uses "Insert gallery" modal instead of Core's "Edit Gallery" modal.

## Steps to Reproduce (for bugs)
1. Create a new post with the Gutenberg editor. 
2. In this post, insert a gallery block.
3. Publish the post.
4. Later, come back and edit that post in the Gutenberg editor.
5. Click on the Edit icon on top of the gallery.
6. The modal that loads, while allowing you to add or remove images, says "Insert gallery".

## Expected Behavior

I expected to be able to edit the gallery, and it took me a second to understand that I could do this through this screen:

![screenshot 2018-01-15 at 20 44 46](https://user-images.githubusercontent.com/426388/34959082-f28c1dd2-fa34-11e7-8185-8ce713f3519e.png)

## Possible Solution
- When editing a gallery in WP, you get a specific "Edit Gallery" modal. Gutenberg could open this:

![screenshot 2018-01-15 at 20 39 22](https://user-images.githubusercontent.com/426388/34958933-42e84e50-fa34-11e7-8fed-ec7d44071392.png)

## Related Issues and/or PRs
#1704

## Details

- Using Chrome, WP 4.9.1
- Gutenberg 2.0.0

**Comment by mellis32** [comment]
Today I tried to make a gallery and noticed this. I also was not able to resize the gallery.

**Comment by jorgefilipecosta** [comment]
Thank you for reporting this issue @jeherve, it was fixed with the merge of https://github.com/WordPress/gutenberg/pull/2488.
