### ISSUE TITLE
Feature Request: Add a menu item on Dashboard to access all FSE templates

### ISSUE THREAD

**Issue by Greatdane** [WordPress/gutenberg#44913]
## What problem does this address?
There is no direct way to go to templates from the dashboard, you have to go through the site editor. 

![Markup on 2022-09-09 at 19:08:34](https://user-images.githubusercontent.com/50875131/189452533-59992896-7b62-4934-a290-017bf1aa954f.png)

## What is your proposed solution?

We should have a direct link to our FSE templates to appear on the dashboard. Something like this:

![Markup on 2022-09-09 at 19:11:17](https://user-images.githubusercontent.com/50875131/189452720-c98be8db-5172-4fed-9646-d0524d4bdc6c.png)

**Comment by youknowriad** [comment]
There has been a lot of iterations on this. Templates have their own section in the site editor now.
