### ISSUE TITLE
The Flow of Selecting Blocks

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#4492]
Here are a few ideas to improve the writing flow by further reducing some of the UI presence when interacting with blocks:

- [x] Moving a block up or down does not select a block (or puts it in `isTyping` mode`.
- [x] Clicking on the first block "Write your story" engages `isTyping` and doesn't show UI unless user continues moving the cursor under a certain threshold of time.
- [ ] Clicking on any block doesn't show toolbar UI until the user continues moving the cursor for more than a threshold (this might be too much).
- [x] Clicking "Enter" on a block _always_ engages `isTyping`.

**Comment by mtias** [comment]
Last one was done in #4395.

**Comment by karmatosed** [comment]
> Clicking on the first block "Write your story" engages isTyping and doesn't show UI unless user continues moving the cursor under a certain threshold of time.

What about if there is inaction in typing anything? I am thinking for cases where people may be lost.

**Comment by mtias** [comment]
Going to close this as current state seems alright.
