### ISSUE TITLE
Localhost Support - get_editor_stylesheets()

### ISSUE THREAD

**Issue by milanchymcak** [WordPress/gutenberg#44951]
### Description

By default get_editor_stylesheets() will not use styles without https or in style directory. (see: [https://github.com/WordPress/wordpress-develop/blob/6.0.2/src/wp-includes/theme.php#L2136-L2181](https://github.com/WordPress/wordpress-develop/blob/6.0.2/src/wp-includes/theme.php#L2136-L2181)).
While developing on the localhost the function will automatically will not use stylesheets without https if they are not in style directory.

### Step-by-step reproduction instructions

Use add_editor_style() for stylesheets (uri without https) outside template directory.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
👋 I think this might be better suited as a WordPress Core ticket: https://core.trac.wordpress.org/newticket

The function annotations mention `@since 4.0.0`, and the block editor/Gutenberg was introduced in 5.0.

**Comment by priethor** [comment]
Closing the issue as it has been stale for a long time. Please feel free to reopen if the issue persists and there is more info; thanks!
