### ISSUE TITLE
warning package is not compatible with webpack 5

### ISSUE THREAD

**Issue by tomalec** [WordPress/gutenberg#44950]
### Description

`@wordpress/warning` and its [`babel-plugin`](https://github.com/WordPress/gutenberg/blob/trunk/packages/warning/babel-plugin.js) rely on `process.env`. So for `env == 'production'` it's supposed not to show the warning.

The problem is webpack 5 removed `process` variable completely:
- https://webpack.js.org/blog/2020-10-10-webpack-5-release/#changes-to-the-structure
   > Automatic polyfills for native Node.js modules were removed
   >  `node.process` removed
- https://webpack.js.org/migrate/5/#run-a-single-build-and-follow-advice
   > webpack 5 does no longer include a polyfill for this Node.js variable. Avoid using it in the frontend code.
   > `process.env` is Node.js specific and should be avoided in frontend code.

So, the `typeof process !== 'undefined' && process.env !=== 'production'` is always false, which prevents `warning` to be called for any kind of environment.

### Step-by-step reproduction instructions

Follow the [package's README](https://github.com/WordPress/gutenberg/tree/trunk/packages/warning#warning) 
1. Put `@wordpress/warning/babel-plugin` into your [babel config](https://babeljs.io/docs/en/plugins#plugin-options) or use [`@wordpress/babel-preset-default`](https://www.npmjs.com/package/@wordpress/babel-preset-default), which already includes the babel plugin.
2.
   ```js
   import warning from '@wordpress/warning';
   warning( 'You should see me' );
   ```
3. Build your bundle with webpack 5

### Environment info

```json
   "@wordpress/warning": "2.19.0",
   "webpack": "^5.74.0",
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tomalec** [comment]
One workaround if to add `new webpack.ProvidePlugin( { process: 'process/browser' } )` to the `plugins` of webpack config.

However, it increases the bundle size, and `@wordpress/warning/babel-plugin` was [meant to reduce it](https://github.com/WordPress/gutenberg/tree/trunk/packages/warning#reducing-bundle-size).

**Comment by gziolo** [comment]
What is the new pattern for marking a code block as intended only for development purposes? We could simplify the check to verify if something like `SCRIPT_DEBIG` (mirroring WordPress core) is set to `true`.

**Comment by gziolo** [comment]
I started to https://github.com/WordPress/gutenberg/pull/50122 to see if we can fix the bug by reworking how we approach feature flagging for development-related tooling.
