### ISSUE TITLE
After updating Page, Message bar should say Page updated not Post updated

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4496]
## Issue Overview
After adding a Page, publishing it, and then updating it, the message bar displays _Post updated! View post_.

It should say _Page updated! View page_, when editing Pages.

![gutenberg-postupdatedbar](https://user-images.githubusercontent.com/2078245/34967942-38e1bc9e-faba-11e7-9ea7-87c1c1929b03.png)

## Steps to Reproduce (for bugs)
1. Create new Page
2. Publish Page
3. Edit the Page and then click the _Update_ button to update the Page
4. View message bar

## Expected Behavior
When editing a Page the message should refer to Page not Post

## Current Behavior
Message Bar advises that I just updated my Post instead of Page.

_Gutenberg 2.0.0
Firefox Quantum 57.0.4 (64-bit)
WordPress 4.9.1_

**Comment by Soean** [comment]
@maddisondesigns Thanks for your ticket, we already have an issue for this: #3315
