### ISSUE TITLE
Cannot add blocks to a nested group or row block when editing templates

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/gutenberg#44989]
### Description

When editing a theme template, if you add a Group block or a Row block inside a Group block (ie a nested Group or Row) it's not possible to add blocks to the nested Group or Row. 

### Step-by-step reproduction instructions

1. Edit a block theme template (tested in both tt2 and a newly created block theme)
2. Add a Group block
3. Add a nested Group block inside the parent Group block
4. The UI to add additional blocks inside the nested Group block does not appear.
5. If you switch the nested Group to a nested Row, you also cannot add blocks

### Screenshots, screen recording, code snippet

Nested group

![nested-group](https://user-images.githubusercontent.com/180629/195920394-089bc439-60f6-4a92-a9b5-672a71de4c74.png)

Nested row

![nested-row](https://user-images.githubusercontent.com/180629/195920414-170bdbea-cfe5-43bd-8d75-adca16663b26.png)

### Environment info

- WordPress 6.0.2 and Gutenberg trunk
- Tested in Brave browser
- Tested on both an M1 Macbook Pro, and Ubuntu 22.04

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bph** [comment]
I can reproduce this. 
See the video

https://user-images.githubusercontent.com/39980/195929688-1d0606c7-0456-4092-8abf-e77675fd3209.mp4

I tested a bit further. 
Using the Inserter from the left sidebar, drops blocks outside the group block even if it's selected. 

My workaround 

- add outside the first group block a heading block and a paragraph block. 
- made them a group. 
- added a new empty paragraph block in the first group block and 
- dragged the second group block inside the first group block in the space of the empty block.  

I can see a sibling inserter. 
Here another video 

https://user-images.githubusercontent.com/39980/195930755-eb7431ef-d5dd-4a9d-b563-d1f0fea0ae33.mp4

It seems the sibling inserter doesn't appear when the group is empty

**Comment by bph** [comment]
This seems to be happening on both, post editor and in the site editor.

**Comment by carolinan** [comment]
I can reproduce this on WP 6.1-RC1-54520, with and without Gutenberg active.
**FSE theme:** I can reproduce it in the block editor, so not only when editing templates.
**Classic theme:** I can **not** reproduce it in the block editor, I can see the inserter button in the nested group.

**Comment by ndiego** [comment]
I can reproduce can well.

**Comment by tellthemachines** [comment]
This is a regression caused by the styles added in  #44660; I'm looking at a fix now.

**Comment by uniquesolution** [comment]
Its not got resolved yet, I tested it in instawp , using Wordpress 6.0.3 and Gutenberg plugin version 14.3.1 and not able to add anything inside child group block.
here is the login credential to test
https://ndly-finch-zadi.instawp.xyz/wp-admin/
Username : bapajacofi4242
Password : ztxNw18WrGbSM6c7LJsg

I also tested with wordpress beta 6.1, guternberg ver. 14.3.1 have same issue in that too.

**Comment by carolinan** [comment]
Hi @uniquesolution. You are right, the fix is not in Gutenberg [14.3.1](https://github.com/WordPress/gutenberg/releases/tag/v14.3.1). It will be in the plugin in a future update.

**Comment by bph** [comment]
From the PR, it seems the fix made it into 6.1 RC2 @uniquesolution could test it again, please?

**Comment by uniquesolution** [comment]
@bph checked in wordpress 6.1 RC2 with gutenberg ver 14.3.1 installed. Still, the same issue persists.

**Comment by ndiego** [comment]
I just tested this. The issue is resolved in 6.1 RC2. However, when Gutenberg v14.3.1 is active, it appears that the issue is not resolved since the fix is not in Gutenberg yet, and Gutenberg styles generally override Core. @uniquesolution try using just 6.1 RC2 without Gutenberg active, and everything should work as expected. Let me know if not. Thanks!

**Comment by bph** [comment]
The fix is slated for 14.4 version of the Gutenberg plugin release next week. The 14.4 RC is already available under releases.
