### ISSUE TITLE
Gutenberg Needs Margins

### ISSUE THREAD

**Issue by zero2webmaster** [WordPress/gutenberg#44986]
The subject says it all. More info here:
https://www.loom.com/share/75cd2669794540458bab0d71d405141c
Thanks!
Kerry

**Comment by glendaviesnz** [comment]
Thanks for reporting this. With the default theme TwentyTwentyTwo the editor does have margins around the content:

<img width="1470" alt="Screen Shot 2022-10-17 at 8 59 27 AM" src="https://user-images.githubusercontent.com/3629020/196055510-8d98308c-ee14-48d6-b536-2b14305bf470.png">

so what you are seeing might be a theme related issue. What theme are you using?

**Comment by zero2webmaster** [comment]
Currently Astra. If it persists on other themes, I will let you know.

**Comment by glendaviesnz** [comment]
I am going to close this for now, but feel free to re-open it @zero2webmaster if you do notice it persisting across themes.
