### ISSUE TITLE
Zoomed out view: consider a way of adding to post editor for long posts

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#44996]
## What problem does this address?

An interesting point of feedback came up in the [seventeenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/09/15/fse-program-testing-call-17-guiding-the-gutenberg-gallery/#comment-2749): 

>I was a little surprised to see that the Zoom Out view only works in Site editing mode. I find it would be useful even when building long pages.

Since this mode is intended to be invoked during relevant moments (example https://github.com/WordPress/gutenberg/issues/44585), I wonder if there's a way to consider allowing this in the post editor in certain situations. 

## What is your proposed solution?

I'm honestly not quite sure. Perhaps an option is provided when you reach a certain character count or length or block amount (thinking about a post filled with images rather than based on words)?

cc @jameskoster for thoughts here :)

**Comment by jameskoster** [comment]
We'll get this for free when https://github.com/WordPress/gutenberg/issues/44461 is closed :)

**Comment by annezazu** [comment]
Ah true! I think the only issue is around _when_ the mode would be invoked for longer posts, since it's not meant in the long run to be a tool to toggle on/off afaik.

**Comment by jameskoster** [comment]
There are certainly situations in which the canvas should zoom out automatically, I'm not sure editing long form content qualifies though. It feels more like a situation where you'd adjust the zoom manually, based on what you're doing within the context of that post.

**Comment by annezazu** [comment]
Closing out since we have it added in the editor for 6.7!
