### ISSUE TITLE
Removing empty List block with delete key fails, leads to iOS crash

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#44990]
## Description
When attempting to remove an empty List block by pressing the keyboard delete key, the block is not removed on Android and the app crashes on iOS. 

## Step-by-step reproduction instructions
1. Add a List block to the content. 
2. Pressing the <kbd>Delete</kbd> key. 

## Expected behaviour
The List block is removed and replaced with a Paragraph block. 

## Actual behaviour
**Android:** The List block is not removed nor replaced. 
**iOS:** The app crashes. 

## Screenshots or screen recording (optional)

<details><summary>Android Screencast</summary>

https://user-images.githubusercontent.com/438664/195932209-1e240670-9eb8-4532-8ead-981d00ba37d7.mp4

</details>

<details><summary>iOS Screencast</summary>

https://user-images.githubusercontent.com/438664/195932001-8622ac2e-d0a9-45f7-84f8-ac8f387ae587.MP4

</details>

## WordPress information
- WordPress version: 6.1
- Gutenberg version: 14.3.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Geologist

## Device information
- Device: Samsung Galaxy S20, iPhone SE
- Operating system: Android 12, iOS 16.1
- WordPress app version: [1.84.0](https://github.com/WordPress/gutenberg/releases/tag/rnmobile%2F1.84.0) or soon-to-be 20.10 beta

**Comment by fluiddot** [comment]
I tested on version 20.9 and the issue can't be reproduced, so definitely this is a regression on version 21.0.

**Comment by dcalhoun** [comment]
This regression appears to have originated from #43181. I am researching further.
