### ISSUE TITLE
Add "No Follow" as an option for link settings

### ISSUE THREAD

**Issue by ChrisEdwardsCE** [WordPress/gutenberg#4499]
This is crucial for SEO. Link options currently have the open in a new window, however, it should also have the option to add No Follow (rel="nofollow") to the link. This is necessary for SEO purposes. 

![image](https://user-images.githubusercontent.com/12351483/34973768-66b48a92-fa57-11e7-85fd-5922746d69d8.png)

**Comment by joaodfmota** [comment]
I propose something like this:
![rel](https://user-images.githubusercontent.com/3788221/34997273-2e9c73b0-fac3-11e7-826c-d03ec155a900.JPG)
Because we have multiple options for [rel](https://www.w3schools.com/tags/att_a_rel.asp) Attribute

**Comment by Soean** [comment]
This option is not in WP Core, is there is a reason?
There are some plugins for this. Is it possible in Gutenberg to add this feature via plugin?
- https://wordpress.org/plugins/nofollow/
- https://wordpress.org/plugins/rel-nofollow-checkbox/
- https://de.wordpress.org/plugins/title-and-nofollow-for-links/

@joaodfmota Why not using a dropdown? There are just a few different options.

**Comment by ChrisEdwardsCE** [comment]
@Soean Yes, this was removed from core a while back, not sure the reasons why it was used. History on the nofollow tag is having nofollow meant you were sharing your "link juice" (hate that word) with that link. This meant you lost some of your PageRank as you shared with the other site. It now is more you just help boost that link you linked to as in you are vouching for it. Normally you would not vouch for a questionable link or a link to something that could be easily edited or publically commented on as it can affect your ranking if that site turns to spam. Big sites such as the NYTimes always use the nofollow tag for any links in contributor articles. 

There are plugins that add this, to my knowledge none work yet in Gutenberg. I feel this should still be a core feature but understand if it deemed to not be. It should never have been removed in the first place. 

Also, this may be a bug, but WordPress core since 4.7.4 adds the rel="noopener" tag to anything that opens a new window for security purposes. It was done for security reasons, see this thread for more info https://core.trac.wordpress.org/ticket/36809 (should I add this as a sperate bug issue)

**Comment by joaodfmota** [comment]
@Soean 
Yes, the dropdown will be better to prevent incorrect values, If the other's are relevant I really don't know 
But the SEO team always tell us to change some attr like: `noreferrer, external and nofollow`. 😄

**Comment by danielbachhuber** [comment]
Closing in favor of #4597

**Comment by juicerocket** [comment]
It's also important because Google and the FTC both require "nofollow" for any paid-for link (like blogs use, for influencer marketing). It's way too difficult to add that now, with Gutenberg. It should be a toggle option like the new window option.

**Comment by Lockcuff** [comment]
Has this issue been resolved? I am seeing quite a few bloggers getting flagged by google because they can't add the no-follow attribute easily.

**Comment by budgetsavvybride** [comment]
The fact that people have been begging for this feature for over a year is really frustrating. This is an essential and necessary add-on to the core of Gutenberg.
