### ISSUE TITLE
Save editor UI configuration to be persistent across reloads

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#450]
Per discussion in https://github.com/WordPress/gutenberg/pull/449#issuecomment-295249182, we need to save the state of various editor configurations, so they are persistent across reloads:

- Did you dismiss the sidebar? (Sidebar is open by default)
- Are you using the visual editor or the text editor?
- Did you reorder the metaboxes in the sidebar? Did you hide one? Did you collapse one?

The ability to dismiss the sidebar is a new feature. All the other options are similar to how they behave in the current editor. 

Here's a screenshot of the sidebar with all metaboxes closed, but the "Status & Visibility" box open. The little configuration panel icon at the top of the sidebar is the equivalent of "Screen Options", where you can choose which metaboxes to show.

**Comment by iseulde** [comment]
Maybe we can use the user setting API for this.
