### ISSUE TITLE
How to turn off welcome page & other plugin blocks permanently? 

### ISSUE THREAD

**Issue by synyan** [WordPress/gutenberg#45001]
Whenever I login to my site, the welcome page and other plugin blocks pops up instantly, even if I turn them off at site.
How could I turn them off permanently? I already tried a lot of ways! 
<img width="1440" alt="scn2022-10-17 10 36 35" src="https://user-images.githubusercontent.com/1881095/196077334-40c7874a-a783-4e46-b4e4-9fe89e1e7ac2.png">
<img width="745" alt="scn2022-10-17 10 37 10" src="https://user-images.githubusercontent.com/1881095/196077364-e2bdfd42-309e-41b0-a476-e5fac174ff03.png">

**Comment by ramonjd** [comment]
> Whenever I login to my site, the welcome page and other plugin blocks pops up instantly, even if I turn them off at site.
How could I turn them off permanently? I already tried a lot of ways!

As far as I know the welcome guide will appear until it's been dismissed. 

How are you trying to turn them off? There is no UI toggle as far as I'm aware. 

There are ways to turn it off programmatically. For reference. see the preferences package's API: https://github.com/WordPress/gutenberg/blob/trunk/packages/preferences/README.md

If you'd just like to turn if off in the browser you can run the following in the console:

```js
wp.data
	.dispatch( 'core/preferences' )
	.set( 'core/edit-post', 'welcomeGuide', false );
```

Or are you expecting something else?

**Comment by talldan** [comment]
@synyan What WordPress version and Gutenberg plugin version are you using?

In older versions of the plugin it will be shown again when you clear bowser data. In more recent versions of the plugin and the upcoming WordPress 6.1 the preferences will be saved to the database, so it shouldn't ever come back again.

**Comment by synyan** [comment]
Hi @talldan 
My WordPress' current version: 6.0.3.
Thank you!

**Comment by talldan** [comment]
It'd be good to know if you still have the issue after updating to WordPress 6.1 (which was released yesterday).

**Comment by synyan** [comment]
Hi talldan, I think the issue may have been solved since I don't see the welcome page again, and thankfully panel buttons are off, even after I clear my browser cache. I will of course keep an eye on it see if it happens in the future. Thank you for your help.
