### ISSUE TITLE
Editing custom fields with Gutenberg and loading the editor on demand

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#4502]
Watching Matt's presentation about the State of Word in WordCamp US 2017, it left me with the idea that the ultimate plan for Gutenberg is to allow it to be used everywhere.

I was wondering if it is or if it will be possible at some time in the future to edit custom fields using Gutenberg.

Also what about loading Gutenberg on demand? Will it be possible to load Gutenberg outside the post edit page, just like it's currently done with the native editor?

**Comment by gziolo** [comment]
> Gutenberg is more than an editor. While the editor is the focus right now, the project will ultimately impact the entire publishing experience including customization (the next focus area).

Sky is the limit :)

**Comment by mcsf** [comment]
Editing custom fields is possible now thanks to meta attributes. See @youknowriad’s concept plugin:

https://github.com/youknowriad/gcf
