### ISSUE TITLE
Navigation: Improve readability by refactoring the logic around fallbacks

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#45039]
The navigation block does different things depending on the state of the user's site - do they have any wp_navigations? Do they have a classic menu? etc. It's very hard to understand this behaviour by reading the code. We should refactor it so that these direction switches are visible in code. For instance legacy placeholder, default behavior with uncontrolled blocks etc.

**Comment by getdave** [comment]
This has been completed in the work around fallbacks in the 6.3 cycle. See https://github.com/WordPress/gutenberg/pull/50032
