### ISSUE TITLE
Navigation block: requires double clicking to select/edit when using page list

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#45083]
### Description

The "click to edit" overlay https://github.com/WordPress/gutenberg/issues/35079 seems to be broken causing one to have to double click in quick succession in order to edit a navigation block. This seems specific to a post theme switch from a classic theme when the page list fallback is in place as I can't replicate when a "regular" navigation block is in place. cc @getdave

### Step-by-step reproduction instructions

1. Use 6.1 RC2 on a site.
2. Convert from a classic theme to block with one menu in place.
3. Try to select and edit the navigation block.

If you need a test site to make it easier, you can spin up a site with https://app.instawp.io/launch?t=fse-call-for-testing-17  from the last call for testing for the FSE Outreach Program. This will give a classic site. Uninstall Gutenberg, update to 6.1 RC2 via beta tester, then switch to TT3. 

### Screenshots, screen recording, code snippet

Here's a video showing the problem just after switching from a classic to block theme and needing to convert the page list links to blocks:

https://user-images.githubusercontent.com/26996883/196560674-2238b8a3-9935-418d-95c9-65a757e70204.mov

I can't replicate after converting to links:

Uploading click to edit post conversion.mov…

### Environment info

- WordPress 6.1 RC2
- TT2
- No Gutenberg
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
Tested and confirmed this is a bug on RC2. You cannot select the Page List _at all_ without double click.

**Comment by getdave** [comment]
I can confirm that turning off `Overlay` causes this issue to disappear. Therefore I believe this is the overlay interfering.

**Comment by getdave** [comment]
<img width="1276" alt="Screen Shot 2022-10-19 at 09 56 02" src="https://user-images.githubusercontent.com/444434/196645094-2ad8f7d2-56da-477d-8b65-9c5f8eddb668.png">

Removing the `pointer-events` from the wrapper fixes this. We'll need to be aware of consequences of doing this. I'll spin up a PR.

**Comment by getdave** [comment]
Ok here I am testing on Gutenberg `trunk`. 

- initially I cannot click on the Page List in the canvas to select it
- then I toggle the overlay to `off`.
- now I _can_ click in the canvas to select.
- now I toggle the overlay _back_ to `Mobile` again.
- now I _can_ click in the canvas to select (this is in contrast to the initial experience).

Why is this happening? What changes? Diving deeper....


https://user-images.githubusercontent.com/444434/196675230-a664b276-2d0a-4e48-b88a-d6446a531c46.mp4

**Comment by getdave** [comment]
I can observe the same behaviour using the following markup:

```
<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:page-list /--></div>
<!-- /wp:group -->
```

Therefore I don't _think_ this is specific to the Navigation block but rather the Page List block.

**Comment by getdave** [comment]
Narrowing this down some more. It seems that the Page List block as an inner block is not receiving the `focusin` event under certain conditions. 

This is causing the `onFocus` _callback_ of [`useRefEffect`](packages/block-editor/src/components/block-list/use-block-props/use-focus-handler.js) not to run for the Page List block. Instead it just runs for the wrapper block.

However, some changes in the editor seem to "trigger" the focus to work as you'd expect for the Page List. One example is simply going in and then out of `Code Editor` view. After doing that the focus works to allow you to select the inner Page List directly. See video:


https://user-images.githubusercontent.com/444434/196728549-766e5598-dac0-4818-a580-1b0bd3196662.mp4

My current thinking is that something is blocking `focusin` from firing. Is it some piece of DOM overlay or a quirk of the JS... 🤔

**Comment by getdave** [comment]
Going deeper. The `focusin` handler is not registered on the Page List `<ul>` element. It appears is is removed by the cleanup function returned by `useFocusHandler`.

### Before toggling Code Editor mode
<img width="1178" alt="Screen Shot 2022-10-19 at 16 22 11" src="https://user-images.githubusercontent.com/444434/196734572-c405a370-010f-4ff0-9b71-c82b816c4738.png">

Notice that the only event handler is that on the _parent_ Group block. 


### After toggling Code Editor mode

Notice that the new handle on the `<ul>`.
<img width="1266" alt="Screen Shot 2022-10-19 at 16 24 26 (1)" src="https://user-images.githubusercontent.com/444434/196735382-6b9c20e6-b256-459a-a8b8-bb42396a6985.png">

**Comment by getdave** [comment]
I now believe the following

- the clean up function of `useFocusHandler` is running for the Page List node.
- `useRefEffect` will run it's cleanup if the `ref` changes.
- the "ref" is passed via `useMergeRefs` here (notice that `useFocusHandler` is one of the hooks):
https://github.com/WordPress/gutenberg/blob/88a1f7ae18bea3a13f6d1e507e3c25090b76cb08/packages/block-editor/src/components/block-list/use-block-props/index.js#L124-L140
- by process of elimination if I removed `useIntersectionObserver` from the merged refs the `ref` remains stable and the thus the callback of `useFocusHandler` does not fire. This means the focus functionality works for Page List.

Therefore I believe the issue may lie in `useIntersectionObserver` or some quirk of how Page List interacts with that hook.

EOD for me here but can pick up again tomorrow.

**Comment by annezazu** [comment]
Amazing job continuing to sleuth. Thank you.

**Comment by getdave** [comment]
I think I now have a fix at https://github.com/WordPress/gutenberg/pull/45143. Full explanation in that PR.
