### ISSUE TITLE
Focus mode: Unable to scroll when editing a longer template part

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#45084]
### Description

When using the focus mode, I'm unable to scroll down when trying to edit a comments block in isolation. I'm also noticing that more content shows up between modes (site editor vs focus mode) - I'm assuming that's to provide filler content but it's a bit of a confusing UX regardless. 

### Step-by-step reproduction instructions

1. Use 6.1 RC 2.
2. Head to Appearance > Editor.
3. Add the comments block.
4. Select the comments block and choose "edit" in the block toolbar.
5. Notice you can't scroll down or move around in general except by selecting things in list view. 

### Screenshots, screen recording, code snippet

Video showing inability to scroll:

https://user-images.githubusercontent.com/26996883/196561515-4c04030b-23eb-438c-a291-0858dace2025.mov

Screenshot of site editor showing no comments:

<img width="923" alt="Screen Shot 2022-10-18 at 4 09 15 PM" src="https://user-images.githubusercontent.com/26996883/196561756-86ed0806-e623-4b91-99cb-a142ff9d8e5d.png">

Screenshot of focus mode showing 3 comments (I'm guessing as filler content for what one would see if there were comments but still):

<img width="1149" alt="Screen Shot 2022-10-18 at 4 09 57 PM" src="https://user-images.githubusercontent.com/26996883/196561822-0894e01d-25ed-4c69-ae61-973c51b5c849.png">

### Environment info

- WordPress 6.1 RC 2
- TT3
- No GB
- Chome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
cc @Poliuk for awareness.

**Comment by carolinan** [comment]
I can reproduce this.
Small note: In TT3, the "comments block" in this template is a template part, which is why it has the Edit option.

**Comment by michalczaplinski** [comment]
I just took a look at this and it's not specific to the Comments block. I can reproduce the problem when trying to edit the Footer template as well:

https://user-images.githubusercontent.com/5417266/196780285-b0f7c687-983f-4a4a-9c36-df3ba7e83581.mp4

The problem seems to be this CSS rule:

https://user-images.githubusercontent.com/5417266/196781773-0806d2db-f6e1-4dce-a7c4-e60bf9130ba4.mp4

**Comment by michalczaplinski** [comment]
I will try to debug this further

**Comment by michalczaplinski** [comment]
There are two additional considerations here:

1.  Removing the `overflow` on the `<div class="edit-site-visual-editor is-focus-mode">` element is probably not the UX that we want. I **think** that the inner container is the one that should be scrolling but I'm not 100% sure.

2. I think it's very confusing that there is a "Comments" template part as well as a "Comments" block:

   <img width="389" alt="Screenshot 2022-10-19 at 14 26 06" src="https://user-images.githubusercontent.com/5417266/196785432-ac613e01-82b7-4e07-845e-d4f172450440.png">


   I would have been quite puzzled if @carolinan hadn't commented that this is actually a template part.

**Comment by carolinan** [comment]
Pinging @mikachan in case there is time to rename the comments template part in TT3 to reduce confusion.

**Comment by annezazu** [comment]
Renaming this back to template part rather than template! Yes, I did see this was a template part but foolishly thought it was isolated to the Comments block implementation for some reason. Thanks for testing more to find out the deeper problem.

**Comment by michalczaplinski** [comment]
I see out that the `overflow: hidden` was added in https://github.com/WordPress/gutenberg/pull/43332 by @ciampo so we should not remove it. Perhaps he has an idea on how to handle this better? 

I've tried fiddling with `overflow` and `height` of `<iframe>` of the template editor but to no avail so far.

**Comment by ciampo** [comment]
> I see out that the overflow: hidden was added in https://github.com/WordPress/gutenberg/pull/43332 by @ciampo so we should not remove it. Perhaps he has an idea on how to handle this better?

I haven't really worked on the site editor myself, I opened that PR while working on [polishing the Popover component](https://github.com/WordPress/gutenberg/issues/42770). All I know is that `overflow:hidden` rule was necessary to prevent the scrolling bug highlighted in https://github.com/WordPress/gutenberg/pull/43332.

Perhaps you may remove the `overflow: hidden` rule only when editing templates?

In general, regardless of the fix, let's make sure we test it extensively — these visual / layout issues are often not caught by e2e test.

**Comment by michalczaplinski** [comment]
I've added a tentative fix in https://github.com/WordPress/gutenberg/pull/45176

Which CSS Wizard could I ping to review this to make sure it's a correct fix? 😃

**Comment by michalczaplinski** [comment]
This should be fixed for good in #45189 now!
