### ISSUE TITLE
On the "loading source..." issue at the 'Story' tab for some components at Storybook Tool

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#45095]
_This issue was originally detected and reported by @bph on a private Slack channel_

### Description

At the Storybook Tool, when clicking on a component from the left menu,  and in the canvas view there's sometimes a story, and sometimes there's a `...loading story` message which never disappears showing the final output. 

![image](https://user-images.githubusercontent.com/422576/196637427-9a6e386f-6503-4e4e-8311-c5a02067cb2d.png)

This seems to be a bug in Storybook not being able of showing TypeScript stories yet https://github.com/storybookjs/storybook/issues/17275

### Possible Solutions

- Remove `Story` for all components 
- Add a warning for the users explaining this issue
- Fix the error somehow

### Step-by-step reproduction instructions

1. Go to Storybook Tool
2. Go to `DateTimePicker` component (`Default` version)
3. Go to `Canvas` Tab
4. Go to `Story` Tab

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mirka** [comment]
As a general fix for this, I'm considering removing the Story panel for all components and adding a prominent link somewhere to the component's source folder on GitHub. That way, people can  easily browse the source code as well as the story code.

**Comment by bph** [comment]
Thanks @juanmaguitar for creating an issue here as well.
