### ISSUE TITLE
UnitControl: normalize wrapper classnames

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#45094]
As discussed in https://github.com/WordPress/gutenberg/pull/41860#discussion_r996049365, we should try to normalize the way `UnitControl` applies the `className` prop to its internal markup — in particular, the general expectation is that `className` applies to the outer wrapper (which is currently not the case).

This refactor would also include changes to the recently introduced `__unstableWrapperClassName` prop.

One option that could be worth exploring could be to remove the outer wrapper altogether, which would allow us to simplify the styles with minimal disruption.

**Comment by aaronrobertshaw** [comment]
I have a PR up exploring the removal of the UnitControl's outer wrapper in https://github.com/WordPress/gutenberg/pull/45139. Depending on any feedback for it, it might be better to be rolled into https://github.com/WordPress/gutenberg/pull/41860

**Comment by aaronrobertshaw** [comment]
Closing this as complete now that #41860 has been merged.
