### ISSUE TITLE
Templates: make blocks available for further processing

### ISSUE THREAD

**Issue by wsydney76** [WordPress/gutenberg#4509]
When evaluating composing a template using standard blocks, you will see some  limitations. One of them is that block data, once entered, disappears in a black hole and is not available for further processing.

Just writing down some random thougths without a concrete requirement, so they will not get lost after dropping the idea.

## Introduce a block key

First of all everything will fail unless there is something like a block key/id/name to specify the semantic of the block. Which one is the author, which one is the description?

## Creating an archive page

Implementing an archive page presenting all your books, with title, image, author, teaser.

To do that you will need to extract the needed blocks. In pseudo code:

the_title();
the_block('author'); // output rendered content

$img = get_block('cover');
--  output thumbnail version of $img['id'] --

$teaser = get_block('teaser');  //
echo '&lt;p&gt;' .  $teaser['attributes']['content'] . '&lt;/p&gt;'  

The saved html may be impossible to use because it may contain styling  options or markup that is useless in this context. So the attribute value has to be extracted out of the html snippet? 

Not even thinking of searching of sorting by author...

## Rest API

Oh well. Can access raw data only with authorization, still useless because of proprietary data format. Needs a JSON representation of block data.

## Clients quote

> Wow. WordPress and Gutenberg is the first system i ever saw that cannot use it's own data.

**Comment by youknowriad** [comment]
Hi!,

We do have functions like `gutenberg_parse_blocks` parsing the block content server-side.
This issue is not very actionable and I'm inclined to close it.

**Comment by wsydney76** [comment]
@youknowriad yes, `gutenberg_parse_blocks` can be used instead of the fantasy function get_blocks(), but it does not address the other issues. 

eg. iterating through parsed blocks without something like a key would require to trust a position (first paragraph = author, second = description), which is bad practice. 

Personally i am fine with closing the issue, as the client already dropped WordPress because of this limiations (and the, in their eyes, unacceptable transition path).

But there should still be a comprehensive  answer to the label @danielbachhuber added: How Do I ???

**Comment by youknowriad** [comment]
@wsydney76 Persisted block Ids have been discussed and rejected in core-meeting https://wordpress.slack.com/archives/C02QB2JS7/p1511374462000036

**Comment by wsydney76** [comment]
@youknowriad Thank you for looking up, but i don't have access to slack. 

And i don't need it, because i am leaving the WordPress universe soon.  So thank you for all your work and efforts pushing the project forward, which is obviously not always easy.
