### ISSUE TITLE
Deactivating core patterns does not seem to work as expected.

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/gutenberg#45109]
### Description

In the section on [removing or hiding block patterns](https://developer.wordpress.org/themes/advanced-topics/block-patterns/#removing-or-hiding-block-patterns) in the Theme Developer handbook on block patterns, the ability to disable core patterns is described:

> remove_theme_support( 'core-block-patterns' ); – removes all core patterns and should be hooked to either the init or the [after_theme_setup()](https://developer.wordpress.org/reference/hooks/after_setup_theme/) hooks.

However, when attempting to do this in a block theme, it does not appear to work.

### Step-by-step reproduction instructions

1. Install and activate a block theme, in this case, Twenty Twenty Two will suffice.
2. Remove all theme patterns, by removing/commenting out this line of code at the bottom of functions.php `require get_template_directory() . '/inc/block-patterns.php';`
3. Disable the loading of remote patterns from the Block Pattern directory by adding this line of code to functions.php `add_filter( 'should_load_remote_block_patterns', '__return_false' );`
4. Finally, remove core patterns as described in the documentation (example code below)
5. Edit a template or post/page and insert a pattern. It is expected that no patterns should exist in this list, but there are still a few button and query patterns available.

Code used to disable core patterns
```
add_action('init', 'twentytwentytwo_deactivate_core_patterns');
function twentytwentytwo_deactivate_core_patterns(){
	remove_theme_support('core-block-patterns');
}
```

Note, this happens without the Gutenberg plugin installed, with it installed, more patterns are available in the pattern inserter.

### Screenshots, screen recording, code snippet

This is what is visible in the pattern inserter once the code changes above have been applied.

https://user-images.githubusercontent.com/180629/196684165-e1e4fdce-90c0-43e3-a45d-5972477b30f7.mp4

### Environment info

- WordPress version 6.0.3
- macOS Monterery
- Brave browser
- Gutenberg not active for the initial tests

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
You might need to bump the priority of your action. 

Without specifying, the default is `10`. See: https://developer.wordpress.org/reference/functions/add_action/


Does this work?

```php
function twentytwentytwo_deactivate_core_patterns(){
        remove_theme_support('core-block-patterns');
}

add_action('init', 'twentytwentytwo_deactivate_core_patterns', 1);
```

**Comment by jonathanbossenger** [comment]
Aha, thanks @ramonjd that was it. I'll see if I can get the docs updated to include that info. Closing.
