### ISSUE TITLE
Global Styles: Font appearance options do not match provided weights in custom fonts

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#45136]
## Description

This issue stems from the discussion in https://github.com/WordPress/gutenberg/issues/45086#issuecomment-1283224355.

Currently, the Font Appearance control offers [options for all potential font weights](https://github.com/WordPress/gutenberg/blob/7796466b8a817477dd65c6fd6653c2259b62d828/packages/block-editor/src/components/font-appearance-control/index.js#L19), regardless of whether a theme's bundled fonts provide those weights.

While browsers will make a best guess at approximating a selected font weight if the font doesn't provide the selected option, it would be nice if we could refine our control to reflect better what is available for any given font. 

This might help reduce confusion and friction for end users of Global Styles.

## Original Comment

> This might be one for folks working more closely on the theme development side of things, but I notice that in the [TwentyTwentyThree theme.json file](https://github.com/WordPress/twentytwentythree/blob/trunk/theme.json#L111), only particular font weights appear to be included in the bundled fonts (I assume to limit the size of fonts that are loaded for the theme?). E.g. DM Sans loads 400 and 700 weights, IBM Plex Mono loads 300, 400, and 700, Source Serif Prop, only 200 and 900, etc. (edit: that last one appears to be a variable weight font, though, so it probably doesn't have the same problem?)
> 
> Whereas in [the font appearance control](https://github.com/WordPress/gutenberg/blob/7796466b8a817477dd65c6fd6653c2259b62d828/packages/block-editor/src/components/font-appearance-control/index.js#L19), all potential weights are presented in the UI controls. Ideally, I wonder if it would make sense for the appearance controls to (somehow) only show the options of fonts that are loaded? The problem with trying to do that, though, is that it mightn't be possible for the block editor to know absolutely which are or are not available, particularly for themes that load fonts outside of theme.json 🤔

**Comment by mikachan** [comment]
I think this issue was fixed with https://github.com/WordPress/gutenberg/pull/61915, so I'm going to close it, but please re-open if necessary.
