### ISSUE TITLE
[Block Library - Video]: Update tracks editor icon

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#45148]
Video blocks use an icon with inconsistent size for track editor. We should update it.

<img width="665" alt="Screenshot 2022-10-20 at 12 08 43 PM" src="https://user-images.githubusercontent.com/16275880/196908363-d219734f-cf1b-4750-996f-b0b4ceedb2a3.png">

--cc @jasmussen @jameskoster

**Comment by jameskoster** [comment]
I can't find it in the icon library, seems like it might be a Dashicons hangover or something custom. 

Before thinking about a new icon, is there an existing one we might use? Pre-formatted might be an option:

<img width="254" alt="Screenshot 2022-10-20 at 12 15 11" src="https://user-images.githubusercontent.com/846565/196934258-9a71abf4-a6d1-4876-bd01-96ebd949e1ee.png">

**Comment by ntsekouras** [comment]
>I can't find it in the icon library, seems like it might be a Dashicons hangover or something custom.

It's a [custom one](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/video/tracks-editor.js#L42).

**Comment by jasmussen** [comment]
How about we use the new "Caption" icon for it?

<img width="481" alt="Screenshot 2022-10-24 at 13 10 10" src="https://user-images.githubusercontent.com/1204802/197512928-1c399ef1-d42a-47a3-8858-4d992fd2419e.png">

The 2nd icon right after Align.

**Comment by ntsekouras** [comment]
>How about we use the new "Caption" icon for it?

We can't because we added this `caption` handling to video blocks as well 😄

**Comment by jasmussen** [comment]
Oh that's right! How about this one, CC for closed captions?

<img width="386" alt="Screenshot 2022-10-24 at 13 49 49" src="https://user-images.githubusercontent.com/1204802/197519098-722ebc44-6fec-4316-a5d2-697e761eb162.png">

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="enable-background:new 0 0 24 24" xml:space="preserve"><path d="M19 5H5c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm.5 12c0 .3-.2.5-.5.5H5c-.3 0-.5-.2-.5-.5V7c0-.3.2-.5.5-.5h14c.3 0 .5.2.5.5v10zM8.2 10.3c.1-.3.4-.5.7-.5.2 0 .3 0 .4.1.1 0 .2.1.3.2.1.1.1.2.2.3 0 .1.1.3.1.4l1.3-.3c-.1-.3-.2-.5-.3-.7-.1-.2-.3-.4-.4-.6-.2-.1-.4-.2-.7-.3-.2-.1-.5-.1-.8-.1-.9 0-1.5.2-1.9.8-.4.6-.6 1.4-.6 2.4s.2 1.8.6 2.4c.4.6 1 .8 1.9.8.3 0 .6 0 .9-.1.3-.1.5-.2.6-.4.2-.2.3-.4.4-.6.1-.2.2-.5.3-.7l-1.3-.3c-.1.3-.2.5-.3.7-.1.2-.4.3-.7.3-.4 0-.6-.1-.8-.4-.1-.3-.2-.7-.2-1.2v-1.1c0-.5.1-.8.3-1.1zm6.4 0c.2-.3.4-.4.8-.4.2 0 .3 0 .4.1.1 0 .2.1.3.2.1.1.1.2.2.3 0 .1.1.3.1.4l1.3-.3c-.1-.3-.2-.5-.3-.7-.1-.2-.3-.4-.4-.6s-.5-.3-.8-.4c-.2-.1-.5-.1-.9-.1-.8 0-1.5.3-1.9.9-.4.6-.6 1.4-.6 2.4s.2 1.8.6 2.4c.4.6 1 .8 1.9.8.3 0 .6 0 .9-.1.3-.1.5-.2.6-.4.2-.2.3-.4.4-.6.1-.2.2-.5.3-.7l-1.3-.3c-.1.3-.2.5-.3.7-.1.2-.4.3-.7.3-.4 0-.6-.1-.8-.4-.2-.3-.2-.7-.2-1.2v-1.1c.1-.6.2-.9.4-1.2z"/></svg>
```

**Comment by jameskoster** [comment]
I considered that one too, but since text tracks is not restricted only to closed captions I wasn't sure if it made sense? 🤔

**Comment by jasmussen** [comment]
Indeed, this is the description: 

> Tracks can be subtitles, captions, chapters, or descriptions. They help make your content more accessible to a wider range of users.

How do those chapters or descriptions show up? I will admit to not having used this feature before. If it's all text overlaid on the video, I think it's fine to call it closed captions.

**Comment by jameskoster** [comment]
The types are listed as:

> * Subtitles: Translations of the dialogue in the video for when audio is available but not understood. Subtitles are shown over the video.
> * Captions: Transcription of the dialogue, sound effects, musical cues, and other audio information for when the viewer is deaf/hard of hearing or the video is muted. Captions are also shown in the video.
> * Descriptions: Text descriptions of what’s happening in the video for when the video portion isn’t available because the viewer is using assistive technology. Descriptions are read by a screen reader or turned into a separate audio track.
> * Chapters: Chapter titles that are used to create navigation within the video. Typically they’re in the form of a list of chapters that the viewer can click on to go to a specific chapter.
> * Metadata: Tracks that have data meant for javascript to parse and do something with. These aren’t shown to the user.

I'm not entirely sure how they appear though. I tried to attach this [sample vvt](https://gist.github.com/samdutton/ca37f3adaf4e23679957b8083e061177) file to a video and nothing happened on the frontend 🤔

**Comment by jasmussen** [comment]
Thanks for diving in. The first three, subtitles, captions, descriptions, they definitely sound like subtitle tracks. But chapters and "metadata" are definite the latter — just metadata. Which I suppose you could categorize subtitles as, as well. In that light, and to differentiate from the `figcaption` caption button, it seems a generic metadata icon would be in order. But there aren't any real good icons to represent that. 

One option could be to show a generic "add" icon?

<img width="389" alt="Screenshot 2022-10-25 at 11 52 53" src="https://user-images.githubusercontent.com/1204802/197743188-029c90a0-2b6c-400a-a894-9c58866f3a37.png">

After all, you add a track.

Another option could be the attachment icon?
<img width="385" alt="Screenshot 2022-10-25 at 11 53 10" src="https://user-images.githubusercontent.com/1204802/197743242-f07058c2-d18c-482b-82da-4facc5f1726c.png">

Perhaps a stretch.

A third option is to just go text-only? After all, there's room for this particular block toolbar:

<img width="768" alt="Screenshot 2022-10-25 at 11 55 33" src="https://user-images.githubusercontent.com/1204802/197743452-66599e11-5584-4034-84f5-fa273dc04c50.png">

**Comment by jameskoster** [comment]
> After all, you add a track.

Possibly a rabbit hole, but you also add a caption. The + could open a menu including options to add captions and text tracks. However, it doesn't work so well for removing.

Perhaps the text button is the way to go for now.
