### ISSUE TITLE
Make "Manage reusable blocks" link match "Explore all patterns"

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#45155]
In the Reusable Blocks tab of the Inserter we find:

<img width="350" alt="Screenshot 2022-10-20 at 11 50 13" src="https://user-images.githubusercontent.com/846565/196929223-f19f71f6-7f88-4110-b410-c161176b60b1.png">

The "Manage reusable blocks" link is a bit plain. It might be better if it stylistically matched the "Explore all patterns" button from the Patterns tab:

<img width="350" alt="Screenshot 2022-10-20 at 11 51 16" src="https://user-images.githubusercontent.com/846565/196929480-1a35f140-45cb-4999-a62d-0d8db248e3b3.png">

**Comment by dsas** [comment]
Taking a look at this 👀
