### ISSUE TITLE
Style variations are not being saved if the sidebar isn't on the variations screen

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#45165]
### Description

<sub>Originally reported by @dsas in https://github.com/Automattic/wp-calypso/issues/68707 but moved it here after realizing this is a Gutenberg issue.</sub>

When changing to a non-default style variation, the choice is not saved when clicking save if the variation screen is navigated away from.

### Step-by-step reproduction instructions

- Make sure you're using the latest version of Gutenberg (14.3.1), since the issue is not reproducible in older versions (e.g. 14.0.2)
- Activate a block theme such as Twenty Twenty-Two
- Open the site editor (`wp-admin/site-editor.php`)
- Click Browse styles
- Choose a non-default variation, i.e. any variation except the top left one
- Notice the preview in the main part of the screen changes to match the selected variation
- Click the '<' next to 'Browse styles' to go back in the sidebar
- Press Save
- Observe how the sidebar very quickly (it's just a flash) changes to the Browse styles page and then changes back.
- Observe how the Save button is not disabled
- Visit the frontend and observe how the original variation is still being used.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1233880/196980970-78ee91f3-cef3-4092-8b4f-3ff7cfd54212.mov

### Environment info

- WordPress: 6.0.3
- Gutenberg: 14.3.1
- Theme: Twenty Twenty-Two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @mmtr

I followed the reproduction steps and could not reproduce the issue using WP 6.1 with and without Gutenberg 14.5 RC. Tested using 2022 and 2023 themes.

Can you confirm that you are still seeing the bug?

**Comment by mmtr** [comment]
You're right @Mamaduka. Seems the issue was solved in Gutenberg 14.4.0 since I cannot reproduce it on that version (but it's still present in 14.3.1).

**Comment by Mamaduka** [comment]
Thanks for the update, @mmtr!
