### ISSUE TITLE
Toolbar on mobile has transparent background

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#4517]
When using v2.0 on mobile, the background becomes transparent at the point where the buttons end.

On desktop that makes sense (and looks good), but on mobile the bar extends across the full width, causing block content below it to show through. So it would need a white background (or fully copy the styling of the desktop version of the toolbar).

![img_1222](https://user-images.githubusercontent.com/6073772/34991931-a97569fe-facb-11e7-807f-19243f3ff82e.PNG)

**Comment by karmatosed** [comment]
This will be fixed when we change the toolbar in https://github.com/WordPress/gutenberg/issues/4077. For now, lets close this and focus there.
