### ISSUE TITLE
Hiding and unhiding the toolbar is confusing on mobile

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#4518]
## Issue overview
When using v2.0 on mobile, the toolbar disappears when you start typing. That was intentional, which I can agree is nice in terms of distraction-free writing, and on desktop it works, but on mobile the behavior is erratic and unpredictable. Some of this is not directly related to the toolbar, but still contributes to make this a confusing operation.

## Steps to reproduce
- Start a new post on a smartphone.
- Tap to focus the default paragraph block > toolbar appears.
- Start typing > toolbar disappears.
- Tap the block > nothing happens. (or if keyboard is dismissed, it opens again).
- Tap another block > new block is selected, still no toolbar.
- Tap AGAIN > now the toolbar comes back (but does not summon the keyboard).

Video of the behavior: 
https://drive.google.com/file/d/1lrB8qncLooohe98myaYo9d1Jh8ggZj5B/view?usp=sharing

## Expected behavior
I don't really know where to start on this one... I'll talk to the other designers here this week, see if we can make sense of it, but any suggestions are welcome.

**Comment by karmatosed** [comment]
We already have an issue to fix the toolbar on mobile. This is covered in https://github.com/WordPress/gutenberg/issues/4077 and closing this as it covers the issue.
