### ISSUE TITLE
Consider renaming or removing "Areas" in dropdown

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#45181]
## What problem does this address?

Currently, the dropdown when in the site editor shows a section titled "areas" when referring to template parts. This is a bit confusing as "areas" is not a well defined term and it's referring to template parts: 

![image (27)](https://user-images.githubusercontent.com/26996883/197085087-0f0513fc-13e4-42fb-b375-d377f6fe72d2.png)

I understand that each template part sets an assigned "area" and carries semantic meaning but I'm a bit confused around the naming of "areas" in the dropdown. 

## What is your proposed solution?

Rename "areas" to something like:
- Parts
- Template Parts
- Sections (inspired by https://github.com/WordPress/gutenberg/issues/39281)
- Synced Blocks (inspired by https://github.com/WordPress/gutenberg/issues/43598)

cc @jameskoster  for context here since afaik you've worked on that dropdown!

**Comment by talldan** [comment]
Naming it 'Template Parts' might lead to confusion around why all template parts aren't shown (only root-level template parts are). It could also be 'Template Part Areas', but that feels a bit verbose.

If it is changed it'd be good to also consider the other parts of the UI that use this term:

Advanced block inspector section:
![Screen Shot 2022-10-21 at 11 34 24 am](https://user-images.githubusercontent.com/677833/197105892-8106c350-c436-42e9-a35c-156e1e01b5df.png)

The modal shown when converting blocks to a template part:
![Screen Shot 2022-10-21 at 11 35 43 am](https://user-images.githubusercontent.com/677833/197105917-48e4c6b7-378a-406e-bb14-67b239173968.png)

As a side note, I'd be interested to know how many users find that dropdown in the top bar useful. I personally always forget that it exists.

**Comment by jameskoster** [comment]
The purpose of the feature is to highlight template parts within the document that have semantic meaning. So we should probably stay away from more generic labels like Sections or Synced blocks. 

> As a side note, I'd be interested to know how many users find that dropdown in the top bar useful

I often use the dropdown to clear customizations, but never to navigate template parts. List View feels like a more intuitive destination for this kind of activity. Obviously that's subjective, but if the general consensus is that this feature is never used, perhaps we could consider removing it?

**Comment by annezazu** [comment]
>Obviously that's subjective, but if the general consensus is that this feature is never used, perhaps we could consider removing it?

I'd be curious if it would be missed too :)

**Comment by MadtownLems** [comment]
We're using a classic theme and are excited to add Template Parts now that 6.1 is here. In our case, does this dropdown even do anything at all? We certainly can't figure out what it's supposed to be accomplishing and is just confusing to our users.

**Comment by annezazu** [comment]
@MadtownLems this dropdown when looking solely at template parts, would allow you to change the semantic meaning of the template part (general, footer, header). I can totally see how this is just confusing to folks!

**Comment by MadtownLems** [comment]
@annezazu Unless I'm misunderstanding something (totally possible!), this dropdown has absolutely no impact or bearing in the case of traditional themes that make use of Template Parts, correct?

All of our Template Parts are registered by our theme. Giving them a new "Area" seems to have no effect, as far as I can tell. (And even if it did, it seems like users shouldn't be able to re-assign Template Parts to a different area)

**Comment by annezazu** [comment]
That's correct ^ @Mamaduka -- since you implemented the template parts in classic themes, I wonder if there's a way, for now, to remove this dropdown from that experience. As @MadtownLems points out, it doesn't really make much sense to have and I wouldn't want to wait on this larger decision about the dropdown to be made in order to move this forward.

**Comment by Mamaduka** [comment]
That makes sense, I will create PR shortly for hiding the dropdown.

**Comment by annezazu** [comment]
Noting more feedback to consider as a [part of the nineteenth call for testing](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2830): 

>The title area at the top makes no sense to me. Why can’t I select between templates there? Why when I select a header or footer in the title area I can’t get out of the header or footer in the title area, but from the list area on the left?

Curious how/if this can evolve as browse mode does as well as it does seem to be less and less relied upon.

**Comment by Mamaduka** [comment]
This was resolved via #48490.
