### ISSUE TITLE
As a user I want the navigation block to fallback to the best possible default

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#45199]
Issue tracking Navigation block playwright test for this user story.

## Tests
- default to my only existing menu https://github.com/WordPress/gutenberg/pull/47744
- default to my most recently created menu 
- default to the only existing classic menu if there are no block menus https://github.com/WordPress/gutenberg/pull/47867
- default to a list of pages if there are no menus at all #45070

**Comment by scruffian** [comment]
Can we close this one?

**Comment by MaggieCabrera** [comment]
it's still missing 2 tests!

default to my most recently created menu
default to the only existing classic menu if there are no block menus (the one I'm working on right now)

**Comment by MaggieCabrera** [comment]
Now we can close!
