### ISSUE TITLE
Block ellipsis menu opens below the toolbar

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#4519]
When opening the ellipsis menu on a block early in the page, and if that ellipsis menu contains a long list of options, it renders below the toolbar.

<img width="872" alt="screen shot 2018-01-16 at 10 57 57" src="https://user-images.githubusercontent.com/6073772/34997683-4df2fa1c-fadd-11e7-8883-1a6e32016ace.png">

## Expected behavior
Render it above all other UI.

**Comment by karmatosed** [comment]
Shouldn't we just flip it like we do on other UI elements and have dropping from the ellipsis in this case?

**Comment by hedgefield** [comment]
Yeah that makes sense, but maybe it's also a good idea to give it a higher z-index regardless to make sure it's always fully visible? There probably isn't any UI that needs priority over this one in this usecase.

**Comment by bobbingwide** [comment]
A higher z-index will only partially help. The item I want is still not reachable. 
![image](https://user-images.githubusercontent.com/2474435/35793886-57eb08ca-0a4b-11e8-91b8-d7e1a2076f2b.png)

Aside: I can use cursor movement keys to get to the first set of menu items. But a novice user would have no idea about this.

PS: As a novice myself, I have no idea how to use cursor movement keys to switch between the top section and the bottom section of the menu. The bottom section being the only part we see in this screen capture, but it doesn't have focus.

**Comment by chriskmnds** [comment]
Hey folks, one thing to keep in mind with "just flipping" this to the bottom is that we may end up clipping items from the bottom if the menu/popover happens to overflow in both top/bottom directions. It looks like the logic that determines the positioning is right [here](https://github.com/WordPress/gutenberg/blob/master/components/popover/index.js#L205) actually. So we can easily account for the top bar's height in `overflowTop`, and it will always flip (you can try with subtracting an extra 1000 from line [204](https://github.com/WordPress/gutenberg/blob/master/components/popover/index.js#L204) to see this), but that won't fix it as we'd have clipping from the bottom. Just FYI. :-)

**Comment by karmatosed** [comment]
I think flipping and giving the higher z-index, then testing is a good path to success here.

**Comment by chriskmnds** [comment]
> I think flipping and giving the higher z-index, then testing is a good path to success here.

True, although in a similar one-page view like above it ends up clipping/cutting-off the bottom menu item instead - which is a similar situation, just in the opposite direction. There is no additional window scrolling added if the menu overflows under the page. A a bit of an edge case though, granted. So just FYI :-)

**Comment by faishal** [comment]
I tried on my local by fixing z-index, but that was introducing some other issue like when we scroll up  menu appear on toolbar but ellipsis goes behind the toolbar. For that, I added another fix which will reposition on scroll.

![4519-block ellipsis menu opens below the toolbar](https://user-images.githubusercontent.com/1633818/38493407-b8f67ed8-3c0f-11e8-90a9-7a0d7daeea83.gif)

**Comment by edent** [comment]
This is also occurs for blocks near the bottom of the page.
![gutenberg scroll](https://user-images.githubusercontent.com/837136/38545085-23f96196-3ca1-11e8-98fb-8d97358357ac.png)

Makes it impossible to scroll to get to the context menu item I want.  As you can see, all three(!) scrollbars are as low as they can go.

**Comment by SuperGeniusZeb** [comment]
Would it be possible to have a scrollbar on the options menu? That seems like the only solution to the problem @edent pointed out.

**Comment by edent** [comment]
I'm not sure that four scrollbars are the answer....!
