### ISSUE TITLE
Add formatting toolbar to text blocks

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#452]
![image](https://cloud.githubusercontent.com/assets/548849/25193077/060ef642-2536-11e7-97ca-1dfa244e7779.png)

**Comment by iseulde** [comment]
What's left here?

**Comment by aduth** [comment]
Linking hasn't been completed yet.

See: #524 (previously #505)

**Comment by mtias** [comment]
Let's close this one as done.
