### ISSUE TITLE
Warn that customisations will be lost on style variation switch

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#45210]
Problem: When you switch away from a customised style variation it's not clear that those customisations will be lost. Technically you can undo yourself out of trouble, but if you save and exit the editor then that customised style variation is gone, without any warning.

Comprehensive style variation management is being explored in https://github.com/WordPress/gutenberg/issues/38333, but that's a pretty big feature that will take time to implement. This is a problem now and a short term solution like a warning could help folks avoid losing their hard work.

**Comment by jasmussen** [comment]
https://github.com/WordPress/gutenberg/issues/45371 takes a different stab at this by clearly delineating customized styles as separate.

**Comment by jasmussen** [comment]
What do you think of the latest iterations to https://github.com/WordPress/gutenberg/issues/45371? By copying a style to "Custom styles" (and adding the unread dot) as soon as it gets customized, does it resolve this?

**Comment by jameskoster** [comment]
Yes, I think so.
