### ISSUE TITLE
Bug: Gutenberg Plugin v13.9+ - Template Attribute for PHP template & theme.json conflict

### ISSUE THREAD

**Issue by sethwhitaker** [WordPress/gutenberg#45216]
### Description

Ever since Gutenberg Plugin v13.9+ the simple existence of the `theme.json` file in the theme causes the template label to always say **Default Template** if its been set to a custom PHP template. Clicking on the Label to open the popup still correctly shows which template is actually set for the page.

I came across this PR https://github.com/WordPress/gutenberg/pull/42091 when looking to see if anyone has had similar experiences. The comment by noisysocks in that conversation is the exact issue im having but based on the remainder of the conversation, i assume it was fixed before merge. There is some discussion at the bottom about `settings.availableTemplates[]` but I cant find any documentation on that anywhere. Is this something I need in my theme.json to define my PHP templates? Do i have to disable block templates? Id like to have the ability to have both block and classic as im primarily developing in a hybrid approach.

At this point im not 100% sure if this is still a bug or if Im just missing something somewhere.
Ive created a simple theme with just a basic `index.php`, `style.css`, `theme.json` and `custom-template.php` so there are no conflicts anywhere.

![bug-template-attribute](https://user-images.githubusercontent.com/578552/197253472-194a47de-8763-4985-8eee-4ecbde5477c3.jpg)

If I remove the `theme.json` file from the theme, then it shows up correctly. 

![correct-template-attribute](https://user-images.githubusercontent.com/578552/197254066-7e159c98-e3dd-4ee7-9618-520ff5c24944.jpg)

This only appears to affect classic PHP templates. As below I created an FSE Template and it works as expected even with the `theme.json` in the theme. 

![FES-template-attribute](https://user-images.githubusercontent.com/578552/197254530-01742885-5866-4a61-a2fe-506f1449f840.jpg)

### Step-by-step reproduction instructions

1. Go to page
2. Click on template title
3. Cange to custom PHP template
4. Template title does not change to reflect chosen template

### Screenshots, screen recording, code snippet

![FES-template-attribute](https://user-images.githubusercontent.com/578552/197274852-6aaac5c8-c0d6-4d22-9cf5-802123cbaa1d.jpg)
![bug-template-attribute](https://user-images.githubusercontent.com/578552/197274856-ceaea1ae-abc6-44bd-95e5-54989212bc40.jpg)
![correct-template-attribute](https://user-images.githubusercontent.com/578552/197274858-8f562ca0-87e1-4b8a-8780-18590a35b2be.jpg)

### Environment info

- Wordpress - v6.0.3
- Gutenberg - v13.9+

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sethwhitaker** [comment]
If I add `remove_theme_support( 'block-templates' );` to functions.php then the template title works as expected. But I do not wish to need to add this to the theme if I do not need too.

Is it not possible to use block templates and classic templates together?

**Comment by skorasaurus** [comment]
Thanks for the thorough, detailed report. 

I have the same experience as well; using Gutenberg 14.0.3 (haven't tested other versions at the time) on a [custom theme](https://gitlab.com/cpl/ernesto) that uses theme.json and no block-based templates. 

From reading over the discussion at https://github.com/WordPress/gutenberg/pull/42091 ; that behavior (the name of the template type should be loaded) should be fixed but it is not. 

@noisysocks or @Mamaduka could you clarify if this has not been fixed?

**Comment by sethwhitaker** [comment]
Good to know that this should be working but maybe isn't. Thought I was going crazy.

**Comment by noisysocks** [comment]
Can confirm this also by activating Twenty Twenty and creating an empty `wp-content/themes/twentytwenty/theme.json` file.

@Mamaduka: Looking at https://github.com/WordPress/gutenberg/pull/42091/files. The presence of `theme.json` causes `supportsTemplateMode` to be `true`. I'm not really sure how to fix this while also making it so that _Default template_ isn't shown in block themes.

**Comment by Mamaduka** [comment]
This should be resolved after #46304.
