### ISSUE TITLE
Pasted italicized/bolded space characters will be omitted

### ISSUE THREAD

**Issue by dagleich** [WordPress/gutenberg#45223]
When I copy and paste formatted text from Microsoft Word into the WordPress Gutenberg editor and in a sentence there is only a space character between two words left italicized while the words are regular, the space will be ommitted and the two words shown as one.

**Comment by t-hamano** [comment]
I was able to reproduce it. This problem seems to occur not only with italic spaces, but also with bold spaces.

https://user-images.githubusercontent.com/54422211/197379078-0f3cc135-6d8a-42d6-b9a3-60de5a810084.mp4

**Comment by ellatrix** [comment]
For any copy/paste bugs, could you provide what is logged in the console?

**Comment by t-hamano** [comment]
This problem appears to have been resolved in the Gutenberg trunk. The italizalicized space was converted to normal spaces, is this the intended behavior? If so, I think this issue can be closed.

Tested on WidnowsOS with Chrome 116.0.5845.97 and Firefox 116.0.3.

https://github.com/WordPress/gutenberg/assets/54422211/9286a445-0770-43c0-9d0e-09d3af9d79a5

**Comment by Mamaduka** [comment]
Tested again, and I can no longer reproduce the bug. I'm going to close the issue.
