### ISSUE TITLE
Popover: Prefer `isAlternate` style when rendering from Toolbar

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#45246]
## What problem does this address?

According to the design spec, popovers opened from the block toolbar should have the same dark border (`isAlternate`) style by default. Currently, consumers need to set that prop on their popovers manually.

## What is your proposed solution?

See if we can do this automatically, likely by using the [context system](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/ui/context).

----

More context from @jasmussen (https://github.com/WordPress/gutenberg/pull/49838#issuecomment-1527123604)

I found a little more context in https://github.com/WordPress/gutenberg/pull/45137, where the "isAlternate" is refactored/deprecated in favor of a variant.

But it boils down to this, you can have two styles of popovers. This one:
<img width="771" alt="Screenshot 2023-04-28 at 09 30 06" src="https://user-images.githubusercontent.com/1204802/235083463-8294c900-f5f1-472e-b7aa-2c743a7df9e4.png">

Notice how it opens from the block toolbar and has the same black borders as the block toolbar.

This one:

<img width="239" alt="Screenshot 2023-04-28 at 09 30 15" src="https://user-images.githubusercontent.com/1204802/235083502-b539eb2e-cfa3-4d19-98ba-663d1520c623.png">

Notice how it _doesn't_ open from the block toolbar, and has the light gray borders, plus a drop shadow.

The thing is, a developer should not have to choose a variant if we can automate this for them. The gray with box shadow can be default, but if something opens from the block toolbar, it should always be the dark version. That way we avoid this issue where someone forgot the variant:

<img width="435" alt="Screenshot 2023-04-28 at 09 30 21" src="https://user-images.githubusercontent.com/1204802/235084267-a971f398-e8ae-4bf1-b8b9-22de4abd399b.png">

**Comment by ciampo** [comment]
I started working the approach suggested by this issue for the new `DropdownMenu` component in #51097

**Comment by mirka** [comment]
Closed by #51154
