### ISSUE TITLE
[Storybook] `Disabled` component are still focusable in Firefox

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#45253]
### Description

This is likely a regression introduced by #44865, which causes the `Disabled` component to rely on the `inert` attribute.

The `inert` attribute is not supported by Firefox browsers, and the polyfill doesn't seem to work in preventing elements wrapped in `Disabled` from being keyboard-focusable.

What needs to be clarified is whether the polyfill is loaded at all in Storybook — depending on that, this may be either an environment-specific issue, or a Gutenberg-wide problem

### Step-by-step reproduction instructions

1. Visit https://wordpress.github.io/gutenberg/?path=/story/components-disabled--default using the firefox browser
2. Make sure the `isDisabled` is set to `true`
3. With the keyboard, focus the different input fields

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1083581/197599647-2fa3ee6f-411a-4635-8d15-b6a15cc6d8ac.mp4

### Environment info

Firefox, MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
I confirmed that there's no regression in Firefox, it's just that there's no polyfill (not just the inert one) is actually loaded in storybook.

**Comment by ciampo** [comment]
Thank you for the confirmation, Riad! I'm going to change the PR's description to better reflect that the issue is only in Storybook.
