### ISSUE TITLE
Quote style two is easy to confuse with comments

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4526]
This is more a potential future clash if we have collaborative editing, but it's also something that goes against a widely interpreted icon. Right now we have this for the second quote style icon:

![2018-01-16 at 20 05](https://user-images.githubusercontent.com/253067/35009843-d585ef78-faf8-11e7-8369-a7355d994f86.png)

This is easy to confuse with adding a comment. Yes, we don't have comments and clicking it doesn't add a comment, but we should consider it's use.

**Comment by melchoyce** [comment]
What if we changed the icons to two labels?
- Style 1
- Style 2

**Comment by karmatosed** [comment]
My only wonder there is we don’t use words anywhere else. I’m saying that I don’t know how we show them any other way unless have a very niche icon design. I wonder if merging as a drop down could also work.

**Comment by karmatosed** [comment]
As quotes are being worked on, split into separate blocks lets close this and iterate there.
