### ISSUE TITLE
Content-only locked patterns: move "Modify" to elllipsis menu

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#45263]
Followup to #43037. When you add `"templateLock":"contentOnly"` manually to the code of a group block (no UI yet), the pattern becomes content-only locked and flattens nested blocks, for simpler editing:

<img width="1437" alt="content only locked" src="https://user-images.githubusercontent.com/1204802/197700495-3273e7e1-a2a1-4aca-8da7-8847818c4b26.png">

There's a big "Modify" button in the toolbar, which unlocks the patterns you can edit, delete, move around nested blocks. 

- [ ] Let's move this button to the ellipsis menu, to reduce its prominence. 

---

An adjacent question/conversation is whether we should rename the button to "Edit", and have it invoke focus mode at the same time. This could use design feedback. CC: @WordPress/gutenberg-design

**Comment by jasmussen** [comment]
Added "Needs dev" as the moving to ellipsis menu task can be completed now, despite the open question.

**Comment by jasmussen** [comment]
Related: #45264

**Comment by jameskoster** [comment]
Considering https://github.com/WordPress/gutenberg/issues/45264, 'Edit' may be out of the question.

> no UI yet

Perhaps we should explore this first? It may be that the solution is a toggle, which could make the 'modify' button unnecessary.

**Comment by jasmussen** [comment]
> 'Edit' may be out of the question.

Actually I thought it neat to combine the two. Modify and Edit could be the same, no?

**Comment by jameskoster** [comment]
Oh yes, that would be good to try :)
