### ISSUE TITLE
Add space to top of publishing calendar

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4528]
The publishing calendar has no space and just by adding a little to reflect the left/right padding it would be better. Left is what we have now, right with a little spacing:

![calendarspace](https://user-images.githubusercontent.com/253067/35010554-29fd15b6-fafb-11e7-8be3-f8272aca7fa6.png)

**Comment by jorgefilipecosta** [comment]
Hi @karmatosed given the latest changes to the panel I think the publish area already has a margin. I'm closing the issue for now, if some design improvement is still needed feel free to reopen it.
