### ISSUE TITLE
Navigation block: Long menu name breaks dropdown view

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#45294]
### Description

If you have a long menu name, the navigation block's new menu management drop down doesn't properly cut it off. Props to @jordesign for finding this: 

<img width="291" alt="Screen Shot 2022-10-25 at 6 17 57 PM" src="https://user-images.githubusercontent.com/26996883/197912448-4dab6a0f-71b0-4e03-82cc-08c42a7a8139.png">

### Step-by-step reproduction instructions

1. Add a new navigation block.
2. Give it a really long name. 
3. Check dropdown :) 

### Screenshots, screen recording, code snippet

<img width="291" alt="Screen Shot 2022-10-25 at 6 17 57 PM" src="https://user-images.githubusercontent.com/26996883/197912524-ef944f3f-62a2-4304-b34c-1faf39147740.png">

### Environment info

- WP 6.1 RC 4
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sharukhkhanajm** [comment]
Hi, @annezazu I just checked it and it seems to work fine.
The only odd thing is the outline.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/47321682/198816520-2206c30d-a924-436d-b583-fae1c4442ab0.png">

**Comment by annezazu** [comment]
@sharukhkhanajm can you clarify what WordPress version you're using and/or Gutenberg? That still looks broken to me for what it's worth :)

**Comment by sharukhkhanajm** [comment]
@annezazu 
WP version: `6.0.3`
Gutenberg ( forked from GitHub ): `14.4.0`

**Comment by annezazu** [comment]
Thanks! Leaving this open as this definitely can be improved and I can still replicate in Chrome with the same setup:

<img width="316" alt="Screen Shot 2022-10-31 at 12 08 38 PM" src="https://user-images.githubusercontent.com/26996883/199090040-8a8a1d2f-ec6a-4c43-9ede-e9847bef8dfd.png">

**Comment by michalczaplinski** [comment]
@yuliyan will work on this ! 🙂

**Comment by yuliyan** [comment]
I'll take the issue.

**Comment by getdave** [comment]
@yuliyan Happy to review this when you're done.

**Comment by yuliyan** [comment]
The issue has been fixed with https://github.com/WordPress/gutenberg/pull/45647.
