### ISSUE TITLE
Update to WordPress 6.1 RC3 causes a Fatal error with Gutenberg 14.4.0-rc.2

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#45301]
### Description

After updating from WordPress 6.1 RC2 to 6.1 RC3 I get this fatal error in block editor context:

<img width="655" alt="Bildschirmfoto 2022-10-26 um 09 04 40" src="https://user-images.githubusercontent.com/31563167/197957493-ad4ea522-3640-44db-946a-348893017448.png">

Deactivating the Gutenberg 14.4.0-rc.2 plugin solve that new issue.

### Step-by-step reproduction instructions

1. Use Gutenberg 14.4.0-rc.2 plugin activated
2. Update to WordPress 6.1 RC3
3. Open the block editor

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for contributing, @CreativeDive!

The fix for this problem was merged yesterday (#45265) and will include in the stable GB 14.4 release.
