### ISSUE TITLE
composer.lock file should be committed to Git

### ISSUE THREAD

**Issue by anton-vlasenko** [WordPress/gutenberg#45314]
## What problem does this address?
I haven't found a ticket that discusses this issue, so I decided to open a new one.
It's considered good practice to commit composer.lock file to Git.
Why?
1. Having it in the repository ensures that each developer is using the same versions of composer packages.
2. It fixes some issues with updating composer packages. Please see https://github.com/WordPress/gutenberg/issues/45313

I wonder if it was a conscious decision not to commit `composer.lock`.

## What is your proposed solution?
Commit the `composer.lock` file to Git.

**Comment by anton-vlasenko** [comment]
As far as I understand, this decision is intentional.
Not having `composer.lock` in the repository allows for more flexibility in using composer packages depending upon the PHP version.
Please see https://core.trac.wordpress.org/ticket/47381 for more context.

**Comment by anton-vlasenko** [comment]
As far as I understand, this decision is intentional.
Not having composer.lock in the repository allows for more flexibility in using composer packages (PHPUnit packages in particular) depending upon the PHP version.
Please see https://core.trac.wordpress.org/ticket/47381 for more context.
FYI: @oandregal

**Comment by oandregal** [comment]
Thanks for gathering and sharing the context, Anton.
