### ISSUE TITLE
Typo in new strings

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#45315]
### Description

https://plugins.trac.wordpress.org/browser/gutenberg/tags/14.4.0/build/edit-post/index.js#L4126

"disrtaction" ...?

If somebody is so kind to say in which file, so I can edit this typo.

### Step-by-step reproduction instructions

It's a simple typo.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I think this was fixed in #45186.

**Comment by NekoJonez** [comment]
Ah, otherwise I would fix it...

**Comment by Mamaduka** [comment]
Thanks for your contributions, @NekoJonez!

The fix will be part of the Gutenberg 14.5 release.
