### ISSUE TITLE
`prelint:php` script doesn't work as expected when new dev dependencies get added to `composer.json`

### ISSUE THREAD

**Issue by anton-vlasenko** [WordPress/gutenberg#45313]
### Description

Neither `composer install` nor `composer install --dev` work as expected.
`composer install` doesn't add new dev dependencies if they are listed in the `required-dev` section of `composer.json`.
Therefore, the `prelint:php` script should be updated to use `composer update` instead.

### Step-by-step reproduction instructions

1. Remove the `src/wp-content/plugins/gutenberg/vendor`.
2. Go to the `src/wp-content/plugins/gutenberg` folder.
3. Run `composer install && composer update` command.
4. Make sure that the `src/wp-content/plugins/gutenberg/vendor/phpcompatibility/phpcompatibility-wp` folder exists.
5. Note the version of the `phpcompatibility/phpcompatibility-wp` package in the `required-dev` section of `composer.json`. Currently it's `"phpcompatibility/phpcompatibility-wp": "^2.1.3",`.
6. Run `composer remove phpcompatibility/phpcompatibility-wp`.
7. Observe there is no `src/wp-content/plugins/gutenberg/vendor/phpcompatibility/phpcompatibility-wp` folder.
8. Add the `phpcompatibility/phpcompatibility-wp` package back to the `require-dev` section of the `composer.json` file.
9. This is where the issue happens (!): run `composer install`, then `composer install --dev`. 

Expected behaviour: `phpcompatibility/phpcompatibility-wp` must be installed.

Actual behaviour: No `phpcompatibility/phpcompatibility-wp` package is installed.

Suggested solution: if you run`composer update` instead of `composer install`, the issue is resolved and the `phpcompatibility/phpcompatibility-wp` package gets installed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by anton-vlasenko** [comment]
Another solution would be to have composer.lock file committed to Git.
So, I'm not sure which solution is the best.
IMO, committing the composer.lock file to Git would be better because of several reasons.

**Comment by oandregal** [comment]
> 9. This is where the issue happens (!): run composer install, then composer install --dev.

I want to note that, if I remove `composer.lock` before this step, `composer install` works fine (it installs the dev dependencies).

---

Thanks for following-up on this, Anton. For full context, I ran into issues when trying the `npm run lint:php` command: some dev dependencies were not installed, hence it failed. When I intentionally installed those dependencies, the error went away.

I'm not sure how widespread the issue is and how to proceed here.

If we were to change `composer install` by `composer update` we should at least look at the [CI jobs](https://github.com/WordPress/gutenberg/tree/trunk/.github/workflows) that use the affected commands and check that they work as before (same or better performance, reproducible builds, etc.). It's a bit out of my area of expertise, I may be miss other things.

**Comment by anton-vlasenko** [comment]
> If we were to change composer install by composer update we should at least look at the [CI jobs](https://github.com/WordPress/gutenberg/tree/trunk/.github/workflows) that use the affected commands and check that they work as before (same or better performance, reproducible builds, etc.). It's a bit out of my area of expertise, I may be miss other things.

@oandregal 
I couldn't find any mention of this command in the CI jobs.
Also, the `PHPUnit test` Core CI job also uses `composer update` instead of `composer.lock` in a similar situation.
https://github.com/WordPress/wordpress-develop/blob/trunk/.github/workflows/phpunit-tests.yml#L142

**Comment by anton-vlasenko** [comment]
@oandregal would you please let me know if you are still opposed to merging this fix?
[The PR](https://github.com/WordPress/gutenberg/pull/45468) has been [approved](https://github.com/WordPress/gutenberg/pull/45468#pullrequestreview-1231927329).

**Comment by oandregal** [comment]
> @oandregal would you please let me know if you are still opposed to merging this fix?
https://github.com/WordPress/gutenberg/pull/45468 has been https://github.com/WordPress/gutenberg/pull/45468#pullrequestreview-1231927329.

I was never opposed! Just noted that it was out of my expertise, and shared some use cases I thought could be problematic. Given you already checked and people approved the PR, let's :ship:

**Comment by anton-vlasenko** [comment]
@oandregal 
> I was never opposed!

Sorry for the confusion and thanks for the reply! 👍
The [PR](https://github.com/WordPress/gutenberg/pull/45468) has been merged.
