### ISSUE TITLE
Small typo in a string, Gutenberg 14.4.0

### ISSUE THREAD

**Issue by piermario** [WordPress/gutenberg#45318]
### Description

Hello, friends!

While translating 14.4.0 into Italian, I noticed a small typo in one of Gutenberg's strings:

The string is this one: Toggle **_disrtaction_** free mode.

References:
[build/edit-post/index.js:4126]
https://plugins.trac.wordpress.org/browser/gutenberg/tags/14.4.0/build/edit-post/index.js#L4126

[build/edit-post/index.min.js:4265]
https://plugins.trac.wordpress.org/browser/gutenberg/tags/14.4.0/build/edit-post/index.min.js#L4265

Here's the link to the string on translate.wordpress.org: 
https://translate.wordpress.org/projects/wp-plugins/gutenberg/stable/it/default/?filters%5Boriginal_id%5D=14723033

No big deal, I thought I'd just give a heads-up in case someone can fix this. 

Thanks!

### Step-by-step reproduction instructions

n/a

### Screenshots, screen recording, code snippet

https://succo.link/7VyzEg

### Environment info

Gutenberg version 14.4.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thank you for your contribution!
This issue is the same as #45315 and the fix will be applied in Gutenberg 14.5.

**Comment by piermario** [comment]
Thank you Aki! 
I didn't see the other issue before opening mine, sorry about that! 😇
