### ISSUE TITLE
Undefined array key 'attrs' in WP_Block_Supports/apply_block_supports

### ISSUE THREAD

**Issue by seothemes** [WordPress/gutenberg#45328]
### Description

After updating to 14.4.0 with 6.0.3 or 6.0.4 I'm seeing this error being caused by the Page List block apparently not having attributes set:

```sh
Undefined array key "attrs"

/wp-includes/class-wp-block-supports.php - Line 94
```

Adding an isset check would fix the issue, but I wasn't able to find the root cause of the problem:

```php
$block_attributes = isset( self::$block_to_render['attrs']  ) ? self::$block_to_render['attrs'] : [];
```

### Step-by-step reproduction instructions

1. Update to 14.4.0 
2. Create a block pattern with a Navigation block containing a Page List
3. Create a page template that renders the pattern, e.g: `<!-- wp:pattern {"slug":"header"} -→`
4. View the page on the front end

### Screenshots, screen recording, code snippet

<img width="612" alt="image" src="https://user-images.githubusercontent.com/24793388/198187161-9f707173-d7fb-401f-9365-d6b905fb3b2a.png">

### Environment info

- WP 6.0.3 & 6.0.4
- Gutenberg 14.4.0
- Blockify theme 0.9.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by seothemes** [comment]
This is actually being caused by an incorrect attribute on the navigation block in one of the patterns.

An isset check should probably still be added just in case, but feel free to close.

**Comment by Mamaduka** [comment]
Thanks for reporting the issue, @seothemes!

Can you share the navigation block code snippet as well? That would make reproduction easier.

Thank you

**Comment by seothemes** [comment]
@Mamaduka 

```html
<!-- wp:navigation {"layout":{"type":"flex","flexWrap":"nowrap"}} /-->
```

It still happens with this block when there is no "ref" attribute set.

For the navigation block to work on WordPress.org previews we need to remove the "ref" attribute from patterns.

**Comment by getdave** [comment]
Pasted this into a site and I didn't see any errors. Going to close as I cannot reproduce.
