### ISSUE TITLE
Meta boxes below editor content and in Extended Settings cannot be toggled

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#4532]
## Issue Overview
Meta boxes which are compatible with the block editor are displayed in the meta boxes section below the main editor or in  the Extended Settings section. They include a Toggle panel button. But it's not active. If a box is closed, it's unusable.

## Steps to Reproduce (for bugs)

1. Activate WordPress SEO
2. Choose Add New
3. Attempt to click on the Toggle panel button

## Expected Behavior
- In the classic editor the meta boxes toggle.
- Meta boxes appear in the toggled state they were left when the Classic editor was last closed. 
- They can also be dragged around.

## Current Behavior
- Meta boxes appear in the toggled state they were left when the Classic editor was last closed. 
- But if the boxes are closed then they cannot be opened, so are unusable.

## Possible Solution

I believe that in the classic editor the toggling is implemented by the postbox.js code. 
A similar solution is required for backward compatibility.

## Screenshots / Video

In this example the _Yoast SEO_ box is closed, the _Fields_ meta box is open.
In the Extended Setting section the _Clone on update_ box is closed.
![image](https://user-images.githubusercontent.com/2474435/35016579-25124894-fb11-11e7-85d1-c7d620a9db9c.png)

## Related Issues and/or PRs

I believe this was already discussed yesterday ( 15 Jan ) with @smp303, but not sure in which channel.
It would be nice if this discussion could be mentioned.
Especially if I've missed anything.

PS. As an Aside. WooCommerce's _Product Data_ meta box is toggleable. This is because they provide their own code to cater for the fields in the header.
But the _Product gallery_ box in the Extended section isn't. 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by afercia** [comment]
I think there is a pending PR for this, see https://github.com/WordPress/gutenberg/pull/4434
