### ISSUE TITLE
DateTimePicker: Localize Weekdays

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#4533]
## Issue Overview
I use a locale 'de_DE' WordPress version.
The month is translated correctly, but the weekdays should start on Monday (Montag) and should be localized Mo, Di, Mi, Do, Fr, Sa, So.

![weekday](https://user-images.githubusercontent.com/695201/35017648-06223c2a-fb1e-11e7-9116-4a3bf2ef3c0b.png)

**Comment by danielbachhuber** [comment]
I believe this is inherited from the `ReactDatePicker` component. If so, we'll need to figure out how to pass localization through. I believe this is where the names are being generated: https://github.com/Hacker0x01/react-datepicker/blob/master/src/calendar.jsx#L273-L281

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521134199000578)._

**Comment by jeffpaul** [comment]
Related to #1311

**Comment by bph** [comment]
One user just pointed out in a support ticket that he expected the date-picker to adhere to the "week starts on"
![screen shot 2018-08-17 at 5 37 27 pm](https://user-images.githubusercontent.com/39980/44289915-42faab00-a244-11e8-8a79-65529ee214d1.png)
set via WP-Admin > Settings > General. 
When it's set to Monday, the date-picker in Gutenberg also should start on Monday.

**Comment by Soean** [comment]
Yes, I see the same, we don't need a separate issue.
The datepicker has changed since I reported the bug, but it is still not localized.

**Comment by luminuu** [comment]
When a post gets scheduled or published, the shown date under "Publish" is also not localized. 

Gutenberg 4.3
WordPress 4.9.8

**Comment by georgeh** [comment]
I'm looking to see if we can localize the datepicker
