### ISSUE TITLE
Custom Field Meta Boxes wont close

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4534]
## Issue Overview
When a plugin creates Custom Meta Boxes, such as Yoast SEO, there's a small arrow next to the Meta Box Title that allows you to open/close the panel. This doesn't work in Gutenberg. When clicking on the arrow icon, nothing happens.

![gutenberg-custommetaboxeswontclose](https://user-images.githubusercontent.com/2078245/35019840-236e35fe-fb7d-11e7-8f89-49865af2c5b9.png)

## Steps to Reproduce (for bugs)
1. Install & Activate Yoast SEO plugin
2. Edit a Page
3. Try to close the Yoast SEO panel by clicking the arrow icon next to the Meta Box title

## Expected Behavior
I should be able to close Meta Boxes, just like I can now when using the classic editor

## Current Behavior
Meta Boxes no longer close

_Firefox Quantum 57.0.4 (64-bit)
Gutenberg 2.0.0
WordPress 4.9.2_

**Comment by bobbingwide** [comment]
Same as #4532

**Comment by youknowriad** [comment]
Closing as duplicate and PR fixing this coming.
