### ISSUE TITLE
Conditionally loading block templates classic themes

### ISSUE THREAD

**Issue by abaicus** [WordPress/gutenberg#45341]
## What problem does this address?
It is currently impossible to specify which templates should be loaded inside classic themes.

There are two theme supports to enable block templates and template parts:
```php
add_theme_support( 'block-template-parts' );
add_theme_support( 'block-templates' );
```

---

A classic theme might implement a complex archive layout with many customization features but still want to allow the possibility to use a template for the archive based on a customizer setting.

I believe that this extends to block-based themes as well. If you want to define templates for CPTs (e.g., WooCommerce Single Product), these will be loaded automatically, regardless of the plugin’s state. When it comes to classic themes, authors would probably want to allow the user to pick which templates he intends to override with block templates.

I’ve seen that WooCommerce has managed to load templates from the plugin in a [custom class](https://github.com/woocommerce/woocommerce-blocks/blob/a5d7c19451e78ef8b2467ddef06e3dc2e0184021/docs/internal-developers/templates/block-template-controller.md), but that feels a bit cumbersome. 

## What is your proposed solution?
Allowing an arguments array with which templates to be loaded for both theme supports could be a good solution:

```php
add_theme_support( 'block-templates',
	array(
		'index'      => get_template_directory() . '/includes/fse-templates/index.html',
		'front-page' => get_template_directory() . '/includes/fse-templates/front-page.html',
	)
);
```

**Comment by annezazu** [comment]
@WordPress/block-themers tagging in this crew as I think this will be of interest!

**Comment by jffng** [comment]
👋  So I understand, the suggestion is to enable classic themes to specify a different file path for a block-based template to override in the hierarchy?

Apologies if I'm missing something, but why not just enable the theme support and supply the block based version of the template in the location that Core will look for, e.g. `block-templates/front-page.html`?

**Comment by abaicus** [comment]
@jffng

That would make sense as well. Just allowing a configurable array of which templates are being loaded would be good enough, I think.

**Comment by jffng** [comment]
Why is a configurable array necessary? Currently if a block template is provided and the theme support is added + enabled, the block template will override the classic one accordingly in the hierarchy. For example: https://github.com/WordPress/wordpress-develop/pull/3545 — archive pages are rendered with the block template and all other pages with the classic template.

**Comment by abaicus** [comment]
@jffng 

It just occurred to me that filtering out the templates you don't want to load using the `get_block_templates` filter would solve this. 

That would solve the issue. I'm not sure why I didn't think about this before. 😶‍🌫️ 

Thank you for being so helpful!

**Comment by jffng** [comment]
Happy to help and try to understand different use cases!

**Comment by annezazu** [comment]
@abaicus is it okay if we close this out considering? Perhaps it's worth updating this handbook page around this specific use case since it seems to have resonated too: https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/

**Comment by abaicus** [comment]
@annezazu Yes, I think we can close the issue. It would be great if it could be mentioned in the handbook. 👍🏻 

Thank you for all the help!

**Comment by carolinan** [comment]
I think we may need a little bit more information to help us update the documentation. @abaicus Would you be able to share an example where you are using the filter?

**Comment by abaicus** [comment]
@carolinan I've added this functionality in this commit: https://github.com/Codeinwp/raft/commit/a3d9919f15e60d6498f68c38d0163b8604636e8d.

Please let me know if you think any additional details are needed! 👍🏻

Thank you!
