### ISSUE TITLE
Scripts: Extend build commands to allow postCSS autoprefixer

### ISSUE THREAD

**Issue by dansdev** [WordPress/gutenberg#45368]
## What problem does this address?
I haven't been able to find any documentation online on whether this is already possible, so apologies in advanced if this has already been covered.

Currently styles outputted via the @wordpress/create-block wp-scripts aren't autoprefixed with vendor prefixes 

e.g `
{
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
}
`

## What is your proposed solution?
Add a new flag e.g --autoprefixer for those that require vendor prefixes or have postCSS autoprefixer built-in by default?

**Comment by chimok** [comment]
Hello @dansdev,

I'm using postcss without any issues, it's official supported with @wordpress/scripts. You can even add custom postcss plugins if you imply add a postcss.conf.js in your project. Please keep in mind a lot of prefixes aren't required anymore, like your example with flexbox. That's why it's not prefixed.

**Comment by gziolo** [comment]
https://github.com/WordPress/gutenberg/blob/9905301c5f783141177f61e37851eb9e7e96b875/packages/scripts/config/webpack.config.js#L78-L110

https://github.com/WordPress/gutenberg/blob/9905301c5f783141177f61e37851eb9e7e96b875/packages/postcss-plugins-preset/lib/index.js#L1

I can confirm that `autoprefixer` is integrated by default with `@wordpress/scripts`. Let us know if we need to change the default settings. You can also always provide your PostCSS config in the project using one of the methods listed below:

https://github.com/WordPress/gutenberg/blob/9905301c5f783141177f61e37851eb9e7e96b875/packages/scripts/utils/config.js#L92-L100
