### ISSUE TITLE
Full Site Editor not selecting home template when opening the default (front) page

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#45363]
### Description

When opening the Gutenberg Full Site Editor, with page being set as the front page, the editor opens that front page by default, but with the pre-selected template being just `page` and not `home`.

### Step-by-step reproduction instructions

1. Ensure a Full Site Editing (FSE) block theme is installed and activated.
2. Make a page the front page.
3. Open the Full Site Editor (Sidebar → Design → Editor (beta))
The Full Site Editor opens and by default will show the front page, but the pre-selected template won't be of the front page but rather a normal page.
The user can manually change the selected template to `home`/front page to eventually achieve the proper preview of that front page.

### Environment info

- WordPress 6.0.3, Gutenberg Plugin 14.4.0
- Chrome
- Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @strarsis

When you select a static homepage from Settings > Reading, that page will be served by WP as a homepage. The site editor mimics this behavior.

I've tested with the TT3 theme, and the behavior is correct.

Let me know if I'm missing something.

**Comment by strarsis** [comment]
@Mamaduka: It may well be that I am missing something in my theme.
I prepared a minimal sample Gutenberg block theme that reproduces the issue: https://github.com/strarsis/fse-test-theme

With a page being set as front page and that test theme pulled and activated, 
note that the Site Editor shows the narrow header part (named just `header.html`) as header for the front page that opens by default, not the large header part (named `header-large.html`), as it should be the case, as it is used in the `home.html` template.

The front page should have the large header part, while the other pages should have the narrow header one.

**Comment by strarsis** [comment]
@Mamaduka: I am able to reproduce this issue with the Twenty Twenty-Two theme and only the Gutenberg-Plugin enabled (or disabled): When I open the Site Editor using Admin Sidebar → Design → Editor (beta), the front page opens, but the template pre-selected (at the top) is just the `page` template, not the `home` template, and the Twenty Twenty-Two theme also ships with a `home` template. 
So the user sees the wrong template for the front page, e.g. the front page should have a large header and the other pages a narrow one. This is not shown, which confused the user. One has first switch the template at the top from `page` to `front page` to get the proper frontend-matching preview in the site editor.

**Comment by Mamaduka** [comment]
@strarsis, that's correct behavior if you have a static homepage set from Settings > Reading.

## Screenshot

![CleanShot 2022-10-28 at 18 41 07](https://user-images.githubusercontent.com/240569/198653623-fa7f890d-e34a-4382-9b73-e8f3e049fc68.png)

**Comment by strarsis** [comment]
@Mamaduka: Yes, I set that page to be the Homepage (frontpage / home).

The frontpage traditionally and now also in block themes (from what I understand) has its own template.
I thought that the page configured to be the frontpage also uses the corresponding classic - or in this case block home template.
If this is not the case and I completely misunderstood this - what would be the purpose of the `home` block template then?

**Comment by strarsis** [comment]
@Mamaduka: As the front page uses that home template over the page template, and this had been the case with classic themes, too, this should be considered a bug, right? Gutenberg site editor should use the same template (home for frontpage) as it is used on the frontend (home for frontpage).

**Comment by Mamaduka** [comment]
@strarsis, on the site front page, WordPress will always use the `front-page.html` template file if it exists.

You can see how the front page hierarchy works on this documentation page: https://developer.wordpress.org/themes/functionality/custom-front-page-templates/#template-hierarchy-of-custom-front-page.

**Comment by strarsis** [comment]
@Mamaduka:
Thanks! Using `front-page.html` indeed made the Editor switch to the front page template for the actual front page.
`home` and `front page` are different in general, and I hadn't picked up that difference first.
