### ISSUE TITLE
Image to Media & Text transformation: Set to wide by deault

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#45375]
### Description

When I transform an image block into a Media and Text block, the new Media and Text block is set to be wide alignment. I would prefer it to not have any alignment by default.

### Step-by-step reproduction instructions

1. Add an image to the post
2. Click on the transform option and select Media & Text
3. Notice that the new Media & Text block has a wide alignment

### Screenshots, screen recording, code snippet

![Uploading mediaandtext.gif…]()

### Environment info

- WordPress and Gutenberg trunk
- OSX
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Related #20941.

**Comment by paaljoachim** [comment]
Hey @scruffian Ben

Default alignment for Media & Text should be set to none.
It has a go ahead from design. (more info in the other issue: https://github.com/WordPress/gutenberg/issues/20941)
Let's get this fixed.

**Comment by paaljoachim** [comment]
I will go ahead and close this issue. As Aaron made a PR which has now been merged into the Gutenberg plugin.
https://github.com/WordPress/gutenberg/pull/48404
