### ISSUE TITLE
Site Editor: Custom page template shows as 'Not found'

### ISSUE THREAD

**Issue by mikachan** [WordPress/gutenberg#45374]
### Description

When creating a tag or category template for a specific term from within the Site Editor, the title of the new template incorrectly shows 'Not found'.

<img width="975" alt="image" src="https://user-images.githubusercontent.com/1645628/198579457-50b0b69e-4ab3-476c-b264-67d88021ea37.png">

First reported on trac: https://core.trac.wordpress.org/ticket/56902

### Step-by-step reproduction instructions

1. Activate Twenty Twenty-Three theme.
2. Create a new tag or category template for a specific item.
3. Observe the success notification at the bottom and Not Found: (template_name) at the top toolbar or at the template list.

### Screenshots, screen recording, code snippet

_(Shared by @franzaurus on the Trac ticket; added here by @ockham.)_

| Upon creation | Template list |
|---------------|--------------|
| ![SkXaUm8 - Imgur](https://user-images.githubusercontent.com/96308/199032771-71653973-5fdb-413d-bc72-0d805a497708.png) | ![A7tYqsj - Imgur](https://user-images.githubusercontent.com/96308/199032756-fa5e7a5c-a83b-492c-9d2c-de5f513bb234.png) |

Screen recording

![oykgMV0 - Imgur](https://user-images.githubusercontent.com/96308/199032742-36de0d10-f412-4644-8f8a-6bea9c932254.gif)

### Environment info

- WordPress 6.1 RC4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ockham** [comment]
cc/ @ntsekouras @jorgefilipecosta for custom template creation expertise 😄

**Comment by jorgefilipecosta** [comment]
This is a core-specific issue (the problem does not affect the Gutenberg plugin), and a fix is available at https://github.com/WordPress/wordpress-develop/pull/3564. It is very important to get this on 6.1.1.

**Comment by Mamaduka** [comment]
The fix was cherry-picked for WP 6.1.1.
