### ISSUE TITLE
Components: ToggleControl text overflows when it has a long label

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#45381]
### Description

`ToggleControl` text overflows when it has a long label.
As the label gets longer, the text overshadows the toggle button.

### Step-by-step reproduction instructions

- Access[ the ToggleControl section of the Storybook](https://wordpress.github.io/gutenberg/?path=/story/components-togglecontrol--default).
- Enter long text in the control panel label.
- Ensure that the text covers the toggle button as the label gets longer.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/198607294-f0e1933d-6960-4dbc-bd60-f90a22e19f49.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sharukhkhanajm** [comment]
Hi, @t-hamano I am trying to fix this bug and found a solution but need some advice.
As to solve this bug I will have to change the **HStack** display from `flex` to `grid`.
@mirka  Can I do that?

I need to add this CSS on the **HStack** container
`display: grid;`
`grid-template-columns: auto 1fr;`


https://user-images.githubusercontent.com/47321682/198815940-5a7fb9cb-b65f-47ef-96ee-d463be337857.mov

**Comment by t-hamano** [comment]
@sharukhkhanajm 

Thank you for your interest in this issue.
`HStack` is a component for arranging child elements horizontally in a Flex layout. For a grid layout, the [Grid](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/grid) component would be appropriate.

Alternatively, I believe that the following style could be applied to the label to solve the issue:

```
flex-grow: 1;
flex-basis: 0;
```

**Comment by sharukhkhanajm** [comment]
@t-hamano 

Thanks for the new CSS properties they look appropriate in this case.
since I am new to contributing to this project will you make these changes or i can do that?

**Comment by t-hamano** [comment]
@sharukhkhanajm 

Your PR is always welcome.
The following documents may be helpful:

- [Getting Started With Code Contribution](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/getting-started-with-code-contribution.md)
- [ToggleControl component README](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/toggle-control/README.md)

Of course, I'm happy to help 👍

**Comment by devanshijoshi9** [comment]
Hey @t-hamano 👋 

It would be helpful if you provide the status of this issue. This issue is still present so does anyone working on this issue or can I create PR to resolve this issue?

Thanks

**Comment by t-hamano** [comment]
@devanshijoshi9 
Thanks for your interest in this issue. I know @sharukhkhanajm is trying to solve this problem, but if you can work on this problem, PR is welcome.

**Comment by devanshijoshi9** [comment]
@t-hamano Thank you for the quick response.

I have created PR for this issue -> https://github.com/WordPress/gutenberg/pull/45962
