### ISSUE TITLE
`TabPanel`: add support for manual activation of tabs

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#45390]
Currently the `TabPanel`'s tabpanels are activated automatically when the associated tab receives focus (referred to as "Tabs with automatic activation" on [the W3C website](https://www.w3.org/WAI/ARIA/apg/patterns/tabpanel/)).

However, as discussed in https://github.com/WordPress/gutenberg/pull/44788#issuecomment-1293826203 and in https://github.com/WordPress/gutenberg/pull/45203#discussion_r1006643474, there instances in which the automatic activation doesn't fit the UX and keyboard navigation needs.

We should look into allowing the `TabPanel` to support manual activation as well, alongside automatic activation.

**Comment by ciampo** [comment]
Opened a related request for the `ariakit` components — we could consider switching to `ariakit`'s implementation directly, if/when manual activation is supported https://github.com/ariakit/ariakit/issues/2007

**Comment by ciampo** [comment]
Update — `ariakit`'s `Tab` component actually already supports manual tab activation — my proposal here is to refactor the component to use `ariakit` instead of working on a custom implementation in the repo.

**Comment by alexstine** [comment]
@ciampo Any idea when this might get some priority? I hate that this is now going to be a longer process and it is an active blocker for better implementation. Makes me wonder if we should patch this ourselves and make it a project for 6.2/6.3/beyond.

Thoughts?

**Comment by ciampo** [comment]
> Any idea when this might get some priority?

We don't have yet a precise timeline, but as of now we're hoping to start work on this sooner than later (cc'ing @ramonjd @talldan as we recently spoke about who potentially could work on the `TabPanel` refactor to `ariakit`)

> I hate that this is now going to be a longer process and it is an active blocker for better implementation. Makes me wonder if we should patch this ourselves and make it a project for 6.2/6.3/beyond.

As it often happens, this is mostly a matter of assigning resources and prioritization — time spent on `TabPanel` is time that is not spent on another part of the project.

Also, implementing this feature on the current implementation of `TabPanel` can definitely be done, but it will still require time nonetheless. I would argue that the most efficient use of our time would be to work directly on the migration to `ariakit`, although that may take longer than adding this feature to the current implementation.

Having said that, I'll see If I can find some time in the next days to explore adding manual tab activation to the current version of `TabPanel` — I'll do so keeping in mind that the component will likely be migrated to `ariakit` in the near future.

**Comment by alexstine** [comment]
@ciampo Can we just re-open #45411 and go from there?

Thanks.

**Comment by talldan** [comment]
> We don't have yet a precise timeline, but as of now we're hoping to start work on this sooner than later (cc'ing @ramonjd @talldan as we recently spoke about who potentially could work on the TabPanel refactor to ariakit)

I'd like to do this, as there seem to be lots of problems with TabPanel. It is unfortunately fairly low on my list atm. It might be two to three weeks before I can work on it again, sorry to get your hopes up! If anyone else wants to take a look at it, I'm happy to support that with reviews.

**Comment by ntsekouras** [comment]
>@ciampo Can we just re-open https://github.com/WordPress/gutenberg/pull/45411 and go from there?

Unfortunately that PR wasn't implementing what we wanted to, so there is no prior art for solving this in GB..
