### ISSUE TITLE
File Block: Missing backward compatible styles for classic themes

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#45399]
### Description

In #41822, the button element styles were moved from each block to `theme.json`. And the style for representing the download button in the file block has also been removed from the block's stylesheet. Since there are no backward-compatible styles for the file block, classic themes without theme.json will apply unnatural styles:

- The button-like style of the download button is lost.
- When the focus is on the download button, the text color is white, making it invisible.

Just as [the button block provides backward-compatible styles for the classic theme](https://github.com/WordPress/gutenberg/blob/3c9a0207f51d731ff4d8cfbfa69daa16f797639f/packages/block-library/src/classic.scss#L1-L15), I believe that this should be done for the file block as well.

### Step-by-step reproduction instructions

Classic themes such as Twenty Twenty One and Twenty Twenty cannot be reproduced because they have styles for file blocks. Therefore, create a plain theme with the following files:

`style.css`

```css
/*
Theme Name: Empty Classic
*/

```

`index.php`

```php
<?php
wp_head();

if ( have_posts() ) {
	while ( have_posts() ) {
		the_post();
		the_content();
	}
}

wp_footer();

```

- Insert a file block.
- Confirm that the style of the download button is lost in both the editor and the front end.
- Confirm that the text disappears (turns white) when the download link is focused on, for example, by mouse-over.

## WordPress 6.0

Has the button-like style.

![wp6 0](https://user-images.githubusercontent.com/54422211/198822582-e642af98-ffdf-48d1-a9ce-84e74783ad3c.png)

## WordPress 6.1

The style of the download button is lost.

![wp6 1](https://user-images.githubusercontent.com/54422211/198822606-45c9dd9a-b523-4a13-85d5-75a9d731e42c.png)

The text disappears (turns white) when the download link is focused.

![wp6 1_hover](https://user-images.githubusercontent.com/54422211/198822608-6387bc6c-4c72-437c-81df-113070f844dc.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mpkelly** [comment]
I am going to take this on now

**Comment by t-hamano** [comment]
Thank you for addressing this issue, @mpkelly !

**Comment by t-hamano** [comment]
Hi @mpkelly,

 Just wanted to know if you were addressing this issue. If it is too difficult for you to tackle, I will be happy to help 👍

**Comment by mpkelly** [comment]
Hi @t-hamano, I'm unlikely to work on it in the near future, so please go ahead.
