### ISSUE TITLE
Image: Add placeholder block state when adding from inserter

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#454]
![image](https://wpcoredesign.mystagingwebsite.com/gutenberg/Image,%20Empty,%20Hover.png)

The flow for inserting an image is:

1. click the inserter
2. click image block
3. a placeholder is inserted, and the media library is opened
4. pick an image from the media library
5. the placeholder is replaced by the image

If you close the media library in step 4 without picking an image, you'll still see the placeholder.

**Comment by jasmussen** [comment]
Per a discussion in #317, perhaps we should make an exception for images and galleries, and skip the placeholder? That is, you invoke the inserter, click image, and are then immediately taken to the "insert image" tab in the media library. Same with gallery, except you are taken to the gallery tab.

In both cases, dragging image(s) into the editor should upload & insert.

**Comment by jasmussen** [comment]
Here's a new mockup for creating galleries via the media library, as opposed to via placeholders. If we like that, we should probably do the same for images: https://github.com/WordPress/gutenberg/issues/317#issuecomment-297670447

**Comment by mtias** [comment]
Update: we still need the image placeholder state because if dismiss the media library after it pops up, an empty block remains. Also the empty state will show through behind media library.

**Comment by jasmussen** [comment]
Added flow description based on recent discussions.
