### ISSUE TITLE
Remove default font weight on Pullquote Paragraph

### ISSUE THREAD

**Issue by monika-12** [WordPress/gutenberg#4540]
## Issue Overview
Remove Default font-weight on paragraph in Pullquote block. There is already formatting option to bold the text so user don't need default font-weight on text. It's confusing for user.

## Steps to Reproduce (for bugs)
1. Insert  Pullquote block
2. Enter any paragraph
3. Displayed in bold format

Using Firefox web browser on Windows-10

## Expected Behavior
Paragraph should display like normal text we can format it using bold option.

## Current Behavior
Displayed in bold format.

## Possible Solution
Remove Font-weight from ".wp-block-pullquote > .blocks-editable p" class

## Screenshots / Video
![pullquote-para](https://user-images.githubusercontent.com/17018981/35036380-339a984c-fb9a-11e7-8f39-09ad0b77afa8.png)

**Comment by karmatosed** [comment]
+1 to removing the default font weight.
