### ISSUE TITLE
getThemeSupports doesn't recognize custom theme supports

### ISSUE THREAD

**Issue by simom** [WordPress/gutenberg#45402]
### Description

I've added a custom theme support in the theme and inside a custom block, created with the create-block functionality, if I try to access to the getThemeSupports data only the core defined supports are returned. 

### Step-by-step reproduction instructions

To access the theme supports I've used:
```
const supports = useSelect( (select) => {
    return select('core').getThemeSupports()
})
```
In the functions.php file of the theme (tested on TwentyTwentyThree), I've added the following code:
```
add_action( 'after_setup_theme', function() {
	add_theme_support( 'custom-support' );
} );
```

### Environment info

- WordPress 6.1-RC5-54715

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @simom

The custom theme support needs to be properly registered for it [to be available via REST API](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/rest-api/endpoints/class-wp-rest-themes-controller.php#L294-L298).

## Example

```php
add_action( 'setup_theme', function() {
	register_theme_feature(
		'custom-support',
		array(
			'description'  => __( 'A custom feature support description' ),
			'show_in_rest' => true,
		)
	);
} );
```

See `register_theme_feature` method for more details: https://developer.wordpress.org/reference/functions/register_theme_feature/

**Comment by simom** [comment]
Hi @Mamaduka,
thanks for reply, I forgot to mention this part, yes, I've added the support with the `register_theme_feature` but it doesn't show in the themeSupports object.

**Comment by Mamaduka** [comment]
That's odd, I'm not able to reproduce the issue. I can see the custom theme feature returned by the selector.

## How to test
Run the following code in the DevTools console while in the post editor:

```
wp.data.select('core').getThemeSupports();
```

## Screenshot
![CleanShot 2022-10-31 at 15 39 32](https://user-images.githubusercontent.com/240569/198999805-c5bfa6a7-c113-47af-ae6d-89a369c2a777.png)

**Comment by simom** [comment]
Still can't see the support, I'm using the TwentyTwentyThree theme, and in the functions.php file I've the following code:
```
add_action( 'setup_theme', function() {
	register_theme_feature(
		'custom-support',
		array(
			'description'  => __( 'A custom feature support description' ),
			'show_in_rest' => true,
		)
	);
} );

add_action( 'after_setup_theme', function() {
	add_theme_support( 'custom-support' );
} );
```

**Comment by Mamaduka** [comment]
I believe that's the issue. The [`setup_theme` action runs](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-settings.php#L544) before `functions.php` is loaded, so your action callback won't run.

If you've to use the `functions.php` file, try using the `after_setup_theme` hook for registering theme features with lover priority, like 1 or 0.

**Comment by simom** [comment]
Oh, my bad, thank you so much for your help!
