### ISSUE TITLE
Paste handler: No way to support non-image file types

### ISSUE THREAD

**Issue by codebykat** [WordPress/gutenberg#45408]
### Description

We have some custom media blocks over on Day One and I'm attempting to support uploads via paste and drag and drop.

Adding a raw handler transform works fine for the image block, since the paste handler finds the transform and passes it through. However, I can't generalize this code to support video/audio/pdf, because it turns out the file paste handler [only allows image files through](https://github.com/WordPress/gutenberg/blob/3c9a0207f51d731ff4d8cfbfa69daa16f797639f/packages/block-editor/src/components/rich-text/file-paste-handler.js#L9).

This seems to be at odds with how the raw handler works, since the raw handler [looks at block transforms](https://github.com/WordPress/gutenberg/blob/626cb0d15aa7423f9713dd88c7d791ae35329ef0/packages/blocks/src/api/raw-handling/html-to-blocks.js#L26) to see if anything matches.

It seems like there's no way to filter the supported files here and I need to basically re-implement the entire paste handler (though the rich text component included by the standalone editor will still include the default one). Is that correct or is there another way to tackle this?

### Step-by-step reproduction instructions

Add a raw transform to any block with a file type other than image. Paste that file into the editor and note that the paste handler does not call the transform.

### Environment info

`@wordpress/block-editor` @ 9.3.0 (standalone)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment]
Could we use https://developer.wordpress.org/reference/functions/get_allowed_mime_types/?

**Comment by codebykat** [comment]
I guess it didn't get linked here, but we discussed in Slack and this would be solved by https://github.com/WordPress/gutenberg/pull/45891
