### ISSUE TITLE
Inline inserter visibility sometimes gets stuck and doesn't hide correctly

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#45418]
The inline Inserter button appears when you cursor between blocks.

Generally it works well, but occasionally it fails to hide itself and will persist on the canvas as you navigate around the editor. 

The easiest way to replicate seems to be: Expose the inline inserter then move the cursor away from the canvas, e.g. to the Inspector panel.

https://user-images.githubusercontent.com/846565/199019135-408d081b-f09c-4b8c-8174-b63a36826f5e.mp4

cc @youknowriad

**Comment by youknowriad** [comment]
This is Chrome right? Cause I'm not able to reproduce on Safari.
