### ISSUE TITLE
twitter profile verification

### ISSUE THREAD

**Issue by AlanBell** [WordPress/gutenberg#45416]
## What problem does this address?
link verification in the profile is great for blogs and sites where you can put a rel=me link, but it would be good to cross verify to twitter in a low friction way.

## What is your proposed solution?
expand services/verify_link_service.rb so that if a twitter handle is present, such as @sometwitteruser it will check twitter to see if the current name for that handle is set to @user@mastodon.instance so to verify a twitter handle you change the twitter display name to reference your mastodon name. As with the other verification this would only happen on save, so you could change it back on twitter afterwards if you wanted to.

**Comment by Mamaduka** [comment]
Hi, @AlanBell

I'm guessing this should be an issue for the Mastodon repo, not Gutenberg.

**Comment by AlanBell** [comment]
oh, how the heck did I fail that hard at creating an issue! sorry about the mess!
