### ISSUE TITLE
Coding Standard: use 'esc_url' for 'get_author_posts_url' in 'packages/block-library/src/avatar/index.php': line 103

### ISSUE THREAD

**Issue by hz-tyfoon** [WordPress/gutenberg#45426]
### Description

this was created in core trac: https://core.trac.wordpress.org/ticket/56829

Note: It's a basic security practice to use `esc_url` where appropiate

### Step-by-step reproduction instructions

In here: https://github.com/WordPress/gutenberg/blob/f131c1f73f796272cb28e43fe73af11a647c0d06/packages/block-library/src/avatar/index.php#L103 
`get_author_posts_url` method should be used with `esc_url`.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by TremiDkhar** [comment]
This issue has been resolved via PR #45427, I believe we can close the issue.

**Comment by mirka** [comment]
Thanks!
