### ISSUE TITLE
Multisite - Navigation Links when importing demo content are not working

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/gutenberg#45438]
### Description

When I import theme demo on a normal installation, links in the navigation are working as expected and opening the right pages. When I import the same demo on the multisite, links are not working. Not sure if this is a bug or I need to add the url part in .xml file other way. Tagging @spacedmonkey . Maybe I'm missing something or it's a cache issue but I just can't get it to work on my end.

### Step-by-step reproduction instructions

1. I've exported demo content for our block theme and manually changed the link in the navigation, this way:. 
2. I imported demo to the normal installation and all works good
3. after I tested it on the multisite and the same is not working right, it adds /home-one/ to the root website address instead to the sub.
4. You can test it by installing WordPress 6.1, default theme and by adding few pages and assigning them to the header part, exporting .xml file and importing to the fresh installation on multisite.  I can share a theme file with you via email if needed. 

### Screenshots, screen recording, code snippet

Normal Installation:
![Screenshot 2022-11-01 at 09 45 39](https://user-images.githubusercontent.com/20610429/199195634-334b8f63-90fe-4ac8-a4a4-3941649e59c1.png)
![Screenshot 2022-11-01 at 09 45 51](https://user-images.githubusercontent.com/20610429/199195648-7ddfaf05-0fc9-44f6-aa31-811e9f723d57.png)

Multisite:
![Screenshot 2022-11-01 at 10 36 45](https://user-images.githubusercontent.com/20610429/199204790-0fde4332-11e3-4b1f-8d47-0fc2885155d4.png)
![Screenshot 2022-11-01 at 10 36 56](https://user-images.githubusercontent.com/20610429/199204799-3378ed78-4f88-474f-8c17-afe53723ac10.png)

![Screenshot 2022-11-01 at 09 38 22](https://user-images.githubusercontent.com/20610429/199195658-43b90cb0-e6ea-48f8-8c2f-97dd87c0e171.png)
![Screenshot 2022-11-01 at 09 38 30](https://user-images.githubusercontent.com/20610429/199195672-ae37cb32-eb51-40fc-8d11-d4d9c0a5313c.png)

### Environment info

-WordPress 6.1 and 6.0, using Basti theme but same happens with default theme
- Gutenberg not installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
cc @getdave, @draganescu

**Comment by draganescu** [comment]
@anarieldesign does the same operation work with WP6.0? Or is this an older problem? The navigation block seems to just render the url of the page or post. This URL comes from the LinkControl which has not been changed significantly ...

**Comment by anarieldesign** [comment]
@draganescu it happens also in 6.0 and it's related to the multisite installations.

**Comment by getdave** [comment]
Here is where the link of the Navigation Link block is set when rendered on the front fo the site

https://github.com/WordPress/gutenberg/blob/eb3faf6ffac764ef9b7293750c45fa94d1d6c348/packages/block-library/src/navigation-link/index.php#L174

It comes from the attributes set on the block. So I'm assuming the bug is likely to be found in the importer or exporter in relation to multi-site rather than the block itself.

**Comment by anarieldesign** [comment]
@getdave is it possible to add something to .xml file to make this work for multisite?

**Comment by getdave** [comment]
@anarieldesign I'm not very familiar with the XML export / import features or the way the data is handled for multi-site.

I've tagged for triage so @ndiego and team will take a look and see who might be able to help out with this one.

**Comment by ndiego** [comment]
@anarieldesign just checking in on this issue. I assume you are still experiencing issues with this on multisite, but are you able to confirm?

**Comment by priethor** [comment]
Closing this issue as it's been stale for a long time. Please feel free to reopen if the issue still persists, @anarieldesign!
