### ISSUE TITLE
Navigation List View: Create a drill down navigation panels system

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#45439]
As outlined in https://github.com/WordPress/gutenberg/issues/42257, when users click on the pencil icon next to a Navigation Item, a new sidebar panel should open allowing them to edit the details for that link item:

<img width="179" alt="Screenshot 2022-11-01 at 10 28 04" src="https://user-images.githubusercontent.com/275961/199213615-dac1b7b4-5301-4709-830a-d4a0c49e008b.png">

**Comment by getdave** [comment]
# Info

- `packages/block-editor/src/components/block-inspector/index.js` is the component for the sidebar
- [Navigator component for nested views](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-navigator--default)
- [prior art](https://github.com/WordPress/gutenberg/pull/43037/commits/4ef07e9c11bb2220b0b18d6534f207429f3b19bf#diff-068538657061c47f0a58cfc331259bbeabe11bcc0c576a0cc496d262e5b0038cR135-R150)

**Comment by scruffian** [comment]
@getdave I think we can close this since we have the back button and follow up issues. what do you think?

**Comment by getdave** [comment]
Yep the basic system is in place.
