### ISSUE TITLE
Page List: Allow filtering by a parent page

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#45449]
The Page List block should allow users to show Pages which are children of the parent Navigation item under which the submenu is nested, when the parent item is a page or hierarchical term.
<img width="250" alt="Screenshot 2022-11-01 at 12 01 00" src="https://user-images.githubusercontent.com/275961/199228074-2b10382f-36d4-4fec-b2a1-05a0e5930583.png">
<img width="329" alt="Screenshot 2022-11-01 at 12 00 44" src="https://user-images.githubusercontent.com/275961/199228076-f2413ee7-ac81-454b-9cdc-0d4409650413.png">

**Comment by skorasaurus** [comment]
Would you consider this to be a duplicate of https://github.com/WordPress/gutenberg/issues/31063?

**Comment by scruffian** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/31063
