### ISSUE TITLE
Navigation List View: Conditionally enabled/disable block selection in the canvas

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#45440]
When you select a block in the list view, the corresponding block is selected in the canvas.

As outlined in https://github.com/WordPress/gutenberg/issues/42257, in the Navigation List View, we want to disable this behaviour so that users can interact with Navigation Item blocks and drill down into them without these items being selected, which would open the block's inspector controls.

**Comment by georgeh** [comment]
I'm going to take a stab at this. Should I be using the branch from #44534 would as a starting point?

**Comment by scruffian** [comment]
@draganescu I think we can close this now right?

**Comment by draganescu** [comment]
Yes. Let's close it.
