### ISSUE TITLE
Navigation List View: Add an "edit" option

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#45442]
As outlined in https://github.com/WordPress/gutenberg/issues/42257, we need to give users the option to edit Navigation Items. 

Ideally this should be according to this design:
<img width="240" alt="Screenshot 2022-11-01 at 11 31 35" src="https://user-images.githubusercontent.com/275961/199223559-504b1bbd-9dac-409f-a782-d9fb940998c1.png">

If it's faster to do this in another way in order to get a prototype together, we should also consider that option.

**Comment by georgeh** [comment]
I'm looking at the interactions shown in [this video](https://github.com/WordPress/gutenberg/issues/42257#issuecomment-1284797475) on #42257 

I see 2 interactions in that video:

1. Editing a Page List block should trigger the "Convert to Links" modal
2. Editing another block should slide in an inspector panel for editing that block's attributes

**Comment by scruffian** [comment]
This is covered by https://github.com/WordPress/gutenberg/pull/45815 for now.

**Comment by georgeh** [comment]
@getdave I'm reopening this one to focus on the convert-to-links modal

**Comment by getdave** [comment]
> to focus on the convert-to-links modal

Sounds good. Thanks 🙇 Any ideas yet on what specifically will you tackle and in what order?

**Comment by scruffian** [comment]
I'm going to close this as the basic issue is done. If there's more work to do lets create a more specific issue. Thanks!
