### ISSUE TITLE
Navigation List View: Add a block appender

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#45445]
As outlined in https://github.com/WordPress/gutenberg/issues/42257 we need to add a block appender to the Navigation List View to allow users to add more items to their navigation:

<img width="237" alt="Screenshot 2022-11-01 at 11 37 21" src="https://user-images.githubusercontent.com/275961/199225387-18491337-b2d1-43cf-8c4c-19d6469741ce.png">

This will probably require us fixing this issue at some point: https://github.com/WordPress/gutenberg/issues/18295

**Comment by getdave** [comment]
FYI the _end_ of [this video](https://github.com/WordPress/gutenberg/issues/42257#issuecomment-1284797475) has a small snippet where the expected UI is detailed 

**Update**: here's a screenshot

<img width="653" alt="Screen Shot 2022-11-21 at 13 20 39" src="https://user-images.githubusercontent.com/444434/203065592-1952281c-fce6-43b9-b9a3-2b268cec09b1.png">

**Comment by getdave** [comment]
@SaxonF I wonder could you confirm how you see this appender working? Is it _always_ at the end of the list of items as per the prototypes? Or can it appear elsewhere?

Any other detail, mockups or guidance at this point before we go too far would be much appreciated 🙇

**Comment by SaxonF** [comment]
@getdave let's start with always at the end but the "trigger" for the add menu item dialog should be able to appear anywhere so that we can play with its position easily in future.

**Comment by getdave** [comment]
@ajlende Status update: I continued working on your PR to add the necessarily functionality but it started getting unwieldy pretty quickly.

I spoken with @scruffian and decided to also explore a simpler approach using the standard inserter from the canvas.

So we have x2 PRs that are variations on the same effort:

- https://github.com/WordPress/gutenberg/pull/4590
- https://github.com/WordPress/gutenberg/pull/45947

The basic problem is:

- there are only two standardised appender components in Gutenberg Core - block and default
- neither fit use case for what is in design (above)
- creating a custom appender is possible either by passing props to existing appenders or using `<Inserter>` directly. Both pose problems and require reimplementing logic (see my PRs).
- we need to avoid getting bogged down in refactoring when we are not sure of the solution we want to achieve.

At this point both PRs need review and feedback.

The next step is to break out the changes to the Offcanvas List View that diverge it from primary LV into a separate PR:

- adding `clientId` prop
- include a custom `style.scss` file

We can also invite design feedback and fix any items from code review.

I was aiming to merge a simple PR that "just works" and then move on to address the other UX issues in follow ups. The most important is making the inserter popup appear in the sidebar not the canvas.

**Comment by getdave** [comment]
Done in https://github.com/WordPress/gutenberg/pull/46013. cc @SaxonF
