### ISSUE TITLE
Navigation List View: Move the navigation selector to the dot menu

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#45444]
As outlined in https://github.com/WordPress/gutenberg/issues/42257, we should move the navigation selector to the dot menu, so that it's not a primary action:

<img width="237" alt="Screenshot 2022-11-01 at 11 36 10" src="https://user-images.githubusercontent.com/275961/199224252-e6f43c65-03c2-4e77-ac10-62ca1f00fd5a.png">

Should be closed by https://github.com/WordPress/gutenberg/pull/44534

**Comment by scruffian** [comment]
@draganescu I think we can close this one

**Comment by draganescu** [comment]
Yes.
