### ISSUE TITLE
Global Styles: Allow access to style variations from any theme

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#45452]
## What problem does this address?
Users should be able to select style variations from any theme - not just the ones that ship with their theme. 

## What is your proposed solution?
There are a few options:
1. A styles gallery of all styles for all themes, so users can choose the one they want - like the pattern gallery
2. We allow the site editor to access styles for all installed themes so users have a much bigger choice.

This work will probably depend on getting this issue closed: https://github.com/WordPress/gutenberg/issues/42732

We also should consider how users could preview their theme with these styles in a gallery of tiles, rather than having to click and select each one.

**Comment by scruffian** [comment]
Similar to https://github.com/WordPress/gutenberg/issues/45371

**Comment by jasmussen** [comment]
https://github.com/WordPress/gutenberg/issues/45371 was updated to include mockups that address this. What do you think?

**Comment by scruffian** [comment]
Love it! I think we can close this in favour of #45371.
