### ISSUE TITLE
Remove the "Extended Settings" wrapper

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#4545]
## Issue Overview
The "Extended Settings" panel appears in the sidebar if any custom sidebar meta boxes are registered. This is an expandable wrapper panel for the custom sidebar meta boxes.

I think we should consider removing this wrapper panel and display the custom meta boxes in the same way that each of the default sidebar panels are displayed. This means that custom meta box panels remain just as discoverable as the default panels.

## Expected Behavior
On a site with a custom sidebar meta box, I'd expect the meta box to appear in the same way that the built-in meta box panels do.

## Current Behavior
The custom sidebar meta box is unnecessarily hidden behind the "Extended Settings" toggle.

## Possible Solution
Display custom sidebar meta boxes in the same way that built-in meta box panels are displayed.

**Comment by StaggerLeee** [comment]
What is this block doing anyway ?
I have some metaboxes from plugins and clicking on "Extended Settings" header does nothing.

**Comment by hedgefield** [comment]
I agree, it's an extra click that's not necessary, the metaboxes contained within are already styled to match Gutenberg.

@StaggerLeee it contains metaboxes that were located in the side column in the classic editor (such as the yoast internal linking metabox). If a plugin only had a wide metabox, that appears below the editor yeah.

**Comment by StaggerLeee** [comment]
Don´t know if I found a bug or. It is empty (2 instalaltions) unless i disable/enable all plugins. on second installation switch to default theme/come back to custom one. Then all Metaboxes appear in righ sidebar. Those what should appear anyway.

#https://github.com/WordPress/gutenberg/issues/4887

**Comment by hedgefield** [comment]
Might also solve #5177.

**Comment by karmatosed** [comment]
If I am right you are suggesting moving the metaboxes from below content to the sidebar? If I am correct in that then I wouldn't suggest that from a design point of view. It is a smaller area and confuses content types. Also some of the rich metaboxes could get really confusing. I am checking that is what is being suggested though. Let me know if not.

**Comment by johnbillion** [comment]
Nope, nothing to do with the meta boxes that appear below the main content. It's just wrapper of the `Extended Settings` in the sidebar that should be removed, so any meta boxes that are contained within it appear in the same manner as all the other meta boxes in the sidebar.

**Comment by karmatosed** [comment]
Thanks for clarifying, I was a little confused on where we were going :)

**Comment by illyaking** [comment]
I use the Extended settings for WP Multisite Crosspost. 
The dialogue box to type in boxes are extremely narrow and almost unusable. I have to switch back to classic editor to cross post, which messes up my post :(
Here is what I see...
![extendedsettings01](https://user-images.githubusercontent.com/30247469/38963216-ada08dd6-4325-11e8-9d84-d273633e277e.JPG)

**Comment by spwarner** [comment]
As a plugin author who uses side metaboxes, I'd like to see this change implemented. The extra "Extended Settings" panel is just a bother!

**Comment by claytoncollie** [comment]
Please remove

**Comment by karmatosed** [comment]
I think in context this is fair to do. Let's remove the design feedback and get this moved to a PR.

**Comment by leahkoerper** [comment]
I'm stoked to see this moved into the 5.0 milestone! Thank you!

**Comment by danielbachhuber** [comment]
> I'm stoked to see this moved into the 5.0 milestone! Thank you!

To clarify, I initially added to the `WordPress 5.0` milestone to make sure the issue was addressed prior to 5.0, not as affirmation of the suggested change.
