### ISSUE TITLE
A Post Format Default Block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#4546]
Let's update the default block whenever a different post format than "Standard" is set for the site/user. Example: if default post format is chosen to be "Image", the default block should be an image.

**Comment by youknowriad** [comment]
The default block is used as a way to say "default paragraph block" in several places (text interactions etc...), if we use an image block as a default block, I'm afraid it will break some interactions.

**Comment by mtias** [comment]
@youknowriad that doesn't sound great :) We could do it with templates if that makes more sense.

**Comment by mtias** [comment]
This is implemented.
