### ISSUE TITLE
Disabling Heartbeat API prevents loading editor

### ISSUE THREAD

**Issue by Grezvany13** [WordPress/gutenberg#4547]
## Issue Overview
When the Heartbeat API is disabled on a website (see reproduction steps on how), then none of the required scripts will be loaded which are needed for the edit page to be rendered.

## Steps to Reproduce (for bugs)
1. Have a new/blank WP setup with Gutenberg installed and activated
2. Deactivate the Heartbeat API through a plugin or theme with the following code:
```
// disable Heartbeat
add_action('init', function() {
    wp_deregister_script('heartbeat');
}, 1);
```
3. Create a new or edit an existing post/page with the Gutenberg editor

## Expected Behavior
- The editor should work even when the Heartbeat API is disabled, just like the current "classic" editor.
- Alternatively an error message should be shown/generated indicating that the editor could not be loaded properly and only the classic editor is available.

## Current Behavior
- no errors (either JS or PHP) are generated
- empty page is shown
- none of the plugin javascript files are loaded in the DOM

## Possible Solution
- remove dependency for the Heartbeat API
https://github.com/WordPress/gutenberg/blob/0940478a49ea15c5403285eba83de395e3a7cc5a/lib/client-assets.php#L689-L696

**Comment by adamsilverstein** [comment]
We can probably enqueue heartbeat separately to fix this issue. Note that with heartbeat disabled post locking and autosaves will not work as both features are based on heartbeat.

**Comment by bobbingwide** [comment]
+1. I thought it was just me that did this sort of thing.

**Comment by adamsilverstein** [comment]
Should be fixed in https://github.com/WordPress/gutenberg/pull/4218/commits/8e26470dbd3b777ca017f4f4a29dd51de4f2e56f please test https://github.com/WordPress/gutenberg/pull/4218 to verify that this resolves this issue for you. Hopefully this will get merged soon.
