### ISSUE TITLE
Page List: Display items in the List View

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#45482]
As outlined in https://github.com/WordPress/gutenberg/issues/42257, the items inside Page List should be displayed in the List View:
<img width="252" alt="Screenshot 2022-11-02 at 09 28 06" src="https://user-images.githubusercontent.com/275961/199453712-31eb0ecf-d7fe-4775-869f-3d87f9099744.png">

Previous art: https://github.com/WordPress/gutenberg/pull/39087

**Comment by draganescu** [comment]
I think we only need to implement the edit component using navigation link blocks. And to allow navigation link blocks to be uneditable. But by now I think we can do this with locking.
