### ISSUE TITLE
Styles for core/post-title missing after updating to 6.1

### ISSUE THREAD

**Issue by franrosa** [WordPress/gutenberg#45485]
### Description

Some styles defined for core/post-title in theme.json are not working anymore after updating to WordPress 6.1.

Styles are defined in http://franrosa.com/wp-content/themes/newdev/theme.json

`"core/post-title": {
                "color": {
                    "background": "var(--wp--preset--color--contrast)",
                    "text": "var(--wp--preset--color--background)"
                },
                "typography": {
                    "fontSize": "var(--wp--preset--font-size--mega)",
                    "fontWeight": "400",
                    "lineHeight": "var(--wp--custom--line-height--mega)"
                },
                "spacing": {
                    "padding": {
                        "top": "calc(var(--wp--custom--grid--base)*1)",
                        "bottom": "calc(var(--wp--custom--grid--base)*0)"
                    },
                    "margin": {
                        "top": "0",
                        "bottom": "0"
                    }
                },
                "elements": {
                    "link": {
                        "color": {
                            "text": "inherit"
                        },
                        "typography": {
                            "textDecoration": "none"
                        }
                    }
                }
            }`

Before the update, they were correctly displayed in front. Now they are still being used in the editor, but missing in the front.

Before the update they were printed as inline css:

`<style id='global-styles-inline-css'>
      …
           .wp-block-post-title {
                color: var(--wp--preset--color--toned-black);
                font-family: var(--wp--preset--font-family--public-sans);
                font-size: var(--wp--preset--font-size--big);
                font-weight: var(--wp--custom--font-weight--bold);
                margin-top: 1rem;
                margin-bottom: 1rem;
            }
      …
</style>`

But now they are missing.

### Step-by-step reproduction instructions

1. Go to [franrosa.com](http://franrosa.com/)
2. Styles for post title are not being used — thus displaying wrong size and color

### Environment info

- WordPress 6.1
- Theme: [NewDev](https://github.com/franrosa/newdev)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by franrosa** [comment]
I think I can offer more information on this:
Something has indeed changed with the update, so maybe it will need to be documented.

However, after some investigation, I can confidently say **it is not an error or malfunction**.

Why?
Because the page in question is a page, and not a post; it just had the `.wp-block-post-title` class included in a `wp-block-heading`.

So, removing unnecessary classes — because the `wp-block-post-title` block is not present on the page/template — seems to be an improvement working properly, which had some unfortunate unexpected effect on my theme.

**But it is the theme that needs to be fixed, not core.**

Sorry for the unnecessary issue.

**Comment by bph** [comment]
@franrosa  No worries. Glad there is a solution. 

I was just about to write to you that I was using your theme.json on and empty theme from the create-block-theme plugin and wasn't able to see a discrepancy between editor and frontend in both WordPress versions 6.03 and 6.1

**Comment by franrosa** [comment]
@bph It seems to be a change that is noticeable when visiting pages, as `.wp-block-post-title` class is loading properly when there is a `wp:post-title` block in use — like in posts.

I don't think it will be affecting many themes, but maybe it should be documented, as I was unable to find anything about this change.

Thanks for your help nonetheless.
