### ISSUE TITLE
Pasting from Google Docs removes one level of list indentation

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#45495]
### Description

When I paste a list from Google Docs, one level of indentation is removed.

Google Doc:

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/36432/199546662-177cb030-7025-4c56-bc90-b825546325a1.png">

Gutenberg result:

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/36432/199546761-a5fd04b1-d90a-4cf4-93a8-57cc173f8552.png">

### Step-by-step reproduction instructions

1. Copy list from [this Google Doc](https://docs.google.com/document/d/1BfgnP0k5jpULt9UWgTB9Zb3s72hTh6hNPp52mCpQFfY/edit).
2. Paste into a new post.

### Environment info

- WordPress 6.2-alpha-20221102.090915
- Gutenberg 14.5.0-rc.1
- Firefox 106.0.3 and Chrome 106.0.5249.119 on Mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment]
Should be fixed by #45498.
