### ISSUE TITLE
AutocompleteUI: Forward slash inserter doesn't work in Japanese

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#45496]
### Description

At least in the Japanese input system, the block list are not properly filtered when using the forward slash inserter.

Because of the vast number of characters in the Japanese language ( including Kanji), it is not possible to input characters directly on a standard keyboard. Therefore, after entering "**hiragana**" characters, we choose which character to convert to and confirm with the `Enter` key.

In WordPress 6.0, the autocomplete popover is retained after we press Enter to "submit" a candidate, allowing me to select the block that matches the keyword.

In WordPress 6.1, the forward slash inserter no longer works because the block at the beginning of the candidate is inserted the moment I press the `enter` key. However, autocomplete works correctly when **pasting** a string containing forward slashes.

I believe this problem also occurs in languages where character output must be confirmed with the Enter key, for example Chinese.

### Step-by-step reproduction instructions

Since this test requires the use of Japanese input for keyboard input, I expect users to test the Japanese keyboard.

- Change the site language to Japanese (`日本語`).
- On the block editor, type `/みだし`. `みだし` is a hiragana character used to convert the Japanese translation of "heading" into `見出し`.
- Confirm that the autocomplete popover disappears and the block at the top of the list is inserted unintentionally when the Enter key is pressed to convert it to `見出し`

### WordPress 6.0

1. Autocomplete works correctly when pasting a string containing forward slashes
2. Autocomplete works correctly when the block name "heading" is entered
3. Autocomplete works correctly even if the enter key is pressed to convert the Japanese name of a block in Japanese input

https://user-images.githubusercontent.com/54422211/199558019-c8aa5a99-6536-41b7-9762-bb53ab49ce1b.mp4

### WordPress 6.1 (with / without Gutenberg Plugin)

1. Autocomplete works correctly when pasting a string containing forward slashes
2. Autocomplete works correctly when the block name "heading" is entered
3. Autocomplete **DOESN'T** work correctly when the Enter key is pressed to convert to the Japanese name of a block in Japanese input

https://user-images.githubusercontent.com/54422211/199557994-43d1a607-df1c-4283-9341-3c3848fc8d47.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Thank you for reporting. Added to the 6.1 board for now.

**Comment by t-hamano** [comment]
I'm investigateing this issue:

- Gutenberg13.9.0: Not reproduced
- Gutenberg14.0.0: Reproduced

**Comment by t-hamano** [comment]
I found the cause.
This is due to the difference in the behavior of `code` and `keyCode` in keyboard events.

In #43432, `keyCode` in the autocomplete UI was replaced with `code`. It then detects the `Enter` key and inserts the currently selected block in the autocomplete popover.

Also, as I explained in the first comment on this issue, in Japanese input, after typing "hiragana" character, we choose which character to convert to and confirm with the `Enter` key. And this `Enter` key is NOT for "inserting blocks".

We also found the following difference between `code` and `keyCode` when the Enter key is pressed to finalize a character:

`code`: detect `Enter` key
`keyCode`: Keep the previous key

Here is a screencast showing sample code and behavior.

<details>

<summary>Sample Code</summary>

```html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
</head>
<body>

<input type="text">
<script>
window.addEventListener( 'keydown', ( e ) => {
	console.log( `keyCode: ${ e.keyCode }, code: ${ e.code }` );
});
</script>
</body>
</html>
```
</details>

<details>
<summary>Screencast</summary>

https://user-images.githubusercontent.com/54422211/199696554-a23a5ce9-e22b-4f1b-bf7c-22ff49360fd1.mp4
</details>

As described above, I think that pressing the Enter key to confirm a character is now considered a "block selection" and has caused this problem.

I would like to address this issue.

**Comment by t-hamano** [comment]
@annezazu 
This issue has been resolved by #45510.
Could you move it to the appropriate column on the project board?

**Comment by annezazu** [comment]
Moved to needing to be cherry picked. Thanks so much for working on this!

**Comment by t-hamano** [comment]
I have submitted #45626 as a follow-up PR to #45510 that addresses this issue.
Sorry for the additional response.
