### ISSUE TITLE
Remove backported code from WP 6.0 compat layer

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#45508]
Now that WordPress 6.1 has been released, we should remove the back-compat code for WordPress 6.0 (in `lib/compat/wordpress-6.0/`) from Gutenberg. This is because Gutenberg supports the current and previous versions of WordPress (i.e 6.1 and 6.0); the code in `lib/compat/wordpress-6.1/` is needed to allow it to work on a WP 6.0 installation (which lacks some code that is in 6.1). (OTOH, the `lib/compat/wordpress-6.0/` dir is no longer needed, as it provides backwards compatibility for WP 5.9 and older; but those versions are no longer supported by Gutenberg.)

We should also look out for tests for that code in `phpunit`, make sure that those tests have been carried over to `wordpress-develop` (and add them there if they haven't), and remove them.

We might need to exercise a bit more care when removing code in `lib/block-supports`; I'm not entirely sure how that (unversioned) compat layer is applied to Gutenberg.

cc/ @c4rl0sbr4v0 @ramonjd @oandregal @scruffian in case y'all wanna help with this 😊

**Comment by ramonjd** [comment]
> cc/ @c4rl0sbr4v0 @ramonjd @oandregal @scruffian in case y'all wanna help with this

You bet. I started with typography a while back already: https://github.com/WordPress/gutenberg/pull/43928 Need to dust it off. 

Will be out of action next week, but I'll put this issue on a list to remind my brain.

**Comment by Mamaduka** [comment]
We cannot remove code from the WP 6.1 compat layer, only from 6.0. The plugin still has to support WP 6.0.

**Comment by ockham** [comment]
> We cannot remove code from the WP 6.1 compat layer, only from 6.0. The plugin still has to support WP 6.0.

Of course 🤦‍♂️ Thank you for pointing that out! I'll change the issue title and contents 😅

**Comment by ockham** [comment]
Closed by #46102.
