### ISSUE TITLE
Deleting a paragraph after a columns block adds it to the colums block

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#45511]
### Description

When deleting a paragraph that is found after a columns block it seems there is a bug causing it to be added to the column block as a new column containing an empty paragraph.

### Step-by-step reproduction instructions

1. Make a new post
2. Add a columns block with two equal columns
3. Add a paragraph after the columns block
4. Delete the paragraph with the BACKSPACE key
5. Notice the error
6. Repeat 3-5 and get many unwanted columns

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/107534/199707832-2478d538-b3ad-4229-afc4-e79587ff6a31.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I think this is similar to #45436.

**Comment by draganescu** [comment]
Thanks @Mamaduka it's identical :) to #45436
