### ISSUE TITLE
Duplicate string: 'Distraction free' and 'Distraction Free'

### ISSUE THREAD

**Issue by atachibana** [WordPress/gutenberg#45523]
### Description

In the [Polyglots of Gutenberg](https://translate.wordpress.org/projects/wp-plugins/gutenberg/), we see two string 'Distraction free' and 'Distraction Free'. These are come from:
```
packages/edit-post/src/components/header/writing-menu/index.js
label={ __( 'Distraction free' ) }

packages/edit-post/src/components/preferences-modal/index.js
label={ __( 'Distraction Free' ) }
```
'Distraction free' (lower 'free') is used in most places (ex. 'Distraction free mode turned on.'), so I think it should be consistent with that text. 'Distraction Free' (capitalized 'Free') is used in the following two places (One is snapshot).

```
packages/edit-post/src/components/preferences-modal/index.js
label={ __( 'Distraction Free' ) }

packages/edit-post/src/components/preferences-modal/test/__snapshots__/index.js.snap
Distraction Free
```

### Step-by-step reproduction instructions

n/a

### Screenshots, screen recording, code snippet

See above.

### Environment info

- Gutenberg 14.4.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@draganescu  as a heads up!
