### ISSUE TITLE
Malformed URL params makes get-query-args to throw an error 

### ISSUE THREAD

**Issue by kozer** [WordPress/gutenberg#45558]
### Description

Malformed url params make `get-query-args` function to throw an error.
This breaks calypso.

We can fix the issue by just ignoring malformed params, keeping only those that are not malformed

Please, also check [this calypso issue](https://github.com/Automattic/wp-calypso/issues/69794) more details

### Step-by-step reproduction instructions

1. Try to parse the following `http://calypso.localhost:3000/start/domains?ref=calypso-selector&source=my-home&siteSlug=%E0%A4%A`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by danielbachhuber** [comment]
🔨
