### ISSUE TITLE
Enable shuffling of sections in zoomed out mode

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#45552]
Related to https://github.com/WordPress/gutenberg/issues/44581 and https://github.com/WordPress/gutenberg/issues/44582

In zoomed out view it would be nice to offer a way to shuffle/remix sections where possible:

* Template parts with semantic area (Headers / Footers) can be shuffled.
* Sections with `templateLock:contentOnly` can be remixed.
* _Potentially_: All sections, applying the same logic from https://github.com/WordPress/gutenberg/issues/44581 can be remixed too.

To clarify, 'shuffling' means to cycle between patterns within a category. 'Remixing' means to cycle between any patterns that comprise of the exact same `content` blocks as the selected section.

**Comment by richtabor** [comment]
@jorgefilipecosta worked on a related PR to introduce shuffling via category here: https://github.com/WordPress/gutenberg/pull/59251

**Comment by jameskoster** [comment]
Cool, we can probably close this and explore the 'remixing' idea later if needed.
