### ISSUE TITLE
Site editing: Create a space for the management of Reusable Blocks

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#45550]
Related to https://github.com/WordPress/gutenberg/issues/44461 and a part of https://github.com/WordPress/gutenberg/issues/32682. 

Currently Reusable Blocks can only be managed in a 'legacy' wp-admin view:

<img width="1708" alt="Screenshot 2022-11-04 at 11 35 08" src="https://user-images.githubusercontent.com/846565/199963310-4d0ee1cd-4ac8-433d-a3e2-740cbba1b133.png">

It's tricky to find, and the friction of moving between editor / wp-admin can be quite disruptive. 

Now feels like a good time to explore how we might bring this into the site editing experience, and make the most of the features therein (previews, focussed edit mode, etc). 

As we look into this it would be good also to consider the management of any other site assets we might want to bring into the site editor: Patterns, Fonts, Media, etc.

**Comment by jasmussen** [comment]
Seems like there's an option for a "Library" menu item in #45346 perhaps?

**Comment by jameskoster** [comment]
Yes I think that makes a lot of sense as a top level item, and it would provide a sensible home for the other items mentioned in the OP as well, when we get to them.

Do you think we need to introduce it straight away though? It might be unnecessary at this stage, if it only contains a single item...

I think we have a couple of avenues to explore:

1. Add the Library section now, to include Templates, Template Parts, and Reusable Blocks
2. Add the Reusable Blocks section now, and move it to a Library section later, once there are items to place alongside it (Patterns, Fonts, Media).

So the main question in my mind is whether we want to include Templates in the Library. What do you think?

**Comment by jasmussen** [comment]
I wonder if Templates and Template Parts shouldn't exist in a single "Templates" section, as RBs are a bit different. A Library section with just RBs honestly seems okay to me, especially if we know we'll add more to it.

**Comment by jasmussen** [comment]
Consolidating this one with #50397, but let me know if this was in error and we can reopen.
