### ISSUE TITLE
Custom Blocks: Force External Stylesheets/disable "inline-css"?

### ISSUE THREAD

**Issue by cheestudio** [WordPress/gutenberg#45557]
### Description

I'm using WP 6.1 and the "create-block" scaffolding. All my custom block CSS is being rendered on the front-end as inline styles, e.g.

`<style id='custom-block-page-hero-style-inline-css' type='text/css'>` 

Ironically, in the dashboard, they are coming through as external stylesheets, e.g.

`<link rel='stylesheet' id='custom-block-page-hero-style-css' href='http://localhost/wordpress/wp-content/plugins/custom-blocks/build/page-hero/style-index.css?ver=0.1.0' media='all' />`

How can I replicate this behavior on the frontend? I know inline CSS is faster and WP is really leaning into that, but I really just want external stylesheets, and can't seem to locate any documentation on how to force this behavior.

### Step-by-step reproduction instructions

1. Create custom block with create-block package
2. Write CSS for custom block
3. View backend and frontend

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by cheestudio** [comment]
This post finally shed some light:

https://make.wordpress.org/core/2021/07/01/block-styles-loading-enhancements-in-wordpress-5-8/

In particular, this function:

`add_filter( 'styles_inline_size_limit', '__return_zero' );`

Although the phrasing in the post said "To completely disable _small styles inlining_:", and that confused me (albeit the preceding sentence explained it more accurately). 

Either way, this could absolutely be better documented somewhere! It really should not take digging into blog posts to find this kind of answer to something as glaring as outputting so much code on the frontend of a site.

**Comment by aristath** [comment]
I saw this issue too late to reply, but I'm glad you found it!
Using the `styles_inline_size_limit` filter is the way to disable that functionality like you mentioned in your previous comment 👍
