### ISSUE TITLE
Documentation Request: Working with Post Metadata within a Block

### ISSUE THREAD

**Issue by LearnWebCode** [WordPress/gutenberg#4556]
This isn't an issue, just a request for documentation in the handbook.

If I want to create a block that lets a user type in a number or choose from a list of options, but I don't want to save their choice as part of the post's actual content, and instead want to save it as metadata for the post... is there a Gutenberg idiomatic way of doing that? Or should I just make my own manual XHR and use the REST API to handle the metadata?

Or maybe it's misguided of me to want non-visual content in a block? After reading in the handbook that we're strongly encouraged to use blocks instead of metaboxes I'm a bit cloudy on how to manage post metadata in WordPress moving forward.

For example, what if I want to manage a relationship between one post and another (a piece of metadata that stores the ID number of another post, so that I can query for that relationship on the front-end of the site)... I'm trying to think of the most Gutenberg'ish way of achieving this.

I realize my question at this point is a bit cloudy; but hopefully someone much smarter than I am will read this and know exactly what I'm getting at.

Thanks!

**Comment by youknowriad** [comment]
Yes, Gutenberg blocks can fetch and save data into post_meta using meta attributes. Details on this can be found here https://wordpress.org/gutenberg/handbook/block-api/attributes/#meta

Good luck!

**Comment by LearnWebCode** [comment]
Thank you so much @youknowriad!!! I promise I spent a good deal of time reading the handbook, but never scrolled down to the Meta section on that page. Sorry for the trouble; that's exactly what I was looking and hoping for!  Really impressed with this aspect of Gutenberg; makes structured content/data pretty easy.

**Comment by youknowriad** [comment]
No worries, it's easy to miss docs. Enjoy hacking!

**Comment by elliotcondon** [comment]
Hi guys. I hope you don't mind me adding to this question.

The referenced [Attributes](https://wordpress.org/gutenberg/handbook/block-api/attributes/#meta) doc is helpful, but doesn't mention how we can define the saving proccess via PHP to perform custom logic, validation, saving, etc. 

One paragraph hints this might be possible:

> If you’d like to use an object or an array in an attribute, you can register a string attribute type and use JSON as the intermediary. Serialize the structured data to JSON prior to saving, and then deserialize the JSON string on the server. Keep in mind that you’re responsible for the integrity of the data; make sure to properly sanitize, accommodate missing data, etc.

When it says "deserialize the JSON string on the server" is it suggesting that we can hook in via PHP and properly sanitize prior to saving, or is it saying that WP will save the serialized string as is, and when we load it via PHP, we need to sanitize it then?

**Comment by youknowriad** [comment]
@narendraj9 You can do that using the data module https://wordpress.org/gutenberg/handbook/packages/packages-data/ by calling this selector `wp.data.getEditedPostAttribute( 'content' )`. Be aware that this call can hurt performance if done a lot of times because it serializes the whole post (which can quickly become not performant for long posts).

> When it says "deserialize the JSON string on the server" is it suggesting that we can hook in via PHP and properly sanitize prior to saving, or is it saying that WP will save the serialized string as is, and when we load it via PHP, we need to sanitize it then?

@elliotcondon I think it probably means the latter here. For saving hooks server-side, you should probably check how you can hook into REST API calls to add custom logic. https://developer.wordpress.org/?s=rest_&post_type%5B%5D=wp-parser-hook

**Comment by narendraj9** [comment]
@youknowriad Thanks for the reference to `wp.data.getEditedPostAttribute`. Do you know of a good way to extract information from the text of the post? With this I get HTML that I need to get the text from.

**Comment by youknowriad** [comment]
If this information is saved in a block attribute, it's better to rely on this instead `wp.data.getBlocks()` which gives you the list of blocks and you don't have to parse any HTML in that case.

**Comment by narendraj9** [comment]
Thanks! @youknowriad I ended but reading the text from `content` and `props.children` recursively to get text from all elements. I appreciate the API that the editor provides more now.
