### ISSUE TITLE
Add basic HTML list types to ordered lists

### ISSUE THREAD

**Issue by druxstr** [WordPress/gutenberg#45567]
## What problem does this address?
The list block only support numbers as list type for `<ol>`.

This is an issue, as nested ordered list quickly become confusing :

```
1. Ordered item
    1. Nested item
    2. Nested item
       1. Deeper nested item
2. Ordered item
```
Other list type should be available, so users could write things like : 

1. Ordered item
    1. Nested item
    2. Nested item
       1. Deeper nested item
2. Ordered item

## What is your proposed solution?
Add [basic HTML list types](https://html.spec.whatwg.org/multipage/grouping-content.html#attr-ol-type) to ordered list : 

- lowercase letters
- uppercase letters
- lowercase Roman numerals
- uppercase Roman numerals

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/17738. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

**Comment by druxstr** [comment]
@skorasaurus Hi, could this issue be reopened and #17738 closed as duplicate ?

#17738 originally tried to [solve 2 unrelated problems](17738#issuecomment-1304652567) : it has since been splitted and renamed.

As a result, most of #17738 content is about #45567, and both issues are stuck.

I think that reopening the current issue and closing #17738 could help.

It would give the problem a fresh start.

Thanks for reading.
