### ISSUE TITLE
Dead link in admin menu

### ISSUE THREAD

**Issue by bugsysop** [WordPress/gutenberg#45571]
### Description

In Admin Menu the submenu `Support` lead to an Error 404

The missing page: `https://fr.wordpress.org/support/plugin/gutenberg`

### Step-by-step reproduction instructions

1. Go to Admin Dashboard
2. Hover the `Gutenberg` menu
3. Clic on `Support` submenu

### Environment info

- WordPress 6.1
- Gutenberg 14.4.0
- Environment: Local WP
- Server: Nginx

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for contributing, @bugsysop

The URL is localized for the French translation, but the page is missing from the `fr.wordpress.org.`

It might be a good idea to reach out to the folks who work on French localization since the issue cannot be fixed in the plugin.
