### ISSUE TITLE
useRootPaddingAwareAlignments does not work for users not having edit_theme_options

### ISSUE THREAD

**Issue by christofervas** [WordPress/gutenberg#45573]
### Description

- In WordPress 6.1 `useRootPaddingAwareAlignments` does not work in the block editor for users not having `edit_theme_options` capability.

### Step-by-step reproduction instructions

1. Set `useRootPaddingAwareAlignments` to true
2. Access the block editor with a user not having the `edit_theme_options` capability

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by justintadlock** [comment]
Can you describe what is happening when you say "does not work"?  Is the option appearing but not saving?  Is the option not appearing at all (this should probably be expected behavior)?  Or, is there another more specific issue?

**Comment by christofervas** [comment]
I noticed that when accessing the block editor for example with the "Editor" role the padding is missing. Here are the output of classes using the Twenty Twenty-Three theme:

As an administrator: 
`is-root-container is-layout-constrained has-global-padding wp-block-post-content block-editor-block-list__layout`

As an Editor: 
`is-root-container is-layout-flow wp-block-post-content block-editor-block-list__layout`

**Comment by tellthemachines** [comment]
Thanks for reporting this! The issue was fixed in #45299, which will be included in the next WP version (6.3). 

I double checked and though I can still reproduce the issue in 6.2 without Gutenberg, with the plugin enabled it is no longer reproducible. Closing this as completed.
