### ISSUE TITLE
Saving changes to templates does not hold custom changes

### ISSUE THREAD

**Issue by antpb** [WordPress/gutenberg#45576]
### Description

When saving a page or home page template, the previous default version of the template overwrites any custom changes. 

In the below example I am attempting to save a template with a custom header menu template part called "innerpage" When saving this template, all looks good on the front end. When I click edit site again the editor displays the previous template that I thought I overwrote.

https://user-images.githubusercontent.com/8985705/200198505-d6f5455c-09b1-4c2b-987b-889937af77b8.mov

### Step-by-step reproduction instructions

Use Twenty Twenty Two default theme
Make a page the static homepage of the site.
Make a change to the home page's page template and add a custom template part.
Save changes and view frontend.
Click Edit site
See old template.

### Environment info

WordPress 6.1
Gutenberg Plugin Version 14.4.0  (and also with default core block editor)
Chrome browser, macos

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
@antpb I cannot seem to replicate this on my end. Any other testing instructions? 🤔

**Comment by bph** [comment]
I edited the page template for the front-page twice, the second time I used a custom template part, and I was able to see my changes when I was returning from the front end to the template editor. 
@antpb What I am missing from your instructions? I, however, used Gutenberg 14.5. Could you try it again with the latest release?

**Comment by antpb** [comment]
Thanks for taking a look. I'm not sure how, but after switching hosting (previously it was on a Digital Ocean droplet) the issue stopped happening. I'm not sure if there was some caching happening but it might be a case we want to cover as this was their recommended configuration for WordPress. 

I have another site on the same configuration that I will test against and report back. If I can't reproduce, going to close this out.

**Comment by antpb** [comment]
Yeah it must have been in a very strange stuck state that worked after migrating servers. Tried on another site with the same configuration and no luck reproducing. If I see it again I'll dig deeper and see if I can give better reproduction steps.

Closing for now as not even I can reproduce it now. :(
