### ISSUE TITLE
core/post-content patterns fail to render preview on page creation of patterns referenced within them

### ISSUE THREAD

**Issue by aplauche** [WordPress/gutenberg#45586]
### Description

I noticed I can create page template patterns (that autoload on page creation) fine by building out content in the editor and then copying the code, but I'd like to create these core/post-content patterns with just a few references to my other section style patterns (otherwise there is a lot of repeating the same pattern multiple places making it hard to maintain). When I try to do this manually it breaks the preview when creating a new page. You can see that the "page text basic" renders partly the block markup, but not the included patterns.

For reference, the patterns still work perfectly when you click to insert them, it is just the preview that does not work. I can also insert them, the switch to code, copy everything and use that as a core/post-content pattern and the preview works again. It is just the pattern reference within preview that is breaking.

Full disclosure: this is happening in a custom theme, so could be a syntax issue, but the behavior of the pattern working but not the preview seemed like a possible bug to me, so wanted to flag.

### Step-by-step reproduction instructions

1. add a standard pattern to your block theme like "hero section"
2. create a pattern with Block Types: core/post-content
3. Add the standard pattern to this template like so `<!-- wp:pattern {"slug":"example/hero"} /-->`
4. Create a new page and the preview does not seem to render the pattern

### Screenshots, screen recording, code snippet

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/50935059/200333893-c18e010b-4424-40a8-972b-867f354510b9.png">
<img width="533" alt="image (1)" src="https://user-images.githubusercontent.com/50935059/200333910-8a64caf3-24c7-448a-b846-effb5fc82236.png">
<img width="1167" alt="image (5)" src="https://user-images.githubusercontent.com/50935059/200333931-61a87fd3-8e11-49f7-8159-d211ca1b100e.png">

### Environment info

- WordPress 6.1
- Custom Theme ***This could an issue with the way my custom theme is setup, but the patterns still  work perfectly so the behavior seems like a potential bug and wanted to flag***

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hi @aplauche, this is a known issue and has been fixed in the latest version of Gutenberg. See the related PR here: https://github.com/WordPress/gutenberg/pull/44784. 

Can you try testing again using Gutenberg 14.4? I have tested on my end using the Twenty Twenty-Three theme, and the nested patterns are displaying as expected. Thanks!

**Comment by aplauche** [comment]
@ndiego Thanks for the info! Just tested and can confirm all is working perfectly with Gutenberg 14.4. Closing now!
