### ISSUE TITLE
List-block not functioning properly if being allow-listed via filter...

### ISSUE THREAD

**Issue by E-VANCE** [WordPress/gutenberg#45583]
### Description

I am trying to limit the available blocks in the editor by filtering / "white-listing" blocks via the `allowed_block_types_all`-filter (see snippet below).

This works fine in the sense that only the specified blocks are showing up for selection but I have noticed **a bug regarding the list-block** – I can add the block but I cannot use the "Enter"-key to add a new list item.

I have re-produced and verified the behaviour on a clean WP-install (6.1) with no other plugins activated and the default "Twenty Twenty Two"-theme in use.

Not seeing any console errors – if the problem is related to another missing core-block from which some of the functionality is 'borrowed' then this should probably appear as error message IMO.

### Step-by-step reproduction instructions

- Enable list-block via `allowed_block_types_all`-filter (restricting other blocks)
- Add list block in editor
- Try to create a new list item via hitting "Enter"
- Nothing happens...

### Screenshots, screen recording, code snippet

```
function allowed_block_types($allowed_blocks, $editor_context) {
  return array(
    'core/block',
    'core/column',
    'core/columns',
    'core/list',
    'core/paragraph',
  );
}
add_filter('allowed_block_types_all', 'allowed_block_types', 25, 2);
```

### Environment info

- WordPress 6.1
- Twenty-Twenty-Two
- Not being Browser- or Device-related...

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by timlg07** [comment]
Experiencing the same issue here since updating to WordPress 6.1

**Comment by timlg07** [comment]
Thanks for pointing out that this only happens if you restrict the block types. I added `"core/list-item"` to the white-listed blocks and it works fine again.

**Comment by E-VANCE** [comment]
Thanks @timlg07!

Exactly right, this fixes the issue and renders the list-block fully usable again. Thanks for chipping in & closing this...
