### ISSUE TITLE
Waypoint animations, parallax and anything tracking window scrolling doesn't work in Gutenberg

### ISSUE THREAD

**Issue by fastlinemedia** [WordPress/gutenberg#4558]
## Issue Overview
It looks like Gutenberg is scrolling the editor content element instead of the body element. Because of this, waypoint animations, parallax and anything tracking window scrolling doesn't work.

I noticed this when playing around with a number counter block that animates from zero to the specified number when scrolled into view (screenshot below). 

It looks like #4445 could be related to this as well.

## Possible Solution
One possible solution would be to use the default browser scrolling on the body element and fixed position for the other elements on the page like the toolbar and sidebar.

## Screenshots / Video
![screenshot 2018-01-17 17 22 43_preview](https://user-images.githubusercontent.com/2453483/35076038-39eb3e8e-fbab-11e7-9ab1-b8f857afd393.png)

## Related Issues and/or PRs
#4445

**Comment by danielbachhuber** [comment]
Hi @fastlinemedia,

Were you able to sort out a solution to this?

**Comment by fastlinemedia** [comment]
@danielbachhuber no and I ended up shelving the project that this was needed for, so I haven't tested it in a while. Feel free to close out. I can reopen it if I run into something again.

**Comment by danielbachhuber** [comment]
👍 Thanks

**Comment by phpbits** [comment]
@danielbachhuber anyway to track the scrolling on editor? Thanks!

**Comment by danielbachhuber** [comment]
> anyway to track the scrolling on editor? Thanks!

Not to my knowledge, no.

**Comment by phpbits** [comment]
@aduth @gziolo Hoping you can help out. Thanks!
