### ISSUE TITLE
`is-layout-flow` gets applied contextually in site editor, causing layout shift

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#45590]
In the site editor, using a layout involving 3 columns of latest posts, when you click between these three columns, the layout shifts:

![shift when selecting column](https://user-images.githubusercontent.com/1204802/200343755-da41b54f-e4e9-4d77-9a5c-8e65a2ab6d9a.gif)

This appears to be caused by a margin that is added to inner items between deselected and selected. When inspecting. it becomes clear that a _selected column_ has a `is-layout-flow` CSS class applied to the column `li` item:

![layout-flow](https://user-images.githubusercontent.com/1204802/200344490-81f22f81-6bff-42ed-b73c-e5bebe2a3a23.gif)

The class `is-layout-flow` applies some margin to place the inner contents:

![margin](https://user-images.githubusercontent.com/1204802/200344945-395fbfd1-fdd8-4bc5-b954-8c3969a6df1c.gif)

If this margin is appropriate for the column, it should be applied to all columns, not just the selected one. So far I've been able to reproduce it using only the Columns block, and it may be limited to just that block.

**Comment by jasmussen** [comment]
@tellthemachines can you reproduce this? I recall you working on flow layout before, any input you have would be great, thank you.

**Comment by tellthemachines** [comment]
Hmm I can't reproduce that on trunk. The `is-layout-flow` classname is applied on the `ul`, but not on any of its `li` whether they are selected or not. The `li` aren't blocks in themselves, so they _shouldn't_ ever have that class unless it's being applied independently of the layout support. 

Could you share some more info on your environment, theme, plugins etc. that might help isolate the cause?

**Comment by jasmussen** [comment]
Thank you for looking. Indeed retracing my steps now, I'm unable to reproduce. The is-layout-flow is no longer applied to the individual post columns. Closing as fixed!
