### ISSUE TITLE
Fix typing space at the beginning of inline boundaries

### ISSUE THREAD

**Issue by spocke** [WordPress/gutenberg#456]
There is a bug where it's quirky to press space at the beginning of a link this is because spaces are not rendered unless they are preceded with a letter. So in this case only once space would be rendered:
`a <a href="a"> b</a>`
however in this case it would be rendered when we are at the boundary
`a <a href="a">\ufeff b</a>`

**Comment by jasmussen** [comment]
This seems fixed in trunk?
