### ISSUE TITLE
Pasting a local image file does not work in Windows + Firefox

### ISSUE THREAD

**Issue by aaronjbaptiste** [WordPress/gutenberg#45602]
### Description

You can copy paste an image file from your local machine into the editor on Mac + any browser, but it seems the same does not work on Windows Firefox

### Step-by-step reproduction instructions

Using Firefox on Windows copy an image file from your local drive and paste it into the editor

Expected: The image is parsed and processed into the editor (I reproduced on p2 and on tumblr's beta editor)

On Mac Firefox or Windows Chrome the console prints:

```
Received HTML:

use-paste-handler.js:101 Received plain text:

paste-handler.js:210 Processed HTML piece:

 <p><img src="blob:https://localhost.redpop.dca.tumblr.net:3000/2cd4602f-5254-410e-8a53-624c47719231"></p>
use-paste-handler.js:176 Received items:

[File]
```

Actual: Nothing is pasted

On Windows Firefox the console prints:

```
Received HTML:

<empty string>

Received plain text:

<empty string>

Processed HTML piece:

<empty string>
```

### Environment info

Windows Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I am able to reproduce this using:
Firefox version 106.0.5 (64-bit)
Windows 10 Pro version 21H2
WordPress 6.1, Twenty Twenty-Three, no plugins.

**Comment by t-hamano** [comment]
Different results were obtained in my environment.
I was able to paste the image, but it is pasted as an "inline image". The browser console does not output any logs.

- Firefox version: 106.0.5 (64-bit)
- OS: Windows 11
- WordPress version: WordPress 6.2-alpha-54777
- Gutenberg version: 14.5.0

https://user-images.githubusercontent.com/54422211/201458908-173cc404-ac5b-4b09-8ccb-772cd01e0f28.mp4

**Comment by Mamaduka** [comment]
@mcsf, I remember you recently fixed a few issues related to pasting images and files. Any ideas on what might be causing the different behavior on Win/Firefox?

**Comment by Lovor01** [comment]
I was unable to reproduce the issue. Win 10 and FF 108 developer version. However, I discovered that pasting does not work if nothing is selected and you are not editing any block. Does this help?

**Comment by mcsf** [comment]
> @mcsf, I remember you recently fixed a few issues related to pasting images and files. Any ideas on what might be causing the different behavior on Win/Firefox?

Indeed, I've worked a couple of times on this, but I have no idea what might cause the different behaviour on Windows. Sadly, in my experience, platforms all implement pasting with their own quirks. I think it's a matter of testing pasting with different browsers on Windows — this [clipboard viewer util](https://dmsnell.github.io/ghpages/clipboard.html) is very handy — and tweaking Gutenberg's heuristics (see implementation of and calls to `shouldDismissPastedFiles`). @aaronjbaptiste, is this something you'd be willing to spend time on?

**Comment by mcsf** [comment]
@aaronjbaptiste: ping, in case you missed the [previous comment](https://github.com/WordPress/gutenberg/issues/45602#issuecomment-1344484075).

I'll be grateful towards any takers for this issue. :)

**Comment by aaronjbaptiste** [comment]
I will give it a go and see if I can resolve or debug further! ⚡  Thanks for your suggestions @mcsf !

**Comment by aaronjbaptiste** [comment]
After testing this and with April help using native Windows, I've come to the conclusion this is a Firefox restriction. Pasting image files does not work in other apps either - tested in Twitter and Discord web apps.

The clipboardData for files array is empty.

I tried switching various Firefox security settings but nothing changed.

Will close this one, thanks all!

**Comment by Mamaduka** [comment]
Thank you, @aaronjbaptiste!
