### ISSUE TITLE
Filtering patterns by keyword

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#45606]
When [registered](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/#register_block_pattern) Patterns are able to include `keywords` which, in addition to categories, help to describe the pattern. I suppose we can think of them as post tags, for block patterns. 

I'm not sure how widespread the use of this affordance is, but when patterns with keywords exist on a site (or when browsing the pattern explorer after it has been [connected to the pattern directory](https://github.com/WordPress/gutenberg/issues/44611)) it would be nice if the UI allowed folks to filter by keyword. In https://github.com/WordPress/gutenberg/issues/44501 a 'wireframe' keyword is being considered, which could elevate usage. 

Areas of the editor to consider surfacing keyword filtering:

### Pattern explorer
<img width="1667" alt="Screenshot 2022-11-08 at 14 22 54" src="https://user-images.githubusercontent.com/846565/200589510-4b8f7f0d-26b6-4fb2-9213-e9a3fc64f5b1.png">

### Patterns panel
<img width="721" alt="Screenshot 2022-11-08 at 14 23 19" src="https://user-images.githubusercontent.com/846565/200589648-80f28761-b53d-48af-bfb3-1580e5419fe8.png">

Are there others?

**Comment by ntsekouras** [comment]
Filtering by `keywords` is already supported. Did you encounter a case that didn't work?

**Comment by jameskoster** [comment]
Do you mean it's supported in the search? That's good to know. I was thinking more about surfacing specific keywords as filtering options in the UI in order to aid discovery.

It's certainly not a high-priority item, just something to think about as the pattern directory grows.

**Comment by ntsekouras** [comment]
>Do you mean it's supported in the search?

Yes, that was what I meant.

**Comment by youknowriad** [comment]
I think we should rework this UI to use DataViews and support filters/search ...

**Comment by jameskoster** [comment]
Yup. The main issue was ensuring keywords are included in the search function. A keyword field might be worth adding to the Patterns data view.
