### ISSUE TITLE
Embedding Tally Forms produces error

### ISSUE THREAD

**Issue by NicoHood** [WordPress/gutenberg#45629]
### Description

Hi,
I try to embed a tally form, but that does not work when I try to submit the request.
https://tally.so/

![image](https://user-images.githubusercontent.com/6888294/200869748-4a9b788b-8274-47d4-9188-8b015f7aee37.png)
![image](https://user-images.githubusercontent.com/6888294/200870163-98bf1426-b67c-4061-ae75-18b749a23ea0.png)

### Step-by-step reproduction instructions

1. Register on https://tally.so/
2. Create a new form
3. Embed this into the wordpress post
4. open the page
5. try to submit the form

### Environment info

- Wordpress 6.0/6.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bph** [comment]
@NicoHood I was able to make it work using the Custom HTML block. 
I created a short video https://recordit.co/tETz2srkBy In the video, I also show which code I was used from the Tally site for this to work.

**Comment by NicoHood** [comment]
Alright, that is a good workaround. But why does the normal wordpress embedding not work? The tally support told me:

> This error usually happens when the Tally embed iframe has a sandbox attribute, so some things like scripts or cookies are blocked.
>
> We don't use cookies, so I'll need to look into why this error comes up.
>
> But the solution should be to remove the sandbox attribute from the <iframe ... /> code. 

My assumption was that wordpress wrote a custom embedd code for tally. Is that true, or how does the native embed work? Or is there some magick that transforms a website to an embedded block? Since it does not work for all website I would have expected some custom code. And that does not seem to work.

Did i missunderstand this?

**Comment by t-hamano** [comment]
WordPress core gives `sandbox="allow-scripts"` for embedded content.
You can check the code here:
https://github.com/WordPress/wordpress-develop/blob/d90013cdeb7832972f84648459bb3f9de4364e25/src/wp-includes/embed.php#L498

I believe this is so that if there is a problem with the embedded content, it will not affect the outside of it.

You can rewrite the HTML output by using the [embed_html](https://developer.wordpress.org/reference/hooks/embed_html/) filter. Replacing the sandbox with [allow-forms](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) seems appropriate, but it may be a good idea to add logic to ensure that only tally forms are covered so as not to relax the restrictions more than necessary.

**Comment by NicoHood** [comment]
Alright, and how does wordpress detect if a website can be embedded or not? Is there a list of supported website or a generic solution like structured data that I am not aware of yet?

Cause at the same time (a bit offtopic) I was wondering why google maps embed does not work.

**Comment by t-hamano** [comment]
Sorry, I do not have an exact answer for that.
You might want to ask about those issues in [the gutenberg discussions](https://github.com/WordPress/gutenberg/discussions) or [support forum](https://wordpress.org/support/forums/).

**Comment by bph** [comment]
@NicoHood The Embed block relies on the [open format oEmbed](https://oembed.com/). If a site doesn't use that format, the embedding out-of-the-box doesn't work. Then you would need to use their site's instructions on how to embed the site or part of the site. For [Tally the instructions are here](https://tally.so/help/how-to-embed-a-tally-form-on-wordpress). You can learn more on the [history of oEmbed and WordPress on MakeUseOf](https://www.makeuseof.com/tag/oembed-wordpress-easier-technology-explained/).
If that's ok with you @NicoHood I close this thread.

**Comment by filipminev** [comment]
@bph @t-hamano @NicoHood Tally Forms founder here 🙋‍♂️

We support the open oEmbed format: all forms contain a discovery link (for example, from the form mentioned above):
`<link rel="alternate" type="application/json+oembed" href="https://api.tally.so/oembed?url=https%3A%2F%2Ftally.so%2Fembed%2Fw5XbXE%3FhideTitle%3D1&amp;format=json" title="Partyborn Partyalarm Aufnahmekriterien">`

It returns an iframe code. You will see in the OP's screenshot that the iframe has sandbox and security attributes, which we don't return, so they must have been added afterward. Could that be the case?

We don't use cookies, so I'm not sure what the "Document.cookie getter..." error is, I still need to investigate further.

**Comment by t-hamano** [comment]
Hi @filipminev,

> It returns an iframe code. You will see in the OP's screenshot that the iframe has sandbox and security attributes, which we don't return, so they must have been added afterward. Could that be the case?

As [this comment](https://github.com/WordPress/gutenberg/issues/45629#issuecomment-1312384981) states, the WordPress core grants `sandbox` and `security` attributes.
