### ISSUE TITLE
Page Template can't be saved or deleted when the page title is in Greek. 

### ISSUE THREAD

**Issue by kosakk** [WordPress/gutenberg#45633]
### Description

I have attempted to create a template for a page. The page's title is in Greek. When I attempt to save, I get the following error in the browser console: `POST https://mydomain.gr/wp-json/wp/v2/templates/twentytwentythree//page-%cf%84%ce%b5%cf%83%cf%84?_locale=user 404` The page's title is "τεστ" (Greek for "test"). Outside of the browser's console there is a Saving failed. error thrown. 
![image](https://user-images.githubusercontent.com/12464123/200885441-bb8bc7e9-282e-4380-93d3-a3830326c4ff.png)

When I create a second page titled "test" under the same installation of WP, and repeat the same process, the template is properly saved.

When I try to delete the Greek titled page template from the general Templates page of the editor, I get the "No route was found matching the URL and request method." message in the bottom left of the page. The template is not deleted. 

When I try to delete the English titled page template from the general Templates page of the editor, I get no errors. The template is properly deleted. 

### Step-by-step reproduction instructions

1. Go to pages.
2. Create a new page. 
3. Name it τεστ. 
4. Go to Appearance > Editor
5. Create a new page template for the τεστ page. 
6. Add a paragraph under the existing content to enable the 'save' option. 
7. Click 'save', verify you have checked the templates for the page:τεστ, and click 'save' once again. 
8. You should now see the error. 
9. Return to the Templates page of the Editor from the top left menu. 
10. You should see a page template for page: τεστ. 
11. Click on the three dots to reveal the options menu. 
12. Click on delete to remove the template. You should see the "No route was found matching the URL and request method." message on the bottom left of the Editor page. 
![Screenshot-maim_selection_2022-11-09_18-25-50](https://user-images.githubusercontent.com/12464123/200887889-5ee25e26-99f3-4239-ac82-d08f47ce828f.png)

### Screenshots, screen recording, code snippet

https://www.loom.com/share/daec9d6a778c4e76a33dae0c68a280ed

### Environment info

- Wordpress version 6.1 with Gutenberg. Fresh clean installation in localhost, with no plugins whatsoever. Bug initially discovered on development site. 
- Twenty Twentythree theme
- Chrome Version 107.0.5304.87 (Official Build) (64-bit)
- OS Linux Manjaro 64-bit i3wm

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kosakk** [comment]
I've explored options further. It appears that if I change the permalink to use English characters, then I am allowed to create a page template, edit, and save it. Returning to the templates page, I can also delete the page template. 

**Steps to follow to reproduce:**
Please create a new page. Name it "τεστ", and change the permalink to "test". Save the page, and create a new page template for the "τεστ" titled page. The Greek characters in the title should not affect the expected behavior of template creation. Edit the template, and save it. It should be saved. Then return to the templates page and delete it. It should be deleted.

**Comment by kosakk** [comment]
On a different note, I converted the already existing pages' permalinks from Greek to English names. That allowed the pages to follow the general single page formatting. It did not solve the problem with deleting previously created templates though. The pages which I converted the permalinks of from Greek to English have now broken titles in the templates editor general page. They can not be deleted either, still. 

Their original names were following the scheme of "Σελίδα-#" (e.g. 1, 2, 3 etc.) and their permalinks also ("σελίδα" is Greek for  "page"). After unsuccessfully attempting to create templates for the original permalinks, I then converted the permalinks from Greek to English. That resulted in the following in the templates editor page:

![image](https://user-images.githubusercontent.com/12464123/201061334-47fb7d0f-f83f-4d1e-a241-10c5f43c55a7.png)

**Comment by sophiegyo** [comment]
I'm not sure this is specific to Greek, I strongly suspect it's related to non-latin characters. I spoke to someone who had the same issue while their site language is Hebrew and it does the same thing:

![Screen Capture on 2022-12-02 at 12-21-08](https://user-images.githubusercontent.com/36608681/205281836-ae6c5fab-378a-47e5-bf98-8503427fc3c7.gif)

I'll ask them to test your workaround of switching the slugs to English!

**Comment by csonnek** [comment]
Person in https://github.com/WordPress/gutenberg/issues/45633#issuecomment-1335101839 reported that changing the category slug also failed: 

![UIs6tArYbR](https://user-images.githubusercontent.com/2814452/205334286-92178582-65ef-40ae-8c25-4dd5e6f84b88.png)

**Comment by kozer** [comment]
@danielbachhuber I'll take a look at this one. Can you please assign it to me?

**Comment by kozer** [comment]
[Wordpress.org pr](https://github.com/WordPress/wordpress-develop/pull/3819)

**Comment by danielbachhuber** [comment]
This fix will be released with WordPress 6.2 https://core.trac.wordpress.org/ticket/57329
