### ISSUE TITLE
Templates List: consider showing which template is currently used for the site's front page

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#45644]
## What problem does this address?

It can be difficult to understand which template is currently being used to display a site's front page, since it depends on both which templates exist and the site's reading settings. 

## What is your proposed solution?

In the templates view, we could clearly mark the template that is currently being used to show the site's front page. 

Not suggesting this is the design, just a sketch to demonstrate the suggestion, for example if the user has a static page set to display their home page: 

<img width="1512" alt="templates-view-home-template" src="https://user-images.githubusercontent.com/5375500/200907137-1ec0b4d9-c0b2-4f8c-a5a3-858f24a3d123.png">

**Comment by youknowriad** [comment]
I think we have now tags to show the front page and posts page in the page data views. So there has been an iteration here. It might not be perfect yet though. Maybe we should consider a new issue if needed as the designs and behavior changed a lot.
