### ISSUE TITLE
`register_legacy_post_comments_block()` uses invalid metadata key

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#45677]
### Description

The `register_legacy_post_comments_block()` function registers the `core/post-comments` block. In its metadata array the `editorStyle` key is provided instead of `editor_style`, which means either this metadata isn't needed or the editor styles are currently broken. Needs testing to verify which is the case.

### Step-by-step reproduction instructions

1. View https://github.com/WordPress/gutenberg/blob/7fd1dc58eaa357c1079201007a263bf1f9e60dde/packages/block-library/src/comments/index.php#L205
2. Confirm the `editorStyle` metadata key is used instead of `editor_style`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by DAreRodz** [comment]
> which means either this metadata isn't needed or the editor styles are currently broken.

I think it's the first case. The `core/post-comments` block is registered to support themes that haven't been updated yet to use `core/comments` instead. That legacy block is dynamic, so it needs to be registered to render correctly.

However, once you open the editor, `core/post-comments` blocks are turned into `core/comments` transparently:

https://github.com/WordPress/gutenberg/blob/5de7f238df8d07337e11809667e531ce3baf1a88/packages/blocks/src/api/parser/convert-legacy-block.js#L75-L78

 So, these styles are never requested. I guess we can safely remove them. 🙂

**Comment by Mamaduka** [comment]
Hi, @DAreRodz

I just wanted to check if you have time to work on the suggested changes.

**Comment by DAreRodz** [comment]
Hey @Mamaduka! Sorry for the delay; I was AFK last week. 😄

And sure, as it's a small change, I think I can spend some time tomorrow and open a PR with the changes, no problem.

**Comment by DAreRodz** [comment]
PR created: https://github.com/WordPress/gutenberg/pull/46514

**Comment by DAreRodz** [comment]
Oh no. While working on this, I've nothing that styles are not working on the front end for the legacy version. 😞 

I have opened a bug: https://github.com/WordPress/gutenberg/issues/46516
