### ISSUE TITLE
Provide Custom CSS per Style Variation

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#45675]
## What problem does this address?
Certain style variations may be better enhanced by having CSS that isn't appropriate for other (or some other) variations (or the base theme) to contain.

An example of this might be a "System controlled Dark Mode color scheme" variation where additional CSS is needed or variations that need CSS to achieve design targets.

## What is your proposed solution?
When a style variation is activated for a theme a specific class (for instance `theme-variation-VARIATION_NAME` or something) is appended.

This would allow selectors to be crafted in style.css that would target only certain variations.

**Comment by carolinan** [comment]
Hi, can I close this as a duplicate of https://github.com/WordPress/gutenberg/issues/43405 ?

**Comment by pbking** [comment]
Oh thank you @carolinan yes this is a dupe, thank you for pointing out #43405
