### ISSUE TITLE
Suggestion: "Clear All Content"

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#4568]
##This is a suggestion and not an issue

It would be great if we can clear all content of a page/post via shortcut and a link under document menu.

![image 2018-01-18 at 4 45 53 pm](https://user-images.githubusercontent.com/5817882/35096877-a354e1da-fc6f-11e7-9b8a-24b43b25e38e.png)

**Comment by ronakganatra9** [comment]
I do not think there is any need for it. Because we can do directly by Select all by CTRL + A and DELETE. It will clear all content and this is also a shortcut.

**Comment by munirkamal** [comment]
I wasn't aware of CTRL + A shortcut. But still the Clear all link below the Copy all link makes sense and may be useful for those who don't use shortcuts.

**Comment by mellis32** [comment]
On Mac, ⌘A will not Select All, only current block, unless you know the hidden trick to select all content, which is to first de-select all blocks. Very frustrating. See #4369.

**Comment by danielbachhuber** [comment]
Thanks again for the suggestion, @munirkamal. I've filed this away in the [Ideas project](https://github.com/WordPress/gutenberg/projects/8) for future consideration.
