### ISSUE TITLE
Allow for using rel="me" on links in the Social Icons Block.

### ISSUE THREAD

**Issue by ThomasOwens** [WordPress/gutenberg#45688]
## What problem does this address?
This became more apparent with Mastodon using rel="me" links to "verify" user accounts. I have a link to my Mastodon profile on my homepage using a Social Icons Block, but it doesn't appear to be possible to use this link in the Social Icons Block to perform that verification. Using rel="me" to point from one page about a person to another page about a person is also a good microformat practice for more semantic markup.

## What is your proposed solution?
It doesn't make sense to apply rel="me" to all links in all cases, so it seems like it would be necessary to add a flag or attribute to determine if the rel="me" should be applied to the link.

**Comment by Mamaduka** [comment]
Hi, @ThomasOwens

I think this was resolved via #45469.

**Comment by ThomasOwens** [comment]
@Mamaduka It looks like it, yes. Just looks like it's not released yet. Definitely a duplicate of that PR and issue. I'll close this and watch for that to be released.

**Comment by Mamaduka** [comment]
The feature should be part of Gutenberg 14.5 (released yesterday) and will be included in WP 6.2.
