### ISSUE TITLE
`@wordpress/eslint-plugin` package does not support node.js 18

### ISSUE THREAD

**Issue by james58899** [WordPress/gutenberg#45696]
### Description

Node.js 18 is LTS now.
But `@wordpress/eslint-plugin` dependency `eslint-plugin-jsdoc` version is too old.

Error:
```
error eslint-plugin-jsdoc@37.9.7: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^16 || ^17". Got "18.12.1"
```

Command `yarn why eslint-plugin-jsdoc` output:
```
=> Found "eslint-plugin-jsdoc@37.9.7"
info Reasons this module exists
   - "@wordpress#scripts#@wordpress#eslint-plugin" depends on it
   - Hoisted from "@wordpress#scripts#@wordpress#eslint-plugin#eslint-plugin-jsdoc"
```

### Step-by-step reproduction instructions

1. Install Node.js 18
2. `yarn add @wordpress/scripts`

### Environment info

Node version: 18.12.1
@wordpress/scripts version: 24.5.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by fabiankaegy** [comment]
There is a PR for this currently: https://github.com/WordPress/gutenberg/pull/42656 Based on the latest feedback on that PR the approach that was used is not the right one for the project. But I spoke with @Antonio-Laguna and he was interested in creating a new PR based on the feedback that was shared in https://github.com/WordPress/gutenberg/pull/42656#issuecomment-1306503950

**Comment by Antonio-Laguna** [comment]
@fabiankaegy I will create this ASAP :)

**Comment by ehrig** [comment]
@Antonio-Laguna Do you have any news/estimate when the PR will be merged? 

Maybe updating the package installation note until this fix is available can be useful for others who try to use node.js 18: https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#installation

**Comment by Antonio-Laguna** [comment]
@ehrig it was promptly created on #45697 yet there are issues with NPM that I'm unsure on how to fix.

**Comment by nicholasio** [comment]
Any updates on this?

Node.js 16 is going EOL later this year.

https://nodejs.org/ar/blog/announcements/nodejs16-eol/

**Comment by gziolo** [comment]
Thank you for the fix @fabiankaegy 👏🏻

**Comment by gziolo** [comment]
As far as I can tell, this change should get published to npm on Wednesday. Let's hope it's the only issue that prevents the package from using with Node 18.
