### ISSUE TITLE
All inputs and controls should have #949494 border colors, not #757575

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#45698]
The border around inputs and control boxes currently have a text-contrast #757575 color (`$gray-700` in the SCSS system): 

<img width="310" alt="border and radius" src="https://user-images.githubusercontent.com/1204802/201035735-3b76f09d-474e-4a6f-bfa9-6fee7643b955.png">
<img width="302" alt="font size slider" src="https://user-images.githubusercontent.com/1204802/201035760-77ae32bf-7fea-4f0e-ad35-0afffdad3d08.png">
<img width="324" alt="font size custom input" src="https://user-images.githubusercontent.com/1204802/201035781-a86230d7-29ab-4607-996e-308b45c8d12f.png">

These borders should be UI-contrast #949494  (`$gray-600` in the SCSS system):
<img width="342" alt="Screenshot 2022-11-10 at 09 09 43" src="https://user-images.githubusercontent.com/1204802/201036221-2943e9df-0c63-49c4-953a-9bf4da3d6815.png">

**Comment by mirka** [comment]
Duplicate of #39425? It's been a while, but good news is that we'll be required to address this as part of the theming work (#44116) we are prioritizing right now 😄

**Comment by jasmussen** [comment]
Ack, sorry I missed that 🙈
