### ISSUE TITLE
Strange issue when adding links

### ISSUE THREAD

**Issue by kdr922** [WordPress/gutenberg#45702]
### Description

After upgrading to the latest version of WordPress, I suddenly encounter an issue when adding a link. It jumps down to the bottom of the page so I need to scroll back the position in the text to check it, and then I can’t see the new window/nofollow buttons properly in the dropdown – I wonder if it’s just on my PC since a colleague of mine doesn't experience this using the same WP backend at all. 

Please see attached. Any thoughts?

![download](https://user-images.githubusercontent.com/117917147/201099799-94cf9bcb-487b-458d-9dd8-76aa13b58600.jpg)

### Step-by-step reproduction instructions

1. Add a link in a Post/Page editor

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
HI, 

Could you share what operating system, browser, and browser version that you are using?

**Comment by Mamaduka** [comment]
This could be a plugin compatibility issue. The core link popover only has the "Open in new tab" option.

![CleanShot 2022-11-10 at 20 28 20](https://user-images.githubusercontent.com/240569/201152032-563ef333-ad44-496e-8f6d-2b99255397d1.png)

**Comment by gOuTM** [comment]
Me too. I guess it is Editors Kit plugin issue. As well as many others, unfortunately.

But I'm forced to use this plugin since #12684 has no progress since 2018 — but the plugin has requested option and it works.

**Comment by bph** [comment]
Although, I have come across this occurrence of 'unknown format' and links can't get pasted anymore, too. I was able to track it down to the Yoast SEO plugin. I close this issue as it's not a Gutenberg bug
