### ISSUE TITLE
Can't save and delete when using custom template for post with multibyte in site editor

### ISSUE THREAD

**Issue by s56bouya** [WordPress/gutenberg#45718]
### Description

When a post containing multibyte characters is selected as a template, it cannot save and delete.

At a later date, I changed the slug thinking multibyte characters were affecting it, but now the template is not found and can't be edited. Still can't delete.

### Step-by-step reproduction instructions

1. Dashboard->Appearance->Editor
2. Editor->Templates->Add New->Single item: Post->Post For a specific item
3. Select posts with multi-byte characters (e.g. `https://abc.com/アイスクリーム`)

### Screenshots, screen recording, code snippet

![screenshot01](https://user-images.githubusercontent.com/15373114/201269264-9ddb3762-26c2-4fa6-8a5d-6eefb924ab40.png)

### Environment info

- WP 6.1
- Twenty Twenty-Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Related #45633.

The templates REST API only supports Latin characters for template slugs.

**Comment by jordesign** [comment]
Closing this issue - as the underlying cause was fixed in WordPress 6.2
https://core.trac.wordpress.org/ticket/57329
