### ISSUE TITLE
Display block shortcuts in Top Bar when Inserter is open

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#45722]
Extracted from https://github.com/WordPress/gutenberg/issues/41379

<img src="https://user-images.githubusercontent.com/1204802/185140173-deb7255e-53af-4447-9a3c-6644b33806f3.png">

When the Inserter is open, it could be nice to try replacing the document tools with shortcuts to insert common blocks. This will be most useful in situations where the Patterns tab is the default but you only want to insert a block.

It might be worth a little design exploration to work out details like animation, but that's probably a nice-to-have and needn't prohibit the creation of a PR.

**Comment by apeatling** [comment]
The issue I see with this -- if you select the wrong pattern and insert it there would be no obvious undo button. I can imagine this being a problem for people. It's easy in this interface to click the wrong pattern -- or see it on the canvas and change your mind without an obvious path out.

**Comment by apeatling** [comment]
I think having this, but also keeping the undo/redo buttons in place would be fine.

**Comment by jameskoster** [comment]
I think that could be okay, as long as there' some visual separation between the shortcuts and the undo/redo tools.

**Comment by youknowriad** [comment]
I think given that the current inserter stays open as long as you keep it, we should discard this idea. 
Also it's a bit of an a11y nightmare.
