### ISSUE TITLE
wp-social-link block should have rel=me as part of the link

### ISSUE THREAD

**Issue by djotaku** [WordPress/gutenberg#45729]
## What problem does this address?

The social media sites that the user has on their blog or site with this block should represent social media sites that belong to the user. They should, therefore, have the rel=me as part of the link. In relation to the current migration to Mastodon, this rel=me link is required to validate the site (green checkmark on Mastodon)

## What is your proposed solution?

Each of the links created by this block should have rel=me

**Comment by t-hamano** [comment]
Hi @djotaku 
I think this was resolved via https://github.com/WordPress/gutenberg/pull/45469.

This PR is included in Gutenberg 14.5 and has been released as a plugin, so you can check it.
