### ISSUE TITLE
Button component with set variant doesn't wrap text

### ISSUE THREAD

**Issue by monsieur-z** [WordPress/gutenberg#45724]
### Description

When set as primary, secondary, or tertiary (via the `variant` prop), the [Button](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/button) component doesn't wrap text on a new line when there's not enough space to display the full label.

This looks like a conscious decision, given [the component styles](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/button/style.scss#L45). However that seems like an odd default behaviour to me, since cutting text causes accessibility issues. I also don't think that's an edge case: I'd assume that on a 320px wide screen and in German (which has longer words than English), labels would be cut fairly often.

### Step-by-step reproduction instructions

1. Visit the [component's page in Storybook](https://wordpress.github.io/gutenberg/?path=/story/components-button--default)
2. With the _Canvas_ tab selected, change the size of the preview to _Small mobile_
3. With the help of the _Controls_ panel below, set the component `variant` prop to `primary`
4. In the same panel, update the content of the `children` prop until you see the text being cut in the preview

### Screenshots, screen recording, code snippet

<img width="412" alt="Screen Shot 2022-11-11 at 10 33 20 AM" src="https://user-images.githubusercontent.com/1620183/201390832-3fb3507d-8a4e-4539-ae10-6a889061df5e.png">

### Environment info

- Using the Storybook page live at the moment of writing: https://wordpress.github.io/gutenberg/?path=/story/components-button--default
- Tested in Chrome  107.0.5304.110 on macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hi @monsieur-z - I'm just checking old/stale issues and wanted to see if this is still relevant in your testing?

I'm closing it for now - but if it _is_ still relevant, please feel free to re-open it.

**Comment by monsieur-z** [comment]
It still happens in my testing. I feel it's a valid issue but there may be a rationale for the text not wrapping.
