### ISSUE TITLE
Hover effect color not fully covered in block editor link control search item

### ISSUE THREAD

**Issue by theminaldiwan** [WordPress/gutenberg#45720]
### Description

When we assign link to any text then link toolbar is appear.After adding link in toolbar then bottom link control search box is fully covered when we hover on it.This is occur in all themes of wordpress.

### Step-by-step reproduction instructions

1)Activate any theme
2)Select paragraph block and add link on it
3)After adding url in search link box
4)Bottom side of toolbar link preview will display
5)Hover on preview area, we facing issue.

### Screenshots, screen recording, code snippet

Recording:https://share.cleanshot.com/Dn70Fn8pGHY9v7jLuXb7

### Environment info

- Wordpress version 6.1
- Gutenberg 14.5.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Closing this issue as the new Link interface for blocks does not display the same hover effect.
