### ISSUE TITLE
Error with handleSuggestionLink on __experimentalLinkControl

### ISSUE THREAD

**Issue by mjjwatson** [WordPress/gutenberg#45733]
### Description

I've noticed since 6.1 updates that __experimentalLinkControl is erroring onChange:

```
const {
	__experimentalLinkControl : LinkControl
} = wp.blockEditor

```

`
const [ tempLink, setTempLink ] = useState( null )`

`
 <LinkControl 
	value={tempLink}
	onChange={(newLink) => {
		setTempLink(newLink)
	}}
/>
`

The JS error is:
"Cannot destructure property 'id' of 'r' as it is null."

 at handleSuggestionClick

The example above is a simplified LinkControl to show it in action. The error occurs when adding in a custom link, or linking to a post object using the suggestion handler. This has been attempted out in the root of the editor, as well as within <InspectorControls>.

### Step-by-step reproduction instructions

1. Any block editor screen
2. LinkControl added to <InspectorControls/>
3. Attempt to add a link via the suggestion handler

### Environment info

Wordpress 6.1 on a clean, empty theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@mjjwatson 
Thank you for your contribution.

I was able to reproduce it. I would like to submit a PR in the near future.
Below is a temporary implementation of your code into the button block to reproduce the error.

https://user-images.githubusercontent.com/54422211/201516362-22077ea5-5ccb-4faa-8f8b-ec7f2c8b4197.mp4
