### ISSUE TITLE
Using same custom block twice in edit(backend) only showing once in save(frontend) 

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#45734]
### Description

When I add two instances of the same block I am expecting it to show twice or however many times I insert the block in the backend. This block is rendered with php though i.e.: `save: () => null`

If I insert the block once then it works fine and as expected. If I add the block again it shows only once on the frontend instead of twice for example. 

Here is the php

```
 register_block_type( __DIR__ . '/build/test-posts', array(
	'render_callback' => 'render_test_posts'
) );

function render_test_posts($attributes, $content, $block)
{
     ob_start();
     require_once( __DIR__ . '/templates/test-posts.php' );
     return ob_get_clean();
}
```

test-posts.php

```
<?php

global $post;
$args = array(
    'post_type' =>  $attributes['chosenPostType'] ),
    'posts_per_page' => 5,
);

$postsQuery = get_posts($args);

    <?php
            foreach ($postsQuery as $post):
            setup_postdata( $post );
    ?>
    <?php the_title(); ?>
<?php
 endforeach;
 wp_reset_postdata(); 
?>
```

### Step-by-step reproduction instructions

As per description.

### Environment info

Wordpress 6.1 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @Jonofat,

Isn't it `require` instead of `require_once`?

Alternatively, since WordPress 6.1, `block.json` supports [render property](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#render), so it would be simpler to implement without render_callback.
