### ISSUE TITLE
Create a component to replace the HeadingLevelDropdown toolbar option.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#45743]
## What problem does this address?

The HeadingLevelDropdown is a toolbar option used to choose between H1-H6 in the heading block, comments title, query title, and post title. The files are in the heading block, and the other blocks import them.
The site title has its own similar option, and it adds a paragraph to the selection.
In addition, if merged, the proposed Details block would also use a heading level option.

There are visual differences between the two options, because they use different icons and site title shows the name of the element in the dropdown.

Heading block:
![A heading block in the block editor with the heading level option expanded](https://user-images.githubusercontent.com/7422055/201520628-16595fa6-9767-468c-bb3d-3f954ce26620.png)

Site title:
![A site title block in the block editor with the heading level option expanded](https://user-images.githubusercontent.com/7422055/201520694-14396033-e605-4ee1-8798-db45e8c72a97.png)

## What is your proposed solution?

Create a component, to which the blocks can pass the HTML tags that should be available.
The benefits are that it would be more future proof in case the heading block changes, it reduces code duplication, the option would look the same in every block where it is used, and no longer be limited to heading elements.

We would need to decide which of the two dropdown designs to use.

**Comment by carolinan** [comment]
My own preference is the second design where the name of the element is visible.

**Comment by carolinan** [comment]
@jameskoster Hi! Who can help decide which of the two heading level drop down designs to use?

**Comment by jameskoster** [comment]
@carolinan probably best to request a review from @ WordPress/gutenberg-design when the PR is ready.
