### ISSUE TITLE
Easy Workflow to Create Custom Blocks

### ISSUE THREAD

**Issue by afmarchetti** [WordPress/gutenberg#45740]
All the WordPress dev want to create block with php, js, css whitout npm and build worflow.
In a small business web site we haven't the time and budget to create a block with that system (local build) to make small changes, we need something quick and easy like this:
https://blockstudio.dev/

If you make something like this all the community will love Gutenberg and WordPress again.

This could change everything and make full site editing grow fast, think about that.

I went to WordCamp Italy, yesterday and all the devs agree with that, cheers keep the good work :)

**Comment by bph** [comment]
The tool you might want to check out is the Create Block scaffolding script built by the Gutenberg team. The recent course on [Introduction to Block Development](https://learn.wordpress.org/course/introduction-to-block-development-build-your-first-custom-block/) gives a great use case for it. 

You can also follow the [block editor handbook tutorial](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/), that has helped me to get started. 
 
There are other plugins and tools that give developers shortcuts to Custom Blocks for the transition. If it's ok with you @afmarchetti I convert this issue to a discussion so others can share their journey on Custom Block development as well. Issues are more for specific feature requests or bug fixes.
