### ISSUE TITLE
Typo in table block styles in WP 6.1

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#45766]
### Description

In WP 6.1 there's a typo in the following file:

`wp-includes/css/dist/block-library/theme.css`

```
.wp-block-table {
  margin: "0 0 1em 0";
}
```

Also posted to trac:
https://core.trac.wordpress.org/ticket/57112

### Step-by-step reproduction instructions

1. Open the `www.example.com/wp-includes/css/dist/block-library/theme.css` in any browser

### Environment info

- WordPress 6.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Soean** [comment]
I can reproduce the bug in 14.5, but not in trunk, so it seems already fixed?

**Comment by Soean** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/45674

**Comment by mrleemon** [comment]
Thanks, I didn't see that PR, sorry.
Will this fix be backported to 6.1.1 or 6.1.2?
