### ISSUE TITLE
Can we add Side Nav bar expandable 

### ISSUE THREAD

**Issue by Ankush11S** [WordPress/gutenberg#45765]

**Comment by Ankush11S** [comment]
![sidenav](https://user-images.githubusercontent.com/33414888/201851258-8eede008-8fed-4601-a87f-06c3a9d3b296.jpg)
attaching the reference for proposed solution

**Comment by annezazu** [comment]
Hey there! I'm not clear what this issue is about exactly. Can you provide more context, including what problem it's solving, how you'd like to extend things, etc? Is this about the navigation component within the Site editor?

**Comment by priethor** [comment]
Closing the issue as it has been stale for a while. Please feel free to reopen if the issue persists and there is more info; thanks!
