### ISSUE TITLE
Document transformation API when it's finalized

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#4578]
From https://github.com/WordPress/gutenberg/issues/4576#issuecomment-358674717

> The shortcode will not be automatically updated but you can defined a "shortcode" transformation to allow transforming the shortcode on paste or when the user clicks explicitely on "Convert to blocks" (for old content in the classic block).
> 
> You can see an example here https://github.com/WordPress/gutenberg/blob/master/blocks/library/image/index.js#L99-L145
>
> This is not documented yet because the transform API is yet to be stabilized.

**Comment by youknowriad** [comment]
closing as this started to be documented here #5189
