### ISSUE TITLE
Docs: Missing link to SVG primitive

### ISSUE THREAD

**Issue by RadND** [WordPress/gutenberg#45804]
### Description

This issue should have a [Type] Developer Documentation label

The link is at https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/#icon-optional -> wp.primitives.SVG component 

I don't know if the original content of /src/svg/(https://developer.wordpress.org/block-editor/reference-guide/packages/packages-primitives/src/svg/) is still at somewhere else on the website ,tried but unable to find. I assume this pattern applies to other pages , too.

### Step-by-step reproduction instructions

goto https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/#icon-optional
click wp.primitives.SVG component

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bph** [comment]
Thank you, @RadND, for flagging this! I confirmed the link is going 404 

The information is available on this page in the repo 
https://github.com/WordPress/gutenberg/blob/trunk/packages/primitives/src/svg/README.md

And on the documentation site is available, too
https://developer.wordpress.org/block-editor/reference-guides/packages/packages-primitives/#usage
