### ISSUE TITLE
CSS for .wp-block-text-columns, which should not be needed, is still there.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#45810]
### Description

Some CSS for `.wp-block-text-columns` remains in the file `/wp-includes/css/dist/block-library/style.css`.

<img width="558" alt="スクリーンショット 2022-11-16 23 20 32" src="https://user-images.githubusercontent.com/31400297/202205157-1ded75d5-2222-492a-8f46-d5a80e054eeb.png">

### Step-by-step reproduction instructions

1. See `/wp-includes/css/dist/block-library/style.css`.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aristath** [comment]
If I'm not mistaken, this CSS is there for backwards-compatibility.
If on a site you were using the text-columns for some posts, removing that CSS will make them seem unstyled - and the site admin would need to edit each of those posts manually so the content gets updated.

**Comment by t-hamano** [comment]
@ddryo 
Thanks for the report.

This block has been deprecated in WordPress 5.3 and cannot be newly inserted at this time. However, without this stylesheet, this block already in the content would not styled correctly.

With stylesheet:

![has-style](https://user-images.githubusercontent.com/54422211/213654150-7a828426-cecb-46ba-a428-9bbe96de8c90.png)

Without stylesheet:

![no-style](https://user-images.githubusercontent.com/54422211/213654161-d5852ddf-4938-459e-be9d-294c3fb28ac2.png)

I would like to close this issue, as I believe it is the intent that the stylesheet remain, but if I have missed anything, please feel free to comment.
