### ISSUE TITLE
Multisite no featured image

### ISSUE THREAD

**Issue by dansdev** [WordPress/gutenberg#45836]
### Description

Hi there,

Sorry I'm unsure if this should be directed at Gutenberg or core. I have an issue/bug with the featured image meta box on a multisite installation in pages and posts.

Adding theme support for post-thumbnails in functions.php
`add_action( 'after_setup_theme', 'theme_init' );
function theme_init() {
    add_theme_support('post-thumbnails');
}
`
After enabling theme support for post-thumbnails, Featured Image box should be in sidebar on post and pages edit screens. In a multisite this is not displayed. Looking at the sidebar in chrome devtools, it's not even rendered. 

I have tested the above on a single installation and Featured Image box displays as it should.

### Step-by-step reproduction instructions

1. Install WordPress as multisite installation
2. add add_theme_support('post-thumbnails'); to functions.php
3. Navigate to post or page

### Screenshots, screen recording, code snippet

<img width="1593" alt="multisite" src="https://user-images.githubusercontent.com/87308680/202368099-52cdfb96-b679-4a2a-8ec5-7520d0177052.png">

### Environment info

WP version: 6.1.1
Theme: Twenty Twenty-Three ( also tested with Twenty Twenty-Two)
Plugins: none
Multisite

Installed locally using Local by Flywheel
Apache 2.4.43
php 8.1.9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @dansdev

I couldn't reproduce the issue when testing with WP 6.1.1 and Twenty Twenty-Three theme. I've not used the snippet to enable the post thumbnails since the Twenty Twenty-Three theme supports the feature out of the box.

Can you provide more details about your setup?

* Do you see any errors in the DevTools console?
* What is the role of the user you're testing with?

Thanks

**Comment by ndiego** [comment]
Just following up on this one as well. I tested with 6.1.1 and the Twenty Twenty-Two theme and added the code snippet included above. I have been unable to replicate the issue. The Featured Image panel is displaying for me on both posts and pages. 

![image](https://user-images.githubusercontent.com/4832319/207321841-463eab27-9e9f-4275-8957-a5d6c5e627cd.png)

**Comment by dansdev** [comment]
> Hi, @dansdev
> 
> I couldn't reproduce the issue when testing with WP 6.1.1 and Twenty Twenty-Three theme. I've not used the snippet to enable the post thumbnails since the Twenty Twenty-Three theme supports the feature out of the box.
> 
> Can you provide more details about your setup?
> 
> * Do you see any errors in the DevTools console?
> * What is the role of the user you're testing with?
> 
> Thanks

Hi @Mamaduka, @ndiego

Thank you both for taking the time to look into my issue. I can confirm that my user role is administrator and that there are indeed DevTools errors, please see below:

![console](https://user-images.githubusercontent.com/87308680/207481634-be9db0c7-fcf0-4934-964c-6e84b348f47d.png)

Interesting enough in Local if I swap over to nginx webserver, the console errors are gone and the featured image panel displays fine in pages, posts and cpts! So looks like the issue might related to either Apache or Local. This is with a fresh install of Twenty Twenty-Three without using the add_theme_support snippet.

For reference, I have tested in Local by Flywheel on Apache 2.4.43 and Nginx 1.16.0, both installations using php 8.1.9.

Cheers

**Comment by Mamaduka** [comment]
@dansdev, based on errors, the WP installation is having trouble finding REST API endpoints. It looks like an Apache server or Local issue.

I will close the issue since this isn't something we can fix in the plugin or WP.

**Comment by ramiy** [comment]
Same issue with 6.1.1 on a regular website, not multisite. In the post editing page, the "featured image" panel is missing.
