### ISSUE TITLE
Search placeholder not displaying on front-end

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/gutenberg#45837]
### Description

While working with the Twenty Twenty-Three theme, I have checked that the Search block is look weired

The search block placeholder is displaying on back-end. But, its not working on front-end and not displaying.

Here, I have attached its screenshots.

### Step-by-step reproduction instructions

1. Install latest wordpress(6.1.1)
2. Create new page and select search gutenberg block and publish that page.

### Screenshots, screen recording, code snippet

<img width="1440" alt="front-end" src="https://user-images.githubusercontent.com/53076293/202389564-592dbffe-02b7-41f0-a3f4-1e7f0c22d03a.png">
<img width="1440" alt="back-end" src="https://user-images.githubusercontent.com/53076293/202389592-7a6bca77-656c-46dc-befb-3ba2a6ca0e17.png">

### Environment info

- WordPress Version 6.1.1
- Mac M1 OS 13.0
- Google chrome Version 107.0.5304.110 (Official Build) (arm64)

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes, No

**Comment by carolinan** [comment]
I will add the same reply here as in the original trac ticket. The placeholder is optional, the text is not intended to show on the front unless the user adds a custom text.

**Comment by sabernhardt** [comment]
Not a bug: the default placeholder needs to remain empty (or not included).

However, there are a few different possibilities to improve this:
1. "Placeholder" is the name of the HTML attribute so it could be too technical, unless the user knows "[a placeholder is not a replacement for labels](https://www.google.com/search?q=placeholder+is+not+a+replacement+for+labels)." Also, parentheses _might_ help clarify that the user does not need to add anything in the editor interface. 
Suggestion: `(Optional help text)`.
2. When empty, the placeholder attribute could be removed entirely from the output.
3. It's likely too late to change where to set the placeholder in the editor, but I think the placeholder field would fit better in the sidebar than the Alternative Text field does for image blocks.
