### ISSUE TITLE
filter hook for dynamic blocks doesn't add new attributes to the frontend

### ISSUE THREAD

**Issue by tomektomczuk** [WordPress/gutenberg#45846]
### Description

I have a hook that add extra data attributes to some of my allowed blocks. The problems is the data attributes are not showing on the frontend for post-title block. In the editor everything is fine but not on the save function. I'm assuming that this hooks will not work for save function that is created dynamically (for example core/post-title). 

There is also no instruction here https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/

### Step-by-step reproduction instructions

1. Add Data attribute to any of dynamic blocks for example core/post-title
2. use getSaveContent.extraProps hook to save this data attribute

Our example
```
const addMarginPaddingDataAttributesToFrontEnd = (
    props,
    block,
    attributes
) => {
    if ( ! allowedBlocks.includes( block.name ) ) {
        return props;
    }

    const margins = prepareDataString( attributes.margins );
    const paddings = prepareDataString( attributes.paddings );

    const newAttributes = {};
    if ( margins !== '' ) {
        newAttributes[ 'data-margin' ] = margins;
    }

    if ( paddings !== '' ) {
        newAttributes[ 'data-padding' ] = paddings;
    }
    return assign( props, newAttributes );
};
addFilter(
    'blocks.getSaveContent.extraProps',
    'custom/save-data-attributes',
    addMarginPaddingDataAttributesToFrontEnd
);
```

### Screenshots, screen recording, code snippet

<img width="2140" alt="201533134-d20a6b5b-53f7-4001-aee2-f7a139aa2aaa" src="https://user-images.githubusercontent.com/40096666/202444236-5d10f187-0b89-4dbf-865b-5fcfa5eb87ad.png">
<img width="2077" alt="201533138-28f816d0-1ea4-415c-b010-4b2d55c2f785" src="https://user-images.githubusercontent.com/40096666/202444271-6e422212-3ade-4452-a028-1b92a1cdf58a.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.
I found the same information in [Discussions](https://github.com/WordPress/gutenberg/discussions/45745). Let's close this issue since I consider this to be a question, not an issue.
