### ISSUE TITLE
core/list enter to next row broken in editor

### ISSUE THREAD

**Issue by tatof** [WordPress/gutenberg#45845]
### Description

When I filter the "core/list" as an allowed_block_type the list doesn't work like it suppose to anymore. The list is displayed in gutenberg editor but I can't press enter to go to the next row. Selecting a new List **is** possible.

When I disable all "allowed_block_type" rules the lists work fine.

See this video for a demo: https://devtof.nl/listvid.mp4

### Step-by-step reproduction instructions

1. add a list and type the first item
2. Press "enter" to go to next row
3. Enter to next row doesnt work

4. disable "allowed_block_type" code
5. Enter to next row does work!

### Screenshots, screen recording, code snippet

```
add_filter( 'allowed_block_types', 'tf_allowed_block_types', 10, 2 );
function tf_allowed_block_types( $allowed_blocks, $post ) {
    $allowed_blocks = array(
        'core/paragraph',
        'core/heading',
        'core/list',
        'core/table',
        'core/audio',
        //'core/image',
        'core/video',
        //'core/quote',
        'core/columns',
        'core/embed',
        'core/spacer',
        'core/freeform',
        'acf/tf-image',
        'acf/tf-buttons',
        'acf/tf-form',
    );

    if($post->post_type === 'cases') {

        // remove items
        $disallowed = array(
            'acf/tf-big-hero',
            'acf/tf-static-steps',
            'acf/tf-static-reviews',
            'acf/tf-static-toepassingen',
            'acf/tf-static-oplossingen',
        );

        // remove and reindex
        $allowed_blocks = array_values(array_diff($allowed_blocks, $disallowed));
    }

    return $allowed_blocks;
}
```

### Environment info

- Wordpress 6.1.1
- Chrome, Brave, Edge, Firefox
- Windows 10 & 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tatof** [comment]
ps. same problem occurs with the not deprecated function "allowed_block_types_all"

```
function wpdocs_allowed_post_type_blocks( $allowed_block_types, $editor_context ) {    
    if ( 'page' === $editor_context->post->post_type ) {
        return array(
            'core/paragraph',
            'core/heading',
            'core/list',
            'core/table',
            'core/audio',
            //'core/image',
            'core/video',
            //'core/quote',
            'core/columns',
            'core/embed',
            'core/spacer',
            'core/freeform',
            'acf/tf-image',
            'acf/tf-buttons',
            'acf/tf-form',
        );
    }    
    return $blocks;
}
add_filter( 'allowed_block_types_all', 'wpdocs_allowed_post_type_blocks', 10, 2 );
```

**Comment by t-hamano** [comment]
I think it would work well if we allow `core/list-item` in addition to `core/list`. This is because, starting with WordPress 6.1 (and the latest Gutenberg), list items are blocks.

**Comment by tatof** [comment]
@t-hamano LEGEND! thank you for this. 

allow -> core/list-item is the fix.
