### ISSUE TITLE
Featured image block has no size selector in Site Editor

### ISSUE THREAD

**Issue by Humanify-nl** [WordPress/gutenberg#45842]
### Description

Recently I was happy to find that the featured image can finally be supplied with a preset image size.

However, this is only possible in the page-editor views, and not in the site / template editor. This defeats the whole purpose of setting featured image sizes for templates. 

This is a major gripe as a featured image is probably the most-used block for singles, and having to resort to classic templates or custom blocks to just set image size (an age old WP standard feature) is really not the way we want to go, but reality for 2 years now.  

The way it works now is you have to set all the image sizes for each single template by hand in the actual post. How is this a good idea for sites with 100 singles?

I can't just let clients have their way with images without setting a size. It creates uncontrollable design problems.

Also, when site editor and page editor have such discrepancies in how they deal with the same blocks, we create a bad UX where expectancy of how things work is constantly defied by the editor 'doing it differently, or restricting certain options for no apparent reason'.

### Step-by-step reproduction instructions

1. Add a new single template.
2. Add a featured image block. 
3. See the block inspector and only find these settings (screenshot).

![image](https://user-images.githubusercontent.com/82579622/202418378-9dac6bfa-793a-440d-bc6c-a54f219e7b9a.png)

4. Compare this with page editor: 

![image](https://user-images.githubusercontent.com/82579622/202418709-dfb29717-f105-426b-bd87-80f716627635.png)

5. Another weird quirk is that the image size selector only appears when an image is added.

### Environment info

- WP 6.1.1
- Default theme.
- No gutenberg.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by luisherranz** [comment]
Confirmed that differences exist between the different environments. There are also differences depending on whether the Featured Image block is inside a Query block, but only in the Site Editor.

- **Post Editor**

  No differences.

  No scale option, only height and width.

  - Outside of a Query block
    - Before adding a featured image
      - Height and width
    - After adding a featured image
      - Height and width
  - Inside of a Query block
    - Height and width

  https://user-images.githubusercontent.com/3305402/203787842-c3e4301d-8633-4ae4-baf5-5d322e3b5aa2.mov

- **Site Editor**

  Differences depending on if the block is inside a Query block or not.

  - Outside of a Query block
    - No options (height or width)
  - Inside a Query block
    - Height, width and scale

  https://user-images.githubusercontent.com/3305402/203788373-afd28df7-b45e-4c1c-b740-f67ead5753d6.mp4

**Comment by Humanify-nl** [comment]
Thanks for confirming. 

It would be great if we can control the appearance of these settings in theme.json, instead of predefined rules (that are inconsistent).

 It is currently not possible to only give user control of preset image-sizes (and remove custom height / width). This is a much needed feature, because incorrect sized images destroys layouts and site performance.

**Comment by DAreRodz** [comment]
This part seems to be related to the "Image Sizes" option not appearing.

https://github.com/WordPress/gutenberg/blob/e291564b71573e15f0b639d8b4a3ac1bf62e2bcf/packages/block-library/src/post-featured-image/edit.js#L82-L89

The image size option list is generated using the available sizes for the media object being rendered in the editor. As single templates don't show any image (there's no `postId`), that list of available sizes is empty, and therefore that setting is hidden.

I am not sure if this is intended; I agree it would be helpful to allow this kind of setting even when no image is being rendered.

**Comment by DAreRodz** [comment]
> 5\. Another weird quirk is that the image size selector only appears when an image is added.

I can confirm this. The option only appears when an image is rendered.

### Home template
<img width="500" alt="Screenshot 2022-11-24 at 13 54 21" src="https://user-images.githubusercontent.com/6917969/203791825-51f27719-d077-4a8f-b69b-ed92dd7de32e.png">

### Post content editor
<img width="500" alt="Screenshot 2022-11-24 at 13 53 37" src="https://user-images.githubusercontent.com/6917969/203791932-9ede22e6-0fd2-4cfe-8b5d-2b3c7ee6c1b5.png">

**Comment by carolinan** [comment]
The scale settings only shows if the height of the image is adjusted.
The reason why the scale setting shows in the Site Editor query example in Twenty Twenty Three,
is that the height is already adjusted in the markup of the template:
`<!-- wp:post-featured-image {"isLink":true,"width":"100%","height":"max(15vw, 30vh)","align":"wide"} /-->`
The editor height setting does not display the custom height value from the template `(max(15vw, 30vh)`.

I think showing and hiding the scale settings this way is confusing and could perhaps be improved by a help text below the height and with setting?

**Comment by carolinan** [comment]
I have tried to solve the image size issue in #46848, it could use a sanity check to see if I understood the logic correctly because there are so many conditions.
