### ISSUE TITLE
Query Loop shows empty Filters section when no filters are enabled in variation

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/gutenberg#45864]
### Description

When creating a Query Loop block variation, if the `allowedControls` does not contain any of the items found under the Filters section in the Inspector Sidebar, only the Filters heading appear.

### Step-by-step reproduction instructions

1. Register a block variation with a custom query and no allowedControls:

```js
registerBlockVariation('core/query', {
	name:  'empty-filters-test',
	title: 'Empty Filters',
	description: 'Displays a list of my streams - from a plugin',
	isActive: ['namespace'],
	attributes: {
		namespace:'empty-filters-test',
                 query: {
			perPage: 5,
			offset: 0,
		},
	},
	allowedControls: [],
	innerBlocks: [
		[
			'core/post-template',
			{},
			[['core/post-title'], ['core/post-excerpt']],
		],
		['core/query-pagination'],
		['core/query-no-results'],
	],
});
```

2. See that the Inspector Sidebar shows the Filters heading:
![Notification_Center](https://user-images.githubusercontent.com/1259027/202545952-b4632222-81a5-4204-8b0a-5a35be7df426.png)

### Screenshots, screen recording, code snippet

![Notification_Center](https://user-images.githubusercontent.com/1259027/202546010-85c683b3-13b5-4e92-a134-b963980bc67f.png)

### Environment info

- WordPress 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/45869.
