### ISSUE TITLE
Template Part Editor broken after updating to WordPress 6.1.1

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#45862]
After updating to WordPress 6.1.1 the Block Based Template Editor is loading just a blank white screen. No console error or anything.

This issue was originally reported on the make blog https://make.wordpress.org/core/2022/10/04/block-based-template-parts-in-traditional-themes/#comment-44097

@Mamaduka was successfully able to replicate this issue and has narrowed it down to the changes that were made in https://core.trac.wordpress.org/ticket/56945 specifically the lines here: https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/class-wp-theme-json-resolver.php#L423-L425

The issue happens on both WordPress 6.1.1 without any plugins and also with Gutenberg trunk.

**Comment by fabiankaegy** [comment]
I'm not sure whether this should be tracked in trac or here in GitHub. So feel free to move over as needed.

**Comment by fabiankaegy** [comment]
Props: [karks88](https://github.com/karks88), [jeffmcnear](https://profiles.wordpress.org/jeffmcnear/), and [maurodf](https://profiles.wordpress.org/maurodf/) for reporting this

**Comment by Mamaduka** [comment]
Adding a simple `theme.json` file should resolve the issue for now. This is a temporary solution before shipping the fix in the next WP release.

P.S. I would recommend using the `theme.json` file for the classic themes that have this feature enabled, at least to define the layout. You find a great example by @justintadlock here - https://gutenbergtimes.com/building-a-block-based-header-template-in-a-classic-theme/#2-adding-theme-json-support.

## Example `theme.json`
```json
{
	"version": 2,
	"settings": {}
}
```

**Comment by fabiankaegy** [comment]
Thanks @Mamaduka 😀 

I do just want to note that adding a theme.json file comes with a few side effects that may surprise someone. For example the inner container div of the group block gets removed which can cause some issues if custom styling depended on the presence of that.

**Comment by maurodf0** [comment]
> 

Thanks @Mamaduka i thought that was a releated theme.json problem cause the others users using this feature included the theme.json into their theme and commented with no problem at all.

Tested in my site and all works fine, even with empty theme.json file.

**Comment by ottomen** [comment]
Could you be so kind to say, what is the target folded for the theme.json, please?

**Comment by mrwweb** [comment]
@ottomen If you didn't figure it out yet, `theme.json` goes in the root of the active theme, e.g. `wp-content/themes/{your theme folder}/theme.json`
