### ISSUE TITLE
6037701726651810I really like the idea of expanding, but I wonder if that then needs easier ordering or something that doesn't surface everything at the same level? I worry a little about too long a list for example and problems even finding things. Something to explore!

### ISSUE THREAD

**Issue by srwrr** [WordPress/gutenberg#45874]
I really like the idea of expanding, but I wonder if that then needs easier ordering or something that doesn't surface everything at the same level? I worry a little about too long a list for example and problems even finding things. Something to explore!

_Originally posted by @karmatosed in https://github.com/WordPress/gutenberg/issues/37407#issuecomment-996943131_

**Comment by Mamaduka** [comment]
Thanks for contributing, @srwrr.

Can you update the issue title and description to provide more details?

Thanks

**Comment by srwrr** [comment]
سلام ریال ایران
