### ISSUE TITLE
Post isn't marked unsaved on paragraph changes

### ISSUE THREAD

**Issue by pento** [WordPress/gutenberg#4589]
## Issue Overview

When editing a paragraph block, the post isn't marked as unsaved until the block loses focus. This allows the window to be accidentally closed, losing any changes in that paragraph.

## Steps to Reproduce (for bugs)
1. Create a new post.
2. Add content to the first paragraph block.
3. Click "Save Draft"
4. Add more content to the paragraph block.

## Expected Behavior

The save notification changes to "Save Draft", and triggers the "are you sure" message if you press Cmd+W.

## Current Behavior

The save notification stays as "Saved", and you can close the tab without a warning that changes will be lost.

**Comment by jorgefilipecosta** [comment]
There was a PR created some time ago that should fix this problem https://github.com/WordPress/gutenberg/pull/2418.

**Comment by danielbachhuber** [comment]
I've experienced this problem too! I was wondering whether it was considered intentional behavior and am glad it's not :)

**Comment by mtias** [comment]
This should work well now.

**Comment by aduth** [comment]
Fixed by #4955
Duplicate of #2758
