### ISSUE TITLE
TinyMCE: try and expand inline boundaries to more elements

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#459]
In #207 which is on track to ship with WordPress 4.8 in May, TinyMCE will add an inline boundary feature for links and code, which you can test here: https://wordpress.github.io/gutenberg/tinymce/

This is a good first step. But we should explore also adding the inline boundary feature to `b`, `i`, `em`, `strong`, `del`, `ins`. 

We might find this is not desirable as those elements tend to be nested. But we should absolutely try it at least in prototype form, and see how it survives complex markup.

**Comment by spocke** [comment]
This has been fixed and a new option that allows you to expand the default list of elements to other things than just code and links. If this is a good idea from a UX standpoint is another question. :)
https://www.tinymce.com/docs/configure/content-appearance/#inline_boundaries_selector

**Comment by androb** [comment]
This has not been tried in Gutenberg yet AFAIK.

Re-opening this issue and assigning to a James to create a "TRY" branch for.

You can view the interaction at this CodePen: https://codepen.io/tinymce/live/EwLYBM

**Comment by EphoxJames** [comment]
PR open in #2947

**Comment by EphoxJames** [comment]
Should now be fixed in master.
