### ISSUE TITLE
It's not possible to style <cite> elements inside quote blocks via theme.json

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#45907]
### Description

The `theme.css` file in WP 6.1 for the quote block styles the <cite> element using the following code:

```
.wp-block-quote {
       .....
	cite,
	footer {
		color: currentColor;
		font-size: 0.8125em;
		position: relative;
		font-style: normal;
	}
       .....
}
```

But seeing the `class-wp-theme-json-6-1.php` file, the `cite` property inside `"styles":"elements"` only targets the `<cite>` element:

https://github.com/WordPress/gutenberg/blob/765f624944bcaf1bd7c6957fd864add6a6e73d89/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php#L113

So, it's impossible to change the color, font size or style of the `<cite>` elements inside quote blocks via `theme.json` because of specificity.

Am I missing something here?

### Step-by-step reproduction instructions

- Style the color, font size or style of the <cite> element in a theme via `theme.json` in WP 6.1.
- Add a quote block with a cite.
- The styles specified in the theme.json file are not applied.

### Environment info

- WordPress 6.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
The theme.css file is only used if the theme adds ` add_theme_support( 'wp-block-styles' )`, you probably want to remove that if you are using theme.json.

**Comment by kathrynwp** [comment]
Hi @mrleemon - given Carolina's clarification above, let me know if you still see this issue as valid or if it should be closed. Thanks!
