### ISSUE TITLE
Embedded Instagram Links Display No Preview on Safari Mobile

### ISSUE THREAD

**Issue by masperber** [WordPress/gutenberg#45901]
### Description

When using an Embed Block to display an Instagram URL, the preview is blank when viewing the Embed Block with the Safari browser version 15.7.1. The problem is not manifested on Safari version 16.1.1

### Step-by-step reproduction instructions

1. Compose a page or post
2. Insert an Embed Block with a valid Instagram URL
3. View the page or post with the Safari browser on a mobile device

### Screenshots, screen recording, code snippet

The Embed Block will look like this.

<img width="388" alt="Screen Shot 2022-11-18 at 9 03 21 AM" src="https://user-images.githubusercontent.com/12906034/202722642-a5e9f7a6-b7e7-4472-8d41-215285fb212d.png">

### Environment info

WordPress.com
WordPress 6.1.1
Gutenberg 14.5.2
Viewing with Safari 15.7.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.
As far as I know, the Instagram embed appears to have been removed by #24472 about two years ago. How did you embed it?
Also, if this can be improved by upgrading the browser, this may not be a Gutenberg problem.

**Comment by jordesign** [comment]
As there's been no further discussion on this issue in 6 months - I'm going to close it. Please feel free to re-open with further details and testing information if it is still an issue.
