### ISSUE TITLE
Provide some safety fallback UX when "Updating failed"

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#4590]
As a Gutenberg user, seeing this error message is quite terrifying:

![image](https://user-images.githubusercontent.com/36432/35129241-85b47f14-fc6f-11e7-9ec7-3aefb563c56f.png)

Specifically, my emotional state is:

> "Updating failed"?! Does this mean I'm going to lose all of the content I published?! How do I get back to safely updating?!

It would be ideal to have some secondary UX in this error state ("save your post to your browser" or similar).

The specific issue I ran into is CloudFlare deciding to block my PUT requests.

**Comment by aduth** [comment]
>The specific issue I ran into is CloudFlare deciding to block my PUT requests.

Unrelated to the UX concern you mention, but noting that this specific issue should be resolved as of #4396.

**Comment by jorgefilipecosta** [comment]
Maybe we can use the new copy all content mechanism and offer the user a link that allows copying all content to the clipboard so they feel safer.

**Comment by wsydney76** [comment]
Showing more specific error messages would also be useful for server side validation : #4063

**Comment by mtias** [comment]
Related #7367.

**Comment by paaljoachim** [comment]
What is the status of this issue? I can not remember seeing the error in a while.

Greg @gziolo

**Comment by gziolo** [comment]
@paaljoachim, I don't know this issue.

**Comment by paaljoachim** [comment]
Thanks for the response Greg!

**Comment by paaljoachim** [comment]
Thoughts on this issue?
@talldan @tellthemachines @mcsf

**Comment by talldan** [comment]
Not sure that it's much of an issue any longer. The underlying reason for the error seems to have been fixed.

There's now also a process that backs up posts to local browser storage, which offers another recovery option.

To add to the previous comment (https://github.com/WordPress/gutenberg/issues/4590#issuecomment-359491059), offering a Copy All Content option seems like a reasonable thing to do for errors relating to save.

Not sure what else can be done, usually when saving fails there's a good reason that can't be easily solved.

**Comment by mcsf** [comment]
I'm up for closing this.

**Comment by jorgefilipecosta** [comment]
Closing this issue as there are no additional action items.
