### ISSUE TITLE
The alignment control displays in block toolbar of child blocks when it shouldn't

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#45915]
### Description

When a block that supports alignment (None, Wide, Full) is placed inside of a container (i.e. Group) and "
Inner blocks use content width" is toggled off in the contrainer, the alignment controls in the block toolbar of the child block should not display since they do nothing. In Gutenberg trunk and WordPress 6.1, they still display. I believe this might actually be a regression. 

### Step-by-step reproduction instructions

1. Using the TT3 theme, copy the code snippet below into a new page. 
2. Notice that "Inner blocks use content width" has been toggled off on the container Group block. 
3. Notice that the alignment control is still present in the toolbar of the Columns block, but it does nothing. This control should be hidden when "Inner blocks use content width" is not toggled on.

### Screenshots, screen recording, code snippet

![alignment-toolbar-error](https://user-images.githubusercontent.com/4832319/202781359-18392d3f-8869-42c9-bce9-5c29a33c67f1.gif)

**The sample code used in the gif**

```
<!-- wp:group {"align":"full","backgroundColor":"contrast","layout":{"type":"default"}} -->
<div class="wp-block-group alignfull has-contrast-background-color has-background"><!-- wp:columns {"backgroundColor":"tertiary","textColor":"contrast","blockVisibility":{"hideBlock":false}} -->
<div class="wp-block-columns has-contrast-color has-tertiary-background-color has-text-color has-background"><!-- wp:column {"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}}}} -->
<div class="wp-block-column" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><!-- wp:heading {"fontSize":"large"} -->
<h2 class="has-large-font-size">Heading</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"small","blockVisibility":{"hideBlock":false}} -->
<p class="has-small-font-size">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut leo nibh, placerat eget nisi non, sagittis convallis purus.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}}}} -->
<div class="wp-block-column" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><!-- wp:heading {"fontSize":"large"} -->
<h2 class="has-large-font-size">Heading</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut leo nibh, placerat eget nisi non, sagittis convallis purus.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->
```

### Environment info

- WordPress 6.1 
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Closing this issue as it is no longer recreatable in WP6.2 and GB 16.1
