### ISSUE TITLE
Traditional indented paragraphs

### ISSUE THREAD

**Issue by ericmacknight** [WordPress/gutenberg#45926]

**Comment by ericmacknight** [comment]
I have used WordPress for years to create class blogs where my students publish essays, poems, and stories. It is great, in so many ways.

However, it sucks when it comes to teaching students what a paragraph is.

I have been waiting for years for WP to include a way to indent the first line of a paragraph, or not, that is a simple as a word processor. Alternatively, a plug-in. It’s 2022, and still no joy.

First-line indents are crucial when including a block quotation in a paragraph: the lack of an indent when the paragraph resumes after the block quotation shows that the reader is still in the same paragraph. With block paragraphs (the default in WP) it is impossible to tell the difference between a new paragraph and a continuation of a paragraph after a block quotation.

First-line indents are crucial, too, when writing dialogue.

I have seen two solutions proposed: 1. CSS code that indents *all* paragraphs. This is useless for those who want to indent the first line of some paragraphs, but not all. 2. Hit the space bar five times. Sometimes this works; other times it does not. So, for students trying to learn what a paragraph is, this is just confusing.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/37462 and https://github.com/WordPress/gutenberg/issues/34688 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

Please reply back if neither of those issue covers your needs.
