### ISSUE TITLE
Template Part semantic areas are no longer recognised

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#45935]
### Description

<img width="1597" alt="Screenshot 2022-11-21 at 09 15 37" src="https://user-images.githubusercontent.com/846565/203011711-50338f57-b174-48fc-9f55-d33318a93a00.png">

In the screenshot above note that the general template part icon is used for the selected Header, and the Footer in list view. Additionally the the block name in the Inspector is incorrect (may be related to https://github.com/WordPress/gutenberg/issues/42154).

### Step-by-step reproduction instructions

1. Open the site editor
2. Select a header or footer template part
3. Ensure it has the 'header' or 'footer' semantic area set (check the Advanced panel in the Inspector)
4. Observe the icon, and block name in the Inspector

### Environment info

Latest trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
If I'm following this correctly, I can replicate with 6.2 RC 2:

<img width="1444" alt="Screen Shot 2023-03-20 at 3 24 08 PM" src="https://user-images.githubusercontent.com/26996883/226478613-07548ad3-5e32-4103-900e-dc4ec6cc37a0.png">
