### ISSUE TITLE
Content missing from first post in Query Loop in custom template.

### ISSUE THREAD

**Issue by Andrew-Starr** [WordPress/gutenberg#45938]
### Description

When creating a custom template containing a Query Loop, the Post Content of the the first post in the loop is missing when viewed on the front end.

Issue reported in TT2 support forum: https://wordpress.org/support/topic/editor-template-blogs-first-content-missed/

### Step-by-step reproduction instructions

Add a new “Custom Template”.
Insert a Query Loop block, make sure “Inherit query from template” is toggled off, and select Post as post type.
In the Query Loop change the Post Exceprt to the Post Content block.
Save the template.

Go to Pages > Add New and create a new page.
Leave page content empty.
Set the page to use the new custom template created previously.

View the page in the front end and notice that the Post Content block is missing from the first post in the Query Loop.

Go back to edit the page and write a paragraph of content.
View the page in the front end and notice that now the first post in the Query Loop is displaying the Post Content but it is the paragraph from the page, when it should be the content of the first post in the query loop.

### Environment info

WP 6.1.1
Issue present with and without Gutenberg 14.5.4 active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@Andrew-Starr
Thank you for the report.

I think this issue is the same as #40743 and appears to be exactly the same as the reproduction procedure in [this comment](https://github.com/WordPress/gutenberg/issues/40743#issuecomment-1229122424).
Let's close this issue and focus the issue on #40743.
