### ISSUE TITLE
[Navigation Block] Experiment: Add Text input to the sidebar when we edit a link menu item

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#45952]
When we edit a link in the navigation block, the text of the link can only be edited in the canvas. We have options to change the rest of the attributes of the link on the sidebar, we should add the text too.

![Screen Capture on 2022-11-21 at 18-59-55](https://user-images.githubusercontent.com/3593343/203128596-c108386c-c09d-438c-bb22-70b65afa1add.gif)

**Comment by scruffian** [comment]
Closed by #45964
