### ISSUE TITLE
[Navigation Block] Experiment: Change focus when we edit a menu item to the correct tab

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#45951]
### Description

When we are editing a menu item, we want the focus to be on the Settings tab instead of the Appearances one, since we are expecting to edit content before styling.

### Step-by-step reproduction instructions

Turn on the Gutenberg experiments _Off canvas navigation_ editor and _Block inspector tabs_ 
Edit a link on the navigation block

### Screenshots, screen recording, code snippet

![Screen Capture on 2022-11-21 at 19-01-27](https://user-images.githubusercontent.com/3593343/203127875-3361f98f-1ef2-4a4f-83ba-e2d82c54b76c.gif)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Random thoughts, and not something to act on: This seems to challenge the idea of appearance alway being the first tab for every user. Which makes me wonder whether there might be other options for the future.

e.g. a designer role where appearance is always first, and an editor role where settings is always first. Other alternatives could could be making this a preference or an editor mode (design mode, but then there wouldn't necessarily be a need for tabs). Or the editor could remember the last selected tab (would need an a11y check on this).

**Comment by scruffian** [comment]
Also noting that the Navigation block has this List View button which opens the inspector controls. Ideally it would also focus the first tab.
<img width="184" alt="Screenshot 2022-12-09 at 15 56 12" src="https://user-images.githubusercontent.com/275961/206741643-e56cabf4-37fd-442d-996c-29296d1e0496.png">

**Comment by scruffian** [comment]
Now that Navigation List blocks don't have tabs I think this is no longer an issue.
