### ISSUE TITLE
Enable "Allow Comments" by Default.

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#4595]
When creating a new post the "Allow Comments" option is currently set to off by default. It should be ON.

![image 2018-01-19 at 1 06 31 pm](https://user-images.githubusercontent.com/5817882/35140675-edbf2cb2-fd19-11e7-9440-15ff73aa57fd.png)

**Comment by Soean** [comment]
This is the same behavior as in the old editor. It depends on what you have defined in the discussion settings in "Allow people to post comments on new articles".

**Comment by munirkamal** [comment]
@Soean Yeah I am aware of that setting. I checked that already and the comments are allowed. Still, this option is set to off by default on every new post I create. Actually, everything is set to default as it is a fresh WordPress installation.

![image 2018-01-19 at 2 48 50 pm](https://user-images.githubusercontent.com/5817882/35145000-12cabd10-fd28-11e7-81b8-c93d6a13f462.png)

**Comment by Soean** [comment]
Does it work in the classic editor?

**Comment by munirkamal** [comment]
Just checked in the classic editor. If I create a new post directly in the classic editor the "Allow comments" is checked by default. But not the same when I create the new post in Gutenberg. 

![image 2018-01-19 at 3 07 12 pm](https://user-images.githubusercontent.com/5817882/35145710-aa6363fa-fd2a-11e7-8dc5-d2eacab29231.png)

P.S. it's the same website with same plugins/theme, etc.

**Comment by karmatosed** [comment]
It is important to allow people to have the option to turn comments on. As a result closing this for now. If there is a bug we can have an issue for that.
