### ISSUE TITLE
Child themes should inherit style variations

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#45965]
## What problem does this address?

When creating a child theme for an existing block theme that has style variations (such as Twenty Twenty Three), the child theme will currently _not_ include those style variations. If the child theme author wishes to have them included, they will have to manually copy the parent theme's `styles/` folder.

First reported in WP.org support forums [here](https://wordpress.org/support/topic/unsuccessful-in-making-child-theme/).

## What is your proposed solution?

Per discussion with @MaggieCabrera: Have child themes include the parent theme's style variations automatically, plus any style variations that the child adds. (If there are any naming collisions, the child's style variation should probably override the parent's style variation with the same name.)

Rationale: I feel that this would be consistent with the way child themes of block themes handle templates. Furthermore, we might want to retain the possibility to create a child theme that only consists of a `style.css` file (and still inherit all the parent's functionality), as is possible with classic themes.

We might want to take stock of any other features of block themes that might also not currently be automatically inherited by their child themes.

---

Note that there is a learn.wordpress.org [resource](https://href.li/?https://learn.wordpress.org/lesson-plan/create-a-basic-child-theme-for-block-themes/) on that subject, and while it mentions that a Block Theme’s child theme should include a `theme.json`, there’s no mention of requiring a `styles/` folder to include Style Variations. For now, I'll ask to update that resource to include instructions how to add the parent's style variations.

**Comment by scruffian** [comment]
I agree that they should be inherited.

**Comment by carolinan** [comment]
Same, I did not realize they were not inherited until this morning.

**Comment by luminuu** [comment]
+1 for showing the parent theme style variations in a child theme.

**Comment by ockham** [comment]
Thanks all! Seems like there's unanimous agreement on the desired behaviour 🎉 

Anyone got some spare cycles to implement this? 😬  (My team's focus will be different in the near future.)

**Comment by carolinan** [comment]
Should the child theme also be able to set variations to "false" ? I mean I think there are use cases where you may want 3 out of 10 variations.

**Comment by MaggieCabrera** [comment]
> Should the child theme also be able to set variations to "false" ? I mean I think there are use cases where you may want 3 out of 10 variations.

could be interesting to explore as a follow up, but we don't do that for things like templates or template parts or even patterns

**Comment by carolinan** [comment]
There are already built in ways to remove both of them but sure it can be a follow up :)

**Comment by jffng** [comment]
I opened a PR above to solve this, let me know what you think! 🙏

**Comment by jffng** [comment]
In the case that a child variation overrides the parent, would it be preferred for the styles to actually be merged? That is, the child still overwrites the parent variation, but also inherits styles from the parent variation of the same name?

**Comment by ockham** [comment]
> In the case that a child variation overrides the parent, would it be preferred for the styles to actually be merged? That is, the child still overwrites the parent variation, but also inherits styles from the parent variation of the same name?

Good question 🤔 Do you think that'd be more ergonomic from a theme author's perspective?

**Comment by ndiego** [comment]
> Good question 🤔 Do you think that'd be more ergonomic from a theme author's perspective?

This would allow you to create a child theme that simply tweaks one of the style variations. Not sure how challenging this would be to support, but it would be a good enhancement.

**Comment by jffng** [comment]
> Do you think that'd be more ergonomic from a theme author's perspective?

I think so, but not sure if it overcomplicates the matter. Opened up a follow up issue to track: https://github.com/WordPress/gutenberg/issues/47265
