### ISSUE TITLE
Restricting blocks that can be used in a block pattern

### ISSUE THREAD

**Issue by mizukimadness** [WordPress/gutenberg#45972]
When creating Block Patterns via the Gutenberg Editor, it's possible to lock the layout, preventing new blocks from being added.
However - it would be nice if it was possible to allow what blocks can be added, when adding the Block Pattern to a page. For example, if I prepare a two column layout for a client, I would prefer to restrict what blocks can be added into these columns. For example, only headings, paragraphs, and images.

This could be done via some kind of checkbox in the editor, or just by adding a property to the json in the html comment, just like you do with "lock":{"move":true,"remove":true}" for example.

**Comment by mtias** [comment]
We have discussed lifting up the `allowedBlocks` prop of InnerBlocks to an attribute of groups and containers. It could be part of the lock modal.

**Comment by youknowriad** [comment]
Group block now supports `allowedBlocks` attribute, so It's actually possible already to add `"allowedBlocks": [ "core/paragraph" ]` to a group block to restrict the available blocks there. I think this can be considered solved.

**Comment by mtias** [comment]
For completeness, it'd also be exposed in the UI #62703
