### ISSUE TITLE
List block styles will be reset in 6.1.1.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#45987]
### Description

When I edit an article written before 6.1 in 6.1.1, the list block settings disappear.

I have not tried all the settings, but "ADDITIONAL CSS CLASS", "Color" settings, etc. will be reset.
At least, the `attributes.className` data seems to disappear.

This bug occurs when updating from 6.0.3 to 6.1.1, for example, and does not occur when updating from 6.0.3 to 6.1.

Therefore, it is believed to be a bug in 6.1.1.

### Step-by-step reproduction instructions

1. Prepare an environment with a version of 6.1 or earlier and use the list. (e.g., 6.0.3)
2. Place the listing block and change the background color.
3. Save the article.
4. Update to 6.1.1 and open the edit window for that article again.
5. You will see that the background color has disappeared.

### Screenshots, screen recording, code snippet

List block in 6.0.3

<img width="1100" alt="ss-wp603" src="https://user-images.githubusercontent.com/31400297/203487209-23fb3865-20a8-424e-9e5e-77c75632c367.png">

Updating to 6.1.1 will result in the following.

<img width="1100" alt="ss-wp611" src="https://user-images.githubusercontent.com/31400297/203487303-ec0ef9cd-7283-42f0-b76e-3f62f63b55e1.png">

### Environment info

- WordPress: 6.1.1
- Twenty Twenty-Three: 1.0
- No Plugins.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I suspect that #44822 backported to 6.1.1 may have something to do with it.
Here, it looks like `attirubutes.className` is lost:

https://github.com/WordPress/gutenberg/pull/44822/files#diff-88e6029dd203a4e41e56514b7536681626386e077e69b405252ba650c7972bdcR75

**Comment by ddryo** [comment]
Hello.

There are quite a few users (in Japan) who are having trouble with this bug and they are still using 6.0 and waiting for it to be fixed.

Will this bug be fixed in 6.1.2 ? (I have already submitted a PR and it has been merged...)

**Comment by talldan** [comment]
@ddryo I don't know that there's any plan to do a 6.1.2 release with [WordPress 6.2 beta](https://make.wordpress.org/core/6-2/) so near.

I'm not involved in the release process though, so I'd recommend asking in the #core slack channel.

**Comment by ddryo** [comment]
@talldan 
I still reproduced this bug in 6.2.

This is a very serious problem, so why is it being put off?

I know that the pull requests to fix this bug were also merged long ago.


Sorry, I know this is probably not the right thing to say to talldan, but could you please send a mention to a member who can address this issue?
