### ISSUE TITLE
Allow link suggestions to be configurable

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#4598]
## Issue Overview

The url-input component uses `wp.api.collections.Posts` to suggest posts you might want to link to, as you type a link.

This doesn't work for all WordPress installs (on some configurations, the `Posts` collection isn't usable), and some networks want to suggest posts from all of their sites.

This issue is to discuss possible solutions.

**Comment by danielbachhuber** [comment]
While working on #4649, I thought of an alternate implementation:

* Gutenberg introduces a `gutenberg/v1/link-suggestions` endpoint.
* A Link Suggestion Resource (aka truly RESTful) implements title and URL attributes.
* By default, the endpoint is fed from Posts. However, a third-party could override that with whatever data they want.

**Comment by danielbachhuber** [comment]
@iseulde @nylen I think ^ would be a reasonable solution for https://core.trac.wordpress.org/ticket/39965 too.

**Comment by danielbachhuber** [comment]
also @kadamwhite ^

**Comment by kadamwhite** [comment]
This makes sense to me. Making the endpoint's query filterable could turn up whatever is relevant to that site. I would also recommend the result contain an ID or GUID attribute in addition to the URL and title.

However, I'm a little more skeptical that this will be a sufficient solution for #39965; worth discussing, for sure, but our experience is that developers are always frustrated having to make two requests, and providing a slimmed-down search endpoint will still mean that we need to individually query for the full resources (discussions from the 4.8 cycle suggest returning multiple resources with different structures in one request could be an issue for API clients written in certain languages).

**Comment by danielbachhuber** [comment]
> worth discussing, for sure, but our experience is that developers are always frustrated having to make two requests, and providing a slimmed-down search endpoint will still mean that we need to individually query for the full resources

How much data do you think would need to be included in the response in order to be sufficient?

**Comment by kadamwhite** [comment]
@danielbachhuber I think that question's out of the scope of this GitHub issue; let's continue it in trac perhaps? But briefly, I don't know that I can say. Custom post types may not even use or have post content or a title, and meta may be needed for some rather than others, so it's unpredictable. There doesn't seem to be an easy one-size-fits-all solution.

**Comment by danielbachhuber** [comment]
This will be addressed with #2084
