### ISSUE TITLE
Title of panel Categories & Tags is wrong when only one taxonomy is used

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#4599]
## Issue Overview
When a custom post type uses either Categories **or** Tags, the title of the panel is _Categories & Tags_.

## Expected Behavior
The title of a panel should reflect its content.

## Possible Solution
Use separated panels for each taxonomy or a neutral term like _Taxonomies_ (or easier to understand ; maybe _Classification_).

---

Tested with Gutenberg 2.0
Related to #2450.

**Comment by afercia** [comment]
Example screenshot: classic editor vs. Gutenberg (Jetpack's Portfolio "Project" Taxonomy):

<img width="700" alt="screen shot 2018-02-07 at 15 03 02" src="https://user-images.githubusercontent.com/1682452/35923821-9c1a8f20-0c21-11e8-91f0-31aab9e65da7.png">

As mentioned in #4934 there are also other labels provided by custom taxonomies the UI should probably use, for example the "add new", "parent", "choose", etc.

**Comment by jorgefilipecosta** [comment]
It looks like we have many possible ways to solve the issue:

1. Rename the top level panel to "Taxonomies".
2. Promote each taxonomy to be a top level (equal to the classic editor) so in the picture provided by @afercia we would not have "Categories & Tags" we would to top-level panels called "Project Types" and "Project Tags".
3. Use a more complex naming mechanism for categories & tags e.g: if categories and tags are the only taxonomies use categories &tags, if just category use category if tags use tags, if other taxonomy use "Taxonomies".

What are your thoughts on this?
cc: @afercia, @karmatosed, @mtias,

**Comment by afercia** [comment]
@jorgefilipecosta not sure. Personally, I don't like to have categories and tags in the same panel because when there are lots of categories (not so uncommon) I'm forced to scroll a lot to get to the tags form.

**Comment by karmatosed** [comment]
I would vote for:

> Promote each taxonomy to be a top level panel (equal to the classic editor) so in the picture provided by @afercia we would not have "Categories & Tags" we would to top-level panels called "Project Types" and "Project Tags".

There is prior format for this in right now. Also having another level 'Taxonomies' seems to make not much sense to many.

**Comment by aduth** [comment]
Closed by #5183

**Comment by aduth** [comment]
Oops, for some reason I thought #5183 had already been merged. I believe the plan is for it to be merged shortly, otherwise this ought to be reopened.
