### ISSUE TITLE
Cannot start a new paragraph or add an image on Android

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#46]
Steps to reproduce:

1. Go to https://wordpress.github.io/gutenberg/ using an Android device.
1. Tap on the (+) menu at bottom left.
1. Try to tap on "Paragraph" to start a new paragraph.
1. Try to tap on "Image" to tap a new image.

<strong>Result:</strong> the controls to add new content blocks seem unresponsive. (<a href="https://cloudup.com/cyPz7x--tIo">19s</a>)

Tested with Chrome on a Pixel with Android 7.1.1.

**Comment by jasmussen** [comment]
Yaaay Sheri! Your testing skills will be super appreciated!

Currently the prototype is primarily for the UI feel, and we haven't tested much on mobile at all yet. It probably wasn't initially meant to grow into anything but a starting point for testing the UI, however recent contributions to this repo suggests it might actually grow into something more!

So for posterity, at the time of this writing, the insert dialog is simply a dummy dialog that doesn't do anything, on desktop or mobile.

**Comment by designsimply** [comment]
<blockquote>So for posterity, at the time of this writing, the insert dialog is simply a dummy dialog that doesn't do anything, on desktop or mobile.</blockquote>

Cool cool. Since the [call for testing for the prototype](https://make.wordpress.org/design/2017/02/09/initial-gutenberg-prototype-editor-testing/) (❤️ed seeing this!) mentioned writing a paragraph of text and adding an image, I had assumed those would be functional in the prototype. I'll try to get more details on what features are meant to be tested and what the known issues are before I test in the future!
