### ISSUE TITLE
List View: Display image thumbnails

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#46015]
When there are many images in a document we might help users distinguish between them in List View by including a thumbnail of the image itself:

<img width="1013" alt="Screenshot 2022-11-23 at 18 04 01" src="https://user-images.githubusercontent.com/846565/203617661-13d5efc8-2d18-4859-8761-8ddd18bf6d61.png">

For Gallery blocks we can stack the thumbnails like: 

<img width="300" alt="Screenshot 2022-06-23 at 16 25 03" src="https://user-images.githubusercontent.com/846565/203617398-8a888ef2-baa3-4bf3-b972-35ee64fe6b78.png">

**Comment by richtabor** [comment]
Interesting. Not 100% sure if it’d work, but have you tried using the image in lieu of the icon?

It may be funky though.

**Comment by jameskoster** [comment]
I did try that, it could work, but I was a bit worried that it might negatively impact scan-ability. Also not entirely sure how it would work for galleries where it is nice to see the first _x_ images.

One thing to figure out is how those gallery thumbnails behave when you expand/collapse. Since the thumbnails will be visible on the children when expanded, there's no need to display them on the parent as well.

**Comment by richtabor** [comment]
Yea.. Perhaps this works for image blocks only?

**Comment by jameskoster** [comment]
Yeah starting with images would probably make sense.

**Comment by andrewserong** [comment]
I'll be keen to have a go at this one if no-one beats me to it. Just adding a link that this feature was mentioned in the make/core post for the media library (under "Improve presentation of media in other editing contexts"): https://make.wordpress.org/core/2023/07/07/media-library/

**Comment by mtias** [comment]
Would love to get this one in and see how it performs. For the gallery, the idea should be that the stack is only rendered if the gallery is collapsed—otherwise it's redundant with the image block children.

**Comment by andrewserong** [comment]
Implemented in #53381
