### ISSUE TITLE
Dynamic blocks not showing a preview

### ISSUE THREAD

**Issue by shramee** [WordPress/gutenberg#4601]
## Issue Overview
Dynamic blocks registered with `wp.components.withAPIData` not previewing in Gutenberg Editor.

## Steps to Reproduce (for bugs)

1. Register a dynamic block that uses `wp.components.withAPIData` to show results, (handbook example can be used) and add PHP handler for it.
2. Add the block in Gutenberg editor, It shows a nice preview. Save the post.
3. View the post, shows as specified in PHP block rendering function.
4. Now editing the post again shows empty block in place of dynamic block preview.

Happens in Chrome on WP 4.9.2 in Gutenberg v2

## Expected Behavior

It should show the preview it shows when adding a new block again when editing the post.

## Current Behavior

It shows an empty block.

## Possible Solution

Well execute withAPIData function when block is showed when post is displayed for editing.

## Screenshots / Video

![image](https://user-images.githubusercontent.com/11048263/35150854-077acc56-fd42-11e7-921d-a28cfac38bb2.png)
![image](https://user-images.githubusercontent.com/11048263/35150895-37406e1e-fd42-11e7-8db4-8eea57500e0c.png)

**Comment by mtias** [comment]
Can you show your `edit` and `save` functions?

**Comment by shramee** [comment]
```JS
jQuery( function ( $ ) {

	var el = wp.element.createElement,
		registerBlockType = wp.blocks.registerBlockType,
		withAPIData = wp.components.withAPIData;

	registerBlockType( 'my-plugin/latest-post', {
		title: 'Latest Post',
		icon: 'megaphone',
		category: 'widgets',

		edit: withAPIData( function () {
			return {
				posts: '/wp/v2/posts?per_page=1'
			};
		} )( function ( props ) {
			if ( ! props.posts.data ) {
				return "loading !";
			}
			if ( props.posts.data.length === 0 ) {
				return "No posts";
			}
			var className = props.className;
			var post = props.posts.data[0];

			return el(
				'a',
				{className: className, href: post.link},
				post.title.rendered
			);
		} ),

		save: function () {
			// Rendering in PHP
			return null;
		},
	} );
} );
```

**Comment by shramee** [comment]
@mtias This happens when using document ready wrapper on block registering functions...

So we can close this now...

Might help others trying to call `registerBlockType` on document `ready` event :sweat_smile:
