### ISSUE TITLE
Feature request — specify font weights in theme.json

### ISSUE THREAD

**Issue by chrisgresh** [WordPress/gutenberg#46046]
I'm using full site editing for the first time in a theme and am super impressed with how far the project has come. Thanks for all the hard work everyone. Also please forgive me if I've missed something and this is already possible, please let me know! I've searched the docs and the closest I can find would be to use `fontFace`, which doesn't quite seem to do what I'm asking here.

## What problem does this address?

I often will load webfonts from Adobe and Google, and only grab specific weights, e.g. 300 and 800. Currently, enabling `fontWeight` will give users every option from 100 through to 900, meaning they can specify weights that might not be available to the user. It would be helpful to be able to limit the choices via a setting in theme.json.

## What is your proposed solution?

Since available weights will often vary by font, I suggest adding a setting in `fontFamilies` that allows you to limit available weights, e.g.:

```
"fontFamilies": [
        {
          "fontFamily": "'Inter', 'Helvetica', 'Arial', sans-serif",
          "slug": "primary",
          "name": "Primary",
          "weights": ["300", "800"] // Two weights are allowed for primary font
        },
        {
          "fontFamily": "'Lora', 'Georgia', serif",
          "slug": "secondary",
          "name": "Secondary",
          "weights": ["500"] // Only one allowed for second font
        },
        {
          "fontFamily": "'Courier New', monospace",
          "slug": "monospace",
          "name": "Monospace" // Weights are not specified, allowing all options
        }
      ]
```

The `fontWeight` setting would still be useful for toggling this option.

For bonus points, it would be good to ensure that bolded text (such as title blocks or text marked with `<strong>`) use these set weights.

**Comment by skorasaurus** [comment]
Hi, thanks for reporting & providing a detailed description. This has already been requested at https://github.com/WordPress/gutenberg/issues/39685 . Please subscribe to that issue to follow its progress.

**Comment by skorasaurus** [comment]
Regarding the bold; that may be covered under https://github.com/WordPress/gutenberg/issues/30297
