### ISSUE TITLE
The More block does not work inside a reusable block

### ISSUE THREAD

**Issue by thuongmhh** [WordPress/gutenberg#46045]
### Description

The More block is ignored when it is put inside a reusable block. It only works fine when it is placed directly on the post content.

I read the WordPress code, and it seems that more tag checking is performed before the reusable block is rendered. The more tag should be checked after all reusable blocks are rendered to HTML.

### Step-by-step reproduction instructions

1. Create a new post, and write 2 paragraphs.
2. Insert a more block between them.
3. Save and view the post on an archive page. Only the first paragraph should be displayed, which is expected.
4. Now convert the more block and the second paragraph to a reusable block, and save the post.
5. View the post on an archive page again. Now both paragraphs will be displayed, which is unexpected.

### Environment info

WordPress 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I've just tested this and the behaviour is no longer present in WordPress 6.3 RC3 - so I'll close this issue as resolved.
