### ISSUE TITLE
Navigation Link: Handle rich text better in the label

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46055]
## What problem does this address?
When navigation links contain formatting, this gets displayed in the label as HTML.
<img width="536" alt="Screenshot 2022-11-25 at 13 07 25" src="https://user-images.githubusercontent.com/275961/203992550-e070fa11-7187-4eb2-ba2a-ec3a56121ff0.png">

## What is your proposed solution?
I'm not sure, but we need to find an input that allows formatting.

**Comment by getdave** [comment]
LinkControl handles this already I think. Maybe we should look at how that works?

**Comment by draganescu** [comment]
My first thought is to build a rich text input :) that looks like a TextControl but supports displaying formatted text. It is possible but a bit weird.

**Comment by getdave** [comment]
https://user-images.githubusercontent.com/444434/204008940-b0338497-f1cd-4921-9ce9-c247d5c92fdc.mp4

Link Control just ignores formatting. It was a compromise we settled on.

**Comment by draganescu** [comment]
@getdave it doesn't ignore it, it removes it - but i can't see any better way either :D

**Comment by scruffian** [comment]
The "better way" might be to just replace the inspector controls with the Link UI

**Comment by getdave** [comment]
> The "better way" might be to just replace the inspector controls with the Link UI

Yeh but the simplest next step is to ignore it.

**Comment by getdave** [comment]
I would recommend reviewing [a similar discussion which occurred here between Joen, Ella and myself](https://github.com/WordPress/gutenberg/pull/35457#issuecomment-940772002). It has a lot of good research and discussion.

**Comment by scruffian** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/46171
