### ISSUE TITLE
'block-templates' theme support breaks the site editor on classic themes

### ISSUE THREAD

**Issue by abaicus** [WordPress/gutenberg#46054]
### Description

Since 6.1.1 core version, adding the `block-templates` theme support to a classic theme causes the site editor page to load as empty.

### Step-by-step reproduction instructions

1. Activate any classic theme (I tried on twentytwenty and a bunch of other themes);
2. Add the following code in the `functions.php` file:
```php
add_action( 'after_setup_theme', function() {
    add_theme_support( 'block-templates' );
} );
```
3. Add a `templates` folder inside the root folder of the theme;
4. Add a `index.html` file inside of the `templates` folder with any content - I used the following:
```html
<!-- wp:heading {"textAlign":"center","level":1,"fontSize":"xxl"} -->
<h1 class="has-text-align-center has-xxl-font-size">Our awesome blog</h1>
<!-- /wp:heading -->
```
5. Go to `wp-admin/site-editor.php` on the website;
6. The site editor will load a blank page, and there are no errors in the console;

### Environment info

- WordPress core 6.1.1 - it used to work with 6.1.0;
- The same thing happens with Gutenberg installed;
- Happens both in Chrome and Firefox;
- I am on macOS 13.0.1 Ventura;

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I believe this is the same issue as described in #45862.

**Comment by abaicus** [comment]
Indeed, @Mamaduka! Thanks for pointing it out. I will close this one as it seems a PR has already been made there 👍🏻 

Thank you!
