### ISSUE TITLE
Cover Image H2 does not appear in Table of Contents

### ISSUE THREAD

**Issue by AdamSoucie** [WordPress/gutenberg#4606]
## Issue Overview

After converting an H2 from a standard heading to a cover image, the H2 was removed from the Table of Contents.

## Steps to Reproduce (for bugs)

1. Create a heading block
2. Observe the table of contents entry for the heading
3. Convert the heading block to a Cover Image block
4. Observe the change in the ToC

Observed in Chrome on an MBP running High Sierra

## Expected Behavior

If the cover image text is an H2, it should remain in the Table of Contents as an H2

## Current Behavior

Right now, the H2 is not appearing in the ToC

## Possible Solution

If https://github.com/WordPress/gutenberg/pull/3444 gets fully implemented, this becomes somewhat of a moot point. That being said, having the ability to make any header a cover image would be greatly appreciated.

## Related Issues and/or PRs

https://github.com/WordPress/gutenberg/pull/3444

**Comment by jasmussen** [comment]
Per discussions in #4616, we decided that #3444 is indeed the way to go. 👍
