### ISSUE TITLE
React Fast Refresh not working - possibly misconfiguration

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#46069]
### Description

# React fast refresh does not work with @wordpress/scripts^24.6.0 

I get the following message:
```
[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'reconnect'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
```

### Step-by-step reproduction instructions

Scripts setting in package.json:
```
"blocks_hot": "wp-scripts start --webpack-src-dir=./src/blocks --hot"
```

then I issued:
```
npm run blocks_hot
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
cc @ryanwelcher

**Comment by Lovor01** [comment]
I debugged this, it was misconfiguration in my webpack.config.js of the project, it worked previously, probably due to a reason that previous versions did not check erroneous config object properties.
My mistake, I'll close this issue.

**Comment by Mamaduka** [comment]
Thanks for the follow-up, @Lovor01!
