### ISSUE TITLE
Posts publishing while losing tags

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/gutenberg#4607]
## Issue Overview

While using Gutenberg on Make/Core I've noticed that when I publish posts that any tags added to the post are lost upon publish. I'm able to re-add those tags via the Quick Edit feature in WP Admin, but that's the only reliable way that I've found. I tend to clone previous posts, so I'm not 100% certain this applies to non-cloned, new posts.

## Steps to Reproduce (for bugs)

1. Clone an existing post.
2. Edit content within the post, including adding and removing tags.
3. Publish post within Gutenberg.

As seen using a MacBook (Retina, 12-inch, Early 2016) with macOS 10.13.2 and Firefox 57.0.4 (64-bit).

## Expected Behavior

The post should publish with the list of tags assigned during editing within Gutenberg.

## Current Behavior

The post publishes but has zero tags attached to it. I then have to go back to Quick Edit in WP Admin to re-assign the lost tags. However this means that the post goes out to email subscribers without any tags noted (not a major issue, but a noted downside).

## Related Issues and/or PRs

I've scanned through the list of existing issues and this appears somewhat related to #2545.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/5879#issuecomment-380990325
