### ISSUE TITLE
WooCommerce Blocks load MUCH slower than classic WooCommerce Widgets

### ISSUE THREAD

**Issue by apenchev** [WordPress/gutenberg#46071]
### Description

The WooCommerce blocks have been a terrible experience for our store, as they avoid page caching and use the slow WordPress REST API – each REST API call takes around 1.8s; hacking WP REST Cache to work with WooCommerce was not enough to make the fetch response time reasonable. The classic WooCommerce widgets, on the other side, are way faster – they don’t rely on the REST API and work with page caching. Would love it if the blocks had an option to avoid using the REST API! That would combine the best of both worlds. I've added videos from our website (which uses cheap shared hosting) showcasing the big difference in loading times.

### Step-by-step reproduction instructions

1. Install WooCommerce: https://wordpress.org/plugins/woocommerce/
2. Create a Page with the following blocks: Product Categories List, Filter by Price, All Products
3. Save & Publish the Page
4. Install the Classic Widgets plugin: https://wordpress.org/plugins/classic-widgets/ 
5. From /wp-admin/widgets.php, add the following Widgets: Product Categories, Filter by Price
6. Create & Publish a new empty Page (that will be used as the WooCommerce's Store Page)
7. From /wp-admin/admin.php?page=wc-settings&tab=products, change the Products Page to be the page from step 6.
8. Now, compare the loading times and perceived performance of the pages from step 6. and step 2.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/3998720/204028386-80b917e3-497c-47be-9813-ee8381298867.mp4

![fetch](https://user-images.githubusercontent.com/3998720/204028393-bad57151-5f9d-423f-8600-9186673b1a47.PNG)

https://user-images.githubusercontent.com/3998720/204028396-b730c314-7b73-46fa-a1de-d94d61e259c5.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
Hi, @apenchev

This is a WordPress block editor development repository; for WooCommerce block-related problems, I would recommend creating an issue here https://github.com/woocommerce/woocommerce-blocks.

**Comment by apenchev** [comment]
Fair, I've created an issue there: https://github.com/woocommerce/woocommerce-blocks/issues/7759

**Comment by Mamaduka** [comment]
Thank you!
