### ISSUE TITLE
Docs: Rewrite nested blocks documentation with hooks

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#46087]
## What problem does this address?
Currently, the `useInnerBlocksProps` hook is used for blocks with nested blocks, such as group and column blocks. However, the Block Editor Handbook provides examples using `InnerBlocks`.

[Nested Blocks: Using InnerBlocks | Block Editor Handbook | WordPress Developer Resources](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/nested-blocks-inner-blocks/)

As far as I know, the only examples of using hooks are presented in the following article:

[Take more control over Inner Block Areas (as a block developer) – Make WordPress Core](https://make.wordpress.org/core/2021/12/28/take-more-control-over-inner-block-areas-as-a-block-developer/)

## What is your proposed solution?
I believe that it would be better to update the documentation with the implementation using hooks as the standard.

**Comment by gziolo** [comment]
@fabiankaegy authored the dev note mentioned in the description. I would be curious to hear from him whether that was his intent to show that the hook should be preferred over the component. I understand the message as the hook is for advanced usage when devs need to have more control over the markup.

**Comment by fabiankaegy** [comment]
@ellatrix is the real brains behind this feature :) So I would defer any final judgment to them. 

From my perspective, we should update the docs to use the hook-based approach. The benefits you get from using the hooks-based approach are a much cleaner markup and therefore also a much easier time styling your blocks.

Before we can make the switch though I think we also need to update the actual docs for the InnerBlocks component in the Block Editor package. Currently all the options are described as props of the `<InnerBlocks>` component and it isn't very obvious for anyone who isn't super familiar with it how these relate to the hook.

It is a bit of a shift in how you have to think about writing inner block areas. But I much prefer the hook based approach after having used it for a bit. And I am running into way fewer issues than when I used the Component-based approach.

**Comment by t-hamano** [comment]
@fabiankaegy 
Thank you for your input.

I did not update the documentation mentioning InnerBlocks, but only added an example of hook usage to the Nested Blocks documentation in #46407. I would appreciate your opinion on this PR.

**Comment by ellatrix** [comment]
Sure, feel free to update the documentation. In addition, we could check where in the codebase we are still using tho component and maybe deprecated the component.
