### ISSUE TITLE
Navigation block - add 'current-menu-item' to post-type archive links

### ISSUE THREAD

**Issue by Humanify-nl** [WordPress/gutenberg#46090]
The navigation block is in its current state unusable in a professional context. I work with designers, and designers want to mark menus that are active. A fairly straigthforward request that I just can't do with FSE, because post-type archives.

There is still no current navigation solution that works. This tiny small issue with big consequences always seems to be ignored, postponed or shoved back another update. 

Am I the only one who makes websites with this in a real environment with customers and constantly gets frustrated by this? Why is no one bothering about proper menu marking and making sure all standard WP features (i.e. custom post types, archives, etc) are working in the navigation-block? 

https://github.com/WordPress/gutenberg/issues/41597
https://github.com/WordPress/gutenberg/pull/40778 (this is great, but still not for post-type archives)
...

I mean, we added new templates purposed for post-type archives this last update, but who cares, when we can't use them anyway? The menu says nope.

Page + query loop is the only way to work with this and have actual working menu marking.

Very frustrating, how can I help to make this possible?

**Comment by Gierand** [comment]
Are there any plans to work on this soon?
