### ISSUE TITLE
Image remains in page after deleting from Media Library

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4610]
## Issue Overview
After inserting an image, I then clicked the _Edit Image_ icon to change the image. Instead of changing the image, I simply deleted the image from the _Select or Upload Media_ dialog window and then closed the popup.

After returning to the page, the image that I deleted from the Media library, still exists on the page.

This is the page where you can see the image
![gutenberg-imgstillonpage](https://user-images.githubusercontent.com/2078245/35179440-738a9668-fdee-11e7-89cc-2dec4a669889.png)

This is the Media Library where you can see that the (chicken nuggets) image doesn't exist.
![gutenberg-imgdeletedfrommedialibrary](https://user-images.githubusercontent.com/2078245/35179444-8dc49c04-fdee-11e7-9d23-315ef670d4d1.png)

## Steps to Reproduce (for bugs)
1. Insert image block
2. Click the _Edit Image_ icon
3. Delete image from Image Library
4. Close popup window

## Expected Behavior
If the image is deleted from the Media Library, I would expect the image to also be deleted from the page. 

## Current Behavior
Image still remains on page after deleting from Media Library

_Firefox Quantum 57.0.4 (64-bit)
Gutenberg 2.0.0
WordPress 4.9.2
No other plugins activated_

**Comment by karmatosed** [comment]
This happens in core right now, this isn't a Gutenberg bug. I would ask if you can create an issue on core trac please as then it will filter down to Gutenberg.

**Comment by maddisondesigns** [comment]
@karmatosed I've raised this as a WP issue on Trac - https://core.trac.wordpress.org/ticket/43152

**Comment by karmatosed** [comment]
@maddisondesigns thanks for doing that 👍
