### ISSUE TITLE
Content of Select Media window disappeared after uploading image

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4611]
## Issue Overview
I added an image block and after clicking the _Add from Media Library_ button, I simply dragged an image to the _Select or Upload Media_ popup window. The complete contents of this popup window then disappeared.

![gutenberg-imgselectdialogcontentdisappears](https://user-images.githubusercontent.com/2078245/35179483-55bc1cb4-fdef-11e7-82e9-d69ab1c8a42f.png)

## Steps to Reproduce (for bugs)
1. Insert image block
2. Drag image onto _Select or Upload Media_ popup window

## Expected Behavior
I expect the popup window to show the uploaded image, not clear the whole content of its content 

## Current Behaviour
Content in Popup window randomly disappears

_Firefox Quantum 57.0.4 (64-bit)
Gutenberg 2.0.0
WordPress 4.9.2
No other plugins activated_

**Comment by danielbachhuber** [comment]
Thanks for the report, @maddisondesigns. I've been able to replicate with the steps you provided:

![2018-01-23 at 5 22 am](https://user-images.githubusercontent.com/36432/35278085-becb8aa4-fffd-11e7-8e11-c515c35b0844.gif)

Interestingly, the image did end up in the post:

![image](https://user-images.githubusercontent.com/36432/35278105-d2bf6ee0-fffd-11e7-8e5a-712d3e531106.png)

It seems like there's a drag-in-drop zones conflict.

**Comment by jorgefilipecosta** [comment]
Thank you for reporting this problem @maddisondesigns, I think it is fixed by https://github.com/WordPress/gutenberg/pull/5432. If the problem persists feel free to reopen!

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521133917000768)._
