### ISSUE TITLE
List View should have its own scroll bar

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#46123]
### Description

When the List View is long:
you can't see at the same time the block in the list and the block in the editor or the block settings editor. This is produced by the fact that you need to scroll down the page to see the element in the list view and when you do that the block in the editor and the block settings panel get out of the viewport.

Maybe the List view panel should have its own scrollbar.

### Step-by-step reproduction instructions

1. Edit a post with a long list of blocks
2. Observe that you can't see at the same time the block in the list and the block in the editor or the block settings editor.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1310626/204295966-dd1b90ad-7679-4914-aa1e-673e9d7ec38c.mp4

### Environment info

- Gutenberg 14.6.1
- WordPress 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
I am able to reproduce this in WP 6.1.1; Gutenberg 14.6.1; Firefox 105. 

The list view has had its own scroll bar in the past and I remember it being there (see https://github.com/WordPress/gutenberg/issues/40173 as an example issue where it is present); marking as a regression

**Comment by talldan** [comment]
Seems like this one was fixed, so I'll close the issue.
