### ISSUE TITLE
Consider creating a toggle block or a toggle option for headings and paragraphs

### ISSUE THREAD

**Issue by beafialho** [WordPress/gutenberg#46124]
I came across this toggle on Notion, and it made me think it could be a useful tool, particularly for business or commerce websites with FAQ's and a lot of written info. This would improve the designs and reading experience, by expanding only what we select.

https://user-images.githubusercontent.com/65220155/204311962-b23914ce-2b4e-401c-a6b2-92b04b1aace0.mp4

**Comment by Mamaduka** [comment]
A similar block is already in development. See #45055.

Original issue #44539.

**Comment by beafialho** [comment]
Yes that seems very similar indeed. Thanks!

**Comment by Mamaduka** [comment]
@beafialho, should we close this as a duplicate?

**Comment by beafialho** [comment]
Sure!
