### ISSUE TITLE
InspectorControls.ToggleControl onChange callback is passed whole event object as argument

### ISSUE THREAD

**Issue by shramee** [WordPress/gutenberg#4613]
## Issue Overview

ToggleControl of block `InspectorControls` passes event object as parameter to `onChange`. Whereas other InspectorControls controls pass value of the control.

## Steps to Reproduce (for bugs)

1. Add `ToggleControls` and any other control e.g. `RangeControl`
2. Make `onChange` callback console log the argument received.
3. Compare ToggleControl and Range control outputs.

## Expected Behavior

`onChange` callback should be passed `event.target.checked` as argument (Other controls pass `event.target.value`).

## Current Behavior

Whole event object is passed which is not consistent with other controls.

## Possible Solution

Well... Will try to do a PR... Idea is to do an anonymous function that calls `onChange` callback with `checked` property of the event target.

## Screenshots / Video

![image](https://user-images.githubusercontent.com/11048263/35179703-660fdeae-fdc5-11e7-9b1b-32004da28afd.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jordymeow** [comment]
I confirm this issue with Gutenberg 2.1.0.
