### ISSUE TITLE
Browse mode: highlight template or template part when selecting from each section

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46136]
## What problem does this address?

[As part of the FSE Outreach Program's current exploration](https://make.wordpress.org/test/2022/11/13/fse-program-exploration-site-editor-sneak-peek/#comment-2763), the following feedback was shared:

>while editing a template or template part, returning to the Design overview leaves the left-hand menu items un-highlighted. Typically, I would expect the appropriate menu item to be highlighted as having been selected to aid with navigation.

Here's a video to demonstrate the behavior: 

https://user-images.githubusercontent.com/26996883/204415969-6e2988a7-082b-4ed6-a200-54253981b73e.mov

## What is your proposed solution?

Have the Template or Template part be highlighted! cc @youknowriad - I didn't add this to the PR itself as a lot is going on there but wanted to note it for you for now :)

**Comment by t-hamano** [comment]
The latest trunk seems to be able to determine if it is a template or a template part, and the template (part) is also highlighted. Would this be a solution?

![template](https://user-images.githubusercontent.com/54422211/213160674-2a4c0b8e-71bd-4f97-b0f5-408f03753085.png)

**Comment by annezazu** [comment]
Yes! Closing this out.
