### ISSUE TITLE
LinkControl: Page Template links appear inside Link Control

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46149]
## What problem does this address?
When creating a new link inside a template part, an additional "edit" icon is created, to edit the page template:

Steps to replicate:
1. Open the site editor
2. Edit a template part
3. Add a paragraph block
4. Add some text to the block
5. Create a link with that text
6. Deselect and reselect the linked text
7. Notice that the Link Control UI loads and then reloads. On the reload, notice that there are two edit icons, one for the Page Template:
<img width="368" alt="Screenshot 2022-11-29 at 10 51 39" src="https://user-images.githubusercontent.com/275961/204510318-5d78420a-6af6-437c-a871-6c6376e903e1.png">

I'm not sure what the correct solution is here - the page template editing is added via a slot fill [here](https://github.com/WordPress/gutenberg/blob/9a4146f3a64184f904d9631c92d2f134957de318/packages/edit-site/src/components/block-editor/index.js#L199). Should this be using LinkControl for this purpose? Or should the Link UI not be using the LinkControl component?

**Comment by jordesign** [comment]
I can no longer recreate this with the new Link UI (added prior to WP6.3 RC3 which I'm testing) so I'll close this as resolved
