### ISSUE TITLE
Navigation block: list based editing "create new menu" UI is off with page list

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46140]
### Description

With Gutenberg 14.6.1, I'm noticing that the list based editing UI is a bit off centered when there's just the page list fall back. Oddly, when I refreshed the page, I wasn't able to get the "Create new menu" to show up so I'm not sure what's going on exactly. This was done with a brand new test site for context. cc @getdave 

### Step-by-step reproduction instructions

1. Create a brand new test site. In my case, I used https://app.instawp.io/launch?t=fse-exploration- and updated to the latest version of Gutenberg to replicate.
2. Open the Site Editor.
3. Select the navigation block with the block settings sidebar open.

### Screenshots, screen recording, code snippet

<img width="279" alt="Screen Shot 2022-11-28 at 8 39 16 PM" src="https://user-images.githubusercontent.com/26996883/204440438-d884bda4-5f3a-478a-b19c-53d986a75dbb.png">

<img width="679" alt="Screen Shot 2022-11-28 at 8 39 14 PM" src="https://user-images.githubusercontent.com/26996883/204440492-284b3eb9-20c8-46de-b7c0-e6d401175c11.png">

### Environment info

- WordPress 6.1.1
- Gutenberg 14.6.1
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
Thanks for reporting. It's now on the board to be addressed 👍

**Comment by scruffian** [comment]
I think this is fixed.
