### ISSUE TITLE
Navigation Block: Percentage Character (%) in Links Are Improperly Encoded

### ISSUE THREAD

**Issue by kavyagokul** [WordPress/gutenberg#46159]
### Description

Possible related bug : https://github.com/WordPress/gutenberg/issues/32837

When adding a URL with the `%` character in a navigation block link, something is converting the percentage character % to %25, causing the link to go somewhere else and fail.

### Step-by-step reproduction instructions

1. Assign an FSE theme to your site
2. Go to Site Editor and edit the Header template
3. Add a Navigation if there isn't one yet
4. Create a menu item and link it to a url containing the % character ([Example](https://api.payaconnect.com/hostedpaymentpage?id=11eacdb9c9fc0d2c989d2057&data=U2FsdGVkX18xMWVhY2RiOa8xisZ0ulzB%2FzlaRnFN0dWAM1rLyZL%2BQpUc9oo2fp616ICqcykrs%2BjPzDfEPLd%2FZA%3D%3D)

The percentage characters (%) are encoded, causing the link to load incorrectly. This does not occur in regular links within paragraph or list blocks.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/1659416/206651316-e5c56ace-4ac4-4811-af69-84b13e7fb713.png)

### Environment info

WordPress 6.1.1
Gutenberg 14.6.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
Hi @kavyagokul the screenshot you shared isn't opening at the moment and the example link is returning a 403 error. 

However, taking a closer look this reminded me of an issue concerning [non-latin characters not saving properly for templates](https://github.com/WordPress/gutenberg/issues/41214 but I am not ). It might not be related.

**Comment by kozer** [comment]
@danielbachhuber can you assign me to this one? Thanks!

**Comment by kavyagokul** [comment]
> Hi @kavyagokul the screenshot you shared isn't opening at the moment and the example link is returning a 403 error.
> 
Thanks for pointing this out. I've fixed both things in the report above.

@kozer Thank you for picking this up \o/

**Comment by kozer** [comment]
[pr link](https://github.com/WordPress/gutenberg/pull/46435)

**Comment by danielbachhuber** [comment]
Fixed up with https://github.com/WordPress/gutenberg/pull/46435
