### ISSUE TITLE
Import and Export templates, blocks etc....

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#4615]
Import and export of templates, blocks and ......

As more and more blocks will show up in the wild it would be good to have a simple way to import these into Gutenberg without having to install a new plugin for each block one wants to add.

The same goes for templates. Having a simple way to import/export a template. 

It will create a really nice flexibility to be able to import/export specific areas of Gutenberg. 
One could then also create something on a test site like what one has done and then exported and imported into another site. 

There are so many possibilities....

**Comment by StaggerLeee** [comment]
It means they have to reside in database instead of PHP files ?
But OK, not first time.

**Comment by danielbachhuber** [comment]
> As more and more blocks will show up in the wild it would be good to have a simple way to import these into Gutenberg without having to install a new plugin for each block one wants to add.

Can you explain how this would work? I'm not sure I follow. A block without UI is simply HTML, whereas a block with UI requires JavaScript and PHP.

**Comment by paaljoachim** [comment]
Hey StaggerLeee and Daniel

As it gets closer and closer to release of Gutenberg it would be natural that more and more blocks that are not Gutenberg core material will be added as plugins. For instance: https://wordpress.org/plugins/embed-gutenberg-block-google-maps/ could be a plugin that would be interesting to import into Gutenberg.

I can compare it to being able to add a code snippet to the child theme functions file instead of having to add a plugin that could add the same functionality.

**Comment by danielbachhuber** [comment]
Makes sense, thanks @paaljoachim. What action do you propose we take as the result of this issue?

**Comment by paaljoachim** [comment]
Good question. I will take one step back for just a moment first.

The goal:
- Be able to import/export external GutenBerg blocks. Someone has a raw block code or have placed it into a plugin. Similar to sharing code snippets one could then share a block snippet.

Action forward:
- I believe we (devs..:) have to look at how blocks are stored today. Then think about what if I was going to add this cool block that someone created. How can we simplify the process of adding/importing external block code. How should it be stored? Should it be added manually or by somekind of import/export button or both? Is the core blocks code extra protected and external block code as a layer on top? What if core decides to add some of the external block plugins?

There are probably other questions as well.

**Comment by billerickson** [comment]
What's the reason for not adding the block by installing a plugin? Blocks will require JS, CSS and possible PHP to function correctly, and a plugin is the logical location for that code. 

A plugin-based block also has the ability to be updated, while some form of "imported" block (ex: storing the block JS in the database somehow) will be effectively frozen in time, not receiving updates as improvements are made or changes required.

**Comment by mtias** [comment]
Going to close as the mechanism for serving blocks is meant to be the plugin system. There might be improvements we can do as a project there that are more specific for blocks (like browsing).
