### ISSUE TITLE
Add 50% option to "Stack on Mobile"

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#46169]
## What problem does this address?
Currently, you can only choose to either keep ALL columns or stack them. 

## What is your proposed solution?
It would be very useful for designers to have the option to stack columns with a max column width of 50%.  If the "Stack on mobile" is toggled "on" maybe an option to show "mobile column width" with the same options as normal column widths (with just % as an option)?

**Comment by annezazu** [comment]
@bradley2083 thanks for opening this issue! From my vantage point, this directly overlaps with a few different current issues including https://github.com/WordPress/gutenberg/issues/41781 Mind commenting there and closing this out to prevent the convo from being too spread out?
