### ISSUE TITLE
Style variation: Sherbet gradient doesn't properly show up when randomized or at base

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46177]
### Description

This might be two bugs: the Sherbet TT3 style variation "background" color shows as red and, when using the style randomizer, the background color changes but the UI doesn't show it. cc @vcanales 

This was found as part of the FSE Outreach Program's Site Editor Sneak Peek:

>With Sherbet, the background color showed as red in the “Elements” section despite being a gradient

### Step-by-step reproduction instructions

1. Turn on the Style Randomizer experiment in gutenberg > experiments.
2. Head to Appearance > Editor.
3. Open Styles.
4. Change to the Sherbet style variation.
5. Head to the Colors section and use the randomizer.
6. Notice the background shows as red and that it doesn't update when changing.

### Screenshots, screen recording, code snippet

<img width="1484" alt="Screen Shot 2022-11-29 at 1 22 48 PM" src="https://user-images.githubusercontent.com/26996883/204650926-76fcc846-ceff-4494-af64-415178d55575.png">

https://user-images.githubusercontent.com/26996883/204651128-c110cfb9-6ca4-4122-b31a-74ec02a2e540.mov

### Environment info

- WordPress 6.1.1
- GB 14.6.1
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by luminuu** [comment]
Related #43715

**Comment by annezazu** [comment]
Closing this out as style randomization hasn't moved forward.
