### ISSUE TITLE
Produce warning when permalinks are not enabled

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#4617]
## Issue Overview
When permalinks are not set things don't work properly. Gutenberg should be up front about this.

## Steps to Reproduce (for bugs)

1. As for #3215 .
3.
4.

## Expected Behavior
Gutenberg should let the user know that there could be a problem when a permalink structure is not defined. 

## Current Behavior
Unexpected messages in the browser log. Things not working as expected. No warnings that things might not work.

## Possible Solution

Call this logic at the end of `gutenberg_pre_init`
```
/**
 * Verifies permalinks are set
 *
 * @since 2.0.1
 */
function gutenberg_check_permalinks() {

	if ( is_multisite() ) {
		if ( get_blog_option( null, 'permalink_structure' ) ) {	
			return;
		}
	} elseif ( get_option( 'permalink_structure' ) ) {
		return;
	}
	add_action( 'admin_notices', 'gutenberg_permalink_notice' );
}

/**
 * Issues a notice about permalinks
 */
function gutenberg_permalink_notice() {
	echo '<div class="error"><p>';
	echo __( 'Gutenberg works better with permalinks.', 'gutenberg' );
	echo '</p></div>';
}
```
Obviously the wording will need some tweaking. And the logic won't be necessary once WordPress TRAC 42382 has been delivered.

## Related Issues and/or PRs

#3215. Possibly #2704 and #2596. And, to be investigated, problems with reusable blocks.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
@bobbingwide Gutenberg should work without pretty permalinks enabled. What specific issues have you run into?

**Comment by bobbingwide** [comment]
@danielbachhuber regarding permalinks specifically... #3215, which for me was responsible for the problem reported in #3210. 

I also had problems with saved blocks but wasn't able to confirm if this was just a performance issue on my local machine when I had my server tracing enabled. Additionally, I may have inadvertently overridden the registration of the  `wp_block` post type accidentally turning off 'show_in_rest'. 

The point is that anyone who fires up a brand new install to try Gutenberg may start trying to use it without having selected something other than plain permalinks.

**Comment by danielbachhuber** [comment]
Ah, I should've clicked through on #3215 before I created the new issue. #3215 is the appropriate issue to fix.
