### ISSUE TITLE
Can't set font family value for verse blocks via theme.json

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#46181]
### Description

WP 6.1.1 loads the `/wp-includes/css/dist/block-library/style.min.css` file AFTER the styles set in `theme.json`. This file contains the following CSS rule:

```
pre.wp-block-verse {
  font-family: inherit;
  overflow: auto;
  white-space: pre-wrap;
}
```

So, any font family value set in `theme.json` is overridden by this rule. Is this intended?

I'm NOT loading the default theme block styles from core (`add_theme_support( 'wp-block-styles' )`)

### Step-by-step reproduction instructions

1. Set a font-family value for the verse block in the theme.json of your theme.
2. Add a verse block to a page.
3. The block uses the inherited font-family instead of the one set in theme.json.

### Screenshots, screen recording, code snippet

![verse](https://user-images.githubusercontent.com/2060659/204737296-e22adee5-3cd9-48ce-862e-5ca9811b5980.jpg)

### Environment info

- WordPress 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by aaronrobertshaw** [comment]
Thanks for writing up this issue @mrleemon 👍 

I have a potential fix up in https://github.com/WordPress/gutenberg/pull/46560
