### ISSUE TITLE
add ability to convert Ultimate Shortcodes (at least the columns)....

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#4618]
WordPress 4.9.2
Gutenberg 2.0

I just tried Gutenberg on one of my existing sites. Example page: https://www.hometownstructures.com/outdoor-living/pergolas/artisan-wood-pergolas/

When I activate Gutenberg, and "Convert to blocks" on this page, **it is converted to shortcode blocks (entirely).** I've got hundreds of pages with this identical issue: **all content is converted to shortcodes**, often because of column shortcodes.

Like 700,000+ other users, my site is using Shortcodes Ultimate (see https://wordpress.org/plugins/shortcodes-ultimate/).

Is there a way to mitigate this? Can Gutenberg be built to decipher and convert some of the shortcodes from Shortcodes Ultimate, particularly columns?

Of course, you cannot accommodate all shortcode plugins, or even all the shortcodes in this one plugin. But Shortcodes Ultimate has an overwhelming market share compared to its competitors (see https://themeisle.com/blog/wordpress-shortcodes-plugins/), so perhaps it needs some special consideration.

Thoughts?

**Comment by youknowriad** [comment]
Gutenberg offers an API to convert shortcodes if there are compatible blocks (see https://github.com/WordPress/gutenberg/issues/4576). If there's no compatible block, the shortcode will continue to work like previously.

But Gutenberg can't favor a plugin over another even if it's very popular. I think it's better to see with the plugin authors if they have plans on supporting Gutenberg. We can provide the necessary support if needed.

**Comment by billerickson** [comment]
As described above, Gutenberg has the ability to transform existing shortcodes into blocks, but it is up to the plugin author to implement it. The plugin can transform its shortcodes to either a core block or a custom block included in the plugin.

I recommend you reach out the plugin author and encourage him to follow this issue: [Document transformation API when it's finalized](https://github.com/WordPress/gutenberg/issues/4578)

**Comment by carlhancock** [comment]
@youknowriad Is the Gutenberg core team reaching out to the plugin developers that have significant install bases proactively to make them aware of how Gutenberg could impact their plugin and to gently prod them to take the steps necessary to make their plugins play nicely with Gutenberg? 

This is just one example of many, many, many plugins where users are going to be in for a very painful surprise once WordPress 5.0 is released if the plugin developers haven't jumped onboard the Gutenberg train.  

Ultimately it is absolutely up to the plugin developers to do what needs to be done. But with the sheer number of users that could be impacted, it could negatively impact WordPress as a whole from an end user standpoint.

A lot of WordPress users won't even know where to go to, or that the Classic Editor Plugin even exists.  Something all of us in the WordPress development bubble sometimes lose sight of is the majority of the WordPress user base lives outside of the development community bubble, don't browse and participate in the WordPress.org forums, don't attend WordCamp's, etc.  They have no clue what is coming.

For that reason, it would behoove WordPress as a whole to be proactively reaching out to plugin developers about this.  The number of sites and end users who may be impacted is scary.

**Comment by danielbachhuber** [comment]
@carlhancock See #4072 and #4087. We're still gathering data and formulating the plan. Given the Gutenberg APIs aren't yet stable, it's a bit premature to start a massive outreach process. But, it's on the radar (or my radar at least).
