### ISSUE TITLE
Page List: Lock icon in the inspector controls

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46191]
## What problem does this address?
The Page List locking icon has been through a number of different iterations in the list view. Currently it doesn't display any lock icon at all:

<img width="275" alt="Screenshot 2022-11-30 at 11 11 01" src="https://user-images.githubusercontent.com/275961/204781311-45b09151-5c73-4b23-ae45-d3ac7682ea2f.png">

## What is your proposed solution?
As outlined in https://github.com/WordPress/gutenberg/issues/42257 we should consider using a sync icon to communicate the concept that these items are in a controlled state:
<img width="248" alt="Screenshot 2022-11-30 at 11 12 14" src="https://user-images.githubusercontent.com/275961/204781597-01a3166b-ce23-4c90-86b0-f5183ec124bb.png">

**Comment by MaggieCabrera** [comment]
Should we rename the Page list block to Auto-menu too? I think that name makes less sense when we use the block outside the navigation block, which has valid use cases.

**Comment by scruffian** [comment]
We should also consider removing the edit button for the inner blocks.

**Comment by MaggieCabrera** [comment]
> We should also consider removing the edit button for the inner blocks.

We have done that already in https://github.com/WordPress/gutenberg/pull/46163

**Comment by scruffian** [comment]
That's what I thought, but they have come back:

<img width="286" alt="Screenshot 2022-12-09 at 15 49 09" src="https://user-images.githubusercontent.com/275961/206740284-e35ec104-2b95-444b-b18c-223083270ada.png">

Edit: This was actually a bug in https://github.com/WordPress/gutenberg/pull/46416

**Comment by scruffian** [comment]
We updated the icon in https://github.com/WordPress/gutenberg/pull/46438

**Comment by scruffian** [comment]
We should consider using smaller lock icons for when a parent is locked:

![screenshot-2022-12-07-at-10 18 03 copy](https://user-images.githubusercontent.com/275961/206752631-5fc52a15-d9b3-425c-9e54-5f82d75b6ded.jpg)

**Comment by draganescu** [comment]
I can't figure out from the comments what is this issue, a bug or an enhancement?

**Comment by scruffian** [comment]
Enhancement

**Comment by MaggieCabrera** [comment]
[Codepen](https://codepen.io/joen/pen/ZERdqEv) for the solution with the icon
