### ISSUE TITLE
Avoid browser paint in the editor

### ISSUE THREAD

**Issue by corentin-gautier** [WordPress/gutenberg#46199]
### Description

This issue tracks the various PR I have open around avoiding browser paint in the editor as requested by @ciampo in https://github.com/WordPress/gutenberg/pull/45545#pullrequestreview-1198135516:

- #46185
- #46187
- #46188
- #46196
- #46197
- #46201
  - #46465

There are still paint issues that do not have a PR right now, they are related to the fact that the scroll areas are set to `overflow: auto;`, but setting overflow to `scroll` breaks the full site editor. Someone with a deeper knowledge of this area might find the solution.
- #45386
- #23427
- #22822

EDIT : This PR should fix the issue with the scrollbars : 
- #47177

**Comment by ciampo** [comment]
Hey @corentin-gautier , thank you for opening those PRs!

Just wanted to let you know that I won't be around to continue reviewing those PRs in the next weeks, but I've made sure to add other folks as reviewers — so please feel free to ping them in case the reviews go stale without me

**Comment by corentin-gautier** [comment]
Hi @ciampo, I have open a new PR regarding the scroll areas issues :

- #47177

could you take a look at it or assign someone with knowledge of this area ? This would help close this issue 🙂

**Comment by corentin-gautier** [comment]
#46465 was fixed by #48794

**Comment by corentin-gautier** [comment]
Except for #22822 which might need further improvements, I think this issue can be closed @ciampo

**Comment by corentin-gautier** [comment]
I have also open this issue regarding js perfs #47619

**Comment by ciampo** [comment]
Agreed, we can close this issue since it was mostly around paint performance. We can treat input lag and overall bundle size separately.

Thank you for your great work so far!
