### ISSUE TITLE
Navigation: Loading the fallback creates multiple wp_navigation CPTs

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46194]
## What problem does this address?
When a navigation block is in a fallback state, it creates a draft wp_navigation CPT, once a user interacts with it. If this draft is not saved then, next time we load the block we load the fallback again, rather than the draft. This can lead to a situation where a user has multiple draft wp_navigation CPTs in their admin.

## What is your proposed solution?
When the block is in a fallback state, we should delete draft wp_navigation CPTs, and create a new one with the latest fallback data, to avoid creating multiple useless drafts.

**Comment by getdave** [comment]
@scruffian Can we close this one out?

**Comment by scruffian** [comment]
I don't think so no.

**Comment by getdave** [comment]
We have a few solutions in the works. We should be able to fix it if we can get one to land. For example https://github.com/WordPress/gutenberg/pull/48698

**Comment by scruffian** [comment]
This has been fixed.
