### ISSUE TITLE
Nav off-canvas editor not offering the option to create a new page when it doesn't exist

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#46193]
In the Nav block when creating a new link, typing in the name of an entity which doesn't exist brings up a `Create new draft page` option in the Link UI search results. This allows you to create new draft pages directly from the Nav block.

That functionality is not present in the Nav offcanvas experiment.

Why?

It's intentional in the sense that I deliberately removed it. 

Why? 

Because including that functionality requires saveEntityRecord from @wordpress/core-data and we need to avoid coupling that package to block editor. I don't yet have a good way around this...

This is blocked by the above.

-----

        it also looks like the off-canvas editor is not offering the option to create a new page when it doesn't exist. I don't know if that's intended or not. If not, then that's definitely something to follow up on.

_Originally posted by @MaggieCabrera in https://github.com/WordPress/gutenberg/pull/46189#discussion_r1035844767_

**Comment by annezazu** [comment]
Ran into this while creating the next call for testing for the FSE Outreach Program. Would be great to see addressed and have some consistency here!

https://user-images.githubusercontent.com/26996883/232617509-d4b743d9-af5d-4899-b4ec-af218f71f703.mov

**Comment by annezazu** [comment]
Noting that this was brought up in the latest call for testing for the [FSE Outreach Program as a point of inconsistency](https://make.wordpress.org/test/2023/06/07/fse-program-testing-call-24-momery-makeover/#comment-3102):

>When I created a new page by way of creating a draft page. I found that a draft page creation option was missing if I tried to create it under the Menu sidebar https://s.id/1Nh2y. However, it showed up if I tried to add a non-existent page link via the Navigation block https://s.id/1NgZg.

**Comment by getdave** [comment]
I now know exactly how to fix this.

**Comment by getdave** [comment]
This was a bug whereby the functionality was disabled for the Link UI component used in the Nav list view. It's fixed in https://github.com/WordPress/gutenberg/pull/52166.

Noting that this required the work from the 6.3 cycle to allow this to happen.
