### ISSUE TITLE
Post author dropdown missing users when number of users exceeds 100

### ISSUE THREAD

**Issue by tkes** [WordPress/gutenberg#4622]
## Issue Overview

Author dropdown does not show all users.
## Steps to Reproduce (for bugs)

1. WordPress 4.9.2, Gutenberg 2.0.0
2. 120 users
3. Edit post
4. Open author dropdown

## Expected Behavior

List of 120 users

## Current Behavior Gutenberg

List of 100 users

## Current Behavior Classic Editor
List of 120 users

## Possible Solution
Use X-WP-TotalPages and/or X-WP-Total headers in REST API response to get missing users.

**Comment by danielbachhuber** [comment]
@tkes A couple follow-up questions to clarify:

1. Just to confirm, does the WordPress user have access to list all 120 users?
2. How did you verify only 100 users were present? Did you scroll through the entire list?

Thanks!

**Comment by tkes** [comment]
1. User "Sandbox" has administrator role.
2. By looking at list, scrolling through list, looking at releated REST API request.
![alt text](https://i.imgur.com/wRyIYEC.png "The End of the World")

**Comment by spencerfinnell** [comment]
There is a hard limit here: https://github.com/WordPress/gutenberg/blob/master/editor/components/post-author/index.js#L88

**Comment by danielbachhuber** [comment]
@spencerfinnell Correct. `wp/v2/users` has a `per_page` cap of 100 items. We'd either need to:

1. Traverse all pages to load all potential items.
2. Show "common" users by default and permit some search auto-complete to get to the unlisted users.

**Comment by tkes** [comment]
@danielbachhuber The only acceptable solution is 1.

Similar code will be required anyway to fix #4632, #4623 and more issues like missing tag entries, missing custom taxonomy entries, etc.

And the hardcoded `?` in REST API call needs to be fixed as well, it won't work with plain permalinks, as [explained here](https://github.com/bobbingwide/oik/issues/97#issuecomment-359250162) by @bobbingwide

**Comment by tkes** [comment]
@danielbachhuber "Another idea" would fail. If real author is not in initial set of users, saving the post without focusing UI element would still unintentionally change its author.

**Comment by adamsilverstein** [comment]
What about adding a (debounced) search feature here so you could start typing the username and drill down to the correct user?

**Comment by bobbingwide** [comment]
Some other things to note:
- The response can contain many users who couldn't possibly be the Author of the post. e.g. Subscribers. 
- IMO the original request should include a filter to eliminate unwanted results. 
- Also, there's a lot of data that's not going to be used.  
- The final post author select list only uses the ID and display_name fields.

**Comment by StuartFeldt** [comment]
So is the need here to add some sort of pagination/traverse options to withAPIData?

**Comment by robbiet480** [comment]
As an alternative, could the query params include `roles=editor,administrator`?

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1520530478000327)._

**Comment by lkraav** [comment]
2.4.0: I just attempted monkey-patching the query to test for `.level_10` but for some reason still seeing everybody irrelevant.

**Comment by adamsilverstein** [comment]
Pushed a proposed fix that changes the selector into a searchable dropdown in https://github.com/WordPress/gutenberg/pull/5921/.

Worth noting the existing dropdown also has some scalability issues, especially when you get to thousands of users which isn't at all uncommon for WordPress sites. This trac ticket covers the discussion which includes mention of a search picker like the one included on the PR:

https://core.trac.wordpress.org/ticket/19867
