### ISSUE TITLE
Page List allows insertion of any child block

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#46224]
Whilst testing the auto inserted Page List in the Nav block we noticed it's possible to insert any block type within the Page List block itself.

https://user-images.githubusercontent.com/444434/205035551-52933ad6-be8c-4e3d-9a3c-9ef6b29f7970.mp4

Page List should only allow `core/page-list-item`.

**Comment by scruffian** [comment]
There are a few different ways that users can add blocks to the Page List block:
1. I can add page list as a child of page list using the appender
2. I can drag and drop some blocks into the block.

We need to make sure these things are also not possible.
