### ISSUE TITLE
[Inserter]: Basic Openverse integration

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#46222]
Extracted from: https://github.com/WordPress/gutenberg/issues/44496

Now that the new `Media` tab [has been merged](https://github.com/WordPress/gutenberg/pull/44918) it's time to explore a basic Openverse integration. 

We should figure out which kind of media and licenses we'd like to show. I imagine that for the first iteration of this feature we could limit the results to just images that are in the Public Domain or CC0 licensed, but in the future we could explore showing more types of media and giving more fine-grained filtering options.

![image](https://user-images.githubusercontent.com/4933/192736279-4b660206-02b0-4efe-af56-aec60e7f7df8.png)

See the comments for some more explorations on [openverse branding](https://github.com/WordPress/gutenberg/issues/44496#issuecomment-1260607702). 

[Figma file](https://www.figma.com/file/60TSFPxYifPR6NvlrH8AT0/Media-Library-Inserter?node-id=875%3A7319) with the explorations.

Noting that we should also find a good way to handle `mature` content, even if they are not labeled as such. There are some first ideas like excluding some sources and a reporting mechanism. For full context for this, see [here](https://github.com/WordPress/gutenberg/pull/44918#discussion_r994958898).

**Comment by priethor** [comment]
In the context of wrapping [Phase 2](https://github.com/WordPress/gutenberg/issues/33094), this issue has been de-prioritized for after WordPress 6.2
