### ISSUE TITLE
Categories checklist missing entries

### ISSUE THREAD

**Issue by tkes** [WordPress/gutenberg#4623]
## Issue Overview

Categories checklist does not show all categories.

Probably same problem for all hierarchical taxonomies, untested.

## Steps to Reproduce (for bugs)

1. WordPress 4.9.2, Gutenberg 2.0.0
2. 120 categories
3. Edit post
4. Look at categories checklist

## Expected Behavior

List of 120 categories

## Current Behavior Gutenberg

List of 100 categories

## Current Behavior Classic Editor

List of 120 categories

## Possible Solution
Use X-WP-TotalPages and/or X-WP-Total headers in REST API response to get missing entries.

Note: Some sites here have 1000+ categories / subcategories / subsubcategories, only a subset is used but all have to be there to choose from.

**Comment by mtias** [comment]
Closing as duplicate of https://github.com/WordPress/gutenberg/issues/4022

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1520530154000513)._
