### ISSUE TITLE
Notice appearance in Browse view

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#46274]
<img width="1513" alt="Screenshot 2022-12-02 at 11 42 33" src="https://user-images.githubusercontent.com/846565/205285437-850ffe70-3e27-4c15-be9a-afca8426fc25.png">

This looks a bit awkward. Let's think about how to display notices in this view, or perhaps in-canvas notices in general.

**Comment by jasmussen** [comment]
I don't think we should show these in the browse view ever. Browse view is meant to not be an editor, after all. I recognize this can cause an animation jump as you enter the edit mode and the notice appears, but I'd rather have that than notices in both contexts.

**Comment by jameskoster** [comment]
I agree that the notices shouldn't appear _in / attached to the frame_, but we do need to display confirmation of certain actions in browse view.

I just double-checked and template deletion / reversion already shows a snackbar, so we can probably just remove this green  "Template reverted" notice altogether since its duplicative.

**Comment by jasmussen** [comment]
Right, I think snackbars are the answer in browse view.
