### ISSUE TITLE
Webfonts aren't working as expected.

### ISSUE THREAD

**Issue by enodekciw** [WordPress/gutenberg#46289]
### Description

Something wrong is happening with the font-families when Gutenberg plugin is activated.

Webfont is registered in `theme.json` like this:
```
...
"fontFamilies": [
{
  "fontFace": [
    {
      "fontFamily": "DM Sans",
      "fontStretch": "normal",
      "fontStyle": "normal",
      "fontWeight": "400",
      "src": [
      "file:./assets/fonts/dm-sans/DMSans-Regular.woff2"
      ]
    },
  ],
  "fontFamily": "\"DM Sans\", sans-serif",
  "name": "DM Sans",
  "slug": "dm-sans"
},
{
  "fontFamily": "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,\"Helvetica Neue\",sans-serif",
  "name": "System Font",
  "slug": "system-font"
},
]
...
```

Expected behavior:
```
--wp--preset--font-family--dm-sans: "DM Sans", sans-serif;
--wp--preset--font-family--system-font: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
```
top level fontFamily used as a font stack and being able to pick between Default, DM Sans, and System Font in Typography selection.

How it works now:
```
--wp--preset--font-family--dm-sans: 'DM Sans';
--wp--preset--font-family--system-font: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
```
CSS variables for fonts with no fontFace are being generated correctly.
CSS variables for fonts with fontFace get their font stack from fontFamily on that fontFace.
Also, DM Sans is being duplicated in Typography selection, once with '"DM Sans", sans-serif;' as a value and other with 'DM Sans' as a value.

### Step-by-step reproduction instructions

1. Install WordPress 6.1 with TwentyTwentyThree.
2. Install Gutenberg 14.6.1 and activate.
3. Visit frontend to see incorrect css variables being generated.
4. Visit editor to see duplicated font-families.

### Screenshots, screen recording, code snippet

WP6.1 with Twenty Twenty-Three:
```
--wp--preset--font-family--dm-sans: "DM Sans", sans-serif;
--wp--preset--font-family--ibm-plex-mono: 'IBM Plex Mono', monospace;
--wp--preset--font-family--inter: "Inter", sans-serif;
--wp--preset--font-family--system-font: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
--wp--preset--font-family--source-serif-pro: "Source Serif Pro", serif;
```
![image](https://user-images.githubusercontent.com/2080743/205465171-d8e58e1e-8d04-4048-bcc3-951b78df02e9.png)

WP6.1 with Twenty Twenty-Three and Gutenberg 14.6.1:
```
--wp--preset--font-family--dm-sans: 'DM Sans';
--wp--preset--font-family--ibm-plex-mono: 'IBM Plex Mono';
--wp--preset--font-family--inter: Inter;
--wp--preset--font-family--system-font: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
--wp--preset--font-family--source-serif-pro: 'Source Serif Pro';
```
![image](https://user-images.githubusercontent.com/2080743/205465294-b6bf81cf-e629-48d6-908e-59796e21037f.png)

### Environment info

- WordPress 6.1
- Twenty Twenty-Three 1.0
- Gutenberg 14.6.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I was also able to reproduce it, and after activating the Gutenberg plugin, I see the following two problems:

- Duplicate font family names
- Font family not defined in `theme.json` is displayed

| Theme  | gutenberg plugin disabled | gutenberg plugin enabled |
| ---- | ---- | ---- |
| Twenty Twenty Three | ![tt3](https://user-images.githubusercontent.com/54422211/205472668-310d9d4e-1e16-4421-8ba5-d6965382a1c8.png) | ![tt3_gb](https://user-images.githubusercontent.com/54422211/205472783-cbccab7a-6d9a-4b2c-903a-e0c38384c277.png) |
| Twenty Twenty Two | ![tt2](https://user-images.githubusercontent.com/54422211/205472660-9ddddc59-53bb-4490-bca6-3133c99de7fe.png) | ![tt2_gb](https://user-images.githubusercontent.com/54422211/205472782-1805e0e0-79b3-48b3-bb92-64b8936a25a2.png) |

**Comment by enodekciw** [comment]
Had some time to investigate this. I think it was able to fix this in #46292 

@t-hamano I can see also see all of those fonts appearing in the dropdown, too. However I think that's a different issue. Those fonts are not defined in `theme.json`, but they are defined in `styles/blue.json, styles/pink.json, styles/swiss.json`

**Comment by matiasbenedetto** [comment]
I tried to reproduce this issue using the latest Gutenberg trunk version, but I could not. I think that was fixed in the latest trunk version, but we still have a problem related to duplicated fonts when using fallback values in the family name https://github.com/WordPress/gutenberg/issues/46376.

**Comment by enodekciw** [comment]
Yup, font-family stack issue seems to be solved now 👍🏻
