### ISSUE TITLE
Fatal Error: Attempt to assign property "parsed_block" on null 

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#46294]
### Description
- Seems the error was introduced after 4.7.0 RC 1 was compiled (Nov 30) 
### Full error message + stack 

[04-Dec-2022 09:00:53 UTC] PHP Fatal error: Uncaught Error: Attempt to assign property "parsed_block" on null in /wp-includes/class-wp-block.php:239
Stack trace:
#0 /wp-content/plugins/gutenberg/build/block-library/blocks/navigation.php(707): WP_Block->render()
#1 /wp-includes/class-wp-block.php(258): gutenberg_render_block_core_navigation()
#2 /wp-includes/class-wp-block.php(244): WP_Block->render()
#3 /wp-includes/class-wp-block.php(244): WP_Block->render()
#4 /wp-includes/blocks.php(1051): WP_Block->render()
#5 /wp-includes/blocks.php(1089): render_block()
#6 /wp-content/plugins/gutenberg/build/block-library/blocks/template-part.php(131): do_blocks()
#7 /wp-includes/class-wp-block.php(258): gutenberg_render_block_core_template_part()
#8 /wp-includes/blocks.php(1051): WP_Block->render()
#9 /wp-includes/blocks.php(1089): render_block()
#10 /wp-includes/block-template.php(240): do_blocks()
#11 /wp-includes/template-canvas.php(12): get_the_block_template_html()
#12 /wp-includes/template-loader.php(106): include('...')
#13 /wp-blog-header.php(19): require_once('...')
#14 /index.php(17): require('...')
#15 {main}
thrown in /wp-includes/class-wp-block.php on line 239

### Step-by-step reproduction instructions
_Still trying to figure out what exactly goes wrong._ 

What I tried
- Using GB 14.6.1 no error message 
- Using 14.7.0 RC 1 no error message.
- Using WP 6.1.1 + Gutenberg Nightly = error message 

### Environment info
- WordPress 6.2-alpha-54929 
- Version [14.8.20221202](https://gutenbergtimes.com/need-a-zip-from-master/#nightly) (Gutenberg Nightly) 
- PHP 8.0
- Theme: [Geologist](https://wordpress.org/themes/geologist/)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

Header Core containing the navigation 
```

<!-- wp:group {"className":"gapless-group","layout":{"inherit":"true","type":"constrained"}} -->
  <div class="wp-block-group gapless-group"><!-- wp:group {"align":"full","style":{"spacing":{"padding":{"bottom":"var(\u002d\u002dwp\u002d\u002dcustom\u002d\u002dgap\u002d\u002dvertical)","top":"var(\u002d\u002dwp\u002d\u002dcustom\u002d\u002dgap\u002d\u002dvertical)"}}},"className":"site-header site-header-linear","layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center"}} -->
  <div class="wp-block-group alignfull site-header site-header-linear" style="padding-top:var(--wp--custom--gap--vertical);padding-bottom:var(--wp--custom--gap--vertical)"><!-- wp:group {"className":"site-brand","layout":{"type":"flex"}} -->
  <div class="wp-block-group site-brand"><!-- wp:site-logo {"width":64} /-->
  
  <!-- wp:group {"className":"site-words-stack-small","layout":{"type":"constrained","justifyContent":"left"}} -->
  <div class="wp-block-group site-words-stack-small"><!-- wp:site-title {"style":{"typography":{"textTransform":"capitalize"}}} /-->
  
  <!-- wp:site-tagline {"style":{"typography":{"fontSize":"var(\u002d\u002dwp\u002d\u002dcustom\u002d\u002dfont-sizes\u002d\u002dx-small)"}}} /--></div>
  <!-- /wp:group --></div>
  <!-- /wp:group -->
  
  <!-- wp:navigation {"ref":740,"__unstableLocation":"primary","className":"blockbase-responsive-navigation-linear","layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"right","orientation":"horizontal"},"style":{"spacing":{"margin":{"top":"0"}}}} /--></div>
  <!-- /wp:group --></div>
  <!-- /wp:group -->

```

**Comment by bph** [comment]
Might be related to this merged PR #46279 @getdave - I wonder if that is a backwards compatibility issue?

> * Note: 'parse_blocks' includes a null block with '\n\n' as the content when
> * it encounters whitespace. This is not a bug but rather how the parser
> * is designed.

**Comment by getdave** [comment]
Ok I'm looking into this now. Thanks for the ping! 🙇

**Comment by getdave** [comment]
Any chance you could send me the inner blocks of that Navigation Menu with the ID `740`? To do this you can follow [this guide](https://www.youtube.com/watch?v=cSzbouojmhI).

**Comment by bph** [comment]
Here is are the actual menu items. @getdave 

```
<!-- wp:site-logo {"width":32,"style":{"color":{"duotone":["#F5F0E5","#FFFFFF"]}}} /-->	 <!-- wp:site-logo {"width":32,"style":{"color":{"duotone":["#F5F0E5","#FFFFFF"]}}} /-->
 <!-- wp:navigation-link {"label":"Home","type":"custom","url":"https://icodeforapurpose.com/","kind":"custom","isTopLevelLink":true} /-->
 <!-- wp:navigation-submenu {"label":"About Me","type":"page","id":3,"url":"https://icodeforapurpose.com/about/","kind":"post-type","isTopLevelItem":true} --> 
 <!-- wp:navigation-link {"label":"Uses","type":"page","id":68,"url":"https://icodeforapurpose.com/uses/","kind":"post-type","isTopLevelLink":false} /-->	 
 <!-- wp:navigation-link {"label":"Contact","type":"page","id":4,"url":"https://icodeforapurpose.com/contact/","kind":"post-type","isTopLevelLink":false} /-->
 <!-- /wp:navigation-submenu --> <!-- /wp:navigation-submenu -->  
 
 <!-- wp:social-links {"iconColor":"primary","iconColorValue":"#F5F0E5","openInNewTab":true,"className":"is-style-logos-only"} -->
 <ul class="wp-block-social-links has-icon-color is-style-logos-only"><!-- wp:social-link {"url":"https://twitter.com/bph","service":"twitter"} /-->
 <!-- wp:social-link {"url":"https://mastodon.social/@bph","service":"mastodon","rel":"me"} /--></ul>
 <!-- /wp:social-links --> 
```

Could it possibly be that the empty submenu that's causing the error? 
` <!-- /wp:navigation-submenu --> <!-- /wp:navigation-submenu -->  `

**Comment by getdave** [comment]
```
<!-- /wp:navigation-submenu --> <!-- /wp:navigation-submenu -->
```

The later tag is invalid and I guess should not be present. If a standalone block is desired then it should be:

```
<!-- wp:navigation-submenu /-->
```

This matches how HTML works.

Containing 

```
<div>Hello world</div>
```

vs

Self closing

```
<div />
```

Notice the slash has moved to the end.

I don't know how this would have occurred in the block editor unless someone manually edited those blocks 🤔 

Also having created a menu with these inner blocks, I don't see the error you are reporting on the front of the site.

**Comment by bph** [comment]
Oh there might have been some editing hick-ups. 
Here is the screenshot of the menu causing the fatal error. 
![Screen Shot 2022-12-05 at 09 47 07](https://user-images.githubusercontent.com/39980/205666067-0c3d2c17-fc23-445b-9530-33971afb3b96.png)

**Comment by bph** [comment]
And here is the code cleaned up. 
```
<!-- wp:site-logo {"width":32,"style":{"color":{"duotone":
    ["#F5F0E5","#FFFFFF"]}}} /-->	
    
 <!-- wp:navigation-link {"label":"Home","type":"custom","url":"https://icodeforapurpose.com/",
    "kind":"custom","isTopLevelLink":true} /-->
 
<!-- wp:navigation-submenu {"label":"About 
        Me","type":"page","id":3,"url":"https://icodeforapurpose.com/about/",
        "kind":"post-type","isTopLevelItem":true} --> 
    <!-- wp:navigation-link {"label":"Uses","type":"page","id":68,"url":
        "https://icodeforapurpose.com/uses/","kind":"post-type","isTopLevelLink":false} /-->

    <!-- wp:navigation-link {"label":"Contact","type":"page","id":4,
        "url":"https://icodeforapurpose.com/contact/","kind":"post-type","isTopLevelLink":false} /-->
 <!-- /wp:navigation-submenu -->
 
 <!-- wp:social-links {"iconColor":"primary","iconColorValue":"#F5F0E5","openInNewTab":true,
    "className":"is-style-logos-only"} -->
    <ul class="wp-block-social-links has-icon-color is-style-logos-only">
        <!-- wp:social-link {"url":"https://twitter.com/bph","service":"twitter"} /-->
        <!-- wp:social-link {"url":"https://mastodon.social/@bph","service":"mastodon","rel":"me"} /-->
    </ul>
    <!-- /wp:social-links --> 
```

**Comment by scruffian** [comment]
Potential fix here: https://github.com/WordPress/wordpress-develop/pull/3731

**Comment by getdave** [comment]
And here https://github.com/WordPress/gutenberg/pull/46374

**Comment by bph** [comment]
This seems to have been fixed, since Dec 8th, 2022
