### ISSUE TITLE
Site Editor: Remove default dark background

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#46291]
## What problem does this address?
If the Gutenberg plugin is enabled and the theme doesn't explicitly specify a background color for the site, a dark color will be applied to the background, making it difficult to recognize text and blocks.

### Empty Theme with Gutenberg plugin disabled

![wp](https://user-images.githubusercontent.com/54422211/205473024-8997a2a4-87d0-44d7-b3c0-a0c7ebefb168.png)

### Empty Theme with Gutenberg plugin enabled

![gb](https://user-images.githubusercontent.com/54422211/205473022-8e487f37-eefe-495a-95d5-5b97b9078811.png)

## What is your proposed solution?
As in the past, I believe that the background color should not be changed unless the background color is specified on the theme.

**Comment by ntsekouras** [comment]
It's the same result in `zoom-out` view. Should it default to white? 🤔 --cc @jasmussen @jameskoster

**Comment by jasmussen** [comment]
White sounds good 👍
