### ISSUE TITLE
Error creating a new page with editor user and trying to change template

### ISSUE THREAD

**Issue by fabio-blanco** [WordPress/gutenberg#46293]
### Description

While logged in with an editor user, if I try to create a new page and change the template an error occurs in the console and I'm not able to change the template.
The error only happens if the user has editor role. With the admin user everything works as expected.

### Step-by-step reproduction instructions

1. Log in as admin and create a new user
2. Change the new user role to editor and save
3. Log out and login with the new created editor user
4. Go to "Pages" and select "Add New"
5. Open the google chrome console and see the first permission denied error on console
6. On the page configuration panel, click on the template to open the dialog to change it
7. On the template combo box, choose any other template
8. Observe that the change don't reflect on the template and a 403 error is displayed on the console

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/20728836/205474271-e2ffadf6-b55e-40e1-a842-0b202a4a098d.png)
![image](https://user-images.githubusercontent.com/20728836/205474276-34b38620-31a4-40c9-99ae-353b5ea8188d.png)

On the "Add New" page screen:
![image](https://user-images.githubusercontent.com/20728836/205474280-66551e6a-cc21-4fbd-a3c7-006a1f83347f.png)

Opening the change template dialog:
![image](https://user-images.githubusercontent.com/20728836/205474281-276d7b0f-9c87-441d-b81c-76b4a153f0e1.png)

The template don't change and an error is displayed in the console:
![image](https://user-images.githubusercontent.com/20728836/205474285-803678a2-5884-4194-931c-9cd3ebfe1ed0.png)

### Environment info

- **WordPress:** 6.1.1, clean install with no Gutenberg plugin installed
- **Apache:** 2.4.41 - Server build: 2022-06-14T13:30:55
- **PHP:** 7.4.3
- **Browser:** Google Chrome - Version 108.0.5359.71 (Oficial version) 64 bits
- **OS:** Ubuntu Linux - version: 20.04.5 LTS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
So, an `editor` should be allowed to change template but not edit or create a new one? @Mamaduka do you remember?

**Comment by Mamaduka** [comment]
@ntsekouras, that's correct, and this error doesn't prevent correct behavior. That being said, we should avoid making requests when a user has no required permissions.

I will see if we can fix this case later this week.
