### ISSUE TITLE
create-block variant option not working

### ISSUE THREAD

**Issue by robruiz** [WordPress/gutenberg#46295]
### Description

running "npx @wordpress/create-block --variant dynamic" -> returns:
error: unknown option '--variant'

### Step-by-step reproduction instructions

1. In command line, run 
`npx @wordpress/create-block --variant dynamic`
2. see error:  unknown option '--variant'

### Environment info

- WordPress 6.1
- Windows 10
- NPM Version = 8.19.2
- Node Version = 16.15.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I was also able to reproduce it. The problem appears to be a combination of a specific OS and a specific npm version.

- ❌ Windows10, Nodev v16.15.0, npm v8.19.2
- ✅ Windows10, Node v14.21.1, npm v6.14.17
- ✅ Ubuntu (WSL) Node v16.15.0 npm v8.19.2
- ✅ Ubuntu (WSL), Node v14.20.1, npm v6.14.17

My feeling is that the changes made in npm versions 7 and 8 might not be compatible with Windows for some reason.

I will investigate this further.

**Comment by t-hamano** [comment]
After additional investigation, it appears that only the variant option causes errors in Node **v16.15.0**, npm **v8.19.2**, and Windows 11.

Therefore, this may be a problem in the create-block.

- ✅ `npx @wordpress/create-block test --wp-env`
- ✅ `npx @wordpress/create-block test --category text`
- ✅ ` npx @wordpress/create-block test --namespace myname`
- ❌ `npx @wordpress/create-block test --variant dynamic`

**Comment by t-hamano** [comment]
Perhaps this problem occurs when **npm version is 7 or higher**.
I have not yet determined the cause, but this error log may provide a clue.

<details>
<summary>outuput log</summary>

```
0 verbose cli [
0 verbose cli   'C:\\Users\\username\\AppData\\Local\\Volta\\tools\\image\\node\\16.18.1\\node.exe',
0 verbose cli   'C:\\Users\\username\\AppData\\Local\\Volta\\tools\\image\\npm\\7.0.2\\bin\\npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   '@wordpress/create-block',
0 verbose cli   '--variant',
0 verbose cli   'dynamic'
0 verbose cli ]
1 info using npm@7.0.2
2 info using node@v16.18.1
3 timing config:load:defaults Completed in 3ms
4 timing config:load:file:C:\Users\username\AppData\Local\Volta\tools\image\npm\7.0.2\npmrc Completed in 2ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:D:\Desktop\.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\username\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Users\username\AppData\Local\Volta\tools\image\node\16.18.1\etc\npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 13ms
19 verbose npm-session 266a898afde0f5f6
20 timing npm:load Completed in 23ms
21 http fetch GET 200 https://registry.npmjs.org/@wordpress%2fcreate-block 15ms (from cache)
22 timing arborist:ctor Completed in 0ms
23 timing arborist:ctor Completed in 0ms
24 timing arborist:ctor Completed in 0ms
25 timing command:exec Completed in 842ms
26 verbose stack Error: command failed
26 verbose stack     at ChildProcess.<anonymous> (C:\Users\username\AppData\Local\Volta\tools\image\npm\7.0.2\node_modules\@npmcli\promise-spawn\index.js:63:27)
26 verbose stack     at ChildProcess.emit (node:events:513:28)
26 verbose stack     at maybeClose (node:internal/child_process:1100:16)
26 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
27 verbose cwd D:\Desktop
28 verbose Windows_NT 10.0.22621
29 verbose argv "C:\\Users\\username\\AppData\\Local\\Volta\\tools\\image\\node\\16.18.1\\node.exe" "C:\\Users\\username\\AppData\\Local\\Volta\\tools\\image\\npm\\7.0.2\\bin\\npm-cli.js" "exec" "--" "@wordpress/create-block" "--variant" "dynamic"
30 verbose node v16.18.1
31 verbose npm  v7.0.2
32 error code 1
```
</details>

**Comment by robruiz** [comment]
I ran npx clear-npm-cache and tried it again. It worked. Must have been cached on my end in npm? IDK. Sorry for the concern. I didn't even know npx had a cache. Learned something new I suppose.

**Comment by pdewouters** [comment]
This error occurs for me on mac os still.
node 18.12.1
npm 8.19.2

Also with `Now using node v20.0.0 (npm v9.6.4)`

So it's not related to OS/node version
