### ISSUE TITLE
Cover Block (backend) looses "Full width" alignment when turned into a "Reusable block"

### ISSUE THREAD

**Issue by ekesto** [WordPress/gutenberg#46306]
### Description

When converting a Cover Block into a "Reusable block" it visually looses the "Full width" alignment (in the backend). In the frontend it is displayed correctly.

### Step-by-step reproduction instructions

1. Add a "Cover Block"
2. Add a background image/color
3. Set "Align" to "Full width"
4. Select the "Cover Block" and click on "Create a Reusable block"
5. This visually resets the alignment.

### Environment info

- WordPress 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for reporting. There are some existing bug reports (#8288 and #17640), so I'll close this as a duplicate.

**Comment by ekesto** [comment]
Thanks for the feedback, @Mamaduka. What a pity this isn't planned to be implemented.
I think people will want to create, for example, a full width call to action section, and use this across the site.

I'm working on a simple JS/CSS workaround that visually fixes this issue (at least until the block is edited), but would like to improve it.

Do you by chance know of any JavaScript hook/function that is called when the editor blocks have been loaded?
