### ISSUE TITLE
Navigation Submenu: Adding the block doesn't create a navigation submenu block.

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46309]
## What problem does this address?
When I add a navigation submenu block, a navigation submenu doesn't get created:
https://user-images.githubusercontent.com/275961/205664336-bf8c07a4-0016-4372-9567-4b77a39878a9.mp4

## What is your proposed solution?

When you add a navigation submenu item, the block that's added should be a navigation submenu block!

## To reproduce:
1. Add a navigation block
2. Add a block that isn't a navigation link block
3. You will now get a block inserter which offers you a navigation submenu block
4. Add a navigation submenu block
5. Notice that the added block doesn't have a navigation submenu

**Comment by draganescu** [comment]
I think this effect is causing this issue. 

https://github.com/WordPress/gutenberg/blob/4b5037678c99d9ad4f6009238783e489f711b6e8/packages/block-library/src/navigation-submenu/edit.js#L548-L553
