### ISSUE TITLE
Saved blocks list doesn't show all saved blocks (only a maximum of 10)

### ISSUE THREAD

**Issue by tkes** [WordPress/gutenberg#4632]
## Issue Overview
Saved blocks list does not show all saved blocks.

Only currently used in post and max. 10 additional saved blocks are shown.

## Steps to Reproduce (for bugs)
1. WordPress 4.9.2, Gutenberg 2.0.0
2. 25 saved blocks
3. Create new post
4. Add block -> saved blocks

## Expected Behavior
List of 25 saved blocks

## Current Behavior
List of 10 saved blocks

## Possible Solution
Use higher per_page (currently 10) and X-WP-TotalPages and/or X-WP-Total headers in REST API response to get missing entries.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1520530708000753)._

**Comment by danielbachhuber** [comment]
@WordPress/gutenberg-core For this issue, I think we need some design input. I see at least two directions we can head:

1. Introduce infinite scroll to the Saved Blocks list. However, this will run into potential accessibility issues.
2. Include pagination on the Saved Blocks list. I'm not sure if there's prior art we can use.

Opinions? Other ideas?

**Comment by karmatosed** [comment]
I don't like the idea of adding pagination as no other blocks have this. Can't we just show all blocks like we do with the other blocks in the library?

**Comment by danielbachhuber** [comment]
> Can't we just show all blocks like we do with the other blocks in the library?

What if there are 1000 saved blocks? The problem space is similar to the media library. We don't load all attachments at once, but rather fetch them in batches of 40 via an infinite scroll experience.

**Comment by karmatosed** [comment]
> What if there are 1000 saved blocks? The problem space is similar to the media library. We don't load all attachments at once, but rather fetch them in batches of 40 via an infinite scroll experience.

This is a problem of scale the library itself faces over one to solve just for saved blocks. Right now we are working on ways to get around this. I don't agree handling saved blocks differently is a good route. We need a scaling interface approach for all blocks. After all the idea is for previews to happen on all potentially.

**Comment by danielbachhuber** [comment]
> Right now we are working on ways to get around this.

Where is this work happening?

> For now, whilst other ways are being worked on outside this for the entire library we should have them display just as we do in other blocks.

How do you suggest this should work?
