### ISSUE TITLE
Parity with Core's PHP CI jobs

### ISSUE THREAD

**Issue by anton-vlasenko** [WordPress/gutenberg#46339]
## What problem does this address?
There is a discrepancy in how PHP-related CI jobs work in Gutenberg compared to Core.
Gutenberg code should be Core-ready as early in the release process as possible.

## What is your proposed solution?
Any missing Core PHP CI jobs should be added to Gutenberg to ensure that the Gutenberg code is Core-ready.

**Comment by anton-vlasenko** [comment]
I'm working on a patch for this issue.

**Comment by talldan** [comment]
@anton-vlasenko This issue seems like the same topic as https://github.com/WordPress/gutenberg/issues/43333. Is it possible to close one issue in favour of the other?

Thanks for working on it, btw!

**Comment by anton-vlasenko** [comment]
@talldan Thanks for the ping!
My bad, I forgot that https://github.com/WordPress/gutenberg/issues/43333 existed.
I agree that this issue should be closed in favour of https://github.com/WordPress/gutenberg/issues/43333.
But I will continue working on https://github.com/WordPress/gutenberg/issues/43333.

**Comment by anton-vlasenko** [comment]
Or maybe let's rename this issue so that it will become a part of #43333.
