### ISSUE TITLE
Sync offcanvas loading state to Navigation Menu loading state

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#46353]
Currently when you take an action which creates a new Navigation Menu the offcanvas list view itself does not display a loading state. Rather it will immediately display in the inner blocks.

This is disconcerting as the rest of the UI around is all in a loading state.

What should happen is the list view should be "loading" until the Nav Menu has resolved.

## Replication Steps

- Clear all Nav Menus and Classic Menus
- Enable offcanvas experiment
- Add Nav block
- Click page list
- Click `Edit` but don't click the button in the modal YET
- Open dev tools and throttle your network
- Now click the `Customize` button in the modal (be ready to do the next step!)
- Now immediately reselect the Navigation block and view the offcanvas
- See that the inner blocks in the offcanvas are shown but the rest of the UI is still resolving the creation of the Nav Menu

## Screenshots

https://user-images.githubusercontent.com/444434/206156622-2f2ef12f-fb2f-4ec5-804c-78f30d314d4c.mp4

**Comment by scruffian** [comment]
Fixed by #46855

**Comment by scruffian** [comment]
This has been fixed.
