### ISSUE TITLE
Navigation List View: Align the block appender

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46359]
## What problem does this address?
The block appender in the Navigation List View should be aligned with the icons:
<img width="298" alt="Screenshot 2022-12-07 at 12 30 55" src="https://user-images.githubusercontent.com/275961/206180383-863497f5-cf0c-4fb5-9af6-6149ce55e0a6.png">

**Comment by draganescu** [comment]
This looks like the size of the appender should be smaller?

**Comment by scruffian** [comment]
We probably don't want to start having different appenders in different locations.

**Comment by ajlende** [comment]
> This looks like the size of the appender should be smaller?

The icon and the appender are both 24px, so I think it should remain the same.
