### ISSUE TITLE
Inconsistent resizing transitions

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#46354]
The recent introduction of [Browse Mode](https://github.com/WordPress/gutenberg/issues/36667) has resulted in a side-effect related to the resizing transitions. It used to be fast and snappy, but now it feels smooth and slow. This is inconsistent with the post editor. 

I think the transitions work well to enter and exit the Browse Mode, but we shouldn't apply them when you are editing your site or looking at the template preview in Browse Mode.

Here are two videos comparing the transitions:

https://user-images.githubusercontent.com/4933/206156446-c467be8f-4578-48fe-a29b-a507d0760b3b.mov

https://user-images.githubusercontent.com/4933/206155365-580a5db9-3d14-4115-9804-e8b6faf4d77c.mov

**Comment by jasmussen** [comment]
I would tend to agree, it'd be nice to turn off the smooth animation when inside the fullscreen editor.

**Comment by jasmussen** [comment]
This appears to have been fixed!
