### ISSUE TITLE
Navigation: Social Icons block doesn't work in the navigation block

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46371]
## What problem does this address?
Add a social icons block to a navigation block:

This is the editor:
<img width="719" alt="Screenshot 2022-12-07 at 16 21 08" src="https://user-images.githubusercontent.com/275961/206233824-f7aa5cfa-c584-498a-a62f-b0a6496b1dc4.png">

On the frontend it doesn't render:
<img width="827" alt="Screenshot 2022-12-07 at 16 21 12" src="https://user-images.githubusercontent.com/275961/206233893-7ef58b1e-e4c9-48cf-8577-361c3510f60f.png">

**Comment by getdave** [comment]
Please see here for quick fix https://github.com/WordPress/gutenberg/pull/46374
