### ISSUE TITLE
Duplicated font families in global settings

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#46376]
### Description

If a theme registers font families with and without fallback values in the family name the font will be repeated in the font selector dropdowns and in the global settings.

### Step-by-step reproduction instructions

1. Activate Twentytwentythree theme.
This theme defines "DM  Sans" font family name like this in `theme.json`. Pay attention to the fontFamily key ("\"DM Sans\", sans-serif"):
```
"typography": {
    "fontFamilies": [
        {
            "fontFace": [
                {
                    "fontFamily": "DM Sans",
                    "fontStretch": "normal",
                    "fontStyle": "normal",
                    "fontWeight": "400",
                    "src": [
                        "file:./assets/fonts/dm-sans/DMSans-Regular.woff2"
                    ]
                }
            ],
            "fontFamily": "\"DM Sans\", sans-serif",
            "name": "DM Sans",
            "slug": "dm-sans"
        }
    ]
}
```

2.  Add a font like this in `functions.php`:
```
<?php
add_action( 'after_setup_theme', function() {
	wp_register_webfont(
		array(
			'font-family'  => 'DM Sans',
			'font-style'   => 'normal',
			'font-stretch' => 'normal',
			"font-weight" => "900",
			'src'          => get_theme_file_uri( '/assets/fonts/dm_normal_900.ttf' ),
		)
	);
} );
?>
```

### Screenshots, screen recording, code snippet
The font will be repeated in font selection dropdown:
![image](https://user-images.githubusercontent.com/1310626/206514064-3be93df9-4452-4cb8-89ea-a199bb377c2c.png)

### Environment info

- WordPress 6.1.1
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by enodekciw** [comment]
I've also encountered this issue, #46289

**Comment by matiasbenedetto** [comment]
> I've also encountered this issue, #46289

I think it's not exactly the same problem, but the cause seems to be the same. A potential fix: https://github.com/WordPress/gutenberg/pull/46378
