### ISSUE TITLE
Button component default class

### ISSUE THREAD

**Issue by schlessera** [WordPress/gutenberg#4638]
## Issue Overview

The `<Button>` component does not contain the default `button` class when it is not specified to be "Primary" or "Large".

This causes a generic `<Button>` component to not be displayed like a button at all, but rather like a link.

## Steps to Reproduce (for bugs)

`<Button className="some-button">` will render as a standard link.

To produce a button that actually looks like one, without making it large or primary, you need to use something like this:

`<Button className="some-button button">` will render as a standard link.

## Expected Behavior

I'd expect the `<Button>` component to render as a button by default.

## Current Behavior

The `<Button>` component renders as a link by default.

## Possible Solution

Make sure the `button` class is added by default, and provide a specific method of disabling this behavior, like an `isLink` property.

**Comment by danielbachhuber** [comment]
Included in #3418, for the next person looking.

**Comment by jorgefilipecosta** [comment]
Hi @schlessera thank for creating this detailed issue.

Rendering a button with button class by default causes many UI implications:

![image](https://user-images.githubusercontent.com/11271197/39014100-45a5652a-4411-11e8-88df-6283d90e940f.png)

I think the button component when no "style prop" is passed is more of semantic than style nature. It represents a button but it is up the component user to style it.
Adding a default button class would be other option, but I fear now the change may not be worth trouble as adding the class by default would create lots of issues and would break back compatibility for external developers using the button without the prop.

**Comment by jorgefilipecosta** [comment]
I will close this issue for now if someone has new inputs to add, feel free to reopen the issue so we can discuss further!
