### ISSUE TITLE
@wordpress/eslint-plugin: upgrade eslint-plugin-jsdoc

### ISSUE THREAD

**Issue by scheinercc** [WordPress/gutenberg#46386]
Trying to install `node_modules` in a project which has the current `@wordpress/eslint-plugin` installed leads to the following error:

```
error eslint-plugin-jsdoc@37.9.7: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^16 || ^17". Got "19.2.0"
```

Since Node LTS has moved to v18, maybe `eslint-plugin-jsdoc` could be updated to support 18 and 19.

https://github.com/WordPress/gutenberg/blob/181b383719e8d1cde0c3e99ce7c9a76e3b13ec4b/packages/eslint-plugin/package.json#L43

**Comment by gregsullivan** [comment]
It looks like this is in progress here:

https://github.com/WordPress/gutenberg/pull/46107

Could there be a way to configure `eslint-plugin-jsdoc` that would prevent the need for the code changes in the above pull request?

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/45696. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
