### ISSUE TITLE
Style book: Hide inline block preview when style book is invoked

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#46394]
## What problem does this address?

Inline block preview is redundant when 'Style book' is open.

<img width="926" alt="image" src="https://user-images.githubusercontent.com/1935113/206391174-16840117-d446-4af8-8929-9810f95ea03d.png">

## What is your proposed solution?

Would it be nice to hide the inline preview when `style book` is open?

**Comment by noisysocks** [comment]
Good idea. Should be easy to do using the useHasStyleBook hook.

**Comment by mtias** [comment]
How would this handle mobile? Also it might seem a bit weird to have the preview just vanish upon opening the style book.

**Comment by madhusudhand** [comment]
>How would this handle mobile?

I think the style book toggle `eye` is not available for the smaller screens. Only inline preview is available.

> Also it might seem a bit weird to have the preview just vanish upon opening the style book.

Hmm. We could leave it as is and revisit in future if required.
