### ISSUE TITLE
Style book: Back navigation in styles panel always navigating to history

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#46393]
### Description

The back navigation click in global styles is not navigating to previous menu, instead it always navigates based on the route history.

### Step-by-step reproduction instructions

1. Invoke `style book` by clicking on eye icon
2. Click on few blocks from the `style book`
3. Exit style book (by clicking on eye icon)
4. Now on click of back link in global styles takes us to all previously clicked block styles instead of previous menu.

### Screenshots, screen recording, code snippet

![style-book](https://user-images.githubusercontent.com/1935113/206389471-3a607abd-1ac3-4145-9274-4958b3a1077b.gif)

### Environment info

- Latest Gutenberg
- Latest WordPress

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/pull/46391 fixes this.
