### ISSUE TITLE
Mention security issue reporting process in README.md and ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#4641]
Given the high-profile nature of the Gutenberg project, we should be up-front about the security issue reporting process in both the README.md and ISSUE_TEMPLATE.

**Comment by ntwb** [comment]
Via #4652 
• https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md#reporting-security
• https://github.com/WordPress/gutenberg/blob/master/SECURITY.md
