### ISSUE TITLE
Navigation & Page List: Page List block can't live inside a submenu

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46413]
## What problem does this address?
It is currently impossible to add a Page List block to a Navigation submenu:

https://user-images.githubusercontent.com/275961/206525733-28a7e340-325a-42f5-8248-be78f433a7b2.mp4

## What is your proposed solution?
It should be possible to add Page List to a navigation submenu block.

**Comment by draganescu** [comment]
Some issues I have for now:
- decide if we’re willing to give up direct insert or find some new UX or only insert page list from the inserter (not discoverable and weird)
- fix page list to know how to render in a submenu too (it checks now if parent is navigation I think)
