### ISSUE TITLE
Can't insert HTML into Rich Text via a format type

### ISSUE THREAD

**Issue by tcmulder** [WordPress/gutenberg#46411]
### Description

The docs and [comment block](https://github.com/WordPress/gutenberg/blob/trunk/packages/rich-text/src/insert.js) for packates/rich-text/src/insert.js say it inserts "an HTML string" into a Rich Text block. However, I'm only able to insert plain text.

If it's not possible to insert HTML, that's cool, but that part should be removed from the comment block (or it should be reworded if it's trying to convey something else). If it is possible though, the way to accomplish that should be documented.

(Note that it may be possible to do what I'm wanting to do via the `insertObject` function by creating a block containing the HTML, but the comment in `insert` still confuses me if this is the case.)

### Step-by-step reproduction instructions

1. Use the code below to create a new format type.
2. Within Gutenberg, attempt to add the new format type into a paragraph block.
3. You'll see `&lt;i&gt;heart&lt;/i&gt;` text gets inserted, rather than a `<i>heart</i>` HTML element.

### Screenshots, screen recording, code snippet

```JavaScript
const { __ } = wp.i18n;
const { registerFormatType, insert } = wp.richText;
const { RichTextToolbarButton } = wp.blockEditor;
const { useSelect } = wp.data;

function ConditionalButton({ isActive, onChange, value }) {
	const selectedBlock = useSelect((select) => {
		return select('core/block-editor').getSelectedBlock();
	}, []);

	return (
		<RichTextToolbarButton
			icon="editor-code"
			title="Heart"
			onClick={() => {
				onChange(
					insert(value, '<i>heart</i>')
				);
			}}
			isActive={isActive}
		/>
	);
}

registerFormatType('example/heart', {
	name: 'example/heart',
	title: __('Heart', 'aquamin'),
	object: true,
	tagName: 'img',
	className: 'heart',
	edit: ConditionalButton,
});
```

### Environment info

- WordPress 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I think `insert` only handles plain text values automatically. For HTML, you'll need to [create](https://github.com/WordPress/gutenberg/blob/trunk/packages/rich-text/src/create.js) and pass value.

Try something like this:

```js
const valueToInsert = create( { html: `<i>heart</i>` } );
insert( value, valueToInsert )
```

**Comment by tcmulder** [comment]
That indeed did the trick—thanks!
