### ISSUE TITLE
Navigation: Block inserter challenges

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46425]
By default the navigation block uses a Link UI to insert blocks:
<img width="539" alt="Screenshot 2022-12-09 at 10 40 52" src="https://user-images.githubusercontent.com/275961/206684147-7c635e9c-baaf-401e-b47c-587f2c03af66.png">

This is because in the majority of cases users will want to add links to their navigation, rather than other blocks. We also provide several transforms to popular blocks: "search", "social icons" and "site logo". If a user adds one of these blocks then on subsequent interactions the block inserter changes to look like this:

<img width="492" alt="Screenshot 2022-12-09 at 10 47 47" src="https://user-images.githubusercontent.com/275961/206685457-22239cc4-5f1f-486b-8f16-98231c9218b7.png">

Now that the Page List block can be configured to display only the child pages of a selected parent, we anticipate that users will also want to add this block to their navigation, which is currently not possible.

In https://github.com/WordPress/gutenberg/issues/42257 @SaxonF suggests a new interface for adding blocks to a navigation:
<img width="375" alt="Screenshot 2022-12-09 at 10 46 20" src="https://user-images.githubusercontent.com/275961/206685187-ee3fccac-a705-4e6c-b16e-a2c3c2afcdcf.png">

This raises several questions:

1. Should this new block inserter be the new default for all blocks added to the navigation block?
1a. If no then should we make it easier to add a Page List block using the initial inserter (the Link UI)?
1b. If yes then does this mean we no longer expect the majority use case to simply be adding custom links?
2. Does the search field on this inserter search for posts and pages or blocks, or both?

**Comment by getdave** [comment]
@scruffian I think this has all been addressed right?

**Comment by scruffian** [comment]
We have a way forward here. Closing.
