### ISSUE TITLE
Add Block: Webmentions Reply

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#4643]
Talked about this briefly with @dshanske. Putting it on my to-do list to design.

**Comment by dshanske** [comment]
https://indieweb.org/reply#Post_a_reply - It is just a matter of marking up a link with the class u-in-reply-to. Webmentions reads microformats 2 classes for context.

**Comment by melchoyce** [comment]
Two ideas:

## Make it a block

![image](https://user-images.githubusercontent.com/2846578/70832882-3cdaf700-1dc4-11ea-9d44-18591766db74.png)

Offer a placeholder that allows you to link to an external website, and then do an embed of whatever is being linked using their OG data.

Or — should this be an advanced setting on every link?

![image](https://user-images.githubusercontent.com/2846578/70832925-5d0ab600-1dc4-11ea-82f5-f4927b129ea0.png)

What do you think, @dshanske?

**Comment by dshanske** [comment]
Well, reply is one of many relationships a link could have. I would say that it is probably a block

**Comment by melchoyce** [comment]
Cool. Can you elaborate a bit on that?

**Comment by jasmussen** [comment]
Any movement on this one? It might be good plugin territory?

**Comment by ellatrix** [comment]
What does it do? Not sure I understand. :)

**Comment by dshanske** [comment]
If your site and the one you are linking to supports webmentions, it would read the markup and display your reply on their site as a comment.

**Comment by paaljoachim** [comment]
https://webmention.net/

"Webmention is a simple way to notify any URL when you link to it from your site."

**Comment by mtias** [comment]
There hasn't been much attention on this one, seems it's better explored through plugins for now. Should be easier with some of the recent tools, like the HTML API.
