### ISSUE TITLE
Cover block should be able to link to current post

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#46449]
1. ## What problem does this address?

Currently, the cover block has an option to use the current featured image. This is great because it enables you to use it in a query loop. By the same token it would be very nice if there was an option to turn the entire cover image into a link to the post. That way the user can click the image and go to the post that the featured image is associated with. Currently you'd have to put the post title  or post date on top of the cover block to create a link to the post. That's not bad, but on small mobile devices, it would be very helpful if the entire image could be tapped to go to the post. 

## What is your proposed solution?

The cover block should have a switch called "Link To Post," which can be set only if the option to link to the Featured Image is selected. If the "Link To Post" is turned on, the entire cover image is linked to the post that the featured image corresponds to.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/42252. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
