### ISSUE TITLE
Non-numeric value encountered cron.php

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#46447]
### Description

Not sure if this should be logged in core wp or not but it only occurs (randomly) with Gutenberg installed.  

I get the following error:
Warning: A non-numeric value encountered in ... /wp-includes/cron.php on line 847

Again, happens at random but I've seen with just the default 2023 theme and Gutenberg only.
 
I'm using Local to dev these sites where I've seen the issue.

### Step-by-step reproduction instructions

I don't have steps to reproduce as it does not happen consistently.

### Screenshots, screen recording, code snippet
<img width="1344" alt="Screen Shot 2022-12-09 at 4 18 38 PM" src="https://user-images.githubusercontent.com/1781226/206811270-986127ff-e7d7-45ae-adf3-0ffff4a81380.png">

### Environment info

-  wp 6.1.1
- gutenberg 14.4.0
- chrome
- macos 12.3.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I am still not sure what is causing this problem, but this is probably where the error is occurring:
https://github.com/WordPress/wordpress-develop/blob/7005e6ddbc246d9dfc2f07e676ce1ccf1a1dddb7/src/wp-includes/cron.php#L847

If an error occurs here, it is possible that the string is defined in `WP_CRON_LOCK_TIMEOUT`.

For example, have you defined constants with strings as follows?

- ❌`define( 'WP_CRON_LOCK_TIMEOUT', '60' );`
- ✅`define( 'WP_CRON_LOCK_TIMEOUT', 60 );`

**Comment by Mamaduka** [comment]
Hi, @bradley2083

Can you confirm that your local dev site doesn't have `WP_CRON_LOCK_TIMEOUT` defined as a string?

**Comment by bradhogan** [comment]
@Mamaduka would this be defined in wp-config.php?  If so, it is not defined.

**Comment by t-hamano** [comment]
Constants are generally defined in `wp-config.php`, but they can also be written in themes or plugins.

By the way, as far as I know, the Gutenberg plugin doesn't  have any settings related to cron, so it is a bit odd that this problem occurs.

If you output logs at the points I have indicated in [this comment](https://github.com/WordPress/gutenberg/issues/46447#issuecomment-1364621874), you may find some clues.

```php
// Record each variable and check which one is non-numeric value.
error_log( '$lock:' . $lock );
error_log( 'WP_CRON_LOCK_TIMEOUT:' . WP_CRON_LOCK_TIMEOUT );
error_log( '$gmt_time:' . $gmt_time );

// Don't run if another process is currently running it or more than once every 60 sec.
if ( $lock + WP_CRON_LOCK_TIMEOUT > $gmt_time ) {
	return false;
}
```

**Comment by priethor** [comment]
Let's close this issue, as it needs more info to be actionable. Please feel free to reopen again if there is more information. 🙏
