### ISSUE TITLE
Reusable Block icon discrepancy 

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#46441]
<img width="1111" alt="Screenshot 2022-12-09 at 17 25 03" src="https://user-images.githubusercontent.com/846565/206758422-350e6536-5f55-462b-a4bd-5f2580123825.png">

The Inserter tab, block toolbar, and Inspector all use the same icon (`symbol`), but the buttons in the Inserter use the `group` icon. They should probably be consistent?

**Comment by mtias** [comment]
The icon in the inserter is showing whatever the outer block is; i.e. if the reusable block is a single paragraph it shows a paragraph.

**Comment by richtabor** [comment]
We should consider if these should be BlockPreview driven anyhow.

**Comment by mtias** [comment]
We used to have previews but were disabled due to performance issues. If I recall correctly it predated async loading, so might be time to revisit.

**Comment by jameskoster** [comment]
This one tripped me up again today. It seems quite likely that Reusable Blocks will often be wrapped in containers, and seeing a mixture of Row, Stack, Group icons doesn't seem super helpful. 

I'd place more value in presenting each with the same icon regardless, but if the current behaviour is preferred I'm happy to close this.

cc @WordPress/gutenberg-design for feedback.

**Comment by jasmussen** [comment]
I think the main issue here is if you have 10 or 20 reusable blocks in the RB tab, having the same icon for all of those will be useless. 

What if we showed the RB generic icon in block toolbar, inspector, list view, but showed the outer wrapper icon only in the inserter? Otherwise I'd actually be tempted to go the other route: show the outer wrapper icon _everywhere_ and repurpose the two diamond icons for templates and template parts respectively. What do you think?

Related: #35453

**Comment by jameskoster** [comment]
> I think the main issue here is if you have 10 or 20 reusable blocks in the RB tab, having the same icon for all of those will be useless.

Now that you mention it, how useful are those icons in general? They seem significantly less helpful than the name / preview, which makes me wonder whether we should present reusable blocks the same way we present patterns:

<img width="298" alt="Screenshot 2023-03-31 at 16 05 35" src="https://user-images.githubusercontent.com/846565/229158344-6a1dca82-357b-4a60-ac9a-8480a8e1a776.png">

I guess we'll explore that in more detail as a part of https://github.com/WordPress/gutenberg/issues/48458. 

So in the mean time I'd vote establishing consistency between what you see in the Inserter, and what you see everywhere else. No strong feeling as to whether that means using the container block icon like you suggest, or the reusable block icon.

**Comment by jameskoster** [comment]
Reusable blocks now appear in the Patterns tab, so I think this can be closed.
