### ISSUE TITLE
Add keyboard shortcuts for formatting text blocks, such as Headings

### ISSUE THREAD

**Issue by bozzmedia** [WordPress/gutenberg#46444]
## What problem does this address?

A missing feature of Gutenberg compared to Classic is the lack of certain critical keyboard shortcuts. One series of keyboard shortcuts that are missing are H1 - H6 formatting. 

In Classic Editor, the keyboard shortcuts are:

Heading 1: Control + 1 (PC) or Command + 1 (Mac)
Heading 2: Control + 2 (PC) or Command + 2 (Mac)
Heading 3: Control + 3 (PC) or Command + 3 (Mac)
Heading 4: Control + 4 (PC) or Command + 4 (Mac)
Heading 5: Control + 5 (PC) or Command + 5 (Mac)
Heading 6: Control + 6 (PC) or Command + 6 (Mac)

Markdown is great when you're typing in the editor, however when formatting many blocks of text it is impractical, as is using a mouse to convert each block.

## What is your proposed solution?
Add critical keyboard shortcuts to gutenberg to achieve parity with the previous editor. With one keyboard shortcut a user should be able to convert or format a text block to be H1-H6 headings. There are probably other missing shortcuts that would be similarly useful.

wp.org thread: https://wordpress.org/support/topic/keyboard-shortcut-to-convert-block-ex-paragraph-to-heading/

**Comment by Saoming** [comment]
I want to do this.

**Comment by mtias** [comment]
This was added in #44681.

**Comment by bozzmedia** [comment]
That's great to hear! Looking forward to having this ability added to core wp soon.
