### ISSUE TITLE
Provide Method to Resize Site Logo Block

### ISSUE THREAD

**Issue by masperber** [WordPress/gutenberg#46451]
## What problem does this address?
Currently, there are no block settings which allow resizing a Site Logo Block. Users may commonly wish to resize their site logo.

[The WordPress.org documentation for the Site Logo Block](https://wordpress.org/support/article/site-logo-block/) claims that there are resize handles, but they do not appear in the Site Editor.

Tested themes: Twenty Twenty Three, Tsubaki,

## What is your proposed solution?
Add resize handles and/or block settings that allow resizing a Site Logo Block. Block settings should allow sizing in px, rem, em, %, vw, etc.

**Comment by khristiansnyder** [comment]
+ 1. Seems like this should be a standard option and have ran into this issue today.

**Comment by masperber** [comment]
This appears to be a bug with the WordPress.com Gutenberg plugin. Closing in favor of https://github.com/Automattic/wp-calypso/issues/71089
