### ISSUE TITLE
Navigation: Open list view tab when clicking list view button

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46462]
## What problem does this address?
The "open list view" button in the navigation block opens the inspector controls, but it doesn't focus the list view tab:
<img width="369" alt="Screenshot 2022-12-12 at 10 33 18" src="https://user-images.githubusercontent.com/275961/207023709-a629ecd7-6bf0-4925-aede-a75e78209d1f.png">

## What is your proposed solution?
We should make sure the "List view" tab is focussed when the "list view" button is clicked

**Comment by draganescu** [comment]
This somehow works for me. Even if I open another tab and close the inspector when I click the list view button I get the correct tab opened. On `trunk`.

**Comment by scruffian** [comment]
This was fixed by https://github.com/WordPress/gutenberg/pull/46335
