### ISSUE TITLE
Page List: When converting to Navigation Links respect the selected parent page

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46469]
## What problem does this address?

If I have Page List block inside a navigation menu, when converting a Page List block to a list of static navigation items, we don't respect the filter for the parent page. So if I have a page list like this:
<img width="289" alt="Screenshot 2022-12-12 at 17 18 29" src="https://user-images.githubusercontent.com/275961/207111215-fd5a7ada-1430-4fb8-84c2-ca4d3d50b484.png">

When I convert it, using this button:

<img width="288" alt="Screenshot 2022-12-12 at 17 18 34" src="https://user-images.githubusercontent.com/275961/207111145-9b99b144-d01a-4d1f-aef7-334689fa38d6.png">

<img width="281" alt="Screenshot 2022-12-12 at 17 19 09" src="https://user-images.githubusercontent.com/275961/207111026-83ff22d5-bc48-4d89-8070-4ff84427f19f.png">

## What is your proposed solution?
We should only convert the pages that are shown by the filter.

**Comment by getdave** [comment]
We'll need to pass the correct pages to the conversion function. I believe the conversion function actually re-fetches the page data rather than use the data from the block edit so we'll need to refactor that in _both_ locations in code.

**Comment by scruffian** [comment]
This was fixed by https://github.com/WordPress/gutenberg/pull/47651
