### ISSUE TITLE
Navigation block: unable to add a top level item at bottom of the new editable list view 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46479]
### Description

When using the new editable list view for an upcoming call for testing for the FSE Outreach Program, I noticed that I cannot drag and drop an item to be a top level item at the bottom of the list view. 

### Step-by-step reproduction instructions

1. Enable the editable list view for navigation block in Gutenberg > Experiments.
2. Head to Appearance > Editor (beta).
3. Select the navigation block and open up block settings.
4. Add a few items to the navigation block.
5. Add some sub menu items to the last item in the navigation menu.
6. Try to drag a sub menu item out and place it as a top menu item at the very bottom.
7. Notice that you can't :D 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/207135810-dedff252-689d-4381-9037-53ddc3c82108.mov

### Environment info

- WP 6.1.1
- GB 14.7
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I think it's the same issue as https://github.com/WordPress/gutenberg/issues/33678.

**Comment by annezazu** [comment]
Ah ha. you are correct. Closing out!
