### ISSUE TITLE
Navigation block: new editable list view undo doesn't work after using the option to create a new menu

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46476]
### Description

When using the new editable list view for an upcoming call for testing for the FSE Outreach Program, I noticed that after selecting the "create new menu" option, it won't allow me to undo and get back to my prior navigation menu that I selected. I could see this being jarring and confusing for users who might be just exploring the block and not yet have clarity around how to move between the different options.

### Step-by-step reproduction instructions

1. Enable the editable list view for navigation block in Gutenberg > Experiments.
2. Head to Appearance > Editor (beta).
3. Select the navigation block and open up block settings.
4. Use the three dot menu to "create a new menu".
5. Notice new menu is created. Try to hit redo to go back to prior option. Notice nothing happens.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/207131597-515fba1d-d358-44fa-95ba-f2a000e7db18.mov

### Environment info

- WP 6.1.1
- GB 14.7
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
The undo options continue to be really strange with this view. It's inconsistent to say the least with GB 14.8.4:

https://user-images.githubusercontent.com/26996883/211108988-0802393d-364a-4ba1-b1f0-e3e573ff0416.mov

cc @scruffian

**Comment by annezazu** [comment]
Noting that this also came up in the [FSE Outreach Program's nineteenth call for testing ](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2840)(the same one I was writing when I found this issue):

>I cycled through some different menus in the dropdown, and then tried “UNDO”ing those changes, but Undo wasn’t able to undo my menu selections.

**Comment by draganescu** [comment]
Undo problems:

- [x] #47683 
- [x] #47633 
- [ ] #47694 - seems to be a much bigger problem outside of the scope of this issue

**Comment by draganescu** [comment]
I think we can close this issue considering the last item is not about the navigation block.
