### ISSUE TITLE
gutenberg as a pluggable solution

### ISSUE THREAD

**Issue by gEndelf** [WordPress/gutenberg#4648]
gutenberg really impressed and I think a lot of teams working on other platforms/languages also will want to integrate **gutenberg** solution for content editing

Do you planning to create such pluggable solution?

**Comment by danielbachhuber** [comment]
> Do you planning to create such pluggable solution?

No plans at this point! It certainly would be interesting to see Gutenberg in front of Drupal, Django, etc. I think such a framework would need to implement a WP REST API equivalent JSON API though.

Let us know if you ever try it out!
