### ISSUE TITLE
@wordpress/e2e-test-utils-playwright is not published to NPM

### ISSUE THREAD

**Issue by yotamselementor** [WordPress/gutenberg#46481]
### Description

The README file for e2e-test-utils-playwright specifies the following installation instructions:
`npm install @wordpress/e2e-test-utils-playwright --save-dev`

However, there is no NPM package called `@wordpress/e2e-test-utils-playwright`

### Step-by-step reproduction instructions

1. Run `npm install @wordpress/e2e-test-utils-playwright --save-dev`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thank you for your report.

I think `@wordpress/e2e-test-utils-playwright` [is not currently explicitly published to npm](https://github.com/WordPress/gutenberg/blob/a7dcc68b3b0831b115faadf177f1d8eba5412a6c/packages/e2e-test-utils-playwright/package.json#L4) and this is not a bug. According to [this article](https://make.wordpress.org/core/2022/03/23/migrating-wordpress-e2e-tests-to-playwright/), this package seems to be released after all Gutenberg E2E testing is migrated to Playwright.

As such, I will label this issue as an improvement to the developer documentation.

**Comment by talldan** [comment]
There's some discussion about this in this PR - https://github.com/WordPress/gutenberg/pull/43998

**Comment by ndiego** [comment]
> There's some discussion about this in this PR - https://github.com/WordPress/gutenberg/pull/43998

This issue was reviewed in today's Editor Docs Scrub. As mentioned in the linked PR above, `@wordpress/e2e-test-utils-playwright` has been "prereleased" and the README has been updated. It's now available [here](https://www.npmjs.com/package/@wordpress/e2e-test-utils-playwright), therefore I am going to close out this issue.
