### ISSUE TITLE
How to remove global css "padding" from body?

### ISSUE THREAD

**Issue by cb911nr** [WordPress/gutenberg#46482]
Since the latest Gutenberg, there's inline CSS that's being added for body

`body {
    padding-top: 0px;
    padding-right: 0px;
    padding-bottom: 0px;
    padding-left: 0px;
};`

Been searching, and trying to figure out how to remove this, it's overwriting our theme CSS file since the global inline css comes after the theme's CSS file.

**Comment by kathrynwp** [comment]
Hi @cb911nr - could you please check Styles > Layout:

<img width="1503" alt="Editor__beta__‹_Self-hosted_Test_—_WordPress" src="https://user-images.githubusercontent.com/7662449/207159273-597cf34d-edee-4649-9af1-d0710cd08c75.png">

There are padding settings there that you can reset to their defaults.

p.s. if you need further help with this, could you please go ahead make a post over in the Gutenberg support forum, including a link to your site, so folks can assist more. Thanks!

https://wordpress.org/support/plugin/gutenberg/

**Comment by cb911nr** [comment]
Unfortunately there is nothing like that since this is affecting all pages/posts/etc... there's inline css adding

body { padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; };

With the rest of the global inline css

**Comment by kathrynwp** [comment]
Heya @cb911nr - could you please go ahead and make a post in the support forum as I mentioned above. Folks will be glad to take a direct look at your site and help you troubleshoot further over there. Thanks!
