### ISSUE TITLE
Global Styles: Reset to defaults action is not working

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#46484]
### Description

In `trunk`, within global styles, the `Reset to defaults` action appears not to be working. From running a `git bisect`, it appears that the change that introduced the regression was https://github.com/WordPress/gutenberg/pull/44770 (the PR that introduced the new browse mode).

Kudos @tellthemachines for flagging the issue!

### Step-by-step reproduction instructions

On `trunk`, open up global styles in a site that has user styles, and attempt to reset the global styles back to the theme defaults. As of #44770, it appears that the drop-down control to reset to defaults no longer works.

For a commit that still works (e.g. prior to #44770) you can checkout 51f0b7766095479a801f8fe451b056a30ca9e778, or really any prior to #44770.

### Screenshots, screen recording, code snippet

| `trunk` | when it was working previously |
| --- | --- |
| ![2022-12-13 10 38 51](https://user-images.githubusercontent.com/14988353/207183817-c468ee24-9ada-40a0-98df-739c31dac3f2.gif) | ![2022-12-13 10 37 24](https://user-images.githubusercontent.com/14988353/207183632-2ffc55c6-abfd-4297-919d-e2bf1d1dedd8.gif) |

### Environment info

- WP 6.1.1
- Gutenberg `trunk`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Pinging a few folks who worked on #44770 and/or reviewed: @youknowriad, @ntsekouras, @scruffian for visibility.

**Comment by ramonjd** [comment]
Looks like it's because `<SidebarComplementaryAreaFills />` has been placed [outside the global context provider](https://github.com/WordPress/gutenberg/pull/44770/files#diff-53f39da7a5f1f996f5359a2dd7b2747fb3d60a494523dd73dba946fab8e82592R177)

**Comment by andrewserong** [comment]
We have a fix open in: https://github.com/WordPress/gutenberg/pull/46486
