### ISSUE TITLE
UI: Add Dark Mode to Gutenberg UI

### ISSUE THREAD

**Issue by Jumaron** [WordPress/gutenberg#46491]
## What problem does this address?

First, i'am a big Dark-Mode fan, Discord, Github, Youtube are all in Dark-mode.
Working with Gutenberg is burning my Eyes.

## What is your proposed solution?

Add a toggleable Dark-Mode for the Gutenberg UI, the people will love it - including me- it is one of the features Gutenberg is lacking.
And i'am sure a lot of people would Switch from Elementor (where Dark Mode UI is available).

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/9483. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
