### ISSUE TITLE
Disable duplicate Travis builds

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#4650]
Travis is currently building both PRs and branches:

![image](https://user-images.githubusercontent.com/36432/35305807-bd8c8fa6-004f-11e8-9bb2-1c814d6c8746.png)

Because each open source project has a limited number of Travis jobs, it's wasteful to have duplicate builds. We should instead build each PR only once.

**Comment by danielbachhuber** [comment]
![image](https://user-images.githubusercontent.com/36432/35306456-ad116450-0052-11e8-8f7f-c9de1d2e48cb.png)

**Comment by ntwb** [comment]
FYI: The WordPress GitHub org has 15 simultaneous Travis jobs, thanks for the support Travis CI ❤️ 

We still shouldn't be wasteful of these resources and running two builds per PR is wasteful

**Comment by aduth** [comment]
Is a rebuild triggered when pushing new commits to a pull request?

**Comment by danielbachhuber** [comment]
> Is a rebuild triggered when pushing new commits to a pull request?

Yes
