### ISSUE TITLE
Comments block: Styles in the frontend doesn't work for the legacy version

### ISSUE THREAD

**Issue by DAreRodz** [WordPress/gutenberg#46516]
### Description

Styles for the legacy version of the Comments block are not present in the frontend, even though the stylesheet is being [explicitly enqueued](https://github.com/WordPress/gutenberg/blob/cfc881afcbb56beb1d1dade911180e04a4bf4936/packages/block-library/src/comments/index.php#L84) while the block is being rendered.

This could be happening because the [`register_legacy_post_comments_block`](https://github.com/WordPress/gutenberg/blob/cfc881afcbb56beb1d1dade911180e04a4bf4936/packages/block-library/src/comments/index.php#L142-L219) function [depends on](https://github.com/WordPress/gutenberg/blob/cfc881afcbb56beb1d1dade911180e04a4bf4936/packages/block-library/src/comments/index.php#L210-L216) a hook callback ([`_wp_multiple_block_styles`](https://developer.wordpress.org/reference/functions/_wp_multiple_block_styles/)) that is deprecated since 6.1, which was required for registering the different styles before enqueueing them.

### Step-by-step reproduction instructions

1. Install a theme using the old Post Comments block (e.g., [TT1 Blocks](https://wordpress.org/themes/tt1-blocks/))
2. Visit any post
3. Check that no styles are applied to the Post Comments block apart from the default ones.

### Screenshots, screen recording, code snippet

| How it looks | How it should look |
| --- | --- |
| ![Screenshot 2022-12-13 at 20 46 50](https://user-images.githubusercontent.com/6917969/207430473-643f758a-3d43-4fd5-9dac-c2fcc5e17679.png) | ![Screenshot 2022-12-13 at 20 49 35](https://user-images.githubusercontent.com/6917969/207430525-3ab9f97c-44c5-45a3-9633-96189ee58fd6.png) |

### Environment info

- WordPress: 6.2-alpha-54963
- Gutenberg: current trunk (6a54882a9b0814e424897dc2e334986c3bcc887e)
- Theme: [TT1 Blocks 0.4.8](https://wordpress.org/themes/tt1-blocks/)
- Browser:  Google Chrome 108.0.5359.98 (Official Build) (arm64)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. I was able to confirm, so removing the Needs Testing label. 

![image](https://user-images.githubusercontent.com/4832319/208696791-c4d83d80-9567-490c-aa77-206abd6979ad.png)

**Comment by jordesign** [comment]
Closing this issue as the Legacy Comments block has been deprecated.
