### ISSUE TITLE
[Block] Site Logo - Missing Image width block settings when Gutenberg 14.7.1 is active

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#46518]
### Description

The **Site Logo** block used in FSE themes has an IMAGE WIDTH slider in it's block settings, as noted here: https://wordpress.org/support/article/site-logo-block/#block-settings

This IMAGE WIDTH setting is visible on a WordPress.org site with no plugins active. But when **Gutenberg 14.7.1** is active on the site, the IMAGE WIDTH is gone, and the available WIDTH setting in it's place offers different tools for constraining the image, which don't seem to work.

### Step-by-step reproduction instructions

1. Activate a Full Site Editing theme such as Twenty Twenty Two
2. Deactivate all plugins
3. Open the Site Editor
4. Select Site Logo (or add one) and use Block settings to adjust width
5. Next, activate Gutenberg 14.7.1
6. Return to Site Editor and try adjusting the Site Logo > Block settings again - the tools are now different.

### Screenshots, screen recording, code snippet

All plugins deactivated, theme Twenty Twenty Two:

![Markup on 2022-12-13 at 16:49:33](https://user-images.githubusercontent.com/27249804/207470868-072dc9e0-1a11-4689-bdf0-d76178ef9899.png)

Gutenberg 14.7.1 only Activated

![Markup on 2022-12-13 at 16:50:09](https://user-images.githubusercontent.com/27249804/207470921-9ab30a68-92f7-4fe1-bfc4-7fb66adfd101.png)

Behavior of the new width settings:

https://user-images.githubusercontent.com/27249804/207470957-547c0d30-6ee3-4217-8483-2d78086a2c08.mov

### Environment info

- WordPress 6.1.1
- Gutenberg Version 14.7.1
- Theme Twenty Twenty-Two version 1.3

Also reported here: https://github.com/Automattic/wp-calypso/issues/71089

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
The issue was fixed via #46214 and should be part of the Gutenberg 14.8 release. Initial report #46198.
