### ISSUE TITLE
Terminal log outputs wrong IP address

### ISSUE THREAD

**Issue by siaimes** [WordPress/gutenberg#46548]
### Description

When wordpress work behand nginx proxy. I can make Activity Log plugin log the real IP by install Real IP Detector plugin.

![image](https://user-images.githubusercontent.com/34199488/207645034-6f78719f-16c3-4b5a-b8b3-c6e9e2342bf6.png)

This means that the wordpress server can obtain the IP address of the real client.

However, the wordpress container's log is the address of the proxy server.
![image](https://user-images.githubusercontent.com/34199488/207644808-3960c4b2-4018-48e8-bc58-7fb45ea25504.png)

So how to make the container log also output the correct IP address?

### Step-by-step reproduction instructions

1. install wordpress behand nginx proxy.
2. see the container log.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Hi @siaimes - this repo is only for the block editor (code-name Gutenberg) – is your issue in any way related to the block editor? If not, could you please submit your report over in Core Trac, where the WordPress project is managed? Thanks!

https://core.trac.wordpress.org/

**Comment by siaimes** [comment]
Sorry, I made a mistake and posted it in the wrong place.
