### ISSUE TITLE
Shared featured blocks and allowed blocks config across sub blocks of Nav block

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#46540]
All blocks which can be sub blocks of Nav block seem to shared

- allowedBlocks
- featured blocks (see below)

Let's create a canonical const and shared that between all blocks.

-----
Let's shared this across all these blocks as a standard piece of config

_Originally posted by @getdave in https://github.com/WordPress/gutenberg/pull/46426#discussion_r1048494957_

**Comment by scruffian** [comment]
I'm not sure we can do this, featured blocks and allowed blocks are different lists containing different items.

**Comment by getdave** [comment]
I think perhaps I meant x2 `const`s? I was advocating for drying up these constants. They may no longer exist 🤷

**Comment by scruffian** [comment]
Closing this for now.
