### ISSUE TITLE
Embeds don't render when loaded from pattern content

### ISSUE THREAD

**Issue by ryelle** [WordPress/gutenberg#46556]
### Description

When a pattern is loaded in a template using the `core/pattern` block, embeds in the pattern are not rendered.

### Step-by-step reproduction instructions

1. Add a pattern file to emptytheme (or your active theme), ex `patterns/youtube-example.php`
2. In the pattern, add an embed block
3. Add the pattern to an HTML template (not through the Site Editor), ex `templates/index.html`
4. Load the page - the embed URL is there, but no embed

<img width="625" alt="Screenshot 2022-12-14 at 3 28 23 PM" src="https://user-images.githubusercontent.com/541093/207707139-9e87c155-c009-4e7b-a243-06a61d329c83.png">

### Screenshots, screen recording, code snippet

You can test it with this pattern, which is just a single embed block.

```
<?php
/**
 * Title: YouTube Example
 * Slug: example/youtube-pattern
 */

?>

<!-- wp:embed {"url":"https://youtu.be/y_6cEoFFcdc","type":"video","providerNameSlug":"youtube","responsive":true,"className":"wp-embed-aspect-4-3 wp-has-aspect-ratio"} -->
<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-4-3 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://youtu.be/y_6cEoFFcdc
</div></figure>
<!-- /wp:embed -->
```

Add it to a template file with `<!-- wp:pattern {"slug":"example/youtube-pattern"} /-->`

### Environment info

- WP 6.1.1
- GB 14.7.3
- Mac, Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hz-tyfoon** [comment]
I've encountered this same issue today.
My environment is: `WP 6.2.2` & `Gutenberg 15.8.1`

Noting: This issue doesn't occur if some changes are made from `site-editor/editor` and then the `save/update` button is pressed (& saved into the database).

**Comment by dsas** [comment]
It looks like the embed block itself doesn't generate the embed HTML. Instead the template-part block [runs this code](https://github.com/WordPress/gutenberg/blob/dded3a7571d71467248bb184ffbcaddd643c3522/packages/block-library/src/template-part/index.php#L151) which generates it. The [pattern block](https://github.com/WordPress/gutenberg/blob/dded3a7571d71467248bb184ffbcaddd643c3522/packages/block-library/src/pattern/index.php#L29) has no analogous code.

I'm not sure why the embed HTML generation code isn't part of the embed block itself, but perhaps a quick win is just update the pattern render_callback to add:

```
global $wp_embed;
$content = $wp_embed->autoembed( $content );
```

**Comment by dsas** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/55979
