### ISSUE TITLE
Navigation block: Add option to remove all preset frontend functionality

### ISSUE THREAD

**Issue by eric-michel** [WordPress/gutenberg#46552]
## What problem does this address?
The navigation block does a great job letting you add nav menus anywhere on the site. However, it's extremely opinionated in how those menus will appear and function (submenus are always hidden and set to absolute positioning, for example).

Menus can appear in a multitude of ways across sites, from main menus at the top of the site (which often function the way this block does), to flyout menus with accordion-style submenus, to mega menus, to side menus for site sections, to a thousand other types that I'm not mentioning.

## What is your proposed solution?
It's not realistic to expect this block to offer every type of menu format, but it would be really nice to have an option to turn off all styling and functionality and just output a simple unordered list like `wp_nav_menu` does so that the theme can apply its own styling and functionality when needed. This would allow for the excellent menu building features included in this block to be usable for many types of menus.

**Comment by carolinan** [comment]
You can already remove all the CSS for the navigation block by dequeueing the navigation, navigation link and optionally the page list and home link block styles.

But to do that for only one copy of the block you would need to use a different method and identify the block for example by adding a custom CSS class, and remove the styles conditionally.
You can use the `render_block` filter to change the block markup on the front, but not the editor.

Remember that if you remove the CSS and don't replace it correctly, the block settings will stop working.

**Comment by eric-michel** [comment]
@carolinan thanks for the tips! I will definitely experiment with conditionally removing styles for specific navigation blocks. 

From a user perspective, it would be really nice if the other styling for the nav block (justification, orientation, colors, spacing, etc) was still available - it's just the opinionated functionality (hidden submenus that appear either on hover or click) I'd like to be able to turn off, similar to the way you can turn off the functionality of converting the menu to an overlay on mobile.

If there were a toggle in the `Display` settings for the block that simply allowed you to turn off that functionality, it could make the rest of that section disappear (again, similar to the `Off` option for `Overlay Menu`). This would make the block far more flexible for users who just want a menu in a sidebar, column, or footer and don't need it to hide submenus (but rather simply output a list of tiered links in a normal `ul` format).
![image](https://user-images.githubusercontent.com/45110062/208944771-054255c1-41dc-43b5-8ec5-17639f5820a2.png)

If I could also set option to default to `off` in `theme.json` that would allow me to also created block styles that our users can use to output different versions of the menu block to accomplish different tasks (including dropdown menus).
