### ISSUE TITLE
Sanitize  block attr

### ISSUE THREAD

**Issue by sharazghouri** [WordPress/gutenberg#4656]
## Issue Overview

I make js block where user add js code  in save function <script>  user input </script>   working very well .
I want to sanitize user input before saving function run or insert into the database. i find one hook "blocks.getSaveContent.extraProps" in js  need same like hook in php where i run esc_js function and sanitize  block data.
![image](https://user-images.githubusercontent.com/17900945/35323530-a158b65a-010f-11e8-8b91-d3588578c0fb.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Current Behavior

![js block](https://user-images.githubusercontent.com/17900945/35323488-786c1462-010f-11e8-9e11-a80e2ec3a82b.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
I think WordPress already sanitize the post content when necessary, if you want to add extra validation, you should probably do it server-side.

Client-side you can just add your validation in the `onChange` handler before calling `setAttributes`
