### ISSUE TITLE
components-popover covers content

### ISSUE THREAD

**Issue by field2** [WordPress/gutenberg#46584]
## What problem does this address?

On desktop, the components popover overlaps into the previous block, covering text and making it difficult to read what was just typed in the last paragraph, for example.

## What is your proposed solution?

Align the components popover to the left if there is enough whitespace to accomodate.

Currently covers the text in the previous paragraph:
<img width="1229" alt="Screen Shot 2022-12-15 at 9 12 49 AM" src="https://user-images.githubusercontent.com/1656980/207885645-e0c9413a-7e6d-4767-8f3f-1f124e80db90.png">

Aligns to the left of the current paragraph:
<img width="868" alt="Screen Shot 2022-12-15 at 9 13 59 AM" src="https://user-images.githubusercontent.com/1656980/207885642-ecdffeda-007f-4f75-9061-1e9bc6a20ede.png">

**Comment by talldan** [comment]
@field2 There is an option in the block editor called 'Top toolbar' that might be useful for you.

I'm not sure it'd be possible to put the toolbar to the left of the block. What if there isn't space to the left of the paragraph?

**Comment by talldan** [comment]
I'll close the issue as I don't think the suggestion is feasible. Thanks for reaching out though.
