### ISSUE TITLE
No color option for selected text within a Paragraph block

### ISSUE THREAD

**Issue by drussogit** [WordPress/gutenberg#46592]
### Description

My test account on WordPress.com (https://testx15.wordpress.com/) uses the Kubrick theme and no plugins except the defaults. If I select text within a Paragraph block, there is no color option in the More menu or on the right panel.

NOTE: All of my privately-hosted WordPress sites have the issue. 

I reported a similar issue before, as described here:
https://github.com/WordPress/gutenberg/issues/39106

But that thread was closed on the assumption that the Advanced Editor plugin was causing the problem. But my test account on WordPress.com (https://testx15.wordpress.com/) does not have the Advanced Editor plugin or any active plugin. 

### Step-by-step reproduction instructions

1. Select text within a Paragraph block in a WordPress post or page with the Block editor enabled. 
2. There is no color option in the More menu or on the right panel.

### Screenshots, screen recording, code snippet

My test account on WordPress.com (https://testx15.wordpress.com/) uses the Kubrick theme and no plugins except the defaults. 

### Environment info

My test account on WordPress.com (https://testx15.wordpress.com/) uses the Kubrick theme and no active plugins that I know of. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Hi @drussogit - please could you reach out to WordPress.com support for help with this issue.

This particular github repository is for the open source version of WordPress.

Here's a link to WordPress.com support - https://wordpress.com/support/

**Comment by drussogit** [comment]
Daniel, this issue is not limited to the WordPress.com version. Should I
add more detail about m my open source WordPress sites as well? They have
the same problem.

**Comment by talldan** [comment]
If you can share some more steps for reproduction that'd be great.

I tested both block and non-block based themes (including 'Kubrick 2' in the theme directory) and they still have the highlight option:
![Screen Shot 2022-12-16 at 10 40 00 am](https://user-images.githubusercontent.com/677833/208009572-20b2446f-5b16-46c3-8b71-faa987775861.png)

If you can share which WordPress/Gutenberg version you're using that would be helpful too.

**Comment by drussogit** [comment]
My mistake. 

I did not realize that the Highlight option includes color options for both selected text (which is what I wanted) and the background for selected text (which is not what I wanted.
