### ISSUE TITLE
Add clear Submit and Cancel buttons to Link UI

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#46593]
Currently there a number of problems in the Link UI which result from a lack of clarity about when a user intends to "submit" changes to a given link.

A classic example is the "Open in new tab" toggle. Should toggling this close the UI and update the link? Or should it merely toggle the switch and wait for you to re-submit the entire link.

It would be a lot clearer and unambiguous if we simply introduced `Submit` and `Cancel` buttons. Here's a nice example of Evernote:

<img width="475" alt="Screen Shot 2022-12-15 at 21 23 46 (1)" src="https://user-images.githubusercontent.com/444434/207970474-c8030bbe-b6bb-4ec7-8332-caf2a5ab5127.png">

By adding these we can remove an entire class of bugs whilst at the same time making the UX a lot clearer for users.

**Comment by getdave** [comment]
Note: the dual submit/cancel buttons should probably only be present once the initial link has been created and the user has hit "Edit".

**Comment by jasmussen** [comment]
Just noting that there's a fair bit of good design feedback on the PR in question, so removing the label from here: #46933
