### ISSUE TITLE
Styles view: Large image overflows page container

### ISSUE THREAD

**Issue by mikachan** [WordPress/gutenberg#46612]
### Description

When an image block is inserted and the image width is forced to be larger than the available space, the image will overflow the page container in the Styles view. The image is cut off to fit the available space on the front end, without overflowing.

For example, if an image block is inserted with the image width set at 2000px, the image will overflow this space in the Styles view / zoomed-out editor view.

### Step-by-step reproduction instructions

1. Insert an Image block with an image, and set the image width to be very large (e.g. 2000px)
2. In the editor, go to Styles > Browse Styles
3. You should see the image overflow the page container

Example markup with only image block:

```
<!-- wp:image {"width":2000,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="image.jpg" alt="" width="2000"/></figure>
<!-- /wp:image -->
```

Example markup with columns block and image block:

```
<!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","bottom":"0px"},"padding":{"top":"0px","bottom":"0px"}},"elements":{"link":{"color":{"text":"var:preset|color|background"}}}},"backgroundColor":"foreground","textColor":"background","layout":{"inherit":true,"type":"constrained"}} -->
<div class="wp-block-group has-background-color has-foreground-background-color has-text-color has-background has-link-color" style="margin-top:0px;margin-bottom:0px;padding-top:0px;padding-bottom:0px"><!-- wp:columns {"align":"full","style":{"spacing":{"blockGap":"0px"}}} -->
<div class="wp-block-columns alignfull"><!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"bottom","width":"calc(1240px / 2)","style":{"spacing":{"padding":{"left":"var(\u002d\u002dwp\u002d\u002dcustom\u002d\u002dgap\u002d\u002dhorizontal)"}}}} -->
<div class="wp-block-column is-vertically-aligned-bottom" style="padding-left:var(--wp--custom--gap--horizontal);flex-basis:calc(1240px / 2)"></div>
<!-- /wp:column -->

<!-- wp:column {"width":"50%"} -->
<div class="wp-block-column" style="flex-basis:50%"><!-- wp:image {"width":1000,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full is-resized"><img src="image.jpg" alt="" width="1000"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->
```

### Screenshots, screen recording, code snippet

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/1645628/208087905-76f4adc5-b249-42b5-9af1-4da46af21716.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I was able to replicate this. In messing around a bit, something like this CSS might solve the issue. 

```
.block-editor-block-list__block.has-block-overlay .block-editor-block-list__block.wp-block-image {
    overflow: hidden;
}
```

**Comment by ndiego** [comment]
I just retested this in trunk, and the issue appears to be fixed. @mikachan, when you have a chance, can you retest and confirm? Thanks!

![image](https://user-images.githubusercontent.com/4832319/216322707-32d5e945-5e29-4446-8005-af4b222515a9.png)

**Comment by mikachan** [comment]
Yes, this also seems to be fixed when I test this in trunk too. Thanks! I'll close this issue.
