### ISSUE TITLE
Page List: "Customize this menu" change

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46613]
## What problem does this address?
The page list block contains this panel:
<img width="302" alt="Screenshot 2022-12-16 at 12 12 36" src="https://user-images.githubusercontent.com/275961/208095619-7b2e93a6-6810-4a9d-82ca-73200e562b31.png">

There are a few things about this that might need reconsidering:
1. Should it be a panel? There’s no huge value in being able to collapse this thing, it could just be a heading.
2. Is “Customize this menu” the right phrasing? It’s just a list of pages, it’s not a menu yet, and if we’re going to use the page list inside submenus, it might need different phrasing.

**Comment by carolinan** [comment]
I think we can describe better what it actually does, which is convert it to link items (and submenu if there are child pages) in the navigation block.

**Comment by SaxonF** [comment]
Once #47064 is in place I'd argue this panel either isn't needed or should be moved to advanced as we can just infer the "customise/convert to link items" intent from any interaction of the list. We also have the existing "edit" action in the toolbar and in future could add more "transform to" options like list.

**Comment by scruffian** [comment]
Let's move the panel lower in the inspector controls for now and revisit later.

**Comment by scruffian** [comment]
This is already captured in https://github.com/WordPress/gutenberg/issues/47236
