### ISSUE TITLE
Page List: Add children automatically

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46614]
## What problem does this address?
When I add a Page to a navigation block, the child pages for that page are not added to the navigation automatically. If I want these children I have to manually add a Page List block and set the parent to the Page I selected.

## What is your proposed solution?
If you are adding a top-level menu item that has subpages, insert those subpages as a Page List.

**Comment by carolinan** [comment]
I don't think we can assume that showing all subpages in the navigation should be the default. Are there any support requests, feature requests or other types of stats that shows what end users expect?

**Comment by scruffian** [comment]
Yeah I think this is definitely questionable. On the one hand, if you want this behaviour it would feel like magic and be very satisfying, on the other hand if you don't want it, it would be annoying to have to remove it every time. cc @jasmussen who suggested it to me.

**Comment by carolinan** [comment]
And I don't think we can compare with classic menus because it is not a smooth experience to add subpages in the old Menus screen either, there is no automation at all for subpages (child pages, grand child pages etc).

**Comment by jasmussen** [comment]
It's a basic idea, and could come with a modal question: "This top level page has n subpages, want to add them"? The motivation is: when you _do_ want to add subpages, it's very likely you not only want them to stay in sync with other subpages you create, but it's likely you want the whole tree. What do you think?

**Comment by scruffian** [comment]
I think it would be a good question to ask when adding a page with subpages.

**Comment by draganescu** [comment]
We should be able (I think @mtias also mentioned this) to convert a link that is a page to a page list that is already set to show that links children including itself. This is new and also differs from how parent selection works in the page list block. Now the page list block does _not_ show the parent itself.

**Comment by ClarusDignus** [comment]
> I don't think we can assume that showing all subpages in the navigation should be the default. Are there any support requests, feature requests or other types of stats that shows what end users expect?

Does the [popular plugin of the same name](https://wordpress.org/plugins/page-list/) speak to this in any way? It allows list depth configuration.

> depth – how many levels in the hierarchy of pages are to be included in the list: [pagelist depth="3"]; by default depth is unlimited (depth=”0″); Displays pages at any depth and arranges them in a flat list: [pagelist depth="-1"];

Though the plugin is shortcode-based rather than block-based, the concept is the same. For the Page List Block, the default depth could be top-level only.

Related: https://github.com/WordPress/gutenberg/issues/48149

**Comment by scruffian** [comment]
Another approach is this:

If you add a submenu to a navigation link which is a Page, then the submenu should automatically contain all the children for that page.

**Comment by scruffian** [comment]
This is the same as https://github.com/WordPress/gutenberg/issues/42598. Closing.
