### ISSUE TITLE
Youtube block - pasting link clearing existing classes 

### ISSUE THREAD

**Issue by tomektomczuk** [WordPress/gutenberg#46627]
### Description

When you add any class to the Youtube block that has already embedded url the class is not save after page refresh.

### Step-by-step reproduction instructions

1. Add Youtube block
2. Add any class and save page - the class is now saved.
3. Open page click the block and paste any YT url -> https://www.youtube.com/watch?v=MFj_S0Nof90&list=RDCMUCFbNIlppjAuEX4znoulh0Cw&start_radio=1
4. Now your class is overwritten by "wp-embed-aspect-16-9 wp-has-aspect-ratio"

### Screenshots, screen recording, code snippet

https://www.loom.com/share/f03c97bb875342caa3019dbd83709a8b

### Environment info

newest version of Wordpress

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@tomektomczuk

Thanks for the report.
I believe it is the same issue as #45540.
