### ISSUE TITLE
wp-env with xdebug fails due to mismatching PHP version

### ISSUE THREAD

**Issue by PooSham** [WordPress/gutenberg#46635]
### Description

[Xdebug recently released version 3.2.0, which drops support for PHP 7.2, 7.3 and 7.4.](https://pecl.php.net/package/xdebug/3.2.0) `wp-env start` seems to take the latest stable version of xdebug from pecl, which causes problems when using PHP <8. Wordpress only has beta support for PHP 8.x, so I don't want to update my plugin to use that yet. 

```
$ wp-env start --xdebug
✖ Error while running docker-compose command.
Sending build context to Docker daemon  421.5MB
Step 1/7 : FROM wordpress:php7.4
 ---> 1730fea0ae8e
Step 2/7 : RUN apt-get -qy install $PHPIZE_DEPS && touch /usr/local/etc/php/php.ini
 ---> Using cache
 ---> ee0742886da6
Step 3/7 : RUN if [ -z "$(pecl list | grep xdebug)" ] ; then pecl install xdebug ; fi
 ---> Running in abab7ff4328a
pecl/xdebug requires PHP (version >= 8.0.0, version <= 8.2.99), installed version is 7.4.33
No valid packages found
install failed
Building wordpress
The command '/bin/sh -c if [ -z "$(pecl list | grep xdebug)" ] ; then pecl install xdebug ; fi' returned a non-zero code: 1
Service 'wordpress' failed to build : Build failed
```

### Step-by-step reproduction instructions

1. In .wp-env.json, set `"phpVersion": "7.4"`
2. Run `wp-env start --xdebug`

### Environment info

- `@wordpress/env` v5.8.0
- Linux (KDE Neon 5.26) 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by PooSham** [comment]
I assume it would be as simple as changing [this line](https://github.com/WordPress/gutenberg/blob/4b4c4befb34d815634b85cbee23cad169ab0e073/packages/env/lib/init-config.js#L172) to

`RUN if [ -z "$(pecl list | grep xdebug-3.1.6)" ] ; then pecl install xdebug-3.1.6 ; fi`

But maybe you want something more maintainable so you don't need to the version inside this file.

**Comment by nakaharag** [comment]
Yes I guess hardcoding version to xdebug-3.1.6 is correct if using PHP 7.*

According to their announcement, this is the last version to support PHP 7
https://xdebug.org/announcements/2022-11-08

**Comment by PooSham** [comment]
@nakaharag 

I can create a PR if you want. I can do one of the following solutions:

1. Hardcode it to 3.1.6 no matter the PHP version used
2. Create a mapping table from PHP version to XDebug version, and choose the appropriate one depending on the user's phpVersion.

The first is simple and quick, the second requires a bit more development. Also, how do you make sure to keep the mapping maintained? I doubt there's an easy way to get that information from an external source programatically.

**Comment by endriu84** [comment]
@PooSham either way would be great
