### ISSUE TITLE
Consider offering a way to rename a navigation block upon creation

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46638]
## What problem does this address?

This was feedback that came up as part of the [nineteenth call for testing with the FSE Outreach Program](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2812). With the new editable list view experience, the renaming was noted as being too hidden away:

>Creating a new menu we should at the same time get an option to give it a name. Renaming is too hidden away.

>Seemed to me that naming and renaming the menu should be somewhere more intuitive than under Settings > Advanced. Maybe next to the create button, or simply by clicking on the name of the menu. Or when creating menu?

>Having the menu name buried in Settings > Advanced made it a little hard to find.

https://user-images.githubusercontent.com/26996883/208337569-e90771fe-8086-4ab2-876b-dfc7c37e9f39.mov

## What is your proposed solution?

For a long time now, the renaming has been hidden under advanced. [As noted in this PR though](https://github.com/WordPress/gutenberg/pull/36238) that (I think) implemented the current flow, this isn't necessarily ideal:

>Also moves the UI for menu naming and deleting UI to the 'advanced' section as often requested. I still strongly feel this isn't the right solution, and naming is important for users. I wasn't able to come up with an alternative in the limited time that lowers the prominence of the UI. Gutenberg still has limited support for ordering inspector panels. There were also no other designs put forward for this problem other than the advanced panel. 

Opening this issue to consider a way to make more prominent than a collapsed "Advanced" section as naming is very much important.

**Comment by jasmussen** [comment]
I'd like to see what the split inspector can do for the prominence of items under the "Advanced" section, or even for complex blocks like these. At the moment, the affordance is intentionally tucked away because it isn't necessarily a common flow to have more than a single menu, and to not weigh down the inspector for the navigation block which has more urgent challenges to address. That's all to say that there's definitely room for improvement, I'd just put it at a lower priority than ongoing efforts.

**Comment by apeatling** [comment]
Flagging https://github.com/WordPress/gutenberg/pull/46457 as some related work on block naming.

**Comment by scruffian** [comment]
I think this was closed by #50583.
