### ISSUE TITLE
Navigation block: double accessibility color contrast warnings

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46637]
### Description

As part of the [nineteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2812), double color contrast warnings were noted when making changes to the colors of the block.

>Should there be multiple color notifications or should this go into a more general color notification?

It's unclear to me what this might be related to and if it's related to the recent split in settings potentially. I couldn't replicate it with other blocks (post title, site title, etc) but I didn't test too many.

### Step-by-step reproduction instructions

1. Using at least Gutenberg 14.8 RC1, head to Appearance > Editor (beta)
2. Select the navigation block. 
3. Using the color settings, make changes to intentionally make it harder to see the color combination.
4. Notice double errors appearing.

### Screenshots, screen recording, code snippet

<img width="286" alt="Screen Shot 2022-12-18 at 6 35 03 PM" src="https://user-images.githubusercontent.com/26996883/208336626-2b1cdac3-6a85-411e-b5ea-6bcd14e8ab95.png">

### Environment info

- WordPress 6.1.1
- GB 14.8 RC 1
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. I have replicated it in Gutenberg 14.7.3, and it appears to be isolated to the Navigation block. I tested nearly all Core blocks, and the Navigation is the only one with this behavior.
 ![image](https://user-images.githubusercontent.com/4832319/208686450-73322b74-59c8-481d-b3bd-4d8d6c30cf4a.png)
