### ISSUE TITLE
Allow Comments and Allow Pingbacks & Trackbacks settings do not save

### ISSUE THREAD

**Issue by chandrapatel** [WordPress/gutenberg#4663]
## Issue Overview
`Allow Comments` and `Allow Pingbacks & Trackbacks` settings do not save when we publish/update the post.

## Steps to Reproduce (for bugs)
1. Create a new post or edit existing post.
2. Toggle `Allow Comments` and `Allow Pingbacks & Trackbacks` settings. Enable these settings.
3. Publish or Update post.
4. Reload the page and you can see that `Allow Comments` and `Allow Pingbacks & Trackbacks` settings not enabled.

WordPress v4.9.2
Gutenberg v2.0.0

## Expected Behavior
When you enable `Allow Comments` and `Allow Pingbacks & Trackbacks` settings then it should save.

## Current Behavior
Currently, `Allow Comments` and `Allow Pingbacks & Trackbacks` settings not enabled.

## Possible Solution
I've tried to debug the issue. When we publish or update post, first REST API called to update a post. In this request, `Allow Comments` and `Allow Pingbacks & Trackbacks` will save properly.

After this, another `fetch` request called to URL `http://example.test/wp-admin/post.php?post=438&action=edit&classic-editor=1&meta_box=1` to save meta boxes values. See https://github.com/WordPress/gutenberg/blob/master/editor/store/effects.js#L154

So in this request, `Allow Comments` and `Allow Pingbacks & Trackbacks` settings will be disabled. Because these settings do not available in request data. In this request, `wp_insert_post()` called again and `comment_status` and `ping_status` set to `closed` because not found in post data. See line no `3399-3408` -- `https://core.trac.wordpress.org/browser/trunk/src/wp-includes/post.php#L3399`

So this issue happened when saving meta boxes.

**Comment by spencerfinnell** [comment]
Experiencing this issue in 2.1.0 as well.

**Comment by jasmussen** [comment]
Not only does it not save the discussion status, it untoggles it if you edit a post authored in the classic editor in Gutenberg. 

Steps to reproduce:

- Edit a post in the classic editor, verify that discussion settings are set to allow comments/pingbacks
- Open this post in Gutenberg, verify that the discussion toggles allow comments
- Click the ellipsis button next to the Classic block and choose "Convert to blocks"
- Press "Update" and notice how the discussion toggles are unset

**Comment by teezeh** [comment]
I'm experiencing the same issues - every single edit in Gutenberg removes the "Allow comments" and "Allow Pings" setting for a post.

I find this really annoying (because I always have to go to the post list and re-enable comments and pings via "Quick Edit") and would love to see this bug fixed ASAP.

I'm on WP 4.9.4 w/ the Munsa Theme from foxland.fi on my blog teezeh.de. Only a few [selected plugins](https://teezeh.de/2017/07/24/handverlesen-das-sind-meine-wordpress-plugins-2/).
