### ISSUE TITLE
Gutenberg repository management document, v1

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#4664]
To better communicate how things are done around this GitHub repo, I've drafted a [Gutenberg repository management document](https://paper.dropbox.com/doc/Gutenberg-Repository-Management-dnkv20djioiT9BSbNpGQl). Specifically, it covers:

* Issues
    * Labels
    * Triaging Issues
* Pull Requests
    * Code Review
    * Merging Pull Requests
    * Closing Pull Requests

Please leave comments on the document as you see fit. Generally, it's a consolidated version of WP-CLI's [pull requests](https://make.wordpress.org/cli/handbook/pull-requests/), [code review](https://make.wordpress.org/cli/handbook/code-review/), and [repository management](https://make.wordpress.org/cli/handbook/repository-management/) documents. We can add further content to it as we go along.

Once we agree it's in a good place, I'll submit it as a pull request against this repo. For sign-off, I'm looking for a "This looks fine to me". Thanks!

**Comment by bobbingwide** [comment]
I get `Forbidden` when trying to view doc.

**Comment by danielbachhuber** [comment]
@bobbingwide I see your avatar in the document. Looks like you sorted it out?

**Comment by bobbingwide** [comment]
Yes, failed on iPad, worked on laptop. Now where are we supposed to make comments? 
Such as...
1. What is the planned response time for new issues?
2. What's the relationship regarding "Projects"?
3. What about documentation updates - both in the docs folder and the handbook?

**Comment by danielbachhuber** [comment]
> Now where are we supposed to make comments?

You can make them directly inline.

> 1. What is the planned response time for new issues?

My personal opinion is that all new issues and PRs should be touched within the first 24 hours during the work week. However, this requires someone actually doing it.

> 2. What's the relationship regarding "Projects"?

I'm not sure how projects are used. We could add something in a v2 of the document.

> 3. What about documentation updates - both in the docs folder and the handbook?

I'm not sure I follow. Could you clarify your question further?

**Comment by bobbingwide** [comment]
OK. I think I've managed that. 

Re documentation. Should PR's with code and tests also be updating the documentation that we find in the docs folder and hence the handbook?

**Comment by danielbachhuber** [comment]
> Re documentation. Should PR's with code and tests also be updating the documentation that we find in the docs folder and hence the handbook?

Ah, I see what you mean. I'd think "as relevant", but probably as a separate pull request in interest of keeping the conversations manageable.

**Comment by jeffpaul** [comment]
I left some comments and suggested edits, otherwise "This looks fine to me".

**Comment by jaswrks** [comment]
"This looks fine to me" also.

**Comment by danielbachhuber** [comment]
@karmatosed I've granted you edit access so you can modify directly.
