### ISSUE TITLE
Browse mode: Consider adding in descriptions of template after selection

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46640]
## What problem does this address?

As part of the nineteenth call for testing for the FSE Outreach Program, the following was shared:

>I find myself wanting some more description than just “Single.” If I customized these all for myself, maybe this would be enough to remind me what each one is.

Previously, with the template list, the descriptions were visible when going through the experience, whereas now all you can rely on is the name:

<img width="379" alt="Screen Shot 2022-12-18 at 7 34 44 PM" src="https://user-images.githubusercontent.com/26996883/208342435-a074916f-5cd9-494a-aba9-e8dc74c84a6a.png">

Of note, this is using Gutenberg 14.8 RC 1. I didn't see this discussed in https://github.com/WordPress/gutenberg/discussions/45346 and it felt worth separating out into its own issue for consideration. If you'd prefer I consolidate there, happy to do so though. 

## What is your proposed solution?

Perhaps when selecting a template, the description is then displayed in the sidebar or it's shown on hover:

<img width="286" alt="Screen Shot 2022-12-18 at 7 36 08 PM" src="https://user-images.githubusercontent.com/26996883/208342676-25ec9ccd-2883-4ad3-972d-4e129823ac33.png">

**Comment by jasmussen** [comment]
I think @jameskoster you might have a design for this, or am I misremembering?

**Comment by jameskoster** [comment]
No recent designs I'm afraid. 

The problem with displaying the descriptions is that the list gets unwieldy when there are many templates – some of them have quite long descriptions.

My instinct is that the solution here might be better organisation in the sidebar. For example we might only surface the most intuitive / commonly edited templates at the top level, then have drilldowns for template collections like "Blog", "Page", "Store", "Advanced", etc. Since each collection would contain fewer templates it might be feasible to include their descriptions as well, but obviously it needs design.

**Comment by jasmussen** [comment]
In addition to better organization (this can likely benefit template creation modals as well), I wonder if we could maybe show the description on-select? It would be a big blue button, but maybe that's fine?

**Comment by jameskoster** [comment]
Something like that, or displaying the description in a tooltip on hover/focus could be worth a try.

**Comment by annezazu** [comment]
Noting that related feedback came up in the[ same call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2840):

>Is it at all possible to show which template is being used as the site’s front page in the browse mode? I thought to myself that I wasn’t sure if it would be a static page using Page, a static page using Home, or Index – and I have to leave the Editor to find out.

& later from the same person:

>After clearing customizations, the Home template moved from the top of the Templates list to the bottom. It was a great user experience for me to see it at the top of the list (as I think about my homepage first), and a little unclear why it moved to the bottom.

This feels critical to figure out both in terms of clearly prioritizing the template powering the homepage and preventing reordering cc @youknowriad. Happy to open more issues here but these all feel related (lack of descriptions, inability to know at a glance which is the home template, and the changing order). 

Adding this to the phase 2 project board of more general issues for consideration and iteration.

**Comment by jameskoster** [comment]
The first point should be addressed when we add brows-ability to the frame and the experience becomes more content driven. You'd just navigate to your homepage and the site hub widget would tell you which template is on display.

Agree the ordering could be better, but again that would be further enhanced by more intuitive template grouping.

**Comment by apeatling** [comment]
You can still get to all of the descriptions by accessing the "Manage all templates" option and scrolling through the templates there. I wonder if that's enough for folks that are unsure of what each template is? Doing this at least keeps you in the same experience.

**Comment by jasmussen** [comment]
A tooltip is another lightweight option.

**Comment by annezazu** [comment]
This came up once more in the [twentieth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2023/01/11/fse-program-testing-call-20-find-your-style/#comment-2905):

>As a WordPress geek I have over time understood that Single means single blog posts, Home means the home page with or without blog posts (I think I remember this correctly), 404 means page is missing, Archive is for blog post archives. But if I was a random user I would likely not understand what these mean. Perhaps there should be some kind of info box on the bottom below the Templates/Template Parts list giving additional information of what each is. As one could click or hover and see the info on the bottom making it clear for the user where each template is used.

Agreed on the tooltip as a lightweight option to explore for now. Either way, I have to agree that this is a current drawback of browse mode.

cc @richtabor as design lead for 6.2!

**Comment by paaljoachim** [comment]
I will add in this discussion on Slack in the FSE channel: https://wordpress.slack.com/archives/C015GUFFC00/p1674650007809749
and nested thread: https://wordpress.slack.com/archives/C015GUFFC00/p1674655791610549

**Comment by ntsekouras** [comment]
Description has been added here: https://github.com/WordPress/gutenberg/pull/47777. Can we close this or we want something more?

**Comment by jameskoster** [comment]
Imo yes, but feel free to re-open.
