### ISSUE TITLE
Media tab not working when video and audio uploads are disabled

### ISSUE THREAD

**Issue by david-binda** [WordPress/gutenberg#46658]
### Description

The media tab added in [44918](https://github.com/WordPress/gutenberg/pull/44918) is not being displayed in case audio and video files uploads are disabled.

The media types in WordPress can be limited (or extended) via `upload_mimes` filter. In case a plugin or a custom code is limiting the upload types to images only.

In case such code is in effect, the Gutenberg is producing JS errors as displayed on the screenshot below upon clicking on the Block inserter toggle and no media tab is being displayed.

IMHO, the code should not expect any media types to be allowed for upload, and only display the media tab for allowed media types, if there are any.

### Step-by-step reproduction instructions

1. Add the code for limiting the media types allowed to be uploaded to a mu-plugin on your test installation
2. Go to new post screen
3. Click on the Block inserter toggle

### Screenshots, screen recording, code snippet

```
add_filter( 'upload_mimes', function( $mimes ) {
	return array_filter( $mimes, function( $type ) {
		return ( false !== strpos( $type, 'image' ) );
	} );
} );
```

<img width="880" alt="Screenshot 2022-12-19 at 16 13 50" src="https://user-images.githubusercontent.com/3651036/208458561-c6fdb311-1018-43ed-8bbe-797987e2fad8.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
This should be fixed properly by: https://github.com/WordPress/gutenberg/pull/46251. Feel free to reopen if you encounter any issues.
