### ISSUE TITLE
Improper enqueuing of dependency scripts in script block.json property

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#46664]
## This bug is quite important to be fixed for page speed optimization.

I expect dependency scripts not to be enqueued if block is not used.

### Step-by-step reproduction instructions

1. use `wp_register_script` to register a script and supply some dependencies to script
2. create some block
3. use handle of enqueued script in `block.json` `script` property
4. make sure block is not used on a page
5. open page in front end
6. check that all dependency scripts are still enqueued

Now, try replacing `script` with `viewScript` - scripts are not enqueued any more

It seems to me that backend logic (all scripts _should_ be enqueued because user can insert block at any time) is transfered to the front end, where only scripts that are going to be used should be enqueued.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
@Lovor01, thank you for the report. I’d be curious to learn whether you are experiencing this issue when using your block with the block theme (one with `block.json`), with the classic theme, or in both cases.

**Comment by priethor** [comment]
Closing the issue as it has been stale for a while. Please feel free to reopen if the issue persists and there is more info, thanks @Lovor01!
