### ISSUE TITLE
Global styles custom CSS help text wording

### ISSUE THREAD

**Issue by dsas** [WordPress/gutenberg#46669]
### Description

I appreciate this is rather subjective, but I'm not sure that the wording to explain the Additional CSS input feels Gutenberg-y.

Is "Changes won't take effect until you've saved the template" necessary? The same thing goes for everything in Gutenberg, but it's not called out anywhere else. 

If it is necessary then what does "the template" mean? If I've only added a style rule I haven't changed a template at all.

Something I have a weaker opinion on is whether "Enter your custom CSS in the textarea and preview in the editor." is necessary? It seems like a statement of the obvious but appreciate that might not be true for all.

### Step-by-step reproduction instructions

1. Go to Gutenberg Experiments page and toggle custom CSS experiment on
2. Open up the site editor
3. Open up global styles sidebar
4. Press 'Custom' in the CSS section at the bottom

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/93301/208634735-b25d5c0a-29ea-4e9a-a9ae-dca1c35e1f58.png)

### Environment info

Gutenberg 14.8

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
> Is "Changes won't take effect until you've saved the template" necessary? 

The CSS actually impacts the whole site, not just a template; and that description text seems redundant. If anything, we could include the `Learn more about CSS` (https://wordpress.org/support/article/css/) link instead, which is employed in the Customizer currently. 

<img width="300" alt="CleanShot 2023-01-11 at 17 25 07@2x" src="https://user-images.githubusercontent.com/1813435/211931019-1f615977-3724-4cb0-a539-91ce01936c10.png">

**Comment by richtabor** [comment]
Here's a mockup, using `ExternalLink` (same as the Image block's alt text): 

<img width="461" alt="CleanShot 2023-01-11 at 17 30 28@2x" src="https://user-images.githubusercontent.com/1813435/211931900-008da51e-0ee2-43a0-895a-5dc5c48ba414.png">


### Update:

I went ahead and pushed a quick PR for folks to try/see in real time.
