### ISSUE TITLE
List View: unable to move Group blocks in between other group blocks on top level

### ISSUE THREAD

**Issue by luminuu** [WordPress/gutenberg#46678]
### Description

When you have multiple Group blocks on the top level, it's impossible to move one of the Group blocks in between other blocks. You can put it at the top of the list but not at the bottom. In between other blocks, it is always moved into the block above. The blue line to full length, indicating the position where the dragged block is going to be positioned only works to the top level at the position the dragged block is currently at. 

This may be related to #43881 but I noticed this reproduceable behaviour specifically for the group block.

### Step-by-step reproduction instructions

1. Open up a page with multiple group blocks on the top level, or create one. Or add multiple patterns.
2. Open the list view.
3. Try to move one of the group blocks to another position that is not the top.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/7585600/208700989-bf2fb2af-20e4-4422-bcd8-a2e22eb3543e.mp4

### Environment info

- WordPress: 6.1.1
- Gutenberg: 14.7.3
- Extendable theme 1.2.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Thanks for opening this issue! I have a proposed fix for this over in https://github.com/WordPress/gutenberg/pull/49390
