### ISSUE TITLE
Assigning classes to elements in "code view" appears to work inconsistently

### ISSUE THREAD

**Issue by ammist** [WordPress/gutenberg#4668]
## Issue Overview
I want to add a class to a heading or paragraph element, for example:
&lt;h2 class='bluesmurf'&gt;Smurfette&lt;/h2&gt;
or
&lt;p class='description'&gt;Smurfette is a Smurf&lt;/p&gt;

When I tried this from the post-wide "code view" I got an error on the block saying the block had been modified outside the editor, but when I tried the same on the "edit code" in the individual element, it worked.

In the process of writing up this bug report, I realized that the block I had edited in the single-block-code-view got silently converted to a 'classic' HTML block,  but the block I edited in post-wide-code-view was telling me there was a problem and giving me a choice about how to address it.

## Steps to Reproduce (for bugs)

1.  Open up the free Gutenberg post that comes when installing a fresh version of Gutenberg
2. Highlight the Heading block "A picture is worth a thousand words"
3. Click on the three dots to the right of the block and edit as HTML
4. Change the heading so the HTML reads as follows: 
![gutenberg_edit_classes](https://user-images.githubusercontent.com/343197/35374566-46faa2b0-0158-11e8-85f7-acc770a26aff.png)
5. Notice the heading now looks like this: 
![gutenberg-red-heading](https://user-images.githubusercontent.com/343197/35374587-5825e4fa-0158-11e8-932e-afc3be01730d.png)
6. Now click on the "Edit as Code" in the upper right corner of the Edit Post Screen.  The HTML of the post content will appear.
7. Now edit the next heading block (Inserter), adding class="blue" to the HTML:
![2018-01-24_22-50-14](https://user-images.githubusercontent.com/343197/35374751-1ba951b4-0159-11e8-9d6b-22848f7db301.png)
8. Switch back to "Visual Editor" and you'll see an error about the formatting of the block:
![2018-01-24_22-47-42](https://user-images.githubusercontent.com/343197/35374778-30d8be1c-0159-11e8-912a-c1322a5cf7db.png)

## Expected Behavior

Adding a class to a single-element block should not change the type of block it is.

## Current Behavior

See "steps to reproduce" section.

## Possible Solution

Add a "block class" attribute in the "advanced settings" for paragraph and heading blocks (and maybe images?)

Add some kind of visual indicator that the "heading block" got converted to a "classic" block when making certain changes to it.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Related #5028

@aduth Let's make sure this particular case is accommodated in the fix for #5028

**Comment by aduth** [comment]
@ammist Can you verify that steps 1-5 still apply? I am seeing the validation warning, same as with editing in code view. #7538 will address the case for adding additional class names to the markup. It will not solve anything regarding style attributes, and to be quite honest, I do not know that this would be possible to support.

**Comment by mtias** [comment]
Let's close to consolidate issues.
