### ISSUE TITLE
I want the text of the two tooltips to be different.

### ISSUE THREAD

**Issue by ud-fibonacci** [WordPress/gutenberg#46683]
## What problem does this address?
There are two buttons named "Align" on the block toolbar .

<video src="https://user-images.githubusercontent.com/34172366/208716081-2f1919a1-6230-4687-86ef-237fc74fb363.mov"></video>
<img width="565" alt="スクリーンショット 2022-12-20 21 42 22 (1)" src="https://user-images.githubusercontent.com/34172366/208717117-f4d45980-4de0-4298-9f67-faa13a30051a.png">

## What is your proposed solution?
I want the two tooltips to have different names.

**Comment by cbirdsong** [comment]
It seems like it might make more sense to move the layout alignment button into the sidebar with other layout things.

**Comment by ud-fibonacci** [comment]
@cbirdsong 
Thank you!!

Please tell me more.
Do you mean the layout alignment button is an "optional" setting?

**Comment by ud-fibonacci** [comment]
We sincerely appreciate your response!
