### ISSUE TITLE
Dynamic block - setAttributes is not replacing attributes that already exist as default

### ISSUE THREAD

**Issue by cb911nr** [WordPress/gutenberg#46691]
This is absolutely throwing me for a loop this afternoon. We recently converted a static block to a dynamic block.

Now for some weird reason inside `edit.js` when we do `setAttributes` if the values match the default values, it will store nothing on the server and will be a blank array.

So for example, if in registering the block type we have a single attribute for reference

`"title" : {
			"type" : "string",
			"default" : "Cool Title"
		}`

Now that the block is dynamic, when I `setAttributes({title: "Cool Title"});`  it'll not actually set the attribute, and when checking the php attributes after the block is saved, it's a blank Array with the key completely gone... if I change the default to something else

`title" : {
			"type" : "string",
			"default" : "Really Cool Title "
		}`

and then do  `setAttributes({title: "Cool Title"});` then I get an array for Title: Cool Title... as intended

Any ideas why this is happening, and it won't update/save when the default matches?

**Comment by cb911nr** [comment]
Another tidbit of information if I `console.log(attributes)` inside of the editor, it clearly shows the new attributes, it's just for some weird reason `setAttributes` isn't saving over the default and is instead making the "keys" completely gone as a dynamic block.

**Comment by cb911nr** [comment]
And lastly, if I remove all defaults for attributes, aka make them all `"default" : ""`, just blank strings, everything saves in the backend fine when I push a new `setAttributes()`

So since moving to a dynamic block, I am clearly doing something wrong, or there's some kind of weird bug that wordpress will not save the attributes to the database when they match the same as the default, and will entirely strip that specific attribute key out.

**Comment by cb911nr** [comment]
Just wanted to politely bump this to see if there'd been any feedback on this issue.

**Comment by talldan** [comment]
Default attributes generally aren't serialized. Possibly to reduce the payload, I don't know exactly why.

Changing it to something else and then back again does seem to be the exception. I'm not sure why it keeps the default in that case. It's likely the code for setting attributes is something like this:
```js
const currentValue = value ?? default;

if ( newValue === currentValue ) {
    return;
}

setAttributeValue( newValue );
```

It's probably difficult to change this behavior now, as there might be backwards compatibility problems.

In PHP, I think you'll want to work mostly with the `WP_Block` type, as that applies default values to `attributes` property:
https://github.com/WordPress/wordpress-develop/blob/e4419d727ca99efff002ed7dbb70500e5093ed53/src/wp-includes/class-wp-block.php#L165-L192
