### ISSUE TITLE
Navigation nested page list uses incorrect styling in the editor

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#46696]
### Description

A page list nested underneath a submenu item uses the top-level styling instead of the submenu styling in the editor. It looks correct in the page preview.

### Step-by-step reproduction instructions

1. Add a navigation menu in the post editor
2. Add a submenu item in the navigation menu
3. Add a page list as a child of the submenu
4. Apply styling to the navigation block for both top-level and for submenus
5. See that the top-level styling is applied to the page list in the submenu
6. Preview the post and see that the final version uses submenu styling as expected

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/5129775/208819573-1ca32e2b-5bc8-4efd-8b77-acadc2760b5a.mp4

### Environment info

- WordPress trunk
- Gutenberg trunk
- Firefox
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by draganescu** [comment]
I cannot reproduce this in `trunk`
