### ISSUE TITLE
German translation for text-toolbar options inconsistent

### ISSUE THREAD

**Issue by devfle** [WordPress/gutenberg#46711]
### Description

Hello,
the German translations for the text toolbar are inconsistent. The tenses differ (past / future).

This would be my suggestion:

Highlight -> Hervorheben
Strikethrough -> Durchstreichen
Subscript -> Tiefstellen
Superscript -> Hochstellen

### Step-by-step reproduction instructions

1. Open Gutenberg in german language
2. Open Text-Toolbar

### Environment info

WP 6.1.1
Gutenberg 14.7.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thank you for your report.

If the original English tense is correct, I believe that updating [the GlotPress translation](https://translate.wordpress.org/projects/wp-plugins/gutenberg/) may solve the problem. Is my understanding correct?

**Comment by devfle** [comment]
Hi @t-hamano,

yes, you are right. Only the german translation is wrong.

**Comment by t-hamano** [comment]
Then you might want to suggest a translation at GlotPress or contact the German translation community 👍
I'll close this issue.
