### ISSUE TITLE
wp-env start command stuck at "Updating docker images."

### ISSUE THREAD

**Issue by sasharma011** [WordPress/gutenberg#46716]
### Description

I am trying to get my wordpress setup running locally but it gets stuck while updating docker images. I am also not able to see any detailed logs to understand what is going wrong.

Would appreciate any guidance related to this.
Thanks

### Step-by-step reproduction instructions

Running wp-env start command.

### Screenshots, screen recording, code snippet

```
wp-env start
⠙ Updating docker images.
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Hi @sasharma011 - thanks for the report. You might get more responses if you post over in the Localhost support forum, so just wanted to suggest that as another avenue. I'll leave this issue open as well, in case anyone is able to help.

https://wordpress.org/support/forum/localhost-installs/

**Comment by sasharma011** [comment]
I tried to pull each docker image manually and found that it was getting stuck while pulling `wordpressdevelop/phpunit`.
On searching a bit about this issue, I just restarted my docker instance and that fixed the issue.

**Comment by kathrynwp** [comment]
@sasharma011 Perfect, glad you solved the problem, and thanks for closing this issue!
