### ISSUE TITLE
Image Block aligned center is offset in the editor with Gutenberg 14.8.0 active

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#46725]
### Description

On my site with Blockbase activated, an image block set to **align center** appears off-center in the editor.

If I deactivate Gutenberg, the image appears centered in the editor, but the image caption does not.

In both states, the image aligns-center properly on the front end.

### Step-by-step reproduction instructions

1. On a site with Gutenberg 14.8.0 active, activate an FSE theme like **Blockbase**
2. In a new page or post, add an image via the **image block**, and reduce it in size so it is less than the width of the editor
3. **Align Center** and notice how it's not actually centered in the editor. (Compare with a center-justified bit of text or heading, for example)
4. Deactivate Gutenberg 
5. Return to that post and refresh to find the image block now centered, but the caption still offset to the left

### Screenshots, screen recording, code snippet

Recording of issue:

https://user-images.githubusercontent.com/27249804/209025346-a33d5157-fdf3-49d0-ba9b-fb14e19e2f7e.mp4

Front End of site unimpacted:

![Markup on 2022-12-21 at 16:47:57](https://user-images.githubusercontent.com/27249804/209025470-544d3892-df8b-4a11-93b2-a324dbca6c1e.png)

![Markup on 2022-12-21 at 16:47:14](https://user-images.githubusercontent.com/27249804/209025495-06c75df1-fc38-4259-8286-79c671e420c7.png)

### Environment info

- WordPress 6.1.1
- Gutenberg 14.8.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@cuemarie 
Thanks for the report.

I tested with the default themes, but could not reproduce it with Twenty Twenty Three / Two / One. Perhaps the Blockbase is overriding the `display` property to `block;` on the editor, so the intended style is not applied.

I think this is not a bug and needs to be addressed on the theme side.

![center](https://user-images.githubusercontent.com/54422211/209431954-d5b23188-5f61-4ba3-b78b-2c2b35d18d52.png)

**Comment by cuemarie** [comment]
Hey @t-hamano , found this notification in a backscroll - thank you for taking a look and pointing out that `display` / `block` issue; I'll see if I can get some themes folks to take a look! 😊

Closing this issue as well.
