### ISSUE TITLE
Page Template Name Not Updating For PHP Template Files

### ISSUE THREAD

**Issue by myleshyson** [WordPress/gutenberg#46723]
### Description

When clicking "Default Template", and then selecting a template defined in a php file, the "Default Template" text does not update to reflect the newly selected template.

It _does_ update when using html templates in the `templates/` folder. However for many of use we're still rocking the template.php files, so that needs to work as well.

Tested this on a fresh install on the twenty twenty three theme.

### Step-by-step reproduction instructions

1. Create a php template and stick it in the root of your theme. E.g.
```php
// template-full-width.php
/**
 * Template Name: Full Width
 *
 * Page template for full-width NORMAL pages (not fancy landing pages). Just hides the page sidebar.
 */

echo 'hi';
```
2. Go to edit a page, click "Default Template" and select "Full Width" from the drop down.
3. Notice that "Default Template stays the same.

### Screenshots, screen recording, code snippet

<img width="377" alt="Screenshot 2022-12-21 at 5 19 57 PM" src="https://user-images.githubusercontent.com/11747187/209013397-168384a7-3ee0-4e83-b3f6-230c1512e629.png">

### Environment info

Wordpress 6.1.1
Twenty Twenty Three Theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for contributing, @myleshyson!

Can you test with Gutenberg 14.8 active? I believe the issue was fixed in that release. See #46304.

**Comment by myleshyson** [comment]
yes I can confirm 14.8 does resolve this. thanks!
