### ISSUE TITLE
Block Inserter Appears in the Site Editor when it should not

### ISSUE THREAD

**Issue by sanjucta** [WordPress/gutenberg#46720]
### Description

When you navigate to the site editor and scroll to the bottom of the page that appears on the right, the block inserter appears although nothing happens when you click it. 

### Step-by-step reproduction instructions

1. From the WordPress dashboard go to Appearance->Editor
2. Scroll to the bottom of the page that appears on the right.
3. The block inserter button shows up at the bottom.
4. Nothing happens on clicking the block inserter.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4763997/208984937-9c94f0fa-49cd-4070-b1ba-7e7f6541dee9.mp4

### Environment info

- WordPress 6.1.1, Gutenberg 14.8.0,  Theme : Twenty Twenty-Three 
- Browser - Google Chrome Version 108.0.5359.124
- Macbook Pro with macOS Monterey v 12.6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bgardner** [comment]
I can confirm this is happening, as I experienced the same thing. (@sanjucta beat me to opening the issue)

**Comment by kathrynwp** [comment]
Thanks for the detailed bug report, @sanjucta! 

Confirming that I can replicate as well:

WP 6.1.1, Twenty Twenty-Three 1.0, Gutenberg 14.8.0 (no other plugins active)
Firefox 107.0.1 & Chrome 108.0.5359.124

This appears to be a bug specific to Gutenberg 14.8.0.
