### ISSUE TITLE
UI Components, settle on 40px and 32px "small" sizes.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#46734]
UI components across the editor (input fields, buttons, etc.) are currently a range of sizes, between 32px, 36px, and 40px:

| <img width="271" alt="Screenshot 2022-12-22 at 11 21 06" src="https://user-images.githubusercontent.com/1204802/209113168-a6a99e37-411b-42e0-b0aa-3082be32788f.png">  |  <img width="351" alt="Screenshot 2022-12-22 at 11 20 59" src="https://user-images.githubusercontent.com/1204802/209113343-dad05050-3c81-450b-83e8-c9b8f3f3de85.png"> |
| --- | --- |
| The inserter button is 32x32, the other buttons are 36x36  | Buttons here are 36px, including the toggles |

| <img width="335" alt="Screenshot 2022-12-22 at 11 24 03" src="https://user-images.githubusercontent.com/1204802/209113777-92b5d64c-c5d2-406a-a6a2-6a7509116407.png"> | <img width="276" alt="Screenshot 2022-12-22 at 11 21 12" src="https://user-images.githubusercontent.com/1204802/209113738-0974341d-5fa0-4db4-8a41-dba9fb22943d.png">  |
| --- | --- |
| Toggle buttons in the block toolbar are 32x32  | Inspector controls are standardizing on 40px |

There's an opportunity here to standardize and make consistent the controls, so there's less guesswork as to which dimensions controls should have. We could do this:

* All controls (inputs, segmented controls, sliders, dropdowns, and buttons) are 40px by default.
* All toggles (block toolbar button, toggles in the inspector such as quick transforms, the active state inside a segmented control) are 32x32px.
* The Button component has a 32px small version, to be used when the button is used in context of toggles, such as the top toolbar.
* The 36px size is retired entirely.

Here's a grid of metrics to illustrate how this could work:

<img width="1247" alt="grid" src="https://user-images.githubusercontent.com/1204802/209149927-4279c3e3-f085-42f1-aeed-dfed42627453.png">

Both 32 and 40px are base8 friendly, which would simplify the grid system. And with a single default (40px for controls, 32 for toggles inside), there would be no guesswork as to which size to use. The 32px button size would be the exception to use, as noted, in the top toolbar for buttons.

**Comment by mirka** [comment]
I'm very happy to see this! We'll start working out the technical logistics in #46741.

**Comment by jasmussen** [comment]
I wonder if we can close this one as fixed?

**Comment by mirka** [comment]
Sure. Closing in favor of the following tracking issues, where there are just a few more things we're working on:

- #46741
- #65751

**Comment by jasmussen** [comment]
Thanks for all the work!
