### ISSUE TITLE
Page List Item: Don't show a "more" menu.

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46751]
## What problem does this address?
Page list items (the blocks inside Page List) shouldn't display a "more" menu, because they aren't really configurable.

## What is your proposed solution?
We could add a new block supports, something like "blockSettings". If it's false then don't display any block setting for that block.

**Comment by carolinan** [comment]
Yes, the "copy block" menu item for the page list item doesn't work, so this can be confusing.

(It copies, but you can't use the copied code in visual editing mode, and it is only a partial block if you paste it in the code editor)

**Comment by carolinan** [comment]
Does the page list item need a toolbar at all?
(I know the more menu is also used in the list view)
