### ISSUE TITLE
min.Height in appearance tool breaks templates and template parts

### ISSUE THREAD

**Issue by exenreco** [WordPress/gutenberg#46760]
version 14.7.3. min.Height in appearance tool breaks templates and template parts. Am guessing its bind to the window hight which break stuff, probably so since its located in a sub element idk?

**Comment by aurooba** [comment]
Hi @exenreco! Could you provide us with more information and what you are trying to accomplish? Code samples and screenshots would also help us determine what the issue is.

**Comment by jordesign** [comment]
With no further info on this issue - and an original report from almost a year ago - I'll close this issue. Can always be re-opened if we get more information.
