### ISSUE TITLE
How to fire "change" event on "Additional CSS Class" input

### ISSUE THREAD

**Issue by PivotDev** [WordPress/gutenberg#4676]
I'm using JS to populate the Additional CSS Class input, which works fine (i.e. the value of the text input field is getting set), however it's not notifying Gutenberg that the value has been updated, and it doesn't save the programmatically-populated value. I've tried:

`$( this ).trigger( 'change' );`
`$( this ).trigger( 'keyup' );`
`$( this ).trigger( 'keydown' );`  
`$( this ).trigger( 'keypress' );`
`$( this ).trigger( 'textInput' );`

...which do fire but have no effect on Gutenberg. Any ideas? Thanks very much and apologies for the noob question.

**Comment by youknowriad** [comment]
You should not use DOM to edit UI content, that's hacky and probably not reliable since DOM can change with release updates. Instead you can use the data module to change block attributes for instance.

`wp.data.dispatch( 'core/editor' ).updateBlockAttributes( blockUID, blockAttributes )`
