### ISSUE TITLE
Site Logo Block: Sizing SVG image not working.

### ISSUE THREAD

**Issue by shadigaafar** [WordPress/gutenberg#46784]
### Description

When  trying add SVG image as a logo through Site Logo Block, it does not size. or it actually disapear. 

### Step-by-step reproduction instructions

1. Allow SVG images by any means.
2. Go to Site Editor and use site logo block to add any svg image.
3. see if does it appear when you scale it up or down.
4. save and preview changes in new tab. 

### Environment info

- WordPress Version: 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by exenreco** [comment]
SVG in classic was not allowed so not sure if they added this feature in fse. SVGs Can Be dangerous

**Comment by shadigaafar** [comment]
> SVG in classic was not allowed so not sure if they added this feature in fse. SVGs Can Be dangerous

I know that, and I'm not asking for adding SVG support, I'm just saying that make sure that sizing work with SVG too, so if the user added SVG support using plugin or a peace of code. He can add logo in SVG.

**Comment by annezazu** [comment]
Hey there! Thanks for opening this. I see a lot of overlap with https://github.com/WordPress/gutenberg/issues/43130 Can you confirm? If so, it would be great to consolidate and close out this issue.

**Comment by shadigaafar** [comment]
> Hey there! Thanks for opening this. I see a lot of overlap with #43130 Can you confirm? If so, it would be great to consolidate and close out this issue.

Confirmed
