### ISSUE TITLE
Site Editor: Gradient background color repeats

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#46782]
### Description

Might be related to #44374

In the global style, repetition may occur when the body has a gradient background color. This seems to occur when the block content is less than the height of the iframe area.

### Step-by-step reproduction instructions

- Activate Twenty Twenty Three.
- Open the site editor and enter the edit mode with the Blank template.
- apply the Sherbet style.
- In zoomed-out view, the content area is heighted to fit the block and no background repetition occurs.
- When you return to edit mode and insert any block (or after a short time), the background will expand to full height and you will see the background image repeat itself.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/209458602-c6046625-7f48-477c-9293-97d8c5973b14.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Perhaps this problem is not limited to gradient backgrounds. When returning from a zoomed-out view, the height of the content switches unsteadily.

https://user-images.githubusercontent.com/54422211/209460394-4738c30f-5615-4af1-8dc7-af1a74676644.mp4

**Comment by annezazu** [comment]
This was reported as part of the [nineteenth call for testing for the FSE Outreach Program:](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2846)

>Theme seems to have a dark mode view that appears to be broken when you’re editing a template part. It’s unclear if the ridges are the expected behavior

![Screenshot 2022-12-27 at 17 58 41 2022-12-27 at 7 05 23 PM](https://user-images.githubusercontent.com/26996883/212223951-d86da942-ef39-421c-bb7f-62214c6da66a.jpg)

**Comment by n-els** [comment]
What is the current status, I still have this problem.

**Comment by annezazu** [comment]
This is still an active issue, meaning it has yet to be fixed.

**Comment by priethor** [comment]
@t-hamano are you still interested in working on this issue?

**Comment by t-hamano** [comment]
I apologize for the delay in responding, even though I have assigned myself.

I have not yet found the ideal solution, but I will work on it as a high priority. If you all have a good approach, I would welcome PR 🙏

**Comment by priethor** [comment]
Thanks, Aki; no worries! I just wanted to know if it's still on your radar 🙂
