### ISSUE TITLE
Admin menu can't be scrolled when its height exceed the viewport height

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#4679]
The WordPress admin menu works in a way that, thanks to some "magic", all its content is always visible, even when it gets very long. Some users are used to add lots of plugins, which in turn may add lots of new items to the admin menu. The menu height can't be predicted.

Seems in the Gutenberg pages the admin menu "magic" doesn't work. If the menu contains many items and gets very tall, there's no way to scroll and access the menu items in the bottom part.

To reproduce, install and activate a few plugins that add items to the menu. I've activated:
- Jetpack, with its custom post types enabled
- WooCoomerce
- a known plugin for SEO

Emulate a viewport width, for example, of 1024 by 768 pixels width. Please consider this is just to make testing easier. Actyally, the inability to scroll applies to any screen/viewport size and depends on the number of items added to the menu.

![screen shot 2018-01-25 at 18 45 21](https://user-images.githubusercontent.com/1682452/35403881-6bfa7c6c-0201-11e8-9040-a045605e1b64.png)

Notice that under "Settings" there are the SEO plugin menu item, the Gutenberg menu item, and the "Collapse menu" button:
- in a Gutenberg page, for example `post-new.php?gutenberg-demo`, I can't scroll the menu
- in all the other pages, for example `post-new.php?classic-editor`, I can

**Comment by jasmussen** [comment]
I can't reproduce, though. Have you tested on 2.1?

![scrolling admin](https://user-images.githubusercontent.com/1204802/35728260-56182e2a-080b-11e8-9f97-855f64391891.gif)

**Comment by afercia** [comment]
Can't reproduce any longer on current master.
