### ISSUE TITLE
Unable to register format type to handle bare tag name

### ISSUE THREAD

**Issue by davilera** [WordPress/gutenberg#46795]
### Description

Users are unable to register a new format type to handle a bare tag name (i.e. when `className` is set to `null`), as `registerFormatType` logs the following error:

> Format "core/unknown" is already registered to handle bare tag name "xxx".

This occurs because `registerFormatType` [has the following validation snippet](https://github.com/WordPress/gutenberg/blob/a7e2895829c16ecd77a5ba22d84f1dee1cfb0977/packages/rich-text/src/register-format-type.js#L80) in line 80:

```js
if ( settings.className === null ) {
  const formatTypeForBareElement = select(
    richTextStore
 ).getFormatTypeForBareElement( settings.tagName );

  if ( formatTypeForBareElement ) {
    window.console.error(
      `Format "${ formatTypeForBareElement.name }" is already registered to handle bare tag name "${ settings.tagName }".`
    );
    return;
 }
}
```

that checks if the given `tagName` is already registered. [The current implementation of `getFormatTypeForBareElement`]():

```js
export function getFormatTypeForBareElement( state, bareElementTagName ) {
  const formatTypes = getFormatTypes( state );
  return (
    formatTypes.find( ( { className, tagName } ) => {
      return className === null && bareElementTagName === tagName;
    } ) ||
    formatTypes.find( ( { className, tagName } ) => {
      return className === null && '*' === tagName;
    } )
  );
}
```

always returns a valid format type for any bare element, because of the second part of the `return` statement, thus making it impossible to register new formats.

**Possible Solution**

In `registerFormatType`, [change line 85](https://github.com/WordPress/gutenberg/blob/a7e2895829c16ecd77a5ba22d84f1dee1cfb0977/packages/rich-text/src/register-format-type.js#L85) from:

```js
if ( formatTypeForBareElement ) {
```

to

```js
if (
  formatTypeForBareElement &&
  formatTypeForBareElement.name !== 'core/unknown'
) {
```

### Step-by-step reproduction instructions

1. Go to the post editor
2. Open your browser's developer tools
3. In the JavaScript console, type the following:

```js
wp.richText.registerFormatType( 'name/format', {
  title: 'Test bare tag format',
  tagName: 'xxx',
  className: null,
  edit: () => null,
} );
```

### Environment info

- WordPress 6.1.1
- Gutenberg 14.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.
I think this issue is the same as #46777.

**Comment by kathrynwp** [comment]
I'm going to go ahead and close this out, so that efforts to fix the issue can be concentrated over in the other ticket. Thank you again for reporting!
