### ISSUE TITLE
Document all Block API functions

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#468]
`blocks/README.md` needs some updating, or a new document needs to be created, especially after #438.  For example, it's common for blocks to need to pull out the `focus` and `setFocus` properties of the object passed to `edit`, but it's not very clear what these are or where they come from.

`focus` in particular is an object whose structure should be documented for block implementers - see https://github.com/WordPress/gutenberg/pull/438#issuecomment-295336742

**Comment by youknowriad** [comment]
We need to document `transforms`, `insertBlockAfter` as well.

**Comment by mtias** [comment]
Done in #1794, ongoing work in #1786.
