### ISSUE TITLE
List Block not recognizing sub-bullets as list items when copy/pasting from Word

### ISSUE THREAD

**Issue by tamara-m** [WordPress/gutenberg#46803]
### Description

As from the late Nov 2022 update to List Blocks, copy/pasting lists from Word to the Block Editor no longer recognizes sub-items.

Not only the formatting is lost but the additional issues happened when attempting to workaround it:

* Convert to HTML resulted in broken code that could not be converted back to Visual mode
* Attempting to edit the items to make them sub-items as they should be, is extremely hard, when not impossible in mobile. Tapping list items prompts the tool bar under other elements and at the top of the screen, it becomes un-reachable, attempting to select anything on the bar selects another List items or List, etc.

It is important to note is that the root issue of the pasted content loosing the sub-level is new to the List Block. Before November updates, this bug did not use to happen, and we used this behavior of copy/pasting Word > Block Editor very frequently.

### Step-by-step reproduction instructions

1. Go to a Word document that has a bulleted list with some items on one sub-level
2. Go to any Post in the Block Editor and Paste

### Environment info

- Safari and Chrome reported the same bugs

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
Hi, @tamara-m I cannot replicate this, when I copy and paste list items from Word the formatting is carried over. This includes the sub-level items as shown in the short video below. 

![Dec-28-2022 15-44-10](https://user-images.githubusercontent.com/41231764/209823866-fdc3bd51-bc6f-446a-944c-4594188d8819.gif)

Testing Enviroment 

- WordPress 6.1.1
- No plugins are active except Gutenberg version 14.8.2
- Twenty Twenty Three theme 

Can you please check your testing environment?

**Comment by danbalaban** [comment]
We have the same issue with a custom theme.

Pasting the bulleted list doesn't work for us either and adding a second list item doesn't work, it only adds nested items.

**Comment by tamara-m** [comment]
I am trying to get a video of the issue to add to this ticket, will post it here if/as soon as I can get it.

**Comment by priethor** [comment]
Let's close this issue, as it needs more info to be actionable. Please feel free to reopen again if there is more information. 🙏
