### ISSUE TITLE
"Classic editor" option in "New post" drop down launches Gutenberg

### ISSUE THREAD

**Issue by rosswintle** [WordPress/gutenberg#4682]
## Issue Overview

I saw this in v2.0 and thought it MUST have been reported and fixed in GB 2.1, but it's not.

On the "All Posts" screen is a "New post" button which, with the GB plugin installed has a dropdown with two items:

* Gutenberg; and 
* Classic editor

<img width="263" alt="screen shot 2018-01-25 at 21 11 24" src="https://user-images.githubusercontent.com/1532368/35412606-976022cc-0214-11e8-8b36-83ae4674b234.png">

Both of these seem to link to /wp-admin/post-new.php

The "Classic editor" link therefore launches Gutenberg.

## Steps to Reproduce (for bugs)
1. Install and activate Gutenberg plugin
2. Go to "All posts" screen
3. Select "Classic Editor" from the dropdown

I'm using Chrome 63 on a MacBook Pro running High Sierra

## Expected Behavior

The Classic Editor should open

## Current Behavior

The Gutenberg editor opens

## Possible Solution

Make the "Classic Editor" link have the `classic-editor` parameter in the URL

**Comment by danielbachhuber** [comment]
I've seen this too, although it's happened intermittently in my experience.

**Comment by rosswintle** [comment]
I just did a load of quick tests and this (where it exists) seems to be a problem going back to version 1.5 when Gutenberg became the default editing experience.

Lines 519 to 526 of `gutenberg.php` are what's at work. 

It looks like it assumes that the button has `?classic-editor` in the href and strips it out for the Gutenberg button.  So if the button doesn't have `?classic-editor` both buttons have the same URL.

So the question is why, in some cases, does the button not have `?classic-editor` in its href by default?

**Comment by karmatosed** [comment]
I have to say I can't recreate this so we need to dig a bit more in.

Just checking the steps to be sure:
1. Click 'All posts'.
2. Click 'Classic editor' and you get the classic editor.

![2018-01-25 at 22 39](https://user-images.githubusercontent.com/253067/35416345-b39c1462-0220-11e8-959b-f35eca75df68.png)

![2018-01-25 at 22 40](https://user-images.githubusercontent.com/253067/35416351-c0623e24-0220-11e8-9d59-ace36e586a2c.png)

I was using Chrome and Mac. 

Now, my thoughts are if my steps are correct there could be a sneaky plugin or theme bug here. So let's dig deeper!

**Comment by rosswintle** [comment]
I did disable all plugins, and my these was a child of Twenty Sixteen with VERY minor modifications.

Let me try on a clean install.

**Comment by danielbachhuber** [comment]
I think it's this hacky code:

![image](https://user-images.githubusercontent.com/36432/35416647-b9b0ff8a-01de-11e8-8069-9c6d9060b9fd.png)

For me, the `var_export()` produces:

```
[25-Jan-2018 22:46:56 UTC] array (
  0 => 'gutenberg_modify_add_new_button_url',
  1 => 'WP_Hook->apply_filters',
  2 => 'apply_filters(\'admin_url\')',
  3 => 'get_admin_url',
  4 => 'admin_url',
  5 => 'wp_admin_bar_new_content_menu',
  6 => 'WP_Hook->apply_filters',
  7 => 'WP_Hook->do_action',
  8 => 'do_action_ref_array',
  9 => 'wp_admin_bar_render',
  10 => 'WP_Hook->apply_filters',
  11 => 'WP_Hook->do_action',
  12 => 'do_action(\'in_admin_header\')',
  13 => 'require_once(\'wp-admin/admin-header.php\')',
  14 => 'require(\'wp-admin/edit.php\')',
)
[25-Jan-2018 22:46:56 UTC] array (
  0 => 'gutenberg_modify_add_new_button_url',
  1 => 'WP_Hook->apply_filters',
  2 => 'apply_filters(\'admin_url\')',
  3 => 'get_admin_url',
  4 => 'admin_url',
  5 => 'wp_admin_bar_new_content_menu',
  6 => 'WP_Hook->apply_filters',
  7 => 'WP_Hook->do_action',
  8 => 'do_action_ref_array',
  9 => 'wp_admin_bar_render',
  10 => 'WP_Hook->apply_filters',
  11 => 'WP_Hook->do_action',
  12 => 'do_action(\'in_admin_header\')',
  13 => 'require_once(\'wp-admin/admin-header.php\')',
  14 => 'require(\'wp-admin/edit.php\')',
)
[25-Jan-2018 22:46:56 UTC] array (
  0 => 'gutenberg_modify_add_new_button_url',
  1 => 'WP_Hook->apply_filters',
  2 => 'apply_filters(\'admin_url\')',
  3 => 'get_admin_url',
  4 => 'admin_url',
  5 => 'wp_admin_bar_new_content_menu',
  6 => 'WP_Hook->apply_filters',
  7 => 'WP_Hook->do_action',
  8 => 'do_action_ref_array',
  9 => 'wp_admin_bar_render',
  10 => 'WP_Hook->apply_filters',
  11 => 'WP_Hook->do_action',
  12 => 'do_action(\'in_admin_header\')',
  13 => 'require_once(\'wp-admin/admin-header.php\')',
  14 => 'require(\'wp-admin/edit.php\')',
)
[25-Jan-2018 22:46:56 UTC] array (
  0 => 'gutenberg_modify_add_new_button_url',
  1 => 'WP_Hook->apply_filters',
  2 => 'apply_filters(\'admin_url\')',
  3 => 'get_admin_url',
  4 => 'admin_url',
  5 => 'require(\'wp-admin/edit.php\')',
)
```

I'm running Laraval Valet, which is why `require(\'wp-admin/edit.php\')` isn't in global scope.

**Comment by rosswintle** [comment]
Interesting. I'm running Laravel Valet too. I'm sure I see this on my blog though.

Here's a video demo on a clean install on Valet...

https://cl.ly/2U3k3h3w350I

**Comment by danielbachhuber** [comment]
@rosswintle Can you verify https://github.com/WordPress/gutenberg/pull/4683 fixes it for you locally?

**Comment by rosswintle** [comment]
Yup. That's good. Nice spot.

But it's now even more hacky code, right?

**Comment by danielbachhuber** [comment]
> But it's now even more hacky code, right?

😉 For the temporary problem it needs to solve, I think it works fine. If I were going to launch a rocket with this, I'd find some more durable solution.

**Comment by rosswintle** [comment]
I want to fix the logic.  I went down a rabbit hole. I'm giving up for the time being.

`gutenberg_modify_add_new_button_url()` - the "hacky" code - by it's own description:

> Sets the default behaviour for the "Add New" button to go to the classic editor."

This is the URL on the button before it gets overridden by JavaScript.  If JavaScript is enabled then the JS form `gutenberg_replace_default_add_new_button()` kicks in and modifies both the "Add New" button and adds the dropdown. But browsers with no JS always go to the classic editor.

So we DO need the hacky code despite what I previously thought.

Hmmm...

**Comment by rosswintle** [comment]
Good morning.

So I slept on this and I'm going to argue for removing the hacky code.

The hacky code (in `gutenberg_modify_add_new_button_url()`) sets the "Add New" button at the top of the All Posts screen to have a default URL (before being overridden by JS) with the `classic-editor` parameter.  If you have JS enabled the JS removed the `classic-editor` param from the button and adds the drop-down.

However, with JS disabled, the other links to create a new post are not modified to use JS.  See the screengrab...

<img width="981" alt="screen shot 2018-01-26 at 07 18 46" src="https://user-images.githubusercontent.com/1532368/35428941-99f5adb8-0269-11e8-9bce-710f01e33105.png">

So instead of adding the `classic-editor` param in and then removing it again using JS, I suggest it should not there in the first place, and we add it in JS when we create the dropdown.

I'll put together a PR later.
