### ISSUE TITLE
Allow start="X" on <ol> elements

### ISSUE THREAD

**Issue by pansamolot** [WordPress/gutenberg#46837]
## What problem does this address?

HTML 5 [allows starting lists from something else than 1](https://stackoverflow.com/a/779052/1469208) and so must this be supported in Gutenberg. I don't think there's too much more that can be said about this.

## What is your proposed solution?

We need Gutenberg to correctly process the following example code, which is [perfectly valid](https://stackoverflow.com/a/779052/1469208):

    <ol start="6">
      <li>Lorem</li>
      <li>Ipsum</li>
      <li>Dolor</li>
   </ol>

So using it in Code Editor will end up (after switching back to the Visual Editor) with this:

![image](https://user-images.githubusercontent.com/60975060/210186080-66c43b79-fd31-4ddf-b378-7b78c03d52fc.png)

And not with this:

![image](https://user-images.githubusercontent.com/60975060/210186090-d851d758-335b-4302-a868-0ef6c878df83.png)

I think that this is all. Thank you for your understanding.

**Comment by mauteri** [comment]
Hi @pansamolot, I took a look and found that `start` is already available in Gutenberg (both in the current plugin and in WP core). Please see screenshot of how to update `start` and let me know if you have any follow up questions. Thanks!

<img width="1524" alt="list-start" src="https://user-images.githubusercontent.com/818980/210191993-76c74f51-bf8c-48b9-a74f-35be090a19fd.png">

**Comment by pansamolot** [comment]
Sorry, no such thing, as you can see in the following screenshot:

![image](https://user-images.githubusercontent.com/60975060/210202048-f9364c11-97dd-4f43-838f-c03019e7307b.png)

Which version of Guttenberg you are using? I have the "separate" development version, now in version 14.8.4:

![image](https://user-images.githubusercontent.com/60975060/210202115-62fbfaf9-ddd0-4979-941f-efb63a928eae.png)

Also, I can see that you have a "normal" fonts while I've been struggling for months (if not years) that after each following update of Gutenberg my fonts are getting "back to normal" and then (after another update) are again and again "incorrect" showing everything in Times New Roman (as currently). I was even wondering how it is possible that the development team of Gutenberg is falling into the same regression with fonts issue over and over again.

So, if you have the same Gutenberg version as I do (the newest official one) and you have both "start" on "ol" and correct forms then maybe this is not a Gutenberg issue in my case but some clash with other plugin, theme or component?

**Comment by mauteri** [comment]
@pansamolot it looks like you may have the `List item` selected, not the actual `List`. Take a look at bottom left of the edit screen and make sure it is `Post > List` not `Post > List > List item`. If it's the latter, click on `List` and you should see the correct screen where you can set `start`. Hope that helps!

**Comment by pansamolot** [comment]
@mauteri Sure thing! Thanks for pointing out and sorry for spamming / duplicating. Closing.

**Comment by mauteri** [comment]
No problem! Have a great day!
