### ISSUE TITLE
Children of block variations refer to their parents with their original name

### ISSUE THREAD

**Issue by sunyatasattva** [WordPress/gutenberg#46833]
### Description

When a block variation is registered and given a different name, while this new name shows correctly in most Gutenberg UI elements (list view, toolbar, inspector controls etc.), it does still show with its original name when selecting it from a child block using the `Select parent block` option.

### Step-by-step reproduction instructions

1. Register a [block variation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/) and make sure the `isActive` method targets that variation uniquely. For example you can use the “Query Loop” block, which already has inner blocks.
2. Select the “Post template” block and notice that your variation name is not respected when selecting the parent block.

For quicker testing, you can use the “Products (Beta)” block included in WooCommerce Blocks.

### Screenshots, screen recording, code snippet

<img width="613" alt="209835250-efad1eb1-5927-4ce8-b54c-970ccbd76148" src="https://user-images.githubusercontent.com/1847066/210087723-2414ec50-7d6d-441c-9d6c-3be08507bf9c.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@jorgefilipecosta wanted to flag for you!

**Comment by jorgefilipecosta** [comment]
Hi @sunyatasattva,
This issue seems fixed on the Gutenberg trunk:
![image](https://user-images.githubusercontent.com/11271197/210790178-b2f43ee2-81a9-4ef5-9b45-9f256b539a17.png)
So I'm going to close the issue. If you can still reproduce the issue on Gutenberg trunk feel free to reopen so we can look further.
