### ISSUE TITLE
When I make changes with the FSE, the changes are not applied.

### ISSUE THREAD

**Issue by Faton1995** [WordPress/gutenberg#46841]
https://user-images.githubusercontent.com/121765651/210258159-bf2ceddc-74d9-4a23-b663-bb32113cffa8.mov

### Description

I have the following problem with my WordPress Multisite network.
When I make changes with the Full Site Editor (FSE) to some of my websites I get the message that the website has been updated has been updated. However, when I check the website, the changes are not and when I call the editor again the changes are gone disappeared.

I have also deactivated many plugins to get to the source of the Problem.
But it just does not want to work.

Even when I created a completely new site in my WordPress Multisite
Network, it does not work.

Here is a sample video:
https://development.ahlulbait.one/2023/01/01/bildschirmaufnahme-von-full-site-editor/
_____________

Does anyone maybe have a solution?

### Step-by-step reproduction instructions

Here you can see a video of it: https://development.ahlulbait.one/2023/01/01/bildschirmaufnahme-von-full-site-editor/

### Screenshots, screen recording, code snippet

https://development.ahlulbait.one/2023/01/01/bildschirmaufnahme-von-full-site-editor/

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Faton1995** [comment]
Hello

I fixed the problem by simply renaming the plugin folder. Now I just have to find out which plugin was the main trigger.

**Comment by kathrynwp** [comment]
Glad you discovered that this is in fact a plugin conflict. 

I'll go ahead and close this ticket, but if you have further issues specific to your setup, feel free to post a support request in one of the support forums: https://wordpress.org/support/forums/
