### ISSUE TITLE
Cant set initial core/cover values without getting a console error

### ISSUE THREAD

**Issue by hoppdigital** [WordPress/gutenberg#46856]
### Discussed in https://github.com/WordPress/gutenberg/discussions/46854

<div type='discussions-op-text'>

<sup>Originally posted by **hoppdigital** January  3, 2023</sup>
Im using Advanced Custom Fields to register a PHP block type. If I set some initial CSS values to the core/cover block type, such as a min-height on page reload the data retrieved from the database isn't correct & the block wont render correctly. The spacer block type works ok on initial setting a value eg height 5px & page reloading, but not the core/cover block.

**template-parts/blocks/content-cta-banner-bg.php**

```
$template = array(
    array( 'core/cover', array(
			// If the below values are set there will be a console error on reload in CMS? Data missmatch.
			// 'minHeightUnit' => 'px',
			// 'minHeight' => '500',
			// 'dimRatio' => '0'
		),
		array(
			array('core/spacer', array(
					//Spacer value set OK...
					'height' => '5px',
				),
			),
			array('core/button', array(
				'placeholder' => 'Type CTA button text here...'
				),
			),
		)
	),
);

echo '<div class="cta-banner-block">';
    echo '<InnerBlocks template="' . esc_attr( wp_json_encode( $template ) ) . '"  templateLock=false/>';
echo '</div>';


```

**functions.php**

```
acf_register_block_type(array(
                                        'name'              => 'cta-banner',
					'title'             => __('Call to Action Banner'),
					'description'       => __('Info here....'),
					'category'          => 'custom-cat-name',
					'icon'		  => 'cover-image',
					'mode'              => 'preview',
					'align'             => 'full',
					'supports'          => array(
						'align' => false,
						'mode'	=> false,
						'jsx'	=> true
					),
					'render_template' => plugin_dir_path(__FILE__) . 'template-parts/blocks/content-cta-banner-bg.php',
				));
```</div>

**Comment by kathrynwp** [comment]
Could you please add:

- detailed, step-by-step reproduction instructions
- your WordPress version
- whether you have the Gutenberg plugin active, and if so, which version
- browser you're seeing the behaviour on
- what other plugins you have active, and whether the problem persists with all plugins deactivated except Gutenberg

**Comment by t-hamano** [comment]
@hoppdigital 
I don't know the specs of that plugin, but it doesn't seem to cause problems in a typical implementation using Gutenberg components.

```javascript
( function ( blocks, element, blockEditor ) {
	var el = element.createElement;
	var InnerBlocks = blockEditor.InnerBlocks;
	var useBlockProps = blockEditor.useBlockProps;

	blocks.registerBlockType( 'create-block/gutenpride', {
		title: 'Gutenpride',
		category: 'design',

		edit: function( props ) {
			var blockProps = useBlockProps();
			return el(
				'div',
				blockProps,
				el(
					InnerBlocks,
					{
						template: [
							[
								'core/cover',
								{
									minHeightUnit: 'px',
									minHeight: '300',
									dimRatio: '10',
								}
							],
						],
					}
				)
			);
		},
	} );
} )( window.wp.blocks, window.wp.element, window.wp.blockEditor );
```

You might try contacting the plugin developer's support forum, for example.

**Comment by t-hamano** [comment]
@hoppdigital
I would like to close this issue as I believe this is not Gutenberg bug. If there is anything I have missed, please feel free to comment.
