### ISSUE TITLE
Browse Mode: consider unifying add new templates and template parts UI

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46867]
## What problem does this address?

This came up as a piece of feedback in the [nineteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2833):

>I found it a little odd that adding a template is in a dropdown menu, but adding a template part is in a modal

Here's a video of the current experience showing the different interfaces:

https://user-images.githubusercontent.com/26996883/210443824-6d895b37-328a-440f-b732-12ee3cd9f427.mov

## What is your proposed solution?

Unify the experience and pick one :) I noticed that it wasn't on the list for follow up items for https://github.com/WordPress/gutenberg/issues/36667 nor discussed in https://github.com/WordPress/gutenberg/discussions/45346 so decided to open this issue for consideration cc @WordPress/gutenberg-design

**Comment by jameskoster** [comment]
The inconsistency doesn't feel like a huge problem to me as things stand, but if it's a simple change then it couldn't hurt to move the "General, Header, Footer" template part options to a popover (same UI as adding a template), but we'd still need a modal for the name input. In that sense the flow would match Custom template creation. 

On balance I think this is something that'd be nice to address holistically in a follow-up to 36667.

**Comment by annezazu** [comment]
Closing this out as the experience has substantially changed beyond this as of 6.4 beta 4:

https://github.com/WordPress/gutenberg/assets/26996883/ad670c21-a44b-47ae-8644-9e47ed524970

It does seem wise to have consistency between template parts and patterns modal so I'll open an issue there.
