### ISSUE TITLE
Show Add Block icon on bottom of block when other block icons show

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4686]
## Issue Overview
At the moment, the _Add Block_ icon at the bottom of the block only shows after actually clicking on a block and then moving your cursor over the bottom border (or very close to it).

This makes the icon difficult to find and for new users, a lot of the time they wont even realise that there's an icon there.

I think this icon should be changed so that it shows at all times the other block icons are displaying. That is, when you hover anywhere over a block, or whilst editing the block. At the moment, if you're just clicking between blocks, you wont even notice the icon. It would be much easier to be able to hover over a block and then simply click the _Add Block_ icon whenever you wanted to insert a new block (between blocks), without having to purposely hover your cursor over the (invisible) icon to get it to display.

![gutenberg-showaddblockicon](https://user-images.githubusercontent.com/2078245/35420814-b8ee1aa0-0293-11e8-9441-a985afec5a02.gif)

## Steps to Reproduce (for bugs)
1. Insert a few paragraph blocks
2. Move between blocks and take note of Add Block icon interaction

## Expected Behavior
The Add Block icon at the bottom of the block is too easy to miss unless you actually know it's there

## Current Behavior
I currently have to move the cursor near the (invisible) icon, or near the bottom border, for it to actually show. How am I going to know to do this if I'm a new user?

## Possible Solution
Show _Add Block_ icon at bottom of block whenever the other block specific icons are showing

_Firefox Quantum 57.0.4 (64-bit)
WordPress 4.9.2
Gutenberg 2.1.0_

**Comment by karmatosed** [comment]
As this section and the "+" has changed, going to close this issue for now. We can of course review and reopen any issue.
