### ISSUE TITLE
I have a idea for Multilingual Feature

### ISSUE THREAD

**Issue by Faton1995** [WordPress/gutenberg#46879]
Hello

I have a very good solution how to make WordPress multilingual thanks to the new FSI editor: 

In the pages templates insert the function that you can assign languages to the templates. Then the pages templates would be eg in the language German and English. You should also include a sync function: for example, if I create an article in the German page, then it should automatically appear as a draft, so that it is first translated before it appears publicly. 

You should also be able to define in the language group template how it will be displayed e.g. de.webseite.com or webseite.com.

Each object / block asks the template: Which language should I render. 

I hope someone understands my idea.

**Comment by youknowriad** [comment]
Hi There! thanks for sharing your idea. It's a bit early for this project but I invite you to detail your proposal in more details in the [Discussions](https://github.com/WordPress/gutenberg/discussions). Also potentially you can start exploring it as a plugin and propose the idea more formally.
