### ISSUE TITLE
Text Only mode: ensure split settings work correctly 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46871]
## What problem does this address?

This came up as part of the [FSE Outreach Program's nineteenth call for testing](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2836):

>In step 11 I like the idea of tabs rather than LOOOOoooonnngg settings screens, but I don’t like the icons. Turning text labels on in the preferences didn’t seem to have any effect on the sidebar. Again, icons-plus-labels would be a much better option here.

<img width="1385" alt="Screen Shot 2023-01-03 at 6 32 53 PM" src="https://user-images.githubusercontent.com/26996883/210458584-800aad11-3c4e-490d-8c94-7efbc53c53b3.png">

cc @aaronrobertshaw 

## What is your proposed solution?

Ensure there are text labels in place for the split settings.

**Comment by aaronrobertshaw** [comment]
A potential fix for this is up in https://github.com/WordPress/gutenberg/pull/46968
