### ISSUE TITLE
Site editor: Custom CSS field is missing in Styles

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46873]
### Description

[As part of the nineteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2838), it was noted that, after changing the Gutenberg version in use, the custom CSS field was suddenly missing. 

It looks like sometime after Gutenberg 14.8, this feature got lost and it's no longer present [even in Gutenberg 14.9 RC1.](https://github.com/WordPress/gutenberg/releases/tag/v14.9.0-rc.1)

cc @glendaviesnz who implemented this feature https://github.com/WordPress/gutenberg/pull/46141

### Step-by-step reproduction instructions

1. Use Gutenberg 14.8.1+
2. Open the Site Editor > Styles
3. Try to find the Custom section at the bottom. See it's not there.

### Screenshots, screen recording, code snippet

<img width="300" alt="Screen Shot 2023-01-03 at 7 06 46 PM" src="https://user-images.githubusercontent.com/26996883/210461734-5258f277-346b-4b00-b1dd-ddb4d391a0f4.png">

### Environment info

- WP 6.1.1
- GB 14.8.4 & GB 14.9 RC1
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by franzaurus** [comment]
I noticed that in Gutenberg 14.8.3 the Custom CSS feature is put into an experiment module. Apparently this is since 14.8.rc2 [#46663](https://github.com/WordPress/gutenberg/pull/46663)

**Comment by annezazu** [comment]
Ah ha! I tried looking at the various release notes but missed this. I'll update the FSE Outreach Program experiment in light of that. Closing this out.
