### ISSUE TITLE
Styles: Preview and Stylebook cut off with Whisper variation

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46874]
### Description

This bug was found as part of the [FSE Outreach Program's nineteenth call for testing:](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2844)

> I found that Style book doesn’t show examples properly on Whisper style variant. I’m using Gutenberg 14.8.3. The problem happened because the style variant applies full body border. For a short work around, undisplaying the border-style through Custom CSS solves the issue. What a way to try out the experiment module that turns out well. 🙂 However, I think Style book should be supportive to any kinds of block theme.

cc @madhusudhand (preview) and @noisysocks (style book) of note, I replicated this with GB 14.9 RC1

### Step-by-step reproduction instructions

1. Activate TT3 and select Whisper style variant
2. Open Style book
3. Notice the bottom border of every example is cut. 
4. Open Styles again > Blocks and notice the previews are also cut off.

### Screenshots, screen recording, code snippet

Stylebook:

<img width="1016" alt="Screen Shot 2023-01-03 at 7 26 34 PM" src="https://user-images.githubusercontent.com/26996883/210463385-91956b9c-d5ef-4225-a5be-d0ac8bb1c800.png">

Style preview:

<img width="286" alt="Screen Shot 2023-01-03 at 7 25 04 PM" src="https://user-images.githubusercontent.com/26996883/210463389-ebd0f8b8-26b7-40b5-b0cc-d7c3e91c8d2f.png">

### Environment info

- WordPress 6.1.1
- GB 14.9 RC1 & GB 14.8.3
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by juanfra** [comment]
Interesting! added a fix for this one [here](https://github.com/WordPress/gutenberg/pull/46946)

**Comment by juanfra** [comment]
Hi @annezazu,

[The PR has just been merged](https://github.com/WordPress/gutenberg/pull/46946), so we should be good to go with this one now 😄

**Comment by annezazu** [comment]
Awesome! Closing out. Thank you ❤️
