### ISSUE TITLE
Delete empty block after columns block moves the empty block inside the columns block

### ISSUE THREAD

**Issue by MatzeKitt** [WordPress/gutenberg#46899]
### Description

If you delete an empty block below a columns block, instead of being deleted, the empty block gets transformed into another column with an empty block.

### Step-by-step reproduction instructions

1. Add a columns block, e.g. with 33 / 33 / 33 layout.
2. Add a new block below the columns block by clicking below the columns block.
3. Press backspace.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1018979/210758922-55d02543-1dd1-4ee8-932d-59789601be77.mp4

### Environment info

– WordPress 6.1.1, no Gutenberg plugin
– Safari/Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I can confirm this with GB 14.9.

**Comment by t-hamano** [comment]
I expect this issue to be the same as #45436.

**Comment by MatzeKitt** [comment]
Yes, seems to be identical.
