### ISSUE TITLE
Warning: Cannot use a scalar value as an array in .../gutenberg/lib/client-assets.php on line 239

### ISSUE THREAD

**Issue by GaryJones** [WordPress/gutenberg#4689]
## Issue Overview
Warnings thrown in Gutenberg 2.0 and 2.1.

## Steps to Reproduce (for bugs)
1. PHP 5.2
2. Activate plugin, and visit Add Post.

## Screenshots / Video
![Gutenberg warning](https://user-images.githubusercontent.com/88371/35432898-7b8ae4fa-0279-11e8-87f8-34c8381818c8.png)

With PHP 5.3, the warnings disappear.

**Comment by danielbachhuber** [comment]
@justnorris @GaryJones Is this issue still applicable?

**Comment by justnorris** [comment]
@danielbachhuber Yeah, I assume it still is - nothing has really changed there. I don't have 5.2 at hand anymore so I can't double-test it right now.

**Comment by GaryJones** [comment]
Yes, though it now disappears under the WP admin chrome:

![screenshot 2018-05-26 02 53 46](https://user-images.githubusercontent.com/88371/40571408-1648d866-6090-11e8-8fbd-933c8121959f.png)

When I hide the menu and GB toolbar, I see:

![screenshot 2018-05-26 02 55 07](https://user-images.githubusercontent.com/88371/40571414-40003c8a-6090-11e8-8ec8-b66b84dc4cf9.png)
