### ISSUE TITLE
Consider moving Snackbars

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#46901]
I ran into an issue today when deleting multiple templates one by one:

<img width="361" alt="Screenshot 2023-01-05 at 11 17 58" src="https://user-images.githubusercontent.com/846565/210768215-7a45f71f-3113-4836-953e-b162bf5806ef.png">

The stacking Snackbars obscure the navigation panel adding friction to the flow. Is there a better position for these where they're less likely to obscure important parts of the UI?

**Comment by richtabor** [comment]
Perhaps we have a max number that's shown? Like after two, the oldest one fades out/up to make room for the newest?

**Comment by richtabor** [comment]
Maybe bottom center, Figma style perhaps (in addition). That way they can show up regardless of the frame/context (which is what snagged up https://github.com/WordPress/gutenberg/pull/47298).

**Comment by jameskoster** [comment]
A maximum sounds sensible, and positioning bottom-center is worth a try imo.

**Comment by apeatling** [comment]
Is it worth closing out https://github.com/WordPress/gutenberg/pull/47298 and starting a new PR with this context in mind? I think the previous PR suffered with not having the full context of the issue.

**Comment by richtabor** [comment]
Yea, I'd say so.

**Comment by glendaviesnz** [comment]
[PR here](https://github.com/WordPress/gutenberg/issues/50624) that fixes this by making sure only one snackbar appears at a time.

**Comment by richtabor** [comment]
> positioning bottom-center is worth a try imo.

I still think centering will also help on this front.
