### ISSUE TITLE
RichText Toolbar bug in Modal

### ISSUE THREAD

**Issue by yarovikov** [WordPress/gutenberg#46906]
### Description

Hi there.

I have RichText inside Modal component. But the toolbar is outside. Inline

### Step-by-step reproduction instructions

1. make simple block
2. open modal
3. select the text

### Screenshots, screen recording, code snippet

<img width="858" alt="Screenshot 2023-01-05 at 14 10 30" src="https://user-images.githubusercontent.com/30932012/210788145-503b5f52-b0e7-4410-8fe1-2a8d98613f7b.png">

### Environment info

- WP 6.1.1
- Chrome 108.0.5359.124
- Mac OS 12.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by yarovikov** [comment]
Ok. I did it 👍
Use these components: SlotFillProvider, Slot, Fill.

 
<img width="864" alt="Screenshot 2023-01-08 at 17 56 00" src="https://user-images.githubusercontent.com/30932012/211208998-dfc9331f-907d-454d-a4c3-33a84968c249.png">

**Comment by dmitrijCraq** [comment]
Hi @yarovikov I came across the same problem. Could you please share your solution?

**Comment by caercam** [comment]
Interested in this as well, trying to do exactly the same thing. @yarovikov could you share your solution?

**Comment by chrstffr** [comment]
Since the OP won't share his solution, here's mine.

```
return (
    <Modal>
      <SlotFillProvider>
        <RichText
          value={value}
          inlineToolbar={true}
          allowedFormats={["core/bold", "core/italic", "core/link"]}
          onChange={(value) => console.log(value)}
        />
        <Slot name="RichText.Toolbar" />
      </SlotFillProvider>
      <Fill name="RichText.Toolbar">
        <BlockControls />
      </Fill>
    </Modal>
  );
```

**Comment by nkyimas-epignosis** [comment]
I tried the solution @chrstffr suggested but for some reason when is wrapped inside `<InspectorControls>` the `<BlockControls/>` keeps rendering outside the settings sidebar.
Is there any explanation for this?

**Comment by chrstffr** [comment]
> I tried the solution @chrstffr suggested but for some reason when is wrapped inside `<InspectorControls>` the `<BlockControls/>` keeps rendering outside the settings sidebar. Is there any explanation for this?

Yes, use `<InspectorControl />` to render controls in the sidebar and `<BlockControl />` to render controls in Blocks. You can't mix them up and expect a good result.
