### ISSUE TITLE
Consider renaming "Push changes to Global Styles"

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46928]
## What problem does this address?

In 14.9, a new feature was added to push changes to global styles:

<img width="276" alt="Screen Shot 2023-01-05 at 8 50 40 PM" src="https://user-images.githubusercontent.com/26996883/210913526-77cc2bf3-1482-477b-a7da-8e7af09b2867.png">

Global Styles is the name of broader effort though than just the exposed Styles UI in my opinion: https://github.com/WordPress/gutenberg/issues/41232 Generally speaking, saying "Global styles" is something that has been avoided in user docs because of this reason. 

## What is your proposed solution?

Rename this to "Push changes to Styles" or "Push changes globally".

**Comment by annezazu** [comment]
@jameskoster since these were based on your designs do you know if it is agreed upon to use the "Global Styles" name? In my mind, I think we should stick with Styles due to precedence in the interface, welcome guide, etc.

**Comment by andrewserong** [comment]
I like this idea, and "Push changes globally" has a nice ring to it to me — instead of using a proper noun, it describes the action, which I quite like for buttons. Happy to throw up a quick PR on Monday if we have agreement on what the label should be.

**Comment by jameskoster** [comment]
I don't think it was discussed at all. I agree this label is probably a bit technical, perhaps even the "push" part as well?

Is "Apply" better than "push"? 🤔 

<img width="280" alt="Screenshot 2023-01-06 at 12 05 29" src="https://user-images.githubusercontent.com/846565/211009566-ab6cb1d6-aadb-44f4-a60f-559b2f099a58.png">

**Comment by annezazu** [comment]
I dig that. While we're looking at this, does the style of the button itself match what we'd normally use? It feels like a very prominent style for a potentially less often used feature under Advanced settings.

**Comment by jameskoster** [comment]
We can probably explore that separately, after we've determined whether the Appearance / Settings inspector tabs experiment has been successful. If so it might make more sense to include this in the Appearance tab.

Another thing to consider is resetting custom styles, which is an action very closely related to this one. A very rough mockup:

<img width="306" alt="Screenshot 2023-01-06 at 17 13 23" src="https://user-images.githubusercontent.com/846565/211062984-be38354d-7096-4563-b966-0f3293fa28f9.png">

**Comment by andrewserong** [comment]
> Is "Apply" better than "push"?

Oh, I like that, too. I've thrown up a quick PR to do the renaming in #46965.

**Comment by juanfra** [comment]
Nicely done 👏 

I see that on @jameskoster's proposal, the description is also changing to start with "Apply this block's...". Do we also want to update that? I'd be happy to open a tiny PR with that.

**Comment by jameskoster** [comment]
@juanfra I think it might be worth it since "Move" is a little bit ambiguous.

**Comment by kristastevens** [comment]
Hi @annezazu, thanks for the ping! 

> Apply globally 

^ This works and feels clear as a label for the button. 

@juanfra  said:

> I see that on....proposal, the description is also changing to start with "Apply this block's...". Do we also want to update that? I'd be happy to open a tiny PR with that. 

For that microtext, I see just one small grammar issue to fix:

Currently reads: 
> Apply this blocks typography, spacing, dimensions, and color styles to all Heading blocks.

Should read: 
> Apply this block's typography, spacing, dimensions, and color styles to all Heading blocks.

**Comment by juanfra** [comment]
Thank you, Krista! I just double-checked the code and the [apostrophe is in place](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/hooks/push-changes-to-global-styles/index.js#L127), so we're safe there. 

I left a comment on [Andrew's PR](https://github.com/WordPress/gutenberg/pull/46965) to address the update of the microtext.

**Comment by annezazu** [comment]
Thank you all for diving right in with design, editorial, and dev work. Love it.

**Comment by richtabor** [comment]
> We can probably explore that separately, after we've determined whether the Appearance / Settings inspector tabs experiment has been successful.

How do we determine this?

>  If so it might make more sense to include this in the Appearance tab.

Agreed, although likely a tad tricky.

**Comment by jameskoster** [comment]
> How do we determine this?

I'm not actually sure :)
