### ISSUE TITLE
Block appender not appearing in WP6.1.1 in certain scenarios

### ISSUE THREAD

**Issue by kmrmohit** [WordPress/gutenberg#46921]
### Description

 Default block appender used to appear at the end of the content in WP5.5.1 but in the newer version it doesn't show up. 

### Step-by-step reproduction instructions

1. add a block
2. again add a non-paragraph block below

### Workaround

The appender at the end doesn't show when a block is already in focus but when clicked outside or when multiple blocks are selected, it reappears.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/39377854/210835882-e9931596-0ebe-4beb-8915-30ee62f63929.mov

https://user-images.githubusercontent.com/39377854/210849031-be1a1935-e617-4f0b-a4b4-9e75bf43f956.mp4

### Environment info

– WordPress 6.1.1, no Gutenberg plugin
– Safari/Chrome

###  Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
maybe heavily related to https://github.com/WordPress/gutenberg/issues/45497 ; need to investigate whether the external block button appender is applied to blocks besides Paragraph block in 6.1.1+

**Comment by kmrmohit** [comment]
The block-button appender existed in 5.5.1 in the above scenario, so was it removed intentionally in 6.0? This is a super-useful feature used by many of our authors. @t-hamano shouldn't it be a bug if this isn't the intended behavior?

**Comment by t-hamano** [comment]
As far as I can tell, I think this is the intended behavior. Perhaps #36656 is related.

> When no block is selected, the appender of the root level is shown.

In other words, when a block is selected, the appender at the root level is not displayed.

**Comment by kmrmohit** [comment]
Putting up a closing note to this issue, our customers were not happy with this new enhancement as they were very much used to the previous feature where they can add a block when they are already working inside a block. But we will convince them to give it a try.
