### ISSUE TITLE
Add support for HTML element option for Cover block.

### ISSUE THREAD

**Issue by EldarAgalarov** [WordPress/gutenberg#46926]
Group block have HTML ELEMENT option for html tags picking different than `div`.
Cover block doesn't have such option. Both blocks are container blocks so Cover block should have this option too.

**Comment by t-hamano** [comment]
I looked up the blocks where the HTML element option is supported. In my opinion, it would be better if the cover block supported 7 elements as well as the group block.

|                    | `div`      | `header` | `main` | `section` | `article` | `aside` | `footer` |
| ------------------ | ---------- | -------- | ------ | --------- | --------- | ------- | -------- |
| core/group         | ✅(default) | ✅        | ✅      | ✅         | ✅         | ✅       | ✅        |
| core/template-part | ✅          | ✅        | ✅      | ✅         | ✅         | ✅       | ✅        |
| core/comments      | ✅(default) |          |        | ✅         |           | ✅       |          |
| core/query         | ✅(default) |          | ✅      | ✅         |           | ✅       |          |

**Comment by carolinan** [comment]
I'd prefer to exclude `<main>`, to avoid it being used by mistake?

**Comment by t-hamano** [comment]
> I'd prefer to exclude <main>, to avoid it being used by mistake?

I think there are users who would like to include a pattern image in the background of the main area. However, it is difficult to say whether this is a common use case.
