### ISSUE TITLE
Navigation: Make the OffCanvasEditor the default experience.

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46938]
## What problem does this address?
Based on the feedback on https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/, let's make the OffCanvasEditor the default experience for the navigation block.

This means removing all references to `window?.__experimentalEnableOffCanvasNavigationEditor` in the code.

One thing to note is that the global navigation sidebar in the Site Editor is also using this experiment to hide its functionality. This sidebar is not yet ready to be moved out of an experiment, so we should ensure that it remains hidden behind this (or another) flag.

Another thing to be aware of is that this experiment is reliant on the tabs in the inspector controls. Both of these experiments need to be made the default. @aaronrobertshaw do you have a plan for this?

A reminder here are the calls for testing:

- [Prototype](https://make.wordpress.org/test/2022/12/08/fse-program-site-editor-sneak-peek-summary/)
- [Experimental implementation](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/)

**Comment by talldan** [comment]
It's good to see that an accessibility review has been requested ❤️ 

Some styling issues I've spotted that might be good to resolve and bring more in line with List View ...

#### In List View the main focus ring surrounds the entire row, which isn't always the case in the off canvas editor
| List View | Off Canvas Editor |
| --------- | ----------- |
|    ![Screen Shot 2023-01-10 at 1 02 18 pm](https://user-images.githubusercontent.com/677833/211466053-2a40dacc-238b-4985-aa0e-7382dba822fd.png)  |  ![Screen Shot 2023-01-10 at 1 02 59 pm](https://user-images.githubusercontent.com/677833/211466121-76424ead-98ec-47b4-8dc6-a421770a15d9.png) |

#### Lock and Block Settings icons are not aligned between rows
| List View | Off Canvas Editor |
| --------- | ----------- |
|  ![Screen Shot 2023-01-10 at 1 05 56 pm](https://user-images.githubusercontent.com/677833/211466454-311c1b15-ea3e-49a1-b06f-32125373fe3a.png)  | ![Screen Shot 2023-01-10 at 1 06 46 pm](https://user-images.githubusercontent.com/677833/211466553-0b9f3cde-627d-441d-a546-a8905988bcfa.png) |

#### Horizontal scroll bars often display
![Screen Shot 2023-01-10 at 1 07 46 pm](https://user-images.githubusercontent.com/677833/211466661-e6ece070-dbcf-4d6a-849a-a1783cc4c47e.png)

**Comment by getdave** [comment]
For additional context I've updated the Issue description with links to the x2 calls for testing that were made on Make Blog for this feature over the past few months.

- [Prototype](https://make.wordpress.org/test/2022/12/08/fse-program-site-editor-sneak-peek-summary/)
- [Experimental implementation](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/)

**Comment by aaronrobertshaw** [comment]
> Another thing to be aware of is that this experiment is reliant on the tabs in the inspector controls. Both of these experiments need to be made the default. @aaronrobertshaw do you have a plan for this?

I'll be putting together a PR to stabilize the inspector controls tabs today in the hope we might be able to get it reviewed and merged in time for the next Gutenberg release. That would give us two full Gutenberg releases with it as the default experience before the WordPress 6.2 feature freeze.

**Comment by aaronrobertshaw** [comment]
https://github.com/WordPress/gutenberg/pull/47045 was just merged stabilizing the block inspector tabs experiment.
