### ISSUE TITLE
Advanced panel HTML element selection is missing help text

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#46967]
## What problem does this address?

The group, comments, query and template part blocks have an option in the Advanced panel where you can change the HTML element.

But only the group block has a help text that explains what the tags are used for, helping users make good decisions:

![The help text is below the HTML element option in the Advanced panel](https://user-images.githubusercontent.com/7422055/211262348-9975933b-7d4b-4120-9878-e813a34e1422.png)

## What is your proposed solution?

Add the relevant help text to the blocks that are missing it.

**Comment by juanfra** [comment]
Good addition! [I've created a PR for this issue here](https://github.com/WordPress/gutenberg/pull/46989).
