### ISSUE TITLE
Option to remove links from Post Tags Block

### ISSUE THREAD

**Issue by alokjain-lucky** [WordPress/gutenberg#46973]
I am using Post Tags Block to show doctors' specialisations on a page. I do not need them to be linked anywhere. But there is no option in the Post Tags Block to disable the links. 

It would be good to add an option to the block to disable the links.

**Comment by skorasaurus** [comment]
thanks for reporting; this is currently also reported at https://github.com/WordPress/gutenberg/issues/50904 where you can follow its progress
