### ISSUE TITLE
Rogue text can be created while editing an image.

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#47]
Not sure if this is a bug with `contenteditable=true` or what exactly, but it does lend to weird behavior.

![phantom-text](https://cloud.githubusercontent.com/assets/16389612/22809876/253b0e66-ef03-11e6-9163-a2e98927dac3.gif)

You are able to create a raw text node within the editor by adding text below an image. No content block created for it.  You could move the image up and down and create more rogue text nodes throughout the document.

One solutionish thing would be to scan the editor for text nodes when a block is selected, like:
```js
// psuedo code
const findTextNodes = ( node ) => {
  return Array.from( node.childNodes ).filter( childNode => childNode.nodeName === '#text' );
}

textNodes = findTextNodes( queryFirst( '.editor' ) )
```
and then destroy the text node(s) and wrap it in a `<p>` instead.

**Comment by mtias** [comment]
We may want to set the image as a non-editable node, see if that helps.

**Comment by BE-Webdesign** [comment]
That sounds like a better solution.

**Comment by jasmussen** [comment]
Closing for now as it seems to have been prototype specific.
