### ISSUE TITLE
Improve accessible text of Open Navigation List View button

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#47007]
As reported in https://github.com/WordPress/gutenberg/issues/46939#issuecomment-1374652632, currently the text of the button in block toolbar which opens the Offcanvas List View for the Nav block is not descriptive enough.

Consider a more descriptive name for the feature and utilise this on the button.

cc @WordPress/gutenberg-design for input here.

**Comment by jameskoster** [comment]
I believe this is the button referenced:

<img width="387" alt="Screenshot 2023-01-10 at 12 37 00" src="https://user-images.githubusercontent.com/846565/211553432-ef13192f-0f48-41b9-a525-80fdd9517a0e.png">

**Comment by draganescu** [comment]
I think we should remove this button. I think it's a superfluous addition for [quite a while](https://github.com/WordPress/gutenberg/issues/42257#issuecomment-1316833855), provides no extra value, and it is confusing.

**Comment by getdave** [comment]
> provides no extra value, and it is confusing.

Are you able to elaborate on this a little? 🙏

**Comment by draganescu** [comment]
@getdave 

- The button is unique to the navigation block and the action opens the settings sidebar. There is a button to open settings.
- The fact that editing nested content is part of a sidebar that is called settings, it somewhat related to @alexstine 's issue with chaotic context - but nevertheless there is an UX in place to get to settings. 
- So then, what is this button, 
  - A sort of shortcut? 
  - Do we need to toggle it on and off based on display state of the settings sidebar?
  - Do we need to toggle it off if the new tabs of the inspector are set to something other than list view?
  - We can't even [open the list view directly](https://github.com/WordPress/gutenberg/pull/46907) yet. 

For all these reasons it is not a good button :) it's a bad button.

**Comment by getdave** [comment]
Excellent reasoning. Now we have the appropriate context available I think we should raise a PR to remove the button. Much appreciated 🙇

**Comment by provenself** [comment]
Looks like this is settled — okay to remove the `Needs Copy Review` tag?
