### ISSUE TITLE
is setup-local-env.sh working?

### ISSUE THREAD

**Issue by idpokute** [WordPress/gutenberg#4700]
## Issue Overview

I bought new laptop and installed ubuntu lts as second os.
Run sudo su, then Installed required apps such as nvm (node lts and npm) git, docker, docker-compose
and run setup-local-env.sh, but it didn't work. It's new laptop and fresh, and followed the steps the How to Contribute page. But it is still no luck. Could anyone shed light?
Thanks.

## Steps to Reproduce (for bugs)

1.Login as the account that you use when you install Ubuntu 16.04 lts
2.Run sudo su
3.install required apps
4.run ./bin/setup-local-env.sh

## Expected Behavior

install proper docker images

## Current Behavior

Shows following message

STATUS: Installing and updating NPM packages...
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress.git /root/.npm/_cacache/tmp/git-clone-8f523ab2
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-8f523ab2': Permission denied
npm ERR!

**Comment by ntwb** [comment]
Are you able to manually run `npm install` from the Gutenberg root folder?

**Comment by idpokute** [comment]
hi @ntwb 
It showed the same error.

**Comment by ntwb** [comment]
Do you have Git installed? `git --version`

**Comment by idpokute** [comment]
yes, so I can pull this repo. I'm using V2.7.4

**Comment by ntwb** [comment]
Can you try deleting the `node_modules` folder, and the `package-lock.json` file and then run `npm install` again, please

The above is via https://stackoverflow.com/a/46681156/1911294 (I'm not a fan of the other answer to the question here)

**Comment by idpokute** [comment]
@ntwb 
the command;npm install, was failed, so there is no node_module directory, and I delete the json file.
and shows the same errors and 2 more warning. here is info;


root@Inspiron-5379:/home/se/projects/gutenberg# npm install
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/babel-jest failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress.git /root/.npm/_cacache/tmp/git-clone-1f086344
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-1f086344': Permission denied
npm ERR! 

I think my laptop is fresh, so some other new developers might meet the same issue.

**Comment by ntwb** [comment]
I see two users being referenced based on your latest output `/home/se` and `/root`

In your original post you wrote:
> Run sudo su, then Installed required apps such as nvm (node lts and npm) git, docker, docker-compose and run setup-local-env.sh

I think this is the cause, as `root` has the npm permissions at `/root/.npm` and your standard user does not.

**Comment by idpokute** [comment]
@ntwb I found a clue from your comment. I thought sudo su command guarantees super user access level permission (aka root permission), but it seems this is not proper command in this case. I solved this issue using another command; su
It works ! I even could run setup-local-env. It works perfectly. 
Thanks.

**Comment by ntwb** [comment]
Great, thanks for the update, I think you may continue to have issues with permissions though.

If you do, uninstalling nvm, npm, docker etc, and reinstall using your standard user, i.e. by not using `sudo` :)
