### ISSUE TITLE
Page List: Consider a different way of showing that this is a synced block

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#47006]
## What problem does this address?
When in the off canvas editor, the page list block uses a different icon:
<img width="291" alt="Screenshot 2023-01-10 at 11 02 15" src="https://user-images.githubusercontent.com/275961/211534546-7c9297f9-c672-4f04-9cd8-6886836a06e6.png">

The intention of this icon is to show that the items within this block are synced with the pages in the site. However there has been some feedback that this intention isn't totally clear. Could we consider a different way to achieve this?

## What is your proposed solution?
Some ideas:
1. Use the standard Page List icon but make it purple
2. Use this alternative icon and make it purple
3. Keep the standard Page List icon and add this alternative icon to the right hand side of the block where the lock icon lives.

cc @SaxonF @jasmussen for design feedback.

**Comment by SaxonF** [comment]
I still think long term we should reconsider the name of this block but in the short term here are a few suggestions:

The first is to revert back to the original icon but adjust inner block to use single page icon so at least there is some contrast between parent and child

![Image](https://user-images.githubusercontent.com/1072756/211985934-eae929ba-4e69-4ae4-ab9d-a7058335f02c.png)

The second is to adjust the description of the page list block to better describe its syncing function.

> Display a list of your site’s pages that are always kept in sync

#47064 should also help here as any interaction should display the same "customise menu" modal we use when clicking "edit". This softens the need to explain syncing functionality up front.

**Comment by jasmussen** [comment]
I like the idea of tying the icon change to a name change 👍 👍

**Comment by scruffian** [comment]
We made some progress towards this in https://github.com/WordPress/gutenberg/pull/47337. I'm going to close for now.
