### ISSUE TITLE
Nav offcanvas - order of block items in inserter doesn't always prioritise Custom Link.

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#47012]
As reported in https://github.com/WordPress/gutenberg/issues/46939#issuecomment-1374652632.

the order of block items in inserter popup doesn't always prioritise `Custom Link`. This is confusing as an initial experience because its likely to be the most common block folks want to insert.

We should find a way to force prioritise certain blocks in this particular inserter instance.

**Comment by scruffian** [comment]
We should probably prioritize page link and post link too.

**Comment by scruffian** [comment]
This was achieved in https://github.com/WordPress/gutenberg/pull/48752
