### ISSUE TITLE
Styling blocks: Color panel descriptions are ambiguous

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#47026]
Navigate to: Styles > Blocks > Button > Colors > Background and you see the following UI:

<img width="280" alt="Screenshot 2023-01-10 at 11 56 44" src="https://user-images.githubusercontent.com/846565/211545681-68c11db4-3a7c-471f-96ca-af8f4cd1fcb3.png">

From the description, you might interpret the change to affect the whole site rather than just the Button block. 

The Text panel is similar:

<img width="278" alt="Screenshot 2023-01-10 at 11 59 01" src="https://user-images.githubusercontent.com/846565/211546173-a08604d7-e532-46a3-a3e9-02a10b1fad57.png">

This feels a bit buggy, and could do with some attention.

**Comment by jameskoster** [comment]
A couple of options:

### Contextual descriptions:

> Set a background color or gradient for **Button**s.

> Set the default color used for **Button** text across the site

### Less explicit descriptions

> Set a background color or gradient

> Set the text color

### Add context to the panel UI

The current descriptions might not be so ambiguous if there was something to indicate what it is you're styling:

<img width="280" alt="Screenshot 2023-01-10 at 12 06 03" src="https://user-images.githubusercontent.com/846565/211547369-7df902fd-cdad-4e28-bcf3-1dd32b16cedc.png">

cc @WordPress/gutenberg-design

**Comment by richtabor** [comment]
It's not in scope, but we could use a better panel navigation — breadcrumbs style perhaps — which would add the context needed to know where you're at, and what you're doing.

Like `Styles > Button > Text` or such.

**Comment by richtabor** [comment]
> Set a background color or gradient for Buttons.

Do you think just saying `Set the default background for Button blocks` is clear enough?

I wasn't thinking we'd need "default", but we probably do - as this change won't affect any button block with modified background/text attributes.

**Comment by jameskoster** [comment]
Breadcrumbs aren't perfect, but I agree something like that could help with orientation. @SaxonF has shared such concepts before. 

> I wasn't thinking we'd need "default", but we probably do - as this change won't affect any button block with modified background/text attributes.

Good point, we also need to consider style variations. IE:

`Set the default background for Outline Button blocks`

So now the description has to include the block name, and the chosen style variation where applicable. Is the additional logic worthwhile, or would a generic description ("Set a background color") be better? More radical: Do we actually need a description in this context? Doesn't the navigational path make it obvious what you're doing?

**Comment by SaxonF** [comment]
Worth exploring what a breadcrumb approach might look like. From previous explorations:

![image](https://user-images.githubusercontent.com/1072756/212583048-d441d91d-2cbb-4a4b-aa67-2cca4ec3c1fe.png)

Difficulty will be when working with longer block names.

Related question, why does the global block panel differ from the local block panel?

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1072756/212583631-c328e51b-37a1-4767-be91-1a001004cf45.png">

**Comment by jameskoster** [comment]
> Related question, why does the global block panel differ from the local block panel?

That's a very good question. It would probably solve a lot of issues (including this one) if they were the same.

**Comment by jameskoster** [comment]
No longer an issue :)
