### ISSUE TITLE
Styling blocks: Access to full color palette editing feels too prominent

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#47021]
Navigate to: Styles > Blocks > Button > Colors and you see the following UI:

<img width="280" alt="Screenshot 2023-01-10 at 11 40 57" src="https://user-images.githubusercontent.com/846565/211542766-cfd4b551-fbd1-4b56-a429-534d515adc21.png">

The placement / prominence of the Palette UI feels a bit inappropriate.

1. You might mistake it for being a button-specific palette
2. In the context of styling a specific block, you'd expect the 'elements' to be the primary focus (IE change the background color of Buttons, rather than changing the Primary color for all blocks across the entire site).

**Comment by jameskoster** [comment]
A potential solution here would be to place access to palette editing in the UI where that palette is visible. IE, when you click "Background" in the screenshot above, you'd see:

<img width="280" alt="Screenshot 2023-01-10 at 11 53 40" src="https://user-images.githubusercontent.com/846565/211545044-0050c960-0efd-42e4-ad52-8dc36016e45a.png">

(We should do something about the description there too, it makes no sense in the context of editing a single block type).

The "Edit palettes" button would take you to the palette editing panel.

**Comment by richtabor** [comment]
I agree, adding palettes right at the top feels out of place and breaks context. They're not relative to what I'm tying to do; that is, change the colors of the buttons on my site. 

Edit palettes control at the bottom seems palatable 😉, although I'm not sure many would understand/see the nuances of the two views. 

Part of a bigger effort, but I think palette management and color application could be one in the same ( https://github.com/WordPress/gutenberg/issues/42278), which would remove the need to edit the palette, then come back to the button (or any other block) and apply that color.

**Comment by jameskoster** [comment]
Good points. #42278 would be a much more comprehensive solution. 

Perhaps in the mean time we simply hide the palette section in this particular context?

**Comment by jameskoster** [comment]
No longer an issue :)
