### ISSUE TITLE
Search: allow filtering of required attribute in search input

### ISSUE THREAD

**Issue by Web-Assembler** [WordPress/gutenberg#47030]
## What problem does this address?
When using the core/search block on a blog archive I want to disable the 'required' setting for the search input box so that all of the posts display in the blog archive when searching with no search term.  This is so that I can just press search on the empty input to show all blog results. This default behaviour would update the URL to example.com/?s= and mean that I don't have to create a back to blog button from the search results page.

The "required" attribute is hardcoded into the `render_block_core_search` function where the input markup is created. 

```php
$input_markup = sprintf(
'<input type="search" id="%s" class="wp-block-search__input %s" name="s" value="%s" placeholder="%s" %s required />',
```

## What is your proposed solution?
It would be great to be able to filter the "required" attribute when using the `render_block` filter e.g.:

```php
function example_change_core_search_atts( $block_content, $block, $instance ) {
	if ( $block['blockName'] === 'core/search' ) {
		$block['attrs']['required'] = false; 
	}
	return $block_content;
}
add_filter( 'render_block', 'example_change_core_search_atts', 10, 3 );
```

or directly in the code/markup, e.g. `"required":false`:
```
<!-- wp:search {"label":"Search","placeholder":"Search","buttonText":"Search","buttonPosition":"button-inside","buttonUseIcon":true,"required":false} /-->
```

**Comment by t-hamano** [comment]
Thanks for the suggestion.

Looking at #15600, it appears that the input field in the search block is recommended to have a required attribute. But you could use a hook to remove this attribute, for example, as follows:

```php
add_filter(
	'render_block_core/search',
	function( $block_content ) {
		return str_replace( 'required />', '/>', $block_content );
	}
);
```

**Comment by Web-Assembler** [comment]
Thanks @t-hamano!
