### ISSUE TITLE
Embed Blocks don't render inside Template Parts in Classic Themes

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#47035]
### Description

Using an Embed Block in a Template Part that was added to a Classic Theme fails to embed, and simply outputs the URL.

### Step-by-step reproduction instructions

1. Create a Classic Theme that uses Template Parts.  (Unfortunately, there is not currently a Core theme that meets this criteria, but it's easy to do: https://gutenbergtimes.com/building-a-block-based-header-template-in-a-classic-theme/
2. Add an Embed Block to a Template Part, such as a YouTube video.
3. See that the Embed Block renders as expected in the Site Editor.
4. View the site, and see that the Embed Block fails to embed the video, and instead, simply displays the URL.

### Screenshots, screen recording, code snippet

On the left is the view in the Editor. On the right is the front-end of the site:
![embed](https://user-images.githubusercontent.com/945157/211605472-3b7f8cd2-78d5-43f9-92fb-f903019309d3.png)

### Environment info

WordPress 6.1.1
No Gutenberg Plugin
No plugins at all
Twenty Twenty One with the modifications linked to above to add support for a basic header Template Part

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carlomanf** [comment]
Related: https://core.trac.wordpress.org/ticket/56780

**Comment by Mamaduka** [comment]
Thanks for contributing, @MadtownLems!

The problem has to be resolved in the WP Core. The [56780](https://core.trac.wordpress.org/ticket/56780) ticket is in the 6.2 milestone; I will try to provide the patch in the next few days.

**Comment by MadtownLems** [comment]
I just tested this again in 6.4.1, and my Embed and Shortcode blocks in Template Parts still don't render.

**Comment by ndiego** [comment]
Reopening this issue since it's not resolved.

**Comment by Mamaduka** [comment]
@ndiego, this needs to be resolved in WP core. So I think we can close the issue here.

**Comment by ndiego** [comment]
> this needs to be resolved in WP core. So I think we can close the issue here.

Oh, gotcha. Thanks for the clarification!
