### ISSUE TITLE
Using wp_mail with wp-env

### ISSUE THREAD

**Issue by MikeiLL** [WordPress/gutenberg#47044]
### Description

I want to utilize [wp_mail](https://developer.wordpress.org/reference/functions/wp_mail/) within a `wp-env` dev environment.

Calling it like this:

```
$didthiswork = wp_mail('me@myemail.com', 'test subject', 'test message');
```

Returns false

### Step-by-step reproduction instructions

Here's the confounding thing. Trying to see what's happening in `wp-includes/pluggable.php` in the `wp_mail` function:

```
function wp_mail( $to, $subject, $message, $headers = '', $attachments = array() ) {
    die("I ran"); // never happens
    etc...
```

Am I working with the right file? The following returns as expected

```
$reflFunc = new ReflectionFunction('wp_mail');
echo $reflFunc->getFileName() . ':' . $reflFunc->getStartLine();
// /var/www/html/wp-includes/pluggable.php:174
```

I even tried removing `/var/www/html/wp-includes/pluggable.php` altogether and the site still loads.

There's only ONE docker instance running. I'm running this one on port 3300:

http://localhost:3300

What is going on here?

### Environment info

Mac OS
Chrome

```
{
  "plugins": ["./my-cool-plugin"],
  "config": {
    "WP_DEBUG": true,
    "WP_DEBUG_LOG": true,
    "WP_DEBUG_DISPLAY": true,
    "SCRIPT_DEBUG": true
  },
  "phpVersion": "8.1",
  "mappings": { "profileApp": "./profileApp" },
  "env": {
    "development": {
      "themes": ["./customtheme"]
    },
    "tests": {
      "config": {
        "KEY_1": false
      },
      "port": 3300
    }
  }
}
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MikeiLL** [comment]
Still confounded. 

1. The code changes to my plugin are being "honored".
2. Changes to core WP files are not. Adding a `die()` directive to /var/www/html/index.php` does nothing.

So the actual WP files that are running must be some place else.

**Comment by noahtallen** [comment]
> So the actual WP files that are running must be some place else.

Right, so the core WP files are downloaded to `cd $(npx wp-env install-path)`. You could modify files from there, if you want. They should be mounted in docker, so I'd almost expect a modification from inside docker to apply outside... But if you need dig into WordPress source code, you can also map the source code yourself locally. Just checkout the WordPress repo somewhere nearby, and set "core" to point at it (https://github.com/WordPress/gutenberg/tree/HEAD/packages/env#local-wordpress-develop--current-directory-as-a-plugin)

**Comment by noahtallen** [comment]
I'll close the issue since I don't think this is actionable on our end, but feel free to continue discussing!

**Comment by MikeiLL** [comment]
Thanks @noahtallen.
