### ISSUE TITLE
Navigation Block List View / Page List: Convert to links on any interaction

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#47064]
## What problem does this address?
Currently it's not possible for users to edit the contents of a Page List block inside the Navigation Block List View, using drag and drop, or any other mechanism:
<img width="291" alt="Screenshot 2023-01-11 at 12 52 42" src="https://user-images.githubusercontent.com/275961/211811234-e089514c-3f84-4014-b7e8-641e54b28be8.png">
It would be good to allow users to make edits here, but we need to consider what the impact of that should be.

## What is your proposed solution?
When users try to edit the items inside Page List we should allow them to do so, but first convert the list to a navigation menu, so that it's clear that they aren't editing their pages anymore but are now just editing a static list.

**Comment by richtabor** [comment]
I like this. 

The whole "click edit before you can change something" can be improved, but I do think this gets you there quicker than having to understand that you have to find the right "Edit" button to click on — before you can change the Page List.

**Comment by scruffian** [comment]
The problem is that if you just do the conversion without telling the user what is happening, they will disconnect their page list from the actual pages of their site without realizing. This is why I proposed https://github.com/WordPress/gutenberg/pull/47748.
