### ISSUE TITLE
Navigation: Disable direct insert

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#47063]
## What problem does this address?
When adding blocks to the navigation block, a custom link gets inserted as soon as you press the [+]. This is unexpected.

## What is your proposed solution?
The Navigation Block List View works differently - you are shown a quick inserter. We should consider doing the same thing in the canvas for the Navigation block.

**Comment by richtabor** [comment]
Noting that the Social Links block does not behave like this, albeit having a similar interaction. It opens the quick inserter (as suggested here). 
 
<img width="876" alt="CleanShot 2023-01-11 at 16 56 48@2x" src="https://user-images.githubusercontent.com/1813435/211926406-10b52b88-39cb-4206-acb7-7df7380ec481.png">

**Comment by SaxonF** [comment]
Definitely worth looking at the inserter in a separate project as I do think defaulting to custom link makes sense. Perhaps there is a nice way to unify the two. e.g. pages show up when searching as well as blocks. Either way I think we should insert the link once a page or block has been selected as opposed to "+" click.

**Comment by annezazu** [comment]
Noting that this came up as a piece of feedback in the [nineteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2846) as a light point of confusion:

>The default menu item type displayed is “Custom Link” https://cloudup.com/cm6xn18h_Gd

**Comment by annezazu** [comment]
Noting that this came up as a piece of feedback again in the [twentieth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2023/01/11/fse-program-testing-call-20-find-your-style/#comment-2894):

>Also using the navigation icon, the + sign to add a new menu item does not display a list of options, it just puts in an item named “Custom link” (that I then cannot edit).

**Comment by richtabor** [comment]
> Either way I think we should insert the link once a page or block has been selected as opposed to "+" click.

+1

**Comment by scruffian** [comment]
This would also help surface the home link block as an option for navigation block.

**Comment by getdave** [comment]
I'd like to add some important context here.

The Navigation block is primarily designed for linking to Posts/Pages on your site. Adding other types of blocks is more the 20% use case - sure it's a requirement but 80% of people will just want to add links. 

With that in mind, some time ago regular contributors to the Navigation block elected to have + auto-insert a standard Navigation Link block without requiring you to pick from a list of options each time you just want to add a link.

Imagine - you and trying to build out your Nav for the first time using WordPress. You click the plus icon only to be confronted with a wall of options. Which one do you choose? Page block? Page List? Custom? Not to mention you also see things like Social/Spacer...etc. This would be a very poor experience.

It is for this reason that we auto-insert the Custom Link - I believe that despite some short comings that is the best experience for most users.

That said, that doesn't mean we ought to try and make it easier for more experiened users to pick the specific type of block they wish to use. For this reason @richtabor and I have been working on https://github.com/WordPress/gutenberg/issues/50888 which will allow users to click `Add block` to pick from a list of blocks.

I have a working PR for this in https://github.com/WordPress/gutenberg/pull/57756.

I recommend we close this Issue as the alternative proposed would provide a suboptimal UX.

**Comment by scruffian** [comment]
The main issue with the current experience is what to do in the case where I click the [+] and then change my mind:

https://github.com/WordPress/gutenberg/assets/275961/5c427c25-2329-42bd-a512-b1c255fcaeba

The current experience of automatically inserting a block when you click the [+] is inconsistent with the way the [+] usually works and is also different to how the [+] works in the navigation block list view.

I think any benefits we get from this feature are lost due to:
1. Inconsistency
2. Difficulty of removing the block

> You click the plus icon only to be confronted with a wall of options. Which one do you choose? Page block? Page List? Custom? Not to mention you also see things like Social/Spacer...etc. This would be a very poor experience.

I think users will be used to seeing these options when they click on a [+], since that's what happens in every other case where we want to add a block.
