### ISSUE TITLE
All featured video plugins (that i have tried) crop the thumbnails wrong

### ISSUE THREAD

**Issue by cosmicrookie** [WordPress/gutenberg#47071]
### Description

Some of my posts are about Youtube videos or about my own videos, so i needed a plugin that replaces the featured image with that video. I have found a bunch of plugins that allow this, but all of them have issues with the thumbnails not displaying right on the theme pages. They get cropped and dont resize to the specified dimentions or aspect rations that images do, even though i try to change the setting of the thumbnails from the page editor.

In editor / templates / index
i have tried changing the image dimensions and scale between cover/contain/fill but none of them work as they should. It is the same with several of the plug ins that i have tried, that replace the featured image with a video.

### Step-by-step reproduction instructions

simply install plug ins that replace the featured image with videos (either youtube or selfhosted videos) and display post thumbnails in a column grid like this:

https://cosmic-rookie.com/blog/

only self hosted videos seem to adhere to the thumbnail scaling

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/111892121/211830625-08abb837-49c5-4a67-b6cd-3596fa2cfb62.png)

### Environment info

2023  wordpress

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I checked your site and the plugin you are using is [Really Simple Featured Video](https://fr.wordpress.org/plugins/really-simple-featured-video/)?

Perhaps they are replacing the featured images with custom video sources. So it appears that this is not a gutenberg issue, but one that should be addressed on the plugin side.

**Comment by cosmicrookie** [comment]
Thanks for the message!
As mentioned, the reason I am posting here about this is, that the issue persist even with the 3 different plugins that I have used for this. So I figured the issue can't be with the plug in but with the theme

Den 12. jan. 2023 03.39, fra 03.39, Aki Hamano ***@***.***> skrev:

**Comment by t-hamano** [comment]
WordPress doesn't currently support the video in te post-featured image. I think that is a feature unique to the plugin and not an issue that can be addressed on the Gutenberg or default themes.
You would probably need to customize the plugin or adjust the CSS in your own theme.

**Comment by Thelmachido** [comment]
Thanks, @t-hamano for looking into this. This was previously reported in forums here: https://wordpress.org/support/topic/all-featured-video-plugins-crop-the-thumbnails-wrong/

**Comment by t-hamano** [comment]
I would like to close this issue.

WordPress does not originally support video as a post-featured-image.
Since the functionality discussed in this issue is plugin-driven, I believe the layout and aspect ratio should be controlled by the plugin.

However, as far as I can tell, there is a core ticket as an extension.
https://core.trac.wordpress.org/ticket/41127

@cosmicrookie 
If there is anything I have missed, please feel free to add a comment.
