### ISSUE TITLE
Using Text Column block and 3 cols breaks the block

### ISSUE THREAD

**Issue by lamosty** [WordPress/gutenberg#4709]
I was trying to use the Text Column block to make 3 columns of text. However, the block breaks when you make 3 columns.

<img width="3322" alt="screen shot on 2018-01-27 at 18 29 51" src="https://user-images.githubusercontent.com/4988512/35474554-1cae3c4e-0390-11e8-8dc1-8c617c0ee6f3.png">

**Comment by karmatosed** [comment]
Hmm this is interesting as I can get 3 columns of text. Let's try and recreate though. Are you using the trunk or latest plugin? What browser are you using (not sure it's that but worth a shot)? Are you using any other plugins or themes (just incase).
