### ISSUE TITLE
Query Loop: Incorrect inspector controls when selecting inner blocks

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#47101]
### Description

When a query block is added to a post, page, or template. If you select it then an inner block such as the Post Title, then select the Post Title for a second post within the same Query block, you'll get duplicate controls in the block inspector sidebar.

~Multiple git bisect attempts pointed to the commit for https://github.com/WordPress/gutenberg/pull/46728 (https://github.com/WordPress/gutenberg/commit/f752350ee8da28110811c37edd4fd9b1f5cf4b61)~ Cause was elsewhere.

#### Expected:

Selecting each block would display only the controls for that block.

#### Actual:

Duplicate controls are rendered in the sidebar. It appears that the block clientId isn't distinct 

### Step-by-step reproduction instructions

1. Add a Query block to a post or template
2. Select the Query block
3. Select a post title within the query block
4. Select a different post's title
5. Note the duplicate controls in the block inspector
6. Select the Query block again and note the incorrect panel display in the block inspector as well

#### On Trunk or with https://github.com/WordPress/gutenberg/commit/f752350ee8da28110811c37edd4fd9b1f5cf4b61 checked out

https://user-images.githubusercontent.com/60436221/211999039-070cf8e2-dacb-4540-934a-5076e867ba19.mp4

#### Last Good Commit https://github.com/WordPress/gutenberg/commit/072448e1cb5c92b04dc6d48be4075eff8891cea0

https://user-images.githubusercontent.com/60436221/211999057-58f3909d-8def-4691-a6c6-71c7cfd6d2eb.mp4

### Environment info

- MacOS
- WP 6.2-alpha
- Gutenberg trunk (bisect run twice pointing to commit in issue description)
- Theme: 2023

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
I don't think the linked PR for iframe styles has anything to do with that.. I remember having this issue before, but don't remember how we resolve it. I'll investigate a bit.

I'll open a PR soon :)

**Comment by t-hamano** [comment]
I ran into the same problem and submitted #47135. I used `git bisect` to search for the commit and sure enough, I came across the [f752350](https://github.com/WordPress/gutenberg/commit/f752350ee8da28110811c37edd4fd9b1f5cf4b61) that this issue shows.
