### ISSUE TITLE
Moving text cursor between list items in the Gutenberg editor

### ISSUE THREAD

**Issue by midgold** [WordPress/gutenberg#47108]
## What problem does this address?

The problem is splitting the list items by different blocks.
After the release of update WordPress 6.1 in the “List” type blocks, to move the cursor (text cursor/caret navigation) between the list items, you need to press the down arrow three times on the PC keyboard:
1. The first click is the highlight of the “add” button;
2. The second click selects the block of the list item;
3. The third click is to move the cursor to the text itself.

Watch the screen recording at this link: [https://ibb.co/DDNypzD](https://ibb.co/DDNypzD)

Also, you need to make two taps on the smartphone screen to move the cursor:
1. The first tap do selection of a block of a list item;
2. The second tap do movement the cursor to the text itself.

Watch the screen recording at this link: [https://ibb.co/QHZd7RB](https://ibb.co/QHZd7RB)

This process makes it difficult to edit the text.

## What is your proposed solution?

In the “Paragraph” type blocks, the cursor is moved between the lines of text by one click on the down arrow on the PC keyboard and one tap on the smartphone screen. This allows you to edit the written text immediately. 
Could you please make the text cursor transfer mechanics for “List“ type blocks similar to “Paragraph” type blocks?

**Comment by ntsekouras** [comment]
Thanks for the issue! I couldn't reproduce this..

https://user-images.githubusercontent.com/16275880/212115846-d45f3365-d655-45aa-9f4a-6ce0084a093e.mov

Do you have Gutenberg enabled?

**Comment by midgold** [comment]
I used 13.1-14.1 Gutenberg Version with WordPress 6.1.1. I have installed the last plugin version and the problem has resolved. Thank you!

**Comment by midgold** [comment]
I was in a hurry. The problem still appears on the smartphone. When I tap at center of a list item, the cursor appears in the end of block. And only second tap moves the cursor in the tap area:

https://user-images.githubusercontent.com/60318087/212306426-9c7c9322-3f5d-47f2-9888-c478f90b93cd.mp4

Could you please make moving of cursor directly to first tap area in list item?

**Comment by priethor** [comment]
Let's close this issue, as it needs more info to be actionable. Please feel free to reopen again if there is more information. 🙏
