### ISSUE TITLE
Navigation Block: Disable "Create menu" when a menu is being created

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#47115]
## What problem does this address?
When you click on "create new menu" the button doesn't become disabled. This means you can repeatedly click the button and create many new menus.

## What is your proposed solution?
We should disable this button until the new menu has been created.

**Comment by getdave** [comment]
Btw this keeps regressing!

**Comment by scruffian** [comment]
> Btw this keeps regressing!

We should add a test then!

**Comment by scruffian** [comment]
This has been fixed by #47825
