### ISSUE TITLE
Propagating a custom block to child pages

### ISSUE THREAD

**Issue by paulryanlucero** [WordPress/gutenberg#47111]
For example I have a custom block that displays a banner on top. I want that block to be automatically added to all child pages.

I have been searching around and all I see is displaying the child pages but nothing about this matter.

Is this possible with gutenberg?

**Comment by kathrynwp** [comment]
Hi @paulryanlucero - GitHub is for bug and enhancement requests for the block editor, rather than support questions. Please go ahead and post your question in the Gutenberg forum and someone will be glad to give you a hand there. Cheers!

https://wordpress.org/support/plugin/gutenberg/
