### ISSUE TITLE
Query Loop: Small image and title pattern has incorrect spacing

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#47129]
This came up as part of the [nineteenth call for testing for the FSE Outreach Program:](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2846)

>A Query Loop pattern was missing a space: https://d.pr/i/a6F2dG

<img width="828" alt="Markup 2022-12-27 at 15 06 06" src="https://user-images.githubusercontent.com/26996883/212223014-18e8718a-c749-4392-b1eb-250ba13a21ce.png">

I could replicate this with Gutenberg 14.9.1 with WP 6.1.1.

**Comment by ntsekouras** [comment]
Which patterns is this? Is it a core one or a theme one? I didn't find it with latest trunk and 2022.

**Comment by annezazu** [comment]
It's one of the bundled Query Loop patterns available for all themes.

**Comment by t-hamano** [comment]
I was able to reproduce it. As the title of the issue says, it is a "Small image and title" pattern 😅

I could find nothing unnatural about the pattern's markup, but its behavior is a bit odd.: clicking within the inserted pattern toggles the position of the space. The following is the behavior in Twenty Twenty Tree:

https://user-images.githubusercontent.com/54422211/212817789-517efc79-2ff4-4d2f-b987-a2db65e99530.mp4

In Twenty Tweny One the spaces are displayed correctly but flash when clicked:

https://user-images.githubusercontent.com/54422211/212818007-7e98eed5-e366-4bcf-9c4c-49ce9f7d74e3.mp4

**Comment by t-hamano** [comment]
From my research, this problem may not be limited to a specific pattern. For example, the following simple query loop with only featured image will also result in unnatural spaces:

```html
<!-- wp:query {"queryId":7,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false}} -->
<div class="wp-block-query"><!-- wp:post-template -->
<!-- wp:post-featured-image {"width":"200px"} /-->
<!-- /wp:post-template --></div>
<!-- /wp:query -->
```

![simple-query](https://user-images.githubusercontent.com/54422211/212822861-049da158-ca1e-48b5-8d57-5e47a7535a5d.png)

Furthermore, if you look at the rendered HTML, you will see that the number of `li` elements and some of their attributes are different (Markups are simplified):

```html
<ul class="wp-block-post-template" >
  <li class="wp-block-post block-editor-block-list__layout is-layout-flow" data-is-drop-zone="true">
    <figure class="wp-block-post-featured-image"><img></figure>
  </li>
  <li class="wp-block-post block-editor-block-preview__live-content components-disabled" role="button" style="display: none;">
    <figure class="wp-block-post-featured-image"><img></figure>
  </li>
  <li class="wp-block-post block-editor-block-preview__live-content components-disabled" role="button">
    <figure class="wp-block-post-featured-image"><img></figure>
  </li>
  <li class="wp-block-post block-editor-block-preview__live-content components-disabled" role="button">
    <figure class="wp-block-post-featured-image"><img></figure>
  </li>
</ul>
```

I don't have in-depth knowledge of the query loop block, so if anyone has any tips on this issue, please advise 🙏
