### ISSUE TITLE
Query Loop: Action duplicates the settings of the block inside

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#47135]
### Description

After inserting a query loop block, selecting a block in the loop will duplicate the block toolbar sidebar settings. This problem is not reproduced when the Gutenberg plugin is disabled.

I believe this issue should be treated as a high priority.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/212263067-d472f433-22a8-4d40-a5d9-892c64a69be8.mp4

### Environment info

- WordPress Version: 6.2-alpha-55060
- Gutenberg Version: 15.0.0-rc.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
It's resolved with https://github.com/WordPress/gutenberg/pull/47110, no?

**Comment by t-hamano** [comment]
Oh, I have confirmed that it does not reproduce on the latest trunk. Sorry for the trouble 🙏
