### ISSUE TITLE
Improve custom block style presentation in the block editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#47146]
## What problem does this address?

Now that custom block styles shows as selectable style variations in global styles,
it feels like the presentation in the block editor is dated and could be improved.

For example, the label of the panel in the block editor is Styles, which is the same as the first tab in the settings sidebar:

![The block settings sidebar of the button block, with a tab and a panel called Styles](https://user-images.githubusercontent.com/7422055/212337480-d8b353cf-b358-429f-8134-3d743c20244a.png)

While in global styles they are labeled "Style variations". I think we need to use the same name across the interface.
![The button block in the global styles, with a panel of style variations below the settings.](https://user-images.githubusercontent.com/7422055/212337789-3a24c67c-05ef-460a-aece-42be781bd312.png)

Also kindly note that in the styles sidebar a single variation is presented on one full row and showing the full name,
while in the block editor, the names are often truncated and difficult to read because of the short width of the button,
please see https://github.com/WordPress/gutenberg/issues/40331

I understand that not all will agree, because it takes up a lot of space, and it might be difficult to find a middle way,
but I much prefer the preview that is in the panel, over the pop out used in the editor because the pop out only shows on hover and is flickery.
![Image block style variation is displayed in a separate modal outside the panel when hovering over the button that lets you select the variation](https://user-images.githubusercontent.com/7422055/212339723-2a7bdc65-e1d7-48ee-bcd4-ba6e9b14ad0a.png)

**Comment by carolinan** [comment]
Ah, and also the tooltip that shows when you hover over the button that lets you select the style seems unnecessary since the text is already visible. We could remove this duplication.

**Comment by ghost** [comment]
> Ah, and also the tooltip that shows when you hover over the button that lets you select the style seems unnecessary since the text is already visible. We could remove this duplication.

We could remove this duplication... when a style name is fully readable.
When style names are truncated, the tooltip is necessary. •́  ‿ ,•̀

**Comment by carolinan** [comment]
So let's give them the space they need 😃
