### ISSUE TITLE
Dead (or bad) code in gutenberg_meta_box_post_form_hidden_fields()

### ISSUE THREAD

**Issue by tfrommen** [WordPress/gutenberg#4714]
## Issue Overview
Maybe I'm missing something, but as far as I can see, there is either dead or at least bad (as in faulty) code in the `gutenberg_meta_box_post_form_hidden_fields` function to be found.

The [`active_post_lock` variable](https://github.com/WordPress/gutenberg/blob/f2bbf5f48aefda63e00b40ea8362a10934dacca9/lib/meta-box-partial-page.php#L365-L367) is undefined, because it is neither actively defined, nor imported from the global scope, nor do I see some other source of definition (e.g., the not-to-be-used `extract` function).

**Comment by youknowriad** [comment]
Good catch, should probably be deleted
