### ISSUE TITLE
useInBetweenInserter classList is undefined in Firefox

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#47165]
### Description

In Firefox, mousing around the Site Editor will occasionally print this error in the console.

```
Uncaught TypeError: event.target.classList is undefined
    onMouseMove
    useInBetweenInserter
    useRefEffect
    assignRef
    useMergeRefs
```

### Step-by-step reproduction instructions

1. Using Firefox go to the Site Editor
2. Mouse around blocks that have text.

It looks like this happens when a text node is moused over instead of a dom element which does not have a `classList`.

```
target: #text
assignedSlot: null
baseURI: "..."​​​
childNodes: NodeList []​​​
data: "Last Name"​​​
firstChild: null​​​
isConnected: true​​​
lastChild: null​​​
length: 9​​​
nextElementSibling: null​​​
nextSibling: null​​​
nodeName: "#text"​​​
nodeType: 3​​​
nodeValue: "Last Name"​​​
ownerDocument: HTMLDocument ...
parentElement: span​​​
parentNode: span​​​
previousElementSibling: null​​​
previousSibling: null​​​
textContent: "Last Name"​​​
wholeText: "Last Name"
```

### Environment info

- WordPress 6.1
- Gutenberg 14.9.1
- Firefox 108.0.1
- macOS 13.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I was able to reproduce this problem.
For some reason, FireFox sometimes detects text nodes as event targets, which appears to be the cause of the console error.

https://user-images.githubusercontent.com/54422211/212532643-30bfb81b-3d57-49b8-abd2-d7bce80d1428.mp4
