### ISSUE TITLE
Clearer controls for copying and pasting styles

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#47164]
## What problem does this address?

Now that we have the functionality in place for [copying and pasting block styles](https://github.com/WordPress/gutenberg/pull/45477), let's follow-up with some approaches for making the functionality more apparent. (Related: https://github.com/WordPress/gutenberg/pull/45477#issuecomment-1373039847)

In its current form, it is not clear that one can copy the current block's style. "Copy block" should continue to function as it does today, where it copies block and styles. 

## What is your proposed solution?

Here are some rough concepts based on the discussion on the original PR to get us moving. 

### Current: 

Here's the current implementation for reference. The "Copy block" control functions as both copying the block as as whole, or styles, based on the paste follow-up action.

<img width="398" alt="CleanShot 2023-01-14 at 19 35 48@2x" src="https://user-images.githubusercontent.com/1813435/212503205-e1438428-82fd-481b-84d6-022f13b94d7c.png">

### Suggestion 1:

Add a section within the popover, with Copy styles and Paste styles in it directly. It could go at the bottom of the popover instead.

<img width="395" alt="CleanShot 2023-01-14 at 19 36 38@2x" src="https://user-images.githubusercontent.com/1813435/212503214-05bd2546-bd22-43f2-9751-4254e689b4f0.png">

### Suggestion 2: 

Add a popover interaction. If we did this, we can afford to have both copy and paste, for block (which is the entire block, as-is - including styles) or just styles. 

<img width="653" alt="CleanShot 2023-01-14 at 19 37 29@2x" src="https://user-images.githubusercontent.com/1813435/212503233-340a488c-1276-4bd9-834b-3f0924ee6198.png">

**Comment by jasmussen** [comment]
I agree, there are some slightly similar iterations in the original issue: https://github.com/WordPress/gutenberg/issues/44418

**Comment by ndiego** [comment]
+1 on this. The functionality is insanely useful, but it's not very clear that "Copy block" then allows you to "Paste Styles".

I wonder if simply removing "block" from "Copy block" helps. We don't have "block" in the "Duplicate" label.

**Comment by richtabor** [comment]
> I agree, there are some slightly similar iterations in the original issue: https://github.com/WordPress/gutenberg/issues/44418

@jasmussen @jameskoster Which direction are you leaning?

**Comment by jasmussen** [comment]
I prefer the flyout for compactness, but that requires a new flyout component structure which is likely non trivial to build, so in lieu of that, grouping with a separator can work in the mean time.

**Comment by jameskoster** [comment]
+1 for the flyout. I wonder if we could streamline a bit if we grouped by action, IE:

```
COPY
Block
Styles

PASTE
Block
Styles
```

**Comment by richtabor** [comment]
> a new flyout component structure which is likely non trivial to build

Agreed. 

I'm good if we roll with adding a grouped section for "Copy styles" and "Paste styles" for now, and iterate towards a flyout later. 

<img width="395" alt="CleanShot 2023-01-14 at 19 36 38@2x" src="https://user-images.githubusercontent.com/1813435/212503214-05bd2546-bd22-43f2-9751-4254e689b4f0.png">
