### ISSUE TITLE
Checkbox Control Help. Thanks!

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#4717]
Just need help on how to your the checkbox field. I'm using 

```
el(
				        CheckboxControl,
				        {
				            label: i18n.__( 'Desktop' ),
				            key: 'unique_key',
				            value: "1",
				            onChange: function( new_val ) {
				            	//need help here
				            },
				        },
			    	)
```
and I need help on how to set the checked value. Thanks!

**Comment by aduth** [comment]
You can refer to the [React Forms documentation](https://reactjs.org/docs/forms.html), which will apply the same for `el`. Specifically, you will want to use `checked` (a boolean value), not `value`, and your `onChange` handler should either [set an attribute](https://wordpress.org/gutenberg/handbook/block-api/attributes/) if it needs to be serialized within post content, or as a state value using the [`wp.components.withState` helper](https://github.com/WordPress/gutenberg/tree/master/components/higher-order/with-state) if the value only needs to be stored temporarily while the user is editing.

**Comment by aduth** [comment]
You can refer to the [React Forms documentation](https://reactjs.org/docs/forms.html), which will apply the same for `el`. Specifically, you will want to use `checked` (a boolean value), not `value`, and your `onChange` handler should either [set an attribute](https://wordpress.org/gutenberg/handbook/block-api/attributes/) if it needs to be serialized within post content, or as a state value using the [`wp.components.withState` helper](https://github.com/WordPress/gutenberg/tree/master/components/higher-order/with-state) if the value only needs to be stored temporarily while the user is editing.

**Comment by phpbits** [comment]
@aduth do you have docs for the fields? It will be easier to check the attributes available. Thanks!

**Comment by phpbits** [comment]
@aduth It's probably similar to this issue : https://github.com/WordPress/gutenberg/issues/4613 . And it's still open. Thanks!

**Comment by phpbits** [comment]
Figured it out :)` event.target.checked` is what I'm looking for.

**Comment by aduth** [comment]
@phpbits You're correct this is related to #4613 . After #4720 is merged, the `ToggleControl` component will pass a boolean to `onChange`, not the event object.

**Comment by phpbits** [comment]
Thanks @aduth ! Would you mind checking this other issue I've posted : https://github.com/WordPress/gutenberg/issues/4759 . Thanks!

**Comment by phpbits** [comment]
@aduth Thank you very much for checking my other post. Would you mind checking this one too : https://github.com/WordPress/gutenberg/issues/4723#issuecomment-361429364 . I can't seem to get a reply. Thanks!
