### ISSUE TITLE
Checking of block type names is incorrect (at least the feedback).

### ISSUE THREAD

**Issue by tfrommen** [WordPress/gutenberg#4718]
## Issue Overview
Custom block types must have a name that follows specific rules. It must have a namespace part (separated by a `/`), and can only contain lowercase alphanumeric characters and dashes (and a single slash, obviously).

If you put an uppercase character in a name, you get according feedback:

> Block type names must not contain uppercase characters.

*But* if you put any special character in a name, you get this confusing feedback:

> Block type names must contain a namespace prefix. Example: `my-plugin/my-custom-block-type`

## Steps to Reproduce (for bugs)
1. Call `WP_Block_Type_Registry::register( 'awesome/block!' )`.

## Expected Behavior
Get non-confusing feedback.

## Current Behavior
Feedback is only about namespace, which is there in my example.

## Possible Solution
There a several possible solutions:
* Add another check for special characters.
* Include special characters in the check for uppercase characters.
* Only have a single check that acts on the exact pattern, and outputs a single feedback message including all there is.

That all-for-one message could be something like this:

> Block type names must contain a namespace prefix, and can only include lowercase alphanumeric characters and dashes, and a single forward slash as namespace separator. Example: my-plugin/my-custom-block-type

Yes, this is verbose. But this also means that people know what's up.

**Comment by gziolo** [comment]
@aduth, what if we would move all those basic validations for blocks you register to PHP like:
- block name
- block category
- attributes
- supports

On JS side we would still have to validate `edit` and `save` fields and everything that needs JS code. Not sure about `title`, `description` or `keywords` though.

This would greatly simplify filtering blocks based on their name or category applied.

My only concern here is that it could negatively impact the size of the serialized JS object with block data that we expose for the JS code.

**Comment by aduth** [comment]
>@aduth, what if we would move all those basic validations for blocks you register to PHP like:

This is probably something we want to do with #2751, yes.

**Comment by gziolo** [comment]
Awesome, looking forward to see how #2751 will evolve.

**Comment by aduth** [comment]
Re-labelling as enhancement since this is more about improved messaging.

**Comment by ntsekouras** [comment]
This has been fixed here: https://github.com/WordPress/gutenberg/pull/3521

Current message is: `Block names must contain a namespace prefix, include only lowercase alphanumeric characters or dashes, and start with a letter. Example: my-plugin/my-custom-block`.

**Comment by mizukimadness** [comment]
I just got this error from pasting the wrong file path...

**Comment by jeremyHixon** [comment]
Same as above. Received the error because of an incorrect path to the build directory. Not ideal.

**Comment by olsonpm** [comment]
I got this error when trying to import an image via wp-scripts.  I don't fully understand the php involved in that however it's clear this error message should be more broad e.g. `An error occurred registering wordpress blocks`

**Comment by rtpHarry** [comment]
I guess this should be its own issue, but I don't have time to read up on the submit process right now.

This error message appears when the block.json is not found (`Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type`). 

I made a shell script to package up my plugin and accidentally filtered out .json files.

It took me a while to figure out that the block.json wasn't in the release version of the plugin, and that's what this error message was actually referring to.

**Comment by gareins** [comment]
I am in the process of learning wordpress by migrating an old design to current wp best practices and this error is useless. To me it just means that the block still has errors and that the issue is on the backend side. Some more verbose error reporting for developing blocks for a newbie would go a long way...
