### ISSUE TITLE
Site Editor: Blocks can be manipulated in browse mode

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#47190]
### Description

In the FireFox browser, even if the site editor is in browse mode, it is possible to manipulate blocks unintentionally.
We can change text, insert blocks, delete blocks, etc.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/212702388-2880d054-aa29-46ad-be75-dd90d60152b3.mp4

**Comment by t-hamano** [comment]
My guess is that in FireFox, the `inert` attribute that disables the operation doesn't appear to be functioning properly. The reason may be that the `inert-polyfill.js` is not loaded into the iframe instance.

**Comment by youknowriad** [comment]
Yeah weird, I'm pretty sure I tested firefox when I originally added the "inert" attribute but maybe some things changed.

**Comment by t-hamano** [comment]
Somehow, when the inert attribute is added to an element in the iframe, it doesn't seem to work correctly in Firefox.

In the browse mode of the site editor, the problem can be solved by making the following changes:

```diff
diff --git a/packages/block-editor/src/components/iframe/index.js b/packages/block-editor/src/components/iframe/index.js
index f9d7b96297..ffff183509 100644
--- a/packages/block-editor/src/components/iframe/index.js
+++ b/packages/block-editor/src/components/iframe/index.js
@@ -251,6 +251,7 @@ function Iframe( {
                                // content.
                                srcDoc={ srcDoc }
                                title={ __( 'Editor canvas' ) }
+                               inert={ readonly ? 'true' : undefined }
                        >
                                { iframeDocument &&
                                        createPortal(
@@ -284,7 +285,6 @@ function Iframe( {
                                                                        marginTop: frameSize,
                                                                        transform: `scale( ${ scale } )`,
                                                                } }
-                                                               inert={ readonly ? 'true' : undefined }
                                                        >
                                                                { contentResizeListener }
                                                                <StyleProvider document={ iframeDocument }>
```

However, there are cases, such as [the table of contents block](https://github.com/WordPress/gutenberg/blob/e54c571ea424cb9f5dcccf46721df137bddcef8d/packages/block-library/src/table-of-contents/edit.js#L296) in edit mode, where you want to disable only certain elements within an iframe. So we may need to investigate the root cause.

**Comment by youknowriad** [comment]
I guess you're maybe right that it comes down to loading the polyfill inside the iframe in this case. The reason I moved the attribute inside is because of the "scrolling". In other words, we should still be able to scroll the template even if disabled. That may be impacted by this PR though #47004 which may allow us to move the inert back outside the iframe.

**Comment by t-hamano** [comment]
From what I have been able to find out, it appears that the inert polyfill doesnot take into account the elements inside the iframe.
We might need to add a polyfill script inside the iframe.

`index.html`

```html
<!DOCTYPE html>
<html>
<body>

<!-- This Polyfill does not appear to be applied within an iframe in FireFox. -->
<script src="https://unpkg.com/wicg-inert"></script>

<iframe src="frame.html"></iframe>
</body>
</html>
```

`frame.html`

```html
<!DOCTYPE html>
<html>
<body inert>

<!-- Need to inject polyfill in iframe -->
<script src="https://unpkg.com/wicg-inert"></script>

<input type="text">
</body>
</html>
```

**Comment by youknowriad** [comment]
yes, that sounds like a decent approach.
