### ISSUE TITLE
Turning gallery to image makes it half the size

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4719]
Steps to recreate:

- Make a new post
- Give it a title
- Add a gallery block
- Convert to image

![2018-01-28 at 14 43](https://user-images.githubusercontent.com/253067/35483425-ac820af4-0439-11e8-94ae-114f76e451a5.png)

The image should stay the full width and not become half size.

**Comment by noisysocks** [comment]
Having trouble replicating this. What browser/platform are you using?

**Comment by karmatosed** [comment]
I can't recreate either! Well that's erm.. yay it's fixed :) I'm going to cautiously glare at my screen as unsure how but let's close and pass on.
