### ISSUE TITLE
Template part doesn't appear in "Areas" UI if not placed at the root level

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#47213]
<img src="https://user-images.githubusercontent.com/1813435/212839413-3f9f1447-0e46-40b6-9ec9-df765aabd28a.png">

In the screenshot above, the Header template part is placed inside a Group. Notice how it doesn't appear in the "Areas" UI in the Inspector.

**Comment by andrewserong** [comment]
I've opened a tentative fix for this over in: https://github.com/WordPress/gutenberg/pull/47232 — it works, but I think there's a more performant way to do it / there could potentially be a better way to iterate over the blocks, so I'll continue on with it tomorrow.

Thanks for opening the issue!

**Comment by andrewserong** [comment]
https://github.com/WordPress/gutenberg/pull/47232 is ready for review now.
