### ISSUE TITLE
Add confirmation step when deleting a Template

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#47225]
## What problem does this address?
This is a duplicate of https://github.com/WordPress/gutenberg/issues/39124 for **deleting** a Template.
There is currently no undo affordance.
Also, there is currently no confirmation step when deleting a Template, which I propose.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/17861443/213032226-ada80559-9db9-428c-96c6-c486110f8ecd.png">

## What is your proposed solution?
Option a) A modal where the user is asked, if they are sure they want to (permanently?) delete the Template. 
Option b) Add Undo Notification.
Option c) Move the Template to a Trash/Bin/Archive section from where the user then can permanently delete the Template.

**Comment by richtabor** [comment]
Agreed, its a bit destructive to not have a method for undoing. 

There should probably be an undo action added to the snackbar that appears when deleting the template.  

<img width="401" alt="CleanShot 2023-04-28 at 18 02 30" src="https://user-images.githubusercontent.com/1813435/235197565-be5d95b2-6aed-4386-a492-33d5c7f6f9d1.png">

**Comment by jameskoster** [comment]
The following modal appears if you delete a page in the site editor:

<img src="https://user-images.githubusercontent.com/846565/246085795-208ae7d3-31e1-4a04-8158-8581f68f9aac.png">

In the interest of consistency it might make most sense to re-use that pattern?

A undo affordance would be nice to have if technically trivial to implement. But I don't know that it's 100% necessary – the modal alone probably gives ample opportunity to cancel the operation? For reference, deleting a page doesn't currently offer an undo option.
