### ISSUE TITLE
Browse Mode: Add theme previews

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#47228]
## What problem does this address?
There is currently no mechanism to preview block themes. Classic themes can be previewed in the Customizer, but block themes don't use the Customizer. When selecting a theme it would be great if I could preview my content in the new theme before I switch.

## What is your proposed solution?
We could show themes inside the "Browse mode" of the Site Editor:
<img width="1512" alt="Screenshot 2023-01-18 at 11 52 11" src="https://user-images.githubusercontent.com/275961/213081141-1d4ce27f-40eb-41e9-88af-9e962e6dea0f.png">

Instead of theme screeshots, each of these thumbnails would be a preview of the site content with the new theme loaded.

If one of previews is selected the user should be able to edit the site in this previewed state. The theme switch would not happen until the changes are saved:

<img width="1512" alt="Screenshot 2023-01-18 at 12 08 54" src="https://user-images.githubusercontent.com/275961/213081532-d57a2bb7-9651-4360-bc48-94d428e60ede.png">

**Comment by annezazu** [comment]
Noting these two related issues: https://github.com/WordPress/gutenberg/issues/37201 & https://core.trac.wordpress.org/ticket/54578

**Comment by priethor** [comment]
Implemented in #50030
