### ISSUE TITLE
Block Variations: Details not unique for dynamic blocks once inserted

### ISSUE THREAD

**Issue by brettsmason** [WordPress/gutenberg#47237]
### Description

When using the `variations` key in `block.json` to register a variation, I expected a unique title, icon and description when inserting my variation. However, whilst this is the case when selecting the block from the inserter, once its inserted it uses the main blocks details everywhere.

[This issue](https://github.com/WordPress/gutenberg/discussions/43835) sounded very similar, however the fix didn't work.

### Step-by-step reproduction instructions

1. A barebones dynamic block has been created [here](https://github.com/brettsmason/gutenberg-example-dynamic-block-variation) using the command `npx @wordpress/create-block --variant dynamic` and using the default response. This repo can be used to test it.
2. Install the plugin
3. Insert the dynamic block on to the page.
4. In the inserter it should have the correct details, but when inserted it will use the main blocks details

### Screenshots, screen recording, code snippet

Screen recording demonstrating the issue: https://share.cleanshot.com/rlrWRpKP

### Environment info

- WordPress 6.1.1
- Twenty-Twenty Two theme
- No plugins installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
👋 - Have you used the [`isActive` API](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/)?

**Comment by brettsmason** [comment]
@ntsekouras yep I have, [see the example repo](https://github.com/brettsmason/gutenberg-example-dynamic-block-variation/blob/main/src/block.json#L27) . Based on the answer from the other issue I linked to.

**Comment by ntsekouras** [comment]
It seems there is a problem with the variation you're using and not with GB APIs. Your block doesn't declare any `attributes` in [block.json](https://github.com/brettsmason/gutenberg-example-dynamic-block-variation/blob/main/src/block.json)(top level props) but you do in your variation, that makes both `attributes` and `isActive` ineffective for your variation.

**Comment by brettsmason** [comment]
Thanks for the feedback. I investigated some more and was now able to get the variation to keep its title, icon and description when inserted 👍

I still feel like this is either a bug (because the block showed up in the inserter still), or the documentation could be clearer though. Surely if the variation was registering as not active (because of my lack of attributes), then the block shouldn't show in the inserter in the first place?

**Comment by ntsekouras** [comment]
It showed in the inserter because you register the block and it would still be shown if you hadn't the variations prop. I think we can close this issue, but if you have a suggestion about improving the docs in `registration` of blocks or the variations, please create a new specific issue for this. Thanks @brettsmason !

**Comment by t-hamano** [comment]
@brettsmason 
For variations, the following documents may be helpful.

- [Metadata in block.json | Block Editor Handbook](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#variations)
- [Variations | Block Editor Handbook](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/) (You can check the explanation about `isActive` property)

**Comment by brettsmason** [comment]
@t-hamano I had read both of those but thanks.
As the property is marked as optional, I had assumed that the variation would still show up (and it did).
I'll close this, but it still feels odd to me that you can register a variation and make it show in the inserter, but when inserted it changea to the main block - an odd user experience (intended or not).

**Comment by t-hamano** [comment]
> but it still feels odd to me that you can register a variation and make it show in the inserter, but when inserted it changea to the main block - an odd user experience (intended or not).

Variations will only have the same namespace as the main block. And once inserted, I believe it is precisely `isActive`'s role to determine if the block is a variation and display the appropriate title and description. If the documentation is confusing, we gladly welcome suggestions for improvement.
