### ISSUE TITLE
Calling render_callback() without register_block_type?

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#4723]
Checking https://github.com/WordPress/gutenberg/blob/a41173b0be06c5c8c8e397bfb7b30604099e3182/lib/blocks.php and there seems to be no block render_callback option without register_block_type. Will there be any filters available? It will be easier rather that removing the `the_content` filter and override it with a new one. Thanks!

**Comment by danielbachhuber** [comment]
Hi @phpbits,

Could you share more detail on what you're trying to do?

**Comment by phpbits** [comment]
@danielbachhuber I'm trying to hide several specific blocks and there's no filter/callback option. I did it by using `remove_filter( 'the_content', 'do_blocks', 9 ); ` then copy the `do_blocks()` and adding it again. Then add my conditions on the foreach loop per block. 

Would be really helpful and better if you have filters and actions available there. Thanks!

**Comment by phpbits** [comment]
@danielbachhuber The`do_blocks()` seems been changed : https://github.com/WordPress/gutenberg/blob/master/lib/blocks.php. Can you please add a filter foreach block before adding them to the content? Something like this on the previous code :

`$content_after_blocks .= apply_filters( 'do_content_block', gutenberg_render_block( $block ), $block );`

Thanks!

**Comment by aduth** [comment]
Relevant exchange at https://github.com/WordPress/gutenberg/pull/4591#issuecomment-362151282

**Comment by chrisvanpatten** [comment]
Seconding this — additional filters on block render would be super valuable. For instance right now I'm trying to change the structure of image tags to modify the `sizes` and `srcset` attributes and have to resort to an ugly domdoc solution because there's no easy way to filter the markup at runtime.

**Comment by mcsf** [comment]
@chrisvanpatten, I think it's best to follow #2751, as its resolution should provide an overarching solution for this.
