### ISSUE TITLE
Sidebar Panel stops displaying items correctly when the nesting is too large

### ISSUE THREAD

**Issue by FalkoJoseph** [WordPress/gutenberg#47245]
### Description

I've built a rather complex layout using group blocks, which tend to require a fair amount of nesting.

When the amount of nested elements is too deep, the UI becomes clunky and you also can't access the context menu dots from the sidebar anymore. 

So you can't select the blocks inside these nested elements.

A very simple solution would be to allow horizontal scrolling.

### Step-by-step reproduction instructions

1. Go to the sidebar panel which shows all of the elements on page
2. Nest a couple of elements 9 levels deep (e.g. the group block)
3. Try accessing the context menu (the three dots) from any element

### Screenshots, screen recording, code snippet

<img width="189" alt="Scherm­afbeelding 2023-01-18 om 14 31 16" src="https://user-images.githubusercontent.com/556086/213184719-f28bcb02-3183-4921-bcf8-7c1542d47c93.png">

### Environment info

- WordPress 6.1.1
- Gutenberg 15.0.0-rc.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I can confirm. It appears that once you get to 7 levels deep, the options icon stops appearing on any list item. Once you collapse down to 6 levels, the options icon reappears. 

![list-view-bug](https://user-images.githubusercontent.com/4832319/213218069-cfc6a164-46c9-488e-b96a-9656a835d726.gif)

**Comment by FalkoJoseph** [comment]
> I can confirm. It appears that once you get to 7 levels deep, the options icon stops appearing on any list item. Once you collapse down to 6 levels, the options icon reappears.
> 
> ![list-view-bug](https://user-images.githubusercontent.com/4832319/213218069-cfc6a164-46c9-488e-b96a-9656a835d726.gif) [ ![list-view-bug](https://user-images.githubusercontent.com/4832319/213218069-cfc6a164-46c9-488e-b96a-9656a835d726.gif) ](https://user-images.githubusercontent.com/4832319/213218069-cfc6a164-46c9-488e-b96a-9656a835d726.gif) [ ](https://user-images.githubusercontent.com/4832319/213218069-cfc6a164-46c9-488e-b96a-9656a835d726.gif)

Yeah, this one's pretty crucial as it blocks the ability for clients to edit content on their website. 🤔

For now I'll try making a patch in CSS. But whoever fixes this I'll give a free beer! 😁

**Comment by ndiego** [comment]
I have confirmed the above in 6.2 Beta 1.

**Comment by richtabor** [comment]
Yea, there should be a way to see the tree of list items fully. 

Either horizontal scrolling (don’t love) or maybe even a resizable list view (not for 6.2, but later — maybe).

**Comment by annezazu** [comment]
This is a duplicate issue: https://github.com/WordPress/gutenberg/issues/44603 I am going to close this out and remove it from 6.2 as I don't see this being addressed in time. If others disagree, just say so! Happy to discuss and reconsider.
