### ISSUE TITLE
iOS Quote and Pull Quote blocks render typography discrepancies

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#47263]
## Description

When adding Quote and Pull Quote blocks on iOS, there are several typographic issues rendered: 

* Quote & Pull Quote: unexpected `p` tags within citation line breaks, incorrect text size
* Pull Quote: Misaligned text

The incorrect text size appears to have surfaced in the WP 21.4 release. The unexpected `p` tags and misalignment appear to have surfaced in the pending WP 21.5 release.  

The incorrect text size may only surface for block themes where custom styles/typography is supported.

## Step-by-step reproduction instructions

1. Add Quote/Pull quote block. 
2. Add multiple lines of text in the quote body. 
3. Add multiline lines of text in the citation. 

## Expected behaviour

Correct text size and alignment is displayed. `p` tags are not inserted for the citation field. 

## Actual behaviour

Incorrect text size and alignment is displayed. `p` tags are inserted for the citation field. 

## Screenshots or screen recording (optional)

<details><summary>21.3</summary>

https://user-images.githubusercontent.com/438664/213334182-7edaffe6-0bd1-4c1c-ad3d-f2fab0c1feae.MP4

</details>

<details><summary>21.4</summary>

https://user-images.githubusercontent.com/438664/213334186-db4583de-763a-4034-b48b-048e52960a0f.MP4

</details>

<details><summary>21.5</summary>

https://user-images.githubusercontent.com/438664/213334191-c7a2a149-d712-4e89-8daf-e7e59e8704f7.MP4

</details>

## WordPress information
- WordPress version:  6.1.1
- Gutenberg version:  14.9.1
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  No, Geologist. 

## Device information
- Device:  iPhone SE
- Operating system:  iOS 16.1
- WordPress app version:  21.5

**Comment by fluiddot** [comment]
> Quote & Pull Quote: unexpected p tags within citation line breaks

I investigated this issue further and seems that might be related to Aztec. When the Quote block is created, the content of the citation element is an empty string. However, when focusing on the Citation text input, the text is updated with the value `<p></p>` 🤔 .

As a side note, I also noticed that this issue can't be reproduced when connecting the Chrome debugger 🙃 .

**Comment by fluiddot** [comment]
I tried to debug the issue and noticed the following difference in Gutenberg Mobile `trunk` before and after [this PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5391) was merged:

**Before:**
<img width="715" alt="Screenshot 2023-01-19 at 12 24 16" src="https://user-images.githubusercontent.com/14905380/213431512-98268db8-383c-4b18-9620-ca0fbf92d72e.png">

**After:**
<img width="698" alt="Screenshot 2023-01-19 at 12 23 35" src="https://user-images.githubusercontent.com/14905380/213431565-8e1284b8-6ae6-4ab7-a589-87112b488124.png">

**NOTE:** The logs generated after focusing the text input were produced after typing the character `a`.

As you can see, there's an extra `onSelectionChangeFromAztec` event triggered when focusing the Citation text input that is setting the content value to `<p></p>`.
