### ISSUE TITLE
Move page list item offcanvas navigation lock icons to the page list

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#47268]
## What problem does this address?

Currently each page list item shows a lock icon, to indicate the item cannot be manipulated within the navigation list view. Instead we can reduce the cognitive load here by moving the lock icons to the parent page list block. 

## What is your proposed solution?

- [ ] In the offcanvas view, move the individual lock icons from the page list item blocks to the page list block

### Visual 

Note that the left-most block iconography in this visual is derived from #47267. 

<img width="736" alt="CleanShot 2023-01-19 at 11 14 22@2x" src="https://user-images.githubusercontent.com/1813435/213347133-2727c72a-cb72-41be-9ec6-ffea895764b6.png">

**Comment by scruffian** [comment]
One concern I have with this approach is that it suggest that the block itself is locked which is not true - only the content is. Is there a way to make that distinction visually, or is that overkill?

**Comment by richtabor** [comment]
> Is there a way to make that distinction visually, or is that overkill?

I think overkill. But perhaps this could become obsolete if we "unlock" it per se https://github.com/WordPress/gutenberg/issues/48034

**Comment by ndiego** [comment]
Just checking in. Are we still aiming to get this resolved for 6.2?

**Comment by scruffian** [comment]
I don't think so, no.

**Comment by ndiego** [comment]
Thanks @scruffian, I will punt to 6.3.

**Comment by ndiego** [comment]
Hey @scruffian @richtabor, this issue was ported over to the [6.3 Project Board](https://github.com/orgs/WordPress/projects/103/views/1) after being punted from 6.2. It doesn't look like any further progress has been made. Given that 6.3 Beta 1 is two weeks away, any objections to me removing it from the 6.3 board?

**Comment by scruffian** [comment]
@ndiego fine with me

**Comment by richtabor** [comment]
We can just close this, as the lock icons aren't there at all anymore :) 

<img width="280" alt="CleanShot 2023-06-14 at 16 26 31" src="https://github.com/WordPress/gutenberg/assets/1813435/a6768f03-6d55-4133-9aad-4110960abf9d">
