### ISSUE TITLE
Off-canvas navigation – revise the icon for menu items with submenus

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#47283]
When a menu item has a submenu it's icon changes to reflect that, see "Sample page" here:

<img width="280" alt="Screenshot 2023-01-19 at 12 53 22" src="https://user-images.githubusercontent.com/846565/213448067-32d0344c-563e-452f-a6d3-708997155a04.png">

This feels a little awkward because it breaks the convention where the icon communicates the relationship between the menu item and the destination entity.

I don't think the presence of a submenu requires a different icon. The chevron already informs the user of the presence of a submenu. Instead it would be better if the convention above was respected:

<img width="280" alt="Screenshot 2023-01-19 at 12 56 43" src="https://user-images.githubusercontent.com/846565/213448764-4f6da9cc-aec0-4192-bf97-17b72ff061e0.png">

cc @WordPress/gutenberg-design for feedback.

**Comment by richtabor** [comment]
Agreed. 

Noting that this is related in part to simplifying other icons https://github.com/WordPress/gutenberg/issues/47267

**Comment by jasmussen** [comment]
Definitely agreed, looks much clearer.

I think there's an argument to be made that if the navigation is set to "open on click" (which essentially makes the top level page un-clickable and inert), a different icon could make sense. However I would consider that an edgecase to consider, and that just swapping out the icon for now would be a strong start.
