### ISSUE TITLE
Page template assign issue in Gutenberg

### ISSUE THREAD

**Issue by Imranaliweb** [WordPress/gutenberg#4728]
## Issue Overview

I am using the latest version of Gutenberg 2.1.0 And I am unable to assign page template and I do not see any select setting with Gutenberg editor, through which you can get a template assignment in the page, you can see the screenshot below. 

https://imgur.com/a/YIi5r

There is no setting for the color change of cover image in Gutenberg editor refers following link.
http://prntscr.com/i71pmq.

Thanks

**Comment by swissspidy** [comment]
The page template selection should be available under "Page attributes". Have you opened that section?

Also, you might want to open a separate issue for the color setting as it's not really related to page templates.

**Comment by Imranaliweb** [comment]
I opened it but there is no selection setting in which the page can be selected.

refer this screenshot link :- http://prntscr.com/i73kt0

**Comment by Imranaliweb** [comment]
and Gutenberg new commit can also provide text color setting on the cover image, which is not available in the current package.

**Comment by jorgefilipecosta** [comment]
Hi @Imranaliweb, thank you for opening the issue 👍  Page Template is a very recent feature and is available to test on the master branch. Unfortunately, It was not released in 2.1.0 and should only be available in the next release.
I'm closing the issue for now if after the next release or when testing on the master branch you have problems feel free to reopen it.
