### ISSUE TITLE
Columns block UI style not working

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#47297]
### Description

If you add a Columns block in the latest update (15.0.0) the styes are not correct.

### Step-by-step reproduction instructions

1. Open page
2. Add Columns Block
3. See styles in the components panel are not right

### Screenshots, screen recording, code snippet

<img width="622" alt="Screen Shot 2023-01-19 at 12 03 35 PM" src="https://user-images.githubusercontent.com/1781226/213536922-e19afa02-f631-4354-aac3-b571a178f3bc.png">

### Environment info

- WP 6.1.1
- Gutenberg 15.0.0
- Chrome
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
I can replicate this in:

WP 6.1.1
Gutenberg 15.0.0
Firefox 108.0.2 
MacOS 12.6
No other plugins active

**Comment by derekblank** [comment]
Possibly related, we noted a recent issue on Gutenberg Mobile where a width value appeared to be `null` when passed to the Column Edit view, which was causing a crash for a small amount of users. We could not actually replicate the crash within the app in our own testing, but created a [temporary fix](https://github.com/WordPress/gutenberg/pull/47234) based on the Sentry logs. Linking the Gutenberg Mobile issue in case they happen to be related:

- https://github.com/wordpress-mobile/gutenberg-mobile/issues/5387

**Comment by t-hamano** [comment]
Thanks for the report.
This issue was fixed in #47109 but it is part of Gutenberg 15.1 that has not yet been released.

I would like to close this issue, but if I have missed something feel please free to comment.
