### ISSUE TITLE
Prevent Site Editor inception with tag cloud block

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#47295]
### Description

After adding a tag cloud to the Site editor, if you click on one of the links, the editor begins to load within itself but stops short.

This matches prior issues:
https://github.com/WordPress/gutenberg/issues/40075 
https://github.com/WordPress/gutenberg/issues/33309 
https://github.com/WordPress/gutenberg/issues/30647

### Step-by-step reproduction instructions

1. Use GB 15.0.
2. Open Appearance > Editor (beta).
3. Add a tag cloud block.
4. Notice you can click on the tag and it will flash loading the associated page.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/213511918-4a6d98a8-8c83-4261-873e-2c74f623e482.mov

### Environment info

- WP 6.1.1
- GB 15.0
- Chrome
- Mac OS
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Updated as I got confused by the theme on my personal site where I first found this problem that used the tag cloud in a way that actually showed categories :)

**Comment by carolinan** [comment]
Good catch, it happens in the block editor too when Gutenberg and a block theme is used.
