### ISSUE TITLE
Youtube Embed automatically removes additional classes

### ISSUE THREAD

**Issue by AstroFoxLabs** [WordPress/gutenberg#47300]
### Description

When you add an additional class, save and leave the editor everything works fine. But as soon as you open the page editor again with that Youtube embed, the additional class gets removed. 

I use the standard Youtube embed. 

### Step-by-step reproduction instructions

1. Start editing a page or a post
2. Add Youtube embed
3. Add additional class to that embed
4. Save
5. Open the editor again

### Environment info

Wordpress 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has already been reported in  https://github.com/WordPress/gutenberg/issues/46627. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
