### ISSUE TITLE
Element > heading link color text not working

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#47303]
### Description

Theme.json rules for element heading link colors not working properly.

### Step-by-step reproduction instructions

1. Open theme.json and add this to the "styles" section:
`"elements": {
	"link": {
		"color": {
			"text": "#000000"
		}
	},
	"heading": {
		"link": {
			"color": {
				"text":"#CCCCCC"
			}
		}
	}
}`
2. In page editor, add a heading and make it a link
3. Notice the link color stays as #000000 rather than using #45786 

### Environment info

- wp 6.1.1
- gutenberg 15.0.0
- chrome
- macos

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I think we can't define nested elements (`heading > link`). If you have defined a schema property, you will get a validation error.

If you define the elements in `blocks > {blockName}` property as follows, it will work as expected:

```json
{
	"styles": {
		"elements": {
			"link": {
				"color": {
					"text": "#000000"
				}
			}
		},
		"blocks": {
			"core/heading": {
				"elements": {
					"link": {
						"color": {
							"text": "#cccccc"
						}
					}
				}
			}
		}
	}
}
```

**Comment by bradhogan** [comment]
@t-hamano Nice, that does seem to work; however, I still can't seem to get rid of the text-decoration default by using:
```
"core/heading": {
  "elements": {
	  "link": {
		  "color": {
			  "text": "#cccccc"
		  }
	  },
	  "typography": {
		  "textDecoration": "underline"
	  }
  }
},
```

**Comment by bradhogan** [comment]
@t-hamano ignore previous comment I had to move the "typography" within the "link" and obviously change the value to "none" and all is good. thanks!
