### ISSUE TITLE
Twenty Twenty Three : The "clear" button is missing in the colour setting panel for heading blocks and other blocks.

### ISSUE THREAD

**Issue by aezazs-multidots** [WordPress/gutenberg#47317]
### Description

When we use the Twenty Twenty Three theme in any setup of WordPress and use heading blocks and any other blocks in any page or post, the clear button is missing in the panel of the colour setting of that block.

### Step-by-step reproduction instructions

1. First of all, activate the Twenty Twenty Three theme.
2. Then go to any post or page and add the heading block.
3. Then open the text and background colour panel in that heading and see that the clear button will be missing.

### Screenshots, screen recording, code snippet

![CleanShot 2023-01-20 at 18 54 02@2x](https://user-images.githubusercontent.com/72435501/213705253-0a9b01fb-805e-4634-8a72-8fc8746d7474.png)

### Environment info

WordPress v6.1.1
Chrome Browser ( Version 109.0.5414.87  )
Mac OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi!
The clear button has been moved into the color options panel.
Please try the following: Next to the panel label (Color), there is a menu button that has 3 dots.
Activating this opens a new panel where you can select "RESET" on the individual setting, or at the bottom of the panel,
select "Reset all"

![The color options panel is opened and shows the option to reset the text color or reset all.](https://user-images.githubusercontent.com/7422055/213708132-2c8a977a-3b54-41fe-981c-216e0d0c00e7.png)

**Comment by richtabor** [comment]
You can also de-select any color preset.

https://user-images.githubusercontent.com/1813435/213964303-2b7230b8-d343-4ba8-aa68-cca92375731a.mp4

**Comment by richtabor** [comment]
It'd be interesting to explore quicker removal, but there's no immediate plans for this: 

<img width="337" alt="CleanShot 2023-01-23 at 12 12 00@2x" src="https://user-images.githubusercontent.com/1813435/213964678-80df84ef-e658-4b65-bdd3-bb6fd6f5d31f.png">

**Comment by kathrynwp** [comment]
I'm going ahead and closing this one, since it doesn't look like it's actually a bug.
