### ISSUE TITLE
Ability to insert custom color settings into Color panel

### ISSUE THREAD

**Issue by justintadlock** [WordPress/gutenberg#47323]
When developing custom blocks, there is sometimes a need to custom color options outside of the standard text, background, and link colors.  Currently, developers must add these to a custom panel instead of adding them to the core Color panel that already exists.

![RNhLH39 - Imgur](https://user-images.githubusercontent.com/1816309/213795024-cd55c28e-e237-4e9d-b1dd-9e474e2f9fff.png)

This request recently appeared in the [support forums](https://wordpress.org/support/topic/how-to-add-custom-item-to-color-toolbar-panel/?view=all), but I've seen other plugins create their own panels just to house custom color options (I've done this in one of my own plugins too).

We need the ability to insert custom color options into the existing panel instead of creating entirely new panels, which take up additional screen real estate and can often make the user experience less than ideal.

**Comment by skorasaurus** [comment]
heavily related: https://github.com/WordPress/gutenberg/issues/41877

**Comment by aaronrobertshaw** [comment]
Thanks for creating this issue @justintadlock 👍 

> When developing custom blocks, there is sometimes a need to custom color options outside of the standard text, background, and link colors. Currently, developers must add these to a custom panel instead of adding them to the core Color panel that already exists.

Blocks can actually already inject their own custom color controls into the Color panel. In fact, a number of core blocks already do this including:

- [Cover](https://github.com/WordPress/gutenberg/blob/b2010abc96f252fbf09cbbc74c3c81f84d906444/packages/block-library/src/cover/edit/inspector-controls.js#L252-L309) (Overlay color & opacity controls)
- [Social Links](https://github.com/WordPress/gutenberg/blob/98fdf9f9b071c1298cd77fd7c517e8a2eda36cfa/packages/block-library/src/social-links/edit.js#L217-L249) (Icon and Icon background colors)
- [Post Featured Image ](https://github.com/WordPress/gutenberg/blob/7cfbdfdff1b94ce9794ed738db55c0e38040456d/packages/block-library/src/post-featured-image/overlay.js#L67-L114) (Overlay color)
- [Navigation](https://github.com/WordPress/gutenberg/blob/af42480806fb22fcbc061056b5670db2e6b7e00a/packages/block-library/src/navigation/edit/index.js#L591-L644) (Custom text, custom background, submenu & overlay text, submenu & overlay background)

For each of the blocks above I've linked to the code where they add their controls to the Color panel's inspector controls slot. They should provide some direction on how you can achieve adding custom color controls.

You can also find a lot of background context and history in the following PRs.

- [Color Block Support: Switch to ToolsPanel for displaying UI](https://github.com/WordPress/gutenberg/pull/34027)
    - In this PR, the color panel was moved to display a ToolsPanel and the color block support updated to render its controls into that panel via a slot. 
    - The InspectoControls groups at this time were experimental and available via `<InspectorControls __experimentalGroup="color">`
- [Sidebar Tabs: Stabilize the block inspector tabs experiment](https://github.com/WordPress/gutenberg/pull/47045)
    - When the block inspector tabs were stabilized we also stabilized those experimental inspector controls groups
- [InspectorControls: Stabilize the experimental control groups](https://github.com/WordPress/gutenberg/pull/47105) 


Some further details were shared in https://make.wordpress.org/core/2023/03/07/introduction-of-block-inspector-tabs/

In case an overly simplified snippet helps:

```jsx
import {
	InspectorControls,
	__experimentalColorGradientSettingsDropdown as ColorGradientSettingsDropdown,
} from '@wordpress/block-editor';

const CustomColorControls = ( { props } ) => (
	<InspectorControls group="color">
		<ColorGradientSettingsDropdown .../>
	</InspectorControls>
)
```

I hope that addresses this issue. Do you think we can close this one now?

**Comment by justintadlock** [comment]
Yes, I think that feedback should close this.
