### ISSUE TITLE
Reduce / Undo columns without loss of content

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#47330]
## What problem does this address?
Grouping and Ungrouping blocks works in both directions without any content loss.

Converting blocks to columns works in only one direction. Converting columns back to regular blocks is only possible with a lot of Drag&Drop in list-view and a real pain!
+ Reducing number of columns with existing blocks inside results in a loss of content on the right side! (And a loss of content should never occur in any regular editor action!)

## What is your proposed solution?
Converting blocks (including groups) to columns is a rearrangement from vertical to horizontal.
New "Undo columns" command could be the same, only in the other direction:
Rearrange blocks of columns again in a regular vertical layout.
+ The same mechanism could prevent content loss when reducing number of columns: The content of the superfluous columns could be rearranged to appear **after** the columns block.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been already been reported at https://github.com/WordPress/gutenberg/issues/9009 and if you wish to follow progress on this issue you can comment in there or [subscribe to the issue in Github](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/about-notifications).
