### ISSUE TITLE
In-canvas theme color no longer same as admin color

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#47347]
When you choose an admin color scheme other than the default, the new color bleeds into controls in the canvas, including:

* Primary buttons
* Focus styles
* Overlay styles

This recently regressed, and the default color is currently shown:

<img width="1392" alt="Screenshot 2023-01-23 at 10 22 55" src="https://user-images.githubusercontent.com/1204802/214004903-741c3325-fc03-4a97-8fe6-e3b071414f9c.png">

**Comment by jasmussen** [comment]
CC: @youknowriad @ellatrix in case you have insights.

**Comment by youknowriad** [comment]
I think components squad have been working on theming recently, so maybe this is related. cc @ciampo @mirka

**Comment by youknowriad** [comment]
One other potential suspect is the recent move to iframe for block themes.

**Comment by youknowriad** [comment]
Actually, since this only affects the canvas, it's probably the latter. cc @ellatrix

**Comment by t-hamano** [comment]
Perhaps we should move this mixin from `style.scss` to `content.scss` ?

https://github.com/WordPress/gutenberg/blob/533844f881d2465ecc99cf3c957c86d02fbf57a8/packages/block-editor/src/style.scss#L63
