### ISSUE TITLE
Padding and margin visualizer broken showing all black

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#47344]
### Description

The padding and margin visualizer seems to be broken with Gutenberg 15.0.  cc @youknowriad since you helped implemented this feature. 

### Step-by-step reproduction instructions

1. Open Appearance > Editor.
2. Select a block with padding and margin support, like a Heading block.
3. Open block settings and notice the black bar that shows up when changing margin/padding.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/213988598-2c7b3720-1eab-4fa9-bce7-c7fc2f601642.mov

### Environment info

- WP 6.1.1
- GB 15.0
- TT3
- Chrome Version 108.0.5359.124
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
If I'm not wrong this has been fixed recently or has a PR or something. @t-hamano might know?

**Comment by t-hamano** [comment]
I believe this problem was fixed in #47139. But this is included in Gutenberg 15.1 and has not been released yet.

**Comment by youknowriad** [comment]
Thanks @t-hamano makes sense.

**Comment by annezazu** [comment]
Amazing. Sorry for missing this one too! Tried to check current issues rather than PRs.
