### ISSUE TITLE
Not all styles panels are visually updated on copy/paste block styles

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#47368]
### Description

Not all pasted styles are "visually" applied in the inspector panel when copying and pasting block styles. The styles are technically applied to the block, but tools that were not already applied to a styles panel, do not get updated. If you deselect the block and then reselect, all styles panels are correctly updated. 

### Step-by-step reproduction instructions

1. Add a heading block and add many custom styles to it, including padding and margin. 
2. Add another unstyled heading block. 
3. Copy the styles for the first heading to the unstyles heading block.
4. See that the applied padding and margin styles do not show up in the Dimensions panel even though they are applied to the block. If you look closely, you will also see that only Typography tools that were already applied to the unstyled heading block get updated. 
5. Click off of the block and then reselect. See that the Dimensions panel is displaying as expected. 

### Screenshots, screen recording, code snippet

![copy-past-styles-error](https://user-images.githubusercontent.com/4832319/214205864-67f338fc-da14-4102-a651-11d322b5b870.gif)

### Environment info

- WordPress 6.1.1
- Gutenberg trunk
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
cc @kevin940726

**Comment by richtabor** [comment]
Confirmed this is happening. Not ideal, but not immediate imo.

**Comment by glendaviesnz** [comment]
Possible fix here https://github.com/WordPress/gutenberg/pull/47590

**Comment by richtabor** [comment]
> Possible fix here https://github.com/WordPress/gutenberg/pull/47590

I missed that, nice! Looks good to me.

**Comment by glendaviesnz** [comment]
Re-opening this as the first fix turned out to be too fragile on trunk

**Comment by glendaviesnz** [comment]
Doing this at the [ToolsPanel level ](https://github.com/WordPress/gutenberg/pull/47673/) seems more robust, but will look further at it tomorrow to see if there is a way to get the ToolsPanelItem to do this by default rather than having to set the `isShownByDefault` prop on every instance.

**Comment by aaronrobertshaw** [comment]
I've created an alternative PR ( https://github.com/WordPress/gutenberg/pull/47727 ) that might help address this issue.

One thing to note with that PR is that if an optional control such as the Heading block's padding or margin controls has been toggled on for display or previously customized, it will still be displayed after block styles are pasted. It will reflect the current value though, so this might potentially help reflect to the user what has changed. Interested in others' thoughts on that, though.
