### ISSUE TITLE
Add a way to turn off/disable Openverse integration

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#47363]
Thanks for the patience if this has already been thought of/handled but, now that the Openverse integration has been merged https://github.com/WordPress/gutenberg/pull/46251, I wanted to ensure there was a documented way to turn this off as I imagine it'll be requested by folks similar to the pattern directory https://github.com/WordPress/gutenberg/issues/32591

cc @ntsekouras  :)

**Comment by ntsekouras** [comment]
I'll keep this in mind, thanks! We'll have to decide first how to include this in `6.2`(experimental handling).

--edit

In https://github.com/WordPress/gutenberg/pull/47404  I'm introducing a new public block editor setting(`enableOpenverseMediaCategory`) to control this.

In addition the media categories in the inserter will be locked for 6.2 https://github.com/WordPress/gutenberg/pull/47319 - so they will not be extendable for 6.2.

The setting description will be added here: https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/#settings_defaults
