### ISSUE TITLE
Post List featured image: Add options to show or hiden in Desktop, Tablet, Mobile

### ISSUE THREAD

**Issue by tohaitrieu** [WordPress/gutenberg#47397]
Dear Support.

Can you add options to show or hide in desktop, tablet, mobile for Post List featured image block?

I dont see this options.

Thank you.

**Comment by ndiego** [comment]
Hi @tohaitrieu, there are no controls in Gutenberg/WordPress for conditionally displaying blocks based on screen size, and this functionality is not on the current roadmap as far as I am aware. 

That said, there are several plugins in the [Plugin Repository](https://wordpress.org/plugins/) that provide this functionality for all blocks. You could also use a simple CSS class to accomplish what you are looking for. Something like:

```
@media ( max-width: 768px ) {
	.hide-on-mobile {
		display: none !important;
	}
}
```

You can then apply this class to any block under the Advanced tab. I hope that helps!

![image](https://user-images.githubusercontent.com/4832319/214569760-8aca3920-b177-4e43-9cae-0204ac1697f9.png)
