### ISSUE TITLE
Avatar border has stopped working on the front

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#47408]
### Description

In WordPress 6.2 alpha, with or without Gutenberg 15.0 or Gutenberg trunk active, the avatar border works in the block editor but not on the front.
This is a regression from WordPress 6.0 and 6.1.

Note that the border still works well with 6.1.1 and Gutenberg trunk, so maybe it is only an incomplete backport somewhere.

On the front, only the border radius is applied. The border style, color and width are also not in the style attribute. The wrapper is missing `has-border-color`  and `has-color-name-border-color` CSS classes.

### Step-by-step reproduction instructions

Using WordPress 6.2 alpha,
Create a new post and add an avatar block.
Adjust the border settings.
Save and view the post on the front.
Compare the results and confirm that the border works in the editor but not the front.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@aaronrobertshaw perhaps you or someone on your team can dig into this?

**Comment by aaronrobertshaw** [comment]
Thanks for flagging this one 👍 

I'm having some trouble replicating the issue, though.

Using the latest nightly, `6.2-alpha-55147`, with or without Gutenberg active (`trunk` or `15.0`), it appears to work as expected i.e. with the border color, style and width being applied on the frontend.

@carolinan can you confirm whether this issue has been resolved?

This is what I'm seeing: 

https://user-images.githubusercontent.com/60436221/215054833-89a02adf-37c2-479c-867e-8606be2f050b.mp4

**Comment by carolinan** [comment]
It is working now with Twenty Twenty-Three.

Kindly test also with a classic theme with `add_theme_support( 'appearance-tools' );`

**Comment by aaronrobertshaw** [comment]
Thanks for confirming TwentyTwentyThree is working for you @carolinan 👍 

> On the front, only the border radius is applied. The border style, color and width are also not in the style attribute. The wrapper is missing has-border-color and has-color-name-border-color CSS classes.

I've switched to a classic theme with `add_theme_support( 'appearance-tools' );` set. I am seeing the inline styles for `border-radius`, `border-style`, and `border-width`, as well as the CSS classes for named preset colors.

<img width="896" alt="Screenshot 2023-01-30 at 12 13 15 pm" src="https://user-images.githubusercontent.com/60436221/215373340-5aab0260-a413-431e-b64a-9875ac30619a.png">

When using a custom color, the `border-color` inline style is also present and showing.

Do you have a specific classic theme that you can replicate the issue with?

**Comment by carolinan** [comment]
Is it because it's a placeholder? I use a fresh install for testing, it has no custom user avatar.
WP 6.2-alpha-55160
Twenty Twenty with appearance tools:

`<div class="wp-block-avatar"><img alt="admin Avatar" src="http://0.gravatar.com/avatar/c2b06ae950033b392998ada50767b50e?s=96&amp;d=mm&amp;r=g" srcset="http://0.gravatar.com/avatar/c2b06ae950033b392998ada50767b50e?s=192&amp;d=mm&amp;r=g 2x" class="avatar avatar-96 photo wp-block-avatar__image  " height="96" width="96" style="border-radius: 5px" loading="lazy" decoding="async"></div>`

https://user-images.githubusercontent.com/7422055/215394354-78f26dbb-b4ca-423b-a139-8f0292434a75.mov

**Comment by ndiego** [comment]
I can confirm this issue using Twenty Twenty with `add_theme_support( 'appearance-tools' );` applied. I do not see any issues in TT3.

![avatar-border](https://user-images.githubusercontent.com/4832319/215457392-ef816467-5133-4533-9766-0f23cb72779b.gif)

**Comment by carolinan** [comment]
Twenty Twenty does not support the palette color as a border color without this patch: https://core.trac.wordpress.org/ticket/56487#comment:23

**Comment by ndiego** [comment]
@carolinan was it working for you with a custom color? In Twenty Twenty, the border doesn't work at all for both the palette color and custom colors.

**Comment by carolinan** [comment]
No it is not working with custom colors.

**Comment by aaronrobertshaw** [comment]
I've done some further digging on this one and found:

- Avatar borders are broken for both classic and block themes. (Tested with TwentyTwenty, TwentyTwentyThree)
- The block doesn't handle individual borders (a.k.a split borders)
- Some of TwentyTwenty's styles obscure issues e.g. default link styling setting the color I was initially selecting, resetting border style to `none` etc.

So easy steps to demonstrate the issue are:

1. Get latest WP Alpha
2. Activate latest Gutenberg trunk & TT3 theme
3. Edit a post, adding an avatar
4. Select the avatar and set a border with differing properties per side
5. Save and note that the border isn't applied correctly on the frontend

There's a PR up to apply borders correctly in https://github.com/WordPress/gutenberg/pull/47630.
