### ISSUE TITLE
Double link button in link editing UI in the site editor

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#47413]
### Description

When editing an inline link in the site editor and using internal posts lists as a source one may randomly end up with two edit buttons in the link UI. When clicking one of them the editor navigates inside its iframe to somewhere else.

### Step-by-step reproduction instructions

0. In the site editor, edit a template
1. Add a paragraph
2. Add text in the paragraph
3. Select some text and click the link format button in the block toolbar
4. Search for an existing page or post
5. Select it
6. Deselect the linked test
7. Click inside the linked text
8. Notice the double edit button
9. Click the one on the right
10. Notice the navigating away effect

### Screenshots, screen recording, code snippet

<img width="1343" alt="Screenshot 2023-01-25 at 11 13 36" src="https://user-images.githubusercontent.com/107534/214527839-7e6abc44-3877-41ef-a629-1e49d83a4484.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Not sure if there is any relation, but I wanted to note https://github.com/WordPress/gutenberg/issues/47293, as it seems like we have a few "duplication" errors in the Site Editor.

**Comment by ndiego** [comment]
The first link icon actually edits the link, the second is an "Edit Page Template" icon.

![image](https://user-images.githubusercontent.com/4832319/214563962-449b415e-c16d-454b-a88b-494a8a9cafa0.png)

**Comment by getdave** [comment]
Thanks for reporting this one. Let's see if these duplicating design tools get fixed. I'm not convinced this is a Link UI specific issue but I'll take a look....

**Comment by getdave** [comment]
Ok the reason for the bug is this code

https://github.com/WordPress/gutenberg/blob/f272fa652f411a234d8e9f8699404ed90c77d46d/packages/edit-site/src/components/block-editor/index.js#L163-L173

~No idea yet what it's trying to do but it would be nice to fix it. This isn't a Link Control specific bug but rather the code that's consuming a slot exposed on Link Control is the bug.~

Looks like it's an intentional feature added in https://github.com/WordPress/gutenberg/pull/20366.

@draganescu Do you still consider this a bug?

**Comment by ndiego** [comment]
I was just reading through #20366 and I don't think that this is the functionality that we want. Given all the changes/improvements to the Site Editor flows, I feel this is more confusing than anything. At the very least, it needs a different icon. Kind of surprised I never noticed this until now 😅

**Comment by getdave** [comment]
It's very confusing. I'm not sure if it's a feature we want to retain.

**Comment by getdave** [comment]
@SaxonF @jasmussen Any ideas if we'd like to retain this functionality. Given that it was seen as a bug by an experienced contributor (@draganescu) I can imagine it might be more confusing than useful but I don't have the full context.

**Comment by getdave** [comment]
Removing the Link Editing tag as this is not a bug of the Link UI specifically.

**Comment by draganescu** [comment]
@getdave it definitely is a bug :) there are two buttons with the same icon that do different things.

**Comment by richtabor** [comment]
> I was just reading through https://github.com/WordPress/gutenberg/pull/20366 and I don't think that this is the functionality that we want. Given all the changes/improvements to the Site Editor flows, I feel this is more confusing than anything.

Agreed. So this edit link opens up the template of the linked element? 

Yea, I don't think we need this. The Site Editor flows have come a long way since this was introduced.

**Comment by getdave** [comment]
I mean...it's a "bug" in the sense that the feature is not longer wanted. Semantics? 

Please feel free to raise a PR to remove it 👍
