### ISSUE TITLE
Spacer shows null in the dimension tooltip

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#47418]
### Description

When dragging the spacer block to resize it horizontally, when there is no way to resize it vertically the tooltip informing of the achieved result is showing a "null" string for vertical size.

### Step-by-step reproduction instructions

1. Edit a header template part in isolation
2. Add a navigation block, if one does not exist
3. In the navigation block add a spacer
4. Drag to resize the spacer horizontally
5. Notice the bug

### Screenshots, screen recording, code snippet

<img width="1342" alt="Screenshot 2023-01-25 at 12 18 26" src="https://user-images.githubusercontent.com/107534/214540698-e503a8a3-399d-47b1-82de-ee13af840414.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
>  when there is no way to resize it vertically

Do you know why this is a limitation? Seems odd that there's an arbitrary height applied (24px) when used within a Row block.

**Comment by draganescu** [comment]
No, I have not looked into this.
