### ISSUE TITLE
Native Custom fields are not showing up

### ISSUE THREAD

**Issue by ms-studio** [WordPress/gutenberg#4742]
I am testing Gutenberg version 2.1.0 on a site running WP 4.9.2.

## Issue Overview

As far as I can see, native Custom Fields are not supported at all in the Gutenberg editor.

## Steps to Reproduce (for bugs)
- Create a new Post using the classic editor.
- Go into Screen Settings, and activate the Custom Fields.
- Create a Custom Field with Name and Value.
- Return to the Post using the Gutenberg editor.

## Expected Behavior
Existing Custom Fields should be available for editing, for instance under Extended Settings.

## Current Behavior
The Custom Fields are not visible in the Gutenberg editor. The extended settings don't show up.

**Comment by danielbachhuber** [comment]
Thanks for the report, @ms-studio. This issue is already tracked in #3228
