### ISSUE TITLE
Custom Colors + TextHighlight: Missing Color Palettes

### ISSUE THREAD

**Issue by gyurmey2** [WordPress/gutenberg#47439]
### Description

Adding custom colors in the Site Editor removes the default color palette on the toolbar (Highlight option).

### Step-by-step reproduction instructions

1. Go to Site Editor.
2. Add a custom color(s).
3. Go to Post Editor.
4. Add text.
5. Try adding a text highlight color from the default palette.

### Screenshots, screen recording, code snippet

Site Editor:

![1](https://user-images.githubusercontent.com/113413673/214781453-b98a2fd0-c570-4b66-b47b-078bec40de8e.png)

Post Editor:

![2](https://user-images.githubusercontent.com/113413673/214781462-de3023ae-f176-40dd-92cf-c4185339b87b.png)

### Environment info

WordPress: 6.1.1
Theme: TT3
Gutenberg: 15.0.1 & 15.2.20230125 & without.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by webmandesign** [comment]
I can confirm this is still an issue.

**Comment by t-hamano** [comment]
Thanks for the report. Let's close this issue and focus our research and discussion in #64857.
