### ISSUE TITLE
No block settings tab is activated when you select the navigation block

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#47438]
### Description

With 6.2-alpha-55142 and Gutenberg trunk, neither the styles or settings tabs are active when you select the block.

### Step-by-step reproduction instructions

1. Activate a block theme
2. Open the Site Editor
3. Insert or select a navigation block.
4. Notice that when the block is selected and the block settings sidebar (inspector) is open, neither the styles or settings tabs are active.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/7422055/214779587-fe614324-0853-418b-b719-cc1040592d83.mov

### Environment info

With 6.2-alpha-55142 and Gutenberg trunk
Twenty Twenty-Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I can confirm. This occurs when the "Off canvas navigation editor" experiment is disabled. 

![image](https://user-images.githubusercontent.com/4832319/214958506-49a5a36f-0807-42a2-ba9b-51b44f333349.png)

**Comment by annezazu** [comment]
@getdave and @scruffian as a heads up!

**Comment by getdave** [comment]
Note that this "experiment" is now the default experience for the Plugin. Therefore I don't think this bug will occur anymore.

**Comment by draganescu** [comment]
I think this was inadvertently fixed by https://github.com/WordPress/gutenberg/pull/46995

**Comment by ndiego** [comment]
@draganescu @getdave Yup, in my testing this looks to be fixed now with the changes that went through yesterday. @carolinan can you confirm on your end as well?

**Comment by carolinan** [comment]
It is working for me now with Gutenberg trunk. The list view is activated.
