### ISSUE TITLE
Input type="number" triggers tinymce error when stepped

### ISSUE THREAD

**Issue by gubbigubbi** [WordPress/gutenberg#4744]
## Issue Overview
I am trying to work with an input number type in a Gutenberg block, which I have implemented like this:

```
edit: props => {

		return (
			<div className={props.className}>
				<input id="colQty" type="number" />
			</div>
		);
	},

```
When using this block in the editor and clicking on the up/down steppers I get the following error in the console:
Error: Permission denied to access property "nodeType"

The error seems to come from the tinymce.min.js script.

## Steps to Reproduce (for bugs)

1. Create a new guteberg block with an input field

## Screenshots / Video
![gutenberg-input-error](https://user-images.githubusercontent.com/16090465/35541630-6e412d64-05a7-11e8-82f8-fd240bf3d7d0.jpg)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by tfrommen** [comment]
I can confirm this, as I have discovered this on my own while working on a custom block including two number inputs.

The behavior seems somewhat random to me though, as I don't get the error always, and also not for a specific _event_. Sometimes it's when I step up or down, sometimes it's when I enter the input, sometimes it's when I leave...

I get the following two errors:

`Error: Permission denied to access property "nodeType"`:
```
getRng                           .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:29297:1
getStart                        .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:29067:32
<anonym>                        .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:35378:24
fire                            .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:23089:17
fire                            .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:23329:16
delegate                        .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:23534:13
executeHandlers                  .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:1694:29
defaultNativeHandler             .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:1721:11
```

`TypeError: Argument 1 of Node.contains does not implement interface Node.`:
```
regularContains                  .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:7890:34
isOrContains                    .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:22219:14
isRngInRoot/<                   .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:22224:16
filter                            .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:336:18
getBookmark                     .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:22253:14
store                           .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:22272:47
register/throttledStore<         .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:41218:9
throttle/timer<                 .../wp-content/plugins/gutenberg/vendor/tinymce.68215e08.js:36082:13
```

**Comment by SuperGeniusZeb** [comment]
I am having this same issue with the number input of a block in a plugin I am working on. Is this entirely a TinyMCE problem, and therefore unable to be fixed by Gutenberg?

**Comment by danielbachhuber** [comment]
@tfrommen Is this error specific to Gutenberg or is it a TinyMCE bug?

**Comment by danielbachhuber** [comment]
Ok, thanks @tfrommen. Closing in favor of https://github.com/tinymce/tinymce/issues/2194
