### ISSUE TITLE
Site Editor: Always Open List View preference possible regression

### ISSUE THREAD

**Issue by Marc-pi** [WordPress/gutenberg#47449]
### Description

* When we edit a template, the list is still collapsed
* Moreover : when we move blocks between block elements (example : move a paragraph from a group to another), the list is not anymore open, it is collapsed again, making it difficult to work / check the action was correctly done

poke @annezazu FSE Outreach

Seems to be a big regression !!! worked like a charm before

### Step-by-step reproduction instructions

1. Go to Appareance > Editor Beta
2. Make sure you se the editor prefearance to Always Open List View
3. Edit a template

![image](https://user-images.githubusercontent.com/919332/214814588-ccd89179-8bc8-4ea6-9cef-ec757500e7f6.png)

### Environment info

- WP 6.1.1
- TT2 theme
- Gutenberg Blocks 15.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@Marc-pi I can't replicate this - can you share a video/more info?

https://user-images.githubusercontent.com/26996883/214943394-dab98803-33b2-47e3-b0fb-aab4b179cb6c.mov

**Comment by ndiego** [comment]
I just tested with Gutenberg trunk and WordPress 6.1.1 and am unable to replicate the issue. 🤔

**Comment by Marc-pi** [comment]
Just see this, FF or Chrome that's the same (the option was set days before, i've just opened it for you)
![image](https://user-images.githubusercontent.com/919332/214962499-37d23e16-9f97-4130-8c98-c084a502f5ed.png)

the same if selected
![image](https://user-images.githubusercontent.com/919332/214963225-09cca773-a672-412c-9825-a8132bf876bf.png)

**Comment by annezazu** [comment]
I am sorry but I still am not understanding the root of the problem here. Can you send a video? What do you expect to have happen?

**Comment by ndiego** [comment]
Hmm, I think I understand what is going on here. Enabling "Always Open List View" does keep the List View open, but container blocks are collapsed by default, which is the expected result. In my testing, once you expand a container block, it remains open until the page is refreshed or the List View panel is manually closed and reopened. 

If you are experiencing situations when the container blocks will collapse automatically while you are moving blocks around, please let me know. This would be a bug. 

Otherwise, things are working as intended, but I could definitely see an enhancement that persists the state of the List View between closing and reopening the panel.

**Comment by Marc-pi** [comment]
the feature was added in Gutenberg 13.3 see https://github.com/WordPress/gutenberg/pull/40757 under @ramonjd PR lead, @getdave @paaljoachim worked also on this. Seems some of my cases were detected during the PR...

> but container blocks are collapsed by default, which is the expected result

* that's was not the case before the latest list view improvements, and does not fit with the preference description text 
* there is inconsistency
    * it is correctly full opened on post edit
    * it is closed by default on template edit
  
it ads extra friction when designing our templates, by adding extra clicks

> If you are experiencing situations when the container blocks will collapse automatically while you are moving blocks around

* yep, it is a bug, user looses time to open again to check of the block moved into the correct node after a drag and drop

IMHO the preference option impact must be fixed in 6.2 cycle for the both use cases, since it brings strong friction because of inconsistencies, it lowers user onboarding on Gutenberg, with many clicks added.

**Comment by Marc-pi** [comment]
@ndiego / @annezazu 
bad news to have droped this from 6.2, since it is a bug "the never opened list view !" 
and a regression also as it worked before
here is a video recording

[screen-recorder-thu-feb-02-2023-14-54-18.webm](https://user-images.githubusercontent.com/919332/219944495-37cd7425-e71d-465a-8eb6-dc7d4b5880a3.webm)

**Comment by Marc-pi** [comment]
the regression is still there
can we fix this in 6.2, since it is a bug ??!?

**Comment by annezazu** [comment]
@getdave any chance you could help review this issue with Ramon out who initially did the PR that implemented this functionality? https://github.com/WordPress/gutenberg/pull/40757 Asking as I see you implemented the efforts to collapse List View by default: https://github.com/WordPress/gutenberg/pull/39573

**Comment by annezazu** [comment]
Apologies - I noticed this issue after digging a bit more https://github.com/WordPress/gutenberg/issues/34759 that seems to likely cover this use case. @Marc-pi doesn't just want list view open by default but wants the collapsed items open and this would cover that use case. It's firmly an enhancement right now to add more granular control. Can we move the discussion there and close this out? I understand you don't agree, Marc, but this is an enhancement looking more broadly at the state of the project, including accessibility concerns.

**Comment by Marc-pi** [comment]
@annezazu 
Reading back your comment, indeed, there is a misunderstanding within the preference modal option wording
and a need of an improvement

![image](https://user-images.githubusercontent.com/919332/220978060-61b54797-a8ef-46c6-9ab1-c2c00466ad23.png)


1/ Change the wording to make this clearer
Always open list view > Always open list view sidebar // add sidebar
Opens the block list view sidebar by default

this point is covered by @getdave / @ramonjd in #40757 / #39573
but the wording change is needed, not everyone reads the below detailed explanation

2/ Open all nested blocks / flat view
* When working heaviliy on templates, having to open every nested blocks is a nightmare,
Especially when moving blocks from one nested area to another, we are blind and need to open groups to see where the move landed !!
* When editing a post / page content (when you write content), that's the same (but it is a less frequent need)

Seems to be indeed an improvement, pointed out by @getdave in #34759

**Comment by Marc-pi** [comment]
closed as moved to @34759
