### ISSUE TITLE
Post Excerpt: Unwanted default margin on paragraph

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#47457]
### Description

The paragraph inside the post excerpt block has the browser default margins, and that is causing a misalignment. 

For example, you would expect the excerpt to align with the post title and the meta, but it won't. The issue is apparent on both in the editor and on the front of the site. The example below was with the Twenty Twenty-three theme, but this is not a theme-specific issue.

![Screenshot 2023-01-26 at 12 21 21](https://user-images.githubusercontent.com/908665/214835814-5857dca8-1a3c-4c9f-8185-7d21f00c5e32.jpg)

It'd be great if it were removed in the plugin so that themes don't need to remove it with CSS.

BTW, the Term Description block shares the problem.

### Step-by-step reproduction instructions

1. Go to the editor
2. Add a post excerpt block
3. See it has top and bottom margins

### Environment info

WP v6.1.1
Gutenberg trunk. The issue is also happening without the plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by beafialho** [comment]
As an additional improvement, it should be possible to have text alignment controls in the post excerpt as in other text blocks.

https://user-images.githubusercontent.com/65220155/214878516-14a9f108-914b-4af0-96cf-577e1603a196.mp4

**Comment by iamtakashi** [comment]
@jasmussen If we can get rid of these unwanted margins, it'd be very helpful for the text-focused patterns for https://github.com/WordPress/gutenberg/issues/44140 Is there any chance for this and #47458 to be looked at?

**Comment by jasmussen** [comment]
This is a really good one, yes. I'll see if I can't sneak in a PR soonish. In the mean time and as prep, I wonder: is there a use case for that default margin? I know we have some other margin rules around paragraphs inside groups, is there really any downside to removing this margin? CC: @ntsekouras

**Comment by carolinan** [comment]
Is this not because the paragraph block has no class? When we add styling to the paragraph block it affects all paragraphs.

**Comment by carolinan** [comment]
I assume from the video that the second request is for text alignment on the post excerpt placeholder.
[I have a pull request for that](https://github.com/WordPress/gutenberg/pull/45003) that needs to be reviewed.

For adding block alignments and wide/full, it was recommended [not to add it](https://github.com/WordPress/gutenberg/pull/45004).

**Comment by jasmussen** [comment]
Created #47538 in an attempt to fix this. Give or take the margin discussion around "Read more", I think this is a good step forward.
