### ISSUE TITLE
Post Excerpt: Read more link is always on new line in the editor

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#47458]
### Description

Post Excerpt has the option to show the read more link on a new line. You'd expect the read more link would appear inline with the excerpt, but it won't. In the editor, the link is always on a new line regardless of the option.

![Screenshot 2023-01-26 at 13 08 36](https://user-images.githubusercontent.com/908665/214843951-64be381f-407e-4151-918b-46b387b6e90b.jpg)

The option works as expected on the front of the site 👍

![Screenshot 2023-01-26 at 13 12 20](https://user-images.githubusercontent.com/908665/214844139-2989a663-86ee-460c-8f2c-2fbe242838ec.jpg)

### Step-by-step reproduction instructions

1. Go to the editor.
2. Add a post excerpt block
3. Turn off the "show link on new line" option

### Environment info

WP v6.1.1.
Gutenberg trunk The issue also occurs without the plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I am not able to reproduce this with "empty theme", Twenty Twenty-Three or Twenty Twenty-One.
I think this may be a theme issue?

**Comment by carolinan** [comment]
Update: Actually I can reproduce it in Twenty Twenty-Three but only when the query loop uses the columns:
when here is not enough space to show the place holder on the same line as the excerpt text.
When switching from columns to lists, the option works.

**Comment by iamtakashi** [comment]
> Actually I can reproduce it in Twenty Twenty-Three but only when the query loop uses the columns:

Hmm, that's strange. The issue occurs regardless of a columns block for me.

![Screenshot 2023-01-30 at 12 51 21](https://user-images.githubusercontent.com/908665/215482839-2a27151a-81d7-4268-80f3-6c7eb5f97bc5.jpg)

**Comment by carolinan** [comment]
Is it the same if you disable all other plugins?

In this clip I am using WP 6.2-alpha-55160 with TT3. Gutenberg is not active:

https://user-images.githubusercontent.com/7422055/215485189-5d3186aa-7aca-4a50-aba6-a6f3096d7dfb.mov

**Comment by iamtakashi** [comment]
> Is it the same if you disable all other plugins?

Yes. 

Could you try adding the Query Loop block to the root, choose "start blank", and try one of the options that have an excerpt?

![Screenshot 2023-01-30 at 14 17 51](https://user-images.githubusercontent.com/908665/215502223-028b5843-029e-4d00-908a-de6a913b8a79.jpg)

**Comment by iamtakashi** [comment]
@carolinan, Ah, I think the option works for you because your test post didn't have any text/excerpt that isn't a common case.

![Screenshot 2023-01-30 at 14 22 49](https://user-images.githubusercontent.com/908665/215503252-9cd42872-f201-4f1f-a8ef-7583f2868fe0.jpg)

![Screenshot 2023-01-30 at 14 24 53](https://user-images.githubusercontent.com/908665/215503844-ef2859a7-6336-456c-ae63-8465561eca9e.jpg)

**Comment by iamtakashi** [comment]
So, in short, the issue always occurs unless the post/excerpt doesn't have any text.

**Comment by iamtakashi** [comment]
The issue is that the closing `</p>` tag does not currently include the read more link when the "show link on new line" is off.

![Screenshot 2023-01-31 at 21 48 32](https://user-images.githubusercontent.com/908665/215892068-2f6f3546-ae5b-4dba-bbf3-5bbe5136e838.jpg)

**Comment by carolinan** [comment]
I have eventually, 😆 been able to reproduce it. I think you may be right about the cause, lets try to see if we can't make the editor and front markup match better.
