### ISSUE TITLE
Insert Link and Edit Link

### ISSUE THREAD

**Issue by rileybrook** [WordPress/gutenberg#4745]
When adding or editing a link in Gutenberg, the user currently sees the label below.

<img width="689" alt="screen shot 2018-01-29 at 6 09 25 pm" src="https://user-images.githubusercontent.com/7691812/35542922-b4a0cfea-051f-11e8-8a9b-a26449ad169b.png">

The "Insert/edit link" label was a suggestion made by @afercia, and I implemented it in PR #4581

@karmatosed surfaced a great point within the comments of PR #4581 (below)
> I think if we can have a slightly more intelligent approach to this text wise it would be good. For example if it doesn't have a link, say link, and if there is, say edit. This way it makes more sense over having double interactions for one button. This aligns with the changes being looked at with linking flow.

The suggestion made by @karmatosed is something that I'd like to explore in a PR. I am creating this as a separate issue, to keep PRs and discussions organized.

**Comment by afercia** [comment]
> over having double interactions for one button

I'd argue that this won't change. The button will have double interaction anyway. It's just the label that will change dynamically.

**Comment by karmatosed** [comment]
Thanks for working on this PR @rileybrook.
