### ISSUE TITLE
Consolidate "appearance" and "settings" tabs if there are no settings controls

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#47463]
## What problem does this address?
In the current UI, the split [Appearance and Settings tabs](https://github.com/WordPress/gutenberg/issues/40204) always show up in the Inspector sidebar.  A proper example of this is the Paragraph block, which has all Appearance controls, and no Settings controls (other than the standard "Advanced" panel). We don't need a tab just for Advanced. 

## What is your proposed solution?

Let's improve this by _not_ showing the separate Appearance and Settings tabs, for blocks that do not have any controls available in Settings. And instead render the "Advanced" panel at the foot of the style controls. 

This change also allows us to experiment with having the Settings tab set as default (if there is a Settings panel). I'll follow-up with another issue on that functionality. 

### Current:

<img width="680" alt="CleanShot 2023-01-26 at 10 03 22" src="https://user-images.githubusercontent.com/1813435/214870447-7fcf963e-650e-456e-8ab6-7da4a9f255e7.png">

### Proposed: 

<img width="593" alt="CleanShot 2023-01-26 at 10 03 51" src="https://user-images.githubusercontent.com/1813435/214870571-e84d0d5c-c713-43d3-80a3-f1a4e9a31daa.png">

**Comment by ndiego** [comment]
Another option would be to render the Advanced panel in the Settings tab but have it open. I'm just thinking of third-party plugins that might add additional Settings panels. 🤔

**Comment by richtabor** [comment]
> I'm just thinking of third-party plugins that might add additional Settings panels. 🤔

Then the Appearance/Settings tabs would render. :)

**Comment by aaronrobertshaw** [comment]
> Another option would be to render the Advanced panel in the Settings tab but have it open.

We did explore having the Advanced panel open by default if it was the only item in the Settings tab in https://github.com/WordPress/gutenberg/pull/46024. Unfortunately, there were some technical limitations in detecting this scenario. 

Alternatively, having the advanced panel open by default when under the settings tab, regardless of other settings, wasn't desirable either.

---

While working on this issue, I encountered a scenario where a block with both list view and styles tabs might only have the advanced panel within the settings tab. The primary use case outlined in this issue revolves around a block without the list view tab, e.g. paragraph. The results, in that case, are no tabs being rendered in the sidebar.

Should we still render the advanced panel under the settings tab if a block has other tabs to display? I'm not sure how well the advanced panel would fit under the list view or styles tabs or the tab panel containing the two.

**Comment by hanneslsm** [comment]
I was trying to recreate the issue and then I realised that I was in the Site editor. Interestingly there is no Settings Tab there implemented (yet ?), so this issue interestingly provides consistency between Block and Site Editor. This might be something to be considered when creating the issue for experimenting having the Settings tab set as default.

(Site editor: Editing the themes. Block editor: Editing posts and pages. I do not know what the correct wordings here are.)

**Comment by aaronrobertshaw** [comment]
Thanks for reporting what you're seeing @HannesDev 👍 

> Interestingly there is no Settings Tab there implemented (yet ?), so this issue interestingly provides consistency between Block and Site Editor.

Can you confirm that you see a Settings tab in the Post Editor but not in the Site Editor? 

With Gutenberg 15.0 installed and active I can see the tabs in both editors. Prior to Gutenberg 15.0 the tabs were a Gutenberg experiment that you'd need to enable via Gutenberg > Experiments from WP Admin.

Here's what I see in the Site Editor:

<img width="280" alt="Screenshot 2023-01-30 at 12 19 18 pm" src="https://user-images.githubusercontent.com/60436221/215374368-7981b34b-f52d-4c14-924c-fd5f13b04e4c.png">
