### ISSUE TITLE
Update copy/paste block and styles UI with a flyout

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#47464]
## What problem does this address?

As a follow-up to #47164, let's replace the copy/paste block and styles `<MenuGroup>` section with a flyout UI.  This would reduce the amount of space the copy and paste actions take up (from three menu items, to one), while also adding additional context for copying/pasting blocks, and copying/pasting styles.  

There's not a component like this today; we'll need to introduce one. 

**Note:** _This is not planned for WordPress 6.2, but a follow-up._

### Current: 

<img width="351" alt="CleanShot 2023-01-26 at 10 24 44" src="https://user-images.githubusercontent.com/1813435/214875887-ab083a9d-5e4f-4c20-a79c-af477b6aa97c.png">

### Suggested

We could use another @WordPress/gutenberg-design pass; here are a couple ideas (sorting copy actions, or block/style actions) below ([ref 1](https://github.com/WordPress/gutenberg/issues/47164#issuecomment-1400124076), [ref 2](https://github.com/WordPress/gutenberg/issues/44418)).  

<img width="627" alt="CleanShot 2023-01-26 at 10 19 58" src="https://user-images.githubusercontent.com/1813435/214874625-8d3dbb30-c162-493d-b7ca-abae57960f78.png">

<img width="611" alt="CleanShot 2023-01-26 at 10 22 38" src="https://user-images.githubusercontent.com/1813435/214875360-2a8435e9-6771-439c-8e4d-edfd2ec03288.png">

**Comment by kristastevens** [comment]
Hi @richtabor, thanks for the copy review ping. I have one small suggestion, one I think that might help clarify the possible outcomes for the user. 

Current: 
> Copy/Paste as 

Suggested:
> Copy/Paste 

I think copy / paste are actions familiar to many users. The "as" introduces a little confusion here, as I would expect the following options to be nouns. If you remove it, you end up with a clean list of next possible actions the user can take.

**Comment by richtabor** [comment]
> Copy/Paste

Good with me ✅

**Comment by richtabor** [comment]
Closing in favor of #49271.
