### ISSUE TITLE
UnitControl: please add max/min properties

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#47509]
## What problem does this address?

I currently have to manually handle the values based on unit type. e.g. for a value where a custom max width value should be 100% or 600px.

## What is your proposed solution?

Add max/min properties to the component.

**Comment by mirka** [comment]
UnitControl does in fact [support](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-unitcontrol--default) `min`/`max` props. Is there a specific use case that you feel is not covered by this?

**Comment by markhowellsmead** [comment]
Ah! No, that's fine. This support isn't documented. https://developer.wordpress.org/block-editor/reference-guides/components/unit-control/

**Comment by mirka** [comment]
I see! For most components now (especially those marked as experimental), the Storybook docs tend to be more complete and up-to-date.

**Comment by markhowellsmead** [comment]
@mirka Is there no equivalent for components like `MediaUploadCheck` or `MediaUpload`?

**Comment by mirka** [comment]
I wish there were! I personally have been focusing on fleshing out the Storybook documentation for `@wordpress/components`, but it would be nice if the ones for `@wordpress/block-editor` could be improved as well.
