### ISSUE TITLE
New block: Copyright and date Block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#47522]
## What problem does this address?

I made a Full Site Editing web site for a client but did not notice any block to where I could add a copyright and date notice in the footer. I manually added it.

## What is your proposed solution?

Let's get a Copyright and date block into Gutenberg.
@mkaz Marcus made a block which is on the repository here: https://wordpress.org/plugins/copyright-block/

There is also a newer here: https://github.com/marktimemedia/copyright-year-block

Thank you to Sallie whom informed me about the above blocks.

I'll ping Anne and George.
@annezazu @Mamaduka

**Comment by masteradhoc** [comment]
Great Idea @paaljoachim ! We need that also quite a lot.

**Comment by paaljoachim** [comment]
Looking at Marcus Copyright and Date block.
https://wordpress.org/plugins/copyright-block/

It has no setting. One just adds the block.
![Screenshot 2023-01-28 at 22 09 13](https://user-images.githubusercontent.com/5323259/215291186-fdbac5a0-29ce-4465-9e53-5f736505ef37.jpg)

--

Looking at Michelle's Copyright year block. 
https://github.com/marktimemedia/copyright-year-block

One can edit the text seen in the canvas inside the block.
It has the "standard" design tools.

![Screenshot 2023-01-28 at 22 11 59](https://user-images.githubusercontent.com/5323259/215291363-7438f2c1-38c3-4051-a83d-c5246d869ada.jpg)

It would be great to take Michelle's block and add it to Gutenberg.
EDIT: One can click into the block text and adjust it.

**Comment by pbiron** [comment]
Hey Paal,

I've recently been working on a copyright block, for a site I'm developing.  I just cleaned it up a little and put it up on github.  You can grab a copy at https://github.com/pbiron/shc-copyright/releases/tag/0.9.0.

Here's a screen shot of it in the editor.

![copyright-block](https://user-images.githubusercontent.com/3824560/215358869-babac135-c765-4605-9c4e-eb39f3aaa7b0.png)

**Comment by paaljoachim** [comment]
Hey Paul

It looks good!
Perhaps you could create a PR in the Gutenberg repo setting up something similar to Michelle's and your own plugins?
Adding in the current design tools seen in Michelle's plugin.
I'll ping Aaron and Joen to get some additional feedback on this.
@aaronrobertshaw @jasmussen

**Comment by Soean** [comment]
Here is an older issue about a copyright block: https://github.com/WordPress/gutenberg/issues/18895
Also see "Add credit block" https://github.com/WordPress/gutenberg/issues/33475

**Comment by paaljoachim** [comment]
We got three issues with various information. I posted in the other issues about this newer duplicate issue. Thank you for mentioning these @Soean 
Hopefully we have enough information to someone to get started with a PR.

**Comment by aaronrobertshaw** [comment]
Thanks for taking the time to create this issue @paaljoachim 👍 

As @Soean noted, it does appear to be a duplicate. I think we'd be best served by consolidating all of the ideas, discussion, potential features, and implementation suggestions into a single issue. Given https://github.com/WordPress/gutenberg/issues/18895 has a little more history and discussion on features. Perhaps we should close this one and add the example plugins to https://github.com/WordPress/gutenberg/issues/18895.

I'd be happy to help review any PRs for the proposed copyright block. Unfortunately, I don't have the bandwidth to take it on personally right now.

**Comment by paaljoachim** [comment]
Thank you for the feedback @aaronrobertshaw 

I have added a comment here: https://github.com/WordPress/gutenberg/issues/18895#issuecomment-1423951253
and can go ahead and close my issue as a duplicate.
