### ISSUE TITLE
Text blocks

### ISSUE THREAD

**Issue by ararTP** [WordPress/gutenberg#47528]
## What problem does this address?
I want to create multiple blocks which retrieve data from a source (DB for example) into the block editor.
The problem I faced is that I want those blocks to have customization options.
To make this, I need to implement the customization options in each block which is waste off time and resources.
## What is your proposed solution?

To create a new "text block" block type, which can be inserted into other blocks instead of text, and the block will simply return a plain text to the parent block, then the text will be customizable via the parent block (every block with text field inside, e.g paragraph, header, button etc.) 

This arch can be even more useful if it will be possible to use them as attributes of blocks like `src` in an Image block

**Comment by talldan** [comment]
I'm not sure if I understand the proposal, would you be able to share more details? Maybe some pseudocode examples would help.

What you mention at the end sounds a bit like this suggested API - https://github.com/WordPress/gutenberg/discussions/39831.

I'm not sure what the status of that is.

**Comment by ararTP** [comment]
@talldan I'm offering a solution to https://github.com/WordPress/gutenberg/issues/37753 , instead of adding plain text to a block content , you will be able to add a "text block", which is a special block that doesn't have styles or structure, it will only return a plain string.
A "text block" will be registered with another function, like `register_text_block_type` or something else, and in the editor you will be able to add those text blocks as a content to other blocks like p, button etc or even to attributes.

**Comment by talldan** [comment]
The issue is that housekeeping gets very difficult when multiple issues are created for the same problem.

Maybe we could consolidate this under one issue? @ararTP would you be willing to leave a comment on https://github.com/WordPress/gutenberg/issues/37753 with your proposal?

I'll close this down and add a link to this issue on the other issue.
