### ISSUE TITLE
Extend the Gutenberg UI to wp-admin

### ISSUE THREAD

**Issue by tomxygen** [WordPress/gutenberg#47530]
## What problem does this address?
WordPress now features two very different design languages. The new modern and minimal Gutenberg design language and the old wp-admin style.

## What is your proposed solution?
Expanding the Gutenberg design language to wp-admin would be great to unify the overall experience.

Are there any plans to do so?

**Comment by skorasaurus** [comment]
Thanks for asking. 

This has been asked in the past at https://github.com/WordPress/gutenberg/issues/36115 and you can track its progress there. I don't believe there is any effort at the moment to rewrite wp-admin to be block-driven; but you can follow any progress in this issue.

**Comment by tomxygen** [comment]
@skorasaurus thanks for your reply, however I don't mean to make wp admin block driven. I'm just talking about the design language.
I saw [this article](https://make.wordpress.org/design/2022/06/13/thinking-through-the-wordpress-admin-experience/#utm_medium=referral&utm_source=facebook.com&utm_content=social) talking about a redesign of the WP Admin in the make wordpress site.
Any chance it could be turned into reality?

**Comment by carlomanf** [comment]
You also opened #47531 so let's keep this one closed.
