### ISSUE TITLE
Applying a link on a text that has a link removes all previous formatting

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#47548]
As per the PR link below, when some richtext already has formatting applied and you create a link ontop of that and then modify the link _text_ it will wipe out all the underlying formatting changes.

-----        

    This PR fixes the problem, but will need one follow up for tweaking how the fix is applied. Most importantly:

- [ ] applying a link on a text that has a link removes all previous formatting

However, the problem it fixes should be worth the trade off for now.

_Originally posted by @draganescu in https://github.com/WordPress/gutenberg/pull/45710#pullrequestreview-1272435061_

**Comment by draganescu** [comment]
I tried to repro this on trunk and could not.
