### ISSUE TITLE
Link Control - Add support for text only labels instead of relying on icons alone to communicate meaning.

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#47545]
Add support for text only labels instead of relying on icons alone to communicate meaning.

To see the current state toggle on the "Show button text labels" option under editor preferences:

<img width="748" alt="Screen Shot 2023-01-30 at 10 17 06" src="https://user-images.githubusercontent.com/444434/215449763-831b6d95-36e3-4d6f-8931-a2ca89357a31.png">

-----

> The link control panel settings don't support the text control options. (Options > Preferences > Show button text labels)

_Originally posted by @joedolson in https://github.com/WordPress/gutenberg/issues/47310#issuecomment-1399557772_

**Comment by abhi3315** [comment]
@getdave RN I am just seeing a single icon in the Link Control. Do I have to add the support to change this icon to the label text?

![image](https://user-images.githubusercontent.com/43412958/217609632-4b4594b1-6cb7-4946-af03-f67dc9e3df0b.png)

**Comment by getdave** [comment]
> @getdave RN I am just seeing a single icon in the Link Control. Do I have to add the support to change this icon to the label text?

👋 I'm not sure what `RN` means, but yes it needs to handle any icons shown and have a text based equivalent. I believe there is a standard mecahnic for this because the Gutenberg toolbars implement this pattern.

@abhi3315 Are you planning to work on this?

**Comment by abhi3315** [comment]
RN stands for Right Now 😅

@getdave Yes, I am looking forward to contribute this issue.

**Comment by getdave** [comment]
That's great to hear. Happy to review PRs. Thank you!

**Comment by abhi3315** [comment]
@getdave I have added this feature to LinkControl. But I have a query, the label uses `aria-label` to display the label. But in the case of LinkControl, the text is too big (`Toggle link settings`).

Should I change the `aria-label` to something like `Setting` or `Link Settings`?
And should I disable the tooltip when only labels are enabled?

![image](https://user-images.githubusercontent.com/43412958/217792395-928b9517-5b6f-4557-8e2e-aaa807792eb1.png)

**Comment by abhi3315** [comment]
> And should I disable the tooltip when only labels are enabled?

Tooltips are also enabled for the other toolbar items so we can ignore this.

![image](https://user-images.githubusercontent.com/43412958/217821097-973e79c5-dc99-444e-8245-7fef43f0f309.png)

**Comment by abhi3315** [comment]
@getdave Please review the PR. https://github.com/WordPress/gutenberg/pull/47930

**Comment by juanfra** [comment]
Seems like this one was resolved with https://github.com/WordPress/gutenberg/pull/47930 - I'm closing this issue, but feel free to re-open if needed.
