### ISSUE TITLE
FSE: Renaming Template names 

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#47551]
## What problem does this address?

Here are the current Template seen in the Template browse mode (I have also included the Front Page which should be by default also included into the list.)

![Screenshot 2023-01-30 at 13 07 11](https://user-images.githubusercontent.com/5323259/215472660-31e17746-c8c9-459a-b986-1dd2146ee25e.jpg)

Using my logic I would look at these as...
Front Page - Nice and clear it shows the home page of my site.
Single - I do not know. What is single?
Home - Is this also the home page of my site? Confused...
Page - I might assume these have to do with all the pages on my site.
Search - I am not totally sure. It might be a search page.
Index - Is this like the index of a book? Or in html I believe index has to do with the home page.
Blog (Alternative) - Alternative to what?
404 - is a number. I assume that means something.
Archive - What kind of archive? May post archive, blog posts or something to do with it?
Blank - I can create a blank template and I assume that I can associate it with anywhere on my site.

Here is a video I made: https://youtu.be/qiQ9jPhfEX0

## What is your proposed solution?

Go through each. Create logical names which explains what each does. Create logical descriptions adding additional explanations. 

Front Page - 
A good name.

Single - 
has to do with all single posts. What if we call these Single Posts?

Home - 
Latest Posts. 
With the explanation that if front page shows posts that the Latest Post template will automatically be used there. There is a PR for this already where discussions on renaming the Home template is being done. https://github.com/WordPress/gutenberg/pull/47389

Page -
Any adjustments here? 

Search -
What about calling this Search Page?

Index - 
Is for me a confusing name. Looking at the description it says: "Displays posts." So this would be the same as the "Latest Posts" template which I renamed above. Can we remove this template from the template list? If not then there would be two show posts templates creating confusion.

Blog (Alternative) -
I do not know why it is there.

404 -
Can we rename to Missing Page? Then add the 404 into the description of the missing page?

Archive -
Can we rename to Post Archive? As that is what it is.

Blank -
Adding in a description of how we can use the blank template would be helpful.

Thank you!

**Comment by hanneslsm** [comment]
I like this. I also always have to think again before explaining it to clients. 
My thoughts: 

Search -
How about „search results“?

404 -
How about „404 error“? You do not have to know what the 404 means, but it is clear that this page displays an error.

archive -
How about „all posts“ or „post overview“?

**Comment by mtias** [comment]
See also https://github.com/WordPress/gutenberg/pull/36000

**Comment by jordesign** [comment]
+1 to 'Search Results' - I was thinking similarly.

> has to do with all single posts. What if we call these Single Posts?

It's something of an edge case - but my understanding is that Single will be used for other post types as well (if present) so the naming may need to be broader?

---

On the whole - having the descriptions showing in the browse mode (those being considered in https://github.com/WordPress/gutenberg/issues/48290) also means we can be a _little_ more forgiving of these names as we have a chance to elaborate?

**Comment by hanneslsm** [comment]
Coming from https://github.com/WordPress/gutenberg/pull/50353 I'd like to add to the idea here that "Error 404: Missing" or "Error 404: Not Found" would be an option for error pages.
This would also give the possibility to add other error pages like "Error 403: Forbidden", which, if sorted alphabetically, would be placed directly under each other. Even if other error messages are not in core, it might be worth considering them.

**Comment by paaljoachim** [comment]
@jameskoster is working on updating the template names in this PR:
https://github.com/WordPress/gutenberg/pull/51428
Head on over and take a look and give some feedback.

**Comment by ntsekouras** [comment]
@jameskoster should we close this since https://github.com/WordPress/gutenberg/pull/51428 has landed? Is there anything else to do here?

**Comment by jameskoster** [comment]
Oh yes, good catch. I think we can close.
