### ISSUE TITLE
Scrolling sidebar on mobile scrolls content

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#4756]
## Steps to Reproduce on mobile
1. Open the demo post in Gutenberg on mobile
2. Open the sidebar
3. Start scrolling
4. Close the sidebar and notice the content has scrolled down too

## Steps to reproduce on desktop
1. Visit www.frontenberg.tomjn.com
2. Resize the browser width until the mobile view breakpoint is reached
3. Open the sidebar
4. Start scrolling
5. Close the sidebar and notice the content has scrolled down too

## Expected Behavior
Opening the sidebar to lock the scrolling of the content.

## Current Behavior
Both scroll at the same time which makes it seem like the sidebar scrolling is janky. Sometimes you can see the content appearing at the bottom of the sidebar while scrolling.

## Screenshots / Video
![scroll](https://user-images.githubusercontent.com/6073772/35613806-64692726-066d-11e8-8358-6f9e65da3d08.gif)

**Comment by karmatosed** [comment]
What device was this on? Is it on all or just a specific one?

**Comment by hedgefield** [comment]
Right sorry, I tested this on several different models of iPhone and Android, using Chrome, Firefox and Safari, the Gutenberg plugin (2.1) in Wordpress, Frontenberg, and even the responsive view on desktop, and they all have this behavior.

**Comment by hedgefield** [comment]
Updated the OP with a gif from the responsive view on desktop. Because of that I also noticed that in the tablet media query some elements like the block chrome and weirdly the text from the cover image block render at a higher z-index than the sidebar...

![zindex](https://user-images.githubusercontent.com/6073772/35613521-b2b25958-066c-11e8-8b2a-370d4908ac58.gif)

![width](https://user-images.githubusercontent.com/6073772/35613783-4fe92346-066d-11e8-9280-c69367c6ffaa.gif)

**Comment by designsimply** [comment]
Closing because I tested with the 'Toggle device toolbar' set to iPhone 6/7 in Chrome DevTools and by resizing the browser to <600px wide to trigger a breakpoint using Chrome 67.0.3396.87 on macOS 10.13.5 and I was unable to see the problem happening using WordPress 4.9.6 and Gutenberg 3.1.1.
