### ISSUE TITLE
Text stops being selected after opening highlight color and link bottom sheets (Only Android)

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#47564]
## Description

After selecting a text, opening either the Highlight color or Link bottom sheets makes the text to be unselected making it hard to know where the formatting will be applied.

## Step-by-step reproduction instructions

1. Add a Paragraph block.
2. Type some text in the Paragraph block.
3. Select a word within the text.
4. Tap on the Highlight color toolbar button.
5. Observe that the Highlight color bottom sheet opens and that the previously selected text is no longer selected.

## Expected behaviour

Text selected should remain after opening the Highlight color or Link bottom sheets.

## Actual behaviour

Text selected stops being selected after opening the Highlight color or Link bottom sheets.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/215525619-b968d706-0763-4fd5-8307-b14db0672c0a.mp4

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: Samsung Galaxy S20 FE 5G, Android 11
- Operating system: Android 13
- WordPress app version: `21.6`

**Comment by fluiddot** [comment]
Setting this issue as a High priority because it impacts negatively the writing flow experience.

**Comment by SiobhyB** [comment]
I'm no longer able to reproduce this in 23.8.1 of the Android app 🎉 

Going ahead to close this issue, but please re-open if I'm missing something or you can still reproduce!

**Comment by fluiddot** [comment]
Yep, seems this issue was addressed by https://github.com/WordPress/gutenberg/pull/57069. Thanks @SiobhyB for testing it 🙇 !

**Comment by fluiddot** [comment]
I thought the changes from https://github.com/WordPress/gutenberg/pull/57069 might have contributed but noticed it's fixed in the production version. Thanks @SiobhyB for testing it 🙇 !
