### ISSUE TITLE
Selecting multiple blocks with dimensions block support styles attached causes screen shudder

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#47589]
### Description

If multiple blocks are selected that have styles attached, eg. several Paragraph blocks with margin and/or padding added, the editor canvas shudders and multiple scroll bars are added until the selection is removed.

### Step-by-step reproduction instructions

1. Add 2 or 3 paragraph blocks to a page and assign margin and/or padding to each
2. Select all the blocks by holding the shift key while selecting
3. While multiple blocks are selected, if the shuddering doesn't start by default then resize the browser window in different directions  - there seem to be certain breakpoints that trigger it

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/3629020/215652959-e122bbfd-98f3-4514-97e2-5cbc381eeccd.mp4

### Environment info

Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@ellatrix not sure if this is related to multi-select or what's going on here but tagging you in just in case!

**Comment by ndiego** [comment]
I don't seem to be able to replicate in Gutenberg trunk. 🤔

Could it be browser specific? I tested with Chrome and Safari.



https://user-images.githubusercontent.com/4832319/216716693-c8bd221c-8ec6-49f7-a758-cd206c258070.mov

**Comment by annezazu** [comment]
I also can't replicate. @glendaviesnz can you offer either more steps and/or replicate once more with information about your browser/computer setup?

**Comment by glendaviesnz** [comment]
So it turned out that this only happens when the Grammerly Chrome extension is enabled! Seems to be related to the Grammerly spinner icon that appears a the bottom right of screen, so I am going to assume the fault is with that extension and not Gutenberg for now and close this.
