### ISSUE TITLE
Consider removing "explore all patterns" with the pattern explorer not connected to the pattern directory

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#47582]
## What problem does this address?

With the explore option not fully in place yet with the pattern directory integration https://github.com/WordPress/gutenberg/issues/44611 we should reconsider the "explore all patterns" option as the modal currently just opens the same exact views of patterns. Currently, it actually opens to "no results" if you don't first select a category:

https://user-images.githubusercontent.com/26996883/215607243-34cc9113-ddff-4ab2-b49a-c6563219030c.mov

## What is your proposed solution?

Until the pattern directory integration work is done, consider removing the "explore all patterns" option ake the pattern explorer.

**Comment by richtabor** [comment]
I think its fine to leave in; it’s not detracting from the experience and I suspect some folks will miss the modal view. 

It's better to just update it later with a proper connection to dotOrg patterns, instead of removing/adding it back.

**Comment by richtabor** [comment]
> Currently, it actually opens to "no results" if you don't first select a category

This seems something we should fix though. I don't believe this was always the case.

**Comment by Mamaduka** [comment]
+1 for keeping to explorer. It provides more real estate for viewing the patterns.

> Currently, it actually opens to "no results" if you don't first select a category

I noticed this as well. So let's mark this as a bug or regression.

**Comment by richtabor** [comment]
Closing this as the explorer will remain, but get leveled-up with a connection to the Patterns Directory https://github.com/WordPress/gutenberg/issues/44611
