### ISSUE TITLE
Browse mode: Can not scroll through all templates

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#47599]
### Description

When there are many templates, I can not scroll through all of them in the browse mode.
I also can not move through them using the arrow keys.
In my case, I can only see the first 19 templates. After that, I need to use the tab key to select the templates one by one and move downwards to the "Manage all templates" button.
When I have tabbed that far, I can no longer see the page preview.
And I do not know how to move through them on a mobile, without keyboard usage.

You may ask, why are there so many templates, what is the use case?
In my case, I have 3 custom post types but I am also using the Site Editor to add some content to taxonomy and terms pages, since these do not support the block editor otherwise.

### Step-by-step reproduction instructions

1. Add many block templates, more than 19 (though perhaps this depends on screen size)
2. Open the Site Editor browse mode
3. Try to scroll through all templates.

### Screenshots, screen recording, code snippet
In this video of browse mode, it is difficult to tell when I am trying to use the mouse to scroll, and when I try to use the keyboard arrows to move up and down: but when I am using tab, you can see the background color of the template change:

https://user-images.githubusercontent.com/7422055/215713629-852a32ad-f6f4-4d3e-8c50-fbac827e1cb2.mov

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tjcafferkey** [comment]
This is also a problem for WooCommerce users using block themes as WooCommerce provides default templates which are currently not scrollable due to this reason.

Thanks!

**Comment by carolinan** [comment]
@youknowriad Do you have any insight in how to solve this?

**Comment by youknowriad** [comment]
Weird, I remember implementing scrollbars on the sidebar. I'll need to check if this regressed. Any particular browser here or is this cross browser?

**Comment by carolinan** [comment]
I tested in Chrome on MacOS and Chrome on android mobile
But I can do a few more tests.

**Comment by carolinan** [comment]
Same issue in Firefox 109.0.1 and Safari Version 16.2 (18614.3.7.1.5)

**Comment by youknowriad** [comment]
Weird, it works for me. @jasmussen do you reproduce this?

**Comment by jasmussen** [comment]
Hmmm not really, I tried a fair bit here 🤔

**Comment by carolinan** [comment]
OK, so after more testing, it is fixed on trunk but is not in 15.0? I don't know what PR or when.

**Comment by carolinan** [comment]
Do we need a label for browse mode? I was unable to find if this had been reported and fixed through the search.
