### ISSUE TITLE
Build instructions output by gutenberg_build_files_notice() are incorrect

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#4760]
## Issue Overview

When attempting to use the Gutenberg plugin from source, an admin notice is shown that says the following:

> Gutenberg development mode requires files to be built. Run `npm install` to install dependencies, and `npm run dev` to build and watch the files.

This is incorrect because `npm run dev` does not build the files, it only starts the webpack file watcher. `npm run build` also needs to be run.

These instructions need to be updated in `gutenberg_build_files_notice()`.

**Comment by youknowriad** [comment]
`npm run dev` do build the files it may take time (like 10 seconds) to show up after the watching starts though.

It's fine to update the message to hint about `npm run build` as well.
