### ISSUE TITLE
Fix failures in loading some images from Pattern Directory core patterns

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#47636]
In https://github.com/WordPress/gutenberg/pull/46450 we removed some  bundled patterns in GB and now we fetch them through Pattern Directory.

There are some failures in loading some images in some patterns - mostly I think for `Cover` block. More details are in this comment: https://github.com/WordPress/gutenberg/pull/46450#issuecomment-1409138691

>The issue you're seeing sounds like https://github.com/WordPress/pattern-directory/issues/488, which should have been fixed with https://github.com/WordPress/pattern-directory/pull/533. In fact, if you copy [the pattern content directly from wp.org](https://wordpress.org/patterns/pattern/header-with-hero-image/), it works. So I think there's some extra encoding/sanitization on the core side that's converting the &amp; to \u0026amp;. I think it's [the wp_kses_post here](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/rest-api/endpoints/class-wp-rest-pattern-directory-controller.php#L200).

**Comment by richtabor** [comment]
> There are some failures in loading some images in some patterns - mostly I think for Cover block. 

This is strange as we have other Cover block patterns that render fine. 

<img width="283" alt="CleanShot 2023-02-07 at 17 39 19" src="https://user-images.githubusercontent.com/1813435/217382803-584ba079-1844-49db-995d-d640fc6c509f.png">

**Comment by richtabor** [comment]
We'll need to resolve these two header patterns:

https://wordpress.org/patterns/pattern/header-with-hero-image/
https://wordpress.org/patterns/pattern/header-inside-full-width-background-image/

Looking at the later, the img src differs like so: 

Broken src:

```
https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/a017-eberhard-cco-the-after-rain.jpg?w=1200&amp;h=1200&amp;fit=clip&amp;crop=default&amp;dpr=1&amp;q=75&amp;vib=3&amp;con=3&amp;usm=15&amp;cs=srgb&amp;bg=F4F4F3&amp;ixlib=js-2.2.1&amp;s=e7b4ca0a0edcc84ba48c1f7ebf02dd5a
```

v. the source from the pattern directory:  

```
https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/a017-eberhard-cco-the-after-rain.jpg?w=1200&h=1200&fit=clip&crop=default&dpr=1&q=75&vib=3&con=3&usm=15&cs=srgb&bg=F4F4F3&ixlib=js-2.2.1&s=e7b4ca0a0edcc84ba48c1f7ebf02dd5a
```

> So I think there's some extra encoding/sanitization on the core side that's converting the & 

Looks like it, yea

**Comment by ntsekouras** [comment]
The issue here is a result of GB sanitizing the pattern content through `wp_kses_post`. The flow there is:
- `wp_kses_normalize_entities` replaces `&` to `&amp;`
- `wp_pre_kses_block_attributes` replaces `&` to `\u0026` that results in `\u0026amp;` in the final output.

The above though is for security reasons and normally is not an issue for block attributes that are not URLs. In the `Cover`
block case though it is a problem, as it results to a malformed URL. I'm not confident following a [similar approach to PD](https://github.com/WordPress/pattern-directory/pull/533) to replace`\u0026amp;` to `&`, but maybe ensuring that the url is not malformed inside `Cover` block might be enough and safe.

I have prepared a PR for that here: https://github.com/WordPress/gutenberg/pull/47906


In addition I was wondering why and if it's better to for .org to host the images of `core` patterns and not use `https://img.rawpixel.com/`. Is there a reason for this? --cc @ryelle

**Comment by ryelle** [comment]
> Why `https://img.rawpixel.com/`

The images in the pattern directory are from Openverse, so the URLs pulled in are the URLs to the image in the Openverse collection.

>  if it's better to for .org to host the images of core patterns

That's possible for `core` patterns, but it would require someone uploading those images and then manually editing the pattern to replace them, since the creator flow only allows Openverse (on purpose, since average users don't have upload permissions).

But if/when the pattern explorer is ready, this issue would pop up again in the rest of the patterns, that wouldn't go through this manual replacement process.
