### ISSUE TITLE
Block control for adjacent blocks gets messed up when one of them is left/right aligned

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [WordPress/gutenberg#4764]
## Issue Overview

Create two blocks one after the other, and left or right align any one of them. The other block, which is center aligned, has its block control extend over the entire area occupied by the former block. Also, the overflow More Options menu does not appear for the center aligned block. Thus, trying to delete from the More Options menu ends up deleting the left/right aligned block. 

## Steps to Reproduce (for bugs)

1. Create any two blocks that can have an align option, one below the other.
2. Left or right align either one of them
3. Click the center aligned block. Observe the block border and block control extend over the area occupied by the other block.
4. Try to delete the center aligned block. Hover mouse to the More options menu, and click delete. The center aligned block will not get deleted, but the other block gets deleted.
5. This issue can be extended to multiple blocks. Create several blocks, align all except one to the left or right. Then click the center aligned block to observe the boundary for the block control.

## Expected Behavior

1. The boundary should enclose only the selected block, and not cover the other blocks.

## Screenshots / Video

The gif below shows multiple adjacent blocks, and clicking the center aligned block has its  block control overlay its preceding blocks.

![d1](https://user-images.githubusercontent.com/1269602/35587854-f67ffe12-0624-11e8-9eae-98e410fa4fef.gif)

The gif below shows how it's impossible to delete the center aligned block (or perform any other operation from the More Options menu), since the menu option is activated only for the smaller, right aligned block.

![d2](https://user-images.githubusercontent.com/1269602/35587955-44bd6c86-0625-11e8-8909-a6e9552ecfbf.gif)

**Comment by brandonpayton** [comment]
I'm able to reproduce this.

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 and Firefox 63.0 on macOS 10.13.6 that adding a right-aligned gallery block followed by a centered instagram block makes it so when you click on the instagram block the selection appears to encompass blocks—however, in my test, the "More options" menu did work properly and apply to the selected block it's just that the selection appears wrong. ([33s](https://cloudup.com/cKNSEiOXGvs))

Note: I also tested the PR in progress for the specific test case mentioned in this issue and found that it did solve the problem noted: https://github.com/WordPress/gutenberg/pull/11357#issuecomment-435218070

**Comment by gziolo** [comment]
Classic block regresses in this PR:
![screen shot 2018-11-09 at 12 56 06](https://user-images.githubusercontent.com/699132/48261284-d7794180-e41e-11e8-84f5-17575fa06e7c.png)
