### ISSUE TITLE
Disable custom colors does not works

### ISSUE THREAD

**Issue by chyvak1831** [WordPress/gutenberg#47642]
### Description

I'm trying disable custom colors
![Screenshot_1](https://user-images.githubusercontent.com/11210100/216022288-dba9b642-4e90-4697-8b2c-0b75c820befb.jpg)

According to [official docs](https://learn.wordpress.org/tutorial/introduction-to-theme-json/) it's possible to do using this settings

```
{
  "$schema": "https://schemas.wp.org/trunk/theme.json",
  "version": 2,
  "settings": {
    "color": {
      "custom": false
    }
  }
}
```

But it does not works for me, Custom color picker still displays and available to setup in wordpress admin.

### Step-by-step reproduction instructions

1. goto `Appearance-> Editor`
2. then select for example `Edit` for single template (or any other template)
![image](https://user-images.githubusercontent.com/11210100/216026584-e55d4ea1-7681-4aad-ab06-17c5eb7c0d90.png)
3. goto `Styles`
![image](https://user-images.githubusercontent.com/11210100/216026663-86480b49-7f7b-4c68-8b5b-e671f143ebbe.png)
4. goto `Colors`
![image](https://user-images.githubusercontent.com/11210100/216026820-2d78459b-5efd-467d-ab39-bcab94f620e2.png)
5. goto `Palette`
![image](https://user-images.githubusercontent.com/11210100/216026940-a35264bf-5787-49bb-9fcd-7bbd8b9066f8.png)
6. Custom section still here
![image](https://user-images.githubusercontent.com/11210100/216027031-710771a4-94b4-47b4-9195-7aa5863c766a.png)

Why this is incorrect? Because if we use similar key to disable Default Colors - it will be hidden in this global settings
![image](https://user-images.githubusercontent.com/11210100/216027616-62239ab3-63ca-4183-be8f-90226ecb1157.png)

### Environment info

WordPress: Version 6.1.1
Theme: Twenty Twenty-Three Version: 1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @chyvak183,

`settings.color.custom` controls whether a color can be freely selected from **the color picker**, in addition to being able to choose a color from the palette variations provided:

![color](https://user-images.githubusercontent.com/54422211/216062722-919e8fec-1667-4fef-9491-2f1536833330.png)

The property doesn't control whether the color palette itself can be customized.

**Comment by chyvak1831** [comment]
hi @t-hamano ,
yes, I know.

`settings.color.defaultPalette: false` - disable default palette panel
`settings.color.custom: false` - does **not** disable custom palette panel

is not it strange?

**Comment by t-hamano** [comment]
The "[Disabling/enabling settings/functionality](https://learn.wordpress.org/tutorial/introduction-to-theme-json/)" section of the Learn WordPress document you referred to states the following:

> Doing so would disable the custom color **picker** across all elements in the Site Editor.

Personally, I have never wondered about this property, as I know it is about the _picker_, not the _panel_. If you need a setting to hide the custom color _panel_ in the global style, you may want to submit the issue as a feature improvement.

**Comment by chyvak1831** [comment]
`settings.color.custom: false` - this disable only color picker in blocks.
But it's still available to add custom color (via **color picker**) in global styles and then it appears and available for all blocks.
So technically color picker still available.

This is logical bug. Because setting which disable color picker does it in in all places except global styles so **color picker still available**.

But ok, I'll create separately ticket as 'feature improvement'.

**Comment by t-hamano** [comment]
Thanks for submitting the new issue.

I think there are no issues to be addressed regarding this issue, so I would like to close this issue. If there is anything I have missed, please feel free to open it.
