### ISSUE TITLE
Inserter Not Available From Main Panel 'Add Block' Button

### ISSUE THREAD

**Issue by bengreeley** [WordPress/gutenberg#47659]
This may be by design, but I noticed as I'm getting used to using the Media Inserter functionality that appears when you click on the 'Add Block' button on the top lefthand side of the editor, there is no way to use the inserter from the view or know of its existence. (see screenshots):

Main panel 'Add Block' button:
<img width="977" alt="Screenshot 2023-02-01 at 4 11 16 PM" src="https://user-images.githubusercontent.com/7133400/216164171-8a523bac-6edb-4816-81a3-284701b951f6.png">

Lefthand 'Add block' button with media inserter:
<img width="1162" alt="Screenshot 2023-02-01 at 4 11 48 PM" src="https://user-images.githubusercontent.com/7133400/216164242-88290098-917e-412a-8c7a-bee85a076c51.png">

Though I understand the purpose of the popup is to provide utility to access the six most frequently-used blocks, I wonder if the interface has evolved beyond needing that popup, given the user is missing out on a lot of functionality that is then buried underneath the 'Browse all' button. 

Or, to think of it another way, is there a way we can call attention to there being lots of additional functionality such as patterns and inserters underneath the 'Browse all' button or maybe even change the block inserter utility that appears in the main editor to emulate the full functionality that is in the lefthand inserter?

**Comment by annezazu** [comment]
Closing this out in favor of this duplicate issue: https://github.com/WordPress/gutenberg/issues/24744
