### ISSUE TITLE
Layout of Navigation block restricted creating alignment problems at large viewport sizes

### ISSUE THREAD

**Issue by beafialho** [WordPress/gutenberg#47652]
### Description

I'm working on a theme whose navigation is supposed to be aligned with the content. To achieve that, I used columns blocks everywhere including header and footer. However, when I scale up the browser window more than a certain width, the navigation stops aligning with the content. Here's a quick video demo where the upper row uses the navigation block that's not working, and the row below (using a paragraph block) that behaves how I'd expect:

https://user-images.githubusercontent.com/65220155/216111049-c3a21dea-aaab-41ff-996e-706822eb850a.mp4

### Step-by-step reproduction instructions

1. Create a header with the same columns as the content
2. Add a Navigation Block in one of the columns
3. Set nav links to use `space between items`
4. Scale up browser and notice how the links do not align with the column edges

### Screenshots, screen recording, code snippet

[Theme live demo](https://fewertheme.mystagingwebsite.com)

### Environment info

- Block Canvas theme
- Gutenberg version 15.0.1
- WordPress 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I can reproduce this in Emptytheme and resolve it by enabling these settings on the column that holds the navigation block:

- Enable 'Inner blocks use content width'
- Set justification to left.

(the nav block still has justification space between and this is respected)

In TT3, the global padding disrupts this somewhat, and padding left has to be set to 0 on the column. So it depends on theme settings.

**Comment by beafialho** [comment]
@carolinan thanks for testing. The thing is, I don't want the navigation to be justified to the left. It must be using `space between items`. So, the issue persists.

**Comment by carolinan** [comment]
The column and navigation justifications are separate.

**Comment by beafialho** [comment]
Could you screen record the how you did it?

**Comment by carolinan** [comment]
I tried to match the settings I could see on the demo
https://user-images.githubusercontent.com/7422055/216357085-eee75e84-5ce3-47d3-9b7a-056c9697d51a.mov

**Comment by beafialho** [comment]
Thanks for the demo @carolinan!

My point is that the actual navigation block's items should be aligned, not the container:

<img width="826" alt="Captura de ecrã 2023-02-20, às 15 33 28" src="https://user-images.githubusercontent.com/65220155/220147784-d2ed9879-181e-487f-979d-241fe4f4e64e.png">

**Comment by carolinan** [comment]
They both need alignment/justification set to achieve the layout.
Did you set the padding to 0 to make up for the global padding?

**Comment by beafialho** [comment]
There seems to be some imposed spacing in the block. If I inspect it and uncheck the `max-width` option, it achieves the intended behaviour.

https://user-images.githubusercontent.com/65220155/226955380-6d909590-6be7-4833-a3f1-e93f02c56e04.mp4

**Comment by getdave** [comment]
I think it's this line

https://github.com/WordPress/gutenberg/blob/46969c932a9b6a8f60e61950820ea200f1e7f28b/packages/block-library/src/navigation/style.scss#L689-L693

It seems unusual although the comment provides a clear rationale for why it was necessary

> // Try to inherit wide-width when defined, so the X can align to a top-right aligned menu.

@beafialho Have you been able to narrow down a proposed fix? PRs always welcome.

**Comment by beafialho** [comment]
> @beafialho Have you been able to narrow down a proposed fix? PRs always welcome.

@getdave thank you for taking a look. I would gladly do so, but my knowledge only allows me to find where the issue may be coming from, not suggest fixes.
