### ISSUE TITLE
Extending Latest Posts block to include CPT support

### ISSUE THREAD

**Issue by mikemcalister** [WordPress/gutenberg#4766]
It would be great if we could extend the Latest Posts block to work with custom post types. I haven't been successful in querying CPT's in a dynamic block yet. If there is a working model for this already (with or without the Latest Posts block), I'd love to take a look at it.

**Comment by westonruter** [comment]
This would be something natural to add to the Query Panel component: #2662.

**Comment by mtias** [comment]
Closing in favor of #1594 and #2662.
