### ISSUE TITLE
Navigation on canvas block inserter position weirdness

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#47674]
### Description

Ran into an edge case today while testing navigation that prevents the inserter from closing.

### Step-by-step reproduction instructions

1. Click to add a new nav item on canvas
2. open inspector and click through to a child item
3. Go back up to parent and notice inserter is still open and unable to be closed

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1072756/216258618-37aa015d-899c-46d9-bf79-386e81d97351.mp4

### Environment info

15.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I'm not currently able to recreate this in WP 6.2.2 - it appears the updates to the Navigation Block/System have resolved it. I'll close this issue for now - but feel free to open with further testing details if the problem still exists.
