### ISSUE TITLE
Big spinner when loading navigation menu

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#47696]
I have a saved and customized header navigation:

<img width="311" alt="Screenshot 2023-02-02 at 15 58 25" src="https://user-images.githubusercontent.com/1204802/216359525-27817146-f42f-41a3-ac34-81928d788b35.png">

When I insert a navigation block, or when a template featuring it initially loads, there's a big unbounded spinner:

![nav spinner](https://user-images.githubusercontent.com/1204802/216359649-dc952e57-68b6-4dea-ba0a-fa9a763a78ee.gif)

Here's a paused screenshot:
<img width="524" alt="Screenshot 2023-02-02 at 15 56 20" src="https://user-images.githubusercontent.com/1204802/216359678-41d86f7d-6db8-4477-a6d1-e7f72ff1835a.png">

Note here both the big round circle, and the gray blob. That gray blob is the actual spinner, but I'm not sure why it's gray, and that circle for some reason does not inherit the boundaries.

<img width="512" alt="Screenshot 2023-02-02 at 15 56 29" src="https://user-images.githubusercontent.com/1204802/216359806-3f9cfd4f-66e9-4491-906b-211a961219e1.png">

Here's a little more inspector values:

<img width="1807" alt="Screenshot 2023-02-02 at 15 56 51" src="https://user-images.githubusercontent.com/1204802/216359860-361f9ac3-4c0a-47ad-bf80-99fb559a4352.png">

This is Chrome and mac.

**Comment by ndiego** [comment]
@jasmussen which theme are you using? I was just able to reproduce this issue in a block theme I built, but the issue goes away with TT3. 

In an attempt to track down the cause, I commented out `add_editor_style( 'style.css' );` which I had in my theme's functions.php file. Not sure why, but doing so fixed the large spinner. I tested in Safari, so the large spinner looks a bit different, but testing in Chrome produces the same results you found.

**Before removing:**
![spinner-before](https://user-images.githubusercontent.com/4832319/216730870-360ab508-017d-4e69-a4fd-5bc8b214e804.gif)

**After removing:**
![spinner-after](https://user-images.githubusercontent.com/4832319/216730895-103a9d7c-f413-4749-a7dd-0cbae50adbca.gif)

**Comment by jasmussen** [comment]
I'm using a variation of TT3 that's gone through quite a few separate saves and exports using Create Block Theme, i.e. it's become its own thing at this point. 

I would imagine that part of the bug here is that the SVG file used for the spinner does not have explicit width/height definitions, that's usually the case when SVGs go splat and fill the available space.

**Comment by apeatling** [comment]
I can reproduce this consistently with the Blockbase theme. I'll work on a PR.

**Comment by jasmussen** [comment]
Thank you 🙏
