### ISSUE TITLE
Custom post type meta box registered through register_meta_box_cb not recognized

### ISSUE THREAD

**Issue by RavanH** [WordPress/gutenberg#4772]
Working on a custom theme with a custom post type "Film" I tried Gutenberg but noticed the custom meta box is failing there. The custom meta box is registered with add_meta_box() called via the custom post type **register_meta_box_cb** parameter callback.

But when I switch to registering the meta box through the **add_meta_boxes** action hook, it suddenly appears fine.

Why is the custom post type parameter register_meta_box_cb failing for Gutenberg?

**Comment by RavanH** [comment]
UPDATE: it appears the $screen value MUST be set otherwise the meta box is ignored in Gutenberg.

The (abbreviated) code I used which was working in the classic editor but failing in Gutenberg was:
`
add_action( 'init', 'ev_post_type' );
function ev_post_type() {
  register_post_type( 'film',
      ...
      'show_in_rest' => true,
      'register_meta_box_cb' => 'ev_add_post_type_metaboxes'
    )
  );
}

function ev_add_post_type_metaboxes() {
	add_meta_box( 'film_metabox', 'Film Meta', 'ev_film_metabox', null, 'normal', 'high' );
}
`

Changing the before-last line to `add_meta_box( 'film_metabox', 'Film Meta', 'ev_film_metabox', 'film', 'normal', 'high' );` ('film' instead of null) makes the meta box appear in Gutenberg as well.

Apparently, `get_current_screen()` does not get the correct screen on https://core.trac.wordpress.org/browser/tags/4.9/src/wp-admin/includes/template.php#L920 when Gutenberg is active.

**Comment by bobbingwide** [comment]
In my opinion it's a backward compatibility bug. 

Unless otherwise excluded by the newly documented parameters, custom meta boxes registered with `null` will only be displayed when editing a `post`, but not for any other post type, including `page`. 

The problem lies in function `gutenberg_collect_meta_box_data()` 

```
// Override screen as though we are on post.php We have access to WP_Screen etc. by this point.
WP_Screen::get( $potential_hookname )->set_current_screen();
```

It's not necessary and overrides the already correct value.
