### ISSUE TITLE
Post editor has flash of unstyled content when loading

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#47724]
### Description

As the title says.

I think this issue is related to the iframed editor causing a delay when loading css, as I've noticed similar issues when working with iframes recently.

### Step-by-step reproduction instructions

1. Create a post with an empty group block and save it
2. Reload the editor (you may need to disable caching or do a hard reload)
3. With an eagle eye, notice that there' briefly a flash of unstyled content (the group block placeholder and the trailing block appender appear unstyled).

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/677833/216228500-6cb53e6f-96c1-4d3d-b186-e966d49b1d87.mp4

### Environment info

Gutenberg trunk
Brave / Mac OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
cc @ellatrix as this might be related to the iframe.

**Comment by ellatrix** [comment]
This was supposed to be fixed by #46706, but it looks like it's regressed somehow? Even for an empty post, I'm seeing a flash of an unstyled inserter button and some focus styles.

**Comment by talldan** [comment]
@ellatrix I tried something out in #47808, and it seems to solve the issue, but I'm not sure if there are any problems with the way I fixed it.

I'll be AFK for a couple of weeks after today, so feel free to take over that PR, or tackle this in whatever way you want.

**Comment by ntsekouras** [comment]
This issue happens in the iframed post editor and since we'll disable it for 6.2 https://github.com/WordPress/gutenberg/pull/48076, I'll remove this issue from the respective board.

**Comment by ellatrix** [comment]
@talldan I'm testing this again, but I can't reproduce _when caching is enabled_. Are you running this with Dev Tools open and cache disabled? In that case I can reproduce, but that's not normal usage.

**Comment by talldan** [comment]
Yep, I am generally testing with dev tools open and cache disabled.

I don't think there should be a flash of unstyled content when there's an empty cache. Especially if it's something that can be fixed.

**Comment by ellatrix** [comment]
@talldan In theory, #51136 should have fixed it. Could you confirm? Reasoning: iframe is now initialised with the styles, and the `load` event should wait until all resources are loaded.

**Comment by talldan** [comment]
Yes, looks to be resolved now. I'll close this and the PR 👍
