### ISSUE TITLE
Cover Block: Fixed background causes image to be zoomed in on Safari browser on iPad

### ISSUE THREAD

**Issue by taipeicoder** [WordPress/gutenberg#47726]
### Description

On iPad devices, cover blocks with fixed background images have an issue where the background image is zoomed in and blurry. This issue was previously reported in #17718 and fixed in the PR #40087:

```diff
-@supports (-webkit-overflow-scrolling: touch) {
+@supports (-webkit-touch-callout: inherit) {
    background-attachment: scroll;
}
```

However, this fix was seemly unintentionally reverted by the PR #40554, where the feature query is reverted back to
```
@supports (-webkit-overflow-scrolling: touch) {
    background-attachment: scroll;
}
```

Thus resurfacing the issue with fixed background images on iPad devices.

### Step-by-step reproduction instructions

1. Create a new page with a cover block, set a background image and toggle the fixed background option.
2. View the page on an iPad.
3. (Optional) Choose the option to request mobile website.
4. (Optional) The issue should be gone since ` -webkit-overflow-scrolling` is only disabled for "desktop" mode.

### Screenshots, screen recording, code snippet

Example: https://rockfielddemo.wordpress.com/ on an iPad
<img width="1180" alt="rockfielddemo" src="https://user-images.githubusercontent.com/797888/216550919-f6917720-0673-40b3-bff7-b6b8b46209b5.png">

### Environment info

* iPad Air 10.86"
* OS: iOS 16.2
* Safari

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by DustyReagan** [comment]
Hi, @taipeicoder! I tried reproducing this issue by going to the demo site https://rockfielddemo.wordpress.com/ on my iPad Air 2 running iPadOS 15.7.3 and the image looks fine. I also tried recreating the issue on my test site with no success. Can you confirm this issue is still happening?

Picture of what I see on my iPad:

![ipad-cover](https://user-images.githubusercontent.com/140841/223793188-28b91561-1204-4135-bac4-239f42a101f3.png)

**Comment by DustyReagan** [comment]
Scratch that. I see the issue on an 8th Gen iPad running iPadOS 16.2.

**Comment by DustyReagan** [comment]
Now that https://github.com/WordPress/gutenberg/pull/48981 has been merged, I believe this issue can be closed. 🎉 However, I lack the ability to close it. ☺️

**Comment by taipeicoder** [comment]
Closing as per @DustyReagan's comment 🙂
