### ISSUE TITLE
Unable to insert video from URL when block is locked

### ISSUE THREAD

**Issue by giambattista-nobile** [WordPress/gutenberg#47745]
### Description

When trying to insert a video from URL in a locked *core/video* block, an ugly error is displayed in console and nothing else happens. I suppose this happens because the lock prevents the replacement with the *core/embed* block.
Bottom line, the lock is too strong. A very similar thing happened many times to me when trying to remove and move blocks programmatically within a locked template.

### Step-by-step reproduction instructions

1. Add a Video block
2. Lock it (*Prevent Removal*)
3. Try to insert a video from URL

### Environment info

WordPress 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I wasn't able to reproduce this one using the latest version of Gutenberg.

**Comment by kathrynwp** [comment]
I **was** able to replicate this with WP 6.1.1, without the Gutenberg plugin active. Here's a screencast:

https://user-images.githubusercontent.com/7662449/217311705-d0df8aa6-af21-4c81-bb09-bdc6c6ec4d07.mov

On the other hand, I was **not** able to replicate the bug while running Gutenberg 15.0.1.

@giambattista-nobile Could you please test again with Gutenberg 15.0.1 and let us know if that solves the issue?

**Comment by giambattista-nobile** [comment]
@kathrynwp That's right, it works fine with Gutenberg 15.0.1, although I noticed the embed block gets unlocked once it's created (or rather, the lock status is not transferred from the video block to the embed block), which may not be the expected behavior.

**Comment by kathrynwp** [comment]
@talldan Would you have any input on the question around lock status just above? Thanks!

**Comment by talldan** [comment]
That the lock status isn't transferred sounds like it could be considered a small bug (maybe even a good first issue).

**Comment by ndiego** [comment]
I just tested in WordPress 6.2 Beta 3, and the issue no longer occurs. Therefore, I am going to close this out. 

The issue of the lock not transferring on block transform is a larger bug that does not just affect the Video block, so we will handle that in a separate issue.
