### ISSUE TITLE
Site editor is empty if a block theme does not include theme.json

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#47759]
### Description

Theme.json is supposed to be optional.
A block theme without theme.json can be activated and displays correctly on the front (unstyled, but the site works).
But if you open the Site Editor you are met with an empty white page. There are no JavaScript errors.

### Step-by-step reproduction instructions

Using WordPress 6.1.1 or 6.2 Alpha:

1. Delete theme.json from Twenty Twenty-Two and Twenty Twenty-Three.
2. Deactivate Gutenberg if it is active.
3. Activate Twenty Twenty-Three. View the front.
4. Open the Site Editor and see the result.
5. Go back to the theme screen in the admin area and activate Twenty Twenty-Two.
6. Open the Site Editor and see the result.

Optionally activate Gutenberg again and confirm that the Site Editor is now working.

### Environment info

WP 6.1.1 - 6.2 alpha. Untested with older versions.

MacOS 13.1
PHP version: tested with 8.0 and 8.1.
Webserver: nginx
Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Olein-jp** [comment]
I followed the same procedure in the following environment, and found the same Site Editor whiteout, with no errors in the console.

**Environment info**
MacOS 12.6
WordPress 6.1.1
PHP Version : 8.0
Server : nginx
Browser: Google Chrome

**Comment by t-hamano** [comment]
I think this issue is the same as #46557.

**Comment by carolinan** [comment]
Hm, yes!, very possible, if that fix has not been back ported to 6.2
