### ISSUE TITLE
Embed Block: frameborder of iframe is not stable depending on the context

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#47761]
## What problem does this address?

An iframe element embedded by the embed block may or may not have a border, depending on the context.

For example, the following differences were observed when Twitter is embedded:

- On the front end, the iframe element doesn't have a border because `frameborder=0` is specified in the WordPress core [get_post_embed_html()](https://github.com/WordPress/wordpress-develop/blob/ec83fd83fbb01ebbbff87fb0a7e6c05cd24b0374/src/wp-includes/embed.php#LL497C13-L498C85) function.
- In the site editor, the iframe element has a border because the iframe element doesn't have a `frameborder` attribute.
- In the post editor, for block themes,  the iframe element has a border because the iframe element doesn't have a `frameborder` attribute.
- In the post editor, for classic themes, the iframe element doesn't have  a border because the border is (perhaps unintentionally) cleared by [the WordPress admin style](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/css/common.css#L241-L244).

The latest Gutenberg uses an iframe for the post editor instance if it is a block theme. Therefore, the same post editor will have different iframe borders depending on whether it is a classic theme or a block theme.

Consider the case of a user who is using a block theme and uses an embedded block in a post. In WordPress 6.1, the editor is not an iframe, so the border is cleared by the admin style. However, in WordPress 6.2, the iframe is an iframe, so the admin reset style is not applied and borders are displayed.

I'm wondering if some users may view this change as a regression.

## What is your proposed solution?

Considering that WordPress core doesn't display borders in rendering iframes on the front end, I think that at least for the embed block, borders should not be displayed in any editor context.

### Front End

The iframe element doesn't have a border because `frameborder=0` is specified in the WordPress core `get_post_embed_html()` function:

![front-end](https://user-images.githubusercontent.com/54422211/216824554-e6aa8c6d-0403-40a6-a99d-442725f42763.png)

### Site Editor

The iframe element has a border because the iframe element doesn't have a `frameborder` attribute:

![site-editor](https://user-images.githubusercontent.com/54422211/216824560-f9c19c4a-4f22-4a2e-b231-53241687ad8d.png)

### Post Editor for Block Themes

The iframe element has a border because the iframe element doesn't have a `frameborder` attribute:

![post-editor-block](https://user-images.githubusercontent.com/54422211/216824698-bfdbca8e-fc00-4a23-a8cb-e5ab837e0989.png)

### Post Editor for Classic Themes

The iframe element doesn't have a border because the border is cleared by the WordPress admin style:

![post-editor-classic](https://user-images.githubusercontent.com/54422211/216824575-e9b08b17-6797-4243-afdd-cf35ba2dad55.png)

**Comment by t-hamano** [comment]
I have added this issue to the project board as I believe it needs to be fixed in the 6.2 release.

**Comment by annezazu** [comment]
cc @ellatrix since you worked on implementing iframing of the post editor when a block theme is in use.
