### ISSUE TITLE
Tall images which have lightbox enabled not be legible

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#47762]
### Description

When using the image block if you upload a tall image (e.g. 4000px) and enable the lightbox option when a user clicks the image the result is the image height is shrunk to fit the height of the screen, but this means the image may no longer be legible (e.g. for screenshots containing lots of text such as a screenshot of an application's settings).

Consider if the image is over a certain amount of the screen width then don't resize the image as much and allow vertical scrolling maybe...?

### Step-by-step reproduction instructions

1. Add an image block to a page
2. Upload a 4000px height image (recommended to use an image with text in it)
3. Enable lightbox option
4. View page
5. Click image
6. Observe the text is not clear

### Screenshots, screen recording, code snippet

<img width="304" alt="image" src="https://user-images.githubusercontent.com/56840277/216826149-06cf16e0-4a5d-4c3e-a680-abac8cc31343.png">

### Environment info

- WordPress 6.1.1
- Gutenberg as per 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@ninetyninew I don't think there's a lightbox feature in Gutenberg. It could be an issue with one of the plugins you're using.

**Comment by ninetyninew** [comment]
My bad, this was based off using the WooCommerce.com admin dashboard for vendors which I assumed would be standard Gutenberg but obviously not.
