### ISSUE TITLE
Covert to reusable block shows error

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#4778]
## Issue Overview
When converting to `Reusable block` I get an error telling me elements are empty, but there is no context on how they should be entered.

The block is called "Untitled block".

## Steps to Reproduce (for bugs)

1. Create a block
2. Use the '...' block menu to select `Convert to reusable block`

## Screenshots / Video

![hello_world___](https://user-images.githubusercontent.com/2005352/35630639-3ae0efd0-06a2-11e8-9ffa-06ec048fa575.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
I am finding I can't recreate this using my local install. Did you use Frontberg to write this? Just wondering if something there causing this - just going by the text.
