### ISSUE TITLE
Some of the items in dot menu of browse's navigation don't work

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#47783]
### Description

In the navigation menu the tree representation of the menu uses a special, reduced, dot menu for every item in the list. In browse mode's navigation editing the menu is the same generic block menu.

### Step-by-step reproduction instructions

1. Open the site editor on browse mode
2. Click on navigation

### Screenshots, screen recording, code snippet

<img width="1340" alt="compare-menu" src="https://user-images.githubusercontent.com/107534/216979472-d096ba86-044d-4241-adfa-fb4857f52432.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by scruffian** [comment]
This is fixed.
