### ISSUE TITLE
All navigation block children should be animated

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#47784]
Starting with #46342 and continued in #47740 the navigation block's block inspector tree editing has an animation whenever children need specific settings and are activated via clicking them in the tree.

In  #47740 it became apparent that only links and submenus animate the inspector upon selection. We should enable the animation for all blocks that are allowed as inner blocks of the navigation block.

In the video below notice when clicking on social links the inspector incoming does not animate on enter

https://user-images.githubusercontent.com/107534/217032890-0ff982b5-0a37-434e-be41-6b6e31d75d94.mp4

**Comment by getdave** [comment]
I didn't know anything was animated 😄 

Would love a video to illustrate here if you have time...

**Comment by draganescu** [comment]
@getdave 
> animate the inspector upon selection

there is an animation of entry when the inspectors for links and submenus are shown.
