### ISSUE TITLE
No Results block shows when there is 1 search result

### ISSUE THREAD

**Issue by mikachan** [WordPress/gutenberg#47793]
### Description

The No Results block is showing when there is 1 search result. It should only show when there are no results.

Here is an example using Twenty Twenty-Three, searching for "hello":

<img width="833" alt="image" src="https://user-images.githubusercontent.com/1645628/217031513-ca2ee496-98d3-4823-bf3e-d5b613d99bbf.png">

### Step-by-step reproduction instructions

1. Activate Twenty Twenty-Three, or insert the No Results block in a search template
2. Search for a keyword that should have 1 search result (e.g. "hello world")
3. Notice the No Results block still shows

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by iamtakashi** [comment]
I can also replicate this issue, but in my testing, the No Results block shows up when there is only one result. When there are more than one result, I don't see the block as expected.

**Comment by t-hamano** [comment]
I was also able to reproduce it.

- If there are **no posts** matching the query, the no results block will appear as expected.
- If there are **two or more posts** matching the query, the no results block will appear as expected.
- If there is only **one post** matching the query, the no results block will appear unintentionally.

Interestingly, this problem occurs when either of the following blocks is present in the query loop block:

- Post Featured Image
- Post Content

Both of these blocks have the same code, as shown below:

https://github.com/WordPress/gutenberg/blob/21da6b3f53abd093dd494afb9757ec69a8d72bcc/packages/block-library/src/post-featured-image/index.php#L22-L26

https://github.com/WordPress/gutenberg/blob/21da6b3f53abd093dd494afb9757ec69a8d72bcc/packages/block-library/src/post-content/index.php#L38-L42

Commenting out `the_post()` appears to solve this problem. Alternatively, if a no results block is present _before_ these blocks, this problem does not occur.

Perhaps there is some problem with the handling of the loop.

**Comment by Zodiac1978** [comment]
See also https://core.trac.wordpress.org/ticket/58031 with more ideas about the why and how to fix.

**Comment by ocean90** [comment]
Another possible fix in #53772.
