### ISSUE TITLE
No mention of core version of theme.json Schema in living reference

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/gutenberg#47797]
## What problem does this address?

There is no reference to the core version specific schema URLs in the [theme.json version 2 iving reference](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/#schema).

## What is your proposed solution?

Expand on the schema section of this page to indicate these versions for use when core WordPress is being used without the Gutenberg plugin.

**Comment by mburridge** [comment]
Add schema and version info to page:

```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
    "version": 2
```

Also, clean up text at top of page.

**Comment by justintadlock** [comment]
Current Theme Handbook reference for this: https://developer.wordpress.org/themes/advanced-topics/theme-json/#how-to-create-a-theme-json-file
