### ISSUE TITLE
Navigation menu with SVG (code content) display in page content

### ISSUE THREAD

**Issue by rotisoft** [WordPress/gutenberg#47801]
### Description

Editor don't display menu items, just empty menu items.

### Step-by-step reproduction instructions

1. Create a menu
2. Add SVG code in menu item content (sample: custom social icons), one is facebook, twitter stc. <svg .... 
3. Save menu
4. Open page to edit
5. Add navigation block, choose the created
6. It's display empty menu

### Screenshots, screen recording, code snippet

![01](https://user-images.githubusercontent.com/32747785/217090939-6ad8bd75-6745-4f33-987a-3c6bc6a64ce8.png)
![02](https://user-images.githubusercontent.com/32747785/217090946-96eb197d-08f2-4849-93d2-155cf5374586.png)
![03](https://user-images.githubusercontent.com/32747785/217093630-69ce8f39-c98c-47cd-a888-1e7860b8a73a.png)
![04](https://user-images.githubusercontent.com/32747785/217095589-348c3c50-c22f-48b9-a583-ab3e348b6ab9.jpg)

The frontend code in the page content:
[code.txt](https://github.com/WordPress/gutenberg/files/10669302/code.txt)

Debug log:
[debug.log](https://github.com/WordPress/gutenberg/files/10669342/debug.log)

Theme is Generatepress and it have a buttom, to hide/show menu, i deleted that code, it's not modify. The menu items content is empty in page content. In the footer, that nav menu is diplay the svg icons.

### Environment info

`
### wp-core ###

version: 6.1.1
site_language: hu_HU
user_language: hu_HU
timezone: Europe/Budapest
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/devroti/public_html/gombai
wordpress_size: 56,19 MB (58916924 bytes)
uploads_path: /home/devroti/public_html/gombai/wp-content/uploads
uploads_size: 11,92 MB (12501961 bytes)
themes_path: /home/devroti/public_html/gombai/wp-content/themes
themes_size: 2,66 MB (2787238 bytes)
plugins_path: /home/devroti/public_html/gombai/wp-content/plugins
plugins_size: 45,18 MB (47370133 bytes)
database_size: 8,00 MB (8388608 bytes)
total_size: 123,94 MB (129964864 bytes)

### wp-active-theme ###

name: GeneratePress Child (generatepress-child)
version: 1.0
author: T
author_website: https://wordpress.org
parent_theme: GeneratePress (generatepress)
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, automatic-feed-links, post-formats, woocommerce, title-tag, html5, customize-selective-refresh-widgets, align-wide, responsive-embeds, editor-color-palette, custom-logo, menus, editor-styles, editor-style, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets
theme_path: /home/devroti/public_html/gombai/wp-content/themes/generatepress-gombai
auto_update: Kikapcsolva

### wp-parent-theme ###

name: GeneratePress (generatepress)
version: 3.2.4
author: Tom Usborne
author_website: https://tomusborne.com
theme_path: /home/devroti/public_html/gombai/wp-content/themes/generatepress
auto_update: Kikapcsolva

### wp-plugins-active (5) ###

GenerateBlocks: version: 1.6.0, author: Tom Usborne, Automatikus frissítések kikapcsolva
GenerateBlocks Pro: version: 1.4.0, author: Tom Usborne, Automatikus frissítések kikapcsolva
GP Premium: version: 2.2.2, author: Tom Usborne, Automatikus frissítések kikapcsolva
SVG Support: version: 2.5.5, author: Benbodhi, Automatikus frissítések kikapcsolva
WooCommerce: version: 7.3.0, author: Automattic, Automatikus frissítések kikapcsolva

### wp-plugins-inactive (1) ###

Rank Math SEO PRO: version: 3.0.24, author: Rank Math, Automatikus frissítések kikapcsolva

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Nem érhető el
imagemagick_version: Nem érhető el
imagick_version: Nem érhető el
file_uploads: File uploads is turned off
post_max_size: 1024M
upload_max_filesize: 1024M
max_effective_size: 1 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.70.el7.x86_64 x86_64
httpd_software: Apache
php_version: 8.1.14 64bit
php_sapi: fpm-fcgi
max_input_variables: 15000
time_limit: 300
memory_limit: 2048M
max_input_time: -1
upload_max_filesize: 1024M
php_post_max_size: 1024M
curl_version: 7.87.0 OpenSSL/1.1.1s
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.40-cll-lve
client_version: mysqlnd 8.1.14
max_allowed_packet: 536870912
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/accountname/public_html/gombai/wp-content
WP_PLUGIN_DIR: /home/accountname/public_html/gombai/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 2048M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Nincs definiálva
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by rotisoft** [comment]
One more image:
![04](https://user-images.githubusercontent.com/32747785/217095417-6ce40195-b568-4b84-a6ac-f976234bf1b6.jpg)

**Comment by kathrynwp** [comment]
Just noting that I've added **both** the Enhancement and Bug labels, since I'm not sure whether it's **intentional** that SVGs are not supported at the moment.

**Comment by getdave** [comment]
It's intentional. For icon support we'd need to look at https://github.com/WordPress/gutenberg/discussions/53510
