### ISSUE TITLE
Site Editor: Mouse click on back button makes chevron disappear

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#47805]
### Description

In the site editor, the chevron icon disappears when the back button is clicked with the mouse.

The icon reappears when the mouse key is released.

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/217131856-f89d42df-ead2-404b-99ea-df42fdfe6dd1.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I think we'll need to set `:active` style for this button.

## Screenshot
![CleanShot 2023-02-07 at 10 02 10](https://user-images.githubusercontent.com/240569/217161498-9ff640c9-b742-49b0-a143-6f16e9ccf52d.png)
