### ISSUE TITLE
HTML Block: Preview has default Iframe insert border styling in editors

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#47818]
### Description

The custom HTML block shows the default (ugly) inset border styling of the iframe element that rendered within it.

It doesn't match the visual style of the block on the frontend.

### Step-by-step reproduction instructions

1. Add a custom HTML block and write some basic content (e.g. `<div>Hello, World!</div>`)
2. Switch to preview mode

Expected: The block prints the text and has no other unexpected border styling
Actual: The block has the default iframe border styles.

### Screenshots, screen recording, code snippet

![Screen Shot 2023-02-07 at 5 24 34 pm](https://user-images.githubusercontent.com/677833/217204494-c8164363-ddeb-41cb-9e0f-d6218f06f8e4.png)

### Environment info

Gutenberg `trunk`

Brave / Mac OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
#47761 similar to this issue has been reported.

**Comment by Mamaduka** [comment]
It's the same issue. Let's close this one as duplicate and continue the discussion in #47761.
