### ISSUE TITLE
HTML Block: Code shown in site editor browse mode

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#47819]
### Description

The default view for the Custom HTML block is the HTML code editor mode.

When HTML blocks show up in the site editor in browse mode, they by default show their code, which isn't reflective of what browse mode is supposed to be—a reflection of the user's front-end.

### Step-by-step reproduction instructions

1. Open the site editor
2. Add a custom html block with some basic content
3. Enter browse mode

Expected: The block's code isn't shown, the html preview is.
Actual: The block's code is shown

### Screenshots, screen recording, code snippet

![Screen Shot 2023-02-07 at 5 28 23 pm](https://user-images.githubusercontent.com/677833/217205372-c7156dba-3186-4d0d-b914-129541f1dfca.png)

### Environment info

Gutenberg `trunk`
Brave / Mac OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I think the solution proposed by @mtias should fix this issue https://github.com/WordPress/gutenberg/pull/41066#issuecomment-1133769853.

See also #46834.

**Comment by t-hamano** [comment]
Another PR: #46836

As noted in [this comment](https://github.com/WordPress/gutenberg/pull/46836#issuecomment-1368529035), relying on `isSelected` for preview status might cause problems for keyboard users.

**Comment by t-hamano** [comment]
My other concern is that this block may not necessarily contain content. Perhaps this is not the intended use, but for example, the following code:

![html](https://user-images.githubusercontent.com/54422211/218233660-9e32aad9-e3ac-44ff-9420-6574ea051a7a.png)

If you preview this block, the block will be almost invisible:

![preview](https://user-images.githubusercontent.com/54422211/218233682-d5770174-44f2-4fc3-a9d1-e3629bd5bcff.png)

This border is also mentioned in #47818, but if this border were removed, the block would be completely invisible and one would not be able to click on the block directly. Personally, I think it is fine as it is now.

**Comment by ndiego** [comment]
> This border is also mentioned in https://github.com/WordPress/gutenberg/issues/47818, but if this border were removed, the block would be completely invisible and one would not be able to click on the block directly. Personally, I think it is fine as it is now.

The border has been removed, so I agree that I think the implementation is ok as is. Not ideal, but not a blocker for 6.2.

**Comment by youknowriad** [comment]
I think we could solve this by using `isPreviewMode` setting of the block editor.
