### ISSUE TITLE
Wrong string concatenation for the read more block.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#47812]
### Description

Introduced in https://github.com/WordPress/gutenberg/pull/45490

We received this feedback related to the change from the PR above https://core.trac.wordpress.org/ticket/57471#comment:27

Basically we should avoid concatenation when it comes to translated strings. We might also want to add a "since" doc block. 

Let's make sure to follow-up on that and label the PR with the "backport to WP beta/RC" label to include on the next package update in core.

**Comment by carolinan** [comment]
I don't think the feedback link is correct? It is for the copy_dir change.

**Comment by youknowriad** [comment]
yeah, sorry, it's fixed now.

**Comment by kebbet** [comment]
A quick look in some other `*.php` files in `wp-includes/blocks` reveals that all functions in them are missing `@since` tags. So maybe nothing to address in this issue?

**Comment by kebbet** [comment]
Created a PR to address it, might be other nicer or smarter solutions, but this is _one_ solution to the issue.

**Comment by carolinan** [comment]
😄
