### ISSUE TITLE
Media Placeholder - 'Insert from URL' popover incorrectly positioned

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#47817]
### Description

The media placeholder 'Insert from URL' popover is incorrectly positioned.

### Step-by-step reproduction instructions

1. Add a video or image block
2. Select the 'Insert from URL' button

Expected - the popover is centered below the button
Actual - the popover is positioned to the top left

It seems even worse if you open List View and then select the button.

### Screenshots, screen recording, code snippet

With List View closed:
![Screen Shot 2023-02-07 at 5 10 47 pm](https://user-images.githubusercontent.com/677833/217201491-34ff73ff-9bfe-4caf-834b-e04ff4888765.png)

With List View open:
![Screen Shot 2023-02-07 at 5 11 01 pm](https://user-images.githubusercontent.com/677833/217201540-8c63e708-9659-4c33-8800-160603f90969.png)

### Environment info

Latest Gutenberg trunk

Brave / Mac OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by apeatling** [comment]
I can't reproduce this in Safari or Chrome on Mac, it's positioned correctly. I do see the problem when opening the list view:

![2023-02-09 12 42 21](https://user-images.githubusercontent.com/1464705/217934923-bedb5d2c-8371-48e4-ac0d-b727450271c4.gif)

**Comment by ntsekouras** [comment]
This issue happens in the iframed post editor and since we'll disable it for 6.2 [here](https://github.com/WordPress/gutenberg/pull/48076), I'll remove this issue from the respective board.

**Comment by apeatling** [comment]
Makes sense, thanks for the extra context on the iframed post editor part.

**Comment by mtias** [comment]
I think this is ok now even in the iframe version.
