### ISSUE TITLE
Private APIs: Improve the unlocking mechanism when paired with data stores

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#47830]
## What problem does this address?

Part of https://github.com/WordPress/gutenberg/issues/47786.

It's based on the observation I shared after studying the refactoring applied by @talldan in #47375 to use hide the experimental APIs with the locking/unlocking system. The comment is available at https://github.com/WordPress/gutenberg/pull/47375#issuecomment-1418801976:

> One potential drawback to calling `unlock` on the entire data store exists. After a couple of refactorings, it will be impossible to tell which selectors/actions are experimental. In the case of promoting an experiment to a stable API, the `unlock` call will stay in place as there won't be any incentive to refactor the code. In addition, it's going to be difficult to tell whether this proxy can be safely removed without running the code, because several more than one selector/action could be experimental.

## What is your proposed solution?

Two solutions were proposed by @adamziel in https://github.com/WordPress/gutenberg/pull/47375#issuecomment-1418856978:

> 1. Don't expose stable selectors on the unlocked store. Drawback: Now you need two useSelect() calls.
> 2. Use a prefix like __internal to make the difference apparent. Drawback: There's still a prefix.
>
> I don't like either of these solutions. This issue could use a separate discussion thread.

@talldan commented on the idea (1) in https://github.com/WordPress/gutenberg/pull/47375#issuecomment-1420023895 with:

> I don't think it'd require two useSelect calls, it'd look a bit like this:
>
> ```js
> const { public, private } = useSelect( select ) => {
>   const { publicSelector } = select( myStore );
>   const { privateSelector } = unlock( select( myStore ) );
>   return { public: publicSelector, private: privateSelector };
> } );
> ```

I responed to the idea (2) in https://github.com/WordPress/gutenberg/pull/47375#issuecomment-1418938406 with:

> It might help if the prefix was automatically prepended by the `lock` call. Still, not ideal 😄

**Comment by adamziel** [comment]
cc @youknowriad @jsnajdr @talldan

**Comment by youknowriad** [comment]
No strong opinion for me. I'm not sure it's very important personally to distinguish between locked and unlocked selectors in core components but regardless, @talldan's idea is fine by me.

**Comment by gziolo** [comment]
Actually, my only concern was that we would end up with lingering `unlock` calls on stores, but it might be partially covered with the following line:

https://github.com/WordPress/gutenberg/blob/a0ef1139112aa93235eba2c582bc3cc5fcc05d55/packages/private-apis/src/implementation.js#L174-L178

We will see how it looks in practice.
