### ISSUE TITLE
Editable: Inline boundary highlight persists after blur

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#4783]
## Issue Overview

If an inline element with boundaries (e.g. link) is highlighted when focus leaves an Editable input, the highlight remains.

## Steps to Reproduce

1. Navigate to https://frontenberg.tomjn.com/
2. Move cursor within inline boundary
3. Select another block

## Expected Behavior

Inline boundary highlight is dismissed.

## Current Behavior

Inline boundary highlight persists.

## Possible Solution

Should TinyMCE's implementation of inline boundaries be detecting focus loss? Or do we need to be triggering this dismissal in our own focus loss handlers?

## Screenshots / Video

![highlight](https://user-images.githubusercontent.com/1779930/35640241-9d0c3402-068a-11e8-8ea3-ffcded5b693b.gif)

**Comment by noisysocks** [comment]
Perhaps Frontendberg is running an older version? This seems OK in `master`:

![selection](https://user-images.githubusercontent.com/612155/35655687-3a44184a-0747-11e8-9fb8-117e342aaa55.gif)
