### ISSUE TITLE
Editor crashes on page load in Safari (trunk & 6.2 beta 1)

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#47865]
### Description

When trying to access the editor by for example creating a new page, the editor renders for a second and then shows the "The editor has encountered an unexpected error." error. Looking at the console this error appears: 
`typeerror: undefined is not a function (near '...[u=n,c=e.innerBlocks]...')`

Clicking the `Copy Error` button copies this:
```
@http://localhost:8888/wp-content/plugins/gutenberg/build/blocks/index.min.js?ver=31dffb10957cf453716d:13:39097
Yn@http://localhost:8888/wp-content/plugins/gutenberg/build/blocks/index.min.js?ver=31dffb10957cf453716d:13:39197
@http://localhost:8888/wp-content/plugins/gutenberg/build/blocks/index.min.js?ver=31dffb10957cf453716d:13:39725
reduce@[native code]
@http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=d05518609e709cea9af4:1:85761
i@http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=d05518609e709cea9af4:1:69741
map@[native code]
@http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=d05518609e709cea9af4:1:85999
i@http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=d05518609e709cea9af4:1:69741
@http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=d05518609e709cea9af4:1:86481
i@http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=d05518609e709cea9af4:1:69741
@http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=d05518609e709cea9af4:1:86850
i@http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=d05518609e709cea9af4:1:69741
@http://localhost:8888/wp-content/plugins/gutenberg/build/edit-post/index.min.js?ver=db338561b12ac1906e67:37:7352
p@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.min.js?ver=0ff95a164fdb7d8c0e31:1:25054
@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.min.js?ver=0ff95a164fdb7d8c0e31:1:25357
$e@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.min.js?ver=0ff95a164fdb7d8c0e31:1:25496
_l@http://localhost:8888/wp-content/plugins/gutenberg/build/edit-post/index.min.js?ver=db338561b12ac1906e67:37:7222
yl@http://localhost:8888/wp-content/plugins/gutenberg/build/edit-post/index.min.js?ver=db338561b12ac1906e67:37:7866
tp@http://localhost:8888/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:1:139608
rm@http://localhost:8888/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:1:166878
py@http://localhost:8888/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:1:240487
Zg@http://localhost:8888/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:1:232090
Gg@http://localhost:8888/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:1:231975
Kg@http://localhost:8888/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:1:231738
Mg@http://localhost:8888/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:1:229282
Fg@http://localhost:8888/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:1:229761
Fg@[native code]
Js@http://localhost:8888/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:1:97398
@http://localhost:8888/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:1:226558
```

### Step-by-step reproduction instructions

1. Navigate to the WordPress Dashboard using Safari (Mac)
2. Click on "Add new Page"
3. Wait for a few seconds

### Screenshots, screen recording, code snippet

![CleanShot 2023-02-08 at 08 54 19@2x](https://user-images.githubusercontent.com/20684594/217469527-7e1e69b9-8965-4410-b8a4-ac51aa68893b.png)

### Environment info

- Gutenberg Plugin `trunk` fresh build
- Safari 16.3
- macOS 13.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thank you, @fabiankaegy!

I'm having trouble reproducing the error. Testing with Gutenberg `trunk`, WP 6.1/6.2-beta, and Safari 16.3.

Based on the screenshot, the errors happen near these lines - https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/parser/apply-block-deprecated-versions.js#L96-L109.


Are you testing with the default theme, and do you have any other plugins active? Or maybe the pages have a template set via settings?

**Comment by ntsekouras** [comment]
I wasn't able to reproduce this.. and was going to say what George said 😄 

It seems a block has no `innerBlocks`, that is quite weird since the default is an empty array. What happens though when editor loads, is to also pre-parse patterns.

My guess would be something is wrong with some pattern.. Do you register any custom patterns?

**Comment by fabiankaegy** [comment]
Okay, in doing some more testing I've found that the issue does not in fact happen on Safari 16.3. But instead only happend in Safari 16.4. Which is really odd... 

I hadn't realized I was using the Technology Preview. Sorry about the confusion. 

I'm not sure whether this is an indicator that this is an actual issue we should investigate or whether it is a browser bug that will get fixed on Safaris end before they release the next version.

**Comment by fabiankaegy** [comment]
The interresting thing about this is, that the issue does not happen in Safari TP on a clean WordPress 6.1.1 instalation. Only when gutenberg or 6.2 comes into play does this happen 100% reliable for me.

**Comment by fabiankaegy** [comment]
And it only happens when you try and create a new empty post. It does not happen when you for example open the "Sample Page" in the editor. So I assume it has something to do with the initially empty editor at the root level.

**Comment by Mamaduka** [comment]
Updated labels and milestones. The bug only occurs in Safari technical preview; let's confirm when the 16.4 stable is released.

**Comment by ajl-2020** [comment]
I get the same error using:
6.2 RC-1
MacOS 13.3 Beta (22E5236f)
Safari Version 16.4 (18615.1.25) [This is the version that comes with the MacOS 13.3 beta; it's not the technical preview.]

Eliminated all plugins. Clean install of Wordpress.

Seems Safari-specific; does not happen in Firefox.

**Comment by Mamaduka** [comment]
@fabiankaegy, I just tested with Safari 16.4 is now stable, and I'm unable to reproduce the error.

## Environment
* WordPress 6.2 RC4 - with and without Gutenberg plugin (`trunk`).
* MacOS 13.3 (22E252)

**Comment by fabiankaegy** [comment]
@Mamaduka I was thinking about this issue today and tested with the new Safari stable version and also the new TP version and the issue seems to have been resolved. So we can close this issue. Sorry again for the confusion :)
