### ISSUE TITLE
Multiple templates selected in dark menu

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#47869]
### Description

In some scenarios it's possible for multiple templates to appear 'selected' in the Templates panel of the site editor navigation.

<img width="390" alt="Screenshot 2023-02-08 at 10 57 37" src="https://user-images.githubusercontent.com/846565/217510915-801be1f8-5948-4570-ad02-090c52b4d246.png">

### Step-by-step reproduction instructions

1. Set homepage to display latests posts
2. Open site editor and create a new template for a specific page
3. Click W button to open the navigation
4. Notice that both the latest posts template (Home or Index) is selected _as well_ as the new template you just created

cc @youknowriad

**Comment by youknowriad** [comment]
I think that's not important to fix now, since we're changing how things work in #47777 
Basically there will be no "active" elements in the sidebar.

**Comment by Mamaduka** [comment]
I thought I fixed this in #46524. I guess I missed the spot 😅

**Comment by jameskoster** [comment]
> I think that's not important to fix now, since we're changing how things work in https://github.com/WordPress/gutenberg/pull/47777

Derp, of course. We can close this when 47777 is merged.
