### ISSUE TITLE
Block Editor: Link control displays scrollbars on toggle

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#47876]
### Description

In the new link control component, an unnatural scroll bar appears when toggling settings.

I have confirmed this issue in both Chrome and Firefox on Windows. On Mac, you might be able to reproduce this by changing the "General > Show scroll bars" setting to "Always".

### Step-by-step reproduction instructions

Set a link to the text and click the settings toggle button.

#### Google Chrome

https://user-images.githubusercontent.com/54422211/217529339-d9f68a47-638d-40d1-b9c3-1d54a2818cae.mp4

#### Firefox

https://user-images.githubusercontent.com/54422211/217529356-3706ba3c-c54c-4ca8-88ad-52befb959c87.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
The new settings "drawer" isn't shipping with WP 6.2.

**Comment by getdave** [comment]
Thanks for reporting.
