### ISSUE TITLE
Nav block creates x2 Menus when you have no menus and add a new block to it

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#47881]
x2 menus are being created by the block.

To replicate

- Delete all existing Nav menus
- New Post
- Add Nav block
- Click to add a new Custom Link block
- See UI indicators that menu being created
- Go to http://localhost:8888/wp-admin/edit.php?post_type=wp_navigation
- See x2 menus are created

--------

If you click the block inserter to add a new block, and select a custom link, two new menus are created:
<img width="305" alt="Screenshot 2023-02-08 at 10 38 21" src="https://user-images.githubusercontent.com/275961/217506589-172713af-3a25-4174-9440-60b921b9d308.png">
<img width="526" alt="Screenshot 2023-02-08 at 10 38 15" src="https://user-images.githubusercontent.com/275961/217506594-802f568e-466c-4b81-9aae-a426ec7dae1c.png">

It would be good to add a test for this!

_Originally posted by @scruffian in https://github.com/WordPress/gutenberg/issues/47825#issuecomment-1422386206_

**Comment by scruffian** [comment]
If we go ahead with [this](https://github.com/WordPress/gutenberg/pull/47684) then this is no longer an issue!
