### ISSUE TITLE
Query Loop Top Border Issue

### ISSUE THREAD

**Issue by Hiren1094** [WordPress/gutenberg#47909]
### Description

Hello,

Top border should be show on mouse hover When I select the query loop block

Core Ticket Link: [Core Ticket](https://core.trac.wordpress.org/ticket/57668)

### Step-by-step reproduction instructions

1. Create new post.
2. And select Query loop block.

### Screenshots, screen recording, code snippet

![Query_loop](https://user-images.githubusercontent.com/74503383/217766187-14ccc5a2-350b-4415-ba46-af98603d81f8.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bhargavcreolestudios** [comment]
This is an issue for "6.2-beta1" version

**Comment by Hiren1094** [comment]
This is an issue for "6.2-beta1"

**Comment by bhaveshd36** [comment]
Hi,
I have tested this in the WP 6.2-beta2 version. The top border is not showing on Mouse hover when choosing a Query loop.
Video of the Issue: https://share.cleanshot.com/8h2bkv45BVSfZN2C60nJ

### Steps to reproduce the issue:
1. Create new post.
2. Select Query loop block.
3. Click on the "Choose" button.
4. Hover over the first option in the "Choose a pattern" pop-up.

**Comment by ndiego** [comment]
I am able to confirm as well in Beta 2.

![image](https://user-images.githubusercontent.com/4832319/220375365-9a217a57-70b7-4239-ac91-6fa8f62d12b7.png)
