### ISSUE TITLE
Custom template parts can't be renamed from the template parts list

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#47915]
### Description

In the Site Editor, both custom templates and custom template parts can be renamed from the 'template details' dropdown:

<img width="1525" alt="Screenshot 2023-02-09 at 10 36 22" src="https://user-images.githubusercontent.com/1682452/217777462-042aa4b1-110f-4010-814b-37c1c3d1e62d.png">

<img width="1510" alt="Screenshot 2023-02-09 at 10 40 16" src="https://user-images.githubusercontent.com/1682452/217777474-fb69d197-bddd-4830-9c98-6a0055244014.png">

Instead, in the templates / template parts list, only custom templates can be renamed. In the template parts list, the 'Rename' Action for custom template parts is missing. The Actions dropdown menu only shows the 'Delete' action:

Templates list:

<img width="1792" alt="Screenshot 2023-02-09 at 10 40 55" src="https://user-images.githubusercontent.com/1682452/217778250-181210ad-f6ec-4a42-8a83-392e0c728581.png">

Template parts list:

<img width="1774" alt="Screenshot 2023-02-09 at 10 41 16" src="https://user-images.githubusercontent.com/1682452/217778319-61c7ed19-3055-42d3-ab14-ba483aa659c1.png">

It appears the `RenameMenuItem` component [returns early](https://github.com/WordPress/gutenberg/blob/300a608b8d4f226055f2b1ae3dc877002ea36284/packages/edit-site/src/components/list/actions/rename-menu-item.js#L27-L29) if the template `is_custom` prop does not exists. To my understanding the `is_custom` prop exists only for templates. It doesn't for template parts/ Therefore, the 'Rename' action is not shown.

Everything else seems to be in place: when commenting out the early return, the Rename action does show and appears to work as expected.

Cc @Mamaduka 

### Step-by-step reproduction instructions

- Go to the Site Editor.
- Create a custom template and a custom template parts.
- Edit them and observe it is possible to rename both from the 'template details' dropdown in the top bar.
- Go to Templates > Manage all templates.
- In the Templates list, click the Actions button for the custom template.
- Observe there is a 'Rename' action.
- Go to Template parts > Manage all template parts.
- In the Template parts list, click the Actions button for the custom template part.
- Observe there is no 'Rename' action.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by afercia** [comment]
Related: https://github.com/WordPress/gutenberg/pull/36911

**Comment by Mamaduka** [comment]
Tanks for catching the bug, @afercia!

I’ll have PR ready before Beta 2.
