### ISSUE TITLE
Add left/right alignment support to the group block

### ISSUE THREAD

**Issue by cbirdsong** [WordPress/gutenberg#47943]
## What problem does this address?

A floating sidebar with text is a common pattern in design:
![Screenshot of a sidebar with text floated right next to some paragraphs](https://user-images.githubusercontent.com/1672206/217926558-21f6cc36-2929-4d15-92a5-397eef5562de.png)

Right now, the only generic way[^1] to do this in the editor is with the cover block. This _works_, but the cover block's default styling/settings expect it to have an image background and are not a great fit for text. 

## What is your proposed solution?

Add left/right alignment controls to the group block.

[^1]: This is possible with the quote block, but then it would be a `<blockquote>`, and that might not be semantically correct.

**Comment by burnuser** [comment]
Also suggested in: https://github.com/WordPress/gutenberg/issues/47114

**Comment by jordesign** [comment]
Closing in favour of #47114

**Comment by annezazu** [comment]
Looks like this didn't actually get closed so closing out properly :D
