### ISSUE TITLE
Templates: Allow breaking out of the template lock programmatically from within a block

### ISSUE THREAD

**Issue by fastlinemedia** [WordPress/gutenberg#4794]
## Issue Overview
I was wondering if it's possible or being considered to break out of the template lock programmatically while in the editor. Currently I only see that the template lock can be setup on the server side.

My use case is that I'd like to create a locked template for my CPT, while giving users the ability to unlock the template and use the full editor if they desire. This would be on a per-role basis. So for example, an admin might be able to break the template lock, but an author would not.

I've spent some time in the Gutenberg code and would be happy to try my hand at a pull request if this sounds like a good idea. I know everyone is busy prepping for the big day :) Let me know what you think! 

## Possible Solution
Last time I checked, it looked like `templateLock` was a prop being passed down the line rather than part of the store. I'd probably need a little guidance but I think making it part of the store with a selector is what needs to happen here.

**Comment by jasmussen** [comment]
If you'd like to take a stab at a PR, I think it likely you'd find someone happy to merge it. The use case seems completely valid.

If you'd like further input, you are most welcome in the [WordPress core slack](https://make.wordpress.org/chat/), channel #core-editor. For now closing this as answered :) go forth and conquer, and thank you!
