### ISSUE TITLE
Adding theme.json to themes that don't support full site editing makes the alignments wide/full controls dissapear form all the blocks.

### ISSUE THREAD

**Issue by Zsolt-R** [WordPress/gutenberg#47959]
### Description

On themes that don't support full site editing the alignment controls wide/full disappear when you add theme.json.
This happens after the Gutenberg update v15.1.0

Add a theme.json file to any older theme, ex Twentytwentyone and you will notice the controls wide/full disappearing.

### Step-by-step reproduction instructions

I just noticed this problem in Gutenberg version 15.1.0
With a clean WordPress installation, created a test child theme containing a minimum amount of files:

style.css
index.php
functions.php with only  `add_theme_support( 'align-wide' );`

1) Create a new page and insert a cover block and you have the align wide/full controls
2) Then add a basic theme.json with only this content:
`{ "$schema": "https://schemas.wp.org/trunk/theme.json", "version": 2, "settings": { "layout": { "contentSize": "650px", "wideSize": "1200px" } } }`
the align wide/full disappears from the cover block and all the blocks that had alignment support before adding the theme.json file.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/14840519/218062008-233d05c4-0350-4b23-999c-be33648f6f7e.png)
![image](https://user-images.githubusercontent.com/14840519/218062325-22de4391-0d07-439c-be7f-3dac01fb0943.png)

### Environment info

WordPress Version 6.1.1
Gutenberg 15.1.0
Custom Theme / TwentyTwentyOne
Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @Zsolt-R,

Thanks for the report.

I would like to close this issue as I believe this issue is the same as https://github.com/WordPress/gutenberg/issues/47857 and will be fixed by #47961.
