### ISSUE TITLE
Allow convert to blocks for other block types

### ISSUE THREAD

**Issue by fastlinemedia** [WordPress/gutenberg#4795]
## Issue Overview
My apologies if this is already possible with transforms, I couldn't tell from the docs. I have a block that I'd like users to be able to "convert to blocks" similar to what you can do with the Classic Text block. That looks like a really powerful catch-all for converting a string of HTML into blocks. 

I did notice that I can call `setUnknownTypeHandlerName( 'my-plugin/my-block' )` to make that happen but that doesn't seem like a very safe solution. Thanks!

**Comment by youknowriad** [comment]
Not sure I understand the question?

If you want your block to be a possible resulting block of the "convert to blocks" actions, you can do this by implemeting a "raw" transforms (not documented yet #4578). Example here https://github.com/WordPress/gutenberg/blob/master/blocks/library/image/index.js#L69-L87

If you want to allow your block to be transformed to other blocks (using the block switcher for instance), it's also done using the transforms property (but this time it's the type: "blocks")

**Comment by fastlinemedia** [comment]
Thanks, @youknowriad! I actually want my block to be transformed to other blocks just like the Classic Text block. I played around with transforms but I couldn't figure out how to do a catch-all transform like that.

![screenshot 2018-02-01 09 16 37_preview](https://user-images.githubusercontent.com/2453483/35692603-a7500938-0730-11e8-9945-f801522ec749.png)

Is it possible to do something like this with transforms? 

https://github.com/WordPress/gutenberg/blob/master/editor/components/block-settings-menu/unknown-converter.js#L38

**Comment by youknowriad** [comment]
@fastlinemedia I think you probably could do it since `wp.blocks.rawHandler` is exposed but I don't believe it's documented yet cc @iseulde

**Comment by iseulde** [comment]
Yes, I see no reason to not keep it exposed. We should add the button to the HTML block as well, which could be a good example on how to do it for other blocks.

**Comment by iseulde** [comment]
And yes, I should add a read me file for it :)

**Comment by fastlinemedia** [comment]
That would be great. I'll dig into `wp.blocks.rawHandler` in the meantime, thanks!

**Comment by SuperGeniusZeb** [comment]
The <kbd><samp>Convert to Blocks</samp></kbd> option has now been added to the Custom HTML block.

**Comment by aaronjorbin** [comment]
This needs documentation to be closed out.

**Comment by chrisvanpatten** [comment]
I think we might be blocked on writing documentation by the potential changes to the raw handler to separate from pasting, but maybe @iseulde could help clarify here whether this might be impacted in those changes?

**Comment by youknowriad** [comment]
So the rawHandler API is now automatically documented as part of the blocks module https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-blocks/#rawHandler

I think it can be enhanced as this is pretty minimal but I think it's fine to close this issue now.
