### ISSUE TITLE
Raw handling: Copy/pasting from text editor causing errors

### ISSUE THREAD

**Issue by firepainting** [WordPress/gutenberg#47968]
### Description

Before this issue, when I Ctrl+V onto Gutenberg Visual Editor (copied from a text editor--plain text, all words, no HTML), each paragraph would be pasted automatically as a block. This is true until my last blog post on January 14, 2023.

(I write first drafts on a text editor, then copy-paste them all onto the Visual Editor.)

But now, the text would all go into one huge block. 

Unordered lists would have their own block, but then paragraphs after them would have their own block but they are nested as if they were another /list block. (I did not experiment on this any further but it's kinda messed up!) Before, there was no nesting. It would just paste everything in separate blocks--whether paragraphs or lists--then I formatted as I liked.

Here's an example (issue persisting):
![Copy Paste Issue](https://user-images.githubusercontent.com/50393421/218087646-a28ade45-0a5d-4b16-a231-13a11172f45d.png)

For the second issue, every time I Ctrl+V, it always yields a preview error. (This was not the case before also.) To view what I just pasted, I would have to click Save, then refresh the page.

![Preview Error](https://user-images.githubusercontent.com/50393421/218087905-a43633ef-2569-46f0-ae38-a55465569c6f.png)

### Step-by-step reproduction instructions

1. Write draft on a text editor
2. Save draft: example.txt
3. Copy-paste everything from example.txt onto Gutenberg Visual Editor (blocks). Note: It's Ctrl+V, NOT Ctrl+Shift+V

### Environment info

- WordPress version: 6.1.1
- Gutenberg version: I can't find it, sorry.
- Active theme: Astra Version 4.0.2
- Browser: Firefox Developer 110.0b9 (64-bit)
- Device: Lenovo ideapad laptop with Linux Mint 21.1 Cinnamon

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by firepainting** [comment]
[Similar/relevant Reddit post.](https://www.reddit.com/r/Wordpress/comments/103z72s/copy_and_paste_problem_in_both_com_and_org/)

**Comment by annezazu** [comment]
@firepainting thanks for opening this! Can you share an example of a txt file that we can use to replicate? What text editor are you using specifically?

**Comment by firepainting** [comment]
I could not share my .txt files but I just made a sample:
[copy paste sample.txt](https://github.com/WordPress/gutenberg/files/10712919/copy.paste.sample.txt)

I tested this with my old .txt files and had the same outcome.

I use [FocusWriter](https://gottcode.org/focuswriter/) 1.8.4. 

Side note: Coincidentally, I also found a bug on FocusWriter (I just added its PPA, installing its latest version), in which pasted (Ctrl+V) text from there onto Gutenberg Visual Editor would look like this (it's also a .txt file):
`</head> <body> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <p><br/></p>`

FocusWriter's dev replied to me and said the issue's now fixed and it will be in the next release. Unfortunately he does not seem to have his Issues available publicly.

Anyway, FocusWriter's issue is only with the HTML tags, but the issues of copy/pasting I described here are absolutely the same (including the preview error).

For testing purposes I am currently using the text editor [xed](https://github.com/linuxmint/xed) version 3.2.8.

Thank you.

**Comment by ndiego** [comment]
Hi @firepainting, I took a look at the sample text file that you provided. I am on a Mac, but I tried opening in Word, Pages, and TextEdit. In all applications, the text provided was just one large block of text. After experiementing more, it looks like you need to add blank lines in the text file, then the WordPress editor recognizes each line of text as an individual paragraph. So something like this:

```
This block is copy-pasted (Ctrl+V) from a .txt file into Gutenberg Visual Editor. Text after ["ENTER" KEY]

should be in a new block already (on a new line)... but apparently is not. ["ENTER" KEY]

This block is copy-pasted (Ctrl+V) from a .txt file into Gutenberg Visual Editor. Text after ["ENTER" KEY]

should be in a new block already (on a new line)... but apparently is not. ["ENTER" KEY]

An example for lists:
- item
- item
- item
```

Can you test this and see if it works on your end? Thanks!

**Comment by firepainting** [comment]
Hi @ndiego and thank you!

Using the text editor _xed_, yes, I do get the expected formatting after adding single blank lines. I also do not get the preview error upon Ctrl+V.

_FocusWriter_ unfortunately has not released a bugfix yet so I think this is irrelevant for now. (Issues are still persisting.)

The workaround I have for now is using _LibreOffice Writer_ (version 7.5.1.2). It's working flawlessly. **However, I don't use blank lines here.** (I have set the "Spacing below paragraph" to "1 line," which is also true for FocusWriter.)

**Comment by firepainting** [comment]
PS: On LibreOffice Writer, files are saved as `example.odt`, NOT `example.txt`. When using `example.txt` I believe the issues would also persist, albeit looking slightly different, but I did not experiment on this further.

**Comment by ndiego** [comment]
Thanks for the additional info. For simple .txt files, you do need to add blank lines to trigger the creating of Paragraph blocks, so I believe everything is working as expected. Once FocusWriter fixes their bug, you should be in good shape. Let me know if you think we can close this issue. Thanks!

**Comment by firepainting** [comment]
Glad it's now working!

Is this issue something that's likely to happen again in the near future, though? I was hoping someone could explain what happened there, or if it was intended, someone confirm it. (I'm no developer and don't follow WordPress Issues.) This must be a bug, right?

**Comment by priethor** [comment]
Let's close this issue, as it needs more info to be actionable. Please feel free to reopen again if there is more information. 🙏

**Comment by priethor** [comment]
Closing this issue as it seems to be working as expected. Please feel free to reopen again if there is something actionable. 🙏
