### ISSUE TITLE
Need to run PHPUnit for code coverage analysis

### ISSUE THREAD

**Issue by jaswrks** [WordPress/gutenberg#4796]
## Issue Overview
Code coverage analysis for PHP is not currently configured for Gutenberg.

## Possible Solution
Configure code coverage with PHPUnit.

## Next Actions
- [ ] Add a whitelist for code coverage in the `phpunit.xml.dist` file.
- ~~[ ] Add new NPM scripts that run code coverage analysis for PHP code.~~
- ~~[ ] Document the new NPM scripts.~~
- [ ] Use Composer for PHP scripts and use PHPUnit + codecov.io for coverage analysis.

**Comment by gziolo** [comment]
> Add new NPM scripts that run code coverage analysis for PHP code.

Isn't there anything PHP based that would able to generate code coverage? My understanding is that you shouldn't need Node.js in PHP projects.
We have code coverage enabled for JS so there might be some overlap. No idea to be honest :)

**Comment by jaswrks** [comment]
I see. The title of this issue was somewhat confusing. I only mentioned NPM as a way to run PHPUnit, since the other PHP unit test scripts are in package.json. But yeah, PHPUnit seems like the way to go. There's some discussion about this in https://github.com/WordPress/gutenberg/pull/4797

**Comment by gziolo** [comment]
Lol, I didn't quite get what you meant at first :) It totally makes sense to add it as proposed in #4797.  Thanks for working on it 👍

**Comment by danielbachhuber** [comment]
Filing against the `Ideas` project for later consideration, per https://github.com/WordPress/gutenberg/pull/4797#issuecomment-393294468
