### ISSUE TITLE
New Navigation Browse Mode does not work with pagelist

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#47977]
### Description

A) If you use only pagelist as navigation content (a very common start with navigation), "Navigation" is not shown at all in left sidebar - Browse mode
B) If at least one additional link is added, "Navigation" is shown and you can navigate to the single link.
But pagelist is shown as "Pagelist" without the pages within. => No navigation to pages.

### Step-by-step reproduction instructions

1. Add some pages
2. Enter site editor
3. Configure Navigation with pagelist and at least 1 additional Link.
4. Try to navigate to certain page (= hidden in pagelist) in Browse mode in the left sidebar

### Environment info

WP 6.1.1
Gutenberg 15.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I have confirmed this in 6.2 Beta 1 and Gutenberg trunnk. See the gif below. 

![page-list](https://user-images.githubusercontent.com/4832319/218774764-3a782a60-8d35-4763-b7cd-b7a545f907e5.gif)

**Comment by draganescu** [comment]
Hi @burnuser thanks for reporting this! I tested and it appears this no loger an issue in `trunk`:



https://github.com/WordPress/gutenberg/assets/107534/7ad02de3-4228-495b-ba47-78df8d8da8c9
