### ISSUE TITLE
Add option to open link in a new window/tab

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#4798]
I noticed that Open link in a new window/tab has been removed from the latest version 2.1 of Gutenberg. Lets add it back in again and see how it needs to be modified.

Related: https://github.com/WordPress/gutenberg/pull/4583
https://github.com/WordPress/gutenberg/issues/4571

**Comment by webdados** [comment]
Please discuss here: https://github.com/WordPress/gutenberg/pull/4583

We need to revert that situation, not opening a new ticket asking to add the option, as the option was removed in the first place.

**Comment by karmatosed** [comment]
I'm closing as the discussion can continue on that linked PR, no need to open a new issue.
