### ISSUE TITLE
Widget Importer: Extra "import" button visible when there's nothing to import

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#47982]
### Description

When there's nothing to import and you add a new template part, an extra "import" option appears that is always in a disabled state.

I also noticed the import option is under "Advanced" rather than at a top line level. This feels a bit hidden and I'm not sure why/where that decision was made but wanted to note!

### Step-by-step reproduction instructions

1. Create a new site using a block theme. 
2. Open the Appearance > Editor. 
3. Add a new template part.
4. Notice there's an import button visible despite there being nothing to import. 

### Screenshots, screen recording, code snippet

When there's nothing to import: 
https://user-images.githubusercontent.com/26996883/218203172-e6332fe2-458d-41cc-95ef-4e299a274b0a.mov

When there's something to import:

<img width="287" alt="Screen Shot 2023-02-10 at 1 35 01 PM" src="https://user-images.githubusercontent.com/26996883/218203380-f57211cc-77c5-46a9-bd75-40aed7032447.png">

### Environment info

- WordPress 6.2 beta 1
- No GB installed
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Noting that this still appears with beta 3 but it has slightly changed:

<img width="312" alt="Screen Shot 2023-02-23 at 10 08 35 AM" src="https://user-images.githubusercontent.com/26996883/220992829-7baf0e0e-ce67-4a5a-aa1b-e7afb54215b7.png">

**Comment by Mamaduka** [comment]
I’ve a potential fix and will push it tomorrow.
