### ISSUE TITLE
Local visual regression test time out

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#47988]
## How to reproduce

- `npm run distclean && npm ci`
- In two separate tabs:
  - First run `npm run storybook:e2e:dev`
  - Once storybook has launched, in a separate tab run `npm run test:e2e:storybook -- --update-snapshots`

### What should happen

The snapshots are generated correctly in a few seconds

### What is currently happening

The tests time out and the snapshots are not generated

## How to fix it

I traced the regression back to PR #46459

Removing the `auto: true` option from this file fixes the issue:

https://github.com/WordPress/gutenberg/blob/8dee3e6764da100b20ad9abd41af5df086b5f42f/packages/e2e-test-utils-playwright/src/test.ts#L156

PR #46459 assumed that all Playwright e2e tests in the repository load the editor, but that assumption is not correct for visual regression tests

**Comment by ciampo** [comment]
@WunderBart @kevin940726 and @t-hamano , could you help with this one?

I'm not as well versed as you may be in Playwright.

Tests in `test/storybook-playwright/specs` (which `import { test } from '@wordpress/e2e-test-utils-playwright'`) are currently timing out — is there any way we can refactor the code so that they can opt out from the code that tries to initialise the editor?

Thank you!

**Comment by ciampo** [comment]
@bph we may want to delay advertising local visual regression testing until this issue isn't ironed out

**Comment by t-hamano** [comment]
I think `@wordpress/e2e-test-utils-playwright` is [E2E utility for WordPress](https://github.com/WordPress/gutenberg/tree/trunk/packages/e2e-test-utils-playwright#e2e-test-utils). Can we solve this problem by importing directly from Playwright as follows? However, I'm not sure if this is the appropriate method, since the snapshot file name would change.

```diff
diff --git a/test/storybook-playwright/specs/font-size-picker.spec.ts b/test/storybook-playwright/specs/font-size-picker.spec.ts
index 6aa11e8926..c2f6fc3580 100644
--- a/test/storybook-playwright/specs/font-size-picker.spec.ts
+++ b/test/storybook-playwright/specs/font-size-picker.spec.ts
@@ -1,7 +1,7 @@
 /**
- * WordPress dependencies
+ * External dependencies
  */
-import { test, expect } from '@wordpress/e2e-test-utils-playwright';
+import { test, expect } from '@playwright/test';
```

Also, this may be an issue in my environment, but the Storybook now only shows components that include E2E testing 🤔

![storybook](https://user-images.githubusercontent.com/54422211/218254528-0e545c82-cba6-4185-8b88-a110ee63571e.png)

**Comment by ciampo** [comment]
> Can we solve this problem by importing directly from Playwright as follows?

That seems to solve it! I'm not sure if there are any implications, but if we ever encounter any I guess we can create a specific version of `test` and `expect` for Storybook visual regression testing 

> the snapshot file name would change.

This shouldn't be too bad, since VizReg for now is only supposed to be used locally (the snapshots should be gitignored)

> Also, this may be an issue in my environment, but the Storybook now only shows components that include E2E testing 🤔

That is expected, so that only e2e-focused stories are compiled and served :) You can read [here](https://github.com/WordPress/gutenberg/blob/fd058dff348903a1a2545f31e4c997ce7a5d8faa/test/storybook-playwright/README.md) for more info

**Comment by kevin940726** [comment]
Oops, I didn't know that `e2e-test-utils-playwright` is used by storybook visual testing.

I agree with @t-hamano here though, the package is designed to work with a WordPress instance, we want to keep it opinionated for that specific use case. You can always just use the official `@playwright/test` for anything else though, `expect` is just a re-export, and `test` is extended in the `test.ts` file. You can go there and copy any part that's relevant to your setup to create your own `test` function. Most of the utils are re-exported as well, so you can also do `new Editor( { page } )` for instance to create an `editor` POM.

**Comment by ciampo** [comment]
> Oops, I didn't know that e2e-test-utils-playwright is used by storybook visual testing.

It's a relatively recent addition that we did to help testing some changes in the components package, still a bit rough around the edges (and for now working only locally).

Awesome, thank you both for the extra context 🙏

**Comment by ciampo** [comment]
> we may want to delay advertising local visual regression testing until this issue isn't ironed out

@bph All solved, feel free to ignore this message :)
