### ISSUE TITLE
iframe editor seemingly breaks react components context for third party libraries

### ISSUE THREAD

**Issue by antpb** [WordPress/gutenberg#47983]
### Description

Hello! Feel free to close if too support-y but I thought this might need communication to other block makers and worth noting in an issue for searchability. :)

I have [a block called Three Object Viewer](https://wordpress.org/plugins/three-object-viewer/) that utilizes Three.js and a react library on top of it to build 3D spaces. I noticed in the 15.1 release of Gutenberg that the iframe editor was enabled by default in the single post editor for block based themes and found that it posed some challenges in the context of the WebGL renderer now that it is in an iframe. For whatever reason, it loses half of the context but still seems to get the enqueued scripts to do 3D things using the library in my React app. I'm not quite sure how to adjust but thought I'd open the issue while I investigate. 

I suspect that this sort of issue will not be specific to the 3D library and something more fundamental that has changed. Maybe not a bug if able to work around, but would be good to identify what needs to be communicated to block developers ahead of 6.2

Here's a screenshot of the error in my app.
![Screenshot 2023-02-10 at 5 20 25 PM](https://user-images.githubusercontent.com/8985705/218220626-27da7281-6f0b-4744-9504-1b83176538db.png)

## To reproduce:
1) Install/Activate Three Object Viewer plugin in a fresh 6.2 WordPress
2) Add 3D Environment Block
3) see hundreds of errors.

Is it possible I'm missing some new flags on a block level to get it out of the iframe? I'm wondering if this could be a setting in block.json.

My plugin is on github and you can find the block.json here: https://github.com/antpb/three-object-viewer/blob/main/blocks/environment/block.json

And if you're extra curious, you can check out the plugin in your plugin directory and `nvm use 16 && yarn && yarn run build` just build again on any changes to the components. 

### To reproduce:
1) Install/Activate Three Object Viewer plugin in a fresh 6.2 WordPress
2) Add 3D Environment Block
3) see hundreds of errors.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/8985705/218221727-1827a5ff-d737-4995-bfaa-2d1823f631d7.mov

### Environment info

 WordPress 6.2 Beta 1 (Also any site using Gutenberg 15.1 + a Site Editor Enabled Theme)
All Browsers
MacOs

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by antpb** [comment]
One bit of information that might be helpful is that I am getting an error of `THREE.WebGLRenderer: Context Lost.` Which I think means that the element unmounted and lost the context of the renderer. Which would make sense why I'm getting a blank grey screen.

Is it possible that there is something happening between the iframe that mounts and unmounts the components? I'm kinda lost. I've never had issues with this renderer in an iframe in the past (and I've done some hacky stuff with it) This feels more like the react app of the editor tries to render for a moment then unmounts and partially catches it in the iframe?

**Comment by antpb** [comment]
Hello, heres a video with more illustration of what I'm seeing and some of where I think the issue is. My gut feel is that this is related to the iframe not having logic or components from the editor. I'm really not sure how to explain what I'm seeing because it's been hard to debug through the iframe. In the video I isolate some logs to the editor in an attempt to debug, but I cant seem to make anything come through the iframe and instead it logs or does logic in the parent.

https://user-images.githubusercontent.com/8985705/218266368-73b48b18-bd9f-425c-ba0e-b4f696452654.mov

**Comment by ellatrix** [comment]
Thanks for the report! I'll have a look at the plugin.

**Comment by ellatrix** [comment]
In the meantime, don't worry, we are reverting the change for 6.2: #48076.

**Comment by annezazu** [comment]
Going to move this out of the 6.2 board since this change is being reverted. Let me know if that needs to change!

**Comment by antpb** [comment]
Thanks all for the quick revert in the core iframe. That definitely buys me some time. I've been making attempts at solving this on and off and had one new interesting development. I suspected that there was some issue with webgl1 and webgl2. The behavior felt like extensions are missing.

So heres one screenshot logging the webgl version before and after installing Gutenberg in a 6.2 that causes the error. In the first, it uses WebGL2 and in the second it with the iframe it uses WebGL1. It seems to be missing all the extensions that make WebGL2 apps work

Before:
<img width="565" alt="Screenshot 2023-03-08 at 10 14 33 PM" src="https://user-images.githubusercontent.com/8985705/223915536-68bc6d73-14b3-407c-b2c9-8b063c4c4941.png">
After installing Gutenberg 15.3.1:
<img width="808" alt="Screenshot 2023-03-08 at 10 14 16 PM" src="https://user-images.githubusercontent.com/8985705/223915567-d67dc7c3-ebe2-4703-ad1e-bf014a92faff.png">


Still debugging how this is switching because of an iframe but thought I'd document here as I learn more.

**Comment by antpb** [comment]
I'm happy to report that I found a fix upstream in Three.js and this was failing due to a check in the engine where it determines if the renderer is WebGL2 with an `instanceof` check. If curious, you can see the overview of the change here: https://github.com/mrdoob/three.js/pull/25733

Thanks for talking this though and allowing me some time to find a fix. I'm excited for all the new editor changes, especially now that we're compatible :D
