### ISSUE TITLE
Change Cover Video to Image on block

### ISSUE THREAD

**Issue by dthenley** [WordPress/gutenberg#47994]
## What problem does this address?
Performance loading on mobile. Users have impact on performance when loading a large video over a low speed network.

## What is your proposed solution?
Creating a separate mobile background option on cover block to improve performance.

**Comment by skorasaurus** [comment]
Hello, 
Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/18962 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
