### ISSUE TITLE
Allow Naming Blocks/Groups to make it easer do navigate

### ISSUE THREAD

**Issue by le-slap** [WordPress/gutenberg#47992]
## What problem does this address?
I am currently creating a website using my custom made theme and the homepage is quite long, with a lot of sections and elements which i use groups for to separate them. But as i create more and more sections, it becomes a pain in the eyes when i tried to edit an specific section i have to kind of click on each group until i finally find the section i need.

## What is your proposed solution?
Allowing to name the blocks just like with can set custom Classes would be ideal for cases like these. I hope i am not the only one requesting this

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/33583 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

Please reopen and clarify if I misunderstood your request and that issue doesn't cover what you're looking for.
