### ISSUE TITLE
Link UI opens in list view for unconfigured Nav Link blocks added via block editor canvas

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#48028]
When creating a Nav menu _in the canvas_ you might add an item and click away before "configuring" it (i.e. setting a link...etc). If you do this and then reselect the (parent) Nav block then you will see the Link UI pops up in the list view automatically.

https://user-images.githubusercontent.com/444434/218489231-f2e70631-0bfc-49d6-8975-b0108f814ce3.mp4

**Comment by scruffian** [comment]
I think the same rationale applies to this issue as to [this one](https://github.com/WordPress/gutenberg/issues/47829#issuecomment-1427961377).

**Comment by scruffian** [comment]
I think this has been fixed.
