### ISSUE TITLE
Add indicators to all drilldown menu items in browse view

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48022]
Part of https://github.com/WordPress/gutenberg/issues/36667

With https://github.com/WordPress/gutenberg/pull/47777 merged, clicking a template or template part in browse view will expose a subsequent panel in the drilldown navigation:

<img src="https://user-images.githubusercontent.com/846565/218449666-6b5a3bdf-ec9a-4029-855b-56e70f0a859b.gif" width="300">

At the root level the menu items indicate this behavior by displaying a chevron:

<img width="357" alt="Screenshot 2023-02-13 at 11 43 34" src="https://user-images.githubusercontent.com/846565/218449170-789096f3-0a1c-4224-9af3-c5be61d4f177.png">

We should apply this convention to all menu items in browse view so that users are able to understand upfront whether a menu item will expose a new panel or have a different behavior.

**Comment by richtabor** [comment]
> We should apply this convention to all menu items in browse view so that users are able to understand upfront whether a menu item will expose a new panel or have a different behavior.

I think so too.

**Comment by ghost** [comment]
+1

**Comment by priethor** [comment]
Should we consolidate this issue in #48591? If I understand correctly, that issue covers this and more cases, right?
