### ISSUE TITLE
Outline button ignores custom padding from global styles

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#48037]
### Description

If you edit the global style padding dimension for the button block, only the "fill" button takes the new dimensions.

### Step-by-step reproduction instructions

1.  In a default install with only Gutenberg and the 2023 default theme, go to Edit Site > Styles > Blocks > Button > Layout
2. Open the Dimensions panel and change the padding to something drastic so you'll notice the issue 
3. Edit a page on the site, add the button block
4. Add a normal "fill" button then add another button and change to the "outline" style
5. Notice the outline button does not take the new dimensions

### Screenshots, screen recording, code snippet

<img width="1063" alt="Screen Shot 2023-02-13 at 9 24 02 AM" src="https://user-images.githubusercontent.com/1781226/218515066-5e89ba97-4d9b-43a0-9e4e-bf669a536e40.png">
<img width="553" alt="Screen Shot 2023-02-13 at 9 24 26 AM" src="https://user-images.githubusercontent.com/1781226/218515090-8c1f09bf-9c3e-4424-bd4a-96533921b991.png">
<img width="535" alt="Screen Shot 2023-02-13 at 9 24 30 AM" src="https://user-images.githubusercontent.com/1781226/218515095-600ddc76-4975-469c-b289-7d5c6187d1b4.png">

### Environment info

- wp 6.1.1
- gutenberg 15.1.0
- chrome
- macos

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hi @bradhogan, thanks for reporting. This issue is actually now resolved in WordPress 6.2 Beta 1 and Gutenberg trunk. Therefore, I am going to close this out. Thanks!
