### ISSUE TITLE
Shadow panel not showing for Group block

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#48038]
### Description

Looks like Shadow has been added to the Group options (at least in the global styles) but there's not an option to choose a shadow option(s) once inside the panel.  [Here's a video](https://soapbox.wistia.com/videos/AbQ5tLZ5li) better showing the issue.

Love that this is finally coming into the editor.  It's great to see it working with the global buttons block (would love to see it in the individual button block panel as well - same with above Group block).  

#46502

### Step-by-step reproduction instructions

[See video](https://soapbox.wistia.com/videos/AbQ5tLZ5li)

### Environment info

- wp 6.1.1
- gutenberg 15.1.0
- chrome
- macos

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
Hey @bradley2083 — it looks like that's a remnant of an earlier concept of placing borders and shadows together. The [singular "Button" block ](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/button/block.json#L91)is the only block to support the new shadow control (for now) — as it's still very new.

**Comment by richtabor** [comment]
We do need to fix some of those headers though; "Border & Shadow" — but should just say "Border". 


Here's what I'm seeing for the Group block (trunk) in the Global Styles sidebar. 

https://user-images.githubusercontent.com/1813435/218558210-db560321-516f-47d6-8747-d917400834f3.mp4

And for comparison, here's what I'm seeing for the Button block: 

https://user-images.githubusercontent.com/1813435/218558510-bd28011a-5fbc-4b04-88ff-65e68f453e15.mp4

**Comment by bradhogan** [comment]
Thanks @richtabor

**Comment by skorasaurus** [comment]
https://github.com/WordPress/gutenberg/pull/48043 closes this PR
