### ISSUE TITLE
Misaligned per-block CSS label

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#48047]
The "Additional block CSS" label for the per-block CSS should be aligned with the other contents of the panel (like the global additional CSS control is). 

## Visual
<img width="825" alt="CleanShot 2023-02-13 at 16 31 04" src="https://user-images.githubusercontent.com/1813435/218579008-76451966-bbae-4e56-a79c-46d00ee470cc.png">

**Comment by glendaviesnz** [comment]
@richtabor there seems to be a difference between the left padding on the top-level global styles panel and the block-level ones. Is this supposed to be the case? For example, if I set the same padding on the additional block CSS section as on the global styles one, it fixes the alignment issue, but it is more indented than the items above it -  but in global styles, they line up as more of a left padding for all:

| Global | Block |
|--------|-------|
| <img width="291" alt="global-css" src="https://user-images.githubusercontent.com/3629020/218600968-97ee751e-9782-4844-b53b-14b32010106e.png">  | <img width="285" alt="block-css" src="https://user-images.githubusercontent.com/3629020/218601022-ee60fa8a-0310-4d3f-8625-c250337af88e.png">|

should I just match the left padding of the other items in the block panel, or does that padding need to be adjusted to match the global styles panel?

**Comment by richtabor** [comment]
Good point. I'm good with resolving the padding discrepancy between the parent and child panels as well. I don't want to index too much on this, as it'll adapt when we move it closer to the Browse Mode UI — but a small padding tweak to consistently align all the controls would be good. 

Here's what that'd look like, with the Additional block CSS tweak included as well: 

<img width="731" alt="CleanShot 2023-02-14 at 08 09 45" src="https://user-images.githubusercontent.com/1813435/218748279-e3cf85a4-e154-46fb-b173-fa70cca835c9.png">

**Comment by ghost** [comment]
The reason for the inconsistency is not in the actual button, but the space around it as mentioned above. The lower panel has padding where the top one doesn't.

![Screenshot 2023-02-14 at 5 58 52 PM](https://user-images.githubusercontent.com/118618474/218805689-f0905063-e0fd-4f6b-898b-12f433f665a5.png)
![Screenshot 2023-02-14 at 5 59 36 PM](https://user-images.githubusercontent.com/118618474/218805917-546ed8a3-394f-4a45-b578-344990ab3f1c.png)

Notice the padding is also inconsistent with the panel for style variations, where margin is used.

![Screenshot 2023-02-14 at 6 01 31 PM](https://user-images.githubusercontent.com/118618474/218806196-4c070f5f-b157-45ec-a956-fdb832ff9ee7.png)
![Screenshot 2023-02-14 at 6 02 18 PM](https://user-images.githubusercontent.com/118618474/218806381-fc9541f2-8a08-4e73-ba0d-f49c60f5e7d8.png)

I suggest choosing one value for padding to apply to all the panels, and removing any extra margins that are now being used on e.g. the quote preview and the style variations panel.

**Comment by glendaviesnz** [comment]
I have made a [start on this here](https://github.com/WordPress/gutenberg/pull/48087), but still a bit of work to do in terms of making sure everything is the same across all the screens. I am AFK for the next week or so, so happy for someone else to pick this up and finish off, otherwise I will finish it off when I am back.

**Comment by jordesign** [comment]
With this control now being moved into the 'Advanced' section - it seems this issue no longer needs to be resolved?

<img width="314" alt="Screenshot 2023-07-27 at 5 28 50 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/9654b78f-40d5-451d-8d63-57240fe5e10b">

**Comment by t-hamano** [comment]
> With this control now being moved into the 'Advanced' section - it seems this issue no longer needs to be resolved?

I agree. It was moved to the Advanced panel as one of #49428. I am closing this issue.
