### ISSUE TITLE
Explore a range-based aspect ratio control

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#48080]
Here's an interesting concept around selecting an aspect ratio, referenced from [Twitter](https://twitter.com/frantzfries/status/1602458328839372800?s=61&t=i5hspOZOI0erJFJ1Wt1kjg). 

I'm not entirely sure if this works 100%, but it may be worth exploring as a more intuitive alternative to the design proposed in https://github.com/WordPress/gutenberg/issues/38990#issuecomment-1396621330. Thoughts? 

https://user-images.githubusercontent.com/1813435/218844527-1200c9d4-4b0c-4654-944b-a0f7809de432.mp4

**Comment by amjadr360** [comment]
Here is one concept. 

 

https://user-images.githubusercontent.com/32260742/219788284-9af17e01-ddba-442e-92dc-5f284d8dd125.mp4

**Comment by richtabor** [comment]
Played around a bit with this concept today. I think something like this could work. 

It feels less technical and more approachable. I have the core/post-featured-image on the left in the viewport by itself, though it won't always be the case that it's so focused on — especially if we add this to the core/image block. Thoughts @mtias?

https://user-images.githubusercontent.com/1813435/229638928-246f2e1c-2391-41b7-a39c-693fae74435e.mp4

**Comment by richtabor** [comment]
Another benefit of this approach would be that core could have as many ratios as needed in core, and that doesn't make the control harder to use/more information dense. I even added 5:7 and 7:5 in the video above, which core does not support currently. 

Of course, we should still have theme.json way to disable all, or some of the ratios.

**Comment by richtabor** [comment]
This is an alternative to something like this https://github.com/WordPress/gutenberg/issues/48110, or the current select.

**Comment by richtabor** [comment]
_Maybe_ needs some sort of reset, other than the toolbelt "Reset" control. Maybe.

**Comment by ndiego** [comment]
I like the slider approach a lot. So long as this control is extensible, either in theme.json or with a filter, this would be a great addition. 🙌

**Comment by justintadlock** [comment]
The latest concept looks much better than the ones shown earlier in the thread. Putting my user hat on, I think I could grasp what's happening with the live preview in place.

I'm not sold on it, though. I feel like a slider works better when moving from smaller to larger values. I prefer the [pop-over experience](https://github.com/WordPress/gutenberg/issues/48110). Plus, it takes up less real estate in the sidebar.

Either option works better than the current solution in core.

> So long as this control is extensible, either in theme.json or with a filter, this would be a great addition.

Definitely agreed on this. It would be awesome to define the set of aspect-ratios from `theme.json`.

**Comment by richtabor** [comment]
> I prefer the https://github.com/WordPress/gutenberg/issues/48110. Plus, it takes up less real estate in the sidebar.

I suppose this could be in a popover, merging the two concepts. 🤔

**Comment by jasmussen** [comment]
Good stuff, great explorations. I would echo that I'd like to see a merger of the concepts. In part to achieve some compression in the inspector, which can otherwise grow somewhat long even if we have the split tabs now. There would also be some duplication in Global Styles > Blocks > Image, where (presumably?) you'd be able to set a default aspect ratio, and you'd also have an image preview at the top. By putting it in a flyout you can potentially have space for both a slider and explicit width/height inputs.

One challenge that would be hard to explore — I really appreciate your previous dropdown with common aspect ratio presets and small icon previews. Would it be at all possible to combine that with the slider? Perhaps slider snap points and tooltips when you near one of the common ones? Not quite similar to [resize visualization](https://github.com/WordPress/gutenberg/pull/45056#issuecomment-1501653790), but conceptually adjacent.

**Comment by abruenin-gm** [comment]
Maybe, when working on this, also a check box 'Keep aspect ratio' near Widht and Height could be added? When choosing Image Dimensions between 25,50,75 and 100%, then the aspect ratio is kept. But when manually editing Width or Height, this breakes the aspect ratio and the other value needs to be calculated manually.
It would be nice to just check some 'Keep aspect ratio' checkbox, enter eg. Height and the Width would be calculated automatically so the image keeps the aspect ratio (and vice versa).

**Comment by jasmussen** [comment]
Just to connect dots, I shared a slider based mockup based on these conversations in https://github.com/WordPress/gutenberg/issues/38990#issuecomment-1540192936

**Comment by richtabor** [comment]
Closing this as not currently planned.
