### ISSUE TITLE
Add aspect ratio support to image block placeholder state

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#48081]
The `core/image` block does not currently allow for dimensions or aspect-ratio (https://github.com/WordPress/gutenberg/issues/38990), before an image is added to the block. 

I propose we remove the need to set an image in place, before assigning any dimensions/aspect ratio, to further simplify designing within the editor. One shouldn't be required to have an image in mind before laying out the contents of a page.

Note that this issue is blocked by first adding support for aspect ratio within the Image block (https://github.com/WordPress/gutenberg/issues/38990).

**Comment by gaambo** [comment]
I'd like to mention #39457 here as well. It's about keeping a set image size when changing the image. And IMHO, it's as important as the aspect ratio for patterns.
