### ISSUE TITLE
15.1 Breaks Width Options in Hybrid Themes

### ISSUE THREAD

**Issue by eric-michel** [WordPress/gutenberg#48082]
### Description

Wide and full alignment options have disappeared in top level blocks in hybrid themes (themes that use `theme.json` but have not fully adopted block-based templates).

### Step-by-step reproduction instructions

1. Install the `Twenty Twenty-One` theme.
3. Add a `theme.json` file with settings of your choice.
4. (Optional) Install the Gutenberg plugin version 15.0.1 or prior.
5. Observe that top level blocks can have their width options set as usual (for instance, Group blocks can be set to wide or full widths).
6. Install the Gutenberg plugin version 15.1.
7. Observe that width options in the editor have disappeared for top level blocks.

### Environment info

Fresh WordPress install with the `Twenty Twenty-One` theme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @eric-michel,

Thanks for the report.

I would like to close this issue as I believe this issue is the same as #47857, #47959 and was fixed by #47961.

**Comment by eric-michel** [comment]
@t-hamano Thanks! You are absolutely correct. I searched through the outstanding issues but for some reason did not check completed ones. I will make sure to do that in the future.
