### ISSUE TITLE
[Site Editor] Identical templates load unreliably inside the Site Editor

### ISSUE THREAD

**Issue by dinhtungdu** [WordPress/gutenberg#48095]
### Description

When switching between templates that have identical content, the Site Editor shows a blank editor. Before #47777, the impact of this issue is bigger:

- From the Archive template, adding the Category/Tag template shows the blank editor (when Tag and Category templates are inherited from the Archive template). If the admin added Tag and Category templates without modification, switching between those templates also have this issue.
- https://github.com/woocommerce/woocommerce-blocks/issues/8378

### Step-by-step reproduction instructions

The #47777 fixes most use cases by a side effect, but the issue is still reproducible by following these steps:

1. With Twenty Twenty-Three activated, create a custom template with the content of the [`home.html` template](https://github.com/WordPress/twentytwentythree/blob/trunk/templates/home.html).
2. Open the Site Editor, the editor shows the Home template by default.
3. From the sidebar, navigate to the test template and select it.
4. See the blank editor.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/5423135/219009109-80a18ba1-03d7-4391-a5bf-13344fab754a.mov

### Environment info

- WP 6.1.1
- Gutenberg 55b0c385d424a84bf53809159ffa44a7141267ca

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
Can't reproduce this. Seems fixed.
