### ISSUE TITLE
Add API to data module to subscribe to store changes

### ISSUE THREAD

**Issue by atimmer** [WordPress/gutenberg#4809]
## Issue Overview

From outside React, we can now select a piece of data by using `wp.data.select`. However, there is no way to watch for changes. Plugins can also not recreate this behavior by watching for any store change because there is no way to subscribe to any store change.

I think we should add a `wp.data.subscribe` method. This method can have a comparable signature as `query`. Something like:

```js
export const subscribe = ( mapSelectorsToProps ) => ( callback ) => {
  // Implementation
};
```

You can then use this API in the following way:

```js
function handleData( data ) {
  // For example, run content analysis.
}

let dataSubscriber = wp.data.subscribe( ( select ) => {
  return {
    slug: select( "core/editor", "getEditedPostSlug" ),
    content: select( "core/editor", "getEditedPostContent" ),
    title: select( "core/editor", "getEditedPostTitle" ),
    taxonomies: select( "core/editor", "getEditedPostTaxonomies" ),
  };
}, handleData );
```

## Current Behavior

There is currently no way to watch for store changes outside React.

## Possible Solution

I have a prototype solution stashes locally. It requires rebuilding some of the work Redux does, maybe there is some part of Redux we can re-use here.

## Todos
- [ ] Tests
- [ ] Documentation

cc @youknowriad, @gziolo.

**Comment by gziolo** [comment]
This one should be concluded once #4823 is merged 👍
