### ISSUE TITLE
Wrong property name on style-engine.js

### ISSUE THREAD

**Issue by suvrodattamitu** [WordPress/gutenberg#48090]
### Description

`const lineHeight = {
  name: 'letterSpacing',
  generate: (style, options) => {
    return generateRule(style, options, ['typography', 'lineHeight'], 'lineHeight');
  }
};`

in `/wp-includes/js/dist/style-engine.js` on line 419 the name property is wrong

### Step-by-step reproduction instructions

1. go to `/wp-includes/js/dist/style-engine.js` 
2. scroll down  to line 419 

### Screenshots, screen recording, code snippet

[
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/19241468/218920635-554e6f48-1ac0-4ac2-80aa-a1aa5b2b4c7f.png">
](url)

### Environment info

WordPress version: 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ocean90** [comment]
Source in Gutenberg: https://github.com/WordPress/gutenberg/blob/9d37dbc89866a6a5426458b57dcf44aec4b4ea9f/packages/style-engine/src/styles/typography/index.ts#L68

**Comment by andrewserong** [comment]
I'll close this issue out now, thanks for opening it and submitting the PR to resolve it @suvrodattamitu! ✨
