### ISSUE TITLE
When editing a template part, the value of styles.spacing.padding in theme.json shouldn't be applied to the Site Editor wrapper

### ISSUE THREAD

**Issue by Aljullu** [WordPress/gutenberg#48098]
### Description

The Site Editor is adding top and bottom padding to the `.editor-styles-wrapper` element in the site editor. That makes sense in the case of templates because that's how they are rendered in the frontend as well. But for template parts, that shouldn't be necessary because they are rendered inside a template and `styles.spacing.padding` is not applied to them.

### Step-by-step reproduction instructions

1. With [TT3](https://wordpress.org/themes/twentytwentythree/) or any other theme with `useRootPaddingAwareAlignments` set to true in `theme.json`, go to Appearance > Editor.
2. Edit the _Comments_ template part.
3. Notice the `.editor-styles-wrapper` element has top and bottom padding (inherited from [`styles.spacing.padding`](https://github.com/WordPress/twentytwentythree/blob/trunk/theme.json#L699-L704)).

![Captura de pantalla de 2023-02-15 15-30-56](https://user-images.githubusercontent.com/3616980/219058649-cea3e7bc-1b30-443f-9f7c-0f212e59ee69.png)

Expected behavior: no padding should be applied to `.editor-styles-wrapper` when editing template parts. In the frontend, templates parts don't inherit the padding from `styles.spacing.padding`, so in the editor they shouldn't either.

While for some template parts this issue is not critical (it just makes the template part to appear lower than it should), it's more problematic when the template part occupies the entire height available, for example a header with a height of `100vh` or the Mini Cart template part in WC (see related issue: https://github.com/woocommerce/woocommerce/issues/42482).

### Environment info

- WP 6.1.
- Gutenberg 15.1.0.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tellthemachines** [comment]
Hi there @Aljullu! This should have been fixed in #54373 which was included in WP 6.4. Would you mind re-testing and checking whether it's still a problem?

**Comment by Aljullu** [comment]
You're right, @tellthemachines, this has been fixed. Thank you!
