### ISSUE TITLE
Isolated Template Part Mode is empty when editing

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#48114]
### Description

Using 6.2-beta2-55349, whenever I try to enter the isolated template part mode, it empties out the template part and doesn't show me the proper framing of the mode (a back button, resize handles, etc). 

### Step-by-step reproduction instructions

1. Use the nightly version of 6.2 beta 2.
2. Open Appearance > Editor.
3. Select a template part and select "edit" in the block toolbar to enter the isolated template part mode.
4. Notice it's broken :) 

### Screenshots, screen recording, code snippet

[Here's a recording in replay](https://app.replay.io/recording/isolated-template-part-mode-is-empty--4bc46f1a-8bd5-40f6-be1f-22bc5fe5140c?point=41862893454486275791619923172655104&time=15779) where you can get a sense of the dev environment to replicate. If you need access, just let me know either in this issue by sharing your slack username for WordPress slack or by pinging me (@annezazu) on Make Slack. 

https://user-images.githubusercontent.com/26996883/219264005-584c8a71-ff89-4416-a786-1c7a2e5e3a5f.mov

### Environment info

- WordPress 6.2-beta2-55349
- No GB
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
As far as I can tell, this problem does not seem to occur with the latest trunk. Perhaps #8063 is related. I was able to reproduce this issue by checking out the commit immediately preceding this PR (6ab97049bd). I believe this issue will be resolved in WordPRess 6.2 Beta3 as this PR has been given a backport label.

cc @youknowriad

**Comment by youknowriad** [comment]
Weird that this commit impacts template parts edit mode. Kind of seems unrelated. cc @ellatrix

**Comment by ndiego** [comment]
I am able to replicate it as well, which might also be related to [#48216](https://github.com/WordPress/gutenberg/issues/48216)

**Comment by Mamaduka** [comment]
I re-tested with WP 6.2 beta3 and could no longer reproduce the issue. The same goes for #48216.

**Comment by ndiego** [comment]
I have also tested in 6.2 Beta 3 and can no longer replicate the issue. I'm going to close this out, but if anyone else continues to experience issues, please feel free to reopen. Thanks!
