### ISSUE TITLE
Text decoration controls rendering for the Template Part block

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#48111]
### Description

I don't expect the text decoration controls to be available on the template part block. This only occurs with Gutenberg active, not the 6.2 beta. 

### Step-by-step reproduction instructions

1. Go to the Site Editor
2. Click on any template part block
3. See Typography > Decoration block supports controls

### Screenshots, screen recording, code snippet

<img width="644" alt="CleanShot 2023-02-15 at 16 06 12" src="https://user-images.githubusercontent.com/1813435/219161534-f4609790-cba7-4f3a-86ab-62e6b96b3c22.png">

### Environment info

- WordPress 6.2 Beta 2
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
I'm actually seeing this on other blocks too. 

<img width="463" alt="CleanShot 2023-02-15 at 16 32 15" src="https://user-images.githubusercontent.com/1813435/219172900-17d2a57a-3499-4ed8-b3c4-68f979836ae5.png">

**Comment by youknowriad** [comment]
Might be something with my recent refactors, I'll take a deeper look tomorrow morning.

**Comment by annezazu** [comment]
Strangely I cannot replicate with 6.2 beta 2 nor with the 6.2 nightly for today. Can't replicate both with and without Gutenberg 15.1.1. I'll try a few more test sites and report back if I can.
