### ISSUE TITLE
Stylizing captions in Image Blocks 

### ISSUE THREAD

**Issue by ddegner** [WordPress/gutenberg#48135]
## What problem does this address?
In the Site Editor -> Styles -> Blocks -> Image Block I was expecting controls to edit the font and alignment of the image captions (the text that goes under the image).

## What is your proposed solution?
Add controls to the Site Editor -> Styles -> Blocks -> Image Block

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. 

Unfortunately none of these features have been implemented but there are requests for each of these: 

This has been requested in https://github.com/WordPress/gutenberg/issues/19975 and https://github.com/WordPress/gutenberg/issues/12997 
https://github.com/WordPress/gutenberg/issues/34643 to choose the font 

https://github.com/WordPress/gutenberg/issues/44071 (for alignment of the image captions) 

In the meantime, you can use CSS to customize the font choice of the captions.

**Comment by ddegner** [comment]
Here's another discussion of it #44071
