### ISSUE TITLE
Image block: Add/remove caption option is covered by additional toolbar

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#48148]
### Description

Using 6.2 beta 2 and trying to record a demo, I noticed the add/remove caption option isn't working properly in that I can't actually see the caption field to write in due to an additional toolbar getting in the way. 

cc @jorgefilipecosta who originally implemented this https://github.com/WordPress/gutenberg/pull/44788

### Step-by-step reproduction instructions

1. Use 6.2 beta 2
2. Go to Posts > Add new
3. Add an Image
4. Select the option to show a caption
5. Notice that you can't see the caption field when you type

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/219519980-2fec193a-2ef4-455d-8ee3-5ec801e52ad1.mov

### Environment info

- WP 6.2 beta 2
- No GB
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@annezazu, can you reproduce the issue with the Gutenberg trunk? This might be related to the Popover bug we have in WP 6.2 betas.

**Comment by jamilbd07** [comment]
I tried to reproduced the issue but I found it's working fine. I am able to add/edit caption.
### **Here is my Environment info:** 
**WP:** 6.2 beta 2
**Theme**: TT3
**Plugins:** Gutenberg v15.2.0-rc.2

### Video Recording

https://user-images.githubusercontent.com/26631449/219553295-29eb170f-2e3d-4e3b-87e1-25ea93d13702.mov

**Comment by t-hamano** [comment]
This problem occurs in all blocks that have the Add/Remove Caption toolbar. And it is not reproduced in the Gutenberg trunk.

I believe the issue is about popovers as it relates to #48140 and #47923.

https://user-images.githubusercontent.com/54422211/219911588-90a187f3-54de-4ec5-8bbb-082aaa146616.mp4

**Comment by annezazu** [comment]
Great! Thanks for the sleuthing. Closing this out based on the above.

**Comment by t-hamano** [comment]
I have confirmed that this issue is not reproduced in WordPress 6.2-beta3-55401 _without_ Gutenberg enabled.
