### ISSUE TITLE
[Site Editor] Template List in Site Editor Sidebar Doesn't Scroll

### ISSUE THREAD

**Issue by ersatzpenguin** [WordPress/gutenberg#48144]
### Description

When first opening the Site Editor and selecting "Templates" to view the currently available templates in the left sidebar, the list does not allow scrolling—causing any templates that extend beyond the space available in the browser window to be inaccessible.

Clicking on one of the templates to set focus doesn't fix the issue, either.

In order to work around this issue, you need to choose to "Edit" a template, then use the "Browse all templates" option in the top dropdown of the template editor. This then displays the site's templates in the normal "preview" area of the site editor, where you can scroll and select any of the templates.

### Step-by-step reproduction instructions

1. Select a Full Site Editing compatible theme.
2. Open the Site Editor.
3. Click on "Templates" in the left sidebar.
4. Resize the window so that the template list extends beyond the viewable area.
5. Attempt to scroll.

Step 4 is not necessary if you already have a number of custom templates added—enough to push the list beyond the available display space.

### Screencast example on a site with multiple custom templates:

[Screencast example on a site with multiple custom templates](https://user-images.githubusercontent.com/10101587/219481299-071487bb-0f28-40df-afda-b5c67f3052ba.mp4)

<br >

### Screencast of the workaround—opening a template for editing, then returning using the "Browse all templates" option to view the list in another location.

[Screencast of the workaround—opening a template for editing, then returning using the "Browse all templates" option to view the list in another location.](https://user-images.githubusercontent.com/10101587/219481654-95c13aae-f87b-4ea4-beb5-bbbf9e6c1eec.mp4) 

### Environment info

- WordPress 6.1.1, Gutenberg 15.1.1, Twenty Twenty-Three
- Chrome 110
- Mac Desktop, MacOS Ventura

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Thanks for opening! I couldn't replicate this with 6.2 beta 2 but could replicate with 15.1.1 so it seems like something went wrong there. Here's a vid with 6.2 beta 2 for context:

https://user-images.githubusercontent.com/26996883/219520396-4a403ee1-87c7-45d5-ab5e-96a2d8516805.mov

I'm going to add this to the 6.2 board to be safe as a to do so this bug doesn't get accidentally backported.

**Comment by ndiego** [comment]
I can confirm that this issue is not present in Beta 2 and is also not present in Gutenberg trunk (at https://github.com/WordPress/gutenberg/commit/a770a6eaceacab0ae499950b4c539676662f4148). 

Let's leave this don't the board until Beta 3 is released, confirm the issue does not exist, and then close.

**Comment by ndiego** [comment]
Just tested in Beta 3, and the issue is resolved. 🎉
