### ISSUE TITLE
Outline headings don't work when we preview `tablet` or `mobile` in classic and hybrid themes

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#48189]
In a different PR that was trying to fix the `title` link in outline, @t-hamano [observed](https://github.com/WordPress/gutenberg/pull/48124#issuecomment-1433135594):

>I have found that in the non-iframe editor when I switch to preview, the anchor no longer works because the ID of the title changes. Can we give a fixed id to the post title? Or is there a way to keep the instanceID?

https://user-images.githubusercontent.com/54422211/219385546-85086095-d9a7-4730-a2e7-75edaf2b8297.mp4

----

This seems to be the case for every block in classic and hybrid themes as well, since when we iframed the previews. In these themes we don't iframe initially(desktop) but then iframe the previews resulting in different blockIds.

Related: https://github.com/WordPress/gutenberg/issues/47624

**Comment by ellatrix** [comment]
This has been fixed since we're using the iframe for the post editor too (same editor as previews)
