### ISSUE TITLE
Adding links in Text Columns doesn't work when hitting Return key

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4819]
## Issue Overview
When trying to add a link to the Text Columns block, if you simply type a URL and then hit the Return key, it doesn't work. It only works if you click the Apply icon.

![gutenberg-textcolumnslinksdontwork](https://user-images.githubusercontent.com/2078245/35711011-c6cf4a7e-080e-11e8-8c22-013ca59d5590.gif)

## Steps to Reproduce (for bugs)
1. Insert Text Columns block
2. Add text to column
3. Highlight some text and click the Link icon
4. Type a url and hit your Return/Enter key

## Expected Behavior
I should be able to simply hit Return/Enter after typing the URL

## Current Behavior
Hitting Return/Enter after typing the URL doesn't work and the link is never added

## Related Issues and/or PRs
#3709 - I've asked multiple times if you can please reopen this as it still breaks

_Firefox Quantum 58.0.1 (64-bit)
WordPress 4.9.2
Gutenberg 2.1.0_

**Comment by paulwilde** [comment]
I suspect this block type may get removed once nesting gets implemented.

**Comment by maddisondesigns** [comment]
I hope so because it's next to useless at the moment

**Comment by ajitbohra** [comment]
Works as expected on master / v3.2
