### ISSUE TITLE
Site Logo placeholder size is too large 

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#48217]
We should make the Site Logo placeholder smaller. The current 120px by 120px placeholder size is quite large and takes up quite a bit of space. 

I propose we reduce it to 80px x 80px. 

Here it is at full size: 

<img width="438" alt="CleanShot 2023-02-17 at 15 49 53" src="https://user-images.githubusercontent.com/1813435/219790656-2b5c5b57-20d7-41c3-b419-eccadd0010e3.png">

cc @WordPress/gutenberg-design

**Comment by richtabor** [comment]
Here's what the new header patterns look like (if I don't manually set a logo image width attribute): 

<img width="646" alt="CleanShot 2023-02-17 at 16 57 20" src="https://user-images.githubusercontent.com/1813435/219801573-dfc39152-037c-4831-88ee-27a43166f2c8.png">

I can set a manual value of 60px for each, but then its harder to enforce a standard across logo blocks in patterns — and (more importantly) applied images will max out at 60px width.

**Comment by jameskoster** [comment]
This is a funny one. It's not uncommon for logos to be more rectangular in aspect, especially if they include a logotype.

<img width="1374" alt="Screenshot 2023-02-24 at 13 05 58" src="https://user-images.githubusercontent.com/846565/221175101-057bece3-d9b5-4ebe-be32-c22e74ec3665.png">

Perhaps it's not possible, and I acknowledge we'd still need a default size, but I wonder if patterns might communicate their general intention more clearly if they were able to define a specific size for the placeholder? This could go for regular images too.

**Comment by richtabor** [comment]
> but I wonder if patterns might communicate their general intention more clearly if they were able to define a specific size for the placeholder? 

Yea I agree, similar to what we'd like to do for image placeholders as well.
