### ISSUE TITLE
Block: Post Template: Allow setting up custom gap

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#48224]
## What problem does this address?

It would be great if we could set up custom gap between Post Template items (entries, posts).

Currently it is hard coded in CSS to `1.25em` ([here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-template/style.scss#L17) and [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-template/style.scss#L27)) and there is no way to tweak this other than with custom CSS code.

## What is your proposed solution?

Maybe allow option to set up `spacing.blockGap` in editor?

**Comment by ghost** [comment]
This would have to be added to "supports" in block.json, currently spacing only has [margin and padding](https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/block.json) options.

I think the question here should be, would block gap be beneficial in multiple core blocks or is it an edge case? If it has use-cases in multiple core blocks then it would be an interesting idea to give this priority, otherwise other options might take precedence.

**Comment by webmandesign** [comment]
Thanks for the input.

I'm a theme author, so technically I'm OK if there was no option for user to set this. Less options, the better.

But as a theme author I find it unnecessarily difficult to change the spacing as of now. I am using this custom CSS currently:
```sass
:root {
	--wp--block--post-template--gap: 2em;
}

.wp-block-post-template.is-flex-container {
	gap: var(--wp--block--post-template--gap);

	@media (min-width: 600px) {
		@for $i from 2 through 6 {
			&.is-flex-container.columns-#{ $i } > li {
				width: calc( ( 100% / #{ $i } ) - var(--wp--block--post-template--gap) + ( var(--wp--block--post-template--gap) / #{ $i } ) );
			}
		}
	}
}
```

As you can see, I'm creating a new `--wp--block--post-template--gap` CSS variable for this, which makes the whole setup much easier for me. If similar approach would be implemented in Gutenberg/WordPress, I'd be happy :)

**Comment by webmandesign** [comment]
I can create a PR for this, but would like to know what is the best approach to naming similar block-specific CSS custom properties in Gutenberg/WordPress. Is there any guideline?

**Comment by andrewserong** [comment]
Thanks for opening up this issue, adding block spacing would be great! The Post Template block will need some more work to properly support block spacing, and there's an existing issue for tracking that work over in https://github.com/WordPress/gutenberg/issues/44557.

**Comment by richtabor** [comment]
@webmandesign are you cool if we close this as a duplicate to https://github.com/WordPress/gutenberg/issues/44899? Seems a good approach would be to refactor via https://github.com/WordPress/gutenberg/issues/44557 and opt the block to the proper dimensions support — rather than a CSS approach.

**Comment by webmandesign** [comment]
@richtabor Sure. Sorry for duplicate issue.
