### ISSUE TITLE
Building blocks with `wp-scripts` without externals

### ISSUE THREAD

**Issue by stephencottontail** [WordPress/gutenberg#48229]
### Description

I’m trying to create some custom blocks for a project that uses Gutenberg in a non-WP environment, so I need to build without externals (because the global `wp` variable won’t be available), but I wanted to test the blocks in WP itself first. I saw that `wp-scripts` includes a `—webpack-no-externals` option that I thought would be what I was looking for. When I build the block with that option, though, it doesn’t appear in the editor, but it does appear when I build without that option. It’s been a while since I worked with `webpack` beyond what `wp-scripts` does; am I missing something here? Alternatively, is there a better way to ultimately achieve what I’m trying to do?

### Step-by-step reproduction instructions

I made a small testing repo to show the issue: https://github.com/stephencottontail/externals-test

The repo includes a small WordPress plugin with a very basic Gutenberg block. There are two separate `npm` scripts setup that both output to the same location and use the same source file. If you run `npm run build`, then Gutenberg finds the block and makes it available in the editor, but if you run `npm run build-with-no-externals`, then it doesn’t appear in the editor.

### Environment info

- WP version 6.0 using whatever version of Gutenberg ships with 6.0
- All browsers show the problem

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kevin940726** [comment]
I don't think we currently support such an option, but you could still customize the webpack config if you want to.

> I’m trying to create some custom blocks for a project that uses Gutenberg in a non-WP environment, so I need to build without externals (because the global wp variable won’t be available), but I wanted to test the blocks in WP itself first.

I think that depends on how you want to consume the built files. If you already have a bundler for your non-WP project, then you can often just use the existing bundler to bundle your custom block and ignore `@wordpress/scripts`.

If somehow that's not possible, you can indeed try `--webpack-no-externals` with a [custom webpack config](https://github.com/WordPress/gutenberg/blob/trunk/packages/scripts/README.md#extending-the-webpack-config). For instance, create a `webpack.config.js` file in your project's root directory and paste the following:

```js
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

module.exports = {
  ...defaultConfig,
  externals: ({ request }, callback) => {
    if (request.startsWith('@wordpress/')) {
      callback(null, request, 'commonjs');
    } else {
      callback();
    }
  },
};
```

This will build your plugin but keep any `@wordpress/` dependency intact as a commonjs `require`. See the documentation of the [`externals`](https://webpack.js.org/configuration/externals/) config in webpack for more info.
