### ISSUE TITLE
Omit untitled page list items from the Page List Block

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#48226]
I've ran into this a few times, where a site's navigation looks offset/misaligned — but really its because untitled page list items have pushed the menu, as they still render in the Page List block. 

It's more of an edge case, but I do think these untitled pages should be omitted from the Page List block altogether. 

The current workaround (once you figure out that this is the case to alignment issues) is to navigate back to the All Pages view, then unpublish/delete/add titles to pages without titles. 

### Visual 

In this example below, the menu is intended to be centered below the Site Logo and Site Title blocks, but is pushed over due to two untitled Page List Items:
 
![CleanShot 2023-02-18 at 07 36 47](https://user-images.githubusercontent.com/1813435/219866187-94ff5040-a3b0-4a61-b27a-16684f03aaf8.png)

Thoughts @scruffian?

**Comment by scruffian** [comment]
I think it would be better to show (no title), as we do in other places.

**Comment by richtabor** [comment]
Would "Page List Item" also say (No Title) in the List view?

**Comment by scruffian** [comment]
Yeah probably

**Comment by richtabor** [comment]
That's fine, though I still wouldn't expect one would want (No Title) in their site navigation.

**Comment by scruffian** [comment]
but at least you can then remove it!

**Comment by MaggieCabrera** [comment]
Would it make sense to show (no title) in the editor maybe with a slight opacity and then not show it on the frontend?

**Comment by draganescu** [comment]
I agree with the folks above about adding a placeholder title rather than hiding.

**Comment by scruffian** [comment]
>  then not show it on the frontend?

I agree with this.

**Comment by scruffian** [comment]
I added a commit so that we output `(no title)` in the list view but nothing in the canvas. What do y'all think?
