### ISSUE TITLE
FSE: List View open add a new Nav link or a Social Links block link. Popup modal partly outside the right edge

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#48234]
### Description

Using the Site Editor.
Open List View. Then explore various blocks such as Nav block. Add a new link. Notice the modal is partly outside the right edge of the browser.
Then add a new link in the Social Links block. Again notice the modal is even further outside the right edge of the browser.

### Step-by-step reproduction instructions

1. Go to the Site Editor.
2. Open List View.
3. In the Nav block add a new link. Notice location of popup link modal.
4. Add a Social Links block and add a service.
5. Notice the location of the modal popup.

### Screenshots, screen recording, code snippet

Here is a reply:
https://app.replay.io/recording/page-template-editor-bluewinddesign-wordpress--1c3580d8-3826-4de8-ad21-5bf233de809d

### Environment info

WordPress 6.2 beta 2
WordPress Beta Tester plugin
Twenty Twenty Three

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Might be related to #48140.

**Comment by paaljoachim** [comment]
Yes that seems very related!
[Incorrect popover placement [6.2]](https://github.com/WordPress/gutenberg/issues/48140)

I will close my duplicate issue and comment there instead.
