### ISSUE TITLE
Bring back the "Open in a new tab" option

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#4824]
Since 2.0 the option "Open in new tab" has gone. 

It seems than it was convenient because there was some accessibility issues in the previous version. 

So it's an useful option and I think people will need it. 

( by the way, it will need some attributes like `rel="external noopener noreferrer`)

**Comment by youknowriad** [comment]
I'm closing as similar issues have been closed see #4798 and discussion is happening in #4583 and its attached issue.
