### ISSUE TITLE
Square brackets mistaken for shortcode upon insertion

### ISSUE THREAD

**Issue by ms-studio** [WordPress/gutenberg#4825]
When attempting copy-paste of text into a Gutenberg paragraph block, I notice that any text contained in square brackets is converted into a shortcode block.

## Example

I copy-pasted the first paragraph of the article on Franz Kafka on Wikipedia:

> Franz Kafka[a] (3 July 1883 – 3 June 1924) was a German-speaking Bohemian Jewish novelist and short story writer, widely regarded as one of the major figures of 20th-century literature. His work, which fuses elements of realism and the fantastic,[3] typically features isolated protagonists faced by bizarre or surrealistic predicaments and incomprehensible social-bureaucratic powers, and has been interpreted as exploring themes of alienation, existential anxiety, guilt, and absurdity.[4] His best known works include "Die Verwandlung" ("The Metamorphosis"), Der Process (The Trial), and Das Schloss (The Castle). The term Kafkaesque has entered the English language to describe situations like those in his writing.

## Expected Behavior
I would expect this entire text to be inserted as a paragraph.

## Current Behavior
The text string [a] is converted into a shortcode field. The result looks like this:

<img width="664" alt="kafka-shortcode" src="https://user-images.githubusercontent.com/241637/35724536-5a5d3d0c-07fe-11e8-8433-a7281a4cf2ad.png">

## Possible Solution
Check if the shortcode actually exists before converting. I notice that the numbers between square brackets are not turned into shortcodes, so there is some conditional testing in place already.

**Comment by wsydney76** [comment]
> Check if the shortcode actually exists before converting

May be not enough, as some shortcodes are "inline" by nature, eg. footnotes (Easy Footnotes plugin)

![image](https://user-images.githubusercontent.com/25308802/35850823-5ee1a6b2-0b26-11e8-919e-ecfae3cdb4d0.png)

in Open Office Writer will become 

![image](https://user-images.githubusercontent.com/25308802/35850864-81f50252-0b26-11e8-8015-88ffde2f823a.png)

### Possible Solution

Do not convert shotcodes to block if they are not on surrounded by line breaks.

**Comment by mtias** [comment]
This works as expected now.
