### ISSUE TITLE
Navigation block: Redundant search icons on mobile browser views only

### ISSUE THREAD

**Issue by jeffgolenski** [WordPress/gutenberg#48259]
### Description

On the live view of the website on a large screen, the search component displays correctly with placeholder text and a search icon as the button. On a mobile phone (in browser), the placeholder text is automatically replaced with with another search icon. So now there are 2 search icons displaying - both facing different directions.

What I expected: The mobile view to display as it does on a large screen. See attached screenshots

### Step-by-step reproduction instructions

Inside of a head template part, add a navigation block with a search component within it. Select the "use button with icon" sub setting for the search component.

cc @jasmussen - please give me some feedback on my report structure! 

### Screenshots, screen recording, code snippet

Settings:
<img width="788" alt="Screen Shot 2023-02-20 at 5 15 22 PM" src="https://user-images.githubusercontent.com/214813/220158651-28d38f3a-2560-4012-b9da-2e64eefea5a5.png">

Large screen view (proper):
<img width="1680" alt="Screen Shot 2023-02-20 at 5 26 59 PM" src="https://user-images.githubusercontent.com/214813/220158851-5e1ffdc0-40f7-4f2c-b550-faf50b8ade3f.png">

Mobile view (not expected):
![IMG_6315](https://user-images.githubusercontent.com/214813/220158991-f10efb4d-5fd9-473f-8c9c-25adffc5a5e8.png)

### Environment info

Google Chrome (mobile): V 110.0.5481.83
Tested on WordPress.com

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes, No

**Comment by carolinan** [comment]
I do not see the same behavior on my self hosted site on my Huawei p20,  Chrome (mobile)  110.0.5481.65 or Firefox mobile 110.0.1, Edge mobile 110.0.1587.41

**Comment by ndiego** [comment]
I was able to replicate on iOS Safari on my personal site. However, other testers during the Editor Bug Scrub were not. 
![IMG_42E204E093D1-1](https://user-images.githubusercontent.com/4832319/220369409-a3581827-519a-41cd-b42e-691a4569bfa7.jpeg)

**Comment by jasmussen** [comment]
Good issue, thanks for the report, this is useful. It seems like this might be mobile safari specfic, does that sound right? I.e. that this icon is added by the browser, perhaps because it's an HTML 5 "type=search" field? I don't have immediate access to an iphone to test on, but it might be good to test such a search field with and without _`-webkit-appearance: none;`, see if that makes a difference.

**Comment by jeffgolenski** [comment]
@jasmussen Sorry for the delay on this. 

> It seems like this might be mobile safari specfic, does that sound right?

I'm experiencing this in mobile chrome, firefox, and safari. Seems to be everywhere.

**Comment by jasmussen** [comment]
I think I have a fix in #49710.
