### ISSUE TITLE
Global Styles: Border customisation is not applied correctly

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#48253]
### Description

With #47630, the border customisation for the Avatar block is applied correctly at the block level. However, the block will not be styled correctly if it's styled in Global Styles.

![Screenshot 2023-02-20 at 15 29 13](https://user-images.githubusercontent.com/908665/220134725-dfb9fa71-06d5-4ba5-9cb7-b8188a3ec667.jpg)

### Step-by-step reproduction instructions

1. Add an avatar block,
2. Go to Styles tab and Blocks > Avatar > Border
3. Try adding a border and specify the border-radius.

### Environment info

- WP 6.1.1
- Gutenberg Trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by beafialho** [comment]
+1 This doesn't work as expected.

<img width="223" alt="Captura de ecrã 2023-03-23, às 09 46 10" src="https://user-images.githubusercontent.com/65220155/227165089-f9fb7d11-3702-4db1-9eeb-67ddade4038b.png">

**Comment by jffng** [comment]
The exact same is true of styling the search block border via global styles — works correctly at the block level but not global styles:

Block | Global Styles
--- | ---
<img width="685" alt="Screenshot 2023-03-28 at 12 33 21 PM" src="https://user-images.githubusercontent.com/5375500/228307964-d7540d78-e6a8-43fa-98df-ff19bd02bca6.png"> | <img width="680" alt="Screenshot 2023-03-28 at 12 29 19 PM" src="https://user-images.githubusercontent.com/5375500/228307619-ec6f838a-20e7-45f9-a9d8-7973cfb6801a.png">

**Comment by james-s-k** [comment]
Border and border radius for the Avatar Block do not work for me. Works on the back-end but the styles do not get carried across to the markup on the front-end.
