### ISSUE TITLE
Error with wp-env start : Error: No plugins activated

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#48285]
### Description

I am trying to set up a dev environment to test a plugin using wp-env but don't seem to be able to.
You can find the plugin here : https://github.com/InfiniteLearner/collapsible-nested-list

### Step-by-step reproduction instructions

Download the github project : 
```git clone https://github.com/InfiniteLearner/collapsible-nested-list.git```

Navigate to the folder :
```cd collapsible-nested-list```

Set up wp-env:
``` npm -g i @wordpress/env```

Start it:
```wp-env start```

### Screenshots, screen recording, code snippet

Result:
× Error while running docker-compose command.
Success: WordPress installed successfully.
Success: Updated the constant 'WP_DEBUG' in the 'wp-config.php' file with the raw value 'false'.
Success: Added the constant 'SCRIPT_DEBUG' to the 'wp-config.php' file with the raw value 'false'.
Success: Added the constant 'WP_ENVIRONMENT_TYPE' to the 'wp-config.php' file with the value 'local'.
Success: Added the constant 'WP_PHP_BINARY' to the 'wp-config.php' file with the value 'php'.
Success: Added the constant 'WP_TESTS_EMAIL' to the 'wp-config.php' file with the value 'admin@example.org'.
Success: Added the constant 'WP_TESTS_TITLE' to the 'wp-config.php' file with the value 'Test Blog'.
Success: Added the constant 'WP_TESTS_DOMAIN' to the 'wp-config.php' file with the value 'localhost'.
Success: Added the constant 'WP_SITEURL' to the 'wp-config.php' file with the value 'http://localhost:8889/'.
Success: Added the constant 'WP_HOME' to the 'wp-config.php' file with the value 'http://localhost:8889/'.
Container 1f7d0ffcc354300d905bfdc29a45f95b-tests-mysql-1  Running
Container 1f7d0ffcc354300d905bfdc29a45f95b-tests-wordpress-1  Running
Warning: The 'collapsible-nested-list' plugin could not be found.
Error: No plugins activated.

### Environment info

I am using Windows 11, version 22H2.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Hey there @InfiniteLearner – thanks for the report. I'm just not not quite sure how this is related to Gutenberg/block editor/Site Editing, would you mind clarifying? Thanks!

I'm thinking this might be an issue for Core Trac instead: https://core.trac.wordpress.org/

**Comment by ghost** [comment]
Hi,

I though that wp-env was developed by the gutenberg team my bad.
I will report it to core trac then.

Thank you
