### ISSUE TITLE
Navigation block: custom widget not imported

### ISSUE THREAD

**Issue by helloarpitgshah** [WordPress/gutenberg#48287]
### Description

As per the step described into this thread - https://github.com/WordPress/gutenberg/issues/48045

I have followed the same but added menu and footer widgets both. Now the menu is imported but not the footer widgets.

see the screenshot below,

![footer-widgets](https://user-images.githubusercontent.com/17160108/220380875-92fb6579-cbe5-485a-8990-dacc81a49a82.png)

### Step-by-step reproduction instructions

Steps Describe here - https://github.com/WordPress/gutenberg/issues/48045

### Screenshots, screen recording, code snippet

![footer-widgets](https://user-images.githubusercontent.com/17160108/220380990-8cb84bba-0469-4e10-8772-d64e4dc291a9.png)

### Environment info

WordPress - 6.1.1
Gutenberg - 15.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Thanks for testing! I think you are referring to this: https://github.com/WordPress/gutenberg/issues/47285 Is that correct? If so, let's close this out as a duplicate.

**Comment by helloarpitgshah** [comment]
Hey @annezazu 

This is the issue after switching the default themes from one to another.

1 - Open this link once to create a test site: https://app.instawp.io/launch?t=fse-call-for-testing-20

2 - Explore your site and feel free to add in more personalized items, under Widgets under Appearance > Widgets.

3 - When you’re ready, head to Appearance > Themes and select “Activate” next to the Twenty Twenty-Three theme.

4 - Head to Appearance > Editor (beta) to be brought into the browse mode experiment in the Site Editor.

5 - Click through the different templates and template parts to view the various parts of your site. Eventually, select your Home template and choose “Edit”. Notice that your previously created menu was automatically imported.

I have tested as follow above steps.

**Comment by annezazu** [comment]
Hi there! I'm still not following. Is it that your custom _menu_ isn't imported? When you say widget, what are you expecting? It sounds like you might be running into this issue if it's related to your menu: https://github.com/WordPress/gutenberg/issues/48045 If so can you comment there with more information to replicate? I have been unable to do so!

**Comment by helloarpitgshah** [comment]
@annezazu  - All are good here

**Comment by annezazu** [comment]
Okay! I'm going to close this out in that case. Thanks for following up.
