### ISSUE TITLE
Alternate color schemes shouldn't be used on trunk

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#4828]
On the WordPress trunk version, the alternate color schemes are disabled.

However, they're not completely disabled on Gutenberg.

To reproduce, on a VVV instal:
- cd to the trunk version and run `grunt build`
- go to the "build" version, likely `http://build.wordpress-develop.test/wp-admin`
- in your user profile page, change color scheme to "Midnight"
- go to the trunk version, likely `http://src.wordpress-develop.test/wp-admin`
- as you can see, the color scheme is the default one across all the admin, and under your profile the color scheme section doesn't appear
- however, Gutenberg displays some of the colors from the "Midnight" scheme:

<img width="1133" alt="screen shot 2018-02-02 at 11 09 44" src="https://user-images.githubusercontent.com/1682452/35728203-16bf0aaa-080b-11e8-8119-c9730e43e1ec.png">

Worth noting the Publish button is blue. On teh build version instead, it's correctly red:

<img width="382" alt="screen shot 2018-02-02 at 11 22 04" src="https://user-images.githubusercontent.com/1682452/35728377-ad51dc68-080b-11e8-98d1-2a53bbf695b4.png">

I guess Gutenberg should be consistent with what WordPress does and never display custom colors on trunk.

**Comment by youknowriad** [comment]
Can I ask why these themes are disabled on "trunk"?

**Comment by afercia** [comment]
I guess because the related stylesheet are generated only during the build process, so they don't work on trunk.

**Comment by youknowriad** [comment]
@afercia Since the build process is being made mandatory by the changes proposed by @omarreiss I guess trunk will have the style as well?

**Comment by omarreiss** [comment]
I think it is likely they will.

**Comment by youknowriad** [comment]
I'm closing this issue right now as it seems related to build tools. And build tools are mandatory with Gutenberg anyway, so once Gutenberg hits Core, Core will have these styles no matter where you run it.

**Comment by afercia** [comment]
No objections from me. However, I guess a Trac ticket should be created as, if I remember correctly, there's some specific code in trunk that prevents the color schemes options to appear under `/wp-admin/profile.php` so that part should be changed. I guess it should also be discussed with the core team and the project leads 🙂 
I'd recommend to coordinate with the Gutenberg team leads and create the Trac ticket as it appears to be a necessary step for integration in core.

**Comment by ntwb** [comment]
The ticket introducing a "build step" is https://core.trac.wordpress.org/ticket/43055

That ticket is primarily focused on JavaScript, so we'll need another ticket for this and possibly some other CSS/SCSS tweaks.

@afercia The code preventing the color schemes loading from `/src` was added in r26137:
• https://core.trac.wordpress.org/browser/trunk/src/wp-includes/general-template.php?annotate=blame&rev=26137#L2118
