### ISSUE TITLE
Site Editor: consider adding a message in the editor canvas when no template is selected

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#48292]
### Description

Currently (WP 6.2 Beta 3), when we open the Site Editor (tested with TT2 activated and no plugin), we have a blank canvas a we need to select something to edit. I'm not sure about the experience, it looks like something is broken (plus, we have a "loading" icon).

Currently:
![4707caf94bc2d2b6772e6421496799bf](https://user-images.githubusercontent.com/1590998/220419886-880c37b1-8268-48a4-b39b-85b7b878823a.gif)

Maybe we could add a message?
<img width="1401" alt="Capture d’écran 2023-02-21 à 18 29 04" src="https://user-images.githubusercontent.com/1590998/220419935-30a2bb84-357d-4869-9a89-a171f8633bb8.png">

### Step-by-step reproduction instructions

1. Activate TT2
2. Go to Site Editor
3. Blank canvas on the right

### Environment info

- WP 6.2 beta 3 (or 2)
- no plugin (even Gutenberg)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
While I can't replicate this with 6.2 beta 3, I believe @ellatrix ran into this in an early part of the release cycle. In my opinion, this is a bug and we should automatically select a template to load rather than requiring the user to do so. cc @youknowriad as a heads up.

**Comment by youknowriad** [comment]
In theory, this shouldn't happen, when you're not in a specific template, the "front-page" is supposed to be loaded. There might be an edge case depending on the site config that we missed. I'll debug more later.

**Comment by audrasjb** [comment]
Adding more info about the context of the issue:
- I noticed it during the WordPress 6.2 beta 3 release party
- No plugin installed, and Gutenberg is not installed
- I'm working locally on MAMP (PHP 7.4), with a fresh install
- It also occurred after updating from 6.1.1 to 6.2 beta 3
- I replicate the issue using WP 6.2 beta 2
- No error in the console

The spinner keeps turning, and nothing never loads on the page on my side.

**Comment by ndiego** [comment]
My testing results: 

- I cannot replicate locally with any block theme. I have tested Beta 3 with and without Gutenberg. I am using Local (PHP 7.4.1 & 8.0.0)
- I can replicate on my personal live site, but only when using Beta 3 **and** Gutenberg. If I deactivate Gutenberg, the issue goes away.
- When the Editor fails to load, I do get error messages, but they occasionally change with each refresh. Below is an example. 

![image](https://user-images.githubusercontent.com/4832319/220435596-424e4b63-97bc-46d0-a6e4-be911a2e7c32.png)

**Comment by Mamaduka** [comment]
@youknowriad is correct. We're sending "homepage" template data from the server to set up the correct template on initial loads.

I've got a feeling failing perf tests problem caught this flakiness behavior, but we thought it was only CI related - #48240.

Edit: I see that we no longer use server-side redirection - https://github.com/WordPress/wordpress-develop/commit/81feb44d53d977796f5bdfd64f5fab1a0c2b451f.

**Comment by youknowriad** [comment]
@Mamaduka the perf issues were something else (basically we had wrong code being tested for 3 months but now it's fixed)

Still unable to reproduce this. Any network response error or anything would be helpful :)

**Comment by annezazu** [comment]
If anyone who can replicate this would like to use replay.io, which records the full browser session, let me know and I'll give access to use. We can then have devs dig in to debug.

**Comment by ellatrix** [comment]
I'm still seeing this issue all the time. No network errors or anything else logged in the console.

![site-editor-loading](https://user-images.githubusercontent.com/4710635/220874699-187791d4-8c4f-47b3-82e1-07cfcd119143.gif)

**Comment by ellatrix** [comment]
For the record, we tracked this down. It's only an issue for sites installed in a subfolder.

**Comment by aurooba** [comment]
@ellatrix pretty sure #48391 is related to this. Going to quote it below for easier access, and in this particular case, we'd want the Site Editor to go straight to the `Template Parts` page. And my console and network tab are also clear, no errors.

> ### Description
> I've got a hybrid (non-block) theme that has Template Parts enabled. When you go to Appearance > Template Parts, you get a loading screen or an error, instead of the expected Template Parts screen.
> 
> ### Step-by-step reproduction instructions
> 1. on `6.2-beta3-55418` version of WordPress
> 2. Install a regular theme that has Template Parts support enabled and at least 1 Template Part
> 3. Go to Appearance > Template Parts
> 4. See the loading screen
> 5. Refresh the page, get the error: `The theme you are currently using is not compatible with the Site Editor.`
> 
> ### Screenshots, screen recording, code snippet
> <img alt="Site Editor with the sidebar but a loading screen instead of the expected Template Parts screen" width="2000" src="https://user-images.githubusercontent.com/6925260/221055811-f640068f-303e-417a-9492-154e3a0a83b8.png">
> 
> If you refresh the page, you get the following error: `The theme you are currently using is not compatible with the Site Editor.`
> 
> ### Environment info
> WordPress: `6.2-beta3-55418` version of WordPress Gutenberg: Tested with Gutenberg and _without_ Gutenberg Browser: Google Chrome

**Comment by drussell17** [comment]
I reported this same problem in 57805

Clicking on Edit Site yields the url below which generates no response

http://localhost/wordpress-svn/src/wp-admin/site-editor.php?canvas=view&path=%2F  

The url from the the same action on a bare install of 6.1.1 yields the following:

http://localhost/wordpress/wp-admin/site-editor.php?postType=wp_template&postId=smartcube%2F%2Fhome

which works.  I did change the theme on the 6.1.1 instance as noted.

My installs are in subdirectories as noted in the urls

**Comment by drussell17** [comment]
For me, this is now fixed with revision 55442.  URL passed is unchanged but site editor "finds" the home template and loads it.

**Comment by aurooba** [comment]
Confirming that my issue is also fixed! :) Clicking on Appearance > Template Parts takes you to the Template Parts page. 🎉 Thank you!
