### ISSUE TITLE
Blocks settings unavailable within the Unsupported Block Editor

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#48298]
## Description

When editing a block with the mobile app's Unsupported Block Editor (UBE), the "Show more settings" option is not available. 

The source of this issue is likely similar to https://github.com/WordPress/gutenberg/issues/33592 and related to the inherent brittleness of the foundational implementation referenced in https://github.com/WordPress/gutenberg/issues/21874. There may have been a change the web editor's DOM hierarchy/class names or a browser-specific issue introduced. 

## Step-by-step reproduction instructions

1. Create a post in the web editor and add a block that is not supported by the mobile app, e.g. Archives. 
2. Open the same post with the mobile app. 
3. Select the block.
4. Tap the <kbd>?</kbd> button. 
5. Tap "Edit using web editor." 
6. Tap the three-dot menu in the block toolbar. 

## Expected behaviour

The "Show more settings" option is available. 

## Actual behaviour

The "Copy block" option is available. 

## Screenshots or screen recording (optional)

<details><summary>Screenshot</summary>

![ube-block-settings-missing](https://user-images.githubusercontent.com/438664/220490756-4d375441-1080-4efd-9f4c-09b41700cbda.jpeg)

</details>

## WordPress information
- WordPress version:  6.1
- Gutenberg version:  15.1.1
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes

## Device information
- Device:  iPhone SE
- Operating system:  iOS 16.3
- WordPress app version:  21.8.0.0

**Comment by geriux** [comment]
This is a tricky one because it looks like the "Show more options" that was supposed to show as the first item after tapping the three-dots button is no longer there:

<kbd><img width="298" alt="Screenshot 2023-02-22 at 12 52 29" src="https://user-images.githubusercontent.com/4885740/220613101-af6c9d66-2f55-4940-a1f0-97cfcb976e50.png"></kbd>

The option to open the block options is now in the header navigation which we don't display within the UBE:

<kbd><img width="298" alt="Screenshot 2023-02-22 at 12 51 03" src="https://user-images.githubusercontent.com/4885740/220613269-915e2624-9172-4321-8bbe-0e3c54b27caa.png"></kbd>

Tapping that button opens a sidebar:

<kbd><img width="298" alt="Screenshot 2023-02-22 at 12 51 18" src="https://user-images.githubusercontent.com/4885740/220613526-dae7483b-aa39-4cbd-8777-d5dc8378bb8b.png"></kbd>

I'm now sure how to workaround that 🤔

**Comment by dcalhoun** [comment]
> I'm now sure how to workaround that 🤔

My initial reaction without looking at the code is that we would need to use JavaScript to manually construct and inject a "Show more settings" button where we need it inside of [`packages/react-native-bridge/common/gutenberg-web-single-block/editor-behavior-overrides.js`](https://github.com/WordPress/gutenberg/blob/2fbe9a0a823aff8e1c39c76651f73ec3dd20a658/packages/react-native-bridge/common/gutenberg-web-single-block/editor-behavior-overrides.js) — a file we solely control. That feels very bad and brittle, but one might argue it is less brittle than previous approach of relying upon the existence of the button being there — which this very issue demonstrates the risk of that approach.

**Comment by dcalhoun** [comment]
From my research, it appears the "Show more settings" button was removed in #46709.

**Comment by dcalhoun** [comment]
> The option to open the block options is now in the header navigation which we don't display within the UBE:

I am wondering if merely displaying the edit post header is the simplest and most stable approach to resolving this. I.e. remove the following lines that currently hide the edit post header. 

https://github.com/WordPress/gutenberg/blob/2f294e19f51b3c6087497ef4b798e4f00b03dd02/packages/react-native-bridge/common/gutenberg-web-single-block/editor-style-overrides.css#L20-L45

Yes, it occupies more vertical space — possibly an annoying amount of space on small displays — but it would further align the UBE with the default web editor and likely make the UBE less brittle. We would likely need to hide individual menu items, e.g. navigating away from the post editor.

**Comment by geriux** [comment]
>I am wondering if merely displaying the edit post header is the simplest and most stable approach to resolving this. I.e. remove the following lines that currently hide the edit post header.

I think we should explore that and like you said just hide the options we don't need there, it is true about the vertical space but nowadays mobile phones are quite big so it might not be an issue, especially if you're just editing one block.

**Comment by dcalhoun** [comment]
I explored the idea of displaying the Edit Post Header. Unfortunately, it does expose the ability to perform actions outside of the scope of modifying a single block and potential confusion for users. 

Specifically, it is very easy to access Post Settings in the sidebar, rather than just Block Settings. When a block is not selected, tapping the Sidebar toggle button opens the Post Settings, which is confusing and undesired for the scope of the UBE. 

I am now exploring displaying the Sidebar toggle button only when a block is selected to avoid this. 

| Visible Edit Post Header | Post Settings | Block Settings |
| - | - | - |
| ![edit post header visible](https://user-images.githubusercontent.com/438664/221195178-1bec3015-082c-4b27-864a-cfd1baf2efed.png) | ![sidebar block settings](https://user-images.githubusercontent.com/438664/221194182-8bdf0607-7dd2-4bd5-bde3-d80a3d6c6a97.png) | ![sidebar post settings](https://user-images.githubusercontent.com/438664/221194179-45dc9748-7a77-46de-b9df-919897cc3779.png) |

**Comment by geriux** [comment]
> I am now exploring displaying the Sidebar toggle button only when a block is selected to avoid this.

That looks like the best approach 👍
