### ISSUE TITLE
Remove beta label from Gutenberg release

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#48297]
While the [beta label has been removed via trac for WordPress 6.2](https://github.com/WordPress/gutenberg/issues/39293), it remains in the Gutenberg plugin (testing with GB 15.1.1 & GB 15.2 RC1). From what I can see, I _think_ it's as easy as editing this line: https://github.com/WordPress/gutenberg/blob/2421c97fc73a99de2bd8693db63b1c05e293df68/packages/edit-site/src/components/editor/index.js#L167 If that's correct, I can quickly open a PR. Otherwise, can someone please take care of this? 😄

**Comment by t-hamano** [comment]
I think the beta label has been removed in the latest Gutenberg trunk. Please see [this comment](https://github.com/WordPress/gutenberg/pull/47855#discussion_r1104282300) for more information.

**Comment by ocean90** [comment]
Correct, it was removed in #48053.

**Comment by annezazu** [comment]
Thanks for connecting the dots! Couldn't seem to find it when I dug through PRs.

**Comment by bgardner** [comment]
@annezazu @ocean90 Unless I'm missing something it appears to me that in Gutenberg 15.2, the label is still present:

https://user-images.githubusercontent.com/486261/220751031-e12aa799-e816-435c-99d4-53111f8464b3.mov

**Comment by annezazu** [comment]
Re-opening :) I can replicate.

**Comment by t-hamano** [comment]
@bgardner

What version of WordPress are you using? WordPress 6.2 Beta3 does not appear to show the beta label, regardless of the status of the Gutenberg plugin

**Comment by annezazu** [comment]
That's likely due to this trac ticket: https://core.trac.wordpress.org/ticket/57654#ticket However, it seems we should have consistency here for those using the Gutenberg plugin.

**Comment by bgardner** [comment]
@annezazu is correct. My video was pointing out the presence of the Beta label with Gutenberg active, which is what I believe the original issue was created to address. I can confirm that WP 6.2 Beta 3 (sans Gutenberg) does not have the label present.

**Comment by ocean90** [comment]
Re-closing as fixed per https://github.com/WordPress/gutenberg/issues/48297#issuecomment-1440277880.
