### ISSUE TITLE
The preview in Styles section, if we switch from Outline to Default does not work properly.

### ISSUE THREAD

**Issue by Anjali29dots** [WordPress/gutenberg#48309]
### Description

The preview which appears when we hover upon the Default and Outline tab appears and goes automatically.

### Step-by-step reproduction instructions

Go to add Button block.
Go to settings and select Style tab.
Go to select Outline option.
Go to hover upon Default tab.
The preview will appear and will disappear.

### Screenshots, screen recording, code snippet

Video: https://share.cleanshot.com/YgKQ1ccbh3kdWTpvhYNT

### Environment info

- WP version: 6.2 beta
- Theme: Twenty Twenty Two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ghost** [comment]
@Anjali29dots This is working fine on my end, using both TT2 and TT3 themes in 6.2 beta. With and without Gutenberg plugin activated. Do you have any other plugins activated?

**Comment by ghost** [comment]
@Anjali29dots I see you also have a LOT of Chrome Extensions, can you test this with them turned off? Or in a different browser? You can also check your console log, to see if any of the extensions give you errors.

**Comment by Anjali29dots** [comment]
@tomdevisser Thanks for it. I tested it with extensions turned off and it works fine for me.
