### ISSUE TITLE
core/html block rendering as html inside reusable block

### ISSUE THREAD

**Issue by kmrmohit** [WordPress/gutenberg#48338]
### Description

core/html block doesn't render as preview when used inside reusable blocks. The expected behavior is that the core/html content renders as preview (which used to happen in version 5.5.1).

### Step-by-step reproduction instructions

1. Create a core/html block and add html to it.
2. Set the core/html state to preview (not required imo but just to be sure)
3. Convert the core/html block to a reusable block

### Screenshots, screen recording, code snippet
<img width="1161" alt="Screenshot 2023-02-23 at 10 30 33 AM" src="https://user-images.githubusercontent.com/39377854/220824763-75a8ef3e-92e0-4e83-bcee-c9f7553f12b7.png">

Recording link: https://drive.google.com/file/d/1JiZxYg84cPCSLkev37Hl12UZn8aEPoZL/view?usp=sharing

### Environment info
- Wordpress 6.1.1, theme twentytwentythree, with and without plugin
- Chrome 109.0.5414.119
- macos monterey

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I think we can adopt the same solution as for #47819. 

@ndiego, should we close this as a duplicate?

**Comment by ndiego** [comment]
@Mamaduka yeah, if the solution that is implemented for https://github.com/WordPress/gutenberg/issues/47819 will also resolve this issue, I think we can close this out. While https://github.com/WordPress/gutenberg/issues/47819 does not sound like the same bug, it is from a technical perspective.
