### ISSUE TITLE
Anchor option for links and pagination in the Query Loop Block

### ISSUE THREAD

**Issue by AdamWarnock-UA** [WordPress/gutenberg#48330]
## What problem does this address?
This problem is essential the same for both links and pagination. Currently, there is not a way to append anchors to link URLs during initial creation nor to pagination links in the Query Loop Block, at all. In the case of links, it creates a user experience issue in that you have to create the link, then edit it to add the anchor. So if I have a page, mysite.com/news, and there's an anchor, my-anchor, on the page I want to link to, I have to first link to the page then edit the link to add the \#my-anchor part to the URL. This can be error prone and effectively doubles the amount of clicks to add an anchor to the link.

For the pagination on the Query Loop Block, the issue is more of a usability issue for site visitors. When you have a Query Loop Block on the page and it has pagination, clicking on the pagination reloads the page and puts the visitor back at the top of the page. This creates friction in the user experience if the block is not above the fold. The visitor has to either look for the block if it's not at the top of the page or scroll to find it if it's below the fold on the page.

## What is your proposed solution?
In both cases the solution is simple, add an option to append an anchor to the URL.

For links in content, this could be as simple as displaying available anchors on a page under the URL for internal pages. Another option is to have an anchor field that loads in available anchors after selecting an internal page to chose from or allows the user to type in the anchor to be appended.

For Query Loop Blocks, I'd argue that by default we want the page to scroll to the block when using the built in pagination. So, for the block as a whole, I'd add an anchor field and automatically populate it based on post type and filters with an index appended to prevent issues from having multiple anchor IDs with the same value. For example, in the case of a Query Loop Block that displays Posts that are in the Cats category and tagged with  long haired, it would automatically add the anchor ID of qlb-title-cats-long-haired-0 to the anchor field. This anchor id would be appended to the pagination links in the Query Loop Block by default.

I'd also argue that, ideally, the Query Loop Block would allow the user to set a custom anchor id for both the block and the anchor that is appended to the pagination URLs. This would allow the user to set the anchor to be a heading for the section the block is in.

**Comment by ghost** [comment]
I like the idea to add this to the Query Block, but I don't know if we should do it by default. Having backwards compatibility in mind, probably lots of devs already solved this by adding a custom solution which might break. It should probably be an opt-in setting like "Scroll to block on pagination" in the block's settings.

I see what you mean with links. I do like the "click on a link, add it and close the popup automatically" UX, although I sometimes forget to click the "Open in new tab" so I already have to open it again a lot of times. I don't think moving the "Open in new tab" should be moved to the top either, but it's something that comes to mind. With that in mind, we might be able to add the anchor field to the top of the popup so we can keep the "close on click" functionality.

<img width="388" alt="Screenshot 2023-02-23 at 3 17 28 PM" src="https://user-images.githubusercontent.com/118618474/220933165-f2d88a6b-bee1-4cd1-a4f4-0dc86a5025a9.png">

Another option is requiring users to click the "Apply" button at the bottom of the popup at all times, forcing one extra click when someone is done selecting a link, enabling the "Open in new tab" if they want to, and optionally adding an anchor.

**Comment by AdamWarnock-UA** [comment]
Point taken about backwards compatibility. I was thinking more along the lines of what would make sense. Having an opt-in would be great, and I don't think it'd be too much of an issue even if you were setting up a lot of these.

With regards to adding anchors to text link, I think that what you talked about would be great. Maybe we have a toggle for scrolling to anchor? Enabling it would produce a list of anchors for pages on the same WordPress install. If it's an external link we could just have a text field that the user types in the anchor, but that might be confusing. How hard would it be to have WordPress scrap the page being linked to and extracting the anchors?

**Comment by ghost** [comment]
Interesting idea adding links to the page list, but I think the implementation of that is pretty complex. Just thinking out loud here - I think in order to show them as "Page links" in the navigation block you'd have to create a post type "Anchor links" or something similar and create a post of that type every time someone enters an anchor. Then there has to be a system that deletes those posts once you remove the anchor. This might also have implications for queries done in multiple places, etc. But in all honesty, I'm not the qualified person to recommend anything in this, lacking a lot of knowledge needed for such decisions. Let's wait until a more experienced contributor chimes in.

**Comment by AdamWarnock-UA** [comment]
I think I may have muddied the waters here by tying these two things together. Both are related to anchors in links, which is why I lumped them together, but I may have been too clever for my own good.

There are two different issues here.

1. **Pagination** Links on the Query Loop Block don't have an option to add an anchor to allow scrolling to the block while navigating the block content. This should be fairly simple, adding an option to append an anchor to the pagination links, perhaps a toggle and a field for custom anchors.
2. Regular links don't have a way to add anchors to the URL without editing the link without creating the link first. This is the one that I was suggesting having WordPress create options based on the anchors available on the page.

Maybe this should be split into two different issues?

**Comment by ghost** [comment]
I think that would be smart @AdamWarnock-UA. The first one needs some good consideration on backw. compat., and it might even be interesting to look at a more general way of implementing anchors. If we're gonna implement it on a wider scale, it wouldn't be smart to jump the gun and build a block specific one for the Query Block first, cause that'll also cause issues when removing it down the line.

The second one might take some more thinking and needs (UX) designs discussing on it so that might be a longer process than you might expect despite it being fairly simple.

**Comment by AdamWarnock-UA** [comment]
I split this up. I don't know if you want to keep this open or close it.

**Comment by ntsekouras** [comment]
Thanks for the issue @AdamWarnock-UA! Since you split this into two tickets, we can close this one.
