### ISSUE TITLE
Delay when clicking/tapping into different paragraph block on iPad

### ISSUE THREAD

**Issue by jsit** [WordPress/gutenberg#48334]
### Description

When using an attached mouse on an iPad (in Safari) to move focus to a different paragraph block, there is a 1 second-long delay before the cursor moves to the new block.

The delay in focusing seems to be shorter when tapping, but still occurs.

This occurs even if theme styles are turned off in the editor preferences.

### Step-by-step reproduction instructions

1. Create a new post in Safari on iPad with an attached mouse or trackpad
2. Add two multi-line paragraph blocks to the post
3. While the cursor is in one of the paragraphs, click an area in the other paragraph
4. There will be a delay of up to 1 second before the focus and cursor moves to the other paragraph

### Environment info

- WordPress 6.1.1
- Safari iPadOS 16.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hi @jsit. I just tested on my iPad and am not able to replicate this issue. Have you tried the same site on desktop? Any additional info you could provide would be helpful. Thanks!

**Comment by jsit** [comment]
@ndiego Thanks — This issue does not exist on desktop, I’ve tried there.

I also tried disabling all my Safari extensions and content blockers, and all my WordPress plugins, and switching to the Twenty Twenty-Three theme, and the problem persists.

Did you try with a bluetooth mouse? Tapping is quicker, but there is still a small delay, but with a mouse (I’m using the touchpad on the Magic Keyboard) it takes around a second for the cursor to move.

And you’re moving between two paragraph blocks, correct? The cursor is in one paragraph block, then you click a point on the other?

**Comment by jsit** [comment]
@ndiego I’m also noticing this occurring on a WordPress.com-hosted site running the Twenty Ten theme and no plugins.

**Comment by ndiego** [comment]
Hi @jsit, just following up on this one. I am still not able to replicate it. Are you still experiencing this issue using WordPress 6.2?

**Comment by jsit** [comment]
@ndiego Yes, this is still happening for me. It happens on wordpress.org/gutenberg, too, with Safari content blockers disabled.

(There is also some slight keyboard delay, I can tell, between pressing keys and their being registered by the paragraph block. It's very, very minor, but noticeable. This is especially pronounced when making a "large" change, like doing Option-Delete, which deletes by word; but this might be a performance issue with `contenteditable` in Safari iOS in general.)

**Comment by jsit** [comment]
@ndiego I can't say with certainty that [6.5's input processing performance improvements](#57935) are what fixed things, but this problem seems to no longer be an issue for me.
