### ISSUE TITLE
Site Editor save button should only render when changes are made

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#48345]
The Site Editor save button/tray should only render when changes are made, instead of always rendering a disabled state. 

If its not necessary to save changes, the button is confusing — as a disabled save state _could_ indicate there are no changes, and it's not clear that both the "Save" button at the editor header and the "Save" button in the dark material have the same action.  

<img width="480" alt="CleanShot 2023-02-23 at 10 18 21" src="https://user-images.githubusercontent.com/1813435/220866093-cc014717-999c-4255-976d-f8bb1a9f7b01.png">

**Comment by Mamaduka** [comment]
See #47895.

**Comment by annezazu** [comment]
[Pulling Matías' comment](https://github.com/WordPress/gutenberg/pull/47895#issuecomment-1441530397) from the above referenced PR as we look to iterate for 6.2:

>I don't think this is a great solution. The save button (at this higher level of the interface) is an affordance only relevant for when a user is making changes across templates, styles, navigation, and so forth. Displaying it so prominently all the time is a considerable distraction and potentially misleading (a single disabled big blue button can be mistaken as active, and draw attention to it). This item is meant to contextually explain what is going on, and it's failing to do that at the moment. If we need to define a permanent area to contain it we should explore other alternatives, like a collapsed panel when there is nothing to be saved, auto-expanded when there is, and always focusable. Alternatively, the disabled state should not be that of a primary button in this context, it could instead read when the last saved happened, with access to revisions, etc.

**Comment by jameskoster** [comment]
Here's a potential design for this:

<img width="1306" alt="Screenshot 2023-02-28 at 16 41 32" src="https://user-images.githubusercontent.com/846565/221919340-ae640bee-4cd2-4d11-80e4-ec53119231ec.png">


When there are no unsaved changes, the save button displays a checkmark and has the label "Saved x minutes ago". 

When there are unsaved changes the save button label simply reads "Save", and has accompanying text: "X unsaved changes".

If we need a dedicated discard button for 6.2 (see https://github.com/WordPress/gutenberg/issues/27896), that might be positioned next to the Save button:

<img width="433" alt="Screenshot 2023-02-28 at 16 44 31" src="https://user-images.githubusercontent.com/846565/221920074-b1920212-349e-4dc1-908f-65cf0957c9b5.png">

**Comment by youknowriad** [comment]
That looks like a good solution to me. I'm not sure we have all the information at hand (save date...) but I'll see what I can do.
