### ISSUE TITLE
WP 6.2 - revert inadvert changes to Link Control

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#48356]
Some changes to the Link Control UI and UX were accidentally included in  the WP 6.2 release. 

This was as a result of the author of those PRs believing that Gutenberg 15.0 was the final version being included in WP 6.2 whereas in fact it was 15.1 (note this was due to a mistake in a Make Post which the author had read and taken at face value).

The changes were:

- https://github.com/WordPress/gutenberg/pull/47309
- https://github.com/WordPress/gutenberg/pull/47306
- https://github.com/WordPress/gutenberg/pull/46933

These will need to be removed from the release as all communication has been that these would _not_ be included in WP 6.2 and now they have been 🤦

**Comment by annezazu** [comment]
Thank you for handling this!
