### ISSUE TITLE
[WP6.2] Wide and full alignments are lost on the page using a custom template when switching block themes

### ISSUE THREAD

**Issue by ya123123** [WordPress/gutenberg#48355]
### Description

When I switch the active block theme, wide and full alignments are lost on the page using a custom template.

Maybe related to #48074 and #47477, but this also happens with default block themes such as TT2 and TT3.

Tested with WordPress 6.2 beta3 nightly.
Same result with/without Gutenberg plugin 15.2.

### Step-by-step reproduction instructions

1. Use TT2 theme, create a new page and set its template to "Page (Large Header)" 
2. Add blocks and set its alignment to wide or full.
3. Switch active theme to TT3. Then, the template of this page is automatically set to "Default" and wide/full alignments are lost.

### Screenshots, screen recording, code snippet

| Before switching theme (TT2) |  Template |
| --- | --- |
| ![01-tt2](https://user-images.githubusercontent.com/114547428/220895214-8d1e943e-773c-4dca-a51f-a55ffafa981c.jpg) | ![01-tt2-custom](https://user-images.githubusercontent.com/114547428/220895222-13c0b320-bee9-4b30-8126-8b5ac2db0997.png) |

| After switching theme (TT3) | Template |
| --- | --- |
| ![02-tt3](https://user-images.githubusercontent.com/114547428/220896565-2991cdea-9222-48c4-85bb-ca0334a03b05.png) | ![02-tt3-custom](https://user-images.githubusercontent.com/114547428/220896574-68adcfbf-bf8f-41f0-a1d3-d291215c426a.png) |

However, wide/full alignments are back if I change the template after switching theme:

| Change template after switching theme (TT3) | Template |
| --- | --- |
| ![03-tt3](https://user-images.githubusercontent.com/114547428/220897335-ae82414d-abc5-47e6-8935-d28ff235f20f.jpg) | ![03-tt3-custom](https://user-images.githubusercontent.com/114547428/220897340-788e5f0b-ff91-4099-a5b9-07fc67267e69.png) |

### Environment info

WordPress 6.2-beta3-55409 (latest nightly), instawp install
TT2 and TT3 included in nightly
Tested with and without Gutenberg plugin 15.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ghost** [comment]
Thanks for submitting the ticket @mayuge3. I can reproduce this bug on my end. I also want to point out this was working fine on 6.1.1, so this is indeed a new bug.

I also want to specify, the full width option doesn't even show on the first load in this template, but it does once switching, taking me to another thing I noticed.

<img width="871" alt="Screenshot 2023-02-23 at 2 59 25 PM" src="https://user-images.githubusercontent.com/118618474/220928891-acd95bfb-0443-4353-bd9e-1d7116179a7d.png">
<img width="1160" alt="Screenshot 2023-02-23 at 2 59 07 PM" src="https://user-images.githubusercontent.com/118618474/220928915-5ece575f-3fc3-49b4-a892-591f77426156.png">

It might be unrelated to this bug (as this also happens in 6.1.1), but related to this subject, there seems to be something wrong with the Template label as well upon switching, it goes from _Default Template_ to _Page_.

https://user-images.githubusercontent.com/118618474/220928950-2b758bae-62b0-4868-9a36-97af92a84af0.mov

**Comment by tellthemachines** [comment]
I can reproduce this issue on trunk, and @andrewserong already has a fix for it in #48386!

**Comment by andrewserong** [comment]
The close the loop on this one — it appears the issue was that after switching themes, the currently set custom template is no longer available in the new theme, so the post editor was unable to retrieve the post content block from the current template, to determine which layout/alignment controls to display. It turns out there was a bug in the fallback logic for the layout/alignment rules, which should be resolved now that #48386 has landed.

If the issue recurs, feel free to reopen this issue! 🙂

**Comment by ya123123** [comment]
Alighments work in 6.2-beta4-55454 and Gutenberg plugin 15.2.4. 
Thank you!
