### ISSUE TITLE
Support of poster image for video block is missing

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#4837]
At the moment, there's no option to set the ~~cover~~ poster image for a video.

Tested with Gutenberg 2.1

**Comment by karmatosed** [comment]
For now, lets close this as the cover image block stands on it's own. If we were going to add video we would probably have another cover video block. I don't think though that's something we're considering right now for version one. It could be an awesome plugin block though for someone to make.

**Comment by karmatosed** [comment]
Ah! Thanks for the clarification.

**Comment by SergioEstevao** [comment]
This will also be great to support this because of the mobile apps, WordPress iOS editor uses the poster image to represent the video in the editor. This allows us to show something to the users without waiting to get a frame from the video source.

**Comment by gziolo** [comment]
@jorgefilipecosta or @danielbachhuber, any hints on how to get the poster image from the media object after the upload is done? I'd like to help get it solved as this is one of the last blockers to have WordPress mobile apps to work with Gutenberg without those annoying compatibility issues.

**Comment by SergioEstevao** [comment]
@gziolo so if you are using VideoPress (trough Jetpack) you can query the [VideoPress API ](https://developer.wordpress.com/docs/api/1.1/get/videos/%24guid/poster/)and get an thumbnail URL to use.

On WordPress.org I don't know if there is any standard mechanism to get a thumbnail.

Meanwhile I also push a [PR](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/999) on Aztec to allow to display videos correctly even when a poster image is not defined.

**Comment by gziolo** [comment]
Initially, maybe all we need is just an attribute which is able to recognize this poster so it wouldn't break if you open it on mobile and then back on the web. I think it needs to work both ways.

**Comment by danielbachhuber** [comment]
@gziolo To clarify existing behavior, the WordPress Classic Editor inserts a `[video]` shortcode for videos:

```
[video width="1280" height="720" mp4="http://wordpress-develop.test/wp-content/uploads/2018/06/SampleVideo_1280x720_1mb.mp4"][/video]
```

Once the shortcode is within the post, there's an Edit icon you can use to get to the poster image screen:

<img width="691" alt="image" src="https://user-images.githubusercontent.com/36432/41881573-06cbc45e-7899-11e8-9565-1c762e1254bb.png">

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/36432/41881597-23cb709a-7899-11e8-84aa-e5dc5e1518bb.png">

The poster image is only stored as an attribute on the shortcode, not within the database:

<img width="843" alt="image" src="https://user-images.githubusercontent.com/36432/41881621-3e32c9ec-7899-11e8-8418-8d27d426b18b.png">

Gutenberg will need to support `<video poster="#">` and have some UI for setting the attribute value.

Hope this helps clarify.

Related #7501

**Comment by jorgefilipecosta** [comment]
Sorry @gziolo I missed your ping.

I think in Gutenberg the best way to have a poster image is a button on the video block toolbar that allows selecting one from the media gallery plus an inspector UI that allows previewing it or even drag & drop a post image.
The poster image should just be an attribute of the video block.

As @danielbachhuber referred poster image is just a property of the shortcode where it is used it is not stored in the database and the same video may have different poster images in different places.
