### ISSUE TITLE
Block editor  - nested innerblocks will mix attributes with each other until post is saved (only complex object/array attributes affected)

### ISSUE THREAD

**Issue by aplauche** [WordPress/gutenberg#48376]
### Description

In a custom block using innerblocks, if the innerblock has a complex attribute, for instance an array of objects - When a new innerblock is inserted if you change the attributes click away and then click on the first child nested block the attributes will get copied into the other block. They are only copied at a surface level because if you at this point save the post the original nested block will go back to its state before it had new attributes copied in erroneously. Once saved, all buggy behavior is gone until you insert a new innerblock at which point the same issue happens again.

This issue only affects complex attributes - the same blocks will not erroneously copy attributes of type "string" for instance when this occurs.

I suspect this has to do with a deep copy of objects not properly being made when a new innerblock is added, but I can't track down where this would occur.

### Step-by-step reproduction instructions

[bootstrap-grid-blocks-for-gutenberg.zip](https://github.com/WordPress/gutenberg/files/10817026/bootstrap-grid-blocks-for-gutenberg.zip)

You can use this plugin on a blank install of wordpress with 2023 theme to test.

- Simple add a bootstrap row block
- add a column within and set the size on a specific breakpoint
- add another column and set the size to something deifferent
- click away, click on the second column, click away, then click on the first
- The first column will now change size and have the second column's attributes
- if you save at this point the first column will return to the size you originally set.
- Now both columns will behave normally.
- Add a third column and click away, back to third, away, and to the first and the same problem will repeat.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/50935059/220999981-d7466524-d162-4f46-87eb-cdc7bc336db3.mov

### Environment info

WP version 6.1.1
2023 Theme
Gutenberg 14

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aplauche** [comment]
I realize this is a custom block plugin, so that muddies the waters, but this behavior seems like something stemming from within the block editor since the attributes are strangely getting passed from sibling block to block, which should not happen at all.

**Comment by Mamaduka** [comment]
Hi, @aplauche

It definitely looks like an issue with shallow copying of the attributes. Here's a similar report from a few months ago, #41565.

Do you mind including a non-compiled source of the example plugin?

**Comment by aplauche** [comment]
@Mamaduka Thanks for the link! I will check my code and see if I can add an new object to the spread anywhere that could fix the issue. In the meantime here are the plugin source files as well, my apology I meant to upload those originally!
[Bootstrap-Grid-Blocks-for-Gutenberg-simple_debug.zip](https://github.com/WordPress/gutenberg/files/10825545/Bootstrap-Grid-Blocks-for-Gutenberg-simple_debug.zip)

**Comment by aplauche** [comment]
@Mamaduka Okay you were 100% right, it was the same issue it appears. I went ahead and restructured (I left comments in where the restructuring took place in the attached code for anyone looking in the future) and by adding an additional level of object spread when setting attributes the issue is resolved.
I'm going to go ahead and close, but I am still a little perplexed by how the attributes move across blocks that were not duplicated from each other - May just be me not understanding what's going on under the hood completely, but seems strange to me.

Thanks again!

[Bootstrap-Grid-Blocks-for-Gutenberg-simple_debug (1).zip](https://github.com/WordPress/gutenberg/files/10825839/Bootstrap-Grid-Blocks-for-Gutenberg-simple_debug.1.zip)

**Comment by Mamaduka** [comment]
Thank for the update, @aplauche. I'm glad you were able to resolve the issue.
