### ISSUE TITLE
Block: Should block select incur focus?

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#4838]
## Issue Overview

When a block becomes programmatically selected, it also calls `focus` on itself, sometimes resulting in unexpected behavior.

## Steps to Reproduce

1. Navigate to Posts > Add New
2. Insert an Embed block
3. Paste and confirm as URL: https://twitter.com/i/moments/880688233641848832
4. Deselect the block by clicking outside
5. Try to remove the block

## Expected Behavior

If you're like me, you hovered the block and clicked the "More Options" ellipsis menu with the intention of "Remove"-ing the block.

## Current Behavior

Following the steps of "Expected behavior", you'll find yourself scrolled far down the editor page because focus has transitioned into the embed's caption field.

## Possible Solution

We call `onSelect` when the user presses the More Options button:

https://github.com/WordPress/gutenberg/blob/daad3f21319ec9ec73fa1b907119a7464442bfac/editor/components/block-settings-menu/index.js#L46-L48

The `blockSelection` reducer `SELECT_BLOCK` handler adds a focus object:

https://github.com/WordPress/gutenberg/blob/daad3f21319ec9ec73fa1b907119a7464442bfac/editor/store/reducer.js#L408-L417

Then the `BlockListBlock` component calls focus into the _block_ node:

https://github.com/WordPress/gutenberg/blob/daad3f21319ec9ec73fa1b907119a7464442bfac/editor/components/block-list/block.js#L157-L160

We should consider either:

- Not setting `focus` object when `SELECT_BLOCK` is handled
- Update the condition of programmatic focus transfer in `BlockListBlock` to check whether active element exists within the block wrapper (since the settings menu button is within the root element of BlockListBlock, but not within the block's immediate wrapper assigned as the `this.node` ref).

cc @youknowriad @iseulde

**Comment by youknowriad** [comment]
With the removal of `focus` and `setFocus`, I think we can close this issue, as we don't have `focus` state anymore. We only care about the `isSelected` state. (which is globally consistent with what React does since focus in uncontrolled in a React application in general)

**Comment by aduth** [comment]
Heh, I forgot about this issue, but this still describes pretty well some of the issues I've been encountering lately with automatic-focus from clicking the ellipsis menu. Embeds and Columns suffer from this.

**Comment by aduth** [comment]
Have I asked yet if we need this behavior at all?

**Comment by youknowriad** [comment]
> Have I asked yet if we need this behavior at all?

We definitely need this behavior. If you split blocks, remove blocks, autofocus url input of embed block, autofocus RichText in paragraph block... All the use-cases have alternative implementations, but I believe consistency across blocks is betteR.

**Comment by youknowriad** [comment]
> Okay, also might have mentioned it elsewhere, but it would be good if we could detach the More Options menu opening from selecting block,

yes, can you clarify this? In `{ shouldShowMenu && <BlockMenu> }`, do you mean moving `shouldShowMenu` inside the `BlockMenu` component which in theory could allow us to force show the menu when it's opened but would also make us think about when to hide the menu exactly? 

Or am I miunderstanding this?

**Comment by aduth** [comment]
At a glance, I think it's a matter of moving the `onClick` handler from the top-level `BlockListBlock` return to the inner `IgnoreNestedEvents`.

**Comment by aduth** [comment]
Basically, it would be nice if clicking the block settings menu would not select the block automatically.

**Comment by aduth** [comment]
>At a glance, I think it's a matter of moving the `onClick` handler from the top-level `BlockListBlock` return to the inner `IgnoreNestedEvents`.

My glance was mistaken. This is happening within the menu component:

https://github.com/WordPress/gutenberg/blob/5d051146fdad85d27aa4713e2ba90f63167c566c/editor/components/block-settings-menu/index.js#L45-L48

**Comment by aduth** [comment]
In experimenting to remove the `onSelect` from `BlockSettingsMenu`, it did feel quite strange for the block to not become selected, particularly when following into the Advanced Settings menu.

>If you split blocks, remove blocks, autofocus url input of embed block, autofocus RichText in paragraph block... 

I'm wondering if there's a different way we can generalize this: maybe on insertion of a new block? Selecting still seems like the wrong action for this behavior to be taking effect.

**Comment by aduth** [comment]
The initial issue with embeds scrolling is no longer present. I don't know that we can't not have this behavior, so I'm going to close for now.
