### ISSUE TITLE
Template Parts link leads to a Site Editor with just a loading icon in hybrid theme.

### ISSUE THREAD

**Issue by aurooba** [WordPress/gutenberg#48391]
### Description

I've got a hybrid (non-block) theme that has Template Parts enabled. When you go to Appearance > Template Parts, you get a loading screen or an error, instead of the expected Template Parts screen.

### Step-by-step reproduction instructions

1. on `6.2-beta3-55418` version of WordPress
2. Install a regular theme that has Template Parts support enabled and at least 1 Template Part
3. Go to Appearance > Template Parts
4. See the loading screen
5. Refresh the page, get the error: `The theme you are currently using is not compatible with the Site Editor.`

### Screenshots, screen recording, code snippet

<img width="2017" alt="Site Editor with the sidebar but a loading screen instead of the expected Template Parts screen" src="https://user-images.githubusercontent.com/6925260/221055811-f640068f-303e-417a-9492-154e3a0a83b8.png">

If you refresh the page, you get the following error: `The theme you are currently using is not compatible with the Site Editor.`

### Environment info

WordPress: `6.2-beta3-55418` version of WordPress
Gutenberg: Tested with Gutenberg and _without_ Gutenberg
Browser: Google Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
@aurooba does it look like https://github.com/WordPress/gutenberg/issues/48292 could be a similar issue?

**Comment by aurooba** [comment]
@ndiego Ooh yes. This is definitely connected. But in this case, we wouldn't want the front page to load anyway, we want it to take us _directly_ to the `Template Parts` page. Should I add my feedback/notes to #48292 and close this here?

**Comment by ndiego** [comment]
Let's leave this open until we are 100% sure it's the same root issue. If you have time to add feedback on the other issue, that would be awesome. 🙏

**Comment by Mamaduka** [comment]
Fixed via #48343 and will be included in the next beta. We also have an E2E test for this feature, so we should catch similar regressions early.
