### ISSUE TITLE
Button Block: Style for pseudo-elements has priority

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#48393]
### Description

If the Gutenberg plugin is enabled, styles for pseudo-elements take precedence in the button block.

### Gutenberg plugin is enabled

![gutenberg-enabled](https://user-images.githubusercontent.com/54422211/221076487-de726a53-8106-4a7a-b78a-090de45050e6.png)

### Gutenberg plugin is disabled

![gutenberg-disabled](https://user-images.githubusercontent.com/54422211/221076500-15175241-c3e8-4962-866a-010563f66e70.png)

### Environment info

- WordPress Version: WordPress 6.2-beta3-55402
- Gutenberg Version: trunk (15.2.1)

**Comment by talldan** [comment]
I could also reproduce this and was about to report it 👍 

It only seems to be an issue in the Gutenberg plugin and doesn't seem to affect 6.2 (without the plugin).

**Comment by t-hamano** [comment]
I found that the root cause of this issue is the same as that reported in #48706 and is related to #47833.

**Comment by t-hamano** [comment]
This issue will be fixed by #48759.
