### ISSUE TITLE
Button Block: Adding spaces when typing button text does not work

### ISSUE THREAD

**Issue by Zowac** [WordPress/gutenberg#48400]
### Description

Hello, when typing the text on a button, the space bar doesn't work.

A similar problem was reported a few years ago #14914

### Step-by-step reproduction instructions

1. Add a Button block.
2. Begin typing text in the button element and add spaces between words.
3. Observe the problem.

### Screenshots, screen recording, code snippet

[Capture vidéo du 24-02-2023 10:31:18.webm](https://user-images.githubusercontent.com/33932697/221148064-ffd39c8a-a543-4c44-ae37-b7ca230a2c1f.webm)

### Environment info

Browser Firefox latest version

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@Zowac, I couldn't reproduce the issue; I tested with Firefox/Chrome. Can you provide more details about your setup?

* WordPress version.
* Gutenberg plugin version if you're using it.

## Screencast

https://user-images.githubusercontent.com/240569/221156113-cc109929-f956-4266-a421-1ee7c64a76da.mp4

**Comment by Zowac** [comment]
Hello,

Just to be sure I looked again and it turns out that I had missed a plugin that is the source of the problem... Sorry for the inconvenience

Have a nice day and thanks again :)
