### ISSUE TITLE
Video Block on doesn't stay in its lane on public view

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#4842]
using Gutenberg Plugin 2.1
## Issue Overview
The video doesn't stay in the content column but bleeds over the sidebar. 

## Steps to Reproduce (for bugs)

1. Upload a short video to the media library
2. Create a new post
3. Insert a video block using the uploaded video into the post
4. Save the post and preview it 

## Expected Behavior

I expected the video to stay in the content section similar to a YouTube embed
## Current Behavior

It covers the full page and is on top of the sidebar. 

## Possible Solution

Similar display as YouTube video embeds. 
![screen shot 2018-02-02 at 7 19 55 pm](https://user-images.githubusercontent.com/39980/35760438-19eb2cfc-084e-11e8-8bf1-c9657508513e.png)

## Screenshots / Video

In Edit Screen it displays ok.
![screen shot 2018-02-02 at 7 12 19 pm](https://user-images.githubusercontent.com/39980/35760406-e0444de4-084d-11e8-9b75-1255953a4c09.png)

Front End View
![screen shot 2018-02-02 at 7 09 56 pm](https://user-images.githubusercontent.com/39980/35760367-a4880eee-084d-11e8-8611-47c484ea68e9.png)
## Todos
- [ ] Tests
- [ ] Documentation

**Comment by Lewiscowles1986** [comment]
Hi,

I'm not sure this is related to #4961 (I can't see the link). 

What I don't understand is if this is backend, frontend or both that it's "bleeding over to the sidebar?"

Also is this the embed UI, or pasting a YT link, or a custom plugin with Gutenberg in WP?

**Comment by bph** [comment]
Sorry, I didn't make myself clear enough. The bleeding happens on the front end from a Video embed (not YT) - In the edit view (admin) it appears fine.

**Comment by Lewiscowles1986** [comment]
@bph it may be a theme issue. Could you right-click and select inspect (`<Ctrl>+<Shift>+<i>` on windows & Linux, I think it might be the command button on mac)?

You'll get an inspector (maybe docked, maybe as a separate window) it'll look something like this in safari, chrome, firefox and ie.

![image](https://user-images.githubusercontent.com/2605791/36463873-8a6a1f9a-16c4-11e8-808a-13750198f2a9.png)

on the right under the tab that says "styles" you may find the culprit. Unless it comes from `/wp-content/gutenberg/` it's likely not going to be from Gutenberg but maybe another plugin or theme.

**Comment by bph** [comment]
You were right, @Lewiscowles1986 :-) it had to do with the current theme. Sorry about the hassle and thanks for the patience

**Comment by Lewiscowles1986** [comment]
NP @bph, thanks for updating.
