### ISSUE TITLE
Comments and pingbacks on new posts are set to off and cannot be turned on

### ISSUE THREAD

**Issue by helen** [WordPress/gutenberg#4843]
## Issue Overview
New posts created in Gutenberg have comments and pingbacks off regardless of the global setting, and attempts to turn them on in Gutenberg do not work. As a workaround, they can be turned on using Quick Edit in the list table. I ran a `git bisect` and it points to https://github.com/WordPress/gutenberg/commit/6dd01de8675b88626748f1773371065b0ec26591.

## Steps to Reproduce (for bugs)

1. Publish a new post. Note that comments and pingbacks are off.
2. Turn them on in the Dicussion panel and update.
3. View the post and note that comments are off.
4. Refresh the editor and note that both settings are still off.

## Expected Behavior
I would expect the post-level discussion settings to respect the global discussion setting and actually save changes.

## Related Issues and/or PRs
* #4184

**Comment by spencerfinnell** [comment]
Related/Duplicate: https://github.com/WordPress/gutenberg/issues/4663

**Comment by helen** [comment]
@spencerfinnell Thanks! I'm apparently not good at searching GitHub issues after so long in Trac...
