### ISSUE TITLE
Repeated concatenated classes using the new "variations" key in theme.json

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#48441]
### Description

I'm testing the new "variations" key in theme.json used to style block variations using WP 6.2-beta3-55422.
As an example, I created a child theme with a theme.json file that overrides some block styles of its parent theme.json.
The following code changes the border of the "rounded" style variation of the image block:

```
{
    "$schema": "https://schemas.wp.org/wp/6.2/theme.json",
    "version": 2,
    "styles": {
        "blocks": {
	    "core/image": {
	        "variations": {
		    "rounded" : {
		        "border": {
			    "color": "pink",
			    "style": "solid",
			    "width": "5px"
		        }
		    }
		}
	    }
	}
    }
}
```

The code works, but checking the source code I see the following inline CSS:

```
.is-style-rounded.is-style-rounded.wp-block-image.wp-block-image img,
.is-style-rounded.is-style-rounded.wp-block-image.wp-block-image .wp-block-image__crop-area{
    border-color: pink;
    border-width: 5px;
    border-style: solid;
}
```

See the repeated concatenated classes `.is-style-rounded.is-style-rounded.wp-block-image.wp-block-image`? Is this a bug or is this by design to be able to override the default GB styles?

### Step-by-step reproduction instructions

1. Create a theme.json with a "variations" key that styles the "rounded" style of the image block.
2. See the generated inline CSS

### Environment info

- WP 6.2-beta3-55422, no Gutenberg plugin, a custom theme
- Firefox 110.0
- Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
@tellthemachines, I see @andrewserong's [comment](https://github.com/WordPress/gutenberg/pull/46343#pullrequestreview-1238192511) on the PR, that mentioned duplicated class names. Is this intentional to avoid specificity issues?

**Comment by tellthemachines** [comment]
> Is this intentional to avoid specificity issues?

Yes. Because in the editor the global styles rules are prefixed with `.editor-styles-wrapper`, there's no duplication there, but it's necessary in the front end to override the styles coming from some of the core block stylesheets.

I'd expect only the variation classname to be repeated though, not the block one, so there may be a bug in there. I'll look into it!

**Comment by Mamaduka** [comment]
Thank you, @tellthemachines!

**Comment by mrleemon** [comment]
I tried the fix, and now only the variation classname is duplicated. Thanks!

```
.is-style-rounded.is-style-rounded.wp-block-image img,
.is-style-rounded.is-style-rounded.wp-block-image .wp-block-image__crop-area{
  border-color: pink;
  border-width: 5px;
  border-style: solid;
}
```
