### ISSUE TITLE
Query Loop Block impossible to configure in the absence of a Post

### ISSUE THREAD

**Issue by danburzo** [WordPress/gutenberg#48455]
### Description

In the absence of a Post (of type `post`) it is impossible to set up a Query Loop block to loop over posts of a different type (Custom Post Type), because the UI to choose the type is not displayed. 

I expect not to need a dummy Post just to access the Query Loop configuration UI.

### Step-by-step reproduction instructions

1. Have the theme register a Custom Post Type `mytype` (with `public: true` and `show_in_rest: true`) 
2. Set the Front Page to a specific Page via the WordPress settings.
3. Include in the Page a Query Loop with the intention of listing posts of type `mytype`.

The UI does not show any configuration options to let you do that:

<img width="281" alt="Screenshot 2023-02-26 at 17 41 31" src="https://user-images.githubusercontent.com/205375/221420653-3c632c49-0b24-4124-b00c-ddd6912c4914.png">

### Environment info

- WordPress 6.1.1
- Firefox macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ghost** [comment]
After selecting a block variation I'm able to choose a different post type without having any posts created in both Posts and Blog.

<img width="308" alt="Screenshot 2023-02-27 at 11 10 09 AM" src="https://user-images.githubusercontent.com/118618474/221535281-d624db01-24f2-4c27-8806-1d928ed7a4de.png">

Have you tried adding a post variation here first?

<img width="330" alt="Screenshot 2023-02-27 at 11 11 30 AM" src="https://user-images.githubusercontent.com/118618474/221535578-dcfc6383-fe6a-4237-b7ef-d85759c4e0e0.png">

**Comment by danburzo** [comment]
Thanks @tomdevisser, I must have accidentally drilled down into the _No results_ Post Template, or some other form of confusion that I'll blame on working weekend nights 🫣. I confirm I am able to change the post type once creating a variation. 

Cheers!
