### ISSUE TITLE
Post Date block: Display last modified date shows date earlier than published date

### ISSUE THREAD

**Issue by jenxi** [WordPress/gutenberg#48467]
### Description

When using the Display last modified date option, on a new scheduled post, the modified date shows the time of scheduling while the published date shows the scheduled date.

So the modified date shows up as a few days earlier than the published date.

I would expect the modified to now appear if it is earlier than the published date.

### Step-by-step reproduction instructions

1. Add the Post Date block
2. Enable Display last modified date
3. Schedule a post

### Environment info

* WP 6.1.1
* Default blocks, Gutenberg not installed
* Wabi theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi!
For the front, this should be solved by https://github.com/WordPress/gutenberg/pull/46839. It only displays the modified date if it is later than the publishing date.

What do you think should show for the modified date in the editor in this case? Open for suggestions.

**Comment by jenxi** [comment]
Thanks! The editor is pretty self-explanatory as it is.
