### ISSUE TITLE
Update "image size" description on the Media & Text block

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#48477]
## What problem does this address?
Causes confusion as it doesn't change the visual size, but the image dimensions, see #48395.

## What is your proposed solution?
Improve the description.

**Comment by hanneslsm** [comment]
Thank you for the issue!
To ensure consistency, the description should also be added to
- [ ]  image block
- [ ]  images within a gallery

**Comment by ghost** [comment]
The replaced string only exists in the Media Text block. I can't find a setting string in the Image block. Can you specify what copy you'd like to see changed in the mentioned blocks? @HannesDev 

<img width="246" alt="Screenshot 2023-02-27 at 2 39 19 PM" src="https://user-images.githubusercontent.com/118618474/221578440-fa5b8e36-7f26-4250-baeb-1dfba28030a2.png">

**Comment by hanneslsm** [comment]
Correct, only the Media Text block has a description.
The Image block and images in gallery do have the same "image size" function but no description at all (yet).

https://user-images.githubusercontent.com/17861443/221581316-6db57a30-dea9-4fc4-84c9-61601b98a8ab.mp4

**Comment by ghost** [comment]
@HannesDev Good catch, should be added to the Image block now, which should fix it for the Image as an innerblock to Gallery as well.

**Comment by hanneslsm** [comment]
I know this might open up a bigger discussion because the code also has the word "size" in it (don't know if this must be changed then), but what if we change the title to "image resolution"?
The word "size" does not really have any meaning here - It's not necessarily the dimensions (this is what this issue is about) but also, it's not really the file size, is it? With a good compression a 1920x720 image could have nearly as much KB as a "smaller" image. 

Could anyone from the copy team could comment on this? (Unfortunately, I do not know who to put in CC)

**Comment by ghost** [comment]
> I know this might open up a bigger discussion because the code also has the word "size" in it (don't know if this must be changed then), but what if we change the title to "image resolution"?

@HannesDev Already changed it to resolution in the description of the latest commit. Size is still relevant in the title, because of [the name of the function you register them with](https://developer.wordpress.org/reference/functions/add_image_size/), and how it's called in your settings.

<img width="417" alt="Screenshot 2023-02-28 at 10 13 05 AM" src="https://user-images.githubusercontent.com/118618474/221806770-c0cad626-c557-4df8-8676-2de922385023.png">

**Comment by hanneslsm** [comment]
Convinced. This is a bigger topic.
As stated in the other issue I think that the whole topic should be rethought though, holistically from the point of view of good UX. Now that everything is edited via the editor most users probably assume that the best image quality with the fastest loading time is automatically used anyway. I may create a new, well thought-out issue when I have more time.
