### ISSUE TITLE
File Block: Turn off PDF embedding by default.

### ISSUE THREAD

**Issue by karks88** [WordPress/gutenberg#48486]
## What problem does this address?
When using the core File block to upload a PDF document, the default behavior is to display it as an embed. This must be manually turned off each time the block is used.

## What is your proposed solution?
Ideally, WordPress would remember that you've turned off displaying the file as an embed. 

An alternative would be a function or setting in the block's block.json file to disable this behavior. Looking through the file, I did not see a way to do this at the present time.

**Comment by bph** [comment]
I can see that a few site owners would find a default setting in the preferences helpful to standardize how PDFs are embedded. And developers might appreciate a parameter/attribute to turn embedd off entirely.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/34825 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
