### ISSUE TITLE
Social link block distorted visually when moved (highlighted)

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#48492]
### Description

Looks like the `.is-highlighted` class is conflicting with the styling of the Social Links block, resulting in visual distortion when the block is moved (i.e. has the `.is-highlighted` class applied). 

It looks like the class is applying to the block itself, and the element inside it: 

<img width="59" alt="CleanShot 2023-02-27 at 09 40 42" src="https://user-images.githubusercontent.com/1813435/221593609-a0ae56f7-0a27-4f65-a76a-7ec4dbe2da74.png">

### Step-by-step reproduction instructions

1. Add a Social Links block.
2. Add two Social Link blocks.
3. Move one of them using the block movers.
4. See the circle break and the background color of the icon fill the block container.

#### Showcasing the issue: 

https://user-images.githubusercontent.com/1813435/221592615-50041a24-436c-48a8-8452-d2342b26a27c.mp4

#### Identifying the `is-highlighted` class issue: 

https://user-images.githubusercontent.com/1813435/221592628-ed439873-5a47-4f30-893a-497d7388e221.mp4

### Environment info

- WordPress RC 3
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
@richtabor I think this can be closed now. Can you confirm when you have a sec?

**Comment by richtabor** [comment]
Yup. Thanks!
