### ISSUE TITLE
Post featured image block dimensions disregarded if 'link to post' is selected

### ISSUE THREAD

**Issue by jamiemarsland** [WordPress/gutenberg#48494]
### Description

When you select 'link to post' it breaks the formatting for featured image dimensions (they are disregarded)

### Step-by-step reproduction instructions

Add query loop block
Set featured image dimensions
Select 'link to post'

### Environment info

2023 theme
Tested on 6.1.1 and 6.2 beta
tested with gutenberg plugin and without gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
Yes, I noted this as well. PR for testing incoming.

**Comment by richtabor** [comment]
Screenshot from the editor, with square 1:1 applied and link: 

<img width="1156" alt="CleanShot 2023-02-27 at 10 01 03" src="https://user-images.githubusercontent.com/1813435/221598966-1e8e7f09-7616-4204-998b-22ca0e3334d3.png">

Screenshot from the front-end: 

<img width="1156" alt="CleanShot 2023-02-27 at 10 01 19" src="https://user-images.githubusercontent.com/1813435/221599080-6172ac2e-05d0-4520-88d8-d9b939f4b850.png">

**Comment by richtabor** [comment]
@jamiemarsland Mind giving that PR a test drive?

**Comment by jamiemarsland** [comment]
Thanks Rich, i might be going crazy but i don't see the aspect ratio option anymore?

**Comment by richtabor** [comment]
> Thanks Rich, i might be going crazy but i don't see the aspect ratio option anymore?

Should be here: 

<img width="473" alt="CleanShot 2023-02-27 at 11 12 16" src="https://user-images.githubusercontent.com/1813435/221617489-c16074c8-7b08-46db-a5a3-6a75bd2029af.png">

**Comment by jamiemarsland** [comment]
Hmm i need to dig some more, those settings aren't showing for me now
