### ISSUE TITLE
Check support for `/u` flag in installed PCRE library

### ISSUE THREAD

**Issue by jaswrks** [WordPress/gutenberg#4852]
## Issue Overview
Gutenberg's PEG parser [expects](https://github.com/WordPress/gutenberg/blob/daad3f21319ec9ec73fa1b907119a7464442bfac/lib/parser.php#L1818) the PCRE library to support the `/u` flag. We should probably check the installed PCRE library to confirm it supports this flag before using it. I opened a trac ticket in core to suggest a function for doing so: https://core.trac.wordpress.org/ticket/43224, and I've asked about this in the phpegjs package: https://github.com/nylen/phpegjs/issues/9

## Next Actions
- [x] Follow-up on [this issue](https://github.com/nylen/phpegjs/issues/9) in the phpegjs package.
- [x] Follow-up on [trac ticket #43224](https://core.trac.wordpress.org/ticket/43224).

**Comment by nylen** [comment]
This case is already handled in the Gutenberg code.  See:  https://github.com/WordPress/gutenberg/pull/1869,  https://github.com/WordPress/gutenberg/search?q=_gutenberg_utf8_split

The remaining follow-up item here is a core merge task, for which I'd suggest creating a separate issue.  WordPress' [`_mb_substr` compatibility function](https://core.trac.wordpress.org/browser/tags/4.9.5/src/wp-includes/compat.php#L65) is almost exactly the same as `_gutenberg_utf8_split` introduced for this purpose, so these functions should be refactored to share most of their logic and only split off where they need to be different.

**Comment by youknowriad** [comment]
I don't think we're using PEG in php anymore.
