### ISSUE TITLE
Gradients broken for cover blocks when only enabled at the block level in theme.json

### ISSUE THREAD

**Issue by grantgeard** [WordPress/gutenberg#48534]
### Description

In theme.json, when gradients are disabled in the global color settings and then re-enabled at the block level for the Cover block, they display in the editor but not on the front-end.

```
{
    "$schema": "https://schemas.wp.org/trunk/theme.json",
    "version": 2,
    "settings": {
        "blocks": {
            "core/cover": {
                "color": {
                    "gradients": [
                        {
                            "slug": "black-to-transparent",
                            "gradient": "linear-gradient(to top, black, transparent)",
                            "name": "Black to Transparent"
                        }
                    ]
                }
            }
        },
        "color": {
            "gradients": []
        }
    }
}
```

In the generated CSS, the variable for the gradient is made available to the scope of the Cover block selector, but no styles are generated to actually apply the variable to the background despite the correct class names being present on the elements.

Tested the same settings for the Group block and it worked as expected.

### Step-by-step reproduction instructions

1. Disable gradients in the color settings of theme.json
2. Add a gradient to the Cover block
3. Apply the gradient to a Cover block and update the entry
4. Note that the gradient is applied in the editor but not on the front-end

### Environment info

- Tested on WordPress v6.1.1 using Twenty Twenty-Two theme
- Gutenberg plugin not installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I wasn't able to reproduce this in my testing. Here's my cover block in the site editor:
![Screen Shot 2023-04-11 at 2 29 45 pm](https://user-images.githubusercontent.com/677833/231075059-043f597c-79fe-4e41-97d0-246721b3bb17.png)

Here it is on the frontend:
![Screen Shot 2023-04-11 at 2 29 57 pm](https://user-images.githubusercontent.com/677833/231075125-9b7b88f2-9d2f-459b-bae7-80140187db44.png)

I was using the latest version of the gutenberg plugin (the unreleased `trunk` code), so it seems as though the issue may have been fixed.

**Comment by talldan** [comment]
I'll close the issue, but let me know if you're still experiencing problems after updating
