### ISSUE TITLE
Pasting Microsoft Word content on Google Chrome for macOS creates an image block rather than text.

### ISSUE THREAD

**Issue by mellis32** [WordPress/gutenberg#4854]
## Issue Overview
Gutenberg now supports pasting pre-formatted content from Microsoft Word in most web browsers. 

However, when I use Google Chrome on MacOS, pasting pre-formatted text from Microsoft Word creates an image block of text rather than the expected, editable text. All of my Google Chrome extensions are disabled.

## Steps to Reproduce (for bugs)
1. Open a document in the latest version of Microsoft Word for MacOS.
2. Copy contents of document.
3. Paste into Gutenberg editor, using Google Chrome for MacOS.
4. The text gets pasted as a block image. Te text cannot be edited in anyway, the content is unusable as a block image rather than workable text.

## Expected Behavior
Content pasted from Microsoft Word should show up as formatted text, it should behave in a similar manor as it did in the classic editor. Images, text, and other elements copied from Microsoft Word should be handled properly rather than just turning the entire copied document into a giant image.

## Current Behavior
Copied text gets pasted as a block image. Te text cannot be edited in any way, the text content is converted to an image rather than pasted as workable text.

## Screenshots / Video
Result of pasting a sample document into gutenberg (It is pasted as an image block rather than useable text):
![Paste](https://i.imgur.com/N0mGFRP.png)
![Paste issue](https://i.imgur.com/zTH7smk.png)
I have this problem regardless of the amount of text I copy. Even just copying one letter from word gets pasted as a letter in WordPress.

Here is a GIF that demonstrates my problem: https://i.imgur.com/VqNtz6o.gif

## More info
Using MacOS High Sierra, with latest version of Microsoft Office 2016 for Mac. Copied into Google Chrome. Site I run: http://www.mdinvasives.org

Edit:
I discovered that "Paste and Match Style" does not have this issue.

All of these browsers are experiencing this issue on MacOS High Sierra for me:
- Google Chrome v64
- Google Chrome Canary v66
- Opera v50

This issue does NOT affect:

- Google Chrome for Windows 10
- Firefox for Windows 10
- Firefox for MacOS
- Safari for MacOs

**Comment by WPprodigy** [comment]
Hmm, interesting. 

MS Word should be supported: https://github.com/WordPress/gutenberg/tree/95d6c39ae7e71f565c38bacb6813503bee9c2c69/blocks/api/raw-handling

Does this only happen when the document contains an image?

**Comment by mellis32** [comment]
Thank you for the reply @WPprodigy.  I just tried this on Windows 10 and had no issue, investigating more now...

**Comment by mellis32** [comment]
Just tried again on my Mac, had no issue on Firefox.  Could be a Chrome extension that interfered, still investigating.

**Comment by mellis32** [comment]
Still coming out as an image block on my Google Chrome for MacOS with all extensions disabled. I do not have this problem with:
- Google Chrome for Windows 10
- Firefox for MacOS
- Safari for MacOs

**Comment by mellis32** [comment]
Just copying one letter is pasting as an image block. 

I'm still investigating if this is a WP problem, or something about my setup. I don't have another MacOS install to test.

**Comment by mellis32** [comment]
I just tried on fresh install of Google Chrome Canary and have the same problem.

**Comment by mellis32** [comment]
Here is a GIFV that demonstrates my problem: https://i.imgur.com/VqNtz6o.gifv

I discovered that "Paste and Match Style" does not have this issue, as shown in the GIFV.

So far I have seen this issue on:
- Google Chrome v64 on MacOS High Sierra
- Google Chrome Canary v64 on MacOS High Sierra
- Opera v50 on MacOS High Sierra

**Comment by kevinfodness** [comment]
This issue is occurring for me, as well as my coworkers, in the latest version of Word for Mac + Chrome. It is reproducible with a new, blank Word doc with just text content.

I'm not certain if this is a Gutenberg bug per se or if it is actually occurring at the Webkit level (since Opera is also affected).

**Comment by kevinfodness** [comment]
Apologies—I meant the Blink engine, not Webkit.

**Comment by kevinfodness** [comment]
Possibly this issue, specifically: https://bugs.chromium.org/p/chromium/issues/detail?id=728937

**Comment by mellis32** [comment]
Worth noting that this is not an issue when pasting into the classic editor, so although it may partly be an issue with Blink, Gutenberg is handling the pasted content differently in a way that led to this issue.

**Comment by iseulde** [comment]
> Te text cannot be edited in any way, the text content is converted to an image rather than pasted as workable text.

Huh, I've never seen this before. I have tested Word a few months back, and didn't see this happen. I'm starting to suspect that Word supplies a file as well as plain text and rich text, and that this file gets processed first and stops further processing, the assumption being that, if there is a file, it is not text paste. A workaround might be to look if there is any text present.

**Comment by WraithKenny** [comment]
#11683 Related to this
