### ISSUE TITLE
Gutenberg Classic block - custom buttons insert shortcodes at start of post

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#4855]
## Issue Overview
I have a plugin ( called oik ) which provides 3 buttons for creating shortcodes in the Classic Visual editor and one Quicktag button for the Text Editor. 
The TinyMCE buttons appear to work correctly in the Classic block.
Except the inserted shortcodes don't always get inserted where they're supposed to be.
More often than not they get inserted at the start of the block.

I would like to know what code changes I need to make to get the logic to work correctly, assuming this is going to be possible. 

## Steps to Reproduce (for bugs)

1. Install and activate the oik base plugin - from WordPress.org or https://github.com/bobbingwide/oik
2. Visit oik options > Buttons and select the Button shortcodes checkbox 
3. Open the editor and create a Classic block
4. Type some text 
5. Click on the Button - Insert bw_button shortcode
6. Click on Insert Button
7. Notice that the shortcode is inserted at the start of the block.

## Expected Behavior
The shortcode should be inserted where the cursor was.

## Current Behavior
More often than not the shortcode is inserted at the start of the block.

## Possible Solution
I have no idea how to fix this. 

My code currently uses 
```
tinyMCE.activeEditor.execCommand('mceInsertContent', 0, shortcode);
```

It works, the shortcode is created, but I don't have any control over the insertion point. 
I have tried to save the current location in a global variable and use this to reposition before the insertion. But the global variable is getting changed. I don't understand why.

## Screenshots / Video

![image](https://user-images.githubusercontent.com/2474435/35781050-a9a293b4-09dc-11e8-96f2-e2d1ad68c52c.png)

![image](https://user-images.githubusercontent.com/2474435/35781044-935a9bc4-09dc-11e8-9dda-2f8285bfe425.png)

![image](https://user-images.githubusercontent.com/2474435/35781054-c36951fc-09dc-11e8-991a-e9e6d2cddf7a.png)

## Related Issues and/or PRs

I discussed this with @youknowriad who was of the opinion "Custom TinyMCE buttons should still work like before in the classic block." 

@azaozz suggested I open this issue having first given this explanation.

Generally Gutenberg loads two tinymce.js. One is the WP tinymce.min.js, the other is a different version "built-in" tinymce.js
The WP tinymce works as before, it's a global, etc. The Gutenberg is not.
So doing things like `tinyMCE.activeEditor...` will always fail as that is accessing the global/WP tinymce which is not used in Gutenberg
Think there was an issue about that, not sure what is happening with it
also about not loading two versions of tinymce.js

This might be related to https://github.com/WordPress/gutenberg/pull/4754

My own issue is https://github.com/bobbingwide/oik/issues/100

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mtilly** [comment]
My plugin has this same issue, there is no control over the insert position.  No matter where the cursor is currently positioned in the editor block, any insert goes to the top of the content.  Please fix this before general release of Gutenberg as it is essential for backward compatibility.

**Comment by earnjam** [comment]
Similar to #10509

**Comment by bobbingwide** [comment]
just to confirm i didn’t make any progress. something that appeared to work in February is only working in one environment where i’ve built a version of Gutenberg 4.0-RC2 locally.

**Comment by bobbingwide** [comment]
I've resolved the issue with my buttons not being displayed at all, for my laptop at least. `thickbox.css` was not being enqueued when using Gutenberg's block editor. This could be considered a backwards compatibility issue. I've already developed a workaround for oik.

**Comment by mtias** [comment]
Combining with #10509 so we have a single tracking point.
