### ISSUE TITLE
Post Title receiving Post Content layout styles in the post editor.

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#48579]
### Description

If the Post Content block in a post template has custom layout settings, they will also be applied to the title in the post editor. This seems to be a result of #46698 which adds the post content classes to the title area.

### Step-by-step reproduction instructions

1. Edit the Post Content block in the post template to e.g. justify content right, and give it a narrow content width;
2. Save and reload the post page;
3. Verify that the post title is now also aligned to the right and correspondingly narrow.

### Screenshots, screen recording, code snippet

<img width="1047" alt="Screenshot 2023-02-28 at 5 02 12 pm" src="https://user-images.githubusercontent.com/8096000/221767798-c312dd02-655c-4fdf-ab13-5a7b6e9f4098.png">

### Environment info

Gutenberg latest trunk and also WP 6.2 Beta 3. Not reproducible on WP 6.1.1, so looks like a regression from the latest release.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I don't love it, but was this intentional?

I know there have been some experiments, but it would be great in the future if the title was not part of the post content at all. 😅

**Comment by annezazu** [comment]
Adding this to to do since it seems like this was a regression, unless we hear that this was done intentionally for some reason!
