### ISSUE TITLE
Gutenberg doesn't allow you to insert Gravity Forms

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4857]
## Issue Overview
Gravity Forms is probably the most popular Forms plugin within the WordPress ecosystem. After creating a form, it provides the user with an _Add Form_ button when editing their content that allows a user to insert a Form into their content.

![classiceditor-gravityforms](https://user-images.githubusercontent.com/2078245/35785062-9557ffbc-0a71-11e8-85bd-1cf0b1bfe295.png)

The Gravity Forms _Add Form_ button doesn't display in Gutenberg which makes it difficult to insert a form into your content.

![gutenberg-gravityforms](https://user-images.githubusercontent.com/2078245/35785235-11611840-0a73-11e8-868d-6624fc25b0ea.png)

## Steps to Reproduce (for bugs)
1. Activate Gravity Forms
2. Create new page/post or edit existing page/post
3. Try to insert a Gravity Forms form using the _Add Form_ button

## Expected Behavior
I need to be able to insert a form into my content.

## Current Behavior
Can't insert form as the _Add Form_ button doesn't display

_Firefox Quantum 58.0.1 (64-bit)
Gutenberg 2.1.0
WordPress 4.9.2
Gravity Forms 2.2.5.21_

**Comment by youknowriad** [comment]
We have a way to support custom media buttons https://github.com/WordPress/gutenberg/pull/4352 but we decided not to merge it right now to encourage people to use blocks instead of these buttons which should be considered "deprecated" as tied to the design of the current editor.

**Comment by maddisondesigns** [comment]
That's not a great solution. While I'm happy to contact Gravity forms, we can't be expected to contact every single plugin author and get them to update their plugins before Gutenberg rolls out. What happens if a plugin author doesn't know React, or just don't have the time/manpower to convert an existing plugin? Gutenberg needs to support plugins as they are now, and not expect everyone to change prior to 5.0. Just one more reason why this should be released as a plugin first, rather than pushing it straight into core. You want people to start using blocks and start building for Gutenberg, yet you haven't even finished building this thing yet and what you have built, still has huge issues. If you've already got a solution to support custom media buttons (that works), then you need to implement it.

**Comment by youknowriad** [comment]
> Just one more reason why this should be released as a plugin first

It's already a plugin for almost a year now.

--
I'm not saying this PR is not going to be merged before the merge to Core, I'm saying not now to encourage people to migrate.

**Comment by jasmussen** [comment]
I wish we could turn off the "thumbs down" feature on Github, because it generates negativity where none is needed. We are all humans here on the other end of the tickets, and we're working hard to make a great editor. It's clear we haven't convinced you that we're there, yet, but please let's keep the human cost in mind as we discuss these things.

In Gutenberg, the UI for inserting content is the unified inserter that's accessible from the editor bar, the side UI and slash command. This is the UI we mean for users to learn as the single place to go to, for adding content. Adding additional insertion UI works against that goal.

If you need those buttons, the best UI you can get for it is the classic editor. There is a classic editor plugin for WordPress, officially supported in the plugin repository. Installing this plugin in WordPress can be as simple as a single click, and you're back to your 4.9 experience. For plugins that haven't chosen to support Gutenberg, or haven't had time to do so, this will provides a means to continue to use those plugins without interruption.

**Comment by travislopes** [comment]
@maddisondesigns A dedicated Gravity Forms block will be released in the very near future.

**Comment by maddisondesigns** [comment]
> It's already a plugin for almost a year now.

Yes it's a plugin now, but its not a finished plugin is it. You only have to look at the number of active installations (currently at ~5000) to see that there's a huge number of people out there who haven't even tried this and guaranteed, there's a huge number of plugin/theme developers among those as well.

> I'm not saying this PR is not going to be merged before the merge to Core, I'm saying not now to encourage people to migrate.

Well that's exactly what it sounds like you're saying, both here and including comments from other people on #4352. You're going about this in completely the opposite way of what should be done. You don't disable a core feature before people have had a reasonable amount of time to update their code, or before people even know that this feature wont be supported. You should be supporting the feature as it is now and then communicating to people that this functionality will be deprecated in favour of blocks, from version 5.x.

> I wish we could turn off the "thumbs down" feature on Github, because it generates negativity

The Thumbs down is in noway directed towards the person making a comment. It's simply a reaction to say that you disagree with a comment, in the same way the Thumbs up is saying that you agree. You can't have one without the other.

> the UI for inserting content is the unified inserter that's accessible from the editor bar, the side UI and slash command

What is "slash command"?

> We are all humans here on the other end of the tickets, and we're working hard to make a great editor. It's clear we haven't convinced you that we're there

I fully realise how hard you guys are working on this, but yes, I still have huge reservations about what is going to end up in core. Believe it or not, I am all for Gutenberg. I have been wanting a block editor built into core for years. Unfortunately though, what you're going to end up releasing will not have anywhere near the kind of functionality that people can currently get from third party Page Builder plugins, and until multi-column support is added, provides very little benefit over the existing TinyMCE editor. Gutenberg is way to unstable at the moment, Custom Fields still don't work properly, and the markup that it currently produces on the front-end is messy and ridiculously difficult to style in any suitable way. Not everybody wants every page to be full-width single column and it seems like no-one has even taken this into consideration. We still cant even do something as simple as selecting a page template yet. There's still a very long way to go before I would even consider using this as my main editor

**Comment by StaggerLeee** [comment]
He is telling you the truth, thumbs up or not.

- There are millions of websites out there with buttons like this, above old TinyMce.
- For those complex websites owner paid 1 to 5 monthly average salaries (paycheck, EU).
- Owner does not want to spend a single € more on website, specially he/she did not ask for any changes.
- Company who made website for money will not do it for free.

Do you from gutenberg team accept to pay ?
Do you accept to fix mess on those websites, if you do not want to pay ?

**Comment by StaggerLeee** [comment]
Can you from Gutenberg tema swear and promise now Classic Editor plugin will be there forever ?
And not some temporary solution, what is not solution at all.

**Comment by jasmussen** [comment]
> What is "slash command"?

Type / on an empty paragraph and you can search through blocks to insert. This is inspired by messaging apps like IRC or Slack, but it is an entirely optional feature you don't have to learn if you aren't going to use it. 

> There are millions of websites out there with buttons like this, above old TinyMce.

Websites that choose to manually upgrade to WordPress 5.0 can install the officially supported [Classic Editor plugin](https://wordpress.org/plugins/classic-editor/), which will restore the 4.9 editor. Any metabox you have that requires this editor will work, as will any "add media" button.

> Can you from Gutenberg tema swear and promise now Classic Editor plugin will be there forever ?
And not some temporary solution, what is not solution at all.

Open source software never goes away.

**Comment by StaggerLeee** [comment]
You did not answer. I expected that.

**Comment by jasmussen** [comment]
Can we please keep the adversarial tone out of these discussions? We are all human beings here, trying to build good software. This negativity will breed only negativity, and will not accomplish anything, quite the opposite. 

_Forever_ is a very very long time. No, I can't promise that the "Classic Editor" plugin will exist forever, or be officially supported. Our goal is for Gutenberg to be a replacement for the Classic Editor, to make it so good that people, after having used the Classic Editor for a while, will _want_ to disable it. 

I don't know of any plans to retire the Classic Editor at some point, or to intentionally break the functionality. I don't see what the purpose of that would be. 

Even if after many years, the current maintainers of the Classic Editor plugin decide to no longer want to support it, the fact that it is _open source software_ released under the GPL license, means that anyone can download the plugin, and put it in the repository again. Or even merge it into their own plugins.

**Comment by maddisondesigns** [comment]
> Type / on an empty paragraph and you can search through blocks to insert. 

Thanks for that. That's really cool. That's the first time I've seen that functionality mentioned

**Comment by jasmussen** [comment]
> Thanks for that. That's really cool. That's the first time I've seen that functionality mentioned

👍 👍

We're looking into ways to make this more discoverable, but balancing it against knowing you don't have to learn this feature to use Gutenberg.

If you happen to create an empty paragraph and deselect it, there's a small tip in the placeholder text:

<img width="659" alt="screen shot 2018-02-06 at 10 30 52" src="https://user-images.githubusercontent.com/1204802/35851661-f67e7eda-0b28-11e8-9bbd-59735c5f7ee8.png">

**Comment by StaggerLeee** [comment]
Classic Editor plugin is from one developer, not plural. And he is from WP core team.
Let us see how long it will be there, or will Gutenberg be so deep in core that it will be impossible to remove.

For me it is the same, nobody will drag me to the court of law because some website is ruined.
Speaking generally.

Tell people as it is. Websites will be ruined, and somebody has to pay for it. In money or time, regardless.

**Comment by karmatosed** [comment]
@StaggerLeee whilst you have clear feelings on this, your tone is not appropriate right now and you are not showing the respect being given to you. This issue needs to focus on a solution not divert to opinion or a combative approach.

**Comment by StaggerLeee** [comment]
What is solution ?
As it is now all those buttons have to be converted to Gutenberg block. 

Please stop accusing commenters of "negativity" any time you read something you do not like to read.
You are paid for this job. If you find it stressful ask your boss to give you another deadline. Thank you.

**Comment by karmatosed** [comment]
Please do not resort to personal attacks @StaggerLeee, you have been asked repeatedly to respect people and refuse to. Whether someone is paid or not does not change whether you should be polite. Everyone understands being passionate about something, but you can do that respectfully, right now you are not doing that.

I am taking the decision to lock this thread as it was closed already. As with any project simple respect is the minimum requirement to participate. Everyone here no matter what their employment status deserves that, we are all humans.

**Comment by carlhancock** [comment]
@maddisondesigns The official Gravity Forms Gutenberg block has been released. We now have an add-on called the Gravity Forms Gutenberg Add-On that is in beta that introduces a Gravity Forms block in Gutenberg.

You can find out more here: https://www.gravityforms.com/gutenberg-add-on-v1-0-beta-1/

This is the first of many Gutenberg blocks we will be building for Gravity Forms that introduce all kinds of new functionality. This is just the very beginning. As Gutenberg matures and becomes more feature complete we will be focusing a lot of our attention on Gutenberg integration and blocks.

The bottom line is plugin developers needs to be on top of what is going on with Gutenberg. They need to be learning and working on incorporating Gutenberg compatibility TODAY. They also needs to be thinking about what new doors that open because of Gutenberg. New places they can take their plugin. 

Is the transition going to be painful? Is it scary? Absolutely. It’s going to be rough. I don’t envy agencies and those that do client work and what they are going to have to deal with from a client standpoint. But ultimately there are a lot of benefits that Gutenberg will bring to WordPress in the long term.

Time to get on the Gutenberg train or go use something else.

**Comment by maddisondesigns** [comment]
@carlhancock Thanks Carl. I got tweet from @travislopes earlier today letting me know that you have it available for download now.

**Comment by azaozz** [comment]
Just wanted to make this clear, again.
1. There are no plans to discontinue the Classic Editor plugin, ever. As @jasmussen points out, open source software does not go away. This is its nature. I'd expect this plugin will still be available 5, 10, even 20 years from now. Of course it's a completely different question if somebody will want to use it then :)
2. The Classic Editor plugin is authored by the WordPress community, the same people that contribute to the WordPress Open Source Project. I may be the only person who has committed code to it for now, but any contributor can suggest a change or create a patch, and any committer can add it and release an update.
