### ISSUE TITLE
Text Columns block causing error when new column added, but nothing entered and saved

### ISSUE THREAD

**Issue by amdrew** [WordPress/gutenberg#4858]
## Issue Overview

The `Text Columns` block can cause an error in the admin: `The editor has encountered an unexpected error.`

- Gutenberg v2.1 (latest master)
- WordPress 4.9.2
- No other plugins active
- Firefox Quantum 58.0.1 (64-bit)

## Steps to Reproduce

1. Add a `Text Columns` block

    <img width="484" alt="screenshot 2018-02-05 18 39 23" src="https://user-images.githubusercontent.com/52581/35789980-c646ce18-0aa4-11e8-91df-dafaeab98d7d.png">

2. Increase the columns to `3`, put content in the first 2 columns but leave the third empty

    <img width="1189" alt="screenshot 2018-02-05 18 40 27" src="https://user-images.githubusercontent.com/52581/35789985-d063ee44-0aa4-11e8-8f77-306b894ff314.png">

3. Publish the page. The `post_content` becomes `<!-- wp:text-columns {"columns":3} /-->` and nothing is outputted to the front end.
    
    <img width="378" alt="screenshot 2018-02-05 18 40 38" src="https://user-images.githubusercontent.com/52581/35790028-0b574636-0aa5-11e8-9d72-8066609ec677.png">
 
4. Refresh the page in the admin and the error appears:

    <img width="867" alt="screenshot 2018-02-05 18 41 12" src="https://user-images.githubusercontent.com/52581/35789964-ae4454fc-0aa4-11e8-9116-d9a10788325e.png">

Console shows `TypeError: content[index] is undefined`:

<img width="1282" alt="screenshot 2018-02-05 18 41 25" src="https://user-images.githubusercontent.com/52581/35790077-45e1f58a-0aa5-11e8-835d-f783c47485ce.png">

## Expected Behavior

The `post_content` should be correctly saved, the columns outputted on the front-end with content, and there should be no error when refreshing the admin page.

## Related Issues and/or PRs

Potentially https://github.com/WordPress/gutenberg/issues/4709 though not the exact same JS error.

**Comment by ajitbohra** [comment]
Works as expected on master / v3.2
