### ISSUE TITLE
Inconsistent use of the chevron icon in the dark sidebar

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48591]
The dark sidebar in the site editor utilises a drill down pattern to expose subsequent levels of navigation.

At the root level of Design, we indicate this behaviour by appending a chevron to each menu item:

<img width="351" alt="Screenshot 2023-02-28 at 13 23 19" src="https://user-images.githubusercontent.com/846565/221866815-8b4e8d83-fd5a-41aa-9b62-a60dddf247a9.png">

However, in each of the other panels, this chevron does not appear, despite the menu items having the same behaviour:

<img width="355" alt="Screenshot 2023-02-28 at 13 24 06" src="https://user-images.githubusercontent.com/846565/221867009-77aced48-db91-4417-8f19-f0a7e3ab4d6e.png">

We should be consistent so that users are better able to predict how the UI will behave. That means either removing the chevrons at the root, or adding them to the other panels.

Important note: We already use the small chevron icon in the Navigation panel to indicate the presence of a submenu:

<img width="357" alt="Screenshot 2023-02-28 at 13 32 04" src="https://user-images.githubusercontent.com/846565/221869320-b52b9df9-f777-436f-a2e9-a23907f9cce5.png">

This is an established pattern in List View as well. If we elect to use chevrons as a universal drilldown indicator for menu items in the dark sidebar, then we need to make sure there's no confusion between the two.

**Comment by jameskoster** [comment]
I think it would be good to try applying the small chevron to any item that invokes a drilldown.

**Comment by apeatling** [comment]
I've opened a PR to fix this. ~It does not address the navigation screen since we already use chevrons there. I'm happy to address the nav screen in a different PR, or change the chevron to something else and include the nav screen in the open PR.~ Update: The nav menus work differently so don't need this.

**Comment by jameskoster** [comment]
If you don't mind I'm going to re-open, purely because we won't have consistency until the nav menu items are updated.

**Comment by apeatling** [comment]
Thanks, yes makes sense. That was automated when the PR closed. 👍

**Comment by apeatling** [comment]
Follow up PR for navigation screen https://github.com/WordPress/gutenberg/pull/50149

**Comment by jameskoster** [comment]
I think we're in a good spot with this one now.
