### ISSUE TITLE
Custom link handling in Navigation panel

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48593]
Working with Custom Links in the Site Editor's Navigation panel is extremely clunky:

https://user-images.githubusercontent.com/846565/221880358-0f6272ad-46b7-4152-aff8-ce1235a5ea9c.mp4

* There's no way to edit the link details. 
* It's possible to select the item, but nothing happens. The subsequent appearance looks broken (grey on blue).

**Comment by annezazu** [comment]
Is this worth adding to the 6.2 board? I know work is being done to update the inserter to prioritize page links but this still feels quite broken.

**Comment by SaxonF** [comment]
The changes in https://github.com/WordPress/gutenberg/issues/48612 will cover custom link editing, but we'll still need to add the ability to trigger the edit dialog from browse mode navigation sidebar. Once the other issue is complete, we can use this issue to track the triggering.

https://user-images.githubusercontent.com/1072756/222632316-0c697ef3-3580-43ad-9e49-8934bed67d12.mp4

**Comment by jameskoster** [comment]
That seems to work reasonably well.
