### ISSUE TITLE
Site Editor dark sidebar contents should remain stationary when entering edit view

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48595]
We currently have a bit of a mismatch in terms of animation when you move between browsing / editing:

https://user-images.githubusercontent.com/846565/221882193-f0bedfdb-f854-456e-a37c-fd10a74f338f.mp4

Note how the Site Icon and Save button remain in place, but the menu items (very quickly) slide away to the left. Ideally everything in the dark sidebar should remain stationary, solidifying the idea that the frame sits "on top" of everything else.

**Comment by ghost** [comment]
@jameskoster You must have a very sharp eye, cause I watched it 4 times on 0.25 playback speed and I still can't see what's wrong about it, haha. Thanks for creating the issue though.

Basically what you're saying is, the menu items are sliding to the left while they shouldn't be? Is the opacity animation okay, or should that also be removed?

Let's wait for a second opinion, if other designers agree I'll see what I can do in code!

**Comment by jameskoster** [comment]
Haha, it's only visible for a frame or two. Here's a screengrab:

<img width="319" alt="Screenshot 2023-02-28 at 17 32 08" src="https://user-images.githubusercontent.com/846565/221932123-55e60e5c-0e93-40f0-ac9b-7ba74994ff21.png">

> Basically what you're saying is, the menu items are sliding to the left while they shouldn't be? Is the opacity animation okay, or should that also be removed?

That's correct. I don't think we need the opacity animation either. 

> Let's wait for a second opinion, if other designers agree I'll see what I can do in code!

cc @WordPress/gutenberg-design for input.

**Comment by ghost** [comment]
I'll receive updates, but don't hesitate to ping me once this is agreed upon, then I'll look at making a PR.

**Comment by jasmussen** [comment]
I would agree. Let's get this done. Thank you for taking a stab!

**Comment by ghost** [comment]
Sorry that got a bit messy, made a pull request after branching off of another branch. Thought I'd patch it up, but it was cleaner to create a new PR. https://github.com/WordPress/gutenberg/pull/48630

Should be fixed now. @jameskoster @jasmussen 


https://user-images.githubusercontent.com/118618474/222128883-d8f3b561-4abb-4b74-8e56-6efcef035f16.mov

**Comment by ghost** [comment]
Btw, the PR does still have the animation. I think it's a nice addition that makes it feel a bit more sophisticated. How about you @jameskoster @jasmussen ?

**Comment by jasmussen** [comment]
I responded on the PR, thanks for incredibly fast work. I do agree it feels sophisticated, I don't hate it. I still think it might be slightly better without it, conceptually because the sidebar material gets _covered_ by the fullscreen editor, rather than "receded" in any sense of the word. The idea is, it's still there, just behind the fullscreen editor.

**Comment by jameskoster** [comment]
This doesn't seem to be an issue any more.
