### ISSUE TITLE
"PHP Notice:  Trying to get property 'area' of non-object"  when creating a new TP from the TP block inside a TP

### ISSUE THREAD

**Issue by Chrystll** [WordPress/gutenberg#48596]
### Description

I get the notice below with WordPress 6.2-beta3-55428 and and Twenty Twenty Three (only) when creating a new TP from the TP block inside a TP.
```

[PHP Notice:  Trying to get property 'area' of non-object in /wp-single/wp-includes/rest-api/endpoints/class-wp-rest-templates-controller.php on line 586
[PHP Stack trace:
[PHP   1. {main}() /wp-single/index.php:0
[PHP   2. require() /wp-single/index.php:17
[PHP   3. wp() /wp-single/wp-blog-header.php:16
[PHP   4. WP->main() /wp-single/wp-includes/functions.php:1330
[PHP   5. WP->parse_request() /wp-single/wp-includes/class-wp.php:780
[PHP   6. do_action_ref_array() /wp-single/wp-includes/class-wp.php:399
[PHP   7. WP_Hook->do_action() /wp-single/wp-includes/plugin.php:565
[PHP   8. WP_Hook->apply_filters() /wp-single/wp-includes/class-wp-hook.php:332
[PHP   9. rest_api_loaded() /wp-single/wp-includes/class-wp-hook.php:308
[PHP  10. WP_REST_Server->serve_request() /wp-single/wp-includes/rest-api.php:410
[PHP  11. WP_REST_Server->dispatch() /wp-single/wp-includes/rest-api/class-wp-rest-server.php:442
[PHP  12. WP_REST_Server->respond_to_request() /wp-single/wp-includes/rest-api/class-wp-rest-server.php:1028
[PHP  13. WP_REST_Templates_Controller->create_item() /wp-single/wp-includes/rest-api/class-wp-rest-server.php:1181
[PHP  14. WP_REST_Templates_Controller->prepare_item_for_database() /wp-single/wp-includes/rest-api/endpoints/class-wp-rest-templates-controller.php:400
```

### Step-by-step reproduction instructions

1. go to /wp-admin/site-editor.php?canvas=view&path=%2Fwp_template_part&postType=wp_template_part then edit the Footer TP for example
2. add a TP block > choose "start blank" > then create your TP. This action triggers the PHP notice mentioned above.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Hi there, thanks for the report @Chrystll 

Could you please confirm:

- what version of PHP does this occur with?
- does this also occur with WP 6.1.1, with Gutenberg 15.2.2 active and/or inactive?

**Comment by Chrystll** [comment]
@kathrynwp 
It occurs also with WordPress 6.1.1 with Gutenberg 15.2.2 inactive.
My PHP version is 7.2.3

**Comment by Mamaduka** [comment]
I can confirm this notice. It needs to be fixed in the core, but let's keep the issue open for tracking purposes.

**Comment by t-hamano** [comment]
I was also able to reproduce it. The problem appears to occur in the template editor as well.

https://user-images.githubusercontent.com/54422211/222333165-2c977bfb-6839-4a2c-a882-734ddd3ad4e2.mp4

**Comment by t-hamano** [comment]
Core Ticket: https://core.trac.wordpress.org/ticket/57851
Core PR: https://github.com/WordPress/wordpress-develop/pull/4165

**Comment by t-hamano** [comment]
This issue has been resolved in the core and I will close.

https://core.trac.wordpress.org/changeset/56248
