### ISSUE TITLE
Convert to blocks makes inline images block level

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4859]
## Issue Overview
After opening a page in Gutenberg that was created using the Classic Editor, I then selected the Convert to Blocks option. Some of my content then disappeared.

This is the page upon first opening it up in Gutenberg

![gutenberg-converttoblocks1](https://user-images.githubusercontent.com/2078245/35791769-aeeb0b46-0a9d-11e8-8f95-63a92f6f1bdb.png)

After selecting Convert to Blocks, the second image disappeared and was instead replaced with a copy of the first image.

![gutenberg-converttoblocks2](https://user-images.githubusercontent.com/2078245/35791790-c623390a-0a9d-11e8-9b3e-e02028d9bd28.png)

This issue is blocked on #2043.

## Steps to Reproduce (for bugs)

1. Create new Page using the Classic Editor
2. Insert dummy content and two or more images, inline in the text
3. Publish page
4. Open the Page using Gutenberg
5. Select Convert to Block from the icon next to the block

## Expected Behavior
I expect all my content to be converted to the appropriate blocks (except for inline images)

## Current Behavior
Every image in the page is replaced with the first image

_Firefox Quantum 58.0.1 (64-bit)
Gutenberg 2.1.0
WordPress 4.9.2_

**Comment by jasmussen** [comment]
The small omega symbol seems an issue with inline images, tracked in #2043.

The second issue, subsequent images being replaced with the first, was fixed in https://github.com/WordPress/gutenberg/issues/4749, and will be in 2.1. 

Should we either rename this ticket to be about converting Classic blocks with inline images not working, or close this and add a comment to #2043?

**Comment by maddisondesigns** [comment]
@jasmussen I presume you mean Gutenberg 2.2? I'm already using v2.1.0.

If you want to rename it so it's more about not converting inline images in Classic blocks, that's fine.

**Comment by jasmussen** [comment]
Ack, sorry, yes 2.2. I'll rename the ticket, thanks.

**Comment by brandonpayton** [comment]
I can also confirm this remains an issue.

**Comment by iseulde** [comment]
Could the issue be retested with the latest version? There were some changes in behaviour.

**Comment by youknowriad** [comment]
I confirm this is still happening.
