### ISSUE TITLE
Site Editor: Crashes when loading navigation panel

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#48594]
## What problem does this address?
If you try to load the navigation panel in the site editor directly, it crashes when the navigation contains any custom links:

## Steps to reproduce
1. Create a navigation that contains a custom link
2. Visit wp-admin/site-editor.php?canvas=view&path=%2Fnavigation
3. Wait
4. Notice that the site editor crashes (it takes a few seconds)

## Screen recording

https://user-images.githubusercontent.com/275961/221882273-1dd67781-0b66-4c79-a5f0-357235ce5107.mov

**Comment by capbussat** [comment]
I am sorry, can not reproduce this error with WP 6.1.1 and Gutenberg plugin 15.2.3  ( on Firefox).  I have tried local and external customs links, both absolute and relative. What is your custom link?

**Comment by annezazu** [comment]
I couldn't replicate this with 6.2 beta 4 with or without GB 15.2.3. What version were you using?

**Comment by scruffian** [comment]
It's only possible to replicate in trunk. It will be fixed by https://github.com/WordPress/gutenberg/pull/48219
