### ISSUE TITLE
Consider Notices

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#486]
Current look:

<img width="510" alt="screen shot 2017-04-24 at 10 42 33" src="https://cloud.githubusercontent.com/assets/1204802/25329140/d849a088-28da-11e7-82ed-9561bb0ece87.png">

Let's discuss what's best to do here.

**Comment by youknowriad** [comment]
I've always found that these notifications are too intrusive. Is it the time to start considering notifications in the Admin Bar (similar to Calypso)? This could be a separate project I guess.

**Comment by jasmussen** [comment]
> I've always found that these notifications are too intrusive. Is it the time to start considering notifications in the Admin Bar (similar to Calypso)? This could be a separate project I guess.

Agree completely, but that's probably a separate project. 

Regardless it's something we have to consider. Because when you publish, you'll need a "Published" notice somewhere. I have some ideas, but wanted to open the floor also.

**Comment by inhll** [comment]
There's a good opportunity to place notifications in the Editor Bar...
![admin ui copy 2](https://cloud.githubusercontent.com/assets/406182/25360099/5d8f191c-290d-11e7-9f48-90a81c94a989.png)
The number of waiting notifications could also be shown. I do agree with @youknowriad that system updates would be better shown in another location, but used them here because... placeholder!
![admin ui copy](https://cloud.githubusercontent.com/assets/406182/25360098/5d8ef45a-290d-11e7-9671-7944c405ebcb.png)

**Comment by rileybrook** [comment]
In thinking about the publishing notification, and not other notifications
> when you publish, you'll need a "Published" notice somewhere. I have some ideas, but wanted to open the floor also.

The publish button element itself could indicate the successful action to the user. Changing from blue to green, then back to blue could reduce screen real estate taken up by a notification that their content has been published successfully.
![publish button - preview 4](https://cloud.githubusercontent.com/assets/7691812/25417747/789ca14c-2a03-11e7-8e85-3e26afd7ce47.gif)

**Comment by jasmussen** [comment]
@inhll 

> There's a good opportunity to place notifications in the Editor Bar...

Good exploration, thank you! 

I'm not convinced that putting them in the editor bar is a good idea, mostly from a "why is it different from the rest of the admin" and space concerns. We likely can't remove the visual/HTML switch from there, as that has to have top hierarchy placement. And the "Saved" indicator will likely at times spell out "Draft [Save]" or even "Saving". Maybe that's not too much space extra, but combined with various translation lengths of the toggle buttons, the ability for plugins to add buttons to the top right action button area, and responsive, it just doesn't seem a scalable area.

A question we also have to ask is: how many notifications are we likely going to see i the editor? @rileybrook taps into something interesting here, rethinking what those notices are. "Published" solves half of it, and if we combine this with a permalink affordance somewhere (perhaps next to Saved? perhaps inline in the body itself?) we have arguably the most important notice of the editor addressed.

The update notice —  perhaps we don't need to see that on _every_ screen in the admin. Perhaps the editor can be the first exception?

Or maybe it can be a floating, dismissable notice?

Good thoughts, let's keep thinking.

**Comment by joyously** [comment]
Wouldn't this be the same area used by plugins for notifications?

**Comment by inhll** [comment]
The feedback is on point @jasmussen -- and I like @rileybrook's approach to the problem! Perhaps a mix, where "publish" is no longer a notification but instead integrates with the button as @rileybrook showed, while actual notifications appear similarly to how they do now?

The floating dismissable notice / notification / toast message is definitely a good option and is pervasive because it works well!

**Comment by mapk** [comment]
I like @rileybrook's take on the published notice. My first thought was how would the button change back to 'publish' again, but then I realized that the button could change back when something is edited on the page. So this works well, I think.

**Comment by joyously** [comment]
I was just reading through the Roles and Capabilities page, and it says that the `publish_posts` capability is needed in order to see and use the Publish button. Otherwise they can only save drafts. Does this affect how the notice works?

**Comment by jasmussen** [comment]
> Otherwise they can only save drafts. Does this affect how the notice works?

It does, but a good solution might be to simply change the publish button to a Save Draft button in that situation.

**Comment by jasmussen** [comment]
Closing this in favor of #707. We can always reopen if need be.
