### ISSUE TITLE
Opening an existing (Classic Editor) page in Gutenberg distorts images

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4860]
## Issue Overview
When opening up a page in Gutenberg that has been created with the Classic Editor, the content is added to a Classic Editor block. Large images are shown distorted and do not keep the correct ratio.

As an example, the third image is 1240 x 930px. When imported into a Gutenberg block, the width is squished to fit the width of the block but the height is kept the same, making the image appear at 608 x 930px.

![gutenberg-converttoblocks3](https://user-images.githubusercontent.com/2078245/35792339-b4ac0bea-0aa0-11e8-9dbe-9785bcba6692.png)

This is the image that was distorted

![calmdown](https://user-images.githubusercontent.com/2078245/35792522-ae47ef5c-0aa1-11e8-9e9c-d733eaf607e3.jpg)

`.gutenberg__editor img` needs to include `height: auto;`

```
.gutenberg__editor img {
    max-width: 100%;
    height: auto;
}
```

## Steps to Reproduce (for bugs)
1. Create new page using the Classic Editor
2. Insert dummy content including a large image (mine was 1240 x 930)
3. Publish page
4. Open page in Gutenberg
5.  View distorted image

## Expected Behavior
Images should display in the editor at the correct ratio. If the width is decreased to fit the width of the block, the height should decrease as well.

## Current Behavior
Wide images are distorted.

_Firefox Quantum 58.0.1 (64-bit)
Gutenberg 2.1.0
WordPress 4.9.2_

**Comment by jasmussen** [comment]
Closing as fixed by https://github.com/WordPress/gutenberg/pull/4752
