### ISSUE TITLE
Iterations to the new menu item dialog

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#48612]
## What problem does this address?
A few issues with the current dialog:
- We use different dialogs depending on if you are in canvas or in inspector/browse mode sidebar. 
- When in canvas we create a link before deciding what that link is. This means a user has to go through the process of removing that link if they decide to cancel the action.
- We don't always show "page link" as a block option in the dialog in the inspector
- The "apply" button is rarely (never?) needed as the link is added as soon as you click an option

## What is your proposed solution?

https://user-images.githubusercontent.com/1072756/222632101-95c49dbd-b631-49d1-8a1e-763159d15dd5.mp4

- [ ] One dialog regardless of where you are adding a link
- [ ] Show preview of link after clicking option so that user can change settings such as "open in new tab" before hitting "add" (replacing "apply"). 
- [ ] Clicking edit on the link preview pill should revert back to the original state. This should be almost identical to editing a link.
- [ ] Don't show "add" button before selecting an option
- [ ] Include an option in the list of items to add "Insert a block instead" that toggles to the generic block inserter dialog
- [ ] Always show option to draft new page at the bottom
- [ ] In this generic block inserter dialog if you select "page link" it reverts back to original dialog
- [ ] Add an "All pages" option that inserts a pages list. In future clicking this will go to the same "preview" state as adding a page link where you can select the parent page.
- [ ] Adding a custom link takes you to a state where you can add text
- [ ] Editing custom links in canvas (and browse mode sidebar) triggers the preview state where you can edit or detach

**Comment by jameskoster** [comment]
In terms of 6.2, there are two big issues that this design would solve:

#### 1. Emphasise Page Links more when creating menu items in the Navigation panel
<img width="418" alt="Screenshot 2023-03-02 at 15 20 10" src="https://user-images.githubusercontent.com/846565/222470780-bf691569-0c6a-417c-93a9-61ff96ee741f.png">

It's a bit unexpected that Page Link doesn't appear in this popover, and that things like Page Break, Spacer, etc are given more prominence. 

#### 2. Page Links (and custom links – https://github.com/WordPress/gutenberg/issues/48593) cannot be edited in the Navigation panel

https://user-images.githubusercontent.com/846565/222472649-7f8637c3-4401-4b03-8ac6-6ba8939acac7.mp4

Page links can be added to the menu, but not edited.

**Comment by jameskoster** [comment]
@SaxonF one thing missing here is how to edit Custom links.

**Comment by SaxonF** [comment]
Updated prototype to show custom links

**Comment by Mamaduka** [comment]
I think a reusable combobox like this would be a great addition to the components package. Maybe we can use [Ariakit](https://ariakit.org/components/combobox) as a base. Cc @ciampo @mirka

@jameskoster, besides #1 from your list (the #2 is in progress), what other enhancements do we want to ship in 6.2? It would be hard to introduce proposed UI changes like these, this late in the release cycle.

**Comment by jameskoster** [comment]
Hey @Mamaduka, yes it's very late ☹️

The other items that seem important:

* https://github.com/WordPress/gutenberg/pull/48689
* https://github.com/WordPress/gutenberg/pull/47748
* https://github.com/WordPress/gutenberg/issues/48675
* https://github.com/WordPress/gutenberg/issues/48591 (this one is more of a nice-to-have)

It would be nice to do something when the menu includes only a Page List block too. The parent feels superfluous here:

<img width="359" alt="Screenshot 2023-03-03 at 09 33 42" src="https://user-images.githubusercontent.com/846565/222684898-2845a45c-85ad-4642-af9d-e37eae029898.png">

I'll make an issue for that one.

**Comment by getdave** [comment]
Whilst I appreciate the UX concerns, I don't think we can be making these changes to the Link UI at this stage in the WP 6.2 release cycle. 

I feel that we should

- resolve only [the most _critical_ issues now](https://github.com/WordPress/gutenberg/issues/48612#issuecomment-1453236692) for the Browser Mode Nav view
- work on the underlying component in https://github.com/WordPress/gutenberg/issues/47310 as part of the **6.3** cycle

**Comment by jameskoster** [comment]
Obviously it depends on what we deem 'critical', but as a tool for managing the primary menu it is very strange to see these blocks as suggestions when clicking the [+]:

<img width="435" alt="Screenshot 2023-03-03 at 10 32 52" src="https://user-images.githubusercontent.com/846565/222698081-75a2a4b8-65e9-4e7d-ac01-416ca0bc4bb1.png">

Most of the time you'll want to add an existing page to the menu, or draft a new page and add that. Both of those flows are buried right now.

**Comment by getdave** [comment]
That dialog is not Link Control but rather the `<Inserter>` component so that's good 👍  

We'll need to update the logic that determines which blocks to show. This is based on a frecency model if I remember correctly...

**Comment by ciampo** [comment]
> I think a reusable combobox like this would be a great addition to the components package. Maybe we can use [Ariakit](https://ariakit.org/components/combobox) as a base

Thank you for the ping! 

The `@wordpress/components` package already has a few components that may be of help here: [`ComboboxControl`](https://wordpress.github.io/gutenberg/?path=/story/components-comboboxcontrol--default) and [`CustomSelectControl`](https://wordpress.github.io/gutenberg/?path=/story/components-customselectcontrol--default).

I also appreciate that those components may not be featuring the most up-to-date editor design language. We do plan to work on them and (as suggested above) actually rewrite them using `ariakit`. That will also be the perfect occasion for updating the components' look&feel.

Although, looking at the video at the top of this issue, what is being proposed here doesn't look like a simple combobox, since clicking on an item in the dropdown doesn't simply select that item, but can trigger new UI to be displayed. Given how tailored to its specific use-case the proposed piece of UI looks like, my suggestion is to build such a component directly in the site editor package.

Finally, I also echo @getdave 's thoughts about making such changes so late during the WP 6.2 release cycle.

**Comment by SaxonF** [comment]
> Although, looking at the video at the top of this issue, what is being proposed here doesn't look like a simple combobox, since clicking on an item in the dropdown doesn't simply select that item, but can trigger new UI to be displayed.

@ciampo I think this is just a combination of ComboBox with custom render item + static render items below (new draft/insert a block) depending on if search is empty or not. It's just a modification of what's already in prod.

**Comment by getdave** [comment]
I would also like to connect this to https://github.com/WordPress/gutenberg/issues/47310. It's really important we don't bolt on lots of changes without looking at the lower-level component as a whole.

**Comment by getdave** [comment]
@SaxonF I think we should close this one out in favour of having a single set of revised designs posted in https://github.com/WordPress/gutenberg/issues/49091. It's getting too confusing. I'm going to go ahead but please feel free to reopen if you feel that's warranted.
