### ISSUE TITLE
core/columns not supporting templateLock

### ISSUE THREAD

**Issue by sque89** [WordPress/gutenberg#48620]
### Description

I implemented a custom block which acts as a wrapper around the core/columns block to provide a simpler editing experience for our content editors and to ease content handling technically.

To make it as easy for the editor as possible to maintain the block i want to lock it in a certain way which only allows the user to duplicate and remove columns but not more. Espacially not adding more content into the custom block.

I could achieve that by using a combination of templateLock insert on the custom block and resetting the template lock on the inner blocks. However unfortunately this does not work because the columns block is ignoring the templateLock attribute.

### Step-by-step reproduction instructions

1. create group block
2. add inner columns block
3. templateLock: 'insert' the group block
4. templateLock: false the columns block
5. try to duplicate a column inside the columns block

current behaviour: column block cannot be duplicated

expected behaviour: column block can be duplicated

### Screenshots, screen recording, code snippet

```return (
    <div {...useBlockProps()}>
      <InnerBlocks
        template={[
          [
            'core/columns', {
              align: 'full',
              templateLock: false
            }, Array(4).fill(columnTemplate)
          ]
        ]}
        templateLock='insert'
      />
    </div>
  );```
  
![222098705-31880902-7aa9-43f6-a744-bf003a3bb4c3](https://user-images.githubusercontent.com/5357139/222100154-f890849a-71fe-4bd1-996a-5098cce6c551.png)

### Environment info

- GB version: 15.2.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
@sque89 
Thank you for the report.

I also agree that the `core/columns` block supports `templateLock`.

In this connection, I see another potential problem.

If the `core/columns` block inherits `templateLock=all` from the parent block, it should not be able to insert child columns, but the number of columns can be changed from the sidebar. And if you add more columns from the sidebar, you cannot insert any blocks.

Ideally, I think the sidebar UI should also be hidden in this case.

cc @jorgefilipecosta

![column](https://user-images.githubusercontent.com/54422211/222325841-e784f0b3-60b9-4f1d-8cc1-75396b15880b.png)

**Comment by t-hamano** [comment]
> If the core/columns block inherits templateLock=all from the parent block, it should not be able to insert child columns, but the number of columns can be changed from the sidebar. And if you add more columns from the sidebar, you cannot insert any blocks.
> 
> Ideally, I think the sidebar UI should also be hidden in this case.

This issue will be fixed in #48691.

**Comment by sque89** [comment]
@t-hamano thanks for providing the PR. I had a look at it, but it seems to me that my original problem (that i cannot reset templateLock on core/columns level) will not be solved. Am i wrong?

**Comment by t-hamano** [comment]
@sque89 
> I had a look at it, but it seems to me that my original problem (that i cannot reset templateLock on core/columns level) will not be solved.

Sorry for the misunderstanding. #48691 does not fix the issue you originally raised in this issue. I will attempt to fix your original issue as a separate PR.

**Comment by sque89** [comment]
Thanks a lot!
