### ISSUE TITLE
Transforming paragraph to list item → Inline code then falsely shown as normal text

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#48627]
### Reproduction

1. You are in Edit Mode of the Code Block Editor. (in my case creating a new thread in the WP.org support forums)
2. Have one or multiple paragraph(s) with some inline code blocks.
3. Transform the paragraphs into a list, where each paragraph then will be a list item.
  - ✅ The transformation works.
  - ❌ But the inline code is not rendered as normal text. Only when you click or highlight it, it is shown as inline code (= grey background-color).
    - The faulty rendering in the edit mode itself is enough of a usability concern which should be solved.
    - I did not try how output (read mode) of the list items would be after submitting.
    - Instead I transformed the list back into paragraphs, then the inline code blocks were correctly formatted again, and published that way.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/737143/222123982-0ba33271-4a51-410d-ab34-88963ba612aa.mp4

### Environment info

- WP.org support forum (uses Gutenberg since ca. fall 2022)
- Safari  16.3.1 
- macOS 11.7.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
@porg 
Thank you for the report.

From the screenshot you provided, I can see that the block editor is from the support forum. This editor is realized by a plugin called [Blocks Everywhere](https://github.com/Automattic/blocks-everywhere), and [the code style is also applied by that plugin](https://github.com/Automattic/blocks-everywhere/blob/0550f066a96d6f88a20a9ef9c842ce02b6a55b45/src/styles/theme-compat.scss#L194).

![blocks-everywhere](https://user-images.githubusercontent.com/54422211/222319151-437f02d5-ae93-4775-88ee-99c7498198c0.png)

I'm not sure if the code styles not being applied outside of paragraphs is a bug or not, but I have submitted an issue on the GitHub repository for the plugin.
https://github.com/Automattic/blocks-everywhere/issues/150

I would like to close this issue as I don't believe this is a gutenberg issue, but please comment if I have missed something.

**Comment by porg** [comment]
Thanks for your issue analysis and CSS code inspection and for forwarding this into the correct issue tracker!
