### ISSUE TITLE
BUG: Unexpected behavior with new core block tabs

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#48655]
### Description

I realized that the new core block tabs (introduced in WP 6.2) are attached to each of my ACF blocks (https://github.com/AdvancedCustomFields/acf/issues/794). I assume this will also affect custom blocks.

The first tab contains the ACF fields.

The second tab contains core text decoration settings.

However, there should be no text decoration settings. I didn't enable this in the `block.json` file and setting typograpfy to false in block.json isn't a solution to fix that either.

The issue is that tabs are not supposed to be shown here. Likewise, the bug here is that the second tab contains text decoration settings that are not enabled.

### Step-by-step reproduction instructions

1. Add a block

2. Block contains two tabs in the sidebar

3. The first tab contains the ACF fields 

<img width="372" alt="222084998-56298c80-70f7-428d-a5b2-1a75f1f6f94a" src="https://user-images.githubusercontent.com/31563167/222237495-c5de7250-6af1-416f-a549-db4e4cae5256.png">

4. The second tab contains core text decoration settings.

<img width="223" alt="222085259-bf1092ca-21e9-4f16-8f90-7d365cd1fe72" src="https://user-images.githubusercontent.com/31563167/222237748-d27c7736-4c2d-48e9-95d1-3b3fda5edfba.png">

### Environment info

WordPress 6.2 beta4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hi @CreativeDive. The bug with the extra typography option will be fixed in Gutenberg 15.3. Can you try disabling the plugin and test with just 6.2 Beta 4? I am able to replicate your issue with 6.2 Beta 4 **and** Gutenberg 15.2, but when Gutenberg is disabled, the bug goes away.

**Comment by CreativeDive** [comment]
@ndiego thanks for the hint. That's it. Nice to see it's already fixed. I can confirm it works with deactivated Gutenberg plugin.

**Comment by ndiego** [comment]
Awesome, thanks!
