### ISSUE TITLE
Occur "Maximum update depth exceeded.” in Navigation Screen.

### ISSUE THREAD

**Issue by torounit** [WordPress/gutenberg#48668]
### Description

Adding a Custom Link block to the navigation causes "Maximum update depth exceeded.”

This problem does not occur in 15.2.4, it occurs with trunk ( 4945d3f42254e36a87a09aa4f99cfbdca916f962 ).

```
Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.js?ver=18:27302:13)
    at scheduleUpdateOnFiber (react-dom.js?ver=18:25485:5)
    at dispatchSetState (react-dom.js?ver=18:17537:9)
    at assignRef (index.js:20:3)
    at index.js:128:4
    at safelyDetachRef (react-dom.js?ver=18:22918:24)
    at commitDeletionEffectsOnFiber (react-dom.js?ver=18:24013:13)
    at recursivelyTraverseDeletionEffects (react-dom.js?ver=18:23999:7)
    at commitDeletionEffectsOnFiber (react-dom.js?ver=18:24128:11)
    at recursivelyTraverseDeletionEffects (react-dom.js?ver=18:23999:7)
```

### Step-by-step reproduction instructions

1. Go to Site Editor.
2. Select Navigation Screen. ( http://localhost:8888/wp-admin/site-editor.php?canvas=view&path=%2Fnavigation )
3. Insert "Custom Link" Block to Navigation.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1908815/222364797-2cf131d4-c42e-459b-a05d-42c6965dc2c4.mov

### Environment info

- Gutenberg: trunk ( 4945d3f42254e36a87a09aa4f99cfbdca916f962 )

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I can confirm the bug. This only happens when inserting the "Custom Link" block.

**Comment by Mamaduka** [comment]
Probably related to #48675.

cc @getdave, @scruffian

**Comment by Mamaduka** [comment]
I believe this is the side effect that triggers the update loop.

https://github.com/WordPress/gutenberg/blob/a85892e50ab26a619c498764d1d4c4fbfab935e6/packages/block-library/src/navigation-link/edit.js#L228-L235

**Comment by getdave** [comment]
That bug is already on the radar and will be fixed by 

https://github.com/WordPress/gutenberg/pull/48219

Thanks for reporting.

**Comment by ntsekouras** [comment]
This PR seems to have caused this: https://github.com/WordPress/gutenberg/pull/47853/ and it's not included in `6.2`.

**Comment by Mamaduka** [comment]
@getdave, should we close some of the issues as duplicates?

**Comment by getdave** [comment]
@Mamaduka I've marked this Issue as being closed by https://github.com/WordPress/gutenberg/pull/48219. So it will be handled.
