### ISSUE TITLE
Modal at the navigation block is not completely visible

### ISSUE THREAD

**Issue by hagege** [WordPress/gutenberg#48666]
### Description

Modal at the navigation block is not completely visible when I want to add a menu item on the right side of the bar. However, the problem only occurs when I have relatively many menu items on the right and the entire screen area is used.
![issue_navigation_block](https://user-images.githubusercontent.com/27292550/222352774-29c260bd-a84e-4262-b072-a15481fc2277.jpg)

### Step-by-step reproduction instructions

1. Appearance > Editor
2. Template Parts
3. Header
4. Edit
5. Choose Navigation Block
6. Right Bar: "+" (Add Block)

### Environment info

WordPress Current version: 6.2-beta4-55454, Gutenberg Version 15.2.4,

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ghost** [comment]
Possible duplicate: https://github.com/WordPress/gutenberg/issues/48059

**Comment by t-hamano** [comment]
@hagege 
Thank you for the report.

From what I have tested, the problem appears to be on the Gutenberg plugin. On WordPress 6.2 Beta4 with the plugin stopped, this problem did not occur.

https://user-images.githubusercontent.com/54422211/222963944-27d93bf3-1af6-45a8-883a-d5f5e6d00889.mp4

**Comment by hagege** [comment]
@t-hamano 
thanks for answer. 
Indeed, I did not test that. Then the issue is not relevant for WordPress 6.2.

**Comment by jordesign** [comment]
I'm seeing this as resolved now when testing WP 6.2.2 - modal appears correctly (whether Gutenberg is active or not).

<img width="756" alt="Screenshot 2023-07-27 at 4 54 05 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/037aadd6-e1a9-4d75-bb10-62bbb259761b">
