### ISSUE TITLE
Add link to post comments in Status panel

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#4867]
In the classic editor, comments on a post show up in a box below the editor. This is a useful way to moderate comments on an individual post. We have no UI for this in Gutenberg, but there's another interface for moderating comments on a single post, in the posts section. 

Specifially if you load up the comments page, and click the comments icon next to a post, you see a list of comments just for that post, with a URL something like `/wp-admin/edit-comments.php?p=9036&comment_status=approved`. We should leverage that in Gutenberg.

Here's a suggested mockup:

<img width="502" alt="screen shot 2018-02-05 at 11 26 23" src="https://user-images.githubusercontent.com/1204802/35800092-33b589e0-0a68-11e8-8311-f0ae7983d2a6.png">

**Comment by jasmussen** [comment]
CC: @karmatosed — I've been doing a bunch of spring cleaning with Gutenberg on my blog, and often found the need to look at comments for an old post. This UI would be easy to do, and would fix it for me.

**Comment by karmatosed** [comment]
This is a great little improvement that could be done. One point, on clicking the comments, how do I get back to the post? Does it save on click to ensure that I don't lose content?

**Comment by jasmussen** [comment]
You'd just press the browser back button to go back, but good point about the auto save, we'd probably want to fire a save indeed.

**Comment by youknowriad** [comment]
Do we really want to trigger a save, I'm thinking the "dirty popup" would show up if there are unsaved changes which is fine enough IMO. 

Trigger save would add a bit of complexity, that I'd prefer avoiding if we can.

**Comment by jasmussen** [comment]
V1 could be without the save, then we can see if we need it?

**Comment by youknowriad** [comment]
@jasmussen yes we can, but It might be a good idea to just keep it without it as it's a more consistent behavior. It's not the only place in the UI where we link to external pages: Revisions, published post link, all WPAdmin menu links :), I believe we have some help links as well.

**Comment by bobbingwide** [comment]
Can anyone explain why there isn’t a meta box for comments. What design decision was made? This needs to be documented for users who are unable to find the box they expect to see.

**Comment by karmatosed** [comment]
This is a good little addition so let's close out design feedback on this.

@bobbingwide comments still function the same with discussion on/off switches and the link, it doesn't have to be a separate section and still has hooks.

**Comment by gziolo** [comment]
Any plugin can add such information with [PluginPostStatusInfo](https://github.com/WordPress/gutenberg/tree/master/packages/edit-post#PluginPostStatusInfo) component through `registerPlugin` API. I think it's okay to close this issue. @jasmussen thanks for sharing your proposal.

**Comment by lkraav** [comment]
> Can anyone explain why there isn’t a meta box for comments. What design decision was made? This needs to be documented for users who are unable to find the box they expect to see.

This question was never answered for some reason. I'm looking at today's Gutenberg 6.5.0 post edit screen, and I don't see a comments meta box available either. What am I missing?
