### ISSUE TITLE
Site Editor Navigation panel: Site Logo, Search, Spacer, Social Icon, Page List experience feels a bit broken.

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48675]
If there's a Site Logo block in the main navigation, you're not able to edit it in the Navigation panel:

https://user-images.githubusercontent.com/846565/222401592-5a08bdd8-9699-437e-90a1-077eee6a9c7d.mp4

But you are able to select it, which does nothing. This experience feels quite broken.

For 6.2 let's explore more appropriate interaction design, IE remove the select-ability of these items. In the future it'd be nice if there was simple edit UIs for these blocks within this panel.

**Comment by jameskoster** [comment]
Noting that the same issue(s) exists for the Search, Spacer, Social Icons blocks too.

**Comment by jameskoster** [comment]
I think removing all hover interactions (except the grab cursor and exposing the ellipsis button), and making these blocks un-selectable would help a lot as a short term measure:

https://user-images.githubusercontent.com/846565/222414357-d8467425-7a35-45fe-9861-ca0d2102791c.mp4

**Comment by jameskoster** [comment]
Related: Selecting the Page List when the children are revealed adds a background color that looks broken:

<img width="340" alt="Screenshot 2023-03-02 at 12 44 39" src="https://user-images.githubusercontent.com/846565/222432419-ac465d1d-59c3-4c24-bd0a-27dbf8f57eda.png">

**Comment by jameskoster** [comment]
Noting that if we can't get custom link editing (https://github.com/WordPress/gutenberg/issues/48593) in time for 6.2, then it would probably be ok for them to behave like the other blocks here. Hopefully it doesn't come to that, though :)

**Comment by richtabor** [comment]
We should almost remove the non-browsable blocks from this Site Editor > Navigation view...

**Comment by jameskoster** [comment]
Do you mean remove the affordances by which you can add those blocks to Navigation menus?

Or just hide them in this view?

The problem with the latter is that you wouldn't be able to re-order, which seems like a shame?

**Comment by richtabor** [comment]
> Or just hide them in this view?

We're mixing browse mode w/ block editing. 

> The problem with the latter is that you wouldn't be able to re-order, which seems like a shame?

Are any block themes using blocks in navigation out of the box? All the core header patterns don't have logo/social/search in the actual navigation block (but rather within a row, next to the Navigation block). 

I'm curious how meaningful it is to have access to those other blocks in the navigation period — why I lean towards hiding them in the Site Editor > Navigation view.

**Comment by SaxonF** [comment]
This is a tough one...

> We're mixing browse mode w/ block editing.

I agree and in general have concerns about how we communicate what the navigation section's main purpose is compared to the navigation block itself. If we were to hide blocks I would much prefer we present the section as "Pages", but still allow re-ordering of pages (setting `order` attribute), which in turn would affect all menus that include a pages list block. This would cover most simple sites and leave advanced menu editing to the editor. 

In saying that though, we're kind of at a point where we need to run with positioning this as menu management, and if we hide blocks in the list we'd also need to hide them from the inserter, which then creates inconsistencies with the editor etc. I think @jameskoster proposal here is a good improvement in the short term.

**Comment by jameskoster** [comment]
Imo this speaks to an underlying issue around whether the Navigation block should be able to entertain children like Search, Social Icons, etc.

Still, as long as they can, I'm struggling to come up with a compelling reason why you shouldn't be able to at least re-order them in this view. 

Like Saxon said, if we hide them in the list then we also need to hide them in the Inserter, and so the list of overrides made to the off-canvas menu editor gets ever longer, to the point where it's almost entirely divergent.

**Comment by jorgefilipecosta** [comment]
Could we just disable the selection from these blocks, so they are essentially disabled?

**Comment by jameskoster** [comment]
@jorgefilipecosta if that wouldn't prohibit re-ordering them then yes, that would be ideal.

**Comment by jameskoster** [comment]
There's refinement still to do, but I think https://github.com/WordPress/gutenberg/pull/48933 is enough to close this.
