### ISSUE TITLE
Site Editor Navigation Panel: Loading state feels a bit fragile

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48682]
https://user-images.githubusercontent.com/846565/222418948-55924a17-0438-4eab-92e7-a5cea5387803.mp4

There are two issues to fix:

1. The loading indicator is visually very bright, could we tone this down a bit so it sits nicer against the dark material?
2. Some menu items appear before others resulting in a staggered load. It's not so bad with small menus but with larger ones it feels quite clunky.

**Comment by jasmussen** [comment]
Good issue. Yes, we need to consolidate on using spinners for loading states. Skeleton indicators can be separately explored for placeholders, but we've tried them for both social links and navigaiton in the past, and it hasn't worked out, so let's avoid those for loading states.

**Comment by scruffian** [comment]
The loading states have changed, I think we can close this.
