### ISSUE TITLE
Move 404 to bottom of templates list

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48697]
https://github.com/WordPress/gutenberg/pull/48473 updated template lists to sort by slug/name. This is generally an improvement with the exception of one small detail: the 404 template now appears at the top of the list:

<img width="358" alt="Screenshot 2023-03-02 at 15 56 52" src="https://user-images.githubusercontent.com/846565/222481571-306be749-8d9c-48db-8716-19f2869610c4.png">

While technically correct, it's a bit strange to see this particular template at the top of the list given its relative importance. Until we get to more comprehensive grouping (https://github.com/WordPress/gutenberg/issues/48651) it might be good to force templates with numerical names to appear at the bottom of the list.

**Comment by glendaviesnz** [comment]
This adds additional complexity to the code just for the one off example of the 404, eg. 

```js
sortedTemplates.sort( ( a, b ) => a.slug.localeCompare( b.slug ) );
```

Has to become something like:

```js
	const sortedTemplatesAlpha = templates
		? [ ...templates.filter( ( t ) => ! /^\d/.test( t.title.rendered ) ) ]
		: [];
	const sortedTemplatesNumber = templates
		? [ ...templates.filter( ( t ) => /^\d/.test( t.title.rendered ) ) ]
		: [];
	sortedTemplatesAlpha.sort( ( a, b ) =>
		a.title.rendered.localeCompare( b.title.rendered )
	);
	sortedTemplatesNumber.sort( ( a, b ) =>
		a.title.rendered.localeCompare( b.title.rendered )
	);
	const sortedTemplates = [
		...sortedTemplatesAlpha,
		...sortedTemplatesNumber,
	];
```

or

```js
function sortTemplates( a, b ) {
	const aStartsWithNumber = /^\d/.test( a.title.rendered );
	const bStartsWithNumber = /^\d/.test( b.title.rendered );
	if ( aStartsWithNumber && bStartsWithNumber ) {
		return a.title.rendered.localeCompare( b.title.rendered );
	}
	if ( aStartsWithNumber ) {
		return 1;
	}
	if ( bStartsWithNumber ) {
		return -1;
	}
	return a.title.rendered.localeCompare( b.title.rendered );
}
```

There may be a simpler approach that I am overlooking, but given that some users may have templates with numbers in the title that they prefer sorted to the top I don't think it is worth implementing this just for the sake of pushing the 404 template to the bottom of the list.

**Comment by glendaviesnz** [comment]
@youknowriad the use of `slug` [here](https://github.com/WordPress/gutenberg/pull/48473/files#diff-8225d1b39bd11da6372f6dde7738eea373cb83fb3f6e94ecbee54a8a2b6b7b0aR70) causes some strange sorting when the slug ends up different to the title, eg.

<img width="410" alt="Screenshot 2023-05-04 at 2 32 33 PM" src="https://user-images.githubusercontent.com/3629020/236098308-3e1f3c25-1797-4809-bb84-719cf7bd23f2.png">

Can you see any issues with switching the sort from `slug` to `title.rendered` ?

**Comment by youknowriad** [comment]
@glendaviesnz no, this should be fine.

**Comment by glendaviesnz** [comment]
I have added a [PR to match the sort order to the visible template names](https://github.com/WordPress/gutenberg/pull/50353) and I suggest we close this issue as I don't think it is worth adding the extra sorting complexity just to make 404 go to the bottom.

**Comment by hanneslsm** [comment]
Adding for visibility the discussion on renaming the template titles. This could make changing the code obsolete: https://github.com/WordPress/gutenberg/issues/47551

**Comment by glendaviesnz** [comment]
Going to close this one. Renaming the templates as suggested in https://github.com/WordPress/gutenberg/issues/47551 would be a better approach than adding a more complex sort just for this one edge case.
