### ISSUE TITLE
Site Editor Navigation panel: When the 'main' navigation menu changes, it's not always clear why, and can be confusing 

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48690]
The Navigation panel is supposed to detail the website's main navigation menu. The problem is that the menu that appears in this panel can sometimes change, and it's not always obvious why it does so which can lead to confusion.

[Here's](https://github.com/WordPress/gutenberg/blob/f580ad6d34e6e45b847ccad6127b20316155b0f4/packages/edit-site/src/components/navigation-inspector/index.js#L75) the current logic for determining the 'main' menu.

> the navigation referenced by the first nav block in the template

This part seems to be causing issues. Example:

I want to add some social icons at the very top of my site. I create a new menu for this in my Header template part:

<img width="967" alt="Screenshot 2023-03-02 at 13 01 11" src="https://user-images.githubusercontent.com/846565/222435846-e1940ace-4c79-4ca9-93c0-b59679c562a7.png">

After saving, I now find that menu represented in the Navigation panel:

<img width="605" alt="Screenshot 2023-03-02 at 13 01 48" src="https://user-images.githubusercontent.com/846565/222435993-8ceef521-e074-40c4-8687-7332c4b05a25.png">

This is unexpected, and it seems nonsensical for this menu to be given such prominence. 

> the navigation manually selected by the user in the navigation block inspector
> when a navigation block gets inspected within the canvas

This part is also a bit problematic. I don't think that merely interacting with a Navigation menu should subsequently mark it as the 'main' one. 

---

What's the solution? It would likely make the Navigation panel feel more robust if we simply said that the first menu created is the 'main' one. This would replace the default 'Page list' menu that exists before no menus have been created.

As a bonus point it would be nice to mark this menu somehow in popovers like this one:

<img width="270" alt="Screenshot 2023-03-02 at 13 13 14" src="https://user-images.githubusercontent.com/846565/222438479-53c139d2-02f4-4446-9090-dd3e797870f1.png">

It may be as simple as adding a (main) suffix.

<img width="317" alt="Screenshot 2023-03-02 at 13 16 19" src="https://user-images.githubusercontent.com/846565/222439164-9cf41102-0265-4f02-931c-2e9baa199a76.png">

**Comment by bobbingwide** [comment]
> What's the solution? It would likely make the Navigation panel feel more robust if we simply said that the first menu created is the 'main' one. This would replace the default 'Page list' menu that exists before no menus have been created.

The fix in #48689 says the opposite. 

> Always pick the latest published manu (sic). 

See also #48897 & #48891

**Comment by annezazu** [comment]
In the flurry of work done around the Navigation section for 6.2 and the later removal, this issue was previously closed. However, it was closed thanks to a PR focused on updating the logic of what's shown rather than thinking about the entire UX, which remains confusing without an option to change what appears built into the sidebar. As a result, I'm going to re-open this as I believe this remains an area to iterate on, even if it's just connecting dots in the UI like James mentions above.

**Comment by scruffian** [comment]
With all the work that's been done on the navigation in Site View, we can now close this.
