### ISSUE TITLE
New Block: Details/Summary HTML Tag

### ISSUE THREAD

**Issue by bhubbard** [WordPress/gutenberg#48699]
The details/summary tag is a bit rare, but generates a common UI that users want, which is a dropdown displaying text. 

https://www.w3schools.com/tags/tag_summary.asp

**Comment by hanneslsm** [comment]
This is in progress: https://github.com/WordPress/gutenberg/pull/45055

**Comment by bhubbard** [comment]
Thanks, @hanneslsm closing as duplicate.
