### ISSUE TITLE
"Additional CSS Class" moves places from placeholder to image block

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#4869]
This is a subtle one. The "Additional CSS Class" input field moves from being at the top of the image block inspector, to being at the bottom, when you create it from a placeholder.

Steps to reproduce:

- Open the sidebar, switch to the Block inspector
- Insert an image placeholder block, note that the "Additional CSS class" input field is at the top
- Insert an image from the media library, verify that the CSS class field is still at the top
- Deselect the image block, then select again, and note that the CSS class field is now at the bottom

Expected result: CSS class field should always be at the end of the list of advanced block settings. 

GIF:

![image css class](https://user-images.githubusercontent.com/1204802/35801542-0a466692-0a6d-11e8-853d-482dd6a7e4ba.gif)

Issue discovered by @bobbingwide

**Comment by bobbingwide** [comment]
I was a bit slow raising this. My screen capturing capability needs to be improved and I got distracted when I resized the window and the image block appeared over the top of the settings.

**Comment by noisysocks** [comment]
This is fixed now that _Additional CSS Class_ is in the _Advanced_ panel at the bottom.

<img width="285" alt="screen shot 2018-04-26 at 16 35 44" src="https://user-images.githubusercontent.com/612155/39289535-efca030e-496f-11e8-89fd-fd4b48d208ea.png">
