### ISSUE TITLE
PanelColorSettings is rendered 50% on style tab

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#48707]
### Description

I have this code to try new styles tab.

The color settings is 50% width of panel.

```
<InspectorControls group="color">
    <PanelColorSettings
	    __experimentalIsRenderedInSidebar
	    initialOpen={ true }
	    panelId={ clientId }
	    colorSettings={ [
		    {
			    value: backgroundColor,
			    onChange: ( color ) =>
				    setAttributes( { backgroundColor: color } ),
			    label: __( 'Background Color', 'popper' ),
		    },
		    {
			    value: overlayColor,
			    onChange: ( color ) =>
				    setAttributes( { overlayColor: color } ),
			    label: __( 'Overlay Color', 'popper' ),
			    enableAlpha: true,
		    },
	    ] }
    />
</InspectorControls>
```

### Step-by-step reproduction instructions

1. create a simple block
2. Add the code above
3. Check style tab

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
It'd be great if you could add a screenshot.

**Comment by Tropicalista** [comment]
![Edit-Popup-‹-Test-—-WordPress](https://user-images.githubusercontent.com/1663035/222771535-4169f510-512d-4138-ba35-92a66ecc119c.png)

Here's a screenshot.

**Comment by t-hamano** [comment]
I have tried converting your code to native JavaScript and running it in the browser console, but could not reproduce it. Is it possible that the CSS in the theme or plugin could be affecting it?

<details>
<summary>Code</summary>

```javascript
var el = wp.element.createElement;

var withInspectorControls = wp.compose.createHigherOrderComponent( function (
	BlockEdit
) {
	return function ( props ) {
		return el(
			wp.element.Fragment,
			{},
			el( BlockEdit, props ),
			el(
				wp.blockEditor.InspectorControls,
				{},
				el(
					wp.blockEditor.PanelColorSettings,
					{
						__experimentalIsRenderedInSidebar: true,
						iniialOpen: true,
						panelId: props.clientId,
						colorSettings: [
							{
								value: '#ff0000',
								onChange: () => {},
								label: 'border color',
							},
							{
								value: '#00ff00',
								onChange: () => {},
								label: 'background color',
							},
						]
					},
				)
			)
		);
	};
},
'withInspectorControls' );

wp.hooks.addFilter(
	'editor.BlockEdit',
	'my-plugin/with-inspector-controls',
	withInspectorControls
);
```
</details>

![screenshot](https://user-images.githubusercontent.com/54422211/222942270-62a67c99-9e72-4959-80df-fe0cce867b60.png)

**Comment by Tropicalista** [comment]
You are not using new `group="color"`. Try adding it and see what happens.

**Comment by t-hamano** [comment]
> You are not using new group="color". Try adding it and see what happens.

Yes, I added the group property and was able to reproduce it.

As far as I can tell, the `PanelColorSettings` component itself is a `ToolsPanel` component, so I think it should not be expected to be put into an existing `ToolsPanel` using the `group` property. I think it would be better to use the `ColorGradientSettingsDropdown` component instead, as [the cover block has done](https://github.com/WordPress/gutenberg/blob/e72bc18ce7d62bed1d9514e73f5c17631bf7ed07/packages/block-library/src/cover/edit/inspector-controls.js#L254-L274).

**Comment by Tropicalista** [comment]
You are correct. Using ColorGradientSettingsDropdown  solved my problem.

Thanks
