### ISSUE TITLE
Add login block to navigation

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#48704]
## What problem does this address?
In most menu is usual to add login/logout link.

## What is your proposed solution?
Add login block to allowed navigation block

**Comment by ideadude** [comment]
Seems to be a dupe of [#38512](https://github.com/WordPress/gutenberg/issues/38512)

**Comment by skorasaurus** [comment]
this has been fixed in https://github.com/WordPress/gutenberg/pull/49160 and will appear in a new version of gutenbeg.
