### ISSUE TITLE
Preview does not always reflect the current state of the post

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/gutenberg#48717]
### Description

Hello Team,

I am working on the **List block** and found that sometimes it's not working properly on the front side.

When we add items to the list block and update the page and then preview it front-view then its works fine.

But, when we are making continuous changes and then checking it to the front side then it's not working as expected.

For better understanding, I have prepared its video.

Please refer to this link: **[List Block Issue](https://share.cleanshot.com/0JVKHHyC5Rb5CLG46P9v)**

Thanks,

### Step-by-step reproduction instructions

- Type / to choose a block
- Select List block
- Add two to three item
- Check it front-side.
- Then add more items.
- Check it again into the front-side.
- Remove the item and add a new item.

### Screenshots, screen recording, code snippet

![list_block_back_end](https://user-images.githubusercontent.com/53076293/222693127-abd08751-1558-40f0-a4c4-f9c108248ed1.png)
![list_block_front_end](https://user-images.githubusercontent.com/53076293/222693154-5a272544-0d19-4079-bd6c-65d2086c080d.png)

### Environment info

- WordPress version: 6.2 Beta, Gutenberg 15.2.0, Theme active: Twenty Twenty-Three,
- Browser: Google chrome, Version 110.0.5481.177 (Official Build) (arm64)
- Device: MacBook Air M1
- OS: macOS 13.1

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I wasn't able to replicate this on Gutenberg 15.15.1 - @viralsampat-multidots are you able to retest on 15.15.1 and see if you can still replicate it?

**Comment by viralsampat-multidots** [comment]
Hello @glendaviesnz 

I hope you are doing well.

I read your above mentioned feedback.

Today, I have checked it again on latest Gutenberg plugins( 15.5.1 )

[Gutenberg Plugin](https://wordpress.org/plugins/gutenberg/)

As you mentioned  15.15.1, But I can't see this version.

Still, I am facing the same issue. I have created its video. Please see my attachment.

[List Block Issue ](https://share.cleanshot.com/70n0SKb4PjjBtVLGHyY3)

Please let me know your feedback for the same.

Thanks,

**Comment by glendaviesnz** [comment]
> As you mentioned 15.15.1, But I can't see this version.

My mistake, it was meant to be 15.5.1.

I was able to replicate this, but not only with the list block, the same thing happened with a paragraph block. There seems to be an issue with the preview showing a stale version of the page content in some circumstances. I have updated the issue title to better reflect this.

**Comment by jordesign** [comment]
Just looping back to this as it has been a few months (and versions). Do you still see this issue happening in your site @viralsampat-multidots  ?

**Comment by viralsampat-multidots** [comment]
Hello @jordesign 

Thank you for the feedback.

I will check it again and will provide detailed updates for the same.

Thanks,

**Comment by viralsampat-multidots** [comment]
Hello @jordesign 

I hope you are doing well.

Today, I have checked the above-mentioned issue on the below-mentioned environment, and now it looks good. I think that now it had fixed.

Environment info:

WordPress version: 6.2.2 Beta, Gutenberg 16.3.0, Theme active: Twenty Twenty-Three, Twenty Twenty-Two, Twenty Twenty-One, Twenty Twenty
Browser: Google Chrome, Version 114.0.5735.198 (Official Build) (arm64)
Device: MacBook Air M1
OS: macOS 13.4.1 (c) (22F770820d)

Thanks,

**Comment by jordesign** [comment]
That's great news - thanks @viralsampat-multidots ! I'll close this issue as resolved now - but please feel free to re-open with further details if it comes up again.
