### ISSUE TITLE
Navigation block: overlay colors are not shown the same in the editor and the frontend

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#48719]
### Description

When we add overlay colors to the navigation block, the editor will not show the same as the frontend. It's looking like the editor preview on mobile is also missing some of the theme's styles for typography too.

### Step-by-step reproduction instructions

1. Add a navigation block with a submenu in it.
2. Change the background and text colors for the overlay
3. Check the submenu in the editor
4. Check the submenu in the frontend. They are not the same color.
5. Check the mobile version too!

I'm using Archeo to test here

### Screenshots, screen recording, code snippet

Editor:
Desktop | Mobile 
--- | ---
<img width="922" alt="Screenshot 2023-03-03 at 11 09 33" src="https://user-images.githubusercontent.com/3593343/222694577-e8121cb7-34df-4ce2-b535-ba4308b8f3cd.png"> | <img width="1141" alt="Screenshot 2023-03-03 at 11 16 21" src="https://user-images.githubusercontent.com/3593343/222694553-cebb3511-5836-4148-8ca1-eec9f34661d5.png">

Frontend:
Desktop | Mobile 
--- | ---
<img width="982" alt="Screenshot 2023-03-03 at 11 09 36" src="https://user-images.githubusercontent.com/3593343/222694650-3eb86854-a4a4-48c8-b70e-e03c77cf5997.png"> | <img width="521" alt="Screenshot 2023-03-03 at 11 15 58" src="https://user-images.githubusercontent.com/3593343/222694687-1faa6b14-0993-4921-be1a-956f62e492f9.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by stacimc** [comment]
I tested this in Twenty Twenty Three and Archeo, and was unable to reproduce the bug:

<img width="742" alt="Screenshot 2023-08-01 at 2 13 08 PM" src="https://github.com/WordPress/gutenberg/assets/63313398/de46642b-542c-42fe-b409-6d0415c85f63">

Is it possible this was resolved by #50968?

**Comment by MaggieCabrera** [comment]
I forgot about this issue, it's no longer relevant, thank you for pointing it out!
