### ISSUE TITLE
Site Editor: Add a description to the Design panel

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48712]
The view that greets users in the Site Editor will change quite a bit from 6.1 -> 6.2.

| 6.1 | 6.2 |
| --- | --- |
| <img width="1199" alt="Screenshot 2023-03-03 at 09 03 25" src="https://user-images.githubusercontent.com/846565/222678145-22e8eca3-a3bd-4689-abe1-53502ddab148.png"> | <img width="1174" alt="Screenshot 2023-03-03 at 09 03 36" src="https://user-images.githubusercontent.com/846565/222678221-256e36bb-6b07-4454-9c90-09fe9962280f.png"> |

To help users orient themselves in this new experience, we might include a description in the Design panel briefly explaining the purpose of this section. e.g:

<img width="359" alt="Screenshot 2023-03-03 at 09 07 29" src="https://user-images.githubusercontent.com/846565/222678944-62a75fb2-5f5d-4905-947e-5c13335af14a.png">

The description above is not a proposal, we can and should explore options.

**Comment by ndiego** [comment]
There is a description now in Beta 5. Can we close this issue out, or is additional work needed?



![Image](https://user-images.githubusercontent.com/4832319/223509560-fa02d871-97d1-4642-ba72-48003a616e47.png)
