### ISSUE TITLE
Page Templates: Using 'default' as the title for the default Page Template within the Page inspector is confusing.

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#48713]
### Description

When viewing/changing Page templates within the page editor - the template is shown as 'default'.

This can be confusing for users if they go looking for which template to edit within the Site Editor (where it is shown as 'Page'.

Bringing consistency to the labelling of these would easy that problem.

### Step-by-step reproduction instructions

With a block theme active - open any page in the editor and check the settings for the Page Template in the Inspector.

### Screenshots, screen recording, code snippet

<img width="428" alt="Screen Shot 2023-03-03 at 8 21 07 pm" src="https://user-images.githubusercontent.com/1842363/222682156-b9530b57-f24c-4321-bd9a-3da81f3f7e3f.png">

### Environment info

WP 6.1.1 AND GB 15.2.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for contributing, @jordesign!

There's already an issue proposing a better label (#41449); I will close this as a duplicate.
