### ISSUE TITLE
Advanced settings being mistaken for a heading

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4871]
This was reported from usability testing:

> (Incidentally, some did click on a block’s vertical three dots to open the dropdown, but they were much more interested in block transformations and generally didn’t click “Show Advanced Settings.” My colleague Jen has a guess as to why that was happening: The :focus state stylings on the text “Show Advanced Settings” makes it look at first glance like a heading for the menu items that appear beneath it, rather than something that can itself be clicked.)

> Our users took a while to discover that blocks had advanced settings in the right-hand panel—and once they discovered it for one block, most didn’t think to revisit that panel for other blocks without some prompting by us.

https://design.oit.ncsu.edu/2018/02/02/gutenberg-testing/

![2018-02-05 at 11 35](https://user-images.githubusercontent.com/253067/35803195-bd42801c-0a6a-11e8-8fc5-0055e4998490.png)

As you can see it would be easy to mistake.

**Comment by melchoyce** [comment]
Any thought to a shortcut to flip over to Advanced Settings? I keep finding myself annoyed every time I have to go over and click on "Block" in the sidebar.

**Comment by karmatosed** [comment]
> Any thought to a shortcut to flip over to Advanced Settings? I keep finding myself annoyed every time I have to go over and click on "Block" in the sidebar.

An interesting idea. There isn't, but I wouldn't be against one.

**Comment by mtias** [comment]
The "add shortcuts to menu items" issue covers shortcuts for all these.

**Comment by karmatosed** [comment]
To solve the issue reported by the user, let's considering un-focusing the first item. This will need a workaround to suit accessibility, possibly with a hidden item. cc @afercia to work through this as we need to balance out this as it's catching users.

**Comment by mtias** [comment]
Note: there are various other issue with the autofocusing (including the table of contents popover jumping to the headings). Ideally the implementation is one that moves focus to the popover (and keeps it there when you tab through) but doesn't focus the initial item.

**Comment by SuperGeniusZeb** [comment]
The discoverability of the block inspector should be improved thanks to #5882, and the focus style of the "More Options" menu is now a dotted outline rather a solid one like in the picture in the main post of this issue. Additionally, clicking on the "More Options" button does not automatically focus "Show Advanced Settings", so it should not be confused for a heading anymore.

Is it safe to consider this issue fixed?

**Comment by karmatosed** [comment]
@SuperGeniusZeb no that doesn't solve the issue here.

**Comment by karmatosed** [comment]
Let's focus this over on https://github.com/WordPress/gutenberg/pull/5595 for now and close. The focus is the key to resolving this fully.
