### ISSUE TITLE
[Site Editor] White screen when using browser back button.

### ISSUE THREAD

**Issue by costdev** [WordPress/gutenberg#48726]
### Description

A white screen appears when using the browser's back button after navigating to the Editor, clicking in the navigation sidebar, then clicking the browser's back button once/twice.

### Step-by-step reproduction instructions

1. Navigate to the Site Editor.
2. Click on the navigation sidebar.
3. Click the browser's back button 🐞  Nothing happens
4. Click the browser's back button again 🐞  Get a white screen with `/site-editor.php?canvas=init&path=%2F` (or similar).

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/79332690/222730102-a4ec0e72-6a8c-4c87-ba71-b334cb37ec65.mp4

### Environment info

- WordPress: `trunk` going as far back as 6.2 Beta 1
- Gutenberg: With/without Gutenberg `trunk` active.
- Theme: Twenty-Twenty Three
- Browser: Chrome
- Plugins: No other plugins activated.
- OS: Ubuntu (WSL2 - Windows 10)
- PHP: 7.4
- @mukeshpanchal27 and @ndiego have confirmed it reproduced on their ends.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Cc @youknowriad

**Comment by youknowriad** [comment]
I don't reproduce personally (using Gutenberg trunk)

**Comment by youknowriad** [comment]
Oh actually, I do reproduce in Chrome but not in Safari.

**Comment by costdev** [comment]
I can also reproduce in Firefox and Edge

**Comment by youknowriad** [comment]
Fix in https://github.com/WordPress/gutenberg/pull/48731
