### ISSUE TITLE
FSE not mapping a custom template to the correct custom post type

### ISSUE THREAD

**Issue by gilsonviana** [WordPress/gutenberg#48738]
### Description

I'm using the 2023 theme to create a website with the FSE functionality.
I needed to create a custom post types and custom template to go with it. 

I was able to create a **single** template for all the items of **A Taste Of** type.

<img width="602" alt="Screenshot 2023-03-03 at 13 33 02" src="https://user-images.githubusercontent.com/12987365/222775513-dfea0743-c2a5-406e-80a6-94eddb31044c.png">

However, after creating a new article with the custom post type the template I get is the **404**.

Here's the snippet of how I'm registering the new custom type. I'm using the `init` hook to run this script.

```
register_post_type('taste-of', [
      'description'           => 'redacted',
      'supports'              => [
        'title',
        'editor',
        'revisions',
        'author',
        'custom-fields',
        'excerpt',
        'page-attributes',
        'thumbnail'
      ],
      'taxonomies'            => [
        'category'
      ],
      'hierarchical'          => false,
      'public'                => true,
      'show_ui'               => true,
      'show_in_menu'          => true,
      'menu_position'         => 20,
      'menu_icon'             => 'dashicons-welcome-widgets-menus',
      'show_in_admin_bar'     => true,
      'show_in_nav_menus'     => true,
      'show_in_rest'          => true,
      'rest_base'             => 'taste-of',
      'rest_controller_class' => 'WP_REST_Posts_Controller',
      'can_export'            => true,
      'has_archive'           => false,
      'exclude_from_search'   => false,
      'publicly_queryable'    => true,
      'capability_type'       => 'post',
      'rewrite'               => [
        'slug'         => 'a-taste-of',
        'with_front'   => false,
        'hierarchical' => true,
      ],
      'labels'                => [
        'name'               => 'redacted',
        'singular_name'      => 'redacted',
        'menu_name'          => 'redacted',
        'name_admin_bar'     => 'redacted',
        'add_new'            => 'redacted',
        'add_new_item'       => 'redacted',
        'new_item'           => 'redacted',
        'edit_item'          => 'redacted',
        'view_item'          => 'redacted',
        'all_items'          => 'redacted',
        'search_items'       => 'redacted',
        'parent_item_colon'  => 'redacted',
        'not_found'          => 'redacted',
        'not_found_in_trash' => 'redacted'
      ],
    ]);
```

### Step-by-step reproduction instructions

1. Register a new post type. `hello-world`
2. Create a new template for it. `single-hello-world.html`
3. Create a new post using the `hello-world` post type.
4. Publish the article.

### Environment info

- Wordpress version: 6.1.1
- Gutenberg version: 15.2.4
- Chrome version: 110.0.5481.177 (Official Build) (x86_64)
- Mac OS: Ventura 13.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ghost** [comment]
I wonder if this has anything to do with rewriting the slug, as I've never had this issue with cpt's. Have you actually tried your own testing instructions with a hello-world post type? And can you test this without rewriting the slug?

You can also try going to Settings > Permalinks and re-saving them.

Let me know how it goes. @gilsonviana

**Comment by gilsonviana** [comment]
Thanks for the advise. 

`You can also try going to Settings > Permalinks and re-saving them.`

This actually helped me.
