### ISSUE TITLE
Highlighted text is not always deleted when pressing "delete" key on keyboard

### ISSUE THREAD

**Issue by twstokes** [WordPress/gutenberg#48747]
### Description

Under the conditions provided in the step-by-step reproduction instructions:

**Expected behavior:**

Text is deleted.

**Actual behavior:**

Text is not deleted.

### Step-by-step reproduction instructions

Using a self-hosted WordPress site:

1. Add a new post
2. Switch to Code editor mode
3. Paste in the following:

```
<!-- wp:table -->
<figure class="wp-block-table"><table><tbody><tr><td><strong>Site Editor (MVP)</strong></td><td>Android tasks were started, <a href="https://www.google.com">but we're now assessing how to move forward due to developer availability</a>. The project will need to be paused if no developers are available to help with native portions. (<a href="https://www.google.com">latest update</a>)</td></tr></tbody></table></figure>
<!-- /wp:table -->
```

4. Exit Code editor
5. With the mouse cursor, select the second column of text (see video). **Note:** The direction the text is selected may have an impact on the issue, e.g. selecting from top left to bottom right or vice versa
6. Press "delete" on the keyboard

### Screenshots, screen recording, code snippet

_Unmute to hear delete being pressed._

https://user-images.githubusercontent.com/2092798/222808196-9ef9fef9-4942-48e5-b41e-10f2844eb97d.mov

### Environment info

- WordPress 6.1.1
- Chrome Version 110.0.5481.177 (Official Build) (arm64)
- MacBook Pro M1 / Monterey using built-in keyboard
- Twenty Twenty theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by twstokes** [comment]
There are possibly related issues but none that I saw that matched exactly:
- https://github.com/WordPress/gutenberg/issues/45880
- https://github.com/WordPress/gutenberg/issues/41416
- https://github.com/Automattic/wp-calypso/issues/65193

**Comment by annezazu** [comment]
@ellatrix in case you can dig into this! (or @mcsf).
