### ISSUE TITLE
A Reusable Block based on an HTML block should preview

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#4875]
When inserting a reusable block made out of HTML, we should probably preview it, and only show the code if the user wants to edit the block:

![image](https://user-images.githubusercontent.com/548849/35824571-8e248e76-0ab3-11e8-8508-1427f63ee24f.png)

**Comment by noisysocks** [comment]
Neat idea. I suspect to do this we'd have to move the `preview` boolean out of the HTML block's component state and into a prop that the reusable block can set and unset.
