### ISSUE TITLE
Allow disabling the shadow panel

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#48753]
### Description

There is no way to turn off the Shadow panel in Site Editor > Styles > Blocks > Button
If theme.json turns off all presets, the panel still shows, but it has no options.

### Step-by-step reproduction instructions

Add the following under `settings` in theme.json:
```
	"shadow": {
		"presets": [],
		"defaultPresets": false
	},
```

### Screenshots, screen recording, code snippet

The panel shows but there are no options:
<img width="572" alt="Shadow panel and modal in the Styles Sidebar" src="https://user-images.githubusercontent.com/7422055/222910186-258d3846-695f-414b-887f-a901145f54d3.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ghost** [comment]
Where did you find the `"defaultPresets": false` option? It doesn't show up in my theme schema yet, or are you suggesting we add this?

**Comment by ghost** [comment]
One other question, I can't find a disable option for the other options, like border. Should that be added as well? Why only for the shadow? Or am I missing something? :)

**Comment by carolinan** [comment]
From the shadow PR https://github.com/WordPress/gutenberg/pull/46502 and theme.json https://github.com/WordPress/gutenberg/blob/trunk/lib/theme.json#L190

Shadow is enabled by default. Border is opt-in, disabled by default.

**Comment by carolinan** [comment]
It follows the same pattern as other settings: `"defaultPalette": false`, `"defaultGradients": false`. ` "defaultDuotone": false`

**Comment by colorful-tones** [comment]
I went as far as trying the above _and_ this and the empty shadow panel still shows (as reported by Carolina).

```
{
    "settings": {
        "blocks": {
            "core/button": {
                "shadow": false
            }
        }
    }
}
```

**Comment by cbirdsong** [comment]
This is not specific to the button block. It also shows up on column blocks.

**Comment by carolinan** [comment]
Yes this issue is a bit out of date since the shadow controls changed in WP 6.5.

**Comment by t-hamano** [comment]
This issue could not be reproduced in the latest Gutenberg. It seems that we just need to set `settings.shadow.defaultPresets` to `false`:

```json
{
	"$schema": "../../schemas/json/theme.json",
	"version": 3,
	"settings": {
		"appearanceTools": true,
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		},
		"shadow": {
			"defaultPresets": false
		}
	}
}
```

I would like to close this issue, but please feel free to reopen it at any time if the problem reoccurs.

**Comment by carolinan** [comment]
I still don't think this is the correct solution since the name of the option is to literally set the default presets to false, not disable the option. 🤷‍♀️

**Comment by t-hamano** [comment]
I believe what is considered a bug in this issue is that the panel is unintentionally displayed even though there is no preset. This issue has already been resolved.

Furthermore, I believe that the specification that the panel's visibility depends on whether there is a preset is consistent across colors, font sizes, and shadows.

What is the correct solution required here?

**Comment by carolinan** [comment]
Colors has text, background, link heading etc that is a boolean set to true or false, which are separate from disabling presets.
So does sticky, aspectratio, background image etc.
The different logic used for similar settings makes theme.json more difficult to use because there is no one pattern to follow.

**Comment by t-hamano** [comment]
I see, so you want to be able to set a boolean instead of an array, as mentioned in [the comment](https://github.com/WordPress/gutenberg/issues/48753#issuecomment-1535387436)? Either way, that would be considered an enhancement, and it's not just limited to shadow presets, so it might be best to open a new issue.
