### ISSUE TITLE
Removing Emojis as GDPR trap

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#48767]
Inserting Emojis in the WordPress backend by every post author is very easy:
![grafik](https://user-images.githubusercontent.com/32030147/223041982-4a3c8731-8fc2-425b-8420-647d4b8d4bce.png)

But when inserted, WordPress breaks a GDPR rule in the webpage frontend out of the box and loads the Emojis as SVG images from s.w.org Server.
![grafik](https://user-images.githubusercontent.com/32030147/223042679-a5f92469-7df8-48c7-885a-6c47279e30c0.png)

So, loading ressources from an external server without user consent, the website owner can be sued in Europe!

The only solution at the moment is using a plugin like https://wordpress.org/plugins/disable-emojis/
![grafik](https://user-images.githubusercontent.com/32030147/223043468-32c0bf3f-2a9f-42e0-9f10-9541ef2fc43e.png)

Without any drawback in result, because any modern browser can display Emojis out of the box!

But adding a "Disable Emojis" plugin to every WordPress website in Europe to be conform with GDPR is not a very lean solution. And most website owners are even not aware of the - high price - problem of a simple, single inserted Emoji!

One of the following solutions would be a lot better:
A) Deactivating Emoji server fetching out of the box in WordPress
B) Make Emoji server fetching optional (default = NOT) with a simple switch box in Settings => Reading
C) Load Emojis locally (= from the same server of the WordPress installation)

**Comment by talldan** [comment]
@burnuser I think this issue would be better created on the WordPress Core issue tracker (https://core.trac.wordpress.org/), as I don't think this is a Gutenberg/Block Editor feature.

(I realise it's a bit confusing that there are two separate issue trackers).

**Comment by burnuser** [comment]
Reported in Core as advised: https://core.trac.wordpress.org/ticket/57880

**Comment by talldan** [comment]
Thank you!
