### ISSUE TITLE
Prevent Reusable Blocks from losing changes

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#4876]
Editing a block, then unselecting the block, loses current changes with no warning. We should show a warning.

**Comment by karmatosed** [comment]
I think this is a great idea and we should give more messages like this.

**Comment by ZebulanStanphill** [comment]
Now if you unselect a Reusable block, nothing is lost, because the block remains in an editing mode. There is a <kbd><samp>Cancel</samp></kbd> button to revert changes you have made.

I think this issue can be closed now.

**Comment by mtias** [comment]
Noting there's a refactor pending on Reusable Blocks.

**Comment by designsimply** [comment]
Tested with WordPress 4.9.8 and Gutenberg 4.1.0 using Firefox 62.0.3 on macOS 10.13.6 and found that unselecting a reusable block that has edits does not result in losing the changes. ([27s](https://cloudup.com/cGog_nCxdXy))

The refactor from #10751 should be included so I think we're good to go on this one. 👍
