### ISSUE TITLE
Template Part details panel: Add semantic descriptions

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48777]
https://github.com/WordPress/gutenberg/pull/48732 will add a basic detail to this panel: The original author of the template part.

We can expand this a lot in the future, and even offer some edit actions (rename, reset, etc).

In the short term it might be nice to add some more flavor by describing semantic areas when appropriate. Here's a rough example:

<img width="358" alt="Screenshot 2023-03-06 at 11 54 29" src="https://user-images.githubusercontent.com/846565/223103382-2c2141f0-7a69-434c-ace9-97a105fc74e0.png">

**Comment by jameskoster** [comment]
Here are some ideas for descriptions:

**Headers**
This Template Part is a Header, which typically includes the site title, logo, and main navigation menu. You can have multiple headers; for example, the blog archive template may have a simple header design while the single post template may feature a more elaborate one, including the Post Featured Image.

**Footers**
This Template Part is a Footer, which typically includes credits, social links, and other contact details. You can have multiple footers; for example, you might want a simpler footer on your Contact page template to avoid repeating page content.

**General template parts**
This is a generic template part unrelated to any specific area within a page. Generic template parts can have various uses; for example, Displaying a Post summary for use in blog archive templates. Or displaying comments on both the Post and Page templates.

**Comment by richtabor** [comment]
> Template Part

Should "Template Part" be capitalized? I don't _think_ so. 

> single post template

But I do think we should capitalize specific templates/template parts. We should also use terms directly referencing the template names when we call out other templates. In this example, I'd use "Single" template, as that's what we call it in the Site Editor. 

> the blog archive template 

Maybe "the Blog's Archive template" perhaps? Not sure, but I do like connecting Archive with Blog.

**Comment by richtabor** [comment]
Perhaps there's an opportunity to detail what template parts are. 

Something like: 

This template part is a Header, which typically includes the site title, logo, and main navigation menu. Template parts are smaller, reusable parts of your site. Personalize this template part or [make a new one](url).

You can have multiple headers; for example, the Blog template may have a simple header design while the Single template may feature a Post Featured Image block for added imagery.

**Comment by jameskoster** [comment]
> Should "Template Part" be capitalized? I don't think so.

I'm never sure on these things. Looking at the copy [here](https://developer.wordpress.org/themes/block-themes/templates-and-template-parts/), I guess not.

> Perhaps there's an opportunity to detail what template parts are.

I thought about that, but we do have the Template part panel itself which already does this to some extent, so I was worried it might be a bit repetitive?

**Comment by apeatling** [comment]
Is the copy finalized for these? I was going to work on adding.

**Comment by jameskoster** [comment]
I think we could start with the suggestions in https://github.com/WordPress/gutenberg/issues/48777#issuecomment-1456053231 and refine in the PR if required.

**Comment by ndiego** [comment]
Hey @jameskoster, just checking in as this issue is on the [6.3 Project Board](https://github.com/orgs/WordPress/projects/103/views/1), and I do not see any recent activity. Are we still aiming for 6.3 with this? Thanks!

**Comment by jameskoster** [comment]
Ideally, yes. But this is just one small detail among a host of other improvements to be made in this panel, the full details of which can be seen in https://github.com/WordPress/gutenberg/issues/50395. So if you'd like to close this issue in favor of that one, please feel free.

**Comment by ndiego** [comment]
Great, thanks @jameskoster. I will close this in favor of https://github.com/WordPress/gutenberg/issues/50395. By Beta 1 (6/27), we should consider adding all remaining items on [6.3 Design](https://github.com/orgs/WordPress/projects/82) to the [6.3 Project Board](https://github.com/orgs/WordPress/projects/103) (they can be on both boards) as that will be the main board that the Editor Triage Team, and the Editor Tech Leads will be working off of.

**Comment by jameskoster** [comment]
Apologies, I linked to the wrong issue. https://github.com/WordPress/gutenberg/issues/50392 is the one I was looking for.
