### ISSUE TITLE
Site Editor: Unsaved changes on a fresh install

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48787]
### Description

After opening the Site Editor on a totally fresh installation, I see two unsaved changes which feels a bit unexpected. 

It seems to be related to the Navigation block. I have an empty instance of that in both my Header and Footer template parts like so:

`<!-- wp:navigation {"layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"left"}} /-->`

Perhaps the menus are being created on initialisation, but not saved.

### Step-by-step reproduction instructions

1. Fresh install of WP 6.2-beta4
2. Active a theme with an instance of the Navigation block in the header and/or footer
3. Open the Site Editor
4. See "unsaved changes" and active save button at the bottom of the dark sidebar

It's worth noting: if you exit the Editor _without saving_ then re-enter, then the "unsaved changes" message disappears. 

### Screenshots, screen recording, code snippet

<img width="1122" alt="Screenshot 2023-03-06 at 13 49 18" src="https://user-images.githubusercontent.com/846565/223130159-424d24ee-7d2a-4d67-aa3c-459fc343d724.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I just tested with Beta 5 without Gutenberg enabled, and I'm unable to replicate this issue 🤔

**Comment by jameskoster** [comment]
> without Gutenberg enabled

Oh, I had Gutenberg trunk active... that might explains things. Or perhaps it got fixed.

I am now seeing a separate issue though – no Navigation panel in the Site Editor at all... 

<img width="501" alt="Screenshot 2023-03-07 at 19 29 16" src="https://user-images.githubusercontent.com/846565/223531725-8692cb04-6ea9-459f-afe7-3fa3dc0fc5b2.png">

Totally fresh beta 5 install, no Gutenberg plugin.

I guess it's because no navigation menus exist on a fresh install... Perhaps you could check before I open a separate issue?

**Comment by ndiego** [comment]
> I guess it's because no navigation menus exist on a fresh install... Perhaps you could check before I open a separate issue?

Yeah, I discovered that as well, but I figured it was expected. Once I added a menu, it appeared, but then I ran into this: https://github.com/WordPress/gutenberg/issues/48897 😅
