### ISSUE TITLE
Site Editor details panel: Add descriptions for key pages like homepage, posts page

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48782]
https://github.com/WordPress/gutenberg/pull/48739 added basic descriptions to pages:

<img width="361" alt="Screenshot 2023-03-06 at 12 56 57" src="https://user-images.githubusercontent.com/846565/223116598-1b9b9a50-d3a0-4a83-86cc-55973311d0d8.png">

It works ok for generic pages, but we can elaborate and improve the experience for special pages like the Homepage, Posts Page, Privacy Policy page, etc. We should do this in a way that plugins can extend, for example WooCommerce might want a unique description for the Shop, Cart, and Checkout pages.

- [ ] Homepage
- [ ] Posts Page
- [ ] Privacy Policy

**Comment by jameskoster** [comment]
Here are some ideas:

**Homepage**
> This is your homepage, visitors will be shown this page when they visit thesiteurl.com. 

In the future it would be nice to allow folks to _change_ their homepage here.

**Posts Page**
This one is tricky, because it's not really a `page`. It's a redirect to either the Home or Index template.

> This is your Posts Page or Blog Home. Visitors will see your latest posts when they view this page.

**Privacy Policy**
I'm not entirely sure why we have a setting for this, so it's a bit tricky to write a description.

**Comment by jasmussen** [comment]
> This is your Posts Page or Blog Home. Visitors will see your latest posts when they view this page.

I wonder if this description could be contextual based on whether it actually acts as your homepage or not. And in relation to your other comment, I agree, it would be nice to be able to make this happen in context of it. Here's a drilldown detail that I don't really love in terms of the visuals, but which nevertheless tries to include a dropdown that would let you set the behavior of that particular page, i.e. set as homepage etc:

<img width="628" alt="Screenshot 2023-04-12 at 14 31 31" src="https://user-images.githubusercontent.com/1204802/231458131-e5449e91-217f-4ce8-8454-638493d9f9c6.png">

Assuming we could do this, we could split in two descriptions. When the Posts Page is also your homepage:

> This is your Posts Page. It is set as your homepage, so visitors will see your latest posts when they visit thesiteurl.com.

When the Posts Page is _not_ your homepage:

> This is your Posts Page or Blog Home. Visitors will see your latest posts when they view this page.

We might even be able to make those descriptions link to a "Site Settings" page from here, where you could change it. As discussed in https://github.com/WordPress/gutenberg/issues/49597#issuecomment-1502883807, it's unclear whether being able to set these special pages in drilldown detail pages could _entirely_ replace the reading setting, or not:

<img width="474" alt="Screenshot 2023-04-12 at 14 35 30" src="https://user-images.githubusercontent.com/1204802/231459136-535051d7-67dd-4a9a-ba66-77e76e1c5247.png">

**Comment by jameskoster** [comment]
The homepage settings are probably worth exploring in a dedicated issue, it's a gnarly one. For now I think it would be nice to simply update these descriptions to be more contextual when appropriate. 

> I wonder if this description could be contextual based on whether it actually acts as your homepage or not

I don't think so, because the 'Posts page' concept only exists when you're using a static home page. This is part of the aforementioned gnarly-ness xD

**Comment by Mamaduka** [comment]
I'm going to punt this one for WP 6.3 as well. Improvements will introduce new strings. While there have been cases of changing strings in minor releases, they are still rare.

**Comment by jasmussen** [comment]
Taking a fresh stab based on [the initial suggestions](https://github.com/WordPress/gutenberg/issues/48782#issuecomment-1456120201).

> **Homepage**
> This is your homepage, visitors will be shown this page when they visit thesiteurl.com.

> **Posts Page**
> This is your Posts Page or Blog Home. Visitors will see your latest posts when they view this page.

☝️ unchanged, seem good.

> **Privacy Policy**
> The Privacy Policy page can be an important component of your website, so as to comply with EU GDPR regulations. This page enables you to inform your site visitors about the collection, usage, and protection of their personal information, whether through the use of cookies or otherwise.

How about this?

**Comment by jameskoster** [comment]
You know what, I think we can probably close this in favor of https://github.com/WordPress/gutenberg/issues/50582. There's probably no need for both. What do you think?

**Comment by jasmussen** [comment]
Sure, do we need to copy the privacy description over?

**Comment by jameskoster** [comment]
I reckon we can use the same approach for that page, IE an icon instead of the description. 

Probably fine to handle that one separately though... the icon might require some exploration, and since most privacy policy pages are most likely titled "Privacy policy", they're already easy to find.
