### ISSUE TITLE
Site Editor Navigation panel: Link titles are misleading

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48799]
<img width="395" alt="Screenshot 2023-03-06 at 16 32 13" src="https://user-images.githubusercontent.com/846565/223172383-59da2065-9566-4c8a-bfe1-073e85ed6ad9.png">

The title here suggests that a click will take you to an edit interface for the block itself, which isn't what happens at all in this context.

**Comment by carolinan** [comment]
What should it say instead, only the block name? And if the name is not available?

**Comment by jameskoster** [comment]
Clicking these items takes you to an interstitial where you can view and edit the associated content. So perhaps something like:

> View `page name`

**Comment by bobbingwide** [comment]
I came across this problem today. My experience may have been further hindered by the fact that my links were incorrect.
But clicking on them didn't appear to do anything at all.

**Comment by jameskoster** [comment]
By 'incorrect' do you mean broken? IE linking to content that no longer exists? I think that's a separate issue.

**Comment by bobbingwide** [comment]
> My experience may have been further hindered ...

by the fact I was running Gutenberg 15.2.4 while attempting to test with 6.2-beta5

- With Gutenberg the Add page link action doesn't display a dialog for me. 
- Nor does clicking on an existing link. 

With 6.2-beta5
- A valid page link leads to the interstitial
- A incorrect / broken link ( eg one that's missing the ID attribute ) doesn't open the interstitial 
- Clicking on a custom-link doesn't open one either - as expected

**Comment by youknowriad** [comment]
How do you see this nowadays? I'm not be relevant anymore.

**Comment by jameskoster** [comment]
Seems to have been fixed somewhere along the way.
