### ISSUE TITLE
List View: Creating a template part from a block's ellipsis does not create a template part from that block if another is selected.

### ISSUE THREAD

**Issue by costdev** [WordPress/gutenberg#48818]
### Description

The List View does not create a template part from the block whose ellipsis was clicked, but rather from the selected block(s).

This means that if I select a Paragraph block, but click on a Group block's ellipsis and click **Create template part**, it will create a template part containing the Paragraph block, not the Group.

**Expected behaviour**
Clicking the ellipsis for a non-selected block, then clicking **Create template block**, should create a template part from the block whose ellipsis was clicked.

**Actual behaviour**
Clicking the ellipsis for a non-selected block, then clicking **Create template block**, creates a template part from whichever block is selected.

### Step-by-step reproduction instructions

1. Insert a Group block containing an image and a heading.
2. Insert a Paragraph block below the Group block (not nested) with the text: "Should not be in template part".
3. Open the List View and ensure the Paragraph block is selected.
4. Click the ellipsis beside the Group block, and create a template part called **My Group**.
5. Navigate to `Template parts > My Group`.
6. 🐞 Notice that the template part contains the Paragraph block, rather than the Group block.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/79332690/223363703-2c005ddb-470d-41ed-b526-d01098e388f4.mp4

### Environment info

- WordPress: 5.9.5, 6.0.3, 6.1.1 and `trunk`
- Gutenberg: `trunk` (active and inactive)
- Theme: Twenty-Twenty Two / Twenty-Twenty Three
- Browser: Chrome
- Device: Desktop on Windows 10 (via WSL2 with Ubuntu)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
The code is checking for which blocks are selected in the editor canvas (as you would expect given the bug).

It should instead be using the `selectedClientIds` parameter that `BlockSettingsMenuControls` provides for the [convert to template parts menu option](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/template-part-converter/convert-to-template-part.js#L82) and the [convert to regular blocks menu option](https://github.com/WordPress/gutenberg/blob/e2e96cf915219854a5adab674737b9f45e771646/packages/edit-site/src/components/template-part-converter/convert-to-regular.js#L27)

e.g.
```jsx
<BlockSettingsMenuControls>
	{ ( { onClose, selectedClientIds } ) => (
```

It seems like it'll require a bit of refactoring to make that possible.

**Comment by PH4NTOMiki** [comment]
@costdev you were right, the bug I created on Trac (https://core.trac.wordpress.org/ticket/57872) is the same.
