### ISSUE TITLE
Resolve PrivateInserter with standard Inserter

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#48824]
In https://github.com/WordPress/gutenberg/pull/48752 we created a PrivateInserter for usage in the Navigation Offcanvas to allow us to customise the ordering of blocks in the inserter.

We need to decide how to resolve this longer term so that there is no need for this private wrapper.

**Comment by getdave** [comment]
cc @scruffian @ntsekouras

**Comment by talldan** [comment]
What kind of technical feedback is needed?

**Comment by ntsekouras** [comment]
I don't think the existence of the private wrapper is an issue and what we might want to question, is the actual `orderInitialBlockItems` API. Currently the ordering is in [trunk](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/off-canvas-editor/appender.js#L116) and we could consider:
1. Removing that API completely if it's not needed anymore. That would remove the wrapper too for now as there are no private APIs for the Inserter.
2. Stabilize the current API(thus no need for the private wrapper for now too)
3. Explore a different API to achieve the same result and stabilize that one(remove wrapper) or just replace `orderInitialBlockItems` as private API(keep the wrapper).

**Comment by getdave** [comment]
Yes what I'm saying is we have a Private inserter. Why do we need one? How can we make it so we don't need one.

Nik is right that `orderInitialBlockItems` is the issue. It's required to achieve specific functionality required by UX for the Nav block. 

We don't want to open the block inserter up to "abuse" in terms of certain blocks being forced to the front. 

That said, I don't think it would be possible to use the `orderInitialBlockItems` API to override the behaviour in the Editor itself as there aren't any extension points.

It's only useful if folks use their own custom implementation of `<Inserter>` in their own Plugin.

**Comment by scruffian** [comment]
Connected to https://github.com/WordPress/gutenberg/pull/49959

**Comment by youknowriad** [comment]
This component doesn't exist anymore.
