### ISSUE TITLE
Can't move block if it goes behind a left-aligned image

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4884]
## Issue Overview
I originally opened #1472 back in June last year. That issue has long been closed now, advising that it's been fixed, but it hasn't. This issues still exists in v2.1.0

If you add a Text block to the bottom of your content and then try to move it up the page, once it goes behind an image that is left aligned, you can no longer move the text block any further.

![gutenberg-cantmoveblocksbehindleftalignedimages](https://user-images.githubusercontent.com/2078245/35839348-0be6f3e0-0b44-11e8-928f-946b66028b6b.gif)

## Steps to Reproduce (for bugs)
1. Insert image block
2. Make image block left aligned
3. Insert multiple paragraph blocks (after image block)
4. Try to move last paragraph block past image block

## Expected Behavior
I should be able to easily move a block past any other block, using the navigation arrows

## Current Behavior
Once a block goes behind a left-aligned image, you can no longer move it

## Related Issues and/or PRs
#1472

_Firefox Quantum 58.0.1 (64-bit)
Gutenberg 2.1.0
WordPress 4.9.3_

**Comment by mtias** [comment]
This is working well now for me.
