### ISSUE TITLE
Gutenberg breaks locking the post content while editing

### ISSUE THREAD

**Issue by pojke** [WordPress/gutenberg#4885]
## Issue Overview
Currently WordPress has the ability to detect whether a user is editing the content of a specific post and notifies another user about it. When Gutenberg is installed that ability disappears causing chaos of editing. 

## Steps to Reproduce (for bugs)
1. Install fresh WordPress installation 
2. Add Gutenberg from plugin repository
3. Create the second user with "Editor" rights
4. As an admin, create and publish a post "test" with paragraph "test"
5. Open a different browser or incognito tab and log in as Editor
6. Copy and paste admin's link to "test" post. Add "something" to the paragraph and save
7. In the browser where admin is logged in, add "no" to the paragraph and save

## Expected Behavior

A popup "Username is already editing this post. Do you want to take over?"

## Current Behavior

One user overwrites the second user.

**Comment by mtias** [comment]
See #4331.
