### ISSUE TITLE
Pattern Sketch file download link down

### ISSUE THREAD

**Issue by hblackett** [WordPress/gutenberg#4886]
The Pattern Sketch file linked to from the [Gutenberg Design Principles](https://wordpress.org/gutenberg/handbook/reference/design-principles/) is leading to a [403](https://cldup.com/EP0acK_gyY.zip?download=pattern%20sketch%20file%20version%200.zip) ("The download of this file has been disabled for security reasons"). Please can a new link be provided?

**Comment by youknowriad** [comment]
This is not the link I'm seeing on the page. I get this link https://cloudup.com/c0Q8RQDHByq and it's working for me.

**Comment by youknowriad** [comment]
Let me know if this is not what you're looking for

**Comment by ajitbohra** [comment]
@youknowriad https://cloudup.com/c0Q8RQDHByq link is not working 
![patternerror](https://user-images.githubusercontent.com/1039236/36806777-22573482-1ce7-11e8-9064-d6cd15747fd3.jpg)

**Comment by youknowriad** [comment]
I didn't click the "download link" :) cc @jasmussen

**Comment by jasmussen** [comment]
Ah, I think that's a @karmatosed file

**Comment by ajitbohra** [comment]
@youknowriad

Have checked the handbook we have 2 links to sketch file.

![sketch](https://user-images.githubusercontent.com/1039236/36813843-d812987a-1cfb-11e8-92e4-c7322f8882dd.png)

- First, link `Download Sketch file` provides 2 files uploaded by @jasmussen  which contains patterns & mockup 
- Second link `Download Pattern Sketch file` uploaded by @karmatosed cannot be downloaded

I guess the first link provides the needed sketch files we can remove the second link or update the docs to directly link to individual files.

**Mockup:** https://cloudup.com/i0Eu-Wy1w-5
**Patterns:** https://cloudup.com/ieNQiu37EMO

**The content of the first link:**
![pattern](https://user-images.githubusercontent.com/1039236/36814304-1f976f8a-1cfd-11e8-9841-7c23810d43c9.jpg)

**Comment by karmatosed** [comment]
This should be fixed now, thanks!
