### ISSUE TITLE
Extended Settings - right sidebar block

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#4887]
Just a Info question.
Can somebody explain me what is purpose of "Extended Settings" block in right sidebar ?

Is it for some advanced block (extra) settings ?
Or is it as it was once, same custom Metaboxes settings in right sidebar ?

I cannot find Info in other issues.

- On one websites it opens with grey background and nothing else.
- On second website seems as it opens with grey background. Block is last in line so difficult to know.

- On second websites I removed everything from backend with Plugin Organizer. Only left are ACF, Gutenberg and Plugin Organizer self.

- JS console gives no errors.

**Comment by StaggerLeee** [comment]
Will quickly close it, as is probably not real bug or issue. 
Waiting for some Info, thank you.

**Comment by StaggerLeee** [comment]
Very strange. Removed blocked plugins (checked, still activated right)  from Plugin Organizer and now Extended Settings works.
Out of my competence to explain this behaviour.

Anyway, to not to open new issue.
You can maybe CSS design and style custom Metaboxes under "Extended Settings" to differentiate them from "Extended Settings" header/block. As it is now they do not look alike subparts of "Extended Settings" but as blocks on its own.

If this block is planned to be there in final version, of course.

**Comment by bobbingwide** [comment]
It's a good question.  

If you have a custom meta box that has a context of 'side' then the Extended settings meta box will contain it.  

You can drag and drop meta boxes between this area and the area below the main content ( context normal ). And you can drag them back again

But only if the Extended settings area does exist.

You can use `&classic-editor` to move the meta boxes about but if you move all of them into the Extended settings section you won't be able to drag them back into the bottom area.

I'd re-open this issue. It needs a design decision as to what is expected to happen.

**Comment by StaggerLeee** [comment]
Tried drag & drop Metabox but seems is not working yet.
