### ISSUE TITLE
Site Editor: Navigation panel does not update as expect with template menu changes.

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#48897]
### Description

In testing WordPress 6.2 Beta 5, I discovered a potential issue with the Navigation panel. The panel does not appear to update consistently when changes are made to the primary navigation in a template. I am wondering if this behavior is expected given https://github.com/WordPress/gutenberg/pull/48689, but if so, I am confused about how to update the Navigation panel with a new "primary" menu. The video below better illustrates this issue 😅 

### Step-by-step reproduction instructions

1. In the Site Editor, add a menu to a template. This menu should reflect in the Navigation panel. 
2. Then create a new menu and replace the previous menu. 
3. The new menu does not reflect in the Navigation panel. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4832319/223518798-a51bc05f-b88f-4614-a5ae-318f88dae833.mp4

### Environment info

- WordPress 6.2 Beta 5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
cc @Mamaduka @ntsekouras @scruffian

**Comment by Mamaduka** [comment]
@ndiego, I believe this is intentional.

Based on recent changes in #48689:

> Always pick the latest published manu and ignore the loaded template (the menu is higher order than the frame)

**Comment by jameskoster** [comment]
Oh yes, this was intentional. The Navigation panel is supposed to always display the main menu, and never change. It was confusing to find different menus represented there based on seemingly random actions. 

We still need to somehow indicate which menu is the main one in the UI though (https://github.com/WordPress/gutenberg/issues/48891).

**Comment by ndiego** [comment]
> Oh yes, this was intentional. The Navigation panel is supposed to always display the main menu, and never change. It was confusing to find different menus represented there based on seemingly random actions.

@jameskoster fair enough, but we also need a way for users to define what the primary menu is and change it. As far as I can tell, there is no way to set this anywhere in the UI.

**Comment by jameskoster** [comment]
I agree. But that is a bigger item and unlikely to make it into 6.2.

**Comment by ndiego** [comment]
> I agree. But that is a bigger item and unlikely to make it into 6.2.

Yup, we are already basically out of time. I am still concerned about this current flow. It is not obvious what menu is presented in the panel and how to change it. This confusion also surfaced in today's [core-editor meeting](https://wordpress.slack.com/archives/C02QB2JS7/p1678286922437239).

**Comment by jameskoster** [comment]
I think it would help if we marked the main menu somehow. But yeah, we're basically out of time even for small changes like that :(

**Comment by annezazu** [comment]
Just want to underscore this feedback and reiterate how confusing the experience is. Here's a quick video demonstrating how odd it is to know which menu will show up and why. 

https://user-images.githubusercontent.com/26996883/223811785-d6c94360-f323-4efe-91e6-f43bba63a6ee.mov

**Comment by Mamaduka** [comment]
The navigation panel was removed in 6.2, punting it to the next major release.

**Comment by getdave** [comment]
So folks are aware [the Navigation panel has been updated to show a list of menus](https://github.com/WordPress/gutenberg/pull/50840) which will allow you to select the most appropriate one.

If there is only a single menu then it will just show that directly.

I think we can close this one out.
