### ISSUE TITLE
Distraction free mode does not hide the Custom Fields panel

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/gutenberg#48909]
### Description

When switching to the new distraction-free mode in WordPress 6.2, if the user has enabled the Custom Fields panel, the panel is not hidden when the distraction-free mode is enabled.

To reproduce, enable the Custom Fields panel in the Editor preferences, and then enable Distraction-free mode.

Tested on WordPress 6.2-beta5. 

### Step-by-step reproduction instructions

1. Create a new post or page
2. Enable the Custom Fields panel for the block editor
3. Enable Distraction free mode

### Screenshots, screen recording, code snippet

![custom-fields-enabled-scaled](https://user-images.githubusercontent.com/180629/223635438-a5fc8116-fc06-4fa9-b774-06245d4a1743.jpg)

### Environment info

- WordPress 6.2-beta5
- Gutenberg plugin is not enabled

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ironprogrammer** [comment]
Thanks for the report! I was able to reproduce this issue as well.

Originally reported in Trac: https://core.trac.wordpress.org/ticket/57800.

**Comment by annezazu** [comment]
Tagging in @draganescu who implemented this feature!

**Comment by annezazu** [comment]
Pulling in information for 6.2 purposes if we want to include this fix (if one can be done in time) from slack from @hellofromtonya: 

> I assume this will require a fix within the packages. If it can be fixed before RC1, then it can be included in the @wordpress package updates planned for tomorrow.

Added to the 6.2 board for now just in case. Otherwise, can punt as this doesn't appear blocking.
