### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#4891]
Hi,

Downloaded and run `npm run package-plugin` as per instructions here https://github.com/WordPress/gutenberg/blob/master/docs/release.md but some files are missing.

<img width="1274" alt="screen shot 2018-02-06 at 9 40 58 pm" src="https://user-images.githubusercontent.com/3365507/35862296-0751cce0-0b00-11e8-8538-bce9e6c97f68.png">

Thanks!

**Comment by Soean** [comment]
@phpbits So you generated a gutenberg.zip file and installed the plugin via this file into a Wp installation?

**Comment by phpbits** [comment]
@Soean Yes! It's successfully generated but there are some files missing. I've even run the npm build and dev and files are still missing. Thanks!

**Comment by phpbits** [comment]
@Soean Is this the issue : https://github.com/WordPress/gutenberg/blob/master/bin/build-plugin-zip.sh there's no `**edit-post/build/*.css \**`

Let me know how it goes.

**Comment by aduth** [comment]
@phpbits Yes, that appears to be the issue. Fix proposed at #4957.

**Comment by phpbits** [comment]
@aduth Perfect! Thanks!
