### ISSUE TITLE
Do not display a post excerpt if the custom post type does not support it

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#48914]
### Description

If you register a custom post type that does not have support for excerpts, the excerpt block is still available in the inserter.
The block can also be used inside a query loop that is set to display custom post types.

When the block is added, it throws a JavaScript error in the editor and displays an auto generated excerpt on the front.
1. This JavaScript error needs to be resolved.
2. An excerpt should not show for post types that do not support it, neither in the editor nor front. It should not show the "No post excerpt found" message.

### Step-by-step reproduction instructions

Register a custom post type and do not include support for excerpts.
https://developer.wordpress.org/plugins/post-types/registering-custom-post-types/

Create a new custom post type item in the block editor.
Add a post excerpt block and see the error.
Add a query block with an excerpt block inside, and select the custom post type in the post type dropdown in the block settings.

### Screenshots, screen recording, code snippet

Introduced in https://github.com/WordPress/gutenberg/pull/44964

```
edit.js:145 Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at PostExcerptEditor (edit.js:145:5)
```

### Environment info

Gutenberg 15.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I closed this because I learnt that _not displaying the excerpt_ does not match how the core PHP functions for excerpts works.
The JavaScript error will be addressed though.

**Comment by bobbingwide** [comment]
> The JavaScript error will be addressed though.

I inadvertently came across the same problem. In my scenario it's the custom post type that's being queried in the query loop that doesn't support `excerpt`. 

In this screenshot the list view has gone wonky.

![image](https://user-images.githubusercontent.com/2474435/224385346-3686a8a6-f5a4-49b3-b27e-66ec327780e5.png)

So how will the JavaScript error be addressed?

**Comment by carolinan** [comment]
I have a PR with a fix, that is waiting for review. https://github.com/WordPress/gutenberg/pull/48730
