### ISSUE TITLE
Travis CI: Docker CLI image permission errors, stops at installing WordPress

### ISSUE THREAD

**Issue by jaswrks** [WordPress/gutenberg#4893]
## Issue Overview
Removing `>/dev/null` from [these lines](https://github.com/WordPress/gutenberg/blob/150809dc786dbbd2abcd3ca88d0fd27a31ffe866/bin/install-docker.sh#L44-L47) reveals permission errors and they are currently halting the execution of some Travis builds. Travis stops at installing WordPress; e.g., https://travis-ci.org/WordPress/gutenberg/jobs/338015961#L639

## Expected Behavior
That the rest of [these lines](https://github.com/WordPress/gutenberg/blob/150809dc786dbbd2abcd3ca88d0fd27a31ffe866/bin/install-docker.sh#L49-L66) would run and complete the installation.

## Current Behavior
Stops at installing WordPress and outputs the following with `>/dev/null` removed.

```
Warning: Unable to create directory wp-content/uploads/2018/02. Is its parent directory writable by the server?
Updating to version 4.9.3 (en_US)...
Downloading update from https://downloads.wordpress.org/release/wordpress-4.9.3-no-content.zip...
Unpacking the update...
Error: Could not create directory.
```

## Possible Solution
Work around a bug in the `cli` docker image, see: https://github.com/docker-library/wordpress/issues/279. This could be fixed temporarily by running commands in the `cli` docker image as UID `33` explicitly.

This was a blocker in https://github.com/WordPress/gutenberg/pull/4797 and I added a temporary fix to get things working there. If you'd like have a look at what I changed, please see: https://github.com/WordPress/gutenberg/pull/4797/commits/92ef33abe044b27ff54ebdcfe08c1ce9591305f3

**Comment by ntwb** [comment]
Thanks for digging into this rabbit hole and finding the solution @jaswrks 💯
