### ISSUE TITLE
Classic block crashes when loaded into Site Editor as part of a Reusable block or post content

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#48938]
### Description

While testing WordPress 6.2-beta5, I inserted a Reusable block into my home page in order to see the color purple.
When I opened the Site Editor the Reusable block was loaded into the post content block, but the Classic block within it encountered an error. 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'tinymce')
```

I've since discovered that the problem also occurs for Classic blocks being displayed in Post Content.

See also #23086

### Step-by-step reproduction instructions

For a site which displays a static page as the home page 

1. Edit your home page 
2. insert a Classic block
3. Save
4. Choose Edit site 
5. Scroll down to see that the Classic block has encountered an error.

### Screenshots, screen recording, code snippet

This screenshot is for the Classic block within the Reusable block

![image](https://user-images.githubusercontent.com/2474435/223796996-dcb7b0e2-6d06-4ae3-8065-c050a231f09a.png)

This screenshot is for the Classic block directly in post content

![image](https://user-images.githubusercontent.com/2474435/223806290-a7ab8acf-9d8e-4c42-bd4a-90c684fba71f.png)

### Environment info

- WordPress 6.2-beta5
- Gutenberg 15.2.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment]
Adding this to the 6.2 board proactively and for consideration. It's by design that the site editor doesn't work with the classic block so I'm not quite sure what our options are here. Curious what @youknowriad thinks since you originally opened an issue about the classic block not working in the site editor, leading to it being hidden/removed.

**Comment by Mamaduka** [comment]
Here's a recent attempt to fix Classic block failure in the Site Editor - #48129.

**Comment by bobbingwide** [comment]
Today I re-tested in a different site without plugins and with/without Gutenberg 15.3.1
In both cases the Classic block was converted to Custom HTML.
I'll rerun the original tests.

![image](https://user-images.githubusercontent.com/2474435/223958538-5cecb1c1-9613-49f3-9e2c-07dfe3ebe08e.png)

**Comment by bobbingwide** [comment]
Rerun with/without Gutenberg 15.3.1, the Classic blocks are converted to Custom HTML.

![image](https://user-images.githubusercontent.com/2474435/223961519-93e0c3d6-05e6-4b04-8b15-7353bbfdd4b6.png)

**Comment by Mamaduka** [comment]
Thanks for re-testing, @bobbingwide!
