### ISSUE TITLE
Fatal error on front end: Call to undefined method WP_Theme_JSON::get_custom_css() 

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#48944]
### Description

`Call to undefined method WP_Theme_JSON::get_custom_css() in wp-content/plugins/gutenberg/lib/compat/wordpress-6.2/get-global-styles-and-settings.php:84`

https://github.com/WordPress/gutenberg/blob/0b8f0d9c3201dc502d22c3bf8ab478ce7722755d/lib/compat/wordpress-6.2/get-global-styles-and-settings.php#L84

That doesn't exist in https://github.com/WordPress/gutenberg/blob/0b8f0d9c3201dc502d22c3bf8ab478ce7722755d/lib/class-wp-theme-json-resolver-gutenberg.php

### Step-by-step reproduction instructions

1. Install WP 6.1 branch from https://core.svn.wordpress.org/branches/6.1 @ `r55024` (the latest as of this report)
2. Install Gutenberg 15.3.0 from the plugin repo
3. Activate TwentyTwentyTwo
4. Visit the front end

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.
I think this issue has been fixed in #48648 and backported to Gutenberg 15.3.1. The same problem was reported in [Slack](https://wordpress.slack.com/archives/C02QB2JS7/p1678309615136379).
