### ISSUE TITLE
Categories Block: No text alignment option

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#48940]
The categories block does not have the option to set text alignment, let's add this. Grabbed from https://github.com/WordPress/gutenberg/issues/48443

**Comment by apeatling** [comment]
@mtias or @pablohoneyhoney -- The categories block has text alignment available;

<img width="653" alt="Screenshot 2023-03-09 at 10 08 29 AM" src="https://user-images.githubusercontent.com/1464705/224116873-d9ad02e7-7eb3-4d87-ae33-cee53a6639c6.png">

Were you expecting the Categories List block to have text alignment? It's an unordered list by default.

**Comment by apeatling** [comment]
Clearly missed my coffee this morning -- it has text _alignment_ not text _decoration_!

**Comment by pablohoneyhoney** [comment]
I can’t recall exactly which theme exploration triggered this note. 
But I looked quickly at one and it doesn’t have it. Tags same.

![image](https://user-images.githubusercontent.com/25516611/224320214-bb408a1a-5cf9-4327-8a45-47788d0fe2be.png)

**Comment by apeatling** [comment]
Ah interesting, so it looks related to layout within a group block. I will try this out! Thanks.

**Comment by nathanrodrigues2111** [comment]
Will this be fixed soon ? , This issues shows up when categories are used outside the query block . Currently I am using a class to archive the same which not an elegant solution @apeatling 

![image](https://github.com/WordPress/gutenberg/assets/28552974/1e245723-93d8-4dc2-bf05-1d82ca1288f9)
