### ISSUE TITLE
How to write "__init__.py" in Gutenberg editor

### ISSUE THREAD

**Issue by HuntZou** [WordPress/gutenberg#48957]
### Description

I can not type some special charecters, it alway turn into formatting tag automatically, such as "__init__.py" turn to "init(italicized).py", what should I do to keep it original? backslash doesn't work for me.

### Step-by-step reproduction instructions

1. click "new post" with Gutenberg editor
2. new a "paragragh" block
3. type some thing like "_xxx_" or "*xxx*" etc.
4. once you type right symbol, format changes.

### Environment info

wordpress version: 6.1.1
Site Language: en_US
Server architecture: Linux 5.4.0-126-generic x86_64
Web server: Apache/2.4.53 (Debian)
PHP version: 7.4.29 (Supports 64bit values)
plz let me know if you need more information.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ghost** [comment]
<img width="157" alt="Screenshot 2023-03-09 at 6 37 26 PM" src="https://user-images.githubusercontent.com/118618474/224109833-8c702fd3-bb98-41a5-a607-3bb0bc54450a.png">

That's because of the markdown syntax. You can either wrap it in backtick characters (`) which marks it as code in markdown.

Like `__py__`, or you can use the code block.

**Comment by ghost** [comment]
<img width="184" alt="Screenshot 2023-03-09 at 6 40 08 PM" src="https://user-images.githubusercontent.com/118618474/224110495-74778f9d-72f6-4ee8-a191-9b6125e370ac.png">

Additional info: Also, this doesn't seem to be the case in the latest version of WordPress and Gutenberg, so it might be removed with the next update.
