### ISSUE TITLE
Page attributes 'Template' is missing

### ISSUE THREAD

**Issue by maxxwv** [WordPress/gutenberg#4895]
When viewing a page using the Gutenberg editor, the template selector is not visible in the Page Attributes meta box on the right side of the screen. When using the classic editor, the select is visible as expected.

### classic editor
<img width="298" alt="image" src="https://user-images.githubusercontent.com/23214346/35868278-09339f32-0b2a-11e8-9321-1e7c5e8d8a37.png">

### Gutenberg editor
<img width="295" alt="image" src="https://user-images.githubusercontent.com/23214346/35868291-15e289aa-0b2a-11e8-8ee0-7d8586dda45b.png">

**Comment by karmatosed** [comment]
Templating is a known issue and due to be added in the future. For now closing this as a duplicate #4728

**Comment by youknowriad** [comment]
Also, the template selector (regular page templates) is shipped now.

**Comment by maxxwv** [comment]
Did not know either of those things - thanks!
