### ISSUE TITLE
Small typo in WP 6-2 Site Editor

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/gutenberg#48966]
### Description

https://build.trac.wordpress.org/browser/trunk/wp-includes/js/dist/edit-site.js?marks=8008#L8008
reads:
`description: (0,external_wp_i18n_namespaceObject.__)('Create new template parts, or reset any customisations made to the template parts supplied by your theme.')`

Since source language is US English, customisations should be changed to customizations.

Rel: https://core.trac.wordpress.org/ticket/57895

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

N/A

### Environment info

N/A

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by glendaviesnz** [comment]
[Pull request for this here](https://github.com/WordPress/gutenberg/pull/48976) - but I haven't flagged it as to be backported @annezazu as I think we have a soft string freeze now, so not sure if this qualifies?

**Comment by tobifjellner** [comment]
We are currently only in "soft string freeze" — even some new strings are still getting added. If this correction gets done, then any translation that has already been done will just become a "fuzzy", which will quickly get confirmed. So it can safely be backported.

**Comment by hellofromtonya** [comment]
@glendaviesnz yes, the release is in a "hard string freeze" right now. However, this particular string was introduced in 6.2 and is considered a bug to fix. There is consensus to fix and include in RC2 (which is tomorrow).

Contributors doing translations will get notified of the change in the [Trac ticket]( https://core.trac.wordpress.org/ticket/57895) with the `i18n-change` keyword.

PR #48976 does indeed resolve the issue 👍
