### ISSUE TITLE
The comments block does not apply `get_comments_number` filter to determine what to show

### ISSUE THREAD

**Issue by janboddez** [WordPress/gutenberg#48975]
### Description

The comments title and legacy comments blocks (and a few others) use `get_comments_number()` to get the comment count.

The comments block instead uses `get_comments()` with an `array( 'count' => true )` argument. And will therefore not apply the `get_comments_number` filter.

This is not normally a problem, _but_ it becomes one when a combination of `pre_get_comments` and a meta query is used.

Some context:

I wanted to use a meta query (slow, I know ...) to exclude certain comments from being shown. I was able to use `pre_get_comments` to accomplish this.

However, because meta queries and the `count` argument [do not go well together](https://core.trac.wordpress.org/ticket/52682#ticket) (!), I'll get a bogus comment number.

So I figured I'd overwrite the comment count using a `get_comments_number` filter. This too works as expected ... but the comments block does not use it.

So in the event that the "corrected" comment count is 0, I still see ... a comments block saying "0 comments on ..." instead of just "Be the First to Leave a Comment" or something. (Because the meta fields on a comment _that ought to be excluded_ wrongly count toward the comment number; see the linked trac ticket.)

If the comments block too would use `get_comments_number()` and thus apply the `get_comments_number` filter, just like the legacy comments block, I'd expect this behavior to once again become consistent.

### Step-by-step reproduction instructions

1. In a block theme, ensure the single post template contains a "modern" comments block.
2. Add a filter not unlike the following:
```
add_action( 'pre_get_comments', function( $query ) {
	if ( is_admin() ) {
		return;
	}

	if ( ! is_singular() ) {
		return;
	}

	// Exclude specific comments, when their `my_meta_key`, if it exists, matches 'some-value' or 'another-value'.
	// This unfortunately screw up comment counts. Which we could filter. Except the comments block ignores that filter.
	$query->query_vars['meta_query'] = array(
		'relation' => 'OR',
		array(
			'key'     => 'my_meta_key',
			'compare' => 'NOT EXISTS',
		),
		array(
			'key'     => 'my_meta_key',
			'compare' => 'NOT IN',
			'value'   => array ( 'some-value', 'another-value' ),
		),
	);
} );
```
3. If you had a couple such comments in your database, you'd likely get bizarre counts, resulting in the comments block to always act as if there were comments to show.
4. Use a `get_comments_number` filter callback to "correct" the comment count according to our use case. Watch the comments block output "0 comments on ..." when the "corrected for" count is 0.
5. Switch to (a theme still using) the "legacy" comments block (which we don't want, as it is not editable ...) and watch all pieces fall into place. Correct filter usage, correct (for our use case) comment count, comments block behavior, and so on.

### Environment info

- WP 6.2
- Gutenberg 15.3.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by janboddez** [comment]
Fixing the underlying issue in core might work too :-)

**Comment by janboddez** [comment]
> The comments block instead uses get_comments()

Turns out this is only part of the story. It uses `get_comments()` but its result is only relevant on closed blocks.
(Still, I'd suggest to use get_comments_number() to bring things in line.)

The other thing is the `core/comments-title` block! This one _does_ in fact use `get_comments_number()`! Little did I know that it's supposed to return a `string`. My bad!

**Comment by ndiego** [comment]
Hi @janboddez, thanks for reporting. If I understand this correctly, the "modern" Comments block should use `get_comments_number()` and then this issue would be resolved. Is that correct?

**Comment by janboddez** [comment]
Yes, I'm sorry for making it seem way bigger than that at first. :-)

This was too blunt of a statement of mine: 
> This is not normally a problem, but it becomes one when a combination of pre_get_comments and a meta query is used.

Either way, the "fix" would be to replace [these lines](https://github.com/WordPress/gutenberg/blob/dafb94cbf72ac08d744a06d090db8fb9dc12a8f1/packages/block-library/src/comments/index.php#L32-L38):
```
	$comment_args = array(
		'post_id' => $post_id,
		'count'   => true,
		'status'  => 'approve',
	);
	// Return early if there are no comments and comments are closed.
	if ( ! comments_open( $post_id ) && get_comments( $comment_args ) === 0 ) {
```

... with:
```
	// Return early if there are no comments and comments are closed.
	if ( ! comments_open( $post_id ) && in_array( get_comments_number( $post_id ), array( 0, '0' ), true ) ) { // Or similar ...
```

The tricky bit (which is why I overreacted somewhat) is that `get_comments_number()` returns **a string** (or literal 0 if the post does not exist). Guess a "regular" not-too-strict comparison would work too.

That would bring it in line with similar blocks, too, I think.

The rest of the "description" you can pretty much forget about. Except one thing: It _would_ be nice if core could fix the "count comments when there's a meta query involved" thing.

**Comment by ndiego** [comment]
Awesome, thanks for the clarification!
