### ISSUE TITLE
Menu slides in from left or right

### ISSUE THREAD

**Issue by web-programmer-here** [WordPress/gutenberg#48977]
can the block navigation slides in from left or right? if there is an option to set that.

**Comment by web-programmer-here** [comment]
similar to this
https://github.com/WordPress/twentytwenty/issues/164

**Comment by kathrynwp** [comment]
Hi @web-programmer-here - thanks for the submission. Could you please provide more details explaining your enhancement request? Here's the template for enhancement requests in case it helps you formulate your request. Thanks!

## What problem does this address?

> Please describe if this feature or enhancement is related to a current problem
> or pain point. For example, "I'm always frustrated when ..." or "It is currently
> difficult to ...".

## What is your proposed solution?

> Please outline the feature or enhancement that you want and how it addresses any
> problem identified above.

**Comment by kathrynwp** [comment]
I'm going to go ahead and close this out, but would be happy to reopen it if the issue can be fleshed out more fully, as requested above. Thanks!
