### ISSUE TITLE
Post Editor: List View has no close button on mobile viewports

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#48982]
### Description

On mobile viewports List View doesn't have a close button, so there's probably no way of closing it.

Usually this wouldn't be too much of an issue, as there's no way to open List View on mobile viewports. But if a user has the 'Always open List View' preference enabled, List View fills the whole screen when entering the editor and there's no way to get rid of it, essentially making the editor unusuable

The tabs also look a little buggy visually.

### Step-by-step reproduction instructions

1. Open the post editor
2. Enable the 'Always open List View' preference.
3. Resize your browser to mobile size
4. Refresh

Expected: There's a way to close List View AND/OR List View doesn't show on mobile viewports
Actual: There's no close button and List View fills the whole screen 😱 

### Screenshots, screen recording, code snippet

![Screen Shot 2023-03-10 at 11 55 11 am](https://user-images.githubusercontent.com/677833/224219498-250b43cf-c75b-49a4-9aeb-55912da825b4.png)

### Environment info

Latest WordPress trunk (with or without the Gutenberg plugin active at latest trunk)
Discovered using Brave / Mac OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I think this is a result of https://github.com/WordPress/gutenberg/pull/44788, where a bunch of issues with the implementation were pointed out, but never addressed. Hopefully @jorgefilipecosta can take a look.

**Comment by nomad-skateboarding-dev** [comment]
Hi @talldan !

Question as a mobile only user, please and thank you. 🙂

I've never seen the List View option at all. How does one get it to show?

**Comment by talldan** [comment]
@nomad-skateboarding-dev I think you can only see the List View toggle icon when your phone is in landscape on mobile web. It seems like you can switch to Landscape, toggle list view on, and then go back to portrait and it'll be active in a more usable. At least there is a way to close it now that this issue has been fixed.

**Comment by nomad-skateboarding-dev** [comment]
Thank you kindly! I was aware of landscape view option, so that's good to know I wasn't completely missing something over the past 2 years. 🙂🙌
