### ISSUE TITLE
Site Editor: remove Convert to Classic Block recovery option since it produces an error

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#48991]
### Description

In the Site Editor I loaded a template that contained a block which contained unexpected or invalid content, therefore displayed the Attempt Block Recovery button and more options menu with Resolve, Convert to HTML and Convert to Classic Block.

Choosing **Convert to Classic Block** causes Uncaught Errors in the console.

Uncaught Error: Block type 'core/freeform' is not registered.

Proposed fix: The **Convert to Classic Block** menu item should not be offered in the Site Editor as the block is no longer available.

### Step-by-step reproduction instructions

1. Edit a template to introduce a block that will fail block validation in the Site Editor
2. Open the Site Editor for this template
3. See the Attempt Block Recovery message instead of the block
4. Choose the More options menu ( ... )
5. Choose the Convert to Classic Block item
6. See the Uncaught Error message(s) in the console.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/2474435/224298911-ef75ce46-1290-4bce-88b1-bb31a0568387.png)

### Environment info

- WordPress 6.5-beta2
- Gutenberg 15.3.1

In my scenario I was also using the the oik-blocks plugin to provide the Block info block that failed.
The block fails validation since it contains an `<svg>` tag with a `viewbox` attribute that Gutenberg wants to convert to `viewBox`.

I didn't spend much time looking for an existing bug since it's only recently that the code was implemented to disable the Classic Block in the Site Editor.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment]
Adding this to 6.2 but for 6.2.1 consideration as it would be a great fix to have since the classic block doesn't work in the site editor.
