### ISSUE TITLE
Cannot add Image using Chrome on OSX Sierra

### ISSUE THREAD

**Issue by jasperf** [WordPress/gutenberg#49]
1. go to https://wordpress.github.io/gutenberg/
2. click on image
3. click on image icon presumably to replace or add image
4. editing options close 

OSX 10.12.3 Sierra, Chrome Version 55.0.2883.95 (64-bit)

**Comment by jasmussen** [comment]
Thanks for the report! 

At this point the prototype has mainly been for getting feedback on the look and feel, so the buttons inside the insertion dialog have simply been dummy UI.

**Comment by jasperf** [comment]
@jasmussen Understood. Well, really impressed so far. Can't wait for new functions to start working!

**Comment by jasmussen** [comment]
❤️🎉 

Thrilled you dig it!
