### ISSUE TITLE
Sprintf requires 2 arguments in `gutenberg_block_core_comment_template_render_comments`

### ISSUE THREAD

**Issue by coderaaron** [WordPress/gutenberg#49000]
### Description

`PHP Fatal error:  Uncaught ArgumentCountError: 2 arguments are required, 1 given in /.../wp-content/plugins/gutenbe
rg/build/block-library/blocks/comment-template.php:65`

Line 65 is `$block_content .= sprintf( $inner_content );`

Suspecting this may be caused by PHP changing the function to no longer return `false` on failure (https://www.php.net/manual/en/function.sprintf.php#refsect1-function.sprintf-changelog)

### Step-by-step reproduction instructions

1. Create new post
2. Click "Publish"
3. Get admin error saying "Publishing Failed" or "Updating Failed"

### Environment info

WordPress 6.1.1
Gutenberg 15.3.1
PHP 8.0.26

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aristath** [comment]
Thank you for reporting this @coderaaron!

I added a PR in https://github.com/WordPress/gutenberg/pull/49054 to fix this 👍
