### ISSUE TITLE
get_the_archive_title filter at priority 10 only works when $show_prefix is false in Query Title block

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#49001]
### Description

In my first experience building a block theme, I ran into an issue with the Query Title block.

I used my standard code in an `mu-plugin` to set custom Query Titles (for things like taxonomy term archives where we want something like "2022 Projects" instead of "2022"). However, I found that it did not seem to work at all.

```php
add_filter( 'get_the_archive_title', __NAMESPACE__ . '\better_archive_titles', 10, 3 );
function better_archive_titles( $title, $original_title, $prefix ) {

	$title = $original_title;

	if( is_tax( 'grant-year') || is_tax( 'grant' ) ) {
		$title = $original_title . ' Projects';
	}

	if( 'tribe_events' === get_post_type() ) {
		$title = 'Upcoming Events';
	}

	return $title;
}
```

After looking at the [code for the block](https://github.com/WordPress/gutenberg/blob/c9708b71c649112966c06cfea10f95a4ad911aaa/packages/block-library/src/query-title/index.php#L34), I discovered that the `get_the_archive_title` filter is run at priority 10 only when the "Show archive type in title" option (e.g. `$show_prefix`) is set to `false`:

```php
if ( $is_archive ) {
	$show_prefix = isset( $attributes['showPrefix'] ) ? $attributes['showPrefix'] : true;
	if ( ! $show_prefix ) {
		$filter_title = function( $title, $original_title ) {
			return $original_title;
		};
		add_filter( 'get_the_archive_title', $filter_title, 10, 2 );
		$title = get_the_archive_title();
		remove_filter( 'get_the_archive_title', $filter_title, 10, 2 );
	} else {
		$title = get_the_archive_title();
	}
}
```

This means that Core is inconsistent about whether a `get_the_archive_title` filter call on priority 10 is run or not:

1. In a "classic" theme, it always works.
2. In block theme it works if `$show_prefix` is true. (Tested and confirmed in WP 6.1.1)

This problem can be solved by the theme/plugin by running the filter at priority 11, but this feels like unexpected behavior, and a better solution would be running the block's filter at priority 9.

### Step-by-step reproduction instructions

1. Install an `mu-plugin` with the code:
```php
add_filter( 'get_the_archive_title', 'test_archive_title_priority', 10, 3 );
function test_archive_title_priority( $title, $original_title, $prefix ) {
	return 'Hello World ' . $title;
}
```
2. View a template with the Query Title block and observe that the "Hello World" only appears if the "Archive type" is also visible.

### Environment info

- WordPress 6.1.1
- Twenty Twenty Three child theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I am able to confirm in WordPress 6.2 RC2. Using priority 11 and above works. I am not clear on the implications of why 10 is not permitted here. I assume there are none. @Mamaduka any ideas? If not, this should be an easy fix.

**Comment by Mamaduka** [comment]
I agree. The hook should work with the same priority, no matter the block settings.

I'll try to create a follow-up PR tomorrow.
