### ISSUE TITLE
position setting is not included in the JSON Schema for theme.json

### ISSUE THREAD

**Issue by pbiron** [WordPress/gutenberg#49010]
### Description

In a comment on [Sticky position block support](https://make.wordpress.org/core/2023/03/07/sticky-position-block-support/#comment-44482), @mrleemon pointed out that the new `position` setting is not yet included in the [JSON Schema for theme.json](https://raw.githubusercontent.com/WordPress/gutenberg/wp/6.2/schemas/json/theme.json).

Please add it to the JSON schema prior to the release of WP 6.2.

### Step-by-step reproduction instructions

View the JSON schema and notice that the `position` setting is not included ;-)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kabhamo** [comment]
@pbiron, I hope you are doing great,
I would be so happy to take this issue on my own, can you assign it to me?
Thank you

**Comment by andrewserong** [comment]
Hi @pbiron, thanks for opening this one. I merged a PR a few days ago that adds it to the schema over in: https://github.com/WordPress/gutenberg/pull/48948

**Comment by pbiron** [comment]
Thanx Andrew!  I'll close this now because the merged PR has covered. it.

(I'll make one comment over on the PR, regarding merging into core).
