### ISSUE TITLE
Media & Text block: Remove Image Size controls from image settings.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#49020]
## What problem does this address?

Currently the Image Size controls are very confusing, as they do not actually change the image but changes the resolution.

Example to where the Image Size controls have been replaced with Image dimensions.
The Image block.
![Screenshot 2023-03-13 at 09 38 16](https://user-images.githubusercontent.com/5323259/224649354-df1eea42-57ed-4c4d-8b2b-88f4242dbd9c.jpg)

Shows width and height.
As well as percentage.
Changing any of the above will result in a visual difference which can be seen in the backend and frontend.

Example from Media & Text block.

![Screenshot 2023-03-13 at 09 13 09](https://user-images.githubusercontent.com/5323259/224651033-0cfb0cc7-9342-4eaf-8662-23c5aefc35c3.jpg)

It uses the Image Size drop down controls. Making a change here might not result in any change seen on the backend but the frontend one might see a blurred image if one had selected Thumbnail, medium etc. Even the default Large the image can be blurred on the frontend. I had to tell my client to go to the backend, select the image and in the Image Size drop down change it to Full Size (as I hoped that it would make a difference). The frontend now showed a nice and sharp image.

## What is your proposed solution?

To remove Image size controls from the Image settings inside the Media & Text block. There are resize handles directly on the image. One could add in Image dimension controls, but I am not sure if that is needed.

Somewhat related PR:
https://github.com/WordPress/gutenberg/pull/48478

@jasmussen @aaronrobertshaw

**Comment by jasmussen** [comment]
There's a related conversation in https://github.com/WordPress/gutenberg/issues/48618#issuecomment-1451460526 around standardizing these, but notably improving the verbiage. There seems to be some overlap between 48618 and this.

**Comment by Thelmachido** [comment]
Hi @paaljoachim you might need to further the discussion on the issue @jasmussen mentioned if this is related. I will mark this as a duplicate for now, feel free to add more information if it's necessary to keep this particular issue open.

**Comment by Mamaduka** [comment]
I think we can close this issue.

## Why?

* The image block now uses Aspect Ratio + Width/Height controls, which are better tools for the task.
* The Media & Text (some others) use Resolution controls, this component has better description and context for the users.

## Screenshot
![Image](https://github.com/user-attachments/assets/59f901bc-f8cf-438b-a667-0a2c974cd5db)
