### ISSUE TITLE
Site Editor switches template when window width reduced or increased

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#49038]
### Description

While I was attempting to create an example of Classic Widget import I noticed that when I reduced the width of my window the template that I was editing switched to the front page.
When I re-adjusted the width it toggled back to the original template.

The problem occurs with WordPress 6.2-RC1 and Gutenberg 15.3.1
I do have other plugins activated and a custom FSE theme. 

### Step-by-step reproduction instructions

1. Open Site Editor
2. Add a new template eg page-widgets
3. Add an empty template part
4. Adjust the width of the window down - make it narrower
5. Notice that at some width the contents changes to the default template ( front page )
6. Adjust the window width up - wider and then narrower
7. Notice the contents toggles between the new template and default template ( front page )

### Screenshots, screen recording, code snippet

![site-editor-sizing](https://user-images.githubusercontent.com/2474435/224748468-ad42629e-5432-4475-9927-646c8b2c907e.gif)

A bit fast but it changes from page-widgets to front-page and then back again as I reduce the width then increase it again, then reduce it again.

### Environment info

- WordPress 6.2-RC1
- Gutenberg 15.3.1
- Custom theme: Fizzie
- Other plugins are activated.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by bobbingwide** [comment]
I reproduced the problem with TT3 and a template called `page-widgets` that contains
```
<!-- wp:template-part /-->
```
WordPress: 6.2-RC1 ( multi site )
Gutenberg: 15.3.1 
No other plugins active.

![wp62RC1-gb1531-tt3](https://user-images.githubusercontent.com/2474435/224756511-0f475b4b-f84d-41c6-95a4-4c4cd569b1b2.gif)

**Comment by ndiego** [comment]
I have been able to confirm this in TT3 following the steps above.

cc @Mamaduka @ntsekouras @annezazu

**Comment by annezazu** [comment]
I can only replicate if Gutenberg 15.3.1 is installed. I cannot replicate if it's just 6.2 RC1. 

For replicating with Gutenberg 15.3.1, I made a replay recording (which records the entire browser session) visible here: https://app.replay.io/recording/replicating-issue-49038--bb20f1e7-76d1-4e39-aff1-01059b0186f2?point=76910897249965681088535998507253760&time=27528 If folks would like access to replay to debug, ping me on WPORG slack (@annezazu there) and I can give you access to track down in case this is hard to find the root cause.

**Comment by ndiego** [comment]
Thanks for testing @annezazu. I can confirm that this **does not** occur in 6.2 RC1 when Gutenberg is disabled. I am going to leave it on the [6.2 Project Board](https://github.com/orgs/WordPress/projects/63) and retest once RC2 comes out just to make sure the bug isn't inadvertently included in a backport.

**Comment by Mamaduka** [comment]
Does the template need to be created via UI or as a file inside the theme directory?

**Comment by bobbingwide** [comment]
> Does the template need to be created via UI or as a file inside the theme directory?

I created the template with the UI. Step 2.

**Comment by Mamaduka** [comment]
I can reproduce the bug with Gutenberg 15.3, but not with the current `trunk`. This might be something that got fixed with other URL synchronization issues. See #48731.

**Comment by ndiego** [comment]
I am not able to replicate this use using only WordPress 6.2 RC2. Therefore, I am going to remove this from the 6.2 Project Board.

**Comment by Mamaduka** [comment]
@ndiego, can you replace it with the Gutenberg plugin's latest trunk?

**Comment by ndiego** [comment]
@Mamaduka nope, I do not see the issue with Gutenberg trunk either. So hopefully, this will all be resolved with 15.4 🤞

**Comment by annezazu** [comment]
Closing this out as I cannot replicate with 15.7 at this point! Happy to reopen if others can.
