### ISSUE TITLE
PaletteEdit: ColorPicker popover position can't be changed

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#49040]
## What problem does this address?

When clicking on a color swatch, the ColorPicker popover opens to the left side of the component with a 20px offset. This positioning is coupled to the block editor sidebar and cannot be changed.

https://user-images.githubusercontent.com/555336/224762107-41e59d71-4f62-4c7a-92fb-5b2be0ec292c.mp4

https://github.com/WordPress/gutenberg/blob/a2e91a4ebe3c1b80f32f75b76c688d8e0f1532d5/packages/components/src/palette-edit/index.js#L99-L101

In Storybook, the result looks glitchy:

https://user-images.githubusercontent.com/555336/224762257-1402808a-0ab3-4455-b533-7fddad5f920c.mp4

## What is your proposed solution?

The popover positioning should not be coupled to the block editor.

Related: All the components with the `__experimentalIsRenderedInSidebar` prop.

**Comment by ciampo** [comment]
cc @jorgefilipecosta — it would be great if we could work towards removing the `__experimentalIsRenderedInSidebar` from the `@wordpress/components` package, since it introduces tight coupling with the block editor.
