### ISSUE TITLE
I've downloaded Gutenberg, version 2.1.0. How do I install it?

### ISSUE THREAD

**Issue by csabotta** [WordPress/gutenberg#4906]
I've downloaded Gutenberg from https://wordpress.org/plugins/gutenberg/#developers , version 2.1.0. How do I install it? I'm accessing WordPress via the Just Host provider.

**Comment by maddisondesigns** [comment]
You install the Gutenberg plugin just like any other plugin. If you've downloaded the zip, you can uploaded it via the _Plugins > Add_ New screen, and clicking the `Upload Plugin` button at the top of the page.

Alternatively, go to the _Plugins > Add New_ screen and search for Gutenburg using the Search form (top-right) and install directly from the WordPress.org Plugin Directory.

**Comment by jasmussen** [comment]
Thank you for answering that, maddisondesigns. Closing as addressed.

**Comment by csabotta** [comment]
Yes, thank you for the information. My hosting service provider made the mistake of directing me to the download site for the Gutenberg plugin, which I realized based on your instructions didn't make sense as I don't have permissions to upload plugins to the provider's server.

 The service should have instead directed me to install the plugin from their web site, where it is available. Now I have the plugin installed and am looking forward to trying out the Block feature.
