### ISSUE TITLE
Disable clamp for font-size

### ISSUE THREAD

**Issue by PH4NTOMiki** [WordPress/gutenberg#49080]
### Description

As far I can tell it's impossible to disable using clamp in font-size,

Am I wrong?
And I'm sorry for posting here, but I do think this is an issue because people should be supposed to turn it of it hey don't want it.

Also I bit of a side-note: It would be great to be able to set different settings for different viewports without needing to use Custom CSS

### Step-by-step reproduction instructions

font size setting in Gutenberg editor

### Environment info

WP 6.2 RC1
Edge, Chrome
Win, Linux

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
You can disable fluid typography at the settings.typography.fluid, like this: 

```
"typography": {
	"fluid": false
}
```

Or at the font size preset level in settings.typography.fontSizes: 

```
"fontSizes": [
  {
    "fluid": false,
    "name": "Large",
    "size": "1.3rem",
    "slug": "large"
  }
]
```

It's not currently possible to disable fluid typography if the theme has enabled it (default is `false`)—currently at least.

**Comment by Thelmachido** [comment]
> As far I can tell it's impossible to disable using clamp in font-size,

Hi @PH4NTOMiki there is an open issue investigating opting out of the clamp option for blocks, you can follow and contribute to the discussion [#45502](https://github.com/WordPress/gutenberg/issues/45502)

In the meantime, you can use the CSS option advice above. 

> It would be great to be able to set different settings for different viewports without needing to use Custom CSS

There are a few discussions about breaking points and having a more intrusive design for themes, I would suggest making a comment there to further this initiative. [#27107](https://github.com/WordPress/gutenberg/issues/27107)

I will mark this as a duplicate, please feel free to re-open this with a note if you need to.
