### ISSUE TITLE
Deleting multiple blocks from list view

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#49087]
## What problem does this address?
When selecting multiple blocks from within the list view in the site editor and hitting delete, it doesn't delete those blocks.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1072756/225230161-57b79552-ca82-4b3f-bc0a-e9e466dc3e0f.png">

Another block deleting issue I've run into is that the delete actions seems to only work in certain scenarios. The video below shows selecting a paragraph block below the post content block and hitting delete just selects post content block instead.

https://user-images.githubusercontent.com/1072756/225231362-3c0adcae-ef36-4b69-a943-1743a7da5e7a.mp4

It might be worth looking at both issues to see if there is a singular solution.

## What is your proposed solution?
Selecting a block from list view and hitting delete should always delete the selected block.

**Comment by Thelmachido** [comment]
I am getting the same issue, hitting the `Delete` button on the keyboard doesn't work - the blocks can be removed using more option. 

However, when Gutenberg is deactivated the issue goes away. Additionally, this is only happening when my site is using the TT3 theme when I switch to TT1 everything works as expected. 

<img width="500" alt="Screenshot 2023-03-17 at 14 03 50" src="https://user-images.githubusercontent.com/41231764/225835624-e3a66d7c-0a2c-4a06-bbda-e46ce748686a.png">



WordPress 6.1.1
Gutenberg 15.3.1

**Comment by Thelmachido** [comment]
I'm now able to delete the block using the keyboard delete option @SaxonF please check your site and confirm.

**Comment by jasmussen** [comment]
For what it's worth, the Delete key still doesn't work for me testing trunk this morning:

![delete](https://user-images.githubusercontent.com/1204802/234496643-b609fdd5-4e6f-4a60-8603-42cacdb52fc6.gif)

In the middle of that GIF I'm selecting a bunch of blocks in the list view using Shift + select, then pressing the Delete key, but nothing happening.

**Comment by kevin940726** [comment]
I'm able to reproduce this bug, but I'm not sure which commit broke it (if it used to work before).

However, I noticed that sometimes clicking/selecting blocks in the list view doesn't focus the elements, but instead moves focus to the canvas. I think this is unexpected and could be considered a bug accessibility-wise. My guess is, ironically, this behavior was probably what made pressing "delete" work in the list view before 😅. Maybe some PRs fixed a part of this bug and "broke" this behavior? Just my guess 😆.

If no one is working on this, I can give it a try next!

**Comment by talldan** [comment]
> I'm able to reproduce this bug, but I'm not sure which commit broke it (if it used to work before).

I think the way it worked before was to always transfer focus to the canvas and use the multi-select and delete shortcut features in the canvas.

I don't think there's ever been a shortcut for deleting blocks in List View, but i'd be cool to have.

**Comment by andrewserong** [comment]
> I don't think there's ever been a shortcut for deleting blocks in List View, but i'd be cool to have.

That's my understanding, too. For a fair few of what folks perceive as bugs with keyboard behaviour in the list view, it's more that there are features that haven't been written yet. Definitely fair to think of them as UX bugs, but the Enhancement label feels appropriate to me here, too.
