### ISSUE TITLE
Link UI (<LinkControl>) Overview Issue

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#49091]
This issue captures the current priorities for the Link UI which we are aiming to include in a (near) future release of WordPress.

There's also a longer backlog used to more exhaustively track open issues, bugs, and pending tasks at https://github.com/WordPress/gutenberg/issues/35073.

⚠️ This is not the place to track bugs. Please use [the Tracking Issue](https://github.com/WordPress/gutenberg/issues/35073).

### Design/Visual/UX

- [Different link types for different contexts](https://github.com/WordPress/gutenberg/issues/49107).
- [Users want more controls](https://github.com/WordPress/gutenberg/issues/23011) available including:
	- "No follow"
	- CSS classes
	- ...extension points for 3rd party developers
- UX confusion re: [committing changes to settings/link text](https://github.com/WordPress/gutenberg/issues/45741).
- [No way to close the Link UI](https://github.com/WordPress/gutenberg/issues/47544) - critical for a11y.
- Search results are limited unintuative.

### Technical

- Link relationships are not preserved for WP entity links
	- https://github.com/WordPress/gutenberg/issues/32282
	- https://github.com/WordPress/gutenberg/issues/18345
- Developers want [extension points for adding more controls](https://github.com/WordPress/gutenberg/issues/47820).
- Component implemented (consumed) differently across Gutenberg components and blocks. There should be a standard, unified implementation.
- [Toggling settings resets state of link](https://github.com/WordPress/gutenberg/issues/43144).
- [Determine user intent for links and URL validation](https://github.com/WordPress/gutenberg/issues/38497).
- Remove dependency on URLInput and migrate to standalone implementation.
- Ability to [customise the search suggestions criteria and results](https://github.com/WordPress/gutenberg/issues/31496).

### Accessibility

See [this list](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+label%3A%22%5BFeature%5D+Link+Editing%22+label%3A%22Accessibility+%28a11y%29%22).

## Relevant Resources

- [Link Control tracking issue](https://github.com/WordPress/gutenberg/issues/35073).
- [Recent revision of Link Control UX and Design](https://github.com/WordPress/gutenberg/issues/47310) to include settings drawer and Apply/Cancel buttons.
- Related Issue with [new Design for creating Navigation links using the Link UI](https://github.com/WordPress/gutenberg/issues/48612).
- [Historical Issue with Joen's mockups of suggestions for evolving the Link UI](https://github.com/WordPress/gutenberg/issues/26351#issuecomment-1288816531).
- [Historical Issue with design revisions to Link UI](https://github.com/WordPress/gutenberg/pull/28755).

**Comment by SaxonF** [comment]
Attached some designs below which attempt to consolidate [this](https://github.com/WordPress/gutenberg/issues/47310) and [this](https://github.com/WordPress/gutenberg/issues/48612). 

**Navigation**
 
https://user-images.githubusercontent.com/1072756/225801677-8671c7ff-fae5-48ab-9da6-410acb0ed26d.mp4


**Inline**

https://user-images.githubusercontent.com/1072756/225801724-7a157203-3c20-476d-9bb1-37d6468a21fa.mp4


**Media**

https://user-images.githubusercontent.com/1072756/225801772-02013ad0-a1f9-4906-8102-630e089fd452.mp4

[Figma prototype](https://www.figma.com/proto/YGtfKrRwltLyuEuomOKNiH/Link-Dialog?page-id=0%3A1&node-id=1-435&viewport=484%2C356%2C0.15&scaling=min-zoom&starting-point-node-id=1%3A435&show-proto-sidebar=1)

**Comment by jasmussen** [comment]
Really nice work Saxon, I dig it. 

<img width="482" alt="Screenshot 2023-03-17 at 08 33 31" src="https://user-images.githubusercontent.com/1204802/225841610-b823963c-e939-485e-bfde-6608008c1db5.png">

Do we actually need to show the permalink on the main link? To me the magic of a page is that it'll always link to the Page, no matter if its slug change. We already show the permalink on the subsequent page, so it seems unnecessary to show it in both places:

<img width="507" alt="Screenshot 2023-03-17 at 08 33 45" src="https://user-images.githubusercontent.com/1204802/225841698-db35f262-7d02-49bb-8b72-2092bf31300f.png">

And reducing the text here would not only benefit the information density (allowing more pages to show), but [would benefit dyslexics and others](https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/).

Finally, can we get the page-list tree-structure in there? I feel like it's a real limitation to only show the 3 most recent pages. When you build out your navigation, you'll constantly see those 3 same static pages, even if you have a structure of 20 to build.

**Comment by jameskoster** [comment]
The permalink can be a useful identifier when a search returns different types of content. That said it is kind of doing the same job as the icon. There might be a way to combine?

<img width="443" alt="Screenshot 2023-03-17 at 10 26 46" src="https://user-images.githubusercontent.com/846565/225879209-35fa6842-1b2a-48b3-9a75-84cb0ff13462.png">

I agree that 3 seems like too few, but it's probably unrealistic to display _all_ pages, there could be thousands.

**Comment by jasmussen** [comment]
We can use icons to differentiate there, maybe?
<img width="1133" alt="Screenshot 2023-03-17 at 11 40 48" src="https://user-images.githubusercontent.com/1204802/225882469-969eb92d-3511-4f72-aa85-f80ada2ed6f7.png">

**Comment by jameskoster** [comment]
The tricky thing with icons is that different post types can have taxonomies with the same name. E.g. post categories and product categories. So if you have a "Pizza" _post_ category and a "Pizza" _product_ category, you'd need different icons in this UI to understand the difference, lest you end up with:

<img width="436" alt="Screenshot 2023-03-17 at 12 41 35" src="https://user-images.githubusercontent.com/846565/225907409-ace622df-6144-4c41-a575-00cd226fe513.png">


I can't really see a way for core to cater to all custom taxonomies, and relying on plugins to supply icons could end up getting messy. 

Icons just seem much less scalable / reliable compared with text, but perhaps there's a smart solution for the icon issue that I'm not seeing?

**Comment by jasmussen** [comment]
That's a fair point with regards to search, and if we need further differentiation there (such as slug), that seems fine, but to me the information density of being able to show almost double the amount of pages in the initial page filter seems worth it, no?

**Comment by jameskoster** [comment]
> being able to show almost double the amount of pages in the initial page filter seems worth it

If we aligned the context-chip horizontally with the title then the menu item footprints would be identical:

<img width="829" alt="Screenshot 2023-03-17 at 13 11 05" src="https://user-images.githubusercontent.com/846565/225914335-24e71733-65db-4ff8-b4bb-a2384bffc32d.png">

We might not even need to display the context-chip / icon in the initial view given the 'Recent pages' heading. It's only really important when searching.

**Comment by getdave** [comment]
> Icons just seem much less scalable / reliable compared with text, but perhaps there's a smart solution for the icon issue that I'm not seeing?

I think we will also need to consider the a11y of using an icon alone. Why not combine icon for the "kind" and then text for the specific type? I guess it might be too much?

> If we aligned the context-chip horizontally with the title then the menu item footprints would be identical

@jameskoster for these mockups would it be possible to include a variety of different titles for the results? Speaking from a long experience of working on this component, if we can add some variety it will help us iron out some of the problems that having long titles alongside long category names could expose.

> ....being able to show almost double the amount of pages in the initial page filter seems worth it, no?

We need some way to improve both the quantity and the quality of the results shown but also how these are displayed to the user.


-------

@SaxonF Thank you for the work on these designs. Much appreciated. Here are my thoughts such as they are:

- What does `All pages` do when clicked?
- If a link has already been created _and_ submitted, what is the state when you click on that link _again_? Just want to be sure I'm understand the visuals correctly.
- Related to the above, currently the component fetches "Rich" previews for links which can be very helpful when you have links to external services. How do you see that fit into these designs?
- Link to Media - it would seem nice to show a rich preview of the media in question. This could be aligned nicely with the point above regarding rich previews of links.
- What's the motivation behind moving "open in new tab" outside of the settings? I'm not against it, but is it because you feel it's such a common action hiding it is a bad move? 
- For the settings in the drawer I think we should plan into the design for a slightly more technical description to appear below the "user friendly" description of the setting. I _know_ there will be technical users who will want to know _exactly_ what they are adding to their links (e.g. rel=nofollow) or whatever. 
- FYI I've been thinking a lot about being more strict about what we consider as a URL. Currently if someone types in "socks" then the UI will allow them to create a custom link for socks and under the hood it's turned into `http://socks` which is clearly pointless. I was thinking of making it a requirement that we have at least a tld (e.g. `.com`) or something to indicate that it's a "real" URL in a practical sense rather than a purely theoretical sense (as is currently).
- There's been a lot of confusion with the process of knowing when a link is "submitted". Are we all in agreement that until you hit "Add" (or whatever) no changes to the link are persisted. So if I toggle "Open in new tab" but don't hit "Add" it will be lost. As a result, we will need to make sure that the "Add" button is not active until a change has been made to the link.

**Comment by getdave** [comment]
cc'ing @alexstine and @joedolson for input on the [accessibility of these proposed changes to the design of the Link UI](https://github.com/WordPress/gutenberg/issues/49091#issuecomment-1473053480). As they are currently in [Figma only](https://www.figma.com/proto/YGtfKrRwltLyuEuomOKNiH/Link-Dialog?page-id=0%3A1&node-id=1-435&viewport=484%2C356%2C0.15&scaling=min-zoom&starting-point-node-id=1%3A435&show-proto-sidebar=1), if there's anything we can do to help to make these designs perceivable for you please let us know.

**Comment by joedolson** [comment]
Using only an icon to differentiate between different types of links is going to be very difficult to use, especially on large sites with a lot of taxonomies (as mentioned above.) I don't think it's worthwhile to display more items if the cost is the inability to distinguish which one is right.

**Comment by SaxonF** [comment]
> What does All pages do when clicked?

This should only be visible in navigation block and should add a page list block.

> If a link has already been created and submitted, what is the state when you click on that link again?

It should open this state where you can edit or remove the link, Clicking edit takes you back to the original state, pressing `esc` or input blur should show token again. "Add" action would change to "Save" (or adjust) if you're editing rather than adding.

![image](https://user-images.githubusercontent.com/1072756/226243014-65dfd4bf-2dfe-4574-81a4-fc1ff066abea.png)

> Related to the above, currently the component fetches "Rich" previews for links which can be very helpful when you have links to external services. How do you see that fit into these designs?

Yep we can still show rich previews which would appear below token like we currently do.

![image](https://user-images.githubusercontent.com/1072756/226243471-2c74665a-bf49-4328-9cb6-7cdc32107d21.png)

> What's the motivation behind moving "open in new tab" outside of the settings? I'm not against it, but is it because you feel it's such a common action hiding it is a bad move?

This was based on recent feedback which does suggest it was too hidden for such a common action. @annezazu might be able to link to some of that feedback.

> FYI I've been thinking a lot about being more strict about what we consider as a URL. Currently if someone types in "socks" then the UI will allow them to create a custom link for socks and under the hood it's turned into http://socks which is clearly pointless. I was thinking of making it a requirement that we have at least a tld (e.g. .com) or something to indicate that it's a "real" URL in a practical sense rather than a purely theoretical sense (as is currently).

Some url validation probably makes sense although would there be edge cases to handle? e.g. localhost or #my-div

> There's been a lot of confusion with the process of knowing when a link is "submitted". Are we all in agreement that until you hit "Add" (or whatever) no changes to the link are persisted. So if I toggle "Open in new tab" but don't hit "Add" it will be lost.

I missed some previous discussion around the addition of cancel/save but makes sense to me to only persist once "save" is hit.

**Comment by SaxonF** [comment]
> Finally, can we get the page-list tree-structure in there?

@jasmussen perhaps we show first 10 or so pages based on order? In future we can get smart with what suggestions we show e.g. for inline links default search is the text you've selected.

I'd treat page suggestions as its own isolated task since recent is current behaviour.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/1072756/226246319-03ae79eb-a757-4b5b-a2c1-0f7f011b3ef3.png">

**Comment by jasmussen** [comment]
> perhaps we show first 10 or so pages based on order? In future we can get smart with what suggestions we show e.g. for inline links default search is the text you've selected.

Definitely a separate issue, fine to iterate. But just thinking further ahead, it seems good to figure out whether we eventually show the tree view or always show the most recent items. For a static stie that hasn't had new pages created in a long time, it really feels awkward to see recent pages there.

**Comment by annezazu** [comment]
>This was based on recent feedback which does suggest it was too hidden for such a common action. @annezazu might be able to link to some of that feedback.

I definitely have sent folks to this issue who have mentioned how hidden open new is as a pain point and I myself have run into it! Let me tag in some folks from the WordPress.com side as they can often bring in at scale feedback (including some data that we can't get otherwise) to the project as a contribution. cc @jordesign @supernovia for any insights you can possibly share.

**Comment by supernovia** [comment]
Ah! Now I understand more about why these changes were made. I'm hoping they can be refined a bit. [Here's a wildly popular forum topic on how to make links open in a new tab](https://wordpress.com/forums/topic/how-to-open-custom-html-link-to-open-in-new-tab/). People haven't previously asked support about this terribly often, but they do find that answer 10K+ times every month.  Here's a video I made to show my before/after, if it helps (this video has sound, but you can see the before/after without sound if needed):

https://user-images.githubusercontent.com/3476361/226486987-5f73086c-e38f-4206-a42d-545feb7a3361.mov

From our forums, about this update:

> they make us click an extra button to turn text into a link that opens in a new window. Why? That button only gives us that option. It’s not like there are other things it offers. That button was where the “open in a new window” button had been. Why make it harder to do that?

**Comment by jordesign** [comment]
I have a few qualitative comments from folks running into this change as users on WordPress.com...

> "Yes, Whenever I insert a link, I apply the feature that says open in new window. If I dont apply that, the visitor will click on the link and the linked story will open in the same screen, instead of another.That feature is not available as of today :-("

User effectively thought the feature was removed, rather than just 'moved'


> "I was just trying to update the sidebar on our home page and when I inserted a link - in the PAST it would let me choose if I wanted to have it open in a NEW page. I do NOT see that option now??? Why?"

> "The facility to open a hyperlink in a new tab seems to have disappeared?"

**Comment by getdave** [comment]
Right so we need to consider making the Open in new tab visible at all times. Got it 👍 

Btw this is additional evidence for why we need to consider revisions to the Link UI as a dedicated project rather than ad hoc efforts. That's what we're doing now with this Issue.

**Comment by getdave** [comment]
Some additional design work happened at https://github.com/WordPress/gutenberg/issues/49873#issuecomment-1527312593. We need to unify this with the discovery undertaken here to ensure we're thinking holistically about the Link Creation UI.

**Comment by hz-tyfoon** [comment]
Hey everyone. 

Super excited to share after spending few hours on going through the conversations and understanding the codebase I  created this PR #50401 where a issue is fixed and I believe the UX is slightly better than shown [in the video](https://github.com/WordPress/gutenberg/issues/49091#issuecomment-1477084979) by @supernovia

I demonstrated the fix [in a video](https://github.com/WordPress/gutenberg/pull/50401#issuecomment-1536737951) in & commented it in my PR.

Everyone's review will be highly appreciated 😊. Thanks 🙏

**Comment by getdave** [comment]
## Update

We have [new proposal for a refreshed UX and Design for the Link UI](https://github.com/WordPress/gutenberg/issues/50891). This is to better support the various context in which it is required.

**Comment by richtabor** [comment]
Closing this as most of these linked issues are either completed, or tracked in the LinkControl tracking issue. 

Solid progress. 🚀
