### ISSUE TITLE
Post date block > rename it to Dates to better reflect its purpose !

### ISSUE THREAD

**Issue by Marc-pi** [WordPress/gutenberg#49093]
I was looking for a last modication date block (update date), but it is embed into the post date block !!!

Purpose :  ease Gutenberg onboarding for new adopters, by finding a better name, to better reflect its purpose

![image](https://user-images.githubusercontent.com/919332/225301136-892c6424-b977-47d3-9b1e-e2adedc57f65.png)

Actually : 
* its name is dedicated to Post, but it can be used for Pages !!!
* it is singular, but we can manage both creation vs last modification dates !

Proposal : move from Post date > `Post & Page Dates`
Maybe a shorter version : `Dates` (works also on CPT ??? i did not test)

and change description accordingly

cc @annezazu for FSE Outreach 
since it is a quickwin, i ping @richtabor :-)

**Comment by richtabor** [comment]
Thanks for the ping @Marc-pi. 

While I don't think the block should be renamed—there is an opportunity to add a variation of this block as the Post Modified Time. That way it's easier to discover, and add, to the page. 

I did this in https://github.com/WordPress/gutenberg/pull/49111 ✨

**Comment by Marc-pi** [comment]
@richtabor that's better, end users will be happy ;-) i love quickwins
hope that PR will be validated. Thanks
