### ISSUE TITLE
e2e-test-utils-playwright - installation fails

### ISSUE THREAD

**Issue by Chrico** [WordPress/gutenberg#49096]
### Description

The documentation of e2e-test-utils-playwright in https://github.com/WordPress/gutenberg/tree/HEAD/packages/e2e-test-utils-playwright#installation describes following:

```cli
npm install @wordpress/e2e-test-utils-playwright --save-dev
```

When running this I'm getting following error back:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@wordpress%2fe2e-test-utils-playwright - Not found
npm ERR! 404
npm ERR! 404  '@wordpress/e2e-test-utils-playwright@*' is not in this registry.
```

### Step-by-step reproduction instructions

1. Create an empty folder "test-e2e"
2. create a package.json with:

```json
{
    "name": "test-e2e",
    "version": "1.0.0"
}
```

3. run:

```cli
npm install @wordpress/e2e-test-utils-playwright --save-dev
// or 
yarn add @wordpress/e2e-test-utils-playwright --save-dev
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @Chrico

The Playwright utils package has yet to be published to NPM. See #43998.

**Comment by Chrico** [comment]
Thanks @Mamaduka - I guess we can close this issue since it is "duplicating" #43998. Just wondering _when_ it will be published..seems everything is looking good and multiple different people "accepted" it. 🤔

**Comment by Mamaduka** [comment]
I believe it's mostly ready to be published. Feel free to leave a comment in the PR to encourage folks :)

**Comment by margolisj** [comment]
> I believe it's mostly ready to be published. Feel free to leave a comment in the PR to encourage folks :)

Someone, anyone, hit the button! 😄
