### ISSUE TITLE
Native support vk.com videos

### ISSUE THREAD

**Issue by Arskrigitsioniets** [WordPress/gutenberg#49109]
## What problem does this address?
I'm always frustrated when I can't insert a video from Vk.com in my articles and have to use custom HTML+CSS for this. Vk.com is a Russian social net that is very popular in Russian and CIS countries.

## What is your proposed solution?
It would be nice if WordPress had native support for VK embed videos, like there's now for YouTube.

**Comment by Mamaduka** [comment]
Hi, @Arskrigitsioniets

The request has to be submitted to the [Core Trac](https://core.trac.wordpress.org/). After the embed provider is added to the core, it will be supported in the editor.
