### ISSUE TITLE
[Navigation] Category/Custom taxonomy links are not searchable in the Link inserter.

### ISSUE THREAD

**Issue by costdev** [WordPress/gutenberg#49107]
### Description

Originally reported in [this Trac ticket](https://core.trac.wordpress.org/ticket/57929).

#48740 made the directly inserted block a Page Link block.

However, when searching for categories and other taxonomies such as `product_cat`, these do not appear in the results. This means converting to a custom link, then searching.

This issue follows on from [a discussion about this on Slack](https://wordpress.slack.com/archives/C01KDAZJMQ9/p1678898147608919).

Quoting @jasmussen:
> Rather than revert the default-to-pages, I’d just allow categories to show up when you’re searching.

### Step-by-step reproduction instructions

1. Insert a Navigation block.
2. Click `+`.
3. Search for a category name, like `uncategorized`.
4. 🐞 Note that no category appears, and it's suggested that you create a draft page.

### Screenshots, screen recording, code snippet

From trac:
![image](https://user-images.githubusercontent.com/79332690/225391393-51f91e1b-ba2c-4a3e-8883-09f2164f6d4e.png)

### Environment info

- WordPress: trunk / 6.2 RC2
- Gutenberg: With or without Gutenberg `trunk`.
- Browser: Chrome
- Theme: Twenty-Twenty Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hellofromtonya** [comment]
cc @Mamaduka @ntsekouras @ndiego This bug was reported today during RC. If fixable in time, it can be included in 6.2 RC3. I put it into the 6.2 Project Board.

**Comment by getdave** [comment]
There is no real quick fix solution here other than _not_ defaulting to a Page link (which was recently added) and going back to a Custom Link.

I would recommend we go with that approach.

The Page link variation of the Navigation Link block is set up specifically to return search results that are Pages. In a future release we could explore improving the logic in `fetchLinkSuggestions` to handle providing fallbacks in case a Page isn't available but I wouldn't recommend doing something like that during an RC.

If everyone is ok with it I would vote for rolling back the PR that introduced using Page as the default.

**Comment by draganescu** [comment]
I would also recommend that we revert the defaulting to page and go back to custom link. I agree with the intent behind the change but the change itself is not sufficient, because the way the block works limits searching to the type of the current navigation link variation - and that was a feature!

Changing how all that works is likely convoluted so reverting the change to default to page should be the best step for now.

**Comment by scruffian** [comment]
Created a revert here: https://github.com/WordPress/gutenberg/pull/49126

**Comment by hellofromtonya** [comment]
Thank everyone for quickly assessing and resolving this issue for WP 6.2 RC3!
