### ISSUE TITLE
WP 6.2 RC2 - Site Editor: Flickering on load and refresh. 

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#49114]
### Description

When use the Editor a site, it loads on with a flickering, bouncing motion. 
It is very hard to see in the video. You would need to watch it a few times. You can see the loading spinner for a moment and then the canvas stays in place. 

https://user-images.githubusercontent.com/39980/225426885-d44eb47e-7789-42d6-99d0-50f581abf0ca.mp4

I also tried it with a different variation, see next video: also a white spinner and then a couple white horizontal lines through the right side of the screen. I also noticed a horizontal scrollbar on the bottom of the left, black menu.

There is also some disconcerting animation on the transition from the black to the red. again a bouncy motion. 

https://user-images.githubusercontent.com/39980/225428375-be7d4955-a949-43ac-af9a-8003e4ba5732.mp4

It feels very janky and makes me personally uncomfortable. 

### Step-by-step reproduction instructions

Go to Appearance > Editor 

### Screenshots, screen recording, code snippet

See above

### Environment info

- Use WordPress 6.2 RC 2
- Theme Twenty-Twenty-Three
- Tested with Style Variation Marigold and Blackout

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hellofromtonya** [comment]
@bph Does this flickering happen when the Gutenberg plugin is deactivated?

Does it happen on WP 6.1.1?

**Comment by bph** [comment]
Yes, Gutenberg plugin is not activated. 

In 6.1.1 the Site Editor screen spans the full screen, which is animated on load, but not as but not as prominent. there is no bouncing on the transition from black to read in the sidebar and no additional horizontal scrollbar on the sidebar.

The left black sidebar is new to 6.2.

**Comment by hellofromtonya** [comment]
Thank you @bph. I'm adding this to WP 6.2 Project Board for visibility since the issue was introduced in the WP 6.2 cycle.

@Mamaduka @ndiego if this can be fixed in time, it can be backported to be part of WP 6.3 RC3.

**Comment by Mamaduka** [comment]
I don't think this is a new issue; maybe it's more visible now that edit canvas has a frame.

There's already an issue with improving Site Editor's loading state #35503. Unfortunately, it's not something we can resolve in WP 6.2 cycle.

cc @jameskoster, @tyxla

**Comment by hellofromtonya** [comment]
>Unfortunately, it's not something we can resolve in WP 6.2 cycle.

Thanks @Mamaduka! I've removed it from the 6.2 Project Board.

**Comment by ndiego** [comment]
Sorry, coming in late to this. But I concur with @Mamaduka.

**Comment by ndiego** [comment]
I am going to close this issue in favor of #35503. Refining the loading state will solve this flickering issue, which definitely still exists in 6.2.
