### ISSUE TITLE
wp_kses filters custom block name with consecutive hyphens

### ISSUE THREAD

**Issue by GlaceDream** [WordPress/gutenberg#49127]
### Description

I worked on a WordPress multisite and administrators cannot edit custom blocks containing consecutive hyphens, but only super administrators. This problem occurs after an administrator registers a page containing custom blocks.

I found that the reason was that WordPress filters HTML content (wp_kses) created by an administrator for security reasons. It prevents the use of multiple dashes in custom block name. Ex: "custom-blocks/contact-form---input" is renamed "custom-blocks/contact-form-input".

In my company, we use dashes ("---") in block name to specify the relation between parent and children blocks. This is really helpful for us. Hence my question, would it be possible to allow to put several dashs in the name of the blocks?

**Related issue**
#36339

**Alternative solution**
For the moment, we gave the administrators the capability "unfiltered_html". So they can edit the different blocks.

**Expected behavior**
Allow multiple dashes in block names. Ex: "custom-blocks/contact-form---input"

### Step-by-step reproduction instructions

1. Create a custom block with a block name that includes consecutive hyphens. (e.g. custom-blocks/contact-form---input)
2. Insert this block and save the post.
3. Reload the edit screen.
4. The block is no longer editable. "Your site doesn't include support for the xxx"
5. In this case, the block name displayed in the core/missing block is abbreviated to a single hyphen. (e.g. custom-blocks/contact-form---input)

The bug is reproducible on any site not necessarily multisite. In this case, you need to compare between an administrator and an author.

### Screenshots, screen recording, code snippet

![OnPaste 20230316-102657](https://user-images.githubusercontent.com/48805054/225573533-f8889624-a7a7-4e1d-a7d2-0f1ae28abc5c.jpg)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by skorasaurus** [comment]
Thanks for the detailed report @JeremieLevain . 

This issue is extremely similar to https://github.com/WordPress/gutenberg/issues/36339 and has the same underlying issue so I am closing this issue. 

Please subscribe and follow https://github.com/WordPress/gutenberg/issues/36339 to keep track of its progress.
