### ISSUE TITLE
Site Editor: When Static Page is selected as Front Page, Site Editor loads with Browse mode deep linked to Single Page

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#49129]
### Description

Since Gutenberg 15.3 the default loading state of the Site Editor has changed if the user has their Reading > Front Page settings set to show a static page.

Previously the Site Editor would load with the Browse sidebar (on the left) showing Navigation, Templates, Template Parts.

After 15.3, with a static front page set - the Site Editor now loads with the Browse Sidebar in a state that appears as though it has already gone through the Navigation > Page List > Page steps

### Step-by-step reproduction instructions

1. Make sure your site is set to show a static Front Page (under Settings > Reading)
2. Open the Site Editor (Appearance > Editor

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1842363/225584477-ef2eb1cb-d718-4362-927f-6ba2758a2755.mov

### Environment info

- WP 6.1.1
- Gutenberg 15.3.1 - but also reproduced in 15.4RC1 (thanks @annezazu )

When tested with WordPress 6.2 RC2 - this issue is not present. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @jordesign

This is a known issue and implication mentioned in original PR #48283. The fixing requires shipping changes in WP; this is why it works in 6.2 RC.

**Comment by Thelmachido** [comment]
Since this is a known issue currently being worked on, I will close this as a duplicate. 🙇‍♀️
