### ISSUE TITLE
Issues using backticks to create inline code elements

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#4912]
Authoring text comes with a nice little bit of syntactic sugar. As you type, you can wrap elements with backticks to convert them to code, on the fly. 

There's an issue with a trailing backtick that gets added, though. Steps to reproduce:

- Write some text. Place the caret before a word. Write a backtick.
- Place the caret after the word. Write a backtick and note how the word is converted into a code element.
- Move the caret with the arrow keys, notice how a trailing ` shows up. 

![backticks](https://user-images.githubusercontent.com/1204802/35907206-8373c27c-0bed-11e8-8eb1-7cc6ffde2ecc.gif)

A smaller issue that is perhaps related, you can't convert a word to code if you add the backticks from right to left:

![backticksbackwards](https://user-images.githubusercontent.com/1204802/35907287-c0f096fc-0bed-11e8-892c-ce33363ef395.gif)

**Comment by Soean** [comment]
Related #4642

**Comment by jasmussen** [comment]
Ack, this is a duplicate then. Thank you Soean, I'll close this one and port the images.
