### ISSUE TITLE
Codepen embeds don't work on the frontend, lacks referrer

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#4913]
Steps to reproduce:

- Paste a codepen into the editor. Such as this: https://codepen.io/joen/pen/oEzYxb
- Note how it converts to a codepen embed.
- Publish the post. Run the codepen on the frontend. Note how the codepen won't render on the frontend, citing a missing referrer.

Note that the codepen runs fine in the admin, just not on the frontend.

![codepen embed error](https://user-images.githubusercontent.com/1204802/35907396-17164e00-0bee-11e8-975a-441ae5755842.png)

**Comment by gritdigital-mibu** [comment]
I'm experiencing the same issue @elliotcondon using an oEmbed ACF with a Vimeo video URL.
The AJAX request is not sending a referrer request header so the request is forbidden.

[https://imgur.com/RiWgMcq](https://imgur.com/RiWgMcq)
[https://imgur.com/yLNCy5W](https://imgur.com/yLNCy5W)

**Comment by joaodfmota** [comment]
If remove `sandbox="allow-scripts"` attr from iframe embed it works... But I don't know what part of code adds this attr...

**Comment by aduth** [comment]
Can you clarify whether this is an issue specific to Gutenberg? Seems like a WordPress issue, for which a [Trac](https://core.trac.wordpress.org/) ticket should be created instead. I can reproduce the original result on a site without Gutenberg installed.

**Comment by jasmussen** [comment]
Great catch. This seems to be a general issue. Tracked in https://core.trac.wordpress.org/ticket/44281 and closing this.
