### ISSUE TITLE
[RNMobile] Newly block replaces currently selected block on iOS

### ISSUE THREAD

**Issue by SiobhyB** [WordPress/gutenberg#49145]
## Description

A recent regression on iOS-only causes a selected block to be completely replaced when a new block is added via the inserter.

## Step-by-step reproduction instructions

The installable build at https://github.com/wordpress-mobile/WordPress-iOS/pull/20340 can be used to test the issue on a physical device:

1. Navigate through the steps to create a new post in the iOS app.
2. Type some text into a paragraph block.
3. Tap the inserter in the editor's toolbar.
4. Select a new block to add to the editor.

## Expected behaviour

The new block should be added below the currently selected paragraph block.

## Actual behaviour

The new block replaces the currently selected paragraph block, causing its content to be lost.

## Screenshots or screen recording (optional)

In the following screen recording you can see the paragraph block being replaced by an image block:

https://user-images.githubusercontent.com/2998162/225719668-cda9b2e3-c256-4999-9456-aa4dcc0ce9d4.mov

**Comment by derekblank** [comment]
In testing, I noted that this issue occurs only on text-based blocks where the input is still focused.
For example, if the user is typing in a paragraph block and inserts another block with the text input focused (i.e., not tapping out of the block), the paragraph block will disappear and be replaced by the new block (and the text content is lost). However, if the user types text in any block with a text input (paragraph, caption, quote) and then taps out of the block to blur the input, the content is not lost, and the new block is inserted as normal. Here's an example of that interaction:

https://user-images.githubusercontent.com/643285/225834088-e83388cb-5dad-4451-9893-a789737d5903.mov

**Comment by derekblank** [comment]
I believe the cause of this is something in [`insertDictationResult`](https://github.com/WordPress/gutenberg/blob/43b8db22352871fcfb7dea9a813f0dedc1689bf3/packages/react-native-aztec/ios/RNTAztecView/RCTAztecView.swift#L366-L375) is prompting Aztec to believe there is no text input until the user "finishes" dictating, i.e., taps out to blur the input. This is partially known and has already been discussed on [this thread](https://github.com/wordpress-mobile/gutenberg-mobile/issues/5165#issuecomment-1410257774).

https://github.com/WordPress/gutenberg/blob/43b8db22352871fcfb7dea9a813f0dedc1689bf3/packages/react-native-aztec/ios/RNTAztecView/RCTAztecView.swift#L366-L375

My hypothesis is that `insertDictationResult` is somehow governing how RCTAztecView handles all text input from something in the https://github.com/WordPress/gutenberg/pull/49056 change, and not just when the user is not using dictation. 

I tried to come up with a fix where we could keep the iOS 16 dictation fix from https://github.com/WordPress/gutenberg/pull/49056 but also fix the general text input block insertion issue, which seems like a bigger regression than the original dictation one. Possible ideas would be to keep all of the recent iOS 16 dictation fix code, but isolate it from Aztec for when the user is not using dictation. @SiobhyB has also outlined possible ideas in this comment: https://github.com/wordpress-mobile/gutenberg-mobile/issues/5165#issuecomment-1410257774
