### ISSUE TITLE
Improve Navigation block loading speed

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#49155]
Currently the perceived loading speed of the Navigation block is quite slow. This Issue tracks the Issues/PRs required to reduce that.

- [x] https://github.com/WordPress/gutenberg/pull/48625
- [x] https://github.com/WordPress/gutenberg/pull/49143
- [x] https://github.com/WordPress/gutenberg/pull/48924

**Comment by annezazu** [comment]
Related: https://github.com/WordPress/gutenberg/issues/48045

**Comment by getdave** [comment]
There's been a lot of work on this in 6.3 cycle.
