### ISSUE TITLE
Bad "current-menu-item" on navigation-link

### ISSUE THREAD

**Issue by FlorientR** [WordPress/gutenberg#49153]
### Description

Feature 'is_active' on 'navigation-link' does not work properly.
If i'm on a page that is an archive page on my term with term_id = 10, my navigation link, for my page of id 10 is active.

The bug is here : https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation-link/index.php#L184

I suggest that change 
```php
$is_active   = ! empty( $attributes['id'] ) && ( get_queried_object_id() === (int) $attributes['id'] );
```

to

```php
$is_active   = ! empty( $attributes['id'] ) && ( get_queried_object_id() === (int) $attributes['id'] ) && ! empty( $attributes['type'] ) && ( get_post_type() && get_post_type() === $attributes['type'] );
```

### Step-by-step reproduction instructions

1. Create a taxonomy
2. Create a term on this taxonomy
3. Create a page
4. Create a navigation menu with a navigation link that contains this page
5. Make same term_id and page ID (exemple 10)
6. Go to the archive page of the term_id 10
7. Your menu add "current-menu-item" on navigation-link for the page with ID 10

### Screenshots, screen recording, code snippet

Before change
![before_fix](https://user-images.githubusercontent.com/16555128/225854194-efccdd0a-9481-4d1b-a930-0b4b0114f829.jpeg)

After change
![after_fix](https://user-images.githubusercontent.com/16555128/225854181-1aaffc0f-c877-4514-95cd-4b434e0f6cbd.jpeg)

### Environment info

WordPress 6.1.1
Gutenberg last version for WP 6.1.1
All devices
All browsers
No plugins
FSE full custom theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aristath** [comment]
Thank you for reporting this issue @FlorientR!

I submitted a PR to fix it in https://github.com/WordPress/gutenberg/pull/49195
The code you posted above didn't work for all cases as it was only taking into account posts and wasn't working properly for terms, so I changed the conditions to work for all scenarios, and applied them both to the `navigation-link` and `navigation-submenu` blocks 👍
