### ISSUE TITLE
lockPostSaving not working for new posts

### ISSUE THREAD

**Issue by rpenav91** [WordPress/gutenberg#49172]
### Description

Feature `lockPostSaving` doesn't work for new posts. I'm trying to add custom validations and the publish/update button only works when the post already exists, but for new posts, nothing happens when running the line of code `dispatch('core/editor').lockPostSaving('slug_naming_conventions');`.

### Step-by-step reproduction instructions

Using `npm install @wordpress/scripts` and using this code below

```
const {select, dispatch, subscribe} = wp.data;

subscribe(() => {
// custom logic to define if we need to disable the button
    if (!valid) {
        dispatch('core/notices').createNotice(
            'error',
            'Error Message',
            {
                id: 'slug_exist_notification',
                isDismissible: false,
            }
        );
        dispatch('core/editor').lockPostSaving('slug_naming_conventions');
    } else {
        dispatch('core/editor').unlockPostSaving('slug_naming_conventions');
        dispatch('core/notices').removeNotice('slug_conventions_notification');
    }
});

```

### Screenshots, screen recording, code snippet

Publish button doesn't disables after `lockPostSaving`

![image](https://user-images.githubusercontent.com/3869759/226014947-202631d6-5dfa-43f7-a514-cd6eaaf6ad4d.png)

Running the  code from the browser's developer tools also didn't disable the button when the action is `publish`

![image](https://user-images.githubusercontent.com/3869759/226017079-6b0dfbf2-3839-4c26-8ebb-ca0b4ce233bd.png)

Expected result:

![image](https://user-images.githubusercontent.com/3869759/226018124-738d59e6-b82a-48b3-b3e4-0837c51b9845.png)

### Environment info

WordPress 6.1.1
Google Chrome
Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @rpenav91

I believe this is due to meta boxes being active in the editor. The "Publish/Update" button is permanently active when they are enabled. Here's a related issue https://github.com/WordPress/gutenberg/issues/48808#issuecomment-1468269879.

**Comment by rpenav91** [comment]
Hi @Mamaduka,

But `dispatch('core/editor').lockPostSaving('slug_naming_conventions');` works when the action is `update`, I want that `lockPostSaving` to work on new posts. I don't get the difference between disabling the button when publishing or updating. 

Since in the update action, we are still using meta boxes being active and disabling the button works perfectly.

**Comment by Mamaduka** [comment]
@rpenav91, the "Publish" button opens the "pre-publish" panel by default, where the actual publishing action will be disabled.

If you disabled the "pre-publish" checks (See Preferences -> Include pre-publish checklist), then you'll notice that button is immediately disabled.

So this is the difference; based on your settings, the "Publish" button might not update the post immediately but offer a user set of options before publishing the post.


## Screenshot
![CleanShot 2023-03-21 at 08 48 29](https://user-images.githubusercontent.com/240569/226521445-e4dbb551-b011-4e6c-8618-452c1243804c.png)

**Comment by rpenav91** [comment]
Thanks @Mamaduka the publish button, effectively is disabled on the pre-publish panel, and disabling that pre-publish check now the button it's disabled. Thanks for your efforts and time to this.

**Comment by Mamaduka** [comment]
Happy to help, @rpenav91.

I’ll close this issue.
