### ISSUE TITLE
Add Distraction Free mode to the Site Editor

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#49175]
We have this mode (https://github.com/WordPress/gutenberg/pull/41740) in place for the Post/Block editor — let's also bring it to the Site Editor.

Is there anything that is blocking this from happening today @draganescu?

For reference, here's Distraction Free mode in the Post/Block editor: 

https://user-images.githubusercontent.com/1813435/226064124-040ddbfb-2a35-41c8-839f-b91553a6d627.mp4

**Comment by draganescu** [comment]
I am so glad you opened this issue @richtabor I'll document what is keeping the feature to be easily "enabled" across editors. One of the main blockers is the unavailability of the inserter which I am trying to advance in #44932

**Comment by richtabor** [comment]
> One of the main blockers is the unavailability of the inserter which I am trying to advance in https://github.com/WordPress/gutenberg/pull/44932

Curious. Why do you think the lack of the inserter is a blocker to bring Distraction Free to the Site Editor?

**Comment by draganescu** [comment]
One thing that distraction free mode hides is the in between inserter. In the site editor having to rely on inserting a paragraph to get to the quick inserter is very annoying since it's not a writing flow. We either expose the in between inserter in the site editor (I think we should) or have the inserter available which inserts afaik after the current selection.

**Comment by annezazu** [comment]
I'll also note that folks rely heavily on List View with the Site Editor so I'm wondering if there's some nuance one can have here with either full distraction free mode or distraction free mode with general high level navigation of content with list view.

**Comment by richtabor** [comment]
>  We either expose the in between inserter in the site editor (I think we should) or have the inserter available which inserts afaik after the current selection.

I think it's fine to implement as-is, and keep the experiences the same across both editors. And if someone prefers to use Distraction Free, then they have that option regardless of editor. We'll certainly identify other ideas to improve the experience for sure but it'd be nice to have parity. 

Are there any technical hurdles to explore?
