### ISSUE TITLE
Remove `!important` annotation for duotone filters

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#49171]
With the changes in https://github.com/WordPress/gutenberg/pull/49103, it may be possible to remove the `!important` annotation since ordering is now handled in one place.

We need to investigate if it's still important to make block-level filters (applied via the toolbar in the editor) actually `!important`. The classes generated by color presets, for example, include the `!important` annotation for the `.has-slug-color` classes. And it may be good to follow suit even though dutone classes are not generated the same way.

Global styles (theme.json `styles` section) don't have the `!important` annotation, so at least those cases can have the annotation removed.

See https://github.com/WordPress/gutenberg/pull/49103#discussion_r1137764276

**Comment by scruffian** [comment]
I think this can be closed.
