### ISSUE TITLE
Facebook and Twitter Embed Blocks not working.

### ISSUE THREAD

**Issue by bahiirwa** [WordPress/gutenberg#4918]
## Issue Overview

Gutenberg 2.1.0 
WP 4.9.4

Thanks for the hard work put in. This is my first time testing gutenberg so pray hold me excuse if I do not know how to use the blocks. However, the facebook and twitter block just echo back the link one embeds. On the editor side/backend for twitter block I get a box like feed. But on the frontend and source code only a url gets returned.
For facebook, nothing happens. Check images for experience. What I see embedded on the backend should reflect on home page; that's my expectation. 

Adding youtube link as video embed (Is this misuse of the block?) fires a blank video player. I know this is because of the iframe from youtube code. But non tech people will do this. Can the youtube URl be stripped and properly used to reflect the expectation?

Please leave a comment where I am not clear.

## Steps to Reproduce (for bugs)

1. Install the plugin. 
2. Create new page
3. Add twitter block and insert url https://twitter.com/omukiguy. Repeat the same for facebook - https://facebook.com/laurence.bahiirwa
4. Add youtube link as video embed 

## Screenshots / Video

![guten-1](https://user-images.githubusercontent.com/7713923/35912515-de105180-0c0d-11e8-88fe-2fda50249c4e.jpg)
![guten-2](https://user-images.githubusercontent.com/7713923/35912516-de4748ca-0c0d-11e8-9bd9-e1a872556a7c.jpg)
![guten-3](https://user-images.githubusercontent.com/7713923/35912518-de7de894-0c0d-11e8-9c55-d4c29ac1d4a8.jpg)
![guten-4](https://user-images.githubusercontent.com/7713923/35912519-deb49bb4-0c0d-11e8-9839-686e121c55e4.jpg)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
I am unable to replicate this. This could mean that it's been resolved,  it also may not. If you are still experiencing this please can you report back and we can reopen. For now closing.
