### ISSUE TITLE
Gutenberg stays English on german site

### ISSUE THREAD

**Issue by zettberlin** [WordPress/gutenberg#49185]
### Description

I downloaded and Gutenberg yesterday from WP plugins and installed it.
The site is in German, the profile of the logged in user is also set to German.
Gutenberg shows up in English only.

### Step-by-step reproduction instructions

1.) install GUtenberg on a sites set to none English
2.)see that Gutenberg stays English

### Environment info

WP 6.0.3
Gutenberg: version too hard to be found in GUI, its the one provided yesterday(18.03.2023) from WP plugins

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
Hi @zettberlin I cannot reproduce this issue on my end. I changed my profile and site's language to Deutsch and everything was translated as expected. I did the change in two areas `Benutzer > Profil` for my profile and `Einstellungen › Allgemein`  for my site and I currently only have Gutenberg active on my site. 

I checked on WP versions `6.0.3` and `6.1.1` Gutenberg is translated from what I can see. Is there anything specific in Gutenberg that isn't translated on your end?

<img width="1367" alt="Screenshot 2023-03-20 at 14 22 12" src="https://user-images.githubusercontent.com/41231764/226272678-74e9cc2e-6f1e-4c5b-8f9f-1c1c8eea6a15.png">

<img width="1386" alt="Screenshot 2023-03-20 at 14 24 13" src="https://user-images.githubusercontent.com/41231764/226273052-ea171ff6-d3e4-49e8-b54f-53c7ae33ced2.png">

Environment 
Twenty Twenty-Three theme 
Gutenberg Version 15.3.1
WP version 6.1.1 and 6.0.3

**Comment by t-hamano** [comment]
Hi @zettberlin,

Perhaps the translation files were not downloaded correctly. When you access Dashboard > Updates, do you see a button to update the translation?

![9be061c27b81fc6c780116caecafb5d3](https://user-images.githubusercontent.com/54422211/226355413-b22f048c-710a-420b-99eb-302cb91acc7e.png)

**Comment by zettberlin** [comment]
Thanks for the answers,
I also thought, it could be missing lang files.
My install from the zip file has 35.5 MB with 798 files, is that OK?

Where would I need to check, if the lang files are present?

**Comment by zettberlin** [comment]
@t-hamano I do not have FTP access to the server(ssh only).
Is it possible to get the updates by hand or using https(as in nextcloud)?

**Comment by t-hamano** [comment]
Perhaps this is a locale issue.

For German, you should be able to select the language from the following five options, which one did you choose?

- de_DE: Deutsch
- de_DE_formal: Deutsch (Sie)
- de_CH: Deutsch (Schweiz)
- de_CH_informal: Deutsch (Schweiz, Du)
- de_AT: Deutsch (Österreich)

The Gutenberg plugin's list of translation locales shows that there are five locales for German, with different translation situations.

**Comment by zettberlin** [comment]
Thanks again @t-hamano  but:
 where in Gutenbergs settings can I make that choice?
I searched a lot but to no avail...
So I thought, it would be enough to set site and profile to simply german...

**Comment by t-hamano** [comment]
@zettberlin 

Yes, you should only need to set the language for the site and user profile and download the translation files. One more confirmation, does this issue also occur when the Gutenberg plugin is disabled?

**Comment by zettberlin** [comment]
@t-hamano  the whole site works OK in German, only Gutenberg does not.

Can you give me a link, how to download the translation files and where to install them?

As for wp-edit:
wp-content/plugins/wp-edit/langs

is it similar for Gutenberg?

**Comment by t-hamano** [comment]
The list of translation locales for the Gutenberg plugin is [here](https://translate.wordpress.org/projects/wp-plugins/gutenberg/).

You can download the files by following the links from each locale. However, downloading and applying the translation files is a bit more difficult and is not related to the Gutenberg issue.

Normally, you should not have to deal with the translation files directly. It is important to check exactly what locale is set on the site and how well that locale is translated in the Gutenberg plugin.

**Comment by zettberlin** [comment]
@t-hamano Ok, now I see a little progress but I doubt, that this would be all...
I downloaded the German/formal po-file and put it to wp-content/languages/plugins AND to plugins/gutenberg since I do not know exactly wehre to put it...

Now I have SOME fields translated but most still show up in English:
![Screenshot_20230323_124833](https://user-images.githubusercontent.com/9048260/227195596-14de9893-52dd-4338-a371-31ab1a815229.png)

**Comment by t-hamano** [comment]
@zettberlin 

Can you please review the following to put the issue in perspective?

- Which of the following locales have you selected for your site and user profile?

![deutsch](https://user-images.githubusercontent.com/54422211/227523262-7a801f2f-98ad-4271-bf01-7d23b42e5702.png)

- As I mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/49185#issuecomment-1476245322), have you checked to see if updates to the translation files exist?

- If you change the language of the site or user to something other than **English** or **German**, will all text in the block editor be translated into that language? Don't forget to update the translation files from Dashboard > Updates as well.

**Comment by Thelmachido** [comment]
Hi @zettberlin did you manage to follow up with what was suggested above?

**Comment by t-hamano** [comment]
Hi @zettberlin,

I believe it is unlikely that the Gutenberg plugin is the cause of the translation not being applied only to certain languages. Perhaps the translation has not been completed in the language you selected on [GlotPress](https://translate.wordpress.org/projects/wp-plugins/gutenberg/), or perhaps the translated language files failed to download in your particular environment.

We would like to close this issue but feel free to reopen it.
