### ISSUE TITLE
Categories list block: wrong position of the option text Show empty categories in french

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/gutenberg#49186]
### Description

In the settings of Categories list block, the option Show empty categories is not correctly displayed. See screenshot.

### Step-by-step reproduction instructions

1.Set the French Language in Settings > General.
2.In the editor, add a Categories List Block.
3.Look at the settings.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/75045144/226192006-427a4f4d-92a2-4b72-bd6a-d1a763d63084.png)

### Environment info

- WordPress version 6.1
- Chrome 111 and Firefox 111
- Gutenberg plugin is not installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by talldan** [comment]
> the option Show empty categories is not correctly displayed.

@jennydupuy Thanks for making this issue. In what way is it not displayed correctly? When I change to French it displays as "Afficher les catégories vides".

I'm on a more recent version of WordPress though, so maybe it has been fixed already.

> See screenshot.

It's great if you can include an adequate textual description to keep issues accessible to all.

**Comment by jennydupuy** [comment]
oops I made a mistake on the option. The one that is displayed wrong is "Show only top level categories".
And this option is correctly displayed in 6.2 version of WordPress.

This issue is therefore to be closed.

**Comment by talldan** [comment]
Thanks!
