### ISSUE TITLE
Post Featured Image - Link settings

### ISSUE THREAD

**Issue by dhrumilkumbhani** [WordPress/gutenberg#49193]
### Description

I have found the bug on the Post Featured Image block. i have use that block on site and set the image on features image block and also add LINK REL and test it but this link is not working on block, link redirect on same post URL, not on set URL.

I have created tickets in WP.
[#57096](https://core.trac.wordpress.org/ticket/57096)

### Step-by-step reproduction instructions

1. Go to the edit post.
2. Add the Post featured image block
3. Add the Feature image.
4. go to Link setting and set the Link to Post.
5. Add Link in Link rel.

### Screenshots, screen recording, code snippet

Screen Shot 1:https://www.awesomescreenshot.com/image/34351166?key=fd7b17cff868460301b077536890fbee

Screen Shot 2: https://www.awesomescreenshot.com/image/34350981?key=f9b55d9078ee5b9659a6aba7c5a0ba1e

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@dhrumilkumbhani, the `Link Rel` setting sets the `rel` [HTML attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel) for a block; it doesn't set URL. So you can only link Feature Image to the post it's used for, not any post.

**Comment by dhrumilkumbhani** [comment]
@Mamaduka Got it Thank you for your opinion.
