### ISSUE TITLE
Beta Editor slowdown on Safari when searching for new blocks to add

### ISSUE THREAD

**Issue by astatide** [WordPress/gutenberg#49208]
### Description

Hello!

Using the beta editor on Safari 16.3 on an M1-based MacBook Air running on Ventura 13.2.1, there is a substantial slowdown to the browser tab when searching for a block type to add: it takes a lengthy bit of time for the letters to all appear, and then any search results are slow to come in and have the images load.  I did a search to see if the issue has been reported; I'm sorry if I missed it being reported before!

This is using the existing .com version of the WordPress site, which I think is bleeding edge, so to speak.

There doesn't appear to be anything suspicious in the console, but I'm not sure specifically what is powering the new editor so I'm not too sure where to look. I'm not running any ad blocker that might result in an improperly blocked failed call (although my network does run AdGuardHome)

So far I've tested with Firefox on both Linux (nixOS; unsure of the Firefox version) and the Mac (110.0.1) and the comparison is night and day; it's lighting fast in FireFox on both browsers.  I can also confirm that using Safari on iOS produces the same problem (I assume other browsers would do the same, since they're all forced to use webkit).

I know that Gnome Web uses WebKit; I can try it from there on a Linux machine too, if it would help.

Unsure if it's a webkit issue or whether any custom theme would be a problem here. If it's a duplicate or if I can provide more information please let me know!

(link to original ticket, posted in the wrong place 😂 https://core.trac.wordpress.org/ticket/57917#comment:4)

### Step-by-step reproduction instructions

1. Use new Beta editor .com site from the Safari Browser
2. Click the + icon
3. Start typing!

### Environment info

.com Wordpress, Safari, both iOS and macOS.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Hi @astatide! Thanks so much for opening this and testing. @Mamaduka dug in and wasn't able to replicate outside of a WordPress.com environment so I've opened an issue in the repo for the WordPress.com team to dig in here: https://github.com/Automattic/wp-calypso/issues/74668 You can follow along there. 

For now, let's see too if anyone else can replicate using a self hosted environment!

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub and I see it was also reported upstream. We have been unable to replicate in a self-hosted environment using the latest versions of Gutenberg and WordPress. Therefore, I am going to close this issue. If anyone can replicate it in the future, please feel free to reopen this issue with additional information.
