### ISSUE TITLE
Exploring making the end of the publishing flow more noticeable

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4920]
In the past we have looked at things like adding an image, or other identifications. I'm pulling this out into an issue as have some more user evidence now that the flow is feeling incomplete.

> With the move to JavaScript, clicking the Publish or Update button doesn’t trigger a page reload. Without that visual cue—and with the new two-click publish workflow—just about all of the users we tested were initially unsure of whether their work was really published.

This comes from: https://design.oit.ncsu.edu/2018/02/02/gutenberg-testing/

> Gutenberg requires two clicks to publish, which is already different. After clicking the second button, there’s no page reload, leaving some users unsure of whether it actually published.

Here is the visual flow so far:

![2018-02-07 at 12 17](https://user-images.githubusercontent.com/253067/35916044-f7026be0-0c00-11e8-8817-8302cd67ef6d.png)

![2018-02-07 at 12 18](https://user-images.githubusercontent.com/253067/35916068-0a660f52-0c01-11e8-8d2c-b339fed5c059.png)

There are visual changes but if the above isn't being noticed, what can we do to improve it? I'd love to get some ideas and sketches around this from people.

**Comment by afercia** [comment]
Related: #4187.

**Comment by karmatosed** [comment]
I am closing this as we have a few things added recently and #4187 exists and is open.
