### ISSUE TITLE
Add more spacing to the side of the inserting button

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4921]
The '+' is a little close to the menu panel:

![2018-02-07 at 12 21](https://user-images.githubusercontent.com/253067/35916182-78ef97fe-0c01-11e8-9196-27d442295c4a.png)

It would be good to add a little more padding to this and give the UI some breathing space.

**Comment by mtias** [comment]
We might not be retaining this design for the inserter.

**Comment by karmatosed** [comment]
I think to give it a fair visual shot doing something like an iteration with spacing could be good, but also happy to put to one side / close if we change.
