### ISSUE TITLE
Quote Block: Deleting lines in a quote block leads to an error when selecting with keyboard

### ISSUE THREAD

**Issue by artemiomorales** [WordPress/gutenberg#49217]
### Description

When selecting the contents of a quote block using the keyboard, then deleting, the block becomes invalid and fires an error.

Using Undo, one is not able to retrieve the lost content, though doing Redo immediately afterward will.

The same behavior is not present when selecting with a mouse; in that case, deletion of the Quote block contents is prevented.

### Step-by-step reproduction instructions

1. Add a new quote block
2. Add to the quote block's main content and attribute
3. Select part of the main content and attribution using the keyboard
4. Delete the content

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/5360536/226489441-9589aa35-10b0-4c4c-ba8e-137cd5947f57.mp4

### Environment info

- WordPress 6.1.1, Gutenberg 15.4-rc1
- Chrome 111.0.5563.64
- Mac OSX 12.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
I can reproduce this but it is very fickle.

In some instances, the delete option on my keyboard wasn't working. Clicking on it wasn't removing anything, this might be related to this issue [#49087](https://github.com/WordPress/gutenberg/issues/49087) 

TT3 theme and TT1 theme

**Comment by Mamaduka** [comment]
I can reproduce the issue only when using the keyboard to select the text. Unfortunately, the error stack trace isn't very helpful.

**Comment by ellatrix** [comment]
Interesting that pointer selection doesn't cause the same problem. Investigating now.
