### ISSUE TITLE
Navigation Menu in left panel of Site Editor takes minutes to load and when done Navigation block on canvas gets replaced with error placeholder

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#49231]
## Reproduction

1. Visit a page in the frontend. In a role which has the Admin Menu.
2. In the admin menu click "Edit Site"
   - Note: I use a plugin which only shows the admin menu on hover. Unrelated to reported issue. Mentioned for completeness.
3. My header template part is composed of these blocks:
    - **Group** with ☑︎ Inner blocks use content width
      -  **Row** with justification set to _Space between items_
          - **Site Logo**
          - **Navigation**
            - Note: Menu was converted from a classic menu earlier.
            - Has ca. 40 items in total.
            - Maximum depth: 4 levels: Visible root level → Sub-menu → Sub-menu → Deepest menu item.
  - ✅ All done loading ca 3-4secs after entering Site Editor.
4. In the Site Editors black left menu pane it shows "←  Home  ✏️ " — Back button (left arrow icon), name of the page exemplarily shown in the template editor, edit button (pencil icon)"
    - This is not yet present in WP 6.1 and will be included in WP 6.2 in only about 2 weeks.
    - ❗️ Hence my bug report as a serious warning, that something here is not in order.
5. Click on the "Navigate up" button.
    - This loads the hierarchy of your menu, which can be used to interactively restructure/rename your menu.
    - ❌ But loading this takes 1-2 minutes (!) despite being only ca 40 items total.
    - The moment it is done loading the navigation menu in the Site Editor's left panel the rendered navigation block disappears from the canvas and instead shows an error placeholder `This block has encountered an error and cannot be previewed`.
    - Opening Safari > DevTools > Console shows:

<details>
    <summary>Error: Minified React error # 185</summary>
    
```
[Error] Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. — react-dom.min.js:1:82575
	ar (react-dom.min.js:1:53537)
	(anonymous function) (react-dom.min.js:1:54005)
	tt (react-dom.min.js:1:38846)
	Jr (react-dom.min.js:1:80908)
	Zr (react-dom.min.js:1:80478)
	Gr (react-dom.min.js:1:80012)
	(anonymous function) (react-dom.min.js:1:91514)
	xl (react-dom.min.js:1:92025)
	fl (react-dom.min.js:1:85796)
	fl
	zn (react-dom.min.js:1:32462)
	(anonymous function) (react-dom.min.js:1:92022)
	xl (react-dom.min.js:1:92025)
	ol (react-dom.min.js:1:84540)
	ol
	v (react.min.js:1:3387)
	ce (react.min.js:1:5530)
	(anonymous function) (load-scripts.php:10:16079)
	P (load-scripts.php:10:15887)
	E (load-scripts.php:10:15944)	
```

</details>

## Screenshots, screen recording, code snippet
- Screen Recording: 1m10s, with audio comment
- Note: Long wait time in left panel shortened in screen recording to ca 10secs, but in reality took ca 2min.

https://user-images.githubusercontent.com/737143/226628603-a5f12540-fc11-4297-afea-16fe0de36c9c.mp4

## Environment info

- Wordpress 6.1.1 with plugin Gutenberg 15.3.1
- Safari 16.3.1 on macOS 11.7.4 Big Sur

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
cc, @getdave, @scruffian

**Comment by kathrynwp** [comment]
While I wasn't able to replicate the slow loading time for the Navigation sidebar, I did get the same `This block has encountered an error and cannot be previewed.` error:

<img width="1476" alt="Home_‹_Template_‹_Editor_‹_Testing_Testing_123_—_WordPress" src="https://user-images.githubusercontent.com/7662449/226715036-6026ca57-e625-4d6d-b7aa-9835e0eb9f1d.png">

Tested with:

WP 6.1.1
Gutenberg 15.3.1
Twenty Twenty-Three
No other plugins active

**Comment by Mamaduka** [comment]
I think a similar issue was fixed recently and should ship with Gutenberg 15.4 - #48668.

**Comment by jorgefilipecosta** [comment]
This issue is to the same as https://github.com/WordPress/gutenberg/issues/48668 and was fixed in a PR by @scruffian https://github.com/WordPress/gutenberg/pull/48219. So I expect it not to happen in 6.2  or Gutenberg anymore? Also, for awareness, I think the navigation item is not going yo ship with 6.2.

**Comment by porg** [comment]
Gutenberg 15.4.0 plugin:
- Seems fixed. 
  - ✅ Loading the page hierarchy in the left sidebar took 8secs (better than 2mins!)
  - ✅ When that was completed, the navigation block on canvas remained
- Good that the navigation item is not included in 6.2 b/c it has other remaining issues too.

**Comment by porg** [comment]
@jorgefilipecosta The linked issue in your comment is this very same issue here. You must have mixed up issue numbers.

**Comment by Mamaduka** [comment]
Thanks for the confirmation, @porg! Closing the issue.

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta The linked issue in your comment is this very same issue here. You must have mixed up issue numbers.

Correct I pasted the wrong link I updated my comment 👍
