### ISSUE TITLE
Shortcodes don't work in Hybrid Theme Template Parts (WordPress 6.2-RC2)

### ISSUE THREAD

**Issue by aurooba** [WordPress/gutenberg#49233]
### Description

I'm testing in a hybrid theme that declares support for `Template Parts`. While shortcodes (or blocks that transform shortcodes) work in the Site Editor itself, on the front-end those shortcodes do not get parsed and show up as plain text. I've tested this with the Gravity Forms block, Gravity Forms shortcode, and just [a random shortcode providing plugin](https://wordpress.org/plugins/shortcode-for-current-date/) I found in the plugin repo.

**This doesn't seem to be an issue for block themes, the shortcodes work there as expected**

**I tested with and without the Gutenberg plugin installed, and the result is the same.**

### Step-by-step reproduction instructions

1. Create a template part in a hybrid theme (a classic theme that declares support for template parts)
2. Try adding a shortcode to a template part
3. See the shortcode plain text on the front end.

### Screenshots, screen recording, code snippet

<img width="858" alt="Screen Shot 2023-03-21 at 8 26 33 AM" src="https://user-images.githubusercontent.com/6925260/226637427-c56cba36-bbcf-425b-898a-6092e7a6bda1.png">

### Environment info

=== Environment
- WordPress: 6.2-RC2
- PHP: 8.1.9 (also tested on PHP 7.4.30)
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.1.9)
- Browser: Chrome 111.0.0.0 (macOS)
- Theme: hybridtheme-test
- MU-Plugins: None activated
- Plugins: 
  * Advanced Custom Fields PRO 6.0.7
  * Gravity Forms 2.7.3
  * Imagify 2.1.1
  * Query Monitor 3.11.1
  * Safe SVG 2.0.3
  * Shortcode For Current Date 2.1.7
  * WordPress Beta Tester 3.3.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
Hi, @aurooba

The bug needs to be resolved in the WP core, specifically in the [`block_template_part()`](https://developer.wordpress.org/reference/functions/block_template_part/) function.

Trac Ticket: https://core.trac.wordpress.org/ticket/56780.

**Comment by aurooba** [comment]
Thanks @Mamaduka. I did a search there and didn't find anything (and also..trac is just unfriendly) I appreciate the direct link!
