### ISSUE TITLE
Block copy/paste: Paste missing a snackbar & should it replace or append?

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#49255]
When I select a block and press ⌘C, the block gets copied, highlighted by a snackbar.

There's no snackbar when I paste, making it unclear that it actually worked, because the paste action replaces the block.

Shown in this GIF, successfully copying a post title block. Not visible in the GIF is me pressing ⌘V repeatedly to paste. If you see the list view, the ellipsis blinks, indicating that the block actually does get replaced. But without a snackbar confirming this, it isn't obvious:

![copy paste](https://user-images.githubusercontent.com/1204802/226845893-60518700-1206-4bf5-824f-70c62f754acf.gif)

Outside of the snackbar, I wonder: should the block-level paste action always replace, or should it append? My expectation from other design apps is that it should append. This is different from a partial text selection, where I would expect it to replace.

**Comment by richtabor** [comment]
I don't _think_ we need a paste snackbar—if you can see a result of pasting, though the "copied" snackbar is helpful as there is no other indicator of success. 

But it looks like in the recording, you're technically copying the block—but _pasting_ the block's styling. Copy/pasting blocks and styles are essentially the same action, just dependent on if you're selected on another block or not. 

Here's the same flow, but showing the styles being applied:

https://user-images.githubusercontent.com/1813435/227015117-dc5aa8e6-d9a9-4fee-8210-dfbea0edecbe.mp4

But we do have a snackbar that indicates the result of copying/pasting styles, when you use the "Copy styles" and "Paste styles" controls (which I also don't think is necessary; there is already a visual indication of styles pasted). 

https://user-images.githubusercontent.com/1813435/227016073-f05aa78c-6285-4b55-abe7-d6db633bf42d.mp4

We should consider making "Copy/Paste" aways append (not have the dual function as copying/pasting styles) and maintain a copied snackbar. And perhaps use that same logic for the Copy/Paste of styling (copied snackbar).

**Comment by jasmussen** [comment]
I appreciate your attention to detail and a non-intrusive flow, but in the two videos you shared, it actually wasn't clear enough to me visually that a paste operation was succesful. 

> We should consider making "Copy/Paste" aways append (not have the dual function as copying/pasting styles) and maintain a copied snackbar. And perhaps use that same logic for the Copy/Paste of styling (copied snackbar).

That seems a good starting point, as it would accomodate a clear visual paste operation. But in absence of this, I'd add a paste snackbar.

**Comment by richtabor** [comment]
> I appreciate your attention to detail and a non-intrusive flow, but in the two videos you shared, it actually wasn't clear enough to me visually that a paste operation was succesful.

The pasting I demonstrated was pasting of the styles (the color/font sizes) — not appending a new block. :)

**Comment by jasmussen** [comment]
Oh sure, and although that has some visual effect if the copied block has styles, if it doesn't, you won't know it worked. It's not a strong opinion, but I think snackbars are kinda perfect for this, my main frustration here is that the snackbars linger for so long.

**Comment by richtabor** [comment]
Ah, I'm following now. :) 

> …my main frustration here is that the snackbars linger for so long.

Yes.

**Comment by kevin940726** [comment]
> But it looks like in the recording, you're technically copying the block—but pasting the block's styling. Copy/pasting blocks and styles are essentially the same action, just dependent on if you're selected on another block or not.

Pasting styles actually have a totally different flow though, and the original gif is not that flow.

Seems like pasting a block on another block **always** replaces the original block. The exception is when the user focuses on a rich-text element rather than selecting the whole block. In that case, pasting a block triggers `onSplit` and inserts a block at the desired location. Though it may seem confusing, I think it's behaving as expected. (c.c. @ellatrix in case I'm wrong)

That said, the question in the title is still valid though, and we can discuss more in this issue :).

**Comment by jasmussen** [comment]
I'm going to close this one for now. The issue although pressing at the time doesn't seem to have generated too much discussion so perhaps it's not as glaring after all. We can always reopen.
