### ISSUE TITLE
Site editor: Goes directly into navigation > active page

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#49252]
Steps to reproduce is to just open the site editor. It went straight to the Navigation > Home page drilldown detail page. I would've expected it to go to the top level Design section always. GIF showing this:

![go directly to navigation](https://user-images.githubusercontent.com/1204802/226843714-03c492ff-739a-43f7-a7d2-f14a843961c6.gif)

No errors in the console. WordPress 6.1.1, Gutenberg 15.3.1. Note that the site has a static front page set, but no Front Page template, in case it matters. The Page created to map to the static front page is, in this case, called "Forside".

**Comment by Mamaduka** [comment]
Do you get the same results when  testing with WP6.2 RC?

I think this is expected side effect for 6.1 and older WP versions. See https://github.com/WordPress/gutenberg/pull/48283.

**Comment by jasmussen** [comment]
No, I can not reproduce it in recent versions including trunk. This was purely a moment in time, so if the cause rings a bell, this one can be closed 👌

**Comment by Mamaduka** [comment]
Yes, the cause is the same as mentioned in PR. Fix requires changes in Core, so there not much we can do in plugin.

The issue doesn’t affect WP 6.2.

**Comment by jasmussen** [comment]
Outstanding, now it's filed and indexed, I'll close. Thank you!
