### ISSUE TITLE
Site editor: Animation when exiting edit view to site view occasionally stops, requiring two clicks

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#49251]
In testing a danish website running on 6.1.1 + Gutenberg 15.3.1, I'm seeing an issue where exiting the fullscreen edit view occasionally requires two clicks. GIF showing the animation stopping midways, then requiring another click, slightly cropped for anonymity:

![entering exiting](https://user-images.githubusercontent.com/1204802/226843029-23311144-1bf6-48a1-879e-efc9c36f3b98.gif)

There are no console issues. I'll follow up and see if the issue persists in newer versions.

**Comment by glendaviesnz** [comment]
There were some other issues with this interaction [noted here](https://github.com/WordPress/gutenberg/issues/49276), but they appear to be [resolved in 15.4](https://github.com/WordPress/gutenberg/issues/49276#issuecomment-1480044977). I wasn't able to replicate this issue on 15.4, are you able to double check if you are still seeing it in 15.4 or trunk?

**Comment by jasmussen** [comment]
I've not seen this on trunk, no, so if we can point to a place where the issue was fixed, this one can definitely be closed 👍 👍

**Comment by glendaviesnz** [comment]
It was https://github.com/WordPress/gutenberg/pull/48731 that fixed https://github.com/WordPress/gutenberg/issues/49276, but I was not able to replicate your issue locally so couldn't verify that it is also the fix for this. If you can check either side of that commit that would verify it. I will leave it to you to close this issue if so.

**Comment by jasmussen** [comment]
Let's close for now, and I'll be sure to revisit if I can keep reproducing. Thanks Glen!
