### ISSUE TITLE
Color user interface needs "Cancel" / "Apply" buttons

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#49262]
### Description

When selecting a color, it is NOT obvious for all people, that they must click somewhere else to leave and confirm a made color selection. And, to make it worse, everywhere else in WordPress, clicking outside the current UI means "Leave WITHOUT any change"

And a simple 1 click option to leave without any change does not exist.

So - as in the new Gutenberg link UI - two simple, common buttons like "Cancel" and "Apply" would make everything for everyone clear and easy to use.

### Step-by-step reproduction instructions

1. Add a simple paragraph block
2. Click in the Settings - Sidebar on Color - Background and change something
3. Try to find the "Close color selection without any change" or "Close color selection and use made changes" options as a WordPress newbee or a person who uses a screenreader

### Screenshots, screen recording, code snippet

![grafik](https://user-images.githubusercontent.com/32030147/226864875-df5047ac-7ad4-418f-844f-aa9aa89df48d.png)

### Environment info

WP 6.1.1 (with and without Gutenberg 15.3.1) + WP 6.2 RC 3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
I have this issue here, which proposes potentially adding a — icon to menu items with colors applied. https://github.com/WordPress/gutenberg/issues/42196

**Comment by Thelmachido** [comment]
Since this issue is related to the one mentioned above, I will close this as a duplicate.
