### ISSUE TITLE
Site Logo: Make it possible to set / update / remove via the Inspector

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#49273]
## What problem does this address?
The Site Logo block makes it possible to set a logo or update an existing one, but only via the block toolbar. If you're mid-workflow flicking between the canvas and Inspector this can feel a little unexpected. 

## What is your proposed solution?
Make it possible to set / update / remove the site logo (and site icon) via the block Inspector.

 When setting a site logo initially, we have a new "Media" panel in the inspector:

<img width="1405" alt="Site logo inspector, Setting initially" src="https://user-images.githubusercontent.com/1204802/231723007-2072d0ee-d285-4905-acb6-59b2c896e951.png">

The Add media button would mainly do the same as the "Upload" button in the canvas.

Once an image is set, the file and a small thumbnail is shown in the inspector:

<img width="1405" alt="Site logo inspector, editing existing" src="https://user-images.githubusercontent.com/1204802/231723066-95724a60-4b9e-478d-9eb3-8cc780e6c72f.png">

---

This issue was updated Apr 13.

**Comment by carolinan** [comment]
Is the new position replacing the option in the toolbar, or should the option be in both places?

**Comment by jameskoster** [comment]
I think both. I suspect that you'd _mostly_ interact with the toolbar to do this, but it's an option that would also feel very natural in the Inspector.

**Comment by jasmussen** [comment]
Here's a quick mockup for your feedback. When setting a site logo initially, we have a new "Media" panel in the inspector:

<img width="1405" alt="Site logo inspector, Setting initially" src="https://user-images.githubusercontent.com/1204802/231451160-cde43a1a-06be-4b3f-b0b6-711a4ecaecf4.png">

The Add media button would mainly do the same as the "Upload" button in the canvas.

Once an image is set, the file and a small thumbnail is shown in the inspector:

<img width="1405" alt="Site logo inspector, editing existing" src="https://user-images.githubusercontent.com/1204802/231450867-d8edf435-1321-4662-9e9b-f9a92868427e.png">

In this case, the item opens the dropdown, just like the Replace button does. 

Note that the design of the item, and the reason for calling it "Media", is that we could potentially replicate this panel for Cover and/or Group as far as background images or videos for those blocks. 

Let me know your thoughts.

**Comment by carolinan** [comment]
🤔 should it have a 3 dot menu for opening the additional options? Or is it obvious enough that clicking the miniature image opens these extra options?

**Comment by jasmussen** [comment]
My instinct is that the filename suggests that it's interactive, but we can always augment it with iconography if we find that to be insufficient.

**Comment by carolinan** [comment]
I assume _in the long run_, we don't want inconsistencies; for example, the other media blocks and the file block would need similar settings.

**Comment by jameskoster** [comment]
Seems like a good place to start. Would the 'Add media' button also be a drop zone?

**Comment by jasmussen** [comment]
Yes! That works great!

<img width="1405" alt="Site logo inspector, Setting initially" src="https://user-images.githubusercontent.com/1204802/231721165-55305891-c0d6-4199-ab4b-2189dc6e84fd.png">

**Comment by jasmussen** [comment]
I've updated this issue with mockup and marked it ready for dev.

**Comment by paaljoachim** [comment]
I am adding the comment here to tie in the comment with this issue.

Currently adding background image or video (file or embed) issues have many different solutions. With the common thread that these issues are getting old and have gone no where.

**Expanding** the media option added through this issue to for instance the Cover block and the Group block could be one solution to solving this issue:
**Add Youtube or similar video service using an embed URL in the background of the Cover block**
https://github.com/WordPress/gutenberg/issues/28860
as well as this 
**Group Block - add support for Background Images**
https://github.com/WordPress/gutenberg/issues/14744

I mentioned the Add Youtube video service issue in the Design Slack channel here: https://wordpress.slack.com/archives/C02S78ZAL/p1682152917077289 @jasmussen  happen to mention the issue for the Site Logo adjustment. As well as this:
> Agreed, we need a bit of a generalized interface for backgrounds that can work across cover and groups. I think this seemingly unrelated interface might actually work there, showing the filename in the inspector to provide an “input” for the background.

@ntsekouras Perhaps you could create two new PR's to where we can explore adding a URL for a video service and the other PR for adding a background image to the Group block?

Perhaps for the Cover and Group block when clicking Add media it would not open the Media Library but the drop down instead. Something along the lines of this: 
![Add Media drop down](https://user-images.githubusercontent.com/5323259/235343363-1d7d2ad3-154e-4bb7-931b-3285834577e6.jpg)

Clicking the Add Media button would show the drop down options of going to the Media Library, Uploading or embed URL. It seems like a simple solution for adding a video to the Cover block. The Add Media option in the toolbar would also need to be adjusted.

For the Group block one would then add the new panel Media with the options it contains.
