### ISSUE TITLE
Buggy mouse input event handling: Clicking toggle button opens left sidebar, but immediately thereafter closes it again

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#49276]
## Reproduction
1. The left sidebar of the Site Editor is closed.
2. Move to the top left toggle button with the mouse (on a MacBook Pro trackpad in my case).
3. Click the toggle button
  - ✅ The sidebar reveal animation (which btw is [too slow](WordPress/gutenberg/issues/49270)) starts
  - ❌ Subsequent bug: Immediately after the click the sidebar unexpectedly closes again. With a high likelyhood > 50%.
    - The cause to me seems to be **unclean input event handling**. See details below.

### Step-by-step reproduction instructions

- During a short time frame after the click (max the first 250ms), if there is only slight mouse movement (only hover movement, no click or tap event, I'm 100% sure!) this triggers a close action.
- A few pixels of movement are enough to trigger this.
- This is very likely for two reasons: Because you move towards the toggle button, click,
  - and then might have some remaining micro momentum from moving there,
  - or are already some micro momentum for moving back into the working area again.
- And even no intentional movement at all can cause this!
  - Just lifting the finger (so no intentional movement at all!) may already causes 1-2px of movement getting registered on a high resolution, high sensitive trackpad.
  - This alone is enough to trigger the unexpected closing.

This happens on a MacBook Pro Magic Trackpad (with both the mechanical click and the tap-click active)

### 1a works

https://user-images.githubusercontent.com/737143/226998170-c0784b59-7149-4993-9778-60daf0573fa8.mp4

### 1b fails due to micro movement not even visible

https://user-images.githubusercontent.com/737143/226998226-f45b6c7a-4ce2-4042-859e-7a81e595b77b.mp4

### 1c fails due to minimal unintentional movement after click

https://user-images.githubusercontent.com/737143/226998277-f6b3e5fe-d62d-4837-84a8-ee5aca191274.mp4

### 2a triggered bug - Closed prematurely

https://user-images.githubusercontent.com/737143/226998384-24b1f399-9458-4495-a961-b37b5e1081d8.mp4

### 2b behaved OK - Micro moment came too late

https://user-images.githubusercontent.com/737143/226998477-f8c28952-b890-4bf2-ba50-0f74ea4a7dbe.mp4

### Environment info

- On the stable Wordpress releases, currently WP 6.1.1, I never ever experienced this!
- But with the Gutenberg plugin 15.3.1 I get this.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by porg** [comment]
Gutenberg plugin 15.4.0 → ✅ This bug is fixed!
- The update came just when I finished my long bug report.
- Nevertheless some acknowledgement what was the cause for this would be appreciated. Thanks!

**Comment by porg** [comment]
@glendaviesnz Can you tell what caused this? Was my analysis right (micro mouse hover events triggering this) ?

**Comment by glendaviesnz** [comment]
> @glendaviesnz Can you tell what caused this? Was my analysis right (micro mouse hover events triggering this) ?

It seems like it was [this PR that fixed it](https://github.com/WordPress/gutenberg/pull/48731), it was related to routing issues rather than mouse clicks. Going to close this issue since this is resolved but this PR. Thanks for reporting this.

**Comment by porg** [comment]
I was dead sure this is input related. I could reproduce this. Tried all the different scenarios and managed to record them all on video.

Anyhow, it is gone now. So I don't mind. Should (seemingly) input related troubles regress later, I would report here.
