### ISSUE TITLE
Global Styles Panel: deep link to the block type panel when selecting a block with Styles open

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#49277]
When selecting a block in the site editor with the global styles panel open, the Styles interface doesn't immediately open to that block's settings. This stands in contrast to the experience of the Styles book and adds unnecessary steps to reach the settings one wants. 

Here's a video of the current experience with 6.2 RC3, including showing the Styles book deep linking experience:

https://user-images.githubusercontent.com/26996883/226999996-9e8fdc95-2086-470e-9b54-389094c14550.mov

Pulled from: https://github.com/WordPress/gutenberg/issues/48443

**Comment by richtabor** [comment]
Basically when the Styles panel is open, the same select functionality should occur that we have when Style Book is active.

**Comment by annezazu** [comment]
Correct!
