### ISSUE TITLE
`More` button in toolbar is causing the bar to disappear

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#4927]
## Issue Overview

When clicking the `more` button the bar might disappear.

## Steps to Reproduce (for bugs)

1. Click on the `more` button a couple of times until the bar disappears.

## Screenshots / Video
![more-button-acting-up](https://user-images.githubusercontent.com/2005352/35921260-7e9b69b2-0c1a-11e8-99eb-9fb614004ffa.gif)

## Todos
- [ ] Tests

**Comment by mtias** [comment]
I can't seem to reproduce this anymore.
