### ISSUE TITLE
BlockTypes pattern preview scroll issues

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#49289]
### Description

The "Patterns" popover is acting up when attempting to scroll available patterns.  

### Step-by-step reproduction instructions

1. Add a new page.
2. Add a core/query-loop block
3. Select the block icon.
4. Select the "Patterns" menu item.
5. Try scrolling the popover to see other patterns.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1813435/227040939-5875fc66-83a4-4ca4-bf75-816ed96e0959.mp4

### Environment info

- WordPress 6.2-RC3
- With, and without Gutenberg 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Noting that I can replicate with 6.3.1: 

https://github.com/WordPress/gutenberg/assets/26996883/9d59dbf0-94b1-41fd-b5bf-fe0ec450e423

**Comment by talldan** [comment]
@annezazu Your video doesn't seem the same as @richtabor's. In Rich's the pattern popover becomes completely detached from the toolbar, whereas in yours it looks like it behaves correctly (stays anchored to the toolbar).

I can't reproduce this now, it seems solved.

**Comment by t-hamano** [comment]
The situation has changed a bit from what was originally reported, but the problem still reproduces in my environment.

- The scrollbar appears ((probably only on Windows)) in the editor canvas when opening pattern popover in the query loop block 
- When I scroll in the preview popover, the popover jumps momentarily and returns to its original position.

My guess is that the preview popover height is overflowing internally, and the scrolling operation inside the popover may actually be scrolling the editor canvas.

https://github.com/WordPress/gutenberg/assets/54422211/51092f0e-a5d5-4d7a-940b-93b1c91c7f80

**Comment by t-hamano** [comment]
I've probably found the cause, so I'd like to submit a PR soon.

**Comment by talldan** [comment]
Maybe it's browser specific, that doesn't happen for me.

**Comment by t-hamano** [comment]
@talldan Thank you for teaching me that. In your environment, are you able to scroll inside the pattern popover as expected?

**Comment by talldan** [comment]
@t-hamano Ok, I think I see it now, thanks for helping me understand it, I didn't quite realise there were multiple patterns in the popover 👍 

It seems like the css overflow rules are wrong, so the popover can't be scrolled, and that causes some weirdness with the popover positioning.

I tried a fix here - [Fix scrollbars on pattern transforms](https://github.com/WordPress/gutenberg/pull/55069#top)
