### ISSUE TITLE
Classic Block toolbar shows up empty on insert

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#4928]
Adding a classic block to my post shows a blank toolbar. Clicking inside the block or moving focus brings it back.

Updated to master f598c96 on WP 4.9.4 + Chrome 63.0.3239.132.

![classic](https://user-images.githubusercontent.com/6073772/35921379-bad47d2e-0c1a-11e8-8562-b0c23e80de7e.gif)

**Comment by phpbits** [comment]
Notice this too! Also, the classic block is not saving when toolbar is empty. Thanks!

**Comment by websupporter** [comment]
Additionally:
When you switch to "Edit as HTML" and back, the toolbar is empty.

**Comment by ajitbohra** [comment]
Works as expected on master / v3.2
