### ISSUE TITLE
Site Editor: Endless scrolling in zoom out and style views when there are blocks with vh units

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#49299]
Might be related to [this comment](https://github.com/WordPress/gutenberg/issues/49120#issuecomment-1480614237)

### Description

If the content contains blocks with a height in units of `vh`, there will be endless scrolling in both the zoomed-out and style views. This problem occurs when the block has a large value, such as `100vh` high. iframe editor content will infinitely grow in height.

### Step-by-step reproduction instructions

- Activate "Zoomed out view" from the Gutenberg > Experiments menu.
- Open the site editor.
- Insert a group block in one of the templates.
- Set min.Height to `100vh` from the Dimensions panel.
- Click the "zoom out" view button or access "Browse styles" menu.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/227163677-3bc7d832-8303-44b9-a65f-2b6b71ed2a12.mp4

### Environment info

- WordPress Version: 6.3-alpha-55582 
- Gutenberg Version: Latest trunk (15.4.0)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
We fixed a similar bug for Block Previews in WP 5.9. See #38175.

**Comment by richtabor** [comment]
Sharing that I'm also seeing this: 

https://user-images.githubusercontent.com/1813435/236936041-ff296ac9-7003-4a7f-a9d8-b2e2d4c75f20.mp4

**Comment by MaggieCabrera** [comment]
Should be fixed by https://github.com/WordPress/gutenberg/pull/59334, can you still reproduce?

**Comment by t-hamano** [comment]
I've confirmed that this issue has been fixed intrunk, so I'm closing it.

https://github.com/WordPress/gutenberg/assets/54422211/95d79d64-8c15-48cc-9664-445a73fb3acd
