### ISSUE TITLE
Introduce a Next Page Block to allow post pagination

### ISSUE THREAD

**Issue by felixarntz** [WordPress/gutenberg#4930]
## Issue Overview
In the classic editor, you can insert a `<!--nextpage-->` comment to break a post into multiple pages. This should be supported in Gutenberg as well and be possible in an intuitive way.

## Expected Behavior
It should be intuitive to add pagination functionality to a post.

## Current Behavior
You can currently insert the comment manually in the HTML view, and it technically works because of existing core logic. However it's not possible to create that in a user-friendly way, and is not visually reflected in the editor when the comment exists.

## Possible Solution
There should be a "Next Page" block that takes over that functionality. Existing `<!--nextpage-->` comments could be autoconverted to that.

## Related Issues and/or PRs
#983 (similar approach for the more tag)

**Comment by gziolo** [comment]
See https://github.com/WordPress/gutenberg/pull/1467 - @swissspidy made some progress on this one. It would be nice to continue this work.

**Comment by mtias** [comment]
This seems to have been closed before https://github.com/WordPress/gutenberg/issues/1328 (should not be).

**Comment by mtias** [comment]
Also, we'd want to do it like this in advance: https://github.com/WordPress/gutenberg/issues/2973

**Comment by swissspidy** [comment]
Ah right, @gziolo asked me about that. I knew there was an email I forgot about! :-)

I'm happy to continue working and to collaborate on #1467 if there's interest. Closing issues and then reopening them months later is confusing…

**Comment by gziolo** [comment]
I'm removing `Stale` label in that case from #1467 :)

**Comment by mtias** [comment]
@swissspidy I think this one was just closed by mistake as "new block" tickets were moved into a project, but the blocks that match existing functionality should be kept open. Sorry about it :)

**Comment by mcsf** [comment]
Closed via #1467
