### ISSUE TITLE
Do not check uncategorized by default

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4931]
There is a core issue for this: https://core.trac.wordpress.org/ticket/36228. However, we can fix it now in Gutenberg, so let's do just that.

Time and time again users are not realising it's checked and posts are going up with the 'uncategorized' category. On top of that, if you don't want it as a category (the question rises who does want it), you then have to uncheck it. That's not a good experience.

**Comment by chthonic-ds** [comment]
Related https://github.com/WordPress/gutenberg/issues/4627

**Comment by StaggerLeee** [comment]
Finally. Taking care of it.

**Comment by ntwb** [comment]
FYI: Ticket [#WP36228](https://core.trac.wordpress.org/ticket/36228) was closed as a duplicate of [#WP14901](https://core.trac.wordpress.org/ticket/14901)

**Comment by danielbachhuber** [comment]
I think it makes more sense to replicate core's existing behavior in Gutenberg.

While the UX is less than ideal (I've personally set my default category to `Categorized`), I don't think it's worth the effort to try and remove the concept of default categories in core.

**Comment by karmatosed** [comment]
I do not agree @danielbachhuber and this could vastly improve the user experience.

**Comment by karmatosed** [comment]
Let's put this one in ideas for now and close for version one.
