### ISSUE TITLE
Code Editor gets context aware and when opened reveals markup corresponding to currently selected block

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#49310]
# Current situation

## Edit as HTML — 👍 Shows markup for the selected block directly on canvas

https://user-images.githubusercontent.com/737143/227242274-06b1b57c-1016-4e11-902c-7d2e5e127ae1.mp4

## Code Editor `⇧ ⌥ ⌘ M` — 👎 Currently not context aware — Always opens on top

https://user-images.githubusercontent.com/737143/227242315-a7aa05f2-1685-4b0b-a239-26e01f727302.mp4

# Proposal: 💡 Code Editor gets context aware!

- If there is/are a currently selected block(s)
- Triggering the Code editor via:
  - block context menu
  - global more menu
  - shortcut (`⇧ ⌥ ⌘ M`)
- Opens the Code Editor and highlights the relevant markup (all lines or start of block)

https://user-images.githubusercontent.com/737143/227245366-62581bd7-4c53-4d70-b91c-d34d4e3b767c.mp4

**Comment by carolinan** [comment]
I would love this feature, it would save me a lot of time when editing my content. The code editor view can sometimes be overwhelming to scroll through and it is not always easy to locate the block you want to edit.

**Comment by porg** [comment]
## Until that feature gets implemented (if ever)

- If you often need to inspect WordPress markup you may find this helpful:
- The free plugin [EditorsKit](https://wordpress.org/plugins/block-options/) offers [syntax highlighting of WordPress markup](https://wordpress.org/plugins/block-options/#:~:text=Code%20Editor%20Mode%20Syntax%20Highlighter) within Gutenberg's **Code Editor** environment:

![Block Editor Syntax Highlighting from plugin EditorsKit](https://ps.w.org/block-options/trunk/screenshot-8.png?rev=2895883)

**Comment by Mamaduka** [comment]
Thank you, @porg.

I think this might be a duplicate of #26738.

A general discussion regarding the syntax highlighting - #10423, #17017.

**Comment by porg** [comment]
Closing.

**Comment by porg** [comment]
- Closing my issue in favor of the elder:
   #26738
   which covers the essence + also has a [good mockup video](https://github.com/WordPress/gutenberg/issues/26738#issuecomment-725714631) by @mapk which performs the context-aware opening of the code editor (jumps to markup and selects it which corresponds to the selection in the GUI)
- [Added link/screenshot of EditorsKit](https://github.com/WordPress/gutenberg/issues/10423#issuecomment-1639917648) as an existing 3rd party WP syntax highlighting plugin to:
  #10423

**Comment by Mamaduka** [comment]
Thanks again for contributing, @porg!
