### ISSUE TITLE
[Block] Navigation - Equip Submenu parent items with typography styles

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#49319]
## What problem does this address?
When working on menu items in a navigation block, you can add individual styles to each menu item using Styles > Typography. But if you convert a styled menu item to a Submenu, those styles and tools are removed.

Reported here: https://github.com/Automattic/wp-calypso/issues/74016

https://user-images.githubusercontent.com/27249804/227380965-d75c0859-66ce-4bca-a493-5b154eede651.mov

## What is your proposed solution?
Provide the same Typography tools available for menu items to Submenu blocks as well.

**Comment by annezazu** [comment]
I can still replicate this with WordPress 6.6.1 and Gutenberg 19.1:

https://github.com/user-attachments/assets/0b054ed6-3b9d-429d-9b17-bcec94811743
