### ISSUE TITLE
Validation for UseOnce blocks when switching from code to visual

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#4932]
## Issue Overview
I can add multiple instances of a `UseOnce` block to a post by copy-pasting in the code editor. They don't get removed when switching back to the visual editor (or when publishing the post).

## Steps to Reproduce (for bugs)
1. Start a post
2. Switch to the code editor
3. Add a Read More block via the inserter (after this it won't allow me to add a 2nd one this way, so that's good)
4. Copy-paste the block tag several times
5. Switch to the visual editor and see multiple Read More blocks with no warnings or notices

Gutenberg 2.1 + WP 4.9.4

## Expected Behavior
To run validation when switching back from the code editor to remove the extra blocks, or show some sort of notice.

Pinging @mcsf as we discussed this during the core-editor chat.

**Comment by mcsf** [comment]
@hedgefield, have a look at #5031, let me know what you think.
