### ISSUE TITLE
Revert new website editor experience

### ISSUE THREAD

**Issue by scrobbleme** [WordPress/gutenberg#49336]
## What problem does this address?

The new experience is:

- (again) totally different from the previous one (why?)
- even worst: totally cumbersome
  - why is everything moving and jiggling around? all this transitions…

## What is your proposed solution?

- revert to the old experience, it was stable, quite fast and straight forward…
- stick to some pattern and improve this, instead inventing something new every couple of months

**Comment by Thelmachido** [comment]
> even worst: totally cumbersome why is everything moving and jiggling around? all this transitions…

Hi @scrobbleme are you able to provide more information about what you are referring to exactly? It would help to know what is not working properly on your end.

**Comment by scrobbleme** [comment]
@Thelmachido Yes, of course.

I'm using the website editor every week, currently nearly daily... 
I've attached two short videos... it is obvious (at least for me) that the new experience just feels bad, slow, sluggish, effect-overloaded... (why is the main window always zooming in and out?)

Another thing, in the original experience you could just click "templates" and got a list containing all important information about templates (author, was it changed (the blue bubble), parent/child theme...) now, you have a very subtle list without any information at all. No real benefit of this.

https://user-images.githubusercontent.com/504835/227742538-e66c05ad-5d1a-4c97-ac46-e4c6782458be.mp4

https://user-images.githubusercontent.com/504835/227742540-27c26c43-be5f-4625-875b-3e61305b0e94.mp4

**Comment by glendaviesnz** [comment]
Related issue here about [sluggish animations](https://github.com/WordPress/gutenberg/issues/49270)

**Comment by scrobbleme** [comment]
I'm closing this in favor of #49270
