### ISSUE TITLE
Color Panel: popover opens in incorrect position

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#49349]
As reported in https://github.com/WordPress/gutenberg/pull/48893 by @jasmussen, @andrewserong , @aaronrobertshaw  and @youknowriad , the popover can sometimes open in the wrong position

https://user-images.githubusercontent.com/1083581/227600788-62bf6a8f-7a9b-469a-80f3-cbccfa61e987.mp4

https://user-images.githubusercontent.com/1083581/227600833-ffb647e3-6cd5-43a8-986d-f5bcf3e88180.mp4

**Comment by ciampo** [comment]
As reported in https://github.com/WordPress/gutenberg/pull/48893#issuecomment-1481777657, it seems that it happens only when the popover contains a tabbed interface (e.g "Solid" and "Gradient" tabs for the background color, or "Default" and "Hover" tabs for the "Link" color). Maybe this could help to narrow down the issue.

For more context, the `Popover` in question is part of the `Dropdown` component. The `Dropdown` component should set the `anchor` for the `Popover` component (the anchor should be the individual item group).

**Comment by youknowriad** [comment]
If it happens only for the tabbed interface, I'm guessing that maybe the "width" of the popover is not right (probably 0) at the time the position gets computed causing the wrong position. So some kind of race condition where we don't update the position based on the right width properly.

**Comment by ciampo** [comment]
#49368 seems to have fixed this issue, closing now
