### ISSUE TITLE
possible regression in 6.2 for getBlockAttributes()

### ISSUE THREAD

**Issue by pbiron** [WordPress/gutenberg#49379]
### Description

I've got a custom dynamic block, that is within the `innerBLocks` of another custom block.  In the `edit()` method of the child block  I do

```
const parent     = select( 'core/block-editor' ).getBlockParentsByBlockName( clientId, 'my-plugin/my-block' );
const { myAttr } = select( 'core/block-editor' ).getBlockAttributes( parent );

```

`clientId` is the clientId of the child block.

 The above is used to get an attribute from the parent block to decide how to render the child block in the editor (on the front-end, the dynamic block is rendered completely via PHP).

This has worked since ~5.8, including in 6.1.1.  However, it no longer works in 6.2-RC4.

The `getBlockParentsByBlockName()` returns an array of clientIds, which in this case, only has a single item in it (the clientId of the parent custom block).

In 6.1.1 and before, `getBlockAttributes()` seems to accept an array as param and it returns the attributes of the 1st item in the array.

However, in 6.2-RC4 (may also happen in other 6.2 betas/RC, I haven't had a chance to check yet), it is returning `null` when passed an array.

If I change my code to:

```
const parent     = select( 'core/block-editor' ).getBlockParentsByBlockName( clientId, 'my-plugin/my-block' );
const { myAttr } = select( 'core/block-editor' ).getBlockAttributes( Array.isArray( parent ) ? parent[0] : parent );

```

it works in 6.1.1 and 6.2-RC4.

The [current documentation](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-block-editor/) for `getBlockAttributes()` clearly documents that it only accepts a string and not an array.  I don't know when that changed.

I don't know if this is a regression or whether my original was never supposed to work but "just happened to".

### Step-by-step reproduction instructions

1. In WP 6.1.1, pass an array containing a single clientId to `getBlockAttributes()` and see it returns an object with the attributes of the 1st item in the array.
2. In WP 6.2-RC4, pass an array containing a single clientId to `getBlockAttributes()` and see it returns `null`

### Environment info

WP 6.1.1 and WP 6.2-RC4, without Gutenberg active.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by pbiron** [comment]
[In Slack](https://wordpress.slack.com/archives/C04JZ199XPG/p1679940655789599?thread_ts=1679938479.322519&cid=C04JZ199XPG), @hellofromtonya asked:

> Maybe something from [this refactoring](https://github.com/WordPress/gutenberg/commit/52f10da01ae4ada5e87514e8f862034af708602b), .i.e. in the .get()?

I think she may be correct.

Here's a screenshot of me single stepping thru the call to `getBlockAttributes()` in Chrome's JS debugger in WP 6.1.1:

![6 1 1-js-debugger](https://user-images.githubusercontent.com/3824560/228052034-476c6109-24b6-4495-825d-4d7b809dd6db.png)

Notice 2 things: the `clientId` passed is an array and `block` is non-null (i.e., `state.blocks.byClientId[clientId]` did return the block even tho an array was passed to the function).

And here's a screenshot of the same point in the execution of `getBlockAttributes()` in WP 6.2.RC4:

![6 2-RC4-js-debugger](https://user-images.githubusercontent.com/3824560/228052696-baae010b-88eb-4c2e-8149-17e77e2ba2a9.png)

where an array was also passed, but now block is `null` (i.e., `state.blocks.byClientId.get(clientId)`  returns `null`).

So, it seems like in 6.1.1 (and before), JS was doing some type coercion in `state.blocks.byClientId[clientId]` that no longer happens in 6.2-RC4.

I suspect this is a case of "no one thought that my original code **should have worked**, so it may not be correct to call this a `regression`, but it is certainly different behavior.

**Comment by pbiron** [comment]
And as confirmation that JS does do implicit type coercion of an array to the first item in the array when an array is used as the index into another array (that's a mouthful), type the following into the JS console in your favorite browser

```
const myArray = [123];
const myValue = myArray[[0]];
console.log( myValue ); // echos 123 to the console
```

So, definitely a case of `_doing_it_wrong()` in my original code, in a way that just happened to work before the refactor in the implementation of `getBlockAttributes()` in 6.2.

**Comment by hellofromtonya** [comment]
Summary of the [discussion in Make/Core slack](https://wordpress.slack.com/archives/C04JZ199XPG/p1679938479322519):

* The `getBlockAttributes()`'s parameter is documented as `string` and has been for years.
* Though `array` may have worked in the past, it was unintended, i.e. not designed to work.
* Given that it is clearly documented as `string`, passing an `array` is `_doing_it_wrong()`.

@pbiron noted:
>I tend to agree.  and I do have a fix for my broken code

[and](https://wordpress.slack.com/archives/C04JZ199XPG/p1679949004669419)
>it was a case of my code `_doing_it_wrong()` in a way that just happened to work prior to 6.2 because of JS doing an implicit type coercion that no longer happens because of a refactor in  :gutenberg:  code, so all is good

Thank you @pbiron for reporting, discussing, and helping to assess.
