### ISSUE TITLE
Other kinds of ordered lists

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#49380]
## What problem does this address?

The only type of ordered list is numbered.

<ol type="a">
<li>But not this</li>
<li>or this</li>
</ol>

<ol type="A">
<li>Or even this</li>
<li>or this!!</li>
</ol>

<ol type="I">
  <li>bet you didn't think this was possible</li>
  <li>and yet the difference is a single character HTML attribute</li>
  <li>foobar</li>
</ol>

All it takes is a `type` attribute:

```html
<ol type="a">
    <li>Foo</li>
    <li>bar</li>
</ol>
```

Which is passed to the tag but it's used to determine if a `ul` or an `ol` should be used.

## What is your proposed solution?

Add an extra button to the toolbar for ordered lists with a 1/A/a/I selector.

There's already a sidebar inspector option for the starting number, and I would register a block style but sadly unless I want unordered graphics or images this isn't a CSS thing, it's a HTML markup thing.

**Comment by skorasaurus** [comment]
Thanks for reporting; this is being requested and discussed in https://github.com/WordPress/gutenberg/issues/17738.

**Comment by tomjn** [comment]
Noting that someone has pointed out that `lower-roman` is a valid value for the list parameter so this _can_ be done with CSS and block styles!
