### ISSUE TITLE
Editing a page that has a Spacer block with an HTML Anchor produces message “This block contains unexpected or invalid content.”

### ISSUE THREAD

**Issue by jpjfox** [WordPress/gutenberg#49382]
### Description

Our website has pages that contain Spacer blocks with HTML Anchors defined. The site has been working for months with this design. Last edits were done in October 2022. Now when I try to edit these pages every one of these Spacer blocks shows the error message “This block contains unexpected or invalid content."

If I choose "Attempt Block Recovery" the Spacer block is restored, but without the anchor. I can then manually add the anchor back, save the page, and all is good... until some future date when a subsequent page edit shows this error again. (What I mean by 'future date' is that I encountered this problem in January 2022, rebuilt the Spacer blocks with Anchors, and everything looked good. The next round of edits in October 2022 worked fine. Then in March 2023 the Spacer Blocks with Anchors choke again when I edit these pages.)

There is no apparent difference in the HTML code generated to specify the anchor between January 2022 and now, but the editor chokes on processing the existing code, then allows adding the Anchor to the Spacer and generates the same code. My expectation is that the existing Spacer does not produce any “This block contains unexpected or invalid content" errors.

### Step-by-step reproduction instructions

Steps to reproduce:
1. Edit an existing page that contains a Spacer block with an HTML Anchor. If the page was last updated over 4–5 months ago the Spacer blocks with Anchors will trip on this error, but if the page was recently edited and saved this error won't occur.
2. Error shown when existing page is edited: 
![Spacer-Anchor (1)](https://user-images.githubusercontent.com/92945757/228053435-aeeb68f7-bf4c-4d45-b0f5-170c61ea828e.JPG)
3. HTML code after "Attempt Block Recovery" chosen:
![Spacer-Anchor (2)](https://user-images.githubusercontent.com/92945757/228053762-a03a9741-5bf1-4ba1-977a-cb974bba46fc.JPG)
4. HTML code after recovered Spacer edited to add the same HTML Anchor that was dropped by recovery:
![Spacer-Anchor (3)](https://user-images.githubusercontent.com/92945757/228054014-a75b3280-2537-4839-bc42-eb59d846d2f7.JPG)

### Screenshots, screen recording, code snippet

Excerpt from console log showing Block validation messages:
![Spacer-Anchor (4)](https://user-images.githubusercontent.com/92945757/228060629-d29669d4-4d3e-428f-a59b-4264e824a4ff.JPG)

### Environment info

WordPress Version: 6.1.1
WordPress.com Editing Toolkit 3.60227
Gutenberg 15.4.0
Firefox 111.0
Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
@jpjfox 

Thank you for the report.

This problem should occur in all blocks that want to support the anchor. The same problem was reported in #48232 and a fix is being attempted in #48232.

**Comment by jpjfox** [comment]
Looks like this problem is resolved after WordPress.com Editing Toolkit 3.60608 installed today.

Thanks to all who helped fix this issue.

**Comment by jpjfox** [comment]
I spoke too soon. Pages I've recently updated show no errors, but when editing older pages I still see “This block contains unexpected or invalid content” on Spacer blocks with Anchors.
After WordPress.com Editing Toolkit 3.60608 plugin installed and WordPress core updated to 6.2.

**Comment by t-hamano** [comment]
Hi @jpjfox,

This issue is due to the dynamic block anchor support added on the Gutenberg plugin. We have removed this feature from the Gutenberg plugin so this issue will not occur.

Instead, I have submitted #51402 to consider re-adding anchor support to dynamic blocks,
