### ISSUE TITLE
Cover Block with Featured Image and Fixed background removing block dimensions

### ISSUE THREAD

**Issue by nudgeD** [WordPress/gutenberg#49384]
### Description

When the Cover block uses the Featured Image as an image and the Fixed background Media setting is enabled, any dimensions added to the cover block (margin and padding) are removed on the front end.

### Step-by-step reproduction instructions

1. In the post editor, set a featured image for your post. 
2. Add a cover block.
3. Set the image for the cover block to Featured image. 
4. In Dimensions, add margins and/or padding. 
5. In Media settings, toggle the Fixed background on. 

### Environment info

- WordPress 6.1.1, Gutenberg 15.4.0, Twenty Twenty-three
- Chrome, Firefox
- MacOS 13

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I can reproduce the issue, labeling this as a bug.
