### ISSUE TITLE
Customizable Block Toolbar using supports field in block setting

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#49398]
## Customization of Block Toolbar
We want to show users only specific block customization options but it is currently difficult to customize the Block Toolbar and hide options without using css or other workarounds.

## What is your proposed solution?
Every toolbar button can be activated or deactivated with the supports field in the block's settings. A boolean may be used to show or hide toolbar options. Also imaginable would be to restrict options for particular user groups.

**Comment by gziolo** [comment]
This issue is related to https://github.com/WordPress/gutenberg/issues/47641.

**Comment by gziolo** [comment]
Closing as duplicate, in favor of #47641.
