### ISSUE TITLE
Site editor template list won't scroll 

### ISSUE THREAD

**Issue by dabowman** [WordPress/gutenberg#49408]
### Description

When you have a lot of templates—enough that they can't all fit on the screen—the site editor won't let you scroll down to see them all. Seems like a little UI bug. 

### Step-by-step reproduction instructions

Create a lot of templates—at least 20—and open the site editor to the template section. If your window isn't tall enough to fit the whole list you won't be able to scroll down to see all the options. 

### Screenshots, screen recording, code snippet

![site-editor](https://user-images.githubusercontent.com/5473066/228310813-b955a846-4ae2-4ed6-a6a2-849ed303f6f9.gif)

### Environment info

Wordpress: 6.1.1
Gutenberg: 15.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by kathrynwp** [comment]
Hi @dabowman - thanks for the report.

Version 15.0.1 is quite a few versions behind the latest version of Gutenberg.

I was not able to replicate this issue with either of these combinations:

WP 6.1.1 + Gutenberg 15.3.1
WP 6.1.1 + Gutenberg 15.4.0
WP 6.2 RC5 + no plugins active
Firefox 111.0 

Could you please let me know if you're still seeing the issue with the latest version of Gutenberg?

If you are, please let me know your browser version. Thanks!

**Comment by dabowman** [comment]
updated to 15.4 and it seems to be working now! thank you!

**Comment by kathrynwp** [comment]
@dabowman Very glad to hear! I'll go ahead and close this out.
