### ISSUE TITLE
_fields return null in getEntityRecords

### ISSUE THREAD

**Issue by insaurabh** [WordPress/gutenberg#49429]
### Description

When using _fields value return null.

```
 attributes.PostData = useSelect((select) => {

        return select('core').getEntityRecords('postType', 'branch', {
            orderby: 'menu_order',
            order: 'asc',
            _fields: ['title']
        });
 });
 ```
    

### Step-by-step reproduction instructions

I created a Gutenberg module. Code related to query is shared above.

The above query is written in edit.js of the module.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @insaurabh

It should always include ID when requesting specific fields since records are stored by ID reference.

This is also mentioned in the `getEntityRecords` doc - https://developer.wordpress.org/block-editor/reference-guides/data/data-core/#getentityrecords.

**Comment by insaurabh** [comment]
Thanks @Mamaduka.

id was required.

**Comment by insaurabh** [comment]
Just for more information.

When I tested in rest api _fields returned even I don't pass id. 

Do `getEntityRecords` and the REST API get data in different ways

**Comment by Mamaduka** [comment]
> Do getEntityRecords and the REST API get data in different ways

No, it uses REST API to get the data, but it also needs ID so the records are correctly referenced in the Redux store.

**Comment by bklynate** [comment]
how do you pass id along with the fields? @insaurabh

**Comment by Mamaduka** [comment]
@bklynate,

```js
select('core').getEntityRecords('postType', 'page', {
        orderby: 'menu_order',
        order: 'asc',
        _fields: ['id', title']
    });
```
