### ISSUE TITLE
Reduce overhead of 'the_content' processing on initial REST request

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#4943]
## Issue Overview
This improvement request may improve the end user's experience of invoking the editor to change existing content. 

When the editor is first invoked for a post the PHP server code calls  `gutenberg_get_post_to_edit()`. This uses the REST API to obtain the post's content to return to the client in JSON format. It sets `context='edit'` since the JavaScript code in the browser needs the `raw` content, not the `rendered` content.  
But, because it's a REST request, the `rendered` content is produced anyway. 
And this can involve a significant overhead, especially if filter functions attached to `the_content` perform a lot of work. 

It doesn't seem right. 

As a plugin developer who has written many complex shortcodes which can produce reams of data, my approach would be to write code to bypass `the_content` processing when I know it's a Gutenberg editor request. 

But I imagine there are hundreds of plugins and themes, oblivious to both the REST API and Gutenberg,, responding to `the_content` in a similar manner:

- dynamically resizing all the images in the page, 
- enqueuing inline JavaScript, 
- generating inline responsive CSS, 
- producing sharing buttons, 
- finding related posts 
- and all sorts.

Just to be ignored.

Some of my posts may contain nothing but shortcodes, each of which is expanded.
And posts without manual excerpts or more tags can get expanded twice.

I've written dynamic shortcodes that do the equivalent of displaying all the content in a particular category. 

Imagine trying to edit all that content in one go.  

There must be a better way.  

## Steps to Reproduce (for bugs)

1. Create a post which contains the latest posts block. Choose a largish number of posts to show.
2. Edit the post
3. View the source and see the post list
4. Also notice the REST request to load the posts

## Expected Behavior
Either there should be no need to render the content in the initial request OR the rendered content should be used until the dynamic content arrives.

## Current Behavior
Multiple requests to the server to load the same data.
A lot of time saving opportunity.

The irony of this suggestion is that the REST request to load the recent posts took 3 times longer than the original request. Probably due to the parallel requests for users, categories and tags.

## Possible Solution
When performing the original context=edit request Gutenberg should deactivate filter functions attached to `the_content`.

## Screenshots / Video

![image](https://user-images.githubusercontent.com/2474435/35948156-1f3f20fa-0c63-11e8-81b6-e1d9aec51f8d.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mtias** [comment]
This was brought up before. Agree the API should allow to get the raw post content without producing the rendered output at the same time.

**Comment by danielbachhuber** [comment]
> Agree the API should allow to get the raw post content without producing the rendered output at the same time.

Given the current design patterns of the API, I suspect this is non-trivial to implement, could have undesired side effects, and is unlikely to happen.

The performance issue documented in the original report should be solved through some other means. 6 seconds response time is a problem on the frontend too.

If someone feels strongly about this, I'd suggest opening a core ticket with a specific implementation proposal.
