### ISSUE TITLE
Missing whitespace when using custom CSS in theme.json

### ISSUE THREAD

**Issue by Trekky12** [WordPress/gutenberg#49446]
### Description

When using the custom css property in the theme.json the resulting CSS is missing a separating whitespace:

```
			"core/navigation": {
				"css": "ul.has-background {padding: 0;}"
			},
```

is created as:
```
<style id='global-styles-inline-css'>
...
.wp-block-navigationul.has-background {padding: 0;}
</style>
```

### Step-by-step reproduction instructions

1. Add custom css property to theme.json
2. see generated source

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@Trekky12 

Thanks for the report.

If you want to apply a style to nested elements, you can use `&`:

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"styles": {
		"blocks": {
			"core/navigation": {
				"css": "& ul.has-background {padding: 11.1px;}"
			}
		}
	}
}
```

The following inline style would be generated:

```html
<style id='global-styles-inline-css'>
.wp-block-navigation ul.has-background {padding: 0;}
</style>
```

But if you want to apply CSS only to the navigation block with a background color, you can write something like this:

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"styles": {
		"blocks": {
			"core/navigation": {
				"css": ".has-background {padding: 0;}"
			}
		}
	}
}
```

![navigation](https://user-images.githubusercontent.com/54422211/228707297-db0c3c12-3514-4015-a9e4-71c146da7cf9.png)

**Comment by Trekky12** [comment]
Hey @t-hamano,

thank you very much for the explanation. I think this issue can be closed when using your suggested syntax.
Unfortunately I found no real documentation. Is there a place where this is described?

**Comment by t-hamano** [comment]
@Trekky12

The following article may be helpful;
[Custom CSS for global styles and per block – Make WordPress Core](https://make.wordpress.org/core/2023/03/06/custom-css-for-global-styles-and-per-block/)

I would also like to close this issue because I think it has been resolved.
