### ISSUE TITLE
Gutenberg Editor in Mobile View

### ISSUE THREAD

**Issue by Faton1995** [WordPress/gutenberg#49499]
Hello, when I want to update a post via the mobile browser, nothing happens. I have posted a video about this. https://user-images.githubusercontent.com/121765651/229048443-c88e727a-b097-4906-92d2-95bf7832e07b.MOV

**Comment by dcalhoun** [comment]
Hey @Faton1995. 👋🏻 Thank you for creating this issue. Sorry to hear you are unable to successfully update posts. 

From reviewing the video you shared, it appears when you attempt to update a post in a web browser, it never succeeds. Given that this occurs in a web browser and not the native mobile app, I am going to change the label for this issue. 

Sharing additional details will likely be required to successfully debug this problem. When creating new issues, using one of the project's [issue templates](https://github.com/WordPress/gutenberg/issues/new/choose) will help ensure useful information is captured. I recommend updating this issue to include all the details requested in the [bug template](https://github.com/WordPress/gutenberg/issues/new?assignees=&labels=&template=Bug_report.yml). Alternatively, you could simply close this issue and replace it with a new issue using the template. 

Hopefully others can help debug and provide guidance once more details are shared.
