### ISSUE TITLE
Strange animation when invoking zoomed-out view

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#49492]
When the zoomed-out view is invoked – either via the dedicated button or when opening style variations – there's an animation that endures for much too long. It seems to be related to images:

https://user-images.githubusercontent.com/846565/228929982-9b25bac9-67b0-4020-af44-a3e6135a27ed.mp4

**Comment by t-hamano** [comment]
I think this issue is the same as #49120.

**Comment by jameskoster** [comment]
You're correct, thanks for pointing that out.
