### ISSUE TITLE
'Edit' button in template part toolbar exits the full screen editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#49491]
https://user-images.githubusercontent.com/846565/228927404-348ccbda-5f38-4c6f-bf44-4e2477f3ac97.mp4

This behaviour means it takes an additional click to edit the template part which is a regression.

**Comment by ntsekouras** [comment]
This has been fixed here: https://github.com/WordPress/gutenberg/pull/49604
