### ISSUE TITLE
Restrict settings of Gutenberg editor

### ISSUE THREAD

**Issue by JanLynx** [WordPress/gutenberg#49493]
There are many ways of restricting the settings of the Gutenberg editor, but they all seem to be quite hacky.

In my special case, I want to remove the button's settings in Gutenberg. Therefore I use a javascript file.

`wp.blocks.unregisterBlockStyle('core/button', 'fill');
    wp.blocks.unregisterBlockStyle('core/button', 'outline');`

Afterward, I register a new block inside a PHP file.

`register_block_style(
'core/button',
array(
'name' => 'primary-button',
'label' => __('Primary Button', 'textdomain'),
'is_default' => true,
'inline_style' => '.is-style-primary-button { color: blue !important; }',
)
);`

At least I use the Theme.json file to remove leftover settings I don't want to use.
`"styles": {
        "elements": {
            "button": {
                "color": {
                    "background": "#17a2b8",
                    "text": "#ffffff",
                    "custom": false
                },
                "border": {
                    "radius": false,
                    "color": false,
                    "style": false,
                    "width": false
                },
                "typography": {
                    "fontSizes": [],
                    "fontFamilies": []
                }
            }
        }
    },`

Is that the way of removing settings and styles? I used three different files... It feels not that good.

**Comment by tellthemachines** [comment]
There's some work towards adding the ability to register new style variations from theme.json in #49827, but it's still in early draft mode so at this stage it's hard to say when it'll ship. The idea is that in the future all these things should be configurable via theme.json.

For now, you can register the new block styles with JS too, using `registerBlockStyles` as shown in [this doc](https://developer.wordpress.org/block-editor/how-to-guides/javascript/extending-the-block-editor/).

As for the theme.json part, are you trying to disable some of the controls for the Button block? If so, the way to do that in `theme.json` would be
```
"settings": {
    "blocks": {
	"core/button": {
	     "border": {
		 "radius": false
		}
	  }
     }
}
```
Disabling controls works independently of block style variations; currently they can only be disabled at the block level.

**Comment by tellthemachines** [comment]
This issue has been quiet for a year so I'm going to go ahead and close it. Further work to extend block style variations is tracked in #57537 in case that's of interest.
