### ISSUE TITLE
Block selection popup can appear partially off-screen

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#4949]
## Issue Overview
The block selection popup can appear partially off-screen when using a browser window with short height.

## Steps to Reproduce (for bugs)
1. Go to the post editing screen and open your browser developer tools at the bottom of the screen (a common behaviour that reduces screen height).
2. Trigger the "Add block" popup.
3. Note that if your screen lacks sufficient height, the popup can appear partially off-screen at the top, which obscures the search box.

## Possible Solution
It might be possible to display the popup with a shortened height (for example with fewer rows of blocks) when there's a lack of vertical space.

## Screenshots / Video
<img width="1118" alt="" src="https://user-images.githubusercontent.com/208434/35967226-25c15696-0cb8-11e8-9669-fc741640402e.png">

**Comment by karmatosed** [comment]
I think in this case it should load down over up. That would be a better iteration than to have the library change itself.
