### ISSUE TITLE
Add a class "wp-block-list" to the List Block

### ISSUE THREAD

**Issue by Snadex** [WordPress/gutenberg#49503]
## What problem does this address?
It is currently difficult to target the List Block in a theme because it is using a plain `<ul><li></li></ul>` output without classes.

Adding a class to the `<ul>` will allow theme developers to easily target and create default styles for the List block, without affecting every other `<ul>` on the site.

## What is your proposed solution?
Adding a `wp-block-list` class to the parent `<ul>` element.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/12420 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
