### ISSUE TITLE
Site Logo block does not update favicon or site icon in admin

### ISSUE THREAD

**Issue by artemiomorales** [WordPress/gutenberg#49516]
### Description

When changing an existing site logo using the Site Logo block first in Full Site Editing, then in the post editor, the logo stops being updated in the admin and the favicon no longer gets updated as expected.

### Step-by-step reproduction instructions

1. Go into Full Site Editing
2. Add a new Site Logo block and populate it with an image
4. Refresh the page and notice the logo has been updated in the admin as expected
5. Now replace the Site Logo's image with a new one
6. Notice that the logo is again updated as expected
7. Now add a new post and Site Logo block, populating it with an image
8. Notice that the Site Logo block no longer updates the image

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/5360536/229193290-fc68b109-4cfa-4254-89f2-14ff0c8c9a4b.mp4

### Environment info

- WordPress 6.2, Gutenberg trunk, Gutenberg 15.4
- Chrome version 111.0.5563.64
- MacOSX 12.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
Do you have "Use as site icon" toggled? 

<img width="279" alt="CleanShot 2023-03-31 at 14 55 20" src="https://user-images.githubusercontent.com/1813435/229206040-2bb53111-94d4-44cb-b769-2afae6d56ded.png">

**Comment by artemiomorales** [comment]
> Do you have "Use as site icon" toggled?

Looks like that solves the issue. Thanks!
