### ISSUE TITLE
Clicking "Edit" on a Template Part should open it in focus mode

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#49528]
I would expect that clicking the "Edit" control from a template part's block toolbar would open directly to the "Focus mode" of that particular template part. 

Currently, you click "Edit" then have to click the edit icon, or click on template part within the frame to actually edit:

https://user-images.githubusercontent.com/1813435/229259573-d624e854-5b23-4ea8-8f8d-cc1fc5a8b44e.mp4

**Comment by jameskoster** [comment]
Duplicate: https://github.com/WordPress/gutenberg/issues/49491 :D
