### ISSUE TITLE
Custom Post Types not showing in the Post Type dropdown of the Query Loop block

### ISSUE THREAD

**Issue by storkontheroof** [WordPress/gutenberg#49539]
### Description

The Query Loop block doesn't support custom post types.

I have a clean install of Wordpress 6.2.

I've created a minimal plugin which uses register_post_type to register "MY CPT", following advice from here: https://developer.wordpress.org/reference/functions/register_post_type/

Next i created a new Page and added the Query Loop block.

In the block editor settings in the side panel, i expect the Post Type dropdown to show "MY CPT" too, but it doesn't. Only the default Post and Page show up.

### Step-by-step reproduction instructions

1. Install Wordpress
2. Use register_post_type to register a CPT
3. Create a new page
4. Add the Query Loop block
5. Try selecting the custom registered CPT

### Screenshots, screen recording, code snippet

<img width="882" alt="dashboard" src="https://user-images.githubusercontent.com/893723/229340523-3999190f-b5ce-4b45-890c-f9509f0cb1b0.png">

<img width="1725" alt="my-cpt-overview" src="https://user-images.githubusercontent.com/893723/229340516-03669335-bdda-44c1-8ad8-a464cda7418c.png">

<img width="1725" alt="edit-page-with-query-loop-block" src="https://user-images.githubusercontent.com/893723/229340519-03116d0e-55f7-499c-88d4-de3702c87534.png">

### Environment info

Wordpress 6.2 with Twenty Twenty Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@storkontheroof 

Thanks for the report.

If `show_in_rest` is set to `true`, it will appear in the dropdown. This option is also required to enable the block editor for that post type:

```php
function myplugin_register_book_post_type() {
	$args = array(
		'public'       => true,
		'label'        => 'Book',
		'show_in_rest' => true,
	);
	register_post_type( 'book', $args );
}
add_action( 'init', 'myplugin_register_book_post_type' );
```

**Comment by storkontheroof** [comment]
Ah, super. Indeed see it now.
Thanks a million!
