### ISSUE TITLE
Duotone appears with 6.2 even when disabled with theme.json

### ISSUE THREAD

**Issue by smerriman** [WordPress/gutenberg#49541]
### Description

Prior to 6.1, duotone filters could be disabled with theme.json. Now they cannot.

### Step-by-step reproduction instructions

< 6.2, the following in theme.json disabled all color options, including duotone:

`{
	"version":2,
	"settings": {
		"color": {
			"palette": [],
			"custom": false,
			"gradients": [],
			"customGradient": false
		}
	}
}`

I have tried updating this to:

`{
	"version":2,
	"settings": {
		"typography": {
			"customFontSize": false,
			"fontSizes": [],
			"dropCap": false,
			"fontWeight": false,
			"fontStyle": false,
			"textTransform": false,
			"textDecoration": false,
			"letterSpacing": false
		},
		"color": {
			"custom": false,
			"customDuotone": false,
			"customGradient": false,
			"duotone": [],
			"gradients": [],
			"palette": [],
			"background": false,
			"defaultGradients": false,
			"defaultPalette": false
		}
	}
}`

The duotone filter still appears on image blocks.

### Environment info

WordPress 6.2, no Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
I'm able to reproduce this WP 6.2  (w/o gutenberg activated) as well with Gutenberg 15.4.0 activated. 

According to https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#settings the following settings in a theme.json should disable the core gradients from being selected as well as adding new gradients. 

I am still able to select the default duotones shipped with WordPress.

> {
>   "version": 2,
>   "settings": {
>     "color": {
>       "custom": false,
>       "customDuotone": false,
>       "customGradient": false,
>       "duotone": [],
>       "gradients": []
> }
> }
> }

**Comment by annezazu** [comment]
@ajlende mind taking a look here?

**Comment by ajlende** [comment]
This is the expected behavior for your settings.

There is a `defaultDuotone` option that controls showing the default filters in the UI. So you need to set all three of these settings to fully remove the duotone panel.

```json
{
  "version": 2,
  "settings": {
    "color": {
      "duotone": [],
      "customDuotone": false,
      "defaultDuotone": false
    }
  }
}
```

The theme.json options will disable UI elements for adding new filters, but default filters will continue to show on the page. In 6.3 the default SVGs will no longer be rendered on pages where they are not used (#49103).
