### ISSUE TITLE
Custom template 'Choose a pattern' modal dialog doesn't open when there are unsaved changes

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#49548]
### Description

When creating a new custom template, the 'Choose a pattern' modal dialog opens automatically to provide users with two options: 'Fallback content' or 'Start blank'. However, when another existing template has unsaved changes, the modal dialog does not open.

There may be some reasoning behing this behavior, as when there are unsaved changes, the editor is in a sort of 'dirty state' but seems to me the users experience feels just broken. 

### Step-by-step reproduction instructions

- Go to the Site editor > Design > Templates
- Click the 'Add New Template' plus icon and choose 'Custom template'.

<img width="743" alt="Screenshot 2023-04-03 at 10 09 16" src="https://user-images.githubusercontent.com/1682452/229455217-2bd4976a-3ed0-4635-9482-9b8f70179dc7.png">

- In the 'Create custom template' modal dialog, enter a name and click 'Create'.
- Wait.
- The 'Choose a pattern' modal dialog opens:

<img width="1070" alt="Screenshot 2023-04-03 at 10 09 48" src="https://user-images.githubusercontent.com/1682452/229455603-4e5a5504-5a17-4c0b-af13-9ad382c1b4b6.png">

- Close the modal dialog.
- Edit an existing template, make some change and do _not_ save your changes.
- To inform there are unsaved changes, the editor shows a 'Save' button and the number of unsaved changes at the bottom of the left sidebar:

<img width="420" alt="Screenshot 2023-04-03 at 10 10 32" src="https://user-images.githubusercontent.com/1682452/229456114-5dd2d524-510a-44ef-b42f-13c8799e62ad.png">

- Follow again the steps to create a new Custom template.
- Wait and observe the 'Choose a pattern' modal dialog does not open.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by afercia** [comment]
Note that this happens with any unsaved change, whether it's from a template or a template part.

**Comment by carolinan** [comment]
I am still experiencing problems with this and it happens even when I don't have any unsaved changes.
I am also, strangely enough, getting different results on the Mac and on the PC.

I am using:
Chrome
WordPress 6.2
Gutenberg latest release
Create block theme latest release
 "local"
nginx,
No difference whether I select PHP 7,4, 8. or 8.1.

Start from a theme with only one template, for example, using the create blank theme option from the Create block theme plugin.
Make some changes to the Index and global styles, and save.

Open Site Editor, Templates, Add new, select Front Page.
- On the mac, I can _never_ get the pattern selection modal to show. 
- On the PC,  (windows 10) which if it matters, loads the site editor significantly slower than the mac (it is old and has less memory),  the pattern selection panel sometimes show after a few seconds, but often not at all.

On the PC, if I click on "Add new" while the message "loading templates" is showing, I can never get the modal to show.

Pinging @jorgefilipecosta and @youknowriad in case you have any thoughts about how to troubleshoot this, solve it, or even add better reproduction steps...

**Comment by Mamaduka** [comment]
The "unsaved changes" issue is due to the `hasDirtyEntityRecords` check. Currently, there's no way to distinguish whether the "dirty" entities are associated with the template.

## Source

https://github.com/WordPress/gutenberg/blob/bd47ab17706b0082d1d94c5e682d63db87b3d474/packages/edit-site/src/components/start-template-options/index.js#L169-L171

**Comment by youknowriad** [comment]
It should be possible to use the result of `__experimentalGetDirtyEntityRecords` to check only dirtiness of with the template or template part using the id returned by `getEditedPostId`
