### ISSUE TITLE
Tags outside of WordPress template comments cause issue with Patterns in Gutenberg editor

### ISSUE THREAD

**Issue by selceeus** [WordPress/gutenberg#49544]
### Description

When creating a new pattern, I put a `<section>` tag outside the template comments. When I select the associated category, a classic edit modal is launched in the editor. When I press cancel, my broken pattern is inserted and wrapped with classic blocks. I have ACF Pro installed but tested it deactivated and had the same result.

### Step-by-step reproduction instructions

1. Create a pattern in the patterns directory of the theme
2. Go to the Editor 
3. Select Patterns and Pattern Category
4. Then a classic edit modal is launch

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/521577/229405103-841934b4-d7db-41ae-ba7e-39f2a337c006.png)
![image](https://user-images.githubusercontent.com/521577/229405163-28923a9d-9651-4df7-a21d-0d38e008f216.png)
![patterns](https://user-images.githubusercontent.com/521577/229405444-6d59657d-5fa2-4241-836b-8693c3ce4a0f.png)
[pattern-code.txt](https://github.com/WordPress/gutenberg/files/11134502/pattern-code.txt)

### Environment info

Wordpress 6.2
Twenty Twenty Three
Latest Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi

> a <section> tag outside the template comments.

Can you provide the pattern code example that shows where you added the `<section>`? I want to double check if I understood it correctly. 

The pattern must be valid block markup. `<section>` is not a block,, so the editor can only transform it into a classic block.

If you want to use a section, use the group block and change the HTML tag from div to section in the Advanced panel in the settings sidebar, or use the HTML block.

**Comment by selceeus** [comment]
Hello, the pattern markup is below. I understand about block markup, etc. I mostly messed around to see what I could and couldn't do. I understand that this is an edge case.

I submitted it mainly as an error-handling issue. Also, this issue happened when I selected the pattern category rather than the pattern specifically. 

Thank you for the information. I will use it when coding in the future!

[pattern-code.txt](https://github.com/WordPress/gutenberg/files/11137940/pattern-code.txt)

**Comment by ndiego** [comment]
> If you want to use a section, use the group block and change the HTML tag from div to section in the Advanced panel in the settings sidebar, or use the HTML block.

Hi @selceeus, thanks for reporting. Just wanted to follow up and concur with @carolinan's comment above. If you update your pattern with the following code, you should be good to go!

```
<?php
/**
 * Title: About Section
 * Slug: twentytwentythree/about-section
 * Categories: featured
 * Keywords: About Section
 * Block Types: core/columns
 */
?>
<!-- wp:group {"tagName":"section","layout":{"type":"constrained"}} -->
  <!-- wp:columns {"align":"wide"} -->
  <div class="wp-block-columns alignwide">

    <!-- wp:column -->
    <div class="wp-block-column">
      <!-- acf:about -->
        <section class="test"></section>
      <!-- /acf:about -->
    </div>
    <!-- /wp:column -->

    <!-- wp:column -->
    <div class="wp-block-column">
      <!-- acf:about -->
        <section class="test"></section>
      <!-- /acf:about -->
    </div>
    <!-- /wp:column -->

  </div>
  <!-- /wp:columns -->
<!-- /wp:group -->
```
