### ISSUE TITLE
Layout / Post Editor: A post content block set to "wide" is not rendered as wide within the post editor

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#49546]
### Description

In WordPress 6.2, the post editor was updated to more closely reflect visually the block attributes set on the post content block in the template currently in use. This works well for constrained layouts with site-level `contentSize` or `wideSize` set, however for themes that use a post content block that is nested within a Group block and set to `wide` alignment, this wide alignment is not reflected in the post editor.

### What's expected

For templates that set the Post Content block to `wide` alignment within the template, that when a user opens up the post editor, the wide alignment will be respected and rendered correctly.

### What happens instead

When opening up the post editor, the blocks are displayed as if constrained to `contentSize` instead of `wideSize`

### A caveat about this issue

This would be a good issue to resolve (ensuring rendering of `wide` post content blocks is accurate within the post editor), but also reveals an interesting case for themes. My suspicion is that in many cases when a template is set up in this way, it isn't _quite_ what the theme or user desires.

For example, if a template is set up as a `wide` template, with the expectation that content within the template will be displayed at a wider size than other templates, in many cases it is likely preferable to set the post content block to a constrained layout with custom values for `contentSize` and `wideSize` that are wider than the global values used by the theme, _or_ to use block patterns where a wrapping group block is set to `wide`, and that pattern is inserted within a post or page by the user. This is because:

* If a template sets the post content block to `wide` and with layout _not_ constrained (that is, no options for content/wide size), then it isn't possible for users to set content within the post to other alignments (e.g. the options for content/wide/full that are commonly expected)

### Step-by-step reproduction instructions

* In a blocks theme (to make testing more clear, I used `emptytheme`), add the following markup to a post or page template:

```
<!-- wp:group {"align":"wide","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide"><!-- wp:post-content {"align":"wide"} /--></div>
<!-- /wp:group -->
```

* Save the template
* Create a post or page using that template
* Notice that while it's expected that the post will be displayed within the editor using `wide` width, instead the regular `contentSize` is applied to blocks within the post or page
* The site frontend is unaffected

### Screenshots, screen recording, code snippet

View while editing the template:

![image](https://user-images.githubusercontent.com/14988353/229425766-a634b450-5c33-43bd-b446-28eb59f3b65a.png)

View while editing a post or page using that template:

![image](https://user-images.githubusercontent.com/14988353/229425854-0078b612-2a7e-4e3b-9105-c1bfa172eee8.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

Thanks @annezazu and @richtabor for raising the issue, and CC: @tellthemachines

**Comment by annezazu** [comment]
cc @anarieldesign who first raised it to me and so you can follow along <3

**Comment by anarieldesign** [comment]
@annezazu @andrewserong thank you for opening this ticket,I thought I'm going crazy and it's just on my end 😵‍💫. Hope this can be resolved soon as it's not the best user experience 🙏. If you need more info and videos let me know 🙏

**Comment by tellthemachines** [comment]
Thanks for the detailed description @andrewserong ! 

If I understand correctly, the fix for this would be to have the post editor layout reflect the alignment settings of the Post Content block from the post template. That should be straightforward to manage because we're already getting the layout info from the Post Content attributes, so it's easy to get the alignment too.

**Comment by andrewserong** [comment]
> If I understand correctly, the fix for this would be to have the post editor layout reflect the alignment settings of the Post Content block from the post template.

Yes, that sounds like a good direction to explore to me. Good thing we're grabbing all the post content attributes, and not just the layout object! I was imagining we could try copying the align code pretty much from `addAssignedAlign` around here and seeing if we can use that for the visual editor container: https://github.com/WordPress/gutenberg/blob/a770a6eaceacab0ae499950b4c539676662f4148/packages/block-editor/src/hooks/align.js#L234

There might be a little bit of juggling since the markup of the post editor isn't quite the same as a post content block in the site editor, but hopefully it won't be too hard to wrangle 🤞
