### ISSUE TITLE
Block style previews on RTL site are covering the style variation buttons

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#49554]
### Description

Splited from #49549

@derridHeidegger reported the following issue:

> another issue is that in 6.2 style variations previews on RTL site are covering the style variation buttons, so it is really hard to use:
> ![forstylevariations](https://user-images.githubusercontent.com/1025218/229446792-f378fe9e-71b7-42c9-9988-603aa04a30c3.png)

### Step-by-step reproduction instructions

WordPress 6.2
edge and chrome browsers
windows 11 desktop

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

In my testing, I was not able to reproduce it (tested with the image block). It would be great if you could confirm if this problem also occurs with the default theme and default site language(English).

![test](https://user-images.githubusercontent.com/54422211/229526249-76005cf9-a83c-4719-80ee-56b2e36a7591.png)

**Comment by derridHeidegger** [comment]
hi
sorry i am in the middle of a holiday so i did not answered. anyways i have made a video that show how bizzare is the issue: group block has preview issues, but not the image and the separator blocks.

https://user-images.githubusercontent.com/1025218/230394562-5e3ace89-3095-4039-ae7f-9f23e93f6d83.mp4

**Comment by kevin940726** [comment]
I can reproduce this issue on the latest trunk both in Safari and Chrome(Brave):

https://user-images.githubusercontent.com/7753001/231375066-b9e5adb5-0df2-439c-81a4-baecc7c93461.mp4

**Comment by derridHeidegger** [comment]
hopefully this will be fixed soon. it makes for a very bad user experience

**Comment by t-hamano** [comment]
I was also able to reproduce it. Maybe the test procedure was wrong. I also identified a problem with the block preview popover flashing depending on the mouse cursor position.

https://user-images.githubusercontent.com/54422211/231486443-0818e452-3235-4602-8cf2-3e5be10d0095.mp4
