### ISSUE TITLE
Calendar block is showing wrong previous month.

### ISSUE THREAD

**Issue by dhrumilkumbhani** [WordPress/gutenberg#49551]
### Description

Hello,
I have used the calendar block in WordPress and it's showing wrong previous month.

### Step-by-step reproduction instructions

1. Go to create new post.
2. Add calendar block.
3. and show below previews link. current month is April and it's showing previous month is FEB instead of March.

### Screenshots, screen recording, code snippet

Screen Short: https://tinyurl.com/2fvn6c38

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by dhrumilkumbhani** [comment]
Also I have created tickets on core track for same.
[#58065](https://core.trac.wordpress.org/ticket/58065)

**Comment by Soean** [comment]
I can't reproduce the issue.

![Bildschirmfoto 2023-04-03 um 11 34 15](https://user-images.githubusercontent.com/695201/229471250-4398fcd2-44a1-4c3e-b087-60c369a0a85a.png)

**Comment by dhrumilkumbhani** [comment]
@Soean thanks for your response.

I have checked and test it in deep and getting, it's show the based on the last month article/post.   
so it's not an bug.
Thank you.
