### ISSUE TITLE
Featured Image Blocks Hide all Settings if there is no query block in the same document

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#49560]
### Description

This made sense when the line was written:

https://github.com/WordPress/gutenberg/blame/trunk/packages/block-library/src/post-featured-image/edit.js#L189

```js
	/**
	 * A post featured image block placed in a query loop
	 * does not have image replacement or upload options.
	 */
	if ( ! featuredImage && isDescendentOfQueryLoop ) {
		return (
			<>
				{ controls }
				<div { ...blockProps }>
					{ placeholder() }
					<Overlay
						attributes={ attributes }
						setAttributes={ setAttributes }
						clientId={ clientId }
					/>
				</div>
			</>
		);
	}
```

But `controls` are used for more than that now! Since then featured image blocks have had new options added, particularly the "Link to post" toggle which sits inside this check in the `controls` component.

### Step-by-step reproduction instructions

Use a featured post image block in a document that does not contain a query block.

In my situation I have a template part inside a query block + post template block, and because of this the featured image inside the template part does not have the option to enable post links, and wipes it if I add it manually and reopen

### Environment info

WordPress v6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I have been able to replicate this. 

1. Add a new template part
2. Add a Post Featured Image block to a template part
3. Edit the Post Featured Image block and notice that the Settings are not displayed

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/4832319/229826299-b25b51fd-55e8-4e9b-9667-826dea0995ae.png">

**Comment by annezazu** [comment]
@ntsekouras or @apeatling can you look into this?
