### ISSUE TITLE
No results block is showing if there is only one search result

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/gutenberg#49575]
### Description

~~I added an additional condition to the post_search or posts_where filter:~~

~~`$where .= " AND {$wpdb->posts}.post_content LIKE '%bar%'";`~~

~~The title of one post is containing "foo" and I'm searching for "foo".~~

~~Because "bar" is part of the post_content of this post and "foo" is part of the title, it shows the post as a search result.~~

~~But the no results block is showing too.~~

~~If no filter is modifying the search results, this is not showing.~~

 You need to use Twenty-Twenty Three (or add the no results block manually to your site) to see the problem.

First reported here: https://core.trac.wordpress.org/ticket/58080

### Step-by-step reproduction instructions

~~Use this code to add condition to search:~~

~~Create post with "foo" on the title and "bar" in the content.~~

~~Search for "foo".~~

~~See one search result (your post) *and* the no results block.~~

New steps from trac ticket:

> I can reproduce this in Twenty Twenty-Three if there is exactly one search result.
> No template or markup changes are needed to test this.
> 
> Create a new post with a unique word that you know is not used anywhere in your content.
> On the front, perform a search for the word (as in, use the search form and enter the keyword to do the search :) )
> The post, as well as this text shows: "Sorry, but nothing matched your search terms. Please try again with some different keywords."
> -This is the text that TT3 adds to the search inside the query no results block.
> 
> Create a second post with the same word, and search again.
> The message does not show. The result is displayed correctly.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Zodiac1978** [comment]
Looks like this is also the case if my code is not active, so maybe my description is wrong and there is another explanation. Found this one on trac: https://core.trac.wordpress.org/ticket/58031

**Comment by carolinan** [comment]
Actually, this was already reported here, sorry for the back and forward:
https://github.com/WordPress/gutenberg/issues/47793

**Comment by Zodiac1978** [comment]
No problem - the other one is much better and has more context.
