### ISSUE TITLE
Screen with spinner when opening Site Editor does not go away

### ISSUE THREAD

**Issue by Nyota** [WordPress/gutenberg#49570]
### Description

When I open the Site Editor, I see a spinner screen, expecting the theme to load. The theme never loads however and the spinner screen does not go away. The only way to access the Site Editor, is to navigate to a specific template: then the preview works and a template can be selected and edited.

EDIT: Additional information: (as per @MadtownLems)

> There are no JavaScript errors in the console.
> There are no PHP errors logged.
> I don't see any failed network requests in the Network inspector of DevTools.

### Step-by-step reproduction instructions

1. Go to Appearance > Editor
2. Wait for preview to load but this never happens. Only the spinner is displayed.

### Screenshots, screen recording, code snippet

![Screenshot 2023-04-04 at 11-16-23 Editor ‹ Devlopr — WordPress](https://user-images.githubusercontent.com/2835543/229748882-281ee999-4abc-436e-8a1d-510bcdcd89be.png)

### Environment info

WordPress 2.6, Theme: Twenty-Twenty-Three 1.1, no plugins active
Firefox and Chrome
Mac Os 12.6.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
This has occurred for me sporadically but is very difficult to replicate. If anyone else experiences this issue, please add a comment here with testing steps if possible. That will help us uncover the root issue.

**Comment by MadtownLems** [comment]
I've run into this a lot.

There are no JavaScript errors in the console.
There are no PHP errors logged.
I don't see any failed network requests in the Network inspector of DevTools.


So far, I've only noticed the following has an impact:

Settings->Reading
Home Page Shows:

Latest Posts -> Infinite spinning (whether or not there's a Page selected for the Posts page)
A static home page -> Works as expected

**Comment by Nyota** [comment]
@ndiego Just as an info, it's been occurred to me on all my test sites with block themes, including the twenty twenty themes. Only one theme would load properly (Just checked and it had a static front page). This was done on clean installations with no other plugins active. I tried @MadtownLems approach and I've resolved the issue for now. Setting a static front page helps.

@MadtownLems Thanks a lot, I tried this and it resolved the issue. Setting the static home page loads the theme within the Site Editor as desired. In previous versions the editor would load the index.html or front-page.html on opening, even if nothing was set. Would be nice if that could happen without having to set a static front page.

And yes, I'll add that info to my post as well, I was not getting any errors or failed requests.

**Comment by kevin940726** [comment]
I can't seem to reproduce this. It might be helpful if anyone can create a replayable recording via [replay.io](https://www.replay.io/) or something similar if possible. Preferably in a testing environment and avoid leaking any sensitive information.

**Comment by MadtownLems** [comment]
If there's anything in particular you're looking for in a screen recording, I can certainly do that. Otherwise just imagine that the circle in the middle is spinning (and never stops)  :)
![fse-spin](https://user-images.githubusercontent.com/945157/231471248-afc01b3a-1c2e-421a-bb56-c8be506dc4af.png)

**Comment by kevin940726** [comment]
@MadtownLems Oh, I mean a recorded link using [replay.io](https://www.replay.io/), a tool helpful for debugging. :)

**Comment by supernovia** [comment]
For those who can't replicate this: is your front page set to show the latest posts? It's showing up pretty consistently for me across themes if that's set.

**Comment by ndiego** [comment]
Yeah, I have set the front page to show the latest posts and am not able to replicate it consistently. Have you tested with Twenty Twenty-Three @supernovia?

**Comment by Mamaduka** [comment]
@Nyota, @MadtownLems, are you running WP multi-site or standard installation?

**Comment by MadtownLems** [comment]
> @Nyota, @MadtownLems, are you running WP multi-site or standard installation?

Fantastic question! I have been on MultiSite up until now. I just spun up a new single site instance (on Local) and, for the first time ever, did NOT get the infinite spinning! I think you might be on to something here.

**Comment by Mamaduka** [comment]
Thanks for the confirmation, @MadtownLems! The issue should be resolved via #49861.

**Comment by Nyota** [comment]
> @Nyota, @MadtownLems, are you running WP multi-site or standard installation?

I'm on multisite, skipped my mind, I should have mentioned that!
