### ISSUE TITLE
Gutenberg plugin v 15.6, stable release April 19, 2023

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#49599]
This issue is to provide visibility on the progress of the release process of Gutenberg 15.6 and to centralize any conversations about it. The ultimate goal of this issue is to keep the reference of the steps, resources, work, and conversations about this release, so it can be helpful for the next contributors releasing a new Gutenberg version.

-   Gutenberg version to release: ([15.6](https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+milestone%3A%22Gutenberg+15.6%22+is%3Aclosed))
-   Release Manager (a.k.a. Release Lead): @bph + @ndiego 
-   Release Date 15.6 RC: April 12, 2023
-   Release Date 15.6 stable: April 19, 2023
-   Previous version change log (as a reference): [15.4](https://github.com/WordPress/gutenberg/releases/tag/v15.4.0)

## Resources

-   📖 Read: [Gutenberg Release Process](https://developer.wordpress.org/block-editor/contributors/code/release/)
-   📽 Watch: [Gutenberg Plugin: New Release Workflow](https://www.youtube.com/watch?v=TnSgJd3zpJY)
-   📽 Watch: [Creating the Gutenberg plugin v12.0 Release Candidate](https://www.youtube.com/watch?v=FLkLHKecxWg)
-   📽 Watch: [Gutenberg plugin v12.0.0 Release Party!](https://www.youtube.com/watch?v=4SDtpVPDsLc)

### RC Day - Wednesday, April 12, 2023

-   [ ] _Optional:_ Attend `#core-editor` meeting (14:00UTC)
-   [x] Post a message in `#core-editor` channel to let folks know you are starting the RC release process
-   [x] Organize and Label PRs on the relevant milestone
-   [x] Start the release process by triggering the `rc` [workflow](https://developer.wordpress.org/block-editor/contributors/code/release/#running-workflow)
-   [x] [Update the created Draft Release accordingly](https://developer.wordpress.org/block-editor/contributors/code/release/#view-the-release-draft)
-   [x] Publish Release
-   [x] Announce in `#core-editor` channel that RC1 has been released and is ready for testing
-   [x] Ping any other relevant channels announcing that the RC is available
-   [x] Create Draft of Release post on Make Core blog _(initial draft in [Google doc](https://docs.google.com/document/d/1Hh25EYXSvRd5K45gq0VFN7yfN5l9om2FpX-_KqpVW7g/edit#))_

### Between RC and Release
- [x] post a reminder in `#core-editor` for backporting PRs to RC (~Label `Backport to Gutenberg RC`)
-   [x] [Backport to RC](https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+label%3A%22Backport+to+Gutenberg+RC%22+is%3Aclosed) = [Cherry-picking](https://developer.wordpress.org/block-editor/contributors/code/release/#creating-release-candidate-patches-done-via-git-cherry-pick)
-   [x] [Draft Release Post Highlights and Change Log](https://docs.google.com/document/d/18r-24xBL57KGjsBCju1Sk-ClmiLuH5SwTG6jMwXgGlI/edit#heading=h.irlo2ckpr1d4)  for 15.6
-   [x] Get assets from [Design Team](https://make.wordpress.org/design/) for the post
-   [x] Reach out to Highlight Authors to draft sections _(if necessary)_

### Release Day - Wednesday, April 19, 2023

-   [x] Post a message in `#core-editor` channel to let folks know you are starting the release process
-   [x] Start the release process by triggering the `stable` [workflow](https://developer.wordpress.org/block-editor/contributors/code/release/#running-workflow)
-   [x] Update the created Draft Release accordingly. Typically, by copy/pasting the last RC release notes and adding any changes/updates as needed.
-   [x] Publish Release
-   [x] Trigger the update to the plugin directory - SVN _(get approval from member of Core team if necessary)_
-   [x] Announce in `#core-editor` channel that the plugin has been released
-   [x] Reach out to other contributors to help get the post reviewed
-   [x] Publish Release post on Make Core blog

**Comment by bph** [comment]
@ndiego  @priethor - I just started the [Release post draft on Google Drive. ](https://docs.google.com/document/d/18r-24xBL57KGjsBCju1Sk-ClmiLuH5SwTG6jMwXgGlI/edit)

**Comment by bph** [comment]
- [ ] Add link to the [Google Drive assets folder for release posts](https://drive.google.com/drive/folders/1U8bVbjOc0MekWjpMjNaVFVhHFEzQkYLB) to the Checklist template. 
- [ ] Add a note on the release post that "Image block settings in the block inspector to be set “Full size” to ensure that all the images look sharp and all the GIFs will play"
- [ ] add the link to the cherry-picking section

**Comment by ndiego** [comment]
[Gutenberg 15.6](https://make.wordpress.org/core/2023/04/19/whats-new-in-gutenberg-15-6-19-april/ ) has been released! 🎉
