### ISSUE TITLE
Switching from text to heading only preserves first paragraph

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#496]
To reproduce, transform a text block of min. 2 paragraphs into a heading. Only the first line is transformed into a heading, while the others disappear.

**Comment by youknowriad** [comment]
Related discussions in #484 and #465.

**Comment by nylen** [comment]
+1 to fixing this, it violates the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).  I think one of two things should happen instead:

- Switching a multi-paragraph text block to a heading is disabled - this operation doesn't really make sense.
- The current paragraph only is transformed into a heading, and the block is split into either two or three blocks.  If we keep a text block as containing multiple paragraphs, it seems potentially difficult to surface this function in the UI.

**Comment by jasmussen** [comment]
@youknowriad I think you fixed this? I can't seem to reproduce in master.

**Comment by youknowriad** [comment]
Yep, this is fixed now. Let's close it
