### ISSUE TITLE
Document Overview overflowing

### ISSUE THREAD

**Issue by cawa-93** [WordPress/gutenberg#49610]
### Description

When Document Overview has 7 or more nesting levels, viewing tree starts overflow panel.
![зображення](https://user-images.githubusercontent.com/1662812/230098180-fdbb724a-b52a-4045-a69c-c1683095f851.png)

Since whole panel have `overflow-x: hidden` there impossible to reach to any dropdown menu on any block

![зображення](https://user-images.githubusercontent.com/1662812/230098442-5db352fe-e7de-4ba0-8c63-81b6d5bc796b.png)

Simple solution
```diff
.edit-post-editor__list-view-panel-content {
- overflow-x: hidden;
+ overflow-x: auto;
}
```

### Step-by-step reproduction instructions

Create document with many nested layers with long blocks names

### Environment info

- WordPress 6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting and working on this. There are some related PRs:
- [List View: Fix the width of the list view to 350px](https://github.com/WordPress/gutenberg/pull/49508#top)
- [List View: Reduce spacing for each nesting level, and between block icon and block title](https://github.com/WordPress/gutenberg/pull/49600#top)

It might be good to coordinate efforts between you and the other contributors (@andrewserong @scruffian)

**Comment by andrewserong** [comment]
Thanks for writing up the issue and working on a fix @cawa-93! I'll give your PR a review today.

This idea for a fix sounds consistent with the other two PRs that Dan linked to above, as you're looking at fixing up the scrolling behaviour for the post editor, where #49508 looks at the site editor, and #49600 is looking at overall spacing for nesting levels.
