### ISSUE TITLE
Use consistent input field style

### ISSUE THREAD

**Issue by paulwilde** [WordPress/gutenberg#4963]
Currently I count 4 different input field styles. For consistency there should only be one. Also for that one style there should be a generic class which can be used in order for a field to inherit that style.

Note that in the screenshots I've provided, all fields are focussed so you can see the different focus styles.

Style one (Shortcode block):
<img width="629" alt="screen shot 2018-02-08 at 19 32 20" src="https://user-images.githubusercontent.com/704594/35993940-d067e24c-0d06-11e8-9124-2583644a3b6a.png">

Style two (Embed blocks):
<img width="624" alt="screen shot 2018-02-08 at 19 32 52" src="https://user-images.githubusercontent.com/704594/35993974-e24f1aa2-0d06-11e8-8d4a-bf57351a2973.png">

Style three (Inspector controls):
<img width="274" alt="screen shot 2018-02-08 at 19 34 53" src="https://user-images.githubusercontent.com/704594/35994069-2a0172aa-0d07-11e8-8af9-16c8a3523f9c.png">

Style four (Tags taxonomy field):
<img width="276" alt="screen shot 2018-02-08 at 19 36 19" src="https://user-images.githubusercontent.com/704594/35994135-6331b940-0d07-11e8-8f0f-81cd274e3b3e.png">

In theory there is a fifth style which is the one used for WordPress. It's basically style three but with less padding.

**Comment by karmatosed** [comment]
I agree and think this is simply a case of the new styles not being picked up. Is that right @jasmussen?

**Comment by jasmussen** [comment]
Took a stab at this in #5605, but would appreciate feedback before taking that one further.
