### ISSUE TITLE
"Switch to Draft" makes it too easy to unintendedly unpublish a post

### ISSUE THREAD

**Issue by webmatros** [WordPress/gutenberg#4964]
It's way too easy to accidentally click "Switch to Draft" on a published post.

The "button" / link is where "Save Draft" has been clicked again and again all throughout the creation of the post. Muscle-memory makes it so easy to accidentally unpublish a post, that way.

I've published two posts using Gutenberg, and have accidentally unpublished both of them. Quite problematic when they've been promoted via social media and/or email.

Either move Switch to Draft somewhere else in the UI, or leave it like it was/is in the current WordPress editor.

Pretty please?

**Comment by mtias** [comment]
Seems it could just show a confirmation step instead "Are you sure you want to unpublish this post?". cc @jasmussen @karmatosed

**Comment by jasmussen** [comment]
I agree with that, even a simple js prompt feels like it would address it.

**Comment by karmatosed** [comment]
+1 here to the confirmation step.

**Comment by webmatros** [comment]
@mtias Yes, at the very least such a prompt would avoid the majority of mishaps.

Still, I'd rather the feature to change post status wasn't in the same position (as I wrote previously). When tired, and one has been writing all day to hit a deadline, I personally find it a possibility that even such a prompt will be mindlessly clicked "yes/okay" to.

But yes: +1 to such a prompt, as an MVP-solution:)

**Comment by jasmussen** [comment]
While we can always revisit these things, having used this for a couple of months or so, the position feels fairly natural to me. The thing is, once a post is published the actions you might want to take on it change from when you are just writing a draft. Suddenly the chief action becomes updating the post on one hand, but also switching to draft on the other — say you accidentally published. 

It took a while to get used to the location too, but once it was there it started to feel right.

**Comment by webmatros** [comment]
Of course, one can get accustomed to even the strangest things;-p

How often do you honestly think someone would want to unpublish a post? The flow is illogical.

Especially now that the Publish function finally has an "are you sure" function. The classic editor didn't, which was equally frustrating, just the other way around:
In the classic editor I feared accidentally publishing a post (not good when using f.e. Jetpack's Publicize module) – in Gutenberg that's no longer an issue, but a new fear of accidentally unpublishing a post has been introduced.

Why not put it where it (IMO) belongs: In Status & Visibility? Either under Visibility, or, as a "Post Status: Draft/Pending/Published" above "Visibility: Public" ?

At the very least another +1 for the js "are you sure you wanna switch back to draft?" prompt.
