### ISSUE TITLE
Enable button block options for other width sizes

### ISSUE THREAD

**Issue by bahiirwa** [WordPress/gutenberg#49652]
## What problem does this address?
![Screenshot 2023-04-07 at 09 29 37](https://user-images.githubusercontent.com/7713923/230554402-05595e3c-681f-4702-985c-12a22b96c8e7.png)

Looking at the [Buttons block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/button/edit.js#L51)
This request seeks to provide an option for the button block to allow more options for other width sizes like 33% and 66%.
More requests for other sizes might come in so having a hook-like option would be helpful.

## What is your proposed solution?
If there was a hook to add more options or even have this in the theme.json as 
```
"blocks": {
	"core/button": {
		"widthSettings" : [ '33', '66' ]
	}
}
```

**Comment by kevin940726** [comment]
Maybe instead of adding more default options or providing hooks, we can just provide the ability to set custom width like in other settings? Here is an example of the typography size option:

![image](https://user-images.githubusercontent.com/7753001/231089369-f8c5a8b1-2705-4ddb-9430-02277cb23cda.png)

**Comment by stokesman** [comment]
Allowing Button as a child of Row/Stack blocks (as in #35192) is an idea that could solve this since they have dimension support.

**Comment by skorasaurus** [comment]
Hi, Thanks for reporting. 

This can be consolidated into https://github.com/WordPress/gutenberg/issues/26368 which allows for custom widths
