### ISSUE TITLE
Styles: Changing the Layout, Padding, and Block Spacing values causes error

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#49666]
### Description

This was found as part of the [FSE Outreach Program's Build a Block Theme Exploration:](https://make.wordpress.org/test/2023/03/29/fse-program-exploration-build-a-block-theme/#comment-2979)

>I’m just getting started, but I’m getting errors when I try to change the Content Widths under Global Styles > Layout.
I also can’t change the Padding or Block Spacing. I can add Layout Settings on individual Group Blocks inside the Template and Template Parts (index.html, only right now, and header.html and footer.html.

### Step-by-step reproduction instructions

1. Open Site Editor using WP 6.2 and GB 15.5.0
2. Edit any template
3. Open Styles
4. Head to Layout
5. Try to change the content width values
6. See error

### Screenshots, screen recording, code snippet

>TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at er (https://fse-block-theme-exploration.instawp.xyz/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=65c2a14c9bcef52f178e:7:19441)
    at https://fse-block-theme-exploration.instawp.xyz/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=65c2a14c9bcef52f178e:7:19481
    at Array.map (<anonymous>)
    at er (https://fse-block-theme-exploration.instawp.xyz/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=65c2a14c9bcef52f178e:7:19452)
    at https://fse-block-theme-exploration.instawp.xyz/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=65c2a14c9bcef52f178e:7:19481
    at Array.map (<anonymous>)
    at er (https://fse-block-theme-exploration.instawp.xyz/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=65c2a14c9bcef52f178e:7:19452)
    at https://fse-block-theme-exploration.instawp.xyz/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=65c2a14c9bcef52f178e:7:19481
    at Array.map (<anonymous>)

https://user-images.githubusercontent.com/26996883/230650811-8d07c373-f4fe-4d46-b16c-e27eec4ddb39.mov

### Environment info

- WP 6.2
- GB 15.5
- TT3
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by paaljoachim** [comment]
I believe that @tellthemachines and @andrewserong have been working on layout things.

**Comment by tellthemachines** [comment]
This has been fixed in #49465.

**Comment by andrewserong** [comment]
It turns out that the fix (#49465) didn't make it into Gutenberg 15.5.0, so I've cherry-picked it into the release/15.5 branch in https://github.com/WordPress/gutenberg/commit/eab4da1305d1f1b75c745aeb0a17a2af48b888bf, and pushed a minor Gutenberg release in [15.5.1](https://github.com/WordPress/gutenberg/releases/tag/v15.5.1).

I'll close out this issue now, but feel free to reopen if the issue crops up again in GB >= 15.5.1.
