### ISSUE TITLE
Project Gutenberg

### ISSUE THREAD

**Issue by JeromeCrecy** [WordPress/gutenberg#4967]
Aside the good job on the product you are developping, I'would like to report the main bug of project.
And that's : its name.

Project Gutenberg is already an old and Very respectable Project. I'm not involved in this project But I think that you project should not have the same name.  That's confusing. And it doesn't respect the work made by web pioneers.

https://www.gutenberg.org/

**Comment by jasmussen** [comment]
I'm going to close this ticket in favor of #4681, whose meta goal is the same, stop using the name.

I've always seen "Gutenberg" as just a project name, or a codename, one that would go away as soon as the project graduated and were added to WordPress. I would imagine it's mostly meaningless for any casual WordPress user.

**Comment by StaggerLeee** [comment]
OK. As you wish and as it ends, the same for me.
Just think about search engines and keywords when we will be forced to search solutions and snippets.

I think wordpress gutenberg something else typed in Google will give us best results for a minute. But, wordpress block something else will drive us crazy.
