### ISSUE TITLE
Site editor not parsing correctly certain special characters

### ISSUE THREAD

**Issue by nuriapenya** [WordPress/gutenberg#49684]
### Description

I created a site called `TOTORO'S BLOG`, and for some reason when landing on the Site editor the `'` is not properly parsed. It doesn't happen with other characters like @#!...

![image](https://user-images.githubusercontent.com/7931304/230890957-8fc17ef4-d373-4acb-bf1b-ea3652626635.png)
<img width="781" alt="Screenshot 2023-04-10 at 13 18 51" src="https://user-images.githubusercontent.com/7931304/230891970-b3e2c40e-9123-408f-8f01-7b3665b90cca.png">

I tested on different themes and it's the same result.

### Step-by-step reproduction instructions

1. Create any site in any flow. 
2. Change the title to `TOTORO'S BLOG`
3. Check the Site Editor 

### Environment info

- WordPress.COM
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
@youknowriad I can reproduce this, do you think this might be a quick win?

**Comment by youknowriad** [comment]
yep let me see what I can do.
