### ISSUE TITLE
Gallery Block: Align center adds 'display: block' in editor, breaking flexbox

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/gutenberg#4968]
## Issue Overview
When you add a Gallery block and align it center, it loses whatever columns styles it has, and displays all images in a single column. This appears to be coming from the `display: block` on the `.gutenberg__editor .aligncenter` selector here, which is overriding the `display: flex`: 

https://github.com/WordPress/gutenberg/blob/b6b211133821550a7c06e5a781103aa9fcf07dac/edit-post/assets/stylesheets/main.scss#L148

This is not happening with the released version of the plugin (v2.1.0). It's only happening for me with dev version (when I clone the GitHub repo and build locally).

## Steps to Reproduce (for bugs)

1. Start with a test site using a cloned version of the GitHub repo for the Gutenberg plugin, not the one downloaded from WordPress.org.
2. Add a gallery block and add at least three images
3. Look at preview - it'll display using the default three-column style
4. Now align the block centre

## Expected Behavior
The gallery will maintain its columned layout.

## Current Behavior
The gallery will lose its columns, and stack the images in one column.

## Screenshots / Video

How the gallery block looks without center alignment:

![](https://cldup.com/QS-8kryn_d-3000x3000.png)

After adding center alignment:

![](https://cldup.com/Y0Jw39N7qF-3000x3000.png)

**Comment by jasmussen** [comment]
Great ticket. I think I fixed it in the above PR ☝️
