### ISSUE TITLE
Time To Read Block - Translations are ignored

### ISSUE THREAD

**Issue by masteradhoc** [WordPress/gutenberg#49694]
### Description

Thanks @t-hamano for the great Time to Read Block. Im trying to integrate it and found one small issue in regards to translations
Although my user and also my site is in german im still getting the english translations although it seems they are translated correctly here: https://translate.wordpress.org/projects/wp-plugins/gutenberg/stable/de/default/?filters%5Bterm%5D=minut&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

### Step-by-step reproduction instructions

1. Create a Page
2. Add the Time to Read Block
3. visit the frontend and check if it shows in your set language (other than english!)
4. check if strings are translated in the translation files (f.e. german here)
https://translate.wordpress.org/projects/wp-plugins/gutenberg/stable/de/default/?filters%5Bterm%5D=minut&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

### Screenshots, screen recording, code snippet

See the difference between the translated date (month) and the not translated "minutes" of the Time to Read Block.
![image](https://user-images.githubusercontent.com/6242098/230986354-103e2c14-8d6f-4fea-9fe7-6fc117534ac1.jpeg)

### Environment info

- newest WordPress
- newest Gutenberg Version
- Edge Browser

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
I was able to replicate this in another language:

- WP 6.2
- Gutenberg 15.5.0
- Language set to Español (ES) - [translations](https://translate.wordpress.org/projects/wp-plugins/gutenberg/stable/es/default/?filters[term]=minut&filters[term_scope]=scope_any&filters[status]=current_or_waiting_or_fuzzy_or_untranslated&filters[user_login]=&filter=Apply+Filters&sort[by]=priority&sort[how]=desc)

One interesting thing I noticed is that the word "minutes" _did_ correctly display in Spanish in the Editor, even though the front end still displayed English.

### Editor

<img width="418" alt="Editar_la_página___Testing_Testing_123_—_WordPress" src="https://user-images.githubusercontent.com/7662449/230983292-99ae39b7-f67c-4408-a1a3-d18777957dd2.png">

### Front End

<img width="137" alt="Testing_Testing_123" src="https://user-images.githubusercontent.com/7662449/230983379-7bb7eff6-c935-4f4f-9ea9-e094034a9232.png">

**Comment by masteradhoc** [comment]
@kathrynwp good note, same here. 👍🏻

**Comment by t-hamano** [comment]
Thanks for the PR.

This issue should be fixed in #49704, but I can't explain why yet, I would like to investigate 😅
