### ISSUE TITLE
Time To Read Block - Add Color Options

### ISSUE THREAD

**Issue by masteradhoc** [WordPress/gutenberg#49692]
### Description

Thanks @t-hamano for the great Time to Read Block. Im trying to integrate it and found one small issue.
Compared to the Paragraph Block its missing a Color Option to adjust Text and Background Color.

![image](https://user-images.githubusercontent.com/6242098/230931498-9ae335a2-5e59-451e-bc89-03e5c30f5ab5.png)

Would be glad if this can be added

### Step-by-step reproduction instructions

1. Create a Page
2. Add the Time to Read Block
3. try to adjust the color and background color without css directly in the block

### Environment info

- newest WordPress
- newest Gutenberg Version
- Edge Browser

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@masteradhoc 

Thank you for your feedback. Color support for the Post Time To Read block has been added in #49496 and will be part of Gutenberg 15.6. Please give it a try when 15.6 is released 👍
