### ISSUE TITLE
Can't apply `padding` for `core/button` block in `theme.json`

### ISSUE THREAD

**Issue by cawa-93** [WordPress/gutenberg#49709]
### Description

I have `styles.blocks["core/button"].spacing.padding.top: 400px` but it doesn't apply to any buttons at all. 
Padding allying only if I specify it for `variant`: `styles.blocks["core/button"].variations.fill.spacing.padding.top: 400px`. But in this case:
1. I'm forced to specify same paddings for each variant. 
2. Paddings actually aplies to `is-style-fill` class, but by-default this class actually not set. So I'm forced to switch style to `outline` and switch it back to add  `is-style-fill` class each time I add button block. 

### Step-by-step reproduction instructions

1. Create theme with `theme.json`
	```json
	{
		"$schema": "https://schemas.wp.org/wp/6.2/theme.json",
		"version": 2,
		"styles": {
			"blocks": {
				"core/button": {
					"spacing": {
						"padding": {
							"bottom": "100px",
							"left": "200px",
							"right": "300px",
							"top": "400px"
						}
					}
				}
			}
		}
	}
	```
2. In editor, add button block.

### Environment info

- WordPress 6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thank you for the report.

I have updated TT3's theme.json with your code and it appears to be working correctly. You may want to check the browser developer tools to see if any styles exist that override the styles in theme.json.

![theme](https://user-images.githubusercontent.com/54422211/231165149-a5c67b2c-0308-4a1e-9845-73aa4bb50643.png)

**Comment by cawa-93** [comment]
That's the point. In my case padding always are `var(--wp--preset--spacing--30)`

![зображення](https://user-images.githubusercontent.com/1662812/231167897-7329fd79-b56f-4527-abad-7f6dcda50f01.png)
And I don't understand why. 

My `theme.json` litterally is 
```json
{
	"$schema": "https://schemas.wp.org/wp/6.2/theme.json",
	"version": 2,
	"styles": {
		"blocks": {
			"core/button": {
				"spacing": {
					"padding": {
						"bottom": "100px",
						"left": "200px",
						"right": "300px",
						"top": "400px"
					}
				}
			}
		}
	}
}
```
No plugins, empty `functions.php` and `styles.css`

**Comment by t-hamano** [comment]
It appears that the padding defined in theme.json is not being output.

Can you please check if the same problem occurs when you switch to Twenty Twenty Three and replace theme.json with the code you provided?

**Comment by cawa-93** [comment]
Yeah. I'm idiot. `them.json` styles for some reason was overwritten by styles from site-editor. Sorry for time-wasting.
