### ISSUE TITLE
WooCommerce Home disappearing with recent update

### ISSUE THREAD

**Issue by Thelmachido** [WordPress/gutenberg#49717]
### Description

When Gutenberg is active WooCommerce > Home is returning a blank page. This is happening due to the recent update as [per this forum issue](https://wordpress.org/support/topic/gutenberg-v15-5-x-causing-conflict-to-woocommerce-7-5-1/). 

The result is consistent on a classic and block theme TT1 & TT3  

### Step-by-step reproduction instructions

1. With Gutenberg Version 15.5.1 activate the WooCommerce plugin
2. From your dashboard try to open WooCommerce > Home 
3. You will see a blank page as per the screenshot below

### Screenshots, screen recording, code snippet

<img width="1429" alt="Screenshot 2023-04-11 at 12 39 31" src="https://user-images.githubusercontent.com/41231764/231137578-c0b4952e-e5ea-445b-b537-2afd6d32ccc7.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
It appears that the woocommerce GitHub project is aware of this issue and the PR has already been merged:

[Fix issue that breaks the WooCommerce Home Page when Gutenberg 15.5 is active #37641](https://github.com/woocommerce/woocommerce/pull/37641)

Therefore, I would like to close this issue.
