### ISSUE TITLE
Classic Theme: Template parts editor does not allow access when reloading page

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#49713]
### Description

In the classic theme with block template parts enabled, the following error message appears when reloading the screen in the template parts menu:

![error](https://user-images.githubusercontent.com/54422211/231112679-19c14a4b-4f6f-4dcd-b4ef-266b3a522ffc.png)

The template parts can be edited and saved normally.

### Step-by-step reproduction instructions

Use the following files to create a simple classic theme. Alternatively, use the zip file below to install the theme:

[testtheme.zip](https://github.com/WordPress/gutenberg/files/11198745/testtheme.zip)

`testtheme/style.css`

```css
/*
Theme Name: Test Theme
*/
```

`testtheme/functions.php`

```php
<?php
function my_theme_setup() {
	add_theme_support( 'block-template-parts' );
}
add_action( 'after_setup_theme', 'my_theme_setup' );
```

`testtheme/index.php`

```php
<?php
// Silence is golden.
```

`testtheme/parts/test.html`

```html
<!-- wp:paragraph -->
<p>Hello World</p>
<!-- /wp:paragraph -->
```

- Access "Appearance > Template Parts"  menu.
- Reload your browser.
- Confirm that the error message is displayed.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/231113818-45a4f1b5-524e-4678-a9b2-917986f27fd7.mp4

### Environment info

WordPress Version: 6.2
Gutenberg Version: 15.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I think the following PR sent to core will resolve this issue, so I will retest when that PR is merged.

https://github.com/WordPress/wordpress-develop/pull/4893

**Comment by Mamaduka** [comment]
Yes, that core PR should resolve the issue.

**Comment by Mamaduka** [comment]
@t-hamano, can you retest with the latest RC?

**Comment by t-hamano** [comment]
I have confirmed that WordPress 6.3 RC2 has resolved this issue 🎉

https://github.com/WordPress/gutenberg/assets/54422211/5229a5de-4a82-40c9-91eb-aa8f6ce15c0e
