### ISSUE TITLE
Add "Advanced Settings" Support to Custom HTML Block

### ISSUE THREAD

**Issue by samxmunoz** [WordPress/gutenberg#49726]
## What problem does this address?
There are no Advanced Settings options for Custom HTML Block - which is unfortunate because I'd like to be able to assign an HTML Anchor and Additional CSS Class(es) to this block without wrapping it in a group.

<img width="499" alt="Screen Shot 2023-04-11 at 1 19 23 PM" src="https://user-images.githubusercontent.com/43501707/231240289-7b68744e-b809-4d27-a69c-388dffb705a1.png">

## What is your proposed solution?

Support HTML Anchor and Additional CSS Class(es) for the Custom HTML Block.

<img width="270" alt="Screen Shot 2023-04-11 at 1 17 10 PM" src="https://user-images.githubusercontent.com/43501707/231240266-36c6ea56-9992-4728-8553-64dd6bfa5074.png">

**Comment by CreativeDive** [comment]
There's really no reason why the HTML block shouldn't also get a wrapper. The user is used to it and the custom anchor can then be activated as usual via block.json. It's more of a break at the moment as this block doesn't get a wrapper like all the others.

**Comment by aurooba** [comment]
I'm playing around with a PR for this. Perhaps we can make it so that a wrapper is _only_ added it there is an anchor or additional classname added in the `Advanced` panel. That way, folks who want to add HTML without any wrappers can do that and folks who want a wrapper can have it when needed.

**Comment by pattonwebz** [comment]
I have also run into this issue before and used the 'wrap in a group' workaround for it but it would be nice to have these options be native to the block itself.

That being said I think a _conditional_ wrapper only if these settings are filled means more code complexity and in the content could cause some unexpected situations with markup that is sometimes one thing and sometimes another thing. I wonder if there is a solution that doesn't create added complexity (both in code and in the maintenance of the content).

**Comment by carolinan** [comment]
The HTML block places the HTML you entered into it on your page; having a wrapper by default would make some designs impossible because of the inheritance of the CSS. Adding it would also break lots of existing sites.
If you need a wrapper, a CSS class, or an anchor, you can add that as part of your custom HTML; that is the strength of the HTML block.

**Comment by Mamaduka** [comment]
I agree with @pattonwebz. Using a conditional wrapper will introduce implicit behavior that can be unexpected for the users and probably generate support requests.

As @carolinan and @ndiego [mentioned](https://twitter.com/nickmdiego/status/1645841476964986880), the wrapper elements and all attributes can be provided manually with HTML block's content.

**Comment by t-hamano** [comment]
I, too, am concerned that introducing advanced settings and conditional wrappers will create new problems. I realize that the purpose of this block is to allow the front end to display the HTML code _as written_ by the user. For users who can write HTML, manually adding id and class attributes should not be difficult.

This block can also embed styles and scripts as well as HTML elements. If the anchor or class were applied to the block, unnatural HTML would be generated (while such HTML is not incorrect).

```html
<div id="anchor" class="wp-block-html custom">
  <style>.selector{font-size: 20px;}</style>
  <script>console.log('log')</script>
</div>
```

**Comment by talldan** [comment]
@samxmunoz It'd be good to share some use cases for this.

I find it difficult to imagine them, because as others have mentioned the HTML can be updated to add those attributes.

I suppose one is for users who're unfamiliar with HTML, but then would those users be adding an anchor and class name? The reason those properties are in the advanced section is because they require some HTML knowledge.

**Comment by carolinan** [comment]
I think the HTML block is being used to create something that the editor does not yet support.
Like copy-pasting an unsupported embed, and perhaps that underlying issue could be solved?

(I am loosely basing that on previous support request from other users)

**Comment by carolinan** [comment]
I also know users and developers are using this to add HTML buttons.

**Comment by CreativeDive** [comment]
@aurooba solution sounds like a good compromise. For no-code users who just want to add an HTML snippet from another source, this is a good solution. And all coders can use the HTML block as before.

**Comment by samxmunoz** [comment]
HTML embed blocks aren't just for things that the block editor can't do yet. 

For example, they are also used for things like embed codes provided by CRMs - like an email opt-in form (this is the use case where I ran into trouble).

Plenty of users will use the HTML embed block for this purpose & not know any of the code they are copying & pasting in (and be afraid / not know how to add a "wrapper") to this code that they didn't write. Although *I* can write this code for _my_ site, I don't know that every average user (especially the no/low-code user WordPress has been focusing on) can.

I understand both sides of the argument - and the workaround / solution to write the HTML anchor into the block itself, but in the case described above I don't think it's a reasonable expectation for that user to know how to write the HTML (whereas the HTML anchor is easy, and no-code and used for anchored links primarily by this type of user).

**Comment by carolinan** [comment]
That's what I meant. That embed code from source ABC might not work without the HTML block. We should make it work by just copy-pasting it into the editor, anywhere. (Or even better, that supplier should make sure they have a custom block for their service)

**Comment by samxmunoz** [comment]
Ahh I see - how would that look practically @carolinan? You would just copy an embed code + paste it into the UI (and some appropriate block would show up? Or would it be block-less?)

I definitely like the latter "suppliers should make sure they have a custom block for their service" - that would be something!

**Comment by carolinan** [comment]
For example, if you copy-paste a youtube video, it just works. The editor transforms it into an embed
But copy-pasting a google map iframe embed code does not work (I don't know how many support requests I have had for that)

**Comment by aurooba** [comment]
Honestly, I played with the code a little and I agree. Adding a conditional wrapper will have unintended side effects that are not worth the effort.

I think it's unrealistic that there would be a block for every custom service and embed out there, so while I can appreciate the sentiment, I'm not sure that's necessarily the right answer in every case.

Wrapping things in the `Group` block when we need extra settings is the right option here. So I'm wondering, what can we do to make that seem like the appropriate solution rather than feel like a workaround? To me, this then sounds like a bit of an education piece.

**Comment by justintadlock** [comment]
> So I'm wondering, what can we do to make that seem like the appropriate solution rather than feel like a workaround? To me, this then sounds like a bit of an education piece.

I'd file something here: https://github.com/WordPress/Documentation-Issue-Tracker/

**Comment by jordesign** [comment]
To summarize the discussion on this issue - closing it as a "won't-fix" as adding a wrapper to allow things like a class could have unintended affects on the output.
