### ISSUE TITLE
Spinner at the bottom when image is loading in gallery

### ISSUE THREAD

**Issue by Rahmon** [WordPress/gutenberg#4973]
## Issue Overview
I was investigating the issue #4364 and now the spinner is at the bottom.

![screenshot from 2018-02-09 08-04-52](https://user-images.githubusercontent.com/6010232/36022349-f83ad874-0d6f-11e8-9093-f70f4e8bd151.png)

Moreover when I select the figure the caption is over the spinner:

![screenshot from 2018-02-09 08-07-40](https://user-images.githubusercontent.com/6010232/36022452-5870da90-0d70-11e8-9067-b75ce933ae30.png)

## Expected Behavior
Spinner aligned vertically and horizontally

## Current Behavior
Spinner at  the bottom left.

## Related Issues and/or PRs
https://github.com/WordPress/gutenberg/issues/4364
https://github.com/WordPress/gutenberg/pull/4199

**Comment by twsp** [comment]
I'm having trouble recreating this issue.  What are you doing in your gallery to create an image figure of that size that contains a spinner that persists for long enough to analyze the issue?  For a second, I was managing to get a spinner to appear, but the figure did not have the height of the original image.  And now when I upload an image, it uploads quickly and does not let me see the spinner.

**Comment by Rahmon** [comment]
@twsp I did a change in gallery-image.js (https://github.com/WordPress/gutenberg/blob/ca74bb38f08dba1f41f18ef6aad406b2b27406f7/blocks/library/gallery/gallery-image.js#L88) file to show the spinner for a specific image. So I was able to analyze.
