### ISSUE TITLE
Cannot press "Enter" or "Return" to add a social link

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#49764]
In the existing LinkControl UI, I can add a URL, then press "Enter" and it is applied. But when adding social links, that flow no longer works—you are required to `tab` + `enter`, or manually press the arrow icon. 

As an aside (which would resolve this as well), this could probably use the LinkControl component (https://github.com/WordPress/gutenberg/issues/49091). Perhaps there's a prop to _only_ allow custom URLs. 

https://user-images.githubusercontent.com/1813435/231508842-93df963d-edac-4b24-b10f-60d2dcf6d731.mp4

**Comment by Mamaduka** [comment]
It's probably a regression after #40906.
