### ISSUE TITLE
Add New template in Manage All Template section not clickable on smaller screen sizes

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#49770]
### Description

Passing on a report from @nomad-skateboarding-dev where on smaller screen sizes the "Add New" option for templates and template parts in the list view is not clickable. 

### Step-by-step reproduction instructions

1. Open the Site Editor
2. Navigate to Templates or Template parts
3. Select the manage all option
4. Make the screen size smaller and try to click "Add New". Notice it doesn't respond.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/231538384-99a4ef98-5ebc-4d7a-987b-5714ccd6598e.mov

### Environment info

- WP 6.2
- GB 15.5.1
- TT3
- Chrome on MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
That is intentional, at least for now. See https://github.com/WordPress/gutenberg/pull/47777#issuecomment-1419450921 for more details.

**Comment by annezazu** [comment]
Hmm got it. I'm going to leave this open for now since I agree with the commentary there that it isn't ideal.

**Comment by nomad-skateboarding-dev** [comment]
Thank you sincerely @annezazu 🙏 Thank you @Mamaduka for checking.

**Comment by youknowriad** [comment]
I think this solved now.
