### ISSUE TITLE
Avatar block not 1:1 between the editor and the front-end

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#49775]
There is an inconsistency between the editor and front-end renders of the core/avatar block. 

Setting a `line-height: 0;` to the top-level `.wp-block-avatar` element resolves this. 

#### Editor: 

<img width="684" alt="CleanShot 2023-04-12 at 14 38 43" src="https://user-images.githubusercontent.com/1813435/231553763-0c1a0d09-2975-439f-b442-57d4e7142bb0.png">

#### Frontend: 

<img width="685" alt="CleanShot 2023-04-12 at 14 38 52" src="https://user-images.githubusercontent.com/1813435/231553701-7234c056-72e1-4707-8535-e338567417a4.png">

**Comment by Anurag-Raut** [comment]
![image](https://user-images.githubusercontent.com/102049482/231657343-865bf979-3c6e-4095-840f-fd20880d98e0.png)
should I add "line-height: 0;" here?

**Comment by richtabor** [comment]
Yea, that would do it.

**Comment by xerpa43** [comment]
can i work on this?

**Comment by aditya-mistri** [comment]
I would like to work on this issue , please assign the issue to me
