### ISSUE TITLE
[Private APIs] Modify consent phrase for WP 6.4 relase.

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#49784]
## What problem does this address?

The Private APIs package includes a consent phrase for developers to dangerously opt-in to the use of private APIs, for WordPress 6.2 the phrase is `I know using unstable features means my plugin or theme will inevitably break on the next WordPress release.`

The package warns extending developers this phrase may change at any time, preventing the further use of these features.

## What is your proposed solution?

During the WordPress 6.3 cycle this ought to be updated to further discourage extending developers from attempting to opt-in to the features. I suggest it be done relatively late in the cycle.

cc @adamziel @youknowriad

**Comment by adamziel** [comment]
I agree, let's actually do what this string says will happen.

**Comment by youknowriad** [comment]
Sounds good to me.

**Comment by peterwilsoncc** [comment]
@adamziel @youknowriad This was missed for 6.3, I've created #55182 in the hope we can change the string for 6.4.

**Comment by peterwilsoncc** [comment]
I've switched this over to a task after discussing it with @hellofromtonya
