### ISSUE TITLE
Images are stretched if image have height attribute specified and width larger than edit area

### ISSUE THREAD

**Issue by diego-betto** [WordPress/gutenberg#4979]
## Issue Overview

Images are stretched if image have height attribute specified.

## Steps to Reproduce (for bugs)

1. open a old post where an image has width / height attributes larger than edit area, like `<img class="size-full" src="...." alt="" width="826" height="119" data-mce-src="...">`

Chrome 64.0.3282.140 @ Win 10

## Expected Behavior

the image should have a proportional height

## Current Behavior

image keeps height specified in the attribute

## Possible Solution

.gutenberg__editor img {
    max-width: 100%;
    **height: auto;**
}

## Screenshots / Video

![Screenshot](https://diegobetto.com/tmp/gutenberg_bug_image.png)

**Comment by youknowriad** [comment]
I think this has been fixed by #4752

**Comment by SilvanBauser** [comment]
> I think this has been fixed by #4752

This is still reproducable in v4.3.0
