### ISSUE TITLE
Unclear how to enable controls after typing

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#498]
Once you type in an editable field, the controls disappear, and it is unclear how to make them show again. The only way seems to be to select another block, and then select then old one again.

Maybe we should always show controls on `mousedown touchstart`?

**Comment by youknowriad** [comment]
Yep I think this is a bug and they should reappear when clicking. Like the prototypes.

**Comment by iseulde** [comment]
Cool, I'll have a look then.

**Comment by iseulde** [comment]
Unassigning for now because I already have some high priority ones.

**Comment by mtias** [comment]
The original intention was that controls would appear on mouse move after typing on the selected block.

**Comment by iseulde** [comment]
It seems like mousedown/touchstart and some keys might be enough. Mousemove seems like something that is hard to do across different devices, and might also be a bit distracting.

**Comment by mtias** [comment]
If I'm typing and I want to switch to bold, I don't want to click on anything because the block is already focused. The hiding of the formatting while typing is mainly to avoid distraction, but as soon as I switch from typing to moving the cursor (one example) the controls should become visible.

**Comment by iseulde** [comment]
Wouldn't you have to select the text first, or put the caret on the word?

**Comment by mtias** [comment]
I mean in the case where I want to switch to italics before writing what I want to be in italics.

**Comment by iseulde** [comment]
Yeah, I guess I thought in that case people would more often use keyboard/text shortcuts for continuous typing, whereas the UI would be used more to format afterwards.

**Comment by mtias** [comment]
Yes, probably. Let's see how #556 feels.

**Comment by mtias** [comment]
There's also the case of having to reselect the block to access the other controls, like alignment.

**Comment by iseulde** [comment]
Fair enough. Let's try adding to it gradually and see how it feels. :)

**Comment by jasmussen** [comment]
Good thoughts here already. Here's how I've been thinking of it. 

Everything is a block. Hovering over it indicates the extent of the block. But when you click a block, or arrow-key into it, that block now is now _selected_, and it is selected until you select another block. Even if you start typing, the block is still technically selected. 

All block boundaries & controls fade out as soon as you start typing, so you can focus on the content. But as soon as you move the mouse, the boundaries & controls fade in again, as this indicates you might want to manipulate the blocks. Keep in mind mobile is slightly different in that the formatting is docked at the top of the screen always. 

☝️  this is how I've been picturing it. It's okay to revisit or think of other approaches, but it's a key value that blocks feel "blocky and manipulable".

**Comment by mtias** [comment]
Let's close this as it's working better now, and open a task to explore mousemove.
