### ISSUE TITLE
Workflows: Component CHAGELOG update check fails on PR from forked repository

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#49817]
### Description

Tested on #49816

A workflow has been introduced in #49443 to check for updates to the CHANGELOG file of component packages. This workflow does not appear to work for PRs submitted from forked repositories.

### Step-by-step reproduction instructions

The complete procedure I followed is as follows:

- Clone the Gutenberg repository on GitHub
- Run ` git clone https://github.com/{my-username}/gutenberg.git`
- Make changes to the `.js` file in the components package
- Commit, push, and submit a PR
- Confirm @wordpress/components CHANGELOG update runs
- [Workflow fails](https://github.com/WordPress/gutenberg/actions/runs/4696177434/jobs/8326027596) (expected)
- Make changes to the `/packages/components/CHANGELOG.md` file
- Commit and push
- Confirm @wordpress/components CHANGELOG update runs
- [Workflow fails](https://github.com/WordPress/gutenberg/actions/runs/4696197649/jobs/8326067289?pr=49816) (not expected)

**Comment by t-hamano** [comment]
It might be necessary to rewrite part of the GitHub Action, like this PR

[fix: ce spec action for PRs from forks by vishnu-narayanan · Pull Request #4587 · chatwoot/chatwoot](https://github.com/chatwoot/chatwoot/pull/4587)

**Comment by chad1008** [comment]
Thanks for testing and troubleshooting @t-hamano, that does indeed look like exactly what we needed. I've made the necessary change in #49906 and it's testing well for me from a forked repo!
