### ISSUE TITLE
Outline for the "menus" section

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#49829]
Trying to capture here the approach for the "menus" section of the "design" subgroup, which was pulled out from 6.2 late in the cycle due to user experience shortcomings.

The overall goal of this panel is to allow users and site maintainers to be able to access, navigate, and modify their menus without having to find them in a specific template in the site editor.

The challenges are — as per usual with menus — that the spectrum of complexity goes from simple sites where a menu is a 1:1 map to the user's pages all the way to large sites with multiple menus or mega-menus where data and presentation are more intertwined.

---

So here's an outline of the basic use cases to address:

### Only one menu

- **Made of a single page list** — we display the page list block and allow the normal edit operations we have on the navigation block itself (syncs pages by default; if reorder, then it doesn't, etc). Selecting a page goes into the details view of that page as normal.
- **Made of mostly page items** — if it's a custom menu but with a few additions (like a search block) we still allow editing directly. If we detect blocks that are not just page list or links, we should allow editing the block as a focused template part by having some icon button for it prominently. (These nav menus are operating both as high level data structure and template parts.)

### Multiple menus

- All menus are displayed by default as a list and don't try to do a "main navigation" outside of maybe grouping things differently. (A label for "main nav" and then "other menus".) Each menu can afford a drilldown level which goes back to the "only one menu" items.

**Comment by jasmussen** [comment]
Consolidating this one on #49829. Let's make some progress on it.

**Comment by annezazu** [comment]
@jasmussen a bit confused here as you seem to be closing out a number of issues and attempting to link to a different issue but linking to the same issue itself. What do you mean to be linking to here? I wasn't quite sure!

**Comment by jasmussen** [comment]
Oh no, my apologies, my copy paste skills failed me! I meant to close this one in favor of #50396, which is more or less the same.
