### ISSUE TITLE
Theme.json: Using Variations duplicates CSS selector output

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#49835]
### Description

I'm experimenting with the following code in theme.json to style buttons that have the Outline block style:

```
	"styles": {
		"blocks": {
			"core/button": {
				"variations": {
					"outline": {
						"color": {
							"background": "transparent"
						},
						"spacing": {
							"padding": {
								"bottom": "14px",
								"left": "29px",
								"right": "29px",
								"top": "14px"
							}
						}
					}
				}
			},
```
The CSS is working, but the selectors seem to be duplicated (two instances of .is-style-outline) per the screenshot below:

`.is-style-outline.is-style-outline.wp-block-button .wp-block-button__link {}`

![image](https://user-images.githubusercontent.com/486261/232069166-1f0f6b7f-bae8-47ce-a842-0b1a37dd49a9.png)

### Step-by-step reproduction instructions

1. Apply code above to theme.json.
2. Create a button using the Outline style.

### Environment info

WordPress 6.2, Gutenberg NOT installed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
The duplication of class names in the variations appears to be intentional to override the style of the core block:

https://github.com/WordPress/gutenberg/blob/1069f48d6e41949f9b84566265ffb989fb941522/lib/class-wp-theme-json-gutenberg.php#L893-L894

This code can also be found in the WordPress core:
https://core.trac.wordpress.org/browser/trunk/src/wp-includes/class-wp-theme-json.php#L897

**Comment by bgardner** [comment]
@t-hamano Interesting. I removed the first instance in the Inspector for my use case and it still seemed to override the style of the core block. Perhaps other blocks require this and that's why it's there, dunno.

**Comment by t-hamano** [comment]
Indeed, it appears that the core block styles can be correctly overridden without duplicate CSS class names.

@tellthemachines 

I believe this feature was added in #46343, is there a problem with removing duplicate CSS class names?

![style](https://user-images.githubusercontent.com/54422211/232177116-55a993fe-950c-4720-9ac9-f71e1afc14ea.png)

**Comment by jacobcassidy** [comment]
Was this confirmed as intentional? The duplicate classes add the unnecessary need for greater specificity when adding custom CSS.

**Comment by tellthemachines** [comment]
The increased specificity is intended to override some core block styles. It's not needed for all blocks; Image variations generally work fine without it, but Button styles don't. Try setting a non-transparent background-color to the Button outline variation, remove the duplicate classname, and you'll see it doesn't work.

A possible alternative to the duplicate classname would be to decrease the specificity of core variation styles. That could cause breakage in themes that are relying on that specificity though.

**Comment by t-hamano** [comment]
Thanks forthe reply, @tellthemachines.

> Try setting a non-transparent background-color to the Button outline variation, remove the duplicate classname, and you'll see it doesn't work.

I was able to confirm this behavior by following the steps below.

- Activate Emptytheme
- Update theme.json as below to apply background to button:
  ```json
  {
  	"$schema": "https://schemas.wp.org/trunk/theme.json",
  	"version": 2,
  	"settings": {
  		"appearanceTools": true,
  		"layout": {
  			"contentSize": "840px",
  			"wideSize": "1100px"
  		}
  	},
  	"styles": {
  		"blocks": {
  			"core/button": {
  				"variations": {
  					"outline": {
  						"color": {
  							"background": "red"
  						}
  					}
  				}
  			}
  		}
  	}
  }
  ```
- Insert a Button block

### If CSS selector is duplicated

![image](https://github.com/WordPress/gutenberg/assets/54422211/c56d7428-e235-4dc2-8c8e-4bee93e2fa35)

### If CSS selector is NOT duplicated

Overridden by the core outline style's transparent background color

![image](https://github.com/WordPress/gutenberg/assets/54422211/19b171fc-e00e-48e1-afcd-55843cee2e23)
