### ISSUE TITLE
Implement multiple select input

### ISSUE THREAD

**Issue by cr101** [WordPress/gutenberg#4984]
Please extend the `select-control` so it supports multi-value selection out of the box. 
The current `select-control` component does not allow the user to select more than one choice. 
The multiple select control could be used to display and select multiple custom taxonomy terms or multiple CPTs.
I recommend that this [react-select](https://github.com/JedWatson/react-select) control is implemented to allow for multi-value selection.

**Comment by youknowriad** [comment]
In general in Gutenberg we're trying to make things available as we use them in the code itself. There's no use-case for such a component right now in Gutenberg so I don't think it makes a lot of sense to add it. 

Also, what's stopping you from using `react-select` directly?

**Comment by youknowriad** [comment]
I'm closing this issue for now. Thanks
