### ISSUE TITLE
SlotFills: Proposal to add a slot to the header toolbar

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#49850]
## What problem does this address?

A large space exists in the header of the post editor. Some developers have added plugin-specific links or buttons to this space.

However, since there is no Slot here, developers have no choice but to insert contents directly by writing code like the following (this code can be tried from the browser console)

```javascript
const headerToolbar = document.querySelector('.edit-post-header-toolbar');
const customHeaderToolbarArea = document.createElement( 'div' );
customHeaderToolbarArea.textContent = 'Custom Content';
headerToolbar.appendChild( customHeaderToolbarArea );
```

![custom-content](https://user-images.githubusercontent.com/54422211/232309916-9f0260fa-4faf-45a5-bc46-0e0dc48dff4c.png)

## What is your proposed solution?

I think adding a slot like `PluginHeaderToolbar` would help many developers.

### Extendify — Gutenberg Patterns and Templates

- https://wordpress.org/plugins/extendify/
- Active installations: 70,000+

![extendify](https://user-images.githubusercontent.com/54422211/232316596-0669fac8-47fd-487e-8749-d3fac83fac9c.png)

### Gutenberg Blocks by Kadence Blocks – Page Builder Features

- https://wordpress.org/plugins/kadence-blocks/
- Active installations: 300,000+

![kadence-blocks](https://user-images.githubusercontent.com/54422211/232316603-d1c35585-3834-42b1-97dd-48f730b60817.png)

### Translate Multilingual sites – TranslatePress

- https://wordpress.org/plugins/translatepress-multilingual/
- Active installations: 200,000+

![translatepress](https://user-images.githubusercontent.com/54422211/232316611-4b901b56-2cf3-48f6-a0fc-94ec5beb8b96.png)

### Genesis Blocks

- https://wordpress.org/plugins/genesis-blocks/
- Active installations: 70,000+

![genesis-blocks](https://user-images.githubusercontent.com/54422211/232316619-90b0e1a2-8273-4326-9e0a-5bb65dd516fa.png)

**Comment by aaronrobertshaw** [comment]
It is worth noting there is ongoing work being done to [overhaul the Top Toolbar](https://github.com/WordPress/gutenberg/issues/40450). There is a pretty high likelihood that directly injecting elements in this unexpected manner will conflict there ([open PR](https://github.com/WordPress/gutenberg/pull/49634)). Lack of horizontal real estate is already an issue with those proposed enhancements without plugins adding more items.

I'd suggest it might be better if we don't further encourage adding items to the toolbar until we see what results from the above issue and PR.

**Comment by Mamaduka** [comment]
@t-hamano, this might be a duplicate of #16988.

P.S. Here's a general discussion on extensibility - https://github.com/WordPress/gutenberg/discussions/37448.

**Comment by t-hamano** [comment]
@Mamaduka Thanks for the info!
I would like to close this issue because it raises the same thing as #16988.
