### ISSUE TITLE
Gutenberg plugin and Rankmath plugin: No analytics 

### ISSUE THREAD

**Issue by reinerschwope** [WordPress/gutenberg#49856]
### Description

I use the gutenberg editor and I like very much. But the analytics side from Rankmath is not working if the gutenberg plugin is working. What I can do?

### Step-by-step reproduction instructions

1. Gutenberg plugin is working
2. Rankmath is not showing the analytics
3. Gutenberg plugin is not activ
4. Rankmath is showing the analytics

### Screenshots, screen recording, code snippet

<img width="1789" alt="Bildschirm­foto 2023-03-27 um 2 21 21 PM" src="https://user-images.githubusercontent.com/113707130/232418887-85f2a65a-96cb-4ed9-a778-088029a12ceb.png">

### Environment info

Version 15.5.1 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I tried opening that page in the following environment and could not reproduce the problem:

- WordPress Version: WordPress 6.2
- Gutenberg Version: 15.5.1
- Rank Math SEO: 1.0.111

For problems that occur with specific plugins, it may be a good idea to report them in [the forum](https://wordpress.org/support/plugin/seo-by-rank-math/) or [on GitHub](https://github.com/rankmath/seo-by-rank-math).

**Comment by t-hamano** [comment]
@reinerschwope

Does this problem still exist today? If possible, it would be great if you could test it with the latest Gutenberg and the latest Rank Math SEO plugin.

**Comment by reinerschwope** [comment]
Dear @t-hamano, the problem was solved. I see the results in the analytics site. I had some communication with the help center from Rank math SEO and then they solved the problem.

**Comment by t-hamano** [comment]
@reinerschwope That's good to know 👍
