### ISSUE TITLE
CheckboxControl doesn't support custom ids

### ISSUE THREAD

**Issue by gsexton** [WordPress/gutenberg#49852]
### Description

 I noticed that on the edit page, when editing a page that has my block embedded, clicking on the label for a block control did not check/uncheck the associated checkbox.

You can see the for clause of the label is not the id specified in the control definition.

### Step-by-step reproduction instructions

1. Define a control:

```
el(
    wp.components.CheckboxControl,
    {
        id: 'cd-rcalendar-wrap', 
        checked: props.attributes.wrap_events,
        label: i18n.__('COM_CONNECTDAILY_WRAPTITLES',CDaily.CAPTION_BUNDLE),
        onChange: function( value ){ setAttributes({wrap_events: value});}
    }
)
```
2. Insert the control.
3. Right click on the wrap events attribute, and choose the browser's inspect tool.
4. Observed Behavior: The control is rendered as:
```
<span class="components-checkbox-control__input-container">
<input id="cd-rcalendar-wrap" class="components-checkbox-control__input" type="checkbox" value="1">
</span>
<label class="components-checkbox-control__label" for="inspector-checkbox-control-5">Wrap Event Titles</label>
```

### Environment info

WordPress 6.1.1
Theme: 2020 Theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mirka** [comment]
Confirmed bug. CheckboxControl does not support custom ids. It should support them, similar to InputControl or SelectControl.

Minimim repro:

```jsx
const BadCheckbox = () => {
	const [ isChecked, setChecked ] = useState( true );

	return (
		<CheckboxControl
			label="Click me"
			id="foo"
			checked={ isChecked }
			onChange={ () => setChecked( ! isChecked ) }
		/>
	);
};
```
