### ISSUE TITLE
Transforms: Quote should not be suggested as a transform from a Group

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#49879]
## What problem does this address?

While using the experimental Grid layout, I noticed that the transform menu prioritizes transforming to a Quote block:

<img width="357" alt="Screen Shot 2023-04-17 at 2 14 06 PM" src="https://user-images.githubusercontent.com/26996883/232612314-8d995fe9-ec90-4466-8c0e-5177387a276b.png">

It turns out the same thing happens with the Stack block:

<img width="526" alt="Screen Shot 2023-04-17 at 2 15 59 PM" src="https://user-images.githubusercontent.com/26996883/232612511-e54325b3-46dd-434c-a5b2-3d6ca6ea319d.png">

Semi related: https://github.com/WordPress/gutenberg/issues/49524 and https://github.com/WordPress/gutenberg/issues/39066

## What is your proposed solution?

At the least, update the transforms to show something more relevant like Columns rather than quote. Ideally, I'd like to see the transforms show the variations in full (stack, row, group, grid). 

@WordPress/gutenberg-design since there wasn't consensus [reached on this prior issue](https://github.com/WordPress/gutenberg/issues/39066#issuecomment-1050618563) that reflected how the transforms menu needs to be thought of in a larger way. While I believe that to be true, I also think we need to make some changes to the Group block variations sooner rather than later with so many variations built in now.

**Comment by richtabor** [comment]
> While using the experimental Grid layout, I noticed that the transform menu prioritizes transforming to a Quote block

That's odd, def shouldn't be the case. 

> Ideally, I'd like to see the transforms show the variations in full (stack, row, group, grid).

Agreed. We currently don't have support for block variation transforms in this popover, though we should. Related: https://github.com/WordPress/gutenberg/issues/49584#issuecomment-1496471000

**Comment by richtabor** [comment]
Even the Grid transform to the Cover block is odd.

**Comment by glendaviesnz** [comment]
> Even the Grid transform to the Cover block is odd.

It is just a hangover from the fact that under the hood it is just a Group block, and the Group block has always had a transform to Cover, which makes sense for a standard Group. The transforms have an `isMatch` callback though which is passed a block's current attributes, so it shouldn't be too hard to check if the Group is standard or one of the variations and limit the transform options accordingly.

**Comment by jameskoster** [comment]
💯 if we're going to offer multiple transform methods, I'd say the prioritised transforms should appear in all locations. That means: variations should appear above the horizontal rule in the transforms menu.

This would help with post meta blocks too.

**Comment by richtabor** [comment]
> The transforms have an isMatch callback though which is passed a block's current attributes, so it shouldn't be too hard to check if the Group is standard or one of the variations and limit the transform options accordingly.

Let's roll with this, with a goal of having Quote not suggested for Groups (or its variations).
