### ISSUE TITLE
Calling Embed block from hover menu requires two clicks to activate

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#4987]
## Issue Overview

When I select the Embed block from the menu that appears on mouse over below the last block, I need to click twice to be able to paste the URL to be embedded.
## Steps to Reproduce (for bugs)

1. Add new post
2. Add any block
3. scroll to the end of it and hover with the mouse until menu appears
4. select embed 
5. paste URL

Chrome Version 63.0.3239.132 / Gutenberg 2.1 / WordPress 4.9.4
## Expected Behavior

One click on the embed icon would bring up the embed block form to paste URL
## Current Behavior

I have to click twice to get to the form 
## Possible Solution

Active embed block on first click
## Screenshots / Video

Video shows first embed via the inserter icon below the previous block, then you see the behavior when selecting the embed icon from the hover menu. 
https://photos.app.goo.gl/4pAUuyx33evUAkG42
## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
This seems fixed to me in master. The embed URL input is auto-focused when you insert an embed block. Please feel free too reopen if it's not the case.
