### ISSUE TITLE
Site Editor: Block Inserter cut off when adding blocks at edges

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#49878]
### Description

When trying to add a block to a column or grid block at the left most edge of the editor, the inserter gets cut off. Found while writing the next call for testing for the FSE Outreach Program. Note, if list view is opened, the problem doesn't occur!

### Step-by-step reproduction instructions

1. Go to Appearance > Editor
2. Go to Template in the Design section and select any template.
3. Add a Columns block or Grid block to the root of the editor.
4. Close out any sidebars and try to use the + button to add a block. 
5. Notice the inserter is cut off.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/232611324-f31ec15d-1292-437b-8675-bf3ff16462b3.mov

### Environment info

- WP 6.2
- GB 15.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Yes, noticed this recently as well. I think it's serious enough for the next upcoming WP minor release, should it go in the 6.2.x board?

**Comment by annezazu** [comment]
Good idea!
