### ISSUE TITLE
Convert to blocks loses marked up content inside a blockquote

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#4992]
## Issue Overview
Having created a post using the Classic editor I attempted to convert it from the Classic block to blocks.
It correctly determined that it should create a blockquote but lost all the content.

This is a backward compatibility issue.

## Steps to Reproduce (for bugs)

1. Using the classic editor create the following content
```
<blockquote>
<h3>The editor will create a new page- and post-building experience that makes writing rich posts effortless, and has “blocks” to make it easy what today might take shortcodes, custom HTML, or “mystery meat” embed discovery.</h3>
<h3>— Matt Mullenweg</h3>
</blockquote>
```
This can be achieved in the Visual editor by pasting the text of the quote, selecting it all and then clicking on the blockquote and h3 toolbar buttons in that order.
2. Save
3. Open in the new editor
3. Choose convert to blocks

## Expected Behavior
- The quote should be extracted correctly. 
- It would also be nice if the cite part of the blockquote was populated into the cite section.

## Current Behavior
The text disappears.

## Screenshots / Video

![issue-4992](https://user-images.githubusercontent.com/2474435/36066321-841c4726-0e9f-11e8-9abc-27ad74401cd1.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
As I said in https://github.com/WordPress/gutenberg/issues/5028#issuecomment-365768265 This is not a backwards compatibility issue because converting to block is an explicit action you can undo and it can't be 100% accurate because the blocks don't support all kind of markup.

So transforming the markup mentioned above is impossible because the quote can't contain headings at the moment, it's just a list of paragraphs. Maybe it shouldn't be converted in that case though. cc @iseulde

**Comment by bobbingwide** [comment]
It’s unexpected loss of data.  
The user should be informed in advance, during or immediately after that there could or have be problems. Undo is OK when it’s an obvious option.  
 
Had I converted a very large block I might have missed the fact that the block quote had gone missing. 

There are a number of potential improvements that can be envisaged. 

For example. 

### Check your results
It should be easy enough to strip the HTML comments from the generated blocks, compare the generated HTML with the original HTML and report the differences.

### Classic Text block
Another is to support a Classic Text block where the content is left completely untouched by the editor. No wpautop processing, no new lines converted to br’s. Nothing. 

This will help with other issues where existing blocks do not satisfy the requirements.  See #4456 and #4672.

In my opinion this is something that is needed to help early adopters demonstrate to others that the site doesn’t break. A nice way of saying ‘You were doing it wrong but now we’ve fixed it for you’.

I’ll raise a separate requirement if you like.. none of the existing blocks support what I need.

**Comment by youknowriad** [comment]
> Another is to support a Classic Text block where the content is left completely untouched by the editor. No wpautop processing, no new lines converted to br’s. Nothing.

That's what we already do if you don't click "convert". Am I misunderstanding something?

**Comment by youknowriad** [comment]
> It should be easy enough to strip the HTML comments from the generated blocks, compare the generated HTML with the original HTML and report the differences.

IMO, there will always be difference. An exemple of this is the autogenerated className per block. I think a solution could be to add a confirmation to this button explaining that loss of data is possible and improve the algorithm to minise it (like I suggested above, don't convert if the blockquote contains tags other than paragraphs)

**Comment by bobbingwide** [comment]
> That's what we already do if you don't click "convert".

The Classic block looks and works a bit like the Tiny MCE editor, but there is no Text editor equivalent.

> Am I misunderstanding something? 
- My experience is that hand crafted content may not survive Save and Re-open. 
- And this can lead to existing content being broken on the front end. 
- Garbage in, garbage out.
- When this happens the changes have to be reverted and the Classic editor used.
- See the issues I referred to.
- I will raise a new requirement. 
- In the mean time, please consider this scenario, I don't know if this has been raised already.

I've modified the original HTML in the Text Editor and it looks fine in the Visual Editor. 
I've removed the h3's and used a cite tag.
```
<blockquote>The editor will create a new page- and post-building experience that makes writing rich posts effortless, and has “blocks” to make it easy what today might take shortcodes, custom HTML, or “mystery meat” embed discovery.
<cite>Matt Mullenweg</cite></blockquote>
```
Copying and pasting this into a new post fails to recognise the cite.

![image](https://user-images.githubusercontent.com/2474435/36251926-d839175a-123a-11e8-9fa5-352f39b5e9de.png)

It's pretty impressive but just needs to be even slicker.

**Comment by youknowriad** [comment]
> The Classic block looks and works a bit like the Tiny MCE editor, but there is no Text editor equivalent.

Isn't the HTML mode per block the equivalent for the text editor for the classic block? I'm just trying to understand here.

---
What exactly are you proposing here?

**Comment by mtias** [comment]
This would be addressed by making Quote have a nested area where you can add different blocks.

**Comment by iseulde** [comment]
Yeah

**Comment by SuperGeniusZeb** [comment]
Keeping headings, lists, etc. will be possible if #6054 is merged.

**Comment by danielbachhuber** [comment]
Now that #6054 has landed, we should make sure this use-case is accommodated for.

**Comment by SuperGeniusZeb** [comment]
@danielbachhuber #6054 was reverted in #6501. There is a new PR for nested blocks in quotes: #6520.

**Comment by nosolosw** [comment]
Just wanted to note that after some changes related to the Raw Handler component this test case no longer loses content but it is transformed into an HTML block.

**Comment by ellatrix** [comment]
Let's close this in favour of #15486. The problem here is that a quote should allow other blocks inside it.
