### ISSUE TITLE
Gutenberg 15.6.0 - Fixed Cover Block contents overlap sticky group blocks due to higher z-index

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#49939]
### Description

As of Gutenberg 15.6.0, contents inside of Fixed cover blocks are overlapping Group blocks set to `sticky` position.

First reported here https://github.com/Automattic/wp-calypso/issues/75986 . The author noted:

> Cover block contents (the .wp-block-cover__inner-container element) have a z-index of 32, which is much higher than Group blocks assigned the "Sticky" position (which have a z-index of only 10). The contents of cover blocks can appear on top of sticky elements as a result.

### Step-by-step reproduction instructions

1. Start with a site with a Site Editing theme active.
2. In the Site Editor, create a Group block with the "Sticky" position. (It may be helpful to set a background color on the Group, or add some larger content to it, so it's easier to see where its contents lie.)
3. Somewhere below the sticky Group, add a Cover block with some form of content.
4. View the site, and scroll.

Cover block content should scroll "beneath" the sticky Group (i.e. the sticky Group should appear on top of all content as you scroll). Instead, the contents of the Cover block have a higher z-index, so they appear on top of the sticky Group:

### Screenshots, screen recording, code snippet

Recording of the issue:

https://user-images.githubusercontent.com/27249804/233216254-cc6ccc10-24b9-4683-9bb4-3e9e48a22c07.mp4

Recording of the same site using Gutenberg 15.5.1 instead:

https://user-images.githubusercontent.com/27249804/233216378-1d51f4f5-410c-4627-920f-ed4e8ec1a0f2.mp4

### Environment info

- WP 6.2
- Gutenberg 15.6.0
- No other plugins active
- Firefox 112.0.1
- Theme: Twenty Twenty-Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aaronrobertshaw** [comment]
Thank you for reporting this issue @cuemarie 👍 

We have a fix up in https://github.com/WordPress/gutenberg/pull/49943.

**Comment by andrewserong** [comment]
A Gutenberg point release has been published ([15.6.1](https://github.com/WordPress/gutenberg/releases/tag/v15.6.1)) to roll out the fix.
