### ISSUE TITLE
Insertion block - Recent blocks tab only shows 8 blocks

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#4995]
## Issue Overview
The recent blocks tab on the block insertion dialog only shows 8 blocks though there's room for 9.
Apparently it used to display 2 by 4 = 8 but now it's 3 x 3.

@karmatosed suggested I raise this issue.

## Steps to Reproduce (for bugs)

1. Use 9 different block types
2. Choose to insert another

## Expected Behavior
Recent blocks shows 3 x 3 

## Current Behavior
Only 8 shown.

## Possible Solution
- Support 9 blocks

## Screenshots / Video

![image](https://user-images.githubusercontent.com/2474435/36066545-4c011c00-0ea3-11e8-9a34-03613b0dd58a.png)

I've also noted that the insertion block is not sizeable, so the vertical space allowed is only good for blocks with short titles. That might be a problem for some languages.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by travislopes** [comment]
Created a PR for this earlier today. #4988

**Comment by bobbingwide** [comment]
Yes, I just noticed. I didn't think about checking after discussing it earlier today.
