### ISSUE TITLE
I can not create a new block with OS Sierra and Firefox 51.0.1

### ISSUE THREAD

**Issue by colomet** [WordPress/gutenberg#50]
I can edit the words of the current block but I can not create a new one, no matter the type of block. Also I can not apply styles to the current blocks

**Comment by jasmussen** [comment]
This is probably the result of the UI prototype being very very limited and having mostly dummy controls at this point. I'm opening a ticket to see where we take this UI prototype!

**Comment by jasmussen** [comment]
Created a ticket for discussing the limitations of the current UI prototype: #51
