### ISSUE TITLE
@wordpress/eslint-plugin package does not support node.js 20

### ISSUE THREAD

**Issue by Toberumono** [WordPress/gutenberg#50001]
### Description

This is an iteration of #45696, but for Node 20 this time.

### Step-by-step reproduction instructions

1. Set up an environment that uses Node 20 or higher
2. Attempt to use any package manager to set up a project that depends either directly or indirectly on @wordpress/eslint-plugin
    - @wordpress/scripts is a good one
3. Observe the error about an incompatible Node version

### Environment info

- Node 20
- @wordpress/scripts in the project dependencies
- Nothing else matters

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Toberumono** [comment]
Is there an ETA on a fix for this? Upgrading to eslint-plugin-jsdoc version 43.1.1 or higher will permanently fix this category of issue because they switched from an explicit enumeration of versions to ">= 14".

**Comment by gziolo** [comment]
I opened #53629 which tries to fix the issue.
