### ISSUE TITLE
Deleting a Paragraph Block that comes immediately after Columns creates an additional column, resizes stuff, and generally just causes a mess

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#50003]
### Description

If you have a blank paragraph that comes immediately after a columns block, and hit backspace in that empty paragraph, the result is kind of a disaster.

What I'd expect: The Paragraph Block goes away

What actually happens: an additional column is added to the preceding Columns block, and the existing columns become incredibly narrow

Note that using List View to remove the Paragraph Block works fine. It's only trying to get rid of it with the backspace key that causes the issue. But as a blank paragraph doesn't have a toolbar available, trying to remove it with a backspace is pretty common.

### Step-by-step reproduction instructions

1. Create a Columns block with 2 columns. Put some basic text in each, such as "column 1" and "column 2"
2. Add a blank paragraph block after the columns
3. Put your cursor in the empty paragraph block
4. Hit backspace

### Screenshots, screen recording, code snippet

Before hitting backspace: 
![before](https://user-images.githubusercontent.com/945157/233732337-2c1b4061-79b2-47d0-a9e2-ef7ea5f65cc0.png)

After hitting backspace:
![after](https://user-images.githubusercontent.com/945157/233732361-2c9d57c0-635b-4b27-bc13-b0977ff61682.png)

### Environment info

WordPress 6.2, no Gutenberg plugin
(Also happens on 6.1.1, and I'm pretty sure it's been happening a long time)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
I could replicate this on my test site with the block and classic theme.

**Comment by t-hamano** [comment]
@MadtownLems 

Thanks for the report.

I believe this issue is the same problem reported in #45436. Let's close this issue and focus on #45436.

@annezazu
I have added #45436 to the UX & Polish project.
