### ISSUE TITLE
Need More Formatting Options in Column Block

### ISSUE THREAD

**Issue by mrjarbenne** [WordPress/gutenberg#5000]
When adding text into the column block, users should be able to add additional text features like Headings, Bulleted or numbered lists, and alignment features. In the paragraph block users get the full feature-set toolbar, 

![2018-02-11_14-26-40](https://user-images.githubusercontent.com/480667/36077350-b6634c28-0f37-11e8-9375-b8eb5c6c885e.png)

but under columns, the options are much more limited:

![2018-02-11_14-27-12](https://user-images.githubusercontent.com/480667/36077353-be7c8000-0f37-11e8-95fe-b02f5f32f343.png)

If you attempt to edit the HTML directly, in order to change the p tag to an h3 (for example), the editor encounters an error.

![2018-02-11_14-29-40](https://user-images.githubusercontent.com/480667/36077385-2fa927ce-0f38-11e8-8ad5-04974da656b1.png)

**Comment by GlennMartin1** [comment]
The present columns feature is being removed in the next version.

Instead, there will be a far more functional "nesting" structure, which will make it possible to add blocks to columns.

Just wait till the next release - big change in this area!

https://github.com/WordPress/gutenberg/pull/3745

**Comment by youknowriad** [comment]
Closing this one as nested is merged now. Let's iterate on it to improve the UX as much as we can.
