### ISSUE TITLE
List view: Focusing a block causes keyboard misbehaviours

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#50019]
### Description

After focusing a block in the list view (by clicking two times), it's not possible to remove the block then via the keyboard.
Defocusing by clicking below the blocks in the list view won't work. You must deselect the block completely by clicking somewhere out of the list view or selecting a different block.

### Step-by-step reproduction instructions

1. Focus a block (with to clicks)
2. Try to remove the block with the keyboard
3. Try to defocus by clicking within the list view
4. Try to remove the block with the keyboard
5. Defocus and deselect by clicking out of the list view area. Select the block again - now you're able to remove the block with the keyboard.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/17861443/233861136-a79d0087-c6d3-41ba-80c4-153ce0c88319.mp4

### Environment info

- Wordpress 6.2
- Gutenberg 15.6.2
- Brave Browser (Chromium)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hanneslsm** [comment]
Probably related: https://github.com/WordPress/gutenberg/issues/49563

**Comment by Thelmachido** [comment]
Hi @hanneslsm yes I can replicate this and it does seem to fall under the tweaks for KeyBoard shortcuts.

**Comment by andrewserong** [comment]
As of https://github.com/WordPress/gutenberg/pull/50422 it's now possible to delete blocks in the list view via keyboard, so I'll close this out now.
