### ISSUE TITLE
Video Block: Dimension Settings missing

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#50018]
### Description

It's not possible to change the width or height of a video. You'd expect it to be the same as for an image. Either with draggable handles or in the settings right.

I'd consider this as a bug since this is such a basic feature, especially when it's known from the image block.
I stopped counting on how often clients have asked me how to change the width of a video.

### Step-by-step reproduction instructions

1. Insert a video 
2. Try to change the width (or height). You can't as easily as you'd expect.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/17861443/233860499-d5aafe7f-78b0-461c-bcaa-be992ee4cea9.mp4

### Environment info

- Wordpress 6.2
- Brave Browser

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/20944 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

**Comment by hanneslsm** [comment]
@skorasaurus Thanks. The linked issue is from 2020. Is there a way to prioritise the kind of basic features? I think this would improve the user experience drastically.
