### ISSUE TITLE
Block Manager: Add 'Enable all' button to the 'N blocks are hidden' message

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#50015]
At some point in your career, you may end up with a lot of hidden blocks:

<img width="533" alt="image" src="https://user-images.githubusercontent.com/36432/233841468-509fa0f0-0467-481d-9f7c-fe9639f7f5d1.png">

It would be nice to have an 'Enable all' button, instead of having to manually click each checkbox.

**Comment by hanneslsm** [comment]
You can easily enable all in one category at once. So it's max 6 clicks in total ( = 6 categories)
Or am I missing something here?

https://user-images.githubusercontent.com/17861443/233866303-81e079ab-43b7-4105-bd61-6f4b1b13c05d.mov

**Comment by danielbachhuber** [comment]
> You can easily enable all in one category at once. So it's max 6 clicks in total ( = 6 categories)

Ah, I didn't even think about that. I don't think that's particularly obvious to the end user (e.g. how are they supposed to know there are only six categories?, etc.)

**Comment by kozer** [comment]
@danielbachhuber , please assign it to me! Thanks!

**Comment by kozer** [comment]
This is merged. We need to close this.

**Comment by danielbachhuber** [comment]
🚢
