### ISSUE TITLE
Page Editor / Site Editor: Different order for Blocks & Patterns inserter

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#50023]
### Description

In the page editor, when clicking the Plus on the top left all blocks are displayed by default.
In the site editor, when clicking the Plus on the top left patterns are displayed by default.

This is very confusing.

### Step-by-step reproduction instructions

1. Try to add a block in the page editor. 
2. Try to add a block in the site editor afterwards and be confused why the patterns are displayed by default instead.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/17861443/233864720-45aa4078-2e3e-4485-9e47-d807e4818931.mp4

### Environment info

- Wordpress 6.2
- Gutenberg 15.6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
Hi @hanneslsm could be that the assumption is that you are most likely to use patterns on templates than individual blocks.

<img width="766" alt="Screenshot 2023-04-25 at 13 57 49" src="https://user-images.githubusercontent.com/41231764/234275758-ae6ba398-cc57-4ba4-b8d0-f83989e8439c.png">

**Comment by hanneslsm** [comment]
As a designer, creating my own block themes, I'm actually using blocks in the Site Editor to create patterns and save them in the theme, so that my clients can use in the Page editor then. 
So, if this logic applies, at least for my use case, it should be actually the other way around. (which as a change I would't welcome very much either)

**Comment by youknowriad** [comment]
This has been unified
