### ISSUE TITLE
Visual indication missing when transforming a block

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#50022]
### Description

There is not really a visual indication (notification / Snack Bar) when transforming a block.
Especially when transforming a image block to a gallery, a notification would improve the UX dramatically.

### Step-by-step reproduction instructions

1. Transform a block
2. Wonder what happed. A notification does not appear.

### Screenshots, screen recording, code snippet

As you can see, it's difficult to see what's going on here. (Transforming an image block to a gallery, undo, doing it again, undo…)

https://user-images.githubusercontent.com/17861443/233864198-d8f1df26-c950-41cc-8509-817ee26a56b1.mp4

### Environment info

- Wordpress 16.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
I don't think it's necessary in _most_ cases to fire a snackbar between transforms—as you do get visual confirmation typically—but one image to gallery transform is a bit odd.

**Comment by hanneslsm** [comment]
> but one image to gallery transform is a bit odd.

It’s odd that the snack bar isn’t fired you mean?
The fact that a visual representation is missing is probably also because of https://github.com/WordPress/gutenberg/issues/50021
The snack bar would be a quick fix here, but I’d vote for implementing it nonetheless until a solution for the other issue would make it irrelevant.

**Comment by richtabor** [comment]
> The fact that a visual representation is missing is probably also because of https://github.com/WordPress/gutenberg/issues/50021

I don't think they're related.

I'm not positive that this transform instance—from image to gallery—justifies adding snackbars for every transform (when nearly every other transform is visually represented), but I'm interested in what others (@WordPress/gutenberg-design) think. And I do certainly appreciate the sentiment + bringing up the issue.

**Comment by jameskoster** [comment]
Is there any reason why transforming an Image to a Gallery deselects the original image? With other transforms the block seems to remain selected. If we did that here there would be some visual indication as the toolbar would change.

**Comment by hanneslsm** [comment]
> Is there any reason why transforming an Image to a Gallery deselects the original image? With other transforms the block seems to remain selected. If we did that here there would be some visual indication as the toolbar would change.

It feels like this is really the root of the issue here. Keeping the image block selected would already help a lot!

**Comment by richtabor** [comment]
> Is there any reason why transforming an Image to a Gallery deselects the original image? With other transforms the block seems to remain selected. 

Yea, that seems to be the root issue here. @hanneslsm do you mind opening a separate issue with a screen recording of the transform between Image and Gallery, then another showing the transform selection working properly for Image -> Cover?

**Comment by hanneslsm** [comment]
> @hanneslsm do you mind opening a separate issue with a screen recording of the transform between Image and Gallery, then another showing the transform selection working properly for Image -> Cover?


Sure! https://github.com/WordPress/gutenberg/issues/50308

**Comment by hanneslsm** [comment]
Fixed via https://github.com/WordPress/gutenberg/pull/50363
