### ISSUE TITLE
Image Block: "Add Text over image" should be removed

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#50025]
### Description

The "Add Text over image" function in the toolbar of the image block should be removed. It does not add text over the image, it transform the image block to a cover block. This is a different behaviour and logic that does not fit to the other functions at that place.

All the other functions in the toolbar can be selected and deselected. 
The "Add Text over image" not so. 
This is confusing. Especially because there is also no image block in the cover block. Clients ask me: "Where did my image block go?" because they do not understand that they have transformed it into a cover block and the cover block contains the image (but confusingly not a image block but a paragraph block)

### Step-by-step reproduction instructions

1. Select a image block
2. Select "add Text over image" in the Tool bar
3. Be confused where your image block is

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/17861443/233865711-b430b88c-c715-4120-9774-f7cc042e1d36.mp4

### Environment info

- Wordpress 6.2
- Gutenberg 15.6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
I see what you mean, instead of removing the option it might be better to describe its function a little bit better.

**Comment by hanneslsm** [comment]
> I see what you mean, instead of removing the option it might be better to describe its function a little bit better.

I was thinking about this as well. But the best description I could think of was "Transform to cover block". And then, there is a place for that. 

I see where the idea implementing this feature is coming from and I know it's well-intentioned but at the end it only confuses people. So my take is: Let's remove this feature to easily and quickly improve the UX of Gutenberg.

**Comment by t-hamano** [comment]
I have been trying to find out in what context this feature was added and #28414 seems to be its PR.

**Comment by Mamaduka** [comment]
@hanneslsm, do you mind closing this and continuing the discussion in #56385? I think these two are somewhat the same.

**Comment by hanneslsm** [comment]
> @hanneslsm, do you mind closing this and continuing the discussion in https://github.com/WordPress/gutenberg/issues/56385? I think these two are somewhat the same.

Sure!
