### ISSUE TITLE
Page Editor / Site Editor: Preferences should be universal

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#50024]
### Description

Some preferences should be overarching for the page and the site editor.
For example "Always open list view". There is no reason why I want a different behaviour in the page editor and the site editor.

### Step-by-step reproduction instructions

1. Change the preferences in the page editor
2. Go to the site editor and be confused why you must change the preferences again.

### Environment info

- Wordpress 6.2
- Gutenberg 15.6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
I see what you mean, it might be useful to unify both editors.

**Comment by richtabor** [comment]
Agreed.

**Comment by youknowriad** [comment]
This has been achieved.
