### ISSUE TITLE
Site Editor: unable to break out of Post Title block

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#50035]
### Description

When editing an individual page from the navigation section of the Site Editor, the post title block is very difficult to break out of, resulting in endless lines of edits.

### Step-by-step reproduction instructions

1. Go to Appearance > Editor and ensure you already have a menu set with the navigation block.
2. Head to Navigation in the dark grey sidebar. 
3. Select a page and edit it.
4. Select the Post title block and make changes. 
5. Notice if you hit return it doesn't break you out of the block and instead you can hit return as much as you want adding more text.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/234009999-c6ba51dc-9adb-4b3b-a608-416886e49a54.mov

### Environment info

- WP 6.2
- GB 15.6.2
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
The behavior is the same in the post editor.

**Comment by carolinan** [comment]
Its weird that you can add line breaks to the post title, but not to heading blocks: And not when editing the actual post title in the block editor (the title at the top, that is not a "real block").
