### ISSUE TITLE
[Fonts API] When not in Site Editor, only enqueued fonts should be added to global styles in gutenberg_add_registered_fonts_to_theme_json()

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#50047]
Part of the Fonts API Roadmap #41479.

## Problem Statement

Currently, all registered fonts are included in the global styles theme.json when invoking `gutenberg_add_registered_fonts_to_theme_json()`.

Outside of the Site Editor, only the _enqueued_ fonts should be included. 

## More Details

When invoking `WP_Theme_JSON_Resolver_Gutenberg::get_merged_data()` or `WP_Theme_JSON_Resolver_Gutenberg::get_theme_data()`, all _registered_ fonts are included via `gutenberg_add_registered_fonts_to_theme_json()`.  This is fine for the Site Editor which uses all registered fonts for user selection and previewing. When not in the Site Editor, only the enqueued fonts should be included in the global styles.

Why?

Enqueued fonts are the global fonts. These include:

* Theme's fonts.
* The theme's selected style variation fonts, if applicable.
* User-selected fonts from other sources such as plugins or a selected style variation (ie selected from the Styles > Typography UI in the Site Editor).

The Site Editor's Styles > Typography UI is the tool to present all of the registered fonts. And those selections are the global fonts for use on the front-end and in the rest of the admin area.

Contextual switching is needed in `gutenberg_add_registered_fonts_to_theme_json()` to know if it should use registered or enqueued fonts.

### Step-by-step reproduction instructions

Steps are coming...

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by anton-vlasenko** [comment]
This issue should be fixed when https://github.com/WordPress/gutenberg/pull/50981 is merged.

**Comment by hellofromtonya** [comment]
Update:

This issue is no longer valid for the Fonts API once the Font Library is merged.

Why?

As shared in Ongoing Roadmap update https://github.com/WordPress/gutenberg/issues/41479#issuecomment-1597915077, the Fonts API will no longer inject / add fonts into theme.json. Rather, it will become read-only of the theme.json merged data.

The `WP_Fonts_Resolver::add_missing_fonts_to_theme_json()` will be removed (see #51716).
