### ISSUE TITLE
insertBlocks doesn't seem to work as expected?

### ISSUE THREAD

**Issue by oobi** [WordPress/gutenberg#50051]
### Description

I'll preface this by saying this is probably a "me" problem, but I cannot for the life of me make this work. 

I have a block (categories) which has a child block (category). I've created a placeholder which displays when the parent block is empty. It contains a button to add the first child.

The insertBlocks method is called, the clientId is valid (confirmed by console.log), it throws no errors but it just doesn't do anything. 

I swapped it out for a call to replaceInnerBlocks which dumps the placeholder and inserts the child block just fine. The child block is registered correctly and works fine.

From a trawl through posted comments here, there seem to be numerous ways to make this work, but so far none have yielded a result. 

Is the insertBlocks method problematic or is there a correct way to use it to insert a child block?

### Step-by-step reproduction instructions

This works:

```
<Button variant="primary" onClick={replaceWithCategory}>
Add category
</Button>
```

This does not (why??)
```
<Button variant="primary" onClick={addCategory}>
Add category
</Button>
```

### Screenshots, screen recording, code snippet

```
        import {store as blockEditorStore } from "@wordpress/block-editor";
```

...

```
	// block insert/replace methods
	const { replaceInnerBlocks, insertBlocks } = dispatch(blockEditorStore);

	// create a new category block
	const addCategory = () => {
		insertBlocks(
			createBlock( CHILD_BLOCK_NAME, {} ),   // I have tried this with and without array notation [createBlock(...)]
			undefined,
			clientId
		);
	};

	// replace inner blocks with a category block
	const replaceWithCategory = () => {
		replaceInnerBlocks(clientId, [createBlock(CHILD_BLOCK_NAME)]);
	};
```

### Environment info

WordPress 6.2 with TwentyTwentyThree
PHP 8.0 / MacOS / Apache

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@oobi The main distinction between `insertBlocks` and `replaceInnerBlocks` seems to be that `insertBlocks` checks whether the block to be inserted is an allowed one and can fail silently if it isn't. `replaceInnerBlocks` doesn't seem to do any kind of check.

It is a little bit inconsistent, I'm not sure why it's that way, possibly either an oversight or `replaceInnerBlocks` is considered lower level.

It might be worth checking your block satisfies all the necessary conditions (`allowedBlocks`, `parent`, `ancestor`, `templateLock` properties are good to check). You should be able to use the `canInsertBlockType` selector to double-check whether the block is allowed.

**Comment by talldan** [comment]
I've proposed making a small improvement to the documentation in #50078 to mention the above.

**Comment by oobi** [comment]
The child block inserts fine if I remove the <placeholder> block. 

I ended up with this as a workaround:

```
	// create a new category block
	const addOrReplaceCategory = () => {
		const childBlockCount = childBlocks ? childBlocks.length : 0;
		const lastChildBlock = childBlocks
			? childBlocks[childBlockCount - 1]
			: null;

		// Create a new block with the attributes of the last child block
		const newBlock = createBlock(
			CHILD_BLOCK_NAME,
			lastChildBlock ? { ...lastChildBlock.attributes } : {}
		);

		if (childBlockCount === 0) {
			replaceInnerBlocks(clientId, [newBlock]);
		} else {
			insertBlocks(newBlock, 0, clientId);
		}
	};
```

This is the placeholder that seems to block the "createBlock" method from working directly. If I remove this then the createBlock method works fine. As it stands the method above (createOrReplace) does work for my use case.

```
	<div {...blockProps}>
		{childBlocks && childBlocks.length === 0 ? (
			<>
				<Placeholder
					icon=<Icon width="2rem" height="2rem" />
					label="Article Categories"
					instructions="Add at least one category"
				>
					<Button variant="primary" onClick={addOrReplaceCategory}>
						Add category
					</Button>
				</Placeholder>
			</>
		) : (
			<InnerBlocks allowedBlocks={allowedBlocks} />
		)}
	</div>
```

**Comment by talldan** [comment]
The problem might be that `InnerBlocks` is conditionally rendered. At the moment that's the only way to set the `allowedBlocks`, and also the only way that the block editor can know that your block accepts inner blocks.

That might be where `insertBlocks` fails.

**Comment by noisysocks** [comment]
Closing this help request as it looks like it's been answered.
