### ISSUE TITLE
Block categories are not unique

### ISSUE THREAD

**Issue by Chrico** [WordPress/gutenberg#50061]
### Description

The Block categories can be set on server-side (PHP) via filter and client-side (TS/JS).

But those values set (and lateron accessed via `wp.blocks.setCategories()`) are not unique. You can add multiple times the same category with same slug and even set the "core" categories multiple times.

Shouldn't they be unqiue by slug? Otherwhise when rendering the "Block inserter" the same Categories and Blocks are rendered multiple times.

#### Setting "custom" categories multiple times:

**server-side:**
```php
add_filter( 'block_categories_all', static function( array $categories = [] ): array {

    $categories[] = [
        'slug' => 'my-slug',
        'title' => __('my title')
    ];

    $categories[] = [
        'slug' => 'my-slug',
        'title' => __('my title')
    ];

    return $categories;

}, 10, 2)
```

**client-side:**

```ts
const cateogries = wp.blocks.getCategories();

wp.blocks.setCategories( [
    ... cateogries, 
    ... [ {'slug':'my-slug', 'title': 'My title'}, {'slug':'my-slug', 'title': 'My title'} ] 
);
```

-----

#### v2) Setting "core" category again with different (or same) name:

![image](https://user-images.githubusercontent.com/3417446/234282818-974d2400-cbc5-489d-a7d0-017b4939b85a.png)

This will result in rendering in "Block inserter" the "Text"-category with Blocks and the "Meeeeh"-category with the same Blocks again (slug is matching):

![image](https://user-images.githubusercontent.com/3417446/234283060-7972cc3b-821d-41f4-b5fc-8acb49f54e7a.png)

### Environment info

- WordPress: 6.2
- Gutenberg: 15.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Chrico** [comment]
any progress or direction where to go @talldan ?

**Comment by talldan** [comment]
@Chrico To me it seems fairly low priority. It's most likely to affect plugins, but the general wisdom in WordPress is that plugins should try to use unique names for things to avoid naming collisions by prepending the plugin name. Are there any other consequences I might be overlooking?

In terms of a fix, I would suggest the duplicate category should fail to register.

As an open source project, contributions to fixing this are welcome.

**Comment by Chrico** [comment]
I've created a PR for this topic @talldan . Even wit low priority, it should be a quick win, right? :)

**Comment by talldan** [comment]
> I've created a PR for this topic @talldan . Even wit low priority, it should be a quick win, right? :)

Yep, if you're willing to work on a PR I'd be happy to review and merge it. The PR looks good at a quick glance. I left a comment about adding a unit test. Let me know if you're happy to do that, and once it's in place I'll give it a final check over.
