### ISSUE TITLE
Navigation block: Current menu item and ancestor class inconsistent application

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#50069]
### Description

In Navigation block the `current-menu-item` class is being applied on the menu `li` tag. However, the `current-menu-ancestor` class is being applied on `li > a` tag.

Please fix the application of `current-menu-ancestor` class and apply it onto the parent `li` tag, not the anchor tag.

### Step-by-step reproduction instructions

Set a Navigation menu block with submenus and visit a page from the submenu. Inspect the classes applied on the Navigation block list items.

### Environment info

WordPress 6.2, Gutenberg 15.6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I've confirmed this behaviour in testing.

<img width="918" alt="Screenshot 2023-07-20 at 11 37 37 am" src="https://github.com/WordPress/gutenberg/assets/1842363/bd0da5da-4013-4927-9e24-8d3e0aa29dee">
