### ISSUE TITLE
Unable to focus quote citation field on iOS

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#5008]
## Issue Overview
Both appears on an actual device and simulation. When I touch the citation field, the screen just scrolls a bit, but I can never focus the field to edit it.

## Steps to Reproduce (for bugs)
1. Open Safari on iOS
2. Open the demo content
3. Touch a quote's citation field

**Comment by jorgefilipecosta** [comment]
Hi @iseulde, I think this problem may have been fixed with the merge of https://github.com/WordPress/gutenberg/pull/5100. Could you confirm if that is the case?
