### ISSUE TITLE
Keyboard remains visible after interacting with `Type a URL` dialog on media blocks (only Android)

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#50105]
## Description

On media blocks like the Image block or Audio block, we present the option to insert media from a URL. On Android, a prompt dialog with the title `Type a URL` is shown for this, which automatically shows the keyboard. However, after dismissing the dialog either by canceling or applying, this results in the keyboard staying open. This is unexpected as there's no text input focused, hence the keyboard should not be visible.

## Step-by-step reproduction instructions

1. Open the editor on the Android app.
2. Add an Image block.
3. Tap on "Insert from URL" option.
4. Observe that the keyboard is shown.
5. Tap on "CANCEL" or "APPLY" button.
6. Observe that the keyboard remains open.

## Expected behaviour

The keyboard shouldn't be visible after dismissing the prompt dialog.

## Actual behaviour

The keyboard remains visible after dismissing the prompt dialog.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/234608591-9ecf6344-707d-4df8-8b50-5bde6962c836.mp4

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: Samsung Galaxy S20 FE 5G
- Operating system: Android 13
- WordPress app version: `22.2-rc-3`

**Comment by dcalhoun** [comment]
From testing just now, this appears to no longer be relevant after merging #54096.
