### ISSUE TITLE
URL dialog: The cancel/apply/settings dialog appears even if you search inside a page link and don't find a page.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#50162]
Related to #49091. The trio of buttons for Settings, Cancel and Apply were recently added to the URL dialog. They make less sense when you search:

<img width="490" alt="Screenshot 2023-04-28 at 12 08 14" src="https://user-images.githubusercontent.com/1204802/235120311-443d34ef-80e0-4dd6-ab42-ee7383310982.png">

Extracting from https://github.com/WordPress/gutenberg/issues/49091#issuecomment-1475601642:

> If a link has already been created and submitted, what is the state when you click on that link again?

It should open this state where you can edit or remove the link, Clicking edit takes you back to the original state, pressing `esc` or input blur should show token again. "Add" action would change to "Save" (or adjust) if you're editing rather than adding.

![image](https://user-images.githubusercontent.com/1072756/226243014-65dfd4bf-2dfe-4574-81a4-fc1ff066abea.png)

Here's the full flow shown:

https://user-images.githubusercontent.com/1072756/225801677-8671c7ff-fae5-48ab-9da6-410acb0ed26d.mp4

See the full flows in [this comment](https://github.com/WordPress/gutenberg/issues/49091#issuecomment-1473053480).

**Comment by scruffian** [comment]
With the changes to link control I think we can close this now.
