### ISSUE TITLE
Cannot embed a Vimeo video including a timestamp

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#5017]
Steps to reproduce:

1. Create a new post.
1. Embed this Vimeo URL in a regular block: https://vimeo.com/73214621#t=3m13s
1. Embed this Vimeo URL in a video block: https://vimeo.com/73214621#t=3m13s
1. Embed this Vimeo URL in a video block: https://vimeo.com/73214621
1. Publish and view the post.

<strong>Result:</strong> Vimeo embeds does not work if a timestamp is included in the URL. Vimeo embeds do not work at all when added via URL in a video block.

<strong>Video:</strong> [1m29s](https://cloudup.com/cE1pP-Mugnd)

![screen shot 2018-02-12 at mon feb 12 6 27 22 pm](https://user-images.githubusercontent.com/1119271/36129072-9b0ebd40-1022-11e8-9c91-58748c5a73eb.png)
<sup>Tested with WordPress 4.9.3 and Gutenberg 2.1.0 on Bluehost using Safari 11.0.3 on macOS 10.13.3.</sup>

/hat tip @sekanderb for originally reporting this issue for the Calypso Editor.

**Comment by iseulde** [comment]
* Looks like @mcsf Is working on making it work in the video block: #4990.
* I can't reproduce it not showing on the front end. The video appears, though the timestamp does nothing. I seems like Vimeo does not support the timestamp through the oEmbed API: https://developer.vimeo.com/apis/oembed.

**Comment by iseulde** [comment]
Timestamp is there, embeds fine, but timestamp does nothing.

<img width="448" alt="screen shot 2018-02-13 at 12 13 41" src="https://user-images.githubusercontent.com/4710635/36147147-6455925c-10b7-11e8-88d3-ac49be2eca45.png">

**Comment by joaodfmota** [comment]
Vimeo [support](https://help.vimeo.com/hc/en-us/articles/360000121668-Starting-playback-at-a-specific-timecode) timestamp through embed.

But I believe this is an issue for WordPress oEmbed API.

The editor uses this `http://wordpress.local/wp-json/oembed/1.0/proxy` that returns an object without the `#t=3m13s` which define when the time starts. Look on `doServerSideRender` function at `blocks\library\embed\index.js` line 98

**Comment by mcsf** [comment]
Thanks, @joaodfmota. Yes, I believe the oEmbed issue should be handled in [core WordPress](https://core.trac.wordpress.org/). /cc @tellyworth

For the issue of the Video block not handling embeds, refer to #4990.

**Comment by rickcurran** [comment]
Hi, is this an issue that should be resolved now in the Gutenberg editor in latest WordPress 5.5.1? I still see the same behaviour where the timestamp is ignored in the embedded video.
