### ISSUE TITLE
LinkControl: Only suggest either "Add new page" or "Add link"

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#50178]
Part of https://github.com/WordPress/gutenberg/issues/50891

When typing a URL (e.g. `www.wordpress.org`) the option to add a draft should not display (and vise-versa). There should only be one or the either available as an action. 

### Visual

This mockup takes the full [LinkControl refresh](https://github.com/WordPress/gutenberg/issues/50891) into account:

<img width="883" alt="CleanShot 2023-05-23 at 15 16 55" src="https://github.com/WordPress/gutenberg/assets/1813435/968ed011-a736-49f0-9213-5aae84414654">

And here's what we have today: 

<img width="406" alt="Screenshot 2023-04-28 at 15 48 31" src="https://user-images.githubusercontent.com/444434/235165579-b2d4b569-6396-46ec-a875-6b140d05f055.png">

Related to https://github.com/WordPress/gutenberg/issues/38497

**Comment by richtabor** [comment]
Just noting that we should still have this logic in place, even with the updates to moving where the draft action occurs (https://github.com/WordPress/gutenberg/issues/49873#issuecomment-1527312593).

**Comment by richtabor** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/51011 and https://github.com/WordPress/gutenberg/issues/50178
