### ISSUE TITLE
Browse mode: Add snackbar notices

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#50175]
## What problem does this address?
We have removed snackbar notices from the Site Editor when in browse mode [here](https://github.com/WordPress/gutenberg/blob/65adadb97f044365a0f6137cb3b2524e92a9c4c7/packages/edit-site/src/components/editor/index.js#L174). We need these notices to allow us to show a notice when switching to a theme (see https://github.com/WordPress/gutenberg/pull/50030).

## What is your proposed solution?
The problem is that these notices are too hard to see because they are low contrast. We should move them to the center of the browser window like this:

<img width="1512" alt="Screenshot 2023-04-28 at 15 21 46" src="https://user-images.githubusercontent.com/275961/235158883-98eeb9c2-1899-4d6d-a499-6a932b90a081.png">

This was suggested by @richtabor

**Comment by jasmussen** [comment]
I think there's an opportunity to include snackbar notices in the theming conversations, potentially applying just a lighter gray to them. But it sems fine to move them to the center as well.

**Comment by richtabor** [comment]
I thought we discussed somewhere to try centering them anyhow, to reduce the visual conflicts. cc @jameskoster

**Comment by jameskoster** [comment]
Without an in-depth exploration, I'd +1 using a lighter gray as a short-term remedy. 

But in general it may be worth giving the Snackbar component a design audit given the introduction of the site view. Some top-of-mind questions:

* Should appearance be consistent across light/dark themes, or not? What are the principles there?
* How is the dismiss affordance working alongside other actions? Should there be a dedicated close button/icon? There's something about the entirely element receiving focus then disappearing that feels a bit strange.
* Is the current timeout still appropriate?
* Elevation – what is the relationship with the Frame?
* Position – bottom center vs bottom left. 
* Animation – Fadeout on dismissal is a bit slow.
* Should we provide affordances for error snackbars (red background, decorative icon)?

**Comment by scruffian** [comment]
I did a quick fix here: https://github.com/WordPress/gutenberg/pull/50794

**Comment by scruffian** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/50794

**Comment by okmttdhr** [comment]
The initial PR https://github.com/WordPress/gutenberg/pull/50794 was reverted by https://github.com/WordPress/gutenberg/pull/50937, but the problem was solved in https://github.com/WordPress/gutenberg/pull/51054 again (c.f. https://github.com/WordPress/gutenberg/pull/51054#issuecomment-1568124960 and https://github.com/WordPress/gutenberg/pull/51054#discussion_r1210093857).

So, I believe this issue has now been solved.

**Comment by scruffian** [comment]
Yes, looks like this can be closed, thanks all.
