### ISSUE TITLE
Add ability to set link text at creation time for Navigation links

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#50179]
The Link UI affords the ability to set the link text (_text_ not the URL) directly from the popover. However in recent times this has been moved into the link "settings drawer" meaning it is not immediately visible when creating a link.

This causes issues for the Navigation block when adding links into a menu.

We need to fix this to improve the flows.

When adding a link it should be possible to set _both_ the link URL and the link text during the initial creation phase. This will involve moving the text control out of the settings drawer.

**Comment by richtabor** [comment]
The current flow requires you to type a URL, apply it, then select the text and change it. Adding the text label alongside the link will make adding a link a more unified experience. 

Current: 

https://user-images.githubusercontent.com/1813435/235177557-a1622e7f-64e8-4f8b-af7b-29c1847f23f7.mp4

**Comment by jasmussen** [comment]
This is URL dialog relevant, not just navigation relevant, correct? CC: @SaxonF as I think he's dabbled with that interface as well.

**Comment by SaxonF** [comment]
The video[ in the link ui overview issue](https://github.com/WordPress/gutenberg/issues/49091#issuecomment-1473053480) should cover this

**Comment by richtabor** [comment]
> This is URL dialog relevant, not just navigation relevant, correct? 

I don't know that it's necessary in every context, but perhaps. I don't want to make links unnecessarily complicated if it's not necessary (adding the label wholesale). 

In the case of adding a link to text, you have the text already there at least. In the Navigation block flow, you add a link _without_ existing text - so the label uses the link instead, which is almost always going to be edited next; it's basically incomplete.

**Comment by getdave** [comment]
I understand the original motivation for hiding the link _text_ was to remove clutter from the UI. 

In this specific case however, I agree with @richtabor that the flow for adding links requires that we can set link text at point of link _creation_. The flow of 

- create link
- click into canvas
- edit text

...feels clunky. It would be much more fluid and natural if we could do the above in a single flow.

**Comment by richtabor** [comment]
I'm going to close this in lieu of #50890, which details the link edit state holistically (including link and text fields on edit)
