### ISSUE TITLE
Add description to Link Text field in Navigation Link block

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#50182]
When using the Nav link block the sidebar has various fields. One is `Link Text`. It's not clear how this is dfifferent from `Label`. Add descriptive help text below field to describe what it does.

<img width="284" alt="Screenshot 2023-04-28 at 16 23 36" src="https://user-images.githubusercontent.com/444434/235174166-4961dca0-04eb-4d85-b0eb-f6defbf021bc.png">

**Comment by juanfra** [comment]
As an addition: Would it make sense to change it from `Link Title` to `Link Title Attribute`? (and the same with `Rel`)

My thought process is that by using "attributes" you can give more clarity to the people that will be interested in using those (people with focus on SEO, etc).

**Comment by getdave** [comment]
We could also leave off the word `Link`. It seems unnecessary.

**Comment by juanfra** [comment]
Even better! We also need to do the same with the submenu link block.

https://user-images.githubusercontent.com/252415/235430581-8e48cb00-59d4-499a-a71c-0ee26b0c0a48.mov
