### ISSUE TITLE
Markdown links are not parsed in HTML blocks

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#5019]
Steps to reproduce:

1. Create a new post and add a link using markdown using an HTML block.
3. Save the post as a draft.
4. Go to All Posts.
5. Reopen post for editing.
7. Click Publish.
8. View the post.

<strong>Result:</strong> the markdown was not converted into a link.

<strong>Video:</strong> [3m3s](https://cloudup.com/chEsmc9O2fc)

![screen shot 2018-02-12 at mon feb 12 7 32 28 pm](https://user-images.githubusercontent.com/1119271/36131014-f028f822-102c-11e8-8ed1-fb29bd033190.png)
<sup>Seen at http://madefortesting.com/2018/02/13/new-title/ running WordPress 4.9.3 and Gutenberg 2.1.0 using Safari 11.0.3 on macOS 10.13.3.</sup>

**Comment by iseulde** [comment]
Hm, we don't support Markdown in the HTML block. Only HTML. Should we? he only way we support Markdown is through paste in rich text fields (e.g. paragraph).

**Comment by youknowriad** [comment]
Thanks for opening the issue, but I think I agree with @iseulde on this one. The HTML block should be for HTML. Markdown "shortcuts" could be used in RichText blocks. 

We may have a dedicated block for markdown in the future (or via a plugin)
