### ISSUE TITLE
Cannot unselect list block

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#502]
__Steps to reproduce:__

1. Navigate to the Gutenberg standalone page
2. Click within the list block (toward the bottom)
3. Try to click elsewhere on the page (outside canvas or another block)

__Expected result:__

The list block is unselected.

__Actual result:__

The list block flickers as unselected for a moment before once again becoming selected.

__Screencast:__

![list](https://cloud.githubusercontent.com/assets/1779930/25357508/061311b2-290c-11e7-8abb-ad0ee7271512.gif)

**Comment by BE-Webdesign** [comment]
Just opened this in #501 lol!

**Comment by aduth** [comment]
Funny timing on that 😄  Good to have the additional context with the TinyMCE error there. I wasn't seeing that in my console when I was testing.

**Comment by BE-Webdesign** [comment]
The TinyMCE error in the console, is unrelated, has to do with something else.  Not sure how that error was consistently popping up, but no longer does. ¯\_(ツ)_/¯

**Comment by iseulde** [comment]
If you run into it again, `The given range isn't in document.` is usually caused by the focus not being set, and trying to set a `Range`.

**Comment by BE-Webdesign** [comment]
This issue seems fixed for now somehow.  Another PR must have inadvertently solved this problem.  That can be kinda scary though.  Now that it is fixed there is another problem for the list block that I will patch up quickly.
