### ISSUE TITLE
Thanks @ramonjd. With the bones in place I can hopefully work on some of the styling / details next week. Watch this space!

### ISSUE THREAD

**Issue by jawomg** [WordPress/gutenberg#50204]
Thanks @ramonjd. With the bones in place I can hopefully work on some of the styling / details next week. Watch this space!

@jasmussen For styles a side-by-side could work:

https://user-images.githubusercontent.com/846565/235176038-57ec26b4-1687-45bf-a0ae-f446711df207.mp4

But it doesn't seem essential for a v1? It would be nice to have as an option.

_Originally posted by @jameskoster in https://github.com/WordPress/gutenberg/issues/50089#issuecomment-1527662011_

**Comment by ramonjd** [comment]
Feel free to reopen when there's more context and commentary on this issue. Right now I'm not convinced it's helpful.
