### ISSUE TITLE
The mobile menu toggle doesn't work

### ISSUE THREAD

**Issue by gyurmey2** [WordPress/gutenberg#50211]
### Description

The mobile menu toggle doesn't work after update to latest nightly version.

### Step-by-step reproduction instructions

1. Go to the mobile version of the menu.
2. Try to open the menu.

### Environment info

WP: 6.2
Gutenberg Nightly (15.8.20230429, 15.8.20230502, 15.9.20230504)
Theme: TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
I can replicate this issue with:

- WP 6.2
- Twenty Twenty-Three 1.1 or Twenty Twenty-Two 1.4
- Gutenberg Nightly 15.8.20230429
- No other active plugins

**Comment by gyurmey2** [comment]
The file **view-modal.min.js** is missing.
