### ISSUE TITLE
Navigation block - Please add support for the Button block

### ISSUE THREAD

**Issue by ChrisBegley** [WordPress/gutenberg#50227]
## What problem does this address?
Currently, only a few blocks can be added within the Navigation block:

- Site Logo block
- Social Icons block
- Search block

## What is your proposed solution?
Buttons are often a part of a website's navigation menu, like the "Get WordPress" button on WordPress.org. It would be nice if the Button block could be added within the Navigation block.

**Comment by talldan** [comment]
Thanks for reporting. It was already suggested in https://github.com/WordPress/gutenberg/issues/46256, so I'll close this as a duplicate.
