### ISSUE TITLE
Remove weird loading state in navigation panel

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#50224]
Whenever you go to the navigation panel this state flashes in, which is quite annoying. It'd be better to not have anything there:

<img width="314" alt="image" src="https://user-images.githubusercontent.com/548849/235502664-4510bd99-42db-4e69-ab75-06b19004faf8.png">

**Comment by annezazu** [comment]
Noting that this experience [was discussed here](https://github.com/WordPress/gutenberg/pull/48689#issuecomment-1525134410) with a suggestion to include a spinner:

>We don't really use a loading state like this anywhere else. Can you replace it with a spinner? And ideally a spinner that is delayed by perhaps .2ms so that it only appears if there's actually any loading to do.

Also noting this very related (perhaps duplicate) issue here: https://github.com/WordPress/gutenberg/issues/48682

**Comment by mtias** [comment]
There's a couple issues — the specific loading indicator used, and then the fact that it triggers all the time as you navigate back and forth which is a much bigger problem.
