### ISSUE TITLE
Search block button text alignment is not proper in the backend & front end.

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/gutenberg#50220]
### Description

While working with the Twenty Twenty-Two theme, I have checked that the Search block button text looks weird on the backend.

The search block button text alignment is not proper in the backend. 

Here, I have attached screenshots.

**Backend:**
![back_end](https://user-images.githubusercontent.com/53076293/235460387-b4092e85-d234-484c-a443-18ca93e0d850.png)

**Frontend**
![front_end](https://user-images.githubusercontent.com/53076293/235460528-79bacc5d-5392-4a85-9885-e7f84e6e8fae.png)

Thanks,

### Step-by-step reproduction instructions

- Go to "WordPress" admin and create a new test page.
- Add "Search Block"
- Change the **"Search Block"** button text and set it width from **"Display Settings"**
- Update the page and then view the page

### Environment info

- Environment info
- WordPress Version 6.2
- Mac M1 OS 13.3.1 (22E261)
- Google Chrome Version Version 112.0.5615.137 (Official Build) (arm64)
- Gutenberg Version: 15.6.2
- Theme: Twenty Twenty-Two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by kathrynwp** [comment]
I'm able to replicate this issue, but only when choosing a width value for the Search block below about 40%. For example, here's what 25% looks like in the editor:

<img width="1241" alt="Add_New_Page_‹_Test_Site_ABC_—_WordPress" src="https://user-images.githubusercontent.com/7662449/235485844-33bfd800-a618-48ad-a7a3-30fbfaaa8d44.png">

On the front end, the search input field becomes smaller to allow the button to be displayed in full:

<img width="204" alt="Search_box_–_Test_Site_ABC" src="https://user-images.githubusercontent.com/7662449/235485953-b7ca27f9-028b-401b-80f6-86c70d84230a.png">

Tested in:

- WordPress 6.2
- No plugins active OR just Gutenberg 15.6.2 active
- Twenty Twenty-Two 1.4 & Twenty Twenty-Three 1.1 (block themes), and Twenty Twenty-One (classic theme) - behaviour was the same in all

**Comment by kathrynwp** [comment]
Possibly related: #34469

**Comment by viralsampat-multidots** [comment]
Hell @kathrynwp

I have checked the above-mentioned issue and observed that this issue is not related to the above-mentioned issue. Width is increased and decreased  

**[Current Issue](https://share.cleanshot.com/LJR7VQ0YcXNXT7mWgG1b)**

Thanks,
