### ISSUE TITLE
Changing the background color on a vertical menu, submenus are not displayed correctly

### ISSUE THREAD

**Issue by hagege** [WordPress/gutenberg#50235]
### Description

While rebuilding a website with a vertical menue, I noticed that there seems to be an issue when I change the background color. In that case, if you have a submenu, the other main menu items are covered up.

### Step-by-step reproduction instructions

1. create a menu with a submenu
2. define the menu as a vertical menu
3. Anything is ok
4. change the background color of the navigation block
5. issue 

### Screenshots, screen recording, code snippet

![issue_submenue_navigation_vertical](https://user-images.githubusercontent.com/27292550/235577329-3179fe19-f352-43c1-849f-6d49798a5041.gif)
![issue_navigation_vertical gif](https://user-images.githubusercontent.com/27292550/235577979-9dfdbbb9-4d4a-4877-970b-96a9988def10.jpg)

### Environment info

`
### wp-core ###

version: 6.2
site_language: en_US
user_language: en_US
timezone: Europe/Berlin
permalink: /index.php/%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: D:\laragon\www\fse
wordpress_size: loading...
uploads_path: D:\laragon\www\fse/wp-content/uploads
uploads_size: loading...
themes_path: D:\laragon\www\fse/wp-content/themes
themes_size: loading...
plugins_path: D:\laragon\www\fse/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: HGG_2023_vertical_menue (hgg_2023_vertical_menue)
version: 0.0.1
author: Anonymous
author_website: (undefined)
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor
theme_path: D:\laragon\www\fse/wp-content/themes/hgg_2023_vertical_menue
auto_update: Disabled

### wp-themes-inactive (8) ###

Eksell: version: 1.9.5, author: Anders Norén, Auto-updates disabled
GeneratePress: version: 3.3.0, author: Tom Usborne, Auto-updates disabled
HGG Block Theme 2023: version: 0.1, author: Hans-Gerd Gerhards, Auto-updates disabled
HGG Blank Theme: version: 0.0.1, author: HGG - Hans-Gerd Gerhards, Auto-updates disabled
HGG\'s Theme: version: 0.0.1, author: haurand.com, Auto-updates disabled
Twenty Twenty: version: 2.2, author: the WordPress team, Auto-updates enabled
Twenty Twenty-Three: version: 1.1, author: the WordPress team, Auto-updates enabled
Twenty Twenty-Two: version: 1.4, author: the WordPress team, Auto-updates enabled

### wp-plugins-active (5) ###

Create Block Theme: version: 1.8.2, author: WordPress.org, Auto-updates disabled
Database Backup for WordPress: version: 2.5.2, author: Delicious Brains, Auto-updates disabled
Gutenberg: version: 15.6.2, author: Gutenberg Team, Auto-updates disabled
UpdraftPlus - Backup/Restore: version: 1.23.3, author: UpdraftPlus.Com, DavidAnderson, Auto-updates disabled
WordPress Importer: version: 0.8.1, author: wordpressdotorg, Auto-updates disabled

### wp-plugins-inactive (2) ###

Sticky Block: version: 1.11, author: Senff, Auto-updates disabled
WP Reset: version: 1.97, author: WebFactory Ltd, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 2G
upload_max_filesize: 2G
max_effective_size: 2 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.35 (Win64) OpenSSL/1.1.1k PHP/7.4.19
php_version: 7.4.19 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 36000
memory_limit: 512M
max_input_time: 60
upload_max_filesize: 2G
php_post_max_size: 2G
curl_version: 7.70.0 OpenSSL/1.1.1k
suhosin: false
imagick_availability: false
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 5.7.33
client_version: mysqlnd 7.4.19
max_allowed_packet: 536870912
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: D:\laragon\www\fse/wp-content
WP_PLUGIN_DIR: D:\laragon\www\fse/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by hagege** [comment]
@annezazu has confirmed the issue on slack channel #fse-outreach-experiment

**Comment by annezazu** [comment]
@getdave mind taking a look here?

**Comment by getdave** [comment]
I will add to my list of reviews and Issues.

**Comment by getdave** [comment]
@hagege Thank you for taking the time to report this Issue. It's much appreciated.

I tried to replicate the Issue you reported but I was unable to do so. I notice you had WP 6.2 with the Gutenberg Plugin enabled. Here is a video of me testing on the same setup:

https://user-images.githubusercontent.com/444434/236314614-d8c25952-8744-4389-b07c-beed38f62216.mp4

As you can see everything appears to be working as you'd expect and your Issue isn't present.

Are you able to provide any more detail about this error? For example are you able to replicate with a _default_ Theme such as Twenty Twenty Three? What about if you disable Plugins (except Gutenberg)?

Also any more steps to replicate would be super helpful.

Thanks again.

**Comment by hagege** [comment]
@getdave 
Thanks for the explanations.
I have now used TT3 (so without customizations) and disabled all plugins except Gutenberg. Nevertheless I get a not optimal display. E.g. the frame around the submenu is missing, which can be seen with the default color. Please see here:

![issue_submenue_navigation_vertical_2](https://user-images.githubusercontent.com/27292550/236378414-5b1604f0-9395-45a7-9f35-a6cfd1c06b62.gif)

Thanks.

**Comment by getdave** [comment]
@hagege Thank you for that extra information. Much appreciated. Can you advise on your OS and Browse please?

**Comment by hagege** [comment]
@getdave
Edition	Windows 10 Pro
Version	21H2
Installiert am	‎14.‎03.‎2021
Betriebssystembuild	19044.2846
Leistung	Windows Feature Experience Pack 120.2212.4190.0

Browser: Chrome Version 112.0.5615.138 (Offizieller Build) (64-Bit)
Same issue when using Brave or Edge

**Comment by getdave** [comment]
I was able to replicate something like this on TT3 by setting a background on the Navigation. 

In the editor the background is applied to the submenu.

On the front of the site the background _is not_ applied to the submenu.

This also happens on Mac. Now investigating fix.

**Comment by scruffian** [comment]
I have a fix here: https://github.com/WordPress/gutenberg/pull/50470

**Comment by scruffian** [comment]
I think this is a better solution: https://github.com/WordPress/gutenberg/pull/50968
