### ISSUE TITLE
FSE: when editing a navigation menu item's label, focus is lost each time you type a character

### ISSUE THREAD

**Issue by nekohayo** [WordPress/gutenberg#50255]
### Description

Everytime I type a character in the editing field for menu labels, it defocuses the field, so I have to click to refocus it after every typed character.

Furthermore, this makes it impossible to type accented characters using [dead keys](https://en.wikipedia.org/wiki/Dead_key) (ex: typing `^` then `e` to create `ê`).

### Step-by-step reproduction instructions

1. Insert a menu in the header template of your website and edit its contents using the sidebar on the right
2. Try to modify the label of an item in a submenu

See video below.

### Screenshots, screen recording, code snippet

[wordpress-6.2-gutenberg-menu-label-editing-focus-issue.webm](https://user-images.githubusercontent.com/479401/235723213-bd93cf33-e9ac-4471-b7db-02c1fab67e3a.webm)

### Environment info

- Fully updated WordPress 6.2, with the stock Gutenberg version that comes with it
- Tested on Firefox 112.0.1 on Fedora Linux 38, in the GNOME Wayland session.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
I am able to reproduce this using:
WordPress 6.2, no plugins, Twenty Twenty-Three
Mac OS
Firefox version 112.0.2

Tested the regular navigation block link, submenu, page list.

But  I can not reproduce it using Chrome version 112.0.5615.137
