### ISSUE TITLE
Deprecated block loses align attribute when upgrading to new version

### ISSUE THREAD

**Issue by bfintal** [WordPress/gutenberg#50281]
### Description

When you have a block that supports **wide** and **full** alignment, during block deprecation, they lose the `align` attribute and revert back to having no set alignment.

### Step-by-step reproduction instructions

1. Open a blank Block Editor, paste this code snippet in the browser console and execute it, this will register a block with which can reproduce the issue:

```js
wp.blocks.registerBlockType( 'example/has-wide-align', {
	title: 'Has Wide Align',
	supports: {
		align: true,
	},
	deprecated: [
		{
			attributes: {},
			save: () => wp.element.createElement( 'div', { 'data-new': 'deprecated' } ),
		},
	],
	edit: () => wp.element.createElement( 'div', { 'style': { background: '#ccc' } }, [ 'Just a block' ] ),
	save: () => wp.element.createElement( 'div', { 'data-new': 'updated' } ),
} )
```

This registered block above simply creates a dummy block that just has some save html on it, then there's a deprecation code for a different save html so that there's a clear upgrade path for the block. More importantly, the block has support for the `align` attribute, so you can set it to wide or full width.

2. Paste this block code into the editor, this block is wide aligned and this will trigger the block deprecation and upgrade the block. You may need to go into the **Code editor** to paste this in, after pasting, go back to the **Visual editor**.

Note that there is a `"align":"wide"` in the attribute of this block:

```html
<!-- wp:example/has-wide-align {"align":"wide"} -->
<div data-new="deprecated" class="wp-block-example-has-wide-align alignwide"></div>
<!-- /wp:example/has-wide-align -->
```

4. Click out of the code editor to trigger the block to be processed by the Block Editor. Afterwards, check the resulting block code, you'll notice that the `align` attribute is gone and was replaced with `className`

```html
<!-- wp:example/has-wide-align {"className":"alignwide"} -->
<div data-new="updated" class="wp-block-example-has-wide-align alignwide"></div>
<!-- /wp:example/has-wide-align -->
```

The expected behavior is the `"align": "wide"` attribute will be retained.

### Further investigation

I think this might be being caused by the `align` support attribute is added dynamically to the block during registration, and then it is not added in during block deprecation. So when the block deprecation triggers, it loses its knowledge of the `align` attribute, and the `alignwide` class falls back as an auto-detected `className` attribute.

### Environment info

- WordPress 6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @bfintal

You'll need to define similar `supports` in the deprecated object for it to work correctly.

This is also noted in the documentation - https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/. I'll try to update the documentation to make it more noticeable :)

> It’s important to note that attributes, supports, and save are not automatically inherited from the current version, since they can impact parsing and serialization of a block, so they must be defined on the deprecated object in order to be processed during a migration.


Try this example:
```js
wp.blocks.registerBlockType( 'example/has-wide-align', {
	title: 'Has Wide Align',
	supports: {
		align: true,
	},
	deprecated: [
		{
			attributes: {},
			supports: { align: true },
			save: () => wp.element.createElement( 'div', { 'data-new': 'deprecated' } ),
		},
	],
	edit: () => wp.element.createElement( 'div', { 'style': { background: '#ccc' } }, [ 'Just a block' ] ),
	save: () => wp.element.createElement( 'div', { 'data-new': 'updated' } ),
} )
```

**Comment by Mamaduka** [comment]
I've updated the docs in #50286 and will close the issue. However, feel free to re-open if you still need help with deprecation.

**Comment by bfintal** [comment]
@Mamaduka I see, thanks for pointing this out! I missed this tidbit and the callout you added helps make this point more apparent 🙌
