### ISSUE TITLE
Author Dropdown?

### ISSUE THREAD

**Issue by jpmuldoon** [WordPress/gutenberg#50299]
### Description

When I create a new post, the author dropdown is nowhere to be found.
Version 15.7.0

### Step-by-step reproduction instructions

Post -

### Screenshots, screen recording, code snippet

None needed

### Environment info

15.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aurooba** [comment]
@jpmuldoon what version of WordPress are you on? Using Gutenberg 15.7 on a clean WordPress install, I see the author dropdown in the Post Summary settings at the bottom.

<img width="294" alt="screenshot of the post summary panel showing the author dropdown" src="https://user-images.githubusercontent.com/6925260/236057306-41d81b67-ff73-4dad-901d-1590a2c07161.png">

**Comment by jpmuldoon** [comment]
Existing install
![image](https://user-images.githubusercontent.com/1918177/236059448-54aa0fc6-ecc7-4d64-98fd-9c2de52de313.png)

**Comment by kathrynwp** [comment]
@jpmuldoon -

- What version of WordPress are you using?
- Is the issue present with the standalone Gutenberg plugin deactivated?
- Is the issue present with **all** your plugins temporarily deactivated? You can use the Health Check plugin's troubleshooting mode for this, which will not change your live site – https://wordpress.org/plugins/health-check/  If the problem goes away, reactivate your plugins one by one (while still in troubleshooting mode) to find the culprit.
- Is the issue present with a default theme like Twenty Twenty-Three? Again, you can use the Health Check plugin for this.

**Comment by jpmuldoon** [comment]
WordPress 6.2
All I did was update Gutenberg (which has a history of bugginess, to be honest) from the plugins screen. Then I went to create a new post where I had to change the author name and discovered the option was gone.
The other stuff is interesting to know and I will get back to you on it.

**Comment by jpmuldoon** [comment]
@kathrynwp  Deactivated Gutenberg and activated Classic Editor. Author is at bottom of page when I scroll down in Classic Editor.

**Comment by Mamaduka** [comment]
Hi, @jpmuldoon

I see that the "Move to trash" button is also missing from your screenshot, usually displayed below the "Post Author" dropdown.

A few follow-up questions to help us narrow down the issue.

* Are you editing the post as administrator?
* What's the plugin's name that displays "Post Views" data below the "Post Formats" dropdown?
