### ISSUE TITLE
Site Editor: Site View doesn't properly render on mobile views

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#50303]
This came up as part of the [FSE Outreach Program's Front Page Fun call for testing](https://make.wordpress.org/test/2023/04/17/fse-program-testing-call-21-front-page-fun/#comment-3013), using GB 15.6.2:

>In the mobile view (Chrome Desktop and Android), the dark gray sidebar does not stay fixed and scrolls up, disappearing. I was expecting it to stay in place. [Here’s a GIF](https://dl.dropbox.com/s/5znuen3x25nhif1/dark-grey-sidebar.gif) demonstrating the issue.

![dark-grey-sidebar](https://user-images.githubusercontent.com/26996883/236084203-1801bdc1-427c-42f8-9096-a1d44962330b.gif)

>In landscape mode (Chrome Android), it only scrolls if I click in a specific area, and it’s not obvious that it can scroll ([GIF](https://dl.dropboxusercontent.com/s/lb72bdx511qtcsg/dark-grey-sidebar-scroll.gif)). It does not scroll at all in Chrome (mobile view).

![dark-grey-sidebar-scroll](https://user-images.githubusercontent.com/26996883/236084237-eb8b3dda-d2ed-43fd-92c0-3e86bfccbd7d.gif)

**Comment by t-hamano** [comment]
With the latest Gutenberg, these issues don't seem to reproduce. Can this issue be closed?

https://github.com/WordPress/gutenberg/assets/54422211/4d4a055c-60fe-47eb-978e-c67d6bf28239

**Comment by annezazu** [comment]
Yes! Let's close. Thanks for trying to replicate :)
