### ISSUE TITLE
Button additional CSS class isn't working properly

### ISSUE THREAD

**Issue by sannenijboer** [WordPress/gutenberg#5030]
## Issue Overview
To match a button-block to the rest of my design, I added an additional CSS class to it. The CSS I gave to this class, isn't working properly in combination with the original button. 
For example: I gave it a green 1px solid border, with a border radius of 3px. It doesn't change anything to the original button, but only added a border to the whole block.

I'm working in Firefox (58.0.1) on a macbook (macOS Sierra) with Gutenberg 2.1.0.

## Steps to Reproduce (for bugs)

1. Add a button-block
2. Give it an additional CSS class
3. Add CSS code to the class
4. Preview

## Expected Behavior

What I'm expecting is that the additional CSS class will overwrite the original CSS. Coming back to the example: the original button will get a border.

## Current Behavior

See the added printscreen. The CSS code is applied to the block instead of the button.

## Screenshots / Video
![screen shot 2018-02-13 at 11 42 29](https://user-images.githubusercontent.com/26793415/36151897-64fdc988-10c9-11e8-872f-b00a68153a15.png)

**Comment by twsp** [comment]
Where are you creating your additional CSS class? Or are you adding a style tag directly to the HTML element?

**Comment by sannenijboer** [comment]
I'm creating this class in the field below the color options of the button. (block settings)

**Comment by youknowriad** [comment]
Can you provide your CSS? Why do you think it's wrong? I guess you're trying to style the wrapper instead of `.wp-block-button__link`?

**Comment by mtias** [comment]
Closing but feel free to reopen if you have more info to provide.
