### ISSUE TITLE
Select the Gallery Block after transforming an Image to a Gallery

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#50308]
### Description

Possible solution to: https://github.com/WordPress/gutenberg/issues/50022

When transforming an image block to a gallery block, no block is selected afterwards. Therefore, a visual indication is missing.

### Step-by-step reproduction instructions

1. Select an image block
2. Transform it to a gallery.
3. no block is selected.

–

1. Select an image block
2. transform it to another block, like a cover block
3. The cover block is selected (as it should be)

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/17861443/236137604-b89072ac-df5d-44e0-ab98-1c01679bda11.mp4

### Environment info

- Wordpress 16.2
- Gutenberg 15.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I believe this is a bug. Other types of transformations select the block.
