### ISSUE TITLE
Quote block: Unexpected empty space is shown when merging/splitting a paragraph block

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#50311]
## Description
When merging and splitting two paragraph blocks within the Quote block, an expected empty space is displayed between the content and the citation element.

## Expected behaviour

Merging/splitting paragraphs within the Quote block shouldn't add extra empty space apart from the expected paddings and margins.

## Actual behaviour

Merging and splitting paragraphs within the Quote block is adding extra empty space between the content and citation element.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/236155281-f769c0bf-5e5c-4101-993f-94cbd1569627.MP4

_Issue can be observed in **00:04**._

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 11
- Operating system: iOS 15.4.1
- WordPress app version: 22.3.0.1

**Comment by fluiddot** [comment]
This issue might be related to https://github.com/WordPress/gutenberg/issues/42713.

**Comment by dcalhoun** [comment]
I am not longer able to reproduce this. Feel free to re-open if it is reproducible.
