### ISSUE TITLE
Docs for wp.data.subscribe do not reflect changes in  #5003

### ISSUE THREAD

**Issue by Shelob9** [WordPress/gutenberg#5032]
In these doc for wp.data.subscribe, and example of subscribing to changes in the post title is given:
https://github.com/WordPress/gutenberg/tree/master/data#wpdatasubscribe-listener-function-

This example is wrong, because of changes in #5003 I'll put in a PR.

**Comment by youknowriad** [comment]
Thanks for opening the issue @Shelob9 but what's wrong in the docs? The selector being used is just an example. These docs are meant to explain the data module and not the core/editor module's selectors.

**Comment by Shelob9** [comment]
The names of the selectors changes in #5003 I was updating them to match. But they have changed again since then.

**Comment by danielbachhuber** [comment]
Looks like this is no longer valid. Feel free to re-open if this isn't the case.
