### ISSUE TITLE
List block: style rule conflicts with Navigation block menu item with background color

### ISSUE THREAD

**Issue by RavanH** [WordPress/gutenberg#50342]
### Description

When there is a List block on a page, these style rules are added:

```
<style id='wp-block-list-inline-css'>
    ol,ul {
        box-sizing: border-box
    }

    ol.has-background,ul.has-background {
        padding: 1.25em 2.375em
    }
</style>
```

The problem with `ul.has-background` is that it not only affects the padding of the list block UL but _also_ the Navigation block when the sub-menus are set to have a different background color.

### Step-by-step reproduction instructions

1. Create a main menu with submenu items
2. Set a custom Submenu background color for that main navigation block
3. Add a List block to a page
4. Compare the main menu submenu items on the page with the List block to other pages without a list block

### Screenshots, screen recording, code snippet

![Schermafdruk van 2023-04-04 01-41-55](https://user-images.githubusercontent.com/1184853/236245636-1eac0217-7ad8-4a93-a102-dbc4c3288a3a.png)

### Environment info

- WordPress: 6.3-alpha-55716
- PHP: 8.1.18
- Server: Apache
- Database: mysqli (Server: 10.6.12-MariaDB / Client: mysqlnd 8.1.18)
- Browser: Chrome 113.0.0.0 (Linux)
- Theme: Twenty Twenty-Three 1.1
- MU-Plugins: None activated
- Plugins:
  * Gutenberg 15.7.0
  * WordPress Beta Tester 3.3.7

Note: the issue also occurs on WP 6.2 and without Gutenberg...

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by RavanH** [comment]
My suggestion: make the block list style rules more specific to the List block. For example:

```
<style id='wp-block-list-inline-css'>
    .wp-block-list {
        box-sizing: border-box
    }

    .wp-block-list.has-background {
        padding: 1.25em 2.375em
    }
</style>
```

And add the class `wp-block-list` to the List block element.

**Comment by cuemarie** [comment]
Created a more generalized report here: 

- https://github.com/WordPress/gutenberg/issues/50486

**Comment by iamtakashi** [comment]
It'd be great if this gets fixed soon. We need to add custom CSS to every theme to fix this issue.

**Comment by jordesign** [comment]
Closing this in favour of the duplicate/broader issue mentioned above.
https://github.com/WordPress/gutenberg/issues/50486

**Comment by RavanH** [comment]
Excellent. Thanks @jordesign :)
