### ISSUE TITLE
Multi-selected block card title should be capitalized

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#50347]
Just capitalize "b" in "blocks" so it looks proper. 

<img width="277" alt="CleanShot 2023-05-03 at 18 06 48" src="https://user-images.githubusercontent.com/1813435/236291780-169045b8-7080-4e9a-8565-5fd3e9068938.png">

**Comment by glendaviesnz** [comment]
It looks a little odd with [`w` in `words` still lower case](https://github.com/WordPress/gutenberg/pull/50356) - what do you think?

**Comment by richtabor** [comment]
I think it’s more odd that it’s not a sentence, like other block descriptions. “3 words selected.” or something.

**Comment by glendaviesnz** [comment]
> I think it’s more odd that it’s not a sentence, like other block descriptions. “3 words selected.” or something.

Do you want it updated to that? With a capital W if it is a sentence?

**Comment by richtabor** [comment]
Sure, let's do that.

**Comment by glendaviesnz** [comment]
> words selected.

@richtabor it actually looked wrong with W once it was a sentence as it obviously isn't the start of the sentence, so made it `3 words selected. ` and seems to look correct:

<img width="205" alt="Screenshot 2023-05-08 at 1 15 45 PM" src="https://user-images.githubusercontent.com/3629020/236713870-242e136e-9317-4bde-b1a5-895f9aa187f2.png">

**Comment by glendaviesnz** [comment]
I went ahead and merged it, but let me know if you are not happy with the `3 words selected.` approach and I will update.

**Comment by richtabor** [comment]
Looks great!
