### ISSUE TITLE
Template part replacement: reduce jumpiness of loading experience

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#50352]
## What problem does this address?

The template part replacement modal shifted to be more of a grid recently https://github.com/WordPress/gutenberg/pull/49894. As a result though, the current experience is quite jumpy. Here's what it looks like with TT3:

https://user-images.githubusercontent.com/26996883/236332415-41b75971-dfcf-4d6d-9945-b7b811ce5301.mov

This gets more jarring the more options you have baked in:

https://user-images.githubusercontent.com/26996883/236332831-8e6dcd3d-8a2f-498f-a4e2-edc02b7f7c74.mov

## What is your proposed solution?

- Adjust the design to accommodate the loading.
- Add a spinner of some sort.
- Improve the loading itself, related to https://github.com/WordPress/gutenberg/issues/35503

**Comment by annezazu** [comment]
FYI to @jameskoster since I know you've been iterating here.

**Comment by jameskoster** [comment]
I feel like this is closely related to https://github.com/WordPress/gutenberg/issues/35503 and the work there.

A per-pattern loader has been suggested before, but I think that may still result in jumpiness. If so it might be better to display a single spinner until everything has finished loading. 

<img width="856" alt="Screenshot 2023-05-05 at 09 34 07" src="https://user-images.githubusercontent.com/846565/236412280-4a4ba0d5-ce97-4ae0-baef-5c37ae86ab2f.png">

**Comment by annezazu** [comment]
This has gotten better in subsequent releases. Closing out for now.
