### ISSUE TITLE
List view options button loses focus style when hovered over

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#50357]
### Description

Hovering over a focused List View options button causes the focus style to be removed and it visually looks like a focus loss.

### Step-by-step reproduction instructions

1. Add some blocks to a post
2. Open List View
3. Tab into it and use the arrow keys to focus a non-selected block
4. Press the right-arrow key to focus the options button of that block
5. Hover over the button with a mouse and then move the cursor away

Expected: The focus style remains on the button
Actual: The focus style is lost and the button is hidden

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/677833/236376672-5d17a67a-d4f5-4dc2-8092-cfa75612a13a.mp4

### Environment info

Brave / Mac OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Thanks for writing this one up! I think it's just a one-liner to fix it. I have a PR open over in: https://github.com/WordPress/gutenberg/pull/50572
