### ISSUE TITLE
Stabilize the Title Bar

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#50378]
Related #50369, #50260, #50218, #50217, #48641

Let's solidify the design and describe all the states in detail so that implementation can go smoothly. There are functions being introduced (#44461) that necessitate the title bar.

### Site Editor

- Show page and template. Switch between the two edit behaviours.
- Include "view page" and "view post" actions.
- Connect with command center
  - Allow quick switching of templates or pages
- Show how template parts and focused template part mode work regarding the title bar. Same for menus. 

### Post Editor

It's unclear if we need to bring the title bar to the post editor at the same time or it can be in stages, but it'd be good to design the aspects that are necessary for the post editor context. Particularly editing the title and the permalink.

### Mockups

Main site editor title bar:

<img width="1472" alt="Title bar, desktop" src="https://github.com/WordPress/gutenberg/assets/1204802/83131675-3f5c-4403-b11b-36a86b71d7a8">

* Shows page title with icon, and ⌘K commandbar affordance in its resting state
* In "top toolbar" mode, it's hidden until you go back to the top level
* In the content template split (#49980), when you edit the template, a "back" button appears on the left
* In the resting state, the entire area is clickable to invoke the command bar, which can show contextually related commands (#50407)
* When editing a template part, the template part name is shown with its rhomboid symbol
* When first editing a template, then diving a step deeper into a template part, the "back" button behaves as a breadcrumb system

Scaling to mobile, and considering the top toolbar option across breakpoints:

<img width="1472" alt="Top toolbar, desktop and mobile, site editor" src="https://github.com/WordPress/gutenberg/assets/1204802/666f43ad-1539-4115-832c-014d64d7e5cc">

* As the viewport grows thinner, the width of the commandbar is flexible
* At smaller breakpoints the template "back" button loses its visible label.
* The title bar is not shown on mobile.

It is likely useful to keep this component site-editor first in the near future, but here is a sketch that explores adding it to the post editor.

<img width="1472" alt="Top toolbar, desktop and mobile, post editor" src="https://github.com/WordPress/gutenberg/assets/1204802/67ef4939-65f6-4dd5-9218-b4e655c55b71">

**Comment by jameskoster** [comment]
Here are the latest designs, let's refine.

### Editing a post or page in the post editor

https://user-images.githubusercontent.com/846565/236471055-80aac229-d9b7-463f-a399-8f7d19867c57.mp4

* Icon button on the left to view the page on the frontend (essentially a relocation of https://github.com/WordPress/gutenberg/pull/50260).
* Icon on the right to indicate the active entity type (post, page, template, etc).
* Clicking the pill exposes the command center with contextual suggestions based on the active entity.
  * Items in the 'Recent' group would load those entities into the editor. If there are unsaved changes the user should be alerted before leaving the current document.
  * "Manage pages" links to the pages list in wp-admin.
  * 'Edit URL' command would invoke this UI:
<img width="317" alt="Screenshot 2023-05-05 at 14 22 40" src="https://user-images.githubusercontent.com/846565/236469226-fe9c02b7-6a7a-4d3f-a9c2-724b055d7ac7.png">


### Editing a page in the site editor

https://user-images.githubusercontent.com/846565/236471806-52ab52c0-03a0-46a4-b217-9d8861487f91.mp4

This is virtually the same as the experience in the post editor, except we do not have a UI for editing the slug in the site editor yet, so that command is omitted for now.

### Editing a template in the site editor

https://user-images.githubusercontent.com/846565/236473861-a15a6e3e-4bbc-450f-8ab1-57b763db9850.mp4

* There's no View icon button as the majority of templates cannot be viewed in a traditional sense. We might want to conditionally include it for some templates like Front-page or Home, but that can be followed up on.
* The entity icon is purple (`--wp-block-synced-color`).
* Suggestions in the command center are template-centric.
  * 'Replace header', 'Replace footer' commands open the relevant modals as seen in the current replace flows:

<img width="1728" alt="Screenshot 2023-05-05 at 14 42 47" src="https://user-images.githubusercontent.com/846565/236474481-bfb21b10-9390-49d8-ae83-cf42d5448e1a.png">

### Edit page -> Edit template

Moving from editing content like a page, to editing the associated template is a flow that already exists in the Post Editor. It's also being [explored](https://github.com/WordPress/gutenberg/pull/49292) in the Site Editor. In such flows we can use the document title to offer a pathway back to the referring document:


https://user-images.githubusercontent.com/846565/236476298-3aa5b90b-3e89-4a5b-a4b1-4260a7b4cdd1.mp4

Where documents have long titles we'll need to exercise some truncation:

<img width="508" alt="Screenshot 2023-05-05 at 14 57 35" src="https://user-images.githubusercontent.com/846565/236478423-3af87d06-dfda-4df6-8717-5e60734a1e9c.png">

**Comment by richtabor** [comment]
I left this comment in [Figma](https://www.figma.com/file/PVjCcceB5jEVHX31wgcjPS?node-id=323:32347#437125387), but surfacing here for visibility. 

I lean towards having the externalLink on the right and classification icon aligned with the label. 

<img width="979" alt="CleanShot 2023-05-05 at 16 46 35" src="https://user-images.githubusercontent.com/1813435/236565810-d3daa36a-a89b-40b2-8331-f36f5618800e.png">

**Comment by SaxonF** [comment]
Agree with @richtabor about alignment. The post type icon to the right makes it look like it should be interactive.

https://user-images.githubusercontent.com/1072756/236743952-a6673542-879a-4ca7-9275-dbd23b0ff613.mp4

**Comment by jasmussen** [comment]
Nice one Saxon. I think that works well: ext-link on the right, page icon next to the title. I would use the same gray for the page title as the extlink button uses. 

Catching up on the requirements:

* Show page and template. Switch between the two edit behaviours. 
* Include "view page" and "view post" actions.

These seem addressed. I wonder if we should embrace the purple for the unit background as well? 

* Connect with command center

How is the command center invoked? I recall an older mockup that showed a keyboard shortcut, could that be an angle?

<img width="261" alt="Screenshot 2023-05-08 at 10 49 25" src="https://user-images.githubusercontent.com/1204802/236780074-c8b6d83f-49cd-46f3-b615-e39f55c5e6dd.png">

* Allow quick switching of templates or pages

That's the "Manage all templates" button from this one:

<img width="330" alt="Screenshot 2023-05-08 at 10 50 26" src="https://user-images.githubusercontent.com/1204802/236780521-fadf2faa-14f1-45ec-bc31-749f2833bb89.png">

Where does that live in the new? It's important we have one, so you have a deep-link to Design > Templates. Without it, you'd have to click Back and then Templates first.

* Show how template parts and focused template part mode work regarding the title bar. Same for menus.

This is one such example:

<img width="1392" alt="Screenshot 2023-05-08 at 10 52 19" src="https://user-images.githubusercontent.com/1204802/236780850-2b70fbd8-2dcb-48fa-8f47-63215f4ed563.png">

Finally, we need to consider how this scales to Mobile, as well as the new Top Toolbar mode. I did [some initial work on this here](https://www.figma.com/file/ERw9rIxFxJP19g4eJVfN15/6.3-issues-needing-design?type=design&node-id=180%3A7705&t=rT6QtMdMwssOaQhw-1):

<img width="1152" alt="Top Toolbar" src="https://user-images.githubusercontent.com/1204802/236781040-d7fb7544-ea27-46d6-8612-449a89068967.png">

I'm happy to take another pass at that, and include the latest design bits. @SaxonF do you have a Figma I can copy your work from? Given [the PR is already](#50369) underway and in a good state, it seems like a good one to hustle on.

**Comment by SaxonF** [comment]
Just to clarify, this is mostly @jameskoster and @richtabor great work, I just copied over from Figma :)

**Comment by jasmussen** [comment]
Ah, sounds good, do you have the Figma link handy? Found it.

**Comment by jasmussen** [comment]
Here's a quick stab at using the gray material that's already present in the PR and in a slew of designs. I've focused on including:

* Mobile and top toolbar contexts
* Show page and template. Switch between the two edit behaviours.
* Include "view page" and "view post" actions.
* Allow quick switching of templates or pages

<img width="1472" alt="No command center" src="https://user-images.githubusercontent.com/1204802/236806367-dab1ecc2-66e3-4dbe-9d37-191b0ad1fc19.png">

Missing from this are these two:

* Connect with command center
* Show how template parts and focused template part mode work regarding the title bar. Same for menus.

I'd love some input on how to best do that. Do we:

* Include a "search" icon to invoke it?
* Do we show the ⌘K shortcut, and perhaps let you click that shortcut as well?
* Something else?

**Comment by jasmussen** [comment]
Want to connect some dots, we can potentially close https://github.com/WordPress/gutenberg/issues/48481 in favor of this one, perhaps.

**Comment by jasmussen** [comment]
To follow up on this one:

> Connect with command center

Here's the older mockup:

<img width="3606" alt="Search" src="https://user-images.githubusercontent.com/1204802/236820855-64375f68-09a3-49d5-a72f-cae5d46cf034.png">

<img width="3480" alt="Search 2" src="https://user-images.githubusercontent.com/1204802/236820911-177c5cde-fc3e-4125-86ff-124029270bce.png">

Should we do that for now, but with a Search icon? It becomes a bit much now that we also have the external link icon in there. 

Another option is to show the search icon on the left, but only when you're not inside "template editing mode":

<img width="1472" alt="Basic command center" src="https://user-images.githubusercontent.com/1204802/236821254-45616bc6-1327-438f-86fc-bfb15dfe3aaf.png">

**Comment by mtias** [comment]
If the whole bar triggers the command palette, I'm not sure that the "view link" should sit within. Might make more sense to keep it next to the "preview" button (and change that one to icon button).

**Comment by jasmussen** [comment]
Here's how that could look, with a new look at integrating the command palette as triggered from the whole bar:

<img width="1472" alt="Title bar, desktop" src="https://user-images.githubusercontent.com/1204802/236850695-8b808a13-51e3-4be0-9906-f47e36ac3ed4.png">

Note that I'd still expect the "back" button to work for exiting the template editing aspect from #49980.

How the above might scale down to mobile:

<img width="1152" alt="Title bar, mobile and top toolbar" src="https://user-images.githubusercontent.com/1204802/236850931-edbd0588-be58-4114-87e1-2ee0c8c4d0e6.png">

**Comment by richtabor** [comment]
> How is the command center invoked? I recall an older mockup that showed a keyboard shortcut, could that be an angle?

> <img width="233" alt="CleanShot 2023-05-08 at 11 57 22" src="https://user-images.githubusercontent.com/1813435/236871773-a2ca8d97-b247-463f-b0a6-e9ed68c63ac1.png">

I was just thinking of this today as well. If we're removing ExternalLink from here, then maybe it's fine to have a teachable moment in the UI re the shortcut.

**Comment by SaxonF** [comment]
> I was just thinking of this today as well. If we're removing ExternalLink from here, then maybe it's fine to have a teachable moment in the UI re the shortcut.

Let's roll with that. External link should be a separate issue but personally don't think we should rush that decision.

**Comment by jasmussen** [comment]
Based on the feedback, I went ahead and tentatively updated this issue with the latest decisions and added the dev tag. If anything pops up as problematic, let's revisit.

**Comment by jameskoster** [comment]
Is there a reason for the exclusion of the cmd+k hint when editing a template?

**Comment by jasmussen** [comment]
No, we can keep it. I'll update.

**Comment by mtias** [comment]
Not to distract here, but it'd be good to start exploring how things behave if we move the primary button to the right of the ellipsis menu, or right before it but after everything else; how plugins would look, etc.

**Comment by SaxonF** [comment]
Kicked off work [here](https://github.com/WordPress/gutenberg/pull/50653) if anyone wants to contribute.

**Comment by jasmussen** [comment]
> Not to distract here, but it'd be good to start exploring how things behave if we move the primary button to the right of the ellipsis menu, or right before it but after everything else; how plugins would look, etc.

Quick sketch:

<img width="1472" alt="Top toolbar with save on the right" src="https://github.com/WordPress/gutenberg/assets/1204802/605bce83-3070-4dd7-86b0-e03d4fafb3a2">

[Figma](https://www.figma.com/file/PVjCcceB5jEVHX31wgcjPS/6.3-North-Star?type=design&node-id=888%3A61125&t=wP4iOWQCZRBvv3Gh-1).

**Comment by jasmussen** [comment]
For reference, I shared some updated mockups for the _mobile_ behavior [here](https://github.com/WordPress/gutenberg/issues/49774#issuecomment-1549515582), and depending on feedback I will update this issue.

**Comment by mtias** [comment]
Another use case to consider is the focused template part mode when engaged from a higher level template. The "back" breadcrumb never made much sense in the canvas and it'd be a nice opportunity to absorb it in the title bar:

<img width="1379" alt="image" src="https://github.com/WordPress/gutenberg/assets/548849/8d7b5c83-f21c-4339-a2bb-765f677112e8">

**Comment by jarekmorawski** [comment]
Hi there! This is exciting to see come to life as we have a flow in WooCommerce that could benefit from a similar solution. In the new block-based product editing experience, the product description will launch the visual editor, which could look and feel like a template part.

Borrowing ideas from some of the explorations I saw, we could show the template part name (in our case: Product description) in the new Title Bar and let the user easily go back to the main editor/form without switching contexts.


https://github.com/WordPress/gutenberg/assets/79307566/10567bdd-a279-401b-9114-ca5580f0abc3

**Comment by talldan** [comment]
<s>Just noticing that the top toolbar and title bar don't seem to be playing well together in the latest trunk:
![Screen Shot 2023-05-25 at 1 01 48 pm](https://github.com/WordPress/gutenberg/assets/677833/e60023b6-6561-4010-9760-fdcf724c06aa)</s>

edit: this was a regression, made a revert in #50937 to resolve the issue.

**Comment by mtias** [comment]
What's pending here to wrap the issue?

**Comment by jameskoster** [comment]
One detail we might consider is the view-on-frontend button. In the post editor we have:

<img width="276" alt="Screenshot 2023-06-05 at 11 31 43" src="https://github.com/WordPress/gutenberg/assets/846565/2821164b-c947-4c6b-b08e-f7dc66cc4a5e">

We could just paste that into the site editor as well, but it might be a bit strange for a button in the top bar to appear / disappear as you move between editing content / templates. Instead, we might incorporate it into the title bar:

<img width="993" alt="Screenshot 2023-06-05 at 11 36 25" src="https://github.com/WordPress/gutenberg/assets/846565/7b05a1c8-2478-4502-b8ba-ad678cfd874b">

**Comment by ndiego** [comment]
> One detail we might consider is the view-on-frontend button.

This would be a great addition. A question came up in the latest [call for testing](https://make.wordpress.org/test/2023/06/07/fse-program-testing-call-24-momery-makeover/) about how to view a page once you have made edits in the Site Editor, and it's currently a bit tricky. Any chance this enhancement could make it into 6.3? 🤞

**Comment by jasmussen** [comment]
The bulk here has been addressed, so I'm closing this one in favor of #51711 (a bugfix followup) and #52032, an enhancement.
