### ISSUE TITLE
Command Center: Add a button to invoke the cmd+k interface in site view

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#50375]
The [Command Center](https://github.com/WordPress/gutenberg/pull/49330) is a powerful tool, but there's no obvious way to summon it in Site View.

<img width="822" alt="Screenshot 2023-05-05 at 12 54 02" src="https://user-images.githubusercontent.com/846565/236452060-c5434ccc-6bdd-4539-b15d-0e065a453c4d.png">

An icon button in the 'site hub' area seems like a reasonable placement. To begin with a search icon might work, but this doesn't really capture the full scope of this feature, so we might consider other options.

**Comment by richtabor** [comment]
I think we should roll with the search icon. It's common enough and relative to the searching-for-commands action.

**Comment by jasmussen** [comment]
Agreed, let's go with the search icon for 6.3 and near future, then we can explore if/when it evolves into something else!
