### ISSUE TITLE
Site Editor: Augment template details panels

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#50389]
Related: https://github.com/WordPress/gutenberg/issues/50386

Template detail panels in the Site Editor include a description of the template:

<img width="388" alt="Screenshot 2023-05-05 at 17 03 54" src="https://user-images.githubusercontent.com/846565/236509386-363b4480-cbbf-4b59-b10e-3696a30205ca.png">

We can make these panels more useful. Some considerations:

* List template parts within the template, a way to contextually switch them, and potentially cross-link to their detail panels.
* Note the original author / theme, and last editor.
* Offer a way to edit settings such as:
  * "Posts per page" for archive templates.
  * What `front-page` should display (latest posts or a static page).
* Include quick links:
  * Revisions
  * Reset / delete / duplicate, and other actions.
  * Explore associated patterns (loaded from the directory, installed themes, etc).

**Comment by richtabor** [comment]
Let's close this in favor of the existing https://github.com/WordPress/gutenberg/issues/49597 issue. It's been updated to focus on template details for blog (index and home) and category template. 🚀
