### ISSUE TITLE
Site Editor: Augment the page details panel 

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#50386]
The page details panel in the site editor currently contains a permalink and generic description:

<img width="359" alt="Screenshot 2023-05-05 at 16 04 00" src="https://user-images.githubusercontent.com/846565/236495676-fb3ceba5-03be-4931-8ae5-c25396c048a8.png">

This panel could be more useful if we surfaced page details (e.g. featured image, slug, template, revisions) and pathways to edit them. Special pages may need unique treatments:

* Homepage (displays posts)
* Static home page
  * Posts page

**Comment by jasmussen** [comment]
Thanks for the issue. I'm consolidating with #50386.
