### ISSUE TITLE
gutenberg_load_plugin_textdomain is looking for an incorrect directory

### ISSUE THREAD

**Issue by strategio** [WordPress/gutenberg#5038]
## Issue Overview
In `gutenberg_load_plugin_textdomain`, the last argument passed to `load_plugin_textdomain` is pointing to `gutenberg/lib/languages/` instead of `gutenberg/languages/`.

## Steps to Reproduce (for bugs)
1. Build the `pot` file with `npm run gettext-strings`.
2. Create `po` and `mo` files in another language (let's say French => `gutenberg-fr_FR.mo`) and place the files in `gutenberg/languages/`.
3. Translate the string "Add block" to "Ajouter un bloc" (this is the first top left corner tooltip for the "+" icon).
4. In your WordPress profile, change the admin language accordingly (i.e. French).
5. Open the Gutenberg editor, and mouse over the "+" icon.

## Expected Behavior
=> The tooltip should display "Ajouter un bloc".

## Current Behavior
=> The tooltip display "Add bloc" (the string is not translated).

## Related Issues and/or PRs
This issue has probably been introduced by https://github.com/WordPress/gutenberg/pull/985

**Comment by aduth** [comment]
Fixed by #5040
