### ISSUE TITLE
Details View → Template Part

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#50392]
<img width="1955" alt="Template parts 2" src="https://github.com/WordPress/gutenberg/assets/846565/6e2bf621-0e35-44fb-83ee-2becdc2a379e">

Show relevant blocks if they are used on the template part.

- [ ] Site title & tagline
- [ ] Site logo element (the one we have in the inspector of the logo block).
- [ ] https://github.com/WordPress/gutenberg/issues/52124
- [x] Navigation menu (should already be expanded if it's a "light menu").

"Added by" section to appear when the template part was added by a plugin or user. 

### Ellipsis menu (next to Edit button)

- [ ] Delete
- [ ] Rename (for custom template parts)

**Comment by SaxonF** [comment]
https://user-images.githubusercontent.com/1072756/236998884-5b7d6e1b-7d12-42be-bc99-f109962cfc34.mp4

Much like other detail panels, the template part panel needs work. If we take the same philosophy as the pages panel we should take an info first approach to this. It’s also a great space to give more attention to blocks that are structurally important to your site. The most basic example is the navigation block.

- [ ] Show created by date with author
- [ ] If theme created, show theme name instead
- [ ] If a template part contains any of the following blocks, they should be listed under template part details within an edit section. `Site title`, `Site logo`, `Site Tagline`, `Navigation`
- [ ] Each of these block menu items should open the editor with the block selected and inspector open
- [ ] In a details section we can initially show what area a template part belongs to. This ties into the [broader library work](https://github.com/WordPress/gutenberg/issues/50397) so might not be ready for this particular issue.
- [ ] Secondary actions include “Delete” and “Duplicate” which can be found in DropdownMenu triggered via ellipsis next to edit 

**Connections**
What do people need to learn about a template part? Template parts are just another type of building block for your site, so we can probably look at other tools that have similar library concepts for inspiration. Figma for example gives you an overview of how a component is being used across the team. This is also relevant for websites, perhaps more so because they are viewable by the public. If I edit this template part, what other parts of my site will be affected? In future, we should providing connections between blocks.

**Comment by jameskoster** [comment]
Here are some updated visuals based on Saxon's above, factoring in other designs that are coming into focus like [meta actions](https://github.com/WordPress/gutenberg/issues/50379). 

First of all let's clarify the details that should appear based on the template part _source_.

<img width="1843" alt="Template parts 1" src="https://github.com/WordPress/gutenberg/assets/846565/987b0039-7a29-4d2b-a0de-fe678d138db7">

* Theme-supplied template parts detail the assigned area
* User-generated template parts detail the assigned area and the author
* Plugin-supplied template parts detail the assigned area and the plugin that added it
* All template parts include information about who last made changes, with access to revisions.
* The area detail will be read-only to begin with.

---

It's common for headers and footers to contain blocks that display site data like the title, logo, and navigation menus. These can be included in the sidebar offering a quick way to edit without engaging the full screen editor:

<img width="1955" alt="Template parts 2" src="https://github.com/WordPress/gutenberg/assets/846565/41ad4b16-8831-42b2-8fc7-929890e30b9f">

* Site Title and Tagline can be edited via modal
* Site logo can be edited on click. This is essentially the same pattern as the Site Logo block's Media control in the Inspector.
* Navigation menus are listed with full edit-ability. When multiple menus are included they are stacked. This is to ensure visual context is always provided by the frame. This part is a bit intricate, so has a dedicated issue: https://github.com/WordPress/gutenberg/issues/50704

**Comment by jasmussen** [comment]
The spacing here seems a bit large:

<img width="547" alt="Screenshot 2023-05-22 at 14 57 00" src="https://github.com/WordPress/gutenberg/assets/1204802/890129b9-723a-4609-a2d2-da46d3595bd6">

And the alignment here might benefit from columns:

<img width="475" alt="Screenshot 2023-05-22 at 14 57 09" src="https://github.com/WordPress/gutenberg/assets/1204802/f7ff101b-6e62-49e1-b02b-625be9ef899d">

Other than that, this seems pretty solid to me.

**Comment by jameskoster** [comment]
Couple of updates here:

### Basic template parts
<img width="1843" alt="Template parts 1" src="https://github.com/WordPress/gutenberg/assets/846565/e56482c4-9a81-4c30-85dd-30f7f215fddd">

### Template parts containing navigation menus, and site settings
<img width="1955" alt="Template parts 2" src="https://github.com/WordPress/gutenberg/assets/846565/d52d1e04-dbb1-4532-a04c-a63f98cf779f">


* Detail rows arranged over two equal columns with left-aligned values.
* Various settings brought into the panel (e.g. Title / Tagline inputs). These can use the modals from before if current componentry cannot achieve the design above.
* Updated colors.

There are on-going discussions in https://github.com/WordPress/gutenberg/issues/50704 about how to handle multiple menus, so I left that out for now. When there's a single menu it seems fine to go ahead and display it.

**Comment by jasmussen** [comment]
Nice. Color updates look good, spacing updates look good. 

One last question, and it migth be useful to see the frame on the right in a mockup to be sure. One thing I like about the current setup, is that there's no separator between site hub and sidebar content:

<img width="494" alt="Screenshot 2023-05-25 at 08 51 21" src="https://github.com/WordPress/gutenberg/assets/1204802/92eadc6a-cb62-4e0d-9d1b-eb35192d0cb0">

And the larger whitespace above the section title I quite appreciate as it gives emphasis and breathing room on the left. Has that been removed in these mockups? It may just be me, but I find that this spacing and the lack of the separator gave it a lot of character, and I'd hate to see that disappear. We can still reach the above if you need to scroll, through a sticky header, but the default state I'd keep the space. 

I'd also keep the view site link hidden until hover. The current conversations around its behavior haven't been fully hashed out, and if we can't hide them, we'll need to find a different place for that link.

**Comment by jameskoster** [comment]
View site link is being worked on in https://github.com/WordPress/gutenberg/pull/50420 👍

The spacing is a part of the other metrics we need to figure out. Title sizes, margins, back button, etc. I'm starting to think it might be worth opening a dedicated issue about that, as we've gone back and forth a lot.

For this particular issue, how do we feel about the panel contents? Ready to update the OP and mark as ready for dev?

**Comment by annezazu** [comment]
Where are we at with this, especially considering the work around consolidating patterns, including template parts, in the new library/pattern section? Seems like it's not clear if this is ready for dev. Doing a sweep as part of a phase 2 update and 6.3 core editor triage.  cc @WordPress/gutenberg-design

**Comment by jameskoster** [comment]
@annezazu Navigation menus can be edited from the template part details panel now. Editing the Site title, tagline, and logo are missing, as are the revisions link. IMO these are all ready for dev. 

Edit: I updated the OP to remove the Duplicate & Replace actions. They're worthy of extraction to dedicated issues.

**Comment by mtias** [comment]
The other thing I wanted to include is the ability to swap / cycle patterns on a template part.

**Comment by jameskoster** [comment]
Isn't that the "Replace" action? Or did you think it should be more prominent?

**Comment by jasmussen** [comment]
I vaguely recall us talking about showing thumbnails for alternate header/footer patterns, even showing which one was active denoted as such.

**Comment by mtias** [comment]
Yeah, more prominent showing related patterns for specific areas. Something to explore later. Also highly related to #44582

**Comment by jameskoster** [comment]
I'm not sure it's possible to mark an active one, as once a pattern is inserted it's disassociated with the source, unless it's synced. But yes it's an option to display patterns in the sidebar, it will make it very long accounting for all the other affordances though:

<img width="1560" alt="Header" src="https://github.com/WordPress/gutenberg/assets/846565/57a66235-3eab-422c-aada-31b1a2a77430">


I don't know if it needs to be so prominent, replacing the entire design of a header probably isn't something you do all that often? 🤔

**Comment by jasmussen** [comment]
Can the thumbnails be in two colunns? Does that get too small?

**Comment by jameskoster** [comment]
It will likely depend on the template part in question. Let's spin up a separate issue to explore.

**Comment by mtias** [comment]
I'm closing this as outdated with the work now of unifying details view and in-editor inspector.
