### ISSUE TITLE
Details View → Page

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#50390]
The page details panel in the site editor currently contains a permalink and generic description:

<img width="359" alt="Screenshot 2023-05-05 at 16 04 00" src="https://user-images.githubusercontent.com/846565/236495676-fb3ceba5-03be-4931-8ae5-c25396c048a8.png">

This panel could be more useful if we surfaced page details and pathways to edit them: 

- Featured image.
- Excerpt.
- Title (should be editable)
- Slug / URL (should be editable).
- Published and modified date at the bottom (next to save action).
- Template (only if there are more than just the default page template).

Special pages may need unique treatments:

* Homepage (displays posts)
* Static home page
  * Posts page

### Ellipsis actions (next to Edit button)

- Delete
- Duplicate

### Mockup

Here's an updated design with a couple of additional details:

<img width="1493" alt="Page" src="https://github.com/WordPress/gutenberg/assets/846565/ad46e641-73e8-4aa4-ae0b-cddf4e47ce47">

**Comment by SaxonF** [comment]
![image](https://user-images.githubusercontent.com/1072756/236994621-931f32b6-47da-40b2-9160-b8b3a14dcf38.png)

The page detail panel offers a great space to provide a quick view into the makeup and performance of a page. We’ll start simple with the most basic of information (e.g. treated similar to OG link previews) but should also design it such a way that allows for extension by plugins (e.g. page statistics).

We can take some inspiration from other tools that give you an insight into a document/record/file e.g. finder or Craft

<img width="266" alt="image" src="https://user-images.githubusercontent.com/1072756/237007788-68c2e521-1468-4275-b6f1-de85475b3b3c.png">

![image](https://user-images.githubusercontent.com/1072756/236995812-d248f56f-2f1b-4fd2-8ce5-a9a9499d1213.png)

- [ ] Show day was first published if published
- [ ] OR show day draft was first created if not published
- [ ] Show featured image if it exists 
- [ ] Show post excerpt if it exists
- [ ] Show’s which template a page is currently using. Clicking on the template name takes you to the template details panel.
- [ ] Clicking back on the template details panel takes you back to the page panel
- [ ] Secondary actions include “Delete” and “Duplicate” which can be accessed via a `DropdownMenu` ellipsis next to edit

As we build this view out, along with any other view on the dark canvas, we should ideally by updating any primitive components to make use of the [new theme provider](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-theme--default) .

@mtias I've purposely stripped this right back for 6.3 which means read only, no editing. We have a bit of work to do around componentry, mixing read vs write info (e.g. plugins), and how we handle [localised saving](https://github.com/WordPress/gutenberg/issues/50379) which makes editing certain fields a bit more complicated.  Thoughts on creating follow-up issues for any high level editing needs as we come across them?

**Comment by jameskoster** [comment]
Here's an updated design with a couple of additional details:

<img width="1493" alt="Page" src="https://github.com/WordPress/gutenberg/assets/846565/ca1b47e2-5490-4d6a-a78a-0874172d577e">

I removed the excerpt affordance as (afaik) pages do not make use of them in the same way as posts. Easy to add back if needed. 

@WordPress/gutenberg-design what do you think? Is this one ready for dev?

**Comment by paaljoachim** [comment]
I got to say that this looks great!
Being able to drill down into a page and later on posts and seeing the most important things is very helpful!
Personally I would not care about time to read in a page. Perhaps I would in a post.

What is important here is status. 
Featured image if the page has one. Might just not have one as it is not needed for a page.
Details.
Template, Parent, Words, Time to read.

Last modified is very helpful.

All in all this is very very nice!

**Comment by SaxonF** [comment]
@jameskoster development has [already started](https://github.com/WordPress/gutenberg/pull/50767) :)

**Comment by jasmussen** [comment]
Since it's already underway, I've triaged it as such 🚀

**Comment by jameskoster** [comment]
> Being able to drill down into a page and later on posts and seeing the most important things is very helpful!
Personally I would not care about time to read in a page. Perhaps I would in a post.

Yeah some of the details feel foundational while others (like time to read, word count) will be more subjective.

Outside of the foundational items, it might be worth exploring toggle-ability of some of the less-important details. Kind of like the "Screen options" affordance in wp-admin.

**Comment by jasmussen** [comment]
> Outside of the foundational items, it might be worth exploring toggle-ability of some of the less-important details. Kind of like the "Screen options" affordance in wp-admin.

Always an option, but also an option I would punt until we have a high degree of polish and solidity of the initial items, so we get a higher confidence in what to keep vs. what to remove.

**Comment by jameskoster** [comment]
Yup, definitely something to look into later.

**Comment by ramonjd** [comment]
I think we can close this now that https://github.com/WordPress/gutenberg/pull/50767 is merged? 

There's a minor [follow up](https://github.com/WordPress/gutenberg/pull/51093) to refactor a few things, but it's only code-related and the UI/UX isn't changing.

Feel free to reopen if there are outstanding issues related to the page details view.

**Comment by mtias** [comment]
Sounds good to close, we'll have smaller follow ups to do.
