### ISSUE TITLE
Expose Style Book in Styles details view

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#50393]
Let's add a control to easily dive into the Style Book from the Site Editor > Styles panel. 

## Visual 

<img width="609" alt="CleanShot 2023-05-05 at 18 23 08" src="https://user-images.githubusercontent.com/1813435/236578284-4291aa26-2a3f-4064-bef8-434dd615cf25.png">
Added by @richtabor for feedback.

**Comment by jasmussen** [comment]
The eye seems the easiest starting point, and does not preclude future changes, so I think we should start with that.

The "Styles" section, I could see in the future, containing other options, such as font sets, or even high level color palette switching. That's something to be explored, but if that were the case we'd need another detail page before you get to style variations like we have now. In such a context, we _could_ consider the style book being a menu item. Even then, so long as the style book lives inside the fullscreen view, its context near the edit button seems useful.

**Comment by richtabor** [comment]
>  In such a context, we could consider the style book being a menu item. Even then, so long as the style book lives inside the fullscreen view, its context near the edit button seems useful.

I'm thinking the same. 👌

**Comment by annezazu** [comment]
Curious how we can, in adding the Style Book here, also ensure the Style settings open up properly when selecting on individual items:

https://user-images.githubusercontent.com/26996883/236899528-2f92504b-343e-4cf3-91e2-73d601753c52.mov

This is a high impact part of the Style Book implementation right now and I could see this being a jarring flow currently if it dropped you out of the Site View and into the Edit View with the Style settings open.

**Comment by richtabor** [comment]
> ensure the Style settings open up properly when selecting on individual items

This was resolved recently in https://github.com/WordPress/gutenberg/pull/49350 I think.

**Comment by annezazu** [comment]
Exactly! I'm saying that's a high impact feature to ensure works intuitively in this experience too. Right now, I think it would be pretty jarring to go to Design > Styles > Open Style Book and click on a block only to have you moved out of the Site View and into the Edit View with Styles open.

**Comment by richtabor** [comment]
> Design > Styles > Open Style Book 

I think this action would invoke Style Book entirely, bringing you into Edit View with Styles open and triggering Style Book. Just like how the "Edit" brings you into the Edit View, with Global Styles open.

**Comment by andrewserong** [comment]
I've had a go at this one over in https://github.com/WordPress/gutenberg/pull/50566
