### ISSUE TITLE
Finalize site hub elements

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#50394]
Placement and interactions of the command center, site icon and view site actions.

### Visual
<img width="843" alt="CleanShot 2023-05-05 at 15 42 58" src="https://user-images.githubusercontent.com/1813435/236554857-ebb6d0fe-3c2e-48de-af0a-07429aba8658.png">

### Main Tasks 
- [x] https://github.com/WordPress/gutenberg/pull/48886
- [x] https://github.com/WordPress/gutenberg/issues/50375
- [x] #50405
- [x] Consider adding back action for Site Editor Site Icon to navigate to WP Admin

### Secondary Tasks
- [ ] https://github.com/WordPress/gutenberg/issues/50288

**Comment by annezazu** [comment]
Added this to the phase 2 board as it's now listed as a main task on the Phase 2 issue. It's not clear to me what stage we're in: needing dev or design. I've added needs design for now. Feel free to update.

**Comment by mtias** [comment]
I'm closing this given there's not enough clarity on the "view site" action, which we can follow up on #50405.
