### ISSUE TITLE
Add action to "View Site" from the Site Editor sidebar

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#50405]
It is not possible to view your site within the Site View of the Site Editor. You can only do so after navigating into the Canvas and selecting the "View" selector in the editor toolbar.  

Let's explore adding a "View Site" action from the Site Hub perhaps, to enable people to quickly view their site in a new tab. 

### Proposal

<img width="444" alt="CleanShot 2023-05-05 at 15 55 45" src="https://user-images.githubusercontent.com/1813435/236557051-ddc0c471-bc18-4769-84a1-3a500092b0cf.png">

**Comment by richtabor** [comment]
I don't love the varying sizes between the `externalLink` and `search` icons here. 

Perhaps we could use a smaller variant of the `externalLink` icon (if not edit the current to be a bit smaller). 

A smaller icon would also work better in the context of the Title bar (https://github.com/WordPress/gutenberg/issues/50378#issuecomment-1536316613), and the newer [ViewLink](https://github.com/WordPress/gutenberg/pull/50260) component in the editor header:

<img width="425" alt="CleanShot 2023-05-05 at 15 59 06" src="https://user-images.githubusercontent.com/1813435/236557602-e45f2c20-719e-44d4-8be5-ccebb676728e.png">

**Comment by glendaviesnz** [comment]
Woops, overlooked the `Needs design feedback` tab. Was a pretty quick task to [put up a PR](https://github.com/WordPress/gutenberg/pull/50420) though, so nothing lost if we don't go ahead with this.

**Comment by jasmussen** [comment]
I wonder if in the site view, the site title could work as a link? I'm mainly thinking ahead to other options sitting in the site hub. A "plus" to add content, for example, could potentially sit there. I would think in the near term we can probably do with a plus in the title area of a detail page, but I still have a feeling that eventually such a plus will be convenient there.

I would agree we need a harmonized external link icon. I think we can potentially update the main icon directly, I don't think we need two variants. The only thing to be careful of there, is searching the codebase for any instances where we are using it at half size, I think that is done in help-text in a few instances.

**Comment by glendaviesnz** [comment]
> I wonder if in the site view, the site title could work as a link

Sounds like a good idea to me, we can add the 'Visit site' tooltip to it as an extra prompt - let me know if you want me to just switch that PR to do that for now instead of the extra icon.

**Comment by richtabor** [comment]
> I wonder if in the site view, the site title could work as a link?

Maybe so? Although it's unclear that clicking site icon in the hub will take you back to WP Admin, but clicking the site title will take you to the front-of-site.

**Comment by jasmussen** [comment]
Mainly I would urge caution in adding items to the site hub, keep it as contextual as possible as long as possible. I might see a "plus" button there to add new content, such as posts or pages, and we probably don't want to end up with too many buttons. It's a tricky balance.

**Comment by glendaviesnz** [comment]
Should I just close [my PR](https://github.com/WordPress/gutenberg/pull/50420) for now while this is discussed further?
