### ISSUE TITLE
Add dynamic templates to pages list

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#50418]
## What problem does this address?

Templates can often be a confusing concept to WordPress beginners or even experienced end users who haven't been exposed to site editing. A lot of this confusions stems from the idea that templates are smartly mapped to certain dynamic pages, and thus could be seen as pages themselves. Visit your site's homepage and you naturally think of it as just another page. 

## What is your proposed solution?

This work aims to reduce some of that confusion by surfacing more general templates in the pages list. This is a follow up to https://github.com/WordPress/gutenberg/issues/44461

<img width="1001" alt="pages" src="https://github.com/WordPress/gutenberg/assets/846565/3d1033e4-4ec0-41a2-96e5-dca91c1558c8">

**Acceptance**

- [ ] If 404 template exists, include in the list using layout icon
- [ ] If search template exists, include in the list using layout icon

Homepage displays latest posts:

- [ ] Include a "Homepage" item using the home icon
- [ ] The homepage item should open the template details panel for `front-page` OR `home` OR `index` in that order

Homepage displays a static page:
- [ ] The page that is marked as homepage should use the home icon with "front page" subtext
- [ ]  The page that is marked as blog should use the loop icon with "posts page" subtext
- [ ] The homepage item should open the page details panel
- [ ] The blog page item should open either `home` OR `index` template details panel in that order

**Comment by jameskoster** [comment]
Looks good to me.

> In reading homepage settings, if "your latest posts" is enabled , include a "Homepage" item using the home icon

If we think the home icon is adequate, could the label be "Latest posts" to align with the settings? Alternatively "Blog" could align with other areas of the UI like the template groupings we've discussed.
