### ISSUE TITLE
`RadioControl` doesn't follow theme colors

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#50428]
Currently, the `RadioControl` component doesn't inherit the theme colors. Here's an [example from Storybook](https://wordpress.github.io/gutenberg/?path=/story/components-radiocontrol--default&globals=componentsTheme:darkBg), when picking the "Dark (background)" theme preset from the top toolbar:

![Screenshot 2023-05-08 at 14 26 15](https://user-images.githubusercontent.com/1083581/236823757-9a54e283-2bdd-41e2-bbc7-dc702df3de74.jpg)

Both the text color and the UI "accent" color should be updated.

Furthermore, from playing around in dev tools, it seems like the existing styles (especially the `background` and `border-color` rules) don't affect the appearance of the `input`.  If we want to continue to add [custom styles](https://github.com/WordPress/gutenberg/blob/ecbde0e846ce3958f125302cfeda1cd34b5b89e3/packages/base-styles/_mixins.scss#L296-L337) to our radios, we should probably add `appearance: none`. Alternatively, we could look into using [`accent-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color) instead, now that it's supported by all evergreen browsers

**Comment by ciampo** [comment]
cc @mirka @jasmussen

**Comment by jasmussen** [comment]
Sounds good. What are the next action items? I would assume colors behave in this component similar to how they behave in checkboxes or toggles.

**Comment by ciampo** [comment]
IMO, next action items should be something like:

1. Understand if and why current color overrides are not working as expected
2. Understand which approach we want to adopt:
   - Do we want to apply the new styles only to `RadioControl`, or should we modify the mixins in the `@wordpress/base-styles` package, thus affecting all inputs in Gutenberg?
   - Should we aim at making the least amount of code changes possible (ie. trying to add `appearance: none`), or should we try to overhaul the styles, getting rid of the custom CSS code and switch to a more modern approach using `accent-color` ?

@jasmussen , do you have a link to the current design specs for radios and checkboxes? That may help us with the above decisions

**Comment by jasmussen** [comment]
I will defer the technical details to you. 

[Here's the component in the Figma library](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?type=design&node-id=28524%3A24057&t=lAug8uJFVB2P5cCw-1),

<img width="511" alt="Screenshot 2023-05-09 at 12 27 02" src="https://github.com/WordPress/gutenberg/assets/1204802/fbec177b-a220-4488-8dd4-c9ba98d3a3b4">

As you can see, there's not yet a "radio plus text" Figma component. But the metrics and behavior as well as focus style should be appropriate.

**Comment by ciampo** [comment]
Thank you! We will try to find some time soon to take a proper look and work on this
