### ISSUE TITLE
Details view → Styles

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#50429]
The Design → Styles view serves three purposes:

* Surfacing style variations for quick switching
* Surfacing a deep-link to the global styles panel in the edit view
* Provide quick-access to style revisions

### Variations
![Image](https://user-images.githubusercontent.com/1204802/236838933-4cedc7a0-bc96-4a0f-8cb6-1d83f17fbd95.gif)

If the theme does not offer style variations, then the view becomes rather empty and incongruent:

![Image](https://user-images.githubusercontent.com/1204802/236839299-fd08c062-e19d-4a04-8322-ebbc68d8a486.png)

We should improve this in a way that lets us keep the deep link to the global styles panel. A couple of ideas for what we could do:

* Keep the drilldown, but change the verbiage when there are no style variations. Perhaps: `Any style variations for your theme will show up here. For now you can click the edit button to edit style properties.`
* Remove the drilldown, and simply have the "Styles" link go directly to the edit view, with the global styles panel open.

- [x] Update panel to account for no variations – https://github.com/WordPress/gutenberg/pull/50573

### Style book
<img width="359" alt="Screenshot 2023-05-25 at 10 05 48" src="https://github.com/WordPress/gutenberg/assets/846565/9b4dc28c-aba9-4d6f-b8cd-1121316b730b">

- [x] https://github.com/WordPress/gutenberg/issues/50393

### Revisions

For access to revisions, we can use the same design as other panels, positioned directly above the save button:

<img width="899" alt="Screenshot 2023-05-25 at 10 02 54" src="https://github.com/WordPress/gutenberg/assets/846565/6b2dae7c-a7b3-48d6-b910-e50243fdcaf6">

- [ ] Add revisions access

It would be nice to load the revisions UI into the sidebar itself, but in the short term it may be necessary to deep link to the revisions panel in the full-screen editor.

**Comment by jasmussen** [comment]
CC: @WordPress/gutenberg-design

**Comment by mtias** [comment]
Also consider referring to the work on revisions: #50089

**Comment by youknowriad** [comment]
I think I saw a PR related to this recently https://github.com/WordPress/gutenberg/pull/50329 

Is this already fixed (I mean the menu item hidden when there's no style variations)

**Comment by jasmussen** [comment]
> Is this already fixed (I mean the menu item hidden when there's no style variations)

In my flurry to create issues I wasn't able to properly test.

But if there is, we still need the "Styles" item, to at minimum surface a deep link to the global styles panel.

**Comment by richtabor** [comment]
> I think I saw a PR related to this recently https://github.com/WordPress/gutenberg/pull/50329

That's right. In trunk, if the theme does not offer style variations, then the Styles nav item is no longer available, per https://github.com/WordPress/gutenberg/pull/50329:

<img width="546" alt="CleanShot 2023-05-08 at 14 47 14" src="https://user-images.githubusercontent.com/1813435/236907014-5e9836f1-2985-474b-ba71-37a6a0b51afc.png">

I think we should keep the Styles item and have the "Styles" action open the Edit view, with the Global Styles panel open (for now). And follow up with design explorations into adding the variations, revisions, and style book as navigation items within the Styles panel. Related: https://github.com/WordPress/gutenberg/issues/50393

**Comment by richtabor** [comment]
And perhaps consider labeling them "Theme variations", as they're within the Styles panel.

**Comment by youknowriad** [comment]
cc @ntsekouras

**Comment by SaxonF** [comment]
+1 on always showing Styles regardless of whether there are variations. Navigation becomes unpredictable otherwise.

**Comment by jameskoster** [comment]
Re-opening as I've seen it suggested to include a deep link to the Style Book in this panel.

**Comment by ntsekouras** [comment]
>Re-opening as I've seen it suggested to include a deep link to the Style Book in this panel.

There are no mockups for this. @jameskoster do we have any?

**Comment by jameskoster** [comment]
> @jameskoster do we have any?

We're working on it. If you'd prefer to tackle that in a separate issue I suppose it would be fine.

**Comment by ntsekouras** [comment]
> If you'd prefer to tackle that in a separate issue

It doesn't really matter. We can keep track of it here.

**Comment by jameskoster** [comment]
Haha I just saw it's tracked in https://github.com/WordPress/gutenberg/issues/50379 so we can close :D

**Comment by paaljoachim** [comment]
Btw it would be nice to be able to drill down into each style and see what settings these are made up of. It gives a deeper understanding of how each style is created.

If we take this even further then each setting for a style could have an on/off toggle switch so the user can create a custom version of a style by turning off specific settings. By doing so creating another version of the style.

**Comment by jameskoster** [comment]
Re-opening as we missed a detail here – access to style revisions. It can share the same design we've worked on for other panels, positioned at the bottom of the panel, just above the save button. I'll update the OP to include this task.

**Comment by andrewserong** [comment]
Just double-checking, is the revisions item in the screenshot in this issue ready for dev now? I see there's also been some discussion over in https://github.com/WordPress/gutenberg/issues/50924 about de-emphasising style variations, so wasn't sure which would be a good next task to pick up to help close out this issue.

**Comment by jasmussen** [comment]
Yep, the design should be ready to go Andrew, thanks for asking. I've updated the labels.

**Comment by andrewserong** [comment]
I have a PR open to explore adding in the Revisions button over in https://github.com/WordPress/gutenberg/pull/51149
