### ISSUE TITLE
jsdoc dependency rules changed

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/gutenberg#50452]
### Description

jsdoc/newline-after-description was removed by jsdoc but is used here producing an error:

>Definition for rule 'jsdoc/newline-after-description' was not found

See https://github.com/gajus/eslint-plugin-jsdoc/releases/tag/v42.0.0

There is a new default in `jsdoc/tag-lines` which does the same thing, which means removing this rule should be sufficient.

### Step-by-step reproduction instructions

-

### Environment info

This package v14.5.0, jsdoc v42.0.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ksharma20** [comment]
Can I pick this one, @gziolo?
I'm a newcomer and would require a little overview of what must be done!

**Comment by gziolo** [comment]
> Can I pick this one, @gziolo?
> I'm a newcomer and would require a little overview of what must be done!

Sure, that would be great. Thank you for volunteering @ksharma20!

I guess we need to update the code in two places.

We need to change the existing ESLint config for JSDoc and the rule mentioned is listed in this line (there might be more places):

https://github.com/WordPress/gutenberg/blob/8346327bcaeb3b85d9b9116eb3d226fa45a9876b/packages/eslint-plugin/configs/jsdoc.js#L130

We would also need to upgrade to the latest version the package with the JSDoc rules listed here:

https://github.com/WordPress/gutenberg/blob/8346327bcaeb3b85d9b9116eb3d226fa45a9876b/packages/eslint-plugin/package.json#L43

**Comment by ksharma20** [comment]
Great, that's really helpful & appreciated! Thank you. 
Please assign me to this task @gziolo

**Comment by ksharma20** [comment]
Hey @gziolo, should I change `'jsdoc/tag-lines': 'off'` to `'jsdoc/tag-lines': 'error'` to turn on tag-lines as well ??? in below line? 
https://github.com/WordPress/gutenberg/blob/8346327bcaeb3b85d9b9116eb3d226fa45a9876b/packages/eslint-plugin/configs/jsdoc.js#L108

 I have removed the below line. Is it okay?
https://github.com/WordPress/gutenberg/blob/8346327bcaeb3b85d9b9116eb3d226fa45a9876b/packages/eslint-plugin/configs/jsdoc.js#L130

And Upgraded jsdoc to v42.0.0 (reference line below), or show I take it to the latest v44.2.2?
https://github.com/WordPress/gutenberg/blob/8346327bcaeb3b85d9b9116eb3d226fa45a9876b/packages/eslint-plugin/package.json#L43

I'm not sure what else needs to be changed!
Please let me know If anything else is also needed to be done.
Or any resource reference to go through before.

Thank you in advance! 🤗

**Comment by gziolo** [comment]
> BREAKING CHANGE:
> 
> 1. Removes `jsdoc/newline-after-description` rule in favor of `jsdoc/tag-lines` with option `startLines: 0` for "never" and `startLines: 1` for "always". Defaults now to `startLines: 0`
> 2. Removes `dropEndLines: true` from `jsdoc/tag-lines` in favor of option `endLines: 0`
> 3. Drops `jsdoc/tag-lines` rule's `noEndLines: true` in favor of `applyToEndTag: false`

The changelog for the package contains all recommendations. 

> v44.2.2?

Yes, the latest version would be the preferred one.

**Comment by ksharma20** [comment]
Appreciated. Thank you, sir. 🤗
I just had a little hard time understanding changelogs because I have never used jsdoc.

**Comment by ksharma20** [comment]
So, now my final changes are:

1.) Version Upgrade
`"eslint-plugin-jsdoc": "^44.2.3"`

2.) Removing Line
`'jsdoc/newline-after-description': 'error'`

3.) Modifying Line
```js
'jsdoc/tag-lines': [
  'error', 
    {
      startLines: 0,
      endLines: 0,
      applyToEndTag: false,
    }
]
```
Are these the only changes required @gziolo ?

**Comment by gziolo** [comment]
I haven't tested it, but it might be it code-wise. There will be some changes to the lock file after `npm install`, and it would be great to add a changelog entry for the modified package.

**Comment by gziolo** [comment]
I opened https://github.com/WordPress/gutenberg/pull/53629 to bring the work started by @ksharma20 to the finish line. It also will unblock usage with Node 20.
