### ISSUE TITLE
Blocks: Cannot open More Options menu for empty paragraph block

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#5047]
Raised at https://github.com/WordPress/gutenberg/pull/4953#issuecomment-365489657

## Issue Overview

It is not possible to open the More Options dropdown menu for an empty paragraph block.

## Steps to Reproduce

1. Navigate to Posts > Add New
2. Insert a new paragraph block
3. Without writing any text, press More Options ellipsis menu

## Expected Behavior

More options menu appears.

## Current Behavior

Nothing happens.

## Possible Solution

https://github.com/WordPress/gutenberg/pull/4953#issuecomment-365489657

**Comment by youknowriad** [comment]
Ok, so I can't see how to fix this without reverting dbad796 maybe it's fine (cc @mtias) especially if we land #5026 at the same time.

**Comment by aduth** [comment]
Wonder if we can remove attachment between the block settings menu and selected block. Seems to be causing a fair few related issues (also the auto-focusing which occurs).
