### ISSUE TITLE
Navigation block: prompt to add link/select post only when selecting individual menu item

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#50479]
## What problem does this address?

This came up as part of the [FSE Outreach Program's Front Page Fun call for testing](https://make.wordpress.org/test/2023/04/17/fse-program-testing-call-21-front-page-fun/#comment-3031):

>one example is when you’re editing the navigation block and want to add a new item. Suppose you don’t choose content for your item (for any reason). If you click outside the sidebar to exit, do something else, and then click again in any part of the navigation block afterwards — not in the navigation item you were working with — you are presented with a popup to select the content for the previously created navigation item ([GIF](https://dl.dropboxusercontent.com/s/kkeyde37ab9leu2/2023-05-05%2014.57.49.gif)). The previous context is remembered for me, but I was not expecting that. I wasn’t even thinking about that item anymore. It took some time for me to understand what the UI was trying to nudge me to select the content. I think this should either be removed or made more obvious. That popup should only appear if I click specifically on the item I was editing before, not in other areas of the navigation block itself.

Here's a video:

https://github.com/WordPress/gutenberg/assets/26996883/515861c0-8598-4d6f-8f0a-649dcdbad8d7

## What is your proposed solution?

Only prompt someone to add a link or select a block when the individual item is selected rather than when the entire navigation block is selected. Consider adding in more context as well rather than just opening the inserter experience.

**Comment by annezazu** [comment]
@getdave this might be worth considering as part of larger link control work.

**Comment by draganescu** [comment]
I cannot reproduce this on `trunk` anymore:


https://github.com/WordPress/gutenberg/assets/107534/e0d4c9db-452d-49de-a3e7-c37cfd056411

**Comment by getdave** [comment]
This should also never be a problem again due to fix in https://github.com/WordPress/gutenberg/pull/50774 and accompanying e2e test (regression) coverage I added.
