### ISSUE TITLE
Navigation block: converting items to blocks removes navigation block selection

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#50477]
### Description

In trying to replicating an issue with the FSE Outreach Program's Front Page Fun call for testing, I found that after converting links to blocks, the navigation block is unselected.

### Step-by-step reproduction instructions

1. Open Appearance > Site Editor.
2. Add a navigation block with page list block.
3. Convert page list block to blocks.
4. Notice that after doing so the navigation block is unselected and you have to reselect it.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/26996883/98b5f1ab-51d3-4d1e-b2ff-61d33fefe090

### Environment info

- WP 6.2
- GB 15.7
- TT3
- Chrome
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
@jeryj I think you've been looking at similar issues recently. Could you add any context here or propose a solution?

**Comment by draganescu** [comment]
I think this is closed by #52193
