### ISSUE TITLE
Always show Navigation section in Site Editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#50483]
## What problem does this address?

Passing along feedback as part of the [FSE Outreach Program's Front Page Fun call for testing](https://make.wordpress.org/test/2023/04/17/fse-program-testing-call-21-front-page-fun/#comment-3016) (using WP 6.2, GB 15.7): 

>Wow that is confusing! It wasn’t there before, was it, even though there was already a navigation block in the header? Not intuitive to me that it shows in the left sidebar only when modified, but not when not modified.

[And later:](https://make.wordpress.org/test/2023/04/17/fse-program-testing-call-21-front-page-fun/#comment-3024)

>Going to the Editor. For a short moment I see Styles, Templates and Template Parts. Suddenly a half second later I see Navigation at the top. It is distracting seeing 3 areas and then a moment later 4 areas. I have sometimes clicked almost immediately and then I have end up clicking into the wrong area.

https://github.com/WordPress/gutenberg/assets/26996883/6d993fb8-88f5-451c-9e03-c2bbb7aaea83

This relates somewhat to this issue with a delay in importing a menu: https://github.com/WordPress/gutenberg/issues/48045

## What is your proposed solution?

 In this case, similar to [Styles discussion here](https://github.com/WordPress/gutenberg/issues/50429#issuecomment-1538877812) about always having a menu item in place, I think we should do the same for navigation. I'm not sure how this relates to the overall vision for Navigation for this section https://github.com/WordPress/gutenberg/issues/50396

**Comment by paaljoachim** [comment]
Default Navigation without adding any pages could show the default Sample page in the starter primary menu.

**Comment by jordesign** [comment]
Testing this issue in WP 6.3RC1 - I don't see the flash. To my mind - https://github.com/WordPress/gutenberg/pull/50321 being merged means this issue can be closed.
