### ISSUE TITLE
"Turn into" repetition in block actions

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#5049]
## Issue Overview
In the block actions menu there are options to switch block type. When there is more than one transformation option the repetition creates unnecessary visual noise.

## Steps to Reproduce
1. Select block (text blocks are the best example)
2. Open block actions menu (`...` icon)
3. Notice repetition of "Turn into..." string

## Possible Solution
Perhaps when there's more than one transformation option we include a single "Turn into" heading with the options beneath it. IE;

> Turn into Heading
> Turn into List
> Turn into Preformatted
> Turn into Quote
> Turn into Subhead
> Turn into Verse

becomes

> **Turn into**
> Heading
> List
> Preformatted
> Quote
> Subhead
> Verse

## Screenshots
<img src="https://cldup.com/Geg5LJ0mLJ-3000x3000.png" width="350" />
<img src="https://cldup.com/ptra3O9Lqq-3000x3000.png" width="350" />

## Bonus points
"Turn into" is a phrase with multiple interpretations which might cause issues during localisation. If we chose to run with this idea we might use something like "Change block type" for the heading instead.

EDIT: Of course, as soon as I open this issue I notice we have the same menu in the toolbar which already [implements](https://cldup.com/VLdXYIKVXJ-3000x3000.png) this suggestion :)

**Comment by karmatosed** [comment]
I really like this as an idea.  @jameskoster how about we have similar styling to the top iteration of this:

![2018-03-06 at 20 15](https://user-images.githubusercontent.com/253067/37056293-e6efe8b4-217b-11e8-9b07-a496b32b2b1b.png)

**Comment by jasmussen** [comment]
Was about to say the same as Tammie, let's do the same as the toolbar switcher.

However let's also make that transformer consistent with the block more menu style, and the editor more menu. 

<img width="565" alt="screen shot 2018-03-07 at 09 59 12" src="https://user-images.githubusercontent.com/1204802/37082992-5d082d8c-21ee-11e8-8d0b-637bf1e27dd5.png">

<img width="303" alt="screen shot 2018-03-07 at 09 59 16" src="https://user-images.githubusercontent.com/1204802/37082994-5ed9a320-21ee-11e8-89fe-6085124d8283.png">

<img width="555" alt="screen shot 2018-03-07 at 09 59 53" src="https://user-images.githubusercontent.com/1204802/37082995-610f35a6-21ee-11e8-95da-fe6fdd5ee13a.png">

I.e. same colors, same padding, same focus style.
