### ISSUE TITLE
Details Block: Enable by default on Gutenberg plugin without opt-in

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#50526]
The Details block added in #45055 is experimental and cannot be used unless explicitly enabled from the `Experimental settings` menu.:

![details-block](https://github.com/WordPress/gutenberg/assets/54422211/31e42cd5-7d99-4584-8e48-9e4b9384f4ec)

However, the other blocks (Time To Read, Table of Contents) with `__experimental:true` in `block.json` are enabled by default on the Gutenberg plugin.

What about eliminating this opt-in feature and enabling it by default in the Gutenberg plugin so that we can get more user feedback?

cc @carolinan @talldan @richtabor

**Comment by carolinan** [comment]
Was the issue with the spacebar in Firefox solved? I don't think it should be moved out of experimental until it is solved.

**Comment by t-hamano** [comment]
> Was the issue with the spacebar in Firefox solved? I don't think ti should be move out of experimental until it is solved.

This issue was reported as #49679 and I am aware of this issue. However, I think this issue is part of being "experimental".
Of course, it would be ideal if this issue was fixed before being published 😅

**Comment by richtabor** [comment]
I added https://github.com/WordPress/gutenberg/issues/49679 to the [Polish](https://github.com/orgs/WordPress/projects/96) board to get more eyes on it, but I'm fine with moving the block out of Experimental settings.

**Comment by t-hamano** [comment]
I'm trying to fix the Firefox issue in #50540.
