### ISSUE TITLE
[Env package]: Queries regarding env package

### ISSUE THREAD

**Issue by shashwatahalder01** [WordPress/gutenberg#50542]
I have some queries regarding the env package:
1. Is there any way to  start only developing or testing environment instead of both
2. Is there any way to grab the test MySQL port number programmatically or global/env variable as I need to connect directly to the database?
    [Accessing MYSQL DB](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/getting-started-with-code-contribution.md#accessing-the-mysql-database) suggests grabbing the port number manually.
3. Is  wp-env.json listed theme(first) activates by default

**Comment by ramonjd** [comment]
> Is there any way to start only developing or testing environment instead of both

It looks like you can run any Docker container separately.

`wp-env run <container> [command..]`

See: https://github.com/WordPress/gutenberg/blob/trunk/packages/env/README.md#wp-env-run-container-command

> Is there any way to grab the test MySQL port number programmatically or global/env variable as I need to connect directly to the database? [Accessing MYSQL DB](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/getting-started-with-code-contribution.md#accessing-the-mysql-database) suggests grabbing the port number manually.

I think you're right there. Looks like a manual fetch according to the docs.

Is it a feature you'd like to suggest?

Maybe you could parse it from `docker ps` output, e.g., 

```bash
$ docker ps --format "{{.Ports}}\t{{.Image}}" | grep -oE '\->(\d){4,4}\/tcp\smariadb'
->3306/tcp	mariadb
->3306/tcp	mariadb
```

And then use `sed` to extract the port number?

> Is wp-env.json listed theme(first) activates by default

As far as I'm aware the default WordPress theme (currently twentytwentythree) will activate after first run. The themes in `.wp-env.json` are only installed.


Are there any features you'd like to suggest as enhancements to wp-env? If so, it would be great to update the description with actionable items.

Otherwise feel free to close this issue.

**Comment by shashwatahalder01** [comment]
@ramonjd, Thanks for your quick response. 
Also Thanks for the heck for grabbing the port number. I was able to achieve this for test db via:
```
docker ps -f ancestor=mariadb -f name=tests-mysql  --format='{{.Ports}}' | sed -E 's/.*:(.*)->.*/\\1/'

``` 

Would you mind shedding more light on the first issue: 
The [link](https://github.com/WordPress/gutenberg/blob/trunk/packages/env/README.md#wp-env-run-container-command) you provided, explains how I can run commands inside the container when the container is already up. But I was looking for control over which container to up.

wpenv start command up below containers:

```
	await dockerCompose.upMany(
		[ 'wordpress', 'tests-wordpress', 'cli', 'tests-cli' ],
		{
			...dockerComposeConfig,
			commandOptions: shouldConfigureWp
				? [ '--build', '--force-recreate' ]
				: [],
		}
	);
```

I was looking for a soln. where I can control which set of containers to up like for  test only below containers to up 'tests-wordpress',  'tests-cli'

**Comment by ramonjd** [comment]
> But I was looking for control over which container to up.

My guess is that an exception would have to be built in to the docker compose config based on whatever parameters you send via cli (?)

E.g.., `wp run wp-env start --environment=development`

I just pulled that out of my hat, I'm not really sure. cc @noisysocks, who will have a better, more educated opinion

**Comment by noisysocks** [comment]
`wp-env` doesn't support starting only one container, no. This could be added but I'm not sure if it should be. The philosophy of `wp-env` is to be somewhat approachable and meet 80% of needs. When more advanced requirements are needed I think it makes more sense that folks "eject" from `wp-env` and use `docker` / `docker-compose`.

In this case you if you only want to start the test containers you can run:

```
docker-compose -f $(wp-env install-path)/docker-compose.yml tests-wordpress tests-cli
```

**Comment by shashwatahalder01** [comment]
@ramonjd and @noisysocks Thanks both of you for your insight.
