### ISSUE TITLE
Navigation loses margins in overlay menu

### ISSUE THREAD

**Issue by beafialho** [WordPress/gutenberg#50541]
### Description

This seems to happen when the navigation block is contained in a group or column.

### Step-by-step reproduction instructions

1. Create a navigation menu and group it or insert it in a columns block
2. Select Overlay menu > Mobile
3. Notice how it looks bad on the front end

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/65220155/0bad107a-5027-4ca9-afcb-a5ef69143cf2

<img width="557" alt="Captura de ecrã 2023-05-11, às 12 16 50" src="https://github.com/WordPress/gutenberg/assets/65220155/29897639-310d-4f7c-bd12-e605da51f2ba">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
I followed those testing instructions and was unable to replicate.

As a result I'm going to close this out. 

Happy to take another look if it's still possible to reproduce.
