### ISSUE TITLE
Navigation: Menu name is not synced with selection UI.

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#50557]
Here are how my menus are presented in the selection UI:

<img width="280" alt="Screenshot 2023-05-11 at 19 15 58" src="https://github.com/WordPress/gutenberg/assets/846565/5698c3e7-3a25-48aa-aff9-6f34f5ab827e">

In the Advanced panel, my "Header navigation" menu has the following name:

<img width="285" alt="Screenshot 2023-05-11 at 19 20 00" src="https://github.com/WordPress/gutenberg/assets/846565/bf43a65d-0071-48b0-9c62-21e97832dfbc">

Which makes for a funny delete experience:

<img width="433" alt="Screenshot 2023-05-11 at 19 15 00" src="https://github.com/WordPress/gutenberg/assets/846565/4b78f709-e85e-4c68-9307-68720742197b">

It's not clear to me which is the source of truth, but they should be in sync anyway I suppose?

In case it's relevant, this menu was created automatically from the "Navigation menu has been deleted..." error message:

<img width="340" alt="Screenshot 2023-05-11 at 19 21 51" src="https://github.com/WordPress/gutenberg/assets/846565/2496a96e-7313-4671-b98b-1328810526a4">

Updating the name manually seems to fix things.

**Comment by Mamaduka** [comment]
@jameskoster, how can I reproduce this issue?

**Comment by jameskoster** [comment]
@Mamaduka Sorry, I'm not really sure. This happened to one of my menus after an update. Maybe it was a glitch in the Matrix? :)

**Comment by Mamaduka** [comment]
I'm going to close this issue. I can no longer reproduce it.
