### ISSUE TITLE
May I ask when will it be compatible with WordPress 6.2?

### ISSUE THREAD

**Issue by ACGtutusang** [WordPress/gutenberg#50553]
I want to know when this plugin will be compatible with wordpress6.2, this plugin is not compatible with version 6.2, this plugin will not work on my website it's a pity

**Comment by glendaviesnz** [comment]
The Gutenberg plugin is compatible with WP 6.2. Are you able to provide details about the notices/errors you see when trying to enable it on your site, and also details about the plugin version that you are trying to run?

**Comment by Mamaduka** [comment]
I believe it's a matter of updating plugin metadata. #50360 handles that.

**Comment by talldan** [comment]
@ACGtutusang When Gutenberg 15.8 comes out it'll show compatibility with 6.2.

For now you can ignore the warning, the plugin is compatible, just an admin task updating the version wasn't completed.

**Comment by ACGtutusang** [comment]
Thank you, I will try again

**Comment by ACGtutusang** [comment]
@talldan 
Still not working, after the plugin is installed, the editor is still old, Gutenberg does not take effect。
![image](https://github.com/WordPress/gutenberg/assets/119815672/e58d468d-eeed-4c84-a7c4-e967707c5247)
![image](https://github.com/WordPress/gutenberg/assets/119815672/587e26c7-97cd-4c64-8c5e-e89065316b10)
![image](https://github.com/WordPress/gutenberg/assets/119815672/92973387-768f-4016-aef2-7be2b274a731)
Even looking at the demo, it's still the old editor：
![image](https://github.com/WordPress/gutenberg/assets/119815672/931ce2b4-ab97-4132-a305-2d4b9d0096bc)

**Comment by talldan** [comment]
@ACGtutusang You're still on Gutenberg 15.7.1, not 15.8.

It's unusual that the classic editor is loading though, I'm not sure why that would be.

**Comment by ACGtutusang** [comment]
@talldan Just now, I have updated to version 15.8, but there is still no change, the editor is still the classic editor
![image](https://github.com/WordPress/gutenberg/assets/119815672/8c922160-2131-4868-8413-a9c1aa775ddf)

**Comment by Mamaduka** [comment]
Hi, @ACGtutusang

Do you have any other plugins active?

Currently, I can think of only two reasons why the Classic Editor would be displayed instead of Block Editor.

1. The site uses [Classic Editor](https://wordpress.org/plugins/classic-editor/) plugin.
2. The post types have a `show_in_rest` argument set to `false`. See https://developer.wordpress.org/reference/functions/register_post_type/#show_in_rest.
