### ISSUE TITLE
Navigation block, justification stretch throws error

### ISSUE THREAD

**Issue by tkapler** [WordPress/gutenberg#50550]
### Description

If you set Justification to Stretch for Navigation block, it throws warning

Warning: Undefined array key "stretch" in /var/www/vhosts/powerbox.one/httpdocs/wp-content/plugins/gutenberg/build/block-library/blocks/navigation.php on line 677

### Step-by-step reproduction instructions

1. place navigation block
2. Settings / Layout / Justification -> Stretch
with debug = true

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Thanks for reporting this! Yes, it looks like the Navigation block likely needs to check that the key is available [here](https://github.com/WordPress/gutenberg/blob/8816de133f49ebdd91499babf8218811ba1594bb/packages/block-library/src/navigation/index.php#L473) before attempting to access it. Also, it'd be good for `stretch` to be added as one of the layout justification options.

**Comment by Mamaduka** [comment]
Fixed via #50568.
