### ISSUE TITLE
Font families: data from `theme.json` is not properly registered

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#50576]
The mechanism for registering font families client-side depends on every font family being registered at the `theme` level. It should be able to register font families from any origin: `default`, `theme` or `custom` (user), like any other preset does.

### Test with data coming from the `default` origin

- Use the latest Gutenberg and WordPress with the TwentyTwentyThree theme.
- Delete the "DM Sans" and "IBM plex mono" from the `theme.json` of TT3.
- Copy them into the `theme.json` bundled with Gutenberg at `lib/theme.json`.

The expected result was that:

- The data store `core/edit-site` has all font families defined by the different origins
	-  `root.settings.__experimentalFeatures.typography.fontFamilies.default` holds the "DM Sans" and "IBM plex mono".
	- `root.settings.__experimentalFeatures.typography.fontFamilies.theme` holds the rest: "Inter", "System font", "Source Serif pro".
- All fonts are registered properly at the UI level.
	- Go to the global styles sidebar and open the typography panel for one of the top-level elements. For example, "Text".

What happened instead was that:

- Data store
	-  `root.settings.__experimentalFeatures.typography.fontFamilies.default` holds the "DM Sans" and "IBM plex mono". This is correct.
	- `root.settings.__experimentalFeatures.typography.fontFamilies.theme` holded all the fonts, the ones defined by `default` and the ones defined by the `theme`. This is incorrect. It should not have the ones defined by `default`
- All fonts are registered properly at the UI level. The fonts defined via `default` don't show the proper labels ("DM Sans" and "Inter Plex mono") but the slug "dm-sans" and "ibm-plex-mono").

[Gravação de ecrã a partir de 12-05-2023 12:16:38.webm](https://github.com/WordPress/gutenberg/assets/583546/f51d9574-2ca7-4c07-86a3-52ad4707de04)

### Test with data coming from the `custom` origin

- Use the latest Gutenberg and WordPress with the TwentyTwentyThree theme.
- Delete the "System font" from the `theme.json` of TT3.
- Save into the database the following `theme.json` for user data (it defines the system font):

```json
{
	"version": 2,
	"isGlobalStylesUserThemeJSON": true,
	"settings": {
	    "typography": {
			"fontFamilies": [
				{
					"fontFamily": "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,\"Helvetica Neue\",sans-serif",
					"name": "System Font",
					"slug": "system-font"
				}
			]
		}
	}
}
```

The expected result was that:

- The data store `core/edit-site` has all font families defined by the different origins
	-  `root.settings.__experimentalFeatures.typography.fontFamilies.theme` holds all the fonts but "System font".
	- `root.settings.__experimentalFeatures.typography.fontFamilies.custom` holds the "System Font".
- All fonts are registered properly at the UI level.
	- Go to the global styles sidebar and open the typography panel for one of the top-level elements. For example, "Text".

What happened instead was that:

- Only the "System Font" was shown in the font family UI.

[Gravação de ecrã a partir de 12-05-2023 12:31:05.webm](https://github.com/WordPress/gutenberg/assets/583546/91c9a695-595d-4744-a32d-2784626a800b)

### Environment info

I've tested this with Gutenberg `trunk` and latest WordPress `trunk`.

**Comment by oandregal** [comment]
> root.settings.__experimentalFeatures.typography.fontFamilies.theme holded all the fonts, the ones defined by default and the ones defined by the theme. This is incorrect. It should not have the ones defined by default

This is because the `gutenberg_add_registered_fonts_to_theme_json` at https://github.com/WordPress/gutenberg/blob/trunk/lib/class-wp-theme-json-resolver-gutenberg.php#L278 In that step we're adding the font families defined by `default` to the list of font families defined by the `theme`.

I don't know what's the intention of that code or the way forward yet, but thought I'd share what I'm learning as early as possible, to gather thoughts from others.

**Comment by hellofromtonya** [comment]
>Copy them into the theme.json bundled with Gutenberg at lib/theme.json.

I do not foresee WordPress Core bundling local fonts, i.e. providing the local font files within WordPress Core. Rather, this is the job of the theme to define the typography and then extenders via plugins for further customization.

@oandregal Can you provide more context as to why or when local font files would be bundled within WordPress Core?

**Comment by oandregal** [comment]
> Can you provide more context as to why or when local font files would be bundled within WordPress Core?

It's fine that we decide not to. My point is that there are issues in how it works now: data defined at the `default` level is duplicated and is not properly rendered.

We should enforce what's expected. I'd suggest make all origins work the same, as we could change our mind, or people could use a [filter](https://make.wordpress.org/core/2022/10/10/filters-for-theme-json-data/) to add them to the `default` origin.
Alternatively, if we don't want to support that, we should make sure that list is always empty.

**Comment by hellofromtonya** [comment]
>Test with data coming from the custom origin
>Use the latest Gutenberg and WordPress with the TwentyTwentyThree theme.
>Delete the "System font" from the theme.json of TT3.
>Save into the database the following theme.json for user data (it defines the system font):

I'm confused by the testing steps of removing "System font". This font is not registered with the Fonts API. Why? It does not have a `fontFace` defined:

```
				{
					"fontFamily": "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,\"Helvetica Neue\",sans-serif",
					"name": "System Font",
					"slug": "system-font"
				},
```

Therefore, the Fonts API has no `@font-face` to generate for it as no properties or `src` are provided.

But I am curious of the results you had and why these are happening. I'll do some testing to see where this font is stored.

**Comment by oandregal** [comment]
I learned a few more things about the font library goals. This is how we aim it to work https://github.com/WordPress/gutenberg/issues/40363#issuecomment-1549542652

**The takeaway for this issue is that the font library and the theme.json models are at odds. The font library currently passes data to the client using the theme.json data for lack of a better alternative, but it should develop its own data flow.**

---

A longer explanation is this. The "origins" is a key concept of theme.json data, and how any preset works. Take colors, for example:

- the ones defined by core via its theme.json end up being stored under `settings.color.palette.default`.
- the ones defined by the theme vias its theme.json end up being stored under `settings.color.palette.theme`.
- the ones defined by the user via the global styles sidebar end up being stored under `settings.color.palette.custom`.

While we only surface this "origins" to the UI for the color preset type, the underlying data flow/storage is the same for every other preset type.

Compare how font families work now;

- fonts defined by core via its theme.json end up stored both in `settings.typography.fontFamily.default` and `settings.typography.fontFamily.theme` origins, and they aren't properly rendered in the UI.
- fonts defined by the theme via its theme.json end up stored in the `settings.typography.fontFamily.theme` and they work as expected in the UI.
- font defined via the PHP API to be used by classic themes or plugins end up stored in `settings.typography.fontFamily.theme` and they work as expected in the UI.
- fonts defined by the user via the global styles sidebar end up stored in `settings.typography.fontFamily.custom` and make the UI ignore any other origin.

If we expected the theme.json model and the font library to work together, all origins should work, classic themes would have an API to add their fonts to the `theme` origin, and plugins would be able to hook into any for different needs. Instead, we want the font library to behave more like the media library.

**Comment by oandregal** [comment]
I'm closing this as the next steps would be to develop the font library data flow and stop using theme.json data. This needs to be tracked in other places and this will no longer be an issue.
