### ISSUE TITLE
Navigation on Browse Mode: List all navigations

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#50578]
When users have more than one navigation, show a list of them in the sidebar. If they only have one, just show that one directly. They will use the names that navigation CPTs already have, which won't be editable (yet).

<img width="308" alt="Screenshot 2023-05-12 at 12 08 48" src="https://github.com/WordPress/gutenberg/assets/275961/11c3addc-4d19-4b02-8c05-a17db28e4aa9">

**Comment by getdave** [comment]
This is coupled to https://github.com/WordPress/gutenberg/issues/50579 and will likely be tackled in the same PR.
