### ISSUE TITLE
Navigation on Browse Mode: Make navigations in the list selectable.

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#50579]
## What problem does this address?
Following on from https://github.com/WordPress/gutenberg/issues/50578, each of the navigations in the list should be selectable.

When users select a navigation from the list, update the navigation list view in the global sidebar to show the selected navigation, and show only that navigation menu in the preview. Also update the URL so that each navigation has its own direct URL and users can navigate the UI with URL history. This is unnecessary in the case where users have only one navigation.

<img width="1090" alt="Screenshot 2023-05-17 at 15 29 26" src="https://github.com/WordPress/gutenberg/assets/275961/050794f8-6b10-4b22-afc3-56c4d5939638">

**Comment by draganescu** [comment]
Now that this sidebar is a drill down sidebar can we avoid horizontal scroll bars caused by expanding deeply nested trees by navigating navigation menus using drill down as well @jasmussen ?

**Comment by jasmussen** [comment]
> Now that this sidebar is a drill down sidebar can we avoid horizontal scroll bars caused by expanding deeply nested trees by navigating navigation menus using drill down as well @jasmussen ?

As a hub for both light-weight editing and content access, the drilldowns are a way to pick an individualpage to see just that, then edit or configure it if you like. 

For just a simple menu of pages, I like to think that we'd avoid deep nesting. As [discussed](https://github.com/WordPress/gutenberg/issues/50396#issuecomment-1538327864), only simple menus should be editable right there on the left. Any menu that is "complex" (a heuristic we can work out together) you only see the name of the menu, but you edit the menu in the fullscreen editor. We can simply decide that menus with dropdowns are "complex". What do you think?

**Comment by draganescu** [comment]
> We can simply decide that menus with dropdowns are "complex". What do you think?

We can definitely try this. It depends on how well we manage to achieve the edit in isolation thing. If that turns our great, yes this could be a way. But I suspect people will want to add submenus in an initially simple menu. If I have

```
Home | Services | Contact

```

and then I want pages for each service and a service is made of sub items, I may want to do it right there:
```
Home | Services | Contact
           | Web design 
           | SEO
           | Fiddling with copy
           | Building megamenus
```

if we decide "menus with submenus are complex", then if the user has a simple menu open in the sidebar and they use the Plus to add, should they also be allowed to add nested items directly or do we do that in detail view alone?

**Comment by jasmussen** [comment]
If editing on the left works well enough for 1 level submenus, seems fine.

**Comment by getdave** [comment]
This is ✅
