### ISSUE TITLE
Navigation on Browse Mode: Add ellipsis menu

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#50583]
When users have a navigation selected (or if they have only one), add an an ellipsis menu next to the "Navigation" title in the Navigation panel, which offers options to delete, duplicate and rename each navigation.

<img width="868" alt="237962967-db0c9a50-d620-44d4-9ed2-729bc872bb15" src="https://github.com/WordPress/gutenberg/assets/275961/cab2ea4c-2fde-4b6e-8d06-5d3c274dcd61">

**Comment by getdave** [comment]
@MaggieCabrera Bear in mind we don't have a UX design for the "Rename" flow. You might like to chase that.

**Comment by MaggieCabrera** [comment]
Oh, good point, I thought we had something somewhere! @WordPress/gutenberg-design for help with this then :D I can start figuring out the functional parts of it while we get UX anyway

**Comment by jasmussen** [comment]
How's this?

<img width="3432" alt="Context menu" src="https://github.com/WordPress/gutenberg/assets/1204802/c33f6f1d-3f35-43e2-9c71-106a27f53a81">

**Comment by MaggieCabrera** [comment]
@jasmussen is this dropdown opening on the + icon or the pencil icon?

**Comment by jasmussen** [comment]
Ellipsis. The pencil icon should edit the menu in edit view, the plus should open the [add new page](https://github.com/WordPress/gutenberg/issues/48456) flow.

**Comment by annezazu** [comment]
This could perhaps close out this prior issue around surfacing renaming more: https://github.com/WordPress/gutenberg/issues/46638
