### ISSUE TITLE
Display home / loop icon on the relevant page details view

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#50582]
In the Pages panel, the homepage and posts page are indicated via icons so that you can quickly find / edit them:

<img width="375" alt="Screenshot 2023-06-07 at 18 46 24" src="https://github.com/WordPress/gutenberg/assets/846565/6e611a58-9f0a-437f-a7cf-f02ef1d5341d">

It would be good to find a way to carry this through to the page details panel too. Appending the same icon seems like a reasonable place to start:

<img width="865" alt="Screenshot 2023-06-07 at 18 49 55" src="https://github.com/WordPress/gutenberg/assets/846565/d18e36d7-ca85-4b81-bd02-0915e9db115a">

---

Issue updated June 7.

<details><summary>Initial version</summary>

<img width="359" alt="Screenshot 2023-05-05 at 16 04 00" src="https://user-images.githubusercontent.com/846565/236495676-fb3ceba5-03be-4931-8ae5-c25396c048a8.png">

</details>

**Comment by jameskoster** [comment]
One thing to be cautious about is making the icon look like a button given it's proximity to the Edit button. In the future it might serve as a shortcut to homepage settings, but until then we could try different placement / color. Or both:

<img width="380" alt="Screenshot 2023-05-12 at 13 00 04" src="https://github.com/WordPress/gutenberg/assets/846565/1deb3edd-3b63-4ff3-82de-77967d93ddda">

I'm not sure we really need the tooltip but it's an option to consider.

We can apply the same format on the Pages list too:

<img width="380" alt="Screenshot 2023-05-12 at 13 02 34" src="https://github.com/WordPress/gutenberg/assets/846565/aced5316-f33a-4d44-945e-56a282f9ec56">

> if the home page is the Blog

A small note on this point, when the homepage is the blog, there is no associated page. There's just the Home / Index template. We should still show the icon on the relevant template:

<img width="380" alt="Screenshot 2023-05-12 at 13 05 14" src="https://github.com/WordPress/gutenberg/assets/846565/65197d11-8734-4b6c-a499-dcda6e2ea614">


But it could also be good to include a proxy for that template in the Pages list too – though that's one to tackle separately.

**Comment by jasmussen** [comment]
Nice work, Jay, that feels close enough that we can get started.

Just to try another thing, reintroducing icons in the pages lists that would help too:

<img width="1316" alt="Site Structure, Page" src="https://github.com/WordPress/gutenberg/assets/1204802/75ee96a3-074d-44b7-9bd4-b3cfbf8b83a1">

The above also puts the home icon left of the title, and pretty close to it, and white. I realize we have lots of icons here, but there's just something about keeping it white that appeals to me. Not a strong opinion though. [Figma](https://www.figma.com/file/ERw9rIxFxJP19g4eJVfN15/6.3-issues-needing-design?type=design&node-id=449%3A41702&t=Go6gSOI1t2vFpIWS-1).

👆 The metrics and colors are off in this sketch, though, so take it mainly as placement notes. What do you think?

**Comment by jameskoster** [comment]
Agreed, the icon work in the Pages panel is underway in https://github.com/WordPress/gutenberg/pull/50630 🚀

**Comment by jasmussen** [comment]
I tentatively went ahead and updated this one. It's such as small thing.

**Comment by jameskoster** [comment]
I think the changes are already included in the [PR](https://github.com/WordPress/gutenberg/pull/50630) 🚀

**Comment by jameskoster** [comment]
Updated this issue given the Pages panel now indicates the home / posts page.
