### ISSUE TITLE
Escape key does not return focus from the block toolbar to the block any longer

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#50594]
### Description

One of the fundamental keyboard interaction affordances the Editor used to provide is that pressing the Escape key on the block toolbar moves focus back to the block content.

This doesn't seem to work any longer. ~I guess since the introduction of the iframe for the editor canvas.~ (not sure it's because of the iframe)

This is a serious regression and breaks one of the most established, expected, keyboard interaction patterns in the Editor.

### Step-by-step reproduction instructions

In the animated GIF below:

- Edit a post, enter a title and add a couple paragraphs.
- Select some text in the first paragraph.
- Press Shift+Tab.
- The block toolbar appears.
- Initial focus is on the Block switcher button.
- Press Enter: the Block switcher menu opens.
- Press the Escape key.
- The Block switcher menu closes. So far, so good.
- Press the Escape key again.
- Expected: The block toolbar to disappear and focus to be moved back to the block content.
- Actual: The block toolbar disappears but focus is not moved back to the block content. Not sure where focus lands, probably a full focus loss occurs.
- Press the Down arrow key.
- Focus goes to the Post title.
- Expected: focus to go to the second paragraph.
- Reopen the block toolbar and close it again with the Escape key.
- Press Tab.
- Focus goes to the Post title.
- Expected; focus to go to the settings sidebar.

![toolbar focus](https://github.com/WordPress/gutenberg/assets/1682452/0de3d2c6-08a2-4342-ac32-1fb539563464)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Is this the same issue as #45767? I was investigating the latter last week, so the issue seemed familiar.

**Comment by afercia** [comment]
Same issue. I forgot I already created that one 🤦
