### ISSUE TITLE
Add justified text alignment option to text alignment toolbar

### ISSUE THREAD

**Issue by theking2** [WordPress/gutenberg#50615]
## What problem does this address?

Currently left, center and right adjusted is offered for paragraphs and other text related blocks. Justify is missing.
## What is your proposed solution?

Beside left, center and right alignment offer justify alignment

**Comment by hanneslsm** [comment]
This is a long discussed issue and with the new global styles there might be the possibility this gets reintroduced. See
- https://github.com/WordPress/gutenberg/issues/8450
- https://github.com/WordPress/gutenberg/issues/48202

**Comment by Thelmachido** [comment]
Since this is currently being worked on someplace else, I will close this issue as a duplicate
