### ISSUE TITLE
Browse Styles: Selection jumps to the top group

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#50613]
### Description

When clicking on "Browse style" the top group is getting selecting, instead of opening the Browse styles panel

### Step-by-step reproduction instructions

1. Select a block which sits in a group block
2. Navigate to the first layer of the style panel
3. click on "Browse styles"

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/17861443/7d26f6d7-4f1b-4314-acae-c66979f9d94a

### Environment info

- WP 6.2
- GB 15.7.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
We were able to confirm this in the Weekly Editor Bug Scrub. The video below walks through the issues with additional information. 

https://github.com/WordPress/gutenberg/assets/4832319/de2c734a-1723-4f8d-b37e-a51d1982b1d1
