### ISSUE TITLE
Removing Gutenberg Breaks Media Files

### ISSUE THREAD

**Issue by jlhalsted** [WordPress/gutenberg#5062]
I took some time to play with Gutenberg today. And I have to beg Wordpress not to make it part of the core program. 

After trying to make it work for my website for a couple hours I finally deactivated it.

Which caused me to receive an error when I tried to upload anything to my media library.

Then I deleted Gutenberg completely.

And now my images are gone though the media files and all the information in them, remain.

Has anyone else had this experience or can advise on how to repair?

Thank you.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
AFAIK Gutenberg doesn't do anything special about the media files when you enable/disable/upload. 

I tried and failed to reproduce. Could you provide precise steps to achieve this.

**Comment by jlhalsted** [comment]
I didn't think it did, either. 

Precise steps:
installed Gutenberg.
Worked with it for a couple hours but could not get it to work well with images and my site layout.
Deactivated Gutenberg.
Tried to load an image.
Received error message: Failed to write to drive.
Removed Gutenburg.
No images show in media library or on website. All info is there- descriptions, at tags, etc. Just no images.

Next steps: deactivating all plug ins to see if there was a conflict when I removed Gutenberg.

**Comment by caraya** [comment]
@jlhalsted  I would also try clearing the browser's cache to make sure it's not a browser issue.

**Comment by youknowriad** [comment]
@jlhalsted I don't think it has anything to do with Gutenberg. It's probably a permissions issue somewhere in your server. The issue may have been exposed by the fact that you installed, added/removed files to a folder on your WordPress installation. 

I'm closing as there's nothing we can do here.
