### ISSUE TITLE
InspectorControls property group "styles" not working

### ISSUE THREAD

**Issue by Maufeat** [WordPress/gutenberg#50631]
### Description

I want to add a custom Inspector Element to the styles-Tab in the Editor. But the problem I am having is, that the property group seems to not be working in the "styles" group, but works if I set it to "settings" and it shows in the settings-Tab.

### Step-by-step reproduction instructions

Create an InspectorControl and add the group "styles" and see if it is showing in the styles-Tab, then set it to "settings" and it should show up in settings.

### Screenshots, screen recording, code snippet

Here a code snippet:

Not working
```
return el(InspectorControls, { group: "styles" }, [
      el(PanelBody, { title: "Test Style" }, null)
]);
```

Working:

```
return el(InspectorControls, { group: "settings" }, [
      el(PanelBody, { title: "Test Style" }, null)
]);
```

### Please confirm that you have searched existing issues in the repo.

Yes, No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@Maufeat I couldn't reproduce any issues. What happens when you try it? If you can share some screenshots, that would be great.

**Comment by Maufeat** [comment]
It works, it was my fault. I've inserted the InspectorControls Element into the wrong place. Sorry for the inconvenience.
