### ISSUE TITLE
Slash inserter: Add API to allow inserter items to be prioritised 

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#50635]
As a followup to https://github.com/WordPress/gutenberg/pull/50510 we should add the same functionality to the slash inserter, so that we have the same behaviour available in both places.

**Comment by ntsekouras** [comment]
I can open a quick PR for that.

**Comment by getdave** [comment]
@ntsekouras That's great. I was thinking about tackling it today but more than happy for you to take that one 🙇‍♂️
