### ISSUE TITLE
Edit only fields within Reusable block, keep styles

### ISSUE THREAD

**Issue by merijnponzo** [WordPress/gutenberg#50661]
Hello,

With my first Full Site Editing projects, me and my clients are having troubles to keep up pages style consistent.

I hoped that the Resuable block was the solution by editing it styles fromout the Resuable block within the reusable block admin, and add content within the pages the block is used.

But as long i don't detach the blok/ or turn it into it's own entity, it's not possible to get unique content per block, but keep up the styles.

Having a reusable block with individual content is in fact dynamic, or would require generated styles fromout the original block.
This would be very challenging development wise.

However, keeping 12 pages style consistant with the same colors, margins, paddings is very challenging as well, with my first projects I am truly considering going back to custom fields with consistent classes.

I'm sure this is widely discussed with designing the Gutenberg architecture, or am i missing some functionality here?

**Comment by merijnponzo** [comment]
i think something built in like this:
https://wpstackable.com/blog/copy-and-paste-block-styles/

Would be an outcome. Then you still have to apply your adjusted styles but it would definitely goes faster.

**Comment by carlomanf** [comment]
It's currently being discussed at: #48458, #50456, #50060

**Comment by priethor** [comment]
Thanks for providing your feedback, @merijnponzo! As @carlomanf says, this is already being considered in the abovementioned issues. If you don't mind, let's close this one in favor of the existing ones 🙏
