### ISSUE TITLE
Change hover over current selected formatting toolbar  "change block type" 

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#5066]
Today hovering over the current selected toolbar it looks like this:

![hover selected formatting option](https://user-images.githubusercontent.com/5323259/36242357-799b2f4a-11e9-11e8-8c32-91badf26d263.png)

To make it super clear which option is currently selected it could look like this:

![hover-selected-formatting-option-new](https://user-images.githubusercontent.com/5323259/36242363-8907649e-11e9-11e8-93f3-8c03b7e49bda.jpg)

**Comment by karmatosed** [comment]
I really am not sure we should change this each time, it seems like something because it's an instruction should remain consistent. I am going to close this, but if we get feedback and more input from others we can always reopen.
