### ISSUE TITLE
Unable to nest lists in a blockquote

### ISSUE THREAD

**Issue by caraya** [WordPress/gutenberg#5067]
## Issue Overview

Nested HTML does not work inside blockquotes

## Steps to Reproduce (for bugs)

1. Create a quote block and switch to 'Quote Style 2' in the toolbar
2. Paste text containing a nested `ul` element
3. Switch to the code editor and fix the code so that it is well-formatted HTML
4. Switch back to the visual editor

I'm using Chrome 64 with a clean build of Gutenberg from today.

## Expected Behavior

I would expect the block to display the nested list

## Current Behavior

When I try to switch back to visual editing the block I'm presented with a dialogue that indicates the block was changed externally. If I choose to overwrite, then the bulleted list disappears and the rest of the content displays normally. 

I can edit it as a classic block or HTML but that's not the behavior I want. 

## Possible Solution

Allow for nested content or provide an error message rather than allow partial content to be displayed visually

## Screenshots / Video

<img width="737" alt="01-well-formed-html" src="https://user-images.githubusercontent.com/409841/36243880-a261a712-11d8-11e8-8b93-a7b535094b33.png">
<img width="1646" alt="02-overwrite-dialogue" src="https://user-images.githubusercontent.com/409841/36243886-a9448d4c-11d8-11e8-8ea5-00e21f80e499.png">
<img width="741" alt="03-resulting-content" src="https://user-images.githubusercontent.com/409841/36243892-ae0aab68-11d8-11e8-9b63-27ff001e6f13.png">

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mtias** [comment]
The Quote block doesn't allow content that is not paragraphs at the moment. The plan is to add a nested group inside the quote to support additional blocks.

**Comment by caraya** [comment]
@mtias Is there a timeline for adding the nested group to quotes

**Comment by bph** [comment]
@mtias  [I posted on the slack channel with a request for ideas](https://wordpress.slack.com/archives/C02QB2JS7/p1520626194000167) to approach a content conversion problem as well. Mine actually could be solved if I could move a group of blocks into a column of a nested block. :-)

**Comment by rfischmann** [comment]
Almost a year and a half and Gutenberg still doesn't support this. 😔

**Comment by chriscoyier** [comment]
I'll toss my hand up here and say this would be very useful. I'm trying to quote a list from another blog post right now and it seems like it's just not happening and I'll have to fake the list markup with text.

**Comment by mbert** [comment]
OK, so I understand this correctly: 

After a sometimes rather painful learning process of learning how to use this rather controversial new editor and - in my case just about 30 wasted minutes for trying to solve it myself and then searching for solutions - it turns out that a feature that is supported by pretty much every other CMS (and, by the way, also by the old WP editor) - and that has lots of use cases, e.g. when citing complex pieces of text from third-party sources, is simply not supported? 

And this has been known for years? And never fixed? 

I am a bit surprised, to say the least. 

(in my case it's worse, as a WP.com user I am not even given the choice anymore to keep on using the old editor)

**Comment by caraya** [comment]
@mbert I'd suggest you contact support and see if they can help. you regarding the old editor.

**Comment by ajtruckle** [comment]
Just noticed this is lacking. Sad. I was hoping to quote a help article.

**Comment by mtias** [comment]
You can follow the progress here: https://github.com/WordPress/gutenberg/pull/25892
