### ISSUE TITLE
add a default: true for theme.json settings

### ISSUE THREAD

**Issue by theking2** [WordPress/gutenberg#50679]
## What problem does this address?
in the style editor Defaults are in font, color, and size. Yet there is no way define what the default is.

## What is your proposed solution?
for each of the items in the `theme.json` scheme add an option `default:true` to specify what the designer declared "default". For instance in pallete
```
"settings": {
  "color": {
    "pallete": [
      {
        "color": "#330000",
        "name": "Text",
        "slug": "text"
      },
    ],
    default: "text"
  }
}
```
where default points to the slug

     ]

**Comment by carolinan** [comment]
Hi!
I did not fully understand what you meant. Can you describe the problem that you are trying to solve?

WordPress provides a default color palette. The palette can be disabled in theme.json.
The name of this palette in the editor is Default.

The **developer** can only provide one palette for the site and custom palettes on a per block basis. (theme.json)
The **user** can also only create one palette for the site and custom palettes on a per block basis. (site editor)

**Comment by carolinan** [comment]
In theme.json, you set the default text color for the whole website directly under styles. 

And in the Site Editor you set the default text color for the whole website in the **first panel** of the styles sidebar > colors > text.

**Comment by theking2** [comment]
Seems like a did not read documentation problem. (In defence: the documentation is not entirely clear
