### ISSUE TITLE
[Env Package]: Access wp-env db port via env variable

### ISSUE THREAD

**Issue by shashwatahalder01** [WordPress/gutenberg#50677]
Currently, connecting directly to the wp-env database requires grabbing the port number manually. 
* [Accessing MYSQL DB](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/getting-started-with-code-contribution.md#accessing-the-mysql-database)
* [Issue Discussion](https://github.com/WordPress/gutenberg/issues/50542)

It would be really nice to access the port number via environment variables like, we have for sites (WP_ENV_PORT and WP_ENV_TESTS_PORT) 

[workaround soln. ](https://github.com/WordPress/gutenberg/issues/50542):
```
docker ps -f ancestor=mariadb -f name=tests-mysql  --format='{{.Ports}}' | sed -E 's/.*:(.*)->.*/\\1/'
```

**Comment by BrianHenryIE** [comment]
I have this working in a branch. Still some work to do before it's ready for a PR:

https://github.com/WordPress/gutenberg/compare/trunk...BrianHenryIE:gutenberg:wp-env-allow-setting-mysql-port-50677?

**Comment by alanef** [comment]
Not just ENV but in .wp-env.json would be good  as right now it means to configuring ( the IDE ) in each restart

**Comment by BrianHenryIE** [comment]
I've been updating my `.env.testing` file's `TEST_DB_PORT=` using a `lifcycleScripts`/`afterStart` containing:

```
TEST_DB_PORT=$(docker ps -f ancestor=mariadb:lts -f name=tests-mysql --format='{{.Ports}}' | sed -E 's/.*:(.*)->.*/\1/')
find . -depth \( -name '.env.testing' \) -exec sed -i '' "s/TEST_DB_PORT=\".*\"/TEST_DB_PORT=\"$TEST_DB_PORT\"/g" {} +
```

Username/password: `root`/`password`.

PR #61057 is ready for review so hopefully this syntax will be valid soon:

```
{
  "env": {
    "development": {
      "mysqlPort": 13306
    },
    "tests": {
      "mysqlPort": 13307
    }
  }
}
```
