### ISSUE TITLE
Improve scroll behaviour of site editor sidebar

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#50688]
## What problem does this address?
The scrolling behaviour of the site editor sidebar currently takes up a lot of space reducing height for actual content. The box shadow can also be seen when adding metadata to the sidebar title. 

## What is your proposed solution?
![image](https://github.com/WordPress/gutenberg/assets/1072756/65d13cd5-dacc-424c-9602-086cddad869b)

Stick title to the top on scroll and reduce font size. Only show shadow when stuck at top.

**Comment by jasmussen** [comment]
Sounds good to me!

Not sure if we need to reduce the font size, we can see how that feels in the branch. I would also suggest that instead of a drop shadow, perhaps we could use background-blur on the gray color of the heading? Both can work, and I suspect a PR will reveal it. Nice one.

**Comment by youknowriad** [comment]
There has been a lot of design changes here, that said scrolling is still possible in the sidebar. What's the remaining actionable items here.

**Comment by jasmussen** [comment]
The title persists when scrolled:

![Image](https://github.com/user-attachments/assets/fa0edd71-4bee-4f89-af78-7c28c95c6256)

Whether we need a border or shadow, unclear, but let's close for now, and can reopen if this was in error.
