### ISSUE TITLE
The block "xxx/xxx" must have a title

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#50707]
### Description

I'm using the following `block.json` file to register a custom block type:

```
{
	"$schema": "https://schemas.wp.org/trunk/block.json",
	"apiVersion": 2,
	"name": "my/really-simple-slider",
	"title": "Really Simple Slider",
	"description": "Display a slider.",
	"textdomain": "really-simple-slider",
	"category": "common",
	"attributes": {
		"images": {
			"type": "array",
			"default": []
		},
		"caption": {
			"type": "string",
			"source": "html",
			"selector": "figcaption"
		},
		"fx": {
			"type": "string",
			"default": "fade",
			"enum": [
				"fade",
				"slide"
			]
		},
		"caption_position": {
			"type": "string",
			"default": "before",
			"enum": [
				"before",
				"after",
				"hidden"
			]
		},
		"navigation_position": {
			"type": "string",
			"default": "before",
			"enum": [
				"before",
				"after",
				"hidden"
			]
		},
		"auto": {
			"type": "boolean",
			"default": false
		}
	},
	"supports": {
		"spacing": {
			"margin": true,
			"padding": true
		}
	},
	"script": "file:./index.js",
	"viewScript": "file:./view.js",
	"style": [
		"file:./style-index.css",
		"file:./view.css"
	],
	"editorStyle": "file:./index.css"
}
```

Using this file, the block works but I'm getting the following warning ONLY IN FRONTEND:

`The block "my/really-simple-slider" must have a title. [blocks.js:9831:10]`

If I replace `"script": "file:./index.js"` with `"editorScript": "file:./index.js"` in the `block.json` file, the warning disappears.
This warning also disappears if I specify the `title` property in the `registerBlockType` function.

Is this an expected behavior? Or is it a bug?

### Step-by-step reproduction instructions

1. Create a custom block with the provided `block.json` file
2. Add this custom block to a page
3. Load the page in the frontend 
4. Check the browser console

### Environment info

- WordPress 6.2.1 (no Gutenberg plugin)
- Windows 10
- Firefox 113

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by skorasaurus** [comment]
I'm able to reproduce this behavior in a test block (Gutenberg 16.1; WP 6.2; 
("@wordpress/scripts": "^26.8.0") ) 

The value of [script](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#script) in block.json is enqueued in both the editor AND on the front-end, so you would think 
that the block registration (which is in index.js) would be properly passed along on the front end. 

And editorScript which only is enqueued in the editor 

All this, yet this error of the block title missing only occurs on the front-end when using the script property.

**Comment by gziolo** [comment]
@mrleemon, was it intentional to register the block also on the frontend? If you need it only in the editor then you should use `editorScript` as pointed out by @skorasaurus. In case, you have some custom JavaScript logic that should run both on the frontend of the site and in the admin/editor then you can move it to the file that is going to be listed as `script` in `block.json`. By default, the metadata for registered blocks on the server is only exposed in the editor (in admin), so for site visitors it would need to be manually handled.

I'm closing the issue as I don't see any actionable items. However, feel free to ask follow-up questions if necessary.
