### ISSUE TITLE
Consider changing the order of nested items added by drag n drop in the list view, so that dragged items are added to the bottom of created components.

### ISSUE THREAD

**Issue by Ren2049** [WordPress/gutenberg#50716]
## What problem does this address?

I'm a week into using the site editor every day for multiple hours, and having to reorder list view items I've dragged into e.g. a group block is super annoying. As a designer I'm working from the top down, and In 99% of the time want to add to the bottom of a component. 

## What is your proposed solution?

Change the order in which dragged in items appear in the list view when added to an existing component.

**Comment by talldan** [comment]
@Ren2049 Could you share some more details about what steps you're following? It's hard to understand exactly what you mean when you say you have to reorder. You should be able to drag between the items in List View.

There have been some improvements around this feature in the Gutenberg plugin, do you have that active at the moment, or are you using WordPress without it?

edit: I saw you also made a few other issues, I think they suffer from the same problem, the specifics aren't completely clear. Including screenshots and videos might be useful.

**Comment by Ren2049** [comment]
@talldan I was using the TT3 theme without the GB plugin. Sorry should have mentioned that I was referring to semi-collpased list items, like group blocks or cover blocks that wrap other text elements. I know that I can open all the "layers" and wiggle items into the exact spot waiting for the blue indicator line to be in the right spot, but it's a pain in editors with layers (Gutenberg isn't an exception). 

It's a lot faster to drop the element on the wrapping container, and when I do that the item is added as the first item in the list, much better would be if it would default to being the last item. Moving the item manually down by clicking the "move" arrow a couple of times is still faster than wiggling it into place though. 

GHs upload tool rejects my screenshots currently, sorry.

**Comment by andrewserong** [comment]
Thanks for opening this issue and for the additional context! Yes, it'd be good when dropping onto collapsed group blocks for the nested block to be set as the last child instead of the first child of the group block. That appears to still be an issue. Here's a screengrab:

![2023-05-25 10 38 49](https://github.com/WordPress/gutenberg/assets/14988353/1541b1c1-78d1-4cf3-b626-f42383a15083)

I'll link to this issue from the list view drag and drop tracking issue (https://github.com/WordPress/gutenberg/issues/49563)
