### ISSUE TITLE
Webp Site Logo isn't aligned properly when viewed in the browser (inside the editor it's ok).

### ISSUE THREAD

**Issue by Ren2049** [WordPress/gutenberg#50720]
### Description

Bottom padding is added out of nowhere when viewed in the browser:

![Screen Shot 2023-05-17 at 20 55 22](https://github.com/WordPress/gutenberg/assets/133038357/fb90a3a0-7b17-401c-8720-980bbfff7ce7)

In the Editor it looks ok:

![Screen Shot 2023-05-17 at 20 55 58](https://github.com/WordPress/gutenberg/assets/133038357/178369ff-8fbd-4702-8b29-cbbba9af4670)

Its a square 256px webp icon shrunk down with the handles inside the editor. The wordmark next to it is a separate webp image. I've separated the logo to use the site icon functionality.

### Step-by-step reproduction instructions

1. Upload a 256px webp logo/icon
2. Add a site logo block inside a navigation header.
3. Shring the icon using the handles to around 32px.
4. Compare in editor and in browser.

### Environment info

6.2, TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hi @Ren2049  - looking at your issue it appears the padding/space that appears below your logo is due to one (or more) other items within that row being taller.

So the overall row has a height set by some of the blocks/content - and because your Site Logo is set to top align, the remaining space appears at the bottom.

If you (in that example) make the logo bigger to 64px (for example) do you still have the same space/padding at the bottom?
If you had a URL where we can check this happening - that could also help.

**Comment by Ren2049** [comment]
@jordesign the local project I've used for this doesn't exist anymore. I didn't use top-align but middle align though, you can see on the sond image that it uses middle-align and looks right in the editor. I'll try it again tomorrow and record a short video if the problem still exists.

**Comment by Ren2049** [comment]
@jordesign I tried to recreate the issue but I've encountered a new problem in 6.3 beta 3 where the dimensions set in the editor aren't picked up on the frontend and it's using the set media Resolution size instead. here's a video:


https://github.com/WordPress/gutenberg/assets/133038357/0962ab58-49f4-4e48-a83d-8116e0bce205

**Comment by Ren2049** [comment]
@jordesign I've opened a new issue for this: https://github.com/WordPress/gutenberg/issues/52499#issue-1798491754

**Comment by Ren2049** [comment]
The content width glitch was caused by a full-width setting on a row child element. The logo alignment issue disappeared after updating to 6.3 beta 4. But it's still present on a blank theme created with the create block theme plugin:  https://github.com/WordPress/create-block-theme/issues/421#issue-1806486362

**Comment by jordesign** [comment]
Thanks @Ren2049 - I'm going to close this issue here in favour of the one in the plugin specific repo.
https://github.com/WordPress/create-block-theme/issues/421#issue-1806486362
