### ISSUE TITLE
Custom CSS and Navigation Arrows in The Site Editor.

### ISSUE THREAD

**Issue by rebeenmajeed** [WordPress/gutenberg#50721]
Hi,

I apologize if this is the wrong place to report this topic. I'd like to share two things in the Site Editor that I believe need to be fixed. These two things only appear when you use the site editor in RTL language, such as when I use WordPress in Kurdish Sorani.

To begin, the navigation arrows for opening the template, template parts, patterns, and gallery are the same as when using WordPress in LTR languages. In RTL languages, the navigation arrow should point to the left.

![Screenshot from 2023-05-17 22-18-52](https://github.com/WordPress/gutenberg/assets/105249529/dd52e3f7-9b4e-4b6d-bb7d-d7975deb17dd)
![Screenshot from 2023-05-17 22-19-13](https://github.com/WordPress/gutenberg/assets/105249529/e0738aa8-9c3f-482e-bf58-110e78e8ae69)

Second, it's extremely difficult to write code in a place when the writing is RTL. It would be ideal if you could write CSS code in LTR.

![Screenshot from 2023-05-17 22-19-55](https://github.com/WordPress/gutenberg/assets/105249529/d76258cd-0314-42d4-b471-d6d06f21f4c0)

**Comment by glendaviesnz** [comment]
I have added a [PR for the CSS input direction](https://github.com/WordPress/gutenberg/pull/50768).

**Comment by rebeenmajeed** [comment]
Hi,

I've been testing WordPress 6.3 Beta 3 since yesterday, and both issues have been resolved; thank you very much for your excellent work.

**Comment by glendaviesnz** [comment]
Thanks for retesting @rebeenmajeed. I will go ahead and close this issue then, but go ahead and reopen it if any further issues.
