### ISSUE TITLE
Impossible to add new link in navigation block when used twice in same template

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#50733]
### Description

When two navigation blocks exist in the same template, in different template parts, because of syncing block data in template parts, the last inserted block client id is unexpected. This causes the off canvas menu building to not function - it breaks the ability to add more page links after the 1st page link was added.

Investigation shows that:

- the bug exist in WordPress 6.2 but it was not caugut/reported because having the same menu ferenced in two template parts in the same template is probably a rare occurence
- relying on last inserted client id is not a strong foundation, we need to always reference the block added by the appender actioned by the user

### Step-by-step reproduction instructions

1. Checkout a theme that has a template with a footer and header template (e.e. TT3)
2. In both the header and the footer insert a navigation block
3. In both navigation blocks choose the same navigation
4. Save
5. In the header select the navigation block
6. In the block's inspector click the [+] appender
7. Select page link
8. Notice the bug - the link control does not show a list of recent pages but a prefilled edit form for the 1st item in the navigation block

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/107534/28445271-df5b-47d7-ba69-060a81c83e9f

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
Related https://github.com/WordPress/gutenberg/issues/50601

**Comment by getdave** [comment]
@draganescu @scruffian With the fix in `trunk` are you able to replicate this any more?

**Comment by getdave** [comment]
Actually Alex tested in https://github.com/WordPress/gutenberg/pull/50774#pullrequestreview-1435188755 and it was 👍  so I'll close this one.
