### ISSUE TITLE
getEditedPostAttribute("content") doesn't return edited content of published posts 

### ISSUE THREAD

**Issue by IreneStr** [WordPress/gutenberg#5073]
## Issue Overview
`getEditedPostAttribute("content")` doesn't return the most up-to-date version of the content when called on a published post. 

## Steps to Reproduce

1. Open a published post (or write a new post and hit 'publish')
2. Make some changes in the content. **Do not** hit 'update'
3. Call `wp.data.select("core/editor").getEditedPostAttribute("content")` in your console.
4. See that the latest changes are not reflected in the returned content.

## Expected Behavior
`getEditedPostAttribute("content")` should return the most up-to-date version of the content.

## Current Behavior
When I edit a published post and call `wp.data.select("core/editor").getEditedPostAttribute("content")` in the console, the returned content is not the latest version. When I hit update, and try again, I do get the most recent version.

NB: when I do the same on a draft, I do get the most recent version either way. 

## Gutenberg version
Latest master

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by aduth** [comment]
What version or commit are you running? I could imagine prior to #4955 & #5071 the content attributes specifically could fall behind in updates.

Running master and your steps to reproduce, I am receiving the expected content in the console.

**Comment by mtias** [comment]
Closing but feel free to reopen if there is more info.

**Comment by aduth** [comment]
@lebleut Could you provide more information on specific reproducible steps, what you're seeing, and what you're expecting to see?
