### ISSUE TITLE
Shortcodes not rendering from Templates

### ISSUE THREAD

**Issue by kubiqsk** [WordPress/gutenberg#50743]
### Description

Shortcodes that are placed in Template in Site editor are not converted to HTML code on frontend but they stay in [shortcode] raw text format.

This can be temporarily fixed by creating a custom Template part, putting shortcode in it and then using this template part inside Template in Site editor - then everything works, but it's a very tricky solution.

### Step-by-step reproduction instructions

Edit template for single post in Site editor and put there eg. Contact Form 7 shortcode, but you can also use their block, because it's also based on shortcode.
Put it eg. below Post content block and save it and take a look on frontend.

### Screenshots, screen recording, code snippet

admin: https://i.imgur.com/oxEuvFi.png
frontend: https://i.imgur.com/VZTcnJ7.png

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kubiqsk** [comment]
Usecase eg. I want to have CTA block with a newsletter form below the post content on single article detail page

**Comment by kubiqsk** [comment]
This is happening no matter if Gutenberg plugin is active or not

**Comment by Mamaduka** [comment]
This is a known issue and will be fixed in the core. Trac ticket: https://core.trac.wordpress.org/ticket/58333.
