### ISSUE TITLE
Error: The theme "xxx" is not installed - @wordpress/e2e-test-utils-playwright

### ISSUE THREAD

**Issue by ManiruzzamanAkash** [WordPress/gutenberg#50741]
### Description

Whenever, I've start working with `@wordpress/e2e-test-utils-playwright` with all setup needed.

It works perfectly with Playwright test, But whenever runs a test @wordpress/e2e-test-utils-playwright using this package, it shows this - 

> Error: The theme "twentytwentyone" is not installed

    at RequestUtils.activateTheme (/Users/maniruzzamanakash/workspace/wpex/wp-content/plugins/surecart-wp/node_modules/@wordpress/e2e-test-utils-playwright/src/request-utils/themes.ts:28:9)
    at Object.test_1.test.extend.requestUtils.scope (/Users/maniruzzamanakash/workspace/wpex/wp-content/plugins/surecart-wp/node_modules/@wordpress/e2e-test-utils-playwright/src/test.ts:139:4)

### Step-by-step reproduction instructions

`.wp-env.json`

```json
{
	"core": null,
	"plugins": [
		"."
	],
	"env": {
		"development": {},
		"tests": {
			"config": {
				"WP_DEBUG": true
			},
			"port": 8889
		}
	}
}
```

`playwright.config.ts`
```ts
import { defineConfig, devices } from '@playwright/test';
import path from 'path';
const { BASE_URL, CI } = process.env;

export default defineConfig({
  testDir: './tests/e2e',
  fullyParallel: true,
  forbidOnly: !!CI,
  retries: CI ? 4 : 0,
  workers: CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: BASE_URL ?? 'http://localhost:8889',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    }
  ],
  webServer: {
    command: 'npm run wp-env start',
    port: 8889,
    timeout: 120_000, // 120 seconds.
    reuseExistingServer: true,
  },
});
```

A simple test-case - `button.spec.ts`

```ts
import { test, expect } from '@wordpress/e2e-test-utils-playwright';

test('should render the button', async ({
	editor,
	page,
}) => {
	await editor.insertBlock('Button');
	await page.keyboard.type('My Button');
	const content = await editor.getEditedPostContent();
	expect(content).not.toBe(null);
});
```

Actually, it doesn't enter into the `test()` for theme warning.

What can I do for this scnenario ?

### Screenshots, screen recording, code snippet

<img width="1235" alt="Screenshot 2023-05-18 at 12 07 24 PM" src="https://github.com/WordPress/gutenberg/assets/17502625/bde0eaa9-c9e5-4c03-90ce-1c99b0d567a8">

### Environment info

- WordPress version - 6.2.1
- Active Theme - Twenty Twenty-One (twentytwentyone)
- PHP version | 8.0.28 (Supports 64bit values)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by fabiankaegy** [comment]
I'm running into this same issue. @ManiruzzamanAkash were you able to find a solution for this?

**Comment by spencerfinnell** [comment]
I am also experiencing this issue.

**Comment by ManiruzzamanAkash** [comment]
Hi @fabiankaegy, @spencerfinnell 
Yeah, I've somehow made a solution with some hacky way. It was because, Gutenberg under the hood, installing a plugin - `gutenberg-test-plugin-disables-the-css-animations`. So, until Gutenberg comes up with a solution, I've made a hacky solution.

Simple solution - Just created a dummy plugin named - `gutenberg-test-plugin-disables-the-css-animations` with it's slug and all and put it inside the test directory. Voila, it has solved.

<img width="1387" alt="Screen Shot 2023-06-21 at 1 11 39 AM" src="https://github.com/WordPress/gutenberg/assets/17502625/179f8c88-c819-4e82-9f15-17e49ce2b649">


Here is a solution, you can find the codes in this PR - https://github.com/ManiruzzamanAkash/wp-react-kit/pull/23

**Comment by alessandrotesoro** [comment]
Same here, makes no sense that I must use twentytwentyone to run tests.

**Comment by swissspidy** [comment]
I think #52339 will actually address this.

In the meantime, if you don't want to create a dummy plugin, you can also simply do `test.extend()` yourself and override the `requestUtils` logic from Gutenberg so it doesn't look for this plugin.

Example:

https://github.com/swissspidy/ginger-mo/blob/b3366f481021f658d4db31bf328837638694237f/tests/performance/fixtures/index.ts#L118-L139
