### ISSUE TITLE
Submenu closes while focus is on parent link

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#50744]
### Description

The Interactivity API for the Navigation block closes the submenu of a parent when focus remains on the parent. Without the Interactivity API, the submenu will remain open while focus is on the parent link.

### Step-by-step reproduction instructions

1. Have a navigation with a submenu
2. Go to the frontend of the site
3. Use the keyboard to place focus on the submenu chevron icon
4. Press `enter` to open the submenu
5. Press `shift + tab` to return focus to the parent link

Without the Interactivity API, the submenu remains open when focus is on the parent link. 
With the Interactivity API, the submenu closes when focus is on the parent link.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by SantosGuillamot** [comment]
Thanks a lot for reporting this 🙂  I created [this pull request](https://github.com/WordPress/gutenberg/pull/50786) to handle that among other accessibility issues.

**Comment by luisherranz** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/50786.
