### ISSUE TITLE
Copy/paste styles should not be available for blocks that do not have style supports

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#50745]
Most notably, the Template Part, Comments, and Query Loop blocks have "Copy styles" and "Paste styles" even though they do not have style supports. 

Let's omit blocks that do not have any style supports declared from rendering the copy/paste controls. 

<img width="600" alt="CleanShot 2023-05-18 at 12 23 42" src="https://github.com/WordPress/gutenberg/assets/1813435/c4504be4-3aa4-48da-9d47-95c3cde27aa7">

**Comment by glendaviesnz** [comment]
This is slightly tricky as there is no single `styles` support, various style supports are listed separately under the `supports` property in block.json. 

Should we just say don't show if no supports at all, or do we want to check for a specific list of supports? For instance, the Query block supports `__experimentalLayout` and Copy/Paste styles will currently copy this setting between blocks.

**Comment by richtabor** [comment]
Maybe copy/pasting requires either supports.typography or supports.color. I think that'd cover the majority of blocks that have copy/paste-able styles yea?

**Comment by glendaviesnz** [comment]
> Maybe copy/pasting requires either supports.typography or supports.color. I think that'd cover the majority of blocks that have copy/paste-able styles yea?

Not sure, would users not expect layout styles to also be copy/pastable. We separate `style` (color, fonts) from `layout` (constrained layout, etc) in code and interface, but those things are all `styles` in most users eyes probably?

**Comment by richtabor** [comment]
> Not sure, would users not expect layout styles to also be copy/pastable. 

I think those styles are fine to stay copy/pastable (everything that is copy/pasteable should remain as so). I just want to reduce the noise for blocks that don't have, or aren't thought to have, styles. 

It's probably fine to include blocks with layout support as copy/pastable, but the main reason I didn't suggest layout is because the Query loop shouldn't have copy/paste styles.
