### ISSUE TITLE
Can't Close the Submenu with Click or Keypress on Chevron

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#50746]
### Description
The Interactivity API for the Navigation block doesn't allow an open submenu to be closed when using the chevron icon.

### Step-by-step reproduction instructions
1. Have a navigation with a submenu
2. Go to the frontend of the site
3. Use the keyboard to place focus on the submenu chevron icon
4. Press `enter` to open the submenu
5. Press `enter` again. The submenu should close, but it remains open.

**Comment by SantosGuillamot** [comment]
Thanks a lot for reporting this 🙂  I created [this pull request](https://github.com/WordPress/gutenberg/pull/50786) to handle that among other accessibility issues.

**Comment by luisherranz** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/50786.
