### ISSUE TITLE
List View: Consider removing cell animation to improve scannability

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#50750]
There's a slight animation (via CSS transition) delaying the visibility of the menu cell. It leads to a bit of inconsistency in how items are transitioned to a hover state as you scan the List view block (as the text hover style is immediate). 

While I'm a proponent of animation, I do think that in the context of the List View (where speed and accuracy are paramount and there are lots of moving pieces) we should reduce the transitions.

### Current 

https://github.com/WordPress/gutenberg/assets/1813435/ef58ae63-cd2b-4827-af59-9fc67b989317

### Proposed

https://github.com/WordPress/gutenberg/assets/1813435/8c32c1cf-9a11-4ddf-80de-493e8f7cbfe0

Another potential follow-up would be to apply a background color to the hover state, instead of a text color change, so that the text and icon colors remain the same (but that's another discussion point, as its not done elsewhere). 

Also, scannability might not be a word :)

**Comment by Ren2049** [comment]
@richtabor
Nice. Talking about list view working speed, what is your opinion about these two issues?

https://github.com/WordPress/gutenberg/issues/50717

https://github.com/WordPress/gutenberg/issues/50716

**Comment by jasmussen** [comment]
Agreed. Let's put it in the ux board.
