### ISSUE TITLE
"Site updated" notification bouncing around with Block Theme Preview experiment on

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#50759]
The "Site Updated" notification seems to be bouncing around a bit in GB 15.8:

https://github.com/WordPress/gutenberg/assets/26996883/99a97d9d-e497-4faa-9a63-12b32591ec1f

This notification occurs when the experiment is active but, if disabled, the notification doesn't occur nor does it bounce :) 

cc @scruffian

**Comment by scruffian** [comment]
I can't replicate this anymore. Closing, but feel free to reopen if you can still see it.
