### ISSUE TITLE
Block mover drag handle cursor style should be `grab`

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#50789]
### Description

When the editor is in 'Select' mode, the cursor style of the block mover (actually it's the 'block selection button') drag handle is `grab`:

<img width="716" alt="Screenshot 2023-05-19 at 13 01 34" src="https://github.com/WordPress/gutenberg/assets/1682452/592ec239-48a6-4efc-bd22-889e7595cc7b">

However, when the editor is in 'Edit' mode, the cursor style is `pointer`:

<img width="735" alt="Screenshot 2023-05-19 at 13 02 11" src="https://github.com/WordPress/gutenberg/assets/1682452/502c7e9a-5d0f-4022-a77e-e19aaa315e2a">

The pointer style isn't appropriate here, as this control can't be clicked.

I _think_ (not 100% sure) this regressed in https://github.com/WordPress/gutenberg/pull/40379

The cursor style in previous WP version 5.7.:

<img width="839" alt="wp 5 7" src="https://github.com/WordPress/gutenberg/assets/1682452/f261c991-e901-4821-83ac-e8917bb1b91f">

### Step-by-step reproduction instructions

- Go to the Post or Site editor.
- Make sure the Editor is in 'Edit' mode.
- Select a block: the block toolbar appears.
- Hover the drag handle.
- Observe the cursor style is `pointer`.
- Switch the editor to 'Select' mode.
- The block toolbar switches to the 'selection button' (that is the black sort-of-toolbar).
- Hover the drag handle.
- Observe the cursor style is `drag`.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Fixed by #50808
