### ISSUE TITLE
Creating custom template fails

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#50793]
Creating a custom template doesn't proceed correctly to the next step:

https://github.com/WordPress/gutenberg/assets/846565/1f897743-3dea-4be6-8a13-da5814d4f6ea

@ntsekouras I wonder if this regression was caused by combining the modals in https://github.com/WordPress/gutenberg/pull/50595?

**Comment by ntsekouras** [comment]
Oh, wow. Sorry about that! I'll create a fix asap.
