### ISSUE TITLE
Quote problem when typing fast

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#5080]
## Issue Overview
When typing fast in the quote block. Characters may be lost and the typing behavior becomes broken.

## Steps to Reproduce (for bugs)

1. Type fast in the content of a code, verify some characters are lost.

## Screenshots / Video
I was just typing, no deleting and we can see delete behavior while typing:
![feb-15-2018 16-22-20](https://user-images.githubusercontent.com/11271197/36267697-75af7d86-126c-11e8-9705-883864389a61.gif)

**Comment by youknowriad** [comment]
Did you try before or after this merge #5071 ?

**Comment by jorgefilipecosta** [comment]
I just retested and that merge fixed the problem 👍 I'm closing this one.  Thank you @youknowriad.
