### ISSUE TITLE
The Manage all template parts screen is too narrow

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#50815]
### Description

On Gutenberg trunk, there is currently a problem with the Manage all template parts screen. It is too narrow. It no longer extends to the browser's width minus the navigation sidebar.

May be related to the display flex here:
```
.edit-site-layout__canvas {
	align-items: center;
	bottom: 0;
	display: flex;
	justify-content: center;
	left: 0;
	position: absolute;
	top: 0;
	width: 100%;
}
```

### Step-by-step reproduction instructions

Go to Appearance > Editor, Template parts > Manage all template parts.

### Screenshots, screen recording, code snippet

<img width="1499" alt="manage all template parts does not extend to the width of the browser minus the sidenar." src="https://github.com/WordPress/gutenberg/assets/7422055/0c41a640-2bf8-4bfd-aa00-1c7ea53bbde6">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I used `git bisect` to locate the commit where this problem occurred. It is probably affected by #49910.
