### ISSUE TITLE
Convert `renderAdditionalBlockUI` to Component and accept props

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#50827]
In https://github.com/WordPress/gutenberg/pull/50774 we augmented the `renderAdditionalBlockUI` render callback. Before this becomes public we should make it accept a _Component_ rather than a function.

This will also solve the issue of a potentially ever expanding list of positional arguments as mentioned in the discussion referenced below.

.......

> This now forms part of the API of `renderAdditionalBlockUI` as positional params. If and when `renderAdditionalBlockUI` becomes part of the stable API, `insertedBlock` and `setInsertedBlock` might not be applicable for some use cases, but we also might want to add additional params at some stage. Would it be worth switching `renderAdditionalBlockUI` to use an object as its param?

_Originally posted by @andrewserong in https://github.com/WordPress/gutenberg/pull/50774#discussion_r1199875085_

**Comment by Mamaduka** [comment]
I started working on this in #51163. I need to do a bit more testing, but PR is ready for early feedback.
