### ISSUE TITLE
The command center icon overlaps the Add New Template button on the Manage all templates screen

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#50842]
### Description

On the Manage all templates screen and the Library (template part list):
When the browser width is narrow enough that the navigation sidebar closes, the command center search icon overlaps the
Add New Template button. Please see screenshot.

### Step-by-step reproduction instructions

1. Activate a block theme.
2. Go to Appearance > Editor. Select Templates, and manage all templates.
3. Reduce the browser window width until the sidebar closes.
4. View the icon and the Add New Template button in the top right corner.

### Screenshots, screen recording, code snippet

<img width="885" alt="Screenshot 2023-05-22 at 13 55 46" src="https://github.com/WordPress/gutenberg/assets/7422055/90cf6cef-99f7-4fe0-b16a-b2f357f2f7b2">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by juanfra** [comment]
I can't reproduce it. It seems that the design for this section has been updated since this was reported. 

This is how it looks in my local environment

![Image](https://github.com/WordPress/gutenberg/assets/252415/341e4aaa-fe91-44ab-b24e-9caa531ad80f)

**Comment by carolinan** [comment]
I am not able to reproduce it either, closing.
