### ISSUE TITLE
Show Page Title placeholder rather than Post Title for page templates

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#50854]
The Post Title block displays the title for posts, pages, and any other content-type. However, the placeholder only ever shows as "Post Title". This causes folks to sometimes remove it from page templates thinking it doesn't relate to their page title:

https://github.com/WordPress/gutenberg/assets/26996883/7340ef59-ee8c-42c3-9bac-d47904e335a1

In this case, if possible, we should show the block as "page title" in certain contexts, especially since you can currently search for that with the slash inserter:

<img width="536" alt="Screen Shot 2023-05-22 at 5 10 17 PM" src="https://github.com/WordPress/gutenberg/assets/26996883/519066d4-cedd-465e-8265-8b4957c2f197">

I couldn't find an open issue for this but if there is one, please feel free to close this out! This issue around preventing removal of important blocks is also related: https://github.com/WordPress/gutenberg/issues/40618

**Comment by ntsekouras** [comment]
I think this could be considered duplicate of https://github.com/WordPress/gutenberg/issues/48963.

**Comment by annezazu** [comment]
Ah ha! Agreed. Thank you. Closing out.
