### ISSUE TITLE
Ability to add a favicon even if there is no site logo

### ISSUE THREAD

**Issue by andxblink** [WordPress/gutenberg#50860]
Ability missing to add a favicon if there is no "image site logo", but only a "text site logo". Currently, this results in the WordPress default favicon, which my not be preferred.

**Comment by hanneslsm** [comment]
You can add a favicon, without having a site logo.
For that, use the customizer by following this link on you website `/wp-admin/customize.php?autofocus[section]=title_tagline`

However, I can confirm that currently this link can only found on the site logo block settings, which is not ideal.
<img width="279" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/a22c1dd4-cada-4611-8a53-1b8c91b9dc13">

**Comment by andxblink** [comment]
Current solution:

1. Use the site-logo-block to open customizer
2. add the favicon in customizer
3. delete the site-logo-block

**Comment by paaljoachim** [comment]
Thank you for this issue! This is really important missing feature that still has not been added that I know about.
@WordPress/gutenberg-design

**Comment by jordesign** [comment]
Could we have a setting added under Settings > General for this? And if there *is* an image already selected - the 'Use as Site Icon' option (in the Site Icon block) defaults to on?

**Comment by paaljoachim** [comment]
Hey @jordesign 
I found this WordPress Trac ticket: 
Add an option to configure the site icon in general settings
https://core.trac.wordpress.org/ticket/54370

**Comment by jasmussen** [comment]
I can't find the issue at the moment, but I think I suggested a Site editor > Settings section for the future, to hold things like these, in an issue about where to store global settings that I vaguely recall @andrewserong creating.

**Comment by paaljoachim** [comment]
That sounds like a very good idea Joen!
Thank you for sharing!

**Comment by jameskoster** [comment]
@jasmussen I think that was [this issue](https://github.com/WordPress/gutenberg/issues/49597), which was morphed to narrow scope, and didn't include the site icon setting. 

I think we should open a new issue for global settings, or repurpose this one.

**Comment by jasmussen** [comment]
Ah yes, perfect! [This was the comment I made](https://github.com/WordPress/gutenberg/issues/49597#issuecomment-1502883807).

**Comment by Marc-pi** [comment]
yep, if we want to quit /suppress the old customizer because of the new paradigm (FSE), we neeed indeed a new setting option within the editor
maybe it will be proposed through the new admin works (phase 3) ?

**Comment by MaggieCabrera** [comment]
There's a valid use case where you don't want your site logo to look like your favicon and vice-versa. You might want them to have different aspect ratios for one

**Comment by andrewserong** [comment]
Just bringing over a bit of the discussion from #59298. In WP 6.5, the settings page of `wp-admin` will have an area for adding a site icon (trac ticket: https://core.trac.wordpress.org/ticket/54370). One of the ideas in #59298 was whether it would also be helpful for the site editor to have a dedicated place for updating the site icon so that folks don't need to navigate out of the site editor in order to make updates? This is probably less urgent now that we'll be able to link users to the settings page instead of into the customizer (the issue to update the link is here: https://github.com/WordPress/gutenberg/issues/59382).

I'd be curious to hear what folks think, if the new area in the settings page for updating the icon is enough for now.

**Comment by jameskoster** [comment]
I'd agree it's less urgent now. I'd be tempted to hold off adding the setting to the site editor until we have a slightly clearer overall picture of the ongoing Admin design work.

**Comment by Sam-Xronn** [comment]
@andxblink I feel like this issue can be closed now? The WP 6.5 feature has covered off this issue?

**Comment by richtabor** [comment]
Makes sense to me.

**Comment by wdburgdorf** [comment]
How is this covered? I still see no option to set the favicon. Settings ("Style Book") only has the site logo, no favicon. (WP 6.6.2)

**Comment by hanneslsm** [comment]
> How is this covered? I still see no option to set the favicon. Settings ("Style Book") only has the site logo, no favicon. (WP 6.6.2)

You can now change the favicon / site icon in the general settings.
https://core.trac.wordpress.org/ticket/54370
I guess this resolves this issue and can be closed.

**Comment by jasmussen** [comment]
Thanks for responding that. Closing as fixed.
