### ISSUE TITLE
Should pressing tab indent a list item when typing in a list block?

### ISSUE THREAD

**Issue by twsp** [WordPress/gutenberg#5087]
## Issue Overview
When typing in a list block, pressing tab moves the focus to the next block, rather than indenting the list item you are working on.  Obviously, this is a design choice, but I feel it would be more intuitive if pressing tab indented the list to create a sub-list, so you don't have to press the "indent/outdent list item" buttons, since this is how most text editors function.

## Steps to Reproduce (for bugs)

1. Create a list block
2. Add an item
3. Under it, add another item, but try to indent it by pressing tab (imagine that item 2 is supposed to be a sub-item under item 1

## Expected Behavior
Pressing tab should indent the list item.

## Current Behavior
Pressing tab moves the focus to the next block, which I feel is less intuitive when typing.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by aduth** [comment]
Related: #1640, #1826

**Comment by youknowriad** [comment]
I'm closing this issue as this has been discussed and dismissed for accessibility reasons (see https://github.com/WordPress/gutenberg/issues/1640#issuecomment-312494920)
