### ISSUE TITLE
LinkControl: Simpler suggestions

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#50885]
Part of https://github.com/WordPress/gutenberg/issues/50891

Let's simplify the suggestion display, allowing room for more results and making them a bit easier to digest. Note that suggestions and search result items are programmatically the same. 

### Tasks 

- [x] Apply proper metrics so that search results have 16px between the contents within each item.
- [x] Update search-item-type styling ($gray-700, body size, capitalize).

### Visuals

| Current  | Proposed |
| ------------- | ------------- |
|<img width="316" alt="CleanShot 2023-05-23 at 12 20 37" src="https://github.com/WordPress/gutenberg/assets/1813435/9dd0c064-3222-4218-b94a-8634772dce42">|<img width="343" alt="CleanShot 2023-05-23 at 12 13 12" src="https://github.com/WordPress/gutenberg/assets/1813435/2633ad81-d518-4c2c-931b-b0488d696404">|

**Comment by getdave** [comment]
> Remove the search-item-info from each item.

We've been [discussing this](https://github.com/WordPress/gutenberg/issues/50891#issuecomment-1562493109) and I think we should be very careful about regressing the utility of the results in favour of the aesthetics. Not to say you won' have considered this, but rather you may not have the context I've outlined in the comment about the history of _why_ this information was introduced here 🙇

**Comment by getdave** [comment]
I'm trying to come up with suggestions for solving this. Maybe a tooltip on hover on a suggestion which shows the URL?

**Comment by richtabor** [comment]
It may be fine to _just_ include the tail end; not the full URL. i.e. `/?page_id=196`

**Comment by richtabor** [comment]
>  i.e. /?page_id=196

Ironically, this wouldn't be particular useful unless permalinks are set.

**Comment by richtabor** [comment]
Met in the middle with this here. I'll close this. 

<img width="346" alt="CleanShot 2023-07-11 at 11 30 41" src="https://github.com/WordPress/gutenberg/assets/1813435/5e0505af-c111-4ab4-96e1-61fe14d1d795">
