### ISSUE TITLE
register_block_style_handle being called when style does not exist. 

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#50889]
### Description

While doing some profiling, I noticed that the `register_block_style_handle` function was being called 184 times. But seems like 72 times this function is called, it trying to register a css files that do not exist. This is wasteful, as it results in realpath being called and not resolving through for not hitting the cache. Not to mention registering a pointless style. 

These stylesheet should not be registered if the file does not exist. 

### Step-by-step reproduction instructions

N / A 

### Screenshots, screen recording, code snippet

<img width="799" alt="Screenshot 2023-05-23 at 18 59 46" src="https://github.com/WordPress/gutenberg/assets/237508/42167dfa-882b-477f-9ab0-cd1add8ecdb5">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by spacedmonkey** [comment]
A simple workaround is adding the following lines in `register_block_style_handle`. 

```
        $style_path = dirname( $metadata['file'] ) . '/' . $style_path;
	if ( ! file_exists( $style_path ) ) {
		return false;
	}
	$style_path_norm = wp_normalize_path( realpath( $style_path ) );
	$has_style_file  = '' !== $style_path_norm;
```

The better solution would be not to call `register_block_style_handle` at all.

**Comment by swissspidy** [comment]
Looks like this might have been introduced in https://github.com/WordPress/gutenberg/pull/32275 / https://core.trac.wordpress.org/changeset/51102, which adds these styles for all core blocks.

Sounds like this was done on purpose:

> Then, inside `gutenberg_register_core_block_styles` if a file doesn't exist for the registered style, a stylesheet will be registered using `false` as `src`. This way, if a theme adds inline styles to one of these blocks, they will be printed.

cc @aristath

**Comment by spacedmonkey** [comment]
Good find @swissspidy . 

I put together a quick commit to improve this. https://github.com/spacedmonkey/wordpress-develop/commit/3eb647298a86ae3099059effb316458bc4cb0efc . Basically skip a lot of the logic if we know the handle doesn't exist.

**Comment by spacedmonkey** [comment]
Another solution is https://github.com/spacedmonkey/wordpress-develop/commit/c1674e2d98e5f9231abc5e7f827dda732fe0e5f9. 

This stop styles from being re-registered. This saved 15ms on block themes.

**Comment by spacedmonkey** [comment]
https://github.com/WordPress/wordpress-develop/pull/4509

**Comment by spacedmonkey** [comment]
I also put together quick PR to improve block registation of styles by limiting the use of realpath - https://github.com/WordPress/wordpress-develop/pull/4542.

**Comment by spacedmonkey** [comment]
@aristath @felixarntz @joemcgill 

So I have been doing some discovery on this ticket. I found the issue. realpath is being in `register_block_style_handle`, on styles that we know do not exist. Realpath on file that do not exist, are expensive and are not cached. In https://github.com/WordPress/wordpress-develop/commit/716a99587c04e5b37b4ceacc3ccce6c72c842464, styles are register for editor and fe, in a way that they are meant to register with URL false, so developer can register inline styles. 

So there are two problems in the core. 
1. For core blocks we know do not have styles for FE or editor styles, skip calling `register_block_style_handle` and just call `wp_register_style` with false. This means no backwards compatibility break. This avoid, the call to realpath in `register_block_style_handle` and other logic that is not needed, as we know the exist does not exist. 
2. For third party blocks we know what are doing this as well, add a file_exist before calling realpath. This still takes up time and I/O, but it is much faster than realpath, that does symlink lookup etc when called. 

I put together PR [here](https://github.com/WordPress/wordpress-develop/pull/4599). 

Benchmarks on 5000 requests

| | Trunk | PR |
| - | ------ | ----- |
| Response Time (median) | 300.03 | 283.83 |
| wp-load-alloptions-query (median) | 0.71 | 0.71 |
| wp-before-template (median) | 34.27 | 29.61 |
| wp-before-template-db-queries (median) | 3.14 | 3.22 | 
| wp-template (median) | 58.85 | 59.34 |
| wp-total (median) | 93.45 | 89.59 |
| wp-template-db-queries (median) | 6.42 | 6.57 | 

Blackfire

### Trunk
<img width="480" alt="Screenshot 2023-06-12 at 14 37 49" src="https://github.com/WordPress/gutenberg/assets/237508/f23bbebf-66fc-41f8-ad30-a2874d33662e">

### PR 
<img width="498" alt="Screenshot 2023-06-12 at 14 35 35" src="https://github.com/WordPress/gutenberg/assets/237508/a3b9048f-949f-4af0-a8fd-2ec472ca6dbc">

**Comment by spacedmonkey** [comment]
Closing this ticket in favour of a core ticket - https://core.trac.wordpress.org/ticket/58528
