### ISSUE TITLE
LinkControl: Remove tools controls from initial state

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#50886]
Part of https://github.com/WordPress/gutenberg/issues/50891

The link settings, cancel, and apply "tools" (`block-editor-link-control__tools`) should only available when a link has been applied—not before. Let's remove these controls and have them only render if a link is added to the control. 

| Current  | Proposed |
| ------------- | ------------- |
|<img width="360" alt="CleanShot 2023-05-23 at 12 29 17" src="https://github.com/WordPress/gutenberg/assets/1813435/19f3bc55-4835-4da1-afd2-8c98d0475c2f">|<img width="360" alt="CleanShot 2023-05-23 at 12 30 20" src="https://github.com/WordPress/gutenberg/assets/1813435/c503f5c8-b283-4c0c-aa15-71a18060c7de">|

**Comment by getdave** [comment]
This suggestion feels right when yuo consider the UX _as a whole_ as outlined in https://github.com/WordPress/gutenberg/issues/50891.

My only concern remains that this may make it difficult for users of assistive technology to dismiss the popover (we cannot _rely_ on `Esc` as many users won't know about this convention).

I'm not suggesting we retain `Apply/Cancel` but rather we consider

- adding a dedicated close `X`
- work with a11y team to see if a visually hidden `Close` button might be an appropriate compromise

**Comment by richtabor** [comment]
> My only concern remains that this may make it difficult for users of assistive technology to dismiss the popover (we cannot rely on Esc as many users won't know about this convention).


I'm fairly confident there's not a dedicated close action on any other popover, and I don't think LinkControl should be treated any differently. Also, ESC does work within the popovers throughout the editor — so I would think the convention _would_ be realized.

**Comment by richtabor** [comment]
> retain Apply/Cancel

I do think it's good to keep Apply and Cancel actions within the context of editing a link https://github.com/WordPress/gutenberg/issues/50890 — as it affords understanding to whether or not link changes have been saved, or discarded.

**Comment by getdave** [comment]
Good to know we've considered this and accounted for the tradeoffs 👍

**Comment by richtabor** [comment]
This was done as part of https://github.com/WordPress/gutenberg/pull/51712
