### ISSUE TITLE
I should be able to use dashicon in site-editor.php with SCRIPT_DEBUG enabled.

### ISSUE THREAD

**Issue by AnthonyLedesma** [WordPress/gutenberg#50897]
### Description

[I found one other related issue concerning dashicons and script_debug](https://github.com/WordPress/gutenberg/issues/44205). That issue does not identify the specific issue around the use of the site-editor.php however, but about previews. Note that published pages are not affected by this bug.

When inside of the `post.php` block editor we **can** see the custom block with dashicon.

When inside `site-editor.php`, we **_cannot_** see the dashicon SVG.

Current behavior
![image (1)](https://github.com/WordPress/gutenberg/assets/30462574/1a92fd6e-783d-4024-9c3b-701802e3634f)

Expected behavior
![image](https://github.com/WordPress/gutenberg/assets/30462574/cf66115e-f1f1-4230-8816-bfb61bab70b8)

I expect to be able to see the block the same in post.php and site-editor.php.

### Step-by-step reproduction instructions

To see the issue go into the site-editor.php and use the sample code snippet. **_The issue is only repeatable_** when you have SCRIPT_DEBUG enabled.

1. Use the provided code snippet in your browser console.
2. Inside of site-editor, add the block.
3. Notice missing SVG.

To see the contrasting, expected behavior go to the post.php editor. 
1. Use the provided code snippet in your browser console.
2. Inside of post.php, add the block.
3. Notice _proper_ SVG.

### Screenshots, screen recording, code snippet

The sample block provided in the original issue still replicates the issue in the site-editor.php.
> Sample dashicon block to see the issue, paste in your browser console:

> const Dashicon = wp.components.Dashicon
wp.blocks.registerBlockType( 'example/dashicon', {
	title: 'dashicon',
	edit: () => wp.element.createElement( wp.components.Dashicon, { icon: 'admin-site' } ),
	save: () => null,
} )

### Environment info

- WP 6.2.2. Gutenberg not active.
- TwentyTwentyThree theme.
- Chrome browser.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by AnthonyLedesma** [comment]
Related to https://github.com/WordPress/gutenberg/issues/44205

**Comment by Mamaduka** [comment]
Thanks for contributing, @AnthonyLedesma!

I believe this is precisely the same issue as #44205. Dashicons does not work with iframed editors when `SCRIPT_DEBUG`.

I see that you already left a comment there, so I'll close this as a duplicate and continue debugging.
