### ISSUE TITLE
Upgrading Gutenberg breaks Gravityforms shortcode content

### ISSUE THREAD

**Issue by WraithKenny** [WordPress/gutenberg#50896]
### Description

When upgrading from 15.7.1 to 15.8.1, the ***content*** of a Gravity Forms block seems to permanently change, such that A) the form displays as a shortcode instead of rendering on the theme side, and B), turning off Gutenberg doesn't revert the content to a working state.

The Gravity Forms in in a FSE template part (footer) in case that's relevant.

### Step-by-step reproduction instructions

I don't know what other factors might be at play, but I have a site backup on WPEngine, where the only action I take is to update Gutenberg, and this problem happens.

### Environment info

Latest WordPress, latest Gravity Forms, and Gutenberg 15.7.1 to 15.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by WraithKenny** [comment]
related: #50743

**Comment by WraithKenny** [comment]
Related https://core.trac.wordpress.org/ticket/58333

**Comment by WraithKenny** [comment]
Note, this is currently still happening on WordPress 6.2.2, when activating Gutenberg 15.8.1

Whatever fix was shipped with WP 6.2.2 is not working with Gutenberg 15.8.1

**Comment by chthonic-ds** [comment]
Another report of a Gravity Forms block in a template part displaying a shortcode instead of content [https://core.trac.wordpress.org/ticket/58366](https://core.trac.wordpress.org/ticket/58366#comment:30)

**Comment by WraithKenny** [comment]
That's for P and BR.

**Comment by Mamaduka** [comment]
The issue is being tracked in the core ticket @chthonic-ds mentioned since it has to be fixed in the core.

@WraithKenny, are you rendering forms in template parts? Does downgrading the Gutenberg plugin resolves the issue when running WP 6.2.2?

**Comment by WraithKenny** [comment]
I actually don't think this is Gutenberg per se.

I've tried recreating the issue, and got to the part where I was about to upgrade Gutenberg, but instead just deactivated it.

The problem happened anyway. 

I think it's a caching issue somehow.

**Comment by WraithKenny** [comment]
I don't get it. 

As long as I don't 
A) Deactivate Gutenberg, or
B) Upgrade Gutenberg
I can't get the problem to reappear. I can edit the site and do everything I want, as long as I don't do those things.

Is this a caching thing in Gutenberg itself?

**Comment by WraithKenny** [comment]
Fixed in gravityforms_2.7.6.1

Guess if other plugins have issues, they'll resolve them.
