### ISSUE TITLE
Iterating on Details → Styles to lower emphasis on style variations

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#50924]
Currently, the Style section of the Site View emphasizes [style variations with a deep link to open Styles](https://github.com/WordPress/gutenberg/issues/50429). In writing calls for testing and thinking about current issues with changing style variations, like [Custom CSS: Unsaved Additional CSS is lost after browsing different style variations](https://github.com/WordPress/gutenberg/issues/47433#top) & [Custom colors are lost when styles are changed](https://github.com/WordPress/gutenberg/issues/48407#top), it feels risky to surface style variations to this degree and doesn't align with what I imagine is a common action a user will take. For many, style variation switches would constitute a pseudo theme switch in terms of impact to the site's design and potentially layout. Right now, it's really easy to switch and not know how to switch back to what you originally had too without an undo button visible. I know we have revisions but to access those revisions one would have to know to go to the granular Styles view > three dot menu > view revisions. 

What else can we emphasize here? Font management is worth considering if this lands in time for 6.3 https://github.com/WordPress/gutenberg/issues/45271 

cc @mtias @WordPress/gutenberg-design

**Comment by jasmussen** [comment]
I'd like to see Color palettes and Font pairs as two drilldowns in this section. As soon as we have one of either, that would make "Style variations" into its own drilldown, and therefore reduce its prominence. If https://github.com/WordPress/gutenberg/issues/45271 can land, it seems possible we can make a minimal fonts section.

Alternatively, we can just go and make Style variations into a drilldown already. It would feel a bit bare to have a Styles section with just one item, plus the edit and style book items, but it might still be worth it temporarily. Depending on what lands, we can even convert the style book and edit items into menu items to give them more prominence, while we wait for the other drilldown sections to land.

**Comment by jameskoster** [comment]
One thing to try could be an iteration that lists the selected style variation, and offers a pathway to choose a different one. It could even be similar to the theme button that has been design for the Design root:

<img width="790" alt="Screenshot 2023-05-25 at 11 51 28" src="https://github.com/WordPress/gutenberg/assets/846565/344133d0-dc81-4223-aab6-ab538baa1357">

Such a UI can potentially help users understand that choosing a different variation is akin to starting again, and will wipe out their customisations.

**Comment by jasmussen** [comment]
I like the button, and I like the two color dots. I think it can still be worth it to have a style variation drilldown, the active style variation isn't always "kept" — i.e. as soon as you make your own custom changes to it, unless you save them, you're effectively disconnected.

One thing we discussed was potentially having a "Fonts" link here, that just opens the modal from https://github.com/WordPress/gutenberg/pull/50927.

**Comment by jdubecky-mower** [comment]
please remove me from this thread.

I have 350 emails since last night.


Terri Villafana

Director, Strategy and Web Development

Employee Owner



D: 315.413.4208     M: 305.807.8014



_____________________________________



[cid:c25de46e-e639-4de1-a52e-19c55a4f1f51]<http://www.mower.com/>





Making Fierce Friends



ANA B2 Award Best Mid-Size Agency 2022

PRNews Agency Elite Top 100 2023

Chief Marketer Top Marketing Agencies 2023



Ad Age – PRWeek – PR News Best Places to Work



________________________________

**Comment by jasmussen** [comment]
Not sure what happened, but can you click "Unsubscribe" in the sidebar?

<img width="338" alt="Screenshot 2023-05-25 at 14 13 38" src="https://github.com/WordPress/gutenberg/assets/1204802/3dcfc681-e88d-49d2-a305-51f0039f9770">

**Comment by jameskoster** [comment]
> I think it can still be worth it to have a style variation drilldown

Agreed, that's what the button would link to.

> the active style variation isn't always "kept" — i.e. as soon as you make your own custom changes to it, unless you save them, you're effectively disconnected.

Yeah, it's about making that behavior intuitive in the UI. Another option would be to display the variation as the current style, _until you make changes_ at which point it switches to `Custom`.

<img width="759" alt="Screenshot 2023-05-25 at 13 22 54" src="https://github.com/WordPress/gutenberg/assets/846565/67b9942a-6439-4baf-8466-202dc94d67a9">

**Comment by mtias** [comment]
I think this treatment overtly emphasis color at the expense of everything else and can be misleading. For example, the TT3 variations won't be well captured with a dotted color approach.

**Comment by jameskoster** [comment]
We could try a minimised version of the tile from the main Styles panel, to capture typography a bit:

<img width="1020" alt="Screenshot 2023-05-26 at 15 16 35" src="https://github.com/WordPress/gutenberg/assets/846565/d5488ce9-1b4f-4f91-b831-ebb2d3a45521">


But it might be simpler to only display the name.

**Comment by mtias** [comment]
Sort of related, can we try a quick prototype that lifts the entire styles sidebar as is in the full editor and change the color of the dark material to light gray when entering styles? I'm curious if it might work.

**Comment by jameskoster** [comment]
@mtias it seems a little clumsy on the left (different panel header format etc), but this is obviously without any massaging of the details:


https://github.com/WordPress/gutenberg/assets/846565/754e69d6-ee69-42c4-bfcf-abc4377a269b

It's a bit less awkward if the Styles panel appears from the right:


https://github.com/WordPress/gutenberg/assets/846565/460d4831-e416-4e88-95de-f5b424b8b751

**Comment by paaljoachim** [comment]
Ahhh that is interesting James!
Appearing from the right shows a kind of shadow of what it would look like when going into a template and clicking the top right Styles icon to enter the styles area. It would give a kind of consistency of the location of Styles.

**Comment by jasmussen** [comment]
I think if we transplant the styles panel from the edit view to the site view, we can probably do light-weight tweaks for it to match the detail page structure, like the subheading etc. But overall, this seems like it could be a good short term solution that solve a bunch of problems including the inspector/global inspector confusion, as well as the prominence of the variations. @mtias what do you think of Jay's sketches above?

**Comment by jasmussen** [comment]
With fonts looking unlikely to land, one thing we could do is to put style variations into a drilldown (so it's Design > Styles > Style variations), and then have a _button_ above the drilldown that just says "Global Styles", which takes you into the full editor just like the edit button does at the moment.

**Comment by annezazu** [comment]
Sounds good to me except I still feel like we should shy away from "Global Styles" in the interface, similar to this issue https://github.com/WordPress/gutenberg/issues/51202. Perhaps something more action oriented like "Open all Styles" or simply "Open Styles" indicating an action?

**Comment by jasmussen** [comment]
A quick visual:

<img width="3432" alt="style prominence" src="https://github.com/WordPress/gutenberg/assets/1204802/b89ed854-73e7-4983-9b16-cb7e168569af">

CC: @jameskoster what do you think?

**Comment by jameskoster** [comment]
That lowers the emphasis a bit, but since it's the first item of only two, it is still quite prominent. It also makes the panel feel a bit empty. 

If something like https://github.com/WordPress/gutenberg/issues/50924#issuecomment-1580720872 isn't going to be feasible for 6.3, maybe the Styles button at the root should just deep-link into the full-screen editor with the Styles panel open?

**Comment by jasmussen** [comment]
That can be feasible for 6.4 and later, I'm thinking of the above as a 6.3 bugfix, so the changes have to be minuscule.

**Comment by jameskoster** [comment]
It could be worth trying, but it makes the panel feels lacklustre to me because half the action items just send you to the main styles panel anyway. 

If we do try it, should "Style variations" be "Browse styles" to match the main panel? Also, perhaps "Edit styles" instead of "Open styles"?

**Comment by jasmussen** [comment]
<img width="3432" alt="styles drilldown temporary" src="https://github.com/WordPress/gutenberg/assets/1204802/9f370168-bbab-433c-9274-dc01e9a883a4">

Like so?

**Comment by jasmussen** [comment]
@ntsekouras The mockup in the comment immediately above, would that be tricky to implement, and can we get this in as a bugfix for 6.3?

**Comment by ntsekouras** [comment]
@jasmussen Regarding the `browse styles` should it show the style variations in the navigation sidebar like it's now, or it should go to edit mode and open the inspector(right) sidebar?

**Comment by jasmussen** [comment]
> Regarding the browse styles should it show the style variations in the navigation sidebar like it's now

Yes exactly, the same detail is just buried one level deeper.

**Comment by draganescu** [comment]
The styles element in the site editor sidebar now disables distraction free mode on purpose, because in this mode we go to great lengths to make sure no chrome is present (due to how the editor UI is built it's not immediately obvious how to interact with overlapping z-index items).

**Comment by annezazu** [comment]
Closing this out as the initial PR to address this was closed: https://github.com/WordPress/gutenberg/pull/51964#issuecomment-1614248930 in favor of https://github.com/WordPress/gutenberg/issues/52158 which matches current behavior in Trunk. While I disagree with no deprioritizing due to the current bugs, let's see how this lands and reopen/iterate as we need.
