### ISSUE TITLE
Hiding some Template parts in the inserter

### ISSUE THREAD

**Issue by alshakero** [WordPress/gutenberg#50926]
## What problem does this address?
There is a growing need for template parts that render across the site (Cookie consent widget, newsletter subscription blocks, possible chat widgets, etc…). I consider these UIs to be distinctive from blocks because they're meant to manipulate the experience, and are not part of the content of the site. Let's call them meta UI.

Template parts are a great way to store and customize these. TPs are isolated from the content and don't interfere with the other user pages and content, and they can be easily rendered on the frontend of the site with some simple actions.

The only problem is that ALL template parts are available in the inserter. This defies the purpose and allows users to add these special parts in random places on the site, thus ruining the distinction between content and meta UI.

## What is your proposed solution?
Just like blocks, template parts should have a configurable `inserter` prop. This would allow theme developers (and not only) to make customizable parts that don't mix up with the content of the site. FWIW, at WordPress.com, we're ready to ship a Cookie Consent Block and Newsletter subscription block as soon as this feature lands.

Thanks a lot!

**Comment by talldan** [comment]
The template part instances in the inserter are [block variations](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/), and I think it should be possible to modify the specific variation, maybe by unregistering and re-registering it to remove the `inserter` scope.

**Comment by alshakero** [comment]
Hi @talldan. Thanks for the quick response. I explored this, and they don't seem to be block variations. The inserter just requests posts of type [`wp_template_part` and lists them](https://github.com/WordPress/gutenberg/blob/3fdc87371c72f7b4e1d91b85d5d8a9897c8867fc/packages/edit-site/src/store/selectors.js#L271-L275). There is no registering as far as I understand. I couldn't intercept the listing at all. I tried to call `unregisterBlockVariation` just to see, and didn't make a difference.

The only thing I could do is add an `apiFetch` middleware, but this removed the part everywhere, not only in the inserter.

It's also not possible to filter out things on the backend because the template editor UI is a SPA and uses React router. It doesn't engage the backend to make decisions based on individual screens. So, we can't hide the template part if someone is in the block editor, for example.

**Comment by talldan** [comment]
> The inserter just requests posts of type [wp_template_part and lists them](https://github.com/WordPress/gutenberg/blob/3fdc87371c72f7b4e1d91b85d5d8a9897c8867fc/packages/edit-site/src/store/selectors.js#L271-L275). There is no registering as far as I understand. I couldn't intercept the listing at all. I tried to call unregisterBlockVariation just to see, and didn't make a difference.

I don't think that selector is used by the inserter. I'm fairly certain they're variations as I wrote the code, and I can't see that it's changed.

The variations are [determined in the block's index.php file](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/template-part/index.php#L284) and [declared in the variations.js file](https://github.com/WordPress/gutenberg/blob/1328f2db78cc5bc68f417d4f9c83329272c72474/packages/block-library/src/template-part/variations.js#L24-L64). They're [added to the block type using a filter](https://github.com/WordPress/gutenberg/blob/1328f2db78cc5bc68f417d4f9c83329272c72474/packages/block-library/src/template-part/index.js#L53-L57).

**Comment by alshakero** [comment]
Thank you so much!

This did it
```js
addFilter( 'blocks.registerBlockType', 'core/template-part', function ( settings, name ) {
	if ( name === 'core/template-part' ) {
		return {
			...settings,
			variations: settings.variations.map( variation => {
				if ( variation.name === PART_SLUG ) {
					return {
						...variation,
						// the original scope is ['inserter']
						scope: [],
					};
				}
				return variation;
			} ),
		};
	}
	return settings;
} );
```

**Comment by talldan** [comment]
@alshakero Glad to be able to help! Do you think issue can be closed, or are there still some other relevant parts to discuss?

**Comment by alshakero** [comment]
Closing now. Really appreciate the help!
