### ISSUE TITLE
Styles sidebar: Site logo spacing controls are reset on saving

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#50940]
### Description

When I try to use a global styles preset for margin for the site logo block, the control in the styles sidebar is reset when I save.

Update: same with padding.

### Step-by-step reproduction instructions

1. Activate a block theme. I used Twenty Twenty-Three.
2. Add a site logo block with an image.
3.  In the Site Editor, Styles sidebar, select the site logo block.
4. In the dimensions panel, select a spacing preset. Either one for all sides, or individual size.
5. Save the style changes
6.  See that the control is reset, but in the preview in the site logo panel, the margin is applied.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/7422055/f546ee7a-4a26-43d6-812e-c99064ddd7cc

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by dogwonder** [comment]
I've also been able to replicate this. I tested it on a vanilla install of 6.2.2, Twenty Twenty-Three theme and 15.8.1 version of Gutenberg plugin 

The margin and padding did not persist in the settings panel when applied in the Global Styles context. 

Steps taken to test the issue: 

1. Activated 2023 Theme
2. In site editor, I navigated to Template parts > Header
3. Edited header and added a site logo to the header and moved it as the first block 
4. In global styles I set the logo to max padding and margin. The styles were not saved. 
5. In the preview (admin and front-end) the margin and padding is applied.
6. Re-applying the padding applies it somewhere but the settings do not reflect the current state

## Screenshots, screen recording, code snippet

<img width="1300" alt="CleanShot 2023-05-25 at 10 50 47@2x" src="https://github.com/WordPress/gutenberg/assets/254175/bbb66d6e-b64d-414c-8c6c-a20303c229d2">

https://github.com/WordPress/gutenberg/assets/254175/dbf44801-eafd-4f03-87b8-88c42d62be74

**Comment by t-hamano** [comment]
This problem can be seen in other blocks, so maybe it is occurring in all blocks.


https://github.com/WordPress/gutenberg/assets/54422211/c0530d5d-d9a0-47bb-9228-735f1604519d

**Comment by t-hamano** [comment]
I have identified the cause. I will submit a PR in the near future.
