### ISSUE TITLE
Consider emphasising Header + Footer in Site Editor navigation

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#50958]
The [introduction of the Library](https://github.com/WordPress/gutenberg/issues/50397) creates a centralised location for assets like patterns, template parts, reusable blocks, fonts, etc. 

One drawback to this is that access to the site header and footer becomes somewhat buried, which seems a shame given their outsized importance compared with most other library items.

Shortcuts to these items at the root level of design could give users direct access to these important elements:

<img width="358" alt="Screenshot 2023-05-25 at 13 31 21" src="https://github.com/WordPress/gutenberg/assets/846565/e81853a2-41fa-4de3-8529-5562673e1d7c">

This might work best when there is only a single header / footer to start with. Support for multiples can be added once the Library itself includes dedicated sections for its constituent asset groups.

**Comment by jasmussen** [comment]
I think it can work, especially as themes and templates become possible to decouple and the ability to swap header and footer template parts with bundled wireframe alternatives become an increasingly useful flow. The majority of websites have headers and footers, after all. 

That said, it might be best to do this in a polish phase after some of that decoupling lands, and after we've been able to test the library in the plugin?

**Comment by youknowriad** [comment]
I think this issue is not relevant anymore. Template parts are merged with patterns.

**Comment by youknowriad** [comment]
Actually I'm not sure, feel free to reopen if you think this is still something we want to do
