### ISSUE TITLE
Inline boundary and arrow navigation edge case

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#5095]
Tested on current master.

In the current demo content, there's a paragraph that contains italic text:

<img width="735" alt="screen shot 2018-02-16 at 09 29 04" src="https://user-images.githubusercontent.com/1682452/36299908-5c93ef74-12ff-11e8-8b33-b693a5ca6f50.png">

TinyMCE adds "boundaries" to the italic text so to actually exit the boundary, you have to move the caret using the right arrow key. At that point, arrows navigation through blocks kicks in and the caret moves to the following block.

There's no way to exit the boundary not even using the mouse. Pressing the spacebar doesn't work, as you're still inside the boundary.

The only way I've found to exit the boundary and start typing not italic text is to press the right arrow (this brings me in the following block) then press the left arrow (this brings me back to the paragraph block, outside of the boundary).

Wondering what the best option would be in this case. I'd agree it's an edge case but I guess it won't be so uncommon that a block ends with some link, italic, or bold text.

**Comment by mtias** [comment]
Sounds like we need to update edge-detection to account for boundaries. cc @mcsf @iseulde

**Comment by afercia** [comment]
See also #1246.

**Comment by SuperGeniusZeb** [comment]
As of Gutenberg 2.6, pressing right arrow allows you to exit a formatting boundary (e.g. links or italic text) without moving to the next block. I think this issue can be closed now as the problem appears to be fixed.

**Comment by afercia** [comment]
Yeah I still can reproduce on current trunk. With the caret at the end of a boundary, users should be able to press the right arrow key to exit the boundary. So in this situation (see below):

<img width="805" alt="screen shot 2018-04-12 at 10 36 01" src="https://user-images.githubusercontent.com/1682452/38665798-978a0f1e-3e3d-11e8-935f-f066afdb4591.png">

I should just be able to press right arrow, exit the italic boundary, and keep typing in the current block. Instead, caret goes to the following bock.

**Comment by iseulde** [comment]
To be honest I see no easy solution here. The edge detection is handled in writing flow, which receives the `keydown` event too late. TinyMCE will already have inserted the zero width space at the very end of the editor, so it's considered the edge. Checking for the zero width space here is no option because then we're blocking caret movement entirely. Some possibility would be to check for a second time with the same node but that would be a very ugly fix.

**Comment by iseulde** [comment]
Unassigning for now as I don't have a solution for this atm.

**Comment by aduth** [comment]
Possibly related:

1. Navigate to Posts > Add New
2. Add new paragraph
3. Cmd+B to bold
4. Enter some text
5. Press enter

Expected: New paragraph added after, caret placed at beginning of new paragraph.
Actual: New paragraph added after, caret stays within the inline boundary.

I'm hoping to be able to revive (at least parts of) #6467 and/or #6712 which should address some of the issues noted here.
