### ISSUE TITLE
Responsive controls

### ISSUE THREAD

**Issue by BeholdPL** [WordPress/gutenberg#50960]
I don't understand why Gutenberg doesn't have built in controls for responsive design. I can't set different margin or colour for different breakpoints, every plugin for Gutenberg can do that.

Responsive controls for each blocks settings should be added as soon as possible.

**Comment by hanneslsm** [comment]
> One of the oft-repeated questions in developer circles who have closely followed WordPress’ revolution via the Gutenberg project has been: _When are we going to get more responsive controls?_ Specifically, this question is often framed around the ability to change some design element of a block based on desktop, tablet, or mobile views…

https://developer.wordpress.org/news/2023/02/intrinsic-design-theming-and-rethinking-how-to-design-with-wordpress/

**Comment by BeholdPL** [comment]
The simple way for usability is just add possibility to change the settings that depends of site preview (desktop / tablet / mobile). Why don't create official questionnaire for that and take the response from users? And give them what they want and what they need? No responsive controls is re-creating the wheel, which is waste of time. That's why Gutenber is still so criticized and does not fully use its potential.

**Comment by Ren2049** [comment]
Intrinsic design for layout is too opinionated for page builders imo. Jen Simmons & co. promoted it for the use within a code editor with full CSS grid access and people who know Grid and Flexbox inside out, to save lines of written code. I'd even go so far and say that it will never work within a page builder because the code it saves when writing CSS is irrelevant there, and apart from that the're too many downsides for people who just want to build using an UI.

**Comment by gyurmey2** [comment]
That would be very helpful, but the topic seems not to be taken seriously:
https://github.com/WordPress/gutenberg/issues/47862
https://github.com/WordPress/gutenberg/issues/48331
https://github.com/WordPress/gutenberg/issues/30142#issuecomment-1409896058

**Comment by annezazu** [comment]
Hey folks! Thanks so much for raising this. To better funnel and consolidate the feedback and questions around this area of work, I'm going to close this out in favor of two currently open issues: https://github.com/WordPress/gutenberg/issues/34641 & https://github.com/WordPress/gutenberg/issues/19909. This will cross connect these various conversations. In terms of the timeline for this work, I want to direct you to this tweet from Matías (the project architect of Gutenberg) https://twitter.com/matias_ventura/status/1415378716151193608 We've accomplished some items with fluid typography and flex support but it's a complex problem to solve.
