### ISSUE TITLE
Button: Undocument the `focus` prop

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#50972]
## What problem does this address?

The documentation for the Button component currently advertises a [`focus` prop](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/button/README.md#focus-boolean), which as far as I can tell, has only been working for a four-month period in 2018. ([First implemented](https://github.com/WordPress/gutenberg/pull/6527/files#diff-47628eb6e63618c43a7afb648c04426d01b0ed4ec5e3bb79fb820df1ba4f62baR47) in May 2018 as an alias for the `autoFocus` prop, and then [removed](https://github.com/WordPress/gutenberg/pull/9572/files#diff-1204d0def76e28ff29950465cc842e3fafcee022c7e97c76fa5cf5baa4c4505aL48) without explanation four months later.)

## What is your proposed solution?

Given that this has barely been working in production, and its originally intended behavior can be accomplished via the standard `autoFocus` prop, I suggest that we simply remove this from the documentation (readme and TypeScript types).

**Comment by ciampo** [comment]
Sounds good to me

**Comment by noahbcaldwell** [comment]
I would like to be assigned to this task!

**Comment by mirka** [comment]
@ncaldwe Perfect, thank you! Ping me when you submit a PR 🙂

**Comment by noahbcaldwell** [comment]
@mirka pull request submitted!
