### ISSUE TITLE
Allow selecting the default `core/navigation-link` variant in the `core/navigation` block

### ISSUE THREAD

**Issue by sethrubenstein** [WordPress/gutenberg#50982]
## What problem does this address?
The `﻿core/navigation` experience is heavily geared towards core taxonomies such as ﻿`category` and `﻿tag` as well as the `page` post type. The navigation-link block provides variations from all public taxonomies, but because of issues with the current insertion UI it effectively hides them. It's easier to create custom navigation blocks if your site structure is centered around a custom taxonomy or other model altogether. 

## What is your proposed solution?

I think a simple "Gutenberg API forward solution" would be to add an attribute something like `defaultVariant` to the core navigation block and then check for that attribute value before defaulting to `DEFAULT_BLOCK` at https://github.com/WordPress/gutenberg/blob/b95148fd0a2fb7ef54e4d913771cb08d04bcc025/packages/block-library/src/navigation/edit/inner-blocks.js#L101. Then it would be as simple as passing something like `{name: 'core/navigation-link', attributes: {type:'my-custom-taxonomy', kind:'taxonomy'}}` as the default value using existing JS or PHP hooks.

I believe there have been several discussions about setting allowed blocks as an attribute on most core blocks, like in the group block (https://github.com/WordPress/gutenberg/pull/49128). At Pew Research Center, we have adopted this strategy in our block library, and it has been very effective. It allows us to extend our own blocks internally using block variations. I think applying the same logic to `__experimentalDefaultBlock` could give developers a lot of flexibility within core blocks and enable them to customize the experience for their end users.

**Comment by sethrubenstein** [comment]
Once I get some Gutenberg build and test issues resolved locally I'll make a pull request for this https://github.com/pewresearch/gutenberg/commit/a3b3970bbda02c31b144e33e80d0859242051114

**Comment by annezazu** [comment]
Thanks for jumping in here to both share an issue and spin up a PR! Love to see Pew Research continuing to drive forward. Going to tag in some folks doing work around 6.3 related priorities for navigation which you can see here: https://github.com/WordPress/gutenberg/issues/50165 @getdave @scruffian

**Comment by sethrubenstein** [comment]
After some merging nightmare I have an updated pull request for this now that #52083 has been merged. https://github.com/WordPress/gutenberg/pull/52610

**Comment by annezazu** [comment]
[After a review](https://wordpress.slack.com/archives/C02QB2JS7/p1707152945370159) by core editor triage leads and core editor tech leads, this has been removed from the board for 6.5 consideration.

**Comment by annezazu** [comment]
Of note, you might want to dig into this recently merged PR: add allowedBlocks field to block.json to specify allowed children ([58262](https://github.com/WordPress/gutenberg/pull/58262)) along with work done to ensure all custom taxonomies/post types are available for the Navigation block https://github.com/WordPress/gutenberg/pull/54801  & https://github.com/WordPress/gutenberg/pull/56100 I _think_ these might solve the problem for you but curious if not!

**Comment by sethrubenstein** [comment]
That it does @annezazu . #58262 is a hugely welcome addition. Thanks!
