### ISSUE TITLE
UI Prototype: Consider how far to take this

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#51]
A lot of eyes on <a href="https://wordpress.github.io/gutenberg/">the prototype</a> these days 🎉 ! 

A lot of tickets have been opened, noting the features the prototype are lacking (due to being dummy controls):

- https://github.com/WordPress/gutenberg/issues/50
- https://github.com/WordPress/gutenberg/issues/49
- https://github.com/WordPress/gutenberg/issues/47
- https://github.com/WordPress/gutenberg/issues/46
- https://github.com/WordPress/gutenberg/issues/45
- https://github.com/WordPress/gutenberg/issues/44
- https://github.com/WordPress/gutenberg/issues/41

All this excitement around what was mainly a UI only prototype leads into the next question: where do we take this prototype from here? We've discussed creating two actual editor prototypes, one which uses TinyMCE as a parent of all blocks, one which uses TinyMCE as a child of each block. @iseulde has already done stellar work on the former here: https://iseulde.github.io/editor-blocks/

Could the UI prototype grow into the latter?

**Comment by mtias** [comment]
Let's keep it just as a UI playground for now to test ideas and to serve as the dynamic mockup for the other work. We'll be merging the TinyMCE as a parent as a separate prototype so we can work on both.

**Comment by mtias** [comment]
Here's what I have in mind for the different prototyping efforts:
```
- /gutenberg — UI prototype.
- /gutenber/01/ — Ella’s approach.
- /gutenber/02/ — a TinyMCE per text block approach.
- /gutenber/03/ — a single instance of TinyMCE without any blocks just to test formatting ideas.
- /gutenber/parser/ — the parsing explorer to test markup.
- etc
```

**Comment by jasmussen** [comment]
Closing this for now, as we have found a good direction for this.
