### ISSUE TITLE
Add an option to describe Blocks for easier navigation in Document Overview

### ISSUE THREAD

**Issue by sreckins** [WordPress/gutenberg#51007]
## When having a lot of blocks in a page it can be hard to find the right group/gallery (also it's ugly)
Especially when I have multiples of the same block - that also have individual advanced attributes like classes or anchors - the visual editor is not always helpful.
![image](https://github.com/WordPress/gutenberg/assets/9610002/6417adc7-4e39-425b-a82c-ad3a9cb00cca)

## Add a comment option to every block that is shown in the List View
This would also help incredibly when using the Drag&Drop Function in the List View!
![image](https://github.com/WordPress/gutenberg/assets/9610002/d20e7750-b6b3-4cb5-9888-2f9f966d140a)

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/33583. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and subscribe to follow progress on that issue.
