### ISSUE TITLE
Video support for Cover Block

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#51016]
## What problem does this address?
It is currently possible to select a video for the cover block.  Unfortunately I don't have the settings like with the standard video block, for example to play the video once or to select a fallback image.

## What is your proposed solution?
Please include the video functions in the cover block as they are also available in the standard video block in order to make settings for playback or fallback.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/38975. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and subscribe to follow progress on the issue
