### ISSUE TITLE
Duotone: Custom filter colors do not work

### ISSUE THREAD

**Issue by kellychoffman** [WordPress/gutenberg#51023]
When using the duotone feature, picking a custom color shows up properly in the editor view, but when you publish, the filter does not appear. However, the presets work just fine. You have to change one of the colors to replicate this bug.

Steps to replicate:

1. Select image block with photo
2. Apply duotone filter
3. Change one or both of the colors
4. See colors change in editor
5. Press publish
6. Navigate to front end of site
7. Notice photo now has no filter applied

**Screenshots**

Editor view:
<img width="619" alt="Screenshot 2023-05-26 at 11 33 57 AM" src="https://github.com/WordPress/gutenberg/assets/5835847/6a2336bc-4dbc-436f-bfd1-53df04249d61">

Published view:
<img width="331" alt="Screenshot 2023-05-26 at 11 32 15 AM" src="https://github.com/WordPress/gutenberg/assets/5835847/39d0d876-5c6c-45ff-bb1e-4149fa64e7a5">

Have tested with a variety themes and versions of Gutenberg. Consistent results. @annezazu can also replicate.

cc @ajlende

**Comment by ajlende** [comment]
@kellychoffman I'm unable to replicate this. There was [an issue with kses that was fixed](https://github.com/WordPress/gutenberg/pull/50678) around the time you opened this issue, so it may already be resolved.

What version of WordPress and Gutenberg were you running?

**Comment by kellychoffman** [comment]
Excellent, thanks for following up. That PR fixed it. Closing this issue.
