### ISSUE TITLE
Dimension controls went missing after latest Wordpress releases

### ISSUE THREAD

**Issue by onny** [WordPress/gutenberg#51022]
### Description

In the full site block editor (FSE) I was able to set margin and padding spacing properties to various blocks. With the latest updates these options are now missing in the editor.

### Step-by-step reproduction instructions

1. Open Full Site Editor
2. Click on various blocks, like the group block
3. On the right pane there are no dimension settings anymore

### Environment info

- Wordpress 6.2.2
- Gutenberg 15.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi
Did you also happen to change the theme?
Spacing settings are not enabled by default. The block theme needs to enable it in the theme.json configuration file.
https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/#spacing

(And are you sure that you are looking in the right tab in the block's settings sidebar? In the Styles tab, not Settings?)

**Comment by priethor** [comment]
Let's close this issue, as it needs more info to be actionable. Please feel free to reopen again if there is more information. 🙏
