### ISSUE TITLE
Pre-Publish sidebar refreshes and removes Suggested panels

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#51024]
### Description

After clicking "Publish" on a post, the pre-publish check sidebar contains the sections:

- **Visibility:** Public
- **Publish:** Immediately
- **Suggested:** Add tags
- **Suggested:** Assign a category

If you wait too long (<30seconds), the pre-publish sidebar refreshes, and the 2 Suggested panels are removed. 

Selecting Cancel then Publish again does not restore them, nor does exiting the editor, refreshing, and entering back in to that post.

### Step-by-step reproduction instructions

1. In a new post editor, open preferences and ensure "Include pre-publish checklist" is enabled
2. Select **Publish**
3. Leave the Pre-Publish checklist open; assign some tags and a category perhaps, but wait here to allow the sidebar to refresh

When it refreshes, you'll find the Suggestion panels disappear

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/27249804/89ff7ccc-eb10-41ac-8e55-696fe524a9b4

### Environment info

- WP 6.2.2
- Gutenberg 15.8.1
- No other plugins installed
- Theme: Twenty Twenty Three

_Looks like this also occurs with the plugin deactivated though this seems to still be an editor preference thing, so starting here. LMK if this should be reported elsewhere!_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by torounit** [comment]
I was able to reproduce this issue.

After a short wait, the panel is removed.

The reason the panel does not appear again is because the categories and tags are set. If you delete the category or tag, it will appear again.

**Comment by cuemarie** [comment]
Tested again today, and I'm still able to reproduce in Gutenberg 16.0.0.  Refresh happened 50 seconds after clicking Publish - video below includes the last ~5 seconds of that wait, and then the refresh occurs and the suggested tags/categories panels are removed. 


https://github.com/WordPress/gutenberg/assets/27249804/ca2b6b74-51d5-45c7-90ed-ff48186f1e38
