### ISSUE TITLE
Customize Widgets: Top toolbar not displaying in correct position

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#51037]
(cc @draganescu)

### Step-by-step reproduction instructions

1. Switch to a classic theme
2. Go to Appearance > Customize > Widgets > [ Sidebar ]
3. Switch the top toolbar option on

Expected - The top toolbar appears in the correct place above the block editor
Actual - it appears next to the publish button over the customizer preview at the very top of the screen

### Screenshots, screen recording, code snippet

![Screen Shot 2023-05-29 at 11 37 38 am](https://github.com/WordPress/gutenberg/assets/677833/bda7e6c5-f2d4-4c11-9ce2-2f3fd35099de)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by draganescu** [comment]
Oh what a catch! Thank you @talldan will look into it ASAP - I only recently fixed a similar problem in the other widgets editor 😂

**Comment by talldan** [comment]
Thanks @draganescu!
