### ISSUE TITLE
SpacingSizesControl: The first mouse drag does not move the slide from position 1.

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#51030]
### Description

In the SpacingSizes control, I cannot move it from position 1 by dragging the mouse.

The problem seems to occur on the first operation when switching to custom size input, entering some value, and then returning to preset mode.

https://github.com/WordPress/gutenberg/assets/54422211/ca032bbf-dea5-4b94-895f-ab205354fd8b

### Step-by-step reproduction instructions

- Access the padding/margin control of any of the blocks.
- Confirm that the slider can be moved correctly.
- Click the Custom Size button.
- Enter some value.
- Press the button to return to the preset mode.
- Confirm that the slider is positioned at the top.
- **Confirm that the slider cannot be moved correctly with the mouse.**
- Release the mouse cursor and try dragging again for correct operation.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I was able to replicate this, but this control is about to get a [big overhaul](https://github.com/WordPress/gutenberg/pull/50660), and I was not able to replicate the issue on that PR, so we may be able to close this once that is merged.

**Comment by glendaviesnz** [comment]
Closing as I was not able to replicate now that #50660 is merged, but feel free to reopen if you still experience this on trunk.

**Comment by t-hamano** [comment]
Thank you! I too have confirmed that it does not reproduce with the latest trunk.
