### ISSUE TITLE
useEntityProp( 'postType', postType, 'meta' ) returns undefined inside Query Loop Block

### ISSUE THREAD

**Issue by poof86** [WordPress/gutenberg#51033]
### Description

When using useEntityProp( 'postType', postType, 'meta' ) in the edit function of a block that is placed inside the Query Loop > Post Template block, the hook returns undefined.

It's working fine when using the same block outside a query loop, for instance in the single post template.

### Step-by-step reproduction instructions

Make a copy of the core/post-title block and add the console.log( useEntityProp( 'postType', postType, 'meta' ) ); in the block's edit function.

In the editor place the new block inside a Query Loop > Post Template Block.

Be sure to support custom-fields and have meta data registered 
add_post_type_support( 'post', 'custom-fields' );
register_post_meta( '', 'test', array(
            'show_in_rest' => true,
            'type' => 'string',
            'single' => true,
));

### Environment info

Wordpress v6.2.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi. I think that to use `useEntityProp in a query loop, you need to specify the `postId` as the fourth argument.

The post title block is an example of this part.

https://github.com/WordPress/gutenberg/blob/0488e292db40ecd17eb4b2e8484a10bfe57665a9/packages/block-library/src/post-title/edit.js#L41-L45

You would also need to define the context in `block.json`.

https://github.com/WordPress/gutenberg/blob/0488e292db40ecd17eb4b2e8484a10bfe57665a9/packages/block-library/src/post-title/block.json#L9

**Comment by poof86** [comment]
I couldn’t find documentation about the hook, but you’re definitely right about useEntityProp() allowing a forth _id argument. (see core-data/src/entity-provider.js)

Because I copied the core/post-title block the context is already provided for.

I’ll try useEntityProp( 'postType', postType, 'meta', postId) and let you know how it goes.

*update*
This was the solution 😄 

Thank you!
