### ISSUE TITLE
Page-Editor sidebar panel menu items appear to be blurry since WP 6.2

### ISSUE THREAD

**Issue by Supportic** [WordPress/gutenberg#51032]
### Description

I updated the WordPress version of one of my instances to 6.2 recently and recognized that the menu items of the sidebar panel are blurry.

### Step-by-step reproduction instructions

1. install [WP playground](https://github.com/WordPress/wordpress-playground)
* git clone https://github.com/WordPress/wordpress-playground
* cd wordpress-playground
* npm install
* npm run dev

2. edit a random page
3. open the right sidebar panel

### Screenshots, screen recording, code snippet

**Comparison**:

WP 6.1 (normal)
![wp-6 1](https://github.com/WordPress/gutenberg/assets/20886239/6d00ffba-998a-4764-a82f-9d81d7276bb8)

WP 6.2 (blurry)
![wp-6 2](https://github.com/WordPress/gutenberg/assets/20886239/0fed0f16-1263-4c19-8b92-51e814709228)

### Environment info

**Specs**:

Chrome Version 113.0.5672.127 64-Bit
Lenovo Laptop [IdeaPad 5 15ARE05](https://psref.lenovo.com/Product/IdeaPad/IdeaPad_5_15ARE05) Windows 10 Version 22H2
and Lenovo [ThinkPad L460](https://psref.lenovo.com/Product/ThinkPad/ThinkPad_L460) Linux Ubuntu 22.04

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aurooba** [comment]
I tested this with WP Playground as you suggested, @Supportic, and I didn't notice any blurriness in the menu items. 

I tested it on a Mac in Chrome and Arc, and on Windows on Chrome. Could it have been a temporary glitch with rendering?

<img width="1604" alt="wordpress playground screenshot with the menu in the block editor open, showing no blurriness" src="https://github.com/WordPress/gutenberg/assets/6925260/7f50358a-b82b-4806-bbc7-77200aa47064">

**Comment by Supportic** [comment]
@aurooba
I think it's either tight to specific devices e.g. Lenovo or in general Laptops with specific screen resolutions. I am not experiencing the issue on desktop PCs.
I am leaning more towards a device issue but it seemed odd to me when two devices experienced the same issue and I also could capture it as a screenshot. (it had something to do with the CSS  transform rule for the panel in combination with the max-width)

If this issue is not reproducible at all we can close it.

Another screenshot from a Galaxy Tab A7 tablet. On the device the effect is more pronounced. Maybe it's just because of the font but it doesn't look as crisp as the adjacent elements.
![ApplicationFrameHost_MGe0R0ApLL](https://github.com/WordPress/gutenberg/assets/20886239/ebe5ee53-5052-46f0-8ba4-50d723b04895)

**Comment by aurooba** [comment]
@Supportic Interesting. I think you're right that this is device and/or OS related.

For example, while I was looking around, I saw that Windows has something called `ClearType` and [often there are settings for it that can cause blurry fonts](https://www.howtogeek.com/849544/how-to-fix-a-blurry-screen-in-windows-11/#:~:text=Enable%20ClearType%20for%20Blurry%20Text,-If%20text%20appears&text=Head%20to%20Settings%20%3E%20Personalization%20%3E%20Fonts,in%20the%20window%20that%20appears.).

For the Galaxy Tab, is it possible that there is system-wide anti-aliasing turned on that could be making things blurry?

**Comment by Supportic** [comment]
@aurooba 

Thank for the link. I updated my drivers, turned hardware acc. in chrome on and off but nothing helped.
I solved the problem on the Windows laptop by setting the zoom factor back to 100% instead of 125% (as a OS setting)
ClearType was enabled.

On the Linux laptop however there was nothing to reset. I tinkered around with some CSS properties. It seems that the translateX property on the menu itself in the popover-slot is responsible for the weird rendering. On even px numbers e.g. a factor of 4 (464px) the rendered text looks good. As soon as you shrink down the browser window on odd numbers it appears to be blurry like in the screenshots before.

![transform-x](https://github.com/WordPress/gutenberg/assets/20886239/a8f3f3a0-786a-456e-942a-0da5815ba356)

Some other people also had success by adjusting the values slightly when it comes to text rendering: https://stackoverflow.com/a/42034210/10192487

**Comment by aurooba** [comment]
I'm glad to hear you were able to resolve this on Windows!

It looks like this Chrome bug has existed for a number of years and has yay to be fixed. And the most reliable way to fix it is to not use the `translate` property for `transforms` at all.

Have you tested other flyout components on the Linux computer? Does the blurriness happen, for example, in the colour palette flyout?

**Comment by Supportic** [comment]
I found a way to reproduce it on desktop. Open the devtools and increase the render size to 125%. Might be an accessibility issue then. It happens on the hover toolbox as well when opening the option menu  (see screenshot)

![chrome_zjwGBdnHvE](https://github.com/WordPress/gutenberg/assets/20886239/6e43c242-0e11-4f02-9a8e-ce947420bf6b)
![chrome_7avxNlIUyI](https://github.com/WordPress/gutenberg/assets/20886239/8334cea5-81f4-446d-8617-9ed9d28bd0a2)

**Comment by aurooba** [comment]
There's definitely an accessibility component to this. Are your able to reproduce it in other browsers, such as Firefox and/or Chromium?

I ask because I'm wondering if this is specific to the browser render or the font render in the operating system.

**Comment by Supportic** [comment]
It's a browser problem. I increased the OS scaling to 125%. Edge and Chrome (chrome based browsers) showed blurry text. In Firefox everything was fine. 

To be more specific it's a problem with the translateX property of css transform in chrome based browsers.

**Comment by Supportic** [comment]
Hello everyone,

I wanted to let you know that I do not encounter this issue anymore in WordPress 6.3.2 in case of the sidebar menu. 

This issue still occurs in **floating** sub menus e.g. when opening additional options for a block element like buttons. 

Thanks

**Comment by mt8** [comment]
I tested this issue on WordPress 6.5.2 GB 18.1.2 and the problem did not reproduce.
![スクリーンショット 2024-04-24 20 29 58](https://github.com/WordPress/gutenberg/assets/2771396/6dffb184-c0c7-46d5-b623-c32487cde4ee)

**Comment by Supportic** [comment]
@mt8 true, tested it
