### ISSUE TITLE
Name of custom font-size is not properly displayed

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#51058]
### Description

When I have only so a small amount of custom font sizes, the selection panel will be displayed instead of a drop down.
In that selection, the name of the font sizes starts with "S", then "M" and so on, instead of the proper name.
The Tooltip shows the correct name though.

### Step-by-step reproduction instructions

1. Create custom font size
2. See wrong worded font names.

### Screenshots, screen recording, code snippet

<img width="270" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/163dddee-0473-417b-81cd-eca810e7105d">

<img width="550" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/fe303bea-77a8-4356-a967-7831d9e2e81b">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@hanneslsm 
Thanks for the report.

I would like to close this issue as I think it is the same as #44245. If you have any better ideas, please feel free to comment on #44245.
