### ISSUE TITLE
Enabling lightbox on images in a Gallery block breaks the gallery layout

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#51068]
### Description

Enabling the new lightbox behavior on Image blocks inside of a Gallery block breaks the gallery's layout. 

### Step-by-step reproduction instructions

1. Create a Gallery with 2+ images
2. Enable the lightbox behavior for each image
3. Set the Gallery block to have two columns
4. Save and view the front end, notice that the Gallery layout is not correctly applied. This is because there is now an extra `div` around each `figure`.

### Screenshots, screen recording, code snippet

**Editor:** 
<img width="1683" alt="image" src="https://github.com/WordPress/gutenberg/assets/4832319/355e2dfe-5141-4d34-b018-aa712ca4c4cb">

**Front end:** 
<img width="1685" alt="image" src="https://github.com/WordPress/gutenberg/assets/4832319/211709f1-39a5-43b5-afdd-399984ce1e30">

### Environment info

- WordPress 6.2
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
cc @luisherranz

**Comment by luisherranz** [comment]
Thanks @ndiego. I was worried that extra `div` would cause some issues 😄

@artemiomorales, what do you need to get rid of it? Can you place the directives directly in the `figure`? Or is it needed for CSS?

**Comment by artemiomorales** [comment]
@luisherranz I think it's possible to get rid of it. But to do so, we'd need to use the Tag Processor to place the directives directly on the `figure`, then do some hefty parsing and processing of the `figure` to set the `wp-lightbox-overlay` as a child, which seems potentially brittle.

Here is the lightbox markup; the `figure` HTML is contained within the `$body_content` and `$content`:

```html
<div class="wp-lightbox-container"
	data-wp-island
	data-wp-context='{ "core": { "image": { "initialized": false, "lightboxEnabled": false } } }'>
		$body_content
		<div data-wp-body="" class="wp-lightbox-overlay"
			data-wp-bind.role="selectors.core.image.roleAttribute"
			aria-label="$dialog_label"
			data-wp-class.initialized="context.core.image.initialized"
			data-wp-class.active="context.core.image.lightboxEnabled"
			data-wp-bind.aria-hidden="!context.core.image.lightboxEnabled"
			data-wp-bind.aria-modal="context.core.image.lightboxEnabled"
			data-wp-effect="effects.core.image.initLightbox"
			data-wp-on.keydown="actions.core.image.handleKeydown"
			data-wp-on.mousewheel="actions.core.image.hideLightbox"
			data-wp-on.click="actions.core.image.hideLightbox"
			>
				<button type="button" aria-label="$close_button_label" class="close-button" data-wp-on.click="actions.core.image.hideLightbox">
					$close_button_icon
				</button>
				$content
				<div class="scrim" style="background-color: $background_color"></div>
		</div>
</div>
``` 

And by the time the lightbox logic runs inside of the `render_callback`, the `figure` HTML has already been generated. We receive it inside of `$content`:

```php
function render_block_core_image( $attributes, $content ) {
	$processor = new WP_HTML_Tag_Processor( $content );
	/// ... Lightbox code continues here
}
```


Options:
1. Is it possible to modify the figure HTML further up the chain? That could be an option.
2. We could roll our own solution to process the HTML using a combination of regexes and Tag Processor logic.
3. We could wait until the HTML Processor is created at some point in the future and/or help develop the HTML Processor with this use case in mind.
4. I believe the intent is to incorporate the lightbox with the gallery block anyway, so perhaps we can accept this as a known limitation for now and then fix it all at once when the time comes.

I'm inclined to take option 4 and even start exploring solutions for the lightbox gallery relatively soon.

Thoughts?

**Comment by SantosGuillamot** [comment]
Asking from a lack of knowledge: cannot we just use the Tag Processor to add the directives to the figure parsing the `$content`?

I mean at [this point](https://github.com/WordPress/gutenberg/blob/a3a63c111aad8cc7be2cf77c6cb525fe6e0d7baa/packages/block-library/src/image/index.php#L60) adding something like this:

```php
$content = $processor->get_updated_html();
$w = new WP_HTML_Tag_Processor( $content );
$w->next_tag(
	array(
		'tag_name'   => 'FIGURE',
	)
);
$w->add_class( 'wp-lightbox-container' );
$w->set_attribute( 'data-wp-island', '' );
$w->set_attribute( 'data-wp-context', '{ "core": { "image": { "initialized": false, "lightboxEnabled": false } } }' );
$content = $w->get_updated_html();
```

Then the HTML returned could remain the same and just remove the parent `<div>`:

```HTML
<<<HTML
$body_content
<div data-wp-body="" class="wp-lightbox-overlay"
    data-wp-bind.role="selectors.core.image.roleAttribute"
    aria-label="$dialog_label"
    data-wp-class.initialized="context.core.image.initialized"
    data-wp-class.active="context.core.image.lightboxEnabled"
    data-wp-bind.aria-hidden="!context.core.image.lightboxEnabled"
    data-wp-bind.aria-modal="context.core.image.lightboxEnabled"
    data-wp-effect="effects.core.image.initLightbox"
    data-wp-on.keydown="actions.core.image.handleKeydown"
    data-wp-on.mousewheel="actions.core.image.hideLightbox"
    data-wp-on.click="actions.core.image.hideLightbox"
    >
        <button type="button" aria-label="$close_button_label" class="close-button" data-wp-on.click="actions.core.image.hideLightbox">
            $close_button_icon
        </button>
        $content
        <div class="scrim" style="background-color: $background_color"></div>
</div>
HTML;
```

Wouldn't an approach similar to this work? I guess it would also need some CSS changes if the parent `div` is removed.

_**EDIT: Oh okay, I just realized that we are missing a wrapper and that can be an issue. I think I understand your point now better.**_

Maybe we can use something like the following and just return $body_content?

```php
$body_content = preg_replace( '/<\/figure>/', $lightbox_html . '</figure>', $body_content );
```

**Comment by gziolo** [comment]
> I was worried that extra div would cause some issues 😄

It's also worth noting that everything works fine in the block editor because there is no wrapping `div`. I'm sure there are more features that won't work as expected because existing CSS styles assume that the HTML tag with the `wp-block-image` class is the most outer element of the block. Example would be the block alignment set to `left`.

The editor:

<img width="924" alt="Screenshot 2023-05-30 at 10 51 05" src="https://github.com/WordPress/gutenberg/assets/699132/636c6130-adc8-4890-859e-298f17e57750">

Frontend without the lightbox enabled:

<img width="1073" alt="Screenshot 2023-05-30 at 10 51 54" src="https://github.com/WordPress/gutenberg/assets/699132/d88a49e0-6c84-45dd-8711-d919be2466a6">

Frontend with the lightbox enabled:

<img width="1032" alt="Screenshot 2023-05-30 at 10 52 30" src="https://github.com/WordPress/gutenberg/assets/699132/c170d904-7edd-4bfd-b1a1-6a974ae55d5e">

---

When you apply more styling it becomes even more broken.

Editor:

<img width="801" alt="Screenshot 2023-05-30 at 10 58 39" src="https://github.com/WordPress/gutenberg/assets/699132/ebcdbfd0-a305-422e-a596-97c805355fb4">


Frontend:

<img width="493" alt="Screenshot 2023-05-30 at 10 58 49" src="https://github.com/WordPress/gutenberg/assets/699132/81ab3576-c666-467c-bc18-ee47e1677cf6">

---

Full-width align doesn't work as expected, too.

Editor:

<img width="1537" alt="Screenshot 2023-05-30 at 11 00 39" src="https://github.com/WordPress/gutenberg/assets/699132/922eaa6e-cb27-407c-b3ba-acb5d08ed5e5">

Frontend:

<img width="1814" alt="Screenshot 2023-05-30 at 11 01 36" src="https://github.com/WordPress/gutenberg/assets/699132/99ccb7c0-6d74-4378-b5dd-60f03228ad96">

**Comment by luisherranz** [comment]
> Maybe we can use something like the following and just return $body\_content?

```html
$body_content = preg_replace( '/<\/figure>/', $lightbox_html . '</figure>', $body_content );
```

This is what I was thinking as well, although I have the impression that we already tried that 🤔

Anyway, is this worth a try, @artemiomorales?

**Comment by artemiomorales** [comment]
@luisherranz @SantosGuillamot 

Sure thing, [pull request created here](https://github.com/WordPress/gutenberg/pull/51089).

It works as far as I can tell. I suppose it should work for most use cases, though would break if users say include the string `</figure>` in their caption.

**Comment by artemiomorales** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/51089
