### ISSUE TITLE
Patterns with a Group block wrapper can be inserted in a Navigation block

### ISSUE THREAD

**Issue by tyxla** [WordPress/gutenberg#51086]
### Description

We recently encountered an instance of a site where a block pattern, containing a Navigation block inside a Group was inserted inside a navigation block. Because that pattern included a navigation block itself, rendering it resulted in an infinite loop.

Unfortunately, I'm unable to reproduce it, but I wonder if anyone has an idea of how this came to be.

I only have the end result - a block pattern that contains a navigation, as an inner block inside a navigation block. 

Related to #51087

### Step-by-step reproduction instructions

I'm not sure what the steps are. I'm looking for anyone who can think of a way to insert a block pattern (one that contains a navigation block) inside a navigation block and break it that way. 

When I try to insert the "Header with Button" pattern from the Yuga theme in the navigation block, it gets inserted outside so I'm unable to reproduce it myself. 

### Environment info

- WordPress 6.2, Gutenberg v15.8.1, [Yuga](https://wordpress.com/theme/yuga) theme.
- All browsers
- All OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by talldan** [comment]
The navigation block has some code to prevent infinite loops (`RecursionProvider`, `useHasRecursion`), and from my testing it seems to work.

I added an inner navigation block inside a pattern inside a group into a parent navigation block. Here's how:
1. Create the pattern with a group and navigation block inside the group and save it
2. Switch to code editor and copy the html for the wp:block
3. Go to the side editor > navigation and edit the navigation menu (ideally the same one that your pattern shows)
4. Switch to code editor and paste in the group block

The result of this was that the inner navigation block wasn't visible at all, I guess some CSS combination causes that.

If I inspect the HTML, it looks like the recursion is properly prevented as the inner navigation block outputs this ("Block cannot be rendered inside itself"):
![Screenshot 2023-10-04 at 4 38 37 pm](https://github.com/WordPress/gutenberg/assets/677833/e22d302a-1916-47d4-9a8b-d4466f32788f)

**Comment by getdave** [comment]
I'm going to close this as I think it's a very unlikely scenario and also as @talldan says recursion is prevented. If anyone disagrees feel free to reopen.
