### ISSUE TITLE
Proposal: Rename the `[Priority] OMGWTFBBQ` label

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#51107]
## What problem does this address?
This GitHub repository currently has a `[Priority] OMGWTFBBQ` label that, according to [the documentation](https://developer.wordpress.org/block-editor/contributors/triage/#general-triage-process), is used for: 

> Major issues that are causing failures and are reported frequently. Typically, these are issues that are critical because they break important behavior or functionality. An example might be, “Unable to remove a block after it is added to the editor”.

The label has only been used a [few times](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BPriority%5D+OMGWTFBBQ%22), but having a label reserved for extreme circumstances is great. That said, the name of the label `OMGWTFBBQ` is not so great. 

The acronym is a meme and does not make it clear what this label is supposed to be used for, especially for non-English contributors who may not be aware of the component English acronyms.  

## What is your proposed solution?

Let's correct this and rename the label to something like: 

- `[Priority] Urgent`
- `[Priority] Critical` **(My vote)**

Once a new name is chosen, the [Triage documentation](https://developer.wordpress.org/block-editor/contributors/triage/#general-triage-process) needs to be updated accordingly.

**Comment by ryanwelcher** [comment]
Agree 100% that while it's a fun label, it's not inclusive to all. 
My vote is for `[Priority] Critical`

**Comment by justintadlock** [comment]
For historical reasons, I dislike getting rid of these little things altogether. A similar priority has been in Core Trac for ages: https://core.trac.wordpress.org/query?priority=highest+omg+bbq

But I definitely see the need for it to be clear, so it's worth changing for that reason alone. "Critical" feels more like a severity rather than a priority (so does "OMGWTFBBQ"). "Highest" would be the priority.

Maybe consider keeping the fun part of that while still making it useful? Maybe `[Priority] Highest (OMGWTFBBQ)`?

**Edit:** If nothing else, `[Priority] Highest` would be consistent with the other priority labels.

**Comment by ndiego** [comment]
@justintadlock are you able to share the historical context? I figured there was some, but I had to Google what OMGWTFBBQ meant and I consider myself fairly enfranchised 😅 

If we do keep it in some fashion, it would be good to explain what it means in the context of WordPress core.

**Comment by justintadlock** [comment]
I have no idea when it was added and what the thinking was, so I cannot give any real context. I just remember it being around for as long as I can remember. 

I assume it was just some playful usage of pretty common internet slang at the time. Plus, it aligns with the BBQ culture in the WordPress space (which may not be as much of a thing now that the community has grown so large). The "WTF" bit also isn't a part of the label in Trac.

To be extra clear, I'd be OK with change. I just wanted to make sure this was noted before doing so. If we do change it, I think it makes sense to make it consistent with the other [Priority] labels: Low, Normal, High, **Highest**.

**Comment by mburridge** [comment]
Whilst acknowledging that it might not be obvious to those for whom English is a second language `OMGWTFBBQ` does serve the purpose of drawing attention to itself in a way that 'highest' or 'critical' may not. I think the intention behind this label was precisely that, to draw attention to something that is urgent or needs immediate attention. The ALL CAPS helps with this too.

It's possible to include emojis in labels so perhaps we could remove the non-inclusive acronym and replace it with a suitable emoji. As emojis aren't commonly used in labels that in itself would draw attention to something that, erm..., needs attention. It would also retain the 'fun' or 'playful' element. e.g.:

<img width="996" alt="image" src="https://github.com/WordPress/gutenberg/assets/20643925/054a97c1-5dd4-45aa-b370-f17b8e3da712">

**Comment by ndiego** [comment]
In light of the discussion here, and the historical context in Trac, which uses the label [`highest omg bbq`](https://core.trac.wordpress.org/query?priority=highest+omg+bbq), what if the label is updated to `[Priority] Highest (OMGBBQ)`. This keeps the historical context while making it clearer with the "Highest" prefix and removes the unneeded "WTF". 

If we all agree on this approach, I will also add some info about the historical context to the [Contributor Guide](https://developer.wordpress.org/block-editor/contributors/triage/).

**Comment by ndiego** [comment]
Thanks for the feedback everyone. I will move forward with updating the label to `[Priority] Highest (OMGBBQ)`. I will add a PR later for updating the Triage documentation with a better explanation of when and how this label should be applied along with some historical context.
