### ISSUE TITLE
contentSize and wideSize vs Editor Wide width and Full width not respected in the frontend with theme.json settings.layout

### ISSUE THREAD

**Issue by eirichmond** [WordPress/gutenberg#51109]
### Description

I'm not sure if this is a known issue. But, when setting theme.json settings.layout with specific contentSize and wideSize the theme doesn't respect the setting in the frontend, nether are the editor alignment options respected if changed to Wide or Full width.

If I change the theme.json to the following I would expect the setting to be respected in the Editor and the Frontend but its only working in the editor.
```
"settings": {
        "appearanceTools": true,
	"layout": {
		"contentSize": "650px",
		"wideSize": "1200px"
	}
}
```

In the frontend the content width is 100% width even though the CSS is showing the global setting as follows:

```
body {
  margin: 0;
  --wp--style--global--content-size: 650px;
  --wp--style--global--wide-size: 1200px;
}
```

Also when a Group Block is added, I would expect the alignment Wide or Full to be respected in the Editor and the Frontend but its only working in the editor.

### Step-by-step reproduction instructions

With a new block theme created...

1. Set theme.json settings.layout with the following:

```
{
    "$schema": "https://schemas.wp.org/trunk/theme.json",
    "version": 2,
    "settings": {
        "appearanceTools": true,
	"layout": {
	    "contentSize": "650px",
	    "wideSize": "1200px"
        }
    }
}
```

2. Create a page/post.
3. Add a group block and set alignment to "Wide width" setting CONTENT to 900px and WIDE to 1200px.
4. Nest a paragraph block in the same group block with some greek text.
5. Add another group block and set alignment to "Full width" setting CONTENT to 900px and WIDE to 1200px.
6. Nest a paragraph block in the same group block with some greek text.
7. Save the page/post and view in the frontend.

### Screenshots, screen recording, code snippet

View in the Editor
![editor](https://github.com/WordPress/gutenberg/assets/525490/66e4dd7c-075d-49ee-9bf7-a912cd141463)

View in the Front End
![frontend](https://github.com/WordPress/gutenberg/assets/525490/fcd54fc2-1e06-49ff-960f-3ba53adb98d9)

### Environment info

WordPress Version 6.2.2,
Gutenberg Version 15.8.1
Firefox 113.0.1
Mac OS 13.3.1 Ventura

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@eirichmond

Thanks for the report.  Can I confirm two points about this?

- Even in default themes such as Twenty Twenty Three, are `contentSize` and `wideSize` not reflected in the front end?
- If you are developing your own theme, is it a block theme or a hybrid theme (classic theme with theme.json)?

**Comment by StephanLoewe** [comment]
Same here

**Comment by jordesign** [comment]
Just pinging @eirichmond  once again to see if you are able to provide the further information requested above?

**Comment by madebygarret** [comment]
Hey there, @jordesign & @eirichmond 

Just to follow this up, I can confirm that, on hybrid themes, the frontend does not render settings.layout properly.

When declaring `contentSize` & `wideSize` in the theme.json, everything works as expected from the editor's side, but **alignments** and `max-width` is never properly rendered on the front.

Do you have any idea about how to properly bring this to the theme.json when working on hybrid themes?

Many thanks!

**Comment by t-hamano** [comment]
> Do you have any idea about how to properly bring this to the theme.json when working on hybrid themes?

I understand that if it is NOT a block theme, layout on the front end is something that should be addressed on the theme side. For more information, see [this comment](https://github.com/WordPress/gutenberg/pull/39594#issuecomment-1073614564) and [this article](https://make.wordpress.org/core/2021/06/29/on-layout-and-content-width-in-wordpress-5-8/).

**Comment by madebygarret** [comment]
It happened the same to me, since I presuppose alignments should work the same as block themes, but it makes a lot of sense for **hybrid and classic themes to require a proper CSS specificity in order to target blocks within theme's custom markups**.

Many thanks for the details and help, @t-hamano !

**Comment by jordesign** [comment]
It sounds to me based on the discussion above - we can close this issue as it is resolved by including the CSS with the correct specificity for Hybrid themes - so I'll close this issue.
