### ISSUE TITLE
Adding a header to the Table of Contents block

### ISSUE THREAD

**Issue by jenxi** [WordPress/gutenberg#51129]
## What problem does this address?
There should be an option to add a header to the TOC. Adding a header before the TOC adds the heading to the TOC list.

## What is your proposed solution?
Have an option for the TOC block to have a header that is not counted as a heading in the TOC.

**Comment by Thelmachido** [comment]
Thanks for opening the issue. 

This request came through forums:
[](https://wordpress.org/support/topic/creating-a-header-for-the-table-of-contents/)

I am going to add the necessary tags.

**Comment by Mamaduka** [comment]
Closing this in favor of #52378, feel free to join the discussion there.
