### ISSUE TITLE
Direct URL to the style book

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#51121]
## What problem does this address?
When creating custom themes, I'm editing the theme.json.
Often times I am checking how those changes look in the editor. For that I'm using the Style Book - however I have to navigate to it every time I refresh the page to load the newest changes from my theme.json.
To make this experience smoother, it'd be great if I could directly open the Style Book, probably by using a specific URL.

**Comment by ramonjd** [comment]
I like this idea. I suppose it'd would have to be activated via URL param. 

I'm thinking a couple of things:

- the site editor should automatically open the global styles sidebar with the URL path contains `/wp_global_styles`. At the moment it doesn't.
- Then, via another param or a subroute of `/wp_global_styles`, the style-book could be triggered to open

Something like this:

https://github.com/user-attachments/assets/fdc598d1-75b8-46ce-b132-4755de2706d1

And the very dodgy code: https://github.com/WordPress/gutenberg/pull/66186

However, we'd meed to think about state:  the url param should update as style book is closed. Also whether the URL should be in the navigation history.

It makes me think that global styles needs its own editor view entirely, or perhaps some modal or other separate UI from the template/post editor.

**Comment by ramonjd** [comment]
Here's something that might influence things:

- https://github.com/WordPress/gutenberg/pull/65619

**Comment by richtabor** [comment]
> Here's something that might influence things:

I came to say the same. 

We already have `wp-admin/site-editor.php?path=%2Fwp_global_styles`, and with https://github.com/WordPress/gutenberg/pull/65619 in the works I don't think we'll need (or should commit to maintaining) a direct link for style book. /wp_global_styles will be a more meaningful and direct styling experience. I'll mark this as not planned for now.
