### ISSUE TITLE
Image: Vertical image from URL cut when displayed in the lightbox

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#51125]
### Description

When using the lightbox behavior for the Image block that contains a vertical image inserted from URL, it displays correctly on the front end. However, when the lightbox gets opened, if the image is tall, then it gets cut on both the top and bottom of the image.

### Step-by-step reproduction instructions

1. Activate the experiment that enables Interactivity API and Behaviors.
2. Go to the post editor.
3. Insert an image with a much bigger height than width using `Insert from URL` option, for example: 
https://pd.w.org/2023/05/7866470b6f485ce37.96403804.jpg.
4. In the advanced settings for the Image block, activate the lightbox behavior.
5. Publish the post.
6. Navigate to the post on the front end.
7. Open the lightbox and check whether the image is correctly displayed.

### Screenshots, screen recording, code snippet

Vertical image in the block editor:

![Screenshot 2023-05-30 at 14 50 27](https://github.com/WordPress/gutenberg/assets/699132/85ac9f8a-0aa1-42dc-8260-82aec74df01d)

Vertical image in the lightbox on the frontend:
![Screenshot 2023-05-30 at 14 50 40](https://github.com/WordPress/gutenberg/assets/699132/50f0ba55-9b54-4b32-8c5a-09f06b519f3b)

### Environment info

- WordPress 6.2, Gutenberg latest (`trunk`)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
I was able to reproduce it for an [uploaded image](https://github.com/WordPress/gutenberg/assets/699132/e5f1368c-4428-4da4-b6d2-9447b3cf75d8).

I set the image size to `Large`:

<img width="1793" alt="Screenshot 2023-05-31 at 12 40 12" src="https://github.com/WordPress/gutenberg/assets/699132/d9451442-a75c-47ca-b2a4-62fe6ddda9e5">

View on the site:

<img width="1660" alt="Screenshot 2023-05-31 at 12 39 59" src="https://github.com/WordPress/gutenberg/assets/699132/adda7abd-0796-4760-a13d-555f97f55acc">

View with the lightbox opened:

<img width="1918" alt="Screenshot 2023-05-31 at 12 39 39" src="https://github.com/WordPress/gutenberg/assets/699132/90807f53-1e0d-431e-b9d6-fb9318fcd23c">

**Comment by SantosGuillamot** [comment]
If I am not mistaken this could be solved using `max-height: 100%` and `max-width: 100%` (or something similar) [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/image/style.scss#L233). I can work on a pull request for that.
