### ISSUE TITLE
Image: The lightbox behavior not applied when the image is linked

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#51127]
### Description

I might be a design decision never to display the lightbox when the image from the Image block is wrapped with a link. However, at the moment, the option is still visible in the editor's UI even when it won't be used on the frontend.

### Step-by-step reproduction instructions

1. Activate the experiment that enables Interactivity API and Behaviors.
2. Go to the post editor.
3. Insert an image in the post.
4. In the advanced settings for the Image block, activate the lightbox behavior.
5. From the block toolbar select `Insert link` option.
6. Choose any option that wraps the image with a link, for example: `Media File`.
7. Publish the post.
8. Navigate to the post on the front end.
9. Click on the image and observe that the link opens a new page, and the lightbox never shows up.

### Screenshots, screen recording, code snippet

**View in the editor:**

<img width="1034" alt="Screenshot 2023-05-31 at 11 56 29" src="https://github.com/WordPress/gutenberg/assets/699132/9e9f46fe-e977-4360-892f-01c5b5355fa1">

---

**View on the frontend:**

<img width="420" alt="Screenshot 2023-05-31 at 11 57 49" src="https://github.com/WordPress/gutenberg/assets/699132/b9e138f1-a1b0-446a-9e72-d8cebcab5962">

### Environment info

- WordPress 6.2, Gutenberg latest (trunk)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by artemiomorales** [comment]
Ok, my first inclination would be to render the Behaviors dropdown inert and add a message stating, "Lightbox will be disabled while the image contains a link."

On the technical side, to do this, we would need to detect the image block's `linkDestination` to override the UI defined in [packages/block-editor/src/hooks/behaviors.js](https://github.com/WordPress/gutenberg/blob/release/15.9/packages/block-editor/src/hooks/behaviors.js). I'm not sure how to do that, but can begin exploring. Any pointers appreciated!

Pinging @jasmussen @SaxonF @jameskoster for design feedback on this approach.

**Comment by artemiomorales** [comment]
I was looking at the [original issue](https://github.com/WordPress/gutenberg/pull/49621#issuecomment-1508200045), and noticed that @jasmussen already expressed a way to handle this:

> ...it could be grayed out and have help-text that says something like "The lightbox behavior is disabled for linked images."

Barring any additional feedback, will go ahead with that approach then.
