### ISSUE TITLE
Twenty Ten - Table block having issue with font size on editor side.

### ISSUE THREAD

**Issue by iamrealfarhanbd** [WordPress/gutenberg#51120]
### Description

You can able to see the change on the front side but the editor side have no change even after applying a different style font size.
I have attached a video for better understanding.
Video URL:- https://video.drift.com/v/abqA2x1QjxW/

### Step-by-step reproduction instructions

Steps to reproduce the issue:-
Activate Twenty Ten Theme.
Choose Table block.
Add some text to the table.
Now change the font size and check it on both the side editor and user side.
You can able to see the change on the front side but the editor side have no change even after applying a different style font size.

### Screenshots, screen recording, code snippet

https://video.drift.com/v/abqA2x1QjxW/

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@iamrealfarhanbd This looks like an issue with the Twenty Ten theme itself. It can't be fixed within the Gutenberg project.

I'd recommend making a ticket on core trac about this as bugs with bundled themes are tracked there - https://core.trac.wordpress.org/.

**Comment by iamrealfarhanbd** [comment]
Hello @talldan ,
Although I had already created the ticket, it was suggested to me that I should create the ticket here as well,  You can find my ticket here: https://core.trac.wordpress.org/ticket/58362
screenshot: https://prnt.sc/IWhLPdbLvS9f
