### ISSUE TITLE
Global styles color palette gets overwritten by unwanted block level color palette.

### ISSUE THREAD

**Issue by codeeater** [WordPress/gutenberg#51124]
### Description

We use a block theme and site editing with the latest versions of WP and Gutenberg plugin.
Our base theme is Twenty Twentythree and we have generated a child theme from it. The theme.json of the child theme only contains some additional font families, nothing else.
Everything is set to use the default style variation.

We have changed the color palette (theme values + additional custom values) inside of the Styles editor in Gutenberg.
Going to the individual block and trying to change a color, would show the correct color picker (displaying correct theme colors and custom colors). Everything works as expected.

But: we see 3 blocks that are not using the custom palette - instead, when I go to the block level Styles settings and try to change a color there, it shows a color picker with the wrong theme colors (from the default style variation) and no custom colors. I see no way in the UI to reset this (like I would reset custom paddings for example).
Also, when I choose an individual block of the problematic type inside a post, it will also show the wrong color palette in the style panel.

It looks as if the color palette is overwritten on block Style level - but this is not a supported feature of Twenty Twentythree AFAIK and not editable.

### Step-by-step reproduction instructions

Unfortunately we don't know how we ended up here.

I found out about this, because elements on the post where showing wrong colors. Then I saw in Chrome dev tools that there are class selectors with CSS color variables that override the global color variables, investigate where this is coming from and simply couldn't find a connection to the UI in the theme editor.

Just a theory, but: it's possible that I went into Styles > Blocks > Columns in the very beginning, when we hadn't customized theme colors and custom colors yet. Then, the default colors somehow got stuck on those block styles and now they are not going away/updating regardless of what I do in Styles.

### Screenshots, screen recording, code snippet

Unwanted markup:
<img width="487" alt="Bildschirmfoto 2023-05-31 um 11 46 51" src="https://github.com/WordPress/gutenberg/assets/338606/8e93b0c1-47fa-4cd1-badc-e9d32eb93933">

Wrong color picker for "Columns" block in Styles:
<img width="553" alt="Bildschirmfoto 2023-05-31 um 11 46 31" src="https://github.com/WordPress/gutenberg/assets/338606/a805bb5d-fb46-443b-b523-3c2dc3e90f5b">

Correct color picker for most blocks in Styles:
<img width="570" alt="Bildschirmfoto 2023-05-31 um 11 45 54" src="https://github.com/WordPress/gutenberg/assets/338606/21e28a09-c179-4214-8d5c-186519cd66b2">

Custom color palette in global Styles:
<img width="284" alt="Bildschirmfoto 2023-05-31 um 11 45 35" src="https://github.com/WordPress/gutenberg/assets/338606/71db3142-f839-47bc-8cdc-b4245d159c96">

### Environment info

Gutenberg 15.8.1
WordPress 6.2.2
Twenty Twentythree

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
> But: we see 3 blocks that are not using the custom palette - instead, when I go to the block level Styles settings and try to change a color there, it shows a color picker with the wrong theme colors (from the default style variation) and no custom color

Hi @codeeater are you able to advise which blocks are being affected exactly?

**Comment by codeeater** [comment]
It happened for "Columns" + "Terms Description" + "Group" - but I think this is arbitrary: it simply happened because at some point in the past I may have gone into the Styles > Columns/Terms/Group settings, maybe even changed something, reset again (but not the coloring).
The other blocks are not affected (my hypothesis), because I never went there - and it's not happening now, because the bug is related to some edge case or earlier version of Gutenberg or esle.

**Comment by codeeater** [comment]
To be more precise: something made the theme editor store the color palette on block Styles level in the past. Now I can't remove it or get it to update to the latest global Styles colors.

**Comment by youknowriad** [comment]
So there are actually two issues here:

1- If a theme or a previously edited global styles had edited "color palettes" per block, it's not possible to do so anymore because we removed that piece of UI from the editor.

2- It's impossible to "reset" the color palette entirely for a block (remove it from a block basically and just use the global one)

I think we need some designs on how to solve these. cc @jasmussen @SaxonF

**Comment by codeeater** [comment]
Thanks @youknowriad , that sounds about right. Although in my case, I think the color palette on the affected blocks got there because of a bug or an edge case - not because it was possible to edit these through the UI in the past (or because I switched themes). Something under the hood attached it wrongfully.
But what you describe would solve the problem.

Any advice for a quick fix for the time being, until there's a UI? Can I advise my WP devs to remove these block level palettes somewhere in the database for example?

**Comment by youknowriad** [comment]
If you know all the changes that have been made on the UI manually, you can click the "Styles actions" (three dots) menu in the global styles sidebar and "reset to defaults" which will reset all saved global styles, and then you can apply your desired changes again. Is this possible for you?

**Comment by jasmussen** [comment]
Thanks for the ping. If I understand this right, the fact that you were able to edit color palettes per block in the past, that left remnants if you actually did so, which now that the UI is gone you cannot delete those palettes. Is that right?

If yes, then it's worth reiterating the motivation for removing that palette UI, which was that it was very confusing to see that palette in the case of individual blocks, not realizing that you weren't editing the global palette. The fact that it left remnants is unfortunate. 

The motivation kind of remains, unless there's a per-block-palette use case that I'm missing. If we can keep with the motivation and there isn't an ideal use case, then, is there a way to migrate those palettes in a plugin upgrade? I.e. a script that looks for those remnants and deletes them? Can a reset be performed to Riad's suggestion? Or can you temporarily downgrade to an older version of the plugin and remove the palette customizations? Can we surface the old palette _only_ in the case where previous palette data is detected?

If there's a use case, let me know.

**Comment by codeeater** [comment]
@jasmussen
>  Thanks for the ping. If I understand this right, the fact that you were able to edit color palettes per block in the past, that left remnants if you actually did so, which now that the UI is gone you cannot delete those palettes. Is that right?

Yes and no: "hat you were able to edit color palettes per block in the past" - I don't think we consciously did this. We have only recently started to use the whole block theme/site editing features and I was not even aware that you could edit palettes on block level. Maybe it simply happened this way, maybe it was some bug that created those block color palettes.

>If yes, then it's worth reiterating the motivation for removing that palette UI, which was that it was very confusing to see that palette in the case of individual blocks, not realizing that you weren't editing the global palette. The fact that it left remnants is unfortunate.

I can confirm from a user perspective, that I see little reason overwrite color palettes on block level. Removing the UI was probably a good idea.

>Can a reset be performed to Riad's suggestion?

I think we did too many wanted changes to easily reset to defaults and then reproduce the wanted stuff.
What I could check, is exported all changes and incorporating them into the child theme (=code) instead of the customizations in the UI. I planned this in the long run anyway: "prototype and stabilize" custom styles in Gutenberg, then move everything into code - as far as I know, this is possible, manifest changes to theme in theme.json of the child theme - can you confirm that?

> Or can you temporarily downgrade to an older version of the plugin and remove the palette customizations?

If you could give me a hint in which version the removed UI was still there, I'm happy to try that approach.
All the other solutions you suggested and not strictly necessary for me: I ran into a one time problem - I don't think I need a permanent solution. I only came here, because I thought it was a bug - not a remnant of the UI removal.
That would be up to you to decide if more people might run into this and you need a migration path.

**Comment by jasmussen** [comment]
> If you could give me a hint in which version the removed UI was still there, I'm happy to try that approach.

@youknowriad do you have a way to track down the PR that removed it, and see which plugin version that corresponded with? This might be the easiest fix for now.

**Comment by youknowriad** [comment]
Yes, I think it was Gutenberg 15.8 that introduced the UI change.

**Comment by jasmussen** [comment]
Thanks. So it seems like it should be feasible to try and download version 15.7 [from here](https://wordpress.org/plugins/gutenberg/advanced/) and see if that helps.

**Comment by codeeater** [comment]
@jasmussen @youknowriad Hi guys! Let me first say, that I appreciate your fast responses!
Now, that was at least partially successful:
- I asked for a roll back to Gutenberg 15.7 on our staging environment
- I see that the option to change color palettes on block styles reappeared
- I went into all color settings and reset them
=> the CSS color variable overrides disappeared from the markup 

But: there's still redundant font families, some spacing and some shadow variable definitions in the block selector (see screenshot). This is not as annoying as the colors, because they were not changed - so this is redundant CSS that should not be there, but it's the same as in the global definition.
No matter what I tried to follow the same approach here, I cannot reset the font families. I guess there's not "remove all customizations for this block" button, right? This is only available on the global level and would I mean I need to recreate any wanted customization, correct?

<img width="996" alt="image" src="https://github.com/WordPress/gutenberg/assets/338606/cfc1ff42-6ed3-4a4b-bd25-73335a952fef">

**Comment by codeeater** [comment]
friendly *ping* - any suggestions about how to get rid of the remaining unwanted font, spacing and shadow presets?

**Comment by jasmussen** [comment]
Glad the color palette thing worked. For the fonts aspect, I'm reaching the limitations of my knowledge around these behaviors. 

I would _imagine_ that if you install https://wordpress.org/plugins/create-block-theme/, use it to export the locally customized theme as a new theme, and then activate that, it might work. But be sure to keep some backups around and use the plugin with are. If that doesn't help, maybe you can get a more broad range of input in GH discussions: https://github.com/WordPress/gutenberg/discussions

**Comment by codeeater** [comment]
@jasmussen @youknowriad Hi guys, just I quick headsup: I needed to do some tweaking to other theme settings today - and the problem still exists. I can't roll back to the old Gutenberg plugin version to get rid of the outdated colors on block elements every time I change the global color palette... any idea how to push this forward? Any help is appreciated...
BTW We are now on Gutenberg 16.6.0 WP 6.3.1

**Comment by youknowriad** [comment]
@codeeater Here is what I can propose, there's no way at the moment to do what you want in the UI but you can maybe use some JS APIs to reset the block specific settings by running these in the browser console of the site editor:

```js
// This allows you to retrieve the "id" of the global styles entity you have to edit 
wp.data.select( 'core' ).__experimentalGetCurrentGlobalStylesId();
// You may have to run the above twice to get the real id

// Next you can retrieve the existing settings  (replace the id)
const settings = wp.data.select( 'core' ).getEditedEntityRecord( 'root', 'globalStyles', id ).settings;

// Next you have to update the settings (make the changes you want like resetting the "blocks" settings)
// The following keeps all the root level settings but resets the block specific ones without distrinction
const updatedSettings = { ...settings, blocks: {} };

// Apply the edits (replace the id)
wp.data.dispatch( 'core' ).editEntityRecord( 'root', 'globalStyles', id, { settings: updatedSettings } );
```

Once the above performed, you should be able to see your changes in the site editor. Last step is to actually save these changes, you can do using the regular "save" button.

**Comment by codeeater** [comment]
@youknowriad Thanks a lot - that helped to solve the issue!

**Comment by youknowriad** [comment]
Glad it worked out.
