### ISSUE TITLE
Column sizes a bit too narrow

### ISSUE THREAD

**Issue by jjchrisdiehl** [WordPress/gutenberg#5114]
## Issue Overview
Multi-columns create narrow text areas, leading to a less favorable layout

## Expected Behavior
Columns should be easy to work with and have enough space to provide a pleasant writing experience.

## Current Behavior
A user currently needs to edit within the constraints of the column's size in the editor, this can be somewhat difficult with more than two columns.

## Possible Solution
When a column is added it should only show an excerpt of the content of the column. When the column is selected it should open as a modal that allows the user to edit the column in a wider format tinymce window. 

## Screenshots / Video

How it is:
![columns](https://user-images.githubusercontent.com/16580129/36332968-637eb056-1342-11e8-9fd0-868acab17b3e.png)

How it could be:
![guten_columns](https://user-images.githubusercontent.com/16580129/36335602-1e346182-134f-11e8-94bd-0d5c1b387c54.gif)

**Comment by GlennMartin1** [comment]
Definately agree with the problem. 

The proposed solution may be fine, too. Seems like editing could be possible within the column; but presently it seems the column margins are too wide to accommodate that.

**Comment by StaggerLeee** [comment]
Columns, and tables, blocks need, have to, be given wide full-width same as cover image.

**Comment by mtias** [comment]
Yes, the UI for nested blocks has not been adjusted to account for the extra loss in padding introduced by block movers, etc, and it's pending design work.

**Comment by vladoa** [comment]
Guys, any update on this? Currently if I choose more than 3 columns, each column looks ridiculously narrow. If I choose 6 columns there is almost no space for the blocks within the columns.
What would be the easiest workaround or is there any fix coming up?

**Comment by vladoa** [comment]
`div[data-type="core/columns"] {
  max-width: 100%;
}`
Just as info, if anyone else encountered this problem. This has worked for me.
