### ISSUE TITLE
Proposal: Remove the `[Priority] Normal` label

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#51141]
## What problem does this address?
At some point the [`[Priority] Normal`](https://github.com/WordPress/gutenberg/labels?q=normal) label was added to the repo, but [according to the documentation,](https://developer.wordpress.org/block-editor/contributors/triage/#general-triage-process) this priority should not exist. By default, all issues/PRs are at normal priority, which makes this label redundant. 

> Note that it’s on purpose that no priority label infers a normal level.

## What is your proposed solution?
Remove the `[Priority] Normal` label and update [all issues/PRs](https://github.com/WordPress/gutenberg/issues?q=label%3A%22%5BPriority%5D+Normal%22+) that have this label.

**Comment by talldan** [comment]
It seems to be used a lot for native mobile issues - https://github.com/WordPress/gutenberg/labels/%5BPriority%5D%20Normal

cc @fluiddot

**Comment by richtabor** [comment]
I don’t use priority labels at all myself.

**Comment by fluiddot** [comment]
> It seems to be used a lot for native mobile issues - [ [Priority] Normal](https://github.com/WordPress/gutenberg/labels/%5BPriority%5D%20Normal)
> 
> cc @fluiddot

We try to tag all issues with a Priority label, as we consider the ones without it as untriaged. In any case, it would be interesting to review our triaging process for native mobile issues and try to align it with [General triage process](https://developer.wordpress.org/block-editor/contributors/triage/#general-triage-process).

Regarding [the current native mobile issues](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Mobile+App+-+i.e.+Android+or+iOS%22+label%3A%22%5BPriority%5D+Normal%22) with https://github.com/WordPress/gutenberg/labels/%5BPriority%5D%20Normal, we could review them and check that they are assigned to the [Mobile Apps board](https://github.com/WordPress/gutenberg/projects/46) to determine they are already triaged.

cc @twstokes

**Comment by ndiego** [comment]
Thanks for the clarification @fluiddot! I am in the process of auditing all labels and also updating the documentation around triaging issues. Since the label is actively being used to manage native mobile issues, let's keep it as is, but would you be ok with me adding a note on the description of the label that it should only be used for native mobile issues? I can also add a note in the triage docs about this. Let me know what you think!

**Comment by fluiddot** [comment]
> Since the label is actively being used to manage native mobile issues, let's keep it as is, but would you be ok with me adding a note on the description of the label that it should only be used for native mobile issues?

@ndiego Sure! Feel free to add a note to the label.

> I can also add a note in the triage docs about this. Let me know what you think!

I'd lean toward follow the same approach for native mobile issues and avoid using https://github.com/WordPress/gutenberg/labels/%5BPriority%5D%20Normal tag. In fact, I'd like to propose removing it from the current tickets. I'd love to hear feedback from @WordPress/native-mobile about this.

Depending on the decision, we might not need to update the docs.

**Comment by ndiego** [comment]
> I'd lean toward follow the same approach for native mobile issues and avoid using [[Priority] Normal](https://github.com/WordPress/gutenberg/labels/%5BPriority%5D%20Normal) tag. In fact, I'd like to propose removing it from the current tickets. I'd love to hear feedback from https://github.com/orgs/WordPress/teams/native-mobile about this.

I think this would be the ideal scenario for the project as a whole, but I don't want to mess with a system that is currently working for the team. So the decision is up to you all 💪

**Comment by twstokes** [comment]
Thanks @fluiddot for the ping! @ndiego we can adapt to the rest of the project and remove the normal tag. 👍

**Comment by ndiego** [comment]
@twstokes fantastic! Thank you for being so flexible 🙏

I will move forward with removing this label.
