### ISSUE TITLE
Can't add different blocks to columns

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#5115]
## Issue Overview
I can't add different blocks to columns. What is the point of a "Multi Column" block if we can't add different types of blocks to each column? How is this any different than the Text Columns block?

On top of this, the new interface is absolutely horrid! There's so many menus and dropdowns and toolbars. Boxes getting highlighted that you can't actually click in. Having to click multiple times in a block before the cursors will actually move into the block. You can't move blocks between columns. You've successfully made what was already a complicated interface, even worse.

![gutenberg-multicolumns](https://user-images.githubusercontent.com/2078245/36337180-a332cd16-13e4-11e8-88e3-e4a386ef9f08.gif)

## Steps to Reproduce (for bugs)
1. Insert Multicolumn block
2. try to add any other block other than a Paragraph block to one of the columns

## Expected Behavior
I expect to be able to add any block I want to any column

## Current Behavior
Can only add text to columns. This is no better than the text Column block

_Gutenberg 2.2
Firefox Quantum 58.0.2 (64-bit)_

**Comment by karmatosed** [comment]
Yes right now the content is limited, that's why it's an experimental block. It's the first step on adding all types. Because this is known for now going to close this issue, as it moves beyond experimental - it took a lot to get where we are - we can add more.

**Comment by youknowriad** [comment]
You can add any type of block to the columns using the `/` command or the inserter at the top of the editor. The UI will be improved over time.

**Comment by mtias** [comment]
> I can't add different blocks to columns.

Yes you can. You can see it on the release video: https://cloudup.com/cVu9gA3wGEI

**Comment by maddisondesigns** [comment]
Ok, so I worked out how you can add other blocks, but this UI is ridiculously unintuitive!

Why does it automatically put in a paragraph block all the time? If I add a block using the Inserter menu at the top, I end up with a new block, plus the original Paragraph block that I don't want.

![gutenberg-multicolumns2](https://user-images.githubusercontent.com/2078245/36347486-2987d09c-14ac-11e8-998e-6c3fdae2757d.gif)

How do I add a Column block, with the first block in Column 1 being something other than a Paragraph block, using the Inserter menu?

**Comment by mtias** [comment]
> If I add a block using the Inserter menu at the top, I end up with a new block, plus the original Paragraph block that I don't want.

@maddisondesigns This is just a missing feature (or bug, depending how you view it). For one, the inserter should replace the paragraph block if it's empty. That's what the "experimental" seeks to imply on the block title, that there are a bunch of interactions that need refinement.
