### ISSUE TITLE
Font Picker: Refine, show font preview, and load only active fonts from library

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#51151]
Extracted from #45271.

The font picker will show fonts that are registered in theme.json. As detailed in #45271, that means fonts added to your library which are _active_.  The font picker can look like this:

<img width="1520" alt="Selecting fonts in Post Editor" src="https://github.com/WordPress/gutenberg/assets/1204802/69400c4d-081d-44da-b7f9-46517d318ef6">

The above design is an enhancement that focuses on showing a preview of the font itself, inline in the picker. But this design should not block either the webfonts API from landing, nor the font manager. The existing picker can work fine in the same system:

<img width="280" alt="existing picker" src="https://github.com/WordPress/gutenberg/assets/1204802/9d1cbb94-5b4f-402f-9f5d-8ee7ad199203">

**Comment by mtias** [comment]
Is this being handled as part of the Fonts UI work?

**Comment by jasmussen** [comment]
Initially that was my instinct, but in order to separate concerns I split it out. Happy to consolidate again, though?

**Comment by mtias** [comment]
It's ok to have it split as long as we don't lose track of it!

**Comment by jasmussen** [comment]
Right! @mikachan is #52698 a good tracking issue to include this one on? Or is there a better one?

**Comment by mikachan** [comment]
Yeah, I think https://github.com/WordPress/gutenberg/issues/52698 would be a good fit for this. I think it fits into the scope of that issue and I don't think there are any other, better tracking issues 😄

**Comment by annezazu** [comment]
I just ran into this while working on a site for someone and found the lack of previews to be so frustrating. I couldn't remember exactly what each font looked like after installing a few and it resulted in a lot of unnecessary back and forth. In handing off the site to the person, it made me wish there was a preview to save them time too when they take it over. 

This is a long winded way of saying consider it a plus 1 to see this iterated on.

**Comment by matiasbenedetto** [comment]
I implemented a potential fix https://github.com/WordPress/gutenberg/pull/67118 using styling and on the native HTML select component rendered by the [FontFamilyControl](https://wordpress.github.io/gutenberg/?path=/docs/blockeditor-fontfamilycontrol--docs).

It works as expected on chromium-derived browsers (Chrome, Edge, Brave, etc). [There's a known bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1536148) that makes the browser ignore the style properties in `<option>` tags. I haven't tried it on Safari.

As alternative to the native solution a custom select component that emulates the native select control could be implemented but I think that's much more complex and could impact accesibility .

@WordPress/gutenberg-components input is appreciated.

**Comment by mirka** [comment]
@matiasbenedetto Have you considered using CustomSelectControl? Those can be styled, and is already being used in similar things like the Appearance select in the Typography controls.

**Comment by matiasbenedetto** [comment]
> @matiasbenedetto Have you considered using CustomSelectControl? Those can be styled, and is already being used in similar things like the Appearance select in the Typography controls.

Ohh I didn't know about that component. I will update the PR using it. Thanks for the input @mirka !

**Comment by annezazu** [comment]
So excited to see this!

**Comment by mtias** [comment]
Cool to see progress here!
