### ISSUE TITLE
Just a quick question about making custom multimedia galleries?

### ISSUE THREAD

**Issue by thedonquixotic** [WordPress/gutenberg#5116]
Hi, I'm a relatively new WP developer/designer. For my personal website that I just finished I made a custom masonry layout gallery using ACF and CPT UI. Basically created a custom post type called Gallery, and then put a repeater field in it that had 4 or 5 different inputs. And then depending on those inputs it would display in different ways, such as a video (which is used in place of a gif to show brief clips of repeating autoplaying muted video), a picture with an external link instead of a lightbox, an iframe embed of a Sketchfab model etc.  (you can see examples of the gallery here: https://www.jackalope.tech/side_project/3d-models-and-shaders/ and here: https://www.jackalope.tech/side_project/branding-and-graphic-design/ )

I'm currently learning React.js and I'm very excited for Gutenberg. I'm hoping to learn how to make my own custom blocks soon. I'd like to convert my multimedia gallery into a custom block but I'm not sure how? Any tips on where I could start?

I've seen the Gutenberg custom blocks boilerplate but I'm not sure if it covers image gallery functionality. Additionally this isn't really an image gallery as it takes multiple media types, so I'm not even sure if it would be using a similar structure etc as the image gallery block. When I built my thing I had to build it as a custom post type with custom fields because the blog gallery function could only upload pictures. 

Any hints on how I should approach this?

**Comment by danielbachhuber** [comment]
Hi @thedonquixotic,

Apologies for the late reply! Were you able to get yourself squared away?
