### ISSUE TITLE
Interactivity API: Navigation Block in Post Steals Focus/Console Errors

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#51179]
When loading a post with a navigation block in it and the Interactivity API enabled, the page will move focus the navigation instead of remaining at the top of the DOM.

### Reproduction
- Have a Navigation Block on your a post/page
- Enable the Interactivity API from Gutenberg > Experiments
- Load this page on the frontend of the site
- Focus will be at the first navigation item of remaining at the top of the dom. Console error will show.

### Screenshot
<img width="1392" alt="Frontend site with focus on navigation item inside of post, preact console error showing: Uncaught ReferenceError: Cannot access 'eff' before initialization at g.notify [as c] (utils.js:41:40)" src="https://github.com/WordPress/gutenberg/assets/967608/c83b8076-be2f-4cec-80ca-91a461c890ef">

**Comment by luisherranz** [comment]
I can't reproduce it in `trunk`:

- `document.activeElement` is `body`.
- No errors in the console.

Is that a clean installation? What options are you using in your Navigation block?

**Comment by jeryj** [comment]
I was able to recreate the issue last week, but I'm unable to now, so let's close it :) If I come across it again I'll try to isolate the reproduction steps better. Thanks for following up about it!
