### ISSUE TITLE
Style Revisions: add more details to revision event

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51183]
## What problem does this address?

Currently, the revision history for styles doesn't provide any context as to what each revision holds, instead relying on a visual display of the changes:

<img width="281" alt="Screen Shot 2023-06-01 at 11 12 00 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/77639629-ba5c-4e6c-b41b-9392895ba617">

While it's helpful to have visuals, it's hard to spot the changes visually without any context. For example, perhaps you made Style changes to a block that's not on the template you're looking at or the changes aren't visible in the part of the template you're looking at. Here's an example:

https://github.com/WordPress/gutenberg/assets/26996883/89021a65-b2c5-449e-a4fe-167d7556f59b

## What is your proposed solution?

I think there should be a way to see more information at a glance when viewing different revisions, perhaps only the currently active one before thinking through comparison style flows. This ties into work to provide more granular info with saving too: https://github.com/WordPress/gutenberg/issues/29388

**Comment by mtias** [comment]
It can be useful for assistive technologies as well to have a summary of changes to identify. This is sort of related to also listing somewhere in global styles what things are changed. The "reset to defaults", for example, could open a modal to confirm that lists those changes as well.

**Comment by ramonjd** [comment]
For the text summary side of things, I did do a very quick test of that when first pulling things together: https://github.com/WordPress/gutenberg/pull/50089#issuecomment-1535597854

Some revisions could contain dozens of changes, so the gist of it was we'd scan the top level of global styles JSON for top-level styles and, for each item in the revisions list, print something like:

"This revision contains changes to typography, color, and the Paragraph block."

Even that could get verbose and adding the iterative logic to insert this content would slow down rendering. Perhaps we could rather insert the content changes on demand, that is, when a user selects an individual revision. Would need some design cycles to get the UI right.

**Comment by annezazu** [comment]
Closing this out in favor of a more recent and duplicated issue: https://github.com/WordPress/gutenberg/issues/55647
