### ISSUE TITLE
Command center: keyboard shortcut inconsistent

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51182]
While testing GB 15.9, I noticed that the command center isn't as consistent in being invoked as it was previously. When editing an individual block, it seems to want to add a link. When no block is selected (or some block combo that's not clear to me), it won't always pop up. I'm not sure what's going on but compared to earlier versions it feels more finicky. 

https://github.com/WordPress/gutenberg/assets/26996883/78ca00c9-6b20-4eee-948e-f580f095ecfe

cc @youknowriad

**Comment by annezazu** [comment]
This was also noted in the [FSE Outreach Program Rapid Revamp call for testing:](https://make.wordpress.org/test/2023/05/18/fse-program-testing-call-23-rapid-revamp/#comment-3069)

>After adding content to About page and leaving the cursor in a paragraph block, when I click on the CMD + K, not open the command center. In this case, open a Search to add a link (the popup that appears when a link is inserted). I have to click in the parent block to work fine in the command center.

[& later:](https://make.wordpress.org/test/2023/05/18/fse-program-testing-call-23-rapid-revamp/#comment-3070)

>However, this only works in certain places, see here: https://haurand.com/wp-content/uploads/2023/06/cmd_k.gif
Therefore, I had to search a little until I found a possibility. But actually a cool thing when you have found it.

**Comment by youknowriad** [comment]
So the fact that it doesn't work when a RichText is focused is actually intended because it's the same shortcut we use for the "link" control. I think the plan is to eventually have commands to add links within the command center, so that we can unify and always trigger the command center when using cmd+k

**Comment by youknowriad** [comment]
Closing this one in favor of #51737
