### ISSUE TITLE
Copy block in widget area doesn't copy the whole block

### ISSUE THREAD

**Issue by MatzeKitt** [WordPress/gutenberg#51196]
### Description

If I copy a block in the widget area via the context menu, the content will be copied as text. This makes it impossible to paste that block 1:1 anywhere else.

### Step-by-step reproduction instructions

1. Create a paragraph block with the content "Test".
2. Open the kebab menu of this block and select "Copy block".

Expected string in the clipboard:

```
<!-- wp:paragraph -->
<p>Test</p>
<!-- /wp:paragraph -->
```

Actual string in the clipboard:

```
Test
```

### Environment info

- WordPress 6.2, no Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by torounit** [comment]
@MatzeKitt  This issue was reviewed in today's Editor Bug Scrub. Can you provide information on themes, plugins, etc. to reproduce this issue? Thanks!

**Comment by MatzeKitt** [comment]
@torounit Thank you for answering!

I disabled all plugins, the result is identical with the Twenty Twenty-One theme. So basically just a plain WordPress 6.2.2 with Twenty Twenty-One in version 1.8.

System: macOS 13.4 with Safari 16.5

I think the system is more important here. With Chrome 114, it works. Sorry that I didn’t came up with this earlier. 🙇‍♂️

**Comment by MatzeKitt** [comment]
Do you need any more information, @torounit?

**Comment by jordesign** [comment]
Hi @MatzeKitt - I've tried testing this out with a fresh install of WordPress 6.2.2 and the TwentyTwentyOne theme and have been unable to recreate it.

Just to clarify where you saw this happening - was this when editing the widgets under Appearance > Widgets, or within the customizer at Appearance > Customize?

I'd also be interested to know if this is still occuring for you?

**Comment by torounit** [comment]
@MatzeKitt @jordesign 

Tested on `wp-admin/widgets.php` now.  It appears to be copying correctly.

https://github.com/WordPress/gutenberg/assets/1908815/35563f73-b981-4b09-8613-0a52fbeff2a9

**Comment by MatzeKitt** [comment]
Unfortunately, I still have the same problem as before, using Safari:

https://github.com/WordPress/gutenberg/assets/1018979/8b63e838-ebfa-4ab6-bf98-d093eb4dbee4

**Comment by MatzeKitt** [comment]
At least in Safari 17.2 it works now just fine. So it seems to be either a browser bug in earlier versions of Safari or the fix has been deployed as side effect in Gutenberg.
