### ISSUE TITLE
Styles: consider increasing the prominence of revisions

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51203]
Currently, revisions for style variations is placed behind the three dot menu in the sidebar:

<img width="286" alt="Screen Shot 2023-06-02 at 9 08 10 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/b6f7b7b4-fe19-4d6a-adc2-3c3da155724d">

This places it at the same prominence as Custom CSS which intentionally was placed there to add friction to adding CSS, an action folks should have to take less and less as the Site Editor grows in functionality. In the twenty-third call for testing for the FSE Outreach Program, @paaljoachim notes how odd this feels:

>Revisions is too hidden away and needs to become more visible directly in the Styles area. Looking at the Post editor. In the sidebar there is an revisions icon and next to it it shows the amount of revisions. What about something like that for the Styles area in the Editor?

I think we should consider surfacing this more, particularly if we keep style variations in place as a top level item in the Site View considering the current bugs with switching between style variations (https://github.com/WordPress/gutenberg/issues/50924) and lack of UI for explaining style hierarchy (https://github.com/WordPress/gutenberg/issues/49278). cc @WordPress/gutenberg-design

**Comment by jasmussen** [comment]
I think @jameskoster might have a later design for this, but it seems like surfacing revisions in site view is a good way to bring extra prominence to a more high level receded view:

<img width="640" alt="Screenshot 2023-06-06 at 09 51 03" src="https://github.com/WordPress/gutenberg/assets/1204802/bc63b56f-e944-4d3b-8bc1-d66ab0bd46e9">

**Comment by jameskoster** [comment]
Style revisions are now accessible from the Styles panel in Site View.

A similar treatment in Edit View seems reasonable.

**Comment by paaljoachim** [comment]
Are we ready to add the "Needs dev" label here?

**Comment by jameskoster** [comment]
I think we're missing a mockup. Perhaps we simply reuse the button from posts / pages / template parts, positioned at the bottom of the panel?

<img width="281" alt="Screenshot 2023-06-08 at 09 59 38" src="https://github.com/WordPress/gutenberg/assets/846565/5a258cc4-2b20-437f-8abe-05e7dacdeea8">

This could work as a short-term solution, but it's beginning to feel like we need to take a broader look at the Styles panel in light of these new features (revisions, style book), and the advent of Site View.

**Comment by jordesign** [comment]
Closing this as we now have the Style Revisions icon at the top level.

<img width="426" alt="Screenshot 2024-01-12 at 11 02 29 am" src="https://github.com/WordPress/gutenberg/assets/1842363/c7a55b5f-c004-4e7b-904e-f6c30cf207cd">


Happy to re-open if needed.
