### ISSUE TITLE
Styles: Iterate on revisions note in top toolbar

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51202]
Currently, we list "Global styles revisions" in the title bar section when viewing revisions for Styles:

<img width="943" alt="Screen Shot 2023-06-02 at 9 04 15 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/3c92150d-e796-497c-9aef-de2dd023c4aa">

In general, I'm under the impression that "Global Styles" is the technical project name and not something to surface or reference to users in most cases. As a result, I think we should update this to say "Style Revisions" and perhaps have it share some commonality with the new title bar https://github.com/WordPress/gutenberg/issues/50378 

<img width="529" alt="Screen Shot 2023-06-02 at 9 06 28 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/211dd987-4e23-4d92-8e13-7b0611e2faa7">

cc @WordPress/gutenberg-design

**Comment by jameskoster** [comment]
It's strange to me that when the main Styles panel is open the 'document title' continues to display the template / page name. But then if you open revisions or the style book, it changes. Not to mention the awkward structure (a Panel titled "Styles" > "Revisions" within a view titled "Global Styles Revisions" 🙈). It would be good to explore these details more holistically soon, especially now that there is the Styles panel in the dark material as well.

But in the mean time I agree. Removing "Global", or even the entire title seems reasonable.

**Comment by jordesign** [comment]
@annezazu This seems like a (hopefully) quick win to get into the other Style Variations work for 6.5?

**Comment by annezazu** [comment]
Kicked off a PR to maybe quickly fix this (assuming I did this correctly) 😜
