### ISSUE TITLE
Opening Style Book from Styles > Revisions doesn't work

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#51238]
### Description

If you attempt to access the Style Book while the Styles Revisions panel is open it doesn't work. The document title updates, but the canvas continues to display revisions:

https://github.com/WordPress/gutenberg/assets/846565/9c663ad9-d6e8-4cc7-aa57-b03a31b9b7ea

### Step-by-step reproduction instructions

1. Open the site editor
2. Open style revisions
3. Click the 👁️ icon to open Style Book
4. Notice that the Style Book is not visible

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
The latest Gutenberg may have solved this problem. Here is what I have tested. This might have something to do with the revision button being moved out of the dropdown.


https://github.com/WordPress/gutenberg/assets/54422211/aa1da5e4-1d43-42eb-9317-3ab956e12764

**Comment by jameskoster** [comment]
Yup, can confirm, this is no longer an issue.

Good spot.
