### ISSUE TITLE
Default name when adding new colors in styles does not appear in sequential order numbers

### ISSUE THREAD

**Issue by cattmin** [WordPress/gutenberg#51230]
### Description

Using FSE to change styles on a page template. When using the English language in site and add new colors to Styles, the default name appear with numbers in order. However, when switching to Japanese language, the sequential order numbers did not work anymore in the default name. 

### Step-by-step reproduction instructions

1. Open the Settings
2. Change Site Language to Japanese 日本語
3. Open Site Editor
4. Click on a template to edit → choose Styles panel on the top right
6. Click on Colors → Palette
7. Click on Custom , add button and choose a new color
8. See that after clicking a new color, the default name is set to the correct sequential order number.
9. Repeat steps to choose a new color
10. See that, now the next default name is not set to a sequential order number but repeats the same number as previous.

### Screenshots, screen recording, code snippet

![issue-report](https://github.com/WordPress/gutenberg/assets/103159231/453eb582-b0d4-45aa-a52c-1ab8943e6fb8)
![issue-report](https://github.com/WordPress/gutenberg/assets/103159231/1e166018-fdef-43fe-8ec2-6090bf83b064)

### Environment info

- The site uses WordPress 6.2.2 , Gutenberg 15.9, Twenty Twenty Three theme
- Reproduced on Firefox 113.0.2 and Chrome Version 114.0.5735.90
macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
I can replicate this issue.

**Comment by t-hamano** [comment]
Thanks for the report. This issue has been fixed by #52212.
