### ISSUE TITLE
wp-env - Migrate to Compose V2

### ISSUE THREAD

**Issue by igorradovanov** [WordPress/gutenberg#51249]
## What problem does this address?

Compose V1 no longer receives updates and will not be available in new releases of Docker Desktop after June 2023.

Docker Desktop will continue to provide the 'alias' command; however, outside of that, it's not possible to run 'wp-env,' for example, on Fedora, as the new command is 'docker compose' (without a hyphen) - screenshot attached for more context.

![Screenshot from 2023-06-05 22-41-14](https://github.com/WordPress/gutenberg/assets/20539903/a3f79089-6a37-4a79-a64f-c7940e7db0c5)

## What is your proposed solution?

wp-env should migrate from docker-compose to docker compose V2 plugin according to the next [guide](https://docs.docker.com/compose/migrate/) in the near future

**Comment by igorradovanov** [comment]
For anyone stumbling upon this issue while running wp-env on POSIX/Linux, a temporary solution is to install the standalone version that uses the docker-compose syntax currently utilized by the wp-env project. You can find the version 1 documentation and installation instructions here: https://docs.docker.com/compose/install/standalone/

**Comment by firxworx** [comment]
For better developer experience across platforms this could always check for `docker-compose` _and_ `docker compose`. 

A current-version Docker Desktop install or docker open-source install (e.g. via brew) on MacOS will not have a `docker-compose` binary in the path. "Quick fix" solutions such as creating an alias will not work with `wp-env`. On MacOS wp-env should be shooting for `docker compose` syntax (reference the guide linked to in the OP issue).

In contrast with MacOS, a user running Windows with Docker Desktop installed on Windows and running linux via WSL2 is likely to have more flexibility with a typical setup. 

It is likely both `docker compose` and `docker-compose` are supported and both will use V2.

A highly likely and generally recommended setup for current Windows + WSL users is Docker Desktop installed on the Windows side with the following settings enabled: "Use WSL 2 Based Engine" and "Use Docker Compose V2" (the latter enables V2 on `docker-compose`).

I would add to the docs to suggest trying the `--debug` flag if there is an issue to help diagnose. The wp-env output can seem to hang at "Starting WordPress" without any other error feedback unless this flag is added.

A common problem that comes up with Docker on WSL2 these days is related to `~/.docker/config.json` getting `"credsStore": "docker.exe"` added to it. It happened in my case just now digging into an older WordPress project to add an update. Deleting that line kicks it in the pants to start clean. Reference: https://github.com/microsoft/WSL/issues/8677
