### ISSUE TITLE
Details block: opening and closing impacts background of header

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51248]
This was found as part of the [FSE Outreach Program's rapid revamp call for testing:](https://make.wordpress.org/test/2023/05/18/fse-program-testing-call-23-rapid-revamp/#comment-3070)

>The Details Block is really a great thing, but unfortunately there is an issue in the frontend with the style I chose regarding the header: the height of the header changes when I click on the arrow to display the hidden content. But this seems to be an issue overall when not much text is written on a page

![detail_block](https://github.com/WordPress/gutenberg/assets/26996883/7cbb465c-ed77-4fbe-b839-7c170829ab7d)

To replicate, switch to the Aubergine style variation for TT3 and add a details block to a page with some text inside. View on the front end of your site and notice when opening the details block, the heading/background appears to move.

This was found using the Aubergine style variation and Gutenberg 15.9.1 with WordPress 6.2.2. I wonder if this is potentially related to https://github.com/WordPress/gutenberg/issues/46782

**Comment by talldan** [comment]
@annezazu I don't think this is an issue with the details block, but more with the aubergine variation and how the background is implemented, so it's probably a core trac ticket.

It would happen for just about any block that can change the page height (like third party accordion blocks) and might become more apparent with the interactivity experiments.

**Comment by justintadlock** [comment]
This is a theme design issue. The background gradient will be problematic on any pages with a shortened height. Here's the background gradient that's used:

```css
linear-gradient(180deg, var(--wp--preset--color--base) 0 min(24rem, 10%), var(--wp--preset--color--secondary) 0% 30%, var(--wp--preset--color--base) 100%)
```

In particular, the `min(24rem, 10%)` is essentially saying to use the lower value (either `24rem` or `10%`). On pages with little content, it is pretty much guaranteed to be `10%` of the `<body>` height.

**Comment by annezazu** [comment]
Thanks for clarifying and giving more insight, @justintadlock. Where do you think is the best place to leave this feedback? Trac or here? It also just might be "by design", meaning it _could_ be closed out.

**Comment by justintadlock** [comment]
Yeah, I believe this is probably best on core Trac.

@anarieldesign might have some insight into whether it's "by design" or could be altered since she was the original author of the variation.

**Comment by annezazu** [comment]
https://core.trac.wordpress.org/ticket/58475 closing out- thank you.
