### ISSUE TITLE
Buttons disappear in FF when turning on developer tools

### ISSUE THREAD

**Issue by BackuPs** [WordPress/gutenberg#5124]
Hi

I am using the default 20-16 theme with woocommerce, rtl tester, regenerate thumbnails and gutenberg plugins but if i open the developer tools in the browser the css responsible for the positioning of the gutenberg edit-post-header disappear behind the left side of the admin bar.

See images

![no-devtools](https://user-images.githubusercontent.com/6078370/36353207-cda28f02-14c3-11e8-93fe-1847437dee20.png)

![devtools](https://user-images.githubusercontent.com/6078370/36353209-cffdd2c0-14c3-11e8-8919-a682ae074a50.png)

Pls fix.  Thank you !

**Comment by mtias** [comment]
I can't reproduce this. Please, reopen if you still see an issue and have more details.

**Comment by BackuPs** [comment]
after 3 months a reply?  i did not even remember i posted this !
