### ISSUE TITLE
Site Editor: Consider adding a View Page link 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51245]
## What problem does this address?

As part of efforts to optimize a content centric edit experience in the Site Editor https://github.com/WordPress/gutenberg/issues/49404, the familiar feedback of wanting a way to view what's being edited https://github.com/WordPress/gutenberg/issues/29398 has come up. This was found as part of the [FSE Outreach Program's Rapid Revamp call for testing:](https://make.wordpress.org/test/2023/05/18/fse-program-testing-call-23-rapid-revamp/#comment-3064)

>This may have been addressed somewhere, but when saving a page from the Site editor, there is no link to view it. After saving changes, it could be awesome to have a link, at least at the bottom left notification where it now says: Site Updated. I think it won’t hurt to have a Page updated View page link like in the page editor.

[& from someone else](https://make.wordpress.org/test/2023/05/18/fse-program-testing-call-23-rapid-revamp/#comment-3069):

>After saving the changes, I like to view the page in the front end, so the unique button available for this is the View button, but I click on it and I go home, not to the about page. This behavior isn’t the hoped.

## What is your proposed solution?

Curious to hear from @WordPress/gutenberg-design but I can think of a few ways:

**Add an option to view page under "View"**
<img width="273" alt="Screen Shot 2023-06-05 at 12 11 01 PM" src="https://github.com/WordPress/gutenberg/assets/26996883/ecbeece3-c936-489c-841a-db099284a923">

**Update "Site Updated" notification**

Right now, after you make changes to Pages in the Site Editor and click save, you get the usual "Site Updated" notice with no option to view the page. It might make sense to update this notification or add an additional one after "Page updated" with a link.

**Include the view link component**

After https://github.com/WordPress/gutenberg/pull/50260 was integrated into 15.8 in the Post Editor, it might provide some good consistency to have this same view link component for a published page in the Site Editor:

<img width="296" alt="Screen Shot 2023-06-05 at 12 14 43 PM" src="https://github.com/WordPress/gutenberg/assets/26996883/6f0fa627-87db-43b5-a273-015ddd63ba14">

Of note, some design iterations are happening around the icons so as to not clutter the experience too much: https://github.com/WordPress/gutenberg/issues/51006

**Comment by annezazu** [comment]
Ah! Noting that this seems to be covered by: https://github.com/WordPress/gutenberg/issues/50378 There just aren't sub-issues for these items yet. Happy to close this out or leave open depending on what's helpful.

**Comment by jasmussen** [comment]
I think #51006 might cover this!

**Comment by jameskoster** [comment]
I'd like to try adding this to the document title (https://github.com/WordPress/gutenberg/issues/50378#issuecomment-1576547838).

**Comment by annezazu** [comment]
Awesome. I'll close this out as it _seems_ tracked enough but happy to keep open. I always worry about things getting lost in the flurry of work :D
