### ISSUE TITLE
Attempting to crop an image wihin a row block causes layout to break

### ISSUE THREAD

**Issue by markdavies** [WordPress/gutenberg#51250]
### Description

When editing an image within a row block, clicking on the crop tool shrinks the image to an unusable size. This will fix itself suddenly sometimes too, after playing with other controls or opening the web inspector.

Inspecting the div that surrounds the react-easy-crop element shows that its width and height are set to 0:

<img width="482" alt="Screenshot 2023-06-06 at 9 35 52 am" src="https://github.com/WordPress/gutenberg/assets/320683/269ae6df-0a1e-4884-9e34-a22e3172b183">

### Step-by-step reproduction instructions

1. Install new Wordpress 6.2.2 and 2023 theme.
2. Create a new post
3. Insert a row block and within it add two images
4. Select one image and click on the crop button in the contextual menu

### Screenshots, screen recording, code snippet

[Screen capture](https://www.loom.com/share/a612b04171764337bf64b3df01b1e571)

### Environment info

- Wordpress 6.2.2 Theme: 2023
- Firefox 113.0.2
- macOS 13.4 (22F66)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub, and I have been able to confirm. Thanks for reporting @markdavies
