### ISSUE TITLE
Navigation block not updating on menu change or classic menus import. Only updates if menu item changed.

### ISSUE THREAD

**Issue by VinodSoftcripts** [WordPress/gutenberg#51270]
### Description

The navigation block is not working properly. When I tried to change the menu or import the classic menu, it is not being updated on the frontend at times. It only updates when we modify a menu item. Please refer to the attached screen recording for further clarification.

### Step-by-step reproduction instructions

1. Create two different menus.
2. Go to the block editor page and add a navigation block with the first menu.
3. Click "Update."
4. Change the navigation block menu to the second menu or import the second menu from the classic menus list.
5. Click "Update."
6. Check the page frontend to see if the menu has been updated.

### Screenshots, screen recording, code snippet

https://capture.dropbox.com/pQS1YJMuazVb2hBt
https://capture.dropbox.com/CGxWdt1bg6tO2WAk

Also tested the same on another site with the Hello Elementor theme and WordPress 6.2.2
https://capture.dropbox.com/VVG831XJdm4gCmDU

### Environment info

- WordPress 6.2.2 version
- Genesis Theme 3.4.0 version
- Google Chrome Version 114.0.5735.90
- macOS version 12.6.6 (21G646) 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aurooba** [comment]
Hi @VinodSoftcripts. Thanks for reporting this! I wasn't able to reproduce this bug when testing with the default Twenty Twenty Three theme. It's possible that this could be happening because of a theme or plugin bug/conflict. 

Could you test with the Twenty Twenty Three theme in your environment with all your plugins turned off, particularly any caching plugins you may have installed? If the issue still persists, let us know!

**Comment by carolinan** [comment]
I wonder if this may have been solved by https://github.com/WordPress/gutenberg/pull/50318.
Does it work better if you install and activate the latest version of Gutenberg?

**Comment by jordesign** [comment]
I can't recreate this with GB16.1 and T23. With no further details in the last month I'm going to close it for now.

If the problem arises again (with a default theme) we can re-open it.
