### ISSUE TITLE
Hello, I would like to collaborate with your project by serving as a translator to Spanish which is my native language. I could translate any document that I have text as long as the translation is a thousand words or more. I can translate the two readme documents and contributing

### ISSUE THREAD

**Issue by LuigiBaute** [WordPress/gutenberg#5127]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by Rahmon** [comment]
Hi @LuigiBaute.

You might translate here: https://translate.wordpress.org/projects/wp-plugins/gutenberg

**Comment by karmatosed** [comment]
@LuigiBaute thanks for creating an issue but as @Rahmon says you can contribute there for translations.
