### ISSUE TITLE
Image: Lightbox doesn't work on image inserted from URL

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#51276]
### Description

Getting PHP errors when using the lightbox with images not in the media library.

```
( ! ) Notice: Undefined index: id in ./gutenberg/build/block-library/blocks/image.php on line 81
```

This happens in both the post editor and the frontend.

### Step-by-step reproduction instructions

1. Add an image block
2. Use 'Insert from URL' to add an image
3. See PHP error

Or use the image block below.

```html
<!-- wp:image {"sizeSlug":"large","behaviors":{"lightbox":true}} -->
<figure class="wp-block-image size-large"><img src="https://wp20.wordpress.net/wp-content/themes/twentyseventeen-wp20/images/wp20-logo-white.svg" alt="WP20 logo"/></figure>
<!-- /wp:image -->
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by SantosGuillamot** [comment]
I started [this pull request](https://github.com/WordPress/gutenberg/pull/51278) to solve it. Thanks a lot for the report 🙂
