### ISSUE TITLE
Global Styles: Add support for elements to individual blocks

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#51272]
## What problem does this address?
There is currently no way to edit element styles for individual blocks using the Global Styles UI. This makes it impossible to modify even some very basic design choices - for example: https://github.com/WordPress/gutenberg/issues/51265.

## What is your proposed solution?
We should add support for elements to block controls in Global Styles to make the UI more powerful.

**Comment by nielslange** [comment]
@scruffian Another use case can be found on https://github.com/woocommerce/woocommerce-blocks/issues/10118, where @mikejolley was wondering if it's possible to apply Global Styles for `<th>` and `<td>` independent of each other. From @glendaviesnz, I understood that this is not possible, and he pointed me to this issue to mention the use case here.

**Comment by scruffian** [comment]
Another time when this came up was trying to remove text decoration from the Site Title block - you need to do it for the link element which isn't possible in the UI.

Similarly it would be very useful to be able to add text decoration to links in a Post Content block.

**Comment by SaxonF** [comment]
@scruffian does [this PR](https://github.com/WordPress/gutenberg/pull/53667) resolve this issue or am I misunderstanding the problem?

**Comment by scruffian** [comment]
No this issue is about making elements available in the Global Styles UI:

<img width="281" alt="Screenshot 2023-09-04 at 16 06 42" src="https://github.com/WordPress/gutenberg/assets/275961/f4042eb9-bb12-46fc-b074-3d6a29bce3b7">

these controls should also be available in the block controls for each block that supports it.

**Comment by SaxonF** [comment]
> these controls should also be available in the block controls for each block that supports it.

@scruffian I still may be misunderstanding but on trunk I now see extended elements in blocks. 

<img width="292" alt="image" src="https://github.com/WordPress/gutenberg/assets/1072756/f04b9066-877c-423f-abc2-e9819949f649">

**Comment by scruffian** [comment]
@SaxonF you're right this does appear in some places, but not everywhere we'd like it - for example there is no way to change captions for all image blocks. However I think that's better dealt with in a different issue, so let's close this.
