### ISSUE TITLE
Heading section should be visible while clicking through Document Outline (Content Structure)

### ISSUE THREAD

**Issue by abdullah1908** [WordPress/gutenberg#5129]
## Issue Overview
Heading section should be visible while clicking on Document Outline(content structure)

## Steps to Reproduce (for bugs)
1. Publish the default Gutenberg Post
2. Just click on info outline icon(Content Structure) in the editor header
3. Click on any heading section used in the post content
**Browser:** Google Chrome Version _63.0.3239.132_
**Gutenberg:** _2.2_
**WordPress:** _4.9.4_

## Expected Behavior
Heading section should be visible and below the Content Structure (Components Popover) while clicking on it

## Current Behavior
Currently, heading section is hidden behind the Content Structure (Components Popover) while clicking on it

## Possible Solution
Reason: Cross Browser Compatibility(CSS glitch)

## Screenshots / Video
![gutenberg-document-outline-issue](https://user-images.githubusercontent.com/14175927/36360565-0c4dc612-1547-11e8-96fc-f3ded28774f3.png)

**Comment by pento** [comment]
I can reproduce this behaviour, but it's probably going to be tricky to fix, and fairly low priority compared to other things the team needs to work on. 

That said, if someone feels like tackling this, we're always happy to review PRs and provide feedback. 🙂

**Comment by abdullah1908** [comment]
Sure :-) 
I am also trying to back track this issue.

**Comment by designsimply** [comment]
I think it's reasonable to expect to have to either close the document outline or click onto the page (which dismisses the content structure popover).

I'd like to close this in favor of letting someone re-open if/when they are actively working on an update.
