### ISSUE TITLE
Template vs content editing UX: improve experience of switching when block sidebar is closed

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51304]
While doing some early testing of https://github.com/WordPress/gutenberg/pull/49980, I noticed that if the block sidebar is closed, the various UI nudges don't seem as clear, making the experience fairly confusing in terms of what actions you can take. Here's a video displaying that where you can see the delay in notifications also makes for an odd experience. For example, the "return to about page" notif shows up after I've already done so using the Title Bar for example and the notif to edit the template when I'm back in the page never returns, making it hard to know how to switch between:

https://github.com/WordPress/gutenberg/assets/26996883/a7729bec-adfe-42d2-9059-3fee2180e795

**Comment by noisysocks** [comment]
I think with https://github.com/WordPress/gutenberg/pull/51366 and https://github.com/WordPress/gutenberg/pull/51224 things are a little clearer and we can close this.

cc. @SaxonF @jameskoster
