### ISSUE TITLE
Query: Editor crashes when query attribute includes `categoryIds` or `tagIds` and the `layout` attribute is applied

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#51308]
### Description

I believe this issue is related to changes made in https://github.com/WordPress/gutenberg/pull/49050, perhaps [here](https://github.com/WordPress/gutenberg/commit/555749a8990314f5f2e122b6957623d5b9844c8e#diff-31872a45d07b61ef8a20bc698f1c7d62252529f505c45ade7c60f005a8fa4338R303). 

See the code example below. When you have a Query block that includes the deprecated sub-attributes `categoryIds` and/or `tagIds` of the `query` attribute, and then the `layout` attribute is set, the Editor will crash. This is a particularly problematic regression because block themes in the WordPress.org repository have patterns built with these attributes.  

This issue is specific to trunk and 16.0 RC1. Gutenberg 15.9.1 works correctly. 

### Step-by-step reproduction instructions

1. Make sure you are using trunk or 16.0 RC1
2. Create a new page and add the following code to the Code Editor.
3. Switch to the Visual Editor and see the Editor crash. 

### Screenshots, screen recording, code snippet

```
<!-- wp:query {"queryId":2,"query":{"perPage":3,"pages":0,"offset":0,"categoryIds":[],"tagIds":[],"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false,"taxQuery":{"category":[1]}},"layout":{"type":"constrained"}} -->
<div class="wp-block-query"><!-- wp:post-template -->
<!-- wp:post-featured-image /-->

<!-- wp:post-date /-->

<!-- wp:post-title /-->
<!-- /wp:post-template -->

<!-- wp:query-pagination -->
<!-- wp:query-pagination-previous /-->

<!-- wp:query-pagination-numbers /-->

<!-- wp:query-pagination-next /-->
<!-- /wp:query-pagination -->

<!-- wp:query-no-results -->
<!-- wp:paragraph {"placeholder":"Add text or blocks that will display when a query returns no results."} -->
<p></p>
<!-- /wp:paragraph -->
<!-- /wp:query-no-results --></div>
<!-- /wp:query -->
```

### Environment info

- Gutenberg 16.0 RC1
- WordPress 6.2.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
@tellthemachines I think this is just a deprecation file issue, but any additional thoughts on this?

**Comment by bgardner** [comment]
I can confirm this is an issue, and thanks to @ndiego, will be pushing out an update to my Powder theme which removes the deprecated sub-attributes ahead of the Gutenberg 16.0 release just_in_case.

**Comment by andrewserong** [comment]
It looks like `migrateToConstrainedLayout` is missing a `return attributes` statement for blocks that have layout that's already in the correct shape. I can put up a quick PR.

**Comment by andrewserong** [comment]
I have a fix up over in https://github.com/WordPress/gutenberg/pull/51311. Thanks for opening the issue and providing the test markup!
