### ISSUE TITLE
Lack of screen space causes block transform preview to prevent user from actually clicking on the transform

### ISSUE THREAD

**Issue by albanyacademy** [WordPress/gutenberg#51309]
### Description

When your screen real estate is small, transform preview popover pops over the thing you're hovering to get the preview going, causing it to flicker endlessly and sort of block you from actually clicking the transform you want.

### Step-by-step reproduction instructions

1. Shrink your screen (was able to replicate this easily at 800px)
2. Create a list block
3. Go to transform the parent list block
4. Observe that the transform preview obscures the transform selection.

### Screenshots, screen recording, code snippet

https://www.screencast.com/t/s7godNGXh

### Environment info

wp 6.2.2, no gutenberg plugin or any other plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Thanks for reporting @albanyacademy. We were able to replicate this in today's Editor Bug Scrub.  

![transform-flicker](https://github.com/WordPress/gutenberg/assets/4832319/d2c1b34c-cd58-4f3a-9bad-4f623efaa68a)

**Comment by talldan** [comment]
It's interesting. I'm not really sure the best way to fix it.

Maybe don't show the preview at particular sizes, or reduce its size, but it may be difficult to determine when this is going to trigger.

**Comment by ndiego** [comment]
> Maybe don't show the preview at particular sizes, or reduce its size, but it may be difficult to determine when this is going to trigger.

Personally, I think just not showing the preview at certain sizes would be fine.

**Comment by albanyacademy** [comment]
one could argue that previews on transforms doesn't really serve a purpose to begin with - previewing how text would look as a header when converting from a paragraph is as simple as transforming it to a header, and then clicking undo if you don't like it,

Maybe if it was a complex block it would be valuable, but previews really only make sense when trying to show the user pattern previews imo. Simple block transforms seems overkill.

the thought process for simple block transforms is moreso of need - this _needs_ to be a list, this paragraph has ended and I've started a new topic, so I _need_ this to be a heading. There's no aesthetic decision there.

**Comment by t-hamano** [comment]
One approach might be to not display the preview when the width is narrow, such as [the block style preview](https://github.com/WordPress/gutenberg/blob/c2a54cd28ecab83d7f770cfbf9e8db3649f0f960/packages/block-editor/src/components/block-styles/style.scss#L6-L13).

However, relying solely on browser width is a bit unstable. This is because the behavior also changes depending on whether the block toolbar is fixed or not, or whether the list view is opened or not.

The screenshot below is for a browser width of 1100px. This issue does not occur if the toolbar is fixed, but it does occur if it is not fixed.

Fixed toolbar enabled:

![image](https://github.com/WordPress/gutenberg/assets/54422211/b0e72cf1-6010-4805-b0fd-ce95ada2f0d2)

Fixed toolbar disabled:

![image](https://github.com/WordPress/gutenberg/assets/54422211/953d5ecd-57be-41df-a8e5-42c569887a2a)

**Comment by annezazu** [comment]
[After a review](https://wordpress.slack.com/archives/C02QB2JS7/p1707152945370159) by core editor triage leads and core editor tech leads, this has been removed from the board for 6.5 consideration.

**Comment by ntsekouras** [comment]
This seems to be an issue in mobile viewport too. Maybe we could update conditionally the popover's placement in `PreviewBlockPopover` (example from `bottom-start` to `top-start`) and sometimes we could stop rendering it too..

**Comment by richtabor** [comment]
> Maybe we could update conditionally the popover's placement in PreviewBlockPopover (example from bottom-start to top-start)

Is this difficult to do? I think even switching left/right would be good — i.e. if there's not enough room on the right, show it on the left.

Side note: I do question how helpful these transform previews are:

https://github.com/WordPress/gutenberg/assets/1813435/864d6a1a-8e8f-487e-847b-e682c2c5f4be

**Comment by albanyacademy** [comment]
> Side note: I do question how helpful these transform previews are:

😬
