### ISSUE TITLE
Template vs content editing UX: focus lands on the featured image upload when clicking template

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51301]
While doing some early testing of https://github.com/WordPress/gutenberg/pull/49980, after dismissing the notice, I'm seeing some super odd behavior in clicking around the template where it’s not clear what to do and it seems to focus on the featured image upload for some reason:

https://github.com/WordPress/gutenberg/assets/26996883/4f8c6f39-4720-4acf-8ddb-9985a1b741a1

I'm noting this as a bug for now as it doesn't seem intentional but welcome updates to the labels if others feel differently.

**Comment by noisysocks** [comment]
@annezazu: Are you still seeing this?

I'm not seeing the Post Featured Image block flash when I test locally and click outside of it. It might be theme dependent. What theme are you using?

Additionally it might be a little clearer what's happening now that we have extra guidance for this feature. See https://github.com/WordPress/gutenberg/pull/51366.

**Comment by annezazu** [comment]
Using 16.1 RC1, I can replicate _eventually_ after a seeming clash of notices between the snackbar and then the pop up. It does feel a bit better/harder to get to though:

https://github.com/WordPress/gutenberg/assets/26996883/2e5f0854-ad5f-4176-8d24-5f213cf33e3c

**Comment by annezazu** [comment]
No longer can replicate in 6.5 beta 2.
