### ISSUE TITLE
Template vs content editing UX: improve block settings content to better indicate possible actions

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51302]
While doing some early testing of https://github.com/WordPress/gutenberg/pull/49980, I noticed that it shows as “no block selected” in the sidebar when you're on the block tab:

https://github.com/WordPress/gutenberg/assets/26996883/9abc1847-6ec8-4a09-986f-d01bb74d5e0b

It also doesn't provide any visual clarity in the sidebar when on the Page tab:

https://github.com/WordPress/gutenberg/assets/26996883/1cffe91a-dd39-43b6-a3e0-6f43bf79aaba

This feels like a missed opportunity, especially when the notice is hard to see on a dark background https://github.com/WordPress/gutenberg/issues/51300 and only seems to appear once.

**Comment by noisysocks** [comment]
> While doing some early testing of #49980, I noticed that it shows as “no block selected” in the sidebar when you're on the block tab:

I think the solution here is to mimic what happens in the other editors where we switch to the Page tab when you unselect a block. I'll work on a fix for that.

> This feels like a missed opportunity, especially when the notice is hard to see on a dark background https://github.com/WordPress/gutenberg/issues/51300 and only seems to appear once.

This notice will appear again now as of https://github.com/WordPress/gutenberg/pull/51366.
