### ISSUE TITLE
Impossible to tell number of columns in a Columns block just by looking at it

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#5131]
## Issue Overview
After you've inserted a Columns block, it's impossible to tell the number of columns it contains, just by looking at it. This also makes it impossible to tell where you're supposed to click to enter your content.

![gutenberg-columnsblock](https://user-images.githubusercontent.com/2078245/36363121-82222c92-158e-11e8-8704-909b2dfb3d5b.png)

## Steps to Reproduce (for bugs)
1. Insert Columns block
2. Try to work out how many columns it has without clicking on it

## Expected Behavior
I should be able to tell exactly what every single block does, just by looking at it. In the case of the Columns block, I should be able to tell how many columns it contains, where the columns start and end, and where I have to click to enter content

## Current Behavior
The current styling makes this block almost impossible to use

_Firefox Quantum 58.0.2 (64-bit)
Gutenberg 2.2.0
WP 4.9.4_

**Comment by karmatosed** [comment]
I don't think as we show this in the advanced settings we need to also have this indicated anywhere. The advanced settings you don't show in your screenshot would show the number of columns. Let's close this for now. As with every issue though we can always consider and reopen.

**Comment by maddisondesigns** [comment]
You shouldn't have to specifically click on the advanced settings in the sidebar to tell how many columns it has. You should be able to tell, just from looking at it. It's ridiculously hard trying to insert content into a column in the column block when you don't know where to click.
