### ISSUE TITLE
Reusable block/Pattern: option to create does not appear when editing content in site editor

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#51310]
### Description

When editing content in the site editor the option to `Create Reusable block` does not appear in the block overflow menu.

### Step-by-step reproduction instructions

- In the Site editor select the `Pages` option from the left menu
- Choose a page to edit and while editing the page content add a new block and in the block overflow menu notice that there is not option to `Create Reusable block`

### Screenshots, screen recording, code snippet

<img width="576" alt="Screenshot 2023-06-08 at 11 59 01 AM" src="https://github.com/WordPress/gutenberg/assets/3629020/f9a1d462-96d7-444c-ab7e-ff9d1650ec4a">

### Environment info

WP 6.2.2 & Gutenberg  16.0.0-rc.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
If I am reading the code correctly, it is because the rootClientId is not provided for this check?
https://github.com/WordPress/gutenberg/blob/af38c95e3777b562bdf509647c228c78d68c467a/packages/reusable-blocks/src/components/reusable-blocks-menu-items/reusable-block-convert-button.js#L68

**Comment by glendaviesnz** [comment]
> If I am reading the code correctly, it is because the rootClientId is not provided for this check?
> 
> https://github.com/WordPress/gutenberg/blob/af38c95e3777b562bdf509647c228c78d68c467a/packages/reusable-blocks/src/components/reusable-blocks-menu-items/reusable-block-convert-button.js#L68

Seems like [getBlockEditingMode](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/store/private-selectors.js#L76C19-L76C36) was the selector that was returned `disabled` if rootClientID was not explicitly set, but not 100% sure why yet - but a [PR that adds the rootClientID is here](https://github.com/WordPress/gutenberg/pull/52671), and this does fix the issue, but I need to do some more testing to make sure there are no other side effects.
