### ISSUE TITLE
Columns block highlighting is confusing

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#5132]
## Issue Overview
After clicking on the Columns block, the border goes to a dark grey, which looks like it's been selected, because it's a different colour to everything else. In actual fact though, when you look at the sidebar settings it shows it's unselected.

Clicking on the block again changes the colour to the exact same (Light Grey) colour as the rest of the ui, but this time the block is selected.

![gutenberg-columnsblock2](https://user-images.githubusercontent.com/2078245/36363319-334efabc-1590-11e8-8e38-d55bee0294fb.png)

## Steps to Reproduce (for bugs)
1. Insert Columns block
2. Try to select it

## Expected Behavior
I expect to be able to clearly differentiate when something is selected or not selected. The current choice of colours is extremely confusing.

## Current Behavior
Clicking on the block changes it's colour which would indicate that something's been 'selected'. This is not the case.

_Firefox Quantum 58.0.2 (64-bit)
Gutenberg 2.2.0
WP 4.9.4_

**Comment by SuperGeniusZeb** [comment]
This appears to be fixed in Gutenberg 2.6.

**Comment by SuperGeniusZeb** [comment]
@maddisondesigns I can not close it, because I am not a developer and I do not have the ability to close the issue. :stuck_out_tongue:

Pinging @karmatosed, who can close the issue.
