### ISSUE TITLE
Columns Block toolbar is inconsistent

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#5133]
## Issue Overview
After entering text in a Paragraph block I then clicked on the Columns block. The Columns block showed a toolbar that had formatting icons such as Left/Right Alignment, Bold, Italic & Links, among others.

Clicking on the Block again the toolbar disappears. Clicking on the block a third time the toolbar changes to only show the Wide & Full icons.

![gutenberg-multicolumns4](https://user-images.githubusercontent.com/2078245/36363572-53415cfa-1592-11e8-8f99-ccd1421432ec.gif)

## Steps to Reproduce (for bugs)
1. Insert Columns block
2. Insert Paragraph block into Columns Block
3. Insert text into a Paragraph block
4. Click on Columns block (toolbar with Left/Right Alignment, Bold, Italic etc. appears)
5. Click on Columns block (toolbar disappears)
6. Click on Columns block (toolbar with Wide & Full icons appears)

## Expected Behavior
I expect toolbars to be consistent

## Current Behavior
I have no idea what toolbar is supposed to show when clicking on a Columns block as it shows different ones each time you click on it

_Firefox Quantum 58.0.2 (64-bit)
Gutenberg 2.2.0
WP 4.9.4_

**Comment by StaggerLeee** [comment]
I personally have difficult to use columns block. Some top visual builder plugins solved it more, more elegant and better.

**Comment by theleemon** [comment]
This minimalist distraction-free ui trend is annoying

**Comment by maddisondesigns** [comment]
Updated to v2.5 and this is still happening

**Comment by SuperGeniusZeb** [comment]
I am unable to reproduce this in Gutenberg 2.6... actually, it looks like the Columns block does not have any toolbar options in Gutenberg 2.6. Now that I think about it, if the proposed Section block in #4900 gets added, the Columns block would not need the wide/full options. Additionally, the columns block should never have been showing the text formatting options of the Paragraph block in the first place. It appears that has been fixed.

**Comment by maddisondesigns** [comment]
@SuperGeniusZeb I can't reproduce the original issue either, in v2.6, and as you said, now there's no toolbar showing at all. Regardless of whether #4900 gets implemented, shouldn't there be a Wide & Full icons, so that I can change the width of my columns? Even if there's a Section block, that's not going to control the width of the content within that section.

**Comment by SuperGeniusZeb** [comment]
@maddisondesigns Oh, I thought the wide/full options on the proposed Section block would affect the contained content as well. Since that is not the case then the Columns block should definitely have the wide/full options as well.

**Comment by SuperGeniusZeb** [comment]
@maddisondesigns Actually, did the Columns block ever actually have the Wide/Full buttons in the first place? I think they may have only ever appeared to exist for the block due to this bug. I think this issue can be closed and a new one can be opened requesting that the Wide/Full options be added to the Columns block.

**Comment by GlennMartin1** [comment]
@maddisondesigns, can you confirm this is resolved, and if so close this issue?

**Comment by maddisondesigns** [comment]
This looks like it's been resolved.
