### ISSUE TITLE
Menu items cannot be selected when the overlay menu is expanded.

### ISSUE THREAD

**Issue by torounit** [WordPress/gutenberg#51330]
### Description

In the editor, when the navigation is expanded, the navigation block cannot be selected if the focus moves to anything other than the navigation.

This is caused by `useDisabled` setting the `inert` attribute to `wp-block-navigation__responsive-container is-menu-open`. IMO.

Once in this state, it becomes difficult to close the overlay menu, and you can't touch the navigation unless you select the navigation block again from the list view.

It is more likely to occur when the overlay menu is set to `Always`, but it also occurs when the menu is set to `Mobile`.

### Step-by-step reproduction instructions

1. Go to site editor.
2. Go to Navigation block setting.
3. Set `Always` to OVERLAY MENU.
4. Open overlay menu in editor.
5. Click on a non-menu item.

 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1908815/27804d7d-f2d4-4d06-b954-dcf440ff4170

### Environment info

- Gutenberg 16 or WordPress 6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ghorivipul97** [comment]
Hello @torounit 
assign issues to me.
I will start to work on it

**Comment by ndiego** [comment]
Hi @ghorivipul97 are you still working on this?

**Comment by annezazu** [comment]
I wasn't able to replicate this problem with RC 2. @torounit can you replicate and/or provide more information? In my case, I found that I couldn't select other blocks outside of the navigation block when the overlay was active:

https://github.com/WordPress/gutenberg/assets/26996883/26a98d22-92da-4ca7-b11c-52805c01a6ea

**Comment by torounit** [comment]
@annezazu 
I tried a little with WP 6.3-RC2 and this issue seems to be resolved.

Perhaps it was fixed by https://github.com/WordPress/gutenberg/pull/51378.
