### ISSUE TITLE
Up Arrow Keypress won't move caret from empty block in Safari

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#51351]
### Reproduction
- In Safari
- Add New post
- Press Enter key several times to create new empty paragraphs
- Use up arrow key to try to move caret to previous block
- Caret does not move

Expected: Caret would move to previous block

### Video
https://github.com/WordPress/gutenberg/assets/967608/751015d5-5ca5-4071-9713-2d726d21e99d

**Comment by jordesign** [comment]
Confirmed this behaviour in Safari when testing

**Comment by annezazu** [comment]
Closing this out as a duplicate of https://github.com/WordPress/gutenberg/issues/53333.
