### ISSUE TITLE
Different look backend vs frontend. Blocks have less width compared to frontend.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#51371]
### Description

Hei

I have come across this a few times. It might be me misunderstanding a setting.

I have noticed the frontend looks like this:
![Screenshot 2023-06-09 at 12 25 49](https://github.com/WordPress/gutenberg/assets/5323259/8d92ba44-dfc8-491b-be6b-084dec50a376)

Clicking to edit the front  page going to the backend in the post editor it looks like this:
![Screenshot 2023-06-09 at 12 26 03](https://github.com/WordPress/gutenberg/assets/5323259/bfaedc7f-e060-4d9d-bab5-4792df6c1019)

Clicking to edit the Front Page template I see this:
![Screenshot 2023-06-09 at 12 29 48](https://github.com/WordPress/gutenberg/assets/5323259/7217c90a-543c-4166-9ec1-e5511ea60533)

I am using Twenty Twenty Three. WordPress 6.2.2. Various plugins as well as the latest Gutenberg plugin. As I mentioned I have seen this earlier. I do not understand why the Post Editor is showing the full width block smaller in the backend.

### Step-by-step reproduction instructions

-

### Screenshots, screen recording, code snippet

-

### Environment info

-

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ndiego** [comment]
This is due to "Inner blocks use content width" not being enabled on the Post Content block. I would consider this a bug, though, because there are some default widths that get applied in the Post Editor if there is no layout setting. I believe this might be a backward compatibility thing, but a confusing experience nonetheless for block themes.

**Comment by ndiego** [comment]
cc @andrewserong @tellthemachines any chance you would be able to look at this when you have a second? The following CSS still get applied in the Post Editor, even when Inner blocks use content width" is disabled. Note the `720px` is the `contentSize` in the theme I am testing. 

<img width="906" alt="image" src="https://github.com/WordPress/gutenberg/assets/4832319/ebebca3f-a403-4e60-9fa8-a8776aef6509">

**Comment by tellthemachines** [comment]
Thanks for reporting, this looks like a bug in the post editor styles. Looking into it!
