### ISSUE TITLE
Navigation on Browse Mode: Can't delete empty navigations

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#51417]
## What problem does this address?
When a navigation is empty it's not possible to delete it in browse mode:
<img width="357" alt="Screenshot 2023-06-12 at 13 54 23" src="https://github.com/WordPress/gutenberg/assets/275961/cf027536-1ad2-49d6-b144-4af3dd8a6c4f">

## What is your proposed solution?
All navigations should be deletable.

**Comment by getdave** [comment]
Closed in https://github.com/WordPress/gutenberg/pull/51420
