### ISSUE TITLE
Stylebook Headings: Wrong number of colors per row

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#51424]
### Description

In the Style Book > Colors > Headings only 5 colors are displayed per row, instead of the default 6.

### Step-by-step reproduction instructions

1. Go to the Style Book > Colors > Heading
2. See the colors being mixed up.

### Screenshots, screen recording, code snippet

<img width="280" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/016837e6-c718-49d2-9575-12b3eab1d0ff">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Thanks for reporting @hanneslsm. This issue has been resolved in the latest version of Gutenberg and will be included in [WordPress 6.3](https://make.wordpress.org/core/6-3/). Let me know if I can help further.
