### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by ACGtutusang** [WordPress/gutenberg#51423]
### Description

I don’t know why, after I installed a certain plugin and edited a new article, when I edit the title of the article, Gutenberg can run normally, but when I click on the body text content edit box, this error appears: Error : Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
I tried disabling all plugins and this error still doesn't go away;
Oddly enough, Gutenberg occasionally works fine when I repeatedly edit new articles.

### Step-by-step reproduction instructions

1.Install new plugins
2.edit new article
3.error occurred
4.Disable all other plugins
5.Still getting an error

### Environment info

wp：6.2.2

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@ACGtutusang, can you provide the plugin name that causes this issue?

**Comment by ACGtutusang** [comment]
umm......It's solved now, maybe it's my browser's problem, I changed Google
Chrome, and there is no more error

George Mamadashvili ***@***.***> 于2023年6月13日周二 00:42写道：

**Comment by Mamaduka** [comment]
Thanks for the update, @ACGtutusang!

What browser were you using before?

I'll close the issue, but feel free to re-open it if you start experiencing the error again.

**Comment by ACGtutusang** [comment]
Because I am in China, I use QQ browser，It is produced by Tencent；
I have to say that this browser is terrible, but because I'm used to using
QQ Browser, I didn't use Google browser to use Gutenberg at the first time
