### ISSUE TITLE
Make 'Back' button in Site Editor drilldown behave more predictably

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#51421]
Although not technically a bug, the following feels quite confusing to use:

* Open Site Editor
* Click Pages
* Click 404
* Click Back
* Land on _Templates_ panel

The expectation is that you'd be taken back to the referring panel, IE Pages, rather than Templates. The current behavior is quite annoying, because it requires several clicks to get back to the original view.

This essentially the same problem described in https://github.com/WordPress/gutenberg/issues/50676. The conversation there seemed to settle on the idea of adding a conditional behavior to the back button to handle these situations.

* There should be a canonical destination for the back button in all panels. This functions as the default, accounting for most flows and any direct inbound links.
* If the panel is 'opened' from a non-canonical referrer, (e.g. clicking 404 in the Pages panel), then the back button should return you to that referrer instead.

It's quite likely that other detail panels could begin to include these non-linear links, so it would be good to get a 'fix' for this up and running to see how it feels in practise in order to make an informed decision around the behavior for 6.3.

**Comment by Ren2049** [comment]
@ndiego 

The placement of the back arrow next to the heading makes the site editor navigation 10x more confusing, prompting people to actually click one page back to get to what the heading says. [This idea](https://github.com/WordPress/gutenberg/issues/50676#issuecomment-1552260705) in #50676 is a lot more user friendly.

I've also created an issue about this before but it got buried. #50715

There's even visual proof from a YT video where site editor UX is pitted against a newer classic customizer theme.

**Comment by jameskoster** [comment]
@Ren2049 there could indeed be room for manoeuvre in terms of the button placement/appearance, there's a lot of good discussion around that in the issue you referenced. But I'd like to keep this issue laser-focussed on updating the behavior in order to fix the flows described in the OP.

**Comment by ndiego** [comment]
@jameskoster is this safe to punt to 6.4, or is this being actively worked on? Just trying to tidy up the 6.3 Board 😅

**Comment by jameskoster** [comment]
The problem isn't as wide-spread as it might have been after changes to the Navigation panel, but I'd still like to see this one included, personally. Changing drilldown behavior later isn't going to be ideal.

What do you think @annezazu @richtabor ?

**Comment by annezazu** [comment]
I agree completely. I think this is key to address for 6.3 and should be a part of blessed work.

**Comment by ndiego** [comment]
Given the feedback above, moving this to Todo.

**Comment by noisysocks** [comment]
Let's consolidate discussion in https://github.com/WordPress/gutenberg/issues/50676.
