### ISSUE TITLE
Gradient: Previews are not displayed correctly when using variables

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#51444]
### Description

I am using my theme.json to define my color palette.
<img width="486" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/7e4d74e7-d14c-4dcd-bf00-aa0bca041bfd">

Those colors should be used for gradients then:
<img width="1108" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/4b81d718-bdce-4cb8-ac66-96be022e30e3">

This is working, the selected block will have the correct color gradient. However, the previews are not displayed correctly which makes them practically useless.
<img width="614" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/d3d08f20-6ead-4481-8a09-4646b8330aeb">

### Step-by-step reproduction instructions

see above

### Screenshots, screen recording, code snippet

see above

### Environment info

- WP 6.2
- GB 15.9.1
- Custom theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hanneslsm** [comment]
Also, in the inspector panel it displays the Background Color / Gradient not to be defined, even though a Gradient is clearly selected.
<img width="579" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/78c192a0-ea50-41ab-bfeb-51c8c0be7efc">

**Comment by t-hamano** [comment]
Hi @hanneslsm,

You might try removing the semicolon (`;`) at the end of the `gradient` property value. I used to have a similar problem with Twenty Twenty Three Theme and was able to solve it by removing the trailing semicolon.

https://github.com/WordPress/wordpress-develop/pull/3715/files

**Comment by hanneslsm** [comment]
🫠
Solved. Thank you!
