### ISSUE TITLE
Track Navigation related code duplication in codebase

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#51455]
Please see https://github.com/WordPress/gutenberg/issues/51446

---------

As the scope of "Navigation" extends outside of the `core/navigation` block we are observing a proliferation of Navigation related code.

Whilst this is currently (relatively) manageable - and we should be mindful of the need not to pre-optimise - it's important we keep track of this for reference and potential future refactorings.

As and when instances of duplication of variance are discovered we should note them here:

- X
- Y
- Z

**Comment by MaggieCabrera** [comment]
https://github.com/WordPress/gutenberg/issues/51446 @scruffian opened an issue already :D

**Comment by getdave** [comment]
Haha! We discussed it but I thought I'd help him out. I"ll close this one out.
