### ISSUE TITLE
List view disappears from TopToolbar after initial load

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#51468]
### Description

Situation: 
The TopToolbar is enabled in the Block editor settings
Now, the Page template is loaded. You can see the List View in the Top Toolbar. But when you click on any other block, the icon disappears and it's not coming back, unless the user leaves the template editing mode and loads the template again from the left menu. 
The list view icon only appears when the template is loaded into the editor. In subsequent editing steps the List view disappears. 

[_reported by Hans-Gerd Gerhards on FSE 24_](https://make.wordpress.org/test/2023/06/07/fse-program-testing-call-24-momery-makeover/#comment-3083)

I was able to reproduce it. 

### Step-by-step reproduction instructions

- Theme Twenty-Twenty-Three is active
- Enter the Editor
- Select Templates from the left menu
- Select Page 
- Enable the TopToolbar 
- Try to open the List view after you clicked on some blocks in the template. 

### Screenshots, screen recording, code snippet

This video should show the issue

https://github.com/WordPress/gutenberg/assets/39980/7b87f390-9d43-4762-978a-00dee538c05b

### Environment info

- WP 6.2.2
- Theme: Twenty-Twenty-Three
- Gutenberg Nightly 16.1.20230613
- Chrome 114.0.5735.106
- MacOS 13.3.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
You have to click the up arrow, the first icon to the right of the blue inserter. The Top Toolbar design will change a lot in 6.3 and take some getting used to for folks. 

![list-view](https://github.com/WordPress/gutenberg/assets/4832319/8443e5ce-9b76-4054-aa14-8ad44076f549)

**Comment by bph** [comment]
Ha. That's interesting. The icon doesn't really lend itself to finding the way around, especially because it's a variation of the undo/redo icon. :-) Thanks for setting us straight, @ndiego 

I close the issue. It's not a bug. It's by design.
