### ISSUE TITLE
The enabled option triggers an error on useEntityRecord if set to false.

### ISSUE THREAD

**Issue by jdm-web** [WordPress/gutenberg#51466]
### Description

Setting the enabled: false option when using useEntityRecord triggers a destructuring error instead of deactivating the query : 
Uncaught TypeError: Cannot destructure property 'data' of 'useQuerySelect(...)' as it is null.
    at useEntityRecord (core-data.js?ver=60feb4306fe9534bc937:6862:11)

### Step-by-step reproduction instructions

1. Create any kind of block
2. Try to use getEntityRecord with valid info, for example `const {record, isResolving} = useEntityRecord('postType','post',1);`
3. Assert it works
4. Add, the {enabled: false} option as a fourth parameter
5. It should trigger the error

### Screenshots, screen recording, code snippet

When looking at the current useEntityRecord source code, I can see why we have this error.

Here, if options.enabled is false, we return null : https://github.com/WordPress/gutenberg/blob/trunk/packages/core-data/src/hooks/use-entity-record.ts#L184-L185

Then, if I understand correctly the function tries to extrapolate data: record, ...querySelectRest from null (https://github.com/WordPress/gutenberg/blob/trunk/packages/core-data/src/hooks/use-entity-record.ts#L182), resulting in the given error.

### Environment info

- WP 6.2.2
- MacOs BigSur 
- Chrome 114.0.5735.106

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @jdm-web,

Thanks for the report. I believe #51534 will solve this problem.

**Comment by jdm-web** [comment]
Great, thanks @t-hamano !
