### ISSUE TITLE
Link Target Attributes

### ISSUE THREAD

**Issue by richardkentgates** [WordPress/gutenberg#5147]
I noticed since beginning use of this plugin that the editor has no way to open links in new tab/window. Now at 2.2.0, manually entering the target attribute, it is completely removing the attribute in mid-typing. Once I get the attribute to target="" without any parameter/value, the editor removes it. I hope this is a glitch and not intentional. I haven't read anywhere that opening links in new tabs is bad for UX or anything else that justifies this. Whatever is making this happen needs to be removed from the project.

**Comment by Soean** [comment]
The `open in new window` option was removed in #4583

Which block type are you using to enter the link attribute manually? I was not able to recreate this bug.

**Comment by richardkentgates** [comment]
I am using an up-to-date version of WordPress with the Gutenberg plugin. It happens when I use a paragraph block. I haven't tried to recreate this with any other blocks. I tried editing as code but that also results in the attribute being removed. The only way to have the target attribute is to use the classic editor.

**Comment by richardkentgates** [comment]
I can understand not making this part of the WordPress platform, but editing it out when it's been manually placed is a bit of overreach.

**Comment by Soean** [comment]
Of course this should be possible. 
I testet again on the paragraph and was able to add `target="_blank"` to a link.

**Comment by richardkentgates** [comment]
Strange behavior. I'm not experiencing the same thing now. What to do with this thread?

**Comment by Soean** [comment]
Maybe you had a small typo in the attribute, then it gets deleted
