### ISSUE TITLE
6.3 Dev Note Tracking Issue

### ISSUE THREAD

**Issue by Leonardus-Nugraha** [WordPress/gutenberg#51484]
## Tracking all Dev Notes from Gutenberg plugin releases 15.2 - 16.1

Please read the information below carefully. If you have questions, connect with @Leonardus-Nugraha or @stevenlinx via Slack or comment here. 

Not all developer-related information needs to be in a separate DevNote on the Make Core blog for the field guide. We can group related information.  We can already make decisions on some features if it warrants a stand-alone blog post or if the information will be part of a group post. 

## Stand-alone post
To streamline the process and eliminate bottlenecks, all writers of stand-alone dev notes will write the dev notes on the Make Core Blog. If you need access to write on the Blog, connect with @hellofromtonya or @abhansnuk via Slack or comment here.
 
**Instructions**
<details>
- Create your note in a new post,
- Save as Draft
- Enable public preview
- Share the link to the public preview in a comment below, as "ready for review"
- "For dev notes, each one must have at least two reviewers" ([Handbook](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/))
</details> 
## Part of a group post
If the information related to your PR will be part of a group post, please write the **dev note in a comment on the PR**, so it can be reviewed and, if necessary commented on, by the release docs team or a reviewer. 

## Before you start writing  📣  please read the handbook pages: 
<details>
- ⭐️ [Writing developer notes](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/)
- ⭐️ [Style & Substance section](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#style-and-substance) of the Post & Comment Guidelines for Make Blog 
- ⭐️ [Documentation Style Guide](https://make.wordpress.org/docs/style-guide/) - Good for reference, when in doubt, especially when English is not your native language.
</details>

The list is incomplete. We are in the process of reviewing plugin release changelogs and add them as we progress on the task. 

There are two labels: 
[`needs dev note`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22) and [`has dev note`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Has+Dev+Note%22+) 

If you worked on a feature/module/component that definitely needs a dev note, please assign the label `needs dev note` If you already added the Dev Note to the make blog on draft or as a comment on the PR, please label it `has dev note` 

---

### Standalone dev notes:

Command Palette API
- [x] #50691 @youknowriad 
- [x]  #51169 @youknowriad 

Block Selectors API
- [x] #46496 @aaronrobertshaw 

Layout-related updates
- [x] #47858 @tellthemachines 
- [x] #47952 @tellthemachines 
- [x] #49050 @tellthemachines  
- [x] #49322 @tellthemachines 
- [x] #51434 @tellthemachines 
- [x] #50621 @andrewserong

Social Icons
- [x] #51020 @ndiego 

### Miscellaneous dev notes:
- [x] #50257 @ntsekouras
- [x] #49673 @kevin940726
- [x] #49649 @noahtallen 
- [x] #48286 @ellatrix 
- [x] #49655 @ellatrix 
- [x] #48076 @ellatrix 
- [x] #50385 @ntsekouras  
- [x] #50139 @ntsekouras
- [x] #50510 @scruffian

### To Do

Editor
- [x] ~#49475 @scruffian~ 
- [x] #51144 @glendaviesnz 

Blocks
- [x] ~#50643 @noisysocks~ 

Patterns
- [x] #47322 @jorgefilipecosta 

Data
- [x] #49134 @jsnajdr

**Comment by noahtallen** [comment]
The dev note I added under #49649 doesn't just apply to plugins, but it's a small enough change that I don't think it needs a separate post.

**Comment by kevin940726** [comment]
Added dev note in https://github.com/WordPress/gutenberg/pull/49673#issuecomment-1596742270 for the relevant part of the PR. LMK if there's anything else I should include! 🙇

**Comment by noisysocks** [comment]
> https://github.com/WordPress/gutenberg/pull/50643 @noisysocks

Decided to not make this API public for 6.3 so no dev note required yet.

**Comment by tellthemachines** [comment]
Dev notes for layout-related work:

[layout stabilisation](https://github.com/WordPress/gutenberg/pull/51434#issuecomment-1614142760)
[spacer block orientation](https://github.com/WordPress/gutenberg/pull/49322#issuecomment-1614140052)
[post template layout and spacing](https://github.com/WordPress/gutenberg/pull/49050#issuecomment-1614134942)
[compound layout class](https://github.com/WordPress/gutenberg/pull/47952)
[reduced specificity layout rules](https://github.com/WordPress/gutenberg/pull/47858)

Edit: added [layout definitions dev note](https://github.com/WordPress/gutenberg/pull/50621#issuecomment-1619352652).

(These could all go together in one layout-related post)

**Comment by tellthemachines** [comment]
## Ready for review

The draft post that groups all layout-related dev notes from the comment above: https://make.wordpress.org/core/?p=106122&preview=1&_ppp=f90c033a3b

**Comment by ellatrix** [comment]
Proposed Dev Note for the iframe PRs:

https://make.wordpress.org/core/?p=106178&preview=1&_ppp=c7bb7ce20d

> **Post Editor Iframed**
> 
> From WordPress 6.3, the post editor will be iframed if all registered blocks have a Block API version 3 or higher. Adding version 3 support means that the block should work inside an iframe, though the block may still be rendered outside the iframe if not all blocks support version 3.
> 
> It is worth noting that the Site Editor and Page Template Editor have always been iframed, alongside block and pattern previews, and will continue to be iframed regardless of the Block API version.
> 
> In order to make adoption easier, all assets (styles and scripts) added through the `enqueue_block_assets` PHP action will now also be enqueued for the iframe. See [this PR](https://github.com/WordPress/gutenberg/pull/48286).
> 
> Please try to make your blocks compatible, and let me know if you run into any problems or have suggestions. In a future version of WordPress, the editor content will load within an iframe regardless of the Block API version.
> 
> For more information about why we are iframing the editor content, see:
> 
> https://make.wordpress.org/core/2021/06/29/blocks-in-an-iframed-template-editor/ [embed]

**Comment by aaronrobertshaw** [comment]
Proposed dev note for the [Block Selectors API](https://github.com/WordPress/gutenberg/pull/46496):

https://make.wordpress.org/core/?p=106203&preview=1&_ppp=8dda7565b7

Unfortunately, I'll be AFK for a little over a week so might need someone to pick this up to address any feedback 🙏

**Comment by Leonardus-Nugraha** [comment]
Thanks @ellatrix , @aaronrobertshaw , @noahtallen , @kevin940726 , and @tellthemachines. I've reviewed the dev notes drafts, and they're up for final checking by @bph before publishing.

I'd also remind everyone that we still need dev notes for the following PRs. Can they be delivered this Friday, if possible?
https://github.com/WordPress/gutenberg/pull/48076 @ellatrix
https://github.com/WordPress/gutenberg/pull/49475 @scruffian
https://github.com/WordPress/gutenberg/pull/49655 @ellatrix
https://github.com/WordPress/gutenberg/pull/50257 @ntsekouras
https://github.com/WordPress/gutenberg/pull/51144 @glendaviesnz 
https://github.com/WordPress/gutenberg/pull/50139 @ntsekouras
https://github.com/WordPress/gutenberg/pull/50385 @ntsekouras
https://github.com/WordPress/gutenberg/pull/51020 @ndiego
https://github.com/WordPress/gutenberg/pull/47322 @jorgefilipecosta
https://github.com/WordPress/gutenberg/pull/50621 @andrewserong
https://github.com/WordPress/gutenberg/pull/50510 @scruffian
https://github.com/WordPress/gutenberg/pull/50691 @youknowriad
https://github.com/WordPress/gutenberg/pull/51169 @youknowriad
https://github.com/WordPress/gutenberg/pull/49134 @jsnajdr

**Comment by andrewserong** [comment]
Thanks for the ping @Leonardus-Nugraha!

> * https://github.com/WordPress/gutenberg/pull/50621 @andrewserong

@tellthemachines added one for this PR in https://github.com/WordPress/gutenberg/pull/50621#issuecomment-1619352652, which can most likely be combined with the other layout dev notes.

**Comment by Leonardus-Nugraha** [comment]
Oh, sorry I missed that @andrewserong, @tellthemachines already added that to the draft for all Layout dev-notes.
Thanks!

**Comment by ntsekouras** [comment]
Dev notes:

- #50385: https://make.wordpress.org/core/?p=106414&preview=1&_ppp=089d5555b3
- https://github.com/WordPress/gutenberg/pull/50139: https://make.wordpress.org/core/?p=106407&preview=1&_ppp=3857824d9f
- https://github.com/WordPress/gutenberg/pull/50257:  https://make.wordpress.org/core/?p=106417&preview=1&_ppp=22472e2484

**Comment by youknowriad** [comment]
I've prepared a draft for the command center dev note https://make.wordpress.org/core/?p=106472&preview=1&_ppp=86b7098999 but the problem is that most of this post has been copied form the request for feedback we previously published in https://make.wordpress.org/core/2023/05/17/command-center-request-for-feedback/ since the API didn't change. I think it's fine but wanted to mention just in case.

**Comment by afragen** [comment]
I’ve prepared a draft for the dev note on the Rollback feature. I could use some feedback please. 
https://core.trac.wordpress.org/ticket/51857
https://core.trac.wordpress.org/changeset/55720

https://make.wordpress.org/core/?p=106222&preview=1&_ppp=ca484d09ed

**Comment by ndiego** [comment]
Sorry for the delay! I'll get https://github.com/WordPress/gutenberg/pull/51020 done by Friday.

**Comment by scruffian** [comment]
> https://github.com/WordPress/gutenberg/pull/49475 @scruffian

This is a private API so I think we don't need a post about it.

**Comment by scruffian** [comment]
> https://github.com/WordPress/gutenberg/pull/50510 @scruffian

Draft here: https://make.wordpress.org/core/?p=106719

**Comment by ndiego** [comment]
> https://github.com/WordPress/gutenberg/pull/51020 @ndiego

Sorry for the delay on this. The draft is here: https://make.wordpress.org/core/?p=106677&preview=1&_ppp=8c7d8f9fb4

**Comment by Leonardus-Nugraha** [comment]
Thanks @ntsekouras, @youknowriad, @scruffian, and @ndiego, for the dev notes!
We only have 3 PRs left to do:
https://github.com/WordPress/gutenberg/pull/51144
https://github.com/WordPress/gutenberg/pull/47322
https://github.com/WordPress/gutenberg/pull/49134
@glendaviesnz, @jorgefilipecosta, @jsnajdr, will we have dev notes for these PRs?

**Comment by glendaviesnz** [comment]
Sorry about the delay. this functionality has been a little in flux, [first draft for #51144](https://github.com/WordPress/gutenberg/pull/51144#issuecomment-1637348305) up.

**Comment by Leonardus-Nugraha** [comment]
Thanks @glendaviesnz!

@youknowriad are you planning to add video to your Command Palette API dev note? https://make.wordpress.org/core/?p=106472&preview=1&_ppp=86b7098999

**Comment by bph** [comment]
@scruffian do you have an code example for the dev note https://make.wordpress.org/core/?p=106719 on the prioritizing blocks in the inserter? I think it would be more helpful.

**Comment by ndiego** [comment]
Thanks for the review @Leonardus-Nugraha, the Dev Note for https://github.com/WordPress/gutenberg/pull/51020 is now published [here](https://make.wordpress.org/core/2023/07/17/social-icons-block-applied-colors-now-dynamically-update-based-on-theme-json-and-global-styles/).

**Comment by ellatrix** [comment]
What is the review process of getting the iframe note published? Here is a refreshed link: https://make.wordpress.org/core/?p=106178&preview=1&_ppp=095d4a9810

**Comment by Leonardus-Nugraha** [comment]
@ellatrix thanks! I've added that dev notes to the Miscellaneous Editor dev notes post, scheduled for publishing today

**Comment by scruffian** [comment]
> @scruffian do you have an code example for the dev note https://make.wordpress.org/core/?p=106719 on the prioritizing blocks in the inserter? I think it would be more helpful.

I updated the post with some pseudo code, it's hard to give a real example because of the different ways you might implement `useInnerBlocksProps`, which could make the example more confusing!

**Comment by jsnajdr** [comment]
@Leonardus-Nugraha For #49134, the "dev note" would be one or two short paragraphs. I don't think it warrants its own blog post. I'd rather squeeze it as a section into some larger document ("other miscellaneous changes"), if anything like that exists.

**Comment by jorgefilipecosta** [comment]
Hi @Leonardus-Nugraha,
Here is the dev note for https://github.com/WordPress/gutenberg/pull/47322.
It is not an essential dev note it does not change behavior and is just an expansion of the API I guess it makes sense to publish it as part of other posts.

## Patterns on the create a new template modal

In WordPress 6.2, we introduced a new modal for creating templates. This modal presents the option to start a new template from a "blank" state or use the current fallback of the template. In WordPress 6.3, we expanded this modal's functionality to display patterns that are suitable for a given template.

For a pattern to appear in the modal, it needs to specify a property called templateTypes, which is an array containing the templates where the patterns can be used as the full content.

Here's an example that demonstrates adding a pattern to the start of a 404 template:
```
register_block_pattern(
	'my-patterns/404-template',
	array(
		'title'      => __( 'New 404 pattern', 'gutenberg' ),
		'templateTypes' => array( '404' ),
		'content'    => '<!-- wp:paragraph {"align":"center","fontSize":"x-large"} -->
						<p class="has-text-align-center has-x-large-font-size">404</p>
						<!-- /wp:paragraph -->',
	)
);
```

**Comment by ellatrix** [comment]
For the record, I added some extra info to the iframe section: https://make.wordpress.org/core/2023/07/18/miscellaneous-editor-changes-in-wordpress-6-3/#post-editor-iframed
