### ISSUE TITLE
Page Details View: Hide featured image if no image is applied

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51508]
As the Page Details view is currently not editable, I propose we don't render a "No featured image" indicator. Instead, only render the featured image if there is one present. If this was a DropZone (performing just like the other featured image uploader) then I think it'd be fine to keep. cc @WordPress/gutenberg-design 

<img width="466" alt="CleanShot 2023-06-14 at 15 55 02" src="https://github.com/WordPress/gutenberg/assets/1813435/fb0ad9c3-5d0f-4336-8d1c-25a69e9b3fd0">

**Comment by paaljoachim** [comment]
I went through the call for testing today and tested Gutenberg version 16.0.
I really enjoy seeing the information in the left sidebar as you show above, but I really missed being able to edit the information as we do in the right settings sidebar in a post/page.
It would be better to focus on adding functionality to this left sidebar area to give a consistent functionality that is similar to the right sidebar settings area.

**Comment by jameskoster** [comment]
It's still not 100% clear exactly which details will be editable here. If that picture was clearer I would agree with you @paaljoachim. But for now, I think hiding makes sense when no featured image is set.
