### ISSUE TITLE
Improve the Inserter experience when editing pages in the Site Editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#51538]
There are a couple of issues it would be nice to address in the page edit experience in the site editor.

1. If you open the Inserter _without first selecting the Post Content block_ it appears totally empty.
2. Dragging blocks from the Inserter to the canvas does nothing, despite the UI hinting that it will via `cursor: copy`.

<img width="1459" alt="Screenshot 2023-06-15 at 14 41 53" src="https://github.com/WordPress/gutenberg/assets/846565/00bc750f-0ccc-4248-b0de-f7dd9b44e553">

For the first issue, I understand this is because blocks cannot be added to the template when you're page editing. But the empty Inserter is a bit unexpected. We might try adding a notice that explains the situation, or alternatively: display the blocks and add some logic so that they get added as child blocks of Post Content on click.

For the second issue, perhaps a modal could appear if you drop a block outside of Post Content, explaining why you cannot do that, and providing a link to go edit the template. Alternatively we could just use `cursor: no-drop` on incompatible regions — this would be more elegant, but potentially confusing ("Why can't I drop this block here?").

cc @SaxonF @noisysocks since y'all worked on this and may have additional context.

**Comment by jameskoster** [comment]
@richtabor potentially one for [UX & Polish](https://github.com/orgs/WordPress/projects/96)?

**Comment by SaxonF** [comment]
We have inserter behaviour as a follow up task [here](https://github.com/WordPress/gutenberg/pull/50857). I've linked it to this post for further context.

**Comment by jameskoster** [comment]
Inserter is no longer empty when editing a page in the site editor which was the main issue here. Closing.
