### ISSUE TITLE
Author picker does not contain current author if more than 100 authors exist on site

### ISSUE THREAD

**Issue by StuartFeldt** [WordPress/gutenberg#5153]
## Issue Overview
The current limitation of the number of authors returned is 100.  If the current user's name is not within the first 100 alphabetically, it is not in the list.

## Steps to Reproduce (for bugs)
1. Create more than 100 authors
2. Login as a user that can edit posts with a user name that is > 100 in a list of alphabetized user names
3. See that the user name is not in the list

## Expected Behavior
The current author should always be available in the list, regardless of how many authors exist on a site.

## Current Behavior
Only the first 100 alphabetically are shown.

## Possible Solution
Increase the max number of authors, or force the current user into the list.

## Related Issues and/or PRs
#5072

**Comment by aduth** [comment]
Thanks for the report. This is being tracked at #4622.
