### ISSUE TITLE
Deleting templates produces no confirmation or undo, and deleting from the details panel sends you to an unexpected location

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#51530]
Templates can be deleted from various locations:

* Command palette
* Details panel
* Management table

In all of these flows, you are never asked to confirm whether or not to delete the template, and in most cases there is no Snackbar confirmation either. This trivialises what can be a very significant action and honestly feels a bit buggy.

When deleting a page, the following modal is displayed:

<img width="484" alt="Screenshot 2023-06-15 at 11 47 03" src="https://github.com/WordPress/gutenberg/assets/846565/208ae7d3-31e1-4a04-8158-8581f68f9aac">

It would be good to reuse this for templates too.

---

Additionally, if you delete a template from the details view, you get sent to the management view, which seems unexpected. In this flow it would be better to mimic the page deletion flow, IE be returned to the templates list view.

**Comment by Mamaduka** [comment]
@jameskoster, I think this is a duplicate of #47225.

**Comment by jameskoster** [comment]
You're correct!
