### ISSUE TITLE
Query Loop UI: Offer a way to override properties when the Query is set to inherit from the template

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#51535]
When a Query is set to inherit from the template in the UI, it will inherit _all_ properties and there is no way to edit any of them. 

However, in the code it is possible for a Query to both inherit, _and_ override the inherited properties. Twenty Twenty-Three [does this in the Home template](https://github.com/WordPress/twentytwentythree/blob/trunk/templates/home.html#L9).

The result is that the blog ignores the global `posts_per_page` value which can be confusing and feel buggy. It also means there's no way for the user to customise how many posts should appear per page which seems like an unnecessary limitation.

Since it's possible for the Query Loop to both inherit and override properties in the code, it seems this should be represented somehow in the UI as well.

**Comment by ntsekouras** [comment]
There shouldn't be any controls available in global query when we inherit from it. I'll create a patch to only use the `per_page` setting from options when we inherit and also to  properly update the inherit Query Loop blocks when the `per_page` option changes. That  would be enough for this [PR](https://github.com/WordPress/gutenberg/pull/51223) and I think we can close this issue..

---

PR here: https://github.com/WordPress/gutenberg/pull/51641

**Comment by jameskoster** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/51641
