### ISSUE TITLE
Cannot resize image galleries

### ISSUE THREAD

**Issue by mellis32** [WordPress/gutenberg#5154]
## Issue Overview
I noticed that Gutenberg's handling of image galleries has many issues. One of these issues that is very problematic for my site is the inability to resize galleries.  Right and left aligned galleries blow up and take up the width of the post, leaving no room for text.

Galleries I publish are not adhering to the size as previewed in the Gutenberg editor.

## Steps to Reproduce (for bugs)
1. Add Image gallery.
2. Align the gallery right or left.
3. Notice no option to resize gallery.

## Expected Behavior

I expect to be able to adjust the size of galleries in the Gutenberg editor.

**Comment by karmatosed** [comment]
You should be able to set an entire gallery size, the individual images adapt to that. I am trying to recreate and unable to. Can you please test using the latest version and maybe add screenshots? Ideally when testing so we are on the same page, could you use a default theme like Twenty Seventeen please?
