### ISSUE TITLE
Title block in Post Content results in loss of style controls in Site Editor

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#51549]
### Description

I ran into this when experimenting with TT3 and the Blank template. This is a common template for when you want to design a really custom layout that is unique to the individual page. In these scenarios, it is common to include the page's title as part of the content. 

With the new content edting functionality in the Site Editor, however, it seems to think that the Title block is part of the template instead of being part of the page's content. In addition to this bug, the Title block loses all styling control as well as the Advanced panel. See the video below.

### Step-by-step reproduction instructions

1. Using TT3, create a new page with a Blank template
2. Add a Title block to the page along with some addition text
3. Navigate to that page in the Site Editor
4. Notice that the Title block is getting "picked up" as being part of the template, rather than part of the page's content
5. Confirm that the styling options are not available to the Title block. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/4832319/f215330e-a2f2-4936-9986-50c7186c5728

### Environment info

- Gutenberg 16.0
- WordPress 6.2.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mov8cam** [comment]
I'm experiencing a similar issue with a template part. It's a query block to show the latest 3 posts, I now no longer get any styling controls on the title blocks. Can't change font size, etc. Tried deleting the block and adding it again, and same result - no styling.

In the list view, there is also no three dot menu on it, so you can't delete it either.

This only happens in template parts though. If I add a title block in a page it works as normal.

<img width="949" alt="Screenshot 2023-06-16 103522" src="https://github.com/WordPress/gutenberg/assets/112494308/5043161c-f860-40f5-97fa-0f3771beba13">

**Comment by noisysocks** [comment]
Thanks for the report! https://github.com/WordPress/gutenberg/pull/52351 fixed this.
