### ISSUE TITLE
Image block: Delayed response when opening image in lightbox for the first time

### ISSUE THREAD

**Issue by artemiomorales** [WordPress/gutenberg#51555]
### Description

When opening an image in the lightbox, there is a delay before the UI responds.

### Step-by-step reproduction instructions

Must be tested on a live (not local) environment.

1. Ensure the Gutenberg Interactivity API experiments are enabled.
2. Add an image to a post.
3. Enable the lightbox for the images in Advanced > Behaviors under the block settings.
4. Publish the post and click on the image.
5. See that there is a delay before the lightbox animation takes effect.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5360536/52ad93a6-0812-4faf-842b-aece256af86a

### Environment info

-Gutenberg 16.0.0, WP 6.2.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by luisherranz** [comment]
Why is the delay happening? Is it because it waits until the image has been downloaded?

**Comment by artemiomorales** [comment]
> Why is the delay happening? Is it because it waits until the image has been downloaded?

@luisherranz Yes, it's because it waits for the image to be downloaded.

**Comment by artemiomorales** [comment]
Note: While we are considering overall lightbox animation improvements, we could include [this suggestion](https://github.com/WordPress/gutenberg/issues/51055#issuecomment-1574849580) as part of the same PR.

>  I also wonder if you all considered a very slight zoom on hover so it’d anticipate the behavior.

**Comment by luisherranz** [comment]
Is it possible to use the original image first, then switch to the full version once it's downloaded?

**Comment by artemiomorales** [comment]
@luisherranz Will give that a shot! I'll also look into preloading the image on hover, which could at least help on desktop.

**Comment by artemiomorales** [comment]
This has been fixed in #51721
