### ISSUE TITLE
Improve Slash command search prioritiziation

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#5158]
We should consider improving how the slash command filters results. Right now, if you search for `/image` and press Enter, you get a Cover Image block. Presumably you wanted the Image block. This happens because C sorts before I alphabetically, but in practice this feels like the wrong behavior for the search command.

GIF:

![slashsearch](https://user-images.githubusercontent.com/1204802/36411678-fb5f00e8-1616-11e8-99fe-57991860df98.gif)

Although I only occasionally use the Cover Image block, I've mistakenly inserted it using the Slash command so often, it now shows up under Recent Blocks.

**Comment by karmatosed** [comment]
This seems like a great enhancement.

**Comment by bph** [comment]
more examples for surprising suggestions for slash command search  see gif. 
 
1) /t included heading and paragraph block 
2) /q only shows Quote (not Pullquote) 
![slashcommands](https://user-images.githubusercontent.com/39980/37230981-5a46d51a-23b7-11e8-9ddb-945d71e13596.gif)

**Comment by jasmussen** [comment]
Noting that the original intent of this issue is fixed in master now, and typing /ima gets you an Image, not a Cover Image. Keeping open per https://github.com/WordPress/gutenberg/issues/5158#issuecomment-371951072

**Comment by mtias** [comment]
Closing in favor of #5643 for further improvements.
