### ISSUE TITLE
Navigation: Focus mode inserter

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#51580]
## What problem does this address?
When in "focus mode" for the Navigation block, the main block inserter is empty:

<img width="919" alt="Screenshot 2023-06-16 at 13 57 39" src="https://github.com/WordPress/gutenberg/assets/275961/0128ca36-c640-400c-9e38-ef98abb74970">

## What is your proposed solution?
This inserter should append items to the navigation block, so it should show only items that can go inside a navigation block, and it should add items to the block. It should look like this: 
<img width="352" alt="Screenshot 2023-06-16 at 14 01 07" src="https://github.com/WordPress/gutenberg/assets/275961/fa8f447d-a5c7-4fff-b919-958a06132d6a">

**Comment by jameskoster** [comment]
Likely related to https://github.com/WordPress/gutenberg/issues/51538.

**Comment by getdave** [comment]
This mode no longer exists.
