### ISSUE TITLE
Add block: Preformatted/Code

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#516]
I'm seeing this block in the mockups, but no issue, so here is one for tracking. :)

Feel free to replace the description.

**Comment by jasmussen** [comment]
Nice. Here are the mockups I have for it.

Neutral:

![code neutral](https://cloud.githubusercontent.com/assets/1204802/25474083/25ea02b6-2b32-11e7-99ae-fe41e66a76b4.png)

Hover:

![code hover](https://cloud.githubusercontent.com/assets/1204802/25474087/28ab6e18-2b32-11e7-95b0-6b102459c96b.png)

Selected:

![code selected](https://cloud.githubusercontent.com/assets/1204802/25474090/2b2f776a-2b32-11e7-9baf-7cd33cebfda1.png)

**Comment by iseulde** [comment]
Looks good! One thing we might have to do (and makes a lot of sense) is splitting this into a preformatted block and a real code block. Preformatted is often used, not for code, but just to format the text e.g. for poetry.

The difference in markup is:

```html
<pre>text</pre>
```

```html
<pre><code>code</code></pre>
```

**Comment by iseulde** [comment]
Both are merged.
