### ISSUE TITLE
Browse mode / Navigation sidebar Pages: Focus style bleed through the sticky footer

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#51633]
### Description

With Gutenberg current trunk active, when I go to Appearance > Editor > Pages,
there is a sticky footer at the bottom of the dark grey left sidebar, which holds the link " Manage all pages".
When there are many pages in the menu, and you use the tab key to navigate the menu, focus can be placed on a menu item that is visually below the sticky footer, and when that happens, it looks like the focus is on an item in the sticky footer.

Could we make the focused menu item scroll into view?

### Step-by-step reproduction instructions

Activate a block theme
[Import the theme test data](https://github.com/WPTT/theme-test-data), so that you have a large number of published pages.
Go to Appearance > Editor, Pages.

Press the tab key repeatedly: 
Navigate past the Draft new page button to the list of pages.
On my screen, I navigated to the **10th** page in the list, and then the menu item is no longer visible.
The focus style is partially visible through the sticky footer.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/7422055/a2213a7c-a426-4493-a635-98fc46c5d366

### Environment info

WordPress 6.2.2
Gutenberg trunk
Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
There's no sticky footer anymore.
