### ISSUE TITLE
Remove "destructive" variant of Components

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#51639]
As mentioned by @jasmussen in https://github.com/WordPress/gutenberg/pull/50843 we should avoid the destructive variant of components.

Let's codify this convention by removing the props so as to avoid developers being able to introduce it into the codebase.       

-------

    > You should never see this. When there's only one menu, show it directly on this top level of the Navigation section, as per #50396:

This has been noted in https://github.com/WordPress/gutenberg/issues/51561 and we are fixing in https://github.com/WordPress/gutenberg/pull/51565

> Let's not use the red color for the button here. In general I think we should move away from "destructive colors" as they do not work well for color blindness

If that's the case then let's deprecate the props of the relevant `@wordpress/components` so that we _codify_ the convention 🙏

_Originally posted by @getdave in https://github.com/WordPress/gutenberg/issues/50843#issuecomment-1596721666_

**Comment by getdave** [comment]
Pinging @ciampo for his opinion here.

**Comment by jasmussen** [comment]
To add a little nuance, I think an argument can be made to keep the destructive color, for historical usage and for use cases like this one:

<img width="344" alt="Screenshot 2023-06-19 at 10 22 53" src="https://github.com/WordPress/gutenberg/assets/1204802/5d4abacb-9903-46a0-9b0e-b4563e4d3c0d">

My point with the comment was specifically that for [Confirm dialogs](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-confirmdialog--default) like the one employed for "Are you sure you want to delete this navigation menu", I consider that component to _be_ the warning that it is destructive, and not in need of further warning signals. To an extent I think of it as an extension of the JS `confirm` dialog, with very little to no styling options.

**Comment by getdave** [comment]
Ah ok so this Issue isn't warranted then and can be closed?

**Comment by jasmussen** [comment]
Not sure — I'd love to codify the practice, but I'm not sure if it should be in guidelines or whether the buttons inside a Confirm dialog can be locked down.

**Comment by getdave** [comment]
I was going to say I didn't think we have a standard "dialog" component but it looks like we do

https://wordpress.github.io/gutenberg/?path=/story/components-experimental-confirmdialog--default

So therefore we should check we don't have a prop on that component that allows for destructive.

I think we should close _this_ Issue however as I don't think it makes sense anymore.

**Comment by ciampo** [comment]
A bit late to this conversation!

`isDestructive` is a prop of [the `Button` component](https://wordpress.github.io/gutenberg/?path=/story/components-button--default&args=isDestructive:true). It serves uniquely to [add visual styles](https://github.com/WordPress/gutenberg/blob/19bcabfcbbc483028d1a429d9abe6a0fd595d233/packages/components/src/button/index.tsx#L129) to the `Button` component.

If we want to discourage using that prop, we could:
1. search across the Gutenberg and remove the prop from all usages of `Button`
2. deprecate the prop
3. We would need to understand if we also want to give a notice that, withing X WordPress released, the `isDestructive` prop (and related styles) will be removed from the component

**Comment by getdave** [comment]
@ciampo Apologies. It opened and closed too quickly. I was a bit hasty!

It looks like Joen was justing wanting to avoid "destructive" on confirmation dialogs. As we don't appear to have that prop exposed on the experimental dialogue component I think we're ok on that front now 🙇

**Comment by jasmussen** [comment]
Sorry about the detour! I think the conversation remains valid (but maybe it can be primarily conversation at this stage), "red" for "bad" isn't necessarily going to help any flows other than make one pause, and for actually destructive (no trash/revisions situations), an "Are you sure" seems better.

**Comment by ciampo** [comment]
In the case of "destructive" actions, showing a confirmation dialog definitely sounds like a good pattern.

IMO, color _can_ aid users in setting expectations around a piece of UI, but it should not be considered the main way that meaning is conveyed.

If at a later point we wanted to remove the destructive styles from `Button`, I reckon that [the plan highlighted above](https://github.com/WordPress/gutenberg/issues/51639#issuecomment-1597026501) should work (cc @mirka )

**Comment by jasmussen** [comment]
Yep, sounds good. We can shelve the conversation and revisit, my main purpose was mainly to omit the destructive color from modals and confirm dialogs, since in those cases you are already in the "are you sure" part of the flow, with no need to warn further.
