### ISSUE TITLE
Command Center: Some templates don't appear in results.

### ISSUE THREAD

**Issue by tjcafferkey** [WordPress/gutenberg#51657]
### Description

When testing the command center feature in the Site Editor against WooCommerce templates I noticed that they weren't appearing in the returned results.

It looks as if the template list is [sliced](https://github.com/WordPress/gutenberg/pull/49330/files#diff-8e2369ac87d157769a66ee5bf038af7b5c04d397092e59afa7d33ab6ec1c5190R48) and the resulting list of 10 is then used to filter against the input. If the expected template isn't in this ten then it looks like it won't be returned as a match.

Additionally if you save a customized version of a template e.g. `Single product` then it _does_ get returned in the results. I'm guessing because databased entries feature earlier in the list of templates and don't get cut off after the `slice` method is used.

Removing the `.slice` on `records` does return the expected results based on the available templates on the site.

### Step-by-step reproduction instructions

1. Install WooCommerce plugin with block theme
2. Go to Appearance > Editor > Select a template to edit
3. Using the command center (Hit command + K, or hit the input at top of screen) enter a Woo template (e.g. `Single product`)
4. See that this template isn't returned in the results.

### Environment info

- GB trunk
- WooCommerce 7.8.0
- WP 6.2.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
I ran into this as well in testing 6.3-RC1, without WooCommerce or any other plugin active, besides Beta Tester.

For example, when typing `single` into the Command Palette I expected to bring up the Single post template, but instead no results were found.

<img width="576" alt="Blog_Home_‹_Template_Part_‹_Editor_‹_LearnWP_—_WordPress" src="https://github.com/WordPress/gutenberg/assets/7662449/9f8b4e8a-f1ce-410e-92d7-b894aa21ce36">

### Expected

Typing the name of any template present in the active theme into the Command Palette should bring up the corresponding template.

**Comment by tjcafferkey** [comment]
I left a comment [here](https://github.com/WordPress/gutenberg/pull/49330/files#r1270602452) on the original PR with some suggestions, hopefully this will provide more context as to _why_ it is happening. I will likely try and open a PR soon with a proposed change to fix this.
