### ISSUE TITLE
Add DocumentActions to Style Revisions header

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51667]
Let's add the DocumentActions component to the header when style revisions are viewed. 

- [ ] Add DocumentActions to the header.
- [x] Update the "Global styles revisions" text to "Style revisions". 

<img width="1275" alt="CleanShot 2023-06-19 at 17 53 22" src="https://github.com/WordPress/gutenberg/assets/1813435/b6bf780c-83c2-4c74-a905-89cdaf842476">

![](https://user-images.githubusercontent.com/846565/247083337-ceb362b2-2833-45a8-a85d-89a49da8afe6.png)

Related issue for Style Book: https://github.com/WordPress/gutenberg/issues/54514

**Comment by richtabor** [comment]
I ran into this when reviewing https://github.com/WordPress/gutenberg/pull/51637

 <img width="568" alt="CleanShot 2023-06-19 at 17 56 09" src="https://github.com/WordPress/gutenberg/assets/1813435/9a1c5243-8777-4006-8375-b3259f77c288">

**Comment by jasmussen** [comment]
Good catch. We've referred to the feature as "global styles" (plural), and the inspector as "the style inspector". At any one time you're only looking at a single style. So should we have in the titlebar "Style revisions"? And in the command bar "Open style revisions"?

**Comment by jameskoster** [comment]
"Style revisions" makes sense to me.

Should it also take on the 'command palette' appearance, and suggest the actions added in https://github.com/WordPress/gutenberg/pull/51637?

<img width="431" alt="Screenshot 2023-06-20 at 11 11 48" src="https://github.com/WordPress/gutenberg/assets/846565/ceb362b2-2833-45a8-a85d-89a49da8afe6">

**Comment by richtabor** [comment]
> Should it also take on the 'command palette' appearance

Makes sense to use the title bar; style book could use it as well: 

<img width="1341" alt="CleanShot 2023-06-20 at 09 32 27" src="https://github.com/WordPress/gutenberg/assets/1813435/1d4b9446-a1f3-4ec5-9164-2ba4e25912b1">
