### ISSUE TITLE
Add deep link to a page's template in the Page Details view

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51665]
I expected to be able to navigate to a page's template by selecting it in the Page Details view. There's already a link within the Page Inspector > Template panel (second screenshot). Can we use that same logic for the template in the Page Details view? 

## Visuals

![CleanShot 2023-06-19 at 15 34 54](https://github.com/WordPress/gutenberg/assets/1813435/19dcb65f-5be4-4b94-83fd-35566ecb65c9)

<img width="953" alt="CleanShot 2023-06-19 at 15 36 18" src="https://github.com/WordPress/gutenberg/assets/1813435/c786d75a-60b0-4d96-a072-24d405b84338">

**Comment by youknowriad** [comment]
There's a deep link the template control of the document inspector and the details view is gone.
