### ISSUE TITLE
i18n: Add domain argument to localization functions

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#5167]
Gutenberg was localized without explicit domain in its [JavaScript gettext implementation](https://github.com/WordPress/gutenberg/tree/master/i18n) with the following assumptions in mind:

- It would make its way to core, where the default strings use the inferred empty domain
- At worst, a domain could be "injected" as part of the string extraction step as a parameter to the extraction utility

Since these assumptions do not hold true for plugin code, and we should seek to open up localization tools more broadly, we should introduce a domain parameter to the localization functions.

As part of this, we may consider being explicit in specifying `gutenberg` domain for strings within Gutenberg, since [we do this in PHP code](https://github.com/WordPress/gutenberg/blob/1ca5f6c1fbd813d33f69f249ac732e9f1c0ba3b2/gutenberg.php#L60) and Gutenberg is still technically a plugin. That said, the [plugin manifest](https://github.com/WordPress/gutenberg/blob/1ca5f6c1fbd813d33f69f249ac732e9f1c0ba3b2/gutenberg.php#L2-L10) does not specify the text domain.

This should not be a very difficult task, as it's merely a matter of adding the argument and using the [domain-prefixed Jed functions](http://messageformat.github.io/Jed/). For example:

__Before:__

```js
export function __( text ) {
	return getI18n().gettext( text );
}
```

([Reference](https://github.com/WordPress/gutenberg/blob/1ca5f6c1fbd813d33f69f249ac732e9f1c0ba3b2/i18n/index.js#L42-L44))

__After:__

```js
export function __( text, domain ) {
	return getI18n().dgettext( domain, text );
}
```

(Repeat for `_x`, `_n`, `_nx`)

**Comment by Rahmon** [comment]
dgettext function has 'domain' parameter. So the correct should be "return getI18n().dgettext( **domain**, text );". Right?

**Comment by aduth** [comment]
Yes, silly oversight on my part. Thanks for the correction! I've updated the original text.

**Comment by ocean90** [comment]
> That said, the plugin manifest does not specify the text domain.

You mean `Text Domain` and `Domain Path`? Both can be omitted if the plugin is in the plugin directory and requires at least WordPress 4.6. See https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#domain-path and https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain.
