### ISSUE TITLE
Content width bug with templates created with Wordpress 6.1

### ISSUE THREAD

**Issue by audunmb** [WordPress/gutenberg#51685]
### Description

If a custom page template has `<!-- wp:post-content {"layout":{"type":"default"}} /-->` instead of  `<!-- wp:post-content {"layout":{"type":"constrained"}} /-->` the buttons for Wide and Full width won't show, even if “Inner blocks use content width” seem to be enabled. 

There should be some kind of warning or that the template is outdated and may cause errors, and a way to automatically fix it. 

### Step-by-step reproduction instructions

1. Create a custom template (with Site editor) in Wordpress 6.1 or earlier. 
2. Make some customisations to the template and enable “Inner blocks use content width” in the Content block.
3. Update to 6.2 (or later) and update the theme. 
4. The buttons for content width (Wide and Full) are now missing in the controls for the block. 

If you disable the "Inner blocks..." in the template, save changes, enable it again and save anew, `"type":"default"` is changed to `"type":"constrained"` in the template code, and the issue disappears.

### Environment info

- Wordpress 6.2.2 with Twenty Twenty-Two 1.4 
- (not using the Gutenberg plugin).

### Please confirm that you have searched existing issues in the repo.

Yes

**Comment by aurooba** [comment]
Thanks for reporting this issue, @audunmb! Could you share a copy of the markup from the custom template you set up in WordPress 6.1 so we can test out the exact situation you encountered?

**Comment by audunmb** [comment]
This is the custom template html:
```
<!--` wp:group {"tagName":"main","style":{"spacing":{"margin":{"top":"0px"}}},"layout":{"type":"default"}} -->
<main class="wp-block-group" style="margin-top:0px">
<!-- wp:cover {"useFeaturedImage":true,"dimRatio":50,"overlayColor":"grey","isDark":false,"align":"full"} -->
<div class="wp-block-cover alignfull is-light"><span aria-hidden="true" class="wp-block-cover__background has-grey-background-color has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:post-title {"textAlign":"center"} /--></div></div>
<!-- /wp:cover -->

<!-- wp:post-content {"layout":{"inherit":true,"contentSize":"","wideSize":""}} /--></main>
<!-- /wp:group -->
```
As noted, changing to `{"layout":{"type":"constrained"}}` for the post-content-block solves the issue.

**Comment by jordesign** [comment]
Noting that the example HTML above had an error - I found this to work:

```
<!-- wp:group {"tagName":"main","style":{"spacing":{"margin":{"top":"0px"}}},"layout":{"type":"default"}} -->
<main class="wp-block-group" style="margin-top:0px">
<!-- wp:cover {"useFeaturedImage":true,"dimRatio":50,"overlayColor":"grey","isDark":false,"align":"full"} -->
<div class="wp-block-cover alignfull is-light"><span aria-hidden="true" class="wp-block-cover__background has-grey-background-color has-background-dim"></span><div class="wp-block-cover__inner-container">
<!-- wp:post-title {"textAlign":"center"} /--></div></div>
<!-- /wp:cover -->

<!-- wp:post-content {"layout":{"inherit":true,"contentSize":"","wideSize":""}} /--></main>
<!-- /wp:group -->
```

@audunmb just to double check your expectation - is it for the other alignment/width options to appear for the Post Content block within the template itself?

**Comment by jordesign** [comment]
@audunmb  - just checkin in again on the comment above...

 just to double check your expectation - is it for the other alignment/width options to appear for the Post Content block within the template itself?

**Comment by audunmb** [comment]
> @audunmb - just checkin in again on the comment above...
> 
> just to double check your expectation - is it for the other alignment/width options to appear for the Post Content block within the template itself?

No, the expectation is that the controls for alignment/width options is to appear in blocks within the Post Content block (ie when you edit a page and add groups and other blocks to the page).

**Comment by audunmb** [comment]
> Noting that the example HTML above had an error - I found this to work:
> 
@jordesign it's odd that the HTML generated by Wordpress has an error. It might be a copy/paste error.

To reproduce this issue:
Install Wordpress 6.1 (or earlier) and the TwentyTwentyTwo theme, create custom templates. Update to 6.2 and edit themes set with the custom templates.

**Comment by tellthemachines** [comment]
Hi @audunmb, the issue is with the Post Content markup you're using, specifically with its layout attributes:

`<!-- wp:post-content {"layout":{"inherit":true,"contentSize":"","wideSize":""}} /-->`

The `contentSize` and `wideSize` properties are here being set to empty strings, which overrides the theme `contentSize` and `wideSize` set in theme.json. Wide and full alignments can only exist if those properties are set. Removing both properties from the markup will fix the issue.

I'm going to go ahead and close this as it's not an actual bug. Thanks for reporting in any case!
