### ISSUE TITLE
WP_Env: tests-cli phpunit executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by JUVOJustin** [WordPress/gutenberg#51686]
### Description

I want to run my phpunit tests within wp-env tests-cli container as it is suggested in the documentation. However, when running `wp-env run tests-cli wp-env run tests-cli --env-cwd=wp-content/plugins/juvo-session-manager phpunit` i get the following error message: 

```
ℹ Starting 'wp-env run tests-cli phpunit' on the tests-cli container. 

OCI runtime exec failed: exec failed: unable to start container process: exec: "wp-env": executable file not found in $PATH: unknown
✖ Command failed with exit code 126
Command failed with exit code 126
```

Same command with composer does work. Also, when starting bash inside the container, i see that phpunit is generally available.

### Step-by-step reproduction instructions

1. Go into plugin folder
2. Star with `npm run wp-env start`
3. Run `wp-env run tests-cli --env-cwd=wp-content/plugins/juvo-session-manager phpunit`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bgoewert** [comment]
Just ran into this same issue. Using the latest package (8.5.0).

**Comment by antonlukin** [comment]
Confirmed on version 8.7.0. 
On 7.0.0 it works for me.

**Comment by dawidurbanski** [comment]
Same here. If I manually exec into the container (any of these: "mysql", "tests-mysql", "wordpress", "tests-wordpress", "cli", "tests-cli"), and I run `phpunit --version`, I get:

> bash: phpunit: command not found

So it looks like the phpunit executable is just not there at all.

**Comment by dawidurbanski** [comment]
As an alternative, if your project uses composer to install packages (mine does, only dev dependencies), you can install phpunit locally and use it this way.

Before:

```
$ wp-env run tests-cli --env-cwd=wp-content/plugins/myplugin phpunit

ℹ Starting 'phpunit' on the tests-cli container.

OCI runtime exec failed: exec failed: unable to start container process: exec: "phpunit": executable file not found in $PATH: unknown
```

PHPUnit installed locally (indirectly via [`PHPUnit Polyfills`](https://github.com/Yoast/PHPUnit-Polyfills)):

```
$ wp-env run cli --env-cwd=wp-content/plugins/myplugin composer install require --dev yoast/phpunit-polyfills:"^1.0"
```

then

```
$ wp-env run tests-cli --env-cwd=wp-content/plugins/myplugin ./vendor/bin/phpunit

.                                                                   1 / 1 (100%)

Time: 00:00.074, Memory: 36.50 MB

OK (1 test, 1 assertion)
```

Please note that I used PHPUnit Polyfills version 1. When trying this with version 2, I got plenty of exceptions and it didn't work (but that's another issue).

```
E                                                                   1 / 1 (100%)

Time: 00:00.122, Memory: 38.50 MB

There was 1 error:

1) SampleTest::test_sample
Error: Call to undefined method PHPUnit\Util\Test::parseTestMethodAnnotations()

/wordpress-phpunit/includes/abstract-testcase.php:547
/wordpress-phpunit/includes/abstract-testcase.php:137
/var/www/html/wp-content/plugins/myplugin/vendor/yoast/phpunit-polyfills/src/TestCases/TestCasePHPUnitGte8.php:60
```

**Comment by jrtashjian** [comment]
Here's what I found while investigating.

In the container:

- `phpunit` is not located within the `/usr/bin` or `/usr/local/bin` directories.
- You can find `phpunit` in the home directory of the container at `~/.composer/vendor/bin/phpunit`.

Additionally:

- The `yoast/phpunit-polyfills` composer package is globally installed during the construction of the container image, as indicated [here](https://github.com/WordPress/gutenberg/blob/069a8f882fdf5f3464ce54844f2297213f11a03a/packages/env/lib/init-config.js#L247-L253) which pulls `phpunit` into the global composer bin directory.

The issue:

- It appears that the composer directory containing `phpunit` is not added to the `$PATH`.

@dawidurbanski's solution works and is what I am doing in [my own projects](https://github.com/jrtashjian/omniform/blob/master/package.json#L22) as well.

You can also change the path in their solution like so to use the globally installed version in the meantime:

```
wp-env run tests-cli --env-cwd=wp-content/plugins/myplugin ~/.composer/vendor/bin/phpunit
```

Ultimately the global composer bin directory should be added to the `$PATH` in the container image.

**Comment by dawidurbanski** [comment]
> The yoast/phpunit-polyfills composer package is globally installed during the construction of the container image, as indicated [here](https://github.com/WordPress/gutenberg/blob/069a8f882fdf5f3464ce54844f2297213f11a03a/packages/env/lib/init-config.js#L247-L253) which pulls phpunit into the global composer bin directory.

Ah! This could explain why installing yoast/phpunit-polyfills:"^2.0" causes an issue. It's just a conflict between these two probably.

**Comment by jrtashjian** [comment]
What's interesting is that if I `echo $PATH` inside the container, the global composer bin directory is returned in the $PATH.

```
$ npx wp-env run tests-cli bash
ℹ Starting 'bash' on the tests-cli container. Exit bash with ctrl-d.

insidecontainer$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:~/.composer/vendor/bin
```

I actually missed this line where it is actually added to $PATH before the phpunit-polyfills package is installed.

https://github.com/WordPress/gutenberg/blob/069a8f882fdf5f3464ce54844f2297213f11a03a/packages/env/lib/init-config.js#L251

**Comment by dawidurbanski** [comment]
Interesting. Now I checked, if I do (I have wp-env installed in the project):

```
$ pnpm wp-env run tests-cli bash

> wp-env "run" "tests-cli" "bash"

ℹ Starting 'bash' on the tests-cli container. Exit bash with ctrl-d.

focus@a1151878116a:/var/www/html$ phpunit --version
PHPUnit 9.6.12 by Sebastian Bergmann and contributors.

xxxxx@a1151878116a:/var/www/html$
```

Hmmmm....

**Comment by dawidurbanski** [comment]
```
npx wp-env run tests-cli bash
ℹ Starting 'bash' on the tests-cli container. Exit bash with ctrl-d.

xxxxx@a1151878116a:/var/www/html$ phpunit --version
PHPUnit 9.6.12 by Sebastian Bergmann and contributors.
```

```
$ npx wp-env run tests-cli phpunit --version
8.7.0
```

There's different version returned if I use it when running from the inside of the container, and different when using directly as a command in the wp-env.

Also:

```
$ npx wp-env run tests-cli bash
ℹ Starting 'bash' on the tests-cli container. Exit bash with ctrl-d.

xxxxx@a1151878116a:/var/www/html$ phpunit
PHPUnit 9.6.12 by Sebastian Bergmann and contributors.

Usage:
  phpunit [options] UnitTest.php
  phpunit [options] <directory>

Code Coverage Options:
  --coverage-clover <file>    Generate code coverage report in Clover XML format
  --coverage-cobertura <file> Generate code coverage report in Cobertura XML format
  ....
  ....
```

But:

```
$ npx wp-env run tests-cli phpunit
ℹ Starting 'phpunit' on the tests-cli container.

OCI runtime exec failed: exec failed: unable to start container process: exec: "phpunit": executable file not found in $PATH: unknown
✖ Command failed with exit code 126
Command failed with exit code 126
```

**Comment by jrtashjian** [comment]
> ```
> $ npx wp-env run tests-cli phpunit --version
> 8.7.0
> ```
> 
> There's different version returned if I use it when running from the inside of the container, and different when using directly as a command in the wp-env.

8.7.0 is actually the version of `wp-env` and in the latest version if you want to pass flags to the command inside the container you need to put a double-dash before the flags like this:

```
$ npx wp-env run tests-cli phpunit -- --version
```

**Comment by dawidurbanski** [comment]
This might be issue with the shell version. This works when using `bash` but fails with `sh`.

I assume running wp-env command tries to run this with default shell. See this:

```
$ npx wp-env run tests-cli sh
ℹ Starting 'sh' on the tests-cli container.

/var/www/html $ phpunit
sh: phpunit: not found
```

**Comment by jrtashjian** [comment]
Possible culprit:

https://github.com/WordPress/gutenberg/blob/069a8f882fdf5f3464ce54844f2297213f11a03a/packages/env/lib/init-config.js#L175-L176

**Comment by jrtashjian** [comment]
PR up. It ended up being a difference in how `docker exec` compared to `docker run`. The `exec` command will run commands within an existing container but with `/bin/sh` as the environment unless it's changed at the time of running `docker exec`.

Putting `/bin/bash -c` before the command being executed in the `wp-env` script was the solution.

**Comment by jrtashjian** [comment]
@JUVOJustin, while we're awaiting approval/merge for the solution addressing the unavailability of global PHPUnit in https://github.com/WordPress/gutenberg/pull/54508, you can implement the interim solution outlined here: https://github.com/WordPress/gutenberg/issues/42286#issuecomment-1722362561
