### ISSUE TITLE
'Edit template' command appears out of context

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#51688]
When you're editing a page in the site editor, a contextual 'Edit template' suggestion appears when you open the command palette. Clicking this enables you to edit the template associated with the current page.

This 'Edit template' command also appears outside of the fullscreen editor if you search, and clicking it will do nothing:

<img width="1376" alt="Screenshot 2023-06-19 at 13 41 34" src="https://github.com/WordPress/gutenberg/assets/846565/981798eb-bd73-4daa-b769-136b8ef8ae93">

It probably makes sense to only surface this command in edit view, when you're editing a page.

cc @noisysocks

**Comment by richtabor** [comment]
An aside, but it would be nice if the template name was included in this commands. I.e. "Edit Index template". Related: https://github.com/WordPress/gutenberg/issues/51693

**Comment by noisysocks** [comment]
@richtabor I'll note that in https://github.com/WordPress/gutenberg/issues/51693.
