### ISSUE TITLE
Add context to the "Reset template" command

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51693]
Can we add the current template that would be reset to the existing "Reset template" command?

"Reset template" would become "Reset $templateName template". 

<img width="779" alt="CleanShot 2023-06-20 at 07 35 43" src="https://github.com/WordPress/gutenberg/assets/1813435/07a4d454-2a58-454e-ac60-863ef8d8394b">

**Comment by richtabor** [comment]
An aside, but perhaps the icon should be the arrow circle, without the clock hands as well — that's what we're using for revisions.

**Comment by noisysocks** [comment]
If we do this let's also make the same adjustment for the _Edit _template_ command.
