### ISSUE TITLE
i18n: Merge PHP and JS strings in POT generation

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#5169]
Related discussion: https://wordpress.slack.com/archives/C5UNMSU4R/p1519137264000547

The current [`npm run gettext-strings` script](https://github.com/WordPress/gutenberg/blob/1ca5f6c1fbd813d33f69f249ac732e9f1c0ba3b2/package.json#L143) will generate a `languages/gutenberg.pot` file using a [custom Babel plugin](https://github.com/WordPress/gutenberg/blob/master/i18n/babel-plugin.js), but only includes strings discovered in the JavaScript source, not those in PHP. The PHP strings can be generated by [i18n tools for PHP](https://codex.wordpress.org/I18n_for_WordPress_Developers#Using_the_i18n_tools).

Furthermore, it appears that the automatic plugin integration for Gutenberg + GlotPress will ignore the custom generated POT file and scan PHP files for strings, thereby ignoring the JavaScript strings altogether.

There are a few options to proceed here:

- We can generate a file which includes the JavaScript strings written as PHP equivalent function calls, which are detected by plugin integration automatically. This is a bit of a hack, but one which has served both [Yoast](https://github.com/Yoast/wordpress-seo/blob/trunk/grunt/custom/convert-pot-to-wp.js) and [WordPress.com Calypso](https://github.com/Automattic/i18n-calypso/blob/master/cli/formatters/php.js).
- We can work to improve GlotPress interoperability with projects with JavaScript localization, and include in our build step both JS and PHP string extraction with merge

In either case, we also want to ensure that, if possible, we only load strings into the browser which are relevant to JavaScript usage.

**Comment by swissspidy** [comment]
Option 1 is a hack and definitely not a long term solution.

For core, we need to pick up things like https://core.trac.wordpress.org/ticket/20491.

Pinging @ocean90

**Comment by ocean90** [comment]
This isn't about GlotPress, it's more the lack of a consensus on the implementation, see the linked ticket.

GlotPress itself already supports a few JS formats, see https://github.com/GlotPress/GlotPress-WP/tree/develop/gp-includes/formats. What's missing is how and especially for which functions JS files should get parsed to extract the translatable strings.

**Comment by aduth** [comment]
To clarify, [we have functions and we have extraction](https://github.com/WordPress/gutenberg/tree/master/i18n) in Gutenberg itself. The issue here is that we can extract JS strings, but need to reconcile those with PHP strings somehow.

And apparently "something" along the way in making the plugin available on the plugin repository prevents the `languages/gutenberg.pot` file from being respected. The assumption is that there's a mechanism which is ignoring it in favor of finding strings automatically from the PHP source.

Related: #5168, #5167

**Comment by swissspidy** [comment]
> And apparently "something" along the way in making the plugin available on the plugin repository prevents the `languages/gutenberg.pot` file from being respected. The assumption is that there's a mechanism which is ignoring it in favor of finding strings automatically from the PHP source.

Yes, POT files in a plugin are completely ignored and they've always been 🙂
Strings are extracted by WordPress.org, not the plugin itself. Ideally, WordPress.org extracts strings from both PHP and JavaScript. That's the whole point.

**Comment by ocean90** [comment]
See https://make.wordpress.org/meta/handbook/documentation/translations/#how-does-the-translation-system-import-strings-do-i-need-po-pot-files.

First we need a solution for core that can be adopted by Gutenberg (or the other way around) and other plugins, then we can set up WordPress.org to also extract JavaScript strings automatically.

**Comment by youknowriad** [comment]
I think we can close this one per #5310, it's a short-term solution but we can update once the extraction in WordPress.org is adapted to allow JS strings.
