### ISSUE TITLE
Dimensions controls missing with Non FSE Compatible Themes

### ISSUE THREAD

**Issue by naumanahmed19** [WordPress/gutenberg#51701]
### Description

Not sure if this is on purpose or a bug but if the theme is not FSE Compatible, dimensions controls do not show up.

![image](https://github.com/WordPress/gutenberg/assets/5273705/9d529208-7ad4-4508-8f5a-d443b4bef7fe)

### Step-by-step reproduction instructions

1. Activate any non-FSE theme, I am using Twenty NineteenVersion: 1.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @naumanahmed19,

The dimension control cannot be used without explicit opt-in. Opt-in methods vary depending on the type of the theme.

## Block Theme

- In `theme.json`, set `settings.appearanceTools` to `true`. This opts in all design tools in all blocks.
    ```json
    {
    	"$schema": "https://schemas.wp.org/trunk/theme.json",
    	"version": 2,
    	"settings": {
    		"appearanceTools": true
    	}
    }
    ```

- If you want to opt-in only for a specific block, say a paragraph block, you can define it as follows.
    ```
    {
    	"$schema": "https://schemas.wp.org/trunk/theme.json",
    	"version": 2,
    	"settings": {
    		"blocks": {
    			"core/paragraph": {
    				"spacing": {
    					"margin": true,
    					"padding": true
    				}
    			}
    		}
    	}
    }
    ```

## Classic theme with theme.json  (hybrid theme)

- For classic themes with `theme.json`, you can opt-in as with block themes.

## Classic theme without theme.json

- Only padding can be opted for in the theme support.
    ```php
    add_theme_support( 'custom-spacing' );
    ```

- If you run `add_theme_support( 'appearance-tools' );`, all design tools will opt-in. However, this only works if the Gutenberg plugin is enabled, and there are issues related to group blocking. [See](https://core.trac.wordpress.org/ticket/57649)

**Comment by t-hamano** [comment]
Hi @naumanahmed19,

I believe the issue you have reported is an expected behavior. I would like to close this issue, but if you have any questions, please feel free to comment.
