### ISSUE TITLE
Button: Audit 24px `isSmall` size

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#51708]
In light of #46734 and https://github.com/WordPress/gutenberg/pull/51012#issuecomment-1578094975, we need to evaluate which of the current 24px `isSmall` button usages are still legitimate.

This is not meant as a complete listing, but as an overview of the typical occurrences.

### Auxiliary toggle buttons in heading labels

|Description |  |
|--------|-------|
|FontSizeControl|<img width="276" alt="Toggle button in FontSizeControl" src="https://github.com/WordPress/gutenberg/assets/555336/45693933-c0ca-4484-9c9e-a9a19a5f1f20">|
|ToolsPanel dropdown|<img width="276" alt="Dropdown button in a ToolsPanel pattern" src="https://github.com/WordPress/gutenberg/assets/555336/0bb95a03-189a-4c68-ad5b-2b90aaf6d94f">|

### Link/Unlink buttons in a box-like control

<img width="271" alt="Link/Unlink buttons" src="https://github.com/WordPress/gutenberg/assets/555336/77fded7c-dacd-4675-ae7e-5694cd8fa709">

### Navigator back button

<img width="279" alt="Navigator back button" src="https://github.com/WordPress/gutenberg/assets/555336/c8980347-5b3e-4733-a3ba-04aff5cb9c71">

### With text labels

|Description |  |
|--------|-------|
|Image block|<img width="274" alt="Image size toggles and reset button" src="https://github.com/WordPress/gutenberg/assets/555336/ac081b02-c870-494c-9b34-5cfec88eb2b8">|
|Button block|<img width="274" alt="Width settings of Button block" src="https://github.com/WordPress/gutenberg/assets/555336/3333ff83-7f1b-419e-ab8f-cce9af49f06f">|
|Cover block|<img width="273" alt="'Clear media' button in Cover block" src="https://github.com/WordPress/gutenberg/assets/555336/65d4b0f4-a415-4849-9286-e14c8e13cf13">|
|Search block|<img width="278" alt="Width settings of Search block" src="https://github.com/WordPress/gutenberg/assets/555336/5cd443da-ac8c-490b-8c65-7b306fb89160">|

**Comment by mirka** [comment]
@jasmussen I'm assuming that the "With text label" small buttons are all outdated and need to be updated with a newer style, but the other types of usages are all still legitimate and need to be preserved as a `Button` size variant. Is that correct?

**Comment by jasmussen** [comment]
Thanks for following up. In the examples you've shared in this grid, the main valid usages are the icon buttons, which especially the link/unlink buttons and ellipsis menus should remain 24x24. I wonder how to best address that. For what it's worth, I don't see us having a 40x40px icon button, so those could potentially be 32x32 (large) and 24x24 (small). I'd appreciate a @jameskoster sanity check on this.

The remaining examples are all instances that have needed updating for quite a while. Clear media, for example, could benefit from being a full tertiary button with the text "Clear" or "Reset", and all those buttongroups could benefit from being segmented controls:

<img width="365" alt="Screenshot 2023-06-21 at 09 09 37" src="https://github.com/WordPress/gutenberg/assets/1204802/1ef8a030-e25d-4907-a345-ad8113b5afd8">

**Comment by jameskoster** [comment]
> For what it's worth, I don't see us having a 40x40px icon button, so those could potentially be 32x32 (large) and 24x24 (small).

Putting our existing UIs aside for a moment and thinking about the components as part of a design system, I'm not sure how practical it is for icon buttons to have different size properties / names to regular buttons (and other inputs for that matter). Wouldn't a default 40px and small 32px for all buttons simplify things considerably?

I appreciate we don't have a specific need for 40px icon buttons currently, but it doesn't seem beyond the realms of possibility as component usage begins to expand outside of the full screen editor. [input] [button] is a fairly common layout:

<img width="260" alt="Screenshot 2023-06-21 at 10 13 36" src="https://github.com/WordPress/gutenberg/assets/846565/aefdb313-41b1-4c3f-8c3d-e64d950e850a">

That leaves a question about what to do with the 24px buttons in the Inspector. I quickly fudged the numbers in dev tools and it doesn't look horrendous:

| Trunk (24px) | 32px |
| --- | --- |
| <img width="281" alt="Screenshot 2023-06-21 at 10 18 02" src="https://github.com/WordPress/gutenberg/assets/846565/a43f50ac-6de4-4838-a380-74f4261796d6"> | <img width="281" alt="Screenshot 2023-06-21 at 10 16 18" src="https://github.com/WordPress/gutenberg/assets/846565/67bced14-a9f5-49af-94bc-69375946bdc8"> |

With a little massaging of our grid values it could be made to work?

**Comment by jasmussen** [comment]
How would you fit all those "advanced" settings icons on the right?

For what it's worth, the small click area there is in part _because_ they are advanced properties. That's not to say that there isn't a use case for a 40px icon button, just that I find it also valid to have a smaller button.

**Comment by jameskoster** [comment]
I don't dislike the 24px button in isolation, I'm just a bit anxious about the complexity it adds to the overall system from a consumer perspective.

> For what it's worth, the small click area there is in part because they are advanced properties

There are other buttons though, (ellipsis, linking/unlinking borders, choosing which side to apply padding), which can always benefit from a larger target.

To be clear I'm not suggesting the advanced icons would need to use the 40px size – they can use the 32px variant. If you manually change the values in dev tools it doesn't actually affect the overall appearance that much. It's easier to see with an active / focus state which my screengrabs above were missing:

<img width="280" alt="Screenshot 2023-06-21 at 14 12 17" src="https://github.com/WordPress/gutenberg/assets/846565/9048ec56-e08a-4c49-a477-6ca82f60a4c3">

**Comment by jasmussen** [comment]
I hear you, and I don't entirely disagree. That said, I like having as a tool the option for the smaller buttons as yet another tool in the toolbox for managing both compression and prominence of advanced features. 

Is there any chance we can move forward with 40+32 for buttons, and 32+24 for icon for now, and then we can make exploring icon sizes a separate thing?

**Comment by ciampo** [comment]
Just to make sure I'm understanding:

- you are suggesting that `Button`s expose a `40px` (default size) and `32px` (small size) variant
- when the `Button` is `40px`, icons rendered inside the button should be `32px`. And when the `Button` is `32px`, icons rendered inside the button should be `24px`

Is that correct?

**Comment by jasmussen** [comment]
Not precisely. From this sheet:

<img width="1071" alt="Inspector controls" src="https://github.com/WordPress/gutenberg/assets/1204802/97b0ac5a-f638-490a-a7ad-d397b4a30976">

I'm suggesting that the Button is 40px by default, but has a 32px option that is the same font size, just not as tall. You can see the 40px button in the modal, and the 32px button in the toolbar.

For _icon buttons or toggles_, they would default to 32px, but have a 24px option.

It isn't clear to me we will ever need a 40x40px icon button.

I would imagine a Button with an icon inside (I think we have a case of an Upload button that features an icon), I would expect the same heuristic as the button, i.e. 40px or 32px button. Icons should never be smaller than 24x24 with few exceptions, so this is mainly about the footprint of the Button and Icon Button components.

**Comment by jameskoster** [comment]
> I would imagine a Button with an icon inside (I think we have a case of an Upload button that features an icon), I would expect the same heuristic as the button, i.e. 40px or 32px button.

This is exactly the point I was making above. Buttons would be 40px or 32px. Whether any individual button includes a text label, an icon, or a combination thereof is inconsequential. This seems much simpler to me in terms of the design system, from both a consumer, and a maintenance perspective.

**Comment by mirka** [comment]
Given the urgency of having to retract the `__next32pxSmallSize` prop for WP 6.3, I'm going to start preparing a PR to introduce a `size` prop where:

- `small` = 24px
- `compact` = 32px
- `default` = 40px when `__next40pxDefaultSize = true`, otherwise 36px

> Is there any chance we can move forward with 40+32 for buttons, and 32+24 for icon for now

I thought about it, but from the consumer API perspective, it is way too complicated for the component sizing scheme to change automatically based on whether the button is an icon button or not. Especially when we are in the middle of a sizing scheme transition from 36px default to 40px.

The `size` prop system I'm proposing above (small/compact/default) will push the complexity out of the automatic component logic, and into the consumer's actual understanding of the design system. We will provide guidelines in the documentation of course, but the consumer will be responsible for choosing the correct `size` for their use case.

This will potentially increase UI inconsistency in the wider ecosystem because not everybody will follow the design system correctly. IMO that is the main downside over a simpler system like @jameskoster is suggesting.
