### ISSUE TITLE
Search block can't change appearance if inside navigation block

### ISSUE THREAD

**Issue by tomxygen** [WordPress/gutenberg#51713]
### Description

It's not possible to change the appearance of the search button if it is placed inside the navigation block.

### Step-by-step reproduction instructions

1. open the Site editor
2. Go to Pages > Home
4. Edit the header and add navigation block
5. inside the navigation block, place a search block
6. Try to edit the appearance, like setting it as a button only.
The edit will not be applied and will be reverted to the original settings.

If instead of editing it from Pages > Home, you go to Library > Header, the issue isn't there.

### Screenshots, screen recording, code snippet

See attached video.

https://github.com/WordPress/gutenberg/assets/47855768/a093188c-c0c5-4f56-9f98-bcf4b02e63ed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I was able to reproduce this problem with Twenty Twenty theme and the latest Gutenberg trunk.

https://github.com/WordPress/gutenberg/assets/54422211/c24c6107-4935-46f4-8a51-06651ed7987b

**Comment by ndiego** [comment]
I was also able to confirm, but I wanted to note that this issue also seems to appear in 6.2.

**Comment by annezazu** [comment]
cc @scruffian as a heads up.
