### ISSUE TITLE
Top Toolbar editor rendered invisible in Safari when Custom Fields enabled and editor's vertical scrollbar appears

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#51720]
### Description

In Safari 16.5, when ~an Image block is added to a page/post~ enough content is added to a post that the vertical scrollbar appears, AND the "Custom Fields" panel is enabled, the Top Toolbar is rendered invisible, but is still clickable. 

### Step-by-step reproduction instructions

_updated instructions 2023-07-05; see [comment for new screenshots](https://github.com/WordPress/gutenberg/issues/51720#issuecomment-1622719062)_

1. Open Safari 16.5
2. Open a post and enable the Preferences > Top Toolbar
3. Open Preferences > Panels and enable "Custom Fields" (Click Show & Reload Page)
3. Add a small amount of content and see the top toolbar work fine
4. Next add enough content to make the vertical scrollbar appear

Observe how the top toolbar is now invisible

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/27249804/f566c355-bbc8-4a98-928b-a5160a8354d4

Compared with Firefox:

![Markup on 2023-06-20 at 18:22:24](https://github.com/WordPress/gutenberg/assets/27249804/405f25bd-11de-43af-930e-8827a2b051a8)

### Environment info

- Gutenberg Version 16.0.0 
- Safari Version 16.5 (18615.2.9.11.4)
- compared with Firefox 114.0.1 (64-bit)

Originally reported https://github.com/Automattic/wp-calypso/issues/78453

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by felipevelzani** [comment]
Hi @cuemarie, thank you for the report!

I tried to reproduce it, but it seems to work from my end. I tried your specific Gutenberg versions 16.0.0 and 16.1.1 and the same Safari version.

Can you still reproduce the same issue? If so, could you confirm if you indeed see the same with only Twenty Twenty-Three and no other plugins?

**Comment by cuemarie** [comment]
Hey @foosantos ! I'm still able to reproduce on my test site using only:

- Gutenberg 16.1.1 
- WP 6.2.2 
- Twenty Twenty-Three (v1.1)
- Safari Version 16.5.1

 but I'm not seeing the same thing happen on your test site with the same configuration and browser. 🤔 

---

I also see that the issue (on my end) is that when the vertical scroll bar appears in the editor, that's what renders the top toolbar invisible for me. I mistook the image block as the issue in my original report, but that's not the issue - you'll see in the recording below that when the scroll bar appears, that's when I run into the problem:

https://github.com/WordPress/gutenberg/assets/27249804/3ee1825f-6be8-4c05-997e-02b48686ca74

**Comment by cuemarie** [comment]
Got it! The issue is reproducible when the "Custom fields" panel is enabled, which appears below the editor. Steps to replicate:

1. Open a Post
2. Open Options > Preferences > Panels
3. Enable `Custom fields`, and click "Show & Reload Page"
4. Add enough content in the editor to make the vertical scrollbar appear
5. Observe the top toolbar turn invisible

![Markup on 2023-07-05 at 17:23:15](https://github.com/WordPress/gutenberg/assets/27249804/7c3ca202-bc9a-4f0e-80f3-45fbd05eb507)

![Markup on 2023-07-05 at 17:21:22](https://github.com/WordPress/gutenberg/assets/27249804/725415a7-e6a5-43e0-81ba-7f7e9bbc6f39)

**Comment by felipevelzani** [comment]
Hi again, @cuemarie!

Thank you for the fantastic work here!

I can reproduce it as well, and I updated the tags accordingly.

**Comment by jsit** [comment]
This is happening for me even on WordPress.com, using Safari for iPad with iPadOS 16.6. I have a barebones WordPress.com blog for testing, which has no plugins activated and is using the Twenty Ten theme.

Custom Fields are not shown in the compose screen.

The issue occurs when I embed an image in the post.

Can somebody please try this on iPadOS Safari and see if they’re seeing it as well? Thanks.

**Comment by jsit** [comment]
It looks like this may be fixed by #53688?

**Comment by jasmussen** [comment]
thanks for connecting the dots, @jsit. @cuemarie, the fix that's being suggested for this should land in 16.5. When that releases in the next couple of days (I think Wednesday or Thursday), can you check and verify if it fixes this issue?

**Comment by cuemarie** [comment]
Looking good to me! Retested on my site with GB 16.5 active, and the problem appears resolved 🎉 

https://github.com/WordPress/gutenberg/assets/27249804/ede528b0-678b-4ce7-99af-ae47f679b118

Closing!
