### ISSUE TITLE
Navigation List View drop indicator should not have a white border

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51745]
Dragging and dropping an item in the Navigation panel should not render a white border around the drop indicator line. 

### Visual 
https://github.com/WordPress/gutenberg/assets/1813435/a5bc3e7f-e599-4322-9f8d-4023fba2ee45

**Comment by juanfra** [comment]
It looks like this one was fixed by https://github.com/WordPress/gutenberg/pull/52122
