### ISSUE TITLE
Expanded submenu within the Site Editor > Navigation List View is improperly colored

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51746]
The styling is removed when the submenu is expanded. To test, drag another navigation item onto another to create a submenu, then open that submenu. 

## Visual 
<img width="356" alt="CleanShot 2023-06-21 at 10 20 07" src="https://github.com/WordPress/gutenberg/assets/1813435/f9d18080-5886-4029-b51e-615493408b83">
<img width="445" alt="CleanShot 2023-06-21 at 10 20 26" src="https://github.com/WordPress/gutenberg/assets/1813435/deb80a59-dcfa-4787-82d1-7a49d53b6d98">

**Comment by youknowriad** [comment]
This looks fixed.
