### ISSUE TITLE
Make replace media flows consistent across media blocks

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51750]
A few thoughts: 

- Is there a reason the "Current" control is only available on Image blocks? I think it'd be just as useful on other blocks. 
- Could we add "Use featured image" to the Image block (effectively transforming it to a Post Featured Image block)?
- Could we add "Use featured image" to the Media & Text block?

#### Image block
<img width="766" alt="CleanShot 2023-06-21 at 10 30 08" src="https://github.com/WordPress/gutenberg/assets/1813435/94715b64-e4df-4f1f-a72d-d08133bc36a3">

#### Cover block
<img width="656" alt="CleanShot 2023-06-21 at 10 30 26" src="https://github.com/WordPress/gutenberg/assets/1813435/45fc7b3c-3ceb-455a-9717-9a819b5daf6d">

### Media & Text block
<img width="645" alt="CleanShot 2023-06-21 at 10 31 49" src="https://github.com/WordPress/gutenberg/assets/1813435/5aac8e85-1565-426e-9a09-8f0237eb706a">

**Comment by annezazu** [comment]
Pulling in feedback from here for consideration as we think about this wider feature: https://github.com/WordPress/gutenberg/discussions/50129 

>Post Featured Image should be possible to transform to a cover block with post featured image as background
