### ISSUE TITLE
Details Block: Increase spacing between icon and text

### ISSUE THREAD

**Issue by beafialho** [WordPress/gutenberg#51758]
The spacing between the icon and the text looks very tight. 

Also, @jasmussen would it make sense to add this, or a similar icon, to the Gutenberg library?

<img width="1060" alt="Captura de ecrã 2023-06-21, às 16 02 56" src="https://github.com/WordPress/gutenberg/assets/65220155/62a6061f-ff98-489c-959f-863b40eb16de">

**Comment by t-hamano** [comment]
I think the Details block is mostly dependent on the default style of the browser. Therefore, the appearance will vary depending on the browser and operating system. In my Windows environment, there seems to be a good balance between icons and text.

## Chrome

![chrome](https://github.com/WordPress/gutenberg/assets/54422211/64db187e-cf97-4d60-8ca9-0f2f5ebe8f15)

## Firefox

![firefox](https://github.com/WordPress/gutenberg/assets/54422211/18c863a7-5ea6-4e61-a36f-f9ba6890f7f5)

**Comment by hanneslsm** [comment]
As @t-hamano says, this is mainly a browser default.
I'd strongly vote for avoiding overwriting default styles as much as possible.

With just a bit of custom CSS I was able to create a style like this and this would have been much harder if other CSS must have been overwritten first. We could think about adding a selectable style though.
<img width="941" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/530f64aa-3f5b-4b36-8123-de56361282fb">

**Comment by jasmussen** [comment]
Yep, this is a tricky one as the arrow is provided by the browser. To Hannes' point above, there are some CSS options [including these](https://css-tricks.com/exploring-what-the-details-and-summary-elements-can-do/), but it isn't entirely clear to me which ones if any, that are appropriate to bring into the block editor as canonical options. If there was some supremely solid and simple styling that allowed us to customize the icon, it would probably be useful. But in that light, we'd likely benefit from a unified "Icon" component, one that would also be useful for the Navigation burger menu icon.

**Comment by beafialho** [comment]
Thanks for clarifying! Yeah, my screenshot is from Chrome, and it looks pretty similar on Safari. I was convinced we could just increase spacing but I'll close this issue since it's not an easy fix.
