### ISSUE TITLE
Typography settings: Disable rounding for line-height

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#51754]
### Description

_"The details are not the details. They make the design" – Charles Eames_
With this wonderful and cheesy quote, I am proposing to you that the rounding of line-height should be disabled.
Currently, it's only possible to enter line-heights like 1.2 or 1.3.
But what if I want to have a line-height of 1.25? Especially for bigger text sizes this makes a difference.

Here as an example in Figma:
<img width="1443" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/cf89a389-55e5-412d-8de4-f77d11b1a4a1">

### Step-by-step reproduction instructions

1. Go to any global styles typography settings and try to enter a line-height of 1.25. It get's rounded to 1.3

### Environment info

- WP 6.2.2
- GB 16.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I believe this issue is identical to what was reported in #42998, so I am closing it.
