### ISSUE TITLE
Perf Testing: Ensure subject branch is up-to-date with trunk

### ISSUE THREAD

**Issue by WunderBart** [WordPress/gutenberg#51753]
For each PR, we're [comparing the performance of the current branch to `trunk`](https://github.com/WordPress/gutenberg/blob/5f2d618cbda4b32832c2e8c96c62f4e54e66001d/.github/workflows/performance.yml#L40-L42) without requiring the current one to be up to date. It's easy to become outdated in such a high-paced repo and, as a result, end up with a meaningless comparison where, for example, a (perf) improvement in the trunk is not present in the current branch. Should we enforce being up to date before running the [performance tests job](https://github.com/WordPress/gutenberg/actions/workflows/performance.yml?query=event%3Apull_request)? (Or at least attempt to do it programmatically when [initializing and fetching the branch for comparison](https://github.com/WordPress/gutenberg/blob/5f2d618cbda4b32832c2e8c96c62f4e54e66001d/bin/plugin/commands/performance.js#L258-L267))

/cc @youknowriad @dmsnell @kevin940726

**Comment by youknowriad** [comment]
What we should be comparing is the PR branch with the commits in the PR and the root of the PR branch without the commits. I think @dmsnell worked on this previously. In fact updating trunk can mislead the PR author to think its own PR did improve the performance or decrease performance while it had nothing to do with it.

**Comment by dmsnell** [comment]
if we rely on `$GITHUB_SHA` we should be good, because that's the merge ref and not the branch's `HEAD`.

that is, if it's not up to date with `trunk` it can't be merged anyway. if it is updated, it will incorporate all of what's in `trunk` too, assuming there are no non-textual conflicts.

https://fluffyandflakey.blog/2022/12/21/what-is-a-github-pull-request-merge-branch/

**Comment by WunderBart** [comment]
> if we rely on `$GITHUB_SHA` we should be good, because that's the merge ref and not the branch's `HEAD`.

Ah, I wasn't aware `GITHUB_SHA` is actually [the last **merge** commit](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#:~:text=auto_merge_enabled%0A%2D%20auto_merge_disabled-,Last%20merge%20commit%20on%20the%20GITHUB_REF%20branch,-PR%20merge%20branch). 👍

Closing this one then, thanks!
