### ISSUE TITLE
Quote block: Unable to transform back to Paragraph block

### ISSUE THREAD

**Issue by kellychoffman** [WordPress/gutenberg#51767]
To replicate: 

- Type paragraph.
- Transform to Quote. 
- No option to transform back to Paragraph.

<img width="331" alt="Screenshot 2023-06-21 at 1 07 24 PM" src="https://github.com/WordPress/gutenberg/assets/5835847/b9291483-0818-41e1-9157-8128040a3962">

Reported via Twitter: https://twitter.com/johnkoetsier/status/1671599027065085952?s=46&t=pGDJgZms4e6KzTRWH6M5IQ

**Comment by richtabor** [comment]
I suspect this was introduced when the Quote block was adapted to support InnerBlocks. There should be a Quote -> Paragraph transform, handled pretty much how the Gallery block transforms to multiple images; basically "unwrapping". 

You can choose the "Ungroup" option in the block toolbar options menu, though it's far from intuitive. 

<img width="557" alt="CleanShot 2023-06-21 at 17 34 06" src="https://github.com/WordPress/gutenberg/assets/1813435/7930da38-96c9-439a-a290-0034672ed814">

**Comment by richtabor** [comment]
Should probably add a “paragraph” transform that acts just like ungrouping does.
