### ISSUE TITLE
Site Editor: `Navigator`'s `goTo` function called twice when navigating screens in the sidebar

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#51760]
When interacting with the sidebar in the site editor, clicking buttons to navigate to a new screen seems to call the underlying `goTo` function twice:

- one call is triggered (correctly) by `NavigatorButton`, used to render those buttons
- one extra call seems to be triggered by the `useSyncPathWithURL` hook, in particular by [this line of code](https://github.com/WordPress/gutenberg/blob/a5dd6626f453de6c7bfa37cbc213543fee3d4961/packages/edit-site/src/components/sync-state-with-url/use-sync-path-with-url.js#L116)

Calling `goTo` twice can prevent `Navigator` from working as expected — for example, when navigating to the previous/parent screen, the focus is currently not being restored correctly on the button that triggered the previous navigation

cc @youknowriad

**Comment by youknowriad** [comment]
> one extra call seems to be triggered by the useSyncPathWithURL hook, in particular by [this line of code](https://github.com/WordPress/gutenberg/blob/a5dd6626f453de6c7bfa37cbc213543fee3d4961/packages/edit-site/src/components/sync-state-with-url/use-sync-path-with-url.js#L116)

This is something I'd like to remove by making the Navigator component controlled. Otherwise, it's very hard to address all the edge cases in these two-way synchronization and React effects.

**Comment by youknowriad** [comment]
We removed the component and removed a lot of the syncing, so this is issue is not relevant anymore
