### ISSUE TITLE
Navigation in Site View: Display draft status

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#51797]
## What problem does this address?
When we list the navigations in the Site View, we show a `(draft)` status next to the name. 
<img width="358" alt="Screenshot 2023-06-22 at 12 51 19" src="https://github.com/WordPress/gutenberg/assets/275961/f7d910d7-1dc1-4a60-828e-ce28e4ab9f1b">

## What is your proposed solution?

We should show the same status when drilling down to the navigation itself:
<img width="361" alt="Screenshot 2023-06-22 at 12 53 43" src="https://github.com/WordPress/gutenberg/assets/275961/b83ed5e4-bb0d-4cd4-87a4-95d1ac4d92d8">

Note: The text shouldn't be red, I'm showing it as red, to make it clear that this is the part that needs adding :)

**Comment by richtabor** [comment]
Navigation menus can be drafted? How does that occur?

**Comment by scruffian** [comment]
> Navigation menus can be drafted? How does that occur?

When you create a new one using the block itself, before you save it.
