### ISSUE TITLE
Navigation in Site View: Make whole canvas clickable to enter focus mode.

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#51794]
## What problem does this address?
When the site view shows only a navigation, it is not possible to click on the canvas to move to focus mode:
<img width="1512" alt="Screenshot 2023-06-22 at 12 37 24" src="https://github.com/WordPress/gutenberg/assets/275961/29706a0c-a29b-4603-bc40-2a70ec281a8e">

## What is your proposed solution?
Either we should make the whole canvas clickable, so that you can enter focus mode by clicking anywhere, or we should make the canvas much smaller, so it's only the same size as the navigation it contains.

cc @jasmussen for feedback

**Comment by jasmussen** [comment]
The initial design assumes a frame that is centered vertically and horizontally, and is only as tall as the content itself, ie. your proposed solution 2:

<img width="3432" alt="Multiple menus" src="https://github.com/WordPress/gutenberg/assets/1204802/e3f66888-aa06-433e-870e-60e874b9da21">

 But solution 1, making the whole thing clickable, seems like a good interim solution, and presumably wouldn't preclude the other change from happening.

Remember though, that we need the Edit icon here as well:

<img width="421" alt="Screenshot 2023-06-22 at 13 45 37" src="https://github.com/WordPress/gutenberg/assets/1204802/361dfb70-9fd4-47ff-9405-9e55e890124a">

When clicking the preview on the right enters the Edit View, there should always be an edit button in the detail panel of the Site View.

**Comment by richtabor** [comment]
> The initial design assumes a frame that is centered vertically and horizontally, and is only as tall as the content itself, ie. your proposed solution 2:

Would be the case for all focus views, yea?

**Comment by jasmussen** [comment]
Yes.

**Comment by getdave** [comment]
I have a PR to do the interim solution and we now have the edit icon as well.
