### ISSUE TITLE
Time zone issues by setting global moment time zone

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#5179]
## Issue Overview

I'm seeing issues with setting the global moment time zone to what amounts to be the time zone of the server. This overrides the moment time zone that might be used in themes or other plugins. In my case, the front-end theme for P2 which I'm also loading Gutenberg.

## Steps to Reproduce (for bugs)
1. Use moment library elsewhere after Gutenberg loads
2. Use moment to display a user's local timezone where user not in UTC/server zone 
3. Time zone is set globally to server zone, wrong time shows

## Possible Solution

My thought is to not set the global time zone on moment library but to create an instance of the moment library which is cloned and the timezone set on that which then gets used. 
Something like:

```
const now = moment();
const gutentime = now.clone();
gutentime.tz.setDefault( 'WP' );
```

For reference the timezone is set in `edit-post/index.js` which is configured from dateSettings in `lib/client-assets.php`

**Comment by youknowriad** [comment]
I think the best solution here is to not load `edit-post` in P2. `edit-post` is only meant to be loaded in the post editor context. The components exposed in the `editor` module should be reusable enough to build any custom layout.

**Comment by mkaz** [comment]
Ok, digging in and trying a couple things - it still does not quite work in a separate context since `isEditedPostBeingSchedule()` and likely other area rely on moment having the global time zone set. 

I'll test out a few other things and see if I can put together a working solution but I think the idea of creating the `WP` timezone is right, just need to use it everywhere moment is used and not set globally. 

For example: `moment().tz( 'WP' ).add( 1, 'minute' )`

**Comment by youknowriad** [comment]
@mkaz I can see that 👍  Thanks for the details.

I think ultimately we should do both things but might a quick win would be the `WP` timezone
