### ISSUE TITLE
Including scaffold block causes JS errors

### ISSUE THREAD

**Issue by ShepFc3** [WordPress/gutenberg#5181]
Given I have create a block via the wp scaffold block CLI
When I include the block
Then I see tinymce errors

## Steps to Reproduce 
1. Run `wp scaffold block test --title="Test block" --plugin=my-plugin`
2. Include block in plugin
3. Observe errors in Admin console

Chrome Version 64.0.3282.167 (Official Build) (64-bit)

## Expected Behavior
No errors in console

## Current Behavior
Edit page or post and observe console errors

```
tinymce.min.js?ver=4607-20180123:3 GET https://lms.dev/wp-content/plugins/gutenberg/vendor/plugins/wptextpattern/plugin.js?wp-mce-4607-20180123 net::ERR_ABORTED

Uncaught TypeError: b is not a constructor
    at n (tinymce.min.js?ver=4607-20180123:13)
    at Object.r [as init] (tinymce.min.js?ver=4607-20180123:13)
    at q.<anonymous> (tinymce.min.js?ver=4607-20180123:13)
    at Array.<anonymous> (tinymce.min.js?ver=4607-20180123:3)
    at b (tinymce.min.js?ver=4607-20180123:1)
    at r (tinymce.min.js?ver=4607-20180123:3)
    at tinymce.min.js?ver=4607-20180123:3
    at HTMLScriptElement.h (tinymce.min.js?ver=4607-20180123:3)
``` 
Gutenberg 2.2.0
WP 4.9.4
```
$ wp --info
OS:	Linux 3.13.0-119-generic #166-Ubuntu SMP Wed May 3 12:18:55 UTC 2017 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.19-1+deb.sury.org~trusty+2
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/srv/www/lms/public_html/wp-content/plugins
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.0.0-alpha-3d3f949
```

**Comment by gziolo** [comment]
It looks like you created a block inside`my-plugin` plugin (`--plugin=my-plugin), but the error is triggered from `wptextpattern` plugin (`plugins/wptextpattern/plugin.js`). I don't think this issue is related to the block's code itself, because WP-CLI generates a static block which doesn't use TinyMCE.

**Comment by ShepFc3** [comment]
Ah, thank you very much. It looks like I had one plugin enabled that is conflicting. I'll close this now.

**Comment by yahilmadakiya** [comment]
@gziolo I am faceing the same issue even only gutenberg is activated.

WordPress Version 4.9.4
Gutenberg Version 2.4.0

**Comment by gziolo** [comment]
@youknowriad is it something that might be cause because we use a different version of TinyMCE in Gutenberg than the core does?
