### ISSUE TITLE
Content editing in site editor guidance

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#51822]
## What problem does this address?
Provide some early guidance for users who are yet to experience content editing in the site editor.

## What is your proposed solution?
Re-use the welcome modal in two different scenarios.

**A user first hits the site editor with a page in context (e.g. after clicking a page in the pages sidebar)**

https://github.com/WordPress/gutenberg/assets/1072756/8396bc0f-d69d-4d96-afb9-68db0bdc3662

**A user first switches to editing a template from a page**

https://github.com/WordPress/gutenberg/assets/1072756/7c01cfc9-283d-4615-8e1a-9048b13b1beb

The video files are attached below. We may need to convert these to gif .

https://github.com/WordPress/gutenberg/assets/1072756/64a46ea9-85f7-4ef3-b8fe-c75c14825135

https://github.com/WordPress/gutenberg/assets/1072756/0621c794-ce40-4837-b076-054e1161eb86

@WordPress/gutenberg-design

**Comment by jasmussen** [comment]
Nice one. Remember to choose the modern color scheme for demo work, though:

<img width="1273" alt="Screenshot 2023-06-23 at 10 21 14" src="https://github.com/WordPress/gutenberg/assets/1204802/4acf63a3-ac23-4198-8e33-396e7770ad47">

I wonder, can we/should we be more abstract in the representation, a la the welcome guide?

<img width="425" alt="Screenshot 2023-06-23 at 10 22 00" src="https://github.com/WordPress/gutenberg/assets/1204802/b758c25e-1a57-4f89-9f4b-a0885942324c">

Screenshots and video age extremely quickly given how much UI work we still have to do, and if we can abstract this down, it'll likely have a longer shelf life.

**Comment by jameskoster** [comment]
I'd +1 the notion for a more abstract graphic – it'll be simpler to maintain. Using the `Guide` component probably makes sense too.

**Comment by richtabor** [comment]
> I wonder, can we/should we be more abstract in the representation, a la the welcome guide?

How were this original ones made?

**Comment by SaxonF** [comment]
The thought was that since this is such a significant change and we don't currently have a tour component a more literal representation would be better in the short term. Long term we can change.

**Comment by noisysocks** [comment]
Will we want this in 6.3?

**Comment by SaxonF** [comment]
@noisysocks Ideally yes

**Comment by noisysocks** [comment]
Cool. Remove the Needs Design Feedback label when you're ready for me to start building it out. Since it's onboarding for a feature that's already landing in 6.3 it's fine to add this during the beta period.

**Comment by jasmussen** [comment]
I think we can go with a GIF/screenshot for now (though we want to be mindful of the compression), and then ticket a followup to replace it with an abstracted version later on.

That said, I would call it a blocker that it's using the classic WordPress blue. The imagery should use the modern colors.

**Comment by SaxonF** [comment]
Thanks @jasmussen, I'll update GIF tomorrow with modern theme enabled. @noisysocks you should be free to work on this now when you have a moment.

**Comment by priethor** [comment]
[Related Trac ticket](https://core.trac.wordpress.org/ticket/58641)
