### ISSUE TITLE
Global Styles: Better labeling and instructions for global CSS and per-block CSS

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#51821]
### Description

The two options for adding CSS via the Site Editor (Additional CSS and Per-block CSS) are powerful and useful - but there are some places where labeling and instructions could give more clarity to which function the user is currently viewing, and assistance on how to use them.

**For Example:**

* The labeling at the top of each section is very similar, making it harder to tell if you are in the 'Additional CSS' or 'Per Block CSS' tool. The only visual difference is in the description.

<img width="271" alt="Screenshot 2023-06-23 at 9 31 20 am" src="https://github.com/WordPress/gutenberg/assets/1842363/a886b125-b5b9-42e7-9238-9a9401fb1661">
<img width="271" alt="Screenshot 2023-06-23 at 9 32 05 am" src="https://github.com/WordPress/gutenberg/assets/1842363/837d80d1-ec86-4553-b634-0e676fc93509">

* In the 'Per Block' CSS tool - it is not clear that CSS needs to be added *without* the selector being used.
This has been previously raised in #49531.

### Step-by-step reproduction instructions

1. Go to the Site Editor and open the styles panel.
2. Compare the 'Additonal CSS' panel, to a CSS panel when editing the styles for a specific block.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
There are some existing PRs in discussion to address _some_ aspects of this issue - but it could probably do with a holistic solution.

* #49627 to add placeholder CSS in per-block CSS textarea. There's also a suggestion of adding the selector _outside_ the textarea.
* #49626 to include more specific instructions for the per-block CSS. The copy/approach here could do with a review.
* No PR - but could we consider changing the label of the 'Additional CSS' to be clearer that it is global, or site-wide?

<img width="281" alt="Screenshot 2023-06-23 at 9 59 27 am" src="https://github.com/WordPress/gutenberg/assets/1842363/0f9f624f-96c5-4e85-9292-faa41203262f">

**Comment by richtabor** [comment]
> No PR - but could we consider changing the label of the 'Additional CSS' to be clearer that it is global, or site-wide?

Maybe the opposite, “Block CSS”.

**Comment by jordesign** [comment]
> Maybe the opposite, “Block CSS”.

That's a good thought - label the more specific instance. I think that would definitely help.

**Comment by jasmussen** [comment]
Worth noting, I don't think custom CSS is enabled in the core offering quite yet — or am I missing it some details on how to add this? I know it has landed, but not quite sure how to activate it locally. It's clearly active on wp.com where these screenshots are from.

In that light, I'd echo Rich, just noting it as block CSS. But I'll also share the original mockups, which haven't yet been fully implemented:

Global CSS:

<img width="1856" alt="Global styles custom CSS" src="https://github.com/WordPress/gutenberg/assets/1204802/586aedba-b340-47c2-ab68-860a91af7adb">

Group CSS:

<img width="1856" alt="Group custom CSS" src="https://github.com/WordPress/gutenberg/assets/1204802/12bb79a8-769e-48df-96cb-59c39affd31a">

I also recall a conversation around how to scope the group CSS to not bleed, and one of the suggestions were to use `:self`, which potentially we could lock into place inside the editable field:

<img width="672" alt="Group custom CSS, locked" src="https://github.com/WordPress/gutenberg/assets/1204802/a87d78b5-5851-4c08-a16a-40dc34e80a0e">

**Comment by richtabor** [comment]
> or am I missing it some details on how to add this? I know it has landed, but not quite sure how to activate it locally. 

Via the vertical ellipsis menu in the Global Styles sidebar.

**Comment by jasmussen** [comment]
Ah, we really hid that one didn't we 😅 — I'm sure there's context that steered it away from the original mockups. Thanks.

**Comment by richtabor** [comment]
Yea.. perhaps a bit too much. It's a risky thing to put so much emphasis on at the top-level Styles panel though. Perhaps in the future there would be sidebar for developer tools, and it could live in there.

**Comment by jordesign** [comment]
I think the thing will be that there are plenty of non-developers who will use the Additional CSS - prompted via support, forums, tutorials etc. So making it as clear as possible would be great.

**Comment by jordesign** [comment]
I just spotted that the Block-Specific CSS is now under the 'Advanced' section of the sidebar settings - which sets a much better context - so this change of labeling is probably no longer an issue.

**Comment by aadilayub** [comment]
Has this feature been removed? I can't find it in the styles pane any more:

![image](https://github.com/WordPress/gutenberg/assets/31581044/8cef2095-f8de-4893-b097-5ccfe1f0912d)
