### ISSUE TITLE
Custom Patterns not displayed in Pattern Modal

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#51844]
### Description

I created a synched pattern and a custom pattern. 

Both are available via the screen accessed via 
Inserter > synch patterns icon > Manage custom patterns

<img width="526" alt="Screenshot 2023-06-23 at 13 54 21" src="https://github.com/WordPress/gutenberg/assets/39980/efaf3e9e-4a70-4d24-8490-d88033925623">

From the Pattern tab of the Inserter, I am able to see the custom pattern category, but when I follow the **Explore all patterns** button, the Custom patterns are not listed. 

<img width="1360" alt="Screenshot 2023-06-23 at 13 54 58" src="https://github.com/WordPress/gutenberg/assets/39980/258b9fa0-fd76-495e-8f6a-a805446f5955">

### Step-by-step reproduction instructions

- Start a new post
- Add two new blocks of random content
- Highlight both blocks
- Use from the 3-dot menu "Create new pattern"
- Keep the toggle for sitewide synch in the off position. 
- Save 
- Open a new page in your WPAdmin
- Use the Inserter > Pattern > Explore all patterns 
- Click on Custom Patterns 

### Screenshots, screen recording, code snippet

A video might help 

https://github.com/WordPress/gutenberg/assets/39980/2cf4d253-7027-4f74-b53b-734518dbc92f

### Environment info

WordPress: WordPress 6.3-alpha-55991
Gutenberg Nightly 16.2.20230622

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I have a potential fix for this at https://github.com/WordPress/gutenberg/pull/51889

**Comment by glendaviesnz** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/51889
