### ISSUE TITLE
After inserting an image or embedding content, there's no visible way to carry on with your post

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#5184]
## Issue Overview

The UI can get in a state where the in-canvas inserter is hidden, and there's no visual indication that you can tab, or insert a new block, or carry on writing your post.

## Steps to Reproduce (for bugs)
1. Insert an image
2. Type a caption
3. Press enter. You're still in the caption, and there's no in-canvas inserter to click on, and the bottom block that would activate if you clicked in it is invisible.

## Expected Behavior

There should always be a visual indication that there's a block to tab into, or click into to get the in-canvas inserter. The user should never have to wave the mouse around looking for hidden UI.

## Possible Solution

Keep the in-canvas inserter visible at the bottom of the document if it appears nowhere else.

**Comment by youknowriad** [comment]
I believe the decision have been made to avoid the inserter at the end of the editor, we added the in-between inserter back to improve the situation and we're iterating on it.

Can we close this @mtias
