### ISSUE TITLE
Consider removing icons from StatusLabel within Page Details view 

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51855]
I like the idea of a status label + icon, though I'm not sure about introducing the icon within the Page Details view, while not elsewhere. Seems this should be a holistic indicator of page status applied everywhere, with proper icons for each status (perhaps even without color). 

cc @WordPress/gutenberg-design 

<img width="354" alt="CleanShot 2023-06-23 at 10 55 43" src="https://github.com/WordPress/gutenberg/assets/1813435/eee8d76c-e993-4a50-9129-3720a1569c89">

<img width="343" alt="CleanShot 2023-06-23 at 10 55 32" src="https://github.com/WordPress/gutenberg/assets/1813435/4ea4fc3a-0ad6-41d8-92ee-489ea8410ddf">

<img width="355" alt="CleanShot 2023-06-23 at 10 58 30" src="https://github.com/WordPress/gutenberg/assets/1813435/3aad35ba-9852-49f1-99d6-e1d7be17d34d">

<img width="358" alt="CleanShot 2023-06-23 at 10 58 50" src="https://github.com/WordPress/gutenberg/assets/1813435/44bea9b8-2a7e-4eed-bc19-8daac9be2df8">

**Comment by jasmussen** [comment]
I tend to agree, though not strongly. The concept can work, it's a nice splash of color, but it might be good to — as you say —  to roll it out in a more holistic way across.

**Comment by jameskoster** [comment]
Alternatively we could update the Post Editor status UI to be consistent with the one in the Site Editor:

| Site Editor | Post Editor |
| --- | --- |
| <img width="353" alt="Screenshot 2023-06-26 at 12 00 21" src="https://github.com/WordPress/gutenberg/assets/846565/89a30182-41f7-4f2e-955f-a406e815f1c7"> | <img width="334" alt="Screenshot 2023-06-26 at 12 01 41" src="https://github.com/WordPress/gutenberg/assets/846565/bbba7bb6-a340-4c1f-9fe1-a2090811c5e9"> |

Then polish details like the colors / icons.

**Comment by youknowriad** [comment]
Going to close this one as the icons moved to the document inspector while the details panel has been removed.
