### ISSUE TITLE
Consider trimming domain from the Page Details view

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51854]
What are your thoughts about trimming the top level domain name from the slug under the page title in the Page Details view? 

<img width="835" alt="CleanShot 2023-06-23 at 10 53 44" src="https://github.com/WordPress/gutenberg/assets/1813435/83e0204d-8b2a-4bb9-9d4a-15769e23e875">

**Comment by jasmussen** [comment]
I think the domain can be useful context for what you're looking at. Not the strongest opinion, and potentially something we can revisit if we start to see issues around unfortunate eliding or wrapping.

**Comment by richtabor** [comment]
As an aside, I'm not sure we need it highlighted up top; perhaps just the slug with the external link — though not 100% sure.

**Comment by jasmussen** [comment]
Yep, the fact that there's an external link feature in the site hub could suggest not having it here. At the same time, it does benefit the "site structure" aspect of pages.

**Comment by youknowriad** [comment]
The document sidebar shows just the slug and the details panel is gone.
