### ISSUE TITLE
Trim trailing block on save

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#5185]
## Issue Overview

As a Gutenberg user, it's not obvious that the trailing default block needs to be removed in order to not be saved with the post content. I'd expect that my stored post content only represent the content I've produced.

## Steps to Reproduce (for bugs)

1. Create a new post.
2. Write a few paragraphs.
3. Unintentionally leave the last block trailing in the post.

## Expected Behavior

When saving a post, I'd suggest the last block be removed if it's an empty paragraph block.

## Current Behavior

The last empty paragraph block is left in my post content.

## Screenshots / Video

<img width="853" alt="image" src="https://user-images.githubusercontent.com/36432/36506012-30876c62-170a-11e8-8089-c181c723670f.png">

***

<img width="802" alt="image" src="https://user-images.githubusercontent.com/36432/36506038-400d6dc6-170a-11e8-8d6f-5ce6e86bb589.png">

**Comment by danielbachhuber** [comment]
What's even weirder behavior is that I can hover over this space at the end of the editor:

<img width="858" alt="image" src="https://user-images.githubusercontent.com/36432/36506292-10b07f04-170b-11e8-8aab-c440f90c922c.png">

When I hover over the space, it's not clear to me whether there's a block there or not.

**Comment by karmatosed** [comment]
> When saving a post, I'd suggest the last block be removed if it's an empty paragraph block.

This feels reasonable and I've seen others get caught in it.

**Comment by aduth** [comment]
Related: #9808 

Discussed today in Slack ([link requires registration](https://make.wordpress.org/chat/)): 

https://wordpress.slack.com/archives/C02QB2JS7/p1536768405000100

An open question on my part: 

Should this apply to only the last empty paragraph block? What if there are multiple trailing empty paragraph blocks? Leading empty paragraph blocks? Empty paragraphs between other blocks?

**Comment by karmatosed** [comment]
Thanks for those thoughts @aduth. As you point out, what we thought of maybe as simple well isn't. In this case whilst I think 'last' makes sense, I am not sure if this is critical for 5.0 or we can predict enough to remove the right 'last'. I would as a result not include this in 5.0 but look as an iteration.

**Comment by danielbachhuber** [comment]
We can punt on this one. It was more of an issue when there was a ghost block at the end of the post that you couldn't remove. It's less of an issue now.

**Comment by ZebulanStanphill** [comment]
@danielbachhuber Doesn't closing this issue imply that there is nothing more to be done here? Shouldn't it just have a label marking it as something to be resolved in the future?

**Comment by danielbachhuber** [comment]
@ZebulanStanphill I've marked it as `[Status] Won't Fix`, as I don't think it's necessarily a problem worth fixing at this point.

It was more of an issue when the empty block couldn't be removed through any UI. Now that there's UI to remove empty blocks, I don't think this is an issue that Gutenberg should try to solve automatically.
