### ISSUE TITLE
Custom Pattern: Each time you switch pattern categories, the number of custom patterns increases

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#51872]
### Description

It is a strange behavior, but every time I switch categories in the main inserter, the number of registered custom patterns increases. This problem appears to occur when multiple custom patterns are registered. Also, I don't think this is the intended behavior, but the custom patterns appear in all categories.

### Step-by-step reproduction instructions

- Register two patterns with Synced turned off from the Library menu in the Site Editor.
- Open the main block inserter.
- Click Patterns tab.
- Click Custom patterns category.
- Two patterns should appear correctly.
- Switch to other categories.
- One custom pattern is added.
- Return to Custom patterns category.
- The number of custom patterns increases to three.
- Repeat to switch categories.
- Each iteration should increase the number of custom patterns.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/2d14f46b-fc0a-4f41-bf04-b486cd17f75e

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
This PR seems to also fix this issue. Can you please test against that PR @t-hamano and confirm?

**Comment by talldan** [comment]
Fixed by #51947
