### ISSUE TITLE
The Preview Could not be loaded

### ISSUE THREAD

**Issue by hasoo440** [WordPress/gutenberg#51874]
### Description

when i open a elementor header foe editing then show a "The Preview Could not be loaded" 

### Step-by-step reproduction instructions

https://zenithpathway.com/wp-admin/post.php?post=1298&action=elementor

### Screenshots, screen recording, code snippet

https://zenithpathway.com/wp-admin/post.php?post=1298&action=elementor

### Environment info

- wordpress, Jeg elementor kit, Header page 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Hey there – since this issue relates to the Elementor page builder plugin and not the core block editor, I'd suggest you reach out to the Elementor support team about this issue. Here are several avenues to reach them:

https://elementor.com/support/
