### ISSUE TITLE
Style Book: When navigating from the sidebar, there are no tabs and blocks cannot be clicked

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#51887]
### Description

The Style Book can also be accessed from the Style menu in the sidebar. When I click on the button, no tabs appear and all blocks are displayed, which is the expected behavior. However, when I click on the canvas, the tabs do not appear and the blocks are not clickable. Reopening the Stylebook from the right-side style sidebar does not solve the problem.

![stylebook](https://github.com/WordPress/gutenberg/assets/54422211/a9b13b69-4168-40c5-839c-a48ab0135d27)

I expect that when the canvas is clicked, i.e. in edit mode, the category tabs will appear as before and each block can also be selected.

Strangely enough, once I go back to template mode and reopen the Stylebook from the right side style sidebar again, it appears as intended.

### Step-by-step reproduction instructions

- Access the Styles menu from the sidebar of the site editor.
- Click on the Style Book button.
- In the canvas area, all blocks are displayed, with no tabs (I think this is the expected behavior).
- Click on the canvas area.
- There are no tabs and each block is not clickable (I don't think this is the correct behavior).
- Click the Style Book button on the right sidebar twice to reopen the Style Book.
- As usual, there are no tabs and each block is not clickable.
- Return to the root menu (Desigin) of the site editor and click on the canvas area.
- Click the Style Book button on the right sidebar.
- The Style Book has tabs and you can click on each block.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/6de2a026-4acd-4583-a7e9-198939a32e09

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I can replicate with 16.1 RC1. Adding to the 6.3 triage board.

**Comment by t-hamano** [comment]
Update: I found that this problem is affected by the `path` included in the URL.

`http://localhost:8888/wp-admin/site-editor.php?path=%2Fwp_global_styles&canvas=edit`

When the Style Book is accessed from the left side menu, `wp_global_styles` is appended to the `path`. This `path` is maintained when moving to edit mode and the issue continues.

On the other hand, this problem is not reproduced when Style Book is opened in edit mode from a menu _other than_ the Styles menu, as shown in the URL below.

- http://localhost:8888/wp-admin/site-editor.php?path=%2Fnavigation&canvas=edit
- http://localhost:8888/wp-admin/site-editor.php?postType=page&postId=25&canvas=edit
- http://localhost:8888/wp-admin/site-editor.php?postType=wp_template&postId=twentytwentythree%2F%2Fblog-alternative&canvas=edit
