### ISSUE TITLE
"block" for no-result queries

### ISSUE THREAD

**Issue by tkapler** [WordPress/gutenberg#51899]
## What problem does this address?
When you have a query loop block, that returns zero results - typically on search page, there is afaik currently no easy way how to display "something". 

In old days we were doing

`
if (have_posts()) :  
   //while loop

else:
     echo '<h1>no posts found</h1>';

endif;
`
(or e.g. added also search block for repeating search, adding a list of most common pages ...)

But i have no clue how to solve it now

## What is your proposed solution?
Actually i think the optimal solution would be a special feature of loop block, that will show 2 block "areas" (or e.g. you would be able to switch which area to show) - one for situation if have_posts(), one for the zero result. So that user can than place proper blocks for that particular situation.
Other (easier?) option would be to create a special "zero result loop" block, that you could put into query loop block and then can put anything into it and it would be shown only if there is no result.

**Comment by t-hamano** [comment]
Hi @tkapler,

If the query loop has no posts, there is a No Results block that displays content instead. This block can have a variety of blocks inserted within it. Is this the block you are looking for?

![no-results](https://github.com/WordPress/gutenberg/assets/54422211/0a3e2212-7f5a-4ac4-a35f-2640521fd164)

**Comment by Himshekhar07** [comment]
Hi @tkapler,

If there is a post type that is no post, it shows no results. You can change the post type as well as per your need. Is there any other question?


![CleanShot 2023-06-26 at 18 50 15](https://github.com/WordPress/gutenberg/assets/73247637/d9393016-9561-4f4b-9176-5160027447e7)

**Comment by tkapler** [comment]
> Hi @tkapler,
> 
> If the query loop has no posts, there is a No Results block that displays content instead. This block can have a variety of blocks inserted within it. Is this the block you are looking for?
> 
> ![no-results](https://user-images.githubusercontent.com/54422211/248805716-0a3e2212-7f5a-4ac4-a35f-2640521fd164.png)

Wow, not only does it already exist, but it's even exactly as I suggested it might be, and it's even called exactly that.

So I'm just completely blind and haven't seen it or seen it used in a common template, so it didn't strike me.

Thanks a lot, I am closing it.
