### ISSUE TITLE
The Document outline doesn't account for headings within Patterns 

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#51909]
### Description

The Document outline doesn't show headings that are within Patterns.

### Step-by-step reproduction instructions

- Create a post with some paragraphs and headings.
- Add a _synced_ pattern that is made by a group that contains a heading and a paragraph.
- In the editor top bar: click Document Overview > Outline
- Observe the Document Outline doesn't show the heading contained within the Pattern.

### Screenshots, screen recording, code snippet

<img width="1425" alt="Screenshot 2023-06-26 at 15 00 49" src="https://github.com/WordPress/gutenberg/assets/1682452/251c2ebd-fc4a-4afe-b9ba-f6b7c2ceea79">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Probably a duplicate of #33079. Btw, I can't reproduce the issue on trunk, but I remember missing heading from Synced Patterns in previous versions.

**Comment by afercia** [comment]
Thanks @Mamaduka, I'll close in favor of https://github.com/WordPress/gutenberg/issues/33079 which has some more information.
