### ISSUE TITLE
Library: In the mosaic of entries template parts do not display the correct icon

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#51905]
<img width="522" alt="Screenshot 2023-06-26 at 13 22 54" src="https://github.com/WordPress/gutenberg/assets/846565/c5dcaecc-97c4-48f0-a3f0-88edc6cf8424">

The icon in the navigation sidebar does not correlate with the one you see in the purple field, adjacent to the template part name. This is true for all template parts; Headers, Footers, and Uncategorized.

**Comment by carolinan** [comment]
I'm sorry, but which icon needs to be switched? The one in purple?
