### ISSUE TITLE
Custom Patterns: Allow renaming and duplication within the Site Editor

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#51919]
## What problem does this address?

In the Library menu of the site editor, you can create custom patterns.

![create-pattern](https://github.com/WordPress/gutenberg/assets/54422211/c9221995-ebbf-4338-983f-a81f344685f3)

However, in the site editor, you can only delete a pattern you have created.

![delete](https://github.com/WordPress/gutenberg/assets/54422211/37f2e6ed-2c81-4660-9447-f45cba5df431)

To rename, the following operation is required.

- Click "Manage all custom patterns"
- Edit a post(pattern)
- Change the post title(pattern name)
- Save the post(pattern)
- Back to the Site Editor

## What is your proposed solution?
It would be nice to be able to rename and even duplicate pattern names in the site editor, as in the navigation menu.

![navigation](https://github.com/WordPress/gutenberg/assets/54422211/6ac8c6cd-793f-4e9e-ad04-8f3e8663a26f)

![rename](https://github.com/WordPress/gutenberg/assets/54422211/3237283b-a494-4fe6-bb86-3857c45b6245)

**Comment by annezazu** [comment]
Noting that I just ran into this with 16.1 RC1 and it's not clear to me where/how we can rename, except by adding the pattern and renaming it from there:

https://github.com/WordPress/gutenberg/assets/26996883/922fb3a2-135f-4397-8629-ddf4c3feefd2

To me, the more important piece is renaming rather than duplication right now for 6.3. Adding to the triage board for consideration.

**Comment by richtabor** [comment]
>  it's not clear to me where/how we can rename, except by adding the pattern and renaming it from there:

Which is very odd; unexpected even. I'd say that renaming control probably shouldn't exist at the pattern block level. I wouldn't expect to be able to change the title of this pattern from any instance; it's disconnected from where I manage/see all my patterns.  

For additional context: 

<img width="279" alt="CleanShot 2023-06-26 at 16 58 53" src="https://github.com/WordPress/gutenberg/assets/1813435/f6c55182-f57f-4fee-b327-ee691a21e58c">

**Comment by talldan** [comment]
Related a11y issue - [Library: revisit keyboard navigation for pattern items](https://github.com/WordPress/gutenberg/issues/52009#top)

Another related observation is that template part actions (like 'Clear customizations') could be made available in the Library.
