### ISSUE TITLE
Image block: JS Warning: `NaN` is an invalid value for the `maxHeight` css style property

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#51913]
### Description

On latest trunk, a JS warning is thrown for apparently any image block. Whatever the image size, I get an:

``NaN` is an invalid value for the `maxHeight` css style property`

No idea where it comes from. I tried two images: 1200 by 400 pixels and 165 by 210 pixels.

Screenshots:

<img width="1760" alt="Screenshot 2023-06-26 at 15 05 18" src="https://github.com/WordPress/gutenberg/assets/1682452/0fe69524-b039-4aeb-93e0-6de17364d48b">

<img width="1776" alt="Screenshot 2023-06-26 at 15 16 36" src="https://github.com/WordPress/gutenberg/assets/1682452/f8ebc9d0-8a71-4491-bb5e-40b0704e48c0">

### Step-by-step reproduction instructions

- Create a new post.
- Add a title and an Image block with an actual image.
- Save.
- Refresh the page.
- Open your browser console.
- Observe the JS warning (see screenshots)

### Environment info

Latest trunk, at commit: https://github.com/WordPress/gutenberg/commit/48b30f4b7da156293b4ffd568db4f879eacde852

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
Just saw this too as this bug/warning will be in WP 6.3 Beta 😄 

It looks like a bunch of the values we use to calculate `ratio` are undefined at this point:

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/image/image.js#L607

Before, there was a check for some of them:

https://github.com/WordPress/gutenberg/pull/51545/files#diff-a14b61c874095649b236b78413e805b4541277b24eb71ce350a17d9f2b6396b1L517

A quick fix might be to set a default

```js
		const ratio =
			( aspectRatio && evalAspectRatio( aspectRatio ) ) ||
			( width && height && width / height ) ||
			naturalWidth / naturalHeight ||
			1;
```

cc @ajlende @jasmussen

**Comment by cbravobernal** [comment]
It is fixed in this PR:
https://github.com/WordPress/gutenberg/pull/52109

**Comment by afercia** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/52109
