### ISSUE TITLE
Patterns: update block description based on sync status/optionality

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51922]
In testing 16.1 RC1 and the new pattern syncing, I noticed that the block description in the block settings sidebar reused (get it) what we had in place for reusable blocks. This doesn't take into account the new syncing status and needs to be updated:

<img width="279" alt="Screen Shot 2023-06-26 at 8 49 18 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/fb0b2e76-b15f-40ec-b1b9-248951161a3a">

Here's the text:

>Create and save content to reuse across your site. Update the block, and the changes apply everywhere it’s used.

**Comment by glendaviesnz** [comment]
I think this is actually correct as the only sort of Pattern block you can select in the editor is a `synced` one, ie. you will not see this decription for an `unsynced` pattern as `unsynced` patterns are never selectable in the editor canvas. @SaxonF what do you think?

**Comment by annezazu** [comment]
Ah! I see. I wonder if we should call this "Synced Pattern" in that case or what can be done to make it clearer in the interface what the distinction is. I know these are details but they all add up to guide the user.

**Comment by talldan** [comment]
It'd be good to make sure there's design feedback on this before progressing.

Maybe it's better to show the pattern name instead of the block title, as is done for template parts?

**Comment by glendaviesnz** [comment]
> Maybe it's better to show the pattern name instead of the block title, as is done for template parts?

I like that idea, as essentially each of these is sort of a block in its own right. It would be nice to pull through the syncstatus as well if we can.
