### ISSUE TITLE
Patterns: use correct icon when searching with the slash inserter

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51921]
After creating a synced pattern and searching for it with the slash inserter, I noticed it defaults to the icon of the top block used in the pattern. This makes it hard to distinguish as different from other blocks:

<img width="468" alt="Screen Shot 2023-06-26 at 8 45 43 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/6b3b0469-f589-4576-8d9f-5ff8a3cbcac8">

For example, if I change the order to have a paragraph block first, the paragraph icon is used:

<img width="470" alt="Screen Shot 2023-06-26 at 8 47 43 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/ad2b33b6-55a0-46d6-8fc8-61074e5a9246">

However, upon insertion, the icon switches appropriately in the toolbar:

<img width="736" alt="Screen Shot 2023-06-26 at 8 46 13 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/d83b58e1-a837-4943-9176-13a07dea134f">

**Comment by glendaviesnz** [comment]
It looks like this is an existing issue with reusable blocks. It would be nice to fix, but I don't think it is a must-have as not introduced by the patterns changes.

**Comment by glendaviesnz** [comment]
It looks like this was a deliberate design decision to show the topmost block icon https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/store/selectors.js#L1989 so currently a feature not a bug 😃

**Comment by annezazu** [comment]
That feels strange to me 😅 @WordPress/gutenberg-design for some thoughts here. IMO we should be indicating they are patterns, along with sync state upon insertion.

**Comment by jameskoster** [comment]
[I agree this can feel a bit strange](https://github.com/WordPress/gutenberg/issues/46441) :).

We're using the `symbol` icon in the Library, and I think we should be consistent. It should be purple too.

**Comment by glendaviesnz** [comment]
I think this should be pushed to post 6.3 - this is existing accepted behaviour so an enhancement rather than a bug. I agree that we should review it, but it is not critical and we have enough other things around patterns/resuable blocks to stabalise.

**Comment by jasmussen** [comment]
When we only had reusable blocks, and patterns were nascent, there might have been good context. I tend to agree with Jay that the new unification here suggests purple and symbol icon for the synced patterns at least.

**Comment by JosVelasco** [comment]
I agree patterns should be colored purple with the special icon, and I'd love to see unsynched patterns on that list when using the slash inserter. At least the custom patterns added by site users.

**Comment by glendaviesnz** [comment]
> I'd love to see unsynched patterns on that list when using the slash inserter. At least the custom patterns added by site users.

@JosVelasco unsynced patterns were [ added to the `/` inserter here](https://github.com/WordPress/gutenberg/pull/52866).

**Comment by glendaviesnz** [comment]
[PR here](https://github.com/WordPress/gutenberg/pull/53208) to make all the icons the same.
