### ISSUE TITLE
Patterns: when editing in the Site Editor, sidebar lists "Template" rather than "Pattern"

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51925]
When editing a pattern in the Site Editor with 16.1 RC1, the sidebar shows as "Template" when it likely should say "Pattern" and list the sync state:

<img width="1476" alt="Screen Shot 2023-06-26 at 9 09 48 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/60571af7-f13e-411e-a2ec-a95e265507ba">

**Comment by richtabor** [comment]
I came here to report this as well; can be confusing. 

![CleanShot 2023-06-26 at 16 22 04](https://github.com/WordPress/gutenberg/assets/1813435/18d12029-bf25-4406-a1c3-6b131bbe1c94)

**Comment by richtabor** [comment]
This should be the correct pattern icon as well: 

![CleanShot 2023-06-26 at 16 43 52](https://github.com/WordPress/gutenberg/assets/1813435/4a60950b-1cd1-4a1c-b812-39aefe34ac78)
