### ISSUE TITLE
Patterns: Detail page doesn't reference sync state

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51926]
As of 16.1 RC1, there's very limited information on the Detail page for a pattern and, at the least, I think we need to display sync state. Ideally, in the future, we could reference things like where else it's in use. 

<img width="772" alt="Screen Shot 2023-06-26 at 9 14 10 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/a084030b-5fd8-453b-8007-5c399064f130">

**Comment by ndiego** [comment]
Related, it would also be good to add renaming here as noted in: https://github.com/WordPress/gutenberg/issues/51919
