### ISSUE TITLE
Enhancement: Add Column A rea and Gutter padding settings

### ISSUE THREAD

**Issue by mathetos** [WordPress/gutenberg#5192]
## Issue Overview
When the new experimental columns are inserted, they have some padding applied outside the columns. Users should have the ability to adjust both the outter column padding and the gutter settings, like so:

![image](https://user-images.githubusercontent.com/930724/36518518-8e941338-173b-11e8-8973-9e5a8ca79227.png)

**Comment by youknowriad** [comment]
While the "gutter" kind of make sense to me, I'm wondering if the padding does. 

In any case, both can be tweaked by the theme and could be considered theme territory.

**Comment by mathetos** [comment]
My primary concern with the column outside padding is the left/right padding and how the default is about 20px inside on both side. Perhaps this should be two issues instead:

1) Add a Gutter width setting
2) Make the columns full-width of the content area without left/right padding by default. 

That feels like a better default that indented on both sides. Then themes can do whatever they want from there.

**Comment by karmatosed** [comment]
I would -1 adding this, we can leave it up to themes for this. Let's close and for now leave it up to them.
