### ISSUE TITLE
Library: synced pattern shows as "standard" and unsynced

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51923]
While testing 16.1 RC1, I noticed that if I create a synced pattern (reusable block) with a classic theme then switch to a block theme, it's listed incorrectly as unsynced:

https://github.com/WordPress/gutenberg/assets/26996883/f0347598-d621-436d-a3fe-b2f96f368211

This stands in contrast to when you create a new pattern and sync it where it shows up correctly:

<img width="627" alt="Screen Shot 2023-06-26 at 8 52 51 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/4dd2f878-9f91-484d-98ef-f06476531861">

**Comment by ndiego** [comment]
In trunk, all of my custom patterns appear as unsynced, even though some are synced. 

| Library | Inserter |
| --- | --- |
| <img width="1159" alt="image" src="https://github.com/WordPress/gutenberg/assets/4832319/94a8a385-9b0b-49f4-b306-d5960f7005e2"> | <img width="432" alt="image" src="https://github.com/WordPress/gutenberg/assets/4832319/b543c656-cb4d-47b7-af1b-1d8486aee140"> |

I am also not able to change the setting when I go to Manage Patterns 🤔

https://github.com/WordPress/gutenberg/assets/4832319/6c382bfc-9f42-4541-b2b7-95d3574e5145

**Comment by aaronrobertshaw** [comment]
Thank you for flagging this!

There were some recent changes to the pattern sync status in the entity's post meta that weren't replicated in the Site Editor Library's pattern creation modal or the PostSyncStatus toggle.

A fix is up in https://github.com/WordPress/gutenberg/pull/51952 that should restore the correct display of patterns etc.
