### ISSUE TITLE
My Patterns vs. Custom Patterns

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51939]
I'm a bit concerned that "custom" does not imply enough ownership/origin. I question if using something like "My Patterns" would convey better?

"Custom" is used during initial create of "custom" templates, But those are also much less visible as "custom" entities.

### Custom patterns: 

<img width="351" alt="CleanShot 2023-06-26 at 16 14 38" src="https://github.com/WordPress/gutenberg/assets/1813435/8436ed1a-f110-4b5e-b87f-3c2acfb42756">

<img width="348" alt="CleanShot 2023-06-26 at 16 14 10" src="https://github.com/WordPress/gutenberg/assets/1813435/324ad977-5bf8-4f1f-96e2-26177073d9a8">

### As seen in templates: 

<img width="820" alt="CleanShot 2023-06-26 at 16 16 10" src="https://github.com/WordPress/gutenberg/assets/1813435/42ce4f17-fabb-4ba9-9b7e-3023e4060015">
<img width="357" alt="CleanShot 2023-06-26 at 16 20 47" src="https://github.com/WordPress/gutenberg/assets/1813435/ddf8eb80-8b97-4e91-af0a-18e2175530a4">
<img width="355" alt="CleanShot 2023-06-26 at 16 18 35" src="https://github.com/WordPress/gutenberg/assets/1813435/9e6c4504-2c06-4633-b8e3-d9186f86cf08">

**Comment by richtabor** [comment]
There is no mention of "custom" when creating patterns as well. 

<img width="473" alt="CleanShot 2023-06-26 at 16 30 10" src="https://github.com/WordPress/gutenberg/assets/1813435/087ec98d-0c63-4fb2-bf2b-b455f9621f11">

**Comment by talldan** [comment]
> I'm a bit concerned that "custom" does not imply enough ownership/origin. I question if using something like "My Patterns" would convey better?

@richtabor The patterns that appear here could be created by multiple users. Happy to go with the renaming if you think it's better, but just wanted to make sure you're aware of that caveat.

**Comment by jasmussen** [comment]
I quite like your concept in #51943, both the spacing and the star. "My patterns" also reads well, though Dan makes a good point. Also worth thinking about is the future where you can save patterns from a theme, then delete that theme. Or even the fact that you could save your own custom patterns to any of the existing categories (Featured, Posts, Footers, etc). 

So essentially "Custom patterns" today are essentially "Uncategorized patterns that users saved", but in the future they will just be patterns on par with all other patterns, regardless of their origin. In that light I wonder if, for now, we call them "Saved patterns", group them at the top with a star like in 51943. But then in the future, they can become "My patterns" and be more of a _tag_ behavior than a category, simply showing the patterns _you_ created, even if they are also filed in the various categories as well.

**Comment by richtabor** [comment]
> simply showing the patterns you created, even if they are also filed in the various categories as well.

Exactly my thinking. 🚀
