### ISSUE TITLE
Patterns in focus mode should not render with layout padding applied

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51937]
As previewed, patterns seen within the Library do not render with applied layout padding. But as you click through to edit one, the padding is then applied. 

The Global Styles > Layout > Padding value should probably be omitted from the canvas when in focus mode. 

<img width="1489" alt="CleanShot 2023-06-26 at 15 21 59" src="https://github.com/WordPress/gutenberg/assets/1813435/a0826536-e895-4024-905a-48c9ee77cae8">

![CleanShot 2023-06-26 at 15 20 48](https://github.com/WordPress/gutenberg/assets/1813435/029240c1-66de-422d-8ce8-05b29c8925ec)

**Comment by carolinan** [comment]
Did you mean that the controls should be hidden too? I think the inconsistency could be confusing.

**Comment by richtabor** [comment]
> Did you mean that the controls should be hidden too? 

No, I mean the padding applied to the block content area should not be present.

**Comment by carolinan** [comment]
But then the control will be there in the sidebar but it will look like it does nothing when you change the spacing.

**Comment by richtabor** [comment]
> But then the control will be there in the sidebar but it will look like it does nothing when you change the spacing.

You're focused in on a pattern; not the site. The layout padding doesn't apply to each individual padding, so it shouldn't be applied visually within the editor - if it's not applied to the pattern anywhere else.

**Comment by richtabor** [comment]
What about if the wrapping block is a container (group, columns, media & text) then the horizontal and vertical padding is omitted from focus view?   

The trailing inserter is another issue. 

https://github.com/WordPress/gutenberg/assets/1813435/3ba261bc-24ed-4213-a342-5699bb165e45

cc @jameskoster as you ran into this earlier as well.

**Comment by jameskoster** [comment]
> What about **if** the wrapping block is a container

I'm not sure there needs to be an if. Imo the "Layout" padding from global styles should be removed in this view regardless.

**Comment by richtabor** [comment]
I suppose if the pattern doesn’t have a wrapper with its own padding, then its text/contents would be pressed up to the frame edges.

**Comment by jameskoster** [comment]
I don't think that's a problem? It's an accurate portrayal of what you'd see when inserting the pattern which is (imo) what we should be aiming for in this context. Otherwise the user could mistakenly assume a doesn't need padding when it does.

**Comment by carolinan** [comment]
I still find it confusing that if I am indeed focusing on the pattern, not the site, why are the site options like global styles available?

**Comment by jameskoster** [comment]
@carolinan do you mean the global styles panel? I think that's a reasonable question to ask, but probably better suited to a separate issue.

**Comment by carolinan** [comment]
1 Yes,
2 OK.  🙂

**Comment by tellthemachines** [comment]
> It's an accurate portrayal of what you'd see when inserting the pattern which is (imo) what we should be aiming for in this context. Otherwise the user could mistakenly assume a doesn't need padding when it does.

That depends on where the pattern is inserted: if it goes in at root level, then what we currently see in focus mode _is_ an accurate portrayal of what it'll look like. If it's inserted inside a nested container such as a Column, then the root padding won't appear.
