### ISSUE TITLE
Enhancement: Support All Block Types in Columns

### ISSUE THREAD

**Issue by mathetos** [WordPress/gutenberg#5193]
## Issue Overview
Columns are a powerful feature that needs to support all block types. Potentially, it could be a matter of simply adding the "+" icon to the right of the column:

![image](https://user-images.githubusercontent.com/930724/36520327-461b9c98-1745-11e8-8452-f57e9e54bde1.png)

**Comment by youknowriad** [comment]
Columns already support all block types, you can use the regular top bar inserter while you're in a column to insert any block there.

It's not obvious how to do it right now so we're iterating on it and fixing some bugs like #5139 but this will be improved

**Comment by youknowriad** [comment]
Thanks for opening the issue, closing as it'a already possible
