### ISSUE TITLE
Custom patterns: Patterns Library and Inserter 1:1

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51945]
It's not clear that if a pattern is synced, then it does not show up in the Patterns Inserter. In the example below, I've created three patterns — two of which are "synced". Consequently, those two are omitted from the Pattern Inserter. 

If I create a pattern, I think it should be available in the Inserter, as it is within the Library, synced or not. 

<img width="1494" alt="CleanShot 2023-06-26 at 17 11 06" src="https://github.com/WordPress/gutenberg/assets/1813435/e0581a28-4788-4cdd-9aa7-6e941bb57024">
<img width="648" alt="CleanShot 2023-06-26 at 17 15 40" src="https://github.com/WordPress/gutenberg/assets/1813435/459680de-f9a9-4acf-93ae-d46025335357">

### Proposal

Perhaps we can include an indicator of synced status in the preview, similar to how Openverse media has an ellipsis for more actions — or a treatment like badges in List view. 

<img width="638" alt="CleanShot 2023-06-26 at 17 21 46" src="https://github.com/WordPress/gutenberg/assets/1813435/754ea776-d81e-437c-a461-775798483442">

<img width="638" alt="CleanShot 2023-06-26 at 17 20 20" src="https://github.com/WordPress/gutenberg/assets/1813435/6a684d7d-9853-4d9d-8cd1-57cbd3751d24">

**Comment by aaronrobertshaw** [comment]
Thanks for writing up this issue @richtabor 👍 

It might be worth highlighting that there is a current bug (with a [pending fix](https://github.com/WordPress/gutenberg/pull/51952)) that prevents the correct separation of synced and unsynced patterns in the library.

With the above fix in place you get the following display in the library.

<img width="1158" alt="Screenshot 2023-06-27 at 3 40 23 pm" src="https://github.com/WordPress/gutenberg/assets/60436221/ff9857c8-cbe7-4a7e-a89a-9c55fdf39d65">


I agree that how the patterns are included in the inserter could do with some love. The original idea in https://github.com/WordPress/gutenberg/pull/51144 was that synced patterns (formerly reusable blocks) would continue to be located where the have been until now, in their own tab under the symbol icon, to minimise disruption. The new unsynced patterns would appear under the Patterns tab given they function the same way.

| Unsynced | Synced |
|---|---|
| <img width="656" alt="Screenshot 2023-06-27 at 3 40 47 pm" src="https://github.com/WordPress/gutenberg/assets/60436221/7e5395d7-c82e-49db-b61d-8648b5de0fbf"> | <img width="676" alt="Screenshot 2023-06-27 at 3 41 00 pm" src="https://github.com/WordPress/gutenberg/assets/60436221/5e777a24-9ec4-4126-a5a8-41c7969c1c3f"> |


@glendaviesnz might be able to point to where the original discussion occurred as it is eluding me at the moment.

Is this issue something that is a must-have for an MVP to land in 6.3?

**Comment by richtabor** [comment]
> The original idea in https://github.com/WordPress/gutenberg/pull/51144 was that synced patterns (formerly reusable blocks) would continue to be located where the have been until now, in their own tab under the symbol icon, to minimise disruption. The new unsynced patterns would appear under the Patterns tab given they function the same way.

I was thinking that _both_ would be available in the Pattern Inserter, while not changing the existing synced patterns location (for the time being at least). 

> Is this issue something that is a must-have for an MVP to land in 6.3?

I do think folks will interpret this as a bug, if you can see custom patterns in your "My patterns" category of the library, but not within the inserter.

**Comment by bgardner** [comment]
> I do think folks will interpret this as a bug, if you can see custom patterns in your "My patterns" category of the library, but not within the inserter.

@richtabor Agreed. I literally sent this message to @annezazu five minutes ago:

_"Good morning! I know you've been doing a lot of testing with the Library (patterns)... I have a Q, which I feel like I'm missing something. So I created a synced pattern via the library, but struggling to understand how it is actually added to a post/page. I understand that non-synced patterns are available with the inserter, but cannot for the life of me figure out how to add a synced one."_

**Comment by SaxonF** [comment]
The separation was intentional, primarily to ease people into the transition from reusable blocks -> patterns. Currently, patterns in the patterns tab aren't synced, and the synced tab contains reusable blocks. The idea is that for 6.3 we keep that behaviour so people can get used to the name change first, and then 6.4 we start to consolidate (e.g. add categories to user created patterns, merge categories in library etc).

If we are getting constant feedback about this we can add synced patterns back in, but that involves a little more work than what's on the surface:
- We need to highlight which patterns are synced
- We need to handle pagination as rendering potentially thousands of reusable blocks/synced patterns (some sites do have this) will kill the client performance.

**Comment by richtabor** [comment]
I would expect them to be in both areas while the shift is occurring. 

Otherwise you don't really learn the new method for finding/inserting synced patterns (i.e. reusable blocks)—you just keep using the old method, as it's the only one available anyhow.

**Comment by glendaviesnz** [comment]
We also need to make sure that the quick inserter is consistent, eg. if a user adds a synced pattern called 'My Pattern' and types `/My pattern` it will appear in the quick inserter popup, but it won't if they add it as an unsynced pattern.

**Comment by glendaviesnz** [comment]
This was fixed by https://github.com/WordPress/gutenberg/pull/54007 - the synced patterns tab has now been merged into the patterns tab.
