### ISSUE TITLE
Inconsistent pattern creation modals

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51941]
These should probably use the same modals. 

When creating from the "Create pattern" control in the block toolbar, and from the Library. 

<img width="1538" alt="CleanShot 2023-06-26 at 16 32 17" src="https://github.com/WordPress/gutenberg/assets/1813435/24d30cb2-a6fe-4de5-b39c-5ec5b0a5c01a">
<img width="1541" alt="CleanShot 2023-06-26 at 16 32 47" src="https://github.com/WordPress/gutenberg/assets/1813435/fda3f5d2-e295-4933-8d4b-a566bbb1c422">

**Comment by richtabor** [comment]
The "Turn this block into a pattern to reuse later" copy can probably be removed. It's not particularly clear/helpful. 

And you're not turning any block into a pattern in this flow; you've just selected the +.

**Comment by SaxonF** [comment]
https://github.com/WordPress/gutenberg/pull/51946
