### ISSUE TITLE
Pattern block: Rename "Convert to regular block"

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51940]
Consider renaming the "Convert to regular block" control to "Unsync", or an alternative. 

If we don't have a good icon for unsyncing, the text label would be fine enough I think.  

<img width="920" alt="CleanShot 2023-06-26 at 16 25 47" src="https://github.com/WordPress/gutenberg/assets/1813435/4c0a83f6-9718-456a-a12e-3019949621fb">

**Comment by richtabor** [comment]
An aside; I don't think we need two of the same controls so close together. Can probably remove this one within the options menu.

![CleanShot 2023-06-26 at 17 01 05](https://github.com/WordPress/gutenberg/assets/1813435/21fb9809-e661-4819-8e72-ac0aa393880d)

**Comment by carlomanf** [comment]
"Unsync" is not a real word and I don't think it belongs here or in any part of the interface, not least because it would cause difficulty for translators. What about "Stop synchronising" instead?

**Comment by richtabor** [comment]
> What about "Stop synchronising" instead?

That’s much less ideal + not intuitive. 

With the introduction of pattern creation and syncing, blocks aren’t “regular” or not. So we need to come to some solution here.

**Comment by richtabor** [comment]
Other alternative is to use “Detach”, much like Figma components.

**Comment by jasmussen** [comment]
Was just about to suggest "Detach block".

**Comment by richtabor** [comment]
> Was just about to suggest "Detach block".

What about "Detach pattern"?

**Comment by jasmussen** [comment]
Right, yes, the patterns are not always grouped 👍 👍

**Comment by carolinan** [comment]
In template parts, the text is "Detach blocks from template part," and it is only in the drop-down. Shouldn't these match?

<img width="247" alt="Screenshot 2023-06-28 at 05 39 13" src="https://github.com/WordPress/gutenberg/assets/7422055/4d0f8b59-b199-4288-b918-759ca2483242">
