### ISSUE TITLE
Enhancement: Add "Turn into Cover Image" option to standard image blocks

### ISSUE THREAD

**Issue by mathetos** [WordPress/gutenberg#5194]
## Issue Overview
Converting existing blocks into other types of related blocks is a very useful feature. The Cover Image block is currently very attractive. Users will most likely want to convert existing Image blocks into Cover images occassionally. This should be rather easy and straight-forward by adding a "Turn into Cover Image" option in the standard image block, like so:

![image](https://user-images.githubusercontent.com/930724/36520825-4abdaa40-1748-11e8-86c7-760969225116.png)

**Comment by karmatosed** [comment]
I am not sure about this one, the thing is very particular images are used usually for cover images, over just images. For now, lets leave this as it is but we can consider and always reopen, if get enough feedback that it is something desired.
