### ISSUE TITLE
Library: Set custom patterns as the initial state

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51943]
Instead of opening the Library on with Headers selected, I propose it starts with "Custom patterns" selected. 

If so, consider moving "Custom patterns" up top, perhaps in its own "group". 

### Current: 

<img width="1958" alt="CleanShot 2023-06-26 at 16 48 31" src="https://github.com/WordPress/gutenberg/assets/1813435/3978427e-08d7-4fb4-9664-5db3e782dd66">

### Proposed: 

<img width="682" alt="CleanShot 2023-06-26 at 16 52 32" src="https://github.com/WordPress/gutenberg/assets/1813435/5afbd643-34c6-4ef9-a762-59f7791e442b">

The visual above is a representation of if we renamed it "My patterns" — https://github.com/WordPress/gutenberg/issues/51939.

**Comment by richtabor** [comment]
> If so, consider moving "Custom patterns" up top, perhaps in its own "group".

If so; we should do the same in the Pattern Inserter as well:

<img width="649" alt="CleanShot 2023-06-26 at 17 09 37" src="https://github.com/WordPress/gutenberg/assets/1813435/6850fba9-d73e-4609-8099-de48c57b8e57">

**Comment by jasmussen** [comment]
Looks good to me, I'm happy for us to do this as proposed.
