### ISSUE TITLE
Adjust alignment-toolbar so that we disable the left, middle & right alignment options as needed

### ISSUE THREAD

**Issue by gubbigubbi** [WordPress/gutenberg#5195]
## Issue Overview
There will be blocks which will only require the full/wide width options and wouldnt need the left, right, centre alignment options. For example I have made a 'section' block which wraps other blocks similar to rows in page builder plugins. 

![_untitled____ _grey_matter_concrete_ _wordpress](https://user-images.githubusercontent.com/16090465/36520795-f72c12da-17de-11e8-8145-5fabb59ef191.jpg)
 
It looks like the alignment options are constants in the block-alignment component:
``const ALIGNMENT_CONTROLS = [
	{
		icon: 'editor-alignleft',
		title: __( 'Align left' ),
		align: 'left',
	},
	{
		icon: 'editor-aligncenter',
		title: __( 'Align center' ),
		align: 'center',
	},
	{
		icon: 'editor-alignright',
		title: __( 'Align right' ),
		align: 'right',
	},
];``

## Possible Solution
It would be cool if when defining the <BlockAlignmentToolbar /> you could specifiy which alignment constants could shown. Something like:

``
<BlockAligmnentToolbar allowedControls = array['left'] />

``

I am happy to help with expanding the documentation on this feature.

**Comment by youknowriad** [comment]
Ther's a prop "controls" you can use to do that

`<BlockAligmnentToolbar controls={['left']} />`

**Comment by gziolo** [comment]
It is also available to specify the list of alignment controls when registering your block as described here: https://github.com/WordPress/gutenberg/blob/a3ceee55afbe0200a1567945e14de6f3b3f14f61/docs/block-api.md#supports-optional. This update to documentation should land in the master together with the changes included in #5099.

**Comment by gubbigubbi** [comment]
Ah great maybe we should add that to the docs under that  component? I
would be happy to help.

**Comment by gziolo** [comment]
Good idea to include it there, too. If you would open a PR, that would be awesome 👍

**Comment by gubbigubbi** [comment]
Cheers will do this weekend :)
