### ISSUE TITLE
Library: Incorrect snackbar text and sidebar menu when removing template/template part

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#51969]
### Description

I believe the following behavior that occurs when a template part is deleted is not what was intended.

- Displayed as `"undefined" deleted.` on snackbar.
- Nothing appears in the side menu.

### Step-by-step reproduction instructions

- Access the Site Editor > Library.
- Click "Create pattern" button > Select "Create template part"
- Create template part.
- Click the document title bar.
- Select "Delete template part".
- A snackbar with the text `"undefined" deleted.` should appear. Also, nothing will appear in the sidebar menu.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/5217fbff-e880-4ac5-935b-3ec55366638e

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I have confirmed that this problem occurs with template as well as template part.

https://github.com/WordPress/gutenberg/assets/54422211/4672885b-4184-449c-90f8-5913053448d9

**Comment by aaronrobertshaw** [comment]
It appears that the entity record received when deleting via the List page vs the command palette is slightly different.

On the List page, the record contains a `template.title.rendered` property which is what the `removeTemplate` action expects, hence the correct snackbar notice there. The record passed on from the command palette only contains a simple string for the `template.title` property. 

I haven't put my finger on why there's a difference just yet but will keep digging.

**Comment by aaronrobertshaw** [comment]
This was fixed in https://github.com/WordPress/gutenberg/pull/52034.
