### ISSUE TITLE
Command center: Open library mapped to a non-existent path

### ISSUE THREAD

**Issue by franzaurus** [WordPress/gutenberg#51960]
### Description

Opening Library from the Command center leads to a non-existent page `/wp-admin/site-editor.php?path=%2Fwp_template_part`. While it should be mapped to `/wp-admin/site-editor.php?path=%2Flibrary.`

This bug is only triggered via the Command center. While manually accessing the Library from the left sidebar menu leads to a correct path. 

### Step-by-step reproduction instructions

1. Press Ctrl-K (win) or Command-K (mac) to invoke the Command center
2. Type or choose Open Library
3. Observe the left sidebar menu disappears
4. Observe the path in the address bar leads to `/wp-admin/site-editor.php?path=%2Fwp_template_part` which is non-exist.

### Wrong library page path

![wrong-open-library-GB1610rc1](https://github.com/WordPress/gutenberg/assets/79677758/efc55b08-b1dd-4a0f-9ef1-100140901335)

### Right library page path

![right-open-library-GB1610rc1](https://github.com/WordPress/gutenberg/assets/79677758/ea15d542-1830-42ae-81a8-4ffae0f2c1ec)

### Environment info

Local WP, WP 6.2.2, Gutenberg 16.1.0 RC-1, Windows 11, Chrome 114.0.5735.134.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @franzaurus,

Thanks for the report.

I believe this issue was resolved in #51837 and would like to close this issue. If I have missed any points, please feel free to comment.
