### ISSUE TITLE
DatePicker: Event dots are adjacent to the inside of the button

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#51966]
## What problem does this address?

The `DatePicker` component adds a background color to the current or selected date. In addition, days that have events will have a small dot under the number.

When these two overlap, the dot is adjacent to the inside of the background color, which looks unnatural to me.

![scale](https://github.com/WordPress/gutenberg/assets/54422211/5d966f09-61d1-4b3e-a697-5021330bc026)

## What is your proposed solution?
By shifting this dot slightly (about 2px) upward, I think it looks just fine.

### Default State

| Actual | Expected |
|--------|--------|
| ![actual](https://github.com/WordPress/gutenberg/assets/54422211/7ac54c1a-e703-4d88-bebd-44dfb3f9f993) | ![expected](https://github.com/WordPress/gutenberg/assets/54422211/8ccc62af-cf82-4ada-9048-d249b7ecedc7) |

### Focused STate

| Actual | Expected |
|--------|--------|
| ![actual-focused](https://github.com/WordPress/gutenberg/assets/54422211/ec8f9fbb-6e85-4616-a0e3-ab8fd9a64cb3) | ![expected-focus](https://github.com/WordPress/gutenberg/assets/54422211/dbaed95c-905c-40b8-9ef9-d7afae14643c) |

**Comment by miminari** [comment]
I agree that dot should shift its position to avoid contact. And, If possible, I think it would be better if the area could be expanded a bit for accessibility.

**Comment by kurudrive** [comment]
I tried shifting the dot 2px upward, but the space between it and the number became too narrow. I think it might be better to either expand the button area or consider a different design.

<img width="280" alt="スクリーンショット 2023-10-20 15 13 17" src="https://github.com/WordPress/gutenberg/assets/3272660/7dfa2bbc-2409-495b-bc00-399104661835">
<img width="280" alt="スクリーンショット 2023-10-20 15 14 26" src="https://github.com/WordPress/gutenberg/assets/3272660/b30c1254-0896-4807-b92f-a47c7f2446ad">

**Comment by t-hamano** [comment]
Fixed by #55502
