### ISSUE TITLE
Footnote: changing link color doesn't update footnote arrow link color

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51991]
### Description

Using 16.1 RC 2 and testing footnotes, I noticed that after setting a link color, that color is only respected in the text itself but not in the arrow to return next to the footnote itself to return. I expect to be able to have the colors match, especially since the current color offered isn't accessibility ready. cc @ellatrix for more insight as I wonder if this has to be set elsewhere. 

### Step-by-step reproduction instructions

1. Open the Post Editor.
2. Add some text. 
3. Highlight some text, use the drop down menu in the block toolbar to add a footnote.
4. Open block settings and set a link color. 
5. Notice this updates the (1) color but not the arrow of the footnote itself.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/26996883/4f48811c-6efc-4a41-bd4c-70f6c543407b

### Environment info

- WP 6.2.2
- GB 16.1 RC 2
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment]
Hm, so you expect the link colour of the anchor to also change the back link colour? Not sure how this all works. Do you know who created this feature?

**Comment by annezazu** [comment]
I do expect that or at least a way to change the color of the arrow/back link. As for the "feature", do you mean color options?

**Comment by ghorivipul97** [comment]
@annezazu I'm here, can you able to assign me

**Comment by t-hamano** [comment]
I think the link color change should only apply to the links in that block (i.e. Paragraph Block) and should not affect other blocks (i.e. Footnotes block).  If the Footnote block itself supported link colors, this problem would be solved.

**Comment by ghorivipul97** [comment]
okay @t-hamano 
I will do it

**Comment by ndiego** [comment]
> I think the link color change should only apply to the links in that block (i.e. Paragraph Block) and should not affect other blocks (i.e. Footnotes block). If the Footnote block itself supported link colors, this problem would be solved.

Agreed. I think the next step here is to add color (and additional block supports) to the Footnotes block. 

@ghorivipul97 is this something you are actively working on? If not, can you unassign yourself?

**Comment by mikachan** [comment]
I've opened a quick PR for updating the block supports, https://github.com/WordPress/gutenberg/pull/52897, as I _think_ this is all we need to address this issue.

Happy to work with anything @ghorivipul97 has in progress, too!

**Comment by ghorivipul97** [comment]
Hello @mikachan 
it's done and raise PR.
