### ISSUE TITLE
`wp:query-no-results` triggered on homepage of fresh WordPress install

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#52007]
### Description

There seems to be an issue with `wp:query-no-results` block triggering on fresh WordPress installation home page even if it contains "Hello world!" post (so the query is not really empty and it contains results).

### Step-by-step reproduction instructions

1. In Twenty Twenty-Three theme open the `templates/home.html` file and add `<!-- wp:query-no-results --><!-- wp:paragraph --><p>Nothing found.</p><!-- /wp:paragraph --><!-- /wp:query-no-results -->` after Pagination block.
2. Set up fresh WordPress installation with the modified theme and check the homepage. Notice the "Nothing found." text even if the query loop displays "Hello world!" post.

### Screenshots, screen recording, code snippet

![wp develop___EMPTY (testing initial install)--20230628055416](https://github.com/WordPress/gutenberg/assets/2456735/937fec7f-344a-4d9e-aa73-cf759edeafef)

### Environment info

- WordPress 6.2.2
- tested also with Gutenberg 16.0.0 but the issue persist

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@webmandesign

Thanks for the report.

This issue has also been reported in #47793, so I would like to close this issue. If I have missed something, please feel free to comment.

**Comment by webmandesign** [comment]
Thanks for the info and sorry for duplicate. You can close this issue.
