### ISSUE TITLE
Position of block error messages

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#5201]
## Issue Overview
If a very long block shows an error, its hard to understand and to find it, because it is in the middle of the block.  So you have to scroll a lot to see that there is an error.

## Possible Solution
- Show the error message at the top of the Block
- The error message scrolls within the block

## Screenshots / Video
![error_test](https://user-images.githubusercontent.com/695201/36539006-a3b40ce2-17d5-11e8-8ae0-eefb512af920.gif)

**Comment by karmatosed** [comment]
I think I would agree we should just show at the top and maybe not even render the full block in this case, if we can do that.

**Comment by Soean** [comment]
Was fixed in #5383
