### ISSUE TITLE
Library: Browser scrollbar blinks at certain browser width

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#52027]
### Description

Note: I have reproduced this problem on a Windows OS, not sure if it reproduces on a Mac OS. I would appreciate it if someone could test it.

On the Library page of the Site Editor, the browser scroll bar blinks at certain browser width. The problem appears to occur at the "break" between whether the scrollbar appears in the browser or not.

It occurs in Chrome and Edge, but does not appear to occur in Firefox.

### Step-by-step reproduction instructions

- Go to the Library page of the Site Editor.
- Go to the Uncategorized category; there should be two patterns, Comments and Post Meta.
- Adjust the width of your browser and check for a blinking scrollbar point.

#### Chrome (Version 114.0.5735.199)

https://github.com/WordPress/gutenberg/assets/54422211/016b7862-02de-4f84-943d-1be9f6e407f2

#### Edge (Version 114.0.1823.58)

https://github.com/WordPress/gutenberg/assets/54422211/16671695-4dc7-486f-9ecb-c16451cfa6df

#### Firefox (Version 114.0.1)

https://github.com/WordPress/gutenberg/assets/54422211/12a3dc41-f072-4aee-af03-54531e56d160

### Environment info

- WordPress Version: 6.3-alpha-56079
- Gutenberg Version: Latest trunk (16.1.0)
- OS: Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by firoz2456** [comment]
I can confirm that I am able to replicate this.

WordPress Version: 6.3-alpha-55909
Gutenberg Version: Latest trunk (16.1.0)
OS: macOS Ventura (M1 Pro)

Browser: Google Chrome 

https://github.com/WordPress/gutenberg/assets/8054727/78c0e705-a836-4807-b88d-e7294365ddfe



Browser: Microsoft Edge Version 114.0.1823.67 

https://github.com/WordPress/gutenberg/assets/8054727/2fe283b2-b434-440d-b68b-de144eb71a59

**Comment by bph** [comment]
Tested again this morning with WordPress 6.3 Beta 3 and couldn't replicate. Seems to be working without issues. 

https://github.com/WordPress/gutenberg/assets/39980/0a3f232b-9e61-4e33-a457-75a933fcbe58

I tested it with and without Gutenberg plugin activated. 

**Browser versions**
- Chrome 114.0.5735.198
- Firefox Developer Edition: 115.0b9 (64-bit
- Safari 16.4

**Comment by t-hamano** [comment]
@bph 

Thanks for the testing. I have found myself submitting a similar problem in the past with #46793. This problem may only occur when the browser's scrollbars have a physical width. Perhaps on a Mac, you might be able to reproduce it by changing the scrollbars to always be visible.

**Comment by t-hamano** [comment]
@firoz2456

Your screencast appears to be testing another issue. If you would like, I would be happy to post again there if there is another issue you are trying to test.

**Comment by aaronrobertshaw** [comment]
I was able to replicate the blinking scrollbar on a Mac when setting scrollbars to always be visible.

My guess is the [block preview component](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-preview/auto.js#L65-L66) is where this originates. When inspecting it via dev tools, you can see the transform `scale()` and `height` styles alternating between values. The block preview adjusts based on a resize observer, so the appearance of the scrollbar may trigger that? 

FWIW this seems like the definition of an edge case 🙃 

@kevin940726 I believe you might have recently looked into the block previews, do you have any thoughts?
