### ISSUE TITLE
Footnotes: Excerpts displays the link text as a * after the text content

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#52035]
## What problem does this address?

When the post content has one or more footnotes, the excerpt block picks up the link text, the visually hidden star, as part of the content.
This might be correct, but I found the result difficult to read.

Example from Twenty Twenty Three:
<img width="644" alt="List of two blog posts where the excerpt block shows the footnotes as a *" src="https://github.com/WordPress/gutenberg/assets/7422055/73f40446-0c67-4683-b2ba-f6fd17634407">

## What is your proposed solution?
I am not sure if it is worth trying to remove the star from the excerpt. Normally in excerpts, link texts are not removed, but I am not sure if the star indicates clearly enough that it represents a footnote.

**Comment by annezazu** [comment]
@ellatrix and cc'ing @WordPress/gutenberg-design

**Comment by jasmussen** [comment]
Good issue. I'd suggest that the excerpt commonly exists to be shown in archive views, where the actual footnote is unlikely to show up. In that light, I'd suggest trying to hide it from the excerpt.

**Comment by ellatrix** [comment]
I wonder if we should just remove the asterisk altogether 🤔 That would also remove the CSS hack where we have to hide it to make place for the counter as a pseudo element. OR we have to remove the CSS counter and replace in PHP.

**Comment by jasmussen** [comment]
Removing the asterisk altogether would make the excerpt have no indication of footnotes, correct? I'd agree with that, it seems fine to have an entirely footnote-less excerpt.

**Comment by ellatrix** [comment]
That's correct, they would be invisible if no CSS is present. The downside of that there's no fallback if there is no CSS: think of emails, RSS...

One alternative is to not use CSS counters and replace/add the anchor content in PHP.

Any opinions? Cc @mtias @mcsf

**Comment by mcsf** [comment]
I chatted a bit with Ella about this.

At first glance, I kind of like the "safety" of CSS-only decorations, in that footnotes gracefully disappear if we are in a context in which we might not expect them, like excerpts. On the other hand, we can't simply ignore syndication, emails and general consumption via the REST API.

I think that part of the solution is to think of footnotes as a first-class concept of posts in the same way that `nextpage`, `more` and shortcodes are. But this is scarier. It implies that footnotes should be well handled all throughout the core logic for WP posts.

We have room to play with the exact markup that we choose for the anchors, where/how we style them (with stylesheets, with inline styles, with server-side injection, etc.), but we can't shy away from thinking of footnotes as a first-class concept — think of [`wp_trim_excerpt`](https://developer.wordpress.org/reference/functions/wp_trim_excerpt/), etc.

Finally, let's not forget that there is a lot of nuance even within those modalities: we can be fairly confident that nor the anchors nor the notes should be visible in an excerpt, but when it comes to emails like newsletters I can imagine that different site admins have different expectations (are the footnotes essential to the content, or should users visit the website to read everything?). And what about general consumers using the REST API? Presumably they should be given the full content, but — unlike in the front end — we don't know how they'll handle CSS (especially fancy CSS like `counter`).
