### ISSUE TITLE
Block theme styles/new-style.json edits not reflecting instantly on front end

### ISSUE THREAD

**Issue by kauaicreative** [WordPress/gutenberg#52041]
### Description

Still waiting for a fix for this. If I edit theme/styles/new-style.json it does not reflect on the front end.

Neither of these solve the issue for me:  
`define( 'WP_DEBUG', true ); `
`wp transient delete --all`

Instead I have to go the wp-admin > Browse Styles. re-select the new-style and resave for the changes to take effect.

The issue is also referenced here https://wordpress.org/support/topic/theme-json-caching/#post-16854526

### Step-by-step reproduction instructions

Create new style. Select the style. Change the style.theme. The changes are not reflected on the front end.

### Environment info

- WP 6.2.2
- Guten 16.1.0
- php 8.0.22
- Mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kauaicreative** [comment]
On the subject, how do you get the current selected style for the current theme? e.g. styles/style.json

**Comment by t-hamano** [comment]
Hi @kauaicreative,

I think `WP_DEVELOPMENT_MODE`, which will be introduced in WordPress 6.3, will help.

[Configuring development mode in 6.3 – Make WordPress Core](https://make.wordpress.org/core/2023/07/14/configuring-development-mode-in-6-3/)

> However, if you are actively developing a theme on the site and modifying theme.json constantly, having to manually invalidate the cache all the time would be detrimental to the development workflow. Therefore, that specific caching functionality is bypassed if the development mode is set to “theme”.

As far as I can tell from reading this, it should always read the contents of the latest json file if you define it as follows:

```php
define( 'WP_DEVELOPMENT_MODE', 'theme' );
```

**Comment by kauaicreative** [comment]
Yes, I believe this fixes the issue `define( 'WP_DEVELOPMENT_MODE', 'theme' );`
