### ISSUE TITLE
Create README for "block-caption" component

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#52047]
As per #22891 the component "block-caption" needs a proper `README.md` that can guide developers using them.

[The README.md for the `alignment-control` component ](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/alignment-control/README.md) is a good model to document the rest of the components

I assign this issue to @SiobhyB as the last developer who worked in this issue (at the time of this issue's creation)
Also pinging @david-szabo97 , @lukewalczak  and @SergioEstevao   in case any of them want to take over this issue.

Please, let me know if there's anything I can do to unblock the creation of this README for this component.

**Comment by SiobhyB** [comment]
@juanmaguitar, I'd be happy to help with this but wanted to note I have some upcoming vacation. If there's no urgency, I can help with this request in a couple of weeks.

**Comment by SiobhyB** [comment]
This is a WIP at https://github.com/WordPress/gutenberg/pull/52535, I aim for the PR to be ready for review in the next couple of days.

**Comment by SiobhyB** [comment]
Noting for posterity that the PR is ready for review at https://github.com/WordPress/gutenberg/pull/52535.
