### ISSUE TITLE
Rename "Library" to just "Patterns"

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#52042]
**For 6.3 Beta**

As we are taking the opportunity to unify some concepts and streamline how users work with patterns, reusable blocks, and template parts, we ended up using the generic label Library. I think this is suboptimal for a few reasons, so I propose calling it just Patterns.

Rationale

- Discovery: this is an opportunity to make patterns front and center as we are introducing the ability to save custom patterns. They should be front and center in the "Design" tab.
- Clarity: library can be obscure and overlaps with other terminology (like Media Library). We didn't get to add font library management in this round, but it would have made things more confusing (would a user expect to see their font library under "Styles" or an item called "Library"?). Calling it patterns removes that ambiguity.
- Presence: patterns is a unique name that has been established in the WP branding parlance for a bit and deserves more clear placement.

**Comment by carolinan** [comment]
I think this is too early and confusing at this time, because template parts are not renamed to patterns in this version.
It is confusing enough that the UI includes "pattern" in the heading and description, when it is  not a pattern.

For someone who sees the updated navigation sidebar for the first time, it will be confusing because the previous template part menu item is missing, it is not that intuitive to look for them under "Patterns".

A declaration of intent for a future version, would help prepare users.

**Comment by mtias** [comment]
I hear you, but I do think it's more intuitive to find them under a Patterns label (that's how you discover headers and footers in the directory, for example) than under a generic term _Library_. Block template parts have always been design patterns, we just discriminated based on data organization, permissions, and theme building semantics.

If this proves difficult to do in one go based on feedback we hear during beta we can pull out template parts out of it into the root level. But in both cases, Library is unnecessary.

**Comment by t-hamano** [comment]
If I understand correctly, the words mentioned here mean the following:

- **Patterns**: means the concept of **design patterns**. Block patterns, template parts, etc. are included in this concept.
- **Pattern**: means "**block pattern**" which is a set of multiple blocks.

In English, the meaning may be identified by whether it is singular or plural. However, languages, especially in Asia, do not identify singular and plural and have the same word.

If the word _Library_ were renamed _Patterns_, we would be more unable to identify whether it represents a design pattern or a block pattern.

**Comment by mtias** [comment]
Not making a distinction here between "design patterns" and "block pattern", it should be the same.

**Comment by jasmussen** [comment]
I quite like "Patterns", and these reasons stand out to me:

* I'd look for "Fonts" in "Styles" anyway
* "Patterns" won't confuse me with Media Library

Mostly, as the WordPress pattern library gets integrated, as patterns get upgraded, and as the Patterns block (#48458) comes into being, having a singular section that embodies these feels like a really strong proposition, as the central place where you can manage, review, even edit your patterns in a central and easily findable place. I think this is going to be especially important to have in the site editor, as I could see a future where patterns can be copied over from one theme to the next between theme activations, needing a place to live on in their theme-detached state. "Library" just feels less obvious for those flows.

**Comment by carolinan** [comment]
Placing patterns under a menu item called patterns is not the issue: Placing things that are not patterns under the same menu makes them difficult to discover.

**Comment by aaronrobertshaw** [comment]
I've made a start on the process of renaming the Library to Patterns (https://github.com/WordPress/gutenberg/pull/52102). It might help the discussion if people can see the Patterns section in action.

**Comment by aaronrobertshaw** [comment]
It looks like we'll be going ahead with the renaming of Library to Patterns in #52102 so it can make the next beta. Any feedback on it in action is very much welcome. 

It also seems the sticking point around template parts being under patterns, could be a subjective one, depending on how you feel about template parts really being a special type of pattern. Perhaps that concern could be lessened by knowing that any discomfort here should be temporary as we work through unifying everything pattern related; parts, reusable blocks, patterns etc.

Thank you for the discussion and concerns shared here 👍

**Comment by carolinan** [comment]
I would like to see a bigger effort on helping the **users** transition and use the interface intuitively and efficiently, my perceived "feelings of discomfort" are not what matters.

**Comment by aaronrobertshaw** [comment]
My apologies if I came across as dismissive in my last comment, my aim was to reassure that our efforts on unifying patterns and resolving this issue are only just beginning.

Your concern is 100% valid and I should have communicated that better.

We have every intention of helping guide users in their transition. The Patterns feature is [evolving rapidly](https://github.com/WordPress/gutenberg/issues/51948) and there are already some PRs being created [adding guidance](https://github.com/WordPress/gutenberg/pull/51771) for the block editor side of things. That PR is only an initial step, we have plans to add some guidance around Patterns in the site editor early next week.

If you have the bandwidth, it would be great if you could review the coming enhancements and make sure they measure up. 

Thank you again for the clarification and feedback 🙇
