### ISSUE TITLE
Stabilize `__experimentalDefaultBlock` and `__experimentalDirectInsert` APIs

### ISSUE THREAD

**Issue by sethrubenstein** [WordPress/gutenberg#52068]
## What problem does this address?
As `__experimentalDefaultBlock` and `__experimentalDirectInsert` are in use across a few blocks now and have been in use for some time it's [agreed](https://github.com/WordPress/gutenberg/pull/51026#issuecomment-1596716951) that it's time to stabilize these APIs. 

The big driver for this is to support the inclusion of `defaultBlock` as an attribute starting with the `core/navigation` in #50982.

## What is your proposed solution?
Stabilize the `__experimentalDefaultBlock` and `__experimentalDirectInsert` by completing the following:
- [x] Remove `__experimental` prefix in codebase and replace with `defaultBlock` and `directInsert`.
- [x] Add `deprecated` calls where existing implementations are found. 
- [x] Write small doc explaining usage and usage of associated other api's/selectors like `__experimentalGetDirectInsertBlock`

**Comment by sethrubenstein** [comment]
@getdave Originally we were planning on two pr's for each of these API's [per your comment](https://github.com/WordPress/gutenberg/pull/51026#issuecomment-1600506787), however after closer examination I realize that `__experimentalGetDirectInsertBlock` is dependent on both, and I want to stabilize that as well so its easiest on us to just work out of one branch and update all this in one go. Just wanted to make sure that wasn't an absolute no-no?

**Comment by annezazu** [comment]
Closing this out with https://github.com/WordPress/gutenberg/pull/52083 merged. Feel free to reopen if wrong!
