### ISSUE TITLE
Create README for "block-controls" component 

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#52061]
As per #22891 the component "block-controls" needs a proper `README.md` that can guide developers using them.

[The README.md for the `alignment-control` component ](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/alignment-control/README.md) is a good model to document the rest of the components

I assign this issue to @ciampo and @jsnajdr as the last developers who worked on this issue (at the time of this issue's creation)
Also pinging @tyxla in case he wants to take over this issue.

Please, let me know if there's anything I can do to unblock the creation of this README for this component.

**Comment by tyxla** [comment]
Drafted a concise README for this one in #52366.
