### ISSUE TITLE
Add README.md file for text-transform-control component

### ISSUE THREAD

**Issue by mburridge** [WordPress/gutenberg#52072]
## What problem does this address?

The [text-transform-control component](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/text-transform-control) is missing a README.md file. As per #22891
## What is your proposed solution?

Pinging original creator of this component @aaronrobertshaw. and other recent committers @mirka and @noisysocks, if you have the bandwidth could you add a README.md file for this component. Thank you.

[This README](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/alignment-control/README.md) is a good example to follow.

Please let me know if there's anything I can do to help with the creation of the README.md file for this component.

**Comment by BenjaminZekavica** [comment]
@mburridge I added the documentation into the pull request  #52243

**Comment by mburridge** [comment]
Awesome, thanks @BenjaminZekavica,  I've approved the PR and have re-run the tests.

**Comment by mburridge** [comment]
Checks have now passed 🙌

**Comment by BenjaminZekavica** [comment]
@mburridge Thank you so much :)

**Comment by mburridge** [comment]
Closing as done by [#52243](https://github.com/WordPress/gutenberg/pull/52243)
