### ISSUE TITLE
Add README.md file for text-decoration-control component

### ISSUE THREAD

**Issue by mburridge** [WordPress/gutenberg#52071]
## What problem does this address?

The [text-decoration-control component](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/text-decoration-control) is missing a README.md file. As per #22891
## What is your proposed solution?

Pinging original creator of this component @aaronrobertshaw. and other recent committers @mirka and @noisysocks if you have the bandwidth could you add a README.md file for this component. Thank you.

[This README](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/alignment-control/README.md) is a good example to follow.

Please let me know if there's anything I can do to help with the creation of the README.md file for this component.

**Comment by BenjaminZekavica** [comment]
Hallo :) I added the documentation for this Issue: https://github.com/WordPress/gutenberg/pull/57184

**Comment by BenjaminZekavica** [comment]
@aaronrobertshaw Do you can close this issue?

**Comment by mirka** [comment]
Closed by #57184
