### ISSUE TITLE
Add README.md file for use-setting component

### ISSUE THREAD

**Issue by mburridge** [WordPress/gutenberg#52079]
## What problem does this address?

The [use-setting component](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/use-setting) is missing a README.md file. As per #22891
## What is your proposed solution?

Pinging original creator of this component @youknowriad . and other recent committers @andrewserong and @ingeniumed, if you have the bandwidth could you add a README.md file for this component. Thank you.

[This README](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/alignment-control/README.md) is a good example to follow.

Please let me know if there's anything I can do to help with the creation of the README.md file for this component.

**Comment by ingeniumed** [comment]
Thanks for bringing this up! I'm hoping to devote some time to this, this week or next week and get a PR up quickly to address it 👍🏾

**Comment by ingeniumed** [comment]
I have put up #53162 to address this. Hopefully everything in there is sufficient to close off this issue.

**Comment by mburridge** [comment]
Thanks for creating the readme.md @ingeniumed. I've approved your [PR](https://github.com/WordPress/gutenberg/pull/53162).

**Comment by ingeniumed** [comment]
Thanks for approving it @mburridge! You are good to merge it as well, as I don't have the permission to do that.

**Comment by mburridge** [comment]
> Thanks for approving it @mburridge! You are good to merge it as well, as I don't have the permission to do that.

Done! Great job @ingeniumed  🙌

**Comment by ingeniumed** [comment]
@mburridge Just mentioning it here for posterity - I think the PR got closed instead of being merged. Would be able to re-open and merge it in?

**Comment by mburridge** [comment]
Looks like it's been merged now.
