### ISSUE TITLE
Footnotes Block: unable to insert footnote on List Block

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#52087]
### Description

Footnotes are not working properly on the List Block. The link in the highlighted piece of text will be added, but the editor will not jump correctly to the Footnote Block. Similar to https://github.com/WordPress/gutenberg/issues/52084

### Step-by-step reproduction instructions

1. Add the List Block to a post or page
2. Add a List item
3. Add a Footnote to the List item
4. The superscript link will be added to the highlighted text, but the screen will not just to the Footnote Block correctly, allowing to add the footnote

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/14153300/183e1591-43d8-477a-92b5-a061c11738ec

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I am able to confirm as well. cc @ellatrix

**Comment by ellatrix** [comment]
Let's close this in favour of #52084, it's the same issue.
