### ISSUE TITLE
Distraction free mode triggered when viewing styles, if no other theme variations 

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#52085]
Uncovered a bug where Distraction Free is enabled when clicking "Styles" from the Site Editor, if a theme only has one style variation. cc @draganescu 

To reproduce, enable a theme without any alternative variations (like [Stacks](https://wordpress.org/themes/stacks/)), then view the Site Editor > Styles panel. 

https://github.com/WordPress/gutenberg/assets/1813435/b8e44b64-1b5d-4872-a16f-3891b2a0b0b1

**Comment by draganescu** [comment]
I can't reproduce this on `trunk` with Stacks. This https://github.com/WordPress/gutenberg/blob/c5d477ab54ad98d3998809ba1e72675eb70f48bc/packages/edit-site/src/components/sidebar-navigation-screen-global-styles/index.js#L59 should turn DFM off when that styles button is clicked.

**Comment by richtabor** [comment]
I can consistently reproduce it, with the same conditions.  😅

I get the snackbar too (and DFM wasn't turned off). Looks like it's doing the opposite of the intent.

<img width="1447" alt="CleanShot 2023-06-28 at 15 21 58" src="https://github.com/WordPress/gutenberg/assets/1813435/fa34b67d-c699-4780-be87-0bf179628348">

**Comment by draganescu** [comment]
Yes, it's a bug in the exact line I mentioned 🤦🏻

[gutenberg/packages/edit-site/src/components/sidebar-navigation-screen-global-styles/index.js](https://github.com/WordPress/gutenberg/blob/c5d477ab54ad98d3998809ba1e72675eb70f48bc/packages/edit-site/src/components/sidebar-navigation-screen-global-styles/index.js#L59)

the feature is toggled ON when its OFF.
