### ISSUE TITLE
WP6.3: Command Palette has no style applied

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#52097]
### Description

In WordPress 6.3 bera-2, the intended style does not appear to be applied to the command palette.

![command-palette](https://github.com/WordPress/gutenberg/assets/54422211/a28624ee-e662-4353-bcea-9434607224a8)

### Step-by-step reproduction instructions

N/A

### Environment info

WordPress Version: 6.3 beta-2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I submitted the ticket because I thought the command package style was not enqueued at the WP core:
https://core.trac.wordpress.org/ticket/58667

Here is the pull request: https://github.com/WordPress/wordpress-develop/pull/4753

**Comment by ndiego** [comment]
Confirmed and added to the 6.3 board.

**Comment by t-hamano** [comment]
This issue has been fixed by [Changeset 56125](https://core.trac.wordpress.org/changeset/56125) and I would like to close it.
