### ISSUE TITLE
Original patterns created in Explore all patterns are not displayed

### ISSUE THREAD

**Issue by Olein-jp** [WordPress/gutenberg#52093]
### Description

You can select the original pattern you created with inserter > pattern, but it is not displayed in Explore all patterns.

### Step-by-step reproduction instructions

1. Create pattern by some blocks
2. Open inserter, then click "Patterns"
3. We can find my created pattern in pattern category named "custom patterns" and possible insert pattern
4. Click "Explore all patterns" in bottom of left sidebar and show modal
5. But we can't find my created patten

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/28924629/bfbe5270-a3a0-48a3-93cd-cfdbfed77ed0

### Environment info

- WordPress 6.3 Beta 2
- Nothing activated without WordPress Beta Tester
- Activated TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting. I think it has already been fixed by https://github.com/WordPress/gutenberg/pull/51889 (edit: the actual PR that included the fix was #51947), but that bug fix didn't make it into beta 2 in time. It should be in beta 3.
