### ISSUE TITLE
Your so-called preview tool is wrong all the time. Get rid of it finally! Allow us to preview pages with ONE click!

### ISSUE THREAD

**Issue by mrfatguy** [WordPress/gutenberg#52105]
## Intro

I know that this has been reported a number of times in the past years, but nothing has changed so far. My irritation level gets a little higher, so I assumed (maybe incorrectly) that this report will be that "last piece to start the avalanche".

This post is emotional. Sorry, if anyone gets offended by many uppercases and bolds here. But the thing is that we are waiting for this change for a couple of years. And nothing is done due to some unclean reasons. Emotional tension seems natural in this case.

## What problem does this address?

Ladies and gentlemen of the fabulous Gutenberg development team. We know that you are doing a really, really good job for us, completely free and in your spare time, and our gratitude is endless. But there is one thing about which you are very, very wrong!

We must sit down and talk. Seriously. You are not listening to us (millions of users of your software)!

This "thing":

![image](https://github.com/WordPress/gutenberg/assets/2903392/d932b521-8195-45d6-aed0-2d2cb3f827ca)

Is **WRONG**, **STUPID**, **POINTLESS** and **NON-SENSE**!

This is because you have built this tool based on a completely wrong assumptions:

1. It is **NOT ENOUGH** to simply change the dimension of editor, browser or screen to get mobile or tablet viewport
2. You would have to take CSS and other formatting information from current theme which you are certainly not doing
3. You would have to include CSS overrides that are coming from "Custom CSS" section which you are also not doing at all

These three points causes that **your tool is completely useless and never used by anyone**!

I have **twenty six** sites in my blog network, of which _each and every one is using_ a different theme. For all of those themes and for all of three modes that your weird tool offers **absolutely non of them is correct**!

No matter, which page (out of 26) I pick and no matter, if I am previewing it in _Desktop_, _Tablet_ or _Mobile_ mode, the viewport (in Gutenberg editor) **never correctly replicates** the actual page look.

Text spans to another line in a completely different places than your "preview" suggests it will. Images are differently displayed, everything looks completely different.

The truth is that for the past 5+ years, since you have introduced this tool, for twenty six pages, I used it **ZERO times**. Given 3 modes times 26 pages gives us 78 (seventy eight!) times that your "tool" is wrong. **EACH DAY AND EVERY DAY**.

Therefore this boils down to the assumption that for some weird reasons you are simply forcing users to click twice in order to see external tab preview of their page (**the only one** accurate preview).

## What is your proposed solution?

GET RID of this tool as soon as possible. You are and were all wrong. Remove every bit of this and give us a clean tool. Where clicking **ONE TIME** on a button causes us to see accurate preview of our post in separate tab.

STOP this madness! Stop forcing us to do non-sense actions. Stop forcing us to click TWICE to get to the only reasonable tool in this.

Stop harming the planet! Millions of post published each day times 3-4 previews of each post (that currently requires TWO clicks) means millions of seconds wasted and GIGAWATS of the energy lost for powering computers and displays.

This is the feature that millions of us wants that is not given to us due to couple of dev folks decision.

Period. No strings attached. It is that simple.

BTW: _Disney was so wrong about where to go with their vision of Star Wars_ that a couple of folks were forced to start a Kickstarter funding to get billion of dollars and to stop Disney from producing another part of this serie. Are you by any chance a little more reasonable or do we also have to start a Kickstarter funding projects to get rid of this tool from Gutenberg once and forever?_

## Tech stuff

Please, do not close this report. Hear us.

Please, do not respond with the suggestion that I should "get my own hands dirty", write and push own PR for such change. I'd loved to so. But I am 10.000% sure that unless there is a "political" agreement on your side each and every such PR will get rejected. 

So until you confirm that we swept all the tears, we said all the good-byes and we are ready to ship that tool into the past, any piece of code written in any PR will be another huge waste of energy. As it gets rejected immediately. Sorry, sad truth.

**Comment by ndiego** [comment]
WordPress 6.3 will include a top-level button that allows you to directly access the page/post in a new tab. You can test this now in the latest version of Gutenberg.

<img width="314" alt="image" src="https://github.com/WordPress/gutenberg/assets/4832319/52ea08ea-9881-4315-84da-a8af8517e1a5">

While I understand that you have strong feelings about the preview tool, it can be very handy depending on the theme you are using. If you have a block theme where virtually all of the CSS is driven by theme.json, the previews are quite accurate. That said, a top-level button for previewing in a new tab was commonly requested and is a great addition.

**Comment by trejder** [comment]
@ndiego Thank you for your update. If a one-click solution is just one-release ahead then I think we can safely close this report.

**Comment by trejder** [comment]
@ndiego No, no, no, this is all wrong! _View Page_ does what it says -- shows page. Saved one (after clicking _Publish_ or _Update_). Using it you cannot **see changes that you are currently working on** -- the one that hasn't been published or updated so far.

This is a _completely_ different functionality! We're using _Preview in a new tab_ (to access which we need those damn TWO clicks) to **preview** changes that hasn't been published so far.

Sorry, the issue remains. This cry-report is still in force.

**Comment by annezazu** [comment]
Thanks for the passionate report! I appreciate you following up and engaging. I'm going to close this out and consolidate in favor of this prior report with lots of feedback on the same topic: https://github.com/WordPress/gutenberg/issues/24584 It helps immensely to see the same issues come up again and again but, to keep the feedback streamlined, it helps us to default to one open issue on a topic. Thanks for understanding!

**Comment by trejder** [comment]
@annezazu Thank you for your feedback and taking care on this topic. We are waiting for #24584 four years. And the feature most wanted by so many hasn't been developed so far. I have already assumed (about a year ago) that it will never be developed. 

Maybe we can resolve this with using some plugin etc. Unfortunately, in this case (four years) waiting for the core dev team has become completely pointless. Sad, but true. Thank you.

**Comment by annezazu** [comment]
I totally hear you. There are some aspects that take so long to get done and some things that happen quickly (check out each [Gutenberg release](https://github.com/WordPress/gutenberg/releases)). Either way, consider your feedback connected to the prior issue on this topic and know it's noted. There is a reason this current system was put in place though. For example, there have been repeat efforts, including this recent one https://github.com/WordPress/gutenberg/pull/64644, where plugins can extend this more robust menu to offer different ways of previewing how content will show up. 

In the meantime, one interim item I'm looking at is surfacing a preview option in the publish panel at an ideal time: https://github.com/WordPress/gutenberg/issues/64659 There's also a new "zoom out" option (experimental for now) in the preview panel https://github.com/WordPress/gutenberg/issues/63861 which might create a need in the future to re-imagine a bit how this current experience works.
