### ISSUE TITLE
Site Editor Pages: If the Posts Page is set, load the appropriate template, not the empty page.

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52114]
Currently: opening the Posts Page via the Pages panel in the Site Editor loads the data from that page into the details panel:

<img width="360" alt="Screenshot 2023-06-29 at 12 20 07" src="https://github.com/WordPress/gutenberg/assets/846565/c2739ed9-d81c-41e6-8f2c-db12d7fee08e">

It's not very practical because this 'page' always resolves to display a specific template (Home or Index), and that template doesn't actually display any page data. It also breaks the word count / time to read data points (https://github.com/WordPress/gutenberg/issues/51260). 

Clicking to edit this page takes you to an awkward state where nothing on the canvas can be edited until you engage template editing.

We can resolve this by updating the Posts Page menu item to link directly to the relevant template.

<img width="806" alt="Screenshot 2023-06-29 at 12 25 13" src="https://github.com/WordPress/gutenberg/assets/846565/44432aaf-4079-45e1-8ff4-7ac1dc8e2b33">

**Comment by ndiego** [comment]
@jameskoster do you think this could be considered a bug, i.e. something we need to get fixed for 6.3?

**Comment by jameskoster** [comment]
Ideally, yes.

**Comment by ramonjd** [comment]
I can look at this

**Comment by ramonjd** [comment]
Hopefully have something working over here:

- https://github.com/WordPress/gutenberg/pull/52266
