### ISSUE TITLE
Pattern Library: it's unclear at first glance what can be edited or not

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#52119]
## What problem does this address?

In the Site Editor -> Library, there are editable (template parts) and non-editable items (default patterns provided by themes). This is not very clear at first glance, as the main difference are the icons next to the item name and the cursor changing when hovering the canvas; the text above the pattern/template part in the canvas is not that understandable.

https://github.com/WordPress/gutenberg/assets/27339341/77fc0d96-20d9-401f-994d-318e47ad8b45

## What is your proposed solution?

Maybe showing a lock next to non-editable items or a pencil next to editable ones could help, or adjusting the copy on the canvas.

**Comment by richtabor** [comment]
There is https://github.com/WordPress/gutenberg/pull/51990 but I’m not entirely sure it’s the right direction. Probably fine for now, but not ideal.

**Comment by priethor** [comment]
Thanks, @richtabor; I missed Joen's comment. Closing as a duplicate of #51990
