### ISSUE TITLE
Site Editor: snackbars remain after context switching and become irrelevant

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#52121]
### Description

When navigating through the Site Editor, snackbars can remain between contexts and become irrelevant, with the call to action not doing anything in the new context.

### Step-by-step reproduction instructions

1. Go to the Site Editor
2. Try to edit a page
3. Click on the header or footer to get a snackbar that says, "Edit your template to edit this block."
4. Within the Site Editor, go to edit a template part or template through the left sidebar or the Command Palette.
5. The same snackbar reappears, is no longer relevant, and clicking the call to action doesn't do anything.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/27339341/cb152134-f1e2-4604-9674-d48be1523a90

### Environment info

- WordPress 6.3 Beta 2, browser-independent.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Related (and possible duplicate): https://github.com/WordPress/gutenberg/issues/50624

**Comment by priethor** [comment]
Thanks, @annezazu; let's consolidate there!
