### ISSUE TITLE
Details View → Template Part: display patterns as replacement options

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52124]
Extracted from https://github.com/WordPress/gutenberg/issues/50392.

When viewing a template part in the site editor, we can enable rapid design alterations by allowing the user to select from a range of semantically related pattern thumbnails. A rough mockup:

<img src="https://user-images.githubusercontent.com/846565/249753688-57a66235-3eab-422c-aada-31b1a2a77430.png">

Clicking a thumbnail would replace all the blocks in the template part currently, with the selected pattern.

**Comment by youknowriad** [comment]
This has been implemented in the template part document inspector and the details panel is gone.
