### ISSUE TITLE
Command Palette: consider nudge to patterns when searching for reusable blocks

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#52137]
## What problem does this address?

With reusable blocks changing to sync patterns, I can imagine folks searching for reusable blocks while in the Site Editor, without awareness of the change. This is a great opportunity to onboard them to the new combined concept:

<img width="1448" alt="Screen Shot 2023-06-29 at 10 51 14 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/a4165784-d038-40cd-b677-83984f91e7a0">

## What is your proposed solution?

When searching for reusable blocks, either add a hint to search for patterns or show patterns outright to indicate the change.

**Comment by annezazu** [comment]
@WordPress/gutenberg-design for consideration

**Comment by richtabor** [comment]
Related: https://github.com/WordPress/gutenberg/issues/51742

**Comment by annezazu** [comment]
There doesn't seem to be time so going to move this out of the 6.3 board.

**Comment by annezazu** [comment]
Closing this out as this ship has sailed in many ways :D
