### ISSUE TITLE
Patterns: remove "apply globally" option from block settings

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#52139]
### Description

When creating a new pattern using 16.1 and syncing it, an option to "apply globally" popped up in the block settings. This doesn't make sense in this context and should be removed.

### Step-by-step reproduction instructions

1. Create a new pattern from three dot menu.
2. Ensure focus remains on the pattern (it should).
3. Open sidebar and notice under advanced an option to apply globally greyed out. 

### Screenshots, screen recording, code snippet

<img width="286" alt="Screen Shot 2023-06-29 at 11 15 29 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/6ddd035b-d656-4a78-badc-7dce4e1c303b">

### Environment info

- WP 6.2.2
- GB 16.1
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
Related: Template parts should also have this omitted. 

Could we use the same logic that omits copy and paste styes from the block toolbar options re https://github.com/WordPress/gutenberg/pull/51503? cc @pbking 

<img width="280" alt="CleanShot 2023-06-29 at 14 50 24" src="https://github.com/WordPress/gutenberg/assets/1813435/73050598-f4b2-45f5-8fae-2404cf309169">
