### ISSUE TITLE
Command Palette: Remove suggestion for deleting templates/parts

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#52143]
While there's not other suggested commands, let's remove the suggested commands for deleting/resetting templates and template parts. They should still be discoverable via searching for the command - but not suggested first thing. 

<img width="571" alt="CleanShot 2023-06-29 at 15 13 00" src="https://github.com/WordPress/gutenberg/assets/1813435/500fc6a6-7fda-4989-a042-da0012d54b8f">
<img width="658" alt="CleanShot 2023-06-29 at 15 10 42" src="https://github.com/WordPress/gutenberg/assets/1813435/cebe7f9c-e534-4bd9-b91b-3027c6aac81a">

**Comment by mtias** [comment]
Agreed!
