### ISSUE TITLE
Command Palette: Site editor-related commands appear in non-block themes

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#52154]
### Description

For non-block themes, the Site Editor is not accessible, but the command palette allows site editor-related commands to be executed. As a result, if you execute a command, you will receive a message indicating that access is not allowed.

Ideally, I think these commands should be disabled for non-block themes.

### Step-by-step reproduction instructions

1.  Go to Appearance > Themes and activate non block theme (i.e Twenty Twenty)
2. Add new post
3. Open  "Command Center" using keyboard short cut. Windows: Ctrl + k / Mac: ⌘ + K
4. Type "Templates" and click on "Open Templates" link. You will be redirected to WordPress page. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/5b7c1a1e-626a-49ea-a7c2-fa1b642a8438

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by firoz2456** [comment]
I can replicate this with WordPress 6.3-beta4.
