### ISSUE TITLE
Footnotes block not removing formatting after block is deleted from the editor

### ISSUE THREAD

**Issue by widoz** [WordPress/gutenberg#52176]
### Description

Adding one or more footnotes in a page content the `fn` links format are not removed from the text if the footnotes block is deleted from the editor.

As additional note I see a strange behavior when I add a new note before an existing one, the block does not seems to reorder the internal list correctly.

### For the block removing issue

1. Create a new post or page and introduce a paragraph
2. Select a portion of the paragraph and add a footnote
3. Delete the Footnotes block

*Result* 
1. The `fn` elements are not removed from the paragraph
2. The Front-end is not rendering the `fn`
3. The Front-end is rendering asterisk 

### For the incorrect internal block list

1. Create a new post or page and introduce a paragraph
4. Select a portion of the paragraph and add a footnote
7. Select another portion of the paragraph which exists before the already added footnote

*Result*
1. The `fn` order looks correct but the block list order is incorrect and missing the new item

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1917784/a82c6d47-bab9-4d83-8b51-d755786dacab

And here how's look like on FrontOffice when the Footnotes block is not available.

![image](https://github.com/WordPress/gutenberg/assets/1917784/b67f6ea3-4c90-4bc2-a906-19af5ac38db3)

### Environment info

- Gutenberg `trunk` up to date to `dec307cff1` commit
- Wordpress 6.3-beta2-56116
- TwentyTwentyThree Theme (it's part of the wp-env)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by karmatosed** [comment]
I also see this as an issue; tested in Chrome using 16.1 (latest).

**Comment by mcsf** [comment]
Until we add more complex configurations for Footnotes, such as the possibility of rendering them in the margins of the document, I believe that #52506 is an adequate solution to this problem. I'd like to merge that fix as soon as possible (regardless of whether it should close this issue).
