### ISSUE TITLE
Preview frame animation should only trigger when hovering the frame

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52175]
If you resize the frame so it is smaller than the default size, the 'zoom' animation occurs when you hover the container, rather than the frame itself:

https://github.com/WordPress/gutenberg/assets/846565/30a8cca7-4f0b-4399-b032-f5c2689a1e89

**Comment by annezazu** [comment]
Can no longer replicate this with 6.6.1 and the latest in GB (Version 18.8.0):

https://github.com/user-attachments/assets/3492b7fb-a905-4a64-b4d0-7b006aa72437

Closing out but happy to reopen if anyone else can replicate!
