### ISSUE TITLE
Site Editor: Update preview frame dynamically when settings change

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52182]
If you browse to a header/footer template part in the site editor and re-order menu items the preview updates dynamically:

https://github.com/WordPress/gutenberg/assets/846565/edf3df53-327a-403f-afed-839fd34bc942

It would be nice to apply this treatment to other configurable items that appear in the details panel. One example is the "Posts per page" setting in the Home / Index template details panel. Currently the preview is only updated when you save changes:

https://github.com/WordPress/gutenberg/assets/846565/d127398d-40c5-499a-a804-3712962717d4

cc @ntsekouras

**Comment by jameskoster** [comment]
Just to note: this is somewhat related to https://github.com/WordPress/gutenberg/issues/50392, where the intention is to include inputs for things like the Site Title in the template part details panel when appropriate:

<img width="244" alt="Screenshot 2023-06-30 at 15 50 01" src="https://github.com/WordPress/gutenberg/assets/846565/331290b2-ae7b-417d-9b02-1587f6a3b45a">

So the solution to the "posts per page" issue will have similar applications elsewhere.

**Comment by youknowriad** [comment]
This seems to work in my testing (the post per page moved to the document inspector though)
