### ISSUE TITLE
Image Block: Add lightbox support for image aspect ratio

### ISSUE THREAD

**Issue by artemiomorales** [WordPress/gutenberg#52192]
## What problem does this address?

The lightbox zoom animation is not compatible with the new image aspect ratio controls. We should add that support.

## What is your proposed solution?

For now, we should disable the lightbox when an aspect ratio other than the original is defined in the image block settings, but we should also work on adding support.

**Comment by artemiomorales** [comment]
Regarding the behavior when the lightbox is opened, I think maintaining the aspect ratio specified in the image block settings makes sense.

**Comment by SantosGuillamot** [comment]
I was testing how maintaining the aspect ratio could look like. There are a couple of things to fix but I believe we could get something like this working:


https://github.com/WordPress/gutenberg/assets/34552881/a65ae839-4f5b-43c6-b10a-7562cd398419

If we agree on this approach, I can take care of submitting a PR with the code.

**Comment by cbravobernal** [comment]
That seems a good approach, better than disabling it.

have you tried in mobile devices?

**Comment by SantosGuillamot** [comment]
> have you tried in mobile devices?

I tested it in the mobile view and it seems to be working. I didn't test it in a real mobile environment.


https://github.com/WordPress/gutenberg/assets/34552881/4ada3cda-4302-45a6-a39d-9476c4034b5c

**Comment by richtabor** [comment]
Noting that this was resolved in #52292 and works well: 

https://github.com/WordPress/gutenberg/assets/1813435/86fd1bb7-6400-4b3e-8b91-db85ecf8d168
