### ISSUE TITLE
Renaming Reusable Blocks Should Still Be Discoverable

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/gutenberg#52194]
### Description

As a user familiar with Reusable Blocks, I expect to find them as a search result when inserting a block even if that feature has moved. Assume I do not know that the feature as moved. 

How do I navigate to see all reuseable blocks I previously created? How do I get to the manage reusable blocks counterpart? 

### Step-by-step reproduction instructions

In 6.2.2:

- Create a Reusable Block 
- Insert it from the Block Inserter searching for "reusable" and/or the reusable block tab
- Insert it using the / command in a paragraph block searching for "reusable"

In 6.3b2 
Attempt the same

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5519705/d3c911bd-5d7f-4bd0-8f6f-1a181e39ea43

https://github.com/WordPress/gutenberg/assets/5519705/2fcd3c40-94aa-4b09-a812-084445ada912

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Probably related issues: #51944, #52150.

cc @aaronrobertshaw

**Comment by ndiego** [comment]
I just added this to the 6.3 project board as a Todo.

**Comment by courtneyr-dev** [comment]
This is partially resolved in beta 3.   Let's continue to check on the `/` command insertion method. 


<img width="403" alt="image" src="https://github.com/WordPress/gutenberg/assets/5519705/5788600b-b135-4d64-9437-27ae88456539">

![image](https://github.com/WordPress/gutenberg/assets/5519705/84e87967-1b2e-4b93-964a-461a8179569b)


<img width="367" alt="image" src="https://github.com/WordPress/gutenberg/assets/5519705/12d44854-c12d-43bb-954a-40043fc54be5">

**Comment by ndiego** [comment]
> Let's continue to check on the / command insertion method.

It would be good to keep the 6.2 functionality until perhaps 6.4. This will let folks migrate to the new "patterns" paradigm more gracefully.

**Comment by courtneyr-dev** [comment]
Beta 4: I am so happy with the prompts for users to know it has been renamed. I still wonder if `/reusable` should work, as `/pattern` does. 
![image](https://github.com/WordPress/gutenberg/assets/5519705/9cf96768-5517-4985-af9b-9e42ad11488b)
![image](https://github.com/WordPress/gutenberg/assets/5519705/ad3e7729-85b3-42ff-9264-4306a6e99ae2)
![image](https://github.com/WordPress/gutenberg/assets/5519705/e31a5c8e-f41a-44d4-81b1-e86136b24452)
![image](https://github.com/WordPress/gutenberg/assets/5519705/d91ac144-bbaf-4ba0-a4e0-3c2f6e7e8143)
![image](https://github.com/WordPress/gutenberg/assets/5519705/522f0a00-b528-43e3-a8fd-bc8cbf2cafac)

**Comment by courtneyr-dev** [comment]
Thanks @noisysocks!

**Comment by annezazu** [comment]
After seeing this change in beta 4 for create pattern/reusable block, I wanted to chime in as, while I understand this helps in the creation flow, it isn't going to help reduce confusion when thinking about the entire experience. I worry it might add to it. For example, here's a screenshot of what I see on a current reusable block after switching from 6.2.2 to 6.3 beta 4:

![Screen Shot 2023-07-12 at 2 15 04 PM](https://github.com/WordPress/gutenberg/assets/26996883/fc1af400-c103-4878-ba8b-c33d4a4b319e)

I think consistency across the different flows, along with the built in nudges, will help immensely. **Are there other options to consider here that might work?** For example, I can see we have concerns about the accessibility of the menu as is but @alexstine [shares the following:](https://github.com/WordPress/gutenberg/pull/51771#issuecomment-1620793816)

>Another option might be to go with @talldan's suggestion above. Using aria-describedby or aria-description might work fine. Although I think aria-description still lacks browser support in some cases.

@richtabor @karmatosed for 6.3 in case you all have any thoughts here.

**Comment by richtabor** [comment]
`Create pattern/reusable block` isn't ideal. 

I wonder if it will help if the control renders "Create synced pattern" and the sync control is enabled by default. 

This is an existing reusable blocks control that folks who use reusable blocks will be looking for — and we're calling reusable blocks "synced patterns" now.

**Comment by glendaviesnz** [comment]
@richtabor, @annezazu, @courtneyr-dev what do you think of the idea of only showing `Create pattern/reusable block` until the user has seen and dismissed one of the rename prompts, once they have dismissed the prompt we assume "discovery phase over" and revert to `Create pattern` for the menu? That way they aren't stuck with that less than optimal menu for the whole of the 6.3 release.

**Comment by glendaviesnz** [comment]
> "Create synced pattern" and the sync control is enabled by default.

I think this would help as the default action is then the previous behaviour. @SaxonF what do you think about this?

**Comment by ndiego** [comment]
> "Create synced pattern" and the sync control is enabled by default.

Making the toggle enabled by default would make the experience more consistent for current reusable block users.

**Comment by glendaviesnz** [comment]
There is a [PR here](https://github.com/WordPress/gutenberg/pull/52664) that renames the menu when the prompt is dismissed and also makes synced the default - probably good to get ✅ and into RC1 if possible.

**Comment by courtneyr-dev** [comment]
RC1 tested and I can find using `/reusable` 💯 
<img width="383" alt="image" src="https://github.com/WordPress/gutenberg/assets/5519705/37dfb651-6c5f-46d6-9595-9d2d72ce9a59">

**Comment by glendaviesnz** [comment]
Closing this as I think the discoverability is covered off for reusable blocks. We still need to look at the discrepancy of unsynced patterns not displaying in the quick inserter, but this is covered on [this issue](https://github.com/WordPress/gutenberg/issues/51945#issuecomment-1642846068).
