### ISSUE TITLE
Heading: controls for heading type

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#522]
We should consider which controls are necessary for the heading block, and how those can work best. This is the current mockup design:

![heading](https://cloud.githubusercontent.com/assets/1204802/25477224/15f22bda-2b3d-11e7-90a9-03d5c03601c7.png)

In general it seems good form to _start out minimalist and opinionated_, and then add back features as we find them necessary. In that vein, here are some questions we should consider:

- Do we need formatting controls, or is it sufficient that bold, italic and others work via keyboard shortcuts?
- Do we need alignment controls, or is it similarly sufficient that keyboard shortcuts work?
- Is there a better design for picking heading size than H1-H6?
- If you just insert a heading block, which size is default? H2?

As we think about this, here are some older (but amazing) mockups by @shaunandrews that may be worth revisiting:

![55240ab0-fe5d-11e6-82a2-4472016bad5b](https://cloud.githubusercontent.com/assets/1204802/25477430/c54911c0-2b3d-11e7-8b34-119c678bbcf5.gif)

![a238c1e2-fe5d-11e6-9237-d2cada55430f](https://cloud.githubusercontent.com/assets/1204802/25477432/c754a696-2b3d-11e7-85a9-e4b46f4e1bb4.gif)

Here's a quick and dirty mockup of "bigger and smaller" buttons. The icons need more love, but the idea is there:

![heading](https://cloud.githubusercontent.com/assets/1204802/25477906/6ff13516-2b3f-11e7-9889-354670dd5320.png)

**Comment by rileybrook** [comment]
Some ideas on the individual questions above.

{1/2}
> - Do we need formatting controls, or is it sufficient that bold, italic and others work via keyboard shortcuts?
> - Do we need alignment controls, or is it similarly sufficient that keyboard shortcuts work?

As someone who uses keyboard shortcuts, I would be happy without formatting/alignment controls. That said, I think it's critical that formatting controls be kept in for users who are novice internet/technology users, usually don't know any keyboard shortcuts, and prefer simple controls they can point & click to use. 

{3}
> Is there a better design for picking heading size than H1-H6?

A recent [user test](https://make.wordpress.org/design/2017/04/27/user-testing-the-gutenberg-editor/#comment-25220) with a first-time Wordpress user showed me that _"H0, H1, H2..."_ might not be as intuitive as representing size changes as shown in @shaunandrews second example of _"Abc, Abc..."_. 

Also, see below for example from Github's own editor.

<img width="786" alt="screen shot 2017-05-02 at 3 58 59 pm" src="https://cloud.githubusercontent.com/assets/7691812/25641237/569175bc-2f50-11e7-9ac9-9df6c8748bc5.png">

{4}
> Here's a quick and dirty mockup of "bigger and smaller" buttons.

Adding on here, I found users strongly correlated up/down arrows with changing the font size of a header/text. Clickable arrow buttons, such as the @jasmussen example of {^aA} would be a good experiment to test.

<img width="188" alt="screen shot 2017-05-02 at 4 01 52 pm" src="https://cloud.githubusercontent.com/assets/7691812/25641323/b5003eda-2f50-11e7-8f60-3617eef66ac2.png">

**Comment by afercia** [comment]
Ideally, the most important thing here is to convey hierarchy, not size changes. The size actually depends on the theme styling and might be completely different from what's represented in the headings control. Headings are meant to structure a document, it would be great to educate users to a correct usage. See also the discussions on
https://core.trac.wordpress.org/ticket/38049
and (very long ticket):
https://core.trac.wordpress.org/ticket/27159

**Comment by jasmussen** [comment]
Nice comments, Riley and afercia! 

It _sounds like_ to me that there is a middle way, where we embrace the changing up or down of sizes, but in a way that visually, perhaps textually, conveys hierarchy. Is there an idea here we haven't thought of? Could different icons and behaviors of the buttons help? What if aside from the increase/decrease size buttons was an indicator somewhere that showed the current hierarchy level? A number? What should that number be? Also keeping in mind you might insert an H2 by default, if you then scale that up to an H1, the "up" button would be disabled as it can't go larger.

**Comment by paaljoachim** [comment]
I apologize if I have not grasped the full discussion but I want to share some of my thoughts on this matter.

Having a way to visually signal that H1 is the biggest and H6 is the smallest will help the user understand the difference.

Vertically similar to how Riley shows it is something I have been thinking about as well, but... a dropdown will cover the content and I am not sure if that is a good idea.
Horizontally as Joen's mockup with the letters in different sizes seems like the best way.

![gutenberg-heading](https://cloud.githubusercontent.com/assets/5323259/25804917/db16dd70-33fd-11e7-9b18-2f2c4e92bfbd.jpg)

**Comment by jasmussen** [comment]
I like having the headings immediately accessible. But they do take up a lot of space. An alternative could be a dropdown like this:

![heading selected](https://cloud.githubusercontent.com/assets/1204802/26244794/b166bde6-3c91-11e7-89dd-ce0bac336786.png)

See also https://github.com/WordPress/gutenberg/issues/783#issuecomment-302671977 for the same pattern applied to "block styles".

**Comment by EphoxJames** [comment]
If you to show the structural meaning of a heading then you need to show it in context to the other headings already on the page and don't give them the option of selecting a h4 just because they want it to look smaller than the h2.

For example you could have a heading block that defaulted to the same size as the parent but had a drop down list that showed the heading in context of all the other headings above it in the heirachy, ie:
```
+-------------------+
| Heading Structure^|
+-----------------------------+
| Heading                     |
| > Sub-heading               |
| >  > ~Your heading~         |
| >  >  > Sub-sub-sub-heading |
```

**Comment by mrwweb** [comment]
I've been thinking a lot about this ticket and issue and have a new idea. I've experimented with the indented heading display that @EphoxJames suggests in my Simple TinyMCE plugin and have been happy with the results. I also think renaming the headings is probably a lost cause since it's just too hard when you get past H3 (see the second ticket @afercia links to).

I noticed that Slack's composed includes the heading levels in the block picker.

![Slack's block format selector: Paragraph, H1, H2, H3, Bulleted List, Numbered List, Checkmark?, Code](https://cloud.githubusercontent.com/assets/1238696/26361230/25c39e52-3f8f-11e7-8ee1-b672685edcca.png)

This makes sense because "Heading" isn't parallel to "Paragraph," "Heading 2" is. That suggests to me that "Heading" is a category of individual heading level block types and should be treated as such in the UI. (I think this is what ephoxjames implies with his ASCII mockup).

I think there have been some UI explorations of block format expanding menus, so those are probably work revisiting in light of this ticket. Some rough mockups to get move things forward and clarify the proposal:

Heading expandable section:
![Expandable heading menu section in collapsed state](https://cloud.githubusercontent.com/assets/1238696/26361341/8eb093c0-3f8f-11e7-97e4-4241a8c2a55c.png)

Heading selection:
![Heading menu expanded with indented heading level items](https://cloud.githubusercontent.com/assets/1238696/26361346/9425bc04-3f8f-11e7-88b3-6a3b7a3a7f60.png)

**Comment by jasmussen** [comment]
This is really interesting.

Showing them all as individual sizes in the switcher seems like a great way to show the hierarchy. The big problem here, is that there are 6 heading sizes. If we had only three, as Slack limits to, it would make things much easier, but that feels un-WordPress-like.

**Comment by mrwweb** [comment]
> Showing them all as individual sizes in the switcher seems like a great way to show the hierarchy. 

And indented with dashes!

> The big problem here, is that there are 6 heading sizes.

That is definitely a thorny issue. I'd start by splitting the question into two:

- Do we need Heading 1? ([Extensive discussion that ended in a "yes."](https://core.trac.wordpress.org/ticket/38049))
- Do we need Headings 5 and 6?

Headings 5 and 6 are probably the most likely for formatting abuse and are almost never needed. There is also at least some precedent for dropping buttons but maintaining the shortcuts (underline in 4.7). I always tell people that if they really need a Heading 5 or 6, their pages are too long. Providing access to all block and inline elements isn't a requirement for the editor, so I think Heading 5 and 6 should be considered for removal (while maintaining shortcuts).

**Comment by jwold** [comment]
Just curious. I realize that H1 - H6 is a longtime standard and a basic piece of html. However, in practice how often are all 6 used? I have rarely found the need for anything more than H1, H2, H3.

**Comment by mrwweb** [comment]
This [article and the linked studies](https://css-tricks.com/average-web-page-data-analyzing-8-million-websites/) may prove quite useful for many decisions that are coming up.

The relevant highlight for this thread:

![bar chart showing most common sectioning elements. H2 and H3 are most popular following H4 and H1. H5 and H6 are much less used](https://res.cloudinary.com/css-tricks/image/fetch/q_auto,f_auto/https://cdn.css-tricks.com/wp-content/uploads/2016/08/content.png)

There definitely appears to be a large cutoff between 3 and 4 and 4 and 5. I'd still vote to keep 4 and drop 5 and 6.

**Comment by jwold** [comment]
@mrwweb that would make sense if we were going to get rid of any to remove H5 and H6. Or at least make them hidden somehow?

**Comment by jasmussen** [comment]
This is one of those situations where it feels like a huge chunk of people, perhaps the majority, just uses the first three sizes, but that a bunch of other not insignificant chunks use the others. SEO concerns have been brought up, and I personally use only h2, h3 and h4 in my designs, relegating h1 to themes. 

This suggests a good design should accommodate both groups. But such a design has been discussed for a very long time, with some trac tickets (also linked here https://github.com/WordPress/gutenberg/issues/522#issuecomment-298834979) having tried to crack this nut for a long time. 

I like @mrwweb's dropdown idea (which inspired [this](https://github.com/WordPress/gutenberg/issues/522#issuecomment-302672133)) because it reduces the use of space, seems predictable to use, and doesn't actually hide any features. Last thing we want is people who otherwise like the visual editor, having to go into text mode to add an H6.

That's not to say I don't endorse efforts in suggesting headlines, and fewer of them. I think that's a noble goal. Just that it's a difficult design nut to crack.

**Comment by jwold** [comment]
Agreed. The design problem is the big issue here. I was playing around with Gutenberg this morning and trying to get a sense of the best way to approach it. No sudden inspiration so far :). Great discussions on the topic though!

**Comment by StaggerLeee** [comment]
H tags take much place. They are not used so often. Many developers chose to remove this option and give Users font-size, font colors, or whatever. To not mess with it and be punished by Google.

I like dropdown mockups.

**Comment by shaunandrews** [comment]
Another +1 for the dropdown solution. Seems the most robust and flexible as a whole pattern.

**Comment by afercia** [comment]
A11y note: a custom widget that emulates a dropdown can perfectly be built in an accessible way to emulate a native select. Thas would require some additional ARIA and scripting efforts though.

**Comment by jasmussen** [comment]
Master is working reasonably well currently, with a decent design. I think it might be worth looking at @paaljoachim's size <a href="https://github.com/WordPress/gutenberg/issues/522#issuecomment-299858311">hierarchy visuals</a> here, to help improve it further.

**Comment by mrwweb** [comment]
I would just like to echo @afercia's [previous comment](https://github.com/WordPress/gutenberg/issues/522#issuecomment-298834979) that matches my experience:

> Ideally, the most important thing here is to convey hierarchy, not size changes.

I'd actually say that size differences without any hierarchical indication leads editors to worse choices.

**Comment by jasmussen** [comment]
I'm going to close this for now as _sort of addressed_. Although the Heading block isn't perfect, it's much improved since this ticket.

If it feels unadressed still, we can reopen. But ideally we can also open new separate tickets for improvements to the block as it exists today.
