### ISSUE TITLE
Padding wrongly applied to Groups with Query Loops

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#52207]
### Description

~~The Query Loop Block shouldn't have a top margin - or it should have dimension controls.
It's not possible to create a layout where the featured image sits directly at the header.~~
<img width="1478" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/74544112-9e1e-4e5f-9071-700c8a681ae7">

~~I could wrap it in a group block and remove the margin.~~
 However, this leads to a padding issue on the right and left:
<img width="1780" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/dadc72e5-9e25-43ab-ae88-cf889678ab00">
So, maybe the real issue here is that featured images with full width do not correctly ignore padding?

~~I could now manually go through all blocks below or wrap them again groups and add a paddings, However, this feels tedious. I'd rather just remove the top margin for the query block.~~

### Step-by-step reproduction instructions

Wrap a query loop block in a group.
The featured image should set to full width.
Remove the padding of the top level group block. See recoding in the comment below.

### Environment info

- WP 6.2.2.
- GB 16.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hanneslsm** [comment]
Okay, the real problem seems to be that there is something off with the padding when grouping a query block.
I'm editing the issue so that it becomes regarding this topic

https://github.com/WordPress/gutenberg/assets/17861443/37431d6e-c908-493c-9ad3-7212355faff7

**Comment by lwangdu** [comment]
I wonder that  something to do your image. I don't have that issue with TT3. Can you try with different images?

**Comment by hanneslsm** [comment]
Thanks for looking into it. I have tried with another image, but please not it's a featured image block here. It's a custom theme.

**Comment by hanneslsm** [comment]
I managed to solve this. The issue was that for the top level group the "Inner blocks use content width" was set to true.
