### ISSUE TITLE
Global Styles: Appearance should only show available font-weights

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#52201]
### Description

When I am enqueuing a new font-family (e.g. via Create Block Theme), it the Appearance drop down should only let me select the available font weights.

### Step-by-step reproduction instructions

1. Add a new fonts, e.g. with Create Block Theme Plugin or just in the theme.js
2. Go to Global Styles → Typography → Text
3. The appearance drop down is full of options, even though I actually only can use some of the weights.

### Screenshots, screen recording, code snippet

<img width="143" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/821f8a35-4930-4c60-aa87-9009de84d13e">
<img width="2348" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/6f6fadb7-f433-44d8-9f9b-d5c610b5d265">
(interestingly, there seem to be another bug here - Barlow is a sans serif font)

### Environment info

- WP 6.2.2
- GB 16.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by cbirdsong** [comment]
This is a dupe, I think: 
- https://github.com/WordPress/gutenberg/issues/49090

**Comment by hanneslsm** [comment]
Yes, thanks. Closed.
