### ISSUE TITLE
Theme.json schema: Remove CSS from block style variations and elements

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#52217]
### Description

According to the schema, theme.json allows using "css" under `styles > blocks >block name > variations > variation name > css`, and `styles > elements > element > css.`

However, this is not implemented yet, the CSS is not applied in the editors or the front,
and I expect there to be a warning in my code editor if theme.json includes this feature.

### Step-by-step reproduction instructions

In theme.json, try to apply custom CSS to a block variation and element.
Note that there are no warnings, and that the styles are not applied in the editor and front.

Example:
```
	"styles": {
		"blocks": {
      "core/separator": {
				"css": "border:10px solid purple; max-width:100px",
				"variations": {
					"default": {
						"css": "border:10px solid blue"
					},
					"wide": {
						"css": "border:10px solid red"
					}
				}
			},
			"core/button":{
				"variations": {
					"outline": {
						"css": "color:blue"
					}
				}
			}
		},
		"elements": {
			"button": {
				"css": "color:red"
			},
			"heading": {
				"css": "border:10px solid green"
			}
		}
	},
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I tested this again and it seems that the css works on both `elements` and `variations` in WP6.6.

The screenshot below shows that all of the CSS is applied when using the theme.json provided in this issue.

![image](https://github.com/user-attachments/assets/eddb2b1b-ad73-4e2f-b4d6-24bcbc1129ac)

Therefore, I would like to close this issue.
