### ISSUE TITLE
Site Editor: The sidebar menu title text is cut off below the descender

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#52218]
### Description

Maybe related to: #51651

The sidebar menu title text is cut off below the descender.

![heading-title](https://github.com/WordPress/gutenberg/assets/54422211/578224a6-376e-445c-8b35-ee32bc9ec338)

I would expect it to appear as follows

![heading-title-expected](https://github.com/WordPress/gutenberg/assets/54422211/5f7decf7-13f5-43c8-a266-83fa83c75053)

This problem seems to be solved by removing the `overflow:hidden` in this area.

https://github.com/WordPress/gutenberg/blob/9a6958e6a3e69ecda18b8deb4e1b3cec352e30a0/packages/edit-site/src/components/sidebar-navigation-screen/style.scss#L67

Perhaps it is an OS or browser issue, so we would appreciate it if you could test to see if you can reproduce this in other environments.

### Step-by-step reproduction instructions

N/A

### Environment info

- WordPress Version: WordPress 6.3-beta2-56120
- Gutenberg Version: Lates Trunk (16.1.0)
- OS: Windows 11
- Browser: Chrome 114.0.5735.199, Firefox 114.0.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by firoz2456** [comment]
@t-hamano 
I am not able to replicate it. 
WordPress Version: 6.3-beta3-56139
OS: macOS Ventura (M1 Pro)
Chrome Browser
![image](https://github.com/WordPress/gutenberg/assets/8054727/08f8d652-4832-4482-81ae-a1b491fd5ebd)

**Comment by ndiego** [comment]
I am not able to replicate either 🤔

**Comment by annezazu** [comment]
Let's close this out for now with two back to back unable to replicate. Can reopen if we can replicate.

**Comment by t-hamano** [comment]
I have come to believe that this problem occurs only on Windows OS. I have found that some of the media attached in other issues show similar problems. In both cases, the reporter's environment appears to be Windows.

#52307:

![52307](https://github.com/WordPress/gutenberg/assets/54422211/1d77613d-7747-49d9-a2b4-ccbe08bd0482)

#52309:


![52309](https://github.com/WordPress/gutenberg/assets/54422211/b2135eae-3761-434b-87f4-1fdae1a7d07c)

I don't think this is a blocker in WordPress 6.3, but let me reopen this for the continued feedback.

**Comment by ramonjd** [comment]
@t-hamano's suggestion seems to do the trick

I've added a PR here:

- https://github.com/WordPress/gutenberg/pull/54769
