### ISSUE TITLE
Patterns: empty unsynced patterns added in site editor do not appear in post editor inserter

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#52227]
### Description

If an unsynced pattern is added via the site editor library, but has no content, it does not appear in the post editor inserter.

### Step-by-step reproduction instructions

- Go to site editor library
- Use the + at top of left nav to add a new unsynced pattern but don't add any content
- Notice pattern appears in unsynced section of library listing as an `Empty pattern`
- Go to post editor and open left patterns inserter panel and notice that the newly added pattern does not appear under My patterns

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I'm no longer able to recreate this - the empty pattern _does_ appear in "My Patterns" both in the pattern library, and in the inserted.

<img width="655" alt="Screenshot 2024-01-13 at 9 27 06 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/2511d8e1-e568-4739-8b7f-c13a97f0003d">

**Comment by ramonjd** [comment]
Do we still need something like this?

- https://github.com/WordPress/gutenberg/pull/52548
