### ISSUE TITLE
Replace outdated size controls in core blocks

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#52223]
### Description

~~`ImageSizeControl` (`__experimentalImageSizeControl`) was marked as deprecated in [#51545](https://github.com/WordPress/gutenberg/pull/51545/files#diff-5a9a2234d89e4080e031dbc85aafab7b248af84799f65710ad15ca7ca03bd5f1R34-R38).~~

~~However, there are two core blocks that use this component:~~

- [x] ~~[Media & Text](https://github.com/WordPress/gutenberg/blob/9a6958e6a3e69ecda18b8deb4e1b3cec352e30a0/packages/block-library/src/media-text/edit.js#L19) #57540~~
- [ ] ~~[Latest Posts](https://github.com/WordPress/gutenberg/blob/9a6958e6a3e69ecda18b8deb4e1b3cec352e30a0/packages/block-library/src/latest-posts/edit.js#L26)~~

~~Just as this API in the image block was [replaced by another API](https://github.com/WordPress/gutenberg/pull/51545/files#diff-a14b61c874095649b236b78413e805b4541277b24eb71ce350a17d9f2b6396b1L21) in #51545, I think it needs to be replaced by another API in these two blocks as well.~~

This issue has had its tasks/objectives updated. See [this comment](https://github.com/WordPress/gutenberg/issues/52223#issuecomment-2274344104).

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mirka** [comment]
I've noticed that when you search for the string `25, 50, 75, 100`, there are also two other blocks that implement a custom version of this outdated control:

<img width="175" alt="Small width percentage picker" src="https://github.com/user-attachments/assets/07bfef18-7cb2-4db1-aba7-93401226f463">

- [ ] [Button block](https://github.com/WordPress/gutenberg/blob/ddadd1a95d18270908ac4a1fd8d6e354cfadf61c/packages/block-library/src/button/edit.js#L128) (related: #62247)
- [ ] [Search block](https://github.com/WordPress/gutenberg/blob/ddadd1a95d18270908ac4a1fd8d6e354cfadf61c/packages/block-library/src/search/edit.js#L453)

These should probably also be switched to `DimensionTool`, is that correct?

I'm going to go ahead and change the title of this issue so it reflects that `__experimentalImageSizeControl` is not currently deprecated anymore, and that there are other blocks to be switched over as well.

**Comment by t-hamano** [comment]
> I'm going to go ahead and change the title of this issue so it reflects that `__experimentalImageSizeControl` is not currently deprecated anymore, and that there are other blocks to be switched over as well.

Yes, thanks for the update!

> These should probably also be switched to `DimensionTool`, is that correct?

Since the only setting is the width, I don't think it needs to be switched to the `DimensionsPanel`. I think we can simply replace it with the recommended component.

Is the recommended component here the `ToggleGroupControl`? If so, I imagine it would look something like this:
![button-width](https://github.com/user-attachments/assets/db54b7cb-ba16-4f8b-be11-879aa228c03a)



I think the important bit is that we explicitly add an `Auto` ( or `None`) option so that we can reset the width.

**Comment by mirka** [comment]
I'm not against switching to ToggleGroupControl, since that's already better than what's in trunk. I was just thinking we might as well switch to a more standard UI pattern that also allows arbitrary values, for example as requested in #62247.

**Comment by t-hamano** [comment]
Perhaps we need a component that consists of the `ToggleGroupControl` and other input field UIs, like the `FontSizePicker` component?

In addition to `RangeControl` and `UnitControl`, we may also be able to use `SizeControl`, as proposed in #62866.

The Search block has both a field for entering an arbitrary width and the `ButtonGroup`, so we may be able to try applying the new component to this block first:

![image](https://github.com/user-attachments/assets/94f7b8d1-1c06-4653-93f7-e3ca58dd1155)

By the way, a design update has been proposed for `ToggleGroupControl`: #64439

**Comment by mirka** [comment]
In #65339 we will be working on an incremental update to swap out all the ButtonGroups to ToggleGroupControls. That probably won't fully address this issue, but at least it will fix the outdated styling and accessibility issues.

**Comment by t-hamano** [comment]
Thanks for letting me know. Perhaps once #65346 and  #65340 are merged, this issue can be closed?

**Comment by t-hamano** [comment]
All `ButtonGroup` components in the core blocks have been replaced with `ToggleGroupControl`, so I think this issue can be closed.
