### ISSUE TITLE
Site Editor: Incorrect headings hierarch in the 'Manage all' screens

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#52254]
### Description

Note: In the following screenshots, I'm using the HeadingsMap browser extension (available for Chrome and Firefox) to visually illustrate the headings in the page.

In  'Manage all templates',  'Manage all template parts', and possibly other 'manage all' screens, the headings hierarchy is incorrect and skips a few levels. A correct headings hierarchy is of fundamental importance for screen rearer users to efficiently navigate the content.

Edit: Please note there are also two H1 headings, which is incorrect.

I seem to recall the hierarchy was already fixed in a PR a while ago so I'm going to mark this issue as a regression.

On a side note: it would be great to re-focus all designers and developers attention to always check for a correct headings hierarchy. It's such a simple thing to implement but in the history of this project there have been several cases where new features have been shipped with a broken headings structure. @mtias I'd greatly appreciate any suggestions on the best way to train developers on this and make sure everybody is always focused on using headings correctly 🙏 
See also https://github.com/WordPress/gutenberg/issues/52253

This is basic semantics / accessibility / HTML. It would be great to just not use heading levels randomly.

ScreenshotL All templates:

<img width="1788" alt="Screenshot 2023-07-03 at 16 36 55" src="https://github.com/WordPress/gutenberg/assets/1682452/309e0924-6f9b-440b-809f-d3c42386f35d">

ScreenshotL All template parts:

<img width="1788" alt="Screenshot 2023-07-03 at 15 43 39" src="https://github.com/WordPress/gutenberg/assets/1682452/4416935c-e608-4256-bc16-19df9823a6a3">

### Step-by-step reproduction instructions

- Use the HeadingsMap browser extension.
- Go to the Site editor > Design > Templates > Manage all templates.
- Observe the headings hierarchy is incorrect.
- Go to the Site editor > Design > Patterns > Manage all template parts.
- Observe the headings hierarchy is incorrect.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Once more, adding to 6.3 and thank you for opening this! Can you confirm what version you are using when you have a chance?

**Comment by afercia** [comment]
Trunk :)

**Comment by ramonjd** [comment]
Would something like this be better?

<img width="1051" alt="Screenshot 2023-07-04 at 5 14 09 pm" src="https://github.com/WordPress/gutenberg/assets/6458278/28ea2483-cd94-447a-9892-92a2346ad528">
