### ISSUE TITLE
It's not obvious a reusable block is a reusable block

### ISSUE THREAD

**Issue by carlhancock** [WordPress/gutenberg#5225]
## Issue Overview
When dealing with content that has a mix of standard blocks and reusable blocks it is not immediately obvious if a block is a reusable block without editing the block and giving it focus.  

The current UI requires you to select each block individually to determine if it is a reusable block or not.  That will be time consuming as content will consist a myriad of blocks of varying types.

The editor UI should make it more obvious that a block is a reusable block.

## Current Behavior

I've put together a simple demonstration using only 2 blocks to outline the UI/UX issue.

<img width="1149" alt="reusable1" src="https://user-images.githubusercontent.com/3789861/36610459-56ac01ec-189e-11e8-83d2-221f6083abab.png">

Above is a page that shows 2 blocks.  One of them is a reusable block.  One is not.

<img width="679" alt="reusable6" src="https://user-images.githubusercontent.com/3789861/36611458-801a31fe-18a1-11e8-8d94-3875ec9b0177.png">

<img width="684" alt="reusable3" src="https://user-images.githubusercontent.com/3789861/36610501-7cdd48e4-189e-11e8-91e5-ee3f5cff6ff4.png">

Above is what you see when you hover over each of the blocks individually. You cannot distinguish a reusable block from a non reusable block.

<img width="676" alt="reusable5" src="https://user-images.githubusercontent.com/3789861/36610583-cad14938-189e-11e8-8c88-7adb6aed376d.png">

It is only when you select a specific block and that block has focus that you can determine it is a reusable block.  In this example both block types were the same but only the 2nd block on the page was a reusable block.

This was an extremely simple example.  In a real world situation the page will consist of numerous blocks of varying types.  Which means distinguishing reusable blocks from non-reusable blocks will be more of a pain for the user.

## Possible Solution

Incorporate a visual indicator that a block is a reusable block without requiring the user to edit the block to make that determination.

This could be something as simple as incorporating the reusable block icon in the block hover UI so that it appears in some fashion the way the up/down arrows and the overflow icon do when you hover over a block.

Clicking on the visual indicator could then not only give the block focus, but also put the reusable block in edit mode so it's ready for you to make changes.

**Comment by carlhancock** [comment]
So I threw together a very quick example.  But quickly ran into a UI issue that makes it look not so good.  

Here is a quick mockup of simply adding a visual indicator to the hover state of the block if the block is a reusable block:

![reusable1](https://user-images.githubusercontent.com/3789861/36618659-fe161326-18b9-11e8-8b19-7e46c45244f4.png)

The very first issue I see is it exposes the UI issue I mentioned above. The default hover state of a Gutenberg block only shows a partial outline around the block.  It only shows vertical lines on the left and right just tall enough for the up/down arrows and the overflow icons to sit next to those vertical lines.  

My personal opinion, and i'm not sure if others feel the same, is it makes it look like there is some sort of CSS issue... like the border state for the hover is supposed to be there but for some reason it is not displaying properly.  But I know that is not the case and it was done intentionally.

This is the opposite of behavior elsewhere in Gutenberg in a variety of places.

Here is an example of showing the same reusable block indicator on a block but shown when the block is selected and has focus:

![reusable2](https://user-images.githubusercontent.com/3789861/36618774-7333ca54-18ba-11e8-8fb0-02e3539d1c0b.png)

The selected state begins to look much better than the hover state.

The partial outline of a block on hover runs counter to other areas of Gutenberg where outlines are used.  They are always complete outlines.

For example when you hover over the title:

<img width="937" alt="reusable3" src="https://user-images.githubusercontent.com/3789861/36619027-50cc4256-18bb-11e8-91c6-eb67c87ccc21.png">

When you hover over the empty block inserter which has already been discussed in other tickets so no need to go into detail on the problems with it, but it is displayed with a full outline:

<img width="892" alt="reusable4" src="https://user-images.githubusercontent.com/3789861/36619083-831e157c-18bb-11e8-8695-63c0438d220f.png">

Although coincidentally when you click on said block inserter you don't get even a partial outline like the default block hover state, you get no outline at all:

<img width="860" alt="reusable5" src="https://user-images.githubusercontent.com/3789861/36619117-a0062e72-18bb-11e8-9da0-e18fc165c80d.png">

Other areas of the UI use outlines around elements as an indicator for the hover state.  Here are a couple more examples:

<img width="334" alt="reusable6" src="https://user-images.githubusercontent.com/3789861/36619136-b346566a-18bb-11e8-8ff5-f563bb74efd9.png">

<img width="816" alt="reusable7" src="https://user-images.githubusercontent.com/3789861/36619146-bd124b86-18bb-11e8-9eb9-a2ddd7e851d1.png">

That last one actually points out another UI issue altogether. Most UI elements in Gutenberg use a rectangular outline and feature plenty of padding/spacing so they appear more visually balanced. But the icons related to the blocks are using circular outlines and the visual padding/spacing is very cramped.

Hopefully someone can chime in on the design side.  I'm curious as to what the thinking is behind the current hover state behavior of blocks only showing a partial outline and why the up/down arrows and overflow icons use a circular outline and don't make use of padding/spacing to make them appear more visually balanced.

Ultimately i'd still like to see a way to visually indicate a block is a reusable block without having to click on the block to select it.  But these other UI issues have been bothering me and they begin to become related when I try to mockup suggestions for the original issue so I figured I would include them here.

**Comment by noisysocks** [comment]
Perhaps we should show the dashed outline at all times instead of just when the reusable block is selected.

cc. @jasmussen

**Comment by jasmussen** [comment]
Solid exploration, and good suggestions. Seems like it holds ingredients for improvement here.

Tagging as in need of some design feedback — it would be nice if we could find a solution that did not involve showing more side UI as that doesn't scale well to nested blocks, but definitely something that could use love.

**Comment by karmatosed** [comment]
Thanks for the exploration @carlhancock - really interesting insights.

> Perhaps we could show the dashed outline at all times instead of just when the reusable block is selected.

I like that idea over the icon. My only issue with the icon is it seems confusing 'what is it'.

What about these two options:

![reusable](https://user-images.githubusercontent.com/253067/37110129-f2c99bfe-2233-11e8-9cc9-5e5cd0a1b556.png)

**Comment by carlhancock** [comment]
@karmatosed @noisysocks How would you denote if it's a locked reusable/shared block that the user doesn't have the capabilities to edit? The first option would provide the space to do so.  

You could show the Edit button if the user has the role/capability to edit the reusable/shared block and if they do not have the capabilities a lock icon with a tooltip explaining why it's locked.

It would make it obvious on hover that it is a reusable/shared (sorry I haven't followed up if it has indeed been changed to shared) block AND if it is editable or not.

One thing to note.  By showing the full dashed outline around these blocks it makes the lack of a solid outlined around standard blocks even more apparent.  I mention this in my 2nd comment above.  The partial outline on hover looks unfinished or like there is a styling issue.  When there actually isn't.

**Comment by jasmussen** [comment]
The point that the dashed line may not be enough on its own is a good point. Could we explore overlaying a "reusable block" indicator as Carl has suggested? Putting it in the side-UI should probably be avoided if at all possible, as that UI is already somewhat difficult to optimize for mobile and is about to receive further refinement as we make it work better for nested elements. But an icon overlay seems like it might work?

**Comment by noisysocks** [comment]
Maybe a badge in the corner? (excuse my terrible Sketch skills)

![reusable block icon](https://user-images.githubusercontent.com/612155/37222328-7c6f9fcc-2381-11e8-842e-9c8e7de4911f.png)

**Comment by jasmussen** [comment]
Right, something in that vein, perhaps.

**Comment by carlhancock** [comment]
@noisysocks Don't sweat your Sketch skills, it got the idea across just fine. 

@jasmussen I like the overlay concept also and something in this vein would probably work well.

Keep in mind the updates committed in #4725 related to user permissions.  It would be good for the reusable block indicator to also reflect if the block is editable or not based on their role/capabilities.

Another thing related to #4725 (which has been merged so I didn't want to comment on the pull request) what does the reusable block UI look like when a user clicks on a reusable block to try and edit it but does not have the capabilities to do so?  Does it show some sort of lock icon in place of the edit button that is typically displayed?

**Comment by karmatosed** [comment]
I worked some options up, I think number 3 of these is a good balance, but putting them all up incase. I think we need to make it an obvious but not 'too obvious' mark, which is what I am balancing with.

![savedblocks](https://user-images.githubusercontent.com/253067/37244908-149e24d8-2488-11e8-9c26-2b2a89ffabc1.png)

**Comment by jasmussen** [comment]
Options 1 and 3 seem like good first steps to explore

2 is difficult as the side UI probably shouldn't be taller than a single paragraph as the minimum height of a block.

**Comment by karmatosed** [comment]
Cool, lets go with option 3 then @noisysocks, if that works?

**Comment by carlhancock** [comment]
@karmatosed @noisysocks The #3 option looks good in the example with the paragraph field but be sure to see how it would be applied to other block types like images, full width images, embed, etc. With a paragraph there are no problems but #1 may work better for scalability with block types, keeping in mind it needs to work good with custom blocks added by plugins, etc
