### ISSUE TITLE
Post Content link color should not be applied to placeholder component links

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#52258]
### Description

Links within the UI should remain styled by the UI. The expectation here is that links have the `--wp-admin-theme-color` applied to them. 

### Step-by-step reproduction instructions

1. Add an Embed block. 
2. See the link color of the theme (TwentyTwentyThree in my screenshot) applied to the links within the component. 

### Screenshots, screen recording, code snippet

<img width="1141" alt="CleanShot 2023-07-03 at 12 28 33" src="https://github.com/WordPress/gutenberg/assets/1813435/5f8958bc-4025-4acb-b7b6-83cbd8e935aa">

### Environment info

WP 6.2.2 
Gutenberg Trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ghorivipul97** [comment]
@richtabor  kindly request to assign this issues to me

**Comment by richtabor** [comment]
> @richtabor kindly request to assign this issues to me

Go for it. When you create a PR for this it should auto-assign I think. 🚀

**Comment by ndiego** [comment]
@ghorivipul97 just checking in on this one. Do you think you will be able to get a PR together by the end of the week? It would be good to get a fix in before Beta 4, which is next week. Thanks!

**Comment by ghorivipul97** [comment]
Yes, I will do it before weekend.

**Comment by ghorivipul97** [comment]
Hello @ndiego 
PR Request: https://github.com/WordPress/gutenberg/pull/52367

**Comment by ndiego** [comment]
@ghorivipul97 I added a comment on the PR.
