### ISSUE TITLE
[Block] Twitter - Twitter Feed embeds show no posts

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#52260]
### Description

Embedding a single twitter post still works in the Twitter Block, but embedding a feed, such as `https://twitter.com/wordpress` results in a "no posts" error that reads `Nothing to see here - yet. When they Tweet, their Tweets will show up here.`

### Step-by-step reproduction instructions

1. Open a new post
2. Add a Twitter Block
3. Embed a twitter feed like `https://twitter.com/wordpress`

### Screenshots, screen recording, code snippet

![Markup on 2023-07-03 at 12:34:50](https://github.com/WordPress/gutenberg/assets/27249804/79600b34-fb26-425c-b2ad-f3e8e483f7a2)

### Environment info

- WordPress version 6.2.2
- Gutenberg version 16.0.0 & 16.1.0 tested

---

I suspect this is taking place because of Twitter's latest limits on post views; see: https://twitter.com/elonmusk/status/1675187969420828672

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mtias** [comment]
Not much to do here as Twitter locks down the ability to share and read tweets while logged out.

**Comment by bph** [comment]
@cuemarie It's a big bummer for many publishers. However, it might just be a temporary: [Elon Musk claims Twitter login requirement just 'temporary'](https://mashable.com/article/elon-musk-twitter-login-requirement-temporary) (Source: Mashable) 

Would it be ok to close this issue for now?

**Comment by cuemarie** [comment]
@bph Thanks for sharing the update, and yep, I think it makes sense to close this since it's out of all our hands. Thanks!
