### ISSUE TITLE
Focus changes when using transform menu

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#52275]
### Description

In some situations it is possible for the focus to change when you use the transform option. This only seems to happen when 'top toolbar' mode is enabled.

### Step-by-step reproduction instructions

1. Enable top toolbar
2. Type 2 lines of text
3. Click on first line and press the transform button in the toolbar. Cancel
4. Click on second line and press the transform button. Note how the focus has shifted to the first line

### Screenshots, screen recording, code snippet

Note how the blue focus outline moves when the transform button is pressed a second time.

https://github.com/WordPress/gutenberg/assets/1277682/ccb13fa7-5aa8-4879-ae5f-921c14b1c7b0

### Environment info

- Gutenberg 16.1.0 (also happens on https://wordpress.org/gutenberg)
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I can reproduce the issue. My guess is that it happens due to a stale `blockClientId` value inside the `useShowMoversGestures` callback.

https://github.com/WordPress/gutenberg/blob/ea6b5a12aa7424c2cd9c10e4a4476d9dad10295d/packages/block-editor/src/components/block-toolbar/index.js#L87-L97
