### ISSUE TITLE
Block API: Normalize function arguments

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#5227]
We have several functions that take arguments like `blockType`, `attributes`, `innerHtml`, but the order is not always consistent.

Since this is an often repeated pattern, we should consolidate usage.

Examples:

`isValidBlock — innerHTML, blockType, attributes.`
`getBlockAttributes — blockType, innerHTML, attributes.`
`getAttributesFromDeprecatedVersion — blockType, innerHTML, attributes.`
`createBlock — name, attributes, innerBlocks.`
`getSaveContent — blockType, attributes.`

**Comment by aduth** [comment]
Maybe we could prefer to pass name instead of `blockType`, assuming that its more readily accessible, and that these functions have access to the registry?

Proposed:

```
isValidBlock( name, attributes, innerHTML )
getBlockAttributes( name, attributes, innerHTML )
getAttributesFromDeprecatedVersion( name, attributes, innerHTML )
createBlock( name, attributes, innerBlocks )
getSaveContent( name, attributes, innerBlocks )
```

**Comment by mtias** [comment]
This needs a quick proposal or closing.

**Comment by gziolo** [comment]
I will work on the proposal shared by @aduth.

**Comment by gziolo** [comment]
`getAttributesFromDeprecatedVersion` - I no longer see this method.

**Comment by gziolo** [comment]
> On the point of name vs. type as an argument; I'd actually be okay with allowing the convenience here of specifying one or the other, as long as it's supported consistently across all functions. Maybe we need an internal function to normalize?

We should address this before 5.0 lands. This won't be a breaking change but it should simplify using the following API methods at least:
* `getSaveContent`
* `getSaveElement`
