### ISSUE TITLE
failed to update post over issue in shortcode block

### ISSUE THREAD

**Issue by yochaiglik-epalle** [WordPress/gutenberg#52272]
### Description

i created a shortcode on my theme
added it to a page using shortcode block in gutenberg
it works fine
but when i changed the $tag of the add_shortcode() function from a litteral string (which was: 'epalle-forms') to a $form_tag variable holding a string ($form_tag = 'epalle-forms') and then tried to update the page in gutenberg, i got the error "Updating failed. The response is not a valid JSON response."
and the weird thing is that the shortcode **will** work in the frontend

### Step-by-step reproduction instructions

1. create shortcode in theme
2. add a $tag_name variable
3. in the add_shortcode() function add the $tag_name variable in the $tag parameter 
4. add shortcode block to a gutenberg page etc...
5. put the shortcode in its place in the block
6. try to update the page (with gutenberg update button)

### Screenshots, screen recording, code snippet

<img width="1752" alt="image" src="https://github.com/WordPress/gutenberg/assets/119490186/a14dee56-40d3-4101-80b4-33cd5e71f7b1">

### Environment info

wp version 6.2
gutenberg plugin not installed
theme storfront 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
@yochaiglik-epalle, do you see any errors or warnings in the `debug.log` file?

**Comment by yochaiglik-epalle** [comment]
yes, i think this is relevant:
<img width="2296" alt="image" src="https://github.com/WordPress/gutenberg/assets/119490186/f4bdb93a-e562-4ca8-82e9-4bf69b182f34">
(i can upload the text itself if needed)

also, errors in js console.log:
<img width="1190" alt="image" src="https://github.com/WordPress/gutenberg/assets/119490186/612b7c8d-8d9e-4d76-ba12-62619e6882df">
with stack trace:
`
api-fetch.min.js?ver=bc0029ca2c943aec5311:2     POST https://dev-epalle.local/wp-json/wp/v2/pages/160062?_locale=user 500
T @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
l @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
O @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
o @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
O.method.r @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
o @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
t @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
v @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ wc-blocks-middleware.js?ver=0f88b73823abe386acef4b1e2baa1147:1
(anonymous) @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
A @ api-fetch.min.js?ver=bc0029ca2c943aec5311:2
(anonymous) @ core-data.min.js?ver=fc0de6bb17aa25caf698:2
await in (anonymous) (async)
(anonymous) @ data.min.js?ver=90cebfec01d1a3f0368e:2
(anonymous) @ redux-routine.min.js?ver=d86e7e9f062d7582f76b:9
(anonymous) @ data.min.js?ver=90cebfec01d1a3f0368e:2
(anonymous) @ data.min.js?ver=90cebfec01d1a3f0368e:2
(anonymous) @ data.min.js?ver=90cebfec01d1a3f0368e:2
(anonymous) @ editor.min.js?ver=1fb5fcf129627da4939e:19
(anonymous) @ data.min.js?ver=90cebfec01d1a3f0368e:2
(anonymous) @ redux-routine.min.js?ver=d86e7e9f062d7582f76b:9
(anonymous) @ data.min.js?ver=90cebfec01d1a3f0368e:2
(anonymous) @ data.min.js?ver=90cebfec01d1a3f0368e:2
(anonymous) @ data.min.js?ver=90cebfec01d1a3f0368e:2
(anonymous) @ acf-input.min.js?ver=6.1.6:1
Promise.then (async)
e.savePost @ acf-input.min.js?ver=6.1.6:1
(anonymous) @ data.min.js?ver=90cebfec01d1a3f0368e:9
(anonymous) @ editor.min.js?ver=1fb5fcf129627da4939e:19
(anonymous) @ editor.min.js?ver=1fb5fcf129627da4939e:19
Xa @ react-dom.min.js?ver=18.2.0:10
B @ react-dom.min.js?ver=18.2.0:10
(anonymous) @ react-dom.min.js?ver=18.2.0:10
$e @ react-dom.min.js?ver=18.2.0:10
qe @ react-dom.min.js?ver=18.2.0:10
(anonymous) @ react-dom.min.js?ver=18.2.0:10
fl @ react-dom.min.js?ver=18.2.0:10
V @ react-dom.min.js?ver=18.2.0:10
Ze @ react-dom.min.js?ver=18.2.0:10
de @ react-dom.min.js?ver=18.2.0:10
ce @ react-dom.min.js?ver=18.2.0:10
`

**Comment by Mamaduka** [comment]
Thanks, @yochaiglik-epalle!

It looks like the change you mentioned in the issue produced a PHP error. This will fail the editor for saving or other similar operations.

Unfortunately, there's nothing WP can do about third-party code errors.

**Comment by yochaiglik-epalle** [comment]
oh yes i see it now in my code, good to know that bad code breaks gutenberg saves etc.
sorry for the bad issue, i hope its not to much trouble.
its my first issue opening so still lear how to do it properly :)

**Comment by Mamaduka** [comment]
No trouble at all!
