### ISSUE TITLE
Extending @wordpress/scripts webpack.config.js

### ISSUE THREAD

**Issue by khoipro** [WordPress/gutenberg#52288]
I'm trying to extend a `@wordpress/scripts` to handle more things, such like copy `src/vendor` to `build/vendor`.

The expected code when I try to get involve:

```js
const CopyWebpackPlugin = require( 'copy-webpack-plugin' );
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );
const path = require('path');

module.exports = {
	...defaultConfig,
	plugins: defaultConfig.plugins.push(new CopyWebpackPlugin( {
		patterns: [
			{
				from: path.resolve( __dirname, 'src/vendor' ),
				to: path.resolve( __dirname, 'build/vendor' ),
			},
		],
	} ))
};
```

However, the response when running `npm run start`:

```
> wp-scripts start src/frontend.js

[webpack-cli] TypeError: item.plugins.unshift is not a function
```

So I guess the way to extend this part is not clear on the document (https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/ - only seeing the way to extend `defaultConfig.module` (an object), and no more clear introduction about how to extend `defaultConfig.plugins`

Am I wrong or we need more things to clear how to add a plugin to `webpack.config.js`?

**Comment by swissspidy** [comment]
[`.push()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push) returns the array's new length, not the updated array.

You'll want something like `plugins: [ ...defaultConfig.plugins, new CopyWebpackPlugin(...) ]` instead.

Here's an example: https://github.com/swissspidy/preferred-languages/blob/4e58d00f9c2c23e7fb666b3964ec81f5dcd62c60/webpack.config.js

**Comment by Jankyz** [comment]
@swissspidy it works perfectly! 

```javascript
const path = require("path")
const defaultConfig = require("@wordpress/scripts/config/webpack.config")

const BUILD_DIR = "build/"
const BUILD_PATH = path.resolve(__dirname, BUILD_DIR)

module.exports = function (env = {}) {
  const ENV = env.NODE_ENV === "production" ? "production" : "development"
  console.log(`#### ${ENV} ####`)

  const getNewPreconfiguredPlugins = require("shared-configs/webpack-configs/plugins.webpack-config")
  let newPluginsAvailable = getNewPreconfiguredPlugins(ENV, BUILD_PATH)

  const config = {
    ...defaultConfig,
    plugins: [...defaultConfig.plugins, newPluginsAvailable.definePlugin],
  }

  return config
}
```

this is how I've adjusted webpack config for wp-scripts, and now it is working with my custom plugin settings

then I can pass `NODE_ENV` in package.json

```json
  "scripts": {
    "build": "wp-scripts build --webpack-src-dir=blocks --config=webpack.config.cjs",
    "build:production": "wp-scripts build --webpack-src-dir=blocks --config=webpack.config.cjs --env=NODE_ENV=production"
  },
