### ISSUE TITLE
Remove Color Randomizer from 6.3

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#52296]
In testing 6.3 beta 3, I noticed that the "randomize colors" was listed as an option in Styles. This is an experimental option for Gutenberg and, unless something changed, should not be in 6.3:

<img width="1279" alt="Screen Shot 2023-07-04 at 4 24 48 PM" src="https://github.com/WordPress/gutenberg/assets/26996883/eba28196-52c5-42d1-b8d7-585f3efed21b">

Furthermore, I can still see it listed as an unworkable button in GB 16.1.1 so something must have gone wrong here. Here are the related PRs for this feature in case it helps: https://github.com/WordPress/gutenberg/pull/40988 https://github.com/WordPress/gutenberg/pull/51539

Here's a video of the current experience:

https://github.com/WordPress/gutenberg/assets/26996883/d6ed0b85-7aae-4f83-93e9-26d7e96e38b2

cc @tellthemachines @ramonjd as Core Editor tech leads!

**Comment by ramonjd** [comment]
Just checking the branches. Here's what I'm seeing:

### Gutenberg wp/6.3
<img width="356" alt="Screenshot 2023-07-05 at 12 40 15 pm" src="https://github.com/WordPress/gutenberg/assets/6458278/78bd718c-15e3-4e1b-b767-c8d58d4f4653">


### Gutenberg trunk
<img width="303" alt="Screenshot 2023-07-05 at 12 40 58 pm" src="https://github.com/WordPress/gutenberg/assets/6458278/e225cbfd-97fe-4d72-8f54-70fce2873b26">


### Core trunk (6.3-beta3-56130-sr)
<img width="289" alt="Screenshot 2023-07-05 at 12 43 11 pm" src="https://github.com/WordPress/gutenberg/assets/6458278/50a63eb5-c925-45b4-94b0-d279818365d2">


Very curious... it appears it should only kick in when [window.__experimentalEnableColorRandomizer](https://github.com/WordPress/gutenberg/blob/095d64a7fd92c3d5fa26e836fc40cd8fe5dc77cd/packages/edit-site/src/components/global-styles/hooks.js#L50-L50) is set to `true`

window.__experimentalEnableColorRandomizer doesn't appear in the global context in Core trunk 🤔 

I'll have a dig around

**Comment by tellthemachines** [comment]
Looks like we need to add back the `randomizeThemeColors` check that was removed [here](https://github.com/WordPress/gutenberg/pull/51539/files)

**Comment by annezazu** [comment]
Amazing sleuthing. Thank you for the quick work!
