### ISSUE TITLE
Title Bar shifts when switching between saved and save

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#52295]
### Description

When using 6.3 beta 3, I found it really distracting that, if the save status changes, the title bar shifts unexpectedly. In my mind, there shouldn't be shifting and it distracts from the overall refinement of the experience.

### Step-by-step reproduction instructions

1. Open the Site Editor
2. Edit the home template
3. Open styles > typography > text
4. Change the font and then change it back to original font selection. Notice the title bar shifts.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/26996883/274dffda-b30a-421b-a95e-853f1fcf043c

### Environment info

- WP 6.3 Beta 3
- TT3
- No GB

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ghorivipul97** [comment]
Hello @annezazu 
I am start to work on it, Please assign me.

**Comment by annezazu** [comment]
All yours! Thanks for taking this on and let me know if you need any help moving this work forward.

**Comment by t-hamano** [comment]
As mentioned in [this comment](https://github.com/WordPress/gutenberg/pull/57462#issuecomment-1872528584), the behavior will be more noticeable depending on the site language. This is because the button width changes depending on the site language.

**Comment by annezazu** [comment]
After a review by core editor triage and core editor tech leads on the WordPress 6.5 release team, [this issue is being removed from the release due to lack of progress ahead of beta 1. ](https://wordpress.slack.com/archives/C02QB2JS7/p1707153082189369?thread_ts=1707153067.570549&cid=C02QB2JS7)

**Comment by t-hamano** [comment]
I believe this issue was resolved in #59134.

https://github.com/WordPress/gutenberg/assets/54422211/41697357-23a4-44d3-8d1c-a820e8c2cf61
