### ISSUE TITLE
Site View > Navigation: renaming menu saves all menu changes

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#52294]
### Description

While testing 6.3 Beta 3, I noticed that when using the Site View > Navigation section, if I rename the menu, all menu changes are saved, even if I didn't confirm that change. 

### Step-by-step reproduction instructions

1. Open the Site Editor
2. Head to Navigation
3. Make changes to the menu, like rearranging items or deleting.
4. Using the three dot menu, rename the menu and notice that all of the changes are saved.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/26996883/ba4fd202-5d0d-4138-8ef7-ec6a9fc06104

### Environment info

- 6.3 Beta 3
- No GB
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
This is a great catch. Thank you Anne.

I've added `Navigation` labels here and I will take a look at it.
