### ISSUE TITLE
I love you gutenberg team

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#52305]
### Description

Is this an issue?
I want to say it.
Don't treat our relationship like an open issue.

### Step-by-step reproduction instructions

1. Look for other 5.000 issues in the repository.
2. Consider that none of them are sincere from the heart.
3. Go to your heart.
4. Return to my issue.
5. Consider it yours too.

### Environment info

- WordPress 6.9.
- All the browsers.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
This is lovely - but I'm going to close it 😂
