### ISSUE TITLE
Grammarly extension conflicts with title block when using emojis

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#5230]
## Issue Overview

Popular Grammarly.com extension conflicts with Gutenberg title block when using emojis

Doesn't look right with the extension on:

![image](https://user-images.githubusercontent.com/87168/36620191-8a7c5100-18fa-11e8-9527-dfd737b6d4f2.png)

If you disable the extension, all goes back to normal:

![image](https://user-images.githubusercontent.com/87168/36620264-df1bc880-18fa-11e8-8866-4aca666e2c1f.png)

## Steps to Reproduce (for bugs)
1. Create a new post
2. Insert emojis into title block (`ctrl`+`cmd`+`space` on MacOS or copy from here: 📚🤓💯⚡️)
3. 💥

#### Setup:
- Gutenberg 2.2.0
- Chrome  64 / MacOS
- [Grammarly for Chrome](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen) 14.827.1446

## Expected Behavior
Smooth ⛵️and no duplicate emojis. 👌

## Current Behavior
- Emojis are "shadowed" duplicate 👥
- Odd squares around Grammarly UI:
    ![image](https://user-images.githubusercontent.com/87168/36620310-1659aa10-18fb-11e8-8f64-9545825a07cd.png)

## Related Issues and/or PRs
https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+grammarly+is%3Aclosed

**Comment by paulwilde** [comment]
See https://github.com/WordPress/gutenberg/issues/1698#issuecomment-358819485.

**Comment by simison** [comment]
Aight! Thanks, @paulwilde. Closing this as well then.

Gist if I understood correctly: the fix has to come from Grammarly.

FYI @blacktaxi
