### ISSUE TITLE
When there are no synced patterns, the first pattern screen is empty and boring.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#52317]
## What problem does this address?

On a fresh WordPress installation where there are no synced pattern created, the first screen when you select
Appearance> Editor > Patterns is empty:

<img width="1499" alt="Empty pattern screen" src="https://github.com/WordPress/gutenberg/assets/7422055/056bbb99-fb79-4264-9f42-2e7c2b17055d">

## What is your proposed solution?

Can we use this area to "promote" pattern creation?
And maybe even link to documentation.

**Comment by 00travelgirl00** [comment]
Maybe a little welcome message with a button for "create a new pattern" in addition to your suggestions? 

Do you mean with "promote pattern creation" the pattern library?

**Comment by carolinan** [comment]
I meant the first, add a second "create new pattern" button.

**Comment by annezazu** [comment]
@WordPress/gutenberg-design to consider as part of the release cycle!

**Comment by jameskoster** [comment]
In lieu of a nicely designed empty state (which may not be feasible for 6.3 given the time we have), could a short-term solution be to select the first non-empty category?

**Comment by carolinan** [comment]
Yes

**Comment by ndiego** [comment]
Just checking in here since Beta 4 is tomorrow. Do we think we can reasonably get this done for 6.3? Or should we punt?

**Comment by richtabor** [comment]
I don't think we could come up with something measurably better that would make a big difference in this short time. 

But I'd appreciate if folks added ideas to this issue on how we could present an empty state that was insightful/an intro to patterns perhaps.

**Comment by jameskoster** [comment]
The current behavior feels pretty buggy imo. "No patterns found." is a bit contradictory when patterns clearly exist?

I don't know if there's time, but it'd be nice to either:

1. Skip to the first category that has patterns.
2. Include the "My patterns" category, active, with `0` count. This would at least contextualise the "No patterns found" message (which could be updated to say "You haven't created any patterns yet").

**Comment by annezazu** [comment]
There doesn't seem to be a clear decision here from design. Let's punt. Moving now.

**Comment by richtabor** [comment]
> Include the "My patterns" category, active, with 0 count. This would at least contextualise the "No patterns found" message (which could be updated to say "You haven't created any patterns yet").

I like this approach.
