### ISSUE TITLE
Patterns: Full width synced patterns inserted with constrained width

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#52312]
### Description

When inserting a synced pattern that was _created_ at full width (outer block set with 'Full' alignment) it remains constrained to the content width.

When it is converted back to regular blocks - the 'full' alignment is restored

### Step-by-step reproduction instructions

1. Create block (or series of blocks) where the outer most block has the alignment set to 'Full'.
2. Create a Synced pattern from the block/s
3. In a new page/post insert the synced block. It will insert as though it is constrained by the content area.
4. Convert the pattern to regular blocks. The pattern will return to the 'Full' alignment

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1842363/5f6b6710-4e9d-4a5d-a7c6-3a4603ffb8d5

### Environment info

- WordPress 6.3 beta2
- Gutenberg 16.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by firoz2456** [comment]
@jordesign 
Are you testing in WordPress 6.3 **beta2** OR WordPress 6.3 **beta3** ?

**Comment by ndiego** [comment]
This issue has actually always been an issue with reusable blocks (now called synced patterns). The original issue is https://github.com/WordPress/gutenberg/issues/8288, so I am going to close this one to keep the conversation over there. Thanks for reporting this @jordesign 🙏
