### ISSUE TITLE
Remove the ability to 'Select' a page in the site editor save modal

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52324]
If you've edited multiple pages in a single session, those pages are listed in the save modal. If you're viewing one of the edited pages in site view, then a "Select" button appears in the item row. Clicking this button selects the Post Content block, which feels buggy in Site View:

https://github.com/WordPress/gutenberg/assets/846565/2a5559f8-4088-4c16-bdfd-247f42a71baa

**Comment by Mamaduka** [comment]
While looking into this issue, I noticed a different bug with the "Select" feature. When you click select in the site editor, it correctly selects the block and closes the save panel. Then I cannot re-open it; clicking the "Save" button does nothing.

Commenting here for future reference. I'll try to fix both issues.

**Comment by Mamaduka** [comment]
Sorry, I got a little bit side-tracked here. The "select" behavior is buggy at the moment in the editors, and as @annezazu described it here, it could be confusing - #27898.

I'm wondering if we should remove this feature.

P.S. The save panel component is part of the `editor` package and is shared between editors. This prevents us from using `edit-site` or `edit-post` specific selectors to change rendered UI.


## Example bug

https://github.com/WordPress/gutenberg/assets/240569/a04997df-6bf8-4cee-84ca-5b6d940aa279

**Comment by jameskoster** [comment]
I don't think it's all that useful and wouldn't be opposed to removing. Especially as we need to revisit saving holistically given the new site view, where being able to select + edit wouldn't be possible anyway.

**Comment by annezazu** [comment]
+1 to removing it. I haven't had any feedback that it's been helpful when saving.
