### ISSUE TITLE
Playwright utils: move plugin-specific request utils to global-setup

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#52339]
## What problem does this address?

Right now the request utils in `e2e-test-utils-playwright` contain a lot of Gutenberg-specific logic that does not apply to other setups:

https://github.com/WordPress/gutenberg/blob/b380a603c23f266499e1bead2f90ac55874594b8/packages/e2e-test-utils-playwright/src/test.ts#L139-L149

Because of this I need to manually override the `requestUtils` fixture in my setup, because otherwise I get errors about things like the `gutenberg-test-plugin-disables-the-css-animations` plugin not existing.

In my case it's not desired to trash all posts because I need some test data before the tests run.

## What is your proposed solution?

Move the highlighted parts above to the global setup file, because that's really where this code belongs.

**Comment by swissspidy** [comment]
cc @kevin940726 @noisysocks @talldan who were involved in writing that code

**Comment by kevin940726** [comment]
Makes sense. I don't remember why I didn't do that in the first place 😅 . Maybe it's because `global-setup` only runs once but worker fixture runs before each test suite? Feel free to open PRs to explore this idea though! 🙇
