### ISSUE TITLE
WP 6.3-beta3: pattern export and import ignores sync type

### ISSUE THREAD

**Issue by bvlgn** [WordPress/gutenberg#52333]
### Description

If you export a synced pattern the sync type (`synced`/`unsynced`) is not stored in the json file.
So an imported `unsynced` pattern will always become a `synced` pattern after import and the user has no way to change that to `unsynced`.

### Step-by-step reproduction instructions

1. Go to /wp-admin/edit.php?post_type=wp_block
2. Export a synced pattern
3. Permanently delete the pattern you just exported
4. Import the pattern and notice it now is marked as fully synced and you cannot change that

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
Thanks for reporting @bvlgn
