### ISSUE TITLE
FIX: Improve language and options for when blocks are modified externally

### ISSUE THREAD

**Issue by mathetos** [WordPress/gutenberg#5233]
## Issue Overview
The current text that explains what options are available when a block is found to have been modified externally is very confusing. This is the text currently:

![image](https://user-images.githubusercontent.com/930724/36623370-e39eb31e-18b8-11e8-87cd-48afa50ce986.png)

> This block appears to have been modified externally. Overwrite the changes or Convert to Classic or Custom HTML to keep your changes.

This explanation does not make it obvious what will happen if you click on the "Overwrite" button. For example, clicking "Overwrite" suggests that the external modifications will be overwritten -- but that's not the case. Instead, the block markup itself is overwritten. The Gutenberg demo itself has done this with the cover image, the markup is changed so that the image can be loaded offsite. 

Additionally, it is not necessary to convert to Classic or HTML blocks in order to keep your changes, the existing block can be updated by clicking "Overwrite". 

Lastly, in the case of the cover image specifically, if you convert to Classic or HTML, you lose the ability to have the full-bleed effect that the cover image supports. So that should also be highlighted somehow.

## Possible Solution

I suggest this as an alternative. This change includes the following:

1. Adds the dynamic name of the block type that is in question.
2. Clarifies the actions that happen with each button.
3. Changes "Edit as HTML" to "Convert to HTML Block" for consistency

> This [BLOCK NAME] block appears to have been modified externally. To update this block with these modifications, click "Update." Alternatively, you can convert this block to either the Classic or HTML blocks. Converting to another block type might result in different block options.

Buttons: [[  Update ]]  [[ Convert to Classic Block  ]]  [[  Convert to HTML Block  ]]

**Comment by jasmussen** [comment]
Is this issue subsumed by #7604?

**Comment by mathetos** [comment]
@jasmussen Probably better to close this in favor of #7604 since this is so old at this point.

**Comment by jasmussen** [comment]
Thanks so much for your work!
