### ISSUE TITLE
WP 6.3-beta3: admin notice for successfull import of a pattern still mentions 'Reusable block'

### ISSUE THREAD

**Issue by bvlgn** [WordPress/gutenberg#52331]
### Description

When you import a pattern the admin notice shows: 'Reusable block imported successfully', instead it should say 'Synced pattern imported successfully'.

### Step-by-step reproduction instructions

1. Go to /wp-admin/edit.php?post_type=wp_block
2. Export e.g. a pattern
3. Import that pattern and look at the admin notice

### Screenshots, screen recording, code snippet

![noitce](https://github.com/WordPress/gutenberg/assets/13752843/2e462e4a-5b0c-4252-a9d0-af68bb2ef2ee)

### Environment info

WordPress: 6.3-beta3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
Thanks for reporting @bvlgn
