### ISSUE TITLE
Editing a page in the Site Editor: Content panel should only include canonical blocks

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52337]
If you edit a page in the Site Editor, the Inspector includes shortcuts to select blocks pertaining to page content, e.g. Title, Post Content, Post Featured Image:

<img width="1366" alt="Screenshot 2023-07-05 at 16 05 35" src="https://github.com/WordPress/gutenberg/assets/846565/f885459c-cf59-4b66-ae8e-38c0f596800d">

Currently there doesn't seem to be any logic around how to handle instances of these blocks that do not pertain to the selected page. For example, you will find duplicate blocks listed if:

1. The page itself contains a custom Query Loop
2. The template that displays the page contains a custom Query Loop

<img width="1365" alt="Screenshot 2023-07-05 at 16 05 00" src="https://github.com/WordPress/gutenberg/assets/846565/5f89b43e-df82-4375-9f69-2f039bc6ef0d">

This somewhat undermines the usefulness of the Content panel, and makes it feel a bit buggy. Ideally only the canonical versions of these blocks should be surfaced in this UI. 

cc @SaxonF @noisysocks

**Comment by SaxonF** [comment]
I was trying to work out how to reproduce this issue. Query loop makes a lot of sense. Thank you !

**Comment by noisysocks** [comment]
Aha 🙂 good catch.
