### ISSUE TITLE
Cannot Enable Dimensions / Spacing on Navigation Via Theme.json

### ISSUE THREAD

**Issue by ZafarKamal123** [WordPress/gutenberg#52341]
### Description

As per the documentation from the block theme handbook. I tried enabling the spacing specifically for "Navigation" (it's also not working for the navigation item blocks) block via theme.json. 

## Code

I'm adding the following code in the theme.json "settings" section inside the "blocks" settings.

```json
{
	"core/navigation": {
		"spacing": {
			"margin": true,
			"padding": true
		}
	},
	"core/navigation-link": {
		"spacing": {
			"margin": true,
			"padding": true
		}
	}
}
```

## Current Behaviour

Dimensions are not enabled on the "Navigation" and "Navigation Link" block.

<img width="1440" alt="Screenshot 2023-07-05 at 10 13 53 PM" src="https://github.com/WordPress/gutenberg/assets/48084051/e404fad8-ae90-4f13-bcb1-1ad94a3c8134">

## Expected Behaviour

Dimensions should be enabled like below:

<img width="1440" alt="Screenshot 2023-07-05 at 10 14 48 PM" src="https://github.com/WordPress/gutenberg/assets/48084051/7d00a639-e0ff-4fe7-a2f1-5b81d4e4f9a3">

---

Please let me know if this is something that's expected, Or if i may be doing something wrong.

Thanks

### Step-by-step reproduction instructions

1. Create a new theme with theme.json
2. Try enabling the spacing/dimensions on navigation block from theme.json.

### Environment info

- Gutenberg Version: 16.0.0
- WordPress Version: 6.2.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hi @ZafarKamal123 

I see you're trying to enable the UI for the other dimension settings - but they can only be added if the block itself is set up to support them

> Note, however, that not all settings are relevant for all blocks. The settings section provides an opt-in/opt-out mechanism for themes, but it’s the block’s responsibility to add support for the features that are relevant to it. For example, if a block doesn’t implement the dropCap feature, a theme can’t enable it for such a block through theme.json.
ref: https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/

What this means is that it won't be _possible_ to add those supports for the Navigation block at this time.
