### ISSUE TITLE
Time to Read block is not available

### ISSUE THREAD

**Issue by franzaurus** [WordPress/gutenberg#52359]
### Description

According to [the test page invitation for WP 6.3](https://make.wordpress.org/test/2023/06/27/help-test-wordpress-6-3/#blocks), a time to read block will be available in this version of WP. But I cannot find it among the block list nor fail to invoke it via the "/" command. Whereas the block is available in [GB 16.1 which is slated to be included in WP 6.3](https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/).

### Step-by-step reproduction instructions

1. Open a template or a page
2. Search for block name "time to read"
3. Observe there is no block with that name

### Screenshots, screen recording, code snippet

![no-time-to-read-block](https://github.com/WordPress/gutenberg/assets/79677758/2b4de6e1-ff73-46b2-81a7-4ab9c0f99eea)

### Environment via Instawp
- WordPress: 6.3-beta3
- PHP: 8.1.20
- Server: Apache/2.4.57 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
- Database: mysqli (Server: 10.6.14-MariaDB-1:10.6.14+maria~ubu2004 / Client: mysqlnd 8.1.20)
- Browser: Firefox 115.0 (Windows 10/11)
- Theme: Twenty Twenty-Three 1.1
- MU-Plugins: None activated
- Plugins:
  * WordPress Beta Tester 3.5.0
  * WordPress Importer 0.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Thanks @franzaurus  - AFAIK the decision was made to _not_ include the 'Time to Read' block in WP6.3 - it was just missed removing it from the call for testing.
