### ISSUE TITLE
Hi, I would like to start working with your project, serving as a translator to Spanish. could translate the document readme and contributing and any other wishing

### ISSUE THREAD

**Issue by UlisesTJ** [WordPress/gutenberg#5236]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ocean90** [comment]
Hello @UlisesTJ, you can translate the plugin at https://translate.wordpress.org/projects/wp-plugins/gutenberg.
