### ISSUE TITLE
Expanding template part detail panels

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52377]
The detail panels for template parts are a little sparse which makes them look a bit unintentional:

<img width="359" alt="Screenshot 2023-07-06 at 14 07 58" src="https://github.com/WordPress/gutenberg/assets/846565/f5fb5f2a-a89d-4b69-9508-f12579e465e7">

We can improve things by including available data points, for example the sync status from regular patterns, and template part area:

<img width="1560" alt="Template part" src="https://github.com/WordPress/gutenberg/assets/846565/82b366fb-1139-49b2-9f1a-8ba4a019510d">

**Comment by ndiego** [comment]
Just checking in here since Beta 4 is tomorrow. Do we think we can reasonably get this done for 6.3? Or should we punt?

**Comment by jameskoster** [comment]
Puntable I think 👍
