### ISSUE TITLE
Create Pattern Modal: Help text should vary depending on sync status

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#52385]
## What problem does this address?

When creating a pattern, the help text is as follows, regardless of the status of the synchronization:

```
Editing the pattern will update it anywhere it is used.
```

Since this text describes a synchronization pattern, it seems to create a contradiction to me when the Synced toggle is turned off:

![synced-help](https://github.com/WordPress/gutenberg/assets/54422211/c831a236-e692-4e9b-ba00-ec463095763a)

## What is your proposed solution?

It would be nice if this help text could change dynamically depending on the sync status.
For example, if the Synced toggle is off, I would expect to see the help text like this:

```
Editing a pattern does not affect patterns already inserted into the content.
```

![synced-help-proposal](https://github.com/WordPress/gutenberg/assets/54422211/c1851730-6eae-41a8-8291-5836bf92cbbb)

**Comment by annezazu** [comment]
In my mind, that text is meant to show what toggling this option on does, rather than reflecting the current status of things. It's essentially helper text. At the same time, I can see the benefit in having different text shown depending on the setting. Curious what @WordPress/gutenberg-design thinks. Tagging this for copy help as well.

**Comment by SaxonF** [comment]
> In my mind, that text is meant to show what toggling this option on does, rather than reflecting the current status of things.

Agreed, this is pretty standard behaviour e.g. see preferences modal in site editor

**Comment by t-hamano** [comment]
Thank you. I understand now 👍
