### ISSUE TITLE
Page editing under Site editor can't have full width align

### ISSUE THREAD

**Issue by wpsoul** [WordPress/gutenberg#52389]
### Description

When I edit any page under Pages - edit in regular workflow, I can select full width align. But When I do the same in Site editor new interface, I can use only inline width and full width align icon is not existed in toolbar

### Step-by-step reproduction instructions

1. Visit new interface for page editing in Site editor
2. Try to add any block with full width control, for example Cover block
3. Full width align is not available

### Screenshots, screen recording, code snippet

[https://monosnap.com/file/WTMep9ZRswpnlOjaQ7yW94z2XtUYLe](https://monosnap.com/file/WTMep9ZRswpnlOjaQ7yW94z2XtUYLe)

### Environment info

wordpress 6.3 beta 3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
If I'm following correctly, I can't replicate with beta 3:

https://github.com/WordPress/gutenberg/assets/26996883/67044a63-f7c0-4bc0-a325-b14108957537

What am I missing? Can you provide more information? Thanks so much for testing ✨

**Comment by wpsoul** [comment]
> If I'm following correctly, I can't replicate with beta 3:
> 
>  Screen.Recording.2023-07-06.at.11.57.14.AM.mov 
> 
> What am I missing? Can you provide more information? Thanks so much for testing ✨

Can you write me theme which you used? It can be related to Page template

**Comment by annezazu** [comment]
I am using Twenty Twenty Three!

**Comment by wpsoul** [comment]
I was able to fix by replacing

`<!-- wp:post-content {"layout":{"inherit":true}} /-->`

to 

`<!-- wp:post-content {"layout":{"type":"constrained"}} /-->`

which I copied from 2023 theme.

To be true, I don't understand why this option works differently in Site editor and in Page editing, but I can replace this manually in all templates
