### ISSUE TITLE
Issues with inline documentation in WP_Block_Type

### ISSUE THREAD

**Issue by Shelob9** [WordPress/gutenberg#5238]
`@access` is used for public methods. It should be omitted according to https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#1-functions-class-methods

`@returns` instead of `@return` here:
https://github.com/WordPress/gutenberg/blob/master/lib/class-wp-block-type.php#L123

PR Incoming

**Comment by aduth** [comment]
Closed by #5239

For future reference, you can include keywords in your pull request text to automatically close the relevant issue upon merger.

See: https://help.github.com/articles/closing-issues-using-keywords/

(Also generally good to cross-reference between related issues / pull requests)
