### ISSUE TITLE
Unable to create a pattern when editing an individual page in the Site Editor > Pages view

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#52393]
### Description

When trying to create a pattern while editing an individual page in the Site Editor, no option appears. I can only create a template part. 

### Step-by-step reproduction instructions

1. Open the Site Editor > Pages
2. Open an individual page.
3. Try to select a few blocks within the post content block and, using the three dot menu, try to create a pattern.
4. Notice no option exists.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/26996883/dbb431a1-95f0-42dd-8e80-f35b93dd0ec0

### Environment info

- WP 6.3 beta 3
- TT3
- No GB

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aaronrobertshaw** [comment]
Thanks for reporting this issue @annezazu 👍 

As reusable blocks have been renamed to patterns, this is the same issue as https://github.com/WordPress/gutenberg/issues/51310. Perhaps we can consolidate the two?

**Comment by annezazu** [comment]
Ah ha! I should have checked for that. Updated that issue to say pattern and closing this one out.
