### ISSUE TITLE
Add warning for post template removal

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#52390]
While testing 6.3 beta 3, I noticed I could still remove the post template block and didn't receive a warning. This seems like a bit of an oversight as part of this PR: https://github.com/WordPress/gutenberg/pull/51145 IMO we should have a warning for both, especially since if you remove the post template block, the experience is still broken:

https://github.com/WordPress/gutenberg/assets/26996883/29273f32-bc2e-4e66-958b-b56afdb5dae9

**Comment by annezazu** [comment]
@tellthemachines in case you can spin up a quick PR to do the same for post template after your earlier work!

**Comment by tellthemachines** [comment]
Hmm the implementation in Gutenberg has diverged from the one in #51145 which went into 6.3, so if we want to fix this for 6.3 we either need to include #51841 or we'll have to do a custom patch for it directly in the release branch, and then fix it separately in Gutenberg. Looking at #51841 I think it should be safe to include and will definitely make things easier to not have two divergent implementations 😅
