### ISSUE TITLE
The frame in Site Editor is sometimes not clickable - so we can't enter edit mode

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#52402]
>`100vh` seems to not be quite right. If you scroll the editor canvas down then you are able to get to a portion of the canvas where clicking on it doesn't open edit mode.Should it be `100%`? I'm not certain, this CSS confuses me. I'm not sure what `body`'s sizing is relative to 😅

_Originally posted by @noisysocks in https://github.com/WordPress/gutenberg/issues/51973#issuecomment-1624762154_

https://github.com/WordPress/gutenberg/assets/612155/13e15fa9-1cbb-40ac-a580-709025d18b8b

**Comment by draganescu** [comment]
It seems removing the min height of the html and the height of the body fixes things in FF at least.

**Comment by getdave** [comment]
When we fix this we need to be sure to retain the "full height" as [this is important for Navigation Focus Mode](https://github.com/WordPress/gutenberg/pull/51798).

**Comment by draganescu** [comment]
This bug was actually introduced by fixing the problem when content is smaller than viewport height (e.g. navigations). We need to apply the fix selectively somehow, as the normal template browsing does not need any fix.
