### ISSUE TITLE
Instagram block should be accepted Instagram URL only

### ISSUE THREAD

**Issue by usmaniqbalse** [WordPress/gutenberg#5241]
## Issue Overview
Instagram block should be accepted Instagram profile URLs only. 

## Steps to Reproduce (for bugs)
1. Just drop the Instagram block
2. Add any other URL except the Instagram profile URL
3. For more details, please see attached video

Gutenberg 2.2
WordPress 4.9.4
Chorome 64.0.3282.167

## Expected Behavior
Block should accept Instagram URL only

## Current Behavior
Block accepts every site URL containing media content 

## Screenshots / Video
![instagram - blcok input validation](https://user-images.githubusercontent.com/18400424/36639724-bfc443e6-1a34-11e8-897d-78fc1e69cb63.gif)

**Comment by karmatosed** [comment]
I think that's a reasonable check. If it is any specific service we should do a check.

**Comment by Kluny** [comment]
I'd like to work on this if no one else is.

**Comment by danielbachhuber** [comment]
Related #6824

**Comment by Dec0y-jb** [comment]
It looks like this actually affects all of the embed blocks, not just Instagram; I was able to replicate this with several others as well.

**Comment by notnownikki** [comment]
The current behaviour is that if you put, for example, a twitter URL into a YouTube block, the block will switch to a Twitter block.
