### ISSUE TITLE
[6.3 Beta 3] Confusing UX. The TT3 "Home" template is listed under pages inside the editor and clicking into it it's not indicating clearly that it's a template.

### ISSUE THREAD

**Issue by Ren2049** [WordPress/gutenberg#52416]
### Description

I've tried to illustrate the user experience from the perspective of an experienced WP user trying out the block editor for very basic tasks.

In summary, the home template shown in the editor in absence of a home page should at least be greyed out and indicate clearly that it's a template.

There should also be notice in the reading settings or prompt to create the actual home and blog pages if they don't already exist.

Also the template naming of the default TT3 theme (home template) **will** create a lot of anger among users when 6.3 is released. I suggest to modify the TT3 templates for a 6.3 release to avoid this confusion.

Below is a user flow and internal conversation hopefully showing why the current state of the ux is bad:

### Step-by-step reproduction instructions

After a fresh install and the deletion of the sample page in the dashboard:

![dashboard-pages](https://github.com/WordPress/gutenberg/assets/133038357/bee23022-9be0-48cb-b951-1ea972993f62)

User: Ok, lets try the new page functionality in the editor and add pages:

![editor-pages](https://github.com/WordPress/gutenberg/assets/133038357/bb7f2a2c-6d2e-4477-aff2-0a754c3980a7)

User: Where does the "home" page come from? I didn't create it. Ok it's showing the blog setting but I want a landing page instead. 

![pages-home](https://github.com/WordPress/gutenberg/assets/133038357/2044ae3d-1a99-480f-96a0-49b07d1ca676)

User: Why am I in the templates menu all of a sudden? Is it a template? If it is, then why was it displayed under pages?

User:  Ok, can't change it in the editor so let's try to change it in the reading settings:

![reading-settings](https://github.com/WordPress/gutenberg/assets/133038357/10210ad0-688f-4cbf-b1bd-a5638343b4f2)

User: The setting isn't there, maybe I remember it incorrectly and it wasn't under reading but somewhere else. Or was it moved to a different location? 

User: Ok so let's create a home and blog page and see if the options become visible. They do, so let's configure them so that home shows a static page and blog the posts:

![reading-settings-home-blog](https://github.com/WordPress/gutenberg/assets/133038357/901781c4-2349-4146-b51d-a8f769ae8cd6)

User: Let's check out the blog page in the editor:

![pages-blog](https://github.com/WordPress/gutenberg/assets/133038357/4a6d3eec-7c93-407c-8061-07b740c70a3b)

User: why does it use a home template? Didn't I just set it to posts?

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
I think these shortcuts have been removed. That said, dealing with home page is still a bit confusing. I think it's a hard problem that is being discussed here https://github.com/WordPress/gutenberg/discussions/64620
