### ISSUE TITLE
[6.3 Beta 3] Navigation items (e.g. pages) should be added to the right instead of the left. 

### ISSUE THREAD

**Issue by Ren2049** [WordPress/gutenberg#52418]
## What problem does this address?
Home Blog About is the common default core page navigation sequence on the web, but if you manually add pages starting with the home, blog and about pages you end up with the opposite (About, Blog, Home) needing manual reordering to fix, basically wasting users time. It's something that users will always do meaning that it should be done right by default. 

## What is your proposed solution?
Change the order of how items are added to the navigation.

**Comment by jordesign** [comment]
> Home Blog About is the common default core page navigation sequence on the web, but if you manually add pages starting with the home, blog and about pages you end up with the opposite (About, Blog, Home) needing manual reordering to fix, basically wasting users time. It's something that users will always do meaning that it should be done right by default.

Hi @Ren2049  - I'd expect the order in which items are added in a horizontal list to be dictated by the alignment and layout settings of the Navigation block.

In terms of recreating this for testing - are you you able to offer more details on how to do so?

**Comment by Ren2049** [comment]
@jordesign I agree with it being dictated by the layout settings of the navigation block, but maybe the navigation block could have different defaults using revrerse ordering to avoid having to reorder it everytime manually.

You can recreate it by adding a home page, a blog page and a about page in this order starting with the home page, and you will see that the resulting horizontal navigation menu order is the opposite of this starting with about.

Fixing the order to something reflecting design intent is basically an UX improvement that makes life a bit easier for users.

**Comment by jordesign** [comment]
Hey @Ren2049  I'm struggling to recreate this in 6.3beta3 with TwentyTwentyThree active. When I add items in that sequence (home, blog, about) to a navigation block I find the read left to right as expected.

Are you able to share a video of the issue as it happens? And more details of the theme you're using and the layout of the area where the navigation block is located?

**Comment by Ren2049** [comment]
Interesting. I tried to test it in a new empty theme created with the create block theme plugin but stumbled upon another issue doing so, where the navigation block still displays items for deleted pages (this still happens when I reactivate TT3):

![empty-pages](https://github.com/WordPress/gutenberg/assets/133038357/98817849-ce60-41d0-98f9-808c181ca5ea)

When I then add the pages back the navigation block stays empty:

![empty-navigation](https://github.com/WordPress/gutenberg/assets/133038357/a70e29d6-236c-44eb-88a9-eb5b31ec9a49)

I was expecting that pages are added to the navigation block automatically like before.

**Comment by jordesign** [comment]
Hey @Ren2049  - I missed this reply somehow I'm sorry.

> Interesting. I tried to test it in a new empty theme created with the create block theme plugin but stumbled upon another issue doing so, where the navigation block still displays items for deleted pages (this still happens when I reactivate TT3):

If that different issue is still happening if you check it now with 6.3 (or the 6.4 RC) could you please open a separate issue?

And do you still see the main issue in this thread occuring in 6.3?

**Comment by Ren2049** [comment]
I don't think it's a problem anymore in 6.4, I haven't encountered this issue there.
