### ISSUE TITLE
Template Part renaming modal doesn't not decode entities

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#52419]
Create a custom Template Part containing some HTML entity such as `David's Template Part` (note the apostophe).

Now go to the TP listing page and click `Rename`. See that the title shows the encoded title: `David&#8217;s Custom TP`.

Needs `decodeEntities`.
<img width="1249" alt="Screen Shot 2023-07-07 at 12 39 00" src="https://github.com/WordPress/gutenberg/assets/444434/8004b269-ab42-48d3-a3b1-6c956e9ed234">

This also happens on the listing page:

<img width="890" alt="Screen Shot 2023-07-07 at 12 45 06" src="https://github.com/WordPress/gutenberg/assets/444434/5f5b7ab6-2a85-48c0-a587-42dbc82997b9">

**Comment by t-hamano** [comment]
I have confirmed that this problem also occurs with custom template renaming modal.

![template](https://github.com/WordPress/gutenberg/assets/54422211/286f4b32-a304-4e40-bd19-04c150d0beee)

On the other hand, it does not occur with the navigation renaming modal.

![navigation](https://github.com/WordPress/gutenberg/assets/54422211/b0595c4f-2e82-41df-83fe-04e9e98f8453)
