### ISSUE TITLE
(Firefox) Caret mispositioned when backspacing into previous line

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#5243]
## Issue Overview
When editing text in a RichText block, the caret position is lost—seemingly randomly—as a line is merged into the previous one. So far, this only happens in Firefox (Quantum, 59.0, Dev Edition, macOS).

## Steps to Reproduce (for bugs)
1. Open the Gutenberg demo.
2. Find the first paragraph block.
3. Place the caret in the middle of the text.
4. Insert a line break by pressing `shift+enter`.
5. Place the caret somewhere in the new line.
6. Hit `backspace` until the line merges into the previous one.

## Expected Behavior
The lines should merge and the caret should be at the end of the line resulting from the merge.

## Current Behavior
The two lines merge, but the caret isn't at its expected position.

## Screenshots / Video
![gut](https://user-images.githubusercontent.com/150562/36641368-87dcf3c8-1a26-11e8-939c-5b56a83511b2.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jartes** [comment]
Using also Firefox (Quantum, 59.0b12 (64-bit) MacOS) it's happening the same with the Text Widget Editor doing the same steps mentioned in the issue:

![widgettext](https://user-images.githubusercontent.com/1046943/36641484-d7511802-1a27-11e8-9b33-67be2a16dc34.gif)

**Comment by mcsf** [comment]
Nice, @jartes! This confirms my hunch that it's a TinyMCE issue.

/cc @iseulde, just FYI. :)

**Comment by iseulde** [comment]
I cannot reproduce on Firefox Quantum, 58.0.2, macOS... Could it be an issue in the developer edition (is that a beta or something)? It's saying 58.0.2 = up-to-date.

**Comment by jartes** [comment]
Yep, it's the latest beta version: 

![captura de pantalla 2018-02-26 a las 12 37 54](https://user-images.githubusercontent.com/1046943/36668524-e1e0dc38-1af1-11e8-9c0b-5a34d947fcf7.png)

**Comment by mcsf** [comment]
@danielbachhuber, I can no longer repro with my following latest versions:
- Firefox Quantum 60.0
- Firefox Developer Edition 61.0b3

Can you confirm? If so, I'm inclined to close the issue.

**Comment by danielbachhuber** [comment]
I can no longer reproduce the issue in Firefox Quantum 59.0.2 against Gutenberg 2.8 or master:

![deleteinteractions](https://user-images.githubusercontent.com/36432/39931444-4878095a-54f2-11e8-8c2f-5b44c621473f.gif)

I suppose the next time something like this comes up with Firefox Quantum we should check to see if it reproduces in other web-based text editors.
