### ISSUE TITLE
Navigation block: importing additional classic menus greyed out after initial import

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#52434]
### Description

After importing an initial classic menu, I'm unable to import or create another with the options visible but greyed out.

### Step-by-step reproduction instructions

To make it faster, you can use  https://app.instawp.io/launch?t=beta-rc&d=v2 which has numerous classic menu options to import and where I initially ran into the bug.

1. Open Site Editor after ensuring you have a few classic menus to import (aka use a classic theme, create a few menus, switch to a block theme).
2. Edit a template.
3. Select the navigation block.
4. Open the block settings sidebar.
5. Try to import a classic menu.
6. Notice you can import one but, if you try to do so again, the options are greyed out.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/26996883/f7bbb36d-e43b-42ad-85dd-65c7f99b5d00

### Environment info

- WP 6.3 beta 3
- TT3
- No GB

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by draganescu** [comment]
I can reproduce this. It does not happen all the time. After importing saving and refreshing any classic menu can be imported. Will investigate.

**Comment by draganescu** [comment]
Seems to be a problem with a state named `isCreatingMenu`, the only one which could set those menu items disabled.
