### ISSUE TITLE
Add support for CSS Units Value 4 ('svh', 'lvh', 'dvh', 'svw', 'lvw', 'dvw', ...)

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#52441]
## What problem does this address?

Hey. I added this in theme.json:

```
"spacing": {
	"units": [
		"px",
		"%",
		"em",
		"rem",
		"vh",
		"vw",
		"dvh",
		"dvw",
		"vb",
		"vw"
	]
},
```

When editing a block, only these are available:

![SCREENSHOT-1](https://github.com/WordPress/gutenberg/assets/138938269/5bd20dab-486a-4451-8436-95c1c4eeed64)

As you can see, in this example, "dvh", "dvw", "vb" and "vw" are missing.

## What is your proposed solution?

I pleasantly ask you to: Recognize the missing CSS Relative Units.
List: https://www.w3.org/TR/css-values-4/#viewport-relative-units
More info: https://www.terluinwebdesign.nl/en/css/incoming-20-new-css-viewport-units-svh-lvh-dvh-svw-lvw-dvw/
More info: https://caniuse.com/viewport-unit-variants

Please consider a backport to WP 6.3.

**Comment by Ren2049** [comment]
This addition would be really important for designers, more context: https://css-tricks.com/the-large-small-and-dynamic-viewports/

**Comment by aristath** [comment]
PR is now available in https://github.com/WordPress/gutenberg/pull/54415
