### ISSUE TITLE
block.json metadata supports align default is true - but docs say it's false

### ISSUE THREAD

**Issue by RockyKev** [WordPress/gutenberg#52451]
### Description

In the guide: https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#align

This is my `block.json`

```
{
    "$schema": "https://schemas.wp.org/trunk/block.json",
    "apiVersion": 3,
    "name": "acf-block-json/button-group-with-text",
    "title": "ACF Block Json Choice: Button Group with Text",
    "category": "acf-block-json",
    "icon": "welcome-write-blog",
    "version": "1.0.0",
    "acf": {
        "mode": "preview",
        "renderTemplate": "template.php"
    }
}
```

**Expectation:** 
By default, it should have been false.

Workaround:
I have to explicitly declare it to false for it to disappear.
```
    "supports": {
        "align": false
    }
```

### Step-by-step reproduction instructions

1. make block.json
2. register it
3. Notice the align feature exists

### Screenshots, screen recording, code snippet

**Example:**
![](https://i.imgur.com/bli72QD.png)

### Environment info

Wordpress Version 6.2.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @RockyKev,

As far as I know, the align default should be `false`. For example, `align` is not defined in [block.json for the Custom HTML block](https://github.com/WordPress/gutenberg/blob/70215589cd2510a9881286d36aa48e41e19d06ac/packages/block-library/src/html/block.json#L16-L20). And the align control is not shown in the block toolbar either.

![custom-html](https://github.com/WordPress/gutenberg/assets/54422211/c575d060-67be-49b6-8161-2e9efc7ae0c8)

Also, looking at the code you attached, I would expect that you are using the Advanced Custom Field plugin, as there is a field named `"acf"`. [ACF Blocks registers blocks via block.json](https://www.advancedcustomfields.com/resources/acf-blocks-with-block-json/), but the default align value might have been changed at that time.

I recommend that you contact the plugin developer for further information.

**Comment by t-hamano** [comment]
Hi @RockyKev,

As far as the problem you reported, I believe it is not a problem with the WordPress core or the gutenberg plugin, but with the plugin you are using. 

I would like to close this issue, but if you have any questions, please feel free to comment.
