### ISSUE TITLE
Dragging a template part displays the wrong icon in the chip

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52461]
<img width="350" alt="Screenshot 2023-07-10 at 09 39 33" src="https://github.com/WordPress/gutenberg/assets/846565/9ea87b5d-2b53-4147-8646-916b9be429f4">

In the screenshot I am dragging the Footer, but the icon in the black chip is the one for general template parts.

**Comment by jameskoster** [comment]
The problem also exists when dragging a template part on the canvas.

**Comment by ritu-devlpr** [comment]
When I am following the same way I am not getting this issue Can you please explain more when you are getting this issue?
![image](https://github.com/WordPress/gutenberg/assets/118799789/92db2a9d-6e6a-4dcb-b5e3-b5a1e3ddb64c)
![image](https://github.com/WordPress/gutenberg/assets/118799789/e5b2516e-665c-46ae-a1ba-99258582d295)

**Comment by jameskoster** [comment]
@ritu-devlpr try dragging a _header or footer template part_ in the site editor. Notice the icon in list view does not match the chip that appears on-drag.

**Comment by ritu-devlpr** [comment]
Okay, I will try it.
