### ISSUE TITLE
Resizing issues in the Site Editor preview

### ISSUE THREAD

**Issue by simom** [WordPress/gutenberg#52464]
### Description
While editing a page in the Site Editor, if you modify the preview size using the "view" button in the top bar and then return to the Editor navigation, the iframe retains its resized state while the container does not. This results in an unusual behavior when attempting to resize it using the preview's left handle.

### Expected behavior
Would it be better to reset the preview to the desktop mode when the user exits from the editing mode?

### Step-by-step reproduction instructions

1. Open the Site editor
2. Click on a page to enable the editing mode
3. Change the preview mode to something differente from the desktop mode
4. Click on the top left corner WordPress logo to go back to the Editor navigation
5. Try to resize the preview with the left handle

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/492145/12355c56-e4a7-4665-8565-c528b45bb82a

### Environment info

WordPress 6.3-beta3
Gutenberg 16.1.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Confirmed this in latest Chrome and Safari builds
