### ISSUE TITLE
Social Links Block: add support for Threads

### ISSUE THREAD

**Issue by jeherve** [WordPress/gutenberg#52463]
## What problem does this address?

The [Threads Social Network ](https://en.wikipedia.org/wiki/Threads_(social_network))has quickly become very popular and may be a good addition to the Social Links Block.

## What is your proposed solution?

The SVG is available here:
- https://en.wikipedia.org/wiki/File:Threads_(app)_logo.svg

Links use the following format: `https://www.threads.net/@wordpress`

**Comment by t-hamano** [comment]
Hi @jeherve,

Thanks for submitting the issue.

I think the criteria for whether or not to add a new Embed provider is whether it meets the guidelines of the [Design Decisions](https://make.wordpress.org/core/handbook/contribute/design-decisions/#adding-new-oembed-providers) page in the core handbook. So, I think it needs to be investigated and discussed in the future whether we should add that provider or not.

The discussion that took place in #2505 may also be helpful.

**Comment by jeherve** [comment]
Since this would be a social option and not an embed, some of the questions may not apply here, but we can look at some of the questions that make sense I think:

> Is the service is popular enough for core developers to have heard of it before? Is it “mainstream?”

Yes, I would think so. There are 109 million registered users for the service at the moment, and growing.

> If similar services are already supported, how does this service compare in terms of size, features, and backing?

It is similar to services like Twitter, and has a large amount of users too.

> Does this service have an established social media presence?

Yes. https://twitter.com/Meta

> Does the service make an effort to build relationships with developers, such as through robust APIs?

I would say yes:
https://developers.facebook.com/

> How old is the service?

It launched on July 5, last week.

> Does it have a well-established Wikipedia article? (Seriously.)

Yes. https://en.wikipedia.org/wiki/Threads_(social_network)

> Has anyone written a WordPress plugin that leverages the service in some way, whether adding it as an oEmbed provider, creating a shortcode, or leveraging other APIs of the service? Do these plugins have any noticeable adoption or traction that would indicate usage and demand?

No, not yet, since it's so new. The Jetpack plugin will be adding support soon though:
https://github.com/Automattic/jetpack/pull/31873

> Is the provider frequently proposed?

It was requested here as well:
https://core.trac.wordpress.org/ticket/58762
