### ISSUE TITLE
Refactor Navigation block `render` function to be open for extension

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#52470]
Over the years the `render_block_core_navigation` function has grown to be pretty unwiedly. Making any changes is prone to error and there's little in the way of _direct_ test coverage (we do have e2e tests).

Let's start an _incremental_ refactor with lots of small PRs which break this function down into discreet functions which do one thing. As this process occurs let's add PHPUnit tests to provide test coverage for the smaller functions.

When complete the main `render_block_core_navigation` should be easy to reason about and extend.

**Comment by getdave** [comment]
@scruffian Can we close this out?

**Comment by scruffian** [comment]
Yes! This was fixed by https://github.com/WordPress/gutenberg/pull/55605
