### ISSUE TITLE
Command Center: Brief flash of background when switching from modal to Command Center palette

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#52490]
### Description

If a modal window (like Editor Preferences or Welcome Guide) is active when the command center is triggered (using the keyboard shortcut) there is a brief flash where the overlay is hidden (from the modal) and then shown again (for the command center).

### Step-by-step reproduction instructions

1. Edit a template in the Site Editor
2. Open a modal window (like Editor Preferences or Welcome Guide)
3. Trigger the command center using the keyboard shortcut `⌘k`

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1842363/03ea4ba7-f050-4d74-8f0e-45ec155eeec2

### Environment info

- WP6.3beta3
- Gutenberg 16.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I would say this is expected behavior when dealing with multiple modals. There will be a flash while the first one is closing and the new one is opening.

I don't think it's worth the code complexity required to fix similar inconveniences.

**Comment by jordesign** [comment]
Totally understandable - thanks for the explanation :)
