### ISSUE TITLE
6.3 Beta 4 - Granual image dimension changes in the editor are getting ignored by the browser (only happens with a blank theme).

### ISSUE THREAD

**Issue by Ren2049** [WordPress/gutenberg#52499]
### Description

I can't implement a custom logo consisting of two parts, the Logomark (site icon) and Wordmark (image). When I change the image height to align it with the Logomark/icon the changes are not picked up by the browser, only the selected source image dimensions are picked up by the browser.

Both images (logomark & wordmark) are webp.

I'm using 6.3 beta 3 and a blank theme freshly created from the create block theme plugin where I have only added a variable font so far.

### Step-by-step reproduction instructions

1. Add a .webp image next to a .webp site icon.
2. Change the height of the image and save.
3. Now when viewing it in the browser it displays the selected source image dimensions instead of the custom size.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/133038357/3ccf8c4f-a76c-4c12-b9eb-65f1df131d6c

### Environment info

Theme: Create block theme plugin -> create blank theme
Version: 16.3 beta 3, Gutenberg is not installed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hi @Ren2049 thanks for opening up this new issue - the video is definitely helpful.

Is there a public URL where you have that test page - where I can take a look at the front end to try and tell why that image isn't being resized?

I also wanted to double check - do you see this same issue happening when you test using the TwentyTwentyThree theme? And does it happen only with WebP images - or with other images as well?

**Comment by Ren2049** [comment]
Hey @jordesign both the logomark and wordmark disappear when I switch back to the TT3 theme, only the site title is shown in their place then! Only the logomark remains as site icon in the editor navigation and tab thumbnails.

My guess is it's because both graphics are associated with the header template-part of my blank custom theme. I'll add them again, also as .png and see what happens.

Edit: when I add both .webp graphics back to TT3 from the media library, adjust the size and view them in the browser they appear like they should!

The site is hosted locally but if there's a free backup/export plugin you prefer I can install it, export the site and upload it to a public file host.

**Comment by Ren2049** [comment]
@jordesign The 16.3 Beta 4 update fixed the logo problem!

Thanks for your help, you're awesome!

![beta 4](https://github.com/WordPress/gutenberg/assets/133038357/32353d22-9171-4e17-a6b1-1c6d3ce27a6f)
