### ISSUE TITLE
Plugin patterns appear under "Theme patterns" heading

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52498]
In the Site Editor Pattern library, patterns added by plugins appear under the "Theme patterns" heading which is inaccurate:

<img width="358" alt="Screenshot 2023-07-11 at 09 48 20" src="https://github.com/WordPress/gutenberg/assets/846565/18ed6a7a-e96d-4d5b-bf41-b338c0774efa">

**Comment by jameskoster** [comment]
Possible solutions:

1. Update "Theme patterns" to "Theme & plugin patterns".
2. Add a separate "Plugin patterns" group.

**Comment by bgardner** [comment]
Hard vote for #2.

**Comment by jeffikus** [comment]
@jameskoster I've been thinking about this for templates as well. I think clarity is the most important thing, so I would want to know where a pattern is coming from/sourced. My vote would be for #2 as well.

**Comment by richtabor** [comment]
Could probably just be “Theme” and “Plugin” headings, as “Patterns” is already declared above.

**Comment by glendaviesnz** [comment]
In relation to option 2 I had a quick look and I am not sure how we would reliably identify plugin patterns as separate to theme patterns as it seems like both just use `register_block_pattern`. This currently doesn't provide any `source` information other than the voluntary use of a hopefully meaningful slug. 

We could potentially try and filter out theme patterns by matching the first part of the slug against the theme name, but that seems a little unreliable. I may be missing some other way of identifying that a pattern came from a plugin as apposed to a theme though.

**Comment by vcanales** [comment]
An optional `source` property was [added recently](https://github.com/WordPress/gutenberg/pull/51672).

>-   `source` (optional): A string that denotes the source of the pattern. For a plugin registering a pattern, pass the string 'plugin'. For a theme, pass the string 'theme'.

It doesn't seem to be used within the Gutenberg codebase as of yet, but I'd imagine we can:

1. Add `source = theme` to all patterns registered by a theme, ie. because they are in a theme's `patterns/` directory.
2. Using the `source` property when available to separate patterns in categories (eg. "Theme patterns", "Plugin patterns", "Other patterns").

**Comment by glendaviesnz** [comment]
> 1. Add `source = theme` to all patterns registered by a theme, ie. because they are in a theme's `patterns/` directory.

I was overlooking the fact that theme patterns are actually registered from the `patterns/` dir with `_register_theme_block_patterns() `, so modifying that method to add the `source` seems like a good option @vcanales

**Comment by jameskoster** [comment]
@vcanales @glendaviesnz thank you for looking into this. Do you think it's possible this gets done in time for 6.3?

If not we may need to go with option 1, or another equally simple idea. Perhaps we could remove the "Theme patterns" heading entirely, and move template parts beneath them:

<img width="342" alt="Screenshot 2023-07-12 at 10 52 28" src="https://github.com/WordPress/gutenberg/assets/846565/e0918866-3d57-45f8-b962-a0ae08004146">

**Comment by carolinan** [comment]
There are many older patterns in themes that were registered before the patterns folder was an option.

**Comment by carolinan** [comment]
> Perhaps we could remove the "Theme patterns" heading entirely, and move template parts beneath them:

Yeah, that would work I think? Now that "My patterns" always show.

**Comment by vcanales** [comment]
> @carolinan There are many older patterns in themes that were registered before the patterns folder was an option.

Good point; I wasn't aware.

> @jameskoster  If not we may need to go with option 1, or another equally simple idea. Perhaps we could remove the "Theme patterns" heading entirely, and move template parts beneath them

How about changing it to "Included patterns" for now?

<img width="348" alt="image" src="https://github.com/WordPress/gutenberg/assets/1157901/468e01c2-898b-4700-a9e5-b609a7ca5040">

Created #52568 to get things rolling.

**Comment by carolinan** [comment]
As someone who reads things literally, "my patterns" and "included patterns" read strange to me, like, "What do you mean, are my patterns not included?"

**Comment by bvlgn** [comment]
> Yeah, that would work I think? Now that "My patterns" always show.

Actually, "My patterns" won't show when there are no custom patterns:
![Scherm­afbeelding 2023-07-14 om 09 38 18](https://github.com/WordPress/gutenberg/assets/13752843/d404b076-1681-417f-9fdc-05dac18212e7)

But maybe "My patterns" could/should be shown always, even when no custom patterns are defined, with the count set to 0?

**Comment by ndiego** [comment]
@jameskoster are you ok with punting this one given RC1 is later today? Or will this be considered closed once https://github.com/WordPress/gutenberg/pull/52568 is merged?

**Comment by jameskoster** [comment]
Ah I think this is already closed via https://github.com/WordPress/gutenberg/pull/52570. Thanks for the ping.
