### ISSUE TITLE
6.3 Beta 4 - Blank theme created with the block theme plugin needs excessive group nesting on header template-part to apply content width.

### ISSUE THREAD

**Issue by Ren2049** [WordPress/gutenberg#52501]
### Description

I'd expect the content within the header template part to be contained by the global content width too, but somehow it doesn't happen, it only applies the content width to the query loop, not the group inside the header template part.

### Step-by-step reproduction instructions

1. Go to global layout and set a content width.
2. Toggle content width on the query loop block.
3. Toggle content width on the header group.
 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/133038357/f6095788-b367-4b5c-aca6-97c3b9a80e4c

I use 92vw content width mainly to replace padding for pages with differently styled content sections (I don't want the background of sections to be contained by padding, or add the padding manually for each section. For post templates I'd then set the content width locally.

### Environment info

6.3 Beta 3, Gutenberg plugin not installed, create block theme plugin -> generate blank theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I've taken a look at this - and confirm I also see the Header and Footer parts maintaining full width in the editor. This is as I would expect - as the outer grouping of the Template Part doesn't have any layout settings.

If you are to edit the Header or Template Part directly - I would try adding a Group Block with the 'inner Blocks use Content Width' option set to be on - which would make it behave in the same way as other content (like the Query loop).

Does that help if you try that?

**Comment by Ren2049** [comment]
@jordesign 13 secs in the video there's a group on the header template part and I've toggled content width on on this group which contains the other elements! The problem is that it ignores the group settings/content width toggle! 

Edit: When I switch to TT3 (now in 16.3 beta 4) everything works as it should!

16.3 beta 4 with my blank theme generated with the create block theme plugin still looks like this:

![width](https://github.com/WordPress/gutenberg/assets/133038357/8364f158-dde8-48b3-9295-5c20d9263397)

**Comment by Ren2049** [comment]
The content width toggle works on the header when I use nested groups (group within a group):

![group](https://github.com/WordPress/gutenberg/assets/133038357/6adf5ee2-ee4f-4981-bed7-be67e43e79da)

I find it strange that the TT3 theme doesn't need this complex nesting for the header. Here's a screenshot with the TT3 header structure:

 
![tt3](https://github.com/WordPress/gutenberg/assets/133038357/20903dc8-21a4-453e-b998-ab4643e888f6)

**Comment by Ren2049** [comment]
Sorry closed the wrong one..

**Comment by Ren2049** [comment]
@jordesign should I open a new issue about the topic? 

Any idea why template-parts within custom themes created with the create block plugin need to be wrapped in an additional group to be able to apply the content-width setting?
