### ISSUE TITLE
Navigation block overlay can be not fully visible when it's placed in cover block.

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#52511]
### Description

The modal has `z-index: 100000` and usually appears on top of most things on the screen, for example, the admin bar. However, when it's placed inside a cover block, the z-index isn't `100000` anymore, and the admin bar that has `z-index:99999` wins. 

### Step-by-step reproduction instructions

1. Open the site editor
2. Add a cover block
3. Add a navigation and set overlay menu `always`
5. Open the navigation on the front of the site.
6. Notice you see the admin bar.

### Screenshots, screen recording, code snippet

![localhost local_ (11)](https://github.com/WordPress/gutenberg/assets/908665/27e182bd-f087-4581-bced-ad09f6aef133)

In this example, it doesn't seem to be a problem, but when we don't have full control for the modal layout, this can be a problem.  

### Environment info

- WP 6.2.2
- Gutenberg Trunk
- Twenty Twenty-three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I've tested this and confirmed 👍

**Comment by getdave** [comment]
@iamtakashi This looks like a duplicate of https://github.com/WordPress/gutenberg/issues/45353. Would you be able to review and close this one out if so?

**Comment by getdave** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/45353
