### ISSUE TITLE
Handbook: Update Block Hooks reference examples to not use lodash

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#52545]
## What is your proposed solution?

Remove lodash as a requirement for these examples:
https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/

**Comment by tyxla** [comment]
Good timing for that one! We're a PR away from the complete Lodash removal from all packages: https://github.com/WordPress/gutenberg/issues/17025#issuecomment-1632633444

Let me know if I can help with modernizing any of those pre-existing examples.

**Comment by tyxla** [comment]
Actually, I'm proposing to update these examples as part of #52571.
