### ISSUE TITLE
Footnotes: footnotes are not reverted or restored with post revisions

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#52541]
### Description

When restoring a post's revision, the footnotes associated with that revision are not restored.

Only the latest version of the post's footnotes will appear on the page at any one time.

The consequence is that users can't access a "true" record of a post's changes.

First noticed [here](https://github.com/WordPress/gutenberg/pull/52518#issuecomment-1631804052). 

### Step-by-step reproduction instructions

1. Create a new post 
2. Add some text in a paragraph
3. Add a footnote or two using he block inspector toolbar
4. Save the post
5. Repeat
6. Save the post
7. Restore the previous version
8. Note that the text has been restored but the footnotes have not.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/6458278/452d4784-d8c4-4c99-a402-705948a4f5d7

### Environment info

Gutenberg 16.2
WordPress 6.3-beta3-56201 running Twenty Twenty-Three theme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by firoz2456** [comment]
@ramonjd 
I would be grateful if you could post a video instead of a GIF. The GIF is playing too fast to understand the issue.

**Comment by ramonjd** [comment]
> I would be grateful if you could post a video instead of a GIF. The GIF is playing too fast to understand the issue.

Thanks for the nudge @firoz2456 

Updated 👍🏻

**Comment by firoz2456** [comment]
WordPress 6.3-beta4-56216
After several attempts, I was able to reproduce the issue.

https://github.com/WordPress/gutenberg/assets/8054727/877e5163-04b3-4775-84a6-e134b12e6e53

**Comment by ramonjd** [comment]
There's a record in the `wp_postmeta` table that contains footnotes data for a particular `post_id`, e.g.,

```
post_id: 4
meta_key: footnotes
meta_value: [{"content":"Vestibulum sed diam at nulla luctus feugiat","id":"b208aa51-801d-4538-92d9-8b1aad7c05aa"},{"content":"Nunc sed dolor libero","id":"597a0e21-41d8-47d5-b5f1-894262c23cd1"}]
```

I haven't tested it too deeply, but a combination of the following hook might get close to where we want to be:

1. `save_post` (or maybe `post_updated`)- check if the post's parent has revision meta, if so save a new meta entry with the updated footnotes against the revision id
2. `wp_restore_post_revision` - fetch the footnotes meta associated with the restored revision and restore it to the post parent's meta (the one that is used on the frontend) using `update_post_meta`
3. `_wp_post_revision_fields` and `_wp_post_revision_field_footnotes` - display the current revision's footnotes meta on the revision.php page.

<img width="1063" alt="Screenshot 2023-07-14 at 11 29 50 am" src="https://github.com/WordPress/gutenberg/assets/6458278/6bbad46b-4761-42da-a0ee-690d86fb99ed">

One downside could be is that it would create a new record in `wp_postmeta` every time a post with footnotes is updated.

**Comment by getsource** [comment]
For reference, here is the core trac ticket regarding supporting revisions for post meta:
https://core.trac.wordpress.org/ticket/20564

**Comment by ramonjd** [comment]
> For reference, here is the core trac ticket regarding supporting revisions for post meta:

Wow, that one has grey hairs 😆 10 years and still kicking!

**Comment by ndiego** [comment]
@ramonjd given that this is related to that [Trac issue](https://core.trac.wordpress.org/ticket/20564), should this be punted?

**Comment by annezazu** [comment]
I believe it should be punted and we should look into this for a future release.

**Comment by ramonjd** [comment]
> given that this is related to that [Trac issue](https://core.trac.wordpress.org/ticket/20564), should this be punted?

Sounds good to me, thanks 👍🏻

**Comment by ellatrix** [comment]
Why is this being punted? This seems like a really bad issue to me. People rely on revisions and we're not saving footnotes? That's content loss.

**Comment by ndiego** [comment]
> This seems like a really bad issue to me. People rely on revisions and we're not saving footnotes? That's content loss.

💯 It is a really bad issue. But my understanding is that a fix requires https://core.trac.wordpress.org/ticket/20564 to be merged in 6.3, which sadly appears unlikely at this point.

**Comment by Mamaduka** [comment]
I personally would like to see the "post meta in revisions" issue resolved properly instead of adding a custom handler for footnotes.

**Comment by adamsilverstein** [comment]
Note the code on https://github.com/adamsilverstein/wp-post-meta-revisions is more up to date that what is on the trac ticket. I will try to post an updated patch there.  We can work on trying to land this in core, in the meantime GB could use the plugin code to revision footnote meta if desired.

**Comment by adamsilverstein** [comment]
I tested revisioning footnotes meta using the plugin and observed it worked mostly - I experienced the "off by one" [issue](https://github.com/adamsilverstein/wp-post-meta-revisions/issues/57#issuecomment-520602957) related to the timing of the save.
