### ISSUE TITLE
Justifiy

### ISSUE THREAD

**Issue by teknowlgysites** [WordPress/gutenberg#52551]
It would be great to have a justify button to let the person who types the choice of this option.

just add the option on the button list

**Comment by hanneslsm** [comment]
This is a long discussed issue and with the new global styles there might be the possibility this gets reintroduced. See

- https://github.com/WordPress/gutenberg/issues/8450
- https://github.com/WordPress/gutenberg/issues/48202
- https://github.com/WordPress/gutenberg/pull/52426

**Comment by jordesign** [comment]
Thanks @hanneslsm for linking those :)

@teknowlgysites  - as this is being handled in those other issues, I'm going to close this one as a duplicate - but thanks for reporting it :)
