### ISSUE TITLE
Post Terms Block: Custom Taxonomies variations are not registered correctly

### ISSUE THREAD

**Issue by gaambo** [WordPress/gutenberg#52569]
### Description

In #39837 (fix for #32924) support was added so that for all public taxonomies, variations of the core/post-terms block were added. But the hook to check for public taxonomies is run on `init` with a default priority of 10. 
It's safe to asume, that this will run before many plugins will have registered their custom taxonomies, because the core init hook is added earlier and 10 is the default priority (so many developers will register it on 10 as well). 

**Proposed solution:** 
1. Run the complete `register_block_core_post_terms` on a priority later than 10 (eg 100)
2. Split the function and add variations for all public taxonomies in the editor in JavaScript (performance for fetching all taxonomies?)
3. ~Split the function and add variations add a later point via PHP~ (not possible because [server side version to register block variations is missing](https://github.com/WordPress/gutenberg/issues/47170))

All other core blocks are registered on priority 10, so I think it would be a bit odd to run the register function for only this block on a later priority. Also of course we can't be 100% sure if on priority 100 all  custom taxonomies are already registered (since developers also can use later priorities). So I guess I actually favor solution 2. Is there precedent for any solution like this?

I ran into this problem multiple times, and in the original PR @mrleemon originally found this bug.

### Step-by-step reproduction instructions

**Negative test:**
1. Register a custom taxonomy ([example code from developer.wordpress.org](https://developer.wordpress.org/plugins/taxonomies/working-with-custom-taxonomies/#step-2-creating-a-new-plugin)).
2. Go into site-editor and try to search for a block named like the custom taxonomy (eg "Courses").
3. Block is not available, only the default "Tags" and "Categories" is available

**Positive test:** 
1. Register a custom taxonomy  ([example code from developer.wordpress.org](https://developer.wordpress.org/plugins/taxonomies/working-with-custom-taxonomies/#step-2-creating-a-new-plugin)) but change `add_action` priority to something lower than 10 (eg 9)
2. Go into site-editor and try to search for a blog named as the custom taxonomy (eg "Courses").
3. Block is available

### Environment info

- WordPress 5.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gaambo** [comment]
Thinking about proposed solution 2: 
This might also be a chance, to only display variations of the post-terms block from taxonomies that are related to the current post type. That might be easy in the post-editor when editing a single post type. But when editing a template in the site-editor it might be more complex. I'm not sure about the internals, but as an example I've created a custom post type "event" and wanted to create a single-events template via the site editor. It let's me add the "tags" and "categories" allthough these taxonomies are not connected to the post type. So maybe in the editor we could filter if the post type is connected to a taxonomy, but I'm not sure how to get _the_ post type a template is applied to (since it could also be a general `single` template, used for all post types)

**Comment by gaambo** [comment]
I've tried a first attempt at solving this with my solution 1 from the op. I don't think it's good to go yet, but I wanted to try how that would work on the editor side. 
Happy for any feedback/review/help :)

**Comment by gaambo** [comment]
The problem described in the original issue is still there in current trunk and the reproducation steps still apply.

**Comment by gaambo** [comment]
Work for #53826 happens in #54434 atm. Since the issue is similar, I expect to reuse those results from there for this issues as well.

**Comment by gaambo** [comment]
Was fixed in 2c247e2ae62b5d61dcdf5c634c13c7ccf0731b0d via the new `variation_callback` argument when registering the block.

**Comment by BenceSzalai** [comment]
Great addition.

For those who are looking for it: For your custom taxonomy to show up in Gutenberg you need to set either `publicly_queryable` and `show_in_rest` to `true` in your `register_taxonomy()` call. If `publicly_queryable` is not explicitly set, it'll default to `public`, so setting `public` to true without `publicly_queryable` is also good.
