### ISSUE TITLE
LinkControl: Remove home URL from suggestion

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#52572]
As a follow-up to https://github.com/WordPress/gutenberg/pull/52523, I propose removing the site's home URL from the `suggestion?.url`. 

For example, on my site richtabor.com, the About page would render `/about`, instead of `https://richtabor.com/about`. This would help reduce the information density and improve scan-ability.

In the screenshot below, `localhost:888` would be omitted. 

<img width="350" alt="CleanShot 2023-07-12 at 11 32 33" src="https://github.com/WordPress/gutenberg/assets/1813435/ac11bd30-789f-4aac-8ceb-7505a72e3996">

**Comment by getdave** [comment]
In theory this is a case of:

- getting the baseURL for the site.
- search and replace on the value

However we should probably try and keep the Link Control ignorant of such things so it could be a little trickier.

**Comment by richtabor** [comment]
Could we add a parameter within `filterURLForDisplay` to omit the baseURL?
