### ISSUE TITLE
[NOT sure if related to Gutenberg] sanitizer about a tag

### ISSUE THREAD

**Issue by RadND** [WordPress/gutenberg#52589]
### Description

I want to insert a `<a></a>` with different protocol , block preview is fine , but the protocol part of URL is missing in real page

### Step-by-step reproduction instructions

1. add a link use pagraph block or custom HTML block
2. `<a href="minecraft://?addExternalServer=My Server Name|server.example.com:port" target="_blank" rel="noreferrer noopener">click to play<strong>My Server Name Again</strong></a>`
3. publish/update
4. don't work , edit again and found 
`<a href="//?addExternalServer=My Server Name|server.example.com:port" target="_blank" rel="noreferrer noopener">click to play<strong>My Server Name Again</strong></a>`
noticed protocol part (minecraft) of href attr is missing

I guees it's universal to other non http(s) protocol , so it doesn't matter to not provide my minecraft server address here

### Environment info

wp is 6.2.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by jordesign** [comment]
Thanks for reporting @RadND  - it would be great if you could double check this _with_ all plugins deactivated except Gutenberg - to see if one of them may be conflicting. Could you please try that out?

It's also worth making sure you test with a default theme like TwentyTwentyThree to make sure it isn't a theme conflict.

**Comment by RadND** [comment]
Sure, I enabled troubleshooting mode (theme is TwentyTwentyThree ) ,hope this fits the requirement , thing in this issue still persists. @jordesign
tried on p block and custom html block

**Comment by t-hamano** [comment]
I think this is not a problem with Gutenberg, but with the WordPress core, which does not allow the `minecraft` protocol. If you update your post using the classic editor, you should be able to reproduce the same problem.

You may want to use the [kses_allowed_protocols](https://developer.wordpress.org/reference/hooks/kses_allowed_protocols/) hook to add the protocols you want to allow.

```php
add_filter( 'kses_allowed_protocols', function ( $protocols ) {
  $protocols[] = 'minecraft';
  return $protocols;
} );
```

I would like to close this issue, but if I have missed something feel free to comment.

**Comment by RadND** [comment]
thank you , now it looks obvious, sorry for wasting your time, I will do more search before ask next time.
