### ISSUE TITLE
WP 6.3-beta4: not all patterns and categories listed in site editor

### ISSUE THREAD

**Issue by bvlgn** [WordPress/gutenberg#52608]
### Description

In de site editor only very few of the regitered patterns and categories are listed.

### Step-by-step reproduction instructions

![listbug](https://github.com/WordPress/gutenberg/assets/13752843/c59cc9f7-5eb6-4447-a64a-fe1cf76a401c)

### Environment info

WordPress: 6.3-beta4, with no other plugins besides de beta tester pluigin. 
Twenty-Twenty-Three theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bvlgn** [comment]
Maybe, also have a look at the console and notice the multitude of messages that are generated when you click on the various pattern categories.

**Comment by jordesign** [comment]
I can recreate this in testing as well. Patterns are still present in the inserter within the editor - but not in the Site Browser.

**Comment by annezazu** [comment]
@aaronrobertshaw since you've worked on this section. Adding to to do as this does feel like a departure from what was there in earlier versions/what's intended.

**Comment by ndiego** [comment]
For TT3, only the three patterns that appear have `Inserter` set to `true`. So I believe this is correct. All other patterns are intentionally hidden. 

If you try and theme like [Frost](https://wordpress.org/themes/frost/), which has all patterns enabled, they do show up.

![Image](https://github.com/WordPress/gutenberg/assets/4832319/60246762-61c2-40f8-9823-d274eaaebe75)

**Comment by bvlgn** [comment]
Ah, that explains it.
But I suspect, this might be an area of confusing for other users too?

**Comment by mikachan** [comment]
https://github.com/WordPress/gutenberg/pull/52633 may also help improve this, as this will allow all patterns to be listed in the Patterns section in the editor, even if they aren't categorised. The exception would be if the pattern sets `Inserter` to `no`/`false` (with the help of https://github.com/WordPress/gutenberg/issues/52629).

**Comment by ndiego** [comment]
> For TT3, only the three patterns that appear have `Inserter` set to true. So I believe this is correct. All other patterns are intentionally hidden.

I was incorrect above. The patterns that are not showing in TT3 do have `Inserter: no` but they are not displaying because they also do not have any assigned categories. As @mikachan mentions, https://github.com/WordPress/gutenberg/pull/52633 and https://github.com/WordPress/gutenberg/issues/52629 will resolve this.

**Comment by annezazu** [comment]
Ah ha. Closing this out then in favor of https://github.com/WordPress/gutenberg/issues/52614 Happy to reopen if there's something I'm missing but want to keep this work consolidated at this point.
