### ISSUE TITLE
Aspect Ratio : Extend

### ISSUE THREAD

**Issue by Stephan256** [WordPress/gutenberg#52606]
hi,

I would like to add to the list of aspect-ratios : 16/10.
How can I do this via JS?
Thanks in advance.
Cordially

**Comment by jordesign** [comment]
Hi @Stephan256  - this Github repo is predominantly for the reporting of bugs an feature requests in the development of Gutenberg.

For support requests like yours - could you please request them in the Support Forums for Gutenberg?
You can do that here:
https://wordpress.org/support/plugin/gutenberg/?view=all
