### ISSUE TITLE
Notification snackbar is below modals

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#52609]
### Description

If there is a modal open in the editor, the notification snack bar is below instead of on top of it.

### Step-by-step reproduction instructions

1.  Open a full-page modal
2. Do an action that raise a notification and see that it is below the modal

### Screenshots, screen recording, code snippet

In the screencast we can see the problem in action:

https://github.com/WordPress/gutenberg/assets/1310626/19b56cf9-46f6-4600-8825-3f95c5824ad9

### Environment info

- WordPress 6.2.2
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by vcanales** [comment]
Snackbars do not currently support this behavior (ie. being on top of Modals and/or their overlays) because they are nested within the body of the site editor, while Modals live closer to the root of the element, as a direct child of `<body>`.

Changes to position and z-index won't put the `Snackbar` above the Modal due to CSS stacking context rules. Nested elements can't out-stack their ancestors, regardless of z-index. We need to adjust the DOM structure or stacking context, not just tweak position or z-index.

The first fix that comes to mind would be moving Snackbar notifications closer to `<body>`, but it doesn't look trivial, since their current implementation makes them rely on the <InterfaceSkeleton /> component to be rendered.

**Comment by mikachan** [comment]
Could the modal be made smaller, so the Snackbar is visible (at least the furthest-to-the-bottom one)? Although this isn't ideal as it's still underneath the overlay. Maybe we could make the modal a similar size to the Preferences modal:

<img width="1436" alt="image" src="https://github.com/WordPress/gutenberg/assets/1645628/c3fbd07a-025d-4414-9156-197bb43442ed">


Another alternative could be to replicate the notifications in another component within the modal and disable the current Snackbar notifications, as it would probably be confusing to have multiple sets of notifications.

**Comment by hanneslsm** [comment]
> Maybe we could make the modal a similar size to the Preferences modal:

The Preference modal also overlays the notifications on smaller viewports.
![Image](https://github.com/WordPress/gutenberg/assets/17861443/96866762-8408-4fc6-8740-29ccc714cbef)

**Comment by mikachan** [comment]
Ah good spot! I think this definitely needs a fix then, maybe something within the modal itself.

**Comment by madhusudhand** [comment]
Currently I see that `snackbar` and `modal` are under different DOM hierarchy. (snackbar is within the editor, where as modal is attached to the body). This is causing `snack-bar` to always be behind the modal.

I think the right way for the snackbar is to attach it to body and give a higher z-index than modal.

I did a small test around this and it seems to be working. (I haven't tested full use cases of snackbar, but it should't break things)

Wraped the snackbar component inside `createPortal` function
```
return createPortal(<></>, document.body)
```
This moved the snack-bar to body in the DOM, and now that it is in the same level as `modal`, setting a higher z-index brings it on top of modal.

**Note**: I have set few additional styles inline to adjust the position.



<img width="812" alt="image" src="https://github.com/WordPress/gutenberg/assets/1935113/5081e8a1-93d4-4cb5-acb2-322443792fc5">

**Comment by mikachan** [comment]
I'm going to close this, as I don't think it's a good idea to move the snackbars above the modals. This was also raised as part of the Font Library work, which [should not be using the snackbar notifications](https://github.com/WordPress/gutenberg/pull/54153#issuecomment-1712538231) anyway.
