### ISSUE TITLE
Theme.json changes/additions in spacingSizes + fontSizes + color-palette NEVER arrive once there are user overrides (in DB)

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#52619]
##  This is a whole user scenario which contains several bugs reports in itself
- Identifying/dissecting the individual bugs needs the help of professionals, ideally developers deeply involved in the Gutenberg Style Engine (putting you in CC below)
  - I hence do consciously not post this into the support forum.
    - The motivation of this is not to achieve a concrete personal end goal, but shows general problems.
  - This really needs the incolvement of people who actually develop the Style Engine.
- Experimenting, debugging and finally reporting took me 2 work days
  - Most people will give up and say: Too much for me, I give up.
  - After having got deep into the trouble already (several DB and file resets) I took that extra mile, to compile this together, in the hopes that this brings insights for fixing bugs

## I) [theme-v1-original-TT3.json](https://github.com/WordPress/gutenberg/files/12044570/theme-v1-original-TT3.json.txt)

- Original TT3 as it was as of WP 6.2, attached here too.

## II) [theme-v2-TT3-customized.json](https://github.com/WordPress/gutenberg/files/12044573/theme-v2-TT3-customized.json.txt)

- Cloned TT3 as a new theme
- Then made a few changes in `theme.json` (plus offtopic: some `functions.php` stuff + Custom CSS files)
- Changes to `theme.json`:

### 1) settings → color → palette

- Added 3 colors: `link-plain`, `good`, `bad`

- Again the first addition "link-plain" only required working with OPcode caching off (or resetting after having done the changes).

- But later color additions `good` and `bad` never made it, also with OPCode entirely deactivated.

- It seems if you have done ANY user customizations on top of the theme (which live in the database) these block the discovery of `theme.json` attribute changes/additions ENTIRELY. The single branches in the JSON working strictly in a ALL or NOTHING manner, not in an additive/differentiated manner.

- ✅ Site Editor: Styles → Colors → Reset Colors.
  - Then colors "good" and "bad" were part of the palette. 
  - Technically this means I wiped the entire user customization layer, for that part of the JSON branch.
- :! But that can't be the only way?
  - It must be possible that changes in `theme.json` are discovered also with some user customization in certain areas.
  - I mean it resolved my issues with the colors.
  - But a) not every area in the Styles UI has a Reset function, and b) this should not be necessary, it leads the whole layer interplay ad absurdum.

### 2) settings → spacing → spacingSizes

Added 2 at start:
```json
{ "size": "clamp(8px, 2.5vw, 16px)", "slug": "25", "name": "0b" },
{ "size": "clamp(0.5rem, -19rem + 48vw, 2rem)", "slug": "29", "name": "0x" },
```

Added 1 at the start:
```json
{ "size": "clamp(11rem, 20vw, 15rem)", "slug": "90", "name": "7" }
```

- Interestingly only first addition slug 25 got available in the UI.
- The other two later additions slugs 29 and 90 never got available.
- ❌ I found no method analog to how I got the extra colors added to the palette ("Reset Colors" in the UI).

### 3) Link text does not have its defined color but falsely color from button text

#51265 Was the reason why I needed the following theme.json fix [advised by](https://github.com/WordPress/gutenberg/issues/51265#issuecomment-1580996230) @scruffian :

- styles → blocks → core/post-content → elements → link → color → text → `var(--wp--preset--color--link-plain)`
  - color "link-plain" was defined in change II.2.

- styles → spacing → padding → top → Changed from "var(--wp--preset--spacing--40)" to "0"
  - AFAIR I persisted in the theme.json what can also be set in the Site Editor UI. Just that this for me crucial change sticks in any case.

### 1) settings → typography → fontSizes

- In the original `fontSize` `x-large` is the only with `fluid: false`
- I turned it into a fluid one too.
- Among the `fontSizes` series I made the size increases less drastic
- But I added no extra `fontSize`. Same amount of elements. Nor did I change the element order.

### 2) styles → elements

- In the original among `h1`-`h6` some use `--wp--preset--font-size--*` while others use `clamp()` while others use a static `rem` size.
  - I wanted all to work along `--wp--preset--font-size--*`
  - Ideally not only with the given `settings → typography → fontSizes` but also with added ones, but I failed already simply changing the existing ones, see II.2.

- `h1 → fontSize`: changed from `3.625rem` to "var(--wp--preset--font-size--xx-large)"

- `h2 → fontSize`: changed from `"clamp(2.625rem, calc(2.625rem + ((1vw - 0.48rem) * 8.4135)), 3.25rem)"` to `var(--wp--preset--font-size--xx-large)`
  - Yes that's exactly as H1. Possibly one day would change that to a new fontSize XXXL, if I knew how to succeed with II.2.

- h1 + h2: Removed `lineHeight: 1.2` alltogether. Shall simply use lineHeight as defined in: styles → elements → heading.

### ❌ Result of III: Effectively total template meltdown! 

- a) The fontFamily is not `System-font` anymore, but instead some `Serif`.
- b) The mitigation attempts make it even worse, bring bigger followup issues.
 - Site Editor → Styles → Typography → Text → Font: `System-Font` not available to choose in dropdown.
- c) Also my theme colors are gone.
 - Site Editor → Styles → Colors → Palette: Shows not my 20 colors (17 + my 3 custom ones), but fewer and different ones.
   - It seems the Style Engine for some reason choose one of the predefined-styles (Aubergine, Block Out, Canary, ...)
 - Going to: Site Editor → Styles → Browse styles → Indeed one of those styles is selected (cannot recall which one, does not really matter, that one of those got auto selected IS the matter)
 - The problem: The color palette defined/customized in `theme.json` "live" nowhere, cannot be "chosen" in the UI.
   - I clicked "Default" in the hopes that this restores my color palette as defined in theme.json.
     - No it doesn't. Also not with a subsequent "Reset colors."
   - The problem is: The style engine seems in an undefined state now due to the change from II to III.
     - It is not using the color palette as in `theme.json`
   - For some reason it automatically chooses a preset-style (simply from that file change in theme.json from v2 to v3, nothing else, I could reproduce this!)
   - And as a user I cannot "unselect a preset", nor does "default" select my color palette as in theme.json.
   - So total dead end, once you are in this situation
 - d) Also the alignment and metrics of my custom header block used in my page template is messed up.
   - All this from a minimal `theme.json` change.

## End result: Template feels like indeterministic voodoo house of cards — Don't dare touching anything too big/essential — Sad
- I have invested over half a year tweaking the template and plugins until they were to my liking.
- Also using the built in theme export function DOES NOT reliably export "original theme + user customizations" into a new theme file.
- No. When you choose that new theme and reset all residue customizations on top, you are left with something else, but not the cumulative "original theme + customizations".
- Nothing of the Style Engine and Templating works deterministic!!!
- I already got deep into it. For half a year did WordPress stuff only, and still don't see through it! Don't like to admit that myself: But that's the horrible verdict.
- Most will know me and my contributions meanwhile: Gutenberg is promising. But the complexity of Block Theme Templating can feel overwhelming.
  - What I did: Reset my DB and reset exactly to theme-v2-TT3-customized.json.
  - I don't dare to touch typography sizes or spazeSizes, although I wanted that to complete all my design module needs.
  - I complete my website with the template as-is now.
  - In 1-2 years will mod a theme clean from scratch.

**Comment by porg** [comment]
CC: @scruffian @getdave @ndiego

**Comment by porg** [comment]
If needed: Tell me where in the DB the user customizations are persisted and how I can dump/export them, and I will provide you these too, so that you can completely replay my scenario.

**Comment by porg** [comment]
A first hunch you could advise me on:
- Keeping the same theme slug, associates it with the existing overrides in the DB, I assume.
- So saving the template under a new slug, starts it as a "fresh slate" then?
  - Could this be a way to avoid the issues I experienced?

**Comment by porg** [comment]
Now did this:
- Created theme-v3 as theme with v3 in its slug and v2 with v2 in its slug, so that technically they are unrelated standalone themes.
- Switching back and forth between these two switches between fine (v2 + user overrides) and broken (v3) 100% re-producible.

**Comment by porg** [comment]
Dear style engine architects/developers,

I'd like to schedule a video call with one/some of you and give you feedback of what I found out:

- Given the complexity of the subject at hand, this would be way more efficient live with screen sharing, than msg ping-ponging.
- Please PM me at abitofmind on the WP-Slack and schedule an appointment with me.
- I'm willing to give you feedback what usability issues I encountered (professional self observation).

**Comment by porg** [comment]
Besides of conceptual issues, I also discovered my human error. Malformed JSON. Explains why the template was "sort of loaded" but mostly broken.

Btw I doubt that "parse as good as possible, and continue without throwing an arrow" is the best way. Throwing a warning in the Site Editor or Backend somewhere would not hurt…

**Comment by ndiego** [comment]
> I'd like to schedule a video call with one/some of you and give you feedback of what I found out:

Hi @porg, thank you for the detailed report. Given timezones and existing work, a scheduled video call will not be possible (at least on my end). We also try and work as asynchronously as possible. 

In that vein, would you be able to record a video of the issues you are experiencing and post it here? That might be easier than writing everything out, and we will be able to view the context behind the issues.

> Also using the built in theme export function DOES NOT reliably export "original theme + user customizations" into a new theme file.

Also, can you elaborate on this a bit more? Are you using the [Create Block Theme](https://wordpress.org/plugins/create-block-theme/) plugin to export the original theme and user customizations? If so, there might be a bug in the plugin. I know I ran into a few issues last week with this.

**Comment by porg** [comment]
My immediate despair regarding the style engine starting to feel more like voodoo than being a deterministic and controllable engine is gone now that I detected that I had fed it with a malformed JSON and all other symptoms were most likely follow up issues of this.

It will take some more time that I see through all this. And then I may be able to extrapolate genuine usability issues and/or bugs from which I'd then possibly share. Keep your subscriptions/notifications on! 👍

**Comment by getdave** [comment]
Thanks for the ping. I'm not sure I'm the best person to help here as the style engine isn't an area where I have particular expertise. 

A good idea would be to raise this as an agenda item for the Core Editor chat which happen each Wednesday in Core Slack. You don't have to attend if you can't make it. Just leave a comment on [the agenda post](https://make.wordpress.org/core/tag/core-editor-agenda/) and the facilitator will raise it on your behalf. A summary will then be posted or you can use the backscroll to see what was discussed.

I would advise keeping the comment short, providing a very brief summary of the problem you've identified and asking for anyone with expertise in the Style Engine to take a look at the Issue.

Please do bear in mind that contributors are spread across the world and there is currently a major release going on so folks are likely to be a little more "stretched" during this time. Generally things will happen async and you may not receive an immediate response. That's normal and it doesn't mean that your issue isn't being considered.

I agree with @ndiego that a succinct video overview of the problem would really help here. Also if there are multiple Issues, we try our best to make them distinct in order that we can avoid making any one issue too overwhelming. 

Thanks for taking the time to provide feedback - it really does help 🙇‍♂️

**Comment by porg** [comment]
- Thanks for the concrete proposal how to raise this.
- Given that there is a release ahead and me having cut the Gordian knot just yday, it is wiser that I raise this on July 26th.
- I hope by then I can sum these up as the essentials.

**Comment by porg** [comment]
## Closing
- Malformed JSON was the root cause.
- Apart from that I could not identify any concrete conceptional/usability issues til now, so it's time to close in order to "burn down", and if I have something concrete would open a new issue then.
