### ISSUE TITLE
Patterns: Theme patterns without Categories do not show in Library

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/gutenberg#52614]
## Issue

**Theme** patterns without the `Categories` (in pattern header) do **not appear at all** in the new Library (WP 6.3 beta 4), but they still appear in the block editor inserter library. 

## Expectation

It should be consistent for uncategorized patterns. Either infer that they're uncategorized and show them anyway under 'Uncategorized' in both the Editor _and_ the inserter, or do not show them at all in either.

### Step-by-step reproduction instructions

WordPress Beta Tester Plugin (v 3.5.2) and WP 6.3 beta-4 installed. Twenty Twenty-Three (v1.1) theme activated. That is all.

1. Launch Editor > Patterns, and choose 'Featured' category (`/wp-admin/site-editor.php?path=%2Fpatterns&categoryType=pattern&categoryId=featured`). Notice there is one pattern: "Call to action"
2. Open Twenty Twenty-Three's `patterns/call-to-action.php` file and remove line 5: ` * Categories: featured` and save the file.

Repeat step #1 (above) and note that the 'Featured' category is gone and the "Call to action" pattern can not be found under any other category in the Editor.

However, you can still create a new post and open the inserter library, switch to the Patterns tab, and still find the "Call to action" pattern even when it does not have the ` * Categories: featured`. I've tested this issue _with_ and _without_ the latest Gutenberg plugin activated and there is no change in impact.

### Screenshots, screen recording, code snippet

| Before | After (theme pattern has no `Categories`) |
|---------|------------|
| ![Screenshot 2023-07-13 at 3 43 11 PM](https://github.com/WordPress/gutenberg/assets/405912/e1165332-dd38-4bad-a1e8-c24406d012a8) | ![Screenshot 2023-07-13 at 3 47 48 PM](https://github.com/WordPress/gutenberg/assets/405912/1ecd43fd-f9e9-449b-9880-d5d522d866b3) |
| ![Screenshot 2023-07-13 at 3 54 56 PM](https://github.com/WordPress/gutenberg/assets/405912/9c714bb2-7fa9-4dfe-a932-6926f849ecf5) | ![Screenshot 2023-07-13 at 3 55 24 PM](https://github.com/WordPress/gutenberg/assets/405912/340f04e9-f78b-4d1c-a2c9-2ea7c5c3ebf0) |

### Environment info

- WordPress 6.3 beta-4
- WordPress Beta Tester Plugin (v 3.5.2)
- Twenty Twenty-Three (v1.1)
- Chrome 114.0.5735.198
- macOS 13.4.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Good catch, thanks @colorful-tones
