### ISSUE TITLE
Block patterns with "Inserter: no" are listed in the Site Editor > Patterns list

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#52629]
### Description

Theme patterns with `Inserter: no` in the pattern file header shows up under Appearance > Editor > Patterns,
but they do not show up in Block Editor > Block Inserter > Patterns tab.

I think this should be consistent. It could be confusing for some users that there are patterns listed that can not be inserted.

### Step-by-step reproduction instructions

In Twenty Twenty-Three, add  `Inserter: no` to the file header of the post meta block pattern: twentytwentythree/patterns/post-meta.php. 
```
<?php
/**
 * Title: Post Meta
 * Slug: twentytwentythree/post-meta
 * Categories: query
 * Keywords: post meta
 * Block Types: core/template-part/post-meta
 * Inserter: no
 */
?>
```
Save the file changes. 😄 
Go to Appearance > Editor > Patterns and see that the post meta pattern is listed under  Theme Patterns > Posts

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by justintadlock** [comment]
The sidebar label text for these also says that the patterns can be inserted:

> For insertion into documents where they can then be customized.

**Comment by widoz** [comment]
Have we considered the fact that, at the end you can copy / paste the blocks or convert the blocks rendered in a template into pattern again making them available everywhere? 

As a content creator it is just a little bit annoying to recreate the pattern but nonetheless an `Insert: no` will not prevent me to do it (the annoying part is to discover where the pattern is being used). 

Based on that logic does still make sense to have "hidden" patterns? I am missing surely something ... but what's the benefit of not making available a pattern if then I can still re-create it?

**Comment by carolinan** [comment]
I am sure different theme authors will give you different answers.
Hidden patterns are not used to prevent advanced users from using patterns, rather hidden to not confuse other users.
A pattern used to translate texts in the context of post meta information is not useful to most users, but theme developers can use them to not have to repeat code in templates.

**Comment by carolinan** [comment]
> the annoying part is to discover where the pattern is being used.

As a user you should not need to even think about this. These patterns are building parts of theme templates,
they are **not** synced patterns that can be edited. When viewed they should just look like any blocks in a template, as a user, you wouldn't even need to know that the theme developer used a pattern to place those blocks there.

**Comment by ndiego** [comment]
I have labeled this as a bug. These patterns should not be insertable or viewable from within the Editor or Site Editor UI. Using `Inserter: no` is the only way to create a pattern designed specifically for internal theme use.
