### ISSUE TITLE
6.3beta: Site Browser - strange loading glitch when previewing patterns

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#52623]
### Description

When loading a category of patterns - taller patterns display a loop/glitch when loading the preview, but only when the category menu item is hovered.

### Step-by-step reproduction instructions

1. Make sure you have a pattern saved which is quite tall. I was able to see this in effect on the default 'Comments' pattern in TwentyTwentyThree
2. Go to the Site Editor > Patterns and click on the category containing the tall pattern (General in this case). **Make sure you keep the cursor hovering over the category menu item**

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1842363/7137fe96-2a2f-4c87-a53d-57da95dfb26c

### Environment info

* WP 6.3 beta 4
* TT3 
* No plugins

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bvlgn** [comment]
It is even more prominent when more patterns are in a section, e.g:

![listbug](https://github.com/WordPress/gutenberg/assets/13752843/4651a8ef-5379-4aa2-8c9e-23a0d6d92a16)

At the start I reload the browser screen and click on 'FSE Eleven' after that I don't interact with it at all; the loading/reloading of the patterns on the right happens on it self.

**Comment by annezazu** [comment]
This should be addressed by @glendaviesnz with https://github.com/WordPress/gutenberg/pull/52538 being merged. This should be in 6.3 RC1. If you can, please help test the PR to ensure it addresses the issue at hand.

**Comment by annezazu** [comment]
Noting that the PR isn't in 6.3-beta4-56228 but I can replicate this problem there. Going to proactively add this to "to do" to be safe and have a note to test again in RC1.

**Comment by annezazu** [comment]
I can't replicate with 6.3-beta4-56253 so I'm going to close this out!

https://github.com/WordPress/gutenberg/assets/26996883/d480b8ba-8f55-4187-9b84-dd4f914c500c

Feel free to reopen as needed based on future replication with RC1+.
