### ISSUE TITLE
Command Center: Selecting actions related to styles redirects from current page to the Home template

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#52626]
### Description

When using the Command Center to access style-related actions - I expect to remain on my current page in the Site Editor, but instead am redirected to the current Home template. This seems to effect:

* Open styles
* Learn about styles
* Open style revisions
* 
By comparison - each of these items *can* be access directly while editing the current page/template in the site editor - by manually going to the Styles panel and then selecting the welcome tour, or revisions.

### Step-by-step reproduction instructions

1. Open the site editor and edit a page
2. Invoke the Command Center and type 'style'
3. Select any of the three actions mentioned above

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1842363/9e362310-0436-40c6-bd2c-928b4ad7d747

### Environment info

* WP 6.3 beta 4
* TT3
* No plugins

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
cc @youknowriad / @mcsf on this! Moving to to do as this does feel like something to fix to make the experience less jarring. Feels very unexpected that it moves you out of the page/template experience and defaults to the Home template.
