### ISSUE TITLE
Custom Fields not available in newest version of Gutenberg

### ISSUE THREAD

**Issue by mrfatguy** [WordPress/gutenberg#52638]
### Description

Enabling Custom Fields in Gutenberg options (as advised by two separate sources: [Wordpress.org](https://wordpress.org/documentation/article/assign-custom-fields/) and [Plugin: Custom Fields for Gutenberg](https://wordpress.org/support/topic/please-read-7) has no effect. Additional section does not appear. No way to add custom fields.

### Step-by-step reproduction instructions

1. Start editing any article in Gutenberg
2. Go to _three dot_ → Preferences → Panels
3. Check _Custom fields_ checkbox, click _Show & Reload Page_

### Screenshots, screen recording, code snippet

![Gutenberg-Custom Fields](https://github.com/WordPress/gutenberg/assets/2903392/0008723b-0cb6-4591-ae6e-92d47c79adc6)

### Environment info

- Wordpress 5.9, Version 16.2.1, [Bloggist](https://superbthemes.com/demo/bloggist/) theme
- Microsoft Edge 114.0.1823.79 (Official build) (64-bit)
- Desktop with Microsoft Windows 11 Pro 10.0.22621 Build 22621

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
@trejder, the fields should be displayed below the post content.

## Screenshot
![CleanShot 2023-07-14 at 17 26 36](https://github.com/WordPress/gutenberg/assets/240569/6ed583e8-74c0-4570-bd33-d87fb6c8c98c)

**Comment by trejder** [comment]
@Mamaduka Thanks! I don't notice them, because my blogs have really, really long content.

Is there any particular reason why they must be _under_ post content? What so different or important about them that they can't appear in post settings sidebar? Just as any other regular section, next to _Tags_, _Excerpt_, etc.?

Shall I rise a feature request to introduce this change?

**Comment by Mamaduka** [comment]
@trejder, this is where the "Custom Fields" always were displayed, even in Classic Editor. That probably won't change.

**Comment by trejder** [comment]
Thank you!
