### ISSUE TITLE
Copying a theme/plugin pattern should open up the patten in its detail view

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#52649]
When copying a pattern bundled with a theme or plugin into "My Patterns", the pattern should be opened up in its detail view. Currently you copy, read the snackbar notification, click the action, then click on the pattern. 

Copying a pattern to "My Patterns" assumes you want to likely edit that pattern. 

https://github.com/WordPress/gutenberg/assets/1813435/cbeee206-5528-4bd5-968d-9cf02f2da36a

**Comment by aaronrobertshaw** [comment]
For some added background here, when the pattern duplication was added it initially when to the pattern edit view. That was a [little jarring](https://github.com/WordPress/gutenberg/pull/52270#issuecomment-1620074308) so as a result the user was left on the Patterns page.

> Being sent immediately to edit the duplicated pattern was a bit unexpected for me. Could we try remaining in the management view?

I'll spin up a PR tomorrow that takes the user to the new pattern's detail view so it can be played with.

**Comment by aaronrobertshaw** [comment]
There wasn't a lot involved in rolling it back to go to the pattern details view. A PR is up in https://github.com/WordPress/gutenberg/pull/53214.
