### ISSUE TITLE
Align Status and Visibility settings in Site Editor and Post Editor

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#52643]
### Description

https://github.com/WordPress/gutenberg/issues/52632 aims to align soem edit features in the Site and Post editorl. However, seems to me the edit features aren't the only things that would need to be better aligned. Some important parts of the UI aren't 'aligned' as well.

I'm not sure I understand why in the Site editor, when editing a page, the Status and Visibility properties are all mixed together under a group and popover named 'Status':

<img width="383" alt="site editor Status Visibility properties mixed together" src="https://github.com/WordPress/gutenberg/assets/1682452/c991047d-03ed-4428-b069-3787685c69be">

To me, that's extremely confusing as these properties have always been separated into two groups: Status and Visibility.

In the Post editor instead:

- the Visibility properties live in a dedicated 'Visibility" group / popover:

<img width="293" alt="Screenshot 2023-07-14 at 16 06 18" src="https://github.com/WordPress/gutenberg/assets/1682452/17b77ee8-3e1a-4052-a357-1cc0ce5abc3b">

- the Status properties (Published, Scheduled, Pending review, Draft) work a bit differently: they're either inherently set (for example based on the publish date) or have separated settings.

Providing two different UIs doesn't seem ideal to me. For example, the 'Private' setting in the Site editor is placed in a completely different spot compared to the Post editor, and so on. I think users will be greatly confused and forced to explore the UI every time they need to find one of these settings. There's no consistency in the two editors, nor the UI provide a sufficient affordance.

Not to mention that, in terms of UI, these properties have always been split into two separate groups in the Classic admin interface. Users are familiar with that and I'm not sure I see a good reason to change that convention. The screenshot below  illustrates how these properties used to be presented in the Classic editor:

<img width="592" alt="classic" src="https://github.com/WordPress/gutenberg/assets/1682452/37808c08-4c66-46fc-99a3-003f53af2bf8">

Visibility:
- Public
- Private
- Password protected 

Status:
- Published 
- Scheduled  (shown conditionally based on the publish date)
- Pending review 
- Draft 

Lastly, there's some wrong terminology in use e.g.

```
Published
Visible to everyone
```

That's a _visibility_ setting: 'Published' should be 'Public'.

Marking this issue as Bug and not as Enhancement because IMHO the UI in the Site Editor is greatly unclear and provides a subpar experience for users.

### Step-by-step reproduction instructions

- Go to the Site editor > Pages > any page
- In the Settings panel, edit the page Status
- Observe the Status and Visibility properties are all mixed together within the same group / popover.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
This has been addressed in a previous release.
