### ISSUE TITLE
Add command for renaming a pattern

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#52651]
When in pattern focus mode I'd expect to be able to quickly rename a pattern. Currently that's only possible via the Patterns Site Editor grid view. The command should be suggested when in this context and could invoke the existing modal for renaming. 

In the future it would be interesting to explore in-command-palette actions, like triggering a view for renaming. 🤔

Edit pencil icon / "Rename" 

<img width="1308" alt="CleanShot 2023-07-14 at 15 55 13" src="https://github.com/WordPress/gutenberg/assets/1813435/e990f778-215b-4749-84ce-ddb10b7811d3">

<img width="381" alt="CleanShot 2023-07-14 at 15 58 54" src="https://github.com/WordPress/gutenberg/assets/1813435/fe48d509-5dad-4be9-bd8a-f695da7a7a42">

**Comment by richtabor** [comment]
We should have the same for renaming a custom template as well.

**Comment by aaronrobertshaw** [comment]
A PR adding a rename pattern command has been merged (https://github.com/WordPress/gutenberg/pull/55188). 

Renaming of templates is still outstanding for the moment.

**Comment by richtabor** [comment]
> A PR adding a rename pattern command has been merged (#55188).

Nice! A quick follow-up would be to have it as a suggested command when you trigger the palette from the pattern editor. And also to use the small edit pencil icon.

**Comment by aaronrobertshaw** [comment]
> have it as a suggested command when you trigger the palette from the pattern editor

I've put up a follow-up PR for this over in https://github.com/WordPress/gutenberg/pull/55332

**Comment by richtabor** [comment]
Closed via https://github.com/WordPress/gutenberg/pull/55332.
