### ISSUE TITLE
Gutenberg release - 16.3

### ISSUE THREAD

**Issue by mburridge** [WordPress/gutenberg#52684]
This issue is to provide visibility on the progress of the release process of Gutenberg 16.3 and to centralize any conversations about it. The ultimate goal of this issue is to keep the reference of the steps, resources, work, and conversations about this release so it can be helpful for the next contributors releasing a new Gutenberg version.

-   Gutenberg version to release: 16.3 ([milestone](https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+milestone%3A%22Gutenberg+16.3%22+is%3Aclosed))
-   Release Manager (a.k.a. Release Lead): @mburridge 
-   Release Date 16.3 RC: 19 July
-   Release Date 16.3: 26 July
-   Previous version change log (as a reference): [16.2](https://github.com/WordPress/gutenberg/releases/tag/v16.2.0)

## Resources

-  📖 Read: [Gutenberg Release Process](https://developer.wordpress.org/block-editor/contributors/code/release/)
-  📖 Read: [Leading a Gutenberg Plugin Release](https://codep2.wordpress.com/2021/07/22/leading-a-gutenberg-plugin-release/)
-  📽 Watch: [Gutenberg Plugin: New Release Workflow](https://www.youtube.com/watch?v=TnSgJd3zpJY)
-  📽 Watch: [Creating the Gutenberg plugin v12.0 Release Candidate](https://www.youtube.com/watch?v=FLkLHKecxWg)
-  📽 Watch: [Gutenberg plugin v12.0.0 Release Party!](https://www.youtube.com/watch?v=4SDtpVPDsLc)

### RC Day - Wednesday, July 19

-   [ ] _Optional:_ Attend `#core-editor` meeting (14:00UTC)
-   [x] Post a message in `#core-editor` channel to let folks know you are starting the RC release process
-   [x] Organize and Label PRs on the relevant milestone
-   [x] Start the release process by triggering the `rc` [workflow](https://developer.wordpress.org/block-editor/contributors/code/release/#running-workflow)
-   [x] [Update the created Draft Release accordingly](https://developer.wordpress.org/block-editor/contributors/code/release/#view-the-release-draft)
-   [x] [Curate the changelog](https://developer.wordpress.org/block-editor/contributors/code/release/#1-curating-the-changelog) before publishing
-   [x] Publish Release
-   [x] Announce in `#core-editor` channel that RC1 has been released and is ready for testing
-   [x] Ping any other relevant channels announcing that the RC is available (e.g. A8c Slack `#gutenberg`)
-   [x] Create Draft of Release post on Make Core blog _(initial draft in [Google doc](https://docs.google.com/document/d/1HVGWEWqtBtNsxqZH-ZeUoN-A1T8xxKRrCdQEgQe1Abw/edit))_

### Between RC and Release

-   [x] Post a reminder in #core-editor for backporting PRs to RC (~Label Backport to Gutenberg RC)
-   [x] If there are any PRs marked as [Backport to RC](https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+label%3A%22Backport+to+Gutenberg+RC%22+is%3Aclosed), run the [cherry-pick command to apply them](https://developer.wordpress.org/block-editor/contributors/code/release/auto-cherry-picking/#how-can-i-use-it-for-a-gutenberg-plugin-release) to the release branch. **This needs to be run locally**
-   [x] [Draft Release Post Highlights and Change Log](https://docs.google.com/document/d/1D-MTOCmL9eMlP9TDTXqlzuKVOg_ghCPm9_whHFViqMk/edit)
-   [x] Get assets from [Design Team](https://make.wordpress.org/design/) for the post
-   [ ] Reach out to Highlight Authors to draft sections (if necessary)

### Release Day - Wednesday, July 26

-   [x] Post a message in `#core-editor` channel to let folks know you are starting the release process
-   [x] Start the release process by triggering the `stable` [workflow](https://developer.wordpress.org/block-editor/contributors/code/release/#running-workflow)
-   [x] Update the created Draft Release accordingly. Typically by copy/pasting the last RC release notes and add any changes/updates as needed.
-   [x] Publish Release
-   [x] Trigger the update to the plugin directory. _(Get approval from a member of [Gutenberg Release team](https://github.com/orgs/WordPress/teams/gutenberg-release/members) if necessary)_
-   [x] Announce in `#core-editor` channel that the plugin has been released
-   [x] Reach out to other contributors to help get the post reviewed
-   [ ] Publish Release post on Make Core blog

**Comment by peterwilsoncc** [comment]
@mburridge In ticket #46110 I've restored the nux package to `wp/6.2`, `wp/6.3` and `trunk` as its removal was causing the syncing of packages to the WordPress Develop repo to fail. The PR for trunk was #52455.

The WP 6.3 branch is using the version range 7.1.x, so when you are publishing packages for the next GB plugin release, can you please ensure it ends up using 7.2.x or 8.x.x as appropriate.

I think the bumping script should automatically move it to 7.2.x but it would be great if you could confirm.

**Comment by mburridge** [comment]
@peterwilsoncc It's using 8.0.0 - https://github.com/WordPress/gutenberg/blob/release/16.3/packages/nux/package.json

**Comment by mburridge** [comment]
- [16.3 release](https://github.com/WordPress/gutenberg/releases/tag/v16.3.0)
- [Release notes](https://make.wordpress.org/core/2023/07/26/whats-new-in-gutenberg-16-3-26-july/)
