### ISSUE TITLE
Site Editor: Pressing the back button repeats the movement between All Template Parts page and Patterns page

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#52690]
### Description

I have only found one condition of occurrence, but I have found a case where I cannot return to the admin page by pressing the back button when I have moved pages in a specific order.

### Step-by-step reproduction instructions

Below is one procedure I found.

1. Access Appearance > Editor
2. Click the canvas area
3. Select the Header template part
4. Click "Edit" button
5. Click on the logo button in the top left corner
6. It should open the template parts view mode
7. Click the back button
8. It should take you to All Template Parts page
9. Click the back button
10. It should take you to Patterns page
11. Click the back button
12. It should take you back to the All Template Parts page, not the admin page.
13. Steps 9 through 12 should repeat endlessly.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/7e5bb662-2f04-423a-8490-da10e4cc0a11

### Environment info

- WordPress version: 6.3-beta4-56247
- Gutenberg version: 16.2.1 (trunk)
- Browser: Chrome, Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
This seems to be related to: https://github.com/WordPress/gutenberg/pull/52910 Can you retest with that PR?

**Comment by aaronrobertshaw** [comment]
I can't replicate the issue following the steps here on trunk. I believe this was fixed by https://github.com/WordPress/gutenberg/pull/52910. 

Are you happy to close this @t-hamano?

**Comment by noisysocks** [comment]
Yeah fixed by https://github.com/WordPress/gutenberg/pull/52910.
