### ISSUE TITLE
CSS `:has()` is not supported in Firefox yet

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#52699]
## What problem does this address?

CSS `:has()` is [not supported in Firefox](https://caniuse.com/css-has) yet, meaning that any [usage in our codebase](https://github.com/search?q=repo%3AWordPress%2Fgutenberg+%22%3Ahas%22+NOT+language%3APHP+NOT+language%3AJSON+NOT+language%3AJava&type=code) will not work in Firefox.

## What is your proposed solution?

Remove and avoid usage of `:has()` until Firefox supports it.

**Comment by strarsis** [comment]
There is a polyfill for `:has` (also for Firefox): https://www.npmjs.com/package/css-has-pseudo

But this polyfill adds more CSS and requires a JavaScript runtime. On the other hand, it is a drop-in solution, 
which can be easily added and later removed, when Firefox `:has` support has finally arrived.

**Comment by skorasaurus** [comment]
Firefox devs [are planning to fully support :has](https://connect.mozilla.org/t5/ideas/when-is-has-css-selector-going-to-be-fully-implemented-in/idi-p/23794/page/2#comments) in 2023

**Comment by ciampo** [comment]
Firefox 121, which adds support for the `:has` selector, should be released on the 19th December 2023. How about that for an early Christmas gift?

**Comment by mirka** [comment]
Firefox 121 has shipped 🚀
