### ISSUE TITLE
Footnotes don't work on nested content

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#52703]
### Description

Adding a footnote to paragraph or heading blocks that are nested inside of parent blocks does not work.  An asterisk is added next to the content, and a unique footnote is not created at the bottom of the post.

### Step-by-step reproduction instructions

1. Create a new post
2. Add text inside of a group block.
3. Highlight a portion of this text, and use the inline tool to add a footnote.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/27249804/5ee43158-f9ee-4f35-99ff-b5e10bbe5267

### Environment info

- Gutenberg 16.2.1
- WordPress 6.2.2
- Tested with Theme TT3, replicated across multiple themes

Originally reported here: https://github.com/Automattic/wp-calypso/issues/79384

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 
Thanks for reporting. 
This was just fixed and merged into the trunk of Gutenberg a few hours ago - https://github.com/WordPress/gutenberg/pull/52682 
The fix should be included in WP 6.3 (also reported at https://github.com/WordPress/gutenberg/issues/52628)

**Comment by cuemarie** [comment]
Thanks so much!
