### ISSUE TITLE
Inline HTML in Paragraph Block 

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#5270]
## Issue Overview

The block validation which fixes missing paragraph tags for content edited externally does not handle inline HTML. If there is inline HTML such as a link, or strong tag, the brackets get converted to &lt; and &gt; and display as `<strong>bold text</strong>`

## Steps to Reproduce (for bugs)
1. Create a new post with a paragraph and highlight and bold a portion of text.

2. To simulate the post being edited externally, switch to Code Editor and remove the `<p>` tags. This can happen if a post is edited externally due to autop/removep functions in WP.

3. Switch back to Visual Editor and the `<strong>` tags will be visible as plain text.

**Comment by Ipstenu** [comment]
You don’t need to switch back and forth.

Make it bold and then save the post and exit. Go back in. It looks fine but if you post, it shows the html. I had this happen on two scheduled post.

**Comment by mcsf** [comment]
I believe this was introduced in #4874 (cc @aduth). In a gist:

- With those changes, a Paragraph block that's missing `<p>` tags is no longer treated as a mere invalid block, but rather as a "supported" invalid block, in the sense that p-less Paragraphs are in a deprecated format for which the block offers a migration plan:

https://github.com/WordPress/gutenberg/blob/8de8b3c5bf031eab5c4390a77de74268bd750b99/blocks/library/paragraph/index.js#L259-L277

However, `attributes.content` is HTML, but in the migration it is treated as text, thus the rendering of the HTML tags in Visual.

- Prior to that change, a user would see the regular validation dialog. There, selecting option "Attempt to Fix" yields the same result as now (i.e. rich formatting leaked as text), but choosing "Convert to Classic" then "Convert to Blocks" yields the expected formatted content.

- @aduth, what potential issues arise if `migrate` assumes it's handling HTML? The following quick change fixes the issue for me:

```diff
diff --git a/blocks/library/paragraph/index.js b/blocks/library/paragraph/index.js
index f31fa3d1..aeafcf65 100644
--- a/blocks/library/paragraph/index.js
+++ b/blocks/library/paragraph/index.js
@@ -7,7 +7,7 @@ import classnames from 'classnames';
  * WordPress dependencies
  */
 import { __ } from '@wordpress/i18n';
-import { concatChildren, Component } from '@wordpress/element';
+import { concatChildren, Component, RawHTML } from '@wordpress/element';
 import {
 	Autocomplete,
 	PanelBody,
@@ -290,7 +290,7 @@ export const settings = {
 			migrate( attributes ) {
 				return {
 					...attributes,
-					content: [ attributes.content ],
+					content: [ <RawHTML>{ attributes.content }</RawHTML> ],
 				};
 			},
 		},
```
