### ISSUE TITLE
Separator block thickness can't be changed below 2px which seems to be hardcoded into WP.

### ISSUE THREAD

**Issue by Ren2049** [WordPress/gutenberg#52718]
### Description

This so frustrating because I can't make the separator the same thickness as my card borders, not with global CSS or directly editing the values in the browser like you can see in the first video. 

What you can also see is that 2px is the thinnest possible value (the crosshair in the color picker is exactly 1px). With 2px lines and borders (button outlines dont count) it's impossible to create elegant designs.

In the other video I'm trying to target it through global CSS but when it's targeted the separator just disappears.

It's a fresh install of 6.2.2 (create block theme -> blank theme) with some style modifications in global styles through the editor, a query loop layout tweak also done entirely in the editor and a placeholder featured image.

### Step-by-step reproduction instructions

Try to change the separator width somehow, or use the methods you see in the videos.

### Screenshots, screen recording, code snippet

The color picker crosshair is exactly 1px! The separator is definetely double of that, 2px!
https://github.com/WordPress/gutenberg/assets/133038357/820cd14c-a0f3-483f-8169-cff2eea44dd0

Why does it disappear entirely when targeted?
https://github.com/WordPress/gutenberg/assets/133038357/95c0e329-013c-4028-839e-122a0c1f8076

### Environment info

Mac, Firefox, 6.2.2, no Gutenberg, create block theme -> blank theme (the only active plugin).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ndiego** [comment]
Hi @Ren2049, thanks for reporting. The Separator block is an `<hr>`, so when `border: 1px solid` is applied, the border is applied on all sides, including the top and bottom. This is why it appears as `2px`. If you update the CSS to the following, it will work as you expect. 

```
.wp-block-separator {
    border: 0;
    border-top: 1px solid;
} 
```

Also, the reason `border: 1px !important` causes the Separator to disappear is that you need to add `solid` or another border style. 

Hopefully, that's helpful, and please let me know if I can answer any additional questions.

**Comment by Ren2049** [comment]
@ndiego thanks for the solution!

I have a question:

In [this post about server-side filters](https://developer.wordpress.org/news/2023/07/how-to-modify-theme-json-data-using-server-side-filters/) you show how to remove color tokens. Does it make sense to use the code to add additional global color tokens e.g. for borders or a second background/surface?

Is it as simple as adding just another sub-array to the palette array, calling it in theme.json and applying the border-color property?

**Comment by ndiego** [comment]
> Is it as simple as adding just another sub-array to the palette array, calling it in theme.json and applying the border-color property?

As far as I am aware, the palette array does not support sub-arrays. That said, you can use the [`custom`](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#custom) section of theme.json to specify your own variables.
