### ISSUE TITLE
Nightlies don't see RC's.

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#52738]
Today, I was in the release party of WP 6.3 RC1. 
When set my website to "Nightly's"... I always updated to WP 6.3 Beta 4 .... When I set the option to "Release Candidates", I could help test... 

But nightly's can be the latest RC too right? It's the latest version after all. Or was I too impatient?

**Comment by Mamaduka** [comment]
Hi, @NekoJonez

This would be an issue report for the Beta Tester plugin, as it's maintained in a separate repo - https://github.com/afragen/wordpress-beta-tester.

**Comment by NekoJonez** [comment]
Ah shoot. I thought I was in the correct repo. My bad
