### ISSUE TITLE
Site Browser > Library: General Template Parts not showing

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#52754]
### Description

In the Site Browser > Library the section for 'General' template parts shows a count of the number of template parts - but does not show thumbnails/previews of them when selected.

By comparison the 'General' template parts _do_ show in the full template part list.

### Step-by-step reproduction instructions

1. Open the Site Editor and go to Library
2. With the TT3 theme active it should show there are 2 'General' template parts - click on that item.
3. Check the thumbnail list of template parts that shows on the right.

### Screenshots, screen recording, code snippet

<img width="1700" alt="Screenshot 2023-07-19 at 8 34 27 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/d7082ad6-c09d-4685-af34-1a37b499ec36">

Default state - showing count of TT3's general template parts, but no previews.

<img width="1528" alt="Screenshot 2023-07-19 at 8 35 41 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/47f6ea46-7bbb-494d-8d0b-67576a9e3110">

Showing a count of '3' after I added my own custom 'General' template part

<img width="1280" alt="Screenshot 2023-07-19 at 8 38 29 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/f23c7f81-3571-451e-893f-7f71888c2cb4">

'All Template Parts' view - showing all 3 'general' template parts

### Environment info

WP 6.3RC1
No plugins
TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
#52747 may resolve this issue. We may want to test it again after #52747 is merged.

**Comment by glendaviesnz** [comment]
This was fixed by https://github.com/WordPress/gutenberg/pull/52747 so closing.

**Comment by jordesign** [comment]
Woohoo - thanks @glendaviesnz
