### ISSUE TITLE
InnerBlocks layouts "content"?

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#5275]
Hi,

I'm trying out the nested blocks and seems like the attributes available are missing `content`. I'm only seeing `name` `label` and `icon`. Anyway I can add default content? Thanks!

**Comment by aduth** [comment]
Is this for a custom implementation of a nested block?

`InnerBlocks` does not currently support defining a predefined set of blocks, but it is slated as a feature.

Related: #2995 (https://github.com/WordPress/gutenberg/issues/2995#issuecomment-336108393), #3745 (https://github.com/WordPress/gutenberg/pull/3745#issuecomment-349032768)

**Comment by aduth** [comment]
Closing in favor of #5448 for discussion of technical implementation.
