### ISSUE TITLE
Add control for renaming a page in the Site Editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52763]
Sometimes a page template may not include a Title block. In this scenario there's no way to update the page title in the site editor.

For potential solutions we can look at existing patterns. Templates can be renamed via their detail panels like so:

<img width="485" alt="Screenshot 2023-07-19 at 15 10 52" src="https://github.com/WordPress/gutenberg/assets/846565/32dc77a0-4817-4349-bfcb-3937e4c5f6d4">

This could work well for pages too, but it would be good to include a way to edit the title in the full screen editor too. Whatever solution is found for that context could be applied to custom templates as well, as they also cannot be renamed currently.

Finally it may be reasonable to surface a rename action in the Command Palette.

**Comment by jasmussen** [comment]
I would think that we need a generic solution for changing page/post titles when there isn't a title block, one that also works for "asides". I feel like there's a separate issue for this that would be good to connect up with this one? The details view doesn't feel like the ideal place for this, IMO.

**Comment by jameskoster** [comment]
> The details view doesn't feel like the ideal place for this

How come? To me it seems perfectly reasonable to edit the title here, similar to how you can edit a post title in the list view. Forcing users into the editor feels a bit tedious.

That's not to say you can't edit the title in the editor too. I think we need both.

**Comment by jasmussen** [comment]
I wouldn't mind that this interface was an additional way of changing the title, and inline renaming here comes to mind. Though I would still instinctually think of the full editor having an interface for it first, no?

**Comment by jameskoster** [comment]
Inline editing can work. Though initially it probably makes sense to re-use the existing pattern we have in place for templates, template parts, patterns, then refine holistically afterwards?

> Though I would still instinctually think of the full editor having an interface for it first, no?

To be honest I see them as equal priority. It would be a bit strange imo if you can change the title in one but not the other.

**Comment by jasmussen** [comment]
Can we add an item in the Summary panel if the title block is not present?

<img width="325" alt="Screenshot 2023-09-13 at 13 40 36" src="https://github.com/WordPress/gutenberg/assets/1204802/605e9f5e-5b1a-42f3-9fd7-7ba63686cd4a">

Title > [title button which opens a naming modal]?

**Comment by jameskoster** [comment]
Yup, I think that can work for the editor, and the pattern we have for templates/patterns can work for the details panel.

<img width="279" alt="Screenshot 2023-09-13 at 12 50 35" src="https://github.com/WordPress/gutenberg/assets/846565/9d0f9464-d67c-4dd7-bad7-7ba75d9c472c">
<img width="915" alt="Screenshot 2023-09-13 at 12 51 05" src="https://github.com/WordPress/gutenberg/assets/846565/f692f0f5-6a4c-4155-8e2f-65fcd240afbd">

**Comment by jameskoster** [comment]
Alternatively we might place the affordance closer to the title card:

<img width="280" alt="Screenshot 2023-09-13 at 12 53 33" src="https://github.com/WordPress/gutenberg/assets/846565/5cc9e99a-7a54-40c8-99ba-886ff7cb3717">

But given [discussion around the edit button in the details panel](https://github.com/WordPress/gutenberg/pull/54190), perhaps the Summary panel is better.

**Comment by jameskoster** [comment]
Connecting a dot here with post formats: A modal invoked from the Summary panel could house an option to toggle frontend visibility of the title:

<img width="1262" alt="Screenshot 2023-09-14 at 10 32 00" src="https://github.com/WordPress/gutenberg/assets/846565/6bea83ad-1e88-4358-9571-54347b02e135">

**Comment by ellenbauer** [comment]
As there could potentially be more actions for Templates would it maybe be an idea to add the Vertical 3 dots actions icon and a list of actions including edit with edit icon? 

Similar to something I've seen in Notion:
<img width="257" alt="Screenshot 2023-09-18 at 8 19 54 PM" src="https://github.com/WordPress/gutenberg/assets/17613630/bd8464c4-a401-4d19-974b-a7bf8a4e2e02">

I have to admit, I also have doubts that the Sidebar icon would be easier to understand for users compared to the current Edit icon.

**Comment by jameskoster** [comment]
@ellenbauer you mean something like this?

<img width="1407" alt="Screenshot 2023-09-19 at 11 29 42" src="https://github.com/WordPress/gutenberg/assets/846565/db02a9ab-8136-45ad-a893-5ec8991bf070">

I think that could work, and the consistency with the details panel in the dark material makes sense. Here's that concept applied to other contexts:

<img width="1476" alt="Screenshot 2023-09-19 at 11 43 36" src="https://github.com/WordPress/gutenberg/assets/846565/9bbbcdcd-d358-4cef-b0e2-8a36c425d586">

**Comment by SaxonF** [comment]
I like that. Still not sure about a "hide title" setting but that's a separate conversation :) . I think we're ready to move forward with this one.

**Comment by SaxonF** [comment]
PR [here](https://github.com/WordPress/gutenberg/pull/54648)

**Comment by scruffian** [comment]
The attached PR looks good, but I also think that the original idea is good - we saw a user looking for a rename option beneath the contextual menu in the Site View.

**Comment by jameskoster** [comment]
Agreed, I don't think it should be necessary to open the full screen editor just to change a page title.

**Comment by annezazu** [comment]
Removing this from the 6.5 editor board due to lack of activity around the PR. Happy to add back in if work picks back up!

**Comment by jameskoster** [comment]
> Site Editor: There's no way to change page title if the template does not include a Title block

This issue is actually resolved after all the post/site editor unification. If you toggle the template preview _off_, it's possible to add a title.

I still think we should enable users to edit the title from the details panel, and from data views, but those can be tackled separately.

**Comment by richtabor** [comment]
> This issue is actually resolved after all the post/site editor unification. If you toggle the template preview off, it's possible to add a title.

It's less than ideal though; I don't know that most folks know what turning off a template preview means. I like the approach from PR https://github.com/WordPress/gutenberg/pull/54648. We already have a UX pattern for using the vertical ellipsis in that area.

**Comment by jameskoster** [comment]
Yup that approach is aligned with the work in https://github.com/WordPress/gutenberg/issues/59689. Unsure why it never got merged 🤔

**Comment by aaronrobertshaw** [comment]
Marking this as complete as https://github.com/WordPress/gutenberg/pull/60230 and https://github.com/WordPress/gutenberg/pull/60232 have been merged.

A command to rename pages is also currently [in the pipeline](https://github.com/WordPress/gutenberg/pull/60231) to address https://github.com/WordPress/gutenberg/issues/60089
