### ISSUE TITLE
Enforce valid function names in `packages/block-library/*/src/index.php` files

### ISSUE THREAD

**Issue by anton-vlasenko** [WordPress/gutenberg#52769]
## What problem does this address?
Follow-up from https://github.com/WordPress/gutenberg/pull/52696.
Functions with `gutenberg_` prefixes should not be permitted in the `block-library` package.

Please see:

1. https://github.com/WordPress/gutenberg/pull/51978
2. https://github.com/WordPress/gutenberg/pull/52696#pullrequestreview-1536235865
3. https://github.com/WordPress/gutenberg/issues/44151#issuecomment-1613503035

Props:  @tellthemachines, @ockham

## What is your proposed solution?
After the merge of https://github.com/WordPress/gutenberg/pull/52696, a new phpcs sniff should be implemented to check that these functions do not exist in the `block-library` package.

**Comment by anton-vlasenko** [comment]
I'm working on a patch for this issue.

**Comment by gziolo** [comment]
Excellent initiative! Should we enforce that all function names start with consistent prefix patterns based on what we have today?

**Comment by anton-vlasenko** [comment]
> Excellent initiative! Should we enforce that all function names start with consistent prefix patterns based on what we have today?

@gziolo Sorry, I'm not sure I understand. Are you referring to the `(G|g)utenberg_` prefix? Or some other prefix?
And where should this enforcement take place? Throughout the entire project or in specific folders?

**Comment by gziolo** [comment]
I'm talking about the same scope as this issue proposes - `/packages/block-library/src/*/index.php`.

Example for the Navigation block:

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation/index.php

<img width="419" alt="Screenshot 2023-08-08 at 14 39 13" src="https://github.com/WordPress/gutenberg/assets/699132/fbbc91b9-1871-4eb5-a001-a8e45d137163">

Functions start with:

- `block_core_navigation_`
- `render_block_core_navigation_`
- `register_block_core_navigation_`

_Aside: there is one function starting with `gutenberg_`, which would get detected if the linter rule described in this issue existed._

Technically speaking `_navigation_` part comes from the folder name, but if that is too difficult to handle with a linting rule, it should be fine to enforce that function names can start with:

- `block_core_`
- `render_block_core_`
- `register_block_core_`

Everything else shouldn't be allowed.

**Comment by anton-vlasenko** [comment]
Thank you for providing more details in your comment, @gziolo.
Your input is much appreciated.

> Technically speaking _navigation_ part comes from the folder name, but if that is too difficult to handle with a linting rule, it should be fine to enforce that function names can start with.

Given that the linting rule I'm working on pertains specifically to Gutenberg, I don't foresee any challenges in customizing it to check if a function's name aligns with the naming rule you described, which includes the `_navigation_` part (as well as other folder/file names).

I think I will need your help with testing the linting rule when it's ready.

**Comment by anton-vlasenko** [comment]
@gziolo I've implemented a draft version of the linting rule.
Please have a look at these code style errors: https://github.com/WordPress/gutenberg/pull/53438/files#diff-92dc6950bcaf54290625664019ea23b023cb3f156de19586612c8d3e3cf52adc
Should we just ignore these files/functions ?

**Comment by gziolo** [comment]
> @gziolo I've implemented a draft version of the linting rule.
> Please have a look at these code style errors: https://github.com/WordPress/gutenberg/pull/53438/files#diff-92dc6950bcaf54290625664019ea23b023cb3f156de19586612c8d3e3cf52adc
> Should we just ignore these files/functions ?

It's fine to ignore all these functions that don't follow patterns. We can't rename them anymore unless we keep all the old names as deprecated aliases calling new function makes that use a proper prefix. I don't think it's worth the effort if a simple code comment would allow us to achieve the same goal. The nice part is that moving forward, the developers will see hints on how to name those functions. This is great work. Thank you so much for coming up with a simple and clean solution so quickly.
