### ISSUE TITLE
Block Theme Previews: Make it clearer what theme you're previewing

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/gutenberg#52772]
## What problem does this address?

With the new block theme preview feature, clicking "Live Preview" at Appearance > Themes brings you into the Site Editor, where you see the words "Previewing [ThemeName]: Design" at the top left. 

Example for the Blockbase theme:

<img width="1484" alt="Index_‹_Template_Part_‹_Editor_‹_LearnWP_—_WordPress" src="https://github.com/WordPress/gutenberg/assets/7662449/9f75246c-5d86-411f-bf6a-22990e14dc77">

Once you click into the area on the right, you lose that frame of reference. While you do do see an "Activate" button at the top right, there's no indication of **which** theme you'd be activating.  If you're in the process of previewing many themes, you may already have lost track of which one you're previewing at the moment, and may want to double-check before activating it. 

Example:

<img width="1509" alt="Index_‹_Template_Part_‹_Editor_‹_LearnWP_—_WordPress" src="https://github.com/WordPress/gutenberg/assets/7662449/e04596a7-ab10-462d-8ee5-77b24a4a9ad2">

## What is your proposed solution?

Include the **theme name** within the Activate button, or on the hover text, or both. 

Example:

<img width="344" alt="Index_‹_Template_Part_‹_Editor_‹_LearnWP_—_WordPress" src="https://github.com/WordPress/gutenberg/assets/7662449/9ef6a906-0716-4e5b-b927-afda50da8ca8">

### Environment info

- 6.3-RC1
- Gutenberg plugin not active
- No other plugins active other than WordPress Beta Tester

**Comment by arthur791004** [comment]
Proposing https://github.com/WordPress/gutenberg/pull/55752 to resolve this issue 🙂
