### ISSUE TITLE
Columns block: difficult to exit 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#52774]
Similar to https://github.com/WordPress/gutenberg/issues/52773 and originally noted here https://github.com/WordPress/gutenberg/discussions/50129, the columns block is difficult to exit with enter:

https://github.com/WordPress/gutenberg/assets/26996883/e71b6b41-91a0-442c-854d-2389c60e6c8d

The only way to exit is through insert before/after or to select the parent and find the in between inserter. This feels overly painful!

**Comment by Mamaduka** [comment]
The Group and Quote block support exists on Enter at the last block (it should be an empty paragraph). This is enabled via the `__experimentalOnEnter` supports flag. See #39911.

Currently, the method doesn't support nested blocks like Columns. When they're supported, we can enable it here.

Cc @oandregal.

**Comment by oandregal** [comment]
cc @ellatrix as she has the most context about the current state of that work.
