### ISSUE TITLE
Site Editor: 'Manage all' links missing on smaller screen and inconsistent

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#52794]
### Description

In the Site editor navigator screens, some items are placed in a 'footer', fixed at the bottom of the navigator.

Typically, these are the various 'Manage all' links that give access either to the related 'classic' WP admin pages or to som special pages in the editor. Additionally, in the Pages screen there are a few more links to some page templates.

Manage all pages + page templates
Manage all of my patterns
Manage all templates
Manage all template parts

There are two problems with these links on smaller screens:

1
Manage all of my patterns, templates, and templates part are not rendered on smaller screens.  Quickly looking at the code, turns out this is a deliberate choice. See for example:

https://github.com/WordPress/gutenberg/blob/6d22c92b664927d0894cec816adfb07769af8688/packages/edit-site/src/components/sidebar-navigation-screen-templates/index.js#L97-L103

I'm not sure what the reasoning behind not rendering these links on smaller screen is, but seems to me it's not ideal. As far as I can tell, there's no other way to access these admin pages. As a user, how I do I access these admin pages on smaller screens?

2
There is some inconsistency in the implementation. While Manage all of my patterns, templates, and templates part are not rendered on smaller screens, Manage all pages and the links to page templates are still rendered. I'm not sure this contributes to a clear, consistent UI and I\d tend to think it introduces a confusing experience for users.

Screenshot:

<img width="1300" alt="Screenshot 2023-07-20 at 14 00 33" src="https://github.com/WordPress/gutenberg/assets/1682452/db15a97b-2dd9-4738-91a5-d00672f65e75">

Overall, I'm not sure that hiding functionalities on smaller screens is the best option. That was the trend in the first days of the responsive design era about 10 years ago and it proved to not be ideal.

### Step-by-step reproduction instructions

- Emulate a smaller screen via your dev tools, for example an iPad Mini (768 x 1024).
- Go to Site Editor > Design > Pages
- Observe the footer in the navigator panel is visible and the 'Manage all pages' plus the links to page templates are visible.
- Go to Site Editor > Design > Patterns
- Observe the navigator footer is not visible.
- Go to Site Editor > Design > Templates.
- Observe the navigator footer is not visible.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Probably a duplicate of #49769.

**Comment by afercia** [comment]
> Probably a duplicate of #49769.

Yeah, sort of. Thank you. I'm going to close this one and integrate https://github.com/WordPress/gutenberg/issues/49769. with the. missing information.

**Comment by Mamaduka** [comment]
Thanks, @afercia!
