### ISSUE TITLE
Command Palette: add command for toggling on/off distraction free mode

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#52806]
Noticed that there's no command for distraction free mode. With that feature being added to both the Site Editor and Post Editor, I think we should include it! I'm not sure if we can add to 6.3 but adding just in case.

**Comment by annezazu** [comment]
Somewhat related to this work: https://github.com/WordPress/gutenberg/pull/52509

**Comment by andrewserong** [comment]
Good idea! I'm not sure if it's too late in the cycle to add it in for 6.3, but I've opened a PR for it in case we can over in https://github.com/WordPress/gutenberg/pull/52868 🙂
