### ISSUE TITLE
What's the license for Gutenberg blocks

### ISSUE THREAD

**Issue by caraya** [WordPress/gutenberg#5281]
What's the licensing for Gutenberg blocks? Will it be ok to publish blocks to the Wordpress Marketplace?

Since #2298 was raised, React moved to the MIT license. This is not GPL and, although they are compatible, Automattic will not accept dual licensed code in the Marketplace for either themes or plugins. Matt explained the situation in [There is No Such Thing as a Split License](https://ma.tt/2015/07/licenses-going-dutch/)

How does the inclusion of React (and the many licenses included in its dependencies) affect this position? If people start creating blocks will the restrictions for non-GPL code be lifted in light of Matt's strong stance on the issue?

**Comment by pento** [comment]
Thank you for the question, @caraya!

Gutenberg [is licensed](https://github.com/WordPress/gutenberg/blob/master/LICENSE.md) under the GPLv2+, the same as WordPress Core. The [MIT license is considered GPL compatible](https://www.gnu.org/licenses/license-list.en.html#Expat) by the Free Software Foundation, which allows us to use React in Gutenberg.

In Gutenberg, blocks are programmed in a similar way to widgets or other WordPress plugins, they are directly linked to WordPress' APIs. With that in mind, the [advice we received from the Software Freedom Law Center](https://wordpress.org/news/2009/07/themes-are-gpl-too/) years ago also applies to the JavaScript that you write to create blocks: the code is directly linked to WordPress' (or Gutenberg's) GPLv2-licensed JavaScript, so must have a GPLv2-compatible license.

And so, the overall position of the WordPress project remains unchanged: [plugins or themes hosted on the WordPress.org directories must be GPLv2 compatible](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#1-plugins-must-be-compatible-with-the-gnu-general-public-license-v2).
