### ISSUE TITLE
Pullquote Block: Font size control adding padding but not affecting actual font size

### ISSUE THREAD

**Issue by pitamdey** [WordPress/gutenberg#52830]
### Description

In the Typography Section of the Pullquote block the size attribute setting is not working as expected. It is giving the padding on top and bottom instead of increasing/decreasing the font size.

### Step-by-step reproduction instructions

1. Add Pullquote Block
2.Open Typography section from the Inspector Controls
3.Tried to change the Size

### Screenshots, screen recording, code snippet

Video : https://www.loom.com/share/53b069c1cd564a54ad01ea0cef8a8c17?sid=3a6b243e-f66e-40f8-9baa-3804f9a9c54a

**Comment by jordesign** [comment]
Thanks for reporting @pitamdey. I'm not able to recreate this _exactly_ in my testing.

When I test - the font size does change, but I agree that the top and padding does _also_ change relative to the font size.

A couple of things to double check:

* Did you type the text in Pullquote in directly, or did you paste it in from another source? Is it possible there's some inline code/styles that have come in and are keeping the font small?

It's also possible this may be a plugin or theme conflict. Please attempt to disable all plugins, and use one of the default (Twenty*) themes. If the problem goes away, enable them one by one to identify the source of your troubles.

If you can install plugins, install and activate "Health Check": <a href="https://wordpress.org/plugins/health-check/">https://wordpress.org/plugins/health-check/</a>  
It will add some additional features under the menu item under Tools > Site Health.
On its troubleshooting tab, you can Enable Troubleshooting Mode. This will disable all plugins, switch to a standard WordPress theme (if available), allow you to turn your plugins on and off and switch between themes, &lt;strong>without affecting normal visitors to your site&lt;/strong>. This allows you to test for various compatibility issues. 

There’s a more detailed description about how to use the Health Check plugin and its Troubleshooting Mode at <a href="https://make.wordpress.org/support/handbook/appendix/troubleshooting-using-the-health-check/">https://make.wordpress.org/support/handbook/appendix/troubleshooting-using-the-health-check/</a>

**Comment by pitamdey** [comment]
Hi @jordesign 
I have tried this by removing the default padding from the PullQuote 
i.e. `.wp-block-pullquote {
    /* padding: 3em 0; */
}`
and now it is working as expected.
Can you please check on your end?

**Comment by jordesign** [comment]
Hi @pitamdey  - that does make a difference for me. But that behaviour is as expected.

The `em` value is based on the font size of the element - so as we make the font larger, it also impacts the padding above and below proportionally. If you change the padding to static value (like 36px) does that make a difference?

**Comment by jordesign** [comment]
Hi @pitamdey were you able to do any further testing on this as mentioned above?

**Comment by carolinan** [comment]
The intention is for the padding to change with the font size. If a user does not want the padding to change with the font size, they should replace the padding in the block setting.

Many themes override this default, but it is up to the theme creator.

Changing this to a value that does not change, like pixels, would change the design unexpectedly for many existing websites.

**Comment by t-hamano** [comment]
> The intention is for the padding to change with the font size.

I also agree with this. Many blocks use `em` units for padding and margin values. Font size does affect padding and margin, but I think this is expected behavior.

If you don't want this behavior, you can override it from the block sidebar.

I'd like to close this issue, but if I've missed anything, please feel free to comment.
