### ISSUE TITLE
Cover: Overlay opacity shouldn't jump to 50 after a image is inserted

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#52835]
### Description

I feel like I am often reverting opinionated settings. So also when you insert a picture into a cover: the overlay opacity always jumps back to 50. 
I am using the gradient tool to adjust the overlay (since I need two overlays - black in the background and a gradient to white at the bottom), which means that I mostly have the overlay on 100% anyways.

The opacity shouldn't jump to 50 after inserting a an image. It'd be fine to do this for the very first image that is inserted, but for the ones after that it's not ideal.

### Step-by-step reproduction instructions

1. Design your cover block
2. Insert a new image
3. Revert the overlay opacity value.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/17861443/51451c6a-78b3-43f9-a75f-b6b1491c775f

### Environment info

- WP 6.2.2
- GB 16.2.1
- custom theme

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hanneslsm** [comment]
By the way, the "color combination" warning is actually wrong and misleading here.
I think @richtabor has also created a ticket for this already some time ago, but I can't find it right now.

**Comment by richtabor** [comment]
> The opacity shouldn't jump to 50 after inserting a an image. It'd be find to do this for the very first image that is inserted..

This is my expectation as well. If there's an `dimRatio` set, then it should not change when an image is uploaded.

**Comment by apeatling** [comment]
I can't seem to reproduce this consistently with trunk. I triggered it to happen once, but all the other times I tried the opacity stayed at the previously set value. 🤔

**Comment by apeatling** [comment]
Actually I've just figured it out. It's only when you set the opacity back to 100.

**Comment by apeatling** [comment]
Fixed up in https://github.com/WordPress/gutenberg/pull/55422. @hanneslsm let me know if you come across any issues with the change.
