### ISSUE TITLE
When searching for a part, classic edit box pops up

### ISSUE THREAD

**Issue by lconnDNL** [WordPress/gutenberg#52846]
### Description

Since update to wp 6.2.2, when you search for a part, a classic edit box pops up. 

### Step-by-step reproduction instructions

1. Go to Pages
2. Edit any page
3. Click the toggle block inserter in the backend when editing a page (Plus Icon)
4. In the search input, search for a term
5. Wait a few seconds or start to scroll through the block results list and then the Classic Edit pop up overlay displays. This block has been added to the list of blocks if you X out of it.

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/140200955/74a1db0a-30ba-4083-b3b4-79de179cf43d)

### Environment info

WP Version 6.2.2 (was not happening with previous version. 
Gutenberg. 
Happening in Firefox, Edge, and Chrome. 
Windows 11 and macOS Ventura 13.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@lconnDNL, what version of the Gutenberg plugin are you using?

**Comment by lconnDNL** [comment]
Hi George – thanks for the follow up. Apologies if I’m being dense but I can’t find specfics on the Gutenberg version anywhere. The best I can find is the below which indicates we’re on version 14.2-15.1 because we’re on WP 6.2.2. If there’s a place I can get more specifics on the Gutenberg version, please let me know.
***@***.***

Elizabeth Conn
DNL OmniMedia, Inc.

Office: 845-266-6766 Ext. 7184
E-mail: ***@***.******@***.***>
Web: www.dnlomnimedia.com<http://www.dnlomnimedia.com/>
Blog: www.TeamDNL.com<http://www.teamdnl.com/>

***@***.***

**Comment by Mamaduka** [comment]
Thanks, @lconnDNL. This means you're using WP 6.2.2 without a Gutenberg plugin.

Do you have any other block plugins active? I'm not able to reproduce the issue when testing locally.

**Comment by lconnDNL** [comment]
Hi George –
We do have Meta Field Block installed but we deactivated and re-tried and the issue is still happening.

We also have custom blocks on the site.

Thanks,
Liz


Elizabeth Conn, Project Manager
DNL OmniMedia, Inc. | Tennessee

Office: 845-266-6766 Ext. 7184
E-mail: ***@***.******@***.***>
Web: www.dnlomnimedia.com<http://www.dnlomnimedia.com/>
Blog: www.TeamDNL.com<http://www.teamdnl.com/>

***@***.***

**Comment by lconnDNL** [comment]
Hi – You can close the case. We found the issue on our end. Thanks for your time!
Liz


Elizabeth Conn, Project Manager
DNL OmniMedia, Inc. | Tennessee

Office: 845-266-6766 Ext. 7184
E-mail: ***@***.******@***.***>
Web: www.dnlomnimedia.com<http://www.dnlomnimedia.com/>
Blog: www.TeamDNL.com<http://www.teamdnl.com/>

[A blue and black logo  Description automatically generated]

**Comment by Mamaduka** [comment]
Thanks for the update, @lconnDNL!
