### ISSUE TITLE
Version 16.2.1 causes errors in existing image blocks

### ISSUE THREAD

**Issue by genem80** [WordPress/gutenberg#52861]
### Description

We hadn’t done any editing on our WP site for a few weeks until 7/21/2023.  On every existing page we bring up to edit, existing images (that were previously loaded into an image block from the Media Library) show the following message: “This block contains unexpected or invalid content.” After hitting the “Attempt block recovery” button the image reverts to the way it was.  The images had been loaded into the Media Library using plugin EWW,
 
Deactivating the Gutenberg plugin solved the problem.  

### Step-by-step reproduction instructions

See web site  berkeleyandbeyond2.com

### Screenshots, screen recording, code snippet

Issue occurs when editing any page with images on site berkeleyandbeyond2.com

### Environment info

ver 16.2.1 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by glendaviesnz** [comment]
May be fixed by https://github.com/WordPress/gutenberg/pull/52822 & https://github.com/WordPress/gutenberg/pull/52853
