### ISSUE TITLE
Reusable Blocks are too narrow in the editor

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#52893]
### Description

If a reusable block is in the editor, it is constrained to the usual contentWidth. If the content inside it is e.g. aligned wide, the display in the editor is therefore markedly different to the output on the website.

### Step-by-step reproduction instructions

1. Add a wide group with some content.
2. Make the group a reusable block.
3. The block is no longer displayed as a wide block in the editor.

### Environment info

Tested in 6.2 and 6.3 RC1 with various themes, including Twenty Twenty Three.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by markhowellsmead** [comment]
Also, if I override the width of this block using `.wp-block-block.is-reusable { max-width: none !important;}`, the block is displayed at full-width, but the nested blocks inside it don't respond to wide/full settings.

**Comment by t-hamano** [comment]
Thanks for the report.

This issue has been reported several times in the past and seems to be most actively discussed in #8288. So let's close this issue and focus on #8288.
