### ISSUE TITLE
List view: Blocks jump the bottom of the list after some drag & drops

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#52919]
### Description

When quickly selecting blocks it can happen that you also move them a tiny little bit.
When doing so, sometimes it happens then that they then will reposition at the bottom of the list.
This happens to all kind of blocks.

cc @andrewserong 

### Step-by-step reproduction instructions

1. Drag and drop a block just a little bit
2. After some time (three clicks or so) the bug appears

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/17861443/77614cce-5c89-4dfb-9304-dec634c72b65

### Environment info

- WP 6.2.2
- GB 16.2.1
- Brave browser
- Custom theme

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Thanks for reporting and for the ping! I can reproduce this — it does seem strange as I can only get it to happen when clicking quickly as you mention. I wonder if there's a stale value within the `200ms` timeout for drag events or something like that. In any case, I'll look into this.

**Comment by andrewserong** [comment]
I think I've gotten to the bottom of what caused this. I've opened a fix in https://github.com/WordPress/gutenberg/pull/52959
