### ISSUE TITLE
Read theme.json files property 

### ISSUE THREAD

**Issue by abkarim** [WordPress/gutenberg#52925]
## What problem does this address?
I'm unable to read theme.json property from my plugin

## What is your proposed solution?
It should have a hook or something else

Please let me know if already a solution exists, I'm unable to find a solution

**Comment by t-hamano** [comment]
Hi @abkarim,

How about using [WP_Theme_JSON_Resolver::get_theme_data()](https://developer.wordpress.org/reference/classes/wp_theme_json_resolver/get_theme_data/)?

**Comment by abkarim** [comment]
I tried many things

now I'm using this

```php
   // Get the path to the active theme's directory
        $theme_directory = get_stylesheet_directory();

        $file_path = $theme_directory . "/theme.json";

        // Check if the file exists
        if (file_exists($file_path)) {
            // Read the file contents
            $file_contents = file_get_contents($file_path);

            self::$theme_json_data = json_decode($file_contents);
            return self::$theme_json_data;
        }

```
