### ISSUE TITLE
Unsynced patterns have 'synced purple' colorisation in title bar

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52923]
The purple accent color is reserved for communicating the synced nature of patterns. However it is currently being applied to _un_-synced patterns in the document title:

https://github.com/WordPress/gutenberg/assets/846565/794e41d0-8825-4fb8-882f-366d2a47709c

**Comment by richtabor** [comment]
Ouch, yea this is certainly confusing.
