### ISSUE TITLE
BlockControls handling with multiple editable elements that trigger a truthy isSelected 

### ISSUE THREAD

**Issue by xupaosso** [WordPress/gutenberg#5294]
## Issue Overview
When creating blocks with multiple editable elements that can trigger an isSelected state (e.g. RichText), the BlockControls will expand to include the editing controls for all the elements within that block with no identifying characteristics. A native block following this format is the Text Columns block

![screen shot 2018-02-27 at 1 35 37 pm](https://user-images.githubusercontent.com/586742/36753555-b69ca674-1bc3-11e8-8d96-b41335ef2327.png)
_Shown above: two sets of RichText editing controls - one for each column_

Are there plans to:
1) Set sub selected states for the individual blocks to trigger the BlockControls?
2) Create sub block groups that can have their own isSelected triggers?
3) Create some kind of identifier in the BlockControls UI to define which element is being affected?

**Comment by Emilybkk** [comment]
Was going to report this. It should show as only one is enough. Mine was like 3 column then 3 editing control.

**Comment by xupaosso** [comment]
I've had a chance to look into this more. This issue lies in the following code for the RichText element (blocks/rich-text/index.js):

`
{ isSelected &&
  <Fill name="Formatting.Toolbar">
    { ! inlineToolbar && formatToolbar }
  </Fill>
}
{ isSelected && inlineToolbar &&
  <div className="block-rich-text__inline-toolbar">
    { formatToolbar }
  </div>
}
`
the isSelected value is determined by the entire block state, and not by the individual RichText components. We need to find some way to determine if the node is selected or if the block is selected.

**Comment by youknowriad** [comment]
There's no issue in the RichText component itself, you can take a look at how we achieve this in the `quote` block for instance to pass an `isSelected` value true to only one RichText at a time

https://github.com/WordPress/gutenberg/blob/master/blocks/library/quote/index.js#L214-L215
