### ISSUE TITLE
Video Block on bottom has unexplainable 8px gap (could also be padding or margin)

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#52944]
https://github.com/WordPress/gutenberg/assets/737143/3c44f029-11fe-41db-9861-9d077e0d3253

I have no explanation where that gap is coming from.
- In the Block Editor I set the padding and margin on bottom explicitly to 0.
- the Frontend DOM inspection also does not really tell me where that gap is coming from.
- The hottest candidate is `:where(figure) { margin: 0 0 1em; }`, but tweaking it, also with !important, does seemingly nothing.

## Reproduction

1. Create a group block: Set its padding-bottom to 0.
2. Insert a headline.
3. Insert a video block. Set its bottom and margin on bottom to 0.

**Expectation:** The video block bottom is flush with the container block bottom.

**Actually:** There is a visible gap of exactly 8px (both on Safari and Chrome) between the bottom side of the video block and the bottom line of the container block.

## Environment

- WordPress 6.2.2
- Gutenberg 15.9.1 (plugin updating off)
- Gap occurs both on Mac Safari and Mac Chrome

## Please confirm that you have searched existing issues in the repo.

Yes

## Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

## Workaround: Custom CSS for Video Block

```css
figure.wp-block-video {
	margin-bottom: -8px !important;
}
```

But I guess this is quite a dirty and unstable and unreliable and not long term fix.

**Comment by porg** [comment]
I'm pinging developers who worked on closely related issues:
- @jasmussen #5256
- @scruffian #34642

**Comment by porg** [comment]
## Custom Block CSS fix — And how it looks in the Editor UI

![WordPress Video Block on bottom has unexplainable gap 4a](https://github.com/WordPress/gutenberg/assets/737143/959ffd94-2674-440e-9236-fcd084d6f7a7)

**Comment by richtabor** [comment]
Yea I think it's the `figure` getting a default browser margin applied to it.

**Comment by jasmussen** [comment]
Actually it seems like the figure margin is handled by a generic rule:

```
:where(figure) {
    margin: 0 0 1em;
}
```

I tested across both image and video to make sure, and sure enough, the rule applies to both. so the 8px are coming from the `video` element. Here's a little inspector session in GIF form:

![inspecting](https://github.com/WordPress/gutenberg/assets/1204802/143092b3-d18f-49e1-916b-898fda5ee9c6)

Shown in the GIF, it isn't entirely clear where that margin is coming from. But setting it to `block` "fixes" the issue. I.e. this would work:

```
.wp-block-video video {
	display: block;
}
```

I'm not sure if that would have any negative side effects, or if there's a better way to zero out that margin. I don't know where it's coming from, and it reminds me of how line-height affects inline-block images as well.

**Comment by porg** [comment]
## `.wp-block-video video { display: block; }` seems to be the proper fix
![WordPress Video Block on bottom has unexplainable gap 5a](https://github.com/WordPress/gutenberg/assets/737143/326a87f7-98b0-4dcf-b95c-af3a33293d9e)
- ✅ In the frontend the video block bottom is now flush with its container group bottom.
- ✅ Also in the Editor UI the selection outline is now congruent with the video itself.
- And I have much more trust in this solution that it will work with all kind of video dimensions and caption on/off, then a hacky `figure.wp-block-video { margin-bottom: -8px !important; }` (requiring `!important` made me skeptical).
- 👍 Thanks for this! Will run with this Custom Block CSS for now.

## Could we apply this fix in codebase?
- I guess to commit this change to the codebase, you must be really sure what's the cause and what's the fix
  - But you @jasmussen wrote "it isn't entirely clear where that margin is coming from".
  - So I guess before a general fix for this comes, the true cause needs to be clear, and the fix and proper Block Theme Modular CSS conformity must be ensured too.

**Comment by porg** [comment]
A great explanation! Thanks!

Graphic from article [Removing White Space Below Image Elements](https://mor10.com/removing-white-space-image-elements-inline-elements-descenders/) by [Morten Rand-Hendriksen](https://mor10.com/author/mor10-2/):

!["Removing White Space Below Image Elements" or "Why Inline Elements Have Descenders"](https://mor10.com/wp-content/uploads/2014/07/imagedescender.png)


- So the video _block_ definitely is no _inline_ element which needs to align with the baseline of text before/after it.
- So yes the Gutenberg team should fix this with the most appropriate CSS `display` attribute.

**Comment by Ren2049** [comment]
Had a similar issue with the 8px padding at the bottom. It appeared below the site logo using blank theme and TT3 before, ~~both issues got fixed recently in both themes~~. https://github.com/WordPress/create-block-theme/issues/421#issue-1806486362

**Comment by porg** [comment]
@jasmussen You still had the issue. With which versions of WP, Gutenberg, TT3 ?

@Ren2049 With which versions of WP, (Gutenberg plugin), TT3 theme did your problem disappear?
- Maybe only that "Site Logo" block got fixed to an explicit block display?
- Could you please create a Video block?
  - And copy its complete HTML markup here. (whole block: figure container + video)

@all
- I assume the fix should not come from the TT3 theme, but rather from a changed block, as the video block should have the same basic metrics in all themes, the theme at most tweaking on top of this.

**Comment by Ren2049** [comment]
@porg Sorry it was a mistake, the problem with the logo is still there with the blank theme (created with the create block theme plugin). Only TT3 got fixed in 6.3 beta4, 6.3 beta 3 still had the problem.

When I insert a video block in TT3 RC2 there's still the 8px padding at the bottom despite it being fixed with the site logo.

**Comment by porg** [comment]
So from this I conclude that TT3 made an "ad hoc hotfix" for the logo (by some means) but that the various native blocks dealing with media (Video block, Site Logo block, others too?) yet got no "systematic revisiting to be explicitly set for block display" and hence default to inline display by basic browser style.

**Comment by jasmussen** [comment]
I can't speak to any logo fixes in TT3, I would think any such fix would, for a block theme as it is, have to live in `style.css`, and for TT3 that's entirely empty. 

But it seems like the next step here is a video display/block PR that can be tested. Anyone up for it?

**Comment by Ren2049** [comment]
I think I know why I had this problem, it was a missing line-height: 0; on the .wp-block-site-logo class which the TT3 has and the blank theme doesn't when I switch themes. 

Is it possible that this class is maybe triggered by line-height settings in global styles/theme.json?

**Comment by t-hamano** [comment]
I know there are many approaches to solving this problem, but I believe the solution is to apply `vertical-align: middle` to the `video` element in the Video block.

For example, we have had similar problems in the past with Media & Text block, and this approach is used in #11025.

I would like to submit a PR if I may, but if anyone would like to work on this, I would be happy to review it.

**Comment by jasmussen** [comment]
Go for it, happy to review.

**Comment by lunaluna** [comment]
✋  I'll try to make PR next week!

**Comment by t-hamano** [comment]
Thanks for your interest in this issue, @lunaluna! Please send me a pin when you are ready for PR.
