### ISSUE TITLE
Revision History: Display "Revision History" item when there has been at least one set of saved revisions

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/gutenberg#52951]
## What problem does this address?

After saving one set of style revisions, it's not yet clear that there's a revision history available.

Details:

1. Go to Appearance > Editor
2. Click into the preview area on the right
3. Click the Styles icon near the top right

Note the default state of the Revisions icon, it's greyed out:

<img width="357" alt="Blog_Home_‹_Template_Part_‹_Editor_‹_LearnWP_—_WordPress" src="https://github.com/WordPress/gutenberg/assets/7662449/5a4914f5-731d-47e2-809a-a3079d9a58e2">

4. Make a change in the Styles area (under Typography, Colors, or Layout) and click Save

Note that the Revisions icon is now active (black). Clicking the icon now displays "Reset to defaults":

<img width="322" alt="Blog_Home_‹_Template_Part_‹_Editor_‹_LearnWP_—_WordPress_and_New_Issue_·_WordPress_gutenberg" src="https://github.com/WordPress/gutenberg/assets/7662449/dba5ead2-eb16-4aa4-a5bb-57f0906878eb">

However, this can be confusing. When I first saw it, I wondered where the new Revisions side panel was, and why it wasn't working.

Once I made and saved another revision, however, I saw that the number "2" appeared in a black square next to a new item "Revision history" – and I then understood that the "Revision history" item would only appear once at least **two** sets of changes have been saved:

<img width="321" alt="Blog_Home_‹_Template_Part_‹_Editor_‹_LearnWP_—_WordPress" src="https://github.com/WordPress/gutenberg/assets/7662449/1ee323e7-c198-467d-8483-40f7d9455efe">

## What is your proposed solution?

I think it would be much clearer, consistent, and less confusing to display the "Revision history" item even when there's only been only **one** saved revision. That will remove any doubt in a user's mind that the revision history panel maybe isn't working.

**Comment by ramonjd** [comment]
👋🏻 

Thanks for filing this issue. It raises a question we grappled with initially, when introducing the revisions feature.

It was a deliberate choice to only show the revisions after two changes. See https://github.com/WordPress/gutenberg/pull/50089#issuecomment-1532276020

> It's because the initial global style custom post isn't considered a "revision" . So if we reduce the condition to const hasRevisions = revisionsCount >= 1;, there's nothing with which we can compare it

If we reveal the panel with one revision, it would show it fine but we can't interact with it:

<img width="292" alt="Screenshot 2023-07-26 at 4 35 20 pm" src="https://github.com/WordPress/gutenberg/assets/6458278/d2325d7f-9dbd-45c5-8137-e8bb3d50087e">

An alternative, and I've already [tested this](https://github.com/WordPress/gutenberg/pull/50089#issuecomment-1532324313), is to show the "reset to default" version as the first revision. 

I've thrown up a PR to demonstrate:

https://github.com/WordPress/gutenberg/pull/52965

cc @jameskoster with whom we originally chatted about this idea 🙇🏻

**Comment by kathrynwp** [comment]
Thanks for the context, @ramonjd .

> If we reveal the panel with one revision, it would show it fine but we can't interact with it:

What if clicking that initial revision just did the same thing as "reset to defaults"? That would be quite consistent and less confusing, in my opinion. But maybe there's a technical reason preventing that?

**Comment by ramonjd** [comment]
> What if clicking that initial revision just did the same thing as "reset to defaults"? That would be quite consistent and less confusing, in my opinion. But maybe there's a technical reason preventing that?

Do you mean the initial revision with the first changes, or the "defaults" revision we're adding in https://github.com/WordPress/gutenberg/pull/52965?

If the latter, then that's the road we're going down. I think that's consistent. 

If the former, I'm not sure that I'd expect to reset styles by clicking on a revision that contains changes different to the theme base 🤔

**Comment by kathrynwp** [comment]
@ramonjd Oh yes, I see what you're saying. I think a "Reset to defaults" item as shown in https://github.com/WordPress/gutenberg/pull/52965 would definitely serve to avoid the confusion I ran into!

**Comment by ramonjd** [comment]
Resolved by https://github.com/WordPress/gutenberg/pull/52965
