### ISSUE TITLE
Missing i18n on strings in Edit Post overview sidebar

### ISSUE THREAD

**Issue by pedro-mendonca** [WordPress/gutenberg#52970]
### Description

On the edit post screen, the tabs "List View" and "Outline" on the left sidebar aren't translatable.

The strings ['List View'](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-post/src/components/secondary-sidebar/list-view-sidebar.js#L143) and ['Outline'](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-post/src/components/secondary-sidebar/list-view-sidebar.js#L148) aren't wrapped on a Gettext `__()` function.

### Step-by-step reproduction instructions

1. Set a language on Settings > General other than *English (US)*.
2. Add new post
3. Click on the overview icon on the top toolbar on the left
4. See both tabs as the image below, in English *.

* Currently 'List View' already has a translation in core, 'Outline' without any context doesn't.

### Screenshots, screen recording, code snippet

"List View" and "Outline" aren't translated.
![imagem](https://github.com/WordPress/gutenberg/assets/7371591/8207d752-7103-4fb0-9f0d-13c417db689f)

### Environment info

- WordPress 6.3
- No Gutenberg installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ocean90** [comment]
Introduced in #50199.

**Comment by jordesign** [comment]
Thanks @ocean90 ! I'll close this issue with that having been added. Thanks again

**Comment by ocean90** [comment]
This still needs to be fixed.
