### ISSUE TITLE
Footnotes: footnotes within nested blocks are sometimes counted twice

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#53009]
Following on from https://github.com/WordPress/gutenberg/pull/52682, it looks like there's still an issue with footnotes sometimes being counted multiple times. It's a bit edge-casey, but I believe a reliable way to reproduce the issue is:

1. Add a Group block to a post
2. Add a Quote block within the Group block
3. Add a footnote to the paragraph within the Quote block as well as to the Citation of the Quote block
4. Notice that the footnote item is duplicated and synced twice:

https://github.com/WordPress/gutenberg/assets/14988353/b28b03d2-d1f6-4755-bba3-6ad3a98adc31

From looking at #52682, I think this might be a result of iterating over inner blocks as well `addValuesForBlocks` being called a second time for blocks with `InnerBlocks.Content`? CC: @ellatrix, @mcsf, @ramonjd, @tellthemachines

**Comment by ellatrix** [comment]
It seems to be the citation that is the problem. Adding footnotes to the paragraph seems to work fine
