### ISSUE TITLE
Drag & drop reordering of "chapters" in the Table of Contents

### ISSUE THREAD

**Issue by schlessera** [WordPress/gutenberg#5301]
I think it would be useful to be able to reorder "chapters" through drag & drop in the "Table of Contents" section in the right sidebar.

<img width="262" alt="image 2018-02-28 at 11 16 05 am" src="https://user-images.githubusercontent.com/83631/36782295-ce4901f4-1c78-11e8-828f-a962d7f96c5e.png">

Dragging a specific heading would move that heading and all blocks immediately below it up to and excluding the next heading of the same level.

Dragging headings could also change their level, depending on where you drag them to.

Let's go through a quick example of how I think this could work.

- A "chapter" is the heading block that was selected, and all blocks immediately following up to and excluding the next heading of the same level or up to the end of the document.
- If the author drags the entry "H2 The Inserter Tool" entry below the "H2 Media Rich" entry, the "H2 The Inserter Tool" chapter gets moved below the "H2 Media Rich" chapter and is the last chapter in the document from then on.
- If the author drags the entry "H3 Sub-heading A" on top of the "H2 The Inserter Tool", the chapter "H3 Sub-heading A" moves from being a sub-chapter of "H2 Visual Editing" to being a sub-chapter of "H2 The Inserter Tool".
- If the author drags the entry "H3 Sub-heading B" between the entries "H2 The Inserter Tool" and "H2 Visual Editing", the chapter "H3 Sub-heading B" gets moved in-between these two chapters and changes its level to "H2 Sub-heading B".

This would make re-ordering the structure of a larger document much faster and easier (no need to scroll around over multiple pages of content) and less error-prone (like copy-pasting only partial chapters).

**Comment by SuperGeniusZeb** [comment]
This issue should probably be renamed to “Drag & drop reordering of “chapters” in the Document Outline”, since the <samp>Table of Contents</samp> is now called the <samp>Document Outline</samp>.

**Comment by paaljoachim** [comment]
I am thinking this issue in regards to The Insert Summary feature might be related #7115

**Comment by ellatrix** [comment]
It would be nice if the block navigation and document outline could be combined (blocks collapse into headings) and we just implement drag and drop once in this list. :)

**Comment by paaljoachim** [comment]
Buzzing @shaunandrews here.....

**Comment by shaunandrews** [comment]
I'm with @ellatrix on this one; I have a hard time justifying the existence of both the Document Outline and the List View. There's long been talk of combining the two UI's somehow, and I think that's likely the better solution to work towards.

**Comment by priethor** [comment]
Ongoing PR that combines the document outline and the List View, which supports Drag&Drop: #14956

**Comment by mtias** [comment]
I think we can close this as it's supported in List view. We should fold the outline into it eventually, probably as a filtered down view (display only headings).
