### ISSUE TITLE
Site Editor: Snackbar timeout seems to reset on each 'save' action

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#53016]
### Description

The snackbar appears to be set to have each instance fade out after 10 seconds of displaying. I found that when _another_ 'save' action takes place it looks like it resets the counter.

In an instance where lots of changes and saves might be taking place (like the style variants) these can start to stack up significantly.

<img width="687" alt="Screenshot 2023-07-27 at 8 03 19 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/f0a0d5a9-7a71-4ac6-ab6c-002345c4f43f">

It then removes a single snackbar instance each 10s so it also takes a long time for them to move away in bulk.

### Step-by-step reproduction instructions

1. Open the site editor and go to 'Styles'.
2. Select a new style and then click 'save'.
3. repeat

### Screenshots, screen recording, code snippet

This example is a massive exaggeration - but still possible to produce if lots of rapid changes are being made.

https://github.com/WordPress/gutenberg/assets/1842363/1bc1be04-214b-4fc4-81b8-86c4e1850e86

### Environment info

WP6.3 RC3
No plugins
TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
There seems to have been prior discussion around the timing of the snackbars, and also their placement.
* https://github.com/WordPress/gutenberg/issues/49165
* https://github.com/WordPress/gutenberg/pull/47199

But this resetting of the dismissal timer seems an extension of that.

**Comment by glendaviesnz** [comment]
I think it makes more sense to only ever display one snackbar at a time for a given action, as we are now doing in a number of other places. [PR for this here](https://github.com/WordPress/gutenberg/pull/53087).
