### ISSUE TITLE
Command Center: Still refers to 'Library' instead of 'Patterns'

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#53027]
### Description

When invoking the Command Center it still refers to the old naming of 'Library' instead of the updated title of 'Patterns' for that section of the Site Browser

### Step-by-step reproduction instructions

1. Open the Site Editor
2. Invoke the Command Center and see 'Open Library' listed as a default option

### Screenshots, screen recording, code snippet

<img width="1155" alt="Screenshot 2023-07-27 at 9 17 15 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/272818bc-8fc6-4554-8c92-9548f6a4f73f">

### Environment info

WP 6.3 RC2
No plugins
TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I've just realised this is correct in GB - but not in 6.3RC3.

**Comment by t-hamano** [comment]
This issue appears to have been resolved in #52742.

@aaronrobertshaw @Mamaduka
Should #52742 be backported to WP6.3?

**Comment by Mamaduka** [comment]
We can't cherry-pick changes that introduce new strings in release RCs.

I'm going to close the issue since it's resolved in the plugin.
