### ISSUE TITLE
SVG icons: the CSS rule for the fill property targets any SVG in the page

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#5302]
In `edit-post/assets/stylesheets/main.scss` there's a CSS rule that translates to this:
```
body.gutenberg-editor-page svg {
    fill: currentColor;
    outline: none;
}
```

and targets _all_ the SVG icons in the page, including the ones that are not specific to Gutenberg.

Many plugins use their own SVG icons and the rule above will conflict, forcing plugin authors to increase specificity for their CSS selectors. Additionally, the rule above targets icons in the whole body, including the WordPress adminmenu and toolbar.

At the very least, I'd propose to use a selector that excludes the adminmenu and toolbar.

What about plugins SVG icons in the metaboxes area or in the plugins sidebar? Instead of trying to target specific areas of Gutenberg, I'd propose to consider to make sure all the Gutenberg-specific SVG icons always use the same CSS class and target that instead of a generic `svg` element. 

A couple examples of CSS conflicts from Yoast SEO (but it could happen with any plugin):

These icons should be purple, instead they get the blue `currentColor`:

<img width="296" alt="screen shot 2018-02-28 at 11 02 16" src="https://user-images.githubusercontent.com/1682452/36782964-ed6e8f98-1c7a-11e8-81c3-ff0b86af3fed.png">

These icons should be red, instead they get the text gray `currentColor`:

<img width="384" alt="screen shot 2018-02-28 at 10 52 43" src="https://user-images.githubusercontent.com/1682452/36782976-f71d4eb2-1c7a-11e8-904f-74c73518a161.png">

I'd also recommend to consider to try to keep selectors specificity always as low as possible. Similar issues could happen not only for SVG icons but also in other cases.

**Comment by afercia** [comment]
Note: the CSS has been reorganized and the rules for SVGs are now scoped a bit better, see the usage of `fill: currentColor` in the following files:
```
components/dashicon/style.scss
components/icon-button/style.scss
```

However, the rule in the first file still applies to _any_ inline SVG with a `dashicon` class. If plugin authors want to use inline SVGs with a `dashicon` class, they are forced to override that rule. It would be definitely better to avoid a such generic selector like:
```
svg.dashicon {
	fill: currentColor;
	outline: none;
}
```

and scope on a component basis. Thoughts? /Cc @jasmussen

**Comment by jasmussen** [comment]
I can wrap quick PRs together to address that, @afercia, but I need to understand better the use case for plugin authors wanting to "use inline SVGs with a dashicon class". Why would you do that?

**Comment by afercia** [comment]
Hm maybe you're right it would be an edge case, was thinking at the case when a plugin wants to use a Gutenberg `Dashicon` component and, for example, give it a different color.

**Comment by jasmussen** [comment]
> was thinking at the case when a plugin wants to use a Gutenberg Dashicon component and, for example, give it a different color.

In this case you could simply change the `color` property of the icon, that should work.

**Comment by karmatosed** [comment]
I am going to close this with the assumption that this is solved for majority of cases. I totally am ok reopening if that's not the case, but I am in reading this thinking we have a better solution and the rest is something that can be worked around for now.

**Comment by daledesilva** [comment]
I've recently encounter @afercia 's mentioned issue and I agree that it is of concern.
I don't believe it would be an edge case at all as it's very common to want colour control of any icon you put in.

In regard to the suggested solutions, none of them work as expected.

@jasmussen , attempting to override the color like below works in the editor but not in the frontend.
```
<Dashicon
   icon = { iconReference }
   width = { iconWidth }
   height = { iconWidth }
   color = { "#FF0000" }
/>
```
In Chrome's dev tools, the color is shown as my input value for the SVG element, but the icon shows as black and I can't figure out what's overriding it.

Attempting to override the fill property instead of color works in the front end but not in the editor (ie. the opposite way around)
```
<Dashicon
   icon = { iconReference }
   width = { iconWidth }
   height = { iconWidth }
   fill = { "#FF0000" }
/>
````
In this case, the editor shows that my input color for the SVG has been applied but has then been overridden by the generic selector styling mentioned by @afercia .

In order to successfully change the color of the dashicon, I've had to set both fill and color.

I'm using theme **Twenty Sixteen Version: 2.1**
And **WordPress Version 5.4.2**

**Comment by jasmussen** [comment]
Hello @daledesilva 

> attempting to override the color like below works in the editor but not in the frontend.

Are you able to provide me with rendered example markup you see on the frontend and in the editor? I.e. if you can inspect the icon and copy the markup you see in the inspector for the icon, both in the editor and the frontend, that would make it easier to debug. Thank you.
