### ISSUE TITLE
Patterns: previewing a pattern which contains a Query disables the Site Browser back button

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#53025]
### Description

When previewing patterns - previewing a category which contains patterns that use a Query within them seems to break the Site Browser's 'Back button.

Additionally - there is a lot of flashing/glitching when loading the patterns that contain queries.

----
I found this to be true for categories containing the following types of patterns:

* A pattern from the theme which contained the Comments block.

https://github.com/WordPress/gutenberg/assets/1842363/1dbcde91-785f-4254-8238-7bf111935dbd

* A custom pattern which contained the Comments block.

https://github.com/WordPress/gutenberg/assets/1842363/df46b084-aa06-4ddc-b760-196f7edf3ef6

* A custom pattern which contained a Query Loop

https://github.com/WordPress/gutenberg/assets/1842363/337045a6-0f04-4c44-b14b-228dc3ab72c6

### Step-by-step reproduction instructions

1. Open the Site Editor and go to the Patterns section
2. Preview a pattern category which contains a pattern using a query within it (for example 'general' in TT2).
3. Try and use the 'back' chevron to the left of the 'Patterns' title.

### Environment info

WP 6.3 RC2
No plugins
TT3

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I think this issue has been resolved in #52964 and a backport label has been given, but it does not appear to have been backported to the latest RC version yet. It would be a good idea to test it again in the next RC3 release.

**Comment by tellthemachines** [comment]
I can no longer reproduce this in Gutenberg trunk; closing as fixed by #52964, which will be added to 6.3 RC3.
