### ISSUE TITLE
Sidebar tab text is not aligned with sidebar panel text

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#5304]
This is one of those "can't unsee" things:

<img width="277" alt="screen shot 2018-02-28 at 12 31 48" src="https://user-images.githubusercontent.com/1204802/36785534-72a5ea28-1c83-11e8-941c-a07396bc294c.png">

Note how the margin left of the "Document" tab is wider than the margin to the left of "Status & Visibility". 

I'm going to fix that, just ticketing this for tracking.

**Comment by karmatosed** [comment]
Argh can't unsee! 👍 please fix.
