### ISSUE TITLE
Blocks: Gallery block breaks under iOS 10.2 Safari

### ISSUE THREAD

**Issue by shoetten** [WordPress/gutenberg#5306]
## Issue Overview

The new list based gallery markup introduced in d8eaefb81f103898a66ba2eaebd2057c255f7e7b breaks the layout in mobile Safari under (at least) iOS 10.2.
I'm using Gutenberg v2.2.0

The [example post](https://wordpress.org/gutenberg/) works, because it is using the now deprecated markup.

## Steps to Reproduce (for bugs)

1. Add the example Gutenberg post to your WP installation
2. Navigate to the post in iOS Safari

## Expected Behavior

![img_0863](https://user-images.githubusercontent.com/1785212/36790282-94e523c2-1c94-11e8-8063-116d5a21c73a.PNG)

## Current Behavior

![img_0862](https://user-images.githubusercontent.com/1785212/36790300-a260cf6a-1c94-11e8-9d13-bc8e0c830eab.PNG)

## Possible Solution

Change the display type on the `<li>` element to block:

```css
.wp-block-gallery .blocks-gallery-item {
    display: block;
}
```

I don't fully grasp all possible display options, but in my understanding this shouldn't break the layout, since the `<figure>` element has it's own `display: flex`, which takes care of the correct positioning of the caption.

**Comment by jorgefilipecosta** [comment]
Hi @shoetten thank you for reporting this issue. I did some tests and it looks like the gallery is not breaking anymore on iOS. If in your tests on the last version, you find that is not the case, feel free to comment and the issue will reopen and we will look further.

**Comment by laphilia** [comment]
Hi 
I have the same issue but only on small screens and older versions of iOS. 
That is on iPad (iOS10) and iPhone (iOS9).
On newer versions (iOS11) it works fine on both devices.

**Comment by billerickson** [comment]
I'm seeing the same issue, iOS 10.3.3.

I think this should be patched, even if it currently works on iOS 11. Not everyone is running the most up-to-date OS.

**Comment by sundweathers** [comment]
Can this issue be reopened?  Problem still exists with iOS10.3.3 and Gutenberg 3.6.2.
Older Ipads can't be updated to iOS 11 but are still used by many of my followers

**Comment by oldmankit** [comment]
The problem is that this degrades really poorly. Gallery images end up covering text making the page unusable for many users. Some people haven't updated to iOS 11 out of choice.

**Comment by oldmankit** [comment]
I'm attaching an image of a page that is basically broken by this bug. On every other browser I've tested it is a perfectly responsive page. The browser in question is Safari on iOS 10.2.1
![180921 ios 10 safari problem](https://user-images.githubusercontent.com/4979371/45858367-42938980-bd87-11e8-9b49-d034f0ac5d60.jpg)

**Comment by ruthmaude** [comment]
https://github.com/WordPress/gutenberg/issues/10150 - same issue reported here

**Comment by scubarob78** [comment]
Hi,

I've the same issues with WP 5.0.3 standard gallery block on Ipad Mini iOS 9.3.5 (13G36) with the browsers: Safari, Opera Mini, Chrome

code:


<ul class="wp-block-gallery columns-1 is-cropped"><li class="blocks-gallery-item"><figure><img src="http://scubarob.love/wp-content/uploads/2018/12/IMG_5336_web-1.jpg" alt="Chile Santiago" data-id="425" data-link="http://scubarob.love/2018/12/27/santiago-as-the-hearth-of-the-chilean-culture/img_5336_web-2/" class="wp-image-425"/></figure></li></ul>

**Comment by slingshotdesign** [comment]
I'm seeing this issue also with iOS version 9.3.5 which apparently had very glitchy support for Flex. In my experience there are still a lot of old iPads around. They can't be upgraded and Chrome, Firefox and Edge cannot be installed on them because the OS is too old. I'm trying to figure out a solution and will report back if I find one.

**Comment by eduardozulian** [comment]
@slingshotdesign, perhaps trying some of the CSS workarounds in #10150 will help. :)

**Comment by brandonquinnsmith** [comment]
I'm seeing the same issue on iOS version 9.3.5 slingshotdesign. And the captions are also a mess as well.
