### ISSUE TITLE
Make Link UI "Advanced" button not have "Admin Color" when open

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#53069]
Currently when the "Advance" toggle is open on Link Control the color is "Admin Color". Let's change that to be the same as when it's closed (is that right @richtabor?).

-------

I would prefer if the Advanced button wasn't the admin color when opened though.

_Originally posted by @richtabor in https://github.com/WordPress/gutenberg/issues/52799#issuecomment-1653955839_

**Comment by richtabor** [comment]
For reference: 

<img width="349" alt="CleanShot 2023-07-28 at 11 12 29" src="https://github.com/WordPress/gutenberg/assets/1813435/50ba6f2e-f08f-4fbc-b210-3277b4fb4d9f">

Open state should maintain the $gray-900 color; not have the admin-color applied.

**Comment by scruffian** [comment]
This color is the default color for buttons that are open, so we should make the change to all expanded buttons.

**Comment by richtabor** [comment]
Not list view, which this emulates most. 
 
<img width="348" alt="CleanShot 2023-08-09 at 11 22 51" src="https://github.com/WordPress/gutenberg/assets/1813435/2afce7b7-238d-4480-8d2f-17abc895060a">

**Comment by getdave** [comment]
This seems like a quick win and a "good first PR".
