### ISSUE TITLE
Block Widgets - Social Icons block elongated in Customizer Widgets

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#53077]
### Description

The Social Icons block is appearing too wide in the Customizer > Widgets area.  

This appears to be a regression or new recurrance of what https://github.com/WordPress/gutenberg/pull/35865 fixed in Gutenberg 11.9.

### Step-by-step reproduction instructions

1. Activate classic theme such as **Twenty Twenty One** or **Twenty Twenty**
2. Appearance > Customize > Widgets
3. Add a Social Icons block, and set up an icon (such as a WordPress icon linked to https://wordpress.org/)
4. Observe the width of the icons in the customizer sidebar.

### Screenshots, screen recording, code snippet

![Markup on 2023-07-27 at 13:12:13](https://github.com/WordPress/gutenberg/assets/27249804/6e04d012-d21e-4c7e-8eb3-f3a6c1d69fba)

### Environment info

- WP 6.2.2
- Gutenberg 16.3 and Gutenberg plugin inactive

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Noting that this occurs with 6.3 RC3. Adding to the 6.3 board.

**Comment by tellthemachines** [comment]
This issue exists in 6.2.2 so it's not eligible for 6.3 at this stage of the release cycle.
