### ISSUE TITLE
Image blocks not look proper on editor side when alignment is changed

### ISSUE THREAD

**Issue by Himshekhar07** [WordPress/gutenberg#53093]
### Description

Image block alignment is not working as aspected when I take 2 image blocks one after the other and set the alignment of the first block to the right and the second block to none. It shows both blocks side by side.

### Step-by-step reproduction instructions

1. In twenty twenty-three themes.
2. Go to post and create a new post.
3. Add image blocks one after the other.
4. Change the alignment of the first image to align right.
5. On the second image alignment set the alignment to none.
6. Now you see both images side by side on the editor side but when you update the page it shows the images in vertical alignment.

### Screenshots, screen recording, code snippet

screen recording - [https://share.cleanshot.com/nJvblNLj1ySJslWXglnW](https://share.cleanshot.com/nJvblNLj1ySJslWXglnW)

![CleanShot 2023-07-28 at 11 57 33](https://github.com/WordPress/gutenberg/assets/73247637/b1ae8547-ac8f-45fa-b7bd-cc028dccc6a7)

### Environment info

-WordPress Version => 6.2.2
-Browser => Chrome
-Browser version => 115.0.5790.114

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tellthemachines** [comment]
Hi @Himshekhar07 !

> Now you see both images side by side on the editor side but when you update the page it shows the images in vertical alignment.

To clarify, do you mean that what you're seeing in the editor is different from the front end, given the same window size? 

It's expected that the unaligned image would sit next to the right-aligned one given enough space, but on a narrower viewport it would sit underneath. 

Could I also ask you to retest with the most recent WP version? The Image block controls have seen a few improvements so it's possible that the issue has resolved itself.

**Comment by karmatosed** [comment]
Thank you for reporting this @Himshekhar07. For now, I am going to close this as I am not seeing the problem. That doesn't mean it isn't either something needs more details around or an issue for you still. If you are able to provide more information please do that and this can always be reopened. I am unable to replicate and as @tellthemachines noted, image block controls have seen a few improvements that might be the reason for not seeing the issue today/
