### ISSUE TITLE
Improve copy of Error messages

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#53095]
## What problem does this address?
When saving fails, the Copy is from a UX standpoint very poor:
<img width="582" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/4a7921e6-ae0a-440e-a940-0486d5ae77a5">

It's missing at least the info on what exactly has happened and what to do next.
I'd love to give more information on how to reproduce the error message and give suggestions on how to improve, but ironically I don't have any more information 😄 

Maybe this caused the error? A small improvement would be to console errors to give more info - would this be possible?
<img width="1246" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/3fae659e-7f19-4019-956a-e0cfc3a0997d">

## What is your proposed solution?
This is a good basic guide on better copywriting for error messages: https://www.thegiggal.com/ux-writing-error-messages/

**Comment by hanneslsm** [comment]
I think the Saving issue came up because my template was called "Temp: Heros". After removing the `:` it disappeared.
Proofs the point that the copy of error message must be improved.

**Comment by skorasaurus** [comment]
I wholeheartedly agree. When I first started developing in Gutenberg (already 3-4 years ago!), the ambiguity of the error message was really frustrating and this largely hasn't changed; I just know now where to look (console, using breakpoints, etc), what typical error message in Gutenberg can mean, and to developers' credit, fewer overall errors.  

Related issues to improve error messages clarity: https://github.com/WordPress/gutenberg/issues/34482 , https://github.com/WordPress/gutenberg/issues/34119, https://github.com/WordPress/gutenberg/issues/10492 , and https://github.com/WordPress/gutenberg/issues/25436

**Comment by skorasaurus** [comment]
(Perhaps for this issue, to keep it on track and make it actionable; surface a message that only certain characters are allowed in template names.

**Comment by hanneslsm** [comment]
> (Perhaps for this issue, to keep it on track and make it actionable; surface a message that only certain characters are allowed in template names.

Actually, I think it'd be beneficial if we keep this issue for general UX and Copy improvement for error messages. The error above was only an example. 

To move forward, we'd probably need more information on which information could be extracted.  Even small improvements, like the displaying the error message from the console, would help already.
We then can see if the copy can be more polished and made more human, so to say.

**Comment by Mamaduka** [comment]
Closing in favor of #64158, which is a new "tracking" issue for database error notification improvements.

Notice component design improvements are discussed in #67662.

Thanks for contributing, @hanneslsm!
