### ISSUE TITLE
Edit image -> Link to drop down not included.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#5309]
Editing an image in TinyMCE. 

One gets this screen:
![screen shot 2018-02-28 at 10 29 29](https://user-images.githubusercontent.com/5323259/36796326-510418a0-1c73-11e8-89f9-19f8332755a0.png)

The Link to options need to be added to Gutenberg.

**Comment by chrisvanpatten** [comment]
Is there any prior art in the Gutenberg UI for pre-selecting links? Happy to mock something up but it would be nice to borrow an existing pattern. (I can't find one, fwiw)

**Comment by paaljoachim** [comment]
Comparing the existing Media Library and Image Details features with that of Gutenberg.

Add Media screen Classic Editor

![classic-editor-media-library](https://user-images.githubusercontent.com/5323259/42112941-e3ebe30c-7be9-11e8-9054-a0042420164a.png)

Left side:
Add Media, Create Audio Playlist, Create Video Playlist, Featured Image, Insert from URL

Center:
Upload Files - Media Library
All Media items - drop down, All dates - drop down, Search Media items.
Thumbnails of the media library media is seen.

Right:
Attachment Details
preview of image
Information about the image
URL, Title, Caption, Alt Text and Description

Attachment Display Settings
Alignment
Link to
Size

Gutenberg Select or Upload Media screen.

![gutenberg-media-library](https://user-images.githubusercontent.com/5323259/42113354-5a446302-7beb-11e8-833f-86f2874d1c9d.png)

No left area. That means we need to make sure that all of the left area of the Classic editor is covered elsewhere such as: 
Create Audio Playlist #7126 
** Create Video Playlist **  - Is this being worked on?
Featured Image - Clicking the left sidebar Featured image is then another way to add the featured image. Gutenberg has the process to add a featured image in the document setting.
** Insert from URL ** - Is this being worked on? I do not know of a way to link to an external image through Gutenberg.

Center area:
** The CSS still needs to be adjusted in the All Dates drop down. I made an issue about this some time back. I thought it was fixed but it does not look like it.
** The drop down should also add a sorting by media type. Audio, video, image, pdf, other.
Today it adds by month if one has added media sorting by month.

Right area:
No Attachment Display Settings in Gutenberg in the Select or Upload Media library screen.
Alignment: Is added in the toolbar above the image/gallery.
Link To:
Single image link shows the following:

![screen shot 2018-06-29 at 22 41 41](https://user-images.githubusercontent.com/5323259/42114003-b43baefe-7bed-11e8-8ebc-9d2b70da8041.png)

In the Classic Editor (as I mentioned further above) shows this:
![screen shot 2018-06-29 at 22 42 53](https://user-images.githubusercontent.com/5323259/42114030-de014e4c-7bed-11e8-84ea-48a7c2083d8d.png)

I would suggest redoing the link feature in the single image to:
![gutenberg-single-image-link-menu](https://user-images.githubusercontent.com/5323259/42114380-2fa95586-7bef-11e8-9391-0bb7ff485ee9.jpg)

Somewhat similar to adding a regular link containing the three dots to open another link menu below it.

Size. Is defined through the Block image setting.

That should then cover the existing Classic Editor Add Media library screen with Gutenberg.

-------------

Classic Editor Image Details.

![classic-editor-image-details](https://user-images.githubusercontent.com/5323259/42114822-ce9172a4-7bf0-11e8-8127-be0710a892ea.png)


Caption.
Alternative Text

Display Settings
Align
Size
Link To

Advanced Options
Image Title Attribute
Image CSS Class
Open Link in a new tab
Link Rel
Link CSS Class

Right side:
Edit Original
Replace

Gutenberg Image Block Settings

![gutenberg-image-block-options](https://user-images.githubusercontent.com/5323259/42115040-bb3e2b7e-7bf1-11e8-9830-d63ccab949d7.png)

Comparing Classic Editor with Gutenberg.

(Caption is added directly on the image.)
Textual Alternative same as Alternative Text.
(Align is done through the layout screen in Gutenberg.)
Source Type same as Size.
Link To is suggested with the further above wireframe.
** Image Title Attribute is not seen in Gutenberg that I know of.
Advanced includes a image CSS Class.
** Open link in a new tab, and Link Rel and Link CSS Class is not solved as far as I know of. 
Can open link in a new tab and Link Rel be included in the Single Image link contextual/3 dot menu?
** Edit Original or replacing the image is not solved as far as I know of.

That gives an overview of the existing media library and the single image details screen in relation to Gutenberg.

**Comment by jasmussen** [comment]
Good discussion here, and nice work overall.

However I feel like the discussion missed a relatively important aspect of the block design principles, the split between basic and advanced functionality. The principles essentially suggest that you should not put anything in the sidebar that is necessary for the basic operation of the block ([the full text](https://wordpress.org/gutenberg/handbook/reference/design-principles/#editor-settings)). 

Those principles are intentionally left up to interpretation, and it is definitely up for debate whether linking an image is _basic_ or _advanced_ functionality. But the net result is that now we have this:

![screen shot 2018-08-07 at 09 44 03](https://user-images.githubusercontent.com/1204802/43761929-d4c5dcf6-9a26-11e8-8120-b0ca5511458b.png)

☝️ In this screenshot, the Settings sidebar is dismissed. How do I link the image?

Note that this is not just about casual users that want a simpler editing experience. It is also an issue when the user is using a plugin, for example "Drop It", which allows you to insert images from Unsplash:

![screen shot 2018-08-07 at 09 48 06](https://user-images.githubusercontent.com/1204802/43762014-0e7c2cf2-9a27-11e8-9c59-8159b01a72fb.png)

**If we feel that linking an image is advanced functionality**, then what is in `master` right now is absolutely the right design.

**If we feel that linking an image is basic functionality**, then we should either consider adding back the link button to the toolbar as it was, or find a way to add the "Links to" functionality to this modal:

![screen shot 2018-08-07 at 09 50 16](https://user-images.githubusercontent.com/1204802/43762122-521da332-9a27-11e8-9f41-43d7a6734761.png)

---

Having written this comment, I'm obviously in the "it's basic functionality" camp. But I'm not strongly so, and I won't argue it to the moon and back. But I have a gut feeling we'll get tickets about this, so it's good to have the discussion.

**Comment by paaljoachim** [comment]
We have the link feature in the toolbar for Paragraph and Heading. To keep it consistent it would be natural to add the link back to the image and gallery toolbar.

**Comment by talldan** [comment]
One way it could be added back in - adding a link via the toolbar could always be treated as a custom link in the Link To setting.

**Comment by jasmussen** [comment]
I like that thought.

If you've already chosen to link to the media file in the inspector, can that link just be prefilled but editable?

**Comment by talldan** [comment]
I think so, and then as soon as it's edited it becomes custom.
