### ISSUE TITLE
Font size setting is not working properly in the Pullquote Gutenberg block in WordPress 6.2.2 running Twenty Twenty-One theme.

### ISSUE THREAD

**Issue by mayurbaroliya-multidots** [WordPress/gutenberg#53107]
### Description

Font size setting is not working properly in the Pullquote Gutenberg block.

### Step-by-step reproduction instructions

1. Create a new page and take the featured Pullquote block.
2. Go to right side Pullquote block setting.
3. And change the font size of the Pullquote block content.
4. WordPress 6.2.2 running
5. Twenty Twenty-One theme.

### Screenshots, screen recording, code snippet

Video URL:- https://share.cleanshot.com/3WzD3PPSC3fw909yxHC1 

### Environment info

- WordPress 6.2.2 running, Twenty Twenty-One theme.
- Chrome browser
- macOS 13.4.1

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I believe this is an issue that will be resolved on the theme side and is also tracked in the core Trac ticket system. Therefore, I would like to close this issue.

[#57854 (Twenty Twenty-One: Pull Quote block font-size issue) – WordPress Trac](https://core.trac.wordpress.org/ticket/57854)
