### ISSUE TITLE
Template parts - General no patterns found after update

### ISSUE THREAD

**Issue by linwoodlana** [WordPress/gutenberg#53111]
### Description

Gutenberg last release: 16.3.0  
All MY Patterns vanished 
My patterns zero? all of them  disappeared after update and template parts General not showing in editor

patterns - Template parts - General

No patterns found, only template parts were not deleted but not showing here.

![Screenshot 7-28-2023 at 02 41 PM](https://github.com/WordPress/gutenberg/assets/18594926/4602fd13-f617-469f-84bd-d7c8312a6694)
![Screenshot 7-28-2023 at 02 42 PM](https://github.com/WordPress/gutenberg/assets/18594926/08b37497-4e72-4a36-9e5d-debd3b9e0c04)

### Step-by-step reproduction instructions

Site editor
Patterns
My patterns 
Template parts/General

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
This issue appears to be resolved in #52961. This PR is part of the next release of Gutenberg 16.4, but has been backported to WordPress 6.3 RC3.

I would like to close this issue, but please feel free to comment if you reproduce this issue in WordPress 6.3 RC3 or Gutenberg 16.4.
