### ISSUE TITLE
Inserter showing recent/most used blocks

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#5312]
I was puzzled when I noticed the inserter showed Cover image and Audio blocks.
(I had forgot that I had earlier tested those blocks.)

![screen shot 2018-02-28 at 10 44 46](https://user-images.githubusercontent.com/5323259/36796797-6eeea3ca-1c74-11e8-828f-0df2806393bf.png)

I am thinking that the Inserter should in general show the blocks that are most likely used and not the last ones used. 

Thoughts?

**Comment by youknowriad** [comment]
Just to clarify, these are not the last ones used, these are the most frequently used blocks.

**Comment by karmatosed** [comment]
This has an issue for using a combination, #5320. In light of that closing this.
