### ISSUE TITLE
Multi-selection: faulty click-and-drag text selection at edges and across blocks

### ISSUE THREAD

**Issue by eidolonnight** [WordPress/gutenberg#53128]
### Description

Click-and-drag selection at the edges of paragraph blocks and across blocks of varying types results in unexpected highlighting and selections.

As demonstrated in the attached video, when using click-and-drag selection, the highlighted selection in the editor may not represent the actual selection that will be copied/pasted. The typical highlight applies to entire blocks while the actual selection may be null, a subset of text, or some combination of nearby blocks.

Similarly, the editor may report "X blocks copied" while the blocks were in fact not copied.

This seems to be a long-standing bug. I had assumed for some time that this was a personal issue, plugin conflict, or browser extension incompatibility, but having taken the time to test in isolation, the issue remains. I've observed this since at least WordPress 6.1.

Shift-click selection does not appear to result in the same behavior.

### Step-by-step reproduction instructions

1. Create a new post or page
2. Insert various paragraph blocks inter-mingled with other blocks
3. Starting mid-paragraph, click and drag to the bottom edge of the block and into the next block
4. Observe highlighted area
5. Copy using keyboard shortcut
6. Paste to verify clipboard contents

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/115154/984502c9-b2e9-4a45-80df-c96ddc2c39f8

### Environment info

Replicated using:
- Mac OS 13.4.1
- WordPress 6.3
- Chrome Version 114.0.5735.248 (Official Build) (arm64)
  - Safari 16.5.2 exhibits slightly different but still unexpected behavior

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@ellatrix  I know you've looked into this and it seems to be intentional for now with some consideration to changing the behavior for multi-select. Curious for your thoughts.

**Comment by annezazu** [comment]
Noting another version of this same issue with a pattern:

https://github.com/user-attachments/assets/0f7c8f71-0b2c-406c-b93c-0e218e6489dc

This is using WP 6.6.1 and GB 19.0.

**Comment by ellatrix** [comment]
Hi @eidolonnight!

This PR should fix the first issue you raised: #64928.

The issue with copying a paragraph + list block, I can't reproduce at the moment. I'd recommend creating a separate issue for that.

Yes, selecting from a paragraph into a list block will trigger full selection. This is a know limitation for now, until I have time to work on selection across different root blocks (the paragraph and list items don't share the same root, the list items are inside a list). I'm not sure if we have a tracking issue for that, so feel free to create one for that also.

**Comment by ellatrix** [comment]
Please submit any remaining issues separately, thank you for the reports!
