### ISSUE TITLE
`__unstableIsBlockBasedTheme` may become undefined in the Site Editor

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#53137]
## What problem does this address?

`__unstableIsBlockBasedTheme` holds the result of whether the currently active theme is a block theme. This property is held in the block editor store and is used, for example

```javascript
const isBlockBasedTheme = useSelect( ( select ) => {
	const settings = select( blockEditorStore ).getSettings();
	return settings.__unstableIsBlockBasedTheme;
}, [] );
```

Using this property is not a problem in most cases, but **on pages where the block editor is not loaded**, this property cannot be retrieved correctly and may cause problems.

For example, there is [`useIsSiteEditorAccessible()` hook](https://github.com/WordPress/gutenberg/blob/6e4bc840699ed2742dba27e585b38ee136f882be/packages/core-commands/src/hooks.js#L8-L16) in the `core-command` package. This hook depends on `__unstableIsBlockBasedTheme` and returns a boolean value. The result of this hook determines [if the Site Editor is accessible and if not, the command is not registered](https://github.com/WordPress/gutenberg/blob/6e4bc840699ed2742dba27e585b38ee136f882be/packages/core-commands/src/site-editor-navigation-commands.js#L127-L133).

However, it is not guaranteed that the block editor will be rendered and `__unstableIsBlockBasedTheme` will be present in a scene where the command palette can be used. For example, the Template Parts List page and the Patterns page in the Site Editor.

If you reload the browser on these pages, `__unstableIsBlockBasedTheme()` will be undefined because the block editor is not present on the page. This means that the command palette described above will not be available.

## What is your proposed solution?

As reported in #52150 and #52154, I believe there will be an increasing reliance on this property for site editor and hybrid theme compatibility. Therefore, I think we need a way to determine if a current theme is a block theme from any context, regardless of whether or not a block editor is present.

For example, since `supportsTemplatePartsMode` resides in the site editor store, it returns accurate results on every page of the Site Editor.

### Screencast

The following screencast describes two issues related to `__unstableIsBlockBasedTheme`.

- If accessed from the root page of the Site Editor, you can execute commands such as "Open navigation", "Open pages", "Open templates", etc. However, if the browser is reloaded on a pattern page where the block editor does not exist, these commands cannot be executed.
- Despite being a block theme, `__unstableIsBlockBasedTheme` is undefined.
- When the Open patterns command is executed, [this conditional statement is not correctly determined](https://github.com/WordPress/gutenberg/blob/6e4bc840699ed2742dba27e585b38ee136f882be/packages/core-commands/src/admin-navigation-commands.js#L46-L58) and the user is directed to the WP-Admin Pattern Post List page instead of the Patterns page in the Site Editor.

https://github.com/WordPress/gutenberg/assets/54422211/f8bc5e12-72d8-48c7-9d2a-f9f697d9e84c

**Comment by ntsekouras** [comment]
Could also checking `wp.data.select('core/edit-site').getSettings().__unstableIsBlockBasedTheme` be enough here? I don't remember exactly what we show/hide if a theme is a hybrid one..

**Comment by t-hamano** [comment]
> `wp.data.select('core/edit-site').getSettings().__unstableIsBlockBasedTheme` be enough here?

Oh, I see that is available in the site editor 😅 However, the problem I'm trying to solve in #53123 is part of the `core-commands` package. Therefore, I am wondering if it is appropriate to add the `edit-site` package to the `core-commands` package.

**Comment by ntsekouras** [comment]
Another option would be to do something like [this](https://github.com/WordPress/gutenberg/pull/52987/commits/df307a20ce048e749e00718a55499a20b8169ec0) and pass options.. We could even make use of `const isSiteEditor = getPath( window.location.href )?.includes(
		'site-editor.php'
	);`.  Not sure yet what would be best, because I'm not sure what screens are allowed in a hybrid theme..

--cc @youknowriad

**Comment by youknowriad** [comment]
Can we rely on `wp.data.select('core').getCurrentTheme().is_block_theme` instead? Maybe we can also remove this unstable setting entirely.

**Comment by t-hamano** [comment]
> Can we rely on `wp.data.select('core').getCurrentTheme().is_block_theme` instead?

Thanks for sharing that API. I tried it with #53123 and it worked as expected.

> Maybe we can also remove this unstable setting entirely.

I would like to close this issue and submit a new issue to remove this unstable setting.
