### ISSUE TITLE
Incorrect dependency values by packages/dependency-extraction-webpack-plugin

### ISSUE THREAD

**Issue by ssovit** [WordPress/gutenberg#53133]
### Description

What I have `import { PluginDocumentSettingPanel } from "@wordpress/edit-post";` used in one of my custom plugin.

The asset dependencies in my `plugin.assets.php` is `wp-editPost` instead of `wp-edit-post`.

The issue seems to on [Line 48 of packages/dependency-extraction-webpack-plugin](https://github.com/WordPress/gutenberg/blob/trunk/packages/dependency-extraction-webpack-plugin/lib/util.js#L48) which is converting dashed dependencies to camelCase

### Step-by-step reproduction instructions

1. Create block plugin (`plugin.jsx`) with with import `import { PluginDocumentSettingPanel } from "@wordpress/edit-post";`
2. Run `wp-scripts build`
3. `plugin.assets.php` has dependency array with `wp-editPost` instead of `wp-edit-post`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @ssovit,

I tested with minimal configuration and could not reproduce it. The file consists of the following:

`package.json`

```json
{
  "name": "test",
  "scripts": {
    "build": "wp-scripts build plugin"
  },
  "dependencies": {
    "@wordpress/scripts": "^26.9.0"
  }
}
```

`plugin.jsx`

```javascript
import { PluginDocumentSettingPanel } from "@wordpress/edit-post"
```

Executing `npm run build` will produce the following `build/plugin.asset.php`

```php
<?php return array('dependencies' => array('wp-edit-post'), 'version' => 'ca7d41db15ebe6d60bd2');
```

I tested on Ubuntu, what is the OS type or `@wordpress/scripts` version?
