### ISSUE TITLE
Site Editor: Snack bar not fixed on certain pages

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#53157]
### Description

Primarily, a snack bar appears in the lower left corner when you perform some action on the block editor. This snack bar is fixed at the lower left corner, even if you scroll the canvas.

However, if the main content is scrollable on the following pages, this snack bar will also be affected by scrolling.

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/e2c579ad-aeb2-4d30-9ebf-6b78736ec337

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I can replicate in 6.3 RC3. Going to add to the 6.3 board but I think this is an okay candidate for 6.3.1 if needs be.
