### ISSUE TITLE
url: `filterURLForDisplay` only considers basic image extensions

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#53154]
Related to #27530

## What problem does this address?

The `filterURLForDisplay()` function in the `url` package properly processes the given URL string and generates a string for display. This function accomplishes two main things:

- Remove protocol and `www` subdomain
- If `maxLength` is given and the URL is a media filename, return the filename containing an ellipsis

Examples of various conversions can be seen in [this unit test](https://github.com/WordPress/gutenberg/blob/aa3bd6b0f656dbb25fe77ce882a8570d2f22b4a4/packages/url/src/test/index.js#L995-L1068).

However, only basic image extensions are considered when rounding strings.

https://github.com/WordPress/gutenberg/blob/aa3bd6b0f656dbb25fe77ce882a8570d2f22b4a4/packages/url/src/filter-url-for-display.js#L24

As a result, URLs in popovers may overflow in `LinkControl` components that use this function, for example.

#### URL with jpg image

![jpg_image](https://github.com/WordPress/gutenberg/assets/54422211/7839c803-eb65-450e-bac9-7735b529363b)

#### URL with webp image

![webp_image](https://github.com/WordPress/gutenberg/assets/54422211/b4a6b603-d2bf-4427-8b67-f0298e99da23)

#### URL with mp4 video

![mp4_video](https://github.com/WordPress/gutenberg/assets/54422211/e7ac2b35-2440-4908-8d67-124b7b63e7b2)

## What is your proposed solution?

I would suggest either of the following approaches:

- Consider all extensions that can be uploaded to WordPress. ([`mime_types` filter](https://github.com/WordPress/wordpress-develop/blob/c676279a1415524893c3921a0510641e972e8918/src/wp-includes/functions.php#L3359) may be helpful)
- All extensions to be rounded up by maxLength

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by brookewp** [comment]
Thanks for opening the issue! I encountered this in the Video block since it uses the same logic. However, I'm not seeing a scroll bar, so the edit button can be difficult to use: 

<img width="351" alt="Screenshot 2023-09-13 at 6 14 34 PM" src="https://github.com/WordPress/gutenberg/assets/35543432/954770aa-bc78-4db3-ac7b-8e9899074e21">
