### ISSUE TITLE
List block: Numbering type selection is not working at not iframe

### ISSUE THREAD

**Issue by shimotmk** [WordPress/gutenberg#53165]
### Description

List block: Numbering type selection is not working at not iframe

The editor is not displayed in an iframe when displaying custom fields.
At that time Numbering type in list block doesn't work.

I think it's related to the pull request below
#51186 #48286

### Step-by-step reproduction instructions

1. Open a Post or Page.
2. Place the list block into an OL tag.
3. Change the Ordered list settings.
4. You can confirm that it does not change when it is not an iframe.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/42362903/bb469c98-dc98-4599-956d-f7e491faf0c9

### Environment
- WordPress: 6.3-RC2
- PHP: 7.4.1
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 7.4.1)
- Browser: Chrome 115.0.0.0 (macOS)
- Theme: Twenty Twenty-Three 1.1
- MU-Plugins: None activated
- Plugins: 
  * WordPress Beta Tester 3.5.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report. Probably the same issue reported in #52826.

**Comment by annezazu** [comment]
Since this seems to be present in WordPress version: 6.2.2 based on the other report, I'm not going to add to 6.3's board.

**Comment by shimotmk** [comment]
Sorry, this is a duplicate issue, so I'll close it.
