### ISSUE TITLE
Image Block: Wide width and full width are not applied correctly

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#53173]
### Description

In WordPress 6.3, if you set the image block to wide or full width, the image will not spread properly in the editor.

This problem occurs even with the latest Gutenberg plugin enabled. Also, it seems to occur when the original size of the image is smaller than the content width; I checked the difference with WordPress 6.2, and it may be due to the width:inherit being applied in this line.

### Step-by-step reproduction instructions

- Add an image block
- Apply Wide Width or Full Width

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/7a3768fe-ef64-42c3-bb98-9ec98c501330

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
The #52286 introduced changes to the Image block markup.

**Comment by t-hamano** [comment]
Another thing I noticed, if Wide Width or Full Width is applied, it would be better to hide all but the Resolution control as before.

## WP 6.2

![image_wp6 2](https://github.com/WordPress/gutenberg/assets/54422211/a07e2505-41ff-449a-b99d-ea8f373575be)

## WP6.3

![image_wp6 3](https://github.com/WordPress/gutenberg/assets/54422211/31ae7422-880d-4dd0-afe8-0ccec6160196)

**Comment by t-hamano** [comment]
I will add this to the Editor Task as I believe this issue is a regression that occurred in WP6.3.
