### ISSUE TITLE
Commands should not require an icon

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#53193]
Not all commands require an icon. In some cases the icons could be distracting—if they're not helping to convey the command context, adding purpose to being rendered. 

I would expect icons to _not_ be required for commands. And if no icon is added, the space where the icon should remain, so that the command labels are always vertically in line. 

### Visual 

<img width="673" alt="commands-w-no-icons" src="https://github.com/WordPress/gutenberg/assets/1813435/b6f5ea55-abd0-457e-a43c-d9ca69cf2a41">

**Comment by KevinBatdorf** [comment]
Do you think it would work better with a default (less prominent) fallback icon like the wp logo or a command specific icon? Your screenshot looks ok given the grouping, but I feel like if that 3rd command _had_ an icon, then the second command without an icon would throw off the look. 

Also, a tool for making icons specifically geared for command like Raycast has ([here](https://icon.ray.so/)) would be a nice edition.

**Comment by richtabor** [comment]
I'm more concerned about scan-ability, rather than the looks. Especially in use cases where there will be a lot of results with the same icon, like https://github.com/WordPress/gutenberg/pull/52509.
