### ISSUE TITLE
Daniel's writing flow observations

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#53196]
Using this as a tracking issue for writing flow quirks I observe:

* [ ] https://github.com/WordPress/gutenberg/issues/48040
* [ ] https://github.com/WordPress/gutenberg/issues/47200
* [ ] https://github.com/WordPress/gutenberg/issues/53195
* [ ] https://github.com/WordPress/gutenberg/issues/53202
* [x] https://github.com/WordPress/gutenberg/issues/40907

**Comment by annezazu** [comment]
@jordesign let's reserve overview for breakdowns of larger initiatives. @ellatrix for considering these writing flow issues!

**Comment by danielbachhuber** [comment]
@annezazu One exercise that might be helpful to embark upon at some point: compare and document Block Editor writing flow against Google Docs, Microsoft Word, etc. It seems like we could crowdsource this pretty easily. Even if we choose not to address the gaps, I think it'd be helpful to have them documented.

**Comment by ellatrix** [comment]
@danielbachhuber Been dreaming about that! Some sort of editing standard spec, maybe even in the form of e2e tests (that could potentially be run on any web editor).

**Comment by ellatrix** [comment]
@danielbachhuber I'm going to close this issue in favour of #63255, where I added the remaining open items (except for #53195, which needs a bigger discussion).

**Comment by danielbachhuber** [comment]
@ellatrix Sounds great, thanks!
