### ISSUE TITLE
Prevent snackbars from stacking up by adding a max count

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#53201]
Snackbars should have a max count, where you can't end up with a stack of them hanging around. https://github.com/WordPress/gutenberg/issues/53200 will reduce the number, but there should be a max. Even as small as three notice max may work just fine. 

<img width="387" alt="CleanShot 2023-07-31 at 17 44 16" src="https://github.com/WordPress/gutenberg/assets/1813435/7e25b5ca-e6c3-4ee0-ac11-5aaa1d3aede2">

**Comment by glendaviesnz** [comment]
Also, each notice type should have a unique id [as done here](https://github.com/WordPress/gutenberg/pull/53087) so that only one of that notice type appears at a time.

**Comment by richtabor** [comment]
> Also, each notice type should have a unique id https://github.com/WordPress/gutenberg/pull/53087 so that only one of that notice type appears at a time.

Yea, perhaps the copy to clipboard snackbar doesn't have one?

**Comment by Mamaduka** [comment]
I like how this library, [Sonner](https://sonner.emilkowal.ski/), handles stacking and multiple snackbars/toasts.

**Comment by richtabor** [comment]
> I like how this library, [Sonner](https://sonner.emilkowal.ski/), handles stacking and multiple snackbars/toasts.

Very cool! What do we need to do to try this interaction in the editor?

For reference: 

https://github.com/WordPress/gutenberg/assets/1813435/010ceaae-fc7b-484f-b772-5e5d66408382

**Comment by Mamaduka** [comment]
I think it would require an update to the `SnackbarList` component.

@mirka, how doable is this with current snackbar components?

**Comment by jasmussen** [comment]
Yes please 🙏

**Comment by mirka** [comment]
> I think it would require an update to the `SnackbarList` component.
> 
> @mirka, how doable is this with current snackbar components?

Architecturally it seems feasible to me, since `SnackbarList` has full control over how the notice data objects are rendered. Most of the complexity would be in getting the interactive animations right.
