### ISSUE TITLE
Not possible to tab back into the title field after tabbing out of it

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#53202]
See video:

https://github.com/WordPress/gutenberg/assets/36432/c58765dd-4599-41c5-9df4-53b3d604b979

**Comment by t-hamano** [comment]
I believe you can return to the title field by pressing the up arrow key when the paragraph is in focus, just as you press the down arrow key when moving from the title field to an empty paragraph.

https://github.com/WordPress/gutenberg/assets/54422211/6f5dab42-5a8a-411d-aa50-7504df81ee2c

**Comment by t-hamano** [comment]
@danielbachhuber 

Returning to the title field with the tab key is probably not intended, and you can return with the arrow keys, so I don't think this behavior is a bug.

I would like to close this issue, but if there is anything I have missed, please comment.
