### ISSUE TITLE
Caption does not appear if image uploaded directly to image block

### ISSUE THREAD

**Issue by carlseibert3** [WordPress/gutenberg#5321]
## Issue Overview

(This is Gutenberg 2.2.0)
If an image is uploaded to Media Library, then placed in an image block, the caption is filled - as expected - from the IPTC caption that was imported with the image.
![screen shot 2018-02-28 at 7 18 54 pm](https://user-images.githubusercontent.com/36741967/36820786-aa8b3670-1cbd-11e8-9d96-edfebfca079f.jpg)

If the image is uploaded from within the image block, the caption is blank (placeholder text appears)
![screen shot 2018-02-28 at 7 18 43 pm](https://user-images.githubusercontent.com/36741967/36820813-c5607140-1cbd-11e8-8148-f37ed92648c5.jpg)

Regardless of which way the image was uploaded, the mapped IPTC caption appears correctly when the image is viewed in Media Library.
![screen shot 2018-02-28 at 7 19 36 pm](https://user-images.githubusercontent.com/36741967/36820828-d76feb68-1cbd-11e8-9ef3-130535577c19.jpg)

Drag and drop into the image block produces the same result as using the upload button within the image block.

## Steps to Reproduce (for bugs)

1. From an image block in post, use the upload button to upload an image with an embedded IPTC caption (caption needs to be in the IIM data block, 'cause that's the only one we read.)
2.Note that caption is absent.
3.Upload another image with caption to the Media Library.
4.From another image block in post, choose to select image from Media Library and select the image from step 3.
5.Note that caption appears as expected.
6.In Media Library, note that caption appears as expected in our caption field on both images.

I did this on a MAMP local server, but I would expect similar behavior on a live server.  I used Chrome 64.
## Expected Behavior

IPTC caption should map to caption in post.

## Current Behavior

IPTC caption behaves as expected if photo is selected from Media Library, but does not if photo is uploaded from within image block.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jorgefilipecosta** [comment]
Thank you for reporting this problem @carlseibert3, a PR that addresses this problem was submitted: https://github.com/WordPress/gutenberg/pull/5337.
