### ISSUE TITLE
"@wordpress/scripts" seems to be incompatible with "node v20.x".

### ISSUE THREAD

**Issue by stein2nd** [WordPress/gutenberg#53213]
### Description

I report that I ran "npm install @wordpress/scripts --save-dev" and got the following WARN.:

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-jsdoc@39.9.1',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || ^17 || ^18 || ^19' },
npm WARN EBADENGINE   current: { node: 'v20.5.0', npm: '9.8.0' }
npm WARN EBADENGINE }

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@es-joy/jsdoccomment@0.36.1',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || ^17 || ^18 || ^19' },
npm WARN EBADENGINE   current: { node: 'v20.5.0', npm: '9.8.0' }
npm WARN EBADENGINE }

npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

When I ran "npm install -D eslint eslint-plugin-jsdoc @es-joy/jsdoccomment" individually, no warn showed up.

### Step-by-step reproduction instructions

1. Using Terminal, run "npm install -D @wordpress/scripts".

### Screenshots, screen recording, code snippet
![image](https://github.com/WordPress/gutenberg/assets/531628/fdad7604-3c5d-462c-9c57-0d5b38037c14)

![image](https://github.com/WordPress/gutenberg/assets/531628/bcb5be93-1723-411b-a244-66b5b05e5a3f)

![image](https://github.com/WordPress/gutenberg/assets/531628/1763c024-8e5a-482f-8586-a3df1cb795cf)

_No response_

### Environment info

- Device: macOS Ventura 13.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by stein2nd** [comment]
Additional information (2023-08-02 11:47 JST).

- Below are the versions of "eslint-plugin-jsdoc" and "@es-joy/jsdoccomment" when installed individually:
  - eslint-plugin-jsdoc: 46.4.5
  - @es-joy/jsdoccomment: 0.39.4

- The following is the result of running "npm ls stable":
  - └─┬ @wordpress/scripts@26.9.0
    - └─┬ @svgr/webpack@6.5.1
      - └─┬ @svgr/plugin-svgo@6.5.1
        - └─┬ svgo@2.8.0
          - └── stable@0.1.8

**Comment by stein2nd** [comment]
When svgo@3.0.2 was installed separately, the "deprecated stable@0.1.8" warning did not appear.

In other words, maybe @wordpress/scripts should install @svgr/webpack@8.0.1 instead of @svgr/webpack@6.2.1.

**Comment by stein2nd** [comment]
- The following is the result of running "npm ls eslint-plugin-jsdoc": 
  - ├─┬ @wordpress/scripts@26.9.0
    - │ └─┬ @wordpress/eslint-plugin@14.11.0
      - │   └── eslint-plugin-jsdoc@39.9.1
  - └── eslint-plugin-jsdoc@46.4.5  <- manual installed

- Next, the following is the result of running "npm ls @es-joy/jsdoccomment":
  - ├── @es-joy/jsdoccomment@0.39.4 <- manual installed
  - ├─┬ @wordpress/scripts@26.9.0
    - │ └─┬ @wordpress/eslint-plugin@14.11.0
      - │   └─┬ eslint-plugin-jsdoc@39.9.1
        - │     └── @es-joy/jsdoccomment@0.36.1
  - └─┬ eslint-plugin-jsdoc@46.4.5 <- manual installed
    -   └── @es-joy/jsdoccomment@0.39.4 deduped

Therefore, maybe @wordpress/eslint-plugin should install eslint-plugin-jsdoc@46.4.5 instead of eslint-plugin-jsdoc@39.6.9.

**Comment by stein2nd** [comment]
The following is the result of running "npm-check-updates" against "@wordpress/dependency-extraction-webpack-plugin/package.json":
- webpack-sources  ^3.2.2  →  ^3.2.3

Next, the following is the result of running "npm-check-updates -u" and "npm update" against "@wordpress/dependency-extraction-webpack-plugin/package.json", which completed successfully.

**Comment by stein2nd** [comment]
The following is the result of running "npm-check-updates" against "@wordpress/element/package.json":
- @babel/runtime     ^7.16.0  →   ^7.22.6
- @types/react      ^18.0.21  →  ^18.2.18
- @types/react-dom   ^18.0.6  →   ^18.2.7
Next, the following is the result of running "npm-check-updates -u" and "npm update" against "@wordpress/element/package.json, which completed successfully.

**Comment by stein2nd** [comment]
The following is the result of running "npm-check-updates" against "@wordpress/escape-html/package.json":
- @babel/runtime  ^7.16.0  →  ^7.22.6
Next, the following is the result of running "npm-check-updates -u" and "npm update" against "@wordpress/escape-html/package.json", which completed successfully.

**Comment by stein2nd** [comment]
The following is the result of running "npm-check-updates" against "@wordpress/jest-console/package.json":
- @babel/runtime      ^7.16.0  →  ^7.22.6
- jest-matcher-utils  ^29.5.0  →  ^29.6.2
Next, the following is the result of running "npm-check-updates -u" and "npm update" against "@wordpress/jest-console/package.json", which completed successfully.

**Comment by stein2nd** [comment]
The following is the result of running "npm-check-updates" against "@wordpress/jest-preset-default/package.json":
- babel-jest  ^29.5.0  →  ^29.6.2

Next, the following is the result of running "npm-check-updates -u" and "npm update" against "@wordpress/jest-preset-default/package.json", which completed successfully.

**Comment by stein2nd** [comment]
The following is the result of running "npm-check-updates" against "@wordpress/stylelint-config/package.json":
- stylelint-config-recommended       ^6.0.0  →  ^13.0.0
- stylelint-config-recommended-scss  ^5.0.2  →  ^12.0.0

Next, the following is the result of running "npm-check-updates -u" and "npm update" against "@wordpress/stylelint-config/package.json":
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @wordpress/stylelint-config@21.21.0
npm ERR! Found: stylelint@14.16.1
npm ERR! node_modules/stylelint
npm ERR!   peer stylelint@"^14.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer stylelint@"^15.10.0" from stylelint-config-recommended@13.0.0
npm ERR! node_modules/stylelint-config-recommended
npm ERR!   stylelint-config-recommended@"^13.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by mikeybinns** [comment]
I am also running into this issue with `@es-joy/jsdoccomment`, and it seems like `eslint-plugin-jsdoc` in `eslint-plugin` is the way to fix it for me

**Comment by gziolo** [comment]
I opened #53629 which tries to fix the issue with `eslint-plugin-jsdoc`.

**Comment by gziolo** [comment]
I also opened https://github.com/WordPress/gutenberg/pull/53630 to see what's required to get rid of the deprecated `stable@0.1.8` deep dependency.
