### ISSUE TITLE
Social Links Block: update Twitter Logo

### ISSUE THREAD

**Issue by jeherve** [WordPress/gutenberg#53223]
## What problem does this address?

Twitter recently updated its branding from Twitter to "X". We may want to update references to Twitter in the Social Links block to match the new branding.

## What is your proposed solution?

The "X" logo is currently an interim logo, but once the new logo is unveiled we may want to update all "Twitter" references to "X".

**Comment by richtabor** [comment]
I think we'd want to add the X logo in addition to the Twitter logo; less forceful of a change on our end. And ensure there's a keyword so it can be found when searching for `twitter`.

**Comment by t-hamano** [comment]
Update: It looks like the Brand toolkit for the new logo has been released.
https://about.twitter.com/en/who-we-are/brand-toolkit

**Comment by bgardner** [comment]
I'd like to see this icon included, and possibly added to the WP 6.3.1 release, given the amount of people who will likely want to use it. (Waiting 3 months for 6.4 might seem too far off.)

**Comment by t-hamano** [comment]
This issue may be a bit daunting because it involves the entire WordPress project 😅

As far as I can think, at least for Gutenberg alone, we will need to change the brand name string (from "Twitter" to "x" or "𝕏"  ), update the Social Link block and update the Embed block.

The following tickets have been submitted for the core: https://core.trac.wordpress.org/ticket/59012

**Comment by richtabor** [comment]
> we will need to change the brand name string (from "Twitter" to "x" or "𝕏" ), update the Social Link block and update the Embed block.

Like I mentioned earlier, I think this should be _in addition_ to the existing Twitter social link variation.

**Comment by t-hamano** [comment]
> Like I mentioned earlier, I think this should be in addition to the existing Twitter social link variation.

I see. So it would be like this?

![twitter](https://github.com/WordPress/gutenberg/assets/54422211/5c2beb67-ffc2-4346-9adb-99bb6912fbc1)

**Comment by richtabor** [comment]
No, sorry. I meant leaving the Twitter variant as-is — but in addition, have the "X" variant. We could use a `twitter` keyword on the X variant though (not the title).

**Comment by PeopleInside** [comment]
When I can see this available on Gutemberg editor?
How can I have this fix?

**Comment by t-hamano** [comment]
Hi @PeopleInside,

#54092 is part of Gutenberg 16.7. In other words, it is built into WordPress 6.4. You can see this icon in the recently released WordPress6.4 Beta1.

**Comment by He-Man321** [comment]
I have just upgraded to WP 6.4.1 but I still have the old Twitter icon.  Is there something else I need to do?

**Comment by PeopleInside** [comment]
> I have just upgraded to WP 6.4.1 but I still have the old Twitter icon. Is there something else I need to do?

I replied here: https://wordpress.org/support/topic/update-twitter-social-icon-x/#post-17210637

**Comment by He-Man321** [comment]
Just to add, as it confused me, you have to change the icon to the new one manually by editing the block (or adding a new one).  The new X is now in the selector, but so is the old bird icon, so you have to manually change it.  This is fine, but at first I assumed it would update automatically, which it does not.

Also, some themes have their own 'social' settings, and these may not have been updated yet (as with the Hueman theme in my case).
