### ISSUE TITLE
Editor "Code Editor" mode allows pasting of blocks with "parent" outside of said parents

### ISSUE THREAD

**Issue by albanyacademy** [WordPress/gutenberg#53244]
### Description

Code editor mode allows user to bypass inability to paste blocks outside of their specific parents.

### Step-by-step reproduction instructions

1. Add a new post
2. See that you cannot add the core/query-pagination block by itself
3. Add a query block, and copy the pagination block by itself
4. Create a paragraph block, and paste in the copied pagination block.
5. Observe that nothing happens.
6. Go into "code editor" mode, and replace the post content with only the pagination block
7. Observe that the pagination block is now on the page, outside of its parent query block.
8. **Observe that in the front-end, the pagination block does not show up on the page at all.**

step 8 appears to be limited to any blocks that rely exclusively on server-side rendering, such as pagination and social-link. Blocks which save HTML content, such as list-item, are not affected by this.

### Screenshots, screen recording, code snippet

https://www.screencast.com/t/kYGTu4Wp1ys

### Environment info

Wordpress 6.2.2, no plugins installed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by stacimc** [comment]
Tested on GB trunk according to the testing instructions and confirmed the current behavior with List/List Item and Social Links/Social Link.

| Code Editor | Appearance in block editor | Appearance on frontend |
| --- | --- | --- |
| <img width="301" alt="Screenshot 2023-08-02 at 11 47 46 AM" src="https://github.com/WordPress/gutenberg/assets/63313398/9ee17d21-c870-4159-8b57-9819602fd224"> | <img width="318" alt="Screenshot 2023-08-02 at 11 48 48 AM" src="https://github.com/WordPress/gutenberg/assets/63313398/93b5f2d1-c66f-42eb-bbdf-4cba8fb66f7c"> | <img width="218" alt="Screenshot 2023-08-02 at 11 48 53 AM" src="https://github.com/WordPress/gutenberg/assets/63313398/c870f512-226f-4b6c-9c1f-b9dc644323f6"> |
| <img width="981" alt="Screenshot 2023-08-02 at 11 48 00 AM" src="https://github.com/WordPress/gutenberg/assets/63313398/17d35075-4586-49dc-ae82-0e82b690b1b0"> | <img width="198" alt="Screenshot 2023-08-02 at 11 39 25 AM" src="https://github.com/WordPress/gutenberg/assets/63313398/45a74293-8925-4b87-bf8f-4ddbd4f2585f"> | <img width="250" alt="Screenshot 2023-08-02 at 11 39 34 AM" src="https://github.com/WordPress/gutenberg/assets/63313398/fe661ba0-7488-4ec2-87d6-8445bbc55922"> |

**Comment by ndiego** [comment]
Hi @albanyacademy, thanks for reporting. This is expected. The Code Editor should be considered a "power user" tool, and breaking things or using the block in unintended ways is possible. 

That said, you can disable access to the Core Editor so users can not unintentionally break things. Here is some sample code that restricts Code Editor access to Administrators:

```php
/**
 * Restrict access to the locking UI and the Code Editor
 * to Administrators.
 * 
 * @param array $settings Default editor settings.
 * @param WP_Block_Editor_Context $context The current block editor context.
 */
function example_theme_restrict_locking_ui( $settings, $context ) {
    $is_administrator = current_user_can( 'activate_plugins' );

    if ( ! $is_administrator ) {
        $settings[ 'canLockBlocks' ] = false;
        $settings[ 'codeEditingEnabled' ] = false;
    }

	return $settings;
}
add_filter( 'block_editor_settings_all', 'example_theme_restrict_locking_ui', 10, 2 );
```

**Comment by albanyacademy** [comment]
Thanks for the response, opened a feature ticket to address the lack of visual feedback.
