### ISSUE TITLE
useMediaQuery can throw a fatal error in Safari

### ISSUE THREAD

**Issue by sirbrillig** [WordPress/gutenberg#53251]
### Description

We see a number of fatal errors recorded in our web app (WordPress.com) which look like this:

```
TypeError: t.addEventListener is not a function. (In 't.addEventListener(\"change\",e)', 't.addEventListener' is undefined); Stack: subscribe@https:\/\/wordpress.com\/calypso\/evergreen\/80998.92f5bc1f27be58bbb686.min.js:2:191882
```

I've traced this back to the `useMediaQuery` hook in the `@wordpress/compose` package. [Here is the line where the error happens specifically](https://github.com/WordPress/gutenberg/blob/trunk/packages/compose/src/hooks/use-media-query/index.js#L41). There is already a guard for a null `mediaQueryList` above it, so for this to occur, `window.matchMedia()` would have to return an object, just not an object that has an `addEventListener` function. That seems impossible based on the MDN info about `matchMedia` but it clearly happens a lot.

All the errors show this happens in Safari 13.1, which must have a broken implementation of `matchMedia`. That's annoying but fortunately the fix is very simple. We could modify `useMediaQuery()` to check for the existence of `mediaQueryList.addEventListener` before calling it. 

### Step-by-step reproduction instructions

I haven't tried this myself, but I believe the reproduction would be:

1. Use Mac OS Safari 13.1.
2. Visit any system using `useMediaQuery` or any of its callers like `useViewportMatch`.
3. See the fatal error, `t.addEventListener is not a function` in the console.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
The listeners can be reverted to deprecated [`addListener`](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener) and [`removeListener`](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/removeListener). Safari 14+ supports MediaQueryList  `change` [event](https://caniuse.com/mdn-api_mediaquerylist_change_event) and shouldn't trigger an error.

I wonder what's the global usage of Safari < 14 and if the block editor should support it.

**Comment by sirbrillig** [comment]
Even if we decide not to support Safari 13, I think it would be nice for it not to crash. A block like this would be enough to ensure that, although I guess it would hide the fact that `useMediaQuery` wasn't working.

```js
if ( ! mediaQueryList.addEventListener ) {
  return () => {};
}
```

**Comment by Mamaduka** [comment]
@sirbrillig, yeah, that would just hide the fact that the hook doesn't work with older Safari.

Based on the [Browser Support](https://make.wordpress.org/core/handbook/best-practices/browser-support/) and [linked stats page](https://caniuse.com/usage-table), I think there's no need to support Safari 13.

**Comment by sirbrillig** [comment]
That's fair. What if we added something like this to at least make the failure more explicit?

```js
if ( ! mediaQueryList.addEventListener ) {
  throw new Error( 'This browser does not support useMediaQuery.' );
}
```

That would read better than `t.addEventListener is not a function`. After all, iOS users often don't have much of a choice when it comes to the browser they use and some will certainly be using older versions. This might help with debugging.
