### ISSUE TITLE
WP 6.3 RC3 Breaks Classic Block - Can no longer edit content in block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#53258]
### Description

WP 6.3 RC3 Breaks the Classic Block. When you click on the block it doesn't insert the cursor which means you can no longer edit the content

vid: https://share.getcloudapp.com/2Nup9QgN

### Step-by-step reproduction instructions

Edit page with Classic Block
Click on Block and try to edit content

### Environment info

WP 6.3 RC 3 (Core only, no Gutenberg plugin)
macOS Ventura 13.4.1
Firefox 116.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
The editing was moved into a modal; you should see an "Edit" button in the toolbar.

IIRC, it was needed for TinyMCE to work with iframed editors.


## Screencast

https://github.com/WordPress/gutenberg/assets/240569/3dd807b3-1814-45a6-83d8-28987945f9be

**Comment by maddisondesigns** [comment]
WOW! I can't put into words how absolutely horrible that decision is. **A)** Not only is it in a popup to start with but **B)** The popup editing area is only 529px wide and you can't even resize it.

Maybe you should have taken this limitation into consideration before putting the whole editor within an iFrame.

Why does the whole editor need to be contained within an iFrame anyway? Are you seriously telling me it's impossible to build a modern page editing experience that isn't contained within an iFrame??

This Classic Editor popup is such a horrible experience for the end user. Gutenberg is going from bad to worse with every major release. Your constant hiding of tools and options behind multiple tabs, menus, multiple popups and icons makes the whole editing experience slow, cumbersome, unintuitive, and just overall awful. And now you have a single stand-alone block that behaves completetely different to every other block, and that you can no longer edit inline because it apparently needs to display in a popup.

**Comment by hanneslsm** [comment]
@maddisondesigns Even this is a bit off topic and I am really just curious: what's a common use case where you would use the classic editor instead of converting the content to blocks?

**Comment by t-hamano** [comment]
> Why does the whole editor need to be contained within an iFrame anyway? Are you seriously telling me it's impossible to build a modern page editing experience that isn't contained within an iFrame??

I think this article will help you understand why the editor is iframed.

[Blocks in an iframed (template) editor – Make WordPress Core](https://make.wordpress.org/core/2021/06/29/blocks-in-an-iframed-template-editor/)

**Comment by maddisondesigns** [comment]
@hanneslsm Editing text heavy content, where every single paragraph is a block, is a HUGE pain in the ass. Gutenberg devs seem to think that the only way people edit content, is by rearranging paragraphs, thereby justifying having every single paragraph in their own block. It's obviously not. Rearranging text content by constantly having to copy text from one block to another is incredibly cumbersome, slow and awkward. Editing your content within a single editor, especially when you're not needing to adjust formats like padding, margin, font size etc.., is ten times quicker, at the bare minimum. Well, it used to be anyway. Now that the Classic Block is showing in a tiny popup (that you can't even adjust), you've successfully made this content cumbersome to edit as well. Congrats!!

There are literally millions of sites out there where people have content still contained in the Classic Block. Every site that was in existence before Gutenberg was in core (and using the core "Classic Editor"), is going to have all their old content contained in a Classic Block. Do you seriously think that everybody went back to every single page and converted them into blocks? Likewise, when and if they need to re-edit that content in the future, they're more than likely not going to convert it into blocks either. Why would they, when they can simply edit their content like before? That would mean that they'd have to spend extra time checking over the whole page again just to make sure that everything converted properly and that nothing was messed up.

**Comment by maddisondesigns** [comment]
@t-hamano Thanks for that link. There seems to be very little benefit in introducing this iFrame that couldn't be solved in other ways. The issues mentioned regarding css conflict could've have been completely avoided from the get-go if the Editor styles weren't so atrocious. From day one, it's been a nightmare trying to get your theme to look the same in the editor and front-end. It seems like you're only introducing this iFrame to solve the issues that Gutenberg created themselves through horribly coded styles.

That post mentions "We currently only iframe new editors". What does this mean? I've just tested multiple sites with 6.3RC3. One site showed the editor in an iFrame, but other sites didn't. There seems to be no clear indication as to why this is. Does it mean that it's used only on newly created sites? Only on newley created pages? Only on sites that are using newer Block Themes? Based on my quick testing across multiple sites, none of these seem to be the case.

**Comment by maddisondesigns** [comment]
If the Classic Editor is to remain in that popup, then users need to be able to resize it. A static 529px width is not good enough.

**Comment by ramonjd** [comment]
As well as revisiting the default dimensions, would a fullscreen toggle option be useful in this instance?

https://github.com/WordPress/gutenberg/assets/6458278/c0f34d9c-4727-4030-84fc-840da0eb5e90

Ignore the design :) This was a quick test adding a fullscreen toggle button to the `<Modal />` component.

**Comment by maddisondesigns** [comment]
@ramonjd Definitely! A full-screen toggle like that would make a huge improvement to that tiny popup. Thanks.

**Comment by ramonjd** [comment]
Got a proposal PR up to allow toggling fullscreen mode in the modal first. Let's see how that flies:

- https://github.com/WordPress/gutenberg/pull/53328

**Comment by maddisondesigns** [comment]
@ramonjd Thanks for creating that PR. It's much appreciated.

**Comment by ramonjd** [comment]
Here's the follow up:

- https://github.com/WordPress/gutenberg/pull/53449
