### ISSUE TITLE
Details Block: Add layout support and opt-in to spacing.blockGap

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#53252]
## What problem does this address?

As suggested in #53155, some folks working on themes would like to add the ability to control block spacing in the new Details block. In order to do that, we will likely need to add layout support to the Details block.

Related issues:

* blockGap: https://github.com/WordPress/gutenberg/issues/43243
* layout: https://github.com/WordPress/gutenberg/issues/43248

## What is your proposed solution?

* Look into opting the Details block in to the layout block support.
* In the process, replace the hard-coded styling rules for the Details block that currently depend on the root block gap CSS var (`--wp--style--block-gap`).
* Factor in how should spacing between the summary and other blocks within `details` work? (spacing between the summary and inner blocks).
* Opt-in to `spacing.blockGap` so that block spacing can be controlled at the individual block level.

**Comment by webmandesign** [comment]
Not sure if it's beneficial, but maybe `core/post-author-biography` block could get `blockGap` support too?
(as per [your comment](https://github.com/WordPress/gutenberg/issues/53155#issuecomment-1661355427) and [my comment](https://github.com/WordPress/gutenberg/issues/53155#issuecomment-1661446233))

**Comment by tellthemachines** [comment]
I'm thinking maybe just give it flow layout? Or would there be any value to allowing constrained too?

**Comment by andrewserong** [comment]
> I'm thinking maybe just give it flow layout? Or would there be any value to allowing constrained too?

👍 I reckon just flow layout would be a good place to start, and I imagine that would cover most use cases since it's likely that `details` will be added within post content or somewhere else that's already within a constrained layout.

**Comment by tellthemachines** [comment]
Did a quick PR to see how it works: https://github.com/WordPress/gutenberg/pull/53282
