### ISSUE TITLE
Group block orientation specific (horizontal & vertical) block spacing setup

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#53255]
## What problem does this address?

I think Group block would benefit from (optional, meaning linked together by default - #53151) separate orientation setup for block spacing.

Especially when Group block is being used as a _Row_ and _wrapping to multiple lines_ is enabled, having separate **horizontal** and **vertical** block spacing/gap setup is useful. It improves responsive design as I am able to set smaller vertical gap between wrapped inner blocks.

Currently the block spacing is set to `"blockGap": true,` in [Group block JSON](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/group/block.json).

## What is your proposed solution?

Would be great if block spacing was set to:
```json
"blockGap": {
	"sides": [ "horizontal", "vertical" ]
},
```

(Maybe the ideal solution would be to have orientation specific block spacing setup enabled only for Row mode of Group block, but I'm not sure whether this is possible in Gutenberg.)

**Comment by andrewserong** [comment]
Thanks for opening this follow-up issue! There's an earlier issue that's requesting the same feature, I believe, over in #47084, so I'll close this one as a duplicate. Let me know if you don't think that covers it, though, and we can re-open.

**Comment by webmandesign** [comment]
Thanks for pointing me to the correct issue and sorry for duplicate.

**Comment by andrewserong** [comment]
Not a worry at all, thank _you_ for raising these issues and contributing to the discussion! 🙂
