### ISSUE TITLE
Recovery Attemp error on changing paragraph block to heading

### ISSUE THREAD

**Issue by ethicaladitya** [WordPress/gutenberg#53261]
### Description

I am adding a paragraph block to the Gutenberg editor, and then trying to edit the same in HTML by changing p tag with H1 causing it to break the block and throwing the error "The block contains unexpected or invalid content." which looks like a bug. 

### Step-by-step reproduction instructions

Add a Paragraph block in Gutenberg
Edit the block with HTML
Change p with h1
Click "Edit Visually"

### Screenshots, screen recording, code snippet

https://monosnap.com/file/nZkP0Vn7XiZyK5FpHLyoKLhhD4SL2j

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @ethicaladitya,

I think that error is expected.

As you can see in the code editor, the block HTML has comment delimiters above and below that indicate what the block is.

```html
<!-- wp:paragraph -->
<p>Hello World</p>
<!-- /wp:paragraph -->
```

So if you just change the element name to the `h` element, the block will not be considered a heading and the block will be broken.

If you want to change a paragraph block into a heading, you can use the block toolbar. Or you can use [the shortcut](44681).

**Comment by jordesign** [comment]
I'd agree with @t-hamano  - this behaviour is as expected - and using the shortcut is the best way to transform an element like that. Being the case - I'm going to close this Issue.
