### ISSUE TITLE
2 Problems with setup() method in the RequestUtils class of @wordpress/e2e-test-utils-playwright

### ISSUE THREAD

**Issue by kopepasah** [WordPress/gutenberg#53277]
### Description

While I know `@wordpress/e2e-test-utils-playwright` is under active development, when working with the package it was expected that I could use `RequestUtils.setup()` to make WP REST API requests; however, I am experiencing two different issues when trying to use this setup method:

## Issue 1: Unable to pass custom baseURL

I am unable to change the `baseURL` by passing a custom url within the `RequestUtils.setup( { baseUrl: 'http://example.com' } )`. This could be expected behavior, because I can pass the `WP_BASE_URL` as an environment variable (i.e. `WP_BASE_URL=http://example.com npx playwright test`), but it seems that this parameter [_should_ be overwritten within the `setup()` method](https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-test-utils-playwright/src/request-utils/index.ts#L62C3-L62C3).

You can see an example of this problem within `custom-baseURL` branch of this repo: https://github.com/kopepasah/wp-playwright-request-utils-test/tree/custom-baseURL

## Issue 2: Multiple requests causes random failures

When running requests using `RequestUtils.setup()` and `npx playwright test`, I cannot make multiple requests, as one of the two requests will always fail (which one is random). You can see and an example of this problem in the `multiple-requests` branch of this repo: https://github.com/kopepasah/wp-playwright-request-utils-test/tree/multiple-requests

Now, I can see that the [Gutenberg e2e](https://github.com/WordPress/gutenberg/tree/fb428fc726511c04cb69b22a8ef95c87cf87b132/test/e2e) tests are [setting up their own `requestContext` in Playwright](https://github.com/WordPress/gutenberg/blob/fb428fc726511c04cb69b22a8ef95c87cf87b132/test/e2e/config/global-setup.ts#L17), but it seems odd that the RequestUtils class does not perform that setup automatically, as it is [expected that `RequestUtils.setup()` will handle this here](https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-test-utils-playwright/src/request-utils/index.ts#L86C18-L86C18). I have not tried the newContext in Playwright (like the Gutenberg e2e tests) way yet, because I was hoping this setup will be handled by the RequestUtils class.

---

Thanks for taking a look, and all help is appreciated!

### Step-by-step reproduction instructions

Please visit this repo for reproducing these issues: https://github.com/kopepasah/wp-playwright-request-utils-test/

This repo is a blank plugin, which installs the lates WordPress using `@wordpress/env`. In addition, it installs and sets up `@playwright/test` and `@wordpress/e2e-test-utils-playwright` for testing.

### Environment info

```
"@playwright/test": "^1.36.2",
"@wordpress/e2e-test-utils-playwright": "^0.6.0"
```

Regarding this issue, the WordPress and Gutenberg versions are not relevant, and all other code is default WordPress.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kou029w** [comment]
> Issue 1: Unable to pass custom baseURL

It appears to me that perhaps rewriting this line as follows should solve the problem:

https://github.com/WordPress/gutenberg/blob/e2941e9741bb8e21f0d7965d6bf70d43113bade2/packages/e2e-test-utils-playwright/src/request-utils/rest.ts#L27

```js
	const response = await request.head( '' );
```

But I did not know if this method was good or not.

**Comment by kopepasah** [comment]
Following up on this issue, and I can confirm it is **resolved**. I can pass `baseURL` to `RequestUtils.setup()` as needed.
