### ISSUE TITLE
Comments Block: Default Avatar returning 404

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#53279]
### Description

When viewing the Comments block (in single post, or page templates) the default avatars are returning broken images. Viewing the console shows that the URL `https://secure.gravatar.com/avatar/?d=mm&f=y&r=g&s=80` is returning a 404.

### Step-by-step reproduction instructions

1. Open the Site Editor and view a single or page template which contains a Comments block.

### Screenshots, screen recording, code snippet

<img width="1705" alt="Screenshot 2023-08-03 at 11 57 30 am" src="https://github.com/WordPress/gutenberg/assets/1842363/b790f221-74fe-4703-9c9d-765be1a842be">

### Environment info

Wp 6.3 RC3
No plugins
TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I was able to reproduce the problem in the environment started with wp-env, although the URL is slightly different.

![comment](https://github.com/WordPress/gutenberg/assets/54422211/7e7b3dca-e043-49c1-a633-4e7388f52e64)

Edit: I was able to reproduce the avatar block by itself.

**Comment by t-hamano** [comment]
The fundamental problem may be that the `avatarURL` returned by the [`ueDefaultAvatar()` hook](https://github.com/WordPress/gutenberg/blob/b56fadd89409a22b5a717a8a2f67a7438782ac1a/packages/block-library/src/avatar/hooks.js#L19-L26) is somehow inaccessible.

```javascript
wp.data.select('core/block-editor').getSettings().__experimentalDiscussionSettings.avatarURL
```

**Comment by t-hamano** [comment]
I thought the problem might be related to the Gravatar endpoint and not the Gutenberg issue. Therefore, I have submitted a core ticket.

https://core.trac.wordpress.org/ticket/58970

**Comment by kraftbj** [comment]
Relayed to the Gravatar team and reported in their internal repo

**Comment by t-hamano** [comment]
Thank you, @kraftbj!

**Comment by kraftbj** [comment]
The fix has been deployed. Some caching may still interfere with some requests until it all flushes out.

Working example: https://secure.gravatar.com/avatar/?s=101&d=mm&f=y&r=g
