### ISSUE TITLE
Link suggestions should indicate expected result of UX spinner

### ISSUE THREAD

**Issue by roikles** [WordPress/gutenberg#5327]
## Issue Overview
When you highlight some text and click the link button it says 'Paste URL or type'. To me this implies that typing a page title for example would find and link to that page. This is further emphasised by the little progress spinner that appears after you type a letter.

This same behaviour happens with the button block.

## Steps to Reproduce (for bugs)
1. Type some text
2. Highlight the text and click the link icon
3. Begin typing in an existing page name
4. Visually it appears to be doing something but never brings up a list of matching pages or similar

Browser: Latest Version of Chrome.
PHP: 7.1.12

## Expected Behavior
The UI and wording suggests that as you type there should be some user interface element that lets you select from a page, post or custom post type.

## Current Behavior
There is no way to actually link to a site page without manually copying and pasting the URL.

## Screenshots / Video

![giphy](https://user-images.githubusercontent.com/36432/40919678-0ba3e30c-67bf-11e8-9bbe-84bedbc362a7.gif)

**Comment by apintocr** [comment]
Exactly the same issue here.

**Comment by danielbachhuber** [comment]
Flagging `Needs Design Feedback` to get direction on what this UX should be.

**Comment by karmatosed** [comment]
I am not sure this needs feedback as in the latest version you get a list of pages come up so I would like to see why they are not for you.

![2018-06-09 at 17 45](https://user-images.githubusercontent.com/253067/41194005-f075bfcc-6c0c-11e8-86d8-2d031fe358a1.png)
]

Are you using the latest version and if you are what browser are you using.

**Comment by danielbachhuber** [comment]
@karmatosed I think the UX case we need to solve for is when there aren't any matching results.

Notably, Pages don't yet show up in search results because it's blocked by #2084

**Comment by karmatosed** [comment]
With pages in the classic editor and links you don't get any feedback. I think we have to avoid endless spinning but we are ok just not returning any pages also.

**Comment by danielbachhuber** [comment]
> With pages in the classic editor and links you don't get any feedback.

Good point.

@roikles @apintocr Will the solution for #2084 solve your problem?

**Comment by roikles** [comment]
@danielbachhuber That solution would be great!

**Comment by danielbachhuber** [comment]
👍 Sounds good. We can track in #2084 then
