### ISSUE TITLE
Image block -  Upload - _wp_attached_file contains full file path in Windows

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#5332]
## Issue Overview
In my Windows server environment the post meta data keyed by `_wp_attached_file` for Images uploaded using the Image block contains the full file path. 
It should only contain the relative part of the file. e.g. Value is being stored as  
``` 
C:\apache\htdocs\wp50/wp-content/uploads/2018/03/dinlo.jpg
```
but it should be
```
2018/03/dinlo.jpg
```
This is actually a REST API issue - TRAC 40861.
This leads to failures downstream.

## Steps to Reproduce (for bugs)

1. Using a local Windows server 
2. Add an Image block
3. Upload an image
4.Check the value for the _wp_attached_file post meta data

## Expected Behavior
The attached file should be a relative path name

## Current Behavior
The attached file name is the full file name.

## Possible Solution
This is a bug in WP_REST_Attachments_Controller->create_item() where wp_slash() is being performed against all the fields in $attachment. $attachment['file'] contains the full file name for the uploaded file which probably contains backslashes. These get doubled and _wp_relative_upload_path fails to strip the uploads dir from the file name. 

## Related Issues and/or PRs

[WordPress TRAC 40861](https://core.trac.wordpress.org/ticket/40861)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Closing in favor of the core Trac ticket: https://core.trac.wordpress.org/ticket/40861
