### ISSUE TITLE
Site Editor > Console > 2 JS Errors : core/interface & core/reusable-blocks already registrered

### ISSUE THREAD

**Issue by Marc-pi** [WordPress/gutenberg#53344]
### Description

We get those 2 errors when the Gutenberg plugin is installed
detected on WP 6.2.2 and WP 6.3RC3
**it is visibile only if the Gutenberg plugin is active**

![image](https://github.com/WordPress/gutenberg/assets/919332/1f3604f9-4602-4082-9bf7-7e8dc4e51788)

### Step-by-step reproduction instructions

1. Open Dev Tool (FF or Chrome)
2. Go to Appearence > Editor : wp-admin/site-editor.php
3. Observe the Console Logs

### Screenshots, screen recording, code snippet

depending the plugins you use, you get several call

![image](https://github.com/WordPress/gutenberg/assets/919332/490b552b-7b6b-4bca-a122-c002f277ff9f)

### Environment info

- WP 6.2.2 / WP 6.3RC3
- Gutenberg 16.3.0

this error issue is there for months after a quick search in the repository (it is not thight to 16.3.0)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report. However, I could not reproduce it.

- Test with InstaWP
  - WordPress Version: 6.2.2
  - Gutenberg Plugin: 16.4
  - Enable `WP_DEBUG` and `SCRIPT_DEBUG`
- Couldn't reproduce it even with the latest gutenberg.

Could you please switch to the default theme and also check if you can reproduce the problem if you disable any plugins other than Gutenberg?

**Comment by Marc-pi** [comment]
I only use TT2/TT3 themes
the console errors seem to be gone after this week plugin updates (woocommerce/gutenberg/wooblocks)
another related issue is https://github.com/woocommerce/woocommerce-blocks/issues/10394
so i close
thanks for your help, i'll reopen if back
