### ISSUE TITLE
Writing Flow: margin empty paragraph between two items

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#53345]
<img width="368" alt="image" src="https://github.com/WordPress/gutenberg/assets/548849/7192f356-598d-4dc7-81f6-3362e3c74f36">

When merging empty paragraph between two list items, we currently end up in this situation:

<img width="296" alt="image" src="https://github.com/WordPress/gutenberg/assets/548849/a7c18013-677a-4870-b5de-4a7b9c1b58a4">

It'd be good to marge the lists instead.

**Comment by ellatrix** [comment]
@mtias This is a duplicate of #46039 and fixed by https://github.com/WordPress/gutenberg/pull/52995 (awaiting review).

**Comment by ellatrix** [comment]
Let's close in favour of https://github.com/WordPress/gutenberg/issues/46039.
