### ISSUE TITLE
Query pagination and next / previous post have different spacing between the arrow icon and text

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#53340]
### Description

If you compare the query pagination and the post navigation link blocks (next and previous posts), **on the front** of a site,
there is a visible difference in the spacing between the arrow icons and the text.

This happens even if the blocks have the same font family, size, weight, line height, etc, parent block, and regardless of theme. It makes consistent styling difficult.

### Step-by-step reproduction instructions

1. Ensure your WordPress installation has enough posts to make the pagination work.
2.  Create a new post.
3.  Add a post navigation link block.
4. Add a query loop with query pagination inside.
5. Enable arrows for both the post navigation block and query pagination. Set the font size. Which size doesn't matter, as long as it is the same for both blocks.
6.  Compare the spacing between the arrow icon and text, for example, with the help of the browser developer tools.
7. Save and view the front. Compare again and see that the spacing is different.

### Screenshots, screen recording, code snippet

The first block is the post navigation link:

<img width="666" alt="misaligned icon and text" src="https://github.com/WordPress/gutenberg/assets/7422055/a909aa1c-e6b0-4047-a45c-7ecb5d4200a9">

With some smart guides I added through Photoshop:
<img width="690" alt="guide lines overlaying the image, showing the difference in spacing" src="https://github.com/WordPress/gutenberg/assets/7422055/c9bbbf16-f787-49c0-9508-9847e69d9d74">

### Environment info

WordPress 6.3 RC 3, Gutenberg is not active.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Testing needed: Compare with the comments pagination block too.

**Comment by stacimc** [comment]
I wasn't able to reproduce this on WP 6.3 RC 3 🤔  I tried Twenty Twenty Three and Archeo, and tested all font sizes and both the arrow and the chevron.

<img width="515" alt="Screenshot 2023-08-04 at 2 34 32 PM" src="https://github.com/WordPress/gutenberg/assets/63313398/f31ec888-38f6-4685-8d9d-0e4f0ab2904d">

Confirmed in the inspector that the spacing was identical.

**Comment by t-hamano** [comment]
I was able to reproduce it. No problem in the editor, but there is definitely a difference in space on the front end.

Here is the HTML of the content created in the post editor. The font size is larger, 30px, to make it easier to see the difference.

<details><summary>Details</summary>

```html
<!-- wp:post-navigation-link {"type":"previous","arrow":"arrow","style":{"typography":{"fontSize":"30px"}}} /-->

<!-- wp:query {"queryId":0,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false}} -->
<div class="wp-block-query"><!-- wp:query-pagination {"paginationArrow":"arrow","style":{"typography":{"fontSize":"30px"}}} -->
<!-- wp:query-pagination-previous /-->

<!-- wp:query-pagination-numbers /-->

<!-- wp:query-pagination-next /-->
<!-- /wp:query-pagination --></div>
<!-- /wp:query -->
```

</details> 

## Editor

![editor](https://github.com/WordPress/gutenberg/assets/54422211/adefd38f-17ae-4f69-be1d-f4bbdfdfd568)

## Frontend

![frontend](https://github.com/WordPress/gutenberg/assets/54422211/8f4df84d-3a58-4cc9-8a13-79175c38be0d)

**Comment by t-hamano** [comment]
Okay, the navigation link may be due to having a space between the arrow and the link on the front end.

![space](https://github.com/WordPress/gutenberg/assets/54422211/a1309b32-360a-4246-9a74-285403d62355)
