### ISSUE TITLE
Toolbar loses anchoring point when merging lists

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#53346]
When the toolbar is visible and you merge two lists with backspace, the toolbar loses its anchoring point and goes to the top left of the canvas.

https://github.com/WordPress/gutenberg/assets/548849/39ae6d40-43af-41cb-b77a-af7672cea2f1

**Comment by ellatrix** [comment]
This was discovered by @jasmussen before and I had commented:

https://github.com/WordPress/gutenberg/issues/48670#issuecomment-1652606742

Cc @ciampo or @talldan maybe?

**Comment by ciampo** [comment]
Gave this a quick look, but I wasn't able to reproduce — could you double-check? I wonder if merging https://github.com/WordPress/gutenberg/pull/46845 fixed this too.

**Comment by annezazu** [comment]
I can't replicate either with 6.3.1 and GB 16.6:

https://github.com/WordPress/gutenberg/assets/26996883/abb73694-0f5a-4189-8840-1d04da3e3280

Going to close out for now! Happy to reopen if others can replicate.

**Comment by ellatrix** [comment]
@jasmussen Can you still reproduce?

**Comment by jasmussen** [comment]
I can't, no, that's nice. I wonder if it's because toolbars are captured now, though. In any case, I'll reopen if it resurfaces. Thanks!
