### ISSUE TITLE
Post Editor Fails to Create Categories or Tags with Long Text; No Error Message Displayed!

### ISSUE THREAD

**Issue by Rajinsharwar** [WordPress/gutenberg#53368]
### Description

When attempting to create a category or tags with very long text on the post editor page, the category or tags are not being created. Furthermore, there is no error message or notification displayed for mentioning exceeding the character limit; the post editor page simply refreshes/ removes the category entered in the field.

This bug was reported by [@nandhuraj](https://profiles.wordpress.org/nandhuraj) in WordPress Trac: https://core.trac.wordpress.org/ticket/58980

### Step-by-step reproduction instructions

1. Go to Dashboard > Post > Edit post.
2. Try adding a post category or tags with very long text in the “New Category Name field”.
3. For example: "Thisisjustanexamplecategorytextsample.Thisisjustanexamplecategorytextsample.ThisisjustanexamplecategorytextsampleThisisjustanexamplecategorytextsample.Thisisjustanexamplecategorytextsample.Thisisjustanexamplecategorytextsample."
4. Click Add New Category
5.  🐞 Bug occurs.

### Expected Results

✅ Either the category/tags should be created successfully, or there should be a notification indicating the error or a character limit.
### Actual Results

❌ The post editor page simply refreshes/removes the category entered in the field without creating the category/tag, and there is no error message or notification displayed mentioning about exceeding the character limit.

### Screenshots, screen recording, code snippet

Adding category with very long text.

![image](https://github.com/WordPress/gutenberg/assets/68213636/775d8816-94d9-4a6f-8d5d-1419da4da80c)

No category created and no error message or character limit notification. Just the text is removed from the field.

![image](https://github.com/WordPress/gutenberg/assets/68213636/1f9cd8ef-dac4-4f46-bbb8-3d8779769e8d)

### Environment info

WordPress: 6.3-RC3-56344
PHP: 7.4.33
Server: TasteWP-S4 Official/3.0.0
Database: mysqli (Server: 8.0.32-0ubuntu0.20.04.2 / Client: mysqlnd 7.4.33)
Browser: Chrome 114.0.0.0 (macOS)
Theme: Twenty Twenty-Three 1.2
MU-Plugins: None activated
Plugins: WordPress Beta Tester 3.5.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for contributing, @Rajinsharwar!

While #53369 could solve the issue, I would recommend a different approach. Try catching an error returned by the server and displaying its message as an error [snackbar](https://wordpress.github.io/gutenberg/?path=/story/components-snackbar--default).

## Why?

* The character limit for term names could change (in the future), or WP installation could enforce a different limit. This way, there will be no need to update the client-side code.
* The term creation could fail for a different reason; the general solution will also cover this case.

**Comment by Rajinsharwar** [comment]
Great idea. I will work on this, and update the PR. Thanks!

**Comment by Rajinsharwar** [comment]
Updated my [PR with a comment](https://github.com/WordPress/gutenberg/pull/53369#issuecomment-1671861552), requesting a review @Mamaduka. Thanks!

**Comment by nrajs36** [comment]
@Rajinsharwar Thank you for reporting the issue here.

**Comment by Mamaduka** [comment]
Resolved in #53369.
