### ISSUE TITLE
WP 6.3-RC3: it is not possible to trash patterns with draft status in post editor

### ISSUE THREAD

**Issue by bvlgn** [WordPress/gutenberg#53367]
### Description

If you add a new pattern in the post editor you will not get the row action option to trash the pattern.

This seems to be caused by map_meta_cap mapping `delete_post` cap to `delete_blocks`.(@Line 153 in capabilities.php).
It looks this is not a default cap assigned to the administrator role, therefor administrators are not allowed to trash draft patterns. Which of course is a bug. See screenshot.

### Step-by-step reproduction instructions

1. Add a pattern in the post editor (wp-admin/edit.php?post_type=wp_block)
2. Save it in draft status
3. Go back to the list table 
4. Try to trash the pattern (the row action will not be there)

### Screenshots, screen recording, code snippet

![Scherm­afbeelding 2023-08-05 om 13 04 48](https://github.com/WordPress/gutenberg/assets/13752843/75b40304-1694-4fb4-9166-c4666dbec49f)

So `$cap = 'delete_blocks',` which is not in `$capabilities`:

![Scherm­afbeelding 2023-08-05 om 12 47 33](https://github.com/WordPress/gutenberg/assets/13752843/3248364a-1099-471e-b35f-5c0f3709d65a)

### Environment info

WP 6.3 RC3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
Thanks @bvlgn, I was able to replicate this, but I could also replicate it with reusable blocks on 6.2.2 so given it is an existing bug not introduced by the pattern changes in 6.3 I don't think we need to prioritise it for 6.3 - but it would be good to get this sorted, so have added to the patterns project board.

**Comment by ramonjd** [comment]
Would something like this be an interim plugin fix? 

- https://github.com/WordPress/gutenberg/pull/53405

If so I can then add a WP backport patch to add `delete_posts` to the [register_post_type args](https://github.com/WordPress/wordpress-develop/blob/444bdf49bc38883f603a584bcc119aedf98257b8/src/wp-includes/post.php#L281).
