### ISSUE TITLE
Filters: wp_theme_json_data_user and block_type_metadata Are Buggy / Not Consistent

### ISSUE THREAD

**Issue by AlchemyUnited** [WordPress/gutenberg#53361]
### Description

Ultimately, I'm looking to control the UI / UX the users gets for each block's set of setting (in the right sidebar). I've been experimenting with the core/paragraph block. 

What I'm finding is there are things I can control via the filter: block_type_metadata that don't map to using filter: wp_theme_json_data_user  and vice versa. 

For example: The Color > Background (remove that control from the UI)

using block_type_metadata it looks something like:	

$arr_metadata['supports']['color']['background'] = false;

Howver, if I do the same via wp_theme_json_data_user then something like

 $arr['settings']['blocks']['core/paragraph']['color']['background'] = false; 
 
 does not work. That is, the Background control is not removed from the UI

That said, 'link' and 'text' work across both. That is, = false will remove them,  

Or for typography with via wp_theme_json_data_user this will remove the custom font size

$arr['settings']['blocks']['core/paragraph']['typography']['customFontSize'] = false;

But that doesn't seem possible via block_type_metadata. 

With block_type_metadata I can remove the one of both Advance inputs (Anchor and Custom class) using something like:

$arr_metadata['supports']['anchor']  = false;
$arr_metadata['supports']['customClassName'] = false;

But those also don't seem to map to using wp_theme_json_data_user .

I'd also like to note that it's 'customClassName' and simply 'className'. Why? I can't seem to find out.

I might as well ask...where can I get a list of the array keys for each UI Component? For example, disabling Color's Text, Link and.or Background.  Since theme.json feels like The Future, me thinks I should prefer using wp_theme_json_data_user, right? 

### Step-by-step reproduction instructions

You'll have to setup test filters I guess and try to array values above, I guess? 

### Environment info

- WP 6.2.2
- Theme is Twenty Twenty-Three
- PHP 8.0.22

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by AlchemyUnited** [comment]
I have some more to share on this, this time using the filter: wp_theme_json_data_user. I'm using that filter hoping to completely build the theme.json there (so - fyi - I can add comments, reuse code, etc. json is VERY limiting :( )

In any case, I'm working with the core/paragraph block and only that block. 

I've added a Custom color palette:

```
	$arr['settings']['blocks']['core/paragraph']['color']['palette'] = array(
		array(
			'color' => '#CCFFFF',
			'name'  => 'Tertiary',
			'slug'  => 'tertiary',
		),
		array(
			'color' => '#00000',
			'name'  => 'Black',
			'slug'  => 'black',
		),

	);
```

But if I try to remove the Theme palette with:

`$arr['settings']['color']['palette']['theme'] = array();`

Well, that also removes the Custom palette.  In short, I can't have a Custom palette without having a Theme palette.  I suppose you can 

I also noticed that if I have a color slug in my own ['color']['theme'] array (for the paragraph block), and that slug already exists in the theme.json then that color will be removed from my customized Theme palette. I'm not too concerned as I'm aiming to only have 'version' => 2 in my actual theme.json, but this behavior otherwise feels unexpected.

That said, I can repeat a slug in the Custom array and it's not effected by what's in the Theme's array. Also, I can repeast the same color in Theme and Custom or my customize Theme and Custom. But not in Theme in my customize theme. That just feels odd but perhaps there's some reason? 

I suppose you could say that if you're going to remove Theme with array() then that's where Custom could go. But that's could create confusion with users if sometimes there's Custom but other times Custom is actually under Theme. 

Along the same lines when trying to implement a customized array of Font sizes there are unexpected results. For example, if I have three sizes in my array, those are automatically assigned to the buttons S, M and L. There doesn't seem to be a way, to say use M, L and X. For example, across the theme there could be a set of sizes (say XXS thur XXL), and different blocks might use some subset. That is, XXS should be consistently the same size and not change because of the first size in the subset is different. 

I realize this all sounds somewhat abstract. I'd be willing to poke around in the code to offer some insights but frankly I'm not even sure where to look. Well, I have tried to look but can't seem to pinpoint where this magic is happening. 

Regardless, something needs to test this flag by flag and then various combos of flags and arrays. I feels awfully buggy :(

**Comment by ndiego** [comment]
Hi @AlchemyUnited, thanks for posting this issue. It can be very confusing. 

> With block_type_metadata I can remove the one of both Advance inputs (Anchor and Custom class) using something like:
>
> $arr_metadata['supports']['anchor'] = false;
> $arr_metadata['supports']['customClassName'] = false;
> 
> But those also don't seem to map to using wp_theme_json_data_user .

`wp_theme_json_data_user` lets you modify what can be specified in theme.json. Nothing else can be controlled using this filter, which is why the above does not work for this filter. This is a [good reference](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/) for all the settings available in theme.json.

For using `wp_theme_json_data_user`, and the other related filters, I recommend taking a peak at this article I wrote recently: [How to modify theme.json data using server-side filters](https://developer.wordpress.org/news/2023/07/how-to-modify-theme-json-data-using-server-side-filters/)

Let me know if I can help further.

**Comment by AlchemyUnited** [comment]
@ndiego  - To clarify, yeah, I've concluded there's a delta between the two different filters (theme.json vs an individual block) but that's exactly my point. In short, if I can hide the anchor and customClassName along w/ all the other "flags" via the one filter, why can't it be done the other way? If the theme.json is the ruler of all things theme-y...why doesn't it allow those two as well? It's doesn't make - good - sense to say "Use the theme.json...well, unless you want to hide the anchor and class name..they don't use that." 

I've read your article. Thanks. Helpful. I've read that theme.json article as well. But I'll give it another spin. 

All that said, I'm still getting too many unexpected results once I start altering the different flags which I've detailed some of those things above. The lack of control for the sizes (for typography) is especially annoying. I want to be able to define some fixed set of sizes and then subset from that. But I want, say, Medium to always from some px, rem or em. I don't want it to shift based on the # of elements in the subset. That's simply not a good and consistent UX. 

And background = false - at least for core/paragrapah - and I presume all other core blocks - is flat out not working. There's no way - that I've found - via the theme.json to remove the background color control.  Text and Link can be removed but not background, at least not via the theme.json.

Which for me raises another question...it seem there a two different sets of validation and setting depending on the filter used. Why is that? That's going to lead to problems...in fact, it already is :(

**Comment by AlchemyUnited** [comment]
p.s. What I'm trying to say is I'm wanitng to use the theme.json in a way that (1) it is supposed to be functioning, but isn't (workng as expected) (2) and in ways that make sense (e.g., anchor and class name) but it doesn't (support at all).

The friction and time devoted to dead ends is consuming and frustrating :(

**Comment by ndiego** [comment]
> In short, if I can hide the anchor and customClassName along w/ all the other "flags" via the one filter, why can't it be done the other way?

Yeah, I understand. At this point, not all block settings are available in theme.json. I fully expect more to be added in the future, but it's not currently possible.

As for disabling the `background` color, give the following code a try. I would also try upgrading to 6.3 if you can since there have been lots of bug fixes since 6.2. 

```
/**
 * This function modifies the theme JSON data by disabling color 
 * controls for the Group block.
 *
 * @param object $theme_json The original theme JSON data.
 * @return object The modified theme JSON data.
 */
function example_filter_theme_json_theme( $theme_json ){
	$new_data = array(
		'version'  => 2,
		'settings' => array(
			'blocks' => array(
				'core/group' => array(
					'color' => array(
						'background' => false,
						'text' => false,
						'link' => false
					),
				),
			)
		),
	);

	return $theme_json->update_with( $new_data );
}
add_filter( 'wp_theme_json_data_theme', 'example_filter_theme_json_theme' );
```

Let me know if you continue to experience issues disabling `background` color and I'll keep investigating. Thanks!

**Comment by AlchemyUnited** [comment]
@ndiego - Thanks again. Pardon the bullets but it'll help me just spit out and move on :)

1) That's such a Catch 22 tho'..."Here, do it this way...but not really." Also, if there are known disconnects - again, anchor and classes - it would help if those were plainly and obviously documented somewhere. Maybe it is, but I didn't see it :( Even for colors it was an excessive amount of trial & error. 

2) I did upgrade to 6.3 but didn't see if background is still an issue. I'll check shortly. Thanks for the heads up. 

3) That said, I'm also config'ing at the block level. So while I might have some global settings (like your example above), I'm ultimately looking for finer control at the ['settings']['block'] level. 

Question: Where in the code can I track this stuff down? Maybe there's more documenting there? For example, the (e.g.) ['some block']['color'] "flags" (properties?) have to be defined, set, etc. Maybe some class w/ setters and getters...but again, I haven't been able to find it. It seems my previous dig-into-the-core-code approach doesn't work as well with GB / Blocks / Block Themes. Or maybe it's just me? 

Thanks again. Sad to say this is my first not-negative experience with GB and issues on GH :(

**Comment by AlchemyUnited** [comment]
@ndiego  - Oh! one more things since you've been 10x helpful... customDuotone: bool and duotone: array, I'm looking for an example. I found a @richtabor  blog post on gradients but can't find a working example of duotone, so I'm not exactly sure how that manifests itself in the theme.json or in a block (via the meta filter, whatever the name is, sorry).

**Comment by ndiego** [comment]
> That said, I'm also config'ing at the block level. So while I might have some global settings (like your example above), I'm ultimately looking for finer control at the ['settings']['block'] level.

The code I provided only applies to Group blocks (`core/group`). Are you trying to apply settings to specific blocks of a given type?

> Question: Where in the code can I track this stuff down? Maybe there's more documenting there? For example, the (e.g.) ['some block']['color'] "flags" (properties?) have to be defined

So all the settings available in theme.json are [available here](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/). And on [this page](https://developer.wordpress.org/block-editor/reference-guides/core-blocks/) you can see what Core block supports a block opts into. 

> customDuotone: bool and duotone: array, I'm looking for an example.

The [TT2](https://wordpress.org/themes/twentytwentytwo/) applied custom duotone, so that is a good theme.json to look at. This is an excerpt from it. 

```json
	"settings": {
		"customDuotone": true,
		"color": {
			"duotone": [
				{
					"colors": [ "#000000", "#ffffff" ],
					"slug": "foreground-and-background",
					"name": "Foreground and background"
				},
                                 ...
```

**Comment by AlchemyUnited** [comment]
@ndiego  - Looks like 6.3 fixed the issue with background. :) 

re: "So all the settings available in theme.json are [available here](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/). And on [this page](https://developer.wordpress.org/block-editor/reference-guides/core-blocks/) you can see what Core block supports a block opts into."

Yeah, that's going to help. Thank you. Again. 

p.s. I've been working on a PHP class to help "encapsulate" the Color settings. Once I have Color sorted I'll share here and move on to the others.  Frankly, I have not much interest in the theme.json as a json. You can't comment in it. You can't alter it dynamically. Using a sever-side filter makes 10x more sense. And having classes to assist with that makes 100x more sense., cause my code editor's code complete, hints, etc. Such things are a god-send when you don't know what's available or not.  But I'm sure you get that :)

**Comment by AlchemyUnited** [comment]
@ndiego - I looked at Duotone. Thanks. But TBH...it feels doesn't belong under Color in the sense that all the other Color args are for type (e.g., paragraph block). Duotone doesn't apply to such block, and only applies to images. 

Yeah, I get it. We use colors to define Duotones but it's such an outliner relative to all the other Color arg, that it feels like Duotone belongs elsewhere.  That said, since it is a Color setting, and all the other Color controls are in the right sidebar, it makes more UX sense to have Duotones over there as well. That's where I would look as that's where I look for all other color "stuff", yes?

**Comment by AlchemyUnited** [comment]
@ndiego  - It's very early days but this is what I've pieced together so far. 

https://gitlab.com/wpezsuite/WPezBlockEditor/ThemeJSONSettings

Yes, I need to detail the README better. I get that. That's going to come as I do more thorough testing of each class. 

Actually, there's another class for removing the anchor and custom CSS inputs but I haven't pushed it yet. It works but I need to refactor a bit based on some additional ideas I've had. Stay tuned for that one :)

**Comment by AlchemyUnited** [comment]
@ndiego  - It's very early days but this is what I've pieced together so far. 

https://gitlab.com/wpezsuite/WPezBlockEditor/ThemeJSONSettings

Yes, I need to detail the README better. I get that. That's going to come as I do more thorough testing of each class. 

Actually, there's another class for removing the anchor and custom CSS inputs but I haven't pushed it yet. It works but I need to refactor a bit based on some additional ideas I've had. Stay tuned for that one :)
