### ISSUE TITLE
Actions on patterns result in notices containing 'block' instead of 'pattern'

### ISSUE THREAD

**Issue by bvlgn** [WordPress/gutenberg#53370]
### Description

If you for example trash a pattern the resulting notice refers to 'block' instead of 'pattern'.

### Step-by-step reproduction instructions

1. E.g. go to the post editor (wp-admin/edit.php?post_type=wp_block) 
2. Click on the 'Trash' row action
3. See admin notice

### Screenshots, screen recording, code snippet

![Scherm­afbeelding 2023-08-05 om 16 27 37](https://github.com/WordPress/gutenberg/assets/13752843/5b86bdfb-dca6-4b8d-9842-62c54e6b660f)

### Environment info

WP 6.3-RC3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Rajinsharwar** [comment]
I think this is expected because the post type is wp_block.

**Comment by bvlgn** [comment]
The wp_block post type was pre 6.3 only used for reusable blocks. So referring to block in notices made sense. Since 6.3 it is only used to store patterns though. The UI calls everything now a pattern so it is very confusing for users when notices speak of 'blocks'. I would even prefer to refactor the post type to not confuse future developers, but at least the notices should be renamed before WP6.3 is released, IMHO ;-)

**Comment by glendaviesnz** [comment]
Thanks @bvlgn. I have added this to the Patterns project board. Because there is now a string freeze on 6.3 I think we will need to wait to post 6.3 release to get these updated.

**Comment by annezazu** [comment]
Adding to the 6.3 board so we don't lose track for a 6.3.x release :)

**Comment by aaronrobertshaw** [comment]
Just a quick note to mention this probably needs a trac ticket and patch as the [notices in question](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/edit.php#L383-L395) are in core rather than Gutenberg.

**Comment by aaronrobertshaw** [comment]
I've created the [trac ticket](https://core.trac.wordpress.org/ticket/59305) and a [PR](https://github.com/WordPress/wordpress-develop/pull/5163) to update these notices.

Ticket: https://core.trac.wordpress.org/ticket/59305
PR: https://github.com/WordPress/wordpress-develop/pull/5163

**Comment by talldan** [comment]
Seems to be fixed in core.
