### ISSUE TITLE
Memory leaks in `Iframe` and `BlockPreview`

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#53382]
### Description

While playing with ideas of potentially improving the performance of `<BlockPreview>`, I discovered that the `<Iframe>` component from the `block-editor` package is leaking memory.

This is especially noticeable when loading lots of patterns, which render `<BlockPreview>`s and `<Iframe>`s under the hood. Memory leaks can cause the page to feel heavy and unresponsive, then eventually stop working when it reaches the browser's limits. This is also worse in Site Editor where we rely on client side navigation and never give the browser chance to nuke everything.

I have some leads regarding identifying the code that causes the leaks, but none are proven yet. I can continue to find them if given more time, but decided to open an issue first for awareness.

### Step-by-step reproduction instructions

1. Open a block editor (post or site)
2. Open your desired memory leak detection tool. For chrome devtools it can be the "Performance Monitor" tab and observe the live document frames or JS heap size, or it can also be the "Memory" tab and take snapshots of the before and after then compare them.
3. Open the global inserter and load a set of block patterns (which renders `<BlockPreview>` -> `<Iframe>`).
4. Close the inserter to unmount the patterns (thus unmounting `<BlockPreview>` and `<Iframe>`)
5. Repeat the process of steps (2) ~ (3) for a few times
6. Notice that the memory keeps growing and never gets garbage collected. The number of document frames also keeps increasing and never gets freed.

### Screenshots, screen recording, code snippet

Using the "Performance Monitor" tab:

https://github.com/WordPress/gutenberg/assets/7753001/2e0e76b3-eda4-45d1-b5c0-560bc31a57fe

Using the "Memory" tab record the heap snapshots:

https://github.com/WordPress/gutenberg/assets/7753001/6844dcbd-2438-415f-82d4-467d3c4238cb

### Environment info

- WordPress trunk, gutenberg trunk (production build)
- macOS, Microsoft Edge, and Brave.
- Theme: twentytwentytwo

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Here's an example of the measurement on the Patterns page, with the WooCommerce plugin enabled, recording CPU usage and JS head size changes when that category is accessed. In my environment, there seems to be so much load that the scroll bars are inoperable for a little while 😅

https://github.com/WordPress/gutenberg/assets/54422211/c9bb9bef-38bc-4032-aa98-105f43cd9efc

**Comment by kevin940726** [comment]
@t-hamano Yeah, it's reported in https://github.com/WordPress/gutenberg/issues/50695, which I failed to mention in the description 😅.

**Comment by kevin940726** [comment]
Just to note that I think I found (partial?) solutions to this and I will share them in a PR soon!
