### ISSUE TITLE
Styling for captions in images

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#534]
The design shows them centered and with better padding.

**Comment by paaljoachim** [comment]
Can we please reopen this issue? 
As the following is about caption styling.

There is now a styling drop down option in the image captions.
<img width="325" alt="Screen Shot 2019-04-22 at 10 29 42" src="https://user-images.githubusercontent.com/5323259/56491819-09242780-64ea-11e9-8f78-63f551976c98.png">

It would be nice to also see: underline, color options and font size added to the drop down list. 
@ellatrix

**Comment by benlk** [comment]
This is kind of an issue about selector specificity: Why does the default block-styles stylesheet make figcaptions centered? In 5.1RC2 the selector for this is more opinionated than I expected it to be:

```css
.wp-block-image figcaption {
    margin-top: .5em;
    margin-bottom: 1em;
    color: #555d66;
    text-align: center;
    font-size: 13px;
}
```

I get that the layout styles need a certain specificity:
```css
.wp-block-image .aligncenter>figcaption,
.wp-block-image .alignleft>figcaption,
.wp-block-image .alignright>figcaption,
.wp-block-image.is-resized>figcaption {
    display: table-caption;
    caption-side: bottom;
```

But why does Gutenberg's default stylesheet ship with rules that:
- center text
- set the color to a light tone that doesn't meet WCAG AA or AAA for contrast on a white background (#7d8185 on white is 3.92, AA requests 4.5 and AAA 7.0)
- muck with line-height
- change the font size?

Can these opinionated styles be removed?

**Comment by benlk** [comment]
nevermind, gonna make that an separate issue rather than reopening this one: https://github.com/WordPress/gutenberg/issues/15574
