### ISSUE TITLE
Display some prompts or options in Command Palette at launch

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/gutenberg#53400]
## What problem does this address?

When I launch Command Palette, I expect to see a few examples of prompts with the ability to scroll down to review more the way I can see them in VS Code and Obsidian. 

## What is your proposed solution?

Display options within Command Palette at launch without typing anything additional. 

## Post Editor:
![image](https://github.com/WordPress/gutenberg/assets/5519705/152277cf-68ca-4e0c-bf20-3167fc501403)

## Site Editor:
![image](https://github.com/WordPress/gutenberg/assets/5519705/a6f53e64-177b-4030-852d-61098baaeaab)

## VS Code:
![image](https://github.com/WordPress/gutenberg/assets/5519705/1f2bc2d9-c56c-42a4-94cd-f71bb4fd5000)

## Obsidian:
![image](https://github.com/WordPress/gutenberg/assets/5519705/98077299-ec75-4b77-828b-9e696a114e51)

**Comment by jordesign** [comment]
Just noting that this seems specific to the Post Editor. When I check the Command Center in the Site Editor/browser view I _do_ get some suggestions.

<img width="538" alt="Screenshot 2023-08-08 at 11 08 38 am" src="https://github.com/WordPress/gutenberg/assets/1842363/1e68157f-d2ee-42b4-b248-8ce8c5c28ae9">

**Comment by courtneyr-dev** [comment]
Interesting. I selected it from the front page and didn't get any suggestions [for this one](https://user-images.githubusercontent.com/5519705/258876039-a6f53e64-177b-4030-852d-61098baaeaab.png).

**Comment by ntsekouras** [comment]
Thank you for the issue @courtneyr-dev! The suggested commands per use case are based on the context ([commands API](https://github.com/WordPress/gutenberg/blob/trunk/packages/commands/README.md#contextual-commands)). Actually they are bit outdated and opened a [PR](https://github.com/WordPress/gutenberg/pull/66860) with the current status.


I'll close this one in favor of https://github.com/WordPress/gutenberg/issues/50407, which is the same and also has suggestions about what contextual commands should be shown per use case.
