### ISSUE TITLE
Pasting a blob of text that starts with a URL attempts to embed the entire pasted content as the URL

### ISSUE THREAD

**Issue by helen** [WordPress/gutenberg#5340]
## Issue Overview
When pasting a blob of text that starts with a URL, the editor attempts to find and insert an embed with the entire blob of text as the URL.

## Steps to Reproduce (for bugs)
1. Try pasting something like `http://example.com and some more text`
2. Watch it attempt to embed (related: #4799) and fail.
3. Notice that the URL in the URL field contains the entire pasted text.

## Expected Behavior
I would expect it to just paste all of the content and not attempt to embed the URL, i.e. only URLs pasted alone should attempt to embed.

## Screenshots / Video
![Demo GIF](http://s.hyhs.me/ptVe/image.gif)

## Related Issues and/or PRs
* #4799

**Comment by aduth** [comment]
Closed by #5385
