### ISSUE TITLE
Create guide in the Block Editor Handbook on how to enqueue assets in the Editor

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#53402]
## What problem does this address?
As the WordPress Editor has evolved, we have developed numerous methods to enqueue assets. There are different methods for individual blocks, themes, and feature plugins. And with WordPress 6.3, we are getting the [`enqueue_block_assets`](https://make.wordpress.org/core/2023/07/18/miscellaneous-editor-changes-in-wordpress-6-3/#post-editor-iframed) method and the Post Editor will be iframed by default (there are some caveats [here](https://make.wordpress.org/core/2023/07/18/miscellaneous-editor-changes-in-wordpress-6-3)). 

The lack of a definitive resource has led to misinformation and [confusion](https://github.com/WordPress/gutenberg/issues/53236) on how to properly interact with the Editor, especially the iframed Editor. 

## What is your proposed solution?

We need a definitive guide/resource for developers that details all the recommended ways to enqueue assets (scripts and styles) and the best practices for each. This guide also needs to identify any limitations and caveats.

**Comment by skorasaurus** [comment]
https://github.com/WordPress/gutenberg/issues/33212 may be helpful with common issues of enqueueing in the editor.

**Comment by tresorama** [comment]
Related

https://github.com/WordPress/gutenberg/issues/48497
