### ISSUE TITLE
Up/down keyboard navigation occasionally gets stuck

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#53416]
See also: #44753

### Description

**Keyboard movement occasionally breaks for no apparent reason.** In certain circumstances, pressing the <kbd>Up</kbd> and <kbd>Down</kbd> keys to navigate across blocks stops working, with the caret seemingly stuck until pointer intervention.

Of all the browsers, Safari seems to be the worst affected here.

### Step-by-step reproduction instructions

(See screencast below.)

### Screenshots, screen recording, code snippet

In the following screencast, I just keep pressing <kbd>Up</kbd> until the caret gets stuck. In this case, it got stuck on the large-text paragraph, but it can get stuck anywhere. You can't tell, but I am pressing <kbd>Up</kbd> at that point. The only way to unstick it is to use the cursor to scroll up a little, and then the caret can resume:

https://user-images.githubusercontent.com/150562/194364911-51463cc4-d94a-4b52-bb30-5700cc81cc67.mov

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
This issue looks similar to #44055. I have narrowed down the problem area to some extent, but have not yet resolved it.

**Comment by mcsf** [comment]
> This issue looks similar to #44055. I have narrowed down the problem area to some extent, but have not yet resolved it.

Thanks for spotting the duplicate. I'll close this one in favour of that.
