### ISSUE TITLE
Style Book: Ability to focus on individual block types.

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#53432]
<img width="1445" alt="Screenshot 2023-08-08 at 16 25 42" src="https://github.com/WordPress/gutenberg/assets/846565/5f63898f-3211-4ac4-bb2b-16a4a64b534b">

Clicking a block in Style Book takes you to the Inspector panel for the global styles of that block. However all the other blocks remain visible on the canvas which can be distracting. 

Let's explore ways a user might focus on individual blocks. This could be an environment in which to include variations and states like hover/active.

**Comment by annezazu** [comment]
Related feedback coming in from the [twenty-fifth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2023/08/09/fse-program-testing-call-25-lets-start-from-the-beginning/#comment-3121):

>Using the Style Book – I was hoping to be able to make changes to the H2 specifically while viewing a preview. It wasn’t made clear anywhere what the hierarchy of editing headings was to edit the ‘Heading’ element for styles that go across all headings, but could then make individual changes to different headings under Typography > Headings.

In particular, I see this as being related to having a more isolated editing experience.

**Comment by daveloodts** [comment]
Hi, that's a nice feature to have. 
But referring back to the ticket #41119, hybrid themes won't go away. Certainly for sites that want 100% control over header and footer. In my case that are e-commerce sites.  There is so much going on in an e-commerce header; let alone the difference between desktop and mobile. I can't see any option besides a shortcode in the current FSE header.

I sense that a direction is chosen eitherway, WordPress is splitted.
But i was just wondering: what is for hybrid themes the easiest way to make use of the kitchen sink overview. I guess just dropping a theme.json won't do it.

**Comment by richtabor** [comment]
I feel this could be overwhelming navigating in and out of individual block instances. It's already difficult orienting when navigating between templates, pages, and patterns—I'm not confident in introducing another step here. It would require you to navigate back to the stylebook proper before selecting another block, requiring many more clicks to style. I don't think that would be worth the advantage of focusing on a singular block at a time.

**Comment by jameskoster** [comment]
Yeah this needs to be re-evaluated based on the outcome of https://github.com/WordPress/gutenberg/issues/66376.

**Comment by richtabor** [comment]
Let's close this as not-planned for now, and if we find that we should revisit this we'll think it through again. Thanks!
