### ISSUE TITLE
Improve pre/post-publish flow for Schedule, and Submit for Review

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#5343]
When you write a post, and click "Publish...", you enter the post-publish flow where you can verify last minute details before publishing your post. This is a valuable _confirm_ step.

"Update" should not have this post-publish step, but "Schedule" should as it's essentially the same "Publish" mindset you're in, you're just publishing to the future. As such you should be allowed the same last-minute checkup:

![publishflow](https://user-images.githubusercontent.com/1204802/36888657-bb9abb2c-1df6-11e8-9c6f-7d95d9f24a83.gif)

— though as we add that step we should be sure to rename the label from "Schedule" to "Schedule..."

In addition to this, we should make improvements to how users with the `contributor` role publish. Right now they just get a "Submit for Review" button, with no confirmation step. They deserve this step also. Here's how that could look. First:

![36848815-a8b812e6-1d62-11e8-9296-3735b63b157b](https://user-images.githubusercontent.com/1204802/36888740-275742ae-1df7-11e8-8b2c-dd29e2a4ef41.png)

Then:

![36848821-ab885fbc-1d62-11e8-88d5-0dca5875c7d6](https://user-images.githubusercontent.com/1204802/36888744-29e5a902-1df7-11e8-8042-0402e11ce5ee.png)

This will be an additional enhancement to the work started in https://github.com/WordPress/gutenberg/pull/5329, and will further address #4231. See also https://github.com/WordPress/gutenberg/issues/4231#issuecomment-369603738.

**Summary of button labels and flows**:

Editors and admins:

- Update — updates immediately, no pos-publish flow
- Publish... — opens post-publish flow
- Schedule...  — opens post-publish flow

Contributors:

- Publish...  — opens post-publish flow where the confirm button says "Submit for Review".

The idea is that the flow is really: “Decide you are done -> Get into Publish Flow -> Submit for Review”

**Comment by afercia** [comment]
Related: #4187.

**Comment by jasmussen** [comment]
@jorgefilipecosta I see that you've assigned this to yourself. For that you get a 🏅 

Feel free to ping me or anything at all, if I can help you with this in any way.

**Comment by jasmussen** [comment]
Thank you Jorge! 🔥
