### ISSUE TITLE
Default font size setting in paragraph block is huge

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#5344]
## Issue Overview
Default font size setting in paragraph block is huge which feels weird.

## Steps to Reproduce (for bugs)
1. Add paragraph block.
2. Change font size in block settings by touching the input range via mouse or keyboard.
3. Font size jumps to 105px or something.

## Expected Behavior
Default font size should start from the beginning from the range, something like 16-20px.

**Comment by stompweb** [comment]
+1 on this.

**Comment by samikeijonen** [comment]
Could be related to #5360.

**Comment by karmatosed** [comment]
Closing this as rolling into fixed in #5268
