### ISSUE TITLE
Style Variations: Display current modifications in the "Browse styles" panel

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#53476]
The "Browse styles" panel shows which style variation is active. 

It can sometimes be useful to understand in more detail which blocks, elements, etc. that variation modifies. In this issue let's explore designs to surface those details with appropriate prominence.

**Comment by annezazu** [comment]
Related to this, we need to show what custom CSS is attached to each variation: https://github.com/WordPress/gutenberg/issues/47433

**Comment by ellenbauer** [comment]
@jameskoster Before adding design ideas, I just want to be extra sure that with 'shows which style variation is active' the slightly darker border around the active style variation is meant, or? Could we maybe also discuss making this active state a little more visible? 

We are creating a theme right now with a lot of style variations and I feel the active state should pop out a little more visible, see screenshot: 

<img width="346" alt="Screenshot 2023-09-06 at 2 44 22 PM" src="https://github.com/WordPress/gutenberg/assets/17613630/da55aaff-76c6-40d0-96e2-2cf8e884bcd2">

Also, when we are adding more information anyway, we could maybe add the name of the active style variation to this list?

**Comment by jameskoster** [comment]
@ellenbauer I don't think anything is totally off the table :) Looking forward to seeing ideas!

**Comment by annezazu** [comment]
[After a review](https://wordpress.slack.com/archives/C02QB2JS7/p1707152945370159) by core editor triage leads and core editor tech leads, this has been removed from the board for 6.5 consideration.

**Comment by mtias** [comment]
What's the status of this one?

**Comment by jameskoster** [comment]
I know I opened this issue, but it's been a while and could use some clarity since the UI/UX has changed a little. 

Are we talking about displaying information regarding modifications the user has made to the active style variation? Or is it about showing which modifications each style variation applies on top of the default one?

The wording in the issue would suggest the latter, but the former seems more useful to me :)

**Comment by mtias** [comment]
Yeah, it seems perhaps we should close this one and continue on the broad work of style variation management :)

**Comment by jameskoster** [comment]
Yes I think so, saving/resetting is mostly covered in https://github.com/WordPress/gutenberg/issues/45371.
