### ISSUE TITLE
Allow inserting un-namespaced editor styles into the iframe

### ISSUE THREAD

**Issue by andreiglingeanu** [WordPress/gutenberg#53473]
## What problem does this address?
This will allow styling the `html` element in the iframe element in some special situations like when the `html` tag inherits the `body` background: https://stackoverflow.com/a/35388084/3220977

## What is your proposed solution?

We can already add custom editor styles by using the `block_editor_settings_all` filter:

```php
add_filter(
  'block_editor_settings_all',
  function($settings) {
    $settings['styles'][] = array(
      'css' => ':root {--test: red;}',
      '__unstableType' => 'theme',
      'source' => 'blocksy'
    );

    return $settings;
  }
);
```

But they will always be namespaced, that is `:root|body|html` will be replaced with `.editor-styles-wrapper`.

The proposed solution is to skip bypassing of transforms for some of the styles here:

![CleanShot 2023-08-09 at 17 29 48@2x](https://github.com/WordPress/gutenberg/assets/2979628/c1df8f2c-0eff-478b-afa7-1a11074f326d)

We could introduce a `skippedTransforms` flag to the style which will allow us to skip some of the transforms here:
![CleanShot 2023-08-09 at 17 43 38@2x](https://github.com/WordPress/gutenberg/assets/2979628/4d781079-f628-41ac-a1f5-eadc63fbad81)

## Related issues

- https://github.com/WordPress/gutenberg/issues/18571
- https://github.com/WordPress/gutenberg/pull/52767

---

I'm happy to work on a PR with the proposed or an alternative solution.

**Comment by ellatrix** [comment]
You mean this? #46752 :)

**Comment by andreiglingeanu** [comment]
@ellatrix yes, but with this new approach everyone will be responsible for scoping their on editor styles into `.editor-styles-wrapper`?

**Comment by ellatrix** [comment]
@andreiglingeanu No, there's no need to scope with the iframe, but we will keep scoping outside the iframe.

**Comment by andreiglingeanu** [comment]
@ellatrix I understand but it seems to me it doesn't cover the use case when someone wants to style `.editor-styles-wrapper` both in iframed and non-iframed states. 

Will it be possible with this new system? If yes, how exactly the selector would have to look like?

**Comment by ellatrix** [comment]
When the editor is _not_ iframed, `.editor-styles-wrapper` is the root, which can't be changed. If we don't scope styles they'll leak into the rest of the admin. But from now on the editor should be iframed.

**Comment by andreiglingeanu** [comment]
@ellatrix even if editor is always iframed, styles are scoped to `.editor-styles-wrapper` (which is the `body` tag in the iframe). We want to apply some styles to the `html` tag of the iframe — that's not possible now.

That's why I'm looking for a way to maybe enable such a thing:

```php
add_action(
	'block_editor_settings_all',
	function($settings) {
		$settings['styles'][] = array(
			'css' => 'html { --test: red; }',
			'__unstableType' => 'theme',
			'skipTransform' => true
		);

		return $settings;
	}
);
```

---

The editor is still not iframed on the desktop in lots of situations, for example when WooCommerce is active (they still seem to have some non-v3 blocks declared).

**Comment by ellatrix** [comment]
> @ellatrix even if editor is always iframed, styles are scoped to `.editor-styles-wrapper` (which is the `body` tag in the iframe). We want to apply some styles to the `html` tag of the iframe — that's not possible now.

No, that will go away with the PR I linked above.

Regarding non iframed, I'd push block devs to update their blocks to v3 asap.

**Comment by andreiglingeanu** [comment]
> No, that will go away with the PR I linked above.

I can confirm that — just tested your branch. This is amazing!
Will this land in 6.4? From the comments in the PR, it seems like so.

If the above PR will land and the styles won't ever be scoped in the iframe, then this issue can be closed.

---

> Regarding non iframed, I'd push block devs to update their blocks to v3 asap

That would be very helpful.

**Comment by ellatrix** [comment]
Yes, that PR should be in 6.4. Trying to get it reviewed.

**Comment by skorasaurus** [comment]
https://github.com/WordPress/gutenberg/pull/46752 has been merged; so we can close the issue. thanks for reporting @andreiglingeanu
