### ISSUE TITLE
dashboard only texts

### ISSUE THREAD

**Issue by papell1970** [WordPress/gutenberg#53491]
### Description

wp 6.3 dont show me the dashboard full.  only words. 

### Step-by-step reproduction instructions

go to my admin wp and dont show the dashboard normally

### Screenshots, screen recording, code snippet

![Screen Shot 2023-08-09 at 2 30 32 PM](https://github.com/WordPress/gutenberg/assets/66057525/707baf1b-dc5e-4e10-baf2-6cbc60a5f062)

### Environment info

![Screen Shot 2023-08-09 at 2 32 16 PM](https://github.com/WordPress/gutenberg/assets/66057525/443b2e80-134b-4a11-998c-a4ff47d34d36)

### Please confirm that you have searched existing issues in the repo.

Yes, No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes, No

**Comment by dhrumilkumbhani** [comment]
I have checked that on fresh WordPress and also I have to check it on WordPress Develop but we have not found this type of issue on the dashboard and it's working fine for me.

**Comment by jasmussen** [comment]
I can't reproduce. It looks like a lot of bundled CSS is not being loaded. Can you try in another browser, see if it's an adblocker? Alternately, are you running any plugins that might be doing some CSS minification or cache optimization that you could try and temporarily toggle off to see if that addresses it? Finally (although this seems unlikely) it could be a bad WordPress update, and you can try and reapplying the update by going to `[yoursite]/wp-admin/update-core.php` and reinstalling.

**Comment by ndiego** [comment]
Hi @papell1970, thanks for reporting, but I am also not able to replicate it. Can you provide a bit more information about your WordPress setup?

**Comment by jasmussen** [comment]
@annezazu I think you may have encountered related issues with styles not loading. Does this seem related? Thanks for looking.

**Comment by t-hamano** [comment]
To my knowledge, no other such problems have been reported. Perhaps it is because WordPress is failing to update or the path to load the CS has been changed by .htaccess or other means? Therefore, I think this issue can be closed.

**Comment by annezazu** [comment]
Just am coming to this as well. Apologies for the delay. This doesn't match other styling related loading issues I've seen nor any other related issues. I agree that this is likely site specific. I'd recommend contacting your host at this point!
