### ISSUE TITLE
Storybook regressions after TypeScript 5.1 update

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#53502]
The recent update to TypeScript 5.1 (#52621, #53445) has caused some breakage in our Storybook:

- The components props tables do not show information sourced from TypeScript data anymore. We are missing a huge chunk of props documentation and controls.
- Event handlers such as `onChange` are not showing up as expected in the Actions panel. It seems like everything with configured with `actions: { argTypesRegex: '^on.*' }` is broken. In some cases, when the handlers are called in component story code without an optional (`onChange()` vs. `onChange?.()`), the story will crash on the first change event.

## How to address

We'll first try to update Storybook to v7 to see if these issues might be resolved naturally. This upgrade was planned from before and we are now unblocked due to the Node upgrade in #53426.

**Comment by noahtallen** [comment]
> The components props tables do not show information sourced from TypeScript data anymore. We are missing a huge chunk of props documentation and controls.

Sorry I missed this!

**Comment by mirka** [comment]
No problem at all, these things aren't very obvious 😄
