### ISSUE TITLE
Block Inserter: Tooltip appears misaligned

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#53518]
### Description

On a block with an inner block, mouse over the block inserter that appears in the lower right corner, and an "Add block" tooltip will appear in the lower right corner.

In some blocks, the tooltip probably overflows the screen, so a scrollbar appears.

### Step-by-step reproduction instructions

- Insert a block with the inner block (Group, Button, List)
- select the block
- Mouse over the block inserter
- Confirm that the tooltip is not positioned correctly or the scrollbar is displayed.

https://github.com/WordPress/gutenberg/assets/54422211/a4912a05-b64c-4a99-99b5-b287f430d500

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by brookewp** [comment]
Hey @t-hamano! Can you still replicate this? I was unable to in Safari, Firefox, and Chrome: 

<img width="864" alt="Screenshot 2023-09-26 at 1 44 50 PM" src="https://github.com/WordPress/gutenberg/assets/35543432/7af9e43f-3573-434a-84fa-aa637f5c56fd">

I'm hopeful this was resolved by the Tooltip refactor #48440.

**Comment by t-hamano** [comment]
Thanks for testing this issue, @brookewp. Admittedly, I didn't reproduce this problem on the latest trunk, so I'd like to close it.

Tested on Windows 11 Chrome and Firefox
