### ISSUE TITLE
When does the Block Editor get iFramed?

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#53511]
### Description

This is kind of related to #53258. In that post I was advised that the Classic Block now only allows you to edit the content within a modal popup. It was mentioned that this was because it was required to get TinyMCE to work within iFrames.

I can only assume that forcing the editor into an iFrame was made in the recent 6.3 release because prior to 6.3 I was able to edit the Classic Block inline, just like any other block.

When asking why the editor is now being iFramed I was pointed to [this post](https://make.wordpress.org/core/2021/06/29/blocks-in-an-iframed-template-editor/) from @ellatrix.

Within this post, Ella states that "**We currently only iframe new editors**". What does this mean? I asked this question over on my above issue, but no-one answered it, and I haven't been able to find out any answer from others I've asked.

I’ve tested multiple sites with WP6.3. One site showed the editor in an iFrame, but other sites didn’t. Which also means that on some sites you can edit the Classic Block inline, just like any other block, and on some sites you have to use the annoying popup. There seems to be no clear indication as to why this is. Does it mean that it’s used only on newly created sites? Only on newly created pages? Only on sites that are using newer Block Themes?

Based on my testing across multiple sites, and with multiple themes (incl. Block and non-Block themes), none of these seem to be the case. The only thing I can determine is that it somehow seems to be site related, and nothing to do with the actual page content, whether the page is newly created and/or edited (or just old), or what theme the site is using.

If someone can explain exactly when the editor is iFramed and when it isn't, it would be greatly appreciated (and I would also recommend updating that Make Core post with this clarification as well).

Thanks.

### Step-by-step reproduction instructions

N/A

### Environment info

- WP Core only (no plugin) - WP6.3
- macOS 13.4.1
- Firefox 116.0.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by swissspidy** [comment]
From what I've heard, the editor is iframed if there are no classic meta boxes added by plugins and if all registered blocks need to use the latest `apiVersion` 3

Edit:

> Within this post, Ella states that "We currently only iframe new editors". What does this mean?

There are a few editors in WordPress: the post editor, the site editor, widgets editor, template editor, etc.

The template editor is one of the newer ones, so it is iframed. The post editor will be done later. It's literally explained in the next sentence.

**Comment by maddisondesigns** [comment]
> if there are no classic meta boxes added by plugins and if all registered blocks need to use the latest apiVersion 3

@swissspidy Thanks for this. That makes it a little clearer. Just testing on a site now I can see that enabling/disabling Gravity Forms or WooCommerce, as an example, will determine whether the block editor displays in an iframe or not.

> The template editor is one of the newer ones, so it is iframed. The post editor will be done later. It's literally explained in the next sentence.

I specifically asked about the Block Editor which is what the post editor is commonly referred to as, not the Site Editor, Widgets Editor or any of the other Editors. That Make Core post that I was pointed to is from 2021, so saying "the post editor will be done later" is literally of no use. When is "later"!? And again, it still doesn't provide any clear explanation in regards to what determines "new editors". One of the test sites I use frequently has no plugins activated and prior to 6.3 you weren't forced to use a modal popup to edit the Classic Block, so I can only assume this iFraming for the main Block Editor has only just been implemented with WP6.3.

**Comment by swissspidy** [comment]
> so I can only assume this iFraming for the main Block Editor has only just been implemented with WP6.3.

Indeed it was! Here's the dev note for it: https://make.wordpress.org/core/2023/07/18/miscellaneous-editor-changes-in-wordpress-6-3/

It's also referenced in the [6.3 field guide](https://make.wordpress.org/core/2023/07/18/wordpress-6-3-field-guide/), which is the go-to resource for developers whenever there's a new release.

**Comment by stokesman** [comment]
For now there is a built-in option that happens to keep the Post editor from being iframed. That's to turn on custom fields. The setting is under Options > Preferences > Panels > Custom fields.

With regards to the Classic block there is another issue currently hinders its use #53477. A plugin or theme can add a bit of CSS to work around that and I posted an example in that thread.

**Comment by maddisondesigns** [comment]
@stokesman Thanks for that little workaround tip on enabling custom fields to prevent the Post Editor being iFramed. Thanks also for the css workaround for fixing the Classic Block toolbar positioning.

@swissspidy Thanks for the link to that 6.3 Dev note. That's helpful.

I'll close this issue now since that answers my question.

**Comment by bantilan** [comment]
Here is the corrected version with improved grammar:

Does anyone have a problem with useRef()? It keeps returning undefined.

I tried using the suggestion from here https://make.wordpress.org/core/2021/06/29/blocks-in-an-iframed-template-editor/ so I can utilize useEffect with the new iframe, but I am stuck with this error.

**Comment by bantilan** [comment]
Does anyone have a problem with useRef()? It keeps returning undefined.

I tried using the suggestion from here https://make.wordpress.org/core/2021/06/29/blocks-in-an-iframed-template-editor/ so I can utilize useEffect with the new iframe, but I am stuck with it.
