### ISSUE TITLE
"My patterns" interface typo

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#53530]
### Description

The text here has a typo:

<img width="280" alt="image" src="https://github.com/WordPress/gutenberg/assets/56840277/c8e4d116-c741-43cb-bc95-2633b68baf63">

This is shown when looking at "my patterns".

Assumedly this should read "Custom patterns add**ed** by site users"

### Step-by-step reproduction instructions

1. Click add
2. Click patterns
3. Click My patterns

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. This was fixed in https://github.com/WordPress/gutenberg/commit/867ca865c98d4a60ee0d7db7dec0ebfed6893ecd and was included in the Gutenberg 16.4.0 release.  Please reopen if you are still experiencing this if you have Gutenberg 16.4.0 installed.

**Comment by richtabor** [comment]
It's still missing the terminal though. 

`Custom patterns added by site users` should be `Custom patterns added by site users.`

**Comment by glendaviesnz** [comment]
> It's still missing the terminal though.

[Fixed here
](https://github.com/WordPress/gutenberg/pull/53544)
