### ISSUE TITLE
Add block-specific commands as contextual suggestions

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#53539]
We currently have suggested commands based on context. Like if you're viewing a page in the site editor, you'll see a contextual command to edit the template _before_ searching for commands. 

It would be nice to bring some of the new block-specific commands added in https://github.com/WordPress/gutenberg/pull/52509 front and center, if you're opening the command palette with a block selected. I don't think we need all the commands, but the more editing-forward commands perhaps. 

#### Example of contextual suggestion when editing a template: 

<img width="472" alt="CleanShot 2023-08-10 at 14 54 56" src="https://github.com/WordPress/gutenberg/assets/1813435/2c15610c-e668-4f03-83a7-8dd9b0d6b300">

### Visual:

<img width="620" alt="block-specific-commands" src="https://github.com/WordPress/gutenberg/assets/1813435/06dde6a5-5a09-40de-8137-47e7d8eb952f">

**Comment by jrtashjian** [comment]
I've pushed up #53974 which accomplishes this by applying a new context for the command palette.
