### ISSUE TITLE
Image Block has unexplainable bottom gap if wrapped within 3rd party container block

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#53537]
## Reproduction
- Create a block structure as visible and explained in the screenshot and video.
- **Problem**: The image blocks wrapped within the 3rd party [Greenshift](https://wordpress.org/plugins/greenshift-animation-and-page-builder-blocks/) container block, acting as grid item within the parent Greenshift container block acting as grid container, have an unexplainable 18px gap on the bottom, both noticeable in Block Editor and Frontend:

### Block Editor
![WordPress Image Block within 3rd party container block has unexplainable bottom gap in Block Editor](https://github.com/WordPress/gutenberg/assets/737143/9797355b-f167-4c7e-8e80-8afc1c7ea992)

https://github.com/WordPress/gutenberg/assets/737143/e960d13c-e114-48a9-89f7-645d3ee6b583

### Frontend
![WordPress Image Block within 3rd party container block has unexplainable bottom gap in Frontend](https://github.com/WordPress/gutenberg/assets/737143/d9c23b8a-2ebb-41b7-a63c-ee7d6893f8b6)

### Code Snippets

<details>
<summary> ℹ️  Block Editor - WordPress Markup — Click to expand</summary>

```html
<!-- wp:greenshift-blocks/container {"id":"gsbp-dd82d7a4-cf0e","calcOperator":["-"],"secondWidth":[],"secondWidthUnit":["px"],"width":[],"widthUnit":["%"],"minHeight":[],"rowspan":[],"columnspan":["2","1"],"columnStart":[],"columnEnd":[],"rowStart":[],"rowEnd":[],"alignSelf":[],"flexGrow":[],"flexShrink":[],"flexBasis":[],"flexBasisCustom":[],"flexGrowHover":[],"flexShrinkHover":[],"flexBasisHover":[],"flexBasisCustomHover":[],"flexGrowFocus":[],"flexShrinkFocus":[],"flexBasisFocus":[],"flexBasisCustomFocus":[],"order":[2,2],"minHeightUnit":["px","px","px","px"],"flexbox":{"enable":false,"type":"grid","gridcolumns":[3,2,null,1],"shrinkzero":false,"rowHeightUnit":[null,"em"],"rowHeight":[null,null],"columngapUnit":["em","em"],"columngap":[1,1],"rowgapUnit":["em","em"],"rowgap":[1,null],"gridtemplate":[null,0]},"animation":{"duration":700,"easing":"ease","type":""},"background":{},"overlay":{},"border":{"borderRadius":{"values":{},"unit":"px","locked":true}},"spacing":{"margin":{"values":{"top":["0px"]},"unit":["px","px","px","px"],"locked":false},"padding":{"values":{},"unit":["px","px","px","px"],"locked":false}},"shadow":{},"typography":{},"position":{"positionType":["","","",""],"positions":{"values":{}}},"shapeDivider":{"topShape":{},"bottomShape":{}},"responsive":{},"csstransform":{},"mobileSmartScroll":false,"minW":126,"maxW":348,"minWUnit":"px","maxWUnit":"px","carousel":{"arrowPos":[null,null,null,null],"arrowSize":[null,null,null,null],"arrowPosV":[null,null,null,null]},"imageBorder":{"borderRadius":{"values":{},"unit":"px","locked":true}},"imageShadow":{},"mobileSSpoint":1175,"blockWidth":{"customWidth":{"value":[],"unit":["px","px","px","px"]},"customHeight":{"value":[],"unit":["px","px","px","px"]},"widthType":""}} -->
<div id="gspb_container-id-gsbp-dd82d7a4-cf0e" class="gspb_container gspb_container-gsbp-dd82d7a4-cf0e wp-block-greenshift-blocks-container"><!-- wp:greenshift-blocks/container {"id":"gsbp-01c88e94-0a31","rowspan":[null],"columnspan":[null,"3",null,"1"],"columnStart":["1"],"columnEnd":["-1"],"rowStart":[null],"rowEnd":[null],"order":[null,null,null,""],"spacing":{"margin":{"values":{"top":["0px"]},"locked":false},"padding":{"values":{},"locked":false}}} -->
<div id="gspb_container-id-gsbp-01c88e94-0a31" class="gspb_container gspb_container-gsbp-01c88e94-0a31 wp-block-greenshift-blocks-container"><!-- wp:heading {"level":3,"style":{"typography":{"fontStyle":"normal","fontWeight":"400"},"spacing":{"margin":{"top":"0","right":"0","bottom":"0","left":"0"},"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"fontSize":"large"} -->
<h3 class="wp-block-heading has-large-font-size" id="special-booking" style="margin-top:0;margin-right:0;margin-bottom:0;margin-left:0;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;font-style:normal;font-weight:400">User prompted for choice when auto-rhythm fails</h3>
<!-- /wp:heading --></div>
<!-- /wp:greenshift-blocks/container -->

<!-- wp:greenshift-blocks/container {"id":"gsbp-86fa196e-39d4"} -->
<div id="gspb_container-id-gsbp-86fa196e-39d4" class="gspb_container gspb_container-gsbp-86fa196e-39d4 wp-block-greenshift-blocks-container"><!-- wp:image {"id":4959,"sizeSlug":"large","linkDestination":"none","style":{"border":{"width":"1px"}}} -->
<figure class="wp-block-image size-large has-custom-border"><img src="https://media.example.com/Kiosk-Book-Time-06b-Later-returning-from-business-trip-1024x640.webp" alt="Kiosk Book Time - Later returning from business trip" class="wp-image-4959" style="border-width:1px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:greenshift-blocks/container -->

<!-- wp:greenshift-blocks/container {"id":"gsbp-f1614c1c-a536"} -->
<div id="gspb_container-id-gsbp-f1614c1c-a536" class="gspb_container gspb_container-gsbp-f1614c1c-a536 wp-block-greenshift-blocks-container"><!-- wp:image {"id":4546,"sizeSlug":"large","linkDestination":"media","style":{"border":{"width":"1px"}}} -->
<figure class="wp-block-image size-large has-custom-border"><a href="https://media.example.com/Kiosk-Book-Time-07a1-Autorythm-fails-and-asks-choice.webp"><img src="https://media.example.com/Kiosk-Book-Time-07a1-Autorythm-fails-and-asks-choice-1024x640.webp" alt="Kiosk Book Time - Autorythm fails and asks choice" class="wp-image-4546" style="border-width:1px"/></a></figure>
<!-- /wp:image --></div>
<!-- /wp:greenshift-blocks/container -->

<!-- wp:greenshift-blocks/container {"id":"gsbp-898b0519-db95"} -->
<div id="gspb_container-id-gsbp-898b0519-db95" class="gspb_container gspb_container-gsbp-898b0519-db95 wp-block-greenshift-blocks-container"><!-- wp:image {"id":4547,"sizeSlug":"large","linkDestination":"media","style":{"border":{"width":"1px"}}} -->
<figure class="wp-block-image size-large has-custom-border"><a href="https://media.example.com/Kiosk-Book-Time-07a2-Further-rulesets.webp"><img src="https://media.example.com/Kiosk-Book-Time-07a2-Further-rulesets-1024x640.webp" alt="Kiosk Book Time - Further rulesets" class="wp-image-4547" style="border-width:1px"/></a></figure>
<!-- /wp:image --></div>
<!-- /wp:greenshift-blocks/container -->

<!-- wp:greenshift-blocks/container {"id":"gsbp-e090047e-4b29","order":[null]} -->
<div id="gspb_container-id-gsbp-e090047e-4b29" class="gspb_container gspb_container-gsbp-e090047e-4b29 wp-block-greenshift-blocks-container"><!-- wp:paragraph {"align":"left","style":{"spacing":{"margin":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":".has-text-justified"} -->
<p class="has-text-align-left .has-text-justified" style="margin-top:0;margin-right:0;margin-bottom:0;margin-left:0">1) Florian returns from his business trip to the office building and swipes his card. The system cannot make any meaningful automatic assumption. Hence it prompts: What's next?</p>
<!-- /wp:paragraph --></div>
<!-- /wp:greenshift-blocks/container -->

<!-- wp:greenshift-blocks/container {"id":"gsbp-ac76dc12-9a19"} -->
<div id="gspb_container-id-gsbp-ac76dc12-9a19" class="gspb_container gspb_container-gsbp-ac76dc12-9a19 wp-block-greenshift-blocks-container"><!-- wp:paragraph {"align":"left","style":{"spacing":{"margin":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":".has-text-justified"} -->
<p class="has-text-align-left .has-text-justified" style="margin-top:0;margin-right:0;margin-bottom:0;margin-left:0">2) Also according to company policy certain attendance or absence states can not be switched to from certain other states, e.g. Florian can not change from his current "Business Trip" to "Telework / Homeoffice".</p>
<!-- /wp:paragraph --></div>
<!-- /wp:greenshift-blocks/container -->

<!-- wp:greenshift-blocks/container {"id":"gsbp-5ac55e39-e49e"} -->
<div id="gspb_container-id-gsbp-5ac55e39-e49e" class="gspb_container gspb_container-gsbp-5ac55e39-e49e wp-block-greenshift-blocks-container"><!-- wp:paragraph {"align":"left","style":{"spacing":{"margin":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<p class="has-text-align-left" style="margin-top:0;margin-right:0;margin-bottom:0;margin-left:0">3) And certain states are limited to certain days of the week or hours of the day, e.g. "Online Training" only during 18:00-20:00 or a "Sports Break" only during 15:00-17:00.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:greenshift-blocks/container --></div>
<!-- /wp:greenshift-blocks/container -->
```

</details>

<details>
<summary> ℹ️  Frontend - HTML — Click to expand</summary>

```html
<div id="gspb_container-id-gsbp-dd82d7a4-cf0e" class="gspb_container gspb_container-gsbp-dd82d7a4-cf0e wp-block-greenshift-blocks-container">
	<div id="gspb_container-id-gsbp-01c88e94-0a31" class="gspb_container gspb_container-gsbp-01c88e94-0a31 wp-block-greenshift-blocks-container">
		<h3 class="wp-block-heading has-large-font-size" id="special-booking" style="margin-top:0;margin-right:0;margin-bottom:0;margin-left:0;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;font-style:normal;font-weight:400">User prompted for choice when auto-rhythm fails</h3>
	</div>
	<div id="gspb_container-id-gsbp-86fa196e-39d4" class="gspb_container gspb_container-gsbp-86fa196e-39d4 wp-block-greenshift-blocks-container">
		<figure class="wp-block-image size-large has-custom-border"><img decoding="async" loading="lazy" width="1024" height="640" src="https://media.example.com/Kiosk-Book-Time-06b-Later-returning-from-business-trip-1024x640.webp" alt="Kiosk Book Time - Later returning from business trip" class="wp-image-4959" style="border-width:1px" srcset="https://media.example.com/Kiosk-Book-Time-06b-Later-returning-from-business-trip-1024x640.webp 1024w, https://media.example.com/Kiosk-Book-Time-06b-Later-returning-from-business-trip-300x188.webp 300w, https://media.example.com/Kiosk-Book-Time-06b-Later-returning-from-business-trip-150x94.webp 150w, https://media.example.com/Kiosk-Book-Time-06b-Later-returning-from-business-trip-768x480.webp 768w, https://media.example.com/Kiosk-Book-Time-06b-Later-returning-from-business-trip-1600x1000.webp 1600w, https://media.example.com/Kiosk-Book-Time-06b-Later-returning-from-business-trip-1536x960.webp 1536w, https://media.example.com/Kiosk-Book-Time-06b-Later-returning-from-business-trip-2048x1280.webp 2048w" sizes="(max-width: 1024px) 100vw, 1024px"></figure>
	</div>
	<div id="gspb_container-id-gsbp-f1614c1c-a536" class="gspb_container gspb_container-gsbp-f1614c1c-a536 wp-block-greenshift-blocks-container">
		<figure class="wp-block-image size-large has-custom-border"><a href="https://media.example.com/Kiosk-Book-Time-07a1-Autorythm-fails-and-asks-choice.webp" data-lbwps-width="2560" data-lbwps-height="1600" data-lbwps-srcsmall="https://media.example.com/Kiosk-Book-Time-07a1-Autorythm-fails-and-asks-choice.webp"><img decoding="async" loading="lazy" width="1024" height="640" src="https://media.example.com/Kiosk-Book-Time-07a1-Autorythm-fails-and-asks-choice-1024x640.webp" alt="Kiosk Book Time - Autorythm fails and asks choice" class="wp-image-4546" style="border-width: 1px; /* vertical-align: middle; */" srcset="https://media.example.com/Kiosk-Book-Time-07a1-Autorythm-fails-and-asks-choice-1024x640.webp 1024w, https://media.example.com/Kiosk-Book-Time-07a1-Autorythm-fails-and-asks-choice-300x188.webp 300w, https://media.example.com/Kiosk-Book-Time-07a1-Autorythm-fails-and-asks-choice-150x94.webp 150w, https://media.example.com/Kiosk-Book-Time-07a1-Autorythm-fails-and-asks-choice-768x480.webp 768w, https://media.example.com/Kiosk-Book-Time-07a1-Autorythm-fails-and-asks-choice-1600x1000.webp 1600w, https://media.example.com/Kiosk-Book-Time-07a1-Autorythm-fails-and-asks-choice-1536x960.webp 1536w, https://media.example.com/Kiosk-Book-Time-07a1-Autorythm-fails-and-asks-choice-2048x1280.webp 2048w" sizes="(max-width: 1024px) 100vw, 1024px"></a></figure>
	</div>



	<div id="gspb_container-id-gsbp-898b0519-db95" class="gspb_container gspb_container-gsbp-898b0519-db95 wp-block-greenshift-blocks-container">
		<figure class="wp-block-image size-large has-custom-border"><a href="https://media.example.com/Kiosk-Book-Time-07a2-Further-rulesets.webp" data-lbwps-width="2560" data-lbwps-height="1600" data-lbwps-srcsmall="https://media.example.com/Kiosk-Book-Time-07a2-Further-rulesets.webp"><img decoding="async" loading="lazy" width="1024" height="640" src="https://media.example.com/Kiosk-Book-Time-07a2-Further-rulesets-1024x640.webp" alt="Kiosk Book Time - Further rulesets" class="wp-image-4547" style="border-width:1px" srcset="https://media.example.com/Kiosk-Book-Time-07a2-Further-rulesets-1024x640.webp 1024w, https://media.example.com/Kiosk-Book-Time-07a2-Further-rulesets-300x188.webp 300w, https://media.example.com/Kiosk-Book-Time-07a2-Further-rulesets-150x94.webp 150w, https://media.example.com/Kiosk-Book-Time-07a2-Further-rulesets-768x480.webp 768w, https://media.example.com/Kiosk-Book-Time-07a2-Further-rulesets-1600x1000.webp 1600w, https://media.example.com/Kiosk-Book-Time-07a2-Further-rulesets-1536x960.webp 1536w, https://media.example.com/Kiosk-Book-Time-07a2-Further-rulesets-2048x1280.webp 2048w" sizes="(max-width: 1024px) 100vw, 1024px"></a></figure>
	</div>
	<div id="gspb_container-id-gsbp-e090047e-4b29" class="gspb_container gspb_container-gsbp-e090047e-4b29 wp-block-greenshift-blocks-container">
		<p class="has-text-align-left .has-text-justified" style="margin-top:0;margin-right:0;margin-bottom:0;margin-left:0">1) Florian returns from his business trip to the office building and swipes his card. The system cannot make any meaningful automatic assumption. Hence it prompts: What’s next?</p>
	</div>
	<div id="gspb_container-id-gsbp-ac76dc12-9a19" class="gspb_container gspb_container-gsbp-ac76dc12-9a19 wp-block-greenshift-blocks-container">
		<p class="has-text-align-left .has-text-justified" style="margin-top:0;margin-right:0;margin-bottom:0;margin-left:0">2) Also according to company policy certain attendance or absence states can not be switched to from certain other states, e.g. Florian can not change from his current “Business Trip” to “Telework / Homeoffice”.</p>
	</div>
	<div id="gspb_container-id-gsbp-5ac55e39-e49e" class="gspb_container gspb_container-gsbp-5ac55e39-e49e wp-block-greenshift-blocks-container">
		<p class="has-text-align-left" style="margin-top:0;margin-right:0;margin-bottom:0;margin-left:0">3) And certain states are limited to certain days of the week or hours of the day, e.g. “Online Training” only during 18:00-20:00 or a “Sports Break” only during 15:00-17:00.</p>
	</div>
</div>
```

</details>

### Image — Linked or Not — Makes no difference
- For testing purposes I set the 1st image block to not link to anything, whereas 2nd and 3rd image link to their corresponding media file. This makes no difference!
  - The whole linked image works as a click zone (as expected) but interestingly when hovering the `<a>` it in the DOM it shows it to have a height of 21px and it is aligned on the lower part of the image with a "padding" of 2-3px:

https://github.com/WordPress/gutenberg/assets/737143/76c520a6-e28d-4d94-96b0-23af7557481d

### Native Image block within native Group block does not have that bottom gap

https://github.com/WordPress/gutenberg/assets/737143/3b49ab0e-60ce-44e9-b752-131a49ddcd93

### Where do the 18px come from?

- From the style engine comes: `:where(figure) { margin:0 0 1em }`
  - Inspecting `figure.wp-block-image` shows that there the `font-size` is `18px`.
  - The same as our gap. Some suspicion moment at least…
- UA Style for `figure` is in effect in the DOM:
```css
display: block;
margin-block-start: 1em;
margin-block-end: 1em;
margin-inline-start: 40px;
margin-inline-end: 40px;
```
- Overriding the inline style for the `*-end` attributes in a particular `figure.wp-block-image` had no visible effect.

- `figure.wp-block-image > img` inspected in DOM behaves normal too:
```css
Inline Style {
border-width: 1px;
}
.wp-block-image.has-custom-border img {
box-sizing: border-box;
}
.wp-block-image img {
vertical-align: middle;
}
.wp-block-image img {
box-sizing: border-box; /* inactivated by higher rule - see above */
height: auto;
max-width: 100%;
vertical-align: bottom; /* inactivated by higher rule - see above */
}
```
- My inspection & experiments led no nothing. Have no further ideas how to fix this.

## Priority & Suspicion

- Given that the native Group block and Columns block has only very rudimentary responsive design capabilities, it is somehow important that the native image block works reliably within 3rd party container blocks, given of course that best practices are followed.
- I suspect this to be just another variant of what we experienced in
  #52944
- where a block falsely uses a CSS inline display mode and hence the browser keeps place free under the image for an assumed text descender, as explained in: [Removing White Space Below Image Elements](https://mor10.com/removing-white-space-image-elements-inline-elements-descenders/) by [Morten Rand-Hendriksen](https://mor10.com/author/mor10-2/):

!["Removing White Space Below Image Elements" or "Why Inline Elements Have Descenders"](https://mor10.com/wp-content/uploads/2014/07/imagedescender.png)

## Environment
- WordPress 6.3
- Gutenberg 16.4.0
- [Greenshift](https://wordpress.org/plugins/greenshift-animation-and-page-builder-blocks/) 6.5.7

**Comment by porg** [comment]
Pinging:

- Those involved in #52944 : @t-hamano @lunaluna @jasmussen @richtabor @comesuccingfuccslot
- Author of the 3rd party plugin [Greenshift](https://wordpress.org/plugins/greenshift-animation-and-page-builder-blocks/): @wpsoul

**Comment by jordesign** [comment]
Just to confirm @porg  - this gap only appears when the third party container is in use?

**Comment by porg** [comment]
Yes just then.

Possibly this could also happen when being wrapped in a native container type block like Group, Columns, etc. 

But I have yet not encountered that. And could also not voluntarily reproduce it in my „provocation test“ visible in above video „Native Image block within native Group block does not have that bottom gap“.

**Comment by jasmussen** [comment]
Can you share the block markup? Go into the code editor and share the result:

<img width="364" alt="Screenshot 2023-08-11 at 09 34 11" src="https://github.com/WordPress/gutenberg/assets/1204802/93bc5428-6da2-4085-ac34-d561fb541f9d">

You can also inspect on the frontend and copy over the markup.

**Comment by porg** [comment]
You oversaw both: In section **Code Snippets** both the WordPress markup and the Frontend HTML are included. „Click to expand“ it says. 😂

**Comment by jasmussen** [comment]
Ah, sorry about that. It's coming from this CSS:

<img width="262" alt="Screenshot 2023-08-11 at 12 45 27" src="https://github.com/WordPress/gutenberg/assets/1204802/a6bcaaf9-f42c-43ae-990f-64235c99b395">

That's solved in core containers through some rules that are applied based on the layout type:

<img width="271" alt="Screenshot 2023-08-11 at 12 47 15" src="https://github.com/WordPress/gutenberg/assets/1204802/83998b7b-353c-4852-8328-22f2e145364e">

I would think if the third party blocks opt into layout types, it would solve that issue, but I'm also not sure some of the intricacies, perhaps @tellthemachines knows more. That said, from my angle this _looks_ intentional, in that the basic `figure` element, even from the browser's side, comes with some CSS that adds bottom margin.

**Comment by t-hamano** [comment]
I think this issue should be addressed on the plugin side.

I tested that plugin in Playground and from the markup, it does not appear that the container block opts in to the core layout type. If that custom container block has its own layout functionality, I think it is incumbent on that plugin to control the top and bottom margins of its child elements.

![playground](https://github.com/WordPress/gutenberg/assets/54422211/96bb5e0e-29ff-4fd6-9cbf-848ead157088)

**Comment by porg** [comment]
## My personal fix

`wp-content/themes/my-theme/assets/css/blocks/greenshift-blocks-container.css` contents:

```css
.wp-block-greenshift-blocks-container .wp-block-image { margin: 0; }
```

`wp-content/themes/my-theme/functions.php` contents:

```php
function my-theme_enqueue_block_styles() {
	$blocks = array(
		...
		'greenshift-blocks/container', // gets enqueued inline conditionally (= if block on current page) by Style Engine
		...
	);
	
	// Loop through each block and enqueue its styles.
	foreach ( $blocks as $block ) {
		
		// Replace slash with hyphen for filename.
		$slug = str_replace( '/', '-', $block );
		
		wp_enqueue_block_style( $block, array(
			'handle' => "my-theme-block-{$slug}",
			'src'    => get_theme_file_uri( "assets/css/blocks/{$slug}.css" ),
			'path'   => get_theme_file_path( "assets/css/blocks/{$slug}.css" )
			) );
		}
	}
add_action( 'init', 'my-theme_enqueue_block_styles' );
```

## What should I tell the 3rd party developer exactly?

As long as you don't opt in to core layout type, please make sure to include a CSS to your plugin like:

```css
.wp-block-greenshift-blocks-container .wp-block-image { margin: 0; }
```

**Comment by porg** [comment]
## My CSS selector is pretty "brute-force"
I guess should be more fine tuned:
- Only match if the image has no caption
- If it has a caption text, will it need that `margin: 0 0 1em` to be visible at all, or is that margin an extra below the bottom of the caption (be it a single line or wrapping onto 2+ lines) ?

**Comment by t-hamano** [comment]
Sorry, we cannot assist you in finding out more about how third-party plugins are implemented and what you should do to resolve the issue.

I suggest you ask your question in the plugin forum.

**Comment by porg** [comment]
Sorry for asking something which I could then find out easily in 5min myself. Good news:

`.wp-block-greenshift-blocks-container .wp-block-image { margin: 0; }` is sufficient.
- because `.wp-block-image` is on a `<figure>` element. 
- and if you add a caption to your image block then `<figure>` gets a `<figcaption>` child having its own spacing:


https://github.com/WordPress/gutenberg/assets/737143/4838f105-f6ac-4aa2-a76c-6f97147ca000

**Comment by t-hamano** [comment]
I am glad to hear that. I would like to close this issue, as I believe you have solved your problem and this is not Gutenberg-related problem.

If you face this kind of problem in the future, I would be glad if you could test if it occurs with a combination of core blocks and if you can reproduce it with plugins other than Gutenberg disabled.

**Comment by porg** [comment]
**Lesson learned:** Should I experience undesired "bottom gap phenomena" again I will first test constellations with "core blocks only" vs. "with 3rd party blocks mixed in" and judge it from that angle.

**Regarding closing**: I just wanted to make sure that WP offers something adequate to 3rd party plugins who want to comply.
- Now that I read that "3rd party blocks can opt in to the core layout type" from both [@jasmussen](#issuecomment-1674556426) and [@t-hamano](#issuecomment-1674768516)  I think that is a given.
- Last please send me the relevant spec for this that I know where to point 3rd party block devs to should said phenomena arise.
- Thanks again. From my side you can close then. I think everything was addressed.

**Comment by porg** [comment]
I also informed the 3rd party developer on how to fix it:

https://wordpress.org/support/topic/wp-image-block-wrapped-in-greenshift-container-should-not-have-bottom-margin/

**Comment by tellthemachines** [comment]
@porg if you'd like to have core layout spacing on your custom block you can add `layout: true` to your block.json file in the `supports` section. that will by default provide some layout controls for the block in the sidebar; if you don't wish to show these you can instead add 
```
"layout": {
    "allowEditing": false
}
```

**Comment by porg** [comment]
Thanks for the info. Should the plugin developer come here, s/he will see that possibility too then. Thanks!
