### ISSUE TITLE
Moving a block in list view can't be undone

### ISSUE THREAD

**Issue by bozzmedia** [WordPress/gutenberg#53546]
### Description

When dragging and dropping blocks inside of the list view, undo doesn't work. If I retry the same action inside the canvas area it does work.

UPDATE: Issue in Firefox, Works in Chrome.

### Step-by-step reproduction instructions

1. In the block editor, add multiple blocks
2. Select list view
3. Change the order or nesting of a block
4. Use keyboard or mouse to select undo
5. Observe the action is not undone

### Environment info

Win10, Firefox 116, WP 6.2.2 or 6.3, GeneratePress Theme, PHP 8.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by jordesign** [comment]
Hi @bozzmedia - I could _initially_ recreate this in testing in Firefox. In my testing, however, I found that after a save or refresh that undo _did_ start working.

Could you please retest and see if, after reloading the editor, you are able to make changes to a list and then undo them?

**Comment by bozzmedia** [comment]
@jordesign thanks for quickly reviewing this. I can confirm if I save as draft the undo feature works as expected. This seems to be the case whether it's a new post or editing an existing post.

**Comment by Mamaduka** [comment]
Thanks for the additional details, @bozzmedia!

Could you tell me if the issue only happens in Firefox?

**Comment by bozzmedia** [comment]
Hi @Mamaduka -- I have tested in Chrome, Edge and Firefox. I have only been able to replicate this in Firefox. Thanks for looking into it!

**Comment by Mamaduka** [comment]
@bozzmedia, I just tested with Firefox (116.0.2) on MacOS. WordPress 6.3 with/without the Gutenberg plugin and couldn't reproduce the issue. I've attached the screencast below.

Is there any specific block in the post where this issue happens, or just any block?

## Screencast

https://github.com/WordPress/gutenberg/assets/240569/cd4ba3ea-5ca1-43b2-85e2-8ba0a28b1525

**Comment by bozzmedia** [comment]
I used paragraph, headings and third party blocks, for all this sort issue occurs. Perhaps this is limited to the Firefox on Windows.

**Comment by Mamaduka** [comment]
@bozzmedia, do you mind testing only with core blocks (Paragraph, Heading, Image), so we can narrow down the cause of the issue?

@t-hamano, could you also give this a try?

**Comment by bozzmedia** [comment]
Hmm, having trouble reproducing this now, with core or third party blocks on 6.3, FF Win10. I did perform some updates to GeneratePress theme and other plugins, perhaps that was the culprit. I will test again on a different machine and report back if I can continue to reproduce.

**Comment by t-hamano** [comment]
I tested the following combinations to see if I could reproduce this problem after loading the editor for the first time, but could not reproduce it in either scenario.

- Enable the latest Gutenberg plugin
  - iframed editor
    - In a new post
    - In an existing post
  - Non-iframed editor (enable custom field)
    - In a new post
    - In an existing post
- Disable the latest Gutenberg plugin
  - iframed editor
    - In a new post
    - In an existing post
  - Non-iframed editor (enable custom field)
    - In a new post
    - In an existing post

My environment is the following:

- Windows 11
- Firefox 116.0.2

Below is a captured example of one of the tests.

https://github.com/WordPress/gutenberg/assets/54422211/41509e6e-06ed-4054-9c10-6518abf03abf

**Comment by Mamaduka** [comment]
Thank you, @t-hamano!

**Comment by t-hamano** [comment]
Hi @bozzmedia,

Are you still reproducing this problem? I would appreciate it if you could disable all plugins and test if this problem occurs.

**Comment by bozzmedia** [comment]
I'm having trouble replicating this on a consistent basis. I'll close this for now unless anyone else is able to replicate it successfully.
