### ISSUE TITLE
@webpack-cli/generators@3.0.7 has some deprecated NPM modules

### ISSUE THREAD

**Issue by stein2nd** [WordPress/gutenberg#53552]
### Description

When `ncu` was executed, `@wordpress/scripts` was displayed as `^26.9.0 → ^26.10.0`, so `ncu -u` `npm install` was executed in sequence.
As a result, several npm modules were shown as deprecated as follows:

npm WARN deprecated debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

These issues has been resolved in [3891](https://github.com/webpack/webpack-cli/issues/3891), [3892](https://github.com/webpack/webpack-cli/issues/3892), and [3893](https://github.com/webpack/webpack-cli/issues/3893) reported in webpack-cli, so it is appropriate to replace it with the latest version.

### Step-by-step reproduction instructions

1. ncu
2. ncu -u
3. npm install

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/531628/73f89ae1-ee6b-4dde-b9cc-ce9fdde1d212)

![image](https://github.com/WordPress/gutenberg/assets/531628/ee83d7c4-c6b7-4763-82c0-c036eed8caa1)

![image](https://github.com/WordPress/gutenberg/assets/531628/fdd5a3ee-79e8-4872-87fc-20cfbb8eb596)

## System:
 - OS: macOS 13.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 478.66 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 20.5.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 9.8.0 - ~/.nodebrew/current/bin/npm
## npmPackages:
 - @webpack-cli/generators: ^3.0.7 => 3.0.7 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by stein2nd** [comment]
After upgrading to @wordpress/scripts@26.11.0, we have confirmed that issue https://github.com/WordPress/gutenberg/issues/53553 has been successfully resolved, but issue https://github.com/WordPress/gutenberg/issues/53552 continues to occur.

Does this mean that this is happening because @webpack-cli/generators is not fixing its own deprecated issues https://github.com/webpack/webpack-cli/issues/3891 with "debuglog", "readdir-scoped-modules", and "@npmcli/move-file"?

**Comment by gziolo** [comment]
@stein2nd, thank you for the report. It looks like `webpack-cli` needs to be updated to the latest version. There were some breaking changes in [v5.0.0](https://github.com/webpack/webpack-cli/compare/webpack-cli@4.10.0...webpack-cli@5.0.0), but they hopefully won't have impact.

**Comment by gziolo** [comment]
I opened https://github.com/WordPress/gutenberg/pull/54657 that might fix this issue.

**Comment by stein2nd** [comment]
[@webpack-cli/generators@3.0.7] yeoman-environment has some deprecated packages.
- debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
- readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
- @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

Aren't these all because "yeoman-environment" is an older version?
