### ISSUE TITLE
Unable to update an existing post after making a change

### ISSUE THREAD

**Issue by brianhogg** [WordPress/gutenberg#5355]
## Issue Overview
Update button is disabled when editing a page

## Steps to Reproduce (for bugs)

1. When viewing a page, click Edit Page
2. Note that the 'Update' button is disabled, and click inside the content to edit
3. Make a change inside the content block
4. Note that Update is still disabled, unless you click somewhere outside the text block to 'blur' away from it which re-enables the Update button

Using Chrome on OSX.

## Expected Behavior

Update button should not be disabled.

## Current Behavior

Update button is disabled.

## Possible Solution

The update button is re-enabled on blur, but not sure where in the code is marking it as disabled in the first place.

## Screenshots / Video

https://youtu.be/yJU7TDdei7E

## Related Issues and/or PRs

I searched but wasn't able to find this particular issue as an existing issue.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by stompweb** [comment]
@brianhogg are you sure you're using the latest version of WP & GB? I've just tried this and the Update button was available as soon as I edited the text.

**Comment by youknowriad** [comment]
Yes this is fixed in 2.3.
