### ISSUE TITLE
Button: Replace deprecated isSmall property with size="small" property

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#53560]
Related to #53472

The deprecated `isSmall` property is being used in the Button component and in the component that wraps the `Button` component.

I believe that the `isSmall` property should be replaced with `size="prop"` to officially deprecate it, as mentioned in [this comment](https://github.com/WordPress/gutenberg/pull/53472#issuecomment-1673643125).

![button-deprecated](https://github.com/WordPress/gutenberg/assets/54422211/08bb6422-0572-4330-8e04-029463774793)

**Comment by skorasaurus** [comment]
Note isSmall is used in several other places and there's a PR  to fix it at https://github.com/WordPress/gutenberg/pull/53599

**Comment by fabiankaegy** [comment]
I can see there are more instances still. So reopening

**Comment by jaclync** [comment]
I'm taking on this one.

**Comment by jaclync** [comment]
For future contributors, the remaining components to replace that I found:

- [ ] `SidesDropdown`
- [ ] `PaletteEdit`
- [ ] `ToolsPanelHeader`

**Comment by t-hamano** [comment]
Once #59302 is merged, all isSmall props will be replaced and this issue can be closed. Thank you to everyone who worked on this issue!
