### ISSUE TITLE
Details block link text issue.

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/gutenberg#53563]
### Description

Hello Team,

I have worked on the Gutenberg details block and found that the details block color setting is not working properly. The block link text color or link hover color did not change based on selection when I changed it.

Here, I have provided its video:

Detail Block Issue: **[https://share.cleanshot.com/wMXrH71fr63v48cHt2CM](https://share.cleanshot.com/wMXrH71fr63v48cHt2CM)**

Please review it and let me know your feedback for the same.

Thanks,

### Step-by-step reproduction instructions

- Type / to choose a Details block
- Add block title
- Add paragraph text
- Change the link text color using the block color setting.
- Save the changes and publish the page.
- Then open page Preview in the new tab

### Environment info

- WordPress version: 6.3, Gutenberg Version 16.4.0, Theme active: Twenty Twenty, Twenty Twenty-Two, Twenty Twenty-Three,
- Browser: Google Chrome, Version 115.0.5790.170 (Official Build) (arm64)
- Device: MacBook Air M1
- OS: macOS Ventura 13.4.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

Looking at your screencast, I see that you are applying the text color to the paragraph block inside the Details block. So if you change the text color or link color in the parent Details block, it will not be applied to the child paragraph blocks because they have their own text color.

If you do not apply the color to the child block, both the text color and link color will be applied correctly.

![details](https://github.com/WordPress/gutenberg/assets/54422211/bce95583-a25c-4ff6-9992-d42ab4df8462)

**Comment by viralsampat-multidots** [comment]
Hello @t-hamano 

Thank you so much for the detailed update.

I have tested this issue again and found that we have two settings. One for the parent block and one for the child(Paragraph) block. When we apply text color for the parent block, it applies to the entire text.

After that, I applied color to a paragraph block text & link, and it's working as expected.

But when I reset the parent block change And set the text color again, it changes the child block link color with the parent text color. For better reference, here I have provided a video link.

**Detail Block Issue: [https://share.cleanshot.com/NGqfHnq6GTXGDPYFMdjW](https://share.cleanshot.com/NGqfHnq6GTXGDPYFMdjW)**

Thanks,

**Comment by t-hamano** [comment]
> But when I reset the parent block change And set the text color again, it changes the child block link color with the parent text color. For better reference, here I have provided a video link.

After investigation, I believe this is a problem with the link collar logic itself. I have summarized this problem in #53801 and would like to close this issue.
