### ISSUE TITLE
Documentation: Use consistent prefixes in code examples

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#53567]
## What problem does this address?

Looking at this code  example,
https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/
```
function filter_metadata_registration( $metadata ) {
    $metadata['apiVersion'] = 1;
    return $metadata;
};
```
The PHP function is not prefixed. If someone copy-pastes this and doesn't change the function name, there is a small risk of naming conflicts.

## What is your proposed solution?

Use `wpdocs` as the prefix in all code examples where one is needed.

**Comment by bacoords** [comment]
I'm submitting a PR with all the PHP examples fixed

**Comment by aurooba** [comment]
I think we should update the prefixes for the javascript examples as well. While conflicts there are _less_ likely, they are still possible, and having that consistency across both PHP and JS would be good.

**Comment by bacoords** [comment]
@aurooba Agreed.

Curious what others think about the [Block Tutorial](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/writing-your-first-block-type/) section in the how-to guides. The example code is a plugin named "Gutenberg Examples," so we see that prefix throughout the code and in the block name:

```php
function gutenberg_examples_dynamic_block_supports() {
	register_block_type(
		'gutenberg-examples/example-dynamic-block-supports',
...
```

Would we want to see something more consistent: 

```php
function wpdocs_dynamic_block_supports() {
	register_block_type(
		'wpdocs/example-dynamic-block-supports',
...
```

And further, would we want to update the fake plugin name entirely to remove the reference to Gutenberg?

**Comment by aurooba** [comment]
I would definitely lean towards removing the `gutenberg_examples` prefix for sure, and adding the `wpdocs/` prefix for the blocks makes a lot of sense too.
