### ISSUE TITLE
Multi-select: Add/remove single block to/from selection via modifier key  -- CMD on Mac / CTRL on Windows/Linux

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#53589]
## Usability Foreword
Selecting multiple elements, efficiently adding/removing to that selection, and then eventually move/edit the whole selection is a crucial function for WYSIWYG design software.

## I) Continuous selection — From first til last via SHIFT key
1. Click first element in left side tree pane ("Document Outline" ) or on canvas.
2. Hold down the ⇧ SHIFT modifier key.
3. Click last element in tree pane or on canvas.

**Expected Outcome**: Selects all elements from first to last (as in tree pane order, not necessarily equal to visual order)
- Implemented in very early issue: #62

- ✅ Mac Chrome
- ✅ Mac Safari — Was improved just recently in #53440

## II) Add to / remove from selection — Via other modifier key
1. You have an existing selection — Single clicked block, or a selection from a mix of method(s) I or II.
2. Hold down the add/remove modifier key (⌘ CMD on Mac ; ⌃ CTRL on Windows/Linux)
3. Click unselected element to add it, click selected element to remove it.

- ❌  Not supported in the browsers that I tested: Mac Safari, Mac Chrome
- Related: #41684

## Video which shows that continuous selection with ⇧  works but add/remove to/from selection via ⌘ does yet not work

https://github.com/WordPress/gutenberg/assets/737143/13f54379-f6e9-466c-936e-25012cb1fc1d

**Comment by ellatrix** [comment]
I _think_ you are asking for non-consecutive multi-selection? So this would be a duplicate of #16797?

**Comment by porg** [comment]
@ellatrix what I asked for is indeed a duplicate of #16797 which goes even beyond the selection process itself but also discusses how to handle the move operations of the [non-consecutive multi selected items](https://github.com/WordPress/gutenberg/issues/16797#issuecomment-616973130) then.

I'm glad that the core team is aware of the lack of this feature. Hence I'm closing my ticket.
