### ISSUE TITLE
Missing wp-block-columns-inline-css styles after upgrade to 6.3

### ISSUE THREAD

**Issue by Jastos** [WordPress/gutenberg#53588]
### Description

After upgrading the WP 6.3, there are missing inline styles for the columns block on the frontend. Things work fine in the editor.

One of the breaking changes is that .wp-block-column{flex-basis:0;flex-grow:1} is missing from the inline styles.

In theme.json style->blocks section:

```
"core/columns":{
  "spacing":{
    "margin":{
      "bottom":"0"
    },
    "blockGap":"var(--wp--preset--spacing--80)"
  }
}
```

Produces:

```
<style id="wp-block-columns-inline-css">
.wp-block-columns{margin-bottom: 0;}.wp-block-columns-is-layout-flow > :first-child:first-child{margin-block-start: 0;}.wp-block-columns-is-layout-flow > :last-child:last-child{margin-block-end: 0;}.wp-block-columns-is-layout-flow > *{margin-block-start: var(--wp--preset--spacing--80);margin-block-end: 0;}.wp-block-columns-is-layout-constrained > :first-child:first-child{margin-block-start: 0;}.wp-block-columns-is-layout-constrained > :last-child:last-child{margin-block-end: 0;}.wp-block-columns-is-layout-constrained > *{margin-block-start: var(--wp--preset--spacing--80);margin-block-end: 0;}.wp-block-columns-is-layout-flex{gap: var(--wp--preset--spacing--80);}.wp-block-columns-is-layout-grid{gap: var(--wp--preset--spacing--80);}
</style>
```

Which is missing core styles.

### Step-by-step reproduction instructions

This doesn't happen on a clean install of 6.3. Only happens when I upgraded from 6.2. Haven't been able to determine the cause. I have tried using 2023 theme.json, removing all plugins, and removing all enqueued CSS/JS.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Jastos** [comment]
Things work as expected if I activate Gutenberg 16.4.0. If I deactivate Gutenberg, WP 6.3 is missing inline styles.

**Comment by ndiego** [comment]
Thanks for reporting @Jastos. Unfortunately I have been unable to replicate. These are the steps that I followed: 

1. Setup a fresh WordPress install using 6.3
2. Made sure the TT3 theme was active and disabled all other plugins
3. Added the following code to the TT3 theme.json file. 

```
"core/columns":{
  "spacing":{
    "margin":{
      "bottom":"0"
    },
    "blockGap":"var(--wp--preset--spacing--80)"
  }
}
```

4. I then added a Columns block to a blank page and confirmed the default block spacing of `--wp--preset--spacing--80` is set along with margin 0.

**Comment by Jastos** [comment]
@ndiego I think this has to do with this ticket:
https://core.trac.wordpress.org/ticket/59111

If I set WP_DEVELOPMENT_MODE to core in the wp-config, the core columns block styles are back again. The columns block was not the only block that this was affecting. It also broke styles for the navigation & social blocks. I'm sure there were others I didn't notice as well.

Not sure what I did to change the normalized path, but that seems to be the issue.

**Comment by t-hamano** [comment]
> @ndiego I think this has to do with this ticket:
> https://core.trac.wordpress.org/ticket/59111

I believe this is true, and other than setting WP_DEVELOPMENT_MODE to core, the solution would be to

- If WP-CLI is available, run `wp transient delete wp_core_block_css_files`. See: https://core.trac.wordpress.org/ticket/59111#comment:4
- Run `delete_transient()` function. See: https://github.com/WordPress/gutenberg/issues/52199#issuecomment-1661430989

In any case, I think this is a problem that should be fixed in the core. Therefore, I would like to close this issue, but if I have missed something, please comment.
