### ISSUE TITLE
Editor help documentation images missing, content obscured

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#53591]
## Description

Images displayed within the editor's "Help" section display blank boxes rather than the images themselves.  Additionally, after closing and re-opening the help section, content is obscured by the scroll view only populating 50% of the device height. 

This appears to have begun occurring in 23.0 app release, likely related to #51303.

## Step-by-step reproduction instructions

1. Open the mobile editor. 
2. Tap the third-dot button in the top-right corner to open the action sheet. 
3. Tap Help. 
4. Navigate to any of the help topics. 

## Expected behaviour

The images are displayed and all text content is accessible via scrolling. 

## Actual behaviour

The image are missing and text content at the bottom of the page is inaccessible as it is cut off. 

## Screenshots or screen recording (optional)

<details><summary>Reproduction video</summary>

<video src="https://github.com/WordPress/gutenberg/assets/438664/4a529f28-c078-4f46-ae03-211a6948903e" />

</details>

| Before | After |
| - | - |
| ![before](https://github.com/WordPress/gutenberg/assets/438664/e1c378f6-db92-4367-a17e-00b1d7328d22) | ![after](https://github.com/WordPress/gutenberg/assets/438664/93ef7385-1279-436c-86de-49d27b488ac2) |
|  | ![cut-off](https://github.com/WordPress/gutenberg/assets/438664/3776df31-edeb-4555-b2f2-a612d2d372ae) |

## WordPress information
- WordPress version:  6.3
- Gutenberg version:  v16.4.0
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes

## Device information
- Device:  iPhone SE
- Operating system:  iOS 16.5.2
- WordPress app version:  23.0

**Comment by dcalhoun** [comment]
The cut off content occurs in the Demo editor (iOS and Android). So, possibly related to #52563, which was included in https://github.com/WordPress/gutenberg/pull/51303. 

The images correctly display when using the Demo editor (iOS and Android) and in the WordPress app for Android. So, the missing images in the WordPress app for iOS must relate to packaging the app via an XCFramework and https://github.com/wordpress-mobile/gutenberg-mobile/pull/5924.

**Comment by dcalhoun** [comment]
👋🏻 @mokagio do you know if we might need to define specific XCFramework packaging steps to include the relevant [static image files](https://github.com/WordPress/gutenberg/tree/73eca1d319eea0755d1935a2251bfe3935813be4/packages/editor/src/components/editor-help/images)? 

Running the `npm run bundle` command in `gutenberg-mobile` places these files into the [`bundle` directory](https://github.com/wordpress-mobile/gutenberg-mobile/tree/db879e15c1c5ee0aa7e85d1ae97d8504488e8466/bundle/ios/assets/gutenberg/packages/editor/src/components/editor-help/images). Presumably the files were then "picked up" by the pre-XCFramework iOS host app integration.

**Comment by derekblank** [comment]
> Do you know if we might need to define specific XCFramework packaging steps to include the relevant [static image files](https://github.com/WordPress/gutenberg/tree/73eca1d319eea0755d1935a2251bfe3935813be4/packages/editor/src/components/editor-help/images)?

I think this may be the case. According to the [docs](https://reactnative.dev/docs/images.html), the name of static image resources needs to be known at bundle time. When logging out the [source value](https://github.com/WordPress/gutenberg/blob/59a346da13c8c0d759bfe9609c15afb737922e53/packages/editor/src/components/editor-help/view-sections.native.js#L65-L67) of these images, an integer is returned. It appears either the name of the image is not being included, or the image itself is not being packaged.

(Side note: I noticed the combined size of these images is 9.7 MB. There is likely an opportunity to use WebP in place of PNG  resources here to reduce the bundle size.)

**Comment by dcalhoun** [comment]
> I think this may be the case. According to the [docs](https://reactnative.dev/docs/images.html), the name of static image resources needs to be known at bundle time. When logging out the [source value](https://github.com/WordPress/gutenberg/blob/59a346da13c8c0d759bfe9609c15afb737922e53/packages/editor/src/components/editor-help/view-sections.native.js#L65-L67) of these images, an integer is returned. It appears either the name of the image is not being included, or the image itself is not being packaged.

My understanding is that the documentation's reference to names relates to the lack of support for _dynamic_ names. E.g. you cannot interpolate a value ``<Image src={`image-${id}.jpg`} />``, as the interpolated value would need to be computed at runtime. I believe the return of an integer value is expected, at least from my experience logging value while running a Metro server. 

I believe your last point of images "not being packaged" is likely the cause of the reported missing images. My guess is that they are not included when generating the XCFramework. 

> (Side note: I noticed the combined size of these images is 9.7 MB. There is likely an opportunity to use WebP in place of PNG resources here to reduce the bundle size.)

Good idea!

**Comment by dcalhoun** [comment]
@mokagio we'd like to **address the reported issue in the 23.0 release** before it is published to the stores, if possible. The help articles can be difficult to comprehend without the visuals communicated with the images. 

I opened https://github.com/wordpress-mobile/gutenberg-mobile/pull/6061 exploring how we might include the static image assets in the XCFramework. Unfortunately, the XCFramework build fails in that branch locally. Would you be willing to help me debug or identify an alternative solution? 🙇🏻

**Comment by mokagio** [comment]
@dcalhoun sorry for the late followup. Having a look now 👀

**Comment by mokagio** [comment]
Possibly related to https://github.com/woocommerce/WooCommerce-Shared/issues/61#issuecomment-1642633376 which was solved via [updating the `bundle` call `--asset-dest` parameter](https://github.com/woocommerce/WooCommerce-Shared/pull/70).

**Comment by mokagio** [comment]
I'm working on https://github.com/wordpress-mobile/gutenberg-mobile/pull/6067 which is promising:

> ![](https://user-images.githubusercontent.com/1218433/260935828-7271cbd0-7dc8-4d44-8bb9-11f8a9e95626.png)

**Comment by derekblank** [comment]
Looks promising indeed, thanks for working on this fix @mokagio!

**Comment by mokagio** [comment]
I assume it's safe to close this because https://github.com/WordPress/gutenberg/issues/53591 landed. However, I don't have the rights to do it.

**Comment by SiobhyB** [comment]
Thanks for the prompt @mokagio, as well as for all your help fixing this! Going ahead to close now.
