### ISSUE TITLE
Handling "enter" on Heading block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#536]
Pressing enter in a heading should probably create a new text block if at the end of the line, or split a single heading in two headings if in the middle of the line.

**Comment by iseulde** [comment]
Looking now.

**Comment by iseulde** [comment]
I'm not entirely sure how to do this atm, without more controlled selection and content. @youknowriad Do you have any thoughts on this?

**Comment by iseulde** [comment]
Related: #579.

**Comment by youknowriad** [comment]
Does TinyMCE trigger a `onNewBlock` event when he creates a `<br /`>?

- If it's the case, we should just update this handler to split if we have two consecutive '<br>` (Same as we do we empty `<p>`). 
- If it's not the case, we should move the `onNewBlock` logic to the `onKeyDown` instead (same as the initial implementation) -> this requires adding a `setTimeout()` to wait for TinyMCE to effectively apply the `keydown` event.

**Comment by iseulde** [comment]
> Does TinyMCE trigger a `onNewBlock` event when he creates a `<br /`>?

It does not, as it's not a new block.

> If it's not the case, we should move the `onNewBlock` logic to the `onKeyDown` instead (same as the initial implementation) -> this requires adding a `setTimeout()` to wait for TinyMCE to effectively apply the `keydown` event.

So `keyup`?

**Comment by iseulde** [comment]
Closing for now. See https://github.com/WordPress/gutenberg/issues/579#issuecomment-301759016.
