### ISSUE TITLE
Audit all the translatable strings to meet core best practices

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#5361]
This is more a task that should run at some point to meet best practices used in core since years.

For good reasons, variables (for example post type and taxonomy names) shouldn't be used in translatable strings. They're impossible to translate in many languages, since translators can't predict whether the variable name is a female or male noun. 

Core always avoids to do that and that's a well established best practice. For some background, see for example 2 of the project leads explaining why:
https://core.trac.wordpress.org/ticket/17609#comment:3
https://core.trac.wordpress.org/ticket/19099#comment:1

In Gutenberg, there are strings that make use of placeholders representing names with unpredictable gender, for example see https://github.com/WordPress/gutenberg/blob/3fc70e7198c86cf007ee93e4287a457357b9a31e/editor/components/post-taxonomies/flat-term-selector.js#L176

```
sprintf( _x( '%s added', 'term' ), singularName );
sprintf( _x( '%s removed', 'term' ), singularName );
sprintf( _x( 'Remove %s: %%s', 'term' ), singularName );
```

These strings are not translatable and should be fixed to meet core best practices.

Other cases should be carefully reviewed by people with great expertise in i18n and l10n issues, I'd recommend to ask @SergeyBiryukov, @ocean90, and @swissspidy for example.

I'd also wonder about a possible mechanism to implement translators comments in JS, or any other kind of mechanism to offer translators a better context. For example, as a translator, I wouldn't know how to translate a string like:
`sprintf( _x( 'Remove %s: %%s', 'term' ), singularName );`

even if it's using `_x()` I wouldn't have any clue what the two `%s` are, and we can't expect non-technical people are able to search for the specific use case in the codebase, nor they should be asked to do that.

**Comment by afercia** [comment]
I see now there is a way to add translators comments, sorry I missed that. So the first point about post type and taxonomy names is still valid. About comments, I'd just recommend to review them carefully as seems to me they could be improved a bit. This should be a task to run at some point. A couple random examples:

```
/* translators: Block title modifier */
__( '%1$s (%2$s)' ),
```

As a translator, I wouldn't find the comment of great help.

```
/* translators: 1: block name */
$message = sprintf( __( 'Block type "%s" is already registered.', 'gutenberg' ), $name );
```

there's no `1` in the string.

**Comment by jorgefilipecosta** [comment]
With merge of https://github.com/WordPress/gutenberg/pull/7201 this issue should be fixed if someone finds other improvements that could be made feel free to reopen the ticket.
