### ISSUE TITLE
Global styles revisions: revision comparisons

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#53620]
## What problem does this address?

It's possible to use WordPress's existing `revisions.php` page to compare the global styles custom post, however it means comparing changes to JSON, which may not be accessible to everyone.

<img width="988" alt="Screenshot 2023-07-24 at 15 56 22" src="https://github.com/WordPress/gutenberg/assets/846565/f73e26b4-7756-4b0e-a6b9-bdac5cc223a9">

It would be more useful to have a visual tool, or initially, a text summary of changes, to differentiate global styles revisions.

Discussed in:
- https://github.com/WordPress/gutenberg/pull/52829#issuecomment-1648177092
- https://github.com/WordPress/gutenberg/pull/50089#issuecomment-1529396895

## What is your proposed solution?

Ideally we'd have a visual representation of changes between two revisions. @jameskoster has been thinking about this:

- https://github.com/WordPress/gutenberg/pull/52829#issuecomment-1648177092
- https://github.com/WordPress/gutenberg/pull/50089#issuecomment-1527662011

As [mentioned previously,](https://github.com/WordPress/gutenberg/pull/50089#issuecomment-1529396895) it is possible to load two versions in two iframes:

https://user-images.githubusercontent.com/6458278/235428869-668a38f6-97f9-4ea1-b078-a3a6da103cc8.mp4

@c4rl0sbr4v0 has also explored a comparison engine to diff two theme.json trees: tenberg/pull/52829#issuecomment-1659027089

We probably need to undertake more investigation in order to balance performance and utility.

As a starting taster will might like to display top-level changes to the user, e.g., 

<img width="300" src="https://user-images.githubusercontent.com/6458278/236362936-f8d441a2-875f-4947-942b-01d50b6495b5.jpg" />

**Comment by jameskoster** [comment]
@ramonjd would you say this is duplicative of https://github.com/WordPress/gutenberg/issues/53484? (Feel free to edit that issue to add more flavour).

**Comment by ramonjd** [comment]
> would you say this is duplicative of https://github.com/WordPress/gutenberg/issues/53484? (Feel free to edit that issue to add more flavour).

Definitely! I'll move some of the info over to that one. Thanks for the heads up.

**Comment by ramonjd** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/53484
