### ISSUE TITLE
Global styles revisions: add pagination

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#53621]
## What problem does this address?
Pagination capability was added to the Global styles revisions endpoint in https://github.com/WordPress/gutenberg/pull/52095

At the moment the maximum amount of Global styles revisions we display in the site editor UI is `100`.

It's conceivable that sites will have more than this, and therefore would find pagination helpful.

## What is your proposed solution?
- Utilize pagination parameters in the global styles revisions rest endpoint to display `n` amount of global styles revisions in the UI. 
- Add pagination controls to the UI.

**Comment by allisonplus** [comment]
It'd be great to see pagination options be fully expanded (see screenshot) to include Prev/Next as well as total number of pages included so user knows total results.

![Image](https://github.com/WordPress/gutenberg/assets/10225971/a6a97fc3-0054-4dca-8ba2-a024b93d8f6b)

**Comment by apeatling** [comment]
Had a crack at the start of a design for this. Seems logical that this would be the general direction based on other pagination. There isn't enough space for the total number of items, this could perhaps go up in the top to the right of the "Revisions" title.

<img width="493" alt="Screenshot 2023-09-07 at 1 09 59 PM" src="https://github.com/WordPress/gutenberg/assets/1464705/7107198f-0847-41e7-95ed-cb3283ddfd01">

**Comment by ramonjd** [comment]
Thanks for the help on direction folks. The first task I believe is to ensure that the core data store can handle and manage the incoming revision entities and related pagination queries. I'm going to take a look at this.

**Comment by jasmussen** [comment]
A couple of more options:

<img width="384" alt="Frame 1" src="https://github.com/WordPress/gutenberg/assets/1204802/0cf37a76-c714-4a0f-a9de-58008b463d8e">

Notably I think we can be a bit more compact with the use of space, by using borderless buttons, by skipping the first-page/last-page buttons, and by disabling the left button on the first page, etc.

I'd also start simple, I'm not quite sure how many pages of revisions we can expect here, but if we end up with hundreds of pages we should probably still skip the first-page/last-page buttons in favor of the ... system. What do you think?

**Comment by ramonjd** [comment]
> we should probably still skip the first-page/last-page buttons in favor of the ... system. What do you think?

Sounds good to me. We could have a threshold, e.g., when the pages hit `n` we switch to `...` 👍🏻

**Comment by jasmussen** [comment]
Yep, it can be tweaked to what fits. E.g. at most 5 items between the ellipses:

* 1  2  3  ...  49
* 1  ...  47  48  49
* 32  33  ...  48  49

**Comment by apeatling** [comment]
Looks good, and makes sense to start simple with it. 👍

**Comment by ramonjd** [comment]
Conversation about state and how to fetch post type revisions going on over in:

- https://github.com/WordPress/gutenberg/pull/54046

**Comment by ramonjd** [comment]
### Update

Getting closer to finalizing the core data API in https://github.com/WordPress/gutenberg/pull/54046, which will enable this feature. 

I might build the UI on top of that PR to demonstrate the designs. Cheers!

**Comment by ramonjd** [comment]
The underlying API works fine 👍🏻 

https://github.com/WordPress/gutenberg/assets/6458278/6c45baa4-e626-4f1a-8fcb-60d105cb0dfd

Slight speed bump: we're adding 2 x extra revision items on the frontend: an "unsaved" state at the start of the revisions array, and a "default theme" state at the end. This means we'll have to take these into account when building pages from the API response, and recalculate the offsets 🤔

**Comment by apeatling** [comment]
@pablohoneyhoney @mtias You'd talked about now wanting to use numbers in the pagination for style revisions. Should we move forward with a "Load More" style pagination for this?

**Comment by ramonjd** [comment]
I know it's not all about me 🤣 but the "Load more" approach would effectively side-step the pagination recalculation mania I came up against [in testing](https://github.com/WordPress/gutenberg/issues/53621#issuecomment-1756914210).

**Comment by ramonjd** [comment]
> You'd talked about now wanting to use numbers in the pagination for style revisions. Should we move forward with a "Load More" style pagination for this?

One argument for pagination is if users want to go to the start of history, and they have many revisions, they can immediately. Users may need to click multiple times to get to older content with a "Load more" button.

We "could" offer both, i.e., a component that lets the user choose between "Load more" and "Pagination" and "X" view/filter. Maybe I'm saying this because I've just been playing with dataviews. 😄  

Or, if we go with pagination initially, a dropdown menu to choose the number of items to display per page.

**Comment by ramonjd** [comment]
Have a WIP idea going on in:

- https://github.com/WordPress/gutenberg/pull/56799

https://github.com/WordPress/gutenberg/assets/6458278/98b079a4-b2ef-48b2-a5b0-b6edbd5c28a3

**Comment by ramonjd** [comment]
Latest from #56799



https://github.com/WordPress/gutenberg/assets/6458278/ee2c82e2-c138-4769-afc8-8433d6819eac

**Comment by ramonjd** [comment]
Another version

@apeatling with the Apply button inline now:

https://github.com/WordPress/gutenberg/assets/6458278/d9a87abc-ed18-4a59-b064-a8c737333961
