### ISSUE TITLE
Can't insert block (between blocks) without inserting Paragraph block first

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#5363]
## Issue Overview
I'm trying to insert a new block between existing blocks, and I'm forced to insert a paragraph block first (which I don't want), before selecting another block. You've just made inserting a block twice as complicated as what it was before. Previously, I could just insert the block I wanted. Now I'm forced to insert a Paragraph block first and then select another block on top of that to convert it to.

Why do I have to insert a block that I don't want? It's also extremely difficult to select a 3px width line between the blocks, and even more so when one of the blocks is already selected.

Why can't you go back to the original Inserter menu that you had at the bottom of each block? You can see on multiple issues that have been raised by other people since the last couple of updates, that everyone prefers the original block inserter menu. These last couple of Gutenberg updates have only made things harder than what they already were.

![gutenberg-insertingblockbetweenblock](https://user-images.githubusercontent.com/2078245/36929303-dd25cfc4-1ee2-11e8-8555-a9db16ea449e.gif)

## Steps to Reproduce (for bugs)
1. Open existing page/post
2. Click on the extremely thin line between blocks (which automatically inserts a paragraph block)
3. Click on Insert Menu (+) on paragraph block and select some other type of block

## Expected Behavior
I shouldn't have to insert "default" blocks before inserting the type of block I actually want.

## Current Behavior
If I want to insert a block between existing blocks, I'm forced to insert a Paragraph block first and then convert it to something else.

## Possible Solution
Restore old Insert Menu (+) that was at the bottom of every block.

_Firefox Quantum 58.0.2 (64-bit)
Gutenberg 2.3.0
WP 4.9.4_

**Comment by spencerfinnell** [comment]
Also very frustrating accidentally clicking this area and having a blank paragraph block inserted. Along with things like #5368 the editor is extremely difficult to use.

**Comment by youknowriad** [comment]
For now, the decision is not to restore the in-between inserter to limit the number of ways we can insert blocks into the editor, this may change over time depending on the feedback and the testing.

We're discussion refinements to the in-between inserter right now, let's consolidate there. #5396

**Comment by maddisondesigns** [comment]
@youknowriad Can you please reopen this. As the title says, the issue I raised was that you "Can't insert block (between blocks) without inserting Paragraph block first".

The in-between inserter was just mentioned as a side-note. The main issue is not being able to insert the actual block that I want to insert, and that your inserting default blocks that I dont want.

**Comment by youknowriad** [comment]
As I said, the decision was made to have this tradeoff, insert an empty paragraph block that you can replace with any block using the side inserter (or the top inserter) whether this decision is valid or not, feedback will tell but for now it's seems to be the right balance between the ease of inserting blocks and avoiding multiple ways to do it which harms the overall UX.

As I said, Nothing set is set in store, but for now, we're pretty happy with it.
