### ISSUE TITLE
Hyperlink Options Now Require More Clicks

### ISSUE THREAD

**Issue by rcrimi54** [WordPress/gutenberg#53643]
## What problem does this address?

In 6.3, when setting up a hyperlink, it now requires more clicks to get to and save the options.  In 6.2.x and previous versions, when you clicked on a hyperlink it opened  up the choices to "open in new windows", "search engines", etc.  6.3 requires to select edit then 'Advanced'.  This is not a useful change.  

## What is your proposed solution?

Please consider restoring the previous way editing hyperlinks operated.

**Comment by Mamaduka** [comment]
This is a duplicate of #52216 and #53463.

The #52799 introduces a potential fix to a problem and has recent discussions.
