### ISSUE TITLE
Inconsistent link preview flow between pasting and selecting links

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#53656]
When pasting a link onto text, we get the preview state right off. But when searching and clicking an internal entity to apply, LinkControl is closed entirely. Perhaps both should perform like pasting does, where the link preview is the next view you see. 

The effort in https://github.com/WordPress/gutenberg/pull/53566 attempts to do this at the moment. 

Linking via searching: 

https://github.com/WordPress/gutenberg/assets/1813435/221ec2de-e9f6-472a-b4ce-a769049085e1

Linking via paste: 

https://github.com/WordPress/gutenberg/assets/1813435/e1915c44-1b59-4e09-8728-dfd24618a871

**Comment by getdave** [comment]
This can be achieved by removing this line:

https://github.com/WordPress/gutenberg/blob/a7327a11f79135300cd69f40a797c866959a62ad/packages/format-library/src/link/inline.js#L188

But that causes a bug with positioning of the Popover. I [have researched this here](https://github.com/WordPress/gutenberg/pull/53566#issuecomment-1677265704) and it should be followed up upon:
