### ISSUE TITLE
External links in the Gallery block

### ISSUE THREAD

**Issue by theleemon** [WordPress/gutenberg#5366]
Currently, one can link to "media files" or "attachment pages" in the Gallery block. Is it planned to add a new option to link to external URLs, so for example, one can create galleries of logos? If not, can the Gallery block be extended via plugins to add this option?

**Comment by karmatosed** [comment]
You can extend the gallery block. I think for images right now as we have image blocks, adding in external links also that way. Galleries in WordPress don't out of the box support right now what you are suggesting either, so it's worth considering in a plugin. I am going to close this issue as it's not something being worked on or planned.

**Comment by Jdeboysere** [comment]
Not being worked on or planned. What a joke! Go telling that to our customers! We are ALL waiting for this feature for years! WordPress is seriously living at the stone age!

Yes we can use https://fr.wordpress.org/plugins/wp-gallery-custom-links/ but it is only available in 6 languages (EN, DE, ES, NL, PL, BR) and the option is very hidden. This feature should be in core **for years**! Wake up please.

Please work on this feature and update your gallery grid. Your gallery is still using float:left. Please use flexbox!

Mid-2018. Wake up. Seriously. Your priorities make us mad.

**Comment by designsimply** [comment]
Media will be more of a focus in the next phase of development after a stable release is merged. It's good to have your feedback, and I noticed someone has opened a new issue asking about this again in #10057 which I have added to the Ideas project which is tracking requests like this one and it will be reviewed there.

**Comment by qwik3r** [comment]
+1

**Comment by jcoonrod** [comment]
+1 two years later...
