### ISSUE TITLE
Post Content Block > ellipsis menu > no Add before / Add after option

### ISSUE THREAD

**Issue by Marc-pi** [WordPress/gutenberg#53680]
### Description

When building our templates, there is not way to add a block before or after the Post Content Block
the only way is to use another block or pattern, then add before or after, and then rearrange the block order with List View

![image](https://github.com/WordPress/gutenberg/assets/919332/5cf0c049-043c-456c-8cff-5707024fa2c3)

### Step-by-step reproduction instructions

1. Create a new template
2. add the Post Content Block
3. look for the ellipsis dots, there are none !

### Environment info

- WP 6.x , we still have the issue with 6.3
- Gutenberg 16.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
Hm, I'm not seeing this actually. 

<img width="599" alt="CleanShot 2023-08-15 at 10 17 27" src="https://github.com/WordPress/gutenberg/assets/1813435/1adfed79-1dc5-4fc8-9384-85dc39a6f686">

**Comment by Marc-pi** [comment]
hum, strange, i've got it twice on 2 different websites
what i know is that i create a Front Page Template
Manage All Templates > Add New Template > Front Page
i tested again, it works now, i'll reopen once i detect another case
