### ISSUE TITLE
Image upload error does not provide feedback

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#5370]
## Issue Overview

When uploading an image with a file size too big, by drag and drop, the image just sat and pulsed making me thing it was uploading. After awhile it just continued to pulse I realized there was an issue.

I switched to the classic media library and drag and dropped the image up there and instantly received the `[image]  exceeds the maximum upload size for this site` error message.

My hunch is other errors such as upload directory not existing, or not writable would produce the same result.

## Steps to Reproduce (for bugs)

1. Create image too big for upload
2. Try to upload the image in Gutenberg
3. No error message alerting

## Expected Behavior

Display an error message letting the user know the image is not uploading properly.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jorgefilipecosta** [comment]
Hi @mkaz, thank you for submitting this issue. It looks like it is very similar to https://github.com/WordPress/gutenberg/issues/3984. And there is already work in progress to fix it https://github.com/WordPress/gutenberg/pull/4203. I'm closing this one to avoid duplication.
