### ISSUE TITLE
Drop cap margin is too big

### ISSUE THREAD

**Issue by stompweb** [WordPress/gutenberg#5371]
## Issue Overview

When adding a drop cap the gap between the drop cap and the start of the text seems a little too big. I've had a look at a few examples across the web (Google Images!) and it all looks a bit tighter. I'm not sure if this is theme dependant but I've tried it with a few of the Twenty themes and it seems to produce the same result.

## Steps to Reproduce (for bugs)

1. Add a paragraph block
2. Turn drop caps on

## Possible Solution

I think it just needs tightening up a bit.

`margin: .07em .1em 0 0`;

on the drop cap seems to work quite well.

## Screenshots / Video

<img width="713" alt="screen shot 2018-03-03 at 14 19 30" src="https://user-images.githubusercontent.com/1017511/36935345-c715702a-1eee-11e8-929f-8c6f954b5742.png">

**Comment by karmatosed** [comment]
I think this is a subjective point. For now, I think this one is worth leaving as works. We need to be careful with margins like that on non-desktop devices too. We can review maybe later.
