### ISSUE TITLE
Site Editing > Navigation > Edit Nav > Manage submenus > hidden + button (UX)

### ISSUE THREAD

**Issue by Marc-pi** [WordPress/gutenberg#53727]
### Description

The submenus entries are not visible until you use the scroll down on the right
And you do not see the "+" button that permits to add other submenus

This is not natural and let user think he cannot add another child elements from the central zone, which is not true.

Seems zindex is not well managed. 
The child elements can be displayed out of the container with no disturbtion, to ease management.

ping @richtabor  / @getdave 

### Step-by-step reproduction instructions

- Just edit a menu that contains submenus
- you'll go to something like wp-admin/site-editor.php?postId={YOUR ID}&postType=wp_navigation&canvas=edit
- the + button is hidden by default

### Screenshots, screen recording, code snippet

Submenus are not visible (on front side those are)

![image](https://github.com/WordPress/gutenberg/assets/919332/8e5755b2-4c1f-4c43-816e-96facc0d2cf3)

The "+" button is hidden by default 

![image](https://github.com/WordPress/gutenberg/assets/919332/4d9c4a88-9d47-46d2-88c8-4e9ce391071f)

### Environment info

- WP 6.2/6.3 and lower
- TT3/TT3 but it is only an admin side issue

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Marc-pi** [comment]
also declared there https://github.com/WordPress/gutenberg/issues/53857

**Comment by getdave** [comment]
@draganescu I remember working on this and making the Navigation focus mode full height in order to avoid this situation. Do you know if we intentionally changed it back?

**Comment by draganescu** [comment]
I am not sure what's going on as for me the canvas is full height. Is this in trunk?

**Comment by getdave** [comment]
`WP 6.2/6.3 and lower` i believe. @Marc-pi are you using the Gutenberg _Plugin_ as well? Is it active?

@draganescu Possible missed backport?

**Comment by Marc-pi** [comment]
@getdave yes, i always do use it, and it is indeed active. Currently 16.4.0, aside with Woo / Woo Blocks and TT3/TT2 themes.

**Comment by getdave** [comment]
Here's a screenshot of my environment on `trunk` using Gutenberg Plugin. It's full height in preview mode.

<img width="1278" alt="Screenshot 2023-08-23 at 16 59 08" src="https://github.com/WordPress/gutenberg/assets/444434/e90e3285-35de-43ba-988b-56b94f3d0fc7">


Maybe this is a browser issue? Please could you post your environment setup including OS, Browser?

@draganescu @scruffian Are you able to replicate this at all?

**Comment by Marc-pi** [comment]
it is the same behavior on Chrome/ FF latest versions. i do not have the full height
My laptop has a 15' screen.

![image](https://github.com/WordPress/gutenberg/assets/919332/135e90a7-b76e-4c1e-9fa9-c0880acd1dc8)

**Comment by getdave** [comment]
> it is the same behavior on Chrome/ FF latest versions. i do not have the full height

You haven't provided your OS info, but I'm assuming from your screenshot that it's some variant of Windows?

**Comment by Marc-pi** [comment]
W10 yes

**Comment by getdave** [comment]
@Marc-pi I've tested this on 

- Windows 10
- Edge & Chrome (latest versions)
- Gutenberg 16.5.0 (note that is _newer_ than your version).
- TT2 Theme active
- I did _not_ activate any other Plugins. 

I cannot replicate the issue you describe. As you can see from the screenshots below both have full height as expected.

It would be useful if you are able to test this _without_ Plugins active. Ideally this would be done on a fresh install so as to rule out interference from another source.


## Chrome (116)

<img width="1291" alt="Screenshot 2023-08-25 at 09 10 06" src="https://github.com/WordPress/gutenberg/assets/444434/7699342d-d1f4-400b-8cbf-949c24eeb35a">
<img width="1303" alt="Screenshot 2023-08-25 at 09 10 14" src="https://github.com/WordPress/gutenberg/assets/444434/639f5e2b-b7e6-4287-b430-ea89efc6336f">

## Edge (115)

<img width="1300" alt="Screenshot 2023-08-25 at 09 10 57" src="https://github.com/WordPress/gutenberg/assets/444434/a014c06f-f3f3-4d6c-8b09-ef73217a3ff3">
<img width="1305" alt="Screenshot 2023-08-25 at 09 10 47" src="https://github.com/WordPress/gutenberg/assets/444434/31b3561c-7ed6-4140-bd1a-0de90d2991b4">

**Comment by Marc-pi** [comment]
I still have the issue with latest Gutenberg, with fresh install, and no plugin activated except gutenberg.
* the issue is about **the submenus not visible** when editing the Footer Template Part : you have to set for instance 5 submenus to see the issue.
* The page is full width, and has the right height, depending the content.
* But the submenus are hidden as explained in the first post of this thread : there is a zindex issue, the submenus are below the editable part.
* your footer height has to be thin to see the issue : the nav menu dropdown cannot show all child elements with clicked to open it. The child elements cannot overflow the border, so are not reachable, even the + button

as listed above, see also https://github.com/WordPress/gutenberg/issues/53857 that has a similar issue ("prevents the display of sub-menu items that extend past the limit of the cover block.").  An overflow hidden rule seems to explain that for that issue. Did not test for ours.

Here it prevents the submenus display that extends the limit of the footer pattern border limits.

**Comment by scruffian** [comment]
I believe that the issue is that the preview is inside an iframe, which means that it's not possible for the submenus to expand beyond it even if the z-index is increased.

Managing submenus is challenging because they don't always appear, which was one of the motivations for adding List View editing to the navigation block - so that at least you can edit them there. I appreciate this isn't ideal and I'd love to find ways of making direct editing in the navigation block easier, but simply increasing the z-index won't work here.

**Comment by draganescu** [comment]
@Marc-pi does #49339 capture the problem?

**Comment by Marc-pi** [comment]
@draganescu yep, same issue, you got it first :-)

**Comment by getdave** [comment]
> * your footer height has to be thin to see the issue : the nav menu dropdown cannot show all child elements with clicked to open it. The child elements cannot overflow the border, so are not reachable, even the + button

These more detailed instructions helped narrow down the issue. Glad we found the root cause. 

@draganescu do we need to close in favour of that canonical Issue?

**Comment by draganescu** [comment]
Yes. I'll update the other one with the finding in this one.
