### ISSUE TITLE
Target area for small blocks is too small

### ISSUE THREAD

**Issue by stompweb** [WordPress/gutenberg#5372]
## Issue Overview

When trying to edit a small paragraph block I noticed myself constantly adding new blocks instead of editing the one I wanted to. My hand-eye co-ordination is good and I don't have any impairments.

## Steps to Reproduce (for bugs)

1. Add a new paragraph block
2. Move your cursor away with the mouse
3. Try and edit the block you added in step 1

Latest Chrome. WordPress 4.9.4. Gutenberg 2.3.0

## Expected Behavior

It should be easy to both be able to distinguish the blocks and to click into them. 

## Current Behavior

I find it a little hard to distinguish where one block ends and one block starts and I have a hard time in always being able to edit the block I want rather than add a new one.

## Possible Solution

Give the blocks a border and/or a minimum height.

## Screenshots / Video

![accidental-new-block](https://user-images.githubusercontent.com/1017511/36935526-c038935c-1ef0-11e8-8094-5a4c174d5bac.gif)

**Comment by spencerfinnell** [comment]
Agreed. Very difficult to edit existing single-line paragraphs without creating extra blank paragraphs by accident.

**Comment by bordoni** [comment]
Should we change the margin or use another cursor to indicate when you are hovering the _Add new block_ part?

**Comment by youknowriad** [comment]
I think this is trying to address the same issue with #5396 let's consolidate there.
