### ISSUE TITLE
Oembeds blocks show when support not enabled

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#5373]
## Issue Overview

Oembed blocks even when oembed support is not enabled. We probably should not show blocks if the capability is not there, probably a low priority bug since most people probably didn't do what I did.

## Steps to Reproduce (for bugs)

1. Disable oembed because you wanted to slim down the download and didn't use any oembed stuff. A bit of code like in functions.php will disable oembed 

```
add_action( 'init', function() {
    remove_action('rest_api_init', 'wp_oembed_register_route');
   remove_filter('oembed_dataparse', 'wp_filter_oembed_result', 10);
    remove_action('wp_head', 'wp_oembed_add_discovery_links');
    remove_action('wp_head', 'wp_oembed_add_host_js');
}, PHP_INT_MAX - 1 );
```

2. Load Gutenberg, oembed blocks show, but obviously doesn't work.

Note: The obvious part of them not working is only obvious after the fact, you likely will forget that you disabled oembeds years ago.

## Expected Behavior

If functionality is not enabled, Gutenberg should not show those blocks as being available.

**Comment by draganescu** [comment]
A way to go about this would be to make the oembed block dynamic and then check with `has_filter` for the set of hooks that are removed (not sure if all of them need to be check or only some/one) and if we determine there is no support we simply don't register the block anymore.

There the question is other blocks have the same problem, where filters disable critical functionality. In that case maybe block.json could have some ... `depends`  list for things that should not be removed?

**Comment by paaljoachim** [comment]
@ntsekouras Nik I think you might want to know about this issue..:)

**Comment by ntsekouras** [comment]
If someone went all the way to disable them with code, shouldn't they just unregister the `embed` block with `unregisterBlockType`?

I think another solution other than @draganescu's to make it dynamic, would be to save an option with that information and retrieve from js then 🤔

**Comment by mkaz** [comment]
I'm going to close this issue, it was low priority and I agree with @ntsekouras assessment, if removing explicitly with code, makes sense to also unregister the blocks in code.
