### ISSUE TITLE
Gutenberg blocks lose formatting after moving site

### ISSUE THREAD

**Issue by mdordaa** [WordPress/gutenberg#53765]
### Description

**Actions that caused the problem**
1. Transferred a site from xampp dev to live server A using akeeba backup plugin.
2. Transferred a site from live server A to live server B using akeeba backup plugin.
3. Transferred a site from live server A to live server B manually.
4. Transferred a site from live server A to xampp dev using akeeba backup plugin.
5. Transferred a site from live server A to subdomain on the same server A using akeeba backup plugin.

**The Problem**
Frontend display issues
1. Navigation blocks lose their formatting
2. Cover block loses it formatting.
3. It appears that all content generated by plugins within blocks display correctly.
4. Problem appears to be with core WordPress blocks, but paragraphs, headings and lists are fine.

Blocks that have been noticed to lose their formatting include: navigation, cover and columns.

Issues with navigation block: li items display bullets, li items display block instead of flex, mobile toggle is displayed on desktop even when set to display on mobile, menu is not hiding under toggle on mobile, mobile toggle does not work. 

Issues with cover block: image not stretching horizontally, image not constrained vertically, nested blocks are displayed below, instead of over, the image. 

Issues with columns block: columns are not stacking on mobile

One of the affected sites is not connected to CDN, so CDN should not be the problem
The problem is not observed when creating the affected blocks on a fresh WordPress installation.
The problem is not observed with the twenty twenty one theme. 
The problem appears to happen with only the block themes. 

**Things I've tried**
1. Deactivated all plugins
2. Reinstalled WordPress from dashboard
3. Reinstalled WordPress manually
4. Changed theme
5. Reinstalled theme
6. Changed PHP version
7. Edited affected content and resaved
8. Created new content of the same block type
9. Repaired database with WordPress repair
10. Changed browsers
11. Cleared site caches
12. Cleared browser cache and cookies

**How to solve the problem**
Install Gutenberg plugin from the WordPress plugin repository and activate, and then clear all caches.
This is not a desirable solution as it introduces an unnecessary plugin into site, and this is a beta plugin. 

### Step-by-step reproduction instructions

1. Install a fresh copy of WordPress 6.3
2. Edit the pages template (or header or footer template part)
3. Create a navigation menu in header or footer
4. Add some items to the navigation menu
5. Create a new page
6. Create a cover block
7. Add an image that is 1024px x 768px
8. Add 2 buttons
9. Load the frontend and observe.
10. Move the site to a different domain (it can be a main domain or a subdomain, on the same or different server)
11. Load the frontend of the site
12. The navigation and cover blocks should lose their formatting
13. Install the Gutenberg plugin from the WordPress plugin repository and activate it
14. Clear all caches
15. Reload the frontend of the site
16. The navigation and cover blocks should now display correctly
17. Disable Gutenberg plugin
18. Clear all caches
19. Reload the frontend of the site
20. The affected blocks will be seen to lose their formatting again

### Screenshots, screen recording, code snippet

This is how the navigation block displayed **before** the site was moved
![How navigation menu should display_Gutenberg blocks display problem after moving site](https://github.com/WordPress/gutenberg/assets/65913939/7cfc30d3-edc0-4585-8390-8596dcefec3d)

This is how the navigation block displayed **after** the site was moved
![Wrong navigation menu display_Gutenberg blocks display problem after moving site](https://github.com/WordPress/gutenberg/assets/65913939/cc17986a-3b67-4abb-bc40-865e7e091acf)

This is how the cover block displayed **before** the site was moved
![How cover block should display_Gutenberg blocks display problem after moving site](https://github.com/WordPress/gutenberg/assets/65913939/121b0d9a-6bba-4d4d-af97-e379ea055c9c)

This is how the cover block displayed **after** the site was moved
![Wrong cover block display_Gutenberg blocks display problem after moving site](https://github.com/WordPress/gutenberg/assets/65913939/c96bfbe3-8532-4bb6-b1a6-6952dae8e714)

This is how heading, paragraph and list blocks displayed **before** and **after** the site was moved. They displayed correctly in both cases
![Headings, paragraphs and lists display correctly_Gutenberg blocks display problem after moving site](https://github.com/WordPress/gutenberg/assets/65913939/103e7fa3-229c-431e-bd79-c1be3043e682)

### Environment info

PHP 7.4 and 8.1
WP 6.3
Twenty twenty three theme
Twenty twenty two theme
Chrome browser
Edge browser
**Everything was updated to the latest version.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I can say anecdotally that I have had this happen with a site that was migrated/imported using WP Migrate. Navigation Block, Cover block, and Query loop didn't seem to be loading the default block styles.

<img width="1411" alt="Screenshot 2023-08-18 at 1 35 44 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/d4bf80aa-f6d3-40e6-b6bb-cfeb7238afad">
<img width="1335" alt="Screenshot 2023-08-18 at 1 35 58 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/61dc3cc8-18cc-4aeb-9d54-c6a1b2359da9">

**Comment by iamtakashi** [comment]
I've seen reports in the dotorg forums from users having display troubles with the navigation, the social icons, and the column block on the front of the sites.

**Comment by annezazu** [comment]
Moving this into the 6.3.x board for broader awareness and dropping into the Test team to see if we can get more reports. Thank you all!

**Comment by ironprogrammer** [comment]
@mdordaa and @jordesign, would you mind running a quick test?

In the migrated site's `wp-config.php`, try adding the following before the `/* That's all, stop editing! Happy publishing. */` line:
```php
define( 'WP_DEVELOPMENT_MODE', 'all' );
```

(This workaround/hunch is based on https://core.trac.wordpress.org/ticket/59111.)

**Comment by mdordaa** [comment]
@ironprogrammer
Yes, adding define( 'WP_DEVELOPMENT_MODE', 'all' ); to wp-config.php solves the problem.

**Comment by ironprogrammer** [comment]
Thanks for checking, @mdordaa! A similar report was opened before that one (https://core.trac.wordpress.org/ticket/59056), which closely aligns with this issue.

As this isn't an editor issue _per se_, I'd recommend this issue be closed, and to continue monitoring over in Trac. (This can of course be re-opened if that doesn't resolve it.) Personally, I feel this should be addressed in 6.3.1 or 6.3.2, and you're welcome to share your own experience and perspective on the Trac ticket as well.

**Comment by annezazu** [comment]
Let's do this and keep tracking for 6.3.1 or 6.3.2 in trac: https://core.trac.wordpress.org/ticket/59056

Thank you for connecting the dots here, @ironprogrammer !
