### ISSUE TITLE
Gutenberg feedback and issues

### ISSUE THREAD

**Issue by padraigobeirn** [WordPress/gutenberg#5377]
## Issue Overview
This is my first Github post so please accept my apologies if this is not the right place or if I'm not using Gutenberg properly. I'm testing Gutenberg 2.3.0 on a Windows 10 laptop with the latest version of Chrome. Here are the things that I'm having trouble with:

1. For me, the paragraph blocks are like taking a page of text and cutting it into ribbons. When I click on a paragraph the pop-up toolbar blocks me from reading some of my text. When I edit text I want to be able to view all of it, not have it blocked with pop-ups every time I click on a word. It gets in the way of my work flow. In my opinion there should be an option to dock the editor toolbar at the top. The toolbar popping up in the middle of the text every time I click on a word or paragraph is annoying and for me the classic editor is much less intrusive.

2. I cannot format two paragraphs or more at the same time like I can in the classic editor. In the classic editor I can select two short paragraphs and make them italic or bold, for example, very easily. I can't seem to be able to do that with Gutenberg unless I format each paragraph block individually which is more cumbersome. 

3. I cannot link to a larger version of an image in Gutenberg which is so easy to do in the classic editor. 

4. I can click and drag an image to position it quite easily in the classic editor. I can't seem to do this in Gutenberg. 

5. In the classic editor I can use Ctrl+X to cut an image from one paragraph and paste it easily in another paragraph. When I Ctrl+X an image in Gutenberg 2.3 it doesn't cut the image. Ctrl+X seems to work like Ctrl-C in Gutenberg.

**Comment by stompweb** [comment]
@padraigobeirn it is best to address each separate issue with it's own Github issue. That way individual issues can be discussed and addressed. 

Also, not sure you saw this when you added your issue but there's a template that you can follow which asks you to describe the issue, state what you expected to happen and state what actually happened. 

As well as that it's really useful to provide screenshots as this can help to remove an ambiguity.

Here is an example of one that I added recently demonstrating the above. https://github.com/WordPress/gutenberg/issues/5368

Hope that helps.

**Comment by mtias** [comment]
> In my opinion there should be an option to dock the editor toolbar at the top.

There is an option for that. Click on the top-right menu with the dots:

![image](https://user-images.githubusercontent.com/548849/36971664-d85436c6-206c-11e8-88da-d12aa957ec63.png)

**Comment by karmatosed** [comment]
Thanks for taking time to give feedback @padraigobeirn. I will note that as @stompweb advises, making an issue for each thing helps with responding. That said lets try and work through, then close this to have issues made.

> For me, the paragraph blocks are like taking a page of text and cutting it into ribbons. When I click on a paragraph the pop-up toolbar blocks me from reading some of my text. When I edit text I want to be able to view all of it, not have it blocked with pop-ups every time I click on a word. It gets in the way of my work flow. In my opinion there should be an option to dock the editor toolbar at the top. The toolbar popping up in the middle of the text every time I click on a word or paragraph is annoying and for me the classic editor is much less intrusive.

You probably want to add this as a thought to: #4780.

> I can click and drag an image to position it quite easily in the classic editor. I can't seem to do this in Gutenberg.

Drag and drop is coming. I would point out that image handling combined with nested blocks gives you far more powerful combinations than the classic editor.

> In the classic editor I can use Ctrl+X to cut an image from one paragraph and paste it easily in another paragraph. When I Ctrl+X an image in Gutenberg 2.3 it doesn't cut the image. Ctrl+X seems to work like Ctrl-C in Gutenberg.

Keyboard shortcuts are being worked on and I'd suggest making a ticket for this recommendation.

**Comment by padraigobeirn** [comment]
Thanks so much Stompweb, Matias and Tammie!  It's great to get your help, advice and comments. I will open up separate issues and add thoughts as advised. Docking the toolbar is a great improvement - I have a related issue to this which I'll open a separate ticket for. Thanks for your work on the project and I hope I can help you guys make it better with continued testing and feedback.

**Comment by mtias** [comment]
Thank you for the feedback!
