### ISSUE TITLE
Rename "Fonts Library" to "Font Library"

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#53778]
## What problem does this address?

The library's name originally was coined as singular form, i.e. "Font Library". Along the way, it changed to the plural form of "Fonts".

The plural form aligns well to font foundries like Google Fonts, Adobe Fonts, Bunny Fonts, etc.

The singular form aligns well to other WordPress-specific libraries and directories, such as:

- Block Library
- Pattern Library
- Media Library
- Photo Directory

Props to @ironprogrammer for raising the singular form relationship to the above list.

## What is your proposed solution?

Rename to use the singular form. Instead of "Fonts Library", rename to "Font Library".

Changes:
- The merged PHP backend files:
    - `lib/experimental/fonts/fonts-library` becomes `lib/experimental/fonts/font-library`.
    - `WP_Fonts_Library` becomes `WP_Font_Library` and its filename changes too.
    - `WP_REST_Fonts_Library_Controller` becomes `WP_REST_Font_Library_Controller` plus its filename.
   - and the associated tests.
- All open issues.
- Rename in frontend work https://github.com/WordPress/gutenberg/pull/53650.

Part of https://github.com/WordPress/gutenberg/issues/52698.

**Comment by hellofromtonya** [comment]
@matiasbenedetto do you agree with the rename?

**Comment by matiasbenedetto** [comment]
> @matiasbenedetto do you agree with the rename?

Yes, sounds good to me. :shipit:

**Comment by hellofromtonya** [comment]
Also noting @mikachan prefers the singular form too. Here's a quote from Sarah from a Slack discussion:

>I also prefer "Font Library"
