### ISSUE TITLE
Visual experience of block usage with the editor desperately needs improvement

### ISSUE THREAD

**Issue by David-Brown** [WordPress/gutenberg#5378]
## Issue Overview

Lack of visual specificity in block placement within the editor, and extremely limited ability to move a block that has been within the editor.
## Steps to Reproduce (for bugs)

1. Select any block within the editor that has already been placed.

## Expected Behavior

When selecting a block that has already been placed in the editor, I receive too minimal a visual cue as to what method I can move that block. A more detailed hover effect, even if only applying a border to the block being hovered on, would more clearly delineate the block that I need to move.

The action of using the arrows to the left of the block to move a block up or down is a clunky editing experience and is too limited in that I can only move the block up once or down once. 

## Current Behavior

I have to click on a block to select it. I have only the arrows on the left and the contextual menu dots on the right to mark which block I've selected. The arrows provide very limited functionality to move this up or down on the page.

## Possible Solution

An improved editing experience would be a clearer visual indication of the block that I'm selecting, even if only applied on hover. Also, a full drag-and-drop interface to move that block up or down within the editor is necessary for a cleaner editing experience. 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
Thanks for your feedback. One point I think we could do is increase the size of the arrows, but that's about as far as I would go on this right now. 

We do have drag and drop being planned and in light of this I will close up this issue because that is being worked on.
