### ISSUE TITLE
Can we make the list block transform smarter?

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#53794]
## What problem does this address?

I had a longer paragraph with items separated by a comma and wanted to turn it into a list.
I used the transform to list feature, and WP created one list item containing all the text.
Can we make it place each text on a separate list item inside the list block?

What can we use to make the block recognize this pattern compared to a regularly flowing text?
Maybe check the length between the commas? If each comma-separated text is only one word, place them on separate list items.

**Comment by ellatrix** [comment]
How do we know what your intention is? This is very tricky. If we do this I would make sure there's no other punctuation in the text, so it's just comma separated text and nothing more.
