### ISSUE TITLE
Custom HTML block: "An unknown error occurred." (2.3.0)

### ISSUE THREAD

**Issue by zakoops** [WordPress/gutenberg#5381]
## Issue Overview

Is it my WP installation that plays havoc with the Custom HTML block under version 2.3.0 of Gutenberg?

In essence, it's impossible to use Custom HTML blocks in the Visual Editor — these blocks showing message "An unknown error occurred."

Under same setup, Custom HTML blocks were OK up to version 2.2.0

Guess this is related to new syntax highlighting (Code mirror) in Custom HTML blocks...

## Steps to Reproduce (for bugs)

1. Create a new post
2. Verify that the Visual Editor is active
3. Insert a block of type Custom HTML

Tested with WP version 4.9.4 and Safari (11.0.3) and Chrome (64.0.3282.186)

Everything else in Gutenberg works ok.

## Expected Behavior

Should be able to edit the block contents, obviously...

## Current Behavior

Message "An unknown error occurred." stops any interaction.

## Possible Solution

Judging by error log shown by the Chrome inspector, some dependencies are not loaded correctly.

Same problem is noted on hosted site and on localhost.

## Screenshots / Video

I tried to maximize information in this screenshot:

![custom-html-error](https://user-images.githubusercontent.com/36708697/36939795-84cc3a34-1f05-11e8-80e7-1904ad9fc206.jpg)

## Related Issues and/or PRs

Don't know how this problem could be related to [issue #5374](https://github.com/WordPress/gutenberg/issues/5374).

**Comment by zakoops** [comment]
As additional information...

Firefox (58.0.2) offers maybe a more succinct and useful view of the problem I raised a few days ago:

![custom-html-error-2](https://user-images.githubusercontent.com/36708697/37041107-60266c24-2129-11e8-8456-b62179ae81f2.jpg)

The following message which appears in yellow in the screenshot essentially says in English: "Failed to load the <script> element whose source is...":

`Échec du chargement pour l’élément <script> dont la source est "http://.../wp-admin/load-scripts.php?load=wp-codemirror,code-editor,htmlhint,csslint,jshint".`

**Comment by youknowriad** [comment]
For some reason, your installation is not loading the wp-codemirror script. Maybe you have a plugin that disabled this script or something?

**Comment by zakoops** [comment]
@youknowriad 

Not sure the problem is settled...

- I deactivated and _even_ deleted all plugins in the installation
- and activated the _Twenty Seventeen_ theme

With this new _plain vanilla_ setup, the Gutenberg plugin has been installed anew and activated.

Still, the **Custom HTML** block shows the same error (‘An unknown error occurred’).

And I'm not alone here: please see [this page](https://wordpress.org/support/topic/latest-update-version-2-3-0-has-broken-some-blocks/) on the WordPress support forum...

**Comment by youknowriad** [comment]
Ok let's consolidate in #5374 as it's the same issue.
