### ISSUE TITLE
Navigation Block custom link URL text spacing formatting issue

### ISSUE THREAD

**Issue by VinodSoftcripts** [WordPress/gutenberg#53811]
### Description

The custom URL field is not functioning correctly. When we copy and paste text with spaces into the URL field, the text converts to URL-encoded '%20,' and the field does not allow us to backspace to remove the URL-encoded form of the space character. It continuously changes the space character into '%252' unless the '%' is removed."

### Step-by-step reproduction instructions

1. "Testing Link" copy paste into navigation custom link URL field.
2. The pasted text will convert to this `Testing%20Link`.
3. Now try to backspace the text, it will not allow to remove the text and keeps showing `%252`.

### Screenshots, screen recording, code snippet

https://capture.dropbox.com/Widr4GP81TXpBPc0
https://capture.dropbox.com/bbAGC8v8MsInXYFZ

Screen recording : https://capture.dropbox.com/vfb9BjrtXJs5XmB8

### Environment info

- Wordpress 6.3 and Active theme "Twenty Twenty-Three (twentytwentythree)"
- Chrome
- MacBook Air with MacOS Monterey

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jorgefilipecosta** [comment]
Hi @VinodSoftcripts,
Thank you for reporting this issue.
I was able to replicate the bug. As the content is urlencoded trying to delete something after the % character always ends up adding another character. I guess the field needs to have a local state with the unencoded version and the URL encoding should only happen when the field loses focus.

**Comment by getdave** [comment]
I'm not longer able to reproduce this and believe it's been fixed.
