### ISSUE TITLE
Site Editor > Patterns: Empty template parts use the text "Empty pattern" in the placeholder

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#53821]
### Description

This is a small inconsistency, but if you create a custom template part that is empty, and then go to 
Admin > Editor > Patterns > Template parts, then the preview to the right of the menu is empty but has the wrong text. It says pattern instead of template part.

### Step-by-step reproduction instructions

Create a custom empty template part through the interface
Go to Admin > Editor > Patterns > Template parts. Select the area used for the part, for example, General.
Confirm that the preview is empty, which is correct, but that the text says "Empty pattern"

### Screenshots, screen recording, code snippet

<img width="1507" alt="the template part screen in the Site Editor with previews of all available template parts in the general template part area" src="https://github.com/WordPress/gutenberg/assets/7422055/efa7d39d-8240-4292-a2ec-7fe6a533df05">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
I can confirm this in testing - it also refers to the pattern within the Template Part details screen.

<img width="340" alt="Screenshot 2023-08-30 at 10 24 50 am" src="https://github.com/WordPress/gutenberg/assets/1842363/e446ce82-bb23-4f68-b5a7-463a02ac3b7a">

**Comment by aaronrobertshaw** [comment]
Thanks for the confirmation @jordesign and flagging the additional label. 

A fix for both is up in https://github.com/WordPress/gutenberg/pull/53842. A quick sanity check and reapproval might be good given I've updated that PR to tweak the extra label since the original green light.
