### ISSUE TITLE
Blocks inside Query loop in Taxonomy page doesn't have settings and styles tab 

### ISSUE THREAD

**Issue by tnchuntic** [WordPress/gutenberg#53836]
### Description

Blocks inside Query loop in Taxonomy page doesn't have settings and styles tab.

I was expecting to have theme both because its just a normal query loop on a taxonomy template, but it doesn't have any settings and styles tab at all.

### Step-by-step reproduction instructions

1. Go to Editor > Templates
2. Create template for Custom Taxonomy (e.g. role / location) > All role/location.
3. Add Query loop use default pattern/template (e.g. feature image, title, read more)
4. Click any of the blocks under/child of the Post Template block
5. e.g. click "Feature Image" block and check the right panel where you can see the block settings it doesn't show the "Settings & Styles tabs". Any blocks inside the Post Template blocks doesn't have "Settings & Styles Tabs".

### Screenshots, screen recording, code snippet

Editor screenshot:
https://snipboard.io/9cmNjO.jpg

### Environment info

- WP 6.3
- Gutenberg 16.4.0
- PHP 8.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tnchuntic** [comment]
**Found solution of the issue.** 
The issue is cause by Query loop "POST TYPE" which is default to POST(if POST is empty issue will occur) and when you set it to "Inherit query from template" it will not override the "POST TYPE" in the Editor. It cause the innerblocks to not able to function properly to display the blocks settings and styles tab.

**Solution:**
Setting the Query Loop "POST TYPE" to PAGE before switching it to "Inherit query from template" ensures that the query loop will get an initial post data from page for the innerblocks to use and will force the blocks to work properly.
https://snipboard.io/cz4oZs.jpg
https://snipboard.io/KLxO7C.jpg

**Comment by ntsekouras** [comment]
Hey @tnchuntic! I tested by creating templates for custom taxonomies and couldn't reproduce this.. Everything was working as expected. Is this still an issue? If yes, can you share a small video of it?

**Comment by ntsekouras** [comment]
I'll close this one since it couldn't be reproduced and no further feedback was provided. Feel free to reopen if it's still present, but with some small video or different reproduction steps in order to be tested. Thanks!
