### ISSUE TITLE
Social Icons are not visible

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#53834]
### Description

Social icons:
They look ok in the editor but they are not visible on the frontend (public pages).
The HTML markup of the social icons is there but the icons are not visible on the frontend.

### Step-by-step reproduction instructions

1. Create a new site
2. Go to the editor to edit the header template part.
4. Add a social icon component with a few icons with links and save.
5. Navigate the frontend page.
6. Check that the social icons are not visible in the frontend.

### Screenshots, screen recording, code snippet

Editor:
![image](https://github.com/WordPress/gutenberg/assets/1310626/2eba1521-a4b7-4d67-9534-1c98b6b24bca)

Frontend:
![image](https://github.com/WordPress/gutenberg/assets/1310626/c49aee76-4278-431f-a12a-e58c73225698)

A screencast creating a brand new instance of WordPress 6.3:
https://github.com/WordPress/gutenberg/assets/1310626/80a50f80-6910-47df-b939-66204e411e1a

### Environment info

- WordPress 6.3 with and without Gutenberg 16.4.0 activated.
- Themes TT3, TT2, and other block themes.

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
Thanks for the report.

From my testing, both the social icons added to the header template and the social icons added to the navigation are displayed correctly.

![social-link](https://github.com/WordPress/gutenberg/assets/54422211/49ee47fb-107b-4580-818d-d8c9d70a0ae9)

> The HTML markup of the social icons is there but the icons are not visible on the frontend.

Is there any custom CSS or plugin that hides the icons?

**Comment by matiasbenedetto** [comment]
I'm sharing a screencast featuring the problem using a brand new WordPress 6.3 instance:

https://github.com/WordPress/gutenberg/assets/1310626/80a50f80-6910-47df-b939-66204e411e1a

**Comment by t-hamano** [comment]
I also use InstaWP and would have followed the exact same procedure, but strangely I can't reproduce it 🤔

https://github.com/WordPress/gutenberg/assets/54422211/109c7e2d-d6d2-4437-b1da-97ef6e747c89

**Comment by t-hamano** [comment]
I would appreciate it if you could confirm the following

- Are there any extensions in your browser that are affecting the site?
- Does it reproduce in other browsers?

**Comment by matiasbenedetto** [comment]
The icons render as expected after disabling "AdBlock Plus" browser extension.
Thanks @t-hamano.
Sorry for the false alarm  :sweat_smile: . I'm closing the issue.
