### ISSUE TITLE
Would it be possible to add Unique ID on front-end block display?

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#5384]
Hi,

I think it would be better for each blocks to have unique ID when displayed on front-end. It's better than us developers adding custom classes each in order to target the block. Let me know your thoughts.

Cheers,
Jeffrey

**Comment by travislopes** [comment]
Agreed. The block render callback should be passed the block ID and the block index (as reusable blocks share the same block ID).

**Comment by bordoni** [comment]
Should this block ID be truly unique for each instance of the Editor? Or like @travislopes suggested saved blocks would share the same ID, with different indexes? 

I really like the idea of the Indexes, would help immensely with styling and classes for first-child, last-child or even-odd behavior for example.

**Comment by travislopes** [comment]
@bordoni Blocks already get a unique ID upon creation.

**Comment by phpbits** [comment]
@bordoni on the editor you can use `data-block` to target specific block but yes they should have specific targeting too because some were wrapped on separate div elements. Front-end should have unique ID too for styling purposes.

**Comment by youknowriad** [comment]
If you want to target block by IDs you can enable anchor support https://wordpress.org/gutenberg/handbook/block-api/#supports-optional and specify and ID. By default this is only active for the heading block though.

**Comment by AdsonCicilioti** [comment]
But how to get the generated unique id of Blocks (Non Anchor)?

I don't need/want for a manual solution.

**Comment by Davesjoshin** [comment]
Is there a way to get that unique ID that WordPress generates in PHP?

**Comment by danieliser** [comment]
@youknowriad - That isn't a proper solution. Please reopen one of these 2 related issues.

There is still no reliable way to get a blocks unique ID from the editor in the frontend during render_block.

Since they have unique Ids in editor already, simply address this by passing that ID to the parsed block array.

This needs to be reopened, it was never completed or addressed.

**Comment by DeoThemes** [comment]
+1 for ID to be passed into a render callback
