### ISSUE TITLE
Sync status is not getting wrapped in translations

### ISSUE THREAD

**Issue by MatzeKitt** [WordPress/gutenberg#53865]
### Description

The "Sync status" in the sidebar of a synced pattern won’t be wrapped if it’s translated with a larger word, as we did it in German, where it translates to "Synchronisierungsstatus".

### Step-by-step reproduction instructions

1. Use German or German Formal language
2. Go to `/wp-admin/edit.php?post_type=wp_block`
3. Create a new synced pattern
4. Look at the sync status

### Screenshots, screen recording, code snippet

![Bildschirmfoto 2023-08-22 um 09 21 30](https://github.com/WordPress/gutenberg/assets/1018979/a1e28a6c-494b-4062-8cee-f67100683e54)

### Environment info

– WordPress 6.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report. This issue has been resolved in #53243 and will be included in WordPress 6.3.2.
