### ISSUE TITLE
Search Block: automatically triggering search 

### ISSUE THREAD

**Issue by tnchuntic** [WordPress/gutenberg#53860]
### Description

Expected to be able to click the search button icon without triggering the actual search.

Currently when the search field has a text on it even if the field is hidden and you click the icon search it will automatically search. It will not allow you to edit or fill-up the search field with a new search keyword.

### Step-by-step reproduction instructions

1. Edit any template
2. Add search block on navigation
3. Select button only and select icon display
4. Save all changes
5. Click the search icon
6. Fill-up the search field with the keyword you wanted to search
7. Click the search icon to trigger the search.
8. Repeat step 5 (in the search result page, where the search field have been filled-up with the previous search.). This will trigger unwanted behavior which opens up the search field and automatically trigger the search.

Supposedly it should show me the search field and allow me to change the search keywords.

### Screenshots, screen recording, code snippet

n/a not able to do screenshot because its even driven issue.

### Environment info

- WordPress 6.3, Gutenberg 16.4.0
- Chrome Version 116.0.5845.96

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@tnchuntic Thanks so much for reporting this. I wasn't able to replicate this behavior where it was automatically searching. Perhaps I'm missing something though. Here's a video with 6.3.1:

https://github.com/WordPress/gutenberg/assets/26996883/c6729bd4-ca98-4499-8909-8580c1d7793d

Can you share more info?

**Comment by jordesign** [comment]
Hey @tnchuntic - Just checking back on this to see if you can still recreate it in WP 6.3 and if you can share any further details?

**Comment by jordesign** [comment]
With no further confirmation of this issue - and 2 major releases since this report I'm going to close it. @tnchuntic  if you can still recreate this in WP 6.4 - please feel free to request the issue be re-opened.
