### ISSUE TITLE
Font Library: Add a disclaimer/notice saying the fonts will be downloaded from third-party sources.

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#53882]
## What ?
In the Font Library, the users will be able to download font families from different font collections provided by core or extenders (plugins for example).

Should we add a disclaimer/notice to let the user know the fonts will be downloaded from third-party sites such as Google fonts CDN?

If we should add this notice, we would need a design to implement it into the Font Library frontend.

## Context
As a reminder:

- Font library will display one or more font collections
- These font collections will present several fonts available to be installed.
- When the fonts are installed the fonts will be downloaded from the third-party source into `/wp-content/uploads/fonts` folder and after that, served from it as any other site static asset.

## Tracking issue
https://github.com/WordPress/gutenberg/issues/53307

**Comment by matiasbenedetto** [comment]
@jasmussen what do you think of this? what could be a good UI/UX to implement this notice?

**Comment by jasmussen** [comment]
I definitely think it's a good idea. The existing mockups from #45271 have such a notice:

<img width="4800" alt="Add fonts from Google, option 1" src="https://github.com/WordPress/gutenberg/assets/1204802/0c3bb21b-3b0b-4044-b597-4491d49c9915">

For legibility, those mockups say:

> Add from Google Fonts. Fonts are copied to, and served, from your own server.

If we need to, we can highlight that more:

<img width="4800" alt="Add fonts from Google, option 2" src="https://github.com/WordPress/gutenberg/assets/1204802/7efb85fe-abe5-44ef-acf6-a9a5eaa15619">

**Comment by priethor** [comment]
As far as I understand, after talking with @mikachan and @ironprogrammer, there will be a connection to third parties as soon users browse and preview the fonts before downloading them. If so, we should probably adapt the notice to clarify that fact, maybe even before showing the list of fonts?

**Comment by jasmussen** [comment]
How's this?

The flow is as usual, you click to add fonts, it opens the modal, though the tab is now called "Install Fonts". But now, the first time you visit a big consent box in the middle, where first you have to allow the connection. 

<img width="6320" alt="Add fonts from Google, option 3" src="https://github.com/WordPress/gutenberg/assets/1204802/438b5f6f-57cf-4773-998e-d9372f5ee5db">

**Comment by priethor** [comment]
Looks amazing, thanks Joen! That should help dissipate any concerns about connecting to third parties without prior notice.

@matiasbenedetto, is there also a filter to disable online fonts entirely? I'm happy to create an issue for it 🙂

**Comment by matiasbenedetto** [comment]
> @matiasbenedetto, is there also a filter to disable online fonts entirely?

If you don't accept the disclaimer you won't make any request for online fonts, so I'm not sure what you mean.

**Comment by priethor** [comment]
It would be good to have a way to completely turn off online fonts so that the tab with the disclaimer doesn't show at all and users can only upload fonts manually.

**Comment by pbking** [comment]
Complete in #54566
