### ISSUE TITLE
Content Block: update block name in placeholder content

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#53894]
### Description

The placeholder text that shows up for the block when editing a template still uses "Post Content Block" as the name

### Step-by-step reproduction instructions

1. Add a Content Block
2. Look into the placeholder text

### Screenshots, screen recording, code snippet

![CleanShot 2023-08-23 at 15 57 14@2x](https://github.com/WordPress/gutenberg/assets/14153300/9ab34580-a789-4638-9b39-95134e5ce512)

### Environment info

- WordPress 6.3, GB 16.5 RC1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Just tested with WP 6.3 and GB 16.5 and can confirm this is in place

**Comment by jordesign** [comment]
Closing this as a fix is merged in https://github.com/WordPress/gutenberg/pull/53902
