### ISSUE TITLE
Flow for creating lists from text

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#539]
Idea discussed with @jasmussen.

![image](https://cloud.githubusercontent.com/assets/548849/25528278/4af4944a-2c1d-11e7-9832-89a7a0c95bf3.png)

If you select text across multiple lines, a contextual "make a list out of these" button could appear next to the block switcher.

Clicking it would create a new list block with those items.

<a href="https://github.com/WordPress/gutenberg/issues/539#issuecomment-298613026">See comments for a mockup of how this could work</a>.

**Comment by jasmussen** [comment]
To elaborate a bit, this might be particularly interesting in combination with the multi paragraph text block, #447. In this case, selecting items inside such a block and clicking the list block would "split the block".

**Comment by jasmussen** [comment]
Here are two flow mockups for this. 

Version 1: the list buttons are always visible:

![version 1](https://cloud.githubusercontent.com/assets/1204802/25610368/44b57f00-2f23-11e7-8b57-1a3d07c5a044.png)

Version 2: the list buttons are visible only when you've selected across lines:

![version 2](https://cloud.githubusercontent.com/assets/1204802/25610420/6787ab52-2f23-11e7-935a-7c44a0a14fc1.png)

In version 2, would we miss the inline formatting buttons?

**Comment by mtias** [comment]
I think these transformations should appear on the block switcher because I expect creating a list to split it into a separate block.

**Comment by jasmussen** [comment]
Chatted with Matías and we came up with this:

![make a list](https://cloud.githubusercontent.com/assets/1204802/25616541/b15d181a-2f3d-11e7-89e2-156fe7a11be1.png)

In this flow, the left most list and quote buttons show up _only_ when you select multiple lines, and they show up in the spot where the block switcher sits.

**Comment by EphoxJames** [comment]
If the list has indents what should the conversion from list to paragraph do?

**Comment by jasmussen** [comment]
Probably okay to remove the indentation in the conversion then. We can always revisit if we find that too destructive.

**Comment by iseulde** [comment]
@jasmussen @mtias Is this still relevant?

**Comment by jasmussen** [comment]
> Is this still relevant?

It is on a meta level. 

I think we have many many aspects right with the editor in its current state. But one of the aspects I still think needs a little polish is cross-text-block actions like list or quote making. It might have to be punted, but I think it's worth keeping this open.

**Comment by mtias** [comment]
@iseulde we need to review transformations in general, both UI and technically. This falls under that. I feel it should be more contextual (if you select multiple lines you get option to create list, otherwise you don't).

**Comment by iseulde** [comment]
@matias So if you select multiple paragraphs, there should be a list option? Sounds like #1811 is a good start for that.

**Comment by jasmussen** [comment]
Here's a new mockup:

![multi-select list making](https://user-images.githubusercontent.com/1204802/28964538-763194ae-790d-11e7-9c40-5644b2046bd6.png)

In this situation, you get a new quick toolbar, one which works across blocks. @iseulde what do you think?

**Comment by iseulde** [comment]
@jasmussen I thought we were going for the blue toolbar on top?

**Comment by jasmussen** [comment]
I still like that blue toolbar, it's an option. If it's easier to implement like that, it's okay. 

The mockup tries a quick toolbar instead, as it adds actions related to formatting.

**Comment by iseulde** [comment]
Yes, I initially made it like this. I think we removed it because of the sticky toolbar problem (would be limited to the first block). Not sure how to solve that problem.

**Comment by jasmussen** [comment]
> Yes, I initially made it like this. I think we removed it because of the sticky toolbar problem (would be limited to the first block). Not sure how to solve that problem.

If it's easier to do in the blue toolbar for now, totally fine, especially since we're pondering a fixed toolbar in https://github.com/WordPress/gutenberg/pull/2148. 

Doing a little inspector surgery, if we can move the block controls to be a child of this div, then it can scroll across the blocks:

![screen shot 2017-08-04 at 17 18 26](https://user-images.githubusercontent.com/1204802/28975074-fd7479d8-7938-11e7-8338-182d3907b32e.png)

But if that's super complicated, totally fine to use the blue one.

**Comment by iseulde** [comment]
@jasmussen Don't think that's true. It would scroll over all the blocks and to get fixed anywhere but the top and bottom.

**Comment by iseulde** [comment]
We can wrap selected blocks in a div (easy with React I guess), but then all iframes will reload every time you multi select them.

**Comment by jasmussen** [comment]
Sounds like we should try putting the buttons in the blue bar for starters, seeing if it's actually a good flow. Then we can iterate from there.

**Comment by fisicx** [comment]
So how do I highlight a group of paragraph blocks? I 've tried using a mouse and keyboard and I can only ever select one block. Gutenburg just won't left me select more than one. I've been putting the cursor to the left of a character, holding shift and using the arrow keys to find the last point for so long (since before WordPerfect 5.1) it was odd to suddenly not be able to do so.

If I can't select multiple blocks then I can't convert them into a list.

**Comment by iseulde** [comment]
@fisicx Does this work for you in the last version, 1.8.1?

**Comment by jasmussen** [comment]
Although the flow can still be polished further, recent advancements in selecting across blocks and the addition of cross-block transformations, I'm going to close this one as addressed.
