### ISSUE TITLE
Navigation Link: Prioritize pages in the Link Control suggestions

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#53904]
## What problem does this address?
When I insert a new Navigation Link block I am most likely trying to add a page to my navigation. At the moment the list of suggestions in Link Control is sorted by most recently edited, I believe:
<img width="619" alt="Screenshot 2023-08-24 at 10 19 55" src="https://github.com/WordPress/gutenberg/assets/275961/8076f8b6-f9f9-4aa6-8361-32780814fbbd">

## What is your proposed solution?
Instead we should prioritize pages in this list, and only show other content if no pages match the query. I tried this in https://github.com/WordPress/gutenberg/pull/53903, but ran into some problems.

**Comment by draganescu** [comment]
Informed by #50432

- show only pages in the default suggestion list
  - ideally try a scrollable tree of pages reflecting the page hierarchy - but this is not clear yet (e.g. what if there are hundreds of pages).
  - we can start with just listing pages ordered by last modified desc
- when a user searches search in everything that is supported, but prioritise pages if the match is in the title
