### ISSUE TITLE
Site Editor: Top Toolbar 'Add New Template' missing for mobile

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/gutenberg#53927]
### Description

There is no means to Add a New Template in the Site Editor for small screens. I discovered this while debugging https://github.com/WordPress/gutenberg/issues/49772

### Step-by-step reproduction instructions

1. Launch the Site Editor by visiting Appearance > Editor
2. Click 'Templates' to view available templates
3. Note the missing + icon where you would click to 'Add New Template' on mobile, which should appear next to the top heading of 'Templates'

### Screenshots, screen recording, code snippet

| desktop | mobile |
|---------|------------|
|  <img width="1121" alt="Screenshot 2023-08-24 at 2 32 08 PM" src="https://github.com/WordPress/gutenberg/assets/405912/40ce5eae-542b-49eb-b007-8d6ea5b50ff2"> |  <img width="354" alt="Screenshot 2023-08-24 at 2 32 21 PM" src="https://github.com/WordPress/gutenberg/assets/405912/6766c3d8-1483-46b7-9c94-b36e4864ec0e"> |

### Environment info

- WordPress 6.3 / TT3 theme
- Gutenberg Trunk _only_ activated
- Any screensize under 400 (for what I tested) using Chrome Dev Tools and Toggle Device Toolbar

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by colorful-tones** [comment]
I believe the code where this is happening is: https://github.com/WordPress/gutenberg/blob/7282cf6d479a647c3531e1d9c66f708a0efee7f8/packages/edit-site/src/components/sidebar-navigation-screen-templates/index.js#L47-L61

**Comment by t-hamano** [comment]
I think this issue is related to #49769.

**Comment by colorful-tones** [comment]
@t-hamano thanks for the duplicate note. I agree, but [I made a note for Anne to update her original Issue notes](https://github.com/WordPress/gutenberg/issues/49769#issuecomment-1695562160), because there is nothing that references or notes that the Add a New Template button is missing. It is on the same screen that is being reported in Anne's Issue, but in a different spot and could easily be missed when that Issue is addressed. Once she updates with that note then I'll be sure to close this out. Thanks!
