### ISSUE TITLE
Block Editor: "Move to" action doesn't work

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#53920]
### Description

When "Move to" is selected from the block toolbar, a thick border appears over the block and the block cannot be moved. I can't immediately recall what the original UI was like, but at least the current behavior must not be what was intended.

### Step-by-step reproduction instructions

- Add multiple blocks.
- Select "Move to" from the toolbar of any block.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/795bc5fc-0428-4855-8279-2cdde2043596

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@annezazu 

This issue can be reproduced in WordPress 6.3 and added to the 6.3.x Editor Task as I consider it a basic and important action.

**Comment by bangank36** [comment]
I think you need to press `Enter` key to proceed the moving? Tested on trunk, steps can be found on https://github.com/WordPress/gutenberg/pull/22453#issue-620659885
![Kapture 2023-08-25 at 10 15 49](https://github.com/WordPress/gutenberg/assets/10071857/dfa3350b-e94a-4421-80c2-f9e8e5abc154)
