### ISSUE TITLE
Updating existing content to Gutenberg doesn't honor existing attributes

### ISSUE THREAD

**Issue by caraya** [WordPress/gutenberg#5392]
## Steps to Reproduce (for bugs)

1.  Open an old post (I use markdown and fenced code blocks with `language-<name>` to indicate the language Prism should use for highlight in my content). Prism is configured as a plugin and works correctly  before opening the post in Gutenberg
2. Convert the classic block containing the post into blocks
3. The code block has a fixed default value `wp-block-code` for the class attribute
4. If I try to add a class attribute manually I get a validation error in Chrome dev tools
5. I have to manually add the class from the editor for every individual code block

Browsers tested with: Firefox Nightly (60.0a1 / 2/28/18), Chrome (64.0.3282) on MacOS
Gutenberg: 2.3.0 compiled from source on 3/3

## Expected Behavior

If there is an existing class for an element that gets converted to a block, that class should be honored when converting the element to a block. I don't think this is related to Automattic/jetpack#7786 as the content has already been rendered and saved to the database before being opened in Gutenberg and the code displays properly before the conversion

## Current Behavior

Code blocks lose the language- attribute and the code highlight. 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
> If I try to add a class attribute manually I get a validation error in Chrome dev tools

You can use the block inspector to add your className to avoid having these errors.

**Comment by caraya** [comment]
that's not the point, the old post already has a class to indicate the type of language I want to highlight. I shouldn't have to add it again just because Gutenberg doesn't see it or doesn't honor it

**Comment by youknowriad** [comment]
I understand that the converting mechanism should be able to add this extra className if detect, I just wanted to help with a workaround for now.

Also, the converting mechanism is not done automatically on purpose. Because there's no way to guarantee no data loss. That's why you have to do it on your own if it's not the result you hoped for you can still undo and continue using the classic block.

**Comment by youknowriad** [comment]
cc @iseulde @mcsf

**Comment by caraya** [comment]
If you use the classic or HTML blocks you lose a lot of the Gutenberg functionality. That's fine with me, I write a lot of HTML in my posts already, but it may not be for everyone upgrading content.

**Comment by iseulde** [comment]
@caraya Could you provide the HTML for us to test and make a PR with?

**Comment by caraya** [comment]
I've attached a simplified version. Github doesn't let me attach html directly so I had to zip it. 


[post.html.zip](https://github.com/WordPress/gutenberg/files/1965493/post.html.zip)

**Comment by caraya** [comment]
I thought I had done this already, I've attached a file with the markdown doc and the converted HTML
[Archive.zip](https://github.com/WordPress/gutenberg/files/2007048/Archive.zip)

**Comment by danielbachhuber** [comment]
> I understand that the converting mechanism should be able to add this extra className if detect, I just wanted to help with a workaround for now.

This was handled with #7538
