### ISSUE TITLE
LinkControl is accepting the wrong urls

### ISSUE THREAD

**Issue by abhi3315** [WordPress/gutenberg#53938]
### Description

The LinkControl block is currently accepting an incorrect URL.

Example:
`xhttps://example.com`
`hpps://example.com`
`pps://example.com`
`://example.com`
`example`

### Step-by-step reproduction instructions

1. Open the post editor
2. Select text
3. Click on the link button from the toolbar
4. Enter the invalid URLs 
5. Save the URL

### Screenshots, screen recording, code snippet

![LinkControl](https://github.com/WordPress/gutenberg/assets/43412958/ca93c15d-08db-4fa2-bc9e-8810bd783678)

### Environment info

- **WordPress** 6.4-alpha-56267-src
- **Browser** Chrome Version 115.0.5790.170 (Official Build) (arm64)
- **Theme** TwentyTwentyThree
- **Device** MBP 14" M1 Pro

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi,

Thanks for reporting; 
This has been reported in  https://github.com/WordPress/gutenberg/issues/47414. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
