### ISSUE TITLE
Permalinks: How to remove the trailing slash?

### ISSUE THREAD

**Issue by kocjs** [WordPress/gutenberg#53937]
Hello everyone, I'm seeking guidance and would appreciate your help. I'm unsure if this is the appropriate forum to ask my question, so if it isn't, kindly re-direct me to the proper place. 

I have realized that my link structure has not been consistent over the years. Lately, I've noticed that some visitors reach my site through links that do not include a trailing slash at the end. After conducting research on this topic, I couldn't find clear instructions. I came across several SEO articles (like this [one](https://ahrefs.com/blog/trailing-slash/) and this [one](https://permalinkmanager.pro/docs/plugin-settings/how-to-add-remove-trailing-slashes/)), suggesting that both options are acceptable. However, it is crucial to maintain a consistent link structure because search engines, such as Google, treat them differently.

I made a change to my permalink structure by removing the trailing slash at the end of the link. Instead of using the format `https://example.com/sample-post/`, I have switched to `https://example.com/%postname%`. I followed the instructions provided in the customize permalink [documentation](https://wordpress.org/documentation/article/customize-permalinks/).

I have successfully implemented a 301 redirect in my .htaccess file based on instructions I found online. However, I recently discovered that my redirection method breaks the functionality of the REST API, which is essential for utilizing a popular [redirection](https://wordpress.org/plugins/redirection/) plugin. Fortunately, the plugin developer has published a reliable set of redirection [rules](https://redirection.me/support/problems/rest-api/) that address this issue.

```
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteCond %{REQUEST_METHOD} GET 
RewriteCond %{REQUEST_URI} !^/wp-json/.* 
RewriteRule ^(.*)/$ /$1 [R=301,L]
```

However, upon reaching out [him](https://wordpress.org/support/topic/permalink-128/#post-16998876), he mentioned that WordPress might be able to handle this redirect automatically. I have attempted to research this further, but unfortunately, I haven't been able to find a definitive answer.

I would appreciate clarification **on whether WordPress automatically redirects visitors using this** `https://example.com/%postname%` **permalink structure, or if it is necessary  set up the 301 redirect in the .htaccess file**. My goal is to avoid any conflicts that may arise when multiple redirects are in place.

I understand the importance of updating internal links to align with the new permalink structure. Considering that my initial 301 redirect caused issues with accessing the REST API, **I would like to know if there are any other files or folders** that should be excluded.

Thank you in advance for your assistance and guidance. Your insights are greatly appreciated!

**Comment by jordesign** [comment]
Hey @kocjs  - as the permalink system is part of WordPress core, and not specifically part of Gutenberg - this probably isn't exactly the right place.

I'd recommend asking for advice on something like that in the Support Forums
https://wordpress.org/support/forums/

And if it is something you consider a bug (or a feature request) you can report it in the Core bug tracking system
https://core.trac.wordpress.org/
