### ISSUE TITLE
Add optional character count prop to RichText

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#5394]
This is a low priority thing, which if it happens in the future, would be nice.

We recently discussed the Cover Image block, and what happens to it if you write more text than can fit in the block. As part of that, the idea of limiting an input field to `n` characters was brought up. 

Here's how that could look:

![character-count](https://user-images.githubusercontent.com/1204802/36962871-82ea131a-2051-11e8-849a-60fc90e8515e.png)

☝️  that's a hypothetical "Status Update" block, which has a character limit of 280. When you are writing inside this block, the block expands vertically to show a little counter in the bottom right.

**Comment by StaggerLeee** [comment]
It could be useful for all widgets now as blocks. Developers want to limit amount of text beginners add there and prevent ruining layout.
As custom filter, not default.

**Comment by jasmussen** [comment]
Filed in Ideas, and closing for now. We should revisit when we revisit ideas :)
