### ISSUE TITLE
Cannot update the Author in Gutenberg

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/gutenberg#5395]
Hello,
When I publish my entry, after I would like to update the author. I change the select, but it does not save the new author.

I've tested in last version Gutenberg 2.3.

**Comment by Soean** [comment]
I tested the issue and can reproduce this bug.

**Comment by bobbingwide** [comment]
See https://github.com/WordPress/gutenberg/issues/5072#issuecomment-368866393
I was going to raise a separate issue, but believe this issue will suffice.

**Comment by leahkoerper** [comment]
I recreated this as well- it appears to save fine but the new author doesn't stick when I go back and view my Posts table.

**Comment by gziolo** [comment]
It should be fixed with #5438 and released as part of 2.4. Can you confirm if it works as expected?
