### ISSUE TITLE
Unable to add Video to Cover Block

### ISSUE THREAD

**Issue by wynwin** [WordPress/gutenberg#53956]
### Description

When attempting to insert a video into the Cover Block, the video does not display and appears as a blank space both in the editor and black/empty space on the frontend. 

This issue occurs consistently and prevents users from effectively incorporating videos into their content using the Cover Block. The result is consistently a non-functional display.

Other types of media, such as images, seem to load without any problem in the Cover Block. The problem specifically pertains to videos. 

### Step-by-step reproduction instructions

1. Create a new post/page or open an existing one.
2. Add a new block and select the Cover Block.
3. Click on the "Select Media" > "Media Library" in Cover Block settings.
4. Choose the "Video" option and upload/select a video file.
5. Observe that the video space remains blank both in the editor and on the frontend.
6. Attempt to preview or publish the post/page to confirm that the issue persists.

### Screenshots, screen recording, code snippet

<img width="815" alt="Screenshot 2023-08-25 at 12 19 18 PM" src="https://github.com/WordPress/gutenberg/assets/31700597/7a61f17e-4d5e-47a4-83af-25ac48782c52">
<img width="1109" alt="Screenshot 2023-08-25 at 12 19 49 PM" src="https://github.com/WordPress/gutenberg/assets/31700597/34bf4165-a107-4ee4-8d3a-32df11256c46">

https://github.com/WordPress/gutenberg/assets/31700597/404b63b7-203c-40c4-be45-c7a7ab33a79b

 

### Environment info

- WordPress 6.3
- Gutenberg 16.5
- Themes tested: Blank Canvas, Erma

This issue has been tested on multiple instances to ensure that it is not specific to a particular environment. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by wynwin** [comment]
6722270-zd-a8c

**Comment by kelasante** [comment]
Another user report in 6741628-zen on an atomic site. I'm also unable to add a video to a cover block on my test atomic site. 

cc @glendaviesnz since this issue appears to be closed.

**Comment by glendaviesnz** [comment]
Thanks @kelasante this problem should be fixed by [this PR](https://github.com/WordPress/gutenberg/pull/53961), which will be in the next release of Gutenberg.

**Comment by ghost** [comment]
6744463-zen on simple site had this issue. Told them we will follow up once this is released.
