### ISSUE TITLE
Font Library: use /wp-content/fonts instead of /wp-content/uploads/fonts to store font assets.

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#53965]
## What
Currently, we are storing the Font Library assets in `/wp-content/uploads/fonts`.
@mtias suggested we should change it back to ` /wp-content/fonts`

## Why?
- We should keep uploads for things you insert into posts.
- If we end up adding folders to media library and someone adds a "fonts" folder for some reason.

**Comment by creativecoder** [comment]
Noting that there's follow-up discussion on the fonts directory location happening in this issue: https://github.com/WordPress/gutenberg/issues/59417
