### ISSUE TITLE
Pattern title is escaping characters

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#53964]
### Description

When registering a pattern with a quotation marks in pattern title, these quotation marks are displayed as `&quot;` in Pattern Inserter.

Please make sure such characters are displayed properly.

### Step-by-step reproduction instructions

1. Register a pattern with:
```php
register_block_pattern(
	'my-pattern-example',
	array(
		'title' => __( 'My pattern with "quoted" text', 'textdomain' ),
		...
	)
);
```
2. Check how the pattern title displays in Pattern Inserter on page edit screen:  
it results in `My pattern with &quot;quoted&quot; text`.

### Screenshots, screen recording, code snippet

![pattern-inserter-escaping](https://github.com/WordPress/gutenberg/assets/2456735/7a5b3d36-aa9c-43f1-8a96-40060d4d57e7)

### Environment info

- WordPress 6.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by webmandesign** [comment]
Obviously, also affects other characters such as `&`.

**Comment by t-hamano** [comment]
Thanks for the report.

I tried testing with the following code, but could not reproduce it. Am I missing something? 🤔

```php
register_block_pattern(
	'my-pattern-example',
	array(
		'title' => __( 'My "pattern" 😄', 'textdomain' ),
		'content' => '<!-- wp:paragraph --><p>My pattern</p><!-- /wp:paragraph -->',
	)
);
```

![patterns](https://github.com/WordPress/gutenberg/assets/54422211/ddcb3aaf-c463-4452-ae8b-5cfbf00d1f3a)

**Comment by webmandesign** [comment]
@t-hamano You are right, it works. Sorry for logging the false positive ticket.
The issue was that I was using `esc_html__()` as I am used to use this and similar escaping functions everywhere. It seems I tried to be more secure than necessary this time :)
