### ISSUE TITLE
A non-existent option causes a fatal error when used inside `wp_theme_json_data_theme`

### ISSUE THREAD

**Issue by Kpudlo** [WordPress/gutenberg#53967]
### Description

If you use `get_options` within the `wp_theme_json_data_theme` filter, and the option doesn't exist in the database, it causes a fatal error. 

### Step-by-step reproduction instructions

1. Add the following snippet to a site: 

```php
function theme_json_test_callback( $theme_json ){
    
    $test = get_option('some_fake_option','fake');
}
add_filter( 'wp_theme_json_data_theme', 'theme_json_test_callback' );
```

2. See the fatal error when visiting the front end or editing a page

### Screenshots, screen recording, code snippet

**Error Details:**

```md
PHP Fatal error:  Uncaught Error: Call to a member function get_data() on null in \wp-includes\class-wp-theme-json-resolver.php:258
```

### Environment info

- WordPress v6.3
- Gutenberg Not Installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Could the cause be that the filter just does not have the proper return statement? The following code should not cause errors.

```php
<?php
function theme_json_test_callback( $theme_json ) {
	$test = get_option( 'some_fake_option','fake' );
	return $theme_json;
}
add_filter( 'wp_theme_json_data_theme', 'theme_json_test_callback' );
```

**Comment by Kpudlo** [comment]
Hi @t-hamano, 

Yes, adding `return $theme_json;` does fix the issue. Thank you!
