### ISSUE TITLE
Internal cut-paste adds empty meta element, block recovery deletes end tag only

### ISSUE THREAD

**Issue by dispoclavier** [WordPress/gutenberg#53978]
### Description

After cut-pasting or copy-pasting content inside the Block Editor, a meta element is added in front of the pasted string:

  `<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>`

After reloading the editor, an invalid or unexpected content warning displays. Block recovery removes the invalid meta end tag but leaves the meta tag, although meta tags in the body element are invalid as well per the HTML spec:

  `<meta http-equiv="content-type" content="text/html; charset=utf-8">`

### Step-by-step reproduction instructions

1. Cut or copy a string e.g. in a paragraph.
2. Paste it back.

### Screenshots, screen recording, code snippet

Documentation available but of little interest.

### Environment info

WordPress 6.3
Twenty Twenty-Three
Brave (Chrome stopped working and updating)
Desktop with Ubuntu

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hi @dispoclavier - It would be great if you could share a little more detail on this. Is it when you past _any_ text from anywhere? Where is the text being 'copied' from initially?

I'm finding I'm unable to recreate this in my testing - so some further details would be useful.

**Comment by dispoclavier** [comment]
Thank you @jordesign for looking into this weird UX issue.

> Is it when you past _any_ text from anywhere?

No, it does not occur when the text comes from a text editor, from a public page made with WordPress.

> Where is the text being 'copied' from initially?

The text is copied from any paragraph block, in the same editor or in another instance. Hence it is frequent as authors move text snippets around, posts may end up littered with these meta elements, and after reopening they are full of invalid markup. After recovering the blocks one by one, the post is still full of stray meta tags looking weird in the source of its public page.

> I'm finding I'm unable to recreate this in my testing

Doing Ctrl+X Ctrl+V after selecting some text in a paragraph does the trick at my end.

After thinking about it, I confess that cut-pasting own stuff rather than deleting and rewriting is probably rare. Copy-pasting, even more. It may happen when writing up documentation…

**Comment by t-hamano** [comment]
I installed Brave and tested it, but could not reproduce it.

- Does it work correctly in browsers other than Brave?
- Do you have any extensions enabled that would interfere with Gutenberg copy events?

**Comment by dispoclavier** [comment]
> I installed Brave and tested it, but could not reproduce it.

Sorry for the trouble.
 
> * Does it work correctly in browsers other than Brave?

I’m unable to test in Chrome and Firefox.

> * Do you have any extensions enabled that would interfere with Gutenberg copy events?

No I have tested it with all extensions deactivated.

https://onlinehtmleditor.dev/ shows that it happens when _pasting_ in the Block Editor. After _copying_ therein, there is no meta tag in the clipboard.

**Comment by t-hamano** [comment]
@dispoclavier I overlooked that you are using Ubuntu OS. I don't have a machine with Ubuntu OS, but is it possible to try it with other OS or other browsers?

**Comment by dispoclavier** [comment]
> is it possible to try it with other OS or other browsers?

I shall try to use Windows. Apologies for my delay. It is a matter of changing the hard disk drive. And the keyboard layout.

**Comment by dispoclavier** [comment]
Please let me do the required tests. I can’t carve out time right now, so please be patient.

**Comment by dispoclavier** [comment]
A quick Google search brings up a similar issue referenced in other such issues:

https://github.com/WordPress/gutenberg/issues/33585

I’ve also tried to test in Chromium but it shows a blank screen. Switching to Classic editor the bug does not happen there.

**Comment by dispoclavier** [comment]
Sorry for not thinking at this before: Now I’ve tested in Chrome for Android and the bug does not happen. So it’s an issue of Chrome or Brave for Linux as hinted in #33585. 

It only happens when pasting from Gutenberg into Gutenberg because it is restricted to internal, per https://github.com/WordPress/gutenberg/pull/36356#issuecomment-966057405

If it is intentional, it should be documented in the first place, and have a setting in Chrome for desktop.

Also, the feature adding the meta element/tag addressed a bug in MacOS and should be restricted to that OS, but I am seeing it in action on Linux.

Plus: The fix in https://github.com/WordPress/gutenberg/pull/36356 only refers to the actual meta tag. But I am getting a **meta end tag** `</meta>` on top of that. And the whole compound stays in place, throws an error, gets the end tag removed on user request, but the meta tag is still there despite https://github.com/WordPress/gutenberg/pull/36356

**Comment by dispoclavier** [comment]
Just tested it in Falkon 23.08.2 on Ubuntu and the bug does not happen.

So this is an issue of Chrome and derived Brave, for desktop only, and as you found out, not on all OSes.

Thank you @t-hamano and @jordesign for looking into this issue, for running tests, and for your patience.

**Comment by dispoclavier** [comment]
Following the links just see another issue addressing seemingly the same problem:

https://github.com/WordPress/gutenberg/issues/34867

**Comment by t-hamano** [comment]
Thank you for letting me know in detail. If possible, could you send me the message logged in the browser console when pasting?

My guess is that [the current logic for removing meta tags](https://github.com/WordPress/gutenberg/blob/19c8d6f12f0fd1b0f7efd10a813d90660eb0d87f/packages/block-editor/src/utils/pasting.js#L42) may not be sufficient.

![paint](https://github.com/WordPress/gutenberg/assets/54422211/bccebe44-0cf3-4e8f-86f3-a7f6382d2c12)

**Comment by dispoclavier** [comment]
With this paragraph:
```html
<p>Cut and <em>paste</em> this.</p>
```
After switching to visual mode and I cut and paste it back, I get this:
```html
<p><meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>Cut and <em>paste</em> this.</p>
```
And the console says:
```
block-editor.min.js?ver=6bf412b7afa6151863a3:41 Received HTML:

 <meta http-equiv="content-type" content="text/html; charset=utf-8">Cut and <em>paste</em> this.
block-editor.min.js?ver=6bf412b7afa6151863a3:41 Received plain text:

 Cut and paste this.
```
So there is not only the meta tag but also an end tag, that went unmentioned, and the console does not report it either. It causes the block to become invalid and requiring block recovery. This negatively affects user experience.

As you mentioned, `removeCharsetMetaTag()` might not work. But there is another place addressing this issue, in `wp-includes/js/dist/blocks.js:15360`. Trying to fix it by adding the end tag however does not get it to work (with `SCRIPT_DEBUG` set to `true`):

```js
function pasteHandler({
  HTML = '',
  plainText = '',
  mode = 'AUTO',
  tagName,
  preserveWhiteSpace
}) {
  // First of all, strip any meta tags.
  HTML = HTML.replace(/<meta[^>]+><\/meta>/g, ''); // Strip Windows markers.
```
Best would probably be to close this issue as unsolvable or wontfix and rather report the bug to Chrome. Chrome does have issues, I remember a bug affecting Chrome, Edge and Firefox for Android, but not Brave and Opera for Android. Now Chrome for Android is free from this bug, just Brave (and probably Chrome) for Ubuntu is not.

The problem is, I can’t get the latest version of the browser. That is also why I’m using Brave, as Chrome stopped working and updating (it crashed when saving a page). Do I need a new computer? It seems this issue does not warrant the expense since doing the copy-paste jobs in plain text while editing as HTML is hassle-free.

Edit: Added a screenshot for completeness.
![console-log](https://github.com/WordPress/gutenberg/assets/16785498/157e7da9-d04b-4543-ae34-9032986bf763)

**Comment by dispoclavier** [comment]
This fixed it:

In `wp-includes/js/dist/block-editor.js:54916`, define the constant `metaTag` as the full meta tag:

```js
const metaTag = `<meta http-equiv="content-type" content="text/html; charset=utf-8">`;
```

in lieu of current:

```js
const metaTag = `<meta charset='utf-8'>`;
```

(Removing the quotes around `utf-8` was not enough.)

This fix includes the `</meta>` end tag coming along, so this removes the full meta element that is currently added in front of the pasted string.

Now I get this console output:

```﻿
block-editor.js?ver=…d24a36b779ba0:54728 
Received HTML:

 Cut and <em>paste</em> this. 

block-editor.js?ver=…d24a36b779ba0:54729 
Received plain text:

 Cut and paste this.

**Comment by dispoclavier** [comment]
The slightly more readable console output above is due to changing `block-editor.js:54727` to:

```js
window.console.log('\nReceived HTML:\n\n', html, '\n\n');
window.console.log('\nReceived plain text:\n\n', plainText, '\n\n');
```

The whole fix was a bit tricky for me because there is also another place with the same, but I was unable to fix it there:

`wp-includes/js/dist/editor.js:12064`.

**Comment by dispoclavier** [comment]
Just tested it on a live website, it works. In `wp-includes/js/dist/block-editor.min.js` we need to replace:

```
<meta charset='utf-8'>
```

with:

```
<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">
```

**Comment by dispoclavier** [comment]
@t-hamano Thanks a lot for advising to check the console log and bringing me on track towards a solution.

**Comment by dispoclavier** [comment]
I didn’t notice that as reported in https://bugs.chromium.org/p/chromium/issues/detail?id=1264616 that `block-editor.js:54907` cites a comment on, the added meta tag was actually `<meta charset='utf-8'>` in Chrome on MacOS X, so I won’t suggest breaking the existing fix but rather adding a new one designed for Chrome on Linux:

```js
/**
 * Removes the http-equiv charset meta tag inserted by Chromium for Linux.
 *
 * @link https://github.com/WordPress/gutenberg/issues/53978
 *
 * Fix based on existing fix.
 * @see removeCharsetMetaTag()
 * @link https://github.com/WordPress/gutenberg/issues/33585
 * @link https://bugs.chromium.org/p/chromium/issues/detail?id=1264616#c4
 *
 * @param {string} html The HTML to be stripped of the meta tag.
 * @return {string} The cleaned HTML.
 */
function removeHttpEquivCharsetMetaTag(html) {
  const httpEquivMetaTag = `<meta http-equiv="content-type" content="text/html; charset=utf-8">`;

  if (html.startsWith(httpEquivMetaTag)) {
    return html.slice(httpEquivMetaTag.length);
  }

  return html;
}
```

Then call the new function after the existing function at current line 54724:

```js
      html = removeCharsetMetaTag(html);
      html = removeHttpEquivCharsetMetaTag(html);
```

**Comment by dispoclavier** [comment]
As of the `</meta>` end tag, Chromium does not add it to the clipboard since the block editor does not need to remove it.

So the invalid `</meta>` tag seems to be added by the block editor not noticing — before validating the block — that meta tags are self-closing.

I see this as a downside of not writing self-closing tags in XHTML syntax. (https://stackoverflow.com/a/19510239)

@t-hamano Is the PR up to me?

**Comment by dispoclavier** [comment]
Simpler would be to just extend the existing function in `block-editor.js:50460`.

```js
/**
 * Removes the charset meta tag inserted by Chromium.
 * See:
 * - https://github.com/WordPress/gutenberg/issues/33585
 * - https://bugs.chromium.org/p/chromium/issues/detail?id=1264616#c4
 * - https://github.com/WordPress/gutenberg/issues/53978
 *
 * @param {string} html the html to be stripped of the meta tag.
 * @return {string} the cleaned html
 */
function removeCharsetMetaTag(html) {
  const metaTag     = `<meta charset='utf-8'>`;
  const longMetaTag = `<meta http-equiv="content-type" content="text/html; charset=utf-8">`;
  if (html.startsWith(metaTag)) {
    html = html.slice(metaTag.length);
  }
  if (html.startsWith(longMetaTag)) {
    html = html.slice(longMetaTag.length);
  }
  return html;
}
```

**Comment by dispoclavier** [comment]
@t-hamano @jordesign As you probably suspected in https://github.com/WordPress/gutenberg/issues/53978#issuecomment-1698151299 and https://github.com/WordPress/gutenberg/issues/53978#issuecomment-1712547000 and I guessed in https://github.com/WordPress/gutenberg/issues/53978#issuecomment-1768612359, this issue does not occur in modern browsers, at least not in Chrome 119.0.6045.160 nor in Edge 119.0.2151.58 tested yesterday on Windows 10. Sorry for being late testing, and even later reporting an issue that could have been solved alongside https://github.com/WordPress/gutenberg/issues/33585 like so (extended from `wp-includes/js/dist/block-editor.js:50460..50477`):

```js
/**
 * Removes the charset meta tag inserted by Chromium.
 * See:
 * - https://github.com/WordPress/gutenberg/issues/33585
 * - https://bugs.chromium.org/p/chromium/issues/detail?id=1264616#c4
 * - https://github.com/WordPress/gutenberg/issues/53978
 *
 * @param {string} html the html to be stripped of the meta tag.
 * @return {string} the cleaned html
 */
function removeCharsetMetaTag(html) {

  const metaTags = [
    `<meta charset='utf-8'>`,
    `<meta http-equiv="content-type" content="text/html; charset=utf-8">`,
  ];

  metaTags.forEach((metaTag) => {
    if (html.startsWith(metaTag)) {
      html = html.slice(metaTag.length);
    }
  });

  return html;
}
```

Does this fit the bill? It allows people on Ubuntu 16.04 like me not to customize `block-editor.min.js`.

**Comment by dispoclavier** [comment]
@jordesign @t-hamano Since this issue does not affect recent browsers, e.g. Chrome 119.0.6045.160, the suggested fix is unlikely to make it into WordPress Core. I was about to set up a PR, then dropped it as pointless and a waste of time. So, if you are okay, this issue should probably be closed as wontfix.

Anyway, for individual needs, as hinted in https://github.com/WordPress/gutenberg/issues/53978#issuecomment-1769880114, this issue can be fixed in `block-editor.min.js` if WordPress upgrades are controlled by adding:
```php
define( 'WP_AUTO_UPDATE_CORE', false );
```
in `wp-config.php`.

Thank you for your kind assistance.

**Comment by Mamaduka** [comment]
Closing as won't fix per @dispoclavier suggestion - https://github.com/WordPress/gutenberg/issues/53978#issuecomment-1817645974.
