### ISSUE TITLE
Transform to preview glitch when the editor does not have sufficient width

### ISSUE THREAD

**Issue by VinodSoftcripts** [WordPress/gutenberg#53985]
### Description

Transform into 'Row,' 'Stack,' and 'Columns' previews is not functioning correctly while the Document Overview is open in the block editor.

### Step-by-step reproduction instructions

1. Open the block editor for any page.
2. Create multiple nested columns with an equal split of columns.
3. Click on 'Document Overview' in the toolbar.
4. Click on the 'Transform to' option on the right side of the nested columns.
5. Hover over the 'Row' or 'Stack' option to preview.
6. Now, you will notice that the preview keeps being added and removed.

### Screenshots, screen recording, code snippet

https://capture.dropbox.com/4eCv9gNCkurWu1n6

### Environment info

`
### wp-core ###

version: 6.3
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html/wordpress
wordpress_size: 52.04 MB (54567978 bytes)
uploads_path: /var/www/html/wordpress/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /var/www/html/wordpress/wp-content/themes
themes_size: 12.35 MB (12952099 bytes)
plugins_path: /var/www/html/wordpress/wp-content/plugins
plugins_size: 292.56 KB (299581 bytes)
database_size: 1.75 MB (1835008 bytes)
total_size: 66.43 MB (69654666 bytes)

### wp-active-theme ###

name: Twenty Twenty-Three (twentytwentythree)
version: 1.2
author: the WordPress team
author_website: https://wordpress.org
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor
theme_path: /var/www/html/wordpress/wp-content/themes/twentytwentythree
auto_update: Disabled

### wp-themes-inactive (3) ###

Impacto 2023: version: 1.0.0, author: Profound Projects, Auto-updates disabled
Twenty Twenty-One: version: 1.9, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.5, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (1) ###

Create Block Theme: version: 1.13.2, author: WordPress.org, Auto-updates disabled

### wp-plugins-inactive (2) ###

Akismet Anti-Spam: Spam Protection: version: 5.2, author: Automattic - Anti Spam Team, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 MB
max_file_uploads: 20
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 6.1.41-63.114.amzn2023.x86_64 x86_64
httpd_software: Apache/2.4.56 (Amazon Linux)
php_version: 8.2.7 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 8.0.1 OpenSSL/3.0.8
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false
current: 2023-08-28T11:25:30+00:00
utc-time: Monday, 28-Aug-23 11:25:30 UTC
server-time: 2023-08-28T11:25:28+00:00

### wp-database ###

extension: mysqli
server_version: 10.5.18-MariaDB
client_version: mysqlnd 8.2.7
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wordpress/wp-content
WP_PLUGIN_DIR: /var/www/html/wordpress/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This problem will occur when the content is not wide enough, not just for a particular block. So let me update the issue title.

https://github.com/WordPress/gutenberg/assets/54422211/c10912ed-1ee5-4e3f-b0c5-51a3cc7f988e

**Comment by t-hamano** [comment]
I found #51309 which already reported the same issue, so I would like to close this issue.
