### ISSUE TITLE
Font Library: load collection data from a URL

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#53992]
## What?
Font Library: load collection data from a URL. Currently, we are loading data for a collection [from a JSON file on the WordPress server.](https://github.com/WordPress/gutenberg/pull/53816)

## Why?
We would need to add a way to load the data from a URL to provide a dynamic list of font families.

## Tracking issue
[Font Library. Stage 2](https://github.com/WordPress/gutenberg/issues/53307)

**Comment by matiasbenedetto** [comment]
A potential implementation for this:
- https://github.com/WordPress/gutenberg/pull/54067

**Comment by pbking** [comment]
Resolved in #54566
