### ISSUE TITLE
Connect text block controls (alignment)

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#54]
![image](https://cloud.githubusercontent.com/assets/548849/22828351/03c6a87c-ef9d-11e6-8cb9-518648710ecb.png)

These should change alignment at block level.

**Comment by BE-Webdesign** [comment]
If you check out #48, it solves that already, and makes for creating any other block controls for new blocks rather easy.

**Comment by BE-Webdesign** [comment]
This was for the most part solved in #60.  I think this can be closed.

**Comment by jasmussen** [comment]
Thanks @BE-Webdesign, solid work!
