### ISSUE TITLE
Refine the up/down arrows to balance visibility with usability better

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#5400]
The side-UI and the inserter interfaces have been iterated a lot over the past few releases, but they are stabilizing, which is a good time to refine.

The _movers_ — the side-UI with up and down arrows to move one or multiple blocks around on the page — were made smaller as part of one of the iterations. Perhaps too small.

Let's revisit those arrow icons, and try to refine them with an eye towards balancing their visual size, their clickable hit-area, and their utility.

**Comment by karmatosed** [comment]
I would +1 for increasing size and/or hit area size.

**Comment by jasmussen** [comment]
Work on this is ongoing in two PRs, a general refactor and bigger hit areas in https://github.com/WordPress/gutenberg/pull/5658 and bigger icons in a separate branch that's not yet PR'ed.

**Comment by jasmussen** [comment]
Closing this in favor of #4223 as this is mostly a duplicate, with the added addition that I mean to change the icons to be visibly larger as well.
