### ISSUE TITLE
Clarify strings “Write quote…” and “Write citation…”

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/gutenberg#5401]
## Issue Overview
The translation project for gutenberg currently contains two strings that in many languages would translate similarly: “Write quote…” and “Write citation…”

If these strings actually mean the same, then please use the same term, either quote or citation.
If these strings have different meaning, then clarifying comments for translators are needed.

## Todos
- [ ] Figure out if these strings have the same meaning or not
- [ ] Fix it

**Comment by karmatosed** [comment]
Closing as I think this has been tackled, if it hasn't then we can reopen.
