### ISSUE TITLE
Cannot edit blank footnote using Firefox

### ISSUE THREAD

**Issue by nigeln42** [WordPress/gutenberg#54015]
### Description

Unable to select an empty footnote to enter text. On Chrome you can select between the number and the backlink icon. Using Firefox the text insert cursor shows but clicking does not set text entry mode. Latest Firefox Version 116.0.3 (64-bit) on Windows 

### Step-by-step reproduction instructions

1. Add a footnote
2. Click away from the new footnote without entering text
3. Attempt to select the insertion point. Cursor changes to insert but clicking has no effect.

### Environment info

Wordpress 6.3
Gutenberg Version 16.5.0
Custom theme based on TwentyTwentThree
Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
Thanks for the report.

I was also able to reproduce the issue you reported, and in Firefox, in addition to the problem you reported, there also seems to be a problem with clicking on the backlink icon not moving the focus to the footnote link.

https://github.com/WordPress/gutenberg/assets/54422211/ee6ee84c-f936-4836-8c5d-dab347426c9e

**Comment by annezazu** [comment]
@ellatrix  for awareness!
