### ISSUE TITLE
Fatal Error: Cannot declare class

### ISSUE THREAD

**Issue by AndrewMclaren8** [WordPress/gutenberg#54012]
### Description

Fatal error: Cannot declare class WP_REST_Navigation_Fallback_Controller, because the name is already in use in /var/www/wp-content/plugins/gutenberg/lib/experimental/class-wp-rest-navigation-fallback-controller.php on line 0

Please contact with your plugin provider once with this error message.

### Step-by-step reproduction instructions

I believe i was some maintenance from your end causing this issue. had no issues untill last night.

### Environment info

Version 16.5.0 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hey @AndrewMclaren8 - is it possible you have another plugin trying to provide navigation functionality? That error you shared (thank you) indicates that something _other_ than Gutenberg is trying to use the class name, but Gutenberg is already using it.

**Comment by AndrewMclaren8** [comment]
Thank you for getting back to me. I will have a look into this.

Thanks,


------------------------------------------------------------------------------

Andrew McLaren
Web Developer

Ext: 886
DDi: 01316037486
www.mcewanfraserlegal.co.uk<https://www.mcewanfraserlegal.co.uk/>

McEwan Fraser Legal, Solicitors and Estate Agents
Head Office: 0131 524 9797
DX 553410, Edinburgh

------------------------------------------------------------------------------

Follow us on our Social Feeds

[Facebook] <https://www.facebook.com/mcewanfraserlegal> [Twitter]  <https://twitter.com/mcewanfraser> [Instagram]  <https://www.instagram.com/mcewanfraserlegal/> [LinkedIn] <https://www.linkedin.com/company/mcewan-fraser-legal>

[https://admin.mcewanfraserlegal.co.uk/img/signature/email-signature-current.jpg]

CYBERCRIME WARNING: Please be aware of the significant risk posed by cyber fraud, specifically affecting e-mail accounts and bank account details. E-mail can be insecure and has the risk of being intercepted by Cyber criminals or altered before reaching you as criminals are known to target e-mails to and from solicitor’s firms in an attempt to alter bank details to divert funds to their account. These emails look as if they have come from the firm as criminals clone email addresses. Please note that our bank account details will never change during the course of a transaction, and we shall take no responsibility if you transfer funds to the wrong account. Please always check our firm's account details that you have been provided with before you transfer any money. A particular tool of scammers is to put victims under time pressure using email correspondence.

________________________________
