### ISSUE TITLE
[Font Library] Google fonts collection: generate SVG previews and add them to the list

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#54038]
To improve the performance of the frontend loading of the fonts list coming from a collection like the Google Fonts one, we would need to create SVG previews of the font families.

## More context:
- https://github.com/WordPress/gutenberg/issues/52795

## Links:
- https://github.com/WordPress/gutenberg/issues/53307
- https://github.com/WordPress/gutenberg/issues/53926

**Comment by matiasbenedetto** [comment]
The SVG preview generation is working on this prototype:
https://github.com/matiasbenedetto/google-fonts-to-wordpress-collection/
If it looks somewhat OK, we would need to find a right place to store that repo.

**Comment by mikachan** [comment]
I believe this can be closed with https://github.com/WordPress/gutenberg/pull/54566, please re-open if necessary!
