### ISSUE TITLE
[Font Library] Frontend: Load SVG previews instead of font files

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#54039]
In the Font Library frontend, we would need to implement the loading of the SVG files instead of the actual font assets to list the font families to improve the performance of the font loading.

## Context:
- https://github.com/WordPress/gutenberg/issues/52698#issuecomment-1696426099

- https://github.com/WordPress/gutenberg/issues/54038

**Comment by pbking** [comment]
Resolved in #54566
