### ISSUE TITLE
Embed Block: Add support for x.com links

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#54042]
## What problem does this address?

Tying to use the `https://x.com` URL to embed tweets results in a text link only. Swapping the `x.com` for `twitter.com` does work to embed the tweet.

Originally requested here: https://github.com/Automattic/wp-calypso/issues/81116

## What is your proposed solution?

Add support for both URL versions to be embedded by the Embed block.

**Comment by BrookeDot** [comment]
Related Core Trac ticket: https://core.trac.wordpress.org/ticket/59142

**Comment by fluiddot** [comment]
The Embed block relies on the [oEmbed endpoint provided by WordPress](https://developer.wordpress.org/advanced-administration/wordpress/oembed/). I checked [the oEmbed implementation](https://github.com/WordPress/wordpress-develop/blob/75c06d620c7dc031e6845a5f70c3ffa6fa2b6b68/src/wp-includes/class-wp-oembed.php#L53-L113) and seems that `x.com` URLs are not included, so embeds using that URL won’t be resolved using the Twitter/X oEmbed service (`https://publish.twitter.com/oembed`). I also checked the [Twitter/X API for embeds](https://developer.twitter.com/en/docs/twitter-for-websites/oembed-api#item1), as well as [the Twitter embed tool](https://publish.twitter.com/), and surprisingly it doesn’t resolve either using `x.com` URLs 🤔. I tried generating the embed code directly from a Tweet and it uses the `twitter.com` domain, so seems that for embeds we should still use that domain.

It’s not clear whether the Twitter oEmbed API will support `x.com` URLs, so in the meantime we could manually change the domain to `twitter.com` when requesting the embed as a workaround. Eventually, the `x.com` URLs should be supported in [the WordPress `oEmbed` functionality](https://github.com/WordPress/wordpress-develop/blob/75c06d620c7dc031e6845a5f70c3ffa6fa2b6b68/src/wp-includes/class-wp-oembed.php#L53-L113).

**Comment by fluiddot** [comment]
Following this comment, I opened https://github.com/WordPress/gutenberg/pull/54876 with the shared proposal.
