### ISSUE TITLE
Quote block: can't cut or copy and paste into citation field

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54043]
Using GB 16.5.1 and WP 6.3.1, I noticed that I can't cut or copy and paste into the citation field:

https://github.com/WordPress/gutenberg/assets/26996883/b41bcb46-4563-4e37-a46f-541e2ee0c3e6

Adding this to the [writing experience tracking ](https://github.com/WordPress/gutenberg/issues/53305)as this totally ruined my day writing up a call for testing 🙃

**Comment by ellatrix** [comment]
This was reported in #53422, and would be fixed by #53453. I know it's a bad bug and should be merged asap, it just needs  a review.
