### ISSUE TITLE
Image block's caption formatting box is obscuring the caption text box

### ISSUE THREAD

**Issue by happychait** [WordPress/gutenberg#54045]
### Description

While trying to add a caption to the image, the caption formatting box (with Bold, Italic, and Link controls) is coming in the way, so the caption is not visible while typing.

### Step-by-step reproduction instructions

1. Start a post or page editor
2. Add an Image block
3. Enable captions from the block toolbar
4. Try to type the caption

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1519466/0093420a-39fd-47f6-bd62-3770ab2b0fad

### Environment info

Gutenberg 16.5.1 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by karthick-murugan** [comment]
@happychait - This issue no longer exists in the latest gutenberg version 19.9.0. Please have a look at the testing video.

https://github.com/user-attachments/assets/2bacdf57-c844-49fc-9b79-e9db5308057a

**Comment by happychait** [comment]
Perfect. Works amazingly now. Thank you so much for the fix!

**Comment by karthick-murugan** [comment]
@happychait - Hope you can close the issue now. Thank you.
