### ISSUE TITLE
Post navigation link: The text orientation option does not work on the front

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#54052]
### Description

When I worked on extending the writing mode and text orientation options, I found that the post navigation link block does not have the writing mode styles applied on the front. The inline styles need to be added to the blocks's PHP file.

### Step-by-step reproduction instructions

Activate a block theme.
The writing mode setting is disabled by default; set it to true in theme.json settings > typography > Writing mode
```
	"settings": {
		"typography": {
			"writingMode": true
		}
	}
```

In the block editor, add a post navigation link block (next or previous). 
Open the block settings sidebar and select the more options in the typography panel.
Enable the text orientation panel, and the vertical text orientation option.
Save and view the front of the website.
Confirm that the text is not vertical.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bph** [comment]
I can confirm: the post navigation link block (Previous/Next) doesn't adhere to vertical setting. It works in the Editor but not on the front end. 
Tested with Blue Note theme.

<img width="456" alt="Screenshot 2023-08-30 at 14 54 37" src="https://github.com/WordPress/gutenberg/assets/39980/91e2fb96-32c2-4cc8-98ac-a3d68af6e83e">

<img width="664" alt="Screenshot 2023-08-30 at 14 54 30" src="https://github.com/WordPress/gutenberg/assets/39980/c49f7c49-5daf-42bd-b2ea-4af7033b0a35">
