### ISSUE TITLE
Copy Blocks Context Menu option doesnt always appear

### ISSUE THREAD

**Issue by namithj** [WordPress/gutenberg#54057]
### Description

Copy Blocks Context Menu doesnt always appear if the top pr bottom most element is an image block

### Step-by-step reproduction instructions

1) Select a set of blocks with an image block at the top or bottom of the set.
2) Click on the three dots menu to bring up the context menu.
3) The selection will get deselected and the contect menu for  either the top or bottom block will appear.

The behaviour is not consistent.  It will sometimes work as intended.  When the issue occurs it will behave the same in the list view as well as in the main editor section.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/48271037/da54bd27-b900-40b9-aa0b-41973c453960

Screen grab video showing both faulty and expected behaviour

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Thanks for reporting. I was not able to replicate it in Chrome, Firefox, or Safari. @namithj Is there any more info you could share about your environment? This might make replication easier. Thanks!

**Comment by jordesign** [comment]
Hi @namithj  - just checking again to see if you can offer any further information?

**Comment by namithj** [comment]
Unable to reproduce after WP 6.3.2
