### ISSUE TITLE
Gallery block: thumbnails instead of full images

### ISSUE THREAD

**Issue by radogado** [WordPress/gutenberg#5405]
The Gallery block inserts full size images into the page, but they could be huge and would make the page too heavy. Can it insert thumbnails instead so my theme's [Lightbox](https://rado.bg) can take over? I'd like to update it for the Gutenberg Gallery-with-links structure. Thanks.

**Comment by Soean** [comment]
Hey @radogado,
thanks for your report. We already have a ticket for this issue #1450
So I close this one, feel free to comment on the existing ticket.
