### ISSUE TITLE
Block toolbar stays on top of post (mobile)

### ISSUE THREAD

**Issue by rxbracho** [WordPress/gutenberg#54064]
### Description

I didn't know there was a different repository for the block editor so this is a copy of a bug I opened in WordPress core, under the Editor category (#59242)...

When working on a post using a mobile browser and WordPress 6.3.1, the toolbar of the "current block" (has focus) stays on top of the entire post, so one must scroll up for simple things like italicize, create a link, a footnote, or change a heading level.
On a desktop browser, the toolbar appears immediately above the "current block".

Thanks in advance,

_Rafael_

### Step-by-step reproduction instructions

Trivial test. On a mobile device edit a post or a page and see how the toolbar of every block stays on top of the entire post.

### Environment info

WordPress 6.3.1 with the 2023 theme. The only change to such theme is the addition of Polylang, everything else is vanilla. I haven't tried disabling Polylang but this is clearly an issue of how sticky toolbars are implemented.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by jordesign** [comment]
Hi @rxbracho I see this behaviour as well - but seems it may be by design.

Is this something that you're seeing has changed recently?

**Comment by rxbracho** [comment]
I am new to the block editor but I doubt that it is by design to make you scroll every time you need to do something like italicize a word. Furthermore, the app doesn't behave like the editor in the browser. It has to do with the reactive behavior when you get to mobile sizes.

A more reasonable place to put it for mobile devices would be anchored at the bottom of the viewport. It would appear just above the phone keyboard, as it does in the app.

I cannot use the app because it doesn't support Polylang and we only see the posts and pages of the default language. So, I'm "stuck" with the browser experience, which is superb except for this major issue of constant scrolling.

**Comment by t-hamano** [comment]
I tested it in the following environment.

- Launch a WordPress site with InstaWP
- Enable the latest Gutenberg
- The device is iPhone 12
- Twenty Twenty-Three Theme
- Tested with Chrome and Safari

From what I've tested, it looks like you can decorate without scrolling. Is this the same behavior you're seeing?

https://github.com/WordPress/gutenberg/assets/54422211/8fafa9eb-3c11-4a75-bf01-595a035debac

**Comment by rxbracho** [comment]
No, the block toolbar does not stay on top of the viewport as it happens on the video. What is instaWP? Also, I have Android but I have to scroll when using Chrome (and Firefox and Samsung Internet).

I'm encouraged to see the behavior you show, now I just have to reproduce it on my phone (sigh).

**Comment by t-hamano** [comment]
Maybe I'm not testing correctly, or maybe it's an OS or browser-dependent issue. Let's wait for other people's feedback 😅

**Comment by rxbracho** [comment]
@t-hamano When you tested, in step (2) you said: "Enable the latest Gutenberg". How could I do that, instead of using whatever comes in vanilla 6.3.1? I'm wondering if the issue is solved in the "latest" version of the editor.

**Comment by t-hamano** [comment]
> I'm wondering if the issue is solved in the "latest" version of the editor.

First, we need to determine whether the problem reproduces itself in the latest editor, whether it is OS- or browser-dependent, and what the ideal behavior is.

> "Enable the latest Gutenberg". How could I do that, instead of using whatever comes in vanilla 6.3.1?

It will be possible to check if the problem is fixed in the latest editor by installing the Gutenberg plugin that has been released.

**Comment by rxbracho** [comment]
I'm sorry for being dense, but how do I do that? I doubt that it is browser-related because it happens with three on my phone, one being Chrome, with which you tested. OS issues would be possible, I have a Samsung with Android 12.

So, can you point me to the latest Gutenberg plugin that will be stable? I assume it's a zip file here on GitHub?

It would make me so much more productive not having to scroll constantly. Thanks.

**Comment by rxbracho** [comment]
I finally found the Gutenberg Plugin which has the latest and greatest, even Beta, code.

AND IT WORKS!! No more scrolling! 🥳

PS. You guys need to place this version in the mainstream, the scrolling is really a downer.
