### ISSUE TITLE
Columns Block: the column count rangeControl is hidden on Wordpress 6.3

### ISSUE THREAD

**Issue by dvaansiseelr** [WordPress/gutenberg#54087]
### Description

Column count rangeControl is hidden.

### Step-by-step reproduction instructions

1. Add Columns block
2. In InspectorControls Column count rangeControl is hidden. It does let increase column count to 4-6. There has no templateLock on a column or columns block. 

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/6765320/fb2daaaa-34c3-4df6-9fce-19bc3d70b740)

### Environment info

- Wordpress 6.3 and 6.3.1

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report. But I could not reproduce it in my environment.

Does this problem reproduce if you change to the default theme and stop all plugins? If you still reproduce the problem, could you switch to the code editor and include the actual HTML code here?

![b12cdef5ad9a14c171a3a258bcfcba0b](https://github.com/WordPress/gutenberg/assets/54422211/cef12747-13f3-411b-9016-ff41f2730f40)

**Comment by dvaansiseelr** [comment]
Thank you! Before the issue I should have changed to the default theme and checked. I found that core/column type was missed in allowed block types filter in my custom theme. After adding the column type into allowed block types, column count range controll is back!

Sorry for the issue!
