### ISSUE TITLE
Formatting text within Captions (inline format bar)

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#541]
The formatting bar should appear only when you have text added in the caption field, not when you select the block.

**Comment by jasmussen** [comment]
For context, it doesn't make sense to select an image block and see "bold" and "italic" options. 

But it does make sense to see bold and italic when you have focus on the caption. Ideally we might even show the formatting bar in context of the caption:

![image](https://cloud.githubusercontent.com/assets/1204802/25575288/28bb43b6-2e56-11e7-927d-1f7d840f1267.png)

But barring this, the formatting bar should still only be visible contextual to text.

**Comment by mtias** [comment]
This could be a prop of `<Editable inline />`. Thoughts @youknowriad @iseulde?

**Comment by youknowriad** [comment]
> This could be a prop of `<Editable inlineToolbar />`

Sounds like a good solution to me 👍

**Comment by iseulde** [comment]
With #660, an alternative could be to show hide the toolbar the some text is focussed.

If not, `<Editable inlineToolbar />` sounds good too!
