### ISSUE TITLE
DFM: main toolbar stays invisible after toggling off

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#54116]
### Description

<img width="935" alt="Screenshot 2023-09-01 at 18 57 28" src="https://github.com/WordPress/gutenberg/assets/4710635/4ac2dfdb-d2cc-4b44-ba91-1c6cbc5383e4">
Cc @draganescu 
Can only be restored after refreshing the page.

### Step-by-step reproduction instructions

Toggle DFW mode on. Reload the page (important). Toggle it off. Main toolbar is empty.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by draganescu** [comment]
This doesn't happen in the site editor in my testing seems limited to the post editor. The quick fix is to not render a motion div if DFM is off but that break the niceness of the inital animation.
