### ISSUE TITLE
Highlight color picker moves

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#54114]
### Description

When I use the highlight feature from the Block Toolbar the color picker moves after I selected the colors. It opens from the Toolbar, but after I am done with the color selection it's sitting on the top right of the screen. 

### Step-by-step reproduction instructions

- Create a new post
- Add a paragraph with text
- Select portions of text
- Use the Highlight option from the Arrow-down drop down in the block's toolbar. 

### Screenshots, screen recording, code snippet

A short video
https://github.com/WordPress/gutenberg/assets/39980/cdcf5f49-a634-43ab-bca4-075e43d02b82

### Environment info

- WordPress 6.4-alpha-56491
- GB nightly: v-16.7.20230901
- Twenty-Twenty-Three

I also tested this with Blue Note Community Theme. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I would like to close this as I believe this is the same issue as [the comment](https://github.com/WordPress/gutenberg/issues/49286#issuecomment-1482797303) in #49286. I will be submitting a PR on this issue in the near future.

**Comment by bph** [comment]
Thank you @t-hamano to staying on top of this! 🙌👏
