### ISSUE TITLE
Duotone filter selector does not apply when using Image block alignment

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#54121]
### Description

(reported earlier on [Trac 59138](https://core.trac.wordpress.org/ticket/59138))

Duotone filters seem to fail in any 'classic' theme when the image has an alignment class because the duotone classes are added to the `figure` element, and that is not the same as the `.wp-block-image` element in classic themes. The [selector in block.json](https://github.com/WordPress/gutenberg/blob/17bc4c206870c4957bee83ea9e167c7815fdb2ac/packages/block-library/src/image/block.json#L118) expects both classes to be on the same element.
```
.wp-duotone-cf2e2e-abb8c3-1.wp-block-image img,
.wp-duotone-cf2e2e-abb8c3-1.wp-block-image .components-placeholder {
  filter: url(#wp-duotone-cf2e2e-abb8c3-1);
}
```

Changing `.wp-block-image` to `[class]` in that line of the block JSON worked for me in the bundled themes (Twenty Ten to Twenty Twenty-Three), though I do not know if the `.wp-block-image` class was necessary somehow.

### Step-by-step reproduction instructions

1. Activate a 'classic' theme such as Twenty Seventeen.
2. Create a new post.
3. Add an Image block.
4. Select one of the block's Alignment options (left, center or right).
5. Give duotone Highlight and Shadow colors to the block.
6. Preview the post on the front end.

### Screenshots, screen recording, code snippet

Image blocks with each alignment option, on the front end, with Twenty Seventeen

![duotone effect only works on image with no alignment](https://core.trac.wordpress.org/raw-attachment/ticket/59138/duotone-aligned-images-6.3.png)

### Environment info

WordPress 6.3 and 6.3.1, without the Gutenberg plugin
Windows 10, with both Firefox and Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sabernhardt** [comment]
When I activated Gutenberg 16.5.1, the styles did not print, so even unaligned image blocks did receive the duotone effect. (And after experiencing that in the post I created earlier, I again had no duotone with an unaligned image in a new post.)

![no images have the duotone effect](https://github.com/WordPress/gutenberg/assets/17100257/384ea133-4589-4d64-89a9-f8dfd0442226)

**Comment by bph** [comment]
Seems to be a similar problem as in 

- #54099
Doesn't feel like it's a duplicate, though.

**Comment by sabernhardt** [comment]
#54099 is probably related to the _missing_ styles in the latest plugin version, but not the bug first reported on Trac about the aligned images. The _faulty_ CSS selector is a regression in WordPress 6.3, which might be fixable in a minor release.

**Comment by ndiego** [comment]
Thanks for reporting. I can confirm. Updating the issue labels.

**Comment by annezazu** [comment]
Noting for @ajlende in case you can share any insights!

**Comment by annezazu** [comment]
[After a review](https://wordpress.slack.com/archives/C02QB2JS7/p1707152945370159) by core editor triage leads and core editor tech leads, this has been removed from the board for 6.5 consideration.
