### ISSUE TITLE
Post excerpt block removes added HTML in excerpt via block tools control

### ISSUE THREAD

**Issue by itzmekhokan** [WordPress/gutenberg#54129]
### Description

When added some HTML in prost excerpt block, its not display that style in frontend. For example if we add post excerpt block and after it change excerpt text style using block toolbar settings. The added style will not visible in frontend.

Because, `$excerpt = wp_trim_words( $excerpt, $excerpt_length );` this `wp_trim_words` function remove html tags to play with excerpt length and return modified text after trim.

This issue is also mention in the ticket - https://core.trac.wordpress.org/ticket/59270

### Step-by-step reproduction instructions

1. Add Post Excerpt Block.
2. Add some excerpt text content if there is no excerpt text rendered.
3. Add some style for excerpt content using block toolbar and save or update post.
4. Check frontend of the excerpt output, you will notice added style is not there for the excerpt content.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@itzmekhokan Thanks for the report.

I would like to close this issue as I believe this is the same problem reported in #49449.
