### ISSUE TITLE
Settings Rationale?

### ISSUE THREAD

**Issue by addedlovely** [WordPress/gutenberg#5413]
## Issue Overview
Have just trialled the latest version of Gutenburg - great to see the progress it's making - but also left me quite confused at the interface.

For blocks, you have the sidebar which contains some settings, there's also settings in the visual preview and settings when clicking the pen icon on the block. No doubt each plugin developer is going to shove stuff in different places.

When using the columns layout (which for me will be essential to most projects) - the approach of having settings in the visual preview just breaks - there's just not enough space for this to fit.

## Possible Solution
Seems to me, there should be a seperation of concerns, with the visual preview being just the visual preview, options to move blocks / convert blocks - then the settings and content options go into the sidebar. For reference this is how the theme customiser works in WordPress (and Shopify).

That sidebar could expand out over the visual preview to give more space for wide settings (content box etc).

This might need a mode shift, as that workflow wouldn't be great for just writing a flat 'normal' post - but trying to combine everything into the visual editor just doesn't work well. See the screenshot below for how confusing and pressed for space the settings get.

If there's already discussion on this, please point me in the direction - would be interested to read.

## Screenshots / Video
<img width="1392" alt="screen shot 2018-03-04 at 17 30 21" src="https://user-images.githubusercontent.com/565669/36982804-a6db3e66-2088-11e8-95fc-8310c4c5ab1f.png">

## Related Issues and/or PRs
https://github.com/WordPress/gutenberg/issues/5331
https://github.com/WordPress/gutenberg/issues/4390#issuecomment-356781738
https://github.com/WordPress/gutenberg/issues/4441

**Comment by karmatosed** [comment]
Typically the settings split into:

- By the block: when beside the block there are commonalities found in all blocks
- In inspector: changes depending on the block and if it even has settings. These differ from the toolbar as are secondary block settings, for example adding a CSS class (in most blocks) and doing styling that isn’t as common. 

I think for now this pattern works but we can iterate over time if we get feedback it doesn't from testing. Right now the testing feedback we are getting is that discoverability is an issue more than anything. That's something we are working on.

As we have existing issues that could combine with the patterns we have, lets close this one and focus there.
