### ISSUE TITLE
Unable to choose post featured image resolution in single or page template

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#54144]
### Description

There is no "resolution" setting available when placing the block in the single template. See https://github.com/WordPress/gutenberg/issues/33789#issuecomment-1653177884

### Step-by-step reproduction instructions

Place the block in the single template.

### Screenshots, screen recording, code snippet

<img width="302" alt="Screenshot 2023-09-04 at 10 41 08" src="https://github.com/WordPress/gutenberg/assets/1571592/c885348b-664f-40cc-a1b9-4b41ef587365">

### Environment info

- WordPress 6.3.1. No plugins.
- Twenty Twenty Three theme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by markhowellsmead** [comment]
The same is true of the single page template.

**Comment by jordesign** [comment]
Similar to #50271, the single template does not have access to the actual featured image from the post, only the placeholder image, that is probably why. It doesn't know what size the actual image is available in.

**Comment by markhowellsmead** [comment]
The bug persists, but closing this in favour of https://github.com/WordPress/gutenberg/issues/50271.
