### ISSUE TITLE
`CircularOptionPicker`: make focus styles resilient to button size changes

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#54156]
## What

The `button` rendered in the `CircularOptionPicker` has some custom focus styles which don't always render correctly, especially when the size of the `button` changes. This can, for example, be tested in the Global Styles sidebar in the side editor:

- open Site Editor
- open Global styles sidebar
- Click on the "Colors" menu item
- Click on the "Palette" button
- Move focus on  the color options in the "Theme" section — the focus ring displays correctly
- Click the "Color options" button (ie. the "..." button), and click the "Show details" menu item
- Try to move focus on the colors items, and notice how the focus ring is not centered around each button

https://github.com/WordPress/gutenberg/assets/1083581/be4cc1ab-82a0-4dab-8a2b-7a5766cfbf9e

## Why

This seems to be caused by how the custom focus ring has been styled. The outer focus ring has a fixed size and positioning, which makes it glithcy if/when the button's size changes.

https://github.com/WordPress/gutenberg/blob/6239b523a47111d3041a787dc288e9239bc7d3d5/packages/components/src/circular-option-picker/style.scss#L102-L128

We should move away from fixed `width`/`height` and from fixed `top` / `left` absolute positions in `px`

A potential alternative could be:

- setting `width` and `height` to something like `calc(100% + 4px)`
- using a more robust way of centering the ring on top of the button (for example [the "pop and plop" technique described here](https://web.dev/centering-in-css/#5-pop-and-plop))

**Comment by andrewhayward** [comment]
This has been resolved in #54196.
