### ISSUE TITLE
Font Library

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#54169]
## What?
**Font Library consists of a font manager that enables users to install, remove, and activate typographic fonts from various sources in WordPress**.

The Font Library is available globally, independently of the theme activated, similar to the Media Library. This list of installed fonts and their assets are site-wide available, and the users can select the fonts activated (available in the editor) for each theme. 

https://github.com/WordPress/gutenberg/assets/1310626/5876512f-b1b8-42e9-87a6-3f41725ccdbb

## 🖼️ Mockups
- https://github.com/WordPress/gutenberg/issues/45271

## 💻 Development
~The development of the Font Library has been split into three logic stages to make it easier to review and ship progressively:~
~- https://github.com/WordPress/gutenberg/issues/52698~
~- https://github.com/WordPress/gutenberg/issues/53307~
~- https://github.com/WordPress/gutenberg/issues/53926~
~**Stages 1 and 2 are intended to be [released as part of WordPress 6.4](https://make.wordpress.org/core/6-4/).**~

This was planned originally for 6.4, but due to the fact it was [punted to 6.5](https://wordpress.slack.com/archives/C02RQBWTW/p1696525101347939), the tracking issue for the tasks needed to font Library ready to merge in core are tracked in this issue:

- https://github.com/WordPress/gutenberg/issues/55277

## 🧪 Previous explorations around this:

https://github.com/WordPress/gutenberg/pull/46332
https://github.com/WordPress/gutenberg/pull/50102

**Comment by Ren2049** [comment]
Is there a chance to include a selection of operating system font stacks like suggested here? https://github.com/WordPress/twentytwentyfour/issues/175

https://github.com/system-fonts/modern-font-stacks

Not be confused with web safe fonts or the usual default serif and sans stacks, here they are grouped by typeface category based on what users have typically installed on their systems using one of the operating systems. OS ship quite a lot of fonts these days and these stacks take advantage of that by categorizing them.

**Comment by matiasbenedetto** [comment]
> Is there a chance to include a selection of operating system font stacks like suggested here?

Yes, I think it's a good idea. Here is an issue to get feedback about this idea: https://github.com/WordPress/gutenberg/issues/54186 . I linked the discussion on [stage 2](https://github.com/WordPress/gutenberg/issues/53307) tracking issue.

**Comment by annezazu** [comment]
Marking this as blessed for [major release per this slack discussion](https://wordpress.slack.com/archives/C055Y7FKS7N/p1695052825968849).

**Comment by fabiankaegy** [comment]
Hey all 👋 Not sure where else to put this feedback. I've tested the font library as of 17.5 RC1 and it works well when uploading individual font files. But as soon as I select more than one font files I get an infinite spinner that never resolves

![CleanShot 2024-01-13 at 13 48 17@2x](https://github.com/WordPress/gutenberg/assets/20684594/3068ba87-af6a-48ad-ac3b-d8d357102ca7)

**Comment by annezazu** [comment]
@fabiankaegy can you open a new issue for it and add to the 6.5 board or tag me in it so I can? <3

**Comment by Milo-W** [comment]
I don't have the Fonts section there?
Is it all out of the box with the WP installation or do I need to install something?
EDIT: Just watched a YT tutorial... OMFG... I thought Gutenberg was now part of the core??? You really release info unclearly...

**Comment by creativecoder** [comment]
Shall we close this now that the Font Library is part of WP 6.5?

**Comment by mikachan** [comment]
Closing this as the Font Library has been merged into Core 🎉  (as per [above comment](https://github.com/WordPress/gutenberg/issues/54169#issuecomment-2040899644)).
