### ISSUE TITLE
Image aspect ratio bug in Safari

### ISSUE THREAD

**Issue by BeholdPL** [WordPress/gutenberg#54182]
### Description

In Safari (desktop) images with aspect ratio, for eg. 3:4, are height 100vh. Problem occurs only in editor, on front everything is ok.

### Screenshots, screen recording, code snippet

<a href="https://ibb.co/JQpqT3H"><img src="https://i.ibb.co/JQpqT3H/Screenshot-2023-09-05-at-11-37-15.png" alt="Screenshot-2023-09-05-at-11-37-15" border="0"></a>

### Environment info

Safari 16.6
WordPress 6.3.1
Gutenberg: no plugin and with plugin v. 16.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jamestitus299** [comment]
The same issue in chrome too.
![image](https://github.com/WordPress/gutenberg/assets/91361573/1bafc886-5280-49ad-a3e1-e7c47ba32d33)

**Comment by ndiego** [comment]
Hi @BeholdPL, thanks for reporting. I just tested in the Twenty Twenty-Three theme using the layout you had in your screenshot, and I am not able to replicate it. Would you be able to test with Twenty Twenty-Three? It also looks like your image block has some custom functionality in the Toolbar. I wonder if something else might be causing this?

<img width="1666" alt="image" src="https://github.com/WordPress/gutenberg/assets/4832319/cc9232cf-82b4-4338-95a8-41b73a6cd5a2">

**Comment by BeholdPL** [comment]
> 

Hi! True, on Twenty Twenty-Three theme works fine, in my case I'm using Blocksy Theme. @jamestitus299 what theme are you using?

So is it Gutenberg issue, or it depends of theme?

**Comment by jamestitus299** [comment]
Hi, 
@BeholdPL I am using the Creatio theme. I think this is an issue with Gutenberg.

**Comment by jordesign** [comment]
Closing this issue as it seems to be theme-specific, and not part of Gutenberg itself
