### ISSUE TITLE
Front and backend very different with custom css

### ISSUE THREAD

**Issue by pulsarinformatique** [WordPress/gutenberg#54189]
### Description

Hi 
with WP 6.3.1 when we edit a page with the gutenberg editor the result in front end may be very different from what we see in back end when we use custom CSS files.

in our example we put most of the CSS in wp-content\themes\mytheme\css\my.css instead of the backend settings. 

We don't have such issues with Elementor pro for instance. what we edit in backend with Elementor pro is very similar from what  we get in front end even if we have custom css files.

Is this issue known please?

thanks

### Step-by-step reproduction instructions

Hi 
with WP 6.3.1 when we edit a page with the gutenberg editor the result in front end may be very different from what we see in back end when we use custom CSS files.

in our example we put most of the CSS in wp-content\themes\mytheme\css\my.css instead of the backend settings. 

We don't have such issues with Elementor pro for instance. what we edit in backend with Elementor pro is very similar from what  we get in front end even if we have custom css files.

Is this issue known please?

thanks

### Environment info

WP 6.3.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by justintadlock** [comment]
In general, the editor and front-end should match. But it can also depend on what theme you're using. WordPress doesn't control that.

If you can provide specific details on the exact issue(s) you're seeing, it could help determine if there's a bug.

**Comment by pulsarinformatique** [comment]
Hi 
we use the standard 20-23 theme with its child theme.
thanks

**Comment by justintadlock** [comment]
Can you provide details on the specific issues? For example, which blocks are not appearing the same? Do you have screenshots? Are you having trouble loading your custom CSS?

**Comment by felipevelzani** [comment]
Also, if your CSS doesn't apply to the editor at all, can you confirm if you are enqueueing it as expected?

You can see more here: https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/applying-styles-with-stylesheets/#enqueue-stylesheets

**Comment by pulsarinformatique** [comment]
Hi
Here is an example of the discrepancy between the back and front
thanks.


![back](https://github.com/WordPress/gutenberg/assets/10794564/a38dca2c-30f3-4e77-8cbd-df91ffaf15ff)
![front](https://github.com/WordPress/gutenberg/assets/10794564/bd7f093c-b9fd-4a25-a39c-86bb3145e9ac)

**Comment by pulsarinformatique** [comment]
Hi,

We've created a test website and successfully replicated the bug. On the example page, you'll find an image as an example with some custom CSS applied, specifically "transform: rotate(95deg) scale(2);".

The website https://wp.test-pulsar.com/ is now up and running. To access the backend, please use this link: https://wp.test-pulsar.com/wp-admin with the following credentials: admin / password.

Below, you'll find screenshots of both the builder and the site preview.
Thanks.

![image](https://github.com/WordPress/gutenberg/assets/10794564/96c8710c-e1ae-4b27-abe1-601c1f64155c)

![image](https://github.com/WordPress/gutenberg/assets/10794564/bbb8ba56-d29e-4ae2-a214-665142901845)

**Comment by pulsarinformatique** [comment]
> Hi,
> 
> We've created a test website and successfully replicated the bug. On the example page, you'll find an image as an example with some custom CSS applied, specifically "transform: rotate(95deg) scale(2);".
> 
> The website https://wp.test-pulsar.com/ is now up and running. To access the backend, please use this link: https://wp.test-pulsar.com/wp-admin with the following credentials: admin / password.
> 
> Below, you'll find screenshots of both the builder and the site preview. Thanks.
> 
> ![image](https://user-images.githubusercontent.com/10794564/266321429-96c8710c-e1ae-4b27-abe1-601c1f64155c.png)
> 
> ![image](https://user-images.githubusercontent.com/10794564/266321548-bbb8ba56-d29e-4ae2-a214-665142901845.png)

![image](https://github.com/WordPress/gutenberg/assets/10794564/5908b92a-d27e-495e-b0f6-a72581e78be5)

**Comment by justintadlock** [comment]
There doesn't appear to be a bug here. It looks like you're just not loading your custom stylesheets in the editor.

Here's a how-to guide on doing that: https://developer.wordpress.org/block-editor/how-to-guides/enqueueing-assets-in-the-editor/

**Comment by pulsarinformatique** [comment]
ok then what is the right practice so that we clearly see in backend what we get in front ? This is the very purpose of Gutenberg
thanks

**Comment by justintadlock** [comment]
> ok then what is the right practice so that we clearly see in backend what we get in front ?

You also need to load your CSS in the editor to have it match the front end. Here's a how-to guide on doing that: https://developer.wordpress.org/block-editor/how-to-guides/enqueueing-assets-in-the-editor/

**Comment by pulsarinformatique** [comment]
Hi
We have to find time to get back to this issue. We decided to keep moving forward with Elementor for the current project bet HAVE to switch to Gutenberg site editor for the next ones. It should happen in a few weeks
thanks for your patience

**Comment by pulsarinformatique** [comment]
sorry for the delay but our new resource comes next week and will be able to focus on this issue and report here. thanks for your patience since this is a very important issue

**Comment by pulsarinformatique** [comment]
The issue is solved. we called the wrong method: wp_enqueue_scripts instead of enqueue_block_assets !

thanks for your help
