### ISSUE TITLE
Get editor preferences and panels

### ISSUE THREAD

**Issue by awps** [WordPress/gutenberg#54200]
### Description

This used to be a good way to get the editor panels, by accessing the editor preferences: 
```
wp.data.select("core/edit-post").getPreferences()
```

It would return something like this: 
```
{
    "hiddenBlockTypes": [],
    "editorMode": "visual",
    "preferredStyleVariations": [],
    "panels": {
        "template": {
            "opened": true
        },
        "featured-image": {
            "opened": true
        },
        "taxonomy-panel-post_tag": {
            "opened": true
        },
        "taxonomy-panel-category": {
            "opened": true
        },
        "custom-panel/my-settings": {
            "opened": true
        },
        "post-status": {
            "opened": true
        },
        "post-excerpt": {
            "opened": true
        },

       // ....
    }
}
```

Since WordPress 6.0 this is deprecated and I have no idea how I can get the same info. It just returns undefined on anything I try.

```
select( 'core/edit-post' ).getPreferences is deprecated since version 6.0. Please use select( 'core/preferences' ).get instead.
```

What argument needs to be passed to the `get` method? 

### Step-by-step reproduction instructions

1. Go to block editor
2. Open the Dev Console
3. Type in: `wp.data.select("core/edit-post").getPreferences()`
4. A deprecation notice will be thrown.

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/1436534/2fc0e337-2d6b-4030-93f1-a9bd9b0b1b28)

### Environment info

- WordPress 6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
With the following code, you can get all the same information.

```javascript
wp.data.select( 'core/preferences' ).get( 'core/edit-post', 'hiddenBlockTypes' );
wp.data.select( 'core/preferences' ).get( 'core/edit-post', 'editorMode' );
wp.data.select( 'core/preferences' ).get( 'core/edit-post', 'preferredStyleVariations' );
wp.data.select( 'core/edit-post' ).isEditorPanelOpened( 'template' );
wp.data.select( 'core/edit-post' ).isEditorPanelOpened( 'featured-image' );
wp.data.select( 'core/edit-post' ).isEditorPanelOpened( 'taxonomy-panel-post_tag' );
wp.data.select( 'core/edit-post' ).isEditorPanelOpened( 'taxonomy-panel-category' );
wp.data.select( 'core/edit-post' ).isEditorPanelOpened( 'post-status' );
wp.data.select( 'core/edit-post' ).isEditorPanelOpened( 'post-excerpt' );
```

**Comment by t-hamano** [comment]
@awps I would like to close this issue as I believe there is a recommended means of getting editor preferences and panels. If there's anything I've missed, feel free to comment.

**Comment by awps** [comment]
Thank you and sorry for the late response. 
It was not exactly what I was looking for, but your snippet helped me with another problem. 🙂
