### ISSUE TITLE
StartPageOptionsModal should not render if content was added to a page

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#54227]
Currently the `StartPageOptionsModal` renders when you add a new post/page, but also when you _remove_ all the content on a page. This makes for a disorienting experience, as a modal pops up out unexpectedly. 

I think the modal should _only_ render when creating a new page.

 If any content has been added to the page, then removed, the `StartPageOptionsModal` should not render again. 

If we want to still provide a mechanism for users to view the modal, we can add a snackbar notification `"Choose a starter pattern."` that renders in this scenario (after content has been added and the content is removed) which provides an action `"View patterns"` for viewing the starter patterns. 

### Current experience

I delete the last top-level block on my page and the modal pops up unexpectedly.

https://github.com/WordPress/gutenberg/assets/1813435/8ec4928e-958c-4ae8-9c05-26fbd5121db8

**Comment by richtabor** [comment]
You can test the above using https://github.com/WordPress/twentytwentyfour. The theme will have a starter patterns added; so this will become more prevalent than it is today (where hardly any themes are leveraging this flow).

Related: https://github.com/WordPress/twentytwentyfour/pull/209

**Comment by Mamaduka** [comment]
Can you reproduce the bug without the Gutenberg plugin?

This is probably a regression after #53673. The modal state is now local to a `StartPageOptionsModal` component. It's rendered based on the `shouldEnableModal` condition; mounting/unmounting resets the local state.

I can also see a modal flash when updating an existing page without the content. Here's the Replay link: https://app.replay.io/recording/the-start-page-options-modal-flashes-when-updating-page--c1d0ebdb-4d57-41ef-8a88-41e433e9b52f

cc @jsnajdr

**Comment by jsnajdr** [comment]
I can reproduce this even with #53673 reverted, the bug must have been there for a very long time.

The bug manifests in two ways:
1. What @richtabor reports: if you have an existing saved page, and remove all blocks and also the title, the page becomes "unsaveable and with no content" -- a condition that triggers displaying the modal.
2. What @mamaduka found: if you have a page that has a title but no content, it's "saveable" -- this is a condition different from the first case. But when it's being saved, it becomes "unsaveable" (per the `isEditedPostSaveable` selector) while the save is in progress. Condition for the modal is satisfied -- flash!

We'll need to improve the condition to really match only pages that are brand new and empty.

**Comment by jsnajdr** [comment]
Fixing in #54227 🙂 I'm looking forward to trying out the starter patterns in Twenty Twenty-Four :+1:
