### ISSUE TITLE
Increase $default-font-size from 13px to 14px

### ISSUE THREAD

**Issue by rileybrook** [WordPress/gutenberg#5426]
Increase the `$default-font-size` variable from 13px to 14px. This suggestion is derived from conversations occurring inside a previous issue (#5359)

In reference to the`$default-font-size` variable, @karmatosed wrote:
>I would be very keen to see 14px be our minimum baseline for font sizes. 13px is still too small and can throw out any typography scale. What I would like to see tried is 14px for smaller and 16px for the basic text line.

Separated this topic into it's own ticket for visibility and organization purposes.

**Comment by karmatosed** [comment]
+1 to this but I want to get feedback on the impact of this. My leanings are to yes but I want a second opinion from @jasmussen

**Comment by jasmussen** [comment]
Closing in favor of #5359 where we are also discussing this. Will respond in a second. Thank you for the ticket!

**Comment by rileybrook** [comment]
All good, thank you @jasmussen 👍
