### ISSUE TITLE
Block Widget Editor: Widget area layout is broken

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#54295]
### Description

The latest Gutenberg seems to have the following problems with the layout in the block widget editor.

### The widget area is narrow and there is spacing around the widget area

![gb_enabled_open](https://github.com/WordPress/gutenberg/assets/54422211/b80a9bdc-c6b5-4f1b-a15f-1f32a086deb8)

### Closing the widget area results in an extremely narrow width

https://github.com/WordPress/gutenberg/assets/54422211/467ec3f4-8427-41fb-8799-638c317e2c6b

### Expected behavior (Gutenberg plugin disabled)

![gb_disabled](https://github.com/WordPress/gutenberg/assets/54422211/0bd8bea5-fc8b-4228-9a7c-178a5f9d6b98)

### Step-by-step reproduction instructions

- Activate Twenty Twenty One theme
- Go to Appearance > Widgets

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
According to my research, I think this is caused by a slight change in the structure of the Widget Editor due to #54149.

**Comment by t-hamano** [comment]
With #54149, the widget editor is now rendered via the new `BlockCanvas` component. This component has a `WritingFlow` component [with the `.editor-style-wrapper` class applied inside it](https://github.com/WordPress/gutenberg/pull/54149/files#diff-fd294b061832dec86b6258209f4532bde7ac2dd19bcba8fdd35140b146bd22e5R26).

However, the widget editor did not originally apply this class to the `WritingFlow` component. Because this class should be applied to [the content wrapper inside each widget area](https://github.com/WordPress/gutenberg/blob/7c73a89241d837198a27278f2a4e62c12220c83b/packages/edit-widgets/src/blocks/widget-area/edit/inner-blocks.js#L42).

If the entire editor has this class, you will end up with unintended style overrides. For example, if a classic theme that supports widgets defines the following theme.json, the style will also be applied to the panel title of the widget area. This is because the widget area panel title is also an h2 element, so it matches the `.editor-styles-wrapper h2` selector.

```json
{
	"version": 2,
	"styles": {
		"elements": {
			"h2": {
				"border": {
					"top": {
						"color": "#ff0000",
						"style": "solid",
						"width": "100px"
					}
				}
			}
		}
	}
}
```

It seems a bit unreasonable to assume all these cases and override the unintended style on the widget editor side. Therefore, I believe that a means to solve this problem by not giving fixed class names to the WritingFlow component is needed first.

@youknowriad 

For example, would it be possible to add something like `writingFlowProps` to the `BlockCanvas` component? The default value is an object like `{className:'editor-styles-wrapper'}`, and the approach is to provide a means to override this.

**Comment by youknowriad** [comment]
For me, it's the widgets editor that has a completely weird behavior. (styles not applied to the whole editor). In an ideal world, the widgets editor would render a separate editor per widget area. I guess there's some reason for the current approach, so in order to avoid regressions let's just avoid using `BlockCanvas` and restore the previous components.

I don't think we should pollute `BlockCanvas` with props to address the specifics of the widgets editor because it's such an edge case.
