### ISSUE TITLE
Can't style paragraph text with inline <code> tags

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#5429]
## Issue Overview
It's impossible to style text in Paragraphs blocks with `<code>` tags. This is important if you want to add some short inline code to your text like in the following example.

![gutenberg-cantaddinlinecode](https://user-images.githubusercontent.com/2078245/37021673-725973e6-2174-11e8-9559-6a62044b9cf0.png)

## Steps to Reproduce (for bugs)
1. Add Paragraph block with dummy text
2. Try to add inline `<code>` tags to part of your text

## Expected Behavior
I expect to be able to add inline code to my paragraph text. Code isn't always large chunks that require it's own block.

## Current Behavior
Impossible to style Paragraph text with `<code>` tags due to limited toolbar options

## Possible Solution
Add `<code>` icon button to toolbar so we can style inline code

_Gutenberg 2.3.0 
Firefox Quantum 58.0.2 (64-bit)
WP 4.9.4_

**Comment by youknowriad** [comment]
It's possible to add `code` within paragraph block, you can do it by switching to the HTML mode or by using backticks:

 - Type something 
 - Type backtick
 - Type something
 - Type another backtick 

I believe adding a button is plugin territory, it's the same in the classic editor

**Comment by karmatosed** [comment]
I would say +1 to this being plugin territory, however as more and more things are explored like this if they are used a lot, they will become merged into core. For now, lets close this up though as in v1 it's not something to bring in.

**Comment by maddisondesigns** [comment]
If the editor supports it already, then why not add a button for it to make it easier for people? Not everyone is going to know that you can use backticks. Also, if I make a mistake and put the second backtick next to the wrong character, the only way I can remove it is by going into the Code Editor and editing the html.

The existing editor has a Code button on the Text Tab.

Having to create a plugin to add a button so that you can easily access functionality that already exists is incredibly frustrating!

**Comment by HippDesign** [comment]
I agree. A button to add inline code elements would be the better option! +1

**Comment by norixx** [comment]
Still can't find any plug-ins that make it possible.
Any suggestion?

**Comment by cogdog** [comment]
I'm glad to find our backticks work! Where else might have I even learned this secret? I too want a `code` button- not as much for lines of code, but in my documentation I like to format 1-2 words when I refer to settings or file names. Going to HTML editor, adding `<code>...</code>` tags going back to visuals is the tedious ness which drives people to the classic editor plugin
