### ISSUE TITLE
Pressing double enter between two paragraphs of a text block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#543]
Right now it splits the text block in two, but it creates an empty `p` with noise at the beginning of the new block:

![image](https://cloud.githubusercontent.com/assets/548849/25528432/2418f9e6-2c1e-11e7-8df6-e87ee248263a.png)

**Comment by youknowriad** [comment]
Can I have more details on this. I can't reproduce (maybe a screen record or the context of the text blocks)
