### ISSUE TITLE
Quote block: Style plain button setting not working on Twenty Twenty-One theme.

### ISSUE THREAD

**Issue by VipulUpadala** [WordPress/gutenberg#54300]
### Description

I tested quote block on the twenty twenty-one theme and found the style plain button setting not working on it. 

### Step-by-step reproduction instructions

1. Created a new page and take the quote block.
2. Next, Click on style plain button setting.
3. And, check it quote block does not any effect.

### Screenshots, screen recording, code snippet

Please check the provided screenshot recording video for a better understanding of the issue.

Video URL: https://share.cleanshot.com/N5hmpftV1sZK44nMRSsN

### Environment info

- WordPress 6.3.1 running
- Chrome
- macOS 13.2

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by justintadlock** [comment]
I have confirmed this issue. However, it is an issue that is specific to the TT1 theme, which has custom CSS in its `style.css` file for styling blockquotes. This should be reported upstream on Core Trac: https://core.trac.wordpress.org/

**Comment by annezazu** [comment]
@VipulUpadala can you please report this on Core Trac? I'm going to close this out for now. If you're unable to do so, please let me know and I'll handle it personally.
