### ISSUE TITLE
Add reset/clear to the group block background image control

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#54319]
I agree with @jameskoster's [comment](https://github.com/WordPress/gutenberg/pull/53934#pullrequestreview-1616991606) on resetting. I expected to find the "Reset" control within the new group block's background image panel. You can reset it within the tools panel, but it feels necessary (and familiar, i.e. the Site Logo block) to have it here. 

Another note (related to https://github.com/WordPress/gutenberg/issues/53997), we should consistent on "Clear" vs. "Reset". 

We're using "Clear" within the color palette popover, but "Reset" within the tools panel. Same follows for the Cover block's "Clear media" button. 

Current: 
<img width="278" alt="CleanShot 2023-09-08 at 17 06 19" src="https://github.com/WordPress/gutenberg/assets/1813435/aa87c373-f5b0-4f59-b14f-bc55d40e59cd">

Expected: 
<img width="321" alt="CleanShot 2023-09-08 at 17 05 13" src="https://github.com/WordPress/gutenberg/assets/1813435/381696d3-7390-4033-82fc-2c5c7d53d82f">

**Comment by hanneslsm** [comment]
> Another note (related to https://github.com/WordPress/gutenberg/issues/53997), we should consistent on "Clear" vs. "Reset".

I wrote a comment regarding this and posted it in the related issue: https://github.com/WordPress/gutenberg/issues/46859#issuecomment-1712445783

**Comment by andrewserong** [comment]
Thanks for opening this Rich! I'll look into a follow-up.

**Comment by jameskoster** [comment]
We probably need to consider both clear and reset:

– Clear removes the image, IE `background-image: none`.
– Reset removes the locally set image if there is one and the default from global styles (if there is one) is inherited.

If a background image is applied globally and locally, then its conceivable that there should be separate clear/reset actions when editing in the local context.

**Comment by richtabor** [comment]
> the default from global styles (if there is one) is inherited.

I wouldn't think this would be common (or likely even?).

**Comment by richtabor** [comment]
Or perhaps "Remove" covers both bases. 

 It removed _this_ application of image (or even color, font, duotone, etc). It just falls back to whatever is in global styles, not background-image: none, just like color does.

**Comment by jameskoster** [comment]
> I wouldn't think this would be common (or likely even?).

Probably not common, but if it is made possible to add a background image globally then we need to consider it.

A single "Remove" could work. First click would reset to global default, a second click would effectively set `background-image: none` locally. Not sure if the extra click is a deal-breaker.

I figured it'd make sense to plot the patterns proposed in https://github.com/WordPress/gutenberg/issues/49278 against this use case and here's what we get:

<img width="1226" alt="bgimage" src="https://github.com/WordPress/gutenberg/assets/846565/431cf171-8666-430e-8dc0-c30809845a83">

I reckon this works well, though I acknowledge we're not quite ready to implement it yet.

**Comment by richtabor** [comment]
> Probably not common, but if it is made possible to add a background image globally then we need to consider it.

I don't think it should tbh. 

"Reset" and "Clear" are similar enough that most folks won't understand the nuance here (we use both inconsistently already). And that exposes functionality we don't support elsewhere — i.e. if you set a background color to the group block, you can't simply "remove" that color in the editor.

**Comment by andrewserong** [comment]
Good discussion, folks! Over in #54341 the proposed code change is to clear out the local background image via the Reset menu item, but without imposing any `background-image: none` kind of rules. I imagined we'd look at the nuance of overriding / clearing out things set in global styles for if and when we implement background images in global styles, which is probably a little further off (e.g. after WP 6.4).

**Comment by richtabor** [comment]
> Over in https://github.com/WordPress/gutenberg/pull/54341 the proposed code change is to clear out the local background image

And just to be clear (pun unintended, but welcomed), that's with a proposed label of "Reset"?

**Comment by andrewserong** [comment]
> And just to be clear (pun unintended, but welcomed), that's with a proposed label of "Reset"?

I just realised I used the word "clear" in my sentence, too! 😆

Yes, that PR is with the proposed label of "Reset" 🙂

**Comment by jameskoster** [comment]
> "Reset" and "Clear" are similar enough that most folks won't understand the nuance here 

Then we should make that nuance clearer (continuing the pun). If you've added a background image to a group locally then these are both valid actions:

* I want this group to have no background image.
* I want this group to use the default background image.

We could make it sequential, IE the first "reset" resets to the global default, and a subsequent "reset" sets background-image: none. I'm not a big fan because removing takes so many more clicks, but it's an option.

Alternatively the labels could be more explicit. Perhaps "Reset to default" (which is only available when there _is_ a default) and "Remove"?

> And that exposes functionality we don't support elsewhere — i.e. if you set a background color to the group block, you can't simply "remove" that color in the editor.

Color is a bit different because you can effectively 'remove' a background color by setting the transparency to 0. I suppose you could upload a transparent background image to fudge `background-image: none;` but that's not very intuitive 😅
