### ISSUE TITLE
The post author does not show up, nor is selected in the sidebar controls

### ISSUE THREAD

**Issue by Sisanu** [WordPress/gutenberg#54326]
### Description

The post author does not show up, nor is selected in the sidebar controls

### Step-by-step reproduction instructions

1. Create a post with user 1
2. Open the post with user 2 or admin
3. The sidebar author dropdown shows selected the current user
4. The sidebar author dropdown does not include user 1 in the list of options
5. The author is shown correctly in the "quick edit" dialog, but not in the "edit post"

### Environment info

- Core 6.3.1
- PHP 8.0.22

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report, but I did not replicate it. I tested with the steps below.

- Create two users with Editor role (Editor 1, Editor 2)
- Log in as "Editor 1" user and publish a post
- Log in as "Editor 2" user and open the post
- Check the sidebar author dropdown

Could you tell me what roles you applied to the user you created?

![dashboard](https://github.com/WordPress/gutenberg/assets/54422211/dd28acce-e865-4658-8259-17b8f51ce285)

![editor](https://github.com/WordPress/gutenberg/assets/54422211/87a93905-0e88-417c-849e-6c0dbdada6ae)

**Comment by Sisanu** [comment]
Hi! Thanks for looking into this. Try changing the role for the user that created the post. When you open the post again, it does not show who created it, and also when you save the author user is lost.

**Comment by t-hamano** [comment]
> Try changing the role for the user that created the post. When you open the post again, it does not show who created it, and also when you save the author user is lost.

I tried the following steps, but I still couldn't reproduce it. Am I missing something?

- As admin user, create two users with Editor roles (Editor 1, Editor 2)
- Log in as "Editor 1" user and publish a post
- Log in as "Editor 2" user
- Open the post created by "Editor 1":  ✅All users are displayed correctly
- Log in again as admin user
- Change "Editor 1" role to Author
- Open the post created by "Editor 1": ✅All users are displayed correctly
- Log in as "Editor 2" user
- Open the post created by "Editor 1": ✅All users are displayed correctly

**Comment by Sisanu** [comment]
Editor 1 creates the post. Then editor 1 is demoted to subscriber for example. When you are an admin and edit the post that editor 1 created, editor 1 is not in the list and when saving the post the admin becomes the author of the post, which is not correct. 

As far as I recall, the only place where an admin takes over the posts of other users is when the user account is deleted, mostly as a fallback, but authorship should not be removed in the workflow because of the user role change.

To avoid this, perhaps the author dropdown needs to have all users with edit post capabilities plus the current post author.

**Comment by t-hamano** [comment]
@Sisanu Thank you for explaining in detail.

> Editor 1 creates the post. Then editor 1 is demoted to subscriber for example. When you are an admin and edit the post that editor 1 created, editor 1 is not in the list and when saving the post the admin becomes the author of the post, which is not correct.

With these steps, I was able to reproduce the problem. If I enable the Classic Editor plugin, all users will be visible, even if the user who created the post has been demoted to subscriber.

> To avoid this, perhaps the author dropdown needs to have all users with edit post capabilities plus the current post author.

I think this approach is probably correct. Posts that have _already_ been created should include the user who created the post, regardless of their roles. Here's how it works in the Classic Editor:

- When an administrator creates a new post: The Author dropdown does not display users with the subscriber role
- When an administrator edits an existing post: The Author dropdown includes the user who created the post
