### ISSUE TITLE
Audio block invisible for block themes when dark mode is enabled

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#54328]
## Description

The contents of an Audio block with set media are invisible when using a block theme and enabling dark mode. 

## Step-by-step reproduction instructions

1. Enable the device's dark mode. 
2. Open the editor for a site using a block theme. 
3. Add an Audio block. 
4. Set the media for the block. 

## Expected behaviour

The block's audio file name and icon are visible. 

## Actual behaviour

The block's audio file name and icon are invisible. 

## Screenshots or screen recording (optional)

| Classic Theme | Block Theme |
| - | - |
| ![audio-block-dark-mode-classic-theme](https://github.com/WordPress/gutenberg/assets/438664/e2b0b2f0-2249-4223-8bc2-1e028da458ca) | ![audio-block-dark-mode-block-theme](https://github.com/WordPress/gutenberg/assets/438664/7cb20172-0577-47fd-898a-76dc84413e79) |

## WordPress information
- WordPress version: 6.3.1
- Gutenberg version:  16.6.0
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Twenty Twenty-Three

## Device information
- Device:  iPhone 13 mini
- Operating system:  iOS 16.6.1
- WordPress app version:  23.2

**Comment by fluiddot** [comment]
I managed to reproduce this issue in version `23.8` for a specific case ([reference](https://github.com/wordpress-mobile/gutenberg-mobile/pull/6398#issuecomment-1829687121)):
1. Go to the browser and activate `Byrne` theme.
2. Edit the Theme style and go to Styles -> Colors.
3. Check that the Background color is white (i.e. `#FFFFFF`).
4. Go to the app and ensure that the device's light mode is active.
5. Create/open a post.
6. Add an Audio block.
7. Set the media for the block.
8. Observe that the text elements are not visible.

<img src=https://github.com/WordPress/gutenberg/assets/14905380/74300c7d-9d82-46f7-ab22-be3e6f0fcad2 width=300>

If I change the background color to any other color the solution incorporated in https://github.com/WordPress/gutenberg/pull/55627 works.

| Background color #FFFFFF | Background color #FFFFFE | Background color ##000000 (with text color set to white) |
|--------|--------|--------|
| <img src=https://github.com/WordPress/gutenberg/assets/14905380/74300c7d-9d82-46f7-ab22-be3e6f0fcad2 width=300> | <img src=https://github.com/WordPress/gutenberg/assets/14905380/7bb9aa58-0389-4ed6-a632-fab9918c3310 width=300> | <img src=https://github.com/WordPress/gutenberg/assets/14905380/f9dfd047-1f51-4bfd-92b2-aaa45a3a4670 width=300> |

**Comment by SiobhyB** [comment]
@fluiddot, I believe this was fixed following the change in https://github.com/WordPress/gutenberg/pull/56752, which aligns with the fact that `Byrne` is a universal theme using style variables. 

Here's the before/after I'm seeing without and then with the changes from that PR:

| Before  | After |
| ------------- | ------------- |
| <img src="https://github.com/WordPress/gutenberg/assets/2998162/aedbb497-b3d5-4341-a96d-d524bb55e0a7" width="100%"> | <img src="https://github.com/WordPress/gutenberg/assets/2998162/436bc038-6193-49ca-98a8-cc42160a6e69" width="100%"> | 

I'll go ahead to close this issue again, as I believe it's resolved, but let me know if you spot other issues!
