### ISSUE TITLE
Synced pattern created with GreenShift Plugin blocks cause page unable to be saved

### ISSUE THREAD

**Issue by akhran** [WordPress/gutenberg#54325]
When a synced pattern created with GreenShift Plugin blocks is inserted into a page or post **two or more times (from the same synced pattern)**, it will cause the page or post to be unable to be saved. At times, clicking on the synced pattern will cause a crash from the editor to the dashboard with the following error:

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message

Environment: WordPress 6.3.1, GreenShift plugin 6.7

Steps to reproduce the issue:

1) Create a synced pattern with any GreenShift block.
2) Insert the synced pattern into the same page or post two or more times.
3) Click Update button. 

The save cannot be completed and if you leave the page, there is a warning that changes made may not be saved.

**Comment by t-hamano** [comment]
Thanks for the report.

I have encountered such errors in the past. The fact that there are more than two synced patterns, and that the React error with a number of 185 occurs may mean that there is a process in the block that the plugin has that causes an infinite loop.

If this problem does not occur only in the core block combination, I suggest you report it to the plugin developer.

**Comment by annezazu** [comment]
Thank you, Aki, for chiming in here. This does seem to be plugin related so I'm going to close this out as it doesn't relate to something Gutenberg can resolve.
