### ISSUE TITLE
Footnotes: writingMode (text orientation) is not visible on the front

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#54344]
### Description

When the text orientation option is enabled for the footnotes block, the style is not visible on the front, only in the editor.

### Step-by-step reproduction instructions

Activate a block theme.
The writing mode setting is disabled by default; set it to true in theme.json settings > typography > writingMode:

```
	"settings": {
		"typography": {
			"writingMode": true
		}
	}
```

Create a new post or page, and add a footnote.
Select the footnote and enable the vertical text orientation option in the typography panel.
Save and view the front.
Confirm that the text is not vertical on the front.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Do you think this can make it in for 6.4? Adding it to the triage column just in case :)
