### ISSUE TITLE
Heading block: Link color does not affect hover state

### ISSUE THREAD

**Issue by nielslange** [WordPress/gutenberg#54340]
### Description

The heading block can contain a link. Both the default and hover colors of that link can be styled using Global Styles. The default state of the link shows an underline. However, when hovering the link, the underline diapers.

### Step-by-step reproduction instructions

1. Create a test page and add the heading block to it.
2. Ensure the heading block contains a link.
3. Apply a default and a hover color to the link.
4. See that then link is underlined in the default state.
5. Hover the link and see that the underline disapears.

### Screenshots, screen recording, code snippet

![Screen Capture on 2023-09-11 at 12-43-19](https://github.com/WordPress/gutenberg/assets/3323310/0bb878c1-1e3d-4fc3-ba00-3ff5addd1a0a)

### Environment info

- WordPress 6.3.1
- Gutenberg 16.6.0
- Twenty Twenty-Three 1.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi Niels,
I don't understand; is it the link :hover color that is not working or is it the underline?

There are no text decoration options in the interface that **only** affect hover styles.

I assume, by looking at the color palette, that you are testing the feature using Twenty Twenty-Three.
In Twenty Twenty-Three, wether the link underline shows or not, is controlled in theme.json.
It is set to `text-decoration:none`  on hover and dashed on focus, and this is on purpose:

```
"link": {
				"color": {
					"text": "var(--wp--preset--color--contrast)"
				},
				":hover": {
					"typography": {
						"textDecoration": "none"
					}
				},
				":focus": {
					"typography": {
						"textDecoration": "underline dashed"
					}
				},
				":active": {
					"color": {
						"text": "var(--wp--preset--color--secondary)"
					},
					"typography": {
						"textDecoration": "none"
					}
				},
				"typography": {
					"textDecoration": "underline"
				}
			}
		},

```

**Comment by nielslange** [comment]
> I don't understand; is it the link :hover color that is not working or is it the underline?

Sorry for not being clear enough. I was indeed referring to the underline, @carolinan. Your reply explained the issue I was seeing. I should have looked up the color palette. 🙈

I'm closing this issue now, and thanks for your prompt response. 🙌
