### ISSUE TITLE
Fatal Error in PHP 8.1 when a template part reference is missing

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#54352]
### Description

Originally raised here: https://core.trac.wordpress.org/ticket/59318

If a block theme template references a template part via a template part block, but no part exists with the matching `slug`, a deprecation error occurs due to a `null` value being sent to preg replace.

In my particular case, the theme attribute was missing for unknown reasons on some templates loading the footer template part, and pages with those templates would trigger these fatal errors

**Importantly, a check for this already exists, but only runs if the site is in debugging mode.**

```php
	// WP_DEBUG_DISPLAY must only be honored when WP_DEBUG. This precedent
	// is set in `wp_debug_mode()`.
	$is_debug = WP_DEBUG && WP_DEBUG_DISPLAY;

	if ( is_null( $content ) && $is_debug ) {
```

During debugging `$content` is indeed `null` but `$is_debug` is `false`, so the failure case is unhandled and `null` is passed to `shortcode_unautop` leading to the crash

### Step-by-step reproduction instructions

Place this in a template:

```html
<!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->
```

Notice that in my situation the reason this was not working was the missing theme attribute:

```
<!-- wp:template-part {"slug":"footer","theme":"my-theme"} /-->
```

It found the template part once `theme` had been added, but it should have failed gracefully and returned blank content instead of generating PHP fatal errors.

### Environment info

WP 6.3, PHP 8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
I've done some sleuthing around this.

There are two PRs which look to contribute towards fixing this:

- Fix: https://github.com/WordPress/gutenberg/pull/54354
- Unit Tests: https://github.com/WordPress/wordpress-develop/pull/5177

These need review so I'm moving this to `Needs Review`.

**Comment by tomjn** [comment]
Just updating that this is still an issue

**Comment by annezazu** [comment]
Punting this from the 6.5 release as we are less than a week away from beta 1 and it's not clear where the associated PR is: https://github.com/WordPress/gutenberg/pull/54354 This was done after a review by the [6.5 core editor triage and tech leads. ](https://wordpress.slack.com/archives/C02QB2JS7/p1707153282702489)

**Comment by tomjn** [comment]
The summary is that the PR does what it needs to do and it makes obvious sense to add the check, but people struggled to reproduce the original error in order to test

**Comment by tomjn** [comment]
As best as I understand the bug, it can be phrased in two ways:

 - the code that load template parts _assumes_ the template was found and only handles the failure case when in debug mode, leading to a crash in production environments
 - if a template part block is missing a `theme` attribute it isn't found leading to a crash

**Comment by getdave** [comment]
> Punting this from the 6.5 release as we are less than a week away from beta 1 and it's not clear where the associated PR is: #54354 This was done after a review by the [6.5 core editor triage and tech leads. ](https://wordpress.slack.com/archives/C02QB2JS7/p1707153282702489)

Hi @annezazu. This was my fault. I believe we should attempt to resolve for 6.5. 

I have re-tested the associated PR and it appears to resolve the Issue. I have asked for a confidence check from a few folks before we merge.

Again apologies for the confusion regarding triage.

**Comment by annezazu** [comment]
Thanks for jumping back in with more context! Let's do it. This is part of the beauty of triaging is to uncover and move forward these things too.
