### ISSUE TITLE
Adding to a gallery doesn't allow me to choose from the media library

### ISSUE THREAD

**Issue by wpmark** [WordPress/gutenberg#5436]
## Issue Overview

When you click on an existing gallery, it insert a dummy image element with a plus symbol overlaid. This to me indicates the ability to add additional images to the gallery. When clicking plus I can only choose to upload media rather than select it from the media library

## Steps to Reproduce (for bugs)

1. Add a gallery
2. Select the gallery block by clicking in the block
3. Click the Plus symbol on the dummy image that is added at the end of the gallery

Default install of WordPress with 1 or 2 plugins, nothing to heavy at all. Uses the 2016 WordPress theme with no customisations outside of the customiser.

## Expected Behavior

Clicking the plus button should invoke the media modal. This happens if you click the small "Edit Gallery" pencil in the gallery toolbar. I think that these two things should do the same.

## Current Behavior

Clicking the plus asks you to choose a file from your computer to upload.

## Possible Solution

Make the plus icon on the dummy image have the same functionality as the edit gallery button.

## Screenshots / Video

![screen shot 2018-03-06 at 14 14 40](https://user-images.githubusercontent.com/2027394/37037137-8d1217e0-2149-11e8-812d-37e82397b36e.png)

![mar-06-2018 14-20-12](https://user-images.githubusercontent.com/2027394/37037595-89d0a780-214a-11e8-9b56-1a36164cf225.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
I don't think we should open the media modal when we click the `+` button. Because this allows The Gallery block to work even if the media modal is not available (Other contexts than the post editor), but maybe it makes sense to have two buttons inside this empty placeholder, a button to add from the media modal and a button to upload directly like other media blocks.

That said, I think this is low priority and I wonder if we should just close it as we're getting closer to merge proposal cc @jasmussen

**Comment by wpmark** [comment]
> but maybe it makes sense to have two buttons inside this empty placeholder, a button to add from the media modal and a button to upload directly like other media blocks

I certainly agree with that approach as, for me at least, the current solution is confusing. It took me a while to find out how to add an image from the media library.

https://markwilkinson.blog/2018/03/testing-gutenberg-on-this-blog/

**Comment by stompweb** [comment]
+1 for a change or additional button here to relaunch the modal. I actually missed the pencil edit button the first time around so I ended up removing the gallery and adding a new one.

**Comment by karmatosed** [comment]
I actually would +1 to closing this and avoid having multiple buttons, which I am not sure is any more helpful on that scale. 

I think it's a behaviour to note, but I have yet to see in testing this catch anyone. We totally can revisit anything we close and should if we get more reports. Thanks for testing and making this something thought about.

**Comment by StaggerLeee** [comment]
As it is now will end in many, many duplicate images in media library.

Maybe it is the time for core to warn Users image with the same filename already exist. And give them option to upload it with differently generated image slug, or go back and search in media library.
