### ISSUE TITLE
6.3.1 Command Palette Includes links to edit Pages even when Page Editor is unavailable

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#54364]
### Description

We've got a "hybrid theme" (uses the Block Editor for content, and has a few Template Parts, but isn't really FSE). When you access the Command Palette while editing Template Parts, it contains links to all of our Pages, as if you could edit them. Clicking on one updates the URL in the address bar as if you're going to edit the page, but since the Page Editor isn't available to us, nothing else really happens.

Example URL before clicking on a Page in the Command Palette:
subsite/wp-admin/site-editor.php?postId=ext-discovery%2F%2Fmain-post-listing-above&postType=wp_template_part

Example URL after clicking on a Page in the Command Palette:
subsite/wp-admin/site-editor.php?postType=page&postId=2612&canvas=edit

I don't think Pages should populating the Command Palette unless the Site Editor's Page Editor is in effect. (Or, it could conceivably redirect to the standard Page Editor I suppose).

I know there was some work done to remove commands that didn't make sense in https://github.com/WordPress/gutenberg/issues/52154, but these Edit Page links should probably be removed as well.

The change in URL also has the effect that, if a user refreshes the page, they once again get the dreaded: "The theme you are using is not compatible with the Site Editor" error. (https://github.com/WordPress/gutenberg/issues/52847)

### Step-by-step reproduction instructions

1. Have a theme that uses Template Parts but not FSE
2. Edit a Template Part
3. Open the Command Palette and see that individual Pages are listed in it

### Environment info

WP 6.3.1, no Gutenberg plugin. Custom hybrid theme (as described above)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thank you for the report.

I believe this issue was resolved in #53718. The individual pages are still displayed in the command palette, but the hybrid theme should take you to the `normal` page editing screen, not the Site Editor.

However, this is not part of WordPress 6.3 as it is part of Gutenberg 16.6; it will ship in WordPress 6.4.

I would like to close this issue, but if I have missed something, please let me know.
