### ISSUE TITLE
TimePicker onChange event only fires on month change

### ISSUE THREAD

**Issue by Honkitonkie** [WordPress/gutenberg#54378]
### Description

Importing the time picker [component](https://wordpress.github.io/gutenberg/?path=/story/components-timepicker--default&args=currentTime:1694210400000;is12Hour:!false)

When updating values other then the month in this component no onChange event is fired. 
The changes in time, day and year do persist after input but don't seem to fire the onChange function. 

I think this is a bug in the component or am I missing something? Hope someone can provide some perspective on this.

### Step-by-step reproduction instructions

Paste this code in an create-block edit.js file.

```
import {TimePicker} from '@wordpress/components';
import { useBlockProps } from '@wordpress/block-editor';

export default function Edit(props) {
	const blockProps = useBlockProps();
	return (
		<div {...blockProps}>
			<TimePicker
				currentDate={ new Date() }
				onChange={ ( date ) => console.log("logging here: ", date) }
			/>
		</div>
	);
}
```
Change values and check the logs. It only fires when changing the month.

### Screenshots, screen recording, code snippet

<img width="511" alt="image" src="https://github.com/WordPress/gutenberg/assets/38691523/7404ca73-87d1-484f-97c5-f5f203fea052">

![timepicker](https://github.com/WordPress/gutenberg/assets/38691523/d3b413e7-3dcc-46a6-abbc-66396d86f39f)

### Environment info

- Chrome Versie 116.0.5845.182 (Officiële build) (64-bits)
- Gutenberg 16.6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bangank36** [comment]
I can reproduce it on the Editor, only the month select fire the `onChange` event. Note that on Storybook, the events are fired correctly on all the time inputs, check the video

https://github.com/WordPress/gutenberg/assets/10071857/c10e9408-d917-4e7f-8d22-ca429a64bb29

On the editor this `event.target` check is returning false, therefore the change callback is stopped
https://github.com/WordPress/gutenberg/blob/69990115cd1cb77b5cd0071a8dfc55b6171814a3/packages/components/src/date-time/time/index.tsx#L130

cc: @ciampo

**Comment by ciampo** [comment]
Nice find!

@bangank36 or @Honkitonkie , would any of you be able to open a PR to fix this? I'd be happy to help with reviewing those changes.

**Comment by bangank36** [comment]
@ciampo I think the root cause here is the check is against `HTMLInputElement` of the parent window, not the iframe container itself, making it return false on the Editor
I made a quick test on https://github.com/WordPress/gutenberg/pull/54643 to confirm the check against iframe `HTMLInputElement` works, but I wonder if there is a way to detect if the Editor is rendered in iframe and to get the `contentWindow` of the iframe?

I also found similar issue has been asked here https://github.com/WordPress/gutenberg/issues/53867

**Comment by ciampo** [comment]
Thank you for the investigation, @bangank36 !

I opened #54669 with what should be a fix, could you both take a look?

**Comment by bangank36** [comment]
I tested the fix and it working well for me! The additional comment also make sense to explain the issue, I will close https://github.com/WordPress/gutenberg/pull/54643 in favor of your fixes
