### ISSUE TITLE
List Block: Numbering Style setting not working on Twenty Twenty-One theme.

### ISSUE THREAD

**Issue by VipulUpadala** [WordPress/gutenberg#54384]
### Description

I have tested the list block on twenty twenty-one theme and found the numbering style setting not working on it.

### Step-by-step reproduction instructions

1.  First, Active the Twenty Twenty-One theme.
2. Create a new page and take the list block.
3. Change the number list and check the numbering style setting.
4. Apply setting like "Uppercase letters", "Lowercase letters", "Uppercase Roman numerals", and "Lowercase Roman numerals" And check it not working.

### Screenshots, screen recording, code snippet

Please check the provided screen recording video below for a better understanding of the issue.

Video URL: https://share.cleanshot.com/jRFR0SjRNQF18R0k3Bp9

### Environment info

- WordPress 6.3.1 running
- Chrome
- macOS 13.2

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This would be the same problem reported in [this comment](https://github.com/WordPress/gutenberg/pull/53301#issuecomment-1664943833). I believe #53301 will resolve this issue.
