### ISSUE TITLE
"Manage My Patterns" in the Block Inserter should link to Site Editor if site is using a block theme

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#54386]
## What problem does this address?
Behavior of the different "Manage Patterns" buttons/actions is still not consistent if the site has a block theme, as it will take users to classic dashboard management screens.

## What is your proposed solution?
Change the link at **Block Inserter > Diamond-shaped icon > Manage My Patterns** to link to Site Editor > Patterns instead of `/wp-admin/edit.php?post_type=wp_block`

**Comment by annezazu** [comment]
Noting that the synced patterns section should be removed with this PR https://github.com/WordPress/gutenberg/pull/54007 making this issue void! Closing out as a result but excellent feedback to have. Thank you.
