### ISSUE TITLE
Font Library: add progress-bar while uploading font assets

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#54399]
Should we add a progress bar while uploading font assets to indicate that to users visually?

**Comment by matiasbenedetto** [comment]
@jasmussen what do you think?
If you agree could you add a mockup for this, please?

**Comment by matiasbenedetto** [comment]
Adding this ticket to Font Library [Stage 3 ](https://github.com/WordPress/gutenberg/issues/53926)planning.

**Comment by jasmussen** [comment]
Sure, could be a nice non-blocking enhancement. You could use the [ProgressBar](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-progressbar--docs).

<img width="1440" alt="spinner" src="https://github.com/WordPress/gutenberg/assets/1204802/81122d75-69ba-4e18-8fde-18db73112429">

**Comment by hbhalodia** [comment]
Hello @matiasbenedetto @mikachan @jasmussen, I have raised the PR for the same. Can you please take a look on the PR - https://github.com/WordPress/gutenberg/pull/57463

Thanks.
