### ISSUE TITLE
Font Library: show the scrollbar bottom edge

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#54401]
![image](https://github.com/WordPress/gutenberg/assets/1310626/2b230df4-ec30-4d2c-bc5d-f19dd57b5121)

**Comment by jordesign** [comment]
I'm no longer seeing this as an issue in GB 17.4.1 - so will close as resolved.


https://github.com/WordPress/gutenberg/assets/1842363/85549ad8-824f-4090-93d8-52ae5011f1ca

**Comment by matiasbenedetto** [comment]
Re-opening the ticket because I'm still able to reproduce the issue:

![image](https://github.com/WordPress/gutenberg/assets/1310626/1a224045-3872-45d3-b0f0-296070a6ff36)
