### ISSUE TITLE
Link Issue

### ISSUE THREAD

**Issue by vitalytennant** [WordPress/gutenberg#54410]
### Description

Hello,
Summation: Code and/or plugin needed to remove rel="noreferrer noopener" from links.

Detailed Issue:

Opening links in new tab/window refrains interruption of the content being read, viewed, and/or listened to.
And it is recommended to open new tabs/windows more often than not, e.g. losing reading position, interrupting AI readers, etc. Yes, it is safe to open new tab/window via _blank, additionally, it isn’t black hat, and does not carry pessimistic tendencies, as well as reference for page rank, not talking about uninterrupted SEO of direct traffic. Aforementioned is important because only 4.1 billion people use the internet, about 56.7 of global population, therefore knowing a reference is important.

How can this be remedied, by removing rel="noreferrer noopener"?

rel="noreferrer noopener" is added automatically, it is re-added (after being removed) upon saving/publishing.
Is there a code and/or plugin that works and does this?

There are references of code for functions.php and plugins that haven’t been updated in years. Code does not work, and we’re reluctant to use the outdated plugins.

Not window.opener.location issue. Any security plugin prevents this, such as CleanTalk.org, etc.

Looking forward to having this resolved.

Thank you in advance.

Best regards.

### Step-by-step reproduction instructions

1. All links with _blank experience this issue.

### Environment info

WordPress 6.3./1, etc. all latest versions, until issue is addressed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/26914. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue. 

That issue also has a comment which has a temporary workaround https://github.com/WordPress/gutenberg/issues/26914#issuecomment-1162706333 which temporarily fixes the problem if you wish.

**Comment by vitalytennant** [comment]
Hello,

Thank you for your response.

Code doesn't work.

//Removes noreferrer from new or updated posts
function my_targeted_link_rel($rel_values) {
return 'noopener';
}
add_filter('wp_targeted_link_rel', 'my_targeted_link_rel',999);

Aforementioned github reference does not address rel=”noopener”

There needs to be a permanent solution, because anyone can add rel=”noreferrer noopener” if they'd like, not the other way around.

**Comment by vitalytennant** [comment]
This can be further elaborated via [https://core.trac.wordpress.org/ticket/59333#ticket](https://core.trac.wordpress.org/ticket/59333#ticket)

"This impacts the entire wordpress opensource, and should be addressed respectively, and enhanced with either WP plugin, and/or the next WP update."

Everyone (without going into intricacies of everything) has links on their wordpress websites, this impacts everyone.
