### ISSUE TITLE
Query block enhanced pagination: additional design enhancements

### ISSUE THREAD

**Issue by luisherranz** [WordPress/gutenberg#54414]
@jasmussen shared with us some design improvements for the Query block enhanced pagination.

These should be pretty fast to do and we should be able to complete them before the 16.7 RC:

- [x] Change the modal text to: `Plugin blocks are not supported. For enhanced pagination to work, remove the plugin block, then re-enable it in settings.`
- [x] Change the modal button text to: `OK`
- [x] Change the error notice text to: `Enhanced pagination only works with the blocks bundled with WordPress. If you want to enable it, you have to remove all plugin blocks from the Query Loop.`
- [x] Remove the left/right margin of the error notice yellow box so it lines up with the text above.
- [x] Start the loading bar further to the left.
- [x] Increase the loading bar starting delay from 300ms to 400ms.

These are more complex and could be done if we have time before the 16.7 RC:

- Figure out if we can combine the focus scroll with the smooth scroll of `scrollIntoView`, but we can investigate.
- Add a “blink” the Query block in the Editor as soon as the toggle is enabled, just to provide some visual feedback in the canvas that something changed.
- Add a fading animation to the enhanced Query Loop navigation
  - https://github.com/WordPress/gutenberg/issues/54060

**Comment by jasmussen** [comment]
Thanks for capturing this! Some of these are in the suggestions/questions category, and in general there's wiggleroom here.

**Comment by luisherranz** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/54455. I've moved the remaining tasks to the tracking issue:

- https://github.com/WordPress/gutenberg/issues/54291
