### ISSUE TITLE
Classic Theme: Design => Widgets - when using "Top Toolbar" part of userinterface disappears

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#54465]
### Description

When using "Top toolbar" in Classic Theme => Widgets screen, parts of the userinterface are not visible, depending on "Show / Hide block tools"
Show: Undo, Redo and List View are gone

Having Gutenberg 16.6.0 installed:
also Update, Settings and Options are gone

### Step-by-step reproduction instructions

1. Use Classic Theme like Twenty Sixteen or GeneratePress
2. Got to Design => Widgets
3. Activate "top toolbar"
4. Select a block
5. Try to activate List View ...

### Screenshots, screen recording, code snippet

WP 6.3.1:
![grafik](https://github.com/WordPress/gutenberg/assets/32030147/e43305ab-55c8-49a7-96d0-66e5009be736)
![grafik](https://github.com/WordPress/gutenberg/assets/32030147/dd37204b-f6c9-4569-92ff-4c798410a5a3)

Gutenberg 16.6.0:
![grafik](https://github.com/WordPress/gutenberg/assets/32030147/8481aa0b-5c06-4ef4-9772-d91e34165ee5)
![grafik](https://github.com/WordPress/gutenberg/assets/32030147/0a99bca5-86b0-4a62-a151-bf9ec66bf8a0)

### Environment info

WP 6.3.1; without and with Gutenberg 16:6.0; Theme: Twenty Sixteen, GeneratePress

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This issue is fixed in ~#54372~ #54329 and will be part of Gutenberg 16.7. Please check to see if this issue is resolved when Gutenberg 16.7 is released as a plugin.
