### ISSUE TITLE
Site Editor: randomly loads blog home rather than selected template

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54479]
### Description

When trying to navigate to different templates, one randomly is presented once more with the blog home or front page template rather than the selected template, causing you to have to reselect. 

### Step-by-step reproduction instructions

1. Open the Site Editor
2. Go to templates
3. Open the blog home template.
4. Open the site view.
5. Head to Page template.
6. Notice you are shown blog home again despite selecting page. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/26996883/a96e3191-42c6-4527-9b57-478bc81357b9

### Environment info

- WP 6.3.1
- GB 16.6
- TT3
- Chrome
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I'm having trouble reproducing the issue on the trunk. Do you have a static homepage enabled from Reading Settings?

**Comment by annezazu** [comment]
I have latest posts for homepage! I can replicate with 16.6 with different templates but haven't tested against trunk yet.

**Comment by Mamaduka** [comment]
I'm unable to reproduce the issue on the trunk. Maybe there's a step I'm missing.

**Comment by annezazu** [comment]
I started with a fresh install and didn't have to do any unique steps to replicate. First reported here: https://github.com/WordPress/gutenberg/issues/54417

**Comment by annezazu** [comment]
I can no longer replicate with 16.7 RC1 so I'm going to close this out as something must have resolved it along the way 😅 

https://github.com/WordPress/gutenberg/assets/26996883/411d8b13-3763-4c11-97f6-a496d3a594b1
