### ISSUE TITLE
Don't display paragraph block colors if support is disabled and palette is empty array

### ISSUE THREAD

**Issue by maxxwv** [WordPress/gutenberg#5447]
## Issue Overview
As of now we can opt to turn off the custom color picker using 'disable-custom-colors' theme support option, as well as being able to define specific color chips to override the defaults. This is great, and thank you! However, this:

```php
add_theme_support('editor-color-palette', array(
	'colors' => [], //also tried false, just in case...
));
add_theme_support('disable-custom-colors');
```

yields this:

![color-picker-gutenberg](https://user-images.githubusercontent.com/23214346/37050008-b7bc5540-2140-11e8-8b2d-7d6ddc8ca34f.jpg)

Seems to me from an user experience perspective it'd be better not to display the option areas at all if the editor can't actually make a choice there.

**Comment by webmandesign** [comment]
Hi,

Your code will actually not work as you are passing an array argument to `add_theme_support( 'editor-color-palette', $argument )`, which is not possible currently (I've logged an issue for that: #6425).

If you want to get rid of all the colors, this seems to work for me (using Gutenberg 2.6.0):
```
add_theme_support( 'editor-color-palette' );
add_theme_support( 'disable-custom-colors' );
```

However, please note that this will not remove the color option areas from Gutenberg block settings.
And also **feels like a bug in declaring the theme support for color palette** _(&rarr; to whom this may concern)_.

Regards,

Oliver
