### ISSUE TITLE
Nested Blocks: Inner block arrangement options

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#5448]
Previously: #2995 (https://github.com/WordPress/gutenberg/issues/2995#issuecomment-336108393), #3745 (https://github.com/WordPress/gutenberg/pull/3745#issuecomment-349032768)

The [`InnerBlocks` component](https://github.com/WordPress/gutenberg/tree/master/editor/components/inner-blocks), used for block nesting, should allow a block implementer to assign a predefined block arrangement, optionally locking or otherwise restricting the types of blocks which are available for insertion in the block.

This could potentially align with existing [block templating](https://wordpress.org/gutenberg/handbook/templates/)

Pseudo-code examples:

```jsx
<InnerBlocks
	allowedBlockNames={ [ 'core/image', 'core/paragraph' ] }
	template={ [
		createBlock( 'core/image' ),
		createBlock( 'core/paragraph' ),
	] }
/>
```

For the inverse relationship (blocks restricted to certain parent contexts), we could either...

- Rely on a combination of block's `isPrivate` API (already used to omit block from inserter) and treat `allowedBlockNames` as overriding this preference
- Add a property to the block API, `allowedRootBlockNames: [ ... ]`

__Related Work:__

Discussion by @jorgefilipecosta about defining inner blocks supported:

https://wordpress.slack.com/archives/C02QB2JS7/p1520252046000229 

cc @jorgefilipecosta

**Comment by michellomp** [comment]
@aduth Is it possible to get InnerBlocks content in the edit function ? I want to add some animation on the innerblocks content something like: 
```
edit( { className } ) {
		return (
			<div className={ className }>
				<InnerBlocks />
				<ScrollAnimation animateIn="slideOutRight">
				  <InnerBlocks.Content />
			        </ScrollAnimation>
			</div>
			
		);
	},
```

**Comment by robbisy** [comment]
The InnerBlocks component [link](https://github.com/WordPress/gutenberg/tree/master/blocks/inner-blocks) are broken :

**Comment by aduth** [comment]
@robbisy The component has been moved to the editor directory. Here's the updated link:

https://github.com/WordPress/gutenberg/tree/master/editor/components/inner-blocks

(I've revised the original comment as well)

**Comment by ajitbohra** [comment]
Closing this as Nested / Inner blocks have been updated https://github.com/WordPress/gutenberg/tree/master/editor/components/inner-blocks

cc: @aduth

**Comment by jessicaplant** [comment]
Link is broken again :(

**Comment by aduth** [comment]
@jessicaplant Here's the updated link. I expect this one should remain relatively stable (famous last words):

https://github.com/WordPress/gutenberg/tree/master/packages/editor/src/components/inner-blocks
