### ISSUE TITLE
Parser: Normalize references to parsed block properties

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#5449]
We should seek to normalize values referencing to properties of the parsed block object:

- `name`
- `attributes`
- `innerBlocks`
- `innerHTML`

Current inconsistencies:

- [ ] [`getBlockContent`](https://github.com/WordPress/gutenberg/blob/7b067e9fbfeac47df716615993858ee8dc87c241/blocks/api/serializer.js#L173-L197), [`getCommentDelimitedContent`](https://github.com/WordPress/gutenberg/blob/7b067e9fbfeac47df716615993858ee8dc87c241/blocks/api/serializer.js#L199-L229)
   - Recommendations: 
      1. Rename `getBlockContent` to `getBlockInnerHTML`
      2. Rename `getCommentDelimitedContent` to `getCommentDelimitedBlockInnerHTML`
- [ ] [`serializeAttributes`](https://github.com/WordPress/gutenberg/blob/7b067e9fbfeac47df716615993858ee8dc87c241/blocks/api/serializer.js#L150-L156)
   - Recommendation:
      1. Rename `attrs` argument to `attributes`
      2. Add a JSDoc block for the function
- [ ] [Post grammar](https://github.com/WordPress/gutenberg/blob/7b067e9fbfeac47df716615993858ee8dc87c241/blocks/api/post.pegjs#L217-L218)
   - Recommendations:
      1. Rename `attrs` to `attributes`
      2. Rename `blockName` to `name`
   - Open question: Should we make the inverse normalization, `name` to `blockName` ? From context of properties of a block, the prefix seems redundant.
   - Impacts both front-end and back-end code

**Comment by draganescu** [comment]
> serializeAttributes
>
>     Recommendation:
>        Rename attrs argument to attributes
>        Add a JSDoc block for the function

This _seems_ to be the low hanging fruit in this list?

**Comment by aduth** [comment]
> This _seems_ to be the low hanging fruit in this list?

It's a pretty straight forward task, yes 👍

**Comment by paaljoachim** [comment]
I will add in a Needs Dev label here....

**Comment by paaljoachim** [comment]
I am going through older issues again. Working on whom I can ping for various kinds of issues.
@ockham Bernie is this something you might be able to look at? As Andrew @aduth is away on a longer sabbatical. Not even sure if he is coming back. Andrew has a lot of older issues that would in one way or another be good to get a resolved. Thanks.

**Comment by donnapep** [comment]
@paaljoachim I can pick this one up, assuming it's still relevant?

**Comment by paaljoachim** [comment]
Hey @donnapep 

That sounds great Donna!
I asked in the Slack Core Editor channel so that another dev can give a reply here to the relevance of the issue.

**Comment by gziolo** [comment]
Some improvements were landed in #29949. Otherwise, I'm inclined to close this issue based on the findings shared by @krfreder in #28436. It'd be too much hassle to change public APIs after several major WordPress releases.
