### ISSUE TITLE
Use Categories and Tabs in CPTs when Gutenberg Editor is disabled

### ISSUE THREAD

**Issue by levycarneiro** [WordPress/gutenberg#54499]
Scenario:
- I have a CPT for videos, with only a Title and an ACF field for the Youtube URL.
- I'm using the "CPT UI" plugin with Categories and Tags enabled for this CPT.
- And also I have "Supports = Editor" disabled as I don't need the Gutenberg editor for this particular CPT.
- The idea is to make it easy for users adding videos in the backend: they click to add a new video, enter a title, paste a URL into the ACF field for Youtube URL, pick a category and/or tabs, and publish. No need for adding Gutenberg blocks, as I have a template with Kadence that applies to all Video CPT posts, controlling the layout of these posts.

Issue:
- The Categories and Tags selector UI doesn't show when "Supports = Editor" is disabled. It only shows when "Supports = Editor" is enabled, which means the Gutenberg editor is enabled (and I don't need it for this CPT).

Request:
- Is there a way to support the Categories and Tags selector UI when the Gutenberg editor is disabled?

Thanks!

**Comment by Mamaduka** [comment]
Hi, @levycarneiro

If you mean Category and Tag selector from the block editor, then - no. Those components are part of the editor and can't be rendered separately.

The classic editor also has panels for Categories and Tags; if they aren't displayed, there might be a misconfiguration in the CPT UI plugin. I would recommend contacting them in [support forums](https://wordpress.org/support/plugin/custom-post-type-ui/).

**Comment by levycarneiro** [comment]
Thanks very much @Mamaduka !

**Comment by levycarneiro** [comment]
Problem solved:
- there was a custom css code in the child theme, hiding the categories/tags panels.
