### ISSUE TITLE
Update SearchControl to include size option

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#54501]
<img width="865" alt="Search" src="https://github.com/WordPress/gutenberg/assets/846565/a0105b65-f3d0-4683-b8fb-5ce1703aa457">

It would be nice to update the [SearchControl](https://wordpress.github.io/gutenberg/?path=/docs/components-searchcontrol--docs) component so that it offers size options like [InputControl](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-inputcontrol--docs) and [SelectControl](https://wordpress.github.io/gutenberg/?path=/docs/components-selectcontrol--docs).

Currently the search input is a static 48px tall. This is inconsistent with all inputs which are gravitating towards a 40px default (see https://github.com/WordPress/gutenberg/issues/46741).

The designs for updated tables in the site editor (https://github.com/WordPress/gutenberg/issues/53233) call for a smaller search input (32px) tall. 

Ideally the sizes would be:

* Default: 32px
* Large: 40px

We might consider a `small` variant too, though there's no immediate need for it.

**Comment by ciampo** [comment]
> Ideally the sizes would be:
> 
> Default: 32px
> Large: 40px

Shouldn't `40px` be the default size, and `32px` and small/compact size? That would align with the work we've been doing with all other control components.

**Comment by jameskoster** [comment]
Sure, that works :)
