### ISSUE TITLE
Add DocumentActions to Style Book

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#54514]
As discussed in https://github.com/WordPress/gutenberg/issues/51667#issuecomment-1598801110, lets add the `DocumentActions` to the Style Book editor header. 

### Before: 
<img width="1389" alt="CleanShot 2023-09-15 at 15 45 39" src="https://github.com/WordPress/gutenberg/assets/1813435/6158c428-b2e4-4ec1-835c-a9649524300e">

### After: 
<img width="1515" alt="CleanShot 2023-09-15 at 15 46 03" src="https://github.com/WordPress/gutenberg/assets/1813435/5b522ab4-4efa-41dc-8257-75511c538e54">

Related issue for Style Revisions: https://github.com/WordPress/gutenberg/issues/51667

**Comment by richtabor** [comment]
It would also have the "Back" button at the left, to go back to the previous view.

**Comment by youknowriad** [comment]
At one point should we consider this view "style book" as opening the "global styles" entity in the editor. Similar to how we open a "page", a "post", a "pattern" or "template part". 

This would make the "back" button (focus mode) and the action bar work. 

It might have side effects elsewhere though (save buttons and such)

**Comment by youknowriad** [comment]
The other noticeable impact such a change makes is that it will also change the "document" panel and its content in the "settings" sidebar. That said, currently it's not possible to open that sidebar while the style book is open. 

I actually wonder if it's a better modal to avoid having a separate "global styles" sidebar and instead just use that "document" panel as the global styles sidebar. I think it would be a better model (mental model that can translate to a UI model) but granted that it might be a bigger change.

**Comment by creativecoder** [comment]
I'm exploring a fix for this and https://github.com/WordPress/gutenberg/issues/51667 over in https://github.com/WordPress/gutenberg/pull/62669.

I didn't take on any refactoring, instead trying to resolve this issue with minimal changes while trying to not make anything worse for when we eventually rework how Style Book/Revisions UI is loaded.

**Comment by creativecoder** [comment]
Resolved by #62669
