### ISSUE TITLE
Post terms block: Missing options for prefix and suffix when there are no terms

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#54523]
### Description

Update: to clarify, I mean the post terms block with variations, not the "categories list" block.

When you add the post terms block, AKA categories block or a variation of the categories block, such as tags, a custom taxonomy or the new pattern categories, there is no way to add a prefix or suffix if the current post does not have these taxonomy terms.

For example, if you have a custom taxonomy on your site, and you are editing an archive template with a query loop block,
then you can't add a prefix or suffix if there are no items **in the editor query block preview** that has that taxonomy.

Or maybe this is clearer:
If your site has 10 posts, your query block shows 3 posts in the editor, and none of those 3 posts has tags, then you can't add the prefix or suffix to the tags block variation in the post template block.

### Step-by-step reproduction instructions

In the block editor, create a new post and add a category.
Add a categories block. Duplicate it and transform it to the tag variation.

Select the categories variation (the default), either by keyboard or mouse, and confirm that it has options for prefix and suffix:
<img width="162" alt="Categories block with options for entering a text before and after the category name" src="https://github.com/WordPress/gutenberg/assets/7422055/7b79366a-b1bd-495b-b646-e5a8c5e0314d">

Now select the tags variation (click on the text "No tags") and confirm that it shows that it does not have the same options.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jorgefilipecosta** [comment]
Hi @carolinan, thank you for bringing this issue to our attention. I have tried to replicate the problem, but it seems to have been resolved now. Can you please confirm if it's fixed?

**Comment by carolinan** [comment]
I am not able to reproduce the problem. I only tested on 6.6 RC 1 with and without Gutenberg trunk.
