### ISSUE TITLE
"Pattern categories" taxonomy is available as a Categories block variation

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#54524]
### Description

Pattern categories are available as a Categories block variation.
I wonder if this is on purpose, what would the use case be for printing a pattern category in the editor and front?

### Step-by-step reproduction instructions

Create a new post or page.
In the canvas, start typing /cat: Confirm that pattern categories show up as a shortcut.

Insert a categories block.
In the block sidebar, confirm that "Transform to variation" includes pattern categories.

### Screenshots, screen recording, code snippet

<img width="281" alt="pattern categories in inserter" src="https://github.com/WordPress/gutenberg/assets/7422055/25205457-96aa-4c3c-8a63-c66d6a7b72da">

<img width="306" alt="Pattern categories in the transforms dropdown" src="https://github.com/WordPress/gutenberg/assets/7422055/a5a7a10f-1e55-4052-b38d-52b08c214ebd">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Also when there are no pattern categories the default text is "No tags".

**Comment by glendaviesnz** [comment]
This is just accidental as the post term block was just grabbing every built in taxonomy as a variation. There is a [PR here](https://github.com/WordPress/gutenberg/pull/54532) to fix this.
