### ISSUE TITLE
Quote: Not possible to paste in citation

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#54538]
### Description

It's not possible to paste text in the quote block citation area.

### Step-by-step reproduction instructions

1. Copy a text
2. Try to paste it in the citation

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/17861443/b50db3ba-1166-4953-9a96-b9fc2785e0be

### Environment info

- WP 6.3.1.
- GB 16.6.0

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
@t-hamano, @ellatrix, I vaguely remember that this issue got fixed. Can you confirm?

**Comment by hanneslsm** [comment]
It's also possible to paste text in the pull quote block.

**Comment by t-hamano** [comment]
This issue was caused by #48254. After exploring various solutions, #54301 has been submitted which reverts the changes.

From what I've tested, merging #54301 should resolve this issue.

**Comment by t-hamano** [comment]
P.S. A similar issue was also reported in #53422.

**Comment by hanneslsm** [comment]
Arigatou!
Will close as duplicate.
