### ISSUE TITLE
Pullquote block text colour is not displaying properly on the back-end & front-end with the Twenty Nineteen theme

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/gutenberg#54530]
### Description

Hello Team,

I have worked on Gutenberg blocks and found that the "Pull Quotes" block text colour displays differently for both the back-end and front-end.

Here, I have attached screenshots:

**Back-end**

![back-end-img](https://github.com/WordPress/gutenberg/assets/53076293/6f6201d0-5d42-48eb-9472-e676693ceaec)

**Front-end**

![front-end-img](https://github.com/WordPress/gutenberg/assets/53076293/414f2850-535e-456e-839c-e25888f065f7)

Thanks,

### Step-by-step reproduction instructions

- Download the Twenty Nineteen theme and active this theme
- Type / to choose a block
- Select **Pullquote** block
- Add quote text
- Change text colour using the block setting "Color" from the right sidebar
- Save the changes and publish the page.
- Then open the page "**Preview in new tab**"

### Environment info

- WordPress version: 6.3.1, Gutenberg 16.6.0, Theme active: Twenty Nineteen(Version: 2.5),
- Browser: Google chrome, Version 116.0.5845.179 (Official Build) (arm64)
- Device: MacBook Air M1
- OS: macOS 13.5.2 (22G91)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I think this is an issue that should be resolved by the theme side. Also, there is a ticket on Trac reporting the same issue, so I would like to close this issue.

https://core.trac.wordpress.org/ticket/58171
