### ISSUE TITLE
API makes an assumption about endpoints

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#5453]
## Issue Overview

Gutenberg makes an assumption that data is coming from endpoints that look like `wp/v2/[endpoint]` originating from the same server. This is how the default wordpress rest api works, however not all installations are the same.

For my use case, we need to send requests to `public-api.wordpress.com/wp/v2/sites/[blogid]/[endpoint]`

The URL is easy enough to override since there exists a `rest_url` filter. However, the `wp/v2/` part which is referred to as the versionString does not have a filter. 

## Possible Solution 

I have submitted a core ticket (<a href="https://core.trac.wordpress.org/ticket/42807">#42807</a>) to add a filter for the versionString, but there is no consensus that this is a good approach.

If a filter existed for versionString in core, I could than use it to set to `wp/v2/sites/[blogid]` as `wpApiSettings.versionString` and then use that variable throughout Gutenberg.

This solution works, I'm running it with a modified core which includes the patch and a forked Gutenberg which replaces all instances of `wp/v2/` with our variable.

I'm open to other suggestions or solutions.

**Comment by rmccue** [comment]
FWIW, this is really a misuse of the REST API by WP.com, as both `namespace` and `endpoint` are not intended to be modified. As mentioned on the core ticket though, that ship has mostly sailed. I don't think Gutenberg needs to handle this in a generic way, but can rather just use a special case for this.

**Comment by mkaz** [comment]
I've boiled down this issue to this one change in `components/higher-order/with-api-data/index.js`

The mapping of the path being requested doesn't match the schema being provided, since the schema and requests are so tied to the endpoints directly, finding routes don't quite work as maybe it should.

I'm fine with skipping the filter and versionString stuff all together, I just need to set a variable which I can do easily with an inline script. I just need to be able to replace the path to be able to match to the schema. 

```
path = path.replace( `wp/v2/`, wpApiSettings.versionString );
const route = getRoute( this.schema, path );
```

thoughts?   cc: @aduth

**Comment by danielbachhuber** [comment]
Related #3462

**Comment by danielbachhuber** [comment]
@mkaz Is this issue still relevant, per https://core.trac.wordpress.org/ticket/42807#comment:12?

I agree with the consensus on the ticket: WordPress.com should change its implementation. I think this use-case would be difficult to support 100% accurately within Gutenberg; I can see the implementation breaking in a variety of ways.

**Comment by mkaz** [comment]
@danielbachhuber I basically implemented the above work around in an internal fork of Gutenberg so it modifies the path on the fly, so yes it is still relevant, but no not a blocker. Just an annoyance to merge things in every release.

It still seems like the versionString shouldn't be hard-coded everywhere, but :man_shrugging: 

I closed the core ticket, so might as well close this one out too.
