### ISSUE TITLE
Code: Unable to style the code block

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#54540]
## What problem does this address?
I am trying to style the code block. Background Color "ivory". No border. Custom border radius.

This is in my theme.json:
````
  "styles": {
    "blocks": {
      "core/code": {
        "border": {
          "radius": "6px",
          "top": { "width": "0px" }
        },
        "color": {
          "background": "ivory"
        }
      }
    },
````
Somehow the styles from the theme.json get overwritten and I am not able to style the code block via the theme.json

<img width="874" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/07560207-27b9-45a6-b0bb-02855f70eb55">

Is this a bug? Am I missing something here?
Any help is very much be appreciated.

Also, I find the `"top": { "width": "0px" }` to remove the default border not very elegant. Is there a better way?

## Environment info
Custom theme created with Create Block Theme plugin
WP 6.3.1
GB 16.6.0

**Comment by Kotaro-Kitamura** [comment]
I edited theme.json from Theme File Editor of WordPress 6.5.2, GB version: 18.1.2, Twenty Twenty Four, and edited the corresponding part, and the background color change was reflected without any problem.
![2024-04-24 20 44の画像 (1)](https://github.com/WordPress/gutenberg/assets/73454265/f29ee21c-29a0-4c39-b21e-5314aa4b2619)
![2024-04-24 20 44の画像](https://github.com/WordPress/gutenberg/assets/73454265/7f312303-ecec-444e-a3c6-9d83d9fa17b2)

**Comment by t-hamano** [comment]
@hanneslsm 

Sorry for the late reply.


This problem does not seem to be reproducible in WP6.5 or the latest Gutenberg.

![code-block](https://github.com/WordPress/gutenberg/assets/54422211/e32f82aa-76cf-41ac-abd9-8f9b7a0c1a16)

The theme.json I used for testing is below.

```json
{
	"$schema": "../../schemas/json/theme.json",
	"version": 3,
	"settings": {
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		}
	},
	"styles": {
		"blocks": {
			"core/code": {
				"border": {
					"radius": "6px",
					"top": {
						"width": "0px"
					}
				},
				"color": {
					"background": "ivory"
				}
			}
		}
	}
}
```

I would like to close this issue, but if the problem still exists, please feel free to comment.
