### ISSUE TITLE
Home key places cursor at end of previous block, not start of current block

### ISSUE THREAD

**Issue by rmccue** [WordPress/gutenberg#5455]
(Using Gutenberg 2.1.0.)

## Issue Overview
Using Home (Cmd-Left on Mac) takes you to end of the previous block, rather than the start of the current block. (The same problem occurs in reverse with End or Cmd-Right moving to the next block rather than the end of the current block.)

## Steps to Reproduce (for bugs)
Using Firefox 59b on macOS 10.12.

1. Create two paragraph blocks with some text.
2. Place your text cursor on the first line of the second block.
3. Press Home (or Cmd-Left on Mac)

## Expected Behavior
Cursor should move to the start of the current block.

## Current Behavior
Cursor moves to the end of the previous block.

**Comment by mtias** [comment]
This seems to be working well for me now:
* Cmd-Left goes to beginning of line.
* Cmd-Up goes to the start of the block.
* Cmd-Down goes to end of block.
