### ISSUE TITLE
Pullquote: Unable to style the pullquote block

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#54554]
### Description

This is the same issue as for the Code block: https://github.com/WordPress/gutenberg/issues/54540
The settings from the theme.json are overwritten by the default styles

### Step-by-step reproduction instructions

1. Create a new theme
2. Try to style the Pullquote block

### Screenshots, screen recording, code snippet
````
      "core/pullquote": {
        "border": {
          "bottom": {
            "style": "none",
            "width": "0px"
          },
          "left": {
            "style": "none",
            "width": "0px"
          },
          "right": {
            "style": "none",
            "width": "0px"
          },
          "top": {
            "style": "none",
            "width": "0px"
          }
        }

````

<img width="1642" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/ec84a68b-8bd2-42d3-a2c1-1c0c6428da70">

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by hanneslsm** [comment]
~~The `cite` element gets also overwritten in the pullquote (works in the block quote block)~~
Scratch that. It's possible to style the cite when not using the global one but the one within the pullquote.
<img width="2541" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/04ef82b9-98b6-4e00-b552-50995760e4b5">

**Comment by hanneslsm** [comment]
I managed to remove the top and bottom border in the theme.json by adding
````
        "border": {
          "style": "none !important"
        },
````

Would be nice, if the `!important` wasn't needed in a theme.json, especially because it removes the possibility to add later custom borders via the UI.

**Comment by ramonjd** [comment]
Is this related to

- https://github.com/WordPress/gutenberg/issues/56628?

**Comment by t-hamano** [comment]
@hanneslsm

Sorry for the late reply.

This problem does not seem to be reproducible in WP6.5 or the latest Gutenberg.

WP6.5:

![pullquote](https://github.com/WordPress/gutenberg/assets/54422211/961cee27-04bf-45c7-9545-4f092adadb85)

Latest Gutenberg:

![pullquote_gutenberg](https://github.com/WordPress/gutenberg/assets/54422211/0e842ff8-8aac-47ea-87e7-844e06c2cdf9)

The theme.json I used for testing is below.

```json
{
	"$schema": "../../schemas/json/theme.json",
	"version": 3,
	"settings": {
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		}
	},
	"styles": {
		"blocks": {
			"core/pullquote": {
				"border": {
					"bottom": {
						"style": "none",
						"width": "0px"
					},
					"left": {
						"style": "none",
						"width": "0px"
					},
					"right": {
						"style": "none",
						"width": "0px"
					},
					"top": {
						"style": "none",
						"width": "0px"
					}
				}
			}
		}
	}
}
```

I would like to close this issue, but if the problem still exists, please feel free to comment.
