### ISSUE TITLE
Fonts Manager: inconsistent results for installed fonts

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54568]
When testing out the fonts manager using the [Gutenberg nightly plugin](https://github.com/bph/gutenberg/releases/tag/16.8.-nightly) as part of the next call for testing for the FSE Outreach Program, I found that after installing two different fonts (Inclusive Sans and Poppins), the results for what's available in the font library varied from no new fonts added, one visible, and both visible. It seems to happen after I use one of the new fonts in Typography:

https://github.com/WordPress/gutenberg/assets/26996883/66af9df2-7bd4-479c-95ca-f9b9612bda4a

cc @matiasbenedetto @ironprogrammer

**Comment by matiasbenedetto** [comment]
Hi @annezazu thanks for reporting this. This seems to be related to this issue: ( https://github.com/WordPress/gutenberg/issues/54222 ). Do you remember doing something similar to what is described in the issue?

**Comment by annezazu** [comment]
Thanks for following up! How do you see it as related? I am not quite following. To be clear, I spun up a new test site and went straight to add fonts before immediately noticing the inconsistencies (no revisions, no other actions taken).

**Comment by matiasbenedetto** [comment]
> Thanks for following up! How do you see it as related? I am not quite following. To be clear, I spun up a new test site and went straight to add fonts before immediately noticing the inconsistencies (no revisions, no other actions taken).

Sorry, I misinterpreted the video. After a re-watch, I think it's unrelated to the issue I pointed out.
I think that, for some reason, the list of installed fonts is not loading as expected in this case.

**Comment by bph** [comment]
The Gutenberg nightly release asset of yesterday (9/18), might not have fully deployed to GitHub. There was an error message I missed on the deploy process. 

Today's build went all the way through. @anne try it again. 

--update: After some investigation, i found  the error message was just about closing the SFTP connection from my script. The release asset should have deployed correctly.

**Comment by annezazu** [comment]
Updated to the latest Gutenberg nightly and I'm still seeing issues, including not all fonts listed randomly, Poppins font not showing up correctly when selected, and when hitting "update" the saving happening in the background without clarity that saving has occurred in the modal:

https://github.com/WordPress/gutenberg/assets/26996883/3ab8f3da-7da0-48e5-b85d-f813bf3c05e6

**Comment by annezazu** [comment]
I can still replicate this with GB 16.7 RC1. It seems you need to upload some fonts and then use one in one of the top level typography options, in this case Headings:

https://github.com/WordPress/gutenberg/assets/26996883/4963d808-e74c-47bb-a369-495498371310

**Comment by ironprogrammer** [comment]
I was also able to replicate this once using the [Gutenberg nightly plugin](https://github.com/bph/gutenberg/releases/tag/16.8.-nightly) referenced above. In my case NO custom fonts were displayed -- they ALL disappeared, compared to only some in @annezazu's recording.

**However**, using GB `trunk`, I was NOT able to repro the issue across Safari, Chrome,Firefox, or [GB `trunk` Playground](https://github.com/WordPress/gutenberg/pull/54511) with lots of fiddling, including manually uploaded and Google fonts. This report looks really similar to issues reported for https://github.com/WordPress/gutenberg/pull/53884 (merged last week). The above-mentioned nightly is from September 5, so it makes sense if similar issues were now resolved. But if @annezazu is still seeing it in 16.7 RC1...🤔 Would you be able to check if there are any errors in the JS console when the issue occurs?

When I tried recording the nightly build test, I couldn't get it to repro again 🤯, but here are the steps:

## Test Report

### Steps to Reproduce
1. Using the font manager, upload a few custom fonts.
2. Click outside the modal, which closes it.
3. Re-open the font manager.
4. Disable one of the custom font's variations.
5. Click outside of the modal, which closes it.
6. Select Headings.
7. Assign a custom font.
8. Return to the main Typography screen.
9. Open the font manager.
10. 👀 Observe the display of custom fonts in the Library tab.

### Environment
- OS: macOS 13.5.2
- Browser: Safari 16.6, Google Chrome 117.0.5938.88, Mozilla Firefox 117.0.1
- Server: nginx/1.25.2
- PHP: 7.4.33
- WordPress: 6.4-alpha-56267-src
- Theme: twentytwentythree v1.2
- Active Plugins:
  - gutenberg v16.7.0-rc.1 (`trunk`) and old nightly build

### Actual Results
- ✅ Able to repro using [16.8.-nightly](https://github.com/bph/gutenberg/releases/tag/16.8.-nightly).
- ❌ Unable to repro on `trunk` (16.7.0-rc.1).

**Comment by annezazu** [comment]
No errors in console! It's very strange. I also noticed that the Poppins font doesn't quite seem to be registered as the font looks quite off compared to this https://fonts.google.com/specimen/Poppins:

<img width="967" alt="Screen Shot 2023-09-21 at 6 23 29 PM" src="https://github.com/WordPress/gutenberg/assets/26996883/2a4a9086-c2e4-49ef-b32c-0bfbc788539f">

Here's a shortened video using 6.4-alpha-56657 and GB 16.7 RC1. Super odd and very consistent. It only seems to happen after I apply a font:

https://github.com/WordPress/gutenberg/assets/26996883/74fe4f25-0f7a-4a73-adc6-cb4aa3814e91

**Comment by annezazu** [comment]
I can no longer replicate with GB 16.7 and 6.4 Beta 1:

https://github.com/WordPress/gutenberg/assets/26996883/673475ba-56ce-4fa0-9fa9-b7c1927d2104

However, I can replicate this bug https://github.com/WordPress/gutenberg/issues/54706 and a new one where the font description changes weight depending on which fonts you activate/deactivate (about to open). 

Going to close this out but let's see make sure it doesn't return.
