### ISSUE TITLE
Blocks: Unify UX for the core blocks that manage media files

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#5456]
## Issue Overview

The changes introduced in #5431 bring images and other media formats closer in terms of UX. However, there are a couple of things we could further improve:
* Audio & video blocks don't support drag & drop for files. I was able to add that feature with a few lines of code when doing some explorations.
* The drop area doesn't take into account media type, we would need to add this capability.
* Should it be possible to specify using an image URL similar to what we have in case of the audio or video block?
* Should we make `Edit` button work in a similar fashion for all media types?

### Audio - file selected
![screen shot 2018-03-06 at 10 24 47](https://user-images.githubusercontent.com/699132/37024295-b309420a-2128-11e8-9114-27e25083dc3e.png)

### Audio - editing

![screen shot 2018-03-06 at 10 24 54](https://user-images.githubusercontent.com/699132/37024296-b32900fe-2128-11e8-8a8a-9e26236590d8.png)

### Gallery - files selected
<img width="1093" alt="screen shot 2018-03-07 at 06 23 35" src="https://user-images.githubusercontent.com/699132/37075120-85813358-21d0-11e8-841e-4ed9a1d3f88d.png">

### Gallery - editing
<img width="898" alt="screen shot 2018-03-07 at 06 24 27" src="https://user-images.githubusercontent.com/699132/37075073-4e83cfa0-21d0-11e8-8999-c1359c22ef5f.png">

### Video - file selected
![screen shot 2018-03-06 at 10 25 07](https://user-images.githubusercontent.com/699132/37024297-b34c86dc-2128-11e8-8b57-b99f9a967ef2.png)

### Video - editing
![screen shot 2018-03-06 at 10 25 15](https://user-images.githubusercontent.com/699132/37024298-b3680d80-2128-11e8-9638-474fa14ef580.png)

## Related Issues and/or PRs
#5431

**Comment by karmatosed** [comment]
Thanks for looking into this it's so great to do unification like this.

> Audio & video blocks don't support drag & drop for files. I was able to add that feature with a few lines of code when doing some explorations.
> The drop area doesn't take into account media type, we would need to add this capability.

Let's have all support drag and drop, that's awesome.

> Should it be possible to specify using an image URL similar to what we have in case of the audio or video block?

Yes, it should and I think that unifies. It was something requested but closed because of time. If we have time this is amazing!

> Should we make Edit button work in a similar fashion for all media types?

Yes, more unification the better!

**Comment by GeekZebre** [comment]
I make an example. What do you think ?
![exemplemediaplaceholder](https://user-images.githubusercontent.com/30160793/37644004-999f580e-2c22-11e8-9c3e-91db339d9228.jpg)

**Comment by GeekZebre** [comment]
For the utility of the "Edit Button" -> my question is : 
What is the difference between : 
 - block not selected
 - block selected
 - block in edit mode ?

**Comment by karmatosed** [comment]
@GeekZebre thanks for taking a look at this. I don't think that having the large buttons and everything centered improves things though. In your visual example scanability is very difficult so let's look at how we can have unifying of the elements but not neutralise everything visually. In this case we are talking about unifying functionality over the design.

**Comment by karmatosed** [comment]
I have done some work on this to just make them all similar. One note I think is that with regards to unifying editing, lets make video and audio go to the media library, that seems a solid consistency.

![artboard](https://user-images.githubusercontent.com/253067/37799808-c344645e-2e18-11e8-80ff-dc33dfbe5680.png)

**Comment by ahmadawais** [comment]
@karmatosed  I think we should have three buttons

1. Upload
2. Add from media
3. Add External image → on click it opens up an input box to fill in the URL.

**Comment by gziolo** [comment]
> Add External image

`Add from URL` - might fit better. Good idea BTW. It might be a better idea to design it as editable inline because you will have to be able to update it later.

**Comment by karmatosed** [comment]
@ahmadawais I have 3 buttons there, so wonder what you mean could you clarify?

@gziolo I . think 'Add' even maybe?

**Comment by karmatosed** [comment]
@ahmadawais feel free to just do a sketch if you want to visually show, it's easier than sharing files.

**Comment by ahmadawais** [comment]
@karmatosed I think I'll do better with a template. PSD preferred, but I can do it via Sketch (the software) as well. 

But here's it. I gave a rough try to the image above with three suggestions I could come up with.

### ⚡ Suggestions

1. Use three buttons and show the text input area on the button click
2. Show the input at all times but with the least priority at the end
3. Don't show the third button just an input area of external images (Press Enter to add UX)

👇Here's what I came up with.

![image](http://on.ahmda.ws/qQz8/c)

Looking forward!

**Comment by karmatosed** [comment]
Thanks @ahmadawais for those. That's totally what I was thinking, so thanks for confirming that. I'll go through each to let you know what I feel and at the end I have a mock that I want us to go with I've done.

Option 1: I feel having 3 buttons and lack of discoverability could cause issues here. It's a pattern we're seeing people want of an input field and removing that in this case isn't a good option. I also feel hiding an input behind a button may raise some accessibility, also usability concerns.

Option 2: This seems like something we want to avoid having all the actions and then a button also for the same input exposed. If the action is after in this case having a button after makes more sense.

Option 3: Not having a button, whilst this works well for things like searches, in this case it may cause more issues than solves. We also may be going against existing patterns and causing accessibility problems.

One thing that Option 3 confirms is what I suggested about the priority, let's do my suggestion on that and based on that @gziolo let's go with this:

![37799808-c344645e-2e18-11e8-80ff-dc33dfbe5680](https://user-images.githubusercontent.com/253067/37877659-50631ab2-3056-11e8-9272-e19abdaab7a1.png)

**Comment by ahmadawais** [comment]
@karmatosed Glad you liked it. I strongly feel that above mockups are wrong. 

#### REASONS:

- It looks and feels like a user needs to enter the URL in the input field and then use the upload button below it to upload that external image (obv. wrongfully)
- Also having the input above normal upload buttons is a bit weird, most users I know upload images in their WordPress sites instead of including from an external resource. The external resource should come after the internal media lib upload buttons.

Just me two cents.

**Comment by karmatosed** [comment]
@ahmadawais I am totally happy to scale back and not do any reversing of inputs, this totally aligns more with the 'scale back and iterate', after all this issue was about unifying not changing the experience. I stand by my comments on your mocks which have also some of the issues you outline in your first point. That all said, apologies for going back and forth @gziolo can you please go with:

![37799808-c344645e-2e18-11e8-80ff-dc33dfbe5680 1](https://user-images.githubusercontent.com/253067/37880138-d6c5e452-307b-11e8-8f87-6a18a2e19d05.png)

Let's get this made up take from there, a small iteration is better in this instance.

**Comment by ahmadawais** [comment]
@karmatosed I agree with the first one and earlier there was a different image. The one where the "Enter URL" input is below the <kbd>Upload</kbd> and <kbd>Add from Media Library</kbd> buttons.

**Comment by karmatosed** [comment]
@ahmadawais yes there was for a few minutes due to uploading issues, it wasn't long but that explains the confusion, thanks.

@gziolo can you please proceed with this version:

![output](https://user-images.githubusercontent.com/253067/37901516-58610808-30e9-11e8-9cba-a780df575965.png)

**Comment by gziolo** [comment]
Awesome. Thank you all for iterating on this one. I won't be able to pick this one up until next week so if anyone else wants to apply those changes, be my guest 🥇

**Comment by karmatosed** [comment]
@gziolo could we pick this up (or anyone) and get it in as a fairly easy fix?

**Comment by gziolo** [comment]
@karmatosed, I'm working on `Pinning for plugins` and other 2.8 related tasks. It might take a week or so until I start working on this one. If anyone else wants to pick it up earlier, feel free to do so :)

**Comment by gziolo** [comment]
Closed with #6820.
