### ISSUE TITLE
Site editor: Add template replace flow to template inspector

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#54562]
Twenty Twenty-Four is exploring adding alternate template types for the home, index, single and page templates. While the effort in https://github.com/WordPress/gutenberg/pull/51477 brings alternate template selection to pages, _templates_ still do not have this capability. 

There's currently not a method for someone to swap a template directly with another templateType. 

### Current
Template swapping in the site editor, for pages: 

<img width="280" alt="CleanShot 2023-09-18 at 11 21 08" src="https://github.com/WordPress/gutenberg/assets/1813435/1ce87eef-18df-4566-9ac9-3ac3a12d47b2">

### Proposed

If there are alternative templateTypes registered for a specific template, then surface the swapping functionality in the template inspector. 

It could be in the verticalEllipsis menu (currently only there when customizations are present), or a button on the inspector, below the template's areas: 

<img width="798" alt="CleanShot 2023-09-18 at 11 38 07" src="https://github.com/WordPress/gutenberg/assets/1813435/3729633d-3ce0-4f54-93ef-6ebab0363702">

I lean towards the verticalEllipsis method, as it's more in line with what we have in pages, and doesn't make it _too_ surfaced. Eventually it'd be nice to see previews of the templates in the sidebar, but for a quick addition something like this seems simple enough.

**Comment by richtabor** [comment]
@ntsekouras pinging ya as you worked on the related PR.

**Comment by richtabor** [comment]
Example: if you wanted to use a different archive template, you can't really — unless your theme does not already have one. For example, my theme here does not have an author archives template, so I can opt to create one, and when I do I am presented with archive template types to choose from. 

I can't get back to that modal view (which could be populated with template types), to swap for another template, unless I delete the custom author archive template, and then re-add. But you can't delete a theme's templates.

![cleanshot_2023-09-18_at_15 50 32_720](https://github.com/WordPress/gutenberg/assets/1813435/23425650-bcc2-4075-9188-203c15829322)
![cleanshot_2023-09-18_at_15 51 16_720](https://github.com/WordPress/gutenberg/assets/1813435/c665a776-0932-4f06-8c78-14c720b473da)

**Comment by jameskoster** [comment]
Resurfacing the pattern modal seems like a good way to get this in quickly, and the ellipsis approach could work well 👍

I'm not 100% sure about the "Swap template" label. It's a bit different to the "Swap template" action when page editing, so I don't know that matching is helpful. It's worth noting there's a similar pattern selection modal that appears when page authoring (if the right patterns exist), and we might want to resurface that one too.

Could something more generic like "Swap design", "Swap layout", or even "Swap pattern" work?

**Comment by richtabor** [comment]
“Replace template”?

**Comment by jameskoster** [comment]
Yeah that can work. It's consistent with "Replace template part" which is a similar flow.

**Comment by luminuu** [comment]
+1 for "Replace template"

**Comment by scruffian** [comment]
I made a start on this here: https://github.com/WordPress/gutenberg/pull/54609

If anyone else wants to work on it be my guest...

**Comment by scruffian** [comment]
> If there are alternative templateTypes registered for a specific template, then surface the swapping functionality in the template inspector.

How is this achieved at present?

**Comment by scruffian** [comment]
Oh I found it, you add:

> Template Types: front-page, index, home

to a template...

**Comment by mtias** [comment]
I think ellipsis menu is super hidden. For reference, this is the design we had been working from for template parts: #44582
