### ISSUE TITLE
Indented list items within an <ol> default to <ul> list items (core/list)

### ISSUE THREAD

**Issue by SteveRyan-ASU** [WordPress/gutenberg#54577]
### Description

Indented list items within an ordered `core/list` block will default to unordered list items instead of ordered items.

- My expectation of indenting a list item within a list is that the type of list being displayed won't change from the original selection. 
- I believe this is happening because the indentation action that's being performed is to wrap the `core/list-item` block in an additional `core/list` block which, by default, is set as a `<ul>` as opposed to a `<ol>`.

### Step-by-step reproduction instructions

Step 1: Copy the following list and paste it into the Gutenberg editor.
```
- Erat convallis mattis sodales mattis vestibulum ut erat magnis blandit.
- Aptent curabitur libero vehicula dis velit vehicula vivamus aenean conubia!
- Diam malesuada lacinia litora cum dui varius elit ipsum condimentum.
- Aptent curabitur libero vehicula dis velit vehicula vivamus aenean conubia.
```
Step 2: Apply the ordered list style to the parent `core/list` block.
Step 3: Indent any of the items in the list

The item just indented should now be wrapped in a separate `core/list` block with the default setting of `<ul>` 

### wp-core ###

version: 6.3.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: local
user_count: 2
dotorg_communication: true

### wp-active-theme ###

name: Twenty Twenty-Three (twentytwentythree)
version: 1.2

### wp-plugins-active (3) ###

Gutenberg: version: 16.6.0, author: Gutenberg Team, Auto-updates disabled

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by felipevelzani** [comment]
Hi @SteveRyan-ASU, thank you for your report!

I can reproduce the issue. I found that it was already reported on https://github.com/WordPress/gutenberg/issues/45754.

I'll close it here as duplicated and we can keep up from there.
