### ISSUE TITLE
Ordered list items should have a way to unset the applied HTML `type` attribute

### ISSUE THREAD

**Issue by SteveRyan-ASU** [WordPress/gutenberg#54578]
### Description

Ordered lists produced by Gutenberg by using the `core/list` block default to a markup that looks like:
```
<ol>
   <li>List item</li>
</ol>
``` 

Upon applying a selection from the Numbering style dropdown, the HTML attribute `type` is applied to the `<ol>` block resulting in the following markup

```
<ol type="a">
   <li>List item</li>
</ol>
``` 

However, because the UI of the numbering style dropdown doesn't have a reset button or a setting for (no type) within, there is no way to "unset" this control and have it default back to the unadorned `<ol>` tag.

### Step-by-step reproduction instructions

Start by creating an ordered list from the following content.
```
Congue vitae urna augue taciti torquent venenatis phasellus donec neque.
Fusce varius congue dolor lacinia.
Himenaeos sed condimentum magna venenatis erat convallis mattis?
Sodales mattis vestibulum ut erat magnis blandit.
```

1. Publish the post or page and inspect the markup produced.
2. Apply a different setting to the `core/list` block to enforce a specific `type` attribute on the block.
3. Publish and inspect the results once again. You'll see the `type` attribute added to the `<ol>`
4. Edit the post/page again and attempt to remove that `type` attribute using the default controls.

Stuck. 🙁 

### wp-core ###

version: 6.3.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: local
user_count: 2
dotorg_communication: true

### wp-active-theme ###

name: Twenty Twenty-Three (twentytwentythree)
version: 1.2
author: the WordPress team

### wp-plugins-active (3) ###

Gutenberg: version: 16.6.0, author: Gutenberg Team, Auto-updates disabled

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.The List block's Numbering Style has been changed to the inline style instead of the `type` attribute to resolve issues reported in #54384, #52826, etc. Its PR is #53301.

This PR does not output the inline style when the default "Numbers" style is selected. This PR will be part of WordPress 6.4 or Gutenberg plugin 16.7.

I'd like to close this issue as I don't think the reported problem will occur anymore, but if there's anything I've missed, please comment.

**Comment by SteveRyan-ASU** [comment]
Thanks for the explanation and the references @t-hamano. 👍
