### ISSUE TITLE
Site Editor: Pattern Category showing up as an option to create a new template with

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54575]
With the addition of pattern categories, I noticed that there's now an option when creating a new template for "pattern category". This seems incorrect as these patterns are meant for internal usage on the site and not for a user to sort by :D 

<img width="1011" alt="Screen Shot 2023-09-18 at 3 24 04 PM" src="https://github.com/WordPress/gutenberg/assets/26996883/b17008b0-6827-4256-ae5d-77d297bac843">

cc @glendaviesnz

**Comment by aaronrobertshaw** [comment]
Thanks for flagging this issue @annezazu 👍 

This one will be fixed when https://github.com/WordPress/gutenberg/pull/54567 lands.
