### ISSUE TITLE
Swap template UX: include initial Page template option 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54572]
When writing the next call for testing for the FSE Outreach Program, I noticed that when switching templates, the Page template (the initial choice) isn't visible in the swap flow. The only way to go back to the Page Template option is to select "reset" which is confusing language when creating a page (makes me think the whole page will be reset: https://github.com/WordPress/gutenberg/issues/46859)

https://github.com/WordPress/gutenberg/assets/26996883/fd1ea166-7567-4ec0-b34f-61ecc802263a

Can we either include the Page Template as an option in the template selection modal or a clearer "reset" mechanism also within the modal? As it stands, my first instinct was there was no way to get back to the original Page Template.  @WordPress/gutenberg-design @ntsekouras

**Comment by richtabor** [comment]
In the post editor template select, there's "Default template". Perhaps changing "Reset" to reference the default template would work better? 

<img width="429" alt="CleanShot 2023-09-18 at 15 54 55" src="https://github.com/WordPress/gutenberg/assets/1813435/f346c3f9-e2a7-43c8-8eec-30b751a2e1c2">

**Comment by annezazu** [comment]
I dig that. Right now, it's just not clear how to get back if someone is trying to just explore what's available.

**Comment by richtabor** [comment]
What if "Reset" was "Default template"?

**Comment by jasmussen** [comment]
If it was default template, could it be a permanent fixture in the dropdown, and the selected template could have checkmarks next to it?

**Comment by jameskoster** [comment]
Agree that "Use default template" works better than "Reset".

> could it be a permanent fixture in the dropdown

I don't think it really needs to be – the template name is already displayed as the button label. That label might communicate when the default template is in use though, e.g.:

> Template: [Single Post (default)]

**Comment by annezazu** [comment]
+1 to default template and/or simply listing it in the overall modal itself where we are pushing folks to explore swapping templates.

**Comment by jameskoster** [comment]
> +1 to default template and/or simply listing it in the overall modal itself where we are pushing folks to explore swapping templates.

That would be ideal, but I think there were some gnarly prohibitive technical issues. @ntsekouras can confim.

**Comment by ntsekouras** [comment]
>That would be ideal, but I think there were some gnarly prohibitive technical issues. @ntsekouras can confim.

Yes, there is no good way currently to get the default template of a page right now. That's why we use `default template` in post editor too. I've opened a quick PR to update the copy though to `use default template` [here](https://github.com/WordPress/gutenberg/pull/54728)
