### ISSUE TITLE
Update Link Control elements & labels to use correct gray color

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#54589]
Let's update all labels and elements in `LinkControl` to use `$gray-900`.
------

I did notice that the other elements/labels are not using $gray-900 as well. May be worth a quick follow-up to do that. 

<img width="347" alt="CleanShot 2023-09-18 at 16 03 01" src="https://github.com/WordPress/gutenberg/assets/1813435/66b1a327-9630-4023-9e82-081f2d0acaca">

_Originally posted by @richtabor in https://github.com/WordPress/gutenberg/pull/54545#pullrequestreview-1631889160_

**Comment by sandnb** [comment]
Hello getdave , Can I know if anyone is working on this Issue?

**Comment by getdave** [comment]
@sandnb No one has picked it up as far as I know. Would you be open to raising a PR? 

If so then please tag myself and @richtabor 🙇

**Comment by sandnb** [comment]
Sure @getdave I would love to raise a PR on this issue and will tag you. Thank You.
