### ISSUE TITLE
REACT error: [sprintf] property "selectedCount" does not exist

### ISSUE THREAD

**Issue by pfefferle** [WordPress/gutenberg#5459]
## Issue Overview
If I hover over the editor I get the error:

![bildschirmfoto 2018-03-07 um 10 24 05](https://user-images.githubusercontent.com/2373/37084056-b96affe8-21f1-11e8-9a36-7e74d2de18eb.png)

![bildschirmfoto 2018-03-07 um 10 25 06](https://user-images.githubusercontent.com/2373/37084082-d2aa7d4e-21f1-11e8-9e21-dd54931f5f3c.png)

## Steps to Reproduce (for bugs)
1. Install Gutenberg 2.3.0
2. Go to Demo-page
3. Hover over text in editor

My system:

* WordPress 4.9.4 (german)
* MacBook Pro/macOS 10.13.3
* Safari Version 11.0.3
* Chrome Version 64.0.3282.186

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by aduth** [comment]
I'm unable to reproduce this. Can you clarify whether you have any other plugins activated on the site?

**Comment by pfefferle** [comment]
I tested it in a blank docker container with a standard WordPress installation.

It shows up, if I hover over a block:

![marz-07-2018 15-36-00](https://user-images.githubusercontent.com/2373/37098099-4b8ffe5c-221d-11e8-82e5-5cd9b4fe2fec.gif)

**Comment by pfefferle** [comment]
I could even reproduce it in a virtual box with Windows and Edge

**Comment by pfefferle** [comment]
Duplicate #5472

It seems to be a problem with the German translation!

**Comment by aduth** [comment]
The issue can be seen here:

https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/de/default?filters%5Bterm%5D=selectedCount&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

![image](https://user-images.githubusercontent.com/1779930/37099472-57015300-21ee-11e8-89a8-3952f8fb0a1a.png)

Note that the translated string includes a placeholder value which does not exist in the source string.

cc @presskopp

**Comment by aduth** [comment]
That being said, a failure to translate a string should ideally not crash the entire application.

**Comment by Presskopp** [comment]
Uh, sorry, translation corrected

**Comment by pfefferle** [comment]
Is it possible to trigger the language update, for a quick fix?

**Comment by thebugfixnet** [comment]
For german language you can go to https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/de/default and select at the bottom Export - all current - po and afterwards export the mo. Rename the downloaded files to gutenberg-de_DE.po and gutenberg-de_DE.mo and upload them via ftp to wp-content/languages/plugins

At least I can use Gutenberg again...

**Comment by Presskopp** [comment]
You can use the files inside this zip and save them to wp-content/languages/plugins

[language-files.zip](https://github.com/WordPress/gutenberg/files/1796645/language-files.zip)

**Comment by ThomasKujawa** [comment]
Thank you so much.
