### ISSUE TITLE
Support two align variations: "full-width" and "wide".

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#546]
Instead of single setting for full bleed images, it can be a "stepped" control—wide, wider, fullwidth. It needs some design work for the UI. It can work really well with galleries and hero-image.

**Comment by jasmussen** [comment]
Here are two approaches. The one literally has steps (design input appreciated, this configuration doesn't feel optimal):

![image neutral](https://cloud.githubusercontent.com/assets/1204802/25579281/c799fbb0-2e76-11e7-9c0a-bdcba3102520.png)

![image selected](https://cloud.githubusercontent.com/assets/1204802/25579282/c903baf4-2e76-11e7-82d5-bd9aa78a5034.png)

![image wide](https://cloud.githubusercontent.com/assets/1204802/25579286/cb151900-2e76-11e7-9012-76467c40071d.png)

![image fullwidth](https://cloud.githubusercontent.com/assets/1204802/25579289/cd4c6c6e-2e76-11e7-8ec2-8ebd3cf9bb3a.png)

Alternately, we add another button to the toolbar:

<img width="244" alt="screen shot 2017-05-01 at 14 01 19" src="https://cloud.githubusercontent.com/assets/1204802/25579294/d7a8b456-2e76-11e7-93ad-df19f28a9b2c.png">

👆 From left to right, that's _float left, center, float right, wide, full-width_.

**Comment by karmatosed** [comment]
Would the button in toolbar appear just for images? We are training people UI wise to expect in the toolbar, so we should as a result not change that with this UI.

**Comment by jasmussen** [comment]
> Would the button in toolbar appear just for images? 

With very few exceptions (I think List might not have any alignments in the first version) we'd have only two types of alignments: text alignments (for text specific blocks) and block level block level alignments, which you see here. 

> We are training people UI wise to expect actions in the toolbar, so we should as a result not change that with this UI.

Can you elaborate?

**Comment by karmatosed** [comment]
> Can you elaborate?

It depends where the placing is. We seem to have a training of:
- Interact with block
- Action toolbar (for want of better word) appears

If we follow that then it makes sense.

I may just need to see this in prototype as assuming from the images.

**Comment by jasmussen** [comment]
<a href="https://wpcoredesign.mystagingwebsite.com/gutenberg/#blueprints">Here's a blueprint</a> for the various terms we've dubbed. 

<img src="https://wpcoredesign.mystagingwebsite.com/gutenberg/Block%20Blueprint.png">

The toolbar docked to the block is the Quick Toolbar, and the button that would control alignment would be the Block Level Formatting group. In the blueprint it shows block level formatting for text, i.e. text alignments. But for any other block, image included, this would instead show _layout_ alignments, like float left, center, right, wide, full width.

**Comment by jasmussen** [comment]
@mtias having thought about this for a long time now, I think the best we can do here is add the extra icon:

<img src="https://cloud.githubusercontent.com/assets/1204802/25579294/d7a8b456-2e76-11e7-93ad-df19f28a9b2c.png">

It's the least mystery meat of all the solutions I've explored, and it keeps the behavior or the buttons to simply be toggles, not steppers. What do you think? I can add the dashicon real quick, then perhaps we can get in the full-bleed branch soon also?

**Comment by mtias** [comment]
And this one would be an intermediary step `wide` instead of `full-wide` which the theme would handle?

![image](https://cloud.githubusercontent.com/assets/548849/26721478/3a031b7c-478c-11e7-823a-4e71eeb150de.png)

**Comment by jasmussen** [comment]
Yes, that step would be `wide`, and 

![screen shot 2017-06-02 at 12 10 26](https://cloud.githubusercontent.com/assets/1204802/26721531/7a1a3e66-478c-11e7-88a0-92bdf3989877.png)

would be `full-wide`

**Comment by mtias** [comment]
Sounds good.

**Comment by jasmussen** [comment]
New icon upstream in Dashicons: https://github.com/WordPress/dashicons/pull/191

**Comment by jasmussen** [comment]
This is fixed in master now! 🎉
