### ISSUE TITLE
Improve interaction between protected post and block template

### ISSUE THREAD

**Issue by gigitux** [WordPress/gutenberg#54607]
## What problem does this address?

The logic for not displaying protected content in WordPress posts and pages is managed by the [`get_the_content`](https://github.com/WordPress/wordpress-develop/blob/0bfc842f807582906bc119eb62aff6bd1c1e8dea/src/wp-includes/post-template.php/#L316-L320) function. The logic is in the `Post Content` block:

| Editor | Site Editor | Frontend |
|--------|--------|--------|
| ![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/2681e141-8a04-4761-a4ad-24453016e472) |![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/08afbd92-568f-4029-8983-48f56eec1c6b)|![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/ce259a3d-0d5b-42ac-9bb3-056bfe6cccaa)| 

If the protected post has a dedicated `Single Post` block template that contains blocks that may have private information, these blocks will be visible:

| Site Editor | Frontend |
|--------|--------|
|![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/92c9685f-855a-4940-a165-8d01c7457ac6)|![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/c8f488a0-ae11-4257-850d-7a4616dcfb99)| 

## What is your proposed solution?

It is necessary to improve how the protected posts/pages are handled. It may make sense to check the protected content on the template level.

**Comment by felipevelzani** [comment]
Hi @gigitux, thank you for your report!

I see your point and understand that your proposal is for adding the single-page template non-content blocks to be part of the restricted content.

I feel like changing this would need to generally change how password protection works on WordPress as this is not specifically added by Gutenberg — I would expect the same to happen if you edit a single page on a classic theme with additional content. 🤔 

I'm closing this from here for now as I believe that it wouldn't apply to Gutenberg, but [you can create a ticket on Core Trac directly](https://core.trac.wordpress.org/).

Please feel free to reopen and reply back in case I misunderstood it somehow.
