### ISSUE TITLE
Autocorrect on android prevents enter making new paragraph blocks

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#5461]
## Issue Overview

If the last word you type in a paragraph block on android gets autocorrected when you press enter, you don't get a new paragraph block.

## Steps to Reproduce (for bugs)
1. Type some text into a new paragraph block. Make the last word something that autocorrect will replace. For example, 'thiks' gets autocorrected to 'thinks' for me.
2. Press enter.
3. Type something else and press enter again.

## Expected Behavior

We should have two paragraph blocks.

## Current Behavior

The two lines of text get combined into one line in a single block.

## Screenshots / Video

![combine](https://user-images.githubusercontent.com/3314354/37086418-6cfd4410-21ef-11e8-9e6d-19b17df10a25.gif)

**Comment by notnownikki** [comment]
The the "combined" block is left in the post, when the post is next edited it's not recognised as a block and you get a prompt to convert it to blocks.

**Comment by designsimply** [comment]
Tested and confirmed that autocorrect followed by enter then text then enter results in the following error for the block when I re-open the post for editing:

> This block appears to have been modified externally.

<img src="https://user-images.githubusercontent.com/1119271/42480734-2d9a4110-839c-11e8-8baa-13f9364ae0d3.png" width="270">
<sup>Tested with Pixel, Android 8.1.0.</sup>

**Comment by iseulde** [comment]
Enter behaviour changed it a lot in the last few releases. Could this issue be retested?

**Comment by youknowriad** [comment]
Can't reproduce this.
