### ISSUE TITLE
Patterns: no user categories in Inserter & automatically listed as both "all categories" and uncategorized

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54616]
Using Gutenberg nightly from the last 24 hours, I noticed that despite creating different categories for two patterns, they do not show up in the Inserter and, for some reason, appear as "uncategorized". This stand in contrast to this PR: https://github.com/WordPress/gutenberg/pull/53933 @glendaviesnz 

To replicate, create a few patterns and set different categories. Try then to add those to a template or page from the Inserter and notice the categories don't appear:

https://github.com/WordPress/gutenberg/assets/26996883/5a0a7847-a34b-4219-b058-543d16ce1feb

**Comment by aaronrobertshaw** [comment]
After some further testing, I found the following:

- Issue can be replicated in the site editor
- Works in the post editor
- Custom user categories have been missing in the site editor's inspector since [#53835](https://github.com/WordPress/gutenberg/pull/53835) merged

**Comment by aaronrobertshaw** [comment]
A fix is up for review in https://github.com/WordPress/gutenberg/pull/54641

**Comment by annezazu** [comment]
Boom! You all are speedy :) Thank you.
