### ISSUE TITLE
Patterns: category doesn't appear for synced patterns

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54617]
While testing the pattern categories, I noticed that the categories only appear if I create an unsynced pattern. To replicate, create a synced pattern with a brand new category and notice it doesn't appear. I am using WP 6.3.1 and GB nightly: https://github.com/bph/gutenberg/releases/tag/16.8.-nightly

https://github.com/WordPress/gutenberg/assets/26996883/67d47ffa-7c72-48d8-a6b5-5ed0e3fd975d

cc @glendaviesnz

**Comment by glendaviesnz** [comment]
Thanks @annezazu it looks like the issue is clicking on the save button straight away doesn't give the category time to save  - clicking the toggle to unsync gives enough time for the category save to happen. We will try and get this sorted.

**Comment by annezazu** [comment]
That seems to be exactly what's going on! Great sleuthing. A video for good measure: 

https://github.com/WordPress/gutenberg/assets/26996883/32a95e1a-b6a2-4b48-8c69-b08c78934aa8
