### ISSUE TITLE
Meta boxes area: remove max-width for input elements

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#5463]
In `edit-post/components/meta-boxes/meta-boxes-area/style.scss` there's a CSS rule that exclusively targets any input field within the meta boxes area:
```
.edit-post-meta-boxes-area input {
    max-width: 300px;
}
```

Plugins should be allowed to style their meta boxes content the way they want. I suggest to remove this rule because it targets all inputs elements (text, checkboxes, radio, etc.) and there's no apparent reason to limit these fields width to 300px, at the risk of potential layout breakage.

Plugins can certainly adapt and increase their CSS rules specificity to override this Gutenberg defaults, but I'm not sure there's a valid reason to keep this rule in the first place.

Example of breakage:

<img width="1117" alt="screen shot 2018-03-07 at 10 50 23" src="https://user-images.githubusercontent.com/1682452/37086345-a2aaee16-21f7-11e8-8ddf-bc74c2490caf.png">

Note: other rules set all the `input, select, textarea` in the meta boxes area to `inline-block`, and add other styling. This could potentially break the plugins meta boxes content layout and conflict with the plugins CSS but I think it should be evaluated separately.

**Comment by karmatosed** [comment]
I would +1 removing it but we should be aware if a size isn't specified then it becomes super small.

**Comment by afercia** [comment]
Yup but this is a max-width, not a min-width.
