### ISSUE TITLE
Extra spacing in Font manager

### ISSUE THREAD

**Issue by iqbalpb** [WordPress/gutenberg#54649]
### Description

Extra spacing is showing in the font manger when there is no external fonts uploaded to the font manager. After upload an external font spacing is ok or spacing issue solved.

Screenshot before uploading font:
![before uploading font](https://github.com/WordPress/gutenberg/assets/19872875/cb8ada09-bcd5-4e37-bc61-738847919b08)

Screenshot after uploading font:
![after uploading font](https://github.com/WordPress/gutenberg/assets/19872875/7359a4d1-cf00-4ea8-8c40-732a89b131f6)

Spacing difference:
![diff](https://github.com/WordPress/gutenberg/assets/19872875/4f0aca62-f90e-4993-8d66-843bbe2562a0)

### Step-by-step reproduction instructions

1. Created website using the instructions form [fse-program-testing-call-26-final-touches](https://make.wordpress.org/test/2023/09/18/fse-program-testing-call-26-final-touches/)
2. Head to Appearance > Editor > Styles > and select the pencil icon to open up the Styles panel.
3. Select Typography to view a list of active fonts and click the “Aa” icon to open up font management.
4. Upload a new font file using the drag and drop option. You can download a font from https://fonts.google.com/ [I uploaded Poppins font]

### Screenshots, screen recording, code snippet

![diff](https://github.com/WordPress/gutenberg/assets/19872875/d75cd7e3-92ed-486d-9ec5-de94f65b3611)

### Environment info

- WordPress 6.4-alpha-56628 running Twenty Twenty-Three
- Gutenberg Nightly Version 16.8.20230919 
- Device: Mac OS Ventura Version 13.5.2 (22G91)
- Browser: Safari Version 16.6 (18615.3.12.11.2)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by madhusudhand** [comment]
Duplicate of #54592

**Comment by iqbalpb** [comment]
Didn't find #54592 while searching
