### ISSUE TITLE
Navigation link variations should have type rendered

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#54668]
The Navigation link block variation (category, page, tag, post, etc) LinkControl suggestions do not have the post type rendered in each search result. 

The results are filtered by the variation, but we should still render the type—as it's expected and an helpful affordance. 

- [ ] Ensure the "type" is rendered as the search item shortcut for each nav link variation (post, page, category. etc). 

<img width="910" alt="CleanShot 2023-09-20 at 10 41 51" src="https://github.com/WordPress/gutenberg/assets/1813435/318aee80-9769-4075-b56d-60ff05c9aef0">

**Comment by carolinan** [comment]
I believe this has been solved, can the issue be closed?

**Comment by richtabor** [comment]
> I believe this has been solved, can the issue be closed?

It's still the case: 

![CleanShot 2024-02-07 at 09 00 37](https://github.com/WordPress/gutenberg/assets/1813435/15bb4038-7071-4abc-a1db-09e5a42f60d0)

**Comment by juanfra** [comment]
I was checking this one, and it looks like it has been solved. Tested with trunk. 

https://github.com/user-attachments/assets/d8ef5abb-7ac1-44d8-aa44-e6b7f95c7cb4

I'm closing this one as it's solved, but feel free to re-open if you see that there's something missing.
