### ISSUE TITLE
Link Control: selecting open in new tab option closes out the entire modal too quickly

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54672]
In testing some of the writing improvements for 6.4, I noticed that the open in a new tab control in the link preview closes out very quickly https://github.com/WordPress/gutenberg/pull/53566 ~and doesn't seem to persist~ (edit: the value _is_ persisted):

https://github.com/WordPress/gutenberg/assets/26996883/bddd6f1c-2434-45bd-a4ae-5d99fe021143

This makes for a jarring and somewhat cumbersome experience for editing links, especially if you are trying to complete a few changes to a link. I'm using 6.3.1 and GB nightly. cc @getdave and @richtabor for thoughts/replication!

**Comment by richtabor** [comment]
Yea, it's unexpected that it closes the panel. I suspect the difference is that the change is committed on the preview view, but within edit view you need to press the "Save" or "Cancel" buttons to commit.

**Comment by getdave** [comment]
From what I can see from your demo it's working as expected. I couldn't see anywhere where it is not being persisted and I've tested on `trunk` and all seems fine. If I missed something could you provided reproduction steps? 🙏 

Note that this checkbox is provided as means to quickly toggle this setting which is  something that a subset of users feel very strongly about as it's a key part of their workflow. Thus why we this is intentionally placed here. Rich's comments above are also accurate.

It is on our roadmap to consider having the control remain open when toggling settings like this. However, we need to solve a11y issues around how users of assistive technology can escape the dialog when there is no explicit close button. To neglect this would be to produce an inaccessible experience for a significant portion of our user-base. 

> This makes for a jarring and somewhat cumbersome experience for editing links, especially if you are trying to complete a few changes to a link

Can you explain the workflow you are undertaking here? I'm genuinely curious as to whether we've overlooked something.

If you want to make a few changes to a link you'll need to enter "edit" mode which requires clicking on the pencil icon in the dialog. The purpose of the setting toggle is not making _multiple_ changes - it's intended to allow you to quickly toggle this one particular niche setting. TBH it's a bit of an anomaly, but as I mentioned, it's a key workflow for a subset of our users.

Note also that [we're proposing removing this preview step entirely](https://github.com/WordPress/gutenberg/pull/50998) which would negate this issue in future releases. Feedback on that feature also appreciated.

**Comment by annezazu** [comment]
>It is on our roadmap to consider having the control remain open when toggling settings like this. However, we need to solve a11y issues around how users of assistive technology can escape the dialog when there is no explicit close button. To neglect this would be to produce an inaccessible experience for a significant portion of our user-base.
>Can you explain the workflow you are undertaking here? I'm genuinely curious as to whether we've overlooked something.

Thanks for following up and for the added context. The workflow is simple: I am adding a link and setting it to open in a new tab. In doing so, the modal closes out the second I click the checkbox, making it unclear to me if it even worked properly. Compare it to the experience of using the advanced settings where it stays open:

https://github.com/WordPress/gutenberg/assets/26996883/0956cc40-ac62-4504-b330-0fabb743b346

It felt like a bug at least to me. I do dig the newer experience you're exploring here more: https://github.com/WordPress/gutenberg/pull/50998

**Comment by getdave** [comment]
> The workflow is simple: I am adding a link and setting it to open in a new tab.

Thanks. It was the "not persisting" that threw me a little because it is in fact persisting it's just (and I think this is the nub of the Issue) the fact isn't clear enough to you (as a user).

I get you. It's not ideal. @richtabor and I are aware of the suboptimal experience and working on it. However, do you still feel this qualifies as a "Bug"? 

I'm open to whatever folks feel is right. Appreciate your time here to report this and provide feedback.

**Comment by annezazu** [comment]
It feels like a bug to me when the Advanced section otherwise stays open but it's likely closer to an enhancement. I'll update the labeling and we can iterate going forward :)

**Comment by annezazu** [comment]
At this point, it seems unlikely to be iterated on for beta 1 so am going to move to punted to 6.5 as well.

**Comment by annezazu** [comment]
[After a review](https://wordpress.slack.com/archives/C02QB2JS7/p1707152945370159) by core editor triage leads and core editor tech leads, this has been removed from the board for 6.5 consideration.

**Comment by annezazu** [comment]
Actually, I think this is fixed now that this has been merged: https://github.com/WordPress/gutenberg/pull/57726 Closing out as I can't replicate.

**Comment by getdave** [comment]
It's been resolved by https://github.com/WordPress/gutenberg/pull/58744

**Comment by annezazu** [comment]
Testing GB 17.8 nightly and WP 6.5-alpha-57555 on WP Playground, I'm now seeing this behavior return:

https://github.com/WordPress/gutenberg/assets/26996883/366c9e81-ad55-4ccd-9be5-3ba7a0798b53

I'll keep an eye on it next week to ensure it's resolved or will reopen otherwise.

**Comment by getdave** [comment]
Checking the code on Gutenberg `trunk` that will go into today's 17.7.0 RC release (final release going into WP 6.5) the code that would render that checkbox is no longer there. 

https://github.com/WordPress/gutenberg/blob/194d208c68e4d234c43c7d0c3d3db55df56c367e/packages/block-editor/src/components/link-control/index.js#L424-L434

That's expected after https://github.com/WordPress/gutenberg/pull/58744.

The updated packages (including `@wordpress/block-editor` which is where the code resides) will be synced to Core today with 17.7.0 RC. Once done then we'll want to check if this behaviour persists during the Beta/RC period.

I'll make a note to circle back.

**Comment by annezazu** [comment]
Couldn't replicate with 6.5 beta 1! Keeping closed. Thank you for your attention to detail, Dave ❤️ 


https://github.com/WordPress/gutenberg/assets/26996883/8420e8f5-4146-402f-9e05-ec41d92906b5
