### ISSUE TITLE
Font Library: Some SVG image previews are clipped or not rendered legibly

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#54688]
## What?

> Some font previews are clipped or not rendered legibly, so it might be hard to decipher. 

Issue originally reported by @ironprogrammer in https://github.com/WordPress/gutenberg/pull/54566#issuecomment-1727127645

```
- Chenla
- Coiny
- Concert One
- Content
- Cutive
- Englebert
- Khmer
- Material Icons
- Material Icons Outlined
- Material Icons Round
- Material Icons Sharp
- Material Icons Two Tone
- Noto Color Emoji
- Noto Emoji
- Noto Kufi Arabic
- Noto Sans Arabic
- Noto Sans Bhaiksuki
- Noto Sans Caucasian Albanian
- Noto Sans Cypriot
- Noto Sans Elymaic
- Noto Sans Gunjala Gondi
- Noto Sans Lycian
- Noto Sans Myanmar
- Noto Sans Old Hungarian
- Noto Sans Old Turkic
- Noto Sans Phags Pa
- Noto Sans SignWriting
- Noto Sans Warang Citi
- Noto Serif Dogra
- Noto Serif Myanmar
- Revalia
- Siemreap
```
## Why?
All previews should look good.

## How?
Update the previews on this repo: https://github.com/WordPress/google-fonts-to-wordpress-collection

**Comment by ironprogrammer** [comment]
@matiasbenedetto, an updated list (as of GB 17.6) has been added over at https://github.com/WordPress/google-fonts-to-wordpress-collection/issues/18.

**Comment by colorful-tones** [comment]
I've triaged this issue: https://github.com/WordPress/gutenberg/issues/54688 onto the [WordPress 6.5 Editor Tasks board](https://github.com/orgs/WordPress/projects/148) under 'In Discussion / Needs Discussion'. Please let me know if this is suitable. It seems this would be a critical piece to the overall Font Library release for 6.5. 

Also, I [left a comment](https://github.com/WordPress/google-fonts-to-wordpress-collection/issues/18#issuecomment-1939145491) on the related issue from the external `wordpress/google-fonts-to-wordpress-collection` item (https://github.com/WordPress/google-fonts-to-wordpress-collection/issues/18), which is also on the WordPress 6.5 Editor Tasks board, but I suggested we remove it and track progress on this issue instead (https://github.com/WordPress/gutenberg/issues/54688).

**Comment by mikachan** [comment]
I believe this can be closed as https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/20 has now been merged. Please re-open if necessary!
