### ISSUE TITLE
Patterns: Add UI to rename/delete pattern category in the Site Editor

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#54699]
Related to #54640

## What problem does this address?

As far as I know, there is no UI in the Site Editor to rename or delete pattern categories once they have been created. The only way is to access `wp-admin/edit-tags.php?taxonomy=wp_pattern_category` directly, but only a few users will know this URL.

![patterns](https://github.com/WordPress/gutenberg/assets/54422211/5d8c6f39-83c6-4dc7-b221-28508a9adcf4)

## What is your proposed solution?

In the short term, we might want to add `wp-admin/edit-tags.php?taxonomy=wp_pattern_category` either above or below "Manage all of my patterns".

Personally, I think it would be ideal to be able to rename or delete categories from the Ellipsis dropdown.

![pattern-manage-ui](https://github.com/WordPress/gutenberg/assets/54422211/c5151a68-1590-4215-9c11-35005d8f6bc5)

**Comment by t-hamano** [comment]
Another option might be to display a dropdown menu at the top right of the canvas.

![patterns-edit-canvas](https://github.com/WordPress/gutenberg/assets/54422211/4a3e4247-d58f-40b0-a116-83429a00e751)

**Comment by ricjcs** [comment]
Is it possible to reopen this issue? Currently it's not possible to rename/delete pattern categories or view empty categories.

**Comment by t-hamano** [comment]
@ricjcs Can you submit your problem as a new issue? This issue was reported over two years ago, and the current site editor UI has changed significantly.
