### ISSUE TITLE
UseOnce block does not get unlocked after transform

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#5471]
## Issue Overview

Converting a locked UseOnce block to another block type does not remove the lock.

![tim](https://user-images.githubusercontent.com/6073772/37091243-ba6335bc-2207-11e8-8487-0952f41190e1.gif)

## Steps to Reproduce (for bugs)
1. Add a subhead block.
2. Add another subhead block, this gets locked for violating UseOnce so to speak.
3. Use the block switcher to switch the locked subhead block to a paragraph block.
4. Now the error says "Paragraph cannot be used twice".

Chrome with WP 4.9.4 vagrant and Gutenberg 2.3.0.

## Expected Behavior
The lock to be lifted after an acceptable transformation has been made (as in, to a block that does not trigger UseOnce).

## Current Behavior
UseOnce is enforced until the block is deleted.

**Comment by mcsf** [comment]
@hedgefield, I was circling back to this one. Can you still repro?

**Comment by hedgefield** [comment]
Nope, it's fixed in 2.4! 🎉
