### ISSUE TITLE
Avatar block toolbar alignment not working proper on backend side.

### ISSUE THREAD

**Issue by VipulUpadala** [WordPress/gutenberg#54714]
### Description

I have tested the Avatar block and found the avatar block toolbar alignment not working when try on twenty twenty-three theme then Align Right not working on backend side. Same thing for twenty twenty-one theme Align center not working. 

### Step-by-step reproduction instructions

1. Create a new page and take the avatar block.
2. And check toolbar alignment setting.( Align right not working for twenty twenty-three theme and Align center not working for twenty twenty-one theme )

### Screenshots, screen recording, code snippet

Please check the provided screen recording video below for a better understanding of the issue.

Video URL: https://share.cleanshot.com/sjjn26Wz5h6DQfbq1KcC

### Environment info

- WordPress 6.3.1 running
- Chrome
- macOS 13.2

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by properlypurple** [comment]
Tested with WP 6.3.1, without Gutenberg, as well as with the following versions of the plugin
- 16.7.0-rc.1
- 16.6.0

I can consistently reproduce this as only happening in the editor, only with block themes. It works as expected on classic themes, and the frontend works properly with both block and classic themes.

Attaching the video from above here, in case it's removed from its current location

https://github.com/WordPress/gutenberg/assets/40858144/78e12c11-fc92-44d8-aaa9-6a2b71955cbb

**Comment by himshekhar97** [comment]
`.alignright {
    float: right;
}`

This code is missing that why alignment is not working.

**Comment by MaggieCabrera** [comment]
This was reported on TT4 too, and I confirmed it also happens on TT3
