### ISSUE TITLE
Remove margins from Notice component

### ISSUE THREAD

**Issue by ecgan** [WordPress/gutenberg#54741]
## What problem does this address?

Currently the Notice component has margins being defined in its CSS:

https://github.com/WordPress/gutenberg/blob/0c0d0139f4ef38970bde2dbf8ac6602e493e3983/packages/components/src/notice/style.scss#L7

Because of the above defined margins, consumers who use the Notice component have to specify their own margins to override this, which is an inconvenient developer experience.

Here's a screenshot from https://wordpress.github.io/gutenberg/?path=/story/components-notice--notice-list-subcomponent - we can see that the Notices are not left-aligned with the checkbox because they have a 15px left margin:

<img width="1138" alt="image" src="https://github.com/WordPress/gutenberg/assets/417342/4bc71009-b57a-4a42-83ca-474d42677b79">

This issue can also be seen in the Gutenberg editor, where the Notice component's margin is being overridden with 0:

![image](https://github.com/WordPress/gutenberg/assets/417342/37e63878-b94d-4154-b61c-f1e9bda19713)

It would be better to have no margins. The spacing of the Notice component should be controlled by the parent layout component.

As an example, we can refer to [Ant Design's Alert component](https://ant.design/components/alert). The component does not have any margins. Spacing between multiple Notice components are controlled by the parent layout component.

![image](https://github.com/WordPress/gutenberg/assets/417342/fafa5bd7-8a80-47b6-87de-3565ca56239e)

## What is your proposed solution?

Remove the margins from the Notice component.

**Comment by mirka** [comment]
Closed by #54800
