### ISSUE TITLE
wp-scripts lint-js and format should preserve spaces within parents

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#54749]
### Description

The update to `@wordpress/scripts` 26.13.0 seems to have caused an issue where spaces are being removed around parens via `npx wp-scripts format` and flagged by `npm wp-scripts lint-js`. I've noticed this on a couple different projects using the `@wordpress/scripts` library for formatting and building blocks.

I believe #54539 is the cause, and I don't believe it was intentional. I've posted `npm ls prettier` output below that may point to that, but I'm not at all sure why. I'm happy to help test any changes though. 😄 

### Step-by-step reproduction instructions

In a clean directory:

1. `npm install @wordpress/scripts@26.12.0`
2. `echo "const x = ( a ) => { return a -1 };" > index.js`
3. `npx wp-scripts lint-js index.js`
4. See no formatting errors related to paren spacing
5. `npm install @wordpress/scripts@26.13.0`
6. `npx wp-scripts lint-js index.js`
7. See `Replace ·a·)·=>·{·return·a·-1· with a)·=>·{⏎↹return·a·-·1;⏎` (noting space before/after `a` is removed)

In each scenario, `npx wp-scripts format` follows the behavior of `lint-js`.

### Environment info

I've tried this with both Node 16 and Node 18.

With Node 16, when I run `npm ls prettier`, which I picked up while reading #21872, I see this:

26.12.0:
```
› npm ls prettier
scripts2@ /Users/jeremyfelt/Development/scripts2
└─┬ @wordpress/scripts@26.12.0
  ├─┬ @wordpress/eslint-plugin@15.1.0
  │ ├─┬ eslint-plugin-prettier@3.4.1
  │ │ └── prettier@npm:wp-prettier@2.8.5 deduped
  │ └── prettier@npm:wp-prettier@2.8.5 deduped
  ├─┬ @wordpress/prettier-config@2.25.0
  │ └── prettier@npm:wp-prettier@2.8.5 deduped
  └── prettier@npm:wp-prettier@2.8.5
```

26.13.0:
```
› npm ls prettier
scripts2@ /Users/jeremyfelt/Development/scripts2
└─┬ @wordpress/scripts@26.13.0
  ├─┬ @wordpress/eslint-plugin@16.0.0
  │ ├─┬ eslint-plugin-prettier@5.0.0
  │ │ └── prettier@3.0.3 deduped
  │ └── prettier@3.0.3
  ├─┬ @wordpress/prettier-config@2.25.0
  │ └── prettier@3.0.3 deduped
  └── prettier@npm:wp-prettier@3.0.3-beta-3
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
It looks like https://github.com/WordPress/gutenberg/pull/54775 will fix this issue.
