### ISSUE TITLE
Font Library: fix endpoint permissions

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#54751]
It is necessary to fix the font library endpoints font permissions check.

## Check the right folder

We need to check for write permissions in the right folder:
Currently, `wp-content/upload/fonts/` is checked instead of `wp/content/fonts`.

## Endpoints

- ` GET /fonts/collections/`
- ` GET /fonts/collections/<id>/`
Should not check for write permissions on disk.
---

- `POST /fonts `
Should check for write permissions on disk only if any font families received have font faces defined with reference to files: `downloadFromUrl` or `uploadedFile`.
Should return HTTP error code 403 if there are no permissions.
---

- `DELETE /fonts`
Should not check write permissions. The font asset will be try to be removed and if it fails it will return error for that particular font face.

---

**Comment by madhusudhand** [comment]
> Should check for write permissions on disk only if any font families received have font faces defined with reference to files: downloadFromUrl or uploadedFile.

@matiasbenedetto can you provide more details on the request payload scenarios. Are these `downloadFromUrl or uploadedFile.` (one of them) always present?
