### ISSUE TITLE
Patterns: Newly added categories are not reflected immediately

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#54752]
### Description

Adding a category to a pattern may not be reflected in the details panel or pattern list page unless you reload the browser.

This seems to only occur in the following scenarios:

- When you open the editor canvas of the created pattern and add a category from the right sidebar
- If the category you are adding is new

### Step-by-step reproduction instructions

- Access `wp-admin/edit-tags.php?taxonomy=wp_pattern_category` and delete all categories.
- Create a pattern in the Site Editor. Do not add categories.
- Add categories in the editor canvas and save the entity.
- Return to the view mode.
- ❌ The added category is not displayed in "Categories" in the details panel.
- Back to the Patterns page.
- ❌ Newly added categories are not displayed.
- Reload your browser.
- ✅ The newly added category will be displayed.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/d6269115-c8ed-4b09-8b77-aae7711c03de

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
[This PR](https://github.com/WordPress/gutenberg/pull/54768) should fix this 🤞
