### ISSUE TITLE
Font Library: .otf font files are rejected.

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#54759]
After the latest mime type [checks implemented](https://github.com/WordPress/gutenberg/pull/53986), the .otf files are rejected by the server.

## Testing
In this screencast, I'm running: 

- WordPress 6.3
- Gutenberg trunk
- PHP Version 8.1.23
- Apache 2
- Ubuntu 22.04
- Firefox browser

Result: 
❎ .otf files no uploading.

The rest of the file types work OK.
✅ .ttf files
✅ .woff files
✅ .woff2 files

In this zip file you can find 5 different font files with otf file extension:
[otf fonts.zip](https://github.com/WordPress/gutenberg/files/12707012/otf.fonts.zip)

## Screencast of the test

https://github.com/WordPress/gutenberg/assets/1310626/3fa5a886-14c0-4784-a7bf-b46e1d11c54a

**Comment by madhusudhand** [comment]
While testing, for some otf files, mime type was `application/vnd.ms-opentype` instead of `font/otf`. Since only one type can be used, we can either switch the mime type or drop the otf support for now and add in the future versions.

Created #54780 [draft] to drop the support for this release.

**Comment by matiasbenedetto** [comment]
Closing this as completed by:
- https://github.com/WordPress/gutenberg/pull/54886
