### ISSUE TITLE
Brocken compatibility with top plugins after filter removing

### ISSUE THREAD

**Issue by OlegApanovich** [WordPress/gutenberg#54794]
### Description

Hi, recently I installed the latest 16.6.0 Gutenberg plugin version downloaded from wordpress.org and surprisingly found that
In the plugin file plugins/gutenberg/build/block-library/blocks/post-content.php function gutenberg_render_block_core_post_content does not have $content = apply_filters( 'the_content', str_replace( ']]>', ']]&gt;', $content ) ); string any more. I even can see the comment related to this string still there https://i.imgur.com/jzn8yin.png but the filter is not there anymore.

Our plugin heavily depends on this filter cos it was the only place where we could change the output of this method and it breaks a lot right now.
I tried hard to find where it happens but couldn't, seems this filter is still there in the branch release/16.6 https://github.com/WordPress/gutenberg/blob/2507c46965ee0b072d265cf832d2b3d2b54c0c70/packages/block-library/src/post-content/index.php#L48C1-L48C1

Is there a chance that something went wrong and the prod version of Gutenberg 16.6.0 missed it?
I only can find that seems it happening somewhere between 16.0 - 16.1 versions, could you please show the pull request or commit where you removed it?
Thank you.

### Step-by-step reproduction instructions

1. Install 16.6.0 Gutenberg plugin version downloaded from wordpress.org
2. Compare the file  plugins/gutenberg/build/block-library/blocks/post-content.php with realize corresponding for this version
3. Observe the issue  $content = apply_filters( 'the_content', str_replace( ']]>', ']]&gt;', $content ) ); filter not there anymore

### Screenshots, screen recording, code snippet

https://i.imgur.com/wmKIm3d.png

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@OlegApanovich,

I can see filter in the files shipped via WP.org - https://plugins.trac.wordpress.org/browser/gutenberg/tags/16.6.0/build/block-library/blocks/post-content.php#L47.

The code hasn't changes on the trunk as well - https://github.com/WordPress/gutenberg/blob/3a6e7fefdb4a730ed2eff5c879e317fc4ef7f5c3/packages/block-library/src/post-content/index.php#L47-L48.

**Comment by t-hamano** [comment]
Just to be sure, I checked the Gutenberg plugin files that I downloaded manually and the Gutenberg plugin files that I installed from the dashboard, and the filter does exist.

**Comment by OlegApanovich** [comment]
Sorry guys most likely issue is on my side. I closed the ticket. Thank you.
