### ISSUE TITLE
Patterns: ensure consistency in capitalization of "All Patterns" and "My patterns"

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54799]
Using 16.7 RC2, I noticed that we have capitalization inconsistencies:

<img width="351" alt="Screenshot 2023-09-25 at 10 16 03 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/180def92-b994-4686-9c93-0b68a9b5d55a">

Considering we write "My patterns" and "All patterns" in the Site Editor > Patterns section, I think we should keep it lowercase to "All patterns" and "My patterns" for a quick change:

<img width="349" alt="Screenshot 2023-09-25 at 10 21 32 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/4738958c-917e-4b96-b687-66a505bf8e3c">

Going forward though, we do write "Call to Action" and it might make sense to switch that to "Call to action" to match this or vice versa. Either way, for now, let's get consistency :) 

@aaronrobertshaw might you be able to help with this?

**Comment by t-hamano** [comment]
Regarding the rules of capitalization, the discussion in #51744 submitted by @richtabor may also be helpful.

Also, I remember talking about something similar with @afercia in [this comment](https://github.com/WordPress/gutenberg/pull/52641#issuecomment-1638148471).

**Comment by aaronrobertshaw** [comment]
PR is up improving casing consistency for pattern labels and notices: https://github.com/WordPress/gutenberg/pull/54807
