### ISSUE TITLE
List: block alignment controls should work

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#548]
Hook up the styles for the alignment controls on lists.

**Comment by BE-Webdesign** [comment]
As far as I can tell, this already works.  Whenever it is left aligned, there is no style attribute added, but the other alignments appear to work properly.  This behavior matches the text block.

**Comment by joyously** [comment]
Does defaulting to left align doing nothing make it more difficult to handle RTL later?

**Comment by jasmussen** [comment]
> As far as I can tell, this already works. Whenever it is left aligned, there is no style attribute added, but the other alignments appear to work properly. This behavior matches the text block.

Just tried it again, and yes this works now. When we did a review of the editor it did not work, for some reason. 

There are still some iffy selection focus features, and a justify button. But these are tracked separately in #567 and #540

**Comment by BE-Webdesign** [comment]
@joyously 

That is a great point to bring up and if there is not already open an issue up for RTL support, you should open one.  That is something we don't want to skip over.
