### ISSUE TITLE
Patterns: ignoring sync option and causing strange effects in syncing status

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54803]
### Description

Using GB 16.7 RC 2 and WordPress 6.3.1 OR 6.4-alpha-56670, I'm unable to create an unsynced pattern. When I deselect the sync option, a synced pattern is still created. cc @aaronrobertshaw. 

### Step-by-step reproduction instructions

1. Open the Site editor.
2. Head to Pages.
3. Open a page.
4. Create some blocks.
5. Select those blocks and use the three dot menu to create a pattern in the Site Editor. 
6. Add a category. 
7. Turn off the sync option.
8. Notice the snackbar notif says unsynced pattern created but notice a synced pattern shows up both in the inserter and on the page itself. 

### Screenshots, screen recording, code snippet

Here's a short vid showing the problem at its simplest:

https://github.com/WordPress/gutenberg/assets/26996883/e31ebeaf-bc2d-41f4-8d77-6e69996182c4

Here's me talking through the bugginess as I'm not quite sure how best to explain it otherwise! Basically the "syncness" seems to not stick and randomly ignore sync status.

https://github.com/WordPress/gutenberg/assets/26996883/c8667871-ab22-4936-9959-a426df5d9c28

### Environment info

- 6.3.1 and 6.4-alpha-56670
- GB 16.7 RC 2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by apeatling** [comment]
I can confirm this when following the same steps :+1:
