### ISSUE TITLE
Post Featured Image: Contain - Aspect Ratio 4:3 - Align left does not align image left

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#54805]
### Description

Inside the Query Loop.
Post Featured Image.
Aspect Ratio: 4:3.
Width: 70%
Scale: Contain

Does not show the image aligned to the left.

### Step-by-step reproduction instructions

1. Add a Post Featured Image block to the Query Loop. Images are 1100 (tall) x 1560 (wide)
2. Aspect Ratio: 4:3
3. Width: 70%
4. Scale: Contain

Result of what I see:
![Screenshot 2023-09-25 at 23 06 38](https://github.com/WordPress/gutenberg/assets/5323259/797a9331-b80d-4f36-b166-f16ab9288e2d)

It should be left aligned. Left align and center align are the same. Right align is different.

### Screenshots, screen recording, code snippet

-

### Environment info

WordPress 6.3.1
Using Gutenberg plugin 16.6.0
Brave (Chrome).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by paaljoachim** [comment]
Frontend.
Image does not align with the Published date just above it.
![Screenshot 2023-09-25 at 23 17 58](https://github.com/WordPress/gutenberg/assets/5323259/9bcfcf04-775c-40f5-be55-0e82b645dfa9)

@ntsekouras

**Comment by ntsekouras** [comment]
Do the aspect-ratio, width etc.. play a role in reproducing? I'll -cc @tellthemachines too because it seems it might be related to layout cases. Maybe this css rule `is-layout-constrained > .alignright` because Query Loop has it's nested blocks inside an extra node(`li`)?

**Comment by tellthemachines** [comment]
> Maybe this css rule `is-layout-constrained > .alignright` because Query Loop has it's nested blocks inside an extra node(`li`)?

Yeah that looks to be the case! Given the rule exists for both constrained and flow layouts, and the styles applied to aligned left/right images don't have any effect inside flex layouts, layout-wise it would be fine to not specify the layout type at all for those rules. I'm not sure why the selector was built like that in the first place though, or if changing it might break anything.

**Comment by tellthemachines** [comment]
I guess an alternative, lower impact approach would be to add Post Template block-specific styles like `.wp-block-post-template-is-layout-constrained > li > .alignright`

**Comment by tellthemachines** [comment]
I have a low-impact fix in https://github.com/WordPress/gutenberg/pull/54997. Given that this is not a regression from 6.3 (it's probably been around forever because Post Template always had this nested markup) I'll leave it up to the release team whether to include it or not now that we're in Beta 😄 cc @mikachan @karmatosed @SiobhyB

**Comment by andrewserong** [comment]
> Given that this is not a regression from 6.3 (it's probably been around forever because Post Template always had this nested markup)

Apologies, I missed this comment and added the PR to the 6.4 board. Feel free to remove it!
