### ISSUE TITLE
Tracking issue: 6.4 Social media assets

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54809]
**Due date: Nov 4**

As part of efforts for the 6.4 release and related assets, this is a tracking issue to cover the work needed for the 6.4 social media assets. Here are two examples of what this work entails: [release coming soon](https://twitter.com/WordPress/status/1688563742164852736) example and [celebratory video](https://twitter.com/WordPress/status/1691468660202696705) with contributor stats. The aim is to have short and relevant social media items to share on the WordPress.org accounts. Let's use this issue to collaborate and share progress. 

This will include the following:
- Release coming soon messaging
- Celebratory video with release stats
- Additional smaller feature focused items (separate from the featurettes work which are slightly longer videos). 

@rmartinezduque would love to hear what else might be helpful.

**Comment by jasmussen** [comment]
I can tentatively raise my hand to help here. Depending on his workload, @marko-srb may or may not be available to help.

**Comment by rmartinezduque** [comment]
> @rmartinezduque would love to hear what else might be helpful.

I think you captured it all very well, thanks Anne. 🙂

Here are a few more additional notes in case it helps:

- The goal of the "Coming soon asset" is to build some excitement before the release. They have usually performed very well on social.
- The latest [celebratory video](https://twitter.com/WordPress/status/1691468660202696705) included stats on: the number of total contributors + new contributors, countries represented, and languages translated. I believe we won't have these numbers until almost the final release. And this time, we may also want to include that 6.4 is led by an underrepresented gender release squad. 

Lastly, we should keep in mind the following sizes for any social media assets:

- 1600 x 900px (for X/Twitter, Facebook, LinkedIn, etc)
- 1080 x 1080px (for Instagram)

**Comment by annezazu** [comment]
@rmartinezduque awesome! I think it would help to share any other expected social media assets to share for this release too. For example, which features we should likely have social media call outs for (Fonts, TT4, and image lightbox come to mind). These could just be condensed versions of featurettes but curious what you think or if you just mainly need the two items (coming soon + celebration).

**Comment by annezazu** [comment]
Quick note that the Font Library has been punted from 6.4 and is now slated for 6.5. Noting as we now don't need to do a social media call out around fonts.

**Comment by rmartinezduque** [comment]
Thanks for following up on this, @annezazu. As of RC1 (next week), we could start sharing social media callouts with the already available assets to raise awareness about what's coming and build excitement. This comes first to mind:

- TT4. Additionally, we can point folks [to this post](https://make.wordpress.org/core/2023/08/24/introducing-twenty-twenty-four/) for more info/details.
- Writing improvements, and point folks to this [Core Editor Improvement](https://make.wordpress.org/core/2023/10/05/core-editor-improvement-ensuring-excellence-in-the-writing-experience/) post.
- Command Palette updates, and point to this other [Core Editor Improvement](https://make.wordpress.org/core/2023/09/12/core-editor-improvement-commanding-the-command-palette/) post.
- Pattern management improvements (categories, new filtering options).

Let me know your thoughts. I'd be happy to start working on copy and reusing available assets for socials.

**Comment by annezazu** [comment]
Checking in to see what else is needed here! I'm not on social media so perhaps we've already been sharing but curious where we stand in terms of coming soon messaging and a celebratory video with release stats. The featurettes are being tracked otherwise and are in a solid spot so not worried there!

**Comment by rmartinezduque** [comment]
> curious where we stand in terms of coming soon messaging and a celebratory video with release stats

Thanks for checking in, @annezazu. I was due an update here! These assets are on track. We'll keep it simple this time and get a static image for the coming soon asset, similar to what [was done for 6.2](https://www.instagram.com/p/CqTNcrTO1pS/). @jasmussen is helping with that. :) We are also looping in some of our video helpers to finish the celebratory video with stats.

We recently started to schedule some social posts for 6.4, one of them with the [highlight grid](https://github.com/WordPress/gutenberg/issues/54808). And this is what I have in mind to promote in the coming weeks:

[Featurettes](https://github.com/WordPress/gutenberg/issues/54810):

- TT4
- Writing improvements
- Workflow upgrades
- Design tools

In addition to the featurettes, we'll have more social posts to highlight the fact that this is a gender-underrepresented release squad and some particular features/improvements, including:

- TT4 + bundled patterns
- Writing improvements
- Command Palette improvements
- Custom categories for patterns + advanced filtering

And others that are usual in all releases, such as the accessibility and performance wins.

**Comment by jasmussen** [comment]
Here are the static assets Reyes mentions, and I'm happy to create more if you have specifics. Zipped so GitHub doesn't resize them:
[Archive.zip](https://github.com/WordPress/gutenberg/files/13225036/Archive.zip)

Edit: for reference, the color contrast between "Coming soon." and the background color is 4.95:1, much ore than the 4.5:1 needed for AA.

**Comment by rmartinezduque** [comment]
These are some of the social posts that have been shared across different platforms so far. Expect more to promote the featurettes and improvements of the release in the coming days and weeks:

- [X/Twitter post with highlight grid](https://twitter.com/WordPress/status/1720059459051946149) | [Instagram](https://www.instagram.com/p/CzJkHy8s12s/)
- [X/Twitter post with TT4 teaser](https://twitter.com/WordPress/status/1720902762542621036) | [Instagram](https://www.instagram.com/p/CzPWTkAP4Ou/)
- [X/Twitter post with coming soon asset](https://twitter.com/WordPress/status/1721512277994565781) | [Instagram](https://www.instagram.com/p/CzT4cjAMalo/)
- [X/Twitter post for the 6.4 release](https://twitter.com/WordPress/status/1721982880614650021) | [Instagram](https://www.instagram.com/p/CzW-vH8uqN7/)

The celebratory video is on track, with details being finalized. It will include a mention of the release squad, along with the stats on contributors, languages translated, countries represented, etc. The idea is to share it next week on social media.

**Comment by rmartinezduque** [comment]
The celebratory video with stats has been finalized and is scheduled to go out by the end of this week.

The TT4 featurette and [this /news post](https://wordpress.org/news/2023/11/introducing-twenty-twenty-four/) were also promoted on social earlier this week.

I think we can close this issue now. @annezazu would you mind helping with that? I don't have access to do so. Thanks!

**Comment by jasmussen** [comment]
🎉
