### ISSUE TITLE
Live-update the site preview when changing posts per page value

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#54821]
When browsing the Index or Blog Home template there's an option to change the number of posts displayed per page:

<img width="359" alt="Screenshot 2023-09-26 at 11 39 09" src="https://github.com/WordPress/gutenberg/assets/846565/e9ff27da-8d01-42e8-976f-a1858b8d3d33">

Ideally the site preview would always reflect this value, similar to how switching a style variation works in the Styles panel. Currently it only does so after a save action.

**Comment by Sirjazzfeetz** [comment]
Perhaps also remove "Some templates may override this setting."  Then if setting is overridden, disable setting and show which template overrides, with edit template link.
