### ISSUE TITLE
Allow links in new tab by default

### ISSUE THREAD

**Issue by roman2861** [WordPress/gutenberg#54824]
## What problem does this address?
It is a bit difficult to set checkbox to open link in the new tab, it requires a lot of clicks.

## What is your proposed solution?
Allow to set checkbox turned on by default

**Comment by skorasaurus** [comment]
Thanks for reporting; there's another issue - https://github.com/WordPress/gutenberg/issues/55395 - with this that has a bit of discussion on it so I'm closing this; please follow that issue for updates.
