### ISSUE TITLE
Hide navigation section in template part details panel when menu cannot be found

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#54822]
If a navigation menu cannot be found, the menu name is still output, orphaned in the template part details panel:

<img width="919" alt="Screenshot 2023-09-26 at 11 48 22" src="https://github.com/WordPress/gutenberg/assets/846565/90694694-d05a-4429-93ff-bfe7f61b5b3c">

This looks a bit strange and should probably just be hidden.

**Comment by Mamaduka** [comment]
@jameskoster, do you have steps to reproduce this state? I can only see the fallback navigation menu title when the menu is deleted.
