### ISSUE TITLE
Font Library: add option to revoke access to Google Fonts

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#54826]
## What problem does this address?
Font Library > Install shows a very cautious warning about allowing access to Google Fonts, but there's no way to revoke that access once it's granted.

## What is your proposed solution?

There needs to be an action button that revokes access to Google Fonts and brings the modal back to its initial state.

![CleanShot 2023-09-26 at 14 14 34@2x](https://github.com/WordPress/gutenberg/assets/14153300/297a99dc-bb8e-481a-8196-94055e81d14e)

**Comment by matiasbenedetto** [comment]
Thanks for proposing this feature. I added under "Needs discussion" in [stage 3 tracking issue.](https://github.com/WordPress/gutenberg/issues/53926)

**Comment by matiasbenedetto** [comment]
Technically this would be simple to implement but we would need to add an UI element if we decide to implement it.

@jasmussen I would like to have your input about this.

**Comment by matiasbenedetto** [comment]
Linking a closely related issue: https://github.com/WordPress/gutenberg/issues/58774

**Comment by jasmussen** [comment]
How's this ellipsis menu? 

<img width="4640" alt="Revoke permission" src="https://github.com/WordPress/gutenberg/assets/1204802/16a784e2-ccfd-4fe8-86d5-51c34d0f1839">

By the way, be mindful of the details in [the existing mockups](https://github.com/WordPress/gutenberg/issues/45271), there's a lot that's diverging in trunk at the moment:

![Screenshot 2024-02-08 at 08 07 44](https://github.com/WordPress/gutenberg/assets/1204802/28241c30-2bc7-4c11-b199-dec5f0bb45ce)

It's possible I'm missing context from other reviews, so correct me if I'm wrong. But the connect box should be vertically centered, I'd avoid the "Google Fonts" heading (the introductory paragraph is sufficient), the width, height and padding of the box is off, the line-height of the warning is wrong, and the "Allow access" button should be centered, or full-width. I realize there's a separate issue for changing the text, that's fine. And finally, a comma is missing from the introductory paragraph.

**Comment by getdave** [comment]
If we implement this how hard would it be to make it provider agnostic. So say Theme A bundles a specific provider of fonts, could we make the UI able to revoke access to that collection also?

The _primary_ objective should be to allow Google Fonts to be revoked in 6.5 though 👍

**Comment by matiasbenedetto** [comment]
Linking this issue here as closely related: https://github.com/WordPress/gutenberg/issues/58774

**Comment by youknowriad** [comment]
So this has been implemented already, Any reason we're keeping the issue open?

**Comment by matiasbenedetto** [comment]
Closing this issue as fixed by: https://github.com/WordPress/gutenberg/pull/59205
