### ISSUE TITLE
Post Navigation Link: Does not render previous and next links on the front of the site

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#54845]
### Description

The Post Navigation Link block has stopped rendering the previous and next links. It works in the site editor, but the links no longer appear on the front of the site.

I tested this with TT3 but I can reproduce it in any theme. Am I missing something obvious?

I didn't see a report about this, but I'm sorry if this has been reported somewhere.

### Step-by-step reproduction instructions

1. Go to the site editor and open a single post template.
2. Add a post navigation link, the previous and the next links.
3. Open the site and see the missing post navigation links.

### Screenshots, screen recording, code snippet

| Editor | Front of the site |
| ----------- | ----------- |
| ![localhost local_wp-admin_site-editor php (2)](https://github.com/WordPress/gutenberg/assets/908665/951c9cf0-42de-4328-a2b9-c3426c2760b2) | ![localhost local_blue-screen-of-joy_](https://github.com/WordPress/gutenberg/assets/908665/220363c7-d17e-4121-a0d5-83ed710d783d) |

They look empty in the inspector:
![Screenshot 2023-09-26 at 23 25 48](https://github.com/WordPress/gutenberg/assets/908665/552e6b3f-51ad-4e30-9d5a-e6cc059a3786)

### Environment info

WP 6.3.1
Gutenberg Trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hey @iamtakashi - I'm unable to recreate this in a fresh install, either with Gutenberg active, or deactivated... Are you able to recreate it on a new/fresh testing site as well?

**Comment by carolinan** [comment]
Are there enough posts on the installation so that there are posts to link to?

**Comment by iamtakashi** [comment]
Yes, there are enough posts. I thought this was weird as no one seemed to notice this. There must be something going on in my environment. I'll try a fresh install.

**Comment by iamtakashi** [comment]
I don't see the same issue with a fresh install. I'm unsure what the problem was, but it's all good now. @jordesign, thanks for the suggestion.

Thank you both for your reply. Sorry for the false alarm. Closing this.
