### ISSUE TITLE
Image lightbox: users cannot reset the block-level setting once it has been set

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#54857]
### Description

Once the user has set the lightbox setting once at the block level, there is no way for them to "reset" it and use the global level setting.

### Step-by-step reproduction instructions

- In the post editor
  - Add two images block.
  - In the first image, enable the lightbox behaviour ("Expand on click") in the block inspector and then disable it.
  - Save the post.
- In the site editor
  - Enable the lightbox behaviour in "global styles sidebar > blocks > image".
- Go to the front end. Only the second image uses the lightbox behaviour.

### Environment info

I've tested this with WordPress 6.4 beta 1, Gutenberg trunk (16.7.0-rc.2), and the TwentyTwentyThree theme. I can reproduce the issue with and without Gutenberg active.

**Comment by oandregal** [comment]
cc @artemiomorales @michalczaplinski 

Once the lightbox has been stored as a block setting, there is no way for the user to clear its value and use the global one, other than opening the code editor and remove the lightbox from the block settings.

**Comment by artemiomorales** [comment]
@oandregal Thanks for taking a look! I tried to reproduce and this actually appears to be working as expected for me. The lightbox setting, like the `resolution`, is part of the Settings `tools` dropdown and can be reset there:

<img width="1541" alt="Screenshot 2023-09-27 at 7 06 40 AM" src="https://github.com/WordPress/gutenberg/assets/5360536/0f9535b5-bcd8-451a-b8fb-611799c9b967">

https://github.com/WordPress/gutenberg/assets/5360536/27cae763-e698-4e89-8c0b-750f1ec9215d

**Comment by oandregal** [comment]
Oh, that sounds about right, Artemio. Thanks!
