### ISSUE TITLE
Missing verb in string?

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#54872]
### Description

During translation I noticed this string: https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=16400696&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc&historypage

https://plugins.trac.wordpress.org/browser/gutenberg/trunk/build/block-editor/index.js#L44010

Block name %1$s to: "%2$s".

Is it me or is there a verb missing here?

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
It has a translation comment:

> translators: %1$s: type of update (either reset or changed). %2$s: new name/label for the block

I think we're making it more complicated. There are two full translation strings; leave only the new block name as a variable.

Source: https://github.com/WordPress/gutenberg/blob/937d51e7721b891ff86581242e36311f2286e062/packages/block-editor/src/hooks/block-rename-ui.js#L49-L54

**Comment by NekoJonez** [comment]
Or just add "is" before the first variable... that would make it even more clear... but then again, conjugation of verbs is a thing.

**Comment by Mamaduka** [comment]
I was thinking of having two strings `Block name reset to: "%s".` and `Block name changed to: "%s".`.

cc @getdave

**Comment by NekoJonez** [comment]
Perfect. That would sidestep the issue with conjugation of verbs as well

**Comment by getdave** [comment]
That sounds good to me. Thank you both 👍

**Comment by Mamaduka** [comment]
Thanks for the confirmation, @getdave!

I'll create PR tomorrow. I need to head out now.
