### ISSUE TITLE
Font Library: "update" button greyed out after uploading a new font

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54881]
When using GB 16.7 and 6.4-beta1-56730, I noticed that after uploading a font, the option to select "update" is greyed out and it doesn't seem to be triggering a save event:

https://github.com/WordPress/gutenberg/assets/26996883/cb536664-e075-4011-9701-b4d26a496f7d

To replicate, open the font library, upload a new font, and notice the option to "update" isn't triggered. cc @matiasbenedetto

**Comment by faisal-alvi** [comment]
@annezazu I have tested and I am able to reproduce it.

![gb-54881](https://github.com/WordPress/gutenberg/assets/25176325/9062e241-9386-4230-9440-9cc74e53cfee)

IMO, it doesn't appear to be a bug. Once a new font is successfully uploaded, there's no need to click the "UPDATE" button, as the font is automatically uploaded and included in the fonts list. I refreshed the page and noticed that the uploaded font had been added to the list. Please let me know what you expect.

**Comment by annezazu** [comment]
Uploading anything in any other situation requires a save :) I believe the same should be the case here.

**Comment by annezazu** [comment]
Noting that using 6.4 beta 1 + GB 16.7, I can't replicate so it seems to be something just after beta 1.

**Comment by mikachan** [comment]
I've just tested this with the latest version of the Font Library (GB trunk) and I can no longer replicate. The UI has also changed slightly from when this was reported, so I believe this should now be fixed. Please re-open if the issue re-appears!
