### ISSUE TITLE
Patterns: show list of categories to pick from 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54885]
Pulling from the [FSE Outreach Program's Final Touches call for testing](https://make.wordpress.org/test/2023/09/18/fse-program-testing-call-26-final-touches/#comment-3178):

> I see that I can add a category, but I can not see which categories already exist. As I might want to place this into a pre existing category. 

Right now, this flow acts more as tags than categories to reuse what's shown in the Post Editor:

<img width="501" alt="Screenshot 2023-09-27 at 11 55 56 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/c7333a98-ae2d-42e4-a3b6-9f06c0ec466b">
<img width="283" alt="Screenshot 2023-09-27 at 11 56 19 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/3b586293-ece5-4c03-b60a-d611e0ca701e">

I think we should consider having some consistency here and show a list of categories to pick from, especially since the intent is that this will improve organization. Curious for design feedback first though :)

**Comment by glendaviesnz** [comment]
As soon as a user starts typing it does show the list of existing matching categories as shown above. The reason for going with this approach is the UX is much simpler than providing the option to select or add, eg.
<img width="285" alt="Screenshot 2023-09-28 at 9 34 43 AM" src="https://github.com/WordPress/gutenberg/assets/3629020/c0431d4b-b404-4244-be6e-2965057db084">

but as you note, let's see what design thinks.

**Comment by Ren2049** [comment]
I think the main problem of discoverability through typing could be that the're often many possible category descriptions for the same thing (e.g. CTA, call to action). 

Not sure if most users just type in the first letter and wait for suggestions to populate, or if the algorithm used for search somehow accounts for the user behavior when users type in more letters (if it still show the results from typing just the first letter). 

They may not see a previously used and forgotten category if they type in more than one letter which would lead to duplicates of categories and clutter (e.g. ca.. wont show CTA). Without an easy way to merge patterns many users would clutter and mess up their pattern library.

The [WP Engine Pattern Manager](https://github.com/studiopress/pattern-manager/) plugin uses hardcoded pattern categories. A similar approach could also make it easier to learn and memorize and integrate with public pattern libraries, or help the compatibility across themes if everybody uses the same category names.

A similar approach works already for new templates where you can pick the name from an existing list.

**Comment by glendaviesnz** [comment]
> The [WP Engine Pattern Manager](https://github.com/studiopress/pattern-manager/) plugin uses hardcoded pattern categories.

It seems potentially limiting to force users to select from a hardcoded list, particularly as we know some sites have 3000+ patterns, and will have very varied uses for them, more so than templates probably. But I am sure we can find a balance between making it easy to discover existing categories and adding new ones.

**Comment by Ren2049** [comment]
Maybe provide a baseline with an option to customize, like with templates. We can steal the category names from popular libraries designers are used to for the baseline ones.

**Comment by glendaviesnz** [comment]
This was fixed by https://github.com/WordPress/gutenberg/pull/55024
