### ISSUE TITLE
Font Library: show allowed upload format and display errors for incorrect uploads

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54882]
Pulling [this feedback from the FSE Outreach Program](https://make.wordpress.org/test/2023/09/18/fse-program-testing-call-26-final-touches/#comment-3177) for consideration for [stage 3 of the Font Library work](https://github.com/WordPress/gutenberg/issues/53926):

>I tried to upload a .zip on purpose but got no errors. It may be nice to have or suggest allowed font formats and a confirmation notification when one gets uploaded.

**Comment by annezazu** [comment]
[Another piece of feedback](https://make.wordpress.org/test/2023/09/18/fse-program-testing-call-26-final-touches/#comment-3178) on this note from the same call for testing:

>Went to fonts.google.com and downloaded Fuggles.zip. It looks like I have to unzip the folder and then upload the Fuggles-Regular.ttf font file.

**Comment by Mamaduka** [comment]
Thre's already an issue for improving the error messages - #54777.

**Comment by annezazu** [comment]
I saw this as slightly different but, for consolidations' sake, I'll close and add the feedback there :)
