### ISSUE TITLE
@wordpress/scripts has some deprecated NPM modules

### ISSUE THREAD

**Issue by stein2nd** [WordPress/gutenberg#54895]
### Description

"intl-messageformat-parser@1.8.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser"

### Step-by-step reproduction instructions

1. delete folder "node_modules" and file "package-lock.json" at project root directory
2. "ncu"
3. "ncu -u"
4. "npm install --force"

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/531628/2b8aea9f-1df5-4795-95e2-1bad84376ff8)

## System:
 - OS: macOS 14.0
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 4.41 GB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 20.7.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.19 - ~/.nodebrew/current/bin/yarn
 - npm: 10.1.0 - ~/.nodebrew/current/bin/npm
 - pnpm: 8.6.12 - ~/.nodebrew/current/bin/pnpm
## npmPackages:
 - @wordpress/scripts: ^26.13.0 => 26.13.0 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by gziolo** [comment]
We need to wait until the Gutenberg repository starts using Node 18 or higher because `lighthouse` dropped support for Node 16 with [`v11.0.0`](https://github.com/GoogleChrome/lighthouse/releases/tag/v11.0.0) that was released after currently used `10.4.0`.
