### ISSUE TITLE
Font size "huge" does not respect the size specified in theme.json

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#54918]
### Description

Let's say, there is a font size called `huge` that is 100px in a theme.

On the front of the site, an element with the `huge` size appears 100px, as expected. However, in the editor, it appears 42px.

To demonstrate the issue, I've added a font size, `huge` to TT3's `theme.json`, and changed the size of the heading in `home.html`

```
{
	"settings": {
		"typography": {
			"fontSizes": [
				{
					"size": "100px",
					"slug": "huge",
					"name": "Huge"
				}
			]
		}
	}
}
```

| Front of site | Editor |
| ----------- | ----------- |
| ![localhost local_ (10)](https://github.com/WordPress/gutenberg/assets/908665/1f589049-4c86-4913-8a23-1f73af473452) | ![localhost local_wp-admin_site-editor php_canvas=edit (1)](https://github.com/WordPress/gutenberg/assets/908665/e99473a5-424f-4e6f-a542-6e567dcb23f7) |

The size is overridden by this, which comes from [here](https://github.com/WordPress/gutenberg/blob/626e1ef7be5b4cffea9d96fab92483210671a3ea/packages/block-library/src/editor.scss#L68). The `!important` seems to be the problem.

![Screenshot 2023-09-28 at 20 08 29](https://github.com/WordPress/gutenberg/assets/908665/0f2fbe79-7f70-4da3-ac1d-dd2a941ebb18)

If I deactivate Gutenberg (trunk), the font size will return to 100px in the editor.

![localhost local_wp-admin_site-editor php_canvas=edit (3)](https://github.com/WordPress/gutenberg/assets/908665/24803acc-3ab7-4f70-a971-7f5a1ceb0240)

### Step-by-step reproduction instructions

1. Activate a theme that has a font size called `huge` or add the size like above in a theme.json
2. Specify a text element like a heading to use the `huge` size.
3. See the discrepancy in size between in the editor and the front of the site. 

### Environment info

WP 6.3.1.
Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by iamtakashi** [comment]
I'm still having this issue. If a theme uses a size with a slug `huge`, the huge size text will be always 42px in the editor instead of the value set in the theme.json.

**Comment by t-hamano** [comment]
Thanks for the report.

This issue is similar to #59701 and I believe it has already been resolved. Tested with WP6.5-RC1.

I would like to close this issue, but if this issue is not resolved in the latest Gutenberg or WP6.5, please let me know.

### Editor

![editor](https://github.com/WordPress/gutenberg/assets/54422211/4191a6fb-91e4-4c83-959c-48f86c1c557a)

### Front end

![front-end](https://github.com/WordPress/gutenberg/assets/54422211/78e63b20-4692-454b-9118-2ecca17e6e9e)
