### ISSUE TITLE
Tracking issue: 6.4 About page assets 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54917]
**Due date: Oct 10**

As part of efforts for the 6.4 release and related assets, this is a tracking issue to cover the work needed for the 6.4 About page features aka everything outside of the overall header image. I imagine this will overlap with the highlight grid and microsite so let’s align there! Tagging in helpers for these efforts for awareness: @richtabor @jasmussen @marko-srb but please jump in anyone who wants to help.

**Comment by jasmussen** [comment]
Definitely. I'm working on the highlight grid (#54808) today and hopefully we can reuse some of that material for screenshots.

**Comment by nudgeD** [comment]
@jasmussen Are there any screenshots ready now that I would be able to get started with?

**Comment by jasmussen** [comment]
I did not have edit access to the main 6.4 About Page Figma file, so I've been working in [this one](https://www.figma.com/file/VuHh6dbBUQHFhbOYTm34f0/Highlight-Grid-draft?type=design&node-id=0%3A1&mode=design&t=jTYUSTaJFClawi2c-1) for the highlight grid, in case that can work as a starting point.

**Comment by nudgeD** [comment]
@jasmussen I've been able to use a few of the screenshots you created but felt the Font Library deserved more presence on the About page with a larger screenshot. Would you mind giving me some feedback on it? I've added you to the main 6.4 About Page Figma file.

**Comment by jasmussen** [comment]
Thanks for the ping, and the edit access 🙏 

I left a ton of comments, please don't be discouraged by them, for this first iteration it was a big step to collect everything. I'm also happy to try and take a stab at an iteration, based on the notes I left, just let me know, I'd prefer to avoid stepping on any toes.

**Comment by rmartinezduque** [comment]
Hi @jasmussen, @nudgeD 👋 Where could I find all the About page assets so MarComms can reuse them on social media and the general release announcement in /news? [Is this Figma file](https://www.figma.com/file/jTjcQf8NF551cxunoAIOeC/About-Page-6.4?type=design&node-id=927-2&mode=design&t=7JyH1rdHOudh9sB2-0)?

cc @richtabor, as I think you helped adapt some About page assets for the final /news post in 6.3. If you could help with this again, it would be great. Let me know, thanks! 🙏

**Comment by nudgeD** [comment]
Hi @rmartinezduque 

That Figma is correct!

I also have the same assets ready for Jessica here, but the webp images still need to be reviewed by @richtabor 
https://drive.google.com/drive/folders/189smUR_FsQBety0-grdw2FROAtu_-JLL

**Comment by richtabor** [comment]
> cc @richtabor, as I think you helped adapt some About page assets for the final /news post in 6.3. If you could help with this again, it would be great. Let me know, thanks! 🙏

Sure thing!

**Comment by rmartinezduque** [comment]
Hi @richtabor! I just wanted to circle back regarding the About page assets for the final /news post. We would need them before November 6. Would you still be able to help? Thank you!

**Comment by richtabor** [comment]
> Hi @richtabor! I just wanted to circle back regarding the About page assets for the final /news post. We would need them before November 6. Would you still be able to help? Thank you!

Sure thing. I'll reference the sizes from the [6.3 release post](https://wordpress.org/news/2023/08/lionel/). Do we have content for the post written yet?

**Comment by rmartinezduque** [comment]
Thanks, @richtabor! Let me know if there's anything I can help with. If I'm not mistaken, the dimensions of those images are 1024 × 666.

> Do we have content for the post written yet?

Yes, the content for the post is [here](https://docs.google.com/document/d/1UPd8GbBdh9yNj4BerxEb74veMtk5WJ_OxVY4FF4mGVI/edit?usp=drive_link)—now being reviewed by MarComms. For context, the content is the same or similar to the About page and other release deliverables/comms.

**Comment by richtabor** [comment]
> Hi @richtabor! I just wanted to circle back regarding the About page assets for the final /news post. We would need them before November 6. Would you still be able to help? 

@rmartinezduque I've uploaded the suite of images to the [drive](https://drive.google.com/drive/folders/189smUR_FsQBety0-grdw2FROAtu_-JLL). Here are copies below. What do you think?

<img width="680" alt="tt4" src="https://github.com/WordPress/gutenberg/assets/1813435/1737cf04-6113-4519-acbe-9b624aef86fa">

<img width="680" alt="writing" src="https://github.com/WordPress/gutenberg/assets/1813435/783a5e30-d9c0-42f1-91eb-9b7467d9aec9">

<img width="680" alt="commands" src="https://github.com/WordPress/gutenberg/assets/1813435/0fb52831-51d4-4176-9e57-d97cbee2f821">
<img width="680" alt="categorize-patterns" src="https://github.com/WordPress/gutenberg/assets/1813435/67799adf-c942-4902-b46e-a2075b781515">
<img width="680" alt="design-tools" src="https://github.com/WordPress/gutenberg/assets/1813435/1e1fce45-16ac-4a60-9b16-20b9ebba323e">
<img width="680" alt="lightbox" src="https://github.com/WordPress/gutenberg/assets/1813435/402a4a82-7fee-43c1-b6e1-8434308dab44">
<img width="680" alt="rename" src="https://github.com/WordPress/gutenberg/assets/1813435/18c8d0e7-c8ee-4ee8-9ac1-cb10a7583340">
<img width="680" alt="list-view-images" src="https://github.com/WordPress/gutenberg/assets/1813435/8138eafe-3b24-457e-a807-ede5517a754b">
<img width="680" alt="exporting-patterns" src="https://github.com/WordPress/gutenberg/assets/1813435/bcbd14a1-13dd-4467-86a2-aebf7caa2a76">
<img width="680" alt="block-hooks" src="https://github.com/WordPress/gutenberg/assets/1813435/c1fae08a-f26f-4d34-a608-abf05aa381e6">

**Comment by rmartinezduque** [comment]
Thank you for these beautiful assets, @richtabor! The [6.4 announcement](https://wordpress.org/news/2023/11/shirley/ ) is live, so I think we can safely close this issue. :)

**Comment by richtabor** [comment]
Noting that the welcome banner was not updated for 6.4. As an aside, I wonder if we _need_ a release branded welcome banner for this anyhow. 

![CleanShot 2023-11-13 at 11 52 33](https://github.com/WordPress/gutenberg/assets/1813435/d19231f6-4330-4206-80ac-b1bf62f85302)

**Comment by rmartinezduque** [comment]
> Noting that the welcome banner was not updated for 6.4.

Thanks, @richtabor. @estelaris, were you able to look into this? Is there anything we can help with to get this updated with a 6.4 release-branded banner?

**Comment by annezazu** [comment]
Closing this as complete in terms of the overall assets. If more work is needed, let's open a more specific issue to follow up.
