### ISSUE TITLE
Template Revision showing  WP_Text_Diff_Renderer_Table::__isset():  errors

### ISSUE THREAD

**Issue by kafleg** [WordPress/gutenberg#54925]
### Description

When clicking on the template revision button, i got this error list, 

![image](https://github.com/WordPress/gutenberg/assets/13062231/04499022-b332-4ad1-8719-75256e7705ec)

Deprecated: WP_Text_Diff_Renderer_Table::__isset(): The property `_title` is not declared. Checking `isset()` on a dynamic property is deprecated since version 6.4.0! Instead, declare the property on the class. in C:\laragon\www\paidreviews\wp-includes\functions.php on line 6034

Deprecated: WP_Text_Diff_Renderer_Table::__isset(): The property `_title_left` is not declared. Checking `isset()` on a dynamic property is deprecated since version 6.4.0! Instead, declare the property on the class. in C:\laragon\www\paidreviews\wp-includes\functions.php on line 6034

Deprecated: WP_Text_Diff_Renderer_Table::__isset(): The property `_title_right` is not declared. Checking `isset()` on a dynamic property is deprecated since version 6.4.0! Instead, declare the property on the class. in C:\laragon\www\paidreviews\wp-includes\functions.php on line 6034

Deprecated: WP_Text_Diff_Renderer_Table::__isset(): The property `_title` is not declared. Checking `isset()` on a dynamic property is deprecated since version 6.4.0! Instead, declare the property on the class. in C:\laragon\www\paidreviews\wp-includes\functions.php on line 6034

Deprecated: WP_Text_Diff_Renderer_Table::__isset(): The property `_title_left` is not declared. Checking `isset()` on a dynamic property is deprecated since version 6.4.0! Instead, declare the property on the class. in C:\laragon\www\paidreviews\wp-includes\functions.php on line 6034

Deprecated: WP_Text_Diff_Renderer_Table::__isset(): The property `_title_right` is not declared. Checking `isset()` on a dynamic property is deprecated since version 6.4.0! Instead, declare the property on the class. in C:\laragon\www\paidreviews\wp-includes\functions.php on line 6034

Deprecated: WP_Text_Diff_Renderer_Table::__isset(): The property `_title` is not declared. Checking `isset()` on a dynamic property is deprecated since version 6.4.0! Instead, declare the property on the class. in C:\laragon\www\paidreviews\wp-includes\functions.php on line 6034

Deprecated: WP_Text_Diff_Renderer_Table::__isset(): The property `_title_left` is not declared. Checking `isset()` on a dynamic property is deprecated since version 6.4.0! Instead, declare the property on the class. in C:\laragon\www\paidreviews\wp-includes\functions.php on line 6034

Deprecated: WP_Text_Diff_Renderer_Table::__isset(): The property `_title_right` is not declared. Checking `isset()` on a dynamic property is deprecated since version 6.4.0! Instead, declare the property on the class. in C:\laragon\www\paidreviews\wp-includes\functions.php on line 6034

Deprecated: WP_Text_Diff_Renderer_Table::__isset(): The property `_title` is not declared. Checking `isset()` on a dynamic property is deprecated since version 6.4.0! Instead, declare the property on the class. in C:\laragon\www\paidreviews\wp-includes\functions.php on line 6034

Deprecated: WP_Text_Diff_Renderer_Table::__isset(): The property `_title_left` is not declared. Checking `isset()` on a dynamic property is deprecated since version 6.4.0! Instead, declare the property on the class. in C:\laragon\www\paidreviews\wp-includes\functions.php on line 6034

Deprecated: WP_Text_Diff_Renderer_Table::__isset(): The property `_title_right` is not declared. Checking `isset()` on a dynamic property is deprecated since version 6.4.0! Instead, declare the property on the class. in C:\laragon\www\paidreviews\wp-includes\functions.php on line 6034

### Step-by-step reproduction instructions

1. Go to Appearance > Editor 
2. Do some changes in the templates 
3. Go back to the template list in the editor and the templates that you recently edited
4. Click on the last modified button and you will see the error. 

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/13062231/42ee151c-668f-49db-b098-d930cb30c783)

### Environment info

- WordPress 6.4 Beta 1
- Gutenberg Version 16.7.0 (Downloaded from org)
- PHP 8.1
- Windows 11
- No other plugin activated except Gutenberg 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I would like to close this issue as I believe this is an issue that should be fixed in core and a core ticket exists.

https://core.trac.wordpress.org/ticket/59431
