### ISSUE TITLE
Lightbox expand doesn't work with Gallery image

### ISSUE THREAD

**Issue by lwangdu** [WordPress/gutenberg#54921]
### Description

I am testing light box with WP 6.4-beta1 without Gutenberg plugin. Gallery image expand doesn't work  when I click on a gallery image on the front end. Here is screen recording: (https://share.vidyard.com/watch/Kcw4vq5ufPMLMLCA5cRkpS?)

### Step-by-step reproduction instructions

Create a gallery page
than click on image and enable expand and look on front end the lightbox doesn't work. Please see the above screen recording.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by properlypurple** [comment]
I've tested this, and I can consistently reproduce this with WP 6.4-beta1-56741, with both 2024 and 2023 theme. It works as expected when Gutenberg 16.7.0 is active.

**Comment by annezazu** [comment]
I'm unable to replicate this with 6.4-beta1-56752, with or without Gutenberg 16.7 installed and active. I'm going to close this out as a result.

**Comment by alizehctl** [comment]
I'm using 6.4.3, and I can't see the lightbox option for images that are in a gallery. Was this feature removed?
