### ISSUE TITLE
Image block uses `esc_attr()` wrongly, passing an array

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#54930]
### Description

Introduced in #3851 / badc3441f1bd94fdad93825a188694b093ebf403, this causes PHP warnings when using the Image block with Lightbox enabled.

Why?

The `block_core_image_render_lightbox()` function passes the results of `wp_get_global_styles()` directly to `esc_attr()`.

`wp_get_global_styles()` can return an array, but `esc_attr()` works on strings.

### Step-by-step reproduction instructions

1. Insert image block with lightbox (I was using the 2021 theme)
2. See warning

### Environment info

WP trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by swissspidy** [comment]
FYI @artemiomorales @michalczaplinski since you worked on that PR.

This should be fixed for the next 6.4 Beta

**Comment by SantosGuillamot** [comment]
Thanks for reporting this. I believe it is the same problem reported [here](https://github.com/WordPress/gutenberg/issues/54682), which is being handled in [this pull request](https://github.com/WordPress/gutenberg/pull/54837).

**Comment by swissspidy** [comment]
Indeed. Thanks.
