### ISSUE TITLE
Progress Bar Block

### ISSUE THREAD

**Issue by mgozdis** [WordPress/gutenberg#54937]
## What problem does this address?
Users would like to have a "Progress Bar Block" available that allows them to display a progress bar either as a typical horizontal progress bar or a circular progress bar which they can manually update to show progress of something like a donation drive or fundraiser.

This functionality is available in third-party plugins like Ultimate Blocks, Essential Blocks, etc. but the plugins occasionally break sites and cause fatal errors. Users would like to have this block as core functionality so as to not rely on third-party plugins that break their site.

## What is your proposed solution?

For reference, these are some examples of the block in third-party plugins: 

- https://ultimateblocks.com/progress-bar-block/
- https://essential-blocks.com/demo/progress-bar/
- https://wpstackable.com/progress-bar-block/
- https://www.gutentor.com/blocks/progress-bar-block/

**Comment by t-hamano** [comment]
I think that block has been proposed in #34219, so I would like to close it.

If you have any ideas, please comment on the issue!
