### ISSUE TITLE
Font Library: Variant list does not update immediately following upload of new variant

### ISSUE THREAD

**Issue by ironprogrammer** [WordPress/gutenberg#54945]
### Description

On the font management Library tab, a font variant's detail list is not updated immediately following upload of a new variant to that same font. I expect the variant list to include newly uploaded variants when switching from the Upload tab to Library.

Note that the variant list does update _after_ navigating back to the full registered fonts list and re-entering the font detail screen.

### Step-by-step reproduction instructions

1. Open the font management modal.
2. In the Upload tab, add a single variant of a new font, and confirm the upload succeeded.
3. Click the Library tab, noting "1/1 variants" for the newly added font.
4. Click into the font's variant detail list, noting the single variant that was added.
5. Click the Upload tab, and add a different variant for that same font, and confirm the upload succeeded.
6. Click the Library tab, noting that the new variant is missing from the list.
7. Click the "back" button under the Library tab to view the registered fonts list, then click back into the new font's variant detail list.
8. Note that the list now includes the additional variant.

### Screenshots, screen recording, code snippet

_Demonstration to reproduce issue:_
![library-list-refresh](https://github.com/WordPress/gutenberg/assets/824344/6f6120a7-82a4-4489-b9c7-88014bf2e22f)

### Environment info

- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 13.6
- Browser: Safari 16.6, Google Chrome 117.0.5938.132
- Server: nginx/1.25.2
- PHP: 7.4.33
- WordPress: 6.4-beta1-56730-src
- Theme: twentytwentythree v1.2
- Active Plugins:
 - gutenberg v16.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ironprogrammer** [comment]
This is something to consider when addressing #54779.

**Comment by mikachan** [comment]
I've just tested this out using the reproduction steps above and I can successfully replicate this.
