### ISSUE TITLE
Layout issues in Row block with Yoast plugin active

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#54943]
### Description

As [reported](https://wordpress.slack.com/archives/C02QB2JS7/p1696015318069139?thread_ts=1695826993.412049&cid=C02QB2JS7) in Slack, I am experiencing an issue with layout (Row block inside of Group block) and the "Space between items" setting not being honored with Yoast plugin active.

### Step-by-step reproduction instructions

1. Add a Group block, set to Full-width layout.
2. Add a Row block inside, set to Wide-width layout, add two items, and select "Space between items" setting.
3. Activate Yoast plugin.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/486261/74ffa4ac-0296-4f32-aa30-1c73038caf37

### Environment info

WordPress 6.4-beta1, with and without Gutenberg 16.7 active.
TT3 theme active.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bgardner** [comment]
Worth noting that this is _only_ an issue with the block editor, as the front end operates as expected.

**Comment by Mamaduka** [comment]
You can also reproduce the issue by enabling the Custom Fields. This is probably related to the editor switching to a non-framed canvas.

## Screenshot
![CleanShot 2023-09-30 at 10 07 51](https://github.com/WordPress/gutenberg/assets/240569/c59fbc24-811d-41e2-b1cf-b0c53a89d544)

**Comment by t-hamano** [comment]
I found that when the editor is not an iframe, the style is not applied because the `.editor-styles-wrapper` selector is nested in the output container class.

![editor-styles-wrapper](https://github.com/WordPress/gutenberg/assets/54422211/dfbc2d29-7075-4301-985a-08db4d283ae2)

**Comment by Mamaduka** [comment]
I think the regression is a side-effect of the following changes:

* #46752 - makes only non-iframed editor styles `scoped`. It is not an issue itself, but it makes it harder to catch the bug when using the Gutenberg plugin and metaboxes aren't active.
* #54466 - switched layout styles to use new styles override API. Layout styles are rendered via the `EditorStyles` component, so scoping is applied for non-iframed editors.

The `getLayoutStyle` method already[ appends the wrapper scope](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/layouts/utils.js#L11-L35) to the generated CSS, so we get double wrapping.

**Comment by t-hamano** [comment]
I was also looking for the cause of this problem, and through git bisect I was able to identify that #54466 caused this problem.

**Comment by Mamaduka** [comment]
I tried fixing this without changing the way layout styles are generated — result #54981.

**Comment by bgardner** [comment]
@Mamaduka @glendaviesnz @t-hamano @annezazu

This issue does not appear to be resolved, as I just tested again with WP 6.4 Beta-2. 

https://github.com/WordPress/gutenberg/assets/486261/8e7fe61e-87ae-46b4-a618-d237d7657dfe

**Comment by mikachan** [comment]
Hey @bgardner. https://github.com/WordPress/gutenberg/pull/54981 wasn't included in Beta 2 (we'd already synced the GB Beta 2 fixes when it was merged), but it will go into Beta 3. In the meantime, I can test this as soon as https://github.com/WordPress/gutenberg/pull/54981 has been cherry-picked, ahead of Beta 3.

**Comment by bgardner** [comment]
@mikachan Ah, gotcha. For some reason I thought it was in Beta 2, so I'll test again once 3 goes out. Appreciate the insight.

**Comment by mikachan** [comment]
Confirming that I've tested these changes as part of the updates for 6.4 Beta 3, and I can no longer see this issue. @bgardner It would be amazing if you could also double-check this once Beta 3 is released! 🙇
