### ISSUE TITLE
Add a "full reset" option to the Site Editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#54958]
## What problem does this address?
I often find that I need to go to three places to reset changes:

1. The template management screen
2. The template part management screen
3. The styles sidebar

On the template and part management screens, I miss an option to reset all my items with one click.

In general I miss an option to reset all my user made changes, so both custom CSS, block style changes, template part markup changes, and template markup changes.

The option for me is to install and use a third party reset plugin, but those delete all my content and deactivate my current theme and plugins.

**Comment by carolinan** [comment]
A command in the command pallet would work well too.

**Comment by annezazu** [comment]
Curious to hear from other @WordPress/block-themers around this!

**Comment by colorful-tones** [comment]
I would find it useful for testing. However, I'm not certain whether it would benefit everyday builders. 

The command palette integration might be a good place to start. 

I wonder if it could/should be tied to a `wp-config.php` constant, like `WP_DEVELOPMENT_MODE`, `WP_ENVIRONMENT_TYPE`, or `WP_DEBUG`. This would then be a developer tool to utilize. 🤔

**Comment by ramonjd** [comment]
I'm a fan of this suggestion! I think I'm biased because I'm constantly testing and resetting. 

Agree that we could trial it it dev mode to gauge its usefulness. 

Or, and please ignore the shoddy UI, but what if it were tucked it away in the actions drop down? 


<img width="1184" alt="Screenshot 2023-10-09 at 10 49 07 am" src="https://github.com/WordPress/gutenberg/assets/6458278/598e1f29-c112-4b7f-9696-53a57f386c0b">

Where else could it live that wouldn't be as awful as the screenshot above? 😄

**Comment by richtabor** [comment]
> A command in the command pallet would work well too.

Yea, maybe with a verify perhaps. Wouldn't want it too easy to reset everything. 

> I wonder if it could/should be tied to a wp-config.php constant, like WP_DEVELOPMENT_MODE, WP_ENVIRONMENT_TYPE, or WP_DEBUG. This would then be a developer tool to utilize. 🤔

Interesting idea.

**Comment by scruffian** [comment]
Love this idea, yes please.

**Comment by ramonjd** [comment]
> A command in the command pallet would work well too.
> Yea, maybe with a verify perhaps. Wouldn't want it too easy to reset everything.

I think this could be a nice way to introduce the feature without being too obtrusive 👍🏻 

_Edit_: possibly with a "reset" view before a verification screen?

<img width="669" alt="Screenshot 2023-10-13 at 11 31 19 am" src="https://github.com/WordPress/gutenberg/assets/6458278/5327243a-364a-42da-94e3-99a7e61b90a1">

**Comment by carolinan** [comment]
Maybe it would be better suited for the Create Block Theme plugin?

**Comment by mikachan** [comment]
> Maybe it would be better suited for the Create Block Theme plugin?

Yeah good idea, sounds like this might be worth trying out there first. I've opened an issue here: https://github.com/WordPress/create-block-theme/issues/686.

Also related to this issue: https://github.com/WordPress/create-block-theme/issues/494.

**Comment by richtabor** [comment]
CBT could add the command for the command palette. Would be a good case for plugins adding relevant commands.

**Comment by carolinan** [comment]
I think we can close this issue and keep the one in the other plugin repo.
