### ISSUE TITLE
Add a dedicated doc for getting started with `wp-scripts` (subpage of Developer Environment)

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#54961]
This doc is part of the larger Getting Started overhaul here: https://github.com/WordPress/gutenberg/issues/54124

<img width="1528" alt="image" src="https://github.com/Automattic/dotorg-devrel/assets/4832319/37654607-7478-4b9a-8cd3-b278b6e45439">

[Excelidraw link](https://excalidraw.com/#room=8c538e461500a1fe8523,7pSlj3w0awiHsHxiWS6tCw)

**Comment by Mamaduka** [comment]
It looks like we've duplicate issues - #54960.

**Comment by juanmaguitar** [comment]
> It looks like we've duplicate issues - https://github.com/WordPress/gutenberg/issues/54960.

Hi @Mamaduka
#54960 & #54961 refer to different tasks.
They're both subtasks of #54124 and one is about creating an introductory guide for `create-block` and the other one for `wp-scripts`
