### ISSUE TITLE
An error when manually dispatching store action

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#54962]
While working on #54951, I noticed an error when manually dispatching to store action via DevTool's console. Then, the editor crashes when I move the focus inside the canvas.

The reproduction method isn't consistent, but I can trigger an error every second or third try.

## Error

```
You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.
```

## Step-by-step reproduction instructions
1. Open a post.
2. Run the following action via DevTools - `wp.data.dispatch( 'core/edit-post' ).removeEditorPanel( 'post-status' );`.
3. Try a few times until the error is triggered. I usually refresh the page before trying it again.

## Screencasts

https://github.com/WordPress/gutenberg/assets/240569/acd2951a-3baf-4623-a031-5419dabbfb85

![CleanShot 2023-09-30 at 14 18 11](https://github.com/WordPress/gutenberg/assets/240569/7f9ddd3f-b06f-43fa-a745-b008181cefab)

![CleanShot 2023-10-02 at 12 36 14](https://github.com/WordPress/gutenberg/assets/240569/79d74e9b-d791-4b03-87ce-63169e640d61)

**Comment by Mamaduka** [comment]
Cc @jsnajdr, @youknowriad.

**Comment by jsnajdr** [comment]
I cannot reproduce this locally at all. One thing that could help debugging is to place a logpoint in the Redux code that calls the reducer:

https://github.com/reduxjs/redux/blob/master/src/createStore.ts#L297-L302

and to log which action to which reducer is being dispatched when this error happens. On the screenshots with stack traces, I don't see any reducer on the call stack.

**Comment by Mamaduka** [comment]
This is odd. As soon as I start logging Redux store calls. I can no longer reproduce the error, but it's back when I disable the logger.

I'll try to record a Reply.io later today.

**Comment by felipevelzani** [comment]
I added the label "needs more info" so that we can keep track of it. :)

**Comment by Mamaduka** [comment]
I was testing a PR and getting the same error 99% of the time when using the `wp.blocks.unregisterBlockType()` method.

**Comment by Mamaduka** [comment]
I'm going to close the issue. I couldn't track down the source, and it doesn't seem to affect the block editor's daily usage.
