### ISSUE TITLE
Categories Block content doesn't match categories

### ISSUE THREAD

**Issue by adammarton** [WordPress/gutenberg#5497]
## Issue Overview

When adding a Categories block, displayed categories doesn't match native categories display.

## Steps to Reproduce (for bugs)

* Create a new post
* Insert a Categories block
* Assign a new category

## Expected Behavior

I want to see all assigned categories.

## Current Behavior

Block just displays 'Uncategorized'.

## Screenshots / Video

![image](https://user-images.githubusercontent.com/5418343/37143917-d4927e42-22bc-11e8-9112-a1356b5e8a8e.png)

## Environment

A clean install of [WordPress](https://hub.docker.com/r/library/wordpress/) with the latest build of Gutenberg.

**Comment by karmatosed** [comment]
I am unable to replicate this, if I assign a new category it shows on front. I would suggest there is either a plugin or something else at play here. If you can retest we can always reopen.
