### ISSUE TITLE
Help text for ToggleControl doesn't behave in a similar manner to SelectControl

### ISSUE THREAD

**Issue by websevendev** [WordPress/gutenberg#5498]
## Issue Overview

I have 2 inspector controls as such:

```
<wp.blocks.InspectorControls key="segment-controls">
	<wp.components.SelectControl
		label={__('Size')}
		help={__('A segment can have different sizes.')}
		options={SIZES}
		value={size}
		onChange={value => setAttributes({size: value})}
	/>
	<wp.components.ToggleControl
		label={__('Basic')}
		help={__('A basic segment has no special formatting.')}
		checked={basic}
		onChange={() => setAttributes({basic: !basic})}
	/>
</wp.blocks.InspectorControls>
```

Both have `help` props. I would expect them to behave in a similar fashion, but here is the current behaviour:
![](https://i.imgur.com/qv3zX77.png)

A `<SelectControl>` displays the help text below the select, while `<ToggleControl>` displays it's contents as flex row. Seems like `.blocks-toggle-control` has `display: flex` assigned without taking account of the fact that the `<BaseControl>` can render help text.

## Expected Behavior

![](https://i.imgur.com/Ab3QFUW.png)

## Related Issues and/or PRs

Perhaps there are more controls that don't handle the help text. Perhaps `<BaseControl>` should render help text in a separate container, so any alignment applied to the children won't affect it.

**Comment by jasmussen** [comment]
Great ticket. Thought I could fix it as part of some ongoing work I'm doing, so I assigned myself. Turns out it's unrelated. Unassigning to let someone else tackle it.
