### ISSUE TITLE
Button: Style variation name is different in the toolbar vs. the inspector 

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#54987]
I noticed the button block’s style variation is named “Default” in the inspector (which I consider the primary method for applying variations) and “Fill” in the block toolbar. 

These should be consistent. But I’m also curious if style variations should persist in both locations anyhow https://github.com/WordPress/gutenberg/issues/54986. 

<img width="1110" alt="CleanShot 2023-09-13 at 12 38 10" src="https://github.com/WordPress/gutenberg/assets/1813435/4e4af175-579a-4f68-947f-8d631ee88927">

**Comment by carolinan** [comment]
Good find.

This becomes even more confusing if a plugin or theme registers a style and sets that as the default with
[`isDefault: true`](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-styles/)

To test, I added this to functions.php in Twenty Twenty-Four:
```
		register_block_style(
			'core/button',
			array(
				'name'         => 'test',
				'label'        => __( 'test style', 'twentytwentyfour' ),
				'inline_style' => "",
				'is_default'   => true,
			)
		);

```

The UI shows two button styles named default:
<img width="1221" alt="The button block style setting with 3 options: Default, Default, and Outline" src="https://github.com/WordPress/gutenberg/assets/7422055/03f87afe-942b-4c06-810a-8b80a97fc73b">

**Comment by carolinan** [comment]
I think the label is wrong though, block variations are the row/stack, columns and query loop variations.
