### ISSUE TITLE
Use namespace for textdomain when --no-plugin is in use

### ISSUE THREAD

**Issue by samhermes** [WordPress/gutenberg#54980]
### Description

When scaffolding a new block with `@wordpress/create-block` and the `--no-plugin` flag, the textdomain in block.json is being set to the slug of the block. In the case where a plugin has already been set up (when `--no-plugin` would be used) and additional blocks are being added to it, this means that each block has the wrong textdomain. It's more likely that the namespace for each block will be better to use for the textdomain, as it should be consistent across blocks. Alternatively, a custom textdomain could be set up during the interactive scaffolding process, or the ability to set a default in the [block metadata template](https://github.com/WordPress/gutenberg/blob/trunk/packages/create-block/docs/external-template.md#external-project-templates).

### Step-by-step reproduction instructions

1. Run `npx @wordpress/create-block --no-plugin` in the blocks directory of an existing plugin.
2. Respond to the questions, giving the block a slug and a namespace.
3. After the block is scaffolded successfully, open block.json and see that the `textdomain` has been set to the slug instead of the namespace.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
Thank you for the report. That's a valid issue because we assume that the `slug` used for the plugin is the same as `textdomain` which is the default for WP plugins, but obviously it could get customized:

https://github.com/WordPress/gutenberg/blob/fce345dc4791e7d1b2362a6c5965785b0ab7441c/packages/create-block/lib/scaffold.js#L92

The solution would be to offer another prompt that shows up in the plugin section in the regular flow, but also when creating a block without a plugin.

**Comment by vampdroid** [comment]
Hi, I created [this](https://github.com/WordPress/gutenberg/pull/57197) PR which makes another prompt in the block scaffolding flow to add `textdomain` which will further be added in block.json meta data. LMK if there are any suggestions or changes to be made in this 🙌 .

**Comment by gziolo** [comment]
@vampdroid, thank you for working on it. I hope it won't take too long to review and test it. I'll keep an eye on it.

**Comment by ryanwelcher** [comment]
@vampdroid I added some comments to the PR.

**Comment by vampdroid** [comment]
Thanks a lot @gziolo and @ryanwelcher 🙇

**Comment by gziolo** [comment]
Resolved with https://github.com/WordPress/gutenberg/pull/57197.
