### ISSUE TITLE
Navigation Block submenus not closing properly on iPad

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#54991]
### Description

Navigation Block submenus fail to close when you tap away from the submenu, or open others. Instead, they remain open, and can overlap each other.

### Step-by-step reproduction instructions

1. Set up a site with a Navigation Block containing submenus (it helps to create a couple dropdowns in the menu)
2. Launch the site on an iPad or test environment for an iPad
3. Explore opening submenus along the page and trying to close them without refreshing/navigating away from the page

### Screenshots, screen recording, code snippet

**Firefox Browser Responsive Tools**

https://github.com/WordPress/gutenberg/assets/27249804/78720682-08fd-4b38-a0a3-77e73c390f0f

**BrowserStack with iPad 10th Generation > Safari**

https://github.com/WordPress/gutenberg/assets/27249804/2ec3978e-6d9e-4854-a378-5b72b74252a8

### Environment info

- WP 6.3.1
- Gutenberg 16.7.0

Also replicated on Gutenberg 16.6.0 and 16.5.1 (I didn't rebuild the block each time though - just switched between versions after building the navigation block on 16.7.0)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Adding this to 6.4 to be safe. I tried to replicate with 6.4 beta 2 and GB 16.7 but wasn't able to replicate when simulating an ipad environment for Chrome or Safari:

https://github.com/WordPress/gutenberg/assets/26996883/1a093c0c-5adb-43a6-8c68-da506737b58d

**Comment by tellthemachines** [comment]
I can reproduce this in the xcode simulator on a 10th gen iPad with iOS 17.0 on Safari:

<img width="666" alt="Screenshot 2023-10-10 at 5 11 47 pm" src="https://github.com/WordPress/gutenberg/assets/8096000/69643329-4c69-4bfd-8175-6cb526e3006d">

On a Navigation with a Search block it's particularly bad 😬 

<img width="384" alt="Screenshot 2023-10-10 at 5 15 13 pm" src="https://github.com/WordPress/gutenberg/assets/8096000/5c93a6ba-00ba-463a-8cc5-4eaaf427b68f">

Edit: I can also reproduce it in Safari on macOS Sonoma. Could just be an issue with the latest OS versions from Apple 🤔

**Comment by tellthemachines** [comment]
As far as I can tell the menus don't close because the `aria-expanded` attribute on the button element isn't being set to `false` (the CSS is attached to that attribute). I can't make out why this is happening though. The same attribute on the button-only Search block is working as expected. Cc @SantosGuillamot and @luisherranz as they are more familiar with this code.

**Comment by luisherranz** [comment]
We'll take a look. Thanks, @tellthemachines.

**Comment by luisherranz** [comment]
We've identified the problem, and @SantosGuillamot will open a PR with a possible fix.

**Comment by SantosGuillamot** [comment]
I just created the pull request that aims to fix it: https://github.com/WordPress/gutenberg/pull/55198
