### ISSUE TITLE
The block toolbar More options button shows a black icon on black background

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#55002]
### Description

In current Gutenberg trunk, the More options button icon is black over a black background when an option is enabled.
This makes the icon impossible to see.

### Step-by-step reproduction instructions

Activate Gutenberg trunk.
Open the block editor.
Add a paragraph block. Add some text and select the text.
Open the More options menu and enable an option, for example, strike through.
Confirm the button colors.

### Screenshots, screen recording, code snippet

With trunk:
<img width="341" alt="The More option button has black icon on a black background" src="https://github.com/WordPress/gutenberg/assets/7422055/7a56b797-b6ef-4c5d-a630-63a18039e2f1">

Expected:
<img width="341" alt="The More option button has a white icon color on a black background." src="https://github.com/WordPress/gutenberg/assets/7422055/e4b7f5e5-8998-49e0-8ccb-cfffbb86115a">

### Environment info

WordPress 6.4 Beta 1 current nightly though the beta tester plugin.
With Gutenberg trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
This issue was resolved in #55065, so I would like to close it.
