### ISSUE TITLE
Font Library: Uploaded fonts do not always display correctly until after page refresh

### ISSUE THREAD

**Issue by ironprogrammer** [WordPress/gutenberg#55018]
### Description

After uploading some custom fonts, the font management UI displays the new font name with a fallback font face (e.g. system serif font). Refreshing or navigating out and back to the editor resolves this, but I expect the newly uploaded font to be accurately represented in the UI without needing to refresh.

This behavior is intermittent, and can vary depending on the font. Here are some examples I tested (all fonts downloaded from Google Fonts for manual upload, except where noted):
- ❌ DM Sans
- ❌ Inclusive Sans
- ✅ Lemonada
- ❌ Press Start 2P
- ✅ Guillon (via zip from https://github.com/WordPress/gutenberg/issues/49021)
- ❌ Cooper Black (local TTF converted to WOFF2)

### Step-by-step reproduction instructions

1. Navigate to _Styles > Typography_ and open the font management UI.
2. Upload a font file. (Fonts that have an obvious stylistic difference are easier to demonstrate.)
3. On the Library tab, observe that the new font's name is not styled with the new font.
4. Observe the same in the font's variant details and active font list on the _Typography_ panel.
5. Refresh the editor and navigate back to _Styles > Typography_.
6. Observe the display of the new font in the active fonts list and within the font management modal.

### Screenshots, screen recording, code snippet

_Figure 1: Demonstration of font display after upload, then before and after refreshing the editor screen._

![demo of needing to refresh the editor for the font to display properly](https://github.com/WordPress/gutenberg/assets/824344/d8d8e48c-248e-41e5-99c3-3a2ddb795b03)

### Environment info

- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 13.6
- Browser: Safari 16.6, Google Chrome 117.0.5938.132
- Server: nginx/1.25.2
- PHP: 7.4.33
- WordPress: 6.4-beta2
- Theme: twentytwentyfour v1.0
- Active Plugins:
  - gutenberg v16.7.0 `trunk`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by franzaurus** [comment]
I experience this too. In my case, it seems the intermittent behavior primarily happens to display fonts type (Google font classification: display). 

The fonts are properly display if I choose: technology (variable), decorative style (sans serif), classification (any) e.g. Montserrat, Open Sans and Space Grotesk. But the problem appears if I select technology (variable), decorative style (sans serif), classification (display) e.g. Tilt Neon, Big Shoulders Stencil Display and Pixelify Sans.

### Environment info:
Windows 11 ver. 22H2
Chrome browser 117.0.5938.134
Local WP Version 7.2.1+6433
Gutenberg 16.7.1
WordPress 6.3.1

**Comment by t-hamano** [comment]
One reason for this problem may be that the added font's `@font-face` definition is not loaded until the browser is reloaded. I think we probably need some logic to dynamically add `@font-face`.

Figure 1: Immediately after uploading the `PressStart2P-Regular.ttf` font. There is no `@font-face` definition for this font:

![before](https://github.com/WordPress/gutenberg/assets/54422211/83aa6764-e321-46f3-a1c3-36564c6f1740)

Figure 2: After reloading the browser, you will see that `@font-face` has been added for this font:

![after](https://github.com/WordPress/gutenberg/assets/54422211/ec83424c-8496-4da6-afa8-0981f1ca7345)

**Comment by matiasbenedetto** [comment]
I added a commit ( https://github.com/WordPress/gutenberg/pull/55393/commits/0d8330cd61ea159b9c78427599a2b8f1482a5261 ) in this PR https://github.com/WordPress/gutenberg/pull/55393 that seems to be solving this problem.

**Comment by jffng** [comment]
> Refreshing or navigating out and back to the editor resolves this, but I expect the newly uploaded font to be accurately represented in the UI without needing to refresh.

I gave this a test just now, and it's fixed with #55393. Thanks everyone.
