### ISSUE TITLE
Fonts: theme font family missing when editing individual blocks

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#55011]
Using WP 6.4-beta1-56757 and GB 16.7, the theme provided fonts disappear post uploading a custom font. Here are steps to replicate:

1. Select a block to edit
2. Add the “Font Family”
3. Open the dropdown, and verify all the theme fonts are there
4. Open the Font Library modal
5. Upload and install the new font
6. Go back to edit a block
7. Open the dropdown again, and verify the theme fonts disappear

Video displaying this:

https://github.com/WordPress/gutenberg/assets/26996883/826d4bbb-792c-4be9-9055-d57bb18a932c

**Comment by arthur791004** [comment]
The block settings only [pick font families from one of the below in order from the global styles settings](https://github.com/WordPress/gutenberg/blob/f36f4cd74ac4f6722daf4a9dab819e6700b2ce67/packages/block-editor/src/components/use-setting/index.js#L192)
- custom
- theme
- default

But I cannot figure out why as I assume we can simply merge them 🤔

**Comment by matiasbenedetto** [comment]
This was caused by a problem not specific to the font library but the global styles/settings. This PR should solve it: https://github.com/WordPress/gutenberg/pull/55219
