### ISSUE TITLE
Move gallery link controls to the block toolbar

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#55022]
Related to https://github.com/WordPress/gutenberg/issues/55020, I propose moving the gallery block's "Link to" control from the inspector to a more familiar, and consistent, link control in the block toolbar. This would consolidate the varying linking controls found in image and galleries today, while also making way for applying "Expand on click" to all images within a gallery block. 

A follow-up to this would be to include "Expand on click" at the gallery parent level here, just like single image blocks will have in https://github.com/WordPress/gutenberg/issues/55020. 

### Before
![CleanShot 2023-10-03 at 16 25 30](https://github.com/WordPress/gutenberg/assets/1813435/c4b24878-5e9a-4cec-8f95-17135a18f300)

### Proposed
<img width="2720" alt="Lightbox for galleries, i4" src="https://github.com/WordPress/gutenberg/assets/1813435/3bf40735-7d7d-4343-986e-b745bcb89877">

**Comment by kinskiandbourke** [comment]
These are great ideas, and I cannot understand why lightbox control at the Gallery level wasnt introduced already.
I have a gallery with 30 images, do I then need to select every individual one to allow for the lightbox?

**Comment by richtabor** [comment]
> These are great ideas, and I cannot understand why lightbox control at the Gallery level wasnt introduced already.

Thanks! It's just a matter of refining it first in time for the 6.4 release. Now that it's in a decent place, we can level-up and bring it to the gallery block.

**Comment by RCNeil** [comment]
I offer no value other than to second this notion.  It also seems that the `theme.json` settings to modify the `core/image` `lightbox` settings to enabled automatically no longer work since the "Expand On Click" setting was moved to the block toolbar under Link Settings for each individual Image block.
