### ISSUE TITLE
IE11: gallery images stretched vertically

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#5504]
This is how the gallery images appear on Internet Explorer 11 and Gutenberg current master:

![screenshot 48](https://user-images.githubusercontent.com/1682452/37158098-d11caa52-22ea-11e8-8e08-3d575eae2f90.jpg)

**Comment by khleomix** [comment]
@afercia I can duplicate this issue and would love to work on this.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1520530384000449)._

**Comment by jorgefilipecosta** [comment]
It seems beside flex problems IE11 also does not support object-fit CSS property used in the gallery. There are some polyfills available but I'm not certain if adding a polyfill in the front end is something we should do.

**Comment by opicron** [comment]
I had the same issue, an temporary fix is rather simple:

.blocks-gallery-item img {
    max-width: 100%;
    flex-shrink: 0;
}

Source:
https://msdn.microsoft.com/en-us/library/jj127297%28v=vs.85%29.aspx
https://msdn.microsoft.com/en-us//library/hh772069%28v=vs.85%29.aspx

Stackoverflow (accepted answer):
https://stackoverflow.com/questions/36822370/flexbox-on-ie11-image-stretched-for-no-reason

**Comment by mtias** [comment]
This should be addressed with https://github.com/WordPress/gutenberg/pull/7465
