### ISSUE TITLE
Inserter: Going to second page in patterns category closes entire sidebar

### ISSUE THREAD

**Issue by luminuu** [WordPress/gutenberg#55043]
### Description

When there are more patterns in a category than it can be displayed in one go, there's a pagination at the bottom to go to the next page. However when you click on either of these navigation buttons, instead of loading the next page on patterns, the entire sidebar closes. See video below for this behaviour. This happens in both in the block editor and the site editor. It does not happen if you select "All patterns".

### Step-by-step reproduction instructions

1. Open/create a post or page.
2. Open the inserter.
3. Click on patterns.
4. Select a pattern category with lot of patterns like Text, not All patterns (it works there)
5. Scroll down to the navigation
6. Click on one of the arrow buttons to go to the next page.
7. The sidebar should close instead of loading the next set of patterns.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/7585600/27e235f0-3bcd-4f9d-aeeb-f3ac2c5bbc1c

### Environment info

- WordPress 6.4 Beta 2
- Gutenberg 16.7
- Twenty Twenty-Four theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I wasn't able to replicate this. When the tab closes are there any javascript error messages in the browser developer console? If so, are you able to provide a screenshot of the message please?

**Comment by talldan** [comment]
I also couldn't replicate it, though it could be related to the particular patterns that are on the second page. Some of the blocks in those patterns may be stealing or transferring focus. I recall similar issues in the past like that.

**Comment by luminuu** [comment]
There is no error happening in the console on clicking the pagination link, but there is one at the beginning of loading the first patterns, but I don't think it's related:

<img width="2542" alt="CleanShot 2023-10-05 at 12 19 16@2x" src="https://github.com/WordPress/gutenberg/assets/7585600/1b625652-1788-4c13-91ec-1ad62236ec92">

I have 6.4 Beta 2 via the Beta Tester plugin installed, Gutenberg 16.7.0 from the plugin repository (not from Github), and Twenty Twenty-Four from the Github repository. Not sure if this setup may make a difference.

**Comment by talldan** [comment]
@luminuu Which browser/OS are you using? There's a similar report in https://github.com/WordPress/gutenberg/issues/55110 for Safari.

Are there patterns that you've created that would be on that second page? Just wondering if there might be a specific block that causes it.

**Comment by luminuu** [comment]
I'm using Firefox and I have created no additional patterns in my environment. This is what TT4 and WP provide as patterns.

**Comment by talldan** [comment]
When I tested I only see 20 text patterns by default, and I had to create some to get a second page.

I'll try testing specifically with the beta tester plugin. Thanks for providing all the additional info.

**Comment by talldan** [comment]
I still only get 20 text patterns by default when using the beta tester plugin for 6.4 beta 2 (after spinning up a completely new site.)

There was one from the video above that I don't have, it has three columns of text with headings 'Virtual Tour', 'Current Shows', 'Useful Info'.

**Comment by t-hamano** [comment]
~~I also couldn't replicate it.~~ **Update**: I tested this issue again and was able to reproduce it on Firefox 124.0.2.

### Testing Report

- Launch a fresh website with InstaWP
- Update to WordPress6.4 beta2 via Beta Tester Plugin
- Activate Twenty Twenty-Four theme
- From the main inserter, select the Patterns tab
  - In the Post Editor, there are 19 patterns in the text category.
  - In the template editor of the site editor, there are 20 patterns in the text category.
- Duplicate the pattern belonging to the text category twice on the Site Editor's Patterns page so that you can go to the second page.
- From the main inserter, select the Patterns tab
  - In the Post Editor, there are 21 patterns in the text category, which can be moved to the second page.
  - In the template editor of the Site Editor, there are 22 patterns in the text category, which can be moved to the second page.

### Browsers

- Chrome: 117.0.5938.150 (64bit)
- Firefox: 118.0.1 (64-bit)

**Comment by annezazu** [comment]
To be safe, adding this to the 6.4 board but we can remove if it can't ultimately be replicated.

**Comment by luminuu** [comment]
I have been testing patterns for something else in TT4 and could no longer replicate this issue with latest 6.4 Beta 3, Gutenberg 16.8.0 and TT4 trunk.

**Comment by carolinan** [comment]
This problem has resurfaced and is reported here: https://core.trac.wordpress.org/ticket/60951

I am able to reproduce it using Firefox version 124.0.2. WP 6.5, Twenty Twenty-Four.

**Comment by annezazu** [comment]
Adding to 6.5.x for visibility.

**Comment by macmanx2** [comment]
Adding from the Core ticket mentioned above, I can also reproduce the problem in Safari 17.4.1.

It seems like Chromium browsers are the only unaffected browsers.

**Comment by t-hamano** [comment]
For those working on this issue, I'll comment what I've found so far. If the browser is Firefox and the pattern category is selected, clicking the pagination button fires the `onClose()` below and hides the inserter.

https://github.com/WordPress/gutenberg/blob/5e994543c63052cbe8d97e975dfb82d46554e82e/packages/editor/src/components/inserter-sidebar/index.js#L39

**Comment by talldan** [comment]
I can repro in Safari now, but not Firefox. Very strange 🤷‍♂️ 

At least it's possible to reproduce and so I'll start investigating. I expect it's a focus loss problem, two things stand out to me:
- It's noticeable that the pagination buttons become `disabled` so will lose focus, which is an anti-pattern that keeps happening in this codebase. They should only be `aria-disabled` as they can become `disabled` while focused.
- There's also the possibility that the pagination buttons are being completely unmounted/remounted in the DOM, the sidebar contents look quite empty when paginating. Ideally the buttons would remain present in the DOM with only the content changing.

**Comment by talldan** [comment]
Fix in #60620. Seems like it was the `disabled` vs `aria-disabled` thing I mentioned.

It'd be great if someone that experiences the issue in Firefox could test, as I wasn't able to replicate that (it might be a mac vs windows thing).

**Comment by creative-reinilda** [comment]
@talldan Thanks for looking into this. Unfortunately I can't test this but I experienced this problem only on Linux, so it really might not occur on Windows (can't check this).

**Comment by talldan** [comment]
@creative-reinilda [Here's a playground link you can use to test the change on linux](https://playground.wordpress.net/#%7B%22landingPage%22:%22/wp-admin/%22,%22steps%22:%5B%7B%22step%22:%22login%22,%22username%22:%22admin%22,%22password%22:%22password%22%7D,%7B%22step%22:%22mkdir%22,%22path%22:%22/wordpress/pr%22%7D,%7B%22step%22:%22writeFile%22,%22path%22:%22/wordpress/pr/pr.zip%22,%22data%22:%7B%22resource%22:%22url%22,%22url%22:%22/plugin-proxy.php?org=WordPress&repo=gutenberg&workflow=Build%2520Gutenberg%2520Plugin%2520Zip&artifact=gutenberg-plugin&pr=60620%22,%22caption%22:%22Downloading%20Gutenberg%20PR%2060620%22%7D,%22progress%22:%7B%22weight%22:2,%22caption%22:%22Applying%20Gutenberg%20PR%2060620%22%7D%7D,%7B%22step%22:%22unzip%22,%22zipPath%22:%22/wordpress/pr/pr.zip%22,%22extractToPath%22:%22/wordpress/pr%22%7D,%7B%22step%22:%22installPlugin%22,%22pluginZipFile%22:%7B%22resource%22:%22vfs%22,%22path%22:%22/wordpress/pr/gutenberg.zip%22%7D%7D%5D%7D).

I think the easiest way is to create a new post, try inserting a pattern, and use the 'All' category.

**Comment by creative-reinilda** [comment]
Hej,
thank you very much for the quick response.
I can test it for "All" patterns and it works. I can't use all the other patterns because there are too few templates displayed for me to be able to switch to a second site with the arrow on the bottom.
But now the „All“ category works fine.
