### ISSUE TITLE
Font Library: Use WOFF2 files for Google Fonts instead of TTF files

### ISSUE THREAD

**Issue by YanCol** [WordPress/gutenberg#55049]
Currently, when a user installs a Google Font, the file that's downloaded from Google and subsequently self-hosted on the server is in TTF format. For performance reasons, it would be more optimal to use the WOFF2 format.

As mentioned in the Google Fonts Glossary: [https://fonts.google.com/knowledge/glossary/web_font](https://fonts.google.com/knowledge/glossary/web_font)
"WOFF (and its successor WOFF2) are compressed file formats created specifically for web fonts. Although regular OpenType fonts (TTF and OTF files) can be used as web fonts, such usage is not recommended as [...] the files are significantly larger."

**Comment by Ren2049** [comment]
[@majodev](https://github.com/majodev/google-webfonts-helper) created a service for WOFF2 Google fonts and font subsetting (to strip WOFF2 font files from unused language characters reducing the file size even further).

Could his API be used and integrated into WordPress?

**Comment by fnpen** [comment]
Is it planned to add woff2 support in the future? As I see WordPress uses wp.org to get JSON files with fonts and it does not include information about woff.

**Comment by kyle-charlton** [comment]
I would love to see this option implemented as part of the Font Library since it would remove the extra steps of converting the fonts to woff2 before uploading them.
Could this be part of the 6.5 release since the Font Library feature has now been punted to 6.5?

**Comment by mikachan** [comment]
I believe this can now be closed as this functionality has been included in https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/3.

> Could this be part of the 6.5 release since the Font Library feature has now been punted to 6.5?

This is planned to be part of 6.5. 👍
