### ISSUE TITLE
CODE tag inside PRE tag in code block is visible in iOS 17

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#55064]
### Description

The code block contains a `code` tag within a `pre` tag. iOS 17 renders the `code` tag visibly in the browser. (IMO this is correct, but not desired.)

### Step-by-step reproduction instructions

e.g. https://permanenttourist.ch/2021/02/how-to-clone-a-wordpress-website-with-wp-cli-and-rsync/

### Environment info

- Latest WordPress
- Tested with and without plugins (except Gutenberg, which is not installed).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Maybe I'm misunderstanding, but I think that seems like a bug in iOS - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre

> If you have to display reserved characters such as <, >, &, and " within the `<pre>` tag, the characters must be escaped using their respective [HTML entity](https://developer.mozilla.org/en-US/docs/Glossary/Entity).

Also - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code

> To represent multiple lines of code, wrap the `<code>` element within a [`<pre>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) element. The `<code>` element by itself only represents a single phrase of code or line of code.

Let me know if I have this wrong.
