### ISSUE TITLE
Site Editor Template Details: Areas not available after saving  

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#55061]
Areas are no longer captured in the template if the template has been edited. To replicate, install a block theme like TT3 or TT4, then view the Blog Home template, make a change to it, save and refresh. 

May be related to https://github.com/WordPress/gutenberg/pull/54861 (or the alternative https://github.com/WordPress/gutenberg/pull/54942). 

https://github.com/WordPress/gutenberg/assets/1813435/c809ea0d-afb9-46f5-89a9-7aee08ee4bd4

**Comment by richtabor** [comment]
cc @Mamaduka @MaggieCabrera — mind looking into this?

**Comment by Mamaduka** [comment]
I can't reproduce this on TT3; it could be a theme markup issue.

**Comment by richtabor** [comment]
> I can't reproduce this on TT3; it could be a theme markup issue.

Interesting. Can you on TT4?

**Comment by richtabor** [comment]
> I can't reproduce this on TT3; it could be a theme markup issue.

Interesting. Can you on TT4?

**Comment by Mamaduka** [comment]
I was able to reproduce on TT3 as well. I'll try to look into it tomorrow morning.

Update: I can also reproduce the issue with the old Gutenberg version (16.4), so it's not related to the recent changes.

**Comment by Mamaduka** [comment]
@richtabor, create fix here - #55085. Should we label it for 6.4 beta backport?
