### ISSUE TITLE
Post Listing Navigation "trash" and "delete" actions unexpectedly lead to Site Editor

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#55082]
The "trash" and "delete permanently" links in the `wp-admin/edit.php?post_type=wp_navigation" screen take you to the site editor. The only way I could delete the different navigation was to use the bulk actions.

These actions should not go to the Site Editor

https://github.com/WordPress/gutenberg/assets/60436221/633180e9-aeb5-48e8-9e0d-47d487adeeb8

------

I've also noticed that. I think those actions shouldn't open the Site Editor. But I'm guessing they're both using `_edit_link` as a path, so we get this behavior.

Here's the core sync PR for that change - https://github.com/WordPress/wordpress-develop/pull/4710. Maybe @ramonjd or @getdave have ideas on how to fix it.

_Originally posted by @Mamaduka in https://github.com/WordPress/gutenberg/issues/55072#issuecomment-1748137572_

**Comment by ramonjd** [comment]
Hi folks! Thanks for creating this issue. 

This is something I suspect we'd need to resolve in Core. Namely, how to return different edit links based on context, or the referring URL params or 🤷🏻 

I've had a Core Tract ticket up for while  to get discussion going around this issue: 

- [Revisions page: how to support varying "Go to editor" link templates #59419](https://core.trac.wordpress.org/ticket/59419)

It's growing cobwebs.

**Comment by noisysocks** [comment]
Ran into this as well while testing.

https://github.com/WordPress/gutenberg/assets/612155/945f93d4-7596-4cf9-ac22-e9b518d09cb8

**Comment by getdave** [comment]
No longer required as we have the `Navigation` section in the Site View sidebar
