### ISSUE TITLE
Link block doesn't offer the options to change text or open in new tab

### ISSUE THREAD

**Issue by olivierborgognon** [WordPress/gutenberg#5508]
## Issue Overview

The link block doesn't allow for "open in new tab" or have the wheel to access that panel like in the classic editor, could be really useful. I have loads of links which I must open in new tabs. 

Sometimes when typing the link and hitting the return button or key, the link disappears from the box, and text stays as text. 
## Steps to Reproduce (for bugs)

1. New post
2.Paragraph block
3.Select text and press on Link button
4.write URL
5. Hit Enter... either works, or doesnt
6. No option when on the link filling popup to go "open in new tab"

Safari 11.0.3 / WP 4.9.4 / theme Mango from NeuronThemes / Host : hostpoint.ch / OS : OSX sierra

## Todos
- [ x] Tests
- [x ] Documentation

**Comment by burnuser** [comment]
Have the same issue - and need "open in new tab" for all links too: text + images !

**Comment by karmatosed** [comment]
Closing this as happening as part of: https://github.com/WordPress/gutenberg/issues/4572
