### ISSUE TITLE
Data views: Pagination

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#55095]
This ticket is a stub to include designs for navigating through multiple pages within data views. Considerations include:

* Positioning (above/below table, pinned/sticky, etc)
* Optimising the overall footprint accounting for tables with many pages
* Quick-navigation to specific page numbers
* Quick-navigation to first/last pages
* Total number of records in current page, and total number of overall records, total number of pages
* Potential inclusion of records-per-page option (overlaps with https://github.com/WordPress/gutenberg/issues/55094)

**Comment by ntsekouras** [comment]
What is needed to change based on the current status of the pagination? As some tasks like `quick navigation` are already in, do we need to update the design? Do we have a mockup?

**Comment by jameskoster** [comment]
Quick jumping to specific pages isn't working for me currently 🤔

Some changes we can try:

* Make the pagination row sticky at the bottom of the view
* Use icons instead of plain text for buttons
  * Next: `chevronRight`
  * Previous: `chevronLeft`
  * First: `previous`
  * Last: `next`

Then there are some cosmetic adjustments; typography, colors, spacing, etc. I'll work on a PR for that as time allows.

**Comment by ntsekouras** [comment]
I think the only remaining thing for now is:
>Positioning (above/below table, pinned/sticky, etc)

Pagination is now at the bottom of the frame at all times. We could add the option to place it above, but since there are no current use cases/designs for that, should we close this? We can always add it when we need to.

**Comment by jameskoster** [comment]
Yes, let's close this 🎉
