### ISSUE TITLE
Make `useBlockLock()` public

### ISSUE THREAD

**Issue by jdamner** [WordPress/gutenberg#55092]
## What problem does this address?
Using `blockEditor.useSetting.before` filter to apply customisation to block settings and I was trying to restrict certain block properties depending on if the block was locked or not. 

If `useBlockLock()` was public, I could use that instead I've had to replicate the method in my own codebase which also means I'll need to watch for any changes/maintenance.

## What is your proposed solution?

Export `useBlockLock()` for use by plugin developers - simple

**Comment by youknowriad** [comment]
Hi there! thanks for the suggestion. What exactly do you need from useBlockLock. Looking at its code, it's just a collection of selector calls and all of these are public already.

**Comment by jdamner** [comment]
Yeah, I used the selectors so it's not a big issue but now if the locked block selectors change I need to maintain my version and I fail to benefit from any upstream changes. 

I was trying to disable some block settings depending if the block was locked or not. For example, disabling background colour on locked blocks, since at the moment locking only prevents moving or removing.

**Comment by Mamaduka** [comment]
I'm going to close the issue. The `useBlockLock` is easily copy-pastable in projects.
