### ISSUE TITLE
Table: Quick-actions

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#55096]
This ticket is a stub to include designs for quick-actions in table views. 

"Quick-actions" include things like moving pages to the trash, or reseting a template. Additionally, they can potentially encapsulate much of the "quick edit" affordance on wp-admin tables, IE enabling users to edit post meta without engaging the full-screen editor.

**Comment by youknowriad** [comment]
Where are we on the design aspect here? I wanted to start looking at this soon.

**Comment by jameskoster** [comment]
@youknowriad the latest work includes quick-actions at the end of each row. They are split into two categories; Primary and Secondary. Primary actions are displayed permanently, and secondary actions are grouped in an overflow menu. 

https://github.com/WordPress/gutenberg/assets/846565/b5e35f0d-c6f7-498f-88b5-3bcecee89091

For Pages the primary actions would be 'View' and 'Trash'. The full list of secondary actions (and their associated UIs) needs to be decided upon, but potentially we can include 'Edit' and 'View revisions' straight away as there are clear destinations for each.

<img width="514" alt="Screenshot 2023-10-16 at 10 31 23" src="https://github.com/WordPress/gutenberg/assets/846565/f17f1952-39d8-49c0-b611-344c9eeb9796">

For templates, the primary action(s) would be 'Trash/Reset' where applicable. Secondary actions would be 'Edit', 'View revisions', and 'Rename' for custom templates.

<img width="477" alt="Screenshot 2023-10-16 at 10 36 48" src="https://github.com/WordPress/gutenberg/assets/846565/bc325d8c-9d0e-4bd1-8d3b-17466c19ed2e">

In both cases there might be an argument to make 'Edit' a primary action, depending on the behavior we settle on for clicking the document title (edit vs. view details).

**Comment by youknowriad** [comment]
@jameskoster Makes sense, how do these actions translate/render in the "grid view"?

**Comment by jameskoster** [comment]
It would be nice to include actions in the same format if possible. Whether they appear adjacent to / beneath the title, overlayed on the thumbnail, or something else will likely depend on how other fields are handled in that view mode. I suspect this will require a dedicated exploration to get right.

**Comment by ntsekouras** [comment]
@jameskoster the `view` quick action will point to the front end or the site editor in 'view' mode?

**Comment by jameskoster** [comment]
The frontend. It's the same functionality as the "View" link in the current pages list in wp-admin.

**Comment by ntsekouras** [comment]
First iteration landed, so it would be good to update this issue with more specific action items, or create a new one.

**Comment by jameskoster** [comment]
@ntsekouras with the foundations in place I reckon we can close this and open issues for different contexts (pages, templates). I'll open those asap. 

One small detail you may want to address until then: The 'Edit' action should go directly into the editor rather than the details view.

**Comment by ntsekouras** [comment]
>One small detail you may want to address until then: The 'Edit' action should go directly into the editor rather than the details view.

@jameskoster what do you mean by that? 

--edit

Actually I probably get what you mean. There could be a race condition there and sometimes redirects you to the details view. I'll take a look at it.

**Comment by jameskoster** [comment]
Just to clarify, the behavior should essentially match the wp-admin 'Edit' link, which takes you directly to the editor (no details view interstitial).
