### ISSUE TITLE
Image block with toolbar alignment setting not working proper. 

### ISSUE THREAD

**Issue by VipulUpadala** [WordPress/gutenberg#55090]
### Description

I have tested the Image block with the toolbar alignment setting and found the alignment setting not working properly. if I select the left alignment or right alignment setting then the frontend side image alignment with the footer position is changing.

### Step-by-step reproduction instructions

1. Create a new page and take the image block.
2. And set the  toolbar alignment setting right or left.
3. check it frontend side footer position also change.

### Screenshots, screen recording, code snippet

Please check the provided screen recording video below for a better understanding of the issue.

Video Recording: https://share.cleanshot.com/whlqG1MYprpR8jjd13N1

### Environment info

- WordPress 6.3.1 running
- Chrome
- macOS 13.2

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hey @VipulUpadala  - thanks for reporting this. The front-end alignment of the block is something the theme you're using could effect. Can I please ask you to try this with the TwentyTwentyTwo or TwentyTwentyThree theme active and see if it still happens?

**Comment by vipulupadala-multidots** [comment]
Hello @jordesign,

Yes, I have tried with all three WordPress themes and TwentyTwentyTwo and TwentyTwentyThree reproduce the above issue.   but TwentyTwentyOne does not appear to issue.

**Comment by carolinan** [comment]
Hi @VipulUpadala The video is not available anymore. It is not clear which theme that was used for testing, do you know if this is a duplicate of https://core.trac.wordpress.org/ticket/61438

**Comment by Mamaduka** [comment]
I'm going to close the issue. No additional info has been provided since 2023.
