### ISSUE TITLE
Featured image isn't saved on publish

### ISSUE THREAD

**Issue by olivierborgognon** [WordPress/gutenberg#5509]
## Issue Overview

In posts, featured image is selected from media library or upload, appears on the right pane. When publishing, going back to any other menu, and coming back to the post or page... featured image has disappeared. 
## Steps to Reproduce (for bugs)

1.open post
2.add featured image & publish
3.quit post, come back to the same post through post list
4.Featured image has gone...

## Expected Behavior

Featured Image should not disappear as it does
## Current Behavior

Featured image doesn't appear, it gets lost, not saved or not pulled back out from Database
## Todos
- [ x] Tests
- [ ] Documentation

**Comment by markjaquith** [comment]
I cannot reproduce this. Featured images are saving properly when I publish a post.

Steps:

1. Clicked New Post
2. Added a title
3. Added a featured image
4. Clicked Publish / Publish
5. Clicked to All Posts screen
6. Clicked title of just-published post
7. Verified that featured image shows in the sidebar
8. Viewed the post and verified that featured image shows in the theme

**Comment by karmatosed** [comment]
I am also unable to reproduce this, so lets close for now. If you still reproduce @olivierborgognon please add a comment and we can reopen.
