### ISSUE TITLE
Data view: Bulk actions

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#55098]
Here are some refinements we can make to the current bulk edit experience in data views:

### Add floating bulk actions toolbar

<img width="787" alt="Screenshot 2024-01-23 at 15 41 57" src="https://github.com/WordPress/gutenberg/assets/846565/fccfc2e5-d775-4e1e-9bfb-b25d89b63660">

Another mouse-user power tool to try is the floating bulk-action toolbar. This enables primary actions to be applied across the selection in a single click.

### Click-to-select

![click](https://github.com/WordPress/gutenberg/assets/846565/05fd1925-8334-4cef-92e0-593f8a6b9e8a)

As a power tool for mouse users it would be nice if clicks registered inside a table row/grid card would trigger selection. This eliminates the need to hit the checkbox directly which is a useful affordance for those with reduced motor skills. Interactive elements should still take priority. IE clicking an action button would perform the action and not select the item.

- [ ] Grid layout: #58802
- [x] Table layout

**Comment by ntsekouras** [comment]
👋 Any current designs for this? Additionally, we'll need some thinking about how multi selection will look like in other views, like `grid`.

**Comment by jameskoster** [comment]
There have been several explorations but the floating toolbar still feels like the best approach, primarily because:

* It is always visible regardless of scroll position.
* It doesn't shift the layout at all when it appears / disappears.
* All additional table functionality remains accessible (filtering etc)

Initially it might appear in the following format:

![bulk](https://github.com/WordPress/gutenberg/assets/846565/eada3413-48c5-4d79-ac22-bf740308ff8d)

Notation about how many items are selected is included, plus a shortcut to deselect. Any relevant primary quick actions associated with each row (as described in https://github.com/WordPress/gutenberg/issues/55096#issuecomment-1764100876) are also displayed. In the case of Pages that just means the ability to Trash.

It would also be nice to include:

* More selection options (select current page, select _all_), but that likely requires some technical exploration since applying bulk actions to 000's of records raises questions about performance. 
* Quick edits, e.g. update the author assigned to multiple pages at once. This needs further design exploration since there are so many different quick-edit options, and the toolbar will need a way to accommodate them all.

<img width="825" alt="Screenshot 2023-10-18 at 13 23 04" src="https://github.com/WordPress/gutenberg/assets/846565/dc163d6a-17f1-40ab-a1db-6fdd4de265e9">


> Additionally, we'll need some thinking about how multi selection will look like in other views, like grid.

It might be simplest to include the checkbox to the left of the title and iterate from there. Some kind of shift-click affordance could be nice to add, but we'll need to work out all the interactions plus any a11y considerations.

**Comment by jameskoster** [comment]
For reference this is the design we're working towards in  https://github.com/WordPress/gutenberg/pull/56476:

<img width="3346" alt="Bulk edit" src="https://github.com/WordPress/gutenberg/assets/846565/6032f7a0-5575-4ddb-b136-62c5fb403171">

 * Bulk actions live in a dedicated "Bulk edit" [DropdownMenu](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-dropdownmenu-v2-ariakit--docs) positioned at the top of the table, possibly before filters, or before the view options button.
 * All actions (e.g. "Delete", "Change status", "Change author") are presented in a group in the menu, disabled until a selection has been made.
 * A second group in the menu includes selection options e.g. "Select current page", "Select all", "Select none".

**Comment by youknowriad** [comment]
@jorgefilipecosta what's remaining here, can we close this one?

**Comment by jameskoster** [comment]
@youknowriad @jorgefilipecosta I think we have some outstanding items:

1. In the templates table, we need to explain why some bulk actions cannot be applied to all records. This needs some design.
2. Bulk actions in Grid layout – where does the checkbox live, etc. This also needs a little design.
3. Try adding the floating bulk actions toolbar as a secondary affordance optimised for mouse users, this one:

<img src="https://private-user-images.githubusercontent.com/846565/276239721-eada3413-48c5-4d79-ac22-bf740308ff8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDY0OTcsIm5iZiI6MTcwNTk0NjE5NywicGF0aCI6Ii84NDY1NjUvMjc2MjM5NzIxLWVhZGEzNDEzLTQ4YzUtNGQ3OS1hYzIyLWJmNzQwMzA4ZmY4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxNzU2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGRlYzUyNTlhZjZkNWFlNjNmOTNmYWM2YjM3YjI5YmEzMWU4ZjdkMWE1ZDg4YWQ1MzE5ZjM0M2NmYjFlMmY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kXFw7fWx4Za0qFAgn0kLT_uqFfQsG8S4pdgoJn2mnsE">

We can probably close this and create follow-up issues for those, if you prefer?

**Comment by youknowriad** [comment]
I don't mind the issue being open, I just wanted some clarity. So maybe add some tasks to the issue description.

**Comment by jameskoster** [comment]
@youknowriad @jorgefilipecosta I've updated the issue to include some general refinements we can make.

> In the templates table, we need to explain why some bulk actions cannot be applied to all records. This needs some design.

This one is a bit tricky and needs a dedicated exploration. I don't personally feel it's super high priority.

**Comment by jameskoster** [comment]
The floating bulk actions toolbar is under way in https://github.com/WordPress/gutenberg/pull/59714.

The work in https://github.com/WordPress/gutenberg/issues/59689 can theoretically unlock the ability to use the Inspector as a bulk edit interface too, e.g:

![Bulk edit](https://github.com/WordPress/gutenberg/assets/846565/f106c1cb-2d87-454c-a268-b7d079f10db8)

But it's worth noting that work might be better tackled separately.

**Comment by jorgefilipecosta** [comment]
I guess we can close this now, as the toolbar is available. We don't have bulk edit yet but that seems like a different task.
