### ISSUE TITLE
createBlock with core-embed/youtube

### ISSUE THREAD

**Issue by alvarotrigo** [WordPress/gutenberg#55104]
Right now this won't work:

```js
// Define the YouTube video URL (replace with your desired URL)
const youtubeVideoURL = 'https://youtu.be/NNrj0N-yTnM';

// Create a new YouTube video block
const youtubeVideoBlock = wp.blocks.createBlock('core-embed', {
  url: youtubeVideoURL,
});
``` 

We get a message:

```js
Uncaught Error: Block type 'core-embed' is not registered.
``` 

It'd be nice to be able to create these kinds of blocks in the same way we can create paragraphs, quotes, images and so on.

**Comment by torounit** [comment]
@alvarotrigo You might try "core/embed". It will probably work.

**Comment by alvarotrigo** [comment]
> @alvarotrigo You might try "core/embed". It will probably work.

Except that it won't be the same as a youtube embed.

<img width="413" alt="image" src="https://github.com/WordPress/gutenberg/assets/1706326/286bbe9a-86c6-446a-9d62-0005fa82ba18">

**Comment by alvarotrigo** [comment]
Yeap, that did the trick!
Thanks! 👍
