### ISSUE TITLE
Site Editor: creating a new page doesn't invoke pattern selection

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#55108]
When using Twenty Twenty-Four and adding a new page in the Site Editor, despite having patterns registered for page creation, the starter pattern modal never appears causing you to enter an empty page, despite there being patterns registered for this creation process. This stands in contrast to when you create a new page using Pages > Add New Page. 

cc @richtabor for flagging this and @aaronrobertshaw in case you can help :) 

### Visual

https://github.com/WordPress/gutenberg/assets/1813435/0c2738b5-db1b-4f78-92ec-d4d5a33f0144

**Comment by talldan** [comment]
I think the pattern selection modal was only ever implemented in the post/page editor. I'll have a look to see if I can port it to the site editor.

**Comment by talldan** [comment]
This is technically an enhancement btw, as it was a never implemented feature rather than a bug.

I'll look into what it takes to implement it, hopefully have a PR, and then we can decide what to do about it and 6.4.

**Comment by talldan** [comment]
#55117 is almost there. Just debugging an issue with there being no patterns in the block editor store when editing a new page via the site editor (`wp.data.select( 'core/block-editor' ).getPatternsByBlockTypes( 'core/post-content' );` returns an empty array).

At the end of my day now so will pick it up on Monday.

**Comment by richtabor** [comment]
Thanks @talldan!

**Comment by annezazu** [comment]
Great to know! Removing from 6.4 in that case. Thank you for diving in.

**Comment by talldan** [comment]
I think I've managed to get it working here - [Add starter patterns to site editor new page](https://github.com/WordPress/gutenberg/pull/55117#top)

However I haven't had time to update the PR description. That'll be a tomorrow task.
