### ISSUE TITLE
Can't add Tags or categories, sidebar option doesn't exist... Extended settings is empty

### ISSUE THREAD

**Issue by olivierborgognon** [WordPress/gutenberg#5510]
## Issue Overview

Can't add Tags or categories, sidebar option doesn't exist... Extended settings is empty

## Steps to Reproduce (for bugs)

1.Create new Post
2. Can't find categories, can't add categories, can't add tags
3.
4.

Safari 11.0.3 / osx Sierra / Hostpoint.ch hosting company / WP 4.9.4

## Expected Behavior

I should be able to add 1 or multiple categories to posts and same for tags

## Current Behavior

I can't add categories or tags to posts

## Todos
- [ x] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Hi @olivierborgognon,

Were you able to identify the source of this issue? If not, can you provide screenshots to what you're referring to, and information on any debugging you've done?

**Comment by vietlongn** [comment]
@danielbachhuber i have the same issue
There is an error while requesting /wp-json/wp/v2/taxonomies?context=edit
![image](https://user-images.githubusercontent.com/6986991/38976912-e0c762fe-43dc-11e8-9e10-2d5720fe9155.png)

The Curent User dont have **manage_categories** capability. For users who have this capability, it's work normally.
Please take a look at this.
Thank you.

**Comment by danielbachhuber** [comment]
@vietlongn Thanks, makes sense. This issue is being tracked in #5879
