### ISSUE TITLE
Image block lightbox: setting lightbox on an image makes all following images open in the lightbox

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#55119]
### Description

This can be reproduced also in WordPress core with Gutenberg disabled so is needs to be fixed before the 6.4 release.
Cc @annezazu @bph @mikachan @SiobhyB @karmatosed @hellofromtonya 

When a post has more than one Image block, setting one of the image to open in the lightbox makes all following imges open in the lightbox, even if their lightbox setting is disabled.

This is clearly not the expected beheavior.

This filter rund at priority 15:

https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/block-library/src/image/index.php#L72

The filter is never removed. That means the lightbox markup and view file are added to all the blocks after the first block that has the lightbox enabled.

That also highlights that the lighbox feature has never been tested with more than one image, which is  a little surprising.

### Step-by-step reproduction instructions

- Create a post.
- Add four image blocks.
- Set only the second image block to open the image in the lightbox.
- Publish annd view the front end.
- Obzerv the first image has no lightbox enabled.
- Observe the second image has the lightbox enabled, as expected.
- Observe the third image  has the lightbox enabled: wrong.
- Observe the fourth image  has the lightbox enabled: wrong.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Thank you for opening this. I can't replicate with 6.4-beta2 and with or without GB 16.7 with the gallery block:

https://github.com/WordPress/gutenberg/assets/26996883/ff4b4f2c-e199-4574-8d12-77654d67d592

I can't with four image blocks either:

https://github.com/WordPress/gutenberg/assets/26996883/66d1bc8a-7094-426c-9134-11374fd58ec0

Perhaps someone else can replicate cc @artemiomorales

**Comment by artemiomorales** [comment]
Thanks for catching this @afercia 🙏

@annezazu I was unable to reproduce this in GB 16.7 at first, but after restarting my dev environment and rebuilding Gutenberg, I was able to see the issue, which is probably a reason this was missed.

**Comment by annezazu** [comment]
Thanks for diving in 🙌🏼

**Comment by afercia** [comment]
> I can't replicate with 6.4-beta2 and with or without GB 16.7 with the gallery block ... I can't with four image blocks either:

> I was unable to reproduce this in GB 16.7 at first, but after restarting my dev environment and rebuilding Gutenberg, I was able to see the issue, which is probably a reason this was missed.

@artemiomorales @annezazu I see taht sometimes changes to the PHP files are not immediately applied and thus testing appears to be sometimes reliable. I have no idea why, but it seems we are at least in three who had some troubles properly testing. I wouldn't underestimate this, as a solid, reliable development environment is key for proper development and testing. Anyone know who maintaines the wp-env environment and the build process and can be pointed at this issue?
