### ISSUE TITLE
Varying publish fields in post and site editors

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#55111]
The "Publish" fields in the Site Editor and Post Editor are different; they should be more consistent. 

There are a few differences in scale/size, but also on how the date/time is communicated. Let's decide on what direction to lean towards and bring these two experiences closer together. 

| Site Editor  | Post Editor |
| ------------- | ------------- |
|![CleanShot 2023-10-05 at 17 41 52](https://github.com/WordPress/gutenberg/assets/1813435/83a49938-db53-4d7e-bb9e-59c9f8788902)|![CleanShot 2023-10-05 at 17 43 45](https://github.com/WordPress/gutenberg/assets/1813435/7e1a607f-bca3-4349-83de-9aa599f7a0b3)|

**Comment by apeatling** [comment]
The experience with more padding looks visually more appealing to me, and probably easier to navigate considering every number is clickable.

**Comment by richtabor** [comment]
Agreed. 

I also added a bit of clarification on which is which (site editor vs. post editor).

**Comment by t-hamano** [comment]
I would like to inform you that #56196, which unifies the PostSchedule component, has been submitted. For this PR, it was chosen to use a format similar to "X days ago".

Also, the issue of different component sizes would be resolved.
