### ISSUE TITLE
Image block: clean-up and improve usage of WP_HTML_Tag_Processor

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#55123]
### Description

Splitting this out from https://github.com/WordPress/gutenberg/pull/55010

See comment https://github.com/WordPress/gutenberg/pull/55010#discussion_r1348064458

Turns out there's room for improvements and clean-up the code of the Image block, specifically:
- reduce the amounc of WP_HTML_Tag_Processor being created 
- better variable names: avoid things like `$w`, `$p` and the iike
- consider using WP_HTML_Tag_Processor [bookmarks](https://github.com/WordPress/gutenberg/blob/0816b4cdf016f64f580853dbd39c9228eec5c5f4/lib/compat/wordpress-6.3/html-api/class-gutenberg-html-tag-processor-6-3.php#L171)

### Step-by-step reproduction instructions

This is a code quality / performance issue. No bugs to reproduce.
As aknowledged in https://github.com/WordPress/gutenberg/pull/55010#discussion_r1348064458 the Block image PHP part has room for improvements as some code is redundant / not necessary and duplicate unnecessary instances of WP_HTML_Tag_Processor are still in place from previous implementations.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by michalczaplinski** [comment]
Closing this now as the PHP side of the Image block went through some refactoring since. It uses bookmarks now when possible and avoids re-creating the Tag Processor instances.

Feel free to open new issues for additional improvements or send a PR directly!
