### ISSUE TITLE
Reordering meta boxes for Custom Post Types does not persist correctly

### ISSUE THREAD

**Issue by alexsanford** [WordPress/gutenberg#5512]
## Issue Overview

When reordering meta boxes (with drag and drop) on the edit page for a Custom Post Type, the new order of the meta boxes does not persist properly. In fact, they are persisted in the user meta `meta-box-order_post` instead of `meta-box-order_{post-type}`.

## Steps to Reproduce (for bugs)

1. Create or edit a post of a Custom Post Type with metaboxes using Gutenberg.
2. Reorder the metaboxes by dragging and dropping.
3. Check the `meta-box-order_{post-type}` user meta. The reordering information is not there.
4. Check the `meta-box-order_{post-type}` user meta. The reordering information is there.
5. Edit the post in the classic editor. The metaboxes will not be ordered as desired.

## Expected Behavior

I expect Gutenberg and the Classic editor to use the same user meta for storing the metabox ordering.

## Current Behavior

Although it appears to work when using only Gutenberg, the ordering is stored in the incorrect user meta, and thus it doesn't work when switching to the classic editor, and vice versa.

**Comment by jorgefilipecosta** [comment]
Thank you for your detailed issue @alexsanford 👍 . A PR that addressed was submitted: https://github.com/WordPress/gutenberg/pull/5594.
