### ISSUE TITLE
Display less numbers at pagination or choose how many to display (Query Block)

### ISSUE THREAD

**Issue by gfarma** [WordPress/gutenberg#55146]
## What problem does this address?
I think the current display of numbers at pagination is a bit confusing.
![image](https://github.com/WordPress/gutenberg/assets/112942896/c07a049c-0349-4661-9d88-30edbd5289c9)
5 numbers maybe are too many.
Btw with the current style at mobiles sometimes the pagination block needs 3 rows to diplay.
![image](https://github.com/WordPress/gutenberg/assets/112942896/6c142c1d-20b3-4492-9310-d799ecd5eba7)

## What is your proposed solution?
I think something like this is better
![image](https://github.com/WordPress/gutenberg/assets/112942896/15eb8a12-c2bf-4bc6-a904-a35f16edb2bf)
Or maybe to let the user choose what type to display front end (1..234..5 or 1..2345..6 etc)

**Comment by t-hamano** [comment]
Hi, @gfarma,

I think the feature you want was implemented in #51216. You can set how many page numbers can be set before and after the current page.

![number-of-links](https://github.com/WordPress/gutenberg/assets/54422211/6db6579b-ce6f-46e2-9fb9-a2d097b92f99)

**Number of Links = 2 (default)**

![number-of-links-2](https://github.com/WordPress/gutenberg/assets/54422211/d010c96c-cc85-4485-8d4e-6a4160fe1ce3)

**Number of Links = 1**

![number-of-links-1](https://github.com/WordPress/gutenberg/assets/54422211/73a07c02-7412-414e-9709-b0749e4964ef)

This feature is part of Gutenberg 16.6, so it's not yet available in WordPress 6.3. You can use it by activating the WordPress 6.4 Beta or the Gutenberg plugin version 16.6 or later.

Therefore, I would like to close this issue as resolved.
