### ISSUE TITLE
Experimental Page List: Ensure sorting by doesn't cover up other drop downs

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#55169]
Took https://github.com/WordPress/gutenberg/pull/54966 for a quick spin and I know it's a work in progress but wanted to note for @ntsekouras as follow up to ensure the sorting drop down doesn't cover up the other drop downs. Right now, it feels a bit cluttered to have the two overlap.

**A screenshot:**

<img width="497" alt="Screenshot 2023-10-09 at 11 44 32 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/f9d872a5-8255-4c4c-94f6-0edfa32156d7">

**Video for clarity:**

https://github.com/WordPress/gutenberg/assets/26996883/7adf1f21-7a0c-455a-a0ee-048665680cb2

**Comment by ntsekouras** [comment]
I had commented about that and pinged folks that work on components. This might be hard to change and we might need to consider some different design.  See @ciampo's [reply](https://github.com/WordPress/gutenberg/pull/54966#issuecomment-1744640721):

> > This works but I couldn't make it to match the design to open a third nested submenu on the left. I've checked radix docs about it a bit, but couldn't fix it. --cc @ciampo .

> I don't think that's really possible, because I believe that nested menu always open to the right (in LTR environments), and only open to the left when there isn't space available on the right. So in this case, the third nested submenu has the space to open to the right and it does so. My hunch is that this behaviour can't be changed

> Also, a heads-up that the experimental `DropdownMenuV2` likely won't stick around too much in its currently iterations (see https://github.com/WordPress/gutenberg/issues/50459)

**Comment by ciampo** [comment]
Let's put this on ice for the time being, until the new dropdownmenu component is ready to be used. I may be able to expose a way to change where the submenu opens in the new implementation

**Comment by annezazu** [comment]
Great! Thank you all for chiming in and for the broader context.

**Comment by annezazu** [comment]
This is much different in 6.7 RC1! Closing out:

![Image](https://github.com/user-attachments/assets/65cf23d0-6655-4ced-9023-8551ce0974a8)
