### ISSUE TITLE
Navigation: Inaccurate description of the Show icon button setting

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#55163]
### Description

The Navigation block provides a 'Show icon button' setting to change the appearance of _both_ the button to open the navigation _and_ the button to close it:

<img width="317" alt="Screenshot 2023-10-09 at 15 16 48" src="https://github.com/WordPress/gutenberg/assets/1682452/d0d8f057-1a28-42fa-aa44-8da1f1239488">

However, the description of the settings only mentions the 'opening' button:

`Configure the visual appearance of the button opening the overlay menu.`

That's wrong and should be changed with a more accurate description.

### Step-by-step reproduction instructions

- Go to the site editor
- Add a Navigation block if there is none yet.
- Select the Navigation and observe the settings panel.
- Observe the "Show icon button' setting visually shows both the opening and closing buttons.
- Observe its description only mentions the opening button.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by masteradhoc** [comment]
@afercia my propose to keep it still short and precise would be:
`Configure the visual appearance of the button opening and closing the overlay menu.`

see #55429
