### ISSUE TITLE
Layout Flex: Width and layout settings remove each other's styles in editor

### ISSUE THREAD

**Issue by dmoux** [WordPress/gutenberg#55161]
### Description

When changing the width of inner block (fill or fixed) of the flex parent, the layout styles are removed. Conversely, if the layout settings are changed, the width style is removed. Only in the block editor, on the front version, all styles work correctly.

### Step-by-step reproduction instructions

1. Create a post, add a Row block and add another Row block inside it. For better clarity, fill this inner block with color and add text to it.
2. Set the width for the inner Row block (Fill or any fixed width).
3. Then change justification setting for the same block.
4. Observe that the width has become auto again.
5. If you set the width again to a new value, the block will be displayed with the new width, but the justification settings will not be applied.
6. Save the post and open the page on the front. Observe that all styles and widths and justification are displayed correctly.

### Environment info

WordPress 6.4 and current plugin version.
WordPress 6.3 works correctly.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tellthemachines** [comment]
Thanks for reporting this! The issue has already been fixed in #55291 which will ship in the next plugin version.
