### ISSUE TITLE
Image And Cover Image Icons are Identical

### ISSUE THREAD

**Issue by charleyf** [WordPress/gutenberg#5516]
## Issue Overview

The icons for adding an image block and cover image block are the same. This is particularly confusing when you're adding a new block and want to use the quick access menu to the right (see screenshot).

## Version Numbers
Wordpress 4.9.4 (on DreamHost)
Gutenberg plugin 1.3.1
Theme "Advanced Twenty Seventeen"

## Steps to Reproduce

1. Create a new image block, upload an image.
2. Create a new cover image block, upload an image.
NOTE: I'm not entirely sure that uploading is necessary, it might be enough to simply create a block, but that's how I did it.
3. Press enter in a text block to get a new text block.
4. Look to the right of the text area in the new block, note that there are two identical icons. By hovering over them you can see what the each do, but you can't tell from the icon.

## Expected Behavior

I would expect the icons to be different. I was actually rather confused as to why the default image block behavior was graying out my image and having white text over it. Turns out that's the default -cover- image behavior.

## Possible Solution

I'd expect the solution to be changing the icon for the cover image since that's probably the less commonly used option and the icon in use now looks like a standard "image" icon to me.

## Screenshots / Video

![image](https://user-images.githubusercontent.com/6818839/37182688-71f85c22-2300-11e8-8ada-1083963524fd.png)
![image](https://user-images.githubusercontent.com/6818839/37182699-76058894-2300-11e8-8a49-962c14415719.png)

**Comment by karmatosed** [comment]
This is interesting as it is an image, but I can see a reason to adjust this. cc @jasmussen for inputs on adjusting this. I would be happy either way.

@charleyf what do you think should indicate a cover image?

**Comment by jasmussen** [comment]
Good point. Mocked up an icon here https://github.com/WordPress/dashicons/pull/283

**Comment by boemedia** [comment]
@karmatosed I have seen so many people getting confused by this, because there's no clarifying text when adding a block throught the quick add option in a block. Of course it's an image too. I'd rather see to have one way to add an image, and being able to change settings within the block from 'normal' to 'cover' to add the possibility of full width and overlay text. But I'm not sure if this is a technical challenge. Anyway, to be continued on #283 :)

**Comment by charleyf** [comment]
Moving over to [283](https://github.com/WordPress/gutenberg/issues/283) to answer your question about what I was imagining @karmatosed.

**Comment by sirbrillig** [comment]
(note that when mentioning 283 above, both @charleyf and @boemedia are referring to https://github.com/WordPress/dashicons/pull/283, not issue 283 in this repo)

**Comment by mapk** [comment]
This drives me nuts. All. The. Time. And I hardly ever wait for the tooltip text to pop up. I see the image icon and click it... wanting to add an image... not a cover image.
