### ISSUE TITLE
Custom colors in color palette don't increment on non-English sites

### ISSUE THREAD

**Issue by properlypurple** [WordPress/gutenberg#55185]
### Description

When using the color palette under global styles to add custom colors, every new color should show up like `Color 1`, `Color 2`, and so on. When on a site with a different language, the numbers in custom colors don't increment.

### Step-by-step reproduction instructions

1. On a fresh site, set the site language to French or German.
2. If using the Gutenberg plugin, install the language pack from Dashboard > Updates
3. Start with a block theme(2023, Spectra, etc), and go to `Appearance > Editor`
4. Go `Styles > Colors > Palette`. Click the button to add a new custom color. In French, this would be under `Personnalisé`.
5. Add a few more colors, and notice that the names are all `Couleur 1` by default.
6. Close the editor, and switch the site's language to English.
7. Repeat steps 3-5, and notice that the color names auto-increment `Color 1`, `Color 2`, and so on.

### English 

https://github.com/WordPress/gutenberg/assets/40858144/c4f17b2d-ce08-44a0-8a89-7dfbcc5052e7

### French

https://github.com/WordPress/gutenberg/assets/40858144/b82ab7e1-f703-48ca-b7ad-c53135cff4fc

I've also tested this with German, Spanish, and Brazilian Portuguese, with the same results.

### Environment info

- WP 6.3.1, with or without the Gutenberg (16.7.1) plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by properlypurple** [comment]
It looks like this is related to how the translation is handled here

https://github.com/WordPress/gutenberg/blob/27964574bbf4828a415555a456baeaf61fbdffb0/packages/components/src/palette-edit/index.tsx#L105

**Comment by t-hamano** [comment]
Thanks for the report.

Some issues have been reported for non-Latin languages with the global style custom color palette.

- #49711
- #39210

It may be difficult to solve all of these problems at once, but I believe that #54332 will be the first step towards solving them.

**Comment by t-hamano** [comment]
This issue has been fixed in #52212. The screencast below shows that palette names are incremented correctly even on a French site.


https://github.com/WordPress/gutenberg/assets/54422211/9268adce-08db-4af9-b590-a11bcab86495
