### ISSUE TITLE
Backport Block Renaming Default Attributes

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#55194]
As per discussion in https://github.com/WordPress/gutenberg/pull/54426/files#r1334343353 let's make `metadata` a standard attribute for all blocks in the same way as for `lock` attribute.

https://github.com/WordPress/wordpress-develop/blob/a80165b78f2367f92e2eff679c4e035d1c5bdc7c/src/wp-includes/class-wp-block-type.php#L248-L250

_Originally posted by @getdave in https://github.com/WordPress/gutenberg/issues/54426#issuecomment-1754828325_

**Comment by gziolo** [comment]
@ockham opened PR https://github.com/WordPress/wordpress-develop/pull/5608 to set `metadata` as a global attribute in WordPress core.

**Comment by ockham** [comment]
> @ockham opened PR [WordPress/wordpress-develop#5608](https://github.com/WordPress/wordpress-develop/pull/5608) to set `metadata` as a global attribute in WordPress core.

Committed to Core in https://core.trac.wordpress.org/changeset/57068.
