### ISSUE TITLE
Exit Unordered List with Double Carriage Return

### ISSUE THREAD

**Issue by mrjarbenne** [WordPress/gutenberg#5519]
## Issue Overview

When adding items to an unordered list, hitting Return twice should result in closing the list and creating a new paragraph. Instead, hitting Return at the end of the list leaves the cursor beside an empty bullet. 

## Steps to Reproduce (for bugs)

1. Create an unordered list
2. Add Bullets
3. Once you’ve added the last bullet, hitting Return/Enter on an empty bullet a second time should launch a new paragraph block, but doesn’t.

**Comment by Soean** [comment]
Hey @mrjarbenne,
thanks for your bug report, we already have a ticket for this issue #5122. So I will close this ticket.

**Comment by mrjarbenne** [comment]
Thanks. Sorry about the duplicate. I searched and didn’t see that one. 

Cheers
