### ISSUE TITLE
Pressing cmd/ctrl as a way to navigate into block toolbars

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#552]
This would be a bit of an experiment for accessibility. @afercia and I talked about tis a few weeks back. At the moment, in the current editor, you need to press some magic f# combination to navigate to the toolbars.

Behaviour:

* Press command on Mac or ctrl elsewhere.
* If another key is pressed during, abort.
* If the key is released without any other key pressed (so it was pressed on its own), show the toolbar and move the focus to the first item.
* From there on you can use tabbing or arrow keys to move focus between the buttons.
* If and only if the esc key is pressed, hide the toolbar and refocus the editor at the last position.
* Clicking works as normal of course.

**Comment by iseulde** [comment]
Not that related, but I also like this a lot: http://littlebigdetails.com/post/114672131085/mailbox-holding-the-cmd-key-on-mac-displays-each

**Comment by afercia** [comment]
> some magic f# combination

Ah, I was wondering how to do that :) Big plus from me for the Cmd/Ctrl idea.

**Comment by afercia** [comment]
The ARIA authoring practices suggest, _as an example_, some shortcuts. Most importantly, they describe the expected interaction and some options:
```
Expected keyboard interaction with a rich text editor (outdated, read all for the suggested interaction)
https://www.w3.org/TR/2013/WD-wai-aria-practices-20130307/#richtext
```

In the latest version, there's just a quick mention here (see the note)
```
https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-9
... For example, a rich text editor may have a menubar that receives focus when
a shortcut key, e.g., alt + F10, is pressed while editing.
```

However, I've never got the reasoning behind that. Alt + F10 doesn't seem the most discoverable and easy to remember shortcut. I'd vote for keeping Alt + F10 for users that are used to that and introduce cmd/ctrl as a new, easier one.
