### ISSUE TITLE
Dirty checking on metaboxes not currently working

### ISSUE THREAD

**Issue by squarecandy** [WordPress/gutenberg#5520]
## Issue Overview

Custom Fields generated with ACF do not trigger the dirty form status, therefore the update button remains disabled until a change is made to the title or main Gutenberg editing area.

I have already read https://github.com/WordPress/gutenberg/pull/4184 and several of the issues that directed to it. These make it sound like this has been addressed already, but perhaps we're seeing a regression with the current version.

## Steps to Reproduce (for bugs)

WordPress 4.9.4 and/or 5.0-alpha-42808 (I tested both)
Gutenberg 2.3.0
ACF Pro 5.6.9
Using [this set of fields](https://gist.github.com/squarecandy/b9c28dd9ee4cc2a13fa6547202de3d70) for testing
Tested on Chrome 64 Mac 
Fresh install of all 3 plugins. No other plugins installed.

Make sure there are some ACF fields attached to the page content type (or any other code or plugin that uses native post_meta fields)

## Expected Behavior

- Edit an existing page in Gutenberg mode
- change a field in a meta box
- Press Update to save and publish the changes

## Current Behavior

- create a new page using the Gutenberg editor and click Publish
- continue to edit the page or leave and come back to the page edit screen
- make changes to the custom fields, but not to the title or Gutenberg blocks/content
- the Update button remains disabled and the page cannot be saved
- make a change to the title or body - now the dirty state is triggered and you can save the page

## Possible Solution

Revisit dirty forms and meta boxes / custom fields. Sorry I don't have anything more specific than that right now...

## Screenshots / Video

https://youtu.be/YqPGOfa5ZiA

## Related Issues and/or PRs

https://github.com/WordPress/gutenberg/pull/4184
https://github.com/WordPress/gutenberg/issues/3182

**Comment by jawittdesigns** [comment]
I wanted to add to this that it's just not ACF but this is also affecting all meta boxes.

**Comment by Soean** [comment]
Have you tested the plugin repository version or the GitHub master? 
This issue should be fixed by #5399

**Comment by squarecandy** [comment]
I can't get the npm build to work on my server setup with the current master. Is there a pre-built version available for testing that is more recent than 2.3.0 ?

**Comment by squarecandy** [comment]
Ok, this is resolved in 2.4 - thank you!
