### ISSUE TITLE
Template Parts not displaying when inside patterns

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#55202]
## What problem does this address?
When a template part is inside a pattern block, it appears missing on the frontend. To reproduce:

1. Update to the latest version of WordPress trunk
2. Switch to the TT4 theme
3. Open the site in the frontend and you'll see this error:
```Template part has been deleted or is unavailable: header ```

## What is your proposed solution?
This seems to have been introduced in https://github.com/WordPress/gutenberg/pull/54651

The problem seems to be that although the template parts are given theme slugs when they are processed by `traverse_and_serialize_blocks`, when the block code itself comes to process the block the theme slug is missing. I can't work out why.

cc @gziolo as you worked on https://github.com/WordPress/gutenberg/pull/54651 :)

**Comment by gziolo** [comment]
@ockham, it is very likely that we missed adding the replacement for `_inject_theme_attribute_in_block_template_content` for patterns as they can also contain template parts.

The way to validate that would be to replace the following code:

https://github.com/WordPress/wordpress-develop/blob/33d124299255e7f7faa3f2dbb5f1c6bb43f9b0f4/src/wp-includes/class-wp-block-patterns-registry.php#L167-L172

to look more like:

https://github.com/WordPress/wordpress-develop/blob/33d124299255e7f7faa3f2dbb5f1c6bb43f9b0f4/src/wp-includes/block-template-utils.php#L552-L560

**Comment by scruffian** [comment]
It works! https://github.com/WordPress/wordpress-develop/pull/5450

**Comment by t-hamano** [comment]
It looks like an error similar to this issue has been reported. However, these issues were reported a long time ago and may not be directly related...

- #44243
- #37128

**Comment by gziolo** [comment]
@t-hamano, thank you for posting references to other tickets. It would be great to test them with all the latest changes as it seems that they could get resolved, too.

**Comment by mikachan** [comment]
I believe this has been fixed with https://github.com/WordPress/wordpress-develop/pull/5450, so we can probably close this.
