### ISSUE TITLE
Layout: Stack block loses its flex-direction style after changing its child layout

### ISSUE THREAD

**Issue by jsnajdr** [WordPress/gutenberg#55249]
**Steps to reproduce:**
Create a flex layout with a row + stack + two items structure:
```
<!-- wp:group {"layout":{"type":"flex"}} -->
  <div class="wp-block-group">
    <!-- wp:group {"layout":{"type":"flex","orientation":"vertical"}} -->
      <div class="wp-block-group">
        <!-- wp:paragraph -->
          <p>First row</p>
        <!-- /wp:paragraph -->
        <!-- wp:paragraph -->
          <p>Second row</p>
        <!-- /wp:paragraph -->
      </div>
    <!-- /wp:group -->
  </div>
<!-- /wp:group -->
```
It is displayed in the editor like this, with the paragraph item laid out in a column:

<img width="679" alt="Screenshot 2023-10-11 at 12 58 32" src="https://github.com/WordPress/gutenberg/assets/664258/a0740db3-712f-4625-8094-8fb0a18bca8b">

Now select the Stack group, and go to its Styles / Dimensions / Width settings:

<img width="281" alt="Screenshot 2023-10-11 at 13 01 04" src="https://github.com/WordPress/gutenberg/assets/664258/c21c57b0-8488-4de1-93aa-3c846c104e17">

Here change "Fit" to "Fill". And then change back to "Fit" (because you don't like the change).

After switching to "Fill" the Stack block's items are suddenly aligned horizonally and they stay horizonal even after you change back to "Fit":

<img width="663" alt="Screenshot 2023-10-11 at 12 59 39" src="https://github.com/WordPress/gutenberg/assets/664258/90069e7c-f3a8-4584-99df-b388a4441475">

My layout is still broken even though I returned back to the original "Fit" option. The only way how to get the original back is Undo or page reload.

The horizonal alignment is caused by the fact that the Stack block originally has a `flex-direction: column` style:

<img width="394" alt="Screenshot 2023-10-11 at 13 02 57" src="https://github.com/WordPress/gutenberg/assets/664258/2aee5544-ce49-436f-9ad8-94f3a8713e30">

but that style disappears after switching to "Fill". And is not re-added after returning to "Fit".

**Comment by tellthemachines** [comment]
I can reproduce this in 6.4 as well as Gutenberg trunk. Looking into it now

Edit: looks to have been caused by #54466
