### ISSUE TITLE
Patterns: Add descriptions to user-created patterns

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#55244]
## What problem does this address?
Pattern descriptions add important information for any user who is not able to see the blocks that are included in a pattern, or any user who needs the information in a different format than the preview.

There is no way for a user to add a description to user-created patterns.

## What is your proposed solution?
Perhaps the excerpt field could be re-purposed as a description for this post type.

**Comment by richtabor** [comment]
I agree this could be nice, especially as patterns keep evolving. 

Something like this: 

<img width="400" alt="patterns-inspector" src="https://github.com/WordPress/gutenberg/assets/1813435/4e49f9ac-2b25-469a-a622-6b3840e2bc77">

**Comment by richtabor** [comment]
@youknowriad how would you see this best reconciling for patterns, related to the ongoing consolidation efforts in https://github.com/WordPress/gutenberg/pull/57049

**Comment by youknowriad** [comment]
I'm going to be working on the excerpt field soon to show it similarly in site and post editors. If the post type supports excerpts then it will show up.

**Comment by youknowriad** [comment]
This PR #57096 adds the excerpt panel to the site editor. So if we enable excerpt support for `wp_block` post type as a follow-up, the panel will show up.

**Comment by richtabor** [comment]
> So if we enable excerpt support for wp_block post type as a follow-up, the panel will show up.

@carolinan do you mind taking that? 🙇

**Comment by carolinan** [comment]
Adding the excerpt support is easy enough, but I found a bug with the Site Editor Pattern screen. There is a regression where there is no way for a screen-reader to actually read out the description to the user, no matter if "grid" or "list" is selected.

**Comment by richtabor** [comment]
Noting that this is supported now. The UI could be much better (it's not quite discoverable). 

![CleanShot 2024-04-25 at 12 54 02](https://github.com/WordPress/gutenberg/assets/1813435/3c5ecd16-021f-471d-935e-364f9911d601)
