### ISSUE TITLE
Block Theme Previews: Activate button has no loading state

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#55273]
## What problem does this address?
When activating a block theme from a preview, the "Activate" button should show a loading state, but instead it just stays blue:

https://github.com/WordPress/gutenberg/assets/275961/c450af7e-0a0f-4a33-8046-1c45f1a97517

## What is your proposed solution?
The activate button needs a loading state to communicate clearly to the user that an action is happening in the background. This is how the save button usually works in the site editor.

Props to @autumnfjeld for raising this.

**Comment by scruffian** [comment]
I spent a long time investigating this today. Here are my findings.:

1. The state of the button that we care about is the one in [this file](https://github.com/WordPress/gutenberg/blob/d2bf1366d55f8fad5edeebd521eda29b610d19bc/packages/edit-site/src/components/save-button/index.js#L17).
2. Setting `isBusy` to true on this button gives it a loading state.
3. At present this state is connected to the `isSavingEntityRecord` selector.
4. This selector doesn't work for activating a theme, since a theme activation isn't an entity.
5. The action that activates the theme is triggered by [the save panel](https://github.com/WordPress/gutenberg/blob/d2bf1366d55f8fad5edeebd521eda29b610d19bc/packages/edit-site/src/components/save-panel/index.js#L53) not the save button, which makes it very difficult to connect the two together.

I am not sure how to proceed. I think we need a way to save the state of the activation in the global state, which means we probably need a new key for it in the store.

**Comment by autumnfjeld** [comment]
> Props to @autumnfjeld for raising this.

I'm just the messenger props go @fushar and also our great testers. :)

**Comment by okmttdhr** [comment]
>I am not sure how to proceed. I think we need a way to save the state of the activation in the global state, which means we probably need a new key for it in the store.

@scruffian 
This seems to make sense to me, as the two components are independent!

**Comment by arthur791004** [comment]
@scruffian I proposed https://github.com/WordPress/gutenberg/pull/55658 to resolve this issue. It's simple but I'm unsure whether it's a good idea. WDYT?
