### ISSUE TITLE
Font Library: refactor REST API

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#55278]
## What?
Font Library: refactor REST API endpoints.

### Refactor REST endpoint URLs
([reference](https://github.com/WordPress/wordpress-develop/pull/5285#discussion_r1335911520) [reference](https://github.com/WordPress/wordpress-develop/pull/5285#discussion_r1335916249)).
PR:
- https://github.com/WordPress/gutenberg/pull/57282

### Transition the Font Family APIs to be SINGULAR
(accepting as parameters and returning as responses a single Font Family item) ([reference](https://core.trac.wordpress.org/ticket/59166#comment:9) [reference](https://wordpress.slack.com/archives/C02RQC26G/p1696281308965689) )

PR:
 - https://github.com/WordPress/gutenberg/pull/57569

### Return a single Error (with multiple calls to `add()`)
instead of a collection of errors. ([reference](https://github.com/WordPress/wordpress-develop/pull/5285#discussion_r1337045813) [reference](https://github.com/WordPress/wordpress-develop/pull/5285#discussion_r1337060481) )

### Return API responses with `rest_ensure_response` instead of `new WP_REST_Response()`
([reference](https://github.com/WordPress/wordpress-develop/pull/5285#discussion_r1342760618))

### Ensure there is error handling of any decoded JSON string
( [reference](https://github.com/WordPress/wordpress-develop/pull/5285#discussion_r1342767882) )

### Add schema's to the requests
([reference](https://github.com/WordPress/wordpress-develop/pull/5285#discussion_r1342770186))

### Break the font library REST API controller in 2 controllers.
One for font families and one for font collections. ([reference](https://wordpress.slack.com/archives/C02RQC26G/p1696366631579099))

PR:
- https://github.com/WordPress/gutenberg/pull/57282

### Error code strings need to be translated
([[reference](https://github.com/WordPress/wordpress-develop/pull/5285/files#r1345355956)]). 

### Ensure the gutenberg domain used for translations is removed when porting to core.
([reference](https://github.com/WordPress/wordpress-develop/pull/5285#discussion_r1335914971))

## Why?
To standardize the endpoint routes and input/output data formats and schemas.

## How?
This task is somewhat big, so multiple PRs for it are expected.

--- 

Props to all the folks that brought this issue in this PR: https://github.com/WordPress/wordpress-develop/pull/5285

**Comment by creativecoder** [comment]
Note that I've outlined a proposed API design used for this refactoring effort in https://github.com/WordPress/gutenberg/issues/57616

**Comment by mikachan** [comment]
Can this be closed now that https://github.com/WordPress/gutenberg/pull/57688 is merged?

**Comment by matiasbenedetto** [comment]
Yep, let's close it and work over more granular issues.
