### ISSUE TITLE
Clean up unneeded style overrides for `Notice` component

### ISSUE THREAD

**Issue by ecgan** [WordPress/gutenberg#55279]
In PR https://github.com/WordPress/gutenberg/pull/54800, we removed the margins for the `Notice` component.

In https://github.com/WordPress/gutenberg/pull/54800#issuecomment-1754879877:

> I think it would be great to have a small follow-up cleaning any related style overrides (that now are not necessary anymore) like the ones listed in [#54800 (comment)](https://github.com/WordPress/gutenberg/pull/54800#discussion_r1347001957).
> 
> We could look for `.components-notice` and see what we find.

This issue is a follow-up to the above comment to remove unneeded style override for `Notice` component.

Here's an example taken from issue https://github.com/WordPress/gutenberg/issues/54741 - we should remove the margin override:

![image](https://github.com/WordPress/gutenberg/assets/417342/37e63878-b94d-4154-b61c-f1e9bda19713)

**Comment by t-hamano** [comment]
Fixed by #57794
