### ISSUE TITLE
Add @woocommerce namespace to dependency extraction plugin

### ISSUE THREAD

**Issue by kimmenbert** [WordPress/gutenberg#55282]
## What problem does this address?
For developers developing on both WordPress and WooCommerce, including @woocommerce dependency extraction to the @wordpress/dependency-extraction-webpack-plugin would offer a couple of benefits when using @wordpress/scripts:

- No need to install @woocommerce/dependency-extraction-webpack-plugin
- No need to extend the @wordpress/script webpack config
- No need to manage version parity with @wordpress/scripts
- Simpler to document how to use @woocommerce packages

## What is your proposed solution?
Either include `@woocommerce` namespaces in `@wordpress/dependency-extraction-webpack-plugin`
Or include `@woocommerce/dependency-extraction-webpack-plugin` in `@wordpress/scripts`

**Comment by peterwilsoncc** [comment]
I don't see any value to the wider WordPress ecosystem in adding WooCommerce dependencies to wp-scripts.

The WooCommerce team does a good job of maintaining their [dependency-extraction-webpack-plugin](https://github.com/woocommerce/woocommerce/commits/trunk/packages/js/dependency-extraction-webpack-plugin) and adding support for one company's packages would be unfair to other companies.

**Comment by gziolo** [comment]
Could WooCommerce provide their shared webpack config instead, with everything configured as necessary?

**Comment by senadir** [comment]
Wouldn't that mean a shift from using `@wordpress/scripts`? How would this happen while still maintaining a single source of truth for documentation?

**Comment by peterwilsoncc** [comment]
@senadir I think it would & add a dependency outside of the control of WordPress contributors. 

As the WooCommerce Dependency Extraction webpack plugin is [well documented](https://developer.woocommerce.com/2020/11/16/woocommerce-dependency-extraction-webpack-plugin/) with a webpack configuration file, I'll close this ticket as unplanned.
