### ISSUE TITLE
Mentions Autocomplete is re-rendeing on each keypress

### ISSUE THREAD

**Issue by WunderBart** [WordPress/gutenberg#55299]
### Description

Originally mentioned in https://github.com/WordPress/gutenberg/issues/55118#issuecomment-1751040571

The constant rerendering of the results popup is causing issues for accessibility. 

The responsible part seems to be the [popup cloning via `createPortal`](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/autocomplete/autocompleter-ui.tsx#L169-L174) as it does not rerender when that part is removed. Kudos to @chad1008 for pinning it down.

cc: @ellatrix, since you worked on this part recently.

### Step-by-step reproduction instructions

1. create a new post
2. type "@" to trigger the mentions autocomplete popup
3. navigate the results with arrow down/up and notice the rendering

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1451471/a8ab4374-6d5e-48df-a94e-6e4c8d17cd81

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by alexstine** [comment]
Labeling this as low priority. Not urgent that this gets fixed, just something to improve on later.

**Comment by jsnajdr** [comment]
Fixed by #61877.
