### ISSUE TITLE
In-between inserter ignores locking via template_lock

### ISSUE THREAD

**Issue by kraftner** [WordPress/gutenberg#5531]
## Issue Overview
If you lock a template [as explained in the docs](https://wordpress.org/gutenberg/handbook/templates/#locking) you can afterwards still add new paragraph blocks by using the "in-between inserter".

## Steps to Reproduce (for bugs)

1. Define a template and set `template_lock` to `all` or `insert`
2. Edit a post
3. Click between the blocks defined by the template

## Expected Behavior

I'd expect the "in-between inserter" to be disabled as well by setting `template_lock` to `all` or `insert`

## Current Behavior

You can still insert paragraph blocks. Even if the   `core/paragraph` block type is disabled via `allowed_block_types`

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jasonbahl** [comment]
related to #5521
