### ISSUE TITLE
Viewport width not accounted for in the site editor > patterns view

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#55324]
Twenty Twenty-Four includes a number of patterns that set the viewport width of the pattern ([source](https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/clients.php#L7)), so that a pattern display nicely within the inserter. 

This works fine in the inserter, but within the site editor > patterns view, the viewport width value is omitted. I would expect the patterns to display exactly the same anywhere the preview is rendered. 

As seen in the patterns inserter and explorer (expected):
![CleanShot 2023-10-12 at 15 09 36](https://github.com/WordPress/gutenberg/assets/1813435/bf5a2f3c-1737-4928-ac07-38386a11a8ac)
![CleanShot 2023-10-12 at 15 11 56](https://github.com/WordPress/gutenberg/assets/1813435/b93d398a-61d9-41ec-aacb-67e0f7a2c755)

As seen in the site editor > patterns view: 
![CleanShot 2023-10-12 at 15 09 44](https://github.com/WordPress/gutenberg/assets/1813435/cb613039-0365-483b-8f7a-8f029baa40a8)

**Comment by t-hamano** [comment]
Maybe it's because [the first letter of width is a lowercase letter](https://github.com/WordPress/twentytwentyfour/blob/61a733f9d1050c131c3b711b7a9131f08db34b33/patterns/banner-hero.php#L6)? It looks like the pattern requires a header called `Viewport Width`.

https://github.com/WordPress/wordpress-develop/blob/cc2133fc3448de9bc050c0a7484f9a08c206847c/src/wp-includes/class-wp-theme.php#L1865

**Comment by richtabor** [comment]
> Maybe it's because [the first letter of width is a lowercase letter](https://github.com/WordPress/twentytwentyfour/blob/61a733f9d1050c131c3b711b7a9131f08db34b33/patterns/banner-hero.php#L6)? It looks like the pattern requires a header called Viewport Width.

Hm, I'll check — but they do work properly in the inserter > patterns views.

**Comment by richtabor** [comment]
> Maybe it's because [the first letter of width is a lowercase letter](https://github.com/WordPress/twentytwentyfour/blob/61a733f9d1050c131c3b711b7a9131f08db34b33/patterns/banner-hero.php#L6)?

I confirmed the casing has no effect. I set the Viewport Width to 500 (to ensure we can see the difference) and it renders fine in the patterns inserter, but is omitted in the site editor. 

![CleanShot 2023-10-31 at 11 35 11](https://github.com/WordPress/gutenberg/assets/1813435/5a0acb7d-985d-49fc-b148-32c9a5af81c0)
![CleanShot 2023-10-31 at 11 35 21](https://github.com/WordPress/gutenberg/assets/1813435/e9b2a2ee-7877-4097-936e-0c843dbbb1f1)

**Comment by t-hamano** [comment]
Thanks for the testing. I've also tested it and it looks like the pattern page view certainly doesn't take the viewport width into account.

I tested two patterns with viewport width defined as 500px or 1000px.

<details><summary>patterns/width-500.php</summary>

```html
<?php
/**
 * Title: Viewport Width 500
 * Slug: emptytheme/width-500
 * Categories: banner
 * Viewport Width: 500
 */
?>

<!-- wp:paragraph {"style":{"typography":{"fontSize":"60px"}}} -->
<p style="font-size:60px">ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ</p>
<!-- /wp:paragraph -->
```

</details> 

<details><summary>patterns/width-1000.php</summary>

```html
<?php
/**
 * Title: Viewport Width 1000
 * Slug: emptytheme/width-1000
 * Categories: banner
 * Viewport Width: 1000
 */
?>

<!-- wp:paragraph {"style":{"typography":{"fontSize":"60px"}}} -->
<p style="font-size:60px">ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ</p>
<!-- /wp:paragraph -->
```

</details> 


| | Viewport Width: 500 | Viewport  Width: 1000 |
|--------|--------|--------|
| Pattern Inserter |  ![500-inserter](https://github.com/WordPress/gutenberg/assets/54422211/e6a035ee-0347-41a0-b3c5-3a8485232035) |  ![1000-inserter](https://github.com/WordPress/gutenberg/assets/54422211/c71d5ccb-6232-460b-a6ed-0c3f44541410) |
| Pattern Inserter Modal |  ![inserter-modal-500](https://github.com/WordPress/gutenberg/assets/54422211/8385d302-a456-45b9-ab65-aa45ee7e4384) |  ![inserter-modal-1000](https://github.com/WordPress/gutenberg/assets/54422211/5636382d-2c9e-4c6a-8d1a-fc6ca4d78d1f) |
| Patterns page view |  ![patterns-page-500](https://github.com/WordPress/gutenberg/assets/54422211/c79f58e4-5b74-4731-a1c0-31febf10cdea) | ![patterns-page-1000](https://github.com/WordPress/gutenberg/assets/54422211/011af152-c117-4dbf-9fea-2ca104d43ba3) |
