### ISSUE TITLE
Convert Rename Menu Item to standard menu item not Plugin

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#55338]
**Update**: when implementing this we can [draw on a bug fix](https://github.com/WordPress/gutenberg/pull/55604) which went directly into the `wp/6.4` branch.

As suggested by @jsnajdr let's make the "Rename" menu item into a default item within the menu as per `BlockLockMenuItem`:

https://github.com/WordPress/gutenberg/blob/ef21f207827e1ac9e23c307ca2a7efaf4366b6c6/packages/block-editor/src/components/block-settings-menu-controls/index.js#L83

We can then remove the filter thus avoiding any perf concerns with the Plugin-based approach.

> Alternatively, the rename UI doesn't need to be a plugin. It could be hardcoded directly into the Block Settings Menu, like, for example, `BlockLockMenuItem` is.

I think what you suggest above is the most pragmatic option for now. This could be actioned in tandem with the follow up in https://github.com/WordPress/gutenberg/issues/55194 to make metadata a default global attribute.

_Originally posted by @getdave in https://github.com/WordPress/gutenberg/issues/55250#issuecomment-1761099347_

**Comment by Mamaduka** [comment]
Great idea!

**Comment by getdave** [comment]
This is on my radar for the 6.5 cycle.
