### ISSUE TITLE
Enable styling of core/heading block per tag

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#55333]
## What problem does this address?
It is not possible to style individual tags in `core/heading` block. I would expect that elements section works just as for other blocks. This partial from `theme.json` does not apply specific styles to h1, h2, h3:

```
			"core/heading": {
				"typography": {
					"fontFamily": "var(--wp--preset--font-family--title-font)",
					"fontWeight": "700",
					"lineHeight": "1.2"
				},
				"elements": {
					"h1": {
						"typography": {
							"fontSize": "4.375rem",
							"textTransform": "uppercase"
						}
					},
					"h2": {
						"typography": {
							"fontSize": "2.5rem"
						}
					},
					"h3": {
						"typography": {
							"fontFamily": "var(--wp--preset--font-family--content-font)"
						}
					}
				}
			},
```

## What is your proposed solution?
Enable styling per tag, just as for other blocks. This is needed feature, I find myself often needed that and thus I am forced to style them in a separate css style file.

**Comment by t-hamano** [comment]
Hi @Lovor01,

I think you can apply styles according to the heading level as shown below.

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"styles": {
		"elements": {
			"h1": {},
			"h2": {},
			"h3": {},
			"h4": {},
			"h5": {},
			"h6": {}
		}
	}
}
```

However, this definition applies to all heading "elements". Do you want to limit this style to heading "blocks" only?

**Comment by Lovor01** [comment]
> Hi @Lovor01,
> 
> I think you can apply styles according to the heading level as shown below.
> 
> ```json
> {
> 	"$schema": "https://schemas.wp.org/trunk/theme.json",
> 	"version": 2,
> 	"styles": {
> 		"elements": {
> 			"h1": {},
> 			"h2": {},
> 			"h3": {},
> 			"h4": {},
> 			"h5": {},
> 			"h6": {}
> 		}
> 	}
> }
> ```
> 
> However, this definition applies to all heading "elements". Do you want to limit this style to heading "blocks" only?

This is only a partial solution - it styles _all_ headings in a document including the ones in other blocks, not only in heading blocks. Further, any properties defined this way are overriden by the same styling properties in block core/heading styles.

I think for the sake of better styling possibilities and consistency, elements inside core/heading block should work.

**Comment by t-hamano** [comment]
I found #55417 reporting a similar issue. Let's close this issue as #55417 has been explored in more detail.
