### ISSUE TITLE
Starting out blank or with selecting a template layout.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#5537]
Brainstorming...
Today starting out blank looks like this (I have an active SEO plugin so that the meta boxes show up below):

![screen shot 2018-03-09 at 10 36 35](https://user-images.githubusercontent.com/5323259/37215407-d90028f2-2385-11e8-9549-0fea7b4de282.png)

Meta boxes really should stick/be fixed to the bottom and there should be more space between the meta boxes border line and the block layout area.

--

Clicking into the "Write your story" block (line) and then clicking somewhere else the block looks like this:

![screen shot 2018-03-09 at 10 44 39](https://user-images.githubusercontent.com/5323259/37215814-040820f8-2387-11e8-8974-76496eb044ad.png)

So the initial writing block first has the text:
"Write your story". As one has clicked into it and out again it changes to "Add text or type / to add content". 

---

Another option when starting could be to see a template gallery of thumbnail previews of post/page templates to begin with. 

Perhaps something similar to this wireframe:

![starter-design-templates](https://user-images.githubusercontent.com/5323259/37216662-57dd7014-2389-11e8-9401-0f4ac10d0e0b.jpg)

Creating templates.
Create post/page layouts and save them as a template to be added to the initial starter design area for a new post/page. Plus have a way to load in a full template into an existing post/page. Either having it overwrite or added to an existing layout.

(I will add on to this issue when additional things come up.)

**Comment by paaljoachim** [comment]
Another wireframe where I also include a blank template.

![initial-starter-page-gutenberg-2](https://user-images.githubusercontent.com/5323259/37874304-39d8309e-302d-11e8-91c3-0a50d8418817.jpg)

**Comment by jasmussen** [comment]
CC: @melchoyce

**Comment by melchoyce** [comment]
Hey, I totally agree @paaljoachim! This is one of the first features we have planned for the Customization phase of Gutenberg. We'll be posting up some more information soon.

**Comment by karmatosed** [comment]
I am closing this as it's planned as part of Customization and there would be a new issue for this along with that with @melchoyce's solution and in phase two. Thanks everyone.

**Comment by paaljoachim** [comment]
I have continued some exploration in regards to mainly starter layouts.

![initial-starter-page-gutenberg-template-structure-reusable-blocks](https://user-images.githubusercontent.com/5323259/50725808-bcb40800-1103-11e9-930b-cd14586099d3.jpg)

1. User creates a new page/post.
2. Goes to the Layout section top right.
First option would be select layout - drop down - with these drop down options:
**Template** - user selects it and a modul (?) shows up on the left showing already saved templates.

Structure - user selects it and it shows up on the left showing structure.

Reusable blocks - user selects is and it shows up on the left.

As the modul (?) is open on the left the user can easily click to go to the other layout options (template, layout structure and reusable blocks.)

There can also be a save button to where the user can save  page/post as a template.
Select one or more empty blocks and save as a structure. 
(similar to saving empty reusable blocks).

Select one or more content added blocks  and save as reusable blocks.

The reasoning for doing it this way is that it keeps different types of layouts in one area. User can
begin to get used to the various options in one place.

**Comment by melchoyce** [comment]
I did some explorations into page layouts last year that could potentially serve as inspiration for future iterations:

![select layout few](https://user-images.githubusercontent.com/2846578/50842644-223b0b00-1335-11e9-8ff7-c6c7f49f5e4c.png)
![select layout many](https://user-images.githubusercontent.com/2846578/50842650-236c3800-1335-11e9-9932-cf2aefa725ce.png)
![select layout hover](https://user-images.githubusercontent.com/2846578/50842655-2535fb80-1335-11e9-9c51-e6f688ca0d9c.png)
![layout with placeholders](https://user-images.githubusercontent.com/2846578/50842657-26ffbf00-1335-11e9-8343-f8945eff34af.png)

(Mobile mockups: https://cloudup.com/cqfTCSlAjCN)

I put together a prototype as well that I ran a couple user tests on: https://marvelapp.com/7fb3074/screen/38364413

The layout picker, like everything else in Gutenberg, is a block. It consists of a couple elements:

- Block title / description.
- Tabs for categorizing layout types (styled after the block inserter).
  - These are theme-defined.
  - When you only have a couple layouts (let’s say, <5), the tabs don’t appear.
  - If there aren’t any categorized layouts, the tabs don’t appear.
- A list of available page layouts.
  - The layout graphics should be automatically generated based on the blocks included in them. 
  - Images are grey boxes, text is darker grey lines, buttons are blue, etc. We should abstract out everything into simple shapes. 
- Finally, the layout itself.
  - In these mockups, you can see theme styles applied to Gutenberg. If theme styles aren’t declared, blocks would fall back to generic Gutenberg styles.
  - You might also notice the global elements on the page — in this case, the site logo, navigation, and footer. These exist for presentation, but are not editable in this first version of layouts. They uneditable and displayed at 40% opacity.

I also explored what it would look like to change your page layout: https://wp.invisionapp.com/share/M5JCEDX3GKJ

I think we've evolved beyond these initial concepts, but I'm hoping they're still relevant to the conversation.

**Comment by paaljoachim** [comment]
Just adding this in here:
Here is a template test made by @jeremyfelt 
https://twitter.com/jeremyfelt/status/1075932152422756353

**Comment by Soean** [comment]
**Full Site Editing** from Automattic

<img width="959" alt="Screen-Shot-2019-05-30-at-1 28 36-PM" src="https://user-images.githubusercontent.com/695201/58792127-da729400-85f3-11e9-9a26-c4fb61f4eb89.png">

WP Tavern article: https://wptavern.com/automattic-is-testing-an-experimental-full-site-editing-plugin
Plugin on WP.org: https://wordpress.org/plugins/full-site-editing

**Comment by paaljoachim** [comment]
Calypso related full site editing issues:
https://github.com/Automattic/wp-calypso/labels/%5BGoal%5D%20Full%20Site%20Editing
