### ISSUE TITLE
Node 18 support for @wordpress/scripts

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/gutenberg#55374]
## What problem does this address?

Trying to install `@wordpress/scripts` with Node 18 results in an error as `eslint-plugin-jsdoc@36.1.1` doesn't support it.

```
🚚  Fetching packages...
error eslint-plugin-jsdoc@36.1.1: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^16". Got "18.16.0"
error Found incompatible module.
```

## What is your proposed solution?

Upgrade the `eslint-plugin-jsdoc` dependency to support Node 18.

**Comment by t-hamano** [comment]
Hi @adamwoodnz,

With the latest `@wordpres/scripts` package it should also work on Node 18. #47490 added support for Node version 18.

If you have the latest `@wordpres/scripts`, the `eslint-plugin-jsdoc` version should be `46.8.2`.

```bash
$ npm ls eslint-plugin-jsdoc
scripts-test@1.0.0 /home/wildworks/projects/scripts-test
└─┬ @wordpress/scripts@26.14.0
  └─┬ @wordpress/eslint-plugin@17.0.0
    └── eslint-plugin-jsdoc@46.8.2
```

What version of `@wordpress/scripts` are you using?

**Comment by adamwoodnz** [comment]
Ah I tried upgrading to latest and it didn't work, but I've now realised there are package.json files in 3 yarn workspaces and I didn't upgrade them all. That solves it. Thanks for the reply!
