### ISSUE TITLE
Edit-Widgets: CSS is preventing admin notice when JS is off

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#55384]
### Description

Reported first on Core: https://core.trac.wordpress.org/ticket/59628

In the WP 6.4 cycle, changeset [r56671](https://core.trac.wordpress.org/changeset/56671) added the following notice to alert users of requirements when JS is disabled in their browser:

>The block widgets require JavaScript. Please enable JavaScript in your browser settings, or install the Classic Widgets plugin.

However, the following CSS from the edit-widgets package hides the notice:

https://github.com/WordPress/gutenberg/blob/5a04a2b62b62a0a1f57e405dafa520d69f2648d5/packages/edit-widgets/src/style.scss#L57-L61

Here's the HTML:

```html
<div class="wrap hide-if-js widgets-editor-no-js">
   <h1 class="wp-heading-inline">Widgets</h1>
   <div class="notice notice-error hide-if-js">
      <p>The block widgets require JavaScript. Please enable JavaScript in your browser settings, or install the <a href="http://wp64.local/wp-admin/update.php?action=install-plugin&amp;plugin=classic-widgets&amp;_wpnonce=30593b619d">Classic Widgets plugin</a>.
      </p>
   </div>
</div>
```

### Step-by-step reproduction instructions

1. Disable JS in the browser. In Firefox:
   a. Go to `about:config` in the browser URL field.
   b. Click/select "Accept the Risk and Continue" button.
   c. In the text field, type: javascript.enabled.
   d. In the far right column, click/select the icon to set that property to `false`. 
2. In Appearance > Themes, activate a non-block theme, such as Twenty Twenty-One (TT1).
3. Navigate to Appearance > Widgets.
3. 🐞 Notice the H1 appears, but not the notice message.

### Screenshots, screen recording, code snippet

Gif showing it in action:

![no-js-notice-not-showing](https://github.com/WordPress/gutenberg/assets/7284611/e92c9aef-ab77-4e6a-9041-37f0618f1ac0)

### Environment info

* OS: macOS
* Web Server: Nginx
* PHP: 7.4 and 8.1
* WordPress: 6.4 Beta 4
* Browser: Firefox
* Theme: Twenty Twenty-Two
* Active Plugins:
    * WordPress Beta Tester 3.5.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by devmuhib009** [comment]
| Normal State |      After CSS Removed      | 
|----------|-------------|
|![before css off](https://github.com/WordPress/gutenberg/assets/142894870/25f8a9cb-9d30-4842-aff6-6c44ad37ad7c)|![after js off](https://github.com/WordPress/gutenberg/assets/142894870/9be1d515-4680-4ca0-bd93-35ea5d1d7414)|

I just reproduced and checked the issue. After removing the CSS, it's working fine.
