### ISSUE TITLE
Image Compatibility: handle caption shortcode

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#554]
The compat layer for the image block should be able to handle `[caption]`.

**Comment by iseulde** [comment]
Do you mean it should be handled in the freeform block? Wouldn't it be better to just have the old editor exactly as the freeform block, just with a different design? See also #1256.

**Comment by mtias** [comment]
This was meant to allow a way to convert old images with captions into the new shape. I think @azaozz was thinking along these lines as well. We may want to focus on _pasting_ first (from old WP content with shortcodes) as a way to convert, and then see fi we want to also offer an on demand mechanism for it.

**Comment by mtias** [comment]
@iseulde I think we can close this one as being handled by pasting.

**Comment by iseulde** [comment]
Yep, done now in #2874.
