### ISSUE TITLE
Table Block: Block margin override layout margin

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#55409]
### Description

The Table block itself has `margin: 0 0 1em` value. This selector has a higher specificity, so it overrides the margins above the blocks and eliminates the white space between the blocks.

![specificity](https://github.com/WordPress/gutenberg/assets/54422211/775d5bda-b984-4a6e-8afa-6991528f10ce)

![table](https://github.com/WordPress/gutenberg/assets/54422211/e332b452-d1ad-4f7c-8d27-dab7f84d893f)

From what I remember, the selector specificity of the layout was reduced. I think this may have brought this issue to the surface. The figure element, which is a wrapper element for the table block, already [has a low-specificity style](https://github.com/WordPress/gutenberg/blob/017d1ad368b0a0c4dcd9d148fa196919ebe43246/packages/block-library/src/common.scss#L161-L163). Therefore, I think the block margin should be removed.

By the way, this style for the Table block exists in [theme.css](https://github.com/WordPress/gutenberg/blob/017d1ad368b0a0c4dcd9d148fa196919ebe43246/packages/block-library/src/table/theme.scss#L1). However, an issue has been reported in #54783 where the Gutenberg plugin's `theme.css` cannot override the core `theme.css`. Therefore, it is not possible to debug whether or not removing the block margin has resolved the issue. Regarding this issue, I submitted #54936.

### Step-by-step reproduction instructions

- Insert multiple blocks, including the table block.
- There should be no margin above the table block.

### Environment info

- WordPress 6.4-RC1
- I also reproduce it with the latest Gutenberg trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@t-hamano thanks so much for opening all these various issues! Can you please start including GB and WP versions when you do so? We are in the middle of the 6.4 cycle and it's critical we know which issues are relevant for triaging purposes.

**Comment by t-hamano** [comment]
Sorry for causing confusion. In the issue I recently submitted, I added information about whether the problem is occurring with WordPress 6.4RC1 or the latest Gutenberg.

**Comment by t-hamano** [comment]
This issue seems to be resolved in the latest Gutenberg. I think the following PRs are probably related.

- [#57699](https://github.com/WordPress/gutenberg/pull/57699/files#diff-04171e764e70e7bff6c7df43c2a9dd7ad31ad1360ad6e74cf96c343a13402678L1-L4): Margin has been removed from the table block
- [#59457](https://github.com/WordPress/gutenberg/pull/59457/files#diff-a9d56f8c3786301af3f0eef72281639be19e361ab414a02a778403ff9d629d0cR12-R14): Margin specificity has been reduced
