### ISSUE TITLE
[Create Block] Add the capability of defining a function from a template to modify values passed to create the block

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/gutenberg#55421]
## What problem does this address?

Currently it's not possible to modify any of the values passed to create-block either from the CLI or a custom template. This means that any new functionality must be added via a flag and that there is no way to customize a large portion of these values in a template. For example, `textdomain` is always the slug value that is passed and is not changeable.

## What is your proposed solution?

I would like to introduce a transformer property that can be defined in an external template. This property would expect a function that receives all of the values that will be used to generate the files. This feature would provide complete control over the values being output and allow for conditional values based on others.

### Example
In this example, we can generate a unqiue id that is prepended to the passed `slug` but then also usable for other properties.

```js
transformer: ( view ) => {
    const hex = getRandomHexCode();
	return {
		...view,
		slug: `${ view.slug }-${ hex }`,
		customBlockJSON: {
			...view.customBlockJSON,
			keywords: [ ...view.customBlockJSON.keywords, hex ],
		},
	};
},

**Comment by gziolo** [comment]
That's a pretty powerful idea, I will leave my feedback on the proposed implementation with https://github.com/WordPress/gutenberg/pull/55423.

**Comment by gziolo** [comment]
> For example, textdomain is always the slug value that is passed and is not changeable.

This one should be tackled separately as I saw an issue raised somewhere that it's impossible to set the `textdomain` when scaffolding a block without a plugin. There usually should be only one `textdomain` set for the plugin.

**Comment by ryanwelcher** [comment]
With the changes I just pushed, it is possible to manage the `textdomain` via the transformer.
