### ISSUE TITLE
[Language] different language broken the editor

### ISSUE THREAD

**Issue by Bizarrus** [WordPress/gutenberg#5542]
## Issue Overview
Editor are broken, when click or create an block.

## Steps to Reproduce (for bugs)
Seems to be a language problem, using german language

## JavaScript Console
> react-dom.min.3583f8be.js:162 [sprintf] property "selectedCount" does not exist

## Screenshots
![g1](https://user-images.githubusercontent.com/1371300/37235452-19c8904e-23ff-11e8-9f30-7e306a364533.JPG)

## Solution Idea
If translation is missing, using default language like english

**Comment by Bizarrus** [comment]
Found duplicates:
#5529, #5459

**Comment by Soean** [comment]
@Bizarrus 
Have you tested the Plugin repository version oder the GitHub Master?

**Comment by Bizarrus** [comment]
Both; But not the current, if last days has new commits/fixes

**Comment by Soean** [comment]
Can't reproduce the bug with different languages, please reopen if it's still an issue.
