### ISSUE TITLE
Front Page Template: With Static Homepage set under Settings > Reading, site editor defaults to static page, not Front Page Template

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#55431]
### Description

If I set a static homepage on a site that uses a theme with a Front Page template, the editor defaults to the static page upon opening, even though the Front Page template is still the site's homepage.

The description in the editor of the Front Page Template reads:

> Displays your site's homepage, whether it is set to display latest posts or a static page. The Front Page template takes precedence over all templates.

### Step-by-step reproduction instructions

1. Activate a theme like [Kigen](https://wordpress.org/themes/kigen/)
2. Open Settings > Reading and set any static page as the homepage
3. Open Appearance > Editor _(Observe: site editor opens to static page)_
4. In a new tab, check the site itself _(Observe: front page template is still the site's homepage)_

### Screenshots, screen recording, code snippet

**Editor showing static page**

https://github.com/WordPress/gutenberg/assets/27249804/88788d9f-0c00-4ce0-ac52-cb49e956b0e8

**Site's Live Home Page still Front Page Template:**

![Markup on 2023-10-17 at 16:26:31](https://github.com/WordPress/gutenberg/assets/27249804/02d21a29-8189-40e5-ab37-bad7a1f8559e)

### Environment info

- WordPress 6.3.2
- Gutenberg 16.8.1, 16.7.1

Gutenberg version 16.6.0 does not show the static homepage in the editor, but the Front Page Template, as expected.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
This has been resolved in #56418
