### ISSUE TITLE
Patterns: Add option to preview locked patterns and/or better explain lock status

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#55469]
Right now, when you head to Site Editor > Patterns, patterns provided by the theme are visible but locked without the ability to click on them to preview in a larger format. If you click on the patterns multiple times, nothing happens and it's not clear why exactly they are locked or if something needs to be done to unlock them.

https://github.com/WordPress/gutenberg/assets/26996883/c15bae18-3982-41aa-b84e-239a2a358ed3

This isn't very intuitive! A few ideas to iterate:

- Add a "view only" option to preview the pattern or a way to see the pattern in a larger but still locked format.
- Add some sort of experience similar to the template vs content experience where if you click numerous times on a locked pattern, a snack bar notice appears that has an action to "duplicate pattern". 

@richtabor curious for your thoughts here.

**Comment by richtabor** [comment]
I'd like them to work just like template parts, where you can edit it and the pattern is yours. Perhaps you can reset them (just like template parts). 

You should be able to edit any pattern where they are present. Instead of currently, where you have to duplicate the pattern into My Patterns first - which means the original pattern is in the way.

**Comment by colorful-tones** [comment]
I mistakenly thought the lock icon represented a synced pattern in my recent WP 6.4 walk-through (on YT). I did not realize it until after the fact, and I’m afraid I’m dispersing misinformation, but I do feel like it could be confused for that as well.

**Comment by carolinan** [comment]
> I'd like them to work just like template parts, where you can edit it and the pattern is yours. Perhaps you can reset them (just like template parts).
You should be able to edit any pattern where they are present. Instead of currently, where you have to duplicate the pattern into My Patterns first - which means the original pattern is in the way.


100+

**Comment by glendaviesnz** [comment]
> I'd like them to work just like template parts, where you can edit it and the pattern is yours. Perhaps you can reset them (just like template parts).

@richtabor I have added [an issue](https://github.com/WordPress/gutenberg/issues/55911) for this specific use case.

**Comment by richtabor** [comment]
@annezazu are we good to close this, to focus on this front? https://github.com/WordPress/gutenberg/issues/55911

**Comment by annezazu** [comment]
Hmmm that works.
