### ISSUE TITLE
Form block: Typo in sidebar text

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#55464]
### Description

In the sidebar, with the Submissions Method set to Custom, the following text has a typo:

_Select the method to use for form submissions. Additional options for the "custom" mode can be found in the **"Andvanced"** section._

It should be:

_Select the method to use for form submissions. Additional options for the "custom" mode can be found in the **"Advanced"** section._

### Step-by-step reproduction instructions

1. Activate Gutenberg > Experiments > Form and input blocks.
2. Go to page editor and add a Form.
3. Set Submissions Method in sidebar to Custom.
4. View typo.

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/486261/b63a52aa-259c-4081-8d39-9df92a1f1b4a)

### Environment info

WordPress 6.3.2, Gutenberg 16.9.0-rc.1 activated.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
I'll fix this real quick. Thanks for creating the issue.
