### ISSUE TITLE
Drag & Drop: Not possible to move block at the very end

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#55474]
### Description

Currently it's not possible to move a block at the end of the list by using drag and drop only.
I'd expect it to drag it anywhere on the blank space at the bottom at the page and an inserter appears to indicate me that it can be dropped to be the last element in the list.

Currently you must drag the block up and then use the arrow to reorder.

### Step-by-step reproduction instructions

1. Have, for example, two groups and one block within
2. Try to move the block at the end only by using drag and drop

or
1. Have a block in a group
2. Try to move it out of the block, aka at the end of the list, by only using drag and drop.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/17861443/b0832fc3-8e13-4ef9-8812-9ef822b17bac

### Environment info

- WP 6.3.1
- GB 16.8.0

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by skorasaurus** [comment]
Thanks for reporting; 
Can confirm; I've encountered this for a while, thought there was an existing issue for this, searched and couldn't find one.

**Comment by annezazu** [comment]
Adding this to the writing experience for consideration: https://github.com/WordPress/gutenberg/issues/53305

**Comment by andrewserong** [comment]
Resolved in #56070
