### ISSUE TITLE
Global Styles Revisions: revision history overview is difficult to access

### ISSUE THREAD

**Issue by HeikoMamerow** [WordPress/gutenberg#55486]
## What problem does this address?
The revision history overview is difficult to access. The history is only accessible via an unnecessary intermediate step.

By clicking on the ![image](https://github.com/WordPress/gutenberg/assets/1729487/2762dd5f-7801-4367-8b4b-7e8df6f76a7d) button this unnecessary overview appears:
![Gutenberg-revisions-step1](https://github.com/WordPress/gutenberg/assets/1729487/b2237053-20be-4277-8f4a-fa5d826a5ced)

... You then still have to click on "Revision history" to finally see the history:
![Gutenberg-revisions-step2](https://github.com/WordPress/gutenberg/assets/1729487/87b0d105-2295-48a0-ada5-e431478c2153)

## What is your proposed solution?
By clicking on the ![image](https://github.com/WordPress/gutenberg/assets/1729487/2762dd5f-7801-4367-8b4b-7e8df6f76a7d) button, the history overview should be displayed directly.

**Comment by ramonjd** [comment]
Thanks for creating this issue.

Retaining "Reset to defaults" was a deliberate measure in https://github.com/WordPress/gutenberg/pull/51318, which consolidated these buttons to remove a bit of clutter in styles actions bar. This is despite the "Default styles" entry at the end of the revisions list.

The "Reset to defaults" in the drop down still provides quick access to reverting global styles changes, particularly where the revisions list is long and the "Default styles" revision is buried at the bottom of the list. 

Furthermore, there are plans to allow `n` revisions with pagination (See https://github.com/WordPress/gutenberg/issues/53621), so I think it might be desirable for now to retain the reset button.  

I think, however, there could be scope to use the idea in this issue and move the "Reset" button to a more prominent position in the revisions view itself. 

cc @jameskoster for thoughts

**Comment by jameskoster** [comment]
I could go either way on this one to be honest. 

Given that resetting to defaults is a fairly infrequent action(?), and that similar links (e.g. posts) take you directly to the revisions UI (where you can reset to default), I could see this button opening the revisions panel rather than a dropdown. 

This change could make the revisions button a toggle too, which would probably work a bit better than the current experience—it's a bit strange how you can open the revisions dropdown when you're already in the Revisions panel.

All that said, it would make resetting more arduous, particularly when there are multiple pages of revisions as Ramon pointed out.

I'd be interested to hear other designers thoughts on this one cc @WordPress/gutenberg-design

**Comment by ramonjd** [comment]
Thanks for the thoughts. Happy to follow up on any proposals 🙇🏻 

If the reset functionality doesn't need to be prominent, what about have a reset button somewhere on the main style panels, like at the bottom? It's bit ambiguous in relation to what we're resetting though, e.g., whether "Additional CSS" is also reset. 

<img width="302" alt="Screenshot 2023-10-25 at 2 41 12 pm" src="https://github.com/WordPress/gutenberg/assets/6458278/0bdf955a-79b9-436a-ab91-52a7abe01d8b">


> it's a bit strange how you can open the revisions dropdown when you're already in the Revisions panel.

Very true! I have a teeny PR to disable the menu item over in:

- https://github.com/WordPress/gutenberg/pull/55620

**Comment by richtabor** [comment]
> If the reset functionality doesn't need to be prominent, what about have a reset button somewhere on the main style panels, like at the bottom?

I think that's much too prominent.

**Comment by t-hamano** [comment]
Regarding the reset button location, I suggested one approach in [this comment](https://github.com/WordPress/gutenberg/pull/55620#issuecomment-1781359178).

Another approach is to move _only_ the reset button back to the ellipsis menu. And the revision button is a button that toggles the revision panel directly and does not display a popover.

![reset-to-defaults](https://github.com/WordPress/gutenberg/assets/54422211/3f989859-ed53-4887-bf40-58a9bc272f66)

**Comment by ramonjd** [comment]
I closed #55620 pending further discussion. I believe others are thinking about this in a more holistic manner cc @apeatling

**Comment by apeatling** [comment]
Tracking more holistic changes here https://github.com/WordPress/gutenberg/issues/55776

**Comment by ramonjd** [comment]
> By clicking on the image button, the history overview should be displayed directly.

I think the following PR closes this issue, no?

- https://github.com/WordPress/gutenberg/pull/56454

**Comment by t-hamano** [comment]
I also think this issue has been resolved by #56454, so I would like to close it.

Revisions can be opened and closed in one click from the Global Styles panel, and we can still access the Reset Styles menu.

https://github.com/WordPress/gutenberg/assets/54422211/1760e0d5-45bf-4ba2-90e5-a4b0f9f486cd

**Comment by apeatling** [comment]
Thanks for catching this one :+1:
