### ISSUE TITLE
Details Block: When opening one block others close?

### ISSUE THREAD

**Issue by webd-uk** [WordPress/gutenberg#55483]
## What problem does this address?
As in the editor when you edit the content of a Details Block, can there be an option to close all other Details Blocks on the front end when you open a Details Block?

## What is your proposed solution?
An option in the block settings under "Open by default" such as "Close others when opened".

**Comment by colorful-tones** [comment]
Hi @webd-uk 
I think this feature enhancement for the Details block would make it behave like an Accordion, which is a different use case and implementation altogether.

Here is an open issue around the Accordion block proposal https://github.com/WordPress/gutenberg/issues/21584

**Comment by webd-uk** [comment]
Hmm ... I'll close this issue and move over to that proposal. Although I would say that by definition, an Accordion Block is just a group of Details Blocks that perform together. And ... the new Twenty Twenty-Four theme uses these blocks exactly like that in the "FAQ" home page panel. Only they don't close when another is opened.
