### ISSUE TITLE
@wordpress/scripts lint-js not compatible with newer versions of ESLint (ESLint 9+)

### ISSUE THREAD

**Issue by ethanscorey** [WordPress/gutenberg#55499]
### Description

The `lint-js` script in the `@wordpress/scripts` package does not work properly with the new ESLint configuration file format (I tested on 8.51.0, but it likely affects older versions as well). It appears that `lint-js` is passing obsolete CLI arguments to ESLint, causing the errors.

For example, if you run it without specifying the `--config` parameter, you get `Invalid option '--eslintrc' - perhaps you meant '--ignore'?`

If you try to resolve the error by adding the `--config` param, you get this error instead: `Invalid option '--ext' - perhaps you meant '-c'?`

### Step-by-step reproduction instructions

1. Create a new directory.
2. Run `npm init` and `npm install '@wordpress/scripts' --save-dev
3. Create a `eslint.config.js` file with any valid config options.
4. Run `npx wp-scripts lint-js`
5. Run `npx wp-scripts lint-js --config eslint.config.js`

### Environment info

Device: Arch Linux with kernel version Linux 6.5.3-zen1-1-zen

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
It looks like the code doesn't detect the new config format introduced recently, as I don't see `eslint.config.js` listed:

https://github.com/WordPress/gutenberg/blob/11df44a7aa2d705958e740cabbd0865798fdc2ec/packages/scripts/scripts/lint-js.js#L23-L33

Another question that might be related here is whether we want to start using the new config format introduced in [v8.21.0](https://eslint.org/blog/2022/08/eslint-v8.21.0-released/) as the default config:

https://github.com/WordPress/gutenberg/blob/11df44a7aa2d705958e740cabbd0865798fdc2ec/packages/scripts/scripts/lint-js.js#L35-L40

**Comment by Utsav-Ladani** [comment]
Hi @gziolo

I tested this bug, and here are my findings:

- The new `eslint` supports the `eslint.config.js` file called `flat config`. 
- In the environment variable, we can deactivate/activate it using `ESLINT_USE_FLAT_CONFIG`.
- The `--config` is still a valid parameter (not working here).
- But the `ext` is not a valid parameter. Instead, we can specify the extension names in the `files` property in the `eslint.config.js` file as an array.
- Same for the `--ignore-path` parameter. We can use the `ignores` property for that.

I have two solutions in my mind:
1. **Dual Eslint Version Support**: Add support for both eslint versions by adding the version check condition
2. **Single Version Focus with Upcoming Release**: Release the new package version with only the latest eslint support, as the `flat config` will be the default option in the upcoming `eslint v9.0.0`.

Please let me know, as I am a newbie to this package management system and may need a different approach.

**Comment by swissspidy** [comment]
Forcing everyone to use ESLint 9, even if done in a new major release, is going to be very painful. I suggest supporting both versions as long as possible, maybe with versions checks or by leveraging `peerDependencies` or something.

**Comment by colorful-tones** [comment]
I think I'm encountering issues that are related to this, but not entirely certain. I've been trying to get ESLint operational in VS Code. I have ESLint extension activated, but I'm seeing issues with Gutenberg's configuration:

```
[Info  - 12:08:33 PM] ESLint server is starting.
[Info  - 12:08:33 PM] ESLint server running in node v20.11.0
[Info  - 12:08:33 PM] ESLint server is running.
[Info  - 12:08:34 PM] ESLint library loaded from: /Users/user/Sites/gutenberg-trunk/app/public/wp-content/plugins/gutenberg-trunk/node_modules/eslint/lib/api.js
[Error - 12:08:34 PM] An unexpected error occurred:
[Error - 12:08:34 PM] Error: ESLint configuration in plugins/gutenberg-trunk/.eslintrc.js is invalid:
	- Property "overrides[9].files" is the wrong type (expected string but got `[]`).
	- "overrides[9].files" should NOT have fewer than 1 items. Value: [].
	- "overrides[9].files" should match exactly one schema in oneOf. Value: [].
```

There is more, but I'm truncating it there

**Comment by swissspidy** [comment]
@colorful-tones I think that's unrelated.

The ninth `overrides.files` entry is this:

https://github.com/WordPress/gutenberg/blob/9cc96a7b81cc186e1ec67c40c89583aae0b334f4/.eslintrc.js#L339

For some reason `typedFiles` is empty in your project.

https://github.com/WordPress/gutenberg/blob/9cc96a7b81cc186e1ec67c40c89583aae0b334f4/.eslintrc.js#L34-L37

**Comment by colorful-tones** [comment]
Great spot there @swissspidy!

I would think running `npm run clean:package-types`
https://github.com/WordPress/gutenberg/blob/41c80e8551294914681b060caded03cfe563c6b6/package.json#L275

and `npm run build:package-types` would solve this issue of not having any tsc files?

https://github.com/WordPress/gutenberg/blob/41c80e8551294914681b060caded03cfe563c6b6/package.json#L271

But it does not and I see TypeScript issues in console when attempting to lint, e.g. `npm run lint:js -c packages/editor/src/autosave-monitor/index.js`

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.3.5 <5.2.0

YOUR TYPESCRIPT VERSION: 5.4.5

Please only submit bug reports when using the officially supported version.

=============
```

However, this is all likely not related to this main issue. It does seem like ESLint could use some attention in Gutenberg though, as there are quite a few issues that are overlapping (or seems so) with mine. https://github.com/WordPress/gutenberg/issues/54305, and the other [231 other results](https://github.com/search?q=repo%3AWordPress%2Fgutenberg+eslint&type=issues).

Anyways, not related and please disregard. Thanks!

**Comment by swissspidy** [comment]
Closing in favor of #64782 which has an active PR.

**Comment by getdave** [comment]
I also see this and unsure how to resolve

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.3.5 <5.2.0

YOUR TYPESCRIPT VERSION: 5.4.5

Please only submit bug reports when using the officially supported version.

=============

```

**Comment by swissspidy** [comment]
That is unrelated. TypeScript releases newer versions faster than `@typescript-eslint/typescript-estree` can verify compatibility. In 99% of cases this doesn't cause any issue and the warning can be hidden too because of this.  Just update TypeScript ESLint & TypeScript to a supported combo and you're good to go. Easiest to simply update both to the latest :-)
