### ISSUE TITLE
Document new "transformer" feature of create-block  in the package docs

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#55535]
As per https://github.com/WordPress/gutenberg/issues/55421, this new feature should be documented at https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/

**Comment by gziolo** [comment]
@juanmaguitar or @ryanwelcher, are you actively working on it? It looks like something that could be labelled with `Good First Issue` with some more details included about the expectations.

**Comment by juanmaguitar** [comment]
Closed as per https://github.com/WordPress/gutenberg/pull/60445
