### ISSUE TITLE
ColorPicker with "enableAlpha" true jumps unexpectedly

### ISSUE THREAD

**Issue by arl1nd** [WordPress/gutenberg#55544]
### Description

While playing with ColorPicker component in Storybook I've noticed a strange bug with ColorPicker when enableAlpha is on:

https://wordpress.github.io/gutenberg/?path=/docs/components-colorpicker--docs

While dragging the color picker to left or bottom edge it starts to interact weirdly and if you go beyond the container while it is dragged it resets hue indicator.

Note: If alpha is not 100% then there are no issues!

### Step-by-step reproduction instructions

1. Insert ColorPicker component
2. Set enableAlpha=true
3. Simply put this onChange event: onChange={ color => setColor( color ) }
4. Start dragging to the left or bottom edge of the Color Picker while having hue set in the middle or somewhere else

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1434831/945ce7a5-0a83-4068-996b-1478b65b83f8

### Environment info

- WP 6.3.2
- Gutenberg 16.8.1
- Chrome 117.0.5938.149
- MacOS Sonoma 14.0 (23A344)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @arl1nd,

Thanks for the report. I believe this issue is the same as the issue reported in #47504, so I will close it.

**Comment by arl1nd** [comment]
Thanks @t-hamano 

Sorry for duplicate, I've checked but was not able to find it.
