### ISSUE TITLE
[WordPress 6.4.RC1][Site Editor] When specifying padding for top and bottom, the unit is changed from rem to px the moment dot is typed in the numeric field

### ISSUE THREAD

**Issue by stein2nd** [WordPress/gutenberg#55559]
### Description

When specifying padding for top and bottom, the unit is changed from rem to px the moment dot is typed in the numeric field, even though rem is specified as the unit.
When using a slider to specify padding, it is possible to specify something like "0.25 rem" (It takes a lot of time and effort).

For example, immediately after entering "0.25", the numeric value is forced to change to "0" at the moment the unit is changed from px to rem.
It is possible to avoid this problem by changing the unit to "rem" first, then entering "14" in the number field, and finally adding "dot" to make it "1.4", but the operation seems physiologically strange.

The same problem does not occur when specifying left and right padding.

### Step-by-step reproduction instructions

1. Enter the "Header" template edit mode in the "Site Editor".
2. Try to change the top and bottom padding of the appropriate group.

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/531628/4b721419-736f-4e34-bf00-752d0109fe8a)

### Environment info

- WordPress: 6.4 RC1
- Theme: Twenty Twenty-Four v.1.0
- Plugins: "Create Block Theme v.1.13.2", "WordPress Beta Tester v.3.5.5"

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by hanneslsm** [comment]
Related (/same?): https://github.com/WordPress/gutenberg/issues/51616

**Comment by mikachan** [comment]
> Related (/same?): https://github.com/WordPress/gutenberg/issues/51616

Yes, I believe this is the same as the issue in https://github.com/WordPress/gutenberg/issues/51616. I'm going to close this, but please re-open if this is a different issue.
