### ISSUE TITLE
Discussion: Declarative vs Procedural theme settings

### ISSUE THREAD

**Issue by folletto** [WordPress/gutenberg#5556]
I just had a short-circuit realizing one of the major issues we had in the past work on theme showcase and a lot of other work we did in automation and processing themes: themes tend to use a _procedural_ approach to declare what they do.

In `functions.php` there's a lot of code that is used to process results. For example:

```
add_theme_support( 'post-thumbnails' ); 
```

Or:

```
function register_my_menus() {
  register_nav_menus(
    array(
      'header-menu' => __( 'Header Menu' ),
      'extra-menu' => __( 'Extra Menu' )
    )
  );
}
add_action( 'init', 'register_my_menus' );
```

This has major benefits in terms of flexibility, but also creates a major issue when the theme has to be statically processed: since all of these contents are dynamically evaluated, we don't know the results until the theme is fully loaded. This means that even for the most basic question such as "how do menus behave in X themes?" is impossible to be answered unless the full WordPress is loaded, each theme is loaded, and its output parsed.

Compare instead to doing the same of the above in an hypothetical _declarative_ approach (I'm using on purpose a weird syntax because this discussion is about the concept not the technical implementation):

```
post-thumbnails=true;
nav-menus=header-menu,extra-menu;
```

The above has major benefits: while it restricts a bit the flexibility of not being calculated live, it's now suddenly a file that can be **parsed, reviewed, and even built in a deterministic way**.

Gutenberg so far has been reusing the same existing syntax to preserve backward compatibility and avoid introducing another change, for example [colors](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/):

```
function mytheme_setup_theme_supported_features() {
    add_theme_support( 'editor-color-palette',
        '#a156b4',
        '#d0a5db',
        '#eee',
        '#444'
    );
}
add_action( 'after_setup_theme', 'mytheme_setup_theme_supported_features' );
```

Which could be:

```
editor-color-palette=#a156b4,#d0a5db,#eee,#444;
```

I'd like to raise this point to see if we can use the Gutenberg merge to introduce a "new" way to configure themes that instead leverages as default a _declarative_ approach (which, sure, can still be procedurally overridden, WordPress is still WordPress) which would have some solid upsides:

1. The theme can be deterministically processed instead of not being defined until running — major advantage in theme browsers, including WordPress itself.
2. The theme configuration can be created and edited with a builder tool — some benefit for automation scripts and some kinds of theme builders.

Given Gutenberg is creating a new syntax for the next 10 years of WordPress, maybe we want to enable also a different way for themes to be discovered, filtered, configured, in the next 10 years too.

---

_I intend this thread more of a reflection, to be discussed, I'm ok even if the answer is "no", I just want to be sure it gets discussed as it's a topic that analyzes the themes from a long-term view._

**Comment by davidakennedy** [comment]
I like this idea a lot. especially as more of WordPress core becomes driven by JavaScript.

Another advantage I can see too: Theme tags can be generated automatically off a file like this.

**Comment by jasmussen** [comment]
I really love this.

And as I close it in a second, please don't take that as anything but a bit of repository management, I'm going to close this ticket and file it in the "Ideas" project so we can revisit this in the future: https://github.com/WordPress/gutenberg/projects/8 — because we're not likely to get to this as part of the Phase 1 Gutenberg project.
