### ISSUE TITLE
Site editor <> Post Editor gaps - WIP

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#55576]
## What problem does this address?
This is a tracking issue that aims to close the gap between the post editor and site editor as we make our way towards [unifying editors](https://github.com/WordPress/gutenberg/issues/41717).

- [ ] Page parent
- [ ] Discussion settings
- [ ] ..

**Comment by jameskoster** [comment]
Related: https://github.com/WordPress/gutenberg/issues/52632

**Comment by SaxonF** [comment]
Ah, thanks @jameskoster . Closing this one out.
