### ISSUE TITLE
Styles: when viewing revisions, allow for the option to view with Style Book

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#55577]
Right now, when you are viewing revisions, you're unable to also use the Style Book:

https://github.com/WordPress/gutenberg/assets/26996883/d6185378-7b0f-495a-aafa-7b70ec59da45

Considering some of the style changes may not be visible in the template itself, it feels wise to be able to switch between both views.

**Comment by pablohoneyhoney** [comment]
I wonder if it needs to be default, opening revisions triggers the stylebook as default view. Which surfaces the issue of seeing already the stylebook icon (would it be toggle on? would two icons toggled on be weird?). 

The other thought is: when opening revisions, it opens up stylebook side by side, so you can see current vs. revised. 

cc @beafialho as we are refining the stylebook view.

**Comment by ramonjd** [comment]
I did some experimenting with this today, where the style book is loaded _instead_ of the current template.

Basically hijacking the Style Book and injecting user config into it:

https://github.com/WordPress/gutenberg/assets/6458278/3e6fb24b-f45a-45cb-b8c4-8eca749ef4bf

> Which surfaces the issue of seeing already the stylebook icon (would it be toggle on? would two icons toggled on be weird?).

Assuming we'd like to offer the user the choice to view the current template OR the style book, which sounds highly reasonable, I think this idea is worth trying out. 

I was thinking that, only when the revisions panel is open, it'd be possible to toggle the style book on and off. The style book could have a different visual to indicate it's "active" but not in 100% style book mode:

<img width="434" alt="Screenshot 2023-12-05 at 2 19 09 pm" src="https://github.com/WordPress/gutenberg/assets/6458278/8ceec978-1e60-4d44-9ebb-7fac9c34f8ce">

To toggle back to the style book, the user would have to close revisions.

The risk is that all the button toggling becomes complex in both code and UX 🤔

**Comment by andrewserong** [comment]
That mockup does look cool!

> The risk is that all the button toggling becomes complex in both code and UX 🤔

Yeah, that'd be my main concern. You wouldn't want someone getting stuck with their toggles in a strange configuration, but I do kinda like the idea that the Revisions and Style Book toggles are _kind of_ independent of one another. I suppose the main difference is that we're happy for folks to navigate around global styles (block level, etc) with the Style Book open, but we wouldn't want users to do this with a different revision active.

All sounds worth playing around with to me!

**Comment by ramonjd** [comment]
Latest update in https://github.com/WordPress/gutenberg/pull/56800 - looking at a toggle button somewhere at the moment.


https://github.com/WordPress/gutenberg/assets/6458278/40e89561-8843-40da-98a2-73390a6a4d96
