### ISSUE TITLE
Reduce complexity of detach control in template parts

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#55601]
I propose we remove the additional context within the template part “detach” functionality, as it’s not necessary and reduces the scan-ability of the list quite a bit.  The one word, action-oriented, deliberate language helps to introduce key ideas, while the longer, more complicated text is more confusing than necessary — that, and we don't include that extraneous context elsewhere. 

"Detach blocks from template part" would be "Detach". 

![CleanShot 2023-10-25 at 11 21 05](https://github.com/WordPress/gutenberg/assets/1813435/131bf4b6-882a-4e3a-b19f-a169bbe82fc8)

**Comment by JorgeVilchez95** [comment]
I have created a PR for this issue - 55870
