### ISSUE TITLE
Details block: Add transform from paragraph

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#55602]
I expected to be able to transform a paragraph into the inner contents of a details block. That way I wouldn’t have to copy and paste, then delete empty paragraph blocks. 
￼
![CleanShot 2023-10-25 at 10 21 52](https://github.com/WordPress/gutenberg/assets/1813435/fb417e81-9123-420c-b84b-5b04abb74666)

**Comment by fjorgemota** [comment]
FYI, I started working on this issue. I'll send a PR soon. :)
