### ISSUE TITLE
List View: "Rename" item is not displayed when no block is selected

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#55612]
### Description

In the List View, you can rename the block from the ellipsis menu. However, for some reason only the "Rename" item doesn't seem to display unless a block is selected.

This issue does not occur in WordPress 6.4 RC2, where only group blocks can be renamed. You should be able to reproduce it when you enable the latest Gutenberg trunk.

### Step-by-step reproduction instructions

- Insert some blocks.
- Open the List View.
- **With no blocks selected**, click the ellipsis button for one of the blocks.
- There should be no "Rename" item.
- Select that block.
- There should be a "Rename" item.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/972ef5d5-3018-44d2-9fd4-9b3624a98b1d

### Environment info

- WordPress Version: 6.4 RC2
- Latest Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I discovered that this issue was caused by [#55250](https://github.com/WordPress/gutenberg/pull/55250/files#diff-b5efc776494e2178d4d575548fb1d3c6326d23fa4291216d69df43350315421cR198) to fix a performance regression. However, I personally find it unnatural that only the Rename menu is not displayed when no block is selected.

**Comment by getdave** [comment]
Noting that this Issue will be resolved once we complete the steps in https://github.com/WordPress/gutenberg/pull/55604#issuecomment-1779632656

**Comment by t-hamano** [comment]
The latest trunk does not reproduce this problem. I believe it's because #56386 was merged. Therefore, I would like to close this issue.
