### ISSUE TITLE
Data views: Expanding quick-actions for Pages

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#55628]
<img width="1110" alt="page quick actions" src="https://github.com/WordPress/gutenberg/assets/846565/28579e91-d2a2-4c82-b756-d8ce650c41e3">

https://github.com/WordPress/gutenberg/pull/55488 enables 'quick actions' in data views. For pages this initially includes primary actions; View, Trash, and the secondary actions: Edit and View revisions. 

We can expand upon this by adding:

- [ ] **Edit Title** – opens a modal similar to renaming a template or pattern
- [ ] **Edit slug** – opens a modal with contents similar to the slug editing popover in the post editor
- [ ] **Edit status** – opens a flyout with status options
- [ ] **Edit author** – opens a flyout with scrollable & searchable list of authors
- [ ] **Edit publish date** - opens a modal with a datepicker like in the post editor
- [ ] **Disable/Enable comments**
- [ ] **Swap template** – opens the same modal you find when editing a page in the site editor
- [ ] **Edit visibility** – opens a modal with a similar UI to the 'Visibility' popover in the post editor
- [ ] **Edit page parent** – opens a flyout with scrollable & searchable list of pages

I suspect much of the design work can occur alongside PR's. But if there's anything we need to dive deeper on before work begins let me know @ntsekouras.

It's also worth noting that the modals here could also potentially be opened when clicking values in table views (https://github.com/WordPress/gutenberg/issues/55101), and when performing bulk actions (https://github.com/WordPress/gutenberg/issues/55098).

cc @WordPress/gutenberg-design for further feedback.

**Comment by jasmussen** [comment]
An immediate thought is that this is a lot of repeated instances of the word "Edit". A more expanded question is whether we can bunch these together as a single, or a few, grouped quick-edit instances. "Edit properties" or "Edit details", something in that vein.

**Comment by jameskoster** [comment]
We could probably omit the repetitive 'Edit...' prefix 👍 The argument to keep each action separate is that they can all be invoked from different flows, e.g.: clicking the values in the table row (inline editing), or bulk actions. Some (like swapping the template) can be invoked from the main document inspector in edit mode too. So it's a case of reusing as much as possible to establish consistency across.

That said, grouping could potentially work similar to wp-admin (albeit with a more considered design). IE a single "Quick edit" action that opens a modal containing all the document meta.

Alternatively the quick actions menu itself might be organised to make use of flyouts. I'll try a couple of mockups.

**Comment by jameskoster** [comment]
Here's a version that groups some options together and utilises flyouts:

<img width="1542" alt="page quick actions" src="https://github.com/WordPress/gutenberg/assets/846565/50db284f-88dc-474c-bcdf-752ca31e0d07">

This feels like a contextual menu and works well imo. The same menu could be revealed when right-clicking a row.

---

Here's a mockup encapsulating all quick-edit options in a modal, similar to editor preferences:

<img width="1841" alt="modal" src="https://github.com/WordPress/gutenberg/assets/846565/4409ac71-aff8-4b76-891f-b1ef9ac52695">

The modal approach provides much more room for manoeuvre per section, but I'm not sure they really need it. The flows that require a modal (changing publish date, template, etc.) would make use of one regardless.

**Comment by paaljoachim** [comment]
This looks real interesting James!

**Comment by jasmussen** [comment]
Might work. Some of the answers might present themselves as we explore in a PR, but I just wonder if in some cases, a single modal opening from the menu, rather than navigating the dropdown, is easier.

**Comment by jameskoster** [comment]
I have a slight preference for discrete flows per action because it's more lightweight / reusable. But totally open to trying both approaches in a PR 👍

**Comment by ntsekouras** [comment]
This issue is really connected to inline editing of fields, and should be addressed probably when we implement that. The goal is to define descriptions for fields, which will generate the editing of them.

**Comment by jameskoster** [comment]
Yes there is considerable overlap. The same UI can theoretically be used for both inline-edits, and quick actions, e.g.:

<img width="1542" alt="reuse" src="https://github.com/WordPress/gutenberg/assets/846565/3d473c16-8dbd-40a8-917f-56a8ee768fa5">

**Comment by jameskoster** [comment]
I think the recent Inspector work may influence the direction here. Closing for now, easy to re-open if required.
