### ISSUE TITLE
Patterns: Why is viewport width specified in pixels?

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#55632]
I guess this is more a question than an issue. Eventually it's a feature request.

When creating patterns, it's possible to add the width, like so:
```
<?php
/**
 * Title: CTA Contact Us 
 * Slug: prolooks/CTA-contact-us
 * Categories: call-to-action, contact
 * Viewport Width: 1280
 */
?>
```

Was there a reason why the viewport width was specified in pixels, and not with `none / content`, `wide` or `full-width`? Additionally, why not specifying the unit, like `1280px`?

**Comment by talldan** [comment]
I think the width is just for displaying the preview of the pattern at a good scale, it doesn't affect how the block works when inserted. Docs seem to confirm that - https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/#register_block_pattern.

You should be able to make a pattern wide/full by adjusting the container block's alignment (e.g. if you have a group in your pattern as the top-level block, you can change that group's alignment).

**Comment by richtabor** [comment]
Correct, it just helps adjust the viewport of the pattern within the block previews. Some patterns are larger (like full page patterns) which are nice to see a bit zoomed out. In those cases I'd suggest using a viewport width that is a bit larger. Whereas other patterns that are smaller in nature, which may be more meaningful if viewed a bit more zoomed in. 

We used this quite a bit in [TT4](https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/page-home-portfolio.php#L9). 

The content, wide, full width value should come from the content within the pattern, not the pattern itself.
