### ISSUE TITLE
Add Embed support for Spotify URLs from podcasters.spotify.com, or disallow fully

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#55633]
## What problem does this address?

This may be something that needs to be addressed on Spotify's side, but I can't quite tell.

Spotify offers embed links/code in their service https://podcasters.spotify.com/ . These links currently fail to embed in WordPress in most browsers, though Safari seems to bypass the API errors that occur.

Tested with
- WP 6.3.2
- Gutenberg 16.9.0

**Firefox 118.0.2**
![Markup on 2023-10-25 at 12:00:53](https://github.com/WordPress/gutenberg/assets/27249804/45db7d26-4a6b-4b9f-a7ce-d5c98f834ec8)

**Safari 17.0**
![Markup on 2023-10-25 at 12:07:38](https://github.com/WordPress/gutenberg/assets/27249804/dba2d84f-6d10-49c4-9f5a-ac1a2bd18363)

## What is your proposed solution?

If possible, adding support for embed links from `podcasters.spotify.com`. Alternatively, disallowing embedding these URLs altogether could help clear up confusion (as right now, they appear to embed but then fail in most browsers).

**Comment by jessedyck** [comment]
@cuemarie is this issue still occurring for you? It was for me last week, but as of today it is not. This makes me suspect it was a Spotify issue after all. I tested on my existing 6.3.2 site, and a new 6.4.1 site - all working!

**Comment by cuemarie** [comment]
Hi @jessedyck ! Same for me, I am now able to see both embedded files in Firefox, Chrome, and Safari. Looks like it was probably fixed! 🎉

**Comment by jordesign** [comment]
With this being seemingly resolved, I'll close the issue. If it does start to happen again we can always re-open it for further investigation.
