### ISSUE TITLE
Spacing: Spacing Sizes are added

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#55636]
### Description

Spacing sizes are getting added to the list, even though I have defined different ones in my theme.
This seems to happen to any theme that does not have `1`, `2`, `3`… defined as spacing size.

### Step-by-step reproduction instructions

1. Select a theme with custom spacing sizes
2. Wonder where the new spacing sizes are coming from

### Screenshots, screen recording, code snippet

<img width="254" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/d6edc40a-4dc7-4158-b8cb-323017f26daf">

### Environment info

- WP  6.4-RC2
- GB 16.9.0

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by hanneslsm** [comment]
i thought maybe i could get around the problem by using 1,2,3... as a slug, but that doesn't change anything either.
<img width="374" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/5cdb9588-dfdb-4a5e-99ab-c182aa34f286">

Edit: Just saw that TT4 used `10` as a slug for `1`. The bug still exists with 10 as slug.

**Comment by bgardner** [comment]
I can confirm this is happening. My Powder theme sets Spacing presets (xSmall, Small, Medium, Large, xLarge) with the following, but numbers are being added per the video below. The slider no longer exists, rather a drop down menu.

```
"spacing": {
	"spacingSizes": [
		{
			"name": "xSmall",
			"size": "20px",
			"slug": "x-small"
		},
		{
			"name": "Small",
			"size": "clamp(30px, 4vw, 40px)",
			"slug": "small"
		},
		{
			"name": "Medium",
			"size": "clamp(40px, 6vw, 60px)",
			"slug": "medium"
		},
		{
			"name": "Large",
			"size": "clamp(50px, 8vw, 80px)",
			"slug": "large"
		},
		{
			"name": "xLarge",
			"size": "clamp(60px, 10vw, 100px)",
			"slug": "x-large"
		}
	],
	"units": [ "%", "px", "em", "rem", "vh", "vw" ]
}
```

https://github.com/WordPress/gutenberg/assets/486261/084b6006-f6e6-4d5e-bde1-87667b979329

**Comment by carolinan** [comment]
From the screenshot of theme.json, It does not look like you have disabled the default sizes by adding
```
			"spacingScale": {
				"steps": 0
			},
```

Do I understand correctly that you are experiencing that this is a change from previous WP or Gutenberg versions?

**Comment by hanneslsm** [comment]
Thanks @carolinan - this has solved the issue!

> Do I understand correctly that you are experiencing that this is a change from previous WP or Gutenberg versions?

Yes, defining the spacingScale was not necessary in previous versions. I leave this issue open to clarify if this is intended or a bug.

**Comment by carolinan** [comment]
I would expect the disabling to use the same format as colors:
```
			"defaultDuotone": false,
			"defaultPalette": false,
			"defaultGradients": false,
```

**Comment by bgardner** [comment]
@carolinan Thanks for calling that out. I’ll have to go back to my commits in Powder because I swear I had that code in my theme.json file. Nonetheless, I have added it to the theme and no longer am experiencing the issue.

**Comment by dabowman** [comment]
Just bumping this. I noticed the same thing. a boolean to toggle off the default spacing scale would be excellent. maybe `settings.spacing.defaultScale` to follow the pattern from the color object.

**Comment by AlchemyUnited** [comment]
Not to get off-topic but I've been digging around in:
`
wp-includes / class-wp-theme-json.php / WP_Theme_JSON > method: set_spacing_sizes()
`

and this code:

```

if ( ! isset( $spacing_scale['steps'] )
	|| ! is_numeric( $spacing_scale['steps'] )
	|| ! isset( $spacing_scale['mediumStep'] )
	|| ! isset( $spacing_scale['unit'] )
	|| ! isset( $spacing_scale['operator'] )
	|| ! isset( $spacing_scale['increment'] )
	|| ! isset( $spacing_scale['steps'] )
	|| ! is_numeric( $spacing_scale['increment'] )
	|| ! is_numeric( $spacing_scale['mediumStep'] )
	|| ( '+' !== $spacing_scale['operator'] && '*' !== $spacing_scale['operator'] ) ) {
	if ( ! empty( $spacing_scale ) ) {
		trigger_error( __( 'Some of the theme.json settings.spacing.spacingScale values are invalid' ), E_USER_NOTICE );
	}
	return null;
}

// If theme authors want to prevent the generation of the core spacing scale they can set their theme.json spacingScale.steps to 0.
if ( 0 === $spacing_scale['steps'] ) {
	return null;
}
```

Shouldn't the second conditional (below the comment: "If theme authors...") be above the verbose validation conditional? Why validate if the steps = 0? Something like:

```
if ( isset( $spacing_scale['steps'] ) && 0 === $spacing_scale['steps'] ) {
	return null;
}

```

That aside, with 2024, spacingScale in the theme.json is set to 0. But in the set_spacing_sizes() method,

`$this->theme_json['settings']['spacing']['spacingScale']`

dumps out as:

```
array[
  "operator" => "*"
  "increment" => 1.5
  "steps" => 0
  "mediumStep" => 1.5
  "unit" => "rem"
]
```

Where are the other value pairs - aside from 'steps' - being added? I've searched the code base for mediumStep as well as spacingScale and can't find what I presume is probably an array_merge() or similar for filling out that array. But again, why create defaults (for the optional args) if steps = 0? 

Finally, what's the best place to look to understand spacingScale and the need it aims to meet? This just says "Object:"

https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/#spacing

I'm also curious about blockGap and why its type is undefined. Why not bool? With a default of false? What's gained by dragging a null around? Wouldn't false (or true) be less ambiguous?

**Comment by carolinan** [comment]
I am no longer able to reproduce this.
When a theme adds its own spacing sizes, with or without editing the spacing scale, then the default sizes are not added.
Also see https://github.com/WordPress/gutenberg/issues/60129
