### ISSUE TITLE
Add the pattern selector to creating pages in the site editor

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#55640]
## What problem does this address?

When a user creates a page from the pages list in WP admin they get a nice modal with patterns that can be used as a starting point.

https://github.com/WordPress/gutenberg/assets/107534/31af6705-061d-437f-a4c1-82b785190631

Let's add the same behavior to the site editor as well:

https://github.com/WordPress/gutenberg/assets/107534/7047da73-9137-4b33-ab7b-efbba974591d

Ideally in the site editor we should ask for title in the same modal somwhow.

**Comment by annezazu** [comment]
Closing this out as it's a duplicate of https://github.com/WordPress/gutenberg/issues/55108
