### ISSUE TITLE
The Future Of The Sidebar

### ISSUE THREAD

**Issue by CuriousCreative** [WordPress/gutenberg#5564]
Given that widgets are likely to eventually be replaced by blocks are sidebars likely to become a thing of the past also? Or will they be repurposed as block containers / container blocks? I noticed they weren't included in the mockups of the customizer side of Gutenberg shown at loopconf.

![loopconf](https://user-images.githubusercontent.com/37296053/37283209-09819dba-25ef-11e8-8fb4-da9feed5649c.jpg)

**Comment by westonruter** [comment]
I think blocks will become available as widgets for existing/legacy themes. But going forward legacy widgets will be made available in blocks (see #4770), and in the future the “sidebar” would just be a group of nested blocks when themes are built with blocks from the ground up. See #4770.

**Comment by mtias** [comment]
Yes, with basic layout capabilities like columns or grid areas, a sidebar is just a designated area where nested blocks can be grouped. The mechanics to support that are already in place with the `layout` attribute.
