### ISSUE TITLE
Styles: Revisions Description Text

### ISSUE THREAD

**Issue by pablohoneyhoney** [WordPress/gutenberg#55648]
For clarity and guidance, I'd consider going from:

> Revisions are added to the timeline when style changes are saved.

to:

> Restore styles from an earlier version of changes that was automatically added to this timeline when new styles were saved.

or

> Restore styles from an earlier version of saved changes.

**Comment by cbravobernal** [comment]
@sacerro will work on this in WordCamp Madrid 2023 (5th of November)
