### ISSUE TITLE
Navigation: link color gets ignored

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#55644]
### Description

Defining text color of the navigation block in the theme.json is currently not possible, since it's getting overwritten by the default link color.
Putting `!important` does work, but I'd consider this as bad practise

### Step-by-step reproduction instructions

1. Define the link color of the navigation in theme.json
2. See that the colors will be getting ignored

### Screenshots, screen recording, code snippet

```
…
      "core/navigation": {
        "elements": {
          "link": {
            ":hover": {
              "typography": {
                "textDecoration": "underline"
              },
              "color": {
                "text": "var(--wp--preset--color--dark-darker) !important"
              }
            },
            "typography": {
              "textDecoration": "none"
            },
            "color": {
              "text": "var(--wp--preset--color--dark-lighter) !important"
            }
          }
        }
      }
```

### Environment info

- WP 6.4 RC2
- GB 16.9.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by carolinan** [comment]
Does it work if the style is added to the child blocks that has the actual links, not the parent navigation block?

- core/navigation-link
- core/navigation-submenu
-  core/page-list
-  core/page-list-item

**Comment by hanneslsm** [comment]
@carolinan you are my savior! Thank you! 💛
Using `core/navigation-link` has solved the issue.

**Comment by carolinan** [comment]
It does not come as a surprise that people expect that editing the navigation block > elements should work. 
When we style the child blocks, we need to style all of them if we want all links to have the same styles.

**Comment by carolinan** [comment]
@justintadlock Perhaps we can include something about this in the theme developer handbook.
