### ISSUE TITLE
Block Renaming Followups for 6.5

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#55643]
The following needs to be undertaken in the WP 6.**5** cycle.

- [x] - Backport [the refactor (bugfix) to the feature undertaken in the `wp/6.4` branch](https://github.com/WordPress/gutenberg/pull/55604#issuecomment-1779632656)
- [x] - [Make "metadata" a global block attribute](https://github.com/WordPress/gutenberg/issues/55194)
- [x] - https://github.com/WordPress/gutenberg/issues/55338
- [x] https://github.com/WordPress/gutenberg/issues/56155

_Originally posted by @getdave in https://github.com/WordPress/gutenberg/issues/54426#issuecomment-1780764881_

**Comment by adamziel** [comment]
@getdave Another one would be: If I have another block selected and I open the hamburger menu on the quote block, there’s no rename option

**Comment by getdave** [comment]
> the hamburger menu on the quote block, there’s no rename option

Thanks for the report. Can you explain where this hamburger menu is? Screenshot of video capture much appreciated.

**Comment by adamziel** [comment]
Rename option is there:

<img width="1148" alt="CleanShot 2023-11-15 at 16 23 04@2x" src="https://github.com/WordPress/gutenberg/assets/205419/2b67fdfc-790f-411e-826b-e940866766d4">

Rename option isn't there:

<img width="1109" alt="CleanShot 2023-11-15 at 16 22 57@2x" src="https://github.com/WordPress/gutenberg/assets/205419/216443d2-d005-4987-930e-1d1cb4b7e9e5">

**Comment by t-hamano** [comment]
> Another one would be: If I have another block selected and I open the hamburger menu on the quote block, there’s no rename option

This seems to be the same issue reported in #55612.

**Comment by getdave** [comment]
Thanks @adamziel. We'll need to add a test for that. I'm going to try and dedicate some time to these followups next week (cc @scruffian ).

**Comment by getdave** [comment]
I'm circling back to these task this week having been otherwise engaged last week.

**Comment by getdave** [comment]
Reopening pending merge of https://github.com/WordPress/gutenberg/issues/56155
