### ISSUE TITLE
Command Palette Error because of block transform in 6.4 RC 2

### ISSUE THREAD

**Issue by bfintal** [WordPress/gutenberg#55668]
### Description

If you have a block that has a transform from `core/paragraph` (it's not specific to only this block, happens also in `core/heading`), then you try using the command palette, it will cause the whole editor to crash.

Here's the error:

> Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### Step-by-step reproduction instructions

Using WP 6.4 RC2:

1. Edit a page
2. Enter this dummy block in the editor using the browser console:

```js
wp.blocks.registerBlockType( 'example/text', {
	title: 'text',
	edit: () => wp.element.createElement( 'div', { children: 'hello' } ),
	save: () => null,
    transforms: {
        from: [
            {
                type: 'block',
                isMultiBlock: true,
                blocks: [ 'core/paragraph' ],
                transform: () => {},
            },
        ],
    },
} )
```

The important thing with this block is that it has a transform from a `core/paragraph`.

3. Add a paragraph block in the page
4. Select the paragraph block
5. Bring up the command palette (cmd/ctrl + K, you may have to press escape since this can also bring up the link popup in the text)
6. Type anything, it will produce the error.

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/1033611/4243c3c1-019f-4346-acc6-6f3669f6829f)

Here's a screen recording **without the error**. In this video, it's just a new page, added a paragraph block and used the command palette:

https://github.com/WordPress/gutenberg/assets/1033611/322e28d4-a3da-4604-a414-093087a9615c

Here's a screen recording **with the error**. In this video, I continued from the previous video, registering the block with the transform, then used the command palette and getting the error:

https://github.com/WordPress/gutenberg/assets/1033611/f64931dc-f648-4806-af0c-68c244e93fc3

### Environment info

- WordPress 6.4 RC2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I was able to reproduce this issue as well, so I submitted #55676 to fix it.

**Comment by bfintal** [comment]
Thanks!
