### ISSUE TITLE
Make the max-width for images filterable

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#5567]
Hi,

I am just working on implementing theme styles for the Gutenberg editor and found the following issue: the images get a `max-width` of 608 px (the default width of the Gutenberg blocks). But I increased the max width of the blocks to the maximum content width of my theme, which is over 608 pixels.

Now I could overwrite the inline style via CSS and `!important` but I think it would be nicer to have the ability of filtering the `maxWidth` value that is set here: https://github.com/WordPress/gutenberg/blob/ee3a61c6038c67f3d787a868ad8f02a119d38faf/editor/components/provider/index.js#L51

The comment above the settings constant says, »You can override any default settings when calling initializeEditor«, but I have no idea how to call that again without getting an error.

I tried this:

```
wp.editPost.initializeEditor( 'editor', window._wpGutenbergPost, {'maxWidth': 800 );
```

But that does not work (I did not really expect it either).

Is there already a way to filter those default settings? If not, would it be possible to add a simple PHP filter that filters the setting’s array that is created in the `/lib/client-assets.php` (https://github.com/WordPress/gutenberg/blob/8a4d644a525c1463f469e525d5d31ad36f44e23c/lib/client-assets.php#L910) or something like that?

Thanks,
Florian

**Comment by jasmussen** [comment]
Noting that there are a number of issues related to the max-width and inline image styles per the use of the semantic `figure` element:

https://github.com/WordPress/gutenberg/pull/5706
https://github.com/WordPress/gutenberg/pull/5209
https://github.com/WordPress/gutenberg/pull/5209#issuecomment-374328167
https://github.com/WordPress/gutenberg/issues/5213
https://github.com/WordPress/gutenberg/pull/5460

**Comment by jasmussen** [comment]
Also related, https://github.com/WordPress/gutenberg/issues/5292
