### ISSUE TITLE
Template part has empty section in toolbar

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#55687]
### Description

With current Gutenberg trunk active, there is an empty section / panel in the toolbar of template parts,
between the buttons that move the block up and down and the Edit button.

### Step-by-step reproduction instructions

Activate a block theme, for example, Twenty Twenty-Four.
Go to Appearance > Editor. Click on the preview to edit the current template.
Select an existing template part or add a new. 
Confirm that there is an empty section in the toolbar.

### Screenshots, screen recording, code snippet

Actual:  there is an extra, empty section in the toolbar.
<img width="1512" alt="There is an empty section in the block toolbar" src="https://github.com/WordPress/gutenberg/assets/7422055/5e676b23-bd49-40b1-9d4f-fb26766a1fa8">

Expected: no empty panel in the toolbar.
<img width="1512" alt="Screenshot 2023-10-30 at 06 36 02" src="https://github.com/WordPress/gutenberg/assets/7422055/05b68228-28cd-47f4-bb00-5f99640905e3">

### Environment info

Only tested on WP 6.4 RC 2, with and without Gutenberg trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
My guess is that this problem occurs when there are no fills in the BlockControls' slots at all. For example, you can see this problem in a Group block or Columns block within a Group block with "
Inner blocks use content width" turned off.

![block-controls](https://github.com/WordPress/gutenberg/assets/54422211/c4ac9574-d7e2-4ff4-ba1a-a0ba488e5bda)

**Comment by Mamaduka** [comment]
I think I know what caused this regression. I will look into it later today.
