### ISSUE TITLE
List block: Support block gap

### ISSUE THREAD

**Issue by dkjensen** [WordPress/gutenberg#55702]
## What problem does this address?
Controlling the spacing / gap between list items within a list block is not currently supported. 

## What is your proposed solution?
Add support for the `blockGap` on the list block

**Comment by cbravobernal** [comment]
I just self-assigned for WordCamp Madrid Contributor's day. In case we cannot fix it. I will leave it for anyone on Monday 6th of November.

**Comment by valerogarte** [comment]
This is my first PR in WP, after spent the day at the WordCamp Madrid Contributor's day.
However, I added the functionality in the PR, but once the pull request is launched it asks me to enter a tag, but it seems I don't have permissions to do it (or i didnt see the funcionality). How can i solve this problem? @c4rl0sbr4v0 @ajitbohra

Thanks!

**Comment by cbravobernal** [comment]
Thanks for the PR! 

It was a permissions issue. You still need some more PRs done in the project to be able to assign labels to PRs. Meanwhile, feel free to ping me and I will update it asap.

Let's wait for someone to review it and keep the conversation in the PR.

Good job! 🎉

**Comment by valerogarte** [comment]
Now we just have to wait for @ajitbohra @ryanwelcher @juanmaguitar @fabiankaegy @ndiego to accept it.

Thanks!
