### ISSUE TITLE
Image block resizes image by clicking anywhere along the side (without dragging)

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#55713]
### Description

_[inspiredtaste](https://profiles.wordpress.org/inspiredtaste) originally reported this on [Trac 59621](https://core.trac.wordpress.org/ticket/59621)_

Clicking along the right and/or bottom sides of the image—without dragging—can unexpectedly set the width in the sidebar settings. When the image has a caption, accidentally clicking the bottom resizing handle is more likely because it can overlap the caption by about 11 pixels.

### Step-by-step reproduction instructions

1. Create a post.
2. Add an Image block and insert an image. Note that the Width and Height settings below Aspect Ratio in the sidebar both say "Auto" (as placeholder text).
3. Click near the bottom edge of the image, up to 11 pixels above or below, but do **not** drag the mouse. Similarly, you could click the right side (or left side, depending on the language direction and/or block alignment setting). Note that the Width setting has a value now, which could be the theme's default content width.

### Screenshots, screen recording, code snippet

`components-resizable-box__handle-bottom` can cover part of the caption area:

![clickable area of the bottom resizing handle](https://github.com/WordPress/gutenberg/assets/17100257/96c539b8-ec3c-4999-a2a7-9d6f07738a17)

In English, the side handle is on the right when no alignment is selected.

![clickable area of the right resizing handle](https://github.com/WordPress/gutenberg/assets/17100257/47340ffe-8562-417e-b05f-48660c45a93d)

In Arabic, the side handle is usually on the left.

![clickable area of the left resizing handle](https://github.com/WordPress/gutenberg/assets/17100257/e269e2da-3758-4d93-9135-0429108130b5)

### Environment info

1. Screenshots use WordPress 6.4-RC2, Twenty Twenty-Four, with no plugins activated.
2. This also happens in WordPress 6.3.2, Twenty Twenty-Three, with Gutenberg 16.9.0 as the only plugin.

Browser/OS: Firefox 119.0 on Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sabernhardt** [comment]
Reducing the clickable area for each handle to only the visible circles could help prevent mistakes.

It would also be good to increase the size of those circles to larger than 23 by 23 pixels, possibly even showing arrows inside them.

**Comment by sabernhardt** [comment]
This seems to have been fixed between WordPress 6.6 and 6.7-RC, but I did not find a related pull request.

**Comment by Mamaduka** [comment]
Thanks for the update, @sabernhardt!

The resizer received some fixes in 6.7 (#63341 and #64819); this could be the result of that. I'll close the issue.
