### ISSUE TITLE
XSS vulnerability error.

### ISSUE THREAD

**Issue by maxwell-feng** [WordPress/gutenberg#55710]
### Description

WordPress Gutenberg Plugin <= 16.9.0 is vulnerable to Cross Site Scripting [(XSS)]

Link:https://patchstack.com/database/vulnerability/gutenberg/wordpress-gutenberg-plugin-13-7-3-authenticated-stored-cross-site-scripting-xss-vulnerability?_a_id=241
Version 16.9.0

### Step-by-step reproduction instructions

try

### Environment info

Version 16.9.0
WordPress version 6.3.2

### Please confirm that you have searched existing issues in the repo.

Yes, No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aaronjorbin** [comment]
The report referenced is not a valid report and did not identify an XSS vulnerability in WordPress. As noted in the CVE, the reported payload does not execute in the context of the domain where Gutenberg is running.
