### ISSUE TITLE
Why is "Cover image" surfaced instead of just the "image" block?

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#5575]
I often add images to my posts. I click into a new block and see my choices:

![new-block](https://user-images.githubusercontent.com/617986/37311325-0ef7a248-2604-11e8-8c9a-06b5262e1951.png)

Obviously, I click the image icon. Ah, cool, it's asking me to upload an image! I can do that.

![image-upload](https://user-images.githubusercontent.com/617986/37311375-39b7b0c2-2604-11e8-8b70-4b6ab24cc965.png)

Wait, crap, this isn't a regular image block.

![not-image-block](https://user-images.githubusercontent.com/617986/37311408-5c6757a8-2604-11e8-889e-13944cdefca7.png)

I'm now left having to delete this block and figure out where the regular image block options are.

My question is, do we have data that guided our decision to surface the "cover image" block instead of the regular "image" block? Do people insert more cover images into their posts than they do regular images?

This has happened to me like 3-4 times. I know... why haven't I gotten it by now? But maybe... just maybe... the problem isn't me?  :)

Love the work everyone! Excellent product nonetheless. 

This kind of references #5516

**Comment by mapk** [comment]
Wait... I'm thinking maybe this icon in the bar is surfaced because it's one of the last blocks I used? Is that how the magic works?

**Comment by jasmussen** [comment]
> Wait... I'm thinking maybe this icon in the bar is surfaced because it's one of the last blocks I used? Is that how the magic works? Regardless, I'm confused.

Yes, that's why. #5158 could also be related.

Noting that in master, #5158 is 95% fixed (at least with regards to image blocks). Master also has a new algorithm for determining recently used blocks, which should improve things here. Finally, when #5582 gets merged in, I think this issue can be closed.
