### ISSUE TITLE
Template parts created in site editor have no className option

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#55750]
### Description

When creating a new template part in the site editor, there is no option to specify className.

Use case: Theme uses the following code to pull in Header template part in various templates (archive, page, single):

```
<!-- wp:template-part {"slug":"header","tagName":"header","className":"site-header"} /-->
```

As expected, the HTML output in source code is:

```
<header class="site-header wp-block-template-part">
```

However when creating an alternative Header template part in the site editor, the HTML output in source code is:

```
<header class="wp-block-template-part">
```

The problem arises when the .site-header class needs to be targeted, but the newly created Header template part has no way of including the .site-header class.

### Step-by-step reproduction instructions

1. Go to site editor.
2. Create new Header template part.
3. View source code.

### Environment info

WordPress 6.4 RC-2, Gutenberg active or not active.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
How about adding a class from the Advanced panel after adding the template parts?

![additional-class](https://github.com/WordPress/gutenberg/assets/54422211/fea5deaf-2467-4dbc-8698-a912355024a0)

**Comment by bgardner** [comment]
@t-hamano Oh snap. Those options didn't exist for the Template Part on the Edit Template Part screen, but are there when I navigate to an Edit Template screen and click on the part. I'll close this now as I was able to do this successfully. Many thanks!

**Comment by gyurmey2** [comment]
Hi @t-hamano 

what happened to the **Additional CSS class(es)** filed? I have Gutenberg 20.1.0 installed.

![Image](https://github.com/user-attachments/assets/8536fb73-c44c-4799-80ed-2bf497c7c6fe)

**Comment by gyurmey2** [comment]
Sorry, I was wrong. It wasn't a template page 😳
