### ISSUE TITLE
Automatically adjust the navigation block with the menu.

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#55769]
### Description

I'm using Twenty Twenty Two and this plugin: https://wordpress.org/plugins/auto-submenu/
This plugin succesfully automatically adds subpages to my menu, yet when I assign that menu to a navigation block in the header... This doesn't update. The subpages don't get added. Also, changes in the menu system don't get reflected if they don't go through the site-editor :(

### Step-by-step reproduction instructions

1. Install plugin.
2. Make a subpage and let the plugin automatically add it to the parent page in the menu
3. Notice that the main menu isn't updated on the website itself.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by colorful-tones** [comment]
@NekoJonez I would encourage you to initiate a new support conversation with the Auto Submenu plugin author(s). Here is a direct link:  https://wordpress.org/support/plugin/auto-submenu/

This Issue area is for Gutenberg and the issue you’re describing is a limitation of the plugin itself (as far as I’m understanding).

For now, I will close this out, but if you do find a specific issue with Gutenberg then feel free to reopen this and continue the conversation.
