### ISSUE TITLE
Can't keyboard navigate out of a list block

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#5576]
Unlike all other editors, when I continue to click through to get to a new block from a list block, it doesn't let me. I was using Firefox with the latest Gutenberg and WordPress versions. Watch my ridiculous gif below.

![list-click-away-2](https://user-images.githubusercontent.com/617986/37312588-dc0ce456-2608-11e8-8cfb-3b60e72dd9f8.gif)

**Comment by jeffpaul** [comment]
@mapk when you say you're "clicking" do you mean a mouse click or using keyboard navigation?

**Comment by mapk** [comment]
@jeffpaul  I was using the keyboard `return` to try and get out.  Sorry, that really wasn't all that clear.

**Comment by SuperGeniusZeb** [comment]
This issue needs to be renamed.

Also, this issue is now fixed. If you press `Enter` twice, you can exit a List block.

**Comment by rianrietveld** [comment]
This ticket can be closed, as this is not really a bug.
