### ISSUE TITLE
Style Revisions: Remove the dropdown menu

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#55779]
We currently have a dropdown menu that contains two items, it feels unnecessary and redundant considering other buttons here have no dropdown:

<img width="428" alt="Screenshot 2023-11-01 at 11 14 28 AM" src="https://github.com/WordPress/gutenberg/assets/1464705/656c7a0a-7ff5-4012-9b4a-c415b952aaaa">

<hr>
We can move all of this information into the style revisions sidebar view.

- [ ] Move the "Reset to defaults" action as a link under the intro text.
- [ ] Move the revisions count from the menu to next to the title in the sidebar
- [ ] Make sure the style revisions button is toggled on when it is selected

<hr>

Here's my suggestion for how this could look:

<img width="326" alt="Screenshot 2023-11-01 at 11 29 59 AM" src="https://github.com/WordPress/gutenberg/assets/1464705/b782cb1b-5e61-4b22-acb7-a20108ce6b0d">

**Comment by richtabor** [comment]
> Move the "Reset to defaults" action as a link under the intro text.

We could put it in the styles vertical ellipsis menu, like we do for template resetting. And use the "Reset styles" copy, which matches what the command center uses (for styles and for templates). 

![CleanShot 2023-11-01 at 16 26 48](https://github.com/WordPress/gutenberg/assets/1813435/c7acc843-7281-47eb-bf4b-41a6aff0be39)

![CleanShot 2023-11-01 at 16 28 41](https://github.com/WordPress/gutenberg/assets/1813435/2e424766-1c8a-4b55-9fdb-5af390419aba)

**Comment by richtabor** [comment]
Is there another way to get to style revisions? Wondering if we need that back arrow next to "Revisions", if the panel is toggled via the "clock" icon.

**Comment by apeatling** [comment]
The back arrow is really awkward in its current state in trunk. It takes you back to the main global styles sidebar, but you don't get there with the reverse animation. I think we can remove it. I'm not aware of other ways to get here.

**Comment by apeatling** [comment]
Should the last item "Default styles" in the revisions history also be called "Reset styles"? It's essentially the same action.

**Comment by richtabor** [comment]
> Should the last item "Default styles" in the revisions history also be called "Reset styles"? It's essentially the same action.

Good question. As everything else is a timeline event, it should probably be labeled as such too. It could be fine to have it be a time/date stamp with "{themeName} activated" even.

**Comment by richtabor** [comment]
While we're at it (though a bit off topic), I don't think we need the "Apply" button and corresponding modal at the footer. It does the saving flow, but not the full deal, like you get when you hit "Save" in the header, or in the site editor sidebar. 

If we do keep it, "Apply" should probably be "Save", and it should use the proper save modal. Though I think it'd be nice to remove the loose end, and rely on the existing save patterns (that are also stronger and less scary). 

![CleanShot 2023-11-01 at 17 02 39](https://github.com/WordPress/gutenberg/assets/1813435/32213dbe-75a9-40b2-8784-e34741165d92)
![CleanShot 2023-11-01 at 17 03 06](https://github.com/WordPress/gutenberg/assets/1813435/07d7bb51-8084-4b5e-9413-91936f9d8d81)

![CleanShot 2023-11-01 at 17 03 46](https://github.com/WordPress/gutenberg/assets/1813435/b73c0444-ac82-475c-bba4-5caefc42a3cc)

**Comment by ramonjd** [comment]
>  While we're at it (though a bit off topic), I don't think we need the "Apply" button and corresponding modal at the footer. It does the saving flow, but not the full deal, like you get when you hit "Save" in the header, or in the site editor sidebar.

Clicking on a revision item provides a preview in the revisions window only. 

The "Apply" button loads the revision into the current editor state and therefore the editor canvas, which is a separate entity and sits below the revisions window. 

This separation is important as users can preview revisions before loading them into the editor, where the change counts as a document edit. 

I'm hopeful there's an alternative UI or even different messaging that would improve the UX here. Perhaps there's a neat way to have two functions, that is, "apply without save" or "apply and save". 🤷🏻 

I'm convinced that something will become obvious as we work through the ideas in https://github.com/WordPress/gutenberg/issues/55776

> If we do keep it, "Apply" should probably be "Save", and it should use the proper save modal. Though I think it'd be nice to remove the loose end, and rely on the existing save patterns (that are also stronger and less scary).

There was some testing around immediate saving in the [initial PR](https://github.com/WordPress/gutenberg/pull/50089#issuecomment-1524766170).

The "Apply" button triggers a dirty state and therefore enables the Save button, and it also affords the user the opportunity to edit the revision changeset before committing it to save (and creating another revision entry). 

The save flow contains other dirty entities as well, such as template edits. It's why the "Restore this revision" paradigm (load and save a single, historical state) of the WordPress code diff revisions.php page is tricky to migrate. 

Another question we had in mind was, if the revisions panel did trigger a save flow, would we want the entire save flow, or limit the entities to global styles seeing as the revisions panel's explicit focus is global styles? Seems like that just complicates things. I'm not sure, but in my mind, the save flow belongs to the editor.

**Comment by ramonjd** [comment]
~~Just thinking more about this, maybe clicking "Apply" should close the revisions panel and take the user back to the editor (with the new changes applied)? Could that be an interim measure until we work out a better way?~~

Forget that, that's the way we already did it 🤦🏻 but it doesn't seem to do it all the time. I'll look into harmonizing it. 

- https://github.com/WordPress/gutenberg/pull/55881

**Comment by apeatling** [comment]
I'm working on this one 👍
