### ISSUE TITLE
Can't delete a list block

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#5578]
I added a list block to my content, then some other blocks. I am able to delete my other blocks except for my list block.  See gif below.

![delete-lists](https://user-images.githubusercontent.com/617986/37312852-f0246f62-2609-11e8-94df-ca705bb56f23.gif)

**Comment by spencerfinnell** [comment]
Testing on master? Could be https://github.com/WordPress/gutenberg/issues/5369

**Comment by jorgefilipecosta** [comment]
Hi @mapk thank you for reporting this issue. I'm now, not being able to reproduce this problem. Could you confirm if it is still happening in your tests?

**Comment by mapk** [comment]
I just tried it out on my install after upgrading recently and it works fine now. Thanks. Closing.
