### ISSUE TITLE
Inconsistent labels for resetting templates and styles

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#55788]
We use "Clear customizations" for some resetting flows ([source](https://github.com/search?q=repo%3AWordPress%2Fgutenberg%20%27clear%20customizations%27&type=code)), while "Reset {item}" for most. 

I propose we use "Reset {item}" consistently. 

### Visuals

![CleanShot 2023-11-01 at 16 29 12](https://github.com/WordPress/gutenberg/assets/1813435/b963c410-df74-4fa3-8a30-721104ae1fc1)
![CleanShot 2023-11-01 at 16 34 09](https://github.com/WordPress/gutenberg/assets/1813435/29a5249f-e362-4ea2-913e-518c7454da00)

**Comment by richtabor** [comment]
I suggested the same as part of the reset styles control in #55779.

**Comment by annezazu** [comment]
Closing this out as a duplicate of: https://github.com/WordPress/gutenberg/issues/46859
