### ISSUE TITLE
Image block: When you set "Expand on click" for an image, border radius is not maintained when expanding

### ISSUE THREAD

**Issue by shimotmk** [WordPress/gutenberg#55791]
### Description

When you set "Expand on click" for an image with a border radius, the expanded image does not have a border raduys.

### Step-by-step reproduction instructions

1. Place Image Block.
Or paste the HTML below.
```HTML
<!-- wp:image {"lightbox":{"enabled":true},"sizeSlug":"large","linkDestination":"none","style":{"border":{"width":"29px","color":"#d8613c","radius":"100px"}}} -->
<figure class="wp-block-image size-large has-custom-border"><img src="https://s.w.org/images/core/5.3/MtBlanc1.jpg" alt="" class="has-border-color" style="border-color:#d8613c;border-width:29px;border-radius:100px"/></figure>
<!-- /wp:image -->
```
2. Change the border color and border radius.
3. Setting "Expand on click".
4. Please display the page and click on the image.
5. You can confirm that the enlarged image does not have a border set.
6. Changing the aspect ratio will cause images with borders to be enlarged.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/42362903/36fdfe0a-77d5-4ae5-ba24-423594236618

### Environment info

- WordPress: 6.4-RC3
- PHP: 8.0.0
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: 8.0.0)
- Browser: Chrome 118.0.0.0 (macOS)
- Theme: Twenty Twenty-Four 1.0
- MU-Plugins: None activated
- Plugins:
  * WordPress Beta Tester 3.5.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by karthick-murugan** [comment]
@shimotmk - I think the issue resolved in the latest version. Check with the HTML that you have provided and the image border works fine. Please have a look at the following video.

https://github.com/user-attachments/assets/3349fbeb-8c28-4523-b9c5-30e09a6ff02a

**Comment by shimotmk** [comment]
@karthick-murugan
Thank you. 
I have confirmed that the problem is fixed in the current version, so I will close this issue. 
Thank you for testing.👏
