### ISSUE TITLE
Wrong imports in RichText docs

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#55831]
### Description

Imports in the RichText component point to `wp.editor` instead of `wp.block-editor` and `wp-editor` instead of `wp-block-editor`:

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/rich-text/README.md

### Step-by-step reproduction instructions

Check the file:

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/rich-text/README.md

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Soean** [comment]
I think it should be `wp.blockEditor.RichText` and `import { RichText } from '@wordpress/block-editor';`.
