### ISSUE TITLE
Patterns not working anymore as a post template

### ISSUE THREAD

**Issue by renatho** [WordPress/gutenberg#55846]
### Description

Pattern block as a post template is not working anymore on the latest versions of Gutenberg. If fires an error on the block editor load, and breaks the block.

We realized that while testing Sensei LMS plugin on WP 6.4 because some custom post types are now broken there. It's also reported in https://github.com/Automattic/sensei/issues/7262 as part of one of the Sensei post types.

### Step-by-step reproduction instructions

1. Create a new post type with a template by using the following snippet:
    ```php
    add_action( 'init', function() {
	    register_post_type(
		    'my-test',
		    [
			    'public'       => true,
			    'show_in_rest' => true,
			    'template'     => [
				    [
					    'core/pattern',
					    [ 'slug' => 'core/simple-header-with-dark-background' ],
				    ],
			    ]
		    ]
	    );
    } );
    ```
2. Create a new post of this new post type.
3. See the error in the editor.
4. Open the browser console and see the JS error.

### Screenshots, screen recording, code snippet

![Screenshot 2023-11-01 at 11 48 33](https://github.com/WordPress/gutenberg/assets/876340/4d202131-4e51-4fe3-be82-5a6ad04a714f)

### Environment info

- Tested on WP 6.4 RC2 or with Gutenberg plugin activated version 17.0.0-rc.1.
- Reproduced on Chrome and Firefox.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hellofromtonya** [comment]
6.4.0 candidate - this issue appears to be a regression or BC break, given it worked prior to 6.4. 

If the ability was removed, then it's a BC break; else, it's a regression.

Pinging 6.4 editor leads @annezazu @bph @karmatosed @mikachan @SiobhyB. 

[Also pinged in Make/Core slack's](https://wordpress.slack.com/archives/C02QB2JS7/p1699114060052179) `#core-editor` channel.

**Comment by Rajinsharwar** [comment]
Hey @hellofromtonya, this does seem to be an issue.

On WP 6.4, the issue occurs when you register any custom post with the template set to patterns. 🐞

On WP 6.3.2, the issue doesn't seem to occur even when the patterns are being used in the templates. ✅
