### ISSUE TITLE
The new Welcome Guide in the Site Editor makes some wrong assumptions and gives bad info for hybrid themes

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#55857]
### Description

I'm testing out 6.4-RC-3 with our hybrid theme (not FSE, just has a few Template Parts).

When I booted up a Template Part to edit, I was shown an "Edit your site" modal popup that is not applicable to our type of theme at all.

"Design everything on your site - from the header right down to the footer - using blocks"

Our users aren't able to do that. Template Parts just control very small bits of the site.

"Click (split circle icon) to start designing your blocks..."

We don't have that icon, again because this is just for Template Parts, not FSE.

### Step-by-step reproduction instructions

1. Load a theme that uses Template Parts, but not FSE
2. Edit a Template Part
3. See the Welcome Guide popup that would be very confusing in hybrid themes

### Environment info

WP 6.4-RC-3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mrwweb** [comment]
Confirming this issue. Hybrid theme with theme.json and template parts support on WP 6.4.1.

Here's the welcome screen:

![the template parts editor is darkened with a modal above it reading "Edit your site" with details about the site editor](https://github.com/WordPress/gutenberg/assets/1238696/3d50fba3-3716-40c8-aed7-102dae490a5f)
