### ISSUE TITLE
Restore sidebar state when resizing a window

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#5586]
This appears to be a regression per the merge of the in-progress sidebar API. 

If you have the sidebar toggled, then resize the window to be small, the sidebar is _untoggled_. This is in contrast to the previous behavior, where the sidebar _state_ was not untoggled, the editor just entred into a mobile state, where the sidebar is a modal. 

The problem is, that the sidebar should be enabled by default on a vanilla out-of-the-box WordPress install. This is key in order for users to learn that if you dismiss the sidebar by pressing the X in the top right corner of the sidebar, you can _see_ that the cog icon is untoggled in the editor bar. This teaches users how to get the sidebar back (and we can show a pointer as well). If a user simply resizes the viewport and it disappears, this connection is less likely to happen. 

![restore sidebar state on resize](https://user-images.githubusercontent.com/1204802/37339076-c7edc632-26b9-11e8-8b3e-b4a98756801f.gif)

Ideally the sidebar would be restored when you return to the desktop breakpoint, unless you explicitly toggle it off.

**Comment by jasmussen** [comment]
CC: @atimmer @IreneStr I believe you worked on the sidebar API.

**Comment by jorgefilipecosta** [comment]
As part of PR https://github.com/WordPress/gutenberg/pull/5435/, we discussed a possible improvement to the state logic that would allow the recovering of this behavior:  https://github.com/WordPress/gutenberg/pull/5435/files/4c9d517c7a719ba138c7d45da4fd83751c2a22af#diff-a7d3f572b6500e5eaddb301621f37c6c.
At the time of that refactoring, it was better not to add this logic right away as it would make the PR huge.
I can try to submit a PR that follows the logic discussed.

**Comment by jasmussen** [comment]
> At the time of that refactoring, it was better not to add this logic right away as it would make the PR huge.

It's totally okay to make tradeoffs like that when shipping new features, just wanted to make sure this was tracked so it doesn't fall between the cracks.

> I can try to submit a PR that follows the logic discussed. Of course, if another person is interested in working on this feel free to comment.

Not super urgent, but definitely something the final version should have.

**Comment by IreneStr** [comment]
It was indeed a known issue in the initial sidebar PR. I believe @jorgefilipecosta also had some ideas about simplifying the state tree that should make handling this/storing the active sidebar much easier.
