### ISSUE TITLE
Cannot import Google fonts in Gutenburg 16.9.0

### ISSUE THREAD

**Issue by Rajinsharwar** [WordPress/gutenberg#55879]
### Description

Cannot import Google Fonts in Gutenburg 16.9.0 and with theme TT4

![image](https://github.com/WordPress/gutenberg/assets/68213636/2f26c921-63a9-4a9d-ae83-a2d6e0b1d895)

Error in Console:

![image](https://github.com/WordPress/gutenberg/assets/68213636/6f079101-8016-4705-b226-0fe201d687a0)

### Step-by-step reproduction instructions

1. Make sure you have a full clean install of WP 6.4, and Gutenburg 16.9.0, and activated theme is TT4.
2. Navigate under Appearance> Editor, and click on any page. 
3. Click on the styles tab: 

![image](https://github.com/WordPress/gutenberg/assets/68213636/185ba2fc-d53a-4dad-aae2-0e575b077cc5)
4. Click Typography.
5. Click on Fonts > Install Fonts.
6. Try to import any Google Font.

### Environment info

- WordPress version 6.4-RC3
- Gutenburg version 16.9.0
- TT4 version 1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Rajinsharwar** [comment]
Confirmed with Gutenberg version 16.7.0. The issue doesn't occur there, on my same installation. 
Seeing the error response in the console, of not having proper permissions. 🤨

![image](https://github.com/WordPress/gutenberg/assets/68213636/35ba374d-dc8b-4ddf-bfbe-2911ab5d66f0)

**Comment by t-hamano** [comment]
Thanks for the report. I was able to reproduce it.

After looking back at the commits, I found that this issue was caused by #54829. I would like to continue trying to find out what is the cause.
