### ISSUE TITLE
Data views: Only display relevant options in status filter

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#55886]
Related https://github.com/WordPress/gutenberg/issues/55083

In the Pages management view _all_ post statuses appear in the Status filter dropdown. This can lead to irrelevant filter configurations, for example if you install WooCommerce you'll find order statuses as options while managing pages:

<img width="738" alt="Screenshot 2023-11-06 at 09 57 43" src="https://github.com/WordPress/gutenberg/assets/846565/31530317-4a3e-444c-a9d3-d9d951d95a99">

Some context from @oandregal:

> but the issue here seems to be that statuses are unbound: they affect all post types – see, for example, [register_post_status](https://developer.wordpress.org/reference/functions/register_post_status/). I can see how Woo may be registering some new statuses that show up there in your setup.

> The issue is that we don't know for which post type a status is registered, and we cannot simply remove the ones that are not the default from core: we'd also be removing post types that plugins intentionally added for pages, for example (editorial flow).

> The way forward may be what Jorge already suggested: allow providing statuses that are bound to a Custom Post Type.

**Comment by oandregal** [comment]
@jameskoster would you be able to share a screenshot of your wp-admin page for pages? I don't see the `trash` status in the list you share, so I wonder whether you'd see the `Trash` link at the top-right of that page:

<img width="532" alt="Captura de ecrã 2023-11-06, às 11 47 06" src="https://github.com/WordPress/gutenberg/assets/583546/d547faae-8cc5-499f-8c4e-8e00a8fc7c7c">

**Comment by jameskoster** [comment]
Yes I see Trash in the wp-admin Pages view:

<img width="457" alt="Screenshot 2023-11-06 at 12 58 53" src="https://github.com/WordPress/gutenberg/assets/846565/bc9157e6-c4b2-4b0d-83b8-3211a67a98c0">

Edit: It does seem to be related to custom statuses though. If I disable WooCommerce then Trash appears as an option:

<img width="544" alt="Screenshot 2023-11-06 at 13 01 34" src="https://github.com/WordPress/gutenberg/assets/846565/097091c3-fedd-40b7-b2e4-3be678de292e">

**Comment by oandregal** [comment]
I've discussed this issue with others, to better understand the way forward here. It seems sensible to only support the core statuses right now.

We want to support custom statuses as well. However, that has many ramifications, see https://github.com/WordPress/gutenberg/issues/3144 and https://core.trac.wordpress.org/ticket/12706 Plugins would need to migrate to this new API. It's something that would take time, and it's beyond the current scope for the dataviews project at the moment. It needs to be looked at separately.
