### ISSUE TITLE
Using selectBlock / selecting in custom block

### ISSUE THREAD

**Issue by marcusig** [WordPress/gutenberg#5589]
## Issue Overview
I'm working on a block that uses an iframe to render the content, a bit like embeds. 
The issue is **when clicking** the content of the iframe the block doesn't get selected 
(the same thing happens with media embeds). 

Is there a function / abstraction we can use to programatically select a block?

**Comment by aduth** [comment]
Related: #483 (https://github.com/WordPress/gutenberg/issues/483#issuecomment-369017880)

**Comment by aduth** [comment]
Technically this is possible by using the [`data` module](https://github.com/WordPress/gutenberg/tree/master/data) via the editor's action creators:

```js
edit: withDispatch( ( dispatch, ownProps ) => {
	const { selectBlock } = dispatch( 'core/editor' );

	return {
		selectBlock: () => selectBlock( ownProps.id );
	};
} )( ( { /* attributes, ... , */ selectBlock } ) ) => {
	return /* ... */;
} );
```

It would probably be preferable for this to be a prop passed into the `edit` component natively though.

Also, don't rely on `ownProps.id`, as this may be normalized to `uid` in a future change.

**Comment by marcusig** [comment]
Thanks. I'm going to try that. I would help to have it as a prop as you said.

**Comment by aduth** [comment]
This was not made as a prop as originally suggested, but you can now use the new `wp.components.FocusableIframe` component which will trigger a `focus` event as expected and interoperates with the block's default focus handler for selection.
