### ISSUE TITLE
TinyMCE Core: mobile support

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#559]
This will be the first drop of the new Alloy UI framework being developed in TinyMC Core. 

It is yet TBD how or if Gutenbeg will be able to pick this up, but it is worth surfacing the work.

See demo at https://www.youtube.com/watch?v=VTn47TueD3o
See notes at https://www.ephox.com/blog/tinymce-is-going-mobile/

**Comment by androb** [comment]
Updated demo video available at:
https://drive.google.com/file/d/0B9mSGhHF8gcPM1RaTzQ2TlFWM28/view?usp=sharing

**Comment by iseulde** [comment]
As we're long out of the prototype stage, and currently not using TinyMCE UI, I'm going to close this.

**Comment by EphoxJames** [comment]
This might still be relevant for the free form block.
