### ISSUE TITLE
DataViews: make "Side by side" an action of the record, not a layout

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#55903]
Related https://github.com/WordPress/gutenberg/issues/55083

I'd like to suggest converting the "Side by Side" layout into an action of the record, available for any layout (table, grid, kanban, etc.).

<img width="1506" alt="Captura de ecrã 2023-11-06, às 17 35 05" src="https://github.com/WordPress/gutenberg/assets/583546/0f01c9da-b182-45d9-a6ce-b4e7f1b0ccb9">

By doing so, we remove some duplication. Right now, "side by side" works by replicating the table view and change the behavior of clicking on the post title (instead of directly opening the editor, it would open a side frame).

My mental model for this "open in a side frame" action would be the following:

1. The side frame opens whenever the user clicks the post title (from whatever layout).
2. Upon clicking the side frame, the user is taken to the site editor.

Note this behavior mimics what we already do in the main navigation of the editor (click on the sidebar to preview, click on the frame to open the editor), so it provides a more coherent experience:

https://github.com/WordPress/gutenberg/assets/583546/771bf5fc-fbf7-41c6-bd27-abd91b31860c

**Comment by oandregal** [comment]
cc @SaxonF @jameskoster @jasmussen @youknowriad @ellatrix @mcsf @ntsekouras @jorgefilipecosta

**Comment by youknowriad** [comment]
I think the side by side view as it exists today is not the real side by side view. I suggested in the PR renaming it to "list" view and renaming the existing "list" view to "table". It's true that if you look at it at the moment it's just the table view but that's not what it's meant to be. So let's focus on updating the design first which will clarify that it's indeed a separate view.

**Comment by youknowriad** [comment]
Ok after some discussions, I think the idea is already in place technically. The "side by side" is not implemented as a view, it's a feature any view can enable but right now it's only enabled on the "list" view (we should rename the side by side one). In the future we could consider enabling for more views if the need arises

**Comment by oandregal** [comment]
Yeah. Though, I'd expect that:

- the existing side-by-side layout is [removed](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/dataviews/dataviews.js#L26), so we only have two (table & grid).
- enable the preview for the table view instead

**Comment by youknowriad** [comment]
> the existing side-by-side layout is [removed](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/dataviews/dataviews.js#L26), so we only have two (table & grid).

I think the existing side by side is to be updated to show a list (like the email list for instance) it's role is to ultimately replace the page we have under "templates" or "pages". It becomes the default view later. So while right now it's just a duplication of the "table" layout, it's not what it's meant to be.
