### ISSUE TITLE
DataViews: fix search, filter, view actions row

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#55905]
Related https://github.com/WordPress/gutenberg/issues/55083

Upon setting the items per page to more than 5, the search/filter/view action row is hidden by scrolling down:

This is problematic for filters: there's no indication of which ones are being applied at the moment. What if we fixed that row, so it's always visible?

https://github.com/WordPress/gutenberg/assets/583546/d1fd491c-640e-405c-815e-017d22d9cb7f

**Comment by oandregal** [comment]
cc @jameskoster @SaxonF @jasmussen @youknowriad @ntsekouras @jorgefilipecosta

**Comment by jameskoster** [comment]
Yup, making that row sticky seems sensible. Same goes for pagination – ideally that is always visible too.

**Comment by oandregal** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/56157
