### ISSUE TITLE
Social Icons: Add Threads icon

### ISSUE THREAD

**Issue by itsamoreh** [WordPress/gutenberg#55914]
Instagram's Threads app has been out for a few months now and has millions of daily active users. It would be great to add a Threads icon to the Social Icons block.

**Comment by mrleemon** [comment]
Is it not added already?

https://github.com/WordPress/gutenberg/pull/52685

**Comment by t-hamano** [comment]
The Threads icon was added in #52685 and will be available in WordPress 6.4. Therefore, I would like to close this issue.
