### ISSUE TITLE
FontLibrary: Error message doesn't disappear after successfull fetch of google fonts

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#55948]
### Description

In the Install fonts tab, it shows the following error message when the api data fetch fails.

"The response is not a valid JSON response."

Switching tabs, would re-fetch the json data and the error message doesn't disappear on successful fetch of the data.

### Step-by-step reproduction instructions

1. Invoke font library modal form global styles
2. Use a plugin to block the network call `/wp/v2/fonts/collections/default-font-collection` or go offline in dev tools.
3. Switch to install fonts tab
4. Observe that modal shows error message
5. Now allow the API from step 2
6. Switch to first tab and then to "install fonts" tab
7. Observe that the fonts are loaded successfully but the error message still persists.

### Screenshots, screen recording, code snippet

<img width="1512" alt="Screenshot 2023-11-07 at 7 44 31 PM" src="https://github.com/WordPress/gutenberg/assets/1935113/51ac6de9-6a4d-410b-b169-c20ce8e1c3f6">

### Environment info

- WordPress develop
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by creativecoder** [comment]
@madhusudhand I think this one may no longer be an issue--are you still seeing the problem?

**Comment by mikachan** [comment]
I believe this has been fixed, so I'm going to close it. Please re-open if necessary!
