### ISSUE TITLE
Global Styles: Always show inherited values in the inspector if we know them

### ISSUE THREAD

**Issue by michalczaplinski** [WordPress/gutenberg#55951]
Parent issue: https://github.com/WordPress/gutenberg/issues/49278

if a particular style is **inherited** (e.g. from Global Styles) the control displays that value, and the label has a purple accent denoting the global context. 

The control cannot be removed because the inherited value will be used if there's no local setting.

**Comment by jameskoster** [comment]
Should we close this? It's essentially a duplicate of https://github.com/WordPress/gutenberg/issues/37752 which was re-opened recently.

**Comment by michalczaplinski** [comment]
Makes sense @jameskoster !

Closing this one in favour of #37752
