### ISSUE TITLE
PullQuote Block default Text Alignment

### ISSUE THREAD

**Issue by pitamdey** [WordPress/gutenberg#55990]
### Description

When we add a PullQuote block it shows the left icon text alignment but the text is in the centre, 
so the alignment icon by default should also show the centre icon
Here is the attached video for better understanding :
https://drive.google.com/file/d/1V5YjhDYJwfWAeMxabK8nYrukiRQbyCkg/view?usp=sharing

### Step-by-step reproduction instructions

1. Select Pull Quotes Gutenberg Block
2. See the text alignment icon in the toolbar it is showing that the alignment is left but we can see the text is aligned centred
3. Try to change the alignment and then we can see after changing for the first time it is working fine. So we have to just replace the default icon in centre

### Screenshots, screen recording, code snippet

Here is the attached video for better understanding :
https://drive.google.com/file/d/1V5YjhDYJwfWAeMxabK8nYrukiRQbyCkg/view?usp=sharing

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting and the video. 

I understand what you're saying (thank you for the video) but this is the intended behavior. 

As shown in the screenshot below, when you create a pullquote by default, no alignment is added, in the code editor; even if the outline is around a setting in the block toolbar. 

![image](https://github.com/WordPress/gutenberg/assets/955351/dbeabe3e-a4e8-437d-8e95-c90384c19e69)

In 00:13 of your video, you'll see that although the outline there; the pullquote block does not have align-left **yet** selected: 

**A setting in the the block toolbar is only applied to the block ; this is visually communicated when the icon's background turns black** as shown in the example below.

![image](https://github.com/WordPress/gutenberg/assets/955351/18346fa8-b25b-48fa-8847-ec2cb21f3e78)


Please reopen if you need clarification.
