### ISSUE TITLE
Cover Heading Colors Aren't Reflected on Front-End

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#56006]
### Description

6.4 introduced Heading color options for container blocks, such as Cover Blocks and Group Blocks.
When used on a Cover block, these colors are reflected in the editor, but not on the front-end (tested in TT3, TT4, Frost, and our custom theme)

### Step-by-step reproduction instructions

1. Using 6.4.1 and Twenty Twenty-Three theme, create a new Page.
2. Insert a Cover Block.
3. Put a Heading Block inside the Cover Block.
4. Set the Heading Color at the Cover Block level.
5. Notice the heading color change in the Editor.
6. Publish the Page and View it.
7. Notice the heading color is not reflected on the front-end.

### Screenshots, screen recording, code snippet

![2023-11-09 11_20_37-Add New Post ‹ Latest Stable (Blank) — WordPress](https://github.com/WordPress/gutenberg/assets/945157/1047cb86-da9f-4e5e-a49a-bf3c1d868f7d)

![2023-11-09 11_20_58-Container Color Test – Latest Stable (Blank)](https://github.com/WordPress/gutenberg/assets/945157/6e957229-ec40-438d-9e7e-b7ba05447f7d)

### Environment info

- WP 6.4.1.  Twenty Twenty-Three theme (also our custom one, tested separately). No Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MadtownLems** [comment]
Doing a little more research on this: It works for Group blocks, but not for Cover blocks.

I can't make it work for Cover blocks in any theme, including TT4 or Frost.

**Comment by tellthemachines** [comment]
I can reproduce this issue; it only happens in the Cover block because it is caused by the [block styles](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/cover/style.scss#L119) overriding the generated element ones.
