### ISSUE TITLE
"Apply Styles Globally" should not be present when the Global Style Editor is not available (such as hybrid themes) and can cause permanent changes

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#56007]
### Description

When editing a Template Part of a Classic Theme that uses Template Parts, but not FSE, you are given the option to "Apply Styles Globally" when editing a block. Doing so can cause irreversible changes by setting Global Styles which cannot be undone through any interface.

For example, if I set a Paragraph Block's background color to Grey, Apply Styles Globally, and Save those changes. My paragraphs are now Grey forever.  I can repeat those steps to apply a different background color globally, but I can never completely undo the changes, because clearing the background color isn't something that can be applied globally.  I assume one could use the Site Editor to reset this global style, but we don't have access to the Global Style editor.

I don't believe that the ability to Apply Styles Globally should exist in this context (editing a Template Part of a hybrid theme). It should only be available in FSE themes.

### Step-by-step reproduction instructions

1. Use a mostly Classic Theme that supports one or more Template Parts.
2. Edit a Template Part.
3. Set the background color of a Paragraph Block, Apply Styles Globally, and Save your changes.
4. Note that all paragraphs on the site now use that background color.
5. Attempt to clear the background color and Apply Styles Globally.
6. Note that updating the template part does not let you save the changes. (You can set a DIFFERENT color, but can never clear it.)

### Environment info

Confirmed on at least WordPress 6.2.3 - 6.4.1. No Gutenberg plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I have been able to confirm by converting the TT1 theme into a hybrid theme with template parts enabled. Here is short video detailing the issue: https://d.pr/v/271eoC

Enabling template parts:

```
function add_block_template_part_support() {
    add_theme_support( 'block-template-parts' );
}
add_action( 'after_setup_theme', 'add_block_template_part_support' );
```
