### ISSUE TITLE
Consistency between example files and handbook 

### ISSUE THREAD

**Issue by Lageeek** [WordPress/gutenberg#5601]
Hi,
I posted it there, but no reaction, also with older issues, so I try it here again:

https://github.com/WordPress/gutenberg-examples/issues/20

**Comment by mtias** [comment]
I agree this is not very helpful at the moment and the example are not being maintained. There are many plans for short term improvements to the handbook that will make this a lot easier to consume and maintain. Please, stay tuned.

**Comment by beinoriusju** [comment]
Hello, I'm working on this. Tutorial provided in documentation should reflect latest "Gutenberg Examples". Its' beyond confusing for beginners.
