### ISSUE TITLE
Lightbox: Expand on click toggle control is disabled on images inserted through the block inserter sidebar

### ISSUE THREAD

**Issue by bacoords** [WordPress/gutenberg#56049]
### Description

When inserting an image from the block inserter sidebar (either Openverse or media library), the 'Expand on click' toggle is disabled at first, even though the image is not actually linked. (If you add a link and then remove it, the toggle then is enabled.)

### Step-by-step reproduction instructions

1. Open a new post
2. Open the block inserter left side panel, select Media, select Openverse or Images,
3. Select an image to insert it
4. See that the 'Expand on click' toggle is disabled.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/6867360/565653e7-8f71-4432-9568-2fe218903005

### Environment info

- WP 6.4.1, no GB plugin
- Tested on Chrome and Arc

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

CC @aurooba

**Comment by aurooba** [comment]
I'm able to reproduce this on my end on a clean install following the steps!

**Comment by sajmes** [comment]
Appears this may be happening again. Simple site: 8002908-zd-a8c

**Comment by t-hamano** [comment]
@sajmes Could you tell me which WordPress version you tested it on? I tested it with both WP 6.5 and the latest Gutenberg, but I couldn't reproduce it. By the way, this setting has been moved from the sidebar to the block toolbar.

https://github.com/WordPress/gutenberg/assets/54422211/c9ae48e9-61b1-4d87-a44d-0174110266ea
