### ISSUE TITLE
Embed placeholder breaks upon reload

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#5604]
If you insert an embed block that's empty, then reload the page, you get an error:

![embed reload](https://user-images.githubusercontent.com/1204802/37394993-719ead8e-2775-11e8-9b7d-149249403cc5.gif)

Steps to reproduce:

1. Write new post
2. Insert embed block
3. Save draft or wait for autosave to kick in
4. Reload the page

**Comment by notnownikki** [comment]
Fixed by #5624
