### ISSUE TITLE
TwentyTwentyFour theme error

### ISSUE THREAD

**Issue by sylviashe** [WordPress/gutenberg#56063]
### Description

I uploaded the Twenty twenty four theme to my wordpress.com with business plan. It worked fine yesterday, but this morning, the site itself was fine, but when in the admin panel, I couldn’t access posts, editor etc. I got a white page with the following:

There has been a critical error on this website. Please check your site admin email inbox for instructions. Which, side note, I never received.

I followed the trouble shooting guide, and switched back to twenty twenty three theme and everything  worked fine, so I thought it was the theme. On the twentytwentyfour forum, someone suggested I go ahead and deactivate all the plugins.
I didn’t initially deactivate plugins, because the troubleshooting guide says to change themes, and if it works, it’s the theme. But, I deactivated all plugins, which all I had were ones wordpress installs automatically. Then I reactivated one by one. It’s Gutenberg. All the others are fine, but Gutenberg gives the error. I’m not sure if I need Gutenberg? Right now I have it deactivated and 2024 theme is working fine.

### Step-by-step reproduction instructions

Install twentytwenty theme
activate gutenberg
try to open posts or theme editor

### Environment info

Wordpress 6.4.1
Gutenberg Version 16.9.0 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hi @sylviashe  - that definitely sounds frustrating - as this sounds like an error specific to the setup of the site on WordPress.com I'd recommend reaching out to their support team.
https://WordPress.com/support
