### ISSUE TITLE
Fully remove WP core-block-supports-inline-css styles in a theme.

### ISSUE THREAD

**Issue by aleph1** [WordPress/gutenberg#56065]
### Description

Attempting to remove the style element with id="core-block-supports-inline-css" does not seem to work with either of these pieces of code added to functions.php. Trying to dequeue the style using wp_dequeue_style in the 'wp_enqueue_scripts' or 'wp_footer' actions seems to have no effect and the CSS is still injected into the page.

### Step-by-step reproduction instructions

Add the following to a themes functions.php file.

```
add_action( 'wp_enqueue_scripts', function() {
	wp_dequeue_style('core-block-supports-inline-css');
}, 99999 );

add_action( 'wp_footer', function() {
	wp_dequeue_style('core-block-supports-inline-css');
}, 99999 );
```
Within either of the above hooks you can add the following code at the beginning of the function to see that the 'core-block-supports-inline-css'  is not included in wp_styles().

```
foreach ( wp_styles()->queue as $style ) {
	echo '<div>' . print_r($style, true) . '</div>';
}
```

### Screenshots, screen recording, code snippet

![wordpress-bug](https://github.com/WordPress/gutenberg/assets/485722/354e2b74-c188-47ea-a1bc-ad28aaee54b4)

### Environment info

WordPress 6.3.2
Gutenberg: Assuming 15.2-16.1 as per https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

The `id` attribute of the style tag and the enqueue handle name do not necessarily match. The `-inline-css` suffix is automatically added when enqueued via the `wp_add_inline_style()` function.

In other words, this CSS is added using the following code:

```php
wp_add_inline_style(
  'core-block-supports',
  // ...
)
```

The actual handle name is `core-block-supports`, so you can delete it with the code below.

```php
wp_dequeue_style( 'core-block-supports' );
```

**Comment by aleph1** [comment]
This doesn't work as expected when an instance of the WordPress gallery block is present on a page or post. Whether my functions.php includes the `wp_dequeue_style('core-block-supports')` hooked to 'wp_enqueue_scripts' or 'wp_footer' any output HTML page that includes the WordPress Gallery Block still has the CSS injected, <style id="core-block-supports-inline-css">. This is the relevant code from my functions.php:

```
add_action('wp_enqueue_scripts', function(){
	wp_dequeue_style('classic-theme-styles');
	wp_dequeue_style('global-styles');
	wp_dequeue_style('wp-block-library');	
	wp_dequeue_style('wp-block-library-theme');
	wp_dequeue_style('core-block-supports');
}, 99999);

add_action('wp_footer', function() {
	wp_dequeue_style('core-block-supports');
}, 99999);
```

It really does seem to be a bug that is triggered only when the gallery block is present on a page.

**Comment by t-hamano** [comment]
> It really does seem to be a bug that is triggered only when the gallery block is present on a page.

It might be due to hook priority. Using the code below, I confirmed that the content can be deleted correctly in the TT1 theme that has a gallery block.

```php
add_action('wp_footer', function() {
	wp_dequeue_style( 'core-block-supports');
}, 5);
```

**Comment by t-hamano** [comment]
In my testing, we should be able to completely remove the `core-block-supports-inline-cs` style by writing a suitable action hook.

@aleph1 I would like to close this issue, but if you are still having problems, please feel free to comment.
