### ISSUE TITLE
"Newly Added" block notification

### ISSUE THREAD

**Issue by joelabreo** [WordPress/gutenberg#5608]
It would be great for UX if there was a visual indicator for any new blocks added via third party addons. This would allow the user to quickly identify the new blocks available as soon as s/he activates a new plugin and clicks on the "+" icon. 

Currently, new blocks are added to the top of the pile (without any adornment) of their respective sections. For example, the "Timeline" block in the screenshot below has been newly added. 

![block-list-no-adorn](https://user-images.githubusercontent.com/20280462/37399077-9b6af998-27a6-11e8-8b86-84eb8b666259.png)

IMO it would be nice to highlight the newly added block, for, say, 24 hours, after it is added. This way, the user can quickly glance through the available blocks and have a visual indicator of the new blocks at his disposal and if s/he wants to immediately try out one of the new blocks. 

![block-list-with-adorn](https://user-images.githubusercontent.com/20280462/37399088-a05cc562-27a6-11e8-8a00-c7b1bfbbd726.png)

Not sure how technically feasible adding this (seemingly) simple functionality would be though.

**Comment by StaggerLeee** [comment]
It won't much help all Users who had websites done by outsider developer(s). 24 hours is not enough.

**Comment by joelabreo** [comment]
re: identifying "new" blocks: Agreed. I don't have a better idea to get around this. 

re: categorising blocks from a particular plugin: Looking at the the documentation of the block API and the how the search works, the user can just easily use the search feature to identify blocks from a particular plugin, provided the developer of that add-on properly uses the keywords property (ref: https://wordpress.org/gutenberg/handbook/block-api/#keywords-optional) 

Since I don't have a solution for the former and am satisfied with the latter, this issue can be closed, I think.

**Comment by karmatosed** [comment]
I would add I don't think having a new block indicator would be at all bad @joelabreo. So long as we maybe had some intelligent mechanisms for it and kept for maybe 48hours, it makes total sense for a user. Maybe we have a limit on the amount we show to avoid a cluster of notifications :)

Design wise, it's something we should explore more. My initial feelings are a red dot isn't the best indicator, what else could we consider?
