### ISSUE TITLE
When blocks are emptied in content, TinyMCE passes in an empty <br /> to the Redux State.

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#561]
When a block with an editable component is emptied, the Redux state on `UPDATE_BLOCK` for that block becomes:

```js
{
  attributes: {
    content: {
      type: 'p',
      key: '0',
      ref: null,
      props: {
        children: {
          type: 'br',
          key: '0',
          ref: null,
          props: {},
          _owner: null
        }
      },
      _owner: null
    }
  }
}
```

Maybe this is a non issue as any block with an Editable component will most likely need this to happen for TinyMCE to work.  This could potentially make the final output of a block weird through `save()` as we will be adding in empty `<br />` tags.  Maybe this is the intended behavior to represent an empty block in  the final rendering of post_content?

**Comment by iseulde** [comment]
This is to pad empty nodes. Normally they are stripped when getting the content, but we get the raw content. `getContent({ format: 'raw' })`

**Comment by iseulde** [comment]
(Which is just innerHTML + some internal stuff stripped that may affect undo levels.)

**Comment by BE-Webdesign** [comment]
I think this will impact `save()` for a block correct?  Does it matter that the component we render in `save()` will have a `<br />` if it is empty?

**Comment by aduth** [comment]
@iseulde Is this fixed by #523?

>I think this will impact `save()` for a block correct?

It could, since the value for the `content` attributes would be non-empty so far as being an element, but still "bogus" content.

**Comment by iseulde** [comment]
@aduth Looks like it. Should just be a `p` with empty props.

**Comment by iseulde** [comment]
@BE-Webdesign Is this still an issue?

**Comment by BE-Webdesign** [comment]
No idea, let me check.

**Comment by BE-Webdesign** [comment]
Looks good, content is now just an empty array.
