### ISSUE TITLE
Snackbar component displays the icon outside of its container

### ISSUE THREAD

**Issue by jaredKreate** [WordPress/gutenberg#56126]
### Description
The `snackbar` component has the option to show an icon along with the notice. That icon's display is currently showing too far to the right and down from the expected inline positioning.

### Expectation
The expected behavior for the icon is to show inline with the text that is shown in the `snackbar` component.

### Potential Fix
I believe that the issue lies within the styling for the `snackbar` component elements, below is an example fix based on the story:
```
.components-snackbar__content {
    display: flex;
    justify-content: space-between;
    line-height: 1.4;
    position: relative;
    align-items: center;
    gap: 1rem;
}
```
The above fix removes the need for:
```
.components-snackbar .components-snackbar__content-with-icon {
    margin-left: 24px;
}

.components-snackbar .components-snackbar__icon {
    position: absolute;
    top: 24px;
    left: 28px;
}
```

### Step-by-step reproduction instructions

1. Go to https://wordpress.github.io/gutenberg/?path=/story/components-snackbar--with-icon
2. Notice the icons alignment in relation to the text.

### Screenshots, screen recording, code snippet

Current View:
![Screenshot 2023-11-14 at 12 39 48 PM](https://github.com/WordPress/gutenberg/assets/4828069/4e09dd96-0404-4e5c-915d-19eb02e53e74)

Fixed View:
![Screenshot 2023-11-14 at 2 36 29 PM](https://github.com/WordPress/gutenberg/assets/4828069/e777b6cc-5cce-4cc5-afd2-8f4575113d7b)

### Environment info

- WordPress Version: WordPress 6.4.1
- Theme: Twenty Twenty-Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report. I was able to replicate it.

This issue can also be seen when displaying the Snackbar via `createNotice`.

```javascript
wp.data.dispatch( 'core/notices' ).createNotice(
	'success',
	'Hello World.',
	{
		icon: '😄',
		type: 'snackbar',
	}
);
```

![notice](https://github.com/WordPress/gutenberg/assets/54422211/bda4d20c-c2a0-4cc0-95f9-0b87df0d69dd)
