### ISSUE TITLE
Navigation: Focus mode: Remove transform to Custom Link

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#56179]
## What problem does this address?
When inside navigation focus mode, the all blocks (e.g. Page List) offer the option to transform itself to a Custom Link:

https://github.com/WordPress/gutenberg/assets/275961/6e78d992-c754-4ea3-8785-98aae4b497df

This also happens for button blocks inside Navigation

## What is your proposed solution?
We should remove this option. Note, this only happens when in Navigation focus mode.

**Comment by getdave** [comment]
This screen no longer exists.
