### ISSUE TITLE
Default colors, gradients and duotones persist in the DOM after they have been disabled in theme.json

### ISSUE THREAD

**Issue by dabowman** [WordPress/gutenberg#56180]
### Description

When you use `settings.color.defaultPalette`, `settings.color.defaultDuotone` and `settings.color.defaultGradients` to turn off the WordPress default options for these supports the css variables still appear in the DOM on inspection. I would expect these to be removed if they've been disabled by the theme and aren't available to the user in the block editor. 

### Step-by-step reproduction instructions

Set `settings.color.defaultPalette`, `settings.color.defaultDuotone` and `settings.color.defaultGradients` to false
inspect the front-end of your application. You should see the variables for the defaults on the body element. One example I'm seeing is the default gradient `--wp--preset--gradient--blush-bordeaux`

### Environment info

WP 6.4.1 
PHP 8 
wp-now local environment

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

In my opinion, this is to keep the default color already applied. For example, `settings.color.defaultPalette` is an option that disables the user's ability to _select_. If you remove the CSS variables that are output to the front end, the colors of existing content will disappear.

**Comment by susurruses** [comment]
I've been watching this get reported over multiple previous tickets (such as [here](https://github.com/WordPress/gutenberg/issues/43385) and [here](https://github.com/WordPress/gutenberg/issues/24684#issuecomment-900083774)), but these threads keep getting closed. I'm hoping the fact that folks keep bringing this up will prevent this one from being closed this time around.

There are _so_ many ways people use WordPress, but one main one is as a CMS with a custom-built theme. In these instances, there's no reason to have these built-in colors be output. I get that for casual theme-switching use-cases, it makes sense to have built-in colors persist, but there really needs to be a way to remove this output for those of us using WordPress as a CMS, with custom-built themes.

Could there maybe be a filter or theme.json setting to remove this output, but have the use of that setting discouraged for distributed themes? Part of what makes WordPress great is that we can disable things that aren't relevant for specific use-cases. This seems like another key area where being allowed to remove this output would be a great help to those of us building custom, non-distributed themes.

**Comment by t-hamano** [comment]
How about using the [wp_theme_json_data_default](https://developer.wordpress.org/reference/hooks/wp_theme_json_data_default/) hook?

```php
function custom_wp_theme_json_default( $theme_json ) {
	$new_data = array(
		'version'  => 2,
		'settings' => array(
			'color'  => array(
				'palette'   => array(),
				'gradient'  => array(),
			),
		),
	);
	return $theme_json->update_with( $new_data );
}
add_filter( 'wp_theme_json_data_default', 'custom_wp_theme_json_default' );
```

**Comment by dabowman** [comment]
I'll give that a shot! I agree that it makes sense to keep these persistent in some cases but It would definitely be useful to be able to remove it. As an agency or enterprise it just seems kinda ... messy? I feel like we shouldn't be outputting stuff that we're not intending to use for a bunch of reasons. As long as there's a stable way to get rid of it, I'm good. I'll report back.

**Comment by dabowman** [comment]
This is a tangent but, I'll also note that this raises the larger question of "what happens to block supports when they get disabled?" Which I've found to be a larger, more foundational issue especially in larger use cases. Gutenberg has gotten better at weeding out attributes for supports that have been disabled, but that requires a user to edit and save a post. When you make a change, like removing a block style or support, and want to ship that to a whole application at once that can be very difficult. In larger use cases that can be hundreds or thousands of posts. Currently, that requires a pretty scary database operation to happen at the same time as your code deployment to remove old references or change them to new ones. Otherwise, as you noted, there might be references to variables that don't exist. That's beyond the scope here, but I think we're catching the tail of the issue. 

I run into this pretty regularly as I'm iterating on my block themes. Perhaps I can't use a core support yet, or I've implemented something with a style that has since been supported by core block supports. Changing from an older way of implementing things to a newer way is very very hard for larger scale applications.

Just thought I'd note it.

**Comment by alizehctl** [comment]
> How about using the [wp_theme_json_data_default](https://developer.wordpress.org/reference/hooks/wp_theme_json_data_default/) hook?
> 
> ```
> function custom_wp_theme_json_default( $theme_json ) {
> 	$new_data = array(
> 		'version'  => 2,
> 		'settings' => array(
> 			'color'  => array(
> 				'palette'   => array(),
> 				'gradient'  => array(),
> 			),
> 		),
> 	);
> 	return $theme_json->update_with( $new_data );
> }
> add_filter( 'wp_theme_json_data_default', 'custom_wp_theme_json_default' );
> ```

There are still some default CSS variables left after adding this to functions.php. Specifically, the ones for default duotone, gradients, spacing, shadow, and font size:

```css
    --wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);
    --wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);
    --wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);
    --wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);
    --wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);
    --wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);
    --wp--preset--gradient--blush-light-purple: linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);
    --wp--preset--gradient--blush-bordeaux: linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);
    --wp--preset--gradient--luminous-dusk: linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);
    --wp--preset--gradient--pale-ocean: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);
    --wp--preset--gradient--electric-grass: linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);
    --wp--preset--gradient--midnight: linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);
    --wp--preset--duotone--dark-grayscale: url( '#wp-duotone-dark-grayscale' );
    --wp--preset--duotone--grayscale: url( '#wp-duotone-grayscale' );
    --wp--preset--duotone--purple-yellow: url( '#wp-duotone-purple-yellow' );
    --wp--preset--duotone--blue-red: url( '#wp-duotone-blue-red' );
    --wp--preset--duotone--midnight: url( '#wp-duotone-midnight' );
    --wp--preset--duotone--magenta-yellow: url( '#wp-duotone-magenta-yellow' );
    --wp--preset--duotone--purple-green: url( '#wp-duotone-purple-green' );
    --wp--preset--duotone--blue-orange: url( '#wp-duotone-blue-orange' );
    --wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);
    --wp--preset--shadow--deep: 12px 12px 50px rgba(0, 0, 0, 0.4);
    --wp--preset--shadow--sharp: 6px 6px 0px rgba(0, 0, 0, 0.2);
    --wp--preset--shadow--outlined: 6px 6px 0px -3px rgba(255, 255, 255, 1), 6px 6px rgba(0, 0, 0, 1);
    --wp--preset--shadow--crisp: 6px 6px 0px rgba(0, 0, 0, 1);
    --wp--preset--font-size--small: 13px;
    --wp--preset--font-size--medium: 20px;
    --wp--preset--font-size--large: 36px;
    --wp--preset--font-size--x-large: 42px;
    --wp--preset--spacing--20: 0.44rem;
    --wp--preset--spacing--30: 0.67rem;
    --wp--preset--spacing--40: 1rem;
    --wp--preset--spacing--50: 1.5rem;
    --wp--preset--spacing--60: 2.25rem;
    --wp--preset--spacing--70: 3.38rem;
    --wp--preset--spacing--80: 5.06rem;
```

**Comment by t-hamano** [comment]
> There are still some default CSS variables left after adding this to functions.php. Specifically, the ones for default duotone, gradients, spacing, shadow, and font size:

What about this code?

```php
function custom_wp_theme_json_default( $theme_json ) {
	$new_data = array(
		'version'  => 2,
		'settings' => array(
			'color'  => array(
				'palette'   => array(),
				'gradients' => array(),
			),
			'shadow' => array(
				'presets' => array(),
			),
			'typography' => array(
				'fontSizes' => array(),
			),
			'dimensions' => array(
				'aspectRatios' => array(),
			),
			'spacing' => array(
				'spacingScale' => array(
					'steps' => 0,
				),
			),
		),
	);
	return $theme_json->update_with( $new_data );
}
add_filter( 'wp_theme_json_data_default', 'custom_wp_theme_json_default' );
```

I'm also not sure what the ideal solution this issue is asking for. If you simply want to remove global style related CSS, isn't the code below sufficient?

```php
function remove_global_styles() {
	global $wp_styles;
	$wp_styles->remove( 'global-styles' );
}
add_action( 'wp_enqueue_scripts', 'remove_global_styles' );
```

**Comment by alizehctl** [comment]
@t-hamano thanks! I'll try these.

To answer your question: I'm not looking to remove global style related CSS - I still want the styles I define in `theme.json` to show up in the DOM. I just want to remove the "default" CSS variables WordPress generates for global styles, like the default spacing, shadow, typography, gradient presets. Since I don't plan to use those.

**Comment by t-hamano** [comment]
I have suggested some solutions, but are there any other scenarios that cannot be resolved?

If there is a case where the CSS variable is output even though it is not used at all in the theme, please let us know.

**Comment by alizehctl** [comment]
I think this code snippet meets all my needs. Thanks!

**Comment by t-hamano** [comment]
So I'd like to close this issue.

@dabowman If there's anything I've missed, please feel free to comment.
