### ISSUE TITLE
Patterns: Provide a way for users to opt out of the 'Choose a Pattern' modal when adding a page

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#56181]
## What problem does this address?
The new 'Choose a Pattern' modal is useful - but _can_ become frustrating for users who don't want to use it, and still need to see it every time.

## What is your proposed solution?
Provide a setting/option where this modal can be enabled/disabled.

**Comment by jordesign** [comment]
From user feedback in the forums:
https://wordpress.org/support/topic/how-do-i-disable-the-choose-a-pattern/

**Comment by MattrCoUk** [comment]
Just for those in whom that triggers anxiety as myself — I’ve created a quick and dirty workaround (use case scenario: e. g. a website with 200 pages to be re-created with a default pattern...)

Github:
https://github.com/MattrCoUk/mattr-dismiss-patterns-popup

Blog post:
https://mattr.co.uk/how-to-disable-the-choose-a-pattern-popup-in-wordpress-twentytwentyfour

**Comment by johnstonphilip** [comment]
I knew this existed and have even played with making my own patterns that use/enable it. 

However, after not using the block editor for a while and coming back to it recently, I found it really jarring to have it pop-up automatically without my prompting.

**Comment by jasonbahl** [comment]
I spun up a new site today to reproduce an issue on a plugin I maintain, and I needed to create a handful of pages for the reproduction scenario.

I was welcomed by this modal on every page: 

![CleanShot 2024-02-14 at 11 00 25](https://github.com/WordPress/gutenberg/assets/1260765/c53efd59-a803-43ff-839d-ca610f54be8a)

And while it was nice to know this new pattern selector is available, I don't want it to pop up every time I create a new page. 

I would love to see some sort of "don't show this to me again" option on the modal, that updated a block editor preference that I could then change again later if I did find it helpful to have the modal on every page in the future. 

![CleanShot 2024-02-14 at 11 31 46](https://github.com/WordPress/gutenberg/assets/1260765/f492b495-6730-4760-ae61-f42970398f47)

**Comment by colorful-tones** [comment]
I just wanted to drop more Twitter/X dialogue around this issue. A few more folks are not keen on the page patterns modal.

X thread starts here: https://x.com/mishterkurth/status/1762655604945076271?s=46&t=qYMrgR5B4ui3KKMSqnKquA

**Comment by chairmanbrando** [comment]
Every time I pop back into Gutenberg after a short time away from it I'm greeted with yet more UI/UX issues foisted upon WP users. It's beyond old at this point.

Every other week there's a new feature in Gutenberg that other builders have been offering for years. I seem to recall this project starting out purposefully _not_ to be a page builder but a simple content editor, yet it's gone so far in that direction that there's a full-on site builder in it.

Can Automattic just buy Elementor already and be done with all this nonsense?

**Comment by MattrCoUk** [comment]
@chairmanbrando While sharing frustrations can be understandable, this platform might be better suited for focused discussions on specific issues.  By outlining the problem and suggesting potential solutions or workarounds, we can create a more constructive dialogue.

**Comment by jakobtrost** [comment]
I have a design suggestion inspired by @jasonbahl's idea:

> I would love to see some sort of "don't show this to me again" option on the modal, that updated a block editor preference that I could then change again later if I did find it helpful to have the modal on every page in the future.

I included a checkbox at the bottom of the modal and a toggle inside the editor preferences. To avoid reinventing the wheel, I looked for similar components.

I was surprised to find that the “Choose a pattern” modal when creating a new template in the site editor does have a bottom bar with a skip button:

<img width="1487" alt="Screenshot-new-date-archive-template" src="https://github.com/WordPress/gutenberg/assets/50317213/2815d630-c15b-47a8-ad04-5904cd6d556a">

I used that and added a “Do not show me this again” checkbox on the left, de-selected by default. The word "me" emphasizes it’s user-specific.
The existing modal uses a simple text-button on the right for the skip action. Adding the checkbox and label on the left made me see the need to emphasize the skip button more. Making it an outlined button improves visibility, visual balance, and indicates interactivity.

<img width="1480" alt="Choose a popup - default" src="https://github.com/WordPress/gutenberg/assets/50317213/960a997e-4220-4d5a-9476-08099523aa87">

I also created a version of the editor preferences that includes this as a new option:

<img width="892" alt="Editor Preferences" src="https://github.com/WordPress/gutenberg/assets/50317213/08380b99-b9da-4d5f-b461-78f81466c8e5">

I’d love to get some feedback on this suggestion to maybe get it ready for a PR in the future.

**Comment by blindmikey** [comment]
How is this still an issue. Interrupting the user is bad UX. This should only pop up when prompted by the user to select a pattern.

**Comment by johnstonphilip** [comment]
What if instead of a modal, this replaced the default block being a `Paragraph Block`, and instead is just a placeholder block that allows you to replace it with a pattern, each of which is presented inside that block? That way nothing has to pop up. So something like this:


```
Type / to choose a block, or select a pattern below to get started

🌅 Pattern 1 | 🌄 Pattern 2 | 🛤️ Pattern 3
```

**Comment by noisysocks** [comment]
Just noting this older comment from https://github.com/WordPress/gutenberg/pull/56307#issuecomment-1818483223:

> My instinct: we should not add this preference yet. The flow for creating new pages is still in flux, with the add new page modal in the site editor, some ideas on a pattern assembler discussed across various comments here, not yet having materialized. In that vein, adding this preference now is going to optimize for an interface that's going to already improve.
>
> If after having refined those other flows such a preference is still desired, we can definitely add it.

@jasmussen: is this interface still in flux? Are there other options we can explore for letting users skip this modal? This feature seems highly requested so it would be good to move this forward.

**Comment by jasmussen** [comment]
> is this interface still in flux? Are there other options we can explore for letting users skip this modal? This feature seems highly requested so it would be good to move this forward.

A little bit, yeah. One of the ideas is to continue to refine the zoom out + contentOnly combo, so when you add a new page, it can start in that interface. @richtabor has some thoughts here too. That said, both those behaviors could potentially have the same opt-out mechanism, which could live in preferences as suggested. This is similar to the pre-publish checks which you can toggle off:

![Screenshot 2024-08-28 at 09 18 19](https://github.com/user-attachments/assets/f0973d74-8378-4dea-857c-33f79f25a247)

**Comment by richtabor** [comment]
>  That said, both those behaviors could potentially have the same opt-out mechanism, which could live in preferences as suggested.

Yes, I'd consider these the same.

**Comment by luminuu** [comment]
[This comment](https://github.com/WordPress/gutenberg/issues/56181#issuecomment-2165782203) already has the design suggestion for it, although the setting has been put in the Interface section, not the Publishing section. I think we can discuss where it fits best, although I think Interface is the better section, as this setting would have only little to do with actual Publishing. cc @jasmussen

**Comment by richtabor** [comment]
> as this setting would have only little to do with actual Publishing. cc @jasmussen

Other than publishing pages :)

**Comment by ramonjd** [comment]
Just stumbled into this. I'd almost call it a bug. 😄 

Here's me trying to edit a page's template bits and moving back and forth:

https://github.com/user-attachments/assets/1cec7ff5-02e0-4109-ad4c-59f2aefd89c6

> Provide a setting/option where this modal can be enabled/disabled.

My vote would be, as well as a setting in preferences, to have the opt-out checkbox on the overlay itself, optionally with a note that it can be turned back on in preferences.

This hands the user immediate control without disrupting their flow.

The other option is to remove this popup in the site editor - what concrete value does it serve?

**Comment by ramonjd** [comment]
I threw up a PR based on @jakobtrost's designs [above](https://github.com/WordPress/gutenberg/issues/56181#issuecomment-2165782203):

- https://github.com/WordPress/gutenberg/pull/65026

https://github.com/user-attachments/assets/3500e7a4-3c0a-4a2d-ac13-6077507ca872

The previous attempt by @glendaviesnz was closed https://github.com/WordPress/gutenberg/pull/56307#issuecomment-1818483223 to avoid adding a preference to the preferences panel.

If this view still stands, I think we should still find a way to stop the panel reappearing unnecessarily.

**Comment by stokesman** [comment]
The opt out PR is much better yet may leave room for improvement. Once opted out, there’s no way to quickly engage the pattern picker modal for new pages. Then opting back in may serve okay if you’re about to go on a spree of creating new pages with starter patterns but you’ll likely opt out again soon after.

Could we consider not autolaunching the modal and instead making a prompt or button available on new pages that provides one-click access? In the Site editor, which already prompts for the page title, it seems like we could try an option to create the draft with a starter pattern. That way it’s quickly available when you want it and never when you don’t.

**Comment by johnstonphilip** [comment]
I already posted a rough mockup of this but I feel like this would better than a dismissable modal, because it never gets in your way, you never have to dismiss it, and it's there if/when you _do_ want it:

<img width="830" alt="Screenshot 2024-09-05 at 1 42 19 PM" src="https://github.com/user-attachments/assets/1aa662bf-01ca-4d25-805a-1cb57d3ed501">

#
If you were to start typing or add a different block, the patterns would disappear, just like the `Type /...` text disappears.

**Comment by stokesman** [comment]
@johnstonphilip, I do like your idea. It would have an advantage to a prompt/button that opens the modal because it’s one fewer click to insert a pattern. Perhaps it can be a bit more distracting then a simple prompt.

--- 
Here’s a demo of a prompt approach:

https://github.com/user-attachments/assets/cfd5633b-7943-41c2-83af-91483ced5b85

I could make that a PR but haven’t yet. I do consider it better to not auto launch a modal.

**Comment by blindmikey** [comment]
I do love the informative unobtrusive prompt approach; users learn about and can quickly access patterns, but doesn't interrupt them if they're not interested. However being able to silence the prompt all together is nice for those not using patterns at all.

**Comment by ramonjd** [comment]
Slightly related. Create a new page on a fresh WP install on trunk with a clean browser local storage:

https://github.com/user-attachments/assets/91c0c8bc-2833-405d-a284-d2404444a241

Probably worth auditing these modals and having some form of centralized control.

**Comment by johnstonphilip** [comment]
@stokesman Personally I don't like the snackbar for anything :D 
https://github.com/WordPress/gutenberg/issues/64622

**Comment by noisysocks** [comment]
I think the decision should move to the beginning of the flow.

![Create page from template](https://github.com/user-attachments/assets/a1af8f9a-dd87-4ece-8577-e3e6f5a14d98)

Selecting _Blank page_ opens the modal we currently have where you enter a title. Selecting _Page from template_ opens a new modal which combines choosing a pattern and entering a title.

**Comment by ramonjd** [comment]
> I think the decision should move to the beginning of the flow.

YES! Thanks for the screenshot too.

I think this makes sense for the site editor, where I'd expect the user to be more comfortable with the editing flows.

 For pages created in the post editor? Not sure. 

What about a placeholder [similar to the suggestion above](https://github.com/WordPress/gutenberg/issues/56181#issuecomment-2332309248) rather than another modal?

<img width="680" alt="Screenshot 2024-09-06 at 3 39 03 PM" src="https://github.com/user-attachments/assets/9eac9a18-3dc0-4205-a086-f3c7b43c8042">

**Comment by johnstonphilip** [comment]
> Selecting Blank page opens the modal we currently have where you enter a title. Selecting Page from template opens a new modal which combines choosing a pattern and entering a title.

I like this concept of moving it to the start of the flow, but if the user select "Blank Page", they shouldn't see the modal. They chose to start with a "Blank Page", so popping up a modal at that point doesn't make sense to me.

**Comment by alFrame** [comment]
Errrmmm. Make it go away. Please!

It's very very annoying. I work with Oxygen Builder. And every time I exit the builder I have to click twice to get rid of a window I never use.

**Comment by ramonjd** [comment]
> It's very very annoying. I work with Oxygen Builder. And every time I exit the builder I have to click twice to get rid of a window I never use.

It's not just you 😄 @ellatrix has a plan to remove this modal:

- https://github.com/WordPress/gutenberg/pull/61489

In the meantime, you can switch the modal off completely using preferences:

- https://github.com/WordPress/gutenberg/pull/65026

**Comment by alFrame** [comment]
Actually there is a very easy solution. At least using the Oxygen Builder.

Without disabling the Oxygen Plugin
Go to Appearance -> Themes and add a new theme
Search for Intentionally Blank and install it
Ignore any warning by Oxygen that themes are disabled

Done. Popup gone!

I still hope this will be a setting in the future!

**Comment by mikes-bowden** [comment]
^ This

**Comment by stokesman** [comment]
> I still hope this will be a setting in the future!

The future has shipped BTW it’s in WP 6.7 or I think could be enabled in 6.6 with the Gutenberg plugin.

![Image](https://github.com/user-attachments/assets/73600e07-62d3-4ed9-b286-0e547332d996)

**Comment by mikes-bowden** [comment]
I'm unsure if this helps anyone, but I had Claude help create a snippet that automatically presses the X.  You have two options: using the snippet below or using what @alFrame suggested above. Setting the theme is cleaner and easier if you can. If you can't, the snippet below should suffice.

```
<?php
if (is_admin()) {
    add_action('admin_enqueue_scripts', function() {
        $current_screen = get_current_screen();
        if ($current_screen && $current_screen->id === 'page') {
            wp_add_inline_script('wp-edit-post', '
                function closePatternModal() {
                    const modal = document.querySelector(".components-modal__frame");
                    const closeButton = modal?.querySelector("button.components-button.has-icon");
                    
                    if (closeButton) {
                        closeButton.click();
                        return true;
                    }
                    return false;
                }

                let attempts = 0;
                const maxAttempts = 10;
                
                const intervalId = setInterval(() => {
                    if (closePatternModal() || attempts >= maxAttempts) {
                        clearInterval(intervalId);
                    }
                    attempts++;
                }, 500);
            ');
        }
    });
}

```

**Comment by roborourke** [comment]
Any advice for dealing with this in Playwright tests? Is there some helper I can use?

**Comment by ramonjd** [comment]
👋🏻 @roborourke You could try looking at other tests that set preferences, e.g., 

https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/specs/editor/various/publishing.spec.js#L69-L121

https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/specs/site-editor/list-view.spec.js#L33

So I'd imagine you'd need to set the right preference in the test, e.g.:

```js
	await editor.setPreferences( 'core', {
		enableChoosePatternModal: false,
	} );
```

**Comment by roborourke** [comment]
@ramonjd thanks! The docs for that package could use some love I think, this is way easier than I thought
