### ISSUE TITLE
Link Control UI: scrollbars showing on smaller screens

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#56190]
On smaller screens a horizontal scrollbar appears when you create a new draft for a page via the navigation link control UI.

![Screen Capture on 2023-11-16 at 10-22-05](https://github.com/WordPress/gutenberg/assets/3593343/61894def-d1ec-4a10-97d9-3392499523a3)

**Comment by richtabor** [comment]
Related to https://github.com/WordPress/gutenberg/issues/53654. Resolving that would fix this as well.
