### ISSUE TITLE
Inspector controls: dropdown covers the controls it's toggling

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#56191]
### Description

When we activate new controls like typography > font family, the same popover that lets us activate them is covering the new controls, so there is no visual feedback that the controls have been activating besides the little tick icon. Besides, knowing how to close the dropdown is not intuitive at all.

### Step-by-step reproduction instructions

1. Insert a paragraph block and add text
2. On the sidebar, open the contextual menu for typography
3. Select any of the inactive controls like Font Family
4. The dropdown is covering the new controls

### Screenshots, screen recording, code snippet

![Screen Capture on 2023-11-16 at 10-33-15](https://github.com/WordPress/gutenberg/assets/3593343/fc36ff89-8953-4c0e-a592-0f1eacc43c5c)

We could have it behave like the color controls:

<img width="611" alt="Screenshot 2023-11-16 at 10 37 51" src="https://github.com/WordPress/gutenberg/assets/3593343/ebe4b35a-e929-40fc-a7b0-dafcdd1feea9">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hanneslsm** [comment]
That's the same as https://github.com/WordPress/gutenberg/pull/55785, isn't it?

**Comment by MaggieCabrera** [comment]
> That's the same as #55785, isn't it?

THANK YOU. I didn't know how to search for this and I couldn't find a similar issue. closing this
