### ISSUE TITLE
Post editor: Missing Back button to go back from template editing

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#56194]
### Description

Discovered while looing into https://github.com/WordPress/gutenberg/issues/56150 as I wanted to check if a similar problem occurs in the Post editor as well.

This appears to be a regression in trunk. I _think_ it's a side effect of https://github.com/WordPress/gutenberg/issues/56150 
Cc @jeryj 

### Step-by-step reproduction instructions

- Test with WordPress 6.4
- Edit a post.
- In the setting panel, click the current template. A popover open. Click 'Edit template'. Screenshot:

![Screenshot 2023-11-16 at 10 39 48](https://github.com/WordPress/gutenberg/assets/1682452/99b3d631-a3f7-4a9d-a3eb-9962730a0f0e)

- The editor switches to a 'Edit template' mode.
- Observe in the top bar there is a 'Back' button to switch back to the normal Post editor mode.
- Observe that whatever you do, the 'Back' button stays there. Screenshot:

![Screenshot 2023-11-16 at 10 51 41](https://github.com/WordPress/gutenberg/assets/1682452/9721083d-4be9-4f7e-bd47-8cb31f814c04)

- Test with latest Gutenberg trunk.
- Repeat the steps above.
- Observe that as soon as you click something within the editor, the Back button and the Command center button disappeaer. Screenshot:

![Screenshot 2023-11-16 at 10 52 27](https://github.com/WordPress/gutenberg/assets/1682452/cff8d39b-09d2-4d27-a634-a9e8c368e128)

- At this point, I'm not sure there is a way to switch back to the normal view other than refreshing the page.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jeryj** [comment]
Thanks for catching this and explaining the issue so clearly! You were right about the cause. https://github.com/WordPress/gutenberg/pull/56217 should address it 🤞🏻
