### ISSUE TITLE
Embed block: pasting an URL doesn't transform to embed block any more (Example: Tweet) 

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#5620]
## Issue Overview

To embed a Tweet into a post you used to be able to just paste the URL into an empty block and it would transform it into an embed block and display the tweet. The webdeveloper console displays: "firefox can’t establish a connection to the server at wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data."
The network view shows a 403 Forbidden error.
## Steps to Reproduce (for bugs)

1. Add post
2. paste: https://twitter.com/Tarendai/status/974028740249432064
3. 
4.

Browser FireFox Developer Edition 60.0b1
Gutenberg 2.4

## Expected Behavior

pasting url transforms to embed block 
## Current Behavior

Nothing happens when you paste
## Screenshots / Video

![mvj6zxcgql](https://user-images.githubusercontent.com/39980/37433661-1d07a31e-27b3-11e8-98b1-4da55b8b05cb.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by aduth** [comment]
Suspected regression of #5311 (changed registration order)
