### ISSUE TITLE
Captions show scrollbars

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#56201]
When you add an Image block (inside a Gallery) and you add captions with **a lot of text** this can cause scrollbars to appear.

This is more visible on Windows operating system.

## Screenshot

<img width="662" alt="Screenshot 2023-11-16 at 11 58 09" src="https://github.com/WordPress/gutenberg/assets/3593343/96c1f457-aceb-4a6b-a061-50a1903c8f58">

(The screenshot is Firefox)

**Comment by MaggieCabrera** [comment]
I think we have a sass mixin to hide scrollbars unless you are hovering, could we use that as a solution?

**Comment by t-hamano** [comment]
Personally, I'm not sure whether to call this a bug. Some people may think that it is the theme's responsibility to decide how to represent the scrollbar. Also, I feel that the scrollbar mixin is mainly used to adjust the UI of the admin screen.

**Comment by MaggieCabrera** [comment]
> Personally, I'm not sure whether to call this a bug. Some people may think that it is the theme's responsibility to decide how to represent the scrollbar. Also, I feel that the scrollbar mixin is mainly used to adjust the UI of the admin screen.

You are right about the mixin but I don't think the default state of the block should look this bad! Specially when we are expecting block themes to not need CSS at all

**Comment by t-hamano** [comment]
I don't have a strong opinion, so if many people find this appearance a bug, I think they can apply this mixin style.

For reference, I will let you know how it looks on Windows OS.

![before](https://github.com/WordPress/gutenberg/assets/54422211/b3ec142f-310e-42de-b267-cbdc5aaa0e6a)

After applying the scrollbar mixin, it will look like this:

https://github.com/WordPress/gutenberg/assets/54422211/b44dfdc7-16aa-4827-87d7-8e0ebc24e9a5

**Comment by MaggieCabrera** [comment]
I think this CSS could go in the block code. It will only be loaded when the block is inserted anyway. I'm not sure if there are any a11y concerns regarding this
