### ISSUE TITLE
Getting System Time time instead of Server Time

### ISSUE THREAD

**Issue by LZL0** [WordPress/gutenberg#5623]
## Issue Overview

Gutenberg gets the time of the local computer and then it decides based on the difference between that and server time if the post will be Published or Scheduled.
If the server time (which is the default time which is given to the post) is ahead of your OS time, then the editor will offer the Schedule button instead of your Publish button, even if you set your local (OS) time incorrectly.

## Steps to Reproduce (for bugs)

1.Make sure that you set your system clock incorrectly (for instance 1 hour back) in the OS,
2.Click on add new post with an account which has the publish_posts capability,
3.The editor will display the 'Schedule' button instead of the 'Publish' button.

## Expected Behavior

The Editor should probably offer the Publish button based on server time.

## Current Behavior

The Editor can incorrectly offer the 'Schedule' button in some rare circumstances described above.

**Comment by jorgefilipecosta** [comment]
Hi @LZL0, thank you for reporting this issue.
We change the way time manipulated in https://github.com/WordPress/gutenberg/pull/5916, and I think this change fixed the issue. I'm now not able to reproduce the problem following the exact steps you provided. If the problem is persisting in your tests feel free to reopen the issue and we will look further.

**Comment by LZL0** [comment]
Thanks for getting back to me and investigating the problem. Okay, will do.

**Comment by LZL0** [comment]
Is 2.8 dropping today?

**Comment by jorgefilipecosta** [comment]
Hi @LZL0, yes 28.8 should be released soon.

**Comment by LZL0** [comment]
Thanks. Just downloaded it. Looking forward working with it. :)
