### ISSUE TITLE
Navigation: Possible to create two navigations by mistake

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#56248]
### Description

The "Create a new menu" option in an empty block is possible to double click:
<img width="557" alt="Screenshot 2023-11-17 at 10 59 31" src="https://github.com/WordPress/gutenberg/assets/275961/62ffab25-3660-434c-b3d0-06afd9dae68d">

If you do that you accidentally create two navigations by mistake

### Step-by-step reproduction instructions

1. Add a navigation block
2. Delete the navigation CPT that the block is using
3. You should now see a prompt that says "Create a new menu".
4. Double click
5. Notice that two navigations are created.

### Environment info

All

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
I wonder if we ought to move these actions to the Core Data store? That way they would be global and we could therefore globally observe their state via `useSelect` and control the UI accordingly.

**Comment by getdave** [comment]
This is still possible today. We should immediately disable the button after it's been clicked.

Logic can be added here pretty easily

https://github.com/WordPress/gutenberg/blob/b7d989e0dafb23866f65295a851e6b8734c3b693/packages/block-library/src/navigation/edit/deleted-navigation-warning.js#L16-L20
