### ISSUE TITLE
Error encountered when adding a Classic block

### ISSUE THREAD

**Issue by chthonic-ds** [WordPress/gutenberg#5625]
## Issue Overview
Adding a Classic block results in an error: "This block has encountered an error and cannot be previewed."

![gutenberg-2 4-add-classic-block-150318](https://user-images.githubusercontent.com/29587253/37440638-6523dab4-2862-11e8-89dd-c3bf03ad31f3.gif)

## Steps to Reproduce (for bugs)
Using WordPress 4.9.4 and Gutenberg 2.4 with TwentySeventeen theme:

1. Install and activate Advanced Custom Fields 4.4.12.
2. Add a new post.
3. Mouse over the "Write your story" block to reveal the plus icon on the left.
4. Click the plus icon and select "Classic".
5. The error is displayed.

Firefox Developer Edition 60.0b2 (64 bit)
Ubuntu 16.04.4 LTS

## Expected Behavior
I expected a functioning Classic block to appear.

## Current Behavior
Classic block fails to load.

**Comment by chthonic-ds** [comment]
Ah! Looks like this is almost certainly a duplicate of 4919.

**Comment by jeffpaul** [comment]
@chthonic-ds let's go ahead and close this issue in favor of #4919 and track updates there, thanks for noting the duplicate!
