### ISSUE TITLE
Site Editor: Static homepage not connected to the Front Page template

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#56267]
Discovered in https://github.com/WordPress/gutenberg/issues/56244

The Front Page template will always resolve to display the homepage, regardless of whether reading settings dictate that it should display latest posts or a static page (see the [template hierarchy](https://developer.wordpress.org/files/2014/10/Screenshot-2019-01-23-00.20.04.png) for more info). 

However, if you set a static homepage, and Front Page exists, the Site Editor doesn't make this connection, and even tells you that an incorrect template is used when you view and edit that page. The post editor works as expected. 

Here's a video that hopefully demonstrates the issue clearly:

https://github.com/WordPress/gutenberg/assets/846565/709682b4-2c74-4e44-80f5-eeff5f11d114

To reproduce:

1. In reading settings select a static homepage
2. In the Site editor create a Front Page template (if one doesn't already exist)
3. Navigate to Pages > [your static homepage] and notice that Front Page isn't listed as the template in the details panel
4. Edit [your static homepage] and notice that Front Page isn't listed as the template in the Inspector

**Comment by draganescu** [comment]
Since the order is:

1. I make a page, which uses the Page template
2. I change settings, to use page at 1 to be homepage
3. I go to Site editor and make a Front Page template

- is the suggestion that when (3) is published the page at (1) is auto updated to use the Front Page template?

**Comment by jameskoster** [comment]
Basically yes. The current site editor implementation is a bug because it doesn't accurately reflect the frontend. If you go and edit a static homepage when Front Page was created you don't see the correct template.

**Comment by youknowriad** [comment]
I'm not entirely sure but I think this probably broke in https://github.com/WordPress/gutenberg/pull/51477 
Maybe someone can confirm by testing prior to that PR. Anyway, I'll continue trying to find a fix here.
