### ISSUE TITLE
Update copy from "template preview" to "show template"

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#56269]
Digging into the template preview feature [during a recent hallway hangout,](https://make.wordpress.org/core/2023/11/15/hallway-hangout-recap-of-working-session-on-consolidating-navigation-modes/) we discussed the language around "template preview" being confusing in that one would expect this to bring you to a template preview. I see this was decided [here](https://github.com/WordPress/gutenberg/pull/52674#issuecomment-1719138802). Can we return to the original proposed language with "show template"?

**Comment by jasmussen** [comment]
CC: @jameskoster

**Comment by jameskoster** [comment]
The concern with "Show template" was that it might be interpreted as a setting for the post/page, and consequently affect the frontend. That was purely an assumption though, so no harm trying it imo.

**Comment by carolinan** [comment]
It took me some time to figure out what part of the interface you meant.

I think it might be easier if the text changed depending on the state, so that when the template is visible, the text could say "Hide template"

**Comment by juanfra** [comment]
Closing as completed in https://github.com/WordPress/gutenberg/pull/57802
