### ISSUE TITLE
Block Inserter: Let me insert all blocks!

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#56266]
## What problem does this address?
Different block inserters show different things in the same context, for example if I have the Columns block selected, if I try to add a block to the Columns block I am given a block inserter with some options:
<img width="837" alt="Screenshot 2023-11-17 at 16 15 23" src="https://github.com/WordPress/gutenberg/assets/275961/1d0c5311-3195-41ba-9429-64fdbeba5caf">

However if I use the main block inserter I am only given the option of the "Column" block:
<img width="1519" alt="Screenshot 2023-11-17 at 16 15 42" src="https://github.com/WordPress/gutenberg/assets/275961/9bcff007-d068-4e0a-a96b-16a63547324a">

This is extremely confusing for users - it looks like something has gone wrong with the block inserter.

## What is your proposed solution?
I think there are two things we should do.

1. If a block has a limited number of allowed inner blocks, we should still show all blocks in the inserter, but they should be below this list, and add blocks after the currently selected block.
2. If the block has special circumstances (like the Columns block which requires a single column to be added before other inner blocks), then the user should still be able to add these other blocks and we can add the necessary wrapping blocks for them.

**Comment by richtabor** [comment]
Noting this is now resolved: 

![CleanShot 2024-07-25 at 07 41 15](https://github.com/user-attachments/assets/13e3c2c4-6c7c-436d-a892-f1add9c7c9b8)
