### ISSUE TITLE
Details block: impossible to get out from block, using a keyboard

### ISSUE THREAD

**Issue by elettrona** [WordPress/gutenberg#56263]
### Description

The block called "details", used in case of inserting a spoiler, has a problem in keyboard navigation: it's impossible to quickly get out from the "detail" block after having written both Summary and Detail parts.
Current result: add Details block, write summary then detail. To get out of the block and add a new one, it's necessary to close the Gutenberg's editing mode switching to navigation mode by pressing Escape key, then press left arrow to Details block, in order to exit it.
Expected result: after writing Summary and Detail -with all content desired for detail-, press "Enter" key twice and it should exit the block, as it does in quotes and lists nested blocks.

### Step-by-step reproduction instructions

1. open an empty post, then add a Details block.
2. add the Summary. Then the Detail.
3. 3. press "Enter" key twice, and it will remain in Details without exiting the block. 
4. this applies both with screen reader uses -JAWS, NVDA,VoiceOver-,and without.

### Environment info

Gutenberg latest stable 17.x build, WordPress 6.4.1, theme twenty-twentyfour and applies to all themes

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by elettrona** [comment]
still present in latest Gutenberg release

**Comment by elettrona** [comment]
still present. And no answer to this one...

**Comment by elettrona** [comment]
Still present in Gutenberg editor 17.6.x builds.

**Comment by elettrona** [comment]
Only work-arounds found to overcome this:

- switching from editing to navigation mode, pressing Esc; then left arrow till "detail" block closes, and afterwards adding a block manually with "add block" button, then verify the new block is actually out of the "details" tree.
- adding a new extra-block (empty block) that is, pressing Enter twice on the keyboard so that you have two empty blocks. On the first you create the "details" with summary and content; so, the other empty one, stays out of the Details block and there is no need to have the "edit mode" switched off. But this is not the proper way to work. Hope someone can solve this, it's a persistent issue coming since details block's birth.

**Comment by carolinan** [comment]
There are over five thousand issues reported in this repository, there is no way for the contributors to work on all, so sometimes it takes time.

**Comment by alexstine** [comment]
This sounds like a fairly serious accessibility bug. Let me try to look into it soon. As a blind screen reader user, I understand how these issues in Gutenberg can really impact workflows. I am currently traveling on business until February 18th so might not be able to make a PR before then.

Thanks.
