### ISSUE TITLE
Consider not padding Frequent tab with blocks that are in common category

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#5627]
## Issue Overview
Creating a new issue because you haven't re-opened the previous one you closed (#3737)

The Frequent blocks tab is showing blocks that I've never used. Even after inserting a single Paragraph block, the Frequent Tab (formerly Recent Tab), is showing Paragraph, Columns, Image, Cover Image, Gallery, Heading, Quote, Audio and Button blocks.

What is the point of having a Frequent Tab if it simply shows a bunch of random blocks that I haven't even used on the page? If you're just going to add random blocks then why bother having this tab at all?

![gutenberg-frequentblocks](https://user-images.githubusercontent.com/2078245/37450136-e5faac12-2880-11e8-862a-165ef66fb9c3.png)

More details can be found on the previous issue raised #3737

## Steps to Reproduce (for bugs)
1. Create new Post/Page
2. Insert single Paragraph block
3. View Inserter menu and switch to Frequent tab
4. Frequent tab is filled with blocks you haven't used

## Expected Behavior
I expect the Frequent tab to only show blocks that been most frequently used. If I've only used one Block, how can it show all these other blocks as been used frequently?

## Current Behavior
Frequent Tab shows random blocks I've never used on the page

## Possible Solution
Only show the blocks I've actually used, and list them in the most frequently used order.

## Related Issues and/or PRs
#3737

_Gutenberg 2.4.0 
Firefox Quantum 58.0.2 (64-bit)_

**Comment by karmatosed** [comment]
Interesting find and I think potentially a bug. I just looked at mine and it seems to not be weighting frequency correctly for me either:

![2018-03-21 at 22 35](https://user-images.githubusercontent.com/253067/37741154-326e3e2a-2d58-11e8-961e-b9b45f8200ec.png)

I am going to change this to a bug as it should absolutely frequent frequent uses. @noisysocks is there a potential this is a change based on the work for the suggested blocks? I would say the frequency in the library should remain untouched.

**Comment by noisysocks** [comment]
Both the _Frequent_ tab in the inserter and the suggested block icons at the bottom of the page use the same algorithm to calculate the list of blocks to suggest.

The algorithm picks nine blocks that the user has used, ordered by a heuristic that weighs both _how recently the block was used_ and _how frequently the block was used_ (see https://github.com/WordPress/gutenberg/pull/5342).

If less than nine blocks have been used, however, then the list of blocks is _padded_ with blocks that are in the `common` category. This ensures that a user who is opening Gutenberg for the first time **always** sees nine blocks in the _Frequent_ tab. This is why there are "random blocks" appearing in the tab.

**Comment by maddisondesigns** [comment]
@noisysocks As I mentioned above, what is the point of having a Frequent Tab if it simply shows a bunch of random blocks that I haven't even used on the page? You may as well just get rid of this tab altogether. By auto-populating this tab so there's 9 blocks means your forcing a users eyes to do more work, scanning through all the blocks, than what they would if it only showed the few blocks that they'd actually used.

When I'm selecting fonts in Microsoft Word, it separates your recently used fonts at the top of the menu, for easy selection. It doesn't automatically add in a bunch of extra common or adhoc fonts, it only shows the ones that I've used. If I've used one font, it only shows one font. If I've used 5, it'll show 5. This is what people are used to.

![gutenberg-recentwordfonts](https://user-images.githubusercontent.com/2078245/37746893-797c83d0-2dd0-11e8-9aae-953397fb135b.png)

Can you please reopen this while the discussion is ongoing.

**Comment by noisysocks** [comment]
> As I mentioned above, what is the point of having a Frequent Tab if it simply shows a bunch of random blocks that I haven't even used on the page? 

I personally think that it's nice that a brand new user is presented with common blocks rather than a blank tab or the fairly overwhelming _Blocks_ tab.

cc. @jasmussen and @mtias for design input. https://github.com/WordPress/gutenberg/issues/2551 raised a very similar concern regarding the usefulness of a Frequent/Recent tab. I think that it's difficult to decide on this one way or another in the absence of data from performing user testing on this tab.

For context, https://github.com/WordPress/gutenberg/pull/1694 is what introduced this padding behaviour.

**Comment by maddisondesigns** [comment]
> I personally think that it's nice that a brand new user is presented with common blocks rather than a blank tab or the fairly overwhelming Blocks tab.

As @karmatosed mentioned on #2551, one solution would be to reorder the tabs so that the _Frequent_ tab is last, rather than first.

I think another option would be to simply make the _Blocks_ tab the default, on new pages. That is, if you've just created a new page and clicked the inserter menu for the first time, make the _Blocks_ tab the default, rather than the _Frequent_ tab. This way you could leave the order of the tabs as they are.

When you're editing an existing page (as opposed to creating a new page), you could leave the _Frequent_ tab as the default as it's more than likely going to show a few different blocks in it anyway.

**Comment by jasmussen** [comment]
There is certainly merit in honing and polishing the Inserter, and how frequency is created. 

I can also see why it would make sense to show as few blocks as possible, on a completely fresh install, and then let the tab be populated as a user starts using blocks. For example it could have Image, Heading, Gallery, perhaps List, and no more.

However I'd be careful to do too many changes to the Inserter in this stage of the Gutenberg project — we need to wrap things up, and also leave some improvements for the next team working on the Gutenberg Customization focus. 

Meta-note, please: no-one should take offense at tickets getting closed. The _discussion_ is not closed, and as is evident from this discussion, tickets can be reopened.

**Comment by karmatosed** [comment]
I actually think we could do 2 things here. As they are 2 distinct places we could ask why should they show the same things.

- Frequent tab be empty for new users and add as you use them.
- Suggested block icons: have algorithm.

Now, the issue with that is an empty tab, maybe we add a message for new users. This is what I expected to happen, which is why I also thought this was a bug. It's interesting that it may be what others expect. My focus was on the suggested blocks in the iterations before, therefore assuming they weren't linked.  Apologies for getting us off track there.

I would add that we totally should be ok closing issues yet continuing discussion.

**Comment by noisysocks** [comment]
In the short term, I think we should rename the tab to _Suggested_. This is an easy change that hopefully will prevent confusion about why the default inserter tab displays blocks that haven't been used.

In the medium term, we can look into alternative designs for the default inserter tab based on feedback we get from the community and user testing.
