### ISSUE TITLE
Button text doesnt wrap

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#5628]
## Issue Overview

You specifically mention that this release fixed an issue with button text not wrapping. It hasn't.

![gutenberg-buttontextnotwrapping](https://user-images.githubusercontent.com/2078245/37450663-e4e8c8fc-2882-11e8-9376-da397c6627bf.png)

## Steps to Reproduce (for bugs)
1. Insert button block
2. Type a lot of text on the button

## Expected Behavior
Button text should wrap and not push the rest of the interface off the screen

## Current Behavior
Button text doesn't wrap

_Gutenberg 2.4.0
Firefox Quantum 58.0.2 (64-bit)_

**Comment by harsh-barach** [comment]
@maddisondesigns I have solved the [issue](https://github.com/WordPress/gutenberg/pull/5636).
