### ISSUE TITLE
List css added via `theme.json` are applied globally.

### ISSUE THREAD

**Issue by jdamner** [WordPress/gutenberg#56318]
### Description

When using the CSS configuration in the `theme.json` for list blocks, the selector used by WP is `ol, li { ... }`. This means that any CSS added here is applied at a global scope, such as to _all_ site furniture, menus even the WP-Admin bar. 

I would expect that the list block output to contain a class and then the CSS from the theme.json to be limited to that class. Ie
`ol.wp-block-list, ul.wp-block-list { ... } `

### Step-by-step reproduction instructions

Add the following snippet to `theme.json` in your theme

```json
{
  "styles": { 
    "blocks": { 
      "core/list": {
        "css": "&:not(ol) > li::marker { content: '— '; color: 'red' }"
        },
      }
    }
}
```
Visit the site. 

### Screenshots, screen recording, code snippet

See the admin-bar having the list-style applied. 
![Screenshot 2023-11-20 at 12 42 50](https://github.com/WordPress/gutenberg/assets/482959/22ce716a-c0e9-4e15-af46-8adec8dbb3b8)

### Environment info

WP 6.4.1, this will affect all browsers and environments though. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This issue was also proposed a long time ago in #12420. As a temporary solution, the code in [this comment](https://github.com/WordPress/gutenberg/issues/12420#issuecomment-1557986683) might be helpful.
