### ISSUE TITLE
Text columns formating toolbar repeats

### ISSUE THREAD

**Issue by mclblock** [WordPress/gutenberg#5633]
## Issue Overview
The Text Columns block allows to create text over N columns. When creating a Text Columns block with 3 columns, and you attempt to change the formatting of the text in one column (i.e. add a link, make bold, etc), the text formatting toolbar appears 3 times. Furthermore, when adding a link, the "add link" popup will appear three times. This issue also scales, so when creating 5 columns, the formatting toolbar will show 5 times

## Steps to Reproduce (for bugs)

1. Create an empty page
2. Add a Text Columns block
3. Add dummy text
4. Attempt to change the text formatting.

Observe that the formatting UI shows twice (assuming you left colums set to 2. 
## Expected Behavior

The formatting UI should only show once, regardless of how many columns the Text Columns block is using.
## Screenshots / Video

here some step by step to demo the issue
1) Two columns with dummy text
![1 - 2 col link](https://user-images.githubusercontent.com/16672507/37458819-1aecc6fa-283e-11e8-8226-ac21d61adb78.PNG)

2) Now try to change the formatting of the text in either column. (Note the duplicated text formatting toolbar)
![2 - 2col link](https://user-images.githubusercontent.com/16672507/37458820-1aff4bf4-283e-11e8-975f-9818d33b71ab.PNG)

3) Now I clicked on the Anchor link to attempt to add a link.  Note the link UI has also duplicated
![3 - 2col link](https://user-images.githubusercontent.com/16672507/37458821-1b117fae-283e-11e8-87a0-6df761be85fa.PNG)

4) Adding 4 columns scales the UI further.
![4 - 4col toolbar](https://user-images.githubusercontent.com/16672507/37458822-1b233104-283e-11e8-83bc-c0f39d90a250.PNG)

## Related Issues and/or PRs

I could not find any related issues, so apologies if it does exist and I couldn't find them.
## Todos
- [ ] Tests
- [ ] Documentation

**Comment by gziolo** [comment]
This should be fixed with #6280, thanks for opening this issue 👍 @mclblock, let us know if that solves your issue.
