### ISSUE TITLE
Upload External Image: Change the label

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#56345]
## What problem does this address?
When working with a user, I saw some confusion about the "Upload External Image" option:

<img width="575" alt="Screenshot 2023-11-20 at 22 48 48" src="https://github.com/WordPress/gutenberg/assets/275961/c3045a4a-ee29-4eb3-a137-ec92198b5e93">

The user thought that this would be an option to upload an image from an external source, rather than that this image _is_ an external image that needs uploading.

## What is your proposed solution?
We could change the label to something else, for example:

- Add image to media library
- Save image in media library

Other suggestions welcome!

**Comment by t-hamano** [comment]
I suggest "Add image to media library" or "Upload image to media library". This issue may also be related to the panel that appears when you first publish a post that contains external resources.

![publih-upload-media](https://github.com/WordPress/gutenberg/assets/54422211/ecc8fabc-f334-4103-823f-a59382da1672)

**Comment by waviaei** [comment]
How about "Upload local image"?

I am not sure whether every user knows or find it self explanatory to understand what "Media library" is.
