### ISSUE TITLE
Site Logo Block: Logo is not displayed when logged in as a non-administrator user

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#56358]
### Description

When a non-administrator user who cannot change the logo logs into the site and inserts a Site Logo block in a post, the logo should not be able to be changed, but the logo should be displayed.

However, the spinner remains visible and the logo does not appear.

### Step-by-step reproduction instructions

- Upload a site logo.
- Log in as an administrator user and upload the site logo.
- Log in as a user other than the administrator.
- Insert a Site Logo block into your post.
- The logo should not be displayed.

### Screenshots, screen recording, code snippet

![site-logo](https://github.com/WordPress/gutenberg/assets/54422211/3f0b2147-46b6-431d-9108-ade3e3e87675)

### Environment info

- WordPress Version: WordPress 6.5-alpha-57120
- Gutenberg Version: trunk (17.1.0-rc.1)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I found a similar issue submitted in core regarding the site editor logo.

[#59935 (Site editor: logo) – WordPress Trac](https://core.trac.wordpress.org/ticket/59935)

The patch currently attached to that core ticket appears to resolve this issue as well.

**Comment by Mamaduka** [comment]
Odd. I think I fixed exact same issue last year. I'll have a look.

**Comment by hellofromtonya** [comment]
In WordPress Core, [a fix was committed](https://core.trac.wordpress.org/changeset/57147) earlier today to `trunk`. Retesting with `trunk`, the changeset resolves the issue reported here. This fix will ship with WordPress 6.4.2.

**Comment by Mamaduka** [comment]
Thank you, @hellofromtonya!
