### ISSUE TITLE
Synced Pattern: Posts cannot be saved if a pattern is updated by a non-administrator

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#56356]
### Description

For example, an author can insert a synced pattern created by an administrator using the inserter. The author can then edit the content within the synced pattern.

However, if you update the post, the save will fail, probably because you don't have permission to update that pattern. Unsaved entities will remain and you will not be able to save unless you reload your browser.

The behavior I expect is that you shouldn't be able to edit the synced pattern in the editor unless you have permission to edit it.

### Step-by-step reproduction instructions

- Create a synced pattern with an admin user.
- Create a user with author privileges and log in as that user.
- Inserts a synced pattern created by an admin user.
- Update content within a synced pattern.
- Press the update button.
- The save should fail.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/c7d3c4bb-e4ca-4193-8002-aaca8da7fa81

### Environment info

Latest Gutenberg (17.1.0-rc.1)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
This looks  like a duplicate of https://github.com/WordPress/gutenberg/issues/54442

**Comment by t-hamano** [comment]
@glendaviesnz Thank you for teaching me. I'm sure it's the same, so I'll close this issue.
