### ISSUE TITLE
Typography: Normalise labels between Font and Font Family

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#56374]
## What problem does this address?
The label for the Font Family setting is different between where it is enabled and where it is set:
<img width="294" alt="Screenshot 2023-11-21 at 11 15 24" src="https://github.com/WordPress/gutenberg/assets/275961/4291c8d4-deae-47e9-8128-3921108a2e69">
<img width="298" alt="Screenshot 2023-11-21 at 11 15 18" src="https://github.com/WordPress/gutenberg/assets/275961/2ab1d710-c06f-49e1-8477-6da08999a270">

## What is your proposed solution?
We should normalize these labels (probably to Font Family).

**Comment by hbhalodia** [comment]
Hi @scruffian @jordesign @t-hamano @kurudrive, I see that it is same for `Font Size`. In that case, if we are changing for `Font Family`, we should also change for the `Font Size` to make it consistent. LMK your thoughts. You can refer to the screenshots below.

<img width="291" alt="Screenshot 2023-12-12 at 10 32 18 AM" src="https://github.com/WordPress/gutenberg/assets/58802366/43688d7f-53d5-43e9-85cd-68d0ca40af51">

LMK, If I can raise the PR for same by creating a new issue and add this on existing PR and issue.

Thanks.

**Comment by creativecoder** [comment]
This came up for a theme builder I was working with today--it was not immediately evident that "Font" meant "Font Family". 

I agree that "Font Family" would be a better label for the dropdown selector.

**Comment by t-hamano** [comment]
I'd like to close this issue since #60547 appears to suggest improvements more broadly as well. If you have any opinions, please feel free to comment on #60547.
