### ISSUE TITLE
Pattern icon misuse in the swap template UI

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#56380]
<img width="1540" alt="Screenshot 2023-11-21 at 12 03 13" src="https://github.com/WordPress/gutenberg/assets/846565/4bf96ae2-41e4-4fb3-8890-22cb7b963f8c">

When editing a page in the site editor there's a template swapping modal accessed via the Inspector. Beneath each preview in the modal is the template name and an icon. I don't think any icon is required here.

**Comment by glendaviesnz** [comment]
Potential fix [here](https://github.com/WordPress/gutenberg/pull/56407)
