### ISSUE TITLE
Most used tags feature

### ISSUE THREAD

**Issue by ikenfin** [WordPress/gutenberg#5638]
Hello!
Is this possible to return "Most used tags" link? 

For example, i'm using hashtag like tag naming system, and it's really annoing to type every *\#tag* every time i need to add the tag to post.

**Comment by karmatosed** [comment]
This is a feature I certainly wouldn't have anything against us bringing back. I'm interested in how many others use it, would love to find out more about that. If it is something people are relying on then yes lets bring it back. In theory we can just by adding the link like in Classic Editor.

**Comment by drw158** [comment]
A common pattern for this type of thing is to show the most recent tags below the input field after the input field receives focus.

**Comment by karmatosed** [comment]
I think this could be an idea in the future but not for the first release of Gutenberg. I am going to close this but move to the ideas project as a result.

**Comment by donnchawp** [comment]
I use the "most used" tags feature all the time on my photoblog where I tag posts with the location and content of my photos. Same general location and similar content so the tag cloud is invaluable.

**Comment by justintadlock** [comment]
Just noting that I got a support question today about this for a non-hierarchical custom taxonomy in one of my plugins.  Remembering terms isn't very user friendly.  Having some sort of method to select from an existing list helps.

**Comment by Markmcl** [comment]
It would be a help to enable being able to select from existing list. I endorse comments above. Users are used to this functionality being available.

**Comment by dcwebman** [comment]
Add another plus one for this feature that was lost. I use it on every post to help select the common tags I use.

**Comment by ms-studio** [comment]
I don't _always_ use tags – but when I do, I like to be consistent. The "Most Used Tags" interface was a very helpful feature for consistency. I would love to see it coming back with a future Gutenberg update.

**Comment by paynterf** [comment]
I just spent an entire day trying to (once again) figure out how to add the 'most used' tag cloud feature to my Quick Edit screen on the dashboard, and to the 'Publish' sidebar in the post edit screen, once again without success.  The ability to select from a list of most-used tags for my blog posts was one of the very best features of the classic editor, and now it is gone.  IMHO this is a major failing of the Gutenberg block. Why have all this new stuff if you have to give up significant functionality?

Frank
