### ISSUE TITLE
Add name input to pattern inspector 

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#56393]
I expected to be able to name/rename a pattern within the pattern inspector, via a text input above categories, with a label of "Name". Currently, I have to go back to the pattern grid to rename a pattern, or use the command palette. 

![CleanShot 2023-11-21 at 11 15 21](https://github.com/WordPress/gutenberg/assets/1813435/61e3ffb7-6aff-4e76-9ae0-652d069c3c27)

**Comment by t-hamano** [comment]
In the latest Gutenberg, we can rename it from the dropdown in the top right corner, so I will close this issue.

![image](https://github.com/WordPress/gutenberg/assets/54422211/d708dbf5-afc1-48b7-876e-94866b87ab98)
