### ISSUE TITLE
Columns: Resize with drag handles

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#56391]
## What problem does this address?
Some users expect to be able to resize columns in the same way as images, using drag handles, rather than a slider:
<img width="1066" alt="Screenshot 2023-11-21 at 15 15 22" src="https://github.com/WordPress/gutenberg/assets/275961/153f7c1d-1168-45a9-b242-02dce41eb116">

## What is your proposed solution?
We should add drag handles to the columns block to allow users to control the width of the columns, for consistency with the image block.

**Comment by carolinan** [comment]
I believe this is a duplicate of https://github.com/WordPress/gutenberg/issues/15659?

**Comment by scruffian** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/15659
