### ISSUE TITLE
Blockquote block empties after switching to text and back.

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#564]
To reproduce, switch to text mode, **focus** the field, and switch back to visual mode. The blockquote is now empty.

**Comment by youknowriad** [comment]
I can't reproduce this. Any context?

**Comment by jasmussen** [comment]
I was able to reproduce this by following the steps very very carefully, the first step being selecting the blockquote first. 

Here's a video: https://cloudup.com/cMHh_0H_dIG
