### ISSUE TITLE
Scroll bar does not work if I want to select a category when creating a pattern 

### ISSUE THREAD

**Issue by hagege** [WordPress/gutenberg#56419]
### Description

When I want to create a pattern, the scroll bar does not work when I want to select a category

### Step-by-step reproduction instructions

1. Mark a pattern
2. In the menu via the three vertical dots (Kebap menu) Select Create Pattern
3. Click in the Categories field
4. Select a category via the scroll bar

### Screenshots, screen recording, code snippet

![issue_creating_a_pattern_with_choosing_a_category](https://github.com/WordPress/gutenberg/assets/27292550/3d5e310b-a2d6-45d1-97a0-4775669923b9)

### Environment info

Gutenberg not installed
Same issue when using Twenty Twenty-Four
`
### wp-core ###

version: 6.4.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: undefined
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: D:\laragon\www\fse_tc_new
wordpress_size: 57.81 MB (60622734 bytes)
uploads_path: D:\laragon\www\fse_tc_new/wp-content/uploads
uploads_size: 6.74 MB (7066988 bytes)
themes_path: D:\laragon\www\fse_tc_new/wp-content/themes
themes_size: 19.65 MB (20607583 bytes)
plugins_path: D:\laragon\www\fse_tc_new/wp-content/plugins
plugins_size: 42.27 MB (44323549 bytes)
database_size: 976.00 KB (999424 bytes)
total_size: 127.43 MB (133620278 bytes)

### wp-active-theme ###

name: Twenty Twenty-Three (twentytwentythree)
version: 1.3
author: the WordPress team
author_website: https://wordpress.org
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, widgets-block-editor, block-templates
theme_path: D:\laragon\www\fse_tc_new/wp-content/themes/twentytwentythree
auto_update: Disabled

### wp-themes-inactive (5) ###

GeneratePress: version: 3.3.1, author: Tom Usborne, Auto-updates disabled
Ollie: version: 1.1.0, author: Mike McAlister, Auto-updates disabled
Twenty Twenty-Four/twentytwentyfour-trunk: version: 1.0, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Four: version: 1.0, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.6, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (1) ###

The Icon Block: version: 1.6.0, author: Nick Diego, Auto-updates disabled

### wp-plugins-inactive (10) ###

Floating Action Button: version: 1.2.2, author: Faraz Quazi, Auto-updates disabled
Gutenberg: version: 17.0.2, author: Gutenberg Team, Auto-updates disabled
Lemmony Companion: version: 1.2, author: Shufflehound, Auto-updates disabled
Shrink Header for Twenty Twenty-Three: version: 1.0, author: hgg, Auto-updates disabled
Shrink Header on Scroll for Twenty Twenty-Three: version: 1.0, author: Your Name, Auto-updates disabled
Sticky Block: version: 1.11, author: Senff, Auto-updates disabled
Transients Manager: version: 2.0.3, author: WPBeginner, Auto-updates disabled
WordPress Importer: version: 0.8.1, author: wordpressdotorg, Auto-updates disabled
WP-Sweep: version: 1.1.8, author: Lester 'GaMerZ' Chan, Auto-updates disabled
WP Reset: version: 1.98, author: WebFactory Ltd, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: 1
post_max_size: 2G
upload_max_filesize: 2G
max_effective_size: 2 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/8.1.10
php_version: 8.1.10 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 36000
memory_limit: 512M
max_input_time: 60
upload_max_filesize: 2G
php_post_max_size: 2G
curl_version: 7.77.0 OpenSSL/1.1.1q
suhosin: false
imagick_availability: false
pretty_permalinks: true
current: 2023-11-22T08:46:58+00:00
utc-time: Wednesday, 22-Nov-23 08:46:58 UTC
server-time: 2023-11-22T08:46:56+00:00

### wp-database ###

extension: mysqli
server_version: 5.7.33
client_version: mysqlnd 8.1.10
max_allowed_packet: 536870912
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: D:\laragon\www\fse_tc_new/wp-content
WP_PLUGIN_DIR: D:\laragon\www\fse_tc_new/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I can reproduce it 👍 

It seems to happen whenever the `__experimentalExpandOnFocus` prop is set on the `FormTokenField` component. It also happens in the storybook - https://wordpress.github.io/gutenberg/?path=/docs/components-formtokenfield--docs.

edit: Seems like whether the suggestion list is open (`isExpanded`) constantly flips between `true` and `false` when that prop is set and the user clicks the scrollbar. When that happens the scroll position is possibly repeatedly set at the top, cancelling out any user action.

**Comment by annezazu** [comment]
Adding this to the 6.4 board to keep track as this would be good to fix in a future point release (6.4.2).
