### ISSUE TITLE
Query Loop Block: Can't find post in the editor

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#56439]
### Description

When I insert a Query Loop block in the editor, there should be posts that matche the query, but no post is found. On the frontend, the posts are displayed correctly.

This problem seems to occur when the Gutenberg plugin is enabled.

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/bac0bcfe-3dbc-4931-9c00-f665c21fae2a

### Environment info

WordPress Version: WordPress 6.5-alpha-57120
Gutenberg Version: 17.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tobeyadr** [comment]
Same issue here!

**Comment by lwangdu** [comment]
I am having same issue here too
