### ISSUE TITLE
Backward compatibility issue with SVG icons on DropdownMenu component

### ISSUE THREAD

**Issue by renatho** [WordPress/gutenberg#56448]
### Description

When dropdown menu contains SVG icons, it used to work well. But now it's not setting the SVG width and height, so depending on the `svg` it's broken.

### Step-by-step reproduction instructions

1. Use the `DropdownMenu` component with the `controls` prop. You can use the example from https://developer.wordpress.org/block-editor/reference-guides/components/dropdown-menu/#usage-2.
2. Check that the icons are broken when rendering.

### Screenshots, screen recording, code snippet

Before (when it used to work - tested in tag `v16.0.0`):
<img width="718" alt="Screenshot 2023-11-22 at 15 29 24" src="https://github.com/WordPress/gutenberg/assets/876340/ec540917-98d4-49f2-b0a2-10b907c99702">

Currently:
<img width="208" alt="Screenshot 2023-11-22 at 15 30 00" src="https://github.com/WordPress/gutenberg/assets/876340/2b65bf1e-ddeb-40b5-8948-f34dc1679874">

(This screenshot is from Sensei. If you test it there you will see it a little different - big icons. The reason is that I removed other related styles we have in Sensei to have a more generic scenario)

### Environment info

- WordPress 6.4 / Gutenberg 17.1.0.
- Chrome
- OSX

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ciampo** [comment]
The `icon` set in the `controls`  should be [passed to `Button`](https://github.com/WordPress/gutenberg/blob/4b10f653ba12baebd374dacdb2df2d93c017a422/packages/components/src/dropdown-menu/index.tsx#L195), which internally [uses the `Icon` component](https://github.com/WordPress/gutenberg/blob/4b10f653ba12baebd374dacdb2df2d93c017a422/packages/components/src/button/index.tsx#L222-L228), which is [supposed to set a size on SVG icons](https://github.com/WordPress/gutenberg/blob/4b10f653ba12baebd374dacdb2df2d93c017a422/packages/components/src/icon/index.tsx#L80-L89).

Would you be able to debug further on your side why `Icon` is not applying the size correctly?

**Comment by renatho** [comment]
@ciampo, thank you for checking it!

I just confirmed that the context where I was testing it imports SVG files using `@svgr/webpack`. It's importing it as a function component and sending it directly to the `controls` without instantiating it, which will send it as the `icon` prop to the `Icon` component, like [this](https://github.com/WordPress/gutenberg/blob/4b10f653ba12baebd374dacdb2df2d93c017a422/packages/components/src/icon/test/index.tsx#L50) (but with an `svg` instead of an `span`).

Since the `Icon` also accepts function components, I thought to also add the `width` and `height` [there](https://github.com/WordPress/gutenberg/blob/4b10f653ba12baebd374dacdb2df2d93c017a422/packages/components/src/icon/index.tsx#L74). But given that it passes the `size` prop, maybe its purpose is more for components like the `Dashicon`.

So I'm considering to close this issue and the PR, and consider that it's wrong using a function component that doesn't have the `size` prop. WDYT?

**Comment by ciampo** [comment]
Thank you for looking into it, @renatho !

We could look into passing `width` and `height` to `icon` when it's a function. There could be side effects in case the React function component passed as the `icon` already handled props called `width` and `height` in a specific way, although I don't think that would be the case (@mirka , can you think of other potential issues / side effects?)

> So I'm considering to close this issue and the PR, and consider that it's wrong using a function component that doesn't have the size prop. WDYT?

If you're able to solve the problem on your side, that is also an option. We can always revisit the possibility of adding this functionality if we receive more feedback about it.

**Comment by renatho** [comment]
> If you're able to solve the problem on your side, that is also an option. We can always revisit the possibility of adding this functionality if we receive more feedback about it.

Yep! We already solved it on our side. So I'll just wait for the answer to your question to see if I close this issue+PR or if I add the props to the function component. 😉

**Comment by ciampo** [comment]
Let's close for now, and re-open if we get more feedback about supporting this feature. Thank you for the help!
