### ISSUE TITLE
Pasted search results title is treated as plain text

### ISSUE THREAD

**Issue by RyanNeilson** [WordPress/gutenberg#56444]
### Description

After a recent jump from WP 5.8.4 to 6.3.1, pasted search results titles are being handled as plain text instead of links. When copying the title of a webpage out of Google search results and pasting that into the block editor, I expect the pasted content to be formatted as a link to the webpage URL. 

### Step-by-step reproduction instructions

Search for something in Google.
Copy the title link of a search result.
Paste this into the block editor of a basic WP install running 6.0 or higher.
The search result link will be pasted in as plain text.

### Screenshots, screen recording, code snippet

**Search Result**
![Screen Shot 2023-11-22 at 12 43 10 PM](https://github.com/WordPress/gutenberg/assets/32141267/22b6a4be-35b5-495a-a89a-1ab0a2f6a6a6)

**WP 5.8.4**
![Screen Shot 2023-11-22 at 12 53 40 PM](https://github.com/WordPress/gutenberg/assets/32141267/7e31f15f-4c85-48cf-b977-16e1066d53da)

**WP 6.0 and higher**
![Screen Shot 2023-11-22 at 12 46 29 PM](https://github.com/WordPress/gutenberg/assets/32141267/5ad428da-e5a2-4c4f-8afa-5b73b7cf9207)

### Environment info

Tested against WP 5.8.4, 5.9, 6.0, 6.3.1, 6.4.1

Tested using Twenty Twenty Two theme with no plugins activated.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Noting that I can replicate with WP 6.4.1 and GB 17.1.1 (and without GB). Going to add this to the polish board as this seems like it would be a straightforward fix (famous last words).

**Comment by waviaei** [comment]
Able to replicate the issue with git pull of gutenberg as of 2024-12-06 and wp-env (6.5-alpha-57143).

![CleanShot 2023-12-07 at 02 11 23](https://github.com/WordPress/gutenberg/assets/1564991/18786677-237f-400d-bb09-86a4d2704ab5)

(please ignore the zoom app popup in the middle)

**Comment by climdj** [comment]
This is still a problem. The original reproduction steps are still valid.

**Comment by climdj** [comment]
This is still a problem. The original reproduction steps are still valid.

**Comment by Mamaduka** [comment]
I'm unable to reproduce the issue. Is this a browser-specific issue?

Tested with:
Gutenberg: 19.0
WP: 6.6.1 (with and without Gutenberg active)
Chrome: Version 127.0.6533.120

## Screenshot

https://github.com/user-attachments/assets/4003ff61-e202-47fd-9ed4-fcab365093c9

**Comment by annezazu** [comment]
I also can no longer replicate this with GB 19 and 6.6.1! Let's close out for now but if someone can replicate, please share and we can reopen.
