### ISSUE TITLE
Input Field block: theme.json spacing/margin settings not working on front end

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#56458]
### Description

With the experimental form block, the following code in theme.json for [Input Field](https://developer.wordpress.org/block-editor/reference-guides/core-blocks/#input-field) only seems to be applied to the block editor, not the front end. In my theme, the x-large spacing = 100px, which was applied to clearly demonstrate how it looks in both places.

```
"core/form-input": {
	"spacing": {
		"margin": {
			"bottom": "var(--wp--preset--spacing--x-large)"
		}
	}
}
```

According to the [block.json](![image](https://github.com/WordPress/gutenberg/assets/486261/e8c64f22-28c3-46df-a1cf-9c8d34934ee4)), it appears the styling should occur via `"style": [ "wp-block-form-input" ]`, but there are no wrapping divs for each input on the front end with the `.wp-block-form-input` class.

### Step-by-step reproduction instructions

1. Create form with input fields
2. Add the code above to theme.json
3. View block editor view vs. front end

### Screenshots, screen recording, code snippet

**Block editor view:**

![image](https://github.com/WordPress/gutenberg/assets/486261/f3edfbfd-ef97-4f02-8d71-619afcbc3035)

**Front end view:**

![image](https://github.com/WordPress/gutenberg/assets/486261/025dae9b-c098-41d3-8563-fe63708895b5)

### Environment info

WordPress 6.4.1, Gutenberg 17.1.0 active.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I will submit a PR to fix this issue in the near future.

**Comment by aristath** [comment]
Related to https://github.com/WordPress/gutenberg/pull/55755 which fixes some styling issues in forms blocks

**Comment by t-hamano** [comment]
I submitted #56507 to resolve this issue. However, during the fixture test to ensure that deprecation was performed correctly, we discovered that form-related blocks were not working correctly. This issue is summarized in #56590.
