### ISSUE TITLE
Fix label of columns inspector panel

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#56461]
Add default inspector panels for core blocks should just use "Settings" instead of $blockName Settings". 

Instead of "Column settings", update this label to read "Settings":

![CleanShot 2023-11-22 at 20 27 52](https://github.com/WordPress/gutenberg/assets/1813435/c4e6b731-2448-4a18-aebd-3ea1db09fd2b)

**Comment by t-hamano** [comment]
Fixed in #56647.
