### ISSUE TITLE
Link suggestions in editor “never” shows taxonomies

### ISSUE THREAD

**Issue by scrobbleme** [WordPress/gutenberg#56478]
### Description

- The link suggestions tool does 3 separate requests (`posts`, `taxonomies`, `media`)
- it then just shows the first x results

**Problem**

When there are too many `posts `containing a result → `taxonomies `(or `media`) are never shown as an option, even if more relevant (i.e. have exact title match)

### Step-by-step reproduction instructions

1. Create many posts with a specific keyword (don't know the threshold, maybe 25)
2. Create a term with teh same keyword

Try to link the term via the search → not possible, as you can't select it

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/504835/a5806101-e847-4f34-bae9-851a4a6dc85f

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

Here is an export from a plain wordpress

* Many "duplicated" posts
* Keyword "suggestions" as category and in title of every post -> not possible to link the category
* Keyword "unique" -> only used as category

[basic.WordPress.2023-11-24.zip](https://github.com/WordPress/gutenberg/files/13456671/basic.WordPress.2023-11-24.zip)

**Comment by noisysocks** [comment]
Ran across this too. It's particularly annoying when creating a Navigation that links to category pages. You type in the exact name of the category (in this example, there's a category titled _Vegetarian travel_) and nothing shows up.

<img width="479" alt="Screenshot 2024-06-03 at 15 15 10" src="https://github.com/WordPress/gutenberg/assets/612155/7ebfa056-2422-4752-a345-e15e7b14d269">
