### ISSUE TITLE
Site Editor Template Usage

### ISSUE THREAD

**Issue by fraubungle** [WordPress/gutenberg#56549]
### Description

I have a issue when using the site editor and the correct templates not being used. I have set a static front page and created a page called front page. if I create a template within the site editor and select the front page option after when I look at the front page under pages in the site editor the template used is Pages. I get the same result if i create a front-page.html template. If I can to All Pages and the front page via the Pages menu in the WP admin the template there is set to front page. 

I registered a second page template called page-without-title and if I set that as the template to be used either in the site editor or on the page itself then that template is shown, but as soon as I set the template on the page to default (front page) then in the editor the template used is pages...

### Step-by-step reproduction instructions

1. Created Front Page (admin)
2. Set static front page (admin)
3. Created front page template (site editor)
4. View front page in site editor and template says Pages
5. View front page in page in admin and template says front page
6. change template in either site editor or admin to page without title
7. both site editor and admin shows template as page without title
8. change template in admin to default (no option in site editor to change to default or front page)
9. site editor shows template as pages and admin shows template as front page

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/695833/6d7c456b-d29b-45d9-8045-3ef398dea925

### Environment info

wordpress Version 6.4.1
Macbook and mac mini
Mac OS 14.2 and Mac OS 13.6.2
Safri, Chrome, Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hi @fraubungle - to clarify something - are you creating a new template in the Site Editor and then selecting the 'Front Page' type?

That template type is designed for use when _not_ having a static page set as the homepage - which explains the behaviour you're seeing. If your Reading Settings were set to 'Show Latest Posts' then the 'Front Page' template would be used for that.

In terms of having a specific Template to use for the page you've _named_ Front Page - you can set up a standard 'Page' template to use for that same as you did for 'page-without-title'.

**Comment by fraubungle** [comment]
Hi @jordesign 

Thank you for getting back to me on this. Yes my understanding was that the front-page.html themplate would act just like it did does with its php equivalent and frankly how home.html/php does. What also threw me was that when you go to all pages from the main admin panel and then to front page there you can see that the template used in that view is front page and you set that template by selecting default. 

Looking over the documentation there is no, 'well i could not find anything' mention of front-page.html but there is home.html

I think that these types of things really need to be communicated way more clearly and that it gets shown in different places within the ui also really confusing.

could you let me know what the difference is between home.html and front-page.html as I assumed that home was to be used when not having a static front page as I said above that is what is in the documentation and also was the behaviour of the old php template structure.
