### ISSUE TITLE
Gutenberg + CoAuthor Plus plugin creates many notices in the admin pages

### ISSUE THREAD

**Issue by xenobytezero** [WordPress/gutenberg#5654]
## Issue Overview
If Gutenberg plugin is active at the same time as the CoAuthor plugin, a large number of PHP Notices are shown throughout the backend. The most noticeable is in the post list.

## Steps to Reproduce (for bugs)
1. Install the following plugins
> Gutenberg 2.4.0
> CoAuthors Plus 3.2.2
2. Go to the All Posts page

## Expected Behavior
The post list is displayed as normal

## Current Behavior
Every post has the following notice above the Edit/Bin links

```
Notice: Object of class WP_Post could not be converted to int in C:\<project path>\wp-content\plugins\co-authors-plus\template-tags.php on line 7
```

## Possible Solution
The issue appears as the `is_coauthor_for_post()` template tag is expecting a `post_id`, and is instead getting a WP_Post object. This post ID is passed in from a `user_has_cap` filter hook, which extracts it from the `$args[2]` parameter.

This issue only appears if both plugins are active.

**Comment by danielbachhuber** [comment]
Thanks for the report, @xenobytezero.

This is addressed by #5863 and will be fixed in the next Gutenberg release.
