### ISSUE TITLE
Using a reserved(?) block attribute name should trigger an error

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#5656]
## Issue Overview

I added a new attribute to my block:

```
layout: {
	type: 'string',
	default: 'foo',
},
```

Whatever I tried it wouldn't receive the default value of `foo` and was automatically inserted into block comments as `layout: 'null'`.

After an hour of questioning my existence I find this:

https://github.com/WordPress/gutenberg/blob/33209b23886a912d7f5eab26db4b319715dbe09b/blocks/hooks/layout.js#L20-L24

## Expected Behavior

Please throw some sort of error message when using reserved attribute names.

**Comment by mtias** [comment]
We have dropped `layout` so closing this.
