### ISSUE TITLE
Distraction free does not toggle off breadcrumbs

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#56565]
### Description

When distraction free mode is toggled on and Prefereces > General > Display block breadcrumbs is also on, the block breadcrumbs perisist at the bottom of the editor.

### Step-by-step reproduction instructions

In the post or site editors,

1. Go to the dot menu in the top right corner
2. Click Preferences
3. Make sure General is selected
4. Toggle on Display block breadcrumbs
5. Close the preferences modal
6. Go to the dot menu in the top right corner
7. Click Distraction free
8. Notice the breadcrumbs still show

### Screenshots, screen recording, code snippet

![Screenshot 2023-11-27 at 18 22 09](https://github.com/WordPress/gutenberg/assets/107534/297754df-1ffe-4a42-b33b-c41c23f586a2)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by draganescu** [comment]
The main problem here is that the auto toggling of preferences to off to accomodate distraction free should naturally put them back to whatever value they had before when distraction free is toggled off.

As @mtias [noted](https://github.com/WordPress/gutenberg/pull/56295#issuecomment-1825742240) a similar issue is now visible since merging #56295 - the block toolbar remains fixed to the editor header even after exiting distraction free mode. This was happening from the inception of distraction free but now it's visible because the toolbar is also present in distraction free mode.

I'll investigate saving a snapshot to be restored of the affected prefs when DFM is toggled.

**Comment by richtabor** [comment]
Noting that distraction free does enable/disable breadcrumbs properly in the page editor (not the site editor).

**Comment by richtabor** [comment]
> As @mtias https://github.com/WordPress/gutenberg/pull/56295#issuecomment-1825742240 a similar issue is now visible since merging https://github.com/WordPress/gutenberg/pull/56295 - the block toolbar remains fixed to the editor header even after exiting distraction free mode. This was happening from the inception of distraction free but now it's visible because the toolbar is also present in distraction free mode.

I noted this as well. It's quite a bit disorienting. Almost feels like you're in an in-between state. 

https://github.com/WordPress/gutenberg/assets/1813435/fd603049-b8e0-4019-abb8-a043d8a11d6f

**Comment by draganescu** [comment]
I'll investigate to see if for now we coult just default to restoring defaults. It's still not great but it's more expected and defaults should be the most wide spread configuration.

**Comment by mtias** [comment]
We should also aim to animate it out like the header toolbar.
