### ISSUE TITLE
Perf tests: Playwright is downloading all the browsers

### ISSUE THREAD

**Issue by WunderBart** [WordPress/gutenberg#56588]
### Description

We're [installing Chromium dependency explicitly](https://github.com/WordPress/gutenberg/blob/4355204514b59a58974b1ed46e5b9a26a1615315/bin/plugin/commands/performance.js#L212) for the performance test runner, because it's the only browser we use there. Still, when those tests are being run for the first time in a fresh environment (like CI), the first thing that happens is that all other browsers are being downloaded as well:

```shell
> gutenberg@17.1.2 test:performance
> wp-scripts test-playwright --config test/performance/playwright.config.ts post-editor.spec.js

Downloading Firefox 118.0.1 (playwright build v1425) from https://playwright.azureedge.net/builds/firefox/1425/firefox-ubuntu-22.04.zip
Firefox 118.0.1 (playwright build v1425) downloaded to /home/runner/.cache/ms-playwright/firefox-1425

Downloading Webkit 17.4 (playwright build v1921) from https://playwright.azureedge.net/builds/webkit/1921/webkit-ubuntu-22.04.zip
Webkit 17.4 (playwright build v1921) downloaded to /home/runner/.cache/ms-playwright/webkit-1921
```

@swissspidy @kevin940726 @Mamaduka 

### Step-by-step reproduction instructions

Try running `npm run test:performance` in a fresh environment.

**Comment by swissspidy** [comment]
We could add a flag to the wp-scripts test-playwright command to not install browsers on the fly.

**Comment by Mamaduka** [comment]
> We could add a flag to the wp-scripts test-playwright command to not install browsers on the fly.

That or even allow passing browser dependencies explicitly.

We could also speed up the core e2e jobs since they are only testing with Chrome now.

The `wp-script` code, responsible for checking/installing browser - https://github.com/WordPress/gutenberg/blob/trunk/packages/scripts/scripts/test-playwright.js#L29-L42.

**Comment by WunderBart** [comment]
Trying something similar to the [suggested solution](https://github.com/WordPress/gutenberg/issues/56588#issuecomment-1829617013) in https://github.com/WordPress/gutenberg/pull/56594
