### ISSUE TITLE
When adding a new button declared as default, the style is not applied.

### ISSUE THREAD

**Issue by webexpr-dhenriet** [WordPress/gutenberg#56589]
### Description

I've disabled the default button styles.
I then created several button styles, including a default one (primary).
When I add a button, the style isn't applied, it's missing `is-style-btn-primary`, I have to click on the "primary" style for this to be added.

```js
wp.domReady( () => {

    wp.blocks.unregisterBlockStyle(
        'core/button',
        [ 'outline', 'fill' ]
    );   

    wp.blocks.registerBlockStyle( 'core/button', {
        name: 'btn-primary',
        label: 'Primaire',
        isDefault: true,
    });
    wp.blocks.registerBlockStyle( 'core/button', {
        name: 'btn-secondary',
        label: 'Secondaire',
    });
    wp.blocks.registerBlockStyle( 'core/button', {
        name: 'btn-outline-primary',
        label: 'Primaire bordure',
    });
    wp.blocks.registerBlockStyle( 'core/button', {
        name: 'btn-outline-secondary',
        label: 'Secondaire bordure',
    });
});
```

```php
function we_enqueue_gutenberg_editor_assets()
{
    wp_enqueue_script(
        'script-editor',
        we_get_js_url( 'editor.js' ),
        ['wp-edit-post', 'wp-blocks', 'wp-dom-ready', 'wp-hooks'],
        we_get_asset_version(get_stylesheet_directory() . '/assets/js/editor.js')
    );
    wp_enqueue_style(
        'style-editor',
        get_template_directory_uri() . '/style-editor.css',
        [],
        we_get_asset_version(get_stylesheet_directory() . '/style-editor.css')
    );
}
add_action( 'enqueue_block_editor_assets', 'we_enqueue_gutenberg_editor_assets');
```

### Step-by-step reproduction instructions

1 Add buttons
2 Add button

### Screenshots, screen recording, code snippet

[e2f7a918-bfd6-4d0d-9f1d-5d8aa872ec78.webm](https://github.com/WordPress/gutenberg/assets/62699215/4b078983-be69-4fec-aa5e-35b270e75c6c)

### Environment info

- Wordpress 6.4.1, hybrid custom theme (theme.json + PHP)
- Chrome
- Windows 10 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/38890 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

**Comment by webexpr-dhenriet** [comment]
@skorasaurus Thanks, I had indeed come across this issue but I thought it only concerned the block cover.
