### ISSUE TITLE
A way to let any one add custom Social Icons (social-link) variations

### ISSUE THREAD

**Issue by RadND** [WordPress/gutenberg#56595]
## What problem does this address?

so, wp's offical plugin directory forbids use of ANY company 's trademark ,right? And these trademark are usally there icon , right?

so if i made a plugin , this plugin add a variation of social icons , let's say  WeChat (or Steam). I can forseen it will only be used by myself because I can't get it listed on wordpress.org, and non-tech user don't search github usually. That's bad.

## What is your proposed solution?

idk, maybe it's possible for a 3rd party dev to make a plugin to curd social-link as key-value in admin's web page.but with no preset include (to fit the rules),it would still be pretty much useless compare to the effct making it.

**Comment by jordesign** [comment]
Thanks @RadND  - this is a great suggestion. If you check out https://github.com/WordPress/gutenberg/issues/19041 you'll see there's already some discussion and work on setting this up, so I'll close this issue in favour of that one.
