### ISSUE TITLE
Paragraph block: Deleting everything in a split paragraph does not result in the selecting the previous block

### ISSUE THREAD

**Issue by jhnstn** [WordPress/gutenberg#56614]
## Description

Writing flow test case [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) is failing the last step. 
After deleting everything in a split block and then deleting the block does not result in the previous block being selected.

## Step-by-step reproduction instructions

Follow [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004)

## Expected behaviour

The previous paragraph should be selected

## Actual behaviour

No blocks are selected

## Screenshots or screen recording (optional)

https://github.com/WordPress/gutenberg/assets/744755/011dc336-3a33-4390-8486-f14ccc32e8c5

## WordPress information
- WordPress version: latest
- Gutenberg version: latest
- Are all plugins except Gutenberg deactivated?  No
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Pixel 8
- Operating system: Android 14
- WordPress app version:  23.6

**Comment by jhnstn** [comment]
This has the same end result as https://github.com/WordPress/gutenberg/issues/56512 but with different initial conditions.

**Comment by fluiddot** [comment]
> This has the same end result as #56512 but with different initial conditions.

I think it's the same cause as #56512, so most likely [this PR](https://github.com/WordPress/gutenberg/pull/56496) will fix it. Hence, I propose to close it as it will be resolved when the betafix `1.109.1` is merged into `23.8`.

cc @geriux

**Comment by geriux** [comment]
> I think it's the same cause as #56512, so most likely [this PR](https://github.com/WordPress/gutenberg/pull/56496) will fix it. Hence, I propose to close it as it will be resolved when the betafix `1.109.1` is merged into `23.8`.

I agree! This should be fixed so we can close this one 👍
