### ISSUE TITLE
Semantics of Post Title in Code Editor differ from that in Visual Editor

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#56633]
In https://github.com/WordPress/gutenberg/pull/54718 the element used to render the Post Title when in "Code View" mode in the editor was changed to a `textarea`. This was to facilitate the usage of plaintext in the code view to expose HTML tags to the user.

This differs from the `<h1>` which is used for the title in the Visual Mode.

That said _both_ options expose as a role of `textbox` and have a label.

The question is, is there any accessibility regression here? Does it matter that the two do not match the _element_ even though they expose identical roles?

## Replication Instructions

- New Post
- Check semantics of the Post title and check it is accessible.
- Switch to Code View with ⇧⌥⌘M (shift + option + cmd + M) - or just use the editor options menu.
- Check semantics of the Post title and check it is accessible.

-------

Regarding accessibility, the title element has been changed from `h1` to the `textarea`. I tested it with a screen reader (NVDA) and it reads the placeholder "Add title", but I'm concerned that the semantics of the document have been lost.

_Originally posted by @t-hamano in https://github.com/WordPress/gutenberg/pull/56582#pullrequestreview-1752793566_

**Comment by jeryj** [comment]
The semantics that get exposed for both are the same. They are both considered a textbox with a label of "Add Title". The H1 there, I believe, is used for styling purposes so the editor and frontend site both use the same h1 CSS.
