### ISSUE TITLE
Docs: Interactivity API - Rename wp-effect to wp-watch

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#56641]
Update documentation at [Interactivity API Docs - API Reference](https://github.com/WordPress/gutenberg/blob/trunk/packages/interactivity/docs/2-api-reference.md) about **wp-effect → wp-watch**

**Comment by luisherranz** [comment]
Done as part of https://github.com/WordPress/gutenberg/pull/56764.
