### ISSUE TITLE
Block Theme Previews: Hide the "Looking for Template Parts?" warning banner

### ISSUE THREAD

**Issue by fushar** [WordPress/gutenberg#56668]
## What problem does this address?

When previewing a theme using the Block Theme Previews feature, a user can be "distracted" by the "Looking for template parts?" banner, when they are actually supposed to do more important things, like trying out Styles. This might be confusing for first-time users.

## What is your proposed solution?

Hide this banner from the Site Editor when BTP is in use, resulting in a "cleaner" experience:

|Before|After|
|-|-|
|<img width="811" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/f477c030-6314-4dec-bc38-a39052103485">|<img width="861" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/593bb5d1-98af-4cd6-bc2c-39b21fa24755">|

cc: @scruffian

**Comment by richtabor** [comment]
Yea, it doesn’t need to be there. We could probably remove the notice for 6.5 even, as it’s been there for two releases.
