### ISSUE TITLE
Gutenberg plugin enabled causes Polyang to now show langauges for template parts, menus, etc.

### ISSUE THREAD

**Issue by badg0003** [WordPress/gutenberg#56683]
### Description

I've noticed with the latest version `17.1.x` that when I go to translate my template parts using Polylang Pro I can no longer access the individual languages. Here's a sample of what I see within the editor:

![image](https://github.com/WordPress/gutenberg/assets/828140/fb8d2a22-f455-46f2-b790-6f41f159f665)

It's only when i disable the plugin that can once again view the languages:

![image](https://github.com/WordPress/gutenberg/assets/828140/a02af774-4ad4-4cbd-98b1-c102d40a6d73)

I'm not seeing any errors in the console.

### Step-by-step reproduction instructions

1. Enable Polylang and Gutenberg plugins
2. Go to Appearance -> Editor and select a template part, or anything really that can be translated
3. Flip to the Polylang sidebar

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Marc-pi** [comment]
Maybe Ask to the polylang team. They are working on a New release...

**Comment by jordesign** [comment]
Hi @Marc-pi  - I'm inclined to agree with the above comment - this will be something that the Polylang plugin needs to work on to make sure their plugin is still compatible. I'll close the issue on this end.
