### ISSUE TITLE
Font Library: Improve UX

### ISSUE THREAD

**Issue by mikachan** [WordPress/gutenberg#56688]
## What problem does this address?

We should improve the UX of the Font Library UI.

## What is your proposed solution?

Here is a list of suggested improvements:

- [ ] Adding a Select / Unselect all variants option (suggested by @jffng)
- [x] Report errors (installing, uninstalling, activating, etc) with specificity in the Font Library modal - handled in https://github.com/WordPress/gutenberg/pull/57688

**Comment by annezazu** [comment]
Some more items on my mind from the FSE Outreach program's last call for testing for consideration:
- [Font Library: consider making the library more discoverable](https://github.com/WordPress/gutenberg/issues/55179#top)
- [Font Library: adjust warning when a font is in use and is about to be deleted](https://github.com/WordPress/gutenberg/issues/55175#top)
- [Command Palette: add command to open fonts](https://github.com/WordPress/gutenberg/issues/54880#top)
- [Fonts: update loading visual with new progress bar component](https://github.com/WordPress/gutenberg/issues/54797#top)
- [Font Library: Consider clarifying which fonts are uploaded vs theme provided in drop down](https://github.com/WordPress/gutenberg/issues/55220#top)

**Comment by colorful-tones** [comment]
Another for Font Library UX consideration: [Font Library: Global Styles > Typography sidebar – group related font sources #58403](https://github.com/WordPress/gutenberg/issues/58403)

**Comment by colorful-tones** [comment]
I just wanted to note that I did [a small design exploration for converting font lists from the TabPanel to the Panel component](https://github.com/WordPress/gutenberg/issues/54431#issuecomment-1930416500), which would address many accessibility concerns. Alongside @afercia 's [callout about grouping font lists with related headings](https://github.com/WordPress/gutenberg/issues/58403#issuecomment-1932358501), it would significantly improve the overall Font Library modal experience.

I'm attaching images from the linked comments for posterity.

![302716781-3ab92307-7207-4566-91ac-ba45817d5393](https://github.com/WordPress/gutenberg/assets/405912/95f61b9f-7d1d-46fd-b97a-63ec4bb2db51)

![Screenshot 2024-02-07 at 12 02 13 PM](https://github.com/WordPress/gutenberg/assets/405912/13d34184-f207-40c7-b86e-6498d119f31a)

**Comment by getdave** [comment]
Are we at a point where this can be closed out?

**Comment by colorful-tones** [comment]
@getdave I think there are a series of issues that are on the 6.5 board that can likely get removed, but could potentially be worked on during the 6.5 cycle, and they're all related to the Font Library UX and a11y (accessibility). I would love to see these aggregated somewhere into an epic so that there is trust that they'll not be lost for continued discovery and dialogue (regardless of the targeted release). It seems this is on the Nice To Have list for https://github.com/WordPress/gutenberg/issues/55277 and that should suffice.

I'll remove from the board.

**Comment by creativecoder** [comment]
@mikachan Should we close this issue and track any further work in individual issues (and in https://github.com/WordPress/gutenberg/issues/60528)?

> Adding a Select / Unselect all variants option

This is being tracked in https://github.com/WordPress/gutenberg/issues/59704

**Comment by mikachan** [comment]
Thanks for the nudge, @creativecoder. Yeah, I think we're good to close this issue and track items separately and in the larger tracking issue (https://github.com/WordPress/gutenberg/issues/60528).
