### ISSUE TITLE
Add Radius Slider to Columns Block

### ISSUE THREAD

**Issue by daviesmediadesign** [WordPress/gutenberg#56692]
## What problem does this address?

There is no "Radius" slider for the "Columns" block inside the Gutenberg Block Editor. This slider exists for the "Groups" block, allowing designers to create rounded corners for backgrounds. With the current setup, Columns blocks only support square backgrounds or backgrounds with a square border. 

## What is your proposed solution?

Add a radius slider to the Columns block settings sidebar under the Styles Tab, Border section.

**Comment by Chetax** [comment]
@daviesmediadesign  can you share screenshot please

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/41345 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

Also note, the border radius is available for the columns block; but not for the individual columns  which is what https://github.com/WordPress/gutenberg/issues/41345 is proposing.

**Comment by skorasaurus** [comment]
![image](https://github.com/WordPress/gutenberg/assets/955351/886ca493-680f-4de0-ac56-da57bf4ef17e)

is a very crude example of applying the  border-radius for the outer columns block.
