### ISSUE TITLE
Query Loop displays "No results found." instead of post preview in the Editor, at the same time the frontend looks correct.

### ISSUE THREAD

**Issue by realthemes** [WordPress/gutenberg#56696]
### Description

On fresh Wordpress local setup just look inside editor of a official twentytwentyfour theme, the Query Loop are display "No results found." message instead of post preview, I clean up all cache in browser etc, and disable every plugin except gutenberg, and bug still presented.
*note, I add and publish 8 posts, they can be viewed on frontend

### Step-by-step reproduction instructions

1. On fresh Wordpress setup install Gutenberg plugin
2. Activate twentytwentyfour theme
3. Add a bit posts with title and content
4. Go to Editor and check what the Query Loop block are displays, it should display posts preview instead on "No results found." message

### Screenshots, screen recording, code snippet

![Screenshot 2023-11-30 181848](https://github.com/WordPress/gutenberg/assets/81107729/fe628045-3804-4d59-a7ae-c5aab26e4b8d)

### Environment info

WP 6.4.1, Gutenberg Plugin 17.1.3, twentytwentyfour theme
Google Chrome
Windows 11 Notebook

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I think this issue was resolved in #56439. This fix will ship as part of version 17.2 of the Gutenberg plugin. I'll close this issue, but if this problem still occurs with Gutenberg plugin version 17.2, I'd appreciate it if you could comment again.
