### ISSUE TITLE
Ability to Style Button Hover Colors for Gutenberg

### ISSUE THREAD

**Issue by daviesmediadesign** [WordPress/gutenberg#56691]
## What problem does this address?

There doesn't appear to be a way to customize the color of button text on hover using the settings available in the Block Editor or Site Editor Styles. You can style the button text, but not the button text on hover (not without custom CSS, that is). This includes when trying to customize the styling of the button block from within the Styles editor of the Site Editor. 

## What is your proposed solution?

Under Styles>Blocks>Button, add some kind of option under the "Color" section to change hover colors. For example, have "Text, Hover Text, Background, Hover Background." Or, when you click on "Text" to change the button's text color, there should be a tab labeled "Hover" where the hover color can be changed (same with the "Background" option). These settings should also be available inside the Block Editor when editing a single instance of a button (under the "Styles" tab of the Block Settings Sidebar under the "Color" section).

**Comment by talldan** [comment]
This is currently being tracked in the issue here - https://github.com/WordPress/gutenberg/issues/38277.

I'll close this one as a duplicate.
