### ISSUE TITLE
New lightbox feature breaks HTML validation

### ISSUE THREAD

**Issue by oldrup** [WordPress/gutenberg#56707]
### Description

Described in https://wordpress.org/support/topic/new-lightbox-feature-breaks-html-validation/?view=all#post-17243973

### Step-by-step reproduction instructions

Se above

### Environment info

WP 6.4.1; PHP 8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

The figure element is categorized as flow content and can have flow content _or_ figcaption element. Therefore, the div inside the figure element is allowed ([source](https://html.spec.whatwg.org/multipage/grouping-content.html#the-figure-element)).

I saw your forum post, what tools do you use to validate HTML?

**Comment by oldrup** [comment]
> I saw your forum post, what tools do you use to validate HTML?

w3.org

Sample report at https://validator.w3.org/nu/?doc=https%3A%2F%2Ftest.oldrup.dev%2Fwp64%2Fsample-page%2F

So, it might be that validator that is wrong? 🤔

**Comment by t-hamano** [comment]
My guess is that this is an issue on the validator side. For example, the validation results will vary depending on the position of the div.

❌ Invalid

```html
<!DOCTYPE html>
<html lang="">
<head>
<title>Test</title>
</head>
<body>
<figure>
  <div></div>
  <figcaption>This is caption</figcaption>
  <div></div>
</figure>
</body>
</html>
```

✅ Valid

```html
<!DOCTYPE html>
<html lang="">
<head>
<title>Test</title>
</head>
<body>
<figure>
  <div></div>
  <figcaption>This is caption</figcaption>
</figure>
</body>
</html>
```

✅ Valid

```html
<!DOCTYPE html>
<html lang="">
<head>
<title>Test</title>
</head>
<body>
<figure>
  <figcaption>This is caption</figcaption>
  <div></div>
</figure>
</body>
</html>
```

This issue was also [reported](https://github.com/validator/validator/issues/576) and closed in the `validator` repository, but I'm not sure if the fix is reflected in the web tools.

**Comment by oldrup** [comment]
That is a valuable troubleshooting @t-hamano. Thank you a lot! 🤘

I assume this is a wrong positive from the w3 validator and will give the native lightbox a try. It surely is a welcome addition to the block editor.

**Comment by t-hamano** [comment]
You're welcome. I would like to close this issue, but if you have any remaining issues, please feel free to comment.
