### ISSUE TITLE
Video block should gracefully transition to embed blocks

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#5671]
As a user, I shouldn't have to know that there are separate youtube, vimeo, and native video blocks.  All I want to do is put a video in my post. If I paste a youtube link in the "Use URL" box in the video block, it should JustWork™, without needing to find the embed block for the specific carrier.

This continues the goal of removing `“mystery meat” embed discovery`.

**Comment by mtias** [comment]
I thought we had a task for this.

**Comment by aaronjorbin** [comment]
I couldn't find one, but there are alot of tickets (145 to be exact).

**Comment by jeffpaul** [comment]
This seems related to #5620 and #4918 all as part of an issue with embeds JustWorking™ (subsidiary of JustWork™).

**Comment by designsimply** [comment]
Closing in favor of #6824 because it has a bit more detail and solving it covers the same request.
