### ISSUE TITLE
Enable `ch` as a unit for dimensions

### ISSUE THREAD

**Issue by dabowman** [WordPress/gutenberg#56722]
## What problem does this address?
Currently (afaik) Gutenberg doesn't support the CSS `ch` unit. This is incredibly useful for defining block width in responsive layouts and global styles. MDN defines ch as "The advance measure (width) of the glyph "0" of the element's font." It's more useful than other relative units like `em` because it not only considers the `font-size` property in it's calculation but it also considers the `font-family` property. It's particularly useful for limiting the width of elements to a max character count—something that makes typography easier and gives designers more intuitive controls. 

## What is your proposed solution?
add `ch` to the list of units you can declare in your theme for dimensions.

**Comment by skorasaurus** [comment]
As far as I can tell, ch isn't supported (at least in the docs at https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/#spacing ) but I made a crude example and it appears to work ?
![image](https://github.com/WordPress/gutenberg/assets/955351/435a7f97-8b02-41bf-bca8-d48661b6d9dd)

```
    "spacing": {
      "padding": true,
      "margin": true,
      "units": ["px", "em", "rem", "vh", "vw", "ch"]
    },

```

![image](https://github.com/WordPress/gutenberg/assets/955351/bee13762-bbaf-4676-83a1-ed8a5f2fee5c)

**Comment by t-hamano** [comment]
As far as I've researched, I think all the units defined by [this variable](https://github.com/WordPress/gutenberg/blob/ded792b18f4dfb7a295cd27d4511e62be3bd7e15/packages/components/src/unit-control/utils.ts#L14) can be used, including the `ch` unit.

Therefore, I would like to close this issue.
