### ISSUE TITLE
Separate the font format in the (accordion block editor)

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#56739]
## What problem does this address?

There is currently no option to distinguish the title of the accordion details block from its text. For example, changing the font size of its title changes also the font size of linked text. 

<img width="1440" alt="Screenshot 2023-12-04 at 18 26 14" src="https://github.com/WordPress/gutenberg/assets/147336669/8853454d-5b45-4d98-825d-dfd1469f7fcf">

## What is your proposed solution?

Adding an option to the **details** block editor (to set different font formats for the title and its linked text) 🙏

**Comment by jordesign** [comment]
Hi @Rodi9999  - thanks for the enhancement request - at the moment it's a little low on details of what you mean - could you please share a little more?

**Comment by ghost** [comment]
> Hi @Rodi9999 - thanks for the enhancement request - at the moment it's a little low on details of what you mean - could you please share a little more?

Hi @jordesign,

Thank you for the reply!

Sorry, I had provided the details in the post but due to not removing specific symbols, the content was not showing up. I have updated it. Thank you!

The feature is not urgent and the block is already fine without it, but I think it would help me improve the visualization of the block.

Again thanks

**Comment by Rodi9999** [comment]
Sorry I have just noticed that Gutenberg already _has_ this feature. It is accessible through the navigation block (list view of the blocks).

**Comment by ghost** [comment]
Sorry I have just noticed that Gutenberg already has this feature. It is accessible through the navigation block (list view of the blocks).
