### ISSUE TITLE
When accessing the pattern collection, in the collection modal menu, does not show the complete collection categories. The category scrollbar get cut-off causing the last one or 2 category not being displayed.

### ISSUE THREAD

**Issue by alanjacobmathew** [WordPress/gutenberg#56740]
### Description

When the enduser access the patterns collection, inside the popup modal, the scrollbar on the left panel, meant for the pattern categiries get, cut-off nearing the end, casuing incomplete pattern category collection. It is usually the 'uncategorized' that get hidden and inaccessible.

### Step-by-step reproduction instructions

Make sure there are pattens saved without selecting any category.
Open post editor -> Add pattern -> Explore All Patterns
Scrollbar on the left panel get cutoff

### Screenshots, screen recording, code snippet

![gqUdHR9uCK](https://github.com/WordPress/gutenberg/assets/33965848/608de5d7-10ac-4665-abbe-e06ba2be227b)

![xplorePattern](https://github.com/WordPress/gutenberg/assets/33965848/4393a6ae-e380-4c26-9498-2e15a1a94bed)

### Environment info

`WP 6.4.1`, `Gutenberg Version 17.1.4` `Theme: 2024`
Chromium & Firefox: Windows

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report. #56787 will fix this problem.
