### ISSUE TITLE
Editor changes the template on the fly

### ISSUE THREAD

**Issue by facu-gamond** [WordPress/gutenberg#56766]
### Description

Hey, channel! Have some of you experienced this issue with the editor? it’s like when I go to edit some template it automatically changes the template for the homepage. This bug can be avoided if I open the editor and wait until the first preview is fully loaded before editing some templates.
Context:
* Acf to build blocks
* Kinsta test server

https://github.com/WordPress/gutenberg/assets/88891792/d8644665-6fa2-4ba9-8071-adc09eacb9a6

### Step-by-step reproduction instructions

1. Open the editor
2. Quickly open a template

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/88891792/cc17efeb-4050-4cd4-af8d-26d75c9b46b0)

### Environment info

- WordPress 6.4.1
- FSE Theme
- Kinsta test server
- ACF 6.2.3 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
hi @facu-gamond - this does indeed sound odd. Do you have the same behaviour take place if you switch to a default theme like Twenty Twenty-Four whilst also having all plugins disabled?

**Comment by youknowriad** [comment]
Going to close this issue as it's not clear how to reproduce. Please let me know if you're still experiencing this and provide detailed instructions (theme maybe) if needed. Thank you
