### ISSUE TITLE
Compiled comments cause a 50% increase in file size

### ISSUE THREAD

**Issue by amdrew** [WordPress/gutenberg#5677]
## Issue Overview

Comments in the .scss files located at `edit-post/assets/stylesheets` are being repeated 25 times each when the `gutenberg/blocks/build/style.css` css file is compiled. In addition, they don't provide any context since they are all stacked.

<img width="752" alt="screen shot 2018-03-18 at 10 17 34 pm" src="https://user-images.githubusercontent.com/52581/37564406-3b192d60-2afa-11e8-90fa-9c0e77cef82b.png">

(note the `1 of 25 matches` above)

This is caused by:

1.) The .scss files being made globally available across the project (very clever btw!):
https://github.com/WordPress/gutenberg/blob/master/webpack.config.js#L41

And 2.) The fact that the comments will compile into the final .css file:

```
/**
 * Breakpoints & Media Queries
 */
```

It seems the simplest solution (for now) would be to change the multi-line comments to use forward slashes which won't compile:

```
//
// Breakpoints & Media Queries
//
```

Not as pretty, but at least the comments won't get compiled and we'll save 50% in file size. After the comments are removed it will reduce the filesize from `44KB` to `22KB`.

## Steps to Reproduce (for bugs)

Using latest master branch:

1. View the `gutenberg/blocks/build/style.css` file in your browser and scroll down to see the repeated blocks of comments.

## Expected Behavior

For the comments to only output once each, in the correct locations. Or as this issue proposes, the comments to not render at all.

## Possible Solution

Use forward slashes for the multi-line comments.

**Comment by amdrew** [comment]
PR: https://github.com/WordPress/gutenberg/pull/5678

**Comment by mtias** [comment]
We've discussed tweaking the build setup to exclude these, but I like the simpler approach here regardless.

**Comment by aduth** [comment]
I'm not able to reproduce this _when building for production_. 

Do you see this in the output of the CSS file after `npm run build`?

If this only affects development, it seems like a minor concern.

**Comment by amdrew** [comment]
@aduth Sorry, I should have clarified. That's correct, it only occurs in the unminified dev version. The minified build version is 👌

**Comment by aduth** [comment]
Then, to be frank, does it really matter?

To me, if the comments are removed during minification anyways, it seems like it avoids the need to try to educate developers on the SCSS commenting syntax and distinction from [otherwise standardized commenting guidelines](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#commenting).

**Comment by amdrew** [comment]
@aduth It certainly doesn't matter at this point but I still feel it's something that should be fixed when time permits. CSS comments shouldn't be repeated unnecessarily, even if they are only seen by a developer.

It seems there are 3 options:

1. Prevent comments from being outputted by changing the type of multi-line comment (proposed PR)
2. Prevent comments from being outputted via the build set up, and keep the original comments (proposed by @mtias above)
3. Output the comments into the unminified script, but only once each, in the correct location for context.

**Comment by aduth** [comment]
Sourcing common variables will definitely need a rethink, as we currently define them in `edit-post` even though they're not exclusively editor-related. I have a feeling this may touch on how the variables are imported into the SASS loader, which hopefully could resolve the duplication.

I imagine the comments may be useful for debugging CSS source in development, so not sure we'd want to drop them altogether.

**Comment by danielbachhuber** [comment]
For production, I definitely think minimizing file size is a priority. For development, I think there are other priorities to focus on.

Thanks for opening the conversation, @amdrew
