### ISSUE TITLE
Navigation Block: needs a way to specify which navigation menu data to use

### ISSUE THREAD

**Issue by speshiou** [WordPress/gutenberg#56789]
## What problem does this address?

My env: 
* WordPress 6.4
* Theme Twenty Twenty-Four

Typically, there is a Navigation Block in the header, and another or more in the footer. However, when adding a new Navigation Block to the page layout, the navigation menu data of the block in header will be used. There is no way to specify or create a new menu data to apply, unless you delete the current menu in the block settings.

<img width="1332" alt="截圖 2023-12-05 下午10 15 49" src="https://github.com/WordPress/gutenberg/assets/6083887/32380e12-3313-4919-a629-a5d70536ca84">

## What is your proposed solution?

Most of websites have multiple navigation block. It'd be better to have a block setting to specify which navigation menu data to apply to the Navigation Block. 

My current workaround is to copy the Navigation Blocks from the built-in footer pattern.
<img width="1007" alt="截圖 2023-12-05 下午10 23 07拷貝" src="https://github.com/WordPress/gutenberg/assets/6083887/3b585ef8-8789-4c5c-bad1-35ea19cdc1c7">

**Comment by hanneslsm** [comment]
> There is no way to specify or create a new menu data to apply, unless you delete the current menu in the block settings.

Not sure if I got this right, but you can have multiple navigations. Click on the three dots in the inspector to create a new one or select from existing.
<img width="297" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/16d83f60-3466-40a6-b82a-2eb6f88b33a5">
And, of course, you can manage them via `…/wp-admin/edit.php?post_type=wp_navigation`

**Comment by speshiou** [comment]
> > There is no way to specify or create a new menu data to apply, unless you delete the current menu in the block settings.
> 
> Not sure if I got this right, but you can have multiple navigations. Click on the three dots in the inspector to create a new one or select from existing. 

That's exactly what I was looking for. Thank you very much!
