### ISSUE TITLE
Issue with AccessPress Social Share Plugin

### ISSUE THREAD

**Issue by tlctara** [WordPress/gutenberg#5679]
## Issue Overview

This is not an issue with Gutenberg, but wanted to notify of conflict with another plugin and Gutenberg.

When activated, the plugin **AccessPress Social Share Plugin 4.3.6** causes autosave and saving/updating of posts with Gutenberg to fail. I have reported on the plugin page as well.
https://wordpress.org/plugins/accesspress-social-share/

Screenshot of error: https://cl.ly/qF1W

I am running Gutenberg 2.4.0

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Possible Solution

Plugin author has been notified.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
Thanks for the ticket. WordPress 5.0 has been released. Do you have news from the plugin authors?

In the meantime, I suggest that you install the classic editor plugin to use this plugin.
