### ISSUE TITLE
Post title: JS TypeError when selecting text with the keyboard

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#5680]
To reproduce:
- type something in the post title
- use the keyboard and Shift + arrow keys to make a selection in the entered text, e.g.:

![screen shot 2018-03-18 at 16 05 05](https://user-images.githubusercontent.com/1682452/37567393-a2798542-2ac6-11e8-8450-3590a040a351.png)

Observe your browser's console: several errors:
`Uncaught TypeError: Cannot read property 'closest' of undefined`

**Comment by afercia** [comment]
Clarification: happens when selecting from right to left, e.g.:
- Shift + Left arrow
- Shift + Up arrow

**Comment by peterwilsoncc** [comment]
Quick testing notes:

* The error occurs in `editor/components/writing-flow/index.js#getClosestTabbable()`. 
* `getClosestTabbable()` returns false for each item in `focusableNodes`
* `lodash.find()` returns undefined as a result.

**Comment by ajitbohra** [comment]
Tested on master / v3.2 was not able to reproduce this.
