### ISSUE TITLE
Users can scroll off the bottom of the block editor into a forbidden void when searching in the inserter

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#56811]
### Step-by-step reproduction instructions

1. Open the site editor (not sure if it happens in the post editor)
2. Open the inserter
3. Enter the search term 'List'

Expected: The inserter scrollbar expands, but the canvas scroll bar isn't affected
Actual: The canvas scrollbar expands allowing users to scroll down into empty space

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/677833/2b0bca73-dd48-4daf-942c-96740f7bbfae

### Environment info

Tested against latest Gutenberg trunk (d1d0b2ab17edcedb16714ce5d07aa118fdfa3b58)
Mac OS / Brave

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by colorful-tones** [comment]
Confirmed in `Chrome Version 120.0.6099.109 ` with latest Gutenberg trunk 9879b85b822aba8454d83ba4faaeed48f20bfd73

**Comment by colorful-tones** [comment]
Also, this happens in the post editor as well. It is not isolated to the Site Editor.

**Comment by colorful-tones** [comment]
This is definitely browser based and bug exists in `Safari Version 17.2 (19617.1.17.11.9)` too, but does not affect `Firefox 120`. I'm doing some debugging to try and decipher what has changed in Blink/webkit browsers, while accounting to make sure all will work nicely on mobile (iOS). I think I've traced it down to an overflow issue. There is this note from Safari 17.2 Release Notes, which feels like a solid lead: https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes#Scrolling. 

I'm feeling like it is pointing to styling here: https://github.com/WordPress/gutenberg/blob/trunk/packages/interface/src/components/interface-skeleton/style.scss#L45-L137

**Comment by colorful-tones** [comment]
I think I've got a fix in place https://github.com/WordPress/gutenberg/pull/57127, but it could use some thorough cross browser testing. I only had time to fix and verify in Chrome 120.

**Comment by andrewserong** [comment]
Thanks for fixing this one up @colorful-tones! 🎉
