### ISSUE TITLE
Pasting URL over text does not create link if URL copied from editor

### ISSUE THREAD

**Issue by sandymcfadden** [WordPress/gutenberg#56826]
### Description

When you have an unlinked URL in the editor and you copy it as text you are not able to then paste it over other text to create a link. Instead of the text being turned into a link it is replaced with the copied URL text.

If the URL is copied from another source like a text editor, or the address bar of the browser this works as expected. It only seems to happen when copying from the editor.

### Step-by-step reproduction instructions

1. Type a URL as text into the editor eg. `https://wordpress.org`
2. Select that text
3. Copy it
4. Type new text into the editor eg. `WordPress`
5. Select that new text
6. Paste the URL you copied

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1326294/60113771-53fc-48f9-84d7-e555408b93ce

### Environment info

Tested on
WordPress version: 6.4.1
Gutenberg version: 17.1.3
Theme: Twenty Twenty-Four
Browsers: Latest Chrome, Latest Firefox
Device: macOS Sonoma

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Just noting that I've confirmed this behaviour in testing.

**Comment by AAloshine-scottlogic** [comment]
Hello, I was wondering if i could be assigned this issue as my first open source contribution?

**Comment by jordesign** [comment]
Hey @AAloshine-scottlogic  - sure thing! For what it is worth - you can always submit a PR without being assigned - but I've made sure you _are_ assigned to this one now.

**Comment by AAloshine-scottlogic** [comment]
@sandymcfadden can i ask if you're using edge when you encountered this issue?

**Comment by sandymcfadden** [comment]
> @sandymcfadden can i ask if you're using edge when you encountered this issue?

@AAloshine-scottlogic Do you mean the browser? I had tried Firefox and Chrome, but hadn't tested in Edge. 
If you mean version of code I was testing using the Gutenberg plugin version: 17.1.3

**Comment by AAloshine-scottlogic** [comment]
<img width="846" alt="image" src="https://github.com/WordPress/gutenberg/assets/125262433/675e2684-97ea-48e9-adfd-48e58587ac5e">
when i've tried to run the project using npm run start i keep on getting this compilation error. Is this a normal occurrence?

**Comment by Mamaduka** [comment]
Unable to reproduce the bug with WordPress 6.6.1, with and without the Gutenberg plugin (v19.0) active and testing using Chrome browser.

@sandymcfadden, can you confirm if the issue has been resolved?

## Screencast

https://github.com/user-attachments/assets/f411dba1-1890-47b2-bad1-a0d9402a7e36

**Comment by Mamaduka** [comment]
@annezazu, if you have time, do you mind also confirming this one? 🙇

**Comment by annezazu** [comment]
Unable to reproduce either with 6.6.1 and GB 19.0! Closing out. 

https://github.com/user-attachments/assets/492ce5c5-0e2d-4076-b464-1558e913b84f

**Comment by sandymcfadden** [comment]
Yes, as @annezazu and you noticed, this looks like it is working as expected now. Thank you!

**Comment by Mamaduka** [comment]
Thanks for confirmation, @sandymcfadden!
