### ISSUE TITLE
Refactor embed block as a single block with options that enable embed types on selection

### ISSUE THREAD

**Issue by gravnetic** [WordPress/gutenberg#5682]
I would like to see a single embed block.  The amount of visual weight that the embed is getting right now could be used in so many more effective ways.

![better-embed-options](https://user-images.githubusercontent.com/475331/37568059-a733fd5a-2a95-11e8-8c20-88453baa1784.jpg)

I am disabling all these which is a significant amount.

![gutenberg-embeds-must-die](https://user-images.githubusercontent.com/475331/37567940-c1d7c1f2-2a93-11e8-8beb-fbde880e8247.jpg)

**Comment by notnownikki** [comment]
One of the goals of Gutenberg is that supported embeds are easily discoverable. To go to a single embed block, we'd need to look at the NUX around discovering what embeddable content is supported.

**Comment by karmatosed** [comment]
In this case as we have the blocks and they are useful let's close this. We absolutely could look at discoverability and refine but for now lets close.
