### ISSUE TITLE
Create a more generic "Change Block Type" option

### ISSUE THREAD

**Issue by gravnetic** [WordPress/gutenberg#5683]
I am using the convert post to blocks and it is wonderful!  I would like to change the fist image in the case to a cover and it would be more efficient if there was an option to change block type.

![change-block-type](https://user-images.githubusercontent.com/475331/37568285-b910125e-2a98-11e8-8565-c5d1bd28ca00.jpg)

**Comment by karmatosed** [comment]
I think this could be a future idea, however not something to add in version one of Gutenberg. I am closing but moving this to our ideas project so it doesn't get lost, thanks.

**Comment by chrisvanpatten** [comment]
@karmatosed I think there's actually another issue here (aside from a generic "change block type" idea) shouldn't there be an option to convert an image block to a cover image block?

**Comment by karmatosed** [comment]
@chrisvanpatten totally see that one as a good issue to split out thanks.
