### ISSUE TITLE
Change Edit Image Behavior to open the image you are working on and add a button to change image.

### ISSUE THREAD

**Issue by gravnetic** [WordPress/gutenberg#5684]
Right now the edit image option opens the media manager.  My expectation was that the edit image would allow me to edit the image I am working on.  I would like the Edit image to open the WordPress default image editing page.  Then add another option that is replace image.

**Comment by markjaquith** [comment]
We use "Edit" and the pencil icon for links, as well, so it's consistent with that. I don't know if we have a "change" or "select new" icon concept. "Edit" is flawed here, but it has precedent.

**Comment by karmatosed** [comment]
I am closing this as it is consistent with what we have right now and links have iterated a little. We can always reopen if we need.
