### ISSUE TITLE
Gutenberg wp-block-code adds <br> tags for empty lines within <pre><code>

### ISSUE THREAD

**Issue by Digiover** [WordPress/gutenberg#56855]
### Description

When adding a code snippet using the code block, <br> HTML tags are added to the source instead of respecting EOL (end of line) like CRLF/CR.

### Step-by-step reproduction instructions

1. Go to Dashboard > Posts > Add New Post
2. Choose the code block
3. Write code...
4. See the result after publishing or preview

### Screenshots, screen recording, code snippet

The result HTML code is (when using "Copy Element" in Chrome DevTools):

```
<pre class="wp-block-code"><code>PS C:\Users\Jan&gt; Measure-Command { Test-NetConnection -ComputerName smtp.gmail.com -Port 25 }
<br>
<br>Days              : 0
<br>Hours             : 0
<br>Minutes           : 0
<br>Seconds           : 0
<br>Milliseconds      : 349
<br>Ticks             : 3498166
<br>TotalDays         : 4.04880324074074E-06
<br>TotalHours        : 9.71712777777778E-05
<br>TotalMinutes      : 0.00583027666666667
<br>TotalSeconds      : 0.3498166
<br>TotalMilliseconds : 349.8166</code></pre>
```

![image](https://github.com/WordPress/gutenberg/assets/8005150/25a75981-8126-4a31-ab36-0e1c3f2359f5)

### Environment info

WordPress 6.4.2
Gutenberg 17.2.0

Verified with multiple WordPress instances, different syntax highlighting plugins and without. Problem first noticed in Gutenberg version 16.9.0.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Digiover** [comment]
Addendum

What I meant with

> Problem first noticed in Gutenberg version 16.9.0.

is that 16.9.0 was the first version I noticed markup issues with code blocks (EOL completely missing, everything came on line line). Now with 17.2.0 the `<br>`'s are added withing `<pre><code>`

**Comment by t-hamano** [comment]
Thanks for the report.

I was also able to confirm this symptom, but I think this behavior is an intentional change.

The PR related to this change is #55999, which mentions:

> Now all rich text values serialise the same way, with line breaks always serialising to the HTML BR tag.

I don't think this behavior is a bug, so I'd like to close this issue, but if there's anything I've missed, please comment.

**Comment by Digiover** [comment]
Thank you for your reply @t-hamano . Can't say I'm happy with it though...

Apparently, it's allowed to use `<br>` in `<pre>` according to the HTML specifications (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre#technical_summary, https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#phrasing_content) but it's changes like these that break sites. Since Gutenberg 16.9.0 -for as far as I remember- my site's code blocks are all messed up, without any indication why.

And now I still have to edit every post to fix code blocks, because I guess this isn't getting reversed.

**Comment by t-hamano** [comment]
@Digover

Is the code block you're using from Gutenberg core? If so, I think this should be fixed on Gutenberg's side.

**Comment by Digiover** [comment]
> @digover
> 
> Is the code block you're using from Gutenberg core? If so, I think this should be fixed on Gutenberg's side.

Yes, it's the Gutenberg core code block. But I have had "syntax highlighting" plugins installed, so there is no telling what is in my database now :) I removed those plugins a while ago.

Just tested it quickly: I do have to edit a code block. First image is how a random posts code block looks, second image is after editing (I added EOL's until `</filter>`, but pressing Update fixed the entire block. Caveats:

1. Other blocks remain unchanged (image 3)
2. only opening the "edit post" page en pressing "Update" doesn't do anything to fix the block. I have to change the block. See image 4, which is image 3 after inserting an space.

![image 1](https://github.com/WordPress/gutenberg/assets/8005150/ee5533e3-05ea-4e5b-99cd-7ca26f135bd2)
![image 2](https://github.com/WordPress/gutenberg/assets/8005150/04d7ff58-96aa-4f12-9ccf-2f07ea4d616f)
![image 3](https://github.com/WordPress/gutenberg/assets/8005150/ae25f40a-53f6-47c4-adff-c34b6ed73101)
![image 4](https://github.com/WordPress/gutenberg/assets/8005150/992b3e50-abbc-494f-bdd8-e8c904df1385)

/edit: fixed image order

**Comment by t-hamano** [comment]
@Digiover 

Sorry it took so long to reply. I haven't yet had enough time to look into this issue in detail, but I'm wondering if it's an issue with the code block itself, or with a compatibility issue with the plugin extending the code block. I would like to keep this issue open until there is clarity.

**Comment by t-hamano** [comment]
I would like to add this issue to the WP6.5 project board as it might affect many developers.

**Comment by Digiover** [comment]
Yeah great, @t-hamano . Anything I can do to help / assist? I've been out of the WP dev business quite some time but can always test or something.

**Comment by t-hamano** [comment]
Sorry for getting in touch with you so late. It turns out that the problem you reported has a much larger impact than I expected. A summary of the problem is summarized in #58659.

**Comment by t-hamano** [comment]
I think #58659 covers this issue, so I'd like to close it.
