### ISSUE TITLE
Custom gradient only saves with new name

### ISSUE THREAD

**Issue by samxmunoz** [WordPress/gutenberg#56865]
### Description

When creating a custom gradient, it only saves if you update the name from "Color 1".

### Step-by-step reproduction instructions

1. Create a custom gradient - **don't** rename it
2. Click "done"
3. Gradient is not saved.

<img width="272" alt="Screenshot 2023-12-07 at 8 12 04 AM" src="https://github.com/WordPress/gutenberg/assets/43501707/9c53587c-93d8-42bc-9d1a-2bf68d344ffa">

1. Create a custom gradient - **name it**
2. Click "done"
3. Gradient is saved.

<img width="268" alt="Screenshot 2023-12-07 at 8 11 55 AM" src="https://github.com/WordPress/gutenberg/assets/43501707/9c910e89-9dee-4dc7-bc0b-4f7f5c74ad84">

### Environment info

Twenty twenty four theme.
With and without Gutenberg installed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
I can replicate this.


https://github.com/WordPress/gutenberg/assets/6458278/ecd3e33d-4270-4b8e-82fa-1a45507990f6


I did a bit of debugging and I think the value is being cleared inside a `useEffect` hook PaletteEdit component:

https://github.com/WordPress/gutenberg/blob/3ad117e075dc6bab30a40d7f39e5455b5b66748b/packages/components/src/palette-edit/index.tsx#L301-L301

See where `onChange` is called - the temporary elements are being removed from the `newElements` array, so `onChange` will be fired with `undefined`.

```js
	useEffect( () => {
		return () => {
			if (
				elementsReference.current?.some( ( element ) =>
					isTemporaryElement( slugPrefix, element )
				)
			) {
				const newElements = elementsReference.current.filter(
					( element ) => ! isTemporaryElement( slugPrefix, element )
				);
				onChange( newElements.length ? newElements : undefined );
			}
		};
		// Disable reason: adding the missing dependency here would cause breaking changes that will require
		// a heavier refactor to avoid. See https://github.com/WordPress/gutenberg/pull/43911
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [] );
```

`onChange` sets the globalStyles userConfig (hook [here](https://github.com/WordPress/gutenberg/blob/3ad117e075dc6bab30a40d7f39e5455b5b66748b/packages/block-editor/src/components/global-styles/hooks.js#L91-L91)) and is passed down from the GradientsPalettePanel component: 

https://github.com/WordPress/gutenberg/blob/3ad117e075dc6bab30a40d7f39e5455b5b66748b/packages/edit-site/src/components/global-styles/gradients-palette-panel.js#L103-L103

I ran out of time to debug, so not sure why it doesn't affect the color preset panel yet...

**Comment by ramonjd** [comment]
Actually, it just occurred to me what's going on.

Gradient elements contain both color and gradient properties, therefore they'll always return true for the `isTemporaryElement` test if the color property is default (#000):

https://github.com/WordPress/gutenberg/blob/3ad117e075dc6bab30a40d7f39e5455b5b66748b/packages/components/src/palette-edit/index.tsx#L264-L264

Hoping this PR will fix it:

- https://github.com/WordPress/gutenberg/pull/56896
