### ISSUE TITLE
Same queryId for all Query Loops

### ISSUE THREAD

**Issue by scrobbleme** [WordPress/gutenberg#56902]
### Description

We are migrating a site with multiple CPT to a Gutenberg-based theme and are using multiple Query Loops within single template.

Unfortunately, all loops have the same queryId attribute. This i.e. happens when duplicating the Loop-Block

**Problems** with this:

* Paging is not working, as every loop is paged
* (scrolling directly to the loop is not working, as all share the same id)

Personally, I would prefer to enable the ID field on the block and allow any Id, as there is no need to just allow a numeric one.

### Step-by-step reproduction instructions

1. Create a single template with a query loop block
2. Duplicate the query loop block
3. → you can see in the HTML, that both have the same ID.

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/504835/81f31f6b-7453-45ce-a923-940d7b0f534d)

### Environment info

* Latest WordPress
* Latest Gutenberg-Plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by scrobbleme** [comment]
> Hi, This issue has gone 30 days without any activity. This means it is time for a check-in to make sure it is still relevant. If you are still experiencing this issue with the latest versions, you can help the project by responding to confirm the problem and by providing any updated reproduction steps. Thanks for helping out.

It is still problem ;)

**Comment by skorasaurus** [comment]
experiencing this on GB 18.5 

occurs not just in templates; but even a post (of post type page) that has displays multiple query loops on it. 

However, I was able to work around the issues @scrobbleme described by manually changing the queryid of one of the loops in the code editor.

**Comment by skorasaurus** [comment]
There is a duplicate issue of it at https://github.com/WordPress/gutenberg/issues/46079 although that issue has an ambiguous issue title so keeping this one open 

I found another issue writing about this at https://github.com/WordPress/gutenberg/issues/55823 ; so I'm closing this and you can follow its progress by subscribing to that issue.

**Comment by skorasaurus** [comment]
I found this issue also reported at https://github.com/WordPress/gutenberg/issues/55823 with a clearer title and you can follow its progress there.
