### ISSUE TITLE
Synced patterns are unsynced when added via drag and drop

### ISSUE THREAD

**Issue by grantgeard** [WordPress/gutenberg#56917]
### Description

When adding patterns to the editor via the block inserter, synced patterns that are added to the editor by clicking on the pattern are added as synced patterns. The same pattern added to the editor by dragging and dropping is added as an unsynced pattern.

Since the pattern itself is a synced pattern, I would expect it to be synced regardless of how it is added to the editor. This is also easily missed if you do not have the document overview open.

### Step-by-step reproduction instructions

1. Create a synced pattern
2. Add the synced pattern to the page by dragging and dropping from the block inserter into the editor
3. Add the same synced pattern to the page a second time by clicking the pattern in the block inserter
4. Note that the pattern that was added via drag and drop is not synced

### Environment info

Tested on WordPress v6.4.2 using Twenty Twenty-Four v1.0 as well as with a custom theme. Tested both with and without the Guternberg plugin (v17.2.0).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thank you for your report. I was able to reproduce it too.

https://github.com/WordPress/gutenberg/assets/54422211/fc7183e3-c614-4d18-97c9-1f708113f803
