### ISSUE TITLE
Post Template block produce double or duplicated CSS selector .wp-block-post-template.wp-block-post-template { ... }

### ISSUE THREAD

**Issue by realthemes** [WordPress/gutenberg#56929]
### Description

Post Template block produce double or duplicated CSS selector
```
.wp-block-post-template.wp-block-post-template { 
    ...
}
```
or
```
.wp-container-core-post-template-layout-1.wp-container-core-post-template-layout-1 {
    grid-template-columns: repeat(3, minmax(0, 1fr));
}
```

It’s also not clear about `.wp-container-core-post-template-layout-1` class, I have 3 columns, but `.wp-container-core-post-template-layout-1` class with the number 1, I’m not sure, this is an error or not

### Step-by-step reproduction instructions

1 Install clean and fresh Wordpress
2. Go to Editor and add any Query Loop variation with grid layout to the page
3. Go to frontend and check CSS selectors that Post Template block are produced

### Screenshots, screen recording, code snippet

![Screenshot 2023-12-10 173353](https://github.com/WordPress/gutenberg/assets/81107729/9287404d-6945-49e6-92f5-72b17c15add9)

### Environment info

Wordpress 6.4.2, Gutenberg 17.2.0, TwentyTwentyFour theme
Windows 11, Google Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jacobcassidy** [comment]
This may be related to the duplicate classes in #49835.

**Comment by realthemes** [comment]
@jacobcassidy, now I understand, yes, I think this method is used in different places

**Comment by realthemes** [comment]
Double CSS selectors are still present, but this may be a feature, not a bug, as mentioned by [jacobcassidy](https://github.com/jacobcassidy).
