### ISSUE TITLE
Add gutenberg_can_edit_post filter

### ISSUE THREAD

**Issue by mattoperry** [WordPress/gutenberg#5692]
## Issue Overview
Allow conditional loading of the editor based on post ID by introducing a new filter, `gutenberg_can_edit_post`.

## Expected Behavior
`gutenberg_can_edit_post` would work almost identically to `gutenberg_can_edit_post_type`, except that it would filter on the ID, not the type.

## Current Behavior
Currently the filter `gutenberg_can_edit_post_type` provides a way for plugins to enable or disable Gutenberg by `post_type`.  A more general and equally useful filter would be one that would allow for enabling or disabling by ID.  The decision to use or not use Gutenberg could thereby be conditional based not only on the ID itself but also anything immediately retrievable from the ID, such as post date.  A common use case might be for sites that want to preserve old editor behavior for their archive but begin using Gutenberg for new posts now.

## Possible Solution
Pretty simple code change ... I'll submit a PR in a moment :)

**Comment by designsimply** [comment]
Closed #8346 as a duplicate and noting it also has an open pull request at #8347.
