### ISSUE TITLE
Image aspect ratio 1:1 is in fact output as 1; failing HTML validation; no option custom settings.

### ISSUE THREAD

**Issue by oldrup** [WordPress/gutenberg#56938]
### Description

When choosing the Square 1:1 aspect-ratio in Gutenberg, the markup actually outputs ` aspect-ratio: 1;`  which, [while totally valid](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) causes [HTML validation to fail](https://github.com/validator/validator/issues/1406)

This appears to be a HTML validator bug, but a Gutenberg problem, as there is currently no way to enter a custom aspect ratio (and why not, btw - 16:10 anyone?)  and by that allowing to enter 1:1, which the validator is ok with.

We can point fingers all we want, blaming the validator, but we false positives leads to people ignoring validating errors, and that hurts accessibility.

Proposed workaround: Update Gutenberg to actually output what it says on the box: `1:1` instad of just `1`

### Step-by-step reproduction instructions

Insert an image.
Set aspect-ratio to Square 1:1
![image](https://github.com/WordPress/gutenberg/assets/17141205/c802d3ce-8031-4215-8b10-957ac5600102)
Validate code.
![image](https://github.com/WordPress/gutenberg/assets/17141205/75433e53-34ea-42b0-9559-903735dcb209)
![image](https://github.com/WordPress/gutenberg/assets/17141205/c84ea34d-c25b-4790-80eb-9ab4abeab3b1)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by oldrup** [comment]
According to MDN, the `aspect-ratio: 1` is, in fact, [valid syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio), an indication that the [W3C markup validator](https://validator.w3.org/) is returning a false positive.

That might lead to the decision, not to change to output of Gutenberg, as the validator is "to blame".

In my opinion, we should meet in the middle, outputting `"1 / 1"` instead of just `"1"`, making everyone happy. It's more intuitive to understand, it's what it says in the editor drop down, and those 3 extra bytes can hardly be considered bloat ;)

Screenshot: demo on MDN
![image](https://github.com/WordPress/gutenberg/assets/17141205/79414e73-09d5-443b-8aa4-414157882117)

**Comment by oldrup** [comment]
Hey. Just checking in. Yes, this markup still causes issues with the W3C HTML validator:

![image](https://github.com/WordPress/gutenberg/assets/17141205/0dda684f-b700-463a-a3d5-3520d19c9e09)

![image](https://github.com/WordPress/gutenberg/assets/17141205/cfb1a362-4314-4089-a63c-d0d3902257bd)

Live URL where this can be tested: https://test.oldrup.dev/wp64/2024/02/11/aspect-ratio-est/

Again, the solution could be writing the aspect ratio as `1 / 1` (easy fix) or let editor enter a custom aspect ratio (bit hard but solves other problems as well)

**Comment by nagatomi** [comment]
I have done a verification test and found no errors.

WordPress ver 6.6
Gutenberg ver 18.8

[aspect_ratio_test-html.txt](https://github.com/user-attachments/files/16323392/aspect_ratio_test-html.txt)

**Comment by kevin940726** [comment]
I've also done a verification test and it seems like the validator fixed the false positive.

![image](https://github.com/user-attachments/assets/bf8ab623-46c8-4afb-9fa1-1cdd2d6b76c1)

I think we can close this now. Feel free to reopen if the issue persists!
