### ISSUE TITLE
Fix Shortcode—Markdown conflicts

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#5695]
Spawned from discussion in #4944.

## Issue Overview

By their respective syntax, Markdown and WordPress shortcodes are prone to conflict with one another. This is particularly visible in the examples below.

### Links

When pasting the following:

```
This contains an [awesome] link to something. This here is even [better][awesomer].

[awesomer]: http://example.org
```

the ideal reconciliation would be as follows:
1. `[awesomer]` is the identifier for a reference-style link
1. `[better]` is the wrapped text for said link
1. thus, let Markdown handle and convert the pair `[better][awesomer]` to a link (to `https://example.org`)
1. `[awesome]` is a standalone tag with no link attached to it
1. thus, let Gutenberg treat it as a shortcode — which for standalone shortcodes means converting to a shortcode block, and for inline shortcodes means leaving it untouched

### Escaping shortcode contents

When pasting the following:

```
[my_shortcode]hello, _there_.[/my_shortcode]
**oh**, [another_shortcode]hello, _there_.
```

the ideal reconciliation would be as follows:
1. `[my_shortcode]` is recognized as a shortcode with opening and closing tags and containing the string `hello, _there_.`
1. thus, don't perform any Markdown conversion on the tag itself and on its contents
1. `[another_shortcode]` is recognized as being a shortcode and not a link, but it is assumed self-closing
1. thus, no escaping is due, and the fragments `**oh**, ` and `hello, _there_.` will be rendered as `<strong>oh</strong>, ` and `hello, <em>there</em>.`, respectively.

## Possible Solution

This comment of mine https://github.com/WordPress/gutenberg/pull/4944#issuecomment-364292287 points to a Gist offering a working solution to get started.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
A lot of things changed since this issue was opened. Is it still valid?

**Comment by mcsf** [comment]
The only thing I could see as an enhancement would be paste-time support for referenced links, as opposed to inline links. For example:

```
Some text with [a link][1] and
another [link][2].

[1]: http://example.com/ "Title"
[2]: http://example.org/ "Title"
```

Aside from that, overall support seems pretty good, defaults are sane, and I don't think the issue surfaces at all as a priority. Will close.
