### ISSUE TITLE
Dataviews: Make preview part of title field display in Table layout

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#56976]
Preview / Featured image is currently given it's own column/cell in table layout:

<img width="677" alt="Screenshot 2023-12-12 at 11 38 41" src="https://github.com/WordPress/gutenberg/assets/846565/4ff75092-d654-405a-9008-581f879c432d">

This creates an unnecessarily large gap between the preview and the title. It would be good to try making the preview display a part of the title field:

<img width="512" alt="Screenshot 2023-12-12 at 11 40 16" src="https://github.com/WordPress/gutenberg/assets/846565/49c1326f-38e7-4ef2-8037-4c481c1b7111">

**Comment by oandregal** [comment]
For table, we don't declare what's the "media field". So far, we haven't given it special treatment, so we didn't need to.

One way to implement this issue would be to:

- set the "featured image" as the media field for the table layout (it's already declared as such for the other layouts)
- render the media field next to the primary field
- do not render a separate column for the media field

**Comment by jameskoster** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/58012
