### ISSUE TITLE
Post Editor: Requires default white background 

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#56981]
### Description

If a theme does not define a background color, you will see a black background in the Post Editor, making the text almost invisible. This issue does not occur on WP6.4.2 with the latest Gutenberg disabled.

The Site Editor applies a white background as a fallback. Like the Site Editor, the Post Editor also requires a white background as a fallback.

Similar PRs have been submitted in the past.

- #54534
- #46314

### Step-by-step reproduction instructions

- Enable Emptytheme. This theme does not define a background color in theme.json.
- The Post Editor should have a black background color.
- The Site Editor should have a white background color.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/fdfffc72-ba04-4f10-8e95-cb17fcb2b19f

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
I think maybe the background color for the `.edit-post-visual-editor` was introduced here: https://github.com/WordPress/gutenberg/pull/50361

@talldan what do you think about perhaps making the default background color of the iframe.editor-canvas `$white`?

I think it still achieves what the original PR set out to do?

<img width="1132" alt="Screenshot 2023-12-22 at 3 44 58 pm" src="https://github.com/WordPress/gutenberg/assets/6458278/70069a4e-ad1c-4742-be6d-4480a7a6aa21">

**Comment by talldan** [comment]
> I think maybe the background color for the .edit-post-visual-editor was introduced here: https://github.com/WordPress/gutenberg/pull/50361

Not something that I introduced, I modified to a slightly different shade in that PR.

I don't really know much of the background (ahem) of the background colors, so not sure I can lend good advice here. I think I did notice there were a couple of elements that had background colors, but I decided to tread lightly in that PR!

**Comment by ramonjd** [comment]
Ah, apologies. Thanks for the context though!
