### ISSUE TITLE
DateTimePicker: Localize the order of month, day and year

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#57007]
## What problem does this address?

The current `DateTimePicker` displays the date in the order "month, day, year" or "day, month, year", depending on the `is12Hour` prop.

![datetimepicker-en](https://github.com/WordPress/gutenberg/assets/54422211/c502be7a-012e-48ed-bed9-6c1b86c4f81f)

The year is always at the end, but in Asian languages such as Chinese and Japanese, the date is always written in the order of year, month, and day, regardless of whether they use 12-hour notation or not.

Therefore, in the Post Editor, the publish date and the date displayed by the `DateTimePicker` component do not match, causing confusion.

![ja](https://github.com/WordPress/gutenberg/assets/54422211/617923fd-3350-4267-a5e8-d5786a832f02)

## What is your proposed solution?

I'm thinking of making the `DateTimePicker` component consider the language when rendering the year, month, and day. For example, WordPress core seems to control the order of input fields by passing them through [a translation function](https://github.com/WordPress/wordpress-develop/blob/5eef2bbb2a476fc3f94f7d7c2d89ff01b9b74f82/src/wp-admin/includes/template.php#L837-L869).

As shown below, in the post list quick edit panel, you can see that the order of  month, day and year changes depending on the language.

### English

![quick-edit-en](https://github.com/WordPress/gutenberg/assets/54422211/268be5c8-8c0f-4b9e-a08b-a1859a73d507)

### Japanese

![quick-edit-ja](https://github.com/WordPress/gutenberg/assets/54422211/ae54b19f-38af-45d8-b00d-2ed20c8daf77)

**Comment by carstingaxion** [comment]
This would even be nice for german translations as well (AT, CH, DE and their formal variants), because in German the day comes first, before month and the year at the end.

DAY MONTH YEAR

**Comment by ramonjd** [comment]
Great idea. Most of Europe uses DD/MM/YY, also New Zealand and Australia. 👍🏻

**Comment by t-hamano** [comment]
Thanks for the feedback! I'm working on a PR to fix this issue.

**Comment by t-hamano** [comment]
I noticed that this issue was already discussed in #38221
