### ISSUE TITLE
Social Icons block: Update the Medium logo

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#57064]
## What problem does this address?

Currently, the Social Icons block includes an old version of the Medium logo, which was used between 2015 and 2017. The current logo has been in use since 2020.

<img width="1440" alt="Frame 20" src="https://github.com/WordPress/gutenberg/assets/8181091/2a46aadb-4cf5-43c2-82c2-23a5d42a25a5">

## What is your proposed solution?

Update the Social Icons block to include the current version of the Medium logo symbol. It can be found [in the Medium logo usage guidelines](https://medium.design/logos-and-brand-guidelines-f1a01a733592).

**Comment by colinduwe** [comment]
I updated the icon in PR https://github.com/WordPress/gutenberg/pull/57081 I used the Medium brand guidlines spacing which I'm not keen on now that I see it in place. I think I'd remove at least of bit of the white space so it's closer in apparent size to the other icons.

**Comment by colinduwe** [comment]
<img width="253" alt="Screenshot 2023-12-14 at 12 22 21 PM" src="https://github.com/WordPress/gutenberg/assets/2152870/1347a547-52e1-4fae-b285-83f555422a6c">
<img width="290" alt="Screenshot 2023-12-14 at 12 22 41 PM" src="https://github.com/WordPress/gutenberg/assets/2152870/c3233951-e8d1-4880-ac23-7c732c97b319">
