### ISSUE TITLE
Inconsistent tooltips for block options control

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#57078]
We have the block options available within list view and within the block toolbar, but the tooltips are inconsistent across both. 

I propose we use "Options" for both. 

![CleanShot 2023-12-14 at 13 50 02](https://github.com/WordPress/gutenberg/assets/1813435/4d35c0dc-b4c4-4e85-9582-c4ca1a4e314f)
![CleanShot 2023-12-14 at 13 50 22](https://github.com/WordPress/gutenberg/assets/1813435/81a2c522-33ec-4200-9196-77d9d89c457a)

**Comment by hbhalodia** [comment]
Hi @richtabor, I hope you are doing good. I have tried to make it consistent. Can you please take a look on this PR - https://github.com/WordPress/gutenberg/pull/57213.

Thanks.

**Comment by richtabor** [comment]
I left a note asking for a11y feedback to double-check we're good to make them consistent.

**Comment by jeryj** [comment]
That code was touched by @alexstine, so I would tend to leave it as is. I can see the rationale for using Options as the tooltip and I can see why it's useful to have the tooltip more explicitly named. I dug around for the rationale behind the decision but couldn't find any.

@alexstine, do you have a preference around using "Options" vs "Options for [block type]" in the list view options button?

**Comment by alexstine** [comment]
I do not think "Options" alone in the list view is enough because if you navigated down the right side of the grid, you'd have no idea which options menu you were opening. Unless I'm missing something?

Thanks.
