### ISSUE TITLE
Data views: Show total count in menu item

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#57072]
In the Patterns page, each view (pattern category) has an associated count:

<img width="346" alt="Screenshot 2023-12-14 at 16 22 10" src="https://github.com/WordPress/gutenberg/assets/846565/8cb62d04-7879-462c-8e45-48b9f19913c2">

It would be nice to bring this UI detail to other views, e.g.:

<img width="374" alt="Screenshot 2023-12-14 at 16 21 32" src="https://github.com/WordPress/gutenberg/assets/846565/6a81022c-36b8-49cf-86b6-ea7acc603cce">

**Comment by finitelydope** [comment]
Can you explain the issue a bit more?

**Comment by jameskoster** [comment]
Sure. In the Pattern management sidebar each category is represented by a menu item. Inside each menu item is a count indicating how many patterns there are in the category. 

I'd like to bring the same count to the `DataViewItem` component. Then, when you visit page management each view (e.g. "All", "Drafts", "Trash") will communicate how many pages it contains without having to visit it directly.

**Comment by jarekmorawski** [comment]
In some views it may make sense for menu items to be drilldowns, which means we'll need to display an additional chevron like in the top-level nav. Could we position the count next to the item name to make room for icons, buttons, and other signifiers on the right?

Proposal from another issue: https://github.com/WordPress/gutenberg/issues/61437#issuecomment-2098036777

**Comment by jameskoster** [comment]
I suspect we'll get to this some time before we add sub-category support. For now it may make sense to use the current placement, and revisit that detail when it comes to implementing subcategories.

**Comment by Souptik2001** [comment]
Hi @jameskoster ,

I have raised a [PR](https://github.com/WordPress/gutenberg/pull/62028) for this issue. Can you please review this as per your convinience.
