### ISSUE TITLE
Shadow: create / edit shadows in the global styles

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#57100]
## What problem does this address?

This is a sub task of #44651

With current implementation (in #44651), plugin gives four preset shadows and user can add more presets using `theme.json` and they appear in the global styles and site editor.

As a next step, add ability to edit or to create a shadow from the editor.

## What is your proposed solution?

Following is the suggested design.

https://github.com/WordPress/gutenberg/assets/846565/7aefcd92-5840-4452-9cf1-0a4f5b118671

Find more discussion related to this [here](https://github.com/WordPress/gutenberg/issues/44651#issuecomment-1634439550)

**Comment by madhusudhand** [comment]
@jasmussen @richtabor I have following thoughts on the editing experience for the shadows.

**Current state:** 
Shadows are available in global styles and block settings and both use a common UI component to show the list of core presets and theme presets.

<img width="566" alt="image" src="https://github.com/WordPress/gutenberg/assets/1935113/767f8b9d-12d1-4ad5-8d03-9157e60da53e">

From the conversation [here](https://github.com/WordPress/gutenberg/issues/44651#issuecomment-1634439550), the new UI should have options to create or edit a shadow, but it is not clear where this new UI belong.

Are you suggesting to make the same panel (as above) editable, or make it a separate component?
I am thinking better place for it would be in the global style settings as follows. My thoughts are based on color palette editing / creation experience.

<img width="283" alt="image" src="https://github.com/WordPress/gutenberg/assets/1935113/6d162a42-38fd-4261-a51b-eb9bcb917d1c"> <img width="283" alt="image" src="https://github.com/WordPress/gutenberg/assets/1935113/d7157e12-5187-4884-bcae-c32472e16138">

Please share your thoughts.

**Comment by jasmussen** [comment]
I think @jameskoster or @SaxonF may have had a hand in some of those more recent shadow design tools (which look promising!) so I'd appreciate their input. 

That said, I don't see global styles having a top level item called _Shadows_. There may be an aditional space for the increasing amount of controls that don't fit in Typography, Colors, and Layout. But how to structure that may be best informed by #47369.

**Comment by jameskoster** [comment]
I could potentially see an 'Effects' section where you're able to manage shadows, filters, duotone, and similar styles. Though I would agree that preset management in global styles needs some general design attention.

**Comment by jasmussen** [comment]
I think "Effects" was recently suggested by @richtabor for something similar, but not sure if that's the right word either. Worst case, could be Shadow & Border to match the panel.

**Comment by madhusudhand** [comment]
Created #60706 to explore the ideas around shadows editing experience. It is inspired from color palette and addresses the following.

1. Categorizes `default`, `theme` and `custom` shadows
2. default and theme shadows are editable, but their names cannot be changed (should they?)
3. New shadows cannot be added under default or theme shadows.
4. Only custom section allows to shadows to be added and edited.

#### Following is the initial UI

Editing experience of default/theme shadows.

<img src="https://github.com/WordPress/gutenberg/assets/1935113/5e367daf-8ae9-49e3-8c9c-14c207f884a2.gif" width="500" />

Editing experience of custom shadows.

<img src="https://github.com/WordPress/gutenberg/assets/1935113/e54e51c8-acc0-4d6a-9eda-efe692773f79.gif" width="500" />

### Problems / Questions

Since a shadow can be a combination of individual shadow strings (ex: value for default preset `outlined` has two shadow strings `6px 6px 0px -3px rgba(255, 255, 255, 1), 6px 6px rgba(0, 0, 0, 1)` together becomes final shadow),
editor should have an option to add multiple shadows within a shadow.

Should this panel have tab layout within, each tab for one sub shadow?
<img width="245" alt="image" src="https://github.com/WordPress/gutenberg/assets/1935113/20e06ee9-e36c-463c-b0a1-7385398611e2">

I am sure it is not the best ideas and not implemented in the [draft PR](https://github.com/WordPress/gutenberg/pull/60706). It picks, only the first part of the shadow for now.

Also, this initial exploration doesn't include a `color picker` for the shadow.

@WordPress/gutenberg-design @richtabor Please suggest UI for the complete workflow.

**Comment by jameskoster** [comment]
Nice work so far, it's exciting to see progress on this. 

The thing that stands out most here is the preview UI, this one:

<img width="279" alt="Screenshot 2024-04-15 at 15 15 51" src="https://github.com/WordPress/gutenberg/assets/846565/1d65851b-186e-4efb-8cdf-4e89f86b40db">

Both in the block inspector, and in global styles, it doesn't work very well imo. In the block editing context, you can see a better, more accurate preview on the canvas, and in global styles they are not interactive, so we could go ahead and show the itemgroup UI, this one:

<img width="281" alt="Screenshot 2024-04-15 at 15 17 53" src="https://github.com/WordPress/gutenberg/assets/846565/90969ee3-3fe0-40fe-9068-b2bb46a98e7e">


> editor should have an option to add multiple shadows within a shadow

For this feature to scale, and for us not to have to redesign it in the near-term, this detail feels important to me. Here's a mockup of how adding / editing a custom shadow could work:


https://github.com/WordPress/gutenberg/assets/846565/7aefcd92-5840-4452-9cf1-0a4f5b118671




[Figma prototype to click through](https://www.figma.com/proto/5204fWmQ45vjtzUOVhpWI7/Shadows?page-id=0%3A1&type=design&node-id=1-607&viewport=827%2C680%2C0.32&t=5oNAcE4qguYB2367-1&scaling=min-zoom&starting-point-node-id=1%3A607&mode=design).

* Clicking the `+` instantly creates a shadow
* Clicking the shadow drills down to the edit interface (similar to editing Elements in the Typography panel)
* Itemgroup in the drilldown lists all shadows
  * Initial shadow cannot be deleted
  * Clicking a shadow opens details in a popover
  * Additional shadows can be added by clicking the `+`
* Ellipsis menu allows you to rename, duplicate, or delete the shadow

What do y'all think?

---

A couple of small details I noticed in the PR:

* Missing a 'Reset shadows' action for theme/system shadows
* 'Done' button is mis-aligned with title.
* Remove buttons do not work
* System shadows should not be remove-able
* There's a double-stroke between buttons in itemgroup

**Comment by madhusudhand** [comment]
@jameskoster Thanks for the designs. They look great and addressing all the issues.

I have a question on color selection. How would you propose the color selection in the following design?

![image](https://github.com/WordPress/gutenberg/assets/1935113/49947112-c322-4271-a265-1a4fcdb6784b)

I assume it would be the similar experience such as text color selection panel. Can you confirm?

![image](https://github.com/WordPress/gutenberg/assets/1935113/1e4e02ea-2ce3-45de-b9ad-dbcca672a919)

> A couple of small details I noticed in the PR:
    Missing a 'Reset shadows' action for theme/system shadows
    'Done' button is mis-aligned with title.
    Remove buttons do not work
    System shadows should not be remove-able
    There's a double-stroke between buttons in itemgroup

Sorry that I did not give attention to the detailed styles in the first iteration as I was aiming to bring up something quickly. These issues should be addressed along with the proposed designs.

**Comment by jameskoster** [comment]
> I assume it would be the similar experience such as text color selection panel. Can you confirm?

That's correct, yes. The UI should be the same :)

**Comment by jameskoster** [comment]
A potential alternative popover design;

<img width="998" alt="Screenshot 2024-05-01 at 17 26 28" src="https://github.com/WordPress/gutenberg/assets/846565/110d3284-d46d-4607-afe7-8ad18e70fe98">

* Drop shadow / Inset shadow option now a segmented control for single-click switching.
* Added a light-source control for manipulating X and Y position together.

**Comment by madhusudhand** [comment]
@jameskoster New design looks great. I have taken part of it in the first iteration. 
Could you please review the latest changes from here #60706. 
Also, posted [few questions](https://github.com/WordPress/gutenberg/pull/60706#issuecomment-2090435348) in the PR, please advise on the same.
