### ISSUE TITLE
Shadow: enable shadow for more blocks

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#57103]
## What problem does this address?

As of Gutenberg 17.3, only a button block supports shadow feature. Add support to more blocks.

## What is your proposed solution?

Enable the shadow support to following blocks.

- [x] Button — ready for review in https://github.com/WordPress/gutenberg/pull/57654
- [x] Cover — Ready for Review in https://github.com/WordPress/gutenberg/pull/61883
- [x] Image
- [ ] Group
- [x] Column and Columns

Enable for more blocks based on the feedback.

**Comment by annezazu** [comment]
With Column, Columns, and Image support added, I'm going to assume this can be removed from 6.5 with GB 17.7RC1 shipped today. Happy to add back if needed though.

**Comment by colinduwe** [comment]
Here's a PR to add shadow support to the Post Featured Image Block
https://github.com/WordPress/gutenberg/pull/59616

**Comment by markhowellsmead** [comment]
Was there an explicit decision made to exclude the group block this time around? It would seem to be one of the most logical container blocks to include in the first launch. It would be good to understand and communicate the reasoning by only including particular blocks when adding features which make sense globally.

**Comment by annezazu** [comment]
Yes! There was an explicit decision made as you can see in this PR: https://github.com/WordPress/gutenberg/pull/57982 TLDR: more testing is needed.

**Comment by markhowellsmead** [comment]
Thanks for the reply, Anne. I can see that testing is needed from that but it’s unclear what issues require more extensive testing than any of the other blocks which now have support. Is the implementation of the control to the group block more complicated than on other containers? Is there any testing I can do which would help?

**Comment by vcanales** [comment]
> Is the implementation of the control to the group block more complicated than on other containers?

This is more or less it. The group and cover block would require changes in the block markup, such as additional wrappers, to make sure that the shadow is rendered correctly and in accordance with the blocks border style. It's not necessarily more complicated, but additional markup wrappers have the potential to introduce regressions down the line.

**Comment by markhowellsmead** [comment]
Thanks for the explanation. Is the necessity because of multiple box shadows? How is that different from a column block?

**Comment by colorful-tones** [comment]
Hi folks,
We are only one week away from the Beta 1 cut-off date for [WordPress 6.6](https://make.wordpress.org/core/6-6/). This issue hasn’t seen any movement in a while, so we (the editor triage leads of the 6.6 release) have decided to remove it from the [WordPress 6.6 Editor Tasks project board](https://github.com/orgs/WordPress/projects/179/views/1).

**Comment by markhowellsmead** [comment]
The question remains unanswered: why does the addition of _box-shadow_ require additional HTML elements?

**Comment by vcanales** [comment]
> @markhowellsmead The question remains unanswered: why does the addition of box-shadow require additional HTML elements?

When I initially enabled support for the cover block, there were inconsistencies between what was seen in the editor and what was in the frontend. In particular, the border radius was not being respected by the shadow. I've tried to enable support again without any modifications to the cover block itself, and it seems to be working fine now — no idea what changed!

PR: https://github.com/WordPress/gutenberg/pull/61883

**Comment by madhusudhand** [comment]
With the introduction of the shadow to cover block, marking this issue as complete.
Shadow will be enabled in future for Group block and may be other blocks based on feedback from the community.
