### ISSUE TITLE
Shadow: add shadow in block settings (site editor)

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#57101]
## What problem does this address?

Add the shadow component in block settings in the site editor. With current implementation, it is only possible to choose/add shadows to blocks only from the global styles.

Adding shadow in the site editor enables specific blocks to have shadows.

## What is your proposed solution?

Proposed UI

![image](https://github.com/WordPress/gutenberg/assets/1935113/aac876a4-cab7-422b-acb1-04faf4c9a211)

## Parent issue

#44651

**Comment by caseymilne** [comment]
That looks good, looking forward to be able to declare it through block/supports.
