### ISSUE TITLE
Audio and Video "Edit Button"

### ISSUE THREAD

**Issue by GeekZebre** [WordPress/gutenberg#5712]
## Issue Overview
When we click on the "edit button" (in BlockControls ) on the video and audio block,
we must have to click the button "Use Url" to go out 'editing' mode if we don't want to modify the media.

## Steps to Reproduce
1. Click "Edit Button" in BlockControls 
2. Try to go out 'editing' mode without modify the media : possible only by cliking "Use Url" button

## Possible Solution
When the block go out selected, return to no edit mode
or
Add a cancel button. 

## Related Issues and/or PRs
https://github.com/WordPress/gutenberg/issues/5456

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by GeekZebre** [comment]
A solution to don't have "Edit Mode" : 
What do you think ?

It can be applied on audio block and video block !

![removemedia](https://user-images.githubusercontent.com/30160793/37737612-869d3748-2d54-11e8-9634-f36c0bcc319e.gif)

**Comment by karmatosed** [comment]
Could we go back a little to what you are trying to achieve here? I want to be sure I am on the same page. You want to edit without having to go into the media, is that correct?

I think that is one thing but I see you're also bringing in a lot of extra options under 'or' we probably want to focus on one thing at a time.

**Comment by GeekZebre** [comment]
In this gif, I present my vision of adding an remove media in a block.

I do same as adding and removing in gallery block.
It's to have the same behaviour.

And : now, if we want to change media, we must : 
 - remove block and create a new one
 - or click on 'Edit Button' to replace media. But, we can't have the 'Use Url' possibility.

Personaly, as user, I prefer remove media and adding a new one to replace media.

And.

Yes, in this gif, I have add 'or' in the placeholder (and change button label).
It's a personal vision to explain to the user what he can do and how.
But, this is just text I propose. 

Also.
In the goal of 'unify' code, I have created a generic placeholder for the media (image, video and audio for now). It's this placeholder I use in the gif.
But, I think I can't do a PR because I work on a copy of image block and not on the original image block.
It's a personnal work method. And, there are a lot of french comment everywhere because it's not a clean code yet. 
But, if you want, I can still do a PR for my not clean work.

**Comment by karmatosed** [comment]
Let's close this issue and focus on https://github.com/WordPress/gutenberg/issues/5456, that has some progress and we're crossing over here. Thanks.
