### ISSUE TITLE
When saving meta data, withDispatch/useDispatch is overwritten by value in Custom Fields Panel

### ISSUE THREAD

**Issue by richardeast84** [WordPress/gutenberg#57137]
### Description

When saving meta data from a React component, either withDispatch or useDispatch are available to help with this task. Unfortunately, if the user has the Custom Fields panel open, the value there will overwrite any work done by withDispatch/useDispatch.
Simply, the problem can be worked around by closing the Custom Fields panel, however there may be reasons that a user wishes to leave it open. I hope to find a more robust solution/workaround that is inline with user expectation.

### Step-by-step reproduction instructions

1. Install a plugin that uses meta fields within Gutenburg
2. Go to Add Post
3. From Preferences, add the Custom Fields panel and reload the page
4. Initiate a change to a meta field
6. Save Draft - the meta value will save correctly
7. Reload the page
8. Change and save the meta field 
9. Save Draft - the value will not be updated as it will be overwritten with the value from the Custom Fields plugin.

### Screenshots, screen recording, code snippet

Screenshot of the plugin file with isolated issue:
<img width="401" alt="Meta_Test" src="https://github.com/WordPress/gutenberg/assets/15229405/e8e0971a-2091-49af-bcea-35a90597ba82">

The issue occurs when using both withDispatch or useDispatch

```
    const { editPost } = useDispatch('core/editor');
    const updateMeta = (metaKey, metaValue) => {
        editPost({ meta: { [metaKey]: metaValue } });
    };
```

```
const applyWithDispatch = withDispatch((dispatch) => {
    const { editPost } = dispatch('core/editor');
    return {
        setMetaValue(newMeta) {
            editPost({ meta: newMeta });
        },
    };
});
```

### Environment info

WordPress 6.4.1, Chrome Version 120.0.6099.71, Mac OSX Ventura
WordPress 6.1.4, Safari Version 16.6, Mac OSX Ventura

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I hope [this document](https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/plugin-sidebar-0.md#note) will help you with any issues you may have when the Custom Fields panel is open.

**Comment by richardeast84** [comment]
> I hope [this document](https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/plugin-sidebar-0.md#note) will help you with any issues you may have when the Custom Fields panel is open.

Brilliant, thank you for that info!

When first registering the meta key in PHP, prefixing the key with _ and providing an 'auth_callback' function is a suitable solution.

```
register_post_meta('post', '_meta_test', array(
    'show_in_rest' => true,
    'single' => true,
    'type' => 'string',
    'auth_callback' => function() {
        return true;
    }
));
```
