### ISSUE TITLE
Reusable FontSettings and Theme customization

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#5714]
Follow up tasks from https://github.com/WordPress/gutenberg/pull/5269.

Allow themes to specify the set of font size values. (Right now it defaults to pixels, but we might extend this.)

```php
// $font_sizes = array(
//    'small' => 14,
//    'regular' => 16,
//    'large' => 36,
//    'larger' => 48,
// };

$font_sizes = get_theme_support( 'editor-font-sizes' );
```

Allow themes to disable custom font sizes (the slider and arbitrary input).

```php
get_theme_support( 'disable-custom-font-sizes' );
```

Create reusable block component for font settings:

```
import FontSettings from '@wordpress/blocks/font-settings';
```

Here we could see whether we prefer a `FontSize` component or a full `FontSettings` with props for dropCap support, etc. Maybe `FontSize` scales better (like `ColorPalette`?).

**Comment by rchipka** [comment]
Related to #6651

**Comment by forsvunnet** [comment]
@mtias @jorgefilipecosta It doesn't look like this issue has been fully solved. The theme support to remove custom font sizes doesn't look to have been implemented.
```
get_theme_support( 'disable-custom-font-sizes' );
```

Is there another way to remove/disable the font size control?
