### ISSUE TITLE
Using useClickAway with gutenberg components

### ISSUE THREAD

**Issue by BroFromSpace** [WordPress/gutenberg#57177]
I am creating a custom block using gutenberg editor and react components. I try to use `useClickAway` functionality from [usehooks](https://usehooks.com/useclickaway) package. I tried to apply it to Popover, however it's not working. I am not sure if it's the right way to this, so I would really appreciate if you could provide a way to use `useClickAway` or similar functionality.

**Comment by mirka** [comment]
Seems to work as expected, please refer to [this example](https://codesandbox.io/p/sandbox/weathered-worker-89lhpk?file=%2Fsrc%2FApp.tsx%3A6%2C47).
