### ISSUE TITLE
Regression: iframed post editor can show some admin styles with classic themes

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#57176]
### Description

In classic themes, styles such as the `background-color` and `line-height` from the admin `common.css` can apply to the `body` element within the iframed post editor canvas.

### Step-by-step reproduction instructions

1. Activate Twenty Nineteen or another classic theme that does not set its own background color to the body (without using the Customizer, that also includes bundled themes from Twenty Ten to Twenty Sixteen).
2. Visit the post editor, and check that it is inside an iframe.
3. Note that the background is a light gray (`#f0f0f1`) instead of white.

### Screenshots, screen recording, code snippet

Twenty Nineteen is one of the themes that shows the admin's light gray background color instead of white.

![post editor uses admin CSS for the body background color](https://github.com/WordPress/gutenberg/assets/17100257/28fe6f8b-ab91-44f9-b3c2-8bbd0998025f)

In an uncommon and extreme example, a Calendar block has a `line-height` of 18.2 pixels—even when the font size is much bigger—in Twenty Twenty.

![font size is 36 pixels and the line-height is only 18.2](https://github.com/WordPress/gutenberg/assets/17100257/189fba92-159f-4e60-b2aa-f5c703de1ab5)

### Environment info

The admin CSS bleed can happen with WordPress 6.4.2, either without any plugins active or with Gutenberg 17.2.3. I also experienced it with WordPress 6.3.2, but only when Gutenberg was active (version 16.9.0).

For the screenshots, I used:
- WordPress 6.4.2 with Gutenberg 17.2.3
- Firefox 120.0.1 in Windows 10 Home

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sabernhardt** [comment]
I can think of two viable fixes.

## Option 1: Restore `html` in `reset.scss`

To override (at least) `body` from admin `common.css`, the `:where(.editor-styles-wrapper)` selector needs a higher specificity.

The **simplest** edit would be adding `html` back to the same [selector from which it was removed](https://github.com/WordPress/gutenberg/pull/46752/files#diff-bda8e417e9cfc8724167f4c82aab1d0d205245c51360a8afa4bba99ba078e6dbR10) (reverting one line).

However, **if** the extra element is necessary for _only_ the iframe body, its reset styles could be nested inside the current selector:

```
:where(.editor-styles-wrapper) {
	html & {
		// add styles for .editor-styles-wrapper whether it is a div or the iframe body
	}
}
```

## Option 2: Remove or replace the reset stylesheet when in an iframe

The [iframed editor proposal](https://github.com/WordPress/gutenberg/issues/20797) promised "no admin CSS bleed at all," so it seems counterintuitive to add and override admin styles in that context.

Enqueuing `reset.css` plus its two dependencies within the iframe adds a lot of code, and the [inline comment](https://github.com/WordPress/gutenberg/pull/48286/commits/898f62c28f60e2a5ec78a8eefed4db2432c834a6#diff-d66c57d67603bf45e2664289929b228b0eb69b037553b5c35a3497182a7e17d5R45) only mentions a need to reset the list styles. Also, if the comment refers to block margins in `wp-editor-classic-layout-styles`, those styles print _later_ in the queue.

If some styles are necessary to override, the iframe could have its own new (smaller) reset stylesheet.

(The current reset stylesheet theoretically could remove the 'common' and 'forms' dependencies only when in an iframe context, though that method might be overcomplicated.)

**Comment by peXed** [comment]
This is breaking older, custom themes from us as well. Would it not be the easiest way to reverting it back to use html? Was it not only removed for performance reasons?

**Comment by sabernhardt** [comment]
This is still a problem in WordPress 6.5-beta1 and Gutenberg 17.7.0.

Themes such as Twenty Thirteen and Twenty Fourteen show the issue more clearly because they do not specify a `font-size` or `background-color` in the editor. They have the `13px` text and `#f0f0f1` light gray from admin `common.css`.

Twenty Thirteen
![editor canvas has wrong background color and small body text](https://github.com/WordPress/gutenberg/assets/17100257/af2c47c3-5caf-4034-bb4d-919aa91c99b2)

Twenty Fourteen
![editor canvas has wrong background color and small body text](https://github.com/WordPress/gutenberg/assets/17100257/f6af3f87-4078-4cc3-8c1b-e7627c5182f3)

**Comment by karmatosed** [comment]
I wanted to confirm that this is still the case today. As has been said, this impacts all 'classic' themes, here is a list of themes which are impacted:

- Twenty Ten
- Twenty Eleven
- Twenty Twelve
- Twenty Thirteen
- Twenty Fourteen
- Twenty Sixteen
- Twenty Nineteen

This means that a significant amount of them are impacted, so my advice would be to look at a resolution or recommend an approach theme by theme if it is decided that the approach in editor is the preferred way. I suspect an approach in the editor is better than going theme by theme though.
