### ISSUE TITLE
Does not update metaboxes on save.

### ISSUE THREAD

**Issue by jsmoriss** [WordPress/gutenberg#5718]
## Issue Overview

Gutenberg does not update metaboxes when a post is saved. This is fine if the metabox is only input fields, but some metaboxes are NOT input fields, they are STATUS or INFORMATION metaboxes, which may pull information from many sources, including other plugins, "the_content" filter, post meta, site meta, have complicated dependencies, etc. And some metaboxes may include "placeholder" values, which need to be updated as well.

Gutenberg needs to provide a way to reload / refresh a metabox -- either (or both?) by specifying an additional argument when defining the metabox (ie. refresh on save = true) and then refreshing the metabox itself, or provide a JS hook so a JS callback function can do an ajax call to get the metabox HTML and then refresh / update the metabox div itself.

**Comment by adrianosferreira** [comment]
This is a very important enhancement. I'm handling a similar issue in WPML where there are some contents that we should only display after the post is saved. It would be great if Gutenberg could refresh the meta boxes.

**Comment by youknowriad** [comment]
We made a decision about not refreshing the meta boxes on save, because this was creating way too many issues as it goes against Single Page Application aspect of Gutenberg.

For example, if you refresh the meta-boxes using Ajax all javascript events registered on `document.load` won’t trigger, so you end up with broken metaboxes.

An alternative if you want to trigger some side effects when the meta boxes save is to do:

```js
var editPost = wp.data.select( 'core/edit-post' ),
    lastIsSaving = false;

wp.data.subscribe( function() {
    var isSaving = editPost.isSavingMetaBoxes();
    if ( isSaving !== lastIsSaving && !isSaving ) {
       lastIsSaving = isSaving;
        // Assume saving has finished
    }

    lastIsSaving = isSaving;
} );
```

**Comment by adrianosferreira** [comment]
@youknowriad of course I won't use your alternative as I don't want to trigger some side effects to my clients. I will see if somehow I can change the DOM after meta boxes are saved and append our stuff there.

**Comment by youknowriad** [comment]
The side effect I'm talking about is "change the DOM after meta boxes are saved" :)

**Comment by adrianosferreira** [comment]
@youknowriad I see. I just can't see what side effect it can cause if I just modify our particular meta box adding a couple of linked images + text.

**Comment by youknowriad** [comment]
Sorry, my terminology is misleading.

No side-effect here, it depends on the way your particular meta box work :). If you replace dom nodes and you'd use any JavaScript events it should be fine.

In general, we use the term side-effect to describe a behavior executed on state change (isLoadingMetabox here), I didn't mean that it will cause something unwanted.

**Comment by adrianosferreira** [comment]
@youknowriad cool, thanks. I've done some tests using your code to detect when meta boxes have been saved and instead of reloading the whole page, through AJAX I'm fetching the page fragment that I need (my particular `div`) and then updated the DOM in this particular `div`. It seems to work fine.

**Comment by jsmoriss** [comment]
Is isSavingMetaBoxes() true when the post is auto saved as well, or just when the "Update" button is pressed?

**Comment by jsmoriss** [comment]
Also, is saving metaboxes the last thing done when saving a post? If a metabox refresh needs the whole post saved, then is i()sSavingMetaBoxes safe to use, or is there a chance that only some parts of the post are saved, and others are not yet saved?

**Comment by youknowriad** [comment]
@jsmoriss yes it's also triggered on autosaves and yes it's the last saving flag.

**Comment by jsmoriss** [comment]
Thanks. So as someone might be editing a metabox, auto-save kicks in, and the metabox is refreshed as their typing? Wouldn't that be a bad thing?

**Comment by youknowriad** [comment]
How would you solve it? @jsmoriss and I guess this is a different issue, feel free to open an issue for it if there's none.

**Comment by jsmoriss** [comment]
@youknowriad So there's no way to find out if we're in an autosave or not? If so, yeah, I'd call that a bit of an issue. :)
