### ISSUE TITLE
Navigation Block Overlay non-functional in Classic Themes

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#57189]
### Description

Navigation Block > Overlays are not working on Classic Themes.  Clicking on the overlay icon has no response, making the navigation items inaccessible.

### Step-by-step reproduction instructions

1. On a site with a classic theme active, create a page containing a Navigation block set to Overlay > ALWAYS
2. Publish and view the page
3. Click the Overlay menu icon.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/27249804/2e6faef6-c4d5-4b56-a006-0c85a5d79a3d

### Environment info

- Themes tested: Blank Canvas (classic), Twenty Twenty, Twenty Twenty One
- Gutenberg 17.2.+ reproduce the issue; in Gutenberg 17.1.4, the overlay menu works as expected.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Confirmed this in texting - seems new in GB 17.2+.
Not present when in 6.4 when GB is not active.

**Comment by pbking** [comment]
I have confirmed this happening as well, happening in any Varia child theme that is using Navigation Block instead of the classic menu option.  Causes the 'overlay' option to not work on any size window.  Discovered in a few support tickets, expect it's pretty widespread.

**Comment by pauljacobson** [comment]
We have a report of this issue in 7470634-zen

**Comment by Jaccuse** [comment]
One report in 7460472-zen

**Comment by daria2303** [comment]
7551332-ZD

Also happening with overlay:mobile

**Comment by draganescu** [comment]
In current `trunk` of Gutenberg this appears to have been fixed again.

**Comment by draganescu** [comment]
I confirmed with @luisherranz that [#57396](https://github.com/WordPress/gutenberg/pull/57396) fixed this.
