### ISSUE TITLE
Tooltip doesn't hide when its anchor loses focus

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#57206]
While the tooltip correctly shows when its anchor receives focus, it doesn't seem to hide correctly when its anchor loses focus:

https://github.com/WordPress/gutenberg/assets/1083581/9b4e4913-90d4-4896-a67d-ce1b00766933

I've also added a few more unit tests in https://github.com/WordPress/gutenberg/pull/57204 to make sure that the component is not behaving as expected.

**Comment by ciampo** [comment]
It looks like regression was introduced in https://github.com/WordPress/gutenberg/pull/54573/files#r1329880428 and wasn't spotted because none of the unit tests explicitly tested for the tooltip hiding on blur.

**Comment by ciampo** [comment]
Adding an explicit `onBlur` prop to the anchor seems to do the trick — will push changes to https://github.com/WordPress/gutenberg/pull/57204

cc @diegohaz, in case you know the reason for this behavior — is there any reason why `Tooltip` doesn't hide on anchor blur  without an explicit `onBlur` handler?

**Comment by diegohaz** [comment]
> cc @diegohaz, in case you know the reason for this behavior — is there any reason why `Tooltip` doesn't hide on anchor blur without an explicit `onBlur` handler?

Yes, Ariakit popups using the [`hideOnInteractOutside`](https://ariakit.org/reference/tooltip#hideoninteractoutside) prop only close when you interact with something else in the same window. The rationale is briefly explained here: https://github.com/ariakit/ariakit/issues/3031#issuecomment-1802273326

We might be able to do something about iframes though.

**Comment by ciampo** [comment]
> We might be able to do something about iframes though.

What do you have in mind, exactly?

**Comment by diegohaz** [comment]
> > We might be able to do something about iframes though.
> 
> What do you have in mind, exactly?

These are my most recent thoughts on this topic: https://github.com/ariakit/ariakit/issues/3031#issuecomment-1803861710

**Comment by ciampo** [comment]
> Yes, Ariakit popups using the [`hideOnInteractOutside`](https://ariakit.org/reference/tooltip#hideoninteractoutside) prop only close when you interact with something else in the same window. The rationale is briefly explained here: [ariakit/ariakit#3031 (comment)](https://github.com/ariakit/ariakit/issues/3031#issuecomment-1802273326)

@diegohaz , coming back to this rationale.

Does it explain why the `Tooltip` doesn't hide when tabbing away from the button in the [isolated Storybook example](https://wordpress.github.io/gutenberg/iframe.html?args=&id=components-tooltip--default&viewMode=story)? There shouldn't be any iframe involved in that example AFAIK

**Comment by diegohaz** [comment]
> > Yes, Ariakit popups using the [`hideOnInteractOutside`](https://ariakit.org/reference/tooltip#hideoninteractoutside) prop only close when you interact with something else in the same window. The rationale is briefly explained here: [ariakit/ariakit#3031 (comment)](https://github.com/ariakit/ariakit/issues/3031#issuecomment-1802273326)
> 
> @diegohaz , coming back to this rationale.
> 
> Does it explain why the `Tooltip` doesn't hide when tabbing away from the button in the [isolated Storybook example](https://wordpress.github.io/gutenberg/iframe.html?args=&id=components-tooltip--default&viewMode=story)? There shouldn't be any iframe involved in that example AFAIK

Yes, the button is the only element on the page. When you tab away from it, you're leaving the document.

**Comment by ciampo** [comment]
Sounds good. I'll close for now, we can always re-open if we discover more serious implications of this behavior
