### ISSUE TITLE
Inserter overflows when open on mobile

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#5721]
## Issue Overview
When opening the inserter on a mobile device, the inserter appears too wide and overflows past the edge of the screen.

## Steps to Reproduce (for bugs)
1. Using DevTools, turn on mobile device emulation (I selected iPhone 6/7/8)
2. Open the inserter

## Expected Behavior
The inserter should appear and fill the screen.

## Current Behavior
The inserter appears but is too wide for the screen.

## Screenshots / Video
<img width="400" alt="screen shot 2018-03-21 at 16 38 45" src="https://user-images.githubusercontent.com/612155/37695835-57a3f7fc-2d26-11e8-8dff-c891b2816cfe.png">

## Related Issues and/or PRs
This seems to have been introduced by https://github.com/WordPress/gutenberg/pull/5541.

**Comment by karmatosed** [comment]
Good find! Hopefully we can get a fix as that's not great.

**Comment by jorgefilipecosta** [comment]
Hi @noisysocks in my tests this problem seems fixed. Could you confirm if that's case or if the problem is still persisting in your tests?

**Comment by noisysocks** [comment]
Yep, this seems fine now! 😄
