### ISSUE TITLE
Still able to select block when block is set to disabled with useBlockEditingMode

### ISSUE THREAD

**Issue by dernin** [WordPress/gutenberg#57227]
### Description

Bug: When a block is set to disabled using setBlockEditingMode, it stops a user from being able to select that block either directly by clicking on it or by selecting it in the block list view, however we discovered that a user is still able to select the disabled block by clicking in the space directly above the block before the block inserter. useBlockEditingMode does not appear to take this method of selecting blocks in to account (if that is a valid method of selecting blocks).
Related to #[52094 ](https://github.com/WordPress/gutenberg/pull/52094)

### Step-by-step reproduction instructions

1. Add two blocks to a page.
2. Disable the second block using the setBlockEditingMode method.
3. Confirm that it is disabled by attempting to select it.
4. Hover the mouse cursor just above the block so that the blue block inserter line and button appear.
5. Click anywhere between the second block and the first block except for the blue line and insert button. This must be in the center within the bounds of the blue line, not to the left or right of it.
6. The second block should now be selected and editable. 

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/68039044/51e6acb5-0fab-4b2e-88ca-cbcabcf1a613)

### Environment info

WordPress 6.4.2.
The Gutenberg plugin is not installed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I can confirm the issue.

@noisysocks, any thoughts on why this might be happening?

## Screencast

https://github.com/WordPress/gutenberg/assets/240569/ec5dde66-1600-43e0-944b-a10fb320875e

**Comment by noisysocks** [comment]
Huh weird. What's the `target` of the click event?
