### ISSUE TITLE
Default block appender doesn't appear underneath nested blocks

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#5722]
## Issue Overview
When editing a column block, the default inserter does not appear underneath the last block in the column.

## Steps to Reproduce (for bugs)
1. Create a _Column (experimental)_ block
2. Hover your mouse underneath the paragraph block in either the left or right column

## Expected Behavior
A grey line should appear on hover, indicating that clicking will insert a block at that position. 

## Current Behavior
No line appears. It does, however, correctly appear when you hover over the space in between blocks, just not when you hover over the space after the last block.

## Screenshots / Video
 
![bug](https://user-images.githubusercontent.com/612155/37695935-1ead2daa-2d27-11e8-99ee-ea8d60741a11.gif)

## Related Issues and/or PRs
It's likely that https://github.com/WordPress/gutenberg/pull/5541 introduced this regression.

**Comment by mtias** [comment]
The line appender is there to create an empty paragraph, since we are already on an empty paragraph, that's the expected result. Can you check what happens if the last item in the column is an image?

**Comment by aduth** [comment]
Discussed in #core-editor weekly triage: https://wordpress.slack.com/archives/C02QB2JS7/p1522944366000137

**Comment by noisysocks** [comment]
It looks like the line no longer appears after the last block in the main editor now, which means that the behaviour is consistent 😄
