### ISSUE TITLE
meta attributes between pages force "This block appears to have been modified externally."

### ISSUE THREAD

**Issue by rufioTR** [WordPress/gutenberg#5724]
## Issue Overview
I'm trying to use meta_ data to update informations on multiple blocks - if a block is on a seperated page it still gets the information, but if changed on one page the blocks on the other page get the "This block appears to have been modified externally." message.

## Expected Behavior / Possible Solution
I'd expect an option to disable the "This block appears to have been modified externally." for specific attributes?
Or maybe I'm just getting something very wrong of the meta idea?

## Ideas?
I'd be super thankfull for any ideas of solving this kind of problem:

As an example the author attribute:

/page1  has a block which uses meta_author
/page2 also has a block with meta_author

on /page2 i update the attribute value of meta_author
on /page1 i get the "This block appears to have been modified externally." message, because the meta_author value got updated

is there something else i should use for this kind of "propblem" ?

**Comment by danielbachhuber** [comment]
Hi @rufioTR,

Apologies for the late reply. Are you still stuck on this question? If so, can you provide specific code examples to reproduce?
