### ISSUE TITLE
Performance issue in Object Cloning using JSON.parse(JSON.stringify()) on Safari and Firefox

### ISSUE THREAD

**Issue by Omerisra6** [WordPress/gutenberg#57247]
### Description

WordPress 6.4 started using the latest version of core-js. This latest version creates significant performance issues in Safari and Firefox for any plugins or products using JSON parse to clone objects, like Elementor.

Our performance team confirmed that the loading time on Chrome is faster.

We detected that the problem is associated with the following commit of core-js (used in wp-polyfill): 
https://github.com/zloirock/core-js/commit/08ceeb13e78aeb366a3fcf481698ec05f77e7b2f

We managed to partially solve the issue by replacing the code with `structuredClone( object )`. However we couldn't replace all the occurrences of `JSON.parse( JSON.stringify( object ) )` with `structuredClone()`, as `structuredClone()` doesn't accept methods.

Using alternative solutions to deep clone objects either increased loading time or had no effect.

After [discussing the issue directly with the corejs team](https://github.com/zloirock/core-js/issues/1316), they suggested the following solution:

> Since it's a stage 3 proposal, most likely, it will be supported in the actual versions of browsers in some months and they will not have this overhead. It's still a ES proposal, so you could load only polyfills for stable ES or you could exclude those modules. Also, you could propose some changes that will increase performance, however, this overhead cannot be completely eliminated.

We opened [this ticket](https://core.trac.wordpress.org/ticket/60094#ticket) on WordPress Trac, but were informed that the wp-polyfill comes from babel-preset-default package, which is a Gutenberg dependency.

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hein-obox** [comment]
Can you please fix this?

**Comment by nicholaszein** [comment]
Hello, any update on this matter?

**Comment by swissspidy** [comment]
PRs are always welcome :)

Since it seems like a one line fix I opened a PR now that might solve this: https://github.com/WordPress/gutenberg/pull/57674

**Comment by richtabor** [comment]
@swissspidy who else should we loop in to verify/review #57674?

**Comment by swissspidy** [comment]
I don't know. Whoever worked on that code in the past according to Git history perhaps.

**Comment by richtabor** [comment]
> Git history perhaps.

It's just yourself, @gziolo and @sgomes.
