### ISSUE TITLE
@wordpress/env 9.0.0 Error on first build.

### ISSUE THREAD

**Issue by tKakazu** [WordPress/gutenberg#57243]
### What?
Before composer require phpunit, create and authorize the "/.composer" directory.
Change line 250 of 'packages/env/lib/init-config.js' like this.
```
USER $HOST_UID:$HOST_GID
ENV PATH="\${PATH}:/home/$HOST_USERNAME/.composer/vendor/bin"

USER root
RUN mkdir -p /.composer && chmod -R 775 /.composer
RUN composer global require --dev phpunit/phpunit:"^5.7.21 || ^6.0 || ^7.0 || ^8.0 || ^9.0 || ^10.0"
```

### Why?
Prevents this error from occurring.
`/.composer does not exist and could not be created:  `

I was unable to submit the request due to a pull request permission error.
I apologize for the inconvenience and thank you for your understanding.

### Step reproduction instructions

Run 'env WP_ENV_HOME=./new-wordpress wp-env start' in the new directory

**Comment by tKakazu** [comment]
I forgot to add the "[Package] Env" label.

**Comment by swissspidy** [comment]
I think this is a duplicate of #51419
