### ISSUE TITLE
Broken Link in 'https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/platform/README.md'

### ISSUE THREAD

**Issue by sha-linimoorthy** [WordPress/gutenberg#57269]
## Description
The link to the tutorial "Building a custom block editor" in the file `docs/how-to-guides/platform/README.md` is currently broken. Clicking on the link leads to a non-existent location, preventing users from accessing the tutorial.

### Expected Behavior
I expect the link to direct users to the tutorial "Building a custom block editor" successfully, allowing them to access the relevant content.

### Current Behavior
The current behavior is that the link is broken, leading to a non-existent location. Users encounter a 404 error when attempting to access the tutorial.

### Steps to Reproduce
1. Navigate to the `docs/how-to-guides/platform/README.md` file.
2. Look for the link to the tutorial "Building a custom block editor."
3. Click on the link, and observe that it leads to a non-existent page.
4. Change to https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/platform/custom-block-editor.md

### Additional Information
No additional information is available at the moment. The issue seems to be related to the incorrect link in the documentation file.

### Screenshots, screen recording, code snippet

![Screenshot 2023-12-20 201447](https://github.com/WordPress/gutenberg/assets/109151905/3f642b59-741c-44b4-892e-5a8945237917)

## Environment Info
- Not using Gutenberg (Gutenberg is not installed)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

The correct link would be `/docs/how-to-guides/platform/custom-block-editor.md`.

**Comment by ghost** [comment]
I have modified the readme file as required, please check and merge, thanks
