### ISSUE TITLE
Pasting list items shouldn't add trailing empty list items

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#5727]
## Issue Overview
See https://github.com/WordPress/gutenberg/pull/5354#issuecomment-369982646 in #5354:

![gutenberg-paste-single-item-list](https://user-images.githubusercontent.com/150562/36911198-b6d11368-1e3a-11e8-91df-3cfd59bc2d72.gif)

After copying a list item from a rich-text source (web page, word processor), pasting it into Gutenberg often results in unexpected empty list items being added — either before the intended pasted content, after, or both.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by iseulde** [comment]
When quote nesting is merged I will have a look into list item nesting. I think this is an issue that could be resolved by that.

**Comment by designsimply** [comment]
Tested with 4.0.0-rc.1 and confirmed the same issue is still happening there.

**Comment by iseulde** [comment]
@mcsf @designsimply Is it still happening in master?

**Comment by iseulde** [comment]
In my testing this seems resolved.
