### ISSUE TITLE
I can't select text using Microsoft Edge in Gutenberg

### ISSUE THREAD

**Issue by maisondasilva** [WordPress/gutenberg#57283]
### Description

I can't select text using Microsoft Edge in Gutenberg
Firefox is ok

Edge 121+

### Step-by-step reproduction instructions

Open Wordpress post or https://br.wordpress.org/gutenberg/

![Video-2023-12-20- 16-14-45  (1)](https://github.com/WordPress/gutenberg/assets/11423362/1cf5a143-613c-4ebc-9a44-d618ef796324)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

As far as I tested, the latest stable version of Edge is 120.0.2210.89, and I was unable to reproduce the issue. It looks like you are using version 121, is this a beta or canary version?

I think this is probably similar to the issue reported in #56408.

**Comment by maisondasilva** [comment]
@t-hamano Yes, I participate in the Windows Insider Program and in this case my Edge activates Preview mode Microsoft Edge releases early ( https://prod.support.services.microsoft.com/en-us/topic/preview-microsoft-edge-releases-early-2352d6f6-d7ef-4636-9a1a-e711e40cf03e?preview=true ), I tested on Edge Canary, Dev and Beta and I have problems on all 3 channels, using the stable version 120 there are no problems!

**Comment by talldan** [comment]
It's the same report as #56408, so closing as a duplicate.
