### ISSUE TITLE
Central Command Area missing when Block with No Tools is Selected

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#57288]
### Description
When a block with no tools is selected, the top toolbar will show a collapse icon even though no block tools are there. I think we could put a `hasAnyBlockControls` check within the privately exported [`useCanBlockToolbarBeFocused`](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/utils/use-can-block-toolbar-be-focused.js#L18).

### Step-by-step reproduction instructions
- Go to Site Editor
- Turn on Top Toolbar
- Edit Navigation Template Part
- Click navigation item
- Press Up Arrow until the block toolbar disappears and only a collapse icon shows in its place.

### Screenshots, screen recording, code snippet
<img width="1515" alt="Navigation Template Part with No Block Tools available and central document command center missing" src="https://github.com/WordPress/gutenberg/assets/967608/f7e45523-43d8-44df-8cb8-9ae2851a77c7">

**Comment by Mamaduka** [comment]
Related #40346.

So far, I can only reproduce the issue with the Navigation block. The [`getBlockSelectionStart` points](https://github.com/WordPress/gutenberg/blob/39b659dafc0332f475a3c5c22429edf77e10d9c5/packages/edit-post/src/components/header/index.js#L76-L77) to a block that no longer exists in the store, at least with the same `clientId`.

I guess that the Navigation block recreates its controlled block without properly updating the selection. While #58979 will potentially resolve the issue, it would be nice to track down the cause for the Nav block as well.

**Comment by jeryj** [comment]
@Mamaduka Ooooh that's a great find! I didn't check to see if it was a navigation block specific bug. I incorrectly assumed that there were blocks with no tools. I do think the idea of https://github.com/WordPress/gutenberg/pull/58979 will be useful to have a centralized check of what block tools are showing, and you're right that there's some deeper issue going on with the navigation block here.
