### ISSUE TITLE
Shared Blocks: Sibling inserter conflicts with selected edit panel

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#5733]
## Issue Overview

The edit "tray" at the bottom of a selected reusable block has erroneous padding.

## Steps to Reproduce

1. Create or insert a shared block
2. Select the block inserted in step 1

## Expected Behavior

Edit tray is flush with bottom border of selected block.

## Current Behavior

Excess padding at bottom of selected block.

## Possible Solution

Probably caused by display of sibling inserter within block display.

## Screenshot

![Reusable padding](https://user-images.githubusercontent.com/1779930/37729910-a59782e2-2d14-11e8-949f-2957da8379c8.png)

**Comment by jorgefilipecosta** [comment]
I'm closing this issue as it looks like it was fixed meanwhile:
<img width="550" alt="screen shot 2018-07-17 at 16 04 01" src="https://user-images.githubusercontent.com/11271197/42825994-3fb967dc-89db-11e8-937c-2be14abfc726.png">

If I missed something in my tests feel free to reopen and I will look further.

**Comment by aduth** [comment]
Yep, appears to have been since resolved. There's a similar padding issue with Classic blocks at #7918.
