### ISSUE TITLE
Calling `wp.data.dispatch('core').saveUser` with wrong data doesn't throw exception

### ISSUE THREAD

**Issue by cawa-93** [WordPress/gutenberg#57365]
### Description

Calling `wp.data.dispatch('core').saveUser` with wrong data doesn't throw exception. It throw exception if I doesnt pass any data
```js
wp.data.dispatch('core').saveUser() // TypeError
```
But if I pass wrong data it make API request, get 400 error as response and then doesn't throw an exception but successfully resolve promise.

### Step-by-step reproduction instructions

In wp admin call
```js
wp.data.dispatch('core').saveUser({})
	.then( (user) => console.log('in then', {user}) )
	.catch( e => console.log('in catch', {e}) ) 
```

### Screenshots, screen recording, code snippet

![зображення](https://github.com/WordPress/gutenberg/assets/1662812/e999c6ad-54e8-4970-a264-ede4d5cb28e6)

### Environment info

WordPress v6.4.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @cawa-93

The core data actions don't throw on error by default, but you can change this behavior by providing the `options` argument. For additional details, you can check the [`saveEntityRecord` reference](https://developer.wordpress.org/block-editor/reference-guides/data/data-core/#saveentityrecord).

**Example:**

```js
wp.data.dispatch('core').saveEntityRecord( 'root', 'user', {}, {throwOnError: true})
	.then( (user) => console.log('in then', {user}) )
	.catch( e => console.log('in catch', {e}) )
```

P.S. Currently, you can't pass options argument to action shortcuts like `saveUser`, but I've created a PR to fix the issue. Ref: #57383

**Comment by Mamaduka** [comment]
I am closing this now that #57383 has been merged.
