### ISSUE TITLE
Block Library: Caption component is rendered when multiple blocks are selected

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#57369]
### Description

Similar to #57357

A common `Caption` component is currently used to render the caption in the following blocks:

- Image
- Audio
- Gallery
- Video

The Caption control also appears on the block toolbar when multiple blocks are selected. This is unexpected behavior, and nothing happens when you click, and you may inadvertently delete caption text.

### Step-by-step reproduction instructions

Note: As for the Image block, it will be solved by #57357.

- Insert multiple blocks of Gallery, Video, or Image.
- Select those blocks.
- A caption button should now appear on the block toolbar.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/b5ac8d9e-4820-4968-bff1-93e151ddcb18

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@t-hamano, I will tentatively assign this to myself and try to push PR later today.

**Comment by t-hamano** [comment]
I would like to close this issue as it has been fixed in all blocks.

- Image Block: #57357
- Audio Block: #57376
- Gallery Block: #57378
- Video Block: #57375
