### ISSUE TITLE
useGlobalStyle not working

### ISSUE THREAD

**Issue by simom** [WordPress/gutenberg#57379]
### Description

I would like to access to the blockGap value defined in the styles.spacing node of the theme.json file and I found the useGlobalStyle function in the Gutenberg project folder.

This function is contained in the **block-editor/src/components/global-styles** folder and the readme file inside talk about “Public APIs”, but following the instructions this doesn’t work.

There is a specific function to access to the global styles defined in the theme.json file?

Thanks,

Simone

### Step-by-step reproduction instructions

```
import { useGlobalSetting } from '@wordpress/block-editor';

function MyComponent() {
	// The theme color palette.
	const [ colorPalette, setColorPalette ] = useGlobalSetting(
		'color.palette.theme'
	);

	// The theme color palette for the paragraph block, ignoring user changes.
	// If the palette is not defined for the paragraph block, the root one is returned.
	const [ pColor, setPColor ] = useGlobalSetting(
		'color.palette.theme',
		'core/paragraph',
		'base'
	);

	return 'Something';
}
```

### Environment info

WordPress 6.4.2
Gutenberg 17.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @simom,

Hooks related to the Global Styles are [private APIs](https://github.com/WordPress/gutenberg/blob/83e1a2c064c2233e8cd82dcccf4cd555c3497be1/packages/block-editor/src/private-apis.js#L4) and cannot be imported using normal methods.

To use this hook, you need to _unlock_ the API. Additionally, please be aware that there are [technical limitations](https://github.com/WordPress/gutenberg/blob/trunk/packages/private-apis/README.md#technical-limitations).

**Comment by simom** [comment]
Hi @t-hamano,
thank you for your feedback!
It might be a good idea to tweak the Readme file in the global-styles folder. The 'Available public APIs' section could be confusing if those are actually private APIs.
By the way, there is a safe way to access to the blockSpacing value defined in the theme.json file?
Thanks,
Simone

**Comment by t-hamano** [comment]
> It might be a good idea to tweak the Readme file in the global-styles folder. The 'Available public APIs' section could be confusing if those are actually private APIs.

Granted, these APIs aren't exposed and [the sample code](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/global-styles/README.md#available-public-apis) shouldn't work either, so we'll probably need to update it.

> By the way, there is a safe way to access to the blockSpacing value defined in the theme.json file?

In PHP, data can be retrieved using the [wp_get_global_styles()](https://developer.wordpress.org/reference/functions/wp_get_global_styles/) function, but I am not aware of any APIs that have been exposed to retrieve data using JS hooks.

**Comment by simom** [comment]
Hi @t-hamano,
thanks, I will likely submit a feature request because it could be beneficial in certain situations to access the theme.json configuration from JavaScript, especially when developing custom blocks with advanced functionality.
Thanks again for your help.
Best,
Simone
