### ISSUE TITLE
Heading block: heading level tooltip blocks you from selecting lower level

### ISSUE THREAD

**Issue by jeherve** [WordPress/gutenberg#57386]
### Description

When using the block controls to change the level of a heading in a heading block, the tooltip indicating the heading level can get in the way of picking a lower level heading.

### Step-by-step reproduction instructions

1. Add a heading block
2. In the block controls, open the heading level picker
3. Move down the list of levels with your mouse.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/426388/6b5ccc12-30c6-4207-874a-f4d6e3c9503f

### Environment info

- WP 6.4.2
- Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jeherve** [comment]
This was originally reported here:
https://fosstodon.org/@ross/111648878647292654

**Comment by t-hamano** [comment]
Thanks for the report.

In #56035, text is now displayed next to the icon instead of a tooltip. This change will be available in Gutenberg versions 17.1 and above.

I'd like to close this issue, but if there's anything I've missed, please comment.
