### ISSUE TITLE
SearchControl: Improve RTL support

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#57406]
The search icon and the close button positioning should flip accordingly in RTL mode.

Here is a reference design from Google in Arabic:

<img width="709" alt="A Google search field in RTL mode, where the close button is on the left and the search icon is on the right" src="https://github.com/WordPress/gutenberg/assets/555336/ed072c59-a047-4913-99a4-80d771565938">

---

This should be addressed after we swap out the implementation in #56524.

**Comment by youknowriad** [comment]
<img width="355" alt="Screenshot 2024-01-01 at 4 14 49 PM" src="https://github.com/WordPress/gutenberg/assets/272444/2d0f8a99-9573-4d92-9bc3-cf72dfce4c38">

This actually looks great to me, it's the google version that looks weird for me.

**Comment by mirka** [comment]
You're right, sorry. I was mid-refactor in a unification effort and was probably looking at a different implementation 😅
