### ISSUE TITLE
Navigation Block: Overlay Menu toggle not working on Classic Themes

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#57428]
### Description

When using a Classic Theme, the Overlay Menu option of the Navigation Block will not work, as clicking the toggle won't change its state.

### Step-by-step reproduction instructions

1. Install a Classic Theme
2. Open a new page or post
3. Insert a Navigation Block
4. Set the Overlay Menu settings to "Always"
5. Open the page and click on the menu toggle to open it - the overlay menu won't open

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/14153300/048fbd5b-238d-4b24-b912-0e3440dbcb5d

### Environment info

- WordPress 6.4, Gutenberg 17.3, tested with Twenty Sixteen and TT4
- Chrome 120, Mac OS Sonoma

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I think this issue was resolved in #57396 and will be fixed in the next Gutenberg plugin 17.4. If it hasn't been fixed, please leave a comment.
