### ISSUE TITLE
Hardcoded definition of max-width in left/right aligned image blocks

### ISSUE THREAD

**Issue by Luehrsen** [WordPress/gutenberg#5745]
## Issue Overview
We are currently developing a theme, where 50% of the available width does not equal half the content width. So the max-width: 50% added as inline styles does not really help the cause. 

Should this not be theme territory, or at least be CSS territory? 

From a usability and code standpoint I find inline style arguments always a sub par solution. 

This is the line of code I'm talking about.
https://github.com/WordPress/gutenberg/blob/master/blocks/library/image/index.js#L178

## Steps to Reproduce (for bugs)
Go into the Gutenberg demo post, add a left aligned image and look at the resulting code. It should have "max-width: 50%" as inline style argument.

## Expected Behavior
I expected the image tag just to have the class, not to make any assumptions about the width, UNLESS the user specifically commands it so.

## Possible Solution
Remove that specific line of code. 
https://github.com/WordPress/gutenberg/blob/master/blocks/library/image/index.js#L178

**Comment by samikeijonen** [comment]
I noticed same thing. And I agree that this is theme CSS territory. It can be in `block.css` if though so themers can overwrite it more easily.

**Comment by jasmussen** [comment]
Closing this in favor of #5567.
