### ISSUE TITLE
Featured Image: Do not hide the Replace button from assistive technologies

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#57451]
### Description

Follow-up to https://github.com/WordPress/gutenberg/pull/50269

In https://github.com/WordPress/gutenberg/pull/50269 the Featured Image UI in the document settings panel changed from this:

![Screenshot 2023-12-29 at 10 48 59](https://github.com/WordPress/gutenberg/assets/1682452/fcec1086-87d9-4dfb-b59d-30e587d8071a)

to this:

![Screenshot 2023-12-29 at 09 55 51](https://github.com/WordPress/gutenberg/assets/1682452/fd738c9a-2aee-4703-a4ac-2493f9c7d685)

It has been released in WordPress 6.3. 
The Replace and Remove buttons now appear only on hover and focus. There's a few accessibility problems with the new design that need some discussion but for now I'd like to focus only on one of them.

The Replace button has an `aria-hidden="true"` attribute with a comment that makes clear this was intentional.

https://github.com/WordPress/gutenberg/blob/3591f4d9da4c941ce50851673018e5841074d997/packages/editor/src/components/post-featured-image/index.js#L211-L212

However, the button is still focusable. As such, it still is in the tab sequence and users, including screen reader users, cn tab to it. The specific behavior may vary depending on the screen reader in use and basically:
- either the button is a silent tab stop
- or it will be announced anyways by screen readers, ignoring the `aria-hidden="true"` attribute.

I think the accessibility team reported several times that there's no good way to hide interactive focusable controls such as buttons and links from assistive technologies. It is not recommended in the first place.

An interactive control that is visually presented to users should also be available to users with no vision.

### Step-by-step reproduction instructions

- Edit a post and add a featured image.
- Test with Safari and VoiceOver.
- Tab to the Document settings panel > Featured image.
- Tan and Shift+Tab multiple times through the Replace and Remove buttons.
- Observe that sometimes there is a silent Tab stop
- Observe that sometimes the Replace button is skipped and sometimes it receives focus and it is announced.

Screenshot: VoiceOver announces the button ignoring the `aria-hidden="true"` attribute:

![Screenshot 2023-12-29 at 12 30 57](https://github.com/WordPress/gutenberg/assets/1682452/7ec54ab9-dd4e-48d0-8e5b-8d7f8a6b0c11)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by afercia** [comment]
It is also important to mention that speech recognition software will not 'perceive' the Replace button. Assuming speech recognition software users have a chance to make the buttons appear, issuing a voice command like 'Click Replace' will not work because the button is aria-hidden.

**Comment by t-hamano** [comment]
~~Can this problem be solved by simply removing the `aria-hidden` attribute of the Replace button? Or is it not recommended to use buttons that are invisible unless you hover over them?~~ Update: I had overlooked that #57453 had been submitted to remove the aria-hidden attribute.

By the way, when testing with NVDA on Windows, the Replace button seems to read "blank".

![nvda](https://github.com/WordPress/gutenberg/assets/54422211/6d0185da-d820-4fb1-ad78-a525d2b7109c)

**Comment by afercia** [comment]
@t-hamano thanks for looking into this.

> Or is it not recommended to use buttons that are invisible unless you hover over them?

It is not a best practice. The accessibility team always reported that controls that appear and disappear continuously are always a problem for accessibility, regardless whether they are rendered conditionally or their visibility is toggled via CSS.

That's a separate issue though and would require some discussion

> when testing with NVDA on Windows, the Replace button seems to read "blank".

Yes, as I mentioned: `The specific behavior may vary depending on the screen reader in use`. The mainpoint is that this button is still focusable but it's 'hidden' in the accessibility tree. It's something unexpected and screen readers get pretty confused.
