### ISSUE TITLE
Search button is cut off in "button-only" mode in navigation block

### ISSUE THREAD

**Issue by bugnumber9** [WordPress/gutenberg#57465]
### Description

When a search block is added into a navigation block and set to button-only mode, the button appears cut off:
![editor](https://github.com/WordPress/gutenberg/assets/1769548/176cdb04-1637-4fd5-b58c-c364ad894a49)
![front](https://github.com/WordPress/gutenberg/assets/1769548/783eb849-8ad4-49d8-9ad3-f3c8d57405cd)

It looks fine when added elsewhere:
![editor2](https://github.com/WordPress/gutenberg/assets/1769548/d3399dac-77a7-4973-9518-b56661f2fae7)
![front2](https://github.com/WordPress/gutenberg/assets/1769548/f3325d17-0a6f-4eba-9227-75683cab2e10)

### Step-by-step reproduction instructions

1. Add search block to a navigation menu and set it to button-only. Check on the frontend.
2. Move the block elsewhere, check on the frontend.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by asafm7** [comment]
Also noticed it. It looks okay on the editor, but not on the front end.

Maybe it is because this CSS is loading on the editor, but not on the frontend:

![image](https://github.com/WordPress/gutenberg/assets/14274769/14588c61-ec60-4431-b423-28eafe200688)

**Comment by annezazu** [comment]
Thanks for opening this. Is this still the case? I tried to replicate with WordPress 6.6.1 and Gutenberg 19.1 but wasn't able to do so:

https://github.com/user-attachments/assets/5c5d2096-a878-4b54-a3a9-7e9bc3e2d332

I'm going to close out for now but, if folks can replicate, please let me know as I'd like to reopen this!
