### ISSUE TITLE
Can't edit search block after setting it to "button only"

### ISSUE THREAD

**Issue by bugnumber9** [WordPress/gutenberg#57464]
### Description

After adding a search block to a navigation menu and setting the block to "button only", it's no longer possible to edit the search block. Focus in the list view jumps to the parent navigation block.
The video below shows this.

https://github.com/WordPress/gutenberg/assets/1769548/4fd693a8-ee4a-4125-bcc6-8eaff5cb7263

### Step-by-step reproduction instructions

1. Add a search block to a navigation menu.
2. Set the block to button-only.
3. Try to edit the search block.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Thanks for opening this! I tried to replicate this with WordPress 6.6.1 and GB 19.1 but wasn't able to:
https://github.com/user-attachments/assets/a6bca829-388c-4de8-a432-5d2cdd2c0aae

Closing this out as a result but let me know if I missed something.
