### ISSUE TITLE
Copy/pasting a link from plain text causes autolinking to not work

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#57487]
### Description

If you paste some text and a link from plain text into Gutenberg and then try to apply the link with a copy/paste onto the text itself, it fails and instead just replaces the text. 

### Step-by-step reproduction instructions

1. Write some text with a link in plain text.
2. Copy and paste it into a new post. 
3. Copy the link you added and paste it over the text.
4. Notice it doesn't link and instead overwrites the text. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/26996883/678a3f87-9c61-4b1b-aa47-bff3ba9e6151

### Environment info

- WP 6.4.2
- GB 17.3
- TT4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@ellatrix might be of interest to you!

**Comment by youknowriad** [comment]
I've tracked this down to a regression introduced here https://github.com/WordPress/gutenberg/pull/54301/files#r1439029813

**Comment by ellatrix** [comment]
The regression is caused by a change in order in #55195, which moved the linking transform after the `isInternal` check.
