### ISSUE TITLE
Support AVIF photo communal house and insert AV1 video along with product photos

### ISSUE THREAD

**Issue by phanduynam** [WordPress/gutenberg#57484]

**Comment by phanduynam** [comment]
Avif format and Av1 video are already very popular, browsers are supported, otherwise there would be 1 prediction missing. I want WordPress to extend support for Avif image and Av1 video formats, as well as add the ability to upload videos with products on WooCommerce.

**Comment by skorasaurus** [comment]
Hi, 

This is better suited as a request for the core WordPress tickets as this would affect all of WordPress; not just the editor. This has been requested in WordPress Core at https://core.trac.wordpress.org/ticket/51228
