### ISSUE TITLE
Template option not showing in components panel

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#57491]
### Description

For some reason the Template option in the components panel is not showing up. 

### Step-by-step reproduction instructions

1. Activate 2024 theme and latest Gutenberg only
2. Edit a page
3. Look in components sidebar in the Pages tab > Summary 
4. Template should be between Publish and URL and it's not there.. (see my screencast)
5. If I deactivate Gutenberg the Template option shows up as a dropdown

### Screenshots, screen recording, code snippet

https://soapbox.wistia.com/videos/Zst5jMTQgs

### Environment info

- wp 6.4.2
- gutenberg 17.3.0
- chrome
- mac sonoma 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Confirmed this in testing with GB 17.3 active. It also only takes place in Block themes (classic themes seem ok).

**Comment by t-hamano** [comment]
I tested with the following Gutenberg plugin versions, but could not reproduce the issue with any version 🤔 Are you seeing any errors in your browser console?

- 17.3.0
- 17.3.1
- 17.4.0
- 17.4.1

![image](https://github.com/WordPress/gutenberg/assets/54422211/ba8184b3-4293-462d-9009-b3279b79db82)

**Comment by bradhogan** [comment]
I can't seem to replicate anymore 🤷
