### ISSUE TITLE
Navigation Link Block Color is overriden by block CSS

### ISSUE THREAD

**Issue by adarshakshatPosimyth** [WordPress/gutenberg#57499]
### Description

Even though color for Hover and text is provided in theme.json
`"core/navigation": {
				"spacing": {
					"blockGap": "0.5rem"
				},
				"elements": {
					"link": {
						"typography": {
							"textDecoration": "none"
						},
						"color": {
							"text": "var(--wp--preset--color--on-surface)"
						},
						":hover": {
							"color": {
								"text": "var(--wp--preset--color--on-surface-variant)"
							},
							"typography": {
								"textDecoration": "underline"
							}
						}
					}
				}`
The Hover State color is overriden by Css Rule from wp-includes/blocks/navigation/style.min.css
Normal State
<img width="1309" alt="Screenshot 2024-01-03 at 1 37 21 PM" src="https://github.com/WordPress/gutenberg/assets/126477178/8cd7217b-2c02-401d-b3a8-7c1d42996e8e">
On Hover State
<img width="1348" alt="Screenshot 2024-01-03 at 1 39 46 PM" src="https://github.com/WordPress/gutenberg/assets/126477178/7054c44d-11fd-41e5-bf85-2fcf33ddd568">

### Step-by-step reproduction instructions

1. Create a Block Theme and mention the navigation link rule for hover and normal state
2. Add a link to Navigation block in post/page
3. View the link in front end and hover over it . Notice Color doesn't change

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
The navigation block links are specific blocks. What I means is that the actual link is not in the block called "core-navigation" but on the inner blocks like the core/navigation-link, core/page-list and so on.
So try to move the link styles to those blocks.

**Comment by carolinan** [comment]
I am removing the needs testing label because I can confirm that this style in theme.json does not work.

It might not be a true "bug", it might be intended?, but it does not work like developers expect it to, and it would be much easier if the style could just be added to core/navigation.

**Comment by adarshakshatPosimyth** [comment]
Apologies for the delay, I tried targetting page-list and it was of no help.


<img width="1292" alt="Screenshot 2024-01-20 at 12 17 46 AM" src="https://github.com/WordPress/gutenberg/assets/126477178/1c13098d-ac6b-473c-86f4-cd644579691a">

Here's the theme.json

`"core/page-list": {
				"spacing": {
					"blockGap": "0.5rem"
				},
				"elements": {
					"link": {
						"color": {
							"text": "var(--wp--preset--color--on-surface)"
						},
						":hover": {
							"color": {
								"text": "var(--wp--preset--color--on-surface-variant)"
							},
							"typography": {
								"textDecoration": "underline" }
						}
					}
				}
			},`

**Comment by gaambo** [comment]
#47431 seems to be related. I [commented a summary](https://github.com/WordPress/gutenberg/issues/47431#issuecomment-2018126625) there. Should these issue be merged?

**Comment by talldan** [comment]
Thanks @gaambo, a bit late, but I'll close this issue as a duplicate of the original you mentioned.
