### ISSUE TITLE
Disable Preview button for non-viewable post types.

### ISSUE THREAD

**Issue by ryanboswell** [WordPress/gutenberg#5749]
## Issue Overview
Currently if a post type is not viewable (as determined by [`is_post_type_viewable`](https://developer.wordpress.org/reference/functions/is_post_type_viewable/) in core), the Classic Editor and Post list table will not show a Preview button or link, but Gutenberg shows the button regardless. This results in a false-impression that users can preview a post if they are editing in Gutenberg and will result a broken link.

This happens on the latest `master` of Gutenberg.

## Steps to Reproduce (for bugs)
1. Create a new custom post type, with `publicly_queryable` set to `false`.
2. Add a new post using Gutenberg's editor and see that the Preview button appears (even after saving as draft).
3. Add a new post using the Classic Editor and see that no Preview button appears (even after saving as draft)
4. Repeat with an existing post and confirm the same Preview button behavior as steps 2/3.

## Expected Behavior
If a post type is not viewable (ie. `public` or `publicly_queryable`, Gutenberg should not display a Preview button in the UI.

## Current Behavior
Gutenberg displays a Preview button in the editor UI regardless of the post type properties that should otherwise disable it.

**Comment by danielbachhuber** [comment]
@jorgefilipecosta Can I pick this up for you?

**Comment by jorgefilipecosta** [comment]
Yes @danielbachhuber, please feel free to pick it 👍

**Comment by danielbachhuber** [comment]
Core Trac ticket to introduce a `previewable` attribute is: https://core.trac.wordpress.org/ticket/43739
