### ISSUE TITLE
Block mover: disabled buttons should be disabled

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#575]
Currently, when a block is the first or last one, the "block mover" shows just one button to move the block down or up.

However, the "disabled" button is still there: it gets revealed on hover and it's still focusable and actionable. It just takes a CSS class that applies a close-to-white color, so it can't be distinguished from the white background:

![screen shot 2017-04-29 at 18 34 24](https://cloud.githubusercontent.com/assets/1682452/25557130/2c0702cc-2d0b-11e7-942f-ccf1f648c1c6.png)

It should probably use `display: none` or `visibility: hidden` if keeping the space that it takes is necessary for layout purposes. I'd consider to make it really disabled too.

**Comment by nylen** [comment]
> It should probably use `display: none` or `visibility: hidden` if keeping the space that it takes is necessary for layout purposes. I'd consider to make it really disabled too.

I think it's nice to leave the buttons visible to indicate that they would be active if not for some condition being true.

**Comment by afercia** [comment]
Yep that also could work 🙂  visible and disabled (visually disabled and with a `disabled` attribute).
