### ISSUE TITLE
Data views: Double scrollbar in templates list layout

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#57594]
If you switch to List layout in the template management data view there are multiple scrolling containers:

https://github.com/WordPress/gutenberg/assets/846565/d7a2ec77-fd70-494a-8aec-24532185f29d

**Comment by t-hamano** [comment]
This problem does not appear to occur on the trunk. However, I am having a similar issue with the grid layout, so I reported it in #58535.

**Comment by jameskoster** [comment]
Thanks for pointing that out, this seems to have gotten fixed somewhere along the way :)
