### ISSUE TITLE
Plugin API Sidebar empty when refreshing page.

### ISSUE THREAD

**Issue by Xyfi** [WordPress/gutenberg#5759]
## Issue Overview

When refreshing the editor when a plugin sidebar is open, the sidebar will be empty. This happens because the plugin hasn't been registered when the editor is rendered.

## Steps to Reproduce (for bugs)

1. Add a plugin sidebar. [You can use this plugin](https://github.com/Xyfi/gutenberg-api-test) or:
```
const {
	registerPlugin,
} = wp.plugins;
const {
	PluginSidebar,
} = wp.editPost.__experimental;
const {
	Fragment
} = wp.element;
const {
	dispatch,
} = wp.data;

const SidebarContents = ( props ) => {
	const onClose = dispatch( "core/edit-post" ).closeGeneralSidebar;
	return (
		<div>
			<p>Here is the sidebar content!</p>
			<button onClick={ onClose }>Close</button>
		</div>
	);
};
const Component = () => {
	return (
		<Fragment>
			<PluginSidebar name="my-sidebar" title="My sidebar">
				<SidebarContents />
			</PluginSidebar>
		</Fragment>
	);
};
registerPlugin( "my-plugin", {
	render: Component,
} );
```
2. Open the sidebar using the `wp.data.dispatch` api.
```
wp.data.dispatch( "core/edit-post" ).openGeneralSidebar( "my-plugin/my-sidebar );
```
3. Refresh the page with the sidebar open.
4. Notice that the sidebar is empty.
5. Any action that triggers a dispatch on the store will make the sidebar show up, like clicking a block.

## Expected Behavior

I expect the plugin sidebar to show up as soon as it is registered.

## Current Behavior

The sidebar is empty until an action is dispatched on the store.

## Possible Solution

Register plugins in the store.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by amdrew** [comment]
👍 Replicated this using the plugin and code example above (though missing a quotation mark on the `( "my-plugin/my-sidebar );` bit ) and also via the documentation here: https://github.com/WordPress/gutenberg/blob/master/plugins/README.md

Shows on first page load, but when refreshing it's blank.
