### ISSUE TITLE
Templates List /Table layout: Hide preview field

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#57597]
In the Templates data view the preview thumbnail is only helpful in Grid layout, where it is large enough to communicate a reasonable preview. In List and Table layouts it's simply too small.

<img width="1079" alt="Screenshot 2024-01-05 at 14 22 53" src="https://github.com/WordPress/gutenberg/assets/846565/8685c585-e358-4f49-930b-32eca2efaa30">

Let's hide the preview field in List and Table layout for now.

**Comment by jameskoster** [comment]
<img width="418" alt="Screenshot 2024-01-05 at 14 33 46" src="https://github.com/WordPress/gutenberg/assets/846565/1228f92b-d54b-42fa-b8da-02ec6cee9045">

One option could be to use icons, but I'm not sure how helpful they are. If such an idea is technically complex then perhaps its simpler to hide the preview field for templates in this layout.

**Comment by jasmussen** [comment]
The broader context, and correct me if I'm wrong, is that the inclusion of thumbnails in this particular list view configuration is a result of needing to be able to show thumbnails in this way for a _Users_ page, is that about right? I do agree that icons could be a good fallback, I mainly wonder if we can't just disable this thumbnail by default, for this particular list view type. Thinking broader, it doesn't seem helpful to see thumbnails on your pages lists. Or going further, on your tags lists.

**Comment by jameskoster** [comment]
Gravatars for the Users page is one example, Featured Image for Pages/Posts is another. Thumbnails for Theme/Plugin lists could be another. It's hard to see all potential use cases accounting for plugins etc, so I'd prefer not to unilaterally disable it because there will undoubtedly be legitimate use cases. 

To me it feels like a detail to be defined in the view config. So a data view like templates can define that; In List Layout, the `preview` field is disabled. A data view like Pages can define that; in List Layout the `preview` field is populated by the featured image. And so on.

All that said, disabling the preview on the templates data view in List layout seems like a reasonable place to start. Icons can be added later if needed.

**Comment by jasmussen** [comment]
>  It's hard to see all potential use cases accounting for plugins etc, so I'd prefer not to unilaterally disable it because there will undoubtedly be legitimate use cases.

Definitely, good point. I think "disabling it" may be too strong a wording, what I'm saying is that for that particular row/table based layout, it seems more likely that there _won't_ be useful thumbnails than otherwise. Exactly as you suggest, it could be off by default, but enabled in the view config.

**Comment by oandregal** [comment]
Some thoughts about how we could implement this:

1. In the consumer (Pages, Templates, Patterns):
    1. It may declare a field depending on the view.type. For example, it may declare all fields for grid but omit featured image for tables and list.
    2. It may declare all the fields for all views, but provide different render for each: the grid gets the "preview", but table/list can act as a boolean/string (as in "has featured image" or not).
2. As part of the DataViews APIs.
    1. We could hide the `mediaField` from the list and table.
    2. As part of the `view.layout`, we could have `hiddenFields` the user cannot make visible.
    3. For list & grid, we do not render any field of type `image` that is not set as `mediaField`.

**Comment by oandregal** [comment]
Added a new option above:

> For list & grid, we do not render any field of type `image` that is not set as `mediaField`.

Adding some context. I was thinking about how would we manage a situation in which there were two images:

- table: just fine, it's another column
- grid & list: unsure how we'd do it

**Comment by jameskoster** [comment]
As with https://github.com/WordPress/gutenberg/issues/58012 I'm a little hesitant about this one now. Linking field availability to layout feels a bit at-odds with the data views concept. Ideally all fields should work in all layouts, and it's up to the user which ones to include or not. In this case, I think we should explore ways to make the template preview work in List layout. I'll open a new issue for this.
