### ISSUE TITLE
Pass content to render callback

### ISSUE THREAD

**Issue by mattheu** [WordPress/gutenberg#5760]
## Issue Overview

The block content is no longer available in the render callback. [It was removed here.](https://github.com/WordPress/gutenberg/pull/4591 ) 

However, it would be very useful to have this data available. I have 2 use cases.

* I have a partially dynamic block. I am saving my block as HTML in the post content. But I want a small part of this to be modified.
* I have a container block with nested children. The block is rendered in PHP. I have no way to get the child block data. 

There are alternative ways to achive these goals. I could have my dynamic block fully rendered in PHP. I could just allow my container block to store all the data in the post content. However this isn't very flexible.

**Comment by gschoppe** [comment]
Other necessary situations for content to be accessible inside the render callback include:

- Members-Only functionality - two different sets of blocks are served to different users
- Fallback data functionality - if a query fails, render a set of blocks as a fallback (imagine no results found on a recent posts block)
- Contextual rendering - render content in one way for a single page, another for the archive view, and a third for the RSS/Atom feeds

**Comment by mcsf** [comment]
This is probably something to have. The issues cross-referenced above may suggest other use cases. Further, here's a use case for the core Gallery block:

https://github.com/WordPress/gutenberg/pull/3852#issuecomment-385684176

**Comment by mattheu** [comment]
Just for reference - there's a pretty stale PR here https://github.com/WordPress/gutenberg/pull/6239

**Comment by gschoppe** [comment]
For two of the examples I provided above, it is also necessary to have the ability to pass child block objects into a render callback. Member content, for example, should be able to contain any number of blocks, and then conditionally choose whether to render them or not. This functionality is currently possible with nested shortcodes, so should not be regressed by moving to Gutenberg.

**Comment by pento** [comment]
Passing the content to the render callback was re-added in #8077, it'll be released in Gutenberg 3.4. 🙂

Passing the child block objects is a little trickier, and will likely require replacing the current `do_blocks()` regex with a much faster parser. See #8244 for an overview ticket of the various approaches towards that.
