### ISSUE TITLE
Image block box-shadows conflict with border-radius

### ISSUE THREAD

**Issue by kaelansmith** [WordPress/gutenberg#57611]
### Description

I'm using the relatively new "shadows" option in `theme.json`, created some shadow presets, and tried applying a default shadow to image blocks via `theme.json` > `styles` > `blocks` > `core/image` > `shadow`, where I also specify a default border-radius, and found that the shadow gets applied to the wrapping `figure` element, while the border-radius gets applied to the nested `img` element, which causes a visual issue where the shadow isn't "in sync" with the border radius -- screenshot (most noticeable on bottom corners):

![image](https://github.com/WordPress/gutenberg/assets/60372141/16578832-c099-47d8-a947-f29d2a84c455)

**Code**:
```json
{
  ...
  "styles": {
    "blocks": {
      "core/image": {
        "border": {
          "radius": "var(--wp--custom--border-radius--lg)"
        },
        "shadow": "var(--wp--preset--shadow--md)",
      }
    }
  }
}
```

### Work-around:
```json
{
  ...
  "styles": {
    "blocks": {
      "core/image": {
        "border": {
          "radius": "var(--wp--custom--border-radius--lg)"
        },
        "css": "& img{box-shadow:var(--wp--preset--shadow--md);}"
      }
    }
  }
}
```

### Step-by-step reproduction instructions

1. apply provided code example in your own theme.json

### Environment info

WP v6.4.2, not using Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by colinduwe** [comment]
I tested this and confirmed the issue when not using the Gutenberg plugin. Installing and activating the Gutenberg 17.8.2 resolves the issue.

**Comment by madhusudhand** [comment]
Thank you @colinduwe for testing. I can also confirm that it is no longer an issue.

<img width="684" alt="image" src="https://github.com/WordPress/gutenberg/assets/1935113/88f21029-8bf9-423b-a53a-032baebabf53">

Closing the issue. If you still observe the issue, please re-open.
