### ISSUE TITLE
Link block with tag <a> breaks the Patterns / Template part Editor (TypeError: Cannot read properties of null (reading 'ResizeObserver'))

### ISSUE THREAD

**Issue by madfcat** [WordPress/gutenberg#57615]
### Description

The simplest custom block with <a> breaks template editor

block.json
```
{
	"$schema": "https://schemas.wp.org/trunk/block.json",
	"apiVersion": 3,
	"name": "my-blocks/something",
	"version": "0.1.0",
	"title": "Something",
	"category": "design",
	"icon": "admin-links",
	"description": "Something.",
	"example": {},
	"supports": {
		"html": false
	},
	"textdomain": "stephen-blocks",
	"editorScript": "file:./index.js",
	"editorStyle": "file:./index.css",
	"style": "file:./style-index.css",
	"viewScript": "file:./view.js"
}
```

**edit.js**
```
import { __ } from "@wordpress/i18n";
import { useBlockProps } from "@wordpress/block-editor";
import "./editor.scss";

export default function Edit() {
	return (
		<a {...useBlockProps()} href="">
			hello
		</a>
	);
}
```

**save.js**
```
import { useBlockProps } from "@wordpress/block-editor";

export default function save() {
	return (
		<a {...useBlockProps.save()} href="">
			hello
		</a>
	);
}
```

package.json
```
{
	"name": "my-blocks",
	"version": "0.1.0",
	"description": "Example block scaffolded with Create Block tool.",
	"author": "The WordPress Contributors",
	"license": "GPL-2.0-or-later",
	"main": "build/index.js",
	"scripts": {
		"build": "wp-scripts build",
		"format": "wp-scripts format",
		"lint:css": "wp-scripts lint-style",
		"lint:js": "wp-scripts lint-js",
		"packages-update": "wp-scripts packages-update",
		"plugin-zip": "wp-scripts plugin-zip",
		"start": "wp-scripts start"
	},
	"devDependencies": {
		"@wordpress/scripts": "^26.19.0"
	}
}

```

Error that happens after this in the console:
```
react-dom.min.js?ver=18.2.0:10 TypeError: Cannot read properties of null (reading 'ResizeObserver')
    at block-editor.min.js?ver=f0bb1e364b792257eb17:41:103660
    at Ur (react-dom.min.js?ver=18.2.0:10:73411)
    at Jr (react-dom.min.js?ver=18.2.0:10:80643)
    at Zr (react-dom.min.js?ver=18.2.0:10:80489)
    at Gr (react-dom.min.js?ver=18.2.0:10:80023)
    at react-dom.min.js?ver=18.2.0:10:91526
    at xl (react-dom.min.js?ver=18.2.0:10:92039)
    at fl (react-dom.min.js?ver=18.2.0:10:85808)
    at Nn (react-dom.min.js?ver=18.2.0:10:32474)
    at react-dom.min.js?ver=18.2.0:10:83226
```

My observation is that it never happens in the editor when the editor is not resizable and there is no drag handles. For example, when I edit a post or a page.
Probably, something is messed up with resizing and ResizeObserver.

### Step-by-step reproduction instructions

1. Clone from [GitHub](https://github.com/madfcat/wordpress-pattern-editor-bug), `npm install`, `npm run build` to build the block. Copy directory to the plugins of wordpress. Activate plugin.
2. From admin: Go to **Appearance -> Editor -> Patterns** and click **"Create template part"**. Choose, for example, footer.
3. Insert the block Click outside this block and the click on this block. The block becomes white.
4. Open block lists. Click on the name from the list, then click on the white block, then on the name again. You will see an error: "The editor has encountered an unexpected error."
5. The error in the console will appear:
```
react-dom.min.js?ver=18.2.0:10 TypeError: Cannot read properties of null (reading 'ResizeObserver')
    at block-editor.min.js?ver=f0bb1e364b792257eb17:41:103660
    at Ur (react-dom.min.js?ver=18.2.0:10:73411)
    at Jr (react-dom.min.js?ver=18.2.0:10:80643)
    at Zr (react-dom.min.js?ver=18.2.0:10:80489)
    at Gr (react-dom.min.js?ver=18.2.0:10:80023)
    at react-dom.min.js?ver=18.2.0:10:91526
    at xl (react-dom.min.js?ver=18.2.0:10:92039)
    at fl (react-dom.min.js?ver=18.2.0:10:85808)
    at Nn (react-dom.min.js?ver=18.2.0:10:32474)
    at react-dom.min.js?ver=18.2.0:10:83226
```

Pressing on the button "Copy error" gives this:
TypeError: Cannot read properties of null (reading 'ResizeObserver')
    at http://website.local/wp-includes/js/dist/block-editor.min.js?ver=f0bb1e364b792257eb17:41:103660
    at Ur (http://website.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:73411)
    at Jr (http://website.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:80643)
    at Zr (http://website.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:80489)
    at Gr (http://website.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:80023)
    at http://website.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:91526
    at xl (http://website.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:92039)
    at fl (http://website.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:85808)
    at Nn (http://website.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:32474)
    at http://website.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:83226

### Screenshots, screen recording, code snippet

https://youtu.be/Bk9d5yw4RVE
https://i.ibb.co/vvVY5B7/Screenshot-2024-01-06-at-4-54-29.png
Clone from here: https://github.com/madfcat/wordpress-pattern-editor-bug

### Environment info

Wordpress version: **6.4.2**
Twenty Twenty-Four Version: 1.0
Version 120.0.6099.129 (Official Build) (arm64)
macOS Monterey
Version 12.6.5
MacBook Pro (16-inch, 2021)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I think this is because the block has an `href` attribute.

> Insert the block Click outside this block and the click on this block. The block becomes white.

Selecting a block means clicking on a link, which will redirect the canvas to an incorrect state. For example, I think you need to do some sort of process to disable link clicks, as shown below.

https://github.com/WordPress/gutenberg/blob/ffbc300ede03b6337cbd950130e99955132ea4fb/packages/block-library/src/avatar/edit.js#L153-L157

**Comment by madfcat** [comment]
> I think this is because the block has an `href` attribute.
> 
> > Insert the block Click outside this block and the click on this block. The block becomes white.
> 
> Selecting a block means clicking on a link, which will redirect the canvas to an incorrect state. For example, I think you need to do some sort of process to disable link clicks, as shown below.
> 
> https://github.com/WordPress/gutenberg/blob/ffbc300ede03b6337cbd950130e99955132ea4fb/packages/block-library/src/avatar/edit.js#L153-L157

Yes, event.preventDefault(); in onClick handle function solved the issue. Thank you!
