### ISSUE TITLE
__experimentalNumberControl doesn't show correct saved value on Editor.

### ISSUE THREAD

**Issue by Arifursdev** [WordPress/gutenberg#57618]
### Description

the `__experimentalNumberControl` doesn't show correct saved value on Editor. it saves the number server side and shows on frontend correctly but in editor it remains what was default or min after a reload

### Step-by-step reproduction instructions

Steps:
- after changing number field to lets say 5
- update and successfully updated
- reload the editor, the number field is back to 1 (default)
- check the SSR frontend var dump attributes: it shows MyNumber as 5 `["MyNumber"]=> string(1) "5"`

### Screenshots, screen recording, code snippet

Attribute is defined when registering block as a number and default 1
```php
[
    'type'  => 'number',
    'default'   => 1
]
```

JS responsible for the field
```js
....

const { __experimentalNumberControl } = wp.components;
el(__experimentalNumberControl, {
    label: 'My Number',
    value: attributes.MyNumber,
    shiftStep: 1,
    min: 1,
    onChange: (value) => {
      setAttributes({ MyNumber: value });
    },
  }),

...
```

### Environment info

Wordpress version: 6.4.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@Arifursdev Could you share the code of how the attribute you're using for the number control is declared?

Or alternatively a working reproduction.

**Comment by talldan** [comment]
I tried testing using the query loop block (which uses this component) and wasn't able to reproduce the issue, so I think there's a bit more to the problem.

**Comment by Arifursdev** [comment]
@talldan yeah, you can try create a simple block with the __experimentalNumberControl field only without any other things..
(I have switched from to raw "input" field for now, and it works perfectly. so it suggests clearly the issue with with that comp.

**Comment by Mamaduka** [comment]
I'm unable to reproduce the issue in Storybook - https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-numbercontrol--docs.

I'll close the issue; the problem seems related to the consumer code.
