### ISSUE TITLE
APP

### ISSUE THREAD

**Issue by zmlmf345** [WordPress/gutenberg#57628]
## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- WordPress app version:

**Comment by skorasaurus** [comment]
Hi, there's no information here for contributors to act upon it;

if you need to create a new issue; be sure to fill out all of the fields - https://github.com/WordPress/gutenberg/issues/new?assignees=&labels=%5BType%5D+Bug&projects=&template=Bug_report.yml
