### ISSUE TITLE
Finding advanced settings for blocks is tough

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#5764]
## Issue Overview
During recent moderated tests each interviewee generally struggled to find advanced settings for blocks and seemed to experience what I'd describe as "sidebar blindness". They were so focussed on the main content area.

## Possible Solution
A very simple solution would be to highlight/focus the block tab in the sidebar when a block is focussed. I think some subtle animation could work to make it obvious, but that might get annoying down the road. Perhaps we could apply some progressive reduction to remove that over time. Either way I think this could do with a little design exploration.

I understand that behaviour is how Gutenberg used to work, and I did find this issue; https://github.com/WordPress/gutenberg/issues/3340

I think this is worth revisiting in some way, though.

**Comment by karmatosed** [comment]
I totally agree we should when a block is focused have the sidebar advanced options show. This has been gone around (I can't find another issue with it but fairly sure there is one), the feedback coming here and in just using it is this is something for now we should go back to (we had it once).
