### ISSUE TITLE
It's not always obvious the block list in the inserter is scrollable.

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#5765]
## Issue Overview
Depending on the OS / Browser settings a scroll bar isn't always visually present, even if the content is scrollable (see screenshot). 

In recent moderated tests quite a few people totally missed that this section scrolls.

## Possible Solution
There's various design solutions we could implement to address this. 

* Fade the bottom of the inserter and overlay the bottom row of blocks
* A downward chevron to indicate scrolling
* Some subtle animation
* Probably more - I can have a play with this next week

## Screenshots / Video
![scrollllll](https://cldup.com/OMIeEqfKoc.png)

**Comment by karmatosed** [comment]
I think the gradual fade could be amazing here. Thanks for giving feedback about this.

**Comment by karmatosed** [comment]
@jameskoster just moving this to the design label for insights as it doesn't right now need a design as much as discussion.

I don't know a way to ensure the bottom is always partially visible, with the potential changes in the library though I think some solutions are solved here.

**Comment by karmatosed** [comment]
As we have iterations going on with the library, I think we may be good to close this now. Let me know if that's not the case though and we can reopen.
