### ISSUE TITLE
ToggleGroupControl: apply animation only when interacting with toggle

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#57668]
## What problem does this address?
Toggle button has a nice animation when toggling, but the animation gets applied also when something else in the surrounding UI changes location of the toggle on the screen:

https://github.com/WordPress/gutenberg/assets/87168/d6192e09-d70a-4bbf-a611-093a6d32e7fa

Note how changing other settings causes toggle animation to lag. That said, collapsing panels doesn't cause the same effect, so I'm not entirely sure what's in play here.

## What is your proposed solution?

Apply animation only `onChange`, and disable otherwise.

**Comment by mirka** [comment]
Are you able to provide some minimal repro code? At some point we fixed the issue of unwanted animations like this, so what you're seeing is probably a particular case. Like you mentioned, it doesn't usually happen on normal layout shifts, for example when toggling the `hideLabelFromVision` prop.

**Comment by mirka** [comment]
I'm assuming this will be fixed by #59642. Please re-open if not!

**Comment by tyxla** [comment]
Thanks for connecting the dots, @mirka, I didn't realize there was an open issue about it. And yes, that's exactly the one we were fixing.
