### ISSUE TITLE
Atlas: Block Patterns

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#57687]
Let's make block patterns out of some of the parts of the theme such as:

- the starscape cover area, and the cover block fallback
- the query block on the blog
- full page patterns if we want variations for the templates (different home pages, single with/without sidebar, etc)

**Comment by carolinan** [comment]
Is this meant to be in the Gutenberg repository? :)

**Comment by MaggieCabrera** [comment]
ugghh no, thanks @carolinan
