### ISSUE TITLE
RichText Block Missing formattingControls

### ISSUE THREAD

**Issue by TwisterMc** [WordPress/gutenberg#5768]
## Setup
WordPress 4.9.4
Running Locally with Local by Flywheel
Gutenberg 2.4.0 
One custom plugin where we're creating Gutenberg blocks

## Issue Overview
1. RichText blocks do not show any formatting controls by default as noted in the [documentation](https://github.com/WordPress/gutenberg/tree/master/blocks/rich-text). 
2. When adding `formattingControls` as shown in the documentation, no controls show.

## Steps to Reproduce (for bugs)

1. Create a new Gutenberg block that is a RichText block
2. Test it in Gutenberg and notice that no formatting controls show.

## Expected Behavior

I expect a formatting bar just like a paragraph block per the documentation.

## Current Behavior

No formatting bar shows.

## Screenshots / Video

https://cloudup.com/cHKzMpuZ7Jm

**Comment by youknowriad** [comment]
Did you pass the `isSelected` prop to the RichText component? `isSelected` should be true for the controls to show up.

**Comment by TwisterMc** [comment]
Well, that did it. 

I have some followup questions:

1. Any idea why `formattingControls` requires an additional field in order to make them appear? Is there a use case where we'd want to have controls but hide them?

2. Why does `isSelected` not default to true? It seems like a user would expect controls by default and then have the option to turn them off.

3. The documentation says "By default, all formatting controls are present" when in reality they are not. From the code perspective, yes, they are there, but from the user perspective, they are not.

I think setting `isSelected` to true would solve the concerns. Or, at the very least, the documentation is updated to note that even when `formattingControls` are enabled, they are hidden from the user.

**Comment by youknowriad** [comment]
> Any idea why formattingControls requires an additional field in order to make them appear? Is there a use case where we'd want to have controls but hide them?

You need to pass the `isSelected` prop coming from the block's props because you need to hide the controls when your block is not selected.

I think that answers the other questions too :)

**Comment by youknowriad** [comment]
That said, feel free to open a PR to clarify the docs :)
