### ISSUE TITLE
Edit permalink UI

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#577]
I'm not fully updated on all the things that were already discussed or already planned, so I might be missing something. If so, I apologize in advance for opening one more issue 🙂 

Looking at the [mockups](https://wpcoredesign.mystagingwebsite.com/gutenberg/) and searching through the GH issues, I couldn't find any reference to the Edit permalink form.

Are there any plans? How it should be integrated in the Plugin UI?

<img width="979" alt="permalink" src="https://cloud.githubusercontent.com/assets/1682452/25566246/8fe3650e-2dd5-11e7-85de-dfc02da3a7fb.png">

**Comment by jasmussen** [comment]
Here are some mockups:

![permalink](https://cloud.githubusercontent.com/assets/1204802/25578415/c6528d10-2e6e-11e7-9cd6-df0ac5996671.png)

![permalink hover](https://cloud.githubusercontent.com/assets/1204802/25578417/c7e15f4e-2e6e-11e7-97cd-ae3da14d6f6f.png)

![permalink opened](https://cloud.githubusercontent.com/assets/1204802/25578418/c9bcfb2a-2e6e-11e7-8b72-0d285ddd3f6c.png)

**Comment by iseulde** [comment]
I quite like that at first sight!

**Comment by melchoyce** [comment]
FWIW, it took me a long while to hunt this down when I was working on a new site on WordPress.com. It wasn't until I finally hovered over this icon that I realized it would let me edit the permalink. I think that could be made more clear.

**Comment by karmatosed** [comment]
+1 to making it clearer, I also have found myself hunting for it.

**Comment by jasmussen** [comment]
The balance to strike here is between that of an already very laden UI, and how often the feature will be used. In hindsight it would have been good to have a question in the survey: how often do you customize your permalink? If we knew for a fact that it was a power user feature, then requiring you to "learn it once" might be okay.

**Comment by jasmussen** [comment]
Here's an alternate design. 

Neutral:

![neutral](https://cloud.githubusercontent.com/assets/1204802/25849345/62fa6cf0-34be-11e7-84df-1fa86ce46089.png)


Selected:

![selected](https://cloud.githubusercontent.com/assets/1204802/25849298/2eeffb96-34be-11e7-9419-c751d319a4ac.png)

**Comment by iseulde** [comment]
I like how this last one is more similar to links in the content, but I worry that it's hard to discover.

**Comment by jasmussen** [comment]
> I like how this last one is more similar to links in the content, but I worry that it's hard to discover.

I think it's worth trying, because you'll seee it as an expanded link every single time you add a title. You may pick it up quickly.

**Comment by paaljoachim** [comment]
What about moving Permalink into the Post setting? Here is an example:

![gutenberg-permalink](https://user-images.githubusercontent.com/5323259/26965099-9c281cea-4cf4-11e7-96dd-062f801e7bde.jpg)

(Btw I removed Post Format. As I do not see the need to include it..)

**Comment by jasmussen** [comment]
The reason for putting permalink into the main body area, is that when it lives there you can access it even when you dismiss the post settings sidebar.

The idea being that a big chunk of people using WordPress might never want to change the post settings, and so they can just dismiss it and have a more immersive writing experience. And so the more the user can customize, in a non-heavy UI way, in the main body of the content, the better.

> (Btw I removed Post Format. As I do not see the need to include it..)

We all want to retire post formats :) And the fact that it's both in the Status and Visibility box (as opposed to a separate metabox), and also automatically inferred from the blocks you use, is a transitional step to removing them entirely. But in the near term I don't think we can completely remove them.

**Comment by paaljoachim** [comment]
`The reason for putting permalink into the main body area, is that when it lives there you can access it even when you dismiss the post settings sidebar.`

That is a very good reason! I would also say that today we are used to having the permalink associated with the title. Having it continue to be associated and directly connected with the title of the post/page is important. We need to look at connection/associations that exist in the current editor and see which of the associations are natural to bring along to the Gutenberg editor.

I like your newest mockup Joen. The one you shared on Slack that also includes an edit button.

![gutenberg-permalink-joen-mockup](https://user-images.githubusercontent.com/5323259/27001206-6fbfbc64-4dc4-11e7-9b3a-6d0ac972a533.png)

**Comment by aduth** [comment]
Partially resolved by: #1042 
Determining edit-ability may be blocked by: https://core.trac.wordpress.org/ticket/41014

**Comment by mtias** [comment]
Let's close and open individual tasks for clarity.
