### ISSUE TITLE
ToolbarButton: aria-disabled prop is also given the disabled attribute at the same time

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#57701]
### Description

For `Button` component, the `aria-disabled` prop is used instead of the `disabled` prop to make the button inactive but still focusable.

For example, the Undo/Redo button in the Post Editor or Site Editor.

![image](https://github.com/WordPress/gutenberg/assets/54422211/e6281c95-c61f-4376-96dc-0f462500ce7d)

https://github.com/WordPress/gutenberg/blob/5380b6c549668b94e38ae5619aa725f57ef7eb0f/packages/editor/src/components/editor-history/undo.js#L23-L36

On the other hand, `ToolbarButton` is used for the Undo/Redo button in the Widget Editor.

https://github.com/WordPress/gutenberg/blob/5380b6c549668b94e38ae5619aa725f57ef7eb0f/packages/edit-widgets/src/components/header/undo-redo/undo.js#L18-L27

It's mentioned that the `ToolbarButton` component accepts the same API as the `Button` component, but it seems like the `aria-disabled` prop also opts into the `disabled` prop at the same time.

![toolbar-button](https://github.com/WordPress/gutenberg/assets/54422211/55b5ab2d-72c4-4009-8c83-0fadc22dee1b)

As a result, as mentioned in #57647 and #57678, it is not possible to focus the Undo/Redo button in the Widget Editor when it is not enabled.

This can be solved by refactoring the Undo/Redo button into the `Button` component, as attempted in #57677, but if the current behavior of `ToobarButton` is not what we intended, I think it will need to be fixed.

### Step-by-step reproduction instructions

- Activate classic theme (Twenty Twenty-One).
- Open the Wdiget Editor.
- Use the tab key or arrow keys to move the focus within the header.
- You should not be able to focus on the Undo/Redo button.

### Screenshots, screen recording, code snippet

Note: In the screencast below, you can also see that the focus outline is cut off, but this issue should also be fixed separately.

https://github.com/WordPress/gutenberg/assets/54422211/bb192ba9-63ed-4d08-a9e4-5ce235fb9f77

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jeryj** [comment]
Would the `accessibleWhenDisabled` prop on `<ToolbarButton />` be useful here?

**Comment by t-hamano** [comment]
@jeryj Thanks for the reply.

I didn't know about that prop, but maybe it's something that's being attempted in [this discussion](https://github.com/WordPress/gutenberg/pull/57274#discussion_r1433434656)? If `accessibleWhenDisabled` can solve the problem, this issue may be closed.

**Comment by jeryj** [comment]
I did end up using accessibleWhenDisabled in the comment you linked to and it seems to be working. I haven't looked into this issue, but hopefully it helps!
