### ISSUE TITLE
Allow defining custom Aspect Ratio options through `theme.json`

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#57707]
There are a few places now where we allow users to select an Aspect Ratio for their Image. The list of available Aspect Ratios is hard-coded however. (See: https://github.com/WordPress/gutenberg/blob/5d063e3fbfbaaef0688e060ad16a1e5ed47fee26/packages/block-library/src/post-featured-image/dimension-controls.js#L93-L126)

This means that there is currently no way to use any aspect ratios that are not a part of this predetermined list. 

Especially in more custom designs we are working with style guides that go down to the aspect ratio level and not being able to filter / override the ratios that should be available is a real issue. 

Ideally this could work similar to the `spazingSizes` preset in `theme.json` where a theme author and eventually maybe even the global styles interface would be able to define the available aspect ratios.

My proposed syntax would be:

```jsonc
{
    "version": 2,
    "settings": {
        "dimensions": {
            "aspectRatios": [ // allows you to define custom aspect ratios
                {
                    "slug": "5by4",
                    "label": "5:4",
                    "value": "5/4"
                }
            ],
            "defaultAspectRatios": false // disables the core provided ones
        }
    }
}
```

**Comment by fabiankaegy** [comment]
Regarding the `AspectGroups` I think we should be able to programmatically determine whether something is Landscape or Horizontal:

https://github.com/WordPress/gutenberg/blob/5d063e3fbfbaaef0688e060ad16a1e5ed47fee26/packages/block-editor/src/components/image-editor/aspect-ratio-dropdown.js#L49-L114

**Comment by justintadlock** [comment]
There's a PR for theme-defined aspect ratios here: https://github.com/WordPress/gutenberg/pull/47271

**Comment by annezazu** [comment]
Looks like this can be closed out with https://github.com/WordPress/gutenberg/pull/47271 merged. Closing but happy to reopen if I'm missing an aspect of this.
