### ISSUE TITLE
FormTokenField with Object as suggestions creates an error on input

### ISSUE THREAD

**Issue by Dominic-Marcelino** [WordPress/gutenberg#57724]
### Description

When using the `FormTokenField` component it allows us to pass custom `saveTransform` & `displayTransform` function as props. Imho the main use-case for this is to allow the usage of suggestions in other formats than a string array. 

When using a custom object for suggestions in combination with both thansformers the displaying and selecting from the list work as expected. Unfortunately this creates an error on input, as the comparator always expects a string 

https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/form-token-field/index.tsx#L515-L516

### Step-by-step reproduction instructions

I've created a reproduction:
https://stackblitz.com/edit/vitejs-vite-51xmqg?file=package.json,src%2FApp.jsx&terminal=dev

1. Click into the input
2. Select on of the option (works)
3. Try to delete an option (works)
4. Try to type an input (creates an error)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mirka** [comment]
This is the expected behavior, as can be seen in our [docs](https://wordpress.github.io/gutenberg/?path=/docs/components-formtokenfield--docs) and TypeScript types. The two transform functions expect a string argument, and `suggestions` is expected to be an array of strings.

Is this more of a feature request so it also accepts objects, for convenience? On the whole I feel like it would be a lot simpler if the consumer were responsible for that kind of data translation. For example in the repro case you've provided, it would be trivial to map the array of objects into an array of strings so it can be passed to the `suggestions` prop. And whatever metadata that needs to be referenced for the transforms, the consumer is still free to take any suitable approach (e.g. linear search through a short array, use a separate key-value store, etc). Thoughts?

**Comment by Dominic-Marcelino** [comment]
>Is this more of a feature request so it also accepts objects, for convenience? 

Imho it's a feature request for something that should be there and the docs imply that it can be done.

> On the whole I feel like it would be a lot simpler if the consumer were responsible for that kind of data translation. For example in the repro case you've provided, it would be trivial to map the array of objects into an array of strings so it can be passed to the suggestions prop.

That's indeed possible and also what I did for now. But I don't see what the transformers should be used for if not to provide a way to interpret a more complex data source. If I already have to break down my data into a simple string array before, there's no need for the transformer anymore. Also I think it can be easily extended to work. As mentioned everything except from the comparator already works.

From my pov I'd even **EXPECT** the comparator to use the display value (or a custom defined comparator), as otherwise it ends in a pretty bad UX when one value is displayed but another one is used for the search comparison.

example:
_You have a simple sting-array of category-ID. The display transformer maps some human readable names to the category-ids. It displays it as `<category-name> (<ID>)`. As an end-user I'd expect that I'm able to search for the category-name but in the current state I'd only be able to search for the IDs._

Looking forward to your thoughts about that.

**Comment by mirka** [comment]
> I don't see what the transformers should be used for if not to provide a way to interpret a more complex data source. If I already have to break down my data into a simple string array before, there's no need for the transformer anymore.

I do see your point. As we can see from the prop descriptions for the transformers in the docs, they were intended for pretty specific purposes (i.e. decoding HTML entities for display and trimming token values for save), not the more generic purposes you had in mind.

> the docs imply that it can be done

From what I can see, neither the docs nor TypeScript types contradict the current behavior, but if you have suggestions to improve the docs so we can better set expectations around this, we'd welcome any PRs!

In the mid- to long-term, we are considering moving the FormTokenField and ComboboxControl components to a more modular subcomponent-based API so consumers can have much more control over the filtering and rendering. See this [Ariakit example](https://ariakit.org/examples/combobox-textarea) that will give you a rough idea of what the next-gen API might look like.

Unfortunately though, with this API revamp on the roadmap, it means we are less likely to be adding more enhancements to the current FormTokenField component.

Does that make sense? Let us know if you have any feedback.

**Comment by Dominic-Marcelino** [comment]
```
In the mid- to long-term, we are considering moving the FormTokenField and ComboboxControl components to a more modular subcomponent-based API so consumers can have much more control over the filtering and rendering. See this [Ariakit example](https://ariakit.org/examples/combobox-textarea) that will give you a rough idea of what the next-gen API might look like.

Unfortunately though, with this API revamp on the roadmap, it means we are less likely to be adding more enhancements to the current FormTokenField component.
```

Thanks for the insights! In that case I think the issue can be closed
