### ISSUE TITLE
Create a Keyboard Shortcut for Grouping Blocks

### ISSUE THREAD

**Issue by samxmunoz** [WordPress/gutenberg#57739]
It would be very helpful to have a keyboard shortcut to group blocks together.

<img width="550" alt="Screenshot 2024-01-10 at 2 50 48 PM" src="https://github.com/WordPress/gutenberg/assets/43501707/640ed21c-e656-4099-847b-06c0b0460e7b">

Perhaps something like `⌥⌘G`

Thank you!

Sam Brockway

**Comment by t-hamano** [comment]
Thanks for the report.

I would like to close this proposal since it was made in #42227. By the way, a PR has also been submitted to make this happen.

- #46972

**Comment by samxmunoz** [comment]
Thank you @t-hamano I couldn't find an issue/proposal but thank you for bringing it to light. I appreciate you!

Sam
