### ISSUE TITLE
Sidebar meta boxes toggle arrows unclear and inconsistent with WordPress patterns

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#5774]
In the sidebar, the meta boxes use arrow icons for the toggle buttons:

<img width="442" alt="screen shot 2018-03-24 at 12 51 31" src="https://user-images.githubusercontent.com/1682452/37863732-8238ec22-2f63-11e8-9813-bd95b1b8b510.png">

Depending on the meta boxes closed / open state, the icons change position, as usual with this kind of visual indicators. However, I'd like to propose to reconsider the way these icons are used, as they don't clearly suggest the underlying _action_ of the toggle control.

Let's make a quick comparison between existing patterns in WordPress, focusing on the "Featured Image" meta box. See screenshot below:

WordPress:
- when closed, the icon points down and suggests that clicking it, something will appear below
- when open, the icon points up and suggests the panel will collapse

Gutenberg:
- when closed, the icon points to the right: I'm not sure why, as it visually suggests something will appear from the right or the panel will slide in an horizontal direction
- when open, the icon points down: this indicates the current state rather than the available action of the control and I think it's potentially confusing

Worth also considering the Gutenberg pattern is inconsistent with the established pattern in WordPress, where in many, many, places the icons point down and up. For example, in the Customizer but also in the Dashboard, Widgets screen, Menus screen, Edit post screen, basically everywhere.

Consistency is key and I'd strongly recommend to not force users to learn and adapt to new patterns across the whole WordPress UI.

<img width="636" alt="screen shot 2018-03-24 at 12 19 17" src="https://user-images.githubusercontent.com/1682452/37863837-5779a7cc-2f65-11e8-8741-fb626bb0e73e.png">

**Comment by karmatosed** [comment]
I think changing this makes sense. Do you want to work on a PR @afercia?

**Comment by afercia** [comment]
I can try :)
