### ISSUE TITLE
Block renaming: retain name when transforming to a different block

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#57752]
## What problem does this address?
At the moment, when you transform a named block to a different block type, the name given is lost.

## What is your proposed solution?
It'd be great to retain the name.

Potentially the entire `metadata` could be retained 🤔

**Comment by getdave** [comment]
> Potentially the entire metadata could be retained 🤔

👍

**Comment by talldan** [comment]
Superceded by #59086
