### ISSUE TITLE
Pages data view: Update title field so that homepage and posts page are marked with a badge

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#57763]
In wp-admin this is achieved with a text label:

<img width="587" alt="Screenshot 2024-01-11 at 14 21 48" src="https://github.com/WordPress/gutenberg/assets/846565/e44787fc-63ca-4e6a-b9c1-f33920280eed">

In the current pages list the homepage and posts page appear at the top with icons to denote their purpose:

<img width="357" alt="Screenshot 2024-01-11 at 14 22 22" src="https://github.com/WordPress/gutenberg/assets/846565/c0bccc8d-4557-4b29-ae72-6c8a91f6eef0">

In the pages data view there is no indication at all about which page serves as the homepage / posts page. Lets come up with a design to achieve this.

---

There are other situations where such a pattern can be useful – for instance the privacy policy page in core, and the shop / cart / checkout pages are also marked this way – so it could be worth implementing this in a reusable/extendable fashion.

**Comment by jameskoster** [comment]
Accounting for the different layouts I think the safest initial approach here may be to add a text label:

<img width="1391" alt="page marking" src="https://github.com/WordPress/gutenberg/assets/846565/422f80f0-ec06-4a81-9a91-4e9bc52d8119">

**Comment by youknowriad** [comment]
Is this the same "badge" kind of fields that we have in "patterns" for the sync status? Because the design looks different to me in the mockups.

**Comment by jameskoster** [comment]
It depends whether this data is a field, technically speaking. I could be convinced otherwise, but I didn't see it as one for a couple of reasons;

1. There can only be one home / posts page
2. I don't know that you'd ever sort / filter by 'is home page'
3. It doesn't feel like a field you'd ever toggle _off_, and given all pages except one would be `false`, it seems a waste of space in the table.

My feeling was that it should be a badge, appended to the title field. Ideally we [graduate the badge to a component](https://github.com/WordPress/gutenberg/issues/61106) for consistent display, but that can happen later.

**Comment by youknowriad** [comment]
Ok, so you're saying that this is just a different rendering for the "title" field. That could work.

**Comment by oandregal** [comment]
Going to give this one a quick shot.

**Comment by oandregal** [comment]
PR at https://github.com/WordPress/gutenberg/pull/61718
