### ISSUE TITLE
Delete the parent buttons block when the last button is deleted via "Delete"

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#57767]
Currently, if I delete the last `core/button` block using the block options menu, I then also have to delete the `core/buttons` wrapper block.  But if I delete the _text_ of the button, it properly removes the buttons block—we should do that same auto-deletion, regardless of the delete method. 

### Visuals

Buttons block remains, when deleting via the block options "Delete" control: 

https://github.com/WordPress/gutenberg/assets/1813435/eedad067-e7fe-4222-949c-33247f509e14

Buttons block is removed, when deleting by deleting the text of the last button (expected): 

https://github.com/WordPress/gutenberg/assets/1813435/af344755-0650-47bb-bd33-86e86cbc752c

**Comment by Mamaduka** [comment]
I can no longer reproduce the issue. I can't pinpoint the exact PR that fixed it, but it could be the #61889.

cc @ellatrix
