### ISSUE TITLE
Add ability to increase the font size for lists

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#5777]
As I mentioned in #5775, for lists having the font size option would be good also. This came up in recent testing, there is a strong argument that for any text we should allow that option.

> With a paragraph we finally see how to change the font size, this is missing for the quote block. The same change for the font size is missing for the list block.

**Comment by karmatosed** [comment]
I am closing as this on every block would be part of phase 2 if at all.

**Comment by aleciabeck** [comment]
We definitely need to be able to change the font size of lists and of single characters inside a block without changing the size of the rest of the text in a block
