### ISSUE TITLE
Image block influences spacing in list block below it

### ISSUE THREAD

**Issue by IreneStr** [WordPress/gutenberg#5778]
## Issue Overview

When a bulleted list block is added below an image block with align left and a caption, at some very specific image sizes, there will be whitespace between the first bullet and the text after the first bullet (see gif below).

## Steps to Reproduce (for bugs)

1. Add an image block and click 'align left'.
2. Add a one-line caption
3. Add something on the right of the image, for example a quote.
4. Below the image-quote block, add a list block with some bullet point.
5. Play a bit with the size of the image, until you see the described situation.
6. Also notice that with some image sizes you will see the gap between the bullet and text when the image block is active (= clicked), but it looks fine when it's not active (= not clicked)

NB. Once, I've run into the same bug without a caption, but I wasn't able to reproduce that situation.

## Expected Behavior

No gap between the bullet and its text/no influence from the block above the list block.

## Current Behavior

A gap between the bullet and its text/influence from the block above the list block.

## Screenshots / Video

![Image and list](https://user-images.githubusercontent.com/17744553/37865562-857d318e-2f7e-11e8-97e3-affcc7ddd4da.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Related #6634 #4127 #4010 #5885 #6172

**Comment by mtias** [comment]
Closing in favor of #4127.
