### ISSUE TITLE
Add a screen reader text option to RichText

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#57799]
## What problem does this address?

There is no easy way for users to add screen reader texts that they can edit in the editor but are visually hidden on the front.
WordPress uses a CSS class, `.screen-reader-text` to visually hide elements, but even if the user is aware of this feature, this class also hides the element in the editor.

## What is your proposed solution?

Add a screen reader text option to RichText.
Just like the RichText toolbar options can be used to wrap text within elements like `<strong>` and `<em>` it could be used to wrap text inside a span with a CSS class that only hides the element on the front.

**Comment by skorasaurus** [comment]
Hi @carolinan ; I believe this is being discussed in https://github.com/WordPress/gutenberg/issues/22332  please reopen if I misunderstand.
