### ISSUE TITLE
Font Library: Uploaded custom font not included in exported Block Theme

### ISSUE THREAD

**Issue by bfintal** [WordPress/gutenberg#57801]
### Description

The custom font I've uploaded isn't included when exporting the Block Theme. The custom font is still selected in style typography settings though.

### Step-by-step reproduction instructions

1. Open nightly in Playground: https://playground.wordpress.net/?wp=nightly&plugin=gutenberg
2. Go to Site Editor and upload a custom font
3. Use the custom font for headings
4. Export the theme
5. Open a fresh site and install and activate the exported theme
6. See that the uploaded font is not there

### Screenshots, screen recording, code snippet

If you check the exported `theme.json`, the font file is not found in there - it's source is referenced from the original. For example, I've uploaded a copy of DM Sans:

```json
{
	"fontFace": [
		{
			"fontFamily": "DM Sans",
			"fontStyle": "normal",
			"fontWeight": "100 1000",
			"src": "https://playground.wordpress.net/scope:0.0731139000825751/wp-content/fonts/dm-sans_normal_100-1000.ttf"
		}
	],
	"fontFamily": "'DM Sans'",
	"name": "DM Sans",
	"slug": "dm-sans"
}
```

### Environment info

https://playground.wordpress.net/?wp=nightly&plugin=gutenberg
- WordPress 6.5-alpha-57272
- Gutenberg 17.4.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mikachan** [comment]
Thanks for reporting, @bfintal! We're discussing how best to handle font exports when a theme is exported here: https://github.com/WordPress/gutenberg/issues/54226. I'll close this issue as a duplicate, but please feel free to join in the discussion there.
