### ISSUE TITLE
Gutenberg saves a huge number of revisions

### ISSUE THREAD

**Issue by mhsabbagh** [WordPress/gutenberg#5781]
## Issue Overview
When writing a new post using Gutenberg, the editor seems to be saving a revision each second, which causes a huge number of revisions to be stored for just one post. E.g: Yesterday I wrote a post of 700 words using Gutenberg, the editor created 225 revisions for that post alone.

This is huge, and causes the database usage to rise and could cause some bandwidth/storage issues on limited environments.

## Steps to Reproduce (for bugs)
1. Go to the new post page.
2. Start writing some words, adding some images or modifying blocks continuously.
3. After a minute or two of continues writing and editing, check the revisions number.

## Expected Behavior
Gutenberg should have created a way less number of revisions, instead of doing it almost every second.

## Current Behavior
Gutenberg seems to create a revision each second, each revision includes a difference of the new words that you wrote before you stop for a split second while writing.

Also, Gutenberg seems to take a revision each new block is created/modified/deleted instantly.

## Screenshots / Video
![gutenberg-bug](https://user-images.githubusercontent.com/1293003/37873694-9538ebd4-302a-11e8-8ae3-4e3c3744f585.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ocean90** [comment]
Thanks for the report. This is being tracked at #3656.
