### ISSUE TITLE
wautop from code view in classic editor

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#5783]
## Issue Overview

If you edit an existing Gutenberg edited page that has blocks, then edit the page/post using the classic editor using its code view, switch to visual, then save, and then switch back to the Gutenberg editor, any lines that were blank will have a `<p>&nbsp;</p>` added, generating tons of new, unwanted blocks.

And people WILL do this.

## Steps to Reproduce (for bugs)

1. See description.
2.
3.
4.

## Expected Behavior

Layout looks the same in Gutenberg before and after editing with classic editor.

## Current Behavior

Unwanted new `<p>` blocks.

## Possible Solution

Disable wautop when Gutenberg has been used.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
This issue seems to be the same as #6385 which has greater detail. Please re-open if you think this not to be the case.
