### ISSUE TITLE
[Question] Can core blocks be extended?

### ISSUE THREAD

**Issue by jahvi** [WordPress/gutenberg#5785]
Is it possible to 'extend' the functionality of core blocks? If not, are there any plans to allow plugins to do so?

My use case is that I'm trying to integrate my [Category Filter](https://wordpress.org/plugins/admin-category-filter/) plugin to work with Gutenberg however I'm not sure how to do so without directly messing with the `TaxonomyPanel` component.

**Comment by gziolo** [comment]
There are a couple of ways how core blocks can be extended or modified. You can see more in here: https://github.com/WordPress/gutenberg/blob/master/docs/extensibility/extending-blocks.md.

We provide a few hooks which make it possible to change core blocks. We are still working on making it more robust so it is still considered experimental. However, we encourage every plugin developer to give it a try.

It seems like in the case you mentioned `blocks.registerBlockType` would be the filter to look at. It allows to override `edit` implementation of the core block. It might be a lot of work to reimplement the `edit` experience with your own logic. Can you share more details what exactly should change in the logic of the existing blocks with your plugin? Is it about UI or data or both?

**Comment by jahvi** [comment]
Thanks for your reply, it definitely points me in the right direction.

I'm my case I'd say it's both data and UI, the way my plugin currently
works is that it adds a text input to the top of the taxonomy list (UI) and
it lets you filter the terms based on what you type (data?). I'll start
playing around with the filters and report my experience.

**Comment by jahvi** [comment]
I think I've hit my first roadblock, I tried using the `blocks.registerBlockType` filter to get a list of block names that I can extend like this:

```js
function getBlockSettings( settings, blockName ) {
    console.log(blockName);
    return settings;
}

wp.hooks.addFilter(
    'blocks.registerBlockType',
    'post-taxonomy-filter/test-function',
    getBlockSettings
);
```

However the list that comes back are block names (which makes sense) however I need to extend one of the core components in the sidebar (`<TaxonomyPanel>` I believe) which is not technically a block.

<img width="269" alt="screen shot 2018-03-30 at 9 38 10 pm" src="https://user-images.githubusercontent.com/661330/38153175-24c3a7e4-3463-11e8-87c5-1205bba85b6c.png">

Can I still extend it somehow?

**Comment by jasmussen** [comment]
To answer the original question, Riad has a bunch of information here as well: https://riad.blog/2017/10/16/one-thousand-and-one-way-to-extend-gutenberg-today/

Closing this ticket as part of some repository management. Support questions are most welcome in the [WordPress core slack](https://make.wordpress.org/chat/), channel #core-editor, or in the [plugin support forum](https://wordpress.org/support/plugin/gutenberg).

**Comment by gziolo** [comment]
Related issue: #6023.
