### ISSUE TITLE
Text highlighting (selection) issues in versions since 17.4.0

### ISSUE THREAD

**Issue by tommusrhodus** [WordPress/gutenberg#57894]
### Description

Text selection is buggy in Gutenberg versions 17.4.0+, 17.3.x versions tested do not exhibit this issue.

Selecting text seems to result in incomplete selections as your selection "flashes" back an arbitrary selection of text. Best described by the attached video. 

Note: attached video is on a custom theme, but this issue is easily reproduced on a fresh install. 

### Step-by-step reproduction instructions

1. Create a fresh install of WordPress.
2. Install Gutenberg 17.4.0+
3. Go to the auto created "sample page"
4. Select text in the blockquote block, full selection, partial selection (may take a few re-selections to trigger)
5. Observe the selected text flash to an arbitrary substring of what you actually selected.

### Screenshots, screen recording, code snippet

https://www.loom.com/share/adeb45b1296f423c9fe4a57f0cd44195?sid=5f1d3458-3e95-472c-8fa6-a3994c1cea55

### Environment info

- WordPress Latest
- Gutenberg 17.4.1
- Chrome 120.0.6099.216

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tommusrhodus** [comment]
Confirming this bug still occurs in Gutenberg 17.5.0

I've found it most reproducible if you end your selection (let go of mouse click) outside the bounds of the block you're selecting text in. e.g In a blockquote block, select all the text then keep mouse dragging until you're out of the left-hand bounds of the block, upon releasing the mouse click you should see the selection jump to only a portion of the string, rather than the whole block.


https://github.com/WordPress/gutenberg/assets/3149464/1e9bc685-a295-48cd-b8ac-1838346cd963

**Comment by tommusrhodus** [comment]
Confirming this issue still exists as of release 17.5.2

**Comment by toncijajic** [comment]
Issue still exists in Version 17.6.1

**Comment by draganescu** [comment]
#58552 should have fixed this in `trunk` unless I am mistaking the bug in being similar to #58465
