### ISSUE TITLE
Tooltips are ignoring spelling rules by enforcing only the first character to be uppercase 

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#5789]
Introduced in #4832 and the language issue was already mentioned in https://github.com/WordPress/gutenberg/pull/4832#discussion_r168813774 by @mtias.

The "More options" tooltip for the block settings menu is in German "Weitere Optionen" with a capital "O". But because of https://github.com/WordPress/gutenberg/blob/f8369387c1bf88f1a20423b0ab7279ca302b2f64/components/tooltip/index.js#L181 it's a lowercased "o".

<img width="337" alt="more-options" src="https://user-images.githubusercontent.com/617637/37879287-ef9ec20a-3076-11e8-95b5-39fd49205b0a.png">

**Comment by aduth** [comment]
Suggestion: Remove the code transform, fix existing errors on a case-by-case basis.

cc @Rahmon
