### ISSUE TITLE
Double enter should break out captions and lists (and similar) and onto a newline

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#579]
From Ella:

> break out of the caption if the line is empty (so double enter to break out). This seems in line with WP's current block quote behaviour, where you break out the quote if you hit enter in the last paragraph and it is empty.

This should apply captions and list blocks, and probably other similar ones.

**Comment by iseulde** [comment]
I think number one seems expected.

3rd option: break out of the caption if the line is empty (so double enter to break out). This seems in line with WP's current block quote behaviour, where you break out the quote if you hit enter in the last paragraph and it is empty.

Option 2 question: what happens if you're _not_ at the end?

**Comment by jasmussen** [comment]
> 3rd option: break out of the caption if the line is empty (so double enter to break out). This seems in line with WP's current block quote behaviour, where you break out the quote if you hit enter in the last paragraph and it is empty.

I like that. Also handily provides an answer to your solid followup option 2 question.

**Comment by melchoyce** [comment]
> 1. You make a linebreak inside the caption (or paragraph break or whatever)

+1 — this is how I'd expect it to work. 

> 3rd option: break out of the caption if the line is empty (so double enter to break out). This seems in line with WP's current block quote behaviour, where you break out the quote if you hit enter in the last paragraph and it is empty.

+1 to this as well :)

**Comment by mtias** [comment]
I am not sure about breaking out of the caption with enter.

**Comment by jasmussen** [comment]
> I am not sure about breaking out of the caption with enter.

Just to be clear, it's enter enter —  that is, enter on an empty line. Would you prefer the way to break out of a caption would be tab or arrow keys?

**Comment by iseulde** [comment]
See also #374

**Comment by mtias** [comment]
The case where you start breaking within the middle of a caption complicates it. Also as we consider all the new blocks being created, "breaking" the content of a block field by hitting enter is going to be fragile and convoluted. I think in most cases we should just remain within the editable field you are in.

**Comment by jasmussen** [comment]
Per this discussion, let's embrace the block, and close this for now. Tab will escape you. And if that isn't enough, we can reopen.
