### ISSUE TITLE
Add body class to reflect sidebar state

### ISSUE THREAD

**Issue by ControlledChaos** [WordPress/gutenberg#5793]
As someone who modifies the admin I think it would be advatageous to add the `is-sidebar-opened` class to the body rather than to the `edit-post-layout` div. This would be particularly helpful with custom admin headers and footers where the state of the sidebar affects layout design.

Currently testing with v2.4.0

**Comment by mtias** [comment]
The sidebar is supposed to be internal state of editor UI view. We could consider adding a class to the editor wrapper, but we don't want to be controlling body classes from within the editor state.

**Comment by ControlledChaos** [comment]
I don't to whom you refer as "we" when dismissing this issue, but as far as I am concerned it is not closed. My testing has found the toggling of the sidebar class to be problematic with less rigid and archaic layout thinking such as the absolute positioning use in the default design. It is far easier to implement flexbox & grid layouts, as well as admin headers and footers, if the `is-sidebar-opened` class is applied to the body element; taking into consideration the admin screen as a whole rather than simply concentrating on the editor.
