### ISSUE TITLE
Latest Gutenberg update seems to have broken Yoast SEO

### ISSUE THREAD

**Issue by bobthemovieman** [WordPress/gutenberg#57976]
### Description

Yoast SEO panel is not loading - see picture. . 
![No yoast](https://github.com/WordPress/gutenberg/assets/138369371/8fe84259-7b7a-423e-ac4b-f7ee41f3bbbf)

Issue only appeared after last update (17.5.0)

### Step-by-step reproduction instructions

1) Enable Troubleshooting mode (standard theme and all plugins disabled) 
2) Enable Yoast SEO in troubleshooter
3) Edit an existing post - the SEO panels in the post appear OK;  
4) Enable Gutenberg. Refresh post and the SEO panels disappear; 
5) Disable Gutenberg. Refresh post and they all appear again. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/138369371/d8f6db6b-d78b-423c-b5db-63c4f5a520b6

### Environment info

- Gutenberg v 17.5.0.  Standard theme (Twenty Twenty-Three in Troubleshooting mode)
- Wordpress 6.4.2
- Chrome browser
- Windows 10 on laptop

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Maktexas** [comment]
I am having the same issue.

**Comment by bobthemovieman** [comment]
Good - glad its not just me.

**Comment by tacoverdo** [comment]
Thanks for your report. The Yoast team is aware of this problem and is looking into the quickest solution to the problem.

Update: Yoast will release a patch to resolve this tomorrow, January 19th.

**Comment by Maktexas** [comment]
thank you!

**Comment by t-hamano** [comment]
This issue looks similar to the issue reported in the wp-calypso repository.

- https://github.com/Automattic/wp-calypso/issues/86601

It also appears that a PR has been submitted to resolve this.

- https://github.com/WordPress/gutenberg/pull/57988

**Comment by tacoverdo** [comment]
On the Yoast side, version 21.8.1 is now available, which fixes this compatibility issue. 
You can find the update in your website's admin dashboard, or download it at https://wordpress.org/plugins/wordpress-seo/.

**Comment by bobthemovieman** [comment]
Thank very much. Appreciate the prompt fix.

Dr Bob Mann
07543 203471
One Mann’s Movies
www.onemannsmovies.com
________________________________

**Comment by jordesign** [comment]
As Yoast have fixed this on their end- I will close this issue
