### ISSUE TITLE
get_post_galleries() support for Gutenberg

### ISSUE THREAD

**Issue by Themeone** [WordPress/gutenberg#5797]
## Issue Overview

To fetch galleries in post content, `get_post_galleries()` or `get_post_gallery()` can be used. But, currently, it only relies on shortcodes syntax. So, it may break themes and plugins which are using these functionalities. For example, Jetpack plugin is using `get_post_galleries()` to fetch gallery images.
Due to the generic name of these functions, it seems necessary to add support for Gutenberg Gallery blocks.

## Steps to Reproduce (for bugs)

1. Insert a Gallery block in Gutenberg
2. Use `get_post_gallery()` to fetch the first gallery in post content
3. An empty array is returned from `get_post_gallery()`

## Expected Behavior

`get_post_galleries()` or `get_post_gallery()` should return a list of arrays containing Gallery block(s) when using Gutenberg as well as Gallery shortcodes as fallback.

## Current Behavior

`get_post_galleries()` or `get_post_gallery()` return empty array with Gallery block(s).

## Possible Solution

Implement a new Gallery block detection method for `get_post_galleries()` or a new dedicated function also used in `get_post_galleries()`.

**Comment by pento** [comment]
Thank you for the bug report, @Themeone!

I agree that it should work as you discribe, unfortunately it's not something we can fix in the Gutenberg plugin: `get_post_galleries()` doesn't provide the necessary filters for us to add support for returning gallery blocks.

With that in mind, I've opened a [core ticket](https://core.trac.wordpress.org/ticket/43826) to track this issue, as it's not something we can tackle until after the block editor has been merged into Core (but before 5.0 is released, of course). I'll close this issue, so we're only tracking it in one place.
