### ISSUE TITLE
|Feature Request| Make links dynamic using ID

### ISSUE THREAD

**Issue by josch87** [WordPress/gutenberg#5799]
## Issue Overview

When linking to an internal item (page, post, document) the absolute URL is added. When the permalink of the linked item changes, the user is beeing forwarded. The embedded links still stay the same. 

## Steps to Reproduce (for bugs)

1. Link to page http://example.com/pagealpha/ on any page/post
2. Change permalink of /pagealpha/ to /pagebeta/
3. Go to page/post where Link is embedded. Links stills links to /pagealpha/
4. After clicking on the link you are being transfered to /pagealpha/ and then forwarded to /pagebeta/

## Expected Behavior

Link to new permalink.

## Current Behavior

Linking to old permalink and then being forwarded. How is forwarding actually working? What if someday a new post gets old permalink /pagealpha/?

## Possible Solution

Instead of inserting absolute permalink you could:
* [Link Without Using Permalinks](https://codex.wordpress.org/Linking_Posts_Pages_and_Categories#Linking_Without_Using_Permalinks) and use ID in URL parameter
?p=123 (post) ?cat=7 (category) page_id=42 (page) and so on
CON: this URL parameter containing the ID is being given in frontend
* BETTER: use dynamic links by setting the ID in backend and WordPress retrieves the permalink and inserts it for frontend sourecode. 
Shortcodes Ultimate is currently doing it using [Permalink shortcode](https://getshortcodes.com/shortcodes/permalink/)
  * make it possible to search for all elements (post, page, taxonomy terms ...)
  * clicking on an item references only ID

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @josch87. At this point, we'll continue to follow WordPress' existing behavior of inserting the entire link.

**Comment by bobbingwide** [comment]
Shame. This is a very sensible requirement that should be added to a backlog of Feature Requests. I use `[bw_link ID]` to automatically set the text to match the current title of the post.
