### ISSUE TITLE
Show block controls on hover

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#58]
The move up/down arrows should show when you hover over a block as well.

**Comment by jasmussen** [comment]
See also mockups for drag and drop in #38

**Comment by jasmussen** [comment]
Updated visuals for the hover UI:

<img src="https://cloud.githubusercontent.com/assets/1204802/23120267/e8d99828-f75b-11e6-91fb-cb137d6fe12b.gif" />

**Comment by jasmussen** [comment]
Closing as fixed in UI prototypes.
