### ISSUE TITLE
Font Library: Google Font have more Option Select and install all

### ISSUE THREAD

**Issue by ghorivipul97** [WordPress/gutenberg#58011]
## What problem does this address?
if we have more then 1 variation then hard to select one by one checkbox.

## What is your proposed solution?
User able to Select & Install All Font 
<img width="708" alt="image" src="https://github.com/WordPress/gutenberg/assets/49809429/d8f395a1-86ac-4c04-9a5c-4e949880686c">

**Comment by creativecoder** [comment]
There's a performance consideration here that's worth considering when looking at the UI design--generally it's best to select only the variants you plan to use and not just install all of them, since loading a lot of fonts on the front-end of the site can add to overall loading time.

Personally I'd argue against including an install/select all button when installing fonts to encourage selecting only what's needed.

**Comment by jasmussen** [comment]
There's a duplicated issue here, where @creativecoder graciously [responded to my inquiry](https://github.com/WordPress/gutenberg/issues/59704#issuecomment-2048051003) on what performance issue specifically was at play:

> So selecting all the variants of a font doesn't cause a performance problem by itself--it's one extra line of html added to the page for each variant. The performance issue comes if all the variants are available, and the styles settings on a page call for loading all of them (e.g. you've picked lots of similar but different weights in the styles settings for blocks that load on the page).

Ah, thanks for clarifying. But to me that's even more an argument for allowing the "select all" checkbox, and instead potentially show a warning notice if you're using too many fonts in a page, can be in pre-publish, can be in the typography panel, can be a snackbar, etc. 

Adding the "select all" checkbox is not just about the ergonomics of not having to click upwards of 20 times for some of the bigger font families (I wouldn't want to click that many times if I'm motor impaired!) It's also about recognizing this same data view pattern as it's being applied across the data views work for pages, templates, etc:
![screenshot of page table in the site editor](https://github.com/WordPress/gutenberg/assets/1204802/c817d8e6-0234-412c-83aa-bf347f0015db)

By omitting the checkbox, we're not protecting you from using too many fonts, or even warning that it's bad. We're just creating an interface that requires more clicks, and which diverges from the list view work that is ongoing. 

I'd love to see this added, in other words 🙏
