### ISSUE TITLE
Cannot use mouse to select URLs in links

### ISSUE THREAD

**Issue by markjaquith** [WordPress/gutenberg#5804]
## Issue Overview
If you try to edit a hyperlink and use your mouse to drag a selection in the URL, it thinks you're selecting blocks, and ejects you from the link editing UI.

## Steps to Reproduce (for bugs)

![kapture 2018-03-26 at 13 42 37](https://user-images.githubusercontent.com/353790/37922881-c7a1fbc0-30fb-11e8-909a-ef1f1e279c5b.gif)

## Expected Behavior

Unless I click outside of the link dialog, I should stay in it.

## Current Behavior

I get ejected from the dialog.

**Comment by aduth** [comment]
I _think_ the link dialog uses a custom implementation instead of the `Popover` component, so might be possible to fix with a refactor to the standard component.

**Comment by designsimply** [comment]
Tested with WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 and Chrome 67.0.3396.99 on macOS 10.13.6 and I'm able to select the url in a paragraph block floating link toolbar (tested using both a trackpad and a mouse). Looks fixed! ([12s](https://cloudup.com/cd6Nyit_aOg))
