### ISSUE TITLE
he “admin bar” UI should not affect the design.

### ISSUE THREAD

**Issue by dev-pandaking** [WordPress/gutenberg#58052]
## What problem does this address?
The “admin-bar” area greatly interferes with designing the theme’s UI. Additionally, the code becomes messy and it is difficult to control the absolute position of position.

## What is your proposed solution?
A panel that simply opens and closes is sufficient. It would be better if you could select the top, back, bottom, and left positions, and if you could open and close it, it could function as an admin-bar without compromising the design. This will make it a plugin with independent management functions, completely separate from the template.

![image](https://github.com/WordPress/gutenberg/assets/155930930/fe60c772-255a-45e5-af0f-6f9282048c47)

ps )
FSE MODE still has a long way to go, but it seems to have plenty of potential. Applause to the entire Gutenberg team.

**Comment by annezazu** [comment]
@dev-pandaking thanks for opening this issue! I'm not quite sure what you are giving feedback on though making it hard to know how to triage or address this properly. Can you please provide more information? What's the problem you're trying to solve? Where in the experience are you having issues? What version of WordPress or Gutenberg are you using?

**Comment by dev-pandaking** [comment]
@annezazu  Thanks for your reply.

![image](https://github.com/WordPress/gutenberg/assets/155930930/7ac3d832-eb89-4ad2-bbd1-0689ed59b5ba)

* What's the problem you're trying to solve? 
* Where in the experience are you having issues? 
  - Please look at the uploaded image.
* What version of WordPress or Gutenberg are you using?
  - 6.4.2

------------------------------------------------------------------

The question is simple.
I don't know why they made this area "admin-bar" affect the design. "html { margin-top: 32px !important; }" I don't know why they created such an unnecessary style sheet.

The "admin-bar" feature is needed, but seems to be worded incorrectly.

**Before clicking**
![image](https://github.com/WordPress/gutenberg/assets/155930930/d373314e-31ef-41af-bfaa-81dcd4cc2f6c)

**AFTER**
![image](https://github.com/WordPress/gutenberg/assets/155930930/c82d98bb-5b62-45f8-ab33-dd136922f6f6)


Is there a setting in which the "admin-bar" function does not affect the UI, assuming that css is not overwritten?

**Comment by annezazu** [comment]
The admin bar is only shown to folks who are logged into the site. It isn't shown on your site generally. It's to help users have an easy way to navigate to the backend of the site to make edits. I'm going to close this out as a result! Thanks for your feedback and for following up.
