### ISSUE TITLE
Font Library: Place checkboxes on the left

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#58070]
### Description

In the Fonts modal dialog, the list of installed fonts and the list of font variants show an user interfaces where checkboxes are aligned to the right. Screenshots:

![Screenshot 2024-01-22 at 10 42 11](https://github.com/WordPress/gutenberg/assets/1682452/fca241c5-dfb2-4bcd-849e-3a44abd66467)

![Screenshot 2024-01-22 at 10 42 42](https://github.com/WordPress/gutenberg/assets/1682452/f250bf85-5d68-499a-aad9-f8c4c80fc5fb)

Checkboxes on the right are not okay for accessibility. See WCAG Technique G162 which explains why and points out it's required for success criterion 3.3.2: Labels or Instructions.

Remediation:
Place checkboxes on the left and visual labels on the right of the checkboxes.

### Step-by-step reproduction instructions

- Go to Site editor > Styles > Typographi > click a fonr title to open the Fonts modal dialog.
- In the Library tab, observe the installed fonts show a checkboxe that is placed far to the right.
- In the Google fonts tab, click a fonr that has variants. 
- Observe the font variants show a checkboxe that is placed far to the right.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by afercia** [comment]
Besides the accessibility requirements mentioned above, I'd like to mention that these checkboxes places on the right are a unique case in the whole WordPress user interface. As such, their placement is inconsistent and unexpected. I think providing _consistent and predictable_ user experience is always a priority over any other argumentation.

**Comment by creativecoder** [comment]
Thanks for opening this issue! It's addressed in https://github.com/WordPress/gutenberg/pull/58212

**Comment by afercia** [comment]
Thanks @creativecoder 🙏
