### ISSUE TITLE
Fonts Library: collection ID is undefined

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#58075]
### Description

This appeaers to be a regression in trunk after https://github.com/WordPress/gutenberg/pull/57735

https://github.com/WordPress/gutenberg/pull/57735 changed the font collection `id` to `slug`, the changes were made mainly on the PHP side. However, it appears a few parts in the JavaScript side sill expect a colelction `id` that it may be now `undefined`.

Cc @matiasbenedetto 

For example:

In the odal dialog markup the ID is still used for the google fonts tab and tabpanel, but it is now undefined:

![Screenshot 2024-01-22 at 15 06 32](https://github.com/WordPress/gutenberg/assets/1682452/7440c8c3-5ccb-4964-8357-90458721e1e6)

The id to be used in these components is expected to be `default-font-collection`.

More importantly:
I couldn't get the prompt to allow to install Google fonts to shohw. Only after reverting https://github.com/WordPress/gutenberg/pull/57735 I was finally able to see the prompt. There is code in the JS implementation that still expects the `default-font-collection` ID while now it receives `undefined`.

Screenshot of the prompt to allow to install fonts from Google:

![Screenshot 2024-01-22 at 15 00 20](https://github.com/WordPress/gutenberg/assets/1682452/05a0a9b4-c7e7-4765-ad44-738c482fa7ca)

### Step-by-step reproduction instructions

- Clear your browser local storage.
- Go to Site editor > Styles > Typography 
- Open the fonts modal dialog by clicking the 'Aa' (sigh) icon button.
- Observe the title of the third tab within the modal dialog is 'Google fonts'. Expected: to be 'Install fonts' and change to 'Google fonts' only after permission to install has been given by the user.
- Observe the content of the third tab is the list of Google fonts: Expected: to be the prompt to allow installation.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by afercia** [comment]
I think this also breaks the modal dialog tabs when additional collections are added.

@matiasbenedetto I was trying to test additional collections by installing your `Modern Fonts Stacks for WordPress Font Library` plugin mentioned on https://github.com/WordPress/gutenberg/pull/54713 and I was getting an error `Plugin could not be activated because it triggered a fatal error`.

After changing `id` to `slug` here 
https://github.com/matiasbenedetto/modern-fonts-stacks-for-wp-font-library/blob/c770b588221e52b70046e30139d3db27220a9121/index.php#L14

the plugin activates correctly and a fourth tab is shown in the modal dialog:

![Screenshot 2024-01-22 at 15 34 54](https://github.com/WordPress/gutenberg/assets/1682452/a43f1f6d-9495-4207-93a5-af21da1a7eca)

but the Google fonts and the Modern Fonts Stacks tab / tabpanel use the same id `tabs-0-undefined` so that the UI is broken.

I also suspect the fatal error comes from the fact the expected array key `slug` isn't set. That likely highlights on the PHP side there should be some better check when the array key is _not set_ to prevent errors.

**Comment by afercia** [comment]
i'm also getting a JS `Warning: Each child in a list should have a unique "key" prop.`
Suspect it's the undefined `id` for the Google fonts tab.

**Comment by matiasbenedetto** [comment]
Hi @afercia :wave: thanks for reporting this. It seems like this should be fixed with this PR https://github.com/WordPress/gutenberg/pull/57884. It was already merged to a feature branch with a larger set of changes https://github.com/WordPress/gutenberg/pull/57688 intended to be merge soon. After merging the feature branch in trunk this problem should be fixed.

After that, I'll update [this little example plugin](https://github.com/matiasbenedetto/modern-fonts-stacks-for-wp-font-library/) to match the new expected shape of data introduced with https://github.com/WordPress/gutenberg/pull/57884, https://github.com/WordPress/gutenberg/pull/57736 and https://github.com/WordPress/gutenberg/issues/57616

**Comment by afercia** [comment]
Thanks for your feedback @matiasbenedetto I see in https://github.com/WordPress/gutenberg/pull/57884 many references to `id` are udpated to `slug` so yes that will probably fix it. Glad to close this issue after the feature branch is merged.

**Comment by mikachan** [comment]
I'm going to close this as https://github.com/WordPress/gutenberg/pull/57688 has now been merged, but please re-open if the issue happens again.
