### ISSUE TITLE
Enhance the Block panel UI

### ISSUE THREAD

**Issue by Dentalicious** [WordPress/gutenberg#58078]
## What problem does this address?
The Block Panel (Elements Panel) looks rudimentary and poorly designed compared to page builders such as Elementor or Bricks.

## What is your proposed solution?
Enhance the Block Panel UI to match or better Elementor/Bricks, making working in the Gutenberg Editor an enjoyable experience.

<img width="2041" alt="E Vs B vs G" src="https://github.com/WordPress/gutenberg/assets/33909786/0fa62be7-a5e7-445f-9bac-02ce86c4bc94">

**Comment by talldan** [comment]
@Dentalicious What features do you think are missing?

**Comment by Dentalicious** [comment]
> @Dentalicious What features do you think are missing?

Hi, 
This is not a missing feature request, rather a request to enhance the UI (User Interface) of the Block Panel, and the shortcut icons of the Blocks, to bring it in line of popular pagebuilders and give it a modern look. 
Cheers

**Comment by jordesign** [comment]
@Dentalicious are there particular things about the design of the panel in those page builders which is better specifically? 'A more modern look' is somewhat subjective.

**Comment by Dentalicious** [comment]
> @Dentalicious are there particular things about the design of the panel in those page builders which is better specifically? 'A more modern look' is somewhat subjective.

The images I shared above give a good contrast of the difference in contrast between the UI of the panels, but if I have to put it into words, then I’ll list it down as follows, 

Icons are not floating into empty space but are contained in a square outline and these square outlines have equal margins on the vertical and horizontal axis. 

When hovering over the icons, the outlines of the Element (Block) change colour to indicate the hovered state. 

Icons are categorised into,
Layout - Flexbox and Grid
Basic - Text, Heading, etc
Media - Images, Gallery, etc

Such attention to detail in the UI stands out and makes working in the editor an enjoyable experience. 

Trust that helps, 
Cheers


https://github.com/WordPress/gutenberg/assets/33909786/ecbb0874-5a4e-4b6b-bfd9-6a8afae504f8

**Comment by Dentalicious** [comment]
@jordesign Why is this issue marked as “Stale” and “Needs more info”?
I have provided all info as requested, and would be glad to give more any additional feedback if required.

**Comment by Dentalicious** [comment]
Thx, Cheers

**Comment by Dentalicious** [comment]
Hi, @jordesign @talldan 
It's the first time I added a feature request for the Block editor, so am unsure of the formalities. 
How long does it take for the feature request to either get approved or rejected!
Cheers!

**Comment by richtabor** [comment]
> @jordesign Why is this issue marked as “Stale” and “Needs more info”?

It's auto-applied after an issue sits for a while. I'm working on some ideas around the inserter, there's room to clean it up for sure.

**Comment by richtabor** [comment]
While interesting ideas here, I do think there’s a level of subjectivity here. I question if adding more borders makes the UI more modern; there’s a risk that it makes browsing the block inserter overwhelming even. 

It’s interesting to group by “Layout”, perhaps you can open a separate issue on that? Thanks!
