### ISSUE TITLE
Global styles: Preset slugs have inconsistent casing

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#58118]
### Description

Originally reported in https://github.com/WordPress/twentytwentyfour/issues/741

In Twenty Twenty-Four, a font family preset slug was accidentally written with mixed casing: `"slug": "system-Serif"`

```
{
	"fontFamily": "Iowan Old Style, Apple Garamond, Baskerville, Times New Roman, Droid Serif, Times, Source Serif Pro, serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
	"name": "System Serif",
	"slug": "system-Serif"
}
```

When the font family preset is chosen in the block editor, the custom CSS variable is referenced with the following CSS, and the font family works:

```
.editor-styles-wrapper .has-system-serif-font-family {
	font-family: var(--wp--preset--font-family--system-serif) !important;
}

--wp--preset--font-family--system-serif: Iowan Old Style, Apple Garamond, Baskerville, Times New Roman, Droid Serif, Times, Source Serif Pro, serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol;

```

But when the font family preset is chosen in the Site Editor > Styles > Typography > Heading > Fonts, the font family does not work, because it is trying to use the CSS custom property with the capital S, which does not exist:
`font-family: var(--wp--preset--font-family--system-Serif);`

This should be fixed in the theme, but WordPress should safe-guard against it and enforce a consistent casing.

### Step-by-step reproduction instructions

1. Activate Twenty Twenty-Four
2. Open the Site Editor and select a template to edit.
3. Open the Styles panel and select Typography  > Headings
4. Set the font family to system Serif
5. View the source and confirm that the variable that the editor is trying to use does not exist.

### Environment info

WordPress 6.4.2
Twenty Twenty-Four.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Here is the ticket and fix for the theme https://core.trac.wordpress.org/ticket/60325

**Comment by zobinadevain** [comment]
This approach does not prevent a plugin from filtering get_the_excerpt and enforcing its own setting at all costs.
So in this regard, both [approaches ](https://capmistoi-6225.weebly.com)have the same problem and I don't think it's solvable. Plugins will always be able to filter the excerpt.

**Comment by carolinan** [comment]
I am not able to reproduce this on WordPress 6.5 with or without Gutenberg trunk enabled. I manually changed the capilitalization of the slugs in theme.json, and the slug is lower case in both the Site Editor and Block editor.
I don't know in which pull request, but it seems to have been fixed.
