### ISSUE TITLE
Templates: Enable users to quickly browse by author/source

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#58111]
When managing templates it can be helpful to quickly view templates by author/source, e.g.:

* Templates added by the active theme.
* Templates added by specific plugins like WooCommerce or bbPress.
* Custom, user-generated page templates ($custom).

To achieve this currently requires several clicks navigating the filters menu.

### Dedicated views

<img width="1147" alt="Screenshot 2024-01-23 at 10 00 17" src="https://github.com/WordPress/gutenberg/assets/846565/eee73dc8-66a0-4f3d-aa17-69e7ff5bc9e2">

This approach builds on the sorting that exists in the current templates list by providing views for the following template groups:

* All templates – self-explanatory.
* Theme – templates bundled with the active theme.
* Custom – any user-generated $custom templates.
* Per-plugin views.

Adding these views could be a nice enhancement for 6.5. The first three should appear regardless, and per-plugin views would appear dynamically when the corresponding plugin is activated.

**Comment by jameskoster** [comment]
This wasn't _fully_ captured by https://github.com/WordPress/gutenberg/pull/58124 so I don't think we can close yet.

Missing details:

* For the 'All templates' view could we use the file icon to differentiate it from the theme views?
* It would be nice to include the counts.
* Perhaps most important: ideally all user-generated templates would be grouped together in a view called "Custom", rather than individual views per user. This view would be the equivalent to filtering by author and selecting all users.

**Comment by youknowriad** [comment]
Given that RC1 is today I'm removing this one from 6.5 as non essential.

**Comment by jameskoster** [comment]
Closing this in favor of individual issues for the outstanding items since they're better handled separately.
