### ISSUE TITLE
Query Loop variations in Core are not detected as active

### ISSUE THREAD

**Issue by jsnajdr** [WordPress/gutenberg#58168]
Steps to reproduce:

Insert the "Posts List" block, which is a variation of Query Loop:

<img width="1042" alt="Screenshot 2024-01-24 at 10 03 47" src="https://github.com/WordPress/gutenberg/assets/664258/e03b911f-ca54-4f60-8fbb-d50bcfbf3ec2">

What I expected:
1. The name of the block in the List View in the sidebar is "Posts List", not "Query Loop".
2. After clicking on "Choose" to choose a pattern, the available patterns are searched for `blockTypes` support for `core/query/posts-list` specifically.

But none of that happens, the active variation is not detected by the `getActiveBlockVariation` selector. That's because the `core/query` variations shipped by Core have no `isActive` function.

This functionality was implemented by @ntsekouras in #44197, but for the Core Query Loop block and its variations it doesn't work. On the other hand, Woo ships a "Products Query" variation of `core/query` which implements `isActive` correctly and is detected.

**Comment by jsnajdr** [comment]
One more thing: there is an `__experimentalGetMatchingVariation` function, used to determine the block placeholder label, and it works. That why you see the "Posts List" label in the screenshot above. But it looks like a duplicate of `getActiveBlockVariation`. If `getActiveBlockVariation` worked reliably, could we remove `__experimentalGetMatchingVariation`?

**Comment by ntsekouras** [comment]
Thanks for the issue! `__experimentalGetMatchingVariation` was introduced before the `isActive` API and can be safely swapped. I'll open a PR soon for this.
