### ISSUE TITLE
Block Registration: Allow using multiple php files for blocks.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#58187]
In https://github.com/WordPress/gutenberg/pull/57979 we tried to have two php files for the navigation blocks:

 - The regular `index.php` file 
 - A utility class that is specific to this block.

We tried putting the files in the `navigation` folder and requiring the class from the main `index.php` file. This worked to a degree: We wanted the build folder of the block to keep the folders: one folder per block as opposite to a single file for the whole block like it exists today.

It seems there's an unwritten assumption in `register_block_type_from_metadata` that tries to guess the file name form the block name or something like that, that prevents us from having multiple php files (single entry point) for blocks.

cc @gziolo

**Comment by draganescu** [comment]
Does this mean the rule for `phpcs` here

https://github.com/WordPress/gutenberg/pull/57979/files#diff-05ae9cddcaec1e845771a7db224961439f83ef5939ec67d3a48744cb34d7e58bR69

is meant to be temporary?

**Comment by youknowriad** [comment]
@draganescu yes, ideally we should remove that.

**Comment by youknowriad** [comment]
I'm closing this issue, while it would be a nice little improvement. It's not really mandatory. Aside the navigation block that is huge, most of the other ones don't really need this.
