### ISSUE TITLE
Category Selection Shows Truncated List

### ISSUE THREAD

**Issue by brysont** [WordPress/gutenberg#5820]
## Issue Overview

When assigning category(s) to a post, only 32 categories show up. 171 categories in all, but only a random first 32 appear in the editor (possibly sorted by use?).

And yes, that many. Sports site covering all professional American leagues and teams = 171 categories.

## Steps to Reproduce (for bugs)

1. Create 33 or more categories
2. Create a new post and try to assign each of the 33+ categories

Using Chrome 65 on a Windows 10 machine (all updates current). WordPress 4.9.4, also fully updated. Gutenberg 2.4.0.

## Expected Behavior

All categories should be visible, likely via use of scrolling overflow for the parent `.components-panel__body.is-opened` div to the `.editor-post-taxonomies__hierarchical-terms-choice` div. The list of categories shown is truncated to 32 results, as adding `overflow: scroll;` or `overflow: auto;` to the CSS doesn't help.

At the very least, it should work like the category list in the classic editor, loading all into a scrollable box. A possible improvement would be to load all parent categories in that manner, each one able to be clicked and expanded to show child categories for selection. On an edited post (categories already assigned), classic editor functionality could be used (pinning assigned categories to the top of the list, out of context), or the appropriate parent category(s) could initialize expanded, to show the assigned children.

**Comment by karmatosed** [comment]
This looks like a similar issue to https://github.com/WordPress/gutenberg/issues/4022 so closing for that. Thanks.

**Comment by brysont** [comment]
Negative. #4022 refers to content output of a category list (frontend).

My issue is about post metadata selection (backend).

**Comment by karmatosed** [comment]
Thanks for clarifying. I am going to cc someone in to double check they aren't related and try and get some progress for you - reopening while that happens. @pento do you have any insights here?

**Comment by danielbachhuber** [comment]
It's the REST API pagination issue. We can keep this open until it's resolved.

**Comment by richardiriwn** [comment]
I have a similar problem. Web sites highly dependent upon categories for navigation. However with Gutenberg enabled, I only see a list of 2 out of several hundred when I create or edit post or page.
Nice looking editor!
