### ISSUE TITLE
Template Part: using name "content" conflicts with the post content block

### ISSUE THREAD

**Issue by dabowman** [WordPress/gutenberg#58215]
### Description

I created a pattern called "Content". I added the post content block inside of it. This results in the pattern being inserted inside itself. 

### Step-by-step reproduction instructions

Make new template part in the general area. 
Name it Content
add the "Content" block inside of it. 
You should get a "this block cannot be rendered inside itself" error. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5473066/84879259-db79-4c56-90e8-542e38319fab

### Environment info

Wp 6.4 
Gutenberg 17.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment]
Hey David! I can't replicate this with a site using 6.4.2:

https://github.com/WordPress/gutenberg/assets/26996883/eb2cfb9c-7a7f-4334-b5e8-fe9f90b75d91

However, I could replicate with 6.4.2 + GB 17.5.1:

https://github.com/WordPress/gutenberg/assets/26996883/a5eaf968-8c9d-4ee3-beb4-42e6e3e19f0a

Looks like something changed since 6.4.2. Adding this to the 6.5 board as this is a regression.

**Comment by colorful-tones** [comment]
I'm digging into this one to find where the regression was introduced. 

Test instructions to reproduce the issue:

1. Launch Site Editor > Patterns > Manage all template parts (at bottom) > Add New Template Part
2. Name the template part "Content" (this is not critical and seems that the naming is not an issue in this matter), and choose 'General' as the type, and click 'Create'
3. Add the Content block and note the message: 'Block cannot be rendered inside itself.' 👈 This message was not appearing before.

**Comment by colorful-tones** [comment]
Something introduced in Gutenberg 17.1.0 is where the regression is caused. I'm trying to narrow down the commit now.

**Comment by colorful-tones** [comment]
Ok, it seems that this regression was introduced in f9b544db9a372a7db6fbcd2eecc6cc4d84d398df
Pinging @youknowriad for clarity, because he worked on the associated PR #56000

**Comment by annezazu** [comment]
Thanks so much for tracking this down!
