### ISSUE TITLE
Blocks within Blocks

### ISSUE THREAD

**Issue by markbiernat** [WordPress/gutenberg#5822]
## Issue Overview

Version 2.4.0

This is not a bug,however, would be helpful for WP page design and functionality.

Nested Blocks - If you could drag and drop, or create blocks within blocks and add margins and padding, this would greatly enhance usability.

For example, current front page design conventions are often rows (divs) that are nested. This one feature would greatly enhance the the power of Gutenberg.

An example of a plug-in with this functionality is Tailor Page Builder i.e. nested content elements.

If boarders could be added to these rows it would also be a desired enhancement.

Below is an image of an example of a full-width front- page with nested blocks with independent background shading.

## Screenshots / Video

![image](https://user-images.githubusercontent.com/30418497/37981749-84ebcb82-31bc-11e8-824a-a110c9970637.png)

**Comment by karmatosed** [comment]
Thank you for your feedback on this. The good news is that drag and drop is coming to Gutenberg and it is one of the features for merge proposal. That said, I will close this and link the main issue around this for reference: https://github.com/WordPress/gutenberg/issues/38.
