### ISSUE TITLE
Template Types in patterns not working

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#58223]
### Description

Using the following code in my patterns to make certain patterns available for creation of templates:

```
<?php
/**
 * Title: Post content with gradient cover
 * Slug: powder/template-single-gradient-cover
 * Categories: powder-template
 * Template Types: single
 */
?>
```

With WordPress 6.4.2, here is a screenshot taken after following the steps below:

![image](https://github.com/WordPress/gutenberg/assets/486261/7cdc5687-bd0a-4c4f-9cc0-5c06016ceac7)

With WordPress 6.4.2 and Gutenberg 17.6.0 RC1 active, here is a screenshot taken after following the steps below:

![image](https://github.com/WordPress/gutenberg/assets/486261/a42d2785-cb6e-46c8-8243-29a43b368c01)

I have two patterns in my theme which use `* Template Types: single`.

### Step-by-step reproduction instructions

1. Go to Editor > Templates > Add New Template > Single item: Post
2. Select All Posts
3. See available templates.

### Environment info

WordPress 6.4.2
Gutenberg 17.6.0 RC1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bgardner** [comment]
I can also replicate this issue with the TT4 default theme.

**Comment by bgardner** [comment]
Also worth noting, this issue does NOT exist with Gutenberg 17.5.2 active:

![image](https://github.com/WordPress/gutenberg/assets/486261/1347f371-b948-4ceb-aab4-67c2c5107f2f)

**Comment by colorful-tones** [comment]
I'm sleuthing on this now to see where code was introduced to cause this regression.

Steps for testing and verifying:

1. Open Site Editor > Templates > Add New Template: 'Single item: Post' > All Posts
2. The 'Choose a Pattern' modal should pop up and with TT4 activated there **should be two patterns available**.

| Before | After (w/ regression) |
|---------|------------|
| ![Screenshot 2024-02-01 at 12 22 17 PM](https://github.com/WordPress/gutenberg/assets/405912/6e7334fb-856f-4f8f-b226-3e536166b01b) | ![Screenshot 2024-02-01 at 12 23 30 PM](https://github.com/WordPress/gutenberg/assets/405912/89a97187-c7ed-4ca0-ba04-a53f0bd8e0c2) |

**Comment by colorful-tones** [comment]
Something was introduced in #57999  that caused this regression. Maybe @ellatrix might have some insight. I'm now peeking at the code that was altered in the PR.

**Comment by colorful-tones** [comment]
~~I suspect that one of the two patterns in our [testing scenario](https://github.com/WordPress/gutenberg/issues/58223#issuecomment-1921864242) comes from the WP core and not the Twenty Twenty-Four theme.~~ There is only one pattern in the Twenty Twenty-Four theme that has a single template target `Template Types: posts, single` in [`twentytwentyfour/patterns/template-single-portfolio.php`](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-content/themes/twentytwentyfour/patterns/template-single-portfolio.php#L5). The other pattern is probably not a pattern per se, and likely showing the `twentytwentyfour/templates/single.html`?

**Comment by ellatrix** [comment]
Does this fix the problem by any chance? #58661

**Comment by ellatrix** [comment]
Thanks for providing minimal steps to reproduce. I indeed see two patterns for 17.5 but online 1 in trunk and even with that branch. I'll investigate further.

**Comment by colorful-tones** [comment]
Thanks @ellatrix for digging in. I meant to dig on the code but did not make it that far. I’m happy to test any follow up.
