### ISSUE TITLE
Font size reset doesn't clear the sidebar selection

### ISSUE THREAD

**Issue by pavel-mailpoet** [WordPress/gutenberg#58255]
### Description

The reset button does reset the font size, but the side bar selector is not cleared.

### Step-by-step reproduction instructions

1. Add a paragraph to the document
2. Open the Typography block settings
3. Change the font size to “M”.
4. In the defaults menu, select “reset” to clear the font size.

Observe the issue: https://d.pr/i/LsJeFf

The “M” font size is selected, but it should be cleared.

### Screenshots, screen recording, code snippet

Screen recording: https://d.pr/v/BCefqZ

### Environment info

WordPress Version: 6.4.2
Browser Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Andrew-Starr** [comment]
Confirming I am able to recreate this issue.

Sometimes (but not always) selecting "Reset all" clears the size, and then subsequently selecting a size and resetting only the size does clear the size selector.

Clicking away from the selected block (e.g. selecting a different block) and then going back into the same block clears the size selector, but yes it should be cleared when selecting "reset" when staying within the block.

**Comment by t-hamano** [comment]
Thanks for the report. 

I tested it with WordPress 6.4.2. I was indeed able to reproduce this issue, but it did not occur when I enabled the latest Gutenberg.

I would like to close this issue as it appears to have been resolved, but if you are still having issues please let me know.

https://github.com/WordPress/gutenberg/assets/54422211/d397d185-2ca0-45a3-abf6-65135988fa6e
