### ISSUE TITLE
Image block: add site logo to block transforms

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#58272]
While on a call with a user, they added in an image to their header and wanted to have it be a site logo but it isn't listed under transforms:

![Screenshot 2024-01-25 at 9 37 03 AM](https://github.com/WordPress/gutenberg/assets/26996883/5d16c99f-3d3e-42b1-abba-421a27e6bbea)

This seems odd considering we show "group" and "file". Let's consider adding in site logo to the mix!

**Comment by richtabor** [comment]
In light of the recent [transform auditing](https://github.com/WordPress/gutenberg/issues/63635) effort, I'm hesitant to add transforms for every little thing. I wonder how valuable this transform would be for most users?

**Comment by annezazu** [comment]
Since we haven't gotten any additional feedback, I'm okay with closing out for now and we can revisit if it comes up again.
