### ISSUE TITLE
Font Library modal: Tab title is repeated in content

### ISSUE THREAD

**Issue by mikachan** [WordPress/gutenberg#58277]
## What problem does this address?

In the Font Library modal, the tab title is displayed in both the tab and the contents of the tab:
<img width="1080" alt="Screenshot 2024-01-25 at 19 50 30" src="https://github.com/WordPress/gutenberg/assets/1645628/0f281897-5652-46bd-b708-83aeec3b18eb">

## What is your proposed solution?

We should consider removing the title inside the tab contents to reduce the repetition.

**Comment by colorful-tones** [comment]
Without looking at the code - we should consider screen readers and tab order here for accessibility. At the very least, we'll need `aria-labelledby` and `aria-label` to associate the tab with the tab-panel content, and the focus should likely shift to the first focusable item once a tab is selected.

In other words, the duplication of the text may be ideal, or if it is not, then we could hide it with CSS (`.sr-only`), but we want to make sure we do any of the above with accessibility at the forefront.

**Comment by mikachan** [comment]
Thanks @colorful-tones! I agree, and this issue was opened with accessibility in mind.

**Comment by akasunil** [comment]
Hi @mikachan 
Is this issue still relevant? Design has been updated of font library. Here is latest screenshot
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/70e523fb-422e-4420-9b7f-9c2048940e30">

**Comment by mikachan** [comment]
Oh true, thanks @akasunil! I think we can close this then 🎉
