### ISSUE TITLE
Font Library: font families endpoints context default to 'edit'.

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#58281]
### Description
`/font-families/` endpoints default `context` patameter to `edit` instead of `view`. But amost all the core endpoints set the default the`context` parameter to `view`. Let's change it to default to `view`.

https://github.com/WordPress/gutenberg/blob/ecda32e0911ee7e04e044b8a7351ee4841e94a19/lib/experimental/fonts/font-library/class-wp-rest-font-families-controller.php#L341

https://github.com/WordPress/gutenberg/blob/ecda32e0911ee7e04e044b8a7351ee4841e94a19/lib/experimental/fonts/font-library/class-wp-rest-font-families-controller.php#L365-L378

## Why?
It seems like we misinterpreted the meaning of the `context` parameter, and we used `view` because the font families are used by default in the editor, but that seems to be unrelated.

I didn't find the docs in the rest API handbook about it, but this reading is useful: https://make.xwp.co/2017/07/25/defining-context-in-the-wp-rest-api/

### Step-by-step reproduction instructions

- check the context default in `lib/experimental/fonts/font-library/class-wp-rest-font-families-controller.php` and compare it with most core endpoints.

### Screenshots, screen recording, code snippet

Screenshot of a search in core codebase:
![image](https://github.com/WordPress/gutenberg/assets/1310626/c832a2f7-665a-43e2-87a3-bde1d1745ca2)

### Environment info

- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by creativecoder** [comment]
Thanks for taking a closer look at this, the linked article was very informative. I've opened a PR to update font-families and font-faces endpoints here: https://github.com/WordPress/gutenberg/pull/58287

**Comment by matiasbenedetto** [comment]
fixed by: https://github.com/WordPress/gutenberg/pull/58287
