### ISSUE TITLE
Link UI incorrectly anchored to "last" link within rich text contenteditable

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#58280]
If you have multiple links within a block of rich text then the Link UI will be "anchor" to ~the final~ first link you clicked in the block.

So if you click the first link in the block and then click on other links, the popover will continue to anchor to the first link. Similarly if you clicked the last link first, it would continue to anchor to that link.

It should be anchored to the link that triggers it. I suspect this is due to the way in which we recently changed the usage of `useAnchor` to cache the first position. 

https://github.com/WordPress/gutenberg/blob/ecda32e0911ee7e04e044b8a7351ee4841e94a19/packages/format-library/src/link/inline.js#L208-L215

https://github.com/WordPress/gutenberg/assets/444434/4d0d88d1-2800-4e45-9876-2ba955b22950

**Comment by getdave** [comment]
cc @richtabor @jeryj @scruffian

**Comment by getdave** [comment]
I confirmed that removing theses lines...

https://github.com/WordPress/gutenberg/blob/trunk/packages/format-library/src/link/inline.js#L208-L215

...will "fix" the problem. But now if you create a new link and submit you'll see the popover is incorrectly positioned.

**Comment by jeryj** [comment]
The same problem lines also cause an issue where the popover is "fixed" on the page, so it doesn't stay attached to the link, but scrolls away from it.

> But now if you create a new link and submit you'll see the popover is incorrectly positioned.

I think the incorrectly positioned new link issue has to do with the popover anchor changing from the paragraph to the link, but the popover anchor doesn't update to be anchored to the new element.
