### ISSUE TITLE
Accessibility check for colors isn't showing up

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#5829]
I think this may have been the result of recent changes so adding (I've not seen this before). The accessibility check for colors seems shy and hiding:

![2018-03-27 at 20 30](https://user-images.githubusercontent.com/253067/37990535-7dbae388-31fe-11e8-9420-91ec733c8de1.png)

**Comment by gziolo** [comment]
I think @jorgefilipecosta has already come up with a fix 😃

**Comment by karmatosed** [comment]
Yay! Thanks for the fast work.
