### ISSUE TITLE
Site Editor: Top toolbar looks broken

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#58295]
The top toolbar has extra space on the bottom due to `overflow-x: scroll;`. It looks just fine in the post editor.

## Step-by-step reproduction instructions
1. Open the site editor.
2. Enable the top toolbar.

## Screenshot

![CleanShot 2024-01-26 at 09 32 29](https://github.com/WordPress/gutenberg/assets/240569/e36409ee-d70c-4f81-b642-b3de856aa00f)

**Comment by Mamaduka** [comment]
cc @draganescu, @jeryj.

**Comment by t-hamano** [comment]
In #57444, we are working on improving the UI of the top toolbar. I believe that once that PR is merged, this issue will also be resolved

**Comment by t-hamano** [comment]
#57444 has been merged. The following is a screencast for Windows OS and Chrome browser, but it should work on MacOS as well. I would like to close this issue, but if you have any remaining issues, please feel free to comment.


https://github.com/WordPress/gutenberg/assets/54422211/f74233c5-c217-4685-a6db-88f977eb6c6d

**Comment by Mamaduka** [comment]
Thank you, @t-hamano 🙏
