### ISSUE TITLE
Shadow: Follow up to address feedback.

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#58298]
This issue is a followup for #57101.

- [x] remove `useShadowProps` hook - feedback from [here](https://github.com/WordPress/gutenberg/pull/57654#discussion_r1464756636) - https://github.com/WordPress/gutenberg/pull/58297
- [x] Skip block style serialization - https://github.com/WordPress/gutenberg/pull/58306
- [x] Default presets are opted-in by default - change to only show if theme opts in?
       [ Should we introduce without core presets enabled? As there are no controls ] - https://github.com/WordPress/gutenberg/pull/58766
- [x] Does it work with appearance tools toggle? (Should be turned off if appearance tools are off)
- [x] Move shadow out of Effects panel and possibility keep it under Border. Design team to provide feedback @jasmussen - https://github.com/WordPress/gutenberg/pull/58466
- [x] Hide shadow control by default and let blocks control the default visibility using `__experimentalDefaultControls`

**Comment by madhusudhand** [comment]
> Default presets are opted-in by default - change to only show if theme opts in?

@mtias 
Default presets were already enabled by default in the previous release for button in global styles. 
Changing the behaviour now might break themes that use shadow for button.

> Move shadow out of Effects panel and possibility keep it under Border.

@jasmussen could you provide updated designs.

**Comment by jasmussen** [comment]
Yep, I'll update a sketch when I have a moment. For now, though, the idea is to just rename the current panel called "Border", call it "Border & Shadow", and move the control to the bottom of that panel.

**Comment by jasmussen** [comment]
Found these:

<img width="1458" alt="Shadows in the inspector" src="https://github.com/WordPress/gutenberg/assets/1204802/b82ffc29-7a57-49f7-a9ce-b4326101ce12">

<img width="901" alt="Shadows in Global Styles" src="https://github.com/WordPress/gutenberg/assets/1204802/0f370bf1-6811-4736-b5d4-b114c02a902c">

The panel title can be contextual, when a block only supports border, call it "Border", if a block only supports shadow, call it "Shadow", when it supports both, call it "Border & Shadow".

**Comment by richtabor** [comment]
> Should we introduce without core presets enabled? As there are no controls

This first iteration does not include the ability to create shadows, so if there are no presets, you should not be able to have the control available. When we do follow-up with shadow creation, then yes, it should be available as an option to apply.

**Comment by richtabor** [comment]
> Default presets are opted-in by default - change to only show if theme opts in?

I would expect shadow presets to work like other default presets—`defaultDuotone`, `defaultPalette`, `defaultGradients`, etc.

**Comment by madhusudhand** [comment]
Closing as all feedback items are complete.
