### ISSUE TITLE
Update defaults for Home Link block

### ISSUE THREAD

**Issue by tjcafferkey** [WordPress/gutenberg#58307]
### Description

It's now possible to use the Block Hooks API to insert inner blocks into the core Navigation block https://github.com/WordPress/gutenberg/pull/57754. Using this API currently doesn't allow you to set attributes along with the hooked block.

We found that when you use the API to insert the `core/home-link` block it has insufficient default attributes. When we insert this block via the API we can't set any attributes and one of the conditions for this block to render server-side is a label attribute, see [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/home-link/index.php#L131-L133).

When you insert the block via the editor, this gets added on the client-side. See [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/home-link/edit.js#L47-L54).

### Step-by-step reproduction instructions

1. Add the below code to your site.
2. Load frontend and see that the block doesn't render at all.
3. Change `core/home-link` to `core/loginout` in the snippet below to see a block rendering correctly as comparison.

```php
function register_home_link_block_as_navigation_last_child( $hooked_blocks, $position, $anchor_block, $context ) {
	if ( $anchor_block === 'core/navigation' && $position === 'last_child' ) {
		$hooked_blocks[] = 'core/home-link';
	}

	return $hooked_blocks;
}

add_filter( 'hooked_block_types', 'register_home_link_block_as_navigation_last_child', 10, 4 );
```

### Environment info

- WP 6.4
- Gutenberg latest `trunk` or 17.6 and above.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ockham** [comment]
> When you insert the block via the editor, this gets added on the client-side. See [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/home-link/edit.js#L47-L54).

I was wondering why this wasn't done via an attribute default [when the block was created](https://github.com/WordPress/gutenberg/pull/30926) in the first place. Maybe it's the i18n? I.e. the `__( 'Home' )` bit?

https://github.com/WordPress/gutenberg/blob/9363cf0f60b35b9fcbaa4bc1edd07260f15b5ffd/packages/block-library/src/home-link/edit.js#L52

(I'm not sure if we have a mechanism to support localized strings like that in `block.json` nowadays 🤔 )

**Comment by ockham** [comment]
Looks like [this](https://github.com/WordPress/gutenberg/blob/9363cf0f60b35b9fcbaa4bc1edd07260f15b5ffd/packages/blocks/src/api/i18n-block.json) is the authoritative source of what `block.json` fields are translated (h/t @MaggieCabrera for the pointer!)

No attribute defaults in that one. So that might explain why this was done on the editor side in the first place 😬

**Comment by tjcafferkey** [comment]
Thanks @ockham! I suspected it may have something to do with translations. Maybe instead of setting the attribute if there isn't one, we can render `__( 'Home' )` in the absence of this attribute but allow users to override it by explicitly setting it still?

**Comment by ockham** [comment]
> Thanks @ockham! I suspected it may have something to do with translations. Maybe instead of setting the attribute if there isn't one, we can render `__( 'Home' )` in the absence of this attribute but allow users to override it by explicitly setting it still?

That sounds like a good idea! It would basically reflect the behavior in the editor, and allow inclusion of a Home Link block with no attributes set 👍

**Comment by ockham** [comment]
> Looks like [this](https://github.com/WordPress/gutenberg/blob/9363cf0f60b35b9fcbaa4bc1edd07260f15b5ffd/packages/blocks/src/api/i18n-block.json) is the authoritative source of what `block.json` fields are translated (h/t @MaggieCabrera for the pointer!)
> 
> No attribute defaults in that one. So that might explain why this was done on the editor side in the first place 😬

Post-scriptum, looks like it was actually discussed at the time: https://github.com/WordPress/gutenberg/pull/30293/files#r619407489
