### ISSUE TITLE
The focus mode back button is not clickable

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#58308]
### Description

With Gutenberg trunk active, if I open the Site Editor, select a pattern or template part and choose Edit, I am taken to a canvas edit mode and there is a back button.

This back button is only partially clickable. I keep miss-clicking on the arrow icon and nothing happens when I expect to go back.
It looks like there is a div with the class name `edit-site-site-hub__container` that is covering part of the button.

### Step-by-step reproduction instructions

Open a pattern or template part or pattern for editing.
Using your mouse or other pointer tool, try to use the back button.

### Screenshots, screen recording, code snippet

In the video, I am in the Site Editor, I select a custom (user created) pattern, open it to edit, and try to click the back button.

https://github.com/WordPress/gutenberg/assets/7422055/2e82aa88-4356-4ef7-b2f4-219962d23ad0

<img width="386" alt="the back button with a div overlapping" src="https://github.com/WordPress/gutenberg/assets/7422055/625dffec-5614-46f7-a9ff-6cfb8296f5a3">

### Environment info

I am using Chrome on Mac OS.
WordPress 6.4.2 and Gutenberg current trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
By the way I tried both with the Data views experiment on and off.

**Comment by afercia** [comment]
@carolinan I can't reproeuce this on latest trunk. For me, thelogo and all its containers never exceed a 60 pixels height. Maybe some conflicting CSS is altering that height for you?

![Screenshot 2024-01-29 at 12 20 13](https://github.com/WordPress/gutenberg/assets/1682452/c357fc4b-5d1e-4f28-8c75-26b86bc0e449)

![Screenshot 2024-01-29 at 12 20 21](https://github.com/WordPress/gutenberg/assets/1682452/1f217c76-77da-4101-8f3e-e68d836a3b6f)

![Screenshot 2024-01-29 at 12 27 01](https://github.com/WordPress/gutenberg/assets/1682452/634dec75-162b-4702-bda6-14ecc4918bf0)

**Comment by carolinan** [comment]
Thank you for testing. Unfortunately the problem is still present for me, in multiple browsers.

**Comment by carolinan** [comment]
I fully deleted my developer environment and started over, and now the problem is gone.
I am still not sure what was causing the height difference.
