### ISSUE TITLE
Setting for block spacing at template level

### ISSUE THREAD

**Issue by wwdes** [WordPress/gutenberg#58326]
## What problem does this address?
Unable to control spacing of blocks in the root of a template

![root block spacing](https://github.com/WordPress/gutenberg/assets/55145125/5408236b-1c49-4a14-8dfd-59bb015e6643)

In this simple template, I have not found any control in the editor to remove the gap between the header and content block. So I am forced to do this with CSS. Nesting entire template in a group block, just so that I get the controls seems to mess with paddings.

## What is your proposed solution?
Add controls to change spacing.

**Comment by t-hamano** [comment]
Hi @wwdes,

I think you can change the space between blocks at the root level in Appearance menu> Editor submenu> Styles button > Layout.

![root-block-spacing](https://github.com/WordPress/gutenberg/assets/54422211/fc5d2c6c-76d6-4cf5-9f69-46d49079accc)

**Comment by wwdes** [comment]
> Hi @wwdes,
> 
> I think you can change the space between blocks at the root level in Appearance menu> Editor submenu> Styles button > Layout.
> 
> ![root-block-spacing](https://private-user-images.githubusercontent.com/54422211/300144695-fc5d2c6c-76d6-4cf5-9f69-46d49079accc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODkyNjcsIm5iZiI6MTcwNjM4ODk2NywicGF0aCI6Ii81NDQyMjIxMS8zMDAxNDQ2OTUtZmM1ZDJjNmMtNzZkNi00Y2Y1LTlmNjktNDZkNDkwNzlhY2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDIwNTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYjFhMjRiZjE0MTRkY2Q5ZTIwMjY5NTE4MTgxNWQzNjc3ODY5ZTU5YWM1NzQyYWYxMjdjY2MxMjk3MjdkMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rmZZrsN8KdpT_SzMRM-SJ27YjvNrka701C9aH3TpVlE)

Those settings are global, which means they set default block spacing everywhere. I am talking about a setting that should be available when editing a template. This setting should behave exactly as on group blocks. Basically, what I am saying is that all group blocks have this setting, but templates do not. Why not? Templates behave mostly just like a group block..

**Comment by t-hamano** [comment]
I see. If so, #47637 would be relevant.

**Comment by wwdes** [comment]
Completed with https://github.com/WordPress/gutenberg/pull/54282
