### ISSUE TITLE
Block-image Caption Does Not Center for images < 608px

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#5834]
## Issue Overview

This is for Gutenberg Version 2.4.0

The wp-block-image caption apparently is meant to be centered under the image. If the image is less than 608px wide (at least in my tests, 608px seems to be the maximum width for wp-block-image width), then the caption is not properly centered. This non-centering can be seen in both the editor view, and in the front-end view for most themes.

## Steps to Reproduce (for bugs)

1. Add an image to a wp-block-image, preferably < 500px width  or so to most easily see image.
2. Add a caption.
3. The caption will not be centered under the image in the editor, and most themes.
4. The non-centering can also be more apparent in themes with wide content width.

## Expected Behavior

The wp-block-image caption should always center under the image, no matter what the width is.

## Possible Solution

This seems to be related to the display:block on the wp-block-image styling. Changing the style to
`.wp-block-image { display: inline-block !important; }`
will fix the centering in both the visual editor and the front-end view. BUT, that leaves an undesirable side effect in that a pair of narrow enough images will not break in the front-end view (they display side by side), but do in the editor because it has some other wrapping blocks that cause a break in the editor DOM version. 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jasmussen** [comment]
This will be fixed by #5706.

**Comment by jorgefilipecosta** [comment]
Closing this issue as https://github.com/WordPress/gutenberg/pull/5706 was already merged and the problem should now be fixed.
Thank you for reporting the issue @weavertheme!
