### ISSUE TITLE
Additional CSS field - code might not work if one presses the spacebar to align code.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#58373]
### Description

When adding CSS into the Additional CSS field and pressing spacebar to align the code. Invisible characters seem to be added making the code not work. I found out about this while creating a video tutorial yesterday when I used the Additional CSS field instead of a Code Snippets plugin to add the CSS.

### Step-by-step reproduction instructions

To go the Additional CSS field in the Styles panel.
Add CSS code.
Click the space bar a few times to align the code.
Test and see if the code works.

### Screenshots, screen recording, code snippet

https://youtu.be/tZa8Unciljg?si=rF6oeNg3nhhUsTQd
Go to 6.20 and watch from there. There I show some code not working and when backspacing to remove the invisible characters and doing a hard refresh it now works.

### Environment info

WordPress 6.4.2

Gutenberg plugin 17.5.2
Autoptimize
Burst Statistics
Code Snippets Pro

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

@tellthemachines @aaronrobertshaw 

I initially posted here.
https://github.com/WordPress/gutenberg/pull/57841

**Comment by t-hamano** [comment]
Hi @paaljoachim,

Is this issue still occurring in WP6.6 or the latest Gutenberg? I was not able to reproduce the issue in my environment.

I added the following CSS for example:

```css
.wp-block-heading {
    color: red;
    text-transform: uppercase;
}
```

**Comment by paaljoachim** [comment]
Hey Aki @t-hamano 

Thank you for testing!
I retested moving the code by clicking backspace and the spacebar. It works for me...:)
Closing this issue.
