### ISSUE TITLE
Font Library: Buttons within the Fonts modal dialog should use the new buttons height

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#58374]
### Description

The height of the buttons within the Fonts modal dialog is 36 pixels. Screenshot:

![Screenshot 2024-01-29 at 12 36 02](https://github.com/WordPress/gutenberg/assets/1682452/a2d1149b-d689-4983-919d-79f55d09495c)

Shouldn't all new UIs use the new 40 pixels buttons height? Cc @WordPress/gutenberg-design 

Buttons in other modal dialogs already use the 40 pixels height e.g. in the "Duplicate pattern" modal dialog:

![Screenshot 2024-01-29 at 12 38 43](https://github.com/WordPress/gutenberg/assets/1682452/576e78fb-b79d-4aa5-bed9-419abed8c32a)

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
> Shouldn't all new UIs use the new 40 pixels buttons height?

As far as #46741 goes, I think that's correct. Some related PRs have already been merged as well.

https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+is%3Amerged+in%3Atitle+__next40pxDefaultSize+
