### ISSUE TITLE
Do not show Advanced Settings toggle & Block sidebar if there are no settings to display

### ISSUE THREAD

**Issue by paulwilde** [WordPress/gutenberg#5837]
I have created a custom block to show a 'Ribbon' like graphic, however the block will not have any advanced settings associated with it. The block also does not support custom CSS classes and HTML anchors, so those do not show.

You can see in the screenshot the baron sidebar pane that the block has. Also the Show/Hide Advanced Settings toggle isn't necessary at this point.

<img width="1194" alt="screen shot 2018-03-28 at 10 50 15" src="https://user-images.githubusercontent.com/704594/38021847-dd4f1c34-3275-11e8-8f5f-d09ed97ed870.png">

**Comment by karmatosed** [comment]
As the sidebar can be used to also show what the block name is and a description, I would say this is ok to have still show on a block without settings. I could see a possibility of having a hook to turn on/off in block but I feel for now let's leave this as is and we can always reconsider.
