### ISSUE TITLE
Block schema: Incorrect description for innerBlocks example

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#58381]
### Description

The current schema description for `example.innerBlocks` includes `[ [ 'core/heading', { content: 'This is an Example' }, [] ] ]` but this format isn't supported. The correct format would be this: https://github.com/WordPress/gutenberg/blob/44df307b1caa686b025542a1cc730a92a4eae76f/packages/block-library/src/columns/index.js#L27-L81

### Step-by-step reproduction instructions

1. Go to https://github.com/WordPress/gutenberg/blob/44df307b1caa686b025542a1cc730a92a4eae76f/schemas/json/block.json#L708-L711
2. Notice the incorrect format

### Screenshots, screen recording, code snippet

<img width="814" alt="Bildschirmfoto 2024-01-29 um 14 19 08" src="https://github.com/WordPress/gutenberg/assets/617637/bc5e37a9-32cc-44b2-821f-1ffa8b7bb787">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MHRSRoni** [comment]
I would like to try this.. Assign me
