### ISSUE TITLE
Font Library: remove font family and font face preview keys from theme.json schema

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#58392]
## What?
Remove font family and font face preview keys from theme.json schema.

## Why?
During the implementation work of the Font Library, in https://github.com/WordPress/gutenberg/pull/56793, we added a `preview` key to `theme.json` to persist a preview image of the font family. The preview image had the objective of speeding up the font family preview display by reducing network usage by loading just a tiny image instead of a complete font asset. 

Later in the implementation process, we figured out that this won't be strictly necessary for the fonts present in theme.json/global styles due to they probably will be already loaded in the browser to use in the editor. Because of this, I think It would be fine to revert this change that doesn't seem crucial for the performance of the Font Library and could add an unnecessary change for `theme.json`.

**Comment by creativecoder** [comment]
Keeping the font preview file out of theme.json (and instead having it as part of Font Library metadata) makes sense to me.

I think the font definitions in theme.json should generally be about rendering the fonts for use as typography settings, and not storing additional metadata we want have for the Font Library.
