### ISSUE TITLE
Core Navigation Submenu Block - "Links are not crawlable" SEO lighthouse warning

### ISSUE THREAD

**Issue by kauaicreative** [WordPress/gutenberg#58396]
### Description

Top level menu items (Core Navigation, Submenu Block) insert empty <a> tags when a link is not entered.
The Submenu Block can be used to open the submenu on mouseover (without clickinging) and there is no intention of using it as a link.
Google page speed score warns - "Links are not crawlable".
It would seem that the a tag should not be inserted in this case. Or inserted with some code that would allow it to pass google page speed score.

Is this the best place to report this issue? You can find the original report here:
https://core.trac.wordpress.org/ticket/60351#comment:2

![image](https://github.com/WordPress/gutenberg/assets/127033/ef426f80-7fa3-4763-b41a-8b37a876a202)

### Step-by-step reproduction instructions

1. create navigation
2. crete submenu
3. change submenu to mouse over

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
[After a review](https://wordpress.slack.com/archives/C02QB2JS7/p1707152945370159) by core editor triage leads and core editor tech leads, this has been punted for consideration to 6.6. This doesn't mean it'll for sure make it into the 6.6 release to be clear!

**Comment by colorful-tones** [comment]
Hi folks,
We are only one week away from the Beta 1 cut-off date for [WordPress 6.6](https://make.wordpress.org/core/6-6/). This issue hasn’t seen any movement in a while, so we (the editor triage leads of the 6.6 release) have decided to remove it from the [WordPress 6.6 Editor Tasks project board](https://github.com/orgs/WordPress/projects/179/views/1).

**Comment by getdave** [comment]
Recent changes to the Link UI in the Navigation block mean that it's now very difficult to create empty links. Indeed we actively optimise  against it.

If someone creates empty links via the code editor or some such then I think they will be aware enough to understand the potential implications.

It's my feeling that we can now close this.

What do you think @kauaicreative?

Also cc @MaggieCabrera @draganescu who have previously worked on the block.

**Comment by MaggieCabrera** [comment]
Sounds like this could be closed
