### ISSUE TITLE
Link Control: Creating Empty Text Link from Selection says link is empty

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#58415]
### Description

When creating a new link without any highlighted text, the preview says link is empty.

I suspect the same root issue for this is the same root issue for https://github.com/WordPress/gutenberg/issues/58325

### Step-by-step reproduction instructions

1. In the block editor
2. with no text highlighted
3. Command + K to create a link
4. Select a page/post from the suggested options
5. Link Preview the "Link is empty" message

### Screenshots, screen recording, code snippet

<img width="392" alt="Link Preview with Link is empty message" src="https://github.com/WordPress/gutenberg/assets/967608/ffce4731-e59a-46f3-a86f-be8db0a4a5cb">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jeryj** [comment]
I think this might be due to the caret being placed outside of the link edge instead of inside of it. When creating a link with a selection, it places the cursor at the inside edge of the linked text. When creating it from an empty selection, it places it on the outside edge.

https://github.com/WordPress/gutenberg/assets/967608/add3c4da-9373-4418-8f49-4a270c3bef53

**Comment by draganescu** [comment]
I think we should place the caret outside the link and not show the Link UI when the link was created with no selection. That as opposed to fixing this by placing the caret inside the crested link.

**Comment by jeryj** [comment]
I believe a big part of this redone link creation UX was for the link preview to remain open after link creation. I believe it remains open after selected text links, so it should probably work the same way.  @richtabor, can you confirm?

**Comment by richtabor** [comment]
> I think we should place the caret outside the link and not show the Link UI when the link was created with no selection. That as opposed to fixing this by placing the caret inside the crested link.

Curious why you would treat link creation with text selection and no text-selection differently?

**Comment by draganescu** [comment]
> Curious why you would treat link creation with text selection and no text-selection differently?

Because without text selection the link inserting operation is in the writing flow, while with text selection the flow is interrupted to apply a format. In select text > apply format flow we also move focus away from the content to the UI, which for inserting a link while writing would be very jarring.

**Comment by richtabor** [comment]
> I think we should place the caret outside the link and not show the Link UI when the link was created with no selection. That as opposed to fixing this by placing the caret inside the crested link.

Ok cool. That's fine, let's try that and see how it feels in practice.
