### ISSUE TITLE
Replicate Screen Options to provide UI for toggling visibility of meta boxes

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#5841]
Gutenberg needs to have a UI to allow toggling the visibility of the metaboxes.

The problem is that if I open the classic editor for a post and close some of the metaboxes through the screen options pane, then when I load GB, those metaboxes are not there and there is also no option to turn them back on.

**Comment by danielbachhuber** [comment]
To provide additional context, metabox visibility historically has been managed in Screen Options:

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/36432/38031635-81f2469c-3250-11e8-9ca8-2653f25e5bfd.png">

Screen Options doesn't currently exist in Gutenberg. We'll need some equivalent UX for feature parity with the Classic Editor.

**Comment by karmatosed** [comment]
Changing to design as we need to consider this over jump into a 'needs design' solution.

**Comment by jasmussen** [comment]
Instead of recreating screen options for Gutenberg, another solution is to always show metaboxes in Gutenberg, even if they are hidden in the classic editor. If not ideal, at the very least that could be an interim solution.

**Comment by danielbachhuber** [comment]
@karmatosed @jasmussen Do you want to explore design for this, or should we force meta boxes to always visible in the primary column?

**Comment by karmatosed** [comment]
I think saying that they are always visible in primary column is good so let's have that as a decision here just like @jasmussen suggests.

**Comment by bkjproductions** [comment]
Throughout the rest of the WordPress interface, the Screen Options are visible. It seems very strange to remove it here. Does this mean that the rest of the WordPress interface will adapt to this new layout? See also #8745
