### ISSUE TITLE
Query Loop Block: Consolidate filter options in one place

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#58420]
## What problem does this address?

The current query loop block has two separate controls for customizing the query.

### Block Toolbar Popover

![image](https://github.com/WordPress/gutenberg/assets/54422211/14766f1e-e705-4657-9e6a-eb18dc9b3d8d)

### Block Sidebar "Filters" Panel

![image](https://github.com/WordPress/gutenberg/assets/54422211/a8cc9f28-759a-4690-9560-e2d7fe090299)

## What is your proposed solution?

Since both are functionally the same, I think they should be put together in one place. My feeling is that the block toolbar popover has limited space, so it would be better to organize them in a block sidebar "Filters" panel.

**Comment by Mamaduka** [comment]
@ryanwelcher started working on this - #58207.
