### ISSUE TITLE
Check whether the 6.4 script-loader.php compat file should be removed in favor of the 6.5 one

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#58431]
### Description

https://github.com/WordPress/gutenberg/pull/56682 added a compat file `lib/compat/wordpress-6.5/script-loader.php` for the Wordpress 6.5 release.

I'm not very familiar with how copat files work @Mamaduka pointed out that:

> There's already a gutenberg_update_wp_date_settings filter in WP 6.4; we should probably remove it to avoid double filtering.

And yes basically the new `lib/compat/wordpress-6.5/script-loader.php` file is the same of the 6.4 one with the only addition of one line. I'd appreciate someone more familiar with compat files than me to double check whether the 6,4 file should be removed. Cc @WordPress/gutenberg-core 

### Step-by-step reproduction instructions

Compare the filter callbacks `gutenberg_update_wp_date_timezone_settings` and `gutenberg_update_wp_date_settings`:
- `lib/compat/wordpress-6.5/script-loader.php`
- `lib/compat/wordpress-6.4/script-loader.php`
- Also important: evaluate whether the change from https://github.com/WordPress/gutenberg/commit/fa802d10e65c7d0951cc0f2357c367b0ab19861c needs to be added to the 6.5 comapt file

### Screenshots, screen recording, code snippet

N/A

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
Thanks for creating this issue. 🙏🏻 

In this case, when creating the 6.5 version of the filter, the 6.4 could have been moved into the 6.5 folder and updated from there.

What's important is backwards compatibility for folks running the plugin on older versions of WordPress.

So folks running the latest version of Gutenberg, and say, WordPress Core 6.3, will have all the plugin functionality ported to WordPress 6.4 and 6.5.

> Also important: evaluate whether the change from https://github.com/WordPress/gutenberg/commit/fa802d10e65c7d0951cc0f2357c367b0ab19861c needs to be added to the 6.5 comapt file

Yes! Thank you for bringing this to my attention. 

I can get a Gutenberg PR up to do this.

**Comment by ramonjd** [comment]
Merging compat files here:

- https://github.com/WordPress/gutenberg/pull/58479

@afercia The changes in https://github.com/WordPress/gutenberg/pull/56682 will still need to be backported to Core for 6.5 if they haven't already. Thank you!

**Comment by afercia** [comment]
@ramonjd thanks for clarifying how compat files are supposed to work and for fixing it.
For core, I create a Trac ticket at https://core.trac.wordpress.org/ticket/60105
