### ISSUE TITLE
Wp_store function is undefined.

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#58436]
### Description

When I try to use interactivity api on render.php I got

`Call to undefined function wp_store`

The code I'm using is:

```
wp_store(
	'archimedia',
	array(
		'product_id' => get_the_ID(),
	)
);
```

### Step-by-step reproduction instructions

1. Create a simple interactivity block
2. In render.php add an initial store

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by cbravobernal** [comment]
Hi there!

The function changed its name, and now is breaking change.

> ##### 8. Rename `wp_initial_state` to `wp_interactivity_state`
> 
> With the new `WP_Interactivity_API` class, all the related functions have been namespaced with `wp_interactivity`, including the one to set the initial state.
> 
> Previously:
> 
> ```php
> wp_initial_state( 'myPlugin', array(
>   'someState' => 'some state'
> ));
> ```
> 
> Now:
> 
> ```php
> wp_interactivity_state( 'myPlugin', array(
>   'someState' => 'some state'
> ));
> ```

You can check the breaking changes here: https://github.com/WordPress/gutenberg/discussions/52906#discussioncomment-8210968
