### ISSUE TITLE
Listed time for Editor chat is off by one hour on make/core

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#5843]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/36432/38031285-b8479540-324f-11e8-842c-eec2559b82b6.png">

I'd change it, but I don't have admin permissions on that blog.

It'd also be great to get the bug scrub listed in https://make.wordpress.org/meetings/

**Comment by karmatosed** [comment]
I put in a meta request so closing.
