### ISSUE TITLE
Font Library: check whether the FontVariant component is actually used and maybe remove it

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#58443]
### Description

While working on other Font Library related issues, I couldn't find any usage of the FontVariant component at https://github.com/WordPress/gutenberg/blob/161b2e469c29c2c21abd9fe89240d9c44a80d5c1/packages/edit-site/src/components/global-styles/font-library-modal/font-variant.js

If it's not used and there's no plans for it, it could be safely removed. If so, there's also some CSS to clean up

### Step-by-step reproduction instructions

- Search for anu usage of the `<FontVariant>` component.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by matiasbenedetto** [comment]
Thanks for flagging this.
Here is a PR removing that old component and CSS: https://github.com/WordPress/gutenberg/pull/58449
