### ISSUE TITLE
Can't select linked and unlinked text

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#58465]
### Description

Using the mouse I can't select text that is unlinked and text that is linked.

### Step-by-step reproduction instructions

1. In a post add a longer paragraph
2. In this paragraph add a link and then a few words apart another link
3. try using the mouse to select text unlinked, from between the two links, to text linked

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/107534/84b07449-8654-465a-8ba4-dfc30db96723

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jeryj** [comment]
Debugging this. Here's what I'm encountering: 
- Begin highlighting off of anchored text
- Highlight into anchored text
- Once the highlight extends into anchored text, the [selectionStart/End](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/rich-text/index.js#L132-L133) range from stops updating.


https://github.com/WordPress/gutenberg/assets/967608/a4edb18d-6d63-41d0-bf01-603775cbcabb

**Comment by jeryj** [comment]
Also, this is not link specific. If you use this with bolded text, it also happens. It seems to be a bug where anytime you highlight text and it crosses into a new tag `<a>`, `<strong>`, etc, it stops updating the selectionStart/End values.

**Comment by jeryj** [comment]
I believe this issue was introduced by https://github.com/WordPress/gutenberg/pull/47525.

I've been looking at it today, but don't quite understand how it all ties together and what a good fix might be.
