### ISSUE TITLE
DataViews: Improve the message when there is no results

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#58482]
## What problem does this address?

In the current data view, a message like this is displayed when there are no items to display.

List Layout: The message `No results` is displayed

![image](https://github.com/WordPress/gutenberg/assets/54422211/c3796f57-cfe4-4f30-98c4-ac3d0beca939)

Grid Layout: No message is displayed

![image](https://github.com/WordPress/gutenberg/assets/54422211/169d1062-1349-4099-bc4b-b885ddb11baa)

Table Layout: The message `No results` is displayed

![image](https://github.com/WordPress/gutenberg/assets/54422211/23fcc167-7756-4bf8-b49c-557b6481b70b)

At the very least, some sort of message should be displayed in the grid layout as well.

## What is your proposed solution?

Even in the Grid layout, the message "No results" should be displayed. Or maybe "No items found." Additionally, it might be good to provide the user with a UI to add the first item, as suggested in #54642.

**Comment by annezazu** [comment]
cc @mcsf for consideration!
