### ISSUE TITLE
Post Editor: A clearer Post Type indication

### ISSUE THREAD

**Issue by syhc** [WordPress/gutenberg#58480]
## What problem does this address?

Currently, it is pretty difficult for users to quickly identify what post type they are on; specifically on WordPress instances that have more than two standard post types.

On the classic editor, a user can can quickly tell by the title of the editor "Add new X" or "Edit X", where X is the post type name.

However, on the Gutenberg editor, it is not obvious:

1. Document Title (Look at the browser tab)
2. Settings sidebar (the settings sidebar could be closed)
3. Block Breadcrumb/Status bar (at the bottom, not obvious)
4. URL of the page
5. Admin menu if the user are not using full screen mode

## What is your proposed solution?

We should take cue from the site editor, and use the top middle of the top toolbar to indicate the post type; like how the site editor use it for the template name.

**Comment by andrewserong** [comment]
Thanks for opening this issue! As of https://github.com/WordPress/gutenberg/pull/65170 from @creativecoder, this has been added to the post and site editors — within the document bar, the post type is now displayed.
