### ISSUE TITLE
Image: Link preset suggestions broken arrow key navigation

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#58495]
### Description

When adding a link to an image, the initial view of the UI shows some preset suggestions:
- Link to image file
- Link to attachment page
- And the recently added 'Expand on click'

This is an ARIA role-menu with menuitems, where navigation with arrow keys is expected to work. In fact, arrow keys navigation works in WordPress 6.4 but it's broken on Gutenberg trunk. As such, this a regression that needs to be fixed for the next release.

It appears this menu has gone through some refactoring but not enough keyboard testing was done. Also, having an E2E trest in place would be nice to make sure arrow keys navigation doesn't break again in the future.

Screenshot from WordPress 6.4 where arrows work:
![Screenshot 2024-01-31 at 10 51 29](https://github.com/WordPress/gutenberg/assets/1682452/be38c8f9-0c84-41e6-a408-8b8678f7f247)

Screenshot from Gutenberg trunk where arrows key navigation is broken:

![Screenshot 2024-01-31 at 10 47 40](https://github.com/WordPress/gutenberg/assets/1682452/59d823a1-f837-444d-80e0-7dcfb2cfcb6e)

Cc @annezazu can we please make sure this gets fixed for WP 6.5? Thanks 🙏 

### Step-by-step reproduction instructions

- Test in WordPress 6.4
- Add an Image block
- In the block toolbar, click the 'Insert link' button.
- Initial focus is set on the input field.
- Press the Tab key three times to move focus to the first preset 'Media file'.
- Press the Down or Up arrow keys and observe they move focus through the menu items.
- Test with Gutenberg trunk.
- Add an Image block
- In the block toolbar, click the 'Insert link' button.
- Initial focus is set on the input field.
- Press the Tab key three times to move focus to the first preset 'Link to image file'.
- Press the Down or Up arrow keys and observe nothing happens.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@artemiomorales  another one for you to dig into <3
