### ISSUE TITLE
Can't insert Navagation blocks with wp.data.dispatch("core/block-editor") 

### ISSUE THREAD

**Issue by Louisna123** [WordPress/gutenberg#58520]
### Description

The html code of Navigation generated by block editor are parsed to blocks, but it can't be inserted to block editor with wp.data.dispatch("core/block-editor") .
For general html code consisting of paragraphs, list, etc., it works fine.

### Step-by-step reproduction instructions

```
const content = '''<!-- wp:navigation-link {\"label\":\"www.google.com/\",\"url\":\"https://www.google.com/\",\"kind\":\"custom\"} /-->''';
const blocks =  wp.blocks.parse(content);
wp.data.dispatch("core/block-editor").insertBlocks(blocks);
```

VM16405:1 Uncaught SyntaxError: Unexpected string
![Snipaste_2024-02-01_02-56-54](https://github.com/WordPress/gutenberg/assets/157883458/72ac8db4-5e99-4c76-9ccc-fd7bf859bfb0)

### Environment info
WP 16.4.22, Gutenberg 17.5.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by eddybase** [comment]
Also, wp.data.dispatch("core/block-editor") doesn't work for the blocks parsed from the html code of some complicated blocks (Category block, tags block)

**Comment by talldan** [comment]
@Louisna123 There are a few issues with the code you posted - the triple quote marks aren't valid javascript, there's a lot of escaping in the string which needs to be removed, and a navigation link also can't be inserted anywhere, only in the navigation block.

**Comment by eddybase** [comment]
> @Louisna123 There are a few issues with the code you posted - the triple quote marks aren't valid javascript, there's a lot of escaping in the string which needs to be removed, and a navigation link also can't be inserted anywhere, only in the navigation block.

Thank you. I'll do further study on it.
