### ISSUE TITLE
404 error on preview page

### ISSUE THREAD

**Issue by marco910** [WordPress/gutenberg#58544]
### Description

When clicking the "Preview in new tab" button in the editor, the current post/page usually opens up in a new tab as preview with a URL like `https://mysite.com/?page_id=1234&preview=true`. Since a while, this doesn't work anymore. Instead of getting the preview of the page/post, the user is getting a 404 error page, because he's redirected to `/wp-admin/undefined`.

This only happens when directly clicking on the "Preview in new tab" button in the editor. When making a right-click and "Open link in new tab" everything works fine.

### Step-by-step reproduction instructions

1. Create new post or page in one of the default post types or a custom one.
2. Save it as draft.
3. Click the "Preview in new tab" button in the editor

### Environment info

- WordPress 6.4.2
- Custom WordPress theme (worked fine with that in the past)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hi @marco910 - to help with narrowing down the issue - can you tell me if you still get the same issue when using a default theme like Twenty Twenty-Four?

**Comment by marco910** [comment]
Hi @jordesign 

I'm currently setting up a dev environment to investigate and test this more in depth. Then I can also switch themes.

What I noticed when debugging on the production site is: When opening the preview in the new tab (without making a right-click and "Open link in new tab") there is flashing the animated WordPress logo shortly which is an indication that the default preview page has been displayed. But then I think a redirect to `/wp-admin/undefined` happens

**Comment by t-hamano** [comment]
Hi @marco910,

If you are using a Chrome browser, the URL should be displayed in the bottom right corner when you hover the mouse over "Preview in new tab". Is a normal URL displayed here?

If so, the moment you open this URL, a redirect might occur due to plugins, server settings, etc.

![preview-link](https://github.com/WordPress/gutenberg/assets/54422211/d98ba0bf-8ba2-4933-b1ac-fbf117d4eb58)

**Comment by marco910** [comment]
Hi @t-hamano ,

I'm using Chrome on macOS but tested also with multiple browsers. It looks exactly as in your screenshot, where the correct URL is display in the bottom left corner of the browser window. Also, when I inspect the "Preview in new tab" button with dev tools, the URL is set correct as `href` value of the `<a />` element.

I will make further tests in a different environment to hopefully find the cause.

**Comment by marco910** [comment]
Hi there!

After testing around a few days with multiple themes and plugins, we have found the issue that was causing the redirect to `/wp-admin/undefined`. It was not caused by the custom WordPress theme, but by a plugin installed on the site. After updating it to it's latest version, we could fix the issue.

Thanks for your help @t-hamano and @jordesign !
