### ISSUE TITLE
Documentation for "@wordpress/experiments" should be pointing to @wordpress/private-apis

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#58560]
## What problem does this address?

`@wordpress/experiments` was renamed to `@wordpress/private-apis`
https://github.com/WordPress/gutenberg/pull/47839

But now there are two packages documented:
https://developer.wordpress.org/block-editor/reference-guides/packages/packages-experiments/
https://developer.wordpress.org/block-editor/reference-guides/packages/packages-private-apis/

**Comment by t-hamano** [comment]
I think this issue needs to be addressed on Developer.WordPress.org theme, so I submitted a PR.

https://github.com/WordPress/wporg-developer/pull/502

cc @ndiego @justintadlock
