### ISSUE TITLE
Blocks: Uncaptioned images / quotes dirty post without change

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#5857]
## Issue Overview

If selecting an image or quote block which has no caption / citation, proceeding to deselect the block marks the post as having changes, despite no changes being made.

## Steps to Reproduce

1. Start a new post
2. Insert an image or quote block
3. Set main content
   - For image block, set an image
   - For quote block, set a quote text
4. Deselect the block
5. Save the post
6. Select the block
7. Deselect the block

## Expected Behavior

There are no changes to be saved.

## Current Behavior

The post is marked as having changes. Autosave will occur after 10 seconds, and the user will be prompted about unsaved changes if attempting to navigate away in the meantime.

## Possible Solution

Probably unnecessarily calling `setAttributes` from these blocks when no changes have been made.

**Comment by jorgefilipecosta** [comment]
Hi @aduth I'm not being able to replicate this problem for the image block. Is the problem still happening in your tests on the image block?

**Comment by aduth** [comment]
Appears this has since been resolved. Thanks for looking @jorgefilipecosta .
