### ISSUE TITLE
Font Library: Last font in default collection is obscured by dialog footer

### ISSUE THREAD

**Issue by ironprogrammer** [WordPress/gutenberg#58586]
### Description

When the default font collection is scrolled to the bottom, the last font (currently Zilla Slab Highlight) is partially obscured by the footer bar of the "Manage fonts" dialog.

I expect that the last font in the list should be plainly visible.

### Step-by-step reproduction instructions

1. In the site editor, open the **Styles** panel, and select Typography.
2. Click the "Manage fonts" icon (the "Aa" glyph above the font list) and go to the Install Fonts tab.
3. Scroll down to the end of the list.
4. Observe that the last font is partially/mostly covered by the footer of the dialog.

### Screenshots, screen recording, code snippet
This animation shows scrolling to the bottom of the list, and how the last font is obscured by another panel, and cannot be scrolled higher to be seen clearly.
![font-library-last-collection-font](https://github.com/WordPress/gutenberg/assets/824344/893acb22-777a-432e-8e79-e0b77be22bab)

### Environment info

- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 14.3
- Browser: Safari 17.3
- Server: nginx/1.25.3
- PHP: 8.3.2
- WordPress: 6.5-alpha-56966-src
- Theme: twentytwentyfour v1.0
- Active Plugins:
   - gutenberg v17.6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
This issue has also been reported in #58799, so let me close this issue as a duplicate. This issue will also be resolved by #58794.
