### ISSUE TITLE
MediaReplaceFlow: layout regression

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#58593]
### Description

It appears that recent changes made in the `LinkControl` component have caused a regression in the layout of the `MediaReplaceFlow` component.

As far as I researched, the two PRs, #57775 and #57608, are related.

---

### ⚒️ Before #57775 is merged

- #58621
- Commit hash: 27fc84e

![commit_27fc84e0](https://github.com/WordPress/gutenberg/assets/54422211/b7c6e089-bfbc-4d65-8afc-fe808d0d9a89)

This should be the expected layout.

---

### ⚠️ After #57775 was merged
 
- #57775
- Commit hash: 614e035

![commit_614e0355](https://github.com/WordPress/gutenberg/assets/54422211/99227d0a-7483-4c1b-973b-4413609729b8)

- The icon and URL are misaligned. 
- The background color of the icon may also not be what we intended.
- Also, this may be a Windows OS-specific problem, but the text _descender_ is cut off.

---

### ✅ After #57608 was merged

Fixed by #58597

- #57608
- Commit hash: 84b09ce

![image](https://github.com/WordPress/gutenberg/assets/54422211/0d82a27d-821d-4cb8-babd-29d79b78ade2)

- A scroll bar will appear.

---

These changes are in the Gutenberg version that ships to WP6.5, and I think they need to be fixed, so I'll add them to the editor task for WP6.5.

### Step-by-step reproduction instructions

- Insert an Image block
- Add media.
- Click "Replace" button.

**Comment by scruffian** [comment]
If the UI demands extra data then shouldn't we add additional props to support it? I tried to fetch the data in the replace media flow component, but that component doesn't like importing from the core data store.
