### ISSUE TITLE
gutenberg_can_edit_post() may erroneously pass a WP_Post to current_user_can() instead of a post ID

### ISSUE THREAD

**Issue by rogertheriault** [WordPress/gutenberg#5859]
## Issue Overview
The return from gutenberg_can_edit_post() may erroneously pass a WP_Post (rather than a post ID) to current_user_can()

## Steps to Reproduce (for bugs)
1. Install Gutenberg and https://github.com/Automattic/Co-Authors-Plus
2. Ensure WP_DEBUG is defined
3. Open the All Posts window. Between the Post Title and edit links, a PHP notice should appear (or, check error_log)
```
Notice: Object of class WP_Post could not be converted to int in /wordpress/wp-content/plugins/Co-Authors-Plus/template-tags.php on line 7
```
4. This could theoretically also be reproduced without that specific plugin, by activating certain other plugins that filter on edit_posts capabilities

## Expected Behavior

filtering of user capabilities should result in a post ID being passed when filtering 'edit_posts' for example

## Current Behavior

In some cases, instead of a post ID, the entire WP_Post object is passed

If a plugin or theme is filtering current_user_can and tries to cast the $post_id to in, a notice will be issued:
```
PHP Notice:  Object of class WP_Post could not be converted to int
```
Plugins may not be able to correctly filter capabilities as a result.

## Possible Solution

at [line 274 of lib/register.php](https://github.com/WordPress/gutenberg/blob/master/lib/register.php#L274), this line:
```
return current_user_can( 'edit_post', $post_id );
```
should probably be changed to:
```
return current_user_can( 'edit_post', $post->ID );
```

**Comment by vRobM** [comment]
Will this take care of all the "Publish failed" issues folks are having through CloudFlare?

**Comment by danielbachhuber** [comment]
> Will this take care of all the "Publish failed" issues folks are having through CloudFlare?

@vRobM Can you point me to the issue you're referring to?

**Comment by vRobM** [comment]
https://github.com/WordPress/gutenberg/issues/3948
https://github.com/WordPress/gutenberg/issues/1761
https://github.com/WordPress/gutenberg/issues/2565

++ Rob

About me <https://remote.com/r>

**Comment by danielbachhuber** [comment]
@vRobM I don't believe this issue is related to that one.
