### ISSUE TITLE
wp-block-code doesn't add proper spaces but unicode variants

### ISSUE THREAD

**Issue by Digiover** [WordPress/gutenberg#58605]
### Description

When adding an space in a wp-block-code block, it doesn't add a space but something unicode that looks like an space. This is annoying when copy-pasting code back and forth. It's always something with Gutenberg (see [56855](https://github.com/WordPress/gutenberg/issues/56855))

### Step-by-step reproduction instructions

1. Start a new post
2. add a wp-block-code block
3. write or paste in your code
4. add spaces
5. copy-paste the code into an editor/IDE like Visual Studio Code. It'll complain:

> The character U+2003 is not a basic ASCII character.

### Screenshots, screen recording, code snippet

![Screenshot 2024-02-02 102858](https://github.com/WordPress/gutenberg/assets/8005150/7ef2125a-1dad-4918-8457-46e7ed68b954)
![Screenshot 2024-02-02 102850](https://github.com/WordPress/gutenberg/assets/8005150/a15e1135-3dbb-4a42-8831-f813b354da94)

### Environment info

- WordPress version: WordPress 6.4.3
- Gutenberg version (plugin): 17.6.0
- running Hester theme version 1.1.4.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report. I would like to close this issue as it has been summarized in #58659.
