### ISSUE TITLE
Epic: 6.5 Social Media Assets

### ISSUE THREAD

**Issue by thetinyl** [WordPress/gutenberg#58627]
### What is this?

This is a tracking issue to cover the work being done for 6.5 release marketing social media. Along with the featurettes requested here #58578, these additional social assets will be shared across WordPress.org social channels including Twitter/X, LinkedIn, Facebook, and Instagram. 

The creative needed includes the following:

- Pre-release teaser/Coming soon messaging
- Celebratory release stats (can be a series of graphics or animated video)

Examples for pre-release:

- [6.0 "Now loading..." ](https://twitter.com/WordPress/status/1528839442374459396)
- [6.3 "Groove to WP 6.3" ](https://twitter.com/WordPress/status/1688563742164852736)
- [6.4 "Coming soon"](https://twitter.com/WordPress/status/1721512277994565781)

Examples for celebratory stats:

- [6.3 stats video](https://twitter.com/WordPress/status/1691468660202696705)
- [6.4 stats video](https://twitter.com/WordPress/status/1725915083019047358)

### Timing*

- [x] Pre-release teaser complete: **March 19**
- [x] Contributor stats complete: **April 9**

_*Proposed dates are flexible._

### Content

The pre-release teaser could be a simple "6.5 coming soon" message, or... it could be a little more playful with a graphic symbol only to pair with post copy (similar to the "Now loading" example above). 

The contributor stats will only be available post-release. We'll provide those here as soon as they're available, in the meantime the previous videos could serve as a reference for what content will be included.

**Comment by marko-srb** [comment]
**Pre-release teaser**


https://github.com/WordPress/gutenberg/assets/111751264/3a9e5463-9ef9-4ac9-9812-ae07a220e86d

https://github.com/WordPress/gutenberg/assets/111751264/ec07ba70-304f-4fb1-9ac0-26918abf5012


[Google Drive](https://drive.google.com/drive/folders/1S8gIqY3k59SAcZUiHZFaXDtl3-8bjdAG?usp=drive_link)

**Comment by marko-srb** [comment]
In the event that the above suggestion doesn't work, there is the fallback in the folder as well...

CC: @thetinyl @jasmussen 

<img width="717" alt="Screen Shot 2024-03-14 at 15 47 21" src="https://github.com/WordPress/gutenberg/assets/111751264/d9d53b04-081d-4ac4-a700-813ff735210f">

**Comment by thetinyl** [comment]
Thanks for this @marko-srb. It's definitely a change from what we've done before. Personally, I appreciate the concept and bringing something unexpected to a piece that's purely for engagement. 

The only real hesitation I have is that the video leans more towards whimsical than jazzy, which makes it feel off-brand (though the music helps). It also doesn't feel connected in any way to the other release visuals—this isn't necessarily a must if it shares elements with the eventual jazzer graphic, but could still be nice to have. 

I'm curious what you think, @dansoschin. 

If we do go with this version, some specific suggestions:
- Cut down the length. I think it works fine as a :10 or :15 
- Copy could read "Stand by for WordPress 6.5"... this whole thing has "trying to fill the time/waiting room" vibes

**Comment by DanSoschin** [comment]
I agree... it is unexpectedly whimsical. I like Lauren's suggestion of "Stand by" or similar to tie into the idea of "hanging out on the street corner waiting."

Could there be a way to tie into the colors/visuals used in the highlight feature grid or other milestone announcements in order to connect this more? Not 100% necessary as I do like mixing things up a bit. So if the brand/design folks are good, so am I.

**Comment by marko-srb** [comment]
Thanks @DanSoschin and @thetinyl . 

Re your points:

- colors of the highlight grid are still not present/final. Other than the green *(which is actually present in the video) and blue, which I would avoid as this is an independent piece, plus it gets very weird if duotone with blue is color of the video, instead of B&W. What I can try though is make hand-drawn lines that animate and follow the hand gestures, but I am not sure if that'll work... Will test. 
- shorter. Can be.
**- whimsical vs jazzy**. Yes, this was intentional and to steer things up a bit. We can always take it down, as it's only a teaser. Regardless, if that doesn't work, I provided static load icon that is resembling on the previous example you shared on top. I am ok with your decision, whatever works better for you. In case it is the static one, please let me know so I don't spend more time on the video that won't be used. If video, I'll try those animated lines that follow hand gestures.

Thanks!

**Comment by thetinyl** [comment]
> as it's only a teaser.

You said it: it's the perfect opportunity to try something new. As long as there are connecting visual elements to the jazzer graphic, it's ok that it doesn't match other release pieces. We can continue with the video. Thanks @marko-srb!

**Comment by jasmussen** [comment]
> In the event that the above suggestion doesn't work, there is the fallback in the folder as well...

Assuming the fun piece is moving forward, I nevertheless wanted to suggest a tweak to the fallback. I like the idea of the "hold" spinner, but we can actually use the exact spinner that's [in the block editor](https://wordpress.github.io/gutenberg/?path=/docs/components-spinner--docs) instead:

![Screenshot 2024-03-18 at 10 14 11](https://github.com/WordPress/gutenberg/assets/1204802/1e37947d-ea56-4c68-9d51-b5083417529e)

**Comment by marko-srb** [comment]
@thetinyl 

Here's the final video in two ratios. I couldn't make the hand gestures with lines as the video is shorter and then it looks weird. So clean variant with edited length and text works well. 

Let me know if this task is closed, or if anything else. :) 

https://drive.google.com/drive/folders/1S8gIqY3k59SAcZUiHZFaXDtl3-8bjdAG?usp=drive_link

**Comment by marko-srb** [comment]
https://github.com/WordPress/gutenberg/assets/111751264/67f435c9-6a3a-419f-8aba-250bc4cae29c

**Comment by thetinyl** [comment]
Thanks @marko-srb. Looks nice. We can consider the teaser wrapped. 

Contributor stats, as mentioned, will be available early next week once the release is out.

@DanSoschin between the square and the wide versions, I believe that should cover everything for social, but give a holler if that's not the case. 👍

**Comment by DanSoschin** [comment]
Good to go with the "stand by" video queued up for Thursday! Thank you!

**Comment by thetinyl** [comment]
@marko-srb Here are the contributor stats we can use:

700+ contributors
57 countries
70+ locales translated
150+ new contributors

@DanSoschin In the past, we've used this content to celebrate a release's monthaversary. Is that something you'd want to continue? If so, it gives Marko more time to put this together (assuming you need more time, Marko).

**Comment by annezazu** [comment]
Closing this out as I assume this has been completed.

**Comment by thetinyl** [comment]
Whoops, this wasn't complete yet. The work is happening though, so no worries that this is closed prematurely.

**Comment by annezazu** [comment]
Okay! Happy to reopen as needed too :)

**Comment by marko-srb** [comment]
https://github.com/WordPress/gutenberg/assets/111751264/8915ad76-86b2-4bfd-bc8f-2e44a77b9e2b

Here's first draft. Let me know if this works. @thetinyl

**Comment by thetinyl** [comment]
Works for me! Thanks @marko-srb.

**Comment by marko-srb** [comment]
Great.

Sending files shortly...

**Comment by thetinyl** [comment]
Noting that tasks for this issue are done. And since the issue is already closed—that's all she wrote! 🚀
