### ISSUE TITLE
Introduce formal API for rendering server-side previews of dynamic blocks

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#5862]
Dynamic blocks are preferable pretty much any time your block departs from pure semantic HTML, for a couple of reasons:

1. You can render context-specific output on the frontend vs. RSS vs. AMP.
2. You can change output without transforming all stored references.

`register_block_type()` already accommodates dynamic blocks with `render_callback`, which works great for display. For editor preview however, you're left to duplicate some amount of your `render_callback` in JavaScript.

Ideally, Gutenberg would offer a formal API for rendering server-side previews of dynamic blocks.

Related #1054 #780 #5615

**Comment by westonruter** [comment]
@danielbachhuber I think this is a duplicate of #780. Please see the PR for this in #5602.

**Comment by danielbachhuber** [comment]
I suppose it is. Closing in favor of #780
