### ISSUE TITLE
Button: Focus outline is too thick in disabled Primary variant

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#58632]
On the ["Primary" `Button` variant](https://wordpress.github.io/gutenberg/?path=/story/components-button--primary&args=__experimentalIsFocusable:true;disabled:true), the focus outline thickness is wrong when `disabled` and `__experimentalIsFocusable` are both true.

## Screenshots

| Current | Expected | Reference (Not disabled) |
|--------|-------|-------|
|![Focus outline too thick](https://github.com/WordPress/gutenberg/assets/555336/7803388c-edb5-4717-881f-97bfd6a2e7a0)|![Expected outline thickness](https://github.com/WordPress/gutenberg/assets/555336/5b1b58f3-52eb-401f-8146-d9e68cc91ca9)|![Focus when not disabled](https://github.com/WordPress/gutenberg/assets/555336/840d7d7e-e14b-4f64-b1cb-6a7db731fcb6)|

**Comment by HimanshuSahu-1** [comment]
Asssign this issue to me

**Comment by amustaque97** [comment]
Changes are merged, I guess this ticket can be closed @mirka

**Comment by mirka** [comment]
@amustaque97 It doesn't look like it has been fixed yet? 🤔
