### ISSUE TITLE
Image block invalidation error.

### ISSUE THREAD

**Issue by creative-andrew** [WordPress/gutenberg#58648]
### Description

On my website, I am getting the following error on the console:

blocks.min.js?ver=7204d43123223474471a:10 Block validation: Block validation failed for `core/image` (Object).

Content generated by `save` function:

`<figure class="wp-block-image alignwide size-full"><img src="https://www.nuvoledibellezza.com/wp-content/uploads/2024/01/unghie-primaverili-4-1040.jpg" alt="unghie primaverili"/><figcaption class="wp-element-caption">Photo Credits: ©NuvolediBellezza</figcaption></figure>`

Content retrieved from post body:

`<figure class="wp-block-image alignwide size-full"><img src="https://www.nuvoledibellezza.com/wp-content/uploads/2024/01/unghie-primaverili-4-1040.jpg" alt="unghie primaverili" class="wp-image-126715" /><figcaption class="wp-element-caption">Photo Credits: ©NuvolediBellezza</figcaption></figure>`

This is only happening on some posts:

![image](https://github.com/WordPress/gutenberg/assets/18492002/dd1caa3f-e7e3-426b-afc1-ea80b70cc85a)

I don't understand why the "class" is not getting added correctly. 

### Step-by-step reproduction instructions

I cannot reproduce it consistency, it only happen on some pages. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by talldan** [comment]
> I don't understand why the "class" is not getting added correctly.

<s>@creative-andrew What is the class, is that something you've added?</s>

Actually, ignore me, I see it's something added by the block.

It seems like the block is missing an `id` attribute somehow.

If you go into the code editor, could you copy and share here the full markup of the image block, including the `<!-- wp:image ` html comments?

**Comment by creative-andrew** [comment]
@talldan Thanks for your reply.

Here is an example:

```html
<!-- wp:image -->
<figure class="wp-block-image alignwide size-full"><img src="https://www.nuvoledibellezza.com/wp-content/uploads/2024/01/unghie-primaverili-4-1040.jpg" alt="unghie primaverili" class="wp-image-126715" /><figcaption class="wp-element-caption">Photo Credits: ©NuvolediBellezza</figcaption></figure>
<!-- /wp:image -->
```

It seems like the `save` function is removing `wp-image-ID` for some reason.

**Comment by talldan** [comment]
@creative-andrew Is there a chance this image block's html was edited manually? Usually the first line of HTML for the block should be more like this:
```html
<!-- wp:image {"id": 126715,"sizeSlug":"full","linkDestination":"none"} -->
```

You seem to be missing all of the attributes.

**Comment by creative-andrew** [comment]
I am closing it for now as it might be caused by something not related to core.
