### ISSUE TITLE
How to Add Components Toolbar on Main Title?

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#5866]
Hi,

Just read [this post](https://automattic.design/2018/03/25/testing-gutenberg-an-empathy-challenge/) and wanted to help out on adding Main Title alignment option for my [Block Options plugin](https://wordpress.org/plugins/block-options/). Can I add additional toolbar to the title? Probably below the permalink option. Thanks!

**Comment by danielbachhuber** [comment]
Hi @phpbits,

Apologies for the late reply. It's not currently possible to add a toolbar to the title.
