### ISSUE TITLE
Block Bindings: Pressing Enter from connected block doesn't move focus to the newly created block.

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#58674]
### Description

One of the most established interaction conventions in the Editor is that pressing Enter at the end of a block creates a new default block i.e. a Paragraph _and_ moves focus to the newsly created Paragraph.

Bound (connected) blocks seem to break this long established interaction. When pressing Enter:
- The new Paragraph is created.
- Focus is _not_ moved.

Animated GIF to better illustrate:

![focus not moved](https://github.com/WordPress/gutenberg/assets/1682452/8afb905b-0c8f-42bc-bc62-4538c49d63c8)

### Step-by-step reproduction instructions

- Add a normal Paragraph block.
- Follow instructions from https://github.com/WordPress/wordpress-develop/pull/5888 to create a Paragraph with content connected to a post meta.
- Click the first Paragraph and move the cusror at the end of its content.
- Press Enter.
- Observe a new Paragraph is created _and receives focus_.
- Click the connected Paragraph.
- Observe the Paragraph is selected.
- Press Enter.
- Observe a new Paragraph is created but focus is _not_ moved to it.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by colorful-tones** [comment]
@artemiomorales we're going through the [WordPress 6.5 Editor Tasks board](https://github.com/orgs/WordPress/projects/148/views/1), and I see you self-assigned this task. Are you able to provide an update on any progress or discovery around this issue please?

**Comment by artemiomorales** [comment]
@colorful-tones Thanks for the ping! I've been on this bug for a couple of days and am feeling a bit stuck, though I've just created a [draft pull request](https://github.com/WordPress/gutenberg/pull/58958) (still not working yet) to facilitate discussion.
