### ISSUE TITLE
ConfirmDialog: Improve styles, and use for block removal warning

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#58690]
Using 6.5-alpha-57531, I noticed the text for deleting a pattern category is quite squished when compared to other modals as shown below.

Screenshot of deleting a pattern category modal:
![Screenshot 2024-02-05 at 12 22 38 PM](https://github.com/WordPress/gutenberg/assets/26996883/7c17c702-f49e-4745-9f1a-5fa1466237ef)

Screenshot of warning about deleting a query loop block on a template:

![Screenshot 2024-02-05 at 12 23 46 PM](https://github.com/WordPress/gutenberg/assets/26996883/c63d7415-d371-48a0-9231-647e6047e7ca)

Can we unify this a bit more and adding a proper heading to the delete modal too for consistency? cc @WordPress/gutenberg-design for any thoughts here.

**Comment by t-hamano** [comment]
At least the current title feels a little pretentious to me. For example, I think it would be a good idea to indicate what we are trying to do with a title like "Delete _Something_".

Another approach, as shown in #58390, is to unify all buttons that perform destructive actions in red and remove the title.

**Comment by talldan** [comment]
> the text for deleting a pattern category is quite squished when compared to other modals

Are you thinking the line-height of the text, width of the modal, or both? I agree it does look a bit squished, mostly the line-height, but perhaps the modal could be wider too.

The Pattern Category modal uses the general `ConfirmDialog` component and the line height is controlled by that component (though it also has a custom width set, not sure why):
https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-confirmdialog--docs

The block removal modal doesn't use `ConfirmDialog`, but it really should for consistency of styles.

Then it's just a situation of updating the styles for `ConfirmDialog` and it should be consistent everywhere.

**Comment by jameskoster** [comment]
ConfirmDialog could be updated to use the new(ish) `size` property on Modal. Maybe it can already be passed and we just need to update the instances?

I don't see any reason for the text styling to be different in these examples.

**Comment by talldan** [comment]
It looks like the reason the pattern category dialog has a custom width is that without it the `ConfirmDialog` takes up the width of the content, so when there's long text it gets quite wide. I think it should really have a hard coded width of the 'small' or 'medium' modal size.

Also worth noting the responsiveness of these modals is not great, there's a lot of empty space! I think there's a bit of work to do here all around:
![Screenshot 2024-02-07 at 12 17 07 pm](https://github.com/WordPress/gutenberg/assets/677833/d3df2050-adc5-43ba-b523-6ab84c68a306)
![Screenshot 2024-02-07 at 12 19 02 pm](https://github.com/WordPress/gutenberg/assets/677833/6d3d7e23-dcca-4d45-b4c3-074038a88ee3)

**Comment by jameskoster** [comment]
If it's possible to detect, we might improve usability on small touch devices (phones) by pinning these to the bottom of the viewport and making the confirm/cancel buttons fill, e.g.:

<img width="361" alt="Screenshot 2024-02-07 at 11 44 44" src="https://github.com/WordPress/gutenberg/assets/846565/3ad1c00a-7074-4f8c-a025-a854416d11d8">

**Comment by richtabor** [comment]
> If it's possible to detect, we might improve usability on small touch devices (phones) by pinning these to the bottom of the viewport and making the confirm/cancel buttons fill, e.g.:

I like the presentation better generally, even for desktop ha :)

**Comment by jameskoster** [comment]
Perhaps there's a way to tie to presentation of the actions to the modal dimensions. IE if the `size` is `small` (384px) or less, make the buttons fill. Agree it could work well on desktop too.

![modals](https://github.com/WordPress/gutenberg/assets/846565/54b46de1-9c21-4717-b487-2943a3e0d46c)

**Comment by jasmussen** [comment]
If we want to change the details we should change them across, I'd avoid having one style for either viewport. I also think we can look at this holistically in a design system, rather than piecemeal.

**Comment by getdave** [comment]
I'm reading the discussion here and trying to decide on what needs to be done for WordPress 6.5. My understanding is:

- `ConfirmDialog` needs to be updated with new `size` property from modal.
- Modal for deleting a pattern category needs to be:
    - aligned with other modals using `ConfirmDialog` component
    - use updated text wording 

In future releases we can look at unifying and improving the dialogs across the design system as suggested.

@WordPress/gutenberg-components Are you able to assist here? 🙏

**Comment by talldan** [comment]
> Modal for deleting a pattern category needs to be:

Other way around, it's the block removal warning that's not using `ConfirmDialog`, though at the same time it looks better than `ConfirmDialog`. So I think the plan should be:
- Improve the styles for `ConfirmDialog` (line height, sizing, etc.)
- Update the block removal warning to use `ConfirmDialog` instead of its custom implementation.

**Comment by annezazu** [comment]
What can we do to iterate and improve for 6.5? I'd like to see the modal updated to be consistent with other modals and, ideally, we can ship some modal responsiveness improvements. @scruffian tagging you in as you very kindly recently helped with this!

**Comment by youknowriad** [comment]
Given that RC1 is today I'm removing this one from 6.5 as non essential.

**Comment by scruffian** [comment]
I made a PR to deal with this but I am concerned that it might be too big a change: https://github.com/WordPress/gutenberg/pull/59645
