### ISSUE TITLE
Inconsistent "BackButton" in site editor

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#58692]
We have two different "Back" buttons in the site editor; let's consolidate these into one consistent UI. I suspect that during some of the unification work the "Back" button was introduced in the canvas area. Instead we should rely on the existing "Back" button within the DocumentBar. 

### Current

As-is, the "Back" button in the top left of the UI does the same exact action as selecting the WP icon at the top left. It's not ideal having two actions do the same thing right next to each other—one of which is not anchored really (the "Back" button). 

![CleanShot 2024-02-05 at 14 33 22](https://github.com/WordPress/gutenberg/assets/1813435/1d3c6116-6d7c-4782-bfcf-ee08c9e9cde9)

### Expected 

![CleanShot 2024-02-05 at 14 32 58](https://github.com/WordPress/gutenberg/assets/1813435/58092ec5-22eb-4761-ac98-c712f5c230a2)

I propose we utilize the "Back" button within the `DocumentBar`. 

We can circle back and tidy up the design itself, but it is an established flow to navigate "up" one level, out of template editing (to the page), that we could also use to navigate "up" one level, out of pattern editing (to the site editor patterns).

**Comment by annezazu** [comment]
This seems to overlap with a number of issues -- which can we close?

https://github.com/WordPress/gutenberg/issues/56868
https://github.com/WordPress/gutenberg/issues/54628
https://github.com/WordPress/gutenberg/issues/50106

**Comment by richtabor** [comment]
They're all related, but slightly different angles. I see those are exploratory whereas this is an actionable fix that we need, regardless of the outcomes of those particular ideas.

**Comment by richtabor** [comment]
@youknowriad do you think this made it in from the recent unification work?

**Comment by richtabor** [comment]
Noting that when this is resolved, we can move forward with https://github.com/WordPress/gutenberg/pull/57124

**Comment by youknowriad** [comment]
I think this has been solved already by @noisysocks

**Comment by noisysocks** [comment]
Yes fixed by https://github.com/WordPress/gutenberg/pull/58528.
