### ISSUE TITLE
Block mover controls have a low contrast ratio

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#587]
The controls to move a block up and down are currently this color:

```scss
$light-gray-600: #d7dade;
```

This has a [contrast ratio of 1.4 against white](http://leaverou.github.io/contrast-ratio/#%23d7dade-on-white):

![2017-05-01t11 55 12-0500](https://cloud.githubusercontent.com/assets/227022/25586566/7bf82e4a-2e65-11e7-82dd-92777d6f7bd7.png)

The minimum contrast ratio according to WCAG 2.0 is 4.5:

- https://www.w3.org/TR/WCAG/#visual-audio-contrast
- https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_color_01

**Comment by afercia** [comment]
Just as a note (also for #573) disabled controls don't need to meet the requirement so the disabled block mover button can have a contrast ratio lower than 4.5:1.

**Comment by nylen** [comment]
This appears to have been resolved by #981.
