### ISSUE TITLE
Latest Posts block needs extra classes on front-end markup

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#5870]
## Issue Overview
The Latest Posts block allows you to insert your latest posts in Grid layout. In the settings, you can specify the number of columns they should appear in. e.g. the image below shows 6 posts in 3 columns.

![gutenberg-latestposts1](https://user-images.githubusercontent.com/2078245/38075471-3817590c-337e-11e8-94ad-0d6f4db6f8a8.png)

On the front-end, it's impossible to style this in a grid  for a couple of reasons.
1. The markup for the List View and the Grid View is identical so it's impossible to tell whether the list items are supposed to be displaying in a List or in a Grid
2. The markup for the Grid View doesn't have a class to specify how many columns there are supposed to be which obviously makes it impossible to specify a width for each list item

Markup for Latest Posts Block in Grid View
![screenshot_611](https://user-images.githubusercontent.com/2078245/38075896-a6a1827a-337f-11e8-9cc9-96b80a896ff6.png)

Markup for Latest Posts Block in List View
![screenshot_612](https://user-images.githubusercontent.com/2078245/38076316-fb7dfe30-3380-11e8-9956-31c557d70a00.png)

As a comparison, when you add a Gallery block, the markup includes a class for the number of columns that there's supposed to be.

![screenshot_610](https://user-images.githubusercontent.com/2078245/38075954-cd74001c-337f-11e8-95ab-14e70e59347f.png)

## Steps to Reproduce (for bugs)
1. Insert Latest Posts block
2. Switch layout to Grid view
3. Publish page and view markup on front-end

## Expected Behavior
There needs to be different class for the Latest Post block depending on whether you select the List View or the Grid View. There also needs to be a class to specify the number of columns when using the Grid View

## Current Behavior
Unable to style Latest Posts blocks properly as the markup isn't suffucient

_Gutenberg 2.5.0
Firefox Quantum 59.0.2 (64-bit)
WP 4.9.4_

**Comment by gziolo** [comment]
This should be fixed by @jomurgel in #6258 🙇
