### ISSUE TITLE
Disable bulk actions on theme-supplied patterns

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#58737]
The Patterns data view currently includes patterns supplied by the active theme. These patterns can be duplicated, but not edited in any way. 

Therefore it's quite confusing that the bulk actions interface (checkbox) appears attached to these items:

<img width="300" src="https://private-user-images.githubusercontent.com/846565/303289010-3e69a337-24e3-49e7-b0ce-d69a126ffa97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDc5NjcsIm5iZiI6MTcwNzc0NzY2NywicGF0aCI6Ii84NDY1NjUvMzAzMjg5MDEwLTNlNjlhMzM3LTI0ZTMtNDllNy1iMGNlLWQ2OWExMjZmZmE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxNDIxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmE0OGY4YjY0Y2ZlYzA5ZjI3OTRkZmIzMjk5OGU0MWFhNTViYWI4NTc2Y2U5Y2JhNjZkMjA0MTJlNjc4ODAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xezPiCVNIgsghG3iMNLLEHgEyfc38rpCANGxnlBNVp8">

It's made worse by the presence of the `lock` icon which explicitly states: "This pattern cannot be edited.".

In such cases I think hiding the checkbox could be worth trying.

Alternatively; if bulk actions were added to theme-supplied patterns (e.g. duplicate, export), that would indirectly solve this issue.

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster, the first bulk action for patterns was already added at https://github.com/WordPress/gutenberg/pull/58747 and is available to use.
And I guess export which is available for all patterns also makes sense as a bulk action and could be the next one, so I think patterns will have at least one available action.

**Comment by annezazu** [comment]
+1 to add bulk export! This has come up before (ditto with bulk import): https://github.com/WordPress/gutenberg/issues/56794

**Comment by jameskoster** [comment]
@jorgefilipecosta Ah, that definitely makes this issue much less problematic. 

We may still need a solution to the selectability of patterns that cannot have bulk actions applied (IE theme-supplied patterns). Or is there a plan to add bulk duplication?

**Comment by jameskoster** [comment]
> Or is there a plan to add bulk duplication?

If not, we can hide the checkbox for theme-supplied patterns. That would eliminate the visual tension that exists between the checkbox and the lock icon:

<img width="346" alt="Screenshot 2024-02-08 at 10 06 35" src="https://github.com/WordPress/gutenberg/assets/846565/3e69a337-24e3-49e7-b0ce-d69a126ffa97">

**Comment by jorgefilipecosta** [comment]
> > Or is there a plan to add bulk duplication?
> 
> If not, we can hide the checkbox for theme-supplied patterns. That would eliminate the visual tension that exists between the checkbox and the lock icon:
> 
> <img alt="Screenshot 2024-02-08 at 10 06 35" width="346" src="https://private-user-images.githubusercontent.com/846565/303289010-3e69a337-24e3-49e7-b0ce-d69a126ffa97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODE2MDMsIm5iZiI6MTcwNzQ4MTMwMywicGF0aCI6Ii84NDY1NjUvMzAzMjg5MDEwLTNlNjlhMzM3LTI0ZTMtNDllNy1iMGNlLWQ2OWExMjZmZmE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxMjIxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjU3ZWZmMGM2Y2VjYjJmNjIxYzNkYzBiODhhOGI2ZWI4Y2YzZmYxOWU0OTUxNTMwZTFlNGQ3YjgzYmI5MGFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YjZglT-lInQgODrQD3jkPTjqwspjgW0Quv05h8jCslY">

I don't have immediate plans to add bulk duplication as that involves providing names. I will look into hiding the checkbox, the challenge here is that it is inside the data views and needs to be generic. So something generic would be don't show the check box if no bulk action can be applied to the item. I think it will work but has some performance impact. For all the items we will check against all the actions if they can be executed or not, probably not something to worry about and it is worth it.

**Comment by jameskoster** [comment]
Hmm I think this is quite problematic. Selecting an item(s) and finding that no bulk actions can be applied is a strange experience. It's made worse by the `lock` icon which conceptually contradicts the checkbox. 

I'll update the issue to better describe the problem.

**Comment by jameskoster** [comment]
Note; if we added bulk actions to theme-supplied patterns (duplicate, export), that would indirectly solve this issue.

**Comment by liviopv** [comment]
I was testing the 17.8 and I found this quite confusing. I was initially in "All Patterns", and assumed bulk select would allow me to export.

If there are no plans to allow exporting theme patterns, then we should at the minimum add some context to why the Export option is unavailable when selecting a mix of user patterns and theme patterns.

**Comment by annezazu** [comment]
This PR was merged for 17.8: https://github.com/WordPress/gutenberg/pull/58897

AFAIK this won't be backported to 6.5. As a result, I think for 6.5 we need to disable bulk actions but for the GB plugin we should continue with the bulk actions, including export. cc @jorgefilipecosta

**Comment by jameskoster** [comment]
> I think for 6.5 we need to disable bulk actions

It would be a shame to lose bulk actions on user-generated patterns. If we can finish up https://github.com/WordPress/gutenberg/pull/58950 and re-position the lock icon, hopefully we'd be in a better position to make a decision on this.
