### ISSUE TITLE
No publish button

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#5874]
## Issue Overview
I tried creating a new Page to test something. I entered a title and pasted in three paragraphs of text.

I went to Publish the page but there's no Publish button. Only a _Schedule..._ button.

![gutenberg_nopublishbutton](https://user-images.githubusercontent.com/2078245/38077553-0f5280f8-3385-11e8-9304-a3f247d92de0.png)

## Steps to Reproduce (for bugs)
1. Create new page
2. Enter page title 
3. Try and click the publish button

## Expected Behavior
There should be a Publish button

## Current Behavior
No Publish button

_Gutenberg 2.5.0
Firefox Quantum 59.0.2 (64-bit)
WP 4.9.4_

**Comment by maddisondesigns** [comment]
As a side note: Even after saving as a draft, the button remains as _Schedule..._ instead of turning into an _Update_ button

**Comment by Soean** [comment]
This normally happens, if you publish date is in the future. The Classic editor has the same behavior.

**Comment by maddisondesigns** [comment]
I wasn't trying to Publish in the future. The _Schedule..._ button only appears (or should only appear) if you specifically specify a future date, which I didn't. I simply tried to create a new page.

**Comment by johnbillion** [comment]
I'm seeing this too. To reproduce, simply open a new Post or Page and note that the `Publish...` button says `Schedule...`.

The button's behaviour appears to work as expected, but its label is incorrect. In order to get the button to say `Publish...` you need to change the post date to something prior to the current day.

**Comment by gziolo** [comment]
@jorgefilipecosta, is it related to your latest changes in #5767 and test removal #5858?

**Comment by jorgefilipecosta** [comment]
Yes @gziolo, It may be related to the changes, but I'm not being able to reproduce, maybe it's a timezone related problem.
@maddisondesigns and @johnbillion thank you for reporting this issue, could you please share your time zone? (as it relates to dates it may happen just in some time zones)

**Comment by johnbillion** [comment]
My timezone is set to `Europe/London`.

**Comment by Soean** [comment]
Berlin is UTC+2

- If I select Berlin as Timezone I see the Schedule button
- If I select UTC+2 I see the Publish button

Same in both settings:
Universal time (UTC) is 2018-03-29 14:52:14. 
Local time is 2018-03-29 16:52:14.

**Comment by maddisondesigns** [comment]
Looks like you don't need it anymore, but my timezone is set to `Australia/Melbourne`

**Comment by jorgefilipecosta** [comment]
Thank you all for the reporting and debugging, a fix for this was merged https://github.com/WordPress/gutenberg/pull/5916 and should be available in the next release.
