### ISSUE TITLE
Drag and drop indicator line positioning is incorrect in WP Playground

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#58756]
### Description

Raised by @annezazu in https://github.com/WordPress/gutenberg/pull/58589#issuecomment-1930989933: the drop indicator line (`BlockPopoverInbetween`) when dragging and dropping into the editor canvas is in the wrong position when using WP Playground.

WP Playground renders the editor lower down within the page, with its own chrome added to the top of the page. It appears that this change means that the positioning of the drop indicator line is off.

Ideally, the drop indicator line logic should be resilient to the editor being rendered in a different position to flush against the top of the viewport.

### Step-by-step reproduction instructions

1. Go to https://playground.wordpress.net/ or https://playground.wordpress.net/gutenberg.html to test with a Gutenberg PR
2. Open up the site editor, and go to drag a Heading block from the block inserter to the left or right of a block within the template
3. Notice that the drop indicator line is in the incorrect position vertically (by roughly the same distance as the height of the Playground chrome)

### Screenshots, screen recording, code snippet

In this screenshot, note how the drop indicator line is lower than the position of the Buttons block we're trying to drag next to: 
<img width="1184" alt="image" src="https://github.com/WordPress/gutenberg/assets/14988353/3521d629-f4de-4f58-bb85-694737e4d249">

This doesn't happen in a "normal" Gutenberg/WP environment

### Environment info

- Gutenberg trunk, specifically testing using WP Playground

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Note: this issue isn't exclusive to drag and drop — it also affects the inbetween inserter when hovering between blocks. For example, in the following screenshot, this should have displayed above the Image block:

<img width="728" alt="image" src="https://github.com/WordPress/gutenberg/assets/14988353/5e2acdfb-86e9-4953-b632-564ba2c1b1b0">

**Comment by t-hamano** [comment]
The root cause of this issue may be the same as reported https://github.com/WordPress/gutenberg/issues/58001 for popover and space visualizer issues.

**Comment by andrewserong** [comment]
Thanks @t-hamano! Yes, that helps — sounds like there's a disconnect between the measurements that the popover is using, and then what happens when the positioning is output for it 🤔

**Comment by andrewserong** [comment]
Just in case it helps anyone else with debugging, I can reproduce this issue outside of WP Playground by adding a `wrapper.html` file into the Gutenberg directory, and then accessing it via http://localhost:8888/wp-content/plugins/gutenberg/wrapper.html — here's an example `wrapper.html` (assuming you're using `wp-env` and your dev site is hosted at `localhost:8888`):

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Gutenberg in an iframe</title>
</head>
<body>
    <div class="header">
        <p>This is a header</p>
    </div>
    <iframe class="editor" src="http://localhost:8888/wp-admin/site-editor.php" title="Test site">

    </iframe>
    <style>
        .header {
            background-color: #f4f4f4;
            padding: 20px;
            text-align: center;
        }

        .editor {
            width: 100%;
            height: 100vh;
            border: none;
        }
    </style>
</body>
</html>
```

That then results in the inbetween inserter rendering lower than expected (the same distance lower at the height of the header area):

<img width="1265" alt="image" src="https://github.com/WordPress/gutenberg/assets/14988353/1130e17a-48e5-4b72-8525-8dad5105bd73">

Unfortunately, I haven't had much luck debugging this, and I can't quite work out if it's a recent issue, or a limitation of floating-ui's iframe awareness, in that it sounds like it should be working up the hierarchy of iframes, but perhaps it doesn't consider whether the outer-most document is itself in an iframe? Just pinging @ciampo who previously worked on https://github.com/WordPress/gutenberg/pull/46845 which removed the old overrides to offset iframes, and @jsnajdr who worked on a floating-ui fix that was surrounding traversing up into the iframe parent: https://github.com/floating-ui/floating-ui/pull/2535

I wonder if the problem is to do with floating-ui, the popover component, or how we use popover slots? Incidentally, if I force the editor canvas to be rendered without an iframe (by enabling Custom fields in the editor preferences) then the positioning issue doesn't appear. So to isolate the problem it seems to be present when we're measuring an element or position that is within the editor canvas iframe (i.e. blocks in the canvas) and the whole editor itself is iframed (as in WP Playground).

**Comment by jsnajdr** [comment]
I see you're putting the Site Editor in `iframe`, and the Site Editor page then creates one more nested `iframe` for the edited content. Yes, that indeed triggers a known bug in Floating UI!  The library can't handle two nested iframes and will calculate positions incorrectly. We've been discussing this with @ciampo several times 🙂 But the only place where this manifested so far was Storybook, never a production situation, so it's been a low priority issue I never got around to fix. Does it become high priority now?

**Comment by youknowriad** [comment]
Yes this issue can be reproduced easily on storybook https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--box

**Comment by bph** [comment]
This also seems to be an issue with the Block Toolbar location covering part of the block it belongs, too. 

I originally thought it was a button block regression issue, but when I tested things in a LocalWP environment, it didn't occur. 

**All Screenrecording and screenshot via Playground**

https://github.com/WordPress/gutenberg/assets/39980/ba887894-ad86-4e52-8a27-aca53ba2df50

It also happens with other blocks: Example paragraph block + Image block
![Screenshot 2024-02-08 at 11 11 12](https://github.com/WordPress/gutenberg/assets/39980/71b6708f-8b96-453b-a591-10055e1942a9)

![Screenshot 2024-02-08 at 11 21 14](https://github.com/WordPress/gutenberg/assets/39980/ad449b17-7eb0-4ce6-b88f-a55358c34301)

![Screenshot 2024-02-08 at 11 21 34](https://github.com/WordPress/gutenberg/assets/39980/3eb2e4fa-5a2d-4fc5-86cd-db6bca4bb579)

**Comment by andrewserong** [comment]
> But the only place where this manifested so far was Storybook, never a production situation, so it's been a low priority issue I never got around to fix. Does it become high priority now?

Thanks for confirming, folks! Yes, it's become a higher priority now that Playground use is becoming more prominent. Since it's a very convenient way for folks to test out WordPress and Gutenberg features, I think that's probably why we're seeing more reports of the issue.

**Comment by jsnajdr** [comment]
I submitted a Floating UI fix here: https://github.com/floating-ui/floating-ui/pull/2785

Let's see what the maintainer says about it. If a new patched version is released, we can upgrade the Gutenberg dependency and that should fix the Playground problem.
