### ISSUE TITLE
Post updated message doesn't use the correct post type name

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#5877]
## Issue Overview
When updating a post type other than Post (for example, a Page), the post updated message states "Post updated" instead of "Page updated".

## Steps to Reproduce (for bugs)
Publish or update a Page using Gutenberg.

## Expected Behavior
The message says "Page updated!".

## Current Behavior
The message at the top of the screen says "Post updated!" instead of using the correct message for the post type.

## Possible Solution
The correct messages are available in PHP via the `post_updated_messages` filter, but they do contain a bit of logic with regard to `$_GET` parameters.

Failing that, a separate set of updated messages needs to be made available on a per post type basis.

**Comment by danielbachhuber** [comment]
Closing in favor of #3315 (earlier version of the same issue).
