### ISSUE TITLE
Tooltips: System font is overridden by custom text font

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#58777]
### Description

Some Tooltips (probably that are directly placed to the canvas) are displayed in global text font instead of the system font.
I found it on the following blocks, but I'm sure there are more
- the placeholder for Groups and the add block "Plus"
- the placeholder for Columns
- Add block "Plus" for File, Media & Content block, Details block…

### Step-by-step reproduction instructions

1. Change globally the text font of the page
2. Insert one of the blocks above
3. Hover over to trigger the tooltips

### Screenshots, screen recording, code snippet

<img width="414" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/830687e6-df4a-4e4c-8959-a94838a39bb1">

<img width="385" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/cb6d71cc-69ca-4536-80cd-b1f0673165bc">

<img width="431" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/aca284aa-4fdc-4c75-b332-b2f99914cf26">

### Environment info

- Custom theme
- WP 6.4.3
- GB 17.6.3

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by riteshvatwani** [comment]
@hanneslsm I have attempted to replicate the issue but have been unsuccessful so far. Could you please provide additional information or a recording so that I can better understand and address the problem?

**Comment by hanneslsm** [comment]
@riteshvatwani Thanks for looking into it!

I've just seen in the release notes that @jasmussen has merged https://github.com/WordPress/gutenberg/pull/59307
@jasmussen This fixes this issue, right?

**Comment by jasmussen** [comment]
Yes, this should ve fixed!
