### ISSUE TITLE
Certain Buttons Unresponsive in Site Editor on Mobile Browsers and Apps

### ISSUE THREAD

**Issue by SiobhyB** [WordPress/gutenberg#58781]
### Description

As reported in https://github.com/Automattic/wp-calypso/issues/87247 by @kelasante, buttons that appear in the top toolbar when editing a template in the site editor are not tappable. Nothing happens when you click on a specific feature like the save or style icon.

<img width="660" alt="Markup 2024-02-06 at 17 39 22" src="https://github.com/Automattic/wp-calypso/assets/74204272/94a69c80-931c-4ed5-b1da-ebc842325900">

Additionally, when you scroll to Patterns, and click to open a pattern, nothing happens.

<img width="820" alt="Markup 2024-02-06 at 17 42 44" src="https://github.com/Automattic/wp-calypso/assets/74204272/e8847e70-63a2-40ef-8c7a-f479a6b2ccda">

### Step-by-step reproduction instructions

1. On a mobile app or mobile browser on a site with an ~FSE~ block theme active, open the Site Editor by clicking the option to update your site's design. 
2. Go to templates 
3. Click on any of the buttons at the top of the page, like save or the block inserter 
4. Similarly, go to Patterns, and click or double-click on a pattern to open it.

### Environment info

This is a new regression that's reproducible with 17.6.3 of the Gutenberg plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by SiobhyB** [comment]
Noting that the buttons become responsive again after changing the z-index for the following selector locally:

https://github.com/WordPress/gutenberg/blob/21f0fc0a813d8b4ad85a3a255e973567c9e68ce7/packages/edit-site/src/components/layout/style.scss#L38-L48

There appear to have been a number of changes related to the site editor which may have contributed.

**Comment by afercia** [comment]
I noticed this regression as well and mentioned in another PR, see https://github.com/WordPress/gutenberg/pull/58740

> Note: the layout suffers from an unrelated bug where some transparent elements overlap the top bar button. As such it's not possible to click these buttons. Use the keyboard to move to them.

I don't think this is related to the Block buttons and not even to the Button component. It's the SIte editor top bar layout that needs some adjustments

**Comment by t-hamano** [comment]
> Additionally, when you scroll to Patterns, and click to open a pattern, nothing happens.

This issue is also mentioned in this comment: https://github.com/WordPress/gutenberg/issues/58044#issuecomment-1925318326

**Comment by getdave** [comment]
I confirmed this Issue is happening. I believe this selector is responsible:


https://github.com/WordPress/gutenberg/blob/f20a23805095d96868cddf8e5f0a72a9692f032a/packages/edit-site/src/components/layout/style.scss#L38-L41

Specifically the `z-index` (which resolved to `2`). If I bump that up to `3` I can click on the buttons but the site logo becomes obscured:

https://github.com/WordPress/gutenberg/assets/444434/09c9daf3-96a9-4a6c-9c99-04a3a331ddba

**Comment by jeryj** [comment]
I have a bugfix ready for review: https://github.com/WordPress/gutenberg/pull/58852
