### ISSUE TITLE
Editor with should adapt to screen with

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#5878]
## Issue Overview
In regular TinyMCE the editor interface covers the screen with. In Gutenberg it covers only a small part in the middle of the screen, with a lot of lost space on both sides on a regular Computer/Notebook screen.
Which results in much more line breaks than in the resulting web page (shown on the same Computer/Notebook) and a loose of clarity, because less text is visible on the screen at once.

Used to classic TinyMCE, this change does not only look terrible, it also feels like a big disadvantage of Gutenberg editor. (For me enough to stay with classic editor!)

## Steps to Reproduce (for bugs)

1. compare Gutenberg and classic editor side by side (2 tabs) on a regular screen.

## Expected Behavior

Gutenberg should use the whole screen with like classic TinyMCE

## Current Behavior

Gutenberg uses only a small part of the screen with

## Possible Solution

Gutenberg should use the whole screen with like classic TinyMCE

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
Whilst adapting the width could be something either a plugin or core could explore later, for now having it set to a width is going to be the way it releases in v1.  It's worth noting that having everything full width also isn't good for readability and usability. This is one area where balancing is important.

**Comment by burnuser** [comment]
If you read the reviews of Gutenberg plugin, you'll find out, that a lot of people complain about the fixed/small editor with. And ignoring all this user voices is not a matter of "balancing", it's simple, yes, ignorance!
But thank you anyway for your quick response. It tells me at least, that using more time for testing of Gutenberg and writing reviews to make it better, ... is a complete waste of time.
