### ISSUE TITLE
Bottom UI Overlaps Last Font Entry in Font Library Modal

### ISSUE THREAD

**Issue by okmttdhr** [WordPress/gutenberg#58799]
### Description

A minor visual bug has been identified within the Font Library modal, where the bottom button bar partially obscures the last font option. This overlap makes it difficult for users to interact with the last font in the list, potentially impacting the user experience by limiting visibility and accessibility.

### Step-by-step reproduction instructions

- Open the Font Library modal from the editor.
- Ensure you have 8-10 fonts.
- Scroll down to the bottom of the font list.
- Observe that the last font item is partially covered by the bottom button bar of the modal.

### Screenshots, screen recording, code snippet

<img width="927" alt="Screenshot 2024-02-08 at 11 45 03" src="https://github.com/WordPress/gutenberg/assets/5287479/96ff154b-e3aa-4909-9aca-a63b0ef46b9a">

### Environment info

Gutenberg >= 17.6

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by matiasbenedetto** [comment]
Thanks for reporting this issue.
I think it may be solved by this in-progress PR: https://github.com/WordPress/gutenberg/pull/58794
