### ISSUE TITLE
Hover Effects for Font Names and Checkboxes in Font Library Modal

### ISSUE THREAD

**Issue by okmttdhr** [WordPress/gutenberg#58800]
## What problem does this address?

The font-variant selection interface currently lacks hover effects for font names and checkboxes. The cursor pointer change is the only indication of interactivity. 
Also, the font selection UI lacks hover effects on the font names, while it already has an effect for the arrow `>`.

https://github.com/WordPress/gutenberg/assets/5287479/66fe6749-0a4f-4ddd-a4fa-0658b750de5f

## What is your proposed solution?

- For font names: A subtle change in the background color or the border of the item to indicate the hover state
- For checkboxes: A border color change or background fill

**Comment by matiasbenedetto** [comment]
@okmttdhr thanks for reporting this!

@jasmussen I'd appreciate your input about if you think this is needed and some mockup in that case.

**Comment by jasmussen** [comment]
There should actually be a hover state as part of the original designs: #45271

**Comment by matiasbenedetto** [comment]
> There should actually be a hover state as part of the original designs: https://github.com/WordPress/gutenberg/issues/45271

Good to know. I moved this issue to to-do.

**Comment by juanfra** [comment]
I was checking this one, and there's a limitation to applying a different text color for the hover state, as Google fonts are displayed as SVGs and loading from w.org (I assume that could be for performance or GDPR-related, correct me if I'm wrong as I don't have full context).

For now, the easiest solution would be to apply only the background color on hover (If I'm not mistaken, we will use `$gray-100`).

**Comment by matiasbenedetto** [comment]
> Google fonts are displayed as SVGs and loading from w.org (I assume that could be for performance or GDPR-related, correct me if I'm wrong as I don't have full context).

That's true, both are valid reasons.
