### ISSUE TITLE
Cover Block: Missing Image Resolution options

### ISSUE THREAD

**Issue by codebymikey** [WordPress/gutenberg#58819]
## What problem does this address?
Some client sites have very large, high resolutions images uploaded, and would be very useful if when using the Cover block, users had the option to specify which resolution to use, similar to how the Media & Text or Image blocks currently work.

This will significantly reduce page load if the appropriate image size is used.

This is issue might also affect other blocks making use of media elements, but the cover block is the only one that's currently relevant at the moment.

## What is your proposed solution?
Implement the [`ImageSizeControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/image-size-control) or [`ResolutionTool`](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/resolution-tool/index.js) component within the block just like the Media & Text or Image block currently do.

**Comment by codebymikey** [comment]
Related issues: #52507 #49020

**Comment by Bladed3d** [comment]
No kidding. Why are simple features still missing in WP after all these years?????
