### ISSUE TITLE
Separate the 'Additional CSS Class' setting

### ISSUE THREAD

**Issue by DannyCooper** [WordPress/gutenberg#5884]
Has it been considered to visually separate the 'Additional CSS Class' setting from the above Panel? By default, it could be mistaken as part of the previous panel.

**Current:**
![image](https://user-images.githubusercontent.com/152804/38089166-6310087a-3356-11e8-912b-c90a57f2e234.png)

**Idea:** 
![image](https://user-images.githubusercontent.com/152804/38089099-2d1adb0a-3356-11e8-9556-a3a2b8c463de.png)

I'm happy to provide a pull request if needed.

Thanks!

**Comment by gziolo** [comment]
There is closed PR which does something similar by grouping such settings. I can bring it back to life and update if we agree to introduce visual changes as proposed.

**Comment by karmatosed** [comment]
I would +1 bringing that back to life @gziolo and adding this in. It feels like a simple improvement but useful one. Thanks for noting this @DannyCooper.

**Comment by mtias** [comment]
It was supposed to be inside an "Advanced Settings" panel, together with "anchor" setting.
