### ISSUE TITLE
Link Control: drafting a page in nav block causes resizing issues

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#58865]
Using 6.5-alpha-57555, I noticed that if I created a drafted page in the navigation block, the link UI suddenly seems to struggle to resize and adds a scrollbar:

https://github.com/WordPress/gutenberg/assets/26996883/431e7a1b-0ec8-4d79-ba3d-dcdf93b2ad88

I'm using WP Playground in case that matters! cc @richtabor

**Comment by annezazu** [comment]
I can replicate with GB nightly for 17.8

**Comment by t-hamano** [comment]
This issue is probably similar to #56190. I plan to issue a PR to resolve the issue as soon as possible.
