### ISSUE TITLE
package.json already contains stone age old obsolete wp-env configuration

### ISSUE THREAD

**Issue by lgersman** [WordPress/gutenberg#58877]
### Description

the monorepo [package.json](https://github.com/WordPress/gutenberg/blob/trunk/package.json#L382C1-L394C3) already contains obsolete wp-env configuration  

```json
"wp-env": {
	"plugin-dir": "gutenberg",
	"plugin-name": "Gutenberg",
	"docker-template": "./bin/docker-compose.override.yml.template",
	"welcome-logo": [
		",⁻⁻⁻·       .                 |",
		"|  ،⁓’.   . |---  ,---. ,---. |---. ,---. ,---. ,---.",
		"|   | |   | |     |---' |   | |   | |---' |     |   |",
		"`---' `---' `---’ `---’ '   ` `---' `---’ `     `---|",
		"                                                `---'"
	],
	"welcome-build-command": "npm run dev"
}
```

git blame told me that these snippet is from 2019. I could not find anymore references to "docker-template" nor "welcome-build-command" in the @wordpress/env command. Seems these config was simply forgotten to be removed. Even the referenced wp-env template file (https://github.com/WordPress/gutenberg/blob/trunk/bin/docker-compose.override.yml.template) is no more in use.

The actual used wp-env configuration is located in file [.wp-env.json](https://github.com/WordPress/gutenberg/blob/trunk/.wp-env.json).

So the [wp-env configuration snippet in root package.json](https://github.com/WordPress/gutenberg/blob/trunk/package.json#L382C1-L394C3) can be removed.

### Step-by-step reproduction instructions

1. removed the [wp-env configuration snippet in root package.json](https://github.com/WordPress/gutenberg/blob/trunk/package.json#L382C1-L394C3)

2. deleted the wp-env configuration template file [`bin/docker-compose.override.yml.template`](https://github.com/WordPress/gutenberg/blob/trunk/bin/docker-compose.override.yml.template) referenced in the [wp-env configuration snippet in root package.json](https://github.com/WordPress/gutenberg/blob/trunk/package.json#L382C1-L394C3)

3. Did a `npm ci`, `npm run build` and finally `npm run env start`. 

WordPress including Gutenberg worked like a charm.

So this code can safely be removed from my opinion.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Good catch! This is from an older version of wp-env.

**Comment by lgersman** [comment]
Yeah, I actually stumbled across the issue while _borrowing_ some configs for my own Gutenberg based project 🤪

Thought "Hmmmm ... I know these settings from many many years ago - this cannot be used anymore." And yes, it was true.

Next time I better do a pull request fixing the issue - costs approximately the same time 🤓
