### ISSUE TITLE
Pattern Dialog: the scrollbar doesn't scroll to the last item

### ISSUE THREAD

**Issue by gigitux** [WordPress/gutenberg#58887]
### Description

When the Pattern Dialog shows the scrollbar, it is impossible to scroll to the last item.

### Step-by-step reproduction instructions

1. Open the post editor.
2. Click on the + icon on the top left.
3. Click on patterns.
4. Click on Explore all patterns.
5. Check that the `Text` is the last item on the left list (pattern categories).
6. Resize the window until the scrollbar is rendered.
7. Try to use the scrollbar.
8. You can't scroll to the `Text` category.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/4463174/225ffe48-9913-401f-b136-67a348a82bcc

### Environment info

- WordPress 6.4.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This issue has been fixed in #56787, so I would like to close this issue. If you enable the latest Gutenberg plugin, you should see that this issue is resolved 👍
