### ISSUE TITLE
Idea: Record screencasts of e2e tests to better communicate UX behaviors

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#5888]
To better communicate what behaviors our end-to-end (e2e) tests cover, it would be neat if we could create screencasts of them in some automated way.

Now that we're using Chrome Puppeteer, this may even be within the realm of possibility. See https://github.com/GoogleChrome/puppeteer/issues/478 for some discussion.

If we can sort the underlying technology of this out, I can see the library of these screencasts living on some standalone website and automagically updated by the Travis build process.

Some related issues that would be nice to cover in this way:

* #6171 "View Post" notice positioned behind admin sidebar on publish

**Comment by karmatosed** [comment]
Whilst this is a great idea, let's move this out of enhancement and into ideas as a project for now. We need to right now focus on features and getting bugs resolved. Absolutely something like this can be something we come back to after 5.0, which is why putting in the ideas project.

**Comment by danielbachhuber** [comment]
Sounds good!
