### ISSUE TITLE
Allow loading fonts directly from Google (for utilizing Cloudflare Fonts)

### ISSUE THREAD

**Issue by asafm7** [WordPress/gutenberg#58883]
I've read about a Font Library.

I haven't seen it yet, so I assume it is a WordPress 6.5 feature?

I also assume it would be similar to the "Manage Theme Fonts" feature of the "Create Block Theme" plugin?

If so, I assume fonts will be hosted locally.

I'm familiar with the legal benefits, but a new Cloudflare feature might change things:

https://developers.cloudflare.com/speed/optimization/content/fonts/

It can also possibly boost performance.

(Maybe it is also relevant for Cloudflare's APO which is supposed to optimize fonts similarly)

Will it be possible for the Font Library to have a toggle for loading Google Fonts directly from Google, so Cloudflare Fonts could be utilized?

**Comment by matiasbenedetto** [comment]
Hi :wave: 

> If so, I assume fonts will be hosted locally.

Yep, that's the default behavior.

> Will it be possible for the Font Library to have a toggle for loading Google Fonts directly from Google, so Cloudflare Fonts could be utilized?

Yes, that's the idea being discussed here: https://github.com/WordPress/gutenberg/issues/58229 you are welcome to add more ideas/proposals.

**Comment by asafm7** [comment]
Perfect 👌

**Comment by annezazu** [comment]
Closing this out :) Thanks for the excitement around this feature coming to 6.5!
