### ISSUE TITLE
Tag cloud: if you change size unit you can't reselect PT

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#58885]
### Description

By default, the size option in the tag cloud block uses PT as a unit. But if you change the unit and want to change it back to PT, then PT is not available.

### Step-by-step reproduction instructions

Add a Tag cloud block.
In the settings panel, in the options "smallest size" and "largest size", change the unit.
Now open the unit option again and try to select PT.

### Environment info

WordPress 6.4.3. with and without Gutenberg
6.5-alpha-56966-src with and without Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by akasunil** [comment]
Spacer block also have the same issue. It occur due to default value with unit which isn't available.

**Comment by carolinan** [comment]
Looking at [edit.js](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/tag-cloud/edit.js#L52), the units for the min and max font size will use the spacing units, or, if the theme does not support spacing units, an array of hard coded units.
Neither of these include PT.

I am no sure why the units can not always be provided as a constant that is unique for this block, and include the PT?

**Comment by akasunil** [comment]
I have searched through the block library, looks like we don't use 'Pt' unit much, It not included over [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/unit-control/utils.ts#L239) too.

Also, Issue here is default unit we defined in attributes for min and max font size. Consider if we add PT unit and theme doesn't support PT unit, then same issue will happen again. 

I have used unit control function to filter that if default unit is not supported by theme, it will return first available unit by default.

**Comment by carolinan** [comment]
The PT unit has been used as the [default unit for the tag cloud](https://core.trac.wordpress.org/ticket/4129) for 17 years, and it is a valid CSS unit. I'm not sure what this means " if... theme doesn't support PT unit": are themes even able to filter this unit?

**Comment by carolinan** [comment]
Looking at the theme.json schema, the unit setting is only available for the spacing controls:
https://github.com/WordPress/gutenberg/blob/trunk/schemas/json/theme.json#L391

**Comment by akasunil** [comment]
> Looking at the theme.json schema, the unit setting is only available for the spacing controls: https://github.com/WordPress/gutenberg/blob/trunk/schemas/json/theme.json#L391

As of now, the available units for tag clouds are spacing units. Since spacing units can be altered by theme, [this](https://github.com/WordPress/gutenberg/pull/59122/files#diff-52194085c13584d0f86aa62bf9b512f41abe5842b30c366e06b5c8f81c24015aR80-R85)  code will ensure that if the pt unit is disallowed by theme, the first available unit will be used as the default unit.

Another solution i can think of is we can remove use of `spacing units` setting here, and add defaults list of units including `pt` unit. That could resolve the issue.
