### ISSUE TITLE
Spacer block no longer inherits orientation

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#58894]
### Description

When a spacer block is inserted in a navigation block which has a default horizontal orientation, the spacer block is oriented vertically.

### Step-by-step reproduction instructions

1. In a tempalte
2. Insert a navigation block
3. Add a link or two
4. Add a spacer block
5. **Notice the spacer spaces only up and down**

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/107534/27124018-bec2-4a80-9e1d-2f93b80d6779

### Environment info

Gutenberg trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by draganescu** [comment]
@tellthemachines in #49322 updated this block to inherit the orientation from the parent's layout. Something must have happened in the mean time.

**Comment by tellthemachines** [comment]
I can't reproduce this on Gutenberg trunk, have you tried in on a clean install?

**Comment by t-hamano** [comment]
@tellthemachines 

If you are testing with TT4, you may not be able to reproduce this issue as the layout is already defined in the template part of the theme.

![image](https://github.com/WordPress/gutenberg/assets/54422211/d23c70e1-a679-4015-a3b5-020c8b044a17)

I think you can reproduce this problem by inserting the navigation somewhere else or creating a new navigation.

**Comment by tellthemachines** [comment]
Oooh I see thanks! I can now reproduce this but it's not only in Gutenberg trunk, I can also see it in WP 6.4.3. Not sure if this can be classed as a regression but I agree it would be good to fix for this release 😅

**Comment by tellthemachines** [comment]
I see what the problem is: we're checking the parent layout `type` but not `default.type`. I can do a quick PR to fix that

**Comment by tellthemachines** [comment]
I suspect now that this _never_ worked correctly and we somehow didn't notice until now 🤔

**Comment by youknowriad** [comment]
For clarity, I removed the label because it's meant for PRs not issues.

**Comment by draganescu** [comment]
@youknowriad oops to eager me!
