### ISSUE TITLE
Inserter in column adds blocks to wrong column or after columns block

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#5889]
## Issue Overview
The inserter in columns is pretty broken. Depending on what you do, it may insert blocks into the wrong column, or it may insert blocks after the columns block.

I thought for sure that this would already have been reported by now, but I can not find any existing open issues about it, so forgive me if it has already been reported.

## Steps to Reproduce (for bugs)
1. Create a new post.
2. Insert a columns block.
3. Try to use the block inserter in the right column to insert a block.
4. Notice that it gets inserted into the left column.

OR

1. Create a new post.
2. Insert a columns block.
3. Change the columns block to have 3 columns.
4. Try to use the block inserter in any of the columns to insert a block.
4. Notice that it gets inserted below the columns block.

## Expected Behavior
Using the inserter in a column should insert a block into that column.

## Current Behavior
In some cases, trying to insert a block into a column will cause the block to be inserted in the wrong column, or after the columns block.

## Screenshots / Video
https://i.imgur.com/X28b5Ew.mp4
https://i.imgur.com/P50JejZ.mp4

**Comment by GlennMartin1** [comment]
Each release I check this functionality.

The flaws in nesting and columns is what prevents me from transitioning my sites to Gutenberg now.

When this works dependably, I'll start transitioning my 7 sites. 

I haven't posted bug reports about this because they are so obvious, and it's still called "experimental."

**Comment by karmatosed** [comment]
This is already reported here: https://github.com/WordPress/gutenberg/issues/5772. Columns is experimental and being worked on, it's very much just a version one of the idea. Thanks for testing it out.
