### ISSUE TITLE
Should "Border & Shadow" panel label include "border" if border is not supported?

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#58907]
### Description

Not all themes support borders, so it can be confusing when a panel labeled Border and Shadow has no border controls.
_I'm not sure if this is a bug, it felt unexpected to me, but I understand that consistency on the panel labels is also important._

### Step-by-step reproduction instructions

On WordPress 6.5 alpha:
Activate a classic theme like Twenty Sixteen
In the block editor, add an **image** block.
Open the block settings panel, locate the "Border and Shadow" panel.
Now add a button:
Open the block settings panel, locate the "Border and Shadow" panel.

Compare the two experiences.

### Screenshots, screen recording, code snippet

<img width="565" alt="Border and shadow panel without border controls" src="https://github.com/WordPress/gutenberg/assets/7422055/b196066d-2d90-4820-b4d2-c3f70eac8279">

### Environment info

WordPress 6.5-alpha-57580

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
cc @WordPress/gutenberg-design for thoughts here. I agree this is confusing!

**Comment by colorful-tones** [comment]
I believe that PR #58776 will address this issue, but waiting for confirmation ([see comment](https://github.com/WordPress/gutenberg/pull/58766#issuecomment-1939643402)).

**Comment by jameskoster** [comment]
I agree the scenario described is confusing. 

Adding logic to adjust panel titles doesn't seem great though... I guess this raises the question about whether Border and Shadow (Effects) should be separate panels, but that's another conversation.

**Comment by jasmussen** [comment]
> Adding logic to adjust panel titles doesn't seem great though... I guess this raises the question about whether Border and Shadow (Effects) should be separate panels, but that's another conversation.

Border & shadow feel connected to me, enough that they belong together. What's your main concern with adjusting panel titles? I feel that's the best path forward.

**Comment by t-hamano** [comment]
How about changing it to a more abstract title like "Outline" or "Frame" or "Contour" like the other panels?

**Comment by jameskoster** [comment]
> What's your main concern with adjusting panel titles?

Mostly the resulting inconsistencies. I feel panel headings should be immutable for immediate recognition across contexts. Not to mention documentation. Making one heading dynamic sets a precedent that they can all be dynamic.

I don't want to derail the conversation, but I'd lean towards something like the Figma approach; a dedicated panel for border, then something more abstract like "Effects" for lesser-used features like shadows and filters.

**Comment by jasmussen** [comment]
I hear you, to me it's no different than a panel being contextual to the block being selected. You could think of it as three panels if you like, border, border & shadow, and shadow. I know that doesn't address your concern. But the benefit of having a single panel, given the behavior and current design of panels that we have, IMO vastly outweigh the benefits of separate panels. If we had the same level of density as Figma does, things would be different. And they can be in the future, too, if we explore improvements to the inspector and panels, so I'd earmark that as something to consider. But until we have more density, it would just be more visual noise, more tab-stops, and dubious user benefit.

**Comment by SaxonF** [comment]
>  I guess this raises the question about whether Border and Shadow (Effects) should be separate panels, but that's another conversation.

I would +1 this

**Comment by madhusudhand** [comment]
> I hear you, to me it's no different than a panel being contextual to the block being selected. You could think of it as three panels if you like, border, border & shadow, and shadow. I know that doesn't address your concern. But the benefit of having a single panel, given the behavior and current design of panels that we have, IMO vastly outweigh the benefits of separate panels.

Created #59358 where it sets the panel label based on the controls enabled. I guess we can move forward with this approach for 6.5 and keep this issue open for discussion on other ideas.
