### ISSUE TITLE
Pattern: show "my patterns" after importing a pattern to show where it's been imported

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#58901]
Using GB nightly (Version 17.8.20240208), I noticed that after importing a pattern, it seems to refresh and dump me in the overall pattern view rather than showing me/placing me either in the original spot I was in or in "my patterns" so I can see where the pattern is:

https://github.com/WordPress/gutenberg/assets/26996883/1695e444-4413-4746-81b2-a3c5a65874e0

I'd expect to be shown "my patterns" or to see where it was uploaded. If we can't do that, I think we should show a "View pattern" in the snackbar notice similar to this https://github.com/WordPress/gutenberg/pull/52693 that takes you to "My patterns".

**Comment by colorful-tones** [comment]
Moving this to In Progress on the [WordPress 6.5 Editor Tasks board](https://github.com/orgs/WordPress/projects/148/views/1), since there is a PR in progress.
