### ISSUE TITLE
Gallery not centered in many themes due to margin/padding on UL

### ISSUE THREAD

**Issue by dreamwhisper** [WordPress/gutenberg#5890]
## Issue Overview

ULs were used for gallery markup in https://github.com/WordPress/gutenberg/pull/3441. However, many themes style lists within the content and add padding or margin to the left side. Thus, galleries appear shifted to the side/uncentered.

## Steps to Reproduce (for bugs)

1. Insert a gallery block
2. Activate a theme that adds margin and/or padding to content ULs (Twenty Fourteen is an example with alignnone selected for the block.)
3. Note galleries will be shifted to the side.

![gallery](https://user-images.githubusercontent.com/1271053/38111233-346d5dea-336c-11e8-8cac-c05501fe9453.png)

## Expected Behavior

Galleries would not be shifted by CSS intended for text-based lists.

## Current Behavior

Margin and/or padding is adopted from text-based list styling and galleries are unintentionally shifted.

## Possible Solution

Reset left/right margin/padding for:

```css
.wp-block-gallery,
.wp-block-gallery.aligncenter,
.wp-block-gallery.alignleft,
.wp-block-gallery.alignnone,
.wp-block-gallery.alignright 
```
## Related Issues and/or PRs

https://github.com/WordPress/gutenberg/pull/3441

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ErikXXon** [comment]
I also get this problem in my theme.
