### ISSUE TITLE
It is unclear how to create a new block.

### ISSUE THREAD

**Issue by jamieschmid** [WordPress/gutenberg#5891]
Version: 2.5.0

## Issue Overview
It is unclear how to create a new block. Currently, the only way I could figure out was to hit return in the existing block, which creates the empty block. I suggest adding additional, labeled controls in both the menu, and the current block, which clearly state "Add New Block".

## Steps to Reproduce (for bugs)
1. Create a new page
2. Start typing in the default block
3. After typing, click outside of the block
4. No controls exist for adding a new block

## Expected Behavior
I spent quite a lot of time looking for a menu control to add a block, before I figured this out. My first instinct was to click the vertical ... which pulls up "More Options" - not there. Then, I went into the pullout menu under the Block tab - not there.

<img width="1090" alt="no-add-block-button" src="https://user-images.githubusercontent.com/6207905/38114406-13139484-335d-11e8-82d1-2200316956a3.png">

## Current Behavior
From what I could find, the only way to create a new block is to hit 'return' from within your current block. I spent a lot of time looking for another way and was unable to find one.

## Possible Solution
I suggest a "+ New Block" button inside the pullout menu Block tab, like so:
![recommendation_add-block](https://user-images.githubusercontent.com/6207905/38114750-6751e59a-335e-11e8-88fe-c980f58871ff.jpg)

This will add a new block directly below the block that is selected.

I understand reasoning behind hitting return to create a new block: if a new block is automatically created immediately after starting one, an empty block will be published if the user never types in it. We want to avoid that. However, using return, and only return, to create the new block is not sufficient. It also presents potentially prohibitive accessibility issues.

**Comment by danielbachhuber** [comment]
Thanks for the feedback, @jamieschmid !

For reference, there's also a "Add Block" button at the top of the view:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/36432/38138055-6e53f656-33dd-11e8-9f44-26b7bf264f99.png">

**Comment by SuperGeniusZeb** [comment]
Perhaps this is a sign that a label should be added to the "Add block" button on desktop? Or at least perhaps a tooltip or something pointing to it when you use the Gutenberg editor for the first time.

Additionally, the sibling inserter is kind of hard to discover if you move your mouse around a lot. You have to hover over an area slowly for it to appear. I kind of miss the old sibling inserter with the icon... it seemed a lot easier to use.

As for putting a button to add a new block in the block inspector, I think that is a bad idea. The block inspector is intended to show options for the currently-focused block, and I do not think an add block button belongs there. Rather, I think the sibling inserter should be improved and perhaps the "Add block" button in the top left be pointed out to new users.

**Comment by karmatosed** [comment]
As there is: https://github.com/WordPress/gutenberg/issues/3670, which explores the experience and tips, for now I am going to close this issue. Discoverability absolutely is something we can work on and will.
