### ISSUE TITLE
Search block: Font size adjusts the size of the button, but not the icon.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#58925]
### Description

When you set the search block to use the icon on the button, the font size option does not increase the size of the icon.

### Step-by-step reproduction instructions

Add a search block.
In the block toolbar, select "Use button with icon".
In the settings panel, under typography, change the font size to something large.

### Screenshots, screen recording, code snippet

<img width="1377" alt="Search block where the text is larger than the icon in the button." src="https://github.com/WordPress/gutenberg/assets/7422055/ccb2a9e6-d433-4edc-948a-15142fde8710">

### Environment info

WordPress 6.4.3.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
Not sure about this approach:

- https://github.com/WordPress/gutenberg/pull/59159
