### ISSUE TITLE
Code Editor does not work when the WordPress installation is located in a separate folder than root

### ISSUE THREAD

**Issue by paulwilde** [WordPress/gutenberg#5892]
For all my WordPress sites I use a git submodule for the WordPress installation, and as such its not located in the root of the site, but within a `/wp/` subdirectory. WordPress then knows that its the root due to `WP_DIR` being set as `/wp`. Whilst not common, this isn't a rare setup, as there is some projects out there which use a similar type of pattern such as [Bedrock](https://roots.io/bedrock/) , although they seem to use an npm package instead.

The error occurs due to the lazy-loading of CodeMirror. The path to the file is hard-coded as such:
```script.src = `/wp-admin/load-scripts.php?load=${ handles.join( ',' ) }`;```

<img width="843" alt="screen shot 2018-03-29 at 23 36 30" src="https://user-images.githubusercontent.com/704594/38116880-096077a2-33aa-11e8-97e5-f6ec1827bf4d.png">

**Comment by greatislander** [comment]
WordPress supports this, so Gutenberg should.

**Comment by danielbachhuber** [comment]
There are a couple solutions I can think of:

1. Introduce some `window.wp.adminUrl` JavaScript variable to provide an always accurate URL reference.
2. Introduce a formal JavaScript API for lazy-loading concatenated scripts.

My preference would be the latter, as that would then allow us to abstract away from `load-scripts.php` at a future data if we needed to.

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/pull/6777 fixed this.
