### ISSUE TITLE
DataViews: My Patterns page pagination is unusable on scrolled view due to the container z-index

### ISSUE THREAD

**Issue by miksansegundo** [WordPress/gutenberg#58929]
### Description

"My patterns" pagination is unusable when the view is scrolled down with patterns exactly behind the pagination links. When you click on the pagination, the detail of the pattern behind it opens instead. 

### Step-by-step reproduction instructions

- Open Appearance > Editor and select Patterns.
- In My Patterns, create or import patterns until you see the pagination appear at the bottom
- Scroll the view in the middle, leaving the pagination right on top of a pattern
- Click on the pagination 
- Instead of the pagination action, expect to see how the pattern that is behind the pagination opens

<img width="366" alt="Screenshot 2567-02-12 at 17 57 26" src="https://github.com/WordPress/gutenberg/assets/1881481/a3eef858-f094-4b18-be7b-69b68e797088">

### Screenshots, screen recording, code snippet

![Screen Capture on 2567-02-12 at 18-33-09](https://github.com/WordPress/gutenberg/assets/1881481/ac6be5fe-633c-4fa4-bb95-51d3beea33ea)

### Environment info

Tested on Gutenberg 17.6.5 and 17.7.0-rc.1 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Thanks so much for reporting! Great find. I can replicate this using 6.5-alpha-57584:

https://github.com/WordPress/gutenberg/assets/26996883/1abe2852-5ab5-4d4c-854c-0295d91dd5c2

@ntsekouras in case you can dig in.
