### ISSUE TITLE
Improve Cover Block empty state

### ISSUE THREAD

**Issue by pitamdey** [WordPress/gutenberg#58937]
## What problem does this address?
when we add a cover block and don't select anything and then see the preview in front-end it shows a blank cover
Recording : https://www.loom.com/share/9ed547c001a04009b1b3e4a7791c7616?sid=d3969784-0f5a-4756-9c49-e6044c192a87

## What is your proposed solution?
I think we should not show anything if no cover photo or color is selected

**Comment by akasunil** [comment]
Probably duplicate of https://github.com/WordPress/gutenberg/issues/10854
@annezazu we can close this issue.

**Comment by annezazu** [comment]
Agreed! Thanks for flagging.
