### ISSUE TITLE
Site Editor: Unintended title display and content width

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#58956]
Most canvases in the site editor seem to be experiencing the following issue.

- The entity title is displayed
- The content width is narrow

When I searched for the problematic commit using `git bisect`, #58935 seems to be affected. #58935 has a backport label, so it may need to be fixed soon.

### Actual

![image](https://github.com/WordPress/gutenberg/assets/54422211/39d026df-f3cc-4615-9c20-deffa2c302e2)

### Expected

![image](https://github.com/WordPress/gutenberg/assets/54422211/929ab3dd-61e4-4f36-8148-51488fa1e4ec)

**Comment by glendaviesnz** [comment]
@youknowriad the `post-only` mode is being used to apply some [post specific layout](https://github.com/WordPress/gutenberg/pull/57700/files#r1463947816), eg the post title and some of the global styles layout widths, eg. [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/editor-canvas/index.js#L166), so applying `post-only` to all entities is what is causing this issue.

**Comment by youknowriad** [comment]
Looking into this.
