### ISSUE TITLE
`wp.blocks.getBlockTypes()` does not return core blocks making it impossible to create a whitelist of blocks

### ISSUE THREAD

**Issue by paulwilde** [WordPress/gutenberg#5895]
The directions as described in the documentation [here](https://wordpress.org/gutenberg/handbook/extensibility/#using-a-whitelist) for whitelisting visible blocks does not work, as it only returns registered custom blocks.

**Comment by gziolo** [comment]
It is a known issue :( It duplicates #4848.

The plan is to resolve it as described in #2751, by moving the process of registration of blocks to the server. The progress can be observed in a more targeted PR: #5802.
