### ISSUE TITLE
Data views: Table headers are no longer sticky

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#58977]
Most likely due to the addition of wrappers like `.dataviews-wrapper` and `.dataviews-view-table-wrapper`, table column headers are no longer sticking to the top of the container as you scroll. 

Given the additional nesting we may need to use javascript to handle this.

**Comment by jameskoster** [comment]
Adding Bug label since the current code is effectively broken. If we can't restore this functionality for 6.5 then we should at least remove the broken code.

**Comment by annezazu** [comment]
@ntsekouras tagging you on this for a 6.5 fix!

**Comment by ntsekouras** [comment]
The style responsible for this comes from here: https://github.com/WordPress/gutenberg/pull/57930

and specifically from:
```
.dataviews-view-table-wrapper {
	overflow-x: auto;
}
```

I've tried a few things to make it work, but without success so far. I'll keep looking a bit more, but some folks with more css expertize could be more helpful.

**Comment by jameskoster** [comment]
I have a potential fix, will open a PR.
