### ISSUE TITLE
Widgets blocks no where to be found

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#58984]
### Description

It appears that all of the blocks under the Widgets category are not accessible.

### Step-by-step reproduction instructions

1. Go to post editor.
2. Try adding Social Icons block, via / command or + inserter.
3. Discover entire set of Widgets blocks are no where to be found.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/486261/7e4db8b9-08df-409a-9ea0-39fbe8f3b089

### Environment info

WordPress 6.5-beta1 (with or without Gutenberg active)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I have not been able to reproduce it on either TT1 or TT4, and regardless of whether the Gutenberg plugin is enabled or not. What theme/plugin are you using?

**Comment by bgardner** [comment]
My Powder theme, but also had similar results with TT4. Are you testing with 6.5 Beta 1?

**Comment by t-hamano** [comment]
> Are you testing with 6.5 Beta 1?

Yes. I couldn't reproduce it in my environment 🤔

https://github.com/WordPress/gutenberg/assets/54422211/c59facb5-99c0-409d-9328-11111d9b05fb

**Comment by bgardner** [comment]
My environment is [Local](https://localwp.com/), and you can see similar results with TT4 active:


https://github.com/WordPress/gutenberg/assets/486261/6ddefff4-23b6-413b-8625-da5d3762df78

**Comment by bgardner** [comment]
Hm, I just tried on my live WP site at https://briangardner.com/ and I can see the Widgets blocks (including Social Icons).

**Comment by bgardner** [comment]
I am going to close this issue. My guess is that there's something isolated to my sandbox site, as another site on Local is working as expected too.
