### ISSUE TITLE
Bug Translation post-visibility/utils.js

### ISSUE THREAD

**Issue by RickorDD** [WordPress/gutenberg#5898]
this box will not be translated

![image](https://user-images.githubusercontent.com/6922544/38130457-7a7cfb14-3403-11e8-829d-a29dc8d76dc4.png)

in
https://github.com/WordPress/gutenberg/blob/master/editor/components/post-visibility/utils.js

Strings are green
![image](https://user-images.githubusercontent.com/6922544/38130564-e5b855e0-3403-11e8-9ff9-e850d1b4057c.png)

**Comment by aduth** [comment]
I believe issue here is that strings are being run through `__` at time of load, not when actually shown, and because the locale data is not set until after the editor script is loaded, they are not correctly translated. May be a fix to set locale data _before_ script.

**Comment by aduth** [comment]
Oh, seeing now that #5910 is meaning to fix this. It's not as easy as I first suspected, because we do already set locale data before, but before `edit-post` (and `edit-post` depends on `editor`, where the strings are actually being localized).
