### ISSUE TITLE
Editor Limited Width Issue and Possible Fix

### ISSUE THREAD

**Issue by FGP-Radio** [WordPress/gutenberg#58986]
### Description

So, for some reason, my Gutenberg editor will not go to full width (please see the attached screenshot). I believe this is a bug because it started out of nowhere and I can't get it to stop, and this is actually the second site that I have had this error on.

Possible fix:
After a bit of digging in Inspector, I found a couple lines of css which seem to be the issue. I have included two screenshots. One from before removing the below style tags and one after.
The issue lines are the "max-width: 620px;" in both of the following style tags.

They are listed below:
<style>
					.editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
						max-width: 620px;
						margin-left: auto !important;
						margin-right: auto !important;
					}
					.editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper > .alignwide  {
						max-width: 1280px;
					}
					.editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper > .alignfull {
						max-width: none;
					}
				</style>
<style>
					.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
						max-width: 620px;
						margin-left: auto !important;
						margin-right: auto !important;
					}
					.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > .alignwide  {
						max-width: 1280px;
					}
					.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > .alignfull {
						max-width: none;
					}
				</style>

### Step-by-step reproduction instructions

Not sure, just randomly started.

### Screenshots, screen recording, code snippet

![before](https://github.com/WordPress/gutenberg/assets/103152959/e27748f8-8ee3-4965-9392-250c66505f03)
![after](https://github.com/WordPress/gutenberg/assets/103152959/5288c8d9-cdc9-4ebd-aeef-42f9f043e083)

### Environment info

- Wordpress: 6.4.3
- Browser: Chrome 121.0.6167.161
- Theme: Twenty Twenty-Four
- Computer: Windows 10 Pro

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by chthonic-ds** [comment]
Looks like this has been addressed by https://github.com/WordPress/gutenberg/pull/58962

**Comment by talldan** [comment]
I'll close this as it seems to have been fixed.
