### ISSUE TITLE
Installing Google font error - No font faces were installed. 

### ISSUE THREAD

**Issue by kafleg** [WordPress/gutenberg#58997]
### Description

While checking WordPress 6.5 Beta 1 and testing Google font installation, fonts are not installed. 

![image](https://github.com/WordPress/gutenberg/assets/13062231/ed386e18-6ad6-4498-abd2-0a52c6b67e84)

Finding the issue and discussion can be found here in Slack, https://wordpress.slack.com/archives/C02RQBWTW/p1707883378714549

**Solution Found:**
Change the number on [these two lines](https://github.com/costdev/wordpress-develop/blob/8ec4d9dfc7e2043485d83d4af9e505ec1cc21470/src/wp-includes/fonts/class-wp-font-utils.php#L234-L235) from _80100_ to _80112_ and see if you can install the fonts.

This worked for me. 

### Step-by-step reproduction instructions

1. Install WordPress 6.5 Beta 1
2. Go to Appearance > Editor 
3. Select a heading or paragraph 
4. Click on Styles and then Typography 
5. click on manage fonts icons
6. Click on Install Fonts and select a font to install 
(Now you can see the issue)

### Screenshots, screen recording, code snippet

Recording: https://i.rankmath.com/v/27NfsL 

https://github.com/WordPress/gutenberg/assets/13062231/6653961c-b0b4-4231-9941-69ed280c2262

### Environment info

**Environment details on my end:**

- WP: 6.5 Beta 1 (Updated via CLI)
- Local Server: Laragon
- PHP: 8.1
- Browser: Edge
- OS: Windows
- Theme: Twenty-Twenty Four
- Fonts tested: ABeeZee
- Plugins: None

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by costdev** [comment]
References:
- [PHP-src: finfo returns wrong mime type for woff/woff2 files](https://github.com/php/php-src/issues/8805)
- [PHP 8.1.12 changelog](https://www.php.net/ChangeLog-8.php#8.1.12)
- [Tests: Adjust the expected mime type for WOFF fonts on PHP 8.1.12+.](https://github.com/WordPress/wordpress-develop/commit/5eefddf4afcd738abd52fe5b7ebbe163412532ad)

**Comment by huzaifaalmesbah** [comment]
## Reproduction Report
First attempt i got this error but second attempt installed successfully.
### Environment
- WordPress: 6.5-beta1-57631
- PHP: 8.3.2
- Server: nginx/1.25.3
- Database: mysqli (Server: 11.2.2-MariaDB / Client: mysqlnd 8.3.2)
- Browser: Chrome 121.0.0.0
- OS: macOS
- Theme: Twenty Twenty-Four 1.0
- MU Plugins: None activated
- Plugins:
  * Test Reports 
  
<img width="927" alt="Screenshot 2024-02-14 at 12 46 32 PM" src="https://github.com/WordPress/gutenberg/assets/63150399/633ebfab-bea2-433a-a3d9-2fed48dfe027">

**Comment by costdev** [comment]
@huzaifaalmesbah Just to clarify: The error you received is due to filesystem permissions that must be handled on the system.

The problem reported in this issue is that the `woff/woff2` font format has a different MIME type from PHP 8.1.12 onwards. The Font Library's code that handles this change checks for `>= PHP 8.1.0`, rather than `>= PHP 8.1.12`, causing a failed MIME type check for PHP 8.1.0 through 8.1.11.

To verify this issue, a PHP version between 8.1.0 and 8.1.11 must be running on the server during the test.

**Comment by hellofromtonya** [comment]
Hello @huzaifaalmesbah 👋 The issue you found is being tracked in this [Core Trac ticket](https://core.trac.wordpress.org/ticket/60528). I'm not seeing a Gutenberg issue opened for it yet though. Hey  @matiasbenedetto is there a GB issue for it?

**Comment by matiasbenedetto** [comment]
> Hello @huzaifaalmesbah 👋 The issue you found is being tracked in this [Core Trac ticket](https://core.trac.wordpress.org/ticket/60528). I'm not seeing a Gutenberg issue opened for it yet though. Hey @matiasbenedetto is there a GB issue for it?

Hi @hellofromtonya this is a different issue than the reported in the [trac ticket you linked](https://core.trac.wordpress.org/ticket/60528). 


We need to create a track ticket for the fix added by @costdev in https://github.com/WordPress/gutenberg/pull/59015 to move that change to the core repo.

**Comment by hellofromtonya** [comment]
>We need to create a track ticket for the fix added by @costdev in https://github.com/WordPress/gutenberg/pull/59015 to move that change to the core repo.

@matiasbenedetto Ticket already exists https://core.trac.wordpress.org/ticket/60536 in Core. @costdev and I will get the fix sync'd back into Core.

>Hi @hellofromtonya this is a different issue than the reported in the [trac ticket you linked](https://core.trac.wordpress.org/ticket/60528).

@matiasbenedetto the issue @huzaifaalmesbah [showed in the test report above](https://github.com/WordPress/gutenberg/issues/58997#issuecomment-1943178496) is the same one you reported in [Trac 60528](https://core.trac.wordpress.org/ticket/60528). Will that issue be fixed here in Gutenberg first? If yes, is there already a GB issue opened for it?

**Comment by matiasbenedetto** [comment]
> @matiasbenedetto the issue @huzaifaalmesbah https://github.com/WordPress/gutenberg/issues/58997#issuecomment-1943178496 is the same one you reported in [Trac 60528](https://core.trac.wordpress.org/ticket/60528). Will that issue be fixed here in Gutenberg first? If yes, is there already a GB issue opened for it?

Sorry @hellofromtonya, I thought that you were referring to the original issue. I think there was no ticket for that in Gutenberg I created one ( https://github.com/WordPress/gutenberg/issues/59023 ) referencing @huzaifaalmesbah comment and adding the[ trac ticket link](https://core.trac.wordpress.org/ticket/60528)

**Comment by hellofromtonya** [comment]
Fix synch'd into Core with https://core.trac.wordpress.org/changeset/57632.
