### ISSUE TITLE
Query loop: Enhanced pagination is displaying the pagination numbers incorrectly

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#58994]
### Description

Enhanced pagination is missing spaces between numbers, or is perhaps displaying one too many numbers.

When the query block has "Force page reload" disabled, the numbers in the query pagination block do not always display correctly.

First page:
1 2 3 … 32

Page 2
Previous Page 1 2 3 4 … 32 Next Page

Page 5:
Here you can see that there is a missing space between 2 and 3.
Previous Page 1 … 23 4 5 6 7 … Next Page

It looks like something breaks here on page 5, because if I select the **previous page** link now, page 4 pagination displays like this, with "22" instead of "2". 
Previous Page 1 22 3 4 5 6 … Next Page

And here is another example from page 12:
Previous Page 1 … 210 11 12 13 14 … Next Page
If I refresh the page, the faulty number 2 corrects itself:
Previous Page 1 … 10 11 12 13 14 … 32 Next Page

### Step-by-step reproduction instructions

Make sure your WordPress installation has enough posts to test the pagination.
In the block editor, add a new query loop block. Select the "Title & excerpt" variation from the placeholder.
In the settings panel, toggle off Force page reload.
Save and view the post on the front of the website.

Navigate forwards at last 5-6 pages, then back.

### Screenshots, screen recording, code snippet

Without force page reload:

<img width="840" alt="Query pagination where there is a missing space between number 2 and 3." src="https://github.com/WordPress/gutenberg/assets/7422055/fb35816d-dd68-4256-a901-f1b23b4336f6">

And now with force page reload enabled:
<img width="411" alt="query-pagination-2" src="https://github.com/WordPress/gutenberg/assets/7422055/7fa0de9e-0366-4c4a-a98d-f63e159df6c0">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Does this occur with 6.5? Want to understand if it's a regression of some kind and whether to add it to the board.

**Comment by carolinan** [comment]
It is not a regression, i was testing on 6.4.3. It seems to have been solved in 6.5.

**Comment by annezazu** [comment]
Music to my ears :D
