### ISSUE TITLE
Artificact file name collisions in end2end-tests workflow.

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#58995]
### Description

Each of the runs in the E2E workflow use the same file names for uploading artifacts:

* failures-artifacts
* flaky-tests-report

In the event multiple runs in the workflow fail, this results in errors on the GitHub action:

> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

### Step-by-step reproduction instructions

1. Go to https://github.com/WordPress/gutenberg/actions/runs/7896354080/job/21550242344
2. View the Playwright 6 log
3. The failed tests will show the error above.

### Screenshots, screen recording, code snippet

Screenshot in case the logs go missing.

![Screen Shot 2024-02-14 at 4 08 03 pm](https://github.com/WordPress/gutenberg/assets/519727/95f7c486-a76c-4caf-b5b4-d547a0c45fd3)

### Environment info

GitHub, Gutenberg Trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
We can probably use the pattern suggested here - https://github.com/actions/upload-artifact/issues/478.
