### ISSUE TITLE
Site Editor / Twenty Twenty-Four: Rich text gets black border

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#58992]
Update: This issue is specific to the TT4 theme and appears to be related to a core ticket aimed at improving focus outlines.

https://core.trac.wordpress.org/ticket/60334

### Description

For example, in the case of a table block, when you focus on a cell, a black border will appear.

![image](https://github.com/WordPress/gutenberg/assets/54422211/6665b583-38df-4559-a1a1-01144aa8ed69)

The paragraph block displays both a black border and a blue border.

![image](https://github.com/WordPress/gutenberg/assets/54422211/30e1e1f3-97ae-47c8-8e2a-f4e65b00173e)

This issue appears to occur in the site editor and not the post editor.

### Step-by-step reproduction instructions

- Open the Site editor.
- Insert a table block or a paragraph block.
- Click a cell in a table block or a paragraph block.

### Environment info

- WordPress Version: WordPress 6.5-beta1-57631
- Gutenberg Version: 17.7.0-rc.1 (Can be reproduced even if disabled)
- OS: Windows 11
- Browser: Chrome 121.0.6167.162, Firefox 122.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
The outline style of the `.wp-site-blocks *:focus` selector appears to override the rich text `outline: none`.

![image](https://github.com/WordPress/gutenberg/assets/54422211/ee8c288e-f476-4860-96a6-1ad28f0f0ae3)

**Comment by carolinan** [comment]
I did not realise wp-site-blocks was also in the Site editor. What would be a better selector?

**Comment by t-hamano** [comment]
@carolinan It might be a good idea to discuss this issue in a core ticket. I've opened a new ticket, so I'll close this issue.

https://core.trac.wordpress.org/ticket/60535
