### ISSUE TITLE
Define API method for handling legacy content data

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#590]
A block should have a way to optionally define what legacy structures to match. This may be a private API we use for core blocks only.

Examples: text without p tags, captioned images with shortcodes.

This issue is not involved with whether these will be enabled by default (i.e: reading shortcode captioned images and overwriting on save with the new markup).

**Comment by nylen** [comment]
Ideally this would not need to be a separate method:  we just define a data/markup structure that a block can accept, and look inside the post content for valid instances of these structures.  See https://github.com/WordPress/gutenberg/issues/391#issuecomment-294965687 for an example of how this could be achieved.

**Comment by mtias** [comment]
Another thought I discussed at some point with @aduth was that this layer could also function for pasting content from other places (word, google docs, etc).

**Comment by iseulde** [comment]
See also #589 for text. Potentially text could be handled automatically if it's just the p tag or text without delimiters.

**Comment by mtias** [comment]
Closing this as things have evolved and we are looking at handling specific cases individually.
