### ISSUE TITLE
Block Hooks: Toggle to enable/disable hooked block doesn't work properly

### ISSUE THREAD

**Issue by pkuliga** [WordPress/gutenberg#59001]
### Description

The hooked block should be hidden when the toggle is clicked but it's duplicated instead.

### Step-by-step reproduction instructions

1. Hook a block to the last child of the Navigation block by using a `block.json` file
2. Go to Site Editor and edit the Single template
3. Click on the Navigation block and open the block Settings
4. Click the toggle to enable/disable the hooked block

### Screenshots, screen recording, code snippet

![2024-02-13 10 12 21](https://github.com/WordPress/gutenberg/assets/4068554/326b920a-d8cf-4921-ad69-a5cbcd9e0c5f)

### Environment info

- WordPress 6.5-beta1-57631
- Gutenberg 17.7.0-rc.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ockham** [comment]
WIP PR to fix this: https://github.com/WordPress/gutenberg/pull/59277/
