### ISSUE TITLE
Font Library in Beta 1 doesn't reflect all applied fonts in the editor side.

### ISSUE THREAD

**Issue by nith53** [WordPress/gutenberg#59010]
### Description

While testing WordPress 6.5 Beta 1, I found that a few fonts if applied won't be reflected in the editor side. However, the applied font is clearly visible on the front end. The next time we open the editor we are able to see this applied font properly with in the editor, but not during the first application.

### Step-by-step reproduction instructions

1. Install WordPress 6.5 Beta 1
2. Go to font library 
3. These are the two fonts I tested with, [Font 1](https://fonts.google.com/specimen/Are+You+Serious?sort=alpha) and [Font 2](https://fonts.google.com/specimen/Black+And+White+Picture?sort=alpha).
4. Apply the font and check whether it can be viewed in the editor side during the first attempt.

### Screenshots, screen recording, code snippet

The editor side:
![1](https://github.com/WordPress/gutenberg/assets/141323754/81e7a9e1-6e10-4c18-90fa-f4427e935f1f)

The front end:
![2](https://github.com/WordPress/gutenberg/assets/141323754/99925790-ace4-4a6d-8a70-f05308f43a16)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by matiasbenedetto** [comment]
I reported this in trac to add the fixes into core repo https://core.trac.wordpress.org/ticket/60541#ticket

**Comment by nith53** [comment]
> I reported this in trac to add the fixes into core repo https://core.trac.wordpress.org/ticket/60541#ticket

A ticket for the same was opened earlier on Core Trac. https://core.trac.wordpress.org/ticket/60537
