### ISSUE TITLE
Data Views > Pages: Show a preview of pages for grid view

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#59041]
Right now, pages is empty and doesn't show a preview, like you find on templates or patterns:

![Screenshot 2024-02-14 at 3 35 49 PM](https://github.com/WordPress/gutenberg/assets/26996883/8c6f1fa6-f585-4b6c-9cf4-6d3d402f168a)

Can we add a preview of the page here? Any reason this is empty? It makes it look like something is broken or missing @WordPress/gutenberg-design

**Comment by t-hamano** [comment]
Unlike templates and patterns, the grid layout in Pages displays featured images in the preview area instead of content previews. Maybe we should display some kind of icon or placeholder, as suggested in [this comment](https://github.com/WordPress/gutenberg/pull/58304#issuecomment-1914673756).

**Comment by annezazu** [comment]
Hmmm there were featured images set for some of these pages though and they didn't show. Perhaps this is a bug then?

**Comment by t-hamano** [comment]
That's strange. I was unable to reproduce this issue in WP6.5 Beta1. The issue cannot be reproduced even if Gutenberg version 17.7.0 is enabled 🤔

https://github.com/WordPress/gutenberg/assets/54422211/5c79e7d2-700a-4637-8c4b-86882ba2a77d

**Comment by annezazu** [comment]
Hmm here's what it looks like with just 6.5-beta1:

https://github.com/WordPress/gutenberg/assets/26996883/e06a97da-703d-46b8-b6ba-6c941822c83c

I could then replicate it with 6.5-beta1-57631.

**Comment by t-hamano** [comment]
Just to be sure, is the featured image not displayed even when the "featured image" field is enabled in the table layout?

![table-layout](https://github.com/WordPress/gutenberg/assets/54422211/890a6624-3391-414b-8abf-4f2c2173cc72)

**Comment by jameskoster** [comment]
We should probably update the placeholder design a bit. When there are no featured images at all it's not entirely clear what's going on. We might use an icon, or something similar to the placeholder state you find in the editor:

<img width="868" alt="placeholder" src="https://github.com/WordPress/gutenberg/assets/846565/6a79bbc0-b155-4fd8-97f3-e28355669b81">

**Comment by annezazu** [comment]
>Just to be sure, is the featured image not displayed even when the "featured image" field is enabled in the table layout?

Correct. I don't see it there either. I'm going to mark this as a bug to be safe and add to 6.5 @colorful-tones @fabiankaegy can you all replicate by chance? To be clear, when you set featured images for pages can you see those images previewed when using data views.

**Comment by annezazu** [comment]
>We should probably update the placeholder design a bit. When there are no featured images at all it's not entirely clear what's going on. We might use an icon, or something similar to the placeholder state you find in the editor: 

Opened a separate issue for this: https://github.com/WordPress/gutenberg/issues/59098

**Comment by colorful-tones** [comment]
I see featured images fine in the 'Manage all pages' area with new data views, and for both the Grid and Table layouts.

**WP 6.5-beta1 - no plugins**

| 'Manage all pages' Grid view | 'Manage all pages' Table view |
|---------|------------|
| ![Screenshot 2024-02-15 at 3 51 50 PM](https://github.com/WordPress/gutenberg/assets/405912/0888ea71-5be2-4bf6-8a8a-b0a56acd503a) | ![Screenshot 2024-02-15 at 3 51 38 PM](https://github.com/WordPress/gutenberg/assets/405912/cd61865f-1b17-48c0-baef-1339c82e8655) |

**WP 6.5-beta1 + Gutenberg trunk** https://github.com/colorful-tones/gutenberg/commit/d46d7a145b6c1a71c73cd7dc9253f0bdeaaa3c69 active

| 'Manage all pages' Grid view | 'Manage all pages' Table view |
|---------|------------|
| ![Screenshot 2024-02-15 at 3 56 16 PM](https://github.com/WordPress/gutenberg/assets/405912/015c0406-0958-4da7-8258-45be2b606d35) | ![Screenshot 2024-02-15 at 3 56 06 PM](https://github.com/WordPress/gutenberg/assets/405912/4134fca7-8464-4de3-9953-15b49b7b1b59) |

**WP 6.5-beta1-57633 - no plugins**

| 'Manage all pages' Grid view | 'Manage all pages' Table view |
|---------|------------|
| ![Screenshot 2024-02-15 at 4 02 45 PM](https://github.com/WordPress/gutenberg/assets/405912/43cefb45-9b80-43ec-8ffd-b66a748e8dfd) | ![Screenshot 2024-02-15 at 4 02 33 PM](https://github.com/WordPress/gutenberg/assets/405912/5fca54d3-8c05-4019-8f91-f39b0ad163e0) |

In all my testing scenarios the featured image is displaying fine. @annezazu I wonder how if it could be your testing platform? Are you using Playground? 

FYI - I'm using the WordPress Beta Tester plugin to test WP 6.5 betas on Local. Just in case it helps. 🤷

**Comment by annezazu** [comment]
Hmmm seems this might be a playground issue 😭 @adamziel no clue what's going on here but this is making playground less and less likely for me to use for testing features due to how unreliable it seems to be with giving a "true" environment. Going forward, I'm no longer going to use playground for testing issues related to 6.5 for this release and will try again in 6.6. It's wasting too much time for me to have to duplicate across situations and, in this case, was a collective waste of time.  

Closing this out for now. Thank you all for testing and digging in here. I didn't realize how many differences there would be.

**Comment by t-hamano** [comment]
I see, this is a problem that can be reproduced with Playground. I was able to reproduce it too 😅 However, I found that this problem can be reproduced even in a non-Playground environment. For example, if you set a very small image such as 50px as the featured image, you will be able to reproduce this problem.

Therefore, I would like to reopen this issue and submit a PR.

---

@adamziel, As far as I investigated, I think that one of the reasons is that the media sizes are not generated in Playground. For example, if I run `wp.data.select( 'core' ).getEntityRecord( 'root', 'media', X )` in the browser console after uploading media, `media_details.size` will always be an empty object. Is my understanding correct?

Another reason is that Gutenberg did not consider a scenario where these sizes did not exist.

https://github.com/WordPress/gutenberg/blob/0e899f76951edd6e4b8ec9cc5d8260b3b7bba0ed/packages/edit-site/src/components/media/index.js#L8-L14

**Comment by colorful-tones** [comment]
@t-hamano you are amazing and nice digging to find and reproduce that bug. 👏

**Comment by annezazu** [comment]
Amazing work! In sleuthing a non-bug, you found a bug 🐛 .

**Comment by t-hamano** [comment]
The issue on Playground should also be resolved. You can test it by following the steps below.

- Access [Gutenberg PR Previewer](https://playground.wordpress.net/gutenberg.html) and enter the PR number (59111)
- From the top right panel, change the WordPress version to 6.5-beta1

#59111 should be backported to 6.5Beta2, so once Beta2 is released, you should simply launch Playground.


https://github.com/WordPress/gutenberg/assets/54422211/88cdad8c-ed2f-4dbd-aa7c-2b5ddf4669a3

**Comment by adamziel** [comment]
This is amazing, thank you so much @t-hamano!

> if I run wp.data.select( 'core' ).getEntityRecord( 'root', 'media', X ) in the browser console after uploading media, media_details.size will always be an empty object. Is my understanding correct?

I think so! I imagine the `getEntityRecord` selector would synchronously return what's already in the store, and the resolver would start an asynchronous request to retrieve the information from the server.
