### ISSUE TITLE
URL input is broken when button text labels are enabled

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#59054]
### Description

With button text labels enabled, the "copy", "edit" and "remove" buttons inside the URL input are visually scrambled and not clickable with a mouse:

<img width="407" alt="Screenshot 2024-02-15 at 5 37 20 pm" src="https://github.com/WordPress/gutenberg/assets/8096000/f165a62d-fb54-40be-b768-8a07104e08b9">

### Step-by-step reproduction instructions

1. In Preferences > Accessibility, enable "Show button text labels".
2. Try to edit an existing URL and verify the buttons are unusable.

### Environment info

Can reproduce this in Gutenberg trunk and WP 6.5 Beta 1.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by draganescu** [comment]
What a mess 😁
