### ISSUE TITLE
Add Box Shadow support for featured image

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#59067]
## What problem does this address?
In templates, features image are a major design element for Archive pages, and it would be expanded the design tools considerably if the box shadow support that is now available for the image block could also be provided for the featured image block. 

## What is your proposed solution?
Open up box shadow support to featured image (among other blocks)

**Comment by colinduwe** [comment]
I tried to add this enhancement but I've run into an issue that I can't seem to resolve. 
I added block.supports.shadow.__experimentalSkipSerialization in block.json but it's still outputting the shadow attributes on the block wrapper element (figure).

Here's an excerpt of block.json supports section
```
"__experimentalBorder": {
	"color": true,
	"radius": true,
	"width": true,
	"__experimentalSelector": "img, .block-editor-media-placeholder, .wp-block-post-featured-image__overlay",
	"__experimentalSkipSerialization": true,
	"__experimentalDefaultControls": {
		"color": true,
		"radius": true,
		"width": true
	}
},
"shadow": {
	"__experimentalSkipSerialization": true
},
"html": false,
```
If anyone can point me in the right direction for why __experimentalSkipSerialization is working for the border but not the shadow I'd submit a PR for this.

**Comment by colinduwe** [comment]
@bph I submitted a PR for this. Please have a look.

**Comment by bph** [comment]
@colinduwe Did you get a chance to go over @aaronrobertshaw comments on the PR?

**Comment by colinduwe** [comment]
@bph and @aaronrobertshaw I did look at the comments which led me down the path of trying to make a PR just for the https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/shadow.php file so if a block adds __experimentalSkipSerialization the styles are not output on the block wrapper element. But then I started testing with the core/column block and adding __experimentalSkipSerialization works as expected without the PR. I'm still trying to understand what's different between core/column and core/post-featured-image.

**Comment by aaronrobertshaw** [comment]
>  I'm still trying to understand what's different between core/column and core/post-featured-image.

The difference you encountered is that the `core/column` block is a static block while the `core/post-featured-image` block is dynamic. 

The issue with skipping serialization is specific to dynamic blocks and is why it is limited to the PHP hook that applies the shadow support.
