### ISSUE TITLE
Help integrating ACF field groups into block settings

### ISSUE THREAD

**Issue by rchipka** [WordPress/gutenberg#5907]
I'm attempting to add an ACF location matching rule for Gutenburg blocks so that the fields can be automatically dropped into the block's settings and saved as attributes for that block.

This would be an extremely powerful feature for custom blocks as well as extending functionality on existing blocks.

I have all the ACF stuff working. The location matching is all set up and the fields load into the settings box when the block is selected.

Now my only problem is interfacing with the block API.

For loading fields, I wait for a block to be selected, then attempt to match the field group to that block.

If it matches, and the "Block" tab is selected in the settings box, then it loads the fields into the settings box.

For saving fields, I find the `.is-selected` block element, and then find the `data-block` block ID on the child block.

When the `blocks.blockEdit` filter is called, I check if the filtered block's props.ID matches the `.is-selected` block ID, then I call `setAttributes({ acf_fields: ... })` on the block.

This seems to work fine, but if anyone else has a better way of doing it, I'd greatly appreciate some advice.

I do have a few specific questions:

 1. Is there any way (from within any hook) that I can identify the element as the currently selected block without the hacky ID matching?
 2. Is there any way to get the ID from within any hook instead of querying the DOM?
 3. Is there any way to retain previously saved attributes when saving again later (without manually re-adding each value)?

Here's the code:

https://gist.github.com/rchipka/4c62e8aa450e34218485d8c724c0d83b

**Comment by rchipka** [comment]
@cr101 Pointed me to [Gutenberg Custom Fields](https://github.com/youknowriad/gcf) on another issue thread.

I thought it would be worth mentioning here that my intention for this solution is to avoid re-implementing a massive code base like ACF using a completely new paradigm (the Gutenburg React component system).

This way we could get existing functionality integrated into the new system as quickly as possible.

Is it hacky to inject ACF fields into a completely React based system? Probably.

Wouldn't we have to do considerably "evil" things in order to achieve this? You bet.

I'm not really concerned with the amount of hooks or hacks it will take to achieve the result, as long as a decent result can be achieved.

Ideally we can get this working the way it we want it to and then we get it working the way it "should" later.

All the ACF stuff is on the up and up, but I need some pointers from the Gutenburg team to move further.

I've done lots of deep source code digging, but I know an experienced React dev from the team could answer my questions pretty quickly.

**Comment by rchipka** [comment]
I believe I've found a better way. Closing this issue. Will publish soon.

**Comment by cr101** [comment]
@rchipka you might also want to look at [create-guten-block](https://github.com/ahmadawais/create-guten-block) if you haven't already.

**Comment by kokers** [comment]
@rchipka would be great if you could share that "better way" you found with others :o)
