### ISSUE TITLE
Components: Revert flaky unit test `sleep()` hacks

### ISSUE THREAD

**Issue by tyxla** [WordPress/gutenberg#59071]
## What problem does this address?
In #59012, #58629, and #58968 we added some `sleep()` calls before `press.Tab()` as a patching attempt to make some unit tests less flaky.

## What is your proposed solution?
We should fix the underlying cause (likely in `@ariakit/test`) instead of resolving it with hacks like this. We should also revert the `sleep()` calls we introduced In #59012, #58629, and #58968.

cc @mirka @Mamaduka

**Comment by tyxla** [comment]
@diegohaz any ideas from the top of your head why tests could be flaky on these rare occasions, and a `sleep()` before `press.Tab()` makes them more stable? Is this something that we could have addressed in `@ariakit/test` instead?

**Comment by diegohaz** [comment]
All items within an Ariakit composite widget remain tabbable until they are completely processed internally (for example, to determine their order). After that, only the active item stays tabbable. This happens asynchronously after the initial render.

This is to guarantee that all elements are accessible to keyboard users until we can respond to arrow keys.

A potential solution could be to wait for inactive items to become non-tabbable before hitting the Tab key during the test.

**Comment by tyxla** [comment]
Cleaning those up in #64205.
