### ISSUE TITLE
Some template blocks in data view previews do not match their display in the editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#59082]
Blocks like "Archive Title" include contextual placeholders. For instance of you're editing the Author archives template it will display 

> Author: Name

or 

> Author name

depending on the block settings:

<img width="1710" alt="Screenshot 2024-02-15 at 14 29 52" src="https://github.com/WordPress/gutenberg/assets/846565/e1b031fa-f5ef-4828-8174-3af8e2c1dc2e">

That contextual placeholder appears correctly in the 'site view' when you browse a template:

<img width="890" alt="Screenshot 2024-02-15 at 14 32 42" src="https://github.com/WordPress/gutenberg/assets/846565/f5f84093-2d64-4d04-a633-165e8e196d02">

However it doesn't carry over to the preview in data views, where it falls back to the generic placeholder:

<img width="343" alt="Screenshot 2024-02-15 at 14 31 55" src="https://github.com/WordPress/gutenberg/assets/846565/3c3ea564-8940-46f8-b0c6-67d3cc9581df">

cc @ntsekouras as iirc you worked on these contextual placeholders.

**Comment by youknowriad** [comment]
Moving this out of 6.6 as we get close to release.

**Comment by youknowriad** [comment]
Not sure how to reproduce this. Can you share more details (which theme and template to use), for me in 2024 and "archives" template it shows the same thing between preview and editor: Archive type: Name

**Comment by jameskoster** [comment]
@youknowriad you have to create a more specific archive template, e.g. `author.html`.
