### ISSUE TITLE
Social icons: Update Soundcloud Logo

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#59084]
## What problem does this address?

Soundcloud has updated their logo (less stripes) and it should be also updated in the editor.
https://press.soundcloud.com/media_kits/228462/

Related, identical issues:
Twitter / X Logo: https://github.com/WordPress/gutenberg/issues/53223
Patreon Logo: https://github.com/WordPress/gutenberg/issues/56925 

## What is your proposed solution?

Updating the logo as for the recent Patreon logo change: https://github.com/WordPress/gutenberg/pull/56951
Soundcloud actually also has changed the brand color related to the logo to black. Not sure about this one though, since the website also still uses the orange and the Media Kit doesn't provide any further information.

**Comment by hanneslsm** [comment]
The media kit only contains PNGs.
Tagging some people from Soundcloud, maybe you could help providing a SVG for WordPress? @pietropizzi @ccmtaylor @miguelgraz Cheers!

**Comment by Mamaduka** [comment]
Resolved via #63504.
