### ISSUE TITLE
Metadata attribute is not preserved after transforming paragraph block into heading

### ISSUE THREAD

**Issue by SantosGuillamot** [WordPress/gutenberg#59086]
## What?
It seems that when transforming a block the `metadata` attribute is not preserved. For example, if I name a paragraph block with a custom name, it disappears after transforming it into a heading. Or if it has some bindings.

It seems it works fine with other attributes.

Is this expected? If not, any idea how it could be solved?

## Reproduce

1. Add a paragraph to a post.
2. Rename the block to "Custom name".
3. Transform the paragraph block into a heading block.
4. Check that the "Custom name" has dissapeared.

**Comment by gziolo** [comment]
@ntsekouras, who would be the best person to explore the best way to generalize handling for metadata attributes. I’m wondering if that’s a bigger task that also impacts Global Styles and other settings dynamically injected with hooks in the block editor. At the same time, maybe it’s expected to retain only the content.

**Comment by talldan** [comment]
I also made an issue for this - [Block renaming: retain name when transforming to a different block](https://github.com/WordPress/gutenberg/issues/57752#top)

I'll close that one though seeing as the discussion is starting here.
