### ISSUE TITLE
Social Icons: Update Reddit Logo

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#59088]
## What problem does this address?
Reddit has updated their logo and it should be also updated in the editor.

Related / identical issues:
Twitter / X Logo: https://github.com/WordPress/gutenberg/issues/53223
Patreon Logo: https://github.com/WordPress/gutenberg/issues/56925
Soundcloud Logo: https://github.com/WordPress/gutenberg/issues/59084

## What is your proposed solution?
Update the Reddit icon to the new one, probably `Reddit_Icon_2Color_FullBleed`
https://reddit.lingoapp.com/s/d9x3n2/?v=21

**Comment by AnukratiMehta** [comment]
Hello, @hanneslsm, I'd like to work on this.

**Comment by AnukratiMehta** [comment]
Hello, the changes I'm making are not reflecting in the editor which makes me unable to test them. This is the first time I'm contributing to WordPress. Can you help me figure out what I may be missing, please?

For context, I've followed the [contributing guidelines](https://github.com/WordPress/gutenberg/blob/a2d2c2b6b5a6fc673e663fdeae4076c12d0ccbe9/docs/contributors/code/getting-started-with-code-contribution.md) to set up the Local WordPress Environment and everything is running smoothly. 

I also followed the Testing Instructions from [this issue](https://github.com/WordPress/gutenberg/pull/56951). 

I'm happy to provide additional information. Thanks!

**Comment by colinduwe** [comment]
In your terminal, have you navigated into the gutenberg plugin directory and run "npm start"? That will start the watch process so when you save file changes it will rebuild the plugin and you should see you changes in the editor (when you reload your browser). Keep an eye on the terminal. It will warn when you have errors that prohibit the plugin from being built.

**Comment by AnukratiMehta** [comment]
> In your terminal, have you navigated into the gutenberg plugin directory and run "npm start"? That will start the watch process so when you save file changes it will rebuild the plugin and you should see you changes in the editor (when you reload your browser). Keep an eye on the terminal. It will warn when you have errors that prohibit the plugin from being built.

@colinduwe I have and the plugin is built correctly too. I see the change in the terminal when a file is updated, but that same change is not reflected in the browser.

**Comment by AnukratiMehta** [comment]
Hello, I'm gonna let this go since I still can't test it. Thanks!

**Comment by hanneslsm** [comment]
@AnukratiMehta Thanks for taken over the issue! Unfortunately I cannot help since I am not familiar with testing by myself. 
However, I will try to get you help. In parallel, I encourage you to reach out to the community. A good place to ask specific questions like yours in the forum or slack channels.
