### ISSUE TITLE
Site Editor > Patterns: Consider adding a "Add new pattern" button

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#59099]
In watching some folks test the new Data Views for 6.5, one of the participants mentioned how hard it is to figure out how to create your own patterns with the + button being so easy to miss. When compared to the other sections, it stands out even more as the Patterns section shows all patterns but doesn't have that ever present "Add new ____" button clearly placed. This feels odd considering patterns are likely something someone will build more than new templates. We want folks to use these and they aren't meant to be overly advanced! Here's a snapshot:

**Site Editor > Templates > Manage all templates:**

![Screenshot 2024-02-15 at 9 42 17 AM](https://github.com/WordPress/gutenberg/assets/26996883/03462e21-3a14-442f-a828-22a532f6287d)

**Site Editor > Patterns**
![Screenshot 2024-02-15 at 9 42 33 AM](https://github.com/WordPress/gutenberg/assets/26996883/3f03b988-3da6-414a-8c12-66b56d4412b0)

**Site Editor > Patterns > Manage all template parts**

![Screenshot 2024-02-15 at 9 51 03 AM](https://github.com/WordPress/gutenberg/assets/26996883/3c5f7894-9d82-4f5b-bb5e-db4d433b0f7f)

**Site Editor > Pages > Manage all pages**
![Screenshot 2024-02-15 at 9 42 06 AM](https://github.com/WordPress/gutenberg/assets/26996883/936459ad-a1ff-4c8f-ac8e-0ea6d40b692d)

## How can we improve this?

My brain goes in a few directions:

- Add a "Add new pattern" to each section of patterns. We'd have to decide if you're in the "Banner" category if clicking "Add new" would automatically add that as a category or if each were distinct ("my patterns" would have to be no category since it isn't tied to one).
- Add "Add a new pattern" after someone adds an initial pattern under just the "my patterns" section and "all patterns" (or just one section). This would at least tie the action to creating your own pattern but doesn't seem great nor consistent. I could see it feeling like something you're stumbling on and it stands in contrast to what we do in other sections.

Something else entirely :)  @WordPress/gutenberg-design as I imagine this was an intentional decision.

**Comment by jameskoster** [comment]
This was originally noted in https://github.com/WordPress/gutenberg/issues/58198. Perhaps @ntsekouras has a moment to look into the feasibility?

**Comment by richtabor** [comment]
Would we not use the + in the dark material? That seems more connective/existing. Why'd we opt for the big button on the right, rather than leverage the existing +?

**Comment by jameskoster** [comment]
In data views, the sidebar primarily serves for navigation and managing views. Some data views may not require additional or custom views, thus lacking a dedicated drilldown. Without a drilldown, where would the '+' button live?

<img width="1251" alt="Screenshot 2024-02-19 at 14 14 07" src="https://github.com/WordPress/gutenberg/assets/846565/0dca1244-bd38-4ada-b13e-6b836ef2a65e">

**Comment by SaxonF** [comment]
What @jameskoster said. Would be nice to start establishing this standard pattern of title on left and CTA's on right when it comes to page content. Actions in sidebar can relate to whatever is in the sidebar, in the case of data views its "views".
