### ISSUE TITLE
Rework dummy post-content to be a "welcome" tutorial

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#591]
Let's use the default post to describe how the editor works, what you can do, the main interaction patterns, default blocks, etc.

**Comment by BE-Webdesign** [comment]
I was also thinking we could build in some user guides into the plugin a help section of sorts.

**Comment by jasmussen** [comment]
> I was also thinking we could build in some user guides into the plugin; a help section of sorts.

Just opened a ticket for porting the help button in #599. In addition to this, there's a ticket for using WordPress pointers in #592. Perhaps these two tickets combined can accomplish this?

**Comment by jasmussen** [comment]
Closing as fixed, as this is in master!
