### ISSUE TITLE
Add "taxonomy" source to block attributes

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#5912]
## Issue Overview
Right now you can have a block attribute be derived from the meta of a post, like so:

> attributes: {
>     attributeName: {
>         type: 'string',
>         source: 'meta',
>         meta: 'meta_key'
>     }
> }

It would be really useful if you could also have block attributes that were derived from the tags, categories, or other taxonomical terms applied to the post. Here is what it could look like:

> attributes: {
>     attributeName: {
>         type: 'array',
>         source: 'taxonomy',
>         taxonomy: 'taxonomy_name'
>     }
> }

This would make it easy to create a block that displays the tags, categories, or custom taxonomy terms of a post.

Is this feasible to implement, and is this the right way to implement it?

**Comment by karmatosed** [comment]
This seems like an interesting idea to bring into later iterations of Gutenberg. Right now let's move it to the ideas project and close. This means it will be considered after 5.0
