### ISSUE TITLE
"Variants from only one font family can be uploaded at a time." is a very unhelpful error message.

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#59138]
### Description

When uploading multiple font files, it's possible to get the error message "Variants from only one font family can be uploaded at a time".

This is really unhelpful copy for users unfamiliar with font categorization, especially when the difference between files uploaded is standard, condensed, semi-condensed, etc.

If a user attempts to upload fonts from multiple families at once, then multiple font families should be created.

While the reproduction steps below use standard & condensed fonts as an example, the same should apply across families. For example attempting to upload both Open Sans and Source Code Pro.

### Step-by-step reproduction instructions

1. Download [Open Sans from Google Fonts](https://fonts.google.com/specimen/Open+Sans) - using the Install fonts tab will not demonstrate the issue
2. Open the fonts manager > Uploads
3. Unzip the open sans download
4. Select a mix of condensed, semi-condensed and standarfd the fonts in the static folder
5. Drag them to the upload drop zone
6. the error message is displayed

### Screenshots, screen recording, code snippet

![unhelpful-error](https://github.com/WordPress/gutenberg/assets/519727/91f199e4-3656-4fb3-a598-b62b14b44681)

### Environment info

- WordPress 6.4
- Gutenberg trunk @ 96cb434382c2a70d991eab85ceb542b76c30a94a

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by colorful-tones** [comment]
I do worry that we may want to consider incorporating some font file checking, which may be as simple as name (string) comparison on uploading. If a filename marches then we could provide some messaging: “there is an existing font already uploaded.” Also, some organization into fonts directories may be beneficial in the string comparison and organization ([see my comment here](https://github.com/WordPress/gutenberg/pull/58474#pullrequestreview-1854867224)).

These comments ☝  should not impact this issues progress and just surfacing some larger viewpoints for Font Library challenges.

**Comment by matiasbenedetto** [comment]
I agree. The error message is not so clear. A PR improving the text is welcome, or, even better, fixing the root limitation that makes this message needed: https://github.com/WordPress/gutenberg/issues/58689

**Comment by peterwilsoncc** [comment]
I'm happy to help with a pull request, is there a copy writer I can get assistance from?

**Comment by annezazu** [comment]
>I'm happy to help with a pull request, is there a copy writer I can get assistance from?

@peterwilsoncc I can snag you folks! Having the `[Type] Copy` should help. I'll re-alert some copy writers to this for now.

**Comment by provenself** [comment]
Editorial/copy folks checking in! 👋 

Re:
> A PR improving the text is welcome, or, even better, fixing the root limitation that makes this message needed: https://github.com/WordPress/gutenberg/issues/58689

For clarity, are you looking to address the text as is, or to fix the limitation first and then reimagine the text?

**Comment by matiasbenedetto** [comment]
> For clarity, are you looking to address the text as is, or to fix the limitation first and then reimagine the text?

A fix for the root issue is in-progress: https://github.com/WordPress/gutenberg/pull/59425

**Comment by provenself** [comment]
> > For clarity, are you looking to address the text as is, or to fix the limitation first and then reimagine the text?
> 
> A fix for the root issue is in-progress: #59425

thank you @matiasbenedetto! I'll follow along there.

**Comment by pbking** [comment]
Closing as complete, though actually unnecessary as #58689 has been completed instead (allowing fonts from multiple families to be uploaded)
