### ISSUE TITLE
Navigation FSE: 

### ISSUE THREAD

**Issue by yeu** [WordPress/gutenberg#59131]
### Description

Navigation menu FSE: When I add an item (page) in the navigation menu and then change the URL (slug) of that page, the permalink/url/slug of the item in the navigation menu remains the old one, it is "detached" from the page.

### Step-by-step reproduction instructions

1. Go to **Appearance > Editor**;
2. Click on **Patterns**;
3. From _Template Parts_ click on **Header**;
4. Click on _Header_ block to edit it;
5. Click on **Navigation** block;
6. In the **Settings** bar (on the right), click on one of the page items;
7. A popup asks you to desynchronize that item from its page, click on **Detach**;
8. Now go to **Pages**, edit a page and change it url/slug;
9. Update the page;
10. Now you can check that the menu item url is NOT updated, but the old one remains.

### Environment info

WordPress version: 6.4.3;
Gutenberg version: the most recent;
Browser: Chrome desktop;
O.S.: Windows 10 Home (version 22H2).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @yeu,

Is the problem you are heading towards the same as mentioned in #52740?

**Comment by yeu** [comment]
Hi @t-hamano,

yes is it. Do you think it could be fixed soon?

**Comment by t-hamano** [comment]
> Do you think it could be fixed soon?

Technically, I think this issue is an improvement rather than a bug. Also, let's close this issue and focus the discussion on #52740.
