### ISSUE TITLE
Typo in filename: use-hide-bocks-from-inserter.js

### ISSUE THREAD

**Issue by annaghi** [WordPress/gutenberg#59148]
### Description

There's a typo in a filename;
`use-hide-bocks-from-inserter.js` is misspelled and should be
`use-hide-blocks-from-inserter.js`

### Step-by-step reproduction instructions

Locate the file in `/packages/editor/src/components/provider/` and observe the typo.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
I'll fix this quickly.
