### ISSUE TITLE
Possibly incorrect code example in the BlockAlignmentToolbar component's readme file

### ISSUE THREAD

**Issue by lunule** [WordPress/gutenberg#59141]
### Description

Not 100% sure about this, but I think the Block Alignment Control component's readme file includes incorrect example code:

``` js
import { BlockAlignmentToolbar } from '@wordpress/block-editor';

const MyBlockAlignmentToolbar = () => (
	<BlockControls>
		<BlockAlignmentToolbar value={ align } onChange={ updateAlignment } />
	</BlockControls>
);
```

Instead of the above, I
- import `BlockAlignmentControl` from `@wordpress/block-editor`, and 
- use the `BlockAlignmentControl` component instead of `BlockAlignmentToolbar`.

The following code (based on the **Text Alignment Control**'s example code [here](https://github.com/WordPress/gutenberg/blob/HEAD/packages/block-editor/src/components/alignment-control/README.md)) works fine.

``` js
import { BlockAlignmentControl } from '@wordpress/block-editor';

const MyBlockAlignmentToolbar = () => (
	<BlockControls>
		<BlockAlignmentControl value={ align } onChange={ updateAlignment } />
	</BlockControls>
);
```

Is the current example code in the readme file incorrect indeed? Or are both versions (`BlockAlignmentControl` & `BlockAlignmentToolbar`) valid, kinda like two different names/variations of the same thing?

(Additionally: there's no explanation of how Toolbar and Component versions relate in the developer guide [@wordpress/block-editor
](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/#api) either.)

### Step-by-step reproduction instructions

You can see the referenced example code in the Block Alignment Control component's readme file.
https://github.com/WordPress/gutenberg/blob/96cb434382c2a70d991eab85ceb542b76c30a94a/packages/block-editor/src/components/block-alignment-control/README.md

**Comment by t-hamano** [comment]
Hi @lunule,

I believe both `BlockAlignmentToolbar` and `BlockAlignmentControl` work correctly. Below is sample code for each and how it is rendered.

### BlockAlignmentToolbar

```javascript
import {
	useBlockProps,
	BlockControls,
	BlockAlignmentToolbar,
} from '@wordpress/block-editor';

export default function Edit() {
	const blockProps = useBlockProps();
	return (
		<>
			<BlockControls>
				<BlockAlignmentToolbar />
			</BlockControls>
			<div { ...blockProps }>Block</div>
		</>
	);
}
```

![block-alignment-toolbar](https://github.com/WordPress/gutenberg/assets/54422211/b58f55f0-0bad-46c9-8135-93c519fc6f74)

### BlockAlignmentControl

```javascript
import {
	useBlockProps,
	BlockControls,
	BlockAlignmentControl,
} from '@wordpress/block-editor';

export default function Edit() {
	const blockProps = useBlockProps();
	return (
		<>
			<BlockControls>
				<BlockAlignmentControl />
			</BlockControls>
			<div { ...blockProps }>Block</div>
		</>
	);
}
```

![block-alignment-control](https://github.com/WordPress/gutenberg/assets/54422211/35beb9b2-6cd7-414b-b4d4-014a8d727776)


Internally, only the `isToolbar` property seems to be different.

https://github.com/WordPress/gutenberg/blob/b91beb0c2a388e465f8d1aeb550546ac2ff04f11/packages/block-editor/src/components/block-alignment-control/index.js#L6-L12

However, this implementation is also done in other components.

- [AlignmentControl, AlignmentToolbar](https://github.com/WordPress/gutenberg/blob/b91beb0c2a388e465f8d1aeb550546ac2ff04f11/packages/block-editor/src/components/alignment-control/index.js#L6-L12)
- [BlockVerticalAlignmentControl, BlockVerticalAlignmentToolbar](https://github.com/WordPress/gutenberg/blob/b91beb0c2a388e465f8d1aeb550546ac2ff04f11/packages/block-editor/src/components/block-vertical-alignment-control/index.js#L6-L12)
- [JustifyContentControl, JustifyContentToolbar](https://github.com/WordPress/gutenberg/blob/b91beb0c2a388e465f8d1aeb550546ac2ff04f11/packages/block-editor/src/components/justify-content-control/index.js#L6-L12)

**Comment by lunule** [comment]
Hey @t-hamano,

A huge thanks for the detailed explainer, and for the additional reference for the other components. Precious detials to add to my own Gutenberg/FSE docs!! 

So, as far as I see and regarding the display in the editor, the difference is minimal - from a point of view of user-friendliness, the `Control` versions can be considered more recommended compared to the `Toolbar` versions, as the former one displays the relevant specific pixel values as well.
