### ISSUE TITLE
6.5 Dev Note Tracking Issue

### ISSUE THREAD

**Issue by Leonardus-Nugraha** [WordPress/gutenberg#59155]
## Tracking all Dev Notes from Gutenberg plugin releases 16.8 - 17.7

Please read the information below carefully. If you have questions, connect with @Leonardus-Nugraha via Slack or comment here. 

- **🗓 **Deadline** March 4th, 2024** 

Not all developer-related information needs to be in a separate DevNote on the Make Core blog for the field guide. We can group related information.  We can already make decisions on some features if it warrants a stand-alone blog post or if the information will be part of a group post. 

## Stand-alone post
To streamline the process and eliminate bottlenecks, all writers of stand-alone dev notes will write the dev notes on the Make Core Blog.
 
**Instructions**
<details>

- Create your note in a new post,
- Save as Draft
- Enable public preview
- Share the link to the public preview in a comment below, as "ready for review"
- "For dev notes, each one must have at least two reviewers" ([Handbook](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/))

</details>

## Part of a group post
If the information related to your PR will be part of a group post, please write the **dev note in a comment on the PR**, so it can be reviewed and, if necessary commented on, by the release docs team or a reviewer. 

## Before you start writing  📣  please read the handbook pages: 

<details>

- ⭐️ [Writing developer notes](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/)
- ⭐️ [Style & Substance section](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#style-and-substance) of the Post & Comment Guidelines for Make Blog 
- ⭐️ [Documentation Style Guide](https://make.wordpress.org/docs/style-guide/) - Good for reference, when in doubt, especially when English is not your native language.
- 
</details>

The list is incomplete. We are in the process of reviewing plugin release changelogs and add them as we progress on the task. 

There are two labels: 
[`needs dev note`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22) and [`has dev note`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Has+Dev+Note%22+) 

If you worked on a feature/module/component that definitely needs a dev note, please assign the label `needs dev note` If you already added the Dev Note to the make blog on draft or as a comment on the PR, please label it `has dev note` 

---

### To Do

- [x] #58620 @andrewhayward  
- [x] #57353 @jorgefilipecosta  
- [x] #55551 @fabiankaegy 
- [x] #55423 @ryanwelcher 
- [x] #55200 @retrofox 
- [x] #54740 @andrewhayward  

`viewScriptModule`: [dev note preview](https://make.wordpress.org/core/?p=111510&preview=1&_ppp=a30e4d185f) - Published
- [x] #58731 @sirreal 
- [x] #57461 @sirreal 
- [x] #57437 @sirreal 

Site editor and page editor unification: [dev note preview](https://make.wordpress.org/core/wp-admin/post.php?post=111680&action=edit)
- [x] #57158 @youknowriad 
- [x] #57012 @youknowriad 
- [x] #56000 @youknowriad 

Deprecate outer margins: [dev note draft](https://make.wordpress.org/core/?p=111864&preview=1&_ppp=07ca7efbd7)
- [x] #58702 @mirka 
- [x] #58701 @mirka 
- [x] #58700 @mirka 
- [x] #58699 @mirka 👈 Dev Note for all 4 PRs consolidated here
- [x] #58974 @mirka
- [x] #58703 @mirka

Font Library: [dev note draft](https://docs.google.com/document/d/1ZUgCpK02gCs_jOd3i1NUDhd9pcDYPD2iQZAUAAWsUNo/edit?usp=sharing)
- [x] #57818 @matiasbenedetto 
- [x] #57569 @matiasbenedetto 
- [x] #54701 @matiasbenedetto 

Misc Dev Notes: [post draft](https://make.wordpress.org/core/?p=111761&preview=1&_ppp=eeaf733814)
- [x] #57005 @andrewserong 
- [x] #56897 @andrewserong 
- [x] https://github.com/WordPress/gutenberg/pull/56064
- [x] #53467 @t-hamano 
- [x] #45731 @t-hamano 
- [x] #57303 @sirreal 
- [x] #54426 
- [x] #58120 @mcsf
- [x] #58262 @jsnajdr 
- [x] #54046 @ramonjd 
- [x] #55337 @jsnajdr  

Block Hooks - Published
- https://make.wordpress.org/core/?p=111613&preview=1&_ppp=a72624fc45

Block Bindings - Published
- https://make.wordpress.org/core/2024/03/06/new-feature-the-block-bindings-api/

**Comment by t-hamano** [comment]
This is a dev note for #53467. Perhaps it would be good to include it as part of the miscellaneous dev note.

https://github.com/WordPress/gutenberg/pull/53467#issuecomment-1951597227

**Comment by andrewserong** [comment]
I've added dev notes as comments to the following PRs:

* https://github.com/WordPress/gutenberg/pull/57005#issuecomment-1951663630
* https://github.com/WordPress/gutenberg/pull/56897#issuecomment-1951680107
* https://github.com/WordPress/gutenberg/pull/56064#issuecomment-1953209301

These features don't require a separate dev note, so can also be added as part of the miscellaneous dev note.

**Comment by t-hamano** [comment]
I added a new #45731 to the list and wrote a dev note. I think it's fine as part of the miscellaneous dev note.

- https://github.com/WordPress/gutenberg/pull/45731#issuecomment-1954048651

**Comment by sirreal** [comment]
The dev note for #57303 was submitted in this comment: https://github.com/WordPress/gutenberg/pull/57303#issuecomment-1869443043

**Comment by sirreal** [comment]
[I've added a link to the `viewScriptModule` dev note preview.](https://make.wordpress.org/core/?p=111510&preview=1&_ppp=a30e4d185f)

**Comment by Leonardus-Nugraha** [comment]
Reminder for PR owners to draft the dev notes by the end of this week if possible

https://github.com/WordPress/gutenberg/pull/58620 @andrewhayward
 https://github.com/WordPress/gutenberg/pull/58262 @jsnajdr
 https://github.com/WordPress/gutenberg/pull/58120 @mcsf
 https://github.com/WordPress/gutenberg/pull/57353 @jorgefilipecosta
 https://github.com/WordPress/gutenberg/pull/57158 @youknowriad
 https://github.com/WordPress/gutenberg/pull/57012 @youknowriad
 https://github.com/WordPress/gutenberg/pull/56000 @youknowriad
 https://github.com/WordPress/gutenberg/pull/55551 @fabiankaegy
 https://github.com/WordPress/gutenberg/pull/55423 @ryanwelcher
 https://github.com/WordPress/gutenberg/pull/55337 @jsnajdr
 https://github.com/WordPress/gutenberg/pull/55200 @retrofox
 https://github.com/WordPress/gutenberg/pull/54740 @andrewhayward
 https://github.com/WordPress/gutenberg/pull/54494 @youknowriad
 https://github.com/WordPress/gutenberg/pull/54426 @getdave 
 https://github.com/WordPress/gutenberg/pull/57818 @matiasbenedetto
 https://github.com/WordPress/gutenberg/pull/57569 @matiasbenedetto
 https://github.com/WordPress/gutenberg/pull/54701 @matiasbenedetto

**Comment by mikachan** [comment]
Noting that the Font Library items listed above should be covered in a dev note that's being drafted [here](https://docs.google.com/document/d/1ZUgCpK02gCs_jOd3i1NUDhd9pcDYPD2iQZAUAAWsUNo/edit).

**Comment by ockham** [comment]
The Block Hooks in 6.5 Dev Note now has a [draft](https://make.wordpress.org/core/wp-admin/post.php?post=111613&action=edit) available in make/core.

**Comment by mcsf** [comment]
Dev note for #58120:

* https://github.com/WordPress/gutenberg/pull/58120#issuecomment-1971396876

**Comment by cbravobernal** [comment]
The Interactivity API in 6.5 Dev Note has a [draft](https://make.wordpress.org/core/?p=111631&preview=1&_ppp=b0a9242da4) available in make/core.

**Comment by jsnajdr** [comment]
Dev note for #58262 (`allowedBlocks` in `block.json`):
- https://github.com/WordPress/gutenberg/pull/58262#issuecomment-1972709233

**Comment by youknowriad** [comment]
A [draft](https://make.wordpress.org/core/wp-admin/post.php?post=111680&action=edit) of the "unification of post and site editors" dev note is available on make/core.

This addresses the three following PRs:

https://github.com/WordPress/gutenberg/pull/57158
https://github.com/WordPress/gutenberg/pull/57012
https://github.com/WordPress/gutenberg/pull/56000

**Comment by youknowriad** [comment]
https://github.com/WordPress/gutenberg/pull/54494 doesn't seem worth a dev note to me.

**Comment by jsnajdr** [comment]
Dev note for #55337 (`useSettings`):
- https://github.com/WordPress/gutenberg/pull/55337#issuecomment-1972776911

**Comment by sirreal** [comment]
[Dev note draft for the Script Modules API](https://make.wordpress.org/core/?p=111683&preview=1&_ppp=05ec3ef05b)

**Comment by getdave** [comment]
[Dev note for block renaming for (almost) all blocks](https://github.com/WordPress/gutenberg/pull/54426#issuecomment-1927069908)

**Comment by Leonardus-Nugraha** [comment]
> [I've added a link to the `viewScriptModule` dev note preview.](https://make.wordpress.org/core/?p=111510&preview=1&_ppp=a30e4d185f)

@sirreal this one has been reviewed

**Comment by retrofox** [comment]
[Dev note for "Editor: Introduce PluginPostExcerpt slot #55200"](https://github.com/WordPress/gutenberg/pull/55200#issuecomment-1975175227)

**Comment by sirreal** [comment]
> > [I've added a link to the `viewScriptModule` dev note preview.](https://make.wordpress.org/core/?p=111510&preview=1&_ppp=a30e4d185f)
> 
> @sirreal this one has been reviewed

~Thanks! Does that mean it's OK to publish now?~

Edit: I've confirmed yes 🙂

**Comment by andrewhayward** [comment]
Dev note for #54740 _(Misc Dev Notes)_:
- https://github.com/WordPress/gutenberg/pull/54740#issuecomment-1976297071

Dev note for #58620 _(Misc Dev Notes)_:
- https://github.com/WordPress/gutenberg/pull/58620#issuecomment-1976663196

**Comment by carolinan** [comment]
Is there no plans for a dev note for the pattern overrides?

**Comment by Leonardus-Nugraha** [comment]
@carolinan I didn't find PRs related to pattern overrides labelled 'needs dev note'. Could you help me point to that if any?

**Comment by mcsf** [comment]
> I didn't find PRs related to pattern overrides labelled 'needs dev note'. Could you help me point to that if any?

* Tracking issue: https://github.com/WordPress/gutenberg/issues/53705
* Recent change: https://github.com/WordPress/gutenberg/pull/58596

There is an active discussion going on on aspects of the feature and its API which needs to be settled before the appropriate dev note can be finalised.

**Comment by jorgefilipecosta** [comment]
Dev note for footnote support in all CPTs available at https://github.com/WordPress/gutenberg/pull/57353#issuecomment-1981059849.

**Comment by artemiomorales** [comment]
[Dev note for the Block Bindings API](https://make.wordpress.org/core/2024/03/06/new-feature-the-block-bindings-api/)
