### ISSUE TITLE
6.5: Quote block citation has additional spacing compared to 6.4.3.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#59164]
### Description

In 6.5 beta or with Gutenberg trunk active on 6.4.3, the spacing between the quote block text content and the citation is larger than in 6.4.3.

The cite element now has a 24px top margin from:

```
:where(body .is-layout-flow) > * {
	margin-block-start: 24px;
	margin-block-end: 0;
}
```

I'm not sure if this is an intended enhancement or bug fix, but it can be an unexpected change on live websites.
The block spacing setting correctly overrides this new spacing: it is the default spacing that is changed.

### Step-by-step reproduction instructions

Add a quote block on 6.4.3.
Note the spacing between the cite and the text content.
Activate Gutenberg or update to 6.5.
Compare the spacing between the versions.

### Screenshots, screen recording, code snippet

6.4.3:
<img width="1510" alt="Quote block cite in 6.4.3 has not top margin" src="https://github.com/WordPress/gutenberg/assets/7422055/81c4f245-f9e7-47b0-b022-c92e389a82fc">

6.5: / Gutenberg trunk
<img width="1510" alt="Quote block cite in 6.5 has top margin" src="https://github.com/WordPress/gutenberg/assets/7422055/bde1f3b9-e5a4-4d95-ad3b-cc2df53a3dc3">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aaronrobertshaw** [comment]
Thanks for flagging this @carolinan 👍 

As the CSS snippet highlights, this appears to be layout-related and is likely the result of the recent adoption of block spacing support for the Quote block in https://github.com/WordPress/gutenberg/pull/56064.

@tellthemachines and @andrewserong might have some insight on this one 🤞

**Comment by carolinan** [comment]
it still may be a non issue that can be covered by a misc. dev note...

**Comment by andrewserong** [comment]
Yes, I think a dev note should suffice — while it is a change on live sites, I think it's arguably a fix as it brings the spacing consistent with other blocks that use layout. I've added a draft dev note on the original PR over in https://github.com/WordPress/gutenberg/pull/56064#issuecomment-1953209301

**Comment by carolinan** [comment]
Even if it is a fix, it may be a change that theme developers need to compensate for: or remove their own custom spacing that may no longer be needed.

**Comment by carolinan** [comment]
I think we can close this! Thank you.
