### ISSUE TITLE
Issues with getEditorSettings to access theme default color or gradient palette

### ISSUE THREAD

**Issue by simom** [WordPress/gutenberg#59171]
### Description

I'm trying to read the theme color palette in a custom block using the editorStore. 
If there are no custom user colors, it returns the theme's default colors array (which is the expected behavior). 
However, if the user defines a custom color, it only returns the user's custom color without including all the theme defaults. 
Is this a bug, or is there another way to access this data?

In the `with-colors.js` component on Gutenberg there is a **useSettings** function, that appears to be private that read from:
```
'color.palette.custom',
'color.palette.theme',
'color.palette.default'
```

### Step-by-step reproduction instructions

import { store as editorStore } from '@wordpress/editor';
const { getEditorSettings } = select(editorStore);
const colors = getEditorSettings().colors;

### Environment info

- WordPress 6.4.3
- Default TT4 theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
The `useSettings` is a [new hook and will ship with WP 6.5](https://github.com/WordPress/gutenberg/issues/55337). Meanwhile, you can use the `useSetting` hook, imported from the `@wordpress/block-editor` package.

**Comment by simom** [comment]
thank you @Mamaduka for the information!

By the way, concerning the first question for the const colors = getEditorSettings().colors is it the expected behavior to return only the user custom color if defined?

**Comment by Mamaduka** [comment]
@simom, IIRC, that's the correct behavior; those settings are coming from the server when the editor loads - https://github.com/WordPress/wordpress-develop/blob/6.4/src/wp-includes/block-editor.php#L555-L565.

**Comment by simom** [comment]
Ok thank you for your help!
