### ISSUE TITLE
Enqueuing a script with `wp-edit-post` as a dependency breaks the editor

### ISSUE THREAD

**Issue by themeblvd** [WordPress/gutenberg#5918]
## Issue Overview
When I enqueue any script (could be just a blank `.js` file) which uses `wp-edit-post` as a dependency so I can get access to the new `wp.editPost.__experimental` API, the editor breaks and I receive the error:

	Uncaught Error: Target container is not a DOM element.

Admittedly, I'm new to a lot of this; so I apologize if I'm doing something completely wrong here, but it seems like a potential bug. With that said, I've done my best to isolate what I see as the issue as simply as possible. When installing the following plugin on a site with nothing but TwentySeventeen and Gutenberg, the editor breaks and gives me the error.

https://github.com/themeblvd/my-plugin

## Steps to Reproduce (for bugs)
1. Hook to `enqueue_block_editor_assets` or `enqueue_block_assets` and enqueue a JavaScript file.
2. When enqueuing the script, add `wp-edit-post` as a dependency. 

Note: I'm using the latest version of Google Chrome browser, WordPress 4.9.4, and Gutenberg 2.5.0 (from wp.org plugin repo).

## Screenshots

<img width="1580" alt="screen shot 2018-03-31 at 2 15 03 pm" src="https://user-images.githubusercontent.com/1952287/38167275-cd4ff480-34ef-11e8-8243-85278432c411.png">

**Comment by youknowriad** [comment]
Did you load the script on the footer? make sure you add `true` the the last param of your enqueue script. This ensures the javascript is only executed once the DOM is ready.

**Comment by themeblvd** [comment]
@youknowriad No I did not... And adding that of course fixes it. I had a feeling I was doing something stupid. Thanks!

**Comment by youknowriad** [comment]
No problem, this issue could be useful for others
