### ISSUE TITLE
Inconsistency with showing + icon on block library

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#5919]
In the various states of the block library you either see the + or don't. I would suggest it should show for all states perhaps?

![2018-04-01 at 13 00](https://user-images.githubusercontent.com/253067/38172922-ee7f3892-35ac-11e8-89ba-d8d64a3faec0.png)

**Comment by mtias** [comment]
This is not related to inserter states, but the button that opens it. I believe the cases where it's not shown is because the hover style on the trailing inserter don't apply when the inserter is opened.

**Comment by karmatosed** [comment]
The bit that confuses is not showing on a selected tab like Blocks but not showing on Shared or search. I'd be down with either not showing on all of those or showing.

**Comment by vishalkakadiya** [comment]
![issue-5919](https://user-images.githubusercontent.com/9035925/38218448-7caba8ec-36ef-11e8-97e7-eccce38c22b6.png)
@karmatosed @mtias I have open PR #5934  for showing all with same opacity when the search box is in the focus.

**Comment by vishalkakadiya** [comment]
@karmatosed Let me know if we need reverse of my solution means when the search box is in focus, we don't want to show all icons at all.

Thanks!

**Comment by vishalkakadiya** [comment]
@karmatosed That PR will solve an issue for all states, and as per my debugging it looks like opacity issue only.

**Comment by vishalkakadiya** [comment]
@karmatosed @mtias Let me know if any updates needed on my PR, I will do updates on right away. Thanks!

**Comment by vishalkakadiya** [comment]
@karmatosed  https://github.com/WordPress/gutenberg/pull/6090 is the refreshed PR for it. Thanks!

**Comment by karmatosed** [comment]
Closing as this has now been added, thanks!
