### ISSUE TITLE
RichText doesn't allow typing if these is a placeholder present.

### ISSUE THREAD

**Issue by Mgrmjp** [WordPress/gutenberg#59192]
### Description

In a custom Gutenberg blog importing RichText and using it doesn't allow for typing at all. The cursor blinks and onChange always returns empty. On PlainText no issues.

### Step-by-step reproduction instructions

Use RichText in a block:

                            el(RichText, {
                                tagName: "span",
                                className: "name",
                                // style: { display: 'flex' },
                                value: attributes.name || '',
                                onChange: value => {
                                    setAttributes({ name: value })
                                },
                                placeholder: __('Nimi', 'ID'),
                            }),

Set a placeholder.

Render block on editor

Click on the text that has placeholder present.

Try to write.

Doesn't do anything.

----------------------

Could be something in the older style of blocks, but can't really change everything in an older theme.

### Screenshots, screen recording, code snippet

![richtext](https://github.com/WordPress/gutenberg/assets/25221891/747c6c3a-815b-4b29-bbf4-b927e450991c)

### Environment info

Problem on Chrome at least.

WordPress 6.4.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @Mgrmjp,

Does the problem occur even if you change to the default theme and disable all plugins? I have tried code like below and it seems to work correctly.

```javascript
wp.blocks.registerBlockType( 'test/test', {
	title: 'Test',
	attributes: {
		name: {
			type: 'string',
		},
	},
	edit: ( { attributes, setAttributes } ) => {
		return wp.element.createElement( wp.blockEditor.RichText, {
			tagName: 'span',
			className: 'name',
			value: attributes.value || '',
			onChange: value => {
				setAttributes( { name: name } );
			},
			placeholder: 'Nimi',
		} );
	},
} );
```

https://github.com/WordPress/gutenberg/assets/54422211/c502d25b-78f3-4736-b64b-a20ee6d6bc8c

**Comment by fabiankaegy** [comment]
Hey all 👋 

I am also running into this constantly and did a little more digging. Turns iut the issue happens whenever the `RichText` element has `display: flex;` applied via styling. 

When flex styling is applied the placeholder text which is a `span` still exists. But the `contenteditable` element has no size. So it is not clickable. 

@ellatrix would love to gain your insights where whether you've encountered this before.

**Comment by ellatrix** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/59473
