### ISSUE TITLE
Show first run pointers for inserter and post settings

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#592]
For when you use the new editor the first time, we should use standard WordPress pointers to point out new features.

1. Probably point to the inserter in the toolbar. With or without a label, people might not immediately intuit that this is also where images live now. 

2. Point to the Post Settings button the first time you dismiss the sidebar, letting people know how to get it back.

**Comment by karmatosed** [comment]
We should do some tests to see if pointers are enough, I have personal doubts if they are and would like to prove or disprove them.

**Comment by mtias** [comment]
Closing in favor of #2176.
