### ISSUE TITLE
Site Editor: uploading an image in featured image placeholder doesn't show loading state similar to Images

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#59222]
Using 6.5 beta 2, I noticed that when I drag and drop an image to upload it to the featured image slot, I don't get a loading state similar to what you see with an image. As a result, for larger images, it makes it seem as though the image isn't being uploaded:

**Featured image in Site Editor:** 

https://github.com/WordPress/gutenberg/assets/26996883/990380ae-17d1-49af-92bc-4ae2dedc7614

**Image block in Site Editor:**

https://github.com/WordPress/gutenberg/assets/26996883/29207812-9e1c-4a78-a9b5-4b1170c0ddb5

This inconsistency makes for a confusing UX and I don't see why it should be such a different experience.

**Comment by t-hamano** [comment]
This improvement may also be applicable to the Site Logo block and Cover block.


https://github.com/WordPress/gutenberg/assets/54422211/395afb77-496f-4c2a-bd8f-ea25a33d44cc

**Comment by akasunil** [comment]
@t-hamano Cover block already have loader on image upload. Its not visible properly due to inner paragraph block placeholder. Should we add some overlay like image block for loading state ?

**Comment by t-hamano** [comment]
Thank you for investigating!

> Should we add some overlay like image block for loading state ?

Yes, I think that similar to the Image block, the semi-transparent image should be displayed during upload. Looking at the code briefly, it appears that the CSS for displaying the image based on the temporary URL and for making them semi-transparent is missing.

**Comment by akasunil** [comment]
Thank you, @t-hamano, for responding. I have modified PR accordingly. It's ready for review.
