### ISSUE TITLE
Empty image block can show scroll bar at some sizes

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#59226]
### Description

An image block in its empty state can show a scroll bar at some sizes:
![Screenshot 2024-02-21 at 11 48 24 am](https://github.com/WordPress/gutenberg/assets/677833/f548646a-654b-4521-9aa3-03504a4db10f)

This seems to happen whenever the placeholder content doesn't fit in the available space:
![Screenshot 2024-02-21 at 11 51 05 am](https://github.com/WordPress/gutenberg/assets/677833/aaf9511f-f5f6-4c8d-a60f-07cae209e38b)

But this scrollbar shouldn't really display when the block isn't selected.

### Step-by-step reproduction instructions

It seems easiest to produce with the 'Team members' pattern that's included with WordPress 6.4/6.5 by default.

1. Insert that pattern
2. Resize the viewport until the scrollbars appear

### Environment info

Mac OS / Brave

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hanneslsm** [comment]
> This seems to happen whenever the placeholder content doesn't fit in the available space

Related: https://github.com/WordPress/gutenberg/issues/55618

**Comment by torounit** [comment]
<img width="1030" alt="スクリーンショット 2024-02-23 15 55 45" src="https://github.com/WordPress/gutenberg/assets/1908815/5a2e02a4-bb8f-4831-9308-b83ec5569834">

Reproduced on Chrome on Mac.

We were able to reproduce a browser width between 783px and 1073px.
