### ISSUE TITLE
Add the option target = "_ blank"

### ISSUE THREAD

**Issue by iescuer** [WordPress/gutenberg#5923]
The target = "_ blank" option that we always use when we add a link, is no longer available. It should leave a checkbox when we introduce the link, giving us the possibility to decide if we want it to open in a new window.

![imagen1](https://user-images.githubusercontent.com/6759889/38191043-4b9fdf76-3667-11e8-93de-7fd3ac946d01.jpg)

Thank you

**Comment by StaggerLeee** [comment]
Just yesterday realised new Google Beta Webmaster Tool opens links in new tab. I don't know where it comes what Gutenberg core developers claim it is not popular and used much in real life.

**Comment by karmatosed** [comment]
Closing as this is happening as part of: https://github.com/WordPress/gutenberg/issues/4572
