### ISSUE TITLE
New mariadb version breaks @wordpress/env funcionality

### ISSUE THREAD

**Issue by angcl** [WordPress/gutenberg#59244]
### Description

Since the release of a new mariadb docker image, starting an environment over @wordpress/env doesn't work anymore.

# Workaround
Change mariadb images in `build-docker-compose-config.js` from `mariadb` to a prior version like `mariadb:10.3`

# Suggestion
Make mariadb version selectable and default to a reasonable version, not latest.

### Step-by-step reproduction instructions

1. mkdir new-project
2. cd new-project
3. npm init -y
4. npm install @wordpress/env --save-dev
5. create a .wp-env.json file
6. npx wp-env start

### Screenshots, screen recording, code snippet

❯ npx wp-env start
✖ Error while running docker compose command.
Container 879c0e8cf3a66537f687a6eca145da4c-tests-mysql-1  Running
Container 879c0e8cf3a66537f687a6eca145da4c-tests-wordpress-1  Running
Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or that contact with the database server at `tests-mysql` could not be established. This could mean your host’s database server is down.

### Environment info

macOS 14.2.1
Docker version 20.10.23, build 7155243
v20.11.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This issue is reported in #59232. This issue was fixed in #59237 and will be fixed in the next npm package update.

**Comment by erikdemarco** [comment]
this issue still exist on latest wp-env. the only way to fix this currently is following this instruction:
https://stackoverflow.com/a/78037703
