### ISSUE TITLE
[WP6.5] Top Toolbar: Toggle does not work as expected when title or block is selected

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#59263]
### Description

The top block toolbar is expected to open the closed block toolbar when a new block is selected, as mentioned in the comments below.

https://github.com/WordPress/gutenberg/blob/9a8984afb45df1635b2a5048b33e8ab9f95bff27/packages/edit-post/src/components/header/index.js#L93

However, the following two problems occur in the post editor.

- Selecting a new block does not open the block toolbar
- Vertical separator appears in the header when clicking title with block toolbar open

This issue does not occur in WP6.4, so I believe it is a regression occurring in WP6.5 or the latest Gutenberg.

### Step-by-step reproduction instructions

- Open the post editor and insert multiple paragraph blocks.
- Enable "Top tooplbar".
- Select one paragraph block. The block toolbar should now be open.
- Close the block toolbar.
- Select another paragraph block.
- ❌ The block toolbar should not open.
- With the block toolbar open, click the post title.
- ❌ A vertical separator should appear in the header.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/5956a7b9-2175-41cd-8193-223122d8e1cb

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
~~Can you reproduce this on the latest Gutenberg trunk?~~

I can reproduce it. I think there's an bug with sync logic.

**Comment by t-hamano** [comment]
>Can you reproduce this on the latest Gutenberg trunk?

Yes. I think that the cause is that the logic is slightly different between the post editor and the site editor, and I'm investigating...

Post Editor:

https://github.com/WordPress/gutenberg/blob/efe7d2e698bc0e19ad5723046658100774ae967a/packages/edit-post/src/components/header/index.js#L92-L97

Site Editor:

https://github.com/WordPress/gutenberg/blob/efe7d2e698bc0e19ad5723046658100774ae967a/packages/edit-site/src/components/header-edit-mode/index.js#L95-L100

**Comment by Mamaduka** [comment]
I think I've a solution, will push PR shortly.
