### ISSUE TITLE
Custom Post hierarchical Taxonomy panel not showing for admin

### ISSUE THREAD

**Issue by carmemias** [WordPress/gutenberg#5926]
## Issue Overview
We are working on an Event Custom Post Type plugin and the taxonomy panel does not appear in the New/Edit screen when using Gutenberg and logged in as Administrator.
It does show OK on the Classic Editor, in Quick Edit and for Posts.

The taxonomy definition is as follows: 
```
add_action( 'init', __NAMESPACE__ . '\event_cpt_functionality' );
/**
 * Register CPT `event_event`
 */
 function event_cpt_functionality() { 
	$features = get_all_post_type_features('post', array( 
		'trackbacks',
		'custom-fields',
		'revisions',
		'author',
		'post-formats',
		'comments',
		'excerpt'
	));
	register_post_type( 'event_cpt', array(
		'labels'  => array(
			'name' => __( 'Events', 'Events CPT general name' , 'events-functionality'),
			'singular_name' => __( 'Event', 'Events CPT singular name' , 'events-functionality'),
			'all_items' => __('All Events'),
 		    'add_new_item' => __('Add New Event', 'events-functionality'),
 		    'edit_item' => __('Edit Event', 'events-functionality'),
 		    'new_item' => __('New Event', 'events-functionality'),
			'view_item' => __('View Event', 'events-functionality'),
			'featured_image' => __('Event image', 'events-functionality'),
			'set_featured_image' => __('Choose Event image', 'events-functionality'),
			'remove_featured_image' => __('Remove Event image', 'events-functionality'),
			'use_featured_image' => __('Use Event image', 'events-functionality'),
 		    'view_items' => __('View Events', 'events-functionality'),
 		    'search_items' => __('Search Event', 'events-functionality'),
 		    'not_found' => __( 'No Events found.', 'events-functionality' ),
			'not_found_in_trash' => __( 'No Events found in Trash.', 'events-functionality' ),
		),
		'show_in_rest'    => true,
		'rest_base'    => 'events',
		'rest_controller_class' => 'WP_REST_Posts_Controller',
		'public' => true,
		'show_ui' => true,
		'has_archive' => true, 
		'rewrite' => array(
			'slug' => __( 'events', 'CPT permalink slug', 'event_cpt'),
			'with_front' => false,
		),
		'menu_icon'   => 'dashicons-images-alt2',
		'menu_position' => 20,
		'supports' => $features, 
		'taxonomies' => array('event-type'),
		'register_meta_box_cb' => __NAMESPACE__.'\events_cpt_add_meta_box'
	));
	register_taxonomy('event-type', 'event_cpt', array(
		'hierarchical' => true,
		'show_in_nav_menus' => false,
		'show_in_rest' => true,
		'rest_base' => 'eventtypes',
		'rest_control_class' => 'WP_REST_Terms_Controller',
		'labels' => array(
			'name' => __('Event types'),
			'singular_name' => __('Event type'),
			'all_items' => __('All Event types'),
			'edit_item' => __('Edit Event type'),
			'view_item' => __('View Event type'),
			'update_item' => __('Update Event type'),
			'add_new_item' => __('Add new Event type'),
			'new_item_name' => __('New Event type'),
			'popular_items' => __('Most used Event types'),
			'separate_items_with_commas' => __('Separate Event types with commas'),
			'add_or_remove_items' => __('Add or remove Event types'),
			'choose_from_most_used' => __('Choose from most used Event types'),
		)
	) ); 
}
/**
* Get all the post type features for the given post type
* @param string $post_type - given post type
* @param array $exclude_features - array of features to exclude
* @return array
**/
function get_all_post_type_features($post_type = 'post', $excluded_features = array()){
	#see https://knowthecode.io/labs/custom-post-type-basics#configure-features
	$raw_features = get_all_post_type_supports($post_type);
	if(!$excluded_features){return array_keys($raw_features);}
	$included_features = array();
	foreach($raw_features as $key => $value){
		if(!in_array($key, $excluded_features)){
			$included_features[]=$key;
		}
	}
	return $included_features;
}
add_filter( 'post_updated_messages',  __NAMESPACE__ . '\event_cpt_updated_messages' );
```

The plugin can be found here: https://github.com/CodeYourFuture/src-website/blob/master/plugins/events_plugin/ 

## Steps to Reproduce (for bugs)

1. Login to WordPress site
2. Install and activate the Events Plugin
3. Click New Event
4. Look to assign an Event Type

We are using a Docker localhost, with WordPress 4.9.4, Gutenberg 2.5.0 and the Event Plugin as the only active plugins.
This has been reproduced in both Firefox(59.0.2) and Chrome(65.0.3325.181)

## Expected Behavior

The Event Type panel should show above the Event Image Panel.

## Current Behavior

The Event Type panel does not show at all. No error message appears in the console.

## Screenshots / Video

Event Type panel does not show for New/Edit Event in Gutenberg:
<img width="281" alt="new event screen with gutenberg" src="https://user-images.githubusercontent.com/10561810/38189891-dc823ce0-3659-11e8-9e7a-fb795b9dd4db.png">

Event Type panel show OK for New/Edit Event in Classic Editor:
<img width="289" alt="new event screen in classic editor" src="https://user-images.githubusercontent.com/10561810/38189890-dc68b25c-3659-11e8-9610-fa796a3fc852.png">

Category panel shows OK for New/Edit Post in Gutenberg:
<img width="280" alt="new post screen in gutenberg" src="https://user-images.githubusercontent.com/10561810/38189892-dc9e04f2-3659-11e8-8e4a-d30377c857d2.png">

## Related Issues and/or PRs

In our case, the problem occurs when logged in a administrator but the closest issue I have found seems to be #4787

**Comment by MikeB8s** [comment]
This seems to be an issue discussed here: [https://core.trac.wordpress.org/ticket/42785]

**Comment by carmemias** [comment]
Hi there,
The problem is not related to the REST API as it all shows OK there, but to the main Edit/New Post screen in the Dashboard.

**Comment by MikeB8s** [comment]
Ok, I see.  I have to read more carefully.  Thanks for the quick update

**Comment by carmemias** [comment]
Thank you for looking into it!On 10 Apr 2018 08:07, MikeB8s <notifications@github.com> wrote:Ok, I see.  I have to read more carefully.  Thanks for the quick update

**Comment by carmemias** [comment]
Actually, this now works OK. The problem does not occur anymore.

Thanks again for looking into it.
