### ISSUE TITLE
Can't find info on submitting notices to Gutenberg

### ISSUE THREAD

**Issue by jsmoriss** [WordPress/gutenberg#5927]
I can't find any information on how to submit notices to Gutenberg. Would anyone be willing to share some insight? :) The code I'm working with so far is:

```
var editPost = wp.data.select( 'core/edit-post' ), lastIsSaving = false;

wp.data.subscribe( function() {
        var isSaving = editPost.isSavingMetaBoxes();
        if ( isSaving !== lastIsSaving && !isSaving ) {
                lastIsSaving = isSaving;

                // TODO: ajax call to get metabox HTML

                // TODO: refresh the metabox container

                // TODO: ajax call to get the notices array

                // TODO: submit notices to Gutenberg for display

        }
        lastIsSaving = isSaving;
} );
```

Thanks, :)

js.

**Comment by danielbachhuber** [comment]
> I can't find any information on how to submit notices to Gutenberg.

Just to clarify, can you share a bit more detail on what you're trying to do?

**Comment by jsmoriss** [comment]
I must perform an ajax call to update a metabox after a post is updated by Gutenberg. This metabox displays status info and gather information from a variety of locations / sources. Some info may be missing or incorrect, which generates notices (error, warning, or info types). So, after getting the metabox HTML, updating the metabox container, I need to retrieve any notices and pass them to Gutenberg for display. There is no information, that I could find, on how I might do this. :)

Thanks,

js.

**Comment by danielbachhuber** [comment]
> I need to retrieve any notices and pass them to Gutenberg for display. There is no information, that I could find, on how I might do this. :)

Makes sense. There isn't a formal notices API yet, so that's something we need to sort out first.

**Comment by danielbachhuber** [comment]
Closing in favor of #5975
