### ISSUE TITLE
Its possible to crash editor by calling `selectBlock` on a non-existent clientId

### ISSUE THREAD

**Issue by artpi** [WordPress/gutenberg#59289]
### Description

When the command palette is open and non-existant block is selected, `useTransformCommands` is passing an **non-empty** array of nulls which triggers an error in 
https://github.com/WordPress/gutenberg/blob/fc0917f8de3647bd2e01cdccab673efe45a37edd/packages/blocks/src/api/factory.js#L163

### A: Handle in block transforms

This would be similar solution that `getBlockNamesByClientId` is using here:

![Zrzut ekranu 2024-02-22 o 19 01 17](https://github.com/WordPress/gutenberg/assets/3775068/bc940386-e6a8-4b75-8cea-2633ad828b94)

https://github.com/WordPress/gutenberg/blob/fc0917f8de3647bd2e01cdccab673efe45a37edd/packages/block-editor/src/store/selectors.js#L408C4-L408C22

This `filter(Boolean)` would have to be introduced in `useTransformCommands`:

https://github.com/WordPress/gutenberg/blob/fc0917f8de3647bd2e01cdccab673efe45a37edd/packages/block-editor/src/components/use-block-commands/index.js#L41

### B: Filter right in `getBlocksByClientId`

It seems obvious to me that getBlocksByClientId should not return an array with a single null:

![Zrzut ekranu 2024-02-22 o 19 06 31](https://github.com/WordPress/gutenberg/assets/3775068/d6cb4f8f-0992-4bfa-bcc4-c2be9851267e)

We could filter right here:

https://github.com/WordPress/gutenberg/blob/fc0917f8de3647bd2e01cdccab673efe45a37edd/packages/block-editor/src/store/selectors.js#L385

I prefer that second solution because it prevents from the problem proliferating to other uses of this selector

## Is this really a bug? You are triggering stuff in console.

Yes, However `core/block-editor` store is a highly advertised integration point for external plugins and we can be certain that some developer will mistakenly try to select non-existant block.
This should fail gracefully.

### Step-by-step reproduction instructions

1. Open editor
2. Select any block
3. Open the Command pallette (Click at the top bar and do CMD+K or open the command palette )
4. Filter for "transforms" to see that they are there
5. Open console, trigger selecting non-existant block by `wp.data.dispatch('core/block-editor').selectBlock('non-existent-block-id', 1);`
6. Observe editor crash and burn.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/3775068/834fbe06-e96d-4a99-bb66-1718eadcabe3

### Environment info

Gutenberg v Version 17.7.0
WordPress.com Atomic
piszek.com

And other environments

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I also think that it should prevent the block editor from crashing, and that returning an array with `null` when the `getBlocksByClientId` parameter contains an invalid ID is not the expected behavior.

The `getBlocksByClientId`  is expected to return an array of type `WPBlock`, but looking at the type below, `null` should not be allowed.

https://github.com/WordPress/gutenberg/blob/908e3ed4b9ab61cfab4fd145d4da95a8865d4c13/packages/blocks/src/api/parser/index.js#L42-L50

**Comment by Mamaduka** [comment]
The `BlockSwitcher` checks the validity of blocks before rendering transformation options. It was introduced initially to solve a similar error - #28122.

I'm not against updating the `getBlocksByClientId`, but we should examine its usage in the code base in case any consumer relies on current behavior.

https://github.com/WordPress/gutenberg/blob/599f3365232316242a2f92d8fdb5a05e0b0accaa/packages/block-editor/src/components/block-switcher/index.js#L182-L184

**Comment by artpi** [comment]
For now I opened a PR with a spot remedy.

**Comment by t-hamano** [comment]
Fixed by #59410
