### ISSUE TITLE
Can't find a way to change the permalink.

### ISSUE THREAD

**Issue by jsmoriss** [WordPress/gutenberg#5928]
I can't seem to find a way to change the permalink of a post.

- When you click on the title block, there's a permalink you can click or copy, but not change.

- When you switch to published -> draft, same thing - click the title block and the permalink is available as a link or for copy, but not editing. BTW, this link is the shortlink - shouldn't this be the permalink??? The old editor would show the permalink, even for drafts, with a button to get the shortlink. I would prefer having an opportunity to modify the permalink, not the shortlink.

- When you publish the draft, the sidebar shows a "Published" sidebox with a "What's next?" input field for the permalink, but the permalink cannot be changed.

Changing the permalink should be a bit more obvious - I still haven't figured out how it's done in Gutenberg. lol. :)

js.

**Comment by chrisvanpatten** [comment]
It's coming soon! You can see the progress in #5756.

**Comment by danielbachhuber** [comment]
Closing in favor of #5756

**Comment by designsimply** [comment]
Quick note to say that https://github.com/WordPress/gutenberg/issues/1285 was the original report and that the permalink can now be edited (after the post or draft is saved).
