### ISSUE TITLE
Template Preview in post editor allows editing of fields that don't get saved anywhere

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#59291]
With the newly introduced ability to preview the template of a post within the post editor (https://github.com/WordPress/gutenberg/pull/56817) there are three blocks that get special treatment. The Post Title, Post Featured Image, and Post Content. 

All the other blocks get their block editing mode set to `disabled` whilst they retain the `default` mode. 

This is correct for the post content block. But the issue with the post title and post featured image is that they are not locked into `contentOnly` mode but still allow editing of all kinds of other tools such as the aspect ratio, font controls etc. Which apply fine in the editor but don't get reflected on the frontend since these changes don't get saved anywhere. 

https://github.com/WordPress/gutenberg/blob/fc0917f8de3647bd2e01cdccab673efe45a37edd/packages/editor/src/components/provider/disable-non-page-content-blocks.js#L1-L55

https://github.com/WordPress/gutenberg/assets/20684594/ff1e5bfa-40f0-4c83-b33d-ec264a138fe2

**Comment by colorful-tones** [comment]
Great testing and find. This is certainly some odd behavior we should prioritize with a fix.
