### ISSUE TITLE
Add ability to mark block as post content

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#59290]
When the block editing mode is set to `template-lock` the template is rendered but all the blocks that are within the template have their block editing mode set to `disabled`.

All except for the post title, post featured image, and post content blocks. 

These are hardcoded into a constant here:

https://github.com/WordPress/gutenberg/blob/d969294162b9d6ce84e920d752ea738157a8c1b2/packages/editor/src/components/provider/disable-non-page-content-blocks.js#L8-L12

There are many ciscumstances where a 3rd party block also reads / writes data to the post object. Whether that is a meta field, a taxonomy or any other custom element. 

It would be great it there was a way to identify those blocks to get the same treatment as these three blocks. 

#### Proposed solutions

Maybe a block support would make sense here 🤔

```jsonc
{
    "version": 2,
    "name": "namespace/event-location",
    "title": "Event Location",
    "supports": {
        "postContent": true // very open to other names for this
    }
}
```

The idea would be that a block can flag that it saves something to the post instead of only saving to local attributes.

**Comment by fabiankaegy** [comment]
@youknowriad I'd love to get your take on solving this issue with a block support vs a filter / some other approach. Very open to suggestions :)

**Comment by Mamaduka** [comment]
Makes sense. Developers should be able to mark blocks that qualify as page content for their projects.

cc @noisysocks

**Comment by noisysocks** [comment]
I'm not sure that a block should care too much about the intricacies of post editing in the site editor. Block are pretty foundational after all. They're often used outside of WordPress, even. 

I think I'm more inclined to allow customising this list via a filter.

**Comment by fabiankaegy** [comment]
Thanks for those insights. @noisysocks as per your suggestion I created a PR that adds a filter to allow overwriting the list: #60068
