### ISSUE TITLE
Site Editor: Add a screen for adding or uploading a site logo / favicon

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#59298]
## What problem does this address?

Currently, in the site editor, if a user wishes to use a site icon / favicon that is different to what's used by the Site Logo block, there is a link to direct users over to the customizer in order to update it. It would be nicer if there were a dedicated part of the site editor for adding / updating site icons explicitly, rather than using the customizer. Here is how it currently looks:

| Site Logo block controls | They redirect to the Customizer page |
| --- | --- |
| ![image](https://github.com/WordPress/gutenberg/assets/14988353/88566772-0e87-4c91-9607-c9eec7c72321) | ![image](https://github.com/WordPress/gutenberg/assets/14988353/b7e35a54-aa56-4f37-bcbe-9a06d5de8ea0) |

## What is your proposed solution?

Add a separate page / screen to the left-hand navigation of the site editor's browse mode for adding or updating site icons.

Note: as of WordPress 6.5, there will be the ability for folks to update the site icon from the general settings page of wp-admin (see trac ticket: https://core.trac.wordpress.org/ticket/54370) — this may or may not influence whether or not there should be a corresponding section in the site editor. (I.e. maybe it's fine if we're linking folks to go to the general settings page)

## A few questions

* What would the menu item be called?
* Which controls would be available within the screen? I.e. would it just be for the site logo, or would it also include other controls for site title, tagline, etc?

An extremely quick mockup of an extra item on the left hand panel to indicate which area I mean:

<img width="744" alt="image" src="https://github.com/WordPress/gutenberg/assets/14988353/0b1e3b0a-86f6-4e5c-af38-19891cc6cd3b">

I couldn't find an existing issue for this exactly, so if there is one, let me know and I'll close this out as a duplicate!

**Comment by bgardner** [comment]
Would this complement the new UI on the General Settings page?

https://twitter.com/bgardner/status/1761077710426710038

**Comment by ResponsiveFlow** [comment]
> Would this complement the new UI on the General Settings page?

I think so.
As more things are placed in the site editor, I don't see why not adding the favicon as well.
The new UI in General Settings works fine, especially for those who are not using a block theme yet.

Also, what do you think about using the favicon/logo to replace the WP logo in wp-login?

**Comment by andrewserong** [comment]
Thanks folks, I hadn't seen that!

> Would this complement the new UI on the General Settings page?

I'd think so — the main idea behind this issue is that it'd be good for folks not to have to leave the site editor in order to make changes.

**Comment by andrewserong** [comment]
Just linking the trac ticket for the site icon in the general settings page: https://core.trac.wordpress.org/ticket/54370

**Comment by hanneslsm** [comment]
> I couldn't find an existing issue for this exactly, so if there is one, let me know and I'll close this out as a duplicate!
 
I think the previous discussion would be this https://github.com/WordPress/gutenberg/issues/50860 but it didn't go into details and solutions.

@jameskoster made a note for "global settings", which I like better than "Site identity". ("Site identity" and "Styles" would be too close)

**Comment by annezazu** [comment]
This is a duplicate IMO of https://github.com/WordPress/gutenberg/issues/50860. Going to close this out as a result and let's continue the discussion there. @andrewserong  please add your thoughts as a comment!
