### ISSUE TITLE
Update default "Hello World" first post with blocks

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#593]
Every new WordPress site is born with a Hello World post. What better time to update this, than when a wild new editor appears? 

We can't for sure know that this is in the cards. But it's a fun design challenge. What would a showcase "Hello World" post from a brand new WordPress install look like, in a block world?

**Comment by melchoyce** [comment]
Cool idea :) 

Related: https://core.trac.wordpress.org/ticket/34116

**Comment by westonruter** [comment]
Also closely related to theme starter content. We should be thinking of blocks in the context of page layouts for Twenty Eighteen.

**Comment by mtias** [comment]
@westonruter blocks will have a state for when they are empty, which means we can do all sort of cool stuff by having block slots in place ready to be filled.

**Comment by jasmussen** [comment]
> blocks will have a state for when they are empty, which means we can do all sort of cool stuff by having block slots in place ready to be filled.

Here's a quick and dirty example of what that might look like. Not in the near future, mind you, just dreaming here:

![post template quick and dirty](https://cloud.githubusercontent.com/assets/1204802/25695436/6892e520-30b3-11e7-9a5a-35b6f0ffc0ca.png)

**Comment by mtias** [comment]
Closing this as it'd be a separate thing from Gutenberg if we were to do this.
