### ISSUE TITLE
Third party builders and the future of blocks

### ISSUE THREAD

**Issue by mikka23** [WordPress/gutenberg#5930]
Okay, so this might seem a bit of a weird place to place - since this is the Gutenberg repo.  However, this is a question which I have that doesn't seem to be clear to resolve.  Gutenberg will bring along with it blocks for content, which will provide a method for plugins to add their elements in a single WP core manner.  This is great and is something which third party builders like Elementor, Divi, Cornerstone, VC etc **could** benefit from.

What are the plans for this on the WP Core side of things?  By that I mean, is there going to be API and functionality added which will allow third party builders to use block elements and components?  For example, a method of using the render and control options for elements within a separate front-end builder.

Right now this is very unclear what is going to happen.  It doesn't seem possible to utilize the blocks outside of Gutenberg (or at least not simply).  It also doesn't seem to be something that is being looked into or thought about.  However if blocks are entirely tied into Gutenberg then it effectively breaks the third party builder market (which some people may be happy about, but I am not one of them).  Gutenberg will have to progress a long way before it is the solution to the entire editing experience.  Until that happens, what is the expected future for third party builders and utilization of blocks?

**Comment by jasmussen** [comment]
Good thoughts. But I'm not sure the issues list here is the best place to post thoughts. Ideally we only have specifically actionable tickets, and any questions around Gutenberg are best shared directly with us all in Slack (https://make.wordpress.org/chat/), channel #core-editor. I say this not to discourage asking these questions, quite the opposite — it's just a higher bandwidth of communication there, and a bigger chance of receiving a good response.

**Comment by mikka23** [comment]
@jasmussen that is true, however I have actually tried to ask in the Slack channel already.  Obviously its a lot easier to miss in there so I don't really blame anyone for lack of response.  I thought it would reach more people if posted here (although if discussion is taking place Slack will be much better).

**Comment by jasmussen** [comment]
Sorry to see that you didn't get a response or that it drowned — we're trying to do a little repo management to bring down the number from 600+ open tickets to just actionable items, and ironically this, via bots, has also drowned out some of the slack. 

Can you post the question again, ping me directly (@joen), and then I can hopefully amplify the question? 

Thanks. Mind if I close this one, btw?

**Comment by mikka23** [comment]
Sure

**Comment by jasmussen** [comment]
Thanks. Going to try and amplify in Slack.

**Comment by gziolo** [comment]
More info also on WordPress Slack: https://wordpress.slack.com/archives/C02QB2JS7/p1522755483000116.
