### ISSUE TITLE
Copy and Paste in Title duplicates it

### ISSUE THREAD

**Issue by michakrapp** [WordPress/gutenberg#59323]
### Description

Seems like Safari only.

When you try to copy or paste in the title block with the key combination, it copies or pastes the whole title.

Could even be replicated in the WordPress Playground.

### Step-by-step reproduction instructions

(only on Safari)
1. Go to Admin -> Posts -> Edit Post
2. Copy a word/text from content with keys (cmd + c) and try to paste it in the title with keys (cmd + v) (image 1)
3. Now the text gets pasted, BUT also the whole title got duplicated (image 2)
4. Paste with right-click and select "paste" from the popup-menu does it correctly (image 3)

Also the same with copy. Try to copy something in the title with keys (cmd + c) copies the whole title

### Screenshots, screen recording, code snippet

<img width="1620" alt="Bildschirmfoto 2024-02-23 um 17 32 22" src="https://github.com/WordPress/gutenberg/assets/5496691/3c72c399-418f-4e11-af1a-56d9f922ee9f">
<img width="1620" alt="Bildschirmfoto 2024-02-23 um 17 32 38" src="https://github.com/WordPress/gutenberg/assets/5496691/73dba3b4-2e52-4192-838c-327067f77c3e">
<img width="1620" alt="Bildschirmfoto 2024-02-23 um 17 32 54" src="https://github.com/WordPress/gutenberg/assets/5496691/cba355f2-cf13-4868-9c32-af541b46bc7c">

### Environment info

Safari (16.6)
WordPress 6.4.3 (all tested sites and playground had this version)
PHP 8.0 & PHP 8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MatzeKitt** [comment]
This is already reported here: https://github.com/WordPress/gutenberg/issues/51047

**Comment by t-hamano** [comment]
Thanks for the report. I will close this issue as a duplicate.

**Comment by michakrapp** [comment]
Closed as duplicate of https://github.com/WordPress/gutenberg/issues/51047
