### ISSUE TITLE
Improving zoom out with patterns

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#59336]
The layout for Zoom Out mode when the pattern inserter is open could be quite improved. This issue will be referenced by several PRs working towards making the zoom out mode with pattern inserter flow accessible and smooth.

### Context

Engaging the zoom-out Gutenberg experiment with the inserter open causes the pattern categories to overlap over the content. It's difficult to add patterns if you can't see where you're adding them. 

Other improvements would be to have the patterns inserter remain open when inserting patterns (like it does outside of zoom-out mode), as well as consider improving the pattern quick inserter when in this view.  

Note that this UI already exists in the form of a Gutenberg experiment. I am proposing refining this experimental view. 

![Site editor in zoom out mode with pattern inserter open and full site editor unobstructed by pattern sidebar inserter](https://github.com/WordPress/gutenberg/assets/967608/dd303308-8603-4e95-9159-0bcc75fe83de)

Related to https://github.com/WordPress/gutenberg/issues/50739 and https://github.com/WordPress/gutenberg/issues/39281. 

co-authored with @richtabor

**Comment by richtabor** [comment]
@jeryj I think we can consider this closed by https://github.com/WordPress/gutenberg/pull/59342 and https://github.com/WordPress/gutenberg/pull/59337, with follow-ups on the [zoom-out overview issue](https://github.com/WordPress/gutenberg/issues/50739). Good work!
