### ISSUE TITLE
Block Editor: Gray background color appears behind theme background color

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#59348]
### Description

A gray background color is applied behind the theme background color in the post editor and site editor.

This background color appears to have been applied in #59334.

This issue does not occur with WP6.5, it occurs with the latest Gutenberg.

### Step-by-step reproduction instructions

Open the post editor or site editor.

### Post Editor

![post-editor](https://github.com/WordPress/gutenberg/assets/54422211/139d2adf-21cf-4bdc-8ddd-42f73485fb0f)

### Site Editor

![site-editor](https://github.com/WordPress/gutenberg/assets/54422211/1aea2353-4215-4e69-8084-d37de5bf580e)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Noting that I'm **not** adding this to the 6.5 board since it doesn't occur within the release but let's make sure whatever is causing this isn't backported for the next beta.
