### ISSUE TITLE
<FormTokenField> has links to outdated docu

### ISSUE THREAD

**Issue by helgatheviking** [WordPress/gutenberg#59343]
### Description

`<FormTokenField>` component docs include link to deprecated docs site in [readme](https://github.com/WordPress/gutenberg/blob/8265e4966b11898ce724d2d64a97ec2a3866da64/packages/components/src/form-token-field/README.md?plain=1#L7) and [index](https://github.com/WordPress/gutenberg/blob/8265e4966b11898ce724d2d64a97ec2a3866da64/packages/components/src/form-token-field/index.tsx#L43)

`http://facebook.github.io/react/docs/forms.html`

should be replaced with

`https://react.dev/reference/react-dom/components#form-components`

But it's also not entirely clear to me what I'm supposed to be seeing in the docu anyway. 
>The `value` property is handled in a manner similar to controlled form components.

What does that mean? What's the format of the value here? Is it an array of strings, an array of objects? Source suggests it can be an array of objects, but why when you add a token it's only ever adds a `string`?

### Step-by-step reproduction instructions

n/a

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by tellthemachines** [comment]
Thanks for opening this issue @helgatheviking ! The `value` property is explained [a few lines below](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/form-token-field/README.md#properties). Is there anything you think could be clarified further here?
