### ISSUE TITLE
Site Editor: Featured image and media are not linked correctly

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#59349]
### Description

In WP6.5, you can set a featured image from the page sidebar in the Site Editor. However, I have identified the following issues:

- "Empty" media is selected when the media library is opened, regardless of whether a featured image is selected
- Incorrect text indicating the number of media

### Step-by-step reproduction instructions

- Go to the Site Editor > Pages > {Page Name} > Block settings sidebar > Featured image.
- Click the "Set featured image".
- Empty media with no thumbnails is selected in the media library.
- The text "Showing X of Y media items" does not correctly display the number of media.

### Environment info

- WordPress Version: 6.5 Beta 2
- Gutenberg Version: 17.8.0-rc.2 (can be reproduced even if disabled)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
Given that RC1 is today I'm removing this one from 6.5 as non essential.

**Comment by t-hamano** [comment]
This issue was also reported in #59768 and appears to have been fixed in #59769.
