### ISSUE TITLE
Font Manager uses incorrect URLs on multisite 

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#59352]
### Description

The font library manager attempts to load fonts using incorrect URLs in the font-manager when using Multisite in sub-directory mode. 

In the console when I open the font manager model the Caro and Inter fonts attempt to load from the following URLs which throw 404 errors:

* http://gb-dev.local/two/wp-admin/undefined/wp-content/themes/twentytwentyfour/assets/fonts/cardo/cardo_normal_400.woff2
* http://gb-dev.local/two/wp-admin/undefined/wp-content/themes/twentytwentyfour/assets/fonts/inter/Inter-VariableFont_slnt,wght.woff2

Elsewhere in the site editor they appear to load from the correct URLs

WordPress installed in a sub-directory will also need to be tested. 

### Step-by-step reproduction instructions

_Edit: Creating a sub-site in not necessary, the issue occurs on the main site too._

1. Configure Multisite in sub-directory mode
2. Create a sub-site `/two/`
3. Visit `host/two/wp-admin/site-editor.php?canvas=edit`
4. Open the browser's developer tools, clear the console.
5. Open Styles > Typography > Manage Fonts
6. Observe the 404 errors in your browsers console or network tab

### Screenshots, screen recording, code snippet

![Screen Shot 2024-02-26 at 12 55 33 pm](https://github.com/WordPress/gutenberg/assets/519727/4d29dd63-df88-4be1-873d-eb061bd9cbcb)

### Environment info

- WordPress 6.4
- Gutenberg trunk @ 4d5fd5a01f758d19568c885fadbc9b57ba30fb2d

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I was also able to reproduce this problem. A DOM exception error is occurring [here](https://github.com/WordPress/gutenberg/blob/4d5fd5a01f758d19568c885fadbc9b57ba30fb2d/packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js#L143), so there might be some problem with the `loadFontFaceInBrowser()` function.

**Comment by peterwilsoncc** [comment]
Thanks for the pointer @t-hamano, I worked backwards to find the source

It appears there are assumptions about the theme URL being made in this code that are incorrect

https://github.com/WordPress/gutenberg/blob/4d5fd5a01f758d19568c885fadbc9b57ba30fb2d/packages/edit-site/src/components/global-styles/font-library-modal/context.js#L172-L173

The `WP_CONTENT_DIR` and `WP_CONTENT_URL` constants can be used to set the content directories to be pretty much anything so `site.url` can't be used to get a predictable result.

The JavaScript equivalents of `get_stylesheet_directory_uri()` and `get_stylesheet_directory_uri()` will need to be used for this purpose. if the data is not available in the theme's rest controller then the data will need to be added in another manner.

**Comment by peterwilsoncc** [comment]
I've confirmed this is happening on Single Site installs with custom directory set ups.

![Screen Shot 2024-02-27 at 9 39 30 am](https://github.com/WordPress/gutenberg/assets/519727/13d6cc63-a503-4eeb-a789-9675b3d87e38)

**Comment by swissspidy** [comment]
Hardcoding URLs like that is definitely incorrect and needs to be addressed

**Comment by matiasbenedetto** [comment]
Here's a potential fix for this issue: https://github.com/WordPress/gutenberg/pull/59421
