### ISSUE TITLE
Anchors on List Items

### ISSUE THREAD

**Issue by ejnwebmaster** [WordPress/gutenberg#59351]
### Description

As far as I can tell, the official definition of \<li\> includes the ID attribute, but this is not implemented, and indeed is rejected by WP and the Gutenberg editor, even when I add it as custom HTML.

https://www.w3.org/TR/2012/WD-html-markup-20121025/global-attributes.html

### Step-by-step reproduction instructions

Select any list item, not the whole list group.  There will be no ability to add an anchor to a list item, and attempting to add an anchor (I used a single digit number reflecting a footnote reference) is rejected when converting back to "edit visually".

### Environment info

I'm using the latest version of everything as of February 2024 in a Chrome browser in Windows 10.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Thanks for reporting; 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/29838. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
