### ISSUE TITLE
Add container divs for each column in the Columns block

### ISSUE THREAD

**Issue by paulwilde** [WordPress/gutenberg#5935]
The current way that the columns HTML is saved makes it impossible to style if you aren't using [CSS Grid](https://caniuse.com/#feat=css-grid). Whist browser support for CSS Grid is decent, it's not good enough when dealing with particular clients (An example being the NHS in the UK).

For a 2 column block, the current output is as such:
```
<div class="wp-block-columns has-2-columns">
    <p class="layout-column-1">Column 1</p>
    <figure class="wp-block-image layout-column-1"><img src=""></figure>
    <p class="layout-column-2">Second one</p>
</div>
```

To allow for a grid using [CSS Flexbox](https://caniuse.com/#feat=flexbox), or legacy floats it would need to be:
```
<div class="wp-block-columns has-2-columns">
    <div class="column layout-column-1">
        <p>Column 1</p>
        <figure class="wp-block-image"><img src=""></figure>
    </div>
    <div class="column layout-column-2">
        <p>Second one</p>
    </div>
</div>
```

Adding containers still works with CSS Grid, whilst also allowing for added flexibility. Having the added `column` class also allows for much more flexibility (Instead of targeting `layout-column-1`, `layout-column-2` etc.) such as the following CSS:

```
.wp-block-columns {
    display: flex;
    flex: flex-wrap;
}

.has-2-columns > .column {
    flex: 0 0 50%;
}
```

**Comment by paulwilde** [comment]
Upon further testing it seems that the current implementation has bugs with what I'm trying to achieve anyway, so if anything this is required moving forward regardless.

In the Gutenberg admin here is the Columns block with 2 columns, text with right floated images:
<img width="939" alt="screen shot 2018-04-03 at 00 23 38" src="https://user-images.githubusercontent.com/704594/38221054-84990e74-36d5-11e8-942b-ba2ca51000e9.png">

Now on the front-end (Using identical grid markup as Gutenberg), this is how its displayed:
<img width="897" alt="screen shot 2018-04-03 at 00 24 57" src="https://user-images.githubusercontent.com/704594/38221070-96fc0e36-36d5-11e8-8564-ba66ad3d31de.png">

Due to lack of containers, the image contained with the column. This is due to markup in the admin actually having containing divs:

<img width="463" alt="screen shot 2018-04-03 at 00 28 22" src="https://user-images.githubusercontent.com/704594/38221167-0712967c-36d6-11e8-9eaa-040b7ee00aa3.png">

**Comment by samikeijonen** [comment]
Discussion also in #5351.

**Comment by rchipka** [comment]
👍

**Comment by paulwilde** [comment]
#7234 resolved this.
