### ISSUE TITLE
Template Preview: blocks used in page Content lack contextual menu if they're locked at the top (Title, Featured Image)

### ISSUE THREAD

**Issue by kmanijak** [WordPress/gutenberg#59359]
### Description

When testing Template Preview I spotted that blocks that are locked at a top level (Title, Featured Image) lack contextual menus when used in Content

### Step-by-step reproduction instructions

1. Add new Page
2. Add some blocks to the page, for example:
  - Separator
  - Featured Image
3. Enable "Template Preview" mode
4. Open List View
5. Focus on Separator - it has contextual menu and block Toolbar
6. Focus on Featured Image - it has no contextual menu and there's no block Toolbar so you can't move the block etc.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/20098064/8e0eddf1-7c9a-47f8-ab68-634e55f41fe7

### Environment info

- WordPress - 6.5-beta2-57707
- Gutenberg - 17.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by fabiankaegy** [comment]
This is getting fixed in: https://github.com/WordPress/gutenberg/pull/59297
