### ISSUE TITLE
Avoid race conditions between media upload and autosave

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#5936]
Related: #4090

An autosave should not take place if there are pending uploads, otherwise the transient media information may be serialized permanently to the post. As in #4090, this was explored as a way to postpone autosave until after blockers have been resolved. This could also be tied into a generalized API for requirements for saves to take place (publish blocking, and related informative UX).

**Comment by talldan** [comment]
Referencing issue #10158 which I think could be a report of this problem. The user reported the following:
> The download link started with blob: (strange protocol)

**Comment by aduth** [comment]
A more recent approach to save locking (mentioned in the original comment) can be found at #10649, which is now merged.

**Comment by noisysocks** [comment]
What's the status on this?

**Comment by talldan** [comment]
@noisysocks looks unresolved. Seems as though the work in #10649 could be used in media blocks to fix the issue though.

**Comment by aduth** [comment]
This is still an issue.

#12724 is a recent effort which includes (working) support to avoid saves whilst an image upload is in progress, but its tandem support for managing undo history of transient states has not yet been settled.

**Comment by paaljoachim** [comment]
Is this issue still valid?

**Comment by adamsilverstein** [comment]
> Is this issue still valid?

I think so @paaljoachim - if the post is autosaved while media is in the process of being uploaded, the autosave will contain "corrupted" images that don't work correctly. An ideal solution here would be to prevent autosaving until all uploads have completed.

**Comment by adamsilverstein** [comment]
This should be fixed by https://github.com/WordPress/gutenberg/pull/41120

**Comment by adamsilverstein** [comment]
https://github.com/WordPress/gutenberg/pull/41120 locks autosaving during uploads, but isn't a complete solution (see comment on PR)

**Comment by youknowriad** [comment]
Going to close this one as autosaves and saves can't persist local urls anymore. The remaining work is being tracked in #5936 (blocking saving or triggered unsaved changes)

**Comment by lancewillett** [comment]
> Going to close this one as autosaves and saves can't persist local urls anymore. The remaining work is being tracked in [#5936](https://github.com/WordPress/gutenberg/issues/5936) (blocking saving or triggered unsaved changes)

@youknowriad Do you have the other issue link handy? I noticed you said "being tracked" but your link is to this same issue (self-referential)

**Comment by youknowriad** [comment]
I think I meant to refer to this issue #39223
