### ISSUE TITLE
Font Library seemingly allows re-installing the same font

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#59386]
### Description

 I noticed is that I can re-install the same font over and over again even though it's already installed. See video below.

### Step-by-step reproduction instructions

1. Install a font from Google Fonts
2. See success notice
3. Click on install button again
4. See same notice again
5. Repeat

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/841956/1931cb2a-5203-4ae7-9e5b-14a85e112415

### Environment info

- WordPress 6.5 Beta 2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Closing this out in favor of the following https://github.com/WordPress/gutenberg/issues/58989 which reflects the same issue. It's not a bug so much as a UX problem.

**Comment by annezazu** [comment]
Also, where are my manners? Thank you for testing and opening this ✨
