### ISSUE TITLE
Revert resized canvas and don't render resize handles when zoomed out

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#59389]
### Description

Enabling zoom-out view on resizable canvases such as template parts or patterns results in unnatural scroll bars. Also, when you move the resize handle, the canvas size seems to change unnaturally.

I think if zoomed-out view is enabled, we need to revert the resized canvas size and disable the resizing feature itself.

### Step-by-step reproduction instructions

- In advance, enable "Zoomed out view" on the "Experiments" page.
- Open the site editor.
- Open the pattern you created or one of the template parts.
- Click the Zoom Out View button.
- Play with the resizing handles and test how the canvas changes.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/5c752266-1cbc-4219-8cc1-93bbc41aa636

### Environment info

Gutenberg 17.8.0-rc.2

Note: Zoom-out view is an experimental feature and is not available in WP6.5.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
> I think if zoomed-out view is enabled, we need to revert the resized canvas size and disable the resizing feature itself.

Agreed. I detailed the same in https://github.com/WordPress/gutenberg/issues/60052. I'll close that in favor of this one.
