### ISSUE TITLE
Prevent Classic Blocks from being converted to Shared Blocks

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#5941]
I was watching a talk about Gutenberg at WordPress Sydney and, during a live demo, I noticed the presenter experience some confusion while attempting to migrate a pre-Gutenberg post to use Gutenberg blocks. Here's what he did:

1. He installed the Gutenberg plugin
2. He edited an existing post
3. He selected the Classic block
4. He clicked on the meatballs icon to open the More options menu:  
  <img width="716" alt="screen shot 2018-04-03 at 13 24 01" src="https://user-images.githubusercontent.com/612155/38227638-804d3eb8-3742-11e8-92ff-0bb3dfabff3a.png">  

5. He immediately moved his cursor to point at _Convert to Shared Block_
6. He paused for a moment 🤔 
7. He then slowly moved his cursor up to _Convert to blocks_ and clicked it

It seems to me that these two menu options are worded very similarly and that this is what was caused the presenter to have his flow of thought interrupted. 

Any ideas on how we could avoid this confusion?

cc. @jasmussen @karmatosed

**Comment by jasmussen** [comment]
Given that the classic block is set to look drastically different once #4926 lands, perhaps we can leverage that visual to change the verbiage slightly. Something in the vein of "Convert from Classic" or something. Perhaps "Update to Modern Editor"? Perhaps this ties into #4681? What is the name of our editor, if not just "Editor"? CC: @mor10 in case you have time to input as well.

**Comment by mtias** [comment]
What about removing the ability to make a Classic block reusable? Doesn't seem worth the added cognitive burden to me. This is supposed to be a fallback block primarily.

**Comment by jasmussen** [comment]
> What about removing the ability to make a Classic block reusable? Doesn't seem worth the added cognitive burden to me. This is supposed to be a fallback block primarily.

Yeah that makes total sense. Especially when seen together with (as mentioned), #4926 — it's less of a block and more of an instance of the old post.

**Comment by karmatosed** [comment]
> What about removing the ability to make a Classic block reusable?

+1 for this. Good catch @noisysocks on a trip point in the experience.

**Comment by noisysocks** [comment]
> What about removing the ability to make a Classic block reusable?

👌 sounds good to me. I've done this in https://github.com/WordPress/gutenberg/pull/5970 using an approach first suggested in https://github.com/WordPress/gutenberg/issues/4722.

**Comment by mtias** [comment]
@noisysocks we should still probably not make this a public API as we cannot ensure blocks are not reused through a nesting mechanism.

**Comment by noisysocks** [comment]
> @noisysocks we should still probably not make this a public API as we cannot ensure blocks are not reused through a nesting mechanism.

Good point. Do you think we should just hard code this restriction instead? 

Slightly unrelated, but it feels weird that a Classic block could be nested into another block.

**Comment by danielbachhuber** [comment]
@noisysocks @mtias Does this issue need any further work or can it be closed?

**Comment by noisysocks** [comment]
It's still an (admittedly very minor) issue. I think preventing Classic blocks from being made into a shared blocks is the right approach. I'll revive #5970 but name it `supports._sharing` to emphasise that it's a non-public API.

**Comment by danielbachhuber** [comment]
I've filed this issue against `Merge Proposal: Editor` to make sure this behavior is addressed before Gutenberg is too public.
