### ISSUE TITLE
Improve color indicators in style previews

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#59444]
Related to [this comment](https://github.com/WordPress/gutenberg/pull/56622#discussion_r1505219705) by @ramonjd, I propose we adapt how the `highlightedColors` are chosen for style variations and associated UI. This way it's a clearer visual of the actual colors applied from the variation. 

I'm thinking the first indicator should be the text color, with the second using the button color. If there's no button color, it would fallback to the text color, which is fine, as that variation may be more minimal. There would always be two indicators, maintaining consistency in the UI, reducing confusion.

This would also ensure that the color indicators have appropriate contrast values, as they are styled with the same values that are expected to have a high contrast value against the variation's background color. 

These indicator colors should be the same for full theme style variations as well, not just instances of these 'mini' selectors. 

![CleanShot 2024-02-28 at 17 29 32](https://github.com/WordPress/gutenberg/assets/1813435/08c00e06-ed57-42d6-9901-c3f565abc744)

**Comment by mtias** [comment]
Shouldn't button color fallback to link color instead of text?

**Comment by bgardner** [comment]
Not sure how I feel about this suggestion TBH. I realize I'm an exception_not_the_rule with my choice of design. My Powder theme includes [22 style variations](https://briangardner.com/variations/), but I still set the Buttons (block or element) background to Contrast (not any of the colors) and the same is true of Links. The colors in each palette are there for convenience sake. If this goes through, all 22 variations will essentially show black and black. Not ideal. A way around this is to update the background of Buttons (block or element) from Contrast to Primary, which would look better in the Site Editor (and WP.org theme page), but also result in unexpected/breaking changes for anyone using the theme.

**Comment by richtabor** [comment]
> Shouldn't button color fallback to link color instead of text?

Yea, that makes sense to me.

**Comment by richtabor** [comment]
@bgardner how else would you suggest? Are the colors in the variations used in the variations, or just setting the palette?

**Comment by spencerfinnell** [comment]
Echoing [my thoughts from a couple of years ago](https://github.com/WordPress/gutenberg/issues/38918#issuecomment-1063259266) I still believe it would be nice for these "previews" to be defined by the theme author. 

[`block.json` supports `example`](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#example), what about something similar in `theme.json`?

**Comment by bgardner** [comment]
I like @spencerfinnell's suggestion. (If anything as primary method, fallbacks as described above would be ok.)

This would allow me to show Contrast (Text) and the Primary (main accent) colors in each preview, which would be ideal in my case.

**Comment by richtabor** [comment]
>  I still believe it would be nice for these "previews" to be defined by the theme author.

I don't think that's a bad idea, although I do think a better fallback for when themes don't would still be beneficial.

**Comment by richtabor** [comment]
Here's an example from TT4, using the proposed method here.

I observe: 
- The results are less random, as the colors are consistently pulled from background, text, and button background (with link color as a fallback).
- The previews are have appropriate contrast out-of-the-box, as text and buttons contrast with the background of the site/preview. 

| Current  | Proposed |
| ------------- | ------------- |
|![CleanShot 2024-04-03 at 13 55 54](https://github.com/WordPress/gutenberg/assets/1813435/aec550ff-d8c4-4d5d-a898-14fd310de432)| ![CleanShot 2024-04-03 at 14 11 58](https://github.com/WordPress/gutenberg/assets/1813435/eff8e8b6-3cff-4075-ab3d-5cc1211b650e)|
 
![CleanShot 2024-04-03 at 14 13 24](https://github.com/WordPress/gutenberg/assets/1813435/921952f4-190c-42b8-ad76-4d070c22da35)
![CleanShot 2024-04-03 at 14 13 44](https://github.com/WordPress/gutenberg/assets/1813435/1ee5eab9-590a-4d7d-af1d-5659299a73ab)
![CleanShot 2024-04-03 at 14 13 54](https://github.com/WordPress/gutenberg/assets/1813435/3841219f-eefc-40d3-afe1-4df7297f20d8)
![CleanShot 2024-04-03 at 14 14 04](https://github.com/WordPress/gutenberg/assets/1813435/290fc041-6023-403c-b4be-813243fdf01a)
![CleanShot 2024-04-03 at 14 14 13](https://github.com/WordPress/gutenberg/assets/1813435/3df848c7-409b-43ab-b1f4-5d301eb7863f)
![CleanShot 2024-04-03 at 14 14 21](https://github.com/WordPress/gutenberg/assets/1813435/adaaa716-e72d-4479-90b3-b548377dada3)
![CleanShot 2024-04-03 at 14 14 31](https://github.com/WordPress/gutenberg/assets/1813435/690c6ca8-afd2-4e84-8264-9b9850f4f16e)
![CleanShot 2024-04-03 at 14 14 43](https://github.com/WordPress/gutenberg/assets/1813435/4a88e355-7425-423c-b606-a44bb7d9c94e)

**Comment by bgardner** [comment]
@richtabor Are we still considering allowing theme authors to specify in theme.json?

_The results are less random, as the colors are consistently pulled from background, text, and button background (with link color as a fallback)._

Because with Powder, whether it be button background or link color, all of my variations would essentially show black/black on white.

**Comment by spencerfinnell** [comment]
Possibly semi-related: https://github.com/WordPress/gutenberg/issues/49661

**Comment by spencerfinnell** [comment]
Also semi-related if a new entry point for previews is added to `theme.json` (which seems very logical to me): https://github.com/WordPress/gutenberg/issues/57286

**Comment by richtabor** [comment]
> @richtabor Are we still considering allowing theme authors to specify in theme.json?

Yes, I think it's worth considering; perhaps like block.json's `example` object. 

@spencerfinnell  @bgardner What do you think that would look like ideally in theme.json?

**Comment by bgardner** [comment]
@richtabor Could be as simple as:

```
{
	"settings": {
		"preview": [
			{
				"colors": [ "#f5f5f5", "#0a0a0a", "#6d28d9" ]
			}
		]
	}
}
```

**Comment by richtabor** [comment]
@bgardner mind opening an issue up about that specifically? I don't want it to get lost.

**Comment by richtabor** [comment]
> @richtabor Could be as simple as:

Maybe just the highlight colors (the two circles), allowing the background to maintain as the background of the preview. 

I wonder if `example` works well, as it's closer to block.json, and maybe even top-level.

**Comment by justintadlock** [comment]
I'd be good with the proposed system as a default/fallback. It's definitely an improvement over what we have today.

I'm in favor of the preview colors being customizable even more.
