### ISSUE TITLE
Native contact form block

### ISSUE THREAD

**Issue by marcarmengou** [WordPress/gutenberg#59478]
It is possible to create a WordPress site without plugins, although most sites must resort to an SEO plugin and a contact form plugin to have a "functional and discoverable" site in search engines.

I don't want to focus now on whether or not simple SEO elements, such as meta tags, Open Graph, indexing, etc, should be part of WordPress or not, because it can be more complex than the contact form. Can create a personal site, a blog or a company site without using anything external to WordPress, but no one will be able to contact without a contact form plugin.

Plugins are a fantastic way to extend the possibilities of WordPress, but in my opinion having a contact form is a basic for any site, both personal and business. Whether we like it or not, email is still the main form of contact.

With the full site editor we have blocks for many features, some of them for quite specific and unused things for the vast majority of people, but we don't have a simple contact form block to establish a simple contact.

**Comment by annezazu** [comment]
Hey @marcarmengou. Thanks for opening your first issue here and for sharing your feedback. I want to alert you to work that's already underway to experiment with a form block. Here's the original issue https://github.com/WordPress/gutenberg/issues/44186 and here's the PR that kicked it off: https://github.com/WordPress/gutenberg/pull/44214

There's a label you can follow as well to track progress or open up more issues/ideas:

https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BBlock%5D+Form+%28experimental%29%22

I'm going to close this out as a result but let me know if you have any questions and I'll do my best to get back to you promptly. You might be into this overall issue too proposing some additional blocks managed by Core that don't come by default: https://github.com/WordPress/gutenberg/issues/58773
