### ISSUE TITLE
Site Editor: Save shortcut shouldn't open the save sidebar

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#59472]
### Description

Using "cmd + s" (the save shortcut) in the site editor in edit mode is weird these days. You can see the save sidebar open for some milliseconds and then it closes itself. 

We should avoid that middle step and just not open the sidebar at all.

### Step-by-step reproduction instructions

1- Go to the site editor
2- Click a template/page or anything
3- Make some changes
4- Use the save shortcut ctrl+s or cmd+s

The sidebar should not "flash".

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
This would be a neat way to also solve this issue: https://github.com/WordPress/gutenberg/issues/38714

**Comment by colorful-tones** [comment]
This may help fix https://github.com/WordPress/gutenberg/issues/59215 also.

**Comment by akasunil** [comment]
I was able to reproduce this issue, and it only occurs on the initial load. If we make changes and save them again, the sidebar does not open.

![CleanShot 2024-03-02 at 11 53 55](https://github.com/WordPress/gutenberg/assets/61308756/88c10591-3519-42bc-ba16-9c4e591dfe9b)
