### ISSUE TITLE
Font Library: Multiple Fetch errors uploading fonts are difficult to read

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#59484]
### Description

When uploading multiple font files, the error message can be difficult to read if there are multiple fetch errors.

Rather than combing identical messages and formatting different errors as a list, the error message is shown as a single long string, for example:

> No font faces were installed. Fetch error: Demonstration of multiple identical fetch errors. Fetch error: Demonstration of multiple identical fetch errors. Fetch error: Demonstration of multiple identical fetch errors. Fetch error: Demonstration of multiple identical fetch errors. Fetch error: Demonstration of multiple identical fetch errors.

Ideally I think the following would happen in the case of multiple errors:
* duplicate errors are removed
* each error is shown as a list item

No change in the event only one error occurs.

### Step-by-step reproduction instructions

1. Modify `WP_REST_Font_Faces_Controller::handle_font_file_upload()` to simply return a `WP_Error` object
   ```php
   protected function handle_font_file_upload( $file ) {
   return new WP_Error( 'rest_font_fetch_errors', __( 'Demonstration of multiple identical fetch errors.', 'gutenberg' ) );
   }
   ```
2. Open the site editor > Styles > Typography > Typography Manager > Upload
3. Drag multiple font files into the upload window
4. Observe the long string of errors, one for each file

### Screenshots, screen recording, code snippet

![Screen Shot 2024-03-01 at 11 35 17 am](https://github.com/WordPress/gutenberg/assets/519727/f234f60a-e800-4c8d-beb9-b46cf99ee052)

### Environment info

- Gutenberg trunk 9957b858fb0657f234b8b392a91996f654256fcf
- WordPress 6.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mikachan** [comment]
I can successfully reproduce this with the testing instructions. It's also easy to replicate by trying to upload multiple fonts that have already been successfully installed, you should see duplicate "Fetch error: A font face matching those settings already exists." error messages:

![image](https://github.com/WordPress/gutenberg/assets/1645628/4aed9d0c-390a-46e6-93ce-b385b803e1b1)

**Comment by matiasbenedetto** [comment]
I was able to reproduce this error.
1. Set the permissions of your fonts folder as non-writable by your server.
2. Try to install multiple font faces at once:


https://github.com/WordPress/gutenberg/assets/1310626/eb554595-1485-41b9-890c-e36f8982c8f2
