### ISSUE TITLE
Ability to declare blocks in a template as wide or full by default

### ISSUE THREAD

**Issue by AndreaBarghigiani** [WordPress/gutenberg#5948]
## Issue Overview
I've been playing a bit on how our themes can create Gutenberg templates but I've noticed that I am not able to set a specific alignment (wide or full) for nested or simple block.

[In the handbook](https://wordpress.org/gutenberg/handbook/templates/) is present an `array( 'align', 'left' )` but if I set it to `wide` in a column block Gutenberg stops working and I get the TunyMCE editor (btw congrats for the fallback).

I've been reading the issues of this repo and the handbook but I didn't find any documentation about it.

## Steps to Reproduce (for bugs)
1. Create a CPT
2. Set a template for the CPT

## Expected Behavior
I would like to be able to declare on a *per post basis* if the current block for the template needs to 

## Current Behavior
The user can change the alignment of a column block as he likes.

## Possible Solution
Insert a new item inside the `template` array named `align` or more meaningful names in order to declare something like this:

```php
$args = array(
  'public' => true,
  'label'  => 'Books',
  'template' => array(
      array('core/columns', 
          array(), // Why is it empty? 
          // Proposal array( 'align', 'wide' ), as for standard template
          array(
            array('core/image', array('layout' => 'column-1')),
            array('core/heading', array(
                'placeholder' => 'Add Author...',
                'layout' => 'column-2'
            )),
            array('core/paragraph', array(
                'placeholder' => 'Add a inner paragraph',
                'layout' => 'column-2'
          )),
      ))
  ),
);
```

## Related Issues and/or PRs
#4383 #4747

**Comment by mtias** [comment]
This already works, but your syntax is incorrect. You need to define the second argument attributes for `align` as any other attribute:

```php
array( 'core/columns', array( 'align' => 'wide' ), $children );
```
