### ISSUE TITLE
link broken in docs

### ISSUE THREAD

**Issue by michellomp** [WordPress/gutenberg#5949]
[Extending Blocks](https://github.com/WordPress/gutenberg/blob/master/docs/extensibility.md#extending-blocks) [link](https://github.com/WordPress/gutenberg/blob/master/docs/extensibility/extending-blocks)  send to a  404 page

**Comment by Soean** [comment]
Hey @michellomp,
thanks for your report.
The .md docs files on GitHub are just the source files for the [handbook](https://wordpress.org/gutenberg/handbook/extensibility/#extending-blocks). On the handbook page the link works correct. So I am closing this issue.
