### ISSUE TITLE
Allow the site tagline to be a heading

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#59523]
## What problem does this address?

There is no way to change the HTML tag of the site tagline from a paragraph.
By enabling the the tagline to be a heading or paragraph, users and designers have more freedom to customize their site.
For example, the tagline could then be a heading above a blog.

## What is your proposed solution?

Allow the site tagline to be a heading as well as the default paragrah.

**Comment by huubl** [comment]
+1 I think this issue isn't isolated and impacts other blocks too. Introducing a `tagName` block support could potentially enhance flexibility. Something like:

```javascript
supports: {
  tagName: ['p', 'span', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6']
}
```

This would enable easy modification of the HTML tag for the site tagline and other blocks, similar to the current functionality of TagName in the `core/group` block.
