### ISSUE TITLE
Parsing "data-*" attributes

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#59532]
### Description

It seems that `data-*` attributes are not parsed by `hpq` library and consequently not as a block attribute. Given their special nature I can understand that. This is perhaps a known issue, but I want to confirm that.

To clarify more, see below:

### Step-by-step reproduction instructions

in `blocks.json`, block attribute definition

```json
{
...
		"openSelector": {
			"type": "string",
			"source": "attribute",
			"attribute": "data-open-selector"
		},
...
}
```

result: openSelector attribute is undefined each time and causes `This block contains unexpected or invalid content.` error, since it is not parsed from the block. I use instead openSelector without "source" and "attribute" instead, so it is written in a block comments, but it would be nice to know if this is known and accepted issue, or bug.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

`data-*` attributes are also used in core blocks.

Table Block:

https://github.com/WordPress/gutenberg/blob/5319e96303b515f98feb7925ae5a2e94cd46c4c8/packages/block-library/src/table/block.json#L90-L94

GalleryBlock:

https://github.com/WordPress/gutenberg/blob/5319e96303b515f98feb7925ae5a2e94cd46c4c8/packages/block-library/src/gallery/block.json#L24-L48

> result: openSelector attribute is undefined each time and causes `This block contains unexpected or invalid content.`

Could you tell us specifically what kind of errors are logged?

**Comment by Mamaduka** [comment]
I'll close the issue.

@Lovor01, feel free to re-open it with any additional details that can help reproduce the bug.
