### ISSUE TITLE
Data Views > Patterns: add option to hide thumbnails or view as a table

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#59545]
## What problem does this address?
While the thumbnails for patterns helps a lot of users, it is very busy and does not serve all workflows equally

Some users might prefer a more streamlined list of patterns they can quickly scan. We should give them the choice to switch between a visual grid and a more condensed table/list view,  just like they can do with Pages.

## What is your proposed solution?
- Add a "View as Table" option
or
- Add an option to hide thumbnails in Grid View

**Comment by t-hamano** [comment]
Thanks for the report.

Since the Patterns page now supports the table layout via #60337, I would like to close this issue. However, since the preview is shown by default and there is no way to hide it, I submitted #60704 proposing a change to this spec.
