### ISSUE TITLE
Pages data view: Include a 'Template' field

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#59552]
Occasionally you want to look for pages that use a certain template. Including a field for display and filtering would achieve this.

<img width="896" alt="Screenshot 2024-03-04 at 13 06 00" src="https://github.com/WordPress/gutenberg/assets/846565/80b762f0-9557-42eb-91de-c1f72db3d6cf">

**Comment by t-hamano** [comment]
Probably the same as what #59040 is suggesting?

**Comment by jameskoster** [comment]
Closed as duplicate.
