### ISSUE TITLE
Text setting reset option is bit confusing

### ISSUE THREAD

**Issue by ajitbohra** [WordPress/gutenberg#5957]
## Issue Overview
Using version 2.5 and noticed now we have new text settings. As reset button is adjacent to size toggles kind of indicates a relation between them. But reset button sets predefined size & custom size to default values. That then indicates reset if for all text settings but it does not rest drop cap.

## Expected Behavior
Reset set size toggles to default

## Current Behavior
Reset option sets predefines & custom size to default values

## Possible Solution
Moving reset button to end of text setting and it reset all the settings

## Screenshots / Video
![text-settings](https://user-images.githubusercontent.com/1039236/38270856-56bd9eb6-37a2-11e8-8d69-c6a63ca3497b.png)

cc: @karmatosed

**Comment by karmatosed** [comment]
The reset does that action to the settings next to it, resetting to the defaults. I can possibly see an argument for making it a link not a button,  but it still should reset to the defaults.

**Comment by ajitbohra** [comment]
Currently, it does not rest drop cap. Link sounds good like we have for the color picker.

Not sure if this makes sense:
- Moving S/M/L/XL + reset at the end 
- Reset also works for the drop cap

Thought to share as it made me think for a moment to understand how rest work.

**Comment by karmatosed** [comment]
> Currently, it does not reset drop cap.

Just to be clear I wasn't saying it did reset drop cap. Just like it isn't a reset for all styling including paragraph background. It's just a contextual reset for sizing. Maybe in future we could add total resets, we do have undo/redo for that.

I'm going to for now say let's keep this as is as we're not seeing confusion with others here. If we do, we totally can revisit and work on next steps forward. I do not think though that moving and adding reset for drop cap is the solution here - totally may be a different solution going foward.

**Comment by markjaquith** [comment]
It was clear to me that it is a size reset, as it is quite nearly grouped with the S, M, L, XL size presets.
