### ISSUE TITLE
Overrides in Synced Patterns: add context about what "Allow instance overrides" does

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#59603]
## What problem does this address?
If a user hasn't been read about overrides, it's very hard to understand what "Allow instance overrides", because the UI doesn't provide any context about it.

## What is your proposed solution?
We should add a brief description above or below the checkbox describing what it does.

**Comment by annezazu** [comment]
Closing this out as this flow was removed and there's now an issue for connecting renaming for unlocking overrides: https://github.com/WordPress/gutenberg/issues/59813#top
