### ISSUE TITLE
Overrides in Synced Patterns: allow overrides to be enabled when creating a Pattern outside the Pattern Editor

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#59602]
## What problem does this address?
It's possible to create a synced pattern from anywhere that pattern can be inserted, however, it's only possible to enable overrides when editing the Pattern from Editor > Patterns or by clicking on "Edit Original" in the toolbar.

## What is your proposed solution?

I think of two possible options: 

* Use the empty space in the Block Inserter sidebar to list blocks contained in that pattern with a checkbox to enable overrides or not

![CleanShot 2024-03-05 at 15 30 36@2x](https://github.com/WordPress/gutenberg/assets/14153300/a1878173-28d5-4600-b2f8-06d1216c5902)

* List individual blocks when a pattern is created, similar to how it shows when an existing pattern is inserted, and surfect the checkbox to allow overrides under Advanced

**Comment by annezazu** [comment]
This friction is intentional and I don't see this changing right now. We need folks to have a mental framework of these more global/cross synced pattern changes. I'm going to close this out as not planned as a result.
