### ISSUE TITLE
NavigationMenuSelector: Can't create new menu after switching to another menu

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#59604]
### Description

Splitting this out from https://github.com/WordPress/gutenberg/pull/59440

As noted in https://github.com/WordPress/gutenberg/pull/59440 I'm not sure some state propertis used by the `NavigationMenuSelector` component work as expected. 

Specifically, `isCreatingMenu` is always `true` after switching to another, existing, menu. This triggers at least two bugs:
- After switching to another menu, it is not possible to create a new menu as the 'Create new menu' button is disabled based on `isCreatingMenu`. [See the code here](https://github.com/WordPress/gutenberg/blob/e89fceffab765902e0162a1e3359d88501e72005/packages/block-library/src/navigation/edit/navigation-menu-selector.js#L179-L188).
- The 'loading' indicator when creating a new menu doesn't work correctly: it always stays to 'Loading'. While this will be mitigated in https://github.com/WordPress/gutenberg/pull/59440 I suspecd that also `isResolvingNavigationMenus` and `hasResolvedNavigationMenus` don't work as expected, at least in terms of _timing_.

Cc @getdave 🙏🏽 

### Step-by-step reproduction instructions

- Make sure you have at least two menus.
- Go to the Site editor, edit mode.
- Select a Navigation, assuming it already contains a menu.
- In the Settings panel, click the ellipsis button after the heading 'Menu' to open the actions dropdown menu.
- Observe the 'Create new menu' button at the bottom of the dropdown menu is enabled. Screenshot:

![Screenshot 2024-03-05 at 16 26 09](https://github.com/WordPress/gutenberg/assets/1682452/415fbca0-4110-4adf-b641-af201312c792)

- Switch to another existing menu.
- Reopen the dropdown menu.
- Observe the 'Create new menu' button is now disabled. At this point, it's not possible to create a new menu. Screenshot:

![Screenshot 2024-03-05 at 16 26 22](https://github.com/WordPress/gutenberg/assets/1682452/53ba46b7-026b-4bfc-86ed-3f126ca3e36e)

- In the settings panel, click the 'Settings' tab, the one with the gear icon.
- Then click the List view tab, this way the `NavigationMenuSelector` component re-renders.
- Open the dropdown menu and observe the 'Create new menu' button is now enabled again.
- Click 'Create new menu'.
- Adger the new menu is created, hover the dropdown ellipsis toggle button to reveal its tooltip.
- Observe the tooltip text hangs on 'Loading...' forever. Note: this will be changed in https://github.com/WordPress/gutenberg/pull/59440

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
Thanks for the bug report 👍

**Comment by draganescu** [comment]
Fundamentally we should not set something called isCreatingMenu when we switch menus. I think it was there as a guard against creating while switching was happening (getting the data for the new menu?) and it maybe worked because when the block re-renders the inspector would re-render and the default of the isCreatingMenu is false.

Maybe there was a time this worked?

**Comment by getdave** [comment]
@fabiankaegy @annezazu @youknowriad I've added this to the Editor Tasks Board for 6.5 during the RC period. The [rationale behind this has been presented](https://github.com/WordPress/gutenberg/pull/59630#issuecomment-1980869737) by @draganescu. 

If a bug fix is in place and merged in time, we will be required to discuss this with the release team prior to RC 2 to agree it's inclusion.
