### ISSUE TITLE
Overrides in Synced Patterns: make option easier to discover

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#59601]
## What problem does this address?
Currently, the option to "Allow instance overrides" is located in the "Advanced" tab, which might make it harder to discover. As this feature becomes more mature and stable, we should consider a new place for it.

## What is your proposed solution?
Possible placements:

- A dedicated section in the Block Inspector sidebar, below the Block Description
- A dedicated icon in the block toolbar
- A setting inside the kebab menu in the block toolbar

**Comment by annezazu** [comment]
Noting that this flow has changed away from a checkbox to renaming to add override-ability and is under discussion in this issue: https://github.com/WordPress/gutenberg/issues/59813#top Going to close this out as a result since it's not quite clear where this will end up.
