### ISSUE TITLE
Overrides in Synced Patterns: allow to create additional Paragraph Blocks when editing an overridable Paragraph

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#59600]
## What problem does this address?
When editing a Synced Pattern instance with an overridable Paragraph, the user might need to create a new Paragraph only in that instance, while keeping the other blocks synced. Currently, hitting Enter/Return after a Paragraph Block will create a line break instead of adding a new Paragraph, which might be limiting for adjusting styles.

## What is your proposed solution?
Add an "Add After" option that will create a new Paragraph that only exists within that Pattern instance.

**Comment by kevin940726** [comment]
I think this is a duplicate of https://github.com/WordPress/gutenberg/issues/61225. I'll close this for now. Feel free to reopen if I'm mistaken! 🙇
