### ISSUE TITLE
Broken Search - Button Only in navigation blocks

### ISSUE THREAD

**Issue by bahia0019** [WordPress/gutenberg#59614]
### Description

In the Navigation block when selecting the Search icon, then selecting the Button Only option, the block becomes un-selectable, and the styles on the front end get messed up.

### Step-by-step reproduction instructions

1. Add or edit a navigation block
2. Add the Search block
3. Choose the Button Only option
4. Attempt to select the Search block again
5. Save the page/template and view the Search icon on the front end

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1586037/c0aa6bb0-7110-4b09-9822-b7bf7db212f1

### Environment info

I used two sites.
Site One: WordPress v6.4.3 with Twenty Twenty-Four theme (Local environment with PHP 8.0.3)
Site Two: WordPress v6.4.3 with Frost theme (Prod environment with PHP 8)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by akasunil** [comment]
I'm unable to reproduce this issue on WordPress v6.4.3 with the Twenty Twenty-Four theme. The same goes for WordPress v6.5 beta and the Twenty Twenty-Four theme. Make sure no third-party plugins are causing the problem.

**Comment by bahia0019** [comment]
> I'm unable to reproduce this issue on WordPress v6.4.3 with the Twenty Twenty-Four theme. The same goes for WordPress v6.5 beta and the Twenty Twenty-Four theme. Make sure no third-party plugins are causing the problem.

Interesting. I've tried this on multiple sites now (Local, Production, Staging, fresh sites with no plugins), and get the same result.

**Comment by torounit** [comment]
I'm unable to reproduce this issue on WordPress v6.4.3 and 6.5-rc1.

**Comment by annezazu** [comment]
Thanks so much for reporting, especially with a video as that always makes it easier to understand what might be going on! This matches a prior issue I just closed out after being unable to replicate: https://github.com/WordPress/gutenberg/issues/57464

I'm going to close this one out too as a result :) but I encourage folks to share if you can replicate so we can get this addressed.
