### ISSUE TITLE
Add inline comment denoting action version

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#59624]
### Description

#58475 introduced a new step in the `rnmobile-ios-runner.yml` workflow to setup Ruby. The action used a specific commit SHA as [recommended in the GitHub security hardening guidelines](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), but did not include an inline comment denoting the version in human-readable format.

[This is an example](https://github.com/WordPress/gutenberg/blob/trunk/.github/workflows/unit-test.yml#L128) of how to include the inline comment in a way that Dependabot will update automatically.

### Step-by-step reproduction instructions

View the `rnmobile-ios-runner.yml` file.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Jayanth-Parthsarathy** [comment]
Hey @desrosj. I would love to work on this. Please assign this to me

**Comment by Jayanth-Parthsarathy** [comment]
Hey @desrosj . Please have a look at my PR and let me know if there are any other changes to be made.
