### ISSUE TITLE
Site Editor: certain themes fail to load static homepage content

### ISSUE THREAD

**Issue by fushar** [WordPress/gutenberg#59634]
### Description

When the homepage is set to show a static page, **on certain themes**, Site Editor will show blank page instead of the static page content.

### Step-by-step reproduction instructions

1. Download, install, and activate the [Bedrock](https://public-api.wordpress.com/rest/v1/themes/download/bedrock.zip) theme
1. Go to Settings -> Reading
1. Set a static page as homepage
1. Open Site Editor
1. You will see a blank page instead of the page content.

### Screenshots, screen recording, code snippet

|Expected|Actual|
|-|-|
|<img width="1277" alt="image" src="https://github.com/WordPress/gutenberg/assets/1525580/5ec33f8e-d342-4a1a-9475-65241753eca8">|<img width="1292" alt="image" src="https://github.com/WordPress/gutenberg/assets/1525580/6cb3c0a1-5972-4f9c-9d1c-2c2219151d4e">|

### Environment info

- Gutenberg 17.8.2
- [Bedrock](https://wordpress.com/theme/bedrock) theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by arthur791004** [comment]
xpost my findings [here](https://github.com/Automattic/wp-calypso/issues/88219#issuecomment-1980528515):

Here are my findings:

* The static homepage of the bedrock theme contains `bedrock/page` pattern with a template part
* When the “homepage displays” is configured to a static page, the post type is weird.
  * It may become the “Page” post so the post type is page. See [here](https://github.com/WordPress/gutenberg/blob/5531a689679576f1b26e6d27e1a95dc1609911c2/packages/edit-site/src/components/editor/index.js#L196).
* We have a hook, [useHideBLocksFromInserter](https://github.com/WordPress/gutenberg/blob/5531a689679576f1b26e6d27e1a95dc1609911c2/packages/editor/src/components/provider/use-hide-blocks-from-inserter.js#L27), that adds a filter to filter out the template part if the post type is not one of wp_block, wp_template, and wp_template_part
* As a result, some blocks of this pattern cannot be inserted into the canvas, resulting in an empty content

So the issue becomes what's the “CORRECT” post type when you open the side editor to edit a static homepage?

**Comment by carolinan** [comment]
Spontaneously, I will say that this is a theme issue, as template parts do not work in and should not be used in page and post content.
Instead of a template part, it is usually possible to use a pattern.

**Comment by carolinan** [comment]
Interestingly enough, I can only reproduce this blank preview when Gutenberg is active.

**Comment by annezazu** [comment]
Not moving this to the 6.5 board since this doesn't seem related to the release (noting for any other core editor triag-ers).

**Comment by iamtakashi** [comment]
> Interestingly enough, I can only reproduce this blank preview when Gutenberg is active.

This is correct. The theme used to work fine before, but it started having this issue with recent updates in the Gutenberg plugin.

**Comment by iamtakashi** [comment]
> Spontaneously, I will say that this is a theme issue, as template parts do not work in and should not be used in page and post content.

@carolinan, thanks for sharing your insight. In the Bedrock theme, the template parts are used inside a full-page pattern, not in a page or a post content. This wasn't an issue until recently. Are you saying a template part should never be used in a pattern? I can see some patterns that use some template parts in the TT4 theme, for example, though.

**Comment by iamtakashi** [comment]
Oh, this is probably related to the recent change to make the page editing mode as default for the static front page.

**Comment by dsas** [comment]
I think it's #58928, if I revert that then it works again. cc @youknowriad

**Comment by dsas** [comment]
Yep, if I add `page` to [`POST_TYPES_ALLOWING_POST_CONTENT_TEMPLATE_PART`](https://github.com/WordPress/gutenberg/blob/afc08a1ca41dfb4c2e9fd6effd3d9878c1955381/packages/editor/src/components/provider/use-hide-blocks-from-inserter.js#L10) the page content shows.

**Comment by iamtakashi** [comment]
Thank you, @dsas, for finding that out!

I wonder if it would have been helpful if there had been an error message instead of a "blank page of death".  This time, a block theme killed the editor to a degree that I hadn't seen before.

**Comment by carolinan** [comment]
> > Spontaneously, I will say that this is a theme issue, as template parts do not work in and should not be used in page and post content.
> 
> @carolinan, thanks for sharing your insight. In the Bedrock theme, the template parts are used inside a full-page pattern, not in a page or a post content. This wasn't an issue until recently. Are you saying a template part should never be used in a pattern? I can see some patterns that use some template parts in the TT4 theme, for example, though.

It depends.
For example, if the pattern is hidden from the inserter, then it can't be inserted in the block editor, so it also can't break there.
If the pattern is set to work on a specific template type or post type, it will depend on which.
After your ping, I did find a few patterns for the query block that might be problematic in TT4, but I have not found the time to test it.

-----
If theme developers need it, the reason behind limiting the template parts should be weighted against the developer needs, and possibly be reconsidered.

I don't have a strong opinion, but I hear from other people who have direct contact with users that the template parts are difficult to use. Allowing the parts in the post content might or might not make them easier to use ( better consistency between the editors).
I was trying to refer to the previous decision, and I did not make the time to include all information that you needed, I apologize.

**Comment by youknowriad** [comment]
Interesting the intent of my PR was normalizing the behavior between post and site editors and not change the site editor behavior. 

That said, I expect the blocks to be hidden from the inserter but I wouldn't expect empty content / breakage. So we'll have to debug this a bit more.

**Comment by iamtakashi** [comment]
@carolinan, thanks for adding the further context. That makes sense.

Thank you all for fixing the issue. Much appreciated!
