### ISSUE TITLE
Color Picker issue on mobile

### ISSUE THREAD

**Issue by ajitbohra** [WordPress/gutenberg#5963]
On mobile color picker will not display if vertical room for popover is not enough to display. 

# Demo 
![color-picker](https://user-images.githubusercontent.com/1039236/38276577-0c9b25b8-37b3-11e8-9e34-ba2af09c44d2.gif)

**Comment by karmatosed** [comment]
What device and browser are you using? I am unable to replicate this so would like a little more information to ensure I can.

**Comment by ajitbohra** [comment]
@karmatosed its working fine with the latest master seems like it was fixed in the last release.

Closing this, for now, will reopen if needed
