### ISSUE TITLE
Typo in pagination strings: `CurrenPageControl` rather than `CurrentPageControl`

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#59652]
### Description

Props due @BronsonQuick `Bronson Quick <bronsonquick@git.wordpress.org>`

In both the dataviews and font-collection pagination strings there are typoed component names `<CurrenPageControl />`. 
This could lead to confusion for translators presuming the string is a typo and fixing it.

data views:

https://github.com/WordPress/gutenberg/blob/02467a592ab610f0279fa54d954e9bc2a31aa6ca/packages/dataviews/src/pagination.js#L36-L43

font collection:

https://github.com/WordPress/gutenberg/blob/6519c5216fc722e799f2e6138d03b0bd8b979e74/packages/edit-site/src/components/global-styles/font-library-modal/font-collection.js#L440-L450

### Step-by-step reproduction instructions

N/A: typo rather than code bug

### Screenshots, screen recording, code snippet

See above

### Environment info

Gutenberg trunk @ 0f37efd49b5f0b2effd65d273a06ca20337d986f
WordPress develop trunk @ https://github.com/wordpress/wordpress-develop/commits/f3e19bf56608e80952a71e77691bdd5aab315548
WordPress develop 6.5 @ https://github.com/wordpress/wordpress-develop/commits/0c1507c2e66a5109db1ed50626176774b8bcb08e

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by rcoll** [comment]
Cheers. I think this PR fixes the issue https://github.com/WordPress/gutenberg/pull/59656.
