### ISSUE TITLE
WP 6.5 RC1 - Partial Sync Patterns br0oken

### ISSUE THREAD

**Issue by nick6352683** [WordPress/gutenberg#59651]
### Description

This regression was introduced in WP 6.5 RC1:

- The "Pattern Overrides" checkbox under the Advanced Tab does not show up in WP RC1.
- Existing partial syncs set in the beta versions work fine, but because the overrides checkbox is missing you cannot make changes to the patterns as far as partial syncing goes.
- Activating the Gutenberg plugin, the bug goes away and all is fine again.

I hope this will be fixed by March 26, and not punt it to WP 6.6.

### Step-by-step reproduction instructions

With WP 6.5 RC1 installed:

1. Try to make a partially synced pattern - you can't...
2. Activate the Gutenberg plugin.
3. Now try step 1 and create a partially synced pattern - now you can !

### Environment info

WP 6.5 RC1, Windows 10, Chrome, Xampp 7.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I was able to reproduce this problem. However, in my environment, the pattern override UI was not displayed even if I enabled Gutenberg trunk (17.9.0-rc.1). What version of the Gutenberg plugin are you using?

In any case, I think the problem with pattern overrides not being available in WP6.5 should be fixed, so I'll add it to the project board.

![pattern-overrides](https://github.com/WordPress/gutenberg/assets/54422211/8fd43c21-b434-47e6-a1e5-c6c9b6f5f551)

**Comment by talldan** [comment]
I realize it's confusing, but the change is intentional. A block now has to be given a name to be considered overridable.

There's a discussion happening in the pattern overrides issue about this change - https://github.com/WordPress/gutenberg/issues/53705#issuecomment-1972834933

**Comment by nick6352683** [comment]
Thanks guys, as a coincidence this was posted 2 hours ago, https://make.wordpress.org/core/2024/03/07/unblocking-wp6-5-font-library-and-synced-pattern-overrides/ and it seems that the pattern overrides will be punted for WP 6.6, which is frustrating... once again 2 steps forward, 1 step back.... After @talldan explanation, in RC1, we never get that checkbox, but to make it partial syncing to work, all we have do is give any pattern you want to partial sync, a block name, and you are set.... Let's see what will happen in the next weeks or so...
