### ISSUE TITLE
The styles page in the site editor

### ISSUE THREAD

**Issue by unprintedch** [WordPress/gutenberg#59675]
## What problem does this address?
It is not clear enough when you are editing local VS global style settings
we need a more direct access "theme" related settings to setup the bases of a new website.

## What is your proposed solution?
When you enter the editor and then style you are offered pre-defined setting.
Could we have the setting that are present later on
<img width="1420" alt="Capture d’écran 2024-03-07 à 15 17 51" src="https://github.com/WordPress/gutenberg/assets/2622001/d560fe90-7dbc-4224-a5b0-504339ce3088">
Like:
DEFAULT STYLE
- Site logo and favicon
- Typography (police, weight, size and colors)
- Color palette
- Spacing (basic default)
- Forms?
Per block global settings >
See capture below

<img width="862" alt="Capture d’écran 2024-03-07 à 18 38 07" src="https://github.com/WordPress/gutenberg/assets/2622001/7bd373b0-80fd-4f22-adbb-5079fe724afd">

I thinks it will also solve the site icon/favicon problem.

**Comment by Marc-pi** [comment]
yep, far better !

**Comment by huubl** [comment]
+1 
In addition, I propose that when modifying Global Styles, the relevant elements from the Style Book should be the default to visualize the user changes. But also have the option to select a specific page for previewing these changes. See my (outdated) issue:
https://github.com/WordPress/gutenberg/issues/49187

**Comment by unprintedch** [comment]
Select the preview page is a good idea, so we could make some "test page" with the relevant paterns and block.
I also would like that the fonts/color/spacing options sticks on the left.
We could so define 2 things. The global settings are always left and on a dark bg and the local changes are always right with light bg.

**Comment by scruffian** [comment]
I like this idea, and it fits well with the direction in https://github.com/WordPress/gutenberg/issues/53483. I think there are still a lot of uncertainties around how we'll surface this level of detail inside the Site View, which are being explored in the Data Views project (for example this https://github.com/WordPress/gutenberg/issues/59659).

I think we should wait to see what the outcome of those explorations are before we commit to a path forward here.

**Comment by annezazu** [comment]
Thanks so much for opening this and showing what you'd like to see visually. It's always helpful to see what folks find useful. To prevent confusion and duplicated discussion, I'm going to close this issue out though and encourage you all to continue the discussion on https://github.com/WordPress/gutenberg/issues/53483. This is where work is more actively being discussed and solutions are being considered.

**Comment by annezazu** [comment]
Please let me know if you would like to post and I'll delete my comment but, for now, to ensure nothing is lost, [I've taken your proposed solution and feedback to that current issue](https://github.com/WordPress/gutenberg/issues/53483#issuecomment-1994965332) so it's more readily available for consideration <3
