### ISSUE TITLE
Translation .pot build replaces '/' with '\' in Windows.

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#597]
The dreaded Windows slash debacle appears to be present in the translation build.  Yes, I am one of those terrible Windows users 😲.  I am not familiar with how the build works, otherwise I would be glad to patch.  When the .pot file is built instead of:
```
blocks/components/editable/index.js:38
```

You get:
```
blocks\components\editable\index.js:38
```

Currently in all of my PRs I don't stage the .pot file for commit and hopefully the changes get put in on someone else's PR.  Most likely node's `resolve()` is changing the resolve to match Windows' paths since I am on Windows?

**Comment by BE-Webdesign** [comment]
It appears there is a babel plugin that handles everything so I assume changing something in there will solve our problems.

**Comment by aduth** [comment]
Thanks for noting this. I'll plan to take a look.

**Comment by BE-Webdesign** [comment]
Ping me in slack, if you need testing, unless you have a VM for Windows.
