### ISSUE TITLE
Gallery Block doesn't apply the 'post_gallery' filter, causing incompatibility with WP Gallery Custom Links

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#5972]
## Issue Overview

The WP Gallery Custom Links plugin adds a “Gallery Link URL” field when editing gallery images so users are able to create galleries which link to external resources.

https://es.wordpress.org/plugins/wp-gallery-custom-links/

The plugin continues to work on the backend with Gutenberg active, but links are ignored on the frontend.

## Steps to Reproduce (for bugs)

1. Install the WP Gallery Custom Links plugin and activate it
2. Add a Gallery block to a post and specify custom URLs in some images
3. Save the post
4. View the post

Firefox and Chrome

## Expected Behavior

The custom links added to gallery images should appear on the frontend

## Current Behavior

The custom links added to the gallery images are not appearing on the frontend, gallery images are not clickable

**Comment by danielbachhuber** [comment]
Related #1451

**Comment by danielbachhuber** [comment]
I've [documented this incompatibility](https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/filter-post-gallery.md) in the migration guide.

**Comment by antpb** [comment]
Going to close as discussed in the recent core-media meeting in favor of keeping things focused on https://github.com/WordPress/gutenberg/issues/1451 

Support for the post_gallery filter will be solved with a fallback to the gallery shortcode.
