### ISSUE TITLE
Docs: Add missing supports to "Block API Reference > Supports" page

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#59735]
[The Supports page](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/) on the Block Editor Handbook should list all the support available for the latest Gutenberg. However, when checked against [the block's JSON schema](https://github.com/WordPress/gutenberg/blob/trunk/schemas/json/block.json), support for the following seems to be missing:

- color.heading
- color.button
- color.enableContrastChecker
- background
- background.backgroundImage
- background.backgroundSize
- renaming
- shadow

**Comment by gaambo** [comment]
Since I had to look those up yesterday, I decided to create a PR which documents those: https://github.com/WordPress/gutenberg/pull/59862
