### ISSUE TITLE
Open the Patterns Inserter when engaging the zoom mode quick inserter

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#59738]
Currently in zoom out mode, the quick inserter opens a popup suggesting four patterns to add. 

Instead, this inserter should open the Inserter open, with the "Patterns" tab active and the "Featured" category open. This brings the user into a more helpful composition view where you can properly search for and explore patterns, rather than requiring another step to get there.

### Tasks 
- [ ] Interacting with the quick inserter should not disengage zoom out mode ([related](https://github.com/WordPress/gutenberg/pull/56891)).
- [ ] Adjust UX to open the Inserter with "Patterns" tab active when engaging with the zoom out quick inserter. 

### Visual 
![CleanShot 2024-03-11 at 06 01 32](https://github.com/WordPress/gutenberg/assets/1813435/faeda134-9216-4cfc-8e79-ce54b13be258)

**Comment by richtabor** [comment]
This is the UX side of https://github.com/WordPress/gutenberg/issues/59738.

**Comment by draganescu** [comment]
In both this and the design issue I don't understand what does the control do since we are already in zoomed out mode with the sidebar open.
