### ISSUE TITLE
Add back Blocks and Media tabs within zoom out mode

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#59740]
Let's consider reverting https://github.com/WordPress/gutenberg/pull/59245. 

Instead of blocking access to blocks and media tabs within the Inserter when using zoom out mode, let's lean in on zooming out when the patterns tab is active (https://github.com/WordPress/gutenberg/issues/44585), and zooming back in when the other tabs are active. 

### Visual 

![CleanShot 2024-03-11 at 06 18 55](https://github.com/WordPress/gutenberg/assets/1813435/b1f48d22-2f48-41f5-b7be-9162b3a42a51)

**Comment by draganescu** [comment]
Closed by #59750
