### ISSUE TITLE
Docs: The theme.json reference is missing documentation for the fluid font size properties.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#59747]
## What problem does this address?

The properties added in https://github.com/WordPress/gutenberg/pull/53081 are in the theme.json schema but not in the theme.json reference here: https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/#typography

## What is your proposed solution?

Add the documentation.

**Comment by t-hamano** [comment]
I believe this issue is fixed in #61024, so I'll close it.
