### ISSUE TITLE
6.5-rc1: `ref` may be `null` from `getElement()` in some element bindings

### ISSUE THREAD

**Issue by wongjn** [WordPress/gutenberg#59757]
### Description

`getElement()` does not seem to work consistently and returns `null` in some situations. I believe that the ref to the HTML element should be available, since:
- [The documentation for `wp-style`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-interactivity/packages-interactivity-api-reference/#wp-style) does not explicitly state `state.*` cannot be used.
- [The documentation for *Accessing data in callbacks*](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-interactivity/packages-interactivity-api-reference/#accessing-data-in-callbacks) demonstrates usage of `getElement()` in a derived state:
  ```js
  const { state } = store( "myPlugin", {
    state: {
      get someDerivedValue() {
        const context = getContext();
        const { ref } = getElement();
        // ...
      }
    }
  ```
 
[Ticket raised in WordPress Trac](https://core.trac.wordpress.org/ticket/60744) (wasn't sure where to report this!).

### Step-by-step reproduction instructions

1. Install and set up WordPress 6.5-RC1
2. Activate Twenty Twenty-Four theme.
3. Append the following code to any template (i.e. `templates/home.html`):
   ```html
   <!-- wp:html -->
   <div data-wp-interactive="test">
     <div data-wp-bind--foo="state.foo"></div>
     <div data-wp-bind--foo="actions.foo"></div>
     <div data-wp-bind--foo="callbacks.foo"></div>
     <div data-wp-class--foo="state.foo"></div>
     <div data-wp-class--foo="actions.foo"></div>
     <div data-wp-class--foo="callbacks.foo"></div>
     <div data-wp-style--foo="state.foo"></div>
     <div data-wp-style--foo="actions.foo"></div>
     <div data-wp-style--foo="callbacks.foo"></div>
     <div data-wp-text="state.foo"></div>
     <div data-wp-text="actions.foo"></div>
     <div data-wp-text="callbacks.foo"></div>
   </div>
   <!-- /wp:html -->
   ```
4. Create a `test.js` file in the root of `twentytwentyfour`:
   ```js
   import { store, getElement } from '@wordpress/interactivity';

   store( 'test', {
     state: {
       get foo() {
         const { ref } = getElement();
         console.log( 'state.foo:', ref );
       },
     },
     actions: {
       foo() {
         const { ref } = getElement();
         console.log( 'actions.foo:', ref );
       },
     },
     callbacks: {
       foo() {
         const { ref } = getElement();
         console.log( 'callbacks.foo:', ref );
       },
     },
   });
   ```
5. Append the following code to `functions.php`:
   ```php
   add_action(
     'wp_enqueue_scripts',
     function () {
       wp_enqueue_script_module(
         'test',
         get_theme_file_uri( 'test.js' ),
         array( '@wordpress/interactivity' )
       );
     }
   );
   ```
6. Go to a webpage that renders the modified template from step 3.
7. Open browser developer tools, observe that `null` is output in the console, instead of the JavaScript DOM object representing an element.

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/11310624/799ac25c-c9aa-4ac2-85cf-6ecad887dcfd)

### Environment info

- WordPress 6.5-RC1
- Twenty Twenty-Four 1.0
- Windows 11
- Chrome Version 122.0.6261.112

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by cbravobernal** [comment]
Hi there!

I hope I can answer all your questions:

> [The documentation for wp-style](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-interactivity/packages-interactivity-api-reference/#wp-style) does not explicitly state state.* cannot be used.

You can use state in `wp-style`, but in needs the style property as a second parameter.

```php
// render.php

<div data-wp-style--color="state.foo"></div>
```

```js
//view.js

const { state } = store("test", {
  state: {
    color: "red",
    get foo() {
      return state.color;
    },
  },
```
Will print `<div data-wp-style--color="state.foo" style="color: red;"></div>`

`refs` are null for the directives you provided, but using them with events will give the HTML referenced.

For example 

```php
// render.php
<div data-wp-watch="state.foo"></div>
```

```js
// view.js
const { state } = store("create-block", {
  state: {
    get foo() {
      const { ref } = getElement();
      console.log("state.foo:", ref);
    },
  },....
```

Will log:

```html
<div data-wp-watch="state.foo"></div>
```

I will add the list of directives that provides a reference to the documentation to avoid misunderstandings 😄

**Comment by luisherranz** [comment]
> I will add the list of directives that provides a reference to the documentation to avoid misunderstandings 😄

Technically, all directives can access the element reference, but only after the reference has been attached to the DOM element 🙂

This is not straightforward, so I'll try to explain.

The Interactivity API is using Preact underneath. In (P)React applications, a reference to a DOM element is `null` until the component has been mounted.

```js
const Comp = () => {
  const ref = useRef(); // null on initial render 
  return <img ref={ref}>
}
```

In this component, `ref` is null until the component has been mounted and the reference is attached to the real DOM element.

You can access the reference in a `useEffect` hook because that hook doesn't run immediately, it runs once the component has been mounted.

```js
const Comp = () => {
  const ref = useRef(); // null on initial render
  useEffect(() => {
    console.log(ref); // it's not null at this point 
  })
  return <img ref={ref}>
}
```

The exact same is happening in the Interactivity API because it is using `useRef` underneath. And that's the reason that `ref` is always defined in `data-wp-init` and `data-wp-watch`, because those directives run inside a `useEffect` hook.

By the way, the reference can't only be `null` when the islands are hydrated, but also when elements appear/disappear from the DOM (for example in client navigation or in the upcoming`data-wp-show`), so people need to be careful and always check if `ref` is `null` in their getters.

By the way, if someone wants to know the value of an attribute in a getter, they can use `attributes` instead, which always exists:

```js
store("myPlugin", {
  state: {
    get someValue() {
      const { ref, attributes } = getElement();
      return ref.getAttribute("data-some-value"); // wrong
      return attributes["data-some-value"]; // right 
    }
  }
})
```

**Comment by sirreal** [comment]
> By the way, the reference can't only be `null` when the islands are hydrated, but also when elements appear/disappear from the DOM (for example in client navigation or in the upcoming`data-wp-show`), so people need to be careful and always check if `ref` is `null` in their getters.

This is not reflected in the types right now but should be. `getElement().ref` has type `HTMLElement`. I'll open a PR to make that nullable.

**Comment by sirreal** [comment]
> This is not reflected in the types right now but should be. `getElement().ref` has type `HTMLElement`. I'll open a PR to make that nullable.

That's a bigger undertaking than I expected. I'll try to make it happen, but we have to enable `strictNullChecks` so it's more work than just fixing a type. Starting that work in https://github.com/WordPress/gutenberg/pull/59865.

**Comment by DAreRodz** [comment]
I've created a PR to update the `ref` documentation.

- https://github.com/WordPress/gutenberg/pull/59868

**Comment by getdave** [comment]
Question: does this affect WP 6.5 and will we need a fix?

**Comment by cbravobernal** [comment]
> Question: does this affect WP 6.5 and will we need a fix?

No 😄, we can close the ticket.

**Comment by sirreal** [comment]
https://github.com/WordPress/gutenberg/pull/59865 is landing imminently which should produce higher quality types for the interactivity package in the next release (including possible nulls).
