### ISSUE TITLE
Merge REST API font face controller hardening from WP-Dev

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#59766]
## What problem does this address?

Changeset [r57804](https://core.trac.wordpress.org/changeset/57804) in WordPress-Develop needs to be merged to Gutenberg's compatibility shim for the Font Face REST API endpoint. 

WP-Dev commit message:

```
REST API: Remove unnecessary upload overrides in font face controller.

This removes settings that are the default value or required for side-loading from the `WP_REST_Font_Faces_Controller::handle_font_file_upload()`. 

This is to harden the endpoint and future proof against any changes to `wp_handle_upload()` and related functions/security checks.

Props peterwilsoncc, dd32.
Fixes [#60741](https://core.trac.wordpress.org/ticket/60741).
```

**Comment by andrewserong** [comment]
Thanks for opening the issue! I've just removed this issue from the Gutenberg 17.9 milestone as the linked PR #59767 already has it attached (I _think_ we usually only have PRs in the milestone).
