### ISSUE TITLE
Make the delete menu confirm dialogs consistent

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#59788]
### Description

There's at least two confirm dialog shown when deleting a navigation menu>

- From the navigation lock inspector > Settings > Advanced > Delete menu
- From the editor navigaiton panel > Design > Navigation > {menu name} > Actions ellipsis button > Delete

Screenshots:

![delete menu from inspector](https://github.com/WordPress/gutenberg/assets/1682452/f5289193-267d-4fd6-9722-c100e964fa41)

![delete menu from navigation screen](https://github.com/WordPress/gutenberg/assets/1682452/a7b6f735-0d67-446b-9992-7367e3e66752)

These two confirm dialogs should look very similar but they have differences in terminology, heading name of the buttons.
Under the hood they use different components but that's fine as long as the design and user experiences are as consistent as possible.

- The first one is [an inspector control that uses a Modal dialog](https://github.com/WordPress/gutenberg/blob/f6531c3a708f7aade1f9b6c6711cfa8c1da3e89d/packages/block-library/src/navigation/edit/navigation-menu-delete-control.js).
- The second one is a [ConfirmDialog](https://github.com/WordPress/gutenberg/blob/f6531c3a708f7aade1f9b6c6711cfa8c1da3e89d/packages/edit-site/src/components/sidebar-navigation-screen-navigation-menu/delete-modal.js).

At the very least they should:
- Etiher both have a heading or omit it (better: make it visually hidden).
- Either both incude the menu name in the heading or omit it.
- Either both have an X close button or omit it.
- Use the same casing for 'Navigation menu'.
- Use the same buttons height.
- Use the same name for the confirm action: genereally WordPress doesn't use 'Confirm', it rather uses the more specific action name, in this case it should be 'Delete'.

Ideally, they should use the same component.

### Step-by-step reproduction instructions

- Go to the site editor.
- Select a Navigation block that does have a menu.
- In the Navigation block inspector, go to the Settings tab, scroll down to 'Advanced', expand it and click 'Delete menu'.
- Observe the confirmation dialog (actually a Modal component).
- Go to the navigation screen: Design > Navigation > {menu name} > Actions ellipsis button > Delete
- Observe the confirmation dialog (actually a ConfirmDialog component).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Good issue. My suggestion would be to go with the second one, always, it's clearer and more actionable.

**Comment by afercia** [comment]
There's already a PR https://github.com/WordPress/gutenberg/pull/59825 that aligns the the to dialogs to the second one. A quick review would be appreciated.
