### ISSUE TITLE
Page title: selecting and pasting causes unexpected results

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#59798]
### Description

I found 2 separate issues pasting into the Page Title on 6.5-RC-2. (I assume they're related, so opening as a single ticket, but happy to split up if desired)

1. "OriginalPastedOriginal"
If you start with a page title of "Original", select it JUST RIGHT, and try to paste "Pasted" over it, you can end up with a title of "OriginalPastedOriginal"

Video Demonstration:

https://github.com/WordPress/gutenberg/assets/945157/81523df8-8b32-4cf7-bd4b-e58d223e4602

2. Multiple Pastings

Admittedly another bit of an edge case, but if you do the following:

a) Select your current page title and paste a new one over it. (seems fine. note that the title is not highlighted)
b) Select (doubleclick) the new current page title and paste over it again (seems fine, but not that this time the title IS highlighted)
c) Paste one more time. You'll now find yourself with the pasted text being appended to the page title, instead of overwriting it, despite the fact that the title was highlighted to begin with and thus should have been replaced.

Video Demonstration

https://github.com/WordPress/gutenberg/assets/945157/7cb61859-e6df-44fb-8da8-53322c4210d9

### Step-by-step reproduction instructions

1. "OriginalPastedOriginal"
If you start with a page title of "Original", select it JUST RIGHT, and try to paste "Pasted" over it, you can end up with a title of "OriginalPastedOriginal"

2. Multiple Pastings

a) Select your current page title and paste a new one over it. (seems fine. note that the title is not highlighted)
b) Select (doubleclick) the new current page title and paste over it again (seems fine, but not that this time the title IS highlighted)
c) Paste one more time. You'll now find yourself with the pasted text being appended to the page title, instead of overwriting it, despite the fact that the title was highlighted to begin with and thus should have been replaced.

### Screenshots, screen recording, code snippet

(in original post)

### Environment info

WordPress 6.5-RC-2, Twenty Twenty-Three theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MadtownLems** [comment]
Tagging @getdave and @youknowriad (per dave's request)

**Comment by annezazu** [comment]
Digging into this to replicate and I can't. I'm using 6.5 RC2 without any plugins active using TT4. To be safe, I tested with TT3 and still can't replicate:

https://github.com/WordPress/gutenberg/assets/26996883/dfc84173-d6a8-40cd-b10e-15dbf7b2c7c9

Can you confirm you don't have any browser extensions running or additional plugins? From what I can see, at least ACF is turned on :)

**Comment by MadtownLems** [comment]
> Can you confirm you don't have any browser extensions running or additional plugins?

I reconfirmed and replicated both issues on a totally blank install (no plugins) with 2024.  However, after disabling browser extensions, I could no longer replicate the first issue ("OriginalPastedOriginal"), so perhaps a browser extension issue was causing that one. Thank you for trying to replicate, and I'll be sure to test without extensions next time.

The second issue, however, still remains easily to replicate.

Looking at it a bit more, I think the root of the issue is that the Title is sometime still highlighted after pasting over it.  Standard behavior when pasting over a selection is to end with nothing selected, and the cursor at the end of what was just pasted in. What's happening here is the text still LOOKS selected (but isn't acting like it).  So when I paste again, the text gets appended instead of overwriting.

**Comment by annezazu** [comment]
For the second issue, is this a change from 6.4? If you haven't tested, no worries. I'll loop back on this when I can.

**Comment by MadtownLems** [comment]
> For the second issue, is this a change from 6.4?

Just tested, and it looks to behave the same on 6.4 - so not a change from 6.4, no.

**Comment by annezazu** [comment]
Got it! I just want to rule this out of being a 6.5 issue with where we are in the cycle. Removing from the board for now.

**Comment by ironprogrammer** [comment]
Possibly related: #51047. The duplication of the original title before and after the pasted text is quite similar.

**Comment by Mamaduka** [comment]
I can still reproduce the bug on the latest Gutenberg trunk. I think the issue is coming from the [custom paste handler](https://github.com/WordPress/gutenberg/blob/46f9fe0f31bf9ce5f6210cad96074206e90527e6/packages/editor/src/components/post-title/index.js#L196). If I remove it temporarily, everything works as expected.

**Comment by Mamaduka** [comment]
Fixed in #64665.

**Comment by MadtownLems** [comment]
> Fixed in #59798.

I think you may have accidentally included a link back to this same thread instead of the PR?

**Comment by Mamaduka** [comment]
@MadtownLems, thanks for catching that. It should be fixed now.
