### ISSUE TITLE
Gallery: Invalid caption type when selecting uncaptioned image

### ISSUE THREAD

**Issue by brandonpayton** [WordPress/gutenberg#5980]
## Issue Overview
When inserting a Gallery block and populating with uncaptioned images, selecting an image causes the image's caption attribute to be set with the wrong type. The following error is printed to the dev tools console:

    Invalid value of type string passed to RichText (expected array). Attribute values should be sourced using the `children` source when used with RichText.

    See: https://wordpress.org/gutenberg/handbook/block-api/attributes/#children

## Steps to Reproduce (for bugs)

1. Use a development build of Gutenberg.
1. Open the Chrome dev tools.
1. Insert a Gallery block.
2. Add uncaptioned images to the gallery.
3. Click on an uncaptioned image in the gallery.
4. Observe the error in the dev tools console.

Environment: Chrome 65.0.3325.181 on macOS 10.13.4.

## Expected Behavior
No error and maintaining correct type for one of the image's `caption` attribute.

## Current Behavior
An error is printed to the console, and apparently, an image's `caption` attribute is set with a string instead of an array.

**Comment by brandonpayton** [comment]
I'm up for taking this but am not claiming until I have time to look at it.

**Comment by talldan** [comment]
@brandonpayton this one seems to have resolved itself in the intervening time. I'm unable to reproduce it in a current build. Happy for it to be closed?

**Comment by brandonpayton** [comment]
Thanks, @talldan. I'm also unable to reproduce. Let's close it.
