### ISSUE TITLE
Pattern Overrides: Explore surfacing the pattern 'schema'

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#59815]
## Problem
See: https://github.com/WordPress/gutenberg/issues/53705#issuecomment-1983576920

Since #59268, a user creating a pattern is now asked to enter meaningful names for the block that are overridable. Combined together, these names create a schema that represents the overridable variable content of the pattern.

Making that schema more visible for a pattern would be helpful for users, potentially when the pattern is being edited?

@youknowriad, any additional info you'd like to provide for this issue?

**Comment by youknowriad** [comment]
I think it would be good to have some designs here. cc @SaxonF but the idea would be that in the pattern sidebar (document sidebar), we show the list of bound blocks (I guess it can be close to the "content" section we have for templates)

**Comment by SaxonF** [comment]
> I guess it can be close to the "content" section we have for templates

+1

**Comment by talldan** [comment]
I'll start looking into this 👍
