### ISSUE TITLE
Pattern Overrides: Refactor pattern (`wp:block`) block to use the block binding editing API

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#59817]
## What problem does this address?
As mentioned in https://github.com/WordPress/gutenberg/issues/53705#issuecomment-1983576920, it'd be good to explore making the pattern block use the block bindings `useSource` API that was introduced in #58085.

edit: `useSource` was replaced in [Block bindings: don't use hooks](https://github.com/WordPress/gutenberg/pull/60724#top), so this issue should now be about using that new block bindings editing API.

**Comment by SantosGuillamot** [comment]
Note here that the `useSource` API will likely change during this release cycle. So we should probably wait to address this until that is done.

Having said that, I started [this branch](https://github.com/WordPress/gutenberg/compare/trunk...experiment/use-bindings-editor-apis-in-pattern-overrides) as an experiment to see how it could work. It's on my to-do list to review it and open an experimental PR at some point.

**Comment by talldan** [comment]
@SantosGuillamot How much time do you think that will take?

Hopefully it isn't something that will end up being merged very close to the 6.6 beta, I'd rather see these changes made early, and pattern overrides can even help inform the implementation.

**Comment by SantosGuillamot** [comment]
Editing the value of the sources, which is what is needed for this use case, it's planned to be the top priority of block bindings for 6.6: [link](https://github.com/WordPress/gutenberg/issues/53300#issuecomment-1994722821). And to do that, the API must meet the requirements for pattern overrides.

I can't say how much time it will take to be ready, but I feel confident that it will be available earlier in the release process.

**Comment by talldan** [comment]
@SantosGuillamot Is there an update on the status of `useSource`? Let me know if there's anything I can help with reviewing.

**Comment by SantosGuillamot** [comment]
We've spent some time to understand better the different use cases and requirements for `useSource` to ensure that whatever we build works for the different sources, including `pattern/overrides`. I feel we have a better picture right now. I'm working on reorganizing the block bindings project on GitHub, and it's clearer how to approach it after that.
