### ISSUE TITLE
Interactivity API: Include `preact/debug` when `WP_DEVELOPMENT_MODE` is enabled.

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#59829]
## What problem does this address?

When I attended [a developer hours regarding the Interactivity API](https://www.meetup.com/learn-wordpress-online-workshops/events/299511132), I saw a participant ask if they had access to developer tools for debugging.

## What is your proposed solution?

I temporarily made the following changes and was able to confirm that [Preact Devtools](https://preactjs.github.io/preact-devtools/) worked on the front end.

```diff
diff --git a/packages/interactivity/src/init.js b/packages/interactivity/src/init.js
index fb510a9c00..79df6745d0 100644
--- a/packages/interactivity/src/init.js
+++ b/packages/interactivity/src/init.js
@@ -1,6 +1,7 @@
 /**
  * External dependencies
  */
+import 'preact/debug';
 import { hydrate } from 'preact';
 /**
  * Internal dependencies
```

![image](https://github.com/WordPress/gutenberg/assets/54422211/975f9138-e255-4752-9767-4c1d13ad17b8)

Perhaps we need to detect whether a project is in development mode or not, but I think this tool will be useful to developers.

**Comment by cbravobernal** [comment]
Yep. But we will still need to make extra adjustments. At least, we should name the Directives component with each directive, so that way we don't have a huge list of Directives component 😅
