### ISSUE TITLE
Typo in source string

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#59824]
### Description

Typo in the following source string: https://translate.wordpress.org/projects/wp-plugins/gutenberg/stable/en-gb/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=17312673&filters%5Btranslation_id%5D=114782074.

“interactivty” should be “interactivity”.

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
Thanks for the report.

This issue was fixed by #59796. It will be shipped to the next Gutenberg plugin version 18.0.

**Comment by ghost** [comment]
OK. Thanks for that, I should have checked more carefully.
