### ISSUE TITLE
i18n translations domains not auto-registering

### ISSUE THREAD

**Issue by mattyrob** [WordPress/gutenberg#5984]
## Issue Overview

The current [documentation](https://github.com/WordPress/gutenberg/tree/master/i18n) indicates that the i18n functions such as `__()`, do take a domain argument. Adding these into a plugin results in a console error "Jed localization error: 
Error: Domain `xxx` was not found."
## Steps to Reproduce (for bugs)

1. Install and activate the Gutenberg Example plugin 
2. Open up the Gutenberg editor.
3. Check the error console for the error message
4.

Tested on Safari 11.1, confirmed in FF 59.0.2 on MacOS 10.13.4

## Expected Behavior

There should be no error, blocks added to Gutenberg should have the domain added automatically and translations should work out of the box.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by aduth** [comment]
You will need to add the locale data (strings) for your domain via `wp.i18n.setLocaleData`. The documentation is not accurate here, and lacks the `domain` argument which is expected for the `setLocaleData` function.

The documentation in the newly-published i18n package is more up to date:

https://github.com/WordPress/packages/tree/master/packages/i18n

It's expected that the folder within Gutenberg will be replaced by a reference to this module.

Keeping this issue open until:

- Gutenberg is updated to use `@wordpress/i18n` module
- Better example documentation for plugins adding their own locales
