### ISSUE TITLE
Link UI obscuring linked text in Site Editor

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#59840]
In the Site Editor (only) when a new link has been created the resulting link preview is placed on top of the linked text. It should be offset as it is in the Post Editor.

## Replication Steps

- Open Site Editor
- Navigate to `Pages`
- Choose any page to edit
- On that page add a paragraph block
- Link some text and create the link
- See the link preview obscures the linked text

## Screencapture

https://github.com/WordPress/gutenberg/assets/444434/431a7491-bfe3-4442-b56e-f5ffe69dfcff

**Comment by getdave** [comment]
cc'ing contributors who I know have worked a lot on the Link UI in this cycle:

@jeryj @scruffian @draganescu (and me).

**Comment by jeryj** [comment]
Is this only with Twenty Twenty Four?

**Comment by getdave** [comment]
> Is this only with Twenty Twenty Four?

Oh wow. Yes it is! It seems it only happens in TT4. What's going on there I wonder and is this a bug with that Theme?

**Comment by jeryj** [comment]
Maybe it's something with the default template files? If you save the template, the popover is positioned correctly. The bug seems isolated to unsaved (default) templates within TT4.

**Comment by getdave** [comment]
I verified this is not specific to the Link UI because the text highlight does the exact same thing:

<img width="1448" alt="Screen Shot 2024-03-14 at 09 48 37" src="https://github.com/WordPress/gutenberg/assets/444434/eb1be6bc-9d8c-4fb5-88f5-20fb92c317da">

I'm suspicious of `useAnchor`.

**Comment by getdave** [comment]
Ok I cannot replicate this any longer. I checked against RC2 and Gutenberg `trunk`. Possibly some kind of build error. It's very unusual.

Going to close.
