### ISSUE TITLE
Enhance List Block for adding Style color option in list-item also

### ISSUE THREAD

**Issue by pitamdey** [WordPress/gutenberg#59854]
## What problem does this address?
This is just a request for enhancement in the list block, we have the option of style colour, font size, appearance and all on selecting List but in its list-item, we also have this option like font size, appearance i.e. typography but not the style color. So we can add this option for the list item also

## What is your proposed solution?
The solution is to add a text colour option to list items if possible.

**Comment by aaronrobertshaw** [comment]
I had a few moments to spare so have put up a quick PR opting into color support for the list item block (https://github.com/WordPress/gutenberg/pull/59892).

@pitamdey if there are some other blocks you'd like to see adopt more color block supports feel free to create a PR and ping me for review. There's a [tracking issue for color support](https://github.com/WordPress/gutenberg/issues/43245) and [one for all design tools](https://github.com/WordPress/gutenberg/issues/43241) that might be of interest.
