### ISSUE TITLE
Wordpress 6.5 RC2 Firefox 123.0.1 lightbox doesnt work anymore

### ISSUE THREAD

**Issue by vilmantasr** [WordPress/gutenberg#59895]
### Description

After installing Wordpress 6.5 RC2 and opening my site (https://ramono.lt/ - Twenty Twenty-Four theme) using Firefox 123.0.1 (all extensions disabled) Lightbox functionality doesn't work anymore, same with Firefox Nightly. It is working using Google Chrome 122.0.6261.129.

### Step-by-step reproduction instructions

Opening site page with photos, clickink on photos, no more Lightbox functionality.

### Environment info

 WordPress: 6.5-RC2
- PHP: 8.2.15
- Server: LiteSpeed
- Database: mysqli (Server: 10.11.7-MariaDB-cll-lve / Client: mysqlnd 8.2.15)
- Browser: Firefox 123.0.1 (Windows 10/11)
- Theme: Twenty Twenty-Four 1.0
- MU-Plugins: None activated
- Plugins:
  * BBQ Firewall 20240306
  * Beam me up Scotty - Back to Top Button 1.0.19
  * Creative Commons 2022.09.1
  * Delete Expired Transients 2.0.7
  * Ivory Search 5.5.4
  * Limit Login Attempts Reloaded 2.26.7
  * Really Simple SSL 7.2.3
  * Simple Mastodon Verification 1.1.3
  * Site Kit by Google 1.122.0
  * SVG Support 2.5.5
  * The SEO Framework 5.0.5
  * UpdraftPlus - Backup/Restore 1.24.1
  * WordPress Beta Tester 3.5.5
  * WP Robots Txt 1.3.3
  * WP Super Cache 1.12.0
  * Yet Another Related Posts Plugin (YARPP) 5.30.10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by mia-204** [comment]
Hi :), did you find a solution for that issue? Would be great if you could post it here. I've got the same issue with Firefox, twenty twenty four and the native Wordpress Lightbox. Thanks in advance!
