### ISSUE TITLE
Find a spot for the "Help" section

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#599]
We have a spot for "Screen Options", it's this control panel icon button:

![screen shot 2017-05-02 at 10 11 41](https://cloud.githubusercontent.com/assets/1204802/25609494/cb9d9b0a-2f1f-11e7-99f9-e3dad039bd16.png)

However we haven't yet found a good new spot for "Help".

As we think about where to place this, let's keep in mind it's a feature that is likely to be useful to users very early on, and then perhaps no longer after that. 

Should it live in the adminbar?

**Comment by karmatosed** [comment]
The only way I think its ok having in admin bar is if we do this on all sections, not just editor. If its just editor, then it should be within that UI context.

**Comment by joyously** [comment]
> We have a spot for "Screen Options", it's this control panel icon button:

I can't see in the image anything that matches what you said.

**Comment by jasmussen** [comment]
We have started adding help text to the sidebar, in context. This feels superior to the old help dialog. As such, I'm going to close this for now, as solved by a different approach. We can re-open if need be.

Screenshots of contextual help:

![screen shot 2017-07-03 at 15 59 41](https://user-images.githubusercontent.com/1204802/27796053-e64b5be4-6008-11e7-9608-27374c751abb.png)

![screen shot 2017-07-03 at 16 00 08](https://user-images.githubusercontent.com/1204802/27796059-e7f5d910-6008-11e7-80c2-fc4d89b70d63.png)
