### ISSUE TITLE
Error adding blocks to the site editor

### ISSUE THREAD

**Issue by renatho** [WordPress/gutenberg#59917]
### Description

Adding blocks to the site editor is not working properly. It's returning an error that we can see in the console. After clicking many times, it's added many times at once.

### Step-by-step reproduction instructions

1. Navigate to the site editor.
2. Open any template.
3. Try to add a paragraph.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/876340/bd209534-257b-4758-9584-10c1e564e927

Sorry for the low quality, but GitHub just allowed me to upload a 10MB video. I clicked many times on "Paragraph", and it took effect after many clicks, adding all the paragraphs at once.

### Environment info

- A fresh site created only for this test.
- WordPress 6.4.3
- Gutenberg 17.9.0
- Chrome
- OSX

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @renatho

Can you share the error message displayed in the console?

**Comment by renatho** [comment]
Hi @Mamaduka!

It was `t.toString is not a function`, but I created a new fresh site to copy the whole error and it didn't happen anymore. Weird that it's the same WordPress and Gutenberg versions, with no changes in my Chrome since I opened the issue.
So I'm closing this issue, but I'll keep an eye and if it happens again I re-open this issue. 😉

**Comment by Mamaduka** [comment]
Thank you, @renatho!

**Comment by aleksatachev** [comment]
Hello. Is there any solution here? I can confirm that the issue still appears in 6.7.2. Easiest repro:
1. open https://try.new
2. go and create new page
3. select any of the predefined pages - I tried with business home and about page
4. click on any section you want

"This block has encountered an error and cannot be previewed." appears on the section and "t.toString" is not a function in the console.

Cannot change anything on the page before refresh, but on refresh I got the same. Any suggestions?

**Comment by Mamaduka** [comment]
I think this is a conflict with Chrome extensions. See: https://github.com/woocommerce/woocommerce/issues/50959#issuecomment-2315392104.

**Comment by aleksatachev** [comment]
thanks for the answer @Mamaduka ! I completely removed React dev tools and currently, it seems to work! I there any workaround to have the plugin anyway, while wp visual builder still works correctly?

**Comment by Mamaduka** [comment]
@aleksatachev, unfortunately, I'm unable to reproduce the issue. I've both React and Redux tools enabled.
