### ISSUE TITLE
Query Loop Block doesn't accept 0 items per page anymore

### ISSUE THREAD

**Issue by JulienGardair** [WordPress/gutenberg#59912]
### Description

Query Loop Block doesn't accept 0 items per page anymore, when 0 is entered it is automatically reversed to 1.

### Step-by-step reproduction instructions

Add QUERY LOOP BLOCK
choose Start Blank>Select a variation to start with>
any 

Then BAR click on display settings 
ITEMS PER PAGE [3 by default]
at the bottom is written 
Limit the pages you want to show, even if the query has more results. To show all pages use 0 (zero).
But when trying to change to 0, it goes back to 1.

This appeared since the addition by default of the pagination and interactivity allowing to go to the next pages without refreshing the page which is great, but the possibility to display all the posts with appropriate filters seems to still be a necessary option. 

### Environment info

WP 6.4.3
Gutenberg 17.9.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

Let me close this issue as the same issue has been reported in #51219.

**Comment by JulienGardair** [comment]
Sorry for the duplicate,
Also, I finally figured out what I was reading wrong:
"Limit the pages you want to show, even if the query has more results. To show all pages use 0 (zero)."
I assumed wrongly that this message was talking about the number of posts while it was talking about the number of pages that can be displayed in the pagination. 
Sorry about this confusion.
