### ISSUE TITLE
Need access to Document Overview in Mobile

### ISSUE THREAD

**Issue by rxbracho** [WordPress/gutenberg#59924]
## Description

The so-called “document overview” in the block editor provides a “list view” or an “outline” and it is invoked by the three offset lines. That icon is missing when editing from a mobile device, regardless of the browser used.

There used to be a most unsatisfactory work-around, namely to ask in Preferences that such “list view” be “always open”. When in Mobile, it would then open in such a view and you could work on it then, although you couldn’t get it back. You had to come out of editing and back in. Nowadays, however, it won’t even open in list view. It is simply inaccessible on a Mobile.

Thanks in advance.

## Expected behaviour

The solution I am after is to have the icon that opens the “document overview” (or even straight to “list view”) present in Mobile browsers, as it does on a desktop

## WordPress information
- WordPress version: 6.4.3
- Gutenberg version: 17.9.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty-Three

## Device information
- Device: Samsung S10 
- Operating system: Android 12.0
- Browsers: Samsung Internet 25.0.0.20, Firefox 123.1.0, Chrome 119.0.6045.194
- WordPress app version: NOT USING APP BUT MOBILE BROWSER

**Comment by dcalhoun** [comment]
👋🏻 @rxbracho. My understanding is that this is a request for mobile web browsers, not the mobile app for iOS and Android. I went ahead and updated the issue labels to reflect that, but let me know if that is incorrect. Thanks!

**Comment by rxbracho** [comment]
Thank you! It is quite a nightmare to navigate the multiple places where one can report issues regarding WordPress. Someone gave me this forum because I apparently had written the report in Wordpress.org and not here in Github.

**Comment by annezazu** [comment]
Thanks for opening this! I am going to close this out in favor of the prior issue on this same topic: https://github.com/WordPress/gutenberg/issues/50301 Please follow along there.
