### ISSUE TITLE
Possibility to add the Image caption on featured image

### ISSUE THREAD

**Issue by JulienGardair** [WordPress/gutenberg#59923]
Add caption to Block Featured image, just like we can on a regular Block Image
or/and
Have the possibility to set Feature Image as the source of a regular Block Image.

This would open a lot of different possibilities for portfolio websites.

**Comment by skorasaurus** [comment]
Hi, 

Thank you for reporting. This has been already requested at https://github.com/WordPress/gutenberg/issues/40946 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue by [subscribing](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/about-notifications)

**Comment by JulienGardair** [comment]
thank you sorry for the duplicate, I couldn't find it through my search.
