### ISSUE TITLE
Directory /wp-includes/blocks/navigation/ is listable after standard installation of 6.5-RC2

### ISSUE THREAD

**Issue by by** [WordPress/gutenberg#59932]
### Description

The directory /wp-includes/blocks/navigation/ is listable after performing a standard installation of Wordpress 6.5-RC2

### Step-by-step reproduction instructions

Go to //YourServerName/wp-includes/blocks/navigation/ and you will see the directory listing

### Environment info

Wordpress 6.5-RC2 on Debian 12 with current Apache2 and php8.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by by** [comment]
Solved w/ new version

**Comment by jordesign** [comment]
Thanks for following up @by - does that mean this issue can now be closed?

**Comment by by** [comment]
Yes, thanks.
