### ISSUE TITLE
Global styles: Active color variation outline is inverted

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#59948]
### Description

The currently selected color variation is showing as not having an outline, the opposite as what the typography variation does.

### Step-by-step reproduction instructions

Using TT4, go to Site editor > Styles

Select a color variation, check the outline of all the options

### Screenshots, screen recording, code snippet

<img width="327" alt="Screenshot 2024-03-18 at 12 02 07" src="https://github.com/WordPress/gutenberg/assets/3593343/9d269681-08e2-42e1-abdc-dc8f397a5df8">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sahiladit** [comment]
Is this issue occurring with all the elements?

**Comment by sahiladit** [comment]
Can you assign it to me?

**Comment by MaggieCabrera** [comment]
> Is this issue occurring with all the elements?

I only see this bug on the left sidebar. On the GS panel on the right under colors seems to be working fine. and it only happens to colors from what I can see.

**Comment by sahiladit** [comment]
I found no such issue in my system.If you still have this issue then you can comment some more screenshots .
