### ISSUE TITLE
Font Library: success message after font install stays in other font views

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#59947]
### Description

Success message after font installation doesn't disappear after navigating to a different font which is not installed, which is misleading in the current font context.

![font-success-message](https://github.com/WordPress/gutenberg/assets/1935113/57946b4c-ed40-46f5-bc51-38f1cc4b7d6b)

### Step-by-step reproduction instructions

1. Install a font from available font collection.
2. Observe that success message appears after installation.
3. navigate back and switch to another font from the list.
4. Observe that the success message still present in the UI which is misleading in the current font context.

### Environment info

- Wordpress - 6.4
- Gutenberg - latest

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Noting that I can replicate with 6.5 RC2. Adding this to the board to be addressed.
