### ISSUE TITLE
Enhance Pullquote Block for adding Style color option for citation also

### ISSUE THREAD

**Issue by pitamdey** [WordPress/gutenberg#59941]
## What problem does this address?
This is just a request for enhancement in the Pullquote block, Currently, we can change the colour of quotes but not the colour of the citation

## What is your proposed solution?
we can add separate colour option for citations also if possible

**Comment by aaronrobertshaw** [comment]
Hi @pitamdey 👋 

Just to clarify, your proposal is to allow different colors for the quote vs citation?

That would likely require refactoring the pullquote block to use inner blocks for the `cite` element. This is somewhat similar to [past proposals to make captions inner blocks](https://github.com/WordPress/gutenberg/issues/54787) for image-related blocks. Unfortunately, there hasn't been a lot desire for such features to push them forwards.

> we can change the colour of quotes but not the colour of the citation

My understanding is that you can change the color of the Pullquote block's citation.

<img width="1116" alt="Screenshot 2024-03-18 at 5 26 38 PM" src="https://github.com/WordPress/gutenberg/assets/60436221/9485b88a-05ba-4f42-a7d7-46c5b690f8da">

**Comment by pitamdey** [comment]
Thanks @aaronrobertshaw, I think this one is theme related issue so i will check it and report it to the core
