### ISSUE TITLE
The toolbar is not visible inside the full editor of the new product editor

### ISSUE THREAD

**Issue by veljkho** [WordPress/gutenberg#59954]
### Description

There is issue in WooCommerce, New Product Editor's full editor for the description section when having Gutenberg nightly build `vnightly-17.9.0-ec86a82` from March 18th 2024.

The issue is that the toolbar when editing description inside the full editor is not visible.

Creating this issue as potential issue in the future when you release the next Gutenberg version.

### Step-by-step reproduction instructions

[make sure the New Product Editor is turned ON in WC Settings > Advanced > Features]
1. Go to WooCommerce > All Products
2. Click to add a new product
3. Click on the description text area and then click to enter the full editor
4. Type some sample text and observe issue

### Screenshots, screen recording, code snippet

https://d.pr/i/h8UAmP

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@veljkho thanks for opening this issue! Can you clarify why you opened it here rather than in Woo's repo? This sounds like an issue with Woo.

**Comment by veljkho** [comment]
Hi @annezazu 

I might be guided improperly, sorry if I missed the place to report.
The issue is connected between WooCommerce and Gutenberg, so without Gutenberg plugin as active this issue is not present. It could be something inside Gutenberg that is affecting this, but only with the nightly build I got from [this place](https://github.com/Automattic/gutenberg-nightlies).

**Comment by annezazu** [comment]
Got it! That would be an issue for Woo to investigate still. Please open an issue here: https://github.com/woocommerce/woocommerce/issues  I'm going to close this out for now. In full transparency, I do work for Automattic and, as a result, work alongside folks in Woo and have alerted them to this to be safe as well.

**Comment by nathanss** [comment]
Hi @veljkho 

Thanks for raising this. We are aware and we already merged a fix for this issue. It should be fixed in 18.0. Here are the related PRs:

https://github.com/WordPress/gutenberg/pull/59800
https://github.com/woocommerce/woocommerce/pull/45650
