### ISSUE TITLE
Keep an inserted pattern within view when added to the page

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#59962]
Currently, selecting a pattern from the Inserter results in the pattern added to the bottom of the page, but does not give you any real indication that it has been successfully added—other than a snackbar notification. Each pattern is already focused when inserted, but if it's not one of the first patterns on a page, you wouldn't see where it's applied/focused.

I propose that when adding patterns to a page, the pattern should be within view. 

This way: 
- I don't have to scroll down to find the pattern added to my page.
- I have immediate confidence that my selection occurred (rather than relying solely on a snackbar). 
- I can quickly take the next steps, whether that means to move it, [shuffle it to another pattern](https://github.com/WordPress/gutenberg/pull/59251), or delete it. 

### Current

https://github.com/WordPress/gutenberg/assets/1813435/e0680f4b-c3a2-4923-8e65-79a9106de86e

**Comment by akasunil** [comment]
@richtabor Created PR https://github.com/WordPress/gutenberg/pull/62700 to resolve this issue.

**Comment by akasunil** [comment]
I guess we can close this issue too as it fixes in latest trunk as show in [video here](https://github.com/WordPress/gutenberg/pull/62700#issuecomment-2226556446)
