### ISSUE TITLE
usesContext applied with filter to core/navigation block is not passed to render filter

### ISSUE THREAD

**Issue by SamTyurenkov** [WordPress/gutenberg#59964]
### Description

I add custom context to navigation via filter:

```
const blockSettings = function ( settings, name ) {
	if ( name !== 'core/navigation' ) {
		return settings;
	}

	// Destructure settings.supports and remove typography
	settings.allowedBlocks = Object.assign( [
		'core/navigation-link',
		'core/navigation-submenu',
	] );

	const { usesContext } = settings;
	if ( usesContext.includes( 'mytheme/menuStyles' ) === false ) {
		settings.usesContext = Object.assign( [ ...usesContext, 'mytheme/menuStyles' ] );
	}

	return settings;
};

wp.hooks.addFilter(
	'blocks.registerBlockType',
	'mytheme/navigation',
	blockSettings
);
```

If i use `console.log(settings)` it seems to be properly applied to object in editor.

However, it's not in $block->context array during rendering with php:

```
add_filter(
    'render_block_core/navigation',
    function ( $attributes, $block_content, $block ) {
		if (empty($block->attributes)) return '';
		$navigation_post   = get_post($block->attributes['ref']);
		$new_block_content = do_blocks($navigation_post->post_content);

		$menu_styles = array_key_exists('menuStyles', $block->context) ? $block->context['menuStyles'] : 'header';

		return $block_content;
	},
    10,
    3
); 
```

Official documentation only provides example for custom blocks, but I suppose its a bug. 
Im on Wordpress 6.4.3

### Step-by-step reproduction instructions

1) Create any parent block that providesContext to children
2) Add navigation block as its child
3) Add javascript and php code suggested above and try to error_log();

### Screenshots, screen recording, code snippet

also usesContext is empty in php error_log();

![image](https://github.com/WordPress/gutenberg/assets/19373777/6dff8163-c9f6-4589-bf2f-82d5cae69a66)

but available in javascript console.log()

![image](https://github.com/WordPress/gutenberg/assets/19373777/6082b636-795d-48d1-8b53-03dafc333137)

### Environment info

Wordpress 6.4.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tellthemachines** [comment]
Hi there @SamTyurenkov!

The `blocks.registerBlockType` JS filter only changes the properties of the block as it's registered in the editor; the changes won't be saved or persisted in any way. If you want those changes reflected in the PHP, you need to add them via the [`register_block_type_args` filter](https://developer.wordpress.org/reference/hooks/register_block_type_args/).

Hope this helps!

**Comment by SamTyurenkov** [comment]
@tellthemachines Thank you!

This helped. Final code is:
```
add_filter( 'register_block_type_args', function($args, $block_type) {

	if($block_type != 'core/navigation') return $args;
	
	$args['uses_context'][] = 'mytheme/menuStyles';

	return $args;

},10,2 );
```
