### ISSUE TITLE
Pattern explorer not loading patterns in the site editor

### ISSUE THREAD

**Issue by dsas** [WordPress/gutenberg#59984]
### Description

The pattern explorer is not listing any patterns in the site-editor. The pattern explorer works in the post editor, and it works in the sidebar view.

### Step-by-step reproduction instructions

1. Go to Appearance → Editor
2. Click on the canvas on the right
3. Press the + icon at the top left of the screen
4. Press the patterns tab
5. Notice some pattern categories are listed and clicking on them previews a pattern
6. Go to the bottom of the category list and press "Explore all patterns"
7. Notice a huge dialog appears with categories to the left and a blank area to the right

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/93301/4541f475-a47f-4dd7-9750-8d687d32ee2e

### Environment info

I'm using GB trunk (f3c0586) with TT4 as the active theme. It also repros in GB 17.9.0 but not I'm told, in GB 17.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I was also able to reproduce this problem. It seems to be happening in WP6.4 as well. Strangely, this problem only seems to occur when the editor canvas is displaying a specific "page".

https://github.com/WordPress/gutenberg/assets/54422211/07737ed1-76a9-4af6-9210-848e96f0bdc2

**Comment by dsas** [comment]
Ah-ha thank you!  I tried bisecting but that was one of the issues tripping me up, and then issues with php/wp versions.

I wonder if changes in GB since WP6.4 have made this issue more prominent.
