### ISSUE TITLE
Site Editor: renaming a navigation menu resets its content

### ISSUE THREAD

**Issue by jsnajdr** [WordPress/gutenberg#59991]
Steps to reproduce:
1. In the Site Editor, go to the Navigation page
2. Verify there is a a navigation item there, and its content is a Page List block, showing the list site's pages.
3. In the navigation's context menu, select Rename
4. Rename the navigation

Result: the navigation is not only renamed, but its content is also reset to empty string (`''`).

Here is a video:

https://github.com/WordPress/gutenberg/assets/664258/b76ed45d-afd7-46ce-9e7a-ac73f6741f9b

Note that the "Sample Page" item (it's part of the Page List block) has disappeared after the rename.

The REST request to rename looks like this:

<img width="392" alt="Screenshot 2024-03-19 at 13 40 21" src="https://github.com/WordPress/gutenberg/assets/664258/c0482e64-cc2b-4812-8a4f-e834211a361e">

and this is the response:

<img width="587" alt="Screenshot 2024-03-19 at 13 41 53" src="https://github.com/WordPress/gutenberg/assets/664258/31e57080-85dc-455b-834b-2581fc03f6f0">

Note that not only the `title` field has changed, but also the `content` has been reset.

@tellthemachines Maybe there is something wrong with the `WP_Navigation_Fallback` class in Core? If I understand it correctly, `wp_navigation` is just another custom post type, and its REST requests are handled by the vanilla `posts` controller. Editing individual fields should work without resetting the others. It's only `WP_Navigation_Fallback` that patches the schema somehow, including the `content.*` fields.

**Comment by annezazu** [comment]
What version of Gutenberg or WordPress are you using?

**Comment by jsnajdr** [comment]
I found the bug when working with `trunk` Gutenberg in a local dev environment. With a `wp-env` WordPress that identifies as 6.6-alpha-57841 in the Dashboard, a fairly recent Docker image.

Now I tested it also on a WordPress.com site and the bug is there, too. Although the REST requests are mapped to different endpoints, namely `PUT public-api.wordpress.com/wp/v2/sites/:site/navigation/:id`. When I `PUT` a `{ id, title }` edit here, the response returns the `content` field reset to an empty string.

**Comment by Mamaduka** [comment]
I can also reproduce the issue with WP 6.4 and the latest trunk. The bug is probably a combo of the `__experimentalSaveSpecifiedEntityEdits` action and the `WP_Navigation_Fallback` REST API filter.

**Comment by jsnajdr** [comment]
I was stepping through `__experimentalSaveSpecifiedEntityEdits` while investigating this and it does everything right. It's solely the REST endpoint: you POST a `{ title }` edit and get modified `content` back.

**Comment by Mamaduka** [comment]
It turns out the `block_core_navigation_update_ignore_hooked_blocks_meta` filter caused the bug — my proposed fix #60071.

**Comment by ockham** [comment]
Cross-referencing https://core.trac.wordpress.org/ticket/61550, which is the same issue, but for templates.
