### ISSUE TITLE
Image Block: Need resize handles

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#600]
We should add resize handles to the image block, so you can give it your custom size. 

Mockup:

![resize-handles](https://cloud.githubusercontent.com/assets/1204802/25610684/7fb8e9a6-2f24-11e7-81bd-e3dde6f350a6.png)

**Comment by mixxster** [comment]
I really wish this was a higher priority.

**Comment by jasmussen** [comment]
Removing the "Low priority" because feedback, including ☝️  :)
