### ISSUE TITLE
Can't select pattern on editor on a classic theme (CPTs, posts or pages)

### ISSUE THREAD

**Issue by ltrihan** [WordPress/gutenberg#60009]
### Description

I created a pattern that I try to call via the editor (of a CPT, a post or a page), the pattern appears in the list of blocks but nothing happens if I click on it

Sorry if the issue already exists, I'm a newbie, I tried to searched but [with the pattern keyword](https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+is%3Aopen+pattern) : 848 results 🫠

### Step-by-step reproduction instructions

1. On a classic theme, create a pattern thanks to the page /wp-admin/edit.php?post_type=wp_block
2. Go to any post type, and try to load it from the editor

### Environment info

Custom classic theme in 6.4.3 and tested in 6.5-RC3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hi @ltrihan - I'm unable to recreate this when using one of the bundled classic themes (like TwentyTwenty, TwentyNineteen etc). Are you able to try with one of the older bundled themes as well and see if it is reproducible?

**Comment by ltrihan** [comment]
Hi @jordesign, same problem still without any plugin, tested on TwentyTwenty and TwentyNineteen, on 6.5-RC and 6.4.3

**Comment by ltrihan** [comment]
UPDATE : sorry it's my bad, it's because I made a nasty copy and paste of a composition on an FSE theme where there were template parts header and footer. By deleting them it works 👌🏻 sorry for the wasting time 🫣
