### ISSUE TITLE
Clicking template when on page

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#60011]
## What problem does this address?
When editing a page in the site editor and clicking outside an editable block (title, featured image, post content) we currently show a toast notification to edit the template. The original intention of this was to provide quicker, more contextual pathways towards editing a template a page uses. Feedback, and further testing, suggests this might not be necessary and removing may actually help force people to add content to pages instead.

## What is your proposed solution?
I'd like to propose two changes:
- Remove the toast notification
- Adjust behaviour so when you click part of a template that is not editable, we select the closest editable block. The definition of closest would be 1. The first child within the clicked block that is editable 2. If no child exists, move to sibling blocks and find editable child 3. if no sibling, move up the tree until a sibling exists.

With https://github.com/WordPress/gutenberg/pull/60010 we are making headers/footers editable which gives you quicker access to a global block that may need to be adjusted as pages are added to your site. Editing the rest of a template is less common.

As a step after this we can make template edit/swapping a more prominent part of the [page inspector](https://github.com/WordPress/gutenberg/issues/59689).

**Comment by noisysocks** [comment]
Would we still need the flash of dotted outlines around editable blocks?

**Comment by SaxonF** [comment]
@noisysocks yep that's still useful , we're just taking the next step and selecting something
