### ISSUE TITLE
Potential regression in TemplateLock behavior.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#60026]
### Description

I've received some information (DM) that 6.5 may have introduced a regression in the TemplateLock behavior. 

### Step-by-step reproduction instructions

The conditions are supposed to be the following:

 - A container with "templateLock=all" (can be top level `wp.data.dispatch( 'core/block-editor' ).updateSettings( { templateLock: 'all' } )` )
 - An unlocked nested container within that locked container.
 - You should be able to transform blocks that are within the nested container but apparently it's not possible anymore in 6.5.

Unfortunately, I don't have more information than that. This needs to be investigated to confirm whether there's a real regression or not.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by youknowriad** [comment]
I've received more information and you should be able to reproduce this issue using this code (when creating a new post)

```
add_filter(
	'register_post_type_args',
	function( $args, $post_type ) {

		if ( 'post' !== $post_type ) {
			return $args;
		}

		$args['template'] = [
			[
				'core/paragraph',
				[
					'placeholder' => 'Your content',
				],
			],
			[
				'core/group',
				[
					'templateLock' => false,
				],
				[
					[
						'core/paragraph',
						[
							'placeholder' => 'You should be able to transform this',
						],
					]
				]
			],
		];

		$args['template_lock'] = 'all';

		return $args;

	},
	10,
	2
);
```

**Comment by youknowriad** [comment]
A potential regression of #57892 cc @ntsekouras

**Comment by annezazu** [comment]
Adding to 6.5 to keep track but unclear if it should be for a point release or to fix in the coming days.
