### ISSUE TITLE
MultiSelectionInspector: incorrect number of words when partial blocks are selected

### ISSUE THREAD

**Issue by jsnajdr** [WordPress/gutenberg#60025]
Steps to reproduce:
1. Select parts of adjacent paragraphs. (See screenshot below)
2. Look at the `MultiSelectionInspector`.
3. It shows the total number of words that are in the selected blocks, but it should count only the words that are really selected.

Example where there are only 2 words selected, but the inspector says 30:

<img width="862" alt="Screenshot 2024-03-20 at 10 41 15" src="https://github.com/WordPress/gutenberg/assets/664258/5d7f180f-df5b-4a21-9c4c-62ca89a1f130">

**Comment by annezazu** [comment]
@ellatrix for you to consider!

**Comment by Mamaduka** [comment]
We can close this. The word count has been removed recently - #67624.
