### ISSUE TITLE
Interactivity API: Debug - Warning about Server Directives Processing errors.

### ISSUE THREAD

**Issue by cbravobernal** [WordPress/gutenberg#60035]
## What problem does this address?

Right now, if there is an error during the server directives processing, there is no way to determine that the error occurred. There is only a layout shift (a brief screen flash) when loading the website, and if the developer has a fast connection or a fast local environment, it is really hard to notice.

## What is your proposed solution?

If debugging is enabled, the client could send a console error if the source differs from the virtual DOM, or the server could send a PHP warning notice if the server directive processing is aborted (due to malformed HTML or unsupported tags).

**Comment by fabiankaegy** [comment]
Really looking forward to this :) Currently, it is really hard to debug what's causing the server processing to fail.

**Comment by sirreal** [comment]
`_doing_it_wrong` [around here](https://github.com/WordPress/wordpress-develop/blob/f6747a384f56893aac4870979c71f02f72d2e624/src/wp-includes/interactivity-api/class-wp-interactivity-api.php#L230) may be a good start.

**Comment by cbravobernal** [comment]
I just created a PR for it in wordpress-develop.

https://github.com/WordPress/wordpress-develop/pull/6413

**Comment by sirreal** [comment]
It's being worked on, good bot.

**Comment by gziolo** [comment]
That seems to be resolved now. Is the anything left to do?

**Comment by cbravobernal** [comment]
I think everything is done.
