### ISSUE TITLE
Navigation Block: overlay menu closes automatically when hovering menu items linked to drafts that follow a submenu item

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#60048]
### Description

Edge case: When a site has a draft page linked to a menu item and that menu item is positioned after a submenu in a Navigation Block, the overlay will automatically close without user input.

### Step-by-step reproduction instructions

1. Add a Navigation Block with the following structure:

* Menu Item
* Menu Item
** Submenu item
** Submenu item
* Menu item with a post/page saved as a draft

2. Set the Navigation to display as an overlay
3. Check the frontend and over the menu item associated with the draft

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/14153300/77f3dd7f-3b5e-4b87-af5f-5bbe7bd1c8f8

Example menu structure:

![CleanShot 2024-03-20 at 16 01 27@2x](https://github.com/WordPress/gutenberg/assets/14153300/f5c7921c-7036-41f5-9631-3cb6dae634e0)

### Environment info

- WordPress 6.5 RC3, GB 17.9
- Chrome 122, MacOS 14.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Finally had time and I can replicate with 6.5 RC3. This feels major @getdave @youknowriad @fabiankaegy  You can replicate by spinning up a site here https://app.instawp.io/launch?t=beta-rc&d=v2 and setting the menu to display mobile always.

**Comment by youknowriad** [comment]
Were you able to check whether this is a new bug in 6.5 or something that pre-existed?

**Comment by colorful-tones** [comment]
I just tested on WP 6.4.3 base install and I was not able to recreate the issue. So, something new in 6.5. In 6.4.3 the draft item is not even displayed on the front end in the navigation, which seems ideal to me.

**Comment by ariel-maidana** [comment]
On a site with the Meraki theme, I found a case in which the link to the draft page is inside the submenu, not after it.

**Comment by youknowriad** [comment]
At this point in the release, it might have to be fixed in a patch release though.

**Comment by draganescu** [comment]
Does the draft render on the front end? We to my knowledge do not render links to draft posts.

**Comment by youknowriad** [comment]
I think the issue is more about the menu closing automatically rather than the draft displaying.

**Comment by draganescu** [comment]
But I can't repro because for me the draft links don't render. And in the editor the overlay does not close automatically.

**Comment by liviopv** [comment]
> 
But I can't repro because for me the draft links don't render. And in the editor the overlay does not close automatically.

@draganescu The draft doesn't render for me either, as expected. The problem happens when the cursor reaches the draft item position, as shown in the video.

**Comment by draganescu** [comment]
Ohh 😂 I didn't see that in the video! I'll try again 🙇🏻

**Comment by draganescu** [comment]
@liviopv what am I not doing?


https://github.com/WordPress/gutenberg/assets/107534/082df6b8-a2c8-445b-9ea4-ddedd6d964e0

**Comment by liviopv** [comment]
@draganescu before the draft item, you need to have a menu item with a submenu, like this structure:

>Menu Item

>Menu Item
>>Submenu item
>>Submenu item

>Draft

**Comment by draganescu** [comment]
> and that menu item is positioned after a submenu in a Navigation Block

Apparently I flopped reading comprehension today :D will test again!

**Comment by draganescu** [comment]
Yes I can confirm this.

**Comment by draganescu** [comment]
The problem manifests for any submenu - the presence of a draft link is not required - and it is happening because there is some bad interference between the code that closes submenus and the code that closes the overlay.

**Comment by draganescu** [comment]
@liviopv if you can test #60130 let me know if it fixes the problem for you.

**Comment by annezazu** [comment]
I really hope we can fix this before the release goes out. I tested the above and it fixed it for me but would appreciate a lot more reviews. I'll flag in Make Test :) cc @fabiankaegy @colorful-tones in case you all can help out too.

**Comment by kjnanda** [comment]
@annezazu I tested out the [PR](https://github.com/WordPress/gutenberg/pull/60130) and the added fix works as expected. 👍🏻 

------

## Test Report
### Description
This report validates whether the indicated PR works as expected.

PR : Fix self closing navigation overlay
PR Link - https://github.com/WordPress/gutenberg/pull/60130

### Environment
- WordPress: 6.4.3
- PHP: 8.3.0-dev
- Server: PHP.wasm
- Database: WP_SQLite_Translator (Server: 5.5 / Client: 3.40.1)
- Browser: Chrome 123.0.0.0
- OS: macOS
- Theme: Twenty Twenty-Four 1.0
- MU Plugins:
  * 0-playground.php 
  * 0-sqlite.php 
  * WordPress WXZ Exporter 0.1
- Plugins:
  * Gutenberg 18.0.0-rc.1
  * Test Reports 1.1.0
  * WordPress Importer Git loader 0.8.2

### Actual Results
1.  ✅ Issue resolved with this given PR.

### Additional Note
Tested with WordPress Playground

### Supplemental Artifacts
Add as Attachment

--------

Please check this visual attached below.

https://github.com/WordPress/gutenberg/assets/15173772/7da8cf7d-8d8f-4dc6-9c0f-d4fd852760cb
