### ISSUE TITLE
readme.txt should be part of the GitHub version

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#6004]
## Issue Overview
For most WordPress plugins the `readme.txt` file contains a number of fields which can be read using `get_plugin_data`. 
This file is not provided in the development version of the plugin obtained from GitHub. 

So I can't use get_plugin_data() to obtain information about the plugin. 

Particularly interested in being able to access
```
Requires at least: 4.9
Tested up to: 4.9.5
```

Additionally, there are some typos in the change log. e.g. Add visibile text.

It would be nice if this file was under version control in GitHub, as well as SVN. 

## Steps to Reproduce (for bugs)

1. Clone the plugin locally
2. Try to find the `readme.txt` file

## Expected Behavior
readme.txt file should be present.

## Current Behavior
It's not. And I don't appear to be able to build it. 

## Possible Solution
Deliver the file as part of the GitHub repo.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by bobbingwide** [comment]
Ah! Looks like you can't get those values using `get_plugin_data()` anyway.

**Comment by danielbachhuber** [comment]
@bobbingwide Seems like this doesn't need action now. Feel free to re-open if you think necessary.

**Comment by swissspidy** [comment]
Adding the `readme.txt` to the repository would make it easier to make contributions to it. Otherwise it gets somewhat forgotten.

A current example is #16674, where a change to the readme is necessary.

**Comment by youknowriad** [comment]
We'll have to tweak the release tool a bit if we move the readme to this repo but I wouldn't mind. Also, what about `changelog.txt`

**Comment by swissspidy** [comment]
Yeah I figured as much.

Adding `changelog.txt` as well makes sense too I think.
