### ISSUE TITLE
Don't render editor resize handles when zoomed out

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#60052]
Resizing the editor when zoomed out mode is engaged causes odd and unexpected behaviors. 

We should not render the editor resize handles when zoom out mode is engaged. 

### Visual

https://github.com/WordPress/gutenberg/assets/1813435/f7d3d3b4-49cb-4e57-b750-1df52a2050f5

**Comment by t-hamano** [comment]
This issue would be similar to #59389.
