### ISSUE TITLE
Document title bar hover color should be the primary admin color

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#60059]
The hover color of the document title label should be the primary admin color, unless it is a template part or synced pattern (purple is reserved for those "synced" assets). 

https://github.com/WordPress/gutenberg/assets/1813435/62f201d3-f0fe-4a9d-a2aa-012d378d3af2

**Comment by mikachan** [comment]
Looks like this was fixed in https://github.com/WordPress/gutenberg/pull/60113, so I'm going to close this. Please re-open if necessary!
