### ISSUE TITLE
Bypass the secondary save view if there is only one change

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#60058]
If there's only one "site change", can we bypass the secondary confirm save view in the Site Editor? Currently, you need to press "Save" twice, in every save scenario in the Site Editor. Feels a bit unnecessary. 

### Visual 

![CleanShot 2024-03-20 at 18 12 31](https://github.com/WordPress/gutenberg/assets/1813435/5040f4eb-101b-41f4-a033-9544b26c22f2)

**Comment by annezazu** [comment]
Can we close this out in favor of the following? https://github.com/WordPress/gutenberg/issues/38714

**Comment by SaxonF** [comment]
We already do this when using the save button in dark sidebar. It only prompts when you either have more than one entity to save, or you're outside the area that's being saved. I think it makes sense to adopt for editor too, except we should only do it if you're still on the post that has been modified. e.g. If I edit a page, then navigate to another page but don't make an edit, I think we should still prompt.

**Comment by richtabor** [comment]
> Can we close this out in favor of the following? https://github.com/WordPress/gutenberg/issues/38714 

I can potentially add it as a comment, but we're asking for separate things really. I don't think we need to add an option to consolidate multiple entity saving, but rather be smarter when the confirmation appears (no second step when there's only one entity).

**Comment by ntsekouras** [comment]
>I can potentially add it as a comment, but we're asking for separate things really. 

Yes, those are different things. I'll have a PR for this issue soon.
