### ISSUE TITLE
"Clear customisations" template action should always trigger a confirmation dialog

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#60072]
Extracted from discussion in https://github.com/WordPress/gutenberg/issues/56603.

If you perform the "Clear customisations" action in the details panel, or the document inspector, a confirmation dialog appears asking if you're sure whether to proceed. 

However, in the templates data view there's no confirmation dialog.

It would be good to be consistent here, and introduce the confirmation dialog in the templates data view.

**Comment by annezazu** [comment]
Somewhat related as there are a few reset mechanism that would benefit from this: https://github.com/WordPress/gutenberg/issues/46859

**Comment by jameskoster** [comment]
This was fixed in https://github.com/WordPress/gutenberg/pull/60119.
