### ISSUE TITLE
Image Cropping via Block Toolbar doesn't work when Image is a Link (cannot drag)

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#60081]
### Description

When an Image block has a link set (whether custom URL or to Media File), the Block Toolbar's cropping tools don't work as expected. You cannot drag them to crop to a desired area. (though the Zoom does work).  Video attached.

I have confirmed this behavior on 6.4.3 & 6.5-RC-3 (with and without Gutenberg 17.9)

### Step-by-step reproduction instructions

1. Insert an Image Block
2. Make the image link to something (this may or may not be the case by default, depending on your value of 'image_default_link_type' in wp_options
3. Try to crop it using the toolbar, making sure to try dragging to find a different center point.

Note that you cannot drag the cropper.

4. Remove the link and try to crop again.
5. See that you can now crop as expected.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/945157/8ee1e6f9-8f23-4b53-b044-5823c325d39d

### Environment info

WP 6.4.3 and 6.5-RC-3. With and without Gutenberg 17.9.  Twenty Twenty Four Theme (among others)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Yup, I can confirm as well.
