### ISSUE TITLE
Disable the edit button until you have an image

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#6014]
I was walking through the blocks today testing and this thought struck me, why do we allow editing when we haven't got an image uploaded yet? It could be great to not have this enabled until we have an image.

![2018-04-05 at 15 48](https://user-images.githubusercontent.com/253067/38373364-08f93a76-38e9-11e8-9874-17efd8c3ed56.png)

**Comment by SuperGeniusZeb** [comment]
I think this is a duplicate of #5246.

**Comment by karmatosed** [comment]
Happy to close for that if we get a fix in that.
