### ISSUE TITLE
Consider allowing shortcode content to be imported as InnerBlocks

### ISSUE THREAD

**Issue by greatislander** [WordPress/gutenberg#6020]
## Issue Overview

A helpful addition to the block transform API would be the ability to convert the text content of a shortcode to `InnerBlocks` within a nested block.

As a generic example, given a shortcode like this:

```
[section]

Here is some inner content.

<ol>
  <li>List Item</li>
</ol>

[/section]
```

Converting to a section block (see #4900) could transform the shortcode’s content into inner blocks within the new section block.

## Expected Behavior

There is a path for transforming shortcode content into `InnerBlocks`.

## Current Behavior

Shortcode content (`source: 'text'`) can only be used as an attribute, and as far as I can tell attributes cannot be used to populate `InnerBlocks`.

## Possible Solution

A transform `from` object could support an `innerBlocks` property, like so:

```
transforms: {
	from: [
		{
			type: 'shortcode',
			tag: 'section',
			attributes: {
				...
			},
			innerBlocks: {
				type: 'array',
				source: 'text',
			},
		},
	],
},
```

The block transform API would then attempt to convert the shortcode content into blocks which would populate the new block's `InnerBlocks`.

## Related Issues and/or PRs
- #4900

**Comment by greatislander** [comment]
May be fixed by #5932.

**Comment by mcsf** [comment]
@greatislander, since 5932 was merged and some time has passed, what's the status of this?

**Comment by greatislander** [comment]
@mcsf I will take a look and get back to you. Thanks.

**Comment by mtias** [comment]
Going to close this for now, please reopen if there's further information.

**Comment by greatislander** [comment]
As far as I can tell this is still not possible. I've checked current Block API docs, transforms docs, and looked through the block library. Can this be opened for reconsideration in a future release?
