### ISSUE TITLE
The Button + Image block doesn't allow adding styles only for the text without affecting the image

### ISSUE THREAD

**Issue by adrianahdez** [WordPress/gutenberg#60239]
### Description

When I attempt to create an underline effect for the text on hover, it's impossible to apply it solely to the text without affecting the image, due to the inappropriate HTML rendering.

**Expected behaviour:** Add an underline effect on hover only for the text in a text+image button block.
**Current behaviour:** The underline applies to both the text and the image.

**NOTE:** I can't use the text-decoration: underline; rule because it doesn't match my design.

### Step-by-step reproduction instructions

For example, I have this button + image block, created in Editor:

![image](https://github.com/WordPress/gutenberg/assets/21199144/ce6d4a27-5937-4fab-981e-ea4d8012cbc8)

When I add an underline effect on hover using any css way to do it (using ::after pseudo-element, the border-bottom property, etc.) it will apply to the entire button including the image, and I want it to apply only to the text:

![image](https://github.com/WordPress/gutenberg/assets/21199144/3fecb25f-4810-4718-b55d-130f26689c96)

Before you suggest using the `text-decoration: underline;` CSS rule... yes, that works, but I need to clarify that this rule does not match my design needs, because the line gets too close to the text, so for this case I would need that the text has its own HTML tag, such as a `<span>` or any.

The result with `text-decoration: underline;` looks like the following **(this is NOT what I want)**:

![image](https://github.com/WordPress/gutenberg/assets/21199144/b5cb9eaf-0fd4-4879-a098-414621bf3805)

**This is what I want to achieve:**

![image](https://github.com/WordPress/gutenberg/assets/21199144/31086186-628e-48f9-a2b1-b396612c5e7b)

And currently, it is not possible with the native button+image block. The problem is that the text in the rendered HTML doesn't have an exclusive own HTML tag, I mean its parent tag (`<a>`) includes the text and also the image:

See how the block is rendered by default:

```HTML
<div class="wp-block-buttons">
<!-- wp:button {"textAlign":"left","backgroundColor":"transparent","textColor":"blue","style":{"elements":{"link":{"color":{"text":"var:preset|color|blue"}}}},"className":"is-style-fill"} -->
  <div class="wp-block-button is-style-fill wp-block-button__clear-style--text-icon">
    <a class="wp-block-button__link has-blue-color has-transparent-background-color has-text-color has-background has-link-color has-text-align-left wp-element-button" href="https://google.com">
    Conoce más 
    <img class="wp-image-64" style="width: 43px;" src="...path/to/the/image.jpg" alt="">
    </a>
  </div>
</div>
```

This problem could be solved if you wrap the button text in its own new tag, like a span, for independent CSS styling of each element:

```HTML
<div class="wp-block-buttons">
<!-- wp:button {"textAlign":"left","backgroundColor":"transparent","textColor":"blue","style":{"elements":{"link":{"color":{"text":"var:preset|color|blue"}}}},"className":"is-style-fill"} -->
  <div class="wp-block-button is-style-fill wp-block-button__clear-style--text-icon">
    <a class="wp-block-button__link has-blue-color has-transparent-background-color has-text-color has-background has-link-color has-text-align-left wp-element-button" href="https://google.com">
        <span>Conoce más </span>
        <img class="wp-image-64" style="width: 43px;" src="...path/to/the/image.jpg" alt="">
    </a>
  </div>
</div>
```

For now, the only solution I see is to create a new custom block for a custom button because the native block won't let me achieve such a simple thing :(

Let me know of any suggestions. Thanks for reading :-)

### Environment info

Wordpress version: 6.4.3
Gutenberg version: 16.2-16.7

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @adrianahdez,

Have you tried [text-underline-offset](https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-offset)? Besides `text-underline-offset`, [text-decoration-thickness](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness) and [text-decoration-color](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color) may also be useful.

The screenshot below is an example of defining a hover style that applies a custom underline to a Button block via the Global Styles panel.

![button-css](https://github.com/WordPress/gutenberg/assets/54422211/83561b66-50ef-4cbb-a903-b64699d4e170)

Alternatively, you can wrap the text in an arbitrary element by applying some formatting to the text node. You may be able to apply styles to this element.

**Comment by adrianahdez** [comment]
Hi @t-hamano,
thanks, it's a good solution!!
But it still seems to me that it needs too many lines:

It requires 4 lines:
```
a:hover {
    text-decoration: underline;
    text-decoration-thickness: 3px;
    text-decoration-color: currentColor;
    text-underline-offset: 10px;
}
```

When I could achieve it in a single line:
```
span:hover {
    border-bottom: 1px solid currentColor;
}
```

So, I am still thinking that it would be a good idea for every element to have its own HTML tag, to have more control over them. But yes, your solution is also very good! It helped me a lot because I had to create a custom block to achieve this effect, and now with this I can remove it and use native blocks

Thanks.

**Comment by t-hamano** [comment]
> So, I am still thinking that it would be a good idea for every element to have its own HTML tag, to have more control over them.

This is a complex problem. This is because the image included in the style we are trying to achieve is part of the editable button text. It would be difficult to automatically detect _only_ the text that comes before an inline image and wrap it in a span tag.

Another approach is to add your own inline format via [Formatting Toolbar API](https://developer.wordpress.org/block-editor/how-to-guides/format-api/). This will allow you to wrap some text with arbitrary elements or apply classes.

**Comment by t-hamano** [comment]
Hi @adrianahdez,

I would like to close this issue since there is already CSS or API to solve the problem reported in this issue. If there is something I missed, please feel free to comment.
