### ISSUE TITLE
Issue Using Keyboard Navigation on Editor Inserter Shortcuts

### ISSUE THREAD

**Issue by michealengland** [WordPress/gutenberg#6024]
## Issue Overview
While using the updated version of Gutenberg 2.6 the new feature that was added to show recently used blocks has a reverse flow for keyboard navigation. While tabbing through the editor once you get to the recently used buttons it focuses on the first button which is on the right side and then goes to the left side. This is due to the use of row-reverse in parent container.

## Steps to Reproduce (for bugs)

1. Create a new post using Gutenberg. ( I have 2.6 installed ).
2. Click on the title field and then use the tab key to navigate through the page.
3. You should see 3 icons to the right. From Left to right "Add Image", "Add Columns", and "Add Heading". 
4. Once you tab into this section the first tab starts on "Add Heading" and moves to the left instead of the right.

## Expected Behavior
When tabbing through the editor I expected the tab focus to maintain normal flow of left to right. All other objects on the page flow from left to right when using keyboard navigation which is why I expected that behavior.

## Current Behavior
When tabbing through the editor the current tab focus is right to left in the recently used blocks.

## Possible Solution
1. Change the flex direction to row instead of row reversed on the .editor-inserter-with-shortcuts
2. Another possible solution would be to reverse the order of the buttons from most recent to least.

**Comment by noisysocks** [comment]
Thanks for the detailed report @michealengland. I'm able to reproduce this.

**Comment by afercia** [comment]
Screenshot for reference:

<img width="809" alt="screen shot 2018-04-12 at 16 15 26" src="https://user-images.githubusercontent.com/1682452/38683045-d6136d46-3e6c-11e8-9705-c812820373e6.png">

Thanks @michealengland yeah this was noticed also in the screen reader testing session by Sina Bahram published on https://make.wordpress.org/accessibility/2018/03/28/accessibility-of-gutenberg-the-state-of-play/ and definitely something to address.
Worth reminding the visual order must always match the tab sequence order, there's also a specific WCAG criterion about this.
