### ISSUE TITLE
blockGap default shows controls

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#60279]
### Description

Not sure if this is a bug in WordPress or an error in the Handbook.

The handbooks says that not defining the blockGap makes it use the default `null` and therefore no controls should be shown.
<img width="996" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/5b29d377-798b-4813-a1f4-e04813ccca19">
https://developer.wordpress.org/themes/global-settings-and-styles/settings/spacing/#enabling-or-disabling-spacing-options

However, when I'm not defining anything in my theme.json the controls are shown.

| Header | Header |
|--------|--------|
| <img width="453" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/45ece9b6-4da4-4c92-926d-76a9d06c61ae"> `not defined` | <img width="280" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/5f8499ac-2090-44cd-8b62-18423da7b318"> |
| <img width="453" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/74c06161-c56f-4e28-a8bd-0544918f86d2"> `null` | <img width="280" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/bab4e4fc-0a62-45d7-855b-2712487f1443"> |
| <img width="450" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/7c2e8441-b01a-4107-a5fd-ff7ca49fbe2d"> `true`  | <img width="280" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/4efb0703-76f3-4c0d-8556-446bf55bef9c"> |
| <img width="449" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/d6fe7f11-652d-45a5-98ec-3889f5c1e214"> `false`  | <img width="281" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/58004205-477f-401e-be58-a7a88509ba56"> |

Also, the margin and padding controls are shown by default, even though they also shouldn't .... right?
And sticky, raised an issue here already: https://github.com/WordPress/Documentation-Issue-Tracker/issues/1522

### Step-by-step reproduction instructions

<details><summary>Create a theme.json from scratch or take this</summary>
<p>

{
  "settings": {
    "appearanceTools": true,
    "border": {
      "color": true,
      "radius": true,
      "style": true,
      "width": true
    },
    "color": {
      "defaultDuotone": false,
      "defaultGradients": false,
      "defaultPalette": false,
      "duotone": [],
      "gradients": [],
      "palette": [
        {
          "color": "#ffffff",
          "name": "Base",
          "slug": "base"
        },
        {
          "color": "#F9F9FA",
          "name": "Base 2",
          "slug": "base-2"
        },
        {
          "color": "#EFEFF0",
          "name": "Base 3",
          "slug": "base-3"
        },
        {
          "color": "#D4D7DD",
          "name": "Base 4",
          "slug": "base-4"
        },
        {
          "color": "#C2C5CC",
          "name": "Base 5",
          "slug": "base-5"
        },
        {
          "color": "#000000",
          "name": "Contrast",
          "slug": "contrast"
        },
        {
          "color": "#212224",
          "name": "Contrast 2",
          "slug": "contrast-2"
        },
        {
          "color": "#464646",
          "name": "Contrast 3",
          "slug": "contrast-3"
        },
        {
          "color": "#616368",
          "name": "Contrast 4",
          "slug": "contrast-4"
        },
        {
          "color": "#84868A",
          "name": "Contrast 5",
          "slug": "contrast-5"
        },
        {
          "color": "#456A49",
          "name": "Primary",
          "slug": "primary"
        },
        {
          "color": "#345C00",
          "name": "Secondary",
          "slug": "secondary"
        },
        {
          "color": "#F6F6F6",
          "name": "Tertiary",
          "slug": "tertiary"
        },
        {
          "color": "#456A49",
          "name": "Accent",
          "slug": "accent"
        }
      ]
    },
    "custom": {
      "lineHeight": {
        "x-small": "1",
        "small": "1.25",
        "medium": "1.6",
        "large": "1.85"
      }
    },
    "dimensions": {
      "minHeight": true
    },
    "layout": {
      "contentSize": "640px",
      "wideSize": "1280px"
    },
    "shadow": {
      "defaultPresets": false,
      "presets": [
        {
          "name": "x-small",
          "shadow": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
          "slug": "x-small"
        },
        {
          "name": "small",
          "shadow": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
          "slug": "small"
        },
        {
          "name": "medium",
          "shadow": "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
          "slug": "medium"
        },
        {
          "name": "large",
          "shadow": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
          "slug": "large"
        },
        {
          "name": "x-large",
          "shadow": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
          "slug": "x-large"
        },
        {
          "name": "xx-large",
          "shadow": "0 25px 50px -12px rgb(0 0 0 / 0.25)",
          "slug": "xx-large"
        },
        {
          "name": "inset",
          "shadow": "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
          "slug": "inset"
        }
      ]
    },
    "spacing": {
      "spacingScale": {
        "steps": 0
      },
      "spacingSizes": [
        {
          "name": "x-small",
          "size": "0.482rem",
          "slug": "x-small"
        },
        {
          "name": "small",
          "size": "0.833rem",
          "slug": "small"
        },
        {
          "name": "medium",
          "size": "clamp(1rem, 0.56rem + 1.1vw, 1.44rem)",
          "slug": "medium"
        },
        {
          "name": "large",
          "size": "clamp(1.728rem, 0.968rem + 1.9vw, 2.488rem)",
          "slug": "large"
        },
        {
          "name": "x-large",
          "size": "clamp(2.488rem, 1.393rem + 2.738vw, 3.583rem)",
          "slug": "x-large"
        },
        {
          "name": "xx-large",
          "size": "clamp(5.16rem, 2.89rem + 5.675vw, 7.43rem)",
          "slug": "xx-large"
        }
      ],
      "units": ["%", "px", "em", "rem", "vh", "vw"]
    },
    "typography": {
      "customFontSize": true,
      "dropCap": false,
      "fluid": true,
      "fontFamilies": [
        {
          "fontFamily": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif",
          "name": "System Font",
          "slug": "system-font"
        },
        {
          "fontFace": [
            {
              "fontFamily": "Inter",
              "fontStyle": "normal",
              "fontWeight": "400",
              "src": ["file:./assets/fonts/inter_normal_400.ttf"]
            },
            {
              "fontFamily": "Inter",
              "fontStyle": "normal",
              "fontWeight": "600",
              "src": ["file:./assets/fonts/inter_normal_600.ttf"]
            },
            {
              "fontFamily": "Inter",
              "fontStyle": "normal",
              "fontWeight": "800",
              "src": ["file:./assets/fonts/inter_normal_800.ttf"]
            }
          ],
          "fontFamily": "Inter",
          "slug": "inter"
        },
        {
          "fontFace": [
            {
              "fontFamily": "Barlow",
              "fontStyle": "italic",
              "fontWeight": "400",
              "src": ["file:./assets/fonts/barlow_italic_400.ttf"]
            },
            {
              "fontFamily": "Barlow",
              "fontStyle": "normal",
              "fontWeight": "400",
              "src": ["file:./assets/fonts/barlow_normal_400.ttf"]
            },
            {
              "fontFamily": "Barlow",
              "fontStyle": "normal",
              "fontWeight": "700",
              "src": ["file:./assets/fonts/barlow_normal_700.ttf"]
            },
            {
              "fontFamily": "Barlow",
              "fontStyle": "italic",
              "fontWeight": "700",
              "src": ["file:./assets/fonts/barlow_italic_700.ttf"]
            },
            {
              "fontFamily": "Barlow",
              "fontStyle": "italic",
              "fontWeight": "600",
              "src": ["file:./assets/fonts/barlow_italic_600.ttf"]
            },
            {
              "fontFamily": "Barlow",
              "fontStyle": "normal",
              "fontWeight": "600",
              "src": ["file:./assets/fonts/barlow_normal_600.ttf"]
            }
          ],
          "fontFamily": "Barlow",
          "name": "Primary",
          "slug": "primary-font"
        }
      ],
      "fontSizes": [
        {
          "fluid": {
            "min": "0.694rem"
          },
          "name": "small",
          "size": "0.833rem",
          "slug": "small"
        },
        {
          "fluid": {
            "min": "1rem"
          },
          "name": "medium",
          "size": "1rem",
          "slug": "medium"
        },
        {
          "fluid": {
            "min": "1.2rem"
          },
          "name": "large",
          "size": "1.2rem",
          "slug": "large"
        },
        {
          "fluid": {
            "min": "1.44rem"
          },
          "name": "x-large",
          "size": "1.728rem",
          "slug": "x-large"
        }
      ],
      "fontStyle": true,
      "fontWeight": true,
      "letterSpacing": true,
      "textDecoration": true,
      "textTransform": true
    },
    "useRootPaddingAwareAlignments": true
  },
  "templateParts": [
    {
      "area": "header",
      "name": "header",
      "title": "Header"
    },
    {
      "area": "footer",
      "name": "footer",
      "title": "Footer"
    }
  ],
  "version": 2,
  "$schema": "https://schemas.wp.org/wp/6.4/theme.json"
}

</p>
</details> 

See that the controls are displayed. 

### Environment info

- WP 6.4.3
- GB 18.0.0 and without

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @hanneslsm,

> The handbooks says that not defining the blockGap makes it use the default `null` and therefore no controls should be shown.

This is correct. But if I look at your theme.json, [appearanceTools](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/#appearancetools) is defined as `true`. This will cause the UI to appear even if you didn't define spacing.blockGap.

> Also, the margin and padding controls are shown by default, even though they also shouldn't .... right?

Neither control is visible by default, but if `apperanceTools` is `true` they will become visible similar to `blockGap`.

**Comment by hanneslsm** [comment]
Ah, I've overseen the `apperanceTools` settings.
Thanks for the quick response @t-hamano!
