### ISSUE TITLE
Allow extensions to customize the template name in the 'Add template' screen

### ISSUE THREAD

**Issue by Aljullu** [WordPress/gutenberg#60283]
### Description

When creating a new template, Custom Post Type taxonomies are displayed with not very user-friendly titles. Ie: `Recipe (recipe_cat)`.

That's not ideal because:

1. Users depend on slugs to distinguish between templates.
2. It's not very obvious that `Category (recipe_cat)` means the Recipes by Category template.

![Add template screen](https://github.com/WordPress/gutenberg/assets/3616980/bf9a9e3c-389e-46fe-9fdc-7560f7be63eb)

Currently, the values which are used are the `singular_name` label and the taxonomy slug:

https://github.com/WordPress/gutenberg/blob/39500f6464be810c2da20532cfd24b0fddd57651/packages/edit-site/src/components/add-new-template/utils.js#L372-L377

However, that doesn't give enough flexibility to 3rd-party plugins because `singular_name` is used in other parts of the UI so it can't be adapted to the context of the Site Editor.

### A real-life example

While the _Recipe_ example I showed above is quite simple, there are other plugins which might add more templates, like WooCommerce:

![Add template screen with WooCommerce](https://github.com/WordPress/gutenberg/assets/3616980/7056ecad-0a18-40a1-8b17-91fe8f950cd2)

(Sidenote: currently WooCommerce doesn't show these templates in the 'Add template' screen, but we would like to: https://github.com/woocommerce/woocommerce/issues/42532)

### Suggested solutions

I would like to propose some possible solutions that, I believe, would help improve this part of the UI:

1. Adding a new label value in the [`register_taxonomy()` WordPress function](https://developer.wordpress.org/reference/functions/register_taxonomy/) intended to be used to name the templates in the admin. In the Product Category case, that could be `Product Category Archives`. If a plugin registers a taxonomy without specifying that value, the `singular_name` could be used as a fallback.
2. If, for some reason, we want to avoid the first approach, we could add a JS filter to let plugins customize the elements in the 'Add template' screen. That means using a less-explicit filter hook instead of the most explicit API from approach 1; however, it would have the advantage that it could be made so 3rd-plugins can also customize the template icon, for example.
3. Modifying the UI of the _Add template_ screen to keep CPT templates separate from the others. If we could add a header for each specific CPT or plugin that registers custom templates, using `singular_name` would automatically become more use friendly. In the WC example, I'm thinking that there could be a `Product` or `WooCommerce` header where all product-related templates could be grouped. Ideally that would require no work by plugins.

### Step-by-step reproduction instructions

1. Add this code snippet to your site in order to create a Recipes post type and a Recipe category taxonomy (you can use [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin if needed):

```PHP
add_action( 'init', function () {
	register_post_type(
		'recipe',
		array(
			'labels'       => array(
				'name' => 'Recipes',
			),
			'show_in_rest' => true,
		)
	);
	register_taxonomy(
		'recipe_cat',
		'recipe',
		array(
			'label'        => 'Categories',
			'labels'       => array(
				'name'          => 'Recipe categories',
				'singular_name' => 'Category',
			),
			'show_in_rest' => true,
		)
	);
} );
```

2. Go to Appearance > Editor > Templates > Add New Template.
3. Once the 'Add template' screen shows up, notice how the title of the custom taxonomy template is not very user friendly: `Category (recipe_cat)`.

**Expected result:**

As a user, I don't need to know that Recipe Categories uses the `recipe_cat` slug internally. Ideally, those buttons should show up a user-friendly name like: `Recipe Category Archives` or `Recipes by Category`.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Aljullu** [comment]
cc @gziolo and @ntsekouras to know your thoughts about the above. I think the questions are:

1. Do you agree this is an area where the UI could be improved, or would you prefer to keep it as-is?
2. If you agree that we could introduce changes, do any of the proposed solutions I wrote sound like a good approach to you?

I would be more than happy to contribute fixing this, but would like to hear your thoughts about it before getting started. :slightly_smiling_face:

**Comment by ntsekouras** [comment]
Thanks for the issue @Aljullu! For me your first suggestion would be the best:

>Adding a new label value in the [register_taxonomy() WordPress function](https://developer.wordpress.org/reference/functions/register_taxonomy/) intended to be used to name the templates in the admin. In the Product Category case, that could be Product Category Archives. If a plugin registers a taxonomy without specifying that value, the singular_name could be used as a fallback.


A similar label could be considered for post type's labels too.

Regarding grouping or reordering is a different issue and could considered as well, besides the label.

**Comment by Aljullu** [comment]
Thanks for the input, @ntsekouras!

> A similar label could be considered for post type's labels too.

Agree, good point.

I opened two PRs, one in Gutenberg and the other one in WordPress, which I think handle all the work related to introducing a new label when registering a CPT and Taxonomy:

* https://github.com/WordPress/gutenberg/pull/60367
* https://github.com/WordPress/wordpress-develop/pull/6344

Hope you don't mind I added you as the reviewer. :slightly_smiling_face:

**Comment by mcsf** [comment]
I agree with adding a label to the taxonomy type, that would be my first move. 

That said, it's worth exploring UI improvements. If nothing else, to distinguish custom types from standard. I wonder what information we could use from the registration process to reliably determine provenance or namespace (like "Woo", etc.), avoiding the cost of another extension of the API.
