### ISSUE TITLE
Block variations registered on the server can get overwritten in the client

### ISSUE THREAD

**Issue by joemcgill** [WordPress/gutenberg#60298]
### Description

As reported in https://core.trac.wordpress.org/ticket/60856, the `core/group` block does not register any of its variations on the server, but instead adds them at runtime in the client. This means that any variations registered on the server via filters or other means get overwritten when the `core/group` block is initialized. I suspect this behavior is consistent with all blocks that are adding variations, which likely includes [this whole list](https://github.com/search?q=repo%3AWordPress%2Fgutenberg+import+variations+from+%27.%2Fvariations%27%3B+language%3AJavaScript&type=code).

I would expect that any variations supplied by the server would be added to the variations added to the block in JS.

### Step-by-step reproduction instructions

1. Add a block variation to the group block using the `get_block_type_variations` filter in PHP.
2. Confirm that the variation is being supplied by the server by inspecting the output of `get_block_editor_server_block_settings()`, which is used to bootstrap block types from the server.
3. Load the editor and inspect the block definition in the console: `wp.blocks.getBlockTypes().filter( (block) => block.name === 'core/group' )`
4. See that the variation supplied by the server is no longer present.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I was also able to reproduce the problem. I tested it with the code below.

```php
function modify_block_type_variations( $variations, $block_type ) {
	// This variation will be registered.
	if ( 'core/paragraph' === $block_type->name ) {
		$variations[] = array(
			'name'  => 'paragraph-variation',
			'title' => 'New Paragraph Variation',
		);
	}
	// This variation will be registered.
	if ( 'core/heading' === $block_type->name ) {
		$variations[] = array(
			'name'  => 'heading-variation',
			'title' => 'New Heading Variation',
		);
	}
	// This variation will not be registered.
	if ( 'core/group' === $block_type->name ) {
		$variations[] = array(
			'name'  => 'group-variation',
			'title' => 'New Group Variation',
		);
	}
	// This variation will not be registered.
	if ( 'core/columns' === $block_type->name ) {
		$variations[] = array(
			'name'  => 'columns-variation',
			'title' => 'New Columns Variation',
		);
	}
	return $variations;
}
add_filter( 'get_block_type_variations', 'modify_block_type_variations', 10, 2 );
```

**Comment by Mamaduka** [comment]
Can you add more variations using JS when initial variations are coming from the server?

**Update:** You can due to the native of the bug. I've some ideas on how to fix it.
