### ISSUE TITLE
HTML API: Plans for WP 6.6

### ISSUE THREAD

**Issue by dmsnell** [WordPress/gutenberg#60324]
[🔝Block API](https://github.com/WordPress/gutenberg/issues/41236) | [HTML issues](https://github.com/WordPress/gutenberg/discussions/57560) | [Refactors](https://github.com/WordPress/gutenberg/discussions/54750) | [↑ Broader Roadmap](https://github.com/WordPress/gutenberg/issues/60397) | [← Plans for 6.5](https://github.com/WordPress/gutenberg/discussions/54579) | [→ Plans for 6.7](https://github.com/WordPress/gutenberg/issues/60396)

---

| <br>&emsp; :warning: This issue was created [from where the discussion originally took place](https://github.com/WordPress/gutenberg/discussions/57827).&emsp;<br>&nbsp; |
| --- |

Plans for the HTML API in WordPress 6.6 are being reassessed.
Most likely there will be two goals for the release:

 - [x] Complete and rely on a custom and spec-compliant encoder/decoder.
     - Core-60841 `WP_Token_Set` class for named character reference lookup.
       WordPress/wordpress-develop#5373
     - Core-61072 Spec-compliant text decoder.
       WordPress/wordpress-develop#6387
 - [x] Design how to communicate when an HTML document has retroactively changed, allow calling code to match on, stop at, and modify implicitly-created elements, including when elements are closed.
     - WordPress/wordpress-develop#6348

### Fixes

 - https://github.com/WordPress/wordpress-develop/pull/6625

### Ideas

 - Can we detect transitions from HTML and SVG/MathML namespaces in the Tag Processor?
   - Probably not, because once entering HTML contexts we have to obey HTML rules to know when to exit that content, before returning to XML-like parsing.

**Comment by fabiankaegy** [comment]
Hi all 👋 

Reminder: The release candidate for Gutenberg Version 18.5 is scheduled for next Friday (May 31st). So anything that is supposed to make it into WordPress 6.6 must be merged by then. 

Please raise any important issues that need additional attention :)

**Comment by dmsnell** [comment]
Thanks @fabiankaegy - this work is independent of and outside of the Gutenberg plugin. It's only here because people wanted to see the plans for the work here. There is nothing in this that relates to Gutenberg or its timelines.

**Comment by fabiankaegy** [comment]
@dmsnell Sorry for the confusion on my end :)

**Comment by dmsnell** [comment]
No worries @fabiankaegy. It's all confusing, and in this new home as an issue we can't thread the responses, which is something I miss. Now it's here forever, but that's okay. 😄

**Comment by gziolo** [comment]
Work on WP 6.6 successfully wrapped up, and we now have a similar issue for WP 6.7 at https://github.com/WordPress/gutenberg/issues/60396.
