### ISSUE TITLE
Impossible to add additional submenu items to nav block

### ISSUE THREAD

**Issue by helgatheviking** [WordPress/gutenberg#60341]
### Description

I just tried to edit my site's header template. I have one menu item that has a submenu. I was able to navigate to that submenu ite, but then there's no visible way to add an additional item.

By using the console's site inspector I was able to change the height of the components div and suddenly I was able to see the + add block/inserter icon again. So it seems like it's being hidden as the editor window is too short.

### Step-by-step reproduction instructions

Create a header with a nav block.
Create one submenu.
Edit the header template a second time. (Not entirely certain of this)
Attempt to add additional link to submenu.

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/507025/334f486c-aa25-4cae-abd8-9d98f7a05b06)

![image](https://github.com/WordPress/gutenberg/assets/507025/0d299aba-857e-4166-9159-b1636d2e1571)

### Environment info

WordPress 6.4.3
Gutenberg not active
Twenty Twenty Four theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by getdave** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/49339
