### ISSUE TITLE
Drag & dropping blocks shows 'Drop files to upload' zones

### ISSUE THREAD

**Issue by paulwilde** [WordPress/gutenberg#6035]
When drag and dropping blocks, the 'Drop files to upload' region appears. In the context of it being a block you are moving, this makes no sense in appearing. Refer to screenshot for reference.

<img width="945" alt="screen shot 2018-04-06 at 12 52 43" src="https://user-images.githubusercontent.com/704594/38419764-83b0024e-3999-11e8-8768-83f836d5cc96.png">

**Comment by gziolo** [comment]
I noticed the same issue yesterday when testing `master` branch.
