### ISSUE TITLE
Documentation: Add missing docs in `editor` package

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#60358]
Recently, we [added](https://github.com/WordPress/gutenberg/pull/60356) auto-generated docs for the `editor` package. 

There are lots of undocumented APIs, so let's add what's missing.

- [x] AutosaveMonitor [#60882](https://github.com/WordPress/gutenberg/pull/60882), [#60905](https://github.com/WordPress/gutenberg/pull/60905)
- [x] CharacterCount [#60906](https://github.com/WordPress/gutenberg/pull/60906)
- [x] DocumentBar [#61733](https://github.com/WordPress/gutenberg/pull/61733)
- [x] DocumentOutline [#61129](https://github.com/WordPress/gutenberg/pull/61129)
- [x] DocumentOutlineCheck [#61129](https://github.com/WordPress/gutenberg/pull/61129)
- [x] EditorHistoryRedo [#60932](https://github.com/WordPress/gutenberg/pull/60932)
- [x] EditorHistoryUndo [#60932](https://github.com/WordPress/gutenberg/pull/60932)
- [x] EditorKeyboardShortcuts [#60933](https://github.com/WordPress/gutenberg/pull/60933)
- [x] EditorKeyboardShortcutsRegister [#60933](https://github.com/WordPress/gutenberg/pull/60933)
- [x] EditorNotices [#61736](https://github.com/WordPress/gutenberg/pull/61736)
- [x] EditorProvider [#61739](https://github.com/WordPress/gutenberg/pull/61739)
- [x] EditorSnackbars [#61110](https://github.com/WordPress/gutenberg/pull/61110)
- [x] EntitiesSavedStates [#62377](https://github.com/WordPress/gutenberg/pull/62377)
- [x] ErrorBoundary [#61950](https://github.com/WordPress/gutenberg/pull/61950)
- [x] LocalAutosaveMonitor [#61951](https://github.com/WordPress/gutenberg/pull/61951)
- [x] PageAttributesCheck [#60977](https://github.com/WordPress/gutenberg/pull/60977)
- [x] PageAttributesOrder [#60977](https://github.com/WordPress/gutenberg/pull/60977)
- [x] PageAttributesPanel [#60977](https://github.com/WordPress/gutenberg/pull/60977)
- [x] PageAttributesParent [#60977](https://github.com/WordPress/gutenberg/pull/60977)
- [x] PageTemplate [#61961](https://github.com/WordPress/gutenberg/pull/61961)
- [x] PostAuthor [#61090](https://github.com/WordPress/gutenberg/pull/61090)
- [x] PostAuthorCheck [#61090](https://github.com/WordPress/gutenberg/pull/61090)
- [x] PostAuthorPanel [#61090](https://github.com/WordPress/gutenberg/pull/61090)
- [x] PostComments [#61964](https://github.com/WordPress/gutenberg/pull/61964)
- [x] PostDiscussionPanel [#61966](https://github.com/WordPress/gutenberg/pull/61966)
- [x] PostExcerpt 
- [x] PostExcerptCheck [#60864](https://github.com/WordPress/gutenberg/pull/60864)
- [x] PostExcerptPanel [#61967](https://github.com/WordPress/gutenberg/pull/61967)
- [x] PostFeaturedImage [#61165](https://github.com/WordPress/gutenberg/pull/61165)
- [x] PostFeaturedImageCheck [#61165](https://github.com/WordPress/gutenberg/pull/61165)
- [x] PostFeaturedImagePanel [#61165](https://github.com/WordPress/gutenberg/pull/61165)
- [x] PostFormat [#61732](https://github.com/WordPress/gutenberg/pull/61732)
- [x] PostFormatCheck [#61732](https://github.com/WordPress/gutenberg/pull/61732)
- [x] PostLastRevision [#61166](https://github.com/WordPress/gutenberg/pull/61166)
- [x] PostLastRevisionCheck [#61166](https://github.com/WordPress/gutenberg/pull/61166)
- [x] PostLastRevisionPanel [#61166](https://github.com/WordPress/gutenberg/pull/61166)
- [x] PostLockedModal [#61968](https://github.com/WordPress/gutenberg/pull/61968)
- [x] PostPendingStatus [#61970](https://github.com/WordPress/gutenberg/pull/61970)
- [x] PostPendingStatusCheck [#61970](https://github.com/WordPress/gutenberg/pull/61970)
- [x] PostPingbacks [#62035](https://github.com/WordPress/gutenberg/pull/62035)
- [x] PostPreviewButton [#62036](https://github.com/WordPress/gutenberg/pull/62036)
- [x] PostPublishButton [#62379](https://github.com/WordPress/gutenberg/pull/62379)
- [x] PostPublishButtonLabel [#62379](https://github.com/WordPress/gutenberg/pull/62379)
- [x] PostPublishPanel [#62380](https://github.com/WordPress/gutenberg/pull/62380)
- [x] PostSchedule [#61345](https://github.com/WordPress/gutenberg/pull/61345)
- [x] PostScheduleCheck [#61345](https://github.com/WordPress/gutenberg/pull/61345)
- [x] PostScheduleLabel [#61345](https://github.com/WordPress/gutenberg/pull/61345)
- [x] PostSchedulePanel [#61345](https://github.com/WordPress/gutenberg/pull/61345)
- [x] PostSlug [#62102](https://github.com/WordPress/gutenberg/pull/62102)
- [x] PostSlugCheck [#62102](https://github.com/WordPress/gutenberg/pull/62102)
- [x] PostSticky [#62100](https://github.com/WordPress/gutenberg/pull/62100)
- [x] PostStickyCheck [#62100](https://github.com/WordPress/gutenberg/pull/62100)
- [x] PostSwitchToDraftButton [#62381](https://github.com/WordPress/gutenberg/pull/62381)
- [x] PostSyncStatus [#62382](https://github.com/WordPress/gutenberg/pull/62382)
- [x] PostTaxonomies [#62384](https://github.com/WordPress/gutenberg/pull/62384)
- [x] PostTaxonomiesCheck [#62384](https://github.com/WordPress/gutenberg/pull/62384)
- [x] PostTaxonomiesFlatTermSelector [#62384](https://github.com/WordPress/gutenberg/pull/62384)
- [x] PostTaxonomiesPanel [#62384](https://github.com/WordPress/gutenberg/pull/62384)
- [x] PostTemplatePanel [#61961](https://github.com/WordPress/gutenberg/pull/61961)
- [x] PostTextEditor [#62099](https://github.com/WordPress/gutenberg/pull/62099)
- [x] PostTitle [#61740](https://github.com/WordPress/gutenberg/pull/61740)
- [x] PostTitleRaw [#61740](https://github.com/WordPress/gutenberg/pull/61740)
- [x] PostTrash [ #62116](https://github.com/WordPress/gutenberg/pull/62116)
- [x] PostTrashCheck [#62116](https://github.com/WordPress/gutenberg/pull/62116)
- [x] PostURL [#61737](https://github.com/WordPress/gutenberg/pull/61737)
- [x] PostURLCheck [#61737](https://github.com/WordPress/gutenberg/pull/61737)
- [x] PostURLLabel [#61737](https://github.com/WordPress/gutenberg/pull/61737)
- [x] PostURLPanel [#61737](https://github.com/WordPress/gutenberg/pull/61737)
- [x] PostVisibility [#61735](https://github.com/WordPress/gutenberg/pull/61735)
- [x] PostVisibilityCheck [#61735](https://github.com/WordPress/gutenberg/pull/61735)
- [x] PostVisibilityLabel [#61735](https://github.com/WordPress/gutenberg/pull/61735)
- [x] TableOfContents [#62385](https://github.com/WordPress/gutenberg/pull/62385)
- [x] TextEditorGlobalKeyboardShortcuts [#62116](https://github.com/WordPress/gutenberg/pull/62116)
- [x] ThemeSupportCheck [#62387](https://github.com/WordPress/gutenberg/pull/62387)
- [x] TimeToRead [#62116](https://github.com/WordPress/gutenberg/pull/62116)
- [x] transformStyles
- [x] useEntitiesSavedStatesIsDirty [#62388](https://github.com/WordPress/gutenberg/pull/62388)
- [x] usePostScheduleLabel [#61345](https://github.com/WordPress/gutenberg/pull/61345)
- [x] usePostURLLabel [#61737](https://github.com/WordPress/gutenberg/pull/61737)
- [x] usePostVisibilityLabel
- [x] VisualEditorGlobalKeyboardShortcuts
- [x] WordCount [#62217](https://github.com/WordPress/gutenberg/pull/62217)

We can do this iteratively, but it would be probably best to do it in chunks.

## Instructions
1. The documentation for editor package is auto generated, so after the addition of any JSDoc we need to `npm run docs:build` in order to update the README file. We shouldn't update manually the README file!
2. There are some linting rules for JSDoc. You can check [this doc's section](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/getting-started-with-code-contribution.md#eslint) about setting this up in your code editor.
3. The generation script searches for JSDocs above the exported module. In some cases we declare the module, but export it in a different place (usually somewhere below in the same file). In that case we should add the JSDocs above the export.

Example:
```
function EditorHistoryRedo() { ... }
....
....

{ Add JSDoc here!!! } 
export default forwardRef( EditorHistoryRedo )
```

**Comment by akasunil** [comment]
Looks like there is issue with `docs:build` command, It generate the documentation only if component is exported as default. Otherwise pipeline get failed. How do we resolve this ?

**Comment by ntsekouras** [comment]
@sunil25393 can you give me an example of this? Because I just tested with `usePostScheduleLabel` which is not the default export and seems to work for me..

**Comment by akasunil** [comment]
Sure @ntsekouras, here is my draft PR https://github.com/WordPress/gutenberg/pull/60932

**Comment by colorful-tones** [comment]
I'm just dropping an update here. I'm organizing an internal WP Engine Contributor Day on Thursday, May 16, 2024, and I plan on utilizing this issue to provide some folks with some quick wins and empower them to feel successful in their contribution efforts. Hopefully, we'll have all the items wrapped up that day. Thanks!

**Comment by colorful-tones** [comment]
We did not make it as far as I thought in our internal Contributor Day, but that is to be expected. I plan on still pursuing chipping away at the items. The biggest hurdle for many folks was the issue with `wp-scripts` command failing: https://github.com/WordPress/gutenberg/pull/61748

I've since been running ESLint 10.0.2 locally and everything has been working smoothly. Perhaps @akasunil will continue pitching in as well. No worries if not. I just wanted to post an update. Thanks to @ntsekouras for continuing to chip away at code reviews 👏

**Comment by ntsekouras** [comment]
Thanks so much for all the contributions from everyone and especially the initiative of @colorful-tones and the organized contributors day! 🚀

**Comment by colorful-tones** [comment]
@ntsekouras I'm happy to do a follow-up pull request to take a pass at refining the consistency of some of these docs. Two items I'm currently seeing:

### Different use of `@return` (random sampling)

- `@return {JSX.Element} The rendered dropdown content.`
- `@return {Component} The component to be rendered.`
- `@return {JSX.Element|null} The rendered button component.`
- `@return {Component|null} The component to be rendered. Return null if the post type doesn't...`
- `@return {Element} The component to be rendered.`

### Description phrasing (random sampling)

- `Renders a control for enabling or disabling pingbacks and trackbacks in a WordPress post.`
- `Renders the PostSlug component. It provide a control for editing the post slug.`
- `This component renders a navigation bar at the top of the editor. It displays the title of the current...`
- `Component handles the keyboard shortcuts for the editor.`

**Comment by akasunil** [comment]
@colorful-tones I had the same thinking; I was waiting for the remaining documents to be completed so that we could refine them all at once.

**Comment by ntsekouras** [comment]
>I'm happy to do a follow-up pull request to take a pass at refining the consistency of some of these docs. Two items I'm currently seeing:

That sounds good, thank you!

> I was waiting for the remaining documents to be completed so that we could refine them all at once.

Yeah, it would be great to do them all at once, since the changes would be minimal.

**Comment by colorful-tones** [comment]
@ntsekouras it seems that `ServerSideRender` is deprecated and should not be on the list, correct? I just wanted to verify. Thanks.

https://github.com/WordPress/gutenberg/blob/247369bc1b081ad8546afccb774f9bf83efa692b/packages/editor/src/components/deprecated.js#L62

**Comment by ntsekouras** [comment]
>@ntsekouras it seems that ServerSideRender is deprecated and should not be on the list, correct? I just wanted to verify

You're right. I'll remove it.

**Comment by akasunil** [comment]
I would go with these options for documentation uniformity 

for return of component,
`@return {Component|null} The component to be rendered or null if the post type doesn't `

for description of component,
` Renders a control for enabling or disabling pingbacks and trackbacks in a WordPress post.`
Following simple structure of `Render { render what? } for { whats the use }` makes it easy to understand the purpose of component. 

@colorful-tones @ntsekouras  Let me know your thoughts.

**Comment by colorful-tones** [comment]
@akasunil I think your suggestions make sense.

I recommend we finalize the initial work in this issue, close it and then open a follow-up issue with notes/reference back to this one and submit a separate pull request towards the newer issue. Reasoning: clean break for work and intent, but I'm open to other ideas. Perhaps that is more work. 🤷

**Comment by colorful-tones** [comment]
@ntsekouras I'm not clear as to whether we need to add docs for `transformStyles`, as it is in `packages/editor/src/index.js`? 🤔 

https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/index.js#L16

**Comment by akasunil** [comment]
> recommend we finalize the initial work in this issue, close it and then open a follow-up issue with notes/reference back to this one and submit a separate pull request towards the newer issue.

Sounds good. And we will mention this issue in a new issue for future reference.

**Comment by ntsekouras** [comment]
Thank you all for the awesome work you did here! 🚀   Additional kudos to @colorful-tones for also organising a contributors day event!! `transformStyles` is just for back compat, so we can skip it and close this issue.

**Comment by akasunil** [comment]
@colorful-tones I have created issue https://github.com/WordPress/gutenberg/issues/62744 as we discussed
