### ISSUE TITLE
ConfirmDialog: Replace 'OK' with more descriptive label

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#60360]
### Description

See also https://github.com/WordPress/gutenberg/issues/60027

The `ConfirmDialog` component was introduced in https://github.com/WordPress/gutenberg/pull/34153 because of two main purposes:

Quoting from the related issues, see https://github.com/WordPress/gutenberg/issues/16583 and  https://github.com/WordPress/gutenberg/issues/33937

- The native `window.confirm()` isn't an ideal experience as we're unable to customise the OK button to have a more descriptive label.
- Major browsers - starting with Chrome - will soon restrict the alert/confirm/prompt functions from being used from within cross-origin iframes.

Regarding the first point, it appears some instances of the `ConfirmDialog` just use the default `OK` button text, thus defeating one of the purposes it was introduced for.

I'd tend to think re-enforcing the in-progress action by using a more meaningul button text would make the user experience better. Also, there's some inconsistency throughout the UI. I'd tend to think all `ConfirmDialog` should either use 'OK' oar a more specific text.

Some exampke screenshots:

![Screenshot 2024-04-02 at 11 49 38](https://github.com/WordPress/gutenberg/assets/1682452/8e552b4a-2e01-486c-8333-423e82a09ffc)

![Screenshot 2024-04-02 at 12 12 08](https://github.com/WordPress/gutenberg/assets/1682452/564687e1-8da9-42af-8a24-41a3b9173d3d)

![Screenshot 2024-04-02 at 11 46 16](https://github.com/WordPress/gutenberg/assets/1682452/1f9d95f4-0c53-47b6-8682-ecaf0dfac655)

![Screenshot 2024-04-02 at 11 50 52](https://github.com/WordPress/gutenberg/assets/1682452/7569b4d8-31e5-4a6f-9b67-254d71f0bd4a)

![Screenshot 2024-04-02 at 12 13 20](https://github.com/WordPress/gutenberg/assets/1682452/1d8d5653-b224-4e08-aa07-dcb3eac776cb)

![Screenshot 2024-04-02 at 12 19 38](https://github.com/WordPress/gutenberg/assets/1682452/4f58cbb8-028f-44a6-a8ca-8fc7933da6c5)

![Screenshot 2024-04-02 at 12 21 20 2](https://github.com/WordPress/gutenberg/assets/1682452/890a0ac3-1c75-4d44-8dbf-890c3911f07b)

### Step-by-step reproduction instructions

- Go through all ConfirmDialogs
- Observe the inconsistent pattern for the confirm button text.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by afercia** [comment]
Worth also noting that the 'Best practices` section added to the component readme in https://github.com/WordPress/gutenberg/pull/59825 now recommends to:

> Use a descriptive text for the _confirm_ button.

**Comment by afercia** [comment]
The ConfirmDialog used for switching to template editing is a special case. To me, its usage isn't ideal in the first place.

A ConfirmDialog should be used 'only for short confirmation messages where a cancel and confirm actions are provided.'.
The copy of this instance doesn't make very clear what the action to confirm is. It onlyy tells used they just did something.

`You’ve tried to select a block that is part of a template, which may be used on other posts and pages.`

Instead, ideally the copy should _ask a question_ or, at least, the action to confirm should me more clear.

Screenshot:

![Screenshot 2024-04-02 at 16 15 33](https://github.com/WordPress/gutenberg/assets/1682452/70b36a06-e2d4-4151-a719-9b9cecea6a9f)

Update:
I struggled a bit understanding how to make this ConfirmDialog appear. Steps:
- Go to the Site editor > Pages > edit a page.
- Double click on an empty area at the side of a block provided by the page template, e.g. the page title.

Originally, the copy of this dialog in https://github.com/WordPress/gutenberg/pull/51366 was `Edit your template to edit this block.`.

In https://github.com/WordPress/gutenberg/pull/60016 it was changed to `You’ve tried to select a block that is part of a template, which may be used on other posts and pages.` I do understand why it was changed, as the underlying functionality changed. However, a confirm dialog copy should always _ask a question_, whether it's an explicit or implicit question. I would like to change this copy, I'll try to think at something meaningful anc concise. Any suggestion would be appreciated Cc @noisysocks

**Comment by afercia** [comment]
What about `Would you like to edit the template this block is part of?`

**Comment by afercia** [comment]
The copy `Any unsaved changes will be lost when you apply this revision.` should be changed as well, to ask a question. I'd like to propose:

`Are you sure you want to apply this revision? Any unsaved changes will be lost.`

**Comment by noisysocks** [comment]
> What about `Would you like to edit the template this block is part of?`

Thanks for flagging. Works for me. I think we could drop the last part so that it is:

```
You've tried to select a block that is part of a template, which may be used on other posts and pages. Would you like to edit the template?

[Cancel] [Edit template]
```

**Comment by afercia** [comment]
Thanks for the feedback, A little verbose but it works for me.
