### ISSUE TITLE
Navigation mobile overlay closes unintentionally after clicking on submenu button

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#60371]
When the navigation block is set to open submenus via the click event instead of hover, the mobile submenu collapses unintentionally after the user clicks on the submenu button once. See the attached video.

https://github.com/WordPress/gutenberg/assets/20684594/a03094fc-d679-4c09-b9f8-7bc438ebe611

**Comment by fabiankaegy** [comment]
CC: @WordPress/interactivity-api

**Comment by annezazu** [comment]
@fabiankaegy is this happening in 6.5? If so, we should at this as a point release bug potentially.

**Comment by fabiankaegy** [comment]
@annezazu it is but I have not been able to test whether it isn't happening in 6.4.3. 

Will do that tomorrow. 

But yeah I do think this would be a nice point update

**Comment by fabiankaegy** [comment]
Okay I was able to test it on 6.4.3 now and the issue does not happen there. So it is 6.5 specify. Because of that I do think that we should add this to a patch release

**Comment by fabiankaegy** [comment]
I've been able to use the debugger to figure out that the issue is happening here:

https://github.com/WordPress/gutenberg/blob/dbd4cecdf862f481560dda325eb07fed58f26e3b/packages/block-library/src/navigation/view.js#L139-L156

When you click away from the button element the focus gets lost for a moment which gets used as a trigger to close the navigation.
