### ISSUE TITLE
Block pattern: Pattern using another inner pattern doesn't show in Inserter modal

### ISSUE THREAD

**Issue by DamChtlv** [WordPress/gutenberg#60379]
### Description

Inserter modal doesn't show patterns that contains other patterns.

### Step-by-step reproduction instructions

1. Create a first pattern _(will be our main pattern)_ and add it to your theme in `/patterns/` _(ex: `test-pattern-1.php`)_ : 
```php
<?php
/**
 * Title: Test pattern 1
 * Slug: abc/test-pattern-1
 * Categories: abc
 * Description: Test parent pattern issue
 * Keywords: test, parent, pattern
 * Block Types: core/post-content
 * Post Types: post, page
 * Inserter: true
 * Viewport Width: 1200
 * Source: theme
 */
?>
<!-- wp:pattern {"slug":"abc/test-pattern-2"} /-->
```

2. Create a second pattern _(will be our inner pattern)_ and add it to your theme in `/patterns/` _(ex: `test-pattern-2.php`)_ : 
```php
<?php
/**
 * Title: Test pattern 2
 * Slug: abc/test-pattern-2
 * Categories: abc
 * Description: Test pattern issue
 * Keywords: test, pattern
 * Block Types: core/paragraph
 * Viewport Width: 1200
 * Source: theme
 */
?>
<!-- wp:paragraph -->
<p>My text paragraph</p>
<!-- /wp:paragraph -->
```

3. Go to **Pages** _(or Posts)_, then click on "**Add new**"
4. Inserter modal should popup and allow you to select the pattern "**Test pattern 1**" but nothing happens:  
![image](https://github.com/WordPress/gutenberg/assets/6544224/222358f0-0ae9-4d86-ac1e-9a83e0d9b6aa)

5. Edit `test-pattern-1.php` to replace `wp:pattern` code with direct block code of `test-pattern-2.php` and save:
```php
<?php
/**
 * Title: Test pattern 1
 * Slug: abc/test-pattern-1
 * Categories: abc
 * Description: Test pattern issue
 * Keywords: test, pattern
 * Block Types: core/post-content
 * Post Types: post, page
 * Inserter: true
 * Viewport Width: 1200
 * Source: theme
 */
?>
<!-- wp:paragraph -->
<p>My text paragraph</p>
<!-- /wp:paragraph -->
```
6. Go back to **Pages** _(or Posts)_, then click on "**Add new**"
7. Inserter modal shows up:  
![image](https://github.com/WordPress/gutenberg/assets/6544224/4c94064d-94c1-426a-8733-9861670138af)

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/6544224/b21dd971-6a86-4c0d-9165-1f7320b7e6b2)

![image](https://github.com/WordPress/gutenberg/assets/6544224/467fd69c-33e6-449d-aa1c-d7c8e6faaed6)

### Environment info

- **WordPress**: 6.4.3 _(LTS)_
- **Gutenberg** _(same as WP 6.4.3)_
- **Browser**: Chrome
- **OS**: Windows

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Noting that afaik this came up previously in https://github.com/WordPress/gutenberg/issues/39732 and was fixed. I wonder what's gone wrong here. @richtabor might you know?

**Comment by DamChtlv** [comment]
For further information, it does render correctly in Appearance > Editor > Patterns but the modal doesn't popLe 2 avr. 2024 20:46, annezazu ***@***.***> a écrit :
Noting that afaik this came up previously in #39732 and was fixed. I wonder what's gone wrong here. @richtabor might you know?

**Comment by talldan** [comment]
I wasn't able to reproduce the issue. The pattern shows up first time at 'step 4' in the reproduction steps for me.

Could've been an issue with 6.4 that's now resolved, as that seems to be what @DamChtlv used.

I tested with 6.5 and the gutenberg plugin active.

**Comment by DamChtlv** [comment]
Hello,
Sorry for the waste of time... i found the issue:
- I had a filter on `allowed_block_types_all` and `core/pattern` wasn't part of the `$allowed_blocks` array which seems to have caused the initial issue.
I tested on 6.5 and removed the filter code part, with & without gutenberg plugin, it does work correctly now.

**Comment by annezazu** [comment]
Happy to hear it! Thanks, folks.
