### ISSUE TITLE
Save user's current styles as custom styles

### ISSUE THREAD

**Issue by unprintedch** [WordPress/gutenberg#60386]
## What problem does this address?
The current experience of managing styles in 6.5 feels great. The addition of the fonts library is incredible.
And it feels fantastic to customize every aspect of the theme typography, color and blocks. 
Once we are done and happy, I find it sad that there is no real materialization of the effort.
We can't save and name our styles? And it is easy, mistakenly, to return to the base styles.
Even if there is this very good restore system, it feels like we never own our design.

Would it be a good addition to save the current state and be able to name it?

I did i like simulation (design is not perfect) but it tells the story:
[See the figma prototype](https://www.figma.com/proto/mjaUKOXUeTF04yyfnOrJI0/WordPress-Design-Library-dc-1?page-id=88200%3A9083&type=design&node-id=88200-9083&viewport=321%2C331%2C0.48&t=lasTCxCk11Cq8BOD-1&scaling=min-zoom&starting-point-node-id=88206%3A16351&mode=design)

### Start from one of the existing styles
<img src='https://github.com/WordPress/gutenberg/assets/2622001/59f3d262-6c2c-4d35-aef6-fe64b25ff652' width='300'>

### Edit name
<img src='https://github.com/WordPress/gutenberg/assets/2622001/0f5a757f-322e-4d7d-a9ea-1462e402f558' width='300'>

### The custom styles are marked 
<img src='https://github.com/WordPress/gutenberg/assets/2622001/0d042171-1fee-4417-bf8b-0afacb1f1cb4' width='300'>

**Comment by annezazu** [comment]
Hey @unprintedch! Thanks for opening this issue. Like you, I'm excited about all that's possible. For this specific use case, it's actually already covered in this prior issue: https://github.com/WordPress/gutenberg/issues/45371

As a result, I'm going to close this out and encourage you to leave a comment on that issue with what you shared. 

In case it's helpful, the Create Block Theme plugin can be helpful for this too and work is underway to move saving style changes to the Site Editor: https://github.com/WordPress/create-block-theme/pull/532#top Currently, you can manage that from WP Admin in the plugin.

**Comment by unprintedch** [comment]
Oh thanks. Sorry about that i could not find some related issues and it felt strange since it seems so obvious to me we need this.

**Comment by annezazu** [comment]
No need to apologize! Always default to open an issue. It's on those of us who help triage to connect the dots when needed.
