### ISSUE TITLE
HTML API: Plans for 6.7

### ISSUE THREAD

**Issue by dmsnell** [WordPress/gutenberg#60396]
[🔝Block API](https://github.com/WordPress/gutenberg/issues/41236) | [HTML issues](https://github.com/WordPress/gutenberg/discussions/57560) | [Refactors](https://github.com/WordPress/gutenberg/discussions/54750) | [↑ Broader Roadmap](https://github.com/WordPress/gutenberg/issues/60397) | [← Plans for 6.6](https://github.com/WordPress/gutenberg/issues/60324) | [→ Plans for 6.8](https://github.com/WordPress/gutenberg/issues/63037)

## Publications

 - [Updates to the HTML API in 6.7](https://make.wordpress.org/core/wp-admin/post.php?post=114692&action=edit)
 - [Progress Report: HTML API](https://make.wordpress.org/core/2024/09/11/progress-report-html-api-3/)

## Pre-release checklist.

 - [ ] Review all docblocks and ensure they have appropriate example code.
 - [ ] Review HTML API class docblocks and ensure they are updated to match currently support.
 - [ ] Gather all non-`trunk` bug-fixes and enhancements into the _Updates to the HTML API_ post.

## Lingering work from 6.6

 - [x] Review all of the push/pop mechanics and polish them, figure out the proper comprehensive model of operation, and refactor the internals to ensure they are elegant and can be introspected.

## Added Spec Support (Core-61576)
 - Tag supports:
   - [x] SVG and MathML foreign content.
     - WordPress/wordpress-develop#6006 
     - [ ] Have `get_qualified_tag_name()` return lowercase tag names.
   - [x] TABLE support.
     - WordPress/wordpress-develop#6040
   - [x] SELECT support.
     - WordPress/wordpress-develop#5908
   - [x] FORM support.
   - [x] TEMPLATE support.
     - https://github.com/WordPress/wordpress-develop/pull/7046
   - [ ] PLAINTEXT support.
     - WordPress/wordpress-develop#5905
 - Various supports:
   - WordPress/wordpress-develop#6973
   - Wordpress/wordpress-develop#6983
   - WordPress/wordpress-develop#6982
   - WordPress/wordpress-develop#6020
   - WordPress/wordpress-develop#6972
   - WordPress/wordpress-develop#6977
   - WordPress/wordpress-develop#6981
   - WordPress/wordpress-develop#7041
   - WordPress/wordpress-develop#7042
   - WordPress/wordpress-develop#7044
   - WordPress/wordpress-develop#7085
   - WordPress/wordpress-develop#7141
   - WordPress/wordpress-develop#7165
   - WordPress/wordpress-develop#7281
   - WordPress/wordpress-develop#7282
 - Text handling
   - WordPress/wordpress-develop#7230
   - WordPress/wordpress-develop#7236
 - [x] Parse DOCTYPE public and system identifiers, used for detecting quirks mode.
   - WordPress/wordpress-develop#7195

 - Testing and verification (Core-61646, Core-61530)
   - WordPress/wordpress-develop#6984
   - WordPress/wordpress-develop#6985
   - https://github.com/WordPress/wordpress-develop/pull/7043
   - WordPress/wordpress-develop#6765
   - WordPress/wordpress-develop#7030
   - WordPress/wordpress-develop#7117
   - WordPress/wordpress-develop#7285

## New Features and Interfaces

 - [x] Core-61617 Add `set_modifiable_text()` for plaintext-only modifications.
   - WordPress/wordpress-develop#7007
   - WordPress/wordpress-develop#7150
 - [x] Core-62036 Add `normalize()`, `serialize()`, and `get_full_comment_text()`
   - WordPress/wordpress-develop#7342
   - WordPress/wordpress-develop#7331

## Bug Fixes
 - Core-61560 The Fragment parser should not add the context node to the stack of open elements.
 - Core-61851 `HTML_Processor::next_tag()` should respect the `tag_name` argument.
   - WordPress/wordpress-develop#6980
 - Various fixes:
   - WordPress/wordpress-develop#6988
   - Core-61719 If `kses` rejects an attribute update, `set_attribute()` should return `false`.
     - WordPress/wordpress-develop#7114
   - Core-61810 Infinite loop on inputs with a missing SCRIPT end tag, which end in `-` or `<`.
     - WordPress/wordpress-develop#7128

 - Audit of CSS semantics and behaviors (Core-61531)
   - WordPress/wordpress-develop#6933
   - WordPress/wordpress-develop#7195
   - WordPress/wordpress-develop#7187
   - WordPress/wordpress-develop#7169

## Enhancements

 - Core-61545 General performance improvements.
   - WordPress/wordpress-develop#6890
 - Core-61399 Add type annotations to HTML API code.
   - WordPress/wordpress-develop#6753
   - WordPress/wordpress-develop#7031

 - [ ] Add `is_self_contained_element()` to identify special atomic elements like `SCRIPT`, `STYLE`, `TITLE`, etc…
   - WordPress/wordpress-develop#7198

## Blocks

 - [ ] Continue developing block attribute sourcing.
 - [ ] Iterate on the Server Directive Processor.
 - [ ] Iterate on the Block Bindings processor. 

## Not likely in 6.7

 - [ ] Setting inner or outer HTML _because_ it should parse the provided new HTML in a fragment parser whose context node is the one in which it is found. Also, because we have to solve the problem of composition and avoiding re-parsing every level of inner content.
   - With outside help a form of this may make it in to 6.7.

## Backports into Gutenberg

 - WordPress/gutenberg#63089

**Comment by gziolo** [comment]
[WordPress 6.7 “Rollins”](https://wordpress.org/news/2024/11/rollins/), which contains all the finished work, was released last week. The work for unfinished but still applicable tasks will continue in the new iteration issue https://github.com/WordPress/gutenberg/issues/63037.
