### ISSUE TITLE
Reconsider including `gutenberg.pot` in the repository

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#604]
In general a source control repository should not store files that are derived from other source files.  With almost every code change we make, there are corresponding changes in `gutenberg.pot`.  It's easy to miss updating this file (see #603 for an example), and I think we really only need it when we do a build.  In that case, shouldn't we remove it from the repository (ignore it) and just cause it to be generated as part of the build step?

One thing that's not clear to me is where and how the actual translations of our strings will be stored, but I think this would be outside of source control as well.

**Comment by aduth** [comment]
This has become enough of a pain point that I'd agree it's probably best to ignore in the repository. Alternatively I'd considered having a bot to generate these automatically upon each commit, but there's not a good core reconciliation story there.

**Comment by nylen** [comment]
Changed this to a bug because it's currently the reason that #603 has merge conflicts with `master`.  I'm about to fix it, but still.
