### ISSUE TITLE
Allow dragging blocks from the up/down arrow mover controls

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6041]
## Issue Overview
For small blocks like Headings or one-line Paragraphs, there is very little space that can you can drag the block from. One would think that you would be able to click, hold, and drag the block from the up/down arrow buttons, but you can not do this, unless the arrows are disabled. This leaves only a small amount of space left for dragging.

## Expected Behavior
When you click and drag on the up/down arrow buttons (and maybe also the 3-dots "More Options" button), you can drag the block.

## Current Behavior
Trying to drag the block from the up/down arrow buttons and the 3-dots "More Options" button does not work. You can only drag the block from the small area around the arrows/"More Options" button and below, and the area below is quite small for blocks with little vertical height.

## Related Issues and/or PRs
#6032

**Comment by paulwilde** [comment]
I must admit, this is actually where I thought the drag handler was implemented when I saw D&D got merged, and it took me a little figure out how to D&D blocks. So +1 from me.

**Comment by theleemon** [comment]
This!

**Comment by karmatosed** [comment]
As it seems related lets close this and focus on #6032, a solution can be found there that aligns.
