### ISSUE TITLE
[2.6.0] Exp Columns - Shortcode columns no longer wrapped with div .layout-column-1 class

### ISSUE THREAD

**Issue by opicron** [WordPress/gutenberg#6042]
On 2.5.0 shortcode columns in experimental columns block are wrapped in a div with the class layout-column-1. In 2.6.0 this no longer seems to be the case.

**Comment by paulwilde** [comment]
See #5935 and #5351.

**Comment by aduth** [comment]
When you say "wrapped", do you mean in the markup saved for the post, or as shown in the editor?
