### ISSUE TITLE
Font Library: Plan for WP 6.5.3

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#60421]
Here is a list of issues/PRs that need to be solved for the next WordPress core patch version 6.5.1. **Please propose the issues you think should be included in the release.**
 
### Bugs: 
 - [x] https://github.com/WordPress/gutenberg/issues/60343
 - [x] https://github.com/WordPress/gutenberg/pull/60641
 
 ### Enhancements:
 - [ ] https://github.com/WordPress/gutenberg/issues/59704

**Comment by t-hamano** [comment]
I think this issue should also be included.

- https://github.com/WordPress/gutenberg/issues/60392

**Comment by creativecoder** [comment]
Noting that the release candidate for 6.5.3 is scheduled for tomorrow. There are 2 open issues here in the description/comments:

- [ ] https://github.com/WordPress/gutenberg/issues/60392

I've added this one to the 6.5.x editor task board, for consideration in a future minor release.

- [ ] https://github.com/WordPress/gutenberg/issues/59704

This one is an enhancement, and generally minor releases only include bug fixes, so I've added it to the WP 6.6 project board instead.

---

With those issues sorted, I'll go ahead and close this tracking issue. If there are any more font library bugs that might be included in a 6.5.x minor release, please add them to the "[WordPress 6.5.x Editor Tasks](https://github.com/orgs/WordPress/projects/186) project for discussion.
