### ISSUE TITLE
Make CodeEditor Component more extendable

### ISSUE THREAD

**Issue by JasonHoffmann** [WordPress/gutenberg#6043]
## Issue Overview
The new lazy-loaded Codemirror component is very well-written and could most likely be useful to other blocks trying to use a CodeEditor component in their blocks. However, because the [CodeEditor](https://github.com/WordPress/gutenberg/blob/aaf60605914958a5ba394685f76fc977ac66fb28/components/code-editor/editor.js) component is wrapped inside of the [lazy loaded component](https://github.com/WordPress/gutenberg/blob/aaf60605914958a5ba394685f76fc977ac66fb28/components/code-editor/index.js), there is no access to the CodeEditor props or Codemirror instance if you want to use that as a standalone component, and no way to even extend the component to replace it with different methods.

My use case is that I am building a syntax highlighting block where the Codemirror component would be extremely useful. However, I need to be able to pull out a reference to the editor from the component so that I can toggle the `mode` of Codemirror based on user input.

## Possible Solution

What would very helpful is if there was a way to:
1. Customize the initial settings used by CodeMirror
2. Get a reference to the editor and props from the `LazyCodeEditor` component each time the `CodeEditor` component is updated.

You can imagine it looking something like this:
```
const { CodeEditor } = wp.components;

const onChange = ( editor ) => {
    // newModeVariable is grabbed from this components state.
    editor.setOption( 'mode', newModeVariable );
};

const settings = window._wpGutenbergCodeEditorSettings;
settings.codemirror.mode = this.state.mode;
settings.codemirror.lint = false;

...
 return (
    <CodeEditor
        onChange={ onChange }
        settings= { settings }
    />
);
```

This would require the `LazyCodeEditor` to accept two props, a function for `onChange` and a `settings` object. It could then pass those props down one step further to the actual `CodeEditor` component which could use the settings prop if one is provided, and call the `onChange` function each time `componentDidUpdate` was called, with a reference to the editor and props. This would make the component far more extendable for use in other blocks.

I'd be happy to clarify further if necessary, and if this feels like a worthwhile addition, put together a PR for review that implements the above. 

Any thoughts or feedback would be much appreciated.

**Comment by BenAttenborough** [comment]
Yes I find it confusing as to how to even update the Code Editor block. There is no setAttributes prop. I can create a plain text block and update it easily. The same doesn't seem to work here.
Is it possible to use a code editor block alongside a plain text block?

**Comment by noisysocks** [comment]
Resolved by https://github.com/WordPress/gutenberg/pull/6147.
