### ISSUE TITLE
Performance tracking issue for 6.6

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#60435]
Edit: template previewing is now ⅓ faster for 6.6.

All results: https://docs.google.com/spreadsheets/d/1kQF-SKwanquvdBiKXiJYZKsviRoU256M_tf_-oDd95M

---

It's too early to tell how much we can do, I'll just list the PRs here as they get made.

So far we probably have a -40% for loading templates. I don't think we'll manage to improve other load metrics though.

This issue keeps track of all related PRs.

https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+is%3Aclosed+label%3A%22%5BType%5D+Performance%22

**Load (Editor/Preview/Pattern/Templates)**

- https://github.com/WordPress/gutenberg/pull/60349
- https://github.com/WordPress/gutenberg/pull/60330
- https://github.com/WordPress/gutenberg/pull/60297
- https://github.com/WordPress/gutenberg/pull/60382
- https://github.com/WordPress/gutenberg/pull/60310
- https://github.com/WordPress/gutenberg/pull/60425
- #60543
- #60544
- #60546
- #60572
- #60612
- #60674
- #60682 
- #60967
- #60988
- #61000
- #61139
- #61329

**Comment by annezazu** [comment]
Heads up to @WordPress/performance as we slowly begin to look towards 6.6. This issue will be kept up to date as performance work continues!

**Comment by bridgebrain** [comment]
Having an option to disable template previews would be appreciated. They're causing my page to crash every time I go to change templates

**Comment by ellatrix** [comment]
@bridgebrain We're going to make a lot of improvements for templates this release so I'd hope that fixes the crash. May I ask what theme you have installed? And what device and browser are you on?

**Comment by fabiankaegy** [comment]
Hi all 👋 

Reminder: The release candidate for Gutenberg Version 18.5 is scheduled for next Friday (May 31st). So anything that is supposed to make it into WordPress 6.6 must be merged by then. 

Please raise any important issues that need additional attention :)
