### ISSUE TITLE
__experimentalUseHasRecursion deprecation is attempting to spread a non-iterable variable

### ISSUE THREAD

**Issue by albanyacademy** [WordPress/gutenberg#60437]
### Description

https://github.com/WordPress/gutenberg/blob/fd060e347248a30864ba23e302152d13598ec072/packages/block-editor/src/components/recursion-provider/index.js#L79

__experimentalUseHasRecursion accepted a string argument (above), the deprecation instead tries to spread a props object (below)

https://github.com/WordPress/gutenberg/blob/49532f3a881419503d8bbf6731c7d77b87befdb4/packages/block-editor/src/components/recursion-provider/index.js#L100

### Step-by-step reproduction instructions

make a block that uses __experimentalUseHasRecursion in Wordpress 6.4.3 and in 6.5.

observe that it works with a unique id as the sole argument in 6.4.3, and that it errors in 6.5 with this message in console appearing: `TypeError: e is not iterable`

### Environment info

wordpress 6.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting @albanyacademy. I've put together a fix, which should land in the next minor WordPress release.

**Comment by albanyacademy** [comment]
no worries, i absolutely wasn't using an experimental feature in a production environment by the way, nope no way just happened to notice it somehow for completely different reasons 😬
