### ISSUE TITLE
Github Action to notify contributors to use Playground for PR testing. 

### ISSUE THREAD

**Issue by ankitguptaindia** [WordPress/gutenberg#60433]
## What problem does this address?

As a Test Team Representative, I've observed that new contributors prefer utilizing the Playground environment for testing core tickets instead of setting up a Local environment.

In Core ticket Pull Requests (PRs), a GitHub action automatically generates a comment regarding the use of the Playground for testing. Since Gutenberg PRs can also be tested using the [Gutenberg PR testing](https://playground.wordpress.net/gutenberg.html) link, it would be advantageous to include a [similar message](https://github.com/WordPress/wordpress-develop/pull/5996#issuecomment-1920188402) in the PR comments to facilitate easier access to the testing environment.

## What is your proposed solution?

Implementing a GitHub action for Gutenberg PRs would greatly benefit new contributors by providing them with easier access to the testing environment.

![image](https://github.com/WordPress/gutenberg/assets/6384299/901cb37b-a2b4-43ff-8f96-30c49d7683cb)

**Comment by Mamaduka** [comment]
The proposal is being tracked in #60795.
