### ISSUE TITLE
Command Palette: Add 'Template Parts' command

### ISSUE THREAD

**Issue by mattreport** [WordPress/gutenberg#60443]
## What problem does this address?
When I'm working on templates in the site editor, I'll often have the need to also quickly jump to the Template Parts section to work on common parts like the header or footer. 

The Command Palette is generally my tool of choice when navigating the many avenues of the site editor, but sadly, 'template parts' is not a command that the palette is aware of. 

While I'm pleased with the efficiencies CP brings during 90% of my daily driving, breaking out the mouse to customize my template parts is draining.

## What is your proposed solution?
It's time to include Template Parts in the command palette.
![GKRI9K1XsAE6xiZ](https://github.com/WordPress/gutenberg/assets/161349953/f41c85bc-13e2-400f-ac48-05d69e7d80bc)

**Comment by markjszymanski** [comment]
Great enhancement suggestion, good sir. I too hope it is implemented swiftly!

**Comment by andrewserong** [comment]
I believe as of https://github.com/WordPress/gutenberg/pull/52817 it looks like the `Template Parts` command was removed, and consolidated into `Patterns`. If you use the command `Patterns`, that'll take you to the patterns part of the site editor, which also lists the current template parts. Is that a close enough match? Or were you expecting a command that would directly take you to the "Manage template parts" screen, that's just a list of template parts (e.g. `/wp-admin/site-editor.php?path=%2Fwp_template_part%2Fall`)?

If so, restoring a command for `Template Parts` that directs to that part of the site editor sounds like a reasonable idea to me.

**Comment by bacoords** [comment]
> a command that would directly take you to the "Manage template parts" screen, that's just a list of template parts (e.g. /wp-admin/site-editor.php?path=%2Fwp_template_part%2Fall)

+1 to this idea

**Comment by mattreport** [comment]
I believe that `Template Parts` deserves equal representation on the command list as they are critical components to `Templates` Command switching to `Patterns` and then having to click into `Template Parts` feels like they aren't much of a priority for builders. 

They even have their own color in the block list, lets give them their own cmd+k, too.
