### ISSUE TITLE
core/file block causes page to remain in "update" mode

### ISSUE THREAD

**Issue by smetzdev** [WordPress/gutenberg#60461]
### Description

When i use the file block on a page, it causes the "Update" button for the page to always be activated.
If i reload the page the "Do you really wan't to leave" Browser dialogue is shown.

This behaviour happens even if i haven't changed anything and ceases after i remove all core/file blocks

### Step-by-step reproduction instructions

1. Go to any Page in the editor
2. Use the file block for a download
3. Link a pdf
4. Hide button and preview
5. Hit update
6. Refresh the page

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/29286869/2d5a4276-ea87-4410-86d0-2946a9b88589

### Environment info

WordPress Version 6.5
Frost Theme Version: 1.0.8
Core Gutenberg Version

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I can also reproduce the bug with the latest Gutenberg plugin. I believe it's due to the side effect that sets the `downloadButtonText` translatable default text.

**Comment by talldan** [comment]
> I can also reproduce the bug with the latest Gutenberg plugin. I believe it's due to the side effect that sets the downloadButtonText translatable default text.

The way that works seems a little unusual. If the user deletes the button text and saves, when they reload 'Download' comes back again.

I wonder if it'd be better to leave it empty in the editor, and only have 'Download' filled in as the default when empty on the frontend (e.g. via `save.js` or `index.php`). 🤔

**Comment by Mamaduka** [comment]
You can't use `save.js` because a translatable string will break the block validation, and all strings should be translatable in the core.

I was thinking of using HTML API in `index.php`, but last time I checked, it couldn't replace text content for an HTML tag.

**Comment by talldan** [comment]
True, I forgot about that. Hopefully soon the HTML API will get that feature 🤞
