### ISSUE TITLE
Add a filter to block_core_image_print_lightbox_overlay

### ISSUE THREAD

**Issue by webzunft** [WordPress/gutenberg#60470]
I am the developer of an image caption plugin for publishers who need to show image attributions for legal reasons.
With WordPress 6.5, lightboxes no longer show the caption I added to images in the post content since lightbox HTML is not rendered separately.

Ideally, I could add a placeholder for the caption into `block_core_image_print_lightbox_overlay()` using a filter, but there is none.
Would you be able to provide one?

In a next step, I would need to figure out how to fill it, but the `render_block_core/image` filter might just be good for that.

**Comment by annezazu** [comment]
Hey @webzunft! Thanks for opening this. I'm going to consolidate it with this recent issue https://github.com/WordPress/gutenberg/issues/60469

I'll move your question there. Please follow along in that issue going forward.
