### ISSUE TITLE
Pages data view: Clarify 'Date' field

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#60477]
Here's how the Date field looks in the Pages data view:

<img width="1115" alt="Screenshot 2024-04-04 at 18 23 42" src="https://github.com/WordPress/gutenberg/assets/846565/a538f8d2-ed1b-4a3e-bb74-183548d17aad">

It's not clear which date is being referred to. Specifically; is it the publish date, the modified date, or something else? This detail is clarified in wp-admin with a preceding label:

<img width="1307" alt="Screenshot 2024-04-04 at 18 25 04" src="https://github.com/WordPress/gutenberg/assets/846565/ff9a43f2-a3ff-4bac-841e-9e3281a8edc5">

---

I suppose the simplest way to tackle this would be to mimic wp-admin and add a prefix. Are there other ways, could/should publish date and modified date be split into separate fields?

cc @WordPress/gutenberg-design @ntsekouras @oandregal for feedback.

Edit: Based on discussion below, let's start simply by adding the prefix:

<img width="1113" alt="Screenshot 2024-04-12 at 13 49 24" src="https://github.com/WordPress/gutenberg/assets/846565/90d20fba-4685-4ab3-be57-0f2334cff487">

**Comment by jasmussen** [comment]
This'll take some finessing, but it might be hard to not have to need two lines of text there. It might be good to gather a bit of comparison material across other apps that have similar formats, see what standards there are.

**Comment by jameskoster** [comment]
I don't know that it needs to involve two lines. The prefix could be a single word: `Modified: April 5, 2024, 09:55`, `Published: April 5, 2024, 09:55`.

**Comment by jameskoster** [comment]
That said...

> could/should publish date and modified date be split into separate fields

I think this could be worth discussing. Filtering by publish date (a legitimate use case) is very different to filtering by modified date (still legitimate, but probably less common?).

**Comment by jasmussen** [comment]
You'd only ever see Published or Modified, in the existing pages, right? That would simplify things, and maintain the value as well as the density.

Building on your suggestion but using the existing date format, this isn't bad:

* Modified: Apr 5, 2024 09:55
* Published: Apr 5, 2024 09:55.

Mainly wondering, could we/should we make an effort to ensure the dates line up vertically, even if the prefix varies in width?

**Comment by jameskoster** [comment]
> You'd only ever see Published or Modified, in the existing pages, right?

Also "Scheduled". 

> make an effort to ensure the dates line up vertically

Yeah that's a bit tricky. We might have to choose between vertically aligned dates or separate lines. 

Another option could be to use a 'human friendly' date format e.g. "Published 30 minutes ago" which might mitigate the alignment issue? The actual timestamp could appear in a tooltip on hover if required.

**Comment by ntsekouras** [comment]
I have no strong opinion about this, but if we feel like both modified and published dates have value, we should probably have them as separate fields. That would probably help with the filtering (when we have date filters).

Additionally if we render both dates in a single field (two lines), I guess in some of them we'll only have one and I'm not sure if this affects the design for any reason. An example is draft posts will always have only modified date.

**Comment by jameskoster** [comment]
I suppose the usefulness of separate fields is:

1. The simplification of filters like "Show all pages published in January". To do this currently you'd need to filter by date _and_ status.
2. The ability to filter all pages specifically by _modified_ date (including ones that have been published or scheduled). Currently this isn't possible.

Seemingly the modified date is already tracked somehow as it appears in the Inspector:

<img width="280" alt="Screenshot 2024-04-05 at 12 40 45" src="https://github.com/WordPress/gutenberg/assets/846565/b04d11ce-c1f4-48b6-853e-c9adef8f5287">

So I guess it wouldn't be a big lift to make it a field?

> An example is draft posts will always have only modified date.

I think that's okay given the explicit labels. It would be strange for a draft post to have a publish date.

**Comment by jasmussen** [comment]
I'd tend to reach parity first, and then expand beyond that when we know it's necessary. This is a cat that's hard to put back in the bag. Easy to expand, hard to contract.

**Comment by jameskoster** [comment]
Agreed. For now let's mimic wp-admin, IE add the prefix.

We can follow-up to discuss in more detail the addition of a separate 'modified date' field.

**Comment by ntsekouras** [comment]
>Agreed. For now let's mimic wp-admin, IE add the prefix.

Does that mean just change the label from `date` to `published date`, or something different?

**Comment by jameskoster** [comment]
@ntsekouras no, because we need to capture modified dates for drafts. So for now it means adding a prefix to the field value. I added a screenshot to the OP.

**Comment by oandregal** [comment]
I'm giving this one a shot.

**Comment by oandregal** [comment]
PR at https://github.com/WordPress/gutenberg/pull/61709
