### ISSUE TITLE
Data views: Make filter reset button contextual to the view

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#60472]
Closely related to https://github.com/WordPress/gutenberg/issues/60468.

When you browse a view like "Trash" in page management the "Reset" button in the filter UI is visible by default, and clicking it will remove all filters. 

Technically this is more like a "Remove" behavior, which in this context makes the "Reset" label a bit misleading. 

Instead, we might consider making the filter reset action contextual. IE when you navigate to the Trash view, the "Reset" button is hidden/disabled, and only becomes active when you add/edit any filters. Clicking it would restore the view to its initial filter configuration, IE status filter active and `trash` selected.

cc @WordPress/gutenberg-design @ntsekouras @oandregal for thoughts.

**Comment by SaxonF** [comment]
I think this would lead to the reset filter action feeling unpredictable . A "discard changes" indicator and action next to view title (both in list and content frame) would be worth exploring

**Comment by jasmussen** [comment]
Responded [here](https://github.com/WordPress/gutenberg/issues/60468#issuecomment-2039030883) as well, I find it confusing to see a filter chip simpy by choosing a main navigation item. I would expect main navigation items to be preset views not ephemeral filters.

**Comment by jameskoster** [comment]
> I think this would lead to the reset filter action feeling unpredictable

How do you feel about the button label reading "Remove filters" in bundled views? It seems confusing to me that if you filter a view like trash, then click "Reset", you do not see trash...

**Comment by jameskoster** [comment]
Out of the discussion in https://github.com/WordPress/gutenberg/issues/60468 it emerged that this is probably the way to go.

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/65264 will close this by introducing the concept of "locked view filters" — those are invisible to the user, so the reset button still behaves predictably to them (removes all visible filters).

**Comment by jameskoster** [comment]
I think this is fixed now. If you add filters to the Trash view, then click Reset, you no longer see all pages.
