### ISSUE TITLE
Text in various blocks does not break/wrap at block boundaries (Gecko/Firefox default styling issue)

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6049]
## Issue Overview
The following blocks do not break/wrap long strings of characters when they reaches the edge of the block in the editor:
- Cover Image
- Heading
- Image
- List
- Paragraph
- Pullquote
- Quote
- Subhead

Some blocks do break/wrap long strings of characters when they get too long, like the Button, Code, and Shortcode blocks. I would expect most other blocks to act the same, with the exception of some blocks like the Preformatted block and maybe Verse block.

## Steps to Reproduce (for bugs)
1. Insert a Paragraph block (or one of the other affected blocks listed above).
2. Type a whole bunch of "w"s or other characters into the block to create a really long string of text.
3. Notice that it does not break/wrap when it reaches the edge of the block, but instead just keeps on going all the way off the screen.
4. Insert a Button block.
5. Type a long string of characters again.
6. Notice that the text is broken and wrapped when it gets too long, like you would expect.

## Expected Behavior
Text in most blocks should always break and wrap once it reaches the boundaries of the block.

## Current Behavior
Long strings of characters without any breaking characters like spaces or hyphens will just extend outside the boundaries of the block and go off the screen. This is especially noticeable when using nested blocks in columns.

## Related Issues and/or PRs
#5130

**Comment by youknowriad** [comment]
These blocks do wrap for me, you may have an extra style loaded by a plugin that breaks these blocks.

**Comment by SuperGeniusZeb** [comment]
@youknowriad I just tested without any plugins and with the Twenty Seventeen theme, and the text is still not wrapping properly.

(I am using Gutenberg 2.6.)

![image](https://user-images.githubusercontent.com/19592990/38512678-7df34d0c-3bf1-11e8-82a2-28174bf0e8e0.png)

**Comment by youknowriad** [comment]
Here's the same thing for me, maybe it's browser specific, tested in Firefox/Chrome Mac

<img width="720" alt="screen shot 2018-04-09 at 18 33 21" src="https://user-images.githubusercontent.com/272444/38512937-9d5d0a88-3c24-11e8-9bd4-04d88ed39095.png">

**Comment by youknowriad** [comment]
It looks like Firefox do wrap if you have have spaces. What's the correct behavior here @jasmussen ? Should we always wrap even without space?

**Comment by SuperGeniusZeb** [comment]
@youknowriad I just tested, and uninterrupted strings of characters are wrapped in Chromium, but not Firefox, which is the browser I am using.

I'm guessing this is a difference in default browser behavior? Concerning what Gutenberg should do, I think always wrapping text when there is no other possible break point is a more useful behavior, both for the editor and the front-end.

This can be accomplished with the CSS property `overflow-wrap`.

**Comment by jasmussen** [comment]
We should always wrap, ideally we break words, but if we can't we should break even without spaces. Can confirm this is also broken in Firefox for me. Going to take this one.

**Comment by shryber** [comment]
@jasmussen I am still seeing this on my website neutro.net when I view it on Chrome (Desktop windows 10 and android 11 version 86.0.4240.111) but no on firefox (mobile version 82.1.1).
The problem is when I have a long URL in a Code block.
You can see my site https://www.neutro.net/setting-neutro-up/
WordPress 5.5.1
Theme Neve Version: 2.8.3

![image](https://user-images.githubusercontent.com/10706767/97637156-71868a00-1a3a-11eb-8cac-0b18f0104cb7.png)
Not sure if this is something you still do but I didn't find a better thread. Anyway, thanks for working on improving Gutenberg.

**Comment by jasmussen** [comment]
Hi @shryber, it looks like the text that doesn't wrap in your screenshot is pasted inside a code block, correct? 

I believe that at the moment, the code block intentionally does not provide any wrapping, but I can also see that it doesn't provide any overflow management either (such as a horizontal scrollbar). Please feel free to open a separate ticket and CC me and we can look at adding something there.

**Comment by shryber** [comment]
@jasmussen Opened a new issue: https://github.com/WordPress/gutenberg/issues/26600#issue-733216034
When you say CC here, should I tag you in the post or is there a specific feature I am missing?
Thanks!

**Comment by jasmussen** [comment]
All good, it's on my radar now, thanks. I'll take a look next week, my day is about to wrap here.

**Comment by shryber** [comment]
Great, thanks so much!  





On Fri, Oct 30, 2020 2:54 PM, Joen A. notifications@github.com  wrote:


All good, it's on my radar now, thanks. I'll take a look next week, my day is
about to wrap here.
