### ISSUE TITLE
Data Views: Revisit layout config structure

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#60507]
Currently in `view` config we have an optional config prop (`layout`) per layout type (`grid`, `table`, etc..).

We're starting to have several kind of displays for fields: primary, media, badge (maybe others in other layouts). It would be good to check if we can consolidate somehow. 

We should check whether existing `layout` config props could be reused in every layout and moved to `fields` API (example `primaryField`), we should check whether existing props should be moved to the `render` function of a field  (example `badgeFields`), and we should explore how/whether to update the `visibleFields` with a different structure. An example [suggestion](https://github.com/WordPress/gutenberg/pull/60284#discussion_r1553370386) by @youknowriad is:

> Maybe visibleFields could support arrays as fields: [ [ { field: 'preview', display: 'media' }], { field: 'title', display: 'primary' }], { field: 'sync-status', display: 'badge' }, 'anyrandomfield' ]

**Comment by youknowriad** [comment]
I'm going to close this issue for now, I'm not entirely satisfied with the current structure but there's no clear and better alternative.
