### ISSUE TITLE
Expected responsive use values

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/gutenberg#60519]
## What problem does this address?
When I use Editor in responsive mode, I expect to change values and keep customized for that size of screen. That would solve the most of issues regarding with responsive fixes. 

## What is your proposed solution?
When you change to Mobile or Tablet, the values for Font size, Margin and Padding would have to keep different values. So we could fix all problems with mobile.

![responsive-font](https://github.com/WordPress/gutenberg/assets/10096360/52d1672e-986d-4909-bd3c-7bb17207fe54)
![responsive-margin](https://github.com/WordPress/gutenberg/assets/10096360/2e43362e-0ded-4f1d-9b9b-e824c2a3bf18)

CC: @mtias @cbravobernal

**Comment by jordesign** [comment]
HI @davidperezgar  - the kind of thing you've mentioned is being discussed in these places:

* https://github.com/WordPress/gutenberg/issues/34641
* https://github.com/WordPress/gutenberg/issues/57719

I'd recommend checking those out and continuing the conversation there. I'll close this issue as a duplicate

**Comment by davidperezgar** [comment]
Ok! I'll check them.

**Comment by mtias** [comment]
@davidperezgar this one is more relevant to your original comment: https://github.com/WordPress/gutenberg/issues/19909

**Comment by davidperezgar** [comment]
thanks @mtias I'll give my feedback
