### ISSUE TITLE
Non-query-able page taxonomy still shows up in the Page settings

### ISSUE THREAD

**Issue by rodelgc** [WordPress/gutenberg#60521]
### Description

This issue was discovered while testing https://github.com/woocommerce/woocommerce/pull/45781 

### Step-by-step reproduction instructions

1. Create a WP 6.5 test site through JN.
2. Install WooCommerce 8.7
3. Add the following code to the Theme Functions (functions.php) file. This code adds queryable and non-queryable taxonomies to Product and Page, respectively.
```php
function add_taxonomies() {
	register_taxonomy( 'queryable_product_taxonomy', array( 'product' ), array(
		'public'             => true,
		'publicly_queryable' => true,
		'show_in_rest' 		   => true,
		'label'              => 'Queryable Product Taxonomy',
	) );
	register_taxonomy( 'non_queryable_product_taxonomy', array( 'product' ), array(
		'public'             => true,
		'publicly_queryable' => false,
		'show_in_rest' 		   => true,
		'label'              => 'Non Queryable Product Taxonomy',
	) );
	register_taxonomy( 'queryable_page_taxonomy', array( 'page' ), array(
		'public'             => true,
		'publicly_queryable' => true,
		'show_in_rest' 		   => true,
		'label'              => 'Queryable Page Taxonomy',
	) );
	register_taxonomy( 'non_queryable_page_taxonomy', array( 'page' ), array(
		'public'             => true,
		'publicly_queryable' => false,
		'show_in_rest' 		   => true,
		'label'              => 'Non Queryable Page Taxonomy',
	) );
}
add_action( 'init', 'add_taxonomies' );
```
4. Create a new post via the Post editor.
2. Add a Product Collection block.
3. Click on the `Page` settings.
4. Notice that `Non Queryable Page Taxonomy` is shown, even though its `publicly_queryable` property was set to `false`

### Screenshots, screen recording, code snippet

<img width="666" alt="IoRPylJNM5" src="https://github.com/WordPress/gutenberg/assets/4509348/84115a09-a5f0-4d87-879d-cab8a1aa663d">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This issue was resolved by #59458. This is part of Gutenberg version 17.9 and is not shipped to WordPress 6.5. I would like to close this issue, but if I have missed anything please let me know.
