### ISSUE TITLE
FocalPointPicker: Convert unit tests to TypeScript

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#60529]
Convert the unit test files to `.tsx` so they are typechecked, and resolve any errors.

**Comment by alpha951** [comment]
Hey, could you please assign this issue to me.

**Comment by mirka** [comment]
@alpha951 Hi there 👋 Feel free to submit a PR, and it should assign you automatically once you link back to this issue, e.g. by writing `Fixes #60529` in the PR description. Ping `@WordPress/gutenberg-components` for review when it's ready!

**Comment by alpha951** [comment]
Hey @mirka , I've raised PR #60935. But seems like I couldn't tag @WordPress/gutenberg-components for review. Also the github checks are also failing.

**Comment by jpstevens** [comment]
Hey @mirka 👋  Can I get a review of this PR please? https://github.com/WordPress/gutenberg/pull/61373

All checks are passing **_except_** for the "enforce labels" check - as I don't have permission to assign one.

Thanks!

**Comment by mirka** [comment]
@jpstevens Thank you for the contribution! I've put this in our review queue 👍

**Comment by Mamaduka** [comment]
Resolved by #61373.
