### ISSUE TITLE
Background is different in zoomed out mode in Safari

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#60552]
### Description

In zoomed out mode the background colors in Safari are different to Chrome and Firefox when using the same theme. 

The following is chrome on left and safari on right with 2024 theme and no global styles set:

<img width="1575" alt="Screenshot 2024-04-08 at 4 06 23 PM" src="https://github.com/WordPress/gutenberg/assets/3629020/936f5dc1-857e-403f-a8cd-748867c5e647">

### Step-by-step reproduction instructions

- Enable zoomed out mode experiment
- In Chrome open an page in site editor and toggle zoomed out mode on and notice grey surround around the page
- In Chrome open an page in site editor and toggle zoomed out mode on and notice the surround is white

It looks like it is because of a difference in the way that Safari handles background colors on transform, ie. Safari applies the background color to the resized container, whereas Chrome and Firefox appear to leave the background color applied to the pre-transform size of the element. If the transform is removed and a manual margin applied the grey surround appears as expected:

<img width="1138" alt="Screenshot 2024-04-08 at 4 45 43 PM" src="https://github.com/WordPress/gutenberg/assets/3629020/a2c7cefc-9bfb-4ea0-80be-ea63d9a6337d">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Closing this out in favor of https://github.com/WordPress/gutenberg/issues/60601 which has more information and bugs.
