### ISSUE TITLE
Lists are not visible in the editor

### ISSUE THREAD

**Issue by Kuuuzya** [WordPress/gutenberg#60553]
### Description

![Снимок экрана 2024-04-08 в 09 10 41](https://github.com/WordPress/gutenberg/assets/1744587/9c904a50-a2de-4dcf-a947-9bdff5c9520f)

In several recent releases, it is impossible to work with lists in text if the sidebar is open. It's just not clear that the block is a list (and what kind). You have to either reduce the page scale or close the right panel (which is inconvenient)

![Снимок экрана 2024-04-08 в 09 13 41](https://github.com/WordPress/gutenberg/assets/1744587/ebf2b6fd-e933-4b4f-86a1-323f3a3d3d6d)
Here right panel is closed.

### Step-by-step reproduction instructions

1. Open New post
2. Create list
3. See the problem

### Screenshots, screen recording, code snippet

![Снимок экрана 2024-04-08 в 09 10 41](https://github.com/WordPress/gutenberg/assets/1744587/9c904a50-a2de-4dcf-a947-9bdff5c9520f)

### Environment info

- Wordpress 6.5
- Safari
- macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Hey there! I'm a bit confused as to what this issue is referring to. What theme are you using? It looks like the editor styles of the theme are causing the list block to be cut off as if I use TT4, I can't replicate with 6.5:
![Screenshot 2024-04-09 at 10 26 55 AM](https://github.com/WordPress/gutenberg/assets/26996883/4ce67d3d-e2b7-43e8-b438-2394a368e951)

**Comment by akasunil** [comment]
I cant replicate it either.

**Tested in :**

- Wordpress 6.5
- Safari
- macOS

![CleanShot 2024-04-17 at 17 34 35@2x](https://github.com/WordPress/gutenberg/assets/61308756/c8416838-4010-4893-a459-1b812fa5bbb0)

**Comment by Kuuuzya** [comment]
Sorry, it's really theme problem :(
If there any way to turn off it without using another theme, I would be very appreciated.

P.S. Option "Use theme style" in Editor is disabled

**Comment by colorful-tones** [comment]
> Sorry, it's really theme problem

@Kuuuzya I recommend reaching out to the theme author for support.

Closing this out since this is not a bug with the Gutenberg plugin
