### ISSUE TITLE
Incorrect copy-paste behavior in the header

### ISSUE THREAD

**Issue by Kuuuzya** [WordPress/gutenberg#60554]
### Description

If you copy a word in the title and try to paste it there, it will be pasted 3 times! And then 4 times and more. In addition, in 100% of cases, it is not the word that is copied, but the ENTIRE title. It is impossible to edit the title using basic functions (copy, cut, paste); you always have to write it manually or edit it character by character.

### Step-by-step reproduction instructions

1. Create a new post
2. Write any title
3. Select 1 word or several letters, press Ctrl+C
4. Go to the end of the title (or any other place) with the cursor and press Ctrl+V.

### Screenshots, screen recording, code snippet

![Снимок экрана 2024-04-08 в 09 22 33](https://github.com/WordPress/gutenberg/assets/1744587/a89340e7-eb1a-4779-bec2-63d8360333cd)

### Environment info

- Wordpress 6.5
- Safari on macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report. This problem looks similar to #51047.

Just to be sure, does this problem only occur in the Safari browser?

**Comment by Kuuuzya** [comment]
@t-hamano yes, it's definitely only in the Safari. Chrome is totally ok.
Found another side of problem. If you try to copy one word from Header to Tags, it would paste all the header, not only the word.

Safari 17.4 (19618.1.13.11.5)

**Comment by annezazu** [comment]
@ellatrix is this something you can look into? 

cc @tellthemachines for 6.5.x consideration.

**Comment by creativecoder** [comment]
Thanks for the report @Kuuuzya ! I'm going to close since it looks like we're already tracking this in https://github.com/WordPress/gutenberg/issues/51047
