### ISSUE TITLE
Can not insert multiple post "content" blocks within the full site editor

### ISSUE THREAD

**Issue by Simbaclaws** [WordPress/gutenberg#60566]
### Description

Whenever you put more then one "content" block within the full site editor, only the first content block is being shown.

I think this has to do with how the content block is meant to display information. Currently: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-content/edit.js

If you look at the following line of code:
```javascript
const hasAlreadyRendered = useHasRecursion( contextPostId );
```
This will check whether the content block has already been displayed within itself in order to prevent a infinite recursion.
But I think the way this is setup right now, is that it looks for the context post id, and when it exists on the template, it will only be rendered once, regardless of whether they are rendered inside of one another or not. So it's not checking for recursion, but rather is checking whether the template already has the content inside of it. (This is what I assume, I haven't done extensive testing yet)

This means that you can not have multiple content blocks inside of a template. Which in my particular case is necessary for my website...

I have a use-case where I've built a "desktop", "tablet" and "mobile" gutenberg block that can contain any block inside, and will only render content based on which device a user is using. In order to make this work, I would need to make it render the content block within all three of these blocks. But as it stands right now, this only gets rendered once in the first content block it encounters.

Is there any way I can circumvent the post content block from rendering only once on a template?

### Step-by-step reproduction instructions

1. go to the full site editor
2. place multiple "content" blocks within a template (without recursion)
3. Check out template in a frontend page that uses the template (making sure that the page has content)
4. Only see the content being rendered once.

### Screenshots, screen recording, code snippet

I think the problem lies within this file:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-content/edit.js

specifically the useHasRecursion function, which has a const of hasAlreadyRendered

### Environment info

- Wordpress version 6.5
- Gutenberg version 18.0.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Simbaclaws** [comment]
Perhaps it could also be that:

```javascript
<RecursionProvider uniqueId={ contextPostId }>
```

contextPostId should not be used as a uniqueId?

The docs show an example of how to use RecursionProvider:'
```javascript
/**
 * WordPress dependencies
 */
import {
	RecursionProvider,
	useHasRecursion,
	useBlockProps,
	Warning,
} from '@wordpress/block-editor';
import { __ } from '@wordpress/i18n';

export default function MyRecursiveBlockEdit( { attributes: { ref } } ) {
	const hasAlreadyRendered = useHasRecursion( ref );
	const blockProps = useBlockProps( {
		className: 'my-block__custom-class',
	} );

	if ( hasAlreadyRendered ) {
		return (
			<div { ...blockProps }>
				<Warning>
					{ __( 'Block cannot be rendered inside itself.' ) }
				</Warning>
			</div>
		);
	}

	return (
		<RecursionProvider uniqueId={ ref }>
			Block editing code here....
		</RecursionProvider>
	);
}

/// ...

<MyRecursiveBlockEdit />;
```


uniqueId:
Any value that acts as a unique identifier for a block instance.

I suppose the context post id should not be the unique identifier if you want to display content multiple times of the same post id from the same context.

**Comment by talldan** [comment]
I personally wasn't able to reproduce any problems with using multiple content blocks in a template. Here's what I end up with in the editor:
![Screenshot 2024-04-09 at 11 34 42 am](https://github.com/WordPress/gutenberg/assets/677833/98162147-2e3c-49c0-997a-dbe9986ff2b8)

and frontend:
![Screenshot 2024-04-09 at 11 35 09 am](https://github.com/WordPress/gutenberg/assets/677833/2e3e557e-7663-486d-983e-1fa98d04abd3)

@Simbaclaws Let me know if I'm misunderstanding anything. Maybe you're able to share a video screencap to demonstrate the issue?

**Comment by Simbaclaws** [comment]
Dear @talldan,

My apologies, I might've overlooked some plugin that I forgot to deactivate before testing with only the gutenberg plugin and wordpress activated.

I then started looking at the gutenberg source code and assumed it had to do something with the hasAlreadyRendered variable.

My suspicion is that one of the plugins I've programmed is causing my issue to appear. I'll do some more extensive testing on my side before replying with a screencap. I could've sworn I disabled all of the plugins before testing, odd.... Maybe it might've been a cache.

**Comment by fabiankaegy** [comment]
I was also not able to replicate this in my testing. 

@Simbaclaws for now I'm going to close this issue. If you do happen to find a way to replicate the issue you described feel free to reopen the issue at any point :)

**Comment by Simbaclaws** [comment]
Sorry for opening this once more. I just wanted to let everyone know that my issue has been resolved.

I found out that if you have a block above the content block that makes use of a WP_Query, that if you forget to reset the post data for that query, it will cause the content block underneath it not to render it's content. 
Apparently it had to do with which blocks were put before the content block that didn't correctly call
 ```php
wp_reset_postdata()
``` 
after creating a post loop.

Note to self: always clear your postdata after use.

I suppose it's intentional that you should clear your postdata before fetching new post data. And should not need some sort of workaround on the post content block (like putting a wp_reset_postdata() call at the top of the block)
