### ISSUE TITLE
Need Unique Class or ID for each Component Panel in Post Edit Panel

### ISSUE THREAD

**Issue by MikeB8s** [WordPress/gutenberg#6057]
Issue Overview

I see a need to differentiate the component panels in the post edit screens. 

In the classic editor, boxes for Categories and Tags are given unique IDs (category div and tagsdiv-post_tag), and custom taxonomies are given IDs such taxonomynamediv.

Adding IDs would allow easier access inside the component.  In my specific case, I use CSS to disable the parent category sections when adding new terms to a custom taxonomy. 

I think think this would ease the transition of some plugins from to Gutenberg where one might want to 

I am using the Gutenberg plugin version 2.6.0 on WordPress 4.9.5 with Genesis Sample theme.  

Steps to Reproduce
1. Open a post in Gutenberg
2. Select Document at top of side-bar.
3. Inspect the code for Categories and Tags.  I am using Chrome DevTools

Current Behavior
Both components are classed as components-panel__body with no ID

Expected Behavior
Unique IDs for each component-panel__body div to differentiate between them.

**Comment by MikeB8s** [comment]
Perhaps this issue could be addressed at the same time as: 
Taxonomy meta box title language #8449

**Comment by mtias** [comment]
We want to encourage the ecosystem to move away from using CSS selectors to achieve these kind of effects in favor of filters and slots, as they are a lot more robust and portable across platforms (like Mobile), which is going to be one of the targets of the editor in the coming months. Using ids as a way to disable features is going to quickly start falling apart for the developer, and would couple us with the DOM structure.

If you need help following the extensibility APIs described in https://wordpress.org/gutenberg/handbook/extensibility/ you may open issues as needed.

**Comment by MikeB8s** [comment]
I fully agree that filters and slots are the way to go.  For the time being, I have a workaround for Gutenburg.

In this specific case, the idea was to use the hierarchal custom taxonomy without the parent dropdown to display a list of checkboxes,  

The correct way to accomplish that would be a setting in the taxonomy parameters.  Because it would be neither hierarchal nor tags no parent dropdown would be needed.     I realize this is a special circumstance, but I have seen at least three questions online asking how to accomplish it.

I will suggest this over on wordpress.org/ideas and see if there is any interest.

**Comment by mtias** [comment]
That's great, and thanks for starting the conversation. I think it'd also be fine as a core ticket if you want to open one. Controlling things from configuration makes a lot more sense to me as something that'd scale better.
