### ISSUE TITLE
Demo image caption asking to do something that cannot be done

### ISSUE THREAD

**Issue by kriskorn** [WordPress/gutenberg#6058]
## Issue Overview

When you first install Gutenberg and go over the demo, then you will find under one image such a caption: "_Give it a try. Press the "wide" button on the image toolbar._".

Unfortunately, this cannot be done, as outlined here - https://wordpress.org/gutenberg/handbook/extensibility/theme-support/

## Steps to Reproduce 
1. Go to WP Admin -> Gutenberg -> Demo
2. Scroll to **A Picture is worth a Thousand Words**
3. Caption under the image will say: "Give it a try. Press the "wide" button on the image toolbar."

## Expected Behavior
Expected to see a **wide** button in the toolbar, when clicked on the image.

## Current Behavior
No wide button is shown, because it requires theme support.

## Possible Solution
Change the image caption to something different, so that it would not confuse people using Gutenberg the first time.

## Screenshots / Video
<img width="545" alt="wide-button-caption" src="https://user-images.githubusercontent.com/12064241/38453316-54e65ba2-3a5c-11e8-8991-3bca66926128.PNG">

Thank you!

**Comment by gziolo** [comment]
Fixed with #6061.
