### ISSUE TITLE
Feature Request: Empty Space Block

### ISSUE THREAD

**Issue by kriskorn** [WordPress/gutenberg#6059]
## Issue Overview

While testing out Gutenberg I found out that there currently is not an **Empty Space** block. I found the **Separator** block, but it does not exactly achieve the result that many users would like.

## Possible Solution

A new block called **Empty Space** with a variable height setting, so that users could define the empty space they need. 

This could be either added via blocks or it could automatically appear in the editor, when a new empty line is added, because on front-end empty paragraph tags are added. Gutenberg could automatically assign a class to these empty paragraphs. 

Here you can see the code that shows on the front-end, when empty lines are in the editor:

```
<div class="entry-content">
  <div class="wp-block-cover-image has-background-dim alignwide" style="background-image:url(https://cldup.com/Fz-ASbo2s3.jpg)">
  <p class="wp-block-cover-image-text">Of Mountains &amp; Printing Presses</p>
</div>

<p>The goal of this new editor is to make adding rich content to WordPress simple and enjoyable. This whole post is composed of <em>pieces of content</em>—somewhat similar to LEGO bricks—that you can move around and interact with. Move your cursor around and you’ll notice the different blocks light up with outlines and arrows. Press the arrows to reposition blocks quickly, without fearing about losing things in the process of copying and pasting.</p>

<p></p>

<p></p>

<p></p>

<p>What you are reading now is a <strong>text block</strong>, the most basic block of all. The text block has its own controls to be moved freely around the post…</p>

<p style="text-align:right">… like this one, which is right aligned.</p>

<p>Headings are separate blocks as well, which helps with the outline and organization of your content.</p>
```

## Screenshots / Video

<img width="498" alt="empty-space-block" src="https://user-images.githubusercontent.com/12064241/38453375-63935f14-3a5d-11e8-9eea-8579b611e98f.PNG">

**Comment by karmatosed** [comment]
This to me seems like something for the next version of Gutenberg where layout is considered. I can see concepts like guttering occuring there. I think having a blank block to do this is possibly the not so scalable approach. For now, you can achieve this using CSS and classes in your theme - I totally get this is an advanced concept for those that know CSS. Done just with a block I can see the issues this could create, it's about balance and totally something to consider later. Closing but putting into Customization project, thanks.

**Comment by spencerfinnell** [comment]
@kriskorn If you need an immediate solution: https://github.com/thatplugincompany/gutenkit-spacer-block

**Comment by kriskorn** [comment]
@spencerfinnell Thank you very much for this!

I was actually thinking of the normal everyday WordPress user. I would define such things in a theme and make sure that design is harmonious. However, everyday users who do not know CSS or create themes might like such a feature instead.

To be honest, I am not a big advocate of adding such a _spacer_ block, because this is a theme design territory and without it all the layouts would look much nicer. But having worked with a lot of WordPress themes and different users, I have realised that not everybody uses the software the same way. :)
