### ISSUE TITLE
Come up with a way to extract pattern-override code from the block-editor package

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#60619]
## What problem does this address?

Originally reported in https://github.com/WordPress/gutenberg/pull/60234#discussion_r1547201296.

Pattern Overrides is a WordPress-only feature. It would be nice to extract the logic and code from the block-editor package to maybe the `editor` package instead.

## What is your proposed solution?

I haven't figured out an elegant way yet but I have some ideas.

Since that we probably shouldn't have multiple menu items with the same label, maybe we can use the label as a key to override the existing ones. For instance, the block-editor package would implement the `Rename` menu item normally without the overrides warning, and we'll give it a `rename` key.

When we try to add a new menu item with the same `rename` key in the `editor` package, then it would simply override the existing ones. This will allow us to implement the warning message there, without leaking WordPress-specific logic to the block-editor package.

**Comment by kevin940726** [comment]
Another potential improvement is the pattern overrides toolbar indicator reported here: https://github.com/WordPress/gutenberg/pull/62317#discussion_r1631024218

**Comment by talldan** [comment]
Superceded by https://github.com/WordPress/gutenberg/issues/65486 (it proposes doing the opposite, and considering pattern overrides as a block editor first feature).
