### ISSUE TITLE
Warning: trying to access array offset (resolve-pattern.php)

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#60636]
### Description

Getting the following: 

Warning: Trying to access array offset on value of type null in /Users/bradhogan/Documents/Websites/mysite/app/public/wp-content/plugins/gutenberg/lib/compat/wordpress-6.6/resolve-patterns.php on line 26

### Step-by-step reproduction instructions

Install just the latest wp and gutenberg, add and activate a child theme (can be stripped down to include essentially nothing other than functions.php and stylesheet and blank theme.json), then view backend or go to edit a page.  

### Environment info

- wp 6.5.2
- gutenberg 18.1.0
- chrome
- mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for contributing, @bradhogan!

#60464 fixed this issue and will be part of the Gutenberg 18.2 release. I've also added a label for the fix to be included in a minor release if scheduled before a major one.

**Comment by bradhogan** [comment]
@Mamaduka Hey there.  Just noticed there was a minor release but this bug is still there.

**Comment by Mamaduka** [comment]
Sorry, @bradhogan. I wasn't involved in this minor release, and it looks like folks missed the PR.
