### ISSUE TITLE
Data views grid layout: Allow users to adjust grid density, and consumers to set default density

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#60630]
<img width="2125" alt="Grid density" src="https://github.com/WordPress/gutenberg/assets/846565/826942b5-8278-496b-b956-f5f45824c37b">

For some views the browsing experience in grid layout can be improved by adjusting the grid density, for instance viewing patterns in fewer columns so that previews are much larger.

It would be neat to allow consumers to specify a default grid density for views, and for users to customise that ad hoc.

**Comment by t-hamano** [comment]
It looks like you have already submitted a similar #60631 😄

**Comment by t-hamano** [comment]
It looks like you have already submitted a similar https://github.com/WordPress/gutenberg/issues/58462 😄

**Comment by jameskoster** [comment]
Haha, I thought I had but couldn't find it when searching. I'll keep this one open since it mentions allowing consumers to set the default which is important.

**Comment by colorful-tones** [comment]
Hi folks,
We are only one week away from the Beta 1 cut-off date for [WordPress 6.6](https://make.wordpress.org/core/6-6/). This issue hasn’t seen any movement in a while, so we (the editor triage leads of the 6.6 release) have decided to remove it from the [WordPress 6.6 Editor Tasks project board](https://github.com/orgs/WordPress/projects/179/views/1).
