### ISSUE TITLE
wp-utils console error in version 2.6

### ISSUE THREAD

**Issue by mattyrob** [WordPress/gutenberg#6063]
## Issue Overview

Since version 2.6 there is a console log error as follows: `ReferenceError: Can't find variable: wp`. This is related to a line injected as follows: `var originalUtils = wp.utils;` from the ./lib/client-assets.php file.

This is because, I think, that line added the code 'before' wp-utils exists. Amended line 100 of ./lib/client-assets.php to include and 'after' argument, instead of 'before' fixes this error.

## Steps to Reproduce (for bugs)

1. Install and activate Gutenberg 2.6
2. Open a page where Gutenberg is active
3. View the console log in your browser

## Expected Behavior

There should be no console error.

## Current Behavior

There is a console error.

## Possible Solution

Current line 100 of the ./lib/client-assets.php file is as follows:
`wp_add_inline_script( 'wp-utils', 'var originalUtils = wp.utils;', 'before' );`

Change is to the following fixes the error:
`wp_add_inline_script( 'wp-utils', 'var originalUtils = wp.utils;', 'after' );`
## Todos
- [ ] Tests
I have tested on my local install and the error resolves.
- [ ] Documentation

**Comment by xenobytezero** [comment]
Can confirm both the issue and the fix.
