### ISSUE TITLE
Separate Block Spacing in Row Block into Vertical and Horizontal Options

### ISSUE THREAD

**Issue by eric-michel** [WordPress/gutenberg#60643]
## What problem does this address?
The `Columns` block allows for block spacing to be set separately for vertical and horizontal axes. Since it's a `flex` container, this sets `row-gap` and `column-gap` separately.
![image](https://github.com/WordPress/gutenberg/assets/45110062/d1c1afee-ef7b-4499-b2ef-1c3ee7907f67)

The `Row` block does not allow this. It only allows for `Block Spacing` which just sets the `gap` property, with no flexibility to have different `row` and `column` gaps for when the `Row` block wraps.
![image](https://github.com/WordPress/gutenberg/assets/45110062/14402b1a-4e5e-4435-9e1b-8699a5bafc04)

## What is your proposed solution?
Follow the example of the `Columns` block and separate vertical from horizontal block spacing settings in the `Row` block.

**Comment by andrewserong** [comment]
Thanks for opening this issue, it's a good idea! One technical challenge to implementation is that the Row block is actually a variation of the Group block and there currently isn't a way to opt in for separate sides of gap for a particular variation / layout type. The standard Group block only has a vertical orientation, so wouldn't support separate sides.

So, we'd need some way to indicate "if this block is using flex layout type, expose both directions, otherwise just show a single control".

**Comment by eric-michel** [comment]
@andrewserong that totally makes sense! The default vs row variants of the Group block are so distinct that I often forget that they're the same block and not discrete ones.

I'm really excited for the `grid` variant of the Group block and just checked and see that it will have the same issue, so I do think this is worth making adjustments for! There are definitely a ton of applications for having separate `row-gap` and `column-gap` values.

**Comment by cbirdsong** [comment]
Has the idea of splitting these increasingly complex layouts option out of the group block been explored? It feels like moving all that into some sort of “layout container” block would allow the group block to return to being a nice basic tool. (Of course, you could still transform a group block into a layout block easily.)

**Comment by eric-michel** [comment]
It does seem odd that such disparate functionality is all folded into a single block using only variants to differentiate them. Paragraphs and Headings have a lot more in common with each other than a regular Group vs Grid block, yet they are separate blocks.

**Comment by carolinan** [comment]
Hi, I believe these two are duplicates? https://github.com/WordPress/gutenberg/issues/47084

**Comment by eric-michel** [comment]
@carolinan You are correct! I did not see #47084 when I first made this issue. Do you think I should close this one in favor of the other since it's older, or is it better to close the older one since this one has more recent comments and is linked to from #61453?

**Comment by Mamaduka** [comment]
Closing as duplicate of #47084.
