### ISSUE TITLE
Pullquote: Theme defined padding is overridden by default

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#60646]
### Description

The theme-defined padding values for the pull quote block are no longer working. They seem to be overridden by the default values. I've tested this with TT4, but it's not a theme-specific issue.

### Step-by-step reproduction instructions

1. Add a pull quote block in the editor.
2. Make sure the active theme has a custom padding.
3. See the block on the front of the site.
4. Notice the difference in the vertical paddings

### Screenshots, screen recording, code snippet

Gutenberg plugin inactive (expected) 👍
![CleanShot 2024-04-10 at 23 23 10@2x](https://github.com/WordPress/gutenberg/assets/908665/28301d0f-2762-448c-8956-d0cc806e7da3)

Gutenberg plugin active 😩
![CleanShot 2024-04-10 at 23 25 57@2x](https://github.com/WordPress/gutenberg/assets/908665/5e0e5d15-706b-4ca6-8e72-1b68dfe04ec3)

### Environment info

WP 6.5.2
Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
@tellthemachines is this related to the recent specificity reduction work? It looks like this rule has higher specificity than the global styles rules, so I'm wondering if it can be reduced, too 🤔:

https://github.com/WordPress/gutenberg/blob/d452cb429a259867d04dc6c94913fc642412eed9/packages/block-library/src/pullquote/style.scss#L2

**Comment by tellthemachines** [comment]
@andrewserong yes that would be a good one to try reducing! I think as a general rule, styles from block-library should have minimum specificity.

**Comment by andrewserong** [comment]
Great! I'll throw up a quick PR.
