### ISSUE TITLE
Unable to Activate Themes from Live Preview without Changes

### ISSUE THREAD

**Issue by okmttdhr** [WordPress/gutenberg#60650]
### Description

When attempting to activate a theme from the Live Preview within the site editor, the activation fails if there are no other changes in the editor. Clicking on "Activate {theme}" triggers the pre-save panel (implying that there are unsaved changes, even though no changes are listed). Subsequently, attempting to confirm the activation by clicking on “Activate” has no effect, with no console errors or network requests being generated to indicate a problem.

**Expected Behavior**: The theme should be activated successfully, reflecting immediately in the site's appearance.

**Actual Behavior**: The activation process does not proceed. The pre-save panel opens without listing any changes, and clicking on “Activate” does nothing. No errors are logged to the console, and no network requests are made.

### Step-by-step reproduction instructions

- Install a Block theme and navigate to the Live Preview by clicking `Live Preview` button
- Without making any other changes in the editor, click on `“Activate {theme}”`
- Observe the pre-save panel opening
- Click on “Activate” in the pre-save panel

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5287479/17b804f3-fcc7-4589-9db7-3a8f555f58eb

### Environment info

- Gutenberg > 18.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
I'm not too familiar with the changed parts of the code, but I'm wondering if https://github.com/WordPress/gutenberg/pull/60077 could have caused the regression? @ntsekouras I see the `EntitiesSavedStatesExtensible` component in that PR was updated to use `saveDirtyEntities` instead of `saveCheckedEntities`, so I'm wondering if that could have resulted in the activation button no longer working if the state otherwise has no changes in it?

**Comment by annezazu** [comment]
Just for triaging sake, noting that I can't replicate this with a clean 6.5.2 install (wanted to rule out a 6.5.x issue).

**Comment by ntsekouras** [comment]
Thanks for reporting! I'll take a look.
