### ISSUE TITLE
Replace "Syncing" term in the details of pattern

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/gutenberg#60657]
### Description

The term "Syncing" causes confusion.

### Step-by-step reproduction instructions

In WordPress 6.5:
1.Go to Appearence menu then Editor
2.Click on Patterns menu
3.Search after an editable pattern 
4.Click on the thumbnail of the pattern
5.Look at Details section in the left panel
6.See "Syncing" label.

### Screenshots, screen recording, code snippet

In the panel Details of a pattern in the site editor, there is the sync status of the current pattern with the term "Syncing" as label.
But this form with the suffix "ing" suggets that synchronization is in progress, and that's how it was translated into French "Synchronization in progress".
This is confusing, as there is no action in progress, as it is a status.

Why not use "Sync" or "Sync Status" instead?

![details-section](https://github.com/WordPress/gutenberg/assets/75045144/7a45fe97-bfdd-4163-a5be-4d6458b81996)

### Environment info

WP 6.5.2
Twenty Twenty-Four
No plugins

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Looks like this might be addressed by work in https://github.com/WordPress/gutenberg/issues/59689#issuecomment-1991723289. How does "Sync status" (as you suggest) work for you instead of "Syncing"?

**Comment by jennydupuy** [comment]
Yes "Sync status" is fine as I suggested in my ticket.

**Comment by karthick-murugan** [comment]
@jennydupuy - I think this issue is already addressed in the latest wordpress version.
