### ISSUE TITLE
TabPanel: Focus styles on `tabpanel` are wrong

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#60663]
The focus ring styles when a `tabpanel` is focused should match the one in `Tabs`.

## Actual

In the Storybook for `TabPanel`:

![Wrong focus styles](https://github.com/WordPress/gutenberg/assets/555336/a19dbcc4-f6a5-45f3-b4dc-1e88ba4d8b7e)

## Expected

In the Storybook for `Tabs`:

![Expected focus styles](https://github.com/WordPress/gutenberg/assets/555336/7854ca77-53b9-41f4-8c48-60541f929c29)

**Comment by alpha951** [comment]
Hey, could you please assign this issue to me?

**Comment by mirka** [comment]
@alpha951 Hi there 👋 Feel free to submit a PR, and it should assign you automatically once you link back to this issue, e.g. by writing `Fixes #60663` in the PR description. Ping `@WordPress/gutenberg-components` for review when it's ready!

**Comment by vipul0425** [comment]
@mirka I have raised the [PR](https://github.com/WordPress/gutenberg/pull/61317) to fix this issue.

Thanks.
