### ISSUE TITLE
Make block-cover-image more responsive

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#6066]
## Issue Overview

Default wp-block-cover-image styling is not optimally responsive.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Possible Solution

Change the default CSS to add:

```
.wp-block-cover-image {			/* make cover images display more responsively */
	background-position:	center center;
}
```

This works well, and looks significantly better when resizing browser.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
What exactly is the display issue you are experiencing right now on other devices?

**Comment by weavertheme** [comment]
Compare the following screen shots:

1. GB default cover-image styling in a wide browser
![default-wide](https://user-images.githubusercontent.com/2816397/39191964-50c5f596-4795-11e8-8214-d6d6a384ed23.jpg)

2. GB default cover-image styling in a narrower browser window
![default-narrow](https://user-images.githubusercontent.com/2816397/39191986-5c1e1e96-4795-11e8-972f-c8cac845d877.jpg)

3. using background-position: center center in a wide browser
![covdr-cover-wide](https://user-images.githubusercontent.com/2816397/39191999-6525d308-4795-11e8-8fd4-360e5705ea1c.jpg)

4. cover-cover in a narrower window
![cover-cover-narrow](https://user-images.githubusercontent.com/2816397/39192010-6b1c5dae-4795-11e8-95ff-2a99ec2673fd.jpg)


The look of the fixed bg image looks much better with center-center.

**Comment by danielbachhuber** [comment]
This seems like a reasonable improvement to me if someone would like to submit a pull request for it.
