### ISSUE TITLE
Support multiple `data-wp-on-window` or `data-wp-on-document` directive with the same event

### ISSUE THREAD

**Issue by DAreRodz** [WordPress/gutenberg#60683]
Currently, both `data-wp-on-window` and `data-wp-on-document` can't be used more than once on the same element and for the same event type. For example, the following code won't work, because browsers don't support duplicated attributes (`data-wp-on-window--click` in this case).

```html
<div
  data-wp-interactive="test/on-window"
  data-wp-context='{ "clickCount": 0, "isToggled": false }'
  data-wp-on-window--click="actions.countClick"
  data-wp-on-window--click="actions.toggle"
>Click me!</button>
```

To fix this, we could use a similar approach to the one in https://github.com/WordPress/gutenberg/pull/60661 for `data-wp-on`, i.e., allowing appending an ID to differentiate multiple directives with the same event.

**Comment by cbravobernal** [comment]
I'll take a look at this one.
