### ISSUE TITLE
Arbitary limit on alignwide width in editor

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#6068]
## Issue Overview

I am using a CSS rule to increase the width of the edit screen to 1100px or even more.
The built-in editor styling for alignwide seem to max out at 1100px. Why?

## Steps to Reproduce (for bugs)

1. Increase the editor width with:
```
.edit-post-visual-editor .editor-post-title,
.edit-post-visual-editor .editor-block-list__block {
	max-width:		1200px;
}
```

2. The default visual editor will limit the width of alignwide to 1100 px, so it ends up the same size as the normal block. There does not seem to be a limit on alignfull.

## Expected Behavior

Editor alignwide defult should be always be between standard width and alignfull.

## Possible Solution

Is there a good reason for this? 

Perhaps the CSS I've found for increasing the editor width is incorrect - likely I suppose. But there seems to be no good reason to limit the editor's width to 610px - it should support very wide screens if a theme has wide pages. You know - make it WYSIWYG as much as possible.

So I see three possible solutions:
1. Provide an "official" CSS rule to increase the display width, and make sure the default alignwide code allows align wide to get upto a few percent of that without making alignwide then the same as alignfull.
2. Simply remove the restriction of 1100px.
3. Let us know some CSS to adjust the alignwide layout.

Just a note: I've been working very hard the past few weeks to fully integrate Gutenberg into my theme - the goal is as close to WYSIWYG between the editor view and the final front-end view. I've gotten very very close so far. My theme allows user defined variable max-width, and I just can'f figure out how to get around the alignwide issue described here. I really believe forcing the theme to an arbitrary max-width in the editor window is extremely limiting. I can see from the way the blocks are bracketed in the edit window that it is not easy (or even possible?) to override the default alignwide or alignfull. That is just fine as long as the user sees 3 different widths - even if the window is set wider by the theme editor CSS. I don't know what you guys are using to test compatibiity between the editor code and a theme with both editor and front-end CSS, but since that what I'm really doing, it is possible that this particular issue has been overlooked.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mtias** [comment]
Glad you found a way around it. We have some further plans to improve the experience here down the road.
