### ISSUE TITLE
Move filter UI into a toggle-able panel to improve experience on narrow viewports/containers

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#60696]
![Filter panel](https://github.com/WordPress/gutenberg/assets/846565/2ff4d60d-60bd-43b8-a4df-926768b35cca)

Instead of permanently displaying filter controls and selections, we can place them in a toggle-able panel. This will allow users to selectively tidy up the interface which will prove particularly useful on narrow viewports (mobile) and containers (list layout).

We can be smart about when to show/hide the panel:

* Hidden by default across all layouts when no filters are applied
* Visible on load when the container is larger than X (Table / Grid layout), _and_ filters are applied
* Hidden on load when the container is smaller than X (List layout), even if filters are applied

<details><summary>Original issue</summary>In https://github.com/WordPress/gutenberg/issues/59696 the display of individual chips can be finessed. 

But we still need to figure out the display of many filters in narrow containers / viewports. It's not a huge problem right now because the existing data views only have <=2 filters. 

However, things like Posts or Media (https://github.com/WordPress/gutenberg/issues/55238) can have many filter options, and this experience isn't ideal:

<img width="406" alt="Screenshot 2024-04-12 at 10 12 11" src="https://github.com/WordPress/gutenberg/assets/846565/2d04c3b0-cc44-478a-bd8f-0eb961849086">

Let's explore how to better display many chips in the filter UI.</details>

**Comment by jameskoster** [comment]
The simplest thing to try here would be horizontal scrolling with a slightly different button appearance / layout:

https://github.com/WordPress/gutenberg/assets/846565/39c933f2-ef09-4d3c-955a-2aebc18a614d

* Add filter and Reset buttons fixed in position on the right
* Add filter and Reset become icon buttons
* Filter chips scroll horizontally

Some other things we might try to save space:

* Remove the inline `x` buttons 
* Reduce chip size and internal padding

There are usability trade-offs to this though, so perhaps worth looking at separately.

**Comment by jameskoster** [comment]
Another option would be to restrict display to _X_ number of chips, and hide the others behind a `+ x more` link:

<img width="1515" alt="Screenshot 2024-04-12 at 13 54 59" src="https://github.com/WordPress/gutenberg/assets/846565/4acaa15f-bae8-4fcd-a67e-efd23b13bdf8">

**Comment by jasmussen** [comment]
The horizontal scrolling is a common practice on mobile devices and scales well. If paired with the scrollbar mixin, it could work well and potentially be simple to implement, at least as a starting point.

**Comment by SaxonF** [comment]
Something else we tried early on is if on mobile or list view, condense filters down into dropdown.  We'd have an indicator "1" on filter icon. Relates a little to previous discussions about hiding view filters by default. 

![image](https://github.com/WordPress/gutenberg/assets/1072756/c7a380c1-3945-4d20-abb0-d4d00044fa4d)

**Comment by SaxonF** [comment]
Horizontal scrolling is also nice though and an improvement over what we have.

**Comment by jameskoster** [comment]
Containing all the filters in a single menu turned out to be a dead-end in terms of accessibility, but a similar approach might be to place filters in a dedicated panel, accessed by a toggle button.

![Filter panel](https://github.com/WordPress/gutenberg/assets/846565/2ff4d60d-60bd-43b8-a4df-926768b35cca)

We can be smart about when to show/hide the panel:

* Hidden by default across all layouts when no filters are applied
* Visible on load when the container is larger than X (Table / Grid layout), and filters are applied
* Hidden when the container is smaller than X (List layout), even if filters are applied
