### ISSUE TITLE
Patterns Page: Hide preview column by default 

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#60704]
## What problem does this address?

#60337 introduced the table layout on Pattern page. Currently, the pattern preview is displayed and cannot be hidden.

![image](https://github.com/WordPress/gutenberg/assets/54422211/92ce7522-2b86-42d1-9956-742154863b99)

## What is your proposed solution?

I suggest the following changes:

- Hide previews by default in the table layout.
- Can display a preview from the view options menu.

These two match the specifications of the current template page and template parts page.

![image](https://github.com/WordPress/gutenberg/assets/54422211/95269622-ef46-4898-babc-fc96bedb8c36)

**Comment by carolinan** [comment]
I agree it makes sense for the table layouts to match better, regardless of what type of item is being viewed.

**Comment by akasunil** [comment]
Hi @carolinan, I apologies for overlooking the "needs-decision" label. I noticed it after I created the PR.
