### ISSUE TITLE
Autocompleter (slash command) doesn't respect allowed_block_types

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#6070]
## Issue Overview
The blocks autocompleter (what you get when you type a /) doesn't respect the `allowed_block_types` filter.

## Steps to Reproduce (for bugs)
2. Add the following to the top of `lib/load.php`:  
  ```php
  add_filter( 'allowed_block_types', function() {
  	return [ 'core/paragraph', 'core/image', 'core/quote' ];
  } );
  ```
2. Create a post
3. Press /

## Expected Behavior
Only the Paragraph, Image and Quote bugs should appear in the dropdown.

Shared blocks should be properly filtered when using `allowed_block_types` filter.

## Current Behavior
All blocks should appear in the dropdown.

If you limit the blocks which can be shown using the allowed_block_types filter then shared blocks do not appear in the 'Shared' block inserter tab.

## Possible Solution
The [`getInserterItems`](https://github.com/WordPress/gutenberg/blob/master/editor/store/selectors.js#L1292) selector will correctly filter out non-allowed blocks if you pass the editor setting as its second argument.

## Screenshots / Video
<img width="262" alt="autocompleter bug" src="https://user-images.githubusercontent.com/612155/38480110-ea934a9c-3c06-11e8-8ac0-00d45c63c984.png">

## Related Issues and/or PRs
https://github.com/WordPress/gutenberg/issues/4225 https://github.com/WordPress/gutenberg/issues/3791 — both of these would also be fixed by the above suggested solution.

**Comment by paulwilde** [comment]
#5893 is also related. Probably of dupe actually.

**Comment by noisysocks** [comment]
Oops, sorry @paulwilde! 😄

**Comment by noisysocks** [comment]
I don't think it's a dupe. #5893 is referring to shared blocks not appearing in the inserter when `allowed_block_types` is set to `false`, whereas #6070 is referring to _all blocks_ mistakenly appearing in the / command regardless of what `allowed_block_types` is set to.

**Comment by jasonbahl** [comment]
#6363 seems related.

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/pull/6067 fixed this. 

<img width="371" alt="screen shot 2018-06-06 at 16 02 02" src="https://user-images.githubusercontent.com/612155/41019662-fb1e485c-69a2-11e8-9fc4-5b6e9f07a64a.png">
