### ISSUE TITLE
WP_Post_Type->template is not used in site editor

### ISSUE THREAD

**Issue by bacoords** [WordPress/gutenberg#60710]
### Description

The initial state of a new post type [is defined](https://core.trac.wordpress.org/browser/tags/6.5/src/wp-includes/class-wp-post-type.php#L287) in `WP_Post_Type->template`. This initial state is acknowledged by the block editor when creating a new post/page/etc but not in the site editor. 

### Step-by-step reproduction instructions

1. Register a [post type block template](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-templates/#api) for a post type that appears in the site editor. We'll use`page` (but you could use `wp_block`). Place this in a `functions.php` or plugin file:

```php
function myplugin_register_template() {
    $post_type_object = get_post_type_object( 'page' );
    $post_type_object->template = array(
        array( 'core/image' ),
    );
}
add_action( 'init', 'myplugin_register_template' );
```
2. Start a new page from the regular dashboard, which loads the block editor, and you'll see the initial block content (an image block) in the post content.
3. Start a new page from inside the site editor - you'll see that there is no initial block content.

### Environment info

- WordPress 6.5.2
- Gutenberg 18.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by colorful-tones** [comment]
I'm a bit confused about the expectations and testing steps here and how they correlate to a bug. 

Currently, I do not expect that I should be able to register a new custom post type, and be able to edit it in the Site Editor. This is not to say that there should never be considerations and planning to support custom post types in the Site Editor, and I would certainly expect it with the direction things are heading.

The referenced (Block) [Templates](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-templates/) handbook page also states the following:

> Planned additions:
> - Saved and assigned to pages as “page templates”.
> - Defined in a template.php file or pulled from a custom post type (wp_templates) that is site specific.
> - As the equivalent of the theme hierarchy.

Ultimately, I'm glad an issue captures this and it should be explored at some point.

**Comment by bacoords** [comment]
Thanks for looking! @colorful-tones I updated the instructions with a clear code snippet to make testing and the overall expectations more clear. This currently effects post types that already can be created in the site editor: `page` and `wp_block` (patterns),

**Comment by fabiankaegy** [comment]
I can replicate this 👍 This will be very important to fix before we ever support the creation/editing of other content types because the `template` field is much more used on custom post types
