### ISSUE TITLE
SKU not updating for old products having empty SKU

### ISSUE THREAD

**Issue by prasidhda** [WordPress/gutenberg#6071]
For newly added products, SKU is updating correctly. However for old product which has empty SKU but after trying to add the SKU, it is not saving the SKU value. 

Woocommerce Version: 3.3.4
WordPress Version: 4.9.5
Gutenberg Version: 2.6

**Comment by danielbachhuber** [comment]
Hi @prasidhda,

Thanks for the report. As follow up questions:

* Does this problem reproduce when Gutenberg is deactivated?
* Can you share a short GIF or screencast to visually communicate the problem?
* Do you see any JavaScript errors in your console? Is there other helpful detail you can share?

**Comment by prasidhda** [comment]
Disabling all other plugins except Woo commerce and Gutengerg solves the issue. I couldn't figure out which plugin was responsible since there were many testing plugins.

Keep doing awesome work. Good luck :)

**Comment by danielbachhuber** [comment]
Makes sense. If you track down the conflicting plugin, please do follow up with the plugin author.
