### ISSUE TITLE
Additional elements to the Editors in addition to PostTitle & BlockList

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#6072]
For a site I am working on I need to have subtitles. For this I normally use https://wordpress.org/plugins/subtitles/

I started looking into how to extend Gutenberg so to support an element between `<PostTitle />` and `<BlockList ... />`/`<PostTextEditor />` in both `VisualEditor` and `TextEditor` but I could not find a solution other then maybe override the two functions which would not be very good for future compatibility.

I don't think adding the field to the sidebar is a very user friendly way of solving the issue.

**Comment by gziolo** [comment]
@mtias or @karmatosed - is it something we have planned for the initial scope or rather for the customization phase?

**Comment by karmatosed** [comment]
I see potentially subhead block as a version one of this. It's actually how I've used it in my own examples. I don't see this being for version one though.

**Comment by grappler** [comment]
> I see potentially subhead block as a version one of this.
The issue with using the subhead block is that the subtile can't be queried separately if you want to display with the Title on the list of posts.

The temp solution for me will be creating a block which saves the subtitle to the metadata. But that will require the users to add a new block every time they want a subtitle.

**Comment by philiparthurmoore** [comment]
> The temp solution for me will be creating a block which saves the subtitle to the metadata. But that will require the users to add a new block every time they want a subtitle.

@grappler Subtitles REST API stuff will be shipped next week so I'll dig into this and see if there's anything we can do. Given the number of active installations of the plugin and consistent updates, I'd like to see if there's an elegant way of handling this even if Gutenburg itself isn't flexible right now. Will continue this in https://github.com/wecobble/Subtitles/issues/104 with you.

**Comment by karmatosed** [comment]
I am going to close this and put to the future milestone as it's something we may iterate on but not right now. Thanks everyone.
