### ISSUE TITLE
Fatal Error: Cannot redeclare function() in render.php

### ISSUE THREAD

**Issue by cb911nr** [WordPress/gutenberg#60759]
### Description

Created a custom dynamic block, it uses **render.php** and **ServerSideRender**

Inside **render.php** I have a custom function called **bookType()** that basically determines one of the attributes passed and then sets some html based on the attributes.

However, I keep getting an error of:

**Fatal error:** Cannot redeclare bookType() (previously declared in render.php:3) in render.php on line 3

Any ideas how to fix / avoid this problem? Assume something funky is going on, or I just don't quite understand. I need that function inside render.php to determine html to render, but I guess I could maybe pass the html as an attribute into render.php and do the calculation inside edit.js, but I would rather not.

### Step-by-step reproduction instructions

This is code based

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by fabiankaegy** [comment]
This is a fundamental limitation with what the `render.php` file is. The file, or rather whatever file you include via the `render` key in `block.json` gets used as the `render_callback` of a block. This render callback will be called multiple times during a WordPress render cycle. 

Because of this this file may not contain any function definitions. Or if it does contain them they need to be guarded with the `functions_exist` check before defining it.

A better option is moving the function definition into another file in the theme or plugin and then only calling it from within the render file

**Comment by cb911nr** [comment]
Thanks for that @fabiankaegy 

Hate to bother but considering my ignorance in this, how would I place that function somewhere to be used inside render.php correctly?

Right now it's a plugin, structure is the typical create-block structure with, so there's on main php file for the plugin that register_block_type everything, but when I put the function in here, render.php doesn't see it?

Assume placing it inside functions.php at the theme level would solve it but rather keep it at the plugin level.

**Comment by fabiankaegy** [comment]
The create block cli creates a main PHP file named after the project slug in the root of the plugin folder. This file contains the plugin header metadata and the `{{namespaceSnakeCase}}_{{slugSnakeCase}}_block_init` function. 

If you define your custom function there that should make it accessible in your `render.php`

**Comment by cb911nr** [comment]
Ah thank you that worked, I guess I had to enable / disable the plugin or something funky.

**Comment by johndavidsparrow** [comment]
> The create block cli creates a main PHP file named after the project slug in the root of the plugin folder. This file contains the plugin header metadata and the `{{namespaceSnakeCase}}_{{slugSnakeCase}}_block_init` function.
> 
> If you define your custom function there that should make it accessible in your `render.php`

Thank you for this, and for your detailed explanation. This just fixed an issue for me, and I'm really grateful!

**Comment by mrleemon** [comment]
Just a note: this limitation (that functions cannot be defined inside a block’s `render.php`) is not documented in the official Gutenberg documentation. This is a reasonable assumption for developers and discovering it only after running into fatal errors is frustrating.

Please consider documenting this clearly in the Gutenberg docs, along with recommended alternatives here:
https://developer.wordpress.org/block-editor/getting-started/fundamentals/static-dynamic-rendering/

Thanks in advance
