### ISSUE TITLE
Global Styles: Add block-level textAlign UI

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#60762]
## What problem does this address?

#59531 adds `textAlign` as block support. This allows developers to opt-in a dropdown for `textAlign` on the block toolbar via code like the following:

```json
{
	"$schema": "https://schemas.wp.org/trunk/block.json",
	"apiVersion": 3,
	"name": "core/test",
	"title": "Test",
	"supports": {
		"typography": {
			"textAlign": true
	}
}

```

Additionally, you can apply default styles to each block via theme.json.

```json
{
	"version": 2,
	"styles": {
		"blocks": {
			"core/media-text": {
				"typography": {
					"textAlign": "center"
				}
			}
		}
	}
}
```

However, there is no way to override the default style via the Global Styles UI.

## What is your proposed solution?

Add block-level global styles UI. One design idea is as follows.

![global-styles-text-align](https://github.com/WordPress/gutenberg/assets/54422211/59c62662-c23f-4b89-b39e-85a32b061b4e)

**Comment by t-hamano** [comment]
This UI will need to ship to WP6.6. See [this comment](https://github.com/WordPress/gutenberg/pull/59531#pullrequestreview-2000235999).

**Comment by colorful-tones** [comment]
@t-hamano I happened to notice you’re tackling some text-align stuff and I wonder if you think some of your work might solve https://github.com/WordPress/gutenberg/issues/60838 🤔 (perhaps it is even a duplicate issue?)

**Comment by t-hamano** [comment]
#60838 seems to suggest adding Justification controls that _already exist_ in the block toolbar.

I believe this is a separate issue since this issue is intended to add a _new_ text alignment UI.
