### ISSUE TITLE
Docs: Interactivity API - Shape a section in the docs providing a full response to the question "Why it's not possible to just use React?"

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#60783]
## What problem does this address?

As per the following [tweet](https://twitter.com/luisherranz/status/1780221484553670964) by @luisherranz 
> The "why can't we just use React?" question/complaint about the Interactivity API keeps coming.
> It's not immediately obvious and so far we've done a poor job explaining it so maybe we should create a new section in the docs called "Why it's not possible to just use React".

## What is your proposed solution?

Shape a section in the docs providing a full response to the question based on the explanations provided by @luisherranz in [tweet](https://twitter.com/luisherranz/status/1780221484553670964) and by @cbravobernal in [his tweet](https://twitter.com/cbravobernal/status/1778831734307524901).

**Comment by ndiego** [comment]
Great idea. Perhaps there could be an FAQ section to collect some of these common questions. 🤔 But either way, a nice paragraph explanation would be good.

**Comment by juanmaguitar** [comment]
>Perhaps there could be an FAQ section to collect some of these common questions.

Yes, I think a FAQ could be a good starting point.

**Comment by cbravobernal** [comment]
The proposal already included a great FAQ.
https://make.wordpress.org/core/2023/03/30/proposal-the-interactivity-api-a-better-developer-experience-in-building-interactive-blocks/#:~:text=it%20in%20Core).-,FAQ,-How%20does%20the

**Comment by juanmaguitar** [comment]
Closed as per https://github.com/WordPress/gutenberg/pull/61323
