### ISSUE TITLE
Docs: Interactivity API - Move docs from "Reference Guides > Package Reference > @wordpress/interactivity" to "Reference Guides > Interactivity API Reference"

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#60781]
## What problem does this address?
In order to escalate the docs around the Interactivity API we need a better location that makes more sense for developers using the docs. I think it would make perfect sense to put the "Interactivity API" at the same level than "SlotFills" or "Data Module" for example 

## What is your proposed solution?
Move docs from "Reference Guides > Package Reference > @wordpress/interactivity" to "**Reference Guides > Interactivity API Reference**". From there it will be easier to add a proper structure for further explanations and sections related to the Interactivity API (like [these ones](https://github.com/WordPress/gutenberg/issues/53296#issuecomment-1911915212) for example)

@ndiego @ryanwelcher @luisherranz @gziolo any thoughts?

**Comment by ndiego** [comment]
I definitely think it could use a more visible location, but what about other APIs? My only other reservation is how this move might impact the npm deployment. 

Another option could be to build out all the docs under `Reference Guides > Package Reference > @wordpress/interactivity` and just make this more discoverable. For example, we could rewrite the [Reference Guides](https://developer.wordpress.org/block-editor/reference-guides/) page (which is horrible) to highlight some featured APIs and reference info. I also think we need a How-to Guide on the IAPI.

**Comment by juanmaguitar** [comment]
> My only other reservation is how this move might impact the npm deployment.

Could you explain this a bit more? The README of the package could just provide an introduction to the package with links to where the documentation is

> Another option could be to build out all the docs under Reference Guides > Package Reference > @wordpress/interactivity and just make this more discoverable. For example, we could rewrite the [Reference Guides](https://developer.wordpress.org/block-editor/reference-guides/) page (which is horrible) to highlight some featured APIs and reference info.

Not 100% convinced, but it doesn't sound like a bad approach 😃 Yes, we need a plan for the "Reference Guides" secition!

**Comment by ndiego** [comment]
> Could you explain this a bit more? The README of the package could just provide an introduction to the package with links to where the documentation is

Ah gotcha, I thought you meant move the entire folder to `Reference Guides > Interactivity API Reference`. 

But yeah, I agree that the main docs for the IAPI should be in their own section in `Reference Guides > Interactivity API Reference`.

**Comment by juanmaguitar** [comment]
I close this issue as per https://github.com/WordPress/gutenberg/pull/61143
