### ISSUE TITLE
Gutenberg plugin v18.2, stable release April 24, 2024

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/gutenberg#60789]
This issue is to provide visibility on the progress of the release process of Gutenberg 18.2 and to centralize any conversations about it. The ultimate goal of this issue is to keep the reference of the steps, resources, work, and conversations about this release so it can be helpful for the next contributors releasing a new Gutenberg version.

-   Gutenberg version to release: 18.2 ([milestone](https://github.com/WordPress/gutenberg/milestone/229))
-   Release Manager (a.k.a. Release Lead): @colorful-tones 
-   Release Date 18.2 RC: Friday, April 19, 2024
-   Release Date 18.2: Wednesday, April 24, 2024
-   Previous version change log (as a reference): [18.1](https://github.com/WordPress/gutenberg/releases/tag/v18.1.0)
- Previous release post (as a reference): [What’s new in Gutenberg 18.1? (10 April)](https://make.wordpress.org/core/2024/04/10/whats-new-in-gutenberg-18-1-10-april/)]

## Resources

-   📖 Read: [Gutenberg Release Process](https://developer.wordpress.org/block-editor/contributors/code/release/)
-   📽 Watch: [Gutenberg Plugin: New Release Workflow](https://www.youtube.com/watch?v=TnSgJd3zpJY)
-   📽 Watch: [Creating the Gutenberg plugin v12.0 Release Candidate](https://www.youtube.com/watch?v=FLkLHKecxWg)
-   📽 Watch: [Gutenberg plugin v12.0.0 Release Party!](https://www.youtube.com/watch?v=4SDtpVPDsLc)

### RC Day - Friday, April 19

-   [ ] _Optional:_ Attend `#core-editor` meeting (14:00UTC)
-   [x] Post a message in `#core-editor` channel to let folks know you are starting the RC release process
    - [#core-editor message 1](https://wordpress.slack.com/archives/C02QB2JS7/p1713524726634509)
-   [x] Organize and Label PRs on the relevant milestone
    - [#core-editor message 2](https://wordpress.slack.com/archives/C02QB2JS7/p1713535571096739)
    - [#core-editor message 3](https://wordpress.slack.com/archives/C02QB2JS7/p1713538515436109)
-   [x] Start the release process by triggering the `rc` [workflow](https://developer.wordpress.org/block-editor/contributors/code/release/#running-workflow)
    - [#core-editor message 4](https://wordpress.slack.com/archives/C02QB2JS7/p1713543283128749)
    - [#core-editor message 5](https://wordpress.slack.com/archives/C02QB2JS7/p1713544419452999)
-   [x] [Update the created Draft Release accordingly](https://developer.wordpress.org/block-editor/contributors/code/release/#view-the-release-draft)
-   [x] [Curate the changelog](https://developer.wordpress.org/block-editor/contributors/code/release/#1-curating-the-changelog) before publishing
    - [#core-editor message 6](https://wordpress.slack.com/archives/C02QB2JS7/p1713545743502299)
-   [x] Publish Release
-   [x] Announce in `#core-editor` channel that RC1 has been released and is ready for testing
    - [#core-editor message 7](https://wordpress.slack.com/archives/C02QB2JS7/p1713551103440189)
-   [x] Ping any other relevant channels announcing that the RC is available
    - cross-posted to #outreach, #core-test, and #core
-   [x] Create Draft of Release post on Make Core blog _(initial draft in [Google doc](https://docs.google.com/document/d/1D-MTOCmL9eMlP9TDTXqlzuKVOg_ghCPm9_whHFViqMk/edit))_
    - [DRAFT – What's new in Gutenberg 18.2? (24 April)](https://docs.google.com/document/d/16e47EtT-6hDnmpbt7Q91k-5diiuvhIyw-VPmBfV7K7k/edit?usp=sharing)

### Between RC and Release

-   [x] Post a reminder in #core-editor for backporting PRs to RC (~Label Backport to Gutenberg RC)
    - [#core-editor Slack message](https://wordpress.slack.com/archives/C02QB2JS7/p1713964655402699)
-   [x] If there are any PRs marked as [Backport to RC](https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+label%3A%22Backport+to+Gutenberg+RC%22+is%3Aclosed), run the [cherry-pick command to apply them](https://developer.wordpress.org/block-editor/contributors/code/release/auto-cherry-picking/#how-can-i-use-it-for-a-gutenberg-plugin-release) to the release branch. **This needs to be run locally**
-   [x] [Draft Release Post Highlights and Change Log](https://docs.google.com/document/d/1D-MTOCmL9eMlP9TDTXqlzuKVOg_ghCPm9_whHFViqMk/edit)
-   [x] Get assets from [Design Team](https://make.wordpress.org/design/) for the post
    - [#design message](https://wordpress.slack.com/archives/C02S78ZAL/p1713892791763569) - I ended up creating the three videos myself with Joen's review.
-   [ ] Reach out to Highlight Authors to draft sections (if necessary)

### Release Day - Wednesday, April 24

-   [x] Post a message in `#core-editor` channel to let folks know you are starting the release process
-   [x] Start the release process by triggering the `stable` [workflow](https://developer.wordpress.org/block-editor/contributors/code/release/#running-workflow)
-   [x] Update the created Draft Release accordingly. Typically by copy/pasting the last RC release notes and add any changes/updates as needed.
-   [x] Publish Release
-   [x] Trigger the update to the plugin directory. _(Get approval from a member of [Gutenberg Release team](https://github.com/orgs/WordPress/teams/gutenberg-release/members) if necessary)_
    - [#core-editor Slack message](https://wordpress.slack.com/archives/C02QB2JS7/p1713986040051859)
-   [x] Announce in `#core-editor` channel that the plugin has been released
-   [x] Reach out to other contributors to help get the post reviewed
    - [#core-editor Slack message](https://wordpress.slack.com/archives/C02QB2JS7/p1713986040051859)
-   [x] Publish Release post on Make Core blog

**Comment by colorful-tones** [comment]
I have some questions around these items from the checklist above:

> Post a reminder in #core-editor for backporting PRs to RC (~Label Backport to Gutenberg RC)

How about: `Hi folks, please be sure to label anything that needs a Release Candidate Backport with the 'Backport to Gutenberg RC'. Thanks!`

> If there are any PRs marked as [Backport to RC](https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+label%3A%22Backport+to+Gutenberg+RC%22+is%3Aclosed), run the [cherry-pick command to apply them](https://developer.wordpress.org/block-editor/contributors/code/release/auto-cherry-picking/#how-can-i-use-it-for-a-gutenberg-plugin-release) to the release branch. **This needs to be run locally**

The expectation here is to probably check in daily to verify whether there are any PRs marked as [Backport to RC](https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+label%3A%22Backport+to+Gutenberg+RC%22+is%3Aclosed). If not, then carry on. Otherwise, run the [cherry-pick command to apply them](https://developer.wordpress.org/block-editor/contributors/code/release/auto-cherry-picking/#how-can-i-use-it-for-a-gutenberg-plugin-release) to the release branch. Correct?

**Comment by youknowriad** [comment]
> The expectation here is to probably check in daily to verify whether there are any PRs marked as [Backport to RC](https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+label%3A%22Backport+to+Gutenberg+RC%22+is%3Aclosed). If not, then carry on. Otherwise, run the [cherry-pick command to apply them](https://developer.wordpress.org/block-editor/contributors/code/release/auto-cherry-picking/#how-can-i-use-it-for-a-gutenberg-plugin-release) to the release branch. Correct?

I think the expectation is to check before the final/stable release, not daily.

**Comment by colorful-tones** [comment]
I'm still waiting for any [design assets](https://wordpress.slack.com/archives/C02S78ZAL/p1713892791763569), and I may be jumping ahead, but my draft for [What's new in Gutenberg 18.2 (24 April)](https://docs.google.com/document/d/16e47EtT-6hDnmpbt7Q91k-5diiuvhIyw-VPmBfV7K7k/edit?usp=sharing) is ready for an initial review. Would somebody mind taking a peek and 'Suggesting' any adjustments? 🙇  (also, posted same message in #core-editor)

**Comment by colorful-tones** [comment]
I'm going to circle back tomorrow morning and get the SVN tag issue resolved. Need somebody with SVN plugin credentials to square it away. Otherwise, Gutenberg 18.2 is out in the wild and officially released. 🥳

**Comment by colorful-tones** [comment]
Bernie Reiter was able to assist me in finalizing the SVN tagging issue. https://plugins.trac.wordpress.org/changeset/3077097

I'm closing this out as done.
