### ISSUE TITLE
Issue adding tags in Gutenberg when autocomplete reaches 20 item limit

### ISSUE THREAD

**Issue by keenode** [WordPress/gutenberg#60791]
### Issue Overview

When creating or editing a post, both the Gutenberg and Classic editors feature a “Tags” section that allows content editors to assign tags to an article. 

However, there is an issue regarding the autocomplete dropdown within Gutenberg with the way the core WordPress Gutenberg admin UI handles the creation or assignment of tags to posts. In the Classic editor, I noticed that the autocomplete dropdown did not have pagination. In the Gutenberg editor, however, it limits the maximum items returned in the dropdown to 20. Often times the suggestion that a content author is looking for falls outside of the paginated range of 20 items when tags contain the same word or similar words. 

The issue with this functionality is that if the user hits “Enter” to submit the tag and if it falls outside of the 20 items, the WordPress admin will assume that the tag is “new” and therefore attempts to “create” a new tag. If the tag already exists in the database, an error is returned that the user is unable to assign the new tag to the post. 

### Current Solution

My fix to this error, I temporarily updated a hardcoded value within the following file from Wordpress core:
media/wp-includes/js/dist/editor.js

By replacing *const* MAX_TERMS_SUGGESTIONS = 20; with *const* MAX_TERMS_SUGGESTIONS = 100; which therefore increases the pagination to get return 100 items (the maximum allowed by the API).

However, this solution does not completely solve it. The desired tag entry could still fall outside of the 100 items returned. The other problem is that we have to ensure our code changes don’t get overwritten by future updates to core Wordpress.

A related issue was reported here, although it was closed and not actually fixed. 
https://github.com/WordPress/gutenberg/issues/40850

I left a comment there and many others have, but it has not been addressed so I opened up this issue. 
Please let me know what can be done or if a fix will be in place so the admin can always check if a tag already exists in the database BEFORE attempting to create it as a new tag rather than associating it with the post (which is causing the error). 

### Step-by-step reproduction instructions

1. Create a new Wordpress site or add to an existing site. 
2. Add the following tags into the "Tags" section when creating a post:
amybug,bmybug,cmybug,aamybug,abmybug,acmybug,aaamybug,aabmybug,aacmybug,abamybug,abbmybug,abcmybug,acamybug,acbmybug,accmybug,bamybug,bbmybug,bcmybug,baamybug,babmybug,bacmybug,bbamybug,mybug
3. Notice an error that says "undefined" appears in the bottom left corner (see screenshot)
4. Unable to assign any tags to the post that contain the word "bug"

### Screenshots, screen recording, code snippet

![Screenshot 2024-04-16 at 11 46 02 AM](https://github.com/WordPress/gutenberg/assets/427374/fd8e7e68-0784-46cf-8831-81ad6806e149)
![Screenshot 2024-04-16 at 11 46 25 AM](https://github.com/WordPress/gutenberg/assets/427374/15aa3850-56ca-46c7-95e9-30b9dfed9a0d)
![Screenshot 2024-04-16 at 11 46 37 AM](https://github.com/WordPress/gutenberg/assets/427374/03c9dff2-5369-483a-aeb1-0d79f12078a1)

### Environment info

WordPress 6.4.2 on custom theme
Issue happens on all browsers / devices. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for creating a separate issue with reproduction steps, @keenode!

**Autocompleter limit:**
* The `MAX_TERMS_SUGGESTIONS` is a limit for fetched term suggestions. It doesn't affect how many tags you can assign or create for a post.
*  Queries without a limit (unbound queries) are generally expensive, which is why an arbitrary limit was introduced.

**Bad request error:**

This isn't actually a "bad" error. When the server responds with the `term_exists` error code, the editor knows how to use the error data and correctly assign the tag.

I tried reproducing the issue using WP 6.5; the editor assigned all 23 tags to my posts.

**Comment by Mamaduka** [comment]
@keenode, I started PR to update the max suggestions number to 100. You can find additional details in #62359.
