### ISSUE TITLE
Query Loop block not working in frontend

### ISSUE THREAD

**Issue by mayurprajapatii** [WordPress/gutenberg#60803]
### Description

Query Loop block display posts in backend & not showing posts in frontend 
it show the page name in which we put the query loop block

### Step-by-step reproduction instructions

1. Add new page
2. Add Query Loop Block
3. It will display posts & save the page
4. check in frontend none posts will display only current page will display

### Screenshots, screen recording, code snippet:

**Backend**:

![backend](https://github.com/WordPress/gutenberg/assets/91679132/7c60148d-7c47-4af4-9ed5-e4d14b80ec9d)

**Frontend**:

![frontend](https://github.com/WordPress/gutenberg/assets/91679132/f3abbbab-7e9b-44e1-9a17-8af212be2bb7)

### Environment info

PHP 8.0
WordPress 6.5.2 
Theme - Twenty Twenty one 2.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by fabiankaegy** [comment]
Hey @mayurprajapatii 👋 

By chance could it be that the Query block has the "Inherit query" option enabled in the sidebar?
