### ISSUE TITLE
Command Palette: Add data view shortcuts

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#60806]
<img width="3710" alt="command-palette" src="https://github.com/WordPress/gutenberg/assets/846565/17282643-b639-4f68-b8c2-0bd13662b5cf">

In the command palette it might be nice if searching for specific data views offered up shortucts to those views.

**Comment by t-hamano** [comment]
What is expected here is to have all the "categories" related to data views accessible via the command palette?

For example, items like:

- Templates > All templates
- Templates > {themeName}
- Pages > All Pages
- Pages > Published
- Pages > Draft
- Patterns > All template parts
- Patterns > Header
- Patterns > All patterns
- Patterns > My patterns
- Patterns > About

**Comment by jameskoster** [comment]
I think so, but now that I think about it there can be a lot of pattern categories. Searching for 'Pattern' could end up returning _a lot_ of results. 

Maybe an alternative would be to start by surfacing the "All $post_type" data views, with commands like "Manage pages", "Manage patterns", "Manage templates".

**Comment by t-hamano** [comment]
I think this topic is best discussed more comprehensively in #50407, so let me close this issue.
