### ISSUE TITLE
Question: How can we surface expected attributes of a block?

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#609]
__Problems:__

At a glance of a block's implementation, there is no easy way to know all attributes that the block uses and manipulates.

The block's `attributes` property allows an implementer to define which attributes are to be parsed from the saved markup of a post. This is not the only state that's available for a block, however, and the default behavior is such that in serializing a block, any attributes which do not have a corresponding key present in the `attributes` property are assumed to be encoded into the comment demarcations.

There are other issues related to this one, specifically ideas around defining an attribute as required, default values, or providing options for the block implementer to coerce an attribute value to a specific type. For the purpose of this issue, I'd like to keep this targeted at the discoverability worry.

__See also:__

- [Documentation](https://github.com/WordPress/gutenberg/tree/master/blocks#api) (out of date, also specifies an additional `encodeAttributes` function for granular control which has not yet been implemented)
- [Implementation](https://github.com/WordPress/gutenberg/blob/29462aadbc7ce229826dcbcdce280bb68045a4f3/blocks/api/parser.js#L31-L51)

__Ideas:__

- Perhaps the attributes property could behave more like [React's PropTypes](https://facebook.github.io/react/docs/typechecking-with-proptypes.html), defining all attributes which the block is expected to handle.
- Rather than implicitly assuming values whose keys are not in the `attributes` property are to be encoded in the comment, we could be more explicit.
  - A new `metadata( 'foo' )` matcher?
  - A separate property `encodedAttributes: string[]` ?
  - Require that `encodeAttributes` in the above documentation be implemented, so it's more obvious which values are encoded into the comment?

**Comment by youknowriad** [comment]
I like the ideas here. I'd see something like this would be great:

```
attributes: {
  content: children( 'p' ).string()
  style: metadata( 'style' ).int()
}
```

**Comment by aduth** [comment]
Similarly expressive, but maybe not quite as obvious, is [Lodash's `flow`](https://lodash.com/docs/4.17.4#flow):

```js
attributes: {
  style: flow( metadata( 'style' ), toInteger )
}
```

- [_.toInteger](https://lodash.com/docs/4.17.4#toInteger)
- [_.toNumber](https://lodash.com/docs/4.17.4#toNumber)
- [_.toString](https://lodash.com/docs/4.17.4#toString)

**Comment by aduth** [comment]
Another alternative is a more expanded object of attribute details:

```js
attributes: {
  style: {
    type: 'number',
    source: metadata( 'style' )
  }
}
```
