### ISSUE TITLE
LinkControl: refine the display of the link preview title and url

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#60900]
### Description

Normally, the LinkControl 'link preview' displayes two lines:
1. the `displayTitle`, which can be a few things:
  - the document title of the fetched 'rich data' of the link destination page
  - or, the entered link text
  - or, the entered link URL
2. The `displayURL` which is the link URL, with the protocol part stripped out.

When the rich data info can not be fetched, the 'title' is, normally, the linked text. Screenshot:

![normally](https://github.com/WordPress/gutenberg/assets/1682452/17d4038e-6e03-47c1-9847-6ee67c282015)

When the link text is the same as the `displayURL`, there is some logic in place to avoid to display two lines with the same identical information. That makes totally sense, and only one line is displayed. Screenshot:

![Screenshot 2024-04-19 at 14 03 49](https://github.com/WordPress/gutenberg/assets/1682452/07fd61d0-ab03-4a14-aba2-db1de3b0573f)

Without this logic, there would be two lines that would repeat the same, identical, information. Screenshot:

![otherwise](https://github.com/WordPress/gutenberg/assets/1682452/16cc1de9-c05d-4230-97ef-588df36da0d6)

So far, so good.

However, the logic in place doesn't take into account the case when the _link text_ contains the protocol. In this case, the preview displayes both lines and they contain the same information, the only difference is the displayed protocol. Screenshot:

![Screenshot 2024-04-19 at 14 04 09](https://github.com/WordPress/gutenberg/assets/1682452/fb90ebdc-1433-4d43-a298-55462b664e18)

Visually and semantically, in this case the repeated information is redundant. It would be best to show only the `displayTitle`.

### Step-by-step reproduction instructions

- Add a Paragraph that contains the text `test.org`.
- Select the text `test.org` and add a link to `test.org` without the protocol part. 
- Once the link is added, click the link in the Paragraph to open the link control preview.
- Observe the link preview displays only one line: `test.org`.
- Add a Paragraph with some text and paste `https://test.org` within the text. The pasted link should be automatically transformed to a link. If not, make sure to add a link to it with the value `https://test.org`. It doesn't matter whether the URL contains the protocol part.
- Once the link is added, click the link in the Paragraph to open the link control preview.
- Observe the link preview displays two lines: `https://test.org` and `test.org`.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by amitraj2203** [comment]
Hi @afercia, For this issue I have raised a [PR](https://github.com/WordPress/gutenberg/pull/61819).
I have added the logic to check weather the URL and text (after removing the protocol from the text) is same or not. If its the same then we are going to show only the `displayTitle`.
