### ISSUE TITLE
Provide hook during wp.blocks.registerCoreBlocks() function

### ISSUE THREAD

**Issue by elliotcondon** [WordPress/gutenberg#6092]
## Issue Overview
It is not possible to register a custom block type without forcing the Gutenberg assets to be enqueued early.

By default, Gutenberg assets are enqueued into the footer (which is good), but by following the documentation to [Write your first block type](https://wordpress.org/gutenberg/handbook/blocks/writing-your-first-block-type/), we are encouraged to enqueue our assets using the `wp_register_script()` function and use the `$deps` argument to require the gutenberg assets early.

To successfully register a Gutenberg block type, the `wp.blocks.registerBlockType()` function MUST be run AFTER Gutenberg has included it's JS and BEFORE the `wp.editPost.initializeEditor()` function is called.

The problem is that both of these events occur in the 'admin_footer' without an easy way to run code in between.

### Solution
A simple solution to this issue is to fire an action during the `registerCoreBlocks()` function: 
https://github.com/WordPress/gutenberg/blob/909d38dca5d48851ca93d0f26e47b851c6039257/blocks/library/index.js#L80

At the end of this function, adding something like the following would be great:
```
wp.hooks.doAction('registerCoreBlocks');
```

This way, we can hook in and register our blocks without touching the assets loading order.

**Comment by nerrad** [comment]
Some additional reasons/discussion supporting the request here have been articulated in #9757 so I'm going to close this issue in favor of continuing the discussion there.
