### ISSUE TITLE
Add possibility to add custom block alignments

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#60937]
## Add possibility to add custom block alignments

I would like to have a feature that my block can be constrained to content width (like it normally is for blocks), but also to fit content inside the block, in which case it may be smaller or bigger than standard sizes. Most logical place for me would be to add another custom alignment in [alignment control toolbar](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/block-alignment-control) which would have a label "fit block content" and custom icon

## What is your proposed solution?

Add some mechanism (possibly hook or slot) to enable adding custom alignment control.

**Comment by talldan** [comment]
There's an open issue for this (https://github.com/WordPress/gutenberg/issues/27629), so I'll close this one as a duplicate.
