### ISSUE TITLE
Creating/Updating templates for classic themes supporting custom block templates is gone.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#60946]
### Description

In Previous WP version (6.4), we used to be able to create custom block templates and edit them in the post editor in classic themes as well but in 6.5 it seems the "template" panel that allows that is now hidden.

### Step-by-step reproduction instructions

1- Use a classic theme like 2020 theme
2- Go the page editor
3- Notice that you can't create custom templates in the "template panel".

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by fabiankaegy** [comment]
This was discussed in the Make WordPress Slack here: https://wordpress.slack.com/archives/C02QB2JS7/p1713777608247919

The TLDR is:
- Any theme that has a `theme.json` file automatically gets `add_theme_support( 'block-templates' );` added
- In https://github.com/WordPress/gutenberg/blob/857cc267d50fb0bb180ee5803c0ef3cc13dfae3f/packages/editor/src/components/post-template/panel.js#L54-L60 we are checking for whether a theme is a block theme. Not whether it supports block templates.
- Changing this check to something similar to here: https://github.com/WordPress/wordpress-develop/blob/4f02bc74e6895370969f1ec79d27edede6cb054d/src/wp-admin/edit-form-blocks.php#L207 should resolve the issue

**Comment by creativecoder** [comment]
👋🏼 This issue is marked for a WP 6.5.x minor release. Just noting that the release candidate for the next minor release (WP 6.5.3) is [scheduled for May 2nd](https://make.wordpress.org/core/2024/04/15/wordpress-6-5-3-an-upcoming-maintenance-release/) (next week), so we'll need a fix before that date to include it in the release.

**Comment by youknowriad** [comment]
Actually, after some testing, this seems to be working as expected. 

 - 2020 theme doesn't have theme.json so the template mode is hidden.
 - Adding theme.json file enables it.

So I'm not entirely sure why I thought there was an issue here initially. Can you confirm @fabiankaegy ?

**Comment by fabiankaegy** [comment]
@youknowriad the `block-templates` theme support is completely decoupled from needing a `theme.json` file. So any classic theme even without a `theme.json` file can enable it. And that is where this issue appears

**Comment by youknowriad** [comment]
> @youknowriad the block-templates theme support is completely decoupled from needing a theme.json file. So any classic theme even without a theme.json file can enable it. And that is where this issue appears

Do you know any theme that does that. 

I tried using a classic theme 2020 and I added `add_theme_support( 'block-templates' )` and it did work for me (it appeared).

**Comment by fabiankaegy** [comment]
I just tried with `twentyfifteen` and adding `add_theme_support( 'block-templates' )` also makes it work as intended for me 🤔

**Comment by youknowriad** [comment]
Ok let's close this issue now until we get further feedback.
