### ISSUE TITLE
Textual Alternative - better interface to encourage more meaningful descriptions

### ISSUE THREAD

**Issue by edent** [WordPress/gutenberg#6095]
## Issue Overview

The "Textual Alternative" interface is a single line which only shows 31 characters of text.
If we want people to add meaningful `alt` text, this should be improved.
I suggest making it a `textarea` element.

## Steps to Reproduce (for bugs)

1. Add an image to a block
2. Try to add `alt` text.
3.  ![screenshot at 2018-04-10 09-36-18](https://user-images.githubusercontent.com/837136/38545755-af958544-3ca2-11e8-93a2-10bd55bd045b.png)
4. Only ~31 characters are shown. There is no way for the user to resize the control. They cannot see the full `alt` text.

Firefox 59.0.2, Ubuntu.

## Expected Behavior

This should be a `<textarea>` element. That will allow authors to see *all* of the alt text and give them enough space to provide decent textual alternatives.

## Possible Solution

I'm unfamiliar with the codebase, but I think...
https://github.com/WordPress/gutenberg/blob/f60517dd955de4e145e228808535b7590a4199e1/blocks/library/image/block.js#L206

Needs to become

```
<TextareaControl
	label={ __( 'Textual Alternative' ) }
	value={ alt }
	onChange={ this.updateAlt }
	help={ __( 'Describe the purpose of the image. Leave empty if the image is not a key part of the content.' ) }
/>
```
As per https://github.com/WordPress/gutenberg/blob/master/components/textarea-control/README.md

## Screenshots / Video

![textare](https://user-images.githubusercontent.com/837136/38546273-1927b922-3ca4-11e8-9050-289f71760e16.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @edent. I've flagged this as `Needs Design Feedback` to ensure there aren't any design concerns.

**Comment by karmatosed** [comment]
I think having this as a textarea would work well. Are there any guidelines on length for such a description though from an accessibility view @afercia?

**Comment by edent** [comment]
From https://www.w3.org/WAI/tutorials/images/tips/

> The <code>alt</code> text should be the most concise description possible of the image’s purpose. If anything more than a short phrase or sentence is needed, it would be better to use one of the long description methods discussed in <a href="../complex/">complex images</a>.

The current input doesn't have a `maxlength`, neither would a textarea.

**Comment by afercia** [comment]
@karmatosed what @edent pointed out is correct 🙂 

See also:
https://www.w3.org/TR/html52/semantics-embedded-content.html#general-guidelines
> NOTE:
> In cases where the text alternative is lengthy, more than a sentence or two, or would benefit from the use of structured markup, provide a brief description or label using the alt attribute, and an associated text alternative.

See also the examples 29 and 30 with complex images, where a perfectly valid textual alternative could be: `alt="Bar chart: average rainfall by Country and Season. Full description in Table below."` so yes, in some cases even the most concise description would need some more space. No objections to a textarea, seems a good improvement.

**Comment by karmatosed** [comment]
Ace, with that lets get this worked on, seems even a good possible first issue! Thanks all.
