### ISSUE TITLE
Update "Link Text" label to "Text" on Social Icons block

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#60966]
As a follow up to https://github.com/WordPress/gutenberg/pull/60047, let's update the "Link Text" label to just "Text", which maps consistently to all other link editing controls in the block editor. 

Except from original comment: https://github.com/WordPress/gutenberg/pull/60047#issuecomment-2059287693
> We should not be making inconsistent one-off changes based on much older iterations. I am always on the side of consistency, with a holistic approach to revising. We don't use "Link text" anywhere in the current WordPress editor.

### Visual 

Current: 

![CleanShot 2024-04-22 at 10 34 27](https://github.com/WordPress/gutenberg/assets/1813435/a695c117-8df6-426d-9185-f47045a668bd)

As seen in other blocks/UI: 

![CleanShot 2024-04-22 at 10 35 18](https://github.com/WordPress/gutenberg/assets/1813435/29903708-cf4c-48f9-8e40-d653bb853b2d)

![CleanShot 2024-04-22 at 10 35 55](https://github.com/WordPress/gutenberg/assets/1813435/feab7295-a5d0-4a3f-97dc-0da7d3261475)

**Comment by hbhalodia** [comment]
Hi @richtabor, I have raised the PR for the same - https://github.com/WordPress/gutenberg/pull/61715. Can you please have a look on this PR.

Thank You ✨.

**Comment by juanfra** [comment]
Closing as completed in https://github.com/WordPress/gutenberg/pull/61715
