### ISSUE TITLE
Invalid JSON Response and RESI API Issue

### ISSUE THREAD

**Issue by oryfoxer** [WordPress/gutenberg#60974]
### Description

We have a wordpress instance running on AWS using bitnami. We are currently running PHP 8.1.16, Wordpress 6.5.2.

The site was running fine, perhaps it updated, idk, but we started getting invalid JSON response when updating. Also, other features that seem to use the REST API do not appear to be functioning. 

I attempted recreating the .htaccess, resetting permissions per bitnami's support page (https://docs.bitnami.com/aws/how-to/troubleshoot-permission-issues/), changing permalink structure, while also increasing php values such as max_upload/max_input_vars/max_timeout.

We currently had child theme for divi, but I swiched to twenty-twenty and disabled all plugins to no avail.

![image](https://github.com/WordPress/gutenberg/assets/6994101/18045eb7-bf7a-4cc1-8ed0-93af84e4a539)

![image](https://github.com/WordPress/gutenberg/assets/6994101/b63183e2-8933-4bd6-93fd-94feb9c59e0d)

Here is the debug, "PHP Warning: Attempt to read property... 'null' "
https://pastebin.com/pxTLXDru

### Step-by-step reproduction instructions

Not sure, kinda just started, perhaps after an auto-update of wordpress.

### Environment info

PHP 8.1.16, Wordpress 6.5.2. AWS Bitnami

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

Looking at the error log, it appears to be similar to the issue reported in the core ticket below.

https://core.trac.wordpress.org/ticket/60909

**Comment by creativecoder** [comment]
Thanks for flagging this @t-hamano and connecting it to https://core.trac.wordpress.org/ticket/60909

This should be solved by these two PRs

- https://github.com/WordPress/wordpress-develop/pull/6420
- https://github.com/WordPress/gutenberg/pull/60925

**Comment by david-binda** [comment]
@creativecoder it seems like the `Gutenberg_REST_Templates_Controller_6_6` class is now overriding the `get_template_fallback` method (since 0e025fd ), but the method does not contain the patch which was submitted to the [WordPress](https://github.com/WordPress/wordpress-develop/pull/6420/). Shall we port it to Gutenberg as well?

**Comment by creativecoder** [comment]
Thanks for the reminder @david-binda ! I started that [here](https://github.com/WordPress/gutenberg/pull/60925), but need to update it to match the version that merged to core. Will do that today.

**Comment by david-binda** [comment]
Thanks! I was not entirely sure if the PR is meant to reflect the core or is a separate fix :)

**Comment by creativecoder** [comment]
https://github.com/WordPress/gutenberg/pull/60925 has how been updated to use the same approach from https://github.com/WordPress/wordpress-develop/pull/6420. Please review!
