### ISSUE TITLE
Only load Noto font in editor for compatible locales; use system serif otherwise

### ISSUE THREAD

**Issue by danstramer** [WordPress/gutenberg#6099]
Hi! about RTL and hebrew fonts in the editor. The currently used font is Noto Serif (called via the style-rtl.css file). The problem is that this font looks really outdated in hebrew. 
It's a bad looking Serif font, sort of like a font in the first days of the internet :slightly_smiling_face:

Is there an option to override the loaded font with a different font from Google fonts? I can suggest a few good options here.
Attached screenshot:
![image](https://user-images.githubusercontent.com/1552408/38560693-3751baf6-3ca4-11e8-8dca-cfa2f76bcea6.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
We've gone back and forth on this and this makes me feel we could go back to considering changing fonts. I don't think adding an option in for Google fonts is the solution. cc @jasmussen for your insights as this is a point we've gone back and forth on previously.

**Comment by danstramer** [comment]
I think that Noto could be the answer, but it's just not doing the adaptation to the locale font which is in use.
Maybe there is a way to connect the language of the WP install with the Noto font family and load those specimens for that specific language.
Noto Sans Hebrew
https://www.google.com/get/noto/

**Comment by jasmussen** [comment]
As a preface, Noto is currently used as part of the editor _base_ styles. If and when it becomes commonplace to load the theme stylesheet into the editor, it will obviously be up to the theme to define what's used here. 

As for Noto in the base stylesheet, I genuinely believe that writing content in the editor set in the Noto font is a better feeling. It feels considered, and styled, as opposed to what we'd get with Times New Roman ("unstyled") or Georgia ("plan B"). As such I would think the ideal solution is to load Noto for locales where we know the base offering works well, and fall back to other alternatives in cases like Hebrew. In other words, Noto for most languages, serif system font as fallback for other languages.

But it's also not a hill I would choose to die or even fight on :)

**Comment by karmatosed** [comment]
> As such I would think the ideal solution is to load Noto for locales where we know the base offering works well, and fall back to other alternatives in cases like Hebrew. In other words, Noto for most languages, serif system font as fallback for other languages.

I think then we have our way forward? Thanks all?

**Comment by danstramer** [comment]
There is a Noto locale font for Hebrew - 
https://www.google.com/get/noto/#sans-hebr
And I suggest using the "sans" font rather than the "serif" for Hebrew.

**Comment by danielbachhuber** [comment]
I've re-titled this issue to better reflect the proposed implementation:

> Only load Noto font in editor for compatible locales; use system serif otherwise

**Comment by mkaz** [comment]
Looking at picking this one up, and looking at the code shows:

```
	/*
	 * Translators: If there are characters in your language that are not supported
	 * by Noto Serif, translate this to 'off'. Do not translate into your own language.
	 */
	if ( 'off' !== _x( 'on', 'Noto Serif font: on or off', 'gutenberg' ) ) {
		$query_args = array(
			'family' => urlencode( 'Noto Serif:400,400i,700,700i' ),
		);

		$fonts_url = esc_url_raw( add_query_arg( $query_args, 'https://fonts.googleapis.com/css' ) );
	}
```

So isn't this already solved by setting the translation to off?
