### ISSUE TITLE
Data Views: Some notices display encoded characters

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#60995]
### Description

If I create a page through Appearance> Editor > Pages, Add new page, and use a symbol like & in the page title, the notice 
that is displayed in the editor shows the `&` as `&#038;`.

- It doesn't happen when I trash the same page from the data view.
- I saw the same thing happen when duplicating pages using https://github.com/WordPress/gutenberg/pull/60637,
- I think further testing of other notices would be good.

### Step-by-step reproduction instructions

Go to Appearance> Editor > Pages.
Select "Add new page"
Add a `&` to the page title, and create the draft.
Notice the content of the notice in the editor.

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/7422055/e6c1750d-f2a0-489e-9dea-79895c8162a9)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by marcarmengou** [comment]
## Reproduction Report
This report validates that the issue can be reproduced.

### Environment
- OS: Windows 10
- Web Server: Nginx
- PHP: 8.1.23
- WordPress: 6.5.3
- Browser: Chrome 125.0

### Actual Results
- ✅ Error condition occurs (reproduced).

### Additional Notes
- The coding error appears as indicated in this ticket. That if you delete the page the & character appears correctly in the tag, but when you create the page it gives a coding error. See attached image.

### Supplemental Artifacts
![png](https://github.com/WordPress/gutenberg/assets/83702259/96019970-341a-4457-9d51-f40ea681a970)

**Comment by carolinan** [comment]
Thank you for testing.

Fixing this is on hold for a little bit because the code is being moved, example: https://github.com/WordPress/gutenberg/pull/61879

**Comment by carolinan** [comment]
I will close this as completed, and if anyone finds more instances where the characters are not displaying correctly, new issues can be opened.
