### ISSUE TITLE
Inserter: Pattern tab visibility

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#61038]
## What problem does this address?
When there is no block selected the pattern tab doesn't show:

### Steps to reproduce.
1. Open the Site Editor.
1. Open the Inserter > Patterns > Any category.
1. Click on the canvas in Zoomed-out view.
1. Notice that the Insert isn't closed, and the Patterns tab is missing.
1. Toggle inserter.
1. Notice that Media tab is also missing

## What is your proposed solution?
I think the patterns tab should always be there but if you select a pattern and we don't know where it should go, we inform the user somehow.

**Comment by draganescu** [comment]
>  if you select a pattern and we don't know where it should go, we inform the user somehow.

A default result is better than an interruption, so always post at the start/end of sections list?

**Comment by scruffian** [comment]
We solved a connected issue in https://github.com/WordPress/gutenberg/pull/61002. However in that issue the problem was knowing which block to select when switching to zoomed out mode. This issue however is about what happens when blocks become deselected in zoomed out mode.

**Comment by richtabor** [comment]
Perhaps I'm misunderstanding, I'm not seeing this I think: 

![CleanShot 2024-05-01 at 10 49 28](https://github.com/WordPress/gutenberg/assets/1813435/512abc74-26c4-4097-b20c-72a7236641d2)

**Comment by scruffian** [comment]
This issue is different now - we do show the patterns tab but it says this:
<img width="1510" alt="Screenshot 2024-06-18 at 12 14 18" src="https://github.com/WordPress/gutenberg/assets/275961/a1d8874a-a3aa-44f6-80cf-b42c26babe95">

This is fine at the moment, but when we move to leaving the inserter always open I wonder if we'll need better messaging here?

**Comment by richtabor** [comment]
Is this still relevant? I'm seeing this here on trunk: 

https://github.com/user-attachments/assets/4e549ab2-55e1-47e3-9355-190b93cfa4d3

**Comment by scruffian** [comment]
Try selecting a button block:
<img width="2026" alt="Screenshot 2024-07-19 at 13 44 03" src="https://github.com/user-attachments/assets/365a5dd9-fe40-4a50-9de2-0a98a9729000">

**Comment by scruffian** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/61320
