### ISSUE TITLE
should viewScriptModule still be experimental in the scripts package? 

### ISSUE THREAD

**Issue by helgatheviking** [WordPress/gutenberg#61047]
Interactivity is now in core... should the `viewScriptModule` support still be hidden under an experimental flag?

**Comment by gziolo** [comment]
Can you clarify how it works exactly today and what would be the expected change?

**Comment by helgatheviking** [comment]
This is a very good example of something I should have put more explanation in to as today!Kathy doesn't really know what past!Kathy was talking about. Closing until I can remember what the point was :)
