### ISSUE TITLE
Block Editor: `BlockCanvas` component is exposed on both public/private

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#61041]
I noticed that `BlockCanvas` component is exposed on both public/private.

https://github.com/WordPress/gutenberg/blob/1f6fec6575ca4e9bcd64822b533df9f3057b9ba1/packages/block-editor/src/components/index.js#L19

https://github.com/WordPress/gutenberg/blob/1f6fec6575ca4e9bcd64822b533df9f3057b9ba1/packages/block-editor/src/private-apis.js#L47

In other words, we can use this component in either of the following ways:

```javascript
import { privateApis as blockEditorPrivateApis } from '@wordpress/block-editor';
import { unlock } from '../../lock-unlock';
const { ExperimentalBlockCanvas: BlockCanvas } = unlock( blockEditorPrivateApis );
```

```javascript
import { BlockCanvas } from '@wordpress/block-editor';
```
Private API may be deleted.

**Comment by andreiglingeanu** [comment]
I see in the `customize-widgets` package it is used as a private API. Should that be changed there too?

**Comment by t-hamano** [comment]
@andreiglingeanu Thanks for the reply.

If it makes sense to remove a private API, I think we need to replace it with a public API in any components that import it.

**Comment by t-hamano** [comment]
After looking deeper into this issue, I found that `BlockCanvas` and `ExperimentalBlockCanvas` are not exactly the same.

`BlockCanvas` is a wrapper component for `ExperimentalBlockCanvas`, but the `ExperimentalBlockCanvas` component can receive more props. See [this file](https://github.com/WordPress/gutenberg/blob/159d01a01b61ee76159ab67bc94d0d7cb3d90b35/packages/block-editor/src/components/block-canvas/index.js).

At this point, I don't think it's possible to integrate these two components, so I'd like to close this issue.
