### ISSUE TITLE
Enabling drop cap creates incorrectly flowed text

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#6105]
## Issue Overview
When enabling Drop Cap on a text block that flows around an aligned image block, the text doesn't reflow correctly.

## Steps to Reproduce (for bugs)
1. Insert an image block, place an image in it, and right-align the image.
2. Insert a paragraph block below it and place some text in it.
3. Enabled "Drop Cap" on the paragraph block.

## Expected Behavior
The drop cap appears correctly.

## Current Behavior
The drop cap appears correctly, but the rest of the text reflows into a non-wrapped appearance. The text stays like this until the cursor is placed back into the paragraph block.

## Screenshots
Before:

<img width="989" alt="" src="https://user-images.githubusercontent.com/208434/38572120-1f08987a-3cea-11e8-8fa8-ab6532c41fa7.png">

After:

<img width="984" alt="" src="https://user-images.githubusercontent.com/208434/38572132-24c89486-3cea-11e8-91d3-1dd8acecc257.png">

**Comment by AtrumGeost** [comment]
Hi there,

I tested this with Gutenberg 4.0 and wasn't able to reproduce the issue. It worked properly on my end:

![gh issue 6105](https://user-images.githubusercontent.com/3696121/47182094-4369fd80-d2ea-11e8-8e3a-6fa835b52866.gif)

_WordPress 4.9.8 and Gutenberg 4.0.0 using Google Chrome Version 69.0.3497.100 (Official Build) (64-bit) on macOS 10.14 - Mac OS Mojave_

**Comment by jorgefilipecosta** [comment]
Hi @johnbillion thank you for reporting this issue. I also tried to replicate this problem and like @AtrumGeost I was not able to do it, I think this issue may have been solved as a side effect of other change. If the problem is persisting in your tests feel free to reopen the issue and I will look further.
