### ISSUE TITLE
Typo - build/edit-site/index.js:23718

### ISSUE THREAD

**Issue by timse201** [WordPress/gutenberg#61052]
### Description

Rese to default and clear all customizations?

should be
Rese**t** to default and clear all customizations?

### Step-by-step reproduction instructions

located:
build/edit-site/index.js:23718

https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/de/default/?filters%5Boriginal_id%5D=17610382

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report. We need to fix this line:

https://github.com/WordPress/gutenberg/blob/6d444aa693c2504da5a2b9350c3ea55521cd1ae0/packages/edit-site/src/components/template-actions/index.js#L138

**Comment by talldan** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/61089
