### ISSUE TITLE
typo - build/editor/index.js

### ISSUE THREAD

**Issue by timse201** [WordPress/gutenberg#61053]
### Description
a unnecessary point at the end of the sentence.

You’ve tried to select a block that is part of a template, which may be used on other posts and pages. Would you like to edit the template?->**.**<-

### Step-by-step reproduction instructions

[build/editor/index.js:18925](https://plugins.trac.wordpress.org/browser/gutenberg/trunk/build/editor/index.js#L18925)
[build/editor/index.min.js:21083](https://plugins.trac.wordpress.org/browser/gutenberg/trunk/build/editor/index.min.js#L21083)

https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/de/default/?filters%5Boriginal_id%5D=17610391

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report. We need to fix this line:

https://github.com/WordPress/gutenberg/blob/6d444aa693c2504da5a2b9350c3ea55521cd1ae0/packages/editor/src/components/editor-canvas/edit-template-blocks-notification.js#L85
