### ISSUE TITLE
Uploading messages for media shouldn't stack

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#6106]
The following is what happens after a series of upload failures:

![audioerrormessagesstack-bug](https://user-images.githubusercontent.com/253067/38573018-b5c72856-3cec-11e8-9344-5f8e6bd4b2a9.png)

Ideally the messages shouldn't stack like this, the last one should stay and be replaced as you get another.

**Comment by mtias** [comment]
> Ideally the messages shouldn't stack like this, the last one should stay and be replaced as you get another.

Not sure about this. If you upload 10 files, and 3 fail, I'd like to see those three messages, otherwise I can't tell if only one failed.

**Comment by karmatosed** [comment]
I agree for multiple uploads, but what if you are just re-uploading because of errors one at a time?

**Comment by mtias** [comment]
I'd say that the moment you start the re-upload, that action should clear the previous error.

**Comment by karmatosed** [comment]
> I'd say that the moment you start the re-upload, that action should clear the previous error.

That would be great, in my testing this didn't happen.
