### ISSUE TITLE
Considering adding button links add from toolbar

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#6107]
We should consider unifying the adding of links to things like buttons with the new link interface.

![buttonlink-interface](https://user-images.githubusercontent.com/253067/38573076-e84b194a-3cec-11e8-9851-ce24b0b16de8.png)

Why don't we just have the link added from the toolbar?

**Comment by mtias** [comment]
We went this way because 1) the link applies to the whole block, it's not an inline link and 2) it's often the primary functionality of the Button block, not a secondary/formatting action.

**Comment by karmatosed** [comment]
I think in this case there is an argument to unify. With cover image having the same link interface, having another that does add a link is to me a good reason to consider.

![2018-04-10 at 20 55](https://user-images.githubusercontent.com/253067/38580330-94164e7a-3d01-11e8-8cd9-bd92299b8fe6.png)

**Comment by SuperGeniusZeb** [comment]
@karmatosed It should be noted that if the Cover Image block is changed to use nested blocks (like what is being done for quotes in #6054), the UI for adding links will likely change as it would probably just be using a nested Heading block by default.

**Comment by jasmussen** [comment]
The general intent behind this ticket seems right — let's simplify the ways a user can insert links, so they don't have to learn how to do it three ways:

- select text, make into a link
- click link button in block toolbar on image block to make entire image into a link
- paste link below button

Select text to make into a link obviously has to stay. 

In the case of both the Button block, and the Image block, these are sort of "atomic units" — there is no nested content in either of those, and there likely never will be. When made into links, they are both _links at the block level_, i.e. the entire thing is clickable.

Perhaps we unify those two? Perhaps we ditch the inline link style for the Button block, and add a block-level linking button to the block toolbar instead?

On the other hand, it's common enough to _not_ link an image, whereas a button is almost useless without a link, so it's good to pop it out inline, to make it super obvious.

**Comment by karmatosed** [comment]
Closing in favour of #6392
