### ISSUE TITLE
Add in text layout options for blocks with text that have formatting alignment

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#6108]
Right now we have 2 different sets of alignment icons:

- Image/layout (blocked)

![2018-04-10 at 19 25](https://user-images.githubusercontent.com/253067/38576088-018a9572-3cf5-11e8-8c5a-a7d7eeea5942.png)

- Text (lines)
![2018-04-10 at 19 24](https://user-images.githubusercontent.com/253067/38576066-f013a7e8-3cf4-11e8-96b5-b9d3c026cf38.png)

We seem to have a few cases that show the image/layout alignment when there is also text. For example in columns, pullquote and tables where it only applies to text, should we add text alignment to those?

![columnsonlyshowsthemealignment](https://user-images.githubusercontent.com/253067/38573417-ea2e0000-3ced-11e8-87f4-f62b6c02ee02.png)

Here is pullquote:

![pullquoteshouldhavetextalignmenticons](https://user-images.githubusercontent.com/253067/38573827-1bd8fbae-3cef-11e8-891c-c0a5c69a10d9.png)

Table:

![tablealignmenticons](https://user-images.githubusercontent.com/253067/38573836-251c5a1c-3cef-11e8-947a-06d0241cd00b.png)

**Comment by mtias** [comment]
Going to close as these layouts apply to the container in all the cases above.
