### ISSUE TITLE
Create Pattern Modal: Modal disappears when focus is moved with tab key

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#61081]
### Description

This problem seems to be occurring since WP6.4.

When creating a pattern from the editor canvas, if you press the tab key inside the modal, the modal will disappear when you leave the category.

Strangely, this problem does not occur in the Site Editor sidebar.

### Step-by-step reproduction instructions

- Insert some block
- Block Toolbar > Options > Create pattern
- Press the tab key continuously.
- The modal should disappear when the focus moves away from the category.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/0cd8b1b7-667d-4372-9adf-ecb6f805fbfe

### Environment info

- OS: Windows 11
- Browser: Chrome 23.0.6312.107, Firefox 125.0.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@t-hamano It's not something that I'm able to reproduce (Mac OS / Brave). I tried to follow the exact steps as in the video. Are you also experiencing this in the post editor with a new post?

**Comment by t-hamano** [comment]
Thank you for the testing. For some reason, I can't reproduce this problem anymore😅 It may have been a temporary problem, so I'd like to close this issue.

**Comment by talldan** [comment]
> Thank you for the testing. For some reason, I can't reproduce this problem anymore😅 It may have been a temporary problem, so I'd like to close this issue.

Part of me wondered if it might have been one of the blocks in the content capturing focus, but other than that, not sure why it would happen 🤔
