### ISSUE TITLE
Zoom-out can trigger double scrollbars in the editor canvas.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#61093]
### Description

Double scrollbars are visible in the editor canvas when you scroll while zoom-out mode is active.

### Step-by-step reproduction instructions

If you're on MacOS, make sure to have the "scrollbars always visible" setting active.

1- Enable the zoom-out mode experiment.
2- Go the site editor.
3- Edit the home page of 2024.
4- Trigger the zoom-out mode.
5- Notice that if you scroll in the canvas, you'll start seeing two scrollbars. And on Safari, they persist even after leaving zoom-out mode.

### Screenshots, screen recording, code snippet

<img width="1470" alt="Screenshot 2024-04-25 at 7 05 00 AM" src="https://github.com/WordPress/gutenberg/assets/272444/68e34d80-6f20-474f-bf52-9d51fab5c4ea">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mikachan** [comment]
I don't think this is related to zoom-out, or it's at least not only triggered by zoom-out mode, as I can reproduce this with the inserter as well:

<img width="1439" alt="image" src="https://github.com/WordPress/gutenberg/assets/1645628/3e055742-9c76-4be8-abd0-f2a2a4c98375">

<img width="1438" alt="image" src="https://github.com/WordPress/gutenberg/assets/1645628/9d60548d-950e-4053-bb96-59e1b231fea9">

The outer scrollbar is from a `NavigableRegion` with `interface-interface-skeleton__content` class. The inner scrollbar is from the editor canvas iframe. I would guess we want to prioritise the scrollbar from the iframe, as that should be the true height of the content we want to scroll.

**Comment by ntsekouras** [comment]
👋 - It would be great if you can test [this PR](https://github.com/WordPress/gutenberg/pull/61548) to see if it fixes the issue you're mentioning here, because I couldn't reproduce your use case, but I've found a double scrollbar issue.. Thanks!
