### ISSUE TITLE
Text columns has duplicated toolbar icons

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#6109]
In this block you can see the following extra toolbar icons:

![38573394-e2e9b0c8-3ced-11e8-983a-2d7bbe9d1cb1](https://user-images.githubusercontent.com/253067/38573631-9d82ed8c-3cee-11e8-844a-b9278f728032.png)

**Comment by SuperGeniusZeb** [comment]
Duplicate of #5633.

**Comment by karmatosed** [comment]
It is, however that one needs a better description to say what it really is, lets fix that!
