### ISSUE TITLE
Add eslint rule for lambda parameters

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#611]
Which should we prefer?

```js
const func = param => value;
```

or

```js
const func = ( param ) => value;
```

I personally prefer the first style, but either way I think we should codify this into a lint rule.

**Comment by aduth** [comment]
My vote would be toward the second, for consistency and ease of maintenance when adding additional arguments.

**Comment by BE-Webdesign** [comment]
I second aduth's statement, even though I usually use the top style.

**Comment by dmsnell** [comment]
My vote is for the first with @nylen, but can I also vote to allow either?

How about we just use Reason/OCaml? No more parentheses!
