### ISSUE TITLE
Add shuffling for header and footer template parts when zoomed out

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#61105]
Advances #50739

## What problem does this address?

#59251 introduced shuffling for patterns. We should have the same interaction available for template parts.

## What is your proposed solution?

Copy the interaction we have for patterns.

**Comment by draganescu** [comment]
The problem to deal with in this issue is similar to the one in #60203 - when we shuffle a template part, what should actually happen:

1. Replace the contents of the template part (keep the same post id) in the template
2. Replace the template part (change post id) in the template

**Comment by richtabor** [comment]
> when we shuffle a template part, what should actually happen:

I would expect my header to change throughout my site, wherever the corresponding template part is used.

**Comment by ntsekouras** [comment]
Since we are about to [remove](https://github.com/WordPress/gutenberg/issues/66105) `shuffle` with a list of suggestions to replace, should we close this one?

**Comment by draganescu** [comment]
Yes.
