### ISSUE TITLE
Media library filter defaults to a single letter

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#6111]
If you have nothing in your library you get the following:

![medialibrarydropdown-bug](https://user-images.githubusercontent.com/253067/38573796-079ea9f4-3cef-11e8-86cf-b5f4e4cc0147.png)

**Comment by Soean** [comment]
Maybe related to #2202

**Comment by karmatosed** [comment]
@Soean maybe, lets consolidate.
