### ISSUE TITLE
Improper Inserter block title text wrapping

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#61125]
The `word-break: break-all` applied to `.block-editor-block-types-list__item-title` is causing block titles to break mid-word. This is a regression from https://github.com/WordPress/gutenberg/pull/60890.

The words should be readable. 

### Visual 

![CleanShot 2024-04-25 at 18 00 10](https://github.com/WordPress/gutenberg/assets/1813435/30551a1c-f768-4993-94dc-fca188a66b87)

**Comment by richtabor** [comment]
Thoughts @afercia?

**Comment by afercia** [comment]
Hmm thanks for the ping @richtabor I noticed this yesterdya as well but didn't dive into it. 

I assumed the `Truncate` component was mainly used to truncate text _in one line_. I do realize it can be used also for text in multiple lines e.g. `<Truncate numberOfLines={ 3 }>`. Will look into it, thinking to add the break-all only when `numberOfLines` is 1 could work.
