### ISSUE TITLE
Navigation block - Allow collapsing on tablet (or custom) breakpoint

### ISSUE THREAD

**Issue by asafm7** [WordPress/gutenberg#61184]
## What problem does this address?
Often, a navigation menu is too big to be properly displayed on a tablet.

## What is your proposed solution?
Allow collapsing the navigation menu on tablet breakpoint (instead of just Mobile or Always). This is standard with other page builders, I think. If a tablet breakpoint isn't defined by Gutenberg, maybe a custom value may be introduced.
![image](https://github.com/WordPress/gutenberg/assets/14274769/d4aa044d-9fd2-49d8-8457-103b3e568ab1)

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/45040 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

**Comment by asafm7** [comment]
I searched before opening the issue but somehow missed it. Thanks.
