### ISSUE TITLE
Docs: View script module - Rephrase "In the future, it will be possible to depend on scripts from script modules" 

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#61191]
At [Block Editor Handbook > Reference Guides > Block API Reference > Metadata in block.json # View script module](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#view-script-module) it states

> WordPress scripts and WordPress script modules are not compatible at the moment. If frontend view assets depend on WordPress scripts, viewScript should be used. If they depend on WordPress script modules —the Interactivity API at this time— viewScriptModule should be used. In the future, it will be possible to depend on scripts from script modules.

In a conversation with @sirreal looking for a link to provide more context to the sentence `In the future, it will be possible to depend on scripts from script modules` he pointed out the Core Trac Ticket https://core.trac.wordpress.org/ticket/60647

The conversation on https://core.trac.wordpress.org/ticket/60647 seems to lean towards introducing modules progressively as needed, rather than migrating existing scripts entirely so the sentence `In the future, it will be possible to depend on scripts from script modules` may not be accurate at the moment.

Jon suggested replacing that sentence with something more in line with the [current plans for `viewScriptModule`](https://core.trac.wordpress.org/ticket/60647) such as:

> More functionality will gradually become available to Script Modules.

cc: @gziolo

**Comment by gziolo** [comment]
I would run all the changes to the docs through @sirreal as he is exploring some paths for adding support for interoperability between scripts and script modules. It might not be possible due to the design decisions that are discussed in the linked Trac ticket.

**Comment by juanmaguitar** [comment]
Closed as per https://github.com/WordPress/gutenberg/pull/61284
