### ISSUE TITLE
Add eslint rule for trailing commas

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#612]
Let's add a lint rule for trailing commas:

```js
const obj = {
    aubergine: 1,
    tomato: 2,
};

const arr = [
    'salmon',
    'shrimp',
];
```

There are several advantages to this.  From the [WordPress coding standards for PHP](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#indentation):

> Note the comma after the last array item: this is recommended because it makes it easier to change the order of the array, and makes for cleaner diffs when new items are added.

In the past, this has been avoided in JavaScript due to lack of support in older versions of IE (this [didn't work correctly until IE9](http://stackoverflow.com/a/19791620)).  However, we don't have to care about this because we have a build process to handle it for us and because [WordPress is dropping support for IE 8-10](https://make.wordpress.org/core/2017/04/23/target-browser-coverage/).

**Comment by ntwb** [comment]
Yes, I think we should do this, and update the coding standards whilst we're at it 👍 

Scattered throughout the JavaScript docs numerous times and to paraphrase quite heavily is:

> https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript
> These are for consistency between the PHP and JavaScript files in the WordPress codebase.

I've created an issue to also update this for `eslint-plugin-wordpress` / `eslint-config-wordpress`

**Comment by youknowriad** [comment]
There's too much places in Javascript where we need trailing commas and we tend to always forget them even if it's our way-to-go preference.

I understand the advantages here, but my preference would go for avoiding them.

Anyway, I prefer a strict rule one way or another.

**Comment by aduth** [comment]
This is one of those rules where I personally prefer without dangling commas, but find myself largely in the minority, so wouldn't fight strongly against them.

But I hope we all realize that for the sake of consistency, it doesn't just apply to...

```js
return [
  'nice',
  'simple',
  'keys',
];
```

...but also...

```js
return {
  not: {
    so: {
      simple: {
        keys: {},
      },
    },
  },
};
```
