### ISSUE TITLE
Block Editor Handbook not properly updated when two markdown files share the name (but not path)

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#61206]
After merging https://github.com/WordPress/gutenberg/pull/61143 for some reason the Quick Start Guide of the Intereactivity API meant to be at "Block Editor Handbook > Reference Guides > Interactivity API Reference > Quick Start Guide" (se [toc.json](https://github.com/WordPress/gutenberg/pull/61143/files#diff-be36db81bf5db2c87826f125630eaa4a6b513aa901208dc18a6395add0d6700e)) has been created at https://developer.wordpress.org/block-editor/getting-started/quick-start-guide/ (replacing the former one) and the url https://developer.wordpress.org/block-editor/reference-guides/interactivity-api/quick-start-guide/ redirects there

The PR https://github.com/WordPress/gutenberg/pull/61198 was created (and merged) to fix this specific update but the issue with the docs generation remains 

It seems the current system generates docs of the Block Editor Handbooks when two markdown files have the same name (even when they are in different paths)

This should be either fixed or a warning should be displayed when running `npm run docs:build` and related scripts

cc: @ryanwelcher @ndiego @oandregal

**Comment by ndiego** [comment]
> ... a warning should be displayed when running npm run docs:build and related scripts

I think this would be a good approach, but not sure how to technically set it up.

**Comment by oandregal** [comment]
Looking at the git history of the `manifest.json` file, this has happened in the past, see https://github.com/WordPress/gutenberg/pull/37505

IIRC, this is a limitation of the handbook setup: it creates pages for every entry present the `manifest.json` based on their slug, so it has to be unique. Back in the days, there was a `import-block-editor.php` in meta that did this job, but I can no longer find it. This ticket https://meta.trac.wordpress.org/ticket/5019 references that file.

I agree it'd be a nice improvement for the scripts to prevent you from committing if there's a repeated slug.

**Comment by juanmaguitar** [comment]
I have opened the PR https://github.com/WordPress/gutenberg/pull/61332 that launch an error in "build time" when duplicated slugs are detected

**Comment by juanmaguitar** [comment]
Closed as per https://github.com/WordPress/gutenberg/pull/61332
