### ISSUE TITLE
Only show color and typography variation control if alternate variations exist

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#61216]
https://github.com/WordPress/gutenberg/pull/59717 added a default color/typography variation. It works well, but one follow-up would be to only show the related UI if there are additional color/typography variations available. 

### Visual

In the visual below, there is a "Default" color variation, even though there are no other color variations provided by the theme. This entire "Presets" UI should only render if there are alternate variations available, for both colors and typography variations independently. 

![CleanShot 2024-04-29 at 15 23 24](https://github.com/WordPress/gutenberg/assets/1813435/e474aa1a-f988-4385-9d08-9d5253c7c913)

**Comment by hbhalodia** [comment]
Hi @richtabor, I can work on this one and would raise the PR soon.

Thank You.

**Comment by hbhalodia** [comment]
Hi @richtabor, I am unable to reproduce the issue again. If you remove the variations and reload the whole site, then you would not be able to see the `presets`. 

Can you please check at your end as well, if we are able to reproduce then I am happy to contribute to the PR.

Thank You.

**Comment by richtabor** [comment]
@hbhalodia 

Here's the Twenty Twenty Four theme, without any style variations (I removed them from the files). You'll see there's the default typography variation, and default color variation rendering. 

![CleanShot 2024-05-27 at 20 00 08](https://github.com/WordPress/gutenberg/assets/1813435/1c337709-a52f-4a38-9869-41876cc41fad)
