### ISSUE TITLE
Remove color styles from typography variation controls

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#61217]
Currently typography variations have the active theme’s styles applied to the controls.

Let’s instead not apply those colors, but only the typography styles—making these controls feel more integrated with the rest of the UI, potentially reducing confusion. These don't need the colors to communicate the typography values, and may be confused with full style variations (which do include color and typography styles).   

### Visual 

![CleanShot 2024-04-29 at 15 39 33](https://github.com/WordPress/gutenberg/assets/1813435/3c2730a0-e2ff-48f5-a749-3579f7a005ee)
![CleanShot 2024-04-29 at 15 41 58](https://github.com/WordPress/gutenberg/assets/1813435/35ed7c06-faa8-4464-a941-259b733a6949)

**Comment by hbhalodia** [comment]
Hello @richtabor, I just have a quick question here, We do have the typography options on the left side panel, while selecting the style's variation. Should also we remove the color from that as well, or should we keep the color to align it with the current style being added and just remove it from the typography section? Below is the screenshot I am talking about.

<img width="1431" alt="Screenshot 2024-05-01 at 4 47 12 PM" src="https://github.com/WordPress/gutenberg/assets/58802366/2e605e0f-986b-453b-8b95-af633ae4abea">

Although, I have raised the PR for the same - https://github.com/WordPress/gutenberg/pull/61280. This PR includes the color for the above issue mentioned, if we need to remove from that, I would update the PR.

Thank You.

**Comment by draganescu** [comment]
I would consider this a visual bug, not an enhancement. The styling make the actual variations less accessible.
