### ISSUE TITLE
Theme preview activation does not work after navigating in the previewing site editor

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#61239]
### Description

Live preview should allow users to customise a theme before activation. This feature is lost now as any navigation in the site editor that previews a theme removes the save button.

### Step-by-step reproduction instructions

1. Go to Appearance > Themes
2. On any of the installed and inactive block themes hover and click "Live preview"
3. On the Site editor that opens, click on _any_ of the sidebar items
4. **Notice bug**: the activate button disappears replaced w/ a "Saved" disabled button

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/107534/084a921f-bc07-4bf5-8058-d17e915806ae

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
I'm wondering if the changes in router could have caused this because the utils `isPreviewingTheme` and `currentlyPreviewingTheme` check the URL. Or maybe [this PR](https://github.com/WordPress/gutenberg/pull/60077). I'll take a look..

**Comment by ntsekouras** [comment]
It seems the changes in router that we strip the checked query params, are responsible for this. I'm not sure though if we should add complexity in router to preserve some specific params and others not. Could we preserve the info whether is previewing a theme (and what else is needed) in the store? 🤔 --cc @scruffian @jsnajdr

**Comment by draganescu** [comment]
Indeed I confirmed by reading #60466 and also resetting to before it.

@jsnajdr the way the sidebar now works with history discards any query string. Was that on purpose? The old `goTo` etc kept the query string around.

Also I think those query strings related to theme preview are a back compat issue.

**Comment by jsnajdr** [comment]
> the way the sidebar now works with history discards any query string. Was that on purpose?

Yes and no. I removed the behavior where query params are preserved during navigation, because that's not compatible with "mainstream" routing. URLs don't work like this. Going from `/foo?a=1` to `/foo?b=2` removes the `a` param. The destination is not `/foo?a=1&b=2`.

But I missed that it's breaking some features. We'll need to fix that. There is `wp_theme_preview`, and also `activeView` is not preserved when working with data views.
