### ISSUE TITLE
Data views: Add 'Edit' action to editable patterns

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#61245]
The Pages, Templates, and Template Parts data views make use of the edit post action for each item which produces the following UI:

 
<img width="1060" alt="Screenshot 2024-04-30 at 14 23 41" src="https://github.com/WordPress/gutenberg/assets/846565/9d8f06d9-d158-4445-935b-32a0d61995dc">
<img width="1055" alt="Screenshot 2024-04-30 at 14 23 26" src="https://github.com/WordPress/gutenberg/assets/846565/b9770f9e-50aa-4df0-8471-54026fafb122">
<img width="1062" alt="Screenshot 2024-04-30 at 14 23 09" src="https://github.com/WordPress/gutenberg/assets/846565/5556b809-967a-4c2d-bcb3-58484a387b96">

However, user generated patterns do not currently make use of this action, producing some inconsistency in the UX. Note the missing 'Edit' action in the ellipsis menu, and the missing pencil icon button:

<img width="1060" alt="Screenshot 2024-04-30 at 14 25 21" src="https://github.com/WordPress/gutenberg/assets/846565/d7be3abc-25a5-460b-b39b-d934a5ef0619">

We can improve overall consistency by adding this action to user generated pattern data views.

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster, it seems like this issue was fixed meanwhile. I'm going to close this issue as it seems working and code wise seems implemented. If things are not working on your tests feel free to reopen and I will debug what's happening.
