### ISSUE TITLE
Block toolbar is too small

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#61248]
### Description

When top toolbar is active it's always horizontally scrolling even if there is more than enough space for it to expand without scrolling.

### Step-by-step reproduction instructions

1. Visit the site editor
2. Set the top toolbar preference to on
3. Select a block - like an image block
4. **Notice the top toolbar is always scrolling**

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/107534/e7093db9-1fd2-4380-ae9e-fa3de53077d9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jeryj** [comment]
Was this fixed by https://github.com/WordPress/gutenberg/pull/61118?

**Comment by richtabor** [comment]
@draganescu does this still persist?

**Comment by draganescu** [comment]
Nope it has fixed itself 👍🏻
