### ISSUE TITLE
Remove font weight on toolbar tab button

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#61254]
After reviewing https://github.com/WordPress/gutenberg/pull/46834 I noticed the Edit and Preview controls in the HTML block's toolbar are set to 500 font weight ([source](https://github.com/WordPress/gutenberg/blob/0221522f253e094b277a1485b7a2d186cb172632/packages/components/src/toolbar/toolbar/style.scss#L94)), where all other text based toolbar controls are not (like the "Replace" button on Image block). 

I propose we remove the font weight applied to these, for consistency across toolbar controls:

![CleanShot 2024-04-30 at 10 14 50](https://github.com/WordPress/gutenberg/assets/1813435/e0d3011f-0f7a-4739-bf9c-e4a659704aeb)

**Comment by hbhalodia** [comment]
Hi @richtabor, I have raised the PR for the same - https://github.com/WordPress/gutenberg/pull/61308

Thank You.

**Comment by t-hamano** [comment]
Fixed by #61308
