### ISSUE TITLE
Template description: Card description breaks words poorly

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#61277]
The template description card breaks words using `word-break: break-all;`:

![poorly broken text](https://github.com/WordPress/gutenberg/assets/1204802/6d2e1cf1-2a89-4947-8523-cad647af382e)

This causes poor legibility. The rule appars to come from the Text component:

![code screenshot](https://github.com/WordPress/gutenberg/assets/1204802/7b0614da-3ad7-454c-b273-7e4160c731ae)

With very few exceptions should we break text like that. At best we can apply `break-word`.

**Comment by richtabor** [comment]
Yes, it's the same issue as https://github.com/WordPress/gutenberg/issues/61125.

**Comment by jasmussen** [comment]
Closing in favor of!
