### ISSUE TITLE
Template inspector: Double border on description card

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#61278]
In the site editor, the template tab, there's a description card towards the top.

This card has a double border above:

![double border](https://github.com/WordPress/gutenberg/assets/1204802/8b79475a-263c-484c-a057-71037371890b)

Between the tabs and the card, there should be only a 1px border.

**Comment by t-hamano** [comment]
I think this is a duplicate of #61055.

**Comment by jasmussen** [comment]
Ah! Thank you. Closing in favor of that.
