### ISSUE TITLE
Clarify multi-selection groups

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#6128]
![image](https://user-images.githubusercontent.com/548849/38640511-c4598632-3dd4-11e8-972f-65e90b30ffa0.png)

Consider showing how many blocks are selected in a multi-selection instance to help clarify that movers, etc, apply to all blocks.

Also, transform tools are confusingly placed at the top:

![image](https://user-images.githubusercontent.com/548849/38640700-4bdcfec2-3dd5-11e8-8e0c-21ad552a9c4f.png)

They should appear there only if the user has chosen to have a fixed toolbar, otherwise it should show by the blocks.

**Comment by karmatosed** [comment]
I like this and showing how many makes a lot of sense.

Side point, a thought buzzing around my head is maybe to only show transforms on ellipsis. I just am not sure they need to be in both places right now. If you had that by the block you'd be experiencing some visual complexity.

**Comment by SuperGeniusZeb** [comment]
Notably, it was decided to only show transforms in the block toolbar and not in the ellipsis menu, so showing the transform options in the ellipsis menu is no longer a good option since it would introduce an inconsistency, as well as not work with the upcoming redesign of the transform button to use a UI that resembles the block inserter.

**Comment by SuperGeniusZeb** [comment]
#7891 has moved the block toolbar to appear inline for a multiple block selection. Notably, it does not stay on-screen when you scroll down past the first block. See #7962.

**Comment by youknowriad** [comment]
Going to close this as the multi-selection UI changed and the switcher is by the block now while the number of blocks is shown in the sidebar
