### ISSUE TITLE
theme.json schema property points to a property that doesn't exist anymore

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#61282]
The `definitions > createTheme` property, of [`theme.json` schema](https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/theme.json) points to https://developer.wordpress.org/block-editor/how-to-guides/themes/create-block-theme/ which doesn't exist anymore

I suggest we update this property to point to  https://developer.wordpress.org/themes/ instead

**Comment by ramonjd** [comment]
Thanks for reporting! 

The alternative link is a good suggestion.

Fix here: https://github.com/WordPress/gutenberg/pull/61306
