### ISSUE TITLE
Site Editor > Pages: renaming shows old title in Inspector if you don't save

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#61292]
While testing GB 18.2 and some of the newer efforts, I noticed that if I rename the page via the page title, don't hit save, and then select the option to rename the page from the inspector, it shows the old title:

https://github.com/WordPress/gutenberg/assets/26996883/c99380d6-5bb7-402f-8d97-4b82ebd0721c

To replicate:

1. Create a new page in the site editor.
2. Edit the page title block and add a new title.
3. Don't save.
4. Select the three dot menu > rename in the Inspector.
5. Notice the old name is in place. 

cc @ntsekouras since you're working on this: https://github.com/WordPress/gutenberg/issues/59689

**Comment by ntsekouras** [comment]
The specific issue seems to have regressed from this PR: https://github.com/WordPress/gutenberg/pull/60752. This highlights though the issue whether we should pass the edited entity or the saved one in these actions. For example `duplicate post` action suffers from the same thing.

This is a decision for all the actions, as they are handled in a single component. I'd say that the edited entity makes more sense in general, but would love more thoughts. --cc @jorgefilipecosta 

Also noting that if we don't pass the edited entity this issue cannot be resolved.

**Comment by jorgefilipecosta** [comment]
Using the edited entity makes sense I will prepare a PR that uses the edited entity it should fix this issue.
