### ISSUE TITLE
Social Icons: Add Bluesky social icon

### ISSUE THREAD

**Issue by paulopmt1** [WordPress/gutenberg#61325]
## What problem does this address?

We'd love to have Bluesky's social icon available.

![image](https://github.com/WordPress/gutenberg/assets/1044309/f2ed020d-d601-4f1f-b107-b95cbb853dc1)

## What is your proposed solution?

- Add the Bluesky social icon [as we did for WhatsApp](https://github.com/WordPress/gutenberg/pull/42137).
- Be aware of its usage with different colors [as pointed here](https://github.com/WordPress/gutenberg/pull/42137#issuecomment-1230084478).

**Comment by amitraj2203** [comment]
Hi, [@paulopmt1](https://github.com/paulopmt1) I have raised a [PR](https://github.com/WordPress/gutenberg/pull/61372) to fix this issue. Let me know if it needs improvement.
Thanks!

**Comment by t-hamano** [comment]
Thanks for the report. I would like to close it because it is a duplicate of #61349.

**Comment by talldan** [comment]
It looks like the other issue is for the embed block and this one is for the social icons block.

Now that the other issue is closed I think it might be best to re-open this one, @amitraj2203 also has a PR open to solve this - #61372.

**Comment by t-hamano** [comment]
> It looks like the other issue is for the embed block and this one is for the social icons block.

Yes, I was confusing the two 😅 Thank you for reopening.

**Comment by jh20001** [comment]
Looks like the option to add Bluesky to the Social Sharing settings results in a blank (no) icon

**Comment by t-hamano** [comment]
@jh20001 Could you give us more details? I don't see any problems related to the icon in my environment.

**Comment by jh20001** [comment]
> [@jh20001](https://github.com/jh20001) Could you give us more details? I don't see any problems related to the icon in my environment.

Sorry, fell asleep soon after. My friend got it to work. Said it was a cache issue server-side, which I didn't think of as I was a bit tired (LONG day). I'm surprised the icon for Google News is still missing from the top social icon header section. Someone pointed that out already via the main site though, and that's a whole other topic. You have the option of setting what your link on Google News is in one section, but when it comes time to add it somewhere, it isn't listed as a checkable item. *shrug* (again, that's a whole diff issue though). :)

**Comment by sirreal** [comment]
There's a list of the available icons in the documentation here: https://wordpress.org/documentation/article/social-icons/

Bluesky is not mentioned. It would be great to update that.
