### ISSUE TITLE
Ensure pattern categories always render in the Inserter

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#61320]
## What problem does this address?
Since https://github.com/WordPress/gutenberg/pull/61108, there are several conditions under which the patterns tab doesn't display patterns:

1. There is no block selected
2. The theme removes support for core block patterns: `remove_theme_support( 'core-block-patterns' );`
3. The patterns haven't loaded yet.

In each of these cases we show this message in the patterns tab:

<img width="516" alt="Screenshot 2024-05-02 at 11 48 30" src="https://github.com/WordPress/gutenberg/assets/275961/617284c9-cc08-48aa-aa3a-0522d90afb9f">

## What is your proposed solution?
We should treat each of these situations differently:
1. We should still show the patterns and just insert them at the end of the content
2. We show a message to explain why
3. We show a loading placeholder

It would be useful to have designs for these states. cc @jasmussen @richtabor

**Comment by jasmussen** [comment]
This issue feels very reminiscent of #60991, enough that if we can do this:

> We should still show the patterns and just insert them at the end of the content

It would likely solve both. We might refine this to "nearest insertable location" rather than "at the end". But wouldn't that mainly be the case? And if we can solve this, do we need loading placeholders or messages?

**Comment by jasmussen** [comment]
CC: @jameskoster

**Comment by richtabor** [comment]
We could combine these into one no results found view:

![CleanShot 2024-05-02 at 09 16 33](https://github.com/WordPress/gutenberg/assets/1813435/46f255a8-165f-49ef-b30d-4b08ba984ce5)

![CleanShot 2024-05-02 at 09 16 39](https://github.com/WordPress/gutenberg/assets/1813435/5bf362a3-863c-4f28-9c4a-6ee02767fd57)

There's already a spinner used when pulling results from the block directory.; we could reuse that UX pattern:

![CleanShot 2024-05-02 at 09 17 29](https://github.com/WordPress/gutenberg/assets/1813435/359659af-1799-4b54-a563-c4f26b665f13)

As aside, but the Inserter should probably not render a "no results found" and a spinner at the same time.

**Comment by richtabor** [comment]
> The theme removes support for core block patterns: remove_theme_support( 'core-block-patterns' );

I removed the needs design label. I think it's fine if the pattern inserter says "No results found" when there are no patterns. 

Although if there are patterns insertable, you should see the pattern categories available. That we should resolve.

**Comment by jorgefilipecosta** [comment]
> Although if there are patterns insertable, you should see the pattern categories available. That we should resolve.

It seems like this is already fixed. When there is no block selected, we can still use the inserter and see the pattern categories, the pattern is inserted at the end of the post. 
The inserter already does not render a spinner and no results are found at the same time, if the patterns are loading only a spinner is rendered.

I'm going to close this issue, but I would appreciate if someone could double-check if I'm missing anything please feel free to reopen.
