### ISSUE TITLE
Focus ring doesn't match button Site Hub Icon size

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#61339]
### Description

The site icon in the header of the site editor has a smaller focus ring.

### Step-by-step reproduction instructions

1. Use the keyboard to move focus to the site hub button
2. The focus ring does not match the size of the site hub button

### Screenshots, screen recording, code snippet

<img width="172" alt="Open Navigation tooltip with focus ring about 8px inside of the edge of the site icon" src="https://github.com/WordPress/gutenberg/assets/967608/39d56411-611d-438e-9c32-0321ac65fe64">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by vipul0425** [comment]
@jeryj I have raised the [PR](https://github.com/WordPress/gutenberg/pull/61350) to fix this issue.

Thanks.

**Comment by kNoCoding** [comment]
so is the issue solved? should i try to fix it?

**Comment by jeryj** [comment]
We're needing design feedback on https://github.com/WordPress/gutenberg/pull/61350, as the focus ring is hard to see in the fix.

**Comment by karthick-murugan** [comment]
@jeryj I have raised this [PR](https://github.com/WordPress/gutenberg/pull/65936) to close this issue.
