### ISSUE TITLE
Add Bluesky embed block variation

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#61349]
## What problem does this address?

Bluesky has just been added as a trusted oEmbed provider in core.

See https://core.trac.wordpress.org/changeset/58091 and https://core.trac.wordpress.org/ticket/61020

The Bluesky logo SVG can be found at https://github.com/bluesky-social/social-app/blob/main/bskyembed/assets/logo.svg / https://github.com/bluesky-social/social-app/blob/cdf7a1957ad6a5bd569f60fb7113c44973f4e2d7/bskyembed/assets/logo.svg

## What is your proposed solution?

Add a new embed block variation for Bluesky embeds for 6.6+

**Comment by amitraj2203** [comment]
Hi, [@swissspidy ](https://github.com/swissspidy) I have raised a [PR](https://github.com/WordPress/gutenberg/pull/61352) to fix this issue. Let me know if it needs improvement.
Thanks!
