### ISSUE TITLE
Navigation block: browse all blocks auto closes without inserting anything

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#61361]
[Originally reported in #core-editor](https://wordpress.slack.com/archives/C02QB2JS7/p1714749597293399) by @talksina, there's a bug with the navigation block in Gutenberg 18.2 where, when trying to search to add additional blocks, the inserter disappears. cc @alexstine for tagging me to investigate.

**Steps to replicate**

1. Create a navigation block, no matter if in post, page or template.
2. Add a new menu item. "add block", the block inserter pops up.
3. Click on "browse all blocks"
4. Type a desired block name in the search field.
5. The inserter closes, without adding anything. 

I can replicate both with clicking and via keyboard navigation.

**Video**

https://github.com/WordPress/gutenberg/assets/26996883/e52effd7-2a41-4d2a-b65a-0a9874e750bc

**Environment**

GB 18.2, WP 6.5.2, TT4

**Comment by t-hamano** [comment]
Looking back at the commits, it appears that this problem occurred in #59925.

cc @jeryj @scruffian

**Comment by elettrona** [comment]
still persist in gutenberg 18.3.0.

**Comment by hagege** [comment]
... and unfortunately finally also in Gutenberg 18.4.0 🤷‍♂️

**Comment by jeryj** [comment]
Hopefully fixed by https://github.com/WordPress/gutenberg/pull/61975.
