### ISSUE TITLE
Distraction free: top toolbar broken in 18.2

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#61363]
While trying to use distraction free with 18.2 while previewing a theme, I noticed some really odd behavior. I could then replicate this while in the Site Editor itself:

https://github.com/WordPress/gutenberg/assets/26996883/748b9f9d-d21e-472a-b9cb-ec9372aa5626

Namely, the settings disappears so you can only toggle off with keyboard shortcuts and the top toolbar isn't visible. cc @draganescu

**Comment by draganescu** [comment]
It's a known issue tracked in #60875 by @youknowriad and @jeryj

**Comment by annezazu** [comment]
Ah! I didn't connect that. Closing out in favor of the other.
