### ISSUE TITLE
 "Warning: Parameter 2 to WPE\Site_Preview::the_posts() expected to be a reference, value given in C:\xampp\htdocs\theme-name\wp-includes\class-wp-hook.php on line 286"

### ISSUE THREAD

**Issue by emran-shaikh** [WordPress/gutenberg#6137]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
It looks like you are reporting an error specific to your site? In this case I am going to close this, however we can totally reopen if you can give a little more information such as what were you doing to get this? Could you please give some screenshots?

**Comment by henrywright** [comment]
I hit this warning today. It relates to a WP Engine plugin and how they are passing the `WP_Query` object to a `the_posts()` method. If you need it fixed you should contact WP Engine

**Comment by Knogobert** [comment]
Try deleting the files listed [here](https://wpengine.com/support/best-practices-uploading-wp-engine-site-another-environment/)

Worked great for me!
