### ISSUE TITLE
Refactor Interactivity Router API to TypeScript

### ISSUE THREAD

**Issue by abhi3315** [WordPress/gutenberg#61371]
## What problem does this address?
The current code of the interactivity-router package is written in JavaScript. It should be written in TypeScript.

## What is your proposed solution?
Refactor the files from JavaScript to TypeScript. There are following files that has to be refactored:
- index.js
- head.js

**Comment by cbravobernal** [comment]
Done in https://github.com/WordPress/gutenberg/pull/61730
