### ISSUE TITLE
Patterns: Unable to insert pattern in nested location

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#61381]
### Description

In the latest Gutenberg, when you try to insert a pattern from the main inserter, the root block to which the block belongs is focused, even if a nested block has focus before the insertion, so the pattern is always inserted at the root level. Masu. Therefore, if you want to insert a pattern in a nested location, you must insert the pattern at the root level and then move the pattern.

### Step-by-step reproduction instructions

- Select a nested block.
- Select a pattern category from the main inserter.
- The canvas will zoom out and the focus should now be on the root block to which the block belongs, not on the block you selected.
- When you insert a pattern, it should be inserted next to its root level.

Note: This issue reproduces in both the site editor and post editor. In the site editor, the canvas will zoom out when you select a pattern category from the main inserter.

### Expected (WP6.5)

The pattern is inserted immediately after the block that actually has focus.

https://github.com/WordPress/gutenberg/assets/54422211/ff625600-1808-4123-a2d1-bcec5896376d

### Actual (Latest Gutenberg)

Patterns are always inserted immediately after the root block.

https://github.com/WordPress/gutenberg/assets/54422211/f4ec7fde-bb00-46f0-9096-f7e1c8e50bee

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Hey @t-hamano I think this is intentional alongside the work with zoomed out view right now https://github.com/WordPress/gutenberg/issues/50739 as it focuses on adding patterns at the top level. This is something [that came up on the recent hallway hangout too.](https://make.wordpress.org/core/2024/04/25/summary-of-hallway-hangout-on-whats-next-in-gutenberg/)

>Q: By zooming out for the pattern view – does that mean that patterns aren’t still useful for smaller groups of blocks (i.e. wanting to add a CTA pattern to a column)?
>These patterns are still useful! This new option is simply offering a different context and allowing you to engage with patterns in a different way. This is also something to figure out how to do to provide a level to add patterns to a specific section.  

cc @richtabor and @scruffian who are working on zoomed out view.

**Comment by t-hamano** [comment]
I tested this issue again and got the following results:

- "Enable zoomed out view when patterns are browsed in the inserter" **disabled**: The pattern is always added after the selected block. 
- "Enable zoomed out view when patterns are browsed in the inserter" **enabled**: The pattern is always added at the root level.

From my understanding, both are correct behavior, so I'm closing this issue.
