### ISSUE TITLE
Block Bindings: Notify on save when users edit the value of a connected custom field instead of the post content

### ISSUE THREAD

**Issue by SantosGuillamot** [WordPress/gutenberg#61405]
This is part of a broader effort to improve the block bindings UI.

## What?

When saving a post, specify if it updates the post content or the value of the custom fields.

As part of the [block bindings project](https://github.com/WordPress/gutenberg/issues/60954), it is expected to allow the users to edit the value of the source connected to the block directly through the rich text. It was showcased in [this Gutenberg Hallway Hangout](https://youtu.be/JaZoPXu57-c?t=2386), and there is an ongoing PR for post meta [here](https://github.com/WordPress/gutenberg/pull/60725).

This means that if a paragraph's content is connected to a custom field, users will edit the value of the custom field instead of the post content. It'd be great to clarify that during the saving in the same way we do with other entities.

<img width="281" alt="Screenshot 2024-05-06 at 13 35 28" src="https://github.com/WordPress/gutenberg/assets/34552881/dc299b46-5bb4-4e80-8384-32aecf7403ef">

At first, I thought it was gonna work out of the box because it is actually using the proper `editEntityRecord` function: [link](https://github.com/WordPress/gutenberg/pull/60725/files#diff-cf4447b4134dbf24fa2819703999f0131449fb79a0611bd544c5e05fd80aa36bR34). However, in the end we are just editing the post entity, and it doesn't differentiate between editing the content or other parts like meta fields.

Would it make sense to specify which parts of the entity are being updated and, in case the meta fields are part of that, trigger the same "warning" as when we edit an external entity like in the previous example? Something like this but properly designed:

<img width="279" alt="Screenshot 2024-05-06 at 13 45 13" src="https://github.com/WordPress/gutenberg/assets/34552881/bbe81453-ab20-44c9-bc6c-f7d9d3a0d650">

**Comment by jasmussen** [comment]
If you change several global styles, we have a gray-colored bulletted list design already, that would work for this. To see this, go to global styles, change typography and colors, and see the save dialog. It should look like the column on the left in this screenshot:

<img width="1132" alt="Near term" src="https://github.com/WordPress/gutenberg/assets/1204802/c6f84e96-d7bf-4269-986c-77fd73a9099a">

The column on the right shows that same layout as applied to connected custom fields, listed out. 

The important piece here is to figure out: what should the text say? Should it say "Page content." and "Page meta." as suggested in this screenshot? Or should we be more explicit, such as "Page content." and "Custom field: meta."? Do we even apply the `code` styling to custom field names, or apply a color?

Longer term it'd be nice to add checkboxes to this list, so you could uncheck changes if they were made in error:

<img width="1132" alt="Longer term" src="https://github.com/WordPress/gutenberg/assets/1204802/52b34154-d759-4f6c-874f-940a344d93a5">

[Figma](https://www.figma.com/design/TthgbBWzOumVdK4ZtKe7pS/Multi-Entity-Saving?node-id=0%3A1&t=NHdPz8k7IGX7N3UK-1).

**Comment by artemiomorales** [comment]
> The important piece here is to figure out: what should the text say? Should it say "Page content." and "Page meta." as suggested in this screenshot? Or should we be more explicit, such as "Page content." and "Custom field: meta."? Do we even apply the code styling to custom field names, or apply a color?

It should be more granular and refer to the custom fields, right? I think it should even get more granular so that you can see all of the individual custom fields have been updated. I believe that's what I'd personally prefer to see, though I understand that would probably vary depending on how technical the user is.

**Comment by artemiomorales** [comment]
@jasmussen We have a very rough, [preliminary implementation going here](https://github.com/WordPress/gutenberg/pull/61811) in case you'd like to take a look.

**Comment by jasmussen** [comment]
Just connecting dots with a comment here, on a potential path forward: https://github.com/WordPress/gutenberg/pull/61560#issuecomment-2124272113

**Comment by gziolo** [comment]
Initial integration landed on Friday with https://github.com/WordPress/gutenberg/pull/61811. This is how it looks like in the post editor when other posts get modified, for example when using Query Loop block with Block Bindings defined in the post template:

<img width="1365" alt="Screenshot 2024-05-31 at 10 14 00" src="https://github.com/WordPress/gutenberg/assets/699132/c25ef49a-87fe-4e59-8b6e-a005d317eabf">

**Comment by SantosGuillamot** [comment]
The initial version of the save panel is already in `trunk`. Is it okay to close this issue and work on potential improvements, like showing the list of meta fields, on follow-up issues/PRs?

![Screenshot 2024-06-27 at 13 30 44](https://github.com/WordPress/gutenberg/assets/34552881/b00962d4-c0d6-47f2-95af-737284213368)

**Comment by artemiomorales** [comment]
> Is it okay to close this issue and work on potential improvements, like showing the list of meta fields, on follow-up issues/PRs?

New issue opened here: https://github.com/WordPress/gutenberg/issues/62938
