### ISSUE TITLE
Site editor related links are exposed to non-admin users

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#61419]
### Description

When generating a link to a page in the site editor, it is determined whether the site editor can be accessed, mainly through the following code, and the link destination is changed depending on the result.

https://github.com/WordPress/gutenberg/blob/771acf45c3ce5b76ffe529f8a0467d1fdc1c9359/packages/edit-post/src/components/header/more-menu/manage-patterns-menu-item.js#L11-L23

However, in the latest version of Gutenberg, `canUser( 'read', 'templates' )` returns `true` for non-administrator users, and they are now considered to have "access to the site editor." As a result, when you run the command, you will receive an error indicating that access is not possible.

### Step-by-step reproduction instructions

- Create a user with the Editor role and log in as that user.
- Open the post editor.
- When you start the command, you should see items like Styles, Templates, etc.
- If you click on those items, you should see an error.
- The "Manage all patterns" link should give you a similar error.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/6a8088ab-aa3a-46b2-83d2-8053324913b3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I think this issue is caused by #60317.

**Comment by bacoords** [comment]
Thanks for confirming as I was seeing this in my PRs. 

That said, I would also like to throw out the idea that if the ability for editors to read templates were determined not be a regression, perhaps the way we check for a user's ability to access the Site Editor could change. 

Perhaps outside the scope of this, but it could be cleaner if we had a core-data function that more closely corresponded to `current_user_can()` or something similar that we could directly pass user capabilities (i.e. 'edit_theme_options') to.

**Comment by fabiankaegy** [comment]
Great find. And yes that seems like my PR introduced this. I would say though that instead of changing the access levels back the way to fix this is using the `canUser( 'create', 'templates' )` check.
