### ISSUE TITLE
Group blocks override theme's list indentation

### ISSUE THREAD

**Issue by gabbsmo** [WordPress/gutenberg#61431]
### Description

If I put a list in a group block, it will not be indented the same way as it was outside. I think this is a regression in WP 6.5 as I do not have this problem in sites still running WP 6.4.

### Step-by-step reproduction instructions

1. Add a group block
2. Add a ordered or unorded list inside it
3. Publish
4. Notice that the list is not indented

### Screenshots, screen recording, code snippet

Theme style:
```
ol, ul {
    margin: 0 0 1.5em 3em;
}
```

Style in WP 6.5 that override the theme:
```
body .is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
    max-width: var(--wp--style--global--content-size);
    margin-left: auto !important;
    margin-right: auto !important;
}
```

### Environment info

WordPress 6.5
Theme: GeneratePress

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by marcarmengou** [comment]
## Reproduction Report
This report validates that the issue can be reproduced.

### Environment
- OS: Windows 10
- Web Server: Nginx
- PHP: 8.1.23
- WordPress: 6.5.3
- Browser: Chrome 125.0
- Theme: GeneratePress, Twenty Twenty-Three and Twenty Twenty-Four

### Actual Results
- ❌ Only seems to be related to GeneratePress.

### Additional Notes
- Indeed what is said in this ticket happens, but only in the GeneratePress theme. In Twenty Twenty-Three and Twenty Twenty-Four the list appears correctly indented.

### Supplemental Artifacts
In the images are two lists. The upper one is free. The lower list is inside a Group Block.

#### GeneratePress
![1](https://github.com/WordPress/gutenberg/assets/83702259/2f22413d-5d27-4bb7-8ae5-d7cdf9c02615)


#### Twenty Twenty-Three
![2](https://github.com/WordPress/gutenberg/assets/83702259/fc480ad7-914e-4688-a4ed-366cfd7508ef)


#### Twenty Twenty-Four
![3](https://github.com/WordPress/gutenberg/assets/83702259/233e8e6b-823b-4009-97b0-2c509408b54a)

#### Editor
![4](https://github.com/WordPress/gutenberg/assets/83702259/3490a918-dde7-4647-95da-40cbb2044648)

**Comment by gabbsmo** [comment]
Thanks for confirming. Can it still be fixed on the WordPress side? I can imagine that this breaks list blocks in many themes and the WordPress style is hard for theme developers to override since the selector is very specific and is using `important!`.

**Comment by marcarmengou** [comment]
I tried to check if other themes not developed by WordPress had the same problem.

I went to the WordPress theme directory and selected the most popular ones, such as Astra, Kadence, Blocksy, Neve, OceanWP, Kubio and PopularFX. 

Of all of them, only Astra experiences the same problem as GeneratePress.

**Comment by gabbsmo** [comment]
It looks like the offending style is no longer rendering, which is good. Currently running WP 6.5.4.
