### ISSUE TITLE
Site Editor: navigating to Patterns produces and unpleasant flash effect

### ISSUE THREAD

**Issue by jsnajdr** [WordPress/gutenberg#61436]
Steps to reproduce:
1. Open Site Editor on the home page (labeled as "Design").
2. Click on "Patterns".

There is a large white content area on the page, and during the navigation to "Patterns" it becomes all black for a moment, before a new white content area is rendered again:

https://github.com/WordPress/gutenberg/assets/664258/1749b4de-5a5e-40bc-93ef-53aa9ec48c73

This is visually very unpleasant, it's like your screen flashed.

**Comment by annezazu** [comment]
I can replicate with GB 18.2 using WP 6.5.2.

**Comment by tyxla** [comment]
I confirm that https://github.com/WordPress/gutenberg/pull/61859 resolves this one.
