### ISSUE TITLE
Time to Read block showing "this block has encountered an error"

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#61459]
### Description

With default WP 2024 theme and Gutenberg, edit your single template and add the "time to read" block and you will see the error.

### Step-by-step reproduction instructions

See above.

### Screenshots, screen recording, code snippet

https://soapbox.wistia.com/videos/CDGp80DwCd

### Environment info

- wp 6.5.3
- gutenberg 18.2.0
- chrome
- mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report. I found the cause and will be filing a PR soon.

**Comment by hbhalodia** [comment]
Hi @t-hamano @bradhogan, Since I have checked the PR was not already created for the issue, so did work on the same and have raised the PR - https://github.com/WordPress/gutenberg/pull/61614. Please take a look on the PR.

Thank You 🙏.

**Comment by bradhogan** [comment]
Great thanks @hbhalodia
