### ISSUE TITLE
Pattern render hooks no longer run

### ISSUE THREAD

**Issue by ryelle** [WordPress/gutenberg#61454]
Prior to https://github.com/WordPress/gutenberg/pull/60349, pattern blocks would run the `render_block`, `render_block_core/pattern`, and related rendering hooks. I've used those to filter over pattern content (see https://github.com/WordPress/wporg-parent-2021/issues/136 for specific details). Since patterns no longer render, the hooks never run, and so my functions don't run.

To reproduce, here's one example from WordPress.org's code (code example below).

1. Have patterns included directly from templates, include an arrow
2. Add a function to filter the content
3. View the content

On Gutenberg 18.0.1, the filter should run — in this case, wrap the arrows with spans.

With GB 18.1+, the filter no longer runs, so the arrows are not wrapped.

Filter code:

```
add_filter(
	'render_block_core/pattern',
	function( $content ) {
		return preg_replace( '/([←↑→↓↔↕↖↗↘↙])/u', '<span aria-hidden="true" class="wp-exclude-emoji">\1</span>', $content );
	}
);
```

Excerpt [from a pattern](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/patterns/download.php):

```
<!-- wp:paragraph -->
<p><?php _e( '<a href="https://wordpress.org/about/features/">See all WordPress features ↗</a>', 'wporg' ); ?></p>
<!-- /wp:paragraph -->
```

We have [a similar function running to handle inline styles on RTL locales](https://github.com/WordPress/wporg-parent-2021/blob/7a7464cd6c3cf5b9ca87c09d8f68fa3182d944fd/source/wp-content/themes/wporg-parent-2021/inc/gutenberg-tweaks.php#L94).

I'm open to doing this a different way, but ideally we need some top-level filter that can be run over the rendered block content once and the pattern render hook was perfect for that.

**Comment by joemcgill** [comment]
I'm curious why you chose to apply this content filtering at the pattern level, rather than somewhere else.

**Comment by ryelle** [comment]
It seemed to be the best place for it, for our use case. On WordPress.org, the content is output via patterns, not post content (so that it can be translated and publicly version-controlled).

For example, [the front page template](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/templates/front-page.html) has just a header, footer, and pattern. The [pattern contains all the page content](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/patterns/home.php).

![page](https://github.com/WordPress/gutenberg/assets/541093/4c7cff7a-0169-412b-8ad9-785e10c00a19)

The same process is true for all pages on wp.org — About [page template](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/templates/page-about.html), [content pattern](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/patterns/about.php); Features [page template](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/templates/page-features.html), [content pattern](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/patterns/about-features.php); etc.

This way, the same theme can be used to render all the Rosetta sites: https://es.wordpress.org/, https://fr.wordpress.org/, and so on.

So hooking into `render_block_core/pattern` was an easy way to run these content filters only once on the page content. Possibly the only way, as looking through the code I don't see any place where the block content can be filtered once it's rendered for the template-canvas.

**Comment by joemcgill** [comment]
Thanks, that helps. Is it possible to apply these content filters on `get_block_templates` instead? I've been wondering for a while if we don't actually need a separate filter for post-processing the entire template content, that is separate from post-processing of post content (i.e., `the_content` ) as the current state of things is causing some filters to run twice (See https://core.trac.wordpress.org/ticket/55996).

**Comment by ryelle** [comment]
>  Is it possible to apply these content filters on get_block_templates instead?

It looks like that applies to the template content before the blocks are parsed and rendered, so it wouldn't catch the markup from any of our server-side blocks. The nice thing about `render_block_core/pattern` was that it ran after everything else was built.

>  I've been wondering for a while if we don't actually need a separate filter for post-processing the entire template content

Yeah, that's pretty much what I'm looking for. In fact, `the_block_template_html` from https://github.com/WordPress/wordpress-develop/pull/5188 would be great.

**Comment by joemcgill** [comment]
I've refreshed the filter approach in https://github.com/WordPress/wordpress-develop/pull/6533.

**Comment by westonruter** [comment]
There's also https://github.com/WordPress/gutenberg/pull/61212 which proposes a filter for the entire HTML response (down to the `html` tag), which may be needed for the Interactivity API.

**Comment by justintadlock** [comment]
Just came here to note that this has broken a conditional/visibility system that I have in place, which I use when calling `<!-- wp:pattern /-->`.

**Comment by ellatrix** [comment]
> Just came here to note that this has broken a conditional/visibility system that I have in place, which I use when calling `<!-- wp:pattern /-->`.

Could you elaborate?

**Comment by ellatrix** [comment]
I commented on my own PR here about running the filters: https://github.com/WordPress/gutenberg/pull/61711#issuecomment-2116609762

I don't understand how this isn't a problem already: once you load patterns in the editor, they'll be resolved, and disappear on the next save.

It sounds like you want to preserve these patterns on the front-end. Maybe there's a way to only replace them when getting patterns for the editor? Maybe we need to remove the resolving from `get_block_templates` and `get_block_template` and only resolve for the REST API endpoint(s).

**Comment by ellatrix** [comment]
Here's my new proposal: #61757

**Comment by justintadlock** [comment]
@ellatrix - The new proposal looks like it'd resolve the issue.

Yes, this is for a system that's on the front end only when used for patterns. Templates in this case are not saved in the database. I can work around it by adding the conditional feature to a wrapping Group block around the pattern, but my main concern is for folks who have deployed it on existing sites using the Pattern block.

**Comment by ryelle** [comment]
> I don't understand how this isn't a problem already: once you load patterns in the editor, they'll be resolved, and disappear on the next save.

For my case, these are patterns that are not enabled in the editor. They're only called from templates, which are never generated from the database, only theme files. The pattern hooks were just a convenient place to run some code.

That said, I believe we've moved away from switching out pattern slugs [in favor of filtering the template hierarchy](https://github.com/WordPress/pattern-directory/pull/686) (which seems more in line with how it "should" work). For the other things we've attached to the pattern render hook, `the_block_template_html` from WordPress/wordpress-develop#6533 works even better.

However until that merges, https://github.com/WordPress/gutenberg/pull/61757 looks good and should let wp.org update gutenberg again.

**Comment by talldan** [comment]
There's also the potential for the `wp/block` (old reusable/new pattern block) to reference bundled patterns via slugs in the future (like template parts do), but the difference is the block wouldn't auto-remove itself. Not sure if that would help with any of the issues being mentioned.

**Comment by ellatrix** [comment]
It sounds like we should go ahead with that fix. Could anyone approve?
