### ISSUE TITLE
Regression: Hovering preview frame no longer scales it up

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#61487]
In the site editor, when you move the mouse over the main preview frame, it is meant to scale up to indicate it's actionable. This recently regressed, and there's no longer any scale effect:

![hover canvas](https://github.com/WordPress/gutenberg/assets/1204802/becb361f-74a5-4646-9899-56148ab3350a)

**Comment by stokesman** [comment]
I'd like if it could stay that way. I've never been a fan of that.

**Comment by stokesman** [comment]
I feel my last comment is lacking. The reasons I'm not a fan:
- The animation duration is lethargic and I feel tends to impress that the app is too.
- Text tends to “vibrate” during the transition (and it’s quite notable due the above point).

I am not opposed to an animated indicator of actionability. I believe there has to be something better. I get this is a regression and so the feedback is out of place here. I just hope to nudge the adept and beautiful folks of the design team to consider getting back to it at some point ❤️.

**Comment by jasmussen** [comment]
Good thoughts. I like to think we could dive in and tweak this animation, see if it can be made slightly faster 👍 👍

**Comment by jasmussen** [comment]
That said, this regression was fixed. I wonder, should we open a new issue for that?
