### ISSUE TITLE
Render in-between inserters on hover and is-selected in zoom out mode

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#61546]
Currently the in-between inserters are rendered when the inserters come into view. 

Instead, let's render them with the same conditions as the outlines: when hovering over a top-level block/section and when the block is selected. 

![CleanShot 2024-05-10 at 10 37 45](https://github.com/WordPress/gutenberg/assets/1813435/caa55e51-7206-4284-a1a7-89e544faeae8)

**Comment by scruffian** [comment]
This seems to have regressed.
![EZBt6dOBf0s9LAWKCUmrO2CLWYg7p3UncWKTJJv5 (1)](https://github.com/user-attachments/assets/a55e543d-99a5-4896-8aad-abadb5cfc0d8)

**Comment by scruffian** [comment]
This was fixed by https://github.com/WordPress/gutenberg/pull/63668
