### ISSUE TITLE
Drag and drop uploading should respect multisite max upload size

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#6154]
## Issue Overview

Drag and drop upload doesn't respect the max upload size option in WordPress multisite.

For reference, here's an example of the error in the media library:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/36432/38708769-98224872-3e6c-11e8-9c98-c25d2105489b.png">

In Gutenberg, I'm permitted to upload the same image without error.

## Steps to Reproduce (for bugs)

In the network admin, configure "Max upload file size" to be a small-ish number:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/36432/38708810-cdce52a4-3e6c-11e8-8f53-104677a6a96d.png">

Then, try uploading an image of a larger size into Gutenberg.

## Expected Behavior

My expected error is to see some equivalent error in the Gutenberg editor. This validation should initially be handled client-side as Plupload, but also handled in the REST API (https://core.trac.wordpress.org/ticket/43751).

In resolving this issue, we'll need to also make sure Gutenberg respects the "Site upload space" option.

The two sitemeta options are `fileupload_maxk` and `blog_upload_space`:

<img width="986" alt="image" src="https://user-images.githubusercontent.com/36432/38708998-ae9260c8-3e6d-11e8-8f07-1d75df8557f5.png">

**Comment by jorgefilipecosta** [comment]
I think this PR https://github.com/WordPress/gutenberg/pull/4203 will handle the issue.

**Comment by danielbachhuber** [comment]
@jorgefilipecosta The PR also needs to respect `blog_upload_space` on multisite. It doesn't appear to include that.

**Comment by danielbachhuber** [comment]
I've updated the Core Trac ticket with a patch I like: https://core.trac.wordpress.org/ticket/43751#comment:3

We can close this issue when a patch for the Trac ticket lands in Core. At this point, I don't think it's worth backporting the change to Gutenberg.

**Comment by danielbachhuber** [comment]
🚢
