### ISSUE TITLE
Styles missing with custom fields panel active

### ISSUE THREAD

**Issue by simom** [WordPress/gutenberg#61565]
### Description

With the latest version of Gutenberg, 18.3.0, and the custom fields panel active, the CSS style is no longer rendered.

### Step-by-step reproduction instructions

1. Edit a page/post
2. From the preferences panel enable the custom fields and save

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/492145/04821108-99d9-4777-a6ea-20b1b54ad00a

### Environment info

- WordPress 6.5.3
- Gutenberg 18.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by remkus** [comment]
Noticed the same thing just now, and I suspect this is related to the reset.css file. Was this file introduced with this edition or heavily altered?

**Comment by goodpenguins** [comment]
> Noticed the same thing just now, and I suspect this is related to the reset.css file. Was this file introduced with this edition or heavily altered?

This reset.css is a standard part of the Gutenberg plugin build. It always loads. But in this case, for some reason it received higher priority than global styles.

**Comment by gyurmey2** [comment]
The problem returned when updating to 18.6.20240528.

**Comment by gyurmey2** [comment]
The issue returned when updating to [18.6.20240528](https://github.com/bph/gutenberg/releases/tag/18.6.-nightly).
#61602
#61582
