### ISSUE TITLE
RSS block: fails to add feed when pasting feed URL and unexpectedly transforms to Embed block

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#61566]
### Description

WHen pasting a feed URL in the RSS block placeholder, the block unexpectedly transforms to the Embed block and fails to render the feed. Also, the 'Undo' doesn't do anything.

This appears to be a regression as in WordPress 6.5 pasting a feed URL works as expected. See Animated GIFs.

WordPress 6.5:

![6 5 rss](https://github.com/WordPress/gutenberg/assets/1682452/1c5d5b48-c234-4944-ba05-a18ecdb0ff26)

Latest trunk:

![trunk rss](https://github.com/WordPress/gutenberg/assets/1682452/58a669a6-310b-4cf1-ac2f-4bb31e73ca20)

### Step-by-step reproduction instructions

- Test on WordPress 6.5
- Create a new post and add an RSS block.
- Paste (do not type) the following URL in the input field in the block placeholder: `https://make.wordpress.org/core/feed/`
- Press Enter or click 'Use URL'.
- Observe the block renders the feed, as expected.
- Click 'Undo' in the top bar and observe the Undo works as expxected.
- Test on latest trunk.
- Repeat the steps above.
- Observe that as soon as the URL is pasted, the RSS feed block placeholder disappears.
- Observe a loading icon appears for a while.
- Observe the block transforms to an Embed block.
- Observe the feed is not rendered and the Embed block placeholder shows an error message: 'Sorry, this content could not be embedded.'.
- Click unto in the top bar and observe it doesn't do anything.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
This problem occurs not only with the RSS block, but with all blocks that have text fields. Since this issue was reported in #61377, I would like to close this issue.
