### ISSUE TITLE
Where is wp.i18n source?

### ISSUE THREAD

**Issue by elliotcondon** [WordPress/gutenberg#6157]
Hi guys,

I'm trying to find the `wp.i18n` object source code so I can perform some debugging.
The script "wp-i18n" is enqueued within the Gutenberg plugin, but can't be found here in the repo.

Looking at the package.json file, this asset looks to be a dependency `"@wordpress/i18n": "1.0.0"` but this seems to be a dead end.

Can you please provide some help finding this .js file (unminified)?

**Comment by pento** [comment]
Hey, @elliotcondon!

All `@wordpress` dependencies come from the [packages repo](https://github.com/WordPress/packages/). In this case, you the `i18n` package is [here](https://github.com/WordPress/packages/tree/master/packages/i18n).

**Comment by elliotcondon** [comment]
Thanks @pento!

**Comment by ntwb** [comment]
p.s. v1.1.0 of `@wordpress/i18n` was released a [couple of hours ago](https://github.com/WordPress/packages/releases/tag/%40wordpress%2Fi18n%401.1.0)
