### ISSUE TITLE
Components: Flaky 'palette-edit' unit test

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#61593]
I noticed the Palette Edit unit test failing several times in the last few days. Here's the latest failure - https://github.com/WordPress/gutenberg/actions/runs/9049257886/job/24863159821?pr=61592#step:6:185.

## Screenshot
![CleanShot 2024-05-12 at 13 24 57](https://github.com/WordPress/gutenberg/assets/240569/d73be079-324a-4dc3-9ea9-2900f6c027d7)

**Comment by tyxla** [comment]
Hey @Mamaduka, do you think we can close this after #61818 and #61791? It appears like these tests have been pretty stable over the past couple of days.

**Comment by Mamaduka** [comment]
@tyxla, sure!
