### ISSUE TITLE
Choose a pattern section scroll not working

### ISSUE THREAD

**Issue by parinpanjari** [WordPress/gutenberg#61613]
### Description

The "Choose a pattern" section scroll functionality is not working on the Chrome browser when the screen resolution is set to 1920x1080 with a 150% scale and layout display settings. This issue arises specifically when the Chrome browser zoom is set to 100% under the 150% scale and layout display settings.

**Expected Behavior:**
The "Choose a pattern" section should scroll smoothly, allowing users to view all available options.

**Actual Behavior:**
The scroll functionality of the "Choose a pattern" section is not responsive, preventing users from scrolling within the section when the browser zoom is set to 100% under the 150% scale and layout display settings.

**Additional Details:**
This issue is only observed in the Chrome browser, Windows 10 Pro
Changing the browser zoom to values below 100% (e.g., 90% or 80%) resolves the scroll functionality problem.

**Priority**: This issue should be considered a priority as it impacts non-technical users who may encounter difficulty navigating that section.

### Step-by-step reproduction instructions

1. Open the Chrome browser.
2. Set the screen resolution to 1920x1080.
3. Adjust the scale and layout display settings to 150%.
4. Now go into wordpress admin backend and create one page and wait for this "Choose a pattern" popup 
Screenshot: https://prnt.sc/8KMZ2VzGSTbd
5. Attempt to scroll within the section.

### Screenshots, screen recording, code snippet

**Screenshot**: https://prnt.sc/8KMZ2VzGSTbd

**Video Recording** 
https://www.loom.com/share/83229593f061452f9abc338cff6bc273?sid=43d8f0d0-bb29-4481-8977-eb0c8715a028

### Environment info

- Wordpress Version 6.5.3
- Twenty Twenty-Four Theme activated
- Windows 10 Pro

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by stokesman** [comment]
Hi @parinpanjari, I watched the recording and I get the impression this is the same issue as reported in #61267. Would you agree?

**Comment by parinpanjari** [comment]
Hi @stokesman 

I agree with you. So do I have to remove this ticket from github?

Thank you!

**Comment by stokesman** [comment]
No need to remove it. I'll close it as a duplicate but I'll mention it on the other issue. It’s helpful to have the report that it happens on Windows too.

**Comment by stokesman** [comment]
Closing as duplicate.
