### ISSUE TITLE
Shift up in first text block should select to 1st character

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#6164]
There's an issue with shift selecting. GIF:

![shift select](https://user-images.githubusercontent.com/1204802/38662841-c1341d76-3e35-11e8-8195-174f2a5f9ad7.gif)

Shift select across paragraphs works.

Setting the caret in the last text block and shift selecting downwards, selects _until the end of the text in that block_, as it should.

Setting the caret in the first block and shift selecting upwards, doesn't seem to select _until the beginning of the text in that block_, as would be expected.

This was a split out from https://github.com/WordPress/gutenberg/issues/5548#issuecomment-380786172

**Comment by designsimply** [comment]
Tested and found that setting the caret in the first block and selecting upward does not select until the beginning of the text in that block and setting the caret in the last block and selecting downward does not select until the end of the text in that block.

**Video:** [56s](https://cloudup.com/c25EQ6DQBac)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13999&action=edit running WordPress 4.9.7 and Gutenberg 3.3.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

**Comment by youknowriad** [comment]
Just to confirm @aduth you were looking at this recently right? Is there a PR to link to?

**Comment by aduth** [comment]
Yes, see #13638 .
