### ISSUE TITLE
The Search Bar on plugin section Seems out of place

### ISSUE THREAD

**Issue by ashikur698** [WordPress/gutenberg#61669]
## What problem does this address?

The search bar in the plugin section of - https://wordpress.org/plugins/ this URL seems out of place. Specially when I click on any plugin. 

## What is your proposed solution?

The search bar should be on the right side as the upper search bar.
<img width="1718" alt="Screenshot 2024-05-15 at 9 41 36 AM" src="https://github.com/WordPress/gutenberg/assets/134126946/6fd45c0c-0939-469c-b7ae-fc88a2c911e1">

**Comment by Mamaduka** [comment]
@ashikur698, this is the repo for the Block Editor development.

The plugin directory tickets can be submitted here - https://meta.trac.wordpress.org/
