### ISSUE TITLE
Publish flow: longer title of post doesn't wrap words

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#61690]
Using GB 18.3, I noticed that a longer title ends up splitting words in two:

![Screenshot 2024-05-15 at 10 53 44 AM](https://github.com/WordPress/gutenberg/assets/26996883/f8c0d9c4-6c5a-4ead-a858-f2a57e1db4bb)

A quick change to make it `break-word` instead of `break-all` fixes it cc @ntsekouras as part of [this work to unify publish flows](https://github.com/WordPress/gutenberg/issues/59878).

**Comment by Mamaduka** [comment]
It seems to be working correctly for me on the trunk. Which browser are you using for testing?

@jasmussen updated the `Text` component (used in that area) to use the new `text-wrap: pretty;` style, which I think should prevent similar issues. See #60164

## Screenshot
![CleanShot 2024-05-15 at 22 25 00](https://github.com/WordPress/gutenberg/assets/240569/da617aa6-5757-4a99-a4c2-b3076d0990a4)

**Comment by annezazu** [comment]
Using Chrome! If it works in trunk, I'll close out in that case. I was writing a post on a site with GB and just wanted to make sure to report :)
