### ISSUE TITLE
ACF Post Objects no longer work with gutenberg

### ISSUE THREAD

**Issue by hartey11** [WordPress/gutenberg#6173]
## Issue Overview

Any custom field that is linked to a post object no longer works when the gutenberg editor is active.

## Steps to Reproduce (for bugs)

1. Add a relational custom field.
2. Go to post with with custom field.
3. No posts show up and there are lots of console errors.
<img width="1439" alt="screen shot 2018-04-13 at 16 32 45" src="https://user-images.githubusercontent.com/6071669/38740763-ada6ff36-3f38-11e8-8640-6c6716ca932f.png">

**Comment by aduth** [comment]
Related: #6174, #6123

Are you running the latest version of the ACF plugin? It was claimed that updating to the latest version resolved the issue in #6123.

**Comment by rchipka** [comment]
This is because ACF overwrites the `window.wp.hooks` object, causing `wp.hooks.hasFilter` to be undefined.

A workaround is to replace all occurrences of `wp.hooks` with `wp.acf_hooks` within the file `/plugins/advanced-custom-fields-pro/assets/js/acf-input.min.js`

**Comment by aduth** [comment]
Going to close this as an issue that should be resolved within the plugin.

There was some discussion in the April 10th [Core JavaScript developers meeting](https://wordpress.slack.com/archives/C5UNMSU4R/p1523366355000353) that the `wp` global should only be used by core scripts, not augmented by plugins.

**Comment by rchipka** [comment]
@aduth If there's a JavaScript issue related to ACF, there's a high probability that this is a cause. Everything else seems to be pretty compatible.
