### ISSUE TITLE
Add tooltip to hover for color presets

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#61743]
### Description

When hovering the color presets in the site editor, I expect to see a tooltip to show that tells me the title of the preset (presumably coming from the title of the style variation it's a part of).

### Step-by-step reproduction instructions

1. Go to site editor > global styles > colors > palette
2. Hover over a preset
3. See nothing

### Screenshots, screen recording, code snippet

The video below shows hover over theme colors in the palette section, which reveals tool tip. When hovering over the presets, no tool tip is revealed.

https://github.com/WordPress/gutenberg/assets/486261/f43e057c-a5f1-4846-81f9-bb94feb06608

### Environment info

WordPress 6.5.3
Gutenberg 18.4.0-rc.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sahiladit** [comment]
Can you assign it to me?

**Comment by amitraj2203** [comment]
Hi @bgardner, I have raised a PR for this issue.

Thank You
