### ISSUE TITLE
Scroll Bar present in styles colors preset panel

### ISSUE THREAD

**Issue by hbhalodia** [WordPress/gutenberg#61759]
### Description

On the Site Editor, if we visit the styles panel and open the colors panel, we can see that there is a scroll bar present in the color presets options pill.

### Step-by-step reproduction instructions

1. Open Site Editor.
2. Go to styles > colors > pallets > presets
3. You can see that there is the little scroll bar present in the pill that shows the color presets.

### Screenshots, screen recording, code snippet

<img width="1426" alt="Screenshot 2024-05-17 at 4 32 21 PM" src="https://github.com/WordPress/gutenberg/assets/58802366/00f6e6e6-9eff-4b4a-ab26-5f3b6418171e">

Screencast to reproduce the issue

[GB New Issue.webm](https://github.com/WordPress/gutenberg/assets/58802366/3e2fbee8-a077-4673-816a-c9f2802c0399)

### Environment info

- WordPress Version - 6.5.3
- Gutenberg Version - Latest Trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hbhalodia** [comment]
There is an issue because `IFrame` is getting the height of `152px`, which is the normalized height defined here.

https://github.com/WordPress/gutenberg/blob/d538f429f018aba34814b360c5adf37eb6013427/packages/edit-site/src/components/global-styles/preview-iframe.js#L27

<img width="1426" alt="Screenshot 2024-05-17 at 4 44 48 PM" src="https://github.com/WordPress/gutenberg/assets/58802366/b8f5ed6b-5abb-43ea-bd3b-1d65dee9c56e">

We need to tweak this in order to fix the scrollbar issue.

**Comment by bgardner** [comment]
This looks like it was ack’ed https://github.com/WordPress/gutenberg/pull/61617 by @youknowriad (https://github.com/WordPress/gutenberg/pull/61617#issuecomment-2107340469) and confirmed by @annezazu (https://github.com/WordPress/gutenberg/pull/61617#issuecomment-2111172164).

**Comment by annezazu** [comment]
Yes! Hopefully, we can get that fixed within that PR. Thanks for sleuthing and dot connecting here.

**Comment by hbhalodia** [comment]
Hi @fabiankaegy, I guess we can move this issue to `Needs Review` status, Since PR is already raised here - https://github.com/WordPress/gutenberg/pull/61617 and looks like the potential fix for this. 

Thank You ✨.

**Comment by fabiankaegy** [comment]
Good call :) thanks!
