### ISSUE TITLE
It's not clear how to change URL for embed. 

### ISSUE THREAD

**Issue by Shelob9** [WordPress/gutenberg#6176]
## Issue Overview
Once I have an embed block and I want to change the URL for the block, it's not super obvious how to edit that. 

If I had to guess, I would say it is the link icon in the middle of the block:
![screen shot 2018-04-13 at 1 29 48 pm](https://user-images.githubusercontent.com/1994311/38749779-dd0d2dda-3f20-11e8-8f65-3a18772aed2a.png)

That's actually part of the UI for the embed caption, which _is obvious I have a caption_

![screen shot 2018-04-13 at 1 30 04 pm](https://user-images.githubusercontent.com/1994311/38749849-0d2aca40-3f21-11e8-8a36-a2faeebdd7db.png)

## Possible Solution
1. Hide the toolbar for the caption until the caption is not empty. This probably requires a placeholder or visible label for the caption so its clear you can enter a caption.
2. Add a control for embed URL to advanced settings for the block.
3. Use the pencil icon when block is focused to open a control for embed URL or focus the advanced setting for it:

![screen shot 2018-04-13 at 1 51 32 pm](https://user-images.githubusercontent.com/1994311/38750087-d07d2100-3f21-11e8-9574-96fbd2667998.png)
 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Good feedback, @Shelob9.

I've filed to `WordPress 5.0` because this doesn't appear to be a blocker for merge proposal.

**Comment by karmatosed** [comment]
I think with our link UI unifications - having in toolbar - this could be solved. That said, the simpler option of a solid placeholder feels also worth exploring:

> Hide the toolbar for the caption until the caption is not empty. This probably requires a placeholder or visible label for the caption so its clear you can enter a caption.

I'll flag as 'needs design' so we can iterate.

**Comment by mtias** [comment]
An edit link next to the alignment toolbar, like we have for the image block, etc, seems the consistent approach here.

**Comment by notnownikki** [comment]
Another vote for an edit link next to the alignment toolbar!

**Comment by notnownikki** [comment]
Fix is up for review in https://github.com/WordPress/gutenberg/pull/8084

**Comment by notnownikki** [comment]
Fix merged!
