### ISSUE TITLE
New Block: Generic Date/Time Block

### ISSUE THREAD

**Issue by bhubbard** [WordPress/gutenberg#61772]
## What problem does this address?
A simple block where user can enter date or time, and it can be displayed using the <time> tag in html. 

## What is your proposed solution?
New block with date and/or time picker, with various options on how to display. Maybe option to choose current date/time. Output html using time tag: https://www.w3schools.com/tags/tag_time.asp

It might also make sense to be able to set time within text similar to inline code, or hightlight.

**Comment by t-hamano** [comment]
Thanks for the suggestion. 

Is this proposal the same as the one proposed in #54488?

**Comment by bhubbard** [comment]
@t-hamano Yep, this would be the same, closing mine, watching yours. Thanks!
