### ISSUE TITLE
Gutenberg Tabs crashing on Edit with React error - unable to edit tabs or content

### ISSUE THREAD

**Issue by lari-ks** [WordPress/gutenberg#61773]
### Description

Feature crashes in Wordpress editor when trying to select Typography to edit the styles - in the browser its showing a React error TypeError: n.map is not a function or its return value is not iterable

Update: It only happens when selecting Typography

### Step-by-step reproduction instructions

Wordpress.com pages, select page, select Edit, select one of the Guternberg tabs, go into styles, select 'Typography' for example, and the block will crash and no longer be displayed or editable. Prevents users editing the Tabs or any of the content inside them to edit.

### Screenshots, screen recording, code snippet

![error-2](https://github.com/WordPress/gutenberg/assets/169511131/fc69c151-90d4-4f41-8757-54790fc7093b)
![error-1](https://github.com/WordPress/gutenberg/assets/169511131/03edf6b1-a105-4307-a950-c19851bc7e55)

### Environment info

Wordpress.com - Assembler Theme - latest Gutenberg version (updated 1 week ago) and latest Gutenberg Tabs version which it says was updated 4 months ago yet the error just happened. It was working fine earlier and in last 2 days. No new plugins were added or edited.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @laraght

The "Tabs" isn't a core feature; it's probably coming from a 3rd-party plugin.

I recommend reaching out to WP.com support. They'll have more details and can submit a ticket upstream to fix the issue.
