### ISSUE TITLE
DataViews: The correct action menus are not displayed for patterns and template parts

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#61787]
### Description

On the Patterns page, the DataView's action dropdown displays unexpected action menus or expected action menus are missing.

### Step-by-step reproduction instructions

The following are unnecessary actions as far as I've researched.

### Patterns bundled with themes

![image](https://github.com/WordPress/gutenberg/assets/54422211/414b678c-4b11-40de-a1cf-8cbc94d42431)

Patterns bundled with themes should only be allowed to be duplicated. The following three actions should not be displayed because they cause unintended behavior.

- Edit: The editor canvas opens, but with the template instead of the selected pattern.
- Rename: The message `Patterns bundled with themes should only be allowed to be duplicated. ` is displayed.
- Move to Trash: The action is executed, but the pattern is not removed (and of course it shouldn't be).

### User-created patterns

![image](https://github.com/WordPress/gutenberg/assets/54422211/370e38c9-6f2b-4aeb-a2c4-fc5288733d3e)

"Move to trash" is not necessary because the "Delete" menu already exists.

### User-created template parts

![image](https://github.com/WordPress/gutenberg/assets/54422211/1272e6dd-7313-4133-b09c-e8fefccbfdcb)

The following actions are missing:

- Rename
- Delete

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jameskoster** [comment]
Just noting that the extraneous 'Move to trash' action on patterns also appears in the Inspector:

<img width="280" alt="Screenshot 2024-05-20 at 16 55 00" src="https://github.com/WordPress/gutenberg/assets/846565/c531a798-3f6f-4cfb-8eff-e627e51a06dc">

**Comment by ntsekouras** [comment]
I'll take a look into this.

**Comment by ntsekouras** [comment]
Closing this as I think it's fully fixed with this [last PR](https://github.com/WordPress/gutenberg/pull/61912). Feel free to reopen if I've missed something.
