### ISSUE TITLE
Make 'Delete', 'Trash', 'Reset' should always be the last item in action menus

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#61798]
'Delete', 'Trash', and 'Reset' are the most destructive actions that can be applied to records. They're also universal in the sense that _most_ editable records will allow one of these actions. 

For the sake of consistency they should always appear _last_ in action menus.

Currently this is not the case for **templates** and **template parts**, both in data views, and in the Inspector:

### Theme template
<img width="329" alt="Screenshot 2024-05-20 at 16 42 13" src="https://github.com/WordPress/gutenberg/assets/846565/15ffa92b-f498-4e44-9c85-178f15c94ba2">

### Custom template
<img width="326" alt="Screenshot 2024-05-20 at 16 42 23" src="https://github.com/WordPress/gutenberg/assets/846565/780c8480-0663-4749-a4eb-9919b259683d">

### Theme template part
<img width="320" alt="Screenshot 2024-05-20 at 16 42 41" src="https://github.com/WordPress/gutenberg/assets/846565/a62c12cd-0424-4446-8c45-8b3b18536218">

**Comment by abhi3315** [comment]
@jameskoster I have raised https://github.com/WordPress/gutenberg/pull/61803 PR to address this issue.
