### ISSUE TITLE
It should be possible to delete custom template parts

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#61799]
I'm not sure when this occurred, but it's currently impossible to delete custom template parts:

<img width="331" alt="Screenshot 2024-05-20 at 16 49 28" src="https://github.com/WordPress/gutenberg/assets/846565/cd76b556-c1c7-4efe-817a-197ad093dbb7">

**Comment by t-hamano** [comment]
I reported a broader issue regarding this in #61787.
