### ISSUE TITLE
Filtering 'My patterns' category in the Inserter is a bit clunky

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#61826]
<img width="936" alt="Screenshot 2024-05-21 at 16 37 28" src="https://github.com/WordPress/gutenberg/assets/846565/417e6593-403b-4def-b7cc-f0dc4abb6481">

---

1. My patterns will always be source=user(?); should that filter be hidden in this context?
2. Why are synced/not synced options disabled?

**Comment by kevin940726** [comment]
> 1\. My patterns will always be source=user(?); should that filter be hidden in this context?

We can do that but I think we only kept them visible for consistency. Should we consider hiding it?

> 2\. Why are synced/not synced options disabled?

I believe this is a bug accidentally introduced in https://github.com/WordPress/gutenberg/pull/57570. I can file a PR fixing that.

**Comment by jameskoster** [comment]
> We can do that but I think we only kept them visible for consistency. Should we consider hiding it?

Since the filter is presented local to the selected category, it seems superfluous to offer options can never be adjusted. Hiding is worth a try imo.

**Comment by kevin940726** [comment]
Closed by #63828 and #63831.
