### ISSUE TITLE
Comments and Pingbacks get cleared out when a pattern is edited (within the editor) and a metabox is shown

### ISSUE THREAD

**Issue by mlaetitia** [WordPress/gutenberg#61827]
### Description

When editing a post, if we also edit a pattern from within the post, the comment_status and pingbacks get turned off.

This happens only (from my tests) when a metabox is added / showing on the editor (example: the custom fields metabox or the Yoast SEO one).

### Step-by-step reproduction instructions

1. Edit or create a post (Gutenberg)
2. Make sure you have Custom Fields showing on the editor (hamburguer menu, preferences, advanced , custom fields)
3. If there's no pattern on that post yet, create one (that syncs across posts)
4. Make sure the posts and pingbacks are turned on.
5. Edit the pattern and save it
6. Head back to the Post editor. If you refresh the page here you'll notice that the comments and pingbacks are turned off. Same happens if instead of refreshing you just "Save Draft" or Update Post. This means somehting is happening in the backend and changing these fields without updating the UI (only when we get new data from the server, do those fields show as off).

### Screenshots, screen recording, code snippet

![Screen Capture on 2024-05-21 at 16-37-38](https://github.com/WordPress/gutenberg/assets/30905719/4098cc76-b9f8-4a33-8d9b-7c46cedda6f2)

### Environment info

This can be replicated with a fresh WordPress installation or WordPress playground without plugins installed.

This can't be replicated in older versions (before 6.5 - I think), seems the issue is present only when we edit the pattern on the post editor itself.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by marcarmengou** [comment]
## Reproduction Report
This report validates that the issue can be reproduced.

### Environment
- OS: Windows 10
- Web Server: Nginx
- PHP: 8.1
- WordPress: 6.5.3
- Browser: Chrome 125.0

### Actual Results
- ✅ Error condition occurs (reproduced).

### Additional Notes
- If you try to play it without activating "Custom Fields" within Preferences, the problem does not occur.
