### ISSUE TITLE
Link popup/modal falls under admin menu

### ISSUE THREAD

**Issue by JeroenSormani** [WordPress/gutenberg#6183]
## Issue Overview
The link popup/modal falls under the admin menu when trying to link a text on the left side of the area.

![image](https://user-images.githubusercontent.com/5774447/38777604-3a3457dc-40ab-11e8-9bc8-89f60078ddb0.png)
(selected 'Hello' to link)

## Expected behaviour
I think its preferable to have it positioned like so;
![image](https://user-images.githubusercontent.com/5774447/38777673-fd77e736-40ab-11e8-99b8-fe92672f53a6.png)
The 'most left' being within the content area.

## Related Issues and/or PRs
https://github.com/WordPress/gutenberg/issues/3350

**Comment by noisysocks** [comment]
Thanks @JeroenSormani. This is definitely a bug and I was able to reproduce this.
