### ISSUE TITLE
Color Presets: Scrollbar is unexpectedly present in color preset previews

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#61840]
### Description

Related to https://github.com/WordPress/gutenberg/issues/61213 and possibly introduced in https://github.com/WordPress/gutenberg/pull/61334

The new color presets design results in an unexpected scrollbar being visible in OSes that are set to always display scrollbars (if present). E.g. a Mac set to "Show scroll bars: Always".

### Step-by-step reproduction instructions

1. In your OS, set scroll bars to display "always"
2. Open up the Site Editor and in the left hand sidebar in browse mode, select Styles
3. Scroll down to the Colors color palettes
4. Notice that there's a grey circle in the top right of the color palette: it's the scroll bar being visible
5. Hover over the color palette and note that you can use the mouse wheel or trackpad to scroll the element

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/14988353/29df49ab-c77b-4c98-9a1b-bb34be210683

### Environment info

- WP 6.5.3
- Gutenberg trunk
- Chrome browser
- macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hbhalodia** [comment]
Just for the context, we have already raised the issue and we are tracking it here - https://github.com/WordPress/gutenberg/issues/61759

**Comment by andrewserong** [comment]
Thanks Hit! Apologies, I missed that issue, I'll close this one out now 🙂
