### ISSUE TITLE
The title field of Reusable Block became unchangeable without a block theme

### ISSUE THREAD

**Issue by greenyang** [WordPress/gutenberg#61855]
### Description

Hi,

I've tried to report this same issue to the [post on the WordPress.org Forum](https://wordpress.org/support/topic/the-title-field-of-reusable-block-became-unchangeable-without-a-block-theme/), then to [the post on WordPress Trac](https://core.trac.wordpress.org/ticket/61208) based on a suggestion from the comment.  Eventually, I think maybe the Gutenberg GitHub Repository is the best place to report to.

As for the post title, some users and I found the title field of Reusable Block became unchangeable without a block theme weeks ago.  Please see the screenshots below in the next section.

I understand it has been called Synced Pattern to be part of the patterns assembled in Appearance – Editor according to [Site Editor Patterns – Documentation – WordPress.org](https://wordpress.org/documentation/article/site-editor-patterns/). It’s good to see that, but I’m afraid part of the compatibility has been missed since the old reusable block relies on the normal block editor which looks like a kind of CPT.
There’s nowhere to see the title field appear and can be named except when Creating a New Pattern (Reusable block) or by switching to the code editing mode in the block editor. I know the SiteEditor and the new related developments are the trend officially. However, please remember there are still plenty of users and designers who support Reusable Block by building the web design works with the block editor ecosystem on a non-block theme for the concerns of high customization.

Thanks,
Green

### Step-by-step reproduction instructions

1. Go to 'Blocks' - 'All Patterns', or 'Appearance' - 'Patterns'.
2. Click 'Edit' on any of the old reusable blocks on the list.
3. You will see there's no title field appears on the top of the block editor as it appeared before the recent core update.
4. Therefore, users can't modify the title of the reusable block unless they switch to 'Code editor' from 'Visual editor'.
5. I haven't tried to 'Convert to block pattern' since it seems not an intuitive step that normal users will try in a non-block theme environment.

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/9197187/7016857c-9c92-420c-ab73-66147450f8f5)
![image](https://github.com/WordPress/gutenberg/assets/9197187/00c0fbab-0fad-4a81-9fb5-7ec27e01c830)

### Environment info

- WordPress version: 6.5.3
- Theme: Blocksy

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

Regarding this issue, it may be related to #59511. In the latest version of Gutenberg, post actions are consolidated into a dropdown, and patterns can also be renamed from there.

![image](https://github.com/WordPress/gutenberg/assets/54422211/702fc72b-114f-401d-b37c-e2a443e4c3b7)

Additionally, in WP6.6, classic themes will also be able to access the Site Editor's Patterns page. See #52150 for details.

**Comment by talldan** [comment]
@greenyang I noticed this recently too, but forgot to make an issue for it.

There is a workaround that I spotted, if you go into the Code Editor mode, then the title is editable there.

**Comment by greenyang** [comment]
@t-hamano Ah, I tried many keywords to search existing issues except "name" of "pattern". Thank you for the answer, I'm expecting the update.

@talldan Thanks for the hint, I know it could be done by switching to Code Editor mode and have shared it with other users, but we still hope it could be fixed or integrated more completely during the transition.

**Comment by t-hamano** [comment]
> Regarding this issue, it may be related to #59511. In the latest version of Gutenberg, post actions are consolidated into a dropdown, and patterns can also be renamed from there.

Given this, can this issue be closed?

**Comment by t-hamano** [comment]
@greenyang I would like to close this issue, but if you have any unresolved issues please feel free to comment.
