### ISSUE TITLE
Page Inspector: Move page attributes UI to updated summary panel

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#61869]
Follow-up to https://github.com/WordPress/gutenberg/issues/59689

Currently page attributes live in a dedicated panel. These can be moved to the updated Summary panel.

### Existing
<img width="279" alt="Screenshot 2024-05-22 at 15 23 38" src="https://github.com/WordPress/gutenberg/assets/846565/fd7a8e8c-f330-4a72-baf3-bbba8a3e6186">

### Proposed
<img width="1552" alt="Screenshot 2024-05-22 at 15 49 03" src="https://github.com/WordPress/gutenberg/assets/846565/894132a6-d97f-4742-b2bc-888a46f3b468">

'Parent' is a line item permanently visible in the list of meta data. 

Order has reduced prominence given it's very situational application.

**Comment by richtabor** [comment]
Closing this as completed (other than the Set as homepage" control, which is detailed in https://github.com/WordPress/gutenberg/issues/63666).  

![CleanShot 2024-07-21 at 16 17 38](https://github.com/user-attachments/assets/fc02af62-9909-449b-a779-318b8e289380)
