### ISSUE TITLE
Focused edit mode discrepancy between post/site editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#61899]
Here's the focused edit mode for template parts, accessed directly (via the Patterns page), or via the page edit experience in the site editor. Note the identical appearance:

### Accessed directly
<img width="942" alt="Screenshot 2024-05-23 at 13 07 40" src="https://github.com/WordPress/gutenberg/assets/846565/dda21e86-2cd8-4f11-b8d9-60b008f51c2f">

### Access via page editing in the Site editor
<img width="943" alt="Screenshot 2024-05-23 at 13 07 50" src="https://github.com/WordPress/gutenberg/assets/846565/83adc210-731c-4dbe-8cc8-1bb758dac3f0">

---

When you edit a template part via the post editor you get a different appearance entirely...

### Access via page editing in the Post editor
<img width="1237" alt="Screenshot 2024-05-23 at 13 08 24" src="https://github.com/WordPress/gutenberg/assets/846565/ab7b5853-8f4f-41df-8acc-13e9da78531f">

Two issues to fix here:

- [x] Missing resize handles: https://github.com/WordPress/gutenberg/pull/61896
- [x] Any padding outside of the template part should not be represented on the canvas: https://github.com/WordPress/gutenberg/pull/61906

**Comment by Mamaduka** [comment]
@jameskoster, it looks like both items have been resolved. Can we close the issue?
