### ISSUE TITLE
IE11 and inline images in contenteditable elements are a keyboard trap

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6192]
In #5794 there's an ongoing effort to make it possible to add inline images within paragraphs (and other editable blocks?).

Seems IE11 has some "peculiarities" with images in a contenteditable element. This is probably something well known to contenteditable specialists and TinyMCE experts /Cc @azaozz @iseulde 

I've initially noticed in the demo content, where the last paragraph has an emoji which is an inline SVG: using the keyboard and tabbing into the block, the image gets focused. Whether it's just "selected" or the "resize handles" appear, seems there's no way to tab away from the image: it's a keyboard trap with no escape:

![screenshot 102](https://user-images.githubusercontent.com/1682452/38796835-ef2d1460-415c-11e8-97fb-672664347f8e.png)

![screenshot 103](https://user-images.githubusercontent.com/1682452/38796836-ef4b4840-415c-11e8-9eae-9721cbc38465.png)

Was hoping it's because the image is a SVG but seems it happens also with other images, see below a test with a JPG: same result, the image gets selected and there's no way to tab away

![screenshot 104 copy](https://user-images.githubusercontent.com/1682452/38796905-23e671ec-415d-11e8-9187-a7fe549821bb.jpg)

Worth noting this happens also on the TinyMCE demo page:

![screenshot 105](https://user-images.githubusercontent.com/1682452/38796936-3d7c9d5c-415d-11e8-800e-fcb63ee2938f.png)

**Comment by afercia** [comment]
@azaozz @iseulde any idea on how to solve this? Yeah I know... IE 11 😬Is this something to be addressed upstream?

**Comment by youknowriad** [comment]
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.
