### ISSUE TITLE
Investigate display issues in the Typography panel

### ISSUE THREAD

**Issue by jarekmorawski** [WordPress/gutenberg#61931]
I noticed the dropdown in the Typography panel has some display issues. The spacing between list items is too great and other UI elements, like toggles and segmented button controls, cover the dropdown.

Tested in Chrome 24.0.6367.61, WP 6.5, WordPress.com.

![image](https://github.com/WordPress/gutenberg/assets/79307566/8c53961e-2601-4865-8724-6f4966ef7f0b)

**Comment by amitraj2203** [comment]
Here's the [PR](https://github.com/WordPress/gutenberg/pull/61937) for this issue.
Thanks

**Comment by t-hamano** [comment]
Thanks for the report.

I searched for the point where this problem occurred and came across #60226.

See [this comment](https://github.com/WordPress/gutenberg/pull/60226#discussion_r1614359131) for details.
