### ISSUE TITLE
Inspector tabs: text no longer visible when 'Show button text labels' preference is enabled

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#61947]
### Description

This appears to be a regression from WordPress 6.5 and should be fixed soon.

Depending on the selected block, the Inspector panel may show content organized within tabs. By default these tabs use icon buttons. Example screenshot:

![Screenshot 2024-05-24 at 15 48 21](https://github.com/WordPress/gutenberg/assets/1682452/e3b0c876-bfd2-4ab5-8f30-4ec554c0c57b)

When the 'Show button text labels' preference is enabled, the icons are supposed to be replacred by visible text. Example screenshot from WordPress 6.5. for a Navigation block:

![6 5](https://github.com/WordPress/gutenberg/assets/1682452/e510cb99-55f1-4c3a-820b-9ce321cf661c)

On latest trunk, the text is not visible any longer. Screenshot for a Navigation block:

![  trunk navigaton](https://github.com/WordPress/gutenberg/assets/1682452/4634144e-277a-4e0a-a713-8d418841f6c7)

Screenshot for an Image block:

![trunk image](https://github.com/WordPress/gutenberg/assets/1682452/3c0656b9-d9df-4a82-a255-60f2c4bb5930)

It appears that some recent changes to a CSS transition introduced this bug, as the `::before` pseudo element that is supposed to generate the visible text has now an `opacity: 0`.

Worth noting the technique to reveal the text for the 'Show button text labels' preference  is fragile to start with, as it uses pseudo elements that _may_ be already used for other purposes. In this case, I think it's used also for the tabs focus style.

Regardless the change to the animation should be either fixed or reverted, as WP 6.6 Beta is very close.

### Step-by-step reproduction instructions

- Go to Options > Preferences > Accessibility, and enable the 'Show button text labels' preference.
- Select any block that is supposed to render tabs in its Inspector panel e.g. an Image block or a Navigation block.
- Observe the tabs text is no longer visible.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by afercia** [comment]
@jasmussen any clue what changed here? Thanks 🙏🏽

**Comment by jasmussen** [comment]
No clue. @WordPress/gutenberg-core

**Comment by t-hamano** [comment]
I've identified the problem and will submit a PR soon.
