### ISSUE TITLE
Add UI to Global styles to allow modification of font size presets

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#61987]
## What?
Add UI to Global styles to allow modification of font size presets

## Why?
This will allow users to edit the font size presets using the editor.

**Comment by matiasbenedetto** [comment]
I started a potential implementation of this here: https://github.com/WordPress/gutenberg/pull/62328

**Comment by annezazu** [comment]
Just wanted to bring in feedback as the PR above gets underway that being able to control the font sizes on smaller devices is a major responsiveness related request I hear from folks. The latest look showing how you can [toggle on an option to set custom fluid sizes](https://github.com/WordPress/gutenberg/pull/62328#issuecomment-2182672359) will go a long way in addressing that! Excited to see this land and to get some testing done.
