### ISSUE TITLE
theme.json h1 tag font size is override by core heading block font size

### ISSUE THREAD

**Issue by uniquesolution** [WordPress/gutenberg#61988]
### Description

when in theme.json file I add font size for both core/heading and h1 to h6 elements, core/heading font size override the h1 to h6 font size. Due to this by default h1 and h2 tags remain same font size and I have to apply manual font size to various heading blocks based on its tag (h1, h2, h3 etc.)

### Step-by-step reproduction instructions

1. Go to theme.json file of the block theme. and apply any font size to core/heading block, for example
"styles": {
"blocks": {
"core/heading": {
"typography": {"fontSize": "var(--wp--preset--font-size--large)"}
}
}
}
2. Now apply different font sizes for heading tags , like h1, h2 etc. For example
"styles": {
"elements": {
"h1": {
"typography": {"fontSize": "var(--wp--preset--font-size--extra-huge)"}
}
}
} etc.
3. Now go to any page in backend and add heading block, it always take the default heading size, instead of the h1, h2, etc applied heading size. We have to manually change h1 tag or h2 font size to a desired size. By default h1, h2 elements font size should override heading block font size, but its happening opposite of it.

### Environment info

Wordpress Version - 6.5.3
I am not using gutenberg plugin as separate plugin, but block editor is using gutenberg version available for the wordpress version.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by carolinan** [comment]
Hi
I would like to understand why you are adding a font size to the heading block if you **don't** want it to apply to heading blocks? (Maybe there is a use case I am not aware about)

**Comment by uniquesolution** [comment]
you are right @carolinan , actually if we are assigning default font sizes for each h tag, then we don't need to assign font size for heading block. So I am closing this issue.

**Comment by strarsis** [comment]
When I use `styles/elements/heading` instead of `styles/block/"core/heading"` I can override the styles with `styles/elements/h1`.
