### ISSUE TITLE
Inline links are hard to see

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#620]
![image](https://cloud.githubusercontent.com/assets/548849/25661462/0de37218-3011-11e7-8ebd-62b4c82a8a5c.png)

-----

We have some work done on the https://wordpress.github.io/gutenberg/tinymce prototype, which includes the link boundaries.

**Comment by iseulde** [comment]
Underline?

**Comment by circlecube** [comment]
Possible to load the styles from the current theme so users get to see what it will look like on their site rather than a default underlined blue.

**Comment by mtias** [comment]
@iseulde yes, but we also need to bring the highlight when selecting within boundaries:

![image](https://cloud.githubusercontent.com/assets/548849/25662166/c80fee4e-3013-11e7-8e1e-aaa634f004be.png)

@circlecube we haven't yet figured out how themes would provide styles.

**Comment by jasmussen** [comment]
Closing as fixed by Ella. Further link boundary improvements are incoming from me also.
