### ISSUE TITLE
[@wordpress/scripts][rtlcss-webpack-plugin] Some internal modules are deprecated.

### ISSUE THREAD

**Issue by stein2nd** [WordPress/gutenberg#62007]
### Description

npm warn deprecated core-js@2.6.12:
core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

### Step-by-step reproduction instructions

1. After deleting the folder 'node_modules' and file 'package-lock.json', run 'ncu', 'ncu -u' and 'npm install -force' in turn.
2. Run 'npm ls <module names>' for each of the module names listed in the warn warning presented by npm.

### Screenshots, screen recording, code snippet

![Pasted Graphic](https://github.com/WordPress/gutenberg/assets/531628/dc887a61-1c64-4c8f-91f8-ce09da8c9fb6)

## System:
 - OS: macOS 14.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 24.13 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 22.2.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.22 - /usr/local/bin/yarn
 - npm: 10.8.0 - ~/.nodebrew/current/bin/npm

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by gziolo** [comment]
I'm working on a fix:
- https://github.com/WordPress/gutenberg/pull/68201
