### ISSUE TITLE
Media & text block: The featured image is output in the wrong place if the block has a nested Media & text block.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#62023]
### Description

If you have a media & text block that:

1. Has the featured image option enabled
2. Has the media on the right
3. Has a media & text block inside the content area

Then the featured image is printed in the wrong position in the markup on the front.
The markup that is supposed to be updated with the featured image  prints and empty `<img>` tag.

### Step-by-step reproduction instructions

1. Activate Gutenberg trunk.
2. Create a new post and add a featured image.
3. Insert a media & text block.
4. Enable the featured image.
5. Enable the option to position the media on the right.
6. Now insert another media & text block in the first media & text block. It doesn't matter if this block has any content or has a media selected.
8. View the front of the website, and compare the result in the editor and front.
9. View the source code to see if the outer media & text block also prints an empty `<img>` tag.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Adding to 6.6 since this impacts a feature for the release (using featured image in media & text block)
