### ISSUE TITLE
Gutenberg - looks like issue #55493 is back?

### ISSUE THREAD

**Issue by tomandersen** [WordPress/gutenberg#62037]
### Description

Is this happening again? I have this exact problem as https://github.com/WordPress/gutenberg/issues/55493  on Version 17.4.1 Safari desktop, and WordPress 6.5.3. Only on safari desktop, and toggling the PDF "Show inline embed " OFF fixes the problem.

Its an easy problem to duplicate. 

### Step-by-step reproduction instructions

1 Make page
2 Add PDF
3 Enable inline
4 Look at with Safari on desktop - safari hangs

### Screenshots, screen recording, code snippet

<img width="1209" alt="image" src="https://github.com/WordPress/gutenberg/assets/221405/29f22544-2e45-4407-8c81-85f03368fe16">
It hangs the safari PDF page completely. 

### Environment info

Safari Version 17.4.1 desktop, and WordPress 6.5.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by SantosGuillamot** [comment]
I am unable to reproduce the issue. I tested it with Safari 17.5 and 6.5.3 with and without the latest version of Gutenberg and it seems to work fine in both cases.

Maybe @DAreRodz can help here as he worked on [the pull request to fix it](https://github.com/WordPress/gutenberg/pull/55667) the first time.

**Comment by DAreRodz** [comment]
I followed the steps with the same versions as Mario, and couldn't reproduce the issue either...

When we did the previous fix, it seemed to be a bug in Safari 17.0. Could it be something specific to Safari 17.4.1? 🤔

**Comment by DAreRodz** [comment]
Hey @tomandersen, another question: Where is this problem happening? On the front end (the published page) or in the editor? Asking because there is [this similar bug](https://github.com/WordPress/gutenberg/issues/62120) that can actually be reproduced in the editor (with the difference that the editor doesn't seem to crash).

**Comment by annezazu** [comment]
@tomandersen I'm going to close this out due to a lack of response and lack of ability to replicate. Thank you for opening it though and **please** comment back if you can reproduce so we can track it down.
