### ISSUE TITLE
Update alt text decision tree links to be translatable

### ISSUE THREAD

**Issue by joedolson** [WordPress/gutenberg#62038]
### Description

In WordPress 6.6, the core alt text decision tree links will become translatable, so that translators can provide a link to the W3C WAI documentation in their own language, when it exists. 

[Locations where this link is referenced in Gutenberg](https://github.com/search?q=repo%3AWordPress%2Fgutenberg+https%3A%2F%2Fwww.w3.org%2FWAI%2Ftutorials%2Fimages%2Fdecision-tree&type=code)

[Relevant trac ticket 60975](https://core.trac.wordpress.org/ticket/60975)

### Step-by-step reproduction instructions

No reproduction steps relevant; this does not change anything in default behavior.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I removed the milestone from this issue because it will be automatically applied when the PR that resolves this issue is merged.

**Comment by narenin** [comment]
@joedolson I am working on this.

**Comment by colorful-tones** [comment]
@narenin, please attach and/or reference a pull request for this when you have a moment. Even if it is still a Draft. Thanks for working on this!

**Comment by narenin** [comment]
@colorful-tones Yes sure, it's done please check.

https://github.com/WordPress/gutenberg/pull/62076

**Comment by t-hamano** [comment]
Fixed by #62076
