### ISSUE TITLE
Media & text block: When the media is on the right, the media position of a nested block does not work

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#62047]
### Description

This happens on WordPress 6.5.3 with and without Gutenberg active.
I have not tested with older versions of WordPress.

When you add a Media & Text block and set the media position to the **right** with the toolbar setting, and then insert a second media & text block in the block's content area: Then the media position option in the **second** media & text block does not work.

 -The media **starts** on the right side, but the default for the block is to position the media on the left, so the expectation is for the media to start on the left side even if it is nested.
- When using the media position option, the button looks activated, but the content area and media area does not switch places. Not in the editor or on the front.

### Step-by-step reproduction instructions

Insert a Media & Text block.
Set the media position option in the block toolbar to the right.
Insert a second Media & Text block inside the first, and try to set its media position.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by amitraj2203** [comment]
Hi @carolinan, I have created a [PR](https://github.com/WordPress/gutenberg/pull/62184) for this issue.

Thank You
