### ISSUE TITLE
Interface: remove no longer necessary complementary area small header

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#62067]
### Description

The ComplementaryAreaHeder component renders a [small header](https://github.com/WordPress/gutenberg/blob/d990957dd5dcd13131feadacbdebe47ea627eec9/packages/interface/src/components/complementary-area-header/index.js#L27-L34) that is only shown on small screens.

The small header only contains:
- A `smallScreenTitle`, if provided.
- The X close toggleButton.

To my understanding, [the original intent](https://github.com/WordPress/gutenberg/blob/486a38168d6a69babd3e86bf2892b6108042e89b/packages/interface/src/components/complementary-area/README.md#smallscreentitle) was to hide the normal header on small screens and show the small header instead.

However, this appears to be broken as _both_ headers are shown at the same time. 

As far as I can tell, a `smallScreenTitle` is passed only in two places:

1
[In the Styles panel](https://github.com/WordPress/gutenberg/blob/d990957dd5dcd13131feadacbdebe47ea627eec9/packages/edit-site/src/components/global-styles-sidebar/default-sidebar.js#L34), where the small header just repeats the title of the normal header. Screenshot:

![trunk](https://github.com/WordPress/gutenberg/assets/1682452/e35c0dc9-c921-4ad1-8881-d2b029c9435a)

Same happens in WordPress 6.5, 6.4 so this appers to be a long standing issue. In 6.3 there's no `smallScreenTitle` passed. Screenshots:

WordPress 6.5

![6 5](https://github.com/WordPress/gutenberg/assets/1682452/f5359265-fc29-4e92-a394-78e684131876)

WordPress 6.4

![6 4](https://github.com/WordPress/gutenberg/assets/1682452/85910416-fe55-4ab7-aeae-8beb4fb9269d)

WordPress 6.3

![6 3](https://github.com/WordPress/gutenberg/assets/1682452/b324e49b-730c-47b2-834e-0a09157758c2)

2
The other instance where `smallScreenTitle` is passed is [in the plugin sidebar header of the Post editor](https://github.com/WordPress/gutenberg/blob/d990957dd5dcd13131feadacbdebe47ea627eec9/packages/editor/src/components/plugin-sidebar/index.js#L92). Install a plugin that adds its own sidebar to the editor e.g. Yoast SEO to see it. 

In this case, the small header shows the post title. However, the post title is now already shown in the editor top bar so this appears to be useless now. Screenshot:

![Screenshot 2024-05-28 at 15 05 27](https://github.com/WordPress/gutenberg/assets/1682452/c8c86bd0-c10a-4d01-9abe-699227e0b38c)

Unless I'm missing something, this 'small header' appears to be unnecessary now. Instead of fixing the layout that shows both headers, the small header should be removed.

## Additional considerations

On small screens, some buttons of the normal header are hidden with CSS `display: none`. As such, there is no access to some important editor features.

In the Styles panel, the buttons highlighted in the screenshot below are hidden. Users can't access the Style Book, the Revisions, and the More button. I'd think only the Style Book should be hidden.

![Screenshot 2024-05-28 at 14 22 56](https://github.com/WordPress/gutenberg/assets/1682452/cd107fe3-6f67-4936-b8a9-535bb5303d26)

In the Post editor plugin panel, the Pin / Unpin button is hidden. Users can't pin or unping a plugin sidebar. Screenshot:

![Screenshot 2024-05-28 at 14 37 25](https://github.com/WordPress/gutenberg/assets/1682452/666ba0ed-b7d5-4f4f-8b6c-cb0818987312)

Lastly, the controls in the header should also take into account the 'Show button text labels' preference. When the buttons show visible text they take much more horizontal space. In this case, it would be worth considering to render the buttons in a 'subheader' as proposed on https://github.com/WordPress/gutenberg/issues/61761#issuecomment-2133540975

### Step-by-step reproduction instructions

- Emulate a viewport with smaller than 782 pixels via your browser dev tools, e.g. for an iPad Mini.
- Go to the Site Editor > Styles
- Observe the Styles panel shows two headers with the same title 'Styles'.
- Observe the Style Book, Revisions, and More buttons are not shown.
- Install a plugin that adds its own sidebar to the Post editor e.g. Yoast SEO.
- Go to the Post Editor > Options > Plugins > click Yoast SEO
- Observe the Yoast SEO sidebar shows two headers:
  - The 'small header' shows the post title and the close button. However, the post title is already shown in the editor top bar.
  - The normal header shows the Plugin name.
  - Observ ethe pin / unpin button is hidden so that users can't pin or unpin the plugin sidebar.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by afercia** [comment]
Looking back into this old issue, it appears it's still on latest trunk. Screenshots of the current situation:

![Image](https://github.com/user-attachments/assets/f2f212dd-f2a9-4d4c-ab86-d1eb92462a67)


I see there's a PR that aims to solve this issue at https://github.com/WordPress/gutenberg/issues/62067 and some conversation there on whether to remove the `smallScreenTitle` prop without deprecation. I'd vote for just removing it.

See also https://github.com/WordPress/gutenberg/issues/64095 for other panel headers.

@t-hamano how can I help https://github.com/WordPress/gutenberg/pull/64474 move on? Would you need any help?

**Comment by afercia** [comment]
One more example of the duplication, when editing a template. Notice the small header doesn't provide the _edited object type_ label added to the DocumentBar in https://github.com/WordPress/gutenberg/pull/65170 which is one more good reason to remove it IMHO.

![Image](https://github.com/user-attachments/assets/543f43a1-078d-41ca-9432-8be7098b98fe)

**Comment by t-hamano** [comment]
> how can I help https://github.com/WordPress/gutenberg/pull/64474 move on? Would you need any help?

I have resolved the conflict in #64474. Could you test this PR?
