### ISSUE TITLE
Inspector: Polish "Link" button / dialog for static homepage 

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#62065]
Here's the Link button / dialog for regular pages:

<img width="507" alt="Screenshot 2024-05-28 at 13 24 13" src="https://github.com/WordPress/gutenberg/assets/846565/6df80c1c-6846-4e01-b08a-60e6cc48e8c9">

Here it is for a static homepage:

<img width="560" alt="Screenshot 2024-05-28 at 13 23 58" src="https://github.com/WordPress/gutenberg/assets/846565/dfee2f06-0277-406c-98a1-9ef03b3787cd">

The button label shows the slug, but the dialog shows only the TLD with no edit-ability. In the case of the homepage, there's very little value in allowing users to change the slug, and it could lead to confusion.

* Should the Link row be hidden entirely for the static homepage?
* Or should it simply list the TLD as an externallink?

<img width="270" alt="Screenshot 2024-05-28 at 13 28 17" src="https://github.com/WordPress/gutenberg/assets/846565/650cefb9-fc1b-4198-a127-e2a7913f0ad4">

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster,

I like the option "Or should it simply list the TLD as an externallink" but the homepage URL may be huge and may not fit a row. Maybe we show the link until a certain number of chars that fit, and after that we show "Homepage" with the link symbol and linking to the homepage. Would that work?

**Comment by jameskoster** [comment]
@jorgefilipecosta there's a PR to unify the behavior of these buttons here: https://github.com/WordPress/gutenberg/pull/61954. It's probably okay if they wrap for now, we can apply unique treatments to specific buttons later.

> and after that we show "Homepage" with the link symbol and linking to the homepage.

There's a separate PR to indicate the homepage here: https://github.com/WordPress/gutenberg/pull/62071, so we probably don't need the extra affordance in the Link row.

> "Or should it simply list the TLD as an externallink"

Maybe we start just with this?

**Comment by colorful-tones** [comment]
With WordPress 6.6 Beta 1 targeted to be released in less than a day - Editor Triage Leads will move this to `Punted to 6.6.1` for now.

**Comment by jorgefilipecosta** [comment]
Hi @colorful-tones, I think this fix can still go with WordPress 6.6, the fact that for frontpages we are showing the wrong link can be seen as a bug.

**Comment by colorful-tones** [comment]
> I think this fix can still go with WordPress 6.6, the fact that for frontpages we are showing the wrong link can be seen as a bug.

Thanks for clarifying @jorgefilipecosta. I've triaged this back to the ToDo column. Does this still need the `Needs design feedback` label, as I see you have an active pull request already in progress, and it seems odd that it would classified as a Bug and an Enhancement, but I'm probably being too stringent. 😅
