### ISSUE TITLE
Block Variations: Support dot notation in `isActive` string array

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#62068]
## What problem does this address?
Block variations support an `isActive` property which can be either a function, or an array of strings (`string[]`), documented [here](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/#using-isactive). _tl;dr:_ Given a block instance, that variation is used to determine which variation is currently active: If `isActive` is a function, it is given the block instance's attributes and the variation's attributes as arguments. It will return `true` if the block instance matches the variation. The `string[]` version of `isActive` is thought of as a shorthand of the above, where all items in the array are attribute names that will be compared.

As documented [here](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/#caveats-to-using-isactive) and [here](https://github.com/WordPress/gutenberg/issues/41303), it's possible that multiple variations' `isActive` criteria match a given block instance, which can lead to the wrong variation being determined to be active.

There's a [potential fix](https://github.com/WordPress/gutenberg/pull/62031) that solves this problem by choosing the matching variation with the highest specificity (i.e. number of items in the `isActive` array), but that only works if all matching variations have `isActive` _arrays_ rather than functions.

One notable case where it's impossible to use an array for `isActive` is when an attribute is an object, and only one of its properties must be compared to determine if its active, for example: https://github.com/WordPress/gutenberg/blob/fe40df67ad88740d83c4c60735603d09a0ca5d55/packages/block-library/src/query/variations.js#L41-L59

## What is your proposed solution?

If we allow dots as ["property accessors"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_accessors) in `isActive` array items, we wouldn't need to resort to `isArray` functions in cases like the above. The example could instead be rewritten as

```js
isActive: [ 'namespace', 'query.postType' ]
```

**Comment by ockham** [comment]
FYI @ntsekouras @tjcafferkey @gziolo

**Comment by ockham** [comment]
We have the [`getValueFromObjectPath` util function](https://github.com/WordPress/gutenberg/blob/406c28a371267756b289a029d1ae7f35d9db9c1f/packages/blocks/src/store/utils.js) that should help with this.

**Comment by ntsekouras** [comment]
I think this is an enhancement that could be done independently from the specificity issue you mention. The `isActive` API as a function is still useful and can accommodate more complex cases ([example in template parts](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/template-part/variations.js)).
