### ISSUE TITLE
Consider a shortcut key for "group"

### ISSUE THREAD

**Issue by alexstandiford** [WordPress/gutenberg#62097]
## What problem does this address?

As I'm using full site editing more, I find that a very common operation is to select a collection of blocks, and then group them together. Coming from a background of design tools like Figma and Illustrator, I keep trying to press CMD+G to group the blocks after selecting them.

## What is your proposed solution?

Add a new shortcut that uses CTRL/CMD+G to group the selected blocks with a group block. _maybe_ even do CTRL/CMD+Shift+G to ungroup, although that's much less common in my experience.

**Comment by t-hamano** [comment]
Thanks for the report.

That shortcut was added in #46972. However, for accessibility reasons, it currently only works when two or more blocks are selected.

**Comment by alexstandiford** [comment]
Got it, thanks for the response, and sorry I missed that!

In that case maybe this is a bug report, because when I hit CTRL+G in Firefox it doesn't do that. Instead it pulls up Firefox's search again functionality.

Here's what I'm doing (in Firefox, naturally)

1. Open the block editor's "document overview" on the right sidebar
2. Select a few blocks
3. Press CTRL+G

Instead of grouping the items, it does Firefox's default action.

**Comment by t-hamano** [comment]
I tested it in Firefox and it seems to work fine.

Do you have the Gutenberg plugin enabled? This feature was added in Gutenberg version 18.4. You should also be able to see it in the upcoming WP6.6 release.

**Comment by alexstandiford** [comment]
Oh. That's it. I didn't realize this was so new that it wasn't in core. Sorry about that! Thanks!
