### ISSUE TITLE
Styles missing with custom fields panel active

### ISSUE THREAD

**Issue by gyurmey2** [WordPress/gutenberg#62091]
### Description

The nighly version causes a regression to the state described in issue #61565

### Step-by-step reproduction instructions

1. Edit a page/post
2. From the preferences panel enable the custom fields and save

### Environment info

WP: 6.5.3
Theme: TT4
Gutenberg: 18.6.-nightly (18.6.20240528)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
cc @andrewserong, @tellthemachines

**Comment by andrewserong** [comment]
Thanks for the ping! Looks like it was to do with the recent change to the global styles rules. Fix here: https://github.com/WordPress/gutenberg/pull/62121
