### ISSUE TITLE
Inserting a new block should scroll to that block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#621]
Whenever you insert a new block using the header + button, we ought to scroll to the bottom so the new block is in view.

**Comment by jasmussen** [comment]
Actually shouldn't it insert the block where the caret is?

**Comment by mtias** [comment]
Good point. We should focus the viewport on the newly created block, regardless of where it is inserted.

**Comment by jasmussen** [comment]
See also conversation in https://github.com/WordPress/gutenberg/pull/565#issuecomment-300143320

Current issue: If you insert a text block (any text, including heading, list, etc.), it scrolls to the inserted block. Good! If you insert a block that doesn't have Editable, like embed or image, it doesn't scroll to the block. Let me know if I should ticket this separately.

A thought from @aduth:

> It might be that TinyMCE is scrolling the page when it initializes, in which case we should try to disable that default and implement a consistent approach across all blocks.

A comment from @iseulde:

> Saw this the other day: https://github.com/tinymce/tinymce-dist/blob/4.6.0/changelog.txt#L6
