### ISSUE TITLE
Site Editor: The sidebar becomes inaccessible on mobile when editing Templates, Pages, and Patterns

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#62106]
### Description

When you try to access the Templates and Pages sections of the Site Editor on mobile in Gutenberg 18.4.1, the Site Editor sidebar becomes inaccessible. This is not the case in WordPress 6.5, so I would consider this a regression. The only way to get to other Site Editor sections is to back all the way out to the WP Admin and reaccess the Site Editor. See the video for a complete walkthrough.

~~The Patterns section has a separate but similar issue, but I will open a dedicated issue for that.~~

Given that https://github.com/WordPress/gutenberg/pull/60302 will add an "Add new..." button for patterns in 18.5, the Patterns section exhibits the exact same issue as Templates and Pages.

### Step-by-step reproduction instructions

1. Use TT4 and Gutenberg 18.4.1
2. Navigate to the Site Editor and then to the Pages or Templates section
3. Reduce the browser width to a mobile-sized view
4. Notice that there is no way to access the Sidebar. The only way to get to other Site Editor sections is to back all the way out to the WP Admin and reaccess the Site Editor.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/4832319/5a760eaa-0339-4172-8f16-42abcddc4b0b

### Environment info

- WordPress 6.5
- Gutenberg 18.4.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
This duplicates https://github.com/WordPress/gutenberg/issues/62878 and I believe both are fixed.
