### ISSUE TITLE
Make strings consistent, lower vs. Upper case

### ISSUE THREAD

**Issue by Presskopp** [WordPress/gutenberg#6210]
I can't remember if I brought this up before somewhere. I made a list a long time ago and just found out it's still immanent:

lower vs Upper case:

block(s) vs. Block(s)

strings are there 2 times:
Convert to blocks vs. Convert to Blocks 
Editor toolbar vs. Editor Toolbar
Featured image vs. Featured Image

audio vs. Audio
embed vs. Embed
image vs. Image

Not sure, could be false positives in here

**Comment by karmatosed** [comment]
As casing depends on context, could you perhaps provide a little more insight into each of these? For example, where do you see them in the interface? Having a list would of ones to work through would be great. I am happy to work through a list like that.

**Comment by Presskopp** [comment]
I found these translating and not in backend. I'll see what I can do, but can't promise antyhing, sorry.

**Comment by Soean** [comment]
1. `Fix Toolbar to Top`
<img width="232" alt="bildschirmfoto 2018-05-22 um 22 20 13" src="https://user-images.githubusercontent.com/695201/40387955-74ffc826-5e0e-11e8-8e05-a86b1cca99ed.png">

2. `Pin to toolbar` / `Unpin from toolbar`

<img width="164" alt="bildschirmfoto 2018-05-22 um 22 23 22" src="https://user-images.githubusercontent.com/695201/40388082-cf560434-5e0e-11e8-9b89-32cbb460dc33.png">

3. `Editor Toolbar` / `Editor toolbar`

<img width="868" alt="bildschirmfoto 2018-05-22 um 22 26 08" src="https://user-images.githubusercontent.com/695201/40388393-b2831b5c-5e0f-11e8-8c74-d6e2afb640eb.png">

4. `Block Toolbar`

<img width="459" alt="bildschirmfoto 2018-05-22 um 22 36 19" src="https://user-images.githubusercontent.com/695201/40388744-97d53672-5e10-11e8-923f-15fbb84ad648.png">

**Comment by Soean** [comment]
1. Convert to Blocks
<img width="356" alt="bildschirmfoto 2018-05-22 um 22 46 03" src="https://user-images.githubusercontent.com/695201/40389213-05ea0da8-5e12-11e8-8856-3b7cb736c03a.png">

2. Convert to blocks

<img width="268" alt="bildschirmfoto 2018-05-22 um 22 44 07" src="https://user-images.githubusercontent.com/695201/40389221-0b62595c-5e12-11e8-917d-8068623b4964.png">

**Comment by Soean** [comment]
`Featured image` / `Featured Image`
<img width="715" alt="bildschirmfoto 2018-05-22 um 22 54 51" src="https://user-images.githubusercontent.com/695201/40389841-b17965aa-5e13-11e8-8c19-88afc6ac351d.png">

**Comment by kristastevens** [comment]
Per the [brand guide](https://dotcombrand.wordpress.com/style/), we default to sentence case for text, including headings and buttons. I recently had a conversation with @mattmiklic to mine his historical memory as someone deeply involved in design from the early days of WP.com, and he confirms this.  Anything that isn't, such as the instances noted above, "Fix Toolbar to Top," "Convert to Blocks" plus all the menu items and buttons, "Show Block Settings," etc., should be in sentence case, e.g., "Fix toolbar to top."  "Edit as HTML" is correct as it is.

**Comment by chrisvanpatten** [comment]
It would be great to have that documentation available on .org, since this is a .org project and not a .com project :)

**Comment by aduth** [comment]
Previously: #4325

**Comment by karmatosed** [comment]
@chrisvanpatten there is a style guide for writing due to be worked on for WCEU so totally something we can then have included.

**Comment by aduth** [comment]
>@chrisvanpatten there is a style guide for writing due to be worked on for WCEU so totally something we can then have included.

@karmatosed Did this happen?

**Comment by karmatosed** [comment]
The style guide for writing didn't happen. Let's see about getting that done sooner over later. I'll work on that thanks for reminder.

**Comment by Soean** [comment]
Copy guidelines were merged in #7588

**Comment by aduth** [comment]
Can this issue be closed then? What actionable tasks remain?

**Comment by mtias** [comment]
Closing. If there are remaining things to address let's open specific issues.
