### ISSUE TITLE
Typography: Font size dropdown control interferes with dimension controls

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#62131]
### Description

When a theme declares a number of font sizes so the font size control is displayed as a dropdown,
and dimension controls (padding, margin) are visible in block editor sidebar,
the font size dropdown list interferes with dimension controls (CSS `z-index`, positioning issue).

### Step-by-step reproduction instructions

1. Add a new font size to Twenty Twenty-Four theme's `theme.json`. This will cause font size control in block editor to display as a dropdown.
2. In block editor enable dimension controls for a block.
3. When dimension controls are displayed, try to select a font size from the dropdown. You can see the dropdown list covered by the dimension controls.

### Screenshots, screen recording, code snippet

![gutenberg-font-control-issue](https://github.com/WordPress/gutenberg/assets/2456735/480b4c98-0699-46e8-8b1c-b8797f630bd2)

### Environment info

- WordPress 6.5.3
- Gutenberg 18.4.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This issue has already been fixed in #61937 and will be reflected in Gutenberg version 18.5.

**Comment by webmandesign** [comment]
Thank you for update and sorry for duplicate.
