### ISSUE TITLE
Ability to control editor preview breakpoints

### ISSUE THREAD

**Issue by kubiqsk** [WordPress/gutenberg#62139]
There should be a way how to control preview breakpoints in editor.

![wp-preview-breakpoints](https://github.com/WordPress/gutenberg/assets/20414087/ea8f7edb-d7eb-402d-8493-c9d97ac3dffd)

We should be able to add / remove / change

Ideally some UI in admin ofc, but also some hook would be enough.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; I agree, this would be great to implement. 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/21235. Feel free to comment in there with your or [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
