### ISSUE TITLE
Site Editor: Unwanted top margin added to the first block inside flow layout container

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#62148]
### Description

This must have been introduced recently. It only happens when the Gutenberg plugin is activated and seems to happen only in the site editor. 

Usually, when the layout is constrained, the top margin is removed from the first block in a container.

![CleanShot 2024-05-30 at 16 03 19@2x](https://github.com/WordPress/gutenberg/assets/908665/6f79f71a-2525-4500-9fb5-2e026754d30a)

However, if the container has the flow layout, the top margin doesn't get removed.

![CleanShot 2024-05-30 at 16 06 51@2x](https://github.com/WordPress/gutenberg/assets/908665/06b13d30-1a93-4553-999b-e1ccea4378a0)

### Step-by-step reproduction instructions

1. Open the site editor
2. Add a group block
3. Add a block in the group block
4. Set the layout of the group block to flow(unconstrained).
5. See the gap between the container and the first block in it.

### Environment info

- WP 6.5.3
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tellthemachines** [comment]
Hmm, looks like there's an extra curly bracket being output in the global styles for the site editor:

<img width="631" alt="Screenshot 2024-05-31 at 9 54 48 AM" src="https://github.com/WordPress/gutenberg/assets/8096000/a841e536-a8e2-4d9d-a017-652e5f1fb416">

Edit: yeah this was introduced by #60715. I'll put up a quick fix!
