### ISSUE TITLE
Update typography variations UX to resemble colors flow

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#62156]
Typography variations are essentially the same concept as the color variations, but the UX to apply them is disjointed. Much like how [color variations were updated to resolve to a separate view within the color palette](https://github.com/WordPress/gutenberg/pull/61334), I proposed that the typography variations are as well. Another benefit is that you can access the individual fonts applied within each typography variation. 

### Visual
![CleanShot 2024-05-30 at 15 33 08](https://github.com/WordPress/gutenberg/assets/1813435/aec77d89-7fa3-4f63-88fb-684292b2dfec)

### Details 

1. The "Typeset" term could potentially be "Font set", "Font pack", or "Font pairing"—or something else. Note that there may be more than two fonts applied within each typography variation (as a typography variation is _any_ application of typographic choices). 
2. If there are no typography variations, then the "Typeset" UI would not render (same as colors). 
3. The label for the typeset is the typography variation label (as it is today).

**Comment by richtabor** [comment]
For reference, this is the Colors view: 

![CleanShot 2024-05-30 at 15 32 22](https://github.com/WordPress/gutenberg/assets/1813435/35c58113-70fb-4f40-879e-379b3a749577)

**Comment by jasmussen** [comment]
This seems worth trying as we continue to refine this interface. I'd pair this with (though not block on) updates to the Styles section in the site editor, receiving a little love as well.
