### ISSUE TITLE
Feature Request: remove block per paragraph

### ISSUE THREAD

**Issue by ash-f** [WordPress/gutenberg#6215]
Block per paragraph isn't efficient or intuitive.
Most of page builders does not use this structure.
Text block should be capable of multiple paragraph like classic editor or widgets.

**Comment by jasmussen** [comment]
Closing as duplicate of https://github.com/WordPress/gutenberg/issues/3629, https://github.com/WordPress/gutenberg/issues/5283 and https://github.com/WordPress/gutenberg/issues/179.
