### ISSUE TITLE
Publish flow: changing date/time doesn't update in both places

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#62150]
In testing this PR for 6.6 https://github.com/WordPress/gutenberg/pull/62070 I noticed a few bugs including that changing the date/time under Publish doesn't reflect properly when you switch to the Status view with the more compact TimePicker.

To replicate, change date/time under Publish then open status to see the scheduled doesn't reflect the time. 

https://github.com/WordPress/gutenberg/assets/26996883/f8d1bc4e-5de6-4f0d-afee-3ba089964874

^ Note this shows two bugs I'm about to open cc @ntsekouras

**Comment by ntsekouras** [comment]
Sorry about missing this.. I only tested the syncing the other way around. Fix is [here](https://github.com/WordPress/gutenberg/pull/62165).
