### ISSUE TITLE
Consider possibility of change font type in aeah block

### ISSUE THREAD

**Issue by castellote** [WordPress/gutenberg#6216]
Consider possibility of change font type in aeah block or almost in each page

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jasmussen** [comment]
Good idea. Definitely something for the Customization folks to think about.

However for now, I'm closing it as a feature for the next iteration of the editor (change across all blocks), and noting that there are duplicate aspects (per-block) in #5775 and #https://github.com/WordPress/gutenberg/issues/5777.
