### ISSUE TITLE
Feature: Allowing password-protected posts to also have 'sticky' attribute

### ISSUE THREAD

**Issue by assad-ebrahim-uk** [WordPress/gutenberg#62173]
Is it possible to make password-protected posts ALSO sticky?  (Feature request if not already possible)

After trial and error and googling to find workarounds, I believe the feature is not possible (kindly provide the method if it is possible!)

Current behaviour:  One password protected (PP) post can have sticky attribute added and this appears at the top of the main page.
However, if a second post is PP with a different password, then the original PP post appears to lose its sticky attribute silently.

Use case for the desired feature : Having the first post on the main page be reference material for an internal group (and therefore password protected).

Related: See #19746 where a non-graceful failure was raised but the feature was not requested.

Thanks

**Comment by jordesign** [comment]
Hi @assad-ebrahim-uk  - this kind of functionality is something that would have impact in WordPress core itself (beyond just the editor. So I'd recommend raising it as a feature request in Core Trac - where it could be looked at.
https://core.trac.wordpress.org/

**Comment by assad-ebrahim-uk** [comment]
Appreciate the steer, thanks!
