### ISSUE TITLE
Parser: applyBlockValidation revalidating original block instead of fixed

### ISSUE THREAD

**Issue by tjcafferkey** [WordPress/gutenberg#62176]
When initially parsing and loading blocks we attempt to validate their parsed attributes and apply auto-fixes when invalid, before attempting to validate again after the fixes have been applied. This is done after we get a new raw block back after a round of fix attempts, which we can revalidate.

However, looking at this [section of code](https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/parser/index.js#L167-L183) it appears as though we are revalidating the original `unvalidatedBlock` instead of `fixedBlock` during the second execution of `validateBlock()`.

It looks to me like on the second run of `validateBlock()`, we should be passing `fixedBlock` as the first param instead.

**Comment by Mamaduka** [comment]
It's probably a regression after #37763. cc @dmsnell
