### ISSUE TITLE
Inserter: after adding a block from the inserter, not all blocks are shown and a loading state is in place

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#62192]
@ellatrix while[ testing your PR](https://github.com/WordPress/gutenberg/pull/62169) in Playground, I noticed that if I add a block from the inserter, like a button block, it seems to cause a loading state to appear in the inserter rather than all blocks. If I then close the Inserter and reopen it again, it shows the desired effect:

https://github.com/WordPress/gutenberg/assets/26996883/857f8538-bedb-4cc6-bacc-4cecb870fbc3

**Comment by richtabor** [comment]
Looks like it's from the search filtering results.

**Comment by t-hamano** [comment]
This may be related to the fact that `networking` support is disabled by default in Playground.

[Query API | WordPress Playground](https://wordpress.github.io/wordpress-playground/query-api#available-options)

Does this issue reoccur with `networking` enabled?

https://playground.wordpress.net/?networking=yes

**Comment by ellatrix** [comment]
Yes, I think this is because networking is disabled

**Comment by t-hamano** [comment]
I think this is a problem with the Playground settings, so I would like to close this issue. If you experience problems in other environments, please feel free to reopen it.
