### ISSUE TITLE
Missing documentation for `compose`

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#6220]
In [data/README.md](https://github.com/WordPress/gutenberg/blob/3a5dd2dc2b1c993682792d7dfe60e55b9dccbae5/data/README.md) the line "higher-order component composition" is linked to https://github.com/WordPress/gutenberg/tree/master/element#compose. But there is no section for `compose`. Should we add a section or update the link to point to somewhere else?

**Comment by gziolo** [comment]
Yes, let’s add it because it is widely used to wrap components with Higher-Order components.

**Comment by brandonpayton** [comment]
I took a look and thought I'd just add documentation for members of the element API, but that would likely duplicate our inline docs. Do we generate anything from our inline documentation or have any vision for what that should look like?

**Comment by ocean90** [comment]
No need to duplicate the inline docs. What's missing is an example and an explanation on how and when to use `compose`, similar to data/README.md.

**Comment by gziolo** [comment]
`compose` is an alias to [flowRight](https://lodash.com/docs/4.17.5#flowRight) from Lodash. It's coming from FP world and allows to compose any number of functions. An example that better illustrates it for 2 functions:

```js
const compose = ( f, g ) => x
    => f( g( x ) );
```

**Comment by gziolo** [comment]
> Do we generate anything from our inline documentation or have any vision for what that should look like?

Not yet, we only generate [Gutenberg handbook](https://wordpress.org/gutenberg/handbook/) from `docs/folder`. I think it was discussed on one of the Core JS weekly meetings, but I didn't see any actions afterward. @atimmer or @omarreiss, what was the plan regarding that? We should start working on it pretty soon to improve discoverability.

**Comment by atimmer** [comment]
@herregroen is working on parsing JSDoc and having the ability to put it into https://developer.wordpress.org
