### ISSUE TITLE
Slide Share Block

### ISSUE THREAD

**Issue by NewYorkerLaura** [WordPress/gutenberg#62203]
### Description

On the latest version of WordPress on a self-hosted site the Block for SlideShare embed is not working. Any attempt to put in the URL of the slide as instructed fails. Message states "Sorry, this content could not be embedded."  even though it is a valid url from SlideShare
 
https://www.slideshare.net/slideshow/the-art-of-the-pitch-wordpress-relationships-and-sales/269457571

Interestingly, previous slides that I have embedded are still visible. I can even duplicate those blocks. However I can't switch out the URL, the same "Sorry, this content could not be embedded." message happens if I attempt any replacement of the existing URL

I resorted to flipping to code view and embedding an iframe to get around the current blocker ( not ideal)

See this page for reference https://newyorkerlaura.com/wordpress-slide-decks/. first deck is an iframe all others are successful embeds using the SlideShare block that were done over a year ago.

### Step-by-step reproduction instructions

1. Select the Slide Share Block
2. Attempt to enter a slide share URL such as https://www.slideshare.net/slideshow/the-art-of-the-pitch-wordpress-relationships-and-sales/269457571
3. The block will not accept the valid URL 
<img width="816" alt="Screenshot 2024-06-01 at 2 43 12 PM" src="https://github.com/WordPress/gutenberg/assets/32318563/0aada927-47b0-4f22-9883-37fb862dd71b">

### Environment info

WordPress 6.5.3 running 2017 theme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting the issue. I've created a trac ticket for this as it seems to be the REST API that's returning a 404 error, and that's part of WordPress core - https://core.trac.wordpress.org/ticket/61349.

There's a chance it's an issue with slideshare rather than WordPress, so it might be worth reporting a problem on that side too.

**Comment by peterwilsoncc** [comment]
Slideshare have confirmed the oembed endpoint has been [effectively deprecated](https://core.trac.wordpress.org/ticket/61349#comment:4). 

I'll reopen this ticket for the purpose of removing the embed block variation, the associated code will be removed from WP-Dev in [WP#61349](https://core.trac.wordpress.org/ticket/61349)
