### ISSUE TITLE
dateI18n

### ISSUE THREAD

**Issue by rwrobe** [WordPress/gutenberg#6221]
## Issue Overview
Loading dateI18n from the date object in a component throws undefined error. The function, however, appears to be defined when entering it into the console (i.e., `wp.date.dateI18n( 'F j, Y' )` in the console gives the properly formatted date), which makes me think it's about loading order.

## Steps to Reproduce (for bugs)

1. Create a new block or component, loading the dateI18n object in the header, like so: 
`const { dateI18n } = wp.date;`
2. Reload the editor, look for dateI18n undefined error in console.

**Comment by aduth** [comment]
Have you defined `wp-date` as a dependency for your block/component's script?

**Comment by rwrobe** [comment]
Hi @aduth --

I have, here's the code:
```
/**
 * External dependencies
 */
const { _x, sprintf } = wp.i18n;
const { Component } = wp.element;
const { dateI18n } = wp.date;

/**
 * Internal dependencies
 */
import './editor.scss';

/**
 * Create an input field Component
 */
export default class Byline extends Component {
	render() {
		const bylineStart = sprintf( _x( '%s by ', 'e.g., March 2, 2018 by Arthur' ), dateI18n( 'F j, Y' ) );

		return (
			<small
				className={ 'byline noedit op-80' }>
				{ bylineStart }
				<strong><a href={ this.props.link } alt={ this.props.name } target={ '_blank' }>{ this.props.name }</a></strong>
			</small>
		);
	}
}
```

Thank you!

**Comment by aduth** [comment]
Can you share the code for registering / enqueueing your block?

**Comment by rwrobe** [comment]
@aduth Apologize for the delay. Here you go:
```
import './editor.scss';
import utils from './utils';
import { options } from '../package.json';

// - Register supported blocks.
options.supports.forEach( function( block ) {
	require( '../blocks/' + block + '/index.js' );
} );
```
I'm using package.json to specify the custom blocks I want loaded for a particular build from a "library" of blocks.

Thank you!

**Comment by rwrobe** [comment]
Adding `wp-date` as a script dependency in PHP solved this. 
```
wp_register_script(
				'editor-js',
				$this->plugin_url . 'dist/js/editor.min.js',
				array( 'wp-blocks', 'wp-date', 'wp-element' ),
				$this->timestamp( $this->plugin_url . 'dist/js/editor.min.js' )
			);
```
