### ISSUE TITLE
Data Views: Bulk toolbar covers other clickable buttons

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#62228]
### Description

The bulk toolbar in the data views appears to be full-width, with an invisible div capturing clicks of anything it overlays. This is notably visible if you scale the viewport just to such a size as to where the toolbar will cover the row of actions, as shown in this GIF:

![can't deselect](https://github.com/WordPress/gutenberg/assets/1204802/9aab852c-7f19-46c7-92e3-bb166c2ace91)

This is likely due to the bulk toolbar having an invisible element that's full-width:

![full width element](https://github.com/WordPress/gutenberg/assets/1204802/2266b101-f9d3-424e-90a2-7461d5754d8b)

### Step-by-step reproduction instructions

* Go to the site editor > templates
* Select one or more items so the bulk toolbar appears
* Scale the browser so the bulk toolbar sits at the same y coordinate as the ellipsis menu for an item in the grid

Observe that you now can't click any ellipsis menu items in the same coordinate.

### Environment info

Trunk plugin + nightly WP.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by jasmussen** [comment]
CC: @ntsekouras and @jameskoster as I think you worked on this.

**Comment by jameskoster** [comment]
cc @jorgefilipecosta. Setting width to `fit-content` and re-positioning the wrapper should fix.

Unrelated, but I'm seeing a regression on trunk; the toolbar is no longer fixed in position as you scroll.
