### ISSUE TITLE
Editing bound paragraph in post editor causes "Site Updated" message to appear

### ISSUE THREAD

**Issue by artemiomorales** [WordPress/gutenberg#62236]
### Description

In the post editor, if one modifies a block connected to post metadata via block bindings, a "Site Updated" notification displays when saving the post, which is incorrect.

First raised in https://github.com/WordPress/gutenberg/pull/61811 and a part of the [block bindings iteration](https://github.com/WordPress/gutenberg/issues/60956#issuecomment-2144790954) for WordPress 6.6.

### Step-by-step reproduction instructions

<details>
<summary>1. Register post meta by adding this snippet to your theme's functions.php</summary>

```php
add_action( 'init', 'test_block_bindings' );

function test_block_bindings() {
	register_meta(
		'post',
		'text_field',
		array(
			'show_in_rest'      => true,
			'single'            => true,
			'type'              => 'string',
			'default'           => 'default text value',
		)
	);
}
```

</details>

<details>

<summary>2. In the post editor, add a paragraph block bound to the custom field using the Code Editor</summary>

```
<!-- wp:paragraph {"metadata":{"bindings":{"content":{"source":"core/post-meta","args":{"key":"text_field"}}}}} -->
<p>Paragraph content</p>
<!-- /wp:paragraph -->
```

</details>
 
3. Press the Save button.
4. Notice that the "Site Updated" message appears, despite the fact that you made no site-wide changes.

### Screenshots, screen recording, code snippet

<img width="1238" alt="site-updated-bug" src="https://github.com/WordPress/gutenberg/assets/5360536/2aac3dce-23df-4a6e-817c-f95d45cd15e2">

### Environment info

- Gutenberg Release Candidate 18.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by SantosGuillamot** [comment]
The changes to trigger the save panel after editing post meta in a post have been reverted in [this pull request](https://github.com/WordPress/gutenberg/pull/63412). I guess this is not an issue anymore and we just have to ensure that whatever we build doesn't trigger this again, right?

I've opened [this new issue](https://github.com/WordPress/gutenberg/issues/63425) to gather all the context and make decisions before working on a new solution.

Should we close this one?

**Comment by artemiomorales** [comment]
> The changes to trigger the save panel after editing post meta in a post have been reverted in https://github.com/WordPress/gutenberg/pull/63412. I guess this is not an issue anymore and we just have to ensure that whatever we build doesn't trigger this again, right?

Yup, we can close this issue. And yes, we just need to make sure the "Site Updated" message doesn't get triggered with any new implementation.

> I've opened [this new issue](https://github.com/WordPress/gutenberg/issues/63425) to gather all the context and make decisions before working on a new solution.
> 
> Should we close this one?

Yes let's keep all the discussion in the new issue and close this one 👍
