### ISSUE TITLE
Support "Add Before" and "Add After" for list items

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#62244]
## What problem does this address?

Inserting a new List Item before the first item in a List Block isn't super intuitive right now. Our content providers use Add Before and Add After as their primary method of inserting blocks into existing content. However, it is currently missing from List Items.

![list-item](https://github.com/WordPress/gutenberg/assets/945157/96666bff-f86a-46ee-a8ac-af418abfc340)

## What is your proposed solution?
Include "Add Before" and "Add After" with list items

**Comment by talldan** [comment]
This is working when I tested:
![Screenshot 2024-06-04 at 10 24 23 am](https://github.com/WordPress/gutenberg/assets/677833/02fa6366-c835-4bf5-b51a-074daf89d02c)

Interesting that the option isn't showing for you @MadtownLems. Did you test on the latest version? Any plugins active?

**Comment by MadtownLems** [comment]
>> Did you test on the latest version? Any plugins active?

This is on 6.5.3 with no plugins.  I did, however, just test with latest Gutenberg active, and the Add Before is there. So I guess we just wait for that to make its way to Core.  Thanks for taking a look!

**Comment by talldan** [comment]
Ah yes, it might be something that will land in 6.6. I think this is the PR - [Set the 'defaultBlock' setting for Columns & List blocks](https://github.com/WordPress/gutenberg/pull/59196#top).

I did a quick test on WordPress trunk with the gutenberg plugin deactivated, and it does seem to be working.

Is it ok if we close the issue?

**Comment by Mamaduka** [comment]
We can close this. The enhancement will be included in WP 6.6.
