### ISSUE TITLE
Color style variations don't resolve CSS custom properties

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#62245]
When defining a color palette in `theme.json` it is possible to reference external colors by using CSS custom properties as follows:

```json
{
    "settings": {
        "custom": {
            "color": {
                "foo": "#39ab00"
            }
        },
        "color": {
            "palette": [
                {
                    "slug": "foo",
                    "name": "Foo",
                    "color": "var(--wp--custom--color--foo)"
                }
            ]
        }
    }
}
```

Doing this will resolve the colors correctly everywhere in the UI. However, this is not the case in the new design of style variations, which showcases the different color palettes defined in block theme style variations. There, they appear in greyscale. 

![CleanShot 2024-06-03 at 17 34 53@2x](https://github.com/WordPress/gutenberg/assets/20684594/dd3e0313-2d57-49e1-8735-6f9b33ef2226)

**Comment by fabiankaegy** [comment]
CC: @richtabor as I know you worked on this

**Comment by ndiego** [comment]
Given that Beta 2 will be released later today, the issue is not specifically related to 6.7 and no work has been done on this, are you comfortable punting to 6.8 @fabiankaegy. cc @colorful-tones

**Comment by fabiankaegy** [comment]
@ndiego sure  👍

**Comment by t-hamano** [comment]
I was not able to reproduce this issue. I made the following changes to Twenty Twenty-Four:

```diff
diff --git a/wp-content/themes/twentytwentyfive/theme.json b/wp-content/themes/twentytwentyfive/theme.json
index e43b5888..b294b5f2 100644
--- a/wp-content/themes/twentytwentyfive/theme.json
+++ b/wp-content/themes/twentytwentyfive/theme.json
@@ -2,12 +2,22 @@
        "$schema": "https://schemas.wp.org/trunk/theme.json",
        "version": 3,
        "settings": {
+               "custom": {
+                       "color": {
+                               "foo": "#39ab00"
+                       }
+               },
                "appearanceTools": true,
                "color": {
                        "defaultDuotone": false,
                        "defaultGradients": false,
                        "defaultPalette": false,
                        "palette": [
+                               {
+                                       "slug": "foo",
+                                       "name": "Foo",
+                                       "color": "var(--wp--custom--color--foo)"
+                               },
                                {
                                        "color": "#FFFFFF",
                                        "name": "Base",
```

As you can see, it's reflected correctly in the color palette.

![Image](https://github.com/user-attachments/assets/c81997c7-31f3-4b39-934c-ed7f6fc5cf57)

**Comment by fabiankaegy** [comment]
In 6.7 I am also unable to reproduce it now :) Thanks!
