### ISSUE TITLE
Group: Add support for shadows

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#62258]
While creating a block theme yesterday I hit a wall when trying to add a drop shadow to my header. I was surprised to learn that you can't currently set a Shadow on Group, Row, Stack or Grid blocks.

I searched around and can see that _Group_ was an item in https://github.com/WordPress/gutenberg/issues/57103 but it was left out of https://github.com/WordPress/gutenberg/pull/57982 as it needed more testing. Not sure if there's been any update since then? cc. @madhusudhand @vcanales

**Comment by madhusudhand** [comment]
One of the common issue with shadows for group block is overlaps. Shadow of a first group block is hidden behind the following group block due to stacking.

<img width="1300" alt="image" src="https://github.com/WordPress/gutenberg/assets/1935113/6fa48c91-ea2b-45eb-a7e0-bfc4d01264da">

Steps:
1. Activate a theme such as `Adventurer`
2. Navigate to global styles and apply shadow to group block

Since the shadow is now available in global styles (since Gutenberg 18.5, WordPress 6.6), it becomes a more common issue if the support enabled for group block. 
It is delayed until WordPress 6.7 which gives more time to observe the feedback and fix all issues.

**Comment by bgardner** [comment]
This morning, I was thinking about this and planned to create an issue. Thank you, @noisysocks, for addressing it first. While I understand there are some considerations when adding style support to the Group block, we need to work through them. The Group block is likely the most popular block for using the shadow style. For instance, if this support is implemented, I could remove three block styles from my Powder theme: https://github.com/bgardner/powder/blob/main/functions.php#L60-L64.

**Comment by andreawetzel** [comment]
I found this issue while trying to figure out how to add a shadow to a group. This would be a great feature to have for designing cards within a grid layout.

**Comment by ndiego** [comment]
> One of the common issue with shadows for group block is overlaps. Shadow of a first group block is hidden behind the following group block due to stacking.

We definitely need to get this resolved for 6.7, as it's one of the first blocks you'd expect to be able to add shadow to. 

If anyone wants to enable this manually in a theme for testing purposes, you can use the following code: 

```javascript
function addShadowSupport( settings, name ) {

	// Bail early if the block does not have supports.
	if ( ! settings?.supports ) {
		return settings;
	}

	// Only apply to Group blocks.
  	if ( name === 'core/group' ) {
		return Object.assign( {}, settings, {
			supports: Object.assign( settings.supports, {
				shadow: true,
			} ),
		} );
	}

	return settings;
}

wp.hooks.addFilter(
	'blocks.registerBlockType',
	'modify-block-supports/add-shadow-support',
	addShadowSupport,
);
```

**Comment by carolinan** [comment]
If the concern is that groups with shadows may need to have margins or padding applied automatically, I don't think we should do that, I think that styling needs to be up to the theme developer/designer/user.

Here is a screenshot of Twenty Twenty-Four with the "Deep" shadow applied to the group from the global styles.
![66 local_](https://github.com/WordPress/gutenberg/assets/7422055/2af2c151-1b0a-4c0e-b459-0ce8b6925ff8)

### Shadows are cut off by the block above or below
And here is a single post with a full width group, followed by a spacer block, and then two full width groups after eachother.

Deep:
![single-post-full-width-group-w-deep-shadow](https://github.com/WordPress/gutenberg/assets/7422055/e02eed09-1005-4ec7-b7ac-28f314a23bc8)
Natural:
![single-post-full-width-group-w-natural-shadow](https://github.com/WordPress/gutenberg/assets/7422055/18d7adb1-63e1-462e-8785-f2d99c0055b0)

### Nested
Here is a group with a background color, padding, and another group inside. Using the outline shadow, the background color between the block and the shadow is white, even if the parent group has a different background color set, but this may be a feature not a bug:
![single-post-nested-groups-outline-shadow](https://github.com/WordPress/gutenberg/assets/7422055/05fde844-f098-4afa-833b-b9f835593e85)

### With negative margins
A wide group with padding, followed by a default width group that has a negative top margin.
![single-post-groups-w-negative-margin-w-sharp-shadow](https://github.com/WordPress/gutenberg/assets/7422055/dbb4359b-45f3-4c45-8757-d3078e66da9b)

**Comment by ndiego** [comment]
> If the concern is that groups with shadows may need to have margins or padding applied automatically, I don't think we should do that, I think that styling needs to be up to the theme developer/designer/user.

I agree. Adding shadow can be a complex action. For edge cases, like two shadowed groups next to one another, it requires some understanding of CSS, much like negative margin does. I think this is fine and we should not be automatically applying any additional styling when a shadow is added. I have already [added shadow manually](https://github.com/WordPress/gutenberg/issues/62258#issuecomment-2186447693) in all my projects, and it works as expected.

I recommend we add shadow to Group as soon as possible and let folks experiment with it.
