### ISSUE TITLE
Navigation: Block toolbar obscures submenu items when Navigation block is at top of editor

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#62256]
### Description

If the Navigation block is at the top of the editor then it's really difficult to edit submenus because the block toolbar obscures the submenu.

### Step-by-step reproduction instructions

1. Install and activate _Emptytheme_, or use the Create Block Theme plugin to create a new empty theme.
2. Go to Appearance → Editor and edit the default template.
3. Insert a Navigation block into the first position in the header template part.
4. Edit the Navigation block and add a submenu to one of the navigation items.
5. Try to edit the submenu.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/612155/adedcf22-0bac-4d4d-9769-941d8cf91cd2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I think this was already reported in https://github.com/WordPress/gutenberg/issues/40382.

Seems like a tricky one to fix!

**Comment by noisysocks** [comment]
Aha! I was searching for that. Thanks.
