### ISSUE TITLE
Remove a panel from the settings?

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#6225]
A Question from _camthor_ in the support forum:

> Hi,
> 
> For the previous editor we had the possibility to remove a default meta box with remove_meta_box. That was useful if, for example, you wanted to create an alternative box for tags.
> 
> Is there anything equivalent for Gutenberg, i.e. to remove a panel from the settings on the right side? I was checking if you could simply hide the element, but all divs seem to have the class “components-panel__body” and no id. So there doesn’t seem to be a way how to select a particular panel. I would prefer, however, to remove the element already before rendering the page if that’s possible, not just with jQuery.
> 
> Thanks!

Source: https://wordpress.org/support/topic/how-to-programatically-remove-a-panel-from-the-settings/

**Comment by youknowriad** [comment]
Let's consolidate in #6225

**Comment by gziolo** [comment]
> is there any solution how to remove the panel of the post tags?

You can do the following as of today:

```js
var el = wp.element.createElement;

function removeCategoryPanel( OriginalComponent ) {
	return function( props ) {
		if ( props.slug === 'category' ) {
			return null
		} else {
			return el(
				OriginalComponent,
				props
			);
		}
	}
};

wp.hooks.addFilter(
	'editor.PostTaxonomyType',
	'my-custom-plugin',
	removeCategoryPanel
);
```

Howeve it won't remove the panel's title. I will have a look tomorrow and find out if that is easy to do.

**Comment by gziolo** [comment]
> There's an API used in the options panel to hide these panels, I think we can just use it here?

I have PR almost ready which adds another flag. The issue with the existing action is that you still would be able to enable it back using Options modal. My change will put the editor in the following state:

![screen shot 2018-11-13 at 09 41 43](https://user-images.githubusercontent.com/699132/48401049-655b7200-e728-11e8-8c9a-c4340abff9e7.png)
