### ISSUE TITLE
Post Date: Add relative date format

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#62259]
Would be good if you could set Post Date to show a relative date. This is common amongst non-block themes.

For example: _12 hours ago_, _2 days ago_, _a month ago_.

<img width="292" alt="Screenshot 2024-06-04 at 14 29 56" src="https://github.com/WordPress/gutenberg/assets/612155/242c9934-9d28-464e-a953-adcc35250143">

WordPress has [`human_time_diff`](https://developer.wordpress.org/reference/functions/human_time_diff/) which can be used.

**Comment by ramonjd** [comment]
Also [humanTimeDiff](https://github.com/WordPress/gutenberg/tree/trunk/packages/date#humantimediff) in the date package since https://github.com/WordPress/gutenberg/pull/50089

🎉
