### ISSUE TITLE
Global Styles: Can't remove a custom color from palette in Safari

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#62261]
### Description

The _Remove color_ button in Styles → Colors → Palette → Custom doesn't work in Safari.

### Step-by-step reproduction instructions

1. Use Safari.
2. Go to Appearance → Editor → Colors → Palette.
3. Add a custom color and press _Done_.
4. Try to remove that custom color.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/612155/815c3b60-734f-4d56-996a-07c3f8de407d

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
Confirmed.

**Comment by t-hamano** [comment]
I'm running Windows OS so I can't test this issue, but was this issue resolved in #62753?

**Comment by ellatrix** [comment]
Yes, this is fixed
