### ISSUE TITLE
Color variations in the Styles section take two clicks and make you lose your place

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#62264]
### Description

In the site editor > styles section, sometimes you have to click a color variation twice to select it. And commonly, the first click will scroll the interface and make you lose your place. This is what's happening in the following GIF:

![click twice](https://github.com/WordPress/gutenberg/assets/1204802/1222433b-d22e-43c1-ad12-e81878fb2a25)

### Step-by-step reproduction instructions

* Have a lot of color variations/presets
* Go the site editor > styles
* Scroll down to the color variations, pick one

Sometimes it works on the first click, sometimes it doesn't, and you lose your place.

### Environment info

Trunk plugin, nightly WordPress.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by scruffian** [comment]
I cannot replicate this. Perhaps it was fixed by another PR. Please reopen if you can still reproduce it.
