### ISSUE TITLE
Themes: Being able to delete templates one do not plan to use

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#62269]
## What problem does this address?

An example 
These templates are included in Twenty Twenty Four. 

![Screenshot 2024-06-04 at 11 46 04](https://github.com/WordPress/gutenberg/assets/5323259/afe00363-0d96-42f2-a4d7-e8ffad610e17)

There are a few page templates I do not plan on using.

It would be helpful to be able to clean up the templates screen by deleting perhaps into a trash can screen the templates I do not plan on using.

## What is your proposed solution?

Having a method to also delete theme templates.

For the next default theme...
Perhaps there should be less templates and instead have full page patterns one can add into a new template instead of predefined templates?

@jordesign @scruffian

**Comment by bph** [comment]
That's an interesting proposal. It's inline with other attempts to curate the editor experience for end users. I was just curious why you want to restrict the feature to core themes. Other themes might also have a myriad of templates available, that one might restrict for usage not only in the template Admin screen but also in the template switching choices in the site and post editor.

**Comment by paaljoachim** [comment]
Hi Birgit @bph 
I have adjusted the title. I totally agree with you. One should be able to delete templates from any theme. Not only core themes. One should also have a better control over which templates one wants to bring between themes.

**Comment by annezazu** [comment]
This is a duplicate of this prior issue: https://github.com/WordPress/gutenberg/issues/49640

Closing this out in favor of it!

**Comment by paaljoachim** [comment]
Thanks @annezazu 
I had a feeling that there was already an issue for it that I had also commented upon, but I just could not locate it.
