### ISSUE TITLE
Button component: link buttons should not use aria-disabled

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#62281]
### Description

Discovered while checking https://github.com/WordPress/gutenberg/pull/62080

The Button component accepts a `href` prop which is supposed to be an URL. When set, the Button renders an `<a>` element: a link with a proper href attribute.

However, when the Button component receives also the `disabled` and `;__experimentalIsFocusable` props both set to `true`, the rendered link gets an `aria-disabled="true"` attribute.

That's not correct for two reasons:
- It's invalid HTML: aria-disabled-true is invalid on an `<a>` element.
- Conceptually incorrect: links can't be 'disabled'. Either they are links or not.

Weirdly enough, when setting `__experimentalIsFocusable` to `false` and keeping the `href` prop, the Button is rendered as a disabled `<button>` element.

Rendered invalid HTML example:

```
<a href="https://wordpress.org" aria-disabled="true" class="components-button">Code is poetry</a>
```

It is worth mentioning that links can't 'really' be disabled. Their real nature is to _not_ be disabled. The defautl action can be prevented via JavaScript to make a click event do nothing but that's less than ideal. It's against the nature of a link.That's the reason why an `aria-disabled="true"` or `disabled` attribute on `<a>` elements are invalid HTML.

### Step-by-step reproduction instructions

- Go to https://wordpress.github.io/gutenberg/?path=/story/components-button--default&args=disabled:!true;__experimentalIsFocusable:!true
- Make sure both the `__experimentalIsFocusable` and `disabled` props are set to `true`.
- Set the `href` prop to `https://wordpress.org`
- Inspect the button rendered at the top of the page.
- Oberve it renders and `<a>` element with an `aria-disabled="true"` attribute.

### Screenshots, screen recording, code snippet

aria-disabled="true" invalid HTML

![Screenshot 2024-06-04 at 15 02 56](https://github.com/WordPress/gutenberg/assets/1682452/51807f9f-5c98-4424-9b11-d3b7db2db681)

disabled invalid HTML

![Screenshot 2024-06-04 at 15 18 44](https://github.com/WordPress/gutenberg/assets/1682452/e7cbf6ff-822e-48c1-be06-260dec4ff6bc)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by afercia** [comment]
Note: I _think_ this problem was discussed when first implementing the Button component but never fully addressed, nor I could find a specific issue about it.

**Comment by mirka** [comment]
I noticed this issue as well when testing edge cases in the TypeScript types for Button. For what it's worth, TypeScript will error on cases where a `disabled` is used together with `href`. But we should definitely fix the runtime behavior.

https://github.com/WordPress/gutenberg/blob/ffb6c43a273f04ee68ff00bf238bf5f107d2b1ad/packages/components/src/button/test/index.tsx#L634-L635
