### ISSUE TITLE
The pattern shuffle feature includes synced patterns but they are inserted unsynced

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#62294]
### Description

If you have created a synced pattern and placed it in an existing pattern category, when you insert another unsynced pattern from that category and use the new shuffle feature, the synced pattern is included in the shuffle. However, the inserted synced pattern is no longer synced. 

### Step-by-step reproduction instructions

1. Use Gutenberg trunk and TT4
2. Open a page and insert one of the banner patterns
3. Modify the pattern slightly (so you can recognize it) save it as a synced pattern and add it to the "Banners" category
4. Now add another banner pattern, you should see the shuffle button
5. Shuffle through the patterns until your synced pattern gets inserted. Notice that it's no longer synced. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/4832319/0cf5bd55-24b4-4a74-b90e-666b41b65c5c

### Environment info

- Gutenberg trunk
- WordPress 6.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
It's technically working as expected: shuffling among the pattern within the inserted category. 

As it shuffles to another pattern, the alternate pattern could be any pattern in that same category—not necessarily any other _synced_ pattern. You're not editing the synced pattern when shuffling.

**Comment by ndiego** [comment]
> As it shuffles to another pattern, the alternate pattern could be any pattern in that same category—not necessarily any other synced pattern. You're not editing the synced pattern when shuffling.

No, I get that, but it inserts the synced pattern as an unsynced pattern. Is that correct?

**Comment by talldan** [comment]
> No, I get that, but it inserts the synced pattern as an unsynced pattern. Is that correct?

I agree with you @ndiego, it doesn't sound correct to me. Synced patterns should probably not be considered as candidates for shuffling, given it's unexpected that they'll be inserted as unsynced.

If they were inserted as synced the shuffle option would disappear as synced patterns don't support it at the moment.

**Comment by jorgefilipecosta** [comment]
> If they were inserted as synced the shuffle option would disappear as synced patterns don't support it at the moment.

Hi @talldan, do you think it would make sense to make synced patterns also support shuffling?

**Comment by richtabor** [comment]
> Synced patterns should probably not be considered as candidates for shuffling, given it's unexpected that they'll be inserted as unsynced.

> If they were inserted as synced the shuffle option would disappear as synced patterns don't support it at the moment.

This makes sense to me.

**Comment by talldan** [comment]
> Hi @talldan, do you think it would make sense to make synced patterns also support shuffling?

I haven't been involved in the recent shuffling work much, so I don't know if it has been discussed before. (@scruffian might be a good person to comment).

Synced patterns are all user created right now (though it could change in the future - #59272), so if the user has sensible categories it makes sense to me that they can leverage shuffle.

Overrides mean that pattern content can be edited, so #62288 is still a concern for synced patterns. It would be possible to maintain the user edits when shuffling synced patterns if the new pattern is compatible, but I imagine it'd result in very few matching patterns. Or you could very easily check for edits (the pattern (`core/block`) block's `content` attribute is non-empty when there are edits).
