### ISSUE TITLE
Backports for 6.6 Beta/RC

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#62315]
This issue supersedes #61226. See [Back-merging code to WordPress Core](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/back-merging-to-wp-core.md).

I'm starting a new issue because I'd like to try a new approach based on the backport log. Note that, since we started the backport log before Beta, this will also include backports from before Beta.

PRs have title/status previews, so it's easy to have an overview of overall status (no need for a checklist).

- https://github.com/WordPress/wordpress-develop/pull/6279
  * https://github.com/WordPress/gutenberg/pull/60063
- https://github.com/WordPress/wordpress-develop/pull/6522
  * https://github.com/WordPress/gutenberg/pull/60106
  * https://github.com/WordPress/gutenberg/pull/60228
  * https://github.com/WordPress/gutenberg/pull/61638
- https://github.com/WordPress/wordpress-develop/pull/6559
  * https://github.com/WordPress/gutenberg/pull/60349
  * https://github.com/WordPress/gutenberg/pull/60464
  * https://github.com/WordPress/gutenberg/pull/60491
  * https://github.com/WordPress/gutenberg/pull/61757
- https://github.com/WordPress/wordpress-develop/pull/6567
  * https://github.com/WordPress/gutenberg/pull/47271
  * https://github.com/WordPress/gutenberg/pull/61774
- https://github.com/WordPress/wordpress-develop/pull/6590
  * https://github.com/WordPress/gutenberg/pull/59531
  * https://github.com/WordPress/gutenberg/pull/61182
  * https://github.com/WordPress/gutenberg/pull/61717
- https://github.com/WordPress/wordpress-develop/pull/6605
  * https://github.com/WordPress/gutenberg/pull/61851
- https://github.com/WordPress/wordpress-develop/pull/6616
  * https://github.com/WordPress/gutenberg/pull/58409
  * https://github.com/WordPress/gutenberg/pull/61328
  * https://github.com/WordPress/gutenberg/pull/61842
  * https://github.com/WordPress/gutenberg/pull/62199
  * https://github.com/WordPress/gutenberg/pull/62252
- https://github.com/WordPress/wordpress-develop/pull/6656
  * https://github.com/WordPress/gutenberg/pull/60715
- https://github.com/WordPress/wordpress-develop/pull/6662
  * https://github.com/WordPress/gutenberg/pull/57908
  * https://github.com/WordPress/gutenberg/pull/62125
- https://github.com/WordPress/wordpress-develop/pull/6694
  * https://github.com/WordPress/gutenberg/pull/60694
- https://github.com/WordPress/wordpress-develop/pull/6731
  * https://github.com/WordPress/gutenberg/pull/62299
- https://github.com/WordPress/wordpress-develop/pull/6737
  * https://github.com/WordPress/gutenberg/pull/62305
- https://github.com/WordPress/wordpress-develop/pull/6744
  * https://github.com/WordPress/gutenberg/pull/62355
- https://github.com/WordPress/wordpress-develop/pull/6756
  * https://github.com/WordPress/gutenberg/pull/62461
  * https://github.com/WordPress/gutenberg/pull/62495
- https://github.com/WordPress/wordpress-develop/pull/6785
  * https://github.com/WordPress/gutenberg/pull/62459
- https://github.com/WordPress/wordpress-develop/pull/6797
  * https://github.com/WordPress/gutenberg/pull/62526
- https://github.com/WordPress/wordpress-develop/pull/6824
  * https://github.com/WordPress/gutenberg/pull/62550
- https://github.com/WordPress/wordpress-develop/pull/6825
  * https://github.com/WordPress/gutenberg/pull/62552
- https://github.com/WordPress/wordpress-develop/pull/6827
  * https://github.com/WordPress/gutenberg/pull/62465
- https://github.com/WordPress/wordpress-develop/pull/6837
  * https://github.com/WordPress/gutenberg/pull/62529
  * https://github.com/WordPress/gutenberg/pull/62610
- https://github.com/WordPress/wordpress-develop/pull/6841
  * https://github.com/WordPress/gutenberg/pull/62598
- https://github.com/WordPress/wordpress-develop/pull/6844
  * https://github.com/WordPress/gutenberg/pull/62640
- https://github.com/WordPress/wordpress-develop/pull/6854
  * https://github.com/WordPress/gutenberg/pull/62670
- https://github.com/WordPress/wordpress-develop/pull/6864
  * https://github.com/WordPress/gutenberg/pull/62488
  * https://github.com/WordPress/gutenberg/pull/62696
- https://github.com/WordPress/wordpress-develop/pull/6873
  * https://github.com/WordPress/gutenberg/pull/62712
- https://github.com/WordPress/wordpress-develop/pull/6959
  * https://github.com/WordPress/gutenberg/pull/63071
- https://github.com/WordPress/wordpress-develop/pull/6987
  * https://github.com/WordPress/gutenberg/pull/63207
- https://github.com/WordPress/wordpress-develop/pull/6989
  * https://github.com/WordPress/gutenberg/pull/63172

**Comment by bgardner** [comment]
@ellatrix Any idea when the issues on this list will get backported to 6.6 Beta? (Asking in particular about https://github.com/WordPress/gutenberg/pull/62199 and if it can get into Beta 2.)

That issue is holding me up from doing extensive testing with 6.6 Beta, as I cannot right now because of the spacing issues.

**Comment by ellatrix** [comment]
@bgardner It's already been backported in https://github.com/WordPress/wordpress-develop/pull/6616, it's in the list above

**Comment by bgardner** [comment]
@ellatrix Great, that’s what I thought. Hoping it makes it into Beta 2. 🙏

**Comment by spacedmonkey** [comment]
@ellatrix Am I good to backport https://github.com/WordPress/gutenberg/pull/62522. I have a PR https://github.com/WordPress/wordpress-develop/pull/6895.

**Comment by ellatrix** [comment]
Of course, please do
