### ISSUE TITLE
Create abstractions for Block Bindings Panel and other ItemGroups

### ISSUE THREAD

**Issue by artemiomorales** [WordPress/gutenberg#62330]
## What problem does this address?

Follow up to https://github.com/WordPress/gutenberg/pull/61527

As detailed in the [following comment](https://github.com/WordPress/gutenberg/pull/61527#discussion_r1601237983), it is likely possible to consolidate the styles and functionality of the bindings panel and features with similar UX such as fonts and shadows.

## What is your proposed solution?

As we iterate on the bindings panel to target the [proposed design](https://github.com/WordPress/gutenberg/issues/61404), we should look to consolidate its functionality and styles, along with that of fonts, shadows, and similar features, into ItemGroup.

**Comment by gziolo** [comment]
How much https://github.com/WordPress/gutenberg/pull/62880 will help to address this issue?

**Comment by gziolo** [comment]
I don’t think there is much left in terms of Block Bindings UI. @artemiomorales, should we clarify what’s left regarding the general enhancement of UI components?

**Comment by gziolo** [comment]
This can be closed now as the direction for Block Bindings sidebar panel UI is a bit different as of:
- https://github.com/WordPress/gutenberg/issues/67520
