### ISSUE TITLE
Delete button in Gutenberg editor

### ISSUE THREAD

**Issue by aramb-dev** [WordPress/gutenberg#62340]
## What problem does this address?

It is currently difficult, especially for beginners at WordPress, to delete an element from the Gutenberg editor.  Currently, the delete button is present within the dropdown menu. 

## What is your proposed solution?

I think the delete button should be moved to the toolbar that pops up when an element is clicked.

https://github.com/WordPress/gutenberg/assets/65731416/a4b134fb-633c-4f84-b77c-d2bfa6b25b3c

**Comment by Mamaduka** [comment]
Thanks for opening the issue, @aramb-dev!

Placing "destructive" actions in dropdowns is a typical UI pattern, as they shouldn't be prominent.

cc @jasmussen

**Comment by jasmussen** [comment]
I share the underlying instinct, that it should be intuitive and easy to delete. Select something, press delete or backspace to remove it. In the case of a paragraph, like other text editors, it deletes letters, not the block. The shortcut that exists is not the most intuitive, I don't recall the context for it, I'm sure there was good reason for choosing that, but I'd love something simpler as an addition, if that's possible. Another way to delete a paragraph is to press Esc to enter select mode, and then the delete key. Refining how you flow between edit and select modes is also a fruitful area of exploration.

That said, I'd echo Mamaduka above, it's not an action that should have such prominence, and in the constrained space that is the toolbar, it also comes at expense of other buttons. Many blocks have long toolbars, such as list items. Add text-labels-only mode to that and eventually you'll need a horizontal scrollbar. So it's not the right place for a few reasons.

**Comment by stokesman** [comment]
@aramb-dev, while I agree with previous comments that the button shouldn’t be there, if you’d really like it on your sites making a plugin for that is fairly simple. To demonstrate the idea, the following can be run from the dev console while on an editor page to add the button.

```js
(( {
    blockEditor: { store: blockEditorStore, BlockControls },
    components: { ToolbarButton },
    compose: { createHigherOrderComponent },
    element: { createElement: el, Fragment },
    data: { useDispatch },
    hooks: { addFilter },
} ) => {
    addFilter(
        'editor.BlockEdit',
        'no62340/with-delete',
        createHigherOrderComponent( ( BlockEdit ) => ( props ) => {
            const { removeBlock } = useDispatch( blockEditorStore );
            const { clientId, attributes: { lock } } = props;
            if ( lock?.remove ) return el( BlockEdit, props );
            return el(
                Fragment,
                null,
                el( BlockEdit, props ),
                el( BlockControls, { group: 'block' },
                    el( ToolbarButton, {
                        icon: 'trash',
                        label: 'Delete block',
                        isDestructive: true,
                        onClick: () => removeBlock( clientId ),
                    } )
                )
            );
        }, 'withDelete' )
    );
})( wp );
```

**Comment by Mamaduka** [comment]
I am closing this issue as "not planned".

## Why?
* A notes above the toolbar has limited space and adding an extra button for all block current isn't viable.
* The project can easily implement this feature. See: https://github.com/WordPress/gutenberg/issues/62340#issuecomment-2158912291.
* Power users can use shortcut to delete blocks. While current shorctu is bit unintuitive, that can be improved separately.
