### ISSUE TITLE
Data views: hide checkboxes in grid layout when unable to select

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#62349]
When viewing items in data views in the Site Editor, checkboxes are shown even if you can't actually select anything. Every time I see this, I still think I can check the box so either the greyed out look needs to shift, the checkboxes need to be removed if you can't select an item, or something else I can't think of right now :) Connecting the dots, it looks like there's feedback to have checkboxes always be visible in certain layouts https://github.com/WordPress/gutenberg/issues/59175

Here's a video showing what I mean: 

https://github.com/WordPress/gutenberg/assets/26996883/1f0f8955-95be-4291-a9b2-79b2d23c8272

**Comment by amitraj2203** [comment]
>  Every time I see this, I still think I can check the box so either the greyed out look needs to shift, the checkboxes need to be removed if you can't select an item, or something else I can't think of right now 

Hi @annezazu, I have raised a PR for this which adds `cursor: not-allowed;` to the unselectable items.

**Comment by annezazu** [comment]
@jameskoster while we've iterated on this and de-emphasized the checkbox option (only shown when hovering), I find it odd that a greyed out checkbox shows at all when using 6.6.1 and GB 19.0: 

https://github.com/user-attachments/assets/003099e8-f2d4-43c1-a8dc-068414100dfe

From what I can see in prior PRs we turned off the checkbox when there aren't any actions to take https://github.com/WordPress/gutenberg/pull/58950 Curious what the intent is here.

**Comment by jameskoster** [comment]
In table layout the checkboxes are removed entirely when there are no applicable bulk actions. I agree it makes sense to do the same thing in Grid layout as well. What do you think @jorgefilipecosta?

**Comment by ntsekouras** [comment]
This was resolved [here](https://github.com/WordPress/gutenberg/pull/68033) by removing the checkbox if no bulk actions exist for any item.
