### ISSUE TITLE
Edit callback on last selected block called on focussing one block

### ISSUE THREAD

**Issue by shramee** [WordPress/gutenberg#6234]
## Issue Overview

Focus 

## Steps to Reproduce (for bugs)

Add any block which does a console log on edit callback... Just need to be able to identify the block message came from...

```
( function( blocks, i18n, element ) {
	var el = element.createElement;
	var __ = i18n.__;
	var RichText = blocks.RichText;

	blocks.registerBlockType( 'gutenberg-issue/focus-issue', {
		title: 'Focus issue',
		icon: 'megaphone',
		category: 'common',

		attributes: {
			content: {
				type: 'array',
				source: 'children',
				selector: 'p',
			},
		},

		edit: function( props ) {
			var content = props.attributes.content;
			var focus = props.focus;

			console.log( content );

			function onChangeContent( newContent ) {
				props.setAttributes( { content: newContent } );
			}

			return el(
				RichText,
				{
					tagName: 'p',
					className: props.className,
					onChange: onChangeContent,
					value: content,
					focus: focus,
					onFocus: props.setFocus
				}
			);
		},

		save: function( props ) {
			return el( 'p', {}, props.attributes.content );
		},
	} );
} )(
	window.wp.blocks,
	window.wp.i18n,
	window.wp.element
);
```
1. Add `Focus issue` blocks with different text.
2. Open Console to see logged messages.
3. Try to focus blocks one by one.
4. It calls last selected block's edit callback after calling one for selected block.

Using browser `Google Chrome Version 65.0.3325.181` on `MacOS High Sierra 10.13.4`

## Expected Behavior
Only selected block should have it's edit callback called ;)

## Current Behavior
Last selected blocks edit callback is called too.

## Possible Solution
Either...
1. Trigger edit callback for selected block only. OR
2. **Trigger on deselected block first then on selected block.**

## Screenshots / Video
https://www.youtube.com/watch?v=b1o8CK9mbXY

## Todos
- [ ] Reproduce
- [ ] Fix

**Comment by mcsf** [comment]
This is expected behavior. `edit` is a render method, semantically different from a callback, and is expected to run in multiple occasions.
