### ISSUE TITLE
Pattern navigation toggles zoom out view

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#62364]
### Description

Tested the zoom out view for patterns still in experiment. 
When I navigate the Patterns in the Inserter and zoom out view changes from zoom out to zoomed in when I navigate the categories. One click on a category the page view zooms out, the next click on a pattern category zooms the page view back in. It's like Zoom out toggle.  The video below is a recording on how I navigated the categories 

### Step-by-step reproduction instructions

- Gutenberg > Experiment > click on **Enable zoomed out view when selecting a pattern category in the main inserter.**
- Open a page in the editor and 
- open the Inserter with the Pattern tab. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/39980/7b66cbe2-e634-4275-8d67-23a4b04cbb0e

### Environment info

- WordPress 6.6-beta1
- Gutenberg 18.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
I've noticed this as well. It needs a bit more refinement since it became the experiment. It's essentially toggling on/off.

**Comment by stokesman** [comment]
I’ve tested on trunk and can no longer reproduce. It looks like it was resolved thanks to #63315.
