### ISSUE TITLE
"Add before" and "Add after" missing when editing pages in the Site Editor

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#62367]
### Description

Looks like something with content locking is reducing the editing capabilities when using the Site Editor. This occurs with blocks nested directly within the "Content" block.  

I'd expect all standard editing controls available.  

### Step-by-step reproduction instructions

1. Open the Site Editor.
2. Select "Pages".
3. Select "Add new page".
4. Add content to the page.
5. Open the block toolbar options menu. 
6. See missing "Add before" and "Add after" controls. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1813435/01c6dd8c-4e46-4f16-9b7e-daeceff4a393

### Environment info

- WordPress trunk
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
This is probably a regression after #61127. I'll have a better look tomorrow.
