### ISSUE TITLE
Text alignment controls in global styles for irrelevant blocks

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#62369]
### Description

The new text alignment controls are available in global styles for blocks that do not support typography. These should be constrained to blocks that support typography, rather than added to every block. 

Notably (but there are certainly others):
- Template part block
- HTML block
- Embed block
- Page list item
- Pattern placeholder
- More
- Page break

### Step-by-step reproduction instructions

1. Open the Site Editor.
2. Select global styles.
3. Select "Blocks"
4. Select "Template part" (then repeat with HTML block).
5. See bug. 

### Screenshots, screen recording, code snippet

![CleanShot 2024-06-06 at 09 28 41](https://github.com/WordPress/gutenberg/assets/1813435/c2ac3bf1-e963-45c2-91dc-3960927f95eb)
![CleanShot 2024-06-06 at 09 32 03](https://github.com/WordPress/gutenberg/assets/1813435/9c5f83b3-e302-47d4-8c30-3272b7b5f895)

### Environment info

WordPress trunk
Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I've found the cause and will submit a PR shortly.
