### ISSUE TITLE
Polish UX when saving post metadata and create supporting data structures

### ISSUE THREAD

**Issue by artemiomorales** [WordPress/gutenberg#62383]
## What problem does this address?

Right now, our existing data structures and logic don't support an ideal user experience when modifying post metadata:
- We are unable to easily show granular edits to the post metadata in the Save Panel ([related discussion](https://github.com/WordPress/gutenberg/pull/61811#discussion_r1615603578))
- We are unable to distinguish between post metadata modifications that should require an extra verification in the save panel versus ones that shouldn't ([related discussion](https://github.com/WordPress/gutenberg/pull/61811#issuecomment-2141715277) where we created a temporary workaround to prevent an extra verification when modifying footnotes)
- The "Site Updated" message shows erroneously whenever post metadata is changed, whether or not the change was related to the overall site ([related discussion](https://github.com/WordPress/gutenberg/pull/62284#discussion_r1626167036))

## What is your proposed solution?

Let's think through the user experience of these scenarios holistically and refactor so that our use cases are easy to implement and understand in the codebase, as well as potentially extensible to future use cases.

**Comment by artemiomorales** [comment]
I'll add some images to help this discussion. We have two open questions and a proposed design to consider:

1. What indication do we show in the snackbar if the Post Meta for an entity has changed?

<img width="1213" alt="post-meta-changed" src="https://github.com/WordPress/gutenberg/assets/5360536/d314f50a-7be9-41f0-b650-703a54c9c31b">

2. Should we add a panel in the pre-publish flow if Post Meta has changed?

<img width="795" alt="pre-publish" src="https://github.com/WordPress/gutenberg/assets/5360536/531feb60-6992-407a-ad33-2ad21ff236cc">

3. In addition, here is the proposed design for the Save Panel when reviewing modified entities.

<img width="1638" alt="332440083-302bf4e4-6133-4c60-9d75-3c037402f5af" src="https://github.com/WordPress/gutenberg/assets/5360536/9024f6a4-713f-4263-9e1f-55f93aa0f7c2">

As mentioned, the supporting data structures to easily modify these experiences do not currently exist in the codebase, so as we think about this holistically, we'll need to consider the best way to make any new flow or UX possible.

**Comment by jasmussen** [comment]
There's a little relevant conversation [happening in Slack as well](https://wordpress.slack.com/archives/C02S78ZAL/p1718093658087619). [Link requires registration](https://make.wordpress.org/chat/).

**Comment by artemiomorales** [comment]
@gziolo @SantosGuillamot Is there anyone we should ping on the code side to move this discussion forward? Maybe a PR with some data structure changes to support the granular review of post meta (as in the image below) would be good?

<img width="1638" alt="332440083-302bf4e4-6133-4c60-9d75-3c037402f5af" src="https://github.com/WordPress/gutenberg/assets/5360536/9024f6a4-713f-4263-9e1f-55f93aa0f7c2">

**Comment by SantosGuillamot** [comment]
From [your previous comment](https://github.com/WordPress/gutenberg/issues/62383#issuecomment-2158219624), it seems there are three things we should/could work on:
1. Decide and fix which message should show when custom fields have changed.
2. Improve the pre-publish workflow to notify users the custom fields have changed, the same way we are doing when saving.
3. Improve the existing saving UX to include the list of custom fields that have changed.

If that's the case, I believe we can address each item individually. I would say that the first step would be to explore how to work on it and, if we get blocked, ask for help with more concrete questions.

**Comment by cbravobernal** [comment]
> @gziolo @SantosGuillamot Is there anyone we should ping on the code side to move this discussion forward? Maybe a PR with some data structure changes to support the granular review of post meta (as in the image below) would be good?
> <img alt="332440083-302bf4e4-6133-4c60-9d75-3c037402f5af" width="1638" src="https://private-user-images.githubusercontent.com/5360536/338182927-9024f6a4-713f-4263-9e1f-55f93aa0f7c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0Nzg1MTQsIm5iZiI6MTcxOTQ3ODIxNCwicGF0aCI6Ii81MzYwNTM2LzMzODE4MjkyNy05MDI0ZjZhNC03MTNmLTQyNjMtOWUxZi01NWY5M2FhMGY3YzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMDg1MDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjE4N2VhMTBhYjljMTgwMzg4MzFjMzQwZDU2YTdkNDQwNmY5MTBlNGUyZmMyMzBkNDY0MDc0ZDFhY2I1NzM5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.COF9OPQB261RGPJoNer3dgcoedrga-u72SZ8E0kDy1o">

I think we are the code side @artemiomorales 😉 

We could work on several things there, as @SantosGuillamot mention. Retrieving those fields, create the sections, add the fold/unfold behavior, etc.

We also would have to check what happens when the user unselect those checks and save.

Feel free to experiment and try to get the design approach, and reach out if blocked.

**Comment by artemiomorales** [comment]
> We also would have to check what happens when the user unselect those checks and save.
> 
> Feel free to experiment and try to get the design approach, and reach out if blocked.

Perfect, sounds like a plan. I'm interested in getting the save panel to work with the checkboxes — will look into that.

**Comment by SantosGuillamot** [comment]
I was checking, and we already have issues for:
1. [Editing bound paragraph in post editor causes "Site Updated" message to appear](https://github.com/WordPress/gutenberg/issues/62236)
2. [Add indicator for modified post meta in pre-publish flow](https://github.com/WordPress/gutenberg/issues/62329).

The only point missing is the one to include a list of the custom fields that have been modified. We can open a pull request or issue once we work on that.

Would it make sense to close this issue and rely on those ones?

> I'm interested in getting the save panel to work with the checkboxes — will look into that.

Regarding this: Which part is not working now? If we talk about having one checkbox per meta field as shown in the image, I would work first on showing the list of fields instead of "Post Meta", even without having checkboxes.

**Comment by cbravobernal** [comment]
>  showing the list of fields...

This would be the best start.

**Comment by artemiomorales** [comment]
>  I would work first on showing the list of fields instead of "Post Meta", even without having checkboxes.

Ok I've created a new issue here:
- https://github.com/WordPress/gutenberg/issues/62938

> Would it make sense to close this issue and rely on those ones?

I hesitate slightly because those two issues, as well as the one above, all would rely on using the same supporting data structure. I'm happy to close this if we feel that makes project management cleaner, though. My inclination is to focus on https://github.com/WordPress/gutenberg/issues/62938 to start, and we could move to the other two afterwards.

**Comment by artemiomorales** [comment]
I looked at this more closely and believe this issue is now better handled in the three more granular ones below. It turns out that they can largely be tackled individually, so I'll close this issue.

- https://github.com/WordPress/gutenberg/issues/62329
- https://github.com/WordPress/gutenberg/issues/62938
- https://github.com/WordPress/gutenberg/issues/62236
