### ISSUE TITLE
Pattern Overrides not rendering on Front End

### ISSUE THREAD

**Issue by jamiemarsland** [WordPress/gutenberg#62396]
### Description

Editing Pattern Overrides isn't working for me in WordPress 6.6 beta 1

### Step-by-step reproduction instructions

1. Create Pattern
2. Enable Overrides
3. Insert Pattern into Page
4. Edit Override content
5. Publish Page 
6. Override content isn't displaying properly

### Screenshots, screen recording, code snippet

https://vimeo.com/954664238/63cf83c1ed?share=copy

### Environment info

WordPress Beta 6.6 (1) 
Tested with Gutenberg plugin installed and also tested without Gutenberg plugin installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by SantosGuillamot** [comment]
Thanks for reporting! If I am not mistaken, it should be fixed after [these changes](https://github.com/WordPress/gutenberg/pull/62355). And this is [the backport in WordPress](https://github.com/WordPress/wordpress-develop/pull/6744).

**Comment by talldan** [comment]
It looks exactly like the same bug as https://github.com/WordPress/gutenberg/issues/62347, so let's close this now that a fix has been merged. If it's not resolved for beta 2, we can reopen the issue.

Thanks for reporting it, @jamiemarsland.
