### ISSUE TITLE
New Block: Query Results Count Block

### ISSUE THREAD

**Issue by bhubbard** [WordPress/gutenberg#62423]
## What problem does this address?
Currently there is no block to display the total # of results from a query.

## What is your proposed solution?
Offer a new block to display totals, this would probably most commonly be used next to the pagination block. Here are some screenshots of how we use it on our site.

Used at top above the query loop:
![Screenshot 2024-06-07 at 9 23 21 AM](https://github.com/WordPress/gutenberg/assets/3837/949878bb-8443-4853-b9ae-5725effd8813)

Used at bottom underneath Pagination links:
![Screenshot 2024-06-07 at 9 22 07 AM](https://github.com/WordPress/gutenberg/assets/3837/a5dbda46-3729-49e3-8507-f25da90cfef3)

**Comment by codersantosh** [comment]
I needed a similar block, but since one wasn't available, I developed a  [Custom Query Total Block](https://github.com/codersantosh/patterns-store/tree/master/src/blocks/query-total).

It would be great if a similar block were included in the core.

**Comment by sarthaknagoshe2002** [comment]
I'll be working on this block.
