### ISSUE TITLE
Outline button variation not working with TT4 (and other themes)

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#62451]
### Description

When clicking the Outline button variation, the proper styling is not being applied. This issue exists with TT4 on both front/back ends, but with my Powder theme, only on back end.

### Step-by-step reproduction instructions

1. Go to a post or page and add the buttons block.
2. Create a button, apply Outline variation.
3. See bug.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/486261/8fed9bca-a3ef-4472-9c59-84a56c02fed0

### Environment info

WordPress 6.6-beta1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by bgardner** [comment]
Worth noting that when I activate Gutenberg 18.5, the issue goes away on both front/back ends with TT4 and Powder per:

https://github.com/WordPress/gutenberg/assets/486261/e3a6255e-a53b-4f84-bc1b-f9e767ba9f8f

**Comment by annezazu** [comment]
Thanks for reporting! Adding to the board to be safe. 18.5 is the final GB release cut off for 6.6 so looks like something didn't come through cc @ellatrix.

**Comment by up1512001** [comment]
This button outline does not work with TT4, TT3, or TT2 but works with TT1.
cc: @annezazu @bgardner

**Comment by aaronrobertshaw** [comment]
Thanks for the issue @bgardner 👍 

The issue was due to some changes to the core theme.json file being omitted from the [specificity changes backport](https://github.com/WordPress/wordpress-develop/pull/6633).

There's a fix already up in https://github.com/WordPress/wordpress-develop/pull/6787 so should be resolved in WP6.6 beta 3.

**Comment by aaronrobertshaw** [comment]
Given the fix has been committed to core, I'll close this issue.
