### ISSUE TITLE
Resetting template part causes snackbar notification saying it's been deleted

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#62458]
Using 6.6 beta 1, if you make a change to a theme provided template part and then reset those changes from data views, you will see a snackbar notice that says the template part has been deleted rather than reset:

https://github.com/WordPress/gutenberg/assets/26996883/6852a728-0d3e-4b2b-b0d4-347ec1fe422b

I can replicate this with 6.6 beta 1 with and without GB 18.5 installed.

**Comment by ramonjd** [comment]
It's triggered by this line: 

https://github.com/WordPress/gutenberg/blob/f64a0afdd9adf85eba648b6a542a86bcb8b2d6c6/packages/editor/src/components/post-actions/actions.js#L874-L874


Introduced here:

https://github.com/WordPress/gutenberg/pull/61612/files#diff-f6d2ea7cd82485550ff502f466f05c286fe0cb0c444921ba001394a06280fe55R724

Wondering if it should be calling `revertTemplate` instead? 🤔 @jorgefilipecosta

Or is Gutenberg just trashing the post and reverting to the static theme file source? In that case we should somehow be able to discern the intention and display a different message I think.

**Comment by jorgefilipecosta** [comment]
Good catch, it was not introduced in #61612 as the reset action already called removeTemplate before https://github.com/WordPress/gutenberg/pull/61612/files#diff-112c6ef76fe2ea3012ca3ea57f5e53a413364e9aa63dda2360b7f24ea1213177L249. Calling removeTemplate seems correct as we want to trash the post and revert to the static theme file source. @youknowriad previously suggested doing that also for templates and not just template parts.
I guess the action should try to be aware if it is a remove or reset and throw a message matching that, I will have a look into this fix.
