### ISSUE TITLE
Block generated with @wordpress/create-block does not show in editor

### ISSUE THREAD

**Issue by drumslave-git** [WordPress/gutenberg#62456]
### Description

Feature: creation of custom block with @wordpress/create-block. I followed this https://developer.wordpress.org/block-editor/getting-started/tutorial/
Expected: after generation of plugin and its activation - new block should appear in WIDGETS section of visual editor
Actual: no new block

### Step-by-step reproduction instructions

just followed this https://developer.wordpress.org/block-editor/getting-started/tutorial/#scaffolding-the-block

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/42586943/4c1924e2-875d-4199-aab4-6d8e042369b9)
![image](https://github.com/WordPress/gutenberg/assets/42586943/37374795-bb4c-469a-8884-dcc1ae933640)

Also I see that only .css files are requested  
![image](https://github.com/WordPress/gutenberg/assets/42586943/5284bbdb-1fc2-43a3-ae60-1a2604f62bc2)

### Environment info

- WordPress: 6.5.4, everything default, just started with `wp-env start`
- Microsoft Edge Version 126.0.2592.36 (Official build) stable app, beta channel (64-bit)
- Desktop, Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Abhilashph123** [comment]
Same issue for me.

**Comment by t-hamano** [comment]
Thanks for the report. 

What version of `@wordpress/scripts` are you using? If it is `28.0`, it's the same issue reported in #62202.

**Comment by drumslave-git** [comment]
> Thanks for the report.
> 
> What version of `@wordpress/scripts` are you using? If it is `28.0`, it's the same issue reported in #62202.

"@wordpress/scripts": "^28.0.0", yep
