### ISSUE TITLE
English strings inserted in translations

### ISSUE THREAD

**Issue by chantalcoolsma** [WordPress/gutenberg#6246]
On translate.wordpress.org there is this string:

https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/nl/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5746763&filters%5Btranslation_id%5D=54835322

For Dutch this is translated as 'Voeg %s toe'. The %s shows English words. Results in for example:

'Voeg Image toe' or
'Voeg Gallery toe' or
'Voeg Heading toe'

![schermafbeelding 2018-04-18 om 16 06 55](https://user-images.githubusercontent.com/867632/38937066-9d0f6b2a-4322-11e8-930a-b495fb7a23bc.png)

![schermafbeelding 2018-04-18 om 16 07 03](https://user-images.githubusercontent.com/867632/38937075-a0f0b9ec-4322-11e8-8762-2f644157fae6.png)

I guess the '%s' strings need to be translatable too.

**Comment by Soean** [comment]
<img width="168" alt="bildschirmfoto 2018-04-19 um 01 25 47" src="https://user-images.githubusercontent.com/695201/38963125-b2eb939e-4370-11e8-9d28-e337e3bb1eda.png">
I can't reproduce it. Seems to be fixed in Gutenberg 2.7.
Please reopen if it still exists.

**Comment by rianrietveld** [comment]
This seems a valid issue, worth to continue the discussion and find a solution for,

**Comment by Soean** [comment]
@chantalcoolsma Thanks for your feedback. Thats another issue, different from the title and description, so I think it's better if we open a new issue.

**Comment by chantalcoolsma** [comment]
@Soean I will open a generic localisation issue and reference this issue. Maybe other translators will drop their thoughts too.
