### ISSUE TITLE
Update JSON schemas to use draft-07

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#62462]
We've been following the [SchemaStore best practices](https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#best-practices) for the development of our JSON schemas. They recommend a schema version based on what is widely supported in editors and IDEs. Previously this was draft-04, so all of our schemas currently use that version. However the new recommendation is draft-07 which comes with some quality of life improvements that can improve the readability and maintainability of our JSON schemas. Namely:

1. The [`$comment`](https://json-schema.org/draft-07/json-schema-core#rfc.section.9) keyword to explain reasoning behind schema decisions inline.
2. The [`propertyNames`](https://json-schema.org/draft-07/json-schema-validation#rfc.section.6.5.8) keyword to improve merging of two or more object subschemas while limiting `additionalProperties`.

Additionally, SchemaStore has an unofficial "strict mode" draft-07 meta schema `https://json.schemastore.org/metaschema-draft-07-unofficial-strict.json` that requires `type`, `title`, and `description` properties which we should be using and provides links to [understanding-json-schema](https://json-schema.org/understanding-json-schema/index.html) for each hint/check to help new JSON Schema contributors.

- There are some [breaking changes from draft-04 to draft-06](https://json-schema.org/draft-06/json-schema-release-notes#backwards-incompatible-changes). You can migrate schemas from draft-04 to draft-07 using [ajv-cli](https://github.com/ajv-validator/ajv-cli).
- The pattern of `*PropertiesComplete` can be updated to [use `propertyNames`](https://json-schema.org/draft-06/json-schema-release-notes#q:-what-happened-to-all-the-discussions-around-re-using-schemas-with) instead of lists of empty objects.
- The `enum` properties with single values can be updated to `const` where it would make sense to use `const`.

**Comment by DivyanshVinayak23** [comment]
Hi, can I work on this?

**Comment by ajlende** [comment]
> Hi, can I work on this?

@DivyanshVinayak23 Absolutely!

Check out the [contributing guidelines](https://github.com/WordPress/gutenberg/blob/trunk/CONTRIBUTING.md), specifically the [developer section](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/README.md), for general information on how to contribute code.

The `#core-editor` channel on [Make WordPress Slack](https://make.wordpress.org/chat) (registration required) is also a good place to ask questions if you have any.

**Comment by scruffian** [comment]
I noticed we use the `ajv-draft-04` npm package, and I can't find an alternative for draft-07...

**Comment by ajlende** [comment]
> I noticed we use the `ajv-draft-04` npm package, and I can't find an alternative for draft-07...

The `draft-07` validator is in the main [`ajv`](https://www.npmjs.com/package/ajv) package. Because there were breaking changes, they made the `draft-04` validator its own package.
