### ISSUE TITLE
Image block: caption persists when replacing image

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#62468]
### Description

When replacing an image that does have a caption with another image that does _not_ have a caption, the previous caption persists.

I can reproduce thie behavior on WordPress 6.5 and on Gutenberg trunk.

Attached animated GIF to illustrate:

![caption persists](https://github.com/WordPress/gutenberg/assets/1682452/719e44a8-bf1e-4cd3-b5df-949fee61f0a3)

### Step-by-step reproduction instructions

- Create a new post.
- Add an Image block from the Media Library, make sure the image does have a caption.
- Observe the image does render its caption.
- Click 'Replace' in the image block toolbar.
- Replace the image with one that does _not_ have a caption.
- Observe the caption of the previous image persists.
- Expected: the caption to not be redered.

Note: when replacing with an image that _does_ have a caption, the caption is correctly updated.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I think this is because there's a process to ensure that caption text isn't overwritten by an empty caption.

https://github.com/WordPress/gutenberg/blob/fe8fe408fcfa066a9efd51ceafc51410c8f6d393/packages/block-library/src/image/edit.js#L197-L203

Do you think this process is unnecessary?

**Comment by afercia** [comment]
I understand the intent of that check but seems to me it is based on an assumption. To me, it is only valid in a scenario where the user has written a new caption and it is still making a decision on what image to use or wants to replace the image with one that fits with the existing caption. Maybe they are trying various images and in that case it makes sense to not  lose the caption. But this is an assumption on a single case.

As a user, when I replace an image with a new one that has its own caption, I expect the caption to be there.

Edit: Also, comparing the behavior with the one that always existed in WordPress and now it's in the Classic editor, this is a change in the expected behavior that should have been considered a little more deeply IMHO.

**Comment by MadtownLems** [comment]
> As a user, when I replace an image with a new one that has its own caption, I expect the caption to be there.

This is my take as well. If I replace an Image block that already has a set caption (in the media library), I'd expect that to replace the one of the image i was using previously.

**Comment by t-hamano** [comment]
> If I replace an Image block that already has a set caption (in the media library), I'd expect that to replace the one of the image i was using previously.

I think this is already the case:

https://github.com/user-attachments/assets/63bd7221-1bca-4085-bdec-03fa7dcf6935

I think the point here is whether to keep the previous caption if the caption of the newly replaced image is empty, or to make it empty.

By the way, in the classic editor, it seems that the caption of the replaced image always takes priority, regardless of whether the caption is empty or not.

https://github.com/user-attachments/assets/ac9c2a0b-7ce6-46dd-836b-d4bd9ff80901

**Comment by t-hamano** [comment]
Contrary to this issue, it is also worth noting that some users consider the caption being replaced with the new image's caption to be a bug.

https://github.com/WordPress/gutenberg/issues/66979

**Comment by Mamaduka** [comment]
Found another related issue - #42834.

I think we need to consolidate these into a single issue and agree on some [80/20 behavior](https://wordpress.org/about/philosophy/) and implement it.

**Comment by t-hamano** [comment]
Thanks for pointing me to another issue.

Let's close this issue and continue the discussion in #42834.
