### ISSUE TITLE
[WP6.6] Select all shortcut doesn't work in modal opened from the List View

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#62478]
### Description

When a modal is opened from the List View, the shortcut to select all text (`Ctrl + a`, `command + a`) does not work in the text field inside the modal.

Instead of the text being selected, it seems to select a block of the List View.

This issue does not occur in WP6.5.

Note: I have confirmed that this problem occurs on Windows OS, but I would appreciate it if someone could test it on MacOS as well.

### Step-by-step reproduction instructions

- Insert some blocks.
- Open the List View and select one block.
- Open the "Rename" or "Create pattern" menu.
- Execute `Ctrl + a`, (`command + a`) in the text field.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/72b4d9fa-6d9f-47b0-a103-11e5364ab2cf

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by colorful-tones** [comment]
> Note: I have confirmed that this problem occurs on Windows OS, but I would appreciate it if someone could test it on MacOS as well.

Confirming that this also affects macOS (14.5 Sonoma) as well.

https://github.com/WordPress/gutenberg/assets/405912/f91d6cdd-5a75-49d4-9b55-c2020ee72f8b
