### ISSUE TITLE
Social Links in widgets area do not listen to certain block styles

### ISSUE THREAD

**Issue by FreestyleDigital** [WordPress/gutenberg#62483]
### Description

Certain block styles configured for the Social Icons block, within a widget, do not pull through to the front end.

I found this issue when trying to add block spacing between the icons, but it would never reflect on the front end. I replicated the styles within a page layout, and this worked fine - but it seems to only happen when added to a widget.

From my tests I can that these styles do not work:
- Block Spacing
- Alignments (Center, left, right, between)
- Orientation
 
<img width="1719" alt="Screenshot 2024-06-11 at 14 27 45" src="https://github.com/WordPress/gutenberg/assets/92812257/b7c9a223-fd95-4366-adc3-9eca89878cb8">

### Step-by-step reproduction instructions

1. Register a widget area
2. Navigate to Appearance > Widgets
3. Add Social Icons to the registered widget area
4. Attempt to add Block Spacing, Alignment, etc.
5. Preview in browser

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/92812257/a989ce8b-1873-41e1-b4ea-57cfa7485961

### Environment info

WP Version: 6.5.4
All browsers
Bespoke theme
I have tested on other themes, bespoke & twentytwentyfour, and the issue persists.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Anuj-Rathore24** [comment]
Hey @FreestyleDigital, 

I have tried to recreate this situation in Twenty Twenty Four theme, but apparently I am not getting the same result as you! I am adding a reference video as to what I have done. Please correct me if I am wrong.


https://github.com/WordPress/gutenberg/assets/80690679/273796d4-1720-4ca0-889e-fe2cef8795da

**Comment by FreestyleDigital** [comment]
Hi @Anuj-Rathore24, thanks for the response!

It looks like you're editing the block pattern.

I'm talking about Widget Areas here (/wp-admin/widgets.php). I understand Gutenberg is trying to move away from widgets, but I still prefer to keep my header/footer in a separate PHP file & use widgets to pull in menus, etc.

**Comment by Anuj-Rathore24** [comment]
hey, @FreestyleDigital, As widgets are not supported in twentytwentyfour theme, I cannot recreate this issue. Is there any other theme apart from bespoke( This Premium Theme is not included) in which I can try this?

**Comment by FreestyleDigital** [comment]
@Anuj-Rathore24 As you mentioned, widgets are getting more deprecated as time goes on. I've instead opted for creating Template Parts to act as "Widgets" and pulling these into PHP files with `block_template_part()`.

But thanks anyway!
