### ISSUE TITLE
Restore "Edit site" in Gutenberg plugin

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#62493]
In Gutenberg 18.5, "Edit site" shows as "Site Editor" [due to this PR](https://github.com/WordPress/gutenberg/pull/61851):

![Screenshot 2024-06-10 at 3 26 56 PM](https://github.com/WordPress/gutenberg/assets/26996883/eb23639f-40eb-417d-87f0-6168539dddc6)

This was done in line with the original changes in [this Core ticket](https://core.trac.wordpress.org/ticket/60977#comment:32) that then changed to "Edit site" for single sites and "Manage site" for multisite. We need to update Gutenberg to align with Core once more.

**Comment by up1512001** [comment]
@annezazu can you please review this PR?
https://github.com/WordPress/gutenberg/pull/62501

**Comment by akasunil** [comment]
Thank you for the contribution @up1512001

**Comment by annezazu** [comment]
Closing this out with https://github.com/WordPress/gutenberg/pull/62501 merged! Thanks, folks.
