### ISSUE TITLE
@wordpress/create-block scaffold does not load without Gutenberg

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#62517]
### Description

Following the instructions in the [Build your first block tutorial](https://developer.wordpress.org/block-editor/getting-started/tutorial/), the block is not registered and does not appear in the inserter, unless Gutenberg is activated. 

### Step-by-step reproduction instructions

1. Run `npx @wordpress/create-block copyright-date-block --variant=dynamic` in `wp-env` or a local WP environment
2. Try to insert the block in a post, verify it is not registered and does not appear in the inserter
3. Install and activate Gutenberg
4. Verify the block is registered and available via the inserter

### Environment info

- WP 6.5.4
- Gutenberg 18.5.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by amitraj2203** [comment]
This issue appears to be similar to #62202.
Also [this](https://github.com/WordPress/gutenberg/issues/62456#issuecomment-2160631004) might help.

**Comment by t-hamano** [comment]
I think this has the same cause as #62202, so I will close it.

**Comment by jffng** [comment]
Thanks @t-hamano @amitraj2203 for the triage.
