### ISSUE TITLE
Grid Block: clicking on empty grid item doesn't add a new block

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#62518]
### Description

When editing a Grid, I expected to be able to click on the outline of the empty grid item to add a block to it. It feels inconsistent with the similar UI found in the Columns Block

### Step-by-step reproduction instructions

1. Add a Grid Block
2. Type something in the first block
3. Try clicking on the outline of the grid item next to it
4. Nothing will happen

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/14153300/99513017-8c3a-4cd9-91b8-19c9fc8ad6fc

### Environment info

- WordPress 6.6 Beta 2, Gutenberg 18.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Thanks for opening the issue, it's a good idea for an enhancement! There were some aspects of grid interactivity in the editor canvas that needed more work and didn't make it in time for the WP 6.6 feature freeze. This is one of those features. I've updated the "improvements to Grid Layout" tracking issue in #57478 to link to this more explicitly for visibility.
