### ISSUE TITLE
Merge background and text color panels

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#6255]
If we merged these we would make a panel that applied to all coloring. It would also result in a better experience where right now the a11y check appears to float not connected on text coloring.

Props to @megsfulton for discovering the color check issue and prompting this.

**Comment by nic-bertino** [comment]
If I'm understanding correctly, we discussed this in #2381, particularly merging the two [here.](https://github.com/WordPress/gutenberg/issues/2381#issuecomment-328912518) Hope that context is helpful.

**Comment by karmatosed** [comment]
@nic-bertino slightly different, but thanks for adding and that issue was great as we got to get to where we are now. This idea is about bringing them both together into one panel, but having 2 options. Not the merging totally.

**Comment by karmatosed** [comment]
@SuperGeniusZeb it depends, I am not sure right now adding those would be a good option.

**Comment by karmatosed** [comment]
Here is what merging could look like. I think this does give us options for the future and aligns more with 'Text Settings' for example.

![colorcombo](https://user-images.githubusercontent.com/253067/39210404-8216d12c-4800-11e8-9cfb-c6ae11861e0e.png)

**Comment by youknowriad** [comment]
This means we lose the color shown next to the panel title. I'm fine with that, just confirming that's what we want.

**Comment by SuperGeniusZeb** [comment]
Also, from another perspective, isn't text color technically a "Text Setting"? And background color options could also be grouped with other background settings, like background images and background gradients. Of course, if non-solid-color background options are not added to any core blocks, it may make more sense to group color options into a single panel.

Additionally, will the Paragraph block even still have background color options when the Section block is added?

**Comment by karmatosed** [comment]
> This means we lose the color shown next to the panel title. I'm fine with that, just confirming that's what we want.

That's a great point, let's have 2 states for that. When closed it can show beside and when open it can show beside each relevant section:

![artboard](https://user-images.githubusercontent.com/253067/40652491-4281841c-6330-11e8-8947-7c8fc2bf181b.png)

**Comment by tofumatt** [comment]
That looks nice, but what happens when I click on one of those colours? They look directly clickable, but I'd imagine what clicking anywhere there will actually do is expand the panel.

Other sections don't show extras when hidden like that, so that seems like an inconsistent design choice.

We should remove the colours from the unexpanded header.

Otherwise looks nice though. 👍

**Comment by tofumatt** [comment]
Oh, cool, okay, I missed that. Ignore me then, I'm very green. 😅

**Comment by gziolo** [comment]
This is an excellent issue to get started with Gutenberg for anyone who likes challenges 🥇

**Comment by designsimply** [comment]
Tested and confirmed that the Paragraph Block options for `Background Color` and `Text Color` are not yet combined. Adding a screenshot for reference:

![screen shot 2018-06-25 at mon jun 25 3 51 15 pm](https://user-images.githubusercontent.com/1119271/41877793-c432f684-788f-11e8-9e81-979262a3c43e.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13830&action=edit using WordPress 4.9.6 and Gutenberg 3.1.0 with Firefox 60.0.2 on macOS 10.13.5.</sup>
