### ISSUE TITLE
theme.json schema change for spacingScale.steps warns about valid value 0

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#62561]
### Description

The [documented way](https://developer.wordpress.org/themes/global-settings-and-styles/settings/spacing/) to turn off the spacing scale (see "Disable the spacing scale" section) is to set `settings.spacing.spacingScale.steps` to `0`.

In VS Code, that now produces the warning:

> Value is below the minimum of 1.

I don't think it's directly relevant, but the recently filed #62520 is also about changes to `theme.json` schema impacting valid spacing values.

### Step-by-step reproduction instructions

1. Create a `theme.json` file
2. Use the following value and observe a warning for the value "0" on line 7 in VS Code

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"spacing": {
			"spacingScale": {
				"steps": 0
			}
		}
	}
}
```

### Environment info

- WordPress 6.5
- No Gutenberg
- Custom hybrid theme
- VS Code

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ajlende** [comment]
I see you're using the `trunk` version of the `$schema` which includes the nightly changes to theme.json and only supports the latest version. It's much better to match your schema version with the minimum supported WordPress version to be alerted of features that might not be available for your users. For example, you would use `https://schemas.wp.org/wp/6.5/theme.json` if your theme's minimum supported version is WordPress 6.5.

The minimum value for `steps` has changed in theme.json version 3 which is introduced in WordPress 6.6. The correct way to disable `spacingScale` is to set `settings.spacing.defaultSpacingScale` to `false` in version 3.

When your minimum version reaches 6.6, there is a [migration guide](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-migrations/#migrating-from-v2-to-v3) for theme.json version 3.

**Comment by mrwweb** [comment]
@ajlende Thanks for that info. I'm glad to about the migration guide. I wonder if the schema could flag the `steps: 0` with an explicit mention of `defaultSpacingSizes: false`. (updated to fix wrong property name, props @crankysparrow)

**Comment by michelleenos** [comment]
In case anyone else comes here looking for this - 

```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 3,
	"settings": {
		"spacing": {
	          	"spacingSizes": [
				...
            		],
			"defaultSpacingSizes": false,
		}
	}
}
```

The comment above indicated the setting to be `defaultSpacingScale` which didn't work for me, but got me on the right track with the migration guide. Setting `defaultSpacingSizes` to `false` did the trick! 

This is working for me on WordPress 6.6, with both the trunk version of the schema and `https://schemas.wp.org/wp/6.6/theme.json`
