### ISSUE TITLE
Synced Pattern Override: Not displaying text value properly on front-end if $ (dollar sign) added

### ISSUE THREAD

**Issue by r-interactive** [WordPress/gutenberg#62591]
### Description

There is an issue that I've noticed when using the Synced Pattern Override.
From the Site editor, I've created a Pricing Table Card Pattern. 
It has these elements (I've enabled overrides for those) :
1) Plan Label
2) Plan Cost
3) Plan Description

It's working, but the 'Cost' isn't displaying or it's messed up on the front-end. I think it's because of the '$' (dollar sign) in front.

Front-end screenshot (issue):
https://snipboard.io/7uBQiW.jpg

Block editor page screenshot :
https://snipboard.io/msHvN3.jpg

Site Editor Synced Pattern screenshot : 
https://snipboard.io/1M9xgf.jpg

When I tried adding an extra space after '$', it shows properly on the front-end. However, I don't want that extra space between the dollar sign and price.

Front-end screenshot after adding an extra space (between '$' and price):
https://snipboard.io/Qi1eFW.jpg

Is this a known issue? Can this be fixed?

### Step-by-step reproduction instructions

1.  Go to "Pages", and create a new page
2. Create a layout using the built-in blocks.
3. 3Make sure to add a 'Price' paragraph. Example content: $100
4. Select the entire layout, click the 3 dot menu and select "Create Pattern".
5.  Give the new pattern a name and make sure the 'synced' is enabled 
6. After the pattern is created, click the 'Edit original' link to edit the pattern.
7. Select the "Price" paragraph and enable override by clicking on the "Enable overrides" button (located under the 'Advanced' panel).
8.  Save the changes.
9. Click the '< Back' link to go back to the page editor.
10. Update the 'price' paragraph to something like this: $50
11. save the change and preview the page.

### Screenshots, screen recording, code snippet

Front-end screenshot (issue):
https://snipboard.io/7uBQiW.jpg

Block editor page screenshot :
https://snipboard.io/msHvN3.jpg

Site Editor Synced Pattern screenshot : 
https://snipboard.io/1M9xgf.jpg

Front-end screenshot after adding an extra space (between '$' and price):
https://snipboard.io/Qi1eFW.jpg

### Environment info

- Wordpress Version: development version (6.6-beta2)
- Theme: Twenty Twenty (FourVersion: 1.1)
- Chrome
- Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@r-interactive Thanks for reporting. This was previously reported in a couple of issues (https://github.com/WordPress/gutenberg/issues/62347, https://github.com/WordPress/gutenberg/issues/62396) and should be fixed (https://github.com/WordPress/gutenberg/pull/62355, https://github.com/WordPress/wordpress-develop/pull/6744), though I guess the fix didn't make it into beta 2 in time as it was only committed to core a few days ago.

I'll close the issue, but we can reopen it if the bug is still a problem in beta 3.
