### ISSUE TITLE
TypeError: Cannot read properties of undefined "(reading 'jsx')"

### ISSUE THREAD

**Issue by inhaledesign** [WordPress/gutenberg#62601]
### Description

Webpack is not working properly. I expect to be able to render React JSX components, however when I try to render them I get error: "TypeError: Cannot read properties of undefined "(reading 'jsx')"

### Step-by-step reproduction instructions

Download the minimal example I've attached.

1. Run `docker compose up`
2.  Run `pnpm install && pnpm run wpstart`  in the /theme directory
3. Activate the theme in Wordpress
4. restart `pnpm run wpstart`
5. Open the webpage and see error in the dev tools

Note that if I substitute the <App/> component for a string, the string will render just fine. I used create reeact app to make the React project, and it renders fine when running the regular `npm run dev` development server.

### Screenshots, screen recording, code snippet

[example theme.zip](https://github.com/user-attachments/files/15856418/example.theme.zip)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @inhaledesign,

The issue you are encountering is likely due to the new JSX transforms.

If you need to support WordPress 6.5 or lower, you will need to use `@wordpress/scripts` version 27.9 or lower.

For more information, please see the following resources:

- [JSX in WordPress 6.6 – Make WordPress Core](https://make.wordpress.org/core/2024/06/06/jsx-in-wordpress-6-6/)
- https://github.com/WordPress/gutenberg/issues/62202

**Comment by inhaledesign** [comment]
> Hi @inhaledesign,
> 
> The issue you are encountering is likely due to the new JSX transforms.
> 
> If you need to support WordPress 6.5 or lower, you will need to use `@wordpress/scripts` version 27.9 or lower.
> 
> For more information, please see the following resources:
> 
> * [JSX in WordPress 6.6 – Make WordPress Core](https://make.wordpress.org/core/2024/06/06/jsx-in-wordpress-6-6/)
> * [New block created with @wordpress/scripts@28 don't show up on wordpress #62202](https://github.com/WordPress/gutenberg/issues/62202)

That was the issue. Thank you!
