### ISSUE TITLE
 Font Library Issue: Changing themes doesn't render the font in the editor untill a refresh is done

### ISSUE THREAD

**Issue by nith53** [WordPress/gutenberg#62602]
### Description

I installed WordPress 6.6 Beta 2 and faced an issue with regard to the font library. The font library works as expected with the currently active theme, but if we switch to another theme and apply the font, the changes are not reflected in the editor but can be seen in the front end. Now if we refresh the editor, we can see the font is applied.

Track ticket link- https://core.trac.wordpress.org/ticket/61417

### Step-by-step reproduction instructions

Testing Instructions
Activate Twenty Twenty-Four theme
Upload a font
Activate it for headings and text
The font is reflected properly in the editor and the front end
Now switch to the Twenty Twenty-Three theme
Activate the font
Apply the font
We can see it is not rendered in the editor
Preview the website in a new tab and the font is reflected properly in the front end
Refresh the editor and now we can see that the applied font is properly applied

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/141323754/c817e091-c1e6-4064-bd57-9821f8d097a9

### Environment info

Testing Environment
WordPress: 6.6-beta2-58392
PHP: 8.2.4
Server: Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.2.4
Database: mysqli (Server: 10.4.28-MariaDB / Client: mysqlnd 8.2.4)
Browser: Chrome 109.0.0.0 (Windows 10/11)
Theme: Twenty Twenty-Four 1.1
MU-Plugins: None activated
Plugins:
WordPress Beta Tester 3.5.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
Thoughts @matiasbenedetto?

**Comment by matiasbenedetto** [comment]
Thanks for reporting the issue.
I could reproduce the bug. I'm testing a potential fix for this. I'll try to submit a PR as soon as possible.

**Comment by matiasbenedetto** [comment]
I submitted a PR with a potential fix for this issue: https://github.com/WordPress/gutenberg/pull/62614
