### ISSUE TITLE
wp-env: $schema property is not allowed

### ISSUE THREAD

**Issue by sirreal** [WordPress/gutenberg#62619]
#36276 added a JSON schema for wp-env, but if the `$schema` property appears in wp-env configuration, it throws an error:

```
Invalid /Users/jonsurrell/a8c/wordpress-develop/trunk/.wp-env.json: "$schema" is not a configuration option.
```

It should allow that property, or possibly even better use the schema to parse configuration.

_Originally posted by @sirreal in https://github.com/WordPress/gutenberg/issues/36276#issuecomment-2173085546_

**Comment by t-hamano** [comment]
Perhaps we need to submit a PR to [the Schema Store repository](https://github.com/SchemaStore/schemastore), as was done by [theme.json](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/theme-v1.json) and [block.json](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/block.json)?

For example, if I directly reference the schema in the Gutenberg repository, it works correctly.

![image](https://github.com/WordPress/gutenberg/assets/54422211/85998ddd-0bc6-4d69-a2e0-cc001fa1a456)

However, if I use the same format as `block.json` or `theme.json`, it doesn't work.

![image](https://github.com/WordPress/gutenberg/assets/54422211/3195a5c7-b86b-4abd-ae42-47781caf6613)

Maybe @ajlende or @gziolo know something about this.

**Comment by sirreal** [comment]
> Perhaps we need to submit a PR to [the Schema Store repository](https://github.com/SchemaStore/schemastore), as was done by [theme.json](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/theme-v1.json) and [block.json](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/block.json)?

Yes, we should do that, but that's just for inclusion in that directory of schemas.

The issue here is that the tool itself rejects configuration values that it does not recognize:

https://github.com/WordPress/gutenberg/blob/708ce27fa10cd2249fa660823ba800c2f912cba0/packages/env/lib/config/parse-config.js#L415-L438

**Comment by ajlende** [comment]
> However, if I use the same format as `block.json` or `theme.json`, it doesn't work.

There must be a whitelist for the wp.org redirects somewhere. We made a [systems request for the initial JSON Schema](https://make.wordpress.org/systems/2021/11/03/redirects-for-json-schemas/). I don't seems to have access to make a systems request, so I'm asking around to get it fixed.

**Comment by ajlende** [comment]
I think I know what's going on. The redirects probably don't support dotfiles. I checked the schemastore website and they don't do dotfiles either. I think we should follow their lead and use wp-env.json for the filename instead.

EDIT: Opened https://github.com/WordPress/gutenberg/pull/62634
