### ISSUE TITLE
Site Editor: Unable to select specific template on mobile

### ISSUE THREAD

**Issue by ivan-ottinger** [WordPress/gutenberg#62649]
### Description

When navigating to the Site Editor using a mobile-sized viewport, it is not possible to tap templates (please see the screen recording below).

The issue can be reproduced with versions higher than `16.4.0`.

### Step-by-step reproduction instructions

1. Use a mobile-sized viewport.
2. In wp-admin, open the navigation, and open the site editor (Appearance → Editor).
3. Select "Templates"
4. Attempt to select a template.

### Screenshots, screen recording, code snippet

Here is the screen recording of the issue:

https://github.com/WordPress/gutenberg/assets/25105483/bf62463c-70d6-458d-a5e1-107b5ddfc806

### Environment info

Higher than `16.4.0`, e.g. `16.5.0` or `18.6.0-rc.1`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
Also affects patterns. I'm looking at this over in:

- https://github.com/WordPress/gutenberg/pull/63002
