### ISSUE TITLE
Rename modal throws error when post type does not support title

### ISSUE THREAD

**Issue by Dartui** [WordPress/gutenberg#62652]
### Description

Some time ago "Actions" dropdown was added to the Gutenberg which has actions like "Rename" or "Duplicate".

![image](https://github.com/WordPress/gutenberg/assets/2657856/4b806d05-d457-4df7-bca6-5ad46ff1d2bd)

However those actions does not care about `title` supports set when CPT is registered and whole editor crashes when you try to Rename posts that does not support title.

### Step-by-step reproduction instructions

1. Create new post type without `title` in `supports` argument (see screenshot)
2. Create new post
3. Save new post
4. Refresh page
5. Open "Actions" dropdown
6. Click "Rename"

### Screenshots, screen recording, code snippet

CPT register function:
<img width="295" alt="image" src="https://github.com/WordPress/gutenberg/assets/2657856/ebc72192-b5aa-4e0c-8ecf-a94f388958e7">

Error:
![image](https://github.com/WordPress/gutenberg/assets/2657856/71cab622-f9df-46c7-8e61-0ba1dfcf6d86)

### Environment info

- WordPress 6.5.3
- Gutenberg 18.5.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This issue has already been resolved in #62248 and has been backported to the WP6.6 release. WP6.6 Beta3 should not have this issue.

Code used for testing: 

```php
function create_my_post_types() {
	register_post_type(
		'faq',
		array(
			'public'       => true,
			'label'        => 'FAQ',
			'show_in_rest' => true,
			'supports'     => array(
				'editor',
			),
		)
	);
}
add_action( 'init', 'create_my_post_types' );
```

![title-support-post-actions](https://github.com/WordPress/gutenberg/assets/54422211/b2289de3-edb6-4611-ad76-11bb566f5882)
