### ISSUE TITLE
Allow dragging block from hover title

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6265]
## Issue Overview
Currently, the block type is shown when you hover over the left side of a block. I feel like you should be able to drag the block from that title. Currently, the title does not do anything other than tell you what block you are hovering over. If it was a drag-point, it would make the hover title more useful, as well as make it easier to move smaller blocks by providing a fairly large drag handle that is clearly visible, unlike the thin and invisible drag handles on the sides of blocks.

## Related Issues and/or PRs
#6032

**Comment by SuperGeniusZeb** [comment]
One neat idea that could go with this would be showing a drag handle icon when you hover over the hover title, indicating that you can drag the block from there. This could reduce the need for a dedicated drag handle button.

**Comment by karmatosed** [comment]
Closing to bring discussion to #6032

**Comment by designsimply** [comment]
Moved to #7114
