### ISSUE TITLE
Block Bindings - Assigning meta in a Pattern produces preview error.

### ISSUE THREAD

**Issue by dannyreaktiv** [WordPress/gutenberg#62664]
### Description

I am using a Pattern within a Custom Post Type.

Within the Pattern are bindings with the source set to `core/post-meta`. Everything is working great on the front-end:

<img width="679" alt="Screenshot 2024-06-18 at 9 47 21 AM" src="https://github.com/WordPress/gutenberg/assets/90352979/50baa892-8568-4c07-a55d-8feec37b3e90">

And for the back-end when editing the Post which has the Pattern. The post's meta correctly displays in the blocks:

<img width="741" alt="Screenshot 2024-06-18 at 9 48 27 AM" src="https://github.com/WordPress/gutenberg/assets/90352979/55fabfeb-ead6-4549-8523-6dbfaf0f3d73">

However, in the back-end, when editing the Pattern (`wp_block`) by itself, there are preview errors…

<img width="747" alt="Screenshot 2024-06-18 at 9 46 57 AM" src="https://github.com/WordPress/gutenberg/assets/90352979/4312a35d-4a22-41ae-ac26-17e4ca9ba94a">

And the console says…

```
TypeError: undefined is not an object (evaluating 'meta[metaKey]')
The above error occurred in the <BindingConnector> component
```

Which, I get, the meta is not available because it hasn't been registered or is available for `wp_block`. 

Would there be a way to silence these missing meta keys when editing a Pattern, or provide default content so I can still edit the block's attributes (styles, dimensions, etc.)? 

### Step-by-step reproduction instructions

1. Create a Pattern (`wp_block`). 
2. Binding a block within the pattern to a meta field that hasn't been registered: `"metadata":{"bindings":{"content":{"source":"core/post-meta","args":{"key":"player_college"}}}},`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
> TypeError: undefined is not an object (evaluating 'meta[metaKey]')
> The above error occurred in the <BindingConnector> component

@dannyreaktiv Thanks for reporting the issue. I believe the `BindingConnector` mentioned in the error message is from an older implementation of block bindings. Which versions of WordPress/Gutenberg are you using?

The WordPress 6.6 beta and more recent versions of the Gutenberg plugin don't seem to have this error in my testing, so hopefully your issue has been resolved already.

**Comment by talldan** [comment]
I'll close the issue, but it can be re-opened if this is something that's still reproducible.
