### ISSUE TITLE
Outline button variation slow-load styles in TT4

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#62668]
### Description

Likely a bi-product of work done in https://github.com/WordPress/gutenberg/issues/62451, there seems to be a lag during the styling in the editor (on page load) for buttons with the outline variation. (Original issue was fixed, now the lag exists)

### Step-by-step reproduction instructions

1. Go to a post or page and add the buttons block.
2. Create a button, apply Outline variation.
3. See bug.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/486261/ba34769f-fbc6-4efb-ab4d-aaaed3b23cfd

### Environment info

WordPress 6.6 beta3 (Gutenberg NOT active)
Issue goes away with Gutenberg 18.5 active.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by bgardner** [comment]
cc: @aaronrobertshaw @ellatrix

**Comment by aaronrobertshaw** [comment]
Thanks for flagging this @bgardner 👍 

I'm not sure what the cause is yet however it does appear isolated to the post editor as there is no styling flash in the site editor. My hunch is the variation styling in the post editor relies on global styles data set in the editor settings which is likely loaded asynchronously causing the delay.

**Comment by bgardner** [comment]
@aaronrobertshaw Can confirm the site editor does not experience the lag. Can you confirm the lag in the post editor on your end?

**Comment by aaronrobertshaw** [comment]
> Can you confirm the lag in the post editor on your end?

Yes, I tested this before making my prior comment that the issue is isolated to the post editor.

I've checked with and without Gutenberg active using the latest 6.6 beta.

**Comment by justintadlock** [comment]
I was just coming to report this. I'm always seeing this flash of the wrong style when loading the Post Editor.

**Comment by bgardner** [comment]
Maybe we can get this resolved in RC2?

**Comment by aaronrobertshaw** [comment]
I'd like to think we can come up with something for this as quickly hacking around providing the global styles data from the server side initially, as a fallback, successfully prevented the flash of styles. 

It will need some deeper thought though to be able to come up with a proper solution that doesn't negatively impact performance too much.

**Comment by aaronrobertshaw** [comment]
I have a potential fix for the flash of variation styles in the post editor up in https://github.com/WordPress/gutenberg/pull/63071.
