### ISSUE TITLE
Clicking Permalink after publishing page shows Preview url rather than live url

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#6267]
## Issue Overview
After publishing a page, clicking the Permalink (above the title) takes you to a URL with `/?preview=true` on the end of it, rather than just the proper live url.

As an example, if I publish a page at `https://mysite.com/my-page`, clicking on the Permalink takes me to `https://mysite.com/my-page/?preview=true` instead of just `https://mysite.com/my-page`.

Using the classic editor, after publishing, you're always taken to the live url.

## Steps to Reproduce (for bugs)
1. Open a page that has been published
2. Click Permalink above title

## Expected Behavior
Once a page has been published, I would expect the Permalink to take me to the proper live url, just like it does in the current version of WordPress.

## Current Behavior
Permalink appends `/?preview=true` on the end of the url after page is published

_Gutenberg 2.7.0
Firefox Quantum 59.0.2 (64-bit)
WP 4.9.5_

**Comment by pento** [comment]
Thanks for the bug report, @maddisondesigns! You're correct, after publishing the Permalink should go to the live URL: only the "Preview" button (once Preview is working for published posts 😉) should add the `preview` parameter.
