### ISSUE TITLE
Site editor: WP logo focus style regression

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#62672]
### Description

The focus style of the WP logo in the Site editor is now barely visible and not standard.

This is the focus style on WordPress 6.5:

![wp 6 5](https://github.com/WordPress/gutenberg/assets/1682452/389b1f35-deeb-4dad-9feb-dd1cd3976735)

This is the focus style on Gutenberg trunk:

![trunk](https://github.com/WordPress/gutenberg/assets/1682452/d70dd2ad-b9bd-4db3-be3c-07f375d19c15)

The WP logo uses a custom implementation of the focus style. I _think_ the regression comes from the fact the `transform scale` CSS is now applied to the link element itself while previously it was applied to the inner div element.

### Step-by-step reproduction instructions

- Go to the Site editor.
- Tab to the WP logo.
- Observe the focus style is barely visible and not standard.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by up1512001** [comment]
@afercia moved the `focus` from before to the `a` tag itself in this PR.
https://github.com/WordPress/gutenberg/pull/62675
