### ISSUE TITLE
Consider showing the permalink UI when hovering over Title

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#6268]
## Issue Overview
In the current version of WordPress it's super easy to tell what your page url is going to be as it's very conveniently displayed beneath the page title.

Gutenberg has turned something that was really convenient into something that's not. You now have to actually click on the page title before you can edit the Permalink or even view it. This is an annoying extra step and it's not some that people are going to expect.

At the very least, the Permalink should show when hovering over the page title.

## Steps to Reproduce (for bugs)
1. Open any page
2. Try to view the Permalink without clicking on anything

## Expected Behavior
I shouldn't have to click on a block to find out what my Permalink it. It's really annoying and frustrating and is yet another process that Gutenberg has mad more difficult than what it currently is.

## Current Behavior
Users need to physically click on the Page title before they can view their page permalink.

## Possible Solution
Either show the Permalink all the time or at the very least, show it when hovering over the page title.

_Gutenberg 2.7.0
Firefox Quantum 59.0.2 (64-bit)
WP 4.9.5_

**Comment by SuperGeniusZeb** [comment]
I am in favor of showing it on hover. I do not think it is necessary to show it all the time (and the UI looks cleaner without it, in my opinion), but showing it on hover makes it simple enough to find and see when you want to find and see it, and increases the discoverability of the permalink.

**Comment by danielbachhuber** [comment]
Flagging `Needs Design Feedback` to see if this is behavior we want to change.

**Comment by karmatosed** [comment]
I think having it show on hover is ok in this case.

**Comment by wpmark** [comment]
I think that having the permalink only editable behind a title box makes no sense here and should be visible somewhere else on the page, or at least be behind a button with the "Permalink" label. It took me about 5 minutes to find where this was.

**Comment by SuperGeniusZeb** [comment]
I agree with @wpmark that it is weird to have the permalink only editable from the title, especially considering the future where the title would become a block and you could theoretically have a post type where you don't even show the title, but you still need a way to edit the permalink. I think the permalink should be editable from the document settings inspector/sidebar.

**Comment by SuperGeniusZeb** [comment]
Why can't it be shown in both the sidebar _and_ when selecting (and/or hovering) the post title?

**Comment by karmatosed** [comment]
> Why can't it be shown in both the sidebar and when selecting (and/or hovering) the post title?

For a moment think about it from a few perspectives:
- Smaller screens (they can't and shouldn't depend on the sidebar)
- Blocks active (they show a different sidebar)

Having this UI showing in up to 3 places is a very confusing experience. As you process through having it there makes a lot of sense, I would encourage that change, testing and potentially revisiting based on outcome.

**Comment by wpmark** [comment]
For now it makes sense to me, to either show this all the time (after all, its space is always present, but it just shows on hover) or move it to the sidebar (which is how Calypso does it).

**Comment by iandunn** [comment]
I had trouble finding it as well. It never occurred to me that I'd need to click on the title to see it. I can see how that makes sense now that I know that's how it works, but I wonder how many existing users will be tripped up by that. I just came across [a forums report](https://wordpress.org/support/topic/cannot-edit-permalink-and-always-switches-to-simple-version/#post-10678802) where the user seems to be confused about that as well.

**Comment by youknowriad** [comment]
We have a new panel for permalinks now #11874. This issue is not relevant anymore
