### ISSUE TITLE
Global Styles: Active variation not shown when using block variations

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#62758]
## What problem does this address?
If style variations contain block variations then the UI doesn't recognise which style variation is active, for example, using the Assembler theme, with the blueberry variation active, but not shown as active in the UI
<img width="356" alt="Screenshot 2024-06-21 at 18 33 11" src="https://github.com/WordPress/gutenberg/assets/275961/d8e5603e-7248-4af2-832a-c98fe8e4c6db">

## What is your proposed solution?
We need to update `areGlobalStyleConfigsEqual` so that it is aware of block variations and can correctly compare the current user settings with a style variation.

**Comment by aaronrobertshaw** [comment]
I haven't been able to replicate this issue using Gutenberg `trunk`. I think we might be able to close it.

More details in this [review](https://github.com/WordPress/gutenberg/pull/62798#pullrequestreview-2137191552).
