### ISSUE TITLE
Gradient colors on headlines, text like doing on buttons

### ISSUE THREAD

**Issue by Tobias-Conrad** [WordPress/gutenberg#62766]
## What problem does this address?
add gradient to headlines H1, H2, and all texts.
Most big players like apple did do color gradient, good to have it possible too.
live example https://www.videosdk.live/
![image](https://github.com/WordPress/gutenberg/assets/7352673/c695d744-3f18-456b-aac3-c517f8a21c4f)

## What is your proposed solution?
add the same gradient function existing on buttons
see screenshot:

![image](https://github.com/WordPress/gutenberg/assets/7352673/79acee30-ab76-41a3-ad67-daf4dc193bdc)

**Comment by akasunil** [comment]
Duplicate issue of https://github.com/WordPress/gutenberg/issues/49642
