### ISSUE TITLE
Categories List Block: Add custom taxonomies support

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#62773]
## What problem does this address?
The Categories List block (`core/categories`) can display a list of categories in various formats.

![image](https://github.com/WordPress/gutenberg/assets/54422211/7d28f002-b720-4cff-ab0e-6b54eb7d7ce9)

This block currently only supports built-in `category` taxonomy, so we cannot display a list of terms from custom taxonomies.

![categories](https://github.com/WordPress/gutenberg/assets/54422211/4d680988-ba74-4b76-85fe-eda31dfccd90)

However, this block uses [wp_dropdown_categories()](https://developer.wordpress.org/reference/functions/wp_dropdown_categories/) function internally, and the `wp_dropdown_categories()` function supports `taxonomy` parameter, so we should be able to support custom taxonomies.

## What is your proposed solution?

The approach I propose is to automatically register registered public taxonomies as variations, similar to [the implementation in the Post Terms block](https://github.com/WordPress/gutenberg/blob/950f5c8239b6e78e9051ec5e845bac5aa863c4cb/packages/block-library/src/post-terms/index.php#L70).

**Comment by devanshijoshi9** [comment]
Very beneficial enhancement ➕ I will look into this and raise a PR 👍

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. This already has been reported at https://github.com/WordPress/gutenberg/issues/51388 and https://github.com/WordPress/gutenberg/issues/33302 . You can track its progress at those issues.
