### ISSUE TITLE
Latest Posts Blocks don't retrieve content reliably

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#6277]
## Issue Overview
The Latest Posts block don't always retrieve the Latest Posts.

I had a page with 2 Latest Posts blocks (image below), and when I tried to edit the page, none of them showed any content.

I also had a page with 6 Latest Posts blocks (showing the different options such as Grid, List, Wide etc). Out of 6 Blocks, 3 showed content and 3 didn't.

![gutenberg-latestposts](https://user-images.githubusercontent.com/2078245/38987381-da3b9f64-4412-11e8-93d3-ebfd85765a24.gif)

## Steps to Reproduce (for bugs)
1. Insert multiple Latest Posts blocks into content and save
2. Close page
3. Edit page with Latest Posts Blocks

## Expected Behavior
Latest Posts Block should always show content when editing the page

## Current Behavior
Latest Posts Block don't reliably retrieve content

_Gutenberg 2.7.0
Firefox Quantum 59.0.2 (64-bit)
WP 4.9.5_

**Comment by pento** [comment]
Thanks for the bug report, @maddisondesigns!

I'm able to reproduce the same behaviour, there seems to be a race condition somewhere in the API response handling. I'll have to do a bit more digging to see what's going on.
