### ISSUE TITLE
Pattern Overrides: Unable to set some attributes like Image block Aspect Ratio when editing the original pattern

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#62814]
### Description

When editing the original pattern and the block has overrides active, some attributes like 'aspect ratio' don't work.

This is a side effect of https://github.com/WordPress/gutenberg/pull/62471, which disabled regular attribute updates for any block with a `__default` pattern override binding. The intention of that PR was to only affect pattern instances to stop situations where edits could be applied to 'locked' parts of blocks. However, it also affects the block when editing the original pattern.

I think it may be worth reverting that PR, even though reverting will cause two new issues:
- The original issue that #62471 tried to solve, captions could incorrectly be set via the media library for overridden blocks in pattern instances, but the value doesn't persist when saving
- For editing the original pattern, #62747 tried to solve an issue where users can display a caption for an image block with overrides, even though captions aren't supported. #62471 disallows setting the caption, but also disallows setting any other unbound attributes too.

### Step-by-step reproduction instructions

1. Create a pattern
2. Add an image block
3. Enable bindings for the image block
4. Upload an image to the block
5. Try adjusting Aspect Ratio, observe it doesn't work.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by SantosGuillamot** [comment]
I have started [this pull request](https://github.com/WordPress/gutenberg/pull/62828) trying to solve the issue.
