### ISSUE TITLE
Consider to change from "More" to "Toolbar Toggle"

### ISSUE THREAD

**Issue by Rahmon** [WordPress/gutenberg#6281]
## Issue Overview
In Classic editor, the icon highlighted below has the tooltip "Toolbar Toggle". But in Gutenberg the tooltip is just "More". So I propose change to "Toolbar Toggle".

![screen shot 2018-04-19 at 08 23 38](https://user-images.githubusercontent.com/6010232/38988834-07f3b3f0-43ab-11e8-8423-9b7237da89be.png)

**Comment by spencerbaynton** [comment]
Duplicate of #6198.

**Comment by karmatosed** [comment]
Closing as duplicate, we can always reopen if this isn't agreed.
