### ISSUE TITLE
Block Remove button misplaced on full-width blocks

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6283]
Noticed while working on #6279: when a block is full-width, the "Remove" button which is now displayed after the ellipsis one, is misplaced (should be placed horizontally I guess):

<img width="1068" alt="screen shot 2018-04-19 at 14 03 27" src="https://user-images.githubusercontent.com/1682452/38990533-f11a535c-43da-11e8-8ea9-8b3ee1aa1fac.png">

**Comment by Rahmon** [comment]
I think this got fixed.

![gb](https://user-images.githubusercontent.com/6010232/41186425-a845b2b6-6b6c-11e8-88e9-ca040183e6d6.png)

**Comment by mtias** [comment]
This button is no longer present.
