### ISSUE TITLE
Post Editor: `⌘+a` shortcut closes the renaming modal and changes focus

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#62831]
### Description

When renaming a block in the post editor, the `⌘+a` shortcut closes the renaming modal; instead of selecting the text, it selects all the blocks on the canvas.

This only happens when editing a post/page, not on the site editor.

### Step-by-step reproduction instructions

1. Go to edit a post or page
2. Open the List View
3. Click on the ellipsis points and select `Rename`
4. Hit `⌘+a `to select all the text; it will close the modal and select all the blocks on the canvas instead

### Screenshots, screen recording, code snippet

![microsite](https://github.com/WordPress/gutenberg/assets/27339341/4f7d94b7-607b-4362-b12f-ce983fd411e4)

This is how it's supposed to work, as seen on the site editor:
![rename command a](https://github.com/WordPress/gutenberg/assets/27339341/c0d55d9e-5420-4306-95fd-6712ad4744ba)

Props to @jasmussen for finding the bug and sharing the gifs.

### Environment info

- WordPress 6.5.5, Gutenberg trunk (18.6.1)
- Checked on MacOs, to be confirmed if it happens in Windows/Linux with `Control+a`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I'm pretty sure @t-hamano fixed this bug in #62479.

**Comment by jasmussen** [comment]
That would explain why I've been able to reproduce it in some cases, but not others.

**Comment by Mamaduka** [comment]
Let's close this. I can't reproduce the issue on the trunk.
