### ISSUE TITLE
Improve Lock modal description and options naming

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#62843]
### Description

Splitting this out from https://github.com/WordPress/gutenberg/pull/62795

The description of the Lock modal dialog and the naming of the various options could use some more clear wording.

Screenshot:

![Screenshot 2024-06-25 at 15 55 20](https://github.com/WordPress/gutenberg/assets/1682452/418452ca-d278-4ade-a228-8fbb431b9d8b)

1
The description: `Choose specific attributes to restrict or lock all available options.`

Note: after https://github.com/WordPress/gutenberg/pull/62795 the description will become the `<legend>` element of the form fieldset, thus it will be used to give the fieldset group a name.

Issues:
- The text is too long. It would benefit from being more concise.
- Visually, the checkboxes order is: 'Lock all' first, the other options after. However, the current description first mentions the other options, and then the ability to lock all. As such, when reading the description, there is a logical mismatch with the visuals that doesn't help with immediately understanding the interface.
- As a user, I have no clue what the difference between 'attributes' and 'options' is. I'm not sure introducing these two concepts helps with understanding the UI. I'd rather propose to simplify. Users just want to lock either all or some _features_.

2
The options naming.
The specific 'options' use three different verbs:
- Restrict
- Disable
- Prevent

While, technically, they may be the most correct verbs to use, I'd argue that by using different verbs this UI adds unnecessary cognitive load. As a user, my experience would be:
- Click on a menu item called 'Lock'.
- A modal dialog named 'Lock {block name}' opens.
- The first option I see is named 'Lock all'.
- But, suddenly, the following options are Restrict / Disable / Prevent.
- At this point, I may wonder what the difference is between Lock / Restrict / Disable / Prevent, if any, and get a little confused.

I'd like to propose to drastically simplify. This is a feture to 'lock things'. How about:
- Lock all
  - Lock editing
  - Lock movement
  - Lock removal
 

### Step-by-step reproduction instructions

- To see all the available options in the Lock modal dialog, add a Navigation block.
- Select the Navigation block and from its toolbar choose Options > Lock.
- Observe the wording of the description and of the options.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mtias** [comment]
This panel will also absorb content-only locking, so a thorough review of all the copy should take that into account. The whole set of access control properties and how to best communicate it to people. It can get complex fast.

**Comment by sarthaknagoshe2002** [comment]
### Here is what i would like to propose
## Proposed Description:

1. `Choose "Lock all" to disable all actions, or select specific actions to lock.`
2. `Choose "Lock all" to disable all actions, or select specific features to lock.`

### Reasoning:

1. Simplifies the language.
2. Aligns with the visual order where "Lock all" is the first option.
3. Avoids unnecessary jargon like "attributes" and "options," focusing on user intent.

## Proposed Option Names:

- `Lock all`
- `Lock editing`
- `Lock movement`
- `Lock removal`

### Reasoning:

1. Consistent use of "Lock" makes the interface intuitive.
2. Simplifies the mental model for users—everything is about "locking."
