### ISSUE TITLE
Featured Image Panel: Text is not fully visible when dragging a file

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#62841]
### Description

If the Featured Images has not been set yet to a post, the button size, i.e. the height of the drag destination area, is 40px. At this height, the icon and text will not be fully displayed:

![WP6 6](https://github.com/WordPress/gutenberg/assets/54422211/faaa0c97-e821-41d8-929f-f86b771ca9ff)

This issue can be reproduced in WP6.6 or the latest Gutenberg, but not in WP6.5 because the UI is different:

![wp6 5](https://github.com/WordPress/gutenberg/assets/54422211/ad627de5-99cc-4d95-a108-4cb0259ba6f6)

The three solutions I can think of are:

| Make text visually hidden | Increase the button height slightly | Align icons and text horizontally |
|--------|--------|--------|
| ![suggest_1](https://github.com/WordPress/gutenberg/assets/54422211/cc4566fd-bc9c-447e-8422-7efc9b1e44b8) | ![suggest_2](https://github.com/WordPress/gutenberg/assets/54422211/0fb74b00-fe50-4c09-bd9c-a7dff1c44cf8) | ![image](https://github.com/WordPress/gutenberg/assets/54422211/2eb4798e-f1fd-4496-bd89-4ebefe2d8005) | 

cc @WordPress/gutenberg-design If you have any other ideas, please let me know.

### Step-by-step reproduction instructions

- Open the post editor.
- Move the file to the "Set featured Image" button.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Good issue. Icon left, text on the right, as well as visually hidden text, both feel like solid solutions. I want to avoid making the button bigger, as it's already received prominence by being moved to the top of the panel.

**Comment by t-hamano** [comment]
@jasmussen Thank you for your feedback! I'll try to work on this issue. I'll add it to the WP6.6 project board, but it seems the editor package for RC1 has already been committed, so it might not ship in time for WP6.6.

**Comment by annezazu** [comment]
Just came here to report the same thing :) Thanks for reporting and already starting on a fix. I hope we can get it into 6.6.
