### ISSUE TITLE
Dropcaps Override Typeface

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#6284]
## Issue Overview

When using a dropcap, the typeface is incorrect

## Steps to Reproduce (for bugs)

1. Create a Dropcap on a paragraph
2. Preview on the frontend
3. Compare upper case letter to dropcap

Tested in Chrome 65 under Mac OS 10.13.4

## Expected Behavior

I expected the dropcap typeface to match the main body or heading

## Current Behavior

The typeface does not match, compare the A in the top heading to the A in the dropcap:

<img width="214" alt="screen shot 2018-04-19 at 13 36 13" src="https://user-images.githubusercontent.com/58855/38991895-ffde478a-43d6-11e8-84ef-12e64b3696ae.png">

## Possible Solution

In this file, the CSS GB applies sets the dropcap to a Serif style:

https://github.com/WordPress/gutenberg/blob/dab685077d64b649489520f462985c0315cfec65/blocks/library/paragraph/style.scss#L23

```
	&.has-drop-cap {
		&:first-letter {
...
			font-family: serif;
			font-weight: 600;
...
		}
	}
```

Instead, either no font-family should be specified, or `inherit` should be used

**Comment by aduth** [comment]
Closed by #6294 

For future reference, you can use keywords to automatically close related issues from pull requests. See: https://help.github.com/articles/closing-issues-using-keywords/
