### ISSUE TITLE
WP 6.6 RC 1: Image cropping fails in the block editor

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#62855]
### Description

When going to crop an image in the block editor while running WP 6.6 RC 1, the image is not cropped after applying a crop.

The issue appears to be caused by something in core, and not in the Gutenberg plugin, as the values being sent to the media/edit endpoint have not changed.

## Related issues:

* https://github.com/WordPress/gutenberg/pull/62854 — the attempt to reinstate the e2e test for image cropping
* https://core.trac.wordpress.org/ticket/32282#comment:28 — trac ticket related to recent changes to image cropping in core
* https://core.trac.wordpress.org/ticket/59782 — a similar trac ticket related to recent changes to image cropping. Reverting the changes in that trac ticket appear to get the cropping tools working again.

### Step-by-step reproduction instructions

1. Run WP 6.6 RC 1
2. Add an image block to a post
3. Click on the Crop tool in the block toolbar
4. Select a Crop from the aspect ratio dropdown
5. Click Apply
6. Note that the Crop has not applied

### Screenshots, screen recording, code snippet

In the below screenshot, an aspect ratio of `1:1` is selected and should be applied, but the returned image from the API endpoint does not include any cropping:

https://github.com/WordPress/gutenberg/assets/14988353/63a9cd0c-7950-4c08-b695-0a9706dcbc7d

### Environment info

- WP 6.6 RC 1
- Gutenberg not active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Update: reverting https://github.com/WordPress/wordpress-develop/pull/6876 locally appears to get the image cropping working again for me. I'll comment over on the related trac ticket: https://core.trac.wordpress.org/ticket/59782

**Comment by andrewserong** [comment]
A potential fix: https://github.com/WordPress/wordpress-develop/pull/6909

**Comment by talldan** [comment]
I believe this was fixed by https://github.com/WordPress/wordpress-develop/pull/6909

**Comment by andrewserong** [comment]
Thanks for updating! Yes it was fixed in https://github.com/WordPress/wordpress-develop/pull/6909, but it [hasn't yet been committed to the RC](https://core.trac.wordpress.org/ticket/61514#comment:8). Since it was missed for RC 2, I'm just going to reopen this for visibility so it doesn't get missed for RC 3. I've moved this back to the "needs core commit" column. Hope you don't mind!

**Comment by annezazu** [comment]
Successfully landed in RC3 per https://core.trac.wordpress.org/ticket/61514 Closing out!
