### ISSUE TITLE
Navigational dead end on smaller viewports

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#62878]
On smaller viewports, once you navigate into a data view in the Site Editor (e.g. Pages or Patterns), you end up stuck in that view. There's no way to return to the main navigation, or (in the case of Patterns & Templates) open the Editor.

https://github.com/WordPress/gutenberg/assets/846565/352ff578-54ea-4d67-8b8e-d3fb9c401352

Related: https://github.com/WordPress/gutenberg/issues/60847.

**Comment by youknowriad** [comment]
I think there's two issues here:

 - Not having the ability to return to previous pages: I think this is arguable because you can always click back in your browser but I agree that it's inconsistent with desktop and we might want to bring a navigation bar/breadcrumb on top.


 - The fact that you can't navigate to the editor is the most concerning one and would love to have it fixed for 6.6. So I'm temptatively adding this issue to 6.6 for this issue.

**Comment by jameskoster** [comment]
> I think this is arguable because you can always click back in your browser

True, but that will not work well in the following common flow: `Open site editor → Pages → Select page → Edit → Click (W) Button → Click browser back button`.

In this case the back button would return you to the Editor.

**Comment by t-hamano** [comment]
Perhaps it's related to #62106 as well?

**Comment by ramonjd** [comment]
> Not having the ability to return to previous pages: I think this is arguable because you can always click back in your browser but I agree that it's inconsistent with desktop and we might want to bring a navigation bar/breadcrumb on top.

You can use the browser's back button and it will take you back, but only back to where you came from. 😄 

 So if you click into Templates, and then to the Editor (you'll need https://github.com/WordPress/gutenberg/pull/63002), and then back to Templates, clicking the browser's back button will take you back to the Editor. 


https://github.com/WordPress/gutenberg/assets/6458278/d611fcc0-f951-4010-8da4-adad628359b4



It would useful to be able to navigation back to the Design menu directly. 

I didn't have a lot of time, but I hacked together a very quick workaround for this. 

https://github.com/WordPress/gutenberg/assets/6458278/2f7bead0-d722-4b0d-980d-d657f2a67f2a

> The fact that you can't navigate to the editor is the most concerning one and would love to have it fixed for 6.6. So I'm temptatively adding this issue to 6.6 for this issue.

Agree, this one is the blocker. Looking at a fix over in https://github.com/WordPress/gutenberg/pull/63002

**Comment by oandregal** [comment]
I've prepared https://github.com/WordPress/gutenberg/pull/63060 as a potential quick change for 6.6.

**Comment by youknowriad** [comment]
This seems fixed right, can we close it?

**Comment by t-hamano** [comment]
I think we can close this issue too. If other issues arise, I'm sure we can address them in a new issue.
