### ISSUE TITLE
Cannot edit templates on smaller viewports

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#62884]
Possibly related to https://github.com/WordPress/gutenberg/issues/62878.

On smaller viewports, clicking a template on the Templates data view does not take you to the editor.

On desktop, if you navigate to edit a template then resize the viewport down then you get kicked back to the data view. 

Here's a video better describing the problem:

https://github.com/WordPress/gutenberg/assets/846565/85dc6be0-3256-497b-9a02-156a77d9adb9

**Comment by annezazu** [comment]
This is a duplicate of: https://github.com/WordPress/gutenberg/issues/62649 Closing out.
