### ISSUE TITLE
[Group Grid] blocks are getting hide behind the Group Grid block

### ISSUE THREAD

**Issue by toheed021** [WordPress/gutenberg#62916]
### Description

When enable the sticky option from Group Grid block then blocks move behind the grind 

- WordPress: 6.6-RC1
- PHP: 7.4.33
- Server: nginx/1.25.3
- Database: mysqli (Server: 10.11.8-MariaDB-ubu2204 / Client: mysqlnd 7.4.33)
- Browser: Chrome 126.0.0.0 (macOS)
- Theme: Spectra One 1.1.3
- MU-Plugins:
  * ZIPWP Client MU 1.0.1
  
- Plugins:
  * Query Monitor 3.16.3
  * Spectra 2.13.7
  * Spectra Pro 1.1.7
  * WooCommerce 9.0.2
  * WordPress Beta Tester 3.5.5
  * WP Reset 2.03

### Step-by-step reproduction instructions

1. Create a new page and add group block
2. Enable the Sticky option of Grid from Position drop Down
3. Add Pull Quote block in first column
4. Now duplicate the Column until the second row not created

Actual Result:
The Paragraph block moving behind he Grid Block

Expected Result:
The Paragraph block should be display under he Grid Block instead of its move behind

### Screenshots, screen recording, code snippet

https://bsf.d.pr/v/RlrE4w

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thank you for reporting and including a detailed video; this has been also reported at https://github.com/WordPress/gutenberg/issues/62613 and you can follow its progress there as well.
