### ISSUE TITLE
Localisation issues with combined strings

### ISSUE THREAD

**Issue by chantalcoolsma** [WordPress/gutenberg#6291]
Some strings are translated separately and combined with other strings using %s. For example this results in a string like "Voeg Kop toe" in Dutch. "Kop" (Heading) shouldn't start with a capital. So "Kop" should be "kop" in this case. I noticed those are separate strings to translate, but since they are single words, translators translate them with a capital. I don't know if those strings are used anywhere else. Otherwise we could translate them without capitalisation. I can imagine this can also apply to other languages than Dutch.

See for original issue https://github.com/WordPress/gutenberg/issues/6246

**Comment by Soean** [comment]
Example:
<img width="168" alt="38963125-b2eb939e-4370-11e8-9d28-e337e3bb1eda" src="https://user-images.githubusercontent.com/695201/39040994-689b8498-4488-11e8-8557-6bf6422c52a1.png">

**Comment by mcsf** [comment]
Thanks for the report, @chantalcoolsma. I agree this needs solving. May I ask, though, that you compile all the exact instances you can find where strings are wrongfully combined, and list them here? Thanks!

**Comment by designsimply** [comment]
I am closing this for now and we can re-open if you are able to add some additional examples as a starting point. Thank you for raising the issue!

**Comment by mcsf** [comment]
Related issue: https://github.com/WordPress/gutenberg/issues/9846
Its scope is technical but we also touched on compiling or informally analyzing our strings.
