### ISSUE TITLE
Blocks Keyboard Shortcuts - Conflict with Google Chrome

### ISSUE THREAD

**Issue by solaceten** [WordPress/gutenberg#62950]
### Description

I want to duplicate blocks quickly in Windows using the shortcut keys CNTRL + SHIFT + D

However, on Google Chrome (and Opera and Firefox) this shortcut key combination is used for selecting multiple open tabs and saving them.  Therefore, I cannot use the WP shortcut keys.

There does not appear to be anyway to easily a) modify Chrome or other browsers or b) modify the shortcut keys selection in WP.

So - either give us the option to modify these, or use cmobinations that are more obscure.

Thanks

https://wordpress.org/documentation/article/keyboard-shortcuts-block-editor/

https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop&sjid=1985471944888679876-AP#zippy=%2Ctab-window-shortcuts%2Cwebpage-shortcuts

Save all open tabs as bookmarks in a new folder | Ctrl + Shift + d

### Step-by-step reproduction instructions

Go to a WP site and page or post editor, using blocks in chrome
try to duplicate a block using the CNTRL + SHIFT + D

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I'm a Windows user too, and can't reproduce this issue.

The browser shortcut does indeed launch when the focus is outside of the editor content, but when a block is selected, the block editor shortcut (duplicate) takes precedence.

https://github.com/WordPress/gutenberg/assets/54422211/0b5d2194-57d1-4cc0-b3a5-f9c8ebd17b3c

**Comment by solaceten** [comment]
Thank you - you are right, when I click on a block and then use the cntrl shift D it does work.  Obviously was too quick to find a fault!!  Thanks for helping clear it up.
