### ISSUE TITLE
[Shadow] - Apply a text shadow to a title or paragraph

### ISSUE THREAD

**Issue by webexpr-dhenriet** [WordPress/gutenberg#62962]
Would it be possible to apply a text shadow to a title or paragraph ?

https://developer.mozilla.org/fr/docs/Web/CSS/text-shadow

**Comment by Mamaduka** [comment]
cc @madhusudhand

**Comment by annezazu** [comment]
Noting that this matches the following issues whose title I just updated to make it easier to find (🤠): https://github.com/WordPress/gutenberg/issues/47904

Closing out as a result and am going to note you opened this as a +1 there.
