### ISSUE TITLE
[Input] - Impossible to paste a value in all input fields with CTRL +V

### ISSUE THREAD

**Issue by webexpr-dhenriet** [WordPress/gutenberg#62967]
### Description

It's impossible to paste a value in all input fields with CTRL +V, it seems to trigger a TAB

### Step-by-step reproduction instructions

1. Go to admin right panel 
2. Copy a value CTRL + C
3. Try to paste this value in another field with CTRL + V

### Screenshots, screen recording, code snippet

[353c2e5b-36ab-4848-a1d2-e4aa6ffd3995.webm](https://github.com/WordPress/gutenberg/assets/62699215/26edecf8-8b5f-424e-b12e-f5559c581af0)

### Environment info

- WP 6.5.5
- Every themes
- Windows 10
- Chrome 126.0.0.0, Firefox 127.0, Edge 126.0.2592.68

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I was able to reproduce this issue in [Storybook](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-unitcontrol--docs), so it's probably a problem with the `UnitControl` component itself.


https://github.com/WordPress/gutenberg/assets/54422211/866b2385-422f-4bf7-ab8d-db7d9014a1a0

**Comment by webexpr-dhenriet** [comment]
@t-hamano thanks for the fix ;)
