### ISSUE TITLE
Post format displays all formats, even if it's limited in theme support

### ISSUE THREAD

**Issue by divpshr** [WordPress/gutenberg#6296]
## Issue Overview
The post format select option lists all post formats, even if it's limited in theme support. 

## Steps to Reproduce (for bugs)
1. Add a few post format support via **add_theme_support()** function in your theme's **function.php** file.
```php
function my_theme_setup(){

    add_theme_support( 'post-formats', array( 'link', 'image', 'gallery' ) );
    
}
add_action( 'after_setup_theme', 'my_theme_setup' );
```
2. Check classic editor, it displays only those few formats properly.
3. Check Gutenberg, it displays all possible formats.

I'm using Chrome Version 65.0.3325.181 (Official Build) (64-bit) on Win 10.
Gutenberg version: 2.7.0

## Expected Behavior
Gutenberg should list only those post formats which are defined in theme support.

## Current Behavior
Gutenberg lists all post formats.

## Screenshots / Video
![formats](https://user-images.githubusercontent.com/31571016/39018783-562b0092-4427-11e8-89a1-daa6cd5bf3ef.JPG)

**Comment by pento** [comment]
Thank you for the bug report, @divpshr!

The REST API doesn't expose the post formats the the current post type supports, but we can add this in and filter the list appropriately.

**Comment by danielbachhuber** [comment]
🔨
