### ISSUE TITLE
Open Tabpanel in Post Sidebar steals focus on load

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#62985]
### Description

When there is an open tabpanel on the post editor sidebar on page load, it steals focus. 

### Step-by-step reproduction instructions

- Have an open tabpanel, such as Tags in the Post Editor Sidebar
- Reload the page
- Press Tab
- Focus will be on the tabpanel header instead of at the beginning of the DOM

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/967608/31cbc25c-6a53-4f43-a6fc-c76c5642514e

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I can no longer reproduce the issue. I'm 99% sure it was resolved via #62974.

**Comment by Mamaduka** [comment]
I'll close the issue. @jeryj, feel free to re-open it if you can still reproduce it.
