### ISSUE TITLE
Emojis are not copied.

### ISSUE THREAD

**Issue by mitogh** [WordPress/gutenberg#63]
> 🙌 The new editor for WP has a prototype and it needs your help. Let's test it. 💯
https://ahmda.ws/WP_Gutenberg
Let's make #WordPress editing experience better. ...

The text above was copied and paste to the editor.

A capture from the text used.

![screen shot 2017-02-11 at 10 29 27 pm](https://cloud.githubusercontent.com/assets/3921289/22859666/be1d12b2-f0a9-11e6-8064-59a641d4b28c.png)

This was the result.

![screen shot 2017-02-11 at 10 30 17 pm](https://cloud.githubusercontent.com/assets/3921289/22859664/b3fb2616-f0a9-11e6-8481-d65e82202194.png)

**Comment by jasmussen** [comment]
Can't quite reproduce in the current version. But this issue is likely to change once the TinyMCE editor gets more involved in the prototypes. So closing for now :)
