### ISSUE TITLE
Cannot read properties of undefined (reading 'store')

### ISSUE THREAD

**Issue by mxvsh** [WordPress/gutenberg#63006]
### Description

Package `@wordpress/core-data` isn't working. It returns undefined when I try to import it in a TypeScript project.

Here's ny TSConfig

```json
{
	"compilerOptions": {
		"jsx": "react-jsx",
		"module": "ESNext",
		"target": "ES2016",
		"strict": true,
		"allowSyntheticDefaultImports": true,
		"moduleResolution": "node"
	}
}
```
### Step-by-step reproduction instructions

1. Install `@wordpress/core-data`
2. Add following code
```js
import { store } from '@wordpress/core-data';
console.log('store', store);
``` 
3. You should get an error.

###  Code:

<img width="441" alt="Screenshot 2024-07-01 at 14 00 23" src="https://github.com/WordPress/gutenberg/assets/31907722/9e101e87-47f7-4a94-8783-676fd31e230e">

### Result:

<img width="475" alt="Screenshot 2024-07-01 at 13 58 04" src="https://github.com/WordPress/gutenberg/assets/31907722/10da5d01-5255-4ce5-b3a4-b47cac41db3c">

### Environment info

- Wordpress Version: 6.5.5
- I am building a custom theme (Clone of 2024)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by miminari** [comment]
Thank you for reporting.
I tested this on WordPress 6.6.1, and I wasn't be able to reproduced, doing like below steps:

1. `npx @wordpress/create-block@latest error-test`
2. `cd error-test`
3. `npx @wp-now/wp-now start --reset`
4. Change the files to Typescript(`index.ts`, `edit.tsx`, `save.tsx`) , Add `tsconfig.json` and `npm i -D @types/wordpress__blocks @types/wordpress__block-editor`
5. Add the code on `edit.tsx`
6. `npm run start`

![SS_2024-08-14 10 55 22](https://github.com/user-attachments/assets/fc0a43b7-571a-47ad-b80d-20cda448e907)

It seems to work nice probably.

**Comment by miminari** [comment]
@mxvsh Hi, if you can share more details, please tell us about that.

**Comment by miminari** [comment]
@mxvsh I would like to close this issue, but if there is anything I have missed, please feel free to comment.
