### ISSUE TITLE
Layout alignment issue due to global padding on wide blocks (WP 6.6 RC1)

### ISSUE THREAD

**Issue by YanCol** [WordPress/gutenberg#63008]
### Description

Since the implementation of https://github.com/WordPress/gutenberg/pull/60715, “Padding is applied to all blocks with constrained layout that are full width or wide width.”

This change has introduced layout issues where the content no longer aligns as expected.

See the screenshots below for examples with the Twenty Twenty-Four theme and a WordPress.com theme.

### Step-by-step reproduction instructions

Steps to reproduce:

1. Visit https://2024.wordpress.net/index.php/entrepreneur-demo (which showcases the Blog Home template of the default theme)
2. Scroll to the third section "An array of resources" and fifth section "Watch, Read, Listen"
3. Observe that the content isn’t correctly aligned

### Screenshots, screen recording, code snippet

https://2024.wordpress.net/index.php/entrepreneur-demo/ 

| WordPress 6.5  | WordPress 6.6 RC1 |
| ------------- | ------------- |
|  ![2024-before](https://github.com/WordPress/gutenberg/assets/54663751/28f10842-be85-4c51-91bc-2617ca254f3d)   |   ![2024-after](https://github.com/WordPress/gutenberg/assets/54663751/1e85937f-2308-40ae-8cb7-4a0f718b72af) |

https://greensteaddemo.wordpress.com/ 

| WordPress 6.5  | WordPress 6.6 RC1 |
| ------------- | ------------- |
|   ![WordPresscom-before](https://github.com/WordPress/gutenberg/assets/54663751/e18272c4-98f6-419c-a665-4d1d1f55bcc4)  |   ![WordPresscom-after](https://github.com/WordPress/gutenberg/assets/54663751/f00b21f9-0473-48e6-923f-dc5034898195) |

### Environment info

WordPress 6.6 RC1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
@tellthemachines and @richtabor just an FYI about this one. Does this sound like a bug in the recently shipped rules changes, or do themes need to update how they construct their patterns? In this case since it might affect content out in the wild, I wasn't sure the scope of the issue.

**Comment by tellthemachines** [comment]
I believe it was a [deliberate decision](https://github.com/WordPress/gutenberg/issues/62597#issuecomment-2180022403) but might be good to confirm with @richtabor because it's hard to anticipate the exact effects of these rules, so this could have been an unintended consequence.

**Comment by annezazu** [comment]
Adding to 6.6 board to be safe either way.

**Comment by carolinan** [comment]
What exactly do theme developers need to change in order to make their layout work in multiple WordPress versions?
The minimum required WordPress versions of the bundled themes can't be adjusted.

**Comment by richtabor** [comment]
> What exactly do theme developers need to change in order to make their layout work in multiple WordPress versions?
> The minimum required WordPress versions of the bundled themes can't be adjusted.

Nothing. 🙂 https://github.com/WordPress/gutenberg/pull/63207
