### ISSUE TITLE
Docs: Create a section about Block Bindings in the Block Editor Handbook

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#63026]
A section about **Block Bindings** is missing in the [Block Editor Handbook](https://developer.wordpress.org/block-editor/) although there's info explaining the possibilities of this feature distributed across different resources:
- [New Feature: The Block Bindings API](https://make.wordpress.org/core/2024/03/06/new-feature-the-block-bindings-api/) - DevNote
- [Introducing Block Bindings, part 1: connecting custom fields](https://developer.wordpress.org/news/2024/02/20/introducing-block-bindings-part-1-connecting-custom-fields/) - Developer Blog post
- [Introducing Block Bindings, part 2: Working with custom binding sources](https://developer.wordpress.org/news/2024/03/06/introducing-block-bindings-part-2-working-with-custom-binding-sources/) - Developer Blog post
- [Editing custom fields from connected blocks](https://make.wordpress.org/core/2024/06/28/editing-custom-fields-from-connected-blocks/) - Make WordPress Core post (6.6 updates)

A new section titled **Block Bindings** with the most relevant info from the resources above could be created under [Reference Guides > Block API Reference](https://developer.wordpress.org/block-editor/reference-guides/block-api/)

cc: @justintadlock @SantosGuillamot

**Comment by gziolo** [comment]
WordPress 6.7 will ship the client-side counterpart of the API so the related dev note is still pending:

- https://github.com/WordPress/gutenberg/pull/65713

**Comment by SantosGuillamot** [comment]
FYI: We are working on the dev note, which will potentially be used as the basis for the docs.

**Comment by gziolo** [comment]
@cbravobernal, is this one finished? I can see a new reference page at https://developer.wordpress.org/block-editor/reference-guides/block-api/block-bindings/.

**Comment by cbravobernal** [comment]
Yes, we can close it.
