### ISSUE TITLE
If the theme folder contains the word `parts`, block template parts provided by the theme can't be customized in the Site Editor

### ISSUE THREAD

**Issue by Aljullu** [WordPress/gutenberg#63030]
### Description

If a theme is in a folder with a name containing the string `parts`, modifying a template part provided by the theme using the Site Editor UI causes a 404 error.

### Step-by-step reproduction instructions

1. Enable Twenty Twenty Four or any other block theme.
2. Change the `twentytwentyfour` folder name in `/wp-content/themes/` to something that contains the word `parts`. Some ideas: `theme-with-template-parts`, `departs-theme` or whatever comes to your mind.
3. Go to Appearance > Template parts.
4. Notice template part names are prepended with `parts`:

![imatge](https://github.com/WordPress/gutenberg/assets/3616980/3564bdcb-21db-46af-82fe-40cd03ee6af5)

5. Open one of the template parts and notice the URL is in this shape: `/wp-admin/site-editor.php?postId=departs%2F%2Fparts%2Fheader&postType=wp_template_part&canvas=edit`. Notice the extra `parts%2F` in the URL which shouldn't be there.
6. Make some edits to the template.
7. Try saving, a 404 request will be made and an error will appear.

### Screenshots, screen recording, code snippet

![Saving failed when modifying the Simple header template part](https://github.com/WordPress/gutenberg/assets/3616980/f2ba68b1-5d1b-4b71-8fe3-0c59d32934d6)

### Environment info

Tested on WordPress 6.5.5 and WordPress 6.6-RC.1.

Kudos to @tjcafferkey for helping me debug this issue.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Could be similar to my old report #42679.

**Comment by Aljullu** [comment]
Oh yes, it looks the same. I will close this one in favor of yours!
