### ISSUE TITLE
Section styles: improve (or remove) preview 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#63035]
Currently, the previews for block style variations don't offer much value when applied to styling sections of blocks with the new feature in 6.6. If anything, the preview looks broken and doesn't match all of the changes one can expect to see:

![Screenshot 2024-07-01 at 11 34 44 AM](https://github.com/WordPress/gutenberg/assets/26996883/aa5febaf-892d-4497-9456-17894d5758a1)

Here's a video:

https://github.com/WordPress/gutenberg/assets/26996883/53f6acc1-7f6a-408f-ae71-dc97a81d3186

As a result, I think we should either remove these previews for Groups & Columns for now or consider a way to improve the preview offered cc @aaronrobertshaw

**Comment by bgardner** [comment]
+1 for improving (or removing) previews for section styles.

**Comment by aaronrobertshaw** [comment]
Just flagging that there were a couple of earlier explorations into updating the UI for Block Styles:
- https://github.com/WordPress/gutenberg/pull/57780
- https://github.com/WordPress/gutenberg/pull/57331

While these were focused on the control itself, e.g. dropdown vs small cards etc., it did come up that the [preview isn't really required](https://github.com/WordPress/gutenberg/pull/57780#issuecomment-1956984191) as it was so easy to see it in action or switch back to the default.

I can put together a quick PR to remove the preview and see what people think.

**Comment by bgardner** [comment]
> I can put together a quick PR to remove the preview and see what people think.

TBH, I think this is better (and likely easier to ship with RC2?) to remove than to style a preview.

**Comment by aaronrobertshaw** [comment]
> and likely easier to ship with RC2?

I think this might be seen more as an enhancement rather than a bug fix, so I don't think it will make it into any of the 6.6 RCs.

**Comment by bgardner** [comment]
Heh, I could make the argument that it _is_ a bug, but that would only be wishful thinking.

In short, I understand and agree with what you said.

**Comment by aaronrobertshaw** [comment]
A draft PR is up for removing the block style previews from the inspector panel only: https://github.com/WordPress/gutenberg/pull/63039.

I am having some problems with my local native env at the moment so I've left the PR in a draft state until I can sort that out and see whether it still makes sense to remove the previews there too.

**Comment by aaronrobertshaw** [comment]
The block styles still use an inline preview for the native UI. Given the next iteration of section styles/block style variations will likely involve a major update to this panel, I wonder if it makes sense to hold off on updating the native UI. 

I've [suggested](https://github.com/WordPress/gutenberg/pull/63039#issuecomment-2202175934) over on #63039 that this could be a separate follow-up but happy to hear other's thoughts on this one.

**Comment by annezazu** [comment]
Thanks for the quick work here.

**Comment by aaronrobertshaw** [comment]
The removal of previews appears to be overkill. An alternate approach, simply improving the Group block's example, is available in https://github.com/WordPress/gutenberg/pull/63114.
