### ISSUE TITLE
[WP 6.6-RC1] Featured Image Media Modal only shows the latest uploaded image

### ISSUE THREAD

**Issue by jartes** [WordPress/gutenberg#63058]
### Description

When setting a featured image using the post/page settings, only the last uploaded image is displayed in the media library modal: 

![Markup on 2024-07-02 at 15:42:06](https://github.com/WordPress/gutenberg/assets/1046943/bb3230a1-b527-4ab7-8098-28e88fe36fa3)

This happens on **WordPress 6.6-RC1** and with and without the Gutenberg plugin active.

The following JavaScript error is being displayed on the browser console: 

```
media-models.min.js?ver=6.6-RC1:2 
Uncaught TypeError: t.get is not a function
    at n.comparator (media-models.min.js?ver=6.6-RC1:2:5566)
    at e.comparator (media-views.min.js?ver=6.6-RC1:2:7240)
    at Array.sort (<anonymous>)
    at n.sort (backbone.min.js?ver=1.5.0:2:11690)
    at n.set (backbone.min.js?ver=1.5.0:2:10286)
    at n.add (backbone.min.js?ver=1.5.0:2:8973)
    at n.validate (media-models.min.js?ver=6.6-RC1:2:2960)
    at n._validateHandler (media-models.min.js?ver=6.6-RC1:2:3953)
    at p (backbone.min.js?ver=1.5.0:2:3818)
    at f (backbone.min.js?ver=1.5.0:2:3497)

```

Props to @mrfoxtalbot for finding out about this issue.

### Step-by-step reproduction instructions

1. Use a site with WordPress 6.6-RC1, with or without the Gutenberg plugin active.
2. Make sure you have a few images on the site media library
3. Create a new post/page. 
4. Click on the `Set features image` button. 
5. Check that only the last uploaded image is being displayed.

### Screenshots, screen recording, code snippet

Screen recording with the steps to reproduce this error:

https://github.com/WordPress/gutenberg/assets/1046943/fa7a2f03-ff2d-4690-8476-3908c21e9583

### Environment info

**WordPress Version:** 6.6-RC1
**Theme:** Twenty Twenty-FourVersion: 1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by priethor** [comment]
I can reproduce this issue with the environment above, but this issue does NOT reproduce with WordPress 6.5.5 and the current Gutenberg plugin trunk (18.7-rc.1); the error comes directly from WP 6.6. I recommend moving it to a Trac ticket. cc @ironprogrammer

**Comment by t-hamano** [comment]
I was not able to reproduce this issue in WP6.6 RC1 🤔


https://github.com/WordPress/gutenberg/assets/54422211/ccae320e-7b56-4270-a76a-2285028250a3

**Comment by youknowriad** [comment]
I think @Mamaduka worked on something related to the media modal for featured image recently right? Maybe you'd know more about this issue?

**Comment by Mamaduka** [comment]
I'm having trouble reproducing the issue, but as @priethor mentioned, it's probably coming from the Media Library code maintained on Trac.

Enabling the [`SCRIPT_DEBUG`](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/#script_debug) should load unminifed JS files and give us a better error report.

Edit: I am happy to help debug this further once we have a consistent way of reproducing the bug.

**Comment by priethor** [comment]
The issue can also be reproduced [with Playground](https://playground.wordpress.net/?php=8.0&wp=beta&storage=none). 

@jartes and I originally reproduced it with the Beta Tester plugin; are you using a bundled 6.6-rc1 or running the WP 6.6 branch, @Mamaduka @t-hamano?

**Comment by Mamaduka** [comment]
@priethor, I've tried the following combos locally.

* WP 6.5 + Gutenberg trunk ✅
* WP beta tester plugin upgrade to 6.6 RC, with and without Gutenberg trunk ✅

**Comment by t-hamano** [comment]
I believe I was using WordPress 6.6 **RC1** when I tested this issue, but I tested it again and I still can’t reproduce the problem.

- WP 6.5 + Gutenberg trunk ✅
- WP beta tester plugin upgrade to 6.6 **RC2**, with and without Gutenberg trunk ✅

**Comment by carolinan** [comment]
I am not able to reproduce the error on the provided playground link, nor on WordPress trunk (For this test I did not use the beta tester plugin), and while searching I found this trac ticket, so I believe it is fixed:
https://core.trac.wordpress.org/ticket/61519

I should have searched before testing 😅

**Comment by colorful-tones** [comment]
I tested with WP 6.6 RC-2 (Beta Tester plugin on Local) with Gutenberg 18.7.1 activated _and_ once deactivated and I was not able to reproduce the issue. 

https://core.trac.wordpress.org/ticket/61519 fixed the issue.
