### ISSUE TITLE
[wp-env] docker-compose.yml: "version" is obsolete

### ISSUE THREAD

**Issue by alessandrotesoro** [WordPress/gutenberg#63073]
### Description

I'm using the wp-env package to run e2e tests via playwright. Recently started getting the following error:

```
time="2024-06-26T13:54:38+02:00" level=warning msg="/.wp-env/b154ed05c3747ba6b44423275a728fe4/docker-compose.yml: `version` is obsolete"
```

I’ve noticed the following [trac ticket](https://core.trac.wordpress.org/ticket/61101) and [PR](https://github.com/WordPress/wordpress-develop/pull/6492/commits/7ab71c7e0c4bd76042f5336ca4cf42ec317ef7c4) however, I’m not sure how to pull in the latest changes?

- All my js dependencies are up to date. 
- All docker volumes, images and containers have been wiped but the error persists. 
- Manually editing the yml file doesn’t solve the issue either.
- Manually deleting all the folders under `~/.wp-env/` doesn't work either because the folder `b154ed05c3747ba6b44423275a728fe4` is recreated after running `wp-env start`

Any ideas on how to solve the issue? I've posted this same question on Slack too but got no answer.

Thank you.

### Step-by-step reproduction instructions

1. Install the `wp-env` package.
2. Run `wp-env start`.
3. Error appears.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ockham** [comment]
I think that this might be coming from [`wp-env`'s own docker-compose config](https://github.com/WordPress/gutenberg/blob/4d8f515c4da1ce128f23cc7b09dc61396ad951a5/packages/env/lib/build-docker-compose-config.js#L178) (which is built dynamically by a script), whereas the Trac ticket and PR you found are about `wordpress-develop`'s docker-compose setup, which is separate (and static, i.e. it's just a static `docker-compose.yml` file there).

Can you try removing the line I linked to and see if that fixes the issue? (FWIW, I haven't been able to reproduce it locally; maybe I need to update my docker-compose version.)

**Comment by ockham** [comment]
> (FWIW, I haven't been able to reproduce it locally; maybe I need to update my docker-compose version.)

Ah, I now see it happen in CI: https://github.com/WordPress/gutenberg/actions/runs/9776598064/job/26989677669?pr=62092

I've filed a PR: https://github.com/WordPress/gutenberg/pull/63099

**Comment by alessandrotesoro** [comment]
@ockham thanks for your help 👍
