### ISSUE TITLE
Improve BlockControls documentation

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6309]
Today, together my team, we had some difficulties to fully understand how `BlockControls` work, had to look at the code and tests to get it. Especially related to how to add set of controls with a separator, turns out some documentation is in the `blocks/README.md`

```
To create divisions between sets of controls within the same `BlockControls`
element, passing `controls` instead as a nested array (array of arrays of
objects). A divider will be shown between each set of controls.
```

Worth considering some documentation within `BlockControls` and a specific `README` in 
`/blocks/block-controls/index.js`

**Comment by gziolo** [comment]
Closed with #6308.
