### ISSUE TITLE
WP 6.6 RC2: The data store doesn't trigger the resolver

### ISSUE THREAD

**Issue by leoloso** [WordPress/gutenberg#63135]
### Description

@talldan @swissspidy Continuation from #63009, here I describe the new problem.

In my plugin, I have a CPT that loads custom blocks, powered by a data store that fetches data from an API.

After upgrading to RC2, the data store doesn't trigger the resolver anymore.

Due to the previous issue, I've just re-done the data stores in my plugin as to remove the generators.

I've based it on the source code from Gutenberg's `block-directory` package:

- https://github.com/WordPress/gutenberg/blob/1b6b4b8d8439b7cc0b0d90334a3b7cccaa665b45/packages/block-directory/src/store/index.js

To do this, I copied the `store` folder from there, and adapted resolver `getDownloadableBlocks` for my own use, into `getSchemaConfigurations`. It's a copy/paste/replace (and deletions of unneeded code), hence the code is the same (I didn't rewrite anything, the logic is the same).

The resulting store is this one:

- https://github.com/GatoGraphQL/GatoGraphQL/blob/66bc58fb0a16e96df92b82eb3e8b0df7c221b723/layers/GatoGraphQLForWP/plugins/gatographql/blocks/schema-configuration/src/store/index.js

The only difference I appreciate is that, while in the Gutenberg repo `getDownloadableBlocks` is invoked within `useState`, in my plugin I invoke `getSchemaConfigurations` within `withState`. (Is this relevant?)

**This code works well in WP 6.5**, as can be seen in the .gif below.

When loading the CPT, block "Schema configuration" will load data from the server via an API. We can see the lines printed in the console, where `getSchemaConfigurations` is invoked, and where its resolver fetches data:

![new-custom-endpoint-wp-6 5](https://github.com/WordPress/gutenberg/assets/1981996/165ee8ed-ff1e-461e-8978-135e02472202)

For debugging, I've added the `console.log` lines like this:

[In `schema-configuration.js`](https://github.com/GatoGraphQL/GatoGraphQL/blob/fdb02c62760cdac0c0c7ef3bafb2906f4ed459cf/layers/GatoGraphQLForWP/plugins/gatographql/blocks/schema-configuration/src/schema-configuration.js#L159):

```js
export default compose( [
	// ...
	withSelect( ( select ) => {
		const {
			getSchemaConfigurations,
			isRequestingSchemaConfigurations,
			getRetrievingSchemaConfigurationsErrorMessage,
		} = select ( 'gatographql/schema-configuration' );

		console.log('##1. calling getSchemaConfigurations()')
		console.log('##1. ', getSchemaConfigurations())

		return {
			schemaConfigurations: getSchemaConfigurations(),
			isRequestingItems: isRequestingSchemaConfigurations(),
			errorMessage: getRetrievingSchemaConfigurationsErrorMessage(),
		};
	} ),
	// ...
] )( SchemaConfigurationSelectCard);
```

[In `resolvers.js`](https://github.com/GatoGraphQL/GatoGraphQL/blob/ac627b38a4f07aa08b63c0cfaa05a6b7cae692c0/layers/GatoGraphQLForWP/plugins/gatographql/blocks/schema-configuration/src/store/resolvers.js#L9):

```js
export const getSchemaConfigurations =
	( variables = parameters.defaultVariables ) =>
	async ( { dispatch } ) => {
		try {
			console.log('--2. executing getSchemaConfigurations() (in resolvers.js)')
			dispatch( fetchSchemaConfigurations( variables ) );
			const response = await fetchGraphQLQuery(
				GATOGRAPHQL_PLUGIN_OWN_USE_ADMIN_ENDPOINT,
				parameters.query,
				variables
			);
			
			// ...

			const results = response.data?.schemaConfigurations || [];
			console.log('--2.', results)
			dispatch( receiveSchemaConfigurations( variables, results ) );
		} catch {}
	};
```

**After upgrading to WP 6.6 RC2, the resolver is not invoked anymore**, as can be seen in the .gif below.

Notice how the `##1` lines are printed, but the `--2` ones are not, and as such, the select component isn't added those items from the API:

![new-custom-endpoint-wp-6 6](https://github.com/WordPress/gutenberg/assets/1981996/d578dd5b-ab5a-47f4-aff2-f969a520c887)

For some more info: I haven't updated the versions of the `@wordpress` packages, it's still using these old ones (may this be relevant to the issue?):

```json
{
    "devDependencies": {
        "@wordpress/components": "^10.0.0",
        "@wordpress/compose": "^3.19.0",
        "@wordpress/data": "^4.22.0",
        "@wordpress/edit-post": "^3.21.0",
        "@wordpress/scripts": "^12.1.0",
        "prettier": "npm:wp-prettier@2.0.5",
        "raw-loader": "^4.0.2",
        "react-select": "^3.0.8"
    }
}
```

### Step-by-step reproduction instructions

1. Install WP 6.6 RC2
2. Have the Gato GraphQL plugin installed, with this version: https://github.com/GatoGraphQL/GatoGraphQL/actions/runs/9796133324/artifacts/1668447468
3. Go to "Custom Endpoints" => Add New (eg: site.com/wp-admin/post-new.php?post_type=graphql-endpoint)
4. The select input in the first block ("Schema configuration") is not filled with items from the API

### Environment info

- WP 6.6 RC2
- [Gato GraphQL latest dev version](https://github.com/GatoGraphQL/GatoGraphQL/actions/runs/9796133324/artifacts/1668447468)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by leoloso** [comment]
After updating dependency `@wordpress/scripts` from `v12.1` to `v27.9`, the problem disappeared! 🎉

Might it be due to upgrading webpack from `v4` to `v5`?

**Comment by leoloso** [comment]
As a side effect, [my plugin now requires at least WordPress 6.0](https://github.com/GatoGraphQL/GatoGraphQL/pull/2719) (it was 5.4). Small price to pay.

**Comment by Mamaduka** [comment]
@leoloso, thanks for keeping us updated.

It makes sense to bump the minimum required WP versions to solve the issue. The support for "thunks" shipped around that version in the core.

Here's the announcement post - https://make.wordpress.org/core/2021/10/29/thunks-in-gutenberg/.
