### ISSUE TITLE
Data Views: filtering by numerous authors causes frameshift 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#63149]
I am testing Data Views with numerous authors and pages and noticed that if you filter by a certain number, a frameshift occurs:

https://github.com/WordPress/gutenberg/assets/26996883/796b7e2e-3a43-41f0-82ad-e0c207aeee60

To replicate:

1.  Add a bunch of users to your site.
2. Head to the Site Editor and open up Pages.
3. Use the filter options to filter by all users.
4. Notice frameshift.

This is using WP 6.5.5 & GB 18.7.1 & Chrome on MacOS.

**Comment by jameskoster** [comment]
Does this occur on trunk? I think it _may_ have been fixed by https://github.com/WordPress/gutenberg/pull/63079.

**Comment by annezazu** [comment]
Finally getting around to testing this again with 6.6 out the door. Looks like it was fixed! Closing out 🥳 
https://github.com/user-attachments/assets/3bdf172e-c1a4-42a8-9c52-fa28eb13dc65
