### ISSUE TITLE
Data views: while loading, a "no results" message flashed

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#63153]
A “no results” message flashed during a loading state:

https://github.com/WordPress/gutenberg/assets/26996883/be793cbe-5d8e-4099-827a-e59d53e4e028

This is using WP 6.5.5 & GB 18.7.1 & Chrome on MacOS. You can replicate this [using this link](https://href.li/?https://playground.wordpress.net/#%7B%20%22landingPage%22:%20%22/wp-admin/site-editor.php%22,%20%22preferredVersions%22:%20%7B%20%22php%22:%20%227.4%22,%20%22wp%22:%20%226.5.5%22%20%7D,%20%22phpExtensionBundles%22:%20%5B%20%22kitchen-sink%22%20%5D,%20%22features%22:%20%7B%20%22networking%22:%20true%20%7D,%20%22steps%22:%20%5B%20%7B%20%22step%22:%20%22login%22,%20%22username%22:%20%22admin%22,%20%22password%22:%20%22password%22%20%7D,%20%7B%20%22step%22:%20%22importWordPressFiles%22,%20%22wordPressFilesZip%22:%20%7B%20%22resource%22:%20%22url%22,%20%22url%22:%20%22https://block-museum.com/wp-content/uploads/2024/07/wordpress-playground-200-pages.zip%22%20%7D%20%7D,%20%7B%20%22step%22:%20%22installPlugin%22,%20%22pluginZipFile%22:%20%7B%20%22resource%22:%20%22wordpress.org/plugins%22,%20%22slug%22:%20%22gutenberg%22%20%7D,%20%22options%22:%20%7B%20%22activate%22:%20true%20%7D%20%7D%20%5D%20%7D) (might make you login) which will spin up a playground instance of the site I found this issue on.

**Comment by ntsekouras** [comment]
I couldn't reproduce this.. Is this still happening for you @annezazu ?

**Comment by annezazu** [comment]
Just tried to replicate today and couldn't with the latest GB plugin:

https://github.com/user-attachments/assets/0f9f2f23-ded2-4c20-846f-d620d50802cb

Closing out!
