### ISSUE TITLE
Data Views: when trying to bulk edit on a site with many pages, the bulk edit option counts up

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#63150]
When selecting the bulk edit option, the option to select all counts up in situations where you have 20+ pages:

https://github.com/WordPress/gutenberg/assets/26996883/6507c0b9-45ef-44f1-904e-efcfca3ef90c

This gets worse the more pages you have visible and have on your site. This is using WP 6.5.5 & GB 18.7.1 & Chrome on MacOS. You can replicate this [using this link](https://href.li/?https://playground.wordpress.net/#%7B%20%22landingPage%22:%20%22/wp-admin/site-editor.php%22,%20%22preferredVersions%22:%20%7B%20%22php%22:%20%227.4%22,%20%22wp%22:%20%226.5.5%22%20%7D,%20%22phpExtensionBundles%22:%20%5B%20%22kitchen-sink%22%20%5D,%20%22features%22:%20%7B%20%22networking%22:%20true%20%7D,%20%22steps%22:%20%5B%20%7B%20%22step%22:%20%22login%22,%20%22username%22:%20%22admin%22,%20%22password%22:%20%22password%22%20%7D,%20%7B%20%22step%22:%20%22importWordPressFiles%22,%20%22wordPressFilesZip%22:%20%7B%20%22resource%22:%20%22url%22,%20%22url%22:%20%22https://block-museum.com/wp-content/uploads/2024/07/wordpress-playground-200-pages.zip%22%20%7D%20%7D,%20%7B%20%22step%22:%20%22installPlugin%22,%20%22pluginZipFile%22:%20%7B%20%22resource%22:%20%22wordpress.org/plugins%22,%20%22slug%22:%20%22gutenberg%22%20%7D,%20%22options%22:%20%7B%20%22activate%22:%20true%20%7D%20%7D%20%5D%20%7D) (might make you login) which will spin up a playground instance of the site I found this issue on.

**Comment by jorgefilipecosta** [comment]
Good catch @annezazu, I think this happens because the permissions of the user need to be checked to make sure the user can execute some action, while the permission checks are in place the count goes up.

There are some mitigations:
- Not show the count while permission checks are in progress.
- Do not show the bulk edit UI at all while the checks are in progress.

@WordPress/gutenberg-design any thoughts on the best path forward?

**Comment by jasmussen** [comment]
> Not show the count while permission checks are in progress.
> Do not show the bulk edit UI at all while the checks are in progress.

None of those options necessarily seem great. 

The thing is, select all is actually _select all on the current page_, not _select all across every page_. Correct?

Gmail has this thing where first you click this checkbox to select across all:
![Screenshot 2024-07-09 at 11 35 28](https://github.com/WordPress/gutenberg/assets/1204802/d7ecea28-8c52-4e97-b4ec-c9963d3dd68a)

That checkbox serves also as a dropdown, and is essentially the bulk-edit tool for gmail. By being a checkbox at the top of the column of checkboxes, it also implies you are selecting _all on this page_.

Once you do, and you have more pages, you'll see a message such as this:

![Screenshot 2024-07-09 at 11 35 21](https://github.com/WordPress/gutenberg/assets/1204802/24a99cb9-af16-40f1-a397-ca663d071a1e)

Outside of an argument to consider the same checkbox+dropdown interface for the bulk tool, one thing we could do would be to lean into the idea that "select all" is for _the current page_. I don't know that we need to change the wording, but we certainly don't need to check permissions do do expensive counts for anything other than the current page. I.e. the count can only ever be between the bounds of 1 and [items per page].

Secondly when selecting all, we could show either a snackbar, a notice, or that floating bulk toolbar at the bottom, to show a similar action as that of Gmail: _Select all items_. For this interface, we could consider showing all items in the taxonomy.

What do you think?

**Comment by jameskoster** [comment]
I suppose this would be indirectly resolved by updating the bulk edit interface as suggested in https://github.com/WordPress/gutenberg/issues/63193 (which needs design feedback).

The Snackbar select-all affordance is neat!

**Comment by jameskoster** [comment]
This UI has changed and the issue no longer seems to be present.
