### ISSUE TITLE
Data Views: Changing items per page to 100 results in poor loading experience

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#63151]
If you set Items per page to 100 then scroll down, you’ll be met with a blank screen as items seem to load. You’ll also see the bulk edit counting up here again to 100, matching the following issue https://github.com/WordPress/gutenberg/issues/63150

https://github.com/WordPress/gutenberg/assets/26996883/17575cc3-bacd-47b7-9a4c-6d4a66f0304c

This is using WP 6.5.5 & GB 18.7.1 & Chrome on MacOS. You can replicate this [using this link](https://href.li/?https://playground.wordpress.net/#%7B%20%22landingPage%22:%20%22/wp-admin/site-editor.php%22,%20%22preferredVersions%22:%20%7B%20%22php%22:%20%227.4%22,%20%22wp%22:%20%226.5.5%22%20%7D,%20%22phpExtensionBundles%22:%20%5B%20%22kitchen-sink%22%20%5D,%20%22features%22:%20%7B%20%22networking%22:%20true%20%7D,%20%22steps%22:%20%5B%20%7B%20%22step%22:%20%22login%22,%20%22username%22:%20%22admin%22,%20%22password%22:%20%22password%22%20%7D,%20%7B%20%22step%22:%20%22importWordPressFiles%22,%20%22wordPressFilesZip%22:%20%7B%20%22resource%22:%20%22url%22,%20%22url%22:%20%22https://block-museum.com/wp-content/uploads/2024/07/wordpress-playground-200-pages.zip%22%20%7D%20%7D,%20%7B%20%22step%22:%20%22installPlugin%22,%20%22pluginZipFile%22:%20%7B%20%22resource%22:%20%22wordpress.org/plugins%22,%20%22slug%22:%20%22gutenberg%22%20%7D,%20%22options%22:%20%7B%20%22activate%22:%20true%20%7D%20%7D%20%5D%20%7D) (might make you login) which will spin up a playground instance of the site I found this issue on.

**Comment by Mamaduka** [comment]
The performance should be improved with #64504, but it probably won't fully resolve the issue.

**Comment by annezazu** [comment]
I can no longer replicate this when I test with Gutenberg 19.7! Closing out as a result.
