### ISSUE TITLE
Use more generic example in Page Attributes popup inline documentation.

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#63158]
## What problem does this address?

The current example string for the inline documentation when selecting a parent page is `Child pages inherit characteristics from their parent, such as URL structure. For instance, if 'Web Design' is a child of 'Services,' its URL would be mysite.com/services/web-design.` (the domain will change in #63154 but that's not important).

While this is a good demonstration in the context of the kind of sites WordPress contributors are likely to work on, it's industry specific rather than generic.

## What is your proposed solution?

Replace the example pages with something more generic that represents a common example for all sites:

* `'Team' is a child page of 'About Us'`
* `'Location' is a child page of 'Contact'`
* Other suggestions as they come in...

**Comment by kristastevens** [comment]
Hi @peterwilsoncc, thanks for the ping! here are a few suggestions. One note, that any examples will need to use double quotation marks to match A8C's style, which defaults to American usage. 

* "FAQ" is a child page of "About Us"
* "Subscribe" is a child page of "Blog"
* "Contact Support" is a child page of "Help" 
* "Pricing" is a child page of "Services"
* "Testimonials" is a child page of "Products"

**Comment by peterwilsoncc** [comment]
It appears the WP inline documentation standards match those of A8C, so we can include that change on this ticket.

Which is the correct placement of the comma in American English: `is a child page of "Services,"` or `is a child page of "Services",`?

**Comment by peterwilsoncc** [comment]
@kristastevens Initially on the pull request #63154, I used the actual WordPress installs home page for the inline documentation to generate the URL but eventually decided to go with example.org to allow for sites with a long home URL.

Do you think it's best to use the actual result or continue using the example domain.

Appearance with a short home URL:

![with-short-url](https://github.com/user-attachments/assets/d97252d1-c384-4595-b3d0-7422c2a34b64)

Appearance with a long home URL:

![long-url_](https://github.com/user-attachments/assets/5cea26fe-5dde-4a0d-a74b-ef0876963e75)

I lean towards accuracy being better but would like to know your opinion?

**Comment by kristastevens** [comment]
Hi @peterwilsoncc, thanks for the ping! I agree that being more specific when possible is better. 

One thing I notice in reading this over, is the use of single quotation marks. All single quotation marks s/b double quotation marks:

'Web design' is a child of 'Services,' should be "Web Design" is a child of "Services,"

**Comment by peterwilsoncc** [comment]
@kristastevens Are you able to link your GitHub account to your WordPress.org account so we can assign props in the linked PR. You can do so by editing your profile at https://profiles.wordpress.org/me/ 

> One thing I notice in reading this over, is the use of single quotation marks. All single quotation marks s/b double quotation marks:

Yep, that's included in the pull request for this ticket.

**Comment by kristastevens** [comment]
@peterwilsoncc account linked! (TYSM!)
