### ISSUE TITLE
Save As button not displayed with custom post_status

### ISSUE THREAD

**Issue by agapetry** [WordPress/gutenberg#63161]
### Description

The Save As button (button.editor-post-save-draft) is not displayed if the post is saved with a custom non-published status.  As a result, if third party code uses register_post_status() to define a custom post status, posts of that status cannot be updated without publishing. 

This issue does not exist in Gutenberg 17.7 and earlier.

### Step-by-step reproduction instructions

1. In PHP, register a custom post status and insert a sample post with that status: 
```php
function sample_post_for_save_as_issue() {
  register_post_status('testing', ['label' => 'Testing', 'internal' => false, 'protected' => true]); 
  
  if (!is_user_logged_in()) {return;}
    
  $query = new WP_Query(['name' => 'status_test_345234']);
  
  if (!$query->have_posts()) {
    wp_insert_post(['post_name' => 'status_test_345234', 'post_title' => 'Status Test', 'post_status' => 'testing']);
  }
}

add_action('init', 'sample_post_for_save_as_issue');
```

2. Open the sample post "Status Test" in Gutenberg.

3. Key in some post content.

### Expected behavior: 

1. Gutenberg displays the Save Draft button. 

2. Clicking the Save Draft button causes post content changes to be saved, while retaining the custom post status.

3. The Posts screen still lists "Sample Post" and the status count caption "Testing" is still visible next to All / Mine / Published / Drafts.

Note that this is not expected to be a finished use case, just a functional Save As button which third party code can build on.  It works as such with Gutenberg 17.7 and WordPress 6.5.

### Screenshots, screen recording, code snippet

**Sample Post saved with custom post status (indicated by status count caption though not in table row):**

![image](https://github.com/WordPress/gutenberg/assets/43488774/230d1770-e205-40b2-bd59-21977d712c06)

.
**Save Draft button displayed in Gutenberg 17.7:**

![image](https://github.com/WordPress/gutenberg/assets/43488774/3be7c6f9-fe36-4dcb-a2c9-cd502c19bcf8)

.
**Save Draft button missing in Gutenberg 18.7:**

![image](https://github.com/WordPress/gutenberg/assets/43488774/d4a00b45-dd52-41eb-8c40-2825264ba2e3)

### Environment info

- WordPress 6.6 rc2
- Gutenberg 18.7.1
- Twenty Twenty-Three theme
- Firefox 127.0.2
- Windows 10 on desktop

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Somewhat related #3144.

**Comment by jorgefilipecosta** [comment]
I confirmed the save button was available on the previous version of WordPress but now it is not available.

**Comment by agapetry** [comment]
@talldan @Mamaduka @jorgefilipecosta @ntsekouras Thank you!
