### ISSUE TITLE
Zoom Out: Can't exit the mode after switching between the pattern categories

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#63168]
After switching between the pattern categories, I noticed that closing the inspector doesn't exist in the "Zoom out" mode in the Site Editor. It works if I only select one category and then close the inspector.

The behavior is slightly different in the post editor; the mode is toggled on every category change.

This is probably a bug with the [`useZoomOut` hook](https://github.com/WordPress/gutenberg/blob/eaa7ed7cf1798a3fb79185e1aff2c86de5e5ba89/packages/block-editor/src/hooks/use-zoom-out.js#L17) and how it's run from pattern category panels.

cc @jeryj, @scruffian

## Testing Instructions
1. Enabled "zoomed out view when selecting a pattern category in the main inserter"  from Gutenberg > Experiments.
2. Go to Site Editor > any template.
3. Open the Inserter
4. Switch between Pattern categories.

## Screencasts

**Site Editor**

https://github.com/WordPress/gutenberg/assets/240569/5320de51-b213-4915-b09b-f69a8f2ee185

**Post Editor**

https://github.com/WordPress/gutenberg/assets/240569/69422f37-1539-4942-a414-bea638cf6598

**Comment by jeryj** [comment]
I believe this is fixed by https://github.com/WordPress/gutenberg/pull/63315 as well. I'll close it, but reopen it if I wasn't testing it right!
