### ISSUE TITLE
Move bulk actions menu to the Footer, consolidate with floating toolbar and total items display

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#63193]
<img width="2656" alt="bulk-edit" src="https://github.com/WordPress/gutenberg/assets/846565/bd76cf8b-7e5d-46dd-b29b-ddae1050dbee">

The mockup above consolidates the bulk action UX in a single UI. In the page footer it's possible to select/deselect all visible items and perform bulk actions like trashing.

**Comment by jorgefilipecosta** [comment]
Hi @WordPress/gutenberg-design, is this issue ready to be developed following the mockup above?

**Comment by jameskoster** [comment]
@jorgefilipecosta barring any minor tweaks, I think so yes :)

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster, what is the plan regarding bulk actions like export as json, or permanently delete that currently don't have icons and are executed on "Bulk edit" menu? Should we add icons to them and show them in the footer like the others?

**Comment by jameskoster** [comment]
Yes, to begin with we can try adding icon buttons for all available actions.
