### ISSUE TITLE
Unregistering core/site-logo block crashes editor when editing Patterns

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#63208]
### Description

When using javascript to unregister the core/site-logo block, and trying to add/edit a Pattern, the editor crashes with the following error: TypeError: Cannot read properties of undefined (reading 'styleVariationSelectors')

### Step-by-step reproduction instructions

Enqueue the following javascript:

```
wp.domReady( () => {

    // does NOT crash editing Patterns; successfully unregisters archives block
    wp.blocks.unregisterBlockType( 'core/archives' );

    // crashes editing Patterns with error:
    // TypeError: Cannot read properties of undefined (reading 'styleVariationSelectors')

	wp.blocks.unregisterBlockType( 'core/site-logo' );
	

} );
```

Attempt to add or edit a Pattern. The editor crashes and lets you copy the error, which is:
TypeError: Cannot read properties of undefined (reading 'styleVariationSelectors')

### Environment info

WP 6.6-RC-2.  (I have confirmed the same behavior on 6.6-RC-1, but I am quite confident that this did not crash on the early Beta I tested, and it definitely doesn't crash on 6.5.5)
No Gutenberg Plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I was able to reproduce this issue too. This issue does not occur in WP6.5. It does occur in WP6.6 RC2 and the latest Gutenberg.

https://github.com/WordPress/gutenberg/assets/54422211/a1bc275c-df94-4334-9861-c27e4380ff71

**Comment by ndiego** [comment]
Yup, I can confirm, but this appears to be a larger issue. The Site Editor crashes when registering Image blocks as well and perhaps others. I have not tested all blocks.

```
wp.domReady( () => {
	// Crashes Site Editor with error:
	// wp.blocks.unregisterBlockType( 'core/site-logo' );
	wp.blocks.unregisterBlockType( 'core/image' );
} );
```

<img width="1528" alt="image" src="https://github.com/WordPress/gutenberg/assets/4832319/4a5b7f33-86cb-4136-abb3-061bb0ab43c6">

**Comment by ndiego** [comment]
Flagging you all since this appears to be an extensibility regression: @fabiankaegy @colorful-tones @ellatrix @vcanales

**Comment by t-hamano** [comment]
The following changes seem to fix the critical issue, but may not be ideal. Perhaps @aaronrobertshaw knows more about this part of the code?

```diff
diff --git a/packages/block-editor/src/components/global-styles/use-global-styles-output.js b/packages/block-editor/src/components/global-styles/use-global-styles-output.js
index 6756398708..41d6970d03 100644
--- a/packages/block-editor/src/components/global-styles/use-global-styles-output.js
+++ b/packages/block-editor/src/components/global-styles/use-global-styles-output.js
@@ -671,7 +671,7 @@ export const getNodesWithStyles = ( tree, blockSelectors ) => {
                                                }
                                                const variationSelector =
                                                        blockSelectors[ blockName ]
-                                                               .styleVariationSelectors?.[ variationName ];
+                                                               ?.styleVariationSelectors?.[ variationName ];
 
                                                // Process the variation's inner element styles.
                                                // This comes before the inner block styles so the
```

**Comment by ndiego** [comment]
> The following changes seem to fix the critical issue, but may not be ideal. 

🤞 this issue is just due to a missing `?`.

**Comment by aaronrobertshaw** [comment]
Thanks for the ping 👍 

It does look like I missed the optional chaining operator there, working under the impression the block nodes would match the available blocks. 

Given that isn't the case the proposed fix is along the right lines. This issue also shows that a variation's inner blocks could also be deregistered triggering a similar error a few lines down.

I'll put together a fix in a moment.

**Comment by aaronrobertshaw** [comment]
A fix following Aki's suggestion is available in https://github.com/WordPress/gutenberg/pull/63252.
