### ISSUE TITLE
Save Draft button incorrectly reports that the post was saved even when there's an error

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#6321]
## Issue Overview

The `Save Draft` button briefly shows the `✓ Saved` message, even if there's an error that causes the save to fail.

## Steps to Reproduce (for bugs)
1. Start writing a post.
2. Go offline.
3. Click the `Save Draft` button.

## Expected Behavior
The `Save Draft` button doesn't report a success message.

## Current Behavior
The `Save Draft` button shows `✓ Saved` before the larger `Updating failed` error banner appears.

**Comment by brandonpayton** [comment]
I'm no longer able to reproduce this on `master`.
![save-button-label-with-fail](https://user-images.githubusercontent.com/530877/46060809-50dffd80-c119-11e8-862f-3413dca311de.gif)
