### ISSUE TITLE
Custom HTML block still broken (2.7)

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#6323]
## Issue Overview

I assume this is known, but the Custom HTML block will simply not work for me.

## Steps to Reproduce (for bugs)

1. Open a new block
2. Click the circle-+ on the left
3. Click the Custom HTML option
4. Block shows: An unknown error occurred.

## Expected Behavior

I don't know - never been able to do this.

What is new is the Edit as HTML on the More Options menu. This works as expected. Perhaps the Custom HTML block is not needed any longer, because it certainly has never worked for me. I've tried since 2.4, I think. I've tested on Chrome and Firefox on a Mac using Twenty-Sixteen, as well as other themes.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
I think this is a duplicate to #5374 Closing let me know if it's a different issue.
