### ISSUE TITLE
wp-admin: latest Gutenberg styles adds extra padding to select boxes and create visual issue with Chrome

### ISSUE THREAD

**Issue by optimizewp** [WordPress/gutenberg#6326]
## Issue Overview
wp-admin: latest Gutenberg styles (`v 2.7.0`) adds extra padding to select boxes and create visual issues with Chrome (For Windows 64 bit)

## Steps to Reproduce (for bugs)

WP `4.9.5` and `5.0-alpha-42993`
Theme: Gutenberg (same issue with other Themes)
1. Login `wp-admin`
2. Edit a post/page/product/cpt

## Expected Behavior
Select boxes render well with FireFox, Edge, Safari and Chrome for Mac.

Gutenberg `v. 2.7.0` on Firefox Latest Version (same on Nigthly)

![image](https://user-images.githubusercontent.com/30923700/39063621-f9cb9a1e-44cb-11e8-846c-a964e908ac8f.png)

Gutenberg `v. 2.6.0` renders well on Chrome (latest version and Canary)

![image](https://user-images.githubusercontent.com/30923700/39063657-10e0e5ba-44cc-11e8-95c3-e8a7e23ecda5.png)

## Visual Issue

Looks trunk with Chrome (Windows), latest version and Canary (Windows).

![image](https://user-images.githubusercontent.com/30923700/39063389-3b7e9ef8-44cb-11e8-9cd4-cc41a5811eca.png)

## Possible Solution
Restore the padding to `2px`

**Comment by jasmussen** [comment]
Thanks for the report. I'll take this one.

**Comment by gziolo** [comment]
A similar issues reported by @StaggerLeee:

![](https://s31.postimg.cc/w1hqx4abv/2018-04-20_193425.jpg)
