### ISSUE TITLE
Copy/paste: heading isn't retained when copy/pasting and is instead shared as a paragraph

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#63274]
Using WordPress nightly and 6.6 RC2, I noticed that if I have a heading block and try to copy/paste it, it's pasted as a paragraph block:

https://github.com/WordPress/gutenberg/assets/26996883/3b482963-778f-4ada-90d3-5ed2ce2a80dd

I was writing a post the other day and found this to be wildly frustrating as I needed the headings to be retained. It seems that if you have text below a heading, it'll differentiate it and copy/paste correctly:

https://github.com/WordPress/gutenberg/assets/26996883/798e5ce9-3b89-434a-9668-aa323c243c9d

Compare this to, for example, Google docs where I can copy/paste headings wherever and it'll be retained:

https://github.com/WordPress/gutenberg/assets/26996883/12b5cfcf-dd98-4eba-a9c7-7a590e2e7938

Adding this to the 6.6 board but I imagine we may not be able to get a fix in time. Might be better for a point release.

**Comment by ellatrix** [comment]
@annezazu I think this is a duplicate of #48040?

**Comment by annezazu** [comment]
Ah you’re right! Closing. Not sure how I missed that in my searching.
