### ISSUE TITLE
Post Editor: 40vh padding applied to the bottom is overwritten with zero

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#63278]
### Description

In WP6.6, when `useRootPaddingAwareAlignments` is `false` in `theme.json`, the expected `40vh` padding below the content in the post editor is overwritten with zero.

This makes it difficult to click below the content and insert a new block.

I think the issue is related to the CSS selector that applies the zero padding changing from `body` to `:root :where(body)`, which has a higher specificity.

### ✅ useRootPaddingAwareAlignments: true

![image](https://github.com/WordPress/gutenberg/assets/54422211/1e40537b-0a56-4e6b-b78a-dea8d776bf37)

### ✅ useRootPaddingAwareAlignments: false

![image](https://github.com/WordPress/gutenberg/assets/54422211/7864fb40-82c0-408f-93e5-933a924176a3)

### ✅ useRootPaddingAwareAlignments: true

![image](https://github.com/WordPress/gutenberg/assets/54422211/c85c44a1-4006-44d1-bfb2-93613e52c2d5)

### ❌ useRootPaddingAwareAlignments: false

![override-padding](https://github.com/WordPress/gutenberg/assets/54422211/666e3044-89e6-4e2f-8780-af2c31ed74a6)

### Step-by-step reproduction instructions

- Define the theme.json for your block theme as follows:
  ```json
  {
  	"version": 2,
  	"settings": {
  		"layout": {
  			"contentSize": "620px",
  			"wideSize": "1280px"
  		}
  	}
  }
  ```
- Open the post editor and insert some content.
- Scroll to the very bottom of the content.
- There will be no padding below the content.

## Actual

![actual](https://github.com/WordPress/gutenberg/assets/54422211/51cf05b5-4279-40fd-b177-4421f8d7757e)

## Expected

![expected](https://github.com/WordPress/gutenberg/assets/54422211/8b7a29df-d7cd-495f-9f2e-2548b24187da)

### Environment info

WordPress 6.6 RC2 and latest Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I don't know much about `useRootPaddingAwareAlignments`. 🤔

I guess the `40vh` rule should be bumped to `0,1,0` specificity?
