### ISSUE TITLE
theme.json schema only allows version 3

### ISSUE THREAD

**Issue by MatzeKitt** [WordPress/gutenberg#63280]
### Description

The current schema for `theme.json` only allows version 3 to be used:

https://github.com/WordPress/gutenberg/blob/trunk/schemas/json/theme.json#L2748

Since this file will be loaded by using ` https://schemas.wp.org/trunk/theme.json` as schema in your `theme.json` (as described in https://developer.wordpress.org/themes/global-settings-and-styles/introduction-to-theme-json/), using any other value will result in an invalid `theme.json`.

### Step-by-step reproduction instructions

Create a `theme.json` with the following content and view it in an editor that uses the schema to validate it (e.g. Visual Studio Code):

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2
}
```

### Screenshots, screen recording, code snippet

<img width="439" alt="Bildschirmfoto 2024-07-09 um 07 22 57" src="https://github.com/WordPress/gutenberg/assets/1018979/f6a1c17d-3654-4ba5-bf03-ee2d4d5ab758">

### Suggestion on how to fix it

Allow also earlier versions. In that case, 1 and 2.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi
This is the intended behavior because trunk is the development version of the schema. It needs to support version 3, and any new theme.json features that are added to Gutenberg.
The validation will be wrong if the schema is not intended to be used with the WordPress version you are using.
Use the schema that is for the themes minimum required WordPress version.

https://make.wordpress.org/core/2024/06/19/theme-json-version-3/

**Comment by MatzeKitt** [comment]
I’m not sure if I understand correctly. I do use the version for the required WordPress version, which is 2. However, in the `theme.json` alone any other version as 3 will be marked as not allowed since it’s the only valid version according to the schema. 

As far as I know, there is no other schema under https://schemas.wp.org to be usable, that has the correct version for me.

**Comment by carolinan** [comment]
Use the schema version that matches your minimum required WordPress version.
https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-v2/

Quote:
The last schema for version 2 is available at `https://schemas.wp.org/wp/6.5/theme.json`.

Theme.json schemas for each WordPress version are available at  https://schemas.wp.org/wp/{{version}}/theme.json.
For example a schema for WordPress 5.9 is available at  `https://schemas.wp.org/wp/5.9/theme.json `.

**Comment by MatzeKitt** [comment]
Ah, thanks! I couldn’t finde that reference.
