### ISSUE TITLE
Will it be possible to wrap Classic Block with <!-- wp:classic --> ?

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#6330]
Hi,

I'm still testing my plugin integration for https://wordpress.org/plugins/block-options/ and found an issue with the Classic Block. It seems that this block wasn't wrapped with the required block tags. Will it be possible to wrap it with `<!-- wp:classic -->`? This will enable us devs to add more attributes to this block. Thanks! 

Tagging @aduth and @gziolo since you both helped me a lot on my previous issues. Thanks!

**Comment by gziolo** [comment]
Not sure to be honest, but I guess it is designed this way to make it clear that Classic Block exists only for backward compatibility reasons. @mcsf or @mtias should be able to confirm.

**Comment by mcsf** [comment]
Hi, @phpbits. The Classic block, by definition, represents pre-Gutenberg content: it's the non-block block. :) As @gziolo points out, it's merely there for backwards compatibility. Thus, there are no plans to wrap it with block tags. I also struggle to see what an attribute for it would _mean_, so could you expand on:

> This will enable us devs to add more attributes to this block.

Thanks!

**Comment by mcsf** [comment]
> How about when the Classic Block was used as block and not the backward compatibility?

I'm not sure I understand the question.

> Here's my plugin which adds additional attributes on each block

That doesn't help us know _what_ information would need to be encoded alongside a Classic block, or _why_. Without that information, I can't recommend anything else.

FWIW, at the parser level, Classic content is picked up as _freeform_, represented as a quasi-block with only inner HTML and no attributes. There are no plans to change this, since conceptually Classic "blocks" can be no more than this.

https://github.com/WordPress/gutenberg/blob/eabf6821c76d56bbbc00dd70f6d539b9199fbe67/blocks/api/post.pegjs#L97-L102

https://github.com/WordPress/gutenberg/blob/eabf6821c76d56bbbc00dd70f6d539b9199fbe67/blocks/api/post.pegjs#L163-L169

**Comment by phpbits** [comment]
@mcsf What I mean is what if I use the Classic Block when I've doing Gutenberg contents? It should work as regular block wrapped with  since it's been used the same way as the other blocks. Thanks!

**Comment by mcsf** [comment]
Regardless of whether the block was spawned out of back-compat to handle older content, or whether the block was added explicitly to contain arbitrary TinyMCE content, it will be represented in `post_content` as non-demarcated content.

>  It should work as regular block wrapped with since it's been used the same way as the other blocks.

At the `post_content`-level, it will remain an exception, at least for now. However, during an editing session, it will exist in memory as a proper block.

It cannot, however, have attributes sourced from `post_content`. It is still not clear to me what kind of attributes could be created for Classic. By definition, it represents content unaware of the block abstraction, so it cannot have block attributes; it can only have its own HTML markup and perhaps post meta, if fitting.

**Comment by mcsf** [comment]
> However, during an editing session, it will exist in memory as a proper block.

For the record, this means that it's possible to get creative with hooks and intercept Classic blocks in the editing context, if you need to.
