### ISSUE TITLE
Site Logo: editing aspect ratio isn't respected when selecting square option

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#63319]
When testing 6.6 RC2, after adding an image to the site logo block, I tried cropping the image and setting aspect ratio to square. After selecting apply, the setting doesn't stick and the site logo isn't 1:1:

https://github.com/WordPress/gutenberg/assets/26996883/e500044e-9962-46f2-ba37-07939fbe8cb3

In 6.5.5, this works as expected and the aspect ratio is changed to 1:1. 

Opening this to be safe with the final RC out today but will test with RC3 later today!

**Comment by ellatrix** [comment]
Looks like this is broken for image too (so generally). The edit request looks fine, it looks like something is going wrong server side.

**Comment by ellatrix** [comment]
I checked out the `wp/6.5` branch for _Gutenberg_, and it's still broken. Yet it works for WP 6.5. That tells me the problem is somewhere on the REST API side in core. Maybe we should create an issue there too?

**Comment by ellatrix** [comment]
I filed this Trac issue for visibility: https://core.trac.wordpress.org/ticket/61612.
Also marked it high priority/major severity, since I think it's a pretty bad bug.

**Comment by annezazu** [comment]
Thank you so much, Ella!

**Comment by Mamaduka** [comment]
Looks similar to #62855.

**Comment by ellatrix** [comment]
Yes, this has actually just been fixed a few hours ago in core in https://core.trac.wordpress.org/ticket/61514, so it's in RC 3!

**Comment by annezazu** [comment]
WHEW! Awesome. I didn't catch that when looking for site logo specific issues (rather than image) so thank you for connecting things.

**Comment by andrewserong** [comment]
+1 thank you for connecting these, and great to hear that the fix landed in time for RC 3!
