### ISSUE TITLE
Preview for published posts not working when editing

### ISSUE THREAD

**Issue by matto15** [WordPress/gutenberg#6331]
Hi. I don't know if this has been reported before or if anyone else is experiencing it, but I have tested versions 2.5 and the latest version (2.7.0) on my staging site and when I am editing an already published post and click preview, the preview does not generate and it only brings a white screen with the "generating preview" text but it is stuck there. I have to switch the post to draft for the preview to work.

**Comment by pento** [comment]
Thanks for the bug report, @matto15! This has been previously reported in #4625, though is actually a symptom of Autosave not being implemented yet, which is being worked on in #6257.

**Comment by myleshyson** [comment]
Hey I just updated Gutenberg with #6257 being merged in and I'm still seeing the same white screen when trying to preview a post. Using 2017 Theme on fresh Wordpress Install. Steps to reproduce:

1) Go to hello world post, click "Preview" and the post preview page shows up fine.
2) Go back to post and then start typing. 
3) Hit "Preview" button again, and now the white screen shows up.

**Comment by HavaCo** [comment]
The same is happening to me.

**Comment by designsimply** [comment]
I have just re-tested with @myleshyson's testing steps and I was unable to reproduce the problem (using WordPress 4.9.8 and Gutenberg 3.5.0 with Firefox 61.0.2 on macOS 10.13.6).

In case autosaves are a factor here, please see https://github.com/WordPress/gutenberg/issues/7852#issuecomment-413049850 for some testing steps that result in previews getting stuck for me and note that https://github.com/WordPress/gutenberg/issues/7416 is the issue to follow for that bug.

**Comment by joostmollerus** [comment]
I am using Gutenberg version 3.6.2 (Chrome Version 68.0.3440.106, OS: Windows 8.1 and WordPress 4.9.8)
One site running Attitude (by Theme Horse) Child theme, has the same problem when using preview: Preview opens and says "generating preview" forever.
However another site running Twenty Twelve,Version: 2.5 by the WordPressteam
has no problems in generating the preview:
So maybe the theme used determines if there is a problem when generating the preview?
Please let me know if you need additional information
