### ISSUE TITLE
Document bar: Long title with no spaces cause layout issue

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#63329]
### Description

The command palette shortcut text is pushed to the right when you insert a long piece of text without spaces.

This issue is more likely to occur in CJK languages ​​that don't insert spaces between words.

### Long Post Title

![long-title-ja](https://github.com/WordPress/gutenberg/assets/54422211/1019f011-b79c-41c4-8f40-48b47287d9f7)

### Long Pattern Name

![image](https://github.com/WordPress/gutenberg/assets/54422211/ad1d876e-ba3b-47b1-8d10-e7de2e9a866f)

### Long Template Name

![image](https://github.com/WordPress/gutenberg/assets/54422211/997de52b-f2cd-4305-9eae-fa2008d82dc6)

Also, this issue can occur in English if you have a long piece of text with spaces.

![long-title-en](https://github.com/WordPress/gutenberg/assets/54422211/068fd56b-fbe1-445c-9b8f-8e5e89871317)

### Step-by-step reproduction instructions

Create posts, templates, template parts, and variations with long titles.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Rishit30G** [comment]
Hey @t-hamano, 
Is this problem specific to windows devices ? 
It seems to be working fine on mac, sharing the screenshot 
<img width="277" alt="image" src="https://github.com/WordPress/gutenberg/assets/74411873/e108f600-540b-4d2b-b111-9c05b6cc2b24">

**Comment by t-hamano** [comment]
@Rishit30G 

Thanks for testing.

Maybe the shortcut text on Windows (`Ctrl+K`) is longer than the shortcut text on Mac (`⌘K`), which is why this problem occurs.
