### ISSUE TITLE
Post status option text is cut from the bottom

### ISSUE THREAD

**Issue by burhandodhy** [WordPress/gutenberg#6332]
## Issue Overview

The text of option of post status is cut off from the bottom. http://prntscr.com/j84gzi

## Steps to Reproduce (for bugs)

1. Go to edit post screen

Using Google Chrome Version 66.0.3359.117 (Official Build) (64-bit)

## Current Behavior

Text is cut off from the bottom 
## Possible Solution

Reduce 2px top and bottom padding
## Screenshots / Video
http://prntscr.com/j84gzi

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by pento** [comment]
Thanks for the bug report, @burhandodhy! We're tracking this issue in #6326.
