### ISSUE TITLE
Post Date Block: Offer relative date option

### ISSUE THREAD

**Issue by cdils** [WordPress/gutenberg#63325]
## What problem does this address?
The Post Date block has a variety of date format options, including the option to enter a custom date format, but it would be nice to have the option to show the publish date as relative to the current date, something like:

`Published x days ago`

<img width="870" alt="screen shot of wordpress post editor depicting a list view with the Date block selected and the corresponding block settings panel" src="https://github.com/WordPress/gutenberg/assets/3099408/68eec4f0-2b52-4c32-839a-726474282f76">

This was a possible feature request noted a few times in https://github.com/WordPress/gutenberg/issues/38751 by @kjellr, @ramonjd, and @jasmussen. As @mtias pointed out in https://github.com/WordPress/gutenberg/issues/38751#issuecomment-1060870156, that enhancement was out of scope for that ticket.

## What is your proposed solution?

I'm not familiar enough with how the Date block works to know if this feature is in or out of scope for that block's intended use.

Currently, the `Custom` format only allows for a date/time format string and does not support free-form text, which makes total sense. But, if you wanted to display something like `Published x days ago` then that brings up some questions:

1. Is the user allowed to append free-form text to the number of days since publishing? Adding custom text before and/or after the number of days seems like the most friendly approach for no or low code users. Though it would be nice to be able to programmatically filter that text.
2. Any accompanying text strings, whether hard-coded or user-generated would need to account for singular/plural day/days, depending on context (e.g., `1 day ago`, `2 days ago`. And internationalization would need to be accounted for, of course.
3. What would would you call it? Perhaps between the various date formats and the `Custom` option there's an option called `Relative Date` (see mock image)

<img width="271" alt="image" src="https://github.com/WordPress/gutenberg/assets/3099408/27cfe0b1-9e64-4c2c-8e75-e9da9ad1ab47">

**Comment by t-hamano** [comment]
Thanks for the suggestion.

Relative date format was already implemented in #62298, but this formatting is not part of WordPress 6.6, which will be released next week.

**Comment by jasmussen** [comment]
Just seeing this typographic widow:
![Screenshot 2024-07-10 at 08 34 26](https://github.com/WordPress/gutenberg/assets/1204802/7c779579-0404-47bc-8ce8-dbcf73202cbf)

Would be good to add text-wrap: balance; to this component.

**Comment by cdils** [comment]
> Thanks for the suggestion.
> 
> Relative date format was already implemented in #62298, but this formatting is not part of WordPress 6.6, which will be released next week.

Thank you @t-hamano I'd missed https://github.com/WordPress/gutenberg/issues/62259 as I'd made a rookie mistake and was searching for open issues. Excited to see this land in Core. 🙏🏻
