### ISSUE TITLE
Site Logo: Improve the initial state

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#63327]
## What problem does this address?
The initial state of the Site Logo block is not clear enough about how to upload the image. (Additionally, the tooltip can be obscured by the floating toolbar). 

<img width="592" alt="image" src="https://github.com/WordPress/gutenberg/assets/4550351/5690fed7-57f1-463d-b4df-655673996833">

There is a button to "Add media" too, but it's tucked away in the block settings in the sidebar, which may or may not be open.

Compare this to the initial state of the Image block that clearly lists the ways an image can be added:

<img width="640" alt="image" src="https://github.com/WordPress/gutenberg/assets/4550351/9883c76e-a1bc-45a5-9018-03e628836689">

## What is your proposed solution?
I would like to propose aligning the initial state of the Site Logo block with the Image block. or otherwise making it more obvious how to upload an image (maybe by adding an "Add media" action to Site Logo block toolbar).

**Comment by Mamaduka** [comment]
cc @jasmussen, since we've worked on MediaPlaceholder design(s) before :)

**Comment by jasmussen** [comment]
This one is very much related to #63254 in more ways than one. But the most important one is: the block _has to be able to work when it's that small_, because it's a valid use case to use the site logo in that small space. 

Adding "add media" to the inspector and adjusting the tooltip feel like good ways to progress, and I'd echo the Image block can be adjusted to match this too.

**Comment by mtias** [comment]
The "replace" workflow once something is set is very clear, so I think the placeholder state should inherit that and just have an "add image" in the toolbar

**Comment by jasmussen** [comment]
[This mockup](https://github.com/WordPress/gutenberg/issues/63382#issuecomment-2222699236) makes progress on suggestions from the conversation here.
