### ISSUE TITLE
Image block can be resized beyond the bounds of the column that it's in

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#63326]
### Description

When you have an Image block within a Columns block, you can currently use the resize handles on the image to resize it beyond the bounds of the column, which results in a pretty broken looking layout. The resize bounds should be limited to the column.

### Step-by-step reproduction instructions

1. Insert a new post
2. Add a Columns block with two columns
3. Add an image to each column
4. Select one of the images and resize it vertically downwards
5. The image overflows the column, but shouldn't

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/612155/cc5e05dd-79b7-46aa-b2ae-37c77acc3ca3

### Environment info

Latest Gutenberg + Core trunk. Firefox. macOS.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by noisysocks** [comment]
`ResizableBox` has a `bounds` prop which you can set to a `DOMElement`. I think fixing this should be a case of setting `bounds` to be the parent Column block's element (using `useBlockElement`) when the parent block is a Column block.

**Comment by Mamaduka** [comment]
This reminds me of #26715, which I think should be re-opened as the proposed fix reverted in #47846.
