### ISSUE TITLE
Missing type attribute for post publish panel <input>

### ISSUE THREAD

**Issue by spencerbaynton** [WordPress/gutenberg#6334]
There is no `type` attribute set on this `<input>`:

https://github.com/WordPress/gutenberg/blob/112c7522d22d0e61b6e904727583bd5dc4be831c/editor/components/post-publish-panel/postpublish.js#L68-L73

Currently displayed as:

![screen shot 2018-04-21 at 06 37 33](https://user-images.githubusercontent.com/1483584/39083211-d8f725b6-452e-11e8-9c02-90c528b8e279.png)

It might be better to replace the entire `<input>` with a `TextControl` component.

```js
import { TextControl } from '@wordpress/components';

...

<TextControl
	className="post-publish-panel__postpublish-link-input"
	onFocus={ this.onSelectInput }
	readonly
	value={ post.link }
/>
```

**Comment by pento** [comment]
Thank you for the bug report, @spencerbaynton!

Is there any particular reason why you'd need the `type` to be defined? All browsers use the `text` type if one isn't defined. ([Ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Form_%3Cinput%3E_types))

**Comment by spencerbaynton** [comment]
I'm using Firefox 59.0.2 and without an explicit `type` the input element isn't being correctly styled. The image above shows how it is currently being styled. With the `type` explicitly set the element appears like:

![screen shot 2018-04-21 at 07 04 37](https://user-images.githubusercontent.com/1483584/39083479-5b5d54aa-4532-11e8-9a48-8cf501e5d8f6.png)
