### ISSUE TITLE
Editing Post Meta triggers multi-entity save flow and duplicate site editor save request

### ISSUE THREAD

**Issue by lgladdy** [WordPress/gutenberg#63355]
### Description

In WordPress 6.6 RC3 (although, I replicated this on beta1 as well), editing an ACF Block is triggering the multi-entity save flow in the site editor when editing a post.

This triggers a notification that something is changing about the site (when actually, it's just in the post being edited) and accepting the save triggers two duplicate POST requests to update the post. One of which completes with `Site Updated` and one with `Post Updated` notifications in editor.

### Step-by-step reproduction instructions

My reproduction steps are with ACF Blocks, but our blocks only update the block comment within our data attribute on edit, we also trigger `wp.data.dispatch('core/editor').editPost({ meta: { _acf_changed: 1 } });` whenever an ACF field is changed so we can do some tracking for revisions. My guess is it's this call that is triggering Gutenberg to believe a site change has happened, show the multi-entity save panel and then duplicate the POST request to actually save.

### Screenshots, screen recording, code snippet

https://youtu.be/X7fR-xrKIQE (sorry about the mono audio)

### Environment info

WordPress 6.6 RC3
Chrome and Safari latest

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by lgladdy** [comment]
A Making WordPress slack discussion on this bug is here: https://wordpress.slack.com/archives/C02QB2JS7/p1720616434101469

**Comment by lgladdy** [comment]
A second bug exists in this flow as well.

If a post is locked using `wp.data.dispatch( 'core/editor' ).lockPostSaving( 'test' );` - the save button is disabled as expected, but you can still click it to bring up the multi-entity save panel, and it will still submit the POST request which triggered `Site Updated` - although, the `Post Updated` call doesn't take place.

**Comment by SantosGuillamot** [comment]
I've opened this [pull request](https://github.com/WordPress/gutenberg/pull/63412) to revert the changes that caused both issues.

**Comment by lgladdy** [comment]
Resolved by #63412.

We're tracking what happens next in #63425 here.
