### ISSUE TITLE
Tag cloud: Improve "no content" rendering when there are no tags

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#63354]
Like many other blocks, we should not render a "no content" message on the front end.

I propose the editor could render example tags (even tag-1, tag-2) if there are no tags. 

And on the front end, don't render anything (not unlike the empty button block, or empty site description). 

### Current (editor)

![CleanShot 2024-07-10 at 09 15 02](https://github.com/WordPress/gutenberg/assets/1813435/0ff20824-6f27-42eb-8acb-79482f600200)

### Current (front end)

![CleanShot 2024-07-10 at 09 22 27](https://github.com/WordPress/gutenberg/assets/1813435/c454142d-8303-4dcc-806c-33ec4d9a5c4b)

**Comment by akasunil** [comment]
I'm not sure about the examples of tags. However, text messaging has to be improved to be more specific to tag cloud block.
Also, we definitely should prevent the block from rendering on the front end if tags are not available.

**Comment by akasunil** [comment]
Duplicate issue of https://github.com/WordPress/gutenberg/issues/63684

**Comment by richtabor** [comment]
And both mine. I'll close this one as the other is clearer. 😅
