### ISSUE TITLE
Query Loop polishing issues for 6.7

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#63361]
This is a non exhaustive list of issues we could aim to land for 6.7 to improve the user experience around this block. 

More issues will be added and please feel free to add or suggest more to be included.

- [ ] https://github.com/WordPress/gutenberg/issues/63350
- [ ] https://github.com/WordPress/gutenberg/issues/31158
- [x] https://github.com/WordPress/gutenberg/issues/30369
- [ ] https://github.com/WordPress/gutenberg/issues/63028
- [ ] https://github.com/WordPress/gutenberg/issues/49280 particularly for a blog pattern
- [ ] Replace “post type” with “content type” and the dropdown should be radio if there are only two options.
- [ ] https://github.com/WordPress/gutenberg/issues/42810
- [x] https://github.com/WordPress/gutenberg/issues/63497
- [x] #63598
- [x] #63599
- [ ] https://github.com/WordPress/gutenberg/issues/42554
- [x] https://github.com/WordPress/gutenberg/issues/64746
- [x] https://github.com/WordPress/gutenberg/pull/64167
- [x] https://github.com/WordPress/gutenberg/pull/65524

**Comment by jeryj** [comment]
Do we want to set the default value of the query block to be inherit as well? If so, here's a quick PR for it: https://github.com/WordPress/gutenberg/pull/63362

**Comment by ktmn** [comment]
> Query Loop deletion from template: make the warning message more understandable by adding context

This message has never done anything but needlessly interrupt me, unfortunately. 

Perhaps this kind of hand-holding stuff could be grouped and opt-out-able when you first onboard. Some people will make hundreds of sites but on every new site the editor will assume you know nothing.

**Comment by Marc-pi** [comment]
IMHO the most needed improvement is the skip current post ID
https://github.com/WordPress/gutenberg/issues/42810

**Comment by brnhrst** [comment]
Nice to see some progress on this block. How about adding more options for the sort order, like #51290 or #50999? In my opinion, these are low-hanging fruit that would greatly improve this block for the end user.

**Comment by ddegner** [comment]
> Nice to see some progress on this block. How about adding more options for the sort order, like #51290 or #50999? In my opinion, these are low-hanging fruit that would greatly improve this block for the end user.

Absolutely, the ability to ad a randomized post from a specific category would be useful for many sites that want to highlight their archive.  I was surprised when looking for this feature and it had been removed.

**Comment by carolinan** [comment]
I would like to add the post format filter to this list since we know that post formats where [highly requested by users for 6.7](https://make.wordpress.org/core/2024/07/08/what-would-you-like-to-see-in-the-next-default-wordpress-theme/).
The issue has a very long discussion in it, and is not limited to one feature: https://github.com/WordPress/gutenberg/issues/53049
The experimental PR is more limited in its scope. https://github.com/WordPress/gutenberg/issues/53049

**Comment by annezazu** [comment]
I think you meant to link to https://github.com/WordPress/gutenberg/pull/64167! I'm going to add this in for the sake of tracking. Thank you <3

**Comment by noisysocks** [comment]
Lots of unchecked boxes here and only a fortnight until the last Gutenberg RC before Beta 1. Shall we move this overview issue to the "Punted to 6.8" column?

**Comment by annezazu** [comment]
As a quick update, some improvements have happened that weren't tracked here. Much of this work has focused on the default settings of the Query Loop block and various UX refinements to configure it properly. 

Done:


- [Add example for query block and posts list](https://github.com/WordPress/gutenberg/pull/63286#top)
- [Replace "Add new post" link text with more meaningful Label (v2)](https://github.com/WordPress/gutenberg/pull/62277#top)
- [Update help text for sticky control in Query loop ](https://github.com/WordPress/gutenberg/pull/63999)
- [Update: Rephrase "Force page reload" and move to Advanced](https://github.com/WordPress/gutenberg/pull/65081#top)
- [Update Inherited Query Loop value from Template Settings changes](https://github.com/WordPress/gutenberg/pull/63358#top)
- [Query Loop block: Convert the post content type setting to a ToggleGroupControl if there are few items](https://github.com/WordPress/gutenberg/pull/63375#top)
- [Make Query Loop settings more intuitive with a ToggleGroup and simplified help text](https://github.com/WordPress/gutenberg/pull/63375#top) 
- [Move Posts Per Page, Offset, and Pages controls from the block toolbar into Inspector Controls](https://github.com/WordPress/gutenberg/pull/58207#top)
- [Query Loop: Change default query loop variations](https://github.com/WordPress/gutenberg/pull/63353#top)
- [Set query loop to have the inherit value by default ](https://github.com/WordPress/gutenberg/pull/63362)
- [Query Loop Block: remove Posts List variation](https://github.com/WordPress/gutenberg/pull/63404#top)

In progress:
- https://github.com/WordPress/gutenberg/pull/64916
- https://github.com/WordPress/gutenberg/pull/64167
- https://github.com/WordPress/gutenberg/pull/63147
- https://github.com/WordPress/gutenberg/pull/61222

The latter two seem unlikely to land but could perhaps with some additional help.

**Comment by emdashftw** [comment]
Long awaited... Thanks in advance to all the people involved on this.
I should still read all the related issues to better understand what's really going on...

But I can try to give my UX feedback. For me the three most frustrating things about the Query Loop / Pagination blocks are:
- That for some time I've found it was difficult/too confusing for me to implement different designs for the first page of the query loop and the paginated ones. Or to add markup between the posts in the paginated pages...

- That there's a Bug with the pagination of the last page that makes it blank when the "inherit" is off. I can still repro it. Happens with WP 6.6.2 & Gutenberg 19.1.0
https://github.com/WordPress/gutenberg/issues/47252

- I really dislike that depending on if we inherit or not, the Urls are expressed like `/page/2` or something like `/?query-22-page=2`. I'd wish the pagination to always be like the former, and that the context details could be managed internally... fully transparent to the URL and the end user.

**Comment by afercia** [comment]
I'd like to propose to add https://github.com/WordPress/gutenberg/pull/65524 to the list.

**Comment by mikachan** [comment]
> I'd like to propose to add https://github.com/WordPress/gutenberg/pull/65524 to the list.

I've added it to this list, but as I'm not sure what's possible for 6.7, I've also added it to this larger tracking issue for extra visibility: https://github.com/WordPress/gutenberg/issues/41405.

**Comment by annezazu** [comment]
With 6.7 out in the world, let's close this out. If we have a set of issues for 6.8, please open a new iteration issue so folks can follow along.
