### ISSUE TITLE
Patterns: add a "blank" option to make it easier to start fresh

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#63377]
When opening a new page while using a theme that has starter patterns available, you're presented with a modal that shows all available patterns. To get out of that flow though or skip it, the only option is to select the X to close out the modal. This is a bit more cumbersome than it should be, especially considering these patterns are likely to cover ever use case. To help

Current:

![Screenshot 2024-07-10 at 10 52 40 AM](https://github.com/WordPress/gutenberg/assets/26996883/fb79dda9-fc20-4271-a08d-faf5b464110f)

Proposed:

![Screenshot 2024-07-10 at 10 53 59 AM](https://github.com/WordPress/gutenberg/assets/26996883/8ea3f46c-b6a6-400f-8cf3-7eb1499661a7)

I don't think this is the best ^ but just to share an idea. If anything, I think we need to make the "start blank" more obvious. As is, this modal is a bit rough around the edges as it's hard to read the names of patterns and to see where one pattern ends before another begins, especially since they are different sizes. 

Note that there's an[ experimental PR](https://github.com/WordPress/gutenberg/pull/61489) around adding zoom out mode with patterns opened in the Inserter instead of starter patterns too which will help here. For now though, this would be helpful to iterate on as is.

**Comment by jasmussen** [comment]
Should probably say "Start blank" (lowercase b), but other than that my instinct would go to the same. The height is an open question, should it be square, portrait? No strong opinions there, and I'd think beyond larger changes (such as taking you into the assembler rather than opening this modal), there are good reasons to move this directly into a PR to get a feel for it.

**Comment by stokesman** [comment]
I'm glad to see the issue raised and think the suggestion has merit yet feel that it may be patching over what is a more general issue. That modal still surprises me and feels interruptive. I’ve thought of a couple ways it might be improved.

One, if its appearance could precede the editor visibility and act as an interstitial. This would avoid the reaction I always have where I think the editor is ready for interaction but suddenly the modal gets in the way. In such a case the “Start blank” option is still valuable.

Alternatively, I think that I’d rather have the choice to engage the “Choose a pattern” flow from a notice prompt instead. In this case “Start blank” wouldn’t be as valuable. I realize perhaps many folks are going to reach for a pattern most of the time and this would add a touch a of friction for them. If they’re they ones to optimize for I guess this is a non-starter. Though I wish it could be a preference at least.

**Comment by carolinan** [comment]
Does it need to be the full size of a blank page? 

The pattern selection for templates has a skip button in the bottom right corner, which is missing on the page pattern selection, is this intentional?

**Comment by carolinan** [comment]
I briefly looked into adding a new blank item or button inside  `StartPageOptionsModal` or `BlockPatternsList` and I was not able to do it.

Could it perhaps be a button next to the panel heading?

**Comment by richtabor** [comment]
I want to be cognizant that this will likely get replaced by a much more efficient [composition flow leveraging zoom out](https://github.com/WordPress/gutenberg/issues/50739), rather than a modal that stands in the way. 

[Here's an experiment ](https://github.com/WordPress/gutenberg/pull/61489) that @ellatrix put together on this front.

**Comment by annezazu** [comment]
Right! I noted that in the original issue:

>Note that there's anhttps://github.com/WordPress/gutenberg/pull/61489 around adding zoom out mode with patterns opened in the Inserter instead of starter patterns too which will help here. For now though, this would be helpful to iterate on as is.

I still think we can iterate for now as zoom out mode remains experimental.

**Comment by annezazu** [comment]
Closing this out as we now have a user preference to opt out of this and, in the future, zoom out is likely to take over the flow: https://github.com/WordPress/gutenberg/pull/65026
