### ISSUE TITLE
Multi-entity save: reverse order of save and cancel buttons when saving in the frame

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#63372]
When saving changes in the frame rather than in the canvas, the order of the buttons should be reversed to make it more obvious to click the primary call to action ("save"). Generally, the primary action for items is often found on the right side. 

**Current:**

![Screenshot 2024-07-10 at 10 30 04 AM](https://github.com/WordPress/gutenberg/assets/26996883/6e1c447f-eee1-4e0e-9a92-a003eff35b85)

**Proposed**

![Screenshot 2024-07-10 at 10 35 47 AM](https://github.com/WordPress/gutenberg/assets/26996883/f4991f65-1006-483c-b0ed-197d5b32e282)

Of note, currently when saving in the canvas/editor, we show a similar order to the current and I wonder if we should also update there:

![Screenshot 2024-07-10 at 10 36 55 AM](https://github.com/WordPress/gutenberg/assets/26996883/bd297587-5940-4049-a3aa-9347bca85ad5)

cc @WordPress/gutenberg-design for more context and thoughts.

**Comment by jasmussen** [comment]
I would think both of these interfaces could use substantial design refreshes. But that shouldn't block this.

**Comment by jameskoster** [comment]
> I wonder if we should also update there

That will probably be necessary to avoid falling foul of a11y requirements (visual order should match DOM order).

**Comment by richtabor** [comment]
One note: if the save and cancel buttons are inverted in the second publish sidebar, when you press Save and the sidebar opens up, you'll press the cancel button almost immediately.

**Comment by jasmussen** [comment]
One thing we could do, which I've seen discussed in other comments, is move the save/publish button almost all the way to the right:

<img width="1632" alt="Option" src="https://github.com/user-attachments/assets/55a4c4b9-91f9-42a2-b8aa-4904521452d7">

[Figma](https://www.figma.com/design/skEBFXtKMZKe9nstJYEXn2/Toolbar%2C-Top-Toolbar?node-id=1-2993&t=YqHi9VuXlyx4qDyE-1).

**Comment by richtabor** [comment]
> One thing we could do, which I've seen discussed in other comments, is move the save/publish button almost all the way to the right:

If we do, should the Inspector icon always be first next to it? So that it's consistently in the same place?

**Comment by jasmussen** [comment]
Yes, like so, good catch:

<img width="1632" alt="" src="https://github.com/user-attachments/assets/9ae28376-efaa-4e62-9881-1cc548dcf99e">

**Comment by juanfra** [comment]
It looks like this one was resolved with https://github.com/WordPress/gutenberg/pull/65695 - I just tested it, and the order of the buttons is reversed. I'm closing this one; please feel free to open it if you think there's something else to do.
