### ISSUE TITLE
Inserter plugin search results causes scroll issue

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#63405]
### Description

You can scroll the canvas out of view in the wrong context.

### Step-by-step reproduction instructions

1. Open inserter
2. Search for "date"
3. Scroll the inserter

Notice how the canvas itself scrolls out of view.

### Screenshots, screen recording, code snippet

![issue](https://github.com/WordPress/gutenberg/assets/1204802/41f1de3c-0bbd-42f0-b994-048ab5ce8b75)

### Environment info

Trunk GB, nightly WordPress.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Fixed via #63397.

**Comment by jasmussen** [comment]
Double posted the issue! Sorry about that, thanks for following up 🙏
