### ISSUE TITLE
Columns block: Container <div> does not receive alignfull or alignwide class

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#6342]
## Issue Overview

For GB Version 2.7.

Maybe two issues, but demo code is one example.

1. alignwide and alignfull not being added to the wp-block-columns div, even though it is in the meta data for the block. The wide/full is displayed correctly in the editor view, just not the front-end.
2. The layout-column-# is being assigned by the order the column content is added, and not the order of the columns on the screen. I'm not sure this is a bug, or just how it works.

## Steps to Reproduce (for bugs)

1. Create a 3 column block.
2. An equal sized images to each column.
3. Select wide or full for the columns block

## Expected Behavior

alignwide nor alignfull are added to the actual `<div>` wrapping the columns.

## Current Behavior

This is the code generated (similar for full). Note the column numbers generated correspond to the order I actually added the images: first column, last column, then middle column.

```html
<!-- wp:columns {"columns":3,"align":"wide"} -->
<div class="wp-block-columns has-3-columns">
    <!-- wp:image {"id":617,"layout":"column-1"} -->
    <figure class="wp-block-image layout-column-1"><img src="http:/example.com/wp-content/uploads/2011/01/dsc20050813_115856_52.jpg" alt="dsc20050813_115856_52" class="wp-image-617" /></figure>
    <!-- /wp:image -->

    <!-- wp:image {"id":611,"layout":"column-3"} -->
    <figure class="wp-block-image layout-column-3"><img src="http://example.com/wp-content/uploads/2011/01/canola2.jpg" alt="canola" class="wp-image-611" /></figure>
    <!-- /wp:image -->

    <!-- wp:image {"id":616,"layout":"column-2"} -->
    <figure class="wp-block-image layout-column-2"><img src="http://example.com/wp-content/uploads/2011/01/dsc20050727_091048_222.jpg" alt="dsc20050727_091048_222" class="wp-image-616" /></figure>
    <!-- /wp:image -->
</div>
<!-- /wp:columns -->
```

**Comment by noisysocks** [comment]
Can confirm that `alignwide` or `alignfull` are not added to the columns `<div>`. Note that you must be using a theme that supports wide/full alignment (e.g. [gutenberg-starter-theme](https://github.com/WordPress/gutenberg-starter-theme)) to reproduce this issue.

**Comment by noisysocks** [comment]
> Note the column numbers generated correspond to the order I actually added the images: first column, last column, then middle column.

Note that this peculiarity is a seperate issue https://github.com/WordPress/gutenberg/issues/6339

**Comment by jorgefilipecosta** [comment]
Thank you for reporting this issue @weavertheme! We fixed it with the merge of https://github.com/WordPress/gutenberg/pull/6364. If any problem is persisting in your tests feel free to reopen it and we will look further.
