### ISSUE TITLE
Permalink Edit hidden

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#6343]
## Issue Overview

The new permalink edit bar is mostly hidden on a full page view. I experience this on Chrome and Firefox. The bar is there, but barely sticks out from under the top menu bar. If I reduce browser width, the permalink edit shows up when the top bar switches to the reduced option button set.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by noisysocks** [comment]
Hi @weavertheme! I'm having a hard time re-creating this issue. Could you please attach a screenshot of what you are seeing?

I'm going to close this out for now. We can re-open the issue once we have some more information.
