### ISSUE TITLE
Inserter categories tabs rendering 48px instead of 40px

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#63440]
These are currently `48px` tall, due to recent updates to `Tab` it looks like. They should be the standard `40px` height. 

| Current  | Expected |
| ------------- | ------------- |
|![CleanShot 2024-07-11 at 10 34 12](https://github.com/WordPress/gutenberg/assets/1813435/7faa92f2-e693-4a47-980e-746d62cf4172)|![CleanShot 2024-07-11 at 10 35 08](https://github.com/WordPress/gutenberg/assets/1813435/72608d21-7cdf-415c-82ec-3b37486cf26b)|

**Comment by juanfra** [comment]
I can't replicate this one, I'm using Gutenberg trunk, and the computed height is `40px`.

https://github.com/user-attachments/assets/6961dc57-876d-4b38-8721-29b2b34ad801

I'll close this issue, but feel free to re-open it if it's still relevant or if there's anything else to fix.
