### ISSUE TITLE
Transform previews render over the transform popover when not enough space

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#63444]
The transform previews end up covering the transform menu items, if there's not enough room to display them. 

### Visual 
![CleanShot 2024-07-11 at 11 05 45](https://github.com/WordPress/gutenberg/assets/1813435/4bc76e85-396c-4b55-b3b9-5fca458c3f89)

**Comment by richtabor** [comment]
I question how helpful these are: 

https://github.com/WordPress/gutenberg/assets/1813435/864d6a1a-8e8f-487e-847b-e682c2c5f4be

**Comment by t-hamano** [comment]
Is this the same issue reported in #51309?

**Comment by richtabor** [comment]
Ah yes. Block Conversion tag should probably just be Transforms. I would have found it easily then.

**Comment by richtabor** [comment]
I think it'd be fine to remove previews from these.

**Comment by Mamaduka** [comment]
Let's close this as a duplicate.
