### ISSUE TITLE
Add a user preference for showing or hiding the pattern selection modal when creating new content

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#63468]
## What problem does this address?

By adding a user preference for wether the pattern selection modal should show when creating new pages, users could tailor their editing experience more to their own personal need.

## What is your proposed solution?

Add a user preference for showing or hiding the pattern selection modal when creating new content.
Either for pages only, or for all occurances.

**Comment by Mamaduka** [comment]
Maybe a post-type setting or a filter to make it global.

**Comment by richtabor** [comment]
I think we need to pause on this until we have a refined composition flow with zoom out. https://github.com/WordPress/gutenberg/issues/50739. It may just be efficient enough to be the default starting point for adding new pages, where a preference is not necessary. 

Related comment: https://github.com/WordPress/gutenberg/issues/63377#issuecomment-2226218674

**Comment by carolinan** [comment]
Thank you @richtabor.

**Comment by annezazu** [comment]
Closing this out as https://github.com/WordPress/gutenberg/pull/65026 was merged to do exactly this!
