### ISSUE TITLE
Pattern Inserter: Multiple undo histories are created

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#63479]
### Description

When I insert a pattern, multiple undo histories are created, so I cannot delete a pattern unless I press the Undo button several times after inserting it. The amount of history created depends on the pattern inserted.

I looked back through the commit history and it looks like this issue first appeared in #61915.

### Step-by-step reproduction instructions

After inserting a pattern, click the Undo button.

### Before #61915

https://github.com/user-attachments/assets/b78407f5-1986-4701-a63b-b4c00f5228d6

### After #61915

https://github.com/user-attachments/assets/4852705c-baca-4d7c-9b93-0d74b1aee909

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@t-hamano, the source PR for the bug seems incorrect. It's also the same PR that should fix it.

**Comment by t-hamano** [comment]
@Mamaduka Thanks for pointing that out! I've corrected the PR number.
