### ISSUE TITLE
Can't find useEntityProp in the Block Editor Handbook

### ISSUE THREAD

**Issue by silaskoehler** [WordPress/gutenberg#63475]
### Description

useEntityProp is not documented in the Block Editor Handbook. 
I only see the hooks useEntityRecord, useEntityRecords and useResourcePermissions
Is this on purpose? Is it deprecated?

(Honestly, I'm not sure it's okay to report this as a bug. Feel free to tell me where the right place for it would be.)

### Step-by-step reproduction instructions

1. I searched here: https://developer.wordpress.org/block-editor/reference-guides/packages/packages-core-data/
2. I find it here in a how to guide for meta boxes: https://developer.wordpress.org/block-editor/how-to-guides/metabox/

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ryanwelcher** [comment]
Thanks for creating this issue! I did a little digging here is this is an issue with how the docs are being generated. I'm putting together a PR now to see if we can get this fixed.
