### ISSUE TITLE
Query Loop: Show design options in the Inspector

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#63492]
When you select a template part design options are presented in the Inspector:

<img width="281" alt="Screenshot 2024-07-12 at 17 11 00" src="https://github.com/user-attachments/assets/6bc61891-98a8-4893-81c9-d89ffb02ba00">

It would be neat to bring this to the Query Loop block as an alternative to the shuffle button.

**Comment by richtabor** [comment]
Related https://github.com/WordPress/gutenberg/issues/63497

**Comment by richtabor** [comment]
I’m actually going to close this in favor of https://github.com/WordPress/gutenberg/issues/63497 as its more detailed.
