### ISSUE TITLE
Add a mechanism to Heading blocks that allows you to control the available levels

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#63527]
The heading level dropdown in the Heading block is powered by the [HeadingLevelDropdown](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/block-heading-level-dropdown) component. This component accepts and `options` parameter that allows you to choose which levels are available in the dropdown. Unfortunately, there is no way to modify this `options` parameter from a Heading block. 

Being able to modify the available levels is critical for heavily curated editing environments and block "governance".

Consider the following situations:

- You only want to allow `h2`, `h3`, and `h4` in Media & Text blocks.
- You want to disable `h1` on posts since the template already populates an `h1` for the post title.
- You want to disable the usage of `h5` and `h6` across the whole site.
- etc.

Curating the available heading levels is currently not possible, but it should be easy to implement using an additional attribute for the Heading block. Developers can then modify this attribute as they need, either directly in theme patterns and templates or via block filters like `blocks.registerBlockType` or `register_block_type_args`. 

| Current functionality | Goal | 
|-|-|
|<img width="587" alt="image" src="https://github.com/user-attachments/assets/f75fef6f-c002-4a3b-93c8-ca81cfca06e5">|<img width="587" alt="image" src="https://github.com/user-attachments/assets/d8a358d7-ebe6-44b0-b378-133320d03f6a">|

Should the mechanism be added to Heading blocks, we should explore similar mechanisms for other blocks with level dropdowns, like Site Title, Post Title, etc.

**Comment by ndiego** [comment]
cc @troychaplin @ryanwelcher

**Comment by troychaplin** [comment]
Thanks for adding this issue @ndiego, this would be a fantastic addition to blocks. Allowing users to freely use H1 in the content area create inaccessible content. Best practices state that only 1 unique H1 should be used on the page, preferably placed above the main content, aka the page title. Outside of a11y concerns, more than one H1 on a page can also have a negative impact on SEO.

IMO the heading block should never allow an H1 to be used in the content area, but that's rather heavy handed so at a minimum, an option to remove it would be amazing!

**Comment by skorasaurus** [comment]
@ndiego Thanks for the clear writeup although this request seems to be covered pretty well under https://github.com/WordPress/gutenberg/issues/20213.
