### ISSUE TITLE
gutenberg_style_engine_get_stylesheet_from_context

### ISSUE THREAD

**Issue by Pixelous** [WordPress/gutenberg#63536]
### Description

Hi,

Looks `gutenberg_style_engine_get_stylesheet_from_context` function is not working however `wp_style_engine_get_stylesheet_from_context` is working fine.

Can you take a look please?

Kind regards

### Step-by-step reproduction instructions

1.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Thanks for reporting the issue, @Pixelous!

Can you share more details on what exactly isn't working? Also, what is the reason for using `gutenberg_style_engine_get_stylesheet_from_context` instead of `wp_style_engine_get_stylesheet_from_context`?

The `gutenberg_` is a plugin-specific prefix, and you should avoid using it in your projects when possible. Instead, prefer a method that ships with WP, like `wp_style_engine_get_stylesheet_from_context`.

**Comment by Pixelous** [comment]
@Mamaduka hi, sorry for not providing more details.

Ok, I am trying to use `wp_style_engine_get_stylesheet_from_css_rules` function https://developer.wordpress.org/reference/functions/wp_style_engine_get_stylesheet_from_css_rules/ https://developer.wordpress.org/block-editor/reference-guides/packages/packages-style-engine/#wp_style_engine_get_stylesheet_from_css_rules to load CSS in the head tag.

I try to replicate the native gallery block as my custom block https://github.com/WordPress/gutenberg/blob/75b44e7d8a301de0cb46fca9a4479ddad97357df/packages/block-library/src/gallery/index.php#L117

It is not working( any thoughts?)

**Comment by Mamaduka** [comment]
@Pixelous, can you share the code you're using? It helps with reproducing the issue.

**Comment by Pixelous** [comment]
@Mamaduka 
[megatheme-blocks.zip](https://github.com/user-attachments/files/16286917/megatheme-blocks.zip)
please see attached zip plugin. I am trying to replicate Gutenberg gallery block to use it as a staring point for my custom block.

```
wp_style_engine_get_stylesheet_from_css_rules(
		$gallery_styles,
		array(
			'context' => 'block-test',
		)
	);
```

in **megatheme-blocks.php** on lines **145-150**.

`wp_style_engine_get_stylesheet_from_css_rules` should insert style tag in sites head, correct? (not the editor but front end page).

The block is **Tiled Gallery** in **Media** category.

**Comment by Mamaduka** [comment]
@ramonjd, any thoughts on why this might not be working?

**Comment by ramonjd** [comment]
Thanks for the ping @Mamaduka and hi 👋🏻 @Pixelous 

> to load CSS in the head tag.

I checked out the attached theme, and the code looks good, however the styles need to be registered and enqueued.

WordPress is currently set up to only load Core `block-supports` styles registered in this way. 

See this line:

https://github.com/WordPress/wordpress-develop/blob/0a12ad2890ec258febb4b65e3840e94008a99cbe/src/wp-includes/script-loader.php#L3152

That means, at least for now, users can't store styles in a different context and expect them to print automatically in the head.

You can however register and enqueue your own stylesheet. 

The style engine docs [contain an explanation and a code example](https://github.com/WordPress/gutenberg/blob/trunk/packages/style-engine/README.md#wp_style_engine_get_stylesheet_from_context). 

I think there was talk of adding a hook here to allow plugin developers to add their own context to this array for convenience, however, I'd recommend registering and enqueuing your own stylesheet: you'll have greater control about what you're loading and won't have to update anything if `wp_enqueue_stored_styles` changes for whatever reason.

I hope that helps!

I'll close this issue as there's no fix.

If you have ideas for improvement, please [create an issue](https://github.com/WordPress/gutenberg/issues/new/choose) so it's on record. 

Thank you!
