### ISSUE TITLE
Anchor for blocks with `save` that doesn't support an `id` prop

### ISSUE THREAD

**Issue by nb** [WordPress/gutenberg#6356]
## Issue Overview

[Anchor support](https://wordpress.org/gutenberg/handbook/block-api/#supports-optional) works by adding an `id` prop to the `save` component during serialization. Unfortunately this doesn't always result in an `id` attribute in the final HTML as promised by the documentation. For example if we provide a custom React component that doesn't pass the `id` prop to the generic HTML components or if we return a list of components.

## Steps to Reproduce

1. Create a block where the `save` method returns a React component that doesn't do anything meaningful with its `id` prop.
2. Add `supports: { anchor: true }`
3. Edit the anchor in the inspector UI and set it to `baba`.
4. Save.

## Expected Behavior
The block would receive an `id="baba"` attribute, but it does not.

## Possible Solution

I don't see a general solution, but updating the documentation to tell block authors that they should handle either the `id` prop or the `anchor` attribute (do we need both?) in the return values of their `save` methods.

**Comment by aduth** [comment]
Related: `wp.element.RawHTML` suffers from a similar issue in that it is intended to be used for unwrapped elements, yet with supports we anticipate that props may be passed. When there are, the output is automatically wrapped with a `div` element:

https://github.com/WordPress/gutenberg/blob/d96d79b3dadf87ef38338fb82877570a0fae5ab6/element/index.js#L194-L211

https://github.com/WordPress/gutenberg/blob/d96d79b3dadf87ef38338fb82877570a0fae5ab6/element/serialize.js#L365-L375

**Comment by designsimply** [comment]
Attempted a PR, but it's quite possible I didn't get the documentation right and may need a hand. 😊

**Comment by benlk** [comment]
For blocks that have a save function that returns null, because [the block's rendering is handled serverside[(https://gist.github.com/pento/cf38fd73ce0f13fcf0f0ae7d6c4b685d#file-php-block-js-L56-L59) or because the block is [a dynamic block](https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/), how is the `id` attribute meant to be accessed?

**Comment by aduth** [comment]
@benlk For the moment you'll need to artificially add the `anchor` attribute definition to your block as defined in the server, imitating what's otherwise added by the hook in the client here:

https://github.com/WordPress/gutenberg/blob/735ab8da26341629a1c032ad307b55eef021f6dd/packages/editor/src/hooks/anchor.js#L39-L46

Adding this attribute definition to your block on the server should make the attribute `anchor` ID value available in the `$attributes` argument of the `render_callback`, which you can add to your block's returned render value.

Related: #2751

**Comment by benlk** [comment]
I must be doing something wrong here, because with the following markup in post_content:

```html
<!-- wp:pym-shortcode/pym {"src":"http://blog.apps.npr.org/pym.js/examples/graphic/child.html","className":"chicken"} -->
<a href="http://blog.apps.npr.org/pym.js/examples/graphic/child.html" id="html-anchor-test" class="wp-block-pym-shortcode-pym chicken">http://blog.apps.npr.org/pym.js/examples/graphic/child.html</a>
<!-- /wp:pym-shortcode/pym -->
```

in block.php: 

```php
<?php
/**
 * The Gutenberg block for Pym.js embeds
 *
 * @package pym-embeds
 */

/**
 * Registers all block assets so that they can be enqueued through Gutenberg in
 * the corresponding context.
 *
 * @see https://wordpress.org/gutenberg/handbook/blocks/writing-your-first-block-type/#enqueuing-block-scripts
 */
function pym_block_init() {
	$dir = dirname( dirname( __FILE__ ) );

	$block_js = 'js/block.js';
	wp_register_script(
		'pym-block-editor',
		plugins_url( $block_js, dirname( __FILE__ ) ),
		array(
			'wp-blocks',
			'wp-i18n',
			'wp-element',
		),
		filemtime( "$dir/$block_js" )
	);

	$editor_css = 'css/editor.css';
	wp_register_style(
		'pym-block-editor',
		plugins_url( $editor_css, dirname( __FILE__ ) ),
		array(
			'wp-blocks',
		),
		filemtime( "$dir/$editor_css" )
	);

	register_block_type( 'pym-shortcode/pym', array(
		'attributes'    => array(
			'src' => array(
				'type' => 'string',
			),
			'pymsrc' => array(
				'type' => 'string',
			),
			'pymoptions' => array(
				'type' => 'string',
			),
			'id' => array(
				'type' => 'string',
				'source' => 'attribute',
				'attribute' => 'id',
				'selector' => '*',
			),
			'anchor' => array(
				'type' => 'string',
				'source' => 'attribute',
				'attribute' => 'id',
				'selector' => '*',
			),
			'className' => array(
				'type' => 'string',
			),
			'align' => array(
				'type' => 'string',
			),
		),
		'editor_script'   => 'pym-block-editor',
		'editor_style'    => 'pym-block-editor',
		'style'           => 'pym-block',
		'render_callback' => 'pym_shortcode',
	) );
}
add_action( 'init', 'pym_block_init' );
```

and with `anchor: true` in `supports`, what gets passed to the callback is:

```php
array (
  'src' => 'http://blog.apps.npr.org/pym.js/examples/graphic/child.html',
  'pymsrc' => NULL,
  'pymoptions' => NULL,
  'id' => NULL,
  'anchor' => NULL,
  'className' => 'chicken',
  'align' => NULL,
)
```
Branch containing this code is https://github.com/INN/pym-shortcode/tree/35-anchor-redux

**Comment by okadots** [comment]
@benlk did you ever figure this out? I cannot figure this out at all and it's making me crazy. The docs for this anchor tag are essentially non-existent.

**Comment by benlk** [comment]
@okadots I did not; but I also have not investigated this problem since my last comment on this thread. Gutenberg may have changed in the last several months to allow the techniques attempted here to work.

**Comment by niklasp** [comment]
i just stumbled upon this issue. cannot get it solved with dynamic blocks. that return null

**Comment by langhenet** [comment]
> i just stumbled upon this issue. cannot get it solved with dynamic blocks. that return `null` in the block's `save` function

Yeah, me too
