### ISSUE TITLE
Wanted: docs on how to parse blocks on front-end

### ISSUE THREAD

**Issue by ms-studio** [WordPress/gutenberg#6358]
I have been looking through [the Gutenberg handbook](https://wordpress.org/gutenberg/handbook/) for some information on how Gutenberg blocks can be parsed (addressed programmatically) on the frontend. I find plenty of information on how to declare block types, but hardly anything on how to play with blocks on a theme's frontend.

Let's imagine that a theme author wants to do the following: "test if the post contains a gallery. If it's the case, display it, otherwise display the first block (whatever it is)". 

Is there an "official WordPress way" of parsing the content of the post? Something like WP_Query, but on block level?

**Comment by Soean** [comment]
We should add examples of these PHP functions to the handbook

**Comment by ms-studio** [comment]
Thanks @Soean , I was hoping exactly for that !

**Comment by mrwweb** [comment]
It seems odd that you can parse `the_content` into an array of blocks with `gutenberg_parse_blocks` but there's no way to take the array and turn it into content without looping through and rendering each block with `gutenberg_render_block`. Is there no `gutenberg_render_blocks` (plural!) that takes an array?

**Comment by ayoub-bousetta** [comment]
parse_blocks() for the new version

**Comment by gtamborero** [comment]
Actually the PEG parser is inside WordPress 5, you can use it this way:

$blocks = parse_blocks(get_the_content());

foreach ($blocks as $block){
//block data
var_dump($block);
}

**Comment by mtias** [comment]
Looks like this has initial documentation.
