### ISSUE TITLE
Pullquote: Background image & colors enhancements

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#636]
A few enhancements that we tabled for the pullquote block, wanted to capture here so they don't get left behind. See initial pullquote issue #547 and PR #607 

* set background image
* set background color in a way that can match the theme colors (would be nice if the theme could provide an array of colors)

**Comment by jasmussen** [comment]
Split out the most pertinent ones in #1221 amd #1222.

**Comment by jasmussen** [comment]
Closing this as the pullquote has changed purposes, and we are looking at adding color and background options to the text block instead. See #2452
