### ISSUE TITLE
Make vertical toolbar sticky when scrolling while zoomed out

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#63619]
Much like the standard block toolbar when you're not in zoom out mode, I expected the toolbar in zoom out to stick to the top while the current pattern is selected and in view. 

https://github.com/user-attachments/assets/522b4834-e871-4f9c-bdd2-b195d33c2899

**Comment by stokesman** [comment]
It’s odd, I thought I had seen this working and in the original PR it was noted that it was working https://github.com/WordPress/gutenberg/pull/60123#issuecomment-2175878482. So I checked out the merge commit 6dfaf0de95 and found it not working there either. Maybe before merge one of the later commits regressed it. Anyway, I’ll go ahead point out that it does work in #63390.

**Comment by richtabor** [comment]
> Anyway, I’ll go ahead point out that it does work in https://github.com/WordPress/gutenberg/pull/63390.

Ok thanks, I'm taking a look at that today.

**Comment by stokesman** [comment]
I noticed that on trunk this actually is working, just not on the first block.

https://github.com/user-attachments/assets/58a7a6fd-a25e-4add-adb8-c1ba293abffd

**Comment by scruffian** [comment]
This was fixed by https://github.com/WordPress/gutenberg/pull/63745
