### ISSUE TITLE
Content panel shouldn't surface blocks inside the 'Content' block

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#63613]
When editing a page, the Content panel surfaces the sections of the document that can be directly manipulated. My understanding is that it does this by looping through the document looking for instances of specific blocks; Title, Featured Image, and Content. When found they are listed in the panel for easy selection:

<img width="310" alt="Screenshot 2024-07-16 at 13 54 32" src="https://github.com/user-attachments/assets/69822476-7e21-4aa2-a4a4-b3300a6f3768">

However, if the Content block _also_ contains instances of these blocks – for instance if there's a custom query in the page content – then those blocks are repeated:

For a number of reasons this makes for a strange UX:

* There's no benefit to highlighting nested featured images, titles, etc because as properties of separate entities they cannot be edited
* It's not clear which is the document-level version of the block
* They add weight to the Content panel, diluting its usefulness
* Selecting a nested block creates a confusing UI where both the block and the parent appear to be selected

<img width="2005" alt="Screenshot 2024-07-16 at 13 57 27" src="https://github.com/user-attachments/assets/7de5641c-f27f-4a82-99e1-e711db938925">

### Solution
It would seem sensible to omit these blocks in the Content panel when they are nested within the Content block.

cc @noisysocks as (iirc) you worked on this feature.

**Comment by Mamaduka** [comment]
I think I've seen a similar issue before, but my keyword search is failing me at the moment 😞

**Comment by jameskoster** [comment]
Same, I couldn't find it either 🥲

@annezazu might know. 

Feel free to close this if it's duplicative.

**Comment by annezazu** [comment]
I can't find a related issue and I think this is a good iteration on the original problem outlined in https://github.com/WordPress/gutenberg/issues/55025 I think this PR implemented what's being discussed here as well: https://github.com/WordPress/gutenberg/pull/57901

**Comment by noisysocks** [comment]
Vaguely remember fixing this at one point. Must have subsequently un-fixed it 🙂 Will open a PR.
