### ISSUE TITLE
It should only be possible to edit the description of $custom templates

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#63659]
Currently it's possible to edit descriptions for non-$custom templates when created by users. For instance see the Blog Home template here:

<img width="280" alt="Screenshot 2024-07-17 at 13 30 56" src="https://github.com/user-attachments/assets/7be18501-6fd0-48a7-bad3-12945650b710">

cc @ntsekouras as I think you worked on this recently.

**Comment by ntsekouras** [comment]
I thought this was handled... I'll take a look.
