### ISSUE TITLE
Entity Actions: Error when duplicating template parts in editor

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#63655]
If you try to duplicate a template part, the side editor crashes. The duplication action works correctly for DataViews.

## Steps to reproduce
1. Open the Site Editor.
2. Open any template part.
3. Try duplicating it from Document Settings actions.

## Screenshot
![CleanShot 2024-07-17 at 15 25 07](https://github.com/user-attachments/assets/8048398d-9e98-4e92-a15e-8e4d8f2c1727)

**Comment by Rishit30G** [comment]
Hey @Mamaduka!
I tried to reproduce the issue, but I couldn't find the errors in my console nor did the editor crash for me 
Please let me know if it was the correct way to reproduce the issue 
Thanks

https://github.com/user-attachments/assets/351a86b7-9012-477b-8b4f-00c704278af3

**Comment by Mamaduka** [comment]
@Rishit30G, as I noted in the description, the duplication action works in DataViews (action in your screencast). Try duplicating the template part from the sidebar when viewing it.

## Screenshot
![CleanShot 2024-07-17 at 15 54 44](https://github.com/user-attachments/assets/db141e90-3535-496a-97af-8adeac427830)

**Comment by Rishit30G** [comment]
@Mamaduka, thanks for the clarification! 🙇 
Got it, I tried it through sidebar as well, it's working fine for me 

https://github.com/user-attachments/assets/65471c86-996e-42c1-aa40-5d641a0b293f

**Comment by Mamaduka** [comment]
@Rishit30G, are you testing with the latest Gutenberg versions?

In any case, I prepared the fix for the bug - #63663.
