### ISSUE TITLE
Provide a way to set the homepage in the site editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#63666]
Currently to change the homepage you have to exit the site editor and navigate to reading settings which is quite disruptive. 

A simple / lightweight method for setting the homepage in the site editor could be a nice enhancement.

### Utilise the page actions menu

In both data views and the page Inspector there is an actions menu which could house a shortcut to set the homepage.

<img width="1888" alt="homepage" src="https://github.com/user-attachments/assets/2b1515a8-0780-46a5-9f77-3b6b575c1539">

Related: https://github.com/WordPress/gutenberg/issues/20338

**Comment by jasmussen** [comment]
This seems like a fairly straight-forward way to do it. I'd assume, per the separate issue we have for this, that this menu item would also be available in the ⌘K command palette? What happens when you press "Confirm", does the document get marked as "dirty", and you can then actually confirm the change in the multi-entity saving flow? What might that look like?

**Comment by jameskoster** [comment]
> I'd assume, per the separate issue we have for this, that this menu item would also be available in the ⌘K command palette?

This is a bit of a tangent, but I'd expect to see this menu alongside shortcuts to other recently edited pages. We need better organisation in the command palette UI to achieve this. Here's an original mockup from way back:

<img width="902" alt="Screenshot 2024-08-28 at 15 37 00" src="https://github.com/user-attachments/assets/3ba47fa9-02ff-4fdb-8fc5-2e05093931df">

> What happens when you press "Confirm"

That's a good question. The other actions in this menu are applied instantly, so I'd probably expect the same for this one.

**Comment by jasmussen** [comment]
> The other actions in this menu are applied instantly, so I'd probably expect the same for this one.

Setting a homepage feels a bit like setting a site logo, which does not happen instantly. But perhaps the name can be different from "Confirm"?

**Comment by jameskoster** [comment]
Yup, it's not a strong feeling. I don't mind storing as a pending change.

> But perhaps the name can be different from "Confirm"?

There is a growing tendency for the button label in such dialogs to echo the action. For instance in the "Move to trash" dialog the primary button is "Trash". Following that convention would give us something like "Set homepage" here, which seems a little long, but might work? 

It would be good to define this detail more concretely in the systems work cc @mattrwalker.

**Comment by mtias** [comment]
While a bit hidden, it seems better than completely absent :)

**Comment by creativecoder** [comment]
Note that there's a draft PR for this here: https://github.com/WordPress/gutenberg/pull/65426

**Comment by jasmussen** [comment]
Since this is a good improvement, since it's in progress already, removing the feedback label.
