### ISSUE TITLE
[theme.json v3] core presets override theme supplied ones

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#63677]
### Description

Using theme.json v3, the core font size and spacing presets override the theme supplied ones if the slugs of the presets match. Is this a bug, or expected behavior with v3? 

My expectation is that the core and theme presets should be merged, with the theme's taking precedence if the slugs match.

This might happen with other presets too, but I've just noticed font size and spacing for now. Encountered this issue upon upgrade to 6.6, which caused some visual regressions on some live sites I'm helping with.

Nothing that if `defaultFontSizes` and `defaultSpacingSizes` are set to `false`, then only the theme presets should appear, and this is working as expected. 

### Step-by-step reproduction instructions

1. Activate twentytwentyfour 
2. Edit the theme.json version to `3`
3. Verify the core presets override the theme's

### Screenshots, screen recording, code snippet

theme.json v2 | theme.json v3
--- | ---
![Screenshot 2024-07-17 at 1 16 35 PM](https://github.com/user-attachments/assets/48e6d3b1-025b-4731-820d-22446e417978) | ![Screenshot 2024-07-17 at 1 16 21 PM](https://github.com/user-attachments/assets/9f4f35a4-343d-4221-89f0-c7c2a9dbc2a5)

### Environment info

- WP 6.6, Gutenberg 18.8.0
- theme.json v3

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by ajlende** [comment]
> Using theme.json v3, the core font size and spacing presets override the theme supplied ones if the slugs of the presets match. Is this a bug, or expected behavior with v3?

This is the expected behavior, and the reason for having to bump the theme.json version.

> This might happen with other presets too, but I've just noticed font size and spacing for now.

This is the behavior that all other presets have always had if you don't specify `"default{option}": false`.

Check the [migration guide](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-migrations/#migrating-from-v2-to-v3) for details on how to keep the old behavior when switching to version 3.

Additionally you may want to check out the [theme.json v3 FAQ](https://make.wordpress.org/themes/2024/06/21/theme-json-version-3-frequently-asked-questions/) or the [theme.json v3 dev note](https://make.wordpress.org/core/2024/06/19/theme-json-version-3/) for more common questions.

> ## Migrating from v2 to v3
> 
> Upgrading to v3 adjusts preset defaults to be more consistent with one another.
> 
> ### How to migrate from v2 to v3:
> 
> 1. Update `version` to `3`.
> 2. Configure the changed defaults (see below).
> 
> ### Changed defaults
> 
> #### `settings.typography.defaultFontSizes`
> 
> In theme.json v2, the default font sizes were only shown when theme sizes were not defined. A theme providing font sizes with the same slugs as the defaults would always override them.
> 
> The default `fontSizes` slugs are: `small`, `medium`, `large`, `x-large`, and `xx-large`.
> 
> The new `defaultFontSizes` option gives control over showing default font sizes and preventing those defaults from being overridden.
> 
> - When set to `true` it will show the default font sizes and prevent them from being overridden by the theme.
> - When set to `false` it will hide the default font sizes and allow the theme to use the default slugs.
> 
> It is `true` by default when switching to v3. This is to be consistent with how other `default*` options work such as `settings.color.defaultPalette`, but differs from the behavior in v2.
> 
> To keep behavior similar to v2 with a v3 theme.json:
> * If you do not have any `fontSizes` defined, `defaultFontSizes` can be left out or set to `true`.
> * If you have some `fontSizes` defined, set `defaultFontSizes` to `false`.
> 
> #### `settings.spacing.defaultSpacingSizes`
> 
> In theme.json v2, there are two settings that could be used to set theme level spacing sizes: `settings.spacing.spacingSizes` and `settings.spacing.spacingScale`. Setting both `spacingSizes` _and_ `spacingScale` would only use the values from `spacingSizes`. And setting either of them would always replace the entire set of default spacing sizes provided by WordPress.
> 
> The default `spacingSizes` slugs provided by WordPress are: `20`, `30`, `40`, `50`, `60`, `70`, and `80`.
> 
> The new `defaultSpacingSizes` option gives control over showing default spacing sizes and preventing those defaults from being overridden.
> 
> - When set to `true` it will show the default spacing sizes and prevent them from being overridden by the theme.
> - When set to `false` it will hide the default spacing sizes and allow the theme to use the default slugs.
> 
> `defaultSpacingSizes` is `true` by default when switching to v3. This is to be consistent with how other `default*` options work such as `settings.color.defaultPalette`, but differs from the behavior in v2.
> 
> Additionally, in v3 both `spacingSizes` and `spacingScale` can be set at the same time. Presets defined in `spacingSizes` with slugs matching the generated presets from `spacingSizes` will override the generated ones.
> 
> To keep behavior similar to v2 with a v3 theme.json:
> * If you do not have any `spacingSizes` presets or `spacingScale` config defined, `defaultSpacingSizes` can be left out or set to `true`.
> * If you disabled default spacing sizes by setting `spacingScale` to `{ "steps": 0 }`, remove the `spacingScale` config and set `defaultSpacingSizes` to `false`.
> * If you defined only one of either `spacingScale` or `spacingSizes` for your presets, set `defaultSpacingSizes` to `false`.
> * If you defined both `spacingScale` and `spacingSizes`, remove the `spacingSizes` config _and_ set `defaultSpacingSizes` to `false`.

**Comment by jffng** [comment]
I hadn't seen the dev note, thanks for the explanation @ajlende !
