### ISSUE TITLE
Can't select zoom out section with keyboard

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#63680]
### Description

Entering into zoom out mode clears the block selection and places it on the root wrapper. Keyboard users don't have a way to access a section to show the zoom out tools or inserters.

Proposed fix:
- When entering into zoom out mode, don't select the root wrapping element. Instead:
- If no block is selected, select the first section
- If there is a block selection, select the parent section of the current block selection to keep the context close by

### Step-by-step reproduction instructions

- Open the main inserter
- Tab to the Patterns tab
- Press Enter
- Tab to a pattern category
- Press enter to go into zoom out mode
- Tab past the category panel until you see a blue outline around the entire canvas
- There is no way to access an individual section to show the zoom out toolbar
- If you have access to a mouse, click a section to see the zoom out toolbar and selection outline

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by draganescu** [comment]
This does not appear to be an issue since the focus now remains on the toggle and zoom out is not triggered by the pattern inserter anymore.
