### ISSUE TITLE
Tabbing to zoom out canvas retriggers scaling animation

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#63681]
### Description

When using the tab key to move focus from the pattern inserter sidebar to the canvas, the scaling animation retriggers when focus is moved to the canvas.

### Step-by-step reproduction instructions

- Open the main inserter
- Tab to the Patterns tab
- Press Enter
- Tab to a pattern category
- Press enter to go into zoom out mode
- Tab past the category panel until you see the animation retrigger

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/47ad722e-5c3a-43a4-9480-1b1a5ef5909e

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by draganescu** [comment]
This does not happen anymore fore me. Also the zoom out is no longer engange automatically on pattern categoryt open.
