### ISSUE TITLE
When adding a link to text, the dialog stays view-able after clicking return

### ISSUE THREAD

**Issue by gravnetic** [WordPress/gutenberg#6370]
I used a return after entering the URL, selecting more options, and setting the toggle to new tab.

Further,  It seems like the toggle could be a verticle and shown inline with the apply button.

Finally, I did enter the URL into the text field and continued without an apply or return twice expecting it would just drop in like Wordpress current behavior.

**Comment by danielbachhuber** [comment]
Thanks for the report, @gravnetic.

Here's a GIF of the current behavior in Gutenberg:

![linkgutenberg](https://user-images.githubusercontent.com/36432/41979839-d9271e08-79d9-11e8-9d4b-153a2e858795.gif)

Notice that the preview dialog appears after the first `return`, and then the link disappears entirely after the second `return`.

The current behavior in Gutenberg replicates the existing behavior in the Classic Editor:

![linkclassic](https://user-images.githubusercontent.com/36432/41979924-16414bce-79da-11e8-882a-4b8efb804495.gif)

Given Gutenberg's behavior matches the Classic Editor's behavior, I'm going to close this as `wontfix`. Please re-open with additional details if you feel there's behavior we need to change.
