### ISSUE TITLE
Quoteblock in 6.6 is missing the <cite> tag

### ISSUE THREAD

**Issue by jan-vandenberg** [WordPress/gutenberg#63729]
### Description

Previous use of the quoteblock (<6.6) had a way to add a name/attribution for a quote. 

By looking at older posts I notice these (old) blocks are of the blockquote class that exists of both a <p> element (the quote) and a <cite> element (the attribution.

It seems this has disappeared in 6.6? It is just a <p> element. There is no way to add a <cite> element from the editor.

### Step-by-step reproduction instructions

1. Add a quote block
2. Try to add an attribution/name i.e. <cite> element

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by talldan** [comment]
@jan-vandenberg There should be a button on the toolbar of the quote block to add the citation:
![Screenshot 2024-07-19 at 1 25 59 PM](https://github.com/user-attachments/assets/e782f440-727a-4937-8eaa-826fe209352f)

One thing to note is that you'll have to make sure you have the quote block selected, as quite often you'll have the paragraph block within the quote block selected (this catches me out)

**Comment by jan-vandenberg** [comment]
Aaah, that is it! A little bit less intuitive (I used to add an enter and get the citation option), but this works fine.  Thanks.
