### ISSUE TITLE
Buttons Block : Add Hover Colour Settings in Buttons

### ISSUE THREAD

**Issue by pitamdey** [WordPress/gutenberg#63736]
## What problem does this address?

I am not able to add a different Hover background or colour in the Button.
Is it possible to do that using block inspector, without adding custom CSS or plugin?

## What is your proposed solution?

I think we should add one section for Hover colour settings also in the blocks

**Comment by carolinan** [comment]
Hi
This feature is already been discussed in this issue: https://github.com/WordPress/gutenberg/issues/38277

**Comment by pitamdey** [comment]
Thanks @carolinan
