### ISSUE TITLE
Restore Document Tab when creating a new post/page

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#6377]
Recently a change was made to automatically select the "Block" tab of the sidebar whenever a block is selected, and then select the document tab when you deselect a block. However if the block tab is selected when you press "Add New", the Document tab isn't restored.

Steps to reproduce:

- Create a new post
- Insert a block, select it, verify the block tab is active
- Click "Add New" in the navigation sidebar to create a new post

Result: the block tab is still selected, but empty. It should show the document tab, since you don't have a block selected.

**Comment by aduth** [comment]
Regressed in recent refactoring toward state persistence. I'll look at reimplementing, likely as suggested by @youknowriad in just not persisting the active general sidebar state.
