### ISSUE TITLE
<dfn>...</dfn> Created by Editing a Block as HTML Lost upon Save and Reload

### ISSUE THREAD

**Issue by ElizabethHudnott** [WordPress/gutenberg#63770]
### What Happens
The editor appears to understand <dfn> tags correctly while editing, since they're formatted correctly. But they disappear after saving and refreshing the page (as in the tags are stripped out) and for no seemingly good reason, since they don't represent any potential security issue.

### Expected Result
Any valid client side code except for JavaScript, <style>, <link>, forms, frames, <object> or <embed> should be left intact on all plans and saved exactly as written.

### Step-by-step reproduction instructions

1. Create a new draft post.
2. Go to the initial paragraph, click on the hamburger menu icon in the floating formatting toolbar and choose "Edit as HTML".
3. Edit the HTML code so that it reads `<p><dfn>Foo</dfn> is a bar.</p>`
4. Click on "Save draft" and wait for it to finish saving.
5. Click on the browser's refresh button.

### Environment info

- WordPress version: wordpress.com
- Browser: Chrome 126.0.6478.128
- OS: Windows 10 on desktop

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Thanks for the report, but I was not able to reproduce the problem.

The `dfn` tag is allowed [by default](https://github.com/WordPress/wordpress-develop/blob/68b23387d752493e79f0a35190a8d495feb49b67/src/wp-includes/kses.php#L142), so any user should be able to save HTML with it.

But it seems that the tag is indeed removed on sites **hosted on wordpress.com**. So it might be a good idea to report this issue to [WordPress.com support](https://wordpress.com/support/).

I would like to close this issue as it is not a problem with the Gutenberg plugin.
