### ISSUE TITLE
Discussion in the side menu did not receive translation

### ISSUE THREAD

**Issue by maisondasilva** [WordPress/gutenberg#63780]
### Description

Discussion in the side menu did not receive translation, I noticed this in my pt-BR language, I believe other languages ​​may be affected

### Step-by-step reproduction instructions

![image](https://github.com/user-attachments/assets/777801ce-c715-439d-ab7b-d71ecd47ee6f)

### Environment info

WordPress 6.6

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by talldan** [comment]
The strings are all internationalized, and it's translated in other languages (I checked French), so it seems like there's missing translations:
https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-comments/index.js

The one issue in the internationalization I can see is that there's no distinction between the verb (e.g. 'to open') and the adjective (e.g. 'is open'), so translators might get that wrong, which I can follow up and fix.

In terms of the missing translations, this wouldn't be the place to report that kind of issue. I don't think there is a place to report it, I believe the untranslated strings will be on a list awaiting translation and I can see others that are untranslated for pt_BR in the UI, so the translation doesn't seem to be 100%. You could reach out to the [polyglots team in slack](https://wordpress.slack.com/archives/C02RP50LK). There's some information about the Portuguese Brazilian team here - https://make.wordpress.org/polyglots/teams/?locale=pt_BR.
