### ISSUE TITLE
Block displaying data with withAPIData only if window width below 782px

### ISSUE THREAD

**Issue by TinBoyko** [WordPress/gutenberg#6379]
## Issue Overview

You can follow this [example](https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/) from Gutenberg handbook.
After post edit page reload,  block not displaying fetched data from API if window width bigger than 782px and get stuck in loading state. In safari if i go back to pages and open this page again data is appeared. I noticed that if window width > 782px edit method of wp.blocks.registerBlockType is called twice.

## Steps to Reproduce (for bugs)

1. Create block with HOC withAPIData ([example](https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/))
2. Add this block in editor
3. Save post
4. Reload page

Chrome, Firefox, Safari

**Comment by keesiemeijer** [comment]
I've got a similar issue with the Latest Posts block provided by Gutenberg (2.7 and 2.6). 

## Steps to Reproduce
1. Add three latest posts blocks
2. Change the "Order by" setting for the middle one
3. Publish the post
4. Refresh the page

Now the middle latest post block is stuck in loading state. Gutenberg 2.5 doesn't have this issue. I couldn't confirm if window width below 782px fixes this issue.

Tested in Firefox 59.02
