### ISSUE TITLE
Add Block: Twitter Embed

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#638]
Looking at a Twitter embed block. I've mocked up a few states for this, and wanted to open this up for discussion. 

**Empty Block:**
Need an empty field to paste in the Twitter embed HTML.
![twitter-empty](https://cloud.githubusercontent.com/assets/617986/25681864/c08ffc76-300a-11e7-98e8-167f43442907.png)

**Neutral:**
I imagine the styling would be structured similarly to the blockquote styling.
![twitter-neutral](https://cloud.githubusercontent.com/assets/617986/25681870/c6155ca4-300a-11e7-8843-b7440d39efb2.png)

**Hover:**
![twitter-hover](https://cloud.githubusercontent.com/assets/617986/25681873/c97ad23e-300a-11e7-8209-9914d801b649.png)

**Selected:**
When selected the switcher would reveal it as a Twitter embed and not a blockquote. The 'edit' button would be to allow the user to click back to the 'empty' state to edit the HTML embed code or update it.
![twitter-selected](https://cloud.githubusercontent.com/assets/617986/25681877/cc015578-300a-11e7-9201-1b6bacddc353.png)

**Comment by jasmussen** [comment]
Nice work. 

Should we maybe pull it back a bit, though? I think we can just make a thin shell wrapper for the existing oembed feature. That would essentially only require a URL to the tweet in the wrapper, and we just let Twitter show us their standard embed stuff inside an iframe, like this:

<img width="532" alt="screen shot 2017-05-04 at 10 03 06" src="https://cloud.githubusercontent.com/assets/1204802/25694850/eec88260-30b0-11e7-87ea-ba3abb4beaa1.png">

**Comment by mapk** [comment]
I love the idea of just keeping the OG styling from Twitter (and any other embed for that matter). After some discussion, I also realized that our Editor doesn't need the embed code, but can just work from the URL itself. So I made some changes around that as well. 

Empty Selected UI
![twitter no-style-empty-selected](https://cloud.githubusercontent.com/assets/617986/25765047/c4ac31e4-319f-11e7-9e42-19270ab2c153.png)

Neutral
![twitter no-style-neutral](https://cloud.githubusercontent.com/assets/617986/25765055/cc922f94-319f-11e7-98ee-57a502361d7d.png)

Hover UI
![twitter no-style-hover](https://cloud.githubusercontent.com/assets/617986/25765059/d1b5be32-319f-11e7-860d-d33a6909ddfa.png)

Selected UI
![twitter no-style-selected](https://cloud.githubusercontent.com/assets/617986/25765062/d7defc7e-319f-11e7-8608-e164b5dd621c.png)

**Comment by jasmussen** [comment]
Looks great!

**Comment by kopepasah** [comment]
I agree that keeping the standard styles is the best option.

Going to pick up this ticket.

**Comment by youknowriad** [comment]
I thought @notnownikki was already working on this?

**Comment by notnownikki** [comment]
I am :)

**Comment by notnownikki** [comment]
I have it working from just the tweet URL, it used the Twitter embed API to fetch the html. I'm just working on sandboxing the returned html in the editor, and it's pretty much done

**Comment by kopepasah** [comment]
@notnownikki okay, sounds good. Reassigning.

**Comment by notnownikki** [comment]
The mockups here are appreciated :) I've been doing more API interaction code than UI work so far (there'll be a reusable <Sandbox> component for us to sandbox third party html in the editor) so the UI thinking here helps me a lot :)

**Comment by jasmussen** [comment]
I'm closing this in favor of #1034, and because the embed block as inspired by this is in!
