### ISSUE TITLE
Unable to use blocks.getBlockDefaultClassName without error

### ISSUE THREAD

**Issue by MarieComet** [WordPress/gutenberg#6380]
Gutenberg v 2.7.0
WordPress v 4.9.5

## Issue Overview
When I try to [add custom CSS class](https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#blocks-getblockdefaultclassname) with `blocks.getBlockDefaultClassName` to button block, saving post, I get an error after reloading post in admin.

## Steps to Reproduce (for bugs)
Add this code : 
```
// Our filter function
function setBlockCustomClassName( className, blockName ) {
    return blockName === 'core/button' ?
        className + ' btn btn-primary' :
        className;
}

// Adding the filter
wp.hooks.addFilter(
    'blocks.getBlockDefaultClassName',
    'my-plugin/set-block-custom-class-name',
    setBlockCustomClassName
);
```
In JS file, enqueued with : `enqueue_block_editor_assets` action
Add a "button" block, save post, and reload it (admin).

## Expected Behavior
Custom CSS class should append to native CSS class

## Current Behavior
CSS class are added, but I get an error after reloading post in admin : 
`Block validation: Expected attribute 'class' of value 'wp-block-button aligncenter', saw 'wp-block-button btn btn-primary'`
where `btn btn-primary` are CSS class I've added

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by gziolo** [comment]
Are you sure that this filter is applied properly before the editor has been initialized? That might be one of the reasons why you see it. I would double check it first.

**Comment by MarieComet** [comment]
Actually, I don't know, how can I check it ?
My JS file is enqueued with `enqueue_block_editor_assets`, maye that's not the good action ?

**Comment by gziolo** [comment]
> My JS file is enqueued with enqueue_block_editor_assets, maye that's not the good action ?

Technically this function should be used when registering blocks, in this case it should also work because it loads scripts and styles when Gutenberg is loaded. I would add a few `console.log` statements with some message to better understand the order of files loaded.

**Comment by Duende13** [comment]
Hi,
Any idea what it could be? I have the same problem, I used classnames to add more than one and it comes back from preview to edit with this error:
<div class="wp-block-cursobloqueswp-barra-herramientas-personalizada message-body">
    <p>sdfsdf</p>
</div>

Actual:

<div class="wp-block-cursobloqueswp-barra-herramientas-personalizada message-body alarma">
    <p>sdfsdf</p>
</div>

Gutenberg v 2.7.0
WordPress v 4.9.5

**Comment by gziolo** [comment]
By the way, there should be also only one class name generated as explained in docs:

> Generated HTML classes for blocks follow the wp-block-{name} nomenclature. This filter allows to provide an alternative class name.

Please also keep in mind, that it is expected to see this kind of validation error when the class name was changed after post got saved with the default class name. It is perfectly correct behavior because it has the old class name stored in the database so after this hook gets applied it detects change.
