### ISSUE TITLE
`contentOnly` locking and `allowedBlocks` is not respected in blocks without a `layout` attribute.

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#63820]
### Description

I just stumbled upon this. If you have a block with `"templateLock":"contentOnly"` set, the Editor will not respect this attribute if there is no `layout` attribute as well. This is very bizarre, and it is not clear why the two are tied together. Furthermore, it makes it impossible to create patterns that utilize `contentOnly` but have no layout constraint. 

**Edit:** I discovered that this issue also occurs when using the `allowedBlocks` attribute. Unless the block also has a `layout` attribute, the `allowedBlocks` restriction will not be implemented. 

### Step-by-step reproduction instructions

To replicate this issue, copy the following code into the Editor and see that content-only mode is enabled. 

**Works**
```html
<!-- wp:group {"templateLock":"contentOnly","style":{"border":{"radius":"8px","width":"1px"},"spacing":{"blockGap":"0","padding":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|20","left":"var:preset|spacing|20","right":"var:preset|spacing|20"}}},"backgroundColor":"white","borderColor":"contrast-3","layout":{"type":"constrained"}} -->
<div class="wp-block-group has-border-color has-contrast-3-border-color has-white-background-color has-background" style="border-width:1px;border-radius:8px;padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--20);padding-bottom:var(--wp--preset--spacing--20);padding-left:var(--wp--preset--spacing--20)"><!-- wp:heading {"style":{"typography":{"fontStyle":"normal","fontWeight":"500","fontSize":"1.5rem"}},"fontFamily":"body"} -->
<h2 class="wp-block-heading has-body-font-family" style="font-size:1.5rem;font-style:normal;font-weight:500">Card heading</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size">Card description. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

Now copy this code into the Editor and see that the mode no longer works and the `"templateLock":"contentOnly"` gets stripped out if you toggle on the Layout option "Inner blocks use content width". 

**Doesn't work**
```html
<!-- wp:group {"templateLock":"contentOnly","style":{"border":{"radius":"8px","width":"1px"},"spacing":{"blockGap":"0","padding":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|20","left":"var:preset|spacing|20","right":"var:preset|spacing|20"}}},"backgroundColor":"white","borderColor":"contrast-3"} -->
<div class="wp-block-group has-border-color has-contrast-3-border-color has-white-background-color has-background" style="border-width:1px;border-radius:8px;padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--20);padding-bottom:var(--wp--preset--spacing--20);padding-left:var(--wp--preset--spacing--20)"><!-- wp:heading {"style":{"typography":{"fontStyle":"normal","fontWeight":"500","fontSize":"1.5rem"}},"fontFamily":"body"} -->
<h2 class="wp-block-heading has-body-font-family" style="font-size:1.5rem;font-style:normal;font-weight:500">Card heading</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size">Card description. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

cc @Mamaduka and @jorgefilipecosta as I know you both have worked on block locking and content only. 

### Screenshots, screen recording, code snippet

| With `layout` set | Without `layout` set |
|-|-|
|<img width="1047" alt="image" src="https://github.com/user-attachments/assets/4eef6365-3d05-40ec-9891-452f45a7a402">|<img width="1074" alt="image" src="https://github.com/user-attachments/assets/d200b657-1944-4bec-b95b-eb43a72d62d8">|

### Environment info

- WordPress 6.6
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by talldan** [comment]
There was a similar report of this a while back (I'll struggle to find it). I think it was due to the group block being invalid though, and a migration was stripping the `allowedBlocks` and `templateLock` attributes.

edit: found it - https://github.com/WordPress/gutenberg/pull/57544

**Comment by Mamaduka** [comment]
This looks similar to #49159, and it's due to layout deprecation introduced in #42763.

The problem:

* When the [default layout deprecation](https://github.com/WordPress/gutenberg/blob/d625b3d19d57e2cc165f4fa8c960e8f2667dce9a/packages/block-library/src/group/deprecated.js#L45-L56) was introduced. The group block had no support for `allowedBlocks` and `"templateLock" : "contentOnly"` attribute values, so they weren't listed when defining deprecation.
* The deprecation `isEligible` is true to a missing layout, and these attributes are discarded.

**Comment by talldan** [comment]
So same thing, but in this case the group block is valid. 😬 

I have an idea to fix it, but it feels a bit sketchy. I'll put together a PR.

**Comment by ndiego** [comment]
Thanks @talldan and @Mamaduka 🙏
