### ISSUE TITLE
Block styles registered with PHP don't show up in Styles > Block 

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#63838]
### Description

[This plain theme](https://github.com/bph/plain-pauli) had three block style variations:
two are registered by [functions.php](https://github.com/bph/plain-pauli/blob/main/functions.php) (purple and red border) one is registered via [/styles/image-blue-border.json](https://github.com/bph/plain-pauli/blob/main/styles/image-blue-border.json). 

All three show up next to the core variations default + rounded in the post editor as well as in the template editor. 

 In the Styles > Blocks > Image I only see the rounded variation and the blue variation. 

### Step-by-step reproduction instructions

- Add a block style to a theme via php in functions.php ([see example](https://github.com/bph/plain-pauli/blob/main/functions.php))
- Add a block style in json format to /styles folder of your theme
- Activate the theme
- Open the page editor to use the block style
- Open Styles > Blocks section to see the block styles. 

### Screenshots, screen recording, code snippet

This video shows the post editor and its image block styles. Then switch over the Appearance > Editor > Styles > Blocks > Image and it only show two variations the core rounded and the blue border from the /styles folder. 

https://github.com/user-attachments/assets/c42fa4c0-82e9-4e6f-a852-f246b3d21dfc

This screenshot also shows the display of all available variations of in the Template editor, too. 

![Screenshot 2024-07-23 at 09 30 11](https://github.com/user-attachments/assets/64fded0d-8424-4dda-af15-086d400284bc)

### Environment info

- WordPress 6.6.1 RC 1
- Theme [Plain-Pauli](https://github.com/bph/plain-pauli)
- Chrome Version 126.0.6478.183
- I also tested it with Gutenberg Nightly v19.0.20240722 activated and it was still happening. 

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by talldan** [comment]
I think only the theme.json style variations are supported in global styles. For the ones that only have a `style_handle`, the styles are expected to be applied via css and so there's no way for global styles to support them reliably.

@aaronrobertshaw would be able to confirm.

**Comment by aaronrobertshaw** [comment]
Thanks for the ping 👍 

I believe @danr's explanation is on the money but it might benefit from some nuances being explained further:

- for any given block style variation to be supported in theme.json and global styles, it must be registered e.g. via `register_block_style`
- only block style variations that have theme.json data are available to be configured through global styles
- block style variations defined within the main theme.json or a theme.json partial in `/styles` have data
- block style variations that are registered via `register_block_style` using a style object for the `style_data` property get [merged into theme.json](https://github.com/WordPress/gutenberg/blob/trunk/lib/class-wp-theme-json-resolver-gutenberg.php?plain=1#L919) and as such have data and can be configured in global styles 

Here's an example of registering a block style in PHP with style data so it is available for further customization in global styles:

```php
register_block_style(
	array( 'core/group', 'core/columns' ),
	array(
		'name'       => 'section-a',
		'label'      => __( 'Section A' ),
		'style_data' => array(
			'color'    => array(
				'background' => '#4f6f52',
				'text'       => '#d2e3c8',
			),
			'blocks'   => array(
				'core/group' => array(
					'color' => array(
						'background' => '#739072',
						'text'       => '#e3eedd',
					),
				),
			),
			'elements' => array(
				'link' => array(
					'color'  => array(
						'text' => '#ead196',
					),
					':hover' => array(
						'color' => array(
							'text' => '#ebd9b4',
						),
					),
				),
			),
		),
	)
);
```

For the theme linked in the description, I believe everything is working as intended. 

The blue border style is available in global styles as it is coming from the theme.json partial. The purple and red border styles aren't registered with a style object for the `style_data` property and have no matching theme.json `styles.variations` or partial entries, so aren't available.

I hope that helps 🤞

**Comment by bph** [comment]
Yes, that helps quite a bit! Thank you, @aaronrobertshaw 
It's probably also the reason @bacoords open the issue 
- #63263

So how would I register the **Red border** with the style_data object in PHP? 

It's not entirely clear from your example. 
I tried: (but I might totally overlook something simple) 
```
 register_block_style(
        array( 'core/image' ),
        array(
            'name'         => 'red-border',
            'label'        => __( 'Red Border', 'plain-pauli' ),
            'style_data'=> array(
                'blocks' => array(
                    'core/image'=> array(
                        'border' => array(
                            'color' => '#00f9ff',
                             'style' => 'solid',
                             'width' => '4px',
                             'radius' => '15px'
                            ),
			            'shadow'=> array(
                            'var(--wp--preset--shadow--natural)'
                        )
                        )

                    )
              )
            )
        );
```
(updated above code) 
1) It wouldn't apply the styles (somehow I messed that up) but  
2)It would be listed in the Global Styles, and I was able to modify it 

So I get the principle. I am super unsure about the syntax, PHP arrays versus theme.json.

**Comment by bph** [comment]
I also close this issue as it seems to work as designed. This is more a documentation issue, rather than a bug.

**Comment by aaronrobertshaw** [comment]
> It's probably also the reason bacoords open the issue

I'm not quite sure yet what to make of https://github.com/WordPress/gutenberg/issues/63263 but I think it is a bit different to this case.

> So how would I register the Red border with the style_data object in PHP?

Thanks for sharing your `register_block_style` snippet, it helps a lot. In your example `style_data` you are defining styles for an inner Image block within a parent Image block style. Not exactly possible at the moment 🙂 

The style data given to `register_block_style` is effectively copied into your theme.json data under the relevant block type/s. So for the example data given, that would end up resembling something like:

```json
	"styles": {
		"blocks": {
			"core/image": {
				"variations": {
					"red-border": {
						"blocks": {
							"core/image": {
								"border": {
									"color": "00f9ff",
									"style": "solid",
									"width": "4px",
									"radius": "15px"
								},
								"shadow": [ 'var(--wp--preset--shadow--natural)' ],
							}
						}
					}
				}
			}
		}
	}
```

Hopefully, that explains why it wasn't working 🤞 

To fix it up so that it does work, try something more like:

```
register_block_style(
	array( 'core/image' ),
	array(
		'name'       => 'red-border',
		'label'      => __( 'Red Border', 'plain-pauli' ),
		'style_data' => array(
			'border'    => array(
				'color' => '#00f9ff',
				'style'       => 'solid',
				'width' => '4px',
				'radius' => '15px'
			),
			'shadow'   => array( 'var(--wp--preset--shadow--natural)' ),
		),
	)
);
```

Note how the styles you want to apply to the block type, the block style is for, are at the top level within the `style_data` property. This mirrors the structure of the theme.json partials which you have working for the [blue border](https://github.com/bph/plain-pauli/blob/main/styles/image-blue-border.json) style.

If you use the example above exactly, just be aware it has the same color from your last example which is blue not red. 

Hope that helps. Happy section styling 😁 

<img width="602" alt="Screenshot 2024-07-23 at 9 14 05 PM" src="https://github.com/user-attachments/assets/63c8e857-a306-482d-ad22-9b304bb3087e">

**Comment by bph** [comment]
@aaronrobertshaw That is so helpful! Thank you so much!

**Comment by ndiego** [comment]
This is a great deep dive into the nuances of block style variations. 👌
