### ISSUE TITLE
Caption, alt text, and description should appear in the featured image modal

### ISSUE THREAD

**Issue by davisshaver** [WordPress/gutenberg#6383]
**Gutenberg featured image selection**
![image](https://user-images.githubusercontent.com/1636964/39189048-47d401c6-479f-11e8-9492-6300ef72a634.png)

**Legacy featured image selection**
![image](https://user-images.githubusercontent.com/1636964/39189064-5775a940-479f-11e8-8cd0-e48c0d9d25c5.png)

**Expected**
Caption, alt text, and description should appear in the featured image selection to assist with selecting the correct image to accompany the Gutenberg post.

**Comment by karmatosed** [comment]
Can you explain a bit more how these help with selecting? I am not against adding them back in for parity but I do wonder if they are as useful. I would love to get some user insight here.

**Comment by davisshaver** [comment]
The caption, alt text, and description often contain text uploaded by someone other than the person selecting the featured image. Including these fields help ensure the correct image is selected.

**Comment by danielbachhuber** [comment]
Notably, it's also a quick way of _editing_ the caption and description associated with an image.

**Comment by karmatosed** [comment]
Thanks for context. Let's go for parity then as we are not in v1 redoing the way featured images are it makes sense to keep parity.

**Comment by danielbachhuber** [comment]
🔨  in #6545
