### ISSUE TITLE
Zoom Out: Canvas size incorrect in Post Editor

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#63848]
## What problem does this address?
On very large screens the canvas size in Zoom Out is larger than full width blocks:
<img width="824" alt="Screenshot 2024-07-23 at 10 50 12" src="https://github.com/user-attachments/assets/7b9a498c-bd9b-4bfd-92b3-968633010075">

## What is your proposed solution?
Full width blocks should always go to the edge of the canvas:
<img width="980" alt="Screenshot 2024-07-23 at 11 45 59" src="https://github.com/user-attachments/assets/44f96e73-245e-4354-a105-97c051f82c01">

**Comment by Rishit30G** [comment]
Hey @scruffian, 
I was replicating this issue, however I'm able to see Full width blocks reaching to edge of the canvas as expected 
Using WordPress v6.7 and Gutenberg v18.8.0
Sharing the screenshot for better understanding: 
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/8b98c1d4-0a16-4b92-ae56-7b01b576f116">

**Comment by scruffian** [comment]
I still see it, but only in the Post Editor:
<img width="733" alt="Screenshot 2024-08-13 at 10 54 53" src="https://github.com/user-attachments/assets/3d51c5a9-3ec2-446b-990a-978c90f67e04">

**Comment by draganescu** [comment]
I can no longer replicate the issue, including in the post editor.
