### ISSUE TITLE
Is it possible using registerBlockType with apiFetch?

### ISSUE THREAD

**Issue by yarovikov** [WordPress/gutenberg#63853]
### Description

Hi there.
I use wp 6.6, clean database, no any plugins, twentytwentyfour theme.

I have a lot of custom blocks (not acf). Currently i would like to have one js for all my blocks.
For example this is working as well:

```
const blocks = [
  'faq',
  'contact-form',
];

blocks.forEach(block => {
  const name = `gutengood/${block}`;
  registerBlockType(name, {
    title: block,
    icon: 'block-default',
    category: 'common',
    edit: (props) => {
      return (
        <Fragment>
          {block}
        </Fragment>
      )
    },
    save: () => null,
  });
});
```

But when i’m getting the same list of blocks using rest api sometimes blocks are not initialized in the editor after edit page reload (also n any errors in the console), although they are in the page code. Also i see them in dropdown (plus button). Is it possible to fix display in the editor after reloading the edit page? 

```
apiFetch({path: '/gutengood/v1/blocks'})
  .then((blocks) => {
    blocks.forEach(block => {
      const name = `gutengood/${block}`;
      registerBlockType(name, {
        title: block,
        icon: 'block-default',
        category: 'common',
        edit: (props) => {
          return (
            <Fragment>
              <InspectorControls>
                <BlockOptions name={name} props={props}/>
              </InspectorControls>
              <ServerSideRender
                block={name}
                attributes={props.attributes}
              />
            </Fragment>
          )
        },
        save: (props) => null,
      });
    });
  })
  .catch((error) => console.error(error?.message));

```

### Step-by-step reproduction instructions

1. Open edit page, insert the block
2. Reload edit page

### Screenshots, screen recording, code snippet

Open edit page, insert the block

<img width="1473" alt="350797380-a2c5f6f8-573e-4a2e-b44b-ff3522d6ea88" src="https://github.com/user-attachments/assets/13922c7e-5050-42b1-b7ea-a12a51e927b5">

After edit page reload:

<img width="1233" alt="350797177-18565498-972c-406d-8475-99dd982b855d" src="https://github.com/user-attachments/assets/ad2cb81f-1878-4cc9-add8-e3c1a11bc344">

<img width="899" alt="350797175-2762a8d5-67cf-47f5-b331-b09b0d70ed00" src="https://github.com/user-attachments/assets/6686103c-6069-4a5c-ad78-5decfbc9e18a">

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by gziolo** [comment]
> But when i’m getting the same list of blocks using rest api sometimes blocks are not initialized in the editor after edit page reload (also n any errors in the console), although they are in the page code. Also i see them in dropdown (plus button). Is it possible to fix display in the editor after reloading the edit page?

Thank you for the report. When the issue occurs after the page reload, are you able to insert new blocks of the same type? When you change anything in the editor, e.g. add a new block, does your block gets correctly updated?

**Comment by yarovikov** [comment]
> Thank you for the report. When the issue occurs after the page reload, are you able to insert new blocks of the same type? When you change anything in the editor, e.g. add a new block, does your block gets correctly updated?

I think this video is better way to explain :)

https://github.com/user-attachments/assets/c0567959-4053-4d79-8814-70e35fc81d82


PS. currently i'm using wp_localize_script for passing block names to my js. But i think using rest api is more beautiful solution.

**Comment by noisysocks** [comment]
Looking at the video I suppose this is to do with `registerBlockType` not being called before the editor is initialised (`wp.editPost.initialize()`) which parses `post_content` and expects to have the block registered.

I don't know that there's much we can do in Gutenberg to fix this? We could make it so that calling `registerBlockType` causes the post to be re-parsed but users would still a flash of "Missing block" error message which isn't a great experience.

Can you definitely not register the block on the server? I think that would be best.

Alternatively maybe you can unhook the inline script attached to `wp-edit-post` that initialises the block editor and define your own inline script that registers your blocks and then initialises the block editor once that's done.

**Comment by yarovikov** [comment]
Hi @noisysocks ,
Thanks for your answer. Currently i'm using wp_localize_script without any problem. Probably i'll think about other ways later. For now i wouldn't like to deviate too much from the stack i'm using ([sage](https://roots.io/sage/)) :)
