### ISSUE TITLE
Opening Gutenberg post in Classic Visual editor adds unwanted <p>&nbsp;</p> content

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#6385]
## Issue Overview

For GB 2.7:

I don't think _gutenberg_disable_editor_settings_wpautop_ is working as expected. I would hope that it would prevent editing a GB post with the classic editor would prevent it from changing all the blank lines between the GB blocks into _&lt;p>&amp;nbsp;&lt;/p>_ which then add lines and show up in GB as a Classic block.

## Steps to Reproduce (for bugs)

1. Create a page/post with Gutenberg blocks (duplicate one you already have
2. From the All Pages/Posts view, edit that page in the Classic Editor, save
3. Open same page in Gutenberg - all the formerly blank lines have been changed to &lt;p>&amp;nbsp;&lt;/p> with unintended consequences.
4. It seems from the comments that gutenberg_disable_editor_settings_wpautop is supposed to prevent that, but it doesn't.

## Possible Solution

Maybe changing the priority of the gutenberg_disable_editor_settings_wpautop filter?

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Related #4672 #4446

**Comment by danielbachhuber** [comment]
Specifically, if you start out with the following in the Text editor:

```
<!-- wp:heading -->
<h2>This is a heading block</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>This is my paragraph text.</p>
<!-- /wp:paragraph -->
```

Switching to the Visual Editor and then back to the text editor leaves you with this:

```
<!-- wp:heading -->
<h2>This is a heading block</h2>
<!-- /wp:heading -->
<p>&nbsp;</p>
<!-- wp:paragraph -->
<p>This is my paragraph text.</p>
<!-- /wp:paragraph -->
```

Here's a GIF of the behavior:

![nbsp](https://user-images.githubusercontent.com/36432/40976802-10b79eea-6884-11e8-9a39-147d00f8f798.gif)

**Comment by azaozz** [comment]
This is not related to `wpautop`. TinyMCE can make (empty) paragraphs from HTML comments that are on a separate new line. Example: http://fiddle.tinymce.com/Ctgaab/5.

To fix this we need to fix the white space between HTML comments when loading the content in TinyMCE, something like:
```
content = content.replace( /-->\s+<!--/g, '' );
```
And of course restore that on saving and switching to the Text editor with:
```
content = content.replace( /-->\s+<!--/g, '-->\n\n<!--' );
```

**Comment by azaozz** [comment]
https://core.trac.wordpress.org/attachment/ticket/44308/44308.patch

**Comment by danielbachhuber** [comment]
@azaozz I tested this locally against my wordpress-develop checkout:

```
grunt patch:https://core.trac.wordpress.org/attachment/ticket/44308/44308.patch
grunt build
```

However, the issue still manifests:

![nbsp](https://user-images.githubusercontent.com/36432/41068543-c6b0e678-699e-11e8-93cb-5397c3196c8a.gif)

Is there some other step I'm missing?

**Comment by azaozz** [comment]
> However, the issue still manifests

Testing in `/build` has some quirks. Enable `SCRIPT_DEBUG` and make sure the browser cache is cleared :)

**Comment by danielbachhuber** [comment]
> Enable SCRIPT_DEBUG and make sure the browser cache is cleared :)

Even clearing browser cache didn't work for me! Opening in incognito did though.

**Comment by danielbachhuber** [comment]
@azaozz Do you think we can shim this into Gutenberg for a more immediate fix?

**Comment by azaozz** [comment]
Sure, think there was a place to add classic editor's TinyMCE fixes somewhere. If not, will have to make a tiny TinyMCE plugin :)
