### ISSUE TITLE
iAPI: Merge of state and context after client-side navigation

### ISSUE THREAD

**Issue by luisherranz** [WordPress/gutenberg#63864]
### Description

There's no way to distinguish the global state belonging to blocks that are inside a router region from the global state belonging to blocks that are not inside a router region. Therefore, we can't use the strategy of replacing the client state with the state coming from the server during client-side navigations.

### Step-by-step reproduction instructions

1. Create a block that uses global state. 
2. Place that block outside of a router region. 
3. Navigate to a page where the global state is different from the initial page. 
4. The state of the block was updated, which it shouldn't have, since it's outside a router region.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by michalczaplinski** [comment]
If I understand correctly: 

This assumes that the "new" page (the one that is navigated to in step 3.) loads some JS (typically the `view.js` file) that updates the global state?

**Comment by luisherranz** [comment]
No, it does refer to the state and context that is serialized from the server and how it merges with the existing state and context.

**Comment by luisherranz** [comment]
Completed in https://github.com/WordPress/gutenberg/pull/62734.
