### ISSUE TITLE
"Post updated!" message - Distinguish Page or Post, please.

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#6386]
## Issue Overview

After updating a page OR Post, the top message bar always says "Post updated! View Posts". Why can't that message differentiate between Pages and Posts? The classic editor does, and I know I depend on that a lot. I imagine other people forget if they are editing a page or a post, and depend on the classic behavior to remind them. It does matter sometimes.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Hi @weavertheme,

Thanks for the report. This issue is already tracked with #3315
