### ISSUE TITLE
Assemble new pages with zoom out

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#63865]
It’s not uncommon for website builders to offer a perspective that allows you to see more of your page by stacking sections of a page together. In WordPress, these are called [Patterns](https://rich.blog/patterns/).

I propose a similar experience within WordPress: an “Add new page” composition flow where you stack patterns on a page, reorder, apply section styles, remove, and even shuffle among similar patterns. 

#### Key points 
- This concept would replace the starter content modal. 
- There should be a clear way to start with a blank page. 
- Perhaps if you indicate to start with a blank page, there’s a modal asking you if that should always happen, and informing you where to change it in the future. 
- This view should open the Inserter with the Patterns tab selected, with zoom out mode engaged. 
- Help text should render if there are no patterns added to the page. 
- Starter content patterns should be prioritized, as full page designs to start with.

**Comment by mtias** [comment]
One thing we should incorporate is clearer distinction between section patterns and full page starter templates in the sidebar UI — it's all a bit mixed right now.

**Comment by MaggieCabrera** [comment]
> One thing we should incorporate is clearer distinction between section patterns and full page starter templates in the sidebar UI — it's all a bit mixed right now.

I was coming to say this. Themes that have full page patterns should have them open by default when in this kind of flow, since we are replacing the modal that is surfacing them now

**Comment by scruffian** [comment]
We have an interesting approach in https://github.com/WordPress/gutenberg/pull/61489

**Comment by getdave** [comment]
> opening the editor in zoom out mode so that users can begin assembling their page from patterns

Small nit, but could we rename this Issue to better reflect the goal? Perhaps it should be `Patterns Zoom out mode on new Page creation`?

Currently `Compose pages with zoom out view` seems like a very broad scope for this issue.

**Comment by annezazu** [comment]
Noting that there's an in progress PR here https://github.com/WordPress/gutenberg/pull/66836 to address this!

**Comment by Mamaduka** [comment]
Re-opening the issue. The #66836 has been reverted via #69081.

It would be good for future resolutions to account items listed in #68736.
