### ISSUE TITLE
Zoom Out: Hold to drag and drop nested patterns.

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#63863]
## What problem does this address?
Following on from https://github.com/WordPress/gutenberg/issues/63862, we want to prioritise patterns as sectioning elements, but we also don't want to totally prevent nested patterns.

## What is your proposed solution?
When in zoom out mode, and using drag and drop, if a user holds a pattern over another pattern for X milliseconds, they become able to nest the pattern inside another pattern. 

This needs to be done after https://github.com/WordPress/gutenberg/issues/63862

**Comment by MaggieCabrera** [comment]
Do we need to do this if we said we weren't going to allow drag and drop inside patterns?

**Comment by scruffian** [comment]
I think it would be a nice improvement to be able to do it after you hold for X seconds, but probably low priority.

**Comment by richtabor** [comment]
Perhaps in the future we can re-explore this, but currently I think it's fine that you can disengage zoom out now, to add patterns wherever you'd like. And with https://github.com/WordPress/gutenberg/pull/65945, it may be confusing determining the state of editing with this extra hold to drag and drop patterns within UX.
