### ISSUE TITLE
Search for blocks with accents

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#6387]
When you search for a block called for example "média" by typing "media",  there is no result. 

This bug will appear when every country will translate Gutenberg. On some countries like France, user won't be able to easily find some blocks. 

It can be fixed by adding some keywords. but it's not ideal. 

The search should search every accentuated character by its standard equivalent : 

é è ê ë should be searched as a simple "e" for example.

**Comment by karmatosed** [comment]
I can replicate this, thanks for catching and lets see about getting a fix for this.

**Comment by braders** [comment]
WordPress core has the helpful `remove_accents( $string )` function. If this was ported to the front-end (maybe as a package in [WordPress/packages](https://github.com/WordPress/packages)), then all strings could be normalised (i.e. without accents) before search comparisons are run.
