### ISSUE TITLE
Post Edit Screen Restricted by Metaboxes

### ISSUE THREAD

**Issue by PC888** [WordPress/gutenberg#63882]
### Description

Hey guys,

I’ve recently noticed that any meta boxes below the content in the Post Editor restrict the size of the editing window i.e. jam the last block hard against the bottom of the editing window, forcing me to add several blank paragraphs, in order to get some ‘breathing space’. Yoast was the plugin in question but the Custom Fields meta box, toggled on from the block editor preferences, has exactly the same effect. If I deactivate the plugin or toggle off the Custom Field UI the issue goes away.

I opened a ticket here >> https://wordpress.org/support/topic/post-edit-screen-restricted-by-yoast-metabox/#post-17908765 for further info...

Image 1. I’ve enlarged the image slightly to try and make it a bit clearer. You should be able to see how the last <p> block is jammed hard against the bottom of the editor window.
![wp-support-post-editor-image1](https://github.com/user-attachments/assets/dc447ba0-384c-4272-815d-3a225d6176fa)

Image 2. I’ve collapsed the Yoast Meta Box and now the last <p> block is jammed against the bottom of my browser window. The content won’t scroll up to raise the last block to a comfortable working height in the editor. I have to add several empty <p> blocks instead…
![wp-support-post-editor-image2](https://github.com/user-attachments/assets/e97997c7-0da8-42f3-8951-d08814b8004a)

Image 3. I’ve deactivated Yoast and this is how I seem to remember it being…
![wp-support-post-editor-image3](https://github.com/user-attachments/assets/ab5f766b-73bb-4168-9349-f63f5a506305)

I have experienced this in the past and IIRC a subsequent update resolved the issue…

Paul

### Step-by-step reproduction instructions

Blank WP install with TT4 active
Toggle on Custom Fields
Drop some Lorum Ipsum into a new post

### Screenshots, screen recording, code snippet

![wp-support-post-editor-image1](https://github.com/user-attachments/assets/6660c17e-f19c-4293-9cc5-2418e97dadca)
![wp-support-post-editor-image2](https://github.com/user-attachments/assets/9092811a-a3ec-4827-9095-99099ac8e3a9)
![wp-support-post-editor-image3](https://github.com/user-attachments/assets/70e6ec2a-7060-4e85-a3ad-526de587f7a8)

### Environment info

WP 6.6 and TT4, no plugins active, Chrome browser, Mac OS 14.5

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by talldan** [comment]
This was also reported in trac - https://core.trac.wordpress.org/ticket/61677

**Comment by carolinan** [comment]
Would love to see this fixed.

**Comment by smerriman** [comment]
This isn't just a visual issue. If the last element in the editor is, say, a Media & Text block, it is actually entirely impossible to insert content at the bottom of the editor as of WordPress 6.6. Previously there was a space I could hover / click to make an inserter show up, but this is no longer the case.

**Comment by talldan** [comment]
> it is actually entirely impossible to insert content at the bottom of the editor as of WordPress 6.6.

I understand it's not ideal, but I don't think it's impossible, there's the `Add After` option in the block options menu.
![Screenshot 2024-08-01 at 10 43 52 AM](https://github.com/user-attachments/assets/bf956a8d-9862-40bc-8f9f-30dca7114c2e)

**Comment by finlay-x** [comment]
Im suprised this doesn't have more traction as an issue as I have had to downgrade multiple sites to 6.5.5 due to site editors  finding it harder to add blocks.

**Comment by PC888** [comment]
100% with you @finlay-x it's an awful user experience!

**Comment by talldan** [comment]
There's some work in progress to change the metabox panel for  6.7 - [Try split content view with open metaboxes](https://github.com/WordPress/gutenberg/pull/64351#top).

I think it should help with this issue, I'd definitely suggest giving it a test if you can and leaving feedback on that PR ([The playground is a quick way to test pull requests](https://playground.wordpress.net/gutenberg.html))

**Comment by smerriman** [comment]
This really needs to be resolved before 6.7, as it was a bug introduced to with 6.6, and also needs to work for a non-iframed editor. So a brand new approach being planned for 6.7 isn't the right solution for people using WordPress now.

**Comment by talldan** [comment]
Ok, I tried a fix in #64639. There might be some reasons for it being like it was in 6.6, so we'll see what the code review feedback is.

**Comment by smerriman** [comment]
@talldan I just tested your CSS in WP 6.6 from #64639 , and while it adds a space, it's still impossible to insert content below the last block (if it's something other than e.g. plain text) by clicking in the blank space, like it was in 6.5.

This is the most frustrating part about this bug, and is what other commenters were referring to above (the difficulty of inserting blocks at the bottom).

Does this need to be reopened as a separate bug report?

**Comment by PC888** [comment]
I'm with you @smerriman, I can't believe this bug fix hasn't had more traction

**Comment by talldan** [comment]
> This is the most frustrating part about this bug, and is what other commenters were referring to above (the difficulty of inserting blocks at the bottom).

> Does this need to be reopened as a separate bug report?

@smerriman Yeah, [I discovered while working on that PR that the lack of a gap was caused by the removal of the inserter button.](https://github.com/WordPress/gutenberg/pull/64639#issuecomment-2303586603)

I see you went ahead and [created another issue though](https://github.com/WordPress/gutenberg/issues/64889), thanks for doing that.

**Comment by paaljoachim** [comment]
I have added a few comments here:
https://github.com/WordPress/gutenberg/issues/64889#issuecomment-2325809282

Using WP 6.6.1
Theme: Twenty Twenty Four.
Gutenberg plugin: 19.1

I have noticed that plugins that add a metabox to the Post Editor screen cause a problem so one can not click below a current block to add a new block. I tested with Autoptimize and Yoast SEO plugins. 

I reopened this issue.

**Comment by t-hamano** [comment]
@paaljoachim This issue has been fixed by #64639. #64639 is part of the upcoming Gutenberg 19.2, so it is not fixed yet in Gutenberg 19.1.

Also, #64639 seems to be planned to be backported to WordPress 6.6.2.

**Comment by talldan** [comment]
Closed again.

@paaljoachim If you look at the pull request that closed an issue, you'll be able to see which Gutenberg version it's milestoned for. You can also test that PR using the playground (https://playground.wordpress.net/gutenberg.html).

It'd be great to not re-open issues unnecessarily, there are already enough open issues 😄

**Comment by paaljoachim** [comment]
It is great to hear a fix has been added!

My mistake.
Thank you for the update!

**Comment by hellofromtonya** [comment]
Hello @finlay-x 👋 

Can you share your [WordPress profile](https://profiles.wordpress.org/) username please?

With this bugfix shipping in 6.6.2, having your WP Profile username will give you a contributor credit (prop) for the release. Thank you.
