### ISSUE TITLE
Framework: Extract notices state from editor module

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#6388]
Notices are not an editor-specific feature, yet the current notices state lives within `editor`. Before plugins start integrating more with this functionality, we should consider whether to extract it, either to its own module (like [viewport](https://github.com/WordPress/gutenberg/tree/master/viewport)), or to `components`, or perhaps even to a new concept of "data-bound components". 

See also #5316 which highlights some issues with the viewport approach of independent data modules exporting their own components, as it can result in circular dependencies between components and the individual module.

**Proposal options:**

- Create new `notices` folder, which creates its own `data` state
   - Either exposes a data-bound component which editor uses to render, or this component lives elswhere
- Add new `notices` component to `components` directory, which bundles its own `data` state

**Open questions:**

Do we need concepts of scoped notices? If a plugin adds a notice and intends for it to be shown in the editor, how does this scale out to a more general solution? Is this something we need to address now?

**Comment by danielbachhuber** [comment]
Some relevant prior issues:

* #5975 Introduce formal API for displaying notices
* #5590 Capture admin notices and summarize them in editor

**Comment by collimarco** [comment]
This issue has been closed, but traditional `admin_notices` don't work in Gutenberg (they are not displayed...)

Please fix this
