### ISSUE TITLE
Pattern shuffle: The shuffle button is displayed when there is only a single pattern in a category

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#63902]
### Description

The pattern shuffle button allows users to cycle through patterns in the same category. However, if there is only a single pattern in a category (admittedly this might be a rare occurrence), the shuffle button is still displayed. When clicked, there are no additional patterns to cycle through, so the button does nothing. This happens in both Zoom out mode and at the block level.

### Step-by-step reproduction instructions

1. Create a new pattern category
2. Add a pattern to this category
3. Insert the pattern and see that the shuffle button is displayed, but it doesn't do anything

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/e56a3883-c740-45ab-80ac-a2fc72bb8a07

### Environment info

- WordPress 6.6
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
This issue seems to have been resolved in #63093. Does this issue still occur in Gutenberg trunk?

**Comment by ndiego** [comment]
> This issue seems to have been resolved in https://github.com/WordPress/gutenberg/pull/63093. Does this issue still occur in Gutenberg trunk?

Ahh shoot, I had an old build. I can confirm it's not in trunk and the issue is fixed in 6.6.1. Closing this out.
