### ISSUE TITLE
an error when running npm start

### ISSUE THREAD

**Issue by derridHeidegger** [WordPress/gutenberg#63926]
### Description

i have a block that i want to work on, but when i tun npm start i get this error: `node:internal/crypto/hash:79
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported`

this is new. i had no issues before to run start or build.

my node version is: 20.16.0
my npm version: 10.5.0

i have no idea what happened or how to fix it. i am not sure if it is a gutenberg issue.... but it is a block

### Step-by-step reproduction instructions

1. go to a block in the plugins directory. cd into it
2. run npm start

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by gziolo** [comment]
Thank you for the report. It would help to find out more details to try to reproduce it. What version of `@wordpress/scripts` do you use in your project? What is the development env in which you run?

**Comment by derridHeidegger** [comment]
my node version is: 20.16.0

my npm version: 10.8.1

the default wordpress theme 2024.

windows 11.
and i have created blocks before: static and dynamic....

**Comment by derridHeidegger** [comment]
there was an issue with a dependency. i fixed it by running: npm install --save-dev ajv@^7
