### ISSUE TITLE
Typesets section renders a list of installed fonts

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#63940]
## What?
I'm seeing this in Gutenberg trunk after merging this PR https://github.com/WordPress/gutenberg/pull/62539. I don't think this is the intended behaviour. It seems like typesets is just rendering the list of the installed fonts and not the font families variations:

[Screencast from 25-07-24 10:28:47.webm](https://github.com/user-attachments/assets/aa55338b-3f1e-4fd9-be4e-a7cc372b3251)

## Expected:
Render a list of font families styles variations.

----
_Originally in https://github.com/WordPress/gutenberg/issues/62539#issuecomment-2250333529_

**Comment by scruffian** [comment]
I think it's working as expected! @richtabor what do you think?

**Comment by richtabor** [comment]
> It seems like typesets is just rendering the list of the installed fonts and not the font families variations

TT4 does not have any typesets, correct?

**Comment by matiasbenedetto** [comment]
To be honest, I'm not sure what is a 'typeset'. I suppose that that term refers to the list of fonts defines by a style variation. If that's true TT4 has a few theme style variations including different font families but they are not listed in the typeset screen.

**Comment by richtabor** [comment]
Style variations that are comprised on only typography rules, like [these](https://github.com/Automattic/themes/tree/trunk/assembler/styles/typography). Just like alternate color palettes, but for typography.

**Comment by matiasbenedetto** [comment]
I'm not sure If I understand. TT4 has style variations with different font families. Should they be considered as 'typesets' or not?

**Comment by richtabor** [comment]
They must be typography-only, to be considered. This is from the Assembler theme:

![CleanShot 2024-07-26 at 12 23 51](https://github.com/user-attachments/assets/49a87868-def4-4d3b-abb8-28645ac0588d)

**Comment by matiasbenedetto** [comment]
I submitted this PR to hide the typesets button when there are not typesets available: https://github.com/WordPress/gutenberg/pull/64515
