### ISSUE TITLE
Add/Editing link in block editor appears underneath the next panel

### ISSUE THREAD

**Issue by BabcoxDeveloper** [WordPress/gutenberg#63944]
### Description

The issue has been present since 6.6. Upgrading to 6.6.1 did not fix the issue. Happens on clean install.

### Step-by-step reproduction instructions

- add enough text so that the text displays close to the next panel
- click the link icon
- the edit link modal displays under the next panel

### Screenshots, screen recording, code snippet

![link-modal-issue](https://github.com/user-attachments/assets/03f87d79-62e5-4cfc-87f8-6ab449c837c5)

### Environment info

- WP 6.6 & 6.6.1
- Windows 10
- Chromium: 127.0.6533.73 

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This issue has also been reported in #62998, and a solution is being attempted in #63939.

Therefore, I'd like to close this issue.
