### ISSUE TITLE
The 'Upload' button for external media doesn't work properly

### ISSUE THREAD

**Issue by HasibTanvir** [WordPress/gutenberg#63956]
### Description

When we hit the Publish button, it shows a pre-publishing checklist including the availability of external media files. The upload button should enable us to upload external files to the media library. But, it isn't working for my case. 

### Step-by-step reproduction instructions

1. Go to Gutenberg editor
2. Keep some external images in the post
3. Hit the Publish button
4. Click on the Upload button from the prepublish panel

### Screenshots, screen recording, code snippet

https://share.cleanshot.com/pVj9vwBR

### Environment info

This feature -> https://github.com/WordPress/gutenberg/pull/46014 isn't working. 

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by sgomes** [comment]
@HasibTanvir I'm not sure if #64741 fixes the issue for you, as it depends on what the root cause was. Please feel free to reopen if this is still broken for you in trunk!

**Comment by HasibTanvir** [comment]
@sgomes It solved the issue for me. Thanks to everyone involved in this fix.

**Comment by solaceten** [comment]
Hello - I also see this issue, what is the fix please?

**Comment by HasibTanvir** [comment]
Hello @sgomes , the issue came back for some of my websites. Can you please have a look if it's related to the latest WP update?

**Comment by sgomes** [comment]
Hey @HasibTanvir, I don't think there have been any changes to this lately, so it's surprising this would stop working.

Are there any error messages in the editor UI or the browser console? Perhaps the images you're trying to upload don't have CORS headers set, and so the editor is unable to download them?
