### ISSUE TITLE
Grid: Don't highlight grid cell if block being dragged is not allowed to be placed into the Grid

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#63979]
When you drag a block over a Grid, we highlight the cell that you're hovering over.

We should not do this when the block you're dragging can't be inserted into a Grid. For example, you can't put a Button block into a Grid. (You can only put a Button block into a Buttons block.)

Example:

https://github.com/user-attachments/assets/228a0d47-b154-4401-8e91-9ae32f03e288

The empty cells shouldn't turn blue.

I believe there's already selectors for this e.g. `canInsertBlockType`.

**Comment by hanneslsm** [comment]
> For example, you can't put a Button block into a Grid. (You can only put a Button block into a Buttons block.)

Regarding this example, wouldn't it be better to automatically create a the button group (or duplicate it with all settings) where the dragged button lives in?
Other than that, I agree that the empty cell shouldn't be blue.

**Comment by noisysocks** [comment]
That's a good suggestion. I think if we did that then we should do it across all blocks. For now, in the context of https://github.com/WordPress/gutenberg/issues/57478, all I really care about is refining Grid specifically.
