### ISSUE TITLE
Quick question, almost impossible to search for. Does Gutenberg not support the "code" block like visual editor?

### ISSUE THREAD

**Issue by thedonquixotic** [WordPress/gutenberg#6397]
What I mean is when you want to `mark something as code formatting`. Does gutenberg not do that? I don't see any default blocks for it. And the backticks don't work the same way that ## and ### do for h2 and h3. So? It's out or what? Just curious.

**Comment by karmatosed** [comment]
You can do that through the code block:

![2018-04-26 at 14 20](https://user-images.githubusercontent.com/253067/39308288-f665cd8c-495c-11e8-98c6-ec7e4c4d5e61.png)

![2018-04-26 at 14 20](https://user-images.githubusercontent.com/253067/39308303-02627b12-495d-11e8-9ee0-86c8e6d75314.png)

You can also go into code view for the entire editor or a specific block:

![2018-04-26 at 14 24](https://user-images.githubusercontent.com/253067/39308517-8d5e36e8-495d-11e8-9c16-8eb11c071c9b.png)

![2018-04-26 at 14 25](https://user-images.githubusercontent.com/253067/39308539-a01cd622-495d-11e8-9e42-7f01caea5c2c.png)

Another option you have is the classic block:

![2018-04-26 at 14 29](https://user-images.githubusercontent.com/253067/39308800-48c778cc-495e-11e8-928d-311c80657f30.png)

Unless I am wrong that gives you options for this so for now going to close. If this isn't what you find useful please add a comment and we can always reopen.

**Comment by chrisvanpatten** [comment]
I agree — a native menu where you could register different inline styles would be excellent. Core has that via [TinyMCE's custom styles](https://codex.wordpress.org/TinyMCE_Custom_Styles) and there isn't an analogue in Gutenberg's Paragraph block.

I think this could also be solved by #4658.

**Comment by thedonquixotic** [comment]
Yes @chrisvanpatten that does seem to fit the bill.
