### ISSUE TITLE
CustomSelectControl: Support generic props type

### ISSUE THREAD

**Issue by meteorlxy** [WordPress/gutenberg#63984]
## What problem does this address?

Currently, the `CustomSelectControl` component is not generic. In the following example, the `option.foo` property could not be inferred correctly in the `onChange` callback:

<img width="760" alt="image" src="https://github.com/user-attachments/assets/241e95bb-5bf8-4c3e-aecd-ff46cfb03944">

By making the props generic, ts could infer the selectedItem type correctly:

<img width="804" alt="image" src="https://github.com/user-attachments/assets/a4485e81-c36b-4912-a502-f47e11f33962">

## What is your proposed solution?

I'll create a PR to help implement it

**Comment by mirka** [comment]
Related: #60293
