### ISSUE TITLE
Clearly denote heading levels in the Style Book

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#64033]
## What problem does this address?
This issue came up in a recent discussion with community members around no-low/low-code theme development. Currently, the Headings section of the Style Book displays five different sizes of the phrase "Code is Poetry". The question was, "How does a user without complete knowledge of HTML markup know what those five different sizes refer to, and why is `h6` missing from the list?"

This issue is further complicated since the Typography > Headings panel allows users to modify the styling for `h1` through `h6`. 

## What is your proposed solution?

I propose that we clearly label each heading level as "Heading One", "Heading Two", etc., and add "Heading Six". 

| Current | Proposed |
|-|-|
|<img width="1516" alt="image" src="https://github.com/user-attachments/assets/22a1fa25-e639-44eb-994d-b76af0fab445">|<img width="1515" alt="image" src="https://github.com/user-attachments/assets/ac8eb8bd-c83a-4cde-80e5-c475466c5889">|

**Comment by ramonjd** [comment]
I think the "Code is Poetry" was meant to reflect the [block example](https://github.com/WordPress/gutenberg/blob/2776e36fa00b91a81459ac71b92acf9c7d534e8a/packages/block-library/src/heading/index.js#L25-L25), which is what the other Style Book examples do.

The "Heading 1, 2, 3..." makes more sense to me too. Done in https://github.com/WordPress/gutenberg/pull/64038

**Comment by ndiego** [comment]
Thanks @ramonjd!
