### ISSUE TITLE
Objects as 'meta' type block attributes

### ISSUE THREAD

**Issue by Luehrsen** [WordPress/gutenberg#6405]
## Issue Overview

As per the meta docs ( https://github.com/WordPress/gutenberg/blob/master/docs/block-api/attributes.md#meta ) I use JSON.stringify and JSON.parse to save an object into post meta.

This works fine, BUT NOT for RichText mulitline elements. Those return a react object, that when parsed though json is obviously not a valid react element for RichText to consume anymore. 

How would I transform the RichText value to and back from JSON to be able to feed it back into RichText?

**Comment by youknowriad** [comment]
Hi!

This should be possible in the next release using `format="string"` in RichTexts. https://wordpress.org/gutenberg/handbook/block-api/rich-text-api/#format-string

I'm going to close this, feel free to reopen if it doesn't solve the issue.
