### ISSUE TITLE
Long slugs break Summary panel UI

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#64052]
<img width="282" alt="Screenshot 2024-07-29 at 11 07 29" src="https://github.com/user-attachments/assets/77083e3f-0faa-4be8-8c03-120ebbe0505c">

**Comment by akasunil** [comment]
Shouldn't we hide long url with using css `text-overflow: ellipsis;`? It was there in [wordpress 6.5](https://playground.wordpress.net/?php=8.3&wp=6.5&storage=none)

**Comment by jameskoster** [comment]
The 6.5 implementation was slightly different since it included the full URL, not only the slug. Still, yes I think that's a reasonable suggestion 👍

**Comment by akasunil** [comment]
I believe it is preferable to have a brief version in a summary as the full slug/URL may be seen in the popover that appears when a link is clicked.

<img width="628" alt="image" src="https://github.com/user-attachments/assets/fad17736-c7b7-46b7-9ca4-506df1176940">

**Comment by Mamaduka** [comment]
It feels like we fixed this issue several times after the redesign.
