### ISSUE TITLE
Editor: Blocks set to Sticky don't work in Template Parts

### ISSUE THREAD

**Issue by kspilarski** [WordPress/gutenberg#64089]
### Description

Setting a block to Sticky does not work if the block is included in a Template part. 

### Step-by-step reproduction instructions

1. Go to the Site Editor.
2. Add a template part like the Header. 
3. In the list view, expand the Header (template part), then set any block under it to sticky and save. 

### Screenshots, screen recording, code snippet

Under the Header template part is the "Header" block which is set to sticky: 

<img width="1527" alt="Screenshot 2024-07-30 at 11 52 25" src="https://github.com/user-attachments/assets/517a92bd-f75f-4a14-87c6-891816f07f43">

Scrolling down the front page doesn't make the Header stay put., even it was set to sticky. 

---

But when a block is not included in a template part, setting the block to sticky works fine: 
<img width="1532" alt="Screenshot 2024-07-30 at 11 56 20" src="https://github.com/user-attachments/assets/9790e4bd-5046-4743-a756-d8b454515188">

### Environment info

- WordPress 6.6.1, Gutenberg 18.8.0
- Twenty Twenty Four theme 
- Chrome 126, MacOS 14.6 

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by carolinan** [comment]
Hi!
This is issue has already been reported, so I am closing it as a duplicate. You can continue the discussions and follow the explorations here:
https://github.com/WordPress/gutenberg/issues/56147
https://github.com/WordPress/gutenberg/issues/47043

Meanwhile, there is a trick that you can use, and that is to add a new group at the top of the template, make it sticky, and place the template part in the group instead.
