### ISSUE TITLE
Show name of named block in settings sidebar like page- or postname

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#64084]
## What problem does this address?
Renaming a block is a valuable option to get more structure and oversight in a post/page.
And using a synced pattern, the given name is also shown in the right settings sidebar - Tab "Block"
But if a regular block is renamed, the name is only visible in the list-view.

## What is your proposed solution?
Show the name of a (renamed) block also in the right settings sidebar, for example "product description" instead of "Paragraph"

**Comment by Mamaduka** [comment]
Fixed via #65641.
