### ISSUE TITLE
Address duplication caused by ComplementaryAreaHeader

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#64095]
On small screens, panels in the Editor show a heading via `ComplementaryAreaHeader`. This produces some unnecessary duplication:

<img width="902" alt="Screenshot 2024-07-30 at 13 15 39" src="https://github.com/user-attachments/assets/dc5f1f71-d3a3-41bc-b646-9d6a491af0b5">

In both cases the heading feels superfluous. The close button is debatable, but given the buttons in the top bar act as toggles, they also feel unnecessary. 

Should these panels be updated to omit `ComplementaryAreaHeader`?

**Comment by Mamaduka** [comment]
Probably a duplicate of #62067.

**Comment by jameskoster** [comment]
Yes, thanks for pointing that out.
