### ISSUE TITLE
Subhead / subheading in archive views

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#6409]
Can subhead subheading be pulled in archive views? It would super nice if you ask me. That's how I (and others I assume) use [Subtitles plugin](https://wordpress.org/plugins/subtitles/).

With this we could have [designs like in Airbnb](https://airbnb.design/).

**Comment by webmatros** [comment]
Agreed. I'd love to see it as well.

For reference: [https://twitter.com/webmatros/status/989095010200113153](https://twitter.com/webmatros/status/989095010200113153)

**Comment by samikeijonen** [comment]
One issue what comes to mind: User can add Subheading anywhere they want, it's not locked under main title in single post.

It might be confusing if user adds subheading in the middle of the post and it appears under title in archive view.

On that note can subheading be locked under main title?

**Comment by philiparthurmoore** [comment]
@samikeijonen Is this similar to the issue raised in https://github.com/WordPress/gutenberg/issues/6072? ☹️

**Comment by samikeijonen** [comment]
@philiparthurmoore Seems pretty much the same but that's closed :(

Great if Subtitles plugin can do it but I don't see a reason why Subheading block could not do it also.

**Comment by karmatosed** [comment]
This feels like a v2 step to me as will mean having a template page right? In the first version of Gutenberg we're not tackling any page templating aspect like that.

I think locking could happen and it was an idea in the original spec, so not one I am against at all.

**Comment by karmatosed** [comment]
As we are logging all version 2 things in the project Customization I am going to do that. We close when we do this to reopen when that project begins. Thanks for the suggestion and discussion can continue.
