### ISSUE TITLE
Use native component props for radio help text

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#64101]
https://github.com/WordPress/gutenberg/pull/63751 updated `RadioControl` to allow per-radio help text. [Example in Storybook](https://wordpress.github.io/gutenberg/?path=/story/components-radiocontrol--with-option-descriptions). 

We should adopt this in UI's that are currently utilising custom code to add this functionality:

<img width="371" alt="Screenshot 2024-07-19 at 09 28 14" src="https://github.com/user-attachments/assets/1f780b8a-eae0-498b-a912-c993a7ee74f0">

### Needs update

- [ ] Status UI in post/page summary panel
- [ ] Discussion UI in post/page summary panel
- [ ] Discussion UI in Blog Home template settings

**Comment by hbhalodia** [comment]
Hi @jameskoster, I guess if we see the latest trunk this is implemented while `RadioControl` component was enhanced,

Ref - https://github.com/WordPress/gutenberg/commit/083bb9196e6d1c2b9079dabc9a6eaa01d94b9449 and PR - https://github.com/WordPress/gutenberg/pull/63751/

I think we can close this issue. 

Thank You,

**Comment by jameskoster** [comment]
Oh nice, I didn't even notice these UI's were updated in the PR 🤦‍♂️
