### ISSUE TITLE
SVG Support?

### ISSUE THREAD

**Issue by pablojoii** [WordPress/gutenberg#64146]
## What problem does this address?
I have header and footer using SVGs and I keep getting "Unexpected of invalid content" error.

## What is your proposed solution?
Get Wordpress Gutemberg to support it. It even renders the SVG, but keep saying that it's not expected. Tried plugins to support it, but they don't seem to be prepared to the "block" idea.

**Comment by bgardner** [comment]
Safe SVG by 10up works great: https://wordpress.org/plugins/safe-svg/

I use it all the time.

**Comment by talldan** [comment]
@pablojoii I believe it's not something that can be fixed in the Gutenberg repository, it's a WordPress core restriction.

There's a trac ticket here discussing SVG support, so I'll close this one - https://core.trac.wordpress.org/ticket/24251.

**Comment by pablojoii** [comment]
Funny you mention that you can't solve it on Gutenberg. I've added a plugin called SVG block, and now my header has no error being reported and renders just as before. Are you sure this can't be done?

**Comment by talldan** [comment]
@pablojoii It can be worked around by plugins, but that isn't solving the central issue, which is a secure way for WordPress to support SVGs, and that's already being discussed in the ticket I mentioned. There's no point duplicating the discussion in the Gutenberg plugin.
