### ISSUE TITLE
Limit Post Password Field to 255 characters.

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#64155]
### Description

In the WordPress database, post passwords are stored in a `varchar(255)` database field.

Presently the post password field in the block editor doesn't limit the length of data in the field so it's possible for users to enter a longer password and trigger a database failure.

The resulting error message is less helpful than it could be as it doesn't explain what caused the database failure.

It would be good to modify the post password field to:

* accept a maximum of 255 characters
* show an inline error message requesting a shorter password

Related [WP#61703](https://core.trac.wordpress.org/ticket/61703)

### Step-by-step reproduction instructions

1. Create a new post
2. Open the status box
3. Set the post to password protected
4. Set the password to a value over 255 characters
5. Click Save 
6. Observe error message.

### Screenshots, screen recording, code snippet

![long post password](https://github.com/user-attachments/assets/8746690b-573d-4e12-990a-66ab136b40c9)

### Environment info

- WordPress trunk at https://github.com/wordPress/wordpress-develop/commits/74e03e3cbef2f2565028f446c76acb2dabf749bd
- Gutenberg plugin disabled

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by ramonjd** [comment]
> The resulting error message is less helpful than it could be as it doesn't explain what caused the database failure.



I wonder if `additional_data` would be more helpful to render?


```json
{
    "code": "db_update_error",
    "message": "Could not update post in the database.",
    "data": {
        "status": 500
    },
    "additional_data": [
        "WordPress database error: Processing the value for the following field failed: post_password. The supplied value may be too long or contains invalid data."
    ]
}
```

**Comment by peterwilsoncc** [comment]
I think using the additional data could be helpful. The string is translatable but the database fields are not (all languages use english db table names, logically enough). 

Another ticket though because it's a wider problem than just this field.
