### ISSUE TITLE
Not possible to assign author to unowned post in the primary edit form

### ISSUE THREAD

**Issue by mossy2100** [WordPress/gutenberg#64163]
### Description

If a user is deleted, and their content is not reassigned, any posts of theirs will be trashed and will no longer have an author. Such a post can be restored, but will still not have an author. You can fix this by doing a Quick Edit and assigning the author to yourself (there's no other option).

However, if you go to the Edit page, there is no author shown and no link to click, although there is an invisible button where the author link usually is. This will bring up the author select dialog with your name shown. You can't change it, and if you close the dialog, the author remains unset and empty.

### Step-by-step reproduction instructions

1. Make a dummy contributor user.
2. Login as the contributor.
3. Create a post.
4. Logout.
5. Login as admin.
6. Delete the contributor without reassigning content.
7. Go to the trash and restore the post.
8. Go to the All tab. Below the post title, click on the Edit link.
9. Note the absence of an Author. Put the mouse where the link normally is and note a hover effect on the empty link. Click it.
10. Note the dialog showing your name in the drop down. You can't change it.
11. Close the dialog and the Author will not be set.

I assume the setting of the author is triggered by a change event on the select control. So, this could perhaps be fixed by having a blank option in the select if the post has no (or an invalid) author. Then selecting your own or some other user's name would trigger the desired change.

### Environment info

WP 6.6
Theme 2024
Mac with Chrome
Site running locally in Docker container with php-fpm 8.3, nginx 1.22, MySQL 8.0.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by Mamaduka** [comment]
Thanks for contributing, @mossy2100!

I can confirm that you can't change the author if there's only one user left.

**Comment by mossy2100** [comment]
You're very welcome :)
