### ISSUE TITLE
Add left/right block hover areas for displaying contextual block tools - Dissapearing hover

### ISSUE THREAD

**Issue by danstramer** [WordPress/gutenberg#6417]
## Issue Overview

New in 2.7: Add left/right block hover areas for displaying contextual block tools.
However they disappear when getting close to them

## Steps to Reproduce (for bugs)

1. Hebrew localhost install
2.Add a block
3.Hover to the right -  the tools appear
4.Hover to the left, over them - they disappear
5. Only the tooltips appear

## Expected Behavior

They should appear when hovering over them

## Screenshots / Video

https://www.dropbox.com/s/kmsu4flufn8szo6/gutenberg-side-menu-bug.mp4?dl=0

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mtias** [comment]
Sounds like an RTL issue and there were some fixes there since.

**Comment by youknowriad** [comment]
I think this is fixed now
