### ISSUE TITLE
Not possible to set hyperlinks at the end of a post

### ISSUE THREAD

**Issue by marco910** [WordPress/gutenberg#64196]
### Description

When trying to set a hyperlink in a paragraph that is at the very end of a post, the dialog field to set the hyperlink is shown behind the meta boxes. This makes adding and editing a hyperlink impossible without adding a few line breaks at the end of the post.

### Step-by-step reproduction instructions

1. Create a new post in the Gutenberg editor
2. Add a long paragraph to it that is at least as tall as the editor space.
3. Try to add a hyperlink at the very end of the post (see screenshot)

### Screenshots, screen recording, code snippet

<img width="868" alt="Bildschirmfoto 2024-08-02 um 11 06 12" src="https://github.com/user-attachments/assets/34353163-0ae9-4c38-b60c-a036606ccfae">

### Environment info

- WordPress version 6.6.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by Mamaduka** [comment]
@t-hamano, was this also fixed in #63939?

**Comment by Mamaduka** [comment]
@marco910, I just tested with the Gutenberg plugin that includes the #63939, and the bug is fixed.

I'm going to close the issue.

**Comment by marco910** [comment]
@Mamaduka Which Wordpress version does include the fix?

**Comment by Mamaduka** [comment]
@marco910, currently, it's only in a plugin that will ship with version 19.0, but I'll mark the fix to be included in the next minor WP release.

Since this is a Gutenberg repository, the issue gets closed if it is fixed in the plugin.

**Comment by t-hamano** [comment]
Yes, this issue should have been fixed in #63939.
