### ISSUE TITLE
Add a column count class on the columns block

### ISSUE THREAD

**Issue by jayclydeTags** [WordPress/gutenberg#64234]
## What problem does this address?
Currently, the WordPress columns block does not provide a way for theme developers to easily target different numbers of columns with specific responsive styles. The existing responsive behavior is uniform across all columns, regardless of the number of columns in the block. This limitation reduces the flexibility for developers to create responsive designs that adapt based on the specific number of columns.

## What is your proposed solution?
Add a class to the columns block that indicates the number of columns, such as wp-block-columns-2, wp-block-columns-3, wp-block-columns-4, and so on. This would allow theme developers to create custom responsive styles tailored to the exact number of columns in use. This approach would provide greater flexibility for designing block themes and patterns, enabling more precise control over the appearance and behavior of column blocks on different screen sizes.

Example from Genesis Blocks
![columns count](https://github.com/user-attachments/assets/c6e31575-0ab3-40b6-901a-6631799d1da0)

**Comment by Mamaduka** [comment]
@jayclydeTags, you can use the [`:nth-child()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) pseudo element in CSS to target specific Column blocks.

**Comment by Mamaduka** [comment]
I'm going to close this request in favor of using the [`:nth-child()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) pseudo-element.

## Why?
* Using a pseudo-element is no different than using a particular class from a CSS perspective.
* The `:nth-child()` will work across multiple WP versions.

**Comment by jayclydeTags** [comment]
@Mamaduka apologies for the delayed response.

Using `:nth-child()` is not a suitable solution for creating responsive controls for the Columns block.

A column count class like `.wp-block-columns-4 .wp-block-columns-6` etc. would be a valuable addition to the Columns block. It would provide a clear and concise way to identify the number of columns in a given block, making it easier for developers to style and manipulate the layout.

Key benefits of a columns count class:
- Responsive design: The block can automatically adapt to different screen sizes based on the specified column count.
- Theme developer flexibility: Themes can create pre-defined layouts and integrate responsive behavior seamlessly.

Incorporating a column count class into the Columns block will greatly improve the overall user experience and empower theme developers to create more versatile and responsive designs.

**Comment by Mamaduka** [comment]
@jayclydeTags,

Can you share an example of CSS and column block markup (you can use the code editor to copy it) where `:nth-child()` is not applicable?

**Comment by jayclydeTags** [comment]
`:nth-child()` is primarily used to target specific children within a container, but it may not always align with responsive design needs, especially with block-based layouts.

For example, in a pricing table with multiple columns, you might want to emphasize one column. While `:nth-child()` can style a specific column, it doesn't control responsiveness effectively.

In our block-based projects, we often override the default column responsiveness to better suit our designs. For instance, if a 4-column layout defaults to stacking at a max-width of `781px`, this might be too soon. Instead, you could use custom classes to maintain a 2-column layout until the screen size is smaller. This gives us more control over the design and ensures it looks good on all devices.



| Laptop | Tablet | Mobile |
| --- | --- | --- |
| ![image](https://github.com/user-attachments/assets/767df1b2-92aa-4722-9795-ac958b4f24ac) | ![image](https://github.com/user-attachments/assets/592565a5-c5f0-4218-8e32-666219f18d85) | ![image](https://github.com/user-attachments/assets/997453ab-d01a-4a4c-8e1d-9ee50dd0c577) |

here's my sample CSS

```
@media screen  and (max-width: 992px) {
	.wp-block-columns-4,
	.wp-block-columns-6 {
		--gap: var(--wp--preset--spacing--md);
		flex-wrap: wrap !important;
	}
	.wp-block-columns.wp-block-columns-4 > .wp-block-column {
		flex-basis: calc(calc(100% / 2) - var(--gap)) !important;
	}

	.wp-block-columns.wp-block-columns-6 > .wp-block-column {
		flex-basis: calc(calc(100% / 3) - var(--gap)) !important;
	}
}


@media screen  and (max-width: 600px) {
	.wp-block-columns.wp-block-columns-4 > .wp-block-column {
		flex-basis: 100% !important;
	}

	.wp-block-columns.wp-block-columns-6 > .wp-block-column {
		flex-basis: calc(calc(100% / 2) - var(--gap)) !important;
	}

	.wp-block-columns > .wp-block-column:nth-child(even) {
		background: red;
	}
}
```

HTML:
![image](https://github.com/user-attachments/assets/102fd425-e81e-4be3-b05c-1fc6c9f6eddb)

**Comment by hbhalodia** [comment]
Hi @jayclydeTags @Mamaduka, I have raised the PR for the same - https://github.com/WordPress/gutenberg/pull/64427, please take a look on the PR.

Thank You,

**Comment by huubl** [comment]
Related: https://github.com/WordPress/gutenberg/issues/42523

**Comment by t-hamano** [comment]
It's a bit complicated, but you can target a Column block with a specific number of columns using a selector like this. `N` is the number of columns:

```css
.wp-block-columns:has(> .wp-block-column:nth-child(N):last-child) {
}
.wp-block-columns:has(> .wp-block-column:nth-child(N):last-child) .wp-block-column {
}
```

**Comment by skorasaurus** [comment]
Thank you for reporting and including all of the detailed use cases and screenshots. 

There is another issue which already covers this at https://github.com/WordPress/gutenberg/issues/42523, so to keep the issues repository easier to search and keep track of existing issues, I'm closing this issue. 

Again, thank you for your effort; and please share your thoughts in that issue
