### ISSUE TITLE
Image Block: Allow drop-to-replace for existing image blocks

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#6424]
## Issue Overview
I'm working up the layout for a page, I duplicated a set of blocks with an image on the left and some text on the right. My hope was that I could just drop images from my desktop to replace the duplicated image blocks, but it doesn't work.

## Steps to Reproduce

1. Add an image block and choose an image
2. Drag an image from your desktop overtop of the image block added in step 1.
3. Notice that you can't replace the existing image, but rather add a new image.

Safari (Version 11.1)

## Expected Behavior

I expected that I could drop an image on top of an existing image block and replace that image. Here's how it works in Keynote:

![keynote-drop-image](https://user-images.githubusercontent.com/191598/39257213-fe27c5ea-487e-11e8-8362-da1400717d7d.gif)

## Current Behavior

Right now its all sorts of wonky, here's a gif of what I experienced:
![image-drop-to-upload](https://user-images.githubusercontent.com/191598/39257228-08320046-487f-11e8-9830-71f76f2c082c.gif)

Since I have the existing image block set to left align, the inserter around the text blocks activates and tries to get me to add a new image block. You'll also notice that there's some weird white text appearing when holding an image over the editor canvas.

If I drop the image, I get some really messed up stuff:

<img width="596" alt="screen shot 2018-04-25 at 11 53 17 am" src="https://user-images.githubusercontent.com/191598/39257333-43d7b9d8-487f-11e8-8783-b6159fe73f0f.png">

**Comment by shaunandrews** [comment]
Another thought here: Maybe dropping an image on an existing image should create a gallery? I'm not sure thats what I'd expect, but I could see the gallery transformation being (maybe) more useful and common than replacing an image.

**Comment by karmatosed** [comment]
Oh that's a good idea! I think that having if you place an image on another if it became a gallery this would be what someone would expect.

Marking as enhancement as it is but this could be really nice and a moment of delight for a user.

**Comment by karmatosed** [comment]
🤔 my initial thoughts are against an option here but we are making an assumption so need to check if that is a good idea or not. I'd not be against this until we knew at least which was the most common wanted.

**Comment by richtabor** [comment]
Is this still relevant?

**Comment by paaljoachim** [comment]
I just tested.
This works in version 13.11 of Safari on my Mac running OSX 10.15.5.
