### ISSUE TITLE
Zoom Out: "Desktop (50%)" view hides breadcrumbs and doesn't work in non-iframe editor

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#64259]
### Description

There seem to be two issues with the "Desktop (50%)" view introduced in #63870:

- ~~The block breadcrumbs is hidden~~ This appears to be the expected behavior, see [this comment](https://github.com/WordPress/gutenberg/pull/63870#issuecomment-2269181015).
- Doesn't work in non-iframe editor

### Step-by-step reproduction instructions

- Open the post editor.
- Click the View button and Select "Desktop (50%)"
- The block breadcrumbs should be hidden.
- Enalbe Custom fields.
- Click the View button and Select "Desktop (50%)"
- Nothing should happen.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/6e889f10-1b75-416f-aab4-35c6ef523563

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by stokesman** [comment]
> * Doesn't work in non-iframe editor

I made #62943 regarding that. I imagined that the iframe would have to be forced if when Zoom Out is engaged which if possible would seemingly also fix this.
