### ISSUE TITLE
Dropping images into a new document is finicky

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#6426]
## Issue Overview
I love dragging and dropping an image from my desktop to the editor, but it takes a little finesse to get it to work sometimes. There's also a little learning curve involved to understand just where and when you can drag-and-drop an image.

![where-to-drop](https://user-images.githubusercontent.com/191598/39258165-4e802a8a-4881-11e8-97fd-effb6e979950.gif)

## Expected Behavior

I expected a bigger indicator of where I could drop images. Once I found that I could only drop above the first text block (below the title), I was able to upload my image, but I then had to move it down below the text block later.

**Comment by karmatosed** [comment]
I would say it not working is a bug so lets tighten this up a little. What browser were you using? Just incase that is impacting here (I've seen it better in some browsers).

**Comment by shaunandrews** [comment]
Safari (v11.1)

**Comment by eliorivero** [comment]
Repro in Chrome 67.0.3396.79 on High Sierra.

**Comment by mtias** [comment]
You have to hover the editor area. The editor area is small, which seems like a separate issue.

**Comment by mtias** [comment]
Closing so that we address the small editor issue separately.
