### ISSUE TITLE
Selectable blocks should still be available in List View when zoomed out

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#64260]
Currently if you engage zoom out view, the top-level blocks you can select are no longer available within List View. I'd expect that selectable blocks would be available in List View, even when zoomed out. 

https://github.com/user-attachments/assets/567c6c01-348e-4465-afe9-cdabf2be049e

Related: https://github.com/WordPress/gutenberg/pull/63870.

**Comment by cat-og** [comment]
I found that similarly, the Header and Footer blocks also disappear from the List View if you add a new pattern while zoomed out. 

Unlike the selectable elements, these blocks did not reappear after returning to standard zoom. 

https://github.com/user-attachments/assets/c2ca34d7-b675-4340-be42-913e9486383a

**Comment by getdave** [comment]
> I found that similarly, the Header and Footer blocks also disappear from the List View if you add a new pattern while zoomed out.

This seems to be because `getEnabledClientIdsTreeUnmemoized` checks for blocks whose `blockEditingMode` is `disabled` and if so then doesn't include in the clientIds passed to List View.

We can't make an exception here so we need to decide if locking template parts is the correct choice in Zoom Out.

**Comment by richtabor** [comment]
> decide if locking template parts is the correct choice in Zoom Out.

Now that it is possible to select and edit the header from page editing as well, it could be fine to have the same while zoomed out.

**Comment by getdave** [comment]
https://github.com/WordPress/gutenberg/pull/65202 will fix the List View for Zoomed Out. The Header/Footer bit would need another PR.
