### ISSUE TITLE
lodash dependency

### ISSUE THREAD

**Issue by theleemon** [WordPress/gutenberg#6427]
## Issue Overview

Just a small question. Is it required to bundle the lodash lib in our block plugins that make use of lodash functions or can we use the already loaded by Gutenberg lib? Although I'm adding the lodash lib as a dependency in my plugin, I'm getting a `ReferenceError: pick is not defined` console error. 
I don't know what I'm doing wrong. Any ideas?

Thanks in advance

```
function register_block() {
        wp_register_script(
            'gutenberg-slider',
            plugins_url( 'block.build.js', __FILE__ ),
            array( 'wp-blocks', 'wp-components', 'wp-element', 'wp-utils', 'lodash' )
        );

        register_block_type( 'my/slider', array(
            'editor_script' => 'gutenberg-slider',
        ) );
}

**Comment by theleemon** [comment]
This is the snippet that calls the `pick` function:

```
onSelectImages( images ) {
    this.props.setAttributes( {
        images: images.map( ( image ) => pick( image, [ 'alt', 'caption', 'id', 'url' ] ) ),
    } );
}
```

But I've found that I can "import" the `pick` function in the following way and now it seem to work as expected:

`const { pick } = lodash;`

So you can close this issue.

**Comment by gziolo** [comment]
Yes, this is how it should be done. I'm glad you were able to find the solution 👍
