### ISSUE TITLE
Invalid param check/warning: `variation` can be array

### ISSUE THREAD

**Issue by musawirali** [WordPress/gutenberg#64279]
https://github.com/WordPress/gutenberg/blob/96cca231cd6b9ce56c94a3dc098016ba6eddefce/packages/blocks/src/api/registration.js#L729

**Comment by ramonjd** [comment]
Hi! 

Could you provide an example of how to reproduce? 

E.g., when a variation could be an array?

I'm looking at the [WPBlockVariation](https://github.com/WordPress/gutenberg/blob/78a3e71ec3ff85944324c99b4128d6cb5cac5542/packages/blocks/src/api/registration.js#L64-L63) type, and it specifies an object.

**Comment by ramonjd** [comment]
I'll close this issue for now. If there's more info, please feel free to reopen. Thank you!
