### ISSUE TITLE
TinyMCE's `.inline-boundary` background color rendering text unreadable in certain cases

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#6429]
## Issue Overview

Not sure if this is TinyMCE related issue or can be taken care of in Gutenberg, but `.inline-boundary` CSS class text gets unreadable when certain colors used on the block:

![Rendering unreadable text with inline boundary in Gutenberg UI](http://easycaptures.com/fs/uploaded/1115/7765742408.png)

## Possible Solution

Making `.inline-boundary` class background color semi-transparent?

**Comment by danielbachhuber** [comment]
Thanks for the report, @webmandesign.

Flagging this as `Needs Design Feedback` to see if there's a reasonable CSS fix we can apply. If not, I think it's safe to consider this an edge case we won't fix.

**Comment by karmatosed** [comment]
If it could add a transparency but I think this could be a won't fix in this case. Going to flag it as has design feedback.

**Comment by mtias** [comment]
If there's a color set we should probably not use the color bg boundary or switch it to the one being worked on in https://github.com/WordPress/gutenberg/pull/6577

**Comment by mtias** [comment]
Should have been fixed with #10623
