### ISSUE TITLE
Sort order for categories.

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#643]
This is tied in with the inserter menu.  What do we want the default sort order to be for the categories and blocks in those categories?  This mainly becomes a concern when other plugins will be able to register blocks and categories.

**Comment by BE-Webdesign** [comment]
Also important to this topic is whether we want categories to be a one to one relationship or a one to many.

**Comment by aduth** [comment]
>one to one relationship or a one to many relationship for blocks.

What's the use case for one-to-one ?

**Comment by BE-Webdesign** [comment]
`one to one` is what we have right now for blockType => category and it is one to many for category => blockType.  If we keep a blockType to only belonging to one category it will keep the ordering simple and displaying the blockTypes simple in the inserter, or wherever else we need to display blockTypes.  But there could be a reason to assign multiple categories as an array i.e. Common and Media for image, video etc.  If we go one to many we would want to do something like:

```js
registerBlock( {
  namespace: core,
  name: embed,
  categories: [ 'common', 'media' ]
} );
```

**Comment by mtias** [comment]
We don't want a block to belong to multiple categories, at least for now. There's a PR to allow creating new categories. It's likely we could assign a plugin-block that hasn't specified a category to be under a "Plugins" category. Same for themes.
