### ISSUE TITLE
Alignment classes aren't applied to blocks in the editor. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#6430]
## Issue Overview

In the frontend, blocks are assigned classes to specify their alignment setting (`alignleft`, `alignwide`, etc.):

<img width="377" alt="screen shot 2018-04-25 at 1 12 58 pm" src="https://user-images.githubusercontent.com/1202812/39261538-c7406d14-488a-11e8-8e9b-be1f980fca49.png">

---

These classnames don't appear in the editor though. Instead, for some blocks the alignment settings can be detected only by observing the `data-align` attribute a couple levels up.

<img width="924" alt="screen shot 2018-04-25 at 1 11 15 pm" src="https://user-images.githubusercontent.com/1202812/39261546-d068f5e6-488a-11e8-96d7-05899399d9ca.png">

When writing a theme's editor styles, this forces you to hook into the data attribute, instead of just using a classname like in the frontend. 

---

For other blocks — like the quote block — the alignment setting is just recorded using an inline `text-align` value. In this case, it's impossible for a theme's editor styles to hook into and customize that block depending on its alignment. 

![alignment](https://user-images.githubusercontent.com/1202812/39305402-fe17dee4-492a-11e8-88d1-cadc78562ad6.gif)

---

Ideally, we should use the alignment classnames for consistency.

**Comment by karmatosed** [comment]
I was fairly sure this was an existing issue but it turns out I can't find it! Good catch and we should see about making this consistent.

**Comment by benhuson** [comment]
Similarly for heading blocks, would be nice to have an alignment class rather than just hardcoded `text-align`.

**Comment by mtias** [comment]
We use the `data-align` property for styling as it has to apply to the wrapper element.
