### ISSUE TITLE
Cannot add Comments Form to Page Template

### ISSUE THREAD

**Issue by dmsnell** [WordPress/gutenberg#64311]
## What problem does this address?
It appears as though the editor does not allow adding comments to a Page template. The comments block is not in the list of available blocks, and when manually added, is restricted from moving around, adding inside a group, etc…

Everything is allowed by manually entering the serialized block markup in the text editor of the page template, and things work on the rendered front-end.

## What is your proposed solution?

If comment blocks are explicitly and arbitrarily limited to Post templates, don't do this. Comments on Pages and other post types is allowable and normative.

Possibly related to #53188

**Comment by t-hamano** [comment]
In my environment, I was able to insert the Comments Fomr block in the Page template in the site editor.

Is there a way to reproduce this issue?

![image](https://github.com/user-attachments/assets/885b9a58-fbfd-4b43-8411-c82fc66b248c)

**Comment by dmsnell** [comment]
Thanks @t-hamano – I double-checked and on a vanilla installation I was able to add the comments block. On my WordPress.com site, however, it's missing; I'm not sure what's preventing that.

Closing for now, since this is not an issue with WordPress itself, or Gutenberg.
