### ISSUE TITLE
Block right controls incorrectly float above Gutenberg toolbar

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#6432]
If I hover over a block that's immediately under the Gutenberg toolbar, its right block controls hover over the toolbar:

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/36432/39264667-4c544720-487a-11e8-93b9-099580f061d6.png">

I'd expect them to be underneath (or not appear at all).

**Comment by nfmohit** [comment]
Hi @danielbachhuber !

Is there a specific scenario where I could replicate this issue? Perhaps a specific browser or OS? Or a specific block?

I cannot seem to replicate this issue, here's a screenshot:
![1](https://user-images.githubusercontent.com/20284937/39511868-c5cb2aba-4e10-11e8-845a-2f0b77c6e057.png)

I'm testing in Chrome Version 66.0.3359.139 in MacOS 10.13.4. Please let me know if I'm missing something.

**Comment by danielbachhuber** [comment]
> I cannot seem to replicate this issue, here's a screenshot:

I can no longer reproduce either. I've tested both Gutenberg 2.7 and master in both Firefox Quantum and Chrome.

My original test was in Firefox Quantum. I don't recall whether it was Gutenberg 2.7 or master though.

Next time I need to include more environment details!
