### ISSUE TITLE
Text alignment is inconsistent

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#6433]
For paragraph blocks its easy to center text, I can just click on the icon that appears when I select the block:

<img width="659" alt="screen shot 2018-04-25 at 2 39 20 pm" src="https://user-images.githubusercontent.com/191598/39265972-b007ebc0-4896-11e8-8e7c-0336bd0cd78c.png">

But for heading blocks those buttons don't show:

<img width="667" alt="screen shot 2018-04-25 at 2 39 35 pm" src="https://user-images.githubusercontent.com/191598/39266100-09f0c0d0-4897-11e8-8c03-d3adcfd8809d.png">

However I dug in a little and found that I can change the alignment in the sidebar:

<img width="130" alt="screen shot 2018-04-25 at 2 39 42 pm" src="https://user-images.githubusercontent.com/191598/39266120-1454b05e-4897-11e8-9917-3948a23d263b.png">

But then I came upon the subhead block, which neither has the buttons when selector nor in the sidebar:

<img width="679" alt="screen shot 2018-04-25 at 2 39 48 pm" src="https://user-images.githubusercontent.com/191598/39266138-2863808e-4897-11e8-81e1-8408e51072fb.png">

<img width="276" alt="screen shot 2018-04-25 at 2 39 53 pm" src="https://user-images.githubusercontent.com/191598/39266144-2aa2d8ea-4897-11e8-8706-9e576674e18c.png">

--

There's lots of little inconsistencies like this across blocks. I find it makes learning how to use the Gute harder—essentially I have to learn how to use each block, rather then learning transferable lessons from block-to-block.

**Comment by jasmussen** [comment]
Thanks for the report, Shaun. I happen to agree. This has also been discussed in #3785, so closing as a duplicate. I'll also update that other ticket to show the latest mockups up top.
