### ISSUE TITLE
Support Disabling the Duplication of Template Parts

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#64344]
## What problem does this address?

Our hybrid theme supports 2 native Template Parts that users can edit, but we disable the Template Part Block in editor contexts (as we aren't a block-based theme).  6.6 allows users to duplicate Template Parts.  Unfortunately, that results in a very confusing situation in our environment, because now there is a Template Part that can be edited, but literally cannot be used anywhere.

## What is your proposed solution?

Support disabling the ability to duplicate Template Parts. An easy method is some kind of settings/filter that can be used.

**Comment by t-hamano** [comment]
Thanks for the report.

> there is a Template Part that can be edited, but literally cannot be used anywhere.

This is true. The only thing allowed in a hybrid theme should be editing the template parts the theme provides. Other actions (Duplicate, Delete, Rename) should not be allowed.

I'm going to label this issue as a bug.

**Comment by MadtownLems** [comment]
Thank you for the quick work here! If this was confirmed as not just a bug, but a regression, is there any chance of backporting it into something like 6.6.2?

**Comment by t-hamano** [comment]
This issue is a regression that occurred in WP6.6, so it might be worth adding to the list of candidates for a minor release. Just to be on the safe side, I'll add #64379 to the list of candidates.
