### ISSUE TITLE
DataViews - layout icon still shows with 1 layout, with empty context menu

### ISSUE THREAD

**Issue by Zealth57** [WordPress/gutenberg#64359]
### Description

When using the new dataviews component, if you try to set the 'view' to only have 1, the icon still shows up. When you click the icon, the exposed context menu is blank. If you only have 1 view, that icon should automatically be hidden. 

### Step-by-step reproduction instructions

- create a dataview table
- only set 'table' as a view, don't allow grid or any other views.
- observe that the view change icon is still visible but clicking it does effectively nothing.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by renishsurani** [comment]
Hi @Zealth57, can you please provide a screenshot or video for reference?

**Comment by Zealth57** [comment]
This must have been fixed in 4.1.0 released 17h ago as I'm able to replicate on 4.0.0 but not on 4.1.0. Looks like quite a few things changed with the UI controls for that and the filters so someone must have been tracking this already. Closing this for now as it seems okay.
