### ISSUE TITLE
Embed blocks: adding captions via toolbar

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#64385]
Some blocks, like audio and image, allow toggling captions on/off via the block toolbar:

<img width="745" alt="Screenshot 2024-08-09 at 09 46 46" src="https://github.com/user-attachments/assets/380cee7b-2f42-407a-9b6b-91d8d383c020">
<img width="552" alt="Screenshot 2024-08-09 at 09 47 02" src="https://github.com/user-attachments/assets/64f1939c-c969-4c91-81f9-582c411302c3">

Meanwhile, embed blocks always have a caption visible with a placeholder nudge to "add caption" when selected:

<img width="692" alt="Screenshot 2024-08-09 at 09 46 17" src="https://github.com/user-attachments/assets/c52a53ce-9312-4764-907f-a0c21d5acd28">

https://github.com/user-attachments/assets/3b539780-2947-4bae-87b9-1d210f477ae0

I'd expect all the media blocks to support captions via the toolbar only, leaving the canvas clean when switching between blocks, less content-jumping when selecting blocks, and better overall consistency.

**Comment by hbhalodia** [comment]
Hi @simison, I would like to work on this issue and would raise the PR for the same.

Thank You,

**Comment by hbhalodia** [comment]
Hi @simison @andrewserong @t-hamano, I have raised the PR to make the embed block consistent as per the issue mentioned - https://github.com/WordPress/gutenberg/pull/64394

Thank You,
