### ISSUE TITLE
Add Block: WordPress Embed

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#644]
Looking at the WordPress Embed block. If we keep a similar design to what is currently active in Core, we can create a block that should look something like this. Let's discuss.

Also to note, the block automatically takes this design as soon as the Editor realizes this URL is for another WP site. As soon as a URL is pasted into the block, it converts to this layout.

**Neutral:**
![wordpress embed-neutral](https://cloud.githubusercontent.com/assets/617986/25686749/909ff000-3025-11e7-8033-bc6ca90dd769.png)

**Hover:**
![wordpress embed-hover](https://cloud.githubusercontent.com/assets/617986/25686766/ada5c562-3025-11e7-960c-7c2105280ce6.png)

**Selected**
![wordpress embed-selected](https://cloud.githubusercontent.com/assets/617986/25686771/b3daa5e2-3025-11e7-9bfc-ad505501e0c7.png)

**User click to embed on own site:**
![wordpress embed-embed](https://cloud.githubusercontent.com/assets/617986/25686786/c66e2670-3025-11e7-831e-086ae09f09ae.png)

**Comment by kopepasah** [comment]
If no one is working on this, I will take it over.

**Comment by jasmussen** [comment]
I'm closing this in favor of #1034, and because the embed block as inspired by this is in!
