### ISSUE TITLE
Serialisation breaks namespaced attributes like `xlink:href`

### ISSUE THREAD

**Issue by roborourke** [WordPress/gutenberg#6441]
## Issue Overview

In version 2.7.0 I'm seeing inline SVGs break that make use of the `xlink:href` attribute. It gets rewritten as `xlinkhref`.

## Steps to Reproduce (for bugs)

1. Create a block that outputs a tag from the `save` property with a namespaced attribute eg. `xlink:href`
2. Save the post
3. Check the markup when viewing the page, `xlink:href` is now `xlinkhref`

Chrome latest on OSX High Sierra.

## Expected Behavior

Namespaced attributes should be preserved.

## Current Behavior

Namespaced attributes are sanitised / serialised incorrectly.

## Possible Solution

Consider the need for `fast-react-render` lib based on it being deprecated.

Alternatively add support for known valid namespaced attributes and handle them in the `getNormalAttributeName()` function of `element/serialize.js`.

## Todos
- [x] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Latest from PR https://github.com/WordPress/gutenberg/pull/6445#issuecomment-385963154

> Ultimately, I think it would be good to have the compatibility, if only to avoid surprises from developers (such as yourself) who are led to believe they are targeting React, particularly when it works in the client-rendered variant.
> 
> A good next step might be to identify the minimal set of these properties that React supports which won't be serialized well in our implementation. From there we can either determine to create a mapping, or generalized logic for converting.

**Comment by aduth** [comment]
I've closed #6445 and the milestone has been updated to reflect the fact that this likely won't be changed for 5.0.

The main issue here is managing expectations as it relates to targeting React. React's treatment of these attributes, however, is non-standard, based neither on HTML attribute nor DOM property namings.

In the interim, it should be made clear that providing attributes as they'd be named in the markup (e.g. `xlink:href`) _is_ supported by `@wordpress/element` serialization (and, in fact, [React itself](https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html)), and can serve as a "workaround" of sorts until a decision can be met for how best to interoperate with React.

**Comment by roborourke** [comment]
Thanks @aduth, sorry I'd completely let this drop off my radar. Because it's such a specific thing to what I was working on I think I'm better off reworking the SVG webpack loader and contribute to that instead. Once I have that piece sorted I can contribute an FAQ to the docs if that's the right place for it.

I'll close this issue out in favour of #11805 for directly documenting any incompatibilities with react and best practices for those.

**Comment by jlambe** [comment]
@aduth I'm currently experiencing the same issue in building custom blocks with the loaded version of Gutenberg in WordPress 5.4.1.

From React, the `xlink:href` attribute is supported if it is written as `xlinkHref`. Based on above comments, I also tried to create a `<use xlink:href="#icon"/>` tag using the `createElement` function from the `@wordpress/element` package.

I've done two tests to work around this:
First by definig the attribute name as in "html":

```jsx
const xref = createElement('use', {
    'xlink:href' => '#icon'
});
```

The results from a call in the block `save` method, is that the html tag is properly registered in the post_content as `<use xlink:href="#icon"/>`. The problem, is that React complains that the attribute is not valid and break the display when working in the editor. React is even suggesting to use `xlinkHref` as an attribute.

Second trial with the below code using the React attribute name:

```jsx
const xref = createElement('use', {
    'xlinkHref': '#icon'
});
```

Results, React is no longer complaining on the post edit screen but the html tag is not correctly saved in the `post_content`. The results of using the recommended syntax from React are that the `:` are removed from the attribute name, storing this value: `xlinkhref="#icon"`.

Currently I haven't found any right solution to properly use SVG xlink attributes with the editor. I even looked at the `@wordpress/primitives` package to see if there are any enhanced components for SVG but I wasn't able to find one for this case.

**Comment by jlambe** [comment]
@aduth For the record, the only workaround at the moment if we need to use svg elements with the `xlink:href` attribute on the block `save` function is to return `null` and specify a render callback for it so we can manage its output from HTML. Making it a "dynamic" block.

**Comment by aduth** [comment]
>The problem, is that React complains that the attribute is not valid and break the display when working in the editor. React is even suggesting to use xlinkHref as an attribute.

Is it just warning? Or does it not actually apply the attribute? My understanding (and testing) is that the attribute should still be applied, even if it complains about it ([related](https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html)). Certainly not ideal of course.

I think the longer-term solution is to either enhance the custom `@wordpress/element` serializer to support these DOM attributes ([prior art](https://github.com/WordPress/gutenberg/blob/2881f84896cace4cc1828774c8e09252d9e67e39/packages/element/src/serialize.js#L285-L302)), or drop the custom serializer altogether.

> @aduth For the record, the only workaround at the moment if we need to use svg elements with the `xlink:href` attribute on the block `save` function is to return `null` and specify a render callback for it so we can manage its output from HTML. Making it a "dynamic" block.

For `save`, you could also consider `@wordpress/element`'s `RawHTML`, the equivalent to [React's `dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml), which should take any HTML string you give it, regardless whether it considers it valid or not.

**Comment by jlambe** [comment]
@aduth It is a triggered error for the invalid attribute but not blocking the process. Looking at source, updating the serializer seems a small and easy fix, at least in a short term... For now I'm sticking with the dynamic render but I'll try to test the `RawHTML` method on a next block. Thanks for the recommendation ;)
