### ISSUE TITLE
Docs: Interactivity API - TypeScript snippet is used in the sample.

### ISSUE THREAD

**Issue by atachibana** [WordPress/gutenberg#64418]
### Description

Actions section of 'Elements of the store' is using TypeScript snippet.
https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/interactivity-api/api-reference.md
Can we use TypeScript snippet without any notice? How do we implement it in `view.js`?

```ts
const { state, actions } = store("myPlugin", {
  actions: {
    selectItem: (id?: number) => {
      const context = getContext();
      // `id` is optional here, so this action can be used in a directive.
      state.selected = id || context.id;
    },
    otherAction: () => {
      // but it can also be called from other actions.
      actions.selectItem(123); // it works and type is correct
    }
  }
});
```

### Step-by-step reproduction instructions

Refer https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/interactivity-api/api-reference.md

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by luisherranz** [comment]
Yes, TypeScript can be used to type stores. There isn’t specific documentation yet, but we are working on a series of new guides for a [new section called Core Concepts](https://github.com/WordPress/gutenberg/pull/63759), and I think we could include one there about TypeScript. I have added it to the [tracking issue](https://github.com/WordPress/gutenberg/issues/62921).

Meanwhile, if you want, you can take a look at this [old discussion](https://github.com/WordPress/gutenberg/discussions/53586), which explains some aspects of how the Store of the Interactivity API works, including how it can be typed.

I have opened a pull request to delete the typing:

- https://github.com/WordPress/gutenberg/pull/64429
