### ISSUE TITLE
404 error while inspecting site. Looks all broken after update

### ISSUE THREAD

**Issue by Thomas328** [WordPress/gutenberg#64424]
### Description

When i click show page in the top right the whole site is broken and i get a 404 when inspecting. See error code below.
This started after the 2.0.0 update

### Step-by-step reproduction instructions

Navigate to site https://bmxsport.nl

### Screenshots, screen recording, code snippet

Uncaught TypeError: Cannot read properties of undefined (reading 'hooks')
    at Object.<anonymous> (frontend.js?ver=2.0.0:1:24711)
    at n (frontend.js?ver=2.0.0:1:110)
    at Module.<anonymous> (frontend.js?ver=2.0.0:1:299301)
    at n (frontend.js?ver=2.0.0:1:110)
    at frontend.js?ver=2.0.0:1:902
    at frontend.js?ver=2.0.0:1:912
3997f130727f3304?embed=18b6a41b-6d32-42ce-90a1-4645f3f8e174&redirectToOypo=false&hideHeaderImage=true:264 [.NET]
gutenverse-template-page-915270.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()

### Environment info

Version 6.1.1 WP
Newest gutenverse as of writing including newest gutenverse form

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by hanneslsm** [comment]
This seems more likely to be an issue with Gutenverse rather than Gutenberg. You can ask for help in their support forum: https://wordpress.org/support/plugin/gutenverse/
