### ISSUE TITLE
Getting An Error When Compiling Scripts using wp-scripts

### ISSUE THREAD

**Issue by LaTableRouge** [WordPress/gutenberg#64446]
Hello,

I'm currently writing a plugin with multiple react blocks inside.

## Environment info
- Wordpress Version 6.6.1
- @wordpress/scripts 28.5.0
- [package.json](https://github.com/LaTableRouge/Mappps/blob/experimental/blockcohabitation/package.json)

## Description
Here's how it's organized : 
![image](https://github.com/user-attachments/assets/753f4041-956a-415c-bdcc-34309c9387f6)

For all thoses blocks I use the command: `wp-scripts build --webpack-src-dir=blocks/src --output-path=blocks/build`

The blocks are registered like so: https://github.com/LaTableRouge/Mappps/blob/experimental/blockcohabitation/includes/blocks/blocks-register.php

Some blocks are using the same leaflet package ([this one](https://www.npmjs.com/package/@changey/react-leaflet-markercluster))

When there was only one block using this package, everything went fine. But as soon as there was two of them using it, I went through an error. If I compile only one block that use this package it works (doesn't matter which one).
Here's the error: 
```
TypeError: L.MarkerClusterGroup is not a constructor
    markerClusterGroup leaflet.markercluster-src.js:1409
    node_modules index.js:11
    useImmutableLeafletElement element.js:13
    usePath path.js:22
    ContainerComponent component.js:6
    hu react-dom.min.js:2
    wo react-dom.min.js:2
    xi react-dom.min.js:2
    bs react-dom.min.js:2
    vs react-dom.min.js:2
    gs react-dom.min.js:2
    as react-dom.min.js:2
    is react-dom.min.js:2
    Hl react-dom.min.js:2
    ws react-dom.min.js:2
    ws react-dom.min.js:2
    ls react-dom.min.js:2
    S react-dom.min.js:2
    T react-dom.min.js:2
    463 react-dom.min.js:2
    t react-dom.min.js:2
    982 react-dom.min.js:2
    t react-dom.min.js:2
    551 react-dom.min.js:2
    t react-dom.min.js:2
    961 react-dom.min.js:2
    t react-dom.min.js:2
    <anonymous> react-dom.min.js:2
    <anonymous> react-dom.min.js:2
react-dom.min.js:2:71400
```

I don't know if it's a problem from the package in itself, but it seems unlikely. My hypothesis is that is from a lack of scoping from the `wp-scripts`

I found theses issues that seems to have the same problem, but without success for my problem:
- [#23607](https://github.com/WordPress/gutenberg/issues/23607)
- [#36926](https://github.com/WordPress/gutenberg/issues/36926)

I'm a bit stuck and I didn't found where to put this issue haha.

**Comment by LaTableRouge** [comment]
Some news, 
I tried a bunch if things to resolve this problem.
About the error "TypeError: L.MarkerClusterGroup is not a constructor" It seems to be linked to the `leaflet-geosearch` package. 
It's called in multiple blocks on my project, I only left only one call of this package.
Now I have another error I still think it's because of a **lack of scoping** when compiling the blocks.
Here's the new error: 
```
TypeError: can't access property "lat", ne2 is undefined
    intersects leaflet-src.js:1385
    _recursively leaflet.markercluster-src.js:1804
    _recursivelyAddChildrenToMap leaflet.markercluster-src.js:1686
    process leaflet.markercluster-src.js:299
    addLayers leaflet.markercluster-src.js:305
    onAdd leaflet.markercluster-src.js:647
    _layerAdd leaflet-src.js:6897
    whenReady leaflet-src.js:4590
    addLayer leaflet-src.js:6955
    addLayer layer.js:9
    ri react-dom.min.js:2
    Ss react-dom.min.js:2
    ws react-dom.min.js:2
    ws react-dom.min.js:2
    is react-dom.min.js:2
    Hl react-dom.min.js:2
    ws react-dom.min.js:2
    ws react-dom.min.js:2
    ls react-dom.min.js:2
    S react-dom.min.js:2
    T react-dom.min.js:2
    463 react-dom.min.js:2
    t react-dom.min.js:2
    982 react-dom.min.js:2
    t react-dom.min.js:2
    551 react-dom.min.js:2
    t react-dom.min.js:2
    961 react-dom.min.js:2
    t react-dom.min.js:2
    <anonymous> react-dom.min.js:2
    <anonymous> react-dom.min.js:2
react-dom.min.js:2:71400
```

**Comment by miminari** [comment]
@LaTableRouge Thank you for report, but your package.json link is 404 now. [Your repo](https://github.com/LaTableRouge/Mappps) seems to update now. If you clear your issue, please tell us. Or not, please tell your package.json file.

**Comment by LaTableRouge** [comment]
@miminari I'm sorry I forgot that Github doesn’t handle links redirection....
I've updated the links on the first comments.
I still have an issue when compiling.

**Comment by LaTableRouge** [comment]
I made a separated branch with the error. It's more clean that way. I've edited the first message in this thread to redirect the links to the branch. :)

**Comment by LaTableRouge** [comment]
I did reply and gave more informations.

**Comment by LaTableRouge** [comment]
I did reply and gave more informations.

**Comment by miminari** [comment]
Hi, thank you for sharing.
OK, your package.json is so complex that I would test the simple one for multiple block building.

# Steps
1. 
```bash
npx @wordpress/create-block test-block-bug
cd test-block-bug
```
2. Make files for 2 blocks in src dir like below:
```
├── src
│   ├── block01
│   │   ├── block.json
│   │   ├── edit.js
│   │   ├── editor.scss
│   │   ├── index.js
│   │   ├── save.js
│   │   ├── style.scss
│   │   └── view.js
│   └── block02
│       ├── block.json
│       ├── edit.js
│       ├── editor.scss
│       ├── index.js
│       ├── save.js
│       ├── style.scss
│       └── view.js
```
3. Update the title and name of the block.json files like below:

block01/block.json
```json
"name": "create-block/test-block-bug",
"title": "Test Block Bug 01",
```

block02/block.json
```json
"name": "create-block/test-block-bug2",
"title": "Test Block Bug 02",
```

4. Add and change the path to these blocks in the php file like below:
```php
	register_block_type(__DIR__ . '/build/block01/');
	register_block_type(__DIR__ . '/build/block02/');
```

5. `npm run build`
6. You will get the message like `webpack x.x.x compiled successfully in 000 ms`
7. And you will see the blocks in the blocks list
![Image](https://github.com/user-attachments/assets/10a3b6a0-314d-4ea7-9ca7-ac9c17f5c166)

As the docs explained like blew, you might not need to change the build command for building multiple block not customizing the dir.
https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#automatic-block-json-detection-and-the-source-code-directory

I did the test by `"@wordpress/scripts": "^30.2.0"`, so you might need to update the version.

I'm sorry that I don't know about the leaflet package very well, you might be better to ask about it in the package repo.

**Comment by miminari** [comment]
Hi, thank you for sharing.
OK, your package.json is so complex that I would test the simple one for multiple block building.

# Steps

1.

```bash
npx @wordpress/create-block test-block-bug
cd test-block-bug
```

2. Make files for 2 blocks in src dir like below:

```
├── src
│   ├── block01
│   │   ├── block.json
│   │   ├── edit.js
│   │   ├── editor.scss
│   │   ├── index.js
│   │   ├── save.js
│   │   ├── style.scss
│   │   └── view.js
│   └── block02
│       ├── block.json
│       ├── edit.js
│       ├── editor.scss
│       ├── index.js
│       ├── save.js
│       ├── style.scss
│       └── view.js
```

3. Update the title and name of the block.json files like below:

block01/block.json

```json
"name": "create-block/test-block-bug",
"title": "Test Block Bug 01",
```

block02/block.json

```json
"name": "create-block/test-block-bug2",
"title": "Test Block Bug 02",
```

4. Add and change the path to these blocks in the php file like below:

```php
	register_block_type(__DIR__ . '/build/block01/');
	register_block_type(__DIR__ . '/build/block02/');
```

5. `npm run build`
6. You will get the message like `webpack x.x.x compiled successfully in 000 ms`
7. And you will see the blocks in the blocks list
   ![Image](https://github.com/user-attachments/assets/10a3b6a0-314d-4ea7-9ca7-ac9c17f5c166)

8. Add some 3rd party package like [recharts](https://recharts.org/en-US/guide/getting-started)

```bash
npm install recharts
```

9. Update the two edit.js to use the package function like below:

```js
import { LineChart, Line, CartesianGrid, XAxis, YAxis } from "recharts";
const data = [{ name: "Page A", uv: 400, pv: 2400, amt: 2400 }];

export default function Edit() {
	return (
		<LineChart width={600} height={300} data={data}>
			<Line type="monotone" dataKey="uv" stroke="#8884d8" />
			<CartesianGrid stroke="#ccc" />
			<XAxis dataKey="name" />
			<YAxis />
		</LineChart>
	);
}
```

10. Again `npm run build` and you can get new blocks like below:
![Image](https://github.com/user-attachments/assets/9d7df83c-8153-42a1-963e-ac71938c9029)


As the docs explained like blew, you might not need to change the build command for building multiple block not customizing the dir.
https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#automatic-block-json-detection-and-the-source-code-directory

I did the test by `"@wordpress/scripts": "^30.2.0"`, so you might need to update the version.

I'm sorry that I don't know about the leaflet package very well, you might be better to ask about it in the package repo.
And I feel this is not Gutenberg issue, so would like to close this. But if there is anything I have missed, please feel free to comment.

**Comment by LaTableRouge** [comment]
Thanks a lot for your time.
I've done what you said and it works... So after all it's the library that I use that is poorly made and not some scope issue.
I'll try to recontact the author of the library.

Thanks again for your time
