### ISSUE TITLE
Triple click selects multiple block in Chrome and Safari

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#64451]
### Description

Triple click normally equals cmd+a to select all text. But in Safari and Chrome it's also selecting into the next block, triggering multi selection.

### Step-by-step reproduction instructions

Triple click in a paragraph.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Although triple-click exists on Windows OS, this issue does not seem to be reproducible on Windows OS (tested on Chrome and Firefox).

https://github.com/user-attachments/assets/69351e5a-37c6-4f06-b317-8da3a8f3483b
