### ISSUE TITLE
Template Sidebar Panel: Content panel shows even when it is empty

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#64472]
### Description

In the Site Editor, when editing a template and the Template panel is opened in the sidebar, I see an empty Content panel.
Should this empty panel be hidden if there is no Content?

I only see the empty content panel if Gutenberg is active.

### Step-by-step reproduction instructions

Activate Twenty Twenty-Four.
Go to Appearance > Editor.
Open the editor, editing for example Blog Home.
**Delete the header and footer template parts from the template.**
Open the settings sidebar.
Open the Template panel.

Check if there is an empty Content panel.

### Screenshots, screen recording, code snippet

<img width="1512" alt="site editor template content panel" src="https://github.com/user-attachments/assets/c025e37f-9b57-49c8-a79d-72bde56bb476">

### Environment info

Tested with and without Gutenberg trunk
WordPress 6.6.1.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by shreya0204** [comment]
@carolinan I would like to work on this issue.

**Comment by Mamaduka** [comment]
@shreya0204, I think this needs design decision/feedback first.

**Comment by hanneslsm** [comment]
> Should this empty panel be hidden if there is no Content?

I don't think so - people could get confused when they cannot find the panel where they would expect it to be. 
Instead we could 
1) disable it. I think this state does not exist for panels though. 
2) Add a info text as a placeholder like "Template parts and patterns will be displayed here" or "This template does not have synced content." or  "Add synced content to this template by inserting template parts or synced patterns. ".… or so? I'm not a good copy writer.

Makes me think if "Content" is really the best title for the panel, but there was for sure already some discussion about it. ("Synced content" would be a little bit more descriptive, I think)

**Comment by carolinan** [comment]
I like the text suggestions.
It is the extra empty space that shows because the panel is opened / expanded by default that gets me: It makes me think something broke.

**Comment by t-hamano** [comment]
Whichever approach we choose, I think we should consider consistency with the Design panel:

![image](https://github.com/user-attachments/assets/a43c5ede-65e3-4a95-bf3e-ab49b33c49c9)

Currently, the Design panel is hidden if no patterns are available:

https://github.com/WordPress/gutenberg/blob/54269c00f74805533b5fec9bf14b84d18f8d3ae9/packages/editor/src/components/post-transform-panel/index.js#L59-L61

If a placeholder is appropriate, I think the same approach should be applied to the Design panel.

**Comment by shreya0204** [comment]
@t-hamano In that case, should I add placeholders for both or hide content panel if no patterns available?

**Comment by t-hamano** [comment]
@shreya0204 Personally I'm leaning towards hiding the panel itself.

I'd like to hear from the @WordPress/gutenberg-design team as well.

**Comment by jasmussen** [comment]
I've been thinking about elevating and improving the contentOnly experience which is currently very under-developed (#60021). The origin of the content panel was from that feature. It's also now used for synced patterns with overrides, and template parts. But the panel aside, the goal of it is to make editing the block easy, and if the panel doesn't accomplish that, then it could be worth exploring a different interface. Is that simply surfacing all available controls directly in the panel? Is it something else? Ultimately contentOnly should be about making it _easy_ to edit what's there.

All that is to say, depending on where those explorations might or might not go, we might even look at retiring the content panel in the future, in favor of something better. To that end, I'd support Aki's suggestion that if it's empty, don't show it.

**Comment by richtabor** [comment]
> I don't think so - people could get confused when they cannot find the panel where they would expect it to be.
Instead we could

> To that end, I'd support Aki's suggestion that if it's empty, don't show it.

I'm +1 for hiding parts of the UI which do not have purpose.

**Comment by t-hamano** [comment]
Thanks for the feedback!

@shreya0204 I think we could go for an approach where we don't show the Content panel if it's not available.

**Comment by shreya0204** [comment]
@t-hamano Raised PR for the same.
