### ISSUE TITLE
Category selector: UX improvement needed when selecting a category

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#64473]
I’m running into a UX problem when using the category selector in the block editor, in the specific case of selecting terms for the Query Loop Block. I have a site with around a dozen categories, each of which has subcategories which have the same name. (So, for example, _Category 1 » Info_, _Category 1 » Summaries_ and also _Category 2 » Info_, _Category 2 » Summaries_.

This means that in the case of using the selector to search for “Summaries”, I get multiple entries but no indication of which one is which. This problem is caused because the field is implemented as a search box with no hierarchical display and not as a hierarchical field.

## Proposed solution
Improve the results list when searching for a taxonomy using this control.

**Comment by annezazu** [comment]
I believe this matches a currently open issue https://github.com/WordPress/gutenberg/issues/31112 Would you agree? If so, we can close this one out.

**Comment by markhowellsmead** [comment]
I do, but if this hasn’t been sorted out in three years, I guess there’s no point in engaging with it. I’ll go ahead and build my own solution.

**Comment by annezazu** [comment]
I hear you! I do encourage you to engage there still, especially since we're seeing some iteration around query loop block settings and default experiences: https://github.com/WordPress/gutenberg/issues/31158#issuecomment-2252221221
