### ISSUE TITLE
Author Name Hidden in Post Editor When Permalink Is Too Long

### ISSUE THREAD

**Issue by alexdeborba** [WordPress/gutenberg#64485]
### Description

When creating or editing a post in WordPress, if the permalink generated is too long, it causes the author name to be hidden or truncated in the post editor interface. This issue was observed when editing a post titled "Gaerea: 'Coma' as a Reflection of Existential Turmoil in Modern Black Metal."

### Step-by-step reproduction instructions

1. Create a new post with a long title.
2. Observe that the permalink generated is long.
3. Notice that the author name is hidden or partially visible in the editor's right sidebar.

### Screenshots, screen recording, code snippet

![Edit-Post-“Gaerea-“Coma”-as-a-Reflection-of-Existential-Turmoil-in-Modern-Black-Metal”-‹-Atmostfear-Entertainment-—-WordPress](https://github.com/user-attachments/assets/d02cc4c6-cf3e-4215-87f4-3bcce109d337)

### Environment info

- WordPress 6.6.1
- Gutenberg 18.9.0
- Aegis 1.0.0 Beta 3

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by Mamaduka** [comment]
Thanks for reporting the issue, @alexdeborba!

The bug should be fixed in Gutenberg 19.0, which will be released today. Related PR: #64053.
