### ISSUE TITLE
Leverage scheduler.yield() in @wordpress/interactivity'ss splitTask() when available

### ISSUE THREAD

**Issue by westonruter** [WordPress/gutenberg#64483]
There is a TODO in this `splitTask()` function:

https://github.com/WordPress/gutenberg/blob/5dae25b15e82a59d28c6c065b5a3745f3f83980f/packages/interactivity/src/utils.ts#L46-L56

Chrome just [announced](https://groups.google.com/a/chromium.org/g/blink-dev/c/DHgWeqFOCXQ/m/J5X8RZ2uAQAJ) the intent to ship this (where previously it was behind an origin trial). Once it is available we can leverage it for better yielding to the main thread as described in the [Optimize long tasks ](https://web.dev/articles/optimize-long-tasks#scheduler-dot-yield) article on Web.dev.

**Comment by swissspidy** [comment]
Looks like this shipped now?
