### ISSUE TITLE
I wish there was more white space at the end of the editor

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#64491]
## What problem does this address?

you may see this screenshot... when I am about to finish my writing, I feel so unconfomtable because there is no space at the end...

## What is your proposed solution?

I hope there is a space at the end. then it will be more confortable when I write 

![editor feedback 1](https://github.com/user-attachments/assets/6e0093bc-92da-4833-a0a2-b8f491e33471)
![editor feedback 2](https://github.com/user-attachments/assets/256a7f3f-1922-4198-93bd-f964f6dbf722)

**Comment by hanneslsm** [comment]
> then it will be more confortable when I write

Gutenberg has a built in distraction free mode which might be beneficial for you:
https://wordpress.org/documentation/article/distraction-free-mode/

**Comment by t-hamano** [comment]
Thanks for the report.

I think the underlying issue is that the editor is not an iframe when the meta box is present. I also found this issue in [this comment](https://github.com/WordPress/gutenberg/pull/63288#pullrequestreview-2165937101):

> Another issue I noticed while testing this PR is that when the editor is not iframed because a meta box is present, the bottom padding is not applied:

This is also related to #61210,

**Comment by MYIG** [comment]
I know distraction mode of course... But if there is no space below, it becomes frustrating to write...
Maybe you didn't write post in wordpress directly... so you guys don't feel uncomfortable.
I will show you examples... you can see writing apps have a space at the end... but block editor don't have space it... it is so uncomfortable when I am about to finish writing...

![writing app 3 MS Word](https://github.com/user-attachments/assets/1649e8c5-1acf-42d3-97e5-937da101383b)
![writing app 1 upnote](https://github.com/user-attachments/assets/cbf18078-482d-40f0-8d3d-0c06b7e4b44c)
![writing app 2 notion](https://github.com/user-attachments/assets/188d2245-229e-4c00-8d10-d8046014f5a1)


The 'revivepress' part of the photo at the very top of this article was to show that I created the space arbitrarily. This part is quite inconvenient... Please fix it...


![distraction mode](https://github.com/user-attachments/assets/41ac0897-8dcc-4f5d-9476-200a1c62dc07)

This is a distraction mode... It's so frustrating

**Comment by stokesman** [comment]
I’ll close this as https://github.com/WordPress/gutenberg/pull/64639 is merged and should resolve it. Please reopen if I'm mistaken.
