### ISSUE TITLE
Why is the link cut off at the bottom?

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#64492]
## What problem does this address?

When I write a post, I usually add link to get SEO, but it is cut in the end... so I should move the entire paragraph up then add link then move it down... it is so uncomfortable

## What is your proposed solution?

When I want to add link where the paragraph in the end of editor, I want the editor to have some margin as I create the link window, or I want the link part to cover more of the top.

![right link](https://github.com/user-attachments/assets/5c5d3ca8-0bed-48b9-8a26-d8e076dbee05)
![what the](https://github.com/user-attachments/assets/b3ae4a01-c0c7-4fc1-9a0a-4a292597af90)

**Comment by Mamaduka** [comment]
Hi, @MYIG

The bug was fixed recently (#63939), and the fix is available in the next minor WordPress release.
