### ISSUE TITLE
Freeform Block: Consider more descriptive name

### ISSUE THREAD

**Issue by annaephox** [WordPress/gutenberg#645]
We have a few tickets on the idea of creating a generic, fallback block to handle unknown block types, serve as a bridge for users transitioning to the Gutenberg editor, provide backwards compatibility and handle complex document types  #335 #349 #365 

**Before we add this block type into the gutenberg inserter #323, we need to give it a name.** A few ideas have been bounced around, each with pros and cons… 

- Option 1: Freeform block (pros: agnostic; cons: ?)
- Option 2: Fallback block (pros: ?; cons: sounds a bit negative)
- Option 3: TinyMCE block (pros: gives a nod to the Swedish boys behind Tiny; cons: gives a nod to the Swedish boys behind Tiny)
- Option 4: _[your idea here]_

For me personally, I love the idea of "TinyMCE" block for two reasons: 
_(full disclaimer: I work for Ephox, the company behind TinyMCE)_ 

1. Since 2005, TinyMCE has been used as an open source editor in WordPress. Not only has TinyMCE become synonymous with editing in this community, but much of the work in those first 10 years was done by two lone huskies ([Joakim](https://github.com/Afraithe) and [Spocke](https://github.com/spocke)) from their homes in Northern Sweden. It’s fair to say that TinyMCE is the product of passion for them, and 
2. Attribution acknowledges the hard work that goes into keeping projects in the open source community alive and thriving, and gives a nod to the those who put in the hard yards. **It’s about sending back a vibe of gratitude**

The counter argument, of course, is that we as the community may feel that naming the block TinyMCE smells not of roses... but of an attempt by Ephox to push our corporate brand into the WordPress community.

_What do you think? To TinyMCE block, or not to TinyMCE block?_

Share your thoughts...

**Comment by BE-Webdesign** [comment]
How about Freeform ( TinyMCE )?  That way it can signal the intent to people who have no idea what TinyMCE is, and more WordPress savvy people will understand that this block represents the classic WordPress editor feel of TinyMCE.

**Comment by nylen** [comment]
My main argument against the name "TinyMCE" is that the average user will have no idea what this means or why they would want to use it.  Also, our other blocks still use TinyMCE so this isn't really "the only TinyMCE block".

To a lesser extent, these same arguments also apply to "Some other name (TinyMCE)".

How about "Classic"?

**Comment by jasmussen** [comment]
A few things in this to unpack here. 

First off, I'm not personally opposed to us trying "TinyMCE" out, seeing how it feels. These things are easy to rename, if we find that it doesn't feel right, we'll rename.

My reluctance to naming the block "TinyMCE" with a graphic logo next to it are the same as James: it doesn't really say what that block does to anyone who doesn't know what TinyMCE is, which seems a disservice. But this is an assumption easily tested by keeping the name for now and testing it for a bit. 

Secondly, I fully agree that TinyMCE, as well as all other contributors to the editor and indeed WordPress as a whole need credit. TinyMCE carries a lot of weight, as James suggest it also powers the `Editable` component which is foundational for virtually every other block. I mentioned this in another thread, we should think about other ways we can give attribution to TinyMCE, regardless of the name here. We need a help section somewhere (#599), perhaps we can put a "The editor is powered by TinyMCE" somewhere in there? We might show an out-of-the-box welcome screen the first time you open the editor. Perhaps we can put the name there as well?

Finally, I think we may be underestimating how many people might want to actually use this block. Hey, we might even want an option somewhere in WordPress that says "Always start with the [name] in the editor", so this block might be opted in as the default starter block. If we can get this block to really shine, many might prefer this over the more atomic text blocks. Down the road we might look at post templates, where people can pre-populate post types with placeholder blocks. In this situation the block would also likely be popular.

For all these reasons, I don't think either "TinyMCE" or "Classic" are good names. Admittedly, perhaps "Freeform" isn't either. 

Maybe "Visual Editor"? Maybe "Advanced"? If we really believe the TinyMCE name adds value for users, perhaps "Advanced TinyMCE"?

As a sidenote, please don't take these discussions personally, by the way. A lot of us are huge fans of TinyMCE and always have been. Joakim and Johan are my heroes.

**Comment by mtias** [comment]
I agree with @nylen on the reasons for how to present it in the inserter. The main objective should be making things completely clear to the user.

Also worth mentioning that we [already have a block in place](https://github.com/WordPress/gutenberg/blob/master/blocks/library/freeform/index.js), called "Freeform" for the time being, it's not doing anything format wise, but it is working as a fallback already.

**Comment by mtias** [comment]
Maybe something we could try is using the tinymce logo and the "Freeform" label on the inserter?

**Comment by mrwweb** [comment]
What about "Rich Text" or "Text Editor", both words currently used to describe the WordPress editor. I initially wondered about just "Text", but that has the opposite problem of being associated with the current HTML editor.

(And I'll just say that I love TinyMCE and greatly appreciate them and yet try to avoid saying it around clients because they don't understand what I'm talking about.)

**Comment by jasmussen** [comment]
Renamed this ticket to make it more searchable.

**Comment by saracannon** [comment]
I agree that from a user-perspective if you are not deeply familiar with WordPress, you'll have no idea what TinyMCE is. "Advanced" seems to be a better label in that regard, which also serves as a warning of some sorts to new users. The "Freeform" label seems too friendly and vague as to its purpose. If the label stayed "Freeform" a new user might use it while typing just to add text because they do not know that it's more of an "Advanced" or different block, which will cause them to lose features (drop cap).

**Comment by hedgefield** [comment]
If we want users to use the new block style of writing posts, we should not give the old way a name that would suggest it is somehow superior or alternative to the blocks, which is what Advanced or Freeform suggest to me. If I were a power user, I would maybe think "ooh advanced, that sounds like the thing for me".

If we're including it as backward compatibility for old posts, we should name it what it is: `Classic`.

**Comment by saracannon** [comment]
You're right @hedgefield, "Classic" would further de-emphasize use.

**Comment by hedgefield** [comment]
I like both, although "classic editor" might suggest that you get the old environment back?

**Comment by jasmussen** [comment]
> I like both, although "classic editor" might suggest that you get the old environment back?

That's sort of the goal, though.. the classic editor in block form, though with a few limitations. I'm not bullish on that, but I'd love if we could call it something that suggests it's still somewhere you can edit text. Perhaps "Classic Text"?

**Comment by hedgefield** [comment]
Ah I see your point. "Classic Text" does sound good, and "Classic Editor" would also work, it's just a thing of anticipating what kind of expectation the latter creates, or rather what we mean by 'editor'. It does have the functionality of the old editor, but it's still in a block form, in the new post editor screen, so you don't entirely get the 'old way' back, which was my first association when I read it. But if that's not a common mindset any of these recent options would be good :)

**Comment by jasmussen** [comment]
Let's try Classic Text for now. Opening separate ticket.

**Comment by jasmussen** [comment]
Great discussion everyone. Closing this in favor of #1326
