### ISSUE TITLE
Button groups in Typography tools should use ToggleGroupControl

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#64525]
The Decoration, Orientation, and Letter Case controls in Typography tools current use an ad hoc button group, but these should be using the [`isDeselectable` variant](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-togglegroupcontrol--docs#deselectable) of ToggleGroupControl. It's already nicely componentized and has an animation on toggle.

There aren't any blockers that I know of, but let me know if there are.

<img width="271" alt="Button groups in Typography tools" src="https://github.com/user-attachments/assets/30ba91e2-d245-4579-b7d1-26adb5263121">

**Comment by hbhalodia** [comment]
Hi @mirka, I would like to work on this issue.

Thank You,

**Comment by hbhalodia** [comment]
Hi @mirka, I have worked on the issue and raised PR for the same - https://github.com/WordPress/gutenberg/pull/64529, Could you please review the same and update with the feedbacks if any.

Thank You,
