### ISSUE TITLE
Font size: Confusing UI

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#6453]
## Issue Overview

_Using Gutenberg 2.7.0_

I've noticed some confusion in UI + CSS class the predefined text/font size functionality seems to produce. Basically, I'm not sure what **"M"** button (from **"S"**, **"M"**, **"L"**, **"XL"** and **"Reset"** buttons group) should do.

It applies a CSS class of `.is-regular-text` on the paragraph, while forcing `16px` font size on it. For me the word _"regular"_ seems to be equivalent of _"theme default font size"_. (And in that case even the forced `16px` size is not OK, should be `1em` I'd say, but that's another issue&hellip;) Or am I wrong, was it meant to describe something different? What is "medium font size" anyway? ;) (In my themes I treat medium font size exactly as regular, theme default one.)

And if the "regular" indeed means "theme default font size" than the **"M"** button should actually duplicate the functionality of **"Reset"** button. In that case even applied `.is-regular-text` CSS class is redundant, the same like one of those buttons.

Here is a screenshot of the issue:

![Font size UI and CSS class](http://easycaptures.com/fs/uploaded/1116/1174673827.png)

## Current Behavior

Clicking the **"M"** button applies `is-regular-text` CSS class on the paragraph.
Clicking the **"Reset"** button removes any font size CSS class from paragraph.

## Expected Behavior

There should be no **"M"** button actually. It is meant to be the regular, theme default font size. It is duplicating the **"Reset"** button functionality.
Either **"Reset"** button or **"M"** button is obsolete.

## Possible Solution

Remove the **"M"** button from UI.
Remove the `.is-regular-text` class from CSS code and from HTML too.

**Comment by karmatosed** [comment]
Some interesting insights here. Thanks for the feedback.

Firstly, themes can hook into 'is-regular-text' so it could be set to anything. That's one flexibility here worth calling out.

There are actually not 1 but 3 ways to change a font size and reset works on all of those. As a result, having both M and Reset does make sense in this case. It could be argued if it didn't interact on all those cases it was obsolete, however I still think from a usability view it makes a lot of sense for someone to have the option of both.

I am going to close this for now, hopefully my explanation clarifies why we do have it. Just noting closing doesn't mean discussion can't continue or issues can't be reopened at some point.

**Comment by webmandesign** [comment]
@karmatosed 

Thank for you reply and explanation, Tammie!

"Reset" button makes sense, indeed.

Even when I think about "M" button now, it also makes complete sense to me. I can actually set it to `1em` in the theme, and use it on blocks with larger font size (like Quote block) to reset them back to regular theme's font size. The problem here is that those font options are available only for specific blocks from what I can see. The Quote block doesn't have those, for example.

Anyway, thanks for explaining and I surely understand why you've closed the issue.
