### ISSUE TITLE
WP 6.6.1 bug: Autocompleter (slash command, "/") doesn't respect allowedBlocks 

### ISSUE THREAD

**Issue by isuke01** [WordPress/gutenberg#64538]
### Description

Hi,

This is issue on the WordPress 6.6.1 - I did test on the 6.5.5 - the autocomplete works as it should.
There was similar issue in past https://github.com/WordPress/gutenberg/issues/6070 that I have found, I tested the PHP hook too, this works as intended. Only the JS hook is an problem.

### Step-by-step reproduction instructions

I have added simple Hook:
```js
import { addFilter } from '@wordpress/hooks';
        
addFilter('blocks.registerBlockType', 'your/namespace', function (settings, name) {
	if (name !== 'core/cover') {
		return settings;
	}

	return {
		...settings,
		attributes: {
			...settings.attributes,
			allowedBlocks: {
				type: 'array',
				default: [
					'core/image',
					'core/paragraph',
				],
			},
		},
	};
});
```

As default paragraph is added.
After this when I use `/` I'll see full list of the blocks:
![image](https://github.com/user-attachments/assets/5acca07e-e9f9-43f9-8d10-f63677a8e2c1)

I'm not able to place any of the blocks from the list, expect the allowed one, so at least this part works.

When "plus" button is clicked, the inserter shows correct list of allowed blocks.
![image](https://github.com/user-attachments/assets/9fb4c7b9-b293-444e-b61e-2c75a22d7a00)

I have tested this hook on multiple core blocks, and custom innerBlock component on my custom block too.

### Environment info

**Wordpress**: 6.6.1
**Theme**: Custom, minimum code.
**Plugins**: No plugins during tests.
**PHP**: 8.3
**System**: MacOS: 14.4
**Browsers**: Chrome: 126, Edge: 129

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This issue was also reported in #64413, and I believe it was fixed in #64413.
