### ISSUE TITLE
Display focus rings on `focus-visible` rather than `focus`

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#64578]
For mouse users, a long-standing issue in the Gutenberg UI is how focus styles can be distracting and/or create unnecessary noise. One of the more egregious examples is the 'Back' button in the Inspector panel:

<img src="https://github.com/user-attachments/assets/88c08818-d246-4efa-8493-145fb40ad3a2" width="300" alt="An animated gif demonstrating how the back button is prominently outlined immediately after drilling into the Shadows section of Global Styles">

Such distractions can be eliminated by attaching focus styles to `:focus-visible` rather than `:focus`. Nowadays support for `focus-visible:` is [widespread](https://caniuse.com/?search=focus-visible), so we might consider adopting it across the components package. As a reminder, here are the differences between `:focus` and `:focus-visible`:

* `:focus:` This pseudo-class applies when an element gains focus, typically via keyboard, mouse, or touch. It can be used to style the element with a focus indicator, like a focus ring. However, this will apply even when an element is focused by methods that might not need a visible indicator, such as mouse clicks.
* `:focus-visible:` This pseudo-class is more specific and applies when an element should display a focus indicator, typically when the user interacts with the keyboard or other non-pointer input methods. It’s designed to prevent the focus ring from appearing when using a mouse, which can reduce unnecessary visual noise for users who don’t need it.

**Comment by mirka** [comment]
Is this a duplicate of #65088?

**Comment by jameskoster** [comment]
Yes 🤦‍♂️
