### ISSUE TITLE
Block Bindings API/UI: Don't show post meta fields that start with an underscore _

### ISSUE THREAD

**Issue by bacoords** [WordPress/gutenberg#64575]
## What problem does this address?

It's a precedent that post meta fields starting with an underscore are "hidden" and don't show up in the regular Custom Fields UI. Feels like they shouldn't show up in the new Block Bindings UI either:

https://developer.wordpress.org/reference/functions/add_post_meta/#comment-467
<img width="687" alt="Screenshot 2024-08-16 at 8 08 58 AM" src="https://github.com/user-attachments/assets/bb2f1cae-a094-4707-943c-705ebf8131de">

## What is your proposed solution?

Only show post meta fields that don't start with an underscore.

Related Conversation: https://github.com/WordPress/gutenberg/pull/64570#issuecomment-2293662672

**Comment by justintadlock** [comment]
It would be correct to hide post meta with keys that begin with an underscore. These are considered "private" meta keys and should never appear in admin UIs: https://developer.wordpress.org/plugins/metadata/managing-post-metadata/#hidden-custom-fields

**Comment by cbravobernal** [comment]
I'll take this one.

**Comment by cbravobernal** [comment]
It is solved with a temporary fix, but we should move that logic to the server as mentioned here: https://github.com/WordPress/gutenberg/pull/64618#pullrequestreview-2250827221
