### ISSUE TITLE
Should sidebar "Search categories" filter be a SearchControl?

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#64593]
## What problem does this address?

The "Search categories" field in the Post sidebar uses a normal `TextControl` even though it's a search field.

<img src="https://github.com/user-attachments/assets/e7da1cc7-7c16-43a1-a1ed-72c98b096c51" alt="Search categories input" width="273">

https://github.com/WordPress/gutenberg/blob/8169dfd2c89b82ed39bb74be8063a715b467c184/packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js#L409-L416

## What is your proposed solution?

@WordPress/gutenberg-design Should this be replaced with the `SearchControl` component, so it can signal that it's a search field, both visually and semantically? At the very least we should probably add back the `type="search"` attribute that seems to have been there in the past.

**Comment by jasmussen** [comment]
I'd think so.
