### ISSUE TITLE
Uncaught TypeError: WeakMap key Symbol() must be an object (signals.ts / interactivity) / regression Gutenberg 19.0

### ISSUE THREAD

**Issue by Marc-pi** [WordPress/gutenberg#64607]
### Description

On a page that contains a cover blocks with an encapsulated Navigation block + Site Logo block, i encounter an issue on mobile  : the burger menu is not clickable anymore on Safari + Firefox (ok with Chrome).

If i look at the Dev Tools, i can see a an error with this.computedsByScope.set in signals.ts (see below screenshot)
I don't know if the error explains the issue with the burger menu not anymore clickable on mobile on Safari/FF only.

### Step-by-step reproduction instructions

I cannot reproduce in a test page : i've build back the banner + logo + nav, but the issue is not there.
> i don't know where the interactivity API is used 
- the website uses pure standard block theme with Gutenberg
- there is no custom code
- as long as i can remember, i guess it is used around the site logo, but i did not investigate deepeer

**the solution : if i deactivate Gutenberg 19, it works back > so the explanation is there**

If someone can fix this ts error, so i can test if it fixes the issue with the nav component, would be great.

### Screenshots, screen recording, code snippet

![image](https://github.com/user-attachments/assets/40af4c8a-6136-415d-95b8-8fe386b07049)
![image](https://github.com/user-attachments/assets/dffca18a-b373-401c-a105-35171d510c30)
![image](https://github.com/user-attachments/assets/484976a6-0ed4-4238-a7c3-31f0c8f5a54a)

### Environment info

- WP 6.6.1
- TT3 theme
- Gutenberg 19.0.0

- I even tested deactivating WooCommerce & WPRocket, but the issue is still there on Safari/FF mobile context (ok with Chrome). 
- Deactivating the Gutenberg plugin fixes the issue with the nav component (burger menu on mobile)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by benharri** [comment]
Reproducible in firefox with any block theme and gutenberg 19.0. Seems to work fine in chrome.

```
Uncaught TypeError: WeakMap key Symbol() must be an object
    getComputed signals.ts:111
    get state.ts:110
    ye utils.ts:388
    De store.ts:189
    De store.ts:187
```

The navigation overlay seems to work on other templates and I haven't been able to narrow down why.

**Comment by benharri** [comment]
Not using any cover blocks but I did put a search bar inside the navigation block. on Firefox it's broken on home but works fine on single posts. Reverted to the version bundled in core for now. 

chrome seems to work perfectly fine

**Comment by matthiashonert** [comment]
I can reproduce the same on a wpcomstaging.com environment. I do not use a cover block. And the error only appears on the frontpage with firefox (mobile/desktop)

**Comment by DAreRodz** [comment]
Hey, there's a bug fix for this in https://github.com/WordPress/gutenberg/pull/64825. It should be fixed on the next Gutenberg release. 🙂

**Comment by Marc-pi** [comment]
Thx !

**Comment by luisherranz** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/64825.
