### ISSUE TITLE
Consider removing use of snackbar component

### ISSUE THREAD

**Issue by johnstonphilip** [WordPress/gutenberg#64622]
## What problem does this address?
The snackbar that pops up upon save can cause playwright tests to be flaky, as it can be _sometimes_ covering an element that playwright wants to click on. So instead of playwright finding the element it wants to click, it instead clicks on the snackbar, causing the test to fail.

This results in playwright tests sometimes passing and sometimes failing. 

Additionally, snackbars and toasts are generally not good for accessibility. See: https://www.erikkroes.nl/blog/burn-your-toast/

Furthermore, the placement of it is on the _opposite_ side of the screen from the Save/Publish/Update button, meaning if you want to click it, it requires great mouse dexterity in the hands of the user.

## What is your proposed solution?
Remove the use of the snackbar component entirely. If the messages are important, they should be persistent. 

If the snackbar cannot be removed entirely, all messages should be manually dismissed.

<img width="371" alt="Screenshot 2024-08-19 at 3 32 13 PM" src="https://github.com/user-attachments/assets/592e5faf-4ef5-40bc-8e15-e7f95b7691b8">

**Comment by Mamaduka** [comment]
E2E test should match actual user behavior. You'll have to close the snackbar before clicking the elements behind it. This is what we do in project e2e tests.

**Comment by johnstonphilip** [comment]
User experience is that the snack bar goes away on its own after save. Making playwright wait for 4 seconds is not ideal though.

Regardless of playwright, it's still not a good pattern for accessibility.

**Comment by Marc-pi** [comment]
> Furthermore, the placement of it is on the opposite side of the screen from the Save/Publish/Update button, meaning if you want to click it, it requires great mouse dexterity in the hands of the user.

i agree see https://github.com/WordPress/gutenberg/issues/47446
