### ISSUE TITLE
Cover Block: Move Clear Media button from Inspector Controls to Block Controls.

### ISSUE THREAD

**Issue by rohitmathur-7** [WordPress/gutenberg#64629]
### Description

The Clear Media Button is present in the Inspector Controls for the Cover block which makes it hard to notice,
The button should be present in Block Controls alongside `Replace` button so that all the buttons related to the media are present in one place only.

### Step-by-step reproduction instructions

- Go to the editor.
- Add Cover Block.
- Add Cover image.
- The `Clear Media` button is present in Inspector Controls.

### Screenshots, screen recording, code snippet

The Clear Media button is present in Inspector Controls of Cover Block:
<img width="1272" alt="cover-clear-media-inspector" src="https://github.com/user-attachments/assets/31258503-82b3-4ad1-b4cc-89ab874903c8">

### Environment info

- WordPress Version: 6.7-alpha-58915
- Gutenberg Version: 19.0.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by richtabor** [comment]
Let's use the existing "Reset" terminology used elsewhere. 

Here's the site logo: 

![CleanShot 2024-08-21 at 20 37 35](https://github.com/user-attachments/assets/9aa2e6b2-87f9-46ba-98a0-8656f23069ad)
