### ISSUE TITLE
Dataviews: Filter icon is displayed even when no filter capabilities are given to any field

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#64631]
### Description

When no `elements` property is defined for any of the items passed in the `fields` prop, the UI still shows the filter icon but displays an empty box

### Step-by-step reproduction instructions

1- Clone https://github.com/WordPress/gutenberg/ repo and install dependencies
2- Edit `packages/dataviews/src/components/dataviews/stories/fixtures.js` and comment on any `elements` or `filterBy` properties passed in the items passed to the `fields` props

```
{
		label: 'Type',
		id: 'type',
		enableHiding: false,
		// elements: [
		// 	{ value: 'Not a planet', label: 'Not a planet' },
		// 	{ value: 'Ice giant', label: 'Ice giant' },
		// 	{ value: 'Terrestrial', label: 'Terrestrial' },
		// 	{ value: 'Gas giant', label: 'Gas giant' },
		// ],
	},
```

```
{
		label: 'Categories',
		id: 'categories',
		// elements: [
		// 	{ value: 'Space', label: 'Space' },
		// 	{ value: 'NASA', label: 'NASA' },
		// 	{ value: 'Planet', label: 'Planet' },
		// 	{ value: 'Solar system', label: 'Solar system' },
		// 	{ value: 'Ice giant', label: 'Ice giant' },
		// ],
		// filterBy: {
		// 	operators: [ 'isAny', 'isNone', 'isAll', 'isNotAll' ],
		// },
		getValue: ( { item } ) => {
			return item.categories;
		},
		render: ( { item } ) => {
			return item.categories.join( ',' );
		},
		enableSorting: false,
	},
```
2- Run `npm run storybook:dev`
3- Go to `/?path=/story/dataviews-dataviews--default` and check how the filter icon still appears and an empty box appears

The expected behaviour here would be:
- no filter icon is displayed when no filter capabilities are given to any field

### Screenshots, screen recording, code snippet

<img width="516" alt="Screenshot 2024-08-20 at 08 32 17" src="https://github.com/user-attachments/assets/c7094af8-ee6e-4c91-909d-ae8966ea59cd">

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

cc: @oandregal

**Comment by imrraaj** [comment]
I have created a fix for this. Creating a PR

**Comment by imrraaj** [comment]
I have implemented the changes. It is ready for review

**Comment by oandregal** [comment]
Thanks for the report, Juanma. As per https://github.com/WordPress/gutenberg/pull/63203#issuecomment-2301440171 I'm going to go ahead with @imrraaj PR.
