### ISSUE TITLE
Dataviews: "elements" property of field items should be a subproperty of "filterBy"

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#64635]
## What problem does this address?
The `elements` property and the `filterBy` property of Dataviews are tightly coupled. In fact, filters are enabled by a field just by passing a proper array of objects to the `elements` property even when `filterBy` is empty. From a Developer Experience point of view, I think this is a bit confusing.

## What is your proposed solution?
I think it makes more sense for the `elements` property to be a sub-property of `filterBy` so it's more naturally understandable that:
- Filters by a field are "enabled" when the property `elements` property of `filterBy`, receives an array of `value`-`label` objects
- Optionally, we can also define `operators` and `isPrimary` values

In the meantime, I opened https://github.com/WordPress/gutenberg/pull/64633 to clarify this from the docs

cc: @oandregal

**Comment by oandregal** [comment]
That's something we considered at the beginning but decided against. The reason for being a standalone property is that it's shared by some features: filtering, but also editing. In the [DataForm storybook](https://wordpress.github.io/gutenberg/?path=/docs/dataviews-dataform--docs) there's an example that shows how `elements` power a radio or select control for fields.

**Comment by juanmaguitar** [comment]
I see! Thanks for the clarification @oandregal 
That makes sense. I'll close this issue then.

**Comment by oandregal** [comment]
Coincidentally, there's [this conversation](https://github.com/WordPress/gutenberg/pull/64398#issuecomment-2299272219) in which we're discussing adding support for having different elements in filter & edit. 😅
