### ISSUE TITLE
1:1 crop in the gallery block

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#6464]
## Issue Overview

It seems that the gallery block uses CSS to do the cropping of images, so it's not a hard crop. My question is, is it possible to do a 1:1/square crop on the gallery images via CSS, too? If so, how? I remember seeing a ticket where an aspect ratio selector for this block was considered, but I cannot find it right now.

**Comment by danielbachhuber** [comment]
Hi @mrleemon,

Were you able to find an answer to your question? If not, can you explain with a bit further detail on what you're trying to do?

**Comment by mrleemon** [comment]
I just want to do a gallery with square thumbnails.

**Comment by mtias** [comment]
You should be able to do that similar to http://moc.co/2018/02/masonry-galleries-gutenberg/ just by having a fixed width / height on the elements through CSS.

**Comment by mtias** [comment]
I mean you can just set a squared size on the `figure` elements and rely on content-fit.
