### ISSUE TITLE
Groups with contentOnly locking should not be transformable into other variations

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#64661]
I propose that when [contentOnly locking](https://rich.blog/content-only/) is in place on a group block, the pattern should not have have transform controls. 

`contentOnly` is a form of flattening/locking the innerBlocks, which when transformed does not typically result in a positive experience (as you can't manipulate the blocks further anyhow to try and fix it).  

### Current 
https://github.com/user-attachments/assets/c2541ae8-e965-4e9d-8245-8197e595d4ea

![CleanShot 2024-08-20 at 20 05 50](https://github.com/user-attachments/assets/37182b25-9ef4-4ff8-b27a-0e0635394f7b)

**Comment by richtabor** [comment]
There may be validity in not having transforms at all for contentOnly locked group blocks?

**Comment by jasmussen** [comment]
> There may be validity in not having transforms at all for contentOnly locked group blocks?

I'd agree. If need be we can build an edit affordance, like there is for synced overridable patterns. Or you would just need to detach. By switching from row to stack, for example, it substantially alters the appearance of most patterns that were meant to be the former.

**Comment by ramonjd** [comment]
I started looking briefly. 

We could completely short-circuit the [block switcher in the toolbar](https://github.com/WordPress/gutenberg/blob/b93bc14d0cd17e5f710261c1a58e28da82237b4d/packages/block-editor/src/components/block-switcher/index.js#L184-L184), but I think the rest would have to be done at the block level, [at least for Group blocks](https://github.com/WordPress/gutenberg/blob/b93bc14d0cd17e5f710261c1a58e28da82237b4d/packages/block-library/src/group/variations.js#L7-L7).

**Comment by ramonjd** [comment]
Testing stuff over here: 

- https://github.com/WordPress/gutenberg/pull/64917

What do folks think should happen when multiple blocks are selected?

My guess is that if a single block among multiple select is locked, then we shouldn't show the transformation options.

The other option is to show them and (try to) only apply the transformation to the non-locked blocks.

**Comment by jasmussen** [comment]
> What do folks think should happen when multiple blocks are selected?

Would it be reasonable/possible to omit the individual-level transform, and keep only the container-level transforms, i.e. "I want to group a paragraph with a content-only locked pattern"? If that's at all hard, I'd also tend to support your instinct:

> My guess is that if a single block among multiple select is locked, then we shouldn't show the transformation option

**Comment by ramonjd** [comment]
> Would it be reasonable/possible to omit the individual-level transform, and keep only the container-level transforms

Hmm, I'm not sure they're filterable off the top of my hat, but I can have a quick look next week 🤔

**Comment by jasmussen** [comment]
I would say: go with the simplest option.

**Comment by richtabor** [comment]
Reopening as destructive transforms are still available from the Inspector:

![CleanShot 2024-09-11 at 13 57 14](https://github.com/user-attachments/assets/39924532-c352-4566-a8e4-d8ec6d7ece35)

**Comment by ramonjd** [comment]
> Reopening as destructive transforms are still available from the Inspector:

Thanks for the report. 

Could you add some testing steps on how to reproduce what you're seeing?

Template lock values of "contentOnly" behave as expected for me in post and site editors so far given the following example:


```html
<!-- wp:group {"templateLock":"contentOnly", "style":{"color":{"background":"#f8f6db"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background" style="background-color:#f8f6db"><!-- wp:paragraph -->
<p>A Group block with template lock === "contentOnly"</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"color":{"background":"#e1dbfd"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background" style="background-color:#e1dbfd"><!-- wp:paragraph -->
<p>A nested Group block with template lock === "contentOnly"</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
```

<img width="959" alt="Screenshot 2024-09-12 at 9 34 28 AM" src="https://github.com/user-attachments/assets/de17b236-581d-425f-8d73-d5c5f823b50b">

**Comment by getdave** [comment]
I wonder if some PRs might need rebasing and that's why this is still coming up in demos...etc?

**Comment by richtabor** [comment]
> I wonder if some PRs might need rebasing and that's why this is still coming up in demos...etc?

Yup! Pretty sure that's what's going on. Closing this. Thanks!
