### ISSUE TITLE
Font Library: Cannot install some Google fonts (e.g. Reddit Sans, Reddit Mono)

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#64685]
### Description

For a project, I recently needed some fonts that are available from Google Fonts:

- [Reddit Sans](https://fonts.google.com/specimen/Reddit+Sans)
- [Reddit Sans Condended](https://fonts.google.com/specimen/Reddit+Sans+Condensed)
- [Reddit Mono](https://fonts.google.com/specimen/Reddit+Mono)

I tried the font library's built-in "Install Font" option, but if I enter any of the above names as search term (or even just "Reddit"), no results are found.

Those fonts are all under the OFL (Open Font License), which I assume is fine? (If that's the reason that they're not shown, it would be good to indicate that somehow in the UI.)

I ended up manually downloading those fonts from Google Fonts, and uploading them to my site.

### Step-by-step reproduction instructions

1. Go to the Global Styles panel.
2. Select 'Typography'.
3. Click on 'Manage fonts'.
4. Navigate to the 'Install fonts' tab.
5. In the search field, enter 'Reddit'.
6. Verify that no results are found.

### Screenshots, screen recording, code snippet

<img width="984" alt="image" src="https://github.com/user-attachments/assets/d9568db0-d520-474d-ac8d-fbae1cc88d8e">

### Environment info

Latest GB (`trunk`) on WP 6.6.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
From what I've researched, it looks like the WordPress font collection is a bit outdated compared to the latest Google Fonts.

I've submitted an issue suggesting updating the WordPress font collection: https://github.com/WordPress/google-fonts-to-wordpress-collection/issues/34

If we update the WordPress font collection, the Reddit fonts should be added.

**Comment by ockham** [comment]
@t-hamano I, I wasn't aware that we have a list of the Google Fonts that we're making available, and a dedicated GH repo for that!

Thank you for filing that other issue! I'll go ahead and close this one -- it's better tracked there, and no need to duplicate it 😄

**Comment by matiasbenedetto** [comment]
Core track ticket created to update the font collection in 6.7 release: https://core.trac.wordpress.org/ticket/62258#ticket
