### ISSUE TITLE
DataViews: Hide "Add filter" link if there are no filters to add

### ISSUE THREAD

**Issue by allilevine** [WordPress/gutenberg#64689]
The Add filter link should only show when there is another filter to add. Currently it shows when there's only one filter and it's already been added. It's not clickable.

<img width="355" alt="Screen Shot 2024-08-21 at 12 00 24 PM" src="https://github.com/user-attachments/assets/1fe1bd38-513d-4c00-815b-06c74c797c58">

**Comment by oandregal** [comment]
Hi @allilevine thanks for the report.

> The Add filter link should only show when there is another filter to add.

I agree with this. If there's one filter, there's never an opportunity for the "add filter" to become enabled.

> When there are multiple filters and they've all been added, the Add filter link still shows

This case is different, though.

You cannot add _more_ filters when you've added all of them, but the button becomes _active_ as soon as you remove one. In this scenario the disabled/enabled states are more representative, IMO. It'll be a confusing experience to having buttons coming in/out on the screen.

Additionally, we need to pay attention to the keyboard affordances: notice how the "add filter" button gains focus when the last filter is removed:

https://github.com/user-attachments/assets/070c46f8-1089-448e-abd7-674194546341

**Comment by oandregal** [comment]
_sorry, clicked the wrong button when commenting :)_

**Comment by allilevine** [comment]
> You cannot add more filters when you've added all of them, but the button becomes active as soon as you remove one. In this scenario the disabled/enabled states are more representative, IMO. It'll be a confusing experience to having buttons coming in/out on the screen.
> Additionally, we need to pay attention to the keyboard affordances: notice how the "add filter" button gains focus when the last filter is removed:

@oandregal Thanks, this was really helpful to see! I agree and I'll update the issue.

**Comment by jameskoster** [comment]
I think the only time the button should be hidden entirely is when the data view only supplies primary filters. Primary filters are always visible in the UI (even if a value is not selected). In these cases it's not possible to add more filters, so there's no benefit to showing the button.

An example of this is the Patterns page, which supplies a single "Sync status" filter which is primary. Consequently there's no visible "Add filter" button.

<img width="427" alt="Screenshot 2024-08-22 at 10 05 42" src="https://github.com/user-attachments/assets/951d66a5-2f53-4dc1-bce7-1bc4d3cee037">

Therefore we can probably close this issue?
