### ISSUE TITLE
DataViews: focus lost when removing the last filter

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#64697]
### Description

Using the keyboard, when the last filter of DataViews is removed, the focus is lost.

### Step-by-step reproduction instructions

A video with the steps:

https://github.com/user-attachments/assets/68731f14-07d1-493e-bb41-4c90c314dc93

### What I expected instead

That the Filter Toggle gained the focus back.

**Comment by jameskoster** [comment]
> What I expected instead
> That the Filter Toggle gained the focus back.

Agreed.
