### ISSUE TITLE
DataViews: Accept an initial active or selected state for items

### ISSUE THREAD

**Issue by allilevine** [WordPress/gutenberg#64690]
There isn't currently a way to give an item an initial active or selected state without a workaround or hack. For example:

```
// We manually click the selected item so that it is rendered as active.
export function useInitializeDataViewsSelectedItem(
	selectedItem,
	paginatedItem,
 ) {
	const initialized = useRef( '' );

	useEffect( () => {
		if ( initialized.current === selectedItem?.slug || ! selectedItem ) {
			return;
		}
		for ( const item of document.querySelectorAll( '.items-dataviews__item' ) ) {
			const slug = item.querySelector( '.items-dataviews__item-url span' );
			if ( selectedItem.slug === ( slug as HTMLElement )?.innerText ) {
				( item as HTMLElement ).click?.();
				initialized.current = selectedItem.slug;
				break;
			}
		}
	}, [ selectedItem, paginatedItems ] );
}
```

**Comment by youknowriad** [comment]
This is actually already possible the `DataViews` component allows a "controlled" mode for the selection so you can pass a `selection` prop and `onChangeSelection` to receive selection changes.

**Comment by allilevine** [comment]
> This is actually already possible the `DataViews` component allows a "controlled" mode for the selection so you can pass a `selection` prop and `onChangeSelection` to receive selection changes.

Thanks! I'll go ahead and close this.
