### ISSUE TITLE
Consider to improve consistency of the button labels and styles

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6469]
Please see below, a quick comparison between the post permalink buttons and the shared block button. Initially, the both display an "Edit" button with the same style:

<img width="716" alt="screen shot 2018-04-27 at 18 20 10" src="https://user-images.githubusercontent.com/1682452/39373477-016642de-4a48-11e8-8d49-fcec825dc048.png">

Instead, when editing:
- the first button becomes "OK" and is styled like a default button
- the second button becomes "Save" and is styled like a primary button (I understand it's to differentiate it from the "Cancel" button)

<img width="711" alt="screen shot 2018-04-27 at 18 20 22" src="https://user-images.githubusercontent.com/1682452/39373617-6a42895c-4a48-11e8-9957-eeb37ce4c0a4.png">

A few considerations:
- what is the standard text for a save action in Gutenberg? "OK" or "Save"? Seems to me using always the same text would improve consistency and make things easier for users
- should the "OK" button be styled as a primary button?
- what is the standard for a save button, should it always be paired with a "Cancel" button? 

/Cc @karmatosed

**Comment by karmatosed** [comment]
Good catch, I am always up for unifying where we can.

I would be totally up for having 'save' over 'ok' on both and remove cancel. Unless there are accessibility reasons to have also a cancel?

**Comment by afercia** [comment]
Yeah, "Save" seems more appropriate to me too. No particular a11y reasons for the "Cancel" button I can think of: pressing Escape already closes the edit form. Yep it would need to close also when "clicking outside".

Should the primary style be removed? I guess so?

**Comment by karmatosed** [comment]
@afercia thanks and yes I agree it's not a primary action so removing that style makes sense.

**Comment by folletto** [comment]
> Yeah, "Save" seems more appropriate to me too. 

+1

**Comment by mtias** [comment]
@karmatosed can we make an actionable issue out of this?

**Comment by karmatosed** [comment]
Yes we are working on #7593 and close to a solution.
