### ISSUE TITLE
Offline development isn't currently possible

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#647]
Loading the Gutenberg editor currently blocks on [several network requests for JavaScript libraries](https://github.com/WordPress/gutenberg/blob/5bd035de02968f25d169c4702d37c35ba3f45008/index.php#L40-L45):

- `'https://unpkg.com/react@next/umd/react' . $react_suffix . '.js'`
- `'https://unpkg.com/react-dom@next/umd/react-dom' . $react_suffix . '.js'`
- `'https://unpkg.com/react-dom@next/umd/react-dom-server' . $react_suffix . '.js'`
- `'https://fiddle.azurewebsites.net/tinymce/nightly/tinymce.min.js'`

This makes it impossible to develop the plugin without an internet connection.  Also, with a slow or even less-than-blazing-fast internet connection, this makes load times longer and development more difficult, especially if the "Disable cache" option is checked in the browser's dev tools.

It would be nice to come up with some other way of loading these scripts.  For example:

- Do this as part of `npm run dev` without holding up the rest of the build
- Have the PHP code fetch them in development mode with caching via [transients](https://codex.wordpress.org/Transients_API)

**Comment by mtias** [comment]
For TinyMCE we need to see what the status of the release with link boundaries is and sync up with that once it lands in trunk WP.

**Comment by iseulde** [comment]
+1 for this

Re TinyMCE: It's been released yesterday, not sure if we want to keep up with the nightly again.
