### ISSUE TITLE
Cover block overlay with detected color does not work once saved

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#64702]
The current functionality for detecting dominant color and applying it to the cover block's overlay is nice, but it's limited—making it feel inconsistent. 

The cover block has the `isUserOverlayColor` attribute, which when set to `true` **does not** detect color and apply a new `customOverlayColor`. 

I propose that this value should only be `true` if the user _actually_ picked a different color than what was detected and applied. 

If I never changed the previously generated overlay color value, and I replaced the image, I'd expect the block to detect and apply the new image's dominant color to the overlay again. This works today — but again, only if I don't save the post.  Once it's saved,  `isUserOverlayColor` is no longer `false` and you're stuck with the previously saved overlay color unless you manually change it. 

Related https://github.com/WordPress/gutenberg/pull/54054.  

### Visual 

https://github.com/user-attachments/assets/b810dea1-b068-490b-a3bb-995b9593fad3

**Comment by andrewserong** [comment]
Interesting bug! I'm not sure of a solution yet, but while testing this out, I found that if I comment out this line from the last deprecation for the block, then replacing the image after reloading the post works again to update the cover overlay color:

https://github.com/WordPress/gutenberg/blob/c56672504bada434aee1ec331366cd2a10ab2b38/packages/block-library/src/cover/deprecated.js#L410

This points to that deprecation's `migrate` function running on newly saved post content, which I think it probably shouldn't be. We'll likely need to dig into that deprecation's logic a little further to see why it's firing when it shouldn't.

**Comment by andrewserong** [comment]
Just assigning this one to myself since I've started looking into it, but anyone else is welcome to look, too, of course! 🙂

**Comment by Mamaduka** [comment]
@andrewserong, the new deprecation seems to be broken. See https://github.com/WordPress/gutenberg/issues/64480#issuecomment-2287661256.

**Comment by andrewserong** [comment]
I have a tentative fix open over in https://github.com/WordPress/gutenberg/pull/65077 that's proposing removing the deprecation. Very happy for feedback on it, either way!

**Comment by andrewserong** [comment]
I've opened an alternative fix over in #65105. Thanks to @ajlende for the guidance!
