### ISSUE TITLE
Placeholder text missing from RichText fields on focus since 2.7

### ISSUE THREAD

**Issue by rwrobe** [WordPress/gutenberg#6470]
## Issue Overview
New blocks no longer show the placeholder text for RichText fields when the block is in focus. When the block is unpopulated and out of focus, the placeholders show, but focusing removes them for all fields. This makes it difficult to navigate between RichText fields in a more complex block, because it's unclear what they are and where they are.

Current, block focus:
<img width="585" alt="screen shot 2018-04-27 at 12 45 33 pm" src="https://user-images.githubusercontent.com/5480192/39374456-e7cb97fe-4a18-11e8-9974-5648809988d1.png">

Without focus: 
<img width="224" alt="screen shot 2018-04-27 at 12 48 38 pm" src="https://user-images.githubusercontent.com/5480192/39374647-8e42f186-4a19-11e8-928f-297089af10a6.png">

## Steps to Reproduce (for bugs)

1. Create a block with two RT components, each of which has placeholder text.
2. Click on block to focus.

Edit method: 
```
edit: props => {
		const { setAttributes, attributes, className, focus } = props;

		const onChangeQuestion = value => {
			setAttributes( {
				question: value,
			} );
		};

		const onChangeAnswer = value => {
			setAttributes( {
				answer: value,
			} );
		};

		return (
			<div className={ classnames( className ) }>
				<div className="inner">
					<RichText
						tagName="h4"
						placeholder={ __( 'Enter question here.' ) }
						value={ attributes.question }
						className="q-and-a question"
						onChange={ onChangeQuestion }
						focus={ focus }
					/>
					<RichText
						tagName="p"
						placeholder={ __( 'Enter answer here.' ) }
						value={ attributes.answer }
						className="q-and-a answer"
						onChange={ onChangeAnswer }
						focus={ focus }
					/>
				</div>
			</div>
		);
	},
```

## Expected Behavior
Fields will lose placeholder text only when the field itself is focused.

## Current Behavior
All fields lose placeholder text when block is focused.

**Comment by tofumatt** [comment]
Looks like this was an intentional change in #2624, but I agree it's inconsistent and a bit confusing.

I'm gonna have the placeholder show on focus... PR incoming.

**Comment by tofumatt** [comment]
After discussion in #6647, (particularly https://github.com/WordPress/gutenberg/pull/6647#pullrequestreview-119514685) this is actually the intended behaviour and while having a lot of empty RichText blocks looks weird, it's more inline with how a prose editor would work if you think of a bunch of RichText fields strung together as one big editor view.

So I think the current implementation is the best trade-off between "maintaining writing flow with minimal interruptions", complexity, and existing behaviours in rich text editors that have some text entered.
