### ISSUE TITLE
Documentation: @wordpress/scripts must not be installed as devDependency?

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/gutenberg#64704]
### Description

e.g. https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#installation
indicate that @wordpress/scripts should be installed as dev dependency

However, it cannot be used as dev dependency as otherwise `npm run build` will fail.

### Step-by-step reproduction instructions

>npm install --location=project --omit=dev --omit=optional

Then run:
>npm run build --location=project

Which will fail:

>\> wp-scripts build
>sh: line 1: wp-scripts: command not found

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by miminari** [comment]
@kkmuffme Hi, thank you for reporting.
I wanted to try your steps, but does it seems to need some package.json sample or something?

Just to be sure, I tested the method shown in the documentation (https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#installation).

1. Make a package.json file like below:
```
{
    "scripts": {
        "build": "wp-scripts build",
        "check-engines": "wp-scripts check-engines",
        "check-licenses": "wp-scripts check-licenses",
        "format": "wp-scripts format",
        "lint:css": "wp-scripts lint-style",
        "lint:js": "wp-scripts lint-js",
        "lint:md:docs": "wp-scripts lint-md-docs",
        "lint:pkg-json": "wp-scripts lint-pkg-json",
        "packages-update": "wp-scripts packages-update",
        "plugin-zip": "wp-scripts plugin-zip",
        "start": "wp-scripts start",
        "test:e2e": "wp-scripts test-e2e",
        "test:unit": "wp-scripts test-unit-js"
    }
}
```
2. `npm install @wordpress/scripts --save-dev`
3. `npm run build`

I did on Node.js v20.17.0 and it seems to be able to run build successfully.

![Screenshot of the build command in VS Code](https://github.com/user-attachments/assets/31f2c8ac-0703-4e51-b794-fe19e6879fbb)

I might be missed something, can you tell more information?

**Comment by miminari** [comment]
@kkmuffme wp-scripts should work in devDependencies or dependencies. And I couldn't reproduce the issue, so I'd like to close this. If you have any problems yet, please provide details like the complete package.json.
