### ISSUE TITLE
URLInput should use InputControl internally

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#64709]
## What problem does this address?

The URLInput component uses an `input` element directly, instead of a standard component like `InputControl` or `TextControl`. This will cause styles to drift from the rest of the app, since it won't receive style updates with the rest of the componentry.

https://github.com/WordPress/gutenberg/blob/4d4522c3102a9e32b8a1a36b09f7c1ab43d3ad37/packages/block-editor/src/components/url-input/index.js#L475

## What is your proposed solution?

We should see if we can refactor this to use InputControl or TextControl. I think InputControl would be better because one of the consumers (LinkControl) has a submit button within the input field border that would be best to put in the `suffix` slot of `InputControl`.

### URLPopover
<img width="489" alt="URLPopover" src="https://github.com/user-attachments/assets/ed795f26-fd90-4028-90d7-c06d5fa487f3">

### LinkControl
<img width="382" alt="LinkControl" src="https://github.com/user-attachments/assets/668b030f-79f9-4917-a587-7d5df0808498">

### Social Icons block

<img width="525" alt="Social Icons block" src="https://github.com/user-attachments/assets/cfb359ff-59de-491d-bd4d-716e54571a66">

@WordPress/gutenberg-design Do we also care to do some consolidation on how the submit button is placed? Especially the LinkControl and Social Icons block seem to have an unnecessary inconsistency.

**Comment by jasmussen** [comment]
> Do we also care to do some consolidation on how the submit button is placed? Especially the LinkControl and Social Icons block seem to have an unnecessary inconsistency.

Definitely care about consolidation. Social links should be the same as the LinkControl.

**Comment by rahulharpal1603** [comment]
@mirka Can I take up this issue?

**Comment by mirka** [comment]
Of course, thank you! Please mention `@WordPress/gutenberg-components` in your PR when it's ready.

**Comment by rahulharpal1603** [comment]
Thanks, this may take some time, is it ok? Because, I also have some college work to do

**Comment by rahulharpal1603** [comment]
![image](https://github.com/user-attachments/assets/63c0d7d2-7266-44c7-88b4-9e0eece3d9b9)

@mirka I replaced the \<input> with \<InputControl> but the problem is that the className prop, when applied to InputControl, it applies to the wrapper \<div> instead of the \<input> tag inside that wrapper \<div>. This is causing the CSS to not apply properly on the input tag. This is due to  some CSS property overriding the height property of the div class.

What to do? Please help, I am stuck here.

**Comment by rahulharpal1603** [comment]
![image](https://github.com/user-attachments/assets/f394e99b-46d8-4f3f-b351-abadc5bf46eb)

See, the height of the \<InputControl> element is smaller (36px) than the above element rendered with \<TextControl>

**Comment by ciampo** [comment]
@rahulharpal1603 we can definitely help! Could you open a PR with your changes, so that we can help with precise code comments and test the changes?

**Comment by rahulharpal1603** [comment]
> @rahulharpal1603 we can definitely help! Could you open a PR with your changes, so that we can help with precise code comments and test the changes?

Sure

**Comment by rahulharpal1603** [comment]
@ciampo, the height issue is fixed but there is some other issue, please check the above PR for more details
