### ISSUE TITLE
Core Image Block - no spacing/margin controls

### ISSUE THREAD

**Issue by fabianpimminger** [WordPress/gutenberg#64715]
### Description

I've been trying to get the spacing/margin controls working for core/image, but it doesn't seem to work. It's working on nearly all other blocks, but refuses to work on core/image - even though it seems to be supported according to the block reference (https://developer.wordpress.org/block-editor/reference-guides/core-blocks/#image)

<img width="948" alt="Screenshot 2024-08-22 at 13 55 55" src="https://github.com/user-attachments/assets/2ccb2df4-df25-4d7c-b5d0-d88c3dae1333">

I do have spacing enabled in the theme.json settings:

```
"spacing": {
  "padding": false,
  "margin": true,
  "units": [ "px", "em" ],
  "blockGap": true,
    "spacingScale": {
    "operator": "+",
    "increment": 1.5,
    "steps": 5,
    "mediumStep": 3,
    "unit": "em"
  }
},
```

### Step-by-step reproduction instructions

1.) Enable Block Margin Spacing via theme.json
2.) Spacing Margin Controls should be visible in the editor

### Environment info

- Wordpress Version 6.6.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Thanks for the report.

The Core Block Reference page refers to the latest Gutenberg, not the latest WordPress release. Margin support for the Image Block was added in #63546, but is part of Gutenberg 18.9 and not yet included in WordPress 6.6 (Please see [the Versions in WordPress page](https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/)).

I'd like to close this issue, but if you have any questions, please feel free to comment.
