### ISSUE TITLE
ContentOnly: Improve the image block toolbar controls within contentOnly locking

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#64727]
The current implementation of image blocks with contentOnly locking needs a bit of attention. 

Here's what I'm proposing: 

1. Remove "Title" from the toolbar, unless the `title` attribute is present on the block already. Otherwise it's confusing. It's an advanced item in the Inspector already anyhow. 
2. Add a divider between "Replace" and "Alt" to better distinguish these two.  
3. Remove the cropping mechanism. Perhaps if it gets better in the future we can reintroduce, but for now it's clunky and does not work well in the contentOnly implementation where you can't really resize the image after cropping. 
4. Update "Alt" to "Add description" to make it much clearer what you can do. 

### Current 

![CleanShot 2024-08-22 at 15 29 48](https://github.com/user-attachments/assets/e0eabfe5-4448-4373-bc78-7ced032f0baf)

### Proposed

![CleanShot 2024-08-22 at 15 28 40](https://github.com/user-attachments/assets/cd29b892-e41f-480b-9541-ca86ae4abc70)

**Comment by talldan** [comment]
There's also a PR here that could be an option to revive - [WIP: Try surfacing content inspector controls for contentOnly inner blocks](https://github.com/WordPress/gutenberg/pull/60412#top)

It allows for alt and other controls to be moved back to the block inspector.

**Comment by jeryj** [comment]
> Update "Alt" to "Add description" to make it much clearer what you can do.

We use "Alternative Text" in other areas, and in the Media Library have both Alternative Text and Description fields. I think Alt text and description are separate things (while confusing, I don't know what description is used for in the media library). So, probably best to rely on Alt or alternative text. What @talldan  said about surfacing inspector controls for contentOnly blocks is probably best overall though.

**Comment by richtabor** [comment]
> There's also a PR here that could be an option to revive - https://github.com/WordPress/gutenberg/pull/60412#top

> It allows for alt and other controls to be moved back to the block inspector.

Maybe—it's an interesting exploration. But it kinda takes the simplicity out of contentOnly mode, as you'd have another navigation tree to take note of.

**Comment by richtabor** [comment]
> We use "Alternative Text" in other areas, and in the Media Library have both Alternative Text and Description fields. 

Yea, I'm curious if using "Description" in lieu of "Alternative text" would result in more people understanding what it is, how to use it, and what to do with it (not just here in this control). "Add alternative text" is likely not as understandable as "Add description" for the majority of users.

**Comment by richtabor** [comment]
> "Add alternative text" is likely not as understandable as "Add description" for the majority of users.

I'm cool with making it "Add alternative text" for now to get this unblocked though.

**Comment by jeryj** [comment]
> Yea, I'm curious if using "Description" in lieu of "Alternative text" would result in more people understanding what it is,

I think you're spot on that this is an opportunity for us to educate the user though. I think titling it Alt Text and then explaining that it's a description.

<img width="281" alt="Screenshot of alt text field in block editor settings sidebar" src="https://github.com/user-attachments/assets/89ffe51c-6465-4aae-bc57-0aeecbec3fa1">

This is what we already do in the sidebar. I checked the description link, and it goes to [this technical document](https://www.w3.org/WAI/tutorials/images/decision-tree/). I wish we linked to a resource that was simpler and straightforward. I imagine no one reads this.

**Comment by jeryj** [comment]
> I'm cool with making it "Add alternative text" for now to get this unblocked though.

Do you want it to just be "Alternative text"? Otherwise we'll need to check if its empty ("Add alternative text ") or has text ("Edit alternative text").

**Comment by jeryj** [comment]
If the above four PRs are merged, this issue can get closed.

**Comment by richtabor** [comment]
> This is what we already do in the sidebar. I checked the description link, and it goes to [this technical document](https://www.w3.org/WAI/tutorials/images/decision-tree/). I wish we linked to a resource that was simpler and straightforward. I imagine no one reads this.

Yea, it's not great.
