### ISSUE TITLE
Enhanced User Role Control in Gutenberg/FSE

### ISSUE THREAD

**Issue by cliffralessio** [WordPress/gutenberg#64742]
### Problem
One of major limitation in Gutenberg is the lack of granular control over user permissions. Currently, there is no native way to restrict certain actions, such as changing colors, moving elements, or adjusting text sizes, based on user roles.

### **Proposal:**

Create a permissions management interface in Gutenberg/FSE where site admins can define what each user role is allowed to do, such as:

Restricting color changes
Preventing element repositioning
Limiting text size adjustments

**Comment by annezazu** [comment]
Hey @cliffralessio! Thanks for opening this. Your issues overlaps nicely with a prior open issue here: https://github.com/WordPress/gutenberg/issues/37489 As a result, let's focus there. If I'm missing a piece of this that requires it remain open, just let me know.
