### ISSUE TITLE
Columns do not align when their widths vary

### ISSUE THREAD

**Issue by atrzyna** [WordPress/gutenberg#64757]
### Description

When you create columns that are not equally divided and have custom varying widths, the columns do not line up. Please refer to the screen shot below. This has been created on a brand new site with no plugins, using Twenty Twenty-Four theme. I have attached a json pattern. 

<img width="1283" alt="columns-issue" src="https://github.com/user-attachments/assets/6a647008-b6e0-49fb-8863-b9d58f7dfda7">

### Step-by-step reproduction instructions

1. Create columns where column 1 is 50% and 2 more columns are each 25%
2. Create columns with 4 columns with 25% each. They will not line up.

### Screenshots, screen recording, code snippet

[columns.json](https://github.com/user-attachments/files/16731448/columns.json)

### Environment info

Wordpress 6.6.1
Twenty Twenty-Four
No plugins

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Thanks for the report.

From my understanding, this is the intended behavior.

For example, assume the content width is `1000px`, and the spacing between columns is `20px`.

### 50% / 25% / 25%

- There are two spacing between blocks, i.e. `20px * 2 = 40px`.
- The available size for the three blocks is `1000px - 40px = 960px`.
- The actual width of the column with 25% width is **`960px * 0.25 = 240px`**.

### 25% / 25% / 25% / 25%

- There are three spacing between blocks, i.e. `20px * 3 = 60px`.
- The available size for the three blocks is `1000px - 60px = 940px`.
- The actual width of the column with 25% width is **`940px * 0.25 = 235px`**.

As you can see, the Column blocks, which have the same 25% width, have different actual widths depending on the number of columns.

To fix this misalignment, I find that the Grid variations of the Group block can be useful.

Try importing the following pattern:

[grid.json](https://github.com/user-attachments/files/16735229/grid.json)

![image](https://github.com/user-attachments/assets/aba71260-0eb8-4ac8-88ff-71526a424831)

**Comment by atrzyna** [comment]
@t-hamano Hi. Makes sense and yes the grid is the perfect way to do this. Thanks
