### ISSUE TITLE
Add ability to transform between Image and Cover Image blocks

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#6475]
## Issue Overview
Currently, it's not possible to transform between the Image and Cover Image blocks.

These seem like natural candidates for a mutual transform because they're essentially both an image ID plus text, although one displays it over the top of the image, of course:

Image block:
![_untitled____ _chris_van_patten_ _wordpress](https://user-images.githubusercontent.com/1231306/39383719-52c6f7a0-4a38-11e8-996b-305d463cc875.png)

Cover Image block:
![_untitled____ _chris_van_patten_ _wordpress](https://user-images.githubusercontent.com/1231306/39383753-6eeca740-4a38-11e8-899f-d59cc68f0e95.png)

## Steps to Reproduce (for bugs)
1. Insert an Image or Cover Image block
2. Try to transform it to the other block
3. Find that you can't :)

## Expected Behavior
You should be able to transform between the two!

## Current Behavior
Currently, an Image block can only be transformed into a Gallery block, and a Cover Image block can only be transformed into a Heading block.

## Possible Solution
Enable transformation between these two blocks, mapping…

+ Image ←→ Cover Image (background)
+ Caption ←→ Cover Image Text

Presumably, block alignment could also be carried over, along with the caption's formatting (excluding alignment, which is possible in the Cover Image Text but not in image captions).

Fixed background and dimness settings would be either discarded (if transforming to Image) or set to the defaults (if transforming to Cover Image).

## Related Issues and/or PRs
This was inspired by #5683.

**Comment by chrisvanpatten** [comment]
Just realised this is probably slightly reduced in scope a bit by #5452, although I think you could still theoretically still do Image → Cover Image; just convert the image caption to a paragraph block inside Cover Image.

**Comment by karmatosed** [comment]
I can see this as a good enhancement to make and add to the list for transforms, it makes sense and thanks for suggesting.

**Comment by youknowriad** [comment]
We're thinking of adding nested support to the cover image block, which will make this transformation less "natural". Do you think it's fine to transform only the image and drop the citation/text?

**Comment by youknowriad** [comment]
Sounds good to me @chrisvanpatten I didn't think about adding those as blocks following the image block, but it also means you can't go back.

**Comment by chrisvanpatten** [comment]
At the risk of blowing everything up, is there a world in which the image caption also supports nested blocks?

I can imagine a world when someone might want a heading in a caption, e.g. a "Figure 1" and then the caption text below that.

If image caption becomes a nested block, that obviously makes it possible to go seamlessly back and forth… although that could introduce other back-compat issues I have definitely not thought about.
