### ISSUE TITLE
Block Variations do not create their own custom Capability

### ISSUE THREAD

**Issue by CodingSamurai** [WordPress/gutenberg#64768]
### Description

All of the Gutenberg blocks have their own capability to allow the enabling / disabling of a block.  HOWEVER when there are variations created on that block there's no corresponding capability created meaning you can't disable a variant while leaving the parent block available:

I would propose that WordPress Core should do one of three things:

1. There is a default capability of core/<blockname>/variations that you can enable & disable all variations of that block as needed 
2. registerBlockVariation creates a named capability by default following the structure of core/<blockname>/<variation> (i.e. [core/media-text/media-text-default from your example](https://developer.wordpress.org/news/2023/08/29/an-introduction-to-block-variations/)) 
3. registerBlockVariation allows the block variant creator to create the specific capabilities as part of the initial JSON definition.

This is basically the inverse use case of this bug: https://github.com/WordPress/gutenberg/issues/51112

### Step-by-step reproduction instructions

Install a plugin like PublishPress Capabilities and view capabilities and see there's only core/embed but not core/embed/youtube etc

Try to target specific variations with the **[allowed_block_types_all](https://developer.wordpress.org/reference/hooks/allowed_block_types_all/)** filter

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Thanks for the report.

Have you tried [unregisterBlockVariation](https://developer.wordpress.org/block-editor/how-to-guides/curating-the-editor-experience/disable-editor-functionality/#disable-block-variations)?

**Comment by t-hamano** [comment]
I think we can use `unregisterBlockVariation` to disable just the block variation and not the block itself.

I'll close this issue, but please comment if I've missed something.

**Comment by CodingSamurai** [comment]
@t-hamano what you missed is that by not creating these capabilities it means EXISTING plugins that control access to all of the other Blocks using the capability CANNOT independently control the variations now.  

If variations of a block are going to be created then they need to behave like first party blocks and NOT just rely on custom code to `unregisterBlockVariations`.  

This new functionality is NOT consistent with all of the other Gutenberg "block types" and does not play well in the existing WordPress ecosystem by creating a new mechanism for permissioning with `unregisterBlockVariation` instead of using the EXISTING permissions structure that was working just fine for all other "blocks".

**Comment by t-hamano** [comment]
> EXISTING plugins that control access to all of the other Blocks using the capability CANNOT independently control the variations now.

For example, [Block Manager plugin](https://wordpress.org/plugins/block-manager/) can disable variations:

![image](https://github.com/user-attachments/assets/383cea14-b852-4f4c-85cd-48766bec4c5b)

Besides this, do you mean that core/Gutenberg itself needs more APIs/features?
