### ISSUE TITLE
Move paragraph alignment to toolbar

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#6476]
We now have the alignment just in one place on the paragraph block, which is great.

![alignp](https://user-images.githubusercontent.com/253067/39395393-1e5e1fb8-4ad6-11e8-87f2-ae0a03b5e950.png)

The problem though is all other blocks have this by the toolbar. Let's bring this back to the toolbar and remove from the sidebar please. Like image for example has:

![aligni](https://user-images.githubusercontent.com/253067/39395397-2fb6c486-4ad6-11e8-9ace-aef6e182c690.png)

**Comment by youknowriad** [comment]
I believe the block alignment toolbar is also shown in the inspector for quote blocks. I think the idea was to avoid two alignment toolbars at the same time in the toolbar (text alignment and block alignment), happy to update with what you think is best.

**Comment by karmatosed** [comment]
@youknowriad that's a very valid point and one I'm going backwards and forward on right now. We have an issue where consistency is a huge issue for people and moving alignment options adds to that. I feel in this case unifying makes sense by having all in toolbar.

**Comment by jasmussen** [comment]
I think we should remove the block alignment toolbar from paragraphs altogether, as I feel like these should be reserved for a _container block_. So you select the container to choose the _layout_, and you can then choose individual paragraphs inside to change the text alignment.

This would work for quotes as well, as quotes are destined to become container blocks for nested paragraphs regardless.
