### ISSUE TITLE
Add Template modal in Mobile Safari has layout issues - WP 6.6

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#64769]
### Description

 In WP 6.6, the Add Template module is off-center and cropped improperly on mobile Safari.

### Step-by-step reproduction instructions

1. In mobile Safari, open the dashboard of a site on WP 6.6 with Gutenberg active or inactive
2. Open Appearance > Editor > Templates
3. Select Add New Template 

### Screenshots, screen recording, code snippet

![image](https://github.com/user-attachments/assets/f5478a0f-aa38-428c-aef3-f819eb802088)

### Environment info

Tested on iOS 17.5.1

When you revert to WordPress 6.5.5, the Appearance > Editor > Templates page does not offer an Add Template button at all

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This issue has been resolved in Gutenberg 18.9. Please see #63627. I actually tested in Safari and confirmed the problem has been resolved in the latest Gutenberg.

If you still have this issue, feel free to comment.
