### ISSUE TITLE
Document Outline / Table of Contents inconsistent naming

### ISSUE THREAD

**Issue by GaryJones** [WordPress/gutenberg#6478]
## Issue Overview
The same feature seems to be called two different things in different locations in the Editor.

## Steps to Reproduce (for bugs)

1. Open the Demo page in Gutenberg editor.
2. View the `i` in the top left to see the "Document Outline"
3. View the Document in the sidebar to see the "Table of Contents"

## Expected Behavior
The feature appears to be the same, but is called Document Outline, or Table of Contents. Since the value appears to just be a graphical linked list of the headings structure, and not a "table" that matches up a heading to a page number (since presumably the term "Table of Contents" comes from printed media), I'd prefer it to be consistently called "Document Outline".

## Current Behavior
Document Outline:
![doc-outline](https://user-images.githubusercontent.com/88371/39396046-de2f7b9a-4ade-11e8-8e23-1cf6e86996aa.png)

Table of Contents:
![toc](https://user-images.githubusercontent.com/88371/39396049-e8658848-4ade-11e8-8bfa-c707bb161116.png)

## Possible Solution
The immediate solution would be to rename the Table of Contents to Document Outline, so there is consistency.

The slightly more logical solution would be to question why this same information appears twice on the same page.

Since there may be other meta boxes being added to the Document sidebar, the presence of the value in there seems redundant in so much as it also takes up space. 

Also, the rest of the sidebar items are interactive - add a category or tag, write an excerpt, select a featured image, toggle discussion settings etc. The Table of Contents, don't _set_ anything - they are just a means of viewing the structure of the document, and if necessary, internal navigation of that document (though it really would be easier to scroll the content area for all but the longest of documents, rather than moving the pointer to the sidebar, opening the meta box, and finding and clicking the correct heading).

The version in the `i` has more space to accommodate longer headings, which makes it easier to read the structure without line-wrapping.

Can you consider removing the version in the Document sidebar completely?

**Comment by karmatosed** [comment]
I think removing from the sidebar here makes sense:

![remove](https://user-images.githubusercontent.com/253067/39398981-c343152e-4b0d-11e8-8a63-029b6e11aeb0.png)

If we do that we can then keep in the top section under 'i' as that feels a better place for this right now.

![2018-04-28 at 17 58](https://user-images.githubusercontent.com/253067/39398984-d2665048-4b0d-11e8-82e1-f18adc918316.png)
