### ISSUE TITLE
Hooks running twice on mount when using 19.0

### ISSUE THREAD

**Issue by tomusborne** [WordPress/gutenberg#64780]
### Description

`useEffect` hooks are running twice on mount when using Gutenberg 19.1.0-rc.1.

For example:

```
useEffect( () => {
    console.log( 'mounted' );
}, [] );
```

Without the Gutenberg plugin, this runs one time.

With the Gutenberg plugin, this runs twice.

This is especially an issue when using a pattern like the below.

```
const isOnMount = useRef( true );

useEffect( () => {
    if ( isOnMount.current ) {
      isOnMount.current = false;
      return; // Skip the first render
    }

    // Code to run on updates only
    console.log( 'useEffect ran on update only' );
}, [ dep ] );
```

Using Gutenberg, code that is not intended to run on mount is running.

That being said, it's just generally a bad thing that hooks are running twice like this.

### Step-by-step reproduction instructions

1. Activate Gutenberg 19.0
2. Implement a simple on mount hook with a `console.log()` in it.
3. Check the different between your console when using the Gutenberg plugin and not.

### Environment info

- WordPress 6.6.1
- Gutenberg 19.1.0-rc.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Thanks for the report.

> `useEffect` hooks are running twice on mount when using Gutenberg 19.1.0-rc.1.

I think this is expected behaviour.

React StrictMode has been enabled by #61943. When StrictMode is enabled, React _intentionally_ renders a component twice to eliminate unsafe side effects.

https://react.dev/reference/react/StrictMode

**Comment by stokesman** [comment]
@tomusborne, I also wanted to mention StrictMode won’t be active unless `WP_DEBUG` and `SCRIPT_DEBUG` are true. That is, on production sites there’s no double rendering.

**Comment by tomusborne** [comment]
Thanks for the info, @t-hamano & @stokesman!

Disabling those constants does indeed "fix" the issue I was seeing. That being said, it looks like the `useRef()` pattern I showed above should still work in StrictMode, so I'll have to dig into that some more to see why that isn't the case.

Thanks again!

**Comment by t-hamano** [comment]
@tomusborne The double mount and ref issues in React 18 are also mentioned in the following discussions. They may provide clues to the solution.

- https://github.com/facebook/react/issues/24670
- https://github.com/reactjs/react.dev/issues/6123
