### ISSUE TITLE
Image Block: Google Docs-esque crop option

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#648]
Google Docs has a killer crop feature. Here's a video:

https://cloudup.com/cKyMJzWm4JJ

It would be really cool if, down the road, we could have a similar feature for our image block. Whether in the inspector, or as a crop button on the quick toolbar, it seems like our UI can carry this!

**Comment by karmatosed** [comment]
That is one nice crop!

**Comment by EphoxJames** [comment]
TinyMCE has the Image Tools plugin:
https://www.tinymce.com/docs/demo/image-tools/

**Comment by melchoyce** [comment]
There's a similar crop tool on WordPress.com: https://cloudup.com/cX4EpT5tNgT

**Comment by karmatosed** [comment]
Moving this one to ideas for future consideration.
