### ISSUE TITLE
Block Editor Color Palette: Only custom color palettes are displayed

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#64857]
### Description

If the custom color palette is defined in the global styles, the color palette in the block editor package only shows that custom color palette.

_Note that I'm talking about [the `ColorPalette` component in the block editor package](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/color-palette/), not [the `ColorPalette` component in the components package](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/color-palette)._

This issue can be seen in color inline formatting and Cover block placeholder. From what I've tested in Playground, this problem appears to have been occurring since at least WP6.3. As I recall, all palettes - theme, default, and custom - were displayed in the past.

### Step-by-step reproduction instructions

- Add a custom color palette with the global styles.
- Add a cover block or apply inline color to the text.

### Screenshots, screen recording, code snippet

Cover block and text color format. Only custom colors are shown:

![custom-color](https://github.com/user-attachments/assets/67083412-c5ab-4bd8-9fae-75b5eae2cfbe)

If no custom color is defined, the theme color is displayed:

![image](https://github.com/user-attachments/assets/65f73479-cd57-4fa1-907c-985edbe57d17)

Like color block support, it should display all three colors `default`, `theme`, and `custom`:

![image](https://github.com/user-attachments/assets/fefe11fe-0507-48f9-b694-0d65f058c28d)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by EddyBoels** [comment]
Same here. If you create a custom colour in the styles, then in a text block, the highlight option will only offer this colour without the basic palette.

**Comment by t-hamano** [comment]
I've confirmed that this issue has been occurring since at least WP 6.0.

**Comment by rohitmathur-7** [comment]
Hii @t-hamano ,
I was also checking this issue recently and found this related Issue from February:
https://github.com/WordPress/gutenberg/issues/59171

Here it is mentioned that we are getting the custom colors from this code:
```
$editor_settings['__experimentalFeatures'] = wp_get_global_settings();
// These settings may need to be updated based on data coming from theme.json sources.
if ( isset( $editor_settings['__experimentalFeatures']['color']['palette'] ) ) {
$colors_by_origin          = $editor_settings['__experimentalFeatures']['color']['palette'];
$editor_settings['colors'] = isset( $colors_by_origin['custom'] ) ?
	$colors_by_origin['custom'] : (
		isset( $colors_by_origin['theme'] ) ?
			$colors_by_origin['theme'] :
			$colors_by_origin['default']
	);
}
```

But when I was checking this in my local I modified this code to set the value of $editor_settings['colors']  as $colors_by_origin['theme'] for testing but still I was getting the custom colors only 🤔 .

**Comment by burnuser** [comment]
This is a very problematic bug, since providing custom colors in the color palette is a central function in the adaption of (FSE-) Themes.

But the described bug is still unresolved in WordPress 6.7. Beta 1

For me, personally, this bug makes the whole FSE color palette system unusable. So I have to use plugins or CSS to replace a so called FSE WordPress core function ins styles.

Am I really the only one who has a problem with this?

Is WP 6.7 really planed to ship with this bug unresolved?

**Comment by richtabor** [comment]
@AKSHAT2802 I left a review on https://github.com/WordPress/gutenberg/pull/65148. Would appreciate a follow-up to get this through; it's close. :)
