### ISSUE TITLE
Classic block: wp editor.css should be loaded as last stylesheet (see the "formatselect" dropdown)

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6485]
In Gutenberg, in the Classic block the `formatselect` dropdown items look like in the screenshot below on hover and focus:

![screen shot 2018-04-28 at 17 23 00](https://user-images.githubusercontent.com/1682452/39398175-9fd09a7e-4b0a-11e8-8c54-80ca02f0110d.png)

- the blue background is correct but the text color should be white
- notice also the select "box" appears to be empty (text is not visible)

In WordPress it looks like this:

![screen shot 2018-04-28 at 17 06 30](https://user-images.githubusercontent.com/1682452/39398185-ca76820c-4b0a-11e8-86ed-a5a9747997fe.png)

Seems to me this happens because in WordPress, `wp-includes/css/editor.css` is loaded _after_ the TiinyMCE skin stylesheet `wp-includes/js/tinymce/skins/lightgray/skin.min.css`. It makes sense, since `editor.css` contains custom styles for WordPress and thus overrides some TinyMCE rules.

Instead, in Gutenberg the stylesheets are loaded in a different order and the skin stylesheet is the last one. No idea why, I haven't looked at the code.

For a quick test, I've simply moved the stylesheets in the DOM in the correct order:

![screen shot 2018-04-28 at 17 25 25](https://user-images.githubusercontent.com/1682452/39398230-35648fdc-4b0b-11e8-959d-4d190cb121ed.png)

Aside: in Gutenberg, the `formatselect` doesn't show the actual theme styles as well, but I guess that's a separate issue related to all the Gutenberg blocks.

/Cc @azaozz

**Comment by designsimply** [comment]
Tested and confirmed that the classic block editor text formatting options are dark text on a dark blue background on hover.

![screen shot 2018-07-24 at tue jul 24 9 23 38 pm](https://user-images.githubusercontent.com/1119271/43178058-b2c78562-8f88-11e8-9c2f-d34dba2608e3.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14022&action=edit running WordPress 4.9.7 and Gutenberg 3.3.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

**Comment by afercia** [comment]
Related: the buttons color when active #6978

**Comment by azaozz** [comment]
This should be fixed in core. Opened https://core.trac.wordpress.org/ticket/46164 to track it there, see https://github.com/WordPress/gutenberg/pull/10281#issuecomment-459703793.
