### ISSUE TITLE
Video block: lack of padding when editing text tracks

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#64867]
### Description

There is a lack of padding, I think the screenshot speaks for itself

### Step-by-step reproduction instructions

1. Insert video block
2. Try to add text tracks
3. See lack of padding in the dropdown

### Screenshots, screen recording, code snippet

<img width="563" alt="Screenshot 2024-08-28 at 13 36 44" src="https://github.com/user-attachments/assets/fc6b8bac-7dba-4423-8553-fa2cd928bc16">

### Environment info

- Latest WP / Gutenberg

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
This was just fixed in this PR: https://github.com/WordPress/gutenberg/pull/64834

**Comment by swissspidy** [comment]
Amazing, thanks!
