### ISSUE TITLE
Page select UI is limited to 101 select items

### ISSUE THREAD

**Issue by Lewiscowles1986** [WordPress/gutenberg#6487]
## Issue Overview

From #6180 

Pages in page editor limits to 101 select items (probably 100 pages) when all top-level

## Steps to Reproduce (for bugs)

I've just tested using the following bookmarklet / console scripts

### Add a page every second

```
setInterval(function() { wp.apiRequest({method:'POST',path:'/wp/v2/pages',credentials:true,data:{'title':'REST-gen-'+Date.now(),'content':'empty','status':'publish'}}) }, 1000)
```

visiting /wp-admin/edit.php?post_status=publish&post_type=page I can see it creates 500+ pages, all published

visiting /wp-admin/post-new.php?post_type=page and running the following content script

### Count pages in side-bar of Gutenberg parent page

```
[].slice.call(document.querySelectorAll('#inspector-select-control-0 option')).length
```

shows 101 (no matter how many pages I add.

## Expected Behavior

Metabox to appear and behave like core WP (or better as I'm sure there is a bug in core for large numbers of pages).

## Current Behavior

Limited to 100 top level pages.

## Possible Solution

* Ideal-case: autocomplete
* Next-best: #6180 scroll-box
* Acceptable: core wordpress matched experience.

## Screenshots / Video

N/A (content script to repeat above), not a visual bug

## Related Issues and/or PRs

#6180 
#4622 
#4022
#5820

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] PR

**Comment by Lewiscowles1986** [comment]
Using classic editor `/wp-admin/post-new.php?post_type=page&classic-editor`

```
[].slice.call(document.querySelectorAll('#parent_id option')).length
```

reports 588, which matches with the 587 pages I automatically added using the content script

**Comment by Lewiscowles1986** [comment]
Sure thing @danielbachhuber 

I only came to this from 6180 after wondering what was done for `parent_id` mechanism, as it's something I use a lot for hobbying.

**Comment by Lewiscowles1986** [comment]
Sorry, why is this marked as closed? #6657 doesn't fix this issue

**Comment by danielbachhuber** [comment]
@Lewiscowles1986 Can you explain why #6657 doesn't fix the issue?

**Comment by Lewiscowles1986** [comment]
Yes, this is regarding the gutenberg editor not loading the paged resources. When I build #6657 I still only get 101 pages in the parent page selection in Gutenberg. The selector I'm using above still shows 101

**Comment by Lewiscowles1986** [comment]
on second thought, this may be related to #6488. I get a whole bunch of noise in the browser console when I upload gutenberg packaged from npm or the bin folder...

![image](https://user-images.githubusercontent.com/2605791/39935734-e0dab0c2-5541-11e8-9ec7-598d335ce17f.png)

```
index.js?ver=1526056183:1 The hook name can only contain numbers, letters, dashes, periods and underscores.
```

Just re-built and still doesn't work, but now doesn't show parent_id field either

![image](https://user-images.githubusercontent.com/2605791/39935788-177ece24-5542-11e8-9ba2-0d2fd7e65b6d.png)

### specific broken script part

```
var u = function(n) {
            return "string" != typeof n || "" === n ? (console.error("The hook name must be a non-empty string."),
            !1) : /^__/.test(n) ? (console.error("The hook name cannot begin with `__`."),
            !1) : !!/^[a-zA-Z][a-zA-Z0-9_.-]*$/.test(n) || (console.error("The hook name can only contain numbers, letters, dashes, periods and underscores."),
            !1)
        };
```

**Comment by danielbachhuber** [comment]
Ok. This seems like it's specific to your environment, not this particular issue. Feel free to pop into `#core-editor` if you need help debugging.
