### ISSUE TITLE
npm run package-plugin failed

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#6488]
Hi,

I can't run `npm run package-plugin` because it's removing the node_module folder and causing error. Thanks!

**Comment by Lewiscowles1986** [comment]
Whenever I make Gutenberg from a non-clean tree I get a series of errors once the plugin is uploaded and Gutenberg editor loads. 

`The hook name can only contain numbers, letters, dashes, periods and underscores.` 

Even if the only edit is a newline character. 

Running `git reset HEAD~1` doesn't fix the problem.

**Comment by Lewiscowles1986** [comment]
I've also repeated this in a vagrant to make sure it's not one of the many OS patches my system has had me install. Happy to contribute a Vagrant file (or receive a repeatable environment)

**Comment by danielbachhuber** [comment]
@phpbits It's not clear to me what this problem is, or how you might suggest fixing it. Can you clarify with further detail?
