### ISSUE TITLE
Editor Bottom Margin/Padding Problem

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#6490]
## Issue Overview

The bottom edge of the edit window can overlap the area at the bottom. This is most noticeable when a meta-box is displayed (e.g., Yoast SEO). A contrasting BG color also makes this evident.
See the screen shot below. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Screenshots / Video

![editor-bottom-edge](https://user-images.githubusercontent.com/2816397/39408940-7638d2bc-4b9b-11e8-9d9b-c6c596689df6.jpg)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
I am half wondering if this relates to: https://github.com/WordPress/gutenberg/issues/7500. That one is about floats but you can get a similar issue.

**Comment by karmatosed** [comment]
I think this does relate to the above issue so lets solve that and review.
