### ISSUE TITLE
Plugin metabox regression prevents tablet and mobile views from working 

### ISSUE THREAD

**Issue by vcanales** [WordPress/gutenberg#64912]
### Description

From https://core.trac.wordpress.org/ticket/61693

> @ironprogrammer Indeed, in [Playground running 6.6 and Yoast SEO](https://playground.wordpress.net/?theme=neve&plugin=wordpress-seo&wp=6.6&url=%2Fwp-admin%2Fpost.php%3Fpost%3D2%26action%3Dedit), the tablet/mobile views do not appear to work (compare to [Playground running 6.5](https://playground.wordpress.net/?theme=neve&plugin=wordpress-seo&wp=6.5&url=%2Fwp-admin%2Fpost.php%3Fpost%3D2%26action%3Dedit)). This looks to be related to the display of the plugin's meta box, and IMHO should be considered a regression.

### Step-by-step reproduction instructions

- Follow the [Playground Link](https://playground.wordpress.net/?theme=neve&plugin=wordpress-seo&wp=6.6&url=%2Fwp-admin%2Fpost.php%3Fpost%3D2%26action%3Dedit) for a site with YoastSEO and the Neve theme activated.
- Create a New Post
- Try to switch to the Mobile or Tablet news
- Notice that the editor disappears

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/52b4c154-5fa2-4f6a-af42-0c0bcfd33924

### Environment info

- WordPress 6.6
- YoastSEO and Neve theme activated.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by helenaartmann** [comment]
I tested using your link/configuration and got the same result (no tablet or mobile view available). 

I also tested with Yoast deactivated, and we can see both the tablet and mobile view.

**Comment by t-hamano** [comment]
This is a known issue and was reported here: https://github.com/WordPress/gutenberg/issues/63708
This issue has also been fixed and has been given a backport label: https://github.com/WordPress/gutenberg/pull/63724#issuecomment-2246838419

**Comment by vcanales** [comment]
@t-hamano, thank you! I've added #63708 to track it for the coming release.
