### ISSUE TITLE
"Edit Original" Pattern keeps Post MetaBoxes

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#64914]
### Description

When writing a Page or Post, and clicking "Edit Original" on a synced pattern, the editor shifts into editing the Pattern, but metaboxes associated with the Post remain. This creates a very confusing screen, as it looks like the metaboxes are associated with the Pattern, when they shouldn't be.

### Step-by-step reproduction instructions

1. Insert a synced pattern onto a Post, while also using a plugin that has (legacy?) metaboxes.
2. Click 'Edit Original' of the synced pattern.

### Screenshots, screen recording, code snippet

For comparison, this is the screenshot of simply adding a new Pattern. Nice and clean!
![new-pattern](https://github.com/user-attachments/assets/818d803e-185a-41b1-8081-991f5a4225a3)

However, when you Edit Original from editing a Post, you get this mess:
![edit-inline](https://github.com/user-attachments/assets/04ab5291-14b1-422a-9bb7-1de3cf82286e)

The metaboxes now all look associated with the Pattern (and will retain any values that had been set previously.)

### Environment info

WordPress 6.6.1, no Gutenberg plugin.

Obviously I have not tested with all plugins deactivated, because I need them to create the metaboxes, but I checked the box because it's required. 🤷‍♂️

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by lgladdy** [comment]
You can easily test this by having an ACF field group associated with a post, then edit the synced pattern.

It looks like the legacy backcompat metabox layer isn't removed when you drop into the pattern editor.

**Comment by ericdye** [comment]
I would also add that if there is more content within the pattern or more meta boxes, the synced pattern content is "covered" and cannot be edited in any way. My most recent report from a Newspack user expected there to be a scrollbar, but there is not.

**Comment by smerriman** [comment]
This has been an open issue since July: https://github.com/WordPress/gutenberg/issues/63143

Hopefully this one gets more traction than that, as it hasn't been resolved in 6.6.2.
