### ISSUE TITLE
Provide mechanism for returning to post after editing synced pattern

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#64915]
## What problem does this address?

When you click 'Edit Original' of a synced pattern while editing a post, the editor shifts to editing only the Pattern - everything about the Post disappears. Both before and after updating the Pattern, I'd like to be able to go back to the original Post.  I understand that the 'back' button doesn't work, as a known and longstanding issue, but there needs to be some kind of button or link to return to the original post (both before and after Saving).

## What is your proposed solution?

I'll leave the specifics to the UI/UX experts, but there should be some way to return to the post I was editing.

**Comment by helenaartmann** [comment]
Hi [MadtownLems](https://github.com/MadtownLems),

I tested it using https://playground.wordpress.net/, PHP 8.0, WP 6.6, and the "back" link available when you are editing the synced pattern will bring you back to the post you were editing/creating. 

Could you confirm if this is what you’re trying to achieve?

<img width="1568" alt="Screenshot 2024-08-29 at 2 56 29 PM" src="https://github.com/user-attachments/assets/22e7fac4-8eb7-4e67-9181-f99abe5673ff">

**Comment by MadtownLems** [comment]
Aha! We actually don't display the Command Palette in the Post Editor, so I missed it. I wish it weren't bundled there, especially because I know there's talk of adding the ability to disable the Command Palette more easily - but I see that it is currently possible for most users. Thank you!!

**Comment by helenaartmann** [comment]
You are welcome! 
I will close this issue as resolved.
