### ISSUE TITLE
Pre-publish checks showing template part details

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#64913]
This is a very obscure bug; if you open the pre-publish checks, then switch immediately to edit a template part, the pre-publish panel will show broken/incorrect information about the template part. Here's a video:

https://github.com/user-attachments/assets/7caeacf8-662f-4396-a381-82916995d518

### To re-produce

1. Edit a draft page
2. Ensure pre-publish checks are enabled in editor preferences
3. Ensure template preview is toggled on so you can select the header or footer
4. Select the header (or footer) then click 'Edit' in the block toolbar
5. Notice the pre-publish panel contents update to reflect the template part

### What I'd expect

By navigating away from editing the page I'd consider the publish flow interrupted. Consequently I'd expect the pre-publish panel to close.

**Comment by sarthaknagoshe2002** [comment]
@jameskoster Thank you for reporting this bug! I have submitted a PR to fix the issue.
