### ISSUE TITLE
DataViews: font size of filter chip

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#64925]
### Description

The font-size of the filter chip is bigger than the rest of the components:

<img width="1044" alt="Captura de ecrã 2024-08-30, às 13 48 29" src="https://github.com/user-attachments/assets/7b8adb0a-12b7-4ecf-90c9-52e28301cc8e">

### Step-by-step reproduction instructions

Go to the storybook and search for [the DataViews component](https://wordpress.github.io/gutenberg/?path=/docs/dataviews-dataviews--docs).

**Comment by oandregal** [comment]
I ran into this when trying to use DataViews in a 3rd party integration. cc @jameskoster

**Comment by jameskoster** [comment]
Not only the font size, the chip itself is too large. 

Seems the font size of several data view elements in the site editor are inherited from the wp-admin stylesheet. I suppose we need to update to provide local styles.
