### ISSUE TITLE
Grid: In RTL languages, the resize handles point in the opposite direction

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#64931]
### Description

In the Grid block, we can change the Row Span or Column Span via the resize handles.

Vertical resizing works correctly in RTL languages, but horizontal resizing expands in the opposite direction to the mouse movement.

### Step-by-step reproduction instructions

- Insert a Grid block.
- Resize the inner block horizontally.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/4daf3538-fc21-4276-912e-37db928b5da5

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by rohitmathur-7** [comment]
@t-hamano I would like to take up this issue.
Thanks.

**Comment by rohitmathur-7** [comment]
Hii @t-hamano ,
I have raised a PR for the issue can you please check and let me know if anything else is needed.
Thanks.
