### ISSUE TITLE
Link popover options hidden or cut off by meta boxes at bottom of editor

### ISSUE THREAD

**Issue by graylaurenm** [WordPress/gutenberg#64938]
### Description

**What I expect to happen:**
Users can see and edit and popup settings boxes in the post editor regardless of where the block is positioned.

**What is currently happening:**
If a user adds a hyperlink to text that is at the bottom of the post editor–near the metaboxes below the editor–the link settings popup is displayed below those metaboxes. 

**Modes impacted:**
- Default
- Spotlight
- Fullscreen

(Not Distraction free)

**Closest issue I could find:** https://github.com/WordPress/gutenberg/issues/51225

### Step-by-step reproduction instructions

1. Create a new site
2. Install "Post Meta Data Manager"
3. Add a new post and put a text link in it
4. Insert a bunch of empty paragraphs above it, so the link is way at the bottom, flush with the meta boxes
5. Click on the linked text
6. Notice that no pop-over options are visible

### Screenshots, screen recording, code snippet

**Screnshot:** https://ocl.ink/i/BQfniH

**Video:**
[Screen Recording at 2024-08-30 at 10-36-06.webm](https://github.com/user-attachments/assets/a010ff84-8524-4053-9aac-cc3a582bcd45)

### Environment info

Confirmed this happens with a fresh install on 6.6.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This problem has been fixed in https://github.com/WordPress/gutenberg/pull/63939. This fix will be available in the next minor WordPress release.
