### ISSUE TITLE
Sidebar "Extended Settings" may be empty when meta boxes are hidden in the Screen Options

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6495]
To reproduce:
- activate a plugin that adds a meta box in the sidebar
- in the Classic editor, go to the Screen Options and uncheck the related checkbox to hide the meta box
- go in Gutenbreg
- in the sidebar, there's the "Extended Settings" panel
- click on it to expand it: it's empty

So when all the sidebar meta boxes are "unchecked" in the Screen Options, the "Extended Settings" panel is still rendered. Ideally, it should check if there's at least one "visible" meta box.

Note: "unchecked" meta boxes are hidden with the `hide-if-js` CSS class.

**Comment by danielbachhuber** [comment]
Related #5841
