### ISSUE TITLE
Tabs: Keyboard navigation and indicator issues in RTL languages

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#64963]
### Description

I think there are two problems with the `Tabs` component in RTL languages.

### ⚒️ Keyboard Navigation

- https://github.com/WordPress/gutenberg/pull/66201

Note: This problem occurs not only in the Tab component, but also in the following two components:

- [x] `ToggleGroupControl`: https://github.com/WordPress/gutenberg/pull/65735
- [x] `RadioGroup` (deprecated): https://github.com/WordPress/gutenberg/pull/66202

When I press the left or right key, I expect the focus to move to the tab in that direction. However, in RTL languages, the direction of the key and the direction in which the focus actually moves are opposite:

https://github.com/user-attachments/assets/76475558-6757-4969-9796-f206aa46155e

From what I understand, this component is based on `@ariakit/react`.

Therefore, when I tested the ariakit `Tab` component itself, the problem seemed to be reproduced in the same way. I tested it by adding `direction:rtl` to the `html` element on [the component preview page](https://ariakit.org/components/tab):

https://github.com/user-attachments/assets/5d0e8bf2-556a-4911-b35a-60ece868f818

### ✅ Indigator position

(Fixed in #64926)

When the browser width changes, the indicator position is misaligned:

https://github.com/user-attachments/assets/8bb2855d-bdff-4862-8e68-504ce212ac66

Probably in RTL languages, ​​we need to calculate the right position instead of the left position:

https://github.com/WordPress/gutenberg/blob/2157b85f7dbbfb52903a430c4946cfba27224b09/packages/components/src/tabs/tablist.tsx#L81

### Step-by-step reproduction instructions

- Access https://wordpress.github.io/gutenberg/?path=/story/components-experimental-tabs--default&globals=direction:rtl.
- Keyboard navigation issue: Focus on one of the tabs and press the left or right key.
- Indicator position issue: Resize your browser width and check the position of the indicator.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by DaniGuardiola** [comment]
I think we should file the keyboard issue in the Ariakit repo, cc @diegohaz for visibility too.

**Comment by DaniGuardiola** [comment]
All indicator issues are fixed in #64926.

**Comment by diegohaz** [comment]
The [`rtl`](https://ariakit.org/reference/tab-provider#rtl) prop must be explicitly set. Related: https://github.com/ariakit/ariakit/issues/2930#issuecomment-1755593831

**Comment by t-hamano** [comment]
I found that this problem occurs not only in the `Tabs` component but also in other components. As far as I could tell, it occurs in the following two components:

- `ToggleGroupControl`: https://wordpress.github.io/gutenberg/?path=/story/components-experimental-togglegroupcontrol--default&globals=direction:rtl
- `RadioGroup` (deprecated): https://wordpress.github.io/gutenberg/?path=/story/components-radiogroup--default&globals=direction:rtl

**Comment by mirka** [comment]
> * `ToggleGroupControl`: https://wordpress.github.io/gutenberg/?path=/story/components-experimental-togglegroupcontrol--default&globals=direction:rtl

ToggleGroupControl bug fix in #65735

**Comment by ciampo** [comment]
- `Tabs` and `TabPanel` fix in https://github.com/WordPress/gutenberg/pull/66201
- `RadioGroup` fix in https://github.com/WordPress/gutenberg/pull/66202

**Comment by ciampo** [comment]
Closing this issue as all flagged components have been improved
