### ISSUE TITLE
Is there any way to reorder core components block editor control in the right panel

### ISSUE THREAD

**Issue by techniway** [WordPress/gutenberg#64964]
**i would like to reorder components control** (inside the editor sidebar) in order to make things more simple to my customers .
After searching the internet, and also this repostory code **i havent found any hooks that allow me to that**, i am pretty new to react and redux so i might have missed something ?, please tell me if there is any way to accomplish this feature, or if not if there is any plan to support this in the future ?

ps : i have found the block_editor_settings_all php hooks that allow me to disable tab, and i also known how to add custom controls

**Comment by techniway** [comment]
I managed to do it via css :), i will close the question

**Comment by skorasaurus** [comment]
closing per request of author
