### ISSUE TITLE
How to get custom image sizes added with add_image_size()

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#6499]
## Issue Overview

Fiddling with the gallery block code I managed to get the thumbnail size of images in addition to their full size using the following code:

```
onSelectImages( images ) {
    this.props.setAttributes( {
        images: images.map( ( image ) => ( { ...pick( image, [ 'alt', 'caption', 'id', 'url' ] ), thumbnail: get( image, 'sizes.thumbnail.url' ) } ) )
    } );
}
```

But checking the input `images` parameter I see that there are no references to custom sizes added with the `add_image_size()` function, just the core ones. Is this the expected behavior?

**Comment by danielbachhuber** [comment]
Hi @mrleemon,

The custom image sizes will only appear if they've been generated for the image. [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) is a plugin that lets you regenerate image sizes from the admin, and `wp media regenerate` is its WP-CLI equivalent if you have command-line access to the site.

**Comment by mrleemon** [comment]
I remember using the Regenerate Thumbnails to generate the custom size thumbnails and after that still seeing just the core size images. I'll try again, maybe that part of the GB code has changed recently.

**Comment by mrleemon** [comment]
The `sizes` var in the gallery block just contains the urls for the full, large, medium and thumbnail sizes. The dropdown size selector in the image block contains the full, large, **medium-large**, medium, thumbnail sizes and the **custom size** added with `add_image_size()`.
It seems that you are doing something different to get the sizes in both blocks.

**Comment by danielbachhuber** [comment]
> The dropdown size selector in the image block contains the full, large, medium-large, medium, thumbnail sizes and the custom size added with add_image_size().

I can confirm this behavior:

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/36432/40666580-f07d0d78-6314-11e8-9e50-2295ecac6829.png">

> The `sizes` var in the gallery block just contains the urls for the full, large, medium and thumbnail sizes.

I'm not sure I follow what you mean by this. Can you clarify?

**Comment by mrleemon** [comment]
The `images` var in the GALLERY block just contains the full, large, medium and thumbnail sizes, not the medium-large nor the custom sizes added via the `add_image_size()` function.

**Comment by danielbachhuber** [comment]
@mrleemon Ok. Can you take a step back and tell me what you're trying to do, and why you're directly modifying the gallery block?

**Comment by chrisvanpatten** [comment]
Perhaps related to #1450?

**Comment by danielbachhuber** [comment]
> Right now, with the old `[gallery`] shortcode one can do something like this easily:
> But not with the new gallery block because one cannot select the source image size.

Makes sense, thanks for clarifying.

> I'd like to be able to select the source image size via a dropdown like the image block or via directly modifying the code of the gallery block.

Directly modifying the gallery block code is strongly discouraged. Being able to select the image size is tracked with #1450

**Comment by Shanery** [comment]
I know that it seemed to work in the past but now custom image sizes are not working.

![image](https://user-images.githubusercontent.com/15805777/55511782-69345600-562f-11e9-8c6c-792e9123ea2d.png)

![image](https://user-images.githubusercontent.com/15805777/55511885-ac8ec480-562f-11e9-9063-086d7531b982.png)

**Comment by tedsecretsource** [comment]
@Shanery I got the custom image sizes to appear in the admin by adding:
```php
add_action( 'admin_init', function() {
	$custom_sizes['my-custom-sizes'] = 'My Custom Size';
	add_filter(
		'image_size_names_choose',
		function( $sizes ) use ( $custom_sizes ) {
			return array_merge( $sizes, $custom_sizes );
		}
	);
});
```
Remember that they will only show up for images that have been upload _after_ the new image sizes have been defined (IIRC - HTH).

@danielbachhuber Any idea why the custom image sizes aren't showing up in wp-cli? I'm only seeing the default sizes, e.g.: thumbnail, medium, medium_large, large, and full.
