### ISSUE TITLE
Zoom out: missing animation when moving patterns in Firefox

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#65014]
Using WordPress 6.6.1 and Gutenberg 19.1, when moving patters in zoom out, the animation is missing that's normally shown in other browsers, like Safari or Chrome:

https://github.com/user-attachments/assets/d1cc250b-f830-43a8-ad06-4b61381244c3

**Comment by talldan** [comment]
I started looking into this issue, but it's not something I can reproduce:

https://github.com/user-attachments/assets/c78a4579-b98c-4ef3-8006-efa135c9676b

**Comment by richtabor** [comment]
I also could not replicate this. 

https://github.com/user-attachments/assets/1968298b-2542-4320-9e96-cb32e210a7e6

**Comment by annezazu** [comment]
Weird. I wonder what changed. I'll close this out and we can always reopen if someone else finds it.
