### ISSUE TITLE
New block box is not shown fully on screens with low height

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#6504]
## Issue Overview
When adding a block and there is not enough space underneath so the box open above but unfortunately there is not enough space there too

Gutenberg 2.7.0

## Steps to Reproduce (for bugs)
1. Set window size to 500px
2. Add a new block.

Browser: Chrome on OSX

## Screenshots / Video
![image](https://user-images.githubusercontent.com/1785641/39430233-932bb6d0-4c8d-11e8-90ba-fc3105a58ecb.png)

**Comment by ocean90** [comment]
Noticed this too. Happens usually when I have Chrome's developer tools open.
