### ISSUE TITLE
Unrelated meta data gets saved with default value

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#6505]
## Issue Overview

If you have a block which stores its data in post meta and also registered other post meta for REST API usage, the other post meta gets also updated with the default value.

## Steps to Reproduce (for bugs)
1. Example plugin: https://gist.github.com/ocean90/7431114b689f1e0686f4f5dfa88838df
2. Activate plugin
3. Add the new block and fill the input
4. Save draft and inspect the save request
5. Notice that the meta entry includes all three meta keys while only one has been changed

## Expected Behavior
Only changed meta data should get saved.

## Possible Solution
I'm not sure yet if that's a limitation of the REST API and/or if Gutenberg can enhance that behaviour.

## Related Issues
* #5626

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by felixarntz** [comment]
I agree with @ocean90 in that matter. I think Gutenberg should check if the meta value is different from the initial value retrieved from the API before it passes it there.

**Comment by aduth** [comment]
Closed by #10827.
