### ISSUE TITLE
Site Editor: Inserter is confusing when editing pages

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#65063]
### Description

When opening a Page for editing in the Site Editor, the inserter tab for Patterns is empty, and while blocks are shown clicking them doesn't seem to do anything.

The reason is that the user is required to click into the Page Content block first to be able to insert blocks. This isn't very clear though, I think instead the editor should default to a better insertion point (maybe at the end of Page Content) rather than no insertion point at all.

### Step-by-step reproduction instructions

1. Open the Site Editor
2. Go to pages on the left side
3. Select a page for editing
4. Once in the editor, open the main inserter sidebar
5. Try inserting blocks or patterns, find that you can't

### Screenshots, screen recording, code snippet

<img width="348" alt="Screenshot 2024-09-04 at 10 12 45 AM" src="https://github.com/user-attachments/assets/64588bcb-70fb-4ba3-aa0b-eb2f1e4aae6b">

### Environment info

Mac OS / Brave
Tested using latest trunk

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by talldan** [comment]
This did work previously, and it worked the way described above. It was a fairly recent regression.

I tracked it down to #64048

**Comment by annezazu** [comment]
Could this be related? https://github.com/WordPress/gutenberg/issues/35530 Or rather, can we fix it at the same time? :)

**Comment by talldan** [comment]
I think it is related, the same PR introduced this bug and the glitchy behavior when hovering blocks.

I'm not sure if solving it would fix the original issue reported in #35530 (possibly it had already been fixed by https://github.com/WordPress/gutenberg/pull/62169).

**Comment by talldan** [comment]
https://github.com/WordPress/gutenberg/pull/65208 should have fixed this.
