### ISSUE TITLE
Remove Text Columns block and convert existing ones to Columns + nested Paragraph blocks

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6506]
## Issue Overview
The Text Columns blocks is pretty much useless. With the Columns block having been added, there is no reason for it to exist. It is not even responsive, so it does not work well at all on mobile. <del>On top of that, the block is currently full of bugs.</del>

When WordPress 5.0 is released, I do not think it makes sense to ship this block, since the Columns block does everything it does and more. Actually, I would not ship WordPress 5.0 with the Columns block as it is right now since it also lacks responsive columns. (See #6048.) If the Columns block does not have responsive columns by the merge proposal, then it may make more sense to just leave it out of WordPress 5.0 rather than ship a pretty much useless block, but in that case, it makes no sense to ship the Text Columns block either since it is even worse.

Is there any reason to keep this block anymore?

To test backwards compatibility with completely-removed blocks and also if backwards compatibility with older Gutenberg versions is desired at this point in development, Text Columns blocks could be converted to Columns blocks with nested Paragraph blocks.

## Related Issues and/or PRs
- #2651
- #4962

**Comment by GlennMartin1** [comment]
I agree - this should happen soon so new users (i.e. Try Gutenberg) don't see two types of Columns blocks.

At the same time, remove the "beta" label from the new Columns block.

**Comment by SuperGeniusZeb** [comment]
@GlennMartin1 I would be cautious about removing the “Beta” label from the Columns block until it supports responsive columns (see #6048) and non-equal width columns (see #7315).

**Comment by mtias** [comment]
We should do this before the "try" notice goes live in WP core.

**Comment by brandonpayton** [comment]
Matías weighed in on this and prefers not to convert. For now, we'll remove the Text Column block from the inserters, so the existing block edit interface will remain available to early adopters. Later, we can remove the block entirely, and existing instances of the block will converted to Classic blocks.

Here's the Slack thread for reference:
https://wordpress.slack.com/archives/C02QB2JS7/p1531922466000197?thread_ts=1531921831.000375&cid=C02QB2JS7

**Comment by chrisvanpatten** [comment]
Should a deprecation notice be spit out to the console so there's some warning? Not sure it matters but maybe worth considering.

**Comment by brandonpayton** [comment]
> Should a deprecation notice be spit out to the console so there's some warning? Not sure it matters but maybe worth considering.

That seems like a good idea, @chrisvanpatten. I added a deprecation warning to the PR.
