### ISSUE TITLE
[Block Bindings] Human readable label for Meta fields

### ISSUE THREAD

**Issue by dannyreaktiv** [WordPress/gutenberg#65066]
## What problem does this address?
Block bindings are a very powerful tool, and the UI is good, but the experience of assigning a meta field means the user sees the meta key.

![Screenshot 2024-09-03 at 7 53 22 AM](https://github.com/user-attachments/assets/3e28aacc-0777-4989-82fd-af2e8a24a621)

## What is your proposed solution?

I propose adding a `label`/`title`/`name` to the `$args` array in `register_meta()` that would then be exposed in the Block Bindings and available for use elsewhere in WordPress.

**Comment by SantosGuillamot** [comment]
Personally, I think that would totally make sense, not only for block bindings but potentially for other use cases as well. I'll try to get something working if I find time to see what it could look like.

**Comment by SantosGuillamot** [comment]
I've started exploring this in [this core pull request](https://github.com/WordPress/wordpress-develop/pull/7298) that I hope can help with the discussion. I'll try to get the respective one in Gutenberg.

**Comment by SantosGuillamot** [comment]
I've started another PR in Gutenberg to see how it could look like and the necessary changes: https://github.com/WordPress/gutenberg/pull/65099

**Comment by dannyreaktiv** [comment]
Wow. Thank you!
