### ISSUE TITLE
List can't evaluate the "start" attribute, and throws an error on visual editor. 

### ISSUE THREAD

**Issue by kosakk** [WordPress/gutenberg#65085]
### Description

I wanted to create an ordered list with a count that would start from something different than the default of 1. I am pretty sure I checked all the available options in the visual editor, but I couldn't find any options there for that. So I jumped in the code editor mode, and manually added that to the <ol> element. So the default

`<ol class="wp-block-list"><!-- wp:list-item -->`

would now look like this: 

`<ol class="wp-block-list" start="2"><!-- wp:list-item -->`

When I returned to the visual editor, I would encounter a grayed-out preview of the output, and above it a bordered block with the message "This block contains unexpected or invalid content." and a button to "Attempt Block Recovery". 

Clicking on that would erase my manual changes and start the counting from 1. 

Upon saving the post as draft and previewing it in the front end it would load as needed. 

Since "start" is a standard HTML attribute for an ordered list, I would expect it to work correctly even though it might not be offered as an option in a visual editor sub-menu, since it's not very widely used. 

### Step-by-step reproduction instructions

1. Add an ordered list item. 
2. Add a lit item.
3. Add some text.
4. Explore the various available options to set an explicit start for the ordered list. 
5. Switch to code editor mode from the top right-hand-side menu. 
6. Add a ' start="2" ' attribute to the <ol> element. 
7. Return to the visual editor mode. 

### Environment info

version 6.6.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Hi @kosakk,

The list block already supports the `start` attribute, which can be set from the block sidebar. Note that you need to select the List block, not the List Item block.

![list](https://github.com/user-attachments/assets/4278a4d1-bdbc-4814-b7d0-213a58076ee3)
