### ISSUE TITLE
Site Editor: Canvas width glitch when selecting 'Browse Styles' then closing inserter sidebar

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#65080]
### Step-by-step reproduction instructions

1. Open the Site Editor and edit a page
2. Select the + button on the top bar to open the Inserter sidebar
3. Select the Styles button on the top bar to open the global styles sidebar
4. Select 'Browse Styles' in the global styles sidebar, observe the canvas zooms out
5. Now close the Inserter sidebar, observe that the canvas looks unusual with scrollbars moved into the middle of the viewport

If you compare this to engaging and disengaging 'Browse styles' without the inserter sidebar open, you'll see that it looks completely different, the scrollbars stay at the edge of the screen.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/1ce5135e-2b64-4acc-9574-50d6f8529b7f

### Environment info

Brave / Mac OS
Latest Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by stokesman** [comment]
Here’s latest trunk showing the same with the newer toggle button (and in the Post editor):

https://github.com/user-attachments/assets/b49ee030-bb56-44b9-80a4-da5e5d8a7c71

That button seems like it will increase exposure to this bug.

--- 

<details><summary>
#63390 under the same scenarios
</summary>

https://github.com/user-attachments/assets/0aee720b-6bad-4cc0-98bf-9a603fbe703e

</details>

**Comment by talldan** [comment]
This isn't working too badly at the moment, but that seems mostly because Zoom Out mode disengages whenever trying to reproduce the issue. Sometimes I think it disengages when it shouldn't (like if you still have browse styles or the pattern inserter open).

**Comment by draganescu** [comment]
I don't think this is an issue anymore. It used to be reproducible using the same steps but using the list view instead of the inserter.

**Comment by draganescu** [comment]
I will close this as it seems to be gone.
