### ISSUE TITLE
Align template part edit flows?

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#65096]
Currently the experience around editing template parts differs based on whether you're editing a page or a template.

### Page editing

When editing a page, template parts can be selected but not edited until you click 'Edit' in the block toolbar, or double-click:

https://github.com/user-attachments/assets/2bea401a-27d4-46c4-b40f-02bdc69ef648

### Template editing

When editing a template it's possible to select and directly manipulate blocks inside template parts:

https://github.com/user-attachments/assets/79504231-994d-4403-8021-bf7190dc8bc9

---

I'm not sure that the differences are warranted, and would lean towards aligning around the page editing experience. 

cc @WordPress/gutenberg-design

**Comment by fabiankaegy** [comment]
My vote would be to revert the decision to have template parts be selectable in the "template-locked" editing mode. That should also resolve this

**Comment by noisysocks** [comment]
To me the page editor and template editor are aimed at different groups. The former is primarily for users building their website and the latter is primarily for theme authors. If anything I'd like to see even further distinction between these two editors. For example the page editor could be based around inserting patterns / zoomed out mode.

**Comment by jameskoster** [comment]
> My vote would be to revert the decision to have template parts be selectable in the "template-locked" editing mode

This would make quickly editing the header / footer more convoluted which feels like a pretty big usability trade-off to me.

> To me the page editor and template editor are aimed at different groups.

That is a good observation, but I think there are a few templates that feel more like virtual pages, and likely fit the mental model for page editing. Examples being; Blog Home, Front Page, Taxonomy archives (post category archives etc.). 

Related: there is active discussion around surfacing the Homepage (when set to display latest posts) in the Pages list in https://github.com/WordPress/gutenberg/issues/60772.

For me the benefit in aligning around the page-edit experience is two-fold:

1. Consistency; it can be quite confusing to see the same block behave differently without any obvious reason.
2. Clarity; A drawback to the current template-edit experience is that it's easy to confuse the template part as being part of the template, and mistakenly miss that you're editing a global item.

Zoomed-out feels useful in both contexts.

**Comment by jameskoster** [comment]
Closing this as it is likely superseded by https://github.com/WordPress/gutenberg/issues/65698.
