### ISSUE TITLE
Remove purple coloring from DocumentBar

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65168]
As an affordance, the purple color applied in the DocumentBar is not helping to communicate the "global" nature of templates, synced patterns, and template parts. It's just not connective in this presentation, and with the addition of post type labels in https://github.com/WordPress/gutenberg/issues/65167 — arguably, not necessary. 

I propose we simplify a bit, removing the purple color within the DocumentBar. 

### Current 

<img width="800" alt="current" src="https://github.com/user-attachments/assets/5a301350-0bc6-423c-b71b-3c43fe4dc15d">

### Proposed 

<img width="800" alt="proposed" src="https://github.com/user-attachments/assets/8b031552-8a84-4e10-b5ee-a327f55bcc56">

**Comment by creativecoder** [comment]
Looking at this, I see we use `color: var(--wp-block-synced-color);` in a number of other places, too, here are some that I found:

**List View Template Parts**
<img width="347" alt="image" src="https://github.com/user-attachments/assets/a8d22d7e-fe0d-44ae-89a5-6316b56c3b90">

**Template Part Block Toolbar**
<img width="314" alt="image" src="https://github.com/user-attachments/assets/5f059d82-39d3-4937-b2df-b69e829c42e8">

**Template Part Block Info**
<img width="266" alt="image" src="https://github.com/user-attachments/assets/5b3fdf2c-4af4-4388-98b0-a2e92e7e493f">

**Template Title**
<img width="275" alt="image" src="https://github.com/user-attachments/assets/5e060e21-3ca0-404d-a97b-d415cec7c0bb">

---

I think this should be consistent, e.g. if the color isn't used for template text in the DocumentBar, then don't use it in the Template info (sidebar) either.

Same for the icon, (unless it's removed from the DocumentBar, see https://github.com/WordPress/gutenberg/issues/65167)

**Comment by richtabor** [comment]
> I think this should be consistent, e.g. if the color isn't used for template text in the DocumentBar, then don't use it in the Template info (sidebar) either.

This yes, but the template part block icon is block-level, so I think it's fine to leave it purple in canvas—for now at least.
