### ISSUE TITLE
Distraction free: keyboard shortcuts conflicts with system-level shortcut in Safari on macOS

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#65160]
The current keyboard shortcut for distraction free (⇧⌘\) conflicts when used in Safari on MacOS:

https://github.com/user-attachments/assets/2a4a3cd4-d4dd-498f-859c-df9efebd73b2

As you'll notice in the[ Apple docs](https://support.apple.com/guide/safari/keyboard-and-other-shortcuts-cpsh003/mac) under Tabs it handles "Show tab overview".

**Comment by Mamaduka** [comment]
Related #15190.

**Comment by draganescu** [comment]
I'll close this for the older #49671
