### ISSUE TITLE
Link Control Hidden behind Metaboxes

### ISSUE THREAD

**Issue by eToolSmith** [WordPress/gutenberg#65164]
### Description

Whenever you have a link at the bottom of the content within the Gutenberg block editor and try to access the link controls to that link it will be hidden behind the metaboxes at the bottom which is not ideal.

### Step-by-step reproduction instructions

Edit a Post with a Standard Metabox after the Gutenberg Content(e.g. ACF Field Group Metabox).

Add link to the very end of the content, make sure you add new lines above it to push it down so the link control will be cut off.
Try to access the link controls for that bottom link and watch the box get cut off from the metabox.

### Screenshots, screen recording, code snippet

<img width="1408" alt="Screenshot 2024-09-09 at 11 27 08 AM" src="https://github.com/user-attachments/assets/4ece91a2-95db-42cb-bcd0-8aa865d50892">

Video:
https://youtu.be/Lir1aSnAJaQ

### Environment info

- Custom Theme
- Wordpress Version 6.6.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by Mamaduka** [comment]
The bug was fixed via #63939 and will be included in the WordPress 6.6.2 release, which I think is scheduled for tomorrow.
