### ISSUE TITLE
DataViews: when there's only one action and is primary, hide actions dropdown

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#65165]
## What

In some scenarios, the DataViews' consumer only declares one primary action. This is how it looks

https://github.com/user-attachments/assets/e1c297a6-4feb-4d9e-97df-4825392a6928

## Proposal

- Grid layout: to stay as it is.
- Table & List: hide the action's dropdown. For example:

<img width="151" alt="Captura de ecrã 2024-09-09, às 17 26 27" src="https://github.com/user-attachments/assets/33ed93b0-824f-447f-a025-b3441fd51c6b">

**Comment by oandregal** [comment]
cc @jameskoster @youknowriad

**Comment by jameskoster** [comment]
I think this makes sense for table layout. How do you see it working in other layouts, it might look a bit odd in Grid?

**Comment by oandregal** [comment]
> I think this makes sense for table layout. How do you see it working in other layouts, it might look a bit odd in Grid?

Right. Making this work for Table & List (only them display primary actions) should be a good first step, leaving Grid as it is (users interact with actions via the dropdown).

**Comment by jameskoster** [comment]
Sounds good to me!

**Comment by oandregal** [comment]
What's difficult about grid that we cannot have actions? Is it that the actions compete with the title for the space? Related https://github.com/WordPress/gutenberg/issues/65600

I'm thinking it'd be nice to support this interaction in DataViews. Perhaps we'd want it in the media library so you can preview images with duotone filters? Or in the templates page to quickly see how different palettes affect a template? All those little rounded buttons would be primary actions:

https://github.com/user-attachments/assets/9027b327-0a8d-4fd9-b56e-f8781ca93e30

_(not that we need to address it right now, but thought I'd share as food for thought)_

**Comment by jameskoster** [comment]
> Is it that the actions compete with the title for the space?

Mostly yes. Displaying primary actions would require a good design.

How would the example actions you shared work on table layout, or would they be layout-locked (grid/list only)?

**Comment by oandregal** [comment]
> How would the example actions you shared work on table layout, or would they be layout-locked (grid/list only)?

Consumers can already provide actions that are specific to a layout with something along these lines:

```js
let actions = [];
switch (view.type) {
    case 'grid':
        actions = getGridActions();
        break;
    default:
        actions = getDefaultActions();
}

<DataViews
  view={ view }
  actions={ actions }
/>
```

In the example I shared I agree those color switcher actions wouldn't make much sense in table, for example.

**Comment by oandregal** [comment]
I've started to work on this for the list layout: https://github.com/WordPress/gutenberg/pull/67015

@jameskoster I'm thinking about tackling table next. If we hide the actions menu for table, I believe the primary action' icon should always be visible (now it's only displayed on hover). Thoughts?

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/67020 for table layout.

**Comment by oandregal** [comment]
The changes for table have landed and list changes are scheduled to land soon, so I'm closing this one.
