### ISSUE TITLE
Embed Block: Match HTML in the editor and frontend

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#65179]
Discovered while reviewing #64970

## What problem does this address?

In #64970, the `figcaption` element was moved into the `figure` element in the editor. However, the HTML in the frontend and editor do not match completely.

Editor:

```html
<div tabindex="0" class="block-editor-block-list__block wp-block is-selected wp-embed-aspect-16-9 wp-has-aspect-ratio wp-block-embed" id="block-87cbd5e9-5d49-47a8-9085-b7e6a72d8c58" role="document" aria-label="Block: YouTube Embed" data-block="87cbd5e9-5d49-47a8-9085-b7e6a72d8c58" data-type="core/embed" data-title="YouTube Embed">
  <figure class="wp-embed-aspect-16-9 wp-has-aspect-ratio wp-block-embed is-type-video">
    <div class="wp-block-embed__wrapper">
      <iframe title="Embedded content from youtu.be" class="components-sandbox" sandbox="allow-scripts allow-same-origin allow-presentation" width="620" height="349"></iframe>
    </div>
    <figcaption role="textbox" aria-multiline="true" aria-label="Embed caption text" aria-readonly="false" class="block-editor-rich-text__editable wp-element-caption rich-text" contenteditable="true" data-wp-block-attribute-key="caption" style="white-space: pre-wrap; min-width: 1px;">Caption</figcaption>
  </figure>
</div>
```

Frontend

```html
<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio">
  <div class="wp-block-embed__wrapper">
    <iframe title="Matt Mullenweg: State of the Word 2023" width="500" height="281" src="https://www.youtube.com/embed/c7M4mBVgP3Y?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
  </div>
  <figcaption class="wp-element-caption">Caption</figcaption>
</figure>
```

As you can see, in the editor, the block wrapper element is a `div` element, not a `figure` element.

This isn't an issue in most cases, but it can cause a visual difference when a block next to an Embed block has zero margins applied. This is because [the figure element has a bottom margin](https://github.com/WordPress/gutenberg/blob/aca9273fd451cd9f264dd8116f9816e5b7ec3487/packages/block-library/src/common.scss#L158-L163) applied to it.

Editor:

![editor](https://github.com/user-attachments/assets/af9e96e5-0fa3-4f95-9442-ade6177b0a0f)

Frontend:

![frontend](https://github.com/user-attachments/assets/1c4d09d6-c5c8-459e-aa10-2b779db6f871)

## What is your proposed solution?

We should be able to make it match the front-end HTML by applying a figure element instead of the block wrapper div in the editor, and removing the existing figure element.

As a preliminary to this, it might make sense to rewrite the [EmbedPreview component](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/embed/embed-preview.js) from a class component to a function component.

**Comment by t-hamano** [comment]
> it might make sense to rewrite the [EmbedPreview component](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/embed/embed-preview.js) from a class component to a function component.

Regarding this point, #51325 should solve it.

**Comment by hbhalodia** [comment]
Hi @t-hamano, I have raised the PR for the fix - https://github.com/WordPress/gutenberg/pull/65478,

Thank You,

**Comment by hbhalodia** [comment]
Hi @t-hamano, Looks like we can close this issue? as PR is merged to trunk.

Thank You,

**Comment by t-hamano** [comment]
Yes, I believe the HTML in the Embed block matches perfectly, so we can close this issue 👍
