### ISSUE TITLE
Safari mobile crashes when exploring patterns in page, post, and site editors

### ISSUE THREAD

**Issue by miksansegundo** [WordPress/gutenberg#65178]
### Description

Safari mobile crashes without error and reloads the page when exploring pattern categories.

The cause for this is commonly a memory leak or a process blocking the UI.

Maybe related to https://github.com/WordPress/gutenberg/issues/64732

cc: @annezazu @ellatrix 

### Step-by-step reproduction instructions

In the site editor:
- Click Patterns
- Change the items per page to 100
- Try to close the settings and scroll
- Verify the browser crashes and reloads automatically

In the post and page editors:
- Open the pattern inserter
- Click on a category
- Click Back
- Click on another category
- Continue until the browser crashes and reloads automatically

### Side editor crash
Increase the items per page to 100 and scroll to explore patterns.

https://github.com/user-attachments/assets/2383c6ac-2c36-4923-b9f3-e11402eae3de

### Post and page editor crash
Open and close pattern categories from the pattern inserter.

https://github.com/user-attachments/assets/82d1cfa6-7eea-47f0-8cd4-5751951cdbeb

https://github.com/user-attachments/assets/c72e2e41-9dca-43dd-8576-f2e6ce19eedf

### Environment info

Tested on iPhone 15 (iOS 17.5)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [ ] Yes

**Comment by Mamaduka** [comment]
@miksansegundo, what version of the WP and Gutenberg plugin are you using for testing?

**Comment by miksansegundo** [comment]
Hi, I missed saying that is Gutenberg 19.1.0


I'm testing on 19.2.0 soon

**Comment by miksansegundo** [comment]
I'm suspecting is some plugin on my site (Dotcom simple) because I cannot reproduce it on a core site with only Gutenberg.

**Comment by Mamaduka** [comment]
@miksansegundo, it could be the number of Patterns loaded on Dotcom env vs. local site.

**Comment by miksansegundo** [comment]
I think the number of patterns makes it worse but there is something else because I cannot reproduce the crash in a core site with only Gutenberg and 600 patterns.

The editor inserter still works:

https://github.com/user-attachments/assets/8a990e6a-7a75-4de3-81b3-dcff5d05ead5

On the site editor's patterns page, I do notice the UI lagging and eventually becomes unresponsive. This component is DataViews.

https://github.com/user-attachments/assets/f82b62dc-f4d6-4017-9d99-e16394f5dfe5

I'm going to continue investigating what else in my site is affecting the editor's performance.

**Comment by annezazu** [comment]
I’m going to close this out for now since it can’t be replicated in Core and there are other issues around pattern performance for Core. Please reopen if you can replicate!
