### ISSUE TITLE
Difficulty removing empty heading blocks

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65174]
When editing templates in the Site Editor I cannot easily delete a Heading block. I don't get this behavior when editing a page; I'm pretty sure it's only when editing a template.

In this video I'm pressing the delete button and it's moving the block up the tree. 

https://github.com/user-attachments/assets/21406b53-bbf1-4884-9a8c-2d454102f575

**Comment by kspilarski** [comment]
Hi @richtabor Thanks for sharing your report. I tested this on my site and was able to replicate the exact issue you mentioned. In the template, deleting a Heading block will move it up the list of blocks. 

Here's my screen recording: 
![Screen Capture on 2024-09-10 at 11-51-00](https://github.com/user-attachments/assets/503abf52-f6cc-45f9-a5e9-04562599e139)

Meanwhile, on patterns, pages and posts, deleting the heading works fine and does not move up the block list when deleted.

**Comment by talldan** [comment]
I can also reproduce this in the post editor, and with paragraphs as well as headings. The bug has been in the last couple of WordPress versions, and is related to some changes that were made for list and quote blocks also applying to other blocks - https://github.com/WordPress/gutenberg/pull/45075.

**Comment by ndiego** [comment]
> I can also reproduce this in the post editor, and with paragraphs as well as headings. 

I ran into the paragraph issue last night. While I thought it might be an intentional decision, it's very frustrating and requires you to manually delete the paragraph/heading from the List View or the Options dropdown. It would be ideal to get this fixed in 6.7.

**Comment by kevin940726** [comment]
I opened https://github.com/WordPress/gutenberg/pull/65262 attempting to fix this. It checks for "empty" blocks and removes them on merge. Technically, this checks for `__experimentalRole`. I'm not sure if that's the best approach though! Feedback welcome!
