### ISSUE TITLE
Crammed nav area during edit.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#65195]
### Description

Crammed navigation when menu item is selected.

### Step-by-step reproduction instructions

1. Go to the Site Editor.
2. Go to one of the templates.
3. Eg Front page.
4. Click to edit the Footer with only a navigation.
5. Notice it can get crammed together because there is so little in the footer.

### Screenshots, screen recording, code snippet

The result of clicking a footer containing only a navigation. It opens in a new screen. Cramming the selected link and the toolbar on top of the navigation area.

![screenshot_2024-09-07_at_10 20 48](https://github.com/user-attachments/assets/d65a8d08-9885-432c-90dd-c133c190d37d)

### Environment info

WP 6.6.1
Gutenberg plugin 19.1
Theme: Twenty Twenty Four
As well as various other plugins.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [ ] Yes

**Comment by t-hamano** [comment]
When editing a template part, pattern, etc. the editor canvas should be centered vertically:

![image](https://github.com/user-attachments/assets/ac8fac44-eb45-43b7-a5d7-1a6ec2093e7f)

But in your screenshot, it looks like the editor canvas is centered at the top 🤔

**Comment by paaljoachim** [comment]
Thank you for taking a look at this @t-hamano Aki!

I retested. I was missing a few steps in my original comment...

1. In the Site Editor. I selected front page.
2. Clicked the footer. In the right sidebar settings under Design I selected the first nav with a logo in the center nav below and Designed with WordPress below the Nav. ![Screenshot 2024-09-10 at 14 36 40](https://github.com/user-attachments/assets/ff0ee3ce-5932-4fc7-b7f8-c7d4a1de2f28)
3. I deleted the logo and Designed with WordPress.
4. Selected the Footer. Clicked Edit.
5. Opened in editor window mode. Clicked the Nav. 
6. In the sidebar settings I clicked the 3 dots and created a new nav.
7. Clicked to add a new link. It looks like this:

![Screenshot 2024-09-10 at 14 30 39](https://github.com/user-attachments/assets/895cfbf9-b6a0-4e48-aaa5-d51ad4468cd6)

Continuing to add menu items shows the same crammed space as is seen just above here.

**Comment by t-hamano** [comment]
> 1. In the Site Editor. I selected front page.
> 2. Clicked the footer. In the right sidebar settings under Design I selected the first nav with a logo in the center nav below and Designed with WordPress below the Nav.
> 3. I deleted the logo and Designed with WordPress.
> 4. Selected the Footer. Clicked Edit.

At this point, the editor canvas will be centered. Is this the same in your environment?

https://github.com/user-attachments/assets/6c571b14-2cd8-4e78-99a2-a54f4de43f0f

Or can you reproduce this issue in the playground?

https://playground.wordpress.net/?plugin=gutenberg

**Comment by paaljoachim** [comment]
[Editing nav](https://www.dropbox.com/scl/fi/vy84128bscp4izsuc4361/Editing-nav-Site-Editor.mp4?rlkey=6ud9mig1wqopo4odxjthqr7q0&st=n25fg2nn&dl=0)

I added the file to my dropbox.

**Comment by paaljoachim** [comment]
The above example is from the Brave browser.

Selected the Pages template.
Changed Footer to the first in design panel on the right with centered Nav.
Removed logo placeholder and designed with WordPress text.
Edit Footer in isolate mode.
Create new menu
Add existing Sample Page.

Screenshot from Firefox.
![Screenshot 2024-09-10 at 15 49 47](https://github.com/user-attachments/assets/bf70799b-8a87-4928-9cd9-646c2c8e6743)

Screenshot from Safari
![Screenshot 2024-09-10 at 15 52 51](https://github.com/user-attachments/assets/cfdf6a06-182d-4992-9139-f24ac4f84973)

**Comment by talldan** [comment]
@paaljoachim Are you testing with the Gutenberg plugin up to date and enabled?

It looks to me like you're testing WordPress without the plugin (the same as the other issue you incorrectly reopened). A lot of fixes will be merged to the plugin before making it into WordPress core, but we still consider those fixed.

I'll close the issue as I also can't reproduce it.

**Comment by paaljoachim** [comment]
Hey Dan @talldan 

"Are you testing with the Gutenberg plugin up to date and enabled?"
The report was about testing with Gutenberg plugin version 19.1. I also tested with Playground.

Resting a dev site using WP 6.6.2
Twenty Twenty Four.
Only plugin active is: Gutenberg plugin 19.2

Here is a video. Showing my experience using the Brave browser. 
Let me know if there are any adjustments I need to make.
https://youtu.be/lKQ32K4SSD0

**Comment by t-hamano** [comment]
Thanks for retesting.

When I watch your video, I can see that the editor canvas is vertically centered.

But maybe what you're essentially taking issue with isn't the alignment of the editor canvas, but perhaps the editing UX of the navigation itself. Am I right?

**Comment by talldan** [comment]
@paaljoachim Here's the screenshot from your original report, showing the toolbar overlapping the block (which is from an old version of the plugin):
![screenshot_2024-09-07_at_10 20 48](https://github.com/user-attachments/assets/d65a8d08-9885-432c-90dd-c133c190d37d)

Here's a screenshot from your video (using the latest version):
<img width="403" alt="Screenshot 2024-09-12 at 5 10 06 PM" src="https://github.com/user-attachments/assets/2f5ca3ef-377d-44cc-bf61-3d72df6c87f6">

You can see it's different, and yes you were testing an outdated version. Now it feels like you're trying to gaslight me by denying it 😄 

Now you might consider this too cramped, which is fair enough - but please could you make an issue using up to date information/screenshots.

**Comment by paaljoachim** [comment]
LOL Dan! @talldan 
I deny everything...:)

I have earlier tested with Gutenberg plugin 19.1 in a dev site when that was the newest plugin.
Then I also tested Playground.

The video is about testing using the new Gutenberg plugin 19.2 in a dev site.

Dan. Yes the older version overlaps. The newer version does not but it is still crammed in not giving enough space.

The issue for me is that the Navigation toolbar and the link dialog box are very close together. So yes this is an issue about the UX. I also went ahead and tested how adding a submenu looks like through the current UX system.

I feel like I am running around chasing my own tail.

Btw the title of the issue says it all.....

**Comment by talldan** [comment]
😄 Ok, I think there's a misinterpretation earlier because there was a previous bug where the toolbar overlapped the block, which made it very cramped.

Editing a nav like that is similar to editing a paragraph and adding a link, which has been this way for a while:
<img width="461" alt="Screenshot 2024-09-12 at 5 08 45 PM" src="https://github.com/user-attachments/assets/d2aa5adc-d663-4710-ad25-f4a7ef47d6a8">

I think it's also similar in other blocks.

If you want to open a new issue about the link interface, I think that might be better than one about a specific block. I also don't think it's right to label it a bug, because it's a subjective opinion—an enhancement would be better with the 'Needs Design Feedback' label.

**Comment by paaljoachim** [comment]
I added this new issue: https://github.com/WordPress/gutenberg/issues/66582

**Comment by talldan** [comment]
Thanks @paaljoachim!
