### ISSUE TITLE
Alpha usability test three: Discoverability and feel

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#652]
**Background:** To catch up on our current state of usability testing, check out this post: https://make.wordpress.org/design/2017/04/27/testing-the-gutenberg-user-test/.

**Goal:** What does the new editor feel like? This is very broad so we need to focus on tasks.

**Task:** Write a usability script using the alpha plugin. You should base it off the existing testing script, however you can add the following tasks:

- full width image
- text
- headlines
- lists
- quotes

We can have a demo page for this but install instructions are good. Remember the goal and focus the task on that.

**Format:** The script should be made into a google form like the first one, however first lets iterate on the script in this issue, then take to the form. This is not a task yet to run these tests. That will come.

The script should also come with a setup sheet for the testers. Our goal is to have as many people doing this test, as easily as possible.

**Comment by mtias** [comment]
@karmatosed can we close this one now?

**Comment by mtias** [comment]
@karmatosed can we close this one now?

**Comment by karmatosed** [comment]
Closing as we have tests live.
