### ISSUE TITLE
BorderBoxControl: Horizontal scrollbar is displayed in block sidebar

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#65207]
### Description

Note: This can be reproduced on Windows OS/Chrome browser where the browser scrollbar has a physical width.

The sidebar width is 280px. However, due to a 17px scrollbar on Windows OS/Chrome browser, the actual content width is 263px. In this case, the box control does not fit into the grid layout and an overflow occurs.

### Step-by-step reproduction instructions

Access a block that supports borders and click the "Unlink sides" button.

### Screenshots, screen recording, code snippet

![image](https://github.com/user-attachments/assets/b38d982b-7ed1-4561-a497-a8205fa3e004)

![image](https://github.com/user-attachments/assets/c497a987-189f-4fcd-91af-2f1c4566c736)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by mirka** [comment]
Good catch!

FYI, macOS also has a setting to show scrollbars with a physical width (which I have enabled), so this is not necessarily a Windows-only issue.

<img width="479" alt="Scrollbar settings on macOS" src="https://github.com/user-attachments/assets/d8344f9e-57bd-4af9-a20b-a3547cc7c161">

**Comment by mirka** [comment]
@WordPress/gutenberg-design Looks like we need some design tweaks here. The current component compresses down to 248px width, but with a scrollbar it needs to compress down to 231px (in the Windows case, 233px on Mac).

**Comment by jasmussen** [comment]
Did we end up making a final decision on gap width? 8, 12 or 16? 

Regardless, if we make a few tweaks we still get a fairly ergonomic control at 237px. 

![Screenshot 2024-09-12 at 09 16 05](https://github.com/user-attachments/assets/58959886-fcde-4af1-849f-c9bfb8f82217)

12px gap, that could be reserved for the "exploded" view here.

Instead of the unit selector having an 8px right margin, it has a 4px right margin:

![Screenshot 2024-09-12 at 09 13 23](https://github.com/user-attachments/assets/54ee4c40-fd0d-4313-8397-241e27120199)

And the width of the inputs is changed from 116px to 112px.

**Comment by jameskoster** [comment]
It would be good to somehow eliminate any hard-coded width values so that we avoid running into this issue again in the future. Ideally the whole component should gracefully adapt to the container.

**Comment by jasmussen** [comment]
The fixed width would be good to eliminate indeed, though I suspect it's a vestige of that partiucular exploded border view, so beyond replacing those with percentages, which we can, it's still going to be a bit tight.

By the way the numberes above assume we want to be able to show 4 digits in the field at all times. If we think 999px borders is as much as anyone needs to _see_, then there's more room still.

**Comment by t-hamano** [comment]
Thanks everyone for the feedback.

I tried simply narrowing the width of the input field until it fits the 231px container width. In my environment, the 4th digit is slightly visible.

![image](https://github.com/user-attachments/assets/d730ccf7-9c6f-47b3-8b47-30c0881775f2)

![image](https://github.com/user-attachments/assets/54f9c705-53f7-426c-aa17-c2291bb3e00a)

**Comment by mirka** [comment]
> I tried simply narrowing the width of the input field until it fits the 231px container width. In my environment, the 4th digit is slightly visible.

I think that should be fine. I doubt people will set borders over two-digit pixels.
