### ISSUE TITLE
Upload external media replaces images in wrong order and/or creates duplicates

### ISSUE THREAD

**Issue by traed** [WordPress/gutenberg#65281]
### Description

When copy-pasting content with several images from e.g. google docs and hitting Publish, an option to upload external images appears. Sometimes when using it the images in the editor gets replaces by the wrong image after the upload is done. So that if a document had images A, B and C, after the upload is done B and C are replaces by copies of A.

### Step-by-step reproduction instructions

1. Copy all content from a google doc with multiple different images
2. Paste it into the WP editor
3. Hit publish and then Upload when prompted
4. After the upload is done the images in the editor are replaces incorrectly

### Screenshots, screen recording, code snippet

Google doc with example content: https://docs.google.com/document/d/1FSNt8QQFofPu27PvoUOo7Gwq1hedkoNoD1t2_KuSFAo/edit?usp=sharing

Screen recording: https://drive.google.com/file/d/1O2WXbaTrGUHFUmToyc8iYdVPsIjmNncv/view?usp=sharing

### Environment info

- WP v 6.6.2 (clean install using https://localwp.com/)
- PHP 8.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by Mamaduka** [comment]
Thanks for reporting the issue, @traed!

This looks similar to #64899, which was fixed via #65122.

cc @sgomes

**Comment by sgomes** [comment]
Thank you for the mention, @Mamaduka! 👍 Yes, that does indeed seem like a similar issue to #64899, I agree.

@traed: If you have the opportunity to give `trunk` a try, please let me know if that fixes things for you!

**Comment by Mamaduka** [comment]
@traed, @sgomes, I just tested using `trunk` and provided test Google Document. The images are uploaded and replaced correctly.

**Comment by sgomes** [comment]
Thank you so much, @Mamaduka! 🙌

**Comment by Mamaduka** [comment]
I'm going to close the issue. The bug has been fixed in Gutenberg trunk.
