### ISSUE TITLE
Request to add dropdown menu on mobile devices

### ISSUE THREAD

**Issue by phanduynam** [WordPress/gutenberg#65284]
I am using WordPress 6.6.2 and Twenty-Four 1.2 theme. I am having trouble creating a menu on mobile. You can see the menu does not collapse but always pops out of the sub-menu items. I tried searching but Gutenberg does not have an option to collapse the entire menu. It will be a disaster if the site has many sub-category products.

![image](https://github.com/user-attachments/assets/d7dde010-81b4-46e6-b480-c8a542390c9b)

**Comment by carolinan** [comment]
Hi, this is already discussed in multiple issues, the most recent being https://github.com/WordPress/gutenberg/issues/62172.

_Kindly refrain from opening duplicate issues in the two ticket queues on Trac and GitHub._
