### ISSUE TITLE
Custom Gutenberg Block incorrect plugin name when trying to activate it instantly after installation

### ISSUE THREAD

**Issue by oskarasriauba** [WordPress/gutenberg#65318]
### Description

I have a custom Gutenberg block which has a separate folder called 'includes' for php files.
I have chosen this approach for them to be included in the build. If they are in the same folder as the main plugin file, they are ignored and skipped from the build.

When I upload the plugin with a plugin manager and install it successfully, I cannot activate it straight away, because it uses a wrong plugin name (e.g. &plugin=blockname%2Fincludes%2Fyourfilename.php)

However, there is no problem activating it in wp-admin/plugins.php page.

Thanks in advance!

Edit: Additionally, if the block is already enabled, 'Activate plugin' should not be present, but it is.

### Step-by-step reproduction instructions

Create a new Gutenberg block (npx @wordpress/create-block)

Create a folder 'includes' and a random php file.

Add this inside your block's main PHP file or 'init' hook which is also in the main file.
require_once plugin_dir_path( \_\_FILE\_\_ ) . 'includes/yourphpfile.php;

npm run build
npm run plugin-zip

Try installing the zip file to WP instance. It should return that it is installed successfully and the "Activate Plugin" button URL query parameter "plugin" value will be "your-block-name%2Fincludes%2Fyourphpfile.php".

### Screenshots, screen recording, code snippet

<img width="942" alt="Screenshot 2024-09-13 at 1 42 21 PM" src="https://github.com/user-attachments/assets/d2daacb6-6f40-4cb7-8672-ffe1788a2db6">

### Environment info

WP 6.5.5
Gutenberg (17.8-18.5)
MacOS

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by miminari** [comment]
I didn't reproduce the error as written here.
But when I have made the `includes` directory in the plugin directory and run build, then I tried to run wp-now, I had an error like below: 

> assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
> (BuilderBase.h:550 block_for_offset)

## Environment info
WordPress 6.6.2

**Comment by miminari** [comment]
@oskarasriauba Hi, could you please share more detail information like what you wrote on the php file, or try latest WordPress version and check you have bugs yet?

**Comment by oskarasriauba** [comment]
@miminari Interesting, I've just found out that the problem occurs on WP hosting provider instance only. Still very strange.
