### ISSUE TITLE
Post Formats: Query loop shows the wrong posts when inheriting the query from the post format archive template

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#65320]
### Description

I have only tested this with a block theme.

When a query loop block with the setting `Inherit query from template` is placed in an archive template for a post format,
the correct posts are shown on the front, but not in the editor. In the editor, all posts are shown.

### Step-by-step reproduction instructions

First, you need a block theme, and you need to enable post format support on the active theme.
If your theme does not have a functions.php file, create one.

Example:
```
function twentytwentyfour_setup(){
	add_theme_support( 'post-formats', array( 'standard', 'aside', 'gallery', 'audio', 'video', 'link', 'image', 'chat', 'status', 'quote' ) );
}

add_action( 'after_setup_theme', 'twentytwentyfour_setup' );
```

Set the permalinks on the test installation to Post name.

Create a few posts and assign them the link post format.

Next, add a link post format archive template inside the theme's `templates` folder.
templates/taxonomy-post_format-post-format-link.html

Go to Appearance > Editor > Templates, locate and edit the template.
Add a query loop block. In the block settings sidebar, make sure that `Inherit query from template` is enabled.
Check if the query loop shows the correct posts, it should only show the posts that you assigned the link format to.
Save.

View the archive on the front: Add `type/link/ `after your test domain in the browser address bar.
(For example `http://66.local/type/link/` )

### Environment info

WordPress 6.6.2, with and without Gutenberg trunk.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by carolinan** [comment]
While troubleshooting this I found that this is true also for tags.
If I go to Appearance > Editor > Templates > Add new and select Tag Archive .. for single item, then the editor shows a list of the most recent posts, not posts with the selected tag.

**Comment by carolinan** [comment]
@ntsekouras I don't suppose you remember why the query loop was only fixed for specific category archive pages, and not other taxonomies? https://github.com/WordPress/gutenberg/pull/44294

**Comment by ntsekouras** [comment]
>@ntsekouras I don't suppose you remember why the query loop was only fixed for specific category archive pages, and not other taxonomies? https://github.com/WordPress/gutenberg/pull/44294

The linked PR was just a bug fix, but I guess the question now becomes why we had only the [categories handling
](https://github.com/WordPress/gutenberg/pull/43699). Maybe it seemed like the most common scenario and it was a first step? 

I'm not sure though how much complexity we should add there given that in many cases the actual result could be way different with filters etc...

**Comment by carolinan** [comment]
The query loop filters are working: it is the default (inherit) that is not working.

**Comment by drivecontact** [comment]
Hi,

Have you found a solution? I have the same problem
