### ISSUE TITLE
SearchControl: Deprecate `onClose` prop

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#65334]
## What problem does this address?

The `onClose` prop is not used anymore in the Gutenberg app. It was originally intended to render a close button to "trigger your own logic to close the search field entirely, rather than just clearing the input value."

The prop itself is causing confusion to consumers (#64921), and I think the UI pattern of a single button that doubles as a reset and a close is questionable from a UX standpoint.

## What is your proposed solution?

I think we can [soft deprecate](https://github.com/WordPress/gutenberg/issues/61099) the feature. For consumers that really want to maintain the original behavior, however unrecommended, we can issue guidance to use the `suffix` prop.

**Comment by ciampo** [comment]
> we can issue guidance to use the `suffix` prop.

Agreed. We could add a dedicated Storybook example too

**Comment by Vrishabhsk** [comment]
Hi @mirka 👋 
- I have raised a `PR` addressing this issue : https://github.com/WordPress/gutenberg/pull/65988
- I was initially going to add context to use `suffix` instead of `onClose` but didn't due to it being unrecommended.
- Let me know If I should extend the `docs` and `deprecation` to suggest the use of `suffix`. Thanks

**Comment by mirka** [comment]
> * I was initially going to add context to use `suffix` instead of `onClose` but didn't due to it being unrecommended.

Yes, I don't think we need to document it officially. At most, I'll maybe add it to a Dev Note.

**Comment by Vrishabhsk** [comment]
Sounds good. I have addressed the feedback in my latest commit : [`PR`](https://github.com/WordPress/gutenberg/pull/65988). 
Thanks

**Comment by mirka** [comment]
Closed by #65988
