### ISSUE TITLE
New or changed patterns on a fluid theme do not show in the block search

### ISSUE THREAD

**Issue by margarita-boomCodes** [WordPress/gutenberg#65335]
### Description

As of WP 6.6, the pattern metadata, such as title and slug, are being saved into a transient (_site_transient_wp_theme_files_patterns-xxxx). The problem is that this transient isn't updated, when the metadata of a pattern file unter the patterns directory, changes or a new file is added. Interestingly, the transient will be updated, when a pattern file is deleted. 

The expected behavior would be to update the transient when a file is changed, added or deleted. 

### Step-by-step reproduction instructions

1. Activate the [Emptytheme](https://github.com/WordPress/gutenberg/tree/trunk/test/emptytheme) fluid theme (This should create also the transient)
2. Create a `patterns` directory and add a new pattern
3. Search the pattern in the library (the new pattern is **not** visible)
4. Delete the `_site_transient_wp_theme_files_patterns-xxxx` on the database's options table. 
5. Search the pattern in the library (the new pattern is now visible)

### Environment info

- WP 6.6.2
- Gutenberg 19.2.0
- [Emptytheme](https://github.com/WordPress/gutenberg/tree/trunk/test/emptytheme) classic theme

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by Mamaduka** [comment]
Adding `define( 'WP_DEVELOPMENT_MODE', 'theme' );` should resolve the issue when developing themes.

You can read more about developing modes here: https://make.wordpress.org/core/2023/07/14/configuring-development-mode-in-6-3/.

**Comment by t-hamano** [comment]
This issue was also reported in #64173, and I believe it is expected behavior, so I would like to close it.

**Comment by margarita-boomCodes** [comment]
> Adding `define( 'WP_DEVELOPMENT_MODE', 'theme' );` should resolve the issue when developing themes.
> 
> You can read more about developing modes here: https://make.wordpress.org/core/2023/07/14/configuring-development-mode-in-6-3/.

@Mamaduka Since the WP_DEVELOPMENT_MODE should not be used in production environment, I think [this solution](https://github.com/WordPress/gutenberg/issues/64173#issuecomment-2268551505) to increase the theme version number, could be more appropriate (even though not ideal)

**Comment by Fab1en** [comment]
Thanks for the details in this tickets that saves me from scratching my head another hour !
`define( 'WP_DEVELOPMENT_MODE', 'theme' );` did the trick for me, and the theme version increase is great too. I also use this php code to delete the cache : 
```php
$cache_hash = md5( get_theme_root() . '/' . get_stylesheet() );
delete_site_transient('wp_theme_files_patterns-' . $cache_hash);
```
