### ISSUE TITLE
Deprecate ButtonGroup component

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#65338]
## What problem does this address?

The component does two things:

- Wrap the buttons in a `role="group"`.
- Add styling to [make it look like a segmented control](https://github.com/WordPress/gutenberg/pull/65336).

As we can see from the usages in the Gutenberg app, `role="group"` is not semantically sufficient to make these buttons behave like a segmented control, and most consumers will not realize this. As such, most of our in-repo usages are inaccessible.

The outdated segmented control style is similar to the already deprecated [RadioGroup](https://wordpress.github.io/gutenberg/?path=/docs/components-radiogroup--docs), and is succeeded by the ToggleGroupControl style.

## What is your proposed solution?

- [x] #65339
- [x] [Soft deprecate](https://github.com/WordPress/gutenberg/issues/61099) the component. https://github.com/WordPress/gutenberg/pull/65429

Consumers who want to wrap their buttons in a `group` can do that with a plain `<div role="group">`.

**Comment by hbhalodia** [comment]
Hi @mirka, I have raised the PR by adding the soft deprecation as expected on the issue. Let me know if we need to update anything else in the PR - https://github.com/WordPress/gutenberg/pull/65429

Thank You,

**Comment by mirka** [comment]
Closed by #65429
