### ISSUE TITLE
Add "Width" and "Height" settings to Woo blocks nested inside Group/Row/Stack/Grid

### ISSUE THREAD

**Issue by octaedro** [WordPress/gutenberg#65342]
## What problem does this address?

From WooCommerce issue  [#47884](https://github.com/woocommerce/woocommerce/issues/47884)

![Screenshot 2024-09-13 at 4 19 50 PM](https://github.com/user-attachments/assets/497d78fc-a25d-44e3-acef-b10ca9d3568b)

We don't support the Width, Height, Min. Width, and Min. Height controls like most core blocks when nested inside a container block (Group, Row, Stack, Grid). Let's start by adding them to the Product Collection block. 

## What is your proposed solution?

The new controls should be displayed in the Dimensions section in the Inspector panel.

<img width="366" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/753a27b3-4d48-4cd0-b386-a2efa68b6059">

// CC @jarekmorawski @j111q

**Comment by Mamaduka** [comment]
@octaedro, unless I'm missing some context, this looks like an issue for the WooCommerce repo.

**Comment by octaedro** [comment]
Thank you @Mamaduka. You're right; it's a WooCommerce issue. I'll close this issue.
