### ISSUE TITLE
Introducing Attributes and Editable Fields - Does not seem to save content or display on frontend

### ISSUE THREAD

**Issue by XpandMarketingLLC** [WordPress/gutenberg#6534]
## Issue Overview
While following the basic tutorial on creating custom blocks for Gutenberg I got stuck on step-03. The block shows up on the backend but when I save it, it doesn't show up on the front end and when I refresh the backend page the text I typed into the editor disappears. 

## Steps to Reproduce (for bugs)
Create a custom block based on code in step-03. Write some text into the text editor. Click update. View front end. Nothing shows up. Reload editor page. The custom text disappears there too. 

1. Download and install theme on localhost https://github.com/XpandMarketingLLC/xpand-starter
2. Create code in functions.php to load the scripts etc
3. Copy and paste code into block.js
4. Repeat as above

Using Google Chrome

## Screenshots / Video

![screen shot 2018-05-02 at 11 35 29](https://user-images.githubusercontent.com/25766560/39519008-f8a7afb2-4dfc-11e8-8716-beefdb82dbc9.png)
![screen shot 2018-05-02 at 11 35 14](https://user-images.githubusercontent.com/25766560/39519009-f8bfaf4a-4dfc-11e8-9541-e17553974f01.png)
![screen shot 2018-05-02 at 11 34 57](https://user-images.githubusercontent.com/25766560/39519010-f8d7841c-4dfc-11e8-951b-7248d6e10aeb.png)
![screen shot 2018-05-02 at 11 34 47](https://user-images.githubusercontent.com/25766560/39519011-f8ef6046-4dfc-11e8-8923-e39192fb34b2.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by chrisvanpatten** [comment]
Potentially going to close and merge into #6185 which also covers revamping our "how to make a block" tutorial!

**Comment by pbiron** [comment]
@XpandMarketingLLC  I followed your **Steps to Reproduce** today and I'm not seeing the problems you describe.  I used WP 4.9.8, GB 4.2 and the version of your theme that was current as of a couple of hours ago.  I also used Twenty Seventeen without problems.

Can you please try again and see if you are still experiencing the same problems?

**Comment by mkaz** [comment]
I also followed the instructions for the Block Tutorial and did not run into any issues.

I'm going to close this issue as it can't be reproduced, please reopen if there still is a problem and I would be glad to help and address.
