### ISSUE TITLE
Build plugin zip artifact on release/* and wp/* branches.

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#65345]
## What problem does this address?
Currently the plugin's zip file is generated upon each commit and stored in the associated action run for each commit on trunk.

For example the artifact for 1df91fb8289db22837ab68030ef7d87c90a2ed72 can be found attached to action run [10856201819](https://github.com/WordPress/gutenberg/actions/runs/10856201819).

As the `release/*` and `wp/*` branches are also production branches, generating the artifact for these commit branches would be helpful for contributors wishing to test the branches

## What is your proposed solution?

Add the WordPress and Release branches to the push section of the build-plugin-zip workflow file.

https://github.com/WordPress/gutenberg/blob/1df91fb8289db22837ab68030ef7d87c90a2ed72/.github/workflows/build-plugin-zip.yml#L5-L6

This workflow also includes the `npm-publish` job so any changes would need to make that portion of the workflow only runs when appropriate. I'm happy to work on the PR for this but it would be good to get some advice to make sure I don't end up triggering a package publish on each push to these branches.

cc @gziolo

**Comment by gziolo** [comment]
> This workflow also includes the npm-publish job so any changes would need to make that portion of the workflow only runs when appropriate. I'm happy to work on the PR for this but it would be good to get some advice to make sure I don't end up triggering a package publish on each push to these branches.


See these conditions for npm publishing:

https://github.com/WordPress/gutenberg/blob/1df91fb8289db22837ab68030ef7d87c90a2ed72/.github/workflows/build-plugin-zip.yml#L309-L311

In effect, it only runs when the Gutenberg plugin RC1 is published. It also depends on other jobs. Finally, npm publishing needs to be manually approved. I think it's very unlikely that any changes would accidentally trigger npm publishing. Anyway, I'm happy to double-check any future changes.

---

> As the release/* and wp/* branches are also production branches, generating the artifact for these commit branches would be helpful for contributors wishing to test the branches

Great idea 👍🏻
