### ISSUE TITLE
Inbound links and shortcode

### ISSUE THREAD

**Issue by Pro12webdesign** [WordPress/gutenberg#6536]
When trying to make an inbound link to another article from my website Gutenberg searches and finds the article but when I go to click on the article it highlights the paragraph and the one below it and goes out of the link function.

Also, when adding shortcode (such as a quiz from Quiz and Survey Master) I have to switch back to the classic editor to make it work.

I'm using Gutenberg version 2.7.0, which will be great once a few issues are ironed out.

**Comment by danielbachhuber** [comment]
Hi @Pro12webdesign:

> When trying to make an inbound link to another article from my website Gutenberg searches and finds the article but when I go to click on the article it highlights the paragraph and the one below it and goes out of the link function.

Does this issue still reproduce in Gutenberg 2.8? Can you share a screencast to visually communicate this behavior?

> Also, when adding shortcode (such as a quiz from Quiz and Survey Master) I have to switch back to the classic editor to make it work.

Can you share more detail about the nature of this bug (including reproduction steps, screencast, etc.)?
