### ISSUE TITLE
Keep revisions of templates & template parts after a reset, similar to global styles

### ISSUE THREAD

**Issue by Andrew-Starr** [WordPress/gutenberg#65369]
## What problem does this address?

It is very frustrating to find that previous template or template part revisions are deleted after hitting the reset option.

It's such an easy mistake to make, and if the user is not aware that all previous revisions will be removed it provides an awful user experience.

Imagine putting a lot of work into editing a template and inadvertently clicking reset instead of revisions, and in one click all your hard work is gone forever.

## What is your proposed solution?

Make it possible to keep the older revisions of templates and parts, in a similar way to how the global styles can be reset to the theme default, but the previous styles are not deleted and are still available should the user wish to switch back to any of the older style edits.

**Comment by talldan** [comment]
Thanks for reporting, this seems similar to #52221, so I'll close as a duplicate and drop a link to this issue.
