### ISSUE TITLE
FSE: Adding custom color in Styles removes regular colors (palette) in Editor - Highlight

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#65363]
### Description

If I use Highlights in the editor to emphasize a word, all regular Theme-colors are there to select with a single click.
If I add a custom color in Styles, afterwards only this color is left to select in Highlights.
If I remove the custom color in Styles, Highligh works again with regular palette

### Step-by-step reproduction instructions

1. Select some text in regular editor and click on "Highlight" in the toolbar => All colors from actual Theme palette are there to select.
2. Go to Styles => Colors => Palette => Custom => + (add a color)
3. Go back to editor and try Highlight spme text again => only the added custom color is there to select

### Screenshots, screen recording, code snippet

![grafik](https://github.com/user-attachments/assets/f8d523dd-008f-4820-b0f6-9d66761e5d7b)
![grafik](https://github.com/user-attachments/assets/5e5d22f5-4bec-4ee3-9a23-fa3f0e820996)
![grafik](https://github.com/user-attachments/assets/0cb9277c-9620-4f39-b0c4-9d1a632081de)

### Environment info

WordPress 6.6.2
Test with Twenty Twenty-Two and Twenty Twenty-Four
Test with Gutenberg 19.2.0 and without Gutenberg (pure WP Core)
Test Firefox and Google Chrome
Test on Windows 10 Desktop

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by gyurmey2** [comment]
https://github.com/WordPress/gutenberg/issues/47439
https://github.com/WordPress/gutenberg/issues/64857

**Comment by t-hamano** [comment]
Thanks for the report. Let's close this issue and focus our research and discussion in #64857.
