### ISSUE TITLE
Image block: cropping without making any changes leads to an error

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#65383]
Using WordPress 6.6.2 and Gutenberg 19.2 (here's a [link to a playground instance](https://playground.wordpress.net/?plugin=gutenberg)), if you add an image block and use the toolbar option to crop the image but don't make any changes, when you hit apply an error appears:

https://github.com/user-attachments/assets/1d099848-03bb-4912-b063-5b287bbaa81c

To replicate:
1. Add an image block.
2. Add an image.
3. Select the option to crop the image in the toolbar.
4. Don't make any changes.
5. Hit "Apply".
6. See error "Could not edit image. Invalid parameter(s): modifiers"

**Comment by andrewserong** [comment]
I can reproduce this. I think it should be a pretty simple fix to cancel out / skip performing the API request if there's nothing to modify.

**Comment by andrewserong** [comment]
Potential fix: https://github.com/WordPress/gutenberg/pull/65384
