### ISSUE TITLE
Table block automatically adds width and/or height values for tr and td

### ISSUE THREAD

**Issue by RobinRoelofsen** [WordPress/gutenberg#6540]
## Issue Overview
When I add a table to a page and add columns, tr and td gets values assigned. The only way to get rid of these values is by deleting them from the source code, since there are no options for the block yet. 

Sometimes heights are added as well, but cannot reliably replicate that.

I style the tables using CSS, but these values override the CSS values. Also, when I delete the values and keep working on the page, values reappear, so I need to remove them again and again.

## Steps to Reproduce (for bugs)

1. Add a table blok
2. Insert a column
3. Check the source code

I am working in the Chrome browser. Gutenberg's version is 2.7.0, WP's is 4.9.5.
## Expected Behavior

I expect values to appear only when I either enter values myself or if the block provides a better solution for entering width and height values. Never have the editor add values without user consent.
## Current Behavior

Now widths are entered by the editor instead of by the user.
## Possible Solution

It would be a nice addition to the tables block to be able to either set widths and heights or turn that off and have it dealt with by CSS.
## Screenshots / Video
https://www.useloom.com/share/98053e56bec7414ca805767bd9039718

**Comment by danielbachhuber** [comment]
Thanks for the report, @RobinRoelofsen. This issue is already covered with #4027

**Comment by danielbachhuber** [comment]
It's also worth noting there's a broader look at `<table>` in #6923
