### ISSUE TITLE
Close button is not working in block inserter menu inside widget editor.

### ISSUE THREAD

**Issue by PARTHVATALIYA** [WordPress/gutenberg#65433]
### Description

In the Widget Editor, the block inserter sidebar close button is not functioning correctly and is throwing an error. Additionally, in the tablet responsive view, two close buttons appear, which is inconsistent with the design and results in a poor user experience.
 A reference video has been provided for further clarification.

### Step-by-step reproduction instructions

- Activate the twenttwentyone theme
- Open appearnce > widgets
- Open block inserter
- Click on close button on the inserter menu and it's through the error in console
- Change the responsive view to tablet view
- Open block inserter
- There is an one extra close button for closing inserter menu

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/1209b5ae-9918-4398-9582-c9eaab561f71

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by miminari** [comment]
I could reproduce this on WordPress 6.6.2 without latest Gutenberg plugin.
But when Gutenberg 19.2.0 is activated, it could not be reproduced.

**Comment by PARTHVATALIYA** [comment]
Hey @miminari, I was able to reproduce this issue with the latest version of Gutenberg (19.6.4). 
Could you please check it again?

Thank you!
