### ISSUE TITLE
Why does RichText return an array instead of a string?

### ISSUE THREAD

**Issue by rwrobe** [WordPress/gutenberg#6544]
## Issue Overview
When adding RichText to a block, the attribute onChange returns an array instead of a string. This does not strictly seem like a bug, but I'm somewhat confused by this return format, as it has changed in 2.7 or 2.6. 

## Steps to Reproduce (for bugs)

1. Create a block and add the RichText component to it. Here's an example:
```
[ ... ]
	attributes: {
		question: {
			type: 'string',
		},
		answer: {
			type: 'string',
		},
	},
[ ... ]
	<RichText
		tagName="h4"
		placeholder={ __( 'Enter question here.' ) }
		value={ attributes.question }
		className="q-and-a question"
		onChange={ onChangeQuestion }
		focus={ focus }
	/>
```
2. Set up the onChange handler to manually update the attribute:
```
		const onChangeQuestion = value => {
			setAttributes( {
				question: value,
			} );
		};
```
3. Check out the stored result:
Before last update:
```
	"blockName": "namespace/q-and-a",
	"attrs": {
		"question": "Q and A Question 1",
		"answer": "Q and A Answer 1"
	},
```

And after:
```
	"blockName": "namespace/q-and-a",
	"attrs": {
		"question": [
			"Q and A Question 1"
		],
		"answer": [
			"Q and A Answer 1"
		]
	},
```
4. A side note, which may be a hole in my understanding of JS: If I try to grab the value at position 1 of the array, I get the trimmed result. That is, if I do this: 
```
		const onChangeQuestion = value => {
			setAttributes( {
				question: value[0],
			} );
		};
```
All white space is trimmed away and there are other strange side-effects (double space will register as a space, but occasionally also backspace).

## Expected Behavior
I would prefer if this return remained a simple string, rather than an array (not even sure what other elements would be in this array). I also find setting this attribute via the onChange event to be way more straightforward than the relatively inscrutable `source` method, especially in situations where the save method is a stub (in a headless implementation, where block attributes are parsed and used directly by a REST consumer, and innerHTML is ignored).

**Comment by youknowriad** [comment]
Closing as it's possible to specify `format="string"` for RichText componoents.
