### ISSUE TITLE
Hide empty paragraph block placeholder when it’s the only block when zoomed-out

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#65474]
After some discussion the new requirement here seems to be:

> Don't show paragraph block placeholder if
> 
> it's the only block on the page
> we're on an empty Page/Post
> we're Zoomed Out.

-----

### Description

When zoom out mode is active in the editor / site editor, empty paragraph blocks continue to display their `Type / to choose a block` placeholder state, even though they cannot be selected.

Should this be hidden in zoom out mode?

### Step-by-step reproduction instructions

1. In a template, somewhere in the middle of the template, add an empty paragraph block
2. Click the Zoom out button at the top right of the site editor
3. Notice that the paragraph placeholder is still visible even though you can't click on it

### Screenshots, screen recording, code snippet

In the following screenshot, the empty paragraph block there cannot be selected, but its placeholder is still visible. Should it be hidden?

![image](https://github.com/user-attachments/assets/e5ee9066-3b65-4f18-b247-2df25e5b429c)

### Expected 

Don't show paragraph block placeholder if

- It's the only block on the page.
- We're on an empty Page/Post.
- The editor is zoomed out.

**Comment by getdave** [comment]
> the empty paragraph block there cannot be selected, but its placeholder is still visible. Should it be hidden?

The question at hand seems to be: if a block is in it's placeholder state / empty should it be displayed when `contentOnly` is `disabled`?

**Comment by andrewserong** [comment]
>  if a block is in it's placeholder state / empty should it be displayed

Good point, it's probably the same for a bunch of other blocks, too, e.g. the empty Tag line block that also nudges folks to start typing 🤔

**Comment by draganescu** [comment]
@getdave @andrewserong since we're eventually going to bring edit mode into zoom out view - see #65702 - then this would not be a problem since the content in placeholder mode is simply editable?

**Comment by richtabor** [comment]
> then this would not be a problem since the content in placeholder mode is simply editable?

I'm testing https://github.com/WordPress/gutenberg/pull/65702 here; it's still a rough case: 

https://github.com/user-attachments/assets/e72c1c98-35b5-4e77-b884-058bdaec954d

**Comment by draganescu** [comment]
@richtabor I don't understand 😄 how is the roughness related to this issue. This issue is "should the placeholder still be visible if the paragraph is empty" with the implication arond other placeholders ... The poor UI in the recording is something else, am I wrong?

**Comment by getdave** [comment]
The original issue was:

> When zoom out mode is active in the editor / site editor, empty paragraph blocks continue to display their Type / to choose a block placeholder state, even though they cannot be selected.

I re-tested this and found

- placeholder is still displayed (expected)
- block _can_ be selected


<details>
<summary>Testing videos</summary>

https://github.com/user-attachments/assets/2b18196f-f477-4cd6-a549-9af118b0f699

https://github.com/user-attachments/assets/6d532ac9-3cf3-4364-aef5-f782599bf24b
</details>

----

Issues I noticed above in @richtabor's testing video:

- Accidental selection of `core/post-content` block. This is the "section root" and [we've deliberately set this to be enabled but in `contentOnly` mode](https://github.com/WordPress/gutenberg/blob/df27bd934838d56271224c76d54402886b88160c/packages/block-editor/src/store/selectors.js#L2926-L2928). What affordances do we want around this element or do we just want to hide it (including when it's a `<main>` tag in other scenarios?
- Alignment of vertical toolbar - being addressed in https://github.com/WordPress/gutenberg/pull/65627

Anything else I missed? Can we close this one out or do we want to change the way the placeholder behaves?

**Comment by richtabor** [comment]
> Anything else I missed? Can we close this one out or do we want to change the way the placeholder behaves?

I don’t think leaving the placeholder is a good idea if it’s the only block on the page (an empty page/post) while zoomed out. Otherwise, it’s easy to get into that odd experience I shared above. Does that empty paragraph stay in place when a pattern is inserted from this view?

**Comment by getdave** [comment]
> I don’t think leaving the placeholder is a good idea if it’s the only block on the page (an empty page/post) while zoomed out.

Based on that I'd say this is the new requirement.

Don't show paragraph block placeholder _if_ 

- it's the only block on the page
- we're on an empty Page/Post
- we're Zoomed Out.

LMK if that is _not_ correct. Thanks 🙇

**Comment by richtabor** [comment]
Yup!

**Comment by getdave** [comment]
Code-wise - placeholders are hard coded into the various blocks. Example:

```js
placeholder={ placeholder || __( 'Heading' ) }
```

You can set the `placeholder` as an attribute  to an empty string (I think) but that would cause a block modification and we'd have to restore the attribute when leaving Zoom Out.

Anyone else got a suggestion for how we could go about implementing this?

**Comment by andrewserong** [comment]
> Anyone else got a suggestion for how we could go about implementing this?

Could one option be to use CSS to hide the placeholders, if that's all we need to do (rather than changing the wording)? There's already one case where we set opacity to `0` in some circumstances, so perhaps there's a precedent:

https://github.com/WordPress/gutenberg/blob/1a29c029e3e95556f0d0bd3c48e2a4e47b641f5d/packages/block-library/src/paragraph/editor.scss#L13-L19

I guess the challenge would be if we have the right selectors available for a CSS condition that matches the situation where we want the placeholder to be hidden?

**Comment by draganescu** [comment]
But will we also _remove_ the block (the empty paragraph) or will the empty paragraph show up when we exit zoom out? I can see it as a source of frustration already. 

I am really suspicious of these just in time tweaks that hide stuff. It seems there is an underlying UX issue to solve and we're obscuring it here.

**Comment by colorful-tones** [comment]
> Could one option be to use CSS to hide the placeholders

This seems odd, and would advise against it.

> I am really suspicious of these just in time tweaks that hide stuff. It seems there is an underlying UX issue to solve and we're obscuring it here.

I agree. It would be ideal to take a breath, step back, and re-assess Zoom Out in the context of its purpose and intent.

**Comment by getdave** [comment]
This Issue appears to be blocked with no clear consensus. We are rapidly approaching WP 6.7 Beta 3. 

I'd say the underlying Issue is perhaps that we don't have a good **initial state** for Zoom Out when the editor is empty. 

By default the paragraph blocks acts as the default placeholder for all editors. It's clearly designed with post content editing in mind which is why it doesn't play well in Zoom Out.

The solution seems to be that if the template is empty we should show a _specific_ placeholder, perhaps with instructional text encouraging you to drag and drop content.

Given we are now in Beta we can't add new features to Zoom Out so we need a decision on whether this is sufficiently important to warrant the "fix" ([as suggested above](https://github.com/WordPress/gutenberg/issues/65474#issuecomment-2390875675)) or we defer a solution until 6.8.

What do you think @richtabor?

Also @kevin940726 @ndiego @colorful-tones as Editor Leads for 6.7.

**Comment by draganescu** [comment]
I would also like to add that this may be well not solved for 6.7 - it's not such a big problem that there is a placeholder there. Nothing else is editable in 6.7 when zoomed out. My 2 cents.

**Comment by ndiego** [comment]
The current placeholder situation is not great, but it is also not mission-critical, in my opinion. There are more pressing Zoom Out issues that need solving in this tight time window, so I don't recommend we spend time on this one.

**Comment by colorful-tones** [comment]
I'm adding this to the WP 6.7 project board. Although, it sounds like it'll just get the Punt to 6.8 status.

**Comment by getdave** [comment]
I would vote to punt this to 6.8 👍

**Comment by ndiego** [comment]
Sounds good, thanks @getdave

**Comment by getdave** [comment]
I looked into this. Before we can action we need to fix https://github.com/WordPress/gutenberg/issues/67564 otherwise you cannot insert any Patterns at all.

Related is also https://github.com/WordPress/gutenberg/pull/68026
