### ISSUE TITLE
Social media share block?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#6547]
Hey

I am just wondering if Gutenberg core should have a default Social media share block included?

Something similar to: https://wordpress.org/plugins/share-block/

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @paaljoachim ! I think this is outside the scope of v1 but I'll file it in the ideas project for later consideration.

**Comment by karmatosed** [comment]
There is already an issue with a design for this so over having duplicates, let's remove this one.
https://github.com/WordPress/gutenberg/issues/1873
