### ISSUE TITLE
Add Transformation from Separator to Spacer

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#65492]
## What problem does this address?

We are still dealing with lots of old content being converted into the Block Editor, and as white space was hard to control in the Classic Editor, people have made liberal use of hr's, which get turned into separator blocks in the conversion process. It has become very commonplace for us to replace them with Separator blocks and just rely on whitespace for separation between content sections, which gives a much more modern look.

## What is your proposed solution?
Add a transform from the Separator block to the Spacer block

**Comment by rudrakshi-gupta** [comment]
Hey, I would like to work on this issue.

**Comment by Antrikshgwal** [comment]
Hey @mtias 
Can i work on this issue ? if it's still unresolved

**Comment by talldan** [comment]
@Antrikshgwal I think this was already implemented in #66230.

**Comment by MadtownLems** [comment]
> [@Antrikshgwal](https://github.com/Antrikshgwal) I think this was already implemented in [#66230](https://github.com/WordPress/gutenberg/pull/66230).

I think the confusion here stems from the fact that @rudrakshi-gupta commented here that he'd like to work on the issue, and submitted a PR to fix it 3 days later without explicitly tagging that the PR is intended to fix this issue. In the future, it would be great to do that so that a) this issue can get properly updated and tracked, and b) whoever first submitted the issue also gets props ;)

Looking forward to having this transformation available on our sites - thanks!
