### ISSUE TITLE
Query Loop: Add keywords to help make block more discoverable

### ISSUE THREAD

**Issue by mikachan** [WordPress/gutenberg#65493]
## What problem does this address?

The Query Loop block currently doesn't include the `keywords` key in its block.json file. I think adding some aliases or additional descriptors for the block would make it more easily discoverable in the Editor. 

For example, if a user is not already aware of the block, "Query Loop" is not immediately obvious as a block that would show a list of posts from your blog, or a list of custom post types. When searching for terms like this in the block inserter, the Query Loop is not returned in the search results.

## What is your proposed solution?

Add a `keywords` key to `packages/block-library/src/query/block.json` which includes some common terms or aliases, such as: 

- posts
- list
- blog
- blogs
- post types

**Comment by dhruvang21** [comment]
Hi @mikachan 
i have raised PR for this issue :- https://github.com/WordPress/gutenberg/pull/65515

Also some more keyword suggested:-

- post query
- post loop
- blog posts
- post list

**Comment by mikachan** [comment]
Nice, thank you @dhruvang21!

With these additional keyword suggestions:

- post query: The Query Loop would be returned here as it includes the word "query".
- post loop: Similar here, but with "loop".
- blog posts: This should be covered by including "blog" and "posts" individually, as you have in https://github.com/WordPress/gutenberg/pull/65515.
- post list: Similar here, this should be covered in https://github.com/WordPress/gutenberg/pull/65515 with "post" and "list".
