### ISSUE TITLE
Figure out how to test the plugin: GH Page, separate site, or both?

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#655]
In order to facilitate user tests, we need an easy way to test the plugin, so @karmatosed and others run tests. Two ideas have been suggested:

**GH Page:**

We archive the prototypes (move to separate repo? archive elsewhere?) and run the editor, with a fake wp-admin around it. 

**Separate site:**

@j-falk has an excellent option for testing in the wp-admin context: https://github.com/WordPress/gutenberg/issues/655#issuecomment-299706311

**Comment by aduth** [comment]
It'd require more work, but I think it would be nice to set up a version allowing public access without needing login credentials (without any save support). This could serve to hold us accountable to ensuring the editor is portable and not tied to any specific context.

Related:

- https://github.com/aduth/fake-editor
- http://adutheditor.mystagingwebsite.com/ (can't guarantee this link will remain active)

**Comment by youknowriad** [comment]
Could we use this http://poopy.life/ for a quick and easy WP site?

**Comment by j-falk** [comment]
I thought about this just earlier today and found this issue, great! I decided to try an approach for this and have setup a website that could be used for testing at:

https://testgutenberg.wpkonsulterna.se/

also created this shortlink that can be used to simplify sharing:

http://bit.ly/test-gutenberg

I have no problem mapping it towards another domain if that is preferred.

The website is a standard WordPress install setup which is using the plugin Autologin Links by Paul Konstantin Gerke (https://wordpress.org/plugins/autologin-links/) to provide the possibility to login as a WordPress user only using a generated login token.

You are being logged in as a already created user who have the role Author and are being sent to the Gutenberg page which have a pre-generated post which you can start edit and save as a draft.

I have 2 thoughts though:

- Right now the Gutenberg Plugin requires a WordPress user to have the capability manage_options to use the editor. It is not very nice to have to give that capability to a temporary user on a website. Wouldn't it make more sense to either use the capability "edit_posts" or create a custom capability if we want it to be even more flexible?

- How could we make sure to keep the plugin updated to the latest version? Will the plugin be published on .org or should we setup a custom deployment script somehow?

**Comment by jasmussen** [comment]
This seems to work great @j-falk! Thanks so much for setting this up!

> Right now the Gutenberg Plugin requires a WordPress user to have the capability manage_options to use the editor. It is not very nice to have to give that capability to a temporary user on a website. Wouldn't it make more sense to either use the capability "edit_posts" or create a custom capability if we want it to be even more flexible?

@youknowriad do you know if we can do something here?

> How could we make sure to keep the plugin updated to the latest version? Will the plugin be published on .org or should we setup a custom deployment script somehow?

I think for the near future we'll probably have to do it manually. But we can probably keep updates to the _tagged releases_, which we plan to start doing sometime this week.

**Comment by iseulde** [comment]
Can't we just initialise the editor on https://wordpress.github.io/gutenberg/?

**Comment by iseulde** [comment]
I guess this goes back to @aduth's comment 

> This could serve to hold us accountable to ensuring the editor is portable and not tied to any specific context.

**Comment by jasmussen** [comment]
> Can't we just initialise the editor on https://wordpress.github.io/gutenberg/?

This would show without the admin, right? Since we're actually able to show it in admin context, I think it'd be good to.

**Comment by iseulde** [comment]
Yeah, it would. I'd argue that if you want to see it in context, install the plugin. I'm not sure we want to user test the context? I also like the idea that the editor could be used stand alone (e.g. as a React component).

**Comment by jasmussen** [comment]
> I'm not sure we want to user test the context?

I'm not a testing expert, but I feel like seeing the new editor in context of actual WordPress makes it "real" in a way it doesn't without it. I would guess this would affect test results. 

> I also like the idea that the editor could be used stand alone (e.g. as a React component).

I like that too —  and your idea isn't bad. Just not sure it's the best for usertests.

**Comment by youknowriad** [comment]
> Wouldn't it make more sense to either use the capability "edit_posts" or create a custom capability if we want it to be even more flexible?

Yes, "edit_posts" seems more "logic" to me. Easy change, I wonder why it's "manage_options" in the first place.

**Comment by jasmussen** [comment]
Let's make the edit_posts change and embrace @j-falk gracious setup of a testing site for now.

**Comment by jasmussen** [comment]
Closing this as fixed, since the edit_posts change has been merged. @j-falk do you have all you need?

**Comment by j-falk** [comment]
I have all I need, I just uploaded the latest version to the site and I guess I can do it manually like this when there are new versions. How often should I update the plugin you think? Once a week?

**Comment by jasmussen** [comment]
Reopening for discussing in light of new ideas.

**Comment by jasmussen** [comment]
There has been some suggestions that we remove the old prototypes, and instead add a built version of the editor running there. This does not necessarily preclude others from hosting it in wp-admin, and the approach is not yet fully fleshed out, hence the reopening.

**Comment by iseulde** [comment]
Would be cool if https://wordpress.github.io/gutenberg/ has the editor on the whole page.

**Comment by jasmussen** [comment]
Seems like we might want to close this in favor of #953?

**Comment by jasmussen** [comment]
Closing in favor of #953.
