### ISSUE TITLE
ContentOnly Select Mode: In Top Toolbar mode, it is not possible to toggle between Design and Edit modes

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#65508]
### Description

Following https://github.com/WordPress/gutenberg/pull/65204:

After switching to the Edit mode (ContentOnly / Select Mode), if a user sets the editor to the top toolbar mode, the toggle for editing modes disappears, and it isn't possible to switch back to the other mode, unless you disable the top toolbar mode.

Should the toggle for Edit vs Design modes persist even when the toolbar is set to display at the top?

### Step-by-step reproduction instructions

1. Open the site editor
2. Click the pointer icon at the top left and toggle to the edit mode
3. In the settings at the top right of the editor, switch to the top toolbar mode
4. Notice that you can no longer switch editing modes at the top left

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/4d4910b5-949e-43f6-bdcf-65dd47954390

### Environment info

- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by vipul0425** [comment]
Hi @andrewserong, I have raised [PR](https://github.com/WordPress/gutenberg/pull/65511) for this issue. Let me know if anything needs to be updated.

Thanks 🙇

**Comment by andrewserong** [comment]
Thanks for the quick fix on this one @vipul0425, nice work! 🙇
