### ISSUE TITLE
Double clicking the template from zoom out mode asks the user to edit the template

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#65505]
### Description

While in zoom out mode while editing a page in the site editor, if you double click on the post title, it'll ask you if you want to edit the template. However, users often use the post title block in order to set the title of their page. In this case, if the user is double clicking on a post title block, can we disable zoom out, instead of displaying the template editing modal?

The assumption here is: if a user is in zoom out mode and double clicks the post title block, they are more likely to be trying to update the title of their page than they are to be wanting to edit the template.

### Step-by-step reproduction instructions

1. Open the site editor
2. Go to Pages > any page to edit a page within the site editor
3. Click the Zoom out button in the top bar
4. Double click the post title block
5. Notice that you get the modal prompt to switch to edit the template, instead of deactivating zoom out mode / allowing folks to edit the page title

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/04292ce4-7dc1-4201-9062-38ce8cdc8bdc

### Environment info

- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by draganescu** [comment]
This is something that also happens when double clicking template parts in zoom out - asked about editing template but the result is you _only_ exit the zoom out view.

**Comment by getdave** [comment]
A solution here seem like it would be to have the double click hander on the "Edit template" also exit Zoom Out mode if it's active.

**Comment by getdave** [comment]
Doubling clicking a template should exit Zoom Out and _not_ activate the Template Editor. You should not be able to "activate" the Template Editor from Zoom Out.

**Comment by richtabor** [comment]
> Doubling clicking a template should exit Zoom Out and not activate the Template Editor. You should not be able to "activate" the Template Editor from Zoom Out.


Yes, exactly.

**Comment by andrewserong** [comment]
Nice, that sounds like a simple way to resolve this 👍

**Comment by andrewserong** [comment]
I've tried that idea out over in https://github.com/WordPress/gutenberg/pull/65963. Happy for any feedback!
