### ISSUE TITLE
Changing background color of header or paragraph block causes extra padding to be added

### ISSUE THREAD

**Issue by rwwwwwr** [WordPress/gutenberg#65506]
### Description

PROBLEM: Changing the background color of a paragraph or header block causes extra padding to be added to the element.

EXPECTED RESULT: Changing the background color of the block does NOT change the dimensions/padding/margins of the block, only changes the background color.

NOTE: This affects both the editor and is also saved and becomes live when the page is saved.

### Step-by-step reproduction instructions

- Open a new wordpress playground (also works on the local install I have of 6.6.2)
- Click "Edit site"
- Click on a header or paragraph block
- Click on the "Settings" right button to show the right-side-menu
- In the "Block" tab, under "Color", click "Background" (default is unset)
- Change color to any color or gradient. Note the text block has now grown in size due to added padding
- Remove background color by hitting "clear" and see text block returns to normal size.

### Screenshots, screen recording, code snippet

![paddingIssue](https://github.com/user-attachments/assets/63a4ec63-2769-401f-b69b-a9eb6066ddbc)

### Environment info

Wordpress 6.6.2; Microsoft Edge Browser; Occurs in both locally hosted WP 6.6.2 and fresh version on playground

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by rwwwwwr** [comment]
Just to add, I was able to get a workaround on this. It seems that the padding/margin options, when first enabled, show "zero", but in reality are unset. If you change the padding/margin options and then reduce them back to zero, I get the desired layout I was expecting.

![paddingIssue2](https://github.com/user-attachments/assets/a61a19f0-dc83-4403-9141-e910f212b5c5)

**Comment by carolinan** [comment]
Hi @rwwwwwr This issue is already discussed in https://github.com/WordPress/gutenberg/issues/30725 so I am closing this as a dupliate.
