### ISSUE TITLE
Allow embedding of remote video media in the background of Cover blocks

### ISSUE THREAD

**Issue by pkarjala** [WordPress/gutenberg#65502]
## What problem does this address?

Currently all media used in the background of a Cover block must be uploaded to the site.  This does not work well for content that is data-intensive, such as video files.  A large number of visitors to a site can quickly eat up bandwidth quotas.  Even taking the time to properly encode and make videos have as small of a footprint as possible does not completely alleviate the issue.  Additionally, not all servers are well configured for serving video content, which can tax resources usually only allocated for serving text and images.

## What is your proposed solution?

All videos to be embedded from external resources in the background of Cover blocks.  An example to start with would be media hosted on YouTube.  Currently all that is desired is to add the embed code of the applicable media with settings such as described at https://developers.google.com/youtube/player_parameters.

This is what we used to do with the classic editor and using manual embed codes, but we are unable to do this with the blocks editor due to the inability to add external media for Cover blocks.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested https://github.com/WordPress/gutenberg/issues/28860. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and subscribe to follow its progress in the issue.
