### ISSUE TITLE
Lists and bullets are removed in brave/safari reading mode

### ISSUE THREAD

**Issue by donbowman** [WordPress/gutenberg#65536]
### Description

I'm not sure where this is introduced, but i'll assume gutenberg rather than theme. An example page https://www.agilicus.com/white-papers/agilicus-anyx-configuration-security/ shows the issue.
I open chrome reading mode, the side bar shows. But, my ordered and unordered lists are removed.

![2024-09-20_11-56](https://github.com/user-attachments/assets/e9c9f2c1-06fe-4847-a7d5-f80a276881d1)

In the html generated I see:
<ol class="wp-block-list">
 <li>
  ::marker
  "info..."
   </li>

### Step-by-step reproduction instructions

1. create a post
2. create a list, set it to be ordered
3. add some bullets
4. open in chrome reading mode in front end

### Screenshots, screen recording, code snippet

![2024-09-20_11-56](https://github.com/user-attachments/assets/b6f61fda-f151-4148-9658-6965965acb0f)

### Environment info

- wordpress 6.6.2
- gutenberg plugin 19.2.0
- chrome 130.0.6723.6-1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Thanks for the report.

Lists inserted in the editor render simple ul/ol tags on the front end, so if the issue occurs in reading mode, I expect it will occur on sites other than WordPress sites as well.

By the way, the latest version of Chrome in my environment is `129.0.6668.59`, and I cannot reproduce this issue:

![image](https://github.com/user-attachments/assets/3ed7e1b2-5037-40c6-863c-9e7f3bedc4ad)

Your Chrome version seems to be `130.0.6723.6-1`, is this a beta version?

**Comment by donbowman** [comment]
Thanks for looking into this.
I reproduced it on Brave and Safari. But then when i went back to chrome it did not show.
Yes, i'm trying on Chrome beta.

I will try and narrow this down. I removed my other plugins and tried it in the wasm-wordpress playpen.

I'm thinking its more the group structure rather than the ul tag

**Comment by t-hamano** [comment]
Just to be sure, if you use the beta version of Chrome to visit a site other than WordPress, do any lists on that site display correctly in reading mode? We need to determine whether this is a WordPress/Gutenberg issue or a Chrome-specific issue.

**Comment by donbowman** [comment]
It occurs on Safari and Brave as well as chrome stable.

using 'stable' version of brave v 1.70.117.
On brave its sections that are missing, more than just the bullets/list.


![image](https://github.com/user-attachments/assets/f4d2d16f-5830-4820-b8b3-02d95dddba77)

**Comment by donbowman** [comment]
I have come up w/ a minimal set of rendered html that shows this, attached. For some reason, it skips the 'introduction' heading, and, the last 2 sentences of introduction in reading mode on safari and brave. I was incorrect in my original assessment around list/bullet.

[sample.zip](https://github.com/user-attachments/files/17085725/sample.zip)

![image](https://github.com/user-attachments/assets/dba44a10-de16-4453-8d30-876f7be2918e)

**Comment by t-hamano** [comment]
I still can't reproduce this issue. Are my steps shown below correct?

https://github.com/user-attachments/assets/3e9273a3-ffb1-478f-88f9-5a18ee96950f

**Comment by donbowman** [comment]
Below I have demonstrated w/ brave-browser, with default install (no extensions, no config, installed specifically for this test). I don't have safari available to me right now, but it does the same.

Step 1. Install brave-browser (1.70.117)
Step 2. Run brave-browser https://www.agilicus.com/www/sample.html
Step 3. Click the button for reader-mode

Attached is a video demo. The page is just simplified html from my earlier: i removed all the javascript etc that was unrelated, and trimmed the content down. This is generated  from wordpress+gutenberg.

[Kooha-2024-09-22-18-51-14.webm](https://github.com/user-attachments/assets/11bcde38-8c0b-44e2-9fe0-03e0e01af8e6)

So i guess this could be a bug in both brave + safari, but they have different rendering engines.

**Comment by t-hamano** [comment]
The following HTML is just plain HTML with no styles or classes. Can you reproduce the issue with this file? If you can, it's not a WordPress/Gutenberg issue.

[rando - Agilicus.zip](https://github.com/user-attachments/files/17092046/rando.-.Agilicus.zip)

**Comment by donbowman** [comment]
I agree with your assessment. This must be a bug in brave + safari and the earlier version of chrome i used. I will close this, sorry for the confusion.
