### ISSUE TITLE
Add "Reset" to the Data View for template parts

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#65538]
## What problem does this address?
If you edit a template part, the only way to reset it is to go into the Editor and then select "Reset" from the options popover in the Template Editor tab. However, if you edit a template, the "Reset" is directly available in the Data View. 

| Editor | Data View (Template Part) | Data View (Template)
|-|-|-|
|<img width="818" alt="image" src="https://github.com/user-attachments/assets/3b171080-e81f-4cd6-9172-91ad690cc359">|<img width="788" alt="image" src="https://github.com/user-attachments/assets/12d8a79b-7e26-4198-baee-c9df0cd93a28">|<img width="849" alt="image" src="https://github.com/user-attachments/assets/58adb4c5-b443-4aeb-92aa-9b0a0c3396bf">|

## What is your proposed solution?
Add the option to "Reset" template parts directly in the Data View.

**Comment by mtias** [comment]
It'd be great to add this as an action on the quick edit panels once those are ready.

**Comment by dhruvang21** [comment]
Hello @ndiego,

I believe this feature is already available in Gutenberg template parts. The reset option appears once you start editing a template part. I’ve attached a video demonstrating the process where I reset the template part from the data view.

[Template-part-reset.webm](https://github.com/user-attachments/assets/b405e16c-5054-4d27-b09c-0cbd140929ac)

**Comment by youknowriad** [comment]
I can confirm that this is solved.
