### ISSUE TITLE
Selecting Most Used Tags

### ISSUE THREAD

**Issue by bartekcholewa** [WordPress/gutenberg#6553]
Allowing to select from already existing most used post tags like in old editor is missing.
![tags old](https://user-images.githubusercontent.com/5921659/39566337-8af8216c-4ebb-11e8-9e76-dff674482c38.png)
![tags new](https://user-images.githubusercontent.com/5921659/39566341-8ba79cd2-4ebb-11e8-9fa2-6c5c1f349bd2.png)

**Comment by Soean** [comment]
Hey @bartekcholewa we already have a ticket for this feature: #5638.
The ticket was closed and moved to the [idea board](https://github.com/WordPress/gutenberg/projects/8#card-9332503). Feel free to comment on the ticket why it should be added to Gutenberg.
