### ISSUE TITLE
Plugins add additional publish controls, Gutenberg omits them

### ISSUE THREAD

**Issue by Forecaster** [WordPress/gutenberg#6554]
## Issue Overview
I have a couple of plugins that add some controls to the "Publish" section in the classic editor, these controls are missing from the Gutenberg editor. I suspect the "issue" is that these plugins don't add modules to the editor, but edit an existing module. (I'm not sure this is what is really going on but this is my guess.)

Is there something I can do or do I simply have to request that the plugins add proper modules so Gutenberg can display the controls? Can support be added for these controls in Gutenberg if that fails?

The plugins in question are
**Public Post Preview** - Adds the option to publicly link to a draft for review purposes
**Jetpack** - Adds "Publicize" controls for selecting which social networks to auto-share the post to on publish.

I was unable to find anything relevant to my issue by searching, but maybe I used the wrong terms.

## Screenshots / Video

This is what the classic editor looks like with these controls:
![image](https://user-images.githubusercontent.com/942137/39567039-ee6cecbc-4ebd-11e8-9eb8-80eb302072b3.png)

**Comment by theleemon** [comment]
Check this:

https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/action-post-submitbox.md

**Comment by Forecaster** [comment]
@theleemon I'm guessing this is for the plugins to implement support for Gutenberg?

**Comment by theleemon** [comment]
Yes, it's a migration guide for plugins. Apparently, right now, there's no way to add anything to the Gutenberg Publish box.

**Comment by Soean** [comment]
`Public Post Preview` has a Gutenberg branch, so they are working to become compatible
https://github.com/ocean90/public-post-preview/tree/gutenberg
See also the video: https://twitter.com/ocean90/status/980420608822562816

`Jetpack` is also working to be compatible with Gutenberg, see https://github.com/Automattic/jetpack/issues/9039

So unfortunately you have to wait for Plugin updates.

**Comment by Forecaster** [comment]
That's acceptable :)
In the meantime I'll just have to switch to the classic editor when I need to access those controls.

You may close this issue unless you want to keep it active for awareness or something.

**Comment by Soean** [comment]
This are known and documented problems. We are already working on a migration guide and the mentioned plugins are working on an update. So I think it should be fine to close this issue.
