### ISSUE TITLE
Paste: Single-line pastes should conform to current block

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#6555]
## Issue Overview

A revisit of #5354. Per the last comment, this is the behavior we'd like to achieve when copying (a) list item(s) from a rich-text source:

- If you are on an empty paragraph, respect the source [and create a new list block, for instance].
- Otherwise, if you copied more than one line, respect the source [and create a new list block, for instance].
- Otherwise, if you copy a single line, paste as plain text [and merely add to the current paragraph].

The last point is where behavior differs: currently, pasting will always create a new block (for a list, etc.) unless the clipboard only contains pure text.

**Comment by iseulde** [comment]
Sure. So how do we determine that something is a single line?

```
<ul><li>If you are on an empty paragraph, respect the source [and create a new list block, for instance].</li></ul>
```

```
<pre><code>A huge chunk of code</code></pre>
```

We'll have to specifically target some kind of blocks?

**Comment by mcsf** [comment]
Ella: we would probably start small and focus on lists first, as they are the kind of content that sparked this discussion.

**Comment by mtias** [comment]
We could try a char-length cutout as well.

**Comment by mcsf** [comment]
@mtias, can you elaborate?

**Comment by mtias** [comment]
If the source has less than x length, we treat it as plain text.

**Comment by iseulde** [comment]
PR coming up.
