### ISSUE TITLE
Query Loop block: block error with GB 19.3 RC1 when using block format support

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#65550]
Using GB 19.3RC1 which includes https://github.com/WordPress/gutenberg/pull/64167, I found that after adding support to the TT4 theme, I wasn't able to get the query loop to properly filter with a format option when adding a query loop block to a page or a template. In this case, I had set a few posts to include an Image format in case that matters:

https://github.com/user-attachments/assets/33435441-78aa-4cc5-83fb-91f7fbb1788a

**Comment by annezazu** [comment]
cc @carolinan as you worked so hard on this ❤️

**Comment by carolinan** [comment]
Which WordPress version is used?
Can you see what the error is in the browser's console? (how to open that will depend on the browser)

**Comment by carolinan** [comment]
Does this only happen when inserting this pattern, or with newly inserted query loops?

**Comment by annezazu** [comment]
Using version 6.6.2 and in Chrome Version 128.0.6613.85 on a Mac. I found this happened when adding a query loop block fresh and trying to customize it. I can also replicating when adding a Posts pattern with a query loop and trying to customize it. 

Here's what I see in the console:

![Screenshot 2024-09-22 at 6 31 03 PM](https://github.com/user-attachments/assets/a368a549-b31c-4ef4-a513-0aba874a2336)

**Comment by carolinan** [comment]
Thank you.

**Comment by annezazu** [comment]
Awesome work. Thank you @carolinan!
