### ISSUE TITLE
400 bad request trying to autosave empty content

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#6556]
## Issue Overview

When adding a new post I got an unexpected "Updating failed" message.
The console log showed  400 bad request.
The response being 
```
{"code":"empty_content","message":"Content, title, and excerpt are empty.","data":{"status":400}}
```

## Steps to Reproduce (for bugs)

1. Add a new post.
2. Insert a Classic block
3. Wait a while

## Expected Behavior

Either no attempt to save the post or allow the empty content to be saved.

## Current Behavior
Autosave kicks in. Since none of the following have been entered... Title, Content and Excerpt
we get the 400 Bad request. which leads to the display of the unexpected "Updating failed" message. 

## Related Issues and/or PRs

#1201

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Thanks for the report, @bobbingwide. I can reproduce this issue:

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/36432/40150765-87bdc72a-5930-11e8-94ec-427bf3f1c822.png">

More specifically, I _think_ this issue happens because an empty Classic block is sent to the server as `''` (empty string), while every other block (even when empty) includes the block HTML comment data.

Building on #1203, I'd suggest we add some special case behavior to `isEditedPostSaveable` that treats empty Classic blocks as not saveable.

**Comment by bobbingwide** [comment]
I can imagine scenarios where the content of the title, post and excerpt is automatically created by plugins from meta data. 

I have one CPT in my Golf Society's website where the posts are generated with content of `<!--more-->`.  
Another CPT just contain's `<!--more-->[bw_fields]`. 

e.g. https://www.anchorgolf.com/result/28-apr-hurtmore-winner-herb-miller/

The posts are created programatically. Perhaps empty content should be allowed.

**Comment by bobbingwide** [comment]
I've just tested. The Classic editor allows you to save posts with empty titles and content. 
So this is a backwards compatibility issue.

**Comment by danielbachhuber** [comment]
> I've just tested. The Classic editor allows you to save posts with empty titles and content.

I'm not quite sure I agree with this result. I'm able to "save" an empty post:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/36432/40204148-5ca805bc-59dc-11e8-8025-f30f6cd7665e.png">

However, if I saved it with an empty title and content, it's not accessible in Edit Posts:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/36432/40204193-853359d2-59dc-11e8-89c8-0425e50b87e1.png">

In the database, it's saved as an `auto-draft`:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/36432/40204221-9bf384a8-59dc-11e8-8c30-f88be1215881.png">


> So if we don't allow an empty post to be saved this would be a backwards compatibility / documentation issue.

I understand how this is a change in behavior that would need to be documented. Can you explain to me how it's a break in backwards compatibility?

**Comment by bobbingwide** [comment]
> Can you explain to me how it’s a break in backwards compatibility?
Tricky. It depends on your understanding of the label. For me, if it’s something that I could do in the previous version but can’t do in the current version, then it’s a regression... a backward compatibility issue.  

If this regression is then considered to be a **bug** then it needs to be worked on. 
If it’s not a bug, then there should be a requirement and a proposed solution, and some tests that explain the scenarios for the change. Failing that some **documentation**.

In this case the documentation might cover how to publish an empty post using the block editor. 
I’ll have to check the steps I performed to create my empty post.

**Comment by bobbingwide** [comment]
To create an empty post.
1. Create post normally with Title and Content. Save
2. Blank out Title and Content. Save

**Comment by danielbachhuber** [comment]
Coming back to this, I think there's one specific scenario to solve for: the user should never experience an "Updating failed" state like this:

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/36432/41489677-b332dca6-70a5-11e8-8202-cd1cc7c31a1d.png">

However unlikely, it should be possible for a user to create a new post in Gutenberg, switch the first block to a Classic Block, and hit "Save Draft". But, this isn't currently possible because of:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/36432/41489735-dc7ed1b4-70a5-11e8-982e-caf093e5bc7d.png">

I'm not sure which technical solution we should apply yet.

**Comment by aduth** [comment]
Additional technical context / possible solution at #7727

**Comment by danielbachhuber** [comment]
While @pento and I were chatting on Tuesday, we discovered some additional odd behavior of the Classic Editor:

1. Create a new post in the Classic Editor.
2. Add some text to the body and leave the title blank.
3. Hit "Save" and see the post is saved successfully.
4. Remove the text from the body.
5. Hit "Save" again and see that the post isn't saved successfully — the text re-appears in the body.

![saveempty](https://user-images.githubusercontent.com/36432/42331143-8effbb18-8029-11e8-9729-6cb801972b7f.gif)

**Comment by danielbachhuber** [comment]
For the purposes of replicating Classic Editor behavior, I'd be fine the solution proposed in #7727 — prevent any saving if the title is empty and the editor has an empty Classic Block.

**Comment by danielbachhuber** [comment]
@aduth @youknowriad Do either of you have a preferred implementation for this?

**Comment by danielbachhuber** [comment]
From @aduth in [Slack](https://wordpress.slack.com/archives/C02QB2JS7/p1538673346000100):

> https://github.com/WordPress/gutenberg/blob/622bbfb6bc6364a4e49991081aafed4257309c92/editor/store/selectors.js#L351-L364
> `! getBlockCount( state )` is technically an optimization to avoid serializing.
Here, we need to check that if count is 1, and the 1 block is fallback, to allow the serializer to run to see if its the empty string result
