### ISSUE TITLE
Site logo block is missing DropZone when a logo is present

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65571]
I should be able to update my logo by dropping in another image. I can already do this everywhere else in the editor. 

### Visual 

https://github.com/user-attachments/assets/9345d382-814a-44bc-a13e-5e56e87260a6

**Comment by dhruvang21** [comment]
Hi @richtabor,
I have raised PR for this enhancement :- https://github.com/WordPress/gutenberg/pull/65596
