### ISSUE TITLE
Synced patterns do not render vertical toolbar 

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65570]
When I would expect that the vertical toolbar displays as expected for synced patterns when zoomed out: 

### Screenshot

![CleanShot 2024-09-23 at 10 37 03](https://github.com/user-attachments/assets/9a86a223-5996-488a-87f9-af0d5fba2146)

### Recording 

https://github.com/user-attachments/assets/7e996053-028e-44a1-b522-34bcf58f3558

**Comment by getdave** [comment]
@draganescu I have a feeling you are working on a solution for this. Can you advise?

**Comment by draganescu** [comment]
It should have been linked above. Yes I have one open PR for this.

**Comment by getdave** [comment]
Is it this one? https://github.com/WordPress/gutenberg/issues/65570

Looks like it [that PR] isn't linked to _this_ Issue.

**Comment by draganescu** [comment]
No it's #65627
