### ISSUE TITLE
Persist edit and design modes

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65572]
Now that the effort to land edit and design modes is in flight (https://github.com/WordPress/gutenberg/issues/60021 and https://github.com/WordPress/gutenberg/issues/65298), should these modes persist on refresh, much like top toolbar, distraction free and spotlight do?

If so, your editing experience would be whatever mode you've selected—rather than having it always start on "Design" mode whenever the page is refreshed. I should be able to reload the page and have the work environment remain largely the same.

### Proposal 

Mode is set to persist locally (session or localstorage), not at user preference level. 

### Visual 
![CleanShot 2024-09-23 at 10 53 09](https://github.com/user-attachments/assets/93b1f902-e62c-4036-acbe-9d91a5fc4a7d)

**Comment by ndiego** [comment]
> should these modes persist on refresh, much like top toolbar, distraction free and spotlight do?

Yes, this is what I would expect.
