### ISSUE TITLE
Tabs: select tab id and visual highlight are out of sync when removing tab

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#65576]
This can be currently reproduced in Storybook:

https://github.com/user-attachments/assets/053c0d0e-8f53-4cfb-9416-3c58d8655493

**Comment by ciampo** [comment]
cc @DaniGuardiola

**Comment by DaniGuardiola** [comment]
Yep, I'm aware of this one and have a simple solution already on my mind, just need to get through the in-progress stuff and then I'll handle this. Thanks for reporting.

**Comment by ciampo** [comment]
Just flagging that this bug "evolved" after the latest work on Tabs, and now manifests differently (and arguably providing a worse UX):

https://github.com/user-attachments/assets/cf52d0e6-9319-4dd4-9d19-27421dc6e02e

**Comment by DaniGuardiola** [comment]
Thanks, yeah makes sense that the bug evolved like this, I'm gonna fix this as my next priority as I follow up on the Tabs and ToggleGroupControl work by cleaning things up and sharing a bit more code.
