### ISSUE TITLE
Revert additional "Typesets" panel in Site Editor > Typography

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65575]
Revert https://github.com/WordPress/gutenberg/pull/62539, which creates a standalone nested "Typeset" panel within the Site Editor > Typography panel. It was a good attempt, but in practice just makes the UI more complicated by requiring more effort to discover these. 

I'd expect the typography variations to reside top-level in the Typography panel, like this: 

![CleanShot 2024-09-23 at 12 28 35](https://github.com/user-attachments/assets/d0be9367-3032-417d-8d28-e93d0ff488b1)

**Comment by jffng** [comment]
Closed by #65579.
