### ISSUE TITLE
SASS deprecation message (legacy JS API)

### ISSUE THREAD

**Issue by n3f** [WordPress/gutenberg#65585]
### Description

I apologize if this is covered elsewhere but it didn't seem to be discovered with a search for [sass legacy](https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+is%3Aopen+sass+legacy).

`npx wp-scripts build` should complete without errors, but shows deprecated message:

```txt
LOG from ./node_modules/sass-loader/dist/cjs.js sass-loader ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./src/style.scss
<w> Deprecation The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
<w>
<w> More info: https://sass-lang.com/d/legacy-js-api
<w>
<w> null

LOG from ./node_modules/sass-loader/dist/cjs.js sass-loader ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./src/editor.scss
<w> Deprecation The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
<w>
<w> More info: https://sass-lang.com/d/legacy-js-api
<w>
<w> null
```

### Step-by-step reproduction instructions

1. `npx @wordpress/create-block my-custom-block`
2. `cd my-custom-block`
3. `npx wp-scripts build`

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by n3f** [comment]
It's possible that #37044 is related.

**Comment by ALJ** [comment]
I just started seeing this same deprecation notice today after a fresh install of `@wordpress/scripts`:

```
<w> Deprecation The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
<w> 
<w> More info: https://sass-lang.com/d/legacy-js-api
<w> 
<w> null
```

I believe this is related to `dart-sass` using the legacy JS API still. Version 1.79.0 was released two weeks ago and emits these warnings: https://github.com/sass/dart-sass/pull/2343

I can reliably prevent the warnings by forcing the use of the "modern" JS API by adding the line `api: "modern"` as a new [option in line 206 of wordpress/scripts webpack.config.js](https://github.com/WordPress/gutenberg/blob/078a5820f5c29c8d68d9b9152990fae2018b857c/packages/scripts/config/webpack.config.js#L206). Like this:

```
loader: require.resolve( 'sass-loader' ),
options: {
	sourceMap: ! isProduction,
	api: "modern",
},
```

**Comment by ALJ** [comment]
Hi @n3f if you're able to add more labels to this issue, I think the `[Package] Scripts` GitHub label is appropriate, in addition to the existing bug label.

**Comment by n3f** [comment]
Unfortunately it looks like I don't have the ability to add/edit tags here.

**Comment by gziolo** [comment]
Fixed with https://github.com/WordPress/gutenberg/pull/67572. Tested with `@wordpress/scripts@30.6.2-next.a9f418477.0`. The stable version is expected to be published to npm on Wednesday.
