### ISSUE TITLE
Site Editor: deleting all pages in Pages section causes screen to blank out

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#65621]
Using WP 6.6.2 and GB 19.2, if you delete all pages while in the pages view, the screen blanks out with an error in console:

https://github.com/user-attachments/assets/d3e6d1fb-2a08-4257-bf62-cf5cf4aa8d9b

Error message:

![Screenshot 2024-09-24 at 11 10 18 AM](https://github.com/user-attachments/assets/dc705ffb-1fb6-4747-b2b4-9dc8aba4c051)

To replicate:

1. Open https://playground.wordpress.net/?plugin=gutenberg
2. Go to the Site Editor > Pages.
3. Delete all pages one by one.
4. See error :)

**Comment by colorful-tones** [comment]
I can confirm this is happening with WP 6.6.2 and Gutenberg 19.2, but it does not seem to happen with Gutenberg trunk.

**Comment by annezazu** [comment]
Huzzah. If it's not happening in trunk, let's close in that case. Thank you. I should have tested with that at this point.
