### ISSUE TITLE
Tabs: icon tabs and text tabs have a different height

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#65624]
Text tabs (ie. `<Tabs.Tab>text</Tabs.Tab>`) are `48px` tall: https://wordpress.github.io/gutenberg/?path=/story/components-experimental-tabs--default

Icon tabs (ie. `<Tabs.Tab><Icon /></Tabs.Tab>`) are `56px` tall: https://wordpress.github.io/gutenberg/?path=/story/components-experimental-tabs--with-tab-icons-and-tooltips

Should we revise any aspects of this? It may be tricky to enforce it fully with the current set of APIs, since `Tabs` can not possibly know what its children are.

**Comment by ciampo** [comment]
cc @WordPress/gutenberg-components @WordPress/gutenberg-design

**Comment by jasmussen** [comment]
They should both have the same height, of course. Probably best to maintain the 48px height for now, since it affects a key visual of the editor:

![Screenshot 2024-09-25 at 10 41 21](https://github.com/user-attachments/assets/4ced63df-4d3a-4487-a065-086d0ffc62e0)

**Comment by jameskoster** [comment]
If we used `min-height` and removed vertical padding I think that would solve this issue? Appreciate it wouldn't account for children taller than `48px`, but that feels like an edge case to me.

**Comment by ciampo** [comment]
We could probably just remove the vertical padding and rely on flexbox alignment ?

**Comment by patil-vipul** [comment]
Raising a PR as per the suggestion from @ciampo in sometime.

cc: @ciampo @jameskoster @jasmussen

**Comment by DaniGuardiola** [comment]
The Tabs component is currently heavily in flux, so please hold off on working on this until a few tweaks have been merged. I believe one of the pending PRs fixes this already.

**Comment by DaniGuardiola** [comment]
This will be fixed by https://github.com/WordPress/gutenberg/pull/65387

**Comment by ciampo** [comment]
Closing as fixed in https://github.com/WordPress/gutenberg/pull/65387

**Comment by t-hamano** [comment]
In WordPress 6.7 Beta3, I noticed that the icon tabs are `56px` tall:

https://playground.wordpress.net/?wp=beta

![Image](https://github.com/user-attachments/assets/ca066e5c-85fb-4551-b5c1-1995880e684b)

Whereas in WordPress 6.6, it is `48px`:

https://playground.wordpress.net/?wp=6.6

![Image](https://github.com/user-attachments/assets/4b068ac6-7c3d-4177-a3d5-10358996accf)

Maybe a special backport is needed for WordPress 6.7?

**Comment by ciampo** [comment]
Yup, feel free to backport the fix PR (and any dependent PRs)!

Otherwise I'll work on it on Monday

**Comment by ciampo** [comment]
@t-hamano I'm actually not sure that backporting the PR that fixed this issue is a good idea — the fix is included in https://github.com/WordPress/gutenberg/pull/65387, which introduced substantial changes to the component. In order to merge #65387, we'd likely need to merge a few dependent PRs before AND a few follow-up PRs that fixed a couple of regressions.

A potential list of backports could be:
- Dependant PRs:
	- https://github.com/WordPress/gutenberg/pull/64371
	- https://github.com/WordPress/gutenberg/pull/65878
- The PR including the fix to this issue: https://github.com/WordPress/gutenberg/pull/65387
- Follow-ups / fix regressions:
	- https://github.com/WordPress/gutenberg/pull/66198
	- https://github.com/WordPress/gutenberg/pull/66215

Separately, we may also want to backport these other fixes:
- https://github.com/WordPress/gutenberg/pull/66201
- https://github.com/WordPress/gutenberg/pull/66207


What do you think?

As an alternative, maybe we could apply a specific hotfix just for the 6.7 release?

**Comment by t-hamano** [comment]
@ciampo I have submitted a minimal PR for WP 6.7.

> Separately, we may also want to backport these other fixes:
> - https://github.com/WordPress/gutenberg/pull/66201
> - https://github.com/WordPress/gutenberg/pull/66207
> 
> What do you think?

Are these two bugs first introduced in WP 6.7? If not, I don't think a backport is necessary.
