### ISSUE TITLE
Site editor crashes on searching or navigating page list

### ISSUE THREAD

**Issue by jp-imagines** [WordPress/gutenberg#65622]
### Description

On Gutenberg 19.2.0, interacting with the page list within the site editor causes the editor to crash to a blank screen. This includes searching for a page or moving to the next page of pages.

Only the "list" layout is affected; grid and table do not appear to have the same issue.

### Step-by-step reproduction instructions

1. Start on a site with Gutenberg 19.2.0 and a block theme active. Ensure there are more than 20 pages on the site.
2. Open the site editor (_Appearance > Editor_).
3. From the Design menu, select _Pages_. Ensure the layout is set to "list."
4. At the bottom of the screen, navigate to the second page of the list. Alternatively, use the search box at the top to search for a page.

### Screenshots, screen recording, code snippet

Screen recording:
https://github.com/user-attachments/assets/f6c10683-8feb-4054-a1e4-9a345a4d6140

Browser console errors:
```
TypeError: Cannot read properties of undefined (reading 'id')
    at iS (index.js:177:14)
    at index.tsx:354:37
    at index.tsx:402:25
    at index.tsx:424:4
    at Vr (react-dom.min.js?ver=18:1:73191)
    at Cl (react-dom.min.js?ver=18:1:92835)
    at react-dom.min.js?ver=18:1:91612
    at El (react-dom.min.js?ver=18:1:91672)
    at dl (react-dom.min.js?ver=18:1:85501)
    at Nn (react-dom.min.js?ver=18:1:32432)
react-dom.min.js?ver=18:1

Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at iS (index.js:177:14)
    at index.tsx:354:37
    at index.tsx:402:25
    at index.tsx:424:4
    at Vr (react-dom.min.js?ver=18:1:73191)
    at Cl (react-dom.min.js?ver=18:1:92835)
    at react-dom.min.js?ver=18:1:91612
    at El (react-dom.min.js?ver=18:1:91672)
    at dl (react-dom.min.js?ver=18:1:85501)
    at Nn (react-dom.min.js?ver=18:1:32432)
react-dom.min.js?ver=18:1
```

### Environment info

WordPress 6.6.2, Gutenberg 19.2.0. Not able to replicate in Gutenberg 19.1.0. Reproduced with default _Twenty Twenty-Four_ theme.
Reproduced on both Chrome (Version 129.0.6668.59) and Firefox (130.0.1) on Mac OS 14.6.1.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by ndiego** [comment]
Thanks for reporting @jp-imagines. Can you check to see if this issue still occurs in Gutenberg 19.3? I am not able to replicate it so 🤞 it's fixed in the latest version.

**Comment by jp-imagines** [comment]
Just got a chance to test on 19.3, and I'm no longer able to reproduce this! The next set of pages (and search results) load as expected without errors or crashes. 👍 

I'll go ahead and close this. Thanks for taking a look @ndiego!
