### ISSUE TITLE
Style book and global styles revisions: zoomed out mode and device switching doesn't work

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#65630]
### Description

Because the style book and global style revisions are presented in their own iframes, they're not connected to changes in the canvas width when:

- activating zoomed out mode
- toggling between device previews

I think it goes beyond activating zoomed out mode for these iframes. I tried it and it's not a great experience. Every time the iframe renders the width "bounces" in zoomed out mode.

https://github.com/user-attachments/assets/908f081a-2b07-4e22-a5e0-09101ef9dbe5

> [!TIP]
> A quick fix would be to deactivate the zoomed out / device tools for style book/global styles revisions.

Beyond that, there is an idea to create an editor instance for previewing global styles. This editor would deactivate a lot of block editor tools that are unnecessary.

- https://github.com/WordPress/gutenberg/issues/62216

The zoomed out / device tools could then be introduced incrementally. 

### Step-by-step reproduction instructions

1. Go to the Site Editor
2. Open up the style book or global styles revisions
3. Activate zoom mode - observe that zoomed out mode doesn't activate
4. Toggle the device previews - observe that the canvas width doesn't change

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/efc310d0-f9c6-4bce-a531-a61cbf19b6e1

### Environment info

- WordPress 6.6
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by getdave** [comment]
I think we should disable Zoom Out for these as I don't believe they add any value.

What do you think @richtabor @draganescu @MaggieCabrera?

**Comment by MaggieCabrera** [comment]
> I think we should disable Zoom Out for these as I don't believe they add any value.
> 
> What do you think [@richtabor](https://github.com/richtabor) [@draganescu](https://github.com/draganescu) [@MaggieCabrera](https://github.com/MaggieCabrera)?

Sounds reasonable, we can revisit that decision later on

**Comment by richtabor** [comment]
> I think we should disable Zoom Out for these as I don't believe they add any value.

Yes, that's fine. Perhaps they can be treated just like the device preview control is disabled for template parts.

**Comment by draganescu** [comment]
The problem here is that again (like in the case of the inserter, and `__experimentalSetIsInserterOpened`) we need control to higher level implementation (edit site) from lower level (block editor).

When one clicks zoom out the style preview and stylebook both exit and one gets back to cavas. Maybe that would be jarring and sudden, especially since there wouldn't be a way to get back.

So maybe when style book or styles are in the canvas the control doesn't show. But the canvas mode and editor canvas contaner view are both stuff that only edit site deals with.

I think we should have a sort of getZoomOutAvailability which centralises all the situations where zoom out should not be available and also where the higher implementation which does not work with zoom out can turn it off.

**Comment by t-hamano** [comment]
Looks like we need to disable zoom out on the Styles screen too. See #65991

**Comment by getdave** [comment]
Is the `sectionRootClientId` setting passed in either of these scenarios? It could be that the editor package itself does not provide the setting if the current screen does not support zoom out.

We'd need to change the implementation so that if the setting is specifically `false` (or something specific) then Zoom Out doesn't show or function.

**Comment by ramonjd** [comment]
I managed to get something working using `useSlotFills` to check the slot fill length:

https://github.com/user-attachments/assets/181d78b8-d523-4833-b0e4-1f056c3d858e

There's a flash when toggling between stylebook and revisions - not sure how to mitigate that just yet.  Not sure if it's too sketchy or not, but I'll get a PR up soon and we'll find out 😄 

It's a band-aid solution until an [alternative delivery mechanism](https://github.com/WordPress/gutenberg/issues/62216) is built to display these surrogate canvas views.

**Comment by ramonjd** [comment]
> I managed to get something working using useSlotFills to check the slot fill length ... Not sure if it's too sketchy or not, but I'll get a PR up soon and we'll find out 

Actually, on second thought, I don't think it's a good idea to hide the preview and zoom tools based on whether the slot is filled, because the behaviour we want to control is very specific to style book and revisions. 

> The problem here is that again (like in the case of the inserter, and __experimentalSetIsInserterOpened) we need control to higher level implementation (edit site) from lower level (block editor).

True!

The least worst alternatives I can think of are:

1. Pass down some more values to the [Editor Component](https://github.com/WordPress/gutenberg/blob/fa8b36fb1406dd27528c9f8a0385a5e0d31fcc25/packages/edit-site/src/components/editor/index.js#L222-L222) via [specific editor settings](https://github.com/WordPress/gutenberg/blob/fa8b36fb1406dd27528c9f8a0385a5e0d31fcc25/packages/edit-site/src/components/editor/index.js#L138-L138), something like `settings.visibleTools={ preview: false, zoom: false }`, or whatever var names make more sense.
2. Add a classname to [.edit-site-editor__editor-interface](https://github.com/WordPress/gutenberg/blob/fa8b36fb1406dd27528c9f8a0385a5e0d31fcc25/packages/edit-site/src/components/editor/index.js#L229-L229) and hide it with CSS 🙃

**Comment by draganescu** [comment]
Some of the problems in this issue have been solved.

https://github.com/user-attachments/assets/dceb7813-ad72-4465-8d30-1715cd1c0533

I updated the issue to reflect the remaining issue.

**Comment by ndiego** [comment]
> Some of the problems in this issue have been solved.

@draganescu based on this, do you think we can remove this issue from the 6.7 project board?

**Comment by getdave** [comment]
I think the Editor leads need to test the original report (also trying it on Gutenberg `trunk`) and see if it's still there.

If no one gets here sooner I'll try and do that tomorrow.

**Comment by ramonjd** [comment]
Thank you @draganescu and @getdave 🎉

**Comment by getdave** [comment]
I tested this with the `wp/6.7` branch. My findings:

- I couldn't replicate the original Issue
- I cannot toggle Zoom Out in Style Book - possible bug the "toggle" remains active 🤔 
- Device preview and Zoom Out are mutually exclusive
- Entering Styles will Zoom Out and return to original Zoom state when exited.

I think we can close this out (possibly creating a separate issue for the toggle remaining active).

Do you agree @kevin940726 @ndiego @colorful-tones @draganescu?

https://github.com/user-attachments/assets/83df557f-ac76-4caa-a700-de2ca6215689

**Comment by ndiego** [comment]
I had the same testing results as @getdave. There are a few minor issues with Style Book that would be great to fix in a follow-up, but they are low priority in my opinion for 6.7.  

Ideally, the Zoom Out and Device Preview buttons should be disabled in the Style Book. Right now, they are clickable but do not really do anything. I did notice that the Zoom Out button toggles the breadcrumb bar at the bottom of the window. 

https://github.com/user-attachments/assets/5939ac22-88c0-4cd1-8b8f-c9aabf0bd917

**Comment by getdave** [comment]
> I had the same testing results as @getdave. 

Let's close this one out 👍 


> Ideally, the Zoom Out and Device Preview buttons should be disabled in the Style Book. Right now, they are clickable but do not really do anything. 

We could follow up with that one as a low priority "nice to have" fix.


> I did notice that the Zoom Out button toggles the breadcrumb bar at the bottom of the window.

I believe it's intentional in order to remove "chrome" from the view when zoomed.

**Comment by ndiego** [comment]
> I believe it's intentional in order to remove "chrome" from the view when zoomed.

Yeah, but it happens in the Style Book as well when toggling the Zoom Out button. Again, pretty minor.

**Comment by ndiego** [comment]
> Let's close this one out 👍

Closing out this issue based on the discussion above, but feel free to reopen if needed.
