### ISSUE TITLE
Insert plus and vertical toolbar displaced by UI state

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#65654]
### Description

In zoom out view the state of the UI - mostly of the inserter it appears - displaces some other elements:

- the plus inserter is sometimes positioned off center
- the vertical toolbar is moved to the left as if it's anchored to the inserter not to the selection

### Step-by-step reproduction instructions

1. In a template
2. Add some patterns
3. Save and reload
4. Toggle zoom out view
5. Hover over the top most pattern - don't click it
6. Click the top plus [+] inserter
7. The inserter will open with patterns and All category selected
8. **sometimes the [+] will be offset**
9. Click on one of the patterns
10. Notice the vertical toolbar to the left
11. Close the inserter from the top left x button [x]
12. **Sometimes the toolbar is moved to the left**

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/89b05f8c-38d7-4dfe-aafe-a918c34597e4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by dhruvang21** [comment]
Hello @draganescu,

I created a PR: [#65771](https://github.com/WordPress/gutenberg/pull/65771) to resolve the issue: [#65595](https://github.com/WordPress/gutenberg/issues/65595). I also found that it resolves this issue as well.

I’ve attached a video below showing the resolved issue.
https://github.com/user-attachments/assets/299d3a96-28c8-42a4-b4a0-42a5acd32b86

Thanks!

**Comment by draganescu** [comment]
Same as #65188
