### ISSUE TITLE
Can't import @wordpress/block-editor FontFamilyControl component

### ISSUE THREAD

**Issue by mr660** [WordPress/gutenberg#65655]
### Description

I'm creating custom block for rendering chart and i'm trying to create selector for font families for certain elements.  I'm trying to follow [this] (https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/font-family) readme with no success.

in edit.js file
```
import {InspectorControls, FontFamilyControl} from '@wordpress/block-editor';

export default function Edit({attributes, setAttributes}) {
    return (
        <>
            <InspectorControls>
                <FontFamilyControl
                    value={''}
                    onChange={() => {
                    }}
                />
            </InspectorControls>
        </>
}

```

I get error saying:
```
edit.js:89 Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Edit`.
```

### Step-by-step reproduction instructions

1. Create custom block in theme or plugin and use code above

### Environment info

Wordpress 6.6.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by Mamaduka** [comment]
Try using `__experimentalFontFamilyControl`. The component is an experiment, and it's currently [exported as one](https://github.com/WordPress/gutenberg/blob/0bfec0f91843b993a929e6aafe9548cf07690eea/packages/block-editor/src/components/index.js#L49).

```js
import { InspectorControls, __experimentalFontFamilyControl as FontFamilyControl } from '@wordpress/block-editor';
```

I'll create a PR to fix the examples in README docs.
