### ISSUE TITLE
Zoom out may break out of canvas in Twenty Twenty Five theme

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#65673]
In the report below it appears that TT5 may break Zoom Out (or Zoom Out doesn't cater for something special TT5 is doing).

Pinging @sarahmonster @MaggieCabrera for expertise. 

Needs triage.

-----
![testing](https://github.com/user-attachments/assets/9a18c917-b2d7-4100-9a3b-fce25bc82743)

There's a curious width issue, not sure if it's related to this branch or not:

![widthissue](https://github.com/user-attachments/assets/6f76e96f-9f01-4c6d-8b84-a8bfb41d05ca)

_Originally posted by @jasmussen in https://github.com/WordPress/gutenberg/issues/65392#issuecomment-2376269694_

**Comment by MaggieCabrera** [comment]
I could not reproduce this by inserting these patterns in a page. I did find that the full page patterns in TT5 are wrapped in a group, which invalidates zoom out and maybe that should be patched within the theme

**Comment by MaggieCabrera** [comment]
The problem is the yellow pattern, the text is too big and it causes overflow on zoom out. I am not sure if the problem should be fixed on TT5 or if anything else should be done in zoom out too.

Editor | Frontend
--- | ---
<img width="983" alt="Screenshot 2024-10-03 at 18 39 17" src="https://github.com/user-attachments/assets/efca5055-2ea4-495e-95b8-38f5e24d08c9"> | <img width="1888" alt="Screenshot 2024-10-03 at 18 40 05" src="https://github.com/user-attachments/assets/815ff2eb-5a4d-45a4-87e9-e91593cddd04">

**Comment by jasmussen** [comment]
We probably want to improve it in TT5, however it seems like something we might want zooming to handle as well. Can you try just a really long paragraph, see how that fares?

```
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
```

**Comment by MaggieCabrera** [comment]
There seems to be something weird going on. Without zoom out mode at all, this is the editor vs the frontend:

Editor:
![Image](https://github.com/user-attachments/assets/04ffe87a-6699-4fd6-8c06-3a4e296587f0)

Frontend (a horizontal scrollbar appears):
![Image](https://github.com/user-attachments/assets/03071858-bd0e-4ebd-b244-033ab2c018a9)

**Comment by jasmussen** [comment]
Hrm. We might need a word-break rule somewhere. I guess this is a theme thing?

**Comment by MaggieCabrera** [comment]
> Hrm. We might need a word-break rule somewhere. I guess this is a theme thing?

No, I saved a post with this template pasted and moved to emptytheme and the inconsistency persists

**Comment by getdave** [comment]
This isn't a Zoom Out specific thing then right?

**Comment by MaggieCabrera** [comment]
> This isn't a Zoom Out specific thing then right?

I see two different things here:

- The difference between editor and frontend. That seems like an editor issue
- The zoom out problem, that looks like a zoom out scaling issue, since it should work like the editor and overflow the wording. I think this is covered by https://github.com/WordPress/gutenberg/issues/65757

In any case, TT5 is not at fault beyond just having big text that highlights this issue. I checked the theme and it has very little CSS, so this kind of issue could affect any other theme.

**Comment by richtabor** [comment]
Is it just the big text that is causing the zoom out distortion? We can make it smaller to mask the issue while https://github.com/WordPress/gutenberg/issues/65757 is being explored.

**Comment by MaggieCabrera** [comment]
> Is it just the big text that is causing the zoom out distortion? We can make it smaller to mask the issue while [#65757](https://github.com/WordPress/gutenberg/issues/65757) is being explored.

yes, if you remove the Stories pattern it goes away

**Comment by richtabor** [comment]
Related https://github.com/WordPress/gutenberg/issues/65974

**Comment by colorful-tones** [comment]
I'm not sure how/why this was not on the WP 6.7 board, but I'm adding it now.

**Comment by colorful-tones** [comment]
I just tested this in WP 6.7 beta 2 with Twenty Twenty-Five and I am not able to recreate the original issue reported:

> In the report below it appears that TT5 may break Zoom Out (or Zoom Out doesn't cater for something special TT5 is doing).

and 

> There's a curious width issue, not sure if it's related to this branch or not:

I'm not sure what branch @getdave was referring to?

However, there is a separate issue later referred to and likely worthy of opening a separate issue for: 

> The difference between editor and frontend. That seems like an editor issue

The issue persists, and it seems to be related possibly to browser styling. In Chrome 129 there are some additional styles that are output in the editor only:

```
p[Attributes Style] {
    -webkit-user-modify: read-write;
    overflow-wrap: break-word;
    -webkit-line-break: after-white-space;
}
```

This seems odd to me that they're only output by the browser and only in the editor? 😕 

![Image](https://github.com/user-attachments/assets/3d9a497c-11f8-4cd2-bd28-f6589ca21f1a)

**Comment by MaggieCabrera** [comment]
I think we can close this one as fixed via https://github.com/WordPress/gutenberg/issues/65757 and let's open a new one regarding the frontend/site editor disparity, which is unrelated to zoom out or TT5

**Comment by getdave** [comment]
Ok let's close out 👍
