### ISSUE TITLE
allowedBlocks does not prevent any block from being inserted via the “Enter” key or sibling inserter

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#6569]
## Issue Overview
The `allowedBlocks` attribute of `<InnerBlocks />` is intended to only allow certain blocks to be inserted into a block. However, by pressing <kbd>Enter</kbd> <s>or by using the sibling inserter</s>(fixed by #7226), you can still insert the default block: the Paragraph block.

## Steps to Reproduce (for bugs)
1. Create a block type containing `<div><InnerBlocks allowedBlocks={ [ 'core/list' ] } /></div>` in its editor markup and `<div><InnerBlocks.Content /></div>` in its saved markup. This block should allow only allow List blocks to be inserted into it as children.
2. Insert the block into a post.
3. Insert multiple List blocks into the container block.
4. Try using <s>the sibling inserter or</s> <kbd>Enter</kbd> to insert a Paragraph block.
5. Notice that, although the Paragraph block is not shown in the inserter pop-up, it can still be inserted.

## Expected Behavior
A block that sets `allowedBlocks` in its `<InnerBlocks />` component should only allow the blocks listed in `allowedBlocks` to be inserted into it. Of course, the question of how to still use slash commands and/or the sibling inserter arise, as both involve inserting Paragraph blocks.

## Current Behavior
Using <kbd>Enter</kbd> <s>or the in-between inserter</s>, you can insert any block into a block with an `<InnerBlocks />` component.

## Related Issues and/or PRs
- #5452
- #5540
- #6067
- #6363
- #6394
- #6520
- #6834
- #7184
- #7226
- #7763

## Update: 2018-07-13
Updated this issue to no longer cover the slash command bug, which was already covered by #6070 and was fixed by #6067.

**Comment by jorgefilipecosta** [comment]
The PR https://github.com/WordPress/gutenberg/pull/6067 made the slash command respect allowed blocks.
But we still can not close this issue because if allowedBlocks does not accept core/paragraph it can still be inserted via the in-between inserter.

**Comment by SuperGeniusZeb** [comment]
@jorgefilipecosta Yeah, I created an issue that suggests removing the placeholders from `<InnerBlocks/>` and having the inserter pop-up be accessible directly from the sibling inserter.

**Comment by ktmn** [comment]
Furthermore, I believe if you have `<InnerBlocks allowedBlocks={ [ 'core/list' ] } />` it still allows to insert a paragraph block. In some cases paragraph would not be good, specially as default.

Might be unrelated, but is there a way to create a block that can not be inserted anywhere, but only when specifically mentioned in `allowedBlocks`?

The use case for example would be to make a `custom/list` block that can only accept `custom/listitem` blocks. A `custom/listitem` block inserted outside of the list context would not be formatted correctly.

In this case the `custom/list` would contain `<InnerBlocks allowedBlocks={ [ 'custom/listitem' ] } />` and currently when adding a new item it would still create a paragraph by default, but it should instantly make the list item.

**Comment by chrisvanpatten** [comment]
@ktmn I _think_ the "parent" attribute is what you need. See here in the core column block:

https://github.com/WordPress/gutenberg/blob/master/core-blocks/columns/column.js#L18

**Comment by ktmn** [comment]
@chrisvanpatten thanks, `parent: [ 'custom/list' ],` indeed makes it unavailable to be inserted in any other context. 

Only problem that remains is that when adding a new item it opens a block selector even though only 1 possible option is available and it could just insert that block straight away

![](https://i.imgur.com/5GFbJYE.png)

And if you click the area on the left of the `+` icon it will create a paragraph.

Should I make a separate issue of this?

**Comment by SuperGeniusZeb** [comment]
#7226 has partially fixed another part of this. The default placeholder block no longer appears in nested contexts where the default block (the Paragraph block) is not allowed, and neither does the sibling inserter. Personally, I think the sibling inserter should just open up in the insertion pop-up directly. See #6834 and #7763.

But anyway, that leaves one way left of inserting the wrong block that is described in this issue: pressing <kbd>Enter</kbd>. If you have a block that only allows something like Heading or List blocks and you press <kbd>Enter</kbd> in them, you can create Paragraph blocks even though that should not be allowed.

There is also the issue of being able to move blocks into a context where they are not allowed (which was not mentioned by this issue), but that should be fixed by #7212.

**Comment by designsimply** [comment]
Closing in order to consolidate to #8589 which is a task that should help resolve this issue and other similar cases.
