### ISSUE TITLE
List view: Miscolored icons

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#65697]
<img width="358" alt="Screenshot 2024-09-27 at 09 58 06" src="https://github.com/user-attachments/assets/38d7a8fd-c9ff-4dad-88ae-2cc608d2a83a">

Some of the icons on selected items in List view are dark gray instead of white.

**Comment by t-hamano** [comment]
I found that this problem was caused by #65361. Since #65361 is not part of WP 6.7, I'd like to remove this issue from the project board.
