### ISSUE TITLE
Display block controls after typing and moving the pointer

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#657]
From @jasmussen:

> All block boundaries & controls fade out as soon as you start typing, so you can focus on the content. But as soon as you move the mouse, the boundaries & controls fade in again, as this indicates you might want to manipulate the blocks.

**Comment by iseulde** [comment]
Done in #556.

**Comment by jasmussen** [comment]
Reopening this, as we're 90% there with #556, but not quite.

What works now is:

- click block to show boundaries
- arrow key around without boundaries disappearing
- can even use shift and other keyboard shortcuts without boundaries disappearing
- as soon as you start typing, boundaries fade out —  good
- as soon as you select text, even with shift + arrow keys, boundaries fade back in —  good

The missing piece is _showing the boundaries of the selected block on mouse movement_.

Here's a GIF:

![focus](https://cloud.githubusercontent.com/assets/1204802/26399653/f68ce9b4-407d-11e7-9423-6b886d186076.gif)

**Comment by iseulde** [comment]
Ah, apologies, I always forget about the `mousemove` part.
