### ISSUE TITLE
Gutenberg Conflict With Text Widget In Customizer

### ISSUE THREAD

**Issue by itsdavidmorgan** [WordPress/gutenberg#6570]
## Issue Overview

With Gutenberg active, the "Visual" editor tab and WYSIWYG within the Text Widget becomes disabled. However, the "Text" edit tab remains usable.

## Steps to Reproduce (for bugs)

1. Activate Gutenberg plugin.
2. Enter the customizer.
3. Add a Text Widget to a widget area.
4. Attempt to add content using the Visual editor tab.

## Expected Behavior

Should work the same as when Gutenberg is disabled.

## Current Behavior

Visual editor for Text Widget is unusable.

## Possible Solution

I haven't done thorough testing, but I'm assuming this is some conflict with Gutenberg and the text-widgets.js file in WP core.

## Screenshots / Video

https://cloudup.com/cgFEjebUOH8

## Related Issues and/or PRs

Unaware of any related issues.

**Comment by karmatosed** [comment]
Using Twenty Seventeen and the latest version of Gutenberg I am able to do this.

![2018-05-07 at 21 00](https://user-images.githubusercontent.com/253067/39722200-cd717dfa-5239-11e8-9507-31ee2d558870.png)

Now, this doesn't mean there isn't an issue with maybe the theme you are using and possibly other plugins. Could you try please using the combination I'm testing with?

**Comment by itsdavidmorgan** [comment]
Hey Tammie,

Ah, I should have known. I found the culprit. It turned out to be a custom block plugin I have been developing that was causing the issue.

Thanks!
