### ISSUE TITLE
'focus' doesn't work anymore?

### ISSUE THREAD

**Issue by iwpeifer** [WordPress/gutenberg#6574]
## Issue Overview

Previously on some blocks I had some features only displayed when a block was focused. I achieved this simply by doing a quick focus check (i.e., const SampleFeature = focus && etc ) Now, it seems focus checks always fail.

Chrome
## Expected Behavior
I want a div to show up when a block is focused in the editor, otherwise I want it to be hidden.

## Current Behavior
Any such divs will be hidden whether or not a block is focused in the editor.

## Possible Solution
¯\_(ツ)_/¯

**Comment by ajitbohra** [comment]
Focus was deprecated in favour of isSelected

**Comment by iwpeifer** [comment]
Ahh Thanks
