### ISSUE TITLE
Remove the "Edit" control from the zoom out toolbar

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65746]
I propose we revert the recently added "Edit" button to the zoom out toolbar:

1. With https://github.com/WordPress/gutenberg/pull/65702 incoming, there's less of a need for an additional shortcut to edit the pattern, as you click on a pattern to access its editable blocks. 
2. The "Edit" action and icon do not map to the edit/writing tool in the editor header, as they are presented the same but have quite different results (this just zooms you back in). Related https://github.com/WordPress/gutenberg/issues/65663.  
3. It's much clearer now how to disengage zoom out, with the addition of the toggle in the editor header. 
4. Double-click also exists as a mechanism to disengage zoom out. 

![CleanShot 2024-09-30 at 10 29 42](https://github.com/user-attachments/assets/63e37058-9cbd-40db-ba6d-ede133bfacfd)

**Comment by jeryj** [comment]
A big rationale for adding the Edit button was to allow keyboard users the same affordance as the double click to easily enter the full editing experience while keeping the same selection. It will be much more annoying for keyboard users to exit zoom out mode to edit the canvas if we remove this edit button. Could we rename the button to something clearer now that “Edit” isn’t fully accurate?

I don’t think we should using arguments for removing this button that include clicking as the alternative, as the edit button is an affordance to make it easier for keyboard users.

**Comment by richtabor** [comment]
> I don’t think we should using arguments for removing this button that include clicking as the alternative, as the edit button is an affordance to make it easier for keyboard users.

What keyboard-centric affordances can we have in place to exit zoom out?

**Comment by jeryj** [comment]
I think something that makes it as easy as the double click on the section. If we don't want a toolbar button, maybe pressing Enter while focus is on the section? I'm not sure if that's a good idea or not.

**Comment by jeryj** [comment]
I just tried pressing Enter while on block selection to see what happens... It adds a new empty paragraph block 😅 I don't think that was the intended behavior, so why don't we try that as an affordance for exiting zoom out and see how it feels? Also, given that no one has removed this behavior yet, hopefully it won't interrupt anyone's flow. 

https://github.com/user-attachments/assets/806036aa-862c-4d98-a3b0-72b7317c1e6e

**Comment by richtabor** [comment]
> I just tried pressing Enter while on block selection to see what happens... It adds a new empty paragraph block 😅 I don't think that was the intended behavior, so why don't we try that as an affordance for exiting zoom out and see how it feels? Also, given that no one has removed this behavior yet, hopefully it won't interrupt anyone's flow.

That's interesting. There's potential there. 

Let's just make sure it works well with https://github.com/WordPress/gutenberg/pull/65702, as that will be the standard zoom out experience.

**Comment by getdave** [comment]
Just noting that I don't believe this is going to be targetted for 6.7 so I think we can remove from the board 🙇
