### ISSUE TITLE
Inserters move when dragging patterns into the zoomed out canvas

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65748]
The inserter should not move when the drop zone is rendering above and below a patten when zoomed out. Currently it covers the "Drop pattern" label. Should those persistent inserters not render when the drop zone is rendered? 

https://github.com/user-attachments/assets/8336742c-b0fd-4a60-b091-a2bff6a04464

**Comment by getdave** [comment]
This will need backporting to 6.7. Thanks for adding to the board 👍

**Comment by getdave** [comment]
The `isDraggingBlocks` selector does not seem to update in response to dragging from the inserter. It remains `false` always 🤔

**Comment by getdave** [comment]
Ah we have `isDragging` as a private selector
