### ISSUE TITLE
Try zooming out when selecting the patterns tab in the inserter

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65749]
Now that it's clearer how to disengage zoom out, with the [toggle in the editor header](https://github.com/WordPress/gutenberg/pull/65183) and [double-click](https://github.com/WordPress/gutenberg/pull/64573), let's try introducing zoom out on pattern tab selection as well. Previously, the concern was about inserting patterns within patterns, but now that you can toggle off zoom out right from the header, to insert patterns wherever, I think it's worth exploring this further. 

Inserting sections of a site with zoom out engaged is a much better experience than without, as patterns are stacked consistently—not placed within other columns, groups, etc. 

![CleanShot 2024-09-30 at 10 58 07](https://github.com/user-attachments/assets/e3cbd6be-c2b6-42f8-b9e2-171c06a9bc08)

**Comment by jeryj** [comment]
If zoom out is not engaged, then we engage zoom out when entering the pattern tab. Do we automatically disengage zoom out when clicking away from the pattern tab? 

We’ll need to make sure if zoom out is already engaged when going into patterns that we don’t disengage zoom out when clicking away

**Comment by richtabor** [comment]
> Do we automatically disengage zoom out when clicking away from the pattern tab?

Yes. If you switch back to "Blocks" it zooms back in.

**Comment by getdave** [comment]
@richtabor just noting that I don't believe this is going to be targeted for 6.7 so I think we can remove from the board. Is that correct?

**Comment by draganescu** [comment]
- Does going to media reset the view or keeps the zoom out view?
- If zoom out is engaged _manually_ does any action in the inserter disengage it? (closing the inserter, switching to tabs)

**Comment by richtabor** [comment]
> Does going to media reset the view or keeps the zoom out view?

Maintains current zoom state. 

> If zoom out is engaged manually does any action in the inserter disengage it? (closing the inserter, switching to tabs)

Yes, when switching to Blocks. 

Yes, I think when zoomed out and you close the inserter, the canvas should zoom back in. You can get stuck otherwise.

**Comment by getdave** [comment]
No need to backport this one.

**Comment by afercia** [comment]
Going through all the changes for WP 6.8 I noticed this change and I have a question about it: why https://github.com/WordPress/gutenberg/pull/65785 is implemented only in the Site Editor? 
In the Post editor, zoom out isn't activated automatically when selecting the Patterns tab.

How this clearly inconsistent user experience between the two editors helps users in any way? Is there any specific reason why it's not implemented in the Post editor or anything else I may be missing?
@WordPress/gutenberg-design

**Comment by t-hamano** [comment]
> why https://github.com/WordPress/gutenberg/pull/65785 is implemented only in the Site Editor? 
> In the Post editor, zoom out isn't activated automatically when selecting the Patterns tab.

To be precise, zoom out is enabled if a section root is present, i.e. "Show template" is enabled.

"Show template" enabled:

![Image](https://github.com/user-attachments/assets/97dfd10c-9f80-45f1-a397-878d922621c4)

"Show template" disabled:

![Image](https://github.com/user-attachments/assets/dd13c79f-94fc-4b8f-a97a-58678b2fa95b)

See https://github.com/WordPress/gutenberg/pull/67232 for more details.
