### ISSUE TITLE
Thick, blurry, block outlines while zoomed out

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65744]
The outline styles on block hover and selection are thicker than they should be when zoomed out, blurry even. This will become more prominent as each section's blocks can be edited in zoom out—as seen in https://github.com/WordPress/gutenberg/pull/65702#issuecomment-2383240162. 

![CleanShot 2024-09-30 at 09 45 27](https://github.com/user-attachments/assets/3c71ffad-7340-46b5-82fe-4637786a06ba)

I expect these outlines to be the same style as when not zoomed out.

**Comment by getdave** [comment]
This will need backporting to 6.7. Thanks for adding to the board 👍

**Comment by youknowriad** [comment]
Looking at the code, it seems the outline width is rendered within the iframe which means it's impacted by the zoom-scaling.  So by default it would appear thinner and to account for that scale, we scale it back using CSS which produces the blurry effect I guess.

**Comment by youknowriad** [comment]
So not easy solution here :) 

Two potential solutions:

 - Accept that the outline is thinner/scaled down when zoomed out.
 - Try a "JS based outline": Do not apply the zoom-out within the iframe and instead use a `BlockPopover` similar to what we do for the block toolbar to render the outline outside of the iframe. (Might be subject to small glitches if the block changes size when it's actually selected...)

**Comment by richtabor** [comment]
Did something change recently? It's looking a bit better. 

https://github.com/user-attachments/assets/1be386cb-78c4-4236-b9f4-4d9b4b5241e4

**Comment by getdave** [comment]
I'm not aware of any PRs directly targeting this specific bug. However, if it's improved then I'd be more than happy to see this closed out. I think this can be your call @richtabor 🙇

**Comment by richtabor** [comment]
I'm cool with closing for now. It's ok as-is.
