### ISSUE TITLE
Only render zoom out inserters on block selection

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65754]
Rendering the block inserters on hover as well as selection makes them feel quite fragile and disorienting, as they render quite a bit. I propose that the inserters are rendered only when selecting a section. 

https://github.com/user-attachments/assets/49a34cc2-b743-421f-aa7c-9e9658eb2d22

**Comment by getdave** [comment]
This will need backporting to 6.7. I'll add to the board.

**Comment by draganescu** [comment]
Is this still an issue? My inserters only render when something is selected.

**Comment by jeryj** [comment]
Should have been closed by https://github.com/WordPress/gutenberg/pull/65759
