### ISSUE TITLE
Only render the zoom out inserter after the selected block, not before

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65756]
To help reduce conflicts as seen below, let's only render the inserter after the selected block when zoomed out: 

https://github.com/user-attachments/assets/73f1c8db-73c3-4a48-8f0e-77d6f6442383

Note that this _may_ not be necessary, if https://github.com/WordPress/gutenberg/issues/65754 is completed and feels alright. The scenario above would not be possible, as the inserter would only render on block selection.

**Comment by jeryj** [comment]
Rather than only do the bottom one, I’d also support only showing them on block selection or an extended hover at an allowed insertion area (like in the normal block canvas). If we only do the bottom one, we won’t be able to insert a pattern before the first section.

**Comment by richtabor** [comment]
>  I’d also support only showing them on block selection or an extended hover at an allowed insertion area (like in the normal block canvas).

Yea, that should be the first attempt before not showing the before one. https://github.com/WordPress/gutenberg/issues/65754

**Comment by getdave** [comment]
This will need backporting to 6.7. I'll add to the board.

**Comment by jeryj** [comment]
@richtabor Should this be closed because https://github.com/WordPress/gutenberg/pull/65759 to only show inserters when a block is selected?

**Comment by richtabor** [comment]
> @richtabor Should this be closed because https://github.com/WordPress/gutenberg/pull/65759 to only show inserters when a block is selected?

Sure, I think https://github.com/WordPress/gutenberg/pull/65759 worked out well.
