### ISSUE TITLE
PHP Notice: Undefined index: content in lib/rest-api.php

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#6575]
## Issue Overview
When accessing a page or post getting a PHP notice saved to the `debug.log`.

PHP Notice: Undefined index: https://github.com/WordPress/gutenberg/blob/v2.8.0/lib/rest-api.php#L260

## Steps to Reproduce (for bugs)
1. Edit a post or page
2. Access the `debug.log`

Gutenberg 2.8.0

## Expected Behavior
No PHP Notice.

## Related Issues and/or PRs
#6436

**Comment by pento** [comment]
Thanks for the bug report, @grappler! We can get this fixed up. 🙂

**Comment by gziolo** [comment]
It should be fixed with #6576.
