### ISSUE TITLE
Zoom out disengages unexpectedly when double-clicking to select all text

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65750]
Once you are able to select nested blocks to edit with https://github.com/WordPress/gutenberg/pull/65702, you will be able to  double-click to select all the text contents of a block—but doing so (a common practice to select all text within a block) will disengage zoom out unexpectedly. 

Perhaps enable the listener directly on the section, not all blocks. 

https://github.com/user-attachments/assets/83c8e7d0-6a82-4fde-a417-d52bd75a730c

Related https://github.com/WordPress/gutenberg/pull/64573.

**Comment by getdave** [comment]
Just noting that I don't believe this is going to be targeted for 6.7 so I think we can remove from the board 🙇

**Comment by getdave** [comment]
Maybe fixed by https://github.com/WordPress/gutenberg/pull/65782

**Comment by getdave** [comment]
@colorful-tones @ndiego @kevin940726 I'm removing this form 6.7 board as I don't believe it's targeting 6.7 as it's discussed possible future functionality and features.

**Comment by draganescu** [comment]
Can we only preserver double click on the workspace area (the gray zone)?

**Comment by richtabor** [comment]
> Can we only preserver double click on the workspace area (the gray zone)?

I think it'll be a nice experience if you double-click and you zoom into the pattern you created. i.e. https://github.com/WordPress/gutenberg/issues/65884

**Comment by afercia** [comment]
> you will be able to double-click to select all the text contents of a block

Just to be accurate, the native behavior is that a double-click selects a word. The triple-click selects an entire block of text. 

This double-click conflict was originally reported in this comment: https://github.com/WordPress/gutenberg/pull/65702#issuecomment-2401499940

> Double-click to exit zoom out:
> I'm not sure this is an ideal interaction in the first place. It would be totally unexpected, especially when the double click is performed on a block of text. I expect the native click behavior to always work:

> - Single clilck: places the cursor in an editable area.
> - Double click: selects a word, whether it's in an editable area or not doesn't matter.
> - Triple click: selects the entire block of text, whether it's in an editable area or not doesn't matter.

> These are native, expected, interactions that shouldn't be hijacked.

**Comment by richtabor** [comment]
Noting that this is only necessary if we proceed with https://github.com/WordPress/gutenberg/pull/65702.

**Comment by richtabor** [comment]
I'm going to go ahead and close this as not-planned per the feedback on https://github.com/WordPress/gutenberg/pull/65702. It doesnt seem like https://github.com/WordPress/gutenberg/pull/65702 is necessary to more forward currently.
