### ISSUE TITLE
Javascript error when resetting Font Size Presets

### ISSUE THREAD

**Issue by benniledl** [WordPress/gutenberg#65774]
### Description

Hello all!

I've got a javascript error and the editor crashed when doing the following:

### Step-by-step reproduction instructions

1. opening global styles
2. typography
3. font size presets
4. add a new individual font size preset
5. click on the new individual preset
6. next to the revisions button click on the 3 dots
7. click reset styles

### Screenshots, screen recording, code snippet

TypeError: f is undefined
    Kh https://hostingtools.at/wordpress/wp-includes/js/dist/edit-site.min.js?ver=5a21c7ca87b2d5588902:11
    ht https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    vr https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    Qs https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    wl https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    bl https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    yl https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    il https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    fl https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    Nn https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    ul https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
[react-dom.min.js:10:53523]

https://github.com/user-attachments/assets/47ed221e-c606-4f2e-b1d9-c7a13e36ddf0

### Environment info

Firefox,
completely fresh and unmodified WordPress 6.7-beta1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by firoz2456** [comment]
Yes, I am getting the same error with fresh installation of WordPress 6.7-beta1
Google Chrome
PHP 8.1.29
nginx
LocalWP
![image](https://github.com/user-attachments/assets/a065a8ce-6542-46db-8e29-5d6a87879c29)

**Comment by nith53** [comment]
I was also able to replicate it.
![font=preset-error](https://github.com/user-attachments/assets/08769b8a-3514-4852-97ee-5e3d4ea2cede)

**Comment by t-hamano** [comment]
Thanks for the report. The error log when `SCRIPT_DEBUG` is enabled is as follows:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'fluid') at FontSize (font-size.js:57:12)
```

Resetting the global styles discards any custom font size presets. This would cause a critical error, as the font size preset panel is built around the assumption that the font preset exists.

Perhaps the ideal solution would be to switch back from the specific preset panel to the previous screen, i.e. the preset list panel, when the global styles are reset.

cc @matiasbenedetto @mikachan

**Comment by benniledl** [comment]
# Remove the "Reset styles" button
I think the reset styles button should be removed from the specific preset panel (clicking on a preset) and moved to the overview of all presets. 

Because having a reset styles button on this specific preset panel could imply that you are only resetting this one (currently selected) preset and not every preset.

## Remove from here (since it implies that reset is only affecting currently selected preset):
![Screenshot 2024-10-01 at 13-48-51 Blog-Startseite ‹ Template ‹ Testsite ‹ Editor — WordPress](https://github.com/user-attachments/assets/d13f99ad-b277-4701-abb5-4d5d141d4fb2)

## Only leave it here:
![Screenshot 2024-10-01 at 13-49-18 Blog-Startseite ‹ Template ‹ Testsite ‹ Editor — WordPress](https://github.com/user-attachments/assets/7a6c8ce3-955b-46c9-a645-b9d55206e571)

**Comment by matiasbenedetto** [comment]
> I think the reset styles button should be removed from the specific preset panel (clicking on a preset) and moved to the overview of all presets.

> Because having a reset styles button on this specific preset panel could imply that you are only resetting this one (currently selected) preset and not every preset.

> Remove from here (since it implies that reset is only affecting currently selected preset):

I think this makes sense, but it's out of the scope of this particular bug because it will impact all the styles / presets.

**Comment by t-hamano** [comment]
@matiasbenedetto I have filed #65765 to resolve a different issue with font size presets (and shadow presets). #65765 does not need to be backported to WP 6.7, but the fix for this issue does need to be backported to WP 6.7, so it might be better to fix this issue before merging #65765.

**Comment by matiasbenedetto** [comment]
A potential fix for this particular bug: https://github.com/WordPress/gutenberg/pull/65791

**Comment by matiasbenedetto** [comment]
> @matiasbenedetto I have filed #65765 to resolve a different issue with font size presets (and shadow presets). #65765 does not need to be backported to WP 6.7, but the fix for this issue does need to be backported to WP 6.7, so it might be better to fix this issue before merging #65765.

Sorry for the overlap I will take a look.

**Comment by nith53** [comment]
Is a trac ticket needed for the backport? @t-hamano

**Comment by t-hamano** [comment]
@nith53 No, the fix will be automatically cherry-picked and committed to the `wp/6.7` branch and will be bundled in the next beta release.

**Comment by benniledl** [comment]
Hello @ciampo @t-hamano @matiasbenedetto 

Some similar behavior applies to Shadows, if you reset the styles and then keep editing the currently selected shadow there is an error.
A new ticket for this: #65930
