### ISSUE TITLE
Zoom out mode doesn't persist when switching to code editor or between templates

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#65783]
### Description

When in zoomed-out view and switching to the code editor, the zoomed-out mode doesn't persist when closing the code editor. However, the button in the header remains active.

### Step-by-step reproduction instructions

Enable zoomed-out view (tested in post editor):

<img width="1278" alt="Screenshot 2024-10-01 at 14 13 48" src="https://github.com/user-attachments/assets/c02836f0-1213-4ad8-bd0e-9f969dcc9324">

Switch to code editor:

<img width="1276" alt="Screenshot 2024-10-01 at 14 13 59" src="https://github.com/user-attachments/assets/7c7a35cb-6eb6-4d8e-a3d8-f33d49fa3658">

Exit code editor:

<img width="1272" alt="Screenshot 2024-10-01 at 14 14 33" src="https://github.com/user-attachments/assets/5d4d975b-37a9-4cac-a6b3-2e7d98b70f77">

Note how the editor isn't in zoomed-out mode but the zoomed-out button remains active:

<img width="1278" alt="Screenshot 2024-10-01 at 14 14 46" src="https://github.com/user-attachments/assets/60057e7a-7e86-433e-ba80-209b5174eb77">

### Environment info

- Gutenberg `trunk` as of Oct 1
- Chrome

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by simison** [comment]
I expected to stay in the zoomed out mode, but if that's not what should happen, then the button at least shouldn't remain active upon switching to code editor.

**Comment by madhusudhand** [comment]
The same issue observed while switching templates:

Steps:

1. Go to zoom out mode
2. Switch to a different template
3. Zoom out button stays active, but the content goes to normal mode.

<image width="500" src="https://github.com/user-attachments/assets/3df81a5d-97d5-4d0e-966c-2f2246e4e5cf" />
<image width="500" src="https://github.com/user-attachments/assets/75547d39-4923-43ad-8be4-604cc45ecc11" />
<image width="500" src="https://github.com/user-attachments/assets/cdabc0ed-940d-42d2-8fff-71620d9bd091" />

**Comment by getdave** [comment]
I suspect that the _state_ for Zoom Out is still "active" but the _UI_ has reset itself. There maybe an effect or listener that handles toggling the "zoom" that we need to make more intelligent / reactive.

**Update**: I tested and indeed it is only the "zooming of the canvas" that isn't displayed properly. The actual "zoom out" mode remains active.

**Comment by madhusudhand** [comment]
> Update: I tested and indeed it is only the "zooming of the canvas" that isn't displayed properly. The actual "zoom out" mode remains active.

Yes, `zoom out` remains active. 

The issue is due to value of `prevContainerWidthRef.current` being `undefined`
It is because the component is removed from the dom and added again, when switched to code editor and then back to editor

I have put [this condition](https://github.com/WordPress/gutenberg/pull/65932/files#diff-ab17abd38e687edd56573694ae3017e105e96b319571c190e9d4705c1872bc9cR245), it works for code editor switching (because the container width doesn't change), but fails when switching to different template.

I guess we either need to save `prevContainerWidth` in the store or in the localStorage may be?

@getdave thoughts?
