### ISSUE TITLE
Unable to delete empty paragraph block

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#6579]
## Issue Overview
Unable to delete empty paragraph block. I was copying content from Word/Pages and pasting it as "Paste and Match Style". This was creating empty paragraphs. This would not be a problem if I could delete the empty blocks.

## Steps to Reproduce (for bugs)
1. Add the following to via the via the "Code Editor" between other blocks
```
<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->
```
2. Try to delete the block using the mouse 🍀 
3. Type somthing
4. Now try to delete the block.

Chrome and Gutenberg 2.8

## Expected Behavior
Be able to delete the empty block without having type something in the block first.

## Current Behavior
Unable to delete empty paragraph block.

**Comment by ocean90** [comment]
You should be able to delete the paragraph block by clicking the delete key.

**Comment by gziolo** [comment]
I think we still should provide `trash` icon for better UX. Or should we just close? /cc @karmatosed @jasmussen

**Comment by grappler** [comment]
The empty paragraph is the only one that does not have trash icon. I don't think that is consistent UX.

Either we should have the icon everywhere or remove it completely. I could get used to deleting all blocks with the keyboard.

**Comment by karmatosed** [comment]
I would actually second having the trash icon on it to delete. I say this as myself looking for it the other day. I also think whilst we know keyboard actions many won't or at least won't first few uses.

**Comment by SuperGeniusZeb** [comment]
I also think that the delete/trash button should be added to empty Paragraph blocks. Several times I have found myself quickly deleting a series of blocks using the delete icon on hover, only to get a little confused for a moment when the button is not there for the Paragraph block, which causes me to have to switch to using the keyboard for a moment.

**Comment by antonioguedes** [comment]
Found out that when you have 2 or more empty columns in one block, if you go to the menu and click on the three lines (hamburger menu) next to the icon "i", select > column > then on the right where you see the number of columns you can create, just delete whatever number is there, and boom! Block is deleted!

**Comment by dkvadratu** [comment]
WP 5.4 not possible to remove empty paragraph, and it generates empty <p> in front.
![image](https://user-images.githubusercontent.com/7911433/78120744-23ad9300-7413-11ea-81fa-e8c286808b08.png)

**Comment by alejandro-moreno-mvd** [comment]
> Found out that when you have 2 or more empty columns in one block, if you go to the menu and click on the three lines (hamburger menu) next to the icon "i", select > column > then on the right where you see the number of columns you can create, just delete whatever number is there, and boom! Block is deleted!

That works on 5.4.1

**Comment by kubiqsk** [comment]
This problem is again in the newest WP 6.5.2
Empty paragraph can not be removed by Delete or Backspace
