### ISSUE TITLE
Global styles: incorrect usage of `Navigator.BackButton`

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#65794]
While working on https://github.com/WordPress/gutenberg/pull/65790, I noticed that the `ScreenHeader` has a `onBack` prop that gets called when `Navigator.BackButton` gets clicked:

https://github.com/WordPress/gutenberg/blob/8e4aac8d2b435bb8ac74851ebff86cae1547a404/packages/edit-site/src/components/global-styles/header.js#L21-L26

`Navigator.BackButton` already performs a backward navigation (to the "parent" screen) — but I noticed usages where consumers of `ScreenHeader` use the `onBack` callback to trigger another navigation. This can cause unintended consequences, since it may trigger `Navigator` to make two consecutive navigations. 

I could spot two usages:

### Font sizes screen

https://github.com/WordPress/gutenberg/blob/8e4aac8d2b435bb8ac74851ebff86cae1547a404/packages/edit-site/src/components/global-styles/font-sizes/font-size.js#L154

Calling `goTo` seems totally unnecessary here — if we just let `Navigator.BackButton` do its job, I believe it would take us to the same screen. Also, using `goTo` without the `isBack` option causes the transition to move in the wrong direction.

### Revisions screen

https://github.com/WordPress/gutenberg/blob/8e4aac8d2b435bb8ac74851ebff86cae1547a404/packages/edit-site/src/components/global-styles/screen-revisions/index.js#L143 

Here I may need @ramonjd and @andrewserong 's help to understand why we need to navigate to `/` when clicking back.

Could we change the code so that `Navigator.BackButton`'s original behaviour is preserved?

Alternatively, we'll need to see if we can `preventDefault`, or consider rendering a `Button` (instead of `Navigator.BackButton`) in `ScreenHeader`, and make the `onBack` callback an alternative to the "default" going back behaviour, instead of an addition.

**Comment by ramonjd** [comment]
>  understand why we need to navigate to / when clicking back.

Thanks for the ping. I think it was because:

1. There's no intermediate path, so root seemed like the best option
2. I didn't know about `Navigator.BackButton`!!  **TIL**

> Could we change the code so that Navigator.BackButton's original behaviour is preserved?

I'll test

**Comment by ramonjd** [comment]
This one is for the global styles: https://github.com/WordPress/gutenberg/pull/65810

I looked briefly into the font sizes panel, but it appears there's an existing bug that's preventing testing - the `origin` and `slug` are [missing from navigation route](https://github.com/WordPress/gutenberg/blob/c22ed15332bf4ebdbf00eda6112cccf37e81c8f3/packages/edit-site/src/components/global-styles/font-sizes/font-size.js#L38-L38).

**Comment by ramonjd** [comment]
> I looked briefly into the font sizes panel, but it appears there's an existing bug that's preventing testing - the origin and slug are [missing from navigation route](https://github.com/WordPress/gutenberg/blob/c22ed15332bf4ebdbf00eda6112cccf37e81c8f3/packages/edit-site/src/components/global-styles/font-sizes/font-size.js#L38-L38).

Fix incoming

**Comment by ramonjd** [comment]
>  onBack={ () => goTo( '/typography/font-sizes/' ) } 

I think the font sizes component needs this. Otherwise, it'll skip the intermediary font sizes list:

https://github.com/user-attachments/assets/1de3a692-f87f-4dbe-b054-7c55cd767ea0

So it might need a button refactor as you suggest. I'll just add the fix for the bug I saw for now.

**Comment by ciampo** [comment]
> > I looked briefly into the font sizes panel, but it appears there's an existing bug that's preventing testing - the origin and slug are [missing from navigation route](https://github.com/WordPress/gutenberg/blob/c22ed15332bf4ebdbf00eda6112cccf37e81c8f3/packages/edit-site/src/components/global-styles/font-sizes/font-size.js#L38-L38).
> 
> Fix incoming

There are already two PRs with potential fixes:

- https://github.com/WordPress/gutenberg/pull/65765
- https://github.com/WordPress/gutenberg/pull/65790

I admittedly forgot to give y'all context about this bug, my bad


There is also another PR that is fixing a separate issue https://github.com/WordPress/gutenberg/pull/65791

Probably better to wait for the dust to settle on these urgent bug fixes, and then look at the code again

**Comment by ciampo** [comment]
> So it might need a button refactor as you suggest. I'll just add the fix for the bug I saw for now.

Could we instead tweak the intermediate screen's path, so that it follows a "hierarchic" URL scheme? That should cause the default behavior of `Navigator.BackButton` to work as expected

**Comment by ciampo** [comment]
With #65942 and #65946 merged, I think we can close this issue too.

Thank you all for the help!
