### ISSUE TITLE
Use of loop and autostart in <audio> causes unknown error

### ISSUE THREAD

**Issue by Ruifrok** [WordPress/gutenberg#6581]
## Issue Overview

Use of loop and autostart in <audio> causes unknown error

## Steps to Reproduce (for bugs)

1. Add audio block
2. Use edit as HTML to add the loop and/or autoplay attributes to the<audio> tag.
3. Update the post.
4. message: block has been changed
5. Click edit as HTML in the block.
6. block shows unknown error. No HTML is shown
7. Switch to code editor: the string ="" is added to the controls, loop and autoplay attributes

Firefox 59.0.3, Chrome 66, Gutenberg 2.8

## Expected Behavior

Preferably the addition of loop and autoplay options(checkboxes), as are available when using the audio shortcode.
At least allow for the error free addition of attributes.

**Comment by danielbachhuber** [comment]
Thanks for the report, @Ruifrok.

This issue is related to a general class of issues stemming from the Gutenberg's decision to drop "unknown" HTML attributes. I think we'll need to address this in some way before WordPress 5.0.

**Comment by Ruifrok** [comment]
Would solve the problem, I think

**Comment by karmatosed** [comment]
I am fine with those settings but as it's additional to what we have right now in WordPress it would be a lower priority. I think the bug here is to fix that it can be done in way it is now - that also wouldn't require any new interface.

**Comment by Ruifrok** [comment]
If it is additional is disputable, I think. You are right when adding audio initially. However when you click the pencil mark for the added audio, a screen opens where you can set preload, autoplay and loop.
But as mentioned, I can live with a solution where I can add html-allowed attributes without generating an error. The question is: Do you want to force code editing where we now have screen to choose the attributes.
