### ISSUE TITLE
Sticky mode error not working, Sticky function is enabled but when scrolling the page it drifts away

### ISSUE THREAD

**Issue by phanduynam** [WordPress/gutenberg#65813]
### Description

Sticky block Group feature is not working. I expect the Header to be Sticky but when I scroll the page it gets lost. Website: nam1.000.pe

### Step-by-step reproduction instructions

1. go to block Group settings
2. scroll down to Position option
3. enter select Sticky and save settings
4. scroll down the website but Sticky not working

### Screenshots, screen recording, code snippet

https://drive.google.com/file/d/1cabRQXmV9iN6aOw-lmGGP8WyqmdXVVoi/view?usp=sharing

![Ảnh chụp màn hình 2024-10-02 110855](https://github.com/user-attachments/assets/ee6c00d5-92c7-4859-be6f-fa07c24893ac)

### Environment info

1. WordPress 6.6.2
2. Gutenberg 19.3.0
3. Theme TwentyTwentyFour 1.2
4. Chrome 129, Safari 18.0
5. Laptop Windows 11 23h2, iPhone iOS 18.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by ocean90** [comment]
Hello there, this is a known issue. Please follow #47043 and #56147 for more details.

There's also a workaround mentioned in https://github.com/WordPress/gutenberg/issues/64089#issuecomment-2258204834.
