### ISSUE TITLE
Using trim() in onChange callback "disables" space key 

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#6582]
## Issue Overview
This might be just for documentation and people like me wondering why they can't add a space into a text input. But there's one inconsistence, see last paragraph.

## Steps to Reproduce (for bugs)
1. Add a `<TextControl />` component to a block.
2. Define a `onChange` callback like:
```js
onChange={ ( newValue ) => {
    setAttributes( { value: newValue.trim() } );
} }
```
3. Enter something and click the space key, notice that no whitespace is added.

## "Expected" Behavior
My (incorrect) assumption was that the `onChange` callback is only triggered once I'm finished adding something to the field.

Now to the inconsistence: If you use `type="email"` this behaviour doesn't exist. While the `trim()` is happening and the value attribute gets changed the visible value can have trailing spaces.

<img width="867" alt="email-field" src="https://user-images.githubusercontent.com/617637/39619210-454911fe-4f87-11e8-8c4a-27a0e893ca66.png">

**Comment by youknowriad** [comment]
Yes, that's how onChange works it's called on each type and since it's a "controlled" component, the value is constantly rerendered which means if you trim the space, it will be removed instantaneously.

If you really want to do this, you can do this with a regular input and a combination of `onBlur` `onChange` and state (state keeps track of the currently typed value and when `onBlur` triggers you set the attribute with a trimmed value.

Thanks for opening the issue, hopefully it will serve as documentation for others.

**Comment by ocean90** [comment]
Any idea why it's different for the email type?

**Comment by youknowriad** [comment]
It's not different, and I don't think we ship an `EmailControl` in Gutenberg. If you're omitting the `value` prop when using the email input (or any other input), it means your Input is uncontrolled (the value represented can be different from the real value). In general we favor Controlled components but there are exceptions https://reactjs.org/docs/forms.html#controlled-components

**Comment by ocean90** [comment]
> It's not different, and I don't think we ship an EmailControl in Gutenberg.

I'm speaking about `<TextControl type="email" />`, see https://github.com/WordPress/gutenberg/blob/5a6fe0d88a71ce025cb1348ced759918af238180/components/text-control/README.md#type

Others like `<TextControl type="url" />` or `<TextControl type="tel" />` have the same behaviour, it's just `<TextControl type="email" />` which different. 🤷‍♂️

**Comment by youknowriad** [comment]
Oh right :) I just looked at the code and there's nothing special about the `email` type. Might be a browser thing?
