### ISSUE TITLE
Inserter: nested overflow on patterns tab

### ISSUE THREAD

**Issue by stokesman** [WordPress/gutenberg#65837]
### Description

There’s an extra scrolling area appearing in the inserter on the patterns tab (probably the media tab too if it had enough content to overflow).

It seems to have come about after #64371 (tested by checking out the parent commit b7bf13396a690971bd7d4f5c8754dc07a36549c6 and noting the lack of the issue). It may be that it’s no fault of that PR’s changes and some detail of this use case is "doing it wrong".

### Step-by-step reproduction instructions

1. Have a look at the patterns tab with a window short enough that there’s overflow

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/5bae29df-47d0-4b15-b01d-d85ddaa8b1e0

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by ciampo** [comment]
Is https://github.com/WordPress/gutenberg/pull/65387 fixing this issue for you?

cc @DaniGuardiola

**Comment by DaniGuardiola** [comment]
I fixed this issue in https://github.com/WordPress/gutenberg/pull/65387
