### ISSUE TITLE
Fix implementation of Zoom Out Toolbar spacing to match expectations of @wordpress/components

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#65852]
As per the comment below, let's revise the implementation of the vertical toolbar so that its following best practises in regards to `@wordpress/components`.

I'll take point on this as the person who was too quick to merge the originating PR.

------

I would ask you to revisit the approach taken here:

- Please do not use `.components-*` class names outside the `@wordpress/components` package. These are intended as private APIs;
- Also, please do not override styles that are meant to be controlled by components itself — `Button` comes with a set of available heights. It those heights don't suit your needs, it's a sign that the design that you're implementing is not following best practices. Or, otherwise, it's a sign that the design guidelines should be updated to keep this new scenario into account
- In this specific case, you should be able to achieve the same effect by setting the `__next40pxDefaultSize` prop on the affected `Button` components — no need to apply any external CSS at all. Soon we will switch all instances of `Button` to have a height of 40px by default.

Those are best practices that can go a long way in raising the quality of our code and our UIs; they are something that we hope everyone working on Gutenberg can learn and apply both when authoring and when reviewing code. 

cc @WordPress/gutenberg-components @WordPress/gutenberg-design

_Originally posted by @ciampo in https://github.com/WordPress/gutenberg/issues/63994#issuecomment-2391109041_

**Comment by ciampo** [comment]
Thank you @getdave for taking ownership!

I think, as you suggested, that writing better public documentation can help folks align better with what we think are some best practices to ensure UI and code quality.

Regarding this specific case, I think we should understand if the design implemented for the vertical toolbar is going to stay — in that case, we should bring any changes directly to the toolbar component, avoiding the need for any style overrides in consumer-land

**Comment by getdave** [comment]
This was closed in https://github.com/WordPress/gutenberg/pull/65858
