### ISSUE TITLE
Providing editor color palette in named arrays breaks background colors

### ISSUE THREAD

**Issue by davidwolfpaw** [WordPress/gutenberg#6585]
Prior to Gutenberg v2.7.0 I provided theme support in the `add_theme_support( 'gutenberg' )` format. As of v2.7.0 I switched to the following to keep up with documentation and return the editor color palette feature:

```
		add_theme_support( 'editor-color-palette',
			'#1D2731',
			'#0B3C5D',
			'#328CC1',
			'#D6BB53',
			'#808182',
			'#EF5656'
		);
```

As of v2.8.0, the deprecated notice of this format displays in the console, informing me to use the following format, which is provided in the documentation:
```
		add_theme_support( 'editor-color-palette',
			array(
				'name' => 'Ivory Black',
				'color' => '#1D2731',
			),
			array(
				'name' => 'Prussian Blue',
				'color' => '#0B3C5D',
			),
			array(
				'name' => 'Sky Blue',
				'color' => '#328CC1',
			),
			array(
				'name' => 'Gold Leaf',
				'color' => '#D6BB53',
			),
			array(
				'name' => 'Carbon Grey',
				'color' => '#808182',
			),
			array(
				'name' => 'Watermelon Red',
				'color' => '#EF5656',
			)
		);
```

The issue that arises is that when I switch to the newer formatting I now get the color names as hover tooltips, and the text color in blocks changes. The background color stays transparent however, both in the editor and on the frontend of the site.

The following screenshot is using the original simple array format for defining palette colors:

![editor with simple HEX array](https://user-images.githubusercontent.com/1971070/39627079-85824c6e-4f72-11e8-941f-ee77cfa99937.png)

This screenshot shows the editor with a background and text color selected from the palette with the new nested array theme support format:

![editor with nested name/color array](https://user-images.githubusercontent.com/1971070/39627080-8592fca8-4f72-11e8-9bb8-512d61205d19.png)

This is on a staging site running trunk and v2.8.0 of Gutenberg

**Comment by robertdevore** [comment]
Can it be due to CSS classes needing to be added for your newly created color options?

[link](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#block-color-palettes)

**Comment by richtabor** [comment]
Yea, you need to add the custom color classes to your theme's stylesheet and within Gutenberg. 

I recently published [a detailed guide](https://richtabor.com/gutenberg-color-palettes/) covering how to add support for custom colors and color classes in WordPress themes. 👍
