### ISSUE TITLE
Vertical Tab Focus Auto-select Movement is disorienting

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#65865]
### Description

The animated background is neat when used with an Enter Keypress or a click, but when selection happens on arrow keypress, it is visually disorienting. It feels laggy and busy.

If the tabs auto-select the category and arrow keys are used, I think we should disable the animation.

### Step-by-step reproduction instructions

- Go to the Preferences Pane
- Go to the tabs
- Use the arrow keys to move between the tabs
- Animated gray background moves along with each arrow key, making it look delayed and overly busy.

### Screenshots, screen recording, code snippet

Video of https://github.com/WordPress/gutenberg/pull/65864 using fixed focus ring:

https://github.com/user-attachments/assets/80622a1a-3a2b-438e-b101-ba8bb5d9df73

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by jeryj** [comment]
@DaniGuardiola @ciampo - What do you think?

**Comment by DaniGuardiola** [comment]
The animation already respects the "reduced motion" setting, I wonder if that'd be enough. I do agree with `selectOnMove` it could potentially be a bit too much even for those that do not normally want to reduce motion, though I think it'd be a bit tricky to implement.

@WordPress/gutenberg-design thoughts?

**Comment by jasmussen** [comment]
If we can't/won't animate the focus-ring, would it be an option to use focus-visible to _omit the animation if you're keyboarding_? A bit of the inverse, but it's a first question to ponder.

**Comment by DaniGuardiola** [comment]
Here's what I did: https://github.com/WordPress/gutenberg/pull/65387#issuecomment-2393539515

Let me know what you think.

**Comment by ciampo** [comment]
I like it, and I think it aligns with @jasmussen 's preferred option.

@jeryj , what do you think?

**Comment by jeryj** [comment]
That's much better! I hadn't considered that option. I tested it with keyboard in the preferences pane and it feels really smooth now. Thank you for addressing it! I would consider this fixed when https://github.com/WordPress/gutenberg/pull/65387 lands.
