### ISSUE TITLE
Inset Blue Focus Ring on Vertical Tabs

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#65863]
### Description

The vertical tabs have a regression in their focus styles where it is inset from the highlighted indicator.

### Step-by-step reproduction instructions

- Go to the Preferences Pane
- Go to the tabs
- Use the arrow keys to move between the tabs
- Blue focus ring is inset from the gray indicator

### Screenshots, screen recording, code snippet

Patterns Category Tabs
![Inserter pattern tab with inset focus ring](https://github.com/user-attachments/assets/6f99988a-dcc8-42a5-8859-b52068bfb99d)

Preferences Tabs
![Image](https://github.com/user-attachments/assets/07f6b246-04e9-45e1-8482-1dc985af2eaa)

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by jeryj** [comment]
@ciampo @DaniGuardiola @t-hamano - Pinging because it looks like y'all have been working hard on the animation improvement from https://github.com/WordPress/gutenberg/pull/64926 :)

**Comment by DaniGuardiola** [comment]
Those screenshots are from an older version of Tabs. If you try the latest trunk you'll see the changes that I think fit what you're after in this issue, let me know :)

**Comment by DaniGuardiola** [comment]
Ah, wait, I think the PR that was supposed to take care of this failed to merge due to test errors. Let me take a look. In any case, the associated PR should be closed, though appreciate the effort!

**Comment by jeryj** [comment]
I tested out https://github.com/WordPress/gutenberg/pull/65387 and it looks like it fixes this well. Thanks!
