### ISSUE TITLE
Update the speak messages when switching editor modes

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#65873]
### Description

https://github.com/WordPress/gutenberg/pull/65204 removes 'select' mode (also called 'navigation' mode). Following changes renamed the editor modes to 'Write' and 'Design'.

However, the speak message for screen reader users still refer to 'edit' and 'navigation' and still mention the Enter and Escape key to switch modes, which are no longer funcitonal.

These messages must be updated and simplified.

Cc @WordPress/gutenberg-core 

https://github.com/WordPress/gutenberg/blob/75c2147b96086d4d502b652a4a49bdc372bde33f/packages/block-editor/src/store/actions.js#L1713-L1724

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by youknowriad** [comment]
I removed this from 5.7 tasks because AFAIK, this mode change is not landing in 6.7

**Comment by afercia** [comment]
Oh I see https://github.com/WordPress/gutenberg/pull/65204 is in the 19.4 and WordPress will include the plugin up to 19.3? Is that correct?

**Comment by youknowriad** [comment]
Yes, that's correct.

**Comment by PARTHVATALIYA** [comment]
I suggest the following updates to the screen reader messages to reflect the new mode names and provide accurate instructions for users. Here's the updated message logic:

```
if ( mode === 'navigation' ) {
        speak(
		__(
			'You are currently in Design mode. Use the Tab key and Arrow keys to navigate blocks.'
		)
	); 
} else if ( mode === 'edit' ) { 
	speak( 
		__( 
			'You are currently in Write mode. Navigate within the text as you normally would.'
		)
	); 
}
```

**Comment by afercia** [comment]
@PARTHVATALIYA thanks for looking into this. It's worth noting that https://github.com/WordPress/gutenberg/pull/65204 also removed the ability to navigat ethe blocks with the Tab key. as such, while an alternative navigation mechanism ie being considered in https://github.com/WordPress/gutenberg/issues/65603, I'd think it would be best to not mention the keyboard interaction at all and simplify the messages.
- You are currently in Design mode
- You are currently in Write mode
