### ISSUE TITLE
Add Border, Radius, and Scaling Options to Media & Text Block

### ISSUE THREAD

**Issue by Hari-Bonda** [WordPress/gutenberg#65870]
## What problem does this address?
Currently, the media and text block does not support adding borders or setting a radius, which limits design flexibility when trying to achieve a modern, softer look. Additionally, there is no option to scale the media and text block, making it difficult to adjust the size as needed. I would like to make the block smaller, but there doesn't seem to be an option for this. 

## What is your proposed solution?
I propose adding an option to the media and text block that allows users to set a border and border radius, enabling round edges for a more customizable design. Additionally, a scaling option should be introduced to allow users to easily adjust the block size. If there is already a way to scale the block, please guide me towards it.

![Image](https://github.com/user-attachments/assets/61ff72b6-02bf-4863-9925-8348a97f706a)

**Comment by vk17-starlord** [comment]
@colorful-tones can i take this issue

**Comment by colorful-tones** [comment]
> @colorful-tones can i take this issue

@vk17-starlord - you would not need permission to tackle this issue. Anyone can submit a pull request to address items in the Gutenberg project.

However, before submitting a pull request, I would advise you to do our due diligence on the following:

- Searching the Gutenberg repo for similar open issues and seeing if similar requests are related to "Media & Text block," "border-radius," or "scaling." This would allow us to assign weight to whether the requested features are relevant.
- If you want to proceed with opening a pull request, I suggest opening separate pull requests to address individual items: border radius, scaling, etc. Keep the code changes small for code reviews and feedback.

Thanks!

**Comment by vk17-starlord** [comment]
ok @vk17-starlord will raise PR

**Comment by vk17-starlord** [comment]
@colorful-tones  - https://github.com/WordPress/gutenberg/issues/64750. i guess this issues are similar

**Comment by colorful-tones** [comment]
> https://github.com/WordPress/gutenberg/issues/64750. i guess this issues are similar

Yes, that issue is similar. The only differentiating piece I see is that  #65870 asks for "scaling options". I'm not certain how that would look, but perhaps we could re-scope this issue @Hari-Bonda to clarify the scaling enhancements only and then allow #64750 to cover the rest, please?

**Comment by vk17-starlord** [comment]
@colorful-tones i can work on this issue if you define a scope for this issue .

**Comment by Hari-Bonda** [comment]
Update: I was trying to create two feature cards using the Media & Text block, but they weren't fitting properly—possibly due to the image size. After discussing the issue with someone in the Gutenberg community, they suggested using the Cover block approach to achieve this layout.

By 'scaling,' I mean there should be an option to reduce the size of the entire media box, including the image

https://goblocks.rgproject.id/patterns/card-1/?fbclid=IwZXh0bgNhZW0CMTAAAR2le24p8ffeBr_cKCj8o9Sn1mwZfIY_x-hlibAdteZ11jSEKuGNN478Yhc_aem_AOJbHB6FxvqDvwlV-P7rsA

![Image](https://github.com/user-attachments/assets/13d86e85-c38a-4679-8ffb-9f61b6814dbd)

**Comment by colorful-tones** [comment]
> they suggested using the Cover block approach to achieve this layout.

Yes, the Cover block is more suitable for this.

Since #64750 already exists to cover the border and shadow features. I believe we're good to close this issue out.
