### ISSUE TITLE
Image Block: Add "make featured image" option

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#65889]
## What problem does this address?
Having uploaded an image, if I want to set that image to be the featured image, it's qute a convoluted process.

## What is your proposed solution?
Let's add an option to the image block to set the current image to be the featured image for the post.

**Comment by paaljoachim** [comment]
I have two customers asking me why they have to add a featured image in the sidebar when they have already added an image to the content area. Having a simple way to select image added to content as featured would be nice. Clicking the image kind like starring it having it automatically be added to the featured image box would be helpful.

**Comment by paaljoachim** [comment]
PR has been added here that can use some design feedback.
https://github.com/WordPress/gutenberg/pull/65896
