### ISSUE TITLE
Build Tools: Parallel option for Docker Compose is deprecated

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#6588]
Running `./bin/install-docker.sh` results in a deprecation warning:

```
WARNING: --parallel option is deprecated and will be removed in future versions.
```

This has been made as the default behavior:

>docker-compose pull is now performed in parallel by default. You can opt out using the `--no-parallel` flag. The `--parallel` flag is now deprecated and will be removed in a future version.

https://github.com/docker/compose/blob/master/CHANGELOG.md#1210-2018-04-10

It should be removed from this script.

**Comment by danielbachhuber** [comment]
🔨
