### ISSUE TITLE
Figure out flows to start testing the front-end renders blocks as expected

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#659]
It'd be good to have some form of automated flow for this. Alternative, maybe another view next to "Visual / Text" that is enabled in development that renders the post markup as if it was the front end (quick preview).

**Comment by jasmussen** [comment]
Would a good start be to simply hook up the Preview button and make it open in a new tab?

**Comment by youknowriad** [comment]
Is the current "Publish" button sufficient to close this?

**Comment by mtias** [comment]
I was hoping to have a quicker mode to test without opening front end, so let's leave open put consider low priority.

**Comment by westonruter** [comment]
I want to call this out as being an area for collaboration with Customizer, namely in applying post data and post meta to the frontend for previewing.

**Comment by jasmussen** [comment]
Clearing milestone due to the low priority.
