### ISSUE TITLE
Since Gutenberg v19.3, `allowedControls` in `core/query` block variation are ignored in Site Editor's singular template editor and post editor

### ISSUE THREAD

**Issue by daviedR** [WordPress/gutenberg#65902]
### Description

Referring to the [Extending the Query Loop Block](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/extending-the-query-loop-block/) documentation, we can use the `allowedControls` property in the `core/query` block variation definition to include only some of the controls in the editor.

For example, if a block variation defines: `allowedControls: []`, the block variation will not display any controls.

However, since Gutenberg v19.3, I have found that some controls are always displayed even if they are not defined in the `allowedControls` array when in the Site Editor's singular template editor and post editor. This issue doesn't occur in the Site Editor's index template editor.

Some of the affected controls are: `postType`, `order`, and `sticky`.

I tried to roll back to previous Gutenberg versions and discovered this issue doesn't happen in v19.2.

Changes in v19.3:
https://github.com/WordPress/gutenberg/blob/v19.3.0/packages/block-library/src/query/edit/inspector-controls/index.js#L125

Compared to v19.2:
https://github.com/WordPress/gutenberg/blob/v19.2.0/packages/block-library/src/query/edit/inspector-controls/index.js#L109

There's the additional logic of `! isTemplate` that caused the issue.

### Step-by-step reproduction instructions

Create a new block variation using this snippet:

```
registerBlockVariation(
	'core/query',
	{
		name: 'testing-allowed-controls',
		title: __( 'Testing Allowed Controls' ),
		category: 'theme',
		keywords: [],
		scope: [ 'inserter' ],
		attributes: {
			namespace: 'testing-allowed-controls',
		},
		allowedControls: [],
		innerBlocks: [],
		isActive: [ 'namespace' ],
	}
);
```

Go to 3 block editors:

- Site Editor > Templates > Index
- Site Editor > Templates > Single Posts
- Posts > Add New, or edit an existing post (e.g. "Sample Page")

Add the `Testing Allowed Controls` query block variation into the block editor content via the inserter. Choose any inner blocks template.

Check the available controls in the block options panel (right sidebar).

### Screenshots, screen recording, code snippet

Using the snippet above, these are 3 different screenshots:

| Site Editor > Templates > Index | Site Editor > Templates > Single Posts | Post Editor (e.g. Sample Page)  |
| ------------------------------- | -------------------------------------- | ------------------------------- |
| ![Image](https://github.com/user-attachments/assets/005cfab2-7af8-4a09-af28-00cef418dc2b) | ![Image](https://github.com/user-attachments/assets/9f171f59-ab5c-4192-baa0-35d17fd7e357) | ![Image](https://github.com/user-attachments/assets/f71fe61f-9a59-43b8-b935-5a7582873116) |

### Environment info

WordPress 6.7 beta1

OR

WordPress 6.6.2
Gutenberg 19.3

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by ndiego** [comment]
@daviedR does the previous functionality work in WordPress 6.6.2 without Gutenberg active?

**Comment by daviedR** [comment]
> @daviedR does the previous functionality work in WordPress 6.6.2 without Gutenberg active?

Yes, it works in WP 6.6.2 without Gutenberg plugin.

**Comment by t-hamano** [comment]
@mikachan @fabiankaegy 

I think #65067 is related, but do you know if what's reported here is a bug or expected behavior? If it is expected, [the documentation](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/extending-the-query-loop-block/#disabling-irrelevant-or-unsupported-query-controls) may need to be updated.

**Comment by fabiankaegy** [comment]
@t-hamano, from my perspective, this is definitely not intended behavior. #65067 intended to update the default way the control display. But it should 100% still respect the `allowedControls` option.

I do think this is a critical bug in 6.7 that needs to be resolved before the release.

**Comment by mikachan** [comment]
Thanks for the ping, @t-hamano. I agree, this is not the intended behaviour. I'll look into this as soon as possible.

**Comment by ndiego** [comment]
> Yes, it works in WP 6.6.2 without Gutenberg plugin.

Thanks for the feedback everyone, I am going to list this as a regression.
