### ISSUE TITLE
Zoom out: Vertical toolbar overlaps with container

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#65909]
### Description

Block themes developed before `root padding` support was added has a workaround to set padding to `.is-root-container` in `style.css`
In such themes, vertical toolbar overlaps with/falls inside the container.

<image width="500" src="https://github.com/user-attachments/assets/8ec5751c-d246-46b9-8921-7cdbf7ff7432" />

Twenty twenty two (style.css):

```
/*
 * Alignment styles.
 * These rules are temporary, and should not be relied on or
 * modified too heavily by themes or plugins that build on
 * Twenty Twenty-Two. These are meant to be a precursor to
 * a global solution provided by the Block Editor.
 *
 * Relevant issues:
 * https://github.com/WordPress/gutenberg/issues/35607
 * https://github.com/WordPress/gutenberg/issues/35884
 */

.wp-site-blocks,
body > .is-root-container,
.edit-post-visual-editor__post-title-wrapper,
.wp-block-group.alignfull,
.wp-block-group.has-background,
.wp-block-cover.alignfull,
.is-root-container .wp-block[data-align="full"] > .wp-block-group,
.is-root-container .wp-block[data-align="full"] > .wp-block-cover {
	padding-left: var(--wp--custom--spacing--outer);
	padding-right: var(--wp--custom--spacing--outer);
}
```

Remote theme: (https://wordpress.org/themes/remote/)

<image width="500" src="https://github.com/user-attachments/assets/04c64c3b-ebb1-4443-800d-be5562086e9c" />

### Step-by-step reproduction instructions

1. Activate twenty-twenty-two theme
2. try inserting following patterns

<image width="500" src="https://github.com/user-attachments/assets/87de00e2-bbd8-4a46-ba89-734d26345f26" />

3. Observe that the vertical toolbar falls inside the container.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by ndiego** [comment]
I can confirm. Adding this to the 6.7 project board.

**Comment by annezazu** [comment]
Closing this out as it overlaps with a current known issue: https://github.com/WordPress/gutenberg/issues/65188
