### ISSUE TITLE
6.7: Writing mode / text orientation is not applied to the Site title block on the front

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#65910]
### Description

In WordPress 6.7-beta1-59184, the inline CSS for the typography option for vertical text is not applied on the front, only in the editors.

-The theme (Twenty Twenty-Five) has `"writingMode": true,` in theme.json > settings > typography.
- Other blocks like heading work.

If I activate Gutenberg trunk, the option works correctly.
Since Twenty Twenty-Five relies on this feature to work for one of the alternative headers, can we rest assured that this will work in 6.7 without Gutenberg?

### Step-by-step reproduction instructions

First, make sure the theme has support for `writingMode`.
Next, insert a site title block.
In the block settings sidebar, open the Typography panel, activate "Orientation" and select vertical. Save.
View the block on the front.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by ndiego** [comment]
I can confirm. 

| Editor | Front end |
|-|-|
|![Image](https://github.com/user-attachments/assets/76752782-9799-44d2-a078-f676180c332c)|![Image](https://github.com/user-attachments/assets/6660f19b-5aa7-4986-96b0-ce64b48b1fbf)|

**Comment by getdave** [comment]
Thanks for flagging this.

> can we rest assured that this will work in 6.7 without Gutenberg?

I don't think we should no. We need to track down the missing PR and make sure it's included in 6.7. 

I see references to [`writingMode` in 2023](https://github.com/WordPress/gutenberg/pull/54351) so I'm confused as to how this isn't already in Core.

I was away for the 6.6 cycle so perhaps @ellatrix might know (also cc @MaggieCabrera @mikachan).

**Comment by ndiego** [comment]
@getdave I just confirmed this issue happens with the Site Tagline block as well. Perhaps it's due to the fact that both are dynamic blocks?

**Comment by t-hamano** [comment]
It looks like the style engine doesn't support `wirtingMode` in WP 6.7 Beta1.

The following code exists in Gutenberg:

https://github.com/WordPress/gutenberg/blob/4c4556cfe394b9173d67d69f243684dd7bc6fec8/packages/style-engine/class-wp-style-engine.php#L300-L305

However, this code doesn't exist in WP 6.7 Beta1:

https://github.com/WordPress/WordPress/blob/42db3985961d284426e90c89258ffc78dc4e9eb8/wp-includes/style-engine/class-wp-style-engine.php#L307

 If you add the Gutenberg-only code to the core as well, it works correctly on the frontend.

Maybe a PHP backport to core was missed during one of the major releases.

**Comment by ndiego** [comment]
> Maybe a PHP backport to core was missed during one of the major releases.

Ah perhaps. cc @kevin940726 @andrewserong

**Comment by t-hamano** [comment]
My understanding is that any changes to the style engine need to be manually backported to the core.

However, the following PR doesn't seem to include any changes to the style engine:

- https://github.com/WordPress/wordpress-develop/pull/5210/

**Comment by andrewserong** [comment]
> My understanding is that any changes to the style engine need to be manually backported to the core.
> However, the following PR doesn't seem to include any changes to the style engine:

That's my understanding, too. Looks like https://github.com/WordPress/wordpress-develop/pull/5210 was intended to backport https://github.com/WordPress/gutenberg/pull/50822, however missed the changes to `class-wp-style-engine.php`. The writing mode support was only added to the Site Title block fairly recently (https://github.com/WordPress/gutenberg/pull/62727), so I imagine we just haven't been in a situation where the long-standing bug was made visible in core.

I'm happy to put up a core PR to add in the missing lines to the style engine, if no-one beats me to it!

**Comment by t-hamano** [comment]
Note: In WordPress 6.6, `writingMode` is available for the following four blocks: 

- Paragraph
- Heading
- Footnotes
- Post Navigation Link (Next Post, Previous Post)

The Paragraph and Heading blocks have inline styles embedded in HTML, so they displayed correctly on the frontend even if the style engine did not support `writingMode`.

On the other hand, the Footnotes and Post Navigation Link blocks are dynamic blocks, so the style engine must support them to render them correctly on the frontend.

Perhaps this issue was overlooked because so few people use `writingMode` in dynamic blocks.

**Comment by andrewserong** [comment]
Thanks for looking that up, Aki!

> Perhaps this issue was overlooked because so few people use writingMode in dynamic blocks.

Yes, that sounds most likely to me, it can be really easy to miss testing these things in core, especially when we're so regularly working on the features in Gutenberg.

I've opened up a core PR to resolve this over in https://github.com/WordPress/wordpress-develop/pull/7534, and here's the trac ticket for it, too: https://core.trac.wordpress.org/ticket/62189

**Comment by andrewserong** [comment]
The core PR (https://github.com/WordPress/wordpress-develop/pull/7534) has been committed, so the fix will be in WP 6.7 Beta 3. Thanks for the troubleshooting and reviews, everyone!

**Comment by getdave** [comment]
Thank you for wrangling this folks 👏
