### ISSUE TITLE
Zoom out: when toggled on, it persists across editors but isn't visible

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#65928]
Using WordPress nightly, I noticed that if you enable zoom out and move between editing a template to a page or vice versa, zoom out shows as toggled on but the canvas isn't zoomed out:

https://github.com/user-attachments/assets/0238e583-2183-4d39-8416-82dd4f921cf1

For now, to simplify a solution, I'd just make zoom out being on not persist between editors unless it's a simple fix to ensure it does persist between.

**Comment by getdave** [comment]
Thanks for raising. I'm going to close this out as a duplicate of  of https://github.com/WordPress/gutenberg/issues/65783.

The actual bug in _both_ Issues is the same. 

The _state_ is persisted but the actual scaling doesn't persist at an implementatino level on the `iframe`.
