### ISSUE TITLE
"Add block" button missing under the Paragraph block

### ISSUE THREAD

**Issue by stevejburge** [WordPress/gutenberg#6592]
Here are the image, audio and list blocks:
![audio](https://user-images.githubusercontent.com/3868028/39634620-46ad1d0e-4f89-11e8-89b7-376c24810ad5.png)
![image](https://user-images.githubusercontent.com/3868028/39634622-481cfcea-4f89-11e8-8a6d-db38cc1b1bb3.png)
![list](https://user-images.githubusercontent.com/3868028/39634625-48815d7a-4f89-11e8-8a11-f2c0df4209fa.png)

But in contrast, that button is missing from under the Paragraph block. It was definitely unexpected. I spent a few minutes trying to mouseover the area, expecting it to be there:

![paragraph](https://user-images.githubusercontent.com/3868028/39634652-5d56c096-4f89-11e8-946a-5558bcb1569f.png)

**Comment by HippDesign** [comment]
My suggestion would be: If the last block is filled out and has no add-button, show one more add-button after the last block. If the last block is empty, just show the add-button at the block itself.

I tried to visualize this: 
![add-button-suggestion](https://user-images.githubusercontent.com/12687777/39662512-a4835284-5062-11e8-803b-837c3ec937f0.gif)

**Comment by danielbachhuber** [comment]
Filed as `Needs Design Feedback` because I'm unsure as to whether this is a deliberate decision or not.

**Comment by karmatosed** [comment]
Having it not show prominently for the paragraph blocks helps with the writing flow. The 'add' block to access the library appears on hover and you can still use the slash command also. The majority of uses of the paragraph block will see more than one used, which is where this helps for the flow.

In this case let's keep it as it is as a design decision. We can always review at a later date.
