### ISSUE TITLE
Double Scrollbar Appears Under Patterns Tab in Block Editor

### ISSUE THREAD

**Issue by dhruvang21** [WordPress/gutenberg#65940]
### Description

When using the Patterns tab in the WordPress Gutenberg editor, a double scrollbar appears on the left sidebar. This is visible when expanding the "My Patterns" section, making the user interface cumbersome and confusing to navigate. The issue becomes more evident when there is content that requires scrolling, as the additional scrollbar does not provide any functional advantage and causes visual clutter.
Additionally, this issue occurs specifically in the tablet responsive view, further impacting usability on devices with smaller screens.

### Step-by-step reproduction instructions

1. Open the WordPress Block Editor.
2. Navigate to the Patterns tab in the left sidebar.
3. Expand "My Patterns" or other pattern categories that contain multiple items.
4. Switch to tablet view and observe that two scrollbars appear in the left sidebar.
### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/056753b2-5ef9-44c4-91ae-9341b66bd423)
![Image](https://github.com/user-attachments/assets/60ea7bd1-294c-43a6-bd69-b169df675ddd)

### Environment info

This seems to affect the latest version of Gutenberg (version 19.3+) and WordPress 6.7, as tested in a local environment.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by t-hamano** [comment]
Thanks for the report.

This issue is the same as #65837 and has been fixed in #65387, so I would like to close it.

#65387 is part of Gutenberg 19.5, so I would appreciate it if you could test it again once Gutenberg 19.5 is released.
