### ISSUE TITLE
Site editor: Appearance section is not mobile responsive

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#65955]
### Description

When using Chrome on mobile, the Appearance section isn't fully visible on the screen.

### Step-by-step reproduction instructions

1. Go to Site Editor
2. Pages
3. Click on the cog wheel
4. Check the results

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/3ca00690-8b9b-4d6e-ad13-931c5a40d36c)

## WordPress information
- WordPress version: 6.6.2
- Gutenberg version: 19.3
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes
- 
## Device information
- Device: iPhone 13 Pro
- Operating system: 18.0
- Chrome

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by megane9988** [comment]
- WordPress version: 6.6.2
- Gutenberg version: 19.5.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes
    - I used Twenty Twenty-Four

# Device information
- Device: iPhone 14
- Operating system: 18.0.1
- Chrome

the Appearance section was fully visible on the screen.

![Image](https://github.com/user-attachments/assets/72a7830b-abd8-4893-9433-6535080ec34c)

**Comment by ramonjd** [comment]
I think the popover should be fullscreen on mobile viewports. This would ensure full accessibility on narrower viewports. It's also easier to mash the buttons with your thumb.

- https://github.com/WordPress/gutenberg/pull/67715
