### ISSUE TITLE
Paragraph appender: layout shift when Content block fills the container

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#65969]
When the Content block is set to "Inner blocks use content width", the Paragraph appender is replaced with a Paragraph block without a layout shift. When the Content blokc is set to _not_ use content width, there's a big visible layout shift when the Paragraph block replaces the appender:

![Image](https://github.com/user-attachments/assets/51e07be8-19e4-4c75-880d-8ab90a9c7e21)

Steps shown in the GIF:

* Site editor, set Content block to "Inner blocks use content width", save. 
* Go to post editor, click the Paragraph block, notice no layout shift.
* Site editor, unset Content block from "Inner blocks use content width", save.
* Go to post editor, click the Paragraph block, notice a big layout shift.

This shift happens because the paragraph inside the appender has top/bottom margins, and this margin is unset by the content width rules, these:

![Image](https://github.com/user-attachments/assets/acbc5309-96e1-434d-a458-1f4f06cfbd71)

**Comment by Vrishabhsk** [comment]
Hi @jasmussen 👋 
- I have raised a PR that fixes this issue : https://github.com/WordPress/gutenberg/pull/66061

Let me know your thoughts on it. Thanks
