### ISSUE TITLE
WP 4.5.6 beta - GDPR Privacy Notes don't play nice with Gutenberg

### ISSUE THREAD

**Issue by Ipstenu** [WordPress/gutenberg#6596]
## Issue Overview

Crossposting of https://core.trac.wordpress.org/ticket/43965

After adding a page, I get the normal message:

> The suggested privacy policy text has changed. Edit the privacy policy.

Click on the edit link and, if you have Gutenberg, you don't get the policy information. In addition, even if you make changes, the alert doesn't go away.

Nor does it go away if I click the dismiss button, so I have to go to the Classic Editor to make the change.

## Steps to Reproduce (for bugs)
1. Upgrade to 4.5.6 Beta
2. With Gutenberg active, make a Privacy Page
3. Go to the Privacy settings page and pick this page
4. Navigate to other pages
5. Click 'edit' to change the content

## Expected Behavior

1. The privacy notes should show up on the gutenpage
2. The alert should go away

## Current Behavior

1. no notes
2. alert stays

**Comment by pento** [comment]
Closing, as it was fixed in core.
