### ISSUE TITLE
Ship the new Figma library so designers can use the improved components in their Figma designs.

### ISSUE THREAD

**Issue by cli-automattic** [WordPress/gutenberg#65978]
- [x] Decide on how we sync Figma libraries across organisations
- [x] Remove any big experimental features (dark mode).
- [x] Remove any WIP components.
- [x] Add a ‘How to contribute’ section.
- [x] Finish/Polish the foundation pages.
- [x] Ensure component props match code.
- [x] Ensure complete component coverage (we have a few gaps per the audit).
- [x] Add editor patterns (Header, ToolsPanel, ListView, Inspector, Inserter)
- [x] Add all component descriptions and links.
- [x] Communicate and ship to designers

**Comment by jameskoster** [comment]
I've begun moving experimental / WIP components out of the library and into a new Figma file: https://www.figma.com/design/8quMtHZzv7tC5UoVU4xBCx/Experimental-components?node-id=2-844&t=JrnV31Gv8tT8ICJA-1

**Comment by jameskoster** [comment]
> Decide on how we sync Figma libraries across organisations

Sharing the proposed process to gather feedback:

1. The source/working file for the library continues to live in the WP community Figma organisation, but is no longer published as a library.
2. With regular cadence (potentially aligned with Gutenberg releases) maintainers of the library (members of the Design team) publish the working file to the [Figma Community](https://www.figma.com/community) and announce in the community #Design Slack channel.
3. Each new version is duplicated to the _Libraries project in the WP community Figma, and published. This is also announced in Slack. The new version should be included as a default for new files.
4. Designers working in the WP community Figma can swap to the latest version using [Figma Library Swapping](https://help.figma.com/hc/en-us/articles/4404856784663-Swap-style-and-component-libraries).

Steps three and four can be replicated by any third party so they can use the library in their own Figma organisations.

**Comment by jasmussen** [comment]
I quite like that suggested process, as it implicitly includes _versioning_ in the library. The goal of the library, ultimately, is to build out mockups. Those mockups serve a purpose here on GitHub. So while you can choose to update an older mockup to a newer library, with a single published version as we'e had in the past, things would often break in that mockup, with no clear benefit. Whereas with a versioning system, where you deliberately choose to target a newer version, you choose to do that deliberately because the mockup is still being worked on. Not just because you press the "Update components" button in the corner of and old file, just to make the snackbar go away.

**Comment by jameskoster** [comment]
Here's a list of missing components and patterns I'd like to prioritise adding to the [Library in Figma](https://www.figma.com/design/804HN2REV2iap2ytjRQ055/Core-System-Library?node-id=551-29619&t=3niNLlh7fY68Wq1j-1) before shipping the 'v1'.

- [x] DropdownMenu V2
- [x] Modal
- [x] ToggleGroupControl
- [x] Notice
- [x] Popover
- [x] ItemGroup
- [x] Editor Pattern: Header
- [x] Editor Pattern: ListView
- [x] Editor Pattern: Inspector
- [x] Editor Pattern: Inserter

The are others, listed below, but these feel less important.

- FormTokenField
- TimePicker
- FormFileUpload
- BorderBoxControl
- DropZone
- SnackbarList
- PaletteEdit
- BorderControl
- CustomGradientPicker
- FocalPointPicker
- FontSizePicker
- GradientPicker
- ResizableBox

Obviously these lists can change, and I'd welcome any thoughts.

**Comment by jameskoster** [comment]
This is complete: https://www.figma.com/community/file/1436359662053949167/wordpress-design-system 🎊
