### ISSUE TITLE
Convert to shared block - Cancel - Admin Message

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#6597]
Think it is a bug.

- Start procedure to convert any block to shared.
- Cancel procedure, do not proceed with converting.
- Admin message "Block created" appears at the top.

What is created ?

**Comment by karmatosed** [comment]
It looks like it's create a block without a title. See here:

![2018-05-10 at 20 09](https://user-images.githubusercontent.com/253067/39888870-0cf51ca6-548e-11e8-8a05-629ac4e00760.png)

I totally agree it should be not doing that. You cancelled therefore it should just not make a block. Thanks for reporting this.

**Comment by noisysocks** [comment]
Yes, it's not been worked on. I'll remove myself as the assignee in case it encourages someone else to pick this up. Otherwise, it is on my list and I will _eventually_ get to it 🙂

**Comment by karmatosed** [comment]
@ZebulanStanphill I think we can probably put this in before, let's milestone for next release and take from there.

**Comment by youknowriad** [comment]
Closing as there's no "cancel" button anymore.
