### ISSUE TITLE
Browsing styles should not zoom out with device preview

### ISSUE THREAD

**Issue by juanfra** [WordPress/gutenberg#65991]
### Description

When I am in the site editor, I choose to have the mobile view and browse styles then the zoom out is triggered. As a result the editor becomes really small and difficult to use. 

I believe in other places we are avoiding this scenario where the mobile view is zoomed out, and it defaults to desktop view.

### Step-by-step reproduction instructions

1. Go to the site editor
2. Select the mobile view.
3. Open the "Styles" section.
4. Click on "Browse styles"
5. See how the editor becomes narrow and challenging to use.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/e1686682-46aa-4b21-8628-363b06c09128

### Environment info

- WordPress 6.7 beta-2. 
- Gutenberg trunk
- Twenty Twenty-Five trunk

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by richtabor** [comment]
Related https://github.com/WordPress/gutenberg/issues/65080
