### ISSUE TITLE
Button: Transition doesn't work for secondary variation

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#66007]
### Description

When the `Button` component is focused, a transition is expected to be applied to the `box-shadow` via the following CSS:

https://github.com/WordPress/gutenberg/blob/7ea28adb62b8333714ec916ed6b6688181731a26/packages/components/src/button/style.scss#L19

This transition works for the `primary`/`tertiary` variations but not the `secondary` variation.

My guess is that transitions won't work between insets and outsets. For example, if I remove the `inset` from [this line](https://github.com/WordPress/gutenberg/blob/7ea28adb62b8333714ec916ed6b6688181731a26/packages/components/src/button/style.scss#L136), the transition will work on the `secondary` variation.

However, simply removing the `inset` may not be an ideal solution, since removing the `inset` increases the default border size by 1px.

### Step-by-step reproduction instructions

- Open https://wordpress.github.io/gutenberg/?path=/story/components-button--secondary
- Focus on the button

## Actual

https://github.com/user-attachments/assets/929016ea-24fc-4177-a7c2-995f38ba84af

## Expected

https://github.com/user-attachments/assets/fad791d2-033c-4f39-8e5e-b9f80422521b

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by Vrishabhsk** [comment]
Hi @t-hamano 👋 
- Your guess was right, we can't transition from an `inset box-shadow` to a `normal box-shadow` ([`Ref-1`](https://stackoverflow.com/a/25410897) & [`Ref-2`](https://stackoverflow.com/a/22461987))
- I was able to use the snippets from these as reference and modify our own style. These were the results
   - `Original`

     https://github.com/user-attachments/assets/79b7a629-c921-490e-b57a-828642d7739d 

   - `Slightly Improved using the above-mentioned hack`

      https://github.com/user-attachments/assets/cc9d3a0d-f6e1-4edf-adc4-fe4620ba261d

   - `Hack + Increase delay by 0.1s`

      https://github.com/user-attachments/assets/c2a6ea4f-5dff-4ecf-aad5-d928c045707a 

Let me know your thoughts on this and whether I can raise a PR to fix it. Thanks

**Comment by Vrishabhsk** [comment]
Hi @t-hamano 👋 
- I have raised the PR for the same : https://github.com/WordPress/gutenberg/pull/66045
- I have used the `box-shadow` hack mentioned above with a slight catch.
- The above implementation used `#FFF` and I switched it with `#000` which improved it and looked identical to other `transitions` without needing to increase the delay.

Let me know your thoughts on this. Thanks

**Comment by tyxla** [comment]
Resolved by #66045.
