### ISSUE TITLE
Patterns fail to load after switching from all patterns (page 2) to template parts tab

### ISSUE THREAD

**Issue by dhruvang21** [WordPress/gutenberg#66009]
### Description

When navigating between the "All Patterns" tab (specifically on page 2) and the "Template Parts" tab, the patterns fail to load correctly, and a "No Results" message is displayed. This issue occurs only when switching between the second page of patterns and the template parts tab. The patterns should render properly, but instead, users encounter the "No Results" message until the page is refreshed or navigated again.

This issue was originally posted in WordPress Core Ticket [#62089](https://core.trac.wordpress.org/ticket/62089).

### Step-by-step reproduction instructions

1.  Log into your test site.
2. Go to Appearance > Editor
3. In the Design menu, select Patterns. By default, the template parts have 5 templates showing
4. In the "View options", set the Layout to Grid. 
5. Go into all patterns.
6. Navigate the next page using the pagination at the bottom of the editor.
7. Select the all template parts tab

🐞 Bug occurs. As no patterns display.

Expected Results :-
Step 7: Patterns should render after switching to All template parts tab.
When reproducing a bug:
✅ Step 7: patterns list is shown empty, no patterns are rendered

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/02298849-927f-4897-9a66-51f3b38b6b6a

### Environment info

OS: unbuntu
Web Server: Apache
PHP: 8.1.2
WordPress: 6.7 latest
Browser: Chrome
Theme: Twenty Twenty-Five
Active Plugins: None

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by dhruvang21** [comment]
### Proposed Solution:-

I’ve tracked down the issue and identified that it occurs because the page is not reset to page 1 when switching tabs. This happens due to the condition failure in the file [index.js#L124](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/page-patterns/index.js#L124). When switching tabs between wp_block post type and wp_template_part, neither has a category, so the categoryId defaults to PATTERN_DEFAULT_CATEGORY. As a result, both the previous and current categories are the same, causing the condition to fail.

I’ve attached a diff where I added a condition using the same logic for the post type, which resolves the issue. If this solution seems appropriate, I’d be happy to create a PR.

Let me know your thoughts!

```diff
diff --git a/packages/edit-site/src/components/page-patterns/index.js b/packages/edit-site/src/components/page-patterns/index.js
index be3bb7429c..a75573918b 100644
--- a/packages/edit-site/src/components/page-patterns/index.js
+++ b/packages/edit-site/src/components/page-patterns/index.js
@@ -78,6 +78,7 @@ export default function DataviewsPatterns() {
        const categoryId = categoryIdFromURL || PATTERN_DEFAULT_CATEGORY;
        const [ view, setView ] = useState( DEFAULT_VIEW );
        const previousCategoryId = usePrevious( categoryId );
+       const previouspostType = usePrevious( type );
        const viewSyncStatus = view.filters?.find(
                ( { field } ) => field === 'sync-status'
        )?.value;
@@ -121,10 +122,10 @@ export default function DataviewsPatterns() {
 
        // Reset the page number when the category changes.
        useEffect( () => {
-               if ( previousCategoryId !== categoryId ) {
+               if ( previousCategoryId !== categoryId || previouspostType !== type ) {
                        setView( ( prevView ) => ( { ...prevView, page: 1 } ) );
                }
-       }, [ categoryId, previousCategoryId ] );
+       }, [ categoryId, previousCategoryId, previouspostType, type ] );
        const { data, paginationInfo } = useMemo( () => {
                // Search is managed server-side as well as filters for patterns.
                // However, the author filter in template parts is done client-side.
```

### After Patch:-
https://github.com/user-attachments/assets/a63fe989-0535-4ca1-bc8f-7176ca5863c0

**Comment by talldan** [comment]
@dhruvang21 That solution makes sense to me at a glance, though I'm not completely familiar with the code. A PR would be appreciated if you have the time. Thanks for investigating!
