### ISSUE TITLE
Ship first set of updates to Storybook [RADIUS]

### ISSUE THREAD

**Issue by cli-automattic** [WordPress/gutenberg#66014]
- [x] Investigate what exists today, what needs updating
- [x] Ensure radius is represented as a style/variables
- [ ] Ship / refactor code
- [ ] Define what exists, include some helpful guidelines
- [ ] Ship & communicate
- [ ] User feedback from designers and engineer
- [ ] Document case study to show impact

**Comment by jameskoster** [comment]
I think this one is essentially a duplicate of https://github.com/WordPress/gutenberg/issues/63703. I'll close in favor of 63703 as it contains some additional detail.
