### ISSUE TITLE
No background image alignment options for Cover Image block

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6602]
## Issue Overview
If you use a wide image for the Cover Image block, the image will extend past the right edge of the block, and the image will not be centered. Ideally, you should be able to control at least the horizontal alignment of the image, and preferably also the vertical alignment.

## Steps to Reproduce
1. Insert a Cover Image block.
2. Choose an image with a wide aspect ratio.
3. Notice that the image extends past the right edge of the block and is not centered.

Tested in Firefox Nightly 61.

## Expected Behavior
By default, the image should be vertically and horizontally centered. There should also be options in the block inspector to change the alignment of the image.

## Current Behavior
The default alignment of the image is such that wide images are not horizontally centered, and tall images are not vertically centered.

**Comment by karmatosed** [comment]
This came up a little while ago here: https://github.com/WordPress/gutenberg/issues/5458.

This was decided to move to Customization as a phase two option. As a result lets merge this into that issue and close here. Saying it's to be done in phase two isn't saying it won't, it's actually saying it will but not right now. Thanks for suggesting something that is very much desirable going forward.

**Comment by SuperGeniusZeb** [comment]
@karmatosed The default horizontal alignment for the Cover Image background should still be centered, though, should it not? The current left-aligned default does not really make sense to me.
