### ISSUE TITLE
Translatable strings from `lib/theme.json` are not being extracted for translation

### ISSUE THREAD

**Issue by yuliyan** [WordPress/gutenberg#66027]
### Description

The strings from the `lib/theme.json` are not being extracted for translation, likely due to `wp i18n make-pot` command being [limited to only scanning the `theme.json` file in the root of the plugin/theme or the JSON files in `styles/*.json`](https://github.com/wp-cli/i18n-command/blob/065bb3758fcbff922f1b7a01ab702aab0da79803/src/ThemeJsonExtractor.php#L21-L22).

As a results some of the strings, such as the aspect ratio options, the drop shadow presets, etc., are [not available for translation in the GlotPress project](https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/de/default/?filters%5Bterm%5D=lib%2Ftheme.json&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) and thus the strings appear untranslated in the block editor (see the attached screenshots).

### Step-by-step reproduction instructions

1. Download the plugin locally.
2. Make POT with `wp i18n make-pot .`.
3. Inspect the generated `gutenberg.pot` file to confirm strings from `lib/theme.json` are not being extracted.

### Screenshots, screen recording, code snippet

**Aspect ratio options:**
![Image](https://github.com/user-attachments/assets/251a310f-b118-4a07-b294-def900bdadff)

**Drop shadow presets:**
![Image](https://github.com/user-attachments/assets/3ff405f8-c621-4a41-91d3-e7924bb09a25)

### Environment info

- WordPress 6.6.2
- Gutenberg 19.4.0
- Theme - twentytwentyfour v1.2
- Site language - German

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by d-alleyne** [comment]
Hi @swissspidy, upon reviewing this issue, we discovered that limiting the extractor to only work with the top-level `theme.json` has caused the bug. Could you provide some insight into why this change was implemented in this commit: https://github.com/wp-cli/i18n-command/commit/345eb7a88443d4db63a8d8e7c7aac935fb197392? We are considering loosening this restriction but are concerned about potential side-effects you might be aware of.

**Comment by swissspidy** [comment]
Well, it's simple. `theme.json` are for block themes and must live in the root folder of a block theme. With this in place, the string extraction is much faster as there is no point in scanning every other directory for such a file.

Plugins normally don't include a `theme.json` file. Gutenberg is the exception because the format is developed here.

I'd rather suggest Gutenberg moving the file location, that would be the simpler solution.

**Comment by d-alleyne** [comment]
I did a test by symlinking the `lib/theme.json` to the root directory, and running `wp i18n make-pot .`. This extracted the [Aspect Ratios](https://github.com/WordPress/gutenberg/blob/trunk/lib/theme.json#L195-L231), but not the [Dropdown Shadow presets](https://github.com/WordPress/gutenberg/blob/trunk/lib/theme.json#L235-L261).

**Comment by swissspidy** [comment]
Then someone forgot to add those to lib/theme-i18n.json when this festure was added, which means nobody is able to translate them right now

**Comment by oandregal** [comment]
There're a few things here:

- one issue is related to how strings are extracted for translation in translate.wordpress.org and it's being addressed at https://meta.trac.wordpress.org/ticket/7866
- the other issue is that aspect ratio wasn't declared as a translatable string and this is being fixed at https://github.com/WordPress/gutenberg/pull/66675

**Comment by oandregal** [comment]
The remaining things for this to work well need to happen upstream and are already tracked there, so closing this one. Thanks @yuliyan for reporting!
