### ISSUE TITLE
[2.8] does not assign new URL permalink, except at initial save

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#6603]
## Issue Overview
Gutenberg 2.7 & 2.8 does not assign new URL permalink, except at initial save.

## Steps to Reproduce
1. Create post - use title "Post ABC"
2. Save. Permalink is automatically generated to ...post-abc
3. Edit title to "Post 123". Edit permalink to be empty. 
4. Resave. Permalink should change to ...post-123, but it instead reverts to prior ...post-abc.

**Comment by pento** [comment]
Thank you for the bug report, @GlennMartin1! I can reproduce this behaviour as you describe, and see how it differs from the Classic Editor behaviour, I'll see about getting it fixed up. 🙂
