### ISSUE TITLE
Unable to modify visibility setting on mobile

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#6604]
## Issue Overview
unable to modify visibility or change publish date on mobile (Android)

## Steps to Reproduce (for bugs)
1. Using Android, create a post. 
2. Go to Document settings. 
3. Visibility and Publish date appear to be permalinks, but offer no way to change these settings.

**Comment by karmatosed** [comment]
I am unable to replicate this, could you add a little bit more information like for example what theme you are using? For example, does this happens using a default theme like Twenty Seventeen and no plugins? Also what browser are you using to view this as there are a few options on Android.

**Comment by GlennMartin1** [comment]
Thanks @karmatosed for your reply.

I'm using using:
- Wordpress 4.9.5
- Gutenberg 2.8 (no other plugins)
- Storefront theme 2.3 RC1 or Twenty Seventeen 1.5 (the only two themes I tried)
- Chrome on Android (v. 66.0.3359.158)

Go to edit a post; click the gear to show Document settings. The Visibility link and the Publish link are both there, but have no effect when clicking it.

Problem is on Android (on desktop, it works fine).

**Comment by GlennMartin1** [comment]
Just to clarify:

- Chrome on Android "desktop view" works fine.
- Chrome on Android "mobile view" is where the problem is.

**Comment by GlennMartin1** [comment]
@karmatosed, have you been able to replicate this with the additional info provided?

**Comment by karmatosed** [comment]
I haven't @GlennMartin1 could you maybe provide a screencast or screenshot just to see what you are?

**Comment by GlennMartin1** [comment]
Chrome on Android, in portrait mode - cannot change Visibility or Publish Date. 

You will see it in this GIF: ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30901407/39939000-ce56b6f4-5522-11e8-85e5-ccc529eb7d03.gif)

**Comment by karmatosed** [comment]
Thanks, I am going to mark this as a bug as the screenshot replicates and we can then dig down into why I can't. What Android device are you using?

**Comment by GlennMartin1** [comment]
I'm using a Stylo 2, running Android Nougat (v.7).

**Comment by karmatosed** [comment]
I have to admit I am having trouble replicating this but this could be a size issue. Lets flag for testing and see if someone else can replicate.

**Comment by GlennMartin1** [comment]
It persists through 2.9.1.

**Comment by GlennMartin1** [comment]
This persists in 3.0.

**Comment by iseulde** [comment]
I can reproduce this. See #7257.

**Comment by GlennMartin1** [comment]
This issue persists in 3.1.0.

**Comment by desrosj** [comment]
Encountered this over the weekend. Like @iseulde, I was using iOS, so I have removed `(Android)` from the issue title.

I am using Gutenberg v3.6.2.

**Comment by GlennMartin1** [comment]
With the new datepicker in 4.1, the date now works for me on Android.

Still unable to modify visibility on mobile.

**Comment by designsimply** [comment]
This was re-reported in #11951 and fixed in #11954 and would have been included in 4.5. 

I verified I can no longer see the problem with WordPress 4.9.8 and Gutenberg 4.5.1 using Pixel on Android 9. ([27s](https://cloudup.com/c2uVR-bJ4Aa))
