### ISSUE TITLE
Use the previous "select mode" dark toolbar style for Write mode

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#66054]
Let's try adding an additional affordance to write mode to help you understand what "mode" you're in, writing or design, by leveraging the pre-existing styles for select mode. This way there's a clear visual affordance to indicate the difference in experiences. 

### Visual 

![Image](https://github.com/user-attachments/assets/a2f4d6f5-5b9e-4e6d-b4ef-9a1eb81616d6)

Related #65298.

**Comment by hanneslsm** [comment]
I like the idea. 
Another one would be leveraging bottom bar, that currently only holds the breadcrumps. 
We could add the name of the mode in the bottom bar [like in VIM](https://linuxhandbook.com/vim-modes/). In VSCode it's even officially called [status bar](https://code.visualstudio.com/api/ux-guidelines/status-bar)
