### ISSUE TITLE
Patterns in the inserter re-render on click of blocks in the editor

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#66052]
### Description

Patterns are re-rendered every-time the active block changes in the editor.

![Image](https://github.com/user-attachments/assets/e65a2a93-11b9-4d62-affd-025e9ec01ef0)

### Step-by-step reproduction instructions

* Open editor
* Open pattern menu
* Click on block in the editor and observe patterns getting re-rendered 

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by ndiego** [comment]
This is the same issue reported here: https://github.com/WordPress/gutenberg/issues/65920, but since this one is already being worked on, @madhusudhand, it's up to you which one to close. I am going to add this to the 6.7 project board regardless.

**Comment by ndiego** [comment]
https://github.com/WordPress/gutenberg/issues/65833 is also related to this issue.

**Comment by madhusudhand** [comment]
Closing duplicate of #65920
