### ISSUE TITLE
Cover block with background image not working with style variation

### ISSUE THREAD

**Issue by juanfra** [WordPress/gutenberg#66067]
### Description

While working on TT5 and the latest Gutenberg, I noticed that some of our patterns were suddenly not working correctly.

I started checking the issue and apparently when you have a group block using section styles, and a cover block inside the image is not being shown. I saw that there were some recent changes to the [z-index](https://github.com/WordPress/gutenberg/pull/65626) of the cover block, so it might be related.

### Step-by-step reproduction instructions

1. Install a theme that uses style variations on groups (Like Twenty Twenty-Five)
2. Create a page.
3. Add a group block, pick a different section style than default.
4. Add a cover block inside the group block.
5. Add a background image for the cover block.
6. Confirm that the image is only displayed when the group block has the default variation. For all the others, the image won't show.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/34cc5acb-4c73-44c7-981e-b36fae41225c

### Environment info

- WordPress 6.7-beta2
- Gutenberg trunk
- TT5 trunk

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by renatho** [comment]
@juanfra, thanks for reporting it quickly! I reverted the original solution and implemented a different one. All details in the PR: https://github.com/WordPress/gutenberg/pull/66074.

**Comment by ndiego** [comment]
I have added the related issues/PRs to the 6.7 project board. cc @getdave @kevin940726

**Comment by juanfra** [comment]
This one can be marked as done, the changes that introduced the bug have been reverted [here](https://github.com/WordPress/gutenberg/pull/66074).

Thank you all! 🚀
