### ISSUE TITLE
Disable wrapping / topmost wrapper

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#6607]
It would be nice if Gutenblocks can be rendered without all the wrapping elements around it or at least offering a way for adding a wrapping element around the element plus its extra wrapped elements.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @strarsis.

I've filed this away in the [Ideas project](https://github.com/WordPress/gutenberg/projects/8) for future consideration. At this point in the Gutenberg development cycle, we're focusing on finishing the remaining features and then switching to bug fixing / polish.
