### ISSUE TITLE
Change name of Instagram block to Instagram Embed

### ISSUE THREAD

**Issue by Imran92** [WordPress/gutenberg#66087]
We've recently change the name of YouTube, Twitter etc blocks to YouTube Embed and Twitter Embed. However, the name for the embedding block for Instagram has not been changed, it's just **Instagram**.

There's another block for social icons named **Instagram**.

Both blocks having same name and icon is confusing. It's causing the E2E tests to fail too, which we have temporarily fixed [here](https://github.com/Automattic/wp-calypso/pull/95282), but it should be properly fixed by changing the name to Instagram Embed so the intention and functionality is more easily understandable.

![Image](https://github.com/user-attachments/assets/e7b373d5-5963-43a7-ab83-fcbfd9963058)

**Comment by t-hamano** [comment]
Hi @Imran92,

The Instagram Embed block has been disabled for about 4 years now: https://github.com/WordPress/gutenberg/pull/24472

How do you make it possible to insert the Instagram block?

**Comment by Imran92** [comment]
Hi @t-hamano !

I'm not sure if it's disabled, because I just created a fresh simple site and the block was there in the inserter. Does adding the deprecation comment result in removing it from the inserter?

Also, the Instagram embed block has always been [covered by this E2E test](https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts), so if it weren't available in the inserter, the E2E test would've reported an error each time GB was updated on WPCOM.

This is what I see in a fresh simple site -
![Image](https://github.com/user-attachments/assets/35a628bf-f207-485b-be27-11bb616722d9)

**Comment by hanneslsm** [comment]
@Imran92 do you have any plugins installed? What kind of theme are you using?

Just for reference, this is what I get with WordPress 6.7-beta2 and TT5:
![Image](https://github.com/user-attachments/assets/76dad422-592a-4c83-b864-fd837275b17f)

**Comment by SH4LIN** [comment]
@Imran92 
I also checked WordPress 6.7 Beta 3, and there is only a single Instagram block that allows adding a social link. There is no embed block.

![Image](https://github.com/user-attachments/assets/0ea27748-79ae-44e4-91ca-4d72abb416d3)

**Comment by t-hamano** [comment]
My guess is that wordpress.com has re-enabled the Instagram block via the Jetpack plugin.

Related issues/PRs:

- https://github.com/Automattic/wp-calypso/issues/45832
- https://github.com/Automattic/jetpack/pull/17192

Maybe you need to fix this here:

https://github.com/Automattic/jetpack/blob/f467c5d4e44473d0051bdddfa91c42d4888f4bbc/projects/plugins/jetpack/extensions/extended-blocks/core-embed/instagram.js#L9

**Comment by SavPhill** [comment]
> Hi @t-hamano !
> 
> I'm not sure if it's disabled, because I just created a fresh simple site and the block was there in the inserter. Does adding the deprecation comment result in removing it from the inserter?
> 
> Also, the Instagram embed block has always been [covered by this E2E test](https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts), so if it weren't available in the inserter, the E2E test would've reported an error each time GB was updated on WPCOM.
> 
> This is what I see in a fresh simple site -
> ![Image](https://github.com/user-attachments/assets/35a628bf-f207-485b-be27-11bb616722d9)
> 

Can you confirm what plugins you have installed? From the screenshot I can see you have Jetpack active.

**Comment by mtias** [comment]
Yeah, this is a plugin issue. Closing.
