### ISSUE TITLE
Escape key no longer brings to "navigation mode"

### ISSUE THREAD

**Issue by elettrona** [WordPress/gutenberg#66085]
### Description

Going from "editing mode" to "navigation mode" via keyboard no longer works in 19.4.0 version.
When editing a block, I'd expect that pressing "ESC" key I go back to navigation mode, where I can pass from a block to another by pressing arrow keys, but without editing them. In "navigation mode" I even can close "nested blocks" by pressing left arrow and opening them by pressing right arrow, then if it's open or closed I can add a block inside the nested block or outside.
But pressing Esc does nothing, and remains in editing mode.
This creates problems when you have nested blocks. Groups, lists, detail blocks, quotes... In the end you always find yourself editing inside the nested block even when you want to add a block outside.

### Step-by-step reproduction instructions

1. add a new post/page and a new block. Write a paragraph.
2. Press Escape. It does nothing. 
3. add a "list" block and populate it.
4. try to press "esc" to go to the navigation mode. Nothing happens. Pressing left arrow to close the tree's level does not work.

### Screenshots, screen recording, code snippet

WorkAround: add blocks as normal, then use the "list view" mode -alt+shift+O- to get the right orientation of nested blocks and, in case, do the editing.

### Environment info

WordPress 6.6.2 with Gutenberg 19.4.0. Windows 11, Chrome and Brave browser. Fearing this issue is also present in upcoming 6.7 WordPress. This is an accessibility regression.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by elettrona** [comment]
I mention @alexstine then @t-hamano and @afercia - further tests are needed, I fear this is coming to WordPress 6.7 stable, if not solved before. It causes much trouble especially when using Full Site Editing.

**Comment by afercia** [comment]
> no longer works in 19.4.0 version
> I fear this is coming to WordPress 6.7 stable, if not solved before

@talksina thanks for reporting this issue. WordPress 6.7 will be released with the version 19.3.0 of Gutenberg so that this issue will not be in the new release. It's still a problem though and I already created another issue at https://github.com/WordPress/gutenberg/issues/65603

Would you like to please report your feedback on that issue, when you have a chance?

**Comment by t-hamano** [comment]
Just to be sure, I have confirmed that this problem does not occur in WordPress 6.7 Beta 2.

Is the issue reported here part of #65603? If so, it may be a good idea to close this issue and consolidate the discussion in #65603.

**Comment by afercia** [comment]
> Is the issue reported here part of https://github.com/WordPress/gutenberg/issues/65603? If so, it may be a good idea to close this issue and consolidate the discussion in https://github.com/WordPress/gutenberg/issues/65603.

I'd agree. It's a good norm to be welcoming to new contributors though so I'd wait for @talksina feedback. There's no need to rush and close this issue immediately.

**Comment by afercia** [comment]
@talksina thanks for your dedication to making WordPress more accessible and for your feedback. Any objection to close this issue in favor of https://github.com/WordPress/gutenberg/issues/65603 ?

**Comment by elettrona** [comment]
Yeah, you can close this issue if the other is already open; I rather
apologize for not respecting the rule "search for similar issues" but I was
influenced by short time we have for next stable WP release. Let's continue
considering the other issue.

**Comment by afercia** [comment]
No problem really. Not to mention that the search functionality on GitHub is less than ideal and searching for existing issue isn't an easy task.
