### ISSUE TITLE
Deprecated function `wp_register_block_template` does not return the registered template object.

### ISSUE THREAD

**Issue by AnmolVerma404** [WordPress/gutenberg#66091]
### Description

While reviewing PR #65958 , I noticed that the deprecated function `wp_register_block_template` does not return a result. This seems to have been overlooked.

@Aljullu, does this sound correct, or did I miss anything?

### Step-by-step reproduction instructions

1. Go to [lib/compat/wordpress-6.7/block-templates.php:66](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.7/block-templates.php#L66)
2. The deprecated function `wp_register_block_template` for legacy code does not return the result from the renamed function `register_block_template`.

### Environment info

- Wordpress Version 6.7, Gutenberg version 19.4.0

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by AnmolVerma404** [comment]
I can create a quick-fix PR for this, if that works for you.

**Comment by Aljullu** [comment]
> While reviewing PR #65958 , I noticed that the deprecated function `wp_register_block_template` does not return a result. This seems to have been overlooked.

My bad. Yes, that was an overlook. 🤦 Good catch with this issue, @AnmolVerma404.

> I can create a quick-fix PR for this, if that works for you.

Sure, that would be awesome! Feel free to ping me for a review. 🙂

**Comment by AnmolVerma404** [comment]
All right @Aljullu  🙌,
I've created a PR for this #66102 . Since this is my first contribution 🎉 , please feel free to reach out if I'm not following or missing any details.

Thank you very much! 😄

**Comment by AnmolVerma404** [comment]
Closing this issue as the related PR has been merged. 🙌 
- #66102
