### ISSUE TITLE
Site Editor - Revisions for templates are only visible after three edits.

### ISSUE THREAD

**Issue by CacheMeOwside** [WordPress/gutenberg#66106]
### Description

Theme - Twenty Twenty-Four

When I try to edit the Blog Home template or the Index template, the `Revisions` section starts showing only after I make three edits to the template. I expect the revisions to start displaying right after the first edit.

### Step-by-step reproduction instructions

1. Go to Site Editor > Templates.
2. Edit the "Blog Home" or the "Index" template.
3. Add a paragraph block with some content, and save it. The `Revisions` option does not show up under the Template sidebar settings.
4. Edit the same paragraph block with more content or another block, and save. The `Revisions` option still does not show up.
5. Repeat step 4, but this time the `Revisions` option is visible after saving.

https://github.com/user-attachments/assets/b4de9f20-98a9-4ad5-a93b-9b2bdc780678

### Environment info

WordPress version: 6.6.2
Gutenberg version: 19.4.0
Active theme: Twenty Twenty-Four
Browser: Chrome 126.0.6478.127 on MacOS Sonoma 14.5

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by Mamaduka** [comment]
@draganescu, @ramonjd, is this same or similar to #49164?

**Comment by ramonjd** [comment]
Thanks @Mamaduka 

Looks the same to me 👍🏻 

There are a couple of options. 

I expect any solution will lie somewhere between fiddling with how WordPress [templates work](https://github.com/WordPress/gutenberg/issues/49164#issuecomme) and a [sensible UX](https://github.com/WordPress/gutenberg/issues/49164#issuecomment-1569339972).

**Comment by Mamaduka** [comment]
Thanks for the confirmation, @ramonjd!

I'm going to close this as a duplicate.

**Comment by ramonjd** [comment]
This PR looks like it will go a long way to resolve this issue:

- https://github.com/WordPress/gutenberg/pull/67125
