### ISSUE TITLE
Disable Zoom Out in Style Book

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#66127]
Let's consider disabling (or removing) the Zoom Out toggle in Style Book

> Ideally, the Zoom Out and Device Preview buttons should be disabled in the Style Book. Right now, they are clickable but do not really do anything. 
> 
> We could follow up with that one as a low priority "nice to have" fix.
> 
> 
> I did notice that the Zoom Out button toggles the breadcrumb bar at the bottom of the window.
> 
> I believe it's intentional in order to remove "chrome" from the view when zoomed.
> 
>  

 _Originally posted by @getdave in [#65630](https://github.com/WordPress/gutenberg/issues/65630#issuecomment-2413745473)_

**Comment by getdave** [comment]
@ndiego @colorful-tones @kevin940726 Lets determine if this is needed for 6.7

**Comment by colorful-tones** [comment]
It would be a nice-to-have for me. 

(Note: I edited the title and description to correct "Storybook" to "Style Book")

**Comment by andrewserong** [comment]
Just a quick drive-by comment, but some of the other header items are greyed out / disabled when the Style Book is open, so I'd probably lean toward disabling rather than removing for consistency:

![Image](https://github.com/user-attachments/assets/8fcec95a-c2ce-40f2-976f-e293a395877c)

So perhaps a similar approach could be used for the Style Book button?

**Comment by andrewserong** [comment]
I've tried a simple (and possibly naive) approach over in https://github.com/WordPress/gutenberg/pull/66228 in case it can make it in for 6.7 in time.

**Comment by madhusudhand** [comment]
I think `View` button could also be disabled when style book is open, because changing the options (Desktop to Mobile) does nothing in this state.

**Comment by andrewserong** [comment]
> I think View button could also be disabled when style book is open, because changing the options (Desktop to Mobile) does nothing in this state.

Good point. I briefly considered doing that in the same PR, but one potential argument for keeping it around is that the dropdown also includes the View Site link — it's possible that some folks would like to quickly get to View Site with the Style Book open, so it could add friction to that particular action if we disable the View dropdown button. So if we look into this idea, perhaps we'd want to disable the Desktop / Tablet / Mobile buttons, but not the View site external link?

![Image](https://github.com/user-attachments/assets/99af6501-1c8c-464e-8e7d-e1f06f9848a1)

That would also help ensure that we don't accidentally disable things added into the dropdown by plugins: https://make.wordpress.org/core/2024/10/18/extending-the-preview-dropdown-menu-in-wordpress-6-7/ — though something else to consider is that items added by a plugin may or may not be compatible with the style book being open. Just something else to consider if we decide to pursue disabling things here.
