### ISSUE TITLE
Broken zoom out view when exiting style book

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#66133]
### Description

The zoomed out view is too narrow when exiting the style book.

I assume it's related to saving the initial width of a container that doesn't exist when entering zoom out.

### Step-by-step reproduction instructions

1. Start in the site editor.
2. Open the 'Styles' sidebar.
3. Open the 'Style Book'.
4. Enter 'Zoom Out'.
5. Close the 'Style Book'.

I've also sometimes been able to reproduce the issue when entering zoom out via 'Browse Styles' and then opening the 'Style Book'.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/452ec2a3-82c8-466f-ab4d-a413efe0297b

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by PARTHVATALIYA** [comment]
Hello @ajlende I can't reproduce this issue. I test it in latest trunk and it work fine. Here is the screen video for that.
https://github.com/user-attachments/assets/a5dee38a-7907-4f9f-97ca-795c72c76de3

**Comment by draganescu** [comment]
I confirm this is soved in trunk.
