### ISSUE TITLE
Inline formatting toolbar border radius clipping

### ISSUE THREAD

**Issue by stokesman** [WordPress/gutenberg#66134]
### Description

The formatting toolbar’s corners are getting a little clipped. It appears to have came about in #64368

### Step-by-step reproduction instructions

1. Add an image block
2. Add or focus the caption text
3. Note the formatting toolbar’s clipped corners

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/8b97e5ce-29a3-46be-8b64-45ed7503d9a1)

### Environment info

- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by stokesman** [comment]
@jameskoster, you’d perhaps be most wise on how to fix this. I see this in 6.7 beta but not in 6.6 so I think it would qualify for fixing in 6.7. Of course it’s not too critical.

**Comment by jameskoster** [comment]
Good spot. There are a couple of things happening:

1. This toolbar is wrapped in a `Popover`, the `4px` radius of which is clipping the toolbar.
2. Button groups in this toolbar have a background color, whereas groups in the regular block toolbar do not.

We need to explore updating the toolbar component to align with the new [radius scale](https://github.com/WordPress/gutenberg/issues/63703), but that's a 6.8 thing. 

I'll open a PR for 6.7 to address this.
