### ISSUE TITLE
Zoom out persists after reloads but not entirely engaged

### ISSUE THREAD

**Issue by stokesman** [WordPress/gutenberg#66138]
### Description

If the page is reloaded while zoom out is engaged the mode is engaged upon reload yet the toolbar button is not shown as pressed and the view scaling/frame spacing is not present.

I'm not sure when/how this came about or if it was intentional.

### Step-by-step reproduction instructions

1. Engage zoom out
2. Reload the page
3. Note that zoom out is still engaged (select a block and note the inserter buttons)

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/4fa76e40-a212-4d85-bf70-395cb14dccd2

### Environment info

Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by jasmussen** [comment]
Encountered this as well, this is an important one to fix.

**Comment by talldan** [comment]
From my testing, this doesn't happen in the wp/6.7 branch, so I'm removing it from the WordPress 6.7 Editor Tasks board.

I believe https://github.com/WordPress/gutenberg/pull/65945 introduced the persistence of the modes, and it wasn't backported for 6.7.

A fix will still be needed for trunk.
