### ISSUE TITLE
Double Scrollbars Appear and Layout Breaks in Block Inserter When Searching for Blocks in Gutenberg

### ISSUE THREAD

**Issue by dhruvang21** [WordPress/gutenberg#66161]
### Description

When searching for blocks in the block inserter within the Gutenberg editor, the layout breaks, and multiple double scrollbars appear. This issue significantly affects the user experience by making it difficult to navigate and select blocks, while also distorting the page layout.

### Step-by-step reproduction instructions

1. Open the Gutenberg editor in the latest trunk branch.
2. Click on the block inserter tab to open it.
3. Type any search term in the block search bar (for example, "a").
4. Observe that multiple scrollbars appear on the screen, and the entire layout shifts awkwardly.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/d33039f0-caa8-4e7d-bc68-3b500d29a81b

### Environment info

- Gutenberg trunk branch
- Operating System:- ubuntu
- Browser: chrome

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by t-hamano** [comment]
Thanks for the report. 

This issue seems to occur when the browser height is low:


https://github.com/user-attachments/assets/65e658c9-37ab-44bf-b30a-fbd4b1cf6ac8


Also, this issue does not occur in WordPress 6.6.2, but does occur in WordPress 6.7 Beta 3 and the latest Gutenberg.

So I will add this to my project board.

**Comment by colorful-tones** [comment]
I took a pass at a fix for this: #66176 , but it could use some cross-browser testing and different screen sizes as well.
