### ISSUE TITLE
Word count crash when content is empty

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#6617]
## Issue Overview

The content editor is crashing when clicking on the information icon to display word count. (tested with 2.8)

The tricky part:  
When you create a post, this button is disabled by default. But when you enter the first paragraph, the button becomes available (but there is still no word to count). 

An error occurs and crashs the editor

## Expected Behavior

Seeing :

![capture 2018-05-07 a 14 54 30](https://user-images.githubusercontent.com/1785489/39702913-9ef7ac20-5206-11e8-97c3-64f4cf6d8e68.jpg)

## Current Behavior

Crashing : 
![capture 2018-05-07 a 14 54 50](https://user-images.githubusercontent.com/1785489/39702917-a3eb6a50-5206-11e8-9d82-b514242fc00c.jpg)

**Comment by aduth** [comment]
Related: https://github.com/WordPress/packages/issues/122

**Comment by klihelp** [comment]
Same happening when page contains non-text based blocks, like image, gallery ...
`The editor has encountered an unexpected error.`
