### ISSUE TITLE
Post Excerpt: not being able to use inline HTML elements.

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#66195]
Originally [reported in the forums](https://wordpress.org/support/topic/excerpt-stripping-out-html/#post-18078485).

## What

Inline HTML elements added to the excerpt no longer work in the front-end.

## Steps to reproduce

WordPress 6.2: works as expected

https://github.com/user-attachments/assets/1e836d09-9f9e-4832-a4c3-9ab1738759f2

WordPress 6.3: works in the editor but not in the front-end

https://github.com/user-attachments/assets/d5b41d30-cdb8-47c9-8425-42ea46492c85

### Environment info

@justintadlock pinpointed it to [this PR](https://github.com/WordPress/gutenberg/pull/44964). I've confirmed that it works in WordPress 6.2 but not in WordPress 6.3.

**Comment by oandregal** [comment]
cc people involved in https://github.com/WordPress/gutenberg/pull/44964 the likely source of the issue: @carolinan @alexstine @mcsf @aristath

**Comment by t-hamano** [comment]
I think this is the same issue as #49449, which appears to be attempted to resolve by #65209.

**Comment by carolinan** [comment]
Yes this is a duplicate.
