### ISSUE TITLE
Cover block should not have additional controls when zoomed out

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#66206]
Currently the Cover block maintains its additional toolbar controls when zoomed out. I propose the tooling when zoomed out should be consistent across blocks, instead of having one-off controls on some blocks. 

### Visual 

![Image](https://github.com/user-attachments/assets/bddf6742-f86d-4ca4-8679-cdf065019fba)

Note that the visual above is testing https://github.com/WordPress/gutenberg/pull/66194.

**Comment by draganescu** [comment]
@youknowriad  will this be auto solved by adding the edit mode to the zoom out view?

**Comment by youknowriad** [comment]
How do you decide (generally speaking for all blocks), which toolbar buttons to show and which ones to hide in zoom-out? Or should we just remove all the "slots"? (all the toolbar buttons defined by the block itself as opposed to the ones added by the framework)

**Comment by ntsekouras** [comment]
I was looking at this and have the same question with @youknowriad. It seems for some `support` toolbar buttons (like `align`) we have an extra check for `blockEditingMode !== 'default'` which essentially not renders them in zoom out. So it's not a specific problem to `Cover` block, but just a coincidence that we usually don't use many other blocks as pattern wrappers.

**Comment by talldan** [comment]
Some other issues were spotted over here - https://github.com/WordPress/gutenberg/pull/66200#issuecomment-2422442515

- Multi-selection group transform options show in the toolbar
- Lock/Unlock options show in the toolbar for user locked blocks
- Vertical alignment shows (observed on the columns block).

It's probably be easiest to hide all the slots as @youknowriad suggests.

**Comment by richtabor** [comment]
> How do you decide (generally speaking for all blocks), which toolbar buttons to show and which ones to hide in zoom-out? Or should we just remove all the "slots"? (all the toolbar buttons defined by the block itself as opposed to the ones added by the framework)

Yea, I don't think we'll have block-specific tools in the toolbar when zoomed out, only controls like the shuffle/change design and  #66465.
