### ISSUE TITLE
Consider to show the number of categories and tags added to a post

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6625]
Splitting this out from #1339

In #1339 (see also #6214) I was initially proposing to show the number of tags added to a post in soe visible text:

> add the total count of terms added in a visible text before the field, something along the lines of {plural term name} added: 3

however, it would be beneficial to do the same thing for categories too. Although not strictly related to accessibility, that would be a useful indication for all users. This textual indication could be in the panel itself, so it's visible also when the panel is closed:

<img width="313" alt="screen shot 2018-05-07 at 19 43 48" src="https://user-images.githubusercontent.com/1682452/39723962-ac6e77bc-5247-11e8-9c84-37fd71f9ade3.png">

For inspiration, Calypso does something similar, even though Categories and Tags are grouped in the same panel (and there's some logic to determine when to show the term's name or the total count):

<img width="310" alt="screen shot 2018-05-07 at 20 03 10" src="https://user-images.githubusercontent.com/1682452/39724009-cf17dbdc-5247-11e8-8798-41187f5d5695.png">

In Gutenberg, this could be simply a number.

**Comment by afercia** [comment]
Just to add a consideration: when there are many categories (the screenshot below shows the ones from the theme unit test data) the only way to know how many and which categories are set on a post is to scroll the entire list of categories, which can be huge... (my one doesn't fit within the viewport height):

![screen shot 2018-05-09 at 15 32 04](https://user-images.githubusercontent.com/1682452/39817416-620a53d2-539e-11e8-905b-238a02df5744.png)

**Comment by karmatosed** [comment]
This is an interesting idea and one that has got me thinking a lot - which is good! I feel that showing the name has merit, however I admit to struggling to see what problem showing the number solves. This could just be I'm not seeing that though.

I do have a concern over both translation and number, what if you have long category names too? Does this approach scale well?

**Comment by karmatosed** [comment]
Let's put this as a possible idea for the future but for now close this and consider about iterating. I'm putting into the ideas project, this closes it but puts it as something to consider in later versions.
