### ISSUE TITLE
Storybook: Improve component organisation

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#66275]
Currently the majority of components are grouped in a single list which isn't very intuitive to navigate. 

This [sitemap](https://www.figma.com/board/0ZfHa37xxWoMqy7McezUNX/WordPress.org-Storybook-Sitemap?node-id=126-5118&t=ruCtnVTDVjHTfksc-1) demonstrates how we might introduce some organisation in order to improve the Storybook experience. 

- [x] Utilities – https://github.com/WordPress/gutenberg/pull/66210
- [x] Actions
- [x] Containers
- [x] Feedback - https://github.com/WordPress/gutenberg/pull/66660
- [x] Layout - https://github.com/WordPress/gutenberg/pull/66659
- [x] Navigation - https://github.com/WordPress/gutenberg/pull/66658
- [x] Overlays - https://github.com/WordPress/gutenberg/pull/66657
- [x] Selection & Input - https://github.com/WordPress/gutenberg/pull/66635
- [x] Typography - https://github.com/WordPress/gutenberg/pull/66633

**Comment by Vrishabhsk** [comment]
Hi @jameskoster 👋. Can I work on this issue?

**Comment by jameskoster** [comment]
@Vrishabhsk of course :)

**Comment by hbhalodia** [comment]
Hi @jameskoster, I have raised the PR to add the components under typography - PR - https://github.com/WordPress/gutenberg/pull/66633

Thank You,

**Comment by hbhalodia** [comment]
Hi @jameskoster, Had raised PR to add components under Selection & Input Category - https://github.com/WordPress/gutenberg/pull/66635.

Thank You,

**Comment by Vrishabhsk** [comment]
Hi @jameskoster 👋 
- The organisation of the components for `Actions` and `Containers` is already implemented
- The only change I can see is for `Actions` - `DropdownMenuV2` (Renamed as `Menu` [recently](https://github.com/WordPress/gutenberg/pull/66289)) is experimental
- Shall I put it under `Actions` folder under `Experimental Components` or let it be as it is now?

Let me know your thoughts. Thanks

**Comment by jameskoster** [comment]
> Shall I put it under Actions folder under Experimental Components or let it be as it is now?

Experimental > Actions > Menu seems good to me :)

**Comment by Vrishabhsk** [comment]
Raised `PR` for moving Menu under `Actions` folder : [`#66680`](https://github.com/WordPress/gutenberg/pull/66680)

**Comment by mirka** [comment]
I think we're done for the scope of this issue. Thanks everyone for helping out!

**Comment by tyxla** [comment]
Thanks everyone, great work y'all 🚀
