### ISSUE TITLE
Restore ability to copy and delete patterns in zoom out 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#66287]
Now that we reverted the [vertical toolbar and have returned to the regular toolbar](https://github.com/WordPress/gutenberg/pull/66039), some of us were testing zoom out today and noticed that we missed having a quick "trash" option. Without it, it's not exactly clear how to remove a pattern, even though using the delete key on the keyboard does still remove the pattern. Considering the prior vertical toolbar included a trash button, I'm marking this as a bug.

**Comment by ellatrix** [comment]
Fixed here: [#66288](https://github.com/WordPress/gutenberg/pull/66288).

**Comment by annezazu** [comment]
As a quick update -- we can also just add in the three dot menu with perhaps just duplicate and delete as the remaining options.

**Comment by getdave** [comment]
Noting that https://github.com/WordPress/gutenberg/pull/66311 should be the right fix for this, avoiding any more proprietary UI.

**Comment by getdave** [comment]
This should have been closed in https://github.com/WordPress/gutenberg/pull/66311

**Comment by richtabor** [comment]
> This should have been closed in https://github.com/WordPress/gutenberg/pull/66311

Re-opening as this was only merged in 6-7, not trunk.

**Comment by draganescu** [comment]
It seems in `trunk` the more menu is there when zoomed out:

![Image](https://github.com/user-attachments/assets/0c6211b6-7010-420c-8c29-5f8df424d970)

but in 6.7.1 the menu is trimmed to less options

![Image](https://github.com/user-attachments/assets/1809dd78-3b2f-4232-a26b-e0655da6af54)
