### ISSUE TITLE
Nofollow option in a button link block adds unnecessary space before the attribute

### ISSUE THREAD

**Issue by franzaurus** [WordPress/gutenberg#66300]
As reported [here](https://wordpress.com/forums/topic/relnofollow-on-button-blocks-has-a-flaw/).

When users add a link in the button block and mark it as nofollow, the resulting HTML comment adds unnecessary space before the attribute.

### Steps to reproduce

1. Add a button block and insert a link
2. Edit the link and check the _mark as nofollow_ option
3. View the resulting HTML code via the Code editor
4. OR inspect the button element via the browser
5. Notice the link's `rel=" nofollow"` attribute has space before the string

I've checked some other blocks that have "rel" attribute enabled (e.g. custom link, social icons, title, featured image, image, media, and text) with the help of this [list](https://fullsiteediting.com/block-attribute/rel/) and found that it only affects the button block.

As a workaround, users can edit the button instances via the code editor view and make the necessary edits to the HTML code there.

**Environment**
Studio, Local
WP 6.6.2 with/without Gutenberg 19.4.0
WP 6.7-beta3 without Gutenberg
 
![Image](https://github.com/user-attachments/assets/fde3f3fd-4183-4d42-bf69-bf1291da64f7)

**Comment by vipul0425** [comment]
Hi @franzaurus, Thanks for reporting this.
It seems like when there was no `rel` value set from the buttons advance settings then also it was appending space before the link `nofollow` value. Added a [PR](https://github.com/WordPress/gutenberg/pull/66303) to fix this issue.
