### ISSUE TITLE
Data views: Add density preference to Table layout

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#66312]
Depending on the type / amount of data being viewed, and accessibility preferences, it could be nice to offer users a density option in data views Table layout. In addition to the default spacing, we might offer higher and lower density options.

## Increased density

![Image](https://github.com/user-attachments/assets/8e6b9d03-412d-4bd2-a08a-a3a58925521f)

## Relaxed density

![Image](https://github.com/user-attachments/assets/e380f833-1216-4b04-ac63-f0a34a62cbdb)

These options would likely live in the view options. What do you think?

**Comment by mtias** [comment]
Agreed with supporting this. It's useful for offering extenders flexibility while also recognizing user preferences. It's also somewhat analogous to grid item size for the grid view.

**Comment by rogermattic** [comment]
+1 on this! we'd use this for payments reporting for sure, we need to support densed views.

I was wondering if you'd consider adding a _predefined_ options for users?  Like in Gmail for example where the user can swap between 3 different density levels? 

![Image](https://github.com/user-attachments/assets/ccfb7d41-c9e0-421b-b305-9ed4442d76c6)

**Comment by oandregal** [comment]
For the record, I've grouped together issues related to "theming" in the dataviews component issue, so they are visible https://github.com/WordPress/gutenberg/issues/55083

**Comment by jameskoster** [comment]
Yes to predefined options. We need to work out how many to offer, and where the current config falls on the scale. 

I don't know that we could create the gmail example with the current component set, that feels like a detail to explore later if we identify other situations that would make use of such a UI.

Initially it might make sense to mimic the 'Preview size' option in grid layout:

<img src="https://github.com/user-attachments/assets/703375b4-bc14-4c57-990a-0df8d13c8de7" width="350">

**Comment by rogermattic** [comment]
Thanks @jameskoster ! 
I'll make two mockups then, this one with the slider and another one for a possible component that we might add later. 

> feels like a detail to explore later if we identify other situations that would make use of such a UI.

I'll think about other potential cases.

**Comment by jameskoster** [comment]
It would be good to mockup the tables with different density values too, the ones in the OP were quickly hacked together :)

**Comment by rogermattic** [comment]
@jameskoster I made the mockups for the `Density`. In general I feel like three density options to choose from would be enough:

1. Selection with a tick

![Image](https://github.com/user-attachments/assets/7aef8a86-f525-4a64-9fcb-d8085b93488b)

I think that works well, just the icons are placeholders for now. Do you think that's worth exploring further?

2. Slider

![Image](https://github.com/user-attachments/assets/c5039885-aa1e-4105-9c74-b96c7d4235f1)

I made a similar mockup to what Veronica (not sure what's her username here on GH) proposed, but I thought it would be better to have just 3 levels not 4 (for `Default`, `Compact` and `Comfortable`)

3. Radio

Was thinking about the simple radio button option but I realised we might not want to use that on the panel, as the component for the items per page and order works as a radio selection..? I made this option then, but understand that might be a bit of a stretch!
3 options squeezed inside that component felt like a bit too much, but I thought we might also want to try just offering 2 options - `Compact` and `Comfortable`

![Image](https://github.com/user-attachments/assets/4eaa208d-cfce-414f-a014-d179ea628ef5)

What do you think?

**Comment by jameskoster** [comment]
I still lean towards the slider myself, just because it is consistent with the 'Preview size' option in Grid layout. 

We can revise holistically after. 

Using `ToggleGroupControl` is an interesting idea though, it might work nicely with icons? Quick mockup:

![Image](https://github.com/user-attachments/assets/9cbd3428-cebb-4d94-bb8f-4786a2f9ae1d)

**Comment by rogermattic** [comment]
> Using ToggleGroupControl is an interesting idea though, it might work nicely with icons? 

I love this! It's simple and gives us the flexibility that we need. 

As I mentioned elsewhere I think we should be able to come up with three predefined settings for the general table component (adjusting padding, badge variant if needed, and perhaps choosing a different variant of the body copy size from the predefined typescale). 
Then each table, depending on the use case, would initially be set to a different default; for example, a number-heavy table would use a compact view, while a blog post list would use a comfortable view, etc. 

That would be hard to solve using the actual `default` label (in the option where we'd have `Default`, `Compact` and `Comfortable`). If for one table the default would be set close to `Comfortable` we would need to add an extra grade _above_ etc. The visual only approach doesn't require us to label things, whether it's a slider or a toggle group.

> I still lean towards the slider myself, just because it is consistent with the 'Preview size' option in Grid layout.
> We can revise holistically after.

Considering using `ToggleGroupControl ` do you think we could settle on this or would you instead still start with the slider?

**Comment by ntsekouras** [comment]
I think density is something that could be supported by any layout if they want to and in order to do that maybe a first step is to use predefined options (like Default, Compact and Comfortable) and not specific icons for every one.

Would it be okay to start without icons for now?

**Comment by rogermattic** [comment]
@ntsekouras Thanks for your feedback!

I'm not convinced anymore that we should use text labels, for the reason I mentioned earlier: 

> That would be hard to solve using the actual default label (in the option where we'd have Default, Compact and Comfortable). If for one table the default would be set close to Comfortable we would need to add an extra grade above etc. The visual only approach doesn't require us to label things, whether it's a slider or a toggle group.

But as @jameskoster said, we can start with a slider approach first; in this case, the `default` setting would just be captured initially by the slider's position. WDYT?

> I still lean towards the slider myself, just because it is consistent with the 'Preview size' option in Grid layout.

Are you happy with a three-grade slider or leaning more towards a continuous line? @jameskoster  @ntsekouras 
![Image](https://github.com/user-attachments/assets/643212ad-6f19-4894-b044-ee144433d2a1)

**Comment by ntsekouras** [comment]
I'm okay with the slider but also checking the code right now to see how we can abstract it better for any layout. It seems we show different density options depending on the viewport width. Is this something we want to preserve? Because it might not make sense in all layouts and we might want to be consistent and always show 3 options.

**Comment by ntsekouras** [comment]
Now that I'm exploring it a bit more, I don't think we can avoid the labels as the `default` could be anything for a layout - it could be closer to compact or comfortable. So, I'm not sure we can use a slider..

**Comment by rogermattic** [comment]
> Is this something we want to preserve? Because it might not make sense in all layouts and we might want to be consistent and always show 3 options.

I think we should be consistent and always show the same number of options. 

> I don't think we can avoid the labels as the default could be anything for a layout - it could be closer to compact or comfortable. 

I think we could display it like that:

If the default is `comfortable`:
![Image](https://github.com/user-attachments/assets/4f157029-fede-49bd-b046-52394464daff)

If the default is `compact`:
![Image](https://github.com/user-attachments/assets/4b972bf2-b31b-4d50-ab17-e123aedc8957)

The in-between state:
![Image](https://github.com/user-attachments/assets/bd565cc8-f6ac-4f9d-a134-d571b427544a)


However I'm worried about the case when the  predefined state for some component means `comfortable`, then what do we call that 3rd option – i.e. we'd have (sorry for the rough mockups):
![Image](https://github.com/user-attachments/assets/c8d9035a-4b83-423a-a95a-125fc61e31a6)

I'm wondering if this wouldn't be confusing for the user, why the initial setting isn't a `default` one :D 

It's easier with two options:
![Image](https://github.com/user-attachments/assets/4870be3b-e2a2-4524-974f-acb256c5cb4a)

Or we need to replace the name `default`.

**Comment by rogermattic** [comment]
Something that I'm exploring in parallel is how the `Density` setting would result in the views , for now just on the table (transactions report, disputes report and the list of pages) example:

![Image](https://github.com/user-attachments/assets/d0213cda-25a9-4234-a3f5-89d6165219ca)


I marked what in my opinion should be the initial views for each example with a green dot. 
There's more options available, but I think we should still aim for 3 presets – `Comfortable` `Medium` `Compact`.

**Comment by ntsekouras** [comment]
I created a PR for this [here](https://github.com/WordPress/gutenberg/pull/66837) and we can discuss and update the design.


>There's more options available, but I think we should still aim for 3 presets – Comfortable Medium Compact.

By implementing this I realised the validity of @rogermattic's point about the `default` label and shouldn't be used as a preset. It makes sense to have presets like the suggested with increasing density and  a consumer could set whatever default value they want.

That also means, that if we agree on such presets, a slider could also be used.

**Comment by rogermattic** [comment]
@ntsekouras I just saw the [screencast on the PR](https://github.com/WordPress/gutenberg/pull/66837#issue-2641826375). t looks great! I really love the clarity of this approach—the labels make everything so clear. My only concern is whether longer labels might cause issues with fitting, especially once localized.

> By implementing this I realised the validity of @rogermattic's point about the default label and shouldn't be used as a preset. It makes sense to have presets like the suggested with increasing density and a consumer could set whatever default value they want.

Thank you! Sorry if I wasn’t very clear in explaining that point :) 

I was thinking about the alternatives to `default` and `medium`, we could also used `balanced` `regular` or `moderate`.

**Comment by annchichi** [comment]
> I was thinking about the alternatives to default and medium

I was reading through the convo, and if the options label default and medium, the default name doesn't clarify what it is. Like Google's options (screenshot above), there is a need to click other options to find what default means. :)

**Comment by mcsf** [comment]
> However I'm worried about the case when the predefined state for some component means `comfortable`, then what do we call that 3rd option – i.e. we'd have (sorry for the rough mockups): ![Image](https://github.com/user-attachments/assets/c8d9035a-4b83-423a-a95a-125fc61e31a6)

To add another difficulty to that representation: these labels are already snug in English, and they could become very awkward in other languages.
