### ISSUE TITLE
Extending BlockFormatControls adds elements not as a child 

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#6632]
## Issue Overview
I want to append a custom button/toolbar to the format controls but the toolbar/button doesn't get a child of `.blocks-format-toolbar`.

## Steps to Reproduce (for bugs)
I tried using this in the edit method of my block:
```js
<BlockFormatControls>
	<IconButton
		icon="smiley"
		label="test"
	/>
</BlockFormatControls>
```

and this:
```
<BlockFormatControls>
	<Toolbar>
		<IconButton
			icon="admin-users"
			label="test"
		/>
	</Toolbar>
</BlockFormatControls>
```

I also tried `<Toolbar controls={ controls}` but that did nothing for some reasons.

In both cases I got this:
<img width="745" alt="toolbar" src="https://user-images.githubusercontent.com/617637/39746007-633b7a06-52a9-11e8-8018-4c56563cddd4.png">

## Expected Behavior
My button/toolbar is a child of `.blocks-format-toolbar`.

## Current Behavior
My button/toolbar is not a child of `.blocks-format-toolbar`.

## Related Issues and/or PRs
#4658

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by gziolo** [comment]
@aduth proposed a fix in #7231 which would solve this issue.

**Comment by aduth** [comment]
Previously: #6089, #6839

**Comment by nerrad** [comment]
Looks like this is superseded by the [Format API](https://github.com/WordPress/gutenberg/tree/master/docs/designers-developers/developers/tutorials/format-api) so I'm closing.
