### ISSUE TITLE
Zoom out returns after inserter is closed

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#66328]
### Description

Disabling zoom out while the inserter is open makes it come back when the inserter is closed.

### Step-by-step reproduction instructions

https://github.com/user-attachments/assets/0efcb333-6eab-40e8-92e4-91c436535660

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by draganescu** [comment]
This is because of the useZoomOut hook "toggling" the state instead of setting it.

**Comment by Mamaduka** [comment]
I also noticed that the `useZoomOut` hook is public and shipped with WP 6.6. It should've been a private hook.

**Comment by jeryj** [comment]
> I also noticed that the useZoomOut hook is public and shipped with WP 6.6. It should've been a private hook.

Yup -- that is true.

@draganescu - @ajlende and I are testing this and unable to reproduce on the 6.7 branch. Can you try again on 6.7?

**Comment by jeryj** [comment]
Confirmed this a bug on `trunk`, not on `wp/6.7`. I remove it from the wp/6.7 board and removed the high priority tag.

**Comment by Mamaduka** [comment]
There might still be time to make `useZoomOut` private and remove public references. I doubt anyone is using this hook outside of the plugin/core.

**Comment by draganescu** [comment]
I triple vote this. Then maybe we can delete it.

**Comment by jeryj** [comment]
Made it private in this PR: https://github.com/WordPress/gutenberg/pull/66374

**Comment by Mamaduka** [comment]
Encountered and got reminded of this bug again today. Here's my alternative approach - #67033.
