### ISSUE TITLE
Improve the DocumentBar post type label for the Homepage and Posts Page cases

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#66320]
### Description

https://github.com/WordPress/gutenberg/pull/65170 added a 'post type label' to the DocumentBar and removed the type icon to provide a clearer information about the object being edited. So far so good. Screenshot:

![Image](https://github.com/user-attachments/assets/5ab5af3c-ae20-460c-a25c-5c7c1fa7194e)

There are at least two edge cases though where other parts of the UI use a special label for the object being edited: The 'Homepage' and 'Posts Page' pages. 

In this cases, while the DocumentBar still says just 'Page', the `PostCardPanel` in the Settings panel adds a more specific label to these special pages. 

As such, users see two inconsistent pieces of information, which is confusing, and may think something is going wrong. 

Screenshots:

![Image](https://github.com/user-attachments/assets/62b25ddb-4b90-47e7-a922-ccc02c046b38)

![Image](https://github.com/user-attachments/assets/c70f33da-25ac-41d7-ae78-f55cc87b020e)

I'd suggest to provide a consistent information and make the Document Bar handle these special cases by providing a consistent label:
- Homepage 
- Posts Page

### Step-by-step reproduction instructions

- Go to the wp-admin Reading Settings.
- Set your homepage to display a static page.
- Set a Posts page.
- Go to the Site editor > Pages.
- Select either the page used tor the homepage or the one used tor the posts page.
- Observe the Document Bar label is 'Page'.
- Observe the Post card in the settings panel uses a more specific label: 'Homepage' or 'Posts page'.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by afercia** [comment]
Noting that the [PostCardPanel](https://github.com/WordPress/gutenberg/blob/d0771cda1bdc8d4d78c956f4fffda04182572967/packages/editor/src/components/post-card-panel/index.js#L102-L111) uses some hardcoded checks to determine the label based on `isFrontPage` or `isPostsPage`.

A similar check is in place in [usePostFields](https://github.com/WordPress/gutenberg/blob/d0771cda1bdc8d4d78c956f4fffda04182572967/packages/edit-site/src/components/post-fields/index.js#L237-L249), which is is used in the data views posts list:

![Image](https://github.com/user-attachments/assets/45640c5c-8c91-40de-9eb5-ede98bc86c0a)

Instead of hardcoding a new, third check I'd suggest to explore how to abstract this logic into a small utility and reuse it where needed.

**Comment by hbhalodia** [comment]
Hi @afercia, I have raised the potential PR to fix the hardcoding, however I noticed that `data-views` are in whole different package, which could not be used inside another package. So I had prevent updating the `post fields` component, and updated `post-card-panel` and `document bar` to resuse the same logic to display the badge.

Thank You,
