### ISSUE TITLE
PluginSidebar and plugins are not functioning in the Widget Editor

### ISSUE THREAD

**Issue by ChrisBoostwords** [WordPress/gutenberg#66326]
### Description: 
Plugins, including PluginSidebars, do not render in the Widget Block Editor.

They are visible in wp.plugins.getPlugins, but they do not appear in the menu or as pinned items. The same plugins render as expected in the Post Block Editor.

### Step-by-step reproduction instructions:
This issue can be reproduced with a simple plugin based on the Gutenberg documentation. The plugin below will register, but nothing is output.
```
import { PluginSidebar } from '@wordpress/edit-post';
import { registerPlugin } from '@wordpress/plugins';
import { useState } from '@wordpress/element';

const PluginSidebarExample = () => {
	return (
		<PluginSidebar
			name="plugin-sidebar-example"
			title={'My PluginSidebar'}
			icon={ 'smiley' }
		>hello</PluginSidebar>
	);
};

// Register the plugin
registerPlugin( 'plugin-sidebar-example', { render: PluginSidebarExample } );
```

**Comment by t-hamano** [comment]
Thanks for the report.

This is a known issue, so let me close. Please see:

- https://github.com/WordPress/gutenberg/issues/47029
- https://github.com/WordPress/gutenberg/discussions/41034
