### ISSUE TITLE
Cover block content position not centered, inside group block alignwide width ignored

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#66340]
### Description

See step-by-step instructions.. 

### Step-by-step reproduction instructions

1. Add a cover block, set to full width
2. Add a group block inside the cover block and set to alignwide
3. Add lengthy paragraph inside the group block
4. Click the cover block and set the content position to bottom left, bottom right, etc. (anything but the default of center)
5. Save and view
6. Note that the group block does not use the alignwide width but rather just spans the full width (with padding) inside the cover block

Final screenshot shows the group block is too far left aligned (it is not in the global wide width size container of 1400px but is instead the default content width of 700px and positioned far left and bottom). 

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/e389a222-5da3-4589-a1e1-e195f9db9ac7)
![Image](https://github.com/user-attachments/assets/de6d9e91-0d8e-47a7-ad1a-d9242eefdb57)
![Image](https://github.com/user-attachments/assets/9b91c74b-e2e4-46ab-a3c0-b32d3ee78100)

### Environment info

- WP 6.6.2
- gutenberg 19.4.0
- chrome
- mac

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Mayank-Tripathi32** [comment]
Hello @bradhogan, I tried to replicate the bug, but everything seems to be working as expected on my end. If you’re still experiencing the issue, could you share a video of the problem? Additionally, are you using a custom theme or a theme.json file?


Wide [1280 width]
![Image](https://github.com/user-attachments/assets/967ee69c-9783-4841-a00c-e88466dddb33)

Wide [620]
![Image](https://github.com/user-attachments/assets/d308c5ac-24d0-424c-8d3e-d5723d54ba17)

Full Width
![Image](https://github.com/user-attachments/assets/b3de1d45-7945-4c25-a5f1-f8ce7525303d)


Tested with: 6.6.2, 6.7
Theme: 2024 default

**Comment by bradhogan** [comment]
@Mayank-Tripathi32 thanks for looking into this.  I can't seem to replicate anymore in my default environment so it must be fixed in a recent update. Cheers.
