### ISSUE TITLE
Add linting rules to prevent the usage of the verb 'toggle' in all translatable strings

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#66372]
### Description

See 
https://core.trac.wordpress.org/ticket/34753
https://github.com/WordPress/gutenberg/discussions/42492
https://github.com/WordPress/gutenberg/issues/66369
https://github.com/WordPress/gutenberg/pull/66371

It would be nice to add ESLint and PHP linting rules to prevent future usages of the verb 'toggle' inside translatable strings.

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by geekofshire** [comment]
Can you please assign this task to me? I would like to work on it.
