### ISSUE TITLE
Allow Positioning Options for Header and Footer

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#66382]
## What problem does this address?

This report originated [here](https://github.com/Automattic/wp-calypso/issues/86286) and I'm raising it with you as I cannot find an exact report.

It's not possible to set a sticky header
Setting sticky on a group block within a header also doesn't work.
The content scrolls.
Moving the group block outside the header fixes the problem.

## What is your proposed solution?

Having an option for these two elements should eliminate the confusion created by the scenario where a user needs to wrap the elements in a Group block.

**Comment by carolinan** [comment]
Hi
This is a limitation with how the CSS for sticky position works.
An element is only sticky inside its parent, in this case, the group is *within* the header not within the body of the document, so it can only be sticky inside the height of the header.

This is already discussed in this [issue](https://github.com/WordPress/gutenberg/issues/47043).
