### ISSUE TITLE
Cover block MediaPlaceholder interferes with block inserter drag and drop

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#66422]
### Description

The cover block's `MediaPlaceholder` seems to prevent dragging and dropping blocks or patterns from the block inserter.

Additionally, it seems to interpret these blocks/patterns as files and shows incorrect messaging in the UI.

This issue may also happen for other blocks that use `MediaPlaceholder` but it's hard to say as I haven't tested widely.

### Step-by-step reproduction instructions

1. Insert a cover block
2. Open the inserter and try dragging a paragraph block over the placeholder
3. Observe it shows a message 'Drop files to upload' even though files aren't being dragged
4. Select a color from the placeholder
5. Try dragging a block or pattern from the inserter into the cover block (which is now not showing the placeholder and should accept blocks)
6. Observe the 'Drop files to upload' still shows and prevents inserting any blocks or patterns into the cover block

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/c7add642-492c-454f-b214-17c84dc315ff

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by getdave** [comment]
@ndiego @colorful-tones I believe this affects Zoom Out so we should gauge it's impact there and decide whether we need to try and resolve during this cycle.

**Comment by ndiego** [comment]
If we do include it in 6.7, we should ideally get it into RC2 so there is a bit of time for folks to test the fix. Can a fix be implemented in time? If so, I'm all for it.

**Comment by getdave** [comment]
Looking into this and documenting findings on this comment as I go...

- Cover block uses `packages/block-editor/src/components/media-placeholder/index.js`
- MediaPlaceholder renders a `<DropZone>` from `packages/components/src/drop-zone/index.tsx`.
https://github.com/WordPress/gutenberg/blob/8a2480a88e0bac2685b279ea377ae18d2523022f/packages/block-editor/src/components/media-placeholder/index.js#L377-L385
- DropZone accepts a handler function `onHTMLDrop` which is implemented as:
https://github.com/WordPress/gutenberg/blob/8a2480a88e0bac2685b279ea377ae18d2523022f/packages/block-editor/src/components/media-placeholder/index.js#L291-L294
- `handleBlocksDrop` handles dropped blocks by checking for Media and extracted that. It ignores anything else so no warning/notice would be shown if you try and drop a random block (e.g. `core/heading`).
https://github.com/WordPress/gutenberg/blob/8a2480a88e0bac2685b279ea377ae18d2523022f/packages/block-editor/src/components/media-placeholder/index.js#L248-L252
- `<DropZone>` uses the `useDropZone` for it's drop functionality. The `onDragEnter` handler is used to set state which shows/hides the blue message `Drop files to upload` on dragover:
https://github.com/WordPress/gutenberg/blob/8a2480a88e0bac2685b279ea377ae18d2523022f/packages/components/src/drop-zone/index.tsx#L106-L108
https://github.com/WordPress/gutenberg/blob/8a2480a88e0bac2685b279ea377ae18d2523022f/packages/components/src/drop-zone/index.tsx#L114-L123
https://github.com/WordPress/gutenberg/blob/8a2480a88e0bac2685b279ea377ae18d2523022f/packages/components/src/drop-zone/index.tsx#L133-L135
- The dragged blocks are handled here
https://github.com/WordPress/gutenberg/blob/6347583a290531b9c7ae8ffde62f51368843f998/packages/block-editor/src/components/inserter-draggable-blocks/index.js#L20

## Suggestion

We could conditionalise the `label` here based on the type of data being dragged over the drop zone. 

However it looks like browser deliberately disable the ability to access the data about the type of "thing" being dragged until it's actually dropped. This is a security feature so I don't think there's a way to tell what got dragged unless we move that to state and track manually 🤔 

Moreover, as the Cover block doesn't accept blocks but only images, we should conditionalise the label to be relevant only to images.

~However, it looks as though we'd have to do some work to distinguish blocks from just "any old HTML" if we wanted to show a better message (e.g. `Drop blocks`).~

**Comment by getdave** [comment]
@kevin940726 @ndiego @colorful-tones I can't see this being resolved in time for RC3 tomorrow. I'm minded to punt to 6.8 cycle. We should fix but there are lots of elements to consider here which I wouldn't feel comfortable rushing into 6.7.

**Comment by ndiego** [comment]
> @kevin940726 @ndiego @colorful-tones I can't see this being resolved in time for RC3 tomorrow. I'm minded to punt to 6.8 cycle. We should fix but there are lots of elements to consider here which I wouldn't feel comfortable rushing into 6.7.

Agreed.

**Comment by richtabor** [comment]
I'd expect the following: 

- I should only ever see the DropZone when dragging media over a cover block, not any other blocks. 
- When not in placeholder state, I can place blocks precisely within the cover block. Again, the DropZone should not be rendered. 

This below should not happen. Instead it should behave like dragging any other blocks into any other groups. 

https://github.com/user-attachments/assets/c0031ffd-9cbd-4aee-89a8-661e1f710e42

**Comment by getdave** [comment]
Agreed. It's something to fix.

**Comment by tellthemachines** [comment]
Looks like this was caused by #49673 adding a non-optional `onHTMLDrop` inside the media placeholder. Because anything coming from the inserter has its [type set to HTML](https://github.com/WordPress/gutenberg/blob/try/classic-stylebook/packages/block-editor/src/components/inserter-draggable-blocks/index.js#L65), the placeholder always shows. 

One way to fix this is by creating an additional dataTransfer type that is exclusive to media, and changing the media placeholder drop handler to handle that one type only. I'll have a play with this and see if it's viable!
