### ISSUE TITLE
Button: Add Custom Hover Color Options

### ISSUE THREAD

**Issue by pitamdey** [WordPress/gutenberg#66427]
## What problem does this address?
In the Button Block, I can see there is a default hover effect on the button, but can we add more color options to customize the hover color of the button?

## What is your proposed solution?
Add color settings in the Inspector panel for customizing button hover effects.

**Comment by carolinan** [comment]
Hi, this is already discussed in this [issue](https://github.com/WordPress/gutenberg/issues/38277).
