### ISSUE TITLE
Page Blank : AH01797: client denied by server configuration

### ISSUE THREAD

**Issue by walisonjose** [WordPress/gutenberg#6643]
Good afternoon people.
I'm trying to run the Gutenberg Plugin and the moment I activate the plugin and having add a new post the page goes blank. Browsing the server logs I came across the following error:

AH01797: client denied by server configuration: /home/l3p/apache_sites/tainacan.medialab.ufg.br/web/wp-content/plugins/gutenberg/data/build/index.js, referer: http://tainacan.medialab.ufg.br/wp-admin/post-new.php

Setting up my environment:
  Apache web server 2.4, with module suPHP enabled and Wordpress with the latest version.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by pento** [comment]
Thank you for the report, @walisonjose!

This error is caused by your Apache configuration blocking access to the `...gutenberg/data/build/index.js` file. I would advise checking your apache conf files, as well as any .htaccess files, for access control settings with `Deny from all` in them.

If you're not sure how to do this, please contact your web host for further assistance, as it depends heavily upon how your server is configured.

**Comment by walisonjose** [comment]
Thanks for your help @pento!  So I'm running the site in a subdomain type: http://tainacan.medialab.ufg.br using fastcgi. The site's .htaccess file is as follows.

`RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
RewriteRule . index.php [L]
`

And the virtual host file:

`<Directory /home/l3p/apache_sites/tainacan.medialab.ufg.br>
	#	AllowOverride None
		#		Require all denied
Options Indexes FollowSymLinks
AllowOverride All
Require all granted

		</Directory>

<VirtualHost *:80>

									DocumentRoot /home/l3p/apache_sites/tainacan.medialab.ufg.br/web
						
		ServerName tainacan.medialab.ufg.br
		ServerAlias www.tainacan.medialab.ufg.br
		ServerAdmin webmaster@tainacan.medialab.ufg.br

		ErrorLog /var/log/ispconfig/httpd/tainacan.medialab.ufg.br/error.log
        

		<Directory /home/l3p/apache_sites/tainacan.medialab.ufg.br/web>
				# Clear PHP settings of this website
				<FilesMatch ".+\.ph(p[345]?|t|tml|)$">
						SetHandler None
				</FilesMatch>
				Options +FollowSymLinks +Indexes
				AllowOverride All
								Require all granted
             		</Directory>
                    
		<Directory /home/l3p/apache_sites/clients/client1/web79/web>
				# Clear PHP settings of this website
				<FilesMatch ".+\.ph(p[345]?|t|tml)$">
						SetHandler None
				</FilesMatch>
				Options +FollowSymLinks
				AllowOverride All
								Require all granted
						</Directory>




		# suexec enabled
		<IfModule mod_suexec.c>
			SuexecUserGroup web79 client1
		</IfModule>
		# php as fast-cgi enabled
	# For config options see: http://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html
		<IfModule mod_fcgid.c>
				FcgidIdleTimeout 300
				FcgidProcessLifeTime 3600
				# FcgidMaxProcesses 1000
				FcgidMaxRequestsPerProcess 5000
				FcgidMinProcessesPerClass 0
				FcgidMaxProcessesPerClass 10
				FcgidConnectTimeout 3
				FcgidIOTimeout 600
				FcgidBusyTimeout 3600
				FcgidMaxRequestLen 1073741824
		</IfModule>
		<Directory /home/l3p/apache_sites/tainacan.medialab.ufg.br/web>
				<FilesMatch "\.php[345]?$">
					SetHandler fcgid-script
				</FilesMatch>
				FCGIWrapper /var/www/php-fcgi-scripts/web79/.php-fcgi-starter .php
				FCGIWrapper /var/www/php-fcgi-scripts/web79/.php-fcgi-starter .php3
				FCGIWrapper /var/www/php-fcgi-scripts/web79/.php-fcgi-starter .php4
				FCGIWrapper /var/www/php-fcgi-scripts/web79/.php-fcgi-starter .php5
				Options +ExecCGI
				AllowOverride All
								Require all granted
						</Directory>
		<Directory /home/l3p/apache_sites/clients/client1/web79/web>
				<FilesMatch "\.php[345]?$">
					SetHandler fcgid-script
				</FilesMatch>
				FCGIWrapper /var/www/php-fcgi-scripts/web79/.php-fcgi-starter .php
				FCGIWrapper /var/www/php-fcgi-scripts/web79/.php-fcgi-starter .php3
				FCGIWrapper /var/www/php-fcgi-scripts/web79/.php-fcgi-starter .php4
				FCGIWrapper /var/www/php-fcgi-scripts/web79/.php-fcgi-starter .php5
				Options +ExecCGI
				AllowOverride All
								Require all granted
						</Directory>



		# add support for apache mpm_itk
		<IfModule mpm_itk_module>
			AssignUserId web79 client1
		</IfModule>

		<IfModule mod_dav_fs.c>
		# Do not execute PHP files in webdav directory
			<Directory /home/l3p/apache_sites/clients/client1/web79/webdav>
				<ifModule mod_security2.c>
					SecRuleRemoveById 960015
					SecRuleRemoveById 960032
				</ifModule>
				<FilesMatch "\.ph(p3?|tml)$">
					SetHandler None
				</FilesMatch>
			</Directory>
			DavLockDB /home/l3p/apache_sites/clients/client1/web79/tmp/DavLock
			# DO NOT REMOVE THE COMMENTS!
			# IF YOU REMOVE THEM, WEBDAV WILL NOT WORK ANYMORE!
      # WEBDAV BEGIN
			# WEBDAV END
		</IfModule>

</VirtualHost>
`
I already tried several configurations but nothing frees the access .. Would you have any idea for this type of configuration?

**Comment by snathan9** [comment]
I had the following block in my Apache that caused similar error. 

```
<LocationMatch "/(data|conf|bin|inc|cache|vendor|file|store)/">
            Order allow,deny
            Deny from all
            Satisfy All
</LocationMatch>
```

This was included for another application running on the same domain.  Noticed in my error it said:
`AH01797: client denied by server configuration: /path/to/website/blog/wp-includes/js/dist/vendor/lodash.min.js`

The directory `vendor` was denied by apache. Removing it resolved the issue.
