### ISSUE TITLE
Zoom out: Keyboard shortcut not working on Windows

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#66449]
## What problem does this address?

#66400 added a shortcut to toggle zoom out, but the shortcut (`Ctrl+Shift+0`) for Windows OS may not be working.

I would appreciate it if you could test whether this is a problem only with my environment or a problem with the Windows OS.

@carolinan @alexstine @torounit I assume you are using Windows OS, so I would appreciate it if you could test it.

## What is your proposed solution?

If this is a problem on Windows OS, I would like to suggest a different key combination:

| Can we use this key as a zoom out shortcut? | Shortcut  | Description | Apps where this shortcut is used |
|--------|--------|--------|--------|
| ✅ | `Shift + 0` (`shift + 0`) | It works | https://defkey.com/what-means/shift-0 |
| ✅ | `Alt + 0` (`alt + 0`) | It works | https://defkey.com/what-means/alt-0 |
| ✅ | `Ctrl + Alt + 0` (`primaryAlt + 0`) | It works | https://defkey.com/what-means/alt-ctrl-0 |
| ✅ | `Ctrl + Shift + Alt + 0` (`secondary + 0`) | It works | https://defkey.com/what-means/ctrl-alt-shift-0 | 
| ❌ | `Ctrl + 0` (`primary + 0`) | At least in Chrome and Firefox this combination is not allowed as it is used to reset the browser zoom level. | - |
| ❌ | `Ctrl + Shift + 0` (`primaryShift + 0`) | This is the current shortcut, but it may not work as explained in this issue. | - | 
| ❌ | `Shift + Alt + 0` (`access + 0`) | This combination is not allowed because it converts a heading block into a paragraph block. | - | 

## Screenshots, screen recording, code snippet

In this video, you can see that the key down event (`event.key`) itself is not fired by the key combination.

- `0`: Key down event occurs and` evnet.key` is `0`.
- `Shift + 0`: Key down event occurs, but `evnet.key` is the alternate key, `)`.
- `Ctrl + 0`: Key down event occurs and `evnet.key` is `0`.
- `Shift + Ctrl + 0`: Key down event doesn't occur.

https://github.com/user-attachments/assets/28e3bad7-50fa-490e-b7c0-d7b74be5a006

**Comment by torounit** [comment]
I was able to reproduce the same issue in Firefox and Chrome on Windows.

I checked using https://w3c.github.io/uievents/tools/key-event-viewer.html and it seems that `shift + ctrl + 0` does not trigger a `keydown` event. But `keyup` fired.

Also, `shift + alt + ctrl + 0` / `shift + alt + ctrl + [1-9]` fires the `keydown` event.

**Comment by torounit** [comment]
The problem of `ctrl + shift + 0` not working seems to be a frequently observed problem in the Japanese environment of Windows.

https://jp.finalfantasyxiv.com/lodestone/character/8356239/blog/2960768/
https://nj-clucker.com/excel/ctrl-shift-0-not-working/
https://yashihei.hatenablog.com/entry/2019/03/18/235304

**Comment by t-hamano** [comment]
Thanks for looking into it. To reproduce this issue, I think both of the following conditions must be met:

- IME (Input method editor) is installed on the Windows OS. Whether IME is installed or not seems to depend on the OS language
- The OS shortcut for switching input languages ​​is enabled

Below is an English article that mentions this issue:

[Solved - Can't use Ctrl+Shift+0 (Windows has it) | Windows 8 Help Forums](https://www.eightforums.com/threads/cant-use-ctrl-shift-0-windows-has-it.22552/)

In any case, it is not guaranteed that switching the zoom out mode with the "Ctrl + Shift + 0" shortcut will always work on the Windows OS, so I think we need to assign a different shortcut.
