### ISSUE TITLE
hr HTML tags Breaking Paragraph Blocks and Classic Revisions Unless it's Inside <!-- wp:separator -->

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#66467]
### Description

This report originates from https://github.com/Automattic/wp-calypso/issues/94184 

There are two issues here:

Adding an HTML code that code that contains the <hr> code results in an eventually broken block. Block recovery attempts recovers what's before the <hr> tag but not what's after it.

If using classic revisions (wp-admin). If a revision contains that <hr> tag, all the content will be visible in the revisions view but anything under the tag will not be included in the restored version.

### Step-by-step reproduction instructions

Using Gutenberg, on any post.
Add a paragraph block and write anything - "Test"
Edit the paragraph block as HTML and add an <hr> to the end or anywhere on the paragraph, but inside the <p> followed by some text.
Click Edit visually.
You will get an Attempt Block Recovery button
Clicking it removes the <hr> tag and all that's after it

### Screenshots, screen recording, code snippet

https://d.pr/v/SbGOoZ (for some reason I can't embed this here)

### Environment info

- WordPress 6.6.2
- Gutenberg 19.5.0

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by carolinan** [comment]
Hi, I am finding it difficult to read the issue, did you mean for the separators to be visible, or for the text to include HTML tags? If you meant to show HTML tags, you can select the text and click on the code symbol in the toolbar to display it as code.

**Comment by carolinan** [comment]
If I am understanding the issue correctly, someone is trying to add a separator inside a paragraph block?
To my knowledge, it is not valid HTML to place an hr inside a paragraph.
To do this anyway, it would be more suitable to use the HTML block, where any HTML is permitted.

**Comment by mtias** [comment]
Agreed with @carolinan. If I'm reading the report correctly the only potential improvement would be for the "attempt recovery" to create two blocks with an hr after the paragraph or to offer to keep it as an html block.
