### ISSUE TITLE
Template part selecting and editing unavailable in “Write” mode

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#66463]
When the editor is set to “Design” mode, users can select template parts, which renders an “Edit” button allowing isolated editing of the template part. However, this functionality is unavailable in “Write” mode.

But if you enter the editor, turn on write mode, and open list view, template parts aren't visible in the list view nor can you edit them. I can replicate this with Twenty Twenty-Five, as well as other block themes with both 6.7 trunk & Gutenberg trunk on:

https://github.com/user-attachments/assets/50bfdd22-c85d-4138-be23-81ed0e307b33

**Comment by annezazu** [comment]
Noting that this includes if you switch between Write and Design modes. If you enter Write mode, it completely removes the ability to select template parts in list View even after switching to Design mode, even though you can select them. This is a demo with GB 19.6:

https://github.com/user-attachments/assets/d1d11ac5-59be-405d-9278-5aba7b8f38e7

**Comment by ntsekouras** [comment]
Hm.. I can't reproduce on trunk. @annezazu can you test in trunk too? I'll keep digging a bit more though to see if there was a PR that fixed that..

**Comment by xavier-lc** [comment]
I've been able to replicate what @annezazu describes on a simple edge site using v19.6.0:

1. Go to `/wp-admin/site-editor.php`
2. Click on `Templates`
3. Click on a template
4. The editor opens in `Write` mode
6. The header and footer are not shown on the List View
7. Switch to `Design` mode
8. Reload the page
9. Now I can interact with header/footer, and they are shown on the list view

https://github.com/user-attachments/assets/3daf53b4-2146-4dfc-994f-86d3e8847c6b

**Comment by xavier-lc** [comment]
Replicated as well on a simple site running v19.5.1:

https://github.com/user-attachments/assets/d6eb58f3-fadf-4c79-8e50-0af515b395a0

**Comment by xavier-lc** [comment]
I've downgraded my simple edge site to v19.4.0 and there I can see that the content of the list view changes when switching between write/design modes:

https://github.com/user-attachments/assets/519cb162-4c8e-4c71-a7d2-242d55e59f81

**Comment by ntsekouras** [comment]
I tried this in .com and actually reproduced. Could it be happening only there?

**Comment by xavier-lc** [comment]
This bug was introduced to dotcom with this PR: https://github.com/WordPress/gutenberg/pull/65945

**Comment by annezazu** [comment]
Thank you all for diving in! I see a PR is underway to address this.

**Comment by annezazu** [comment]
I'm going to reopen this since the original problem remains in this issue. Namely that you cannot view or edit template parts when Write mode is enabled:

https://github.com/user-attachments/assets/c5c51253-9674-4738-a499-7deb9474d1ac

To be clear, I'd expect to be able to both see the template parts in List View and then be able to edit the content of individual blocks. Part of the issue is that we need to ensure blocks like [Site Title are compatible with contentOnly](https://github.com/WordPress/gutenberg/issues/65778) and that we have a way to [edit/manage a menu with contentOnly](https://github.com/WordPress/gutenberg/issues/65699). With that said though, for now, we should be able to see the template parts in List View and have a contentOnly experience, even if there is a lock icon and you cannot select anything.

**Comment by richtabor** [comment]
> I tried this in .com and actually reproduced. Could it be happening only there?

Na, occurs universally.

**Comment by xavier-lc** [comment]
> I'm going to reopen this since the original problem remains in this issue. Namely that you cannot view or edit template parts when Write mode is enabled

I've traced the origin of this behavior back to https://github.com/WordPress/gutenberg/pull/65204. On the previous [commit](https://github.com/WordPress/gutenberg/commit/3910eab3e8db99a4e049a838549d908f22e2ac95) (PR https://github.com/WordPress/gutenberg/pull/65373) it's possible to view and edit template parts, even though at that point the `Write` mode was called `Edit`.

cc @annezazu @youknowriad

**Comment by talldan** [comment]
> I've traced the origin of this behavior back to https://github.com/WordPress/gutenberg/pull/65204. On the previous [commit](https://github.com/WordPress/gutenberg/commit/3910eab3e8db99a4e049a838549d908f22e2ac95) (PR https://github.com/WordPress/gutenberg/pull/65373) it's possible to view and edit template parts, even though at that point the Write mode was called Edit.

That's the PR that originally introduced Write Mode, so there's no regression of behavior. It's something that was never implemented.
