### ISSUE TITLE
TinyMCE editor events and transformation APIs

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#6648]
One of the plugins I help create is Tasty Links, which automatically adds links around specific keywords. For example, here is `Gutenberg` automatically linked to `wordpress.org/gutenberg`:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/36432/39783154-05b1715e-52c9-11e8-9c61-861e8f94d17d.png">

If you click on a Tasty Link, a custom preview toolbar (based on `editor.wp._createToolbar`) appears:

<img width="811" alt="image" src="https://user-images.githubusercontent.com/36432/39783338-8bd5e698-52c9-11e8-8537-4d9fc1f473c7.png">

_Notably_, this isn't the standard WordPress link UX. The previewed Tasty Links look like links because of a custom editor stylesheet. In reality, they're `<span>` stripped on save:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/36432/39783446-f476a1d8-52c9-11e8-8654-6f994cf9f34c.png">

If I click the "Remove" icon in the preview toolbar, then the `<span>` is replaced with a HTML comment that is persisted on save:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/36432/39783511-2b852514-52ca-11e8-9220-b0240bac6e2f.png">

[Here's the corresponding JavaScript](https://gist.github.com/danielbachhuber/7994605866299c57e2d9f9bac021f423) for my TinyMCE plugin.

In order to recreate the same Tasty Links UX in Gutenberg, I _think_ all I need is:

* Ability to bind to a click event within Gutenberg.
* `editor.dom` equivalent (which supports `select()`, `addClass()`, `removeClass()`, etc).

Related #4658

**Comment by danielbachhuber** [comment]
@azaozz @iseulde Could I get your thoughts on ^ when you have a moment?

**Comment by iseulde** [comment]
I'm not entirely sure what you're trying to create. So far I understand:

* You type some words.
* One keyword that has been typed should be recognised and wrapped in a link?
* The link should be editable? Or it it fixed?
* What does the span do? What should be output on the front-end?

**Comment by danielbachhuber** [comment]
> I'm not entirely sure what you're trying to create.

The product launched, so there's [more detail available here](https://www.wptasty.com/tasty-links). In a nutshell, the plugin automatically adds links around specific keywords on the frontend. But in the backend, rather than render the links themselves, the plugin creates a link-like UX around `<span>` in the editor.

Taking a step back towards Gutenberg, what seems to be missing are APIs equivalent to `TinyMCE.activeEditor` and `TinyMCE.dom.DOMUtils`.

Related #3688

**Comment by iseulde** [comment]
I'm hesitant to let plugins use TinyMCE APIs because this might all change. We'll have to create something here to would enable you to create a similar experience. How about adding the links in the content before it loads in the editor? Why does it have to be a `span`? Just trying to understand it better.

**Comment by danielbachhuber** [comment]
It has to be a `<span>` to avoid standard editor behavior around `<a>`. Specifically, if the `<span>` preview is removed:

![image](https://user-images.githubusercontent.com/36432/40010624-259eee70-575a-11e8-849e-63e4e7b2e17d.png)

Then a HTML comment is added:

![image](https://user-images.githubusercontent.com/36432/40010638-344086a0-575a-11e8-97fa-68b7dbaec48f.png)

> I'm hesitant to let plugins use TinyMCE APIs because this might all change.

I'm not suggesting we use TinyMCE APIs directly. A reasonable alternative would be to expose named Gutenberg APIs whose underlying implementation can change.

More so though, I'd love to get up to speed on any existing conversation that's been had on this topic.

**Comment by iseulde** [comment]
Okay. It would almost seem ideal if it followed the normal link behaviour where the link would be added on text input only. Then when the user removes it, it just would no longer show up. Might not be what you want though. Not sure atm how else this would be possible without a huge amount of code.

Related: #771.

**Comment by mtias** [comment]
Closing to focus on #3688.

**Comment by gziolo** [comment]
We have just landed Format API with #10068. It allows registering any format you need. We are still working on a way to give better control which control can be displayed for a given block and documentation. It should be all ready early next week.

I think that most of the functionality described here can be recreated with new API, I'm only not quite sure about HTML comment.

**Comment by iseulde** [comment]
@danielbachhuber you can now target it with `tagName: 'span'` and `className: 'tasty-link'`. Do you need anything else?

**Comment by danielbachhuber** [comment]
@iseulde Should be good now, thanks!
