### ISSUE TITLE
Interactivity API - Random directive parsing errors v19.5.0

### ISSUE THREAD

**Issue by poof86** [WordPress/gutenberg#66490]
### Description

After updating to Gutenberg 19.5.0 from 19.4.0 I get errors when elements with directives get parsed.
The errors disappear when I downgrade back to 19.4.0

I get errors like:
directives.tsx:574 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map') 
for elements that have the data-wp-each-child attribute

and the error:
directives.tsx:480 Uncaught TypeError: Cannot use 'in' operator to search for 'hidden' in null
for elements that have the data-wp-bind--hidden attribute set

What changed for this to happen?

### Step-by-step reproduction instructions

Created a custom block with a render.php where these directives are used.
The viewScriptModule file view.js uses the following assets.php
`<?php return array('dependencies' => array('@wordpress/interactivity', array('id' => '@wordpress/interactivity-router', 'import' => 'dynamic')), 'version' => 'e60eae253fd57d3f', 'type' => 'module');`
on page load I now get these errors why I didn't with 19.4.0

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by poof86** [comment]
It seems that v19.6.0 fixes this bug

Was it because the delayed hydration was added?

Thanks!

**Comment by michalczaplinski** [comment]
Hi @poof86 ! Apologies for the late reply. 

I believe this might have been caused by https://github.com/WordPress/gutenberg/issues/66691 which was fixed in https://github.com/WordPress/gutenberg/pull/66772 that just shipped in `19.6`. Glad that solved your issue!
