### ISSUE TITLE
A typo in a string from WordPress version 6.7

### ISSUE THREAD

**Issue by isaeedam-ir** [WordPress/gutenberg#66513]
Hi! I think the string that has the link below has a typo, it says "**pane**" instead of "**panel**". Do you think so too?
[https://build.trac.wordpress.org/browser/branches/6.7/wp-includes/js/dist/edit-post.js?marks=3075#L3075](url)

**Comment by t-hamano** [comment]
Thanks for the report. This string was corrected by #66502.
