### ISSUE TITLE
Style book: creating landing page view

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#66517]
## What

Create a new "landing page" view for the style book to display common theme blocks (and one day [patterns](https://github.com/WordPress/gutenberg/issues/53437) 🤷🏻).

The requirements as stated in the parent issue are:

> A “Landing” tab that would serve as the landing page of the stylebook: a page displaying only blocks that more commonly and immediately are able to represent the theme.

> The landing page would be useful for the current iteration of the Site View, which does not currently feature tabs. It serves as a quick glanceable "poster view" for the site style guide:

![poster-view](https://github.com/WordPress/gutenberg/assets/1204802/395e33fd-935f-4bb3-9b23-17289670f769)

## How 

It will very much depend on the outcome of discussions in:

- https://github.com/WordPress/gutenberg/issues/66376

There are a few open questions:

- What is the current use case for this view? When and where would it appear?
- What should appear there? What does "more commonly and immediately are able to represent the theme" mean?
- Can themes add their own blocks/patterns to the landing page? If so how? There would have be a special category or register function. For the former, blocks only have one category as a string. Should blocks/patterns accept subcategories, or an array of categories or some other flag?
    -  Assuming "yes" to the above question, should theme patterns/blocks take precedence over Core's? How?
- How would the landing page handle classic themes, if at all?

## Considerations

It's not yet certain how the landing view, which would presumably NOT contain a list of all blocks, would interact with a global styles panel in:

- https://github.com/WordPress/gutenberg/pull/65619

Perhaps the canvas's content could be dynamic, driven by navigation routes. For example, if the landing page is active and the user clicks on a block style, the canvas would load that block style.

## Related

- https://github.com/WordPress/gutenberg/issues/66376
- https://github.com/WordPress/gutenberg/pull/65619

**Comment by tellthemachines** [comment]
> It's not yet certain how the landing view, which would presumable NOT contain a list of all blocks, would interact with a global styles panel in #65619 

I think the landing view would be ideal as a first glimpse of the stylebook when opening global styles! But given that #65619 also makes it possible to scroll specific blocks into view when looking at their global styles, we'd probably need a few different screens to switch between in that view.
