### ISSUE TITLE
WordPress 6.7: Unlinked contributors

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#66537]
While compiling a list of contributors that helped with the upcoming WordPress 6.7 release using the project's "Prop" script, it was determined that there are still ~80 contributors that have not linked their WordPress.org and GitHub accounts. Contributions come in many shapes and sizes, some examples include opening issues or bug reports, providing testing feedback, etc..

In the WordPress project, all credit given out must be attached to a WordPress.org account. After creating a W.org account (or logging in to your preexisting one), you [can link your GitHub account following these steps in the Core Handbook](https://make.wordpress.org/core/handbook/tutorials/linking-your-github-and-w-org-profiles/).

If you are receiving a ping, it's because you contributed to an issue or pull request on this repository that will be included in the upcoming WP 6.7 release. Please link your accounts so that your work can be celebrated. Conversation for this issue will be locked to avoid any unnecessary noise. Responding is not required since rerunning the script will automatically detect any new connections that have been made since.

Previously: #63064.

@jarekmorawski, @laurelfulford, @alaczek, @nick-a8c, @rohitmathur-7, @aduth, @oryfoxer, @smerriman, @ericdye, @autumnfjeld, @dannyreaktiv, @finitelydope, @MikeB8s, @sophiegyo, @louwie17, @greenworld, @75th, @vicobot-0815, @realthemes, @its-danny, @michaelpick, @rdoughbs, @rithik56, @ktmn, @jawadmalikdev, @MadGanGithub, @lukasbesch, @Kuuuzya, @La-Geek, @janpfeil, @ssang, @digitalex11, @designsimply, @lex127, @audiovisuel-uqam, @eballeste, @jenilk, @zhitaryksergey, @christianMiguez, @karan4official, @harlet, @randomburner, @RCNeil, @gabrieltogan, @porg, @bradhogan, @DivyanshVinayak23, @wp-seopress, @mleathem, @sergiu-radu.

**Comment by desrosj** [comment]
@Sirjazzfeetz, @albanyacademy, @tofumatt, @StyleShit, @agapetry, @iamibrahimriaz, @alessandrotesoro, @brentjett, @webexpr-dhenriet, @bogiii, @joehoyle, @Zealth57, @sahiladit, @ametaplus, @peXed, @graylaurenm, @fabiorubioglio, @convolutedkdlkf, @saulyz, @erikiva, @scrobbleme, @ppolo99, @smithjw1, @dereksmart, @fcenteno, @keenode, @shashwatahalder01, @gyurmey2, @Amir-A-M, @akashdhawade1991, @gemkev, @bridgetwes, @17cliu, @paolopiaggio, @paulopmt1.

**Comment by jeffpaul** [comment]
For the folks here, if you've not connected your GitHub.com and WordPress.org accounts it would be great to do so via the link in the original issue description above (and/or share your WordPress.org username so we can ensure its included in the 6.7 release)... thanks!
