### ISSUE TITLE
Limit block count pr post type

### ISSUE THREAD

**Issue by mfolkeseth** [WordPress/gutenberg#6654]
## Issue Overview
Is there a way to restrict block count pr. post type? Let's say I create a custom post type, but I want that post type to be restricted to containing only a single block.

**Comment by gziolo** [comment]
> Is there a way to restrict block count pr. post type? 

Not as of today.

> Let's say I create a custom post type, but I want that post type to be restricted to containing only a single block.

However, you can achieve what you describe by using template locking: https://wordpress.org/gutenberg/handbook/templates/#locking.

**Comment by mfolkeseth** [comment]
Not exactly. I want the post to contain only one block, but users choose the block type. Or maybe I'm missing something?

**Comment by gziolo** [comment]
It might be possible in the future when we extend all the work on templates. @mtias, any thoughts on this one?
