### ISSUE TITLE
Theme translations not working after "Internationalization improvements in 6.7"

### ISSUE THREAD

**Issue by tigriweb** [WordPress/gutenberg#66547]
### Description

Hi,

After the [i18n improvements in WordPress 6.7](https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/), standard theme i18n strings are not working.

I’ve tested this on FSE patterns (404 page, footer) and in functions.php.

### Step-by-step reproduction instructions

1) Create an FSE pattern for the 404 page with the i18n string: `<?php echo esc_attr_x( 'Page not found', '404 error page', 'your-theme-name' ); ?>`
2) Create a `/languages/pl_PL.mo` file containing the translated data.
3) Load the theme text domain:
```
add_action( 'after_setup_theme', function() {
	load_theme_textdomain( 'your-theme-name', get_template_directory() . '/languages' );
} );
```
3) Set the `pl_PL` language in wp-admin.
4) Go to the 404 page. The string does not display the translation.
5) You can also test the following code in `functions.php`:
```
echo esc_attr_x( 'Page not found', '404 error page', 'your-theme-name' );

add_action( 'init', function() {
	echo esc_attr_x( 'Page not found', '404 error page', 'your-theme-name' );
} );
```

### Environment info

WordPress 6.7-RC1, 6.8.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [x] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by t-hamano** [comment]
Thanks for the report. I was able to reproduce this issue too.

To test this issue, I created a repository: https://github.com/t-hamano/translate-test

The `load_theme_textdomain()` function seems to return true, but the text is not translated at all.

| WordPress 6.6.2 | WordPRess 6.7 RC2 |
|--------|--------|
| ![Image](https://github.com/user-attachments/assets/1b5b2831-eaaf-4340-97e2-af7d9dda3475) | ![Image](https://github.com/user-attachments/assets/a2326b09-d2eb-40ac-aef4-77c3510f3d87) |
| ![Image](https://github.com/user-attachments/assets/5a5415da-a917-4b84-baf4-b93c37e52e4d) | ![Image](https://github.com/user-attachments/assets/8c5f2563-0328-4b60-9e97-d0fb74f96867) |

**Comment by swissspidy** [comment]
This is better reported over at https://core.trac.wordpress.org/ as it doesn't seem to be an editor issue.

**Comment by t-hamano** [comment]
Core ticket: https://core.trac.wordpress.org/ticket/62337

**Comment by swissspidy** [comment]
Thanks, closing in favor of https://core.trac.wordpress.org/ticket/62337 then

**Comment by swissspidy** [comment]
This is a consequence of https://core.trac.wordpress.org/changeset/59157. If calling `load_*_textdomain()` _after_ WordPress has already attempted just-in-time loading, nothing happens. For themes, just-in-time loading is triggered by `_register_theme_block_patterns` (which is hooked to `init` at prio 10).

So the code snippet above with `after_setup_theme` should actually work 🤔 

Anyhow, please follow https://core.trac.wordpress.org/ticket/62337 for updates.
