### ISSUE TITLE
Create a selector for wp:action targetSchema flags

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#6655]
From https://github.com/WordPress/gutenberg/pull/6630#discussion_r186942846

> I realised I forgot to comment on this in #6529. I think it'd be useful to create a selector for retrieving this data. Something like `select( 'core/editor' ).getPostLink( 'wp:action-assign-author' )`, or maybe `select( 'core/editor' ).getPostActionFlag( 'assign-author' )`. Neither of those names are good, but you get the idea.

We should figure out what we want to name this, and introduce the selector.

**Comment by designsimply** [comment]
So the selector would be for retrieving whether the current user can assign an author for a post or not?

I looked at other similarly named things for inspiration: https://github.com/WordPress/gutenberg/search?q=%22select%28+%27core%2Feditor%27+%29.get%22&type=Code

How about `select( 'core/editor' ).getPostAttribute( 'can-assign-author' )` ?

**Comment by danielbachhuber** [comment]
Closing. This is pretty low priority and not a particularly valuable enhancement.
