### ISSUE TITLE
Pages data view: Clicking the featured image in grid layout no longer opens the editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#66588]
On the Patterns and Templates data views, clicking the thumbnail in grid layout opens the editor. This used to be the case in the Pages data view too, but is no longer the case.

cc @oandregal @ntsekouras @youknowriad

**Comment by jameskoster** [comment]
cc @gigitux in case this is related to https://github.com/WordPress/gutenberg/pull/64496

**Comment by gigitux** [comment]
We are aware of this! The behavior will be restored when https://github.com/WordPress/gutenberg/pull/66365 is merged. Given that it is a regression, should we prioritize it?

**Comment by jameskoster** [comment]
@gigitux I think it depends whether the bug is going to be in 6.7 or not as things stand. If it is, then we should probably prioritise :)

**Comment by gigitux** [comment]
According to [this page](https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/), the Gutenberg version included in Core is 19.3.

https://github.com/WordPress/gutenberg/pull/64496 has been included in Gutenberg 19.6. Also, I checked WordPress Playground with WordPress 6.7-RC2 and the regression isn't reproducible.

**Comment by youknowriad** [comment]
Yes, I think this should be given more priority. I do think the "onFocusItem" or "onClickItem" or something like that is the right solution for it. And we need to come up with the right heuristics:

 - Click media fields in grid triggers `onClickItem` is a good one.
 - Click primary fields in table should probably trigger `onClickItem` which also means we should remove the "clicking" behavior from the fields themselves. 
- Maybe there are other primary/media fields that should have this behavior in other layouts.

It's fine to start small though and only implement it for the current regression and iterate/expand separately. (Which is clicking media items in grid views)
