### ISSUE TITLE
Is the Gutenberg plugin not deactivated on WordPress 5.0?

### ISSUE THREAD

**Issue by SeanDS** [WordPress/gutenberg#6659]
## Issue Overview
Scanning the `gutenberg_pre_init` function, the current WordPress version is [only checked to see if it is older than 4.9](https://github.com/WordPress/gutenberg/blob/16d6a0117171be37dc03ec2535cbbdccecbe29f7/gutenberg.php#L123), in which case the plugin deactivates due to incompatibility. Should there not also be a check for versions >= 5.0, since by that point Gutenberg will have been merged into WordPress Core? I can imagine lots of people will have installed an early version of the Gutenberg plugin which doesn't detect version 5.0, and won't have updated it by the time WordPress 5.0 is released, potentially creating a huge mess with two almost identical sets of code hooking into the same parts of the code trying to provide the same tools.

Apologies if this is something that the developers are already aware of, or is already covered somehow in the code. I thought I'd report it anyway just to be safe.

## Steps to Reproduce (for bugs)
I don't think this is causing problems yet, because (as far as I am aware) Gutenberg has not been merged into the WordPress 5.0 development branch yet.

## Expected Behavior

Gutenberg plugin will deactivate itself if it detects WordPress 5.0 is being run, since WordPress 5.0 will have had the plugin code merged into the core and so this plugin will no longer be necessary.

## Current Behavior
This will probably not be a problem until Gutenberg is merged into WordPress 5.0, but it's worth getting the check in early so that most users who have the plugin installed won't have any problems later.

## Possible Solution
Check not only for versions < 4.9, but also for version >= 5.0, and if true, deactivate the plugin. It might also be useful to check for the presence of some flag to determine if someone is testing this plugin against the current 5.0 branch **without** the Gutenberg code merged in.

**Comment by karmatosed** [comment]
Hi @SeanDS what happens in 5.0 hasn't been decided, so thank you for suggesting here. As you say there are no issues right now because of the current way this is setup. That all said during the merge and path to 5.0 things will be worked out and discussed. It will absolutely have a lot of work done on not having clashes though.

For now, I am going to close this as it's not something we need to do and the path to 5.0 may take many different routes. Thanks for being observant and looking forward.
