### ISSUE TITLE
Add option to Status & Visibility?

### ISSUE THREAD

**Issue by jsmoriss** [WordPress/gutenberg#6661]
I've been unable to find information on how to add an option to the Status & Visibility box. Is this possible? And if not, will it be possible? :)

**Comment by greatislander** [comment]
See https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/action-post-submitbox.md.

**Comment by youknowriad** [comment]
Duplicate of #6299 closed in #6300

**Comment by jsmoriss** [comment]
Oh, wow, well that's a pretty big problem. :) Hopefully https://github.com/WordPress/gutenberg/issues/6299 will be resolved soon. Thanks! :)

**Comment by youknowriad** [comment]
Oh sorry my message was not clear enough, it's already resolved https://github.com/ryanwelcher/gutenberg/blob/8efddae270b3cb451b39568fefac87e50f5097e7/edit-post/README.md#pluginpoststatusinfo

**Comment by jsmoriss** [comment]
FYI - There seems to be a syntax error in that example...

https://github.com/WordPress/gutenberg/issues/6992
