### ISSUE TITLE
Consider allowing dynamic content from meta fields to be inserted inline in Paragraph, Heading, List, etc.

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6665]
## The issue and how existing page builders have solved it
Currently, there is no easy way to have inline dynamic content sourced from custom (or even non-custom) fields in Gutenberg.

Somewhat recently, Beaver Builder has gained the ability (through the official Beaver Themer extension) to easily insert dynamic content into any text or image field from any meta field, including (but not limited to) featured image, post title, post date, post modified date, excerpt, archive, site title, and any custom fields.

I highly recommend checking this feature out and playing around with in the demo to see how it works. It is quite powerful.
https://www.wpbeaverbuilder.com/beaver-themer/

Elementor Pro has also gained this functionality recently, albeit slightly less powerful: you can only have the dynamic content take up the entire text field, whereas Beaver Themer allows you to use it mixed in with standard static content by using the <kbd><samp>Insert</samp></kbd> button instead of <kbd><samp>Connect</samp></kbd>. (The <kbd><samp>Insert</samp></kbd> button uses a shortcode.)
https://elementor.com/introducing-theme-builder/

Divi is also working on implementing this same functionality in pretty much the same way as Elementor Pro:
https://www.elegantthemes.com/blog/theme-sneak-peeks/divi-feature-sneak-peek-dynamic-content

## Approaching the issue in Gutenberg
Technically, you could just use some kind of shortcodes plugin to add dynamic content from fields into text inputs. However, Gutenberg is aiming to replace most, if not all shortcode usage. Therefore, I think that Gutenberg should have some kind of system in place for inserting inline (or in some cases not inline, but still within an existing block) dynamic content sourced from fields into text inputs (and possibly also image inputs).

Some example use cases:

- A user could create a shared block made from a Paragraph block containing the phrase “This post was posted on <var>XX:XX</var>”, where <var>XX:XX</var> would be the publish date of the post. The user would be able to easily modify this block to change the wording and position of the time in the sentence, without having to create a custom block or write any code.
- A user could insert an image block and have it show the featured image of the post. This could eliminate the need for a Featured Image block. (Though there is nothing stopping it from existing in addition to the ability to use featured images in any image input.)
- In the future when Gutenberg is used outside of `post_content`, the Heading block could be re-used for the Post Title without having to create a dedicated Post Title block.

As for how to implement it, the first idea that comes to mind is doing it through the inline block/token system proposed by #2043. The only flaw I can think of at the moment to doing it through that system is that it does not provide a way for the dynamic content to be used in inspector inputs that are not shown outside of the sidebar.

Assuming I understand the inline block/token system, it seems like it could also allow for things that none of the page builders do right now, like an inline block/token that lists the categories, tags, or other taxonomical terms of a post. There are definitely some exciting possibilities to look into there.

## Related Issues and/or PRs
#1851
#2043
#6663

**Comment by rchipka** [comment]
Also check out the "slug" concept on [this issue](https://github.com/WordPress/gutenberg/issues/6663)

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @SuperGeniusZeb. I've filed this to the `Ideas` project for future consideration.

**Comment by aristath** [comment]
> I've filed this to the Ideas project for future consideration.

I've seen this mentioned multiple times so I'm just curious... Where is this `Ideas` project? I can't find anything on github 🤔

**Comment by danielbachhuber** [comment]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/36432/39999327-af5243a0-573d-11e8-96d3-244cf565f498.png">

And https://github.com/WordPress/gutenberg/projects/8

**Comment by aristath** [comment]
Ah gotcha! Thanks 👍

**Comment by gravnetic** [comment]
How come this issue was put into a project and closed, and then that project was closed?  That seems like a really unusual way to concatenate issues.

**Comment by ZebulanStanphill** [comment]
I've been told this sort of thing is now possible to implement with the [Format API](https://github.com/WordPress/gutenberg/tree/master/docs/designers-developers/developers/tutorials/format-api). Not exactly sure _how_ to use it to do this, but in case anyone is wondering if it's possible with the existing APIs, this should help.

**Comment by ZebulanStanphill** [comment]
This issue was originally intended to suggest that a visual UI be added for inserting inline dynamic content, but in hindsight, I think that's something best left to plugins, at least until there's noticeable demand for the feature. The upcoming full site editing and related blocks will likely provide the functionality most users are looking for. Since it is technically possible for plugins to implement this now, I'm leaving this issue closed.

**Comment by ZebulanStanphill** [comment]
Actually, it looks like it might be a bit difficult to implement this? See #18490 for continued discussion.
