### ISSUE TITLE
Zoom out: Pattern inserter always forces iframe editor

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#66671]
### Description

When the Patterns tab is selected, the zoom out mode is enabled via [the `useZoomOut` hook](https://github.com/WordPress/gutenberg/blob/86ca73a86541f0a1a16e30a906ebed3ba2ad66d2/packages/block-editor/src/components/inserter/menu.js#L83-L85) and the editor behaves as an iframe. On the other hand, if the editor is NOT an iframe, the zoom out toggle is not displayed (https://github.com/WordPress/gutenberg/pull/65452).

This inconsistency leads to unintended behavior.

### Step-by-step reproduction instructions

To make the [`useShouldIframe` hook return false](https://github.com/WordPress/gutenberg/blob/86ca73a86541f0a1a16e30a906ebed3ba2ad66d2/packages/edit-post/src/components/layout/use-should-iframe.js#L43-L47), do the following:
  - Activate the classic theme.
  - Activate a plugin that includes the v2 block (e.g. [CoBlocks](https://wordpress.org/plugins/coblocks/)).

---

- Open the post editor.
- The editor should be running as a non-iframe.
- Enable custom fields and refresh your browser. Ensure the meta box is legacy (not resizable).
- Select the Patterns tab from the main inserter.
  - 🤔 You should see the zoom out toggle button in the header.
  - 🤔 The meta box should change to resizable.
- Click the zoom out toggle button in the header.
  - 🤔 The zoom out button should disappear.
  - 🤔 The meta box should change to legacy.

## What is your proposed solution?

Here are my suggested approach for the non-iframe editor:

- For WP 6.7: Don't enable zoom out mode when accessing the Patterns tab.
- For Gutenberg (WP 6.8): Enable zoom out mode in the non-iframe editor, i.e. displays the zoom out toggle button in the header and also provides the zoom out shortcut.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/5c345b3a-54d9-4fa7-ac71-25a76c86e38a

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [x] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by annezazu** [comment]
@ellatrix  curious for your thoughts here

**Comment by t-hamano** [comment]
This may need to be discussed in more detail in #66718.

**Comment by ndiego** [comment]
As this issue is still in discussion with https://github.com/WordPress/gutenberg/issues/66718 and the fact that https://github.com/WordPress/gutenberg/pull/66742 has been merged, I am going to remove this from the 6.7 project board. This was also reviewed in [Slack](https://wordpress.slack.com/archives/C07BTF54N68/p1730885842754079).

**Comment by ellatrix** [comment]
In this case I think we should:

* Not put the content in zoom out when you open patterns.
* But maybe leave it as an open in the toolbar, which will render the zoom-out view in an iframe.

Zoom-out should always be iframed, it's a new mode and we don't care about back compat.
