### ISSUE TITLE
Site Editor Uses Incorrect Template

### ISSUE THREAD

**Issue by mdawaffe** [WordPress/gutenberg#66687]
### Description

Since #66579, the Site Editor has changed which template it uses.

In current trunk, the Site Editor uses the template from `/wp/v2/templates/lookup&slug=front-page&_locale=user`.

In Gutenberg 19.5.1, the Site Editor uses the template from `/wp/v2/templates/lookup&slug=page-{$page_slug}&_locale=user`.

Depending on the theme, the templates returned by those two requests can be very different.

### Step-by-step reproduction instructions

1. Create a page.
2. Set that page to be your site's homepage (`page_on_front`).
3. Switch theme to Twenty Twenty-Four.
4. Go to `wp-admin/site-editor.php?canvas=edit`
   * In Gutenberg 19.5.1, you'll see the title and contents of the page you created in step 1. In the Page settings sidebar, note that it's using the "Pages" template (or whatever template you gave it.)
   * In current trunk, you'll see the Twentytwenty-Four default homepage. In the Page settings sidebar, note that it's using the "Blog Home" template.

### Screenshots, screen recording, code snippet

Reading Settings:
<img src="https://github.com/user-attachments/assets/3ae4239e-0850-4df1-820a-d443a66d4990" alt="Reading Settings" width="40%">

|19.5.1|Trunk|
|-----|------|
|![Gutenberg 19.5.1](https://github.com/user-attachments/assets/6a84765a-d413-4038-b232-ba876379fa74)|![Current Trunk](https://github.com/user-attachments/assets/ac7119ec-37c1-4fd8-8cb5-c0bff2417fa6)|

### Environment info

WordPress: 6.8-alpha-59335
Gutenberg: 49c3bf9b8791546231826feeff8681ed3d9ab153 (behavior changed in #66579)
Theme: Twenty Twenty-Four

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [x] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by draganescu** [comment]
I can confirm this. On my dev env the reading settings are:

- homepage - some page
- posts page - some other page

Opening the site editor I see "some page" which is the homepage rendered with the block home template. However opening the "some page" page in the post editor I see the page correctly rendered with the pages template.

Also the swap template button doesn't work anymore in the site editor.

**Comment by ellatrix** [comment]
Thanks for the report!

Trying to understand the problem better. I have Twenty-Twenty Four enabled. I go to Reading setting and I set the front page to some random page. I go to the front page (actual, not Site Editor) and this is what I see (not the page I set):

![Image](https://github.com/user-attachments/assets/532de073-3d5a-4cc8-9e7e-7d7062127d61)

In the Site Editor I see the same. So my question is: is the front-end of the site also wrong? Am I testing this wrong?

**Comment by mdawaffe** [comment]
Hm - that's not the behavior I see. I see the `page_on_front` page on the front-end as expected, but not in the site editor. Here's what I did:

1. `npm run wp-env destroy`
2. `npm run wp-env start`
3. `npm run wp-env run -- cli -- wp theme activate twentytwentyfour`
4. `npm run wp-env run -- cli -- wp option set show_on_front page`
5. `npm run wp-env run -- cli -- wp option set page_on_front 2 # ID=2 is the default Sample Page` 
6. Go to the site: `http:/site-url/`. See the default "Sample Page" as expected.
   <img src="https://github.com/user-attachments/assets/2449c740-e51f-4a12-b609-114b7b77da56" width="400" />
7. Go to the site editor: `/wp-admin/site-editor.php?canvas=edit`. See the Twenty Twenty-Four default homepage (incorrect).
   <img src="https://github.com/user-attachments/assets/f5dc83eb-4810-44d7-a508-993b46719324" width="600" />
8. Go to the page editor: `/wp-admin/post.php?post=2&action=edit`. See the contents of "Sample Page" as expected.
   <img src="https://github.com/user-attachments/assets/958306de-c3cf-4451-b28e-4f82b37c2831" width="600" />

**Comment by ntsekouras** [comment]
Yeah, it's a regression from https://github.com/WordPress/gutenberg/pull/66579.

**Comment by ellatrix** [comment]
Ok, thanks, I tried with a fresh install and it's indeed setting the sample page. Something must be wrong with my install. Looking into the issue.

**Comment by ellatrix** [comment]
Should be fixed in #66739.
