### ISSUE TITLE
Buttons: wrong text color on focus

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6668]
Both Publish buttons have a wrong color when focused (i.e. when navigating with the keyboard and they get focus). Probably related to recent work on buttons. /Cc @jasmussen 

<img width="425" alt="screen shot 2018-05-09 at 23 38 44" src="https://user-images.githubusercontent.com/1682452/39841448-093cadf0-53e3-11e8-9a1a-99a3da82cbe8.png">

<img width="358" alt="screen shot 2018-05-09 at 23 42 50" src="https://user-images.githubusercontent.com/1682452/39841449-0957abc8-53e3-11e8-8b3c-ec48993567f3.png">

Worth also noting there's a great variety of focus styles now, not sure if that's intentional. See the buttons below (all with forced focus via browser's dev tools):

<img width="395" alt="screen shot 2018-05-09 at 23 47 36" src="https://user-images.githubusercontent.com/1682452/39841603-986be9fa-53e3-11e8-8011-552f9356cb98.png">

**Comment by afercia** [comment]
Seems this is not limited to the Publish buttons:

<img width="310" alt="screen shot 2018-05-11 at 15 37 49" src="https://user-images.githubusercontent.com/1682452/39998164-8dac4852-5785-11e8-985e-d6190b7e8689.png">

**Comment by nfmohit** [comment]
> Seems this is not limited to the Publish buttons:

@afercia Just FYI, #6714 should address those and any other buttons having the `.button-primary` class as well.

Screenshot:
![gutenberg-6729](https://user-images.githubusercontent.com/20284937/40013400-41eeeff6-57cf-11e8-9b0b-e6fcd7ba2096.png)

Thank you!

**Comment by jasmussen** [comment]
I've noticed this too, and I've promised to help @youknowriad with https://github.com/WordPress/gutenberg/pull/6562, which should fix this. So I've assigned myself. However I've got a bit too much on my plate these days, so I can't promise I'll make it for 2.9, so if anyone else would like to patch this in the mean time, they should feel free to.
