### ISSUE TITLE
Improvements for the keyboard shortcuts in tooltips

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6669]
The new keyboard shortcuts shown in the tooltips of the top toolbar buttons (see #6605) are a good idea to expose the available shortcuts. Tooltips usually open at the top of the related controls:

<img width="377" alt="screen shot 2018-05-09 at 23 51 39" src="https://user-images.githubusercontent.com/1682452/39841936-d9da31d4-53e4-11e8-8445-66e95b12358b.png">

Now, when quickly hovering on these buttons (e.g. from Add block to Undo / Redo) or when navigating with the keyboard, the "jump effect" of the tooltip that sometimes opens at the top, sometimes at the bottom, is a bit confusing and distracting.

<img width="336" alt="screen shot 2018-05-09 at 23 51 41" src="https://user-images.githubusercontent.com/1682452/39842999-540f9558-53e9-11e8-8923-67a7242cf449.png">

When the shortcut text is longer than the tooltip text, the latter is misaligned (should be centered?):

<img width="195" alt="screen shot 2018-05-10 at 00 25 43" src="https://user-images.githubusercontent.com/1682452/39843000-542de68e-53e9-11e8-8ed6-d4bed4f02bae.png">

When a tooltip shows just the shortcut (because the button already has visible text and doesn't need a tooltip to expose its name) then it's a bit difficult to see. To me, a tooltip that shows just `⌘S` doesn't look so right, but maybe it's just me.

<img width="408" alt="screen shot 2018-05-10 at 00 26 13" src="https://user-images.githubusercontent.com/1682452/39843045-817f0988-53e9-11e8-942c-d03c34cb1874.png">

I'd recommend to consider some improvements and try to always open the tooltips in the same direction. That would probably require to make their height a bit smaller, or put the suggested keyboard shortcut on the same line, or some other adjustment.

**Comment by karmatosed** [comment]
> When a tooltip shows just the shortcut (because the button already has visible text and doesn't need a tooltip to expose its name) then it's a bit difficult to see. To me, a tooltip that shows just ⌘S doesn't look so right, but maybe it's just me.

I think that's fine as we don't need to repeat what is already said.

> I'd recommend to consider some improvements and try to always open the tooltips in the same direction. 

I think that's sensible as an approach otherwise it is super disorientating.

**Comment by youknowriad** [comment]
Is this still valid? It seems like they all show up under the buttons right now?

**Comment by karmatosed** [comment]
@afercia could you confirm if this is still something to resolve as I agree with @youknowriad that I can't find it still being an issue. If it is, could we have some examples please?

**Comment by afercia** [comment]
Fixed in #11307 see #11180 (which actually was a duplicate of this issue).
