### ISSUE TITLE
Hide meta boxes when zoomed out

### ISSUE THREAD

**Issue by stokesman** [WordPress/gutenberg#66718]
In the Post editor with a block theme active and meta boxes present, zooming out doesn’t affect the meta box pane visibility. This may be seen as unideal because displaying as much of the post content vertically as possible seems to be an aim of zoom out. Zooming out hides the editor’s footer for presumably that reason (though maybe that has more to do with content-only editing). However, not a major issue as the meta box area can be resized to take up minimal space.

> [!NOTE]  
> Availability of zoom out and meta boxes together is new in WP 6.7. If showing meta boxes while zoomed out is considered a bug then it seems eligible to fix in WP 6.7

## Demo of trunk

https://github.com/user-attachments/assets/68a46dde-bcf6-4460-997e-6613f933de95

**Comment by stokesman** [comment]
This doesn’t seem like a very important question/issue but I’m inviting @WordPress/gutenberg-design to weigh in.

**Comment by t-hamano** [comment]
Thank you for bringing this up.

There are several issues/PRs related to this issue, and we may need to consider them comprehensively:

- https://github.com/WordPress/gutenberg/pull/66726
- https://github.com/WordPress/gutenberg/issues/66629
- https://github.com/WordPress/gutenberg/issues/66671

My understanding is that the zoom out mode is about using patterns to roughly craft the overall content, so I don't see how necessary meta boxes are in that case.

In my opinion, the ideal specifications are:

- Consistently disable meta boxes in zoom out mode.
- Enable zoom out toggle and shortcuts even when the editor is not an iframe. Currently, the zoom out toggle is not visible when the editor is not an iframe, but the Patterns tab forces zoom out mode, so the zoom out toggle button suddenly appears when you open the pattern tab (related to [#66671](https://github.com/WordPress/gutenberg/issues/66671))
- Use legacy (non-resizable) meta boxes on mobile/tablet ([#66726](https://github.com/WordPress/gutenberg/pull/66726) tries to do that) but as mentioned in this comment, it might be more ideal to use resizable meta boxes for non-desktop views

That is, I would expect the following behavior:

https://github.com/user-attachments/assets/86a9dc45-f016-486a-ba88-7818d1ace410

cc @getdave @draganescu for visibility

**Comment by jasmussen** [comment]
I'd tend to echo Aki's points above, and note that one of the primary goals of zooming out is to literally work at a receded, higher, level. Work with simpler ingredients. In that vein, hiding the metaboxes works towards that. I'd defer to folks with stronger opinions, though.

**Comment by getdave** [comment]
> My understanding is that the zoom out mode is about using patterns to roughly craft the overall content, so I don't see how necessary meta boxes are in that case.

Correct 👍 I would vote to hide metaboxes in Zoom Out. It's a view designed for composing content and not tweaking settings.

**Comment by MaggieCabrera** [comment]
> Correct 👍 I would vote to hide metaboxes in Zoom Out. It's a view designed for composing content and not tweaking settings.

I have the same thought. We want to keep open the tabs that relate to editing templates/pages layout and styles, I don't think metaboxes are relevant in a zoomed out context

**Comment by getdave** [comment]
I should also add that I don't think we should have metaboxes for the device previews either. Those are designed as "previews" so metaboxes don't seem like a good fit there. Are there any known reasons why that would be a mistake?

**Comment by getdave** [comment]
> Consistently disable meta boxes in zoom out mode.

~@t-hamano Do we have a PR for this?~ I raised https://github.com/WordPress/gutenberg/pull/66742

**Comment by draganescu** [comment]
A little too late and not a blocker, just a thought: I don't know what was it so important about metaboxes showing in zoom out that required such a fast response and also merging at this stage. It's great we did it but it's an enhancement which debuted 20 hours ago and has type question 😆 

It made more sense IMO exploring in trunk ways to achieve what @t-hamano shows where metaboxes are connected to all the features that would hide them.

**Comment by stokesman** [comment]
> It made more sense IMO exploring in trunk ways to achieve what [@t-hamano](https://github.com/t-hamano) shows where metaboxes are connected to all the features that would hide them.

#66742 was only merged to `wp/6.7` so I think that’s why this is still open and we can still explore what to do with trunk.

**Comment by t-hamano** [comment]
> I should also add that I don't think we should have metaboxes for the device previews either.

This may indeed be the case. However, there may be plugin developers that require meta boxes on more than just the desktop view.
 
Pingging @arnaudbroes and @enricobattocchi: Are meta boxes necessary for tablet/mobile previews? I remember getting some feedback from you during the meta box enhancements and fixes.

**Comment by ndiego** [comment]
I am going to remove this issue from the 6.7 project board, having [already removed](https://github.com/WordPress/gutenberg/issues/66671#issuecomment-2459994285) #66671.

**Comment by arnaudbroes** [comment]
> > I should also add that I don't think we should have metaboxes for the device previews either.
> 
> This may indeed be the case. However, there may be plugin developers that require meta boxes on more than just the desktop view.
> 
> Pingging [@arnaudbroes](https://github.com/arnaudbroes) and [@enricobattocchi](https://github.com/enricobattocchi): Are meta boxes necessary for tablet/mobile previews? I remember getting some feedback from you during the meta box enhancements and fixes.

I think it would be fairly unintuitive for users if metaboxes disappear when you toggle the tablet/mobile preview.

I'm a little bit confused here though. How exactly does this new Zoom Out feature (which I really like by the way) relate to mobile previews?

Imo metaboxes should be hidden for this Zoom Out feature, but not for the mobile previews, or are they one and the same?

**Comment by stokesman** [comment]
> I should also add that I don't think we should have metaboxes for the device previews either.

It may be that in the majority cases when enabling a device preview meta boxes are unwanted. However hiding them completely risks degrading any use case where a meta field influences something related to the post’s display in the editor. If the post’s template is displayed it seems more likely and perhaps with block bindings it is a possibility.

Given that the meta boxes are now collapsible it seems okay to be conservative and keep them available. We could consider automatically collapsing them when a device previews is enabled if we’re sure that most of the time they’re a nuisance.

> I'm a little bit confused here though. How exactly does this new Zoom Out feature (which I really like by the way) relate to mobile previews?

They aren’t technically related but the question seems to have been raised because of some similarity and doubt about there being any known cases where it’s useful to have them present while a device preview is active. It’s definitely something that can be considered separately.

**Comment by t-hamano** [comment]
Thank you everyone for your feedback. So, would the following be the best course of action for now?

- Hide meta boxes in the zoom out mode in `trunk` branch, similar to `wp/6.7` branch
- Work to move #66706 forward. This means that we will _always_ use resizable meta boxes, regardless of whether the editor is an iframe or not, or what the preview device is.

**Comment by arnaudbroes** [comment]
> So, would the following be the best course of action for now?
> 
> * Hide meta boxes in the zoom out mode in `trunk` branch, similar to `wp/6.7` branch
> * Work to move [Split view with meta boxes even with legacy canvas #66706](https://github.com/WordPress/gutenberg/pull/66706) forward. This means that we will _always_ use resizable meta boxes, regardless of whether the editor is an iframe or not, or what the preview device is.

This seems like an excellent plan to me.

**Comment by richtabor** [comment]
> Hide meta boxes in the zoom out mode in trunk branch, similar to wp/6.7 branch

Yup! That would close this issue then, yea?
