### ISSUE TITLE
Stretched images in Gallery in Internet Explorer 11

### ISSUE THREAD

**Issue by ErikXXon** [WordPress/gutenberg#6671]
Stretched images in Gallery in Internet Explorer 11

When viewing images in Gallery with Internet Explorer 11, the thumbnail of the images is stretched.

**Desktop (please complete the following information):**
 - Windows 7
 - Internet Explorer 11.0.9600

Gutenberg 2.8.0

![stretchedout](https://user-images.githubusercontent.com/6995808/39852223-a47bd952-541b-11e8-8de6-e686c0edc86a.JPG)

If you uncheck 100% height and width in web browser, the gallery will look as it should with the thumbnails.

![stretchedout-gone](https://user-images.githubusercontent.com/6995808/39852233-af8be148-541b-11e8-80b0-fa8527443fd9.JPG)

**Comment by mtias** [comment]
Fixed by #7465.
