### ISSUE TITLE
Code block: Add “Edit as HTML” option and allow inline HTML elements

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#6672]
## The issue
The Code block currently does not have the <kbd><samp>Edit as HTML</samp></kbd> option in its <kbd><samp>More Options</samp></kbd> ellipsis menu. It also currently does not allow any semantic inline HTML elements. But why not? There are definitely some situations where I have wanted to use a code block but add inline formatting, such as `<kbd>`, `<samp>`, and `<var>` tags, as well as creating links within the code where URLs are.

## The feature request
Just add the ability to use the <samp>Edit as HTML</samp> option with the Code block and allow inline HTML elements to be used.

**Comment by ZebulanStanphill** [comment]
The obvious way to fix this issue would be to update the Code block to use a RichText field. But there is a catch. To quote myself from #9326:
>At first, this sounds like no problem. However, RichText fields apparently have issues when they are inline elements. See #8785, #9180, and #9195. The content of the Code block is stored inside a `<code>` element nested in a `<pre>` element. The `<code>` element is an inline element, which means that issues like #9180 could occur if the Code block was updated to use RichText.
>
>You might think that the solution to this issue is simply removing the `<code>` tags from the Code block, but doing so would remove the semantics that separate the Code block from the Preformatted block, making the former redundant. So unless some solution to the inline RichText issues is found, the Code block is pretty much stuck being unable to support inline elements, unfortunately. :disappointed:

The ability to use the <kbd><samp>Edit as HTML</samp></kbd> option does not depend on this, but if you can not add inline HTML elements, then there is no reason to edit the block as HTML.

Anyone have any ideas on how to fix this issue?

**Comment by ellatrix** [comment]
Don't see why not. Added in #24689.

**Comment by westonruter** [comment]
> Don't see why not.

This seems to have introduced a regression. See #26301.
