### ISSUE TITLE
Move "Heading" block text alignment options to the block toolbar from the sidebar

### ISSUE THREAD

**Issue by nfmohit** [WordPress/gutenberg#6673]
**Description**
To improve consistency between the settings over all blocks, the text alignment options in the "Heading" block should be moved to the block toolbar instead of the sidebar. Other blocks e.g. paragraph have alignment options in the block toolbar, but the heading block still have them in the sidebar.

**To Reproduce**
1. Open Gutenberg editor.
2. To compare, add a "Paragraph" block. The text alignment options should be viewable in the block toolbar.
3. Add a "Heading" block.
4. Locate the text alignment options in the sidebar and not the toolbar.

**Expected behavior**
The text alignment options in the "Heading" block should be in the block toolbar instead of the sidebar.

**Screenshots**
Paragraph block:
![gutenberg-paragraph](https://user-images.githubusercontent.com/20284937/39852940-397a057c-5441-11e8-921d-e6d77626717f.png)

Heading Block:
![gutenberg-heading](https://user-images.githubusercontent.com/20284937/39852958-433684e6-5441-11e8-8dcf-d823e93cd7fc.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.4
 - Browser: Google Chrome
 - Version: 66.0.3359.139

**Additional context**
WordPress Version: 4.9.5
Gutenberg Version: 2.8.0

**Comment by gziolo** [comment]
Closed by #6675.
