### ISSUE TITLE
Allow for disabling `autoFocus` on URL Input component

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#6674]
When embedding a URL Input within a larger block structure, as opposed to its use in the `Button` component, it doesn't always make sense for it to auto-focus. The particular use case I was running into was when trying to implement a "Jumbotron" component that has a specific `<button>` element as part of its structure. 

![jumbotron](https://user-images.githubusercontent.com/3460448/39854588-4fd9d8f6-53f6-11e8-802c-2eb6aa274563.png)

**Describe  the solution you'd like**
The ability to pass `autoFocus={false}` as a prop to `editor/components/UrlInput` so that when a user clicks into the Block, they are focused on the expected `RichText` input.

**Describe alternatives you've considered**
For the actual block I'm working on, I considered implementing it using Nested/Inner Blocks, but that seemed to overkill for what I was looking for and appeared to be lacking in features for just including a single nested component.

Happy to submit a PR if this seems workable.

**Comment by youknowriad** [comment]
I think it probably best if it's opt-in instead of opt-out

**Comment by danielbachhuber** [comment]
Hi @TimothyBJacobs,

Is this a duplicate of #6196?

**Comment by TimothyBJacobs** [comment]
Yep! Apologies.
