### ISSUE TITLE
Only render the write/design mode control with a template preview

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#66775]
### Description

The “Write” and “Design” mode control appears even when a template is not rendered, though this distinction is less meaningful without a template preview. Showing these controls can be confusing when post content is abstracted from the template, as users expect unrestricted typing. The mode control should be hidden in the editor header whenever the template is not rendered. 

Additionally, “Design” mode should be the default whenever the template preview is off, ensuring a consistent experience.

Hiding the mode control without a rendered template and defaulting to “Design” mode with preview off will simplify the interface, reducing unnecessary options and improving clarity.

### Steps to reproduce

1. Open the site editor or post editor.
2. Switch to a view where no template is rendered.
3. Observe that the “Write” and “Design” mode control is still visible.
4. Turn off the template preview and check the active mode.

### Expected

- The “Write” and “Design” mode control should be removed when a template is not rendered, as the mode distinction is less meaningful.
- “Design” mode should be enabled automatically when turning off the template preview, maintaining consistency as the default mode.

### Visual

This is how to engage the template preview. Within the Site Editor template preview is enabled by default; in the post editor it is not. I'd expect when the template preview is off, the tool is not available and the mode is set to "Design". 

https://github.com/user-attachments/assets/efe01123-a8af-45d4-9e53-6bedfbea40eb

**Comment by draganescu** [comment]
@richtabor I have a hard time following why we're hiding this control - when post editing where you mostly write the default mode is design, and in template editing where you mostly designing you can switch to write mode?

**Comment by CreativeDive** [comment]
@richtabor I don't know why this toggle has been removed for post/pages? Activating the "Focus on content" mode is very nice to see all content fields with "role: content" only, without all the design related controls.

Please add these toggle back. It's very helpful and could be also conditionally set for specific user roles.
