### ISSUE TITLE
Relocate “View” external link to end of editor header controls

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#66776]
### Description

The “View” external link icon currently appears between other controls when viewing a published post or page in the editor. This placement disrupts muscle memory, causing a disorienting experience as users expect consistent control positions, regardless of publish state. 

### Proposal

Move the “View” external link icon to the end of the list of controls. This will maintain expected positioning, allowing for a more intuitive and predictable experience.

#### Current 

![Image](https://github.com/user-attachments/assets/1a74f47a-20db-45de-8fc5-3e219d235675)

#### Proposed 

![Image](https://github.com/user-attachments/assets/31c8c33b-0287-4690-8a62-4fda3312c98a)

**Comment by jasmussen** [comment]
Sounds good to me, sound reasoning. 👍 👍
