### ISSUE TITLE
featured image

### ISSUE THREAD

**Issue by anoopranawat** [WordPress/gutenberg#6677]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by anoopranawat** [comment]
Existing featured image is not loading : https://screenshots.firefox.com/ZBIIDZOEmswRGXvW/localhost

**Comment by danielbachhuber** [comment]
Hi @anoopranawat,

Thanks for the report. A few follow-up questions:

* Can you share any debugging you've done?
* When you look in your Dev Tools, is the featured image request successful or failed? If the latter, can you share the specific response?
* Does the problem reproduce with all plugins deactivated (except Gutenberg) and Twenty Seventeen enabled?

**Comment by t-wright** [comment]
Just trying Gutenberg for the first time and I'm experiencing the same issue. I'm running a multisite install on VVV. Have tried with Twenty Seventeen and all other plugins disabled. Looks like when the feature image is updated, a request is made to `http://sitename.test/wp-json/wp/v2/media/86?context=edit`. The response I'm getting is:

`"<br />
<b>Notice</b>:  Undefined index: content in <b>/srv/www/sitename/htdocs/wp-content/plugins/gutenberg/lib/rest-api.php</b> on line <b>260</b><br />
<br />
<b>Notice</b>:  Undefined index: content in <b>/srv/www/sitename/htdocs/wp-content/plugins/gutenberg/lib/rest-api.php</b> on line <b>260</b><br />
{"id":86,"date":"2018-05-11T10:51:30","date_gmt":"2018-05-11T00:51:30","guid":{"rendered":"http:\/\/sitename.test\/wp-content\/uploads\/2018\/01\/800x800-2.png","raw":"http:\/\/sitename.test\/wp-content\/uploads\/2018\/01\/800x800-2.png"},"modified":"2018-05-11T10:51:30","modified_gmt":"2018-05-11T00:51:30","slug":"800x800-3","status":"inherit","type":"attachment","link":"http:\/\/sitename.test\/article\/8\/new-york-new-york\/800x800-3\/","title":{"raw":"800x800","rendered":"800&#215;800"},"author":1,"comment_status":"closed","ping_status":"closed","template":"","meta":[],"revisions":null,"permalink_template":"http:\/\/sitename.test\/article\/8\/new-york-new-york\/%postname%\/","description":{"raw":"","rendered":"<p class=\"attachment\"><a href='http:\/\/sitename.test\/wp-content\/uploads\/2018\/01\/800x800-2.png'><img width=\"768\" height=\"768\" src=\"http:\/\/sitename.test\/wp-content\/uploads\/2018\/01\/800x800-2-768x768.png\" class=\"attachment-medium size-medium\" alt=\"\" srcset=\"http:\/\/sitename.test\/wp-content\/uploads\/2018\/01\/800x800-2-768x768.png 768w, http:\/\/sitename.test\/wp-content\/uploads\/2018\/01\/800x800-2-150x150.png 150w, http:\/\/sitename.test\/wp-content\/uploads\/2018\/01\/800x800-2.png 800w\" sizes=\"(max-width: 768px) 100vw, 768px\" \/><\/a><\/p>\n"},"caption":{"raw":"","rendered":""},"alt_text":"","media_type":"image","mime_type":"image\/png","media_details":{"width":800,"height":800,"file":"2018\/01\/800x800-2.png","sizes":{"thumbnail":{"file":"800x800-2-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"http:\/\/sitename.test\/wp-content\/uploads\/2018\/01\/800x800-2-150x150.png"},"medium":{"file":"800x800-2-768x768.png","width":768,"height":768,"mime_type":"image\/png","source_url":"http:\/\/sitename.test\/wp-content\/uploads\/2018\/01\/800x800-2-768x768.png"},"full":{"file":"800x800-2.png","width":800,"height":800,"mime_type":"image\/png","source_url":"http:\/\/sitename.test\/wp-content\/uploads\/2018\/01\/800x800-2.png"}},"image_meta":{"aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0","keywords":[]}},"post":8,"source_url":"http:\/\/sitename.test\/wp-content\/uploads\/2018\/01\/800x800-2.png","_links":{"self":[{"href":"http:\/\/sitename.test\/wp-json\/wp\/v2\/media\/86"}],"collection":[{"href":"http:\/\/sitename.test\/wp-json\/wp\/v2\/media"}],"about":[{"href":"http:\/\/sitename.test\/wp-json\/wp\/v2\/types\/attachment"}],"author":[{"embeddable":true,"href":"http:\/\/sitename.test\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"http:\/\/sitename.test\/wp-json\/wp\/v2\/comments?post=86"}]}}"`

Checking that `$response_data['content']` exists in `gutenberg_add_block_format_to_post_content()` does indeed fix the issue.

**Comment by danielbachhuber** [comment]
Ah. This is fixed by #6576 for Gutenberg 2.9. You can apply this change locally if you need the fix more immediately.
