### ISSUE TITLE
Write mode: some group blocks/patterns can't be edited after switching into Write mode

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#66803]
Opening a bug report to be safe but I can't quite discern the distinction here for why certain Group blocks from patterns can't be edited after switching into Write mode using the Twenty Twenty-Four theme, GB 19.6, and WP 6.6.2:

https://github.com/user-attachments/assets/60c33961-5841-4775-9fac-747bf12bacac

To replicate:

1. Install and activate the Twenty Twenty-Four theme.
2. Install and activate Gutenberg 19.6 (latest release)
3. Open the Site Editor.
4. Edit the Blog Home template.  
5. Switch into Write mode and notice you can't edit the first three patterns provided in the template 

I can also replicate this following the same steps but with the Twenty Twenty-Five theme using 6.7 RC3 and GB 19.6. In this case, I had to add a few patterns to the Blog home template to replicate: 

https://github.com/user-attachments/assets/298e16f8-91db-4039-8fa6-0a3979bc26e4

**Comment by annezazu** [comment]
Using Gutenberg nightly, I can't replicate this so something definitely resolved this between 19.6 and now:

https://github.com/user-attachments/assets/a6c6bd6a-4765-45c9-bb35-f10490cca864

cc @ntsekouras as you're digging into these!

**Comment by ntsekouras** [comment]
Does @mcsf 's [PR](https://github.com/WordPress/gutenberg/pull/66833) fixes that too?

**Comment by annezazu** [comment]
Yes! Just was coming here to follow up and test:

https://github.com/user-attachments/assets/b1ffdf0d-eb32-44a6-a9ae-681269d841cf

Closing out.
