### ISSUE TITLE
DataViews: (List view) Only one primary action is shown, and there is a offset

### ISSUE THREAD

**Issue by doekenorg** [WordPress/gutenberg#66814]
### Description

On the list view, only the first primary action is shown. Others are only visible in the action dropdown menu. But that menu is also hidden by a visual offset. So it's not apparent there is even more. 

So two bugs: 

- [ ] All primary actions should be shown
- [ ] The action dropdown button should be visible

### Step-by-step reproduction instructions

1. Add multiple primary actions
2. See the list view

### Screenshots, screen recording, code snippet

I've reproduced this on the storybook:

![Image](https://github.com/user-attachments/assets/7de5da0f-e965-4dba-8e47-ba4e73de807c)

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by oandregal** [comment]
> The action dropdown button should be visible

What WordPress & Gutenberg versions do you have? I cannot reproduce with WordPress 6.6/6.5 (with or without Gutenberg 19.6 active).

> All primary actions should be shown

This is intentional. The list view has very few space so we limited to a single one. This may change in the future, but it's not a bug.

**Comment by doekenorg** [comment]
> > The action dropdown button should be visible
> 
> What WordPress & Gutenberg versions do you have? I cannot reproduce with WordPress 6.6/6.5 (with or without Gutenberg 19.6 active).

This is reproduced on the storybook. https://wordpress.github.io/gutenberg/?path=/docs/dataviews-dataviews--docs If you check the first one, and switch to List layout; you see this happening. Locally I had the same with the latest branch. I didn't test this on the WordPress components, but on DataKit we have the same issue.  I'm pretty sure this will be another css discrepancy. 

> 
> > All primary actions should be shown
> 
> This is intentional. The list view has very few space so we limited to a single one. This may change in the future, but it's not a bug.

Ok, I wasn't aware of that limitation on a List. I guess it depends on the amount of data on the list. In that case it might be useful to have influence on the actions on the layout type. Where `isPrimary` is a callback, that at least receives the current layout context. Then you can make a choice which Primary action should stay. (just thinking out loud).
