### ISSUE TITLE
Tooltips width depends on the CSS rules order in the built stylesheet

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6681]
When I build Gutenberg on macOS, the tooltips size is correct:

![screen shot 2018-05-10 at 12 37 23](https://user-images.githubusercontent.com/1682452/39866329-817117d0-5450-11e8-9c60-d87a41ca4459.jpg)

However, when I build it on Windows, the tooltips have a min-width of 240 pixels:

![screenshot 129](https://user-images.githubusercontent.com/1682452/39866343-93939fb4-5450-11e8-9351-36d11152504a.png)

Seems to me there are 2 conflicting CSS rules that have the same specificity and the only reason it works correctly on macOS is because the one with `min-width: 0` comes later in the built stylesheet. Please notice the line numbers in the screenshots.

I have no idea why on Windows the order of the rules in the built stylesheet is different. I also understand Gutenberg will be built on a *nix machine. However, to be safe, I'd recommend to slightly increase the specificity of the tooltips rule, so it works regardless of the order.

**Comment by afercia** [comment]
I still see this happening on Windows, with all browsers. Just tested the built version from the repo and the plugin version 3.1 (released yesterday so they're basically identical) and the tooltips in the repo version are broken, in the plugin version are OK.

![screenshot 6](https://user-images.githubusercontent.com/1682452/41767639-7fcd3cd4-760a-11e8-9c80-301f12b4c255.png)

Compared to the previous screenshots, now also the tooltip "arrow" doesn't look as it should.

**Comment by earnjam** [comment]
I don't have a windows machine to test this on. @afercia is this still happening?

**Comment by jorgefilipecosta** [comment]
I verified that the selectors still rely on the code order to work properly. I think the specificity of the tooltip selector should be increased.
