### ISSUE TITLE
Update placeholder instructions for blocks that support drag and drop

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#66828]
There are inconsistencies in the terminology between block placeholders, leading to a suboptimal experience. With variations in instruction wording across the interface, users may hesitate or second-guess their actions, slowing down the overall workflow. 

Consistent language provides clarity, reduces cognitive load, and helps users accomplish their tasks without unnecessary friction.

### Proposal 

1. Prioritize drag and drop terminology (and in some cases add it) as this is the inferred action not provided by a clear call to action below the instructions. "Upload" is the first, bold, button in each placeholder—it has enough prominence as an action. 
2. Throughout the editor, the UI uses "choose" as a verb for selecting, or "picking", more consistently. "Pick" is actually only used in placeholders. 
3. Inconsistencies in terminology used throughout these instructions. 
4. Avoid using "ones".

#### Image block

Current: "Upload or drag an image file here, or pick one from your library."
Proposed: `Drag and drop an image here, upload, or choose from your library.`

#### Gallery block
Current: "Drag images, upload new ones or select files from your library."
Proposed: `Drag and drop images here, upload, or choose from your library.`

#### Cover block
Current: "Drag and drop onto this block, upload, or select existing media from your library."
Proposed: `Drag and drop an image or video here, upload, or choose from your library.`

#### Audio block
Current: "Upload or drag an audio file here, or pick one from your library."
Proposed: `Drag and drop an audio file here, upload, or choose from your library.`

#### Video block
Current: "Upload a video file, pick one from your media library, or add one with a URL."
Proposed: `Drag and drop a video here, upload, or choose from your library.`

#### File block
Current: "Upload a file or pick one from your media library."
Proposed: `Drag and drop a file here, upload, or choose from your library.`

#### Media & Text block
Current: "Upload a media file or pick one from your media library."
Proposed: `Drag and drop an image or video here, upload, or choose from your library.`

### Visual 

![Image](https://github.com/user-attachments/assets/92593e2e-3e2d-4cea-9ed1-7fe0cd657bdf)

**Comment by matiasbenedetto** [comment]
Copy texts updated here: https://github.com/WordPress/gutenberg/pull/66842

**Comment by up1512001** [comment]
@richtabor Also can we incorporate the same illustrator as the `Image` block for this blocks.

https://github.com/user-attachments/assets/54cd13a9-8064-4ad8-8529-5fc3b9db5e82


I have raised PR to do that for `Audio`, `File` & `Media text` blocks.
Audio Block: https://github.com/WordPress/gutenberg/pull/66838
File Block: https://github.com/WordPress/gutenberg/pull/66839
Media text block: https://github.com/WordPress/gutenberg/pull/66841
