### ISSUE TITLE
Add Media” to “Add media” to follow sentence-case UI standards

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#66826]
### Description

The Cover block's “Add Media” control should be updated to “Add media” to align with the sentence-case UI ruleset, ensuring consistency across the interface.

### Steps to Reproduce:

1.	Navigate to the section with the “Add Media” button.
2.	Observe that the text currently displays in title case.

### Expected:

Button text should follow sentence-case standards and display as “Add media.”

### Visual 

![Image](https://github.com/user-attachments/assets/6cdfa89b-d975-4a63-b37f-77cb7eff1326)

**Comment by matiasbenedetto** [comment]
Text updated here: https://github.com/WordPress/gutenberg/pull/66843
