### ISSUE TITLE
Fix auto-applying of top-left positioning in the Cover block BlockAlignmentMatrixControl

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#66831]
### Description

The BlockAlignmentMatrixControl in the Cover block toolbar auto-applies the top-left value to the block each time the control is engaged with. This behavior is unintended, as the control should only apply a new position if the user actively selects one of the matrix points. The current experience leads to unexpected positioning changes, which disrupts user workflows and content layout.

### Steps to Reproduce:

1. Add a Cover block to the editor.
2. Add media.
3. Open the "Change content position" control.
4. Observe that the top-left position is auto-applied to the content even without selecting any matrix point.

### Expected:

The position should remain unchanged unless the user actively selects a new matrix point.

### Visual 

https://github.com/user-attachments/assets/56e76b41-9f25-444c-b263-38643d532e47

**Comment by t-hamano** [comment]
I was not able to reproduce this issue.

https://github.com/user-attachments/assets/3e16ab67-a376-4c18-bf66-a25499fde5d9

**Comment by dhruvang21** [comment]
i am also not able to reproduce this issue.

https://github.com/user-attachments/assets/e8e7da6b-9734-4179-a6e7-39388004b4f4

**Comment by richtabor** [comment]
I can't either. Doesn't look like anything would have inadvertently resolved this. Let's just close it. Thanks for looking into it!
