### ISSUE TITLE
On Patterns screen for classic theme, site icon does not return to admin dashboard on mobile

### ISSUE THREAD

**Issue by ironprogrammer** [WordPress/gutenberg#66844]
### Description

With a classic theme active, clicking the site icon to return to the admin dashboard yields a different result between desktop and mobile.

On desktop, the site icon returns to the dashboard. On mobile, however, it opens the site editor sidebar menu, revealing other screens that are not compatible with non-block themes. For instance, a blank page results when attempting to access Styles. The issue appears to have been introduced in 6.6 when the Patterns link was updated to resolve in the site editor.

### What I expected
The expected result is that on mobile screens (728px or narrower) the site icon should return to the admin dashboard, like on desktop.

Props @kebbet for raising this in the `#core` channel.

### Step-by-step reproduction instructions

1. Open WordPress 6.6+ on a mobile device, _OR_ on desktop, shrink the viewport to 728px width or less.
2. Activate a classic theme, such as `twentytwenty`.
3. Navigate to _Appearance > Patterns_.
4. Inspect the site icon (typically the WordPress "W") in the upper left, and observe that it is the "Go to Site Editor" button (via `aria-label` attribute).
5. Click the site icon and observe that the left site editor panel opens.

Here are some test links that activate classic theme `twentytwenty` and navigate to the Patterns screen directly:
- [Playground link to test Core](https://playground.wordpress.net/?theme=twentytwenty&url=%2Fwp-admin%2Fsite-editor.php%3Fpath%3D%2Fpatterns)
- [Playground link including Gutenberg latest](https://playground.wordpress.net/?plugin=gutenberg&theme=twentytwenty&url=%2Fwp-admin%2Fsite-editor.php%3Fpath%3D%2Fpatterns)

### Screenshots, screen recording, code snippet

Animated GIF demonstrating clicking the site icon when viewing the Patterns screen with Twenty Twenty activated:
![Image](https://github.com/user-attachments/assets/15fdad1f-778d-45f9-9c05-6b8a6fd84209)

### Environment info

- Playground
- Browser: Safari 17.6, Google Chrome 130.0.6723.92
- Theme: `twentytwenty` and `twentyten`
- Plugin: w/ and w/o `gutenberg`

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [x] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by yogeshbhutkar** [comment]
I believe the mobile site hub menu's WP Button has some old code that just navigates back.

```js
<Button
	__next40pxDefaultSize
	ref={ ref }
	label={ __( 'Go to Site Editor' ) }
	className="edit-site-layout__view-mode-toggle"
	style={ {
		transform: 'scale(0.5)',
		borderRadius: 4,
	} }
	onClick={ () => {
		history.push( {} );
		navigate( 'back' );
	} }
>
	<SiteIcon className="edit-site-layout__view-mode-toggle-icon" />
</Button>
```

If we fetch the dashboard link, assign it to the href, and remove the onClick handler, the issue will then be resolved.

I would like to take up this issue and come up with a corresponding PR.
