### ISSUE TITLE
My patterns > Editor Role > cannot access to the list of my own patterns (Appareance > Editor > Patterns)

### ISSUE THREAD

**Issue by Marc-pi** [WordPress/gutenberg#66847]
## What problem does this address?

usecase : As an user with Editor role, i can create my own patterns, detach them, but only from the Page/Post edit side.
I do not have access to pattern admin menu (Appareance > Editor > Patterns) to find My Patterns and edit them 
I can only see them from the Inserter, but it's only to insert to, there is no edit way from there.

## What is your proposed solution?

Permit the user that can create Patterns to manage them from the Appareance > Editor > Pattern menu
This will allow them to also see the patterns they cannot edit (ex : footer, header, etc.)
but allow them to edit the patterns they are author of.
>> there is a need to manage permissions around that area
and it deals with the Admin new UX

**Comment by talldan** [comment]
> I can only see them from the Inserter, but it's only to insert to, there is no edit way from there.

There is the Manage Patterns option for editors which loads the wp admin style posts screen:
<img src=https://github.com/user-attachments/assets/7b7b638c-fa0b-4444-a5e8-3909af1b8e33 width="275" />

But agree, it'd be great to be able to use the site editor's Patterns page. 👍

**Comment by t-hamano** [comment]
This appears to be the same as #61637 so I will close it.

**Comment by Marc-pi** [comment]
@t-hamano good, i searched but did not find https://github.com/WordPress/gutenberg/issues/61637, it's the same need
@talldan did not see this menu option, thanks, will test for my users
