### ISSUE TITLE
Disable the default font sizes and JS TypeError

### ISSUE THREAD

**Issue by stefanolissa** [WordPress/gutenberg#66858]
### Description

I'm trying to disable the defaultFontSizes (S, M, L, ...) using a filter over the theme.json (since it should be disabled only for a specific custom post type).

`add_filter('wp_theme_json_data_theme', function ($theme_json) {
   
        $new_data = array(
            'version' => 3,
            'settings' => array(
                'typography' => array(
                    'fontSizes' => [],
                    'defaultFontSizes' => false,
                ),
            ),
        );`

I followed the instructions here: https://wpdevelopment.courses/articles/block-editor-typography-settings/#disable-font-size-controls

Setting settings.typography.defaultFontSizes to false does nothing (WP 6.6.2, no plugins, 2024 theme).

Setting settings.typography.fontSizes to and empty array, leave the "sizes box" active without options (S, M, L, ... they disappear), but if you activate the custom size selector, which starts with an empty value, moving the slider does nothing and there is a JS error:

`Uncaught TypeError: n?.startsWith is not a function
    at Dh (block-editor.min.js?ver=7ab6a9fdca1a0386ea66:21:312023)
    at onChange (block-editor.min.js?ver=7ab6a9fdca1a0386ea66:21:313162)`

if you try to type a size directly the paragraph block disappear (I'm testing it on a paragraph block) and you get:

`This block has encountered an error and cannot be previewed.`

with the same error recorded in the JS console.

It's a bug or I'm doing something wrong? The defaultFontSizes should disable the default sizes selector?

Thanks, Stefano.

### Step-by-step reproduction instructions

1. filter the theme.json using wp_theme_json_data_theme and merge in the settings.typography.fontSizes = []
2. create a post, add a paragraph and try to set the font size using the custom font size control

### Environment info

WP 6.6.2, no plugins, 2024 theme 

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by t-hamano** [comment]
Thanks for the report. I believe this issue has also been reported in #62072, so I will close it.
