### ISSUE TITLE
Search block button text overlapping.

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/gutenberg#66852]
### Description

Hello Team,

I have checked **"Search Block"** and found that the button text is overlapping when we change its **"Change button position"** to **"Button Only"** & and we change block width to **25%** from block settings.

For better understanding, Here I have provided its video.

Please see my attachment.

**Issue video:**

https://github.com/user-attachments/assets/9b8818e5-0fb5-44c7-ad55-7468218a3462

### Step-by-step reproduction instructions

- Type / to choose a block
- Select search block
- Change its button position using **"Change Button position"** setting to **"Button only"**
- Change block button width from **"Setting"** to **25%**
- Save the changes and publish the page.
- View the editor side & front-end side.
- Click on "Search" button and see the button text is overlapping.
- Just see the difference

### Environment info

- WordPress version: WordPress 6.7-beta3 running
- Themes:
- Twenty Twenty-Five Version: 1.0 and other themes too
- Browser: Google Chrome, Version 130.0.6723.92 (Official Build) (arm64)
- Device:** MacBook Air M1
- OS: macOS 15.1 (24B83)
- Gutenberg plugin: Version 19.6.0

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by snehapatil2001** [comment]
I have identified the above and some alignment issues on mobile screens and have created a separate GitHub [issue ](https://github.com/WordPress/gutenberg/issues/66871)to address them.

To resolve these issues, I have raised a pull request: [PR #66868](https://github.com/WordPress/gutenberg/pull/66868), which includes the necessary adjustments to improve inconsistencies for both the issues.
