### ISSUE TITLE
Unable to expand groups on List View

### ISSUE THREAD

**Issue by xavier-lc** [WordPress/gutenberg#66869]
### Description

After creating a group element, when I add a pattern element, those elements stop being expandable on the List View.

### Step-by-step reproduction instructions

1. Go to `/wp-admin/post-new.php?post_type=page`
2. Close the `Choose a pattern` modal
3. Create a `List` block
4. Open the List View
5. Check that the List block can be expanded
6. Add an About Pattern
7. Go to the List View
8. Check that the List block can't be expanded anymore

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/2225df41-aab2-471e-9f4e-4e3c83a49152

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [x] Not sure

**Comment by xavier-lc** [comment]
Using `git bisect`, I've managed to identify https://github.com/WordPress/gutenberg/commit/4af4518b0917296091f6d520ce1352f6094cc3eb as the commit where this bug was introduced.

**Comment by jeryj** [comment]
Might be fixed by https://github.com/WordPress/gutenberg/pull/66574 or https://github.com/WordPress/gutenberg/pull/66381. I'm guessing the editor is stuck in the wrong editing mode.

**Comment by xavier-lc** [comment]
> Might be fixed by [#66574](https://github.com/WordPress/gutenberg/pull/66574) or [#66381](https://github.com/WordPress/gutenberg/pull/66381). I'm guessing the editor is stuck in the wrong editing mode.

Good to know, thanks!

**Comment by Mamaduka** [comment]
I can confirm that this has been resolved.
