### ISSUE TITLE
Styles of Search block button are breaking.

### ISSUE THREAD

**Issue by snehapatil2001** [WordPress/gutenberg#66871]
### Description

**Related issue: https://github.com/WordPress/gutenberg/issues/66852**

I found some more errors related to the above issue on the mobile screen, as shown in the video below.

**Bugs:**
- View the editor side, the text is overlapping in the mobile screen.
- View the frontend side, the text is not centered.

### Step-by-step reproduction instructions

1. Type / to choose a block
2. Select search block
3. Change its button position using "Change Button position" setting to "Button only"
4. Change block button width from "Setting" to 25%
5. Save the changes and publish the page.
6. View the editor side in mobile screen size, the text is overlapping.
7. View the frontend side in mobile screen size, the text is not centered.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/da5c06e1-4e22-41e0-81f2-4ec579ec3bf5

### Environment info

WordPress version: 6.8-alpha-59366
Theme: Twenty Twenty-Five Version: 1.0 
Device:** MacBook Air M2
Gutenberg plugin: Version 19.6.0

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by gziolo** [comment]
Fixed with #66868.
