### ISSUE TITLE
Console error in Editor: GET 400 (Bad Request), code: rest_invalid_type, message: post[0] is not of type integer.

### ISSUE THREAD

**Issue by realthemes** [WordPress/gutenberg#66882]
### Description

Hello, I am getting a console error on a clean local WordPress 6.6.2 installation with the latest Gutenberg plugin:

Failed to load resource: the server responded with a status of 400 (Bad Request)
http://local.test/wp-json/wp/v2/comments?context=edit&post=twentytwentyfour%2F%2Fhome&type=block_comment&status=any&per_page=100&_locale=user

If I open this link, I'm getting this:

```
{
    "code": "rest_invalid_param",
    "message": "Invalid parameter(s): post",
    "data": {
        "status": 400,
        "params": {
            "post": "post[0] is not of type integer."
        },
        "details": {
            "post": {
                "code": "rest_invalid_type",
                "message": "post[0] is not of type integer.",
                "data": {
                    "param": "post[0]"
                }
            }
        }
    }
}
```

### Step-by-step reproduction instructions

1. Install clean WordPress 6.6.2 in local environment.
2. Install Gutenberg plugin.
3. Open Editor (click Home template to get inside Editor).
4. Check console for errors.

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/78498c8f-ef36-406e-b01b-6b1b8f2d4653)

### Environment info

- WordPress 6.6.2, Gutenberg 19.6.1, TwentyTwentyFour theme.
- Edge Browser.
- Desktop with Windows 11.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by t-hamano** [comment]
Thanks for the report. I was also able to reproduce this issue in Gutenberg 19.6.1, but I noticed that this issue does not occur in trunk. After investigating, I found that this issue was resolved by #66670.

Therefore, this issue will be resolved in Gutenberg 19.7.
