### ISSUE TITLE
Place "Write mode" functionality behind a Gutenberg experiment

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#66881]
In light of user testing and current known limitations outlined in https://github.com/WordPress/gutenberg/issues/60021, let's change Write mode to an experiment for now to better contain the experience and give time for the feature to evolve before rolling it out more broadly again. In the referenced issue, I put together a list of proposed Tasks to stabilize Write mode that can be discussed further there. 

cc @ntsekouras  @youknowriad @mcsf  for help!

**Comment by ntsekouras** [comment]
What would this mean in terms of the modes? If the experiment is not enabled, should we only have the `design` mode or you're thinking of bringing back the `select` mode we had in place of the `write` mode?

**Comment by youknowriad** [comment]
I think the idea is just to hide the tool selector entirely

**Comment by annezazu** [comment]
I don't have a strong direction here but either hiding it (if that's easier) or returning it to the prior setup of Edit vs Select options.

**Comment by richtabor** [comment]
Yes, just hiding it entirely and ensuring "Design" mode is set. I don't think it's worth backtracking to Edit / Select.

**Comment by carolinan** [comment]
What percentage of users use the select mode? I am concerned that it is an important feature for few, but for those who need it, it is vital.
