### ISSUE TITLE
If possible, only input should fade out block boundaries

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#669]
Related to #657, we want the block boundaries and controls to fade out as soon as you start typing, so you can focus on the content. 

Right now "start typing" means you press any key, including shift, command, control, alt, etc. If at all possible, it would be nice that block boundaries only faded out once _text input_ was actually entered in input fields, and not before.

**Comment by iseulde** [comment]
At first I would say we should check if non input keys are pressed, but if we keep the content in sync (#475), we could see if the content actually changed.
