### ISSUE TITLE
Adding Anchor Link to Media & Text Block Sets Link to Inline-Block

### ISSUE THREAD

**Issue by Infinite-Null** [WordPress/gutenberg#66914]
### Description

When adding an anchor link to the Media & Text block, the following CSS style is applied, causing the media to display at a reduced size.

Testing with a medium media size results in the image width being limited to 300px, making the media appear too small.

In the Editor the media size looks perfect.

```
.wp-block-media-text__media a {
    display: inline-block;
}
```

### Step-by-step reproduction instructions

1. Go to any post
2. Add Media & Text Block

![Image](https://github.com/user-attachments/assets/99e0175a-5d5d-4c93-9d0f-b5c94325ea5b)

3. Select an image

![Image](https://github.com/user-attachments/assets/7e565391-9f7e-45f4-9ee8-a4f84ff1cf49)

4. Select resolution as medium

![Image](https://github.com/user-attachments/assets/465f0153-9eab-4aae-baa8-3eea00d434ae)

5. Add an anchor link to block and save

![Image](https://github.com/user-attachments/assets/41d8685e-9509-47c7-af99-c225e99ca895)

5. Check frontend 

### Screenshots, screen recording, code snippet

Preview:
![Image](https://github.com/user-attachments/assets/30c02936-a64b-4e8b-ad9c-594eeefabac7)

Demo link:
https://share.zight.com/7KuN5mYJ

### Environment info

WordPress Version: 6.8
Browser: Chrome
Operating System: Mac OS

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by ajmaurya99** [comment]
Related Ticket - https://core.trac.wordpress.org/ticket/62376
