### ISSUE TITLE
Query loop: Title block as paragraph

### ISSUE THREAD

**Issue by Drivingralle** [WordPress/gutenberg#66916]
## What problem does this address?

While I was building a client website I tried to create a section, that talks about the blog. In this section I wanted to list a few posts. Therefore I used the query block to fetch them dynamically. With filters and styling option I can get the list to look fine. But the markup of the page is "broken". There is only the option to make the post title to be a headline. But in this case the headline tags are breaking the structure of the document. 

The same if I use query blocks inside the footer to automatically display child pages for navigation. Suddenly there are headlines of some level inside the footer no matter if the main content doesn't lead to the headling level. 
As far es I know there should be no headings inside the footer anyway. 

## What is your proposed solution?
Extent the list of allowed tags/heading-levels to also include the paragraph tag.

**Comment by Marc-pi** [comment]
yep, i've also this need.
Sometimes we don't want to force a heading as title for the "Title block"
in the dropdown, would be fine to add a "no heading" like option (div)
![Image](https://github.com/user-attachments/assets/98e4aa3d-2b25-47eb-9f41-7a0558865614)

**Comment by carolinan** [comment]
Hi
There seems to be some confusion here.
The post title block is not part of the query loop. It is its own block and can be placed outside the query loop.
Using the p tag with the post title block is already discussed in this issue: https://github.com/WordPress/gutenberg/issues/30549
So I am closing this as a duplicate, please continue the discussion in the original issue.
