### ISSUE TITLE
is_admin + 'core-block-patterns' theme support

### ISSUE THREAD

**Issue by mleathem** [WordPress/gutenberg#66928]
### Description

It seems the add/remove theme_support for 'core-block-patterns' has no application within the context of `is_admin()` function 

(as in `remove_theme_support('core-block-patterns')`  /  `add_theme_support('core-block-patterns')`  in conjunction with `is_admin()`

as a simplified example:

```
function remove_default_block_patterns() {
    if  ( is_admin() ) {
        add_theme_support('core-block-patterns'); 
    } else {
        remove_theme_support('core-block-patterns'); 
    }
add_action('after_setup_theme', 'remove_default_block_patterns')
```

Use case: The use case for this is that Admin users should have access to all the available patterns, but other backend users only custom defined patterns.

### Step-by-step reproduction instructions

1. add the code snippet into functions.php
2. login as admin user
3. view the available patterns

Note as way of testing - I have tested within this function:
`remove_theme_support('core-block-patterns');` and `add_theme_support('core-block-patterns');` both behave as expected, and I have tested that `is_admin()` is available.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by mleathem** [comment]
I am surprised/(wonder) that `add_theme_support('core-block-patterns');` is at all needed... I would have expected the default to apply the core-block-patterns; perhaps this is the case so long as the patterns have not once been removed/re-registered etc  (I havent explored the database to see what is written to the tables).

I also tried this approach ... again: **is_admin** isnt applied.

```
    remove_theme_support('core-block-patterns');
    if  ( is_admin() ) {
        add_theme_support('core-block-patterns'); 
    } 
```

**Comment by Andrew-Starr** [comment]
`is_admin` returns true if the user is in the admin interface, it is not for checking if the user is an admin.

For checking if the user has admin capabilities, you should use `current_user_can( 'manage_options' )` instead.

**Comment by Andrew-Starr** [comment]
e.g. this should work:

```
function remove_default_block_patterns() {
    if ( current_user_can( 'manage_options' ) ) {
        add_theme_support( 'core-block-patterns' ); 
    } else {
        remove_theme_support( 'core-block-patterns' ); 
    }
}
add_action( 'after_setup_theme', 'remove_default_block_patterns' );
```

**Comment by t-hamano** [comment]
> `is_admin` returns true if the user is in the admin interface, it is not for checking if the user is an admin.
> 
> For checking if the user has admin capabilities, you should use `current_user_can( 'manage_options' )` instead.

I think this is correct.

@mleathem This issue is not a bug, but rather appears to be a problem with incorrect use of the function, so I will close it. Please let me know if there is anything I have missed.

**Comment by mleathem** [comment]
sorry.
Thanks @t-hamano  for clearing up my mistake.
