### ISSUE TITLE
Pattern without categories break the editor when browsing uncategorized patterns.

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#66944]
## What?
Patterns without categories break the editor when browsing uncategorized patterns.

### Step-by-step reproduction instructions

1. Activate TT5 theme.
2. Use the site editor
3. Open the inserter
4. Browse the patterns from the inserter
5. Click 'Explore all patterns' button at the bottom of the patterns inserter.
6. Click 'Uncategorized' in the pattern modal.

See the screencast below

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/c30b0a8f-de3b-4f2b-9d7b-1e932df3b0dc

### Environment info

- WordPress 6.7 rc5

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by rick2414** [comment]
This looks alot like https://core.trac.wordpress.org/ticket/62367
