### ISSUE TITLE
Add text alignment controls to Verse block toolbar

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6695]
## The Verse block seems to be missing something
The Heading, Paragraph, and Subheading blocks all have text alignment controls in their block toolbars. (The Cover Image and Quote blocks do as well, but those blocks will soon be updated to use nested Paragraph and Heading blocks, so they do not really count.) For some reason, the Verse block currently does not.

## Solution
Just add the same text alignment button controls to the block toolbar of the Verse block.

## Related Issues and/or PRs
- #3785
- #5635
- #5880 
- #6447 & #6525
- #6673 & #6675
- #6696
- #6697
- #6698
- #6699

**Comment by danielbachhuber** [comment]
@SuperGeniusZeb Can you share an example use-case for this enhancement?

**Comment by SuperGeniusZeb** [comment]
@danielbachhuber Making poetry/music lyrics appear centered, especially when surrounded by standard non-poetic text (Paragraph or Heading blocks) that are centered, as having the Verse blocks use a different text alignment from surrounding Paragraph blocks looks weird.

![image](https://user-images.githubusercontent.com/19592990/40328030-8b752b64-5d0a-11e8-8231-1736dc3caf4a.png)

**Comment by danielbachhuber** [comment]
Good example, thanks @SuperGeniusZeb

**Comment by karmatosed** [comment]
Closing as now merged in #6700
