### ISSUE TITLE
Image Block: Replacing Image can alter caption settings

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#66979]
### Description

When you have an Image Block (with Caption toggled off), and replace it with an Image from your Media Library that does have a caption, the Image Block gets its Caption setting toggled on (and uses the caption of the new Image block).  This doesn't feel like expected behavior at all in typical contexts, and is very annoying when dealing with Block Patterns.  Many of our Block Patterns make use of Image Blocks (withOUT captions).  When users customize the Pattern with their own Image, a Caption suddenly pops up where nobody intended one to be (and is very easy to miss).

### Step-by-step reproduction instructions

1. Insert an Image Block. Make sure its caption is Off.
2. Replace the media with an image from the Media Library that already has a Caption set
3. See that the Image Block gets its Caption setting toggled On (when it was off) and the caption is unexpectedly displayed

### Environment info

WordPress 6.7, no Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [x] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Mayank-Tripathi32** [comment]
@MadtownLems I am able to replicate the behavior and suspect it may be intentional; however, it could easily be perceived as a bug from a user’s perspective.

**Comment by t-hamano** [comment]
While the current behavior is intended, I agree that this is a bit confusing.

Even in the Classic Editor, when you replace an image, the caption for the new image appears.

**Comment by MadtownLems** [comment]
What's the process for debating making a change here? I think that
replacing an image and having the caption show up should never happen - but
I REALLY don't think it should happen in the context of a pattern (which I
believe is now possible to detect).

**Comment by t-hamano** [comment]
There has been some discussion about this issue in a few places. Let's close this issue and continue the discussion in #42834.
