### ISSUE TITLE
Add text alignment controls to List block toolbar

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6697]
## No way to align List blocks?
The Heading, Paragraph, and Subheading blocks all have text alignment controls in their block toolbars. (The Cover Image and Quote blocks do as well, but those blocks will soon be updated to use nested Paragraph and Heading blocks, so they do not really count.) For some reason, the List block currently lacks these controls.

## Solution
Add the text alignment button controls to the block toolbar of the List block.

## Related Issues and/or PRs
- #3785
- #5635
- #5880
- #6447 & #6525
- #6673 & #6675
- #6695
- #6696
- #6698
- #6699

**Comment by karmatosed** [comment]
I'm not sure also about adding these to list. What is your thinking of adding to list? I'll note as have in other issues maybe considering if something should have alignment is a good step over assuming it should in all blocks?

**Comment by karmatosed** [comment]
I'm not convinced lists are the same treatment but if someone wants to work on a PR that's totally fine by me on this.

**Comment by SuperGeniusZeb** [comment]
@karmatosed

I just discovered that just using `text-align: right` on a List does not work how I expected it to:

![image](https://user-images.githubusercontent.com/19592990/40182239-94788aba-59b0-11e8-868e-0e73d06b074b.png)

I was envisioning the List to be placed on the right, but the list items would retain proper indentation. This is possible if you modify the HTML like so:

```
<div style="display: flex; justify-content: end">
	<ul>
		<li>sfasfsad
			<ul>
				<li>sdfsdf</li>
				<li>sfsdfs</li>
			</ul>
		</li>
		<li>sfsfsd</li>
	</ul>
</div>
```
That produces a list that looks like this:

![image](https://user-images.githubusercontent.com/19592990/40182415-f630d078-59b0-11e8-9fcf-bfaf4f83573e.png)

Of course, this requires a wrapper `<div>` using `display: flex` and `justify-content: end`, so this is considerably more difficult to implement than I thought. It looks like the best way to have center or right-aligned lists is to use block alignment instead of text alignment.

So does this mean you should wrap the List block in something like the proposed Section block, or should block alignment tools be added to the List block?

**Comment by karmatosed** [comment]
Whilst I understand what you are saying regarding having this as an option, what use do you think there is for this as a real use case?

![2018-05-17 at 10 45](https://user-images.githubusercontent.com/253067/40194528-932e41fe-59bf-11e8-8a0f-b3b42e93a437.png)

The above is what it looks like in the current editor for example.

**Comment by SuperGeniusZeb** [comment]
@karmatosed That’s what I realized… **text** alignment on a List block is pretty much useless. It is some sort of **block** alignment that I now realize is what I really wanted. Should open a new issue for that and close this one?

**Comment by karmatosed** [comment]
I am still unsure you need it for lists but not against it as an option if you feel there is a use case. I can't see one right now so would encourage thinking about that first.

**Comment by gmfunk9** [comment]
Client has been using "align center" on lists for many years now. 
I'm attempting at remaking her site in a way she is used to using it

Adding text-align:center to my UL works perfectly, but it's not user-friendly in the Gutenberg editor
