### ISSUE TITLE
Add text alignment controls to Preformatted block toolbar

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6698]
## No way to align Preformatted blocks?
The Heading, Paragraph, and Subheading blocks all have text alignment controls in their block toolbars. (The Cover Image and Quote blocks do as well, but those blocks will soon be updated to use nested Paragraph and Heading blocks, so they do not really count.) For some reason, the Preformatted block currently lacks these controls.

## Solution
Add the text alignment button controls to the block toolbar of the Preformatted block.

## Related Issues and/or PRs
- #3785
- #5635
- #5880
- #6447 & #6525
- #6673 & #6675
- #6695
- #6696
- #6697
- #6699

**Comment by karmatosed** [comment]
I am not totally sure about adding it to this as the idea is the formatting is kept. What need can you see for having it beyond the others having it? I think it could be ok to not have every block having it.

**Comment by SuperGeniusZeb** [comment]
@karmatosed Now that I think about it, it does not really make sense to have text alignment options for the Preformatted block. I can not actually think of any use cases where that would be useful. I created this issue because I noticed the block lacked the controls while making the related issues, but in hindsight I do not see any reason to actually add the controls.

Closing this issue.
