### ISSUE TITLE
Preload script modules and enqueue script modules in wrong order

### ISSUE THREAD

**Issue by ajgagnon** [WordPress/gutenberg#66982]
### Description

In `WP_Script_Modules`, there is this order of output:

```php
add_action( $position, array( $this, 'print_import_map' ) );
add_action( $position, array( $this, 'print_enqueued_script_modules' ) );
add_action( $position, array( $this, 'print_script_module_preloads' ) );
```
This is adding a preload _after_ printing script modules. This is not always a problem, but can cause a race condition if assets are stored in the browser or served quickly. Dependencies may not load before dependent scripts.

### Step-by-step reproduction instructions

1. Add a script module with dependencies marked as "static"

```php
<?php
// instead, use a static loader that injects the script at runtime.
$static_assets = include trailingslashit( plugin_dir_path( __FILE__ ) ) . 'build/scripts/test/index.asset.php';
wp_register_script_module(
	'@my-plugin/test',
	trailingslashit( plugin_dir_url( __FILE__ ) ) . 'build/scripts/test/index.js',
	array(
		array(
			'id'     => '@wordpress/interactivity',
			'import' => 'static',
		),
	),
	$static_assets['version']
);
```

2. View the markup on the page source:

```html
<script type="module" src="https://mysite.com/wp-content/plugins/my-plugin/build/scripts/test/index.js?ver=0d40f7f88c7660867299" id="@my-plugin/test-js-module"></script>
<link rel="modulepreload" href="https://mysite.com/wp-includes/js/dist/script-modules/interactivity/debug.js?ver=d1c1c7faff86314c361a" id="@wordpress/interactivity-js-modulepreload">
```

The expected output should be the opposite, since the module requires `@wordpress/interactivity`

```html
<link rel="modulepreload" href="https://mysite.com/wp-includes/js/dist/script-modules/interactivity/debug.js?ver=d1c1c7faff86314c361a" id="@wordpress/interactivity-js-modulepreload">
<script type="module" src="https://mysite.com/wp-content/plugins/my-plugin/build/scripts/test/index.js?ver=0d40f7f88c7660867299" id="@my-plugin/test-js-module"></script>
```

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [x] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by yogeshbhutkar** [comment]
Thanks @ajgagnon for raising the issue. The fix for this seems to be made inside the core, so I've created a corresponding Trac Ticket here (https://core.trac.wordpress.org/ticket/62435) and have added a potential fix for the same.

Thanks for reporting the issue.

**Comment by ajgagnon** [comment]
Ah, great! Thanks for opening the Tract Ticket. Glad I could help! Would you like me to submit a PR?

**Comment by sirreal** [comment]
I'll close this to continue on the trac ticket https://core.trac.wordpress.org/ticket/62435.

**Comment by yogeshbhutkar** [comment]
Hi @ajgagnon.

There's some awesome discussion happening in this Trac Ticket (https://core.trac.wordpress.org/ticket/62435) about this particular issue and it would be helpful if you could provide your views on the Trac Ticket's discussion as you originally authored the issue here.

Thanks.
