### ISSUE TITLE
When I remove the Header in a template and and try to add a new header the slash command is not working

### ISSUE THREAD

**Issue by westnz** [WordPress/gutenberg#66984]
### Description

When I remove the Header in a template and try to add a new header, I can't type forward slash header. I tried it on a custom template, but also tested it on the Page no title template 

### Step-by-step reproduction instructions

1. Use the Twenty Twenty-Five theme
2. Go to Templates and add a custom template
3. Select the pattern
4. Delete the header
5. Select the Content block and select 'Add before'
6. You will notice that you can't use the slash command
7. If you click on the plus icon you can select a block

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/cffedec1-99fb-496a-b0b2-74157483ff37

### Environment info

- WordPress 6.7, latest version of Gutenberg
- Chrome
- MacBook Pro

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by yogeshbhutkar** [comment]
Hi @westnz, thanks for raising the issue.

I was trying to reproduce the issue, and followed the steps mentioned above, but seems like it's not happening with me and I'm unable to reproduce the issue.

### Environment Details:
WordPress Version: 6.8-alpha-59361
Gutenberg Plugin: 19.7.0-rc.1

### Additional Details
I also tried testing it on WordPress Version 6.7, but I'm unable to reproduce the issue.

### Screencast:
https://github.com/user-attachments/assets/18d1a378-0b5f-4adc-80b4-0a016e097344

**Comment by westnz** [comment]
I just tested it again, and it works now. Seems like the issue must've been resolved. Thank you @yogeshbhutkar
