### ISSUE TITLE
Add text alignment controls to Table block toolbar

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6699]
## No way to align the text in Table blocks?
The Heading, Paragraph, and Subheading blocks all have text alignment controls in their block toolbars. (The Cover Image and Quote blocks do as well, but those blocks will soon be updated to use nested Paragraph and Heading blocks, so they do not really count.) For some reason, the Table block currently lacks these controls.

## Solution
Add the text alignment button controls to the block toolbar of the Table block.

## Related Issues and/or PRs
- #3785
- #5635
- #5880
- #6447 & #6525
- #6673 & #6675
- #6695
- #6696
- #6697
- #6698

**Comment by karmatosed** [comment]
We have one issue focusing on for tables as a holistic iteration so closing this to focus there. #6923
