### ISSUE TITLE
Navigation Block : Font Size setting not working

### ISSUE THREAD

**Issue by pitamdey** [WordPress/gutenberg#67005]
### Description

In the Navigation Block Typography section, the font size setting is not functioning as expected. Changing the font size does not take effect unless we select a specific page link and adjust the font size directly.

If anyone has insights on the purpose of the Size setting in the Navigation Block, especially if font size adjustments can only be made by selecting individual page links, please let me know.

### Step-by-step reproduction instructions

1. Add Navigation Block
2. Go to "Typography" Section
3. Try to change the font size 

### Screenshots, screen recording, code snippet

https://www.loom.com/share/d734b839915d4766a8092d303a35da27?sid=72062109-546c-4a10-9e19-2b1276f685ce

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Mayank-Tripathi32** [comment]
@pitamdey  I’m unable to replicate the issue; everything appears to be working as expected on my end. Could you let me know which Wordpress version you’re using? Also, are there any third-party themes or plugins active?

https://github.com/user-attachments/assets/cf741a2d-ddbd-4d53-ae67-94b721643855

**Comment by kspilarski** [comment]
Hi @pitamdey @Mayank-Tripathi32 I tested this on a site with version 6.7, with the Twenty Twenty-Five theme and only Gutenberg plugin active, and was not able to replicate the issue reported. 

I was able to change the font size of the menu item (S, M, L, XL, XXL, or a specific size) and the font size change was reflected both in the editor and the live page. 

https://github.com/user-attachments/assets/4bfdd414-218f-4ffa-9c25-1e214754a7c2

Please check what your WP site version is, and test if your theme or a specific plugin is causing this issue.
