### ISSUE TITLE
Block lock "restrict editing" option no longer showing

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#67014]
### Description

It looks like the option to "restrict editing" for a block has been removed.  Any idea if that was intentional?  Very useful option to have to prevent clients from editing certain content. 

### Step-by-step reproduction instructions

1. Add a block (e.g. Heading block)
2. Click three dots and select Lock
3. See only two options available

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/b0a21679-ca40-4cf9-9b34-20cbf3f32d1b)

### Environment info

- wp 6.7
- gutenberg 19.6.2
- chrome
- mac

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Mamaduka** [comment]
Hi, @bradhogan 

The "Restrict editing" locking option is only available in Navigation and Pattern (Reusable) blocks. It was never visible for any other block types.

**Comment by bradhogan** [comment]
@Mamaduka Ok got it.  Do you have the ability to move this to a featured request in that case?  I don't see a downside to having the restrict editing available on every block.   Cheers.

**Comment by Mamaduka** [comment]
@bradhogan, the feature request to allow fully locking a block is being tracked here - #51968.
