### ISSUE TITLE
Conflict between Zoom Out mode and Distraction free mode

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#67025]
### Description

It is possible to have Zoom Out mode and Distraction free mode enabled at the same time via the zoom out toggle button or shortcuts.

Zoom out mode expects to insert patterns at the root level via the inserter, whereas Distraction free mode does not expect to insert blocks, resulting in a conflict.

### Step-by-step reproduction instructions

- Enable Distraction free mode.
- Click the Zoom out toggle button.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/96205bfd-273c-4e3f-b502-8173d850fe2f

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by yogeshbhutkar** [comment]
Thanks, @t-hamano for the issue.

Can you please describe the ideal behavior in this case? Do we allow inserter access when distraction mode is enabled and the content is zoomed out?

**Comment by t-hamano** [comment]
For now, I haven't come up with an ideal behavior. We also need to consider whether to allow both Zoom Out mode and Distraction free mode to be enabled.

**Comment by yogeshbhutkar** [comment]
@t-hamano, I think the ideal behavior should be to allow zooming out, but when the Distraction Free mode is enabled, then, when zoomed out, the Inserter Mode Button should ideally be disabled or should be made hidden.

**Comment by t-hamano** [comment]
> I think the ideal behavior should be to allow zooming out, but when the Distraction Free mode is enabled, then, when zoomed out, the Inserter Mode Button should ideally be disabled or should be made hidden.

In this case, we can't do anything in Zoom Out mode, right? I think the main purpose of Zoom Out mode is to be able to insert patterns at the root level.

**Comment by yogeshbhutkar** [comment]
@t-hamano Agreed!!!

Probably the feature ( zoom out ) can be used to view the content at a glance as well. Seems like a basic feature to have even after eliminating its association with the inserter, this can independently be used.

These two features conflict for sure, but I think limiting the Inserter of Zoomed Out state is the most efficient way to tackle the problem instead of either keeping Zoom out in its entirety or removing it completely when distraction-free mode is enabled.

I've raised a PR, the preview is attached as a screencast on the PR itself, will modify based on the flow of discussion that happens here.

Thank You.

**Comment by Mamaduka** [comment]
We should probably hide/disable the Zoom out toggle when in distraction-free mode. We do the same thing for Inserter, List View, Preview and others.

cc @richtabor, @draganescu

**Comment by yogeshbhutkar** [comment]
@t-hamano @Mamaduka, I've updated the PR accordingly with the expected behavior.

Thanks for your suggestions.

**Comment by draganescu** [comment]
I agree we should not show the zoom out control in DFM because the zoom out feature - for now at least - makes sense with the UI of the editor nearby to allow for quick building an iteration of high level content structure.
