### ISSUE TITLE
complianz-gdpr & languages plugins don't work in WordPress 6.7

### ISSUE THREAD

**Issue by DomZukInn** [WordPress/gutenberg#67037]
### Description

Hey team
After upgrading to WP 6.7 we received errors with Polylang/Languages plugin:

"Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the complianz-gdpr domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in /home/server/domains/dev1715885705.innsyte.com/public_html/wp-includes/functions.php on line 6114"

Please see screenshot attached. The error appears only on polish version of website.

After deactivating "Complianz GDPR plugin":"

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the wpforms-lite domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /home/server/domains/dev1715885705.innsyte.com/public_html/wp-includes/functions.php on line 6114

After deactivating "Polylang":

Everything works smoothly

### Step-by-step reproduction instructions

1. Install complianz-gdpr plugin
2. Install languages/Polylang![Image](https://github.com/user-attachments/assets/e02e9b3b-6fd7-49b8-b86d-0b0c3f3228a4)
 plugin
3. Set-up english and polish websites
4. Open any website in polish website

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/23f8a10d-6076-43c7-91df-38e7547d4c07)
![Image](https://github.com/user-attachments/assets/fad51de2-bb18-4088-9697-624f41383dc6)
![Image](https://github.com/user-attachments/assets/6d3ba9ea-c52a-451c-b701-8b5a88cc096e)
![Image](https://github.com/user-attachments/assets/54347fa2-6747-41e8-9944-c9f8c7f595cf)

### Environment info

- WP 6.7
- Microsoft Edge
- Languages/Polylang 3.6.5
- Complianz | GDPR/CCPA Cookie Consent 7.1.5

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Mamaduka** [comment]
Hi, @DomZukInn 

This repository is for Gutenberg/Block Editor project development. The issue you reported doesn't seem to be related to the project.

Please use [Polylang](https://wordpress.org/support/plugin/polylang/) or [Complianz GDPR](https://wordpress.org/support/plugin/complianz-gdpr/) plugin support forums  to report the issue.
