### ISSUE TITLE
Gutenberg Framework: Clarify and simplify how to load content styles

### ISSUE THREAD

**Issue by aks30498** [WordPress/gutenberg#67048]
### Description

I just followed the steps to bootstrap a basic editor and copied your code in my react project 

```import { createElement, useState } from "react";
import { createRoot } from "react-dom/client";
import { BlockEditorProvider, BlockCanvas } from "@wordpress/block-editor";
import { registerCoreBlocks } from "@wordpress/block-library";

// Default styles that are needed for the editor.
import "@wordpress/components/build-style/style.css";
import "@wordpress/block-editor/build-style/style.css";

// Default styles that are needed for the core blocks.
import "@wordpress/block-library/build-style/common.css";
import "@wordpress/block-library/build-style/style.css";
import "@wordpress/block-library/build-style/editor.css";

// Register the default core block types.
registerCoreBlocks();

function Editor() {
  const [blocks, setBlocks] = useState([]);
  return (
    /*
      The BlockEditorProvider is the wrapper of the block editor's state.
      All the UI elements of the block editor need to be rendered within this provider.
    */
    <BlockEditorProvider
      value={blocks}
      onChange={setBlocks}
      onInput={setBlocks}
    >
      {/*
          The BlockCanvas component renders the block list within an iframe
          and wire up all the necessary events to make the block editor work.
        */}
      <BlockCanvas height="500px" />
    </BlockEditorProvider>
  );
}


createRoot(document.getElementById("root")!).render(<Editor />);
```
But the editor styles are off, it is missing a lot of styles and looks ugly, also, I tried using text align on paragraph and it does not work so I believe a css is not getting loaded, I tried to debug, the css file is being imported and the file has classes for alignment but when I inspect the pargraph element, I cannot see the classes in styles tab 

### Step-by-step reproduction instructions

create a new react project and siply paste the example in docs.

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/812fb265-f176-4666-bf6a-3332028e242c)
![Image](https://github.com/user-attachments/assets/52639276-9ef2-413f-a9da-8746aad9908c)

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by ramonjd** [comment]
Could you link to the example you're working from?

What I think is happening is that the CSS required to style blocks is there, but it's not available in the editor iframe.

`<BlockCanvas />` has a styles prop that accepts the following value:

```js
const styles = [ { css: 'body { ... } ... ' }, { css: '.test { ... } ... ' }  ];
```

Each item in the array will be rendered inside a style tag inside the iframe.


To get align styles to work I had to raw import the `@wordpress/block-library/build-style/common.css` module and pass it to `<BlockCanvas />` .

Example:

```js
import common from "!!raw-loader!@wordpress/block-library/build-style/common.css";
const styles = [
	{
		css: common,
	},
];

....

<BlockCanvas height="100%" styles={ styles } />

```


Here's what I also imported to get it working:

```jsx
import "@wordpress/block-library/build-style/common.css";
import "@wordpress/block-library/build-style/style.css";
import '@wordpress/components/build-style/style.css';
import '@wordpress/block-editor/build-style/style.css';

```

https://github.com/user-attachments/assets/9bd9eb57-9329-4ab6-afe6-c7a7c3a1e4ba

Also, add `import '@wordpress/format-library';` if you want the formatting tools in the toolbar.

Having said all that, I don't know if that's the correct way of going about all this, and if the docs are wrong or need to be updated.

cc @WordPress/gutenberg-core for tips.


I also noticed there's a prop called `shouldIframe`, which is `true` by default, but it's not passed to the inner component, so it does nothing.

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-canvas/index.js#L132

**Comment by youknowriad** [comment]
Good point, worth noting that we don't have a lot of feedback on the "Gutenberg Framework" use-case, so I'm very happy to see this bug report. 

What @ramonjd is saying is correct, I think our documentation doesn't explain this properly, so we need to fix the documentation here.
But also, we need to make it easier to load the "required content styles" into the block editor without too much boilerplate, with the "required content styles" I'm referring to:

 - content styles that come in `block-editor` package.
 - content styles that come in `components` package potentially (placeholders).
 - default block library content styles.

We should also document all of that properly in the "platform docs".

cc @ellatrix as she worked on content styles and also some third-party Gutenberg editors.

**Comment by aks30498** [comment]
@ramonjd I don't get it sorry, I tried the !!raw-loader line and it throws error, can you fix it in my code may be please ? 

Example I used is from here 
https://github.com/WordPress/gutenberg/blob/trunk/platform-docs/docs/intro.md

**Comment by ramonjd** [comment]
> I tried the !!raw-loader line and it throws error

Sorry if that was a bit confusing, @aks30498- it was just meant to be example code. 

In my local development environment, I'm using webpack to build assets and raw loader will import the contents of the styles file as they are:

https://www.npmjs.com/package/raw-loader

To get your example working you'll need the contents of `@wordpress/block-library/build-style/common.css` loaded into the block editor iframe. 

I think we should update that example.

**Comment by aks30498** [comment]
> > I tried the !!raw-loader line and it throws error
> 
> Sorry if that was a bit confusing, @aks30498- it was just meant to be example code.
> 
> In my local development environment, I'm using webpack to build assets and raw loader will import the contents of the styles file as they are:
> 
> https://www.npmjs.com/package/raw-loader
> 
> To get your example working you'll need the contents of `@wordpress/block-library/build-style/common.css` loaded into the block editor iframe.
> 
> I think we should update that example.

@ramonjd Can you help me with this in vite ? I tried using ?inline and ?raw to import common.css in a variable but it keeps throwing common.css has no default export

**Comment by ramonjd** [comment]
> Can you help me with this in vite ? I tried using ?inline and ?raw to import common.css in a variable but it keeps throwing common.css has no default export

Apparently you can specify a file extension in the [vite.config.js es loader option](https://github.com/vitejs/vite/issues/13493#issuecomment-1588791892). Theoretically, `?raw` should work according to the [docs](https://vite.dev/guide/assets.html#importing-asset-as-string). I don't know if that helps you.

Without knowing anything else about your app, I don't think I can be of much help unfortunately. You might like to look at how @ellatrix imports editor CSS dependencies using vite: https://github.com/blocknotes-org/blocknotes/blob/0857170afd81a144d746dce9d3964538766d4b02/src/editor.jsx#L16

I know it's not all exactly straight forward. 🙃 

When I said [above](https://github.com/WordPress/gutenberg/issues/67048#issuecomment-2510250171) that the example should be updated, I agree with you and think that the public example in the Gutenberg docs needs to reflect a working example.

**Comment by aks30498** [comment]
@ramonjd Thanks for the help! The ?raw should work, but I might be missing something in setup I guess, I am new to vite as well, I just wnat the gutenberg to work in my setup, building something on top of it and if I can use the system already build by wordpress it will save a lot of effort. 

@ellatrix Can you help with the import plz ? I tried importing css as string and passing to the BlockCanvas styles prop just like @ramonjd did using ?raw and ?inline but it just breaks saying common.css has no default export, I saw your working code which was linked in above comment has similar ?raw suffix for light.css for example, what might I be missing ?

**Comment by stokesman** [comment]
@aks30498, importing `@wordpress/block-library/build-style/common.css` is not necessary because that file is already built into `@wordpress/block-library/build-style/style.css`.

This was closed since #61341 which now includes passing the `styles` prop to `BlockCanvas`. If you try the latest instructions and are still having issues then leave a reply and I’ll try to help. Please note the whole intro was overhauled and it’s now recommended to use the React starter/variant from `npm create vite@latest`. So it would be a good idea to start fresh from that.

**Comment by ramonjd** [comment]
Thank you @stokesman !!

**Comment by aks30498** [comment]
@stokesman Thanks, it works with new docs, I have a few questions though, having used the latest version of all libs, there are loads of TS errors in the docs example that shows how to use history (undo-redo) but leaving that aside the most irritating one is that it says BlockCanvas is not exported from @wordpress/block-editor while it surely is coz it is working. 

Also, while I can apply height to BlockCanvas , there is no width prop available, I wish to create a Canva like canvas for my users where they can design things using block builder, but I can't specify width am I missing something ?

**Comment by stokesman** [comment]
@aks30498, I'm glad the latest instructions are working for you. It is unfortunate about all the TS errors. I agree they are quite a nuisance. For the time being, you'll have to bear with it but work going into #67691 should resolve all of that.

> Also, while I can apply height to BlockCanvas , there is no width prop available, I wish to create a Canva like canvas for my users where they can design things using block builder, but I can't specify width am I missing something ?

I suppose it's expected that the width is be determined by the parent component. `BlockCanvas` should be the full width of its parent by default.

**Comment by aks30498** [comment]
@stokesman I was wondering, are the docs not done on this package yet? I left dev on the project for a while, getting back to it I wanted to create similar UI as Gutenberg in wordpress (with the sidebars doing exactly what they do) in react. But I keep getting lost, I looked at npm page and a lot of components say "undocumented component". Is there a simple way in React to just make it same as wordpress plugin? I can create custom blocks looking at docs later. 

I tried using Inserter component in the left sidebar but it gives me a + icon which opens a popup with the options which I want to be visible right away in the sidebar, but cannot find a component for that.

Also, text align center has started to work for me, but when I try to center image, it does not work

**Comment by stokesman** [comment]
> I was wondering, are the docs not done on this package yet? … I looked at npm page and a lot of components say "undocumented component".

I would say the docs are far from done. Regarding the individual components there is on going work to document them tracked by #22891. If a component you want to use is undocumented you could check that issue to see if it has a PR in progress and maybe that could help. Of course, if you want to contribute to that effort, it would be appreciated.

> Is there a simple way in React to just make it same as wordpress plugin?

If your project is meant to be a WordPress plugin then `@wordpress/editor` has much higher level components that would make it simpler but it sounds like you’re interested in making something separate. `@wordpress/interface` has the `InterfaceSkeleton` component that should provide the same layout as used in the WP editors but I can’t say whether it would suit your use case.

> I tried using Inserter component in the left sidebar but it gives me a + icon which opens a popup with the options which I want to be visible right away in the sidebar, but cannot find a component for that.

It sounds like you could be looking for [`InserterLibrary`](packages/block-editor/src/components/inserter/library.js) which is exported from `@wordpress/block-editor` as `__experimentalLibrary`. It’s lacking any docs right now.

BTW, I didn’t know the name/location of that component from experience. I had to inspect with React dev tools on a WP site and figure it out. I recommend doing the same if there’s a component that interests you. It can be tedious. Even once you find the component, in many cases it’ll take reading its source and/or examining where and how it’s used to guide your own usage.

> Also, text align center has started to work for me, but when I try to center image, it does not work

I find the same thing now that I’ve tried it. Also, all the layout styles (for blocks like Row/Stack/Grid) are not working. I’d assumed they would be. Thanks for bringing this up. I think it probably merits a new issue and it looks like more than just documentation updates because, so far, I don’t see how the built-in layouts can be applied in this context. It’s possible to add your own styles for them (through the `styles` prop of `BlockCanvas`) but that doesn’t seem like it should be necessary.
