### ISSUE TITLE
Grammarly causing WordPress to shake while in editing mode

### ISSUE THREAD

**Issue by westnz** [WordPress/gutenberg#67058]
### Description

Screen shaking while in editing mode. It disappeared for some users when they turned Grammarly off. 

### Step-by-step reproduction instructions

1. Edit your site or write a P2 post while having Grammarly installed on your site.
2. I'm unsure if you will be able to reproduce this issue, as only some folks indicated that they experienced it. I'm also unsure if the issue has been resolved, but we probably want to avoid this from happening again. Someone also wrote: "It looks like Grammarly has shipped an update. I can no longer replicate my original issue in the post editor." I can also confirm that I experienced this problem. 
3.  Please see this thread from the .Org Forum: https://wordpress.org/support/topic/wordpress-shaking-while-in-edit-mode/#post-18139467

### Environment info

- WordPress 6.7
- Chrome
- MacBook Pro

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by kspilarski** [comment]
Hello @westnz thanks for reporting! I tested this on my site with version 6.7 and Grammarly installed in Chrome, but didn't experience any shaking.  What happens if you remove Grammarly, and then clear your browser cache?

**Comment by talldan** [comment]
If the problem goes away when Grammarly is turned off, then it should be reported to them. Has anyone done that?

It's fine to have a report here as well, but with these things it's very hard to tell whether it's a WordPress problem, a Grammarly problem, or even a problem with a particular browser without lots of information.

Some things that would be useful to know:
- Does it happen in particular browsers or on particular operating systems?
- Does it happen in particular WordPress versions?

It could be that it happened to users on older WordPress versions, but has been resolved in newer versions - or perhaps the other way round it was introduced in a newer WordPress version. It if happens across lots of WordPress versions, but only started recently, then it's very likely a Grammarly issue or a problem with a particular browser.

**Comment by westnz** [comment]
> Hello @westnz thanks for reporting! I tested this on my site with version 6.7 and Grammarly installed in Chrome, but didn't experience any shaking. What happens if you remove Grammarly, and then clear your browser cache?

I actually did clear my cache on Friday, but I also turned Grammarly off for a while. I can't reproduce this either now.

> If the problem goes away when Grammarly is turned off, then it should be reported to them. Has anyone done that?

That is why I created this Issue, as I am unsure if someone reported it.

> Does it happen in particular browsers or on particular operating systems?

I used Chrome

> Does it happen in particular WordPress versions?

These Forum messages came after 6.7 landed. 8 people responded to this thread: https://wordpress.org/support/topic/wordpress-shaking-while-in-edit-mode/#post-18139467. T

**Comment by talldan** [comment]
> That is why I created this Issue, as I am unsure if someone reported it.

I meant that it should be reported to Grammarly, not only to WordPress 😄 

Anyway, I've heard from someone else I work with that the issue was resolved after the Grammarly extension was updated. I've dropped a message in that forum thread asking if folks can confirm that and if they can (or there's no reply) I'll close the issue.

**Comment by kspilarski** [comment]
Sharing here as well - there was a similar issue opened in Trac https://core.trac.wordpress.org/ticket/62442  - the issue is closed as it was caused by Grammarly, an external browser extension.

> I meant that it should be reported to Grammarly, not only to WordPress 😄

I agree. Thanks for checking in with the folks in the forums!

**Comment by westnz** [comment]
> I meant that it should be reported to Grammarly, not only to WordPress 😄

Gotcha 😉 

Thank you, both!!
