### ISSUE TITLE
Filterable block inspector tabs

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#67054]
## Block inspector tabs

Block inspecor tabs are defined in `packages/block-editor/src/components/inspector-controls-tabs/use-inspector-controls-tabs.js`.
I have a need to add custom tab for my block. The easiest way to achieve that would be to add filter in the source to allow adding custom tabs.

**Comment by aminul-xs** [comment]
[Block Inspector Tabs](https://github.com/WordPress/gutenberg/issues/59115)

**Comment by talldan** [comment]
Closed as a duplicate of #59115
