### ISSUE TITLE
Styles > Typography: Custom typesets can not be selected, theme typesets can not be deselected

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#67064]
### Description

When you have a block theme active, and the theme registers typography presets, the user can select between them in the Styles sidebar > Typography. By default, the first preset is selected:

![Image](https://github.com/user-attachments/assets/0d02c3ce-1b13-4e8b-84d5-d2273a6998a9)

But if a user opens "Manage fonts" and installs a new font and saves, it is saved as a custom style.
The new font is listed in the Fonts section, and the theme typeset is no longer shown as being selected: it has no dark border:
![Image](https://github.com/user-attachments/assets/8fb59f04-4743-4743-a103-5b3e8ec96b1f)

Next, if the user clicks on any theme typeset, they have no way to re-select their custom style in the interface.
- There is no button or similar that the user can click on to select their custom typeset.
- The theme typeset can not be deselected: I thought that clicking on a typeset twice might unset it, but no.

The only way to get back to the custom typeset is to refresh the page before saving, or, if you have already saved, use the revisions.

### Step-by-step reproduction instructions

Activate Twenty Twenty-Five.
Open the Site Editor
Open the Styles sidebar
Open the Typography panel, and next to the label that says FONTS, click on the icon that has the tooltip "Manage fonts"
Install a new font.
Save.

Select a typeset under the label TYPESETS
The theme typeset is selected.

Try to get your customized typeset back.

### Environment info

WordPress 6.7.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by carolinan** [comment]
Could the customisation be added as a button last on the list of typesets? And all it would do is unset the selection of the theme typeset?

**Comment by carolinan** [comment]
Originally reported here:
https://wordpress.org/support/topic/manage-fonts-not-showing/

**Comment by matiasbenedetto** [comment]
A related issue: https://github.com/WordPress/gutenberg/issues/59574

**Comment by carolinan** [comment]
> Another issue I found is that after setting a preset, it can't be unset. I would expect that if I clicked the preset again, it would be unset. In the screencast, I click several times on the preset, but it is not unset.

That's exactly it, thank you @matiasbenedetto Let's close this one.
