### ISSUE TITLE
Pullquote Block: Spacing inconsistency between editor and frontend

### ISSUE THREAD

**Issue by SainathPoojary** [WordPress/gutenberg#67067]
### Description

There is a spacing inconsistency in the Pullquote block between the editor and the frontend.

Expected behavior:
The spacing inside the `<blockquote>` tag in both the editor and the frontend should remain consistent. For example, in the Twenty Twenty-Five theme, the spacing is set to --wp--preset--spacing--30 (20px), which should apply consistently.

Current behavior:
In the editor, the spacing above the <cite> element is consistent with the theme’s expected spacing. However, on the frontend, the <cite> tag introduces additional unintended space, causing the overall spacing to exceed the expected value.

### Step-by-step reproduction instructions

1. Open a post or page in the WordPress editor.
2. Insert a Pullquote block and add content, including a citation.
3. Observe the spacing inside the `<blockquote>` tag in the editor.
    - For the Twenty Twenty-Five theme, this spacing should be --wp--preset--spacing--30 (20px).
4. Publish the post or page and view it on the frontend.
5. Compare the spacing above the `<cite>` tag between the editor and the frontend.

#### Editor:
![Image](https://github.com/user-attachments/assets/87303538-5daa-4be4-a061-a3332d52f5d4)

#### Frontend:
![Image](https://github.com/user-attachments/assets/d9687573-d82a-43fd-bbc2-53f462f0edf8)

### Environment info

- WordPress: 6.8-alpha-59409
- PHP: 8.2.25
- Server: Apache/2.4.62 (Debian)
- Database: mysqli (Server: 11.4.4-MariaDB-ubu2404 / Client: mysqlnd 8.2.25)
- Browser: Chrome 131.0.0.0
- OS: macOS
- Theme: Twenty Twenty-Five 1.0
- MU Plugins: None activated
- Plugins: Gutenberg 19.7.0-rc.2

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by rinkalpagdar** [comment]
Hello @SainathPoojary 
I have tested your PR changes and it's working fine for me.
Thanks!

**Comment by ellatrix** [comment]
Closing after this comment: https://github.com/WordPress/gutenberg/pull/67068#issuecomment-2519885927
