### ISSUE TITLE
Edge case: The editors break if the pattern category taxonomy is unregistered

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#67060]
### Description

The `wp_pattern_category` is [a taxonomy registered on the `wp_block` post type](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/taxonomy.php#L226).

It can be unregistered using [unregister_taxonomy_for_object_type](https://developer.wordpress.org/reference/functions/unregister_taxonomy_for_object_type/)

If the taxonomy is unregistered, the editors break with the following JavaScript error:

```
react-dom.min.js?ver=18:1 TypeError: Cannot read properties of undefined (reading 'map')
    at Pe (private-selectors.js:333:47)
    at private-selectors.js:394:6
    at Array.map (<anonymous>)
    at private-selectors.js:393:6
    at s (rememo.js:270:18)
    at r (factory.js:56:10)
    at r (index.js:249:13)
    at selectors.js:2482:22
    at s (rememo.js:270:18)
    at r (factory.js:56:10)

```

![Image](https://github.com/user-attachments/assets/57b78e15-d343-471f-83a7-17b35250b2cf)

I am not sure what the use case would be: But since unregistering is supported by WordPress, the editors should not break if it happens.

### Step-by-step reproduction instructions

Unregister the taxonomy. For example, copy the following to functions.php in your active theme:

```
add_action( 'init', 'unregister' );
function unregister() {
	unregister_taxonomy_for_object_type( 'wp_pattern_category', 'wp_block' );
}
```

Create a new post. Confirm if there is a JavaScript error.

### Environment info

I am using WordPress 6.7 with Gutenberg trunk and:

```
define( 'WP_DEBUG', true );
define( 'WP_DEVELOPMENT_MODE', 'theme' );
define( 'WP_ENVIRONMENT_TYPE', 'local' );
```

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by im3dabasia** [comment]
I was able to reproduce the error, and after testing the patch, I can confirm that it resolves the issue.

**Comment by carolinan** [comment]
I have set this to low priority because I believe that unregistering this taxonomy would be a very uncommon edge case.
