### ISSUE TITLE
Create an eslint rule to use memize not lodash's memoize

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#6707]
I didn't realise we should be using [memize](https://www.npmjs.com/package/memize) over lodash's built-in `memoize`, pointed out here: https://github.com/WordPress/gutenberg/pull/6686#discussion_r187601035

I forget if we can make an eslint rule preventing us from importing it or at least warning us about it, but if so I'll make a PR so it doesn't happen again 😄

**Comment by aduth** [comment]
Potential implementation reference:

- https://eslint.org/docs/rules/no-restricted-syntax
- https://eslint.org/docs/developer-guide/selectors
