### ISSUE TITLE
Template level blocks can be unlocked and moved when template preview is active

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#67082]
In WordPress 6.7 there is a regression in the handling of Blocks that are part of the template but that remain editable. 

For example the post title or the post featured image blocks remain editable when they are part of the template when the "Show Template" option is enabled in the editor.

In WordPress 6.7 these blocks now suddenly show a lock icon in their block toolbar. Clicking that allows editors to unlock and then move them. 

This moving doesn't get persisted luckily. But it still created a broken editorial experience for users. 

https://github.com/user-attachments/assets/c947f1fc-e9a9-44ea-b6a8-316c32b82009

**Comment by fabiankaegy** [comment]
Looking further into this it appears this has already been fixed in Gutenberg. So we need to find the PR and add that to the backport list 

![Image](https://github.com/user-attachments/assets/eb2e1436-fe72-4533-ad9f-ac368bf058e9)

**Comment by youknowriad** [comment]
Hey folks, this seems to be a 6.7 only bug, I can't reproduce on Gutenberg trunk. I think it might be related to the block toolbar updates that were done specifically on that branch. Any ideas @getdave @ellatrix

**Comment by getdave** [comment]
Nothing springs to mind. There was a lot of divergence between `trunk` and `wp/6.7` during the Beta/RC period as `trunk` continued to evolve in/around Zoom Out and changes to "Write mode" so it would have been easy for something to have been missed.

Also cc @cbravobernal who is leading 6.7.X releases from Editor side.

**Comment by getdave** [comment]
I noticed `isDefaultEditingMode` seems to be missing from the `packages/block-editor/src/components/block-toolbar/index.js` file in `wp/6.7` but it is there in `trunk`.

https://github.com/WordPress/gutenberg/blob/c43a0c9944b33ad01fa2805a02a171b42b791282/packages/block-editor/src/components/block-toolbar/index.js#L205-L209

I tried adding it in and it seemed to fix things.

Haven't had much time to test but here is [a PR](https://github.com/WordPress/gutenberg/pull/67121)

**Comment by t-hamano** [comment]
#66200, which was manually backported to wp/6.7, appears to be related.

[Here](https://github.com/WordPress/gutenberg/pull/66200/files#diff-9ac2a4466e7c0a85aaff0b40c5d7bc64c894132528ca3c879db4bebb438617dcL186-L188), both `isDefaultEditingMode` and `isContentOnlyEditingMode` were removed. The removal of `isContentOnlyEditingMode` seems to have been intentional, but the removal of `isDefaultEditingMode` might not have been.

**Comment by getdave** [comment]
So can we tweak https://github.com/WordPress/gutenberg/pull/67121 to resolve?

**Comment by cbravobernal** [comment]
Punting this to 6.8 as it seems there won't have time to fix it for 6.7.2.

**Comment by youknowriad** [comment]
Well in that case, we should close it since it works normally on trunk right?

**Comment by t-hamano** [comment]
Yes, I think this issue can be closed.

@cbravobernal #67121 targets the `wp/6.7` branch and has already been merged, so the problem reported in this issue should be fixed in WP 6.7.2

**Comment by t-hamano** [comment]
Removing the `Backport to WP Minor Release` label as this issue has already been fixed in the 6.7 release.
