### ISSUE TITLE
Unify navigation styles between Data Views and font navigation

### ISSUE THREAD

**Issue by juanfra** [WordPress/gutenberg#67123]
## What problem does this address?

The navigation styles between the Data Views and the Font Navigation are inconsistent, leading to a fragmented user experience. Below are two screenshots highlighting the differences.

| Navigation in Data Views | Navigation in the Fonts section  |
| --- | --- |
|  ![Image](https://github.com/user-attachments/assets/945956cf-7cde-4961-bf58-8f3c652021c6) | ![Image](https://github.com/user-attachments/assets/ea3ceefd-b729-4e7b-a80f-11ec4231d704) |

## What is your proposed solution?

To improve consistency and usability, I propose updating the navigation in the fonts section to align with the style used in Data Views. This would create a more cohesive interface and enhance user familiarity.

 ![Image](https://github.com/user-attachments/assets/a802d0d9-1513-4a63-9fa4-f4283a365f56)

**Comment by matiasbenedetto** [comment]
Potential fix for this: https://github.com/WordPress/gutenberg/pull/67143
