### ISSUE TITLE
Add template name as a CSS class in the editor

### ISSUE THREAD

**Issue by colinduwe** [WordPress/gutenberg#67179]
## What problem does this address?
I have a theme with page templates that have different background colors. If the user swaps the template, the editor's background color should match the front end. But currently the page template slug isn't added as a class to the editor like it is to the <body> on the front end.

## What is your proposed solution?
I worked around it by adding it via the admin_body_class filter but it would be nice to add it on the editor automatically.

**Comment by ellatrix** [comment]
Related: #56831, #17854, #10640. Could also be considered a duplicate of #59108.

**Comment by colinduwe** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/17854
