### ISSUE TITLE
Query Loop block: remove "add new post" prompt in the sidebar

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#67177]
When using the Query Loop block, there's a link to "add new post" in the description of the block. If you click on this, it brings you to the post editor. While I understand the intent to try to explain to someone that to have posts show up here, especially in an empty state, you need to add new posts I think this flow does more harm than good. By taking them out of the editor to publish a post, we never close the loop then to the Query Loop block unless the user knows to return and how. As a result, I think we should remove this right now.

https://github.com/user-attachments/assets/91da798d-1db6-463e-ab7f-b23812e002c8

**Comment by Mayank-Tripathi32** [comment]
Hi @annezazu,

I believe opening the window in a new tab would be a better solution. This way, users can learn how to add a post without accidentally losing their current changes.

**Comment by yogeshbhutkar** [comment]
Hi @annezazu,

Thank you for raising this issue. I believe it might primarily confuse users who are relatively new to the Query Loop Block and possibly WordPress in general. However, it’s unlikely to significantly impact users with some familiarity with WordPress.

An alternative approach could be the solution proposed by @Mayank-Tripathi32, as it retains the previously active Query Block window while also guiding users on how to return to the parent Query Block post after creating a new post using the Add New Post link.

Additionally, I’m listing my PR here, as it aligns with the anticipated solution for this issue. However, I feel this matter requires design feedback before proceeding further.

Thanks!

**Comment by annezazu** [comment]
I'll note that accessibility wise we don't want to open up new tabs [due to these guidelines](https://www.w3.org/TR/WCAG20-TECHS/G200.html):

>The objective of this technique is to limit the use of links or buttons that open new windows or tabs within Web content. In general, it is better not to open new windows and tabs since they can be disorienting for people, especially people who have difficulty perceiving visual content.

At this point, I'd rather remove as again I don't think opening in a new tab will lead to a better experience or more understandable connection to the Query Loop block. 

Thanks for working on this PR!

**Comment by t-hamano** [comment]
I agree with removing this link.

The suggestion to add this link, #23461, was submitted about 4 years ago. This link may have made sense back then, when Gutenberg didn't even have a site editor, but I'm not sure it's useful to many users today.

cc @mtias @ntsekouras

**Comment by ntsekouras** [comment]
Personally, I think it's fine to remove.

**Comment by t-hamano** [comment]
Thanks for the feedback! Now let's move forward with #67189 to remove this link.
