### ISSUE TITLE
Make `lerna` a dependency rather than a devDependency

### ISSUE THREAD

**Issue by nerrad** [WordPress/gutenberg#6718]
**Describe the bug**
For context see #6658 .  My plugin (I'm assuming others might as well) has GB/master defined as a devDependency because we use gutenberg in jest unit tests.  However, since the mentioned pull was merged in we're getting [failed builds in travis](https://travis-ci.org/eventespresso/event-espresso-core/jobs/377880482).  Specifically, this is the cause:

```bash
> gutenberg@2.8.0 postinstall /home/travis/build/eventespresso/event-espresso-core/node_modules/gutenberg
> lerna bootstrap --hoist
sh: 1: lerna: not found
```

@aduth and I had a [chat about this in slack](https://wordpress.slack.com/archives/C02QB2JS7/p1526067807000549) and it looks like one resolution would be to move lerna from being a devDependency to being a dependency.

Other solutions could be removing the post-install script, or modifying it so it only runs in the context of Gutenberg itself.

**Comment by ntwb** [comment]
No objections to this from me.

Once we've got all the modules published we should add/update the docs on including Gutenberg and its modules for running tests as you are in your eventespresso repo.

**Comment by gziolo** [comment]
I guess it's a temporary solution until we have all packages published. Let me open PR for that.

**Comment by aduth** [comment]
>In general, you shouldn't need to do it.

Can you clarify what's meant by "it" here? Installing Gutenberg as a dependency?

To me, the general issue is that anything used by `postinstall` should be defined as a `dependencies`, since these are run automatically by consuming projects and the consuming project won't install `devDependencies`.
