### ISSUE TITLE
"Test has no assertions" lint rule is very annoying when writing tests

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#67185]
The "Test has no assertions" lint rule makes it very hard to see what you're doing when you're in the process of writing tests:
<img width=300 src="https://github.com/user-attachments/assets/35901888-6e9d-4853-9602-c4560956bef2" />

I haven't gotten to the point where I want to add an assertion yet. There are squigly yellow lines everywhere! I should be able to add assertions in my own time.

This might depend on the IDE/plugins being used, but I think my setup is a pretty standard one.

I'd suggest disabling this unless it can be improved as it's a bad experience for contributors. For me, this discourages writing tests.

**Comment by Mamaduka** [comment]
100%. This was super annoying when I was migrating tests to Playwright. Sure, you can start a simple test with assertion, but that's rarely the case in this project.

**Comment by manzoorwanijk** [comment]
It was fixed in https://github.com/jest-community/eslint-plugin-jest/pull/1452.

I have created #67222 to update the package and fix the issue.
