### ISSUE TITLE
Documentation: In the wild Plugins

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#6719]
I am starting this issue to get an overview of block plugins being made in the wild to inspire and learn from. Perhaps some of the features can in some form or another also find its way into Gutenberg Core. (There are A LOT of block plugins out there. It is good to get an overview of what is being created as it shows which blocks are missing from Gutenberg Core.)

**https://block-options.com/**
Devices Visibility Options, User Login State, Display Logic, User Roles Restriction, Per Days Visibility, Date Range Visibility, Custom Block Links, Custom Alignment per Devices and more.

**https://wordpress.org/plugins/stackable-ultimate-gutenberg-blocks/**
Card, Pricing box, Header, Count up, Video Popup, Testimonials, Team Members, Call to Action, Notification, Blockquote (Improved!), Pullquote, Number box, Button (Improved!), Ghost Button, Expand / Show more, Divider (Improved!), Spacer and more.

**https://github.com/WebDevStudios/WDS-Blocks**
Hero, Call To Action, Recent Posts Grid, Multi-select, Related Posts Grid, Two Column Layout, Github Gist, Users Grid and more.

**https://wordpress.org/plugins/map-block-gutenberg/**
Maps Block for Gutenberg powered by Google Maps.

**https://wordpress.org/plugins/gutenberg-custom-fields/**
Gutenberg Custom Fields

**https://wordpress.org/plugins/disable-gutenberg/**
Disable Gutenberg

**https://wordpress.org/plugins/unregister-gutenberg-blocks/**
...unregister default Gutenberg Blocks and keep only those you really need.

**https://wordpress.org/plugins/manager-for-gutenberg/**
Gutenberg Manager

**https://profiles.wordpress.org/coblocks#content-plugins**
Gutenberg Block plugins by CoBlocks
Additional blocks being planned (or already released) are: 
Accordion Block, Alert Block, Author Block, Click to Tweet Block, Dynamic HR Block, Gif Block, GitHub Gist Block, Spacer Block, Social Sharing Block.

**https://wordpress.org/plugins/advanced-gutenberg-blocks/**
Notice, Post, WooCommerce Product, WooCommerce Add to cart button, Banner Ad, Text + rectangle Ad, WordPress Plugin Card, Website Card preview, Testimonial and Google Map.
Additional features: Deactivate blocks, centralized settings, Extensible and more.

**https://wordpress.org/plugins/atomic-blocks/**
Testimonial Block, Inline Notice Block, Accordion Block, Share Icons Block, Call-To-Action Block, Customizable Button Block, Spacer & Divider Block, Author Profile Block and Drop Cap Block.

**https://wordpress.org/plugins/blocks-for-gutenberg/**
Sidenote

**https://wordpress.org/plugins/advanced-gutenberg/**
Create edition profiles, Activate lightbox effect, custom CSS styles, post summary based on content headers, create button with more styles, advanced List block, Testimonial block, Counter block, Advanced Image block and Supercharge the separator tool.

**https://wordpress.org/plugins/feature-block-gutenberg/**
Use Gutenberg to create Feature Blocks – blocks that provide information about key features.

**https://wordpress.org/plugins/aceblocks/**
Block Type - description, Testimonial, Alert, Icon Block, Social Block and Image Block.

**https://wordpress.org/plugins/faq-block-for-gutenberg/**

**https://wordpress.org/plugins/advance-video-for-gutenberg/**

**https://wordpress.org/plugins/woo-gutenberg-products-block/**
This block is a custom products area that features your WooCommerce products. 

**https://wordpress.org/plugins/share-block/**
Super social share block

**https://wordpress.org/plugins/pillar-press-content-blocks/**
Spacer Block and Notices Block.

**https://wordpress.org/plugins/reusable-gutenberg-blocks-widget/**
Easily display WordPress Gutenberg Editor saved reusable blocks anywhere via widget.

**https://wordpress.org/plugins/organic-profile-block/**
This custom block is designed to display personal profiles. It includes options to add a profile image, name, title, biography, and social media links.

**https://wordpress.org/plugins/advanced-content-blocks/**
Tabs

**https://wordpress.org/plugins/form-blocks/**
Adds a new contact form block.

**https://wordpress.org/plugins/block-background/**
Extend gutenberg blocks with additional background options.

**https://wordpress.org/plugins/summary-and-details/**
This plugin adds a Gutenberg block which provides details with an optional summary.

**https://wordpress.org/plugins/sword-layouts/**
Create more interesting and modern page designs.

**https://wordpress.org/plugins/qr-code-block/**
The QR-Code Block gives you the ability to create QR-Code Blocks in the Gutenberg editor.

**https://wordpress.org/plugins/wpblocks/**
Info Box, Social Icons and Empty Space.

**https://wordpress.org/plugins/ultimate-blocks/**
Call to Action Block, Click to Tweet, Divider Block, Feature Box Block, Notification Box Block, Number Box Block, Testimonial Block, Spacer Block.

I just had to add this in:
**https://wordpress.org/plugins/advanced-backgrounds/**

https://wordpress.org/plugins/search/gutenberg/
I came to page 7.

**Comment by karmatosed** [comment]
Thanks for this @paaljoachim looks like a great list. What I think would be sensible is to move this to the 'idea' project and close for now but that means it can act as a running list, to collect. Having this as an issue is probably not as useful as that because it isn't actionable. Thanks and feel free to update it when you find more.

**Comment by phpbits** [comment]
Thank you very much @paaljoachim for including my plugins specially Block Options :)

**Comment by bph** [comment]
@paaljoachim This is fantastic!  Would you be ok, if I take your list and publish it on Gutenberg Times? I wanted to do this for so long now, and this would give me a huge head start!

**Comment by leahkoerper** [comment]
It's awesome to see so many folks playing with and building on Gutenbergh! My team at Modern Tribe has https://github.com/moderntribe/events-gutenberg, which is the alpha-version precursor to full compatibility between The Events Calendar and Gutenberg. It's a stand alone plugin for now, and we're working on expanding and polishing it before 5.0 comes out so it can be part of our core plugin.
