### ISSUE TITLE
BAPI for inspector / advanced settings

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#672]
I think it could maybe be an optional `inspector()` function in `registerBlock` that leverages Fill behind the scenes. I think we should not be prescriptive about what you can render in the sidebar, but provide basic form components eventually.

Examples for this use case:
- Advanced embed settings (youtube settings, tweet settings, etc).
- Query-like controls for blocks like "latest-posts".

**Comment by mtias** [comment]
Somewhat related to #609.

**Comment by jasmussen** [comment]
Here are mockups of how the inspector could work. 

When no block is selected, you see the normal sidebar:

![image](https://cloud.githubusercontent.com/assets/1204802/25744495/8596c3ca-319a-11e7-908e-56294e247fe2.png)

As soon as you select a block, the sidebar shows the inspector:

![image inspector](https://cloud.githubusercontent.com/assets/1204802/25744521/a60bcccc-319a-11e7-8b2d-8b53b31f070e.png)

You can click the breadcrumb trail in the sidebar to get back to your Post Settings. This also deselects any selected blocks.

**Comment by jasmussen** [comment]
Also possibly related, #352

**Comment by jasmussen** [comment]
See also #952
