### ISSUE TITLE
Hiding all metaboxes prevents `POST` request to `post.php` to save meta fields

### ISSUE THREAD

**Issue by enricobattocchi** [WordPress/gutenberg#67207]
### Description

Since WordPress 6.7, when all the metaboxes are hidden in the preferences, the  `POST` request to `post.php` to save meta fields is not fired anymore as it used to (e.g. in 6.6.2).
This creates problems with plugins, e.g. Yoast SEO, that use a sidebar to allow users to change some post metadata.
In general, this is a different behaviour from what used to happen so any mechanism relying on that request being fired could be affected.

### Step-by-step reproduction instructions

1. Have WordPress 6.7.* on your site
2. Install and activate only one plugin adding metaboxes, e.g. Yoast SEO
3. In the block editor, _Preferences_ > _General_ > _Advanced_, disable "Yoast SEO" and close
4. important: reload the page or edit another post - the metabox needs to be hidden from the beginning
5. open the Yoast SEO sidebar and change a setting, e.g. the focus keyphrase
6. save the post
7. no `POST` request is fired to `post.php`, so the changed value is not saved

Up until  6.6.2, a `POST` request was fired to `post.php` even with hidden metaboxes, so the new value was saved.

Important to notice: the value change in the hidden field works as expected, only the `POST` request is not fired anymore.

Notable finding:
if the user visits _Preferences_ > _General_ > _Advanced_, enables the metabox and then disables it again, then **doesn't reload the page**, the changed value will be saved instead. The problem happens only if all metaboxes are hidden since the editor page has been loaded and the relevant settings have not been touched.

### Screenshots, screen recording, code snippet

https://www.loom.com/share/bdf879f26d67454caca89aa7b6c3de0b (created by a Yoast support engineer for [this issue](https://github.com/Yoast/wordpress-seo/issues/21851))

### Environment info

- WordPress 6.7, 6.7.1
- Firefox 132 on Devuan Linux "Daedalus"
- Local by Flywheel instance with PHP 8.2.10

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by afercia** [comment]
I think the culprit is here:

https://github.com/WordPress/gutenberg/blob/b58cce696977b0f8850a39bfaf895a426a59c619/packages/edit-post/src/components/layout/index.js#L229-L245

Previously, the 'normal' and 'advanced' metaboxes areas were still rendered and hidden with CSS.
After https://github.com/WordPress/gutenberg/pull/64351 these etaboxes areas aren;t rendered at all. As such, there's no POST request.

**Comment by Mamaduka** [comment]
cc @stokesman

**Comment by afercia** [comment]
Reading [the dev note](https://make.wordpress.org/core/2024/10/18/post-editor-iframing-with-meta-boxes-in-wordpress-6-7/) about the split view for metaboxes, there's no mention that the rendering of the HTML has changed. As in:

When panels visibility is disabled in the Preferences:
- Previously: the metaboxes HTML was rendered and hidden with CSS.
- After: the metaboxes HTML is not rendered.

This impacts, for example, any plugin that uses hidden input fields in their metaboxes to save meta and thus trigger the POST request.

It sounds like a breaking change that was overlooked and not documented.

**Comment by afercia** [comment]
Of course, avoiding to render the HTML and run extra code is a performance benefit. However, I'm not sure this behavior can be changed without _deprecating_ saving meta via hidden input fields in the metaboxes area and allowing a grace period for plugins to adapt.

**Comment by t-hamano** [comment]
I was not able to reproduce this issue. Is there a step I'm missing?

- WordPress 6.7.1
- Only the Yoast SEO plugin enabled
- All meta boxes disabled

https://github.com/user-attachments/assets/59375125-1a7b-46e4-a86d-7ef425ad8cf4

**Comment by afercia** [comment]
@t-hamano thanks for testing. I'm not sure why you can't reproduce on your environment.
I just tested again on a clean WP 6.71 install and I can reproduce it. Animated GIF:

![Image](https://github.com/user-attachments/assets/e6a6173b-5800-4b91-8ddd-76e19b21d488)

**Comment by t-hamano** [comment]
Ah, after a few tests, I was able to reproduce this issue stably. It may have been due to my environment.
