### ISSUE TITLE
Incorrect publishing UX for Contributor without publishing capability

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#6725]
When a contributor is working on a new post with status `draft`, they see a "Publish..." button:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/36432/39951689-0a4e75d4-5541-11e8-83dc-65814ec9c88e.png">

The contributor _should_ see a "Submit for Review" button (which they do see once they've "Published"):

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/36432/39951712-4f4fdc18-5541-11e8-803a-331e72a94a41.png">

However, the contributor then sees explanatory text that's incorrect:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/36432/39951726-8d98c8f4-5541-11e8-9b95-dff6275401bc.png">

And two options that aren't available to them:

<img width="281" alt="image" src="https://user-images.githubusercontent.com/36432/39951729-9975a2f0-5541-11e8-8c6b-f18466611a06.png">

We should:

* [ ] Ensure the contributor only ever sees a "Submit for Review" button.
* [ ] Update the "Are you ready to publish?" copy to reflect the submitting for review workflow.
* [ ] Remove the invalid visibility and scheduling UI.

Related #6724

**Comment by nfmohit** [comment]
I believe the "Publish..." button mentioned here is just acting as a toggle button which doesn't actually "publish/save" anything but just opens the editor post publish panel where the actual "Submit for Review" button is displayed which converts the post status to "Pending".

It is completely understandable that the "Publish..." label which is displayed at the first place as the toggle button isn't ideal for sure. But would it be wise to change it to "Submit for Review" label as that'd make the contributor see two different "Submit for Review" buttons, one as the toggle button and the other as the actual submission button. Should there be a different label other than "Submit for Review" for the toggle button?

Thanks!

**Comment by nfmohit** [comment]
Okay, I just re-tested to refresh my memory and it seems it acts the same for administrators as well during publishing, i.e. first the "Publish..." button as the toggle button and then another "Publish" button for the actual submission/publishing. So, please disregard the previous comment. Working on the PR.

**Comment by danielbachhuber** [comment]
Landed in #6729

**Comment by gary-woods** [comment]
It makes no sense that [PluginPrePublishPanel](https://developer.wordpress.org/block-editor/developers/slotfills/plugin-pre-publish-panel/) is not displayed to `contributor` users when they are the ones who need publishing suggestions the most!

Please see [#16198](https://github.com/WordPress/gutenberg/issues/16198)

Looks like the panels were removed when the visibility panel was accidentally displayed to contributor users (as highlighted above). 

I definitely suggest enabling **PluginPrePublishPanel** for contributor users as well as the purpose of it is to provide guidance and they essentially need it the most. Alternatively, something like PluginPre**Review**Panel could work.
