### ISSUE TITLE
Change the font for supporting other languages (like Greek)

### ISSUE THREAD

**Issue by meymigrou** [WordPress/gutenberg#6726]
Writing in Greek is very frustrating because the English letters and Greek letters are different. Here's a quick example of what I mean:

![gutenberg](https://user-images.githubusercontent.com/30810726/39963721-548e1b86-567c-11e8-9690-4ec8090b91a1.png)

Are you going to fix that problem? I would like to see a clean font.

**Comment by ocean90** [comment]
Related: #6099

**Comment by danielbachhuber** [comment]
Thanks for the report, @meymigrou.

> Are you going to fix that problem? I would like to see a clean font.

It seems like this is the proposed solution:

> As such I would think the ideal solution is to load Noto for locales where we know the base offering works well, and fall back to other alternatives in cases like Hebrew. In other words, Noto for most languages, serif system font as fallback for other languages.

Closing in favor of #6099 to track to conclusion.

**Comment by meymigrou** [comment]
@danielbachhuber and how am I going to load Noto font to work with Greek? Is this going to be fixed in the next versions of Gutenberg?

**Comment by danielbachhuber** [comment]
@meymigrou Yes, the problem will be fixed in a future Gutenberg version (albeit not necessarily the next one).
