### ISSUE TITLE
Spellcheck does not run on pasted content

### ISSUE THREAD

**Issue by davidwolfpaw** [WordPress/gutenberg#6727]
If you compose content in a separate editor and paste it into a Gutenberg post, spellcheck doesn't activate for that content. In order to have spellcheck information display for content you need to click through each individual block that you want to see spellcheck on. 

It would be useful for spell check to activate when blocks are pasted in as well as directly edited.

**Comment by danielbachhuber** [comment]
> It would be useful for spell check to activate when blocks are pasted in as well as directly edited.

I agree — this seems like expected behavior to me, as it's how other editors behave.

**Comment by mkaz** [comment]
@iseulde You are right, spellcheck is triggered on focus.

Investigating a potential solution is to run the focus over each of the new blocks on paste. I did a quick check in console using: 
```
jQuery(".wp-block-paragraph").each( (i, el)  => el.focus() )
```

The focus goes too quickly through each of the paragraphs the spellcheck is not triggered for the middle paragraphs. The last paragraph does highlight the misspelled words. If I go through and select via console on each and pause a second, they all get picked up. 

This doesn't seem like it would be a great solution, especially for longer pasted text.

**Comment by paaljoachim** [comment]
I tested this with writing some text in another program. Making spelling errors and copied the text into Gutenberg. I notice that the spelling errors shows up as errors in Gutenberg.

![Screen Shot 2021-01-22 at 14 49 27](https://user-images.githubusercontent.com/5323259/105498931-11158a80-5cc1-11eb-9572-9a75a4ec731c.png)

I will close this issue. If I am mistaken then please reopen.

**Comment by rfischmann** [comment]
I've been a Firefox user for a few years and its spell checker works just fine in Gutenberg. However, I've been testing Microsoft Edge today and I've noticed the behavior mentioned here; whenever I open a post to proofread it, Edge's spell checker only works when I click once on each block/paragraph. It shouldn't be this way…
