### ISSUE TITLE
Impossible to delete an empty paragraph

### ISSUE THREAD

**Issue by sebastienserre** [WordPress/gutenberg#6728]
**Describe the bug**
When you're writing a post, pressing enter make a new paragraph. If you leave it empty, you cant delete it.... you have to put some characters in it to be able to delete. 

**Expected behavior**
The dust bin icon should be available here.

**Screenshots**

! [dust bin not present] (https://www.dropbox.com/s/557yur5ip7xdqqh/dust-bin-not-present.jpg)
! [dustin bin present] (https://www.dropbox.com/s/u9zmk7ptc74j47d/dust-bin-present.jpg)

**Comment by ocean90** [comment]
This will be fixed in the next version, see #6579.
