### ISSUE TITLE
Resizable items below the "Drag to resize" handle are not resizing properly in Firefox

### ISSUE THREAD

**Issue by remcokalf** [WordPress/gutenberg#67316]
### Description

Resizable items below "Drag to resize" handle are not resizing properly. Dragging their handle results in stuttering/glitching. This happens for example with an ACF text area field.
The issue happens in Firefox only it seems. I don't see it in Chrome.

This issue happens will every resizable item. Not only textareas, also items that have e.g. `resize: vertical` set in CSS.
Resizable items outside of this area are resizing just fine, like the post title textarea in code view.

See below screenshot of and example with an ACF text area field.

Not entirely sure if this is a Gutenberg issue, or if I should add it in trac.

### Step-by-step reproduction instructions

- Install ACF or another custom field plugin, eg. Custom Field Suite
- Add a resizable field, e.g. a textarea field
- Open a post/page edit screen in Firefox
- Try to resize the field

### Screenshots, screen recording, code snippet

In Firefox:
![Image](https://github.com/user-attachments/assets/d1659bb0-d954-4f78-9f07-197b0318a302)

### Environment info

- Happens in Firefox only
- Happens in WP 6.7 and 6.7.1
- Does not happen in 6.6.1 (only other version I could test on).

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by hanneslsm** [comment]
Can confirm.
Tested on MacOS and Firefox 132.0.2 (aarch64)
![Image](https://github.com/user-attachments/assets/44ec09c9-1b9d-4ec6-bd48-a4012d6b55eb)

**Comment by remcokalf** [comment]
Maybe this should be a separate bug report, but this is probably related or part of the same issue: the "Drag to resize" handle itself also does not work properly. Not only in Firefox, but also in Chrome.

**Comment by ellatrix** [comment]
cc @stokesman

**Comment by stokesman** [comment]
@remcokalf Thanks for reporting this! #68252 fixes it in my testing.

> Maybe this should be a separate bug report, but this is probably related or part of the same issue: the "Drag to resize" handle itself also does not work properly. Not only in Firefox, but also in Chrome.

Yes it probably should be. I’d be surprised if it weren’t already reported because if it’s not working in Chrome it would surely be noticed by now. If you can add any detail about what isn’t working properly I’d appreciate it.

**Comment by remcokalf** [comment]
@stokesman Thanks for fixing this, tested and works!
I don't see the drag handle issue anymore, maybe it was fixed in the meantime, not sure.
