### ISSUE TITLE
Importing core data store on front-end brings in the entire `@wordpress/block-editor` module

### ISSUE THREAD

**Issue by samueljseay** [WordPress/gutenberg#67334]
Recently on WooCommerce we decided to explore using entities to share some data between blocks. The data is some editable block headings we want to share between blocks.

To access this data in front-end we use the core data store, specifically we use `getEditedEntityRecord`. The issue with doing this, is that `@wordpress/core-data` depends on `@wordpress/block-editor` so when we do this basic query of some entity records front-end we're forced to load the entirety of the block editor. 

It seems this dependency is only for [unlocking a private API](https://github.com/WordPress/gutenberg/blob/eadf2dda88e69176c9d577ed7cd197a3da9197a2/packages/core-data/src/footnotes/get-rich-text-values-cached.js#L4). The only other usage is in a test file.

I'm not sure what a good fix to this would be, but it would be hugely helpful if we could avoid depending on `@wordpress/block-editor` for this package.

**Comment by Mamaduka** [comment]
Thanks for reporting the issue, @samueljseay!

There's already a similar report. I will close this as a duplicate. Feel free to add your comment on #64604.
