### ISSUE TITLE
More Menu shows overly verbose shortcut

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#6734]
**Describe the bug**
Shortcut menu shows too long shortcut description.

![screen shot 2018-05-14 at 11 22 30](https://user-images.githubusercontent.com/1204802/39989078-521c3d22-5769-11e8-9817-44f9d77bfbba.png)

**Expected behavior**

Something like this:

![screen shot 2018-05-14 at 11 28 20](https://user-images.githubusercontent.com/1204802/39989324-ebd6b9ce-5769-11e8-8ee5-6bbcc4ad9daa.png)

**Desktop (please complete the following information):**

MacOS and Chrome

@tofumatt  @iseulde I think maybe you were looking at this recently?

**Comment by tofumatt** [comment]
The issue with showing just the shortcuts is that they aren’t clear to many users; @iseulde pointed out that the new Mac keyboard doesn’t even show those icons. I think we could remove the icons and fit the content but that would be the clearer fix I think.

- Matt (Sent from mobile)

**Comment by jasmussen** [comment]
That's a good point.

Let's do what Google Docs does here, and go halfway. That is, Shift and Option we spell out (capitalized), but we use the ⌘ for Command on Mac. Can a Windows user sign into Docs and see what they use for Control on Windows? Is it "Ctrl"?

Screenshots:

![screen shot 2018-05-14 at 12 39 27](https://user-images.githubusercontent.com/1204802/39992740-0d22dbbc-5774-11e8-9f16-9340187b6e2c.png)

![screen shot 2018-05-14 at 12 39 35](https://user-images.githubusercontent.com/1204802/39992747-0ebebb8a-5774-11e8-8c96-353f2d8b78c0.png)

![screen shot 2018-05-14 at 12 39 41](https://user-images.githubusercontent.com/1204802/39992750-105f7c90-5774-11e8-985f-b05149f5aa66.png)

Would also be nicer to see if we can make the width of the menu wider if necessary to accommodate the shortcut on the right.

**Comment by theleemon** [comment]
On Windows Google Docs uses "Control"

![docs](https://user-images.githubusercontent.com/2060659/39994989-4485aa60-577b-11e8-9ccd-5db9d67e0edc.jpg)

**Comment by tofumatt** [comment]
We do use just the clover symbol for command on Mac (check out shortcuts like Command+B) for bold.

**Comment by iseulde** [comment]
Just looked into CMD/CTRL+ESC... Not so simple to make it work with Mousetrap and TinyMCE. We'll have to do this on our own and see if the esc key was pressed or not.
