### ISSUE TITLE
Unnecessary line breaks within image captions due to display: inline-block; on `.wp-block-image a`

### ISSUE THREAD

**Issue by frkly** [WordPress/gutenberg#67366]
### Description

Ideally, the text in captions, including hyperlinks, should flow continuously without any forced line breaks. However, currently, the presence of a hyperlink leads to text breaking before or after it if there isn't sufficient width to accommodate it without wrapping. In my estimation, this issue stems from a lack of consideration for hyperlinks within figcaptions when addressing [Issue #62556](https://github.com/WordPress/gutenberg/pull/62556), which focused on fixing the focus ring around images when they are linked.

### Step-by-step reproduction instructions

1. Activate the Twenty Twenty-Four theme.
2. Open Gutenberg Editor.
3. Add an Image block to your post.
4. Type a caption for the image that includes a moderately long anchor text link. Here is the example text I used for the caption:

> This charming tabby cat, spotted [enjoying a peaceful afternoon nap](#) on the sunlit hood of my car, [perfectly demonstrates the art of relaxation](#) and mindfulness. Cats are renowned for [their ability to find comfort](#) almost anywhere. It is said that in ancient days, [cats were believed to bring peace to any place they chose to rest](#), magically transforming even [the most chaotic homes into havens of calm](#). (Photo by Burak Argun on [Pexels.com](https://www.pexels.com/photo/29554445/))

5. Save and publish your post.
6. Open the published post in a browser.
7. Open the browser's DevTools. Set the viewport to iPhone SE to simulate a smaller screen size. Locate the CSS for `.wp-block-image a`. Toggle the `display: inline-block;` on and off to observe the differences in how the caption text is displayed.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/ca62f567-77f9-4234-b7fd-cbd81be57ff3

### Environment info

- WordPress 6.7.1, Gutenberg 19.7.0
- Google Chrome 131.0.6778.86（Official Build）
- Desktop with Windows 11

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Infinite-Null** [comment]
Hi @frkly ,
Thank you for highlighting this issue. I was able to successfully reproduce it and agree that it is important to include hyperlinks that flow seamlessly without any forced line breaks. Example:

<img src="https://github.com/user-attachments/assets/a319278e-97a4-4d86-80e9-10df99ddd885" width="350" alt="Image description">

### Supplemental Artifacts
https://github.com/user-attachments/assets/0716eb37-a8df-4e7c-8c04-89ecb60b90e8

### Environment
- WordPress: 6.8-alpha-59366
- Browser: Chrome 131.0.0.0
- OS: macOS
- Theme: Twenty Twenty-Five 1.0

**Comment by hanneslsm** [comment]
Can't test right now. Does it affect the caption in galleries?
