### ISSUE TITLE
Block editor: unwanted scroll bar while loading.

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#67360]
### Description

On load time the block editor displays an unwanted scroll bar. Please take a look at the screenshot below.

I'm tagging this issue with zoom-out tag because this seems to be the result of the changes introduced in https://github.com/WordPress/gutenberg/pull/67126

Specifically this line:
https://github.com/WordPress/gutenberg/blob/857ca64ae813ae75e5f3a3c5a7d4f930d7bd47d9/packages/block-editor/src/components/iframe/content.scss#L22-L24

### Step-by-step reproduction instructions

1. Use Gutenberg trunk and TT5 theme.
2. Browse theme style variations in the sidebar.
3. Observe the unwanted scroll bars while the block editors are loading

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/f9170178-e3ad-4afd-9e52-f96fac5275af)

### Environment info

- WordPress 6.7.1
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by t-hamano** [comment]
I'm wondering why the theme style preview or palette preview even needs zoom-out related CSS class names or variables 🤔

![Image](https://github.com/user-attachments/assets/5624f74f-357f-4f5b-8e10-f94c9e9cdb22)

cc @jeryj @draganescu @ajlende

**Comment by jeryj** [comment]
~~I think this should be fixed by https://github.com/WordPress/gutenberg/pull/67495 and https://github.com/WordPress/gutenberg/pull/67496~~

Ah, never mind. I think this is due to the animation assuming the resulting canvas will have a scrollbar. If the height of the content is less than the frame, we won't want to force a scrollbar.
