### ISSUE TITLE
Horizontal scrolling occurs when set the borders individually on a Windows Chrome, Firefox environment.

### ISSUE THREAD

**Issue by shimotmk** [WordPress/gutenberg#67362]
### Description

Horizontal scrolling occurs when set the borders individually on a Windows Chrome, Firefox environment.

### Step-by-step reproduction instructions

1. Go to page
2. Set borders individually in Windows Chrome, Firefox environment
3. See that a horizontal scroll bar has appeared.

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/ce60e247-430e-458d-af77-9038a3194a33)

### Environment info

- WordPress Version 6.7.1
- Twenty Twenty-Five
- Windows
- Chrome
- Firefox

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Mayank-Tripathi32** [comment]
Hi @shimotmk,

Thank you for reporting the issue. I was able to successfully reproduce the bug on a Windows machine. It seems to be caused by the scrollbar size, which gets added on Windows. I will work on a possible solution to address this.

Thanks

**Comment by Mayank-Tripathi32** [comment]
Point to note: This issue also occurred in version 6.6.2 and is not a newly introduced bug.

**Comment by Mayank-Tripathi32** [comment]
@shimotmk Do you think adjusting the styles for the sidebar would be a viable solution for this issue on Windows? Making it behave more like the Mac version might resolve the problem.

cc: @t-hamano Could you share your thoughts on this?

**Comment by t-hamano** [comment]
Thanks for the report.

This issue is the same as #65207. I have also submitted a PR to resolve this issue: https://github.com/WordPress/gutenberg/pull/67049

**Comment by shimotmk** [comment]
I'm sorry for creating duplicate issues 🙇
