### ISSUE TITLE
“withInstanceId” component uses incorrect capitalization of “ID”

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6742]
## The issue
<code><var>withInstanceId</var></code> uses incorrect capitalization of “ID”. It should be “withInstanceID”. A variable used by the component, <code><var>instanceId</var></code> also uses incorrect capitalization.

https://github.com/WordPress/gutenberg/tree/master/components/higher-order/with-instance-id

## Expected behavior
“ID” should be correctly capitalized in all functions, variables, etc. according to camelCase standards. Assuming I understand camelCase properly, “ID” and “UID” should always be entirely capitalized unless it is the first word in a name, in which case it should be entirely lowercase.

## Related Issues and/or PRs
#6685
#6741

**Comment by gziolo** [comment]
Let's track all occurrences in one issue. Closing this one in favor of #6741.
