### ISSUE TITLE
`const { RichText } = wp.editor;` does not works

### ISSUE THREAD

**Issue by hideokamoto** [WordPress/gutenberg#6745]
**Describe the bug**
`RichText` should be called from `wp.blocks`, but the docs example calls from `wp.editor`.

**To Reproduce**
1. Go to https://wordpress.org/gutenberg/handbook/blocks/introducing-attributes-and-editable-fields/#attributes
2. Copy example code `ESNext`
3. Run `webpack` to build the example code.
4. Go to new post page
5. See error in console like `Uncaught TypeError: Cannot read property 'RichText' of undefined`

**my example component**

```
const { __ } = wp.i18n;
const { registerBlockType } = wp.blocks;
const { RichText } = wp.editor;

registerBlockType( 'guten-blocks/first-block', {
	title: __( 'Hello custom' ),
	category: 'formatting',
	attributes: {
		content: {
			type: 'array',
			source: 'children',
			selector: 'p'
		}
	},
	supports: {
		// Removes support for an HTML mode.
		html: false,
	},
	edit({attributes, setAttributes}) {
		const { content } = attributes
		const onChangeContent = (newContent) => setAttributes({content: newContent})
		return (
			<RichText
				tagName="p"
				onChange={ onChangeContent }
				value={ content }
			/>
		);
	},
	save() {
		return <p>{__( 'Hello from the saved content!' )}</p>;
	},
} );
```

**Expected behavior**
use `const { RichText } = wp.blocks`, it works well.

```
const { __ } = wp.i18n;
const { registerBlockType, RichText } = wp.blocks;

registerBlockType( 'guten-blocks/first-block', {
	title: __( 'Hello custom' ),
	category: 'formatting',
	attributes: {
		content: {
			type: 'array',
			source: 'children',
			selector: 'p'
		}
	},
	supports: {
		// Removes support for an HTML mode.
		html: false,
	},
	edit({attributes, setAttributes}) {
		const { content } = attributes
		const onChangeContent = (newContent) => setAttributes({content: newContent})
		return (
			<RichText
				tagName="p"
				onChange={ onChangeContent }
				value={ content }
			/>
		);
	},
	save() {
		return <p>{__( 'Hello from the saved content!' )}</p>;
	},
} );
```

**Screenshots**
![2018-05-15 0 15 08](https://user-images.githubusercontent.com/6883571/40006342-12cebac0-57d5-11e8-90e5-dd932d47d735.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: chrome
 - Version:latest

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by aduth** [comment]
The documentation is currently generated from master, where `RichText` has been moved from `blocks` to `editor`. There's a proposal to change documentation generation to only run from current release version: #6514

(Closed in favor of #6514)

**Comment by fvonellerts** [comment]
In case someone still steps over this issue, make sure to include 'wp-editor' in your PHP wp_enqueue_script dependencies.

**Comment by piersb** [comment]
Thanks @fvonellerts - I've been searching for an answer to this for some time, and this has solved my problem!
