### ISSUE TITLE
Global Syles Preview: vertical scroll bar appears when loading style previews

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#67462]
### Description

In the Global Styles, a vertical scrollbar appears when the style preview is loaded.

### Step-by-step reproduction instructions

This issue should be easily reproduced on Windows OS. On Mac OS, make scrollbars always visible. 

- Access the site editor.
- Open the global styles.
- Check the style preview.
- Access the Browse styles link.
- Check the style preview.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/36271b6a-f401-4d29-b836-43b4fe9e21d0

The screenshot below shows the moment when the scrollbars are visible:

![Image](https://github.com/user-attachments/assets/6a53fd7a-188d-49c3-bf68-a6a05defd5c8)
![Image](https://github.com/user-attachments/assets/736f540e-deb7-4fd5-8a9d-7f1c083b3721)

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Infinite-Null** [comment]
Hello @t-hamano,
Could you please take a look at issue #67360? It seems that this issue might be related to that one.
Thank you!

**Comment by t-hamano** [comment]
@Infinite-Null Thanks for letting me know! I'll close this issue.
