### ISSUE TITLE
RichText issues

### ISSUE THREAD

**Issue by ross-ritchey** [WordPress/gutenberg#6747]
This is the same issue as #6740 (opening new issue so I don't hijack his thread)

In my case it is a bit worse because I have a repeatable block that allows for many editable sections:
![image](https://user-images.githubusercontent.com/2796748/40009189-5428fc76-576f-11e8-8378-a33527e0bf97.png)

Notice that I have a number field without limits in the InspectorControls. Each slide you add creates 2 RichText areas and a MediaControl. I improved things a bit by only allowing one of those RichText areas to have formattingcontrols - but when you get past 2-3 slides it gets a bit unwieldy.

I am in 2.8 release.

Here is my Edit function (using ES5 currently because I haven't figured out a way to get gutenblocks to work with ESNext. Its on the list):

	edit: function( props ) {
		var slidecount = props.attributes.slidecount,
			slides = props.attributes.slides,
			focusedEditable = props.focus ? props.focus.editable || 'blocktitle' : null;

		// console.log(slides);

		function onImageSelect( media ) {
			return props.setAttributes( {
				blockimageurl: media.url,
				blockimageid: media.id,
			} );
		}

		function renderEditSlides() {
			let ret = [];

			let slideCount = props.attributes.slidecount;
			let slides = props.attributes.slides;

			for (var i = 0 ; i < slideCount; i++) {
				(function(j) {
					let slide = slides[j];

					ret.push(
						el('div', { className: 'slide-container' },
							el( 'div', { className: 'slide-content-container' },
								el(
									RichText, {
										tagName: 'h2',
										className: 'slide-title',
										inline: true,
										formattingControls: [],
										placeholder: 'Write slide title...',
										value: slide.title,
										focus: focusedEditable === 'slide-title' ? focus : null,
										onChange: function(value) {
											let newslides = props.attributes.slides;
											newslides[j].title = value;

											return props.setAttributes({ slides: newslides });
										},
									}
								),
								el(
									RichText, {
										tagName: 'div',
										className: 'slide-content',
										inline: true,
										placeholder: "Write slide content...",
										value: slide.content,
										focus: focusedEditable === "slide-content" ? focus : null,
										onChange: function(value) {
											let newslides = props.attributes.slides;
											newslides[j].content = value;

											return props.setAttributes( { slides: newslides } );
										},
									}
								),
							),
							el('div', { className: 'slide-image-container' },
								el(
									MediaUpload, {
										type: 'image',
										multiple: false,
										value: slide.imageid,
										onSelect: function(media) {
											let newslides = props.attributes.slides;
											newslides[j].imageid = media.id;
											newslides[j].imageurl = media.url;
											
											return props.setAttributes( { slides: newslides } );
										},
										render: function (obj) {
											return el(components.Button, {
												className: slide.imageid ? 'image-button' : 'button button-large',
												onClick: obj.open
											},
												!slide.imageid ? 'Upload Image' : el( 'img', { src: slide.imageurl, dataid: slide.imageid } )
											);
										}
									}),
							),
						)
					);
				})(i);
			}

			return ret;
		}

		return [
			el( InspectorControls, { key: 'inspector' },
				el( 'div', { className: 'wse-cta-block-options' },
					el( 'h2', {}, 'World Synergy Slideshow Options' ),
					el( 'p', {}, '' ),
					el( 'p', {}, 'Number of Slides' ),
					el( 'input', { type: 'number', value: slidecount, onChange: function(event) {
						let newcount = event.target.value;
						
						let newslides = props.attributes.slides;
						if (newslides.length < newcount) {
							newslides.push({
								title: ["Title"],
								content: ["Content"],
								imageid: "",
								imageurl: "",
							});

							props.setAttributes( { slides: newslides } );
						}						

						return props.setAttributes( { slidecount: newcount } );
					} } ),
				),
			),
			el( 'div', { className: 'slideshow-container' }, 
				renderEditSlides(),
			),
		];
	},

**Comment by gziolo** [comment]
> In my case it is a bit worse because I have a repeatable block that allows for many editable sections

This issue was solved in `master` branch. 2.9 should be released later this week and you shouldn't have this issue anymore. Displaying formatting toolbar is now automatically handled by `RichText` with changes introduced in #6419. When you omit `isSelected` and `onFocus` props, as you did, it should work perfectly fine. 

By the way, `focus` property is no longer supported for `RichText` field.
