### ISSUE TITLE
Update components CONTROL_HEIGHT config value to 40 pixels

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#67484]
### Description

Discovered while investigating https://github.com/WordPress/gutenberg/issues/67425 

To my understanding, some components that use CSS-in-JS rely on some CSS values stored in `packages/components/src/utils/config-values.js`.
It appears the height value in this config is still 36 pixels, while the new default size should be 40 pixels.

https://github.com/WordPress/gutenberg/blob/15d63ce9a27adf8b7f70abf95308493237afdde0/packages/components/src/utils/config-values.js#L7

Notice also all the `controlHeight*` variants are based on 36 pixels.

One of the places where the old 36 pixels value is used is for the `ItemGroup` > `Item` component, which can be optionally rendered as a button by the means of the prop `as`. When rendered as a button or as a link, it uses this [unstyledButton](https://github.com/WordPress/gutenberg/blob/15d63ce9a27adf8b7f70abf95308493237afdde0/packages/components/src/item-group/styles.ts#L11) style where there's no height value set. Still, [all the padding values](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/item-group/styles.ts/#L104-L106) are based on the 36 pixels value.

I guess all these calculations should use the new 40 pixels height, not sure whether the best option would be allowing to pass the `__next40pxDefaultSize` flag to the styles calculations or switching directly to new hard-coded values.

Cc @WordPress/gutenberg-components @t-hamano 

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by tyxla** [comment]
I think @mirka planned to address this as part of #46741, which is in progress, so I'd personally close this issue in favor of #46741.

**Comment by afercia** [comment]
Oh thanks for pointing me at the existing issue. I see it;s from Dec 22, 2022 and still no movement 🙁  No objections to close this one, in that case I will report my findings on https://github.com/WordPress/gutenberg/issues/46741

**Comment by tyxla** [comment]
> Oh thanks for pointing me at the existing issue. I see it;s from Dec 22, 2022 and still no movement 🙁 No objections to close this one, in that case I will report my findings on [#46741](https://github.com/WordPress/gutenberg/issues/46741)

Right, I agree it took a while, but for what it's worth, @mirka is working on one of the last pieces (https://github.com/WordPress/gutenberg/issues/65751) and it's almost there.

Feel free to leave this issue open, but IMHO it's unnecessary because in https://github.com/WordPress/gutenberg/issues/46741 we have a tracking item specifically for what you reported:

> Clean up usage of $button-size SCSS variable and CONFIG.controlHeight CSS-in-JS variable

**Comment by afercia** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/46741
