### ISSUE TITLE
Navigation block: Added a hook to add allowFormat

### ISSUE THREAD

**Issue by shimotmk** [WordPress/gutenberg#67559]
## What problem does this address?

Hello👋

I would like a hook for the navigation block allowedFormats.

Adding a hook here makes it easier to customize from plugins.

For example, adding inline icon markup.

In the classic theme, you could add HTML tags to the menu label.

(Although this may not have been very good security practice.)

`<span class="dashicons dashicons-admin-home"></span>WordPress`

### This is how it looks in Twenty Twenty-One

![Image](https://github.com/user-attachments/assets/b91a7268-1efe-4c1e-885e-2e437342c69c)

![Image](https://github.com/user-attachments/assets/0492d435-372d-4948-8741-632c5aa48473)

### Twenty Twenty-Five example

In block themes, you can only add formats allowed by allowedFormats.

![Image](https://github.com/user-attachments/assets/9fcf675f-7d3a-4f74-b4b3-0ab217170340)

Adding a hook to allowedFormats will allow customization from plugins, allowing for a variety of design expressions.

Thank you for your consideration.

## What is your proposed solution?

Add a hook to add `allowedFormats`.

https://github.com/WordPress/gutenberg/blob/968131a2f6c5256e237d513ff919ba47944a6d9a/packages/block-library/src/navigation-link/edit.js#L529-L534

https://github.com/WordPress/gutenberg/blob/82d7ad7b27d891e9e31c4a1dfd9802e882edc0d3/packages/block-library/src/navigation-submenu/edit.js#L576-L581

label

[Block] Navigation

[Block] Navigation Link

**Comment by Mamaduka** [comment]
I think I've got a solution that doesn't require a filter. I'll push a PR later today.

**Comment by Mamaduka** [comment]
Here's the PR - #67585.
