### ISSUE TITLE
Terms List block disappears when Show empty terms is turned on

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#67556]
### Description

The **Terms List** block breaks when the `Show empty terms` switch is turned on. In the _Visual Editor_, the block just simply disappears.

When you switch from the _Visual Editor_ to the _Code Editor_, the block still appears to be in the content, but when in the _Visual Editor_ nothing shows and you're unable to select it. The only way to recover is to switch to the _Code Editor_ and manually delete the block and reinsert it.

Screencast
https://share.zight.com/YEu6NBP7

### Step-by-step reproduction instructions

- Insert Terms List block
- In the Settings Sidebar, turn on the `Show empty terms` switch
- Watch block disappear

### Environment info

WP 6.7.1
Firefox 133.0
macOS Sonoma 14.6.1
Theme: Twenty Twenty One
No plugins activated
Core Block Editor (i.e. Gutenberg plugin not activated)

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [x] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Mamaduka** [comment]
Thanks for the report, @maddisondesigns!

Do you see any errors in the DevTools Network or Console tab?

**Comment by maddisondesigns** [comment]
@Mamaduka sorry, I forgot to look at that. Yep, I see an error...

It's trying to get :
```
http://your-wordpress-site.com/wp-json/wp/v2/tags?context=view&per_page=100&hide_empty=&_locale=user&page=2
```

and gets the response:
```
{"code":"rest_invalid_param","message":"Invalid parameter(s): hide_empty","data":{"status":400,"params":{"hide_empty":"hide_empty is not of type boolean."},"details":{"hide_empty":{"code":"rest_invalid_type","message":"hide_empty is not of type boolean.","data":{"param":"hide_empty"}}}}}
```


***http://your-wordpress-site.com** is a local test site so you obviously wont be able to see it.

**Comment by Mamaduka** [comment]
The bug appears in the REST API response. The link returned for the next page query is malformed. I need to confirm if it's specific to the terms controller or affects other endpoints.

## Screenshot
![Image](https://github.com/user-attachments/assets/89bf46ef-364e-421d-a95c-a315b99f76ac)

**Comment by Mamaduka** [comment]
Found the ticket on track: https://core.trac.wordpress.org/ticket/59425.

I'll close this issue since it's not actionable on the Gutenberg side.
