### ISSUE TITLE
Words count in the multi-selection inspector doesn't work with bound content

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#67610]
### Description

When two or more blocks are selected, the block inspector shows the amount of selected blocks and the selected words count.

When one of more of the selected blocks content is bound to a source, the words count still counts the words in the original content (the block markup) while visually the rendered content comes from the bound source, which likely contains a different amount of words.

While i do understand why this occurs, from an user perspective this looks just broken and confusing. Here's a couple of example screenshots:

![Image](https://github.com/user-attachments/assets/ed462a9c-26c3-457e-b632-43575ae9ed77)

I wonder whether the words count adds great value in the first place. To my understanding it is only used when there is a multi-block selection. Is this information actually useful for users?

If the prevalent opinion is to keep the word count, then I would say that it should either work correctly for bound content or it should be disabled when a block has bound content.

Cc @WordPress/gutenberg-design @artemiomorales 

### Step-by-step reproduction instructions

- Have a bound source that provides a text string to be used for connected content attribute of a paragraph block. You can qui8cly add this to your theme's functions.php

```
add_action( 'init', 'test_block_bindings' );

function test_block_bindings() {
	register_meta(
		'post',
		'text_short',
		array(
			'show_in_rest'      => true,
			'single'            => true,
			'type'              => 'string',
			'sanitize_callback' => 'wp_strip_all_tags',
			'default'           => 'Text from the bound source',
		)
	);
}
```

- Create a post with two paragraphs and add only one word to each paragraph.
- Select the first Paragraph, and bount its content to the registered source from the block settings panel > Attributes.
- Select both paragraphs.
- Observe the block inspector shows the word count.
- Observe the words count is `2 words`.
- Observe the visible selected words are more than two.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by jasmussen** [comment]
What is the question that folks in the design ping can help with?

**Comment by afercia** [comment]
The question is:

> I wonder whether the words count adds great value in the first place.

Why this feature in the first place? Why it has been designed only for the multi-selection inspector and what users need addresses?

**Comment by jasmussen** [comment]
That seems like a question that could use broader feedback than just a sub-group assumed to have designed that particular aspect of the editor. CC: @WordPress/gutenberg-core

**Comment by afercia** [comment]
Isn't that what the design team is supposed to be responsible for? Designing features.

**Comment by Mamaduka** [comment]
My two cents: Considering the number of changes it might require compared to the benefits of the feature, we might just remove it.

IIRC, this also doesn't count words from controlled blocks like sync patterns.

**Comment by t-hamano** [comment]
The prototype of this panel appears to have been added a very long time ago. See: https://github.com/WordPress/gutenberg/pull/12050

**Comment by ntsekouras** [comment]
I'll spin up a quick PR to remove it.
