### ISSUE TITLE
Make Write mode and Zoom out block options menus consistent

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#67658]
### Description 

The block options menus in write mode and zoom out mode differ in available actions today. To ensure consistency, the menu in write mode should be updated to match the zoom out menu, which includes options for “Copy,” “Duplicate,” and “Delete.”

### Steps to Reproduce:

1.	Open the editor in write mode.
2.	Click on the options menu for a top-level group block (i.e. pattern).
3.	Note the available menu options.
4.	Switch to zoom out mode.
5.	Click on the options menu for a top-level group block (i.e. pattern).
6.	Compare the menu options between write mode and zoom out mode.

### Expected:

The block options menus in both modes should be identical, with options for “copy,” “duplicate,” and “delete.”

### Visuals 

Write Mode: 

![Image](https://github.com/user-attachments/assets/bf5e6366-f564-49d6-8d57-789ed92e34d5)

Zoom out (correct one): 

![Image](https://github.com/user-attachments/assets/aa0de0bb-cb73-4324-b8ae-f20f572aac38)

**Comment by rinkalpagdar** [comment]
Hello @richtabor Can you please tell me what I am missing here?
https://github.com/user-attachments/assets/34cc3306-3f1f-42f2-8472-0622b2078117
Thanks!

**Comment by richtabor** [comment]
> Hello @richtabor Can you please tell me what I am missing here?

You need to turn on the Write mode experiment within Gutenberg > Experiments. 

![Image](https://github.com/user-attachments/assets/6f00f2af-b765-45e8-bfd6-d92e3407279d)
