### ISSUE TITLE
Default block appender does not appear if there is already a block in the editor and paragraph block is disabled

### ISSUE THREAD

**Issue by fttriquet** [WordPress/gutenberg#67653]
### Description

I've upgraded my wordpress from 6.5 to 6.7 version and the behavior of default block append changed in gutenberg.

![Image](https://github.com/user-attachments/assets/9ecc781a-3b8f-4752-8a4e-46959870b103)

![Image](https://github.com/user-attachments/assets/13ae3e7c-e006-4868-9388-5c978b1de2d5)

We have a specific setup, we remove all default blocks from gutenberg (including paragraph) and only use our custom blocks added through a plugin.
Before when paragraph was not available gutenberg would always display the block appender button at the end of the document, with or without blocks. But now it is only available when I have no blocks displayed.

Step-by-step reproduction instructions

Thanks

### Step-by-step reproduction instructions

- Open gutenberg
- Add a block with block appender

### Environment info

- Remove all default blocks from gutenberg, in our code we do this through a theme
```   
    add_action('enqueue_block_editor_assets', function () {
        wp_enqueue_script('block_editor_assets', get_template_directory_uri() . '/assets/app.js', array('wp-blocks', 'wp-dom-ready', 'wp-edit-post'));
    });
```
app.js
```
wp.domReady(function () {
  setTimeout(() => { //FIXME [poca] Voir le commit message
      blocks = getBlockTypes();
      blocks.filter(block => !block.name.startsWith('nl-blocks')).forEach(block => unregisterBlockType(block.name))
  }, 100)
});
```
- Have a custom blocks plugin with some blocks

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by talldan** [comment]
@fttriquet I'm not sure it's related to your changes to the registered blocks, the appender was removed as a design choice.

In the post editor you should be able to click at the end of the block list to insert a block or use the Insert Before / After actions. With your setup, you may need to configure one of your blocks to be the editor's default block to make those actions work:
```js
wp.blocks.setDefaultBlockName( 'my-custom-block' );
```

I'll close the issue as this isn't really a bug but an intentional change.

**Comment by bwaltz** [comment]
I am also experiencing this. I would love the Appender button to return. We only have custom blocks through ACF.
