### ISSUE TITLE
The shadows menu items miss a chevron icon

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#67696]
### Description

In the Global styles panel there are several menu items that provide access to su-pabels, in design jarcon the 'drill-down' menu sub-panels.

Moat of these menu items use a chevron icon to visually indicate the presence of a sub-level panel and to make interaction predictable.

The Shadows menu items don't.

For consistency and better user experience, I think all the menu items that navigate to a drill-down sub-level should use the chevron icon.

Cc @WordPress/gutenberg-design 

Screenshot with a few examples:

![Image](https://github.com/user-attachments/assets/687d8d60-0651-4fd7-9765-d2eb515ca8fd)

### Step-by-step reproduction instructions

- Go to the Site editor > Styles > Shadows
- Observe the shadows menu items don't use a chevron icon.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by richtabor** [comment]
Why are we rendering the font sizes alongside the labels? You can't interact with them from this view and they don't mean anything. Reading `1.75rem` has no frame of reference in relation to a font size. We don't show them for shadows, naturally. 

I propose that if we add chevrons, we remove the font size values.

**Comment by Mamaduka** [comment]
Should we also remove the icon prefix for the shadow names? It's the same icon and doesn't convey any meaning.

**Comment by afercia** [comment]
I'd agree with both points above: removing the font sizes and the icons for the shadows, although those are issues slighly outside the scope of this report which is specifically about the chevron icon.

Regarding the icon for the shadows:
I'm not sure I ever understood why the concept of shadow (dim light, penumbra, dark) is conveyed by the means of an icon that represents a shining sun. Anyone have any context about it?

**Comment by Mamaduka** [comment]
I think @yogeshbhutkar started working to resolve all points in #67720, so we can handle these in one go.

> I'm not sure I ever understood why the concept of shadow (dim light, penumbra, dark) is conveyed by the means of an icon that represents a shining sun. Anyone have any context about it?

I'm not sure. The same icon is usually used in OS to represent screen brightness, so it seems out of place here.

**Comment by jameskoster** [comment]
Related: https://github.com/WordPress/gutenberg/issues/64445
