### ISSUE TITLE
Select box display does not update when font size is reset

### ISSUE THREAD

**Issue by inc2734** [WordPress/gutenberg#67721]
### Description

If the font size is reset while the font size choice is in the select box, the value is reset, but the select box display is not updated.

### Step-by-step reproduction instructions

1. Add font size presets.
2. Go to block editor.
3. Add a paragraph to the document.
4. Open the Typography panel.
5. Change the font size.
6. Click “reset” to clear the font size.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/cabf7c4c-263c-4cf5-b552-c9edd2bca0dd

### Environment info

- WordPress 6.7.1

and

- WordPress 6.7.1
- Gutenberg 19.8.0 

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by subodhr258** [comment]
I was able to reproduce this bug. When the dropdown is being used, there is no immediate change reflected in the dropdown when we click on the `RESET` button.
It is only reflected when we click anywhere outside the box. Working on fixing this.

Recording in local:
https://github.com/user-attachments/assets/4ee3477c-681f-4196-8b57-7f3b51f96d6a

**Comment by Rishit30G** [comment]
To add more to the solution of this issue, as per my findings I could see that when the `RESET` button is clicked the value in the dropdown still remains the same even though the UI changes are taking place 

Files that can potentially be debugged: 
packages/components/src/custom-select-control/index.tsx
packages/components/src/tools-panel/tools-panel-header/component.tsx

Sharing a screencast: 
https://github.com/user-attachments/assets/adb89b29-98fc-4a8a-b366-91645e78dbe8
