### ISSUE TITLE
Give 'Add title' focus when creating new posts

### ISSUE THREAD

**Issue by dgwyer** [WordPress/gutenberg#6776]
**Describe the bug**
The 'classic' WordPress editor automatically gives the title field focus when you creating a new post. This should also be the case for new Gutenberg posts so you can start typing out a title without having to click in the field first.

**To Reproduce**
Create a new post.

To enter a title you first have to click in the field which is an unnecessary step.

**Expected behavior**
When creating a new Gutenberg post the title field should automatically have focus so you can immediately start typing out a title.

**Comment by danielbachhuber** [comment]
I agree. We should emulate core behavior in this case, unless there's been a deliberate design decision otherwise.

**Comment by karmatosed** [comment]
This is something that's come up before and whilst I understand right now in the editor this happens, perhaps we need to consider if this is the correct path. Not every post has to have a title and having it as the focus presumes that. I still feel in this case leaving it without focus is the best way forward. If someone wants to add a title it should be an option.

As this was flagged for design feedback, going to close as for now the decision is still to not add this in. Thanks for the suggestion though as it does raise the point of how with the various uses of WordPress titles aren't always used.

**Comment by dgwyer** [comment]
I don't think this issue should be closed. I would say that a post has a title most of the time rather than not and it's just something that you'd expect to see creating a new post.

It's essential that users feel comfortable using the new editor and this is one of the first pain points I experienced. It just felt awkward to have to manually click in the title field every time you create a post. I don't see any issue at all with making the title have focus as the classic post editor currently does.

For example, if the post isn't to have a title then the first action is to click to add a block. This isn't an extra step. But if you do want a post title (which is most of the time) then the title field already has focus and you can just start typing. Hence, there isn't any overhead to having the title auto focus as far as I can see.

I would also point out that this behavior is standard on other publishing platforms too (e.g. Dropbox Paper, Github, Wix - these are just the few I tested) and probably for a very good reason. So it's not just current users who would expect this behavior.
