### ISSUE TITLE
Block inserter does not work on widgets screen

### ISSUE THREAD

**Issue by mt8** [WordPress/gutenberg#67809]
### Description

I expect: Block list opens
Actual: Block list does not open

### Step-by-step reproduction instructions

1. Enable Theme TT1
2. Open Appearance > Widgets
3. Click the plus button in any widget area
4. Click [Browse all]

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/acbdf681-24b0-4bef-a715-ede98b6f21ea

### Environment info

WordPress: 6.7.1
Plugin: nothing
Theme: TT1

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [x] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by PARTHVATALIYA** [comment]
I was able to reproduce this issue. When clicking on Add Block > Browse All in the widget area, the block inserter does not open.

https://github.com/user-attachments/assets/d1a2a5a8-8710-4efe-8e18-1a5501d8d4af

**Comment by t-hamano** [comment]
Thanks for the report. I've noticed this issue first appeared in WP 6.7, so it might be worth fixing in WP 6.7.2.

**Comment by t-hamano** [comment]
With the merge of #68200, this issue will be resolved in WP 6.7.2.
