### ISSUE TITLE
Cannot save to meta from block in custom post type

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6783]
## The issue
When a block saves one of its attributes to a custom meta field, that block does not work in custom post types, as the value you input will be erased on save.

## Reproduction steps
1. Create a plugin that registers a custom meta field and a custom block.
2. Give the custom block an attribute that is sourced from the custom meta field.
3. Add an input field to the custom block to change the value of the meta field.
4. Install the plugin on a WordPress site with Gutenberg installed.
5. Create a new standard core WordPress post.
6. Insert the custom block and input some data to be saved to the custom meta field.
7. Notice that the data is retained upon save.
8. Create a new post of your custom post type.
9. Insert the custom block and input some data to be saved to the custom meta field.
10. Notice that the data is removed upon save.

## Expected behavior
You should be able to save attributes to a custom meta field in a custom block in any post type, not just the core ones.

**Comment by ocean90** [comment]
Does the custom post type has defined support for `custom-fields`?

**Comment by SuperGeniusZeb** [comment]
I guess I was mistaken then. Thanks for pointing that out, @ocean90! :smile:

Closing this issue.
