### ISSUE TITLE
add /assets folder to plugin build process

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#67835]
## What problem does this address?
It allows the implementation of a Playground blueprint for a Live preview of the Gutenberg plugin in the repo. 
The blueprint was added in #67742 

## What is your proposed solution?
~~Add a line to the [build process script.](https://github.com/WordPress/gutenberg/blob/b66f9ff095f5b70f9af15a50af1772c0e201a5e6/bin/build-plugin-zip.sh#L83-L93)~~ That's obviously wrong...  

as @t-hamano was wondering about  [in this comment ](https://github.com/WordPress/gutenberg/pull/67742#issuecomment-2536084453)

**Comment by sirreal** [comment]
Assets are not part of the plugin zip, the assets would need to be synced to this directory on publish: https://plugins.trac.wordpress.org/browser/gutenberg/assets

**Comment by sirreal** [comment]
It seems like assets should be synced as part of [this flow](https://github.com/WordPress/gutenberg/blob/b66f9ff095f5b70f9af15a50af1772c0e201a5e6/.github/workflows/upload-release-to-plugin-repo.yml).

**Comment by sirreal** [comment]
The contents of https://plugins.trac.wordpress.org/browser/gutenberg/assets should probably also be synced to this repo if we go this route.

**Comment by bph** [comment]
So the folder /blueprints folder from this repo's /assets folder needs to go into the https://plugins.trac.wordpress.org/browser/gutenberg/assets folder. 

Cc: @karmatosed
