### ISSUE TITLE
wp-scripts: Build fails when using pnpm with hoisting disabled.

### ISSUE THREAD

**Issue by manzoorwanijk** [WordPress/gutenberg#67866]
### Description

While reproducing #67864, I noticed that if I don't install `@bable/runtime` as a dependency, I see an error when using pnpm with hoisting disabled.

`Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'`

The fix the probably to have `@bable/runtime` as a dependency for the scripts package.

<details>
<summary> ⚠  Click to expand the full error reported ⚠ </summary>
<code>
> wp-scripts build

[webpack-cli] Failed to load '/node_modules/.pnpm/@wordpress+scripts@30.7.0_@playwright+test@1.49.1_@types+eslint@9.6.1_@types+node@22.10.2_@ty_wroepmchm5g4fgh3o3zlqgqj4a/node_modules/@wordpress/scripts/config/webpack.config.js' config
[webpack-cli] Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /node_modules/.pnpm/rtlcss-webpack-plugin@4.0.7/node_modules/rtlcss-webpack-plugin/dist/src/index.js
- /node_modules/.pnpm/@wordpress+scripts@30.7.0_@playwright+test@1.49.1_@types+eslint@9.6.1_@types+node@22.10.2_@ty_wroepmchm5g4fgh3o3zlqgqj4a/node_modules/@wordpress/scripts/config/webpack.config.js
- /node_modules/.pnpm/webpack-cli@5.1.4_webpack-bundle-analyzer@4.10.2_webpack-dev-server@4.15.2_webpack@5.97.1/node_modules/webpack-cli/lib/webpack-cli.js
- /node_modules/.pnpm/webpack-cli@5.1.4_webpack-bundle-analyzer@4.10.2_webpack-dev-server@4.15.2_webpack@5.97.1/node_modules/webpack-cli/lib/bootstrap.js
- /node_modules/.pnpm/webpack-cli@5.1.4_webpack-bundle-analyzer@4.10.2_webpack-dev-server@4.15.2_webpack@5.97.1/node_modules/webpack-cli/bin/cli.js
- /node_modules/.pnpm/webpack@5.97.1_webpack-cli@5.1.4/node_modules/webpack/bin/webpack.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/node_modules/.pnpm/rtlcss-webpack-plugin@4.0.7/node_modules/rtlcss-webpack-plugin/dist/src/index.js:3:30)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/node_modules/.pnpm/rtlcss-webpack-plugin@4.0.7/node_modules/rtlcss-webpack-plugin/dist/src/index.js',
    '/node_modules/.pnpm/@wordpress+scripts@30.7.0_@playwright+test@1.49.1_@types+eslint@9.6.1_@types+node@22.10.2_@ty_wroepmchm5g4fgh3o3zlqgqj4a/node_modules/@wordpress/scripts/config/webpack.config.js',
    '/node_modules/.pnpm/webpack-cli@5.1.4_webpack-bundle-analyzer@4.10.2_webpack-dev-server@4.15.2_webpack@5.97.1/node_modules/webpack-cli/lib/webpack-cli.js',
    '/node_modules/.pnpm/webpack-cli@5.1.4_webpack-bundle-analyzer@4.10.2_webpack-dev-server@4.15.2_webpack@5.97.1/node_modules/webpack-cli/lib/bootstrap.js',
    '/node_modules/.pnpm/webpack-cli@5.1.4_webpack-bundle-analyzer@4.10.2_webpack-dev-server@4.15.2_webpack@5.97.1/node_modules/webpack-cli/bin/cli.js',
    '/node_modules/.pnpm/webpack@5.97.1_webpack-cli@5.1.4/node_modules/webpack/bin/webpack.js'
  ]
}
 ELIFECYCLE  Command failed with exit code 2.

</code>
</details>

### Step-by-step reproduction instructions

- Checkout https://github.com/wptrainingteam/devblog-dataviews-plugin/pull/4
- Run `pnpm remove @babel/runtime`
- Run `pnpm install`
- Run `pnpm build`
- See the build failure

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by gziolo** [comment]
`@babel/runtime` is listed as a dependency for `@wordpress/babel-preset-default`:

https://github.com/WordPress/gutenberg/blob/94df94101b05a7884f1fd783321f0b3cde6501e5/packages/babel-preset-default/package.json#L40

which is listed as a dependency for `@wordpress/scripts`:

https://github.com/WordPress/gutenberg/blob/94df94101b05a7884f1fd783321f0b3cde6501e5/packages/scripts/package.json#L38

I'm not sure what exactly happens when using `pnpm`with hoisting disabled, but I would expect it has the package installed.

Is that issue specific to `@wordpress/dataviews` package with the `build-wp` version or a general problem?

**Comment by manzoorwanijk** [comment]
> I'm not sure what exactly happens when using `pnpm` with hoisting disabled, but I would expect it has the package installed.

It's something related to the import of `rtlcss-webpack-plugin` which interestingly [defines `@babel/runtime` as a dependency](https://github.com/wix-incubator/rtlcss-webpack-plugin/blob/6d73d89250f10e13e16f353cadaf1469771aeea2/package.json#L40)

> Is that issue specific to `@wordpress/dataviews` package with the `build-wp` version or a general problem?

No, it's a general issue.

**Comment by gziolo** [comment]
I was checking `rtlcss-webpack-plugin` and it might not be actively maintained as there is PR ready for updating `@babel/runtime` dependency in their repository. We also have a related issue tracked already:
- https://github.com/WordPress/gutenberg/issues/62007

The plugin is so simple that we could consider forking it. In fact, we already use a fork ... 😅

**Comment by gziolo** [comment]
I'm working on a potential fix:
- https://github.com/WordPress/gutenberg/pull/68201
