### ISSUE TITLE
Block Editor breaks after updating to Gutenberg 19.8.0 - Blocks missing inside the editor

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#67875]
### Description

Hey,

since Gutenberg version 19.8.0 something strange is happening. Before this update or without the active Gutenberg plugin installed, everything worked as expected.

Now the complete block editor is empty and has no block content. In my case, this affects the page post type only. Other post types seem to work correctly.

This is only related to the new version 19.8.0 of the Gutenberg plugin. There are no console errors or anything like that. Watch the video to see what happens.

So I debugged it and found the reason why this problem occurs.

In my theme I use:

```php
if ( ! function_exists( 'panther_setup_theme' ) ) :
    function panther_setup_theme() {
        remove_theme_support( 'block-templates' );
    }
endif;

add_action( 'after_setup_theme', 'panther_setup_theme' );
```

After commenting this out, this problem is solved.

This is a bug that needs to be fixed urgently.

### Step-by-step reproduction instructions

See the issue description.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/8f0a1fe4-507b-4dfe-921c-bcae2babad3d

### Environment info

- WP 6.7.1
- Gutenberg 19.8.0
- Google Chrome Browser latest

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Mamaduka** [comment]
@CreativeDive, are you using a block theme or a classic? I think I know the reason for the failure, but I want to be sure I covered all the cases.

**Comment by CreativeDive** [comment]
@Mamaduka I have a `theme.json` inside the theme folder. So I think it's a block theme.

In my case I builded an own template system, I don't use the FSE template feature, so template support is disabled via `remove_theme_support( 'block-templates' );`

**Comment by Mamaduka** [comment]
@CreativeDive, #67879, should fix the bug.

You can use the snippet below to fix the issue temporarily, until new Gutenberg plugin is release.

```js
add_filter( 'register_post_type_args', function( $args ) {
	unset( $args['default_rendering_mode'] );
	return $args;
}, 20 );
```

**Comment by CreativeDive** [comment]
@Mamaduka Thank you for sharing this snippet to temporary fix this issue. It's working!

**Comment by Mamaduka** [comment]
Hi, @CreativeDive 

I just wanted to follow up on this. What's the case for using a block theme with `block-templates` disabled? The `wp_is_block_theme` will return `false` when you have a classic theme with just a `theme.json` file.

I'm trying to cover all the cases before new default rendering mode ships with WP 6.8.

**Comment by CreativeDive** [comment]
Hey @Mamaduka, 

the possibilities are greater than you probably realize. But you can do almost anything with WordPress. In my case, I developed an independent template system. I use all the block functionality but not the FSE part. It is not a classic theme. It is more of a self-developed FSE solution.

Currently, no further problems have arisen for me after the update resolved this.
