### ISSUE TITLE
Add ability to copy settings from one block to another.

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6788]
## Check this out!
https://www.elegantthemes.com/blog/theme-releases/divi-feature-update-a-game-changing-new-way-to-be-creative-with-divi

https://www.youtube.com/watch?v=7ngwSY84GYc

Divi has just added the ability to easily copy individual styles and paste them into other modules via context menus and keyboard shortcuts. This is a very powerful feature which solves one of the most annoying issues I have experienced when creating stuff with page builders: copying styles from one object to other already existing objects.

## Gutenberg-ify it!
Of course, in the context of things like copying all button styles or heading styles from one module to another (as shown in the video), that can be made simpler in Gutenberg since most buttons would just be instances of the same Button block. This feature would mainly apply to things like background color, text size, and other things that currently exist as reused components throughout different block types.

You should be able to copy individual settings or whole groups of settings from one block to another, and ideally you should be able to copy them from one block type to another block of a completely different type. Copying things like the color of a background and pasting them into a text color option would also be quite nice.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @SuperGeniusZeb !

I've filed this away in the [Ideas project](https://github.com/WordPress/gutenberg/projects/8) for future consideration. At this point in the Gutenberg development cycle, we're focusing on finishing the remaining features and then switching to bug fixing / polish.
