### ISSUE TITLE
"Convert to blocks" of Gallery creates a List block instead

### ISSUE THREAD

**Issue by miina** [WordPress/gutenberg#6790]
**Describe the bug**
When extending Gallery block so that the saved content gets modified and then removing the extending code creates validation error which offers you to either "Convert to blocks" or "Edit as HTML". In case of most of the blocks this seems to work as expected (e.g. Image, Embed, Code, etc.), however, in case of Gallery block "Convert to blocks" creates a list instead.

This would mean that if a plugin extends the gallery block and then gets disabled, it would likely cause the block to cause validation error with "Convert to blocks" not working as expected.

**To Reproduce**
1. Extend the gallery block, for example by using this filter:
```
wp.hooks.addFilter( 'blocks.getSaveContent.extraProps', 'foobar/addExtraAttributes', function( props, blockType, attributes ) {
			if ( 'core/gallery' !== blockType.name ) {
				return props;
			}
			return _.assign( { 'data-test': 'foobar' }, props );
		} );
```
2. Create a Gallery block and save;
3. Remove the extending code, thus creating the validation error;
4. Click "Convert to blocks";
5. See a list block created;

**Expected behavior**
Clicking "Convert to blocks" on Gallery block should create/restore the gallery block.

**Screenshots**
1. Created gallery with extending code:
![screen shot 2018-05-16 at 9 56 07 pm](https://user-images.githubusercontent.com/3294597/40138305-0a076776-5955-11e8-899f-3566c85cfc2a.png)

2. Removed the extending code and refreshed the edit page:
![screen shot 2018-05-16 at 9 57 00 pm](https://user-images.githubusercontent.com/3294597/40138372-2618f510-5955-11e8-9a9c-66b3bd8a46de.png)

3. Clicked on "Convert to Blocks":
![screen shot 2018-05-16 at 9 57 09 pm](https://user-images.githubusercontent.com/3294597/40138383-2e067a40-5955-11e8-96a6-14f8406aae9d.png)

**Context**
Gutenberg: 2.8

**Comment by tecnogaming** [comment]
This is STILL HAPPENING.  Is there someone in the Gutenberg team to care to fix this?.  It is happening all over the place,  ALL THE FREAKING TIME.  Gutenberg is UNUSABLE because of this.    I just can't believe this bug is still out there.

**Comment by designsimply** [comment]
Closing in favor of #7344. 

@miina could you let me know if you think this issue is not covered by #7344 so we can re-open? I am working to help test and sort issues and this one looks the same as #7344 and easier to test in terms of technical capability. 😊 Thank you!
