### ISSUE TITLE
Refactor "Settings" panel of Site Title block to use `ToolsPanel` instead of `PanelBody`

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#67901]
Part of #67813 

Convert the "Settings" panel of the Site Title block to use the `ToolsPanel` instead of `PanelBody`

**Comment by t-hamano** [comment]
I am reopening this issue as there are issues that need to be resolved.

See https://github.com/WordPress/gutenberg/pull/67898#discussion_r1895812854

cc @Sukhendu2002
