### ISSUE TITLE
Transform process loses Inspector changes if done before Saving

### ISSUE THREAD

**Issue by mattyrob** [WordPress/gutenberg#6791]
**Describe the bug**
I have written a block that produced a shortcode in the post content. I am used Inspector controls to provide a user interface for the creation of shortcode parameters.

The Transforms for my block work well on saved content but if the Inspector controls are used to changed the intended shortcode output and then the block is transformed before a save, the change is lost on the transform process.

I may well be doing something wrong but it seems that 

**To Reproduce**
1. I will try to attach example block code that will demonstrate this.

**Expected behavior**
The transform process should preserve and use information from the Inspector that modifies content, even before saving.

**Comment by mattyrob** [comment]
```
// Version 1.0 - Initial version
( function( blocks, i18n, element, components ) {
	var el = element.createElement,
		CheckboxControl = components.CheckboxControl;

	blocks.registerBlockType( 'my-shortcode/shortcode', {
		title: i18n.__( 'Transform Test' ),
		icon: 'email',
		category: 'widgets',
		attributes: {
			shortcode: {
				type: 'text',
				selector: 'p'
			},
			nojs: {
				type: 'boolean'
			}
		},
		transforms: {
			to: [
				{
					type: 'block',
					blocks: [ 'core/shortcode' ],
					transform: function( content ) {
						return blocks.createBlock( 'core/shortcode', { text: content.shortcode } );
					}
				}
			],
			from: [
				{
					type: 'block',
					blocks: [ 'core/shortcode' ],
					transform: function( content ) {
						if ( 'shortcode' === content.text.substr( 1, 9 ) ) {
							var shortcode = content.text;
							var params = content.text.replace( /^\[shortcode|\]$/g, '' ).replace( /^\s+|\s+$/g, '' ).split( /['"]\s/g );
							var param, nojs;

							for ( var i = 0; i < params.length; i++ ) {
								param = params[i].split( '=' );
								if ( 'nojs' === param[0] ) {
									nojs = param[1].replace( /['"]+/g, '' ) === 'true';
								}
							}

							return blocks.createBlock( 'my-shortcode/shortcode', {
								shortcode: shortcode,
								nojs: nojs
							} );
						}
					}
				}
			]
		},
		edit: function( props ) {
			var nojs = props.attributes.nojs || false,
			isSelected = props.isSelected;

			function onChangeNojs( newNojs ) {
				props.setAttributes( { nojs: newNojs } );
			}

			return [
				isSelected && el(
					blocks.InspectorControls,
					{ key: 'my-shortcode/inspector' },
					el( 'h3', {}, i18n.__( 'Shortcode Parameters' ) ),
					el(
						CheckboxControl,
						{
							id: 'nojs',
							label: i18n.__( 'Disable Javascript' ),
							checked: nojs,
							onChange: onChangeNojs
						}
					)
				),
				el(
					'div', {
						key: 'my-shortcode/block',
						style: { backgroundColor: '#ff0', color: '#000', padding: '2px', 'textAlign': 'center' }
					}, i18n.__( 'HTML Shortcode' )
				)
			];
		},
		save: function( props ) {
			var attributes = props.attributes || '';
			var nojs = '';

			if ( true === attributes.nojs ) {
				nojs = ' nojs="true"';
			}

			props.attributes.shortcode = '[shortcode' + nojs + ']';
			return el( element.RawHTML, null, '<p>' + props.attributes.shortcode + '</p>' );
		}
	} );
} ) (
	window.wp.blocks,
	window.wp.i18n,
	window.wp.element,
	window.wp.components
);
```

**Comment by youknowriad** [comment]
I'm not sure I undestand the question but the transforms are only run if the content is transformed to block (from an old post or something), If you're already using a block, the transforms are not used at all.

**Comment by youknowriad** [comment]
Actually, my bad, you're talking about block transforms and I was talking about the "shortcode" transforms.

**Comment by youknowriad** [comment]
The issue in your code is that you're trying to edit the attribute in the `save` function but that's wrong. The `save` function is just used to serialize the block. What you need to do instead is to update the `shortcode` attribute on response to the inspector control instead of using a separate `nojs` attribute.

**Comment by mattyrob** [comment]
@youknowriad 

I've tried updating the shortcode but `props.setAttributes` seems to execute late.

For example, in any of the onChange functions, if we add some `window.alert();` calls and then click a check box:

`window.alert( newNojs );` // returns true if the box is checked and false if unchecked
`window.alert( props.attributes.nojs );` // called before the `props.setAttributes` returns the opposite of the alert above
`window.alert( props.attributes.nojs );` // called **after** the `props.setAttributes` **still** returns the opposite of the alert above

Why does it seem that `props.setAttributes` is not working in my code? I can't start trying to update the shortcode from the Inspector until this delay in updating the props variables makes sense.
