### ISSUE TITLE
Refactor "Settings" panel of Date block to use `ToolsPanel` instead of `PanelBody`

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#67917]
Part of #67813 

Convert the "Settings" panel of the Date block to use the `ToolsPanel` instead of `PanelBody`

**Comment by t-hamano** [comment]
It looks like the space above the "Choose a format" control has been lost. Let's fix this problem.

### Actual

![Image](https://github.com/user-attachments/assets/0c03057c-812a-4a81-be55-56a354647b1b)

### Expected

![Image](https://github.com/user-attachments/assets/7fa9aaa4-9cb5-476f-bb55-137c217b55a0)
