### ISSUE TITLE
Refactor "Settings" panel of Column block to use `ToolsPanel` instead of `PanelBody`

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#67922]
Part of #67813 

Convert the "Settings" panel of the Column block to use the `ToolsPanel` instead of `PanelBody`

**Comment by t-hamano** [comment]
Resetting the column count via keyboard causes focus to be lost. Let's fix this accessibility issue.

https://github.com/user-attachments/assets/b8256289-8aef-4402-a6dd-900b880e59cc
