### ISSUE TITLE
Block API: supports: useOnce

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#6795]
**Is your feature request related to a problem? Please describe.**
Most extended block features were moved into the `supports` object, except `useOnce`. 

**Describe the solution you'd like**
To become more consistent, `useOnce` should also be moved into the `supports` object.

**Comment by ocean90** [comment]
Not sure but `supports: useOnce` reads a bit weird. Maybe can change that to
`supports: multiple(Instances) : true|false`?
