### ISSUE TITLE
HTML5 semantic tags wrappers for Gutenberg block elements

### ISSUE THREAD

**Issue by tunyk** [WordPress/gutenberg#67993]
## What problem does this address?
Currently, it is not possible to use basic HTML5 semantic tags in the editor. This greatly complicates the implementation of semantic layout on websites.

## What is your proposed solution?
Add a selector for block elements in the editor to select the HTML Tag for the wrapper: div, section, header, footer, main, aside

**Comment by Mamaduka** [comment]
@tunyk, can you give us the list of blocks missing this feature?

Container blocks like Group and Template Parts (plus a couple of others) already support changing the HTML element. You can find this setting in the Advanced panel.

## Screenshot
![Image](https://github.com/user-attachments/assets/ab4a9292-2e8e-49cb-81fa-49b660321d68)

**Comment by tunyk** [comment]
> [@tunyk](https://github.com/tunyk), can you give us the list of blocks missing this feature?
> 
> Container blocks like Group and Template Parts (plus a couple of others) already support changing the HTML element. You can find this setting in the Advanced panel.
> 
> ## Screenshot
> ![Image](https://github.com/user-attachments/assets/ab4a9292-2e8e-49cb-81fa-49b660321d68)

Ideally, if there was such an element in all blocks.

H headings are often used with semantic tags, but they are not mandatory, so the block may not contain it and it makes no sense to increase the nesting (in the blocks you listed) and it is not convenient.

I would like this switch to be at least in:
- cite
- code
- table
- all media blocks (image, gallery, video etc)
- columns
- Inserts blocks

+ Woocommerce Gutenberg blocks

**Comment by Mamaduka** [comment]
The Headings block already uses semantic `h(1...6)` tags, so do other blocks in your list. Changing the wrapper element tag to something else will result in unsemantic HTML.

If you need a heading element inside `aside` or `selection`, use a Group block to compose them. Composition over options is a better alternative.

**Comment by tunyk** [comment]
Yes, aside

**Comment by Mamaduka** [comment]
Then, you can use the Group block to set the HTML element as `aside` and the next Heading block.

I think we can close this feature request. Blocks where HTML element selection makes sense already have this feature.

**Comment by afercia** [comment]
> Add a selector for block elements in the editor to select the HTML Tag for the wrapper:

The editor allows to use a Group block as a wrapper for any other block so that it is possible to make the Group block a HTML sectioning element rather than the other way around. As @Mamaduka pointed out, composition appears to be a simpler, more flexible, and more intentional way to do that.

Rather, I'm wondering about the discoverability of this feature. It's currently buried down into the 'Advanced' section and I'm not sure I understand why 'niche' features like a duotone filter are prominent in the block toolbar while selecting the type of HTML element isn't.

**Comment by Mamaduka** [comment]
Changing HTML Elements and classes has been labeled an Advanced feature, which is why they are grouped in an advanced section.

Hopefully, discoverability can be improved through documentation and tutorials.

I'm going to close the issue.
