### ISSUE TITLE
data-nosnippet for Gutenberg blocks

### ISSUE THREAD

**Issue by tunyk** [WordPress/gutenberg#67992]
## What problem does this address?
It is not uncommon for non-main content to appear in the automatic description in Google search results. This includes data from Gutenberg blocks.

Google's recommendations are as follows: https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#data-nosnippet-attr

I want to use data-nosnippet on span, div, and section elements, as recommended by Google. But due to the limitations of Gutenberg blocks, it is not possible to do this custom.

## What is your proposed solution?
Please add the option to add data-nosnippet for Gutenberg blocks in the editor (as a checkbox in the block settings)

**Comment by Mamaduka** [comment]
Thanks for creating an issue, @tunyk!

I think this is a third-party plugin territory. I've not checked, but various SEO plugins might already support it. If not, you can request a feature for your SEO plugin.

**Comment by afercia** [comment]
I would agree this proposed feature sounds more like plugin territory and I'm not sure it should be in the editor core.
Ideally, the editor should provide good APIs to make plugins' job easier, both at a block level and selected text level.

**Comment by tunyk** [comment]
I started topics for
Rank Math https://wordpress.org/support/topic/proposal-for-gutenberg-blocks/
Yoast SEO https://wordpress.org/support/topic/proposal-for-gutenberg-blocks-2/

**Comment by Mamaduka** [comment]
Thanks, @tunyk!

I'll close the issue here since it's not actionable on the editor side.
