### ISSUE TITLE
Errors on link input

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#680]
>Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.
>    `in input (created by FormatToolbar)`

>Warning: A component is changing an uncontrolled input of type url to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
>   ` in input (created by FormatToolbar)`

**Comment by mkaz** [comment]
I don't see this error - not sure if it was fixed at some point and just not closed.

It looks like this line does set a default value of empty string, however this was in place prior to this issue being opened, so seems unlikely.
https://github.com/WordPress/gutenberg/blob/master/blocks/editable/format-toolbar.js#L31

@iseulde If you can still reproduce, can you include some more info such as browser, and steps to reproduce. I'm going to look at another Link bug as part of beta milestone so will keep an eye out for it also

**Comment by iseulde** [comment]
Can definitely still reproduce. Put the caret in a word and click the link button. Genning the error mentioned above.

**Comment by iseulde** [comment]
Fixed in 00c9bbeb7d43bcd7b5c21fc07e65bedb127916c5.
