### ISSUE TITLE
Category block alignment breaks it's own UI

### ISSUE THREAD

**Issue by vtrpldn** [WordPress/gutenberg#6806]
**Describe the bug**
The float property added by align buttons breaks the category block UI.

**To Reproduce**
1. Add a category block
2. Click on align left or right

**Expected behavior**
It should keep it's block behavior, pushing other elements down.

**Screenshots**

Left-align

![image](https://user-images.githubusercontent.com/5367401/40198050-a113c9ac-59eb-11e8-8a30-d88891370abd.png)

Right-align. Overlaps shortcuts

![image](https://user-images.githubusercontent.com/5367401/40198080-bb74643c-59eb-11e8-9c6e-a4db3a87f705.png)

Right-align with duplicated blocks

![image](https://user-images.githubusercontent.com/5367401/40198337-91ae34b0-59ec-11e8-9d77-f502289fdf29.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Firefox
 - Version 60

**Additional context**
- Gutenberg 2.8.9
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Fix**
- A clearfix might solve that relatively easy, gonna take a look at that

**Comment by vtrpldn** [comment]
Turns all it happens with all blocks that can be aligned

![image](https://user-images.githubusercontent.com/5367401/40200962-10381a6a-59f4-11e8-8d74-92866b3a4e2c.png)

**Comment by danielbachhuber** [comment]
Thanks for the report, @vtrpldn.

This class of issue is already identified with #6634 #4010 and #4127

**Comment by youknowriad** [comment]
I'm not certain this is a bug, that's how float alignment works. Clearing floats could be an option but not something enforced.

**Comment by vtrpldn** [comment]
Hey @danielbachhuber, thanks for the reply. I guess the solution still need to be defined. 

IMO floats should be cleared not only to make blocks behave more like `display: block` but also to prevent the overlapping bug on align right.
