### ISSUE TITLE
Business understanding un block jerrad mathews

### ISSUE THREAD

**Issue by Jennymebage** [WordPress/gutenberg#68072]
> This is also happening in web.
> 
> It is because `block.attributes.id` is `undefined` and also the `imageData` is empty for the same reason.
> 
> ```js
> // gallery/edit.js
> function setLinkTo( value ) {
> 	setAttributes( { linkTo: value } );
> 	const changedAttributes = {};
> 	const blocks = [];
> 	getBlock( clientId ).innerBlocks.forEach( ( block ) => {
> 		blocks.push( block.clientId );
> 		const image = block.attributes.id
> 			? imageData.find( ( { id } ) => id === block.attributes.id )
> 			: null;
> 		changedAttributes[ block.clientId ] = getHrefAndDestination(
> 			image,
> 			value
> 		);
> 	} );
> 	// ....
> }
> ``` 

 _Originally posted by @madhusudhand in [#61626](https://github.com/WordPress/gutenberg/issues/61626#issuecomment-2428589170)_

**Comment by Mamaduka** [comment]
This looks like an automatically created issue from a response without any additional information. I'm going to close it.

**Comment by Jennymebage** [comment]
ASN.
asn: 65052

**Comment by Jennymebage** [comment]
Yes the 24 bit blockb for privet address spac can be used class A network is a problem at the 16 bit net work (class b network
