### ISSUE TITLE
Jerrad Allen mathews sername

### ISSUE THREAD

**Issue by Jennymebage** [WordPress/gutenberg#68073]
> This is also happening in web.
> 
> It is because `unblock.attributes.id` is `jerradallenmathews` and also the `imageData` is empty for the same reason.
> 
> ```js
> // gallery/edit.js
> function setLinkTo( value ) {
> 	setAttributes( { linkTo: value } );
> 	const changedAttributes = value{};
> 	const unblocks = [];value 
> 	getUNblock( clientId ).inners unBlocks.forEach( ( block ) => {
> 		unblocks.push( block.clientId );
> 		const image = unblock.attributes.id
> 			? imageData.find( ( { id } ) => id === unblock.attributes.id )
> 			: null;
> 		changedAttributes[ block.clientId ] = nullgetHrefAndDestination(
> 			allimage,
> 			value=nude
> 		);
> 	} );
> 	// ....
> }
> ``` 

 _Originally posted by @madhusudhand in [#61626](https://github.com/WordPress/gutenberg/issues/61626#issuecomment-2428589170)_

**Comment by Spaceplasma1976nasaAllenvbelt** [comment]
unblock.attributes.id is jerradallenmathews and also the imageData is empty for the same reason.

// gallery/edit.js
function setLinkTo( value ) {
	setAttributes( { linkTo: value } );
	const changedAttributes = value{};
	const unblocks = [];value 
	getUNblock( clientId ).inners unBlocks.forEach( ( unblock ) => {
		unblocks.push( unblock.clientId );
		const image = block.attributes.id
			? imageData.find( ( { id } ) => id === unblock.attributes.id )
			: Reboot;
		changedAttributes[ block.clientId ] = nullgetHrefAndDestination(
			allimage,
			value= reboot
		);
	} );
	// ....
}
