### ISSUE TITLE
Classic Editor breaks - WP 4.9.6+Gutenberg+Yoast

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#6809]
**Describe the bug**
I just updated one of my sites in my dev environment to WP 4.9.6 and the Classic Editor no longer shows the toolbars, or loads any content.

To narrow down the issue I deactivated all plugins except for Gutenberg and switched my theme to TwentySeventeen.

It seems to be an issue with Yoast. Disabling all plugins except for Gutenberg and it works fine.
As soon as I activate Yoast, the content and TinyMCE no longer load.

The console shows the following error:

**Loading failed for the <script> with source “http://dev.maddisondesigns.com/wp-content/plugins/gutenberg/vendor/themes/modern/theme.min.js?wp-mce-4711-20180425”.**

**To Reproduce**
1. Activate Yoast SEO
2. Update WP to 4.9.6
3. Try to create a new Post using the Classic Editor

**Expected behavior**
The TinyMCE Editor should load properly with all the toolbars and the content should load

**Screenshots**
![gutenberg_tinymcenotworking](https://user-images.githubusercontent.com/2078245/40213135-3d94de6e-5a97-11e8-8d7f-e4ba89c0385d.png)

![screenshot_659](https://user-images.githubusercontent.com/2078245/40213379-8776b344-5a98-11e8-820b-eb5b9218395f.png)

macOS Sierra 10.12.1 (16B2659)
Firefox Quantum 60.0 (64-bit)

WordPress 4.9.6
Gutenberg 2.8.0
Yoast SEO  7.5.1

**Comment by bobbingwide** [comment]
Related #4678

**Comment by maddisondesigns** [comment]
@bobbingwide looks like a different issue to me

**Comment by danielbachhuber** [comment]
I'm not able to reproduce this issue locally against trunk and Gutenberg 2.9. Can you do a bit more debugging to see if you can pull up more details?

**Comment by maddisondesigns** [comment]
It's looking for a file that doesn't exist. It's looking for `theme.min.js` in the `wp-content/plugins/gutenberg/vendor/themes/modern/` folder but there are no sub-folders under the `vendor` folder, within the Gutenberg plugin.

If I view the page source I can see a JavaScript reference to the TinyMCE Modern theme and considering part of the url above is looking for the `/vendor/themes/modern/`folder, I'm pretty confident in saying that it's related.

![screenshot_662](https://user-images.githubusercontent.com/2078245/40265694-66eea6ca-5b80-11e8-82f3-d3280389a7df.png)

In WP Core there's a `wp-includes/js/tinymce/themes/modern/theme.min.js` file. Gutenberg is looking for that same file in the plugin folder but it's not there.

Lastly, there's a couple of ACF fields on the page, but the issue occurs even when ACF is deactivated, so it's obviously nothing to do with ACF.

**Comment by maddisondesigns** [comment]
Have also updated to Gutenberg 2.9.0 and the same issue occurs

**Comment by danielbachhuber** [comment]
Related #6847
