### ISSUE TITLE
Editor doesn't scroll past bottom of page when pasting content

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#6821]
**Describe the bug**
When pasting content into a block near the bottom of the page, the editor doesn't automatically scroll.

**To Reproduce**
1. Add blocks until you get to the bottom of the browser window
2. Add a new paragraph block and copy some text into the block
3. Keep pasting text until the cursor disappears past the bottom of the browser window

**Expected behavior**
Editor should scroll no matter whether I'm pasting content or typing content

**Screenshots**
![gutenberg_editordoesn tscroll](https://user-images.githubusercontent.com/2078245/40229596-09fa78a2-5ad8-11e8-9177-cc22329d04c5.gif)

_macOS Sierra 10.12.1 (16B2659)
Firefox Quantum 60.0 (64-bit)
WordPress 4.9.6
Gutenberg 2.8.0_

**Comment by nerrad** [comment]
I can confirm this bug still exists.

**Comment by youknowriad** [comment]
Looks like the typewriter effect improved this a little bit but it's not perfect yet.

**Comment by adamziel** [comment]
Fixing https://github.com/WordPress/gutenberg/issues/5317 should also fix this one

**Comment by paaljoachim** [comment]
I pasted in lots of text and it looks like it is working fine now.

Using Twenty Twenty One. Gutenberg 9.8. WordPress 5.6.
If I am mistaken then please reopen the issue.
