### ISSUE TITLE
Video block player controls aren't usable

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#6825]
**Describe the bug**
After inserting a video into a Video Block it shows some controls for the video. Clicking on the controls does nothing. Clicking on the play button, video scrubber/slider, volume slider or full screen icon doesn't work.

Not only that, there's a toolbar that covers part of the time scrubber, which is going to render that control useless.

After clicking around in frustration for a couple of minutes I found that if you click above the control, you can actually get them to work. They don't work if you click on the controls themselves though. 

**To Reproduce**
1. Add video to video block
2. Try and click on any of the controls such as the play button or video scrubber/slider.

**Expected behavior**
The controls should work

**Screenshots**
![gutenberg_videoblockconrolsdontwork](https://user-images.githubusercontent.com/2078245/40232987-7351e0cc-5ae4-11e8-99d8-b8f288f0e468.gif)

_macOS Sierra 10.12.1 (16B2659)
Firefox Quantum 60.0 (64-bit)
WordPress 4.9.6
Gutenberg 2.8.0_

**Comment by maddisondesigns** [comment]
The same thing happens with the Audio Block as well

**Comment by danielbachhuber** [comment]
Thanks for the report, @maddisondesigns. I can confirm the issue in Firefox Quantum. If I add `z-index:2; position: relative;`, then the controls become playable:

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/36432/40257839-91a126cc-5aa4-11e8-807b-8ffeb0642357.png">

**Comment by nfmohit-wpmudev** [comment]
FYI, this issue is related to the caption inline toolbar and can be replicated in all browsers. Here's a screencast for reference:
![gutenberg-6825](https://user-images.githubusercontent.com/20284937/40281257-16b406e4-5c81-11e8-8628-183b1d00ed90.gif)

I've submitted #6853 addressing the issue.

**Comment by tofumatt** [comment]
This has been fixed and doesn't happen anymore. I'm terribly sorry I'm not sure which commit fixed it, but I can't reproduce this in Firefox 62 (Developer Edition) on Mac.
