### ISSUE TITLE
Site Editor Layout Breaks When Selecting Font Sizes with Long Names in theme.json

### ISSUE THREAD

**Issue by SainathPoojary** [WordPress/gutenberg#68271]
### Description

When adding custom font sizes with long names in the theme.json file, the Site Editor layout breaks when these font sizes are selected. The issue manifests as an overflow in the Site Editor panel, causing a horizontal scrollbar to appear. This negatively impacts the user experience by breaking the layout and making the interface difficult to use.

### Step-by-step reproduction instructions

1. Add  custom font sizes with long names in your theme’s theme.json file. Example:
```json
{
	"settings": {
		"typography": {
			"fontSizes": [
				{
					"slug": "extra-long-heading-one",
					"size": "16px",
					"name": "Extra Extra Extra Long Heading Style One"
				},
				{
					"slug": "extra-long-heading-two",
					"size": "20px",
					"name": "Extra Extra Extra Long Heading Style Two"
				}
			]
		}
	}
}
```
2. Navigate to the Site Editor (Appearance > Editor).
3. Open the Typography panel and try to select one of the custom font sizes with a long name.
4. Observe how the Site Editor layout breaks, leading to overflow and the appearance of a scrollbar.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/79e9652e-f8d5-4726-b4bd-bf2caff1284c

### Environment info

- WordPress: 6.8-alpha-59533
- PHP: 8.2.26
- Server: Apache/2.4.62 (Debian)
- Database: mysqli (Server: 11.4.4-MariaDB-ubu2404 / Client: mysqlnd 8.2.26)
- Browser: Chrome 131.0.0.0
- OS: macOS
- Theme: Emptytheme 1.0
- MU Plugins: None activated
- Plugins: Gutenberg 19.9.0

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by himanshupathak95** [comment]
I observed similar behavior with the given conditions - 


![Image](https://github.com/user-attachments/assets/e059418e-03d7-4462-94c4-5c4fc2ef3da7)

**Comment by yogeshbhutkar** [comment]
A similar thing can be replicated on mobile devices if the text becomes too large. 

![Image](https://github.com/user-attachments/assets/9441facb-48d3-4290-9b82-be237008425a)

**Comment by yogeshbhutkar** [comment]
Thank you for raising the issue, @SainathPoojary. I’ve implemented a potential fix for the issue, simply applying `display: contents` appears to resolve it.

**Comment by SainathPoojary** [comment]
Thank you for addressing the issue @yogeshbhutkar!  Applying `display: contents` seems like a reasonable solution. I’ve tested it, and it’s working correctly.

<img width="281" alt="Image" src="https://github.com/user-attachments/assets/d45bc81e-5ea9-4180-a8c0-61d376105155" />
