### ISSUE TITLE
ref="ref" breaks toolbar

### ISSUE THREAD

**Issue by Pixelous** [WordPress/gutenberg#68302]
Hi,

Can anyone please help with toolbar is not appearing when using ref="ref" https://react.dev/learn/manipulating-the-dom-with-refs in custom block?

```
return (
		<figure
			{ ...blockProps }
			className={ clsx(
				blockProps.className,
				layoutClassNames,
				'blocks-gallery-grid',
				{
					[ `align${ align }` ]: align,
					[ `columns-${ columns }` ]: columns !== undefined,
					[ `columns-default` ]: columns === undefined,
					'is-cropped': imageCrop,
				},
			) }
			ref={ galleryRef }
		>
```
Adding `ref={ galleryRef }` breaks toolbar:

![Image](https://github.com/user-attachments/assets/3608bc54-5e4b-43a5-b702-de949f4dc8cf)

No errors in Chrome console.

`console.log( galleryRef.current );` works fine.

Kind regards

**Comment by t-hamano** [comment]
How about adding the ref to the `useBlockProps` hook? Example:

```jsx
import { useBlockProps } from '@wordpress/block-editor';
import { useRef } from '@wordpress/element';

export default function Edit() {
	const ref = useRef();
	const blockProps = useBlockProps( { ref } );
	return <div { ...blockProps }>Block</div>;
}
```

**Comment by Mamaduka** [comment]
Class names and ref to the block wrapper element should be added via `useBlockProps` to merge correctly with the data the block editor provides.

https://developer.wordpress.org/block-editor/reference-guides/block-api/block-edit-save/#block-wrapper-props

**Comment by t-hamano** [comment]
I don't think what is reported here is a bug in Gutenberg, so I'd like to close this issue.

@Pixelous I hope the code and documentation links we've provided are helpful to you.

**Comment by Pixelous** [comment]
Hi, @t-hamano @Mamaduka thanks for the hint!

The problem is I have already `const blockProps`. This is the shortened code:

```
export default function Gallery( props ) {
	const {
		blockProps
	} = props;

const galleryRef = useRef();

useEffect( () => {
	console.log( galleryRef.current );
}, [] );

return (
		<figure
			{ ...blockProps }
			className={ clsx(
				blockProps.className,
				'blocks-gallery-grid',
			) }
			ref={ galleryRef }
		>
			{ blockProps.children }
		</figure>
	);
}
```
I had tried:

```
blockProps.ref = useBlockProps( {
		ref: galleryRef,
	} );
```
But no luck (

**Comment by Mamaduka** [comment]
@Pixelous, it's hard to suggest a fix with partial code.

* Is the `Gallery` block edit component?
* Where does the `blockProps` come from?
* What's the intended use for `galleryRef`?

**Comment by Pixelous** [comment]
@Mamaduka 

1. This is a copy of default Gutenberg gallery block https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/gallery/gallery.js#L34

2. https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/gallery/gallery.js#L24 https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/gallery/edit.js#L715

3. I am trying to run masonry js library https://masonry.desandro.com/

**Comment by Pixelous** [comment]
@Mamaduka @t-hamano 

This code in edit.js instead of gallery.js works fine:

```
import { useRef } from '@wordpress/element';

const ref = useRef();

const blockProps = useBlockProps( {
		className: clsx( className, 'has-nested-images' ),
		ref: ref,
	} );

	useEffect( () => {
		console.log( ref.current );
	}, [] );

	useEffect( () => {
		console.log( ref.current );
	}, [ images ] );
```

Toolbar is appearing now.

**Comment by t-hamano** [comment]
@Pixelous Perhaps you want to reference a child component from an `Edit` component? One approach is to use `fowardRef` to forward the ref. Example:

```jsx
const Gallery = forwardRef( ( { blockProps }, ref ) => {
	return (
		<div { ...blockProps } ref={ ref }>
			Children
		</div>
	);
} );

export default function Edit() {
	const ref = useRef();

	useEffect( () => {
		console.log( ref.current );
	}, [] );

	const blockProps = useBlockProps( {
		ref,
	} );
	return (
		<>
			<Gallery ref={ ref } blockProps={ blockProps } />
		</>
	);
}
```

**Comment by Pixelous** [comment]
@t-hamano ok, thanks, will keep in mind.

Appreciate your help.
