### ISSUE TITLE
Useless Editor Classic Editor Is 100 Times Better Then This.

### ISSUE THREAD

**Issue by km-to-mi** [WordPress/gutenberg#68333]
WordPress should revert back to classic editor as this new editor has lots of issues.

**Comment by flowenworld** [comment]
[https://github.com/Gogamukh-A-Small-Town-in-Upper-Assam](url)

**Comment by Mamaduka** [comment]
@flowenworld, can you provide a link for the issues you're experiencing?

Otherwise, general comments like this are disrespectful and discouraging to the contributors who worked hundreds of hours on this project.
