### ISSUE TITLE
Impossible to drag blocks inside InnerBlock with Full Width enabled

### ISSUE THREAD

**Issue by nk-o** [WordPress/gutenberg#6845]
**Describe the bug**
When the container block is set to Full Width, it is not possible to drag Inner Blocks inside.

**To Reproduce**
1. Add Columns block
2. Make it Full Width
3. Insert blocks inside it
4. Try to drag inner blocks

**Screenshots**
1. ![image](https://user-images.githubusercontent.com/14810891/40268081-dd230928-5b6f-11e8-88a1-1b1a479f003b.png)
2. ![image](https://user-images.githubusercontent.com/14810891/40268195-e510a828-5b71-11e8-9687-2847f8d283ec.png)
3. ![image](https://user-images.githubusercontent.com/14810891/40268206-fc70642c-5b71-11e8-88a8-efb49b4684a5.png)
4. ![image](https://user-images.githubusercontent.com/14810891/40268209-0a302066-5b72-11e8-9183-4a208853d0de.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 66

**Additional context**
- 2.9.0

**Comment by mtias** [comment]
This works for me after some of the latest refactors to block outlines.
