### ISSUE TITLE
Classic Editor Visual Mode Broken by Gutenberg

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#6847]
**Describe the bug**
WordPress 4.9.6
Gutenberg 2.9.1

The Classic Visual Editor is broken ; displays only a white screen. Text view okay.

**To Reproduce**
1. Disable all plugins except Gutenberg.
2. Activate a Twenty-Something theme (I used Twenty Sixteen).
3. Open Dashboard : Pages, Select some page, and click Classic Editor
4. The Visual Editor show a white screen. Nothing editable.
5. Strange side effect: If you switch to Text View, content there. Switch back to Visual, see blank screen. Now switch BACK to Text View, and all the line breaks are gone - just run together HTML.

**Expected behavior**
Duh - the classic editor needs to work. Note that WP 4.9.6 updated TinyMCE.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome, Firefox
 - Version: latest

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by danielbachhuber** [comment]
Related #6809

**Comment by weavertheme** [comment]
2.9.1 seems to break WP 4.9.5 also, except even the Text View doesn't show there.
