### ISSUE TITLE
RichText formatting for one line of text is not saved 

### ISSUE THREAD

**Issue by virgiliud** [WordPress/gutenberg#6850]
## Issue Overview
The RichText formatting is showing in the edit screen but not being saved for one line of text. I'm using Gutenberg 2.9.1

## Steps to Reproduce (for bugs)
1. Add a block which uses the RichText API (heading, or quote) 
2. Add one line of text and add a link to it or emphasize using the toolbar
3. Update
4. Refresh editor screen or view the published page/post

I am using Chrome

## Current Behavior
After updating the page/post and refreshing the edit screen, the formatted text is not saved. It works however if you add normal text after the formatted text. For example, add a link and on the second line add normal text.

**Comment by iseulde** [comment]
After some initial testing, I can see that there is no call to `onChange` when formatting some text for the first time in a `RichText` instance. There is a call on subsequent formatting. I tested this in 2.8 and there seems to be the same issue, although `onChange` is called for some other user actions so it's not as obvious. I'm unsure if this is exactly this issue, but noting it here.
