### ISSUE TITLE
Extending blocks - validation fail

### ISSUE THREAD

**Issue by virgiliud** [WordPress/gutenberg#6856]
I'm using `blocks.getSaveContent.extraProps` to add a background to all blocks. I'm using the exact code from the documentation.  https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#blocks-getsavecontent-extraprops

I'm running the code from a plugin and it works fine but when disabling the plugin I get Block validation failed on blocks. Is this normal or is it a bug?

**Comment by gziolo** [comment]
This is expected behavior, but it isn't perfect. We should improve this experience.

There is also a related issue described in this article [WordPress Gutenberg Block API: Block Look and Feel](https://code.tutsplus.com/tutorials/wordpress-gutenberg-block-api-part-2--cms-31057):

> Secondly, when editing the contents of the `save` method, something strange seems to happen to the editor window when it's next refreshed.
> 
> To demonstrate this, I added a new list item (`<li>Indigo</li>`) in the `save` method and then refreshed the post editor (after having to clear the cache again, of course!). Here's the result:
>
> <img src="https://cms-assets.tutsplus.com/uploads/users/1527/posts/31057/image/save-error.png" />
> 
> Block update issue
> 
> If you choose either **Convert to Blocks** or **Edit as HTML** then you get presented with the contents of the `save` method, which is meant to be viewed on the front end and not in the editor.
> 
> Convert to blocks and edit as HTML views
>
> <img src="https://cms-assets.tutsplus.com/uploads/users/1527/posts/31057/image/two-errors.png" />
> 
> This is very confusing, and the only obvious way to bring things back to normality was to delete the block from the editor window and reinsert it again. As I mentioned in the previous post, Gutenberg is still a work in progress, and this is a good example of that!

**Comment by gziolo** [comment]
In the meantime @johngodley added support for showing the difference between invalid block and the original one which should mitigate the issue:

> The difference appears in a modal and the user can select to keep the current contents or apply the conversion, with full knowledge of the result of their action.
> 
> ![another_post___ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/42805227-2d622be2-89a3-11e8-929f-ee2fb78e6270.jpg)

See 
https://github.com/WordPress/gutenberg/pull/7995 for more details.

I think this closes this report given that it was never an actual bug.
