### ISSUE TITLE
Attempt to Sort Nested/Multi-column Block grabs internal blocks.

### ISSUE THREAD

**Issue by bahia0019** [WordPress/gutenberg#6857]
**Describe the bug**
When attempting to sort block sections that contain nested or multi-columns, the "Move Up/Move Down" icon from the inner-left block displays instead of the containing block. 
The containing block "Move Up/Move Down" icon does show but after some hunting with the cursor.

**To Reproduce**
1. Create a nested/multi-column block.
2. Hover over block in an attempt to move drag/drop or click "Move Up/Move Down" icon.
3. Inner block icon will display.
4. Move cursor around a little above to finally see containing block "Move Up/Move Down" icon.

**Expected behavior**
Since this is a nested block/multi-column, my assumption is that the block author meant for the structure to remain tied to that block.
I would expect that the "Move Up/Move Down" icons not display for internal blocks, and only for the containing block.

**Screenshots**
<img width="1198" alt="screen shot 2018-05-20 at 4 58 15 pm" src="https://user-images.githubusercontent.com/1586037/40285508-c5526b12-5c51-11e8-96ce-0d0df8af90de.png">

<img width="1198" alt="screen shot 2018-05-20 at 5 15 13 pm" src="https://user-images.githubusercontent.com/1586037/40285509-c56a075e-5c51-11e8-969e-aacb1763cd86.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.3
 - Browser: Chrome
 - Version: 66.0.3359.139

**Additional context**
- Gutenberg: Version 2.9.1

**Comment by mtias** [comment]
Closing as there have been multiple changes to the nested block and columns UI with improvements in this area.
