### ISSUE TITLE
Uploading to Gallery Block acts funny. Photos Disappear. 

### ISSUE THREAD

**Issue by bahia0019** [WordPress/gutenberg#6861]
**Describe the bug**
Using the Upload button in a Gallery Block the browser selector pops up, I select a handful of images, and push Upload. One of two things happen:
1. In Posts the photos upload, but then disappear, and then reappear again. 
2. In CPTs a 1 pixel bar of the photo flashes quickly, and then they all disappear.   

**To Reproduce**
1. Open a gallery block.
2. Upload images.

**Expected behavior**
Expected behavior is no flashing or disappearing images.

**Screenshots**

![funny upload post](https://user-images.githubusercontent.com/1586037/40288290-5eeacc8c-5c67-11e8-8885-564f9761f3cf.gif)

![funny upload cpt](https://user-images.githubusercontent.com/1586037/40288289-5ed0c5da-5c67-11e8-8c04-f3fdf147148c.gif)

**Desktop (please complete the following information):**
 - OS: MacOS 13.3
 - Browser: Chrome
 - Version: 66.0.3359.139

**Additional context**
I am on a Local by Flywheel environment, and I'm also using Templates for the Services Post Type.

**Comment by mtias** [comment]
This improvement has been added to uploading images to a gallery: https://github.com/WordPress/gutenberg/pull/7657

Please, reopen if you are still seeing issues.
