### ISSUE TITLE
Post formats not selectable

### ISSUE THREAD

**Issue by metamn** [WordPress/gutenberg#6864]
**Describe the bug**
With the latest plugin update (2.9.1) and Wordpress update (4.9.6) when using the Gutenberg editor one can't select the format of the post.

**To Reproduce**
1. Go to 'All posts'
2. Click on 'Edit' on one of the posts
3. On the right sidebar there is no 'Formats' section

**Expected behavior**
A Formats section should be visible also in the Gutenberg editor, as is in the Classic editor

**Screenshots**
![The Gutenberg editor without the Formats](https://user-images.githubusercontent.com/86295/40292510-64b67bbc-5cd4-11e8-807f-03491a7dabbc.png)
![The Classic editor with Formats](https://user-images.githubusercontent.com/86295/40292546-a3bdc270-5cd4-11e8-87be-1939586b78a7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Firefox
 - Version: 60.0 (64-bit)

**Comment by danielbachhuber** [comment]
Hi @metamn,

Which WordPress theme are you using?

**Comment by metamn** [comment]
That would be https://wordpress.org/themes/log-lolla/

It's made by me so I can modify it if necessary.

Thank you.

**Comment by danielbachhuber** [comment]
Thanks @metamn. This isn't specific to your theme, but rather a regression introduced in https://github.com/WordPress/gutenberg/commit/63abd32d9b5cb809ad71167f209dd7a6d0a79a3f#diff-110a4693fc7c5790ebeacaef78d7fa14R16 (#6500) which landed in 2.9.

cc @youknowriad
