### ISSUE TITLE
Meta tags and categories are not displayed in the Gutenberg editor. How to fix?!

### ISSUE THREAD

**Issue by shamhaner** [WordPress/gutenberg#6868]
Meta tags and categories are not displayed in the Gutenberg editor. How to fix?!

**Comment by danielbachhuber** [comment]
Hi @shamhaner,

I'm not sure I follow. Could you share more details about your issue, including a screenshot if possible, your Gutenberg version, and any debugging steps you've tried?

**Comment by youknowriad** [comment]
Are you talking about the default tags/categories or a custom taxonomy?
By default, the tags/categories taxonomies have a `show_in_rest` set to `true`. Make sure you didn't change this and if it's a custom taxonomy, make sure it's set to true as well.

**Comment by shamhaner** [comment]
Taxonomy on the site works. In my case, it is not possible to specify a category and a tag in the new record; they are not displayed in the menu of the gutenberg editor. The classic editor has no problems with this, the categories and shortcuts are where they are assigned, everything works correctly and without problems. Please tell me in which file I should check the specified parameters in the themes of the Wordpress or the gutenberg plugin.

**Comment by shamhaner** [comment]
It's decided. Plugin settings "iThemes Security" => "WordPress Tweaks" => expose "Default Access"  (Access to REST API data is left as default. Information including published posts, user details, and media library entries is available for public access.) => "Save Settings"
