### ISSUE TITLE
"Updating failed" for any article with error 400

### ISSUE THREAD

**Issue by GenaBitu** [WordPress/gutenberg#6875]
**Describe the bug**
I downloaded Gutenberg 2.9.2 through brand new WordPress 4.9.6, activated it (only active plugin) and tried to edit a post. I got "Updating failed" with error 400.

**To Reproduce**
1. Download and activate Gutenberg
2. Edit a post
3. Click "Update"

**Expected behavior**
The article is saved

**Screenshots**
![screenshot from 2018-05-21 20-19-09](https://user-images.githubusercontent.com/3134692/40322983-5d59c08a-5d34-11e8-858b-f186906b8c50.png)

![screenshot from 2018-05-21 20-19-19](https://user-images.githubusercontent.com/3134692/40322987-61d8fba8-5d34-11e8-88f6-47a7cf80c41a.png)

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
```

**Desktop:**
 - Debian testing
 - Firefox, Chromium
 - 60.0.1, 62.0.3202.89

**Server:**
 - Apache 2.4.33
 - Tried PHP 5.6, 7.0 and 7.2

**Additional context**
Adding an article leads to the same result. Opening the address of the XHR is successful and gives me some JSON.

**Comment by danielbachhuber** [comment]
Hi @GenaBitu,

This appears to be a server configuration issue. Can you open a support ticket with your hosting company and see what they say?

**Comment by GenaBitu** [comment]
Hi, I have already discussed it with my hosting provider and other webpages on the same hosting seem to work fine.
I can check the server configuration, but I have no idea where to start...
Is there something I can do to find out the cause of this?

**Comment by GenaBitu** [comment]
I've now also tried enabling Gutenberg on another webpage (same hosting) and I get the exact same result...

**Comment by GenaBitu** [comment]
Ok, I've tried a website configured by my friend who has used Gutenberg there and it works for him, but it fails for me. No idea.

**Comment by danielbachhuber** [comment]
Sorry :/ This is specific to your hosting configuration. I'll flag this in the `#hosting-community` channel to see if someone might have a suggestion.
