### ISSUE TITLE
Add "Today" to the Date Picker

### ISSUE THREAD

**Issue by bahia0019** [WordPress/gutenberg#6881]
**Is your feature request related to a problem? Please describe.**
Being able to bounce back to Today in the date picker should be performed by a simple button press rather than walking back through months/years.

**Describe the solution you'd like**
Add a "Today" button in the Date Picker UI
I'm attaching a few random Date Picker's on a Google image search.
The third one is Joomla's

![date_picker](https://user-images.githubusercontent.com/1586037/40332755-23fd11a4-5d0a-11e8-882f-c95debb1c2de.png)
![datepicker](https://user-images.githubusercontent.com/1586037/40332756-24135306-5d0a-11e8-89c5-791387fac012.png)
![datepicker1 calendar-en](https://user-images.githubusercontent.com/1586037/40332757-2428213c-5d0a-11e8-9afd-2c85ce9c587f.png)

**Comment by HardeepAsrani** [comment]
React Date Picker, which is used by Gutenberg, does allow a "Today" button by default, but that button takes you to the current date of your browser, I suppose, not your WordPress timezone.

**Comment by bahia0019** [comment]
That could work. I don't see that really being an issue.
If I click "Today" I would expect it to go to the actual "Today."
If I'm traveling in Australia and it's Wednesday, but my site is on US Pacific time, I'd expect it to go to Wednesday, not Tuesday.

**Comment by HardeepAsrani** [comment]
Not like that, but let's imagine it this way:

My website is running on London time and it's Saturday night there, while it's Sunday in India. When I click on Today, it takes me to the current date which is Sunday in time, even tho it's Saturday for the website, so WordPress takes it as a future time, in my case.

**Comment by HardeepAsrani** [comment]
I also see a utcOffset parameter, which should fix this issue.

**Comment by bahia0019** [comment]
The scenario you laid out is exactly the same as mine, but with different countries.

Again, I would expect when I click Today, that it snaps to the Today of the timezone I'm currently in, not based on the WordPress setting.

**Comment by HardeepAsrani** [comment]
No, that’s not what you want. If I do that in India right now, my post will be “Scheduled” instead of being Published. It’s hard to understand in text and I only understood when I tried that with code. :)

**Comment by HardeepAsrani** [comment]
Yup, adding a timezone offset worked. Let me send a PR. :)

**Comment by HardeepAsrani** [comment]
@bahia0019 Maybe you can also test on your side to make sure I didn't miss anything. :)

**Comment by bahia0019** [comment]
I do need some coffee, but that's because I've got to figure out how to setup a Multisite on Google Cloud right now! :D 
I'll see what I can do about this if I get some time. If not, hopefully it's merged into the next release of Gutenberg and I'll see it then.

Thanks for contributing to this!

**Comment by tofumatt** [comment]
There's talk of using a new date picker component in #7621 (see: https://github.com/WordPress/gutenberg/pull/7621#issuecomment-401605022).

I think it's likely that this will be addressed when #1311 is addressed.

**Comment by karmatosed** [comment]
As we have the new date component lets close this one and focus there.

**Comment by Kpudlo** [comment]
Would it be possible to open this back up? We finally switched our team over to Gutenberg and this was a requested feature. 

If you look at the Classic Editor, the Today button is visible:
![image](https://user-images.githubusercontent.com/4432822/82907614-d6423380-9f34-11ea-9888-3d2d809221e1.png)

However, the Gutenberg Editor doesn't have that button:
![image](https://user-images.githubusercontent.com/4432822/82907694-eeb24e00-9f34-11ea-83f3-ad0d6d00f870.png)
