### ISSUE TITLE
Publishing and Updating Fails (maybe a Multisite issue)

### ISSUE THREAD

**Issue by bahia0019** [WordPress/gutenberg#6883]
**Describe the bug**
When I add a new post with Gutenberg, the post will attempt to autosave after a few seconds, but instead of autosaving, an error message displays across saying Updating Failed.
When I attempt to publish, the same error pops up saying Publishing Failed, and the Publish button returns. 

Classic editor posts just fine. See screen cast video below. 

(This may be a Multisite issue as I have another local site that is not Multisite, and it seems to work fine. I've posted my Local by Flywheel configuration as a screenshot below as well.
I will run a couple more tests to see if I can pinpoint any issues.)

**To Reproduce**
1. Create new post wait for autosave. 
2. Publish.

**Expected behavior**
No error message.

**Screenshots**
![update-failing](https://user-images.githubusercontent.com/1586037/40334599-8c0272fe-5d13-11e8-9af7-f828ca8bd9d1.gif)

<img width="660" alt="screen shot 2018-05-21 at 4 23 41 pm" src="https://user-images.githubusercontent.com/1586037/40334629-b26e8e0a-5d13-11e8-837c-fd58df911d2c.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.3
 - Browser: Chrome
 - Version: 66.0.3359.139

**Comment by danielbachhuber** [comment]
Hi @bahia0019,

Can you look at your Network tab in the Developer Tools to see and report the actual error response?

**Comment by bahia0019** [comment]
This is the console when I create a new Gutenberg post: 
<img width="1272" alt="screen shot 2018-05-21 at 4 34 41 pm" src="https://user-images.githubusercontent.com/1586037/40334816-f237cf3c-5d14-11e8-91e6-e23a3d8158d8.png">

And this is console errors when I publish:
<img width="836" alt="screen shot 2018-05-21 at 4 32 28 pm" src="https://user-images.githubusercontent.com/1586037/40334827-07d20fe2-5d15-11e8-9084-4d7eaf8f9c83.png">


On the Network side of things:
<img width="778" alt="screen shot 2018-05-21 at 4 38 27 pm" src="https://user-images.githubusercontent.com/1586037/40334887-7617c172-5d15-11e8-8486-fc71aea8d6f3.png">
<img width="570" alt="screen shot 2018-05-21 at 4 37 39 pm" src="https://user-images.githubusercontent.com/1586037/40334889-7cbb4b34-5d15-11e8-9c1f-65ad0d4e1fe7.png">

That url-metrics is from my Mozbar Chrome extension. Nothing to do with WP.

**Comment by danielbachhuber** [comment]
It looks like your WP REST API is returning 404 responses for every request. Can you debug a bit further as to why that might be the case?

**Comment by bahia0019** [comment]
That's exactly what it was. For some reason something was off with Local by Flywheel. 
Switched from Apache to Nginx and back, and everything is working fine.
I'll close this item.

Thanks for looking @danielbachhuber.

**Comment by ericariel** [comment]
I also encountered this problem. After I tried to change the fixed link, everything returned to normal
