### ISSUE TITLE
Selecting the Document tab should deselect blocks. 

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#6887]
**Describe the bug**

When you select a block and the Settings sidebar is open, the Block tab is automatically selected. 

When you deselect a block, the Document tab is then opened.

If you select a block, then click the Document tab, logically this should also deselect the block.

**To Reproduce**

- Click a block, observe the Block tab is opened
- Click the Documents tab, observe the block is not deselected

**Expected behavior**

Way back, in version 0.6 I think, we used something a similar feature to autoselect the block inspector when a block had focus. We used a "breadcrumb" style instead of tabs for the sidebar, the idea being that the sidebar was always contextual, and when you had no block selected you were at the document scope, when a block selected you dug into the block scope.

This behavior is now reinstated, although with tabs. But because deselecting a block automatically selects the Document tab, it feels like selecting the Document tab when a block is selected should logically also deselect the block. 

**Screenshots**
![deselect](https://user-images.githubusercontent.com/1204802/40348699-b423e0e2-5da4-11e8-9997-293a85f24a0a.gif)

**Comment by karmatosed** [comment]
> it feels like selecting the Document tab when a block is selected should logically also deselect the block.

I would +1 that this behaviour makes sense.

**Comment by jasmussen** [comment]
> This also means that if we switch to the document settings and immediately switch back to the block inspector, the block inspector will be empty. Do we want this?

I would consider this the expected behavior, yes, because selecting the block tab doesn't also select a block, whereas I feel like the inverse is true.

**Comment by SuperGeniusZeb** [comment]
@youknowriad @jasmussen Would it make sense to not show the “Block” tab at all when no block is selected, then?

**Comment by jasmussen** [comment]
Potentially, but then they aren't really tabs anymore. In a way past implementation, as I mentioned, we used breadcrumbs instead of tabs. But that wasn't popular, whereas the same sidebar switching behavior now with the tabs seem to have caused less of an issue.

**Comment by rogerlos** [comment]
Just noting, for me, If I have a block selected, my expectation was that if I selected "document" in the inspector (say, to check a value there) and then switch back to block without doing anything in the document inspector, I was expecting to still see "my" block info there...as I didn't really deselect the block, if you can follow my logic ("this sidebar seems to be block contextual").

Perhaps if the block has to be deselected when viewing "document" properties, a link could be placed in the block inspector sidebar to "reselect last block" if the user switches back to allow easy refocusing?
