### ISSUE TITLE
Classic Block Toolbar not fixed on screen

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#6890]
In any block, the toolbar is fixed on screen. So if writing longer text (more than screenhigh) the toolbar is already visible.
But the toolbar in Classic Block is not fixed. Editing longer content (more than screenhigh) with help of the toolbar is NOT really possible!
Also the page option "show toolbar fixed at the top" is not available for Classic Block.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @burnuser.

I've filed this away in the [Ideas project](https://github.com/WordPress/gutenberg/projects/8) for future consideration. At this point in the Gutenberg development cycle, we're focusing on finishing the remaining features and then switching to bug fixing / polish.
