### ISSUE TITLE
Insert Link to image needs "open in new tab" option

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#6891]
We have the (needed!) "open in new tab" option for text links. But image linking is missing this option.

For example if using icons of external websites as link source (Facebook, an NGO, Companys, ...) the "open in new tab" option is also needed!

**Comment by danielbachhuber** [comment]
Related #6392

**Comment by antpb** [comment]
I'm going to work on getting this going. Can we get some design feedback on if we should have the option in both the modal and the editor? I think exposing this option only in the editor is what we need.

**Comment by antpb** [comment]
Looks like this is solved now that https://github.com/WordPress/gutenberg/pull/9520 is merged.
