### ISSUE TITLE
Gutenberg is not WYSIWYG

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#6892]
In Classic TinyMCE the editor width is controlled by the theme (for example "Twentysixteen: page has more width than post) to get the same width in editing a page/post as in the resulting webpage.
That's true WYSIWYG.
(I know, responsive display on smaller screens changes everything, but Billions of users on the whole world are using - especially in business context - big screens!)

In Gutenberg (announced as true WYSYWIG editor) with its fixed editor width, What You See Is NEVER What You Get! That's a terrible fallback against Classic TinyMCE Editor!

**Comment by Soean** [comment]
@burnuser 
You can set the editor width via CSS in your Theme, see in the Handbook:
https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#changing-the-width-of-the-editor

**Comment by burnuser** [comment]
Dear Soean, I think we need a solution with existing themes (for example Twentysixteen) and without the need of any coding. In Classic TinyMCE an average user without any codingskills has WYSIWYG out of the box. Gutenberg should not be less comfortable in such an important point.

**Comment by danielbachhuber** [comment]
Hi @burnuser,

Thanks for the report. We haven't quite decided how to handle `$content_width`. See #5650 for further conversation.
