### ISSUE TITLE
"Status & Visibility" heading incorrect color in Firefox Quantum

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#6898]
![image](https://user-images.githubusercontent.com/36432/40377241-46f6e784-5da5-11e8-8d06-4aa2424866b2.png)

It should be white, not grey:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/36432/40377272-587144a0-5da5-11e8-8a8e-dc03d77cb3b1.png">

From https://wordpress.slack.com/archives/C02QB2JS7/p1527001520000263

**Comment by vtrpldn** [comment]
It also doesn't outline on focus and apply other properties related to `.components-button:not(:disabled):not([aria-disabled="true"]):focus`
