### ISSUE TITLE
"Open in new window" option only works if you already placed the link

### ISSUE THREAD

**Issue by vtrpldn** [WordPress/gutenberg#6900]
**Describe the bug**
If you try to toggle the "Open in new window" without the link being already set the modal closes.

**To Reproduce**
1. Go to a RichText block
2. Select some text
3. Try to toggle the "Open in new window" 

**Expected behavior**
The best UX would be keeping the modal open so the user can keep filling the link.

**Screenshots**
![link-bug](https://user-images.githubusercontent.com/5367401/40378346-a6a4cb6e-5dc9-11e8-90ea-949b9faa1cb2.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.4
 - Browser: Firefox 59

**Additional context**
- Gutenberg 2.9.2

**Comment by Soean** [comment]
#6886 fixes this issue
