### ISSUE TITLE
Automatic hiding of the "Post updated!" message.

### ISSUE THREAD

**Issue by yuanworks** [WordPress/gutenberg#6906]
**Is your feature request related to a problem? Please describe.**
I decided to use Gutenberg on a production website as a real world example, where I write long posts, and I find myself frequently saving the draft or updating the post (a habit from when Word didn't have recover/auto-save). I've noticed that the "Post updated!" message doesn't hide or disappear after you continue to type, and stays on top of the editor:

![image](https://user-images.githubusercontent.com/3508123/40403320-cbcb9246-5e83-11e8-8ca4-058177e14b6b.png)

**Describe the solution you'd like**
1. Fading/closing the message after typing or clicking (focusing) the editor. Or;
2. Fading the message after a few seconds.
 
Thanks!

**Comment by Soean** [comment]
Related #4495

**Comment by danielbachhuber** [comment]
Filed this as `Needs Design Feedback` to see if we want to reconsider the original conclusion.

**Comment by youknowriad** [comment]
It seems to me that it has been stated that we want to keep it as is for now https://github.com/WordPress/gutenberg/issues/4495#issuecomment-385391685

I'm closing. Let's reopen if it's not the case anymore.
