### ISSUE TITLE
Change InspectorControl position / order when registering via blocks.BlockEdit filter

### ISSUE THREAD

**Issue by virgiliud** [WordPress/gutenberg#6907]
When adding a new InspectorControl panel, is it possible to change its ordering/position? Currently it seems like custom panels are stacked on top of the default panels.

**Comment by danielbachhuber** [comment]
Hi @virgiliud,

Inspector controls should appear in the order they're registered. Can you share more detail about what you're trying to do, including screenshots and sample code?

**Comment by virgiliud** [comment]
Hi @danielbachhuber 

I'm extending the default blockEdit component using:

```
import Inspector from './components/inspector';
const withInspectorControl = createHigherOrderComponent( ( BlockEdit ) => {
	return ( props ) => {
		const { animation } = props.attributes;
		return (
			<Fragment>
				<Inspector { ...props } />
				<BlockEdit { ...props } />
			</Fragment>
		);
	};
}, 'withInspectorControl' );

addFilter( 'blocks.BlockEdit', 'my-plugin/withInspectorControl', withInspectorControl );
```
This adds a new block panel (from components/inspector):

```
<InspectorControls>
   <PanelBody title={ __( 'New Settings' ) } initialOpen={ false } >
   ...
   </PanelBody>
</InspectorControls>
```

But the "New Settings" panel/inspector control appears before all the default panels. I'm trying to find out if i can change the order of the new inspector control

**Comment by virgiliud** [comment]
![image](https://user-images.githubusercontent.com/3076742/40427098-bad5fe9a-5e6a-11e8-83ec-4c2875528fec.png)

As you can see in the image, the new panel is on top

**Comment by gziolo** [comment]
If you want to put it at the end of settings you should render `Inspector` after `BlockEdit`:

```diff
import Inspector from './components/inspector';

const withInspectorControl = createHigherOrderComponent( ( BlockEdit ) => {
	return ( props ) => {
		const { animation } = props.attributes;
		return (
			<Fragment>
-				<Inspector { ...props } />
				<BlockEdit { ...props } />
+				<Inspector { ...props } />
			</Fragment>
		);
	};
}, 'withInspectorControl' );

addFilter( 'blocks.BlockEdit', 'my-plugin/withInspectorControl', withInspectorControl );
```

It's the same rule as you would have with DOM by using `prepend` vs `append`.
