### ISSUE TITLE
Default paragraph block type still available when blacklisted

### ISSUE THREAD

**Issue by tomasruud** [WordPress/gutenberg#6916]
I don't know if this is a possible duplicate or something that is being worked on, but I have made a set of custom block types which I want to enforce my users to use. To make it even easier for the users, I have disabled all of the default blocks, including the paragraph block. However, because the editor displays the paragraph block by default, it is still possible to technically insert that block, without using the "Add block" menu.

**To Reproduce**
1. Blacklist `core/paragraph`
2. Create/edit any post
3. Click on the `Add text or type / to add content` and type some text
4. The paragraph block is added

**Expected behavior**
I would expect only whitelisted blocks to be available, and possibly that there would be no default block.

**Comment by youknowriad** [comment]
The editor needs a "default" block to work. This default block should have the same attributes (content type array) as the paragraph block. If you disable the default block, you can set an alternative default block using `wp.blocks.setDefaultBlockName( 'myblock' )`.

**Comment by tomasruud** [comment]
I can't get this to work. I have created a block which is not possible to edit, that has the same content attribute as the paragraph block.
```js
const {__} = wp.i18n
const {registerBlockType} = wp.blocks

registerBlockType('namespace/ignored', {
  title: __('Ignored block'),
  icon: 'minus',
  category: 'widgets',

  attributes: {
    content: {
      type: 'array',
      default: []
    }
  },

  edit() {
    return <span/>
  },

  save() {
    return null
  }
})
```
When I try to register it with the function you provided it still doesn't work.
