### ISSUE TITLE
Unable to upload a featured image when using Gutenberg editor

### ISSUE THREAD

**Issue by scott-grav** [WordPress/gutenberg#6919]
**Describe the bug**
(See screen shot) When I open the "Featured Image" section there is no input where I can upload an image
**To Reproduce**
1. Go to a Post and edit using the Gutenberg editor
2. Click on "Featured Image" under "Document" in the sidebar

**Expected behavior**
An upload input or some way to access my media library should show

**Screenshots**
I have attahced a screenshot of what I am seeing

**Desktop (please complete the following information):**
 - OS: Mac OS X El Capitan
 - Browser Chrome
 - Version 66.0.3359.139

**Additional context**
- This test site is running on my local MAMP environment
![2018-05-23_0841](https://user-images.githubusercontent.com/11282157/40435617-e156bc76-5e65-11e8-9764-92fd299a576d.png)

**Comment by Soean** [comment]
@scott-grav 
Have you deactivated the other plugins for testing?
Do you have any errors in the JS developer console?

**Comment by MasterAnakin** [comment]
I experienced the same issue, no error in the console: https://prnt.sc/jlbi7q

**Comment by jaymullen** [comment]
I just had the same issue.  I disabled the ACF plugin which the site is also using and it fixed the issue.

**Comment by scott-grav** [comment]
@jaymullen I also deactivated ACF and that fixed it for me. Thank you for the feedback. I will try that ACF updated next

**Comment by scott-grav** [comment]
Yes, updating ACF Pro to 5.6.10 fixed the issue. Thanks all

**Comment by vaheedxp** [comment]
I have this problem too. No other plugin is installed, just Gutenberg is installed and activated but still the featured image is missing. please help me.

**Comment by vaheedxp** [comment]
> I have this problem too. No other plugin is installed, just Gutenberg is installed and activated but still the featured image is missing. please help me.

I found that my single.php page is not supporting featured image, because i started to code my theme from scratch.
