### ISSUE TITLE
Consider state middleware injection as extensibility mechanism

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#692]
Related: #594

In #594, when a post draft finishes saving, we adjust the current browser URL to reflect the new post ID. While this is necessary in the context of the dedicated editor screen, this reduces the portability of the editor as these URL changes are not applicable outside this context. If we'd want to allow initializing an editor on other screens (e.g. front-end, Customizer), we might need to explore options for injecting context-specific middlewares. This could serve as a generic extensibility pattern for any side effects of state changes.

For the post save navigation example, this could look something like:

```js
wp.editor.injectMiddleware( ( store ) => ( next ) => ( action ) => {
	const { type, isNew, post } = action;
	if ( 'REQUEST_POST_UPDATE_SUCCESS' === type ) {
		const [ baseUrl, query ] = window.location.href.split( '?' );
		const qs = parse( query || '' );
		const newUrl = baseUrl + '?' + stringify( {
			...qs,
			post_id: newPost.id,
		} );
		window.history.replaceState( {}, 'Post ' + newPost.id, newUrl );
	}

	return next( action );
} );
```

See also:

- http://redux.js.org/docs/advanced/Middleware.html
- https://hyper.is/#extensions-api (`middleware`)

**Comment by dmsnell** [comment]
Check out Automattic/notifications-panel and how we do this to integrate with Automattic/wp-calypso

[injecting the enhancers](https://github.com/Automattic/notifications-panel/blob/1c047b4408024ae1a01c991958132c6d318ff614/src/Notifications.jsx#L81)

[default actions for iframe mode](https://github.com/Automattic/notifications-panel/blob/1c047b4408024ae1a01c991958132c6d318ff614/standalone/index.js#L22)

[custom integrations in Calypso](https://github.com/Automattic/wp-calypso/blob/master/client/notifications/index.jsx#L158)

**Comment by gziolo** [comment]
8 months passed and we still need it 😃 We had a major refactoring in the way we handle data, but middlewares still play an important role. We could explore whether hooks library would be a good fit here. We might inject additional middlewares using filters in here: https://github.com/WordPress/gutenberg/blob/master/editor/store/middlewares.js#L40. @youknowriad suggested to make in an internal  API for start.

**Comment by aduth** [comment]
This is superseded by new patterns with data module: Notably the `subscribe` and `withSelect` APIs, which allow a developer to observe for and react to changes over time: https://github.com/WordPress/gutenberg/blob/master/packages/data/README.md
