### ISSUE TITLE
This block appears to have been modified externally.

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#6925]
**Is your feature request related to a problem? Please describe.**

Now I'm trying to build some new blocks using create-guten-block. 
I'm getting totally frustrated with "This block appears to have been modified externally." because some tiny thing is mismatched.

I don't know the code that triggers that message, but if there is any possibility at all, it would be great if there were another option to show what triggered the message. Would likely save many plugin developers tons of time.

**Describe the solution you'd like**
Either some kind of config setting, or a third button on the message dialog.

**Describe alternatives you've considered**

**Comment by ajitbohra** [comment]
@weavertheme its already taken care in case of `This block appears to have been modified externally. ` debugging info is output in browser console which can help developers to troubleshoot the issue. 

![block-modified](https://user-images.githubusercontent.com/1039236/40467462-aae15088-5f47-11e8-9cf3-5afaae81194c.png)

**Comment by youknowriad** [comment]
Closing as there's already an indication.

**Comment by skorasaurus** [comment]
Unfortunately, this isn't a very helpful explanation. I've run into the same problem and as I understand, it's that gutenberg is expecting that the block's content (as a plugin; not the content that you'd type into gutenberg) doesn't change. 

I've seen that you've encountered this again in https://github.com/WordPress/gutenberg/issues/7097

For anyone who comes across this issue via google (which is how I did); see 
https://github.com/WordPress/gutenberg/issues/6826
and 
https://github.com/WordPress/gutenberg/issues/7604

**Comment by shrimp2t** [comment]
I have the same problem, please fix.
