### ISSUE TITLE
font family for InspectorControls

### ISSUE THREAD

**Issue by robbisy** [WordPress/gutenberg#6931]
Would be great to have something like this in the InspectorControls
![easy-google-fonts](https://user-images.githubusercontent.com/18592516/40474272-dd2ae3aa-5f3e-11e8-9720-0259dfefbb3e.jpg)

**Comment by karmatosed** [comment]
Can I check what you are suggesting? You are wanting to have the option to change fonts in the page editor?

**Comment by robbisy** [comment]
@karmatosed  Yes

**Comment by karmatosed** [comment]
Thanks for clarifying @robbisy, whilst I understand this option could be useful for some for version one of Gutenberg this isn't something that will be added. It totally may be something considered in later versions. I can also see maybe this being a plugin as an option.
