### ISSUE TITLE
Multi-selection: Select the whole block before moving on to multi-select

### ISSUE THREAD

**Issue by joehoyle** [WordPress/gutenberg#6949]
When I'm editing a post with my keyboard only, and hold SHIFT + arrow keys to progressively select more text, once I reach the block boundary (and have all text selected), the next "SHIFT + down arrow" will select the current block, _and_ the next block.

It would feel much more natural to me if first it selected just the current block, and _then_ once I press SHIFT + down again, it would select the 2 blocks.

I don't know if I'm describing it super well, so I made a quick gif of the current behavior:

![picture](https://user-images.githubusercontent.com/161683/40519312-ec090cd2-5f8c-11e8-800a-3b88cd33b009.gif)

There's no step inbetween having the inner text selected (up until the last word) and then having _2_ blocks selected. I think there should certainly be first a selection of the whole current block step, so I could more easily achieve block-level operations on the current block.

**Comment by mtias** [comment]
It sounds similar to formatting boundaries (links, bold, italics) but applied to blocks. cc @iseulde @mcsf

**Comment by SuperGeniusZeb** [comment]
In a similar scenario, pressing <kbd><kbd>Ctrl</kbd>+<kbd>A</kbd></kbd> once will select the text in a block. Pressing it again does nothing. Pressing it a third time selects all blocks.

I think pressing <kbd><kbd>Ctrl</kbd>+<kbd>A</kbd></kbd> twice should select the block, rather than doing nothing. It feels weird for it to select the text, then seem to do nothing, then select all blocks.

**Comment by designsimply** [comment]
Quick note to mention some issues with `ctrl+a`, or `meta+a`, noted in the latest comment were fixed in #8180.

**Comment by designsimply** [comment]
After reviewing this issue in more detail, it appears that #3629 has some in-depth discussion about selecting text over multiple blocks and I would like to consolidate to that issue. @joehoyle if you think this issue should remain open separate from #3629, please ask to re-open here with a note. Thank you!
