### ISSUE TITLE
Keyboard shortcut to delete current block

### ISSUE THREAD

**Issue by joehoyle** [WordPress/gutenberg#6950]
When using a keyboard to edit my post, I can't seem to find a way to delete the current block (unless if it's a paragraph)

#6949 could provide a way to do this, perhaps - but it's possible I'm missing something very basic, to which I can only apologize to create unneeded issues!

If my keyboard focus is as follow, how do I delete the block?

![](https://joehoyle-captured.s3.amazonaws.com/yoeXKIyV.png)

Pressing backspace when in the following situation (caret after the block) just switched focus back to the embed url input

![](https://joehoyle-captured.s3.amazonaws.com/65jJNesX.png)

**Comment by danielbachhuber** [comment]
Related #4299

**Comment by karmatosed** [comment]
Let's make sure we co-ordinate in #4299 as I do think they are related - in theory fixing there will fix here. Thanks for reporting and lets focus on that issue for now.
