### ISSUE TITLE
Comparing the existing content creation and Gutenberg.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#6952]
Hey

I am placing my mind in neutral as best that I can checking out the existing content creation with TinyMCE.

https://youtu.be/bXz7uvyO43Y

Then with the above content creation in mind looking at how a few things are done with Gutenberg version 2.9.2.

https://youtu.be/6eOHbpEtR-w

Bottom line is that Gutenberg is a very powerful tool to use for laying out content. A huge leap compared to TinyMCE.

**Comment by danielbachhuber** [comment]
Hi @paaljoachim,

Thanks for putting together these videos. Are there any actionable changes you'd suggest at this time?

**Comment by paaljoachim** [comment]
Hey Daniel thanks for the headsup and the very good reminder!

I am looking at various things I encountered and notice these things are not taken care of (I believe there area issues for the following items. I am just not able to locate them at present.)

- As one adds a single or gallery image there is a drop down option to link to None, Attachment page or Media file but there is no way to link to an URL. 
- Selecting one image in a gallery changes the link to option for all of them
- I know I have seen an issue for this: Heading text alignment should be above next to h2 H3 H4 to keep it consistent.
- Changing the color of text changes all the text in the block. One can not select a word and change that to another color. (As could be done in the classic editor.)

I think that is it for now. We can probably just close this issue when that feels right.

**Comment by danielbachhuber** [comment]
> * As one adds a single or gallery image there is a drop down option to link to None, Attachment page or Media file but there is no way to link to an URL.
> * Selecting one image in a gallery changes the link to option for all of them

As a matter of fact, I don't see issues for these first two in the [backlog with the "Media" label](https://github.com/WordPress/gutenberg/issues?page=1&q=is%3Aopen+is%3Aissue+label%3AMedia). Could you create them?

> * Changing the color of text changes all the text in the block. One can not select a word and change that to another color. (As could be done in the classic editor.)

Is this #7131?

**Comment by paaljoachim** [comment]
I think that both the first two issues will need to be covered in #5309
The second issue is then described in as you mention 7131 for additional better inline styling of specific words and more. I do will do some work on 5309. Both are issues I believe we need to discuss how to handle during perhaps an open office.

**Comment by mtias** [comment]
Thanks for providing feedback and videos. Going to close with label Feedback as there's nothing actionable.
