### ISSUE TITLE
In between inserter sometimes stays visible

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#6953]
**Describe the bug**
I can't figure out exact steps to reproduce quickly, but after some time the in between inserter stay visible. Hovering over it doesn't hide it.

**Screenshots**

![inserter-between](https://user-images.githubusercontent.com/4710635/40543535-2a4ae4aa-6025-11e8-9575-20c083db1075.gif)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 66.0.3359.139

**Comment by mtias** [comment]
I can't reproduce this with the latest tweaks.
