### ISSUE TITLE
Meta Boxes: Meta boxes absent when script enqueued in head depends on `wp-edit-post`

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#6963]
**Describe the bug**

If a plugin registers a script which depends on `'wp-edit-post'` and does not explicitly pass [`$in_footer` as `true` in its script registration](https://developer.wordpress.org/reference/functions/wp_register_script/), meta boxes will not be displayed.

**To Reproduce**

1. Create a file at `wp-content/mu-plugins/demo-breakage.php` with the following content:

```php
<?php

/**
 * Plugin Name: Demo Breakage
 */

add_action( 'init', function() {
    wp_enqueue_script( 'demo-breakage', '/', [ 'wp-edit-post' ] );
} );
```

2. Activate at least one plugin which adds a meta box (e.g. Yoast)
3. Navigate to the editor
4. Note that the meta box is not shown

**Expected behavior**

Meta boxes should be shown regardless of whether plugin author passes `$in_footer => true`, or this should be very clearly documented, as it is too easy to overlook and too difficult to debug (speaking from experience).

**Suspected cause**

#5943 changed Gutenberg script registration to enqueue in footer (cc @pento)

Meta boxes rely on this because they are not registered until Gutenberg content is output:

https://github.com/WordPress/gutenberg/blob/1e689af43b6e29336678eac29278de8afaf5808c/gutenberg.php#L33

https://github.com/WordPress/gutenberg/blob/1e689af43b6e29336678eac29278de8afaf5808c/lib/meta-box-partial-page.php#L327-L330

So when a plugin depends on `wp-edit-post` and it does not register itself to be enqueued into the footer, it effectively pulls the `wp-edit-post` enqueuing into the head instead. Since the meta boxes' `wp_add_inline_script` is called after the `wp-edit-post` inline scripts have already been printed, it is never output to the page (and thus never called).

Alternative solution: Should late `wp_add_inline_script` be accounted for in some fashion, similar to `print_footer_script`'s handling of ["scripts that were queued [...] too late for the HTML head"](https://developer.wordpress.org/reference/functions/print_footer_scripts/) ?

**Additional context**

- Gutenberg 2.9.2

**Comment by wpscholar** [comment]
Created a ticket for a more elegant, long term solution to this issue: https://core.trac.wordpress.org/ticket/44709#ticket
