### ISSUE TITLE
Metaboxes repositioned by user in Classic Editor are stranded

### ISSUE THREAD

**Issue by spwarner** [WordPress/gutenberg#6965]
In the Classic Editor, users can drag metaboxes from the side to the main 'normal' column, and vice versa. This is saved to usermeta with the key 'meta-box-order_$page'. Gutenberg respects the location the user dragged the metabox to, but does not support drag/drop at this point so the location can't be changed further.

Drag & Drop between side & normal contexts should either be enabled in Gutenberg, or Gutenberg should ignore previous user dragging and render the metabox only in the context it is defined in by the plugin.

**Comment by SolespireMarcus** [comment]
In my opinion, it would be most ideal if Gutenberg not only respects user meta through the 'meta-box-order_$page' key but also allows classic drag/drop in the new editor with Admin functionality to turn off this ability and instead set a site-wide locked order of meta boxes for all registered users.

**Comment by danielbachhuber** [comment]
Thanks for the report, @spwarner.

This issue is already tracked with #5841. Closing in favor of that issue.
