### ISSUE TITLE
Update button remains disabled when update failed

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#6966]
**Describe the bug**
I updated some plugins in another tab and during that I saved my gutenberg post. Since plugin updates put the site in "Maintenance mode" the post update failed, console showing:

`Failed to load resource: the server responded with a status of 503 (Service Unavailable)`

Which is understandable, how ever the "Update" button remains disabled even after the maintenance is complete. 

![Disabled update button](https://i.imgur.com/NLHV9JN.png)

This prevents from trying to save the post again, forcing to refresh the page and lose all updated content.

**To Reproduce**
1. Update or install some plugins in another tab
2. Try to save a post
3. Maintenance mode over
4. Can't attempt to save again

**Comment by nfmohit-wpmudev** [comment]
I do not seem to be able to reproduce the issue. Here's a screencast from my end:
![issue-6966-min](https://user-images.githubusercontent.com/20284937/40578497-02328b40-6137-11e8-978c-5d19da748ca6.gif)

Do you think I'm missing something here?

**Comment by ktmn** [comment]
I tried with Twenty Seventeen and it also worked like your screencast.

The previous theme I used had metaboxes. So to test I installed a [random plugin](https://wordpress.org/plugins/open-graph-metabox/) that also adds a metabox and that reproduced my issue.

Along with this error:
`POST .../wp-json/wp/v2/posts/117 503 (Service Unavailable)`

I also get this:
`POST .../wp-admin/post.php?post=117&action=edit&classic-editor=1&meta_box=1 503 (Service Unavailable)`

So looks like the presence of metaboxes could be the culprit.

**Comment by lubimow** [comment]
I have the same problem

**Comment by blogxkomo** [comment]
i have same problem too

**Comment by noisysocks** [comment]
I was able to reproduce this by:

1. Configuring my dev environment to use a local WordPress installation by setting `"core": "~/path/to/wordpress-develop/build"` in `.wp-env.json`
1. Activating the 'Gutenberg Test Plugin, Meta Box' plugin 
1. Creating a post in the block editor and entering some content
1. Forcing maintenance mode by creating a file at `~/path/to/wordpress-develop/build/.maintenance` which contains. 

   ```php
   <?php
   $upgrading = time();
   ```
1. Returning to the editor and clicking _Save draft_
1. Deleting `~/path/to/wordpress-develop/build/.maintenance`

Although the site is now not in maintenance mode, you cannot click _Save draft_.

**Comment by noisysocks** [comment]
Possibly related: #19780

**Comment by paaljoachim** [comment]
Is this issue still valid?

**Comment by paaljoachim** [comment]
Robert @noisysocks Can you recheck this issue? Thanks.
