### ISSUE TITLE
Show all block-related button on hover

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#6984]
**Is your feature request related to a problem? Please describe.**
I was very confused about how to delete a block, I looked for a button but there wasn't any. I hovered over a block, and there were just arrows on the left-hand side. Just by accident I hovered over the right side of a block and discovered some new UI elements. 

<img width="67" alt="zrzut ekranu 2018-05-28 o 16 54 09" src="https://user-images.githubusercontent.com/205419/40621193-13c906b6-629c-11e8-9056-39a4cba29d1e.png">

**Describe the solution you'd like**

Display all block-related buttons regardless of hover location. Also display them when a block is being edited.

**Describe alternatives you've considered**

Display all block-related buttons at all times and have a special distraction-free mode accompanied with a short guided tour to hide them by default. It should be more obvious how things work this way.

**Comment by mtias** [comment]
Showing the UI all the time on hover quickly makes the interface look crowded. This was a deliberate change done a few versions ago to improve this perception. To learn where things can be accessed there's https://github.com/WordPress/gutenberg/pull/6631
