### ISSUE TITLE
Move "add block" button to block context

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#6986]
**Is your feature request related to a problem? Please describe.**
I was very confused about how to add a block, I was looking for some kind of "+" button related to blocks but all I could see was a "+" button in the navigation bar here:

<img width="912" alt="screen shot on 2018-05-28 at 17_29_39" src="https://user-images.githubusercontent.com/205419/40621456-109d3d44-629d-11e8-9903-e66ab28172cc.png">

Finally I clicked on it and discovered it is the add block button, I hesitated for some time because it seemed to be related to post as a whole since the same bar contains "save" and "preview" buttons.

**Describe the solution you'd like**

I would move this "+" button inside the editor like this, it would clearly suggest what is it for:

<img width="910" alt="zrzut ekranu 2018-05-28 o 17 31 49" src="https://user-images.githubusercontent.com/205419/40621442-04f1e9ae-629d-11e8-9156-5251846b5684.png">

**Comment by SuperGeniusZeb** [comment]
Related: #6834.

See also the recently-merged new(-ish) in-between inserter design of #6818 that will be included in Gutenberg 3.0.

**Comment by karmatosed** [comment]
There are a few ways to add a block and the top menu is just one. You can have it beside the content:

![2018-06-22 at 15 27](https://user-images.githubusercontent.com/253067/41783959-2da6313c-7636-11e8-873e-7247fe7571b8.png)

You can also add in-between blocks:

![2018-06-22 at 16 12](https://user-images.githubusercontent.com/253067/41784251-0caf46f2-7637-11e8-957f-2fb7fe6ef8d1.png)

For now going to close this as there are a few options to add blocks already there.

**Comment by SuperGeniusZeb** [comment]
Notably, the placeholder block (seen in the first screenshot posted by @karmatosed as well as at the bottom of the second one) does not appear after a Paragraph block. To insert after a Paragraph block requires using the inserter button in the top bar or pressing `Enter`.

Personally, I think that either the placeholder should always be shown at the bottom of a post, or (and this is my preferred option) the sibling inserter should be usable at the bottom of the last block in a post or nested context. See also: #6834.
