### ISSUE TITLE
Syntax error for PluginPostStatusInfo example in README

### ISSUE THREAD

**Issue by jsmoriss** [WordPress/gutenberg#6992]
**Describe the bug**

I'm getting `SyntaxError: expected expression, got '<'` when using the PluginPostStatusInfo example from the README:

https://github.com/wordpress/gutenberg/blob/8efddae270b3cb451b39568fefac87e50f5097e7/edit-post/README.md#pluginpoststatusinfo

**To Reproduce**

The example code is:

```
const { __ } = wp.i18n;
const { PluginPostStatusInfo } = wp.editPost;

const MyPluginPostStatusInfo = () => (
	<PluginPostStatusInfo>
		{ __( 'My post status info' ) }
	</PluginPostStatusInfo>
);
```

**Comment by gziolo** [comment]
Can you try using ES5 syntax? Example:

```js
var el = wp.element.createElement;
var __ = wp.i18n.__;
var PluginPostStatusInfo = wp.editPost.PluginPostStatusInfo;

var MyPluginPostStatusInfo = function() {
    return el( 'PluginPostStatusInfo', {}, __( 'My post status info' ) );
);
```

**Comment by jsmoriss** [comment]
I don't get a syntax error in the browser console anymore, but nothing changes in the "Status & Visibility" box.

```
var el = wp.element.createElement;
var PluginPostStatusInfo = wp.editPost.PluginPostStatusInfo;
var MyPluginPostStatusInfo = function() {
        return el( 'PluginPostStatusInfo', {}, 'TEST' );
}
```

BTW, is 'PluginPostStatusInfo' only to show text strings, or can it be used for options as well?

Thanks,

js.

**Comment by gziolo** [comment]
> BTW, is 'PluginPostStatusInfo' only to show text strings, or can it be used for options as well?

It isn't limited to text strings only, you can put any component you want there which fits visually.

Here is an example of the plugin which register Publish Panels: https://gist.github.com/gziolo/fd8141f2cde7fcb1b513c09eea45d27f. You should do something similar for `PluginPostStatusInfo` to make it work. What I shared is just for the component which renders the post status info row.

**Comment by gziolo** [comment]
If you have more questions please use WordPress.org Slack channel to find more help. This is not an issue with the Gutenberg itself, so closing this one. Thanks.
