### ISSUE TITLE
New Block Layouts

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#6993]
Since adding _templates_ last year we have been working on various features related to the ability to compose multiple blocks together. `InnerBlocks` has been our for a bit, with refinements to the design and interactions. The Child Block API will be released with 3.0, allowing block authors to create relationships between blocks, and so on.

Given this updates, the editor is already quite flexible in achieving some common layouts by combining pieces. With the addition of the [container block](https://github.com/WordPress/gutenberg/issues/4900), this would expand further. Yet, there's still room for another piece of the puzzle: creating some layout blocks that function as shortcuts for achieving common design patterns. These are not to be confused with templates — which apply to the whole page setup.

@melchoyce explored some in quick mockups: https://cloudup.com/cNXrAMW7FBY

The idea is we can create some of these as registered blocks, available under the "Layout" group, and it'd leverage _nested blocks_ to offer a ready-made unit. Creating this should also push us to refine template locking so that it can be applied at a group level, not only via template registration.

![image](https://user-images.githubusercontent.com/548849/40626777-138fd5b6-62bb-11e8-8b62-82cb0fd00e57.png)

**Comment by SuperGeniusZeb** [comment]
Other related issues:
- #4902
- #5351 (specifically the [Layout block mockups](https://github.com/WordPress/gutenberg/issues/5351#issuecomment-371885817))
- #5935
- #6048
- #6650 (relevant as layout blocks will almost always need to be responsive in one way or another)

**Comment by mtias** [comment]
We have one of these blocks implemented. Moving the rest as something to revisit for phase 2. cc @alexislloyd

**Comment by alexislloyd** [comment]
Thanks @mtias! I would also suggest that we refer to these as "complex blocks" (i.e. blocks containing multiple blocks to achieve a common pattern), to distinguish them from "simple blocks" (blocks that contain only one block) and from "templates" (which apply to the entire page layout).

**Comment by strarsis** [comment]
Also themes should be able to register a layout for their templates.
E.g. a theme template should have two columns, both with main content.
The editor should reflect this, similar to [Mesh](https://meshplugin.com/).

**Comment by aristath** [comment]
This is now possible using [Block Patterns](https://developer.wordpress.org/block-editor/developers/block-api/block-patterns/) so I'll go ahead and close this ticket. :+1:
