### ISSUE TITLE
Inserter Tweaks for Child Blocks

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#6998]
With **Child Blocks API** merged into master, there are a few extra improvements we can make. Currently, the relationship between a child block and its parent is not immediately evident in the inserter — the only visual change is that child blocks appear only when in context of the parent, and that they show first in the list.

One thing I'd like to explore is signaling which blocks have children assigned in the main inserter and then, once within the context of the parent, clearly list the available child blocks as a group.

@jasmussen did some design explorations on how this could work.

**1)** Blocks with children would show a subtle hint as a stack of cards:

![woo block 1](https://user-images.githubusercontent.com/548849/40654132-add693f8-633d-11e8-8e70-38f907956f80.png)

This would also work in tandem with the idea of letting block authors color-code their blocks.

**2)** Once a user is within the context of such a block, the available child blocks are listed at the top, and the parent block is provided as anchor:

![woo child blocks 1](https://user-images.githubusercontent.com/548849/40654474-bad8e500-633e-11e8-94b2-3fe1d45daf4f.png)

**Comment by jasmussen** [comment]
The pattern used here is inspired by the mockup work we did for inline blocks in https://github.com/WordPress/gutenberg/pull/5794#issuecomment-382684045, but takes it slightly further. Here's how the pattern above could look when applied to those:

![inline_blocks](https://user-images.githubusercontent.com/1204802/40654796-99b4184e-633f-11e8-8a2c-12c230d70277.png)

Worth noting that _inline blocks_ are not the same as _child blocks_, so you'd never see for example the Paragraph block as a "stacked blocks" just because it can have inline blocks inside. But there's no reason we can't use the same pattern.

**Comment by youknowriad** [comment]
How this would relate to allowing custom block categories? There's some overlap.

**Comment by mtias** [comment]
I don't think there's much overlap with categories. The main thing here is that Woo Product is a real block, not just a group of blocks — clicking on it will insert something, not just expand the contents.

**Comment by aduth** [comment]
>This would also work in tandem with the idea of letting block authors color-code their blocks.

Could this just be a property of the Plugin API to associate a brand color to the plugin (and use in UI as applicable)?

**Comment by mtias** [comment]
What if you have blocks but are otherwise not using the Plugin API at all?

**Comment by karmatosed** [comment]
Just wanted to add that I really like these as a solution, it seems clear and logical.

**Comment by aduth** [comment]
>What if you have blocks but are otherwise not using the Plugin API at all?

At the risk of opening a rabbit hole, maybe we need a more formalized relationship between a block and a registered plugin, instead of the namespace convention? Currently there's no way to associate a plugin which also registers blocks, except by its plugin name vs. block namespace, which aren't guaranteed to be equal. By formalized relationship, I could imagine either blocks as a property of a plugin registration object, or the return value of the registration being an object which contains various APIs:

```js
wp.plugins.registerPlugin( 'my-plugin', {
	// ...
	blockTypes: {
		'map': {
			// ...
		},
	},
} );
```

```js
var plugin = wp.plugins.registerPlugin( 'my-plugin', {
	// ...
} );

plugin.registerBlockType( 'map', {
	// ...
} );
```

**Comment by mtias** [comment]
Mmm, not sure that would be ideal. In my mind, most plugins would either register a block, or use the Plugin API to provide functionality in another way. We could think about extending that, but the ability for a block to specify a color should also be allowed in any case. Sounds easier to start there and see if we need a more formal relationship.

**Comment by jorgefilipecosta** [comment]
https://github.com/WordPress/gutenberg/pull/7003 was merged so I think we can close this issue. If there are further improvements required feel free to reopen.

**Comment by jorgefilipecosta** [comment]
> We just need to add the API for supplying a bg color to the block icon card.

Sorry, @mtias missed this one. Right now we set a class for each inserter item editor-block-list-item-[block-name] e.g:editor-block-list-item-acme-product or editor-block-list-item-gallery.
Maybe we can document a sample where these classes are used to change the design of an inserter button e.g: the color of the inserter. Do you think doing that would be a good solution?

**Comment by mtias** [comment]
Probably not, that seems a bit fragile — and won't scale to contexts like mobile apps. People would have to potentially overwrite multiple selectors for all the appearances of a block, and we won't be able to ensure consistency for users.

**Comment by jorgefilipecosta** [comment]
Ok, I'm reopening this issue as we will need to provide a special API.
My initial idea of a possible API is to use an inserterBgColor property in the block registration but I'm still thinking about what are the other possibilities we have.

**Comment by mtias** [comment]
I think we could something like:

```js
icon: [
    svg || dashicon-string,
    '#color-value',
]
```

If the property is not an array, we assume svg/dashicon-string.

**Comment by mtias** [comment]
`inserterBgColor` is too specific for the inserter.

**Comment by jorgefilipecosta** [comment]
Nice idea @mtias I will submit a PR with the implementation of it, so we can see how it looks.

**Comment by chrisvanpatten** [comment]
Would you also need to provide an icon color (for dashicons) to make sure there's sufficient contrast on the icon? Or is that something Gutenberg itself can handle?

**Comment by jorgefilipecosta** [comment]
@chrisvanpatten excellent question, Gutenberg itself can use https://github.com/bgrins/TinyColor mostReadable function to compute the best color for given background color according to the set we provided. But I'm not sure if we should do that or allow the user to configure both colors.
