### ISSUE TITLE
Automated Testing: Unskip tests blocked by Enzyme support of React 16.3

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#7005]
Previously: https://github.com/WordPress/gutenberg/pull/6527/files#r185974677

We currently skip tests which rely on `React.forwardRef` because they are not supported yet by Enzyme:

https://github.com/WordPress/gutenberg/blob/400f8fc685ce309c12ebcb33762c381594002025/components/button/test/index.js#L106-L118

This is tracked by the Enzyme project at https://github.com/airbnb/enzyme/issues/1604

Once the above issue is closed and Enzyme produces a new release introducing support for `React.forwardRef`, we should remove the workarounds introduced by #6527 .

__Open questions:__

- What else do we use from React 16.3 that isn't supported by Enzyme that will need to be updated?
- What components other than `Button` have tests which need to be updated?

**Comment by gziolo** [comment]
I just wanted to add that all tests that we skip currently are blocked by Enzyme's upgrade.

**Comment by gziolo** [comment]
This is how similar issues were fixed by @nerrad using `React.TestUtils`: #7835, #7834. We should go this route instead of waiting for `enzyme` upgrade.

**Comment by nerrad** [comment]
Ya although its a pain, the more you work `react-test-utils`, and `react-dom/test-utilities` the less of a hassle it becomes. Definitely more reliable.   It's kind of odd that the official react docs still suggest using enzyme.

**Comment by nerrad** [comment]
Also worth noting that under the hood enzyme uses the various react test utilities.

**Comment by nerrad** [comment]
The pulls I fixed skipped tests related to this were:

- #7837 
- #7835 
- #7834 

The pulls I converted away from enzyme (because they failed in #7557 are
- #7828 
- #7829 
- #7827 
- #7815 
- #7798 
- #7797 
- #7796 
- #7794 
- #7793 
- #7790 
- #7788 
- #7787 
- #7786 
- #7784 
- #7780 
- #7777 
- #7773 
- #7756 
- #7752

**Comment by aduth** [comment]
We no longer use Enzyme.
