### ISSUE TITLE
Registering styles should not use 'wp-editor-font' as dependency

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#7007]
Hello, 

If someone is not using the Noto font in the editor, and loads it own custom font, he may want to deregister `wp-editor-font` stylesheet. 

But doing so will break the editor because `wp-editor` has `wp-editor-font` in dependencies array. 

Would be cool to remove these dependencies, what do you think? Am I missing something? 
(It's not mandatory to load font before applying it in CSS)

Maybe a different approach will be taken when merging Gutenberg in the core? 

Also: 
is it necessary to load Gutenberg assets in every admin pages for now? 

Thanks!

**Comment by karmatosed** [comment]
I feel this isn't a design feedback question so for now removing that label and we can review.

**Comment by youknowriad** [comment]
> is it necessary to load Gutenberg assets in every admin pages for now?

Gutenberg don't load the styles in each admin pages, that's probably coming from a plugin adding Gutenberg styles as dependencies.

When it comes to the font, let's close this as a duplicate of #12611
