### ISSUE TITLE
Add additional formatting options to the Table block inspector sidebar

### ISSUE THREAD

**Issue by SymbolicallyMe** [WordPress/gutenberg#7008]
## The Issue:
Text within a table cell of the **Table** block is missing a few formatting options. Just like the **Paragraph** block, the **Table** block should be able to apply a font size, background and/or text color to each table cell.

## The Solution:
Add font size, background and text color options to the inspector sidebar.

<img width="277" alt="sidebar" src="https://user-images.githubusercontent.com/39569148/40684574-ac1c72fe-635f-11e8-82a9-d41ee05f5bf1.png">

**Comment by mtias** [comment]
Closing in favor of #6923.
