### ISSUE TITLE
Gutenberg InnerBlocks.Content return array

### ISSUE THREAD

**Issue by pavithraidl** [WordPress/gutenberg#7009]
**Problem I have at the movement**
I tried to create a custom column layout block.
<img width="1238" alt="screen shot 2018-05-30 at 10 24 24" src="https://user-images.githubusercontent.com/8181627/40688993-5767659e-63f4-11e8-8ec0-d07ba8a08926.png">

Using the right-hand side control buttons (red arrowed) I can control the layout(grid style) of my two columns. 

The only way to add any class to the `InnerBlocks`, the only way is to use the `name` key under layouts. 
` InnerBlocks,
                            { layouts: [
                                    { name: 'grid-item-right ' + '" style="width:' + rightColumnWidth + ';', label:'Column Right', wrap: 'right',  },
                                ]},`

But with the layout change, if I change the layout's `name` key, It will identify the that as a new `InnerBlocks` and my current content disappears. I have three buttons to change the layout. I call them x, y and z. If I click x and add some content and then if I want to change the layout and if I click the y button, my content disappears. But if I click x again that previous content appears back. 

It seems like I can't add any classes to the layout name field and change them dynamically.

So I created two divisions and place two `InnerBlocks` in to those divs. 
`'div',
                    { className: props.className + ' fl-grid col-md-12' },
                    el(
                        'div',
                        { className: props.className + ' fl-grid-left '+ leftColumn},
                        el(
                            InnerBlocks,
                            { layouts: [
                                    { name: 'grid-item-left ' , label:'Column Left', wrap: 'left',  },
                                ]},
                        ),
                    ),
                    el(
                        'div',
                        { className: props.className + ' fl-grid-right '+ rightColumn},
                        el(
                            InnerBlocks,
                            { layouts: [
                                    { name: 'grid-item-right ' , label:'Column Right', wrap: 'right',  },
                                ]},
                        ),
                    ),`

But in the save section, it returns both `InnerBlocks`'s content together when I use `InnerBlocks.content`. There's no way to get them separate to put back to separate divs. 

**Proposed solution**
Suggestion one: separate `InnerBlocks` layout classes and name. The developers will be able to add any classes to InnerBlocks and change them dynamically. 

Suggestion two: InnerBlocks.Content should have a way to identify separate layouts in the save section. ex: InnerBlocks.Content['grid-item-left'] ... something like that.

**Comment by chrisvanpatten** [comment]
Related: #6895

**Comment by youknowriad** [comment]
The layouts prop has been deprecated and remove. this issue is invalid now.
