### ISSUE TITLE
Remove reusable block actions in lieu of @wordpress/core-data methods

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#7011]
We should be able to remove `fetchReusableBlocks()`, `updateReusableBlocks()`, etc. and instead use the built-in `@wordpress/core-data` methods e.g. `getEntityRecord()` and `updateEntityRecord()`. 

This came up in https://github.com/WordPress/gutenberg/pull/6067 and again in https://github.com/WordPress/gutenberg/pull/6753#discussion_r190861884.

Blocked on https://github.com/WordPress/gutenberg/issues/7119.

**Comment by mtias** [comment]
Is this going to be part of the refactoring? https://github.com/WordPress/gutenberg/pull/7453

**Comment by noisysocks** [comment]
I plan on doing this after #7453 lands as the refactoring will make it a whole lot simpler.

**Comment by noisysocks** [comment]
Closing this as it is a subset of https://github.com/WordPress/gutenberg/issues/11124.
