### ISSUE TITLE
Documentation: Document missing methods for `data` module

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#7015]
When working on publishing `data` module to npm, we noticed that some methods aren't documented in the README file:

* `setPersistenceStorage`
* `withRehydration`
* `loadAndPersist`

We should fix it. In addition, we should add a note how to use them in node environment because by default they depend on `window.localStorage`. Example of how to setup it with `store` npm module: 
```js
import store from 'store';

setPersistenceStorage( store );
```

I haven't tested it, but in general, it should work as explained by @aduth:

> So we default to a broken (error-throwing) state for Node environments where this package is used?
> 
> It's probably a larger dependency than we'd want, but something like [Store.js](https://github.com/marcuswestin/store.js) is a good abstraction for this sort of thing.

**Comment by aduth** [comment]
Closing as invalid since these functions have since been deprecated and removed.

Alternative / equivalent `persistence` module is documented here:

https://github.com/WordPress/gutenberg/tree/master/packages/data/src/plugins/persistence
