### ISSUE TITLE
Linting: Warn when importing all of lodash

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#7019]
As mentioned in https://github.com/WordPress/gutenberg/pull/6996#issuecomment-393160461, we should avoid loading all of lodash and instead import the appropriate functions from it. That way we don't load all of lodash on the client when we only need certain pieces.

We should warn/error in eslint when we do `import _ from 'lodash';` and fix all instances of that in the existing code base.

**Comment by nerrad** [comment]
In triage there was consensus that this is unlikely to happen.  It can be revisited if there's instances of this happening.  See [this discussion in slack (requires signup)](https://wordpress.slack.com/archives/C02QB2JS7/p1555335977109100) for context.
