### ISSUE TITLE
Link improvements

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#702]
The current WordPress editor is arguably the best in the world for creating, managing and handling links. Let's make sure and port all the great stuff:

- [x] Set focus on link input field when clicking link 
- [ ] Search your old posts and pages in the input field
- [ ] Select text then paste link to make a link
- [ ] Port "Link options" button

**Comment by jasmussen** [comment]
Also came upon a few issues today:

- Make an empty link, then click a different block, then click back to the link, and theres a weird overlay on the link.
- There's an issue with the link boundary feature in headings in general.

**Comment by jasmussen** [comment]
Would be nice to also have a bigger link dialog box that also lets you search Google. Perhaps an expandable one.

**Comment by mtias** [comment]
Can we break this into specific tasks? It's harder to browse list views otherwise.

**Comment by jasmussen** [comment]
Closing in favor of individual tickets, #1040 and #1041. 

Decided against creating a separate ticket for "port link options button", as the only thing that feature offers is to let you open the link in a new tab. If this becomes necessary, seems like we can find a better UI for it, perhaps. For posterity, here's the behavior:

![link options](https://cloud.githubusercontent.com/assets/1204802/26826985/6f405b38-4abb-11e7-8ab5-0ef46d328921.gif)

**Comment by kristarella** [comment]
It would also be nice to have the Ctrl+K shortcut for adding a link.

**Comment by StaggerLeee** [comment]
Cannot copy/paste URL inside this field. Ctrl + V works.
Browser is Vivaldi, Chrome engine. In Chrome it works OK. 

Dont know if it is anything you are interessted about. Just to maybe check, so if solution is easy why not to implement it.
