### ISSUE TITLE
Backticks for code

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#703]
When you write a backtick (```) before and after text in the current WordPress editor, you make code. We should port this.

**Comment by iseulde** [comment]
Should we port all the shortcuts? Forgive me if there's already separate tickets. Might make sense as a whole though, technically, to add an API. Also, would love to work on this as I've done it for core. :D

**Comment by jasmussen** [comment]
> Should we port all the shortcuts? Forgive me if there's already separate tickets. Might make sense as a whole though, technically, to add an API. Also, would love to work on this as I've done it for core. :D

Yes! Port _all_ the good stuff. And you seem the perfect person to work on it. 

It's lower priority than some of the other issues, though, but once the milestone stuff is out of the way, definitely go for it!

**Comment by aduth** [comment]
Do you think it might be possible to use the same `wptextpattern` TinyMCE plugin verbatim?

**Comment by iseulde** [comment]
It should work in any TinyMCE instance, yes.

**Comment by iseulde** [comment]
I am hoping a bit to change the approach though.

**Comment by mtias** [comment]
Done in #1674.
