### ISSUE TITLE
[2.9.2] Convert to Blocks not properly converting successive Shortcodes

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#7030]
**Describe the bug**
On a Classic block with multiple successive Shortcodes, choose the option "Convert to Blocks." Not all the Shortcodes will convert.

**To Reproduce**
1. create a new page/post
2. add this content in a Classic block
[shortcodetest]
[shortcodetest]
[shortcodetest]
3. choose "Convert to Blocks"
4. BUG: It will not create all the Shortcode blocks

Different combinations of text with successive Shortcodes result in different behavior, but in most/all scenarios, at least one of multiple successive Shortcodes does not convert.

**Expected behavior**
Any combination of Shortcodes, even in succession, should convert to Shortcode blocks.

**Comment by danielbachhuber** [comment]
I've confirmed this bug:

![convertmulti](https://user-images.githubusercontent.com/36432/41038919-b2906a12-694c-11e8-9414-ff2cc3fd8053.gif)

In my testing, it's the last shortcode that isn't converted to a block.

**Comment by danielbachhuber** [comment]
I suspect this is going to be a more common issue than not, so elevating priority.

Related #3900 #4456

**Comment by danielbachhuber** [comment]
Interestingly, opening a post in the Classic Editor immediately wraps shortcodes with paragraph tags:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/36432/42479975-2c744850-8390-11e8-9238-1fe597790734.png">

<img width="668" alt="image" src="https://user-images.githubusercontent.com/36432/42479978-34ce8114-8390-11e8-94c3-9ba512327a72.png">

Related #3900
