### ISSUE TITLE
Add keyboard shortcut for changing block type

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#7034]
I see that we have a few keyboard shortcuts for some things already, such as Bold, Italic, Strikethrough, and Link ([ref](https://github.com/WordPress/gutenberg/blob/master/editor/components/rich-text/format-toolbar/index.js#L26-L51)). May we also have a keyboard shortcut for changing a block type?

![screen shot 2018-05-30 at wed may 30 4 32 29 pm](https://user-images.githubusercontent.com/1119271/40751161-43c4ed6c-6427-11e8-85ed-ce2ea7e5d9ad.png)
<sup>Tested with WordPress 4.9.6 Jetpack 6.1.1 Gutenberg 2.9.2 using Firefox 60.0.1 on macOS 10.13.4.</sup>

**Comment by danielbachhuber** [comment]
@designsimply Aren't there multiple possible block types?

<img width="430" alt="image" src="https://user-images.githubusercontent.com/36432/41983614-873ebaec-79e3-11e8-8d18-0dcef289dcc8.png">

How would a keyboard shortcut work in this case?

**Comment by mtias** [comment]
Yes, the keyboard flow should be just to open the transform panel.

**Comment by designsimply** [comment]
> How would a keyboard shortcut work in this case?

It would open that view!

> Yes, the keyboard flow should be just to open the transform panel.

Apologies, how do you use the keyboard to open a transform panel?

Note: it's possible I misunderstood and you are closing this as wontfix. That's fine! Just confirming. 🙂
