### ISSUE TITLE
DOMRect doesn't work in some browsers

### ISSUE THREAD

**Issue by SymbolicallyMe** [WordPress/gutenberg#7036]
**Describe the bug**
The function/constructor `DOMRect`, used in [dom.js](https://github.com/WordPress/gutenberg/blob/master/packages/dom/src/dom.js) (line 160), does not work in Chrome 56, IE 11 and Microsoft Edge, but works in FireFox and Safari.
<img width="451" alt="screen shot 2018-05-30 at 8 08 04 pm" src="https://user-images.githubusercontent.com/39569148/40754065-3a805fd4-6445-11e8-978d-b06957405f4d.png">

**To Reproduce**
1. Add the **Table** block
2. Open the command line
3. Click on an empty table cell (you should get an error in the console for the browsers mentioned above).

**Expected behavior**
When clicking on an empty table cell within the **Table** block, and error should not occur.

**Possible Solution**
Since `DOMRect` works only in some browsers, a polyfill or mock DOMRect function should be created or used in place of it. TinyMCE provides it's own function to create Rectangles without issue.
```JS
import tinymce from 'tinymce';
var rectangle = tinymce.geom.Rect.create( x, y, width, height );
```

**Screenshots**
<img width="392" alt="screen shot 2018-05-30 at 10 31 28 am" src="https://user-images.githubusercontent.com/39569148/40753759-c90ae618-6443-11e8-895f-fbd41ffe1261.png">

**Relate Issues**
 #6666

**Comment by danielbachhuber** [comment]
Looks like we've started progress on this, but are currently blocked: https://github.com/WordPress/gutenberg/pull/6666#issuecomment-400718184

**Comment by brandonpayton** [comment]
I'll take a look at unblocking #6666 next. We submitted a DOMRect polyfill to a polyfill repository we use, but we can create a place to maintain and use them locally until they're successfully contributed to a polyfill library.

**Comment by brandonpayton** [comment]
We're no longer using the DOMRect constructor in [the latest `@wordpress/dom` package](https://github.com/WordPress/gutenberg/blob/caaf20474e7e45a6e6669f3fafb3d57edf61662e/packages/dom/src/dom.js). Let's close for now and revisit if we resume use of `new DOMRect()`.
