### ISSUE TITLE
Colour selection panels in sidebar constantly close

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7042]
**Describe the bug**
When changing the the Background and/or Text colour for a Paragraph block, I have to click either 'Background Color' and/or 'Text Color' to reveal the colour selectors. When I click on another Paragraph Block I then have to click on 'Background Color' and/or 'Text Color' again, to reveal the colour selectors. This is really frustrating and a makes block editing really slow.

If I open the Background Color and/or Text Color panel, it should remain open until I either close it myself or update the page.

**To Reproduce**
1. Click on a Paragraph Block
2. Change Background and/or Text Colour
3. Click on another Paragraph block
4. Change Background and/or Text Colour

**Expected behavior**
After clicking a panel such as Background Color, it should remain open until I close it myself or until the page is saved/updated, even when moving between different blocks.

_macOS 10.12.1 (16B2659)
Firefox Quantum 60.0.1 (64-bit)
Gutenberg 2.9.2_

**Comment by danielbachhuber** [comment]
Thanks for the report, @maddisondesigns. Flagging this as `Needs Design Feedback` to see if it's a behavior we want to implement.

**Comment by karmatosed** [comment]
As we have planned to merge these sections in #6255, lets close this for now as both would be open if combined.
