### ISSUE TITLE
I need one definitive clarification

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#7048]
Will version 5.0 (with Gutenberg merged) be forced as automatic core upgrade ?
Do I need any code line inside wp-config.php file, to prevent Gutenberg WP core upgrade be forced ?

Statements I found on Google are somehow versatile, so one clear answer is needed. Thank you.

As much I appreciate your work and GPL licence, I sincerely have no lust to deal with people who are not my close friends, and explain to them all benefits of Gutenberg, fix all possible problems, lose much time, and all of it for free. Rather I stop updating their websites, minor and major.

**Comment by Soean** [comment]
By default major updates like 5.0 are not automatic, just minor updates like 4.9.6. So Gutenberg will not come via auto update.
If you want to, you can change it via the constants and filters: https://codex.wordpress.org/Configuring_Automatic_Background_Updates

**Comment by StaggerLeee** [comment]
Thank you.

Just one more question before I close issue.
Will it be possible to downgrade core version after testing Gutenberg with this plugin ?
https://wordpress.org/plugins/wp-downgrade/

**Comment by Soean** [comment]
I wouldn't recommend to downgrade a core version because of Gutenberg. You can disable the  Gutenberg editor via this plugin: https://wordpress.org/plugins/classic-editor/

If you want to test Gutenberg, you can install the Gutenberg plugin before you upgrade to 5.0.

**Comment by StaggerLeee** [comment]
I meant after showing Gutenberg to clients. And after discussing in lenght with complete strangers about it, losing lot of time, all for free, and seeing a e-mail message: "I want my old admin interface back."

Have no more question, thank you.
