### ISSUE TITLE
Mobile: Show mover in block-toolbar on mobile

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#705]
We need to surface the controls for up, down, trash and advanced on mobile. Let's also surface them on wide images. 

Here's how it looks on desktop now:

![block ui desktop](https://user-images.githubusercontent.com/1204802/27789811-29a82644-5fee-11e7-8775-857d9b0d3110.png)

On "wide" images we move the controls above the image. Let's do the same for the mover:

![block ui wide](https://user-images.githubusercontent.com/1204802/27789828-3885a7e0-5fee-11e7-9d75-6581ac6b73ff.png)

On mobile, let's try a new interface. Let's have an ellipsis on the right of the selected block:

![block ui mobile collapsed](https://user-images.githubusercontent.com/1204802/27789968-d388599a-5fee-11e7-93c6-734d27445187.png)

When you click this ellipsis, a new toolbar expands and replaces the old one:

![block ui mobile expanded](https://user-images.githubusercontent.com/1204802/27789974-d6ade1da-5fee-11e7-9e52-e7f693a525da.png)

We can do this with simple responsive CSS. That is, we always have the mover, trash and cog present in the above-the-block toolbar, and simply hide these on desktop breakpoints, show them on mobile. I've checked the accessibility implications with @afercia, and so long as the controls are `display: none;` when they aren't used, they aren't announced by screenreaders or show up in the tab stack. On mobile, there is no tabbing, so the requirements here are different.

[Older mockup can be seen here](https://cloud.githubusercontent.com/assets/1204802/25796649/9eae74f6-33da-11e7-879a-08733e414ec5.png).

**Comment by jasmussen** [comment]
We should prioritize this one. 

In case there isn't room for up/down arrows in the toolbar, we might want to address this one in conjunction with #706.

**Comment by jasmussen** [comment]
I updated the screenshots in this ticket with a new proposal, that should be easier to implement yet accomplish the same.

**Comment by afercia** [comment]
I'd just recommend a meaningful `aria-label` for the ellipsis button and an `aria-expanded` attribute to give users some feedback when the press the ellipsis button.
