### ISSUE TITLE
Simplify the Inserter accessibility implementation

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#7052]
After #6636 the Inserter is now using collapsible panels (accordions). As mentioned in https://github.com/WordPress/gutenberg/pull/6168#issuecomment-387386979 this allows also to re-think and simplify the accessibility part.

Previously, each category group in the inserter had the semantic of an ARIA menu with menuitems. Also, navigation with arrow keys was implemented, as that's typical for ARIA menus. In fact, in its initial versions, the Inserter design and interaction were closer to the one of a menu. For some history, see below the Inserter in Gutenberg 1.1.0, 1.4.0, and 1.7.0.

![screen shot 2018-05-31 at 14 02 09](https://user-images.githubusercontent.com/1682452/40781863-cde6ee62-64dd-11e8-869b-2810553061d0.png)

The Inserter has now a completely different interaction model. I'd say menu and menuitems don't make much sense any longer. I'd also consider to remove arrows navigation and greatly simplify the interaction and code. Let's just let users Tab through the available blocks in the accordions. I'd also propose to remove the active item tracking, as that made sense to allow quick Tab navigation through the categories. Now that accordions can be collapsed or expanded by users, that appears to be a bit overkill.

The current accordions work pretty well, they're simple to use and understand also when using assistive technologies. Seems to me there's really no need to overcomplicate.

**Comment by anevins12** [comment]
> Now that accordions can be collapsed or expanded by users, that appears to be a bit overkill.
Yes and may cause more errors because the keyboard shortcuts are not predictable for the model being used - conveyed via the Role.
