### ISSUE TITLE
Z-index issue using Classic block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#7061]
Selecting a link in the classic block and having it active then selecting another link in the left sidebar it looked like this:

![screen shot 2018-05-31 at 18 37 33](https://user-images.githubusercontent.com/5323259/40795551-b05f6796-6502-11e8-8510-65198a4cf7df.png)

**Comment by tofumatt** [comment]
@brandonpayton and I took at look at this today; oddly even after we added:

```css
#adminmenu .wp-submenu {
  z-index: 99991;
}
```

it still didn't work–though that `z-index` should put it in front of the popup.

It seems that the popup with either always be above both the menu *and* submenu or below them both. We were a bit stumped, but it seems in core the submenu should have a higher `z-index` so we can adjust for something being above the main menu (which we want in this case as it won't fully overlap) but *below* the submenus.

**Comment by paaljoachim** [comment]
I just tested and I can see that the z-index has been taken care of.
