### ISSUE TITLE
filemtime() called on asset that does not exist

### ISSUE THREAD

**Issue by tn3rb** [WordPress/gutenberg#7064]
@brandonpayton

**Describe the bug**
This recent commit:
https://github.com/WordPress/gutenberg/commit/6728906116c12b5865e66b32b634d2b300136334#diff-620130744b6b73b822a3df609671d930
includes the following bit of code on line 450 of `lib/client-assets.php`:

```php
filemtime( gutenberg_dir_path() . 'build/core-blocks/theme.css' )
```

but that file does not exist after running `npm run build` nor after `npm run dev`

so visiting any admin page results in the following error appearing:

```
Warning: filemtime(): stat failed for /wordpress-default/public_html/wp-content/plugins/gutenberg/build/core-blocks/theme.css
in /wordpress-default/public_html/wp-content/plugins/gutenberg/lib/client-assets.php on line 450
```

This is using VVV on Windows 10

**To Reproduce**
1. checkout latest master
2. run `npm install` followed by either `npm run build` or `npm run dev`
3. visit any admin page 

**Expected behavior**
either the 'build/core-blocks/theme.css' should exist, or a `file_exists()` check should be performed before registering that asset

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Version 1709 Build 16299.431
 - Browser FireFox Quantum 
 - Version 60.0.1

**Additional context**
- latest master

**Comment by aduth** [comment]
Thinking since this will warn for all users of the plugin, should be resolved before 3.0.

**Comment by youknowriad** [comment]
This file is being generated properly for me. Not certain why you're not seeing it

**Comment by brandonpayton** [comment]
I see the file properly generated in macOS, but when I test in Windows 10, `build/core-blocks/theme.css` is missing. I'll take a look at this.
