### ISSUE TITLE
UI: Separate out drafting, saving, publishing actions

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#707]
We'll soon be able to save and publish posts! #594!

Once that's in, we should consider splitting the flow up, so the publish button doesn't do it all. 

**Saving & Publishing**

![saving publishing](https://cloud.githubusercontent.com/assets/1204802/26669945/0c376270-46b0-11e7-9ce1-8db240d592a2.png)

The indicator on the left shows the saved state. It autosaves the post, like it always has, and indicates when changes are saved. 

When there are unsaved changes, you can either wait for the auto-save to kick in, or you can click "Save", as a blue button.

The publish button has two roles:

- Publishing the post the first time
- Updating a published post

In addition to this, it can show a "working" animation when content is being published or updated. 

**Edit:** I updated the mockup to remove the dropdown button, as that is unrelated to this ticket. See also https://github.com/WordPress/gutenberg/issues/707#issuecomment-304934065.

**Comment by jasmussen** [comment]
Per discussion in https://github.com/WordPress/gutenberg/issues/708#issuecomment-302451611 we should also have a "Schedule" state for the button.

**Comment by youknowriad** [comment]
So the button text could be either "Publish", "Update" or "Schedule".

Currently, we also have "Saving", "Updating", "Saved", "Updated", "Save failed", "Update failed". We should drop this status from the button text itself, right!?

**Comment by jasmussen** [comment]
> Currently, we also have "Saving", "Updating", "Saved", "Updated", "Save failed", "Update failed". We should drop this status from the button text itself, right!?

Right. Saving and Updating should probably both be the same, "Saving..." and sit in the area on the left

"Published", "Save failed", "Update failed", "Updated" is something that might actually require a notice, like we have in Calypso. Maybe I need to open a new ticket for notices with mockups. But we don't want them in the button, for sure.

**Comment by nylen** [comment]
Does this design require two clicks (one to open the dropdown, and the other to click the "real" button) to update a post?  That seems undesirable to me.

**Comment by jasmussen** [comment]
> Does this design require two clicks (one to open the dropdown, and the other to click the "real" button) to update a post? That seems undesirable to me.

The dropdown isn't part of this ticket, sorry, mockup is misleading. But yes, #708, suggests an extra click. Note: that extra click is for these actions:

- Publishing
- Scheduling a post to be published
- Updating a published post

It is not for _saving a draft_ (which is done on the left side in this ticket), or for picking the schedule date, which is done in the sidebar, or could be done in the dropdown itself. 

There are a couple of benefits to this:

a) it puts a barrier between you and the published post, an implicit "yes, I'm sure I want to publish this post". It's a replacement for the "confirm publish" alert, which has been requested a number of times on WordPress.com, and is also being discussed in https://core.trac.wordpress.org/ticket/39841
b) the dropdown itself is a chance to show the most important metadata, at the very last minute —  like "did you remember to tag?"
c) it allows us an affordance to let you add that metadata without actually using the sidebar, essentially letting users who don't need the vast majority of metaboxes never open the sidebar after dismissing it the first time

I'm a believer in this design. I think it's good for everyone, and so long as the _save_ action isn't buried there, it's desired friction.

That being said, it is a separate ticket from this one, because it is not as important to get to. Or to put it differently: if we don't get to it at all, that's okay too.

**Comment by youknowriad** [comment]
closed by #945

**Comment by jasmussen** [comment]
There seems to have been a regression here, as discovered in #1295. I can no longer get the "Saving..." state to invoke. Is this tracked somewhere else?
