### ISSUE TITLE
Add search bar and filters to search for settings in inspector

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#7070]
## Having lots of settings is necessary for a full page builder experience
When Gutenberg is merged into WordPress core, I do not expect it to have every possible styling or formatting option available for the core blocks.

I do however, fully expect plugins to exist that add all those options. If you take a look at a page builder plugin like Divi, for example, you will see that the modules of its builder are filled to the brim with settings and options, which many people (including myself) find very useful. Gutenberg can simply not replace something like Divi unless it can be extended to provide all those options. There will definitely be plugins that add gradient background, border, font, hover state, and any other type of option you can think of to every core block.

## The issue that users of those plugins will face
The more options there are, the more there are to scroll through. Ideally, you would want some way to filter through the available options to only show the ones you are interested in. This may not be immediately necessary for core WordPress, but it will almost certainly be needed in situations where blocks have been extended or added with tons of options.

## A solution based on an existing page builder
Using Divi as an example again, you can search for specific settings for a module using a search bar, and recently the ability to only show settings with a non-default value has been added as well:

https://www.elegantthemes.com/blog/theme-releases/divi-feature-update-huge-design-efficiency-improvements-now-available

https://www.youtube.com/watch?v=3X39sy733sg

## Some other notes
Thanks to the block-based nature of Gutenberg, many blocks will have much fewer options than their counterpart in page builder plugins, since many things would be comprised of multiple nested blocks, allowing settings to be more focused. That said, I think a search bar and the ability to only show modified settings would still be very useful.

**Comment by danielbachhuber** [comment]
Hi @SuperGeniusZeb,

Thanks for the suggestion! I've filed this away in the [Ideas project](https://github.com/WordPress/gutenberg/projects/8) for future consideration. At this point in the Gutenberg development cycle, we're focusing on finishing the remaining features and then switching to bug fixing / polish.
