### ISSUE TITLE
NUX: Fix DotTip positioning

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#7071]
The first `DotTip` that appears in the NUX (https://github.com/WordPress/gutenberg/pull/6631) is supposed to appear next to the inserter toggle. Instead, it appears above it.

The problem is that, during the initial page load, the popover position is calculated while `PostTitle` is hidden because `PostTypeSupportCheck` is waiting for the `getPostType` resolver to complete:

<img width="1112" alt="screen shot 2018-05-31 at 15 25 08" src="https://user-images.githubusercontent.com/612155/40763216-6e1f2828-64e7-11e8-89a6-81ff2363b67f.png">

When the resolver eventually finishes, `PostTitle` appears and the popover is now in the wrong position:

<img width="1111" alt="screen shot 2018-05-31 at 15 30 27" src="https://user-images.githubusercontent.com/612155/40763256-a3ad744a-64e7-11e8-8646-49bbdb6cd75b.png">

For now we are working around the issue by [forcing the popover to reposition itself on the next frame](https://github.com/WordPress/gutenberg/pull/6631#discussion_r191712101).

We need to fix this properly, though. Some ideas:

- Look into why `getPostType` does not resolve immediately, since all of the data should be preloaded on initial page load.
- We could have Popover use `MutationObserver` to watch for changes to the DOM and then reposition. This would be quite expensive though since we'd have to trigger a recalculation whenever **any** of the anchor's parents changes. We could mitigate the performance penalty by throttling the recalculations and/or making it opt-in (e.g. so that only the first `DotTip` does this).

**Comment by noisysocks** [comment]
> Look into why getPostType does not resolve immediately, since all of the data should be preloaded on initial page load.

I spent a little time looking into this and, although the data is preloaded, the `PostTypeSupportCheck` component re-renders each time we dispatch an action while fulfilling the resolver / iterating through the async iterator:

<img width="696" alt="screen shot 2018-06-07 at 17 01 37" src="https://user-images.githubusercontent.com/612155/41083658-112299b4-6a75-11e8-8bbf-f2be000e26e8.png">

Our `yield` and `await` calls must give React a chance to render the rest of the component tree which is what causes the issue.

I'm not sure what the best way forward is. Any ideas, @youknowriad? 

Perhaps instead of preloading data by storing it in `_wpAPIDataPreload` we can instead build the initial `core-data` Redux state on the server and then pass that into `createStore`.

**Comment by youknowriad** [comment]
> Perhaps instead of preloading data by storing it in _wpAPIDataPreload we can instead build the initial core-data Redux state on the server and then pass that into createStore.

While this is a neat idea globally, I don't want to add a lot of complexity just to fix this specific issue. I think I'm fine with the current workaround. Maybe a small improvement could be to propose an official API in Popover to refresh the position. Something like `popover.refresh()`.

Otherwise, I'm fine closing this issue.

**Comment by noisysocks** [comment]
👍 sounds like a good plan. Thanks for the input.
