### ISSUE TITLE
Autosave has a blank title

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/gutenberg#7078]
### Description

When creating an initial autosave for published posts, a blank title is stored. If the user restores this autosave, the post title will be blank.

Follow up to https://github.com/WordPress/gutenberg/pull/6257.

### Steps to reproduce:

1. Create a post and publish it.
2. Change the content of the post and wait 10 seconds for the autosave to fire.
3. Check the autosave REST request - note that the title is missing in the request. Check the database and note the autosave title is blank in the database.
4. The title will continue to not be sent & stored as blank/empty _until it is modified_.

### Expected Behavior:

The title should be sent with each autosave request, regardless of if it has been modified.

### Screenshots:

Autosave lacking title:
![](https://cl.ly/3a3B2h0u2c1b/download/[967184d1f11dfc401ceb44abc430f029]_Image%202018-06-01%20at%209.31.42%20AM.png)

Database after blank save:
![](https://cl.ly/0X042N3A1K2Y/download/Image%202018-06-01%20at%209.19.24%20AM.png)

### Tested on
 - OS: Mac
 - Browser Chrome & Firefox 
 - Version: latest
 
cc: @aduth @danielbachhuber

**Comment by aduth** [comment]
Related Slack conversation: https://wordpress.slack.com/archives/C02QB2JS7/p1527860463000600

**Comment by adamsilverstein** [comment]
This should be fixed by https://github.com/WordPress/gutenberg/pull/7092.
