### ISSUE TITLE
Drag and drop sometimes hangs

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#7081]
**Describe the bug**

I don't have exact steps to reproduces, maybe others have seen this bug as well. Sometimes when I drag a block and drop it (maybe a specific location triggers it), the block just continues floating around.

**Expected behavior**

It should move to a place it the editor.

**Screenshots**

<img width="773" alt="screen shot 2018-06-01 at 15 50 52" src="https://user-images.githubusercontent.com/4710635/40844362-ff2c8dfc-65b3-11e8-8a78-f61a970ca509.png">

Here I dropped the block. It's still transparent and not in place.

<img width="749" alt="screen shot 2018-06-01 at 15 51 05" src="https://user-images.githubusercontent.com/4710635/40844385-105c7e66-65b4-11e8-8278-11a2c5872bb2.png">

Here I clicked in the block underneath. The toolbar is transparent too.

<img width="749" alt="screen shot 2018-06-01 at 15 51 27" src="https://user-images.githubusercontent.com/4710635/40844418-295c8e06-65b4-11e8-8efe-8ec9f313eca3.png">

When I scroll, the block stick on the viewport.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 66.0.3359.139 (Official Build) (64-bit)

**Comment by braders** [comment]
I think this is a duplicate of #6145

**Comment by iseulde** [comment]
Thanks!
