### ISSUE TITLE
wp_register_script doesn't work in wp_enqueue_scripts

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#7084]
This doesn't work:
```
function slug_gutenberg_scripts() {
	wp_register_script( 'gutenberg-xxx', plugins_url( 'js/gutenberg-xxx.js', __FILE__ ), array( 'wp-blocks', 'wp-element' ) );

	$xxx = array(
		'categories' => get_terms(array(
			'taxonomy' => 'custom_post_type_category',
			'hide_empty' => false,
		))
	);
	wp_localize_script( 'gutenberg-xxx', 'gutenbergXxx', $xxx );
}
add_action( 'wp_enqueue_scripts', 'slug_gutenberg_scripts' );

function slug_gutenberg_blocks() {
	register_block_type( 'slug/xxx', array(
		'script' => 'gutenberg-xxx',
	) );
}
add_action( 'init', 'slug_gutenberg_blocks' );
```

This doesn't work:
```
function slug_gutenberg_blocks() {
	wp_register_script( 'gutenberg-xxx', plugins_url( 'js/gutenberg-xxx.js', __FILE__ ), array( 'wp-blocks', 'wp-element' ) );

	$xxx = array(
		'categories' => get_terms(array(
			'taxonomy' => 'custom_post_type_category',
			'hide_empty' => false,
		))
	);
	wp_localize_script( 'gutenberg-xxx', 'gutenbergXxx', $xxx );

	register_block_type( 'slug/xxx', array(
		'script' => 'gutenberg-xxx',
	) );
}
add_action( 'init', 'slug_gutenberg_blocks' );
```

Reason: `var gutenbergXxx = {"categories":{"errors":{"invalid_taxonomy":["Invalid taxonomy."]},"error_data":[]}};`

Is the only option to make it work to use `add_action( 'init', 'slug_gutenberg_blocks', 11 );`?

Expected: Being able to enqueue scripts in regular `wp_enqueue_scripts` to have access to custom post types etc.

**Comment by manake** [comment]
Yes, that's correct.

A plugin has `add_action( 'init', 'slug_gutenberg_blocks' );` and a theme which registers a post type has `add_action( 'init', 'register_that_post_type' );`.

While I can use 11 priority to fix this, shouldn't it be possible to use `wp_enqueue_scripts` hook to register scripts? This hook happens a lot later after `init` and it would offer access to whatever is missing in `init`.

I don't know if this is a bug but it was unexpected by me that `wp_enqueue_scripts` did not work.

**Comment by danielbachhuber** [comment]
@manake Were you able to track a resolution for this down? If not, can you share a fully-functional (not sample) code snippet that reproduces the issue?

**Comment by manake** [comment]
You already have the full code. You only don't have a `register_post_type` call but you can register it yourself like this:

1. What I have in the first post was in a plugin.
2. I was registering a post type in another plugin (or theme) with `10` priority `init` hook.
3. It just happens that when both have `10` priority then there's a chance that the post type won't be available yet and my `get_terms` will fail (see first post).
4. Hence I tried to use `wp_enqueue_scripts` to definitely have post types available. But that didn't work.
5. So I was forced to use `add_action( 'init', 'slug_gutenberg_blocks', 11 );` to solve this.

Again: I don't know if this is a bug. If I can't use `wp_enqueue_scripts` to register my Gutenberg scripts then I consider this to be a bug for now.

The documentation uses `init` hook for `wp_register_script`. Are you requiring `register_block_type` scripts to be in `init`?

https://wordpress.org/gutenberg/handbook/blocks/writing-your-first-block-type/

**Comment by designsimply** [comment]
@manake since it has been a few months since this issue was started, may I ask if you're still having trouble and if the code examples are still good? If yes, I will see what I can do to help test and will get additional help with that if I need it. Thanks so much!

**Comment by youknowriad** [comment]
Closing as stale, let's reopen if there's are reproducible steps/actionable items.
