### ISSUE TITLE
Server side render encodes some attributes incorrectly

### ISSUE THREAD

**Issue by timothyjensen** [WordPress/gutenberg#7086]
I'm running into a situation where my attributes are being returned in an unexpected format.  For example, an array of Post IDs is converted to an array that contains one comma separated string.

Expected:
```php
$postIds = [
   1,2,3
];
```

Observed:
```php
$postIds = [
   '1,2,3'
];
```

Another example is an array of objects is converted to `[object Object],[object Object]`.  Both cases are problematic because the data are inconsistent between the post editor and front end.  Having to account for both formats increases the chances of buggy code.

I have narrowed the problem down to `getQueryUrlFromObject`, though I can't offer a solution. https://github.com/WordPress/gutenberg/blob/7066905fe907bb8b160d1373a5c5ec3220b5eec0/components/server-side-render/index.js#L68-L74

**Additional context**
- Gutenberg v2.9.2

**Comment by chrisvanpatten** [comment]
_Additional_ additional context: this is happening when passing attributes with array values to the `<ServerSideRender />` component. Just seems like the process of URL-encoding the attributes for the API request might need to be refined.

**Comment by brianpiccione** [comment]
Whoa I've been tearing my hair out all day trying to get this to work! Thought it was just me. Would it be possible to change the call to the server change to a POST?

**Comment by brianpiccione** [comment]
I've been working through this for a while and found that @miina was registering the attributes in the `register_block_type` php function see [here](https://github.com/WordPress/gutenberg/pull/5495/files/128513c84118c9bbaa5d1c33346d244e743cee43#diff-f17015086c18df1952e3505b197491fa):

```
register_block_type( 'core/archives', array(
	'attributes'      => array(
		'showPostCounts'    => array(
			'type'    => 'boolean',
			'default' => false,
		),
		'displayAsDropdown' => array(
			'type'    => 'boolean',
			'default' => false,
		),
		'align'             => array(
			'type'    => 'string',
			'default' => 'none',
		),
	),
	'render_callback' => 'render_block_core_archives',
) );
```

After adding this in my php file (and also making sure the attributes were in the block's js file) booleans worked fine. I haven't tried an array @timothyjensen but hopefully this helps you make some progress!

**Comment by chrisvanpatten** [comment]
@brianpiccione I think normal types, like `boolean` and `string`, are okay. It only becomes an issue when trying to register `array` or `object` type attributes; they aren't always urlencoded correctly.

**Comment by brianpiccione** [comment]
Gotcha, thanks Chris. It'd be good to add this requirement (registering the atts in PHP) to the docs. I went down a number of rabbit holes to find this! Let me know if I can help at all

**Comment by chrisvanpatten** [comment]
One idea for this would be to use a JS equivalent of PHP's http_build_query, which is capable of transforming complex arrays/objects into a query string.

Such as: https://github.com/vladzadvorny/http-build-query
