### ISSUE TITLE
GET wp/v2/blocks?per_page=-1 fires each time a new paragraph is created

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#7088]
![blocks](https://user-images.githubusercontent.com/36432/40855019-15185b36-6588-11e8-8f96-659fc2833d4a.gif)

This seems too frequent.

**Comment by mcsf** [comment]
@danielbachhuber, is this fixed by #7077?

**Comment by danielbachhuber** [comment]
> is this fixed by #7077?

Yep, it does appear to be fixed in #7077
