### ISSUE TITLE
getWPAdminURL assumes you are in wp-admin

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#7095]
The true bug is when using Gutenberg out of the /wp-admin/ , for example as a front-end editor within P2 theme and the user selects "Move to Trash" the TRASH_POST_SUCCESS effect redirects the browser location to"

```
window.location.href = getWPAdminURL( 'edit.php', { ... } )
```

However, `getWPAdminURL()` does not actually get the /wp-admin/ URL, it only adds query parameters to the page passed in, which works if the editor is already in /wp-admin/ but not if it elsewhere.

**To Reproduce**

See `getWPAdminURL` function in `editor/utils/url.js` does not return the URL of a wp-admin page

**Expected behavior**

The function should return a full relative link to /wp-admin/

**Comment by mcsf** [comment]
@danielbachhuber: I'm not necessarily objecting, but wanting to understand: why the _Back Compat_ label? Seems like this only affects use cases where we'd want to use Gutenberg outside of WP-Admin, and I'd interpret anything non-WP-Admin to fall outside of the domain of backward compatibility. No?

Full disclaimer: my gut says this is not needed for 5.0 and we should close it for now.

**Comment by danielbachhuber** [comment]
@mcsf `admin_url()` is filterable. I think #7096 would be sufficient though.

**Comment by danielbachhuber** [comment]
> I think #7096 would be sufficient though.

Alternatively, we can close this issue until it comes up again. I consider it relatively minor.

**Comment by mcsf** [comment]
> Alternatively, we can close this issue until it comes up again. I consider it relatively minor.

Cool, I agree.
