### ISSUE TITLE
Change 33.33333% to 1fr for .wp-block-columns.has-3-columns

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#7101]
Before:
```
.wp-block-columns.has-3-columns {
    grid-auto-columns: 33.33333%;
}
```

After:
```
.wp-block-columns.has-3-columns {
    grid-auto-columns: 1fr;
}
```

Without this change `grid-column-gap: 1234px;` doesn't work like expected when inserted in style.css of a theme.

**Comment by ocean90** [comment]
This was also mentioned in https://github.com/WordPress/gutenberg/issues/5351#issuecomment-371623719.

**Comment by manake** [comment]
I noticed this:

1. Just doing `grid-template-columns: 2fr 1fr;` doesn't work well when the content is very wide.
2. Something else has to be used like `grid-template-columns: minmax(0, 2fr) minmax(0, 1fr);`.

**Comment by mtias** [comment]
We are not using grid anymore for the Columns block.
