### ISSUE TITLE
Can WordPress 5.0 have a deadline?

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#7107]
There is no information about WordPress 5.0 release date anywhere:

- https://make.wordpress.org/core/5-0/
- https://wordpress.org/about/roadmap/

It's also hard to estimate where Gutenberg is now, how much more work is required, how fast the work is progressing?

Should we expect it in June? July? August? September? October?

My main concern (and the reason why I'm asking this question) is this:

Some features like `InnerBlocks` or `Columns` or `Section` don't exist or don't work like they should (`Columns` for example should be probably split into `Columns` and `Layout` blocks like already suggested elsewhere while `InnerBlocks` needs better documentation to be usable) and I'd like to use them already but there is no progress regarding these features in the past 60 days.

There is an ongoing discussion regarding such features and it's hard to estimate when some decisions will be made.

**Comment by sylvaincordiere** [comment]
> Should we expect it in June? July? August? September? October?

Or maybe later
The 4.9.7 is planned to be released end of july or early august
https://make.wordpress.org/core/tag/4-9-7/
> No pressing need for quick 4.9.7 release, so aiming for ~6-8 week release cycle for 4.9.7

**Comment by Soean** [comment]
Hey,
the release of 5.0 is far away. There is no official date for 5.0, it comes when Gutenberg is ready. If you see the milestones of the merge proposal https://github.com/WordPress/gutenberg/milestones there is a lot to be done. If Gutenberg is merged into core, then there is a long beta and release candidate phase of 5.0.

(**My personal expectation** January or February 2019)

**Comment by danielbachhuber** [comment]
Hi @manake,

I don't expect there are any formal announcements now, but I'd watch Matt's talk at WordCamp Europe for the official details on the state of Gutenberg.

**Comment by salcan** [comment]
No news on the 5.0 launch date?

**Comment by danielbachhuber** [comment]
> No news on the 5.0 launch date?

The formal launch date is still to be determined. Matt [presented a roadmap](https://wptavern.com/matt-mullenweg-unveils-gutenberg-roadmap-at-wceu-wordpress-agencies-and-product-developers-sprint-to-prepare) at WCEU that's worth reviewing.

**Comment by Tajwebdeveloper** [comment]
There are too much bugs and improvements needed... also there are several plugins which wont work without classic editor.. so according to me it'll take at least 6-12 months from now.

**Comment by pagelab** [comment]
Just add https://make.wordpress.org/core/5-0/ in [Visualping](https://visualping.io) to receive the release date in your email when it's available.
