### ISSUE TITLE
Adding thickness and width to the Separator block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#7113]
Right now the Separator block does not offer any width or height to it.

At present it looks like this:
![default seperator](https://user-images.githubusercontent.com/5323259/40905045-fd9ee900-67dc-11e8-88d2-84d62d9529b5.png)

I have been looking at https://www.joomunited.com/wordpress-products/advanced-gutenberg and they have included a slider for thickness and width of the seperator line as well as style.

![joomunited seperator](https://user-images.githubusercontent.com/5323259/40904684-cb594e28-67db-11e8-9bb0-7b9915df4684.png)

These options should really be added to the default GB seperator line making it easy to right away create the width, thickness and style that is needed.

**Comment by karmatosed** [comment]
I think for the first version this doesn't need this as it does have a CSS class. Maybe later and maybe someone could create a plugin for this but right now lets keep things simple.
