### ISSUE TITLE
No editor: 500 error in console when adding new testimonial using Strong Testimonials and Gutenberg

### ISSUE THREAD

**Issue by RobinRoelofsen** [WordPress/gutenberg#7118]
**Describe the bug**
I'm building a new network, and want to use the Strong Testimonials plugin. When I go to add a new testimonial, the editor is blank. On this site, I use the Gutenberg plugin.

Tested with all plugins off, then turn Gutenberg and Strong Testimonials on, no problem. Turning all other plugins on one by one, no problem. Turn on Yoast SEO, the editor issue returns.

So I thought Yoast was the problem. Funny thing is, when I have only ST, Gutenberg and Yoast on, no problem...

When I go to the Add new testimonial screen and the editor is empty, and I use Chrome's Inspector and go to the Console tab, I see the following error:

Failed to load resource: the server responded with a status of 500 ()

Clicking on the link behind it and showing the log, it says:

load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-position,jquery-u&load[]=i-sortable,moxiejs,plupload&ver=4.9.6:9 JQMIGRATE: Migrate is installed, version 1.4.1
/wp-content/plugins/gutenberg/vendor/themes/modern/theme.min.js?wp-mce-4711-20180425:1 Failed to load resource: the server responded with a status of 500 ()

I guess the problem is Gutenberg's, but I am not sure. Could you please have a look 

**Expected behavior**
I would expect to see either the TinyMCE  editor or Gutenberg.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: checked in Chrome and Firefox

**Additional context**
Gutenberg version 2.9.2.

**Comment by danielbachhuber** [comment]
Hi @RobinRoelofsen,

Thanks for the report. This issue will be fixed in Gutenberg 3.0, see https://github.com/WordPress/gutenberg/issues/6809#issuecomment-390383562

**Comment by RobinRoelofsen** [comment]
Thanks!

Op ma 4 jun. 2018 16:44 schreef Daniel Bachhuber <notifications@github.com>:
