### ISSUE TITLE
Post Editor: BrowserURL should be resilient to post save failure

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#7123]
Related: #7122 (specifically https://github.com/WordPress/gutenberg/pull/7122#discussion_r192786768 )

Currently, if a save request fails for a post where the request explicitly updates the post status, the `BrowserURL` component introduced in #7122 will not revert the URL back to `post-new.php` if the post was an auto-draft at the time of initiating the save.

__Steps to reproduce:__

1. Navigate to Posts > Add New
2. Go offline (e.g. [Chrome "Offline" preset in Developer Tools](https://developers.google.com/web/tools/chrome-devtools/network-performance/network-conditions))
3. Enter a title
4. Publish the post

__Expected result:__

The post is optimistically assumed to update, thus it's reasonable for the URL to change, but once the save fails, it should revert back to the URL which had existed prior to the save being initiated (i.e. `post-new.php`).

__Actual result:__

The URL lingers in its optimistic state.

Fortunately, from what has been tested, it is perfectly okay for `post-new.php` to be treated as equivalent to `post.php?id=XYZ&action=edit` where XYZ is the post ID for an auto-draft post, so no breakage occurs.

**Comment by aduth** [comment]
>Fortunately, from what has been tested, it is perfectly okay for `post-new.php` to be treated as equivalent to `post.php?id=XYZ&action=edit` where XYZ is the post ID for an auto-draft post, so no breakage occurs.

@danielbachhuber Based on your [comment from Slack today](https://wordpress.slack.com/archives/C02QB2JS7/p1528124716000619), might I expect you'd propose we consider treating this as the default behavior anyways?

**Comment by danielbachhuber** [comment]
> might I expect you'd propose we consider treating this as the default behavior anyways?

Yes, I think this is a reasonable assumption, respecting any future discoveries otherwise.

**Comment by danielbachhuber** [comment]
Related https://github.com/WordPress/gutenberg/issues/3702#issuecomment-394517772

**Comment by tofumatt** [comment]
Sounds like #6322 is related too.

**Comment by nerrad** [comment]
Triage review agrees that this seems to be expected behaviour.  See [discussion context on Slack (requires signup)](https://wordpress.slack.com/archives/C02QB2JS7/p1555336208114500)
