### ISSUE TITLE
[3.0] columns do not appear on front end

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#7127]
**Describe the bug**
Columns do not appear on front end.

**To Reproduce**
1. Create a page/post with columns.
2. Add content to the columns
3. save
4. View on front end.
5. BUG: the content is not in columns.

**Expected behavior**
The content should be in columns.

**Comment by aduth** [comment]
Regression of #6773 

https://github.com/WordPress/gutenberg/pull/6773/files#r192851558

**Comment by jasmussen** [comment]
Sorry about that, and nice catch, thanks for the fast bug report!
