### ISSUE TITLE
Consider adding the ability to edit the source/text for a single block at a time.

### ISSUE THREAD

**Issue by circlecube** [WordPress/gutenberg#713]
There is the visual tab and the text tab, some advanced users will use the visual tab, but also want to make edits to the source. Switching to the text tab displays the text only view and it takes a while to find your place when looking at that (especially if there is a lot of content). Having the ability to simply edit the source for a single block would useful for quick source edits and would keep even the text view "modular". Displaying the comment block labels for each block will also be something every user will have to get used to, and editing just the source per module may alleviate that learning curve as well.

**Comment by paulwilde** [comment]
Rather than introducing new UI to handle that, maybe it would make more sense if your selection is consistent between each tab (Visual/Text)?

So if you were on say the 4th block down, and you switched the Text - Then your cursor would have the 4th block selected.

**Comment by mtias** [comment]
We have a Custom HTML block that toggles view between code and preview. Modifying the HTML os specific blocks is not something we will encourage since blocks can overwrite changes when the user interacts with it.
