### ISSUE TITLE
Text-styling options for a selection within a block

### ISSUE THREAD

**Issue by hansschuijff** [WordPress/gutenberg#7131]
**Is your feature request related to a problem? Please describe.**
When working with text within a paragraph, users sometimes want the ability to change the presentation of some text within the paragraph. I'm thinking f.i. color, font-size, underline, sub-script/super-script, inline block kind of things. In the previous editor one could select a (number of) letters or words and use the tools to change the selection only. Now such features are reserved mainly for the block as a whole. 

**Describe the solution you'd like**
What I would like is to have more font-related options in the tool-tip above the paragraph-block or a separate tool-bar above a text-selection, with options that apply to the selection. Right now the tools contains both options for the block as a whole (text-alignment) or a selection (bold/italic/del), but bold, italic and del seem to be the only options that can be applied to a selected text and that seems quite limited. 

Any setting that can be relevant on a letter by letter in stead of forming a new block might be in the toolbar. For instance: How can I mark part of a sentence as being code? Can I change fonts-attributes on a selection or even the font itself? Making a word red and large to have it stand out, making m2 looking like m-square (2 in superscript), or being just a bit creative with text-presentation? The toolbar in the mce-editor had some options that aren't yet in Gutenberg (or moved to the block-level), so perhaps there's a source for ideas?
 
I could imagine having the tools-tip above the paragraph being used only for font-related options, so they could all be used on a selection or set as a property to be used on new text. In that case the alignment (right, center, left) should be part of the block settings in the sidebar, where they probably would be more amongst their pierce. But if they are used so much that they have earned their place on the above tooltip, perhaps they should be also visually separated from the options that are not on blocklevel but on text-level.

**Describe alternatives you've considered**
Any alternative that doesn't expect me to code html+css is fine. Only he end-result counts.

**Comment by mcsf** [comment]
Closing in favor of #3688
