### ISSUE TITLE
Hitting Enter to recreate new paragraph block doesn't work when cursor is within italicized text

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#7134]
When my cursor is within the italicized text, hitting Enter creates a new paragraph block but keeps the cursor at the existing position.

I'd expect that my cursor would be placed within the new block.

![newblock](https://user-images.githubusercontent.com/36432/40946610-3eea59d6-6813-11e8-9c8b-30902c80a287.gif)

**Comment by GlennMartin1** [comment]
Same thing happens with **bold**.

A similar thing happens (slightly differently) with underline.

**Comment by mcsf** [comment]
@danielbachhuber, I can't repro. Writing Flow has somewhat improved recently. Feel free to reopen if I misdiagnosed.
