### ISSUE TITLE
Autosaving somehow triggers a full save when metaboxes exist, causing too many revisions

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#7135]
When there are one or more metaboxes on the page, the autosave process somehow triggers a full save, which then causes the creation of a ton of revisions.

See this GIF:

![toomanyautosaves](https://user-images.githubusercontent.com/36432/40947782-709b4458-6819-11e8-92c6-bfd81851d80b.gif)

Notably, see the "Autosaving..." animation, quickly followed by "Saving...". At the end of the experience, 4 revisions have been created (the UI for which is only present after you refresh the page):

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/36432/40947891-fb5856f8-6819-11e8-96d4-a5220c0731f1.png">

Previously https://github.com/WordPress/gutenberg/issues/3656#issuecomment-394531874

cc @adamsilverstein @aduth

**Comment by adamsilverstein** [comment]
Thanks for opening this issue, I’m out this week. I’ll take a look soon if nobody beats me to it.
