### ISSUE TITLE
Expose URLs based on functionality, do not assume wp-admin locations 

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#7136]
Stemming from issue #7095 

When Gutenberg is being used outside of wp-admin, for example as a front-end editor for P2, the expected redirect locations may be different than those within wp-admin. The specific case was for after the Move to Trash event, the redirect location is hard coded to edit.php which is the list of posts in wp-admin. However, for the P2/front-end use case, it might make more sense to redirect to the home page.

So a potential solution is to have the granular control to define redirection URLs, for example something like `getRedirectURLAfterTrash()`

**Comment by danielbachhuber** [comment]
Closing for now per https://github.com/WordPress/gutenberg/pull/7096#issuecomment-403868126

It seems like this optimization isn't entirely necessary now, but we can reconsider it in the future if it comes up again.
