### ISSUE TITLE
3.0.0 breaks custom icons.

### ISSUE THREAD

**Issue by Vinsanity** [WordPress/gutenberg#7139]
**Describe the bug**
Upgrading to version 3.0.0 breaks custom icons that are loading SVGs as JSX templates.

**To Reproduce**
1. Register a new block
2. For the icon property, add a JSX template for an SVG icon
3. Load a page on the FE and find your block.
4. Icon no longer appears. If you switch back to version 2.9.x it works

**Expected behavior**
Adding a custom SVG icon for a block from a JSX template should display an icon.

**Comment by jorgefilipecosta** [comment]
Hi @Vinsanity,
Thank you for reporting this problem. It is being addressed in https://github.com/WordPress/gutenberg/pull/7140.
As a temporary workaround, it is possible to wrap the SVG in a function e.g: () => ( <svg ... />, or create a component that renders the item and pass it e.g: icon: MyBlockIcon.
I'm sorry for the troubles caused.
