### ISSUE TITLE
Gallery Styling broken on front-end (3.0)

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#7152]
**Describe the bug**
With the release of 3.0, the styling for columns with images on the front-end is broken. All images appear in a single column.

(Sorry, I originally thought this was the Gallery block, but it turned out to be columns.)

This is with more than one theme, including Gutenberg Starter and Twenty Seventeen.

I reverted to GB 2.9.2, and the columns layout correctly.

**To Reproduce**
1. Create a 3 column block filled with images.
2. View on front end.
3. Columns all vertically arranged.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by youknowriad** [comment]
Are you using the Gallery or the Columns block? The gallery block works fine, but the columns block broke in 3.0.0

**Comment by weavertheme** [comment]
Sorry - it was Columns, and I've corrected the entry. Got the wrong block highlighted in the debugger on my test page which was a gallery. I didn't see any other bug reports on the columns issue, either, so sorry if a duplicate.

**Comment by youknowriad** [comment]
Yep, it's a duplicate and this is already fixed in #7128
