### ISSUE TITLE
Preview button does not redirect if pressed while unsaved changes exist

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#7154]
Related: #7124
Separate from publish preview task (#4099)

If the user hits the Preview button for a draft where unsaved changes exist, the preview window appears but the user is never redirected to the post.

**Steps to reproduce:**

1. Navigate to Posts > Add New
2. Enter a title
3. Hit Preview button (before autosave occurs)

**Expected result:**

Intermediary page appears, but eventually redirects to preview.

**Actual result:**

Redirect never occurs.

**Workaround:**

If the user first hits Save before Preview, then the preview loads correctly.

**Suspected cause:**

The logic for detecting whether a redirect should take place depends on the post's `modified` field being updated. This does not occur for autosaves. A preview is expected to be saved as an autosave (at least for published posts, which are not expected to be updated immediately).

https://github.com/WordPress/gutenberg/blob/e86d7b6415b0b073823f6b512430d76fd2ca90f3/editor/components/post-preview-button/index.js#L28-L36

**Comment by jenny-leung** [comment]
I have the same issue with Firefox and Chrome. Both do not load preview if not saved. The difference is Chrome opens a new tab with "about:blank" and Firefox shows the same url as the post edit page instead of the preview url.

**Comment by aduth** [comment]
Should be fixed in #7130
