### ISSUE TITLE
Rethink `allowedType` parameter in media-upload functions/components

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#7155]
I'm proposing two changes to the `allowedType` parameter used in the functions/components related to media uploading:

1. Rename `allowedType` to `accept`
2. Mimic the [syntax rules](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept) for the `accept` attribute in an `<input type="file">`

I think this would result in less confusion in our codebase, and more flexibility/clarity for third-parties who are going to use these components.

## Context
As we expand the scope of file uploads to filetypes beyond image/audio/video, I'm finding some problems with the `allowedType` parameter as it stands.

1. The name sort of conflicts with WP's [get_allowed_mime_types()](https://developer.wordpress.org/reference/functions/get_allowed_mime_types/), which is what we're planning to use for checking allowed types before uploading (#6968).

    Note that the WP-side `allowed_mime_types` is the list of all types that the current WP user can upload, which is dependent on the site. In contrast, Gutenberg-side `allowedType` is being used for restricting a component to only accept a certain type, like "image" for Image blocks.

    For example, an SVG file would pass a Gutenberg-side `allowedType="image"`, but it might be rejected against the WP-side `allowed_mime_types` if SVGs are not allowed. In any case, they each serve a different purpose and warrant different behaviors/errors when rejected, so we can't merge these two checks together. We should rename our `allowedType` so it won't be confused with the WP-side `allowed_mime_types`.

2. The syntax to be used for `allowedTypes` is not immediately apparent. Since its purpose is very similar to the `accept` attribute in an `<input type="file">`, we could just rename `allowedTypes` to `accept` and mimic that syntax.

## Relevant functions/components
- [mediaUpload](https://github.com/WordPress/gutenberg/blob/master/utils/mediaupload.js)
- [editorMediaUpload](https://github.com/WordPress/gutenberg/blob/master/editor/utils/editor-media-upload/index.js)
- [MediaUpload](https://github.com/WordPress/gutenberg/blob/master/edit-post/hooks/blocks/media-upload/index.js)
- [MediaPlaceholder](https://github.com/WordPress/gutenberg/blob/master/editor/components/media-placeholder/index.js)

**Comment by nerrad** [comment]
I'm going to make the assumption that since this hasn't surfaced as a problem in pulls/issues since this was created (after performing a search), that this is not something that will get changed.

Note: in #9707 there was work changing this attribute from `allowedType` (or `type` in some cases) to `allowedTypes`.

This can be reopened or a new issue created if additional reasons arise for the naming.
