### ISSUE TITLE
Framework: Use standard polyfill pattern for Element#closest polyfill

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#7159]
Related: #7033 (specifically overview at https://github.com/WordPress/gutenberg/pull/7033#pullrequestreview-124835640 )

We should consolidate our approaches to polyfilling missing behavior, mostly impacting Internet Explorer support. Our use of the `element-closest` module has proven difficult to maintain. The approach used in #7033 for polyfilling `Node#contains` is looking to be a better candidate for its maintenance and performance implications.

As part of this, we must determine a way to ensure these polyfills are loaded by all dependent scripts. Some ideas:

>In that sense, and given that these are true progressive enhancements which do nothing if a browser is detected to support a given feature, I'd say: Load it everywhere; every WordPress admin screen; for any features we ever use.

https://github.com/WordPress/gutenberg/pull/7033#pullrequestreview-124835640 

>we should probably not need to load it if:
>
>- There are zero scripts on a screen otherwise
>- We have some way of knowing / inferring that modern authoring practices are employed
>   - Only those which are transpiled (from a build directory)?
>   - Some other metric akin to @babel/preset-env@next's useBuiltIns: 'usage'?
>   - Register scripts through a new abstracted registration function, e.g. wp_register_script_with_polyfill?

https://github.com/WordPress/gutenberg/pull/7033#issuecomment-393572986

>There's a couple things I'd like to see, but not necessarily as part of these changes:
>
>- Avoid polyfills being considered as dependencies of specific scripts, unless we're certain we can maintain those dependencies.
>   - There's nothing about wp-dom that depends on the Node#contains polyfill. Wherever we're using it should be the dependency
>   - But then again, this highlights the bigger problem that this is a source of maintenance headaches and is likely not worth maintaining, vs. load always
>- Better names for the script enqueues, which avoids potential plugin incompatibilities. Probably something with a WP-specific prefix, e.g. wp-polyfill-node-contains

https://github.com/WordPress/gutenberg/pull/7033#pullrequestreview-125293992

**Comment by aduth** [comment]
Related Slack conversation (Core JS Meeting, 2018-06-19):

https://wordpress.slack.com/archives/C5UNMSU4R/p1529414641000073

**Comment by altrovideo** [comment]
Hi,
just found this error, using Gutenberg - Yoast - Woo Gutengerg Block plugins
`Uncaught Error: only one instance of babel-polyfill is allowed
http://wordpress.woo/wp-content/plugins/wordpress-seo/js/dist/commons-820.min.js?ver=8.2 line 1`

**Comment by aduth** [comment]
Hi @altrovideo , thanks for the report. You can follow https://github.com/Yoast/wordpress-seo/pull/10969 for Yoast's work on this. It appears to have been merged, so should be resolved in an upcoming release.
