### ISSUE TITLE
Using the inserter to insert a paragraph in the second column of the columns block, moves the cursor to the first column

### ISSUE THREAD

**Issue by haemeulrich** [WordPress/gutenberg#7160]
I'm unable to insert a Paragraph Block inside a Columns (Beta) Block. I'm only able to insert other blocks like images. Is this a limitation of the current version?

**Comment by haemeulrich** [comment]
Now it is even worse. I get content only to the first column. Please see my screencast here:
https://www.screencast.com/t/5S5M3mPibeW9

**Comment by youknowriad** [comment]
I'm seeing a small issue in your screencast where the paragrapn is inserter to the first column.

A simple workaround is to put the cursor directly in the second column and start typing.

**Comment by haemeulrich** [comment]
ok, thanks for this worlaround. Do I habe to do any bug report or so?

**Comment by youknowriad** [comment]
No, this issue is fine, I'm just renaming the title to clarify the bug.

**Comment by haemeulrich** [comment]
great thamk you for your great work!

**Comment by ZebulanStanphill** [comment]
I think this is a duplicate, or at least very closely related to #5772.

**Comment by mtias** [comment]
Is this issue still happening?

**Comment by ZebulanStanphill** [comment]
@mtias Yes, it is still happening in `master`.

**Comment by youknowriad** [comment]
Ii think this is fixed now.

**Comment by ZebulanStanphill** [comment]
@youknowriad It's currently not possible to reproduce this bug due to the mobile-style clickthrough selection behavior introduced a little while ago. It might resurface if that change is reverted (see #16888), though I'm not sure. It's probably fine to close this for now, though.
