### ISSUE TITLE
Should we add feature flags to aid with development?

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#7161]
[Feature flags](https://en.wikipedia.org/wiki/Feature_toggle) allow features that are currently under development to be turned off for end users. They're sometimes called feature toggles or feature switches. Check out [Calypso's implementation](https://github.com/Automattic/wp-calypso/tree/master/config#feature-flags) for inspiration.

There's a few advantages to having feature flags, including:

1. Merging code is no longer tied to a release—currently, we can't merge code until we are ready to ship it. This can block development since a developer then has to wait for a future release before they can iterate on that code. A feature flag lets us merge code now but release it in a later release by enabling the flag.
2. It's easier to keep PRs small—it's far easier to break up a large PR into smaller non-functional pieces when we know that the non-functional code is hidden behind a flag.
3. It's easier to experiment—with feature flags, we can introduce experimental features and APIs knowing that only advanced users will be able to access them. Importantly, we don't have to maintain backwards compatibility for something that's behind an experimental feature flag.

There's some disadvantages, of course:

1. Debugging is more complex—when filing a bug, for example, one will have to include what flags they have enabled in the bug report.
2. Testing is harder—for example, developers might not notice a bug that users see because they have some feature flags enabled that stops the bug.

Overall, I think adding feature flags would be useful for Gutenberg development and would help us maintain a fast and iterative development cycle while also ensuring stability for end users and plugin developers.

But what do you think? cc. @WordPress/gutenberg-core

**Comment by tofumatt** [comment]
Yes.

These are fantastically useful and the two main disadvantages are easily overcome if the flags have defaults in one file and overrides provided in a separate db/location/file–providing a clear view as to what's different.

Testing was rarely an issue in our usage of feature flags on @mozilla/addons-frontend, fwiw.

**Comment by youknowriad** [comment]
We already have a reducer keeping track of the features in local storage (it's used for the toolbar preference). The question is what things need to be hidden behind a feature flag. I think we all agree on the usefulness.
