### ISSUE TITLE
Consider tweaking nested block side action styles

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#7182]
To make it easier to tell which side tools are visible, the side tools for nested blocks (inside innerblocks layout areas) have a slightly different style; currently like this, with visible button borders:

![_untitled____ _mindful_org_ _wordpress](https://user-images.githubusercontent.com/1231306/41049044-01d773e6-697e-11e8-86d0-f20ab2c03d04.png)

This is slightly different from parent blocks, which don't display borders:

![_untitled____ _mindful_org_ _wordpress](https://user-images.githubusercontent.com/1231306/41049077-13de5992-697e-11e8-8f45-7f22de929311.png)

The distinction is helpful but I think can be improved — and make the side UI a little more consistent with the main toolbar — by wrapping these areas in a border instead of an always-visible border for individual styles.

Before and after:

![block-side-tools](https://user-images.githubusercontent.com/1231306/41049612-51423b18-697f-11e8-80ae-ddb1fa96a211.png)

And here's a demo:

![kapture 2018-06-06 at 11 35 35](https://user-images.githubusercontent.com/1231306/41049662-7034b3de-697f-11e8-8e20-aa226f9eb2af.gif)

This could extend to parent blocks as well, for greater consistency, although I didn't include that in the above demo.

Note that I also styled the borders to match the block hover styles implemented in #6773 but that could be changed as well.

**Comment by chrisvanpatten** [comment]
I've posted a PR for this in #7211. It's far from merge-able, but is useful as a way to try it out locally and get a feel for the change in your own environment. Would love thoughts and design feedback!

**Comment by karmatosed** [comment]
Closing this as we've explored other options.
