### ISSUE TITLE
Expanding selection on consecutive Meta+A presses buggy in Firefox doesn't work on Safari

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#7186]
Seems to me the new feature that allows to "Expand selection on consecutive Meta+A presses" introduced in #4600 hasn't been fully tested on all major browsers.

At a very first test, here's hat I've noticed:
- Chrome 66: works 
- Firefox 60.0.1: buggy (macOS and Windows)
  - first meta+a: selects block content, as expected
  - second meta+a: does nothing, expected: should select all blocks
  - third meta+a: select all blocks
  - holding meta+a: selects all blocks
  - on Windows, _sometimes_ after the first failure (that means the third step above) then a new meta+a press in a new block select all blocks (expected: should select the single block content) but couldn't reproduce consistently
- Safari 11.1: doesn't work at all; whether I repeatedly press meta+a or hold meta+a, nothing happens
- Edge: works
- IE 11: works!
- I haven't tested with screen readers on Windows

Worth noting an audible message after the selection happens would be beneficial for screen reader users, as right now there's absolutely no feedback on what happens when using meta+a.

**Comment by jorgefilipecosta** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/7445 which is more detailed.
