### ISSUE TITLE
Formatting toolbar buttons not visible in IE 11

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#7187]
Seems to me this is pretty new, as I haven't noticed before today. Here's how a block formatting toolbar looks like in IE 11. Notice there's a selection in the block text, so all the toolbar buttons should appear. Instead, just the "Change block type" is visible:

![screenshot 17](https://user-images.githubusercontent.com/1682452/41056681-472cd46c-69c5-11e8-9fd0-4a8e0eb695a2.png)

Actually, seems the buttons are there but seems they're "overlaid" so just one of them is visible. This is very clear when tabbing with the Tab key through the buttons: all the tooltips appear in sequence:

![screenshot 18](https://user-images.githubusercontent.com/1682452/41056761-786e229c-69c5-11e8-8d2d-82657968aee7.png)

So seems to me it's probably a CSS issue. Any relevant, recent change to the CSS?

**Comment by brandonpayton** [comment]
Based on a search with `git bisect`, the breaking commit appears to be 2b6d1663. I haven't had a chance to look further yet.

**Comment by brandonpayton** [comment]
This is due to `position: sticky` being unsupported on IE11.
