### ISSUE TITLE
Custom HTML shows An unknown error occurred.

### ISSUE THREAD

**Issue by mrdirby** [WordPress/gutenberg#7188]
When adding a custom html block I get an error that says "An unknown error occurred."

I just updated to version 3.0.1. 

![screen shot 2018-06-06 at 2 50 18 pm](https://user-images.githubusercontent.com/4106160/41058900-0527f19a-6999-11e8-908e-280d5e8464f8.png)

**Comment by aduth** [comment]
Can you check your browser's developer tools console to see if there are any useful messages there after the error occurs? This may vary by browser, but it is usually accessible by the keyboard combination Press Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac).

**Comment by mrdirby** [comment]
Sorry I should have checked in the first place. I'm using Chrome 67.0.3396.79 on High Sierra.

When I inspected that element I saw these errors. 
![screen shot 2018-06-07 at 10 35 07 am](https://user-images.githubusercontent.com/4106160/41107094-9453043a-6a3f-11e8-9927-cffcff5b1177.png)

I opened the same page in Firefox and the custom html field loaded. When I added some html and saved the changes the field worked in Chrome. Now all Custom HTML fields are working in Chrome. 

I am seeing these errors still in the console, both in Chrome and Firefox. So obviously there is a conflict with ACF. I will keep testing Chrome and see if I can repeat the error again. 

```
The hook name can only contain numbers, letters, dashes, periods and underscores. 105 index.js:1:3191
	u http://ghdev.test/app/plugins/gutenberg/build/hooks/index.js:1:3191
	c/< http://ghdev.test/app/plugins/gutenberg/build/hooks/index.js:1:3403
	add_action http://ghdev.test/app/plugins/advanced-custom-fields-pro/assets/js/acf-input.js:433:5
	_add_action http://ghdev.test/app/plugins/advanced-custom-fields-pro/assets/js/acf-input.js:2427:4
	extend/< http://ghdev.test/app/plugins/advanced-custom-fields-pro/assets/js/acf-input.js:2388:5
	each http://ghdev.test/cms/wp-includes/js/jquery/jquery.js:2:2929
	extend http://ghdev.test/app/plugins/advanced-custom-fields-pro/assets/js/acf-input.js:2386:4
	<anonymous> http://ghdev.test/app/plugins/advanced-custom-fields-pro/assets/js/acf-input.js:2666:15
	<anonymous> http://ghdev.test/app/plugins/advanced-custom-fields-pro/assets/js/acf-input.js:257:2
```

**Comment by mrdirby** [comment]
It seems like something wasn't loading before that is loading now. I can't recreate the error.

**Comment by aduth** [comment]
Related: #6091

**Comment by ombion** [comment]
I have this exact issue. It's not the browser. I happen to have 2 sites using Gutenberg. Using the same browser, one site works fine, and I get this error on the other site. The difference one site is installed under a sub directory, which I think is the problem. Custom HTML is an important block and this needs to be fixed with high priority. There's no other way to place custom HTML with Gutenberg.
