### ISSUE TITLE
Subheading Block: cannot add more than one subheading even after a page break

### ISSUE THREAD

**Issue by davidsword** [WordPress/gutenberg#7190]
**Describe the bug**

Sub Heading can't be used more than once in the editor - but shouldn't they be re-allowed after Page Breaks?

**To Reproduce**

Create subheading block, a paragraph block, whatever else, a page break, then add sub heading again for the new page
Get error, can't use 2x subheadings.

**Expected behavior**
Each page break should allow for another subheading

**Screenshots**

<img width="761" alt="screen shot 2018-06-06 at 12 29 32 pm" src="https://user-images.githubusercontent.com/1996370/41060967-0197f060-6986-11e8-8294-e14bd4ccc806.png">

**Desktop (please complete the following information):**

safari 11.1, mac os 10.13.4, gb 3.0.1, wp 4.9.6

**Comment by strarsis** [comment]
Hadn't this block been deprecated now?

**Comment by youknowriad** [comment]
Yes, it was, let's close this issue is invalid.
