### ISSUE TITLE
Image block captions are not synced with media library

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#7193]
**Describe the bug**

Images in the media library have caption data that can be entered. When images are inserted into content, the caption follows the image.

In the classic editor, when the caption is edited in post content, it also changes in the media library.

In Gutenberg, when the caption is edited in post content, it does not change in the media library.

In both the classic editor and Gutenberg, when the caption is edited by editing the image itself, the updated caption is applied to the content.

**To Reproduce**
1. Open a new post
2. Add an image block
3. Select a media item
4. Edit the media item's caption in attachment details
5. Click "Select" to insert the media
6. Edit the caption directly in the block
7. Edit the image
8. Look at the caption in attachment details

**Expected behavior**

Based on current behavior, I would expect that the caption text is synchronized between the image in content and the media library.

**Additional context**
- Gutenberg 3.0.1
- WordPress 4.9.6

**Comment by danielbachhuber** [comment]
> In the classic editor, when the caption is edited in post content, it also changes in the media library.

Are you sure about this? I don't believe it's the case. As soon as an image is inserted into the post, its caption and alt text are properties of the post, no longer the attachment database object.

Can you share a GIF or some screenshots of the behavior?

**Comment by jeremyfelt** [comment]
Bah, I was fooled. :)

When editing an image via post content in the classic editor, an "Image Details" modal comes up that shows the caption from post content. It does **not** sync with the media item's caption.

When editing an image via post content in Gutenberg, the "Select or Upload Media" modal comes up. This allows you to override the caption currently in post content, but does not sync from post content.

So more of a behavior change than a bug it seems like.

**Classic editor:**
![old-image-captions](https://user-images.githubusercontent.com/286171/41069463-d4fd2ca6-69a2-11e8-92f3-c8b5af86b561.gif)

**Gutenberg:**
![image-captions](https://user-images.githubusercontent.com/286171/41069335-4f5c74b2-69a2-11e8-9726-ce4dbf0979bc.gif)

**Comment by danielbachhuber** [comment]
@jeremyfelt No bug then?

**Comment by jeremyfelt** [comment]
Yeah, just some initial confusion for somebody used to a workflow. It's documented now though. :)

Thanks!
