### ISSUE TITLE
Cannot Type In Table-Cells: "Admin > Block > Table".

### ISSUE THREAD

**Issue by Xarcell** [WordPress/gutenberg#7207]
**Describe the bug**
Cannot input data/text/type into table cells via admin using latest version of Gutenberg, and Microsoft Edge.

**To Reproduce**
1. Go to: 'Gutenberg'
2. Click on: 'Add Block > Table'
3. Then: 'Try to type in Table-cells'
4. See error: nothing happens.

**Expected behavior**
I should be able to click on a table-cell and type in text.

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Browser: Edge 
 - Version 42.17134.1.0

**Additional context**
Gutenberg Version: 2.9.2
Wordpress Version: 4.9.6 
TwentySeventeen Theme Version: 1.6

**Tested In**
Google Chrome(66.0.3359.181) - WORKS!
Microsoft Edge(42.17134.1.0) - FAILS!

**Comment by Clorith** [comment]
Can confirm this is still an issue in Gutenberg 3.4.0 as well.

The `data-mce-selected` is unable to be set on cells inside the table, it only gets set on the `table` tag.

**Comment by stefanamport** [comment]
Can confirm that too, tested in Gutenberg 3.5.0
It's also not working in MS Edge

**Comment by stefanamport** [comment]
There was a contenteditable="true" on the <table> element, which is not supported in Edge & IE.

The issue seems to be solved by the following commit: https://github.com/WordPress/gutenberg/pull/8767

**Comment by mtias** [comment]
@designsimply can you check if this is still an issue?
