### ISSUE TITLE
Assigning separate color palettes for different blocks

### ISSUE THREAD

**Issue by davidknight4242** [WordPress/gutenberg#7213]
##Is your feature request related to a problem? Please describe.
At the moment we can load a palette of set colors, which is wonderful, but those same colors load for all blocks. This creates an issue if you have certain colors that should only be used for certain elements.

For instance I have blue, red and green, so those colors are great to use as buttons, but a user may end up using those colors as background for normal paragraph text and the visual hierarchy and design of the theme will be lost. Works the other way as well. I may have light grey I want them to use as a text background (Maybe for code/pre) but then they will use that color for buttons. 

This would be an issue for all blocks.

##Describe the solution you'd like
A way to assign different color palettes to different blocks easily, so we still give the user choice, but we set boundaries within the themes design.

--Describe alternatives you've considered
Hiding certain colors in blocks with CSS. Very hacky and dirty. Does not work

..Apologies if this has been covered elsewhere. I looked but could not come up with an answer.

**Comment by mtias** [comment]
Between block style variants (coming soon) and being able to supply a custom color palette when using the `ColorPalette` component, I think this should be covered.

**Comment by davidknight4242** [comment]
Block style variants sounds like it would be perfect! Thanks for the reply.
