### ISSUE TITLE
[3.0] Removing a block

### ISSUE THREAD

**Issue by vonloxx** [WordPress/gutenberg#7215]
**Description**
Removing a block auto selects/focus the previous one but it doesn't open the block tab on the sidebar.

**To Reproduce**
With, at least two blocks, remove the last one and you see that the previous block is focused but the active sidebar tab is "Document".
I was able to confirm that after removing a block it triggers the OPEN_GENERAL_SIDEBAR action event two times, first for document and another for block but it's the document tab that stays active. And then, if we click on a block or on the sidebar block tab, the OPEN_GENERAL_SIDEBAR event is not triggered.

**Screenshots**
![gutenberg-remove-block](https://user-images.githubusercontent.com/1254357/41113799-804bc8a6-6a7a-11e8-8790-a7d01282cf9a.gif)

**Notes**
This behavior has little impact on the UX but I guess for integrations it could be a problem.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox, Chrome

**Comment by mtias** [comment]
Thanks for raising this. It looks to be working as expected now.
