### ISSUE TITLE
In add block menu show preview or description on mouse over

### ISSUE THREAD

**Issue by s1sfa** [WordPress/gutenberg#7217]
When you are adding a block there are lots to choose from. Maybe as a benefit to new users or users discovering new blocks is that on mouse over there can be a description about the block, an image, or an animation showing what the block will look like.

**Comment by karmatosed** [comment]
We have a preview for shared blocks and it's been talked about before having for all. I like that idea a lot.

**Comment by mtias** [comment]
We initially added preview for all blocks, but given there's not always default text to show, it wasn't great. We are adding it for style variations, so it could be something we revisit.
