### ISSUE TITLE
Blocks: Bring transforms into block library

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#7227]
Right now we have transforms showing blocks but not in a library. This can be a weird experience and what I suggest is we both only have transforms in one place and also have them use the block library interface.

![transforms](https://user-images.githubusercontent.com/253067/41156905-bfb7bfe4-6b1b-11e8-977a-ea8797cf201b.png)

**Comment by SuperGeniusZeb** [comment]
Thanks to #7362, this issue can be closed now, right?

**Comment by gziolo** [comment]
Yes, correct. I can see it in the `master` branch:
![screen shot 2018-07-05 at 11 22 13](https://user-images.githubusercontent.com/699132/42314619-b7f73f98-8045-11e8-8df4-eb1758554e2d.png)
