### ISSUE TITLE
Edit "Publish Date" quickly with input box

### ISSUE THREAD

**Issue by pinghsing** [WordPress/gutenberg#7241]
Problem:
Some times we need to publish posts from distance past, 2012 for example. Current way of moving publish date month by month require 72 click to move to 2012, which is not convenient.

Suggested solution:
Let us type the year of publish in a input box, similar to that of "hour" and "minute".

Suggested alternative solution:
Add button to switch each decimal of publish year from 0~9, if input box is not desired.

**Comment by danielbachhuber** [comment]
Flagging `Needs Design Feedback` to see if this is something we'd like to address.

I think @pinghsing brings up a good point. In the Classic Editor, it's relatively simple to move a post back in time:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/36432/42572319-3a5d7222-84ce-11e8-9f87-25b68b6f718c.png">

In Gutenberg, there's no direct inputs for modifying the month, day, or year:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/36432/42572392-4f775cae-84ce-11e8-9e5f-413d49671bed.png">

**Comment by karmatosed** [comment]
The date picker is something being explored so let's focus on that and come back to iterations once we have a base picker everyone is happy with. #1311 has some background there.
