### ISSUE TITLE
Height control in Cover Image block settings

### ISSUE THREAD

**Issue by VladNov** [WordPress/gutenberg#7245]
**Problem**
Currently the Cover Image block height depends on quantity of added text.

**Suggested Solution**
To remove this dependency and give more flexibility, add a text input in settings so it would be possible to change the block height, similar to the option in the Spacer block.

**Comment by strarsis** [comment]
It would be already nice to be able to separately adjust the image settings (for selecting an image size), 
like a normal image block and the cover block allows compositing stuff above each other.

**Comment by kjellr** [comment]
This issue is a little stale, in that it's mostly referring to the old version of the Cover block. I'm going to close it in favor of #17113, which addresses the same end goal.
