### ISSUE TITLE
"Custom HTML" in "Columns (beta)" doesn't work

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#7248]
**Describe the bug**
Console says that the block breaks because of this reason:

```
Expected:

<div class="layout-column-1"><div class="layout-column-1">
		<div class="abc">This is my custom HTML that I entered in the "Custom HTML" block.</div>
	</div></div>
```

```
Actual:

<div class="layout-column-1">
		<div class="abc">This is my custom HTML that I entered in the "Custom HTML" block.</div>
	</div>
```

**Additional context**
- Please add the version of Gutenberg you are using: 3.0.1
- "Custom HTML" blocks outside "Columns (Beta)"/InnerBlocks work.

**Comment by roborourke** [comment]
I've just run into this too, thanks for reporting @manake

**Comment by SuperGeniusZeb** [comment]
Is this still happening in Gutenberg 3.2?

**Comment by manake** [comment]
I'm 99% certain it's not happening for me anymore in v3.2.

**Comment by SuperGeniusZeb** [comment]
I can not reproduce either in Gutenberg 3.2, so I think this issue can be closed.
