### ISSUE TITLE
Preview not working well with Gutenberg editor

### ISSUE THREAD

**Issue by ginigangadharan** [WordPress/gutenberg#7253]
**Preview not working well**
We used to click Preview button to see how our post look like right ? And with Gutenberg editor, most of the times Preview will not work properly. It will open a new tab (or new window) but will just show and with a message (or blank) as below.

Please wait…

Generating preview.

**To Reproduce**
Add something on your wordpress post --> Click Preview Button.

**Expected behavior**
It should open a new window (or tab) with preview of current post/page.

**Screenshots**
https://github.com/ginigangadharan/techbeatly/blob/master/images/gutenberg-editor-preview-not-working-well.PNG

**Desktop (please complete the following information):**
 - Hosting : shared hosting at Hostgator (also tried google cloud standalone server)
 - Browser : firefox, Google Chrome

**Additional context**
Gutenberg : Version: 3.0.1

Workaround I am using  - Click on "Save Draft" and try Preview button; it will work.

**Comment by danielbachhuber** [comment]
Hi @ginigangadharan,

Is this a duplicate of #4099?

**Comment by ginigangadharan** [comment]
Hi @danielbachhuber ,
exactly, thanks for pointing that.
not sure why did I miss that :)

let's check it on main thread.
