### ISSUE TITLE
Cannot search block library on mobile

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#7254]
**Describe the bug**

When searching for a block through one on the interest, the insert screen completely disappears on typing the first character.

**To Reproduce**
1. Use one of the inserters to get to the block library on a mobile device.
2. Focus the search field and enter a character.
3. The library disappears.
4. 

**Expected behavior**

To get a filtered list of blocks.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser [e.g. chrome, safari] safari
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by iamthomasbishop** [comment]
Fwiw, I'm unable to reproduce this on the following:

* iPhone X: iOS 12 beta 6 / Safari (stock) + Chrome (68.0.3440.83)
* Google Pixel 2: Android 9.0.0 / Chrome (67.0.3396.87)

**Comment by mtias** [comment]
Closing this as unable to reproduce. Let's reopen if it surfaces again.
