### ISSUE TITLE
Title field does not auto resize correctly on first load

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#7255]
**Describe the bug**

I’ve seen this a few times on desktop too. Forgive me if it’s already been reported.

![d134c2c2-f04a-4bb0-8c5b-306f072b651d](https://user-images.githubusercontent.com/4710635/41214389-78ba657e-6d4b-11e8-8971-4b7c00bd3f6e.png)

**To Reproduce**
1. Load Gutenberg and observe the title. You may have to change it in length but for me it happens with the demo content too.

**Expected behavior**

Whole title should be visible.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] safari
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by jorgefilipecosta** [comment]
I think this problem is not happening now. @iseulde could you confirm if the problem is resolved?

**Comment by afercia** [comment]
See also #6897 (re-tested on July 19) and #8930.

**Comment by tofumatt** [comment]
I think this is a duplicate of #6897, but I guess that means it can happen on browsers other than Firefox.
