### ISSUE TITLE
Cannot edit publish date on mobile

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#7257]
**Describe the bug**

Clicking the date in the document tab does nothing.

**To Reproduce**
1. Click on the cog icon and then on the date. Nothing happens.

**Expected behavior**

To be able to edit the date.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] safari

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by GlennMartin1** [comment]
This is a duplicate of https://github.com/WordPress/gutenberg/issues/6604

**Comment by iseulde** [comment]
Thanks!
