### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7259]
I've added Block Editor styles to a theme so that the editor resembles the front-end. On my 27" iMac, the editor works fine. When I try to edit a page on my (old 2011) MBP though, with a smaller screen resolution, I get horizontal scrolling.

I've set `max-width` on `.editor-block-list__block` but because the width of `.edit-post-layout__content` is only 50px more than that max-width that I've set, there ends up being horizontal scrolling. This is due to the way Gutenberg editor has been designed and the absolute positioning of elements outside of each blocks container (i.e. the block mover and block settings menu). It's these elements that are negatively positioned that are causing the horozontal scrolling.

There's no way for me to know the screen size the end user will be using, and therefore no way for me to know the maximum width of `.edit-post-layout__content`. The whole reason behind using `max-width` is so that I don't need to know these widths. Gutenberg needs to rethink where these controls are placed so that it doesn't cause horizontal scrolling within the editor.

**To Reproduce**
1. Set `editor-block-list__block` to `max-width: 1190px;`
2. Reduce browser width to 1680px
3. View horizontal scrolling

**Screenshots**
![gutenberg_horizontalscrolling](https://user-images.githubusercontent.com/2078245/41219586-1a447d5c-6da2-11e8-90b1-37e2d84c86dc.gif)

_mac osSierra 10.12.1
Firefox Quantum 60.0.1 (64-bit)
Gutenberg 3.0.1_

**Comment by karmatosed** [comment]
I can't replicate this in my own theme and as it seems to be part of a custom theme lets close for now this as we focus on phase one.

**Comment by chrisvanpatten** [comment]
If #6224 lands, I _think_ that'll fix this.

**Comment by maddisondesigns** [comment]
@chrisvanpatten Unless the block mover is also moved inside the block container, it wont fix it completely
