### ISSUE TITLE
Strip Blocks from Auto-Generated Excerpts

### ISSUE THREAD

**Issue by fklein-lu** [WordPress/gutenberg#7268]
**Describe the bug**
When the function `get_the_excerpt()` is called, and no manual excerpt exists, `wp_trim_excerpt()` generates an excerpt from the post content.

The issue is that when the beginning of the post contains a Gutenberg block, it will be rendered. But only the textual content will survive, as `wp_strip_all_tags()` is called on the generated output.

Excerpts are supposed to be text only, and Gutenberg should not break this convention.

**To Reproduce**
1. Create a post, and insert a Gutenberg block outputting a mixture HTML tags and text at the top.
2. Save the post.
3. View the generated excerpt in any theme using `get_the_excerpt()`.

**Expected behavior**
Gutenberg blocks should not be rendered in excerpts.

The way I see it, a block and a shortcode are very similar, so they should be treated the same: being stripped.

Related: #5572

**Comment by danielbachhuber** [comment]
> The way I see it, a block and a shortcode are very similar, so they should be treated the same: being stripped.

I agree with this assessment.

**Comment by chrisvanpatten** [comment]
Might have to put an exception in for certain blocks for this to work properly. Paragraphs, list, blockquotes, etc. would all be stripped if you just blindly stripped all blocks.

**Comment by danielbachhuber** [comment]
@fklein-lu Can you include more detail of your expected behavior?

**Comment by danielbachhuber** [comment]
@chrisvanpatten Do you understand this issue well-enough to include full reproduction steps and detail of expected behavior?

**Comment by chrisvanpatten** [comment]
@danielbachhuber I'm not sure what you mean — I didn't report the issue. Want me to take it over? Happy to help, just not sure what you need :)

**Comment by danielbachhuber** [comment]
@chrisvanpatten Sure, if you'd like. I'll close otherwise. I need more detail about how to reproduce this issue and what the expected results are. I started looking into it 12 days ago but got stuck when I realized I didn't fully understand the nature of the request.

**Comment by danielbachhuber** [comment]
Thanks @chrisvanpatten, this is exactly the clarification I was looking for.

**Comment by bobbingwide** [comment]
The Gutenberg implementation involves some hacky code that adds `strip_dynamic_blocks` to the `the_content` filter then removes it again when `wp_trim_excerpt` is run - the function invokes the filter hook. 
This assumes that `wp_trim_excerpt` will be run. 
In one of my plugins I had replaced `wp_trim_excerpt` with my own code.

```
remove_filter( "get_the_excerpt", "wp_trim_excerpt" );
add_filter( "get_the_excerpt", "oik_get_the_excerpt" );
```

Since wp_trim_excerpt is no longer being run the strip_dynamic_blocks hook is not being removed. So my dynamic blocks did not appear when the post was being displayed singly and WordPress SEO is activated. 

My workaround is to not remove the filter.
