### ISSUE TITLE
Provide clear distinction when expanding/collapsing block categories

### ISSUE THREAD

**Issue by jancavan** [WordPress/gutenberg#7272]
**Is your feature request related to a problem? Please describe.**
I kind of lose track of where I am when expanding/collapsing block categories:

![screenshot 2018-06-11 13 42 56](https://user-images.githubusercontent.com/4924246/41256065-61e2c4ea-6d7d-11e8-995f-328db1a0df54.png)

**Describe the solution you'd like**

1. Subtle animation when expanding/collapsing sections.
2. Perhaps the opened section should look slightly different from the collapsed ones.

**Describe alternatives you've considered**
I haven't explored any alternatives, but either one (or both?) solutions above will help.

**Comment by SuperGeniusZeb** [comment]
Here is a mockup GIF from [one of the comments](https://github.com/WordPress/gutenberg/pull/6168#issuecomment-387081676) in #6168 which shows one alternative solution for always keeping the current block category visible: make it sticky.

![](https://user-images.githubusercontent.com/191598/39706879-c399dcb8-51e0-11e8-9ad6-633860e10aa9.gif)
