### ISSUE TITLE
Confusing hierarchy of quick access buttons

### ISSUE THREAD

**Issue by jancavan** [WordPress/gutenberg#7274]
Why do the Transform buttons exist within the ellipsis when they can also be accessed from the + button?
![screenshot 2018-06-11 13 51 35](https://user-images.githubusercontent.com/4924246/41256491-9a7277a0-6d7e-11e8-9da7-99dea0631b6c.png)

This confused me because we have quick access buttons (quote, image, gallery), then we have the ellipsis which contains additional settings. However, in the same ellipsis, there's more quick access buttons. 

So essentially - quick access buttons --> settings (hide, edit, etc.) --> then more quick access buttons. It just feels to me like the continuity is lost. It made me feel like the second group of buttons in the ellipsis are something else that's not quick access to certain blocks:

![screenshot 2018-06-11 13 51 35](https://user-images.githubusercontent.com/4924246/41257058-587fe8b2-6d80-11e8-9fa5-c78e752f10f0.png)

**Comment by chrisvanpatten** [comment]
I believe this will be addressed as part of #7227 and #6449.

**Comment by mcsf** [comment]
Closing per the above.
