### ISSUE TITLE
Guetenberg permalink change and page update doesn't affect WP Admin bar

### ISSUE THREAD

**Issue by pojke** [WordPress/gutenberg#7275]
**Describe the bug**
When you change the permalink in Gutenberg, WP admin bar "view page" is not affected after updating the post. It still links to the old page until the page is refreshed. 

**To Reproduce**
1) Create a new page "test". Publish.
2) Edit permalink, change "test" to "test123"
3) Click "Update"
4) Click View Page on WP Admin bar

**Expected behavior**
Expecting View Page to link to "test123" but it still links to "test" until refreshed

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.2.0. ([42s](https://cloudup.com/c0RC9u8dO37))

![screen shot 2018-11-06 at 7 27 30 pm](https://user-images.githubusercontent.com/1119271/48106779-298d4d80-e1fa-11e8-9c4a-4a81804331f7.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15563&action=edit running WordPress 4.9.8 and Gutenberg 4.2.0 using Firefox 63.0 on macOS 10.13.6.</sup>
