### ISSUE TITLE
props.isHovered not working

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#7281]
Hi,

I'm creating a tabbed-layout column for easier column management and found out that isSelected is working but isHovered isn't. Here's a preview on what I'm working on. Thanks!

![screen capture on 2018-06-11 at 17-13-19](https://user-images.githubusercontent.com/3365507/41283147-b110a2ea-6dea-11e8-9637-ccf629af9adf.gif)

Cheers,
Jeffrey

**Comment by youknowriad** [comment]
In which component `isHovered` is not working? Is it in a block? If that's the case, I think `isHovered` was never a thing there?

**Comment by phpbits** [comment]
@youknowriad Hmmm, searched and there's `isHovered` on property. What do you recommend in order for me to display the tabs on inner block selection? I need to be able to display them aside from when the main column block is selected. Thanks!

**Comment by youknowriad** [comment]
Maybe you should try showing them inside the `edit` function of your wrapper's block. But not as buttons in the `BlockControls` but directly inside the block itself.

**Comment by phpbits** [comment]
@youknowriad I'm using` blocks.BlockEdit` filter via ES5, would you mind letting me know which is the `edit` function? I'm using similar function to this one : https://github.com/WordPress/gutenberg/pull/4002 Thanks!

**Comment by youknowriad** [comment]
Oh, so you're extending the core provided columns block, I suggested creating your own columns block instead.

**Comment by phpbits** [comment]
@youknowriad yes. I think there's no point on creating a new one since I'll be adding toggle selection view on the block's setting area. Do you think it's possible to show the tabs when innerblocks are selected? Thanks!

**Comment by youknowriad** [comment]
If the tabs are not displayed in `BlockControls` they will be always visible.

**Comment by phpbits** [comment]
@youknowriad Thanks! Will try it out.

**Comment by youknowriad** [comment]
I'm closing for now, let me know if it doesn't work.

**Comment by phpbits** [comment]
@youknowriad I thinks there's no option aside from `BlockControls`. Do you have any suggestion? Thanks!

**Comment by youknowriad** [comment]
Just remove the `BlockControls` wrapper. Can you share the code of your hook?

**Comment by phpbits** [comment]
@youknowriad I'm using similar code to this one : https://github.com/WordPress/gutenberg/pull/4002 👍 
```
var testButton = !! props.focus
                && el(
                    BlockControls,
                    { key: 'test_button_block' },
                    el(
                        TestButton,
                        {
                            button: {
                                key: 'test_button',
                                isPrimary: false,
                                title: __( 'Test', 'test' ),
                                onClick: onTestButtonClick
                            },
                            container: {
                                className: 'components-toolbar'
                            },
                        }
                    )
                );
            element = [ element, testButton ];
```

**Comment by phpbits** [comment]
@youknowriad Can you change the status to open again? Thanks!

**Comment by youknowriad** [comment]
Remove the wrapper `BlockControls` and the `props.focus` test

**Comment by phpbits** [comment]
@youknowriad Thanks! It's working now. Another question is do have idea how can I add item on the Block Settings? I need to add toggle view for tabbed and the default one. Thanks!
<img width="265" alt="screen shot 2018-06-12 at 6 59 24 pm" src="https://user-images.githubusercontent.com/3365507/41286584-d2ebd222-6df4-11e8-959c-1db53daabb56.png">

**Comment by phpbits** [comment]
@youknowriad There's a problem on onClick when it's not on `BlockControls`. Seems like click is disabled. Thanks!

**Comment by youknowriad** [comment]
> how can I add item on the Block Settings?

That's not possible and that maybe a good Extensibility Slot to add, but not possible at the moment.

> There's a problem on onClick when it's not on BlockControls. Seems like click is disabled. Thanks!

Unfortunately, I can't debug all the issues you have in your plugin, a bit more efforts to find the source of these issues would be greatly appreciated.
