### ISSUE TITLE
Can't Drag 'n Drop Multiple blocks at once

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7283]
After selecting multiple blocks, you can't then drag 'n drop them. You can only Drag 'n Drop a single block at a time. Since every single paragraph is forced into it's own block, it's going to be very frustrating and slow if we can only move one block at a time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select multiple blocks
2. Try to drag and drop those blocks to another position

_mac osSierra 10.12.1
Firefox Quantum 60.0.2 (64-bit)
Gutenberg 3.0.1_

**Comment by draganescu** [comment]
This is still an issue as of April 2020. The better part is that with the G2 UI improvements its clearer that this is not something that you can do: the mover does not show a drag handle if there is a multiple selection.

However for Full Site Editing, it might be an even more important issue to consider in the context of page building, vs post editing.
