### ISSUE TITLE
Figure Captions:  bug on generation URL in Caption

### ISSUE THREAD

**Issue by danielbento** [WordPress/gutenberg#7285]
**Describe the bug**
https://cl.ly/0d1j0V261I3G (animation showing bug on generation URL in Caption)
When adding a URL in Caption, it shows URL instead of adding it.

**To Reproduce**
https://cl.ly/0d1j0V261I3G
1. Add image with caption
2. Add URL in caption
3. See error

**Expected behavior**
The URL should be added to the caption, now showing it.

**Screenshots**
https://cl.ly/0d1j0V261I3G

**Comment by ellatrix** [comment]
@danielbento Looking at the video, it looks like you changed the selection from selecting the entire caption to collapsing the selection. Inserting a link with a collapsed selection will insert the whole link. Make sure the whole text stays selected when inserting a link.
