### ISSUE TITLE
Data Module: Improve Selectors/Actions docs

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#7287]
Related #7264

Now, that we generate markdown docs for Selectors and Actions, we need to make sure the wording used there is accurate and not redundant.

For instance: Actions shouldn't state that they return action objects.

Instead of `Returns an action object used in signalling that block types have been added.`, write `Signal that a block type, or types, have been added.`

More details here https://github.com/WordPress/gutenberg/pull/7264#pullrequestreview-127916268

**Comment by aduth** [comment]
Hmm, but they're worded as such because the functions alone do not signal anything, they _do_ return action objects, even if in the typical sense they are only used in dispatching to a Redux store.

**Comment by tofumatt** [comment]
Yeah, but wording them all to say they just return an object doesn't imply how/why they're actually used. As mentioned in [this comment](https://github.com/WordPress/gutenberg/pull/7264#discussion_r194701027), I think the middle ground is to say the entire set of functions returns the object, but then describe each function on the action it creates when passed to the store's `dispatch()` function.

Describing the actions all as just "functions that return objects" isn't very informative 😄

**Comment by youknowriad** [comment]
Seems like there's no consensus here, I'm closing this issue right now but we can still reconsider.
