### ISSUE TITLE
Multiple loading animations when uploading multiple images

### ISSUE THREAD

**Issue by eliorivero** [WordPress/gutenberg#7288]
**Describe the bug**
When I drop multiple images, there are multiple loading animations. Checking wp-admin/upload.php shows that some images are already fully uploaded.

**To Reproduce**
Steps I followed with more issues along the way
1. Added a new post
2. Tried to drop images in it, like in TinyMCE. I couldn't, similar to #6426 but an image block was added and Media Library was open
3. Dropped images to the open Media Library. They started uploading but the Media Library went blank and was removed—only Gutenberg was now visible
4. The image block was now a Gallery block and images seemed to be uploading. It displayed multipled loading animations like

<img width="698" alt="captura de pantalla 2018-06-12 a la s 11 29 40" src="https://user-images.githubusercontent.com/1041600/41297720-2975b66c-6e36-11e8-9401-d93685d4d47c.png">

**Expected behavior**
While I found a bunch of issues with dropping images (those mentioned in the steps and the fact that the 15 images weren't uploaded and the component kept loading forever), this issue is focused only on the last issue described: there should be only one animation, regardless of whether the images will be displayed as soon as they're fully uploaded or at the end of the batch.

**Desktop (please complete the following information):**
 - OS: High Sierra
 - Browser: Chrome
 - Version: 67.0.3396.79

**Additional context**
- Gutenberg 3.0.0

**Comment by mtias** [comment]
This should have been addressed by https://github.com/WordPress/gutenberg/pull/7657
