### ISSUE TITLE
Tooltip styling is broken

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#7299]
## The issue
The styling for tooltips seems to be broken in `master` right now.
![image](https://user-images.githubusercontent.com/19592990/41355370-f35ebe0a-6ee6-11e8-9391-b096633c1321.png)

Tested in Firefox Beta 61.0b13 and Chromium 67.0.3396.79.

**Comment by danielbachhuber** [comment]
I can't reproduce in Firefox 60.0.2:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/36432/41443422-8ec51e9c-6ff1-11e8-912d-df9b8838b035.png">

Do you have any plugin styles that might be impacting? Can you debug further to see if you can track down the root cause?

**Comment by SuperGeniusZeb** [comment]
The issue seems to be gone now. I guess it was a plugin or theme conflict that has now been resolved. :man_shrugging:
