### ISSUE TITLE
Always show "new gallery item" below the gallery

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#7300]
Currently, selecting a gallery can shift the layout presentation to accommodate the extra placeholder item. That makes it hard to work with galleries since layout can change on selection and not be faithful.

Let's move the "new gallery item" to be always below the gallery, full-width, and avoid disrupting the gallery presentation.

![image](https://user-images.githubusercontent.com/548849/41355548-13ee0938-6f22-11e8-8f30-f0e444570dfd.png)

**Comment by SuperGeniusZeb** [comment]
Just to be clear, the placeholder will still only appear when the block is selected, right? If so, then great! The placeholder moving the other images around felt a bit odd.

**Comment by mtias** [comment]
Yes, correct, only on selection. Just would avoid the gallery becoming 3 columns for some reason on selection.

**Comment by karmatosed** [comment]
I sort of like it shifting I have to say. I did say in PR but saying here to make sure say in right place, sorry about that.

For example here where it shows there could be more.

![2018-06-20 at 20 41](https://user-images.githubusercontent.com/253067/41680733-62f48b80-74ca-11e8-8605-42dae6a029e3.png)

I feel it gives more of an impression of what it could be.

**Comment by tofumatt** [comment]
It's harder to locate though; putting the inserter in a common place and on its own line makes it easier to locate and makes it stand out. I actually found, just in testing this patch against the behaviour in master, that the existing, inline inserter is harder to locate/tell apart (from those example, grey-background images), and the placement being inconsistent makes it annoying to add images one after the other.

I think the full width, consistently-placed inserter is much better and more discoverable.

**Comment by caxco93** [comment]
Besides from the inserter being more discoverable, I think another great benefit is preventing the layout from changing and not being faithful to what the user would finally see as posted.

Regards 
> I feel it gives more of an impression of what it could be.
I see it more as a "what WILL the user see posted" vs "what COULD the user see posted"

**Comment by mtias** [comment]
> I feel it gives more of an impression of what it could be.

The problem is that selecting a gallery to, say, add a caption to an image, can drastically change the layout, which makes it very hard to write the caption and see how it would look because the "add new image" is changing the whole layout.

**Comment by karmatosed** [comment]
After reflecting on this 👍 lets get it in and tested. I do still feel the impression point is valid but consensus is also ok to go with.
