### ISSUE TITLE
prevState in gutenberg

### ISSUE THREAD

**Issue by sylvaincordiere** [WordPress/gutenberg#7302]
I have an attribute checked which is a boolean type
like this 

 ```
checked:{
			 type:   'boolean',
			 default: false,
		}
```
Is it possible to use prevState with it ?
```

					      setAttributes((prevState, checked) => ({
						  checked: !prevState.checked
						}));
```

**Comment by mitogh** [comment]
I think you can use `componentDidUpdate(prevProps, prevState, snapshot)
` in your component where you have to the `prevProps` and the attributes are props injected into the component. @sylvaincordiere .

Unless you want to access the value on initial loading.

**Comment by mcsf** [comment]
Closing as duplicate of #5596.
