### ISSUE TITLE
How to add a custom setting?

### ISSUE THREAD

**Issue by mitogh** [WordPress/gutenberg#7314]
Hey guys was looking into a way to add a custom option into `<BlockSettingsMenu>` for my block in the same way we can add custom settings on the sidebar.

Was looking into some examples and code but the only settings presents are the default ones per block.

Thanks a lot for the guidance and help.

**Comment by Luehrsen** [comment]
Hey @mitogh, 

sure. That is done with the `BlockControls` component, that gets rendered in the `edit` function. 

E.g.: 
<img width="653" alt="bildschirmfoto 2018-06-15 um 10 07 35" src="https://user-images.githubusercontent.com/1105871/41457473-11b6da74-7084-11e8-8fad-667cf3034ded.png">

In this example i register my own block controls, add a toolbar and render two icon buttons in that toolbar. That buttons have an onclick function, that does some variable wrangling somewhere else in the class.

**Comment by mitogh** [comment]
Fantastic thanks a lot @Luehrsen 🎉

**Comment by mitogh** [comment]
BTW! Any way to add this controls into the `<BlockSettingsMenu>` instead of above the block? 

As `<Blockcontrols>` seems like adds the controls above the block.
