### ISSUE TITLE
Can't resize columns in Columns Block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7315]
It's not currently possible to resize the columns in the columns block. The ability to have columns is imperative for providing more flexible layouts. If you can only add equal width columns though, it makes it extremely limiting.

Ideally, you should be able to specify a percentage width for each column. At a bare minimum though, you should at least be able to select a different layout such as:

If there's 2 columns: 50/50, 25/75, 75/25
If there's 3 columns: 33.3/33.3/33.3, 50/25/25, 25/25/50, 25/50/25
If there's 4 columns: 25/25/25/25, 40/20/20/20, 20/20/20/40
etc...

_Gutenberg 3.0.1_

**Comment by chrisvanpatten** [comment]
Further context/previous related discussions: #4900, #6650, #6461, #4902, #5886, #6048, #219

**Comment by rickcurran** [comment]
The ability to define this via various responsive classes defined in CSS would definitely be useful.

**Comment by sylvaincordiere** [comment]
This request have been ask many time.
Is there any decision taken by gutenberg team ?
Is there any plan to add this in wordpress 5, later or never

**Comment by SuperGeniusZeb** [comment]
I agree that it would be nice to see a decision on whether the Columns block will be getting non-equal width and responsive columns before WordPress 5.0 or not. In its current state, the Columns block, while definitely better than it was initially, is still useless for nearly any practical applications – primarily due to the lack of responsiveness, though non-equal width columns are almost as essential.

**Comment by designsimply** [comment]
Thank you for the feedback! It's a good question. Since the Columns block is still in beta and  because the question has been asked in a few other places, I am closing this issue in favor of https://github.com/WordPress/gutenberg/issues/6048 which I believe should cover this issue once a decision has been made there.

**Comment by emar** [comment]
Thanks I'll keep an eye open for further releases, sound great works nicely.
The great thing is I'll have no need for two extra plugins to have a custom editor... soon.

**Comment by kevinckc** [comment]
A work around solution to resize (width) with column

Conside the column structure to be below and than add a custom css class "w-two-one" which defined in theme css file:
<div class="wp-block-columns w-two-one ...">
    <div class="wp-block-column">...</div>
    <div class="wp-block-column">...</div>
</div>

In the theme CSS, something like:
.wp-block-columns.w-two-one {}
.wp-block-columns.w-two-one .wp-block-column { flex-basis: 33.3%; margin-left: 0; }
.wp-block-columns.w-two-one .wp-block-column:first-child { flex-basis: 66.6%; }

**Comment by bkline** [comment]
> I am closing this issue in favor of #6048 which I believe should cover this issue once a decision has been made there.

Unfortunately, that ticket has been closed without addressing this issue.

**Comment by bkline** [comment]
How do I reopen this issue?

**Comment by gbwashleybrown** [comment]
This still is an issue?

**Comment by ZebulanStanphill** [comment]
@gbwashleybrown Not in the latest version of Gutenberg plugin. (The changes won't come to WordPress core until WordPress 5.3.)

**Comment by ZebulanStanphill** [comment]
@gbwashleybrown The issue was fixed a little while ago. You can change column widths in the latest version of the Gutenberg plugin. The changes won't come to WordPress core until WordPress 5.3, though.

**Comment by My1** [comment]
okay. well I am on 5.3.2 and while I do get a few options for cols when creating them there's still 2 small issues:
1) you dont have a lot of control over the sizes
2) I have found no way to change the size after the fact

**Comment by vladoa** [comment]
One issue I have with the columns is that if I choose to have 4 columns, there is no way for me to set the following:
25/50/50/25

Every time I set the middle two columns to specific width (let's say 50), Gutenberg recalculates the width of the rest of the blocks, making it impossible to adjust the values to all 4 columns.

Second thing is that they look horrible within the editor. Gutenberg is far too narrow for managing these columns. If I choose to have 6 columns then it gets ridiculously narrow. A popup to adjust columns would be an elegant solution to this problem.

**Comment by My1** [comment]
well 25/50/50/25 is not something you can really do percentage-wise as that is bigger than a hundred.

for a 1/2/2/1 ratio you rather have 17/33/33/17

**Comment by vladoa** [comment]
Sorry, bad math. I updated my comment. But you get what I mean, right?

**Comment by ZebulanStanphill** [comment]
@vladoa There is currently a PR that would fix the issue you are describing: #19515.
