### ISSUE TITLE
Blocks inserted in Columns Block shouldn't have Wide & Full options/icons

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7316]
When you insert a Block such as an image block, into the Columns block, it retains the Wide & Full icons. These icons make no sense in this context and currently break the layout by overlapping other columns.

**To Reproduce**
1. Insert Columns block
2. Insert Image block in first column
3. Insert paragraph block in second column
4. Add image to Image block
5. View the Wide/Full icons on the image block

![gutenberg_widefulliconsincolumnsblocks](https://user-images.githubusercontent.com/2078245/41462209-6d309966-70d5-11e8-9c69-68811963df0f.gif)

_Gutenberg 3.0.1
Firefox Quantum 60.0.2 (64-bit)
macOS Sierra 10.12.1_

**Comment by nerrad** [comment]
This is still a relevant issue in master as of writing this comment.

**Comment by paaljoachim** [comment]
Hey @maddisondesigns Anthony 

Testing using
Theme: Twenty Twenty One
Gutenberg plugin 9.8
WordPress 5.6

Added a Columns block with 3 columns. Added image to the first column and text into the next column.
Changed alignment of image to Full. Here is the result:

<img width="743" alt="Screen Shot 2021-01-22 at 17 25 37" src="https://user-images.githubusercontent.com/5323259/105517074-ddddf600-5cd6-11eb-9e63-5aae7bbf7957.png">

I will close the issue. If I am mistaken then please reopen.
