### ISSUE TITLE
Allow more URLs in link handler

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#732]
Right now our link filter is pretty strict about there being an actual link there. We should probably relax this a bit so at least you can insert a simple # anchor link.

**Comment by jasmussen** [comment]
Screenshot:

![screen shot 2017-08-18 at 09 55 14](https://user-images.githubusercontent.com/1204802/29449523-5dad61c6-83fb-11e7-8ce5-2a3d50034437.png)

**Comment by tfrommen** [comment]
What exactly should be allowed here?
Everything that can be URI-encoded, which is basically everything?
Only valid (partial) URIs?
Only absolute links as well as (relative) anchor links? What about relative links (e.g., `/contact`) then?

**Comment by jasmussen** [comment]
> What exactly should be allowed here?

WordPress currently allows anything. And since you could potentially have a specialized theme that allowed modern JS like "routes" like `contact` without any slashes, it seems like we should in fact allow anything.

**Comment by tfrommen** [comment]
Alright then. I will take care of that.

**Comment by mtias** [comment]
Closed by #2870.
