### ISSUE TITLE
ServerSideRender component should debounce the request

### ISSUE THREAD

**Issue by ivanlopez** [WordPress/gutenberg#7320]
**Describe the bug**
When using the new ServerSideRender component if you have a text control in the Inspector on each change event it sends a request to the Block API Endpoint without debouncing it. Also if one of your attributes is an array or an array of arrays or an array of objects it is not getting sent correctly to the REST API.

**To Reproduce**
1. Use the component that is found at this gist: https://gist.github.com/ivanlopez/3f415d805704e950a94ad62a4dd75981
2. After you install and add the component to the editor open your dev tools to the network tab in your browser.
3. Start typing in the text field in the inspector and you'll see that every change event fires a request to the Block API endpoint without debouncing or canceling the previous request.
4. Click on the buttons in the Inspector and you'll see that the response you get is not what you would expect. For a simple array you'll get the an array with a single value of all the items you sent. For nested array you will get all the items in one nested array. Finally for an array of objects the data is getting sent as [object Object]so the API can't process that request.

**Expected behavior**
I would expect that when using ServerSideRender request would get debounced. I would also expect that if you have an attribute with an array or an array of arrays or an array of objects that the ServerSideRender component would send the data correctly to the block API endpoint.

**Screenshots**
![serversiderenderingtextcontrol](https://user-images.githubusercontent.com/1428016/41472223-c8d32128-7083-11e8-8d81-e7e220b23cdf.gif)

![screen shot 2018-06-15 at 10 38 05 am](https://user-images.githubusercontent.com/1428016/41473768-38d97fe0-7088-11e8-8819-11f687d6910d.png)

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser Chrome
 - Version 66.0.3359.181

**Additional context**
- Gutenberg 3.0.1

**Comment by danielbachhuber** [comment]
> Also if one of your attributes is an array or an array of arrays or an array of objects it is not getting sent correctly to the REST API.

This is covered by #7086

**Comment by aduth** [comment]
Use-case with RangeControl mentioned in #10168.

**Comment by danielbachhuber** [comment]
> This can cause server issues, especially with changing TextControls being passed to SSR (because those are likely to change in quick succession as you type). Sort of a mini-DDOS, most applicable if you're on bad hosting.

Yeah, I saw this on a client project yesterday.

**Comment by notnownikki** [comment]
Picking this up.
