### ISSUE TITLE
Impossible to undo Convert to Blocks when post_content contains a core oEmbed link

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#7323]
**Describe the bug**
Clicking "Convert to Blocks" successfully converts classic editor content to blocks, and appears to add to the undo history, but clicking "undo" has no result.

In my testing this is caused by oEmbed lines in `post_content` pointing to WP posts.

**To Reproduce**
1. Create a post in the Classic Editor with a WordPress oEmbed link, e.g.…
```
My paragraph

https://www.chrisvanpatten.com/notes-from-wordcamp-halifax-2018

My other paragraph
```
2. Open the post in Gutenberg
2. Open the Classic Editor block's settings menu and select "Convert to Blocks"
3. Note that the Undo button is enabled
4. Try to click undo
5. See nothing happen

**Expected behavior**
Either this process should be "undoable" or the undo button shouldn't change its state.

**Screenshots**
![kapture 2018-06-15 at 16 26 29](https://user-images.githubusercontent.com/1231306/41485958-e8e77ab0-70b8-11e8-8e3f-e8cfcc8f5ed2.gif)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.5
 - Browser: Safari 11.1.1
 - Gutenberg Version: 3.0.1

**Comment by mcsf** [comment]
Related: https://github.com/WordPress/gutenberg/pull/6325#issuecomment-385968584

**Comment by mcsf** [comment]
@chrisvanpatten, thanks for the report.

I can't repro. Do you have content I can use to test this?

**Comment by chrisvanpatten** [comment]
@mcsf I did a bit more testing and I've narrowed it down. The client has WordPress oEmbed links in their `post_content`, e.g.

> My paragraph
> 
> https://www.website.com/2018/08/internal-link/
> 
> My other paragraph

If I remove those oEmbed lines from the `post_content`, conversion and undo work fine. With the oEmbeds, you can convert to blocks but not back the other way.

**Comment by mcsf** [comment]
That makes much more sense, thanks for checking!

**Comment by mcsf** [comment]
Closing in favor of umbrella issue #8119
