### ISSUE TITLE
[3.0.1] The "read more" block does not respond to "enter" despite being a single line block

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#7324]
**Describe the bug**
The "read more" block is a single line, so pressing "enter" does not create a second line within that block.

However, the current behavior is that when "read more" block is in focus, the "enter" key doesn't do anything.

**Expected behavior**
Pressing "enter" while within a "read more" block should open a new paragraph block.

**Comment by thefifthisa** [comment]
Hey @GlennMartin1, I'm new here and would love to work on this!

**Comment by GlennMartin1** [comment]
@thefifthisa 
Go ahead!

**Comment by Soean** [comment]
@thefifthisa Have you made some progress or do you need help with this issue?

**Comment by thefifthisa** [comment]
@Soean I'm so sorry but I don't think I'll be able to contribute right now. Hopefully someone else can pick this up?

**Comment by davewarfel** [comment]
I noticed this today as well, and wanted to include a quick screencast with keystrokes to illustrate the issue.

![gutenberg-read-more-enter-new-block](https://user-images.githubusercontent.com/783021/44171286-1bb2ab00-a097-11e8-9f45-1e97822fae86.gif)

**Screencast:** https://www.dropbox.com/s/a8qogt061x7kmce/gutenberg-read-more-enter-new-block.mp4?dl=0
