### ISSUE TITLE
CSS custom property name in a `style` attribute becomes hyphenated in the save version of a block

### ISSUE THREAD

**Issue by laras126** [WordPress/gutenberg#7326]
**Describe the bug**
When defining a CSS custom property in a `style` attribute, the property name becomes hyphenated in the save version of the block.

**To Reproduce**

1. Register a block with a custom property defined in the style attribute:
```
registerBlockType('cgb/block-var-test-block', {
  title: 'Testing',
  icon: 'carrot',
  category: 'common',
  
  edit(props) {
    return (
      <p className={props.className} style={{ '--pBgColor': 'skyblue' }}>Backend should be skyblue</p>
    )
  },
 
  save(props) {
    return (
      <p className={props.className} style={{ '--pBgColor': 'peachpuff' }}>Frontend should be peachpuff</p>
    )
  }
});
```

2. This code for `style.scss`, to be loaded on both the editor and frontend:
```
.wp-block-cgb-block-var-test-block {
  background-color: var(--pBgColor, green);
}
```

3. Add new "Testing" block and save.
4. View the block on the frontend, and the inline custom property name will be converted to `p-bg-color`. 

**Expected behavior**
The custom property name should be `--pBgColor` on the frontend, as it is in the edit version of the block.

**Desktop:**
 - OS: Mac
 - Browser: Firefox 60.0.2

**Additional context**
- Gutenberg v3.0.1
- Reviewed with @noisysocks at WordCamp EU 🙌

**Comment by noisysocks** [comment]
Thanks for going into detail @laras126! This is an excellent bug report 🙂
