### ISSUE TITLE
WordPress 5.0 and WordCamp Europe

### ISSUE THREAD

**Issue by sylvaincordiere** [WordPress/gutenberg#7328]
Is there any information given by Matt's talk at WordCamp Europe  on the state of Wordpress 5 and gutenberg.
Is it planned for 2018 or the begining of 2019 ?

**Comment by chrisvanpatten** [comment]
I don't believe the talk has been posted (and I also expect this ticket will be closed before it does get posted 😬) but he said that the aim is to mark Gutenberg as feature complete this month, get the "Try Gutenberg" callout in a point-release in early July, with the _potential_ for WordPress 5.0 "as soon as August," but there were no firm deadlines.

**Comment by mrleemon** [comment]
According to Matt, in August at the earliest:

https://www.youtube.com/watch?v=7XzPPnHGp_0

**Comment by sylvaincordiere** [comment]
Thanks to both of you
