### ISSUE TITLE
Keyboard text selection issues when caret is positioned at start or end of text

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#7333]
### Describe the bug
When you position the text caret at the start or end of a text element (I _believe_ all RichText instances; I've confirmed it in the Paragraph, List, Heading, Quote, and Pullquote blocks), and then attempt to use keyboard selection, you are only able to select in one direction.

On macOS, this occurs whether you're using the keyboard selection per-character shortcut (<kbd>Shift+Left Arrow</kbd> or <kbd>Shift+Right Arrow</kbd>) or the keyboard selection per-word shortcut (<kbd>Shift+Option+Left Arrow</kbd> or <kbd>Shift+Option+Right Arrow</kbd>).

I've tested on a few completely isolated WordPress installs (no shared plugins or anything) to be sure it wasn't anything specific to the sites, and was able to reproduce in all cases.

### To Reproduce
1. Create a paragraph block
2. Type content
3. Place your text caret at the end of the content
4. Press <kbd>Shift+Left Arrow</kbd> or <kbd>Shift+Option+Left Arrow</kbd> to select some content
5. Press <kbd>Shift+Right Arrow</kbd> or <kbd>Shift+Option+Right Arrow</kbd> with the intention of de-selecting content
6. Note that the selection area does not change

This works in reverse as well, if you place your caret at the start of a paragraph block and try to select forward and back.

### Screenshots
_You want GIFs? I've got GIFs!_

![recording-48](https://user-images.githubusercontent.com/1231306/41503485-40070150-71ac-11e8-84dc-648f04566059.gif)

![recording-49](https://user-images.githubusercontent.com/1231306/41503491-74580288-71ac-11e8-8aa7-9939f3068a00.gif)
(Not sure why my screen recorder didn't capture it, but trust me that I was pressing <kbd>Shift+Right Arrow</kbd> and <kbd>Shift+Left Arrow</kbd>, not just the arrow keys alone.)

### Expected behavior
You should be able to select in multiple directions no matter where your text caret starts, as in this example from TextEdit.app:

![recording-50](https://user-images.githubusercontent.com/1231306/41503517-ec6377da-71ac-11e8-9d43-91e1a1a27cd3.gif)

### Desktop:
 - OS: macOS 10.13.5
 - Browser: Chrome 68.0.3440.25 and Safari 11.1.1
 - Version: Gutenberg 3.0.1

**Comment by mcsf** [comment]
@chrisvanpatten, is this still an issue after the recent writing flow improvements? If so, please close. Thanks!

**Comment by chrisvanpatten** [comment]
@mcsf I can reproduce in 3.2. I don't have access to a build from `master` at the moment but if it's possible it's been fixed in master I can get one spun up to test.

**Comment by mcsf** [comment]
@chrisvanpatten, I lost your reply in the notification noise. :) It's been a few releases; could you check now? Thanks!

**Comment by chrisvanpatten** [comment]
@mcsf no worries — it does appear to be resolved! 🎉
