### ISSUE TITLE
Converting blocks lose anchor tags

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#7335]
**Describe the bug**
When converting a classic page to blocks, any existing anchor tags on titles are lost. This is despite the block and the original classic content both utilize the `id` attribute to provide the anchor tag.

**To Reproduce**
1. Create a post in the classic editor
2. Edit the HTML of the post and add an anchor tag using the `id` attribute on a heading.
3. Save the post and leave
4. Open the post in Gutenberg
5. Choose to convert the post to blocks

**Expected behavior**
Elements that are supported in Gutenberg should be retained when converting, as an aside  would it be an idea to not strip non-supported attributes but rather leave in the HTML to avoid breaking content?

**Additional context**
Gutenberg 3.0.1 (running on WordPress.org, in case there's something special introduced there?)

**Comment by danielbachhuber** [comment]
Related #6581 #6096 #4498

**Comment by danielbachhuber** [comment]
@WordPress/gutenberg-core Do we want to handle this with an abstraction similar to `className`, or should we simply add this feature to the blocks that it's relevant to? And, in either case, what should the attribute name be?

**Comment by brandonpayton** [comment]
It appears #8124 is meant to address this issue.

**Comment by Clorith** [comment]
#8124 only allows ID attributes, what about other attributes that users may have previously added manually for plugins and such for example?

We shouldn't be stripping anything when converting, if we do it should be a migration instead, and it should be clear that attribute data may be lost if it does not adhere to our pre-defined standards.

**Comment by brandonpayton** [comment]
👍 You're right. It just addresses a specific instance of this issue. Thanks for correcting.

**Comment by pento** [comment]
#8124 fixes the issue with the `id` attribute, #6878 continues the broader conversation of how to handle random attributes that we don't explicitly support.
