### ISSUE TITLE
gutenberg_parse_blocks( $post->post_content ) takes 135 ms to execute

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#7337]
```
$start = microtime(true);
$blocks = gutenberg_parse_blocks( $post->post_content );
$time_elapsed_secs = microtime(true) - $start;
echo $time_elapsed_secs * 1000;
```

And every time I call this function this time is increased, for example 5 &times; 135 ms = 675 ms.

Is there some `$wp_query->parsed_blocks` or something available?

**Comment by manake** [comment]
I'm using this until some official response arrives:

```
function xxx() {
	global $post;
	$GLOBALS['parsed_blocks'] = gutenberg_parse_blocks( $post->post_content );
}
add_action( 'wp', 'xxx' );
```

I found that `pre_get_posts` is too early and `posts_selection` is something unknown to me so I used `wp` action.

https://codex.wordpress.org/Plugin_API/Action_Reference

**Comment by katerlouis** [comment]
I'm curious what gutenberg_parse_blocks is; I can't find an explanation on the webz.

**Comment by danielbachhuber** [comment]
@manake Can you share the contents of `$post->post_content` in a Gist or similar?

**Comment by manake** [comment]
I tested it with several `$post->post_content`. The execution (parsing) time increases in direct proportion to the content's length.

The following gives me roughly 35 ms (PHP 7.0.4, i7, Windows 10):

```
$blocks = gutenberg_parse_blocks( '<!-- wp:columns {"columns":3} -->
<div class="wp-block-columns has-3-columns">
	<!-- wp:heading {"layout":"column-1"} -->
	<h2 class="layout-column-1">Test</h2>
	<!-- /wp:heading -->

	<!-- wp:paragraph {"layout":"column-1"} -->
	<p class="layout-column-1">TEst</p>
	<!-- /wp:paragraph -->

	<!-- wp:heading {"layout":"column-2"} -->
	<h2 class="layout-column-2">Test2</h2>
	<!-- /wp:heading -->

	<!-- wp:paragraph {"layout":"column-2"} -->
	<p class="layout-column-2">testsetestsetsetsetsetset</p>
	<!-- /wp:paragraph -->

	<!-- wp:heading {"layout":"column-3"} -->
	<h2 class="layout-column-3">Kjsjdf</h2>
	<!-- /wp:heading -->

	<!-- wp:paragraph {"layout":"column-3"} -->
	<p class="layout-column-3">testsetsets</p>
	<!-- /wp:paragraph -->
</div>
<!-- /wp:columns -->' );
```

Out of curiosity I tried it on PHP 7.1.18, Ubuntu 16.04.1, Intel c2750 and the value oscillates around 10.068893432617 ms while 5 copies raise it to 49.859046936035 ms.

My issue is already somewhat solved (with a workaround) but since WordPress is already running `gutenberg_parse_blocks` once and my theme/plugin runs `gutenberg_parse_blocks` again then I thought I'll ask if perhaps WordPress exposes the result somewhere (if this is such a time-consuming function it was worth asking)?

**Comment by danielbachhuber** [comment]
Thanks for the additional detail, @manake. I've filed this as a bug for now, to at least get some visibility on it before too long.

> My issue is already somewhat solved (with a workaround) but since WordPress is already running `gutenberg_parse_blocks` once and my theme/plugin runs `gutenberg_parse_blocks` again then I thought I'll ask if perhaps WordPress exposes the result somewhere (if this is such a time-consuming function it was worth asking)?

I'm not convinced saving the results to some global is the appropriate technical solution. It seems more valuable and important to solve the performance issue.

Related #5967 #5572

**Comment by mcsf** [comment]
@manake: Thanks for the report. #8083 recently introduced an all-new parser implementation which should greatly improve performance. I expect this issue to thus be resolved, but feel free to reopen if you're not satisfied.
