### ISSUE TITLE
Right aligned content not parsed correctly

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#735]
The following default content does not show correctly in the editor.

```html
<!-- wp:core/text -->
<p style="text-align:right;">... like this one, which is separate from the above and right aligned.</p>
<!-- /wp:core/text -->
```

**Comment by aduth** [comment]
What is incorrect specifically?

**Comment by iseulde** [comment]
I don't see this block being right aligned.

**Comment by aduth** [comment]
Hmm, it's aligned correctly for me. What browser / version are you using?

![image](https://cloud.githubusercontent.com/assets/1779930/25861239/13762086-34b2-11e7-8cef-00cc412e2ce3.png)

**Comment by iseulde** [comment]
Chrome

<img width="692" alt="screenshot 2017-05-09 18 31 51" src="https://cloud.githubusercontent.com/assets/4710635/25861734/d88255ba-34e5-11e7-80c0-19fd6857a244.png">

I'll have a closer look then if it's just me.

**Comment by aduth** [comment]
@iseulde Is this still an issue you're observing?

**Comment by iseulde** [comment]
This seems to have been fixed in the last few days.
