### ISSUE TITLE
Link to: support for Image Block

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#7354]
**Is your feature request related to a problem? Please describe.**
Sorry, but it is hard for me to find related discussions, so if this has been discussed previously, please point me to the issue.

Background:
I just had a theme support issue for my theme where a user literally had organized his site around image attachment pages. I think for some users, attachment page views of images are very important.

So while checking this out, I discovered that the Link to: field when inserting an image as in the classic editor is not supported for the standard Image block. I assume this must have been an intentional decision, but it seems that it will leave many people who count on that feature out in the cold.

Any chance of adding the Link to: to the image?

**Comment by danielbachhuber** [comment]
Thanks for the report, @weavertheme. This issue is already tracked with #5309
