### ISSUE TITLE
How to use server requests in blocks edit()?

### ISSUE THREAD

**Issue by katerlouis** [WordPress/gutenberg#7358]
### The use case
A dynamic author block which has only one dropdown, containing all users who are able to post and therefor are authors. 

Since there is no way (.. I know of ..) to access all users in js without some kind of server request, I went with an ajax call:

```jsx
// index.js of my plugin
let users; 
$.post(ajaxurl, {
	action: "foobar_blocks_get_all_users",
}, function(response) {
	users = JSON.parse(response)
})

registerBlockType("foobar-blocks/author", {
   ...
    edit() {
        // `users` is, expectedly, still undefined on first render, since the ajax call is slower then reigsterBlockType
        ...
```

```php
// index.php of my plugin
add_action("wp_ajax_foobar_blocks_get_all_users", function() {
	$users = get_users(array(
		"fields" => array("id", "display_name"),
		"who" => "authors"
	));

	echo json_encode($users);
});
```

As expected, `users` is still undefined when `edit()` is called. Delaying `registerBlockType` via promises or simple feels like a really bad idea. 

## My question in general now
How **exactly** can I access posts, users, attachments etc. in `edit()` properly?
Please provide a barebones example on how to approach this, since I am heavily confused from ReST API, ServerSideRenderer, withAPIdata, Ajax– and the "wasteland of docs" only give little pieces which confuse me even more

## Suggestion for the Handbook
Describing the differences in Wordpress' use of ReST API, compare this to when to use ServerSideRenderer, or what withAPIdata() is all about with more details. What I found so far didn't make me reach my goal.

_PS: sorry, but I can't hide my frustration. I feel so lost.. practically no reliable docs available. This thing is a huge puzzle making me run in circles. How should people start migrating to Gutenberg this way? Result: they don't. Wordpress Stackexchange, discord server, IRC Channel, several forums; no one there to give reliable information; Sure.. there are articles and talks about Gutenberg, but 80% feel out of date since Guterberg 3.0 was released. There is no conversation, no exchange. Picking up breadcrumb after breadcrumb; hunting in source code for examples in readmes; desperately searching 800 issues here, write my own just to find out later on somebody (surprise surprise) had the same issue, just phrased it so much different.._

 – I truly believe once the docs are truly centralized, more complete and stronger in general, devs using gutenberg will increase and the snowball starts rolling. Right now.. there isn't even any snow :'(

**Comment by youknowriad** [comment]
The main way to access remote data in `edit` functions is through the REST API and it can be achieved in several ways:

 - Use the `@wordpress/data` module and its selectors. Details about this are available on the handbook: https://wordpress.org/gutenberg/handbook/packages/packages-data/  (see `withSelect`HoC)

The Core Data packages exposes a list of selectors you case. See an example here with `getAuthors` https://wordpress.org/gutenberg/handbook/packages/packages-core-data/#example

This Page also lists all the available selectors https://wordpress.org/gutenberg/handbook/packages/packages-data/packages-data-core/

 You can also use `@wordpress/api-fetch` directly in your React's lifecycle hooks.

**Comment by youknowriad** [comment]
I'm closing, Feel free to open PRs to improve the documentation.
