### ISSUE TITLE
Inserter adds new block at wrong position when there's focus

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#7360]
**Describe the bug**
When using the inserter at position A while editing a block at position B, the newly added block is inserted at position B, not A.

**To Reproduce**
1. Create 3 blocks
2. Click into the first one and maybe type something
3. Scroll to the bottom and click on the block inserter appearing after the last block
4. Try to insert a block and notice that it's inserted after block 1, not block 3.

**Expected behavior**

The new block should be added at the bottom since that is where I used the inserter.

**Video**

I uploaded a video of the bug here: https://cloudup.com/c47_hiEFhPo

**Additional context**

I'm using Gutenberg 3.0.1, WordPress 4.9.6 and Chrome 67 on macOS.

**Comment by jorgefilipecosta** [comment]
Closing this issue, as with the last changes to the sibling inserter I'm not being able to replicate this issue.
