### ISSUE TITLE
Inserter should "remember" which accordion panels are open/closed

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#7370]
Currently, every time you close and re-open the inserter, it "forgets" which accordion panels were expanded, and goes back to having everything closed except Most Used.

This behaviour is different from the Inspector, which remembers your accordion settings even if it's been open and closed or the page has been hard-refreshed.

It'd be great to see this behaviour standardised so your open accordion panels are remembered.

**Comment by hedgefield** [comment]
Yes please. It became annoying when I had to add a few shared blocks in a row. _Press insert, scroll down, expand panel, click block, repeat._ It gets old real fast.

**Comment by chrisvanpatten** [comment]
The inserter no longer uses collapsible panels, so this can be closed!
