### ISSUE TITLE
Error message isn't displayed on media upload failure

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#7372]
**Describe the bug**

When I try to upload an image and the upload fails for some reason at the server level, the generic `Error while uploading file %s to the media library.` error message isn't displayed.

![noerror](https://user-images.githubusercontent.com/36432/41604512-4c9e9286-7394-11e8-96e7-9a72d320ef23.gif)

**To Reproduce**

Include this snippet locally to force upload failures:

```
$force_upload_failure = function( $file ) {
	$file['error'] = 'This file upload has been forced to fail.';
	return $file;
};
add_filter( 'wp_handle_sideload_prefilter', $force_upload_failure );
add_filter( 'wp_handle_upload_prefilter', $force_upload_failure );
```

Attempt to upload a media file and see that there isn't an error message.

**Comment by danielbachhuber** [comment]
#6957 is a likely candidate.

**Comment by eriktdesign** [comment]
This still seems to occur when uploading files with a "Media & Text" block
