### ISSUE TITLE
Set a consistent and readable variable name for Array#reduce accumulator variable

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#7378]
I pointed out (in https://github.com/WordPress/gutenberg/pull/6782#discussion_r196217847) that we used `settersAcc` as the accumulator variable in some code and it wasn't obvious what it was from reading the code.

@aduth pointed out we are quite inconsistent with this variable: https://github.com/WordPress/gutenberg/pull/6782#discussion_r196538878

It'd be nice to go through and clean these up:

1. Make them consistent
2. Put `accumulator` in the variable name (maybe make that the variable name suffix all the time).

**Comment by jpjjulie** [comment]
Hey, 
Can I please try to work on this issue? I am new to open source and I thought I could contribute to Wordpress to start with. I will try and do my best to fix this issue. I am not sure if I can complete the entire fix but I would like to give it a try.

**Comment by lozinska** [comment]
Hi there! I'm new to GitHub and would like to work on this problem, but because I don't have enough experience me and my classmate decide to work together on this issue and split the work between 2 of us. Thank you

**Comment by gziolo** [comment]
I have just merged #17893 from @lozinska, I will have a look at another PR from @jpjjulie shortly.

**Comment by aduth** [comment]
In addition to changes within the current codebase, we should want to consider how to document the coding standard.

Possible locations:

- https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/
- https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md

Could make for a good topic of the [weekly JavaScript chat](https://make.wordpress.org/meetings).

**Comment by mburridge** [comment]
@gziolo what needs documenting here?

**Comment by gziolo** [comment]
It's all about using good names for variables, it's a very specific use case so I don't know if we need to explicitly document it. Example usage:

https://github.com/WordPress/gutenberg/blob/6b75d2e67dc2c5cf181fec2f477291b29b4abcf3/packages/blocks/src/api/registration.js#L342-L353

In other places, the names can be different, but they still contain the `accumulator` suffix, example:

https://github.com/WordPress/gutenberg/blob/6b75d2e67dc2c5cf181fec2f477291b29b4abcf3/packages/block-editor/src/components/font-sizes/with-font-sizes.js#L41-L49

We have local coding guidelines for Gutenberg at: https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/coding-guidelines.md

General coding standards for JavaScript have a very short section about naming conventions at https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#naming-conventions.

We could also close the ticket at this point.

**Comment by DaisyOlsen** [comment]
Thanks for the feedback, @gziolo. We'll close this for now. We can work to improve coding standard guidelines later if there seems to be a need.
