### ISSUE TITLE
Transition Body or Post class

### ISSUE THREAD

**Issue by aleksandargubecka** [WordPress/gutenberg#7383]
Hi,

First of all, thanks for doing great job with Gutenberg. 😄 

I'm creating a Gutenberg ready theme since there will be two types of posts, pages (Classic and Gutenberg ) it would be great if we have body or post class that let us know with type it is. Or even better it would be to have a is_gutenberg() function, so we can include JS for blocks and stuff. Let me know about your opinion on this?

Cheers  😄

**Comment by tofumatt** [comment]
I don't think there's a specific `is_gutenberg()` function needed; Gutenberg saves output as HTML, same as the classic editor. Your theme shouldn't need to differentiate content based on the editor used, as the editor will save HTML your theme can output normally.
