### ISSUE TITLE
Insert textlink to uploaded PDF document

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#7389]
In classic editor I can use "Insert media" button to create a text link to an uploaded PDF document.

I know I can find out the URL of each media element in the mediathek and copy it manually to create a link in Gutenberg, but that can not be the solution (compared with TinyMCE).
Maybe I haven't found the "new" insert mechanism for PDF (and other) links in Gutenberg?

**Comment by acidrums4** [comment]
On the "insert" button at the top left, look for "Common blocks" and select "File".

**Comment by mtias** [comment]
Like @acidrums4 mentions, there's a new "File" block that allows you to upload and link to a file quickly.
