### ISSUE TITLE
Youtube video embed block doesn't seem to work

### ISSUE THREAD

**Issue by designarti** [WordPress/gutenberg#7394]
Adding youtube URL in the videoblock. Shows the following code:

```
<figure class="wp-block-video aligncenter"><video controls="" src="https://youtu.be/OJfOsoUYPts"></video>
	<figcaption>iPhone X – does it still worth 1k?</figcaption>
</figure>
```
After insertion, both backend and frontend looks like this:

<img width="610" alt="screen shot 2018-06-20 at 10 43 52" src="https://user-images.githubusercontent.com/1475630/41647521-ebbb838c-7476-11e8-8998-0acfc1c40258.png">

And obviously doesn't work. Doesn't load.

Tried to insert both versions of the embeddable URL, youtube.com one and youtu.be one. Same output.

Using underscores theme from Automattic, with no code modifications. It is Gutenber 3.0.1. Running on MAMP Pro, on a Mac, regular setup, nothing wrong with the DE.

**Comment by tofumatt** [comment]
I just tried this locally and it worked:

![2018-06-20 11 01 07](https://user-images.githubusercontent.com/90871/41648519-7028fe68-7479-11e8-9674-504ba44920bb.gif)

Are you using the YouTube block or the Video block? If you insert a YouTube URL into the Video block it won't work, but the YouTube one will.

**Comment by designarti** [comment]
I was using the video block. Didn't know it won't work.
![giphy](https://user-images.githubusercontent.com/1475630/41650392-389bef3c-747e-11e8-873f-f8abcb6bb89a.gif)

**Comment by tofumatt** [comment]
I guess a cool enhancement to the video block would be detecting certain common urls and changing the block to YouTube, Vimeo, etc if detected. Could you file a feature request issue for that? :-)

- Matt (Sent from mobile)

**Comment by tofumatt** [comment]
Nevermind, looks like this is an existing issue already: #6824.

**Comment by a4jp-com** [comment]
I have a similar problem but when I try and upload an MP4 files from my server. The other thing that is annoying is when the URL goes missing when I click the edit button.
