### ISSUE TITLE
Columns implementation : why grid [only] and why columns are not wrapped/separated?

### ISSUE THREAD

**Issue by eddr** [WordPress/gutenberg#7396]
Hi

Why a grid was selected to be the base for columns? I think it can be limiting and uncomfortable in some situations, especially when responsiveness it needed. Also, the fact the columns are not wrapped with div or something could result in some unnecessary complications

For example:
1. A flexbox would allow automatic wrapping, making it much easier to handle responsiveness in most cases
2. with unwrapped columns (as it is now), inner elements are artificially aligned - this is an unwanted behavior many times.

I understand that with grid and "soft" columns the ability to order is maximized and that in some cases (probably not that many), it would be beneficial. 
However, it is not as advantageous for most as flexbox, so at least it might be a good idea to implement a choice between grid and flex + "hard" columns. Should be hard, after all and allow for a better control and less work.

**Comment by rickcurran** [comment]
Yep, a few people (including myself!) are keen for improvements here. This PR is worth following: #7234

**Comment by mtias** [comment]
There's multiple conversations around this. Closing so we can focus discussion in #7234
