### ISSUE TITLE
Core blocks: Stop using `withAPIData` for Latest Posts block in code and docs

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#7397]
Raised by @mrleemon in #7390:

> It might be a good idea to update the handbook section dedicated to building dynamic blocks cause it still makes reference to `withAPIData`:
>
> https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/

We should refactor Latest Posts block to use `withSelect` instead of `withAPIData` and update all docs to follow the same pattern. We are planning to deprecate `withAPIData`, so let's make sure it is no longer exposed in Gutenberg handbook.

More details on how to perform migration is shared in #7390.

There is also a known bug with a race condition inside `withAPIData` that has been around for quite some time. This is another reason why we should migrate our codebase sooner than later.

**Comment by mrleemon** [comment]
There are other references to `withAPIData` in addition to those in the Latest Posts block:

https://github.com/WordPress/gutenberg/blob/581522d66012035b160a67fbea41f044c5650ea2/editor/components/page-attributes/parent.js
https://github.com/WordPress/gutenberg/blob/247a6e07c22792769c4d397ad3a6d118dbc90a77/editor/components/post-taxonomies/flat-term-selector.js
https://github.com/WordPress/gutenberg/blob/247a6e07c22792769c4d397ad3a6d118dbc90a77/editor/components/post-taxonomies/hierarchical-term-selector.js

**Comment by gziolo** [comment]
Some of usages of `withAPIData` will be removed in #8088.
