### ISSUE TITLE
Possibility to filter $editor_settings in /lib/client-assets.php

### ISSUE THREAD

**Issue by dannydehaan** [WordPress/gutenberg#7400]
Hi,

When working on my dev environment, I don't want Gutenberg autosaves a post every 10 seconds. With a filter I could set the interval to 3600 or something, like this:

```
add_filter( 'gutenberg_editor_settings', function( $gutenberg_editor_settings ) {
    $gutenberg_editor_settings['autosaveInterval'] = 3600;

    return $gutenberg_editor_settings;
} );
````

**Comment by danielbachhuber** [comment]
Specific to autosave intervals, there was some conversation on https://github.com/WordPress/gutenberg/pull/6257#discussion_r188004797 about respecting the `AUTOSAVE_INTERVAL` constant. However, the product goal for Gutenberg is to produce a "Google Docs-like experience" (i.e. your document is always saved), so `AUTOSAVE_INTERVAL` may no longer be relevant.

> When working on my dev environment, I don't want Gutenberg autosaves a post every 10 seconds. 

Is there some practical implication of this, or is this simply a matter of personal preference?

**Comment by pento** [comment]
Per the discussion on #7400, there's already a method in place to change the editor settings, so I'm going to close this issue.
