### ISSUE TITLE
Support adding classes to BlockListBlock in editor.BlockListBlock filter

### ISSUE THREAD

**Issue by oxyc** [WordPress/gutenberg#7405]
**Is your feature request related to a problem? Please describe.**

I'm creating a plugin that adds support for background colors to all blocks.

**Describe the solution you'd like**

It would be useful if there was a separate property for the [`wrapperClassName`](https://github.com/WordPress/gutenberg/blob/09f9334e4009119cd1d71d9f3b39ea290456d442/editor/components/block-list/block.js#L444:LL452) where you can extend the list. For example:

```js
		const wrapperClassName = classnames( 'editor-block-list__block', {
			'has-warning': ! isValid || !! error,
			'is-selected': shouldAppearSelected,
			'is-multi-selected': isMultiSelected,
			'is-hovered': isHovered && ! isEmptyDefaultBlock,
			'is-shared': isSharedBlock( blockType ),
			'is-hidden': dragging,
			'is-typing': isTypingWithinBlock,
                        [ this.props.wrapperClassName ]: !! this.props.wrapperClassName,
		} );
```

**Describe alternatives you've considered**

At the moment the only way is to apply classes is to override `className` through `wrapperProps` but then you need redefine all the above classes making it very unstable.

What I currently opt for is providing the classes `data-*` attributes like [align](https://github.com/WordPress/gutenberg/blob/f95b2d5b952e7a495128d6cb5ca90cc42cf4e169/editor/hooks/align.js#L107) does but that means that themes need additional styling rather than just `has-*-background-color`.

**Comment by 2one2** [comment]
I agree, styling with data attributes is not the best approach.

My proposed solution:

[wrapperClassName](https://github.com/WordPress/gutenberg/blob/09f9334e4009119cd1d71d9f3b39ea290456d442/editor/components/block-list/block.js#L444:LL452)
```javascript
const editWrapperClassNames = blockType.getEditWrapperClassNames( block.attributes ) || '';

const wrapperClassName = classnames( 'editor-block-list__block', {
	'has-warning': ! isValid || !! error,
	'is-selected': shouldAppearSelected,
	'is-multi-selected': isPartOfMultiSelection,
	'is-hovered': isHovered && ! isEmptyDefaultBlock,
	'is-shared': isSharedBlock( blockType ),
	'is-hidden': dragging,
	'is-typing': isTypingWithinBlock,
        editWrapperClassNames,
} );
```

Block Configuration
```javascript
getEditWrapperClassNames( attributes ) {
	const { color } = attributes;
	if ( 'light' === color ) {
		return [ 'color-light', 'background-dark' ];
	} else {
		return 'color-dark';
	}
},
```

**Comment by chrisvanpatten** [comment]
@aduth also proposed another idea which I really like in this comment: https://github.com/WordPress/gutenberg/pull/7841#issuecomment-406319849

**Comment by youknowriad** [comment]
The `BlockListBlock` supports a `className` prop now, so this is possible now. Thanks.

**Comment by mahdiyazdani** [comment]
@youknowriad Would you mind clarifying in which version `className` prop has been added?
