### ISSUE TITLE
Trash icon disappears on aligned Embed Block

### ISSUE THREAD

**Issue by modreness** [WordPress/gutenberg#7406]
**Describe the bug**
I think there is maybe problem with aligning embeded elements in gutenberg? When I set align to left or right, I can not remove embeded element, I need to set again on center, and after that I have option to remove element.

**To Reproduce**
1. Go to 'Add block'
2. Click on 'Embeds' and select one from list (facebook, youtube  etc...)
3. Click on position icon: 'Align left' or 'Align right'
4. There is no trash icon. Trash icon dissapear. 

**Expected behavior**
Trash Icon need to be visible.

**Screenshots**
Trash icon dissapeard:
![trashicondissapear](https://user-images.githubusercontent.com/17008589/41657098-7fb8b09e-7492-11e8-8569-a797a2a5cd29.jpg)

Trash icon visible on center align:
![trashiconvisible](https://user-images.githubusercontent.com/17008589/41657099-7fdb49ba-7492-11e8-846d-3175b4aa9f13.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Chrome, Firefox]

**Comment by karmatosed** [comment]
I can reproduce this thanks for reporting.

**Comment by mtias** [comment]
I think this would be superceded by #7216.
