### ISSUE TITLE
Quotes keyboard navigation and manipulation is confusing

### ISSUE THREAD

**Issue by koke** [WordPress/gutenberg#7412]
There are a number of issues when you try to edit quotes with the keyboard.

As in the case of paragraphs, I would expect a double enter to trigger a new block (quote or now).

![quotes-1](https://user-images.githubusercontent.com/8739/41665103-78651002-74a7-11e8-957f-d87518d532b0.gif)

This doesn't work either when trying to split a quote in two

![quotes-2](https://user-images.githubusercontent.com/8739/41665136-8c115b74-74a7-11e8-8dfa-acf938ae710d.gif)

Trying to merge quotes doesn't work either, as pressing backspace at the beginning of the second quote just move the cursor (inexplicably) to the beginning of the previous quote, instead of combining the two quotes.

![quotes-3](https://user-images.githubusercontent.com/8739/41665172-a9ad157e-74a7-11e8-916e-c09324a61b4f.gif)

When you try to select, you can do it one character at a time, but if you press shift-down to try to select the whole quote, it will just move the cursor.

![quotes-4](https://user-images.githubusercontent.com/8739/41665246-ced56d88-74a7-11e8-88b5-34c7a5a26ff2.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 11

**Additional context**
- Tested with Gutenberg 3.0.1

**Comment by draganescu** [comment]
As of Gutenberg 7.9.1 part of the things described here are partially solved:

1) Pressing Enter twice in a quote takes the cursor out of the quote
2) Pressing backspace from a quote following another quote will merge the two and keep the cite of the lowest one
3) Selecting with keyboard has been improved and pressing arrow down while selecting does not move the cursor to the cite anymore, but selects the whole quote instead.

@koke could you re-test and update the issue accordingly or close it if the new behavior is good enough?

**Comment by koke** [comment]
Yes, everything reported seems to work nicely in 7.9.1 🎉
