### ISSUE TITLE
RTL: alignment buttons don't work as expected

### ISSUE THREAD

**Issue by azaozz** [WordPress/gutenberg#7415]
In RTL mode the alignment buttons should work in the same way they work in LTR mode. Currently when clicking Align Left, the content (tested with images) is aligned right. Seems to happen because the CSS that floats the block is run through `rtlcss` which changes `float: left;` to `float: right;`.

In addition there are other "oddities" with the buttons themselves and the tooltips. We should (probably) swap the places of Align Right and Align Left buttons, but the actual buttons should do as they say.

**Comment by yoavf** [comment]
This should be taken care of by #3911

**Comment by azaozz** [comment]
Right. Not sure why I couldn't find 3911 when searching... Closing as duplicate.
