### ISSUE TITLE
Post meta not saved if attributes not included in block JS

### ISSUE THREAD

**Issue by LABCAT** [WordPress/gutenberg#7425]
Not sure if this is a bug or if this expected behaviour but I think the post_meta should save if the attributes have been registered in PHP (and not in JS).

**To Reproduce**
1. Register a dynamic block with php containing at least one meta attribute (making sure post type supports rest and meta has been registered)
2.  Create the required JS with no attributes
3. Create new post enter
3. Save post

**Expected behavior**
Post meta is saved/updated

**Screenshots**

**Desktop (please complete the following information):**
 - windows 10
 - chrome
 - 67

**Additional context**
- Gutenberg version 3.0.1.

If I include the following in my block JS the meta value gets saved but if this is only included in PHP it does not:
`
attributes: {
            myMeta: {
              type: 'string',
              source: 'meta',
              meta: 'my_meta'
            }
          },
`

**Comment by youknowriad** [comment]
Is this still the case? I don't see why it wouldn't work.

**Comment by noisysocks** [comment]
_This issue was [raised](https://wordpress.slack.com/archives/C02QB2JS7/p1579755999207500) in a #core-editor triage session._

@LABCAT: Are you still running into this issue? If so, could you please provide some sample code which demonstrates the issue so that it's easier for testers to verify the bug report?

**Comment by LABCAT** [comment]
@noisysocks that was a very long time ago and I honestly can't remember what I was doing then. This could potentially be closed and reopened in the future if needed.

**Comment by noisysocks** [comment]
Thanks @LABCAT! Let's do that.
