### ISSUE TITLE
wp_reset_query() in a block doesn't work

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#7427]
```
function xxx() {
	$something = apply_filters( 'the_content', '<!-- wp:slug/something /-->' );
}
add_action( 'admin_enqueue_scripts', 'xxx' );

function render_callback_for_slug_something(){
	$recent = new WP_Query( $args );

	while ( $recent->have_posts() ) {
		$recent->the_post();
	}

	wp_reset_query();
}
```

With the above code present when I try to edit a `page` like:
http://localhost/wp-admin/post.php?post=111&action=edit

Then that URL redirects me to some other ID (of some `post`):
http://localhost/wp-admin/post.php?post=222&action=edit

In other words `wp_reset_query();` didn't restore `$post`? How can I make a custom query in a PHP render callback?

Gutenberg 3.0.1

**Comment by obenland** [comment]
Is your code snippet a fully working example? I'm having a hard time recreating this

**Comment by manake** [comment]
Yes, I reduced this to all necessary parts.

And yes, this definitely was happening and I remember debugging it down to the usage of `$recent = new WP_Query( $args );` and to not working `wp_reset_query();`. So, these two lines were causing this.

I don't have time to test this again now, if you believe this is not happening you can close this and I can reopen this later if it'll be happening.
