### ISSUE TITLE
Block "More" Menu: Final design proposal

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#7433]
Here's a mockup showing the latest iteration of the block's "More" menu:

![screen shot 2018-06-21 at 14 56 38](https://user-images.githubusercontent.com/1204802/41720523-9b8f23ee-7563-11e8-9531-29cbb808d3d6.png)

Compare to master:

![screen shot 2018-06-21 at 14 58 57](https://user-images.githubusercontent.com/1204802/41720545-afd44f8c-7563-11e8-8351-6f45cd293276.png)

Note that although the mockup uses Gridicons, we'll keep using Dashicons in the menus. It's also okay to keep or adjust the labels in implementation, depending on prior history. Finally, the shortcut combinations are suggestions only, and we should adhere to standards where available, and consider other conflicts, when choosing these. 

ToDo list:

- [x] Add "Insert Before" and "Insert After" icons to Dashicons
- [x] Add "Insert Before" and "Insert After" buttons, see https://github.com/WordPress/gutenberg/issues/7297
- [x] Add keyboard shortcut indicators
- [x] Add keyboard shortcuts
- [x] Adjust sorting order is a little different
- [x] Adjust padding to match

**Comment by jasmussen** [comment]
It was suggested we add space between the trash button, if we add that to the menu, and the other menu items. Here's a pattern for separators in the popout menus:

![screen shot 2018-06-21 at 15 51 39](https://user-images.githubusercontent.com/1204802/41723332-1b0ed9be-756b-11e8-9971-8c973c529f21.png)

**Comment by karmatosed** [comment]
This is a great iteration. I am not as keen on the inserting/adding but see the place for it so 👍 Let's try and get this in with the trash icon being there and a separator before it.

**Comment by mtias** [comment]
Padding between item (focus ring) and the popover also stands out.

**Comment by jasmussen** [comment]
CC: @talldan regarding keyboard shortcuts, I just updated this issue. I will make a separate PR for padding, and I'm going to create some Dashicons as well.

**Comment by jasmussen** [comment]
I've added pull requests to check a number of these boxes, and there's now also a PR to add the new icons in https://github.com/WordPress/dashicons/pull/311.

**Comment by talldan** [comment]
Thanks @jasmussen - really appreciate you looking at those separately.

**Comment by noisysocks** [comment]
What's left to do here?

**Comment by jasmussen** [comment]
Yay, it's done! Closing as such.
