### ISSUE TITLE
Show a single "This post has been modified externally" prompt, instead of many dialogs in each modified block

### ISSUE THREAD

**Issue by daniloercoli** [WordPress/gutenberg#7435]
There are situations where you modify a GB post in an external editor, making changes in more than one block of the post, that can result in many  "This block has been modified externally" prompts, one for each of the modified block.
To recover the whole document you need to tap on each single block.

Would be cool to have one single "This post has been modified externally" prompt, that will be shown on the screen when you re-open the post in Gutenberg. Tapping recover will try to recover all the blocks that has been corrupted by the external editor.

**Comment by draganescu** [comment]
I wonder if the current behavior isn't actually better as it offers a clearer perspective on what will be affected by the recovery?

**Comment by mapk** [comment]
Having the 1:1 relationship to see what's been changed conveys this more accurately. Let's close this one for now because the current solution works quite well.
