### ISSUE TITLE
Heading shortcuts with hashtags

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#7436]
**Describe the bug**
In the classic editor, we implemented heading shortcuts using hashtags, `##Title` would make a H2, `###Title` a H3 etc, and it converts to a heading once you provide a linefeed/return character.

In Gutenberg, we sort of have this, but it requires you to type the hashtags, then add spacing which converts the view into a heading block that you can then type into. Although some new flows must be expected with the introduction of the new experience, it would be nice if we could retain the previous behavior here (I only discovered this was still a thing when I accidentally hit space in testing).

**Additional context**
Gutenberg 3.0.1

**Comment by mtias** [comment]
Doing `#test` could also be considered a matcher for having inline hash-tags. I think the current experience with the space is a good baseline.

cc @iseulde for thoughts.

**Comment by Clorith** [comment]
It's worth noting that we don't (in the classic editor) have a hashtag shortcut for a single tag/h1 (this is intentional as a site should only ever have one primary heading).

**Comment by iseulde** [comment]
I'm fine with using enter/return for converting... I don't have a preference.

**Comment by youknowriad** [comment]
I'm personally leaning towards closing as this could create conflicts with plugins adding hashtags support. We could also imagine adding tags support built-in in the future. And hitting Enter should create a new paragraph instead.
