### ISSUE TITLE
Gallery Block: Add Multiple Styles

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#744]
Add multiple styles for laying out the gallery block.
Two initial styles are Tile (default) and Masonry layout. 
A potential additional style could be slideshow

See #317 and #740

**Comment by mtias** [comment]
I think slideshow should be a separate block.

**Comment by mrwweb** [comment]
Related: #783

**Comment by mtias** [comment]
We already implemented a tiled gallery design by default which is fairly flexible with cropping and columns.

**Comment by feeela** [comment]
> I think slideshow should be a separate block.

I though blocks would refer to the content. A slideshow in indeed a gallery, when speaking of the content. It is just presented in another form. In fact, there mustn't even be differences in the HTML, beside some data-* attribute to indicate, that a JS plugin should displya this gallery as a slideshow.

**Comment by mtias** [comment]
Blocks refer to what is meaningful to a user to discover and use. Different blocks can have the same HTML markup but different expectations and different UIs.
