### ISSUE TITLE
Preview doesn't work when revisions are turned off

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#7442]
**Describe the bug**
When revisions are turned off, the preview doesn't work.
The same behaviour occurs when revisions are limited to a number and you have reach the limit.

**To Reproduce**
1. Turn off revisions
1. Create a new post or make some changes to an existing one
1. Do not save the draft or update your post
1. Try to preview the post
1. See that you're stuck to "Please wait... Generating preview."

**Expected behavior**
The preview should be rendered.

**Desktop (please complete the following information):**
 - OS: macOS 10.3.5
 - Browser: Firefox 60.0.2

**Smartphone (please complete the following information):**

**Additional context**
- Gutenberg version 3.0.1

**Comment by danielbachhuber** [comment]
Related #7348
