### ISSUE TITLE
Tooltips disappear without clicking on them

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7457]
The new Gutenberg tooltips disappear without even clicking on them, which makes them less useful.

I edited a new page and after clicking on a block, a tooltip appeared. I then clicked outside of a block and the next tooltip appeared. When I clicked another block, the tooltip disappeared and none have returned since. I have no idea what the tooltips said because I didn't notice it until the second one appeared due to how they're styled, and then when I clicked somewhere, it disappeared completely without given me a chance to read it.

It's kind of pointless having a _See next tip_ link if clicking anywhere on the screen shows you the next tip regardless. Same goes for the dismiss/close icon. If the tips automatically close no matter where you click, then there's really no point in having this dismiss/close icon.

**To Reproduce**
1. Update to Gutenberg  3.1.0
2. Click on a block (and the first tip appears)
3. Click outside of a block (the second tip appears)
4. Click on another block (The tips disappear for good)

**Expected behavior**
Tips shouldn't disappear unless I click the Dismiss icon on the tip.
Tips shouldn't move onto the next tip unless I click the _See next tip_ link

_Gutenberg 3.1.0_

**Comment by danielbachhuber** [comment]
Related #7447

**Comment by talldan** [comment]
@maddisondesigns this looks to be resolved in #7447 (Pull request #7541), so will close this.
