### ISSUE TITLE
Tips: Option not untoggled when they are over

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#7458]
<img width="1028" alt="screen shot 2018-06-22 at 09 18 55" src="https://user-images.githubusercontent.com/1204802/41763073-5262422e-75fd-11e8-8555-1b804e02398e.png">

In the above picture, the onboarding has already finished, and all tips have been dismissed. The expected behavior here would then be for the checkbox to disappear from the "Show Tips" option. Because no further tips are being shown.

If you uncheck that option, then check it again, tips start over, this is also a way to reprocuce the bug:

- Uncheck the box, check it again
- Flip through tips
- Note that the check isn't gone when you're done

**Comment by tofumatt** [comment]
Does this happen only for edited posts (where the tips are not shown even if they haven't been viewed) or for new posts as well?

**Comment by tofumatt** [comment]
I've been writing NUX tests for this and I see why it is: we stop showing tips once there are no more available but we don't actually *disable* tips then.

If we disabled the tips after showing them all, newly added tips wouldn't show.

That said, I'd say the "show tips" button should probably be visibly unchecked once all tips have been shown even if `areTipsEnabled === true`. Clicking on it should restart the tips process. That seems like the right behaviour.

**Comment by noisysocks** [comment]
> That said, I'd say the "show tips" button should probably be visibly unchecked once all tips have been shown even if areTipsEnabled === true.

Yep, that sounds right. 

It's a little tricky though because we don't always know which tips exist ahead of time. Anyone can add a new tip by rendering `<DotTip>` somewhere on the page.

Feel free to take this issue, @tofumatt. I haven't started working on it yet. Up to you! 🙂

**Comment by tofumatt** [comment]
Cheers! I shall take it, though I didn't realise `DotTip`s worked like that so I'll have a look through. It looks like they might be a component that could use a bit of optimisation.

**Comment by tofumatt** [comment]
Ah, interesting! There's nothing in there about a tip being the "final" tip. But it looks like https://github.com/WordPress/gutenberg/blob/master/nux/components/dot-tip/index.js#L58 knows that there aren't anymore tips to show… I'll ping you if I need to brainstorm something 😄. Thanks 👍

**Comment by gziolo** [comment]
When merging fix for this issue, please make sure to unskip tests from #7874. They should help to prevent future regressions. Props to @tofumatt.

**Comment by jasmussen** [comment]
This appears to be a non issue now.

**Comment by timovanasten** [comment]
@gziolo It appears that the tests in #7874 are still skipped, but this issue is closed now. Is that intentional?

**Comment by gziolo** [comment]
I think that the issue was resolved but tests got out of sync and would have to be updated to make them work in addition to removing `.skip` part. This needs to be further investigated.
