### ISSUE TITLE
Missing : npm install @wordpress/plugins --save

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#7460]
Hi,

I'm following this documentation : https://github.com/WordPress/gutenberg/blob/e440ca26fbbcd6c6799822f2aadfc13f2b2b338b/packages/plugins/README.md and I'm getting the error below :

npm ERR! code E404
npm ERR! 404 Not Found: @wordpress/plugins@latest

Thanks!

**Comment by gziolo** [comment]
We merged the PR which moved this code to packages earlier this week and didn't get to the release process. It's still unpublished. It should be fixed next week. We might want to wait until Babel migration from 6 to 7 is finished: https://github.com/WordPress/packages/pull/136.

**Comment by gziolo** [comment]
We have a very similar issue with `@wordpress/dom` as noted here https://github.com/WordPress/gutenberg/issues/3955#issuecomment-394724086 by @nerrad.

I also explained in details what is the issue with the current configuration based on Babel 6 here: https://github.com/WordPress/gutenberg/issues/3955#issuecomment-395868572.

**Comment by phpbits** [comment]
@gziolo Just wanted to follow up this issue. Thanks!

**Comment by gziolo** [comment]
This one is already published. It will get another update after #7832 lands.
