### ISSUE TITLE
IE11: the "editor-warning" makes the horizontal scrollbar appear

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#7462]
On my Windows laptop, the default scaling (set in Control Panel > Display settings) is 125%. This is common on Windows laptop and it's the default, recommended setting. While this seems to not affect in any way how Gutenberg renders in other browsers, in IE 11 there's at least one minor edge case that makes the horizontal scrollbar appear.

Scrollbar in IE 11:

![screenshot 3](https://user-images.githubusercontent.com/1682452/41766639-db7a603c-7607-11e8-8933-a99b9df258a1.png)

Turns out in the current Gutenberg demo content, there's an image that is not rendered for some error (not sure why). Thus, the `BlockCrashWarning` is rendered:

![screenshot 4](https://user-images.githubusercontent.com/1682452/41766703-f8745440-7607-11e8-8418-ef53da260d34.png)

Haven't looked in depth at the CSS but for some reason this warning produces the horizontal scrollbar. Seems IE11 is not happy with a mix of flexbox, position absolute, and width properties. For example removing the width makes the horizontal scrollbar disappear:

![screenshot 5](https://user-images.githubusercontent.com/1682452/41766785-36126544-7608-11e8-844e-ebf16afd8d5b.png)

**Comment by brandonpayton** [comment]
This appears to still be an issue. To test, I rigged the Image block to error when rendering and loaded the demo content. A bit lower in the demo content there is a full-width image that results in a very wide warning. I loaded it in Edge, IE11, and Chrome and observed horizontal scrolling.

In each browser, the horizontal scrolling went away when the `data-width="full"` attribute was removed from the block div. The issue appears to be related to styles for full width.

Here's horizontal scrolling with a full-width warning in Chrome 69:
![full-width-warning](https://user-images.githubusercontent.com/530877/45664826-d08b1e00-bac2-11e8-90ba-4c89bf2ab84a.gif)

**Comment by tellthemachines** [comment]
Closing as I can no longer reproduce this issue in Windows 10/IE11 at default scaling ( the default on my laptop is 250% and I usually have it at 300% - and even that didn't trigger horizontal scroll 😅). `editor-warning`, now renamed to `block-editor-warning`, no longer has a width set so that must have fixed it.
