### ISSUE TITLE
Icons that are not dashicons don't get margins

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#7464]
![image](https://user-images.githubusercontent.com/548849/41768755-714467d4-760d-11e8-9f82-ec4e58f78f21.png)

On the "more menu", icons that are not dashicons don't get the margin right applied.
cc @jasmussen

**Comment by jasmussen** [comment]
Do we have any documentation with code examples on how to add plugins here? I have a gist bookmarked but wondering if official docs are up to date. Then I can jump in and fix this relatively easily.

**Comment by mtias** [comment]
@jasmussen you can install https://wordpress.org/plugins/dropit/
