### ISSUE TITLE
Permalinks editing has vanished

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#7467]
Right now on master the permalink editing has gone:

![2018-06-22 at 11 26](https://user-images.githubusercontent.com/253067/41772212-9903fae4-760f-11e8-94b7-f31bb327154a.png)

**Comment by tofumatt** [comment]
After `git bisect`ing things it looks like 1f9d0b4889e5fcc8e1faa6eb446cb9355d5807de is the culprit commit. Checking into things now and trying to fix it.

**Comment by aduth** [comment]
We should consider adding an end-to-end test to verify that permalinks editing works as expected.

**Comment by tofumatt** [comment]
Agreed, filed #7554.
