### ISSUE TITLE
Image with EXIF rotation uploaded incorrectly

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#7471]
**Describe the bug**
I uploaded an iPhone photo by dragging it into the image block, and it appeared upside down.

**To Reproduce**
1. Download [this image](https://drive.google.com/open?id=1WW0dwlQJUz8mOVRTZMk5i2_W4b7zRQsY)
2. Create a new image block
3. Drag the image into the block
4. See it upside down

**Probable cause**
I expect this is due to EXIF rotation in the image metadata. Many OSes and programs correct this on the fly to show the image with the correct rotation, but in the metadata technically it would still be rotated in the 'wrong' way. 

**Screenshots**
<img width="1213" alt="screen shot 2018-06-22 at 12 38 58" src="https://user-images.githubusercontent.com/6073772/41772733-170156ee-761a-11e8-9b64-a1287d3b28c4.png">

**Specs:**
 - MacOS High Sierra 10.13.5
 - Chrome 67.0.3396.87
 - Gutenberg 3.1 (tried on two different sites)

**Comment by jorgefilipecosta** [comment]
Hi @hedgefield, thank you for reporting this issue! It looks like the link you provided is private could you upload the image to a public URL?

**Comment by hedgefield** [comment]
Ah sorry, it's on the company GDrive so the link wasn't set up for outsiders :) Now it is!

I also have an addendum: I saved the photo again in Photoshop (which does show it rotated correctly when I open it, but often saving it via PS fixes any weird EXIF rotation). Then I dragged it into the image block again. Get this:

The thumbnail during the uploading is fine. _Once it's uploaded_ it's upside down again.

So I uploaded it manually to the media library for inserting:

The uploading thumbnail looks fine, but the image is still upside down afterwards (in the media library and inserted in the post). But, **when I press `Edit image` in the media library, _the image appears correctly rotated..._**

**Comment by jorgefilipecosta** [comment]
> The uploading thumbnail looks fine, but the image is still upside down afterwards

Yes, when the image is uploaded to the media library without Gutenberg, the problem also happens.
When the image is being uploaded in the image placeholder we temporarily set a blob url for the file without any kind change/parsing, and the browser renders it incorrectly. I think this problem is related with the way browsers handle this image and it is not something we can control on Gutenberg.

**Comment by jorgefilipecosta** [comment]
I'm closing this issue as I think it is not a Gutenberg problem but a browser/core problem as when images are uploaded in the classic editor or the media library the problem also happens. If my analysis is not correct, feel free to reopen the issue and we can look further.
