### ISSUE TITLE
Pasting text into paragraph converts spaces to non breaking spaces

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#7474]
**Describe the bug**

If you paste text into a paragraph block after a space, it will convert the space into the non breaking space. This breaks various link processing filters that look to auto link URLs, because now there's `&nbsp;` where there should have been a space.

**To Reproduce**

1. Copy `this is pasted text`
2. Create a new post
3. Type `this is typed text` with a trailing space
4. Hit ctrl+v (or cmd+v on those weird laptops you all seem to have ;) )
5. Immediately publish the post
6. View the published post, you'll see the content has `this is typed text&nbsp;this is pasted text`

**Expected behavior**

There should not have been any non breaking spaces.

**Comment by johngodley** [comment]
I think this is a TinyMCE bug.

If you create a paragraph and save `this is pasted text ` (note the trailing space), a `&nbsp;` also appears in the saved content.

Looking further when you add a trailing space in TinyMCE it seems a non-breaking space is actually added (`0xC2A0`). When you add another character this non-breaking space is replaced with a standard breaking space, and you carry on unaware.

What seems to be happening is that when you have a trailing non-breaking space and then paste more text, TinyMCE is not converting the non-breaking to breaking space. Your post then gets saved with the non-breaking space, and deep within the bowels of WordPress this is then converted into `&nbsp;` when the post is displayed.

TinyMCE and non-breaking spaces seems to be a bit of a [thing](http://blog.room34.com/archives/5075). There's even a report of the same problem [here](https://community.tiny.cloud/communityQuestion?id=90661000000ESWfAAO) (sadly unanswered).

@iseulde I think you may know more about how this works. Is this fixable in TinyMCE, or should we try and fix it within Gutenberg? (i.e. replace a trailing non-breaking space with a breaking one). Do we even want non-breaking spaces in a paragraph?

**Comment by iseulde** [comment]
@notnownikki I think #12166 should fix this issue. Could you confirm?

**Comment by ashucodiotic** [comment]
dasad
