### ISSUE TITLE
make it possible to append to Gallery block from media library

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#7475]
**Is your feature request related to a problem? Please describe.**
I switched an image block to a gallery block and wanted to add more images from my media library, but I only got the option to upload from my computer.

**Describe the solution you'd like**
I love that big `add more images` button that's been added to the gallery block, but we gotta also let people add it from the media library, or you have to remove the whole block and start over.

<img width="689" alt="screen shot 2018-06-22 at 13 28 05" src="https://user-images.githubusercontent.com/6073772/41774459-1f901876-7620-11e8-8c6f-a64abe40635e.png">

**Comment by mtias** [comment]
This already works if you click "edit gallery" and then "add to gallery" in the media modal.

See https://cloudup.com/cHNUcvaACaP
