### ISSUE TITLE
Block toolbar for multiple block selection is always shown in the top bar regardless of “Fix Toolbar to Top” setting

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#7485]
## The issue
When selecting multiple blocks, the block toolbar for that selection (which currently only ever contains the transform button) is always shown in the top bar, regardless of whether the <kbd><samp>Fix Toolbar to Top</samp></kbd> setting is enabled or not.

![image](https://user-images.githubusercontent.com/19592990/41788191-89629ed2-7610-11e8-85e6-927ba5c3dc2f.png)

## Reproduction steps
1. Make sure <kbd><samp>Fix Toolbar to Top</samp></kbd> is disabled.
2. Insert multiple Paragraph blocks.
3. Select multiple Paragraph blocks.
4. Notice that the transform button is shown in the top toolbar on both mobile and desktop, regardless of whether <kbd><samp>Fix Toolbar to Top</samp></kbd> is enabled or not.

## Expected behavior
The block toolbar for a multiple block selection should appear inline just like the block toolbar of a single block.

**Comment by mtias** [comment]
See #6128.

**Comment by SuperGeniusZeb** [comment]
@mtias Ah, thanks. I had forgotten about that issue. Should this issue be closed?

**Comment by mtias** [comment]
Yes, we can consolidate there.
