### ISSUE TITLE
transferring guten block project between WP installs fails

### ISSUE THREAD

**Issue by smlombardi** [WordPress/gutenberg#7487]
I created a Gutenberg block plugin on one computer in a local site using **create-guten-block**.  It works fine. I've been working on the project, and everything is fine.

I created a Git repo out of the plugin on computer 1 and [created a repo on Github](https://github.com/smlombardi/gutentest) and pushed it. 

On a second computer, running the same versions of Gutenberg and Wordpress, I cloned the repo into the `plugins` directory.

I ran `npm i` and activated the plugin on the Plugins page of admin. But the block does not load in the post editor. Instead I get an error:

`This block has encountered an error and cannot be previewed.`

Looking at the browser console, I see a React error 130, and when I look that up on the React site I get:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

Once again, please note this block works perfectly on computer 1, I can add it to any post or page and it works without error.  So there is something about the transfer via Github?  Normally I develop code on more than one Mac and use git to keep both computers in sync.

If it matters, I am using 10.13.5, Git Tower 3, git version 2.15.2 (Apple Git-101.1)

**Comment by ajitbohra** [comment]
@smlombardi whats the version of Gutenberg you are using?

**Comment by smlombardi** [comment]
I have tried in with 3.10 and the previous version.  Both work fine when you use create-guten-block and create a block directly into the plugins folder.   My problem is I cannot move one of these plugins to a different WP install.

**Comment by youknowriad** [comment]
Make sure to move the built files of the plugin when you move it to a different WP install. It seems that maybe a script is missing somewhere adding some components used by your plugin. Also make sure to ask in create-guten-block's repo on the steps to "deploy" your plugin using this tool.
