### ISSUE TITLE
Gutenberg 3.1 breaks Real Media Library (on Wordpress Media Library screen)

### ISSUE THREAD

**Issue by opicron** [WordPress/gutenberg#7488]
**Describe the bug**
With the latest Gutenberg update (3.1) the Wordpress Media Library does not load and shows an blank screen. I narrowed this down to an plugin I use which is no longer working after the update. The plugin in question is Real Media Library (RML). It fails with the following errors in the console:

ReferenceError: wpApiSettings is not defined: rml.js:1:47210
TypeError: window.rml is undefined: script.js:10:5
TypeError: e is undefined: load-scripts.php:277:1538

On the previous Gutenberg 3.0.1 (?) there was no issue. Also when I disable RML and use only Gutenberg 3.1 all works as intended.

**To Reproduce**
1. Install Gutenberg 3.1
2. Install Real Media Libary
3. Open Wordpress Media Library

**Expected behavior**
Expected behavior is to not interfere with other plugins.

**Screenshots**
I can upload the error or blank screen if requested.

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Firefox 

**Additional context**
I am not sure if this bug report belongs here or at Real Media Library. At the moment the issue report has been posted both to RML and Gutenberg.

**Comment by matzeeable** [comment]
Hi! The RML plugin developer here. I can not have a look at this atm, unfortunely. RML is using the global `window.wpApiSettings`. Has Gutenberg changed something for the global variable? My guess is that the `wpApiSettings` object is `wp_localize_script`'d after RML enqueues scripts.

Can you try to navigate to `wp-content/plugins/real-media-library/inc/general/Assets.class.php` and replace:

```php
$this->enqueueScript('real-media-library', 'rml.js', array('react-dom'));
```

with
```php
$this->enqueueScript('real-media-library', 'rml.js', array('react-dom', 'wp-api'));
```

**Comment by opicron** [comment]
Thanks, no rush to fix this-- I tried the adjustment but the error remains.

**Comment by opicron** [comment]
Adding the following code before enqeueScript solves the issue for now. Same as in the other issue thread.

`gutenberg_extend_wp_api_backbone_client();`
