### ISSUE TITLE
Chart block not displaying on frontend

### ISSUE THREAD

**Issue by dgwyer** [WordPress/gutenberg#7489]
**Describe the bug**

I've created a chart block using [Semiotic](https://github.com/emeeks/semiotic) which is a mature React based data visualisation library (used internally by Netflix).

The chart displays fine in the editor but only an empty SVG container is outputted on the front end. This was working in a previous version of Gutenberg when I tried it a few months ago.

I'm using WordPress 4.9.6, and Gutenberg 3.1.0.

**To Reproduce**

This is the block JS I'm using:

```javascript
/**
 * BLOCK: wpgo-ultimate-blocks
 *
 * Registering a basic block with Gutenberg.
 * Simple block, renders and saves the same content without any interactivity.
 */

//  Import CSS.
import './style.scss';
import './editor.scss';

const { __ } = wp.i18n; // Import __() from wp.i18n
const { registerBlockType } = wp.blocks; // Import registerBlockType() from wp.blocks

const { ResponsiveXYFrame, XYFrame } = Semiotic;
const frameProps = {
  title: "Scatter Chart",
  size: [500, 500],
  points: [
    { x: 500, y: 50 },
    { x: 250, y: 50 },
    { x: 50, y: 50 },
    { x: 0, y: 0 },
    { x: 100, y: 100 }
  ],
  xAccessor: "x",
  frameKey: "1", 
  yAccessor: "y",
  pointStyle: { fill: "red", stroke: "blue", strokeWidth: 5 },
  margin: { top: 50, left: 50, bottom: 50, right: 50 },
  axes: [{ orient: "left" }, { orient: "bottom" }]
};

registerBlockType( 'wpgo-plugins/test-block', {
	title: __( 'Semiotic Test Chart' ),
	category: 'common',
	keywords: [
		__( 'semiotic' ),
	],
	edit: function( props ) {
		return (
			<div className={ props.className }>
				<XYFrame {...frameProps} />
			</div>
		);
	},
	save: function( props ) {
		return (
			<div>
				<XYFrame {...frameProps} />
			</div>
		);
	},
} );
```

**Expected behavior**

The chart should display on the front end exactly as it does on the backend but only an empty SVG container is outputted.

Not sure what has changed in Gutenberg that is preventing the chart from displaying on the front end.

**Screenshots**
Here are screenshots of the editor and frontend.

![screen shot 2018-06-22 at 18 42 38](https://user-images.githubusercontent.com/1482075/41791098-9e44e62a-764c-11e8-9372-b1f1a62f0dc4.png)

![screen shot 2018-06-22 at 18 44 25](https://user-images.githubusercontent.com/1482075/41791113-ae0aa43c-764c-11e8-8f51-214fa8f3c8d8.png)

**Desktop (please complete the following information):**
 - Issue is the same on Windows and macOS
 - Using Chrome browser

**Comment by danielbachhuber** [comment]
Hi @dgwyer,

Can you share what content ends up stored in the database?

**Comment by dgwyer** [comment]
@danielbachhuber This is the 'post_content' db entry for the post.

```
<!-- wp:wpgo-plugins/test-block -->
<div class="wp-block-wpgo-plugins-test-block">
	<div class=" frame xyframe" style="background:none">
		<div class="frame-elements" style="height:500px">
			<div class="visualization-layer" style="position:absolute"><svg class="visualization-layer" style="position:absolute" width="500" height="500"><defs><filter id="paintyFilterHeavy"><feGaussianBlur id="gaussblurrer" in="SourceGraphic" stddeviation="4" colorinterpolationfilters="sRGB" result="blur"></feGaussianBlur><feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 34 -7" result="gooey"></feColorMatrix></filter><filter id="paintyFilterLight"><feGaussianBlur id="gaussblurrer" in="SourceGraphic" stddeviation="2" colorinterpolationfilters="sRGB" result="blur"></feGaussianBlur><feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 34 -7" result="gooey"></feColorMatrix></filter><clipPath id="matte-clip-undefined"></clipPath></defs></svg></div>
		</div>
	</div>
</div>
<!-- /wp:wpgo-plugins/test-block -->
```

**Comment by danielbachhuber** [comment]
@dgwyer Did you get this sorted out?

**Comment by dgwyer** [comment]
@danielbachhuber No this issue still persists. The chart SVG is missing markup, including all the data points, when saved to the db.

**Comment by danielbachhuber** [comment]
@dgwyer Are you able to save the SVG in the Classic Editor?

I suspect KSES may strip some SVG elements for security purposes. If this is the case, the user would need `unfiltered_html` capability, or you'd need to whitelist the elements with a filter.

**Comment by dgwyer** [comment]
I just pasted the whole chart SVG in the classic editor an no elements were stripped out. The whole SVG remained intact.

I'm testing as an administrator in the back end so I should already have `unfiltered_html` capability when saving editor content?

**Comment by dgwyer** [comment]
I just pasted in the SVG into the classic editor and no elements were stripped out.

I'm using the editor as administrator so I should already have the `unfiltered_html` capability?

**Comment by dgwyer** [comment]
I pasted in the SVG into the classic editor and no elements were stripped out.

I'm using the editor as an administrator so I should already have the `unfiltered_html` capability?

**Comment by designsimply** [comment]
@dgwyer since it has been several weeks since this issue last had activity, may I ask for a check one more time from you to find out if you are still having trouble even after updating to the latest version of WordPress? If the problem persists, I will see about learning to test the code you've provided or find some help for doing that.

**Comment by dgwyer** [comment]
Just tested again with latest version of WP and GB plugin. Still exactly the same behavior observed as before.

**Comment by designsimply** [comment]
Thanks for the check. I will do some research and loop back to you.

**Comment by DevinWalker** [comment]
I'm having the same issue but with ChartJS. Seeing if somehow I can find the fix.

**Comment by youknowriad** [comment]
I think this is related to the fact that `<XYFrame>` is probably not a synchronous component that renders its elements on first render. And that's a requirement for the `save` function. You can't use components that requires multiple re-renders in order to produce the desired markup.

I'm closing. Let me know if it doesn't answer your question.

**Comment by kennedy0527** [comment]
I'm having the same issue with HighchartJS too.
any way to fix it ?

**Comment by dgwyer** [comment]
I'm rendering the chart as React on the frontend now which gives me much more flexibility. I'm no longer constrained by the limitations of the `save` function.
