### ISSUE TITLE
bulk convert existing content to blocks

### ISSUE THREAD

**Issue by ptica** [WordPress/gutenberg#7490]
**Is your feature request related to a problem? Please describe.**
I've got existing content, I want to offer the client the editing comfort of Gutenberg,
I'm able to store the content using wp-cli, but for conversion into blocks I see no programmatic way
so I click and click and click in the ui

**Describe the solution you'd like**
`wp post create ./content.html --post_type=page --convert_to_blocks=true`

**Describe alternatives you've considered**
to enrich the content with the gutenberg block comments

**Comment by ajitbohra** [comment]
looks like a good enhancement for wp-cli command 
https://github.com/wp-cli/entity-command#wp-post-create

**Comment by ptica** [comment]
from my debugging is seems that the conversion is done in js, isn't it?
I'm not sure the wp-cli has a js runtime at hand.

**Comment by scottbasgaard** [comment]
Would be tricky but this would be amazing…
