### ISSUE TITLE
Movement controls are confusingly positioned for floating blocks

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#7492]
## The issue
When a block is using float alignment (the Image block, for example), the movement controls ~and ellipsis menu~ are not displayed in the right spot.
![image](https://user-images.githubusercontent.com/19592990/45633328-19ac8500-ba65-11e8-82e7-ca39ce48de44.png)

#9074 has fixed the ellipsis part of this issue (by moving the ellipsis to the toolbar), but the up/down movers are still affected.

## Related issues
- #6288
- #7491
- #7500

**Comment by chrisvanpatten** [comment]
This would be closed by #10085!

**Comment by ZebulanStanphill** [comment]
Closed by #10085, at the cost of now having no movement controls at all for floated blocks. It would be nice if there were keyboard shortcuts to do this. See #10455.
