### ISSUE TITLE
Tooltip focus info tooltip/popover appears below tooltip

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#7497]
**Describe the bug**
When tabbing through the buttons in the NUX tooltips on a fresh install, 

**To Reproduce**
1. Clear localStorage so NUX tips appear
2. Tab through until you are keyboard focused on the close/"x" in the tooltip's top corner
3. Observe the info is below the tooltip
4. Struggle to read the tooltip

**Expected behavior**
The tooltip appears above, well, the tooltip.

**Screenshots**
![2018-06-22 20 29 17](https://user-images.githubusercontent.com/90871/41795847-24a38d02-765c-11e8-9189-99112d1aa911.gif)

Happening in Gutenberg `master`.

**Comment by afercia** [comment]
@tofumatt seems to me #7562 already describes the same issue, unless I'm missing something.

**Comment by tofumatt** [comment]
Hehe, well, #7562 is newer I think... but yes, they're the same issue. Yours has more screenshots though, so I'll close this 😉
