### ISSUE TITLE
High CPU usage when simply typing in paragraph block

### ISSUE THREAD

**Issue by emrikol** [WordPress/gutenberg#7498]
**Describe the bug**
Ever since the latest update to 3.1.0, typing in the Gutenberg editor thrashes my CPU.  I've tested this on my local site and also using [Frontenberg](https://frontenberg.tomjn.com/) (just to see if it was my setup).  Whenever I stop typing, CPU usage drops dramatically.  I don't remember this being an issue with the previous version, but it at least wasn't as bad because I didn't notice.  Right now I can't even type without serious lag.

**To Reproduce**
1. Open a new post or edit an old post
2. Type in a Gutenberg text box
3. Watch CPU usage

**Expected behavior**
I would expect just typing to not use 100% of my CPU and lag so much that I can't see what I'm typing without buffering.

**Screenshots**
![gutenburnthecpu](https://user-images.githubusercontent.com/3060583/41795985-b7c25dd6-7632-11e8-8538-2248dbc9f4a3.gif)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.16299.492]
 - Browser: Google Chrome
 - Version: 67.0.3396.87 (Official Build) (64-bit)

**Comment by emrikol** [comment]
I just downgraded to 3.0.1 and no longer have this problem, so it definitely was the 3.1.0 version.

With 3.0.1 the highest CPU usage a Gutenberg page uses while typing is ~50% typing as fast as I can.

**Comment by danielbachhuber** [comment]
Yeah, I notice this too right now.

Related #6466

**Comment by notnownikki** [comment]
Investigated the issue and found the change here: https://github.com/WordPress/gutenberg/issues/7680#issuecomment-402126697

**Comment by brunoc** [comment]
This is still a big issue in WP 5.3 making Gutenberg unusable (I have to use the "Disable Gutenberg" plugin in prod).

![gutenberg wp5 3 sluggish frontend](https://user-images.githubusercontent.com/1373723/68944780-043d0300-07af-11ea-9457-e6bcfa64ad60.gif)

FYI in the example post above,  I have about 70-80 blocks (hidden above) with 90% text and titles 10% custom HTML blocks. NO Active Plugins. Using Chrome 78.0.3904.87 (Official Build) (64-bit) MacOS 10.13.6 

Let me know if you need more diagnostics.

**Comment by tlcd96** [comment]
There's a need for this to be viewed again. High CPU usage on a span of 6 processes created by Gutenberg.
Please reopen this issue.
