### ISSUE TITLE
Video block: missing features compared to classic editor

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#7501]
**Describe the bug**
When we add a self hosted videos with the classic editor, we can set many attributes. that are not available with the Gutenberg video block

Missing features:
- alternate sources (issue #9457)
- subtitles (issue #7673)
- ~~poster image~~ (Issue #4837, PR #9335)
- ~~preload (auto/metadata/none)~~ (PR #7929)
- ~~autoplay~~ (PR #7672)
- ~~loop~~ (PR #7672)

_edited by Soean_

**Additional context**
- Gutenberg 3.1

**Comment by danielbachhuber** [comment]
Related #6581

We'll need to solve https://github.com/WordPress/gutenberg/pull/7322#issuecomment-397709683 before we can get this in.

**Comment by Soean** [comment]
I edited the issue with the PR/Issue numbers. Autoplay and Loop get merged and there is now a PR for Preload. I will start to work on the other features in the next days...

**Comment by Soean** [comment]
Most features are merged now, for the missing ones we have separate issues, so im closing this.

- alternate sources (issue #9457) 
- subtitles (issue #7673)
