### ISSUE TITLE
Consider feature parity for "Image Details" TinyMCE functionality

### ISSUE THREAD

**Issue by getsource** [WordPress/gutenberg#7504]
Right now, there are a few things remaining for parity with the current "Edit Image" functionality present in core.

This modal (screenshots below) is accessible within TinyMCE when mousing over an inserted image, then clicking the edit button.

The features from this modal that seem to not have equivalents in Gutenberg at the moment are:
* [ ] Edit Image Title 
Note: Title edit is available in Gutenberg, but changes title globally in library, rather than per inserted image, and does not appear to insert this title into the title attribute, like the current feature.
* [x] Link Rel (#7771)
* [x] Link CSS Class (#7771)
* [x] Open Link in a new tab (#9520)

**Screenshots**
![screen shot 2018-06-22 at 1 41 19 pm](https://user-images.githubusercontent.com/1034160/41798308-070a4946-7622-11e8-88d6-919b1643af87.png)
![image](https://user-images.githubusercontent.com/1034160/41798201-a3eda29a-7621-11e8-9828-5d64fcb7645b.png)

**Additional context**
* The Edit button looks the same, but does something different, flow-wise, in Gutenberg to what users would have expected in TinyMCE.
* Core tried removing some of these options in 3.9, but ended up adding them back after user feedback. I'm personally not opposed to trying to change what is offered again, but figured it'd be a good idea to discuss, so that anything removed is done with intentionality.

**Comment by karmatosed** [comment]
> Core tried removing some of these options in 3.9, but ended up adding them back after user feedback. I'm personally not opposed to trying to change what is offered again, but figured it'd be a good idea to discuss, so that anything removed is done with intentionality.

@getsource would you mind some context as to what was tried to be removed and the general outcome there? I see you say some, it could be good to know which.

**Comment by danielbachhuber** [comment]
Previously #4007 #5309

**Comment by getsource** [comment]
@karmatosed Per my recollection (this was a while ago), it was everything that is under the advanced options section in the modal, and informed primarily by WP.com user testing (actual rollout and rollback) and statistics.

**Comment by getsource** [comment]
Related: #5309

**Comment by designsimply** [comment]
Removed the `Good First Issue` label because this issue looks a bit complex for someone new to tackle. If you feel strongly about adding it back, please add it back with a comment or ping me to discuss!

**Comment by karmatosed** [comment]
Looking at this it's an advanced setting over something to surface at the sidebar level. What about this?

![artboard](https://user-images.githubusercontent.com/253067/42814855-7835a152-89bd-11e8-9503-2fb6d5e89273.png)

This doesn't really change much. It does remove open in new window as that is assumed in this case.

**Comment by getsource** [comment]
Sorry, I'm seeing this comment a bit late. Yes, the sidebar seems like a perfect place to surface it.

**Comment by Ipstenu** [comment]
Related to this... You can't use `attachment_fields_to_edit` for Gutenberg.

Which means if you need to add in a required field to an image, it won't show up in the Gutenblock sidebar.

**Comment by danielbachhuber** [comment]
> Which means if you need to add in a required field to an image, it won't show up in the Gutenblock sidebar.

`attachment_fields_to_edit` doesn't currently add fields to this UI:

![image](https://user-images.githubusercontent.com/36432/46439122-92be0480-c714-11e8-8e37-6192c2377020.png)

Once an image is inserted into the `post_content`, it's de-coupled from the attachment stored in the database. All of the fields in the image shared reference `<img>` attributes directly.

**Comment by Ipstenu** [comment]
Just to show what kind of thing you can add in, this is what you see from Add Media on Classic:

![screen shot 2018-10-03 at 3 oct - 4 46 07 pm](https://user-images.githubusercontent.com/807903/46445514-23540f00-c72c-11e8-931a-4e4201396c18.jpg)

It doesn't show on the gutenberg sidebar nor (as Daniel pointed out) the details UI. That said, you don't get to that details UI very easily on Gutenberg either!

**Comment by getsource** [comment]
Per request by @antpb, double-checked to confirm, and all of the features mentioned in the issue description are still not present in Gutenberg.

**Comment by antpb** [comment]
I'd like to identify the different parts to split out here. @getsource thanks so much for doing the discovery work here. I believe you mentioned recently that you have notes on the way we can split this out. If you could share here, I'd love to go that route. 
Also I would imagine pull 7771 would be it's own issue too: https://github.com/WordPress/gutenberg/pull/7771 

7771 is really close to being merged but does not solve everything in this one. I think we should be tracking that bit separately.

**Comment by karmatosed** [comment]
After chatting in Slack today one potential solution now would be to avoid having everything in sidebar (it's getting busy there now) and have if required fields it open the media library. This isn't a perfect flow. What else could we do?

**Comment by getsource** [comment]
Thinking about this a bit more, I think having the fields in the media library might be problematic because we don't want them to appear to apply to all instances of the inserted image. 

"Edit Image" before was that place for instance/post specific data to an image.

**Comment by getsource** [comment]
@Ipstenu created #11333 to split discussion for the `attachment_fields_to_edit` portion of this.

**Comment by gziolo** [comment]
#7771 was merged which adds link rel and link class to image block inspector.

**Comment by gziolo** [comment]
> "Edit image title" I don't think needs to be added anymore (or ideally isn't added), due to feedback from the accessibility team (See: https://wordpress.slack.com/archives/C02RP4X03/p1540501890000100).

It seems like all issues were addressed in such case.
