### ISSUE TITLE
Featured image meta box does not respect admin_post_thumbnail_size filter

### ISSUE THREAD

**Issue by arpadHegedus** [WordPress/gutenberg#7505]
**Describe the bug**
admin_post_thumbnail_size filter is not respected when loading the Featured Image meta box image. Instead the full size of the image is shown

**Comment by danielbachhuber** [comment]
Hi @arpadHegedus,

What image size are you using / expecting in the Featured Image UI?

**Comment by danielbachhuber** [comment]
@arpadHegedus I've submitted a pull request to include a new JavaScript filter for this: https://github.com/WordPress/gutenberg/pull/8196

I've also created a page for it in my Gutenberg migration guide https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/filter-admin-post-thumbnail-size.md
