### ISSUE TITLE
Tooltip: Suggests to click on "Add Block", which is not visible on screen

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#7506]
**Describe the bug**
When the tool reads: 
"Welcome to the wonderful world of blocks! **Click on 'Add block'** to insert different kinds of content (...)" 

**To Reproduce**
1. Use a clean install
2. Add a new post
3. wait until Tool tip appears
4. Find the place where there is a "Add Block" mentioned 

**Expected behavior**
The blue dot points to the inserter + so the wording could say: **Click on the + sign** to insert different kinds of content.

Also, possible to have the "Add Block" text show above the inserter to make clear that's where people should click. 

**Screenshots**
![screen shot 2018-06-22 at 10 32 14 am](https://user-images.githubusercontent.com/39980/41800545-ff6ce834-7643-11e8-8b8b-6e3753f8c66e.png)

**Desktop (please complete the following information):**
 - OS: X 10.11.6
 - Browser Chrome
 - Version Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by karmatosed** [comment]
Thanks for this catch and a great adjustment. Let's work in the PR as to what the actual copy says.
