### ISSUE TITLE
Consider allowing text align in headings

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#751]
Splitting out from #497, we should, after all, consider allowing text aligns in headings. Reading this article suggests that though typographically weird, a text aligned heading can make for an interesting layout: http://www.windowscentral.com/windows-10-creators-update-review

What do you think?

See also, #522, which might free up space for a text align control group.

**Comment by 00travelgirl00** [comment]
I thinks it's important, that the headings has also the option of text-align. 

In case of adding the option "float" I'm not sure, cause I don't know if all users would understand the difference between float and text-align. But if we can communicate that in a clear way it would be a good option.

**Comment by iseulde** [comment]
We could put these in the inspector now.

**Comment by jasmussen** [comment]
Actually we could do that, but also remove h4-6 from the main quick toolbar, and have the full range only in the inspector. That seems like a neat solution!

**Comment by iseulde** [comment]
Maybe 1-5-6 😊

**Comment by iseulde** [comment]
Or all of them and just have 2-3-4 on the block.

**Comment by jasmussen** [comment]
🔥🍿

I could actually be swayed by that. I know it would make a lot of people happy.

**Comment by jasmussen** [comment]
Because this exists in the inspector, let's close this for now.
