### ISSUE TITLE
"Updating failed" - error 400 when filtering the_content with PHP's DomDocument

### ISSUE THREAD

**Issue by acidrums4** [WordPress/gutenberg#7512]
**Describe the bug**
I'm using a function to filter the_content with a custom function to include classes on elements and images to make them compatible with UIKit3, framework I'm using for a custom theme on a project I'm working on. No problems whatsoever with classic editor. Said function goes like this:

    function add_div_to_image( $content )
    {
        global $post;

        if( !empty( $content ) && ( $post->post_type === 'post' ))
        {
            $dom = new DOMDocument();
            libxml_use_internal_errors( true );
            $dom->loadHTML( mb_convert_encoding($content, 'HTML-ENTITIES', 'UTF-8'));
            libxml_clear_errors();
            $imgs = $dom->getElementsByTagName("img");
            $xpath = new DOMXpath( $dom );

            foreach ( $xpath->evaluate('//body/*') as $node )
            {
                $node->setAttribute("class", "uk-container uk-container-small");
            }

            $dom->normalizeDocument();
            $return = "";
            $body= $dom->getElementsByTagName('body')->item(0);

            foreach( $body->childNodes as $child)
            {
                $return .= $dom->saveHTML( $child  );
            }
        }

        else
        {
            $return = $content;
        }

        return $return;
    }

    add_filter('the_content', 'add_div_to_image' );

So I decided to give Gutenberg a try. But everytime I try to publish a new post or update an old one, the "Updating failed"/"Publishing failed" message appears, with a 400 error on network console.

The above function includes a thing to set additional classes and stuff for images, but that was stripped here for "minimal example" purposes. Still, setting this function as it is, still makes Gutenberg show the "Updating failed"/"Publishing failed" messages.

Unsetting this filter makes Gutenberg work as expected

**To Reproduce**
1. Set the mentioned function as filter for the_content.
2. Create a new post or edit an existing one.
3. "Updating failed"/"Publishing failed" messages appear - despite the post is actually published/updated.

**Expected behavior**
Clean-for-the-user updating/publishing posts process, no warning/error messages shown.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
 - Wordpress 4.9.6
 - Gutenberg 3.1.0
 - PHP 5.4.16
 - mysql  Ver 15.1 Distrib 5.5.56-MariaDB

**Comment by danielbachhuber** [comment]
Hi @acidrums4,

Thank you for the detailed report.

I tried applying your code snippet locally and wasn't able to reproduce the issue on `master`:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/36432/41979251-7bcb19f4-79d8-11e8-9c4b-c25ca46be9c7.png">

Can you debug this further and provide additional information? To start, it would be helpful to know the full data in the response to the `POST` request.

**Comment by acidrums4** [comment]
Thank you so much for your answer,

Weird enough I just tested it again and it didn't throw a 400 error response (maybe because I cleared caches), but also a 200. Still, the "Publishing failed"/"Updating failed" messages appear.

You can find the full response (I'm not sure if it's this, I copied all the HTML from the 'response' tab on Firefox's inspector) [in this pastebin (https://pastebin.com/kyFbzTq8)](https://pastebin.com/kyFbzTq8).

Please let me know if you need more data from here and I will send it as soon as I can.

Thanks!

**Comment by danielbachhuber** [comment]
Hi @acidrums4,

It appears the HTML you've shared is the initial page load. Can you share the HTML from the REST API response corresponding to the save?

**Comment by acidrums4** [comment]
Still not sure (sorry, I'm pretty noob on network stuff), but do you mean this output?

https://pastebin.com/2R1jWVRs

**Comment by danielbachhuber** [comment]
Not quite. The contents of this Response tab:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/36432/41982261-d3bdc3a8-79df-11e8-9489-05553f3214a8.png">

**Comment by acidrums4** [comment]
Aaaaah, it's JSON! Here you go.

https://pastebin.com/w4jTvEBG

**Comment by danielbachhuber** [comment]
Interesting. Nothing obvious there. Can you share a screenshot of the entire Inspector view, similar to how I've done so?

**Comment by acidrums4** [comment]
![An screenshot](https://user-images.githubusercontent.com/513421/41982738-d0186ff2-79f1-11e8-9bf2-f1a49ec300bf.jpg)

**Comment by danielbachhuber** [comment]
Can you track down with request triggers the "Updating Failed" message? This screenshot doesn't seem to indicate anything.

**Comment by acidrums4** [comment]
I couldn't find that, but seems I could solve this.

The `if( !empty( $content ) && ( $post->post_type === 'post' ))` line on my code was making PHP throw an "Trying to get property of non-object" notice message, and that appeared on a JSON response. Clearing that solved the issue and I can now publish/update posts with no warnings.

So as I feared this was a PEBCAK thing, but I still don't know if it's convenient an unexpected PHP message makes Gutenberg show such warning.

However, thank you so much for your help. :)

**Comment by danielbachhuber** [comment]
Glad you were able to sort it out :)

**Comment by designsimply** [comment]
@acidrums4 may I ask how you modified the `if( !empty( $content ) && ( $post->post_type === 'post' ))` line to in order to resolve the "updating failed" error in your case?

**Comment by acidrums4** [comment]
@designsimply Sure, you'd just encapsulate that whole `if( !empty( $content ) && ( $post->post_type === 'post' ))` into a `if ( $post )`:

    if ( $post )
    {
        if( !empty( $content ) && ( $post->post_type === 'post' ))
        {
            // Stuff...
        }
    }

**Comment by Oxibug** [comment]
Nice, But unfortunately the DOMDocument class may not be installed in some shared hosts so it's not appropriate for all clients

Thanks for share your experience
