### ISSUE TITLE
Trying to add a New Block after converting a Block to a Shared Block crashes the editor

### ISSUE THREAD

**Issue by jfarsen** [WordPress/gutenberg#7517]
**Describe the bug**
If I convert an existing block to a Shared Block, and then click on the (+) New Block toolbar button, the editor crashes.

**To Reproduce**
1. Create a new Page
2. Enter a Title and create a single Text Block
3. Click on the three-dot contextual menu, click "Convert to Shared Block"
4. Click on "Save" without changing the default name of the shared block ("Untitled shared block")
4. Click on the (+) in the top bar to add a new Block
5. Crash

**Crash Log**
```
r@http://gutenberg.local/wp-content/plugins/gutenberg/build/editor/index.js?ver=1529837520:12:155265
http://gutenberg.local/wp-content/plugins/gutenberg/build/editor/index.js?ver=1529837520:12:155328
filter@[native code]
value@http://gutenberg.local/wp-content/plugins/gutenberg/build/editor/index.js?ver=1529837520:12:155370
value@http://gutenberg.local/wp-content/plugins/gutenberg/build/editor/index.js?ver=1529837520:12:154363
jc@http://gutenberg.local/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:134:140
gc@http://gutenberg.local/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:225
vb@http://gutenberg.local/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:232
ub@http://gutenberg.local/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:67
wg@http://gutenberg.local/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:137:184
Ze@http://gutenberg.local/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:41:26
Ze@[native code]
```

**Expected behavior**
Not sure, never seen what follows ;)

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.5
 - Browser : Safari 11.1.1

**Additional context**
- Gutenberg 3.1.0 (no other plugins active)
- Running WordPress Beta Tester, WP 4.9.7-alpha-43316
- Running in a Local by Flywheel machine, nginx + PHP 7.1.7

**Comment by danielbachhuber** [comment]
I can reproduce this issue on `master`. Thank you for the detailed reproduction steps.

The issue seems to be specific to the shared block having the default title. I see the following JavaScript error:

```
Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
    in input (created by t)
    in form (created by t)
    in t (created by r)
    in r (created by t)
    in t (created by WithDispatch(t))
    in WithDispatch(t) (created by WithSelect(WithDispatch(t)))
```
