### ISSUE TITLE
ColorPalette - problem with Clear vs default value

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#7520]
**Describe the bug**
The Clear link on the ColorPallet picker sets the attribute to undefined instead of the default value originally defined for the attribute. This leads to problems with the block validation and breaks the block.

**To Reproduce**
I hope these code excerpts are enough to demonstrate the problem.
 
1 The attributes:

```
attributes: {
		titleColor: {
			type: 'string',
			default: '#0000FF'
		}
}
```

2. The save render:

`<h4 style={ { color: titleColor, fontSize: titleFontSize } }>{ title }</h4>`

2. The editor render:

```
<RichText
	tagName="h4"
	value={ title }
	style={ {color: titleColor, fontSize: titleFontSize} }
	onChange={ ( value ) => setAttributes( { title: value } ) }
	placeholder={ __( 'Write column one title...', 'blocks-by-weaver') }
	keepPlaceholderOnFocus
/>
```

3. The relevant inspector code:

```
const { 
    attributes,
    setAttributes,
} = this.props;

const {
	titleSize,
	titleColor,

} = attributes;


<PanelColor title={ __( 'Title Color', 'blocks-by-weaver' ) } colorValue={ titleColor } initialOpen={ false }>
	<ColorPalette
		label={ __( 'Title Color', 'blocks-by-weaver' ) }
		value={ titleColor }
		onChange={ ( value ) => setAttributes( { titleColor: value } ) }
	/>
</PanelColor>
```

This, I believe, is where things go wrong. Instead of the default for titleColor, you get undefined. This then breaks the editor/save renders, giving the validation error:

4. The validation error:

Open a post in the editor. Create an example block, and enter the title. All is okay. From the inspector view, change the title color to some other color. This works fine. Then, use the Clear link the ColorPalette. This changed the color to undefined, giving the following upon reloading the editor:

```
Expected:
... <h4 style="color:#0000FF;font-size:150%">COLUMN 1</h4> ...

Actual:

... <h4 style="font-size:150%">COLUMN 1</h4> ...

Note the missing color: from the style= code because the value is undefined due to clearing to undefined in the PanelColor code in the inspector.
```

**Expected behavior**
I would hope the color reverts to the default value.

This sort of code in the inspector fixes the problem:

`onChange={ ( value ) => setAttributes( { titleColor: (value === undefined ? '#0000FF' : value) } ) }`

Is there some aspect of setting up the ColorPalette code I'm missing? I see that the default paragraph and button blocks use getColor and setColor and extra attributes that seems to avoid this issue, but that makes it all seem somewhat more complicated that I would hope it needs to be.

The full plugin that has this issue is 'Designer Blocks for Gutenberg by Weaver' Version 0.4. I plan to use the above noted fix for Version 0.5 to be updated soon.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: any

**Smartphone (please complete the following information):**

**Additional context**
- Gutenberg V 3.1

**Comment by youknowriad** [comment]
I think the fix is correct. The ColorPalette is an independent component so it shouldn't have anything to do with the block default values. The clear is used to set the value to undefined, if this is not the expected behavior for your own usage of ColorPalette, replacing the value with something else if you detect it's undefined seems like the right approach to me.
