### ISSUE TITLE
Embed link not recognize Twitter as whitelisted site.

### ISSUE THREAD

**Issue by Emilybkk** [WordPress/gutenberg#7521]
Normally with the Classic Editor I will disable WP Embeds from the WP Rocket cache plugin settings (many optimizer plugins has this option too). 

Even turn off the WP Embeds but the URL from twitter will still enable to embeds and render well when insert from the Classic Editor (as same as the link from YouTube). But with Gutenberg it not work at all. Turn Off the WP Embeds will completely turn off Embeds from any website.

**Comment by danielbachhuber** [comment]
Hi @Emilybkk,

Thanks for the report. I'm not sure I follow the issue though. Can you provide specific reproduction steps with screenshots?

**Comment by Emilybkk** [comment]
@danielbachhuber 

Well. Seem like the image size are not an issue but it move to block settings on the right but I still think it is not intuitive that way. It make user click Edit and then have to move to the right panel for setting. It should have popup and ready for settings like with the Classic editor. It is faster and more natural that way. 

![image-details](https://user-images.githubusercontent.com/13035541/41976177-9dfd7fb2-7a46-11e8-885a-0a4898afdf80.png)

So the one that left to be an issue is the "Link to" which we used to use it for link to Attachment/Media file/ Custom URL/None now disappear. It is only a normal insert link like we did for text link. 

![link-gone](https://user-images.githubusercontent.com/13035541/41976452-65dcabf2-7a47-11e8-97fd-1b160059346c.png)

**Comment by Emilybkk** [comment]
It seem to render in post now. It used to display as normal text of the twitter url. I don't know but it just work! The WordPress Embeds still disable too. 

But the one issue is it still can't preview.  
![embet-no-preview](https://user-images.githubusercontent.com/13035541/41976972-74e07092-7a48-11e8-8aea-8f76b28177ca.png)

But at least it work.
![xwp](https://user-images.githubusercontent.com/13035541/41977046-a3a02d32-7a48-11e8-864c-ee87858b0e04.png)

**Comment by danielbachhuber** [comment]
Ok. Let us know if you track down specific reproduction steps and we can take a further look.

**Comment by aubokani** [comment]
> It seem to render in post now. It used to display as normal text of the twitter url. I don't know but it just work! The WordPress Embeds still disable too.
> 
> But the one issue is it still can't preview.
> ![embet-no-preview](https://user-images.githubusercontent.com/13035541/41976972-74e07092-7a48-11e8-8aea-8f76b28177ca.png)
> 
> But at least it work.
> ![xwp](https://user-images.githubusercontent.com/13035541/41977046-a3a02d32-7a48-11e8-864c-ee87858b0e04.png)

Hi Emily,
I have the same problem with a BBC page. Could you please let me know how you embedded your twitter link? I might be able to use the same strategy to fix my problem. I wish there would be a way to easier embed other ULRs that are not listed in the Whitelist! Thanks.
