### ISSUE TITLE
Cannot select image from library

### ISSUE THREAD

**Issue by JeroenSormani** [WordPress/gutenberg#7523]
**Describe the bug**
It currently is not possible to select a image from the library. No issues with the classic editor with this.

**To Reproduce**
1) Add image block
2) Try and select a image from library - no way to do so.

**Expected behavior**
Have a 'Media library' button

**Screenshots**
![image](https://user-images.githubusercontent.com/5774447/41837113-e3576cda-785c-11e8-9e10-2d0a41c869b7.png)

**Additional context**
- Version: 3.1.0

**Comment by karmatosed** [comment]
Thanks for reporting this @JeroenSormani. It does look like you have a missing button that I see on adding an image. For example, what I see is this:

![2018-06-25 at 15 57](https://user-images.githubusercontent.com/253067/41857935-84604a2e-7890-11e8-9d19-7d18d295b857.png)

Do you perhaps have other plugins active? My thinking is that something is causing you to not see this button. I notice it says add_to_cart, are you perhaps using an e-commerce plugin? With that removed do you still get no button?

**Comment by JeroenSormani** [comment]
Seems to have been a conflict with ACF - see https://github.com/WordPress/gutenberg/issues/7524 - also resolved after updating to the latest. Thanks.

**Comment by ChrisBAshton** [comment]
For the record, looks like the fix was [this line on this commit](https://github.com/AdvancedCustomFields/acf/commit/c8e181c848009aa9f6a3919ee19981fb2774f634#diff-6d2aae6276519633265301c63b04deefR250).

Had hoped tracking down the fix would help me find a fix for my custom plugin, but no luck 😫I'm seeing the same bug with a bespoke plugin (not open source) but there's no reference to `wp.hooks` anywhere...

**Comment by ChrisBAshton** [comment]
Narrowed it down to the plugin's main PHP file:

```php
// Hook: Editor assets.
add_action( 'enqueue_block_editor_assets', 'action_block_cgb_editor_assets' );

function action_block_cgb_editor_assets() {
	wp_enqueue_script(
		'action_block-cgb-block-js',
		plugin_dir_url( __FILE__ ) . '/dist/blocks.build.js',
                // THIS LINE - try passing an empty array and things work again! :
		array( 'wp-blocks', 'wp-i18n', 'wp-element', 'wp-editor' ), // Dependencies
		true // enqueue script in footer
	);
}
```

I've raised an issue with https://github.com/ahmadawais/create-guten-block/issues/128
