### ISSUE TITLE
Featured image not being able to set / not visible when set

### ISSUE THREAD

**Issue by JeroenSormani** [WordPress/gutenberg#7524]
**Describe the bug**
Two scenario's;
1) A new / existing post without a existing featured image. There is no link anymore to set a featured image.
![image](https://user-images.githubusercontent.com/5774447/41837543-1321b0dc-785e-11e8-879d-0912a4dbb5c0.png)

2) When a screenshot is set, it can be removed (showing the link for that), but it doesn't show the image.
![image](https://user-images.githubusercontent.com/5774447/41837468-dd05b3b8-785d-11e8-859e-bd78db5c42e1.png)

**To Reproduce**
Not doing anything special here. Just updated to the latest GB version and this happened, worked good before. 

**Additional context**
- Version 3.1.0

**Comment by karmatosed** [comment]
This is super interesting and makes me wonder if you have a plugin conflict. Let's find out and get to the bottom of things for you. I see this on the latest version:

![2018-06-25 at 16 01](https://user-images.githubusercontent.com/253067/41858156-0f83a542-7891-11e8-9d14-437be024b5d7.png)

If you remove all plugins apart from Gutenberg do you still have the same issue?

**Comment by joshuafredrickson** [comment]
I saw this exact same issue while using an older version of ACF Pro. Updating to the latest version (5.6.10) fixed it.

**Comment by JeroenSormani** [comment]
Thanks @joshuafredrickson - that seems to fix it for me too. Weird ACF caused a conflict for something like that.
