### ISSUE TITLE
get_post_blocks() in php for custom calculations etc.

### ISSUE THREAD

**Issue by katerlouis** [WordPress/gutenberg#7526]
Related to this issue #5797, where `get_post_galleries()` is being discussed,
I'd like to propose a simliar function for all blocks in general, which returns an array of blocks with their data. This is especially useful for dynamic blocks.

My usecase:
I made a custom gallery block and want to show total count of images used throughout the whole article. (this situation could also be solved with a custom field which gets filled with the right amount automatically etc., but still it would be very useful to have access to the block data anywhere in the code)

I imagine something like this:

```php
// php

$galleries = get_post_blocks("my-blocks/my-gallery", $post->ID);

var_dump($galleries);

// outputs something like this:
array(3) {

    // gallery #1
    [0] => array(...) {
        "data" => array(...) {
             // json data in the serialized comment
         },

         // the saved html between the block-comments 
         "html" => "..."
    },

    // gallery #2
    [1] => ...

    // gallery #3 
    [2] => ...
}
```

**Comment by youknowriad** [comment]
This is not possible at the moment technically speaking and it falls under the Server Side Awareness of blocks project. So I'm closing in favor of #2751
