### ISSUE TITLE
Dead / Broken links in Documentation

### ISSUE THREAD

**Issue by katerlouis** [WordPress/gutenberg#7529]
Learning to support Gutenberg is hard enough already.
Broken links in the handbook don't need to complicate things even more.

Let's hunt them down and report them here!

**Comment by katerlouis** [comment]
On this page: https://wordpress.org/gutenberg/handbook/extensibility/
![image](https://user-images.githubusercontent.com/1983382/41848934-83eb412c-787f-11e8-98db-99e325635b39.png)


There's a broken link leading to: **https://github.com/WordPress/gutenberg/blob/master/plugins**

**Comment by gziolo** [comment]
We moved them to `packages` subfolder, they need to get updated.
