### ISSUE TITLE
Plugin compatibility issue when applying filters to the_content

### ISSUE THREAD

**Issue by rachelslurs** [WordPress/gutenberg#7536]
**Describe the bug**
Adding filters to `the_content` is not handling embeds as expected. Not only is this the case with a plugin I work on, but it seems common amongst all other plugins that modify `the_content` for controlling access to content ie paywalls. Using Gutenberg v3.0.1

**To Reproduce**
1. (will add a snippet later of code demonstrating this) Add snippet to modify post content to see a typical use case for a paywall plugin. (in the meantime, here's [a good example](https://wordpress.org/plugins/paid-memberships-pro/) to try
2. Enable Gutenberg
3. Add an embed code of some kind and a bunch of text to trigger the break (if using the read more break, the behavior is the same)
4. View the post and observe the embed isn't being rendered as an embed, but rather a link to the embedded content

**Expected behavior**
The embed should be rendered as an embed and not as a URL

**Additional context**
I was going to submit this as a question, but seeing that it poses compatibility issues for more than just my plugin, I submitted it as a bug. Apologies if this isn't appropriate.

Will update with a smaller plugin example shortly...

**Comment by danielbachhuber** [comment]
Hi @rachelslurs,

Thanks for the report. Any additional reproduction steps, including a code snippet, screenshots of what you're seeing, etc. would be very helpful.
