### ISSUE TITLE
Disappearing metaboxes in 3.1.0

### ISSUE THREAD

**Issue by jhackett1** [WordPress/gutenberg#7537]
I have a website that uses metaboxes on pages. When I update to the latest version of Gutenberg, the meta boxes disappear from the "Extended Settings" area in the sidebar they were in previously.

When I amend my theme code to add 

    `array(`
        '__block_editor_compatible_meta_box' => true,
    )`

as per the [advice here](https://wordpress.org/gutenberg/handbook/extensibility/meta-box/), the boxes are still not visible.

When I set the option to `false` instead, the box still does not appear when I choose the Classic editor option, although it does appear (ticked) in screen options.

_WP 4.9.6 and Gutenberg 3.1.0, Chrome_

**To Reproduce**
Upgrade to Gutenberg 3.1.0, activate a theme with a custom meta box defined to be either gutenberg-compatible, gutenberg-incompatible, or simply not explicitly defined.

**Expected behavior**
Still need to see the meta box.

**Comment by danielbachhuber** [comment]
Hi @jhackett1,

Thanks for the report. This isn't quite enough information to determine what's going on, so I have a few follow-up questions:

1. Does the problem reproduce with Gutenberg 3.0.1?
2. Does the problem reproduce with all plugins deactivated except Gutenberg?
3. Can you share the full code for your metabox?

**Comment by phpbits** [comment]
@danielbachhuber I'm having same issue. Tried this one : https://gitlab.com/snippets/1699308 and the metaboxes are only showing when on Classic Editor.

**Comment by xenobytezero** [comment]
Also having this issue with Gutenberg 3.4.0, no metaboxes from any plugins are appearing in the Gutenberg editor (Seriously Simple Podcasting, ACF, etc), but are in the classic editor

**Comment by youknowriad** [comment]
Do you all have a Gutenberg sidebar plugin installed like suggested in #8742?

**Comment by youknowriad** [comment]
I think this is closed by #8400
