### ISSUE TITLE
Post Thumbnail panel display should respect supported post types

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#7547]
**Describe the bug**
At the moment, the Post Thumbnail panel is either displayed for all posts types or not displayed.
The editor should respect the second argument which defines the supported post type.

**To Reproduce**
1. Set `add_theme_support( 'post-thumbnails', array( 'post' ) );` in your theme `functions.php`
1. Edit a page
1. See the Post Thumbnail panel is displayed

**Expected behavior**
For post types for which there's no theme support for `post-thumbnails`, the Post Thumbmail panel should not be displayed.

**Desktop (please complete the following information):**
 - OS: macOS 10.13.5
 - Browser : Firefox 60.2

**Additional context**
- Gutenberg 3.1

**Comment by danielbachhuber** [comment]
> The editor should respect the second argument which defines the supported post type.

This should already be the case. On what hook are you calling `add_theme_support()`?

**Comment by danielbachhuber** [comment]
Hi @benoitchantre,

I've added the following to a mu-plugin with Twenty Seventeen active:

```
add_action( 'after_setup_theme', function(){
	add_theme_support( 'post-thumbnails', array( 'post' ) );
});
```

With this code snippet present, I still see "Featured Image" in the Page screen of the Classic Editor:

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/36432/41916320-a7d1cbaa-790c-11e8-9e6b-f6dfa2bde3e4.png">

Can you do a bit more debugging and provide step-by-step reproduction steps?

**Comment by benoitchantre** [comment]
Hi @danielbachhuber,

In order that your changes take effects from an mu-plugin (same for a plugin), you should first remove support for post thumbnails and use an higher priority like below:

```php
add_action( 'after_setup_theme', function(){
	remove_theme_support( 'post-thumbnails' );
	add_theme_support( 'post-thumbnails', array( 'post' ) );
}, 11 );
```

**Comment by danielbachhuber** [comment]
Thanks for the additional detail, @benoitchantre. I've been able to reproduce the issue with the code snippet you provided.

In `gutenberg_ensure_wp_json_has_theme_supports()`, we'll need to pass the specific post type slugs when they're defined:

https://github.com/WordPress/gutenberg/blob/e5e7335bd84c8124290219abb3562341c2c2dfff/lib/rest-api.php#L430-L434

Once the data is present in the REST API index, we'll need to incorporate it into the `ThemeSupportCheck`:

https://github.com/WordPress/gutenberg/blob/dc7ee1213675c51b479ea4108f7a027742461082/editor/components/theme-support-check/index.js#L11-L21
