### ISSUE TITLE
How can I refresh the sidebar "PostTaxonomies" component panels ?

### ISSUE THREAD

**Issue by manooweb** [WordPress/gutenberg#7549]
Hello,

With Polylang, one of our features refreshes datas in the editor.
When you change the language in the Polylang metabox, these datas are refreshed :
* permalink root with the language selected
* categories in the language selected
* autocompletion for tags in the language selected

# With Classic Editor
See screenshots below

Before changing the language

![2018-06-26_1405-before-change-language](https://user-images.githubusercontent.com/1003778/41918918-9ba9ea82-795d-11e8-831c-d3ec0d04d6ba.png)

After changing the language

![2018-06-26_1444 -after-change-language](https://user-images.githubusercontent.com/1003778/41913266-a0c0cc28-7950-11e8-9f0e-c5c0743d37cb.png)

A ajax call is made to :
* store the new language ( a taxonomy with Polylang) for this post
* get categories filtered by the new language
* get the new permalink
* get specific datas for the language metabox (translations, flags)

After the ajax call, datas is refreshed in the UI.

# With Gutenberg
see screenshots below

Before changing the language

![2018-06-26_1550-gut-before-change-lang](https://user-images.githubusercontent.com/1003778/41917317-64ba7cba-795a-11e8-9994-db5c41803a31.png)

After changing the language

![2018-06-26_1550-gut-after-change-lang](https://user-images.githubusercontent.com/1003778/41920131-501ca07a-7960-11e8-83df-ea0be38aa5c0.png)

# What we already found
## Permalink
It is a little bit tricky because permalink is built on the fly based on the permalink template which is not editable like the slug. 
So, as we had to store the language too, we decided to use the Gutenberg savePost() method when the language is changed. It does the job because savePost() is visible for an external use.

`wp.data.dispatch('core/editor').savePost();`

## Categories
We understood how this metabox is built but we did not found a way to refresh its datas.
When we toggle twice the panel to close and reopen the metabox, the API request is sent again and datas are refreshed. We did not found how to do the same thing from our code.

## Tags
It is almost the same behaviour than the categories. The autocompletion works fine with the new language but results always display tags in the language before the change.
We have to toggle twice the panel to reset results for the initial language.
As "Tags" uses the same component as "Categories", we did not found a way to well refresh its datas.

# What we are looking for
We are looking for a way to interact with these components of Gutenberg.
Is it already possible ? Is it possible to expose a method for this specific need ?

Thanks for your help.
# Context
* Gutenberg master branch from github
* Polylang Pro is necessary because it implements a REST API compatibility to use well the language which is not exist in Polylang (free).
* Polylang for Gutenberg a specific plugin that we decided to develop to not disturb the development on our plugin before we find all the solutions.
https://github.com/polylang/polylang-gutenberg

**Comment by chrisvanpatten** [comment]
This has the documentation ticket but I think we need clarity on whether or not it is possible. Would love some technical feedback on this before we can move forward.

**Comment by designsimply** [comment]
Based on a read of https://github.com/WordPress/gutenberg/issues/11700 it sounds to me that it is currently not possible for a plugin to hook into the `PostTaxonomies` component and refresh it on the fly and a new API for this is not yet approved because we want to keep the APIs semantically correct and try to ensure forward compatibility. It also looks to me like two possible solutions were suggested: one is to use [`toggleEditorPanelEnabled`](https://wordpress.org/gutenberg/handbook/data/data-core-edit-post/#toggleeditorpanelenabled) and the other is to build a separate component in a separate sidebar instead of trying to hook into the default component. @chrisvanpatten am I reading #11700 correctly and can you help identify what is left to make this issue actionable for the Documentation team?

**Comment by designsimply** [comment]
I am removing the `[Type] Help Request` label from this issue because it has changed status to a `[Type] Documentation` issue.

**Comment by aduth** [comment]
Depending on how a component is implemented, if it consumes data which is "fetched" as a result of a [data module resolver](https://github.com/WordPress/gutenberg/blob/master/packages/data/README.md#resolvers), you can force the data to be re-fetched by invalidating the selector resolution state.

An example of this can be seen with the embed block's "Try Again" preview loading:

https://github.com/WordPress/gutenberg/blob/00454e469955fa699bf7c6e49bd06039ccb5f044/packages/block-library/src/embed/settings.js#L85-L90

**Comment by youknowriad** [comment]
This has a good answer, let's close.

**Comment by manooweb** [comment]
Yes ! It was what we used on advice of @youknowriad. The diffculty is to find the correct parameters :-)
