### ISSUE TITLE
Edit image inserted into post can't define image size, link to, CSS Classes

### ISSUE THREAD

**Issue by Emilybkk** [WordPress/gutenberg#7558]
Image that upload into post/page are not able to change these settings. I would like to add the css class for some specific image. To do this I only have to edit as HTML. Not so friendly. Bring back the edit function like the same one on classic editor please. 

Also when finished uploaded, image insert  directly into post I not able to choose where to link to anymore and it not even linked! unable to click.

**Comment by breath-ee** [comment]
Also adding 'id' for anchor points like you get with the headings block!

**Comment by chrisvanpatten** [comment]
See also #7504.

> not able to choose where to link to anymore

Are you referring to the ability to select to link to the attachment page or directly to the media URL? It's still possible to link an image but it does look like the ability to automatically link to the image is no longer available.

**Comment by Emilybkk** [comment]
@chrisvanpatten 

I mean all of this when click edit after uploaded in post/page. Not able to choose the size. Not able to choose Link to. Not able to put the CSS Classes ect. 

![image-details](https://user-images.githubusercontent.com/13035541/41971576-25d05d28-7a39-11e8-954c-c92195176003.png)

and also this
![also-this](https://user-images.githubusercontent.com/13035541/41971588-308ee0a4-7a39-11e8-89fc-da99bd00bcb8.png)

**Comment by chrisvanpatten** [comment]
@Emilybkk #7504 covers the full Edit Image interface, but I don't believe there's a ticket covering the "Link To" setting.

For CSS classes, you can use the Advanced panel in the sidebar:

![june_2018___ _mindful_ _wordpress](https://user-images.githubusercontent.com/1231306/41974575-59427f72-79e6-11e8-8e60-0f5415b6db68.png)

And for size, I believe #6177 is changing the way image sizing works, so that's still a WIP.

**Comment by Emilybkk** [comment]
@chrisvanpatten Got it! I think I get used to the old way where we just insert or click edit and it suddenly popup. It was good user experience compare to this new one that we have to move left and right. They separate the alignment and the size from each other but these 2 should be close to each other. It is what people most use. For now we need the Link to back. Should I submit another ticket?

First I thought they will make they faster workflow but now I am not sure. Well we still have more time to develop. But I have to deactivate it until the next update to try again. Also all the shortcut key like Heading (alt+cmd+1,2,3) or Insert media (alt+cmd+m) are not available anymore. I hope they add it back in the future update. I am sure others must already submit this. 

Thank you.

**Comment by danielbachhuber** [comment]
> I don't believe there's a ticket covering the "Link To" setting.

See #5309
