### ISSUE TITLE
Safari Only : Insert Block ( Between 2 existing blocks ) does not work

### ISSUE THREAD

**Issue by GreenSunBear** [WordPress/gutenberg#7559]
On Safari 11.1.1  : Clicking on (+) Icon - Insert Block ( Between 2 existing blocks ) results in:
A. Focus on the nearest existing block
B. No error messages in the console.

**Expected behavior**
The new Block should be created and focus ( as in Chrome )

**Desktop (please complete the following information):**
 - OS:  High Sierra -macOS
 - Browser Safari
 - Version 11.1.1
 - Gutenberg: Version 3.1.0

**Comment by gziolo** [comment]
@jasmussen @tofumatt, do changes in #7530 fix the issue for Safari, too? Can you confirm? @GreenSunBear, this issue should be solved at least for Firefox in the development version of Gutenberg and is planned to be rolled out as part of 3.2 release the latest next week.

**Comment by jasmussen** [comment]
Yes, I can confirm that the fix that will be in 3.2 will fix things for Safari and Firefix. Sorry about that, and thank you for your patience.
