### ISSUE TITLE
Preview stuck in "generating preview" (about:blank ) after auto-save on published post

### ISSUE THREAD

**Issue by katerlouis** [WordPress/gutenberg#7561]
**Describe the bug**
Stuck on "generating preview" when clicking preview after auto-save. Apparently preview is only working 'when updated / published / refreshed. Not after auto-save.

**To Reproduce**
1. Add new post
2. Write some stuff
3. Publish post
4. Edit something in the post
5. Wait for autosave (Don't Update!)
6. Click Preview
7. Enjoy the about:blank page

8. Update Post
9. Click Preview
10. Preview works again

**Expected behavior**
Seeing the preview!

**Screenshots**
![image](https://user-images.githubusercontent.com/1983382/41967544-214ddf64-7a02-11e8-8be8-c48349fac82b.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser Chrome 66

**Additional context**
- Gutenberg 3.1.0

**Comment by danielbachhuber** [comment]
@Soean Can you verify this issue reproduces on `master`? I think it may be fixed with #7130

**Comment by Soean** [comment]
@danielbachhuber Yes, I can reproduce the issue in the current master.

**Comment by danielbachhuber** [comment]
@Soean I can't reproduce:

![autosavepreview](https://user-images.githubusercontent.com/36432/41977031-3c205382-79d3-11e8-8c3a-03f4650a1a85.gif)

Can you share a GIF of your reproduction steps?

**Comment by Emilybkk** [comment]
This happen to me too. Sometime it work but sometime it just stuck there on Generating Preview.

**Comment by Soean** [comment]
Maybe you have to publish it first
![preview](https://user-images.githubusercontent.com/695201/41977396-865c4932-7a1f-11e8-9aab-5409415b3c40.gif)

**Comment by danielbachhuber** [comment]
@Soean I'm unable to reproduce the issue with the post published either.

**Comment by designsimply** [comment]
Tested and confirmed using Firefox 60.0.2 on macOS 10.13.5:

<strong>Video:</strong> [59s](https://cloudup.com/c8DVA5yYHLe)

@danielbachhuber looking at your GIF, you missed the step to make an edit to a published post before previewing.

**Comment by danielbachhuber** [comment]
@designsimply It works for me editing a published post too:

![autosavepreview](https://user-images.githubusercontent.com/36432/41978405-a67bc3f8-79d6-11e8-98f4-53363cf84916.gif)

**Comment by designsimply** [comment]
This time 🙂 you didn't wait for an autosave. The steps:

1. Create post.
1. Publish.
1. Make an edit.
1. Wait for autosave of edit.
1. Click Preview.

**Comment by danielbachhuber** [comment]
I swear I did that the first time I tested.

In any case, I can reproduce the issue now. @aduth Any good ideas on what this might be?

**Comment by Emilybkk** [comment]
This is my screen record. This is published post. I just come back to making some change by insert image and it is autosave. Then I preview but it not done with generate preview. Only if I come back and manually update the post then it could preview successful.

[https://drive.google.com/file/d/1xBc1SzuiNiATrXmn62nEbdLaAJJ1V_hx/view?usp=sharing](url)

**Comment by aduth** [comment]
This is proposed to be fixed / improved in #7703

**Comment by designsimply** [comment]
Noting that we're consolidating to #7416.
