### ISSUE TITLE
UX: Auto Save concept is unclear and UI is confusing

### ISSUE THREAD

**Issue by katerlouis** [WordPress/gutenberg#7563]
Gutenberg Version: 3.1.0

I've roughly searched for this issue but couldn't find one solely dedicated to the UX behind it Autosaving. 

Once a post is published, it is not clear to me what exactly is happening. 
Here are my unfiltered thoughts experiencing and learning the editor. 

–––

"Switch to draft" – Does this mean the post stays published and I edit a copy of it?

The "Switch to Draft" button becomes a "Autosaving" message, then "Saving", then back to the "Switch to Draft" button. What?

While this is happening, the Update button also changes to an animated "Updating", but it stays a button, which I still can press? Oh no, I can't– Pressing doesn't do anything. So why not communicate that with a more deactivated look?

So, when "Switch to Draft" Says "autosaving"->"saving", what exactly is happening here? Is it saving a revision? Apparently not–

"Updating" indicates to really update the published post? Hopefully not!

What exactly is a revision, now? Each auto save becomes a revision? Try, Try, Try– Okay, apparently revisions are made when a post gets updated (published state) – makes sense. Cool.

Let's look at the revisions; Oh, it says I will lose unsaved content? But an autosave just happened. I'm confused. 

What happens when I refresh? Same dialogue; let's try it out and refresh anyways. Damn the changes are gone! But why is it saying "saved", then? I mean, there must be a way to save progress, without updating the live post or unpublishing and make a draft, right?!

–––

So far so good on my thoughts. 
You might say I exaggerate, but I was and am genuinely confused by the current system. It took a lot of trial and error to understand as much as I do so far– this was a lot longer and transformed a lot while writing it.

#Summary:
1. Why does "Switch to Draft" loses it's button status, while "Updating" remains a button?
2. Why does "Switch to Draft" has two messages? "Autosaving" and then "Saving"?
3. What is happening when "Switch to Draft" says "autosaving"/"saving"? 
4. What is auto-save even good for, when Refreshing shows content from last actual publish / update?
5. Why are there two different save/update indications anyways (Switch to Draft- and Update-Button)?
6. When exactly does saving produces a revision?
7. Why does the "Update" button animate on auto-save, when it isn't updating the published post?

Being a ux-designer myself, I know things can become really complex and that the current system doesn't come without thought. Still, I am not happy with the solution and have some rough suggestions. (Again: I don't know if this collides with other concepts you guys are following; just some ideas)
– A clearer distinction between drafts / revisions and published posts. Maybe reducing terminology?
– Rename "Switch to Draft" to "Unpublish"
– Show Autosave message left next to the "Unpublish" Button
– Make only 1 Auto-Saving message 
– (or if they are different for a reason) make distinction clear and extend the copy to something like "Saving revision"
– **Don't animate the "Update"-Button on auto-save** #7564
– Nice2Have: If nothing has changed, deactivate the "Update" Button (functionally and/or visually)
– Nice2Have: if nothing has changed, rename "Preview" to "View"

**Comment by jasmussen** [comment]
Some good thoughts here. 

From a high level — and this is written more indepth on another ticket which escapes me right now — with the autosave feature we are embracing _the web_ and _mobile_ as the platforms for WordPress, and that is a world where saving happens automatically, in the background, and all the time.

Many of the issues you bring up here are real issues and in many cases are compromises due to us being stuck in between the old WordPress world and the new one.

It would be nice to address as many of these as we can, though some might take longer than others, as they might require a rethinking of aspects, like the revision interface. Labelling "Needs design".

**Comment by chrisvanpatten** [comment]
There are many thoughts about saving over on #9455 that are definitely worth reading.
