### ISSUE TITLE
Update-Button is animating (updating) on auto-save

### ISSUE THREAD

**Issue by katerlouis** [WordPress/gutenberg#7564]
Gutenberg Version 3.1.0

On auto-save the "Update" Button is animating and indicating that the changes are automatically published, which I was glad to found out, is not the case–

So why is the button animating and the "Switch to Draft"-Button also saying "saving", which it also does when you say actually Update the post.

**Comment by nerrad** [comment]
I can reproduce (still happening in WP 5.2 beta3)

**Comment by youknowriad** [comment]
I think you need to "publish" the post and then make updates to experience this. I reproduce the issue.
