### ISSUE TITLE
How can I refresh the sidebar "Page Attributes" component panels ?

### ISSUE THREAD

**Issue by manooweb** [WordPress/gutenberg#7565]
Hello,

With Polylang, one of our features refreshes page attributes : parent page dropdown list.

# With Classic Editor
See screenshots below

Before changing the language

![2018-06-27_1023-page-before-change-lang](https://user-images.githubusercontent.com/1003778/41962121-864502ca-79f4-11e8-88ba-2e82433984ee.png)

After changing the language

![2018-06-27_1023-page-after-change-lang](https://user-images.githubusercontent.com/1003778/41967479-ffedb268-7a01-11e8-939d-52cad4690055.png)

A ajax call is made to :
* store the new language ( a taxonomy with Polylang) for this post
* get parent pages list filtered by the new language

After the ajax call, parent page dropdown list is refreshed in the UI.

# With Gutenberg
see screenshots below

Before changing the language

![2018-06-27_1023-page-gut-before-change-lang](https://user-images.githubusercontent.com/1003778/41967728-8d1adf6c-7a02-11e8-8079-6a51d5907964.png)

After changing the language

![2018-06-27_1023-page-gut-after-change-lang](https://user-images.githubusercontent.com/1003778/41968280-35ee105e-7a04-11e8-8935-c079f5b3bcb5.png)

It is the same beahviour that we have with the PostTaxomies panel that we notice in this issue 
https://github.com/WordPress/gutenberg/issues/7549

Unlike in this issue, toggle the panel to reopen it does nothing. No REST API is called on this event and datas are never refreshed.

# What we are looking for
We are looking for a way to interact with this component of Gutenberg.
Is it already possible ? Is it possible to expose a method for this specific need ?

Thanks for your help.
# Context
* Gutenberg master branch from github
* Polylang Pro is necessary because it implements a REST API compatibility to use well the language which is not exist in Polylang (free).
* Polylang for Gutenberg a specific plugin that we decided to develop to not disturb the development on our plugin before we find all the solutions.
https://github.com/polylang/polylang-gutenberg

**Comment by danielbachhuber** [comment]
Hi @manooweb,

It _appears_ the "Language" drop down exists within a meta box. Is this correct?

If so, if you convert it to a Gutenberg Post Settings Component, then it will automatically refresh when its data is updated.

**Comment by danielbachhuber** [comment]
> Since we opened this issue in june, we decided to rewrite completely our metabox with React/Gutenberg's technologies as you see in our repository https://github.com/polylang/polylang-gutenberg.

Great!

> We decided to put our metabox / panel in a Plugin Sidebar Component because we can't propose to our users to put it where they want in the document sidebar and we didn't have the information that we can make a Post Settings Component. I saw nothing about that in the Gutenberg's handbook. Maybe am I missing something ?

I'm likely mistaken. I'm not yet 100% up to speed with the extensibility API. @chrisvanpatten Do you know by chance?


> In fact, Parent Page's attribute doesn't work like categories and tags panels for post. Categories and tags panels are refreshed every time the panel is opened or the document sidebar is re-rendered. It works because an API call is done each time the panels have to be rendered.
For Parent Page's attribute it is not the case. The API call is just done once when we edit the page the first time.
> 
> [...]
>
> In that case, firing easily a re-render for adjacent panels is a real question.

Ah, I understand what you're talking about now.

My understanding of the Gutenberg architecture, and React generally, is that correct order of operations is:

1. Data updates.
2. Components re-render.

In your particular scenario, you'd want to update the store for Parent Page data, and then the UI would update correspondingly.

Whether or not this is possible is another question, but I think this is how it's meant to be used.

**Comment by manooweb** [comment]
@danielbachhuber 
I know in general the principles of React but in the Guterberg's context it is difficult to find the right way to do some things.

In fact, for categories and tags a REST API call is done each time you open the panel (toggle action). So it is easy for us by using apiFetch middleware (use method) to add the lang parameter to filter them with the right language.

For parent page attribute this REST API call is done only the first time. So Polylang filters correctly by language just this first time. So I'm looking for a way to do the same thing than categories and tags to filter every time I change the language in the language Panel.

I already wrote this difference of behaviour between parent page attribute and categories/tags when I opened the issue.

So, either a REST API call is done every time the parent page attribute is rendered and I have nothing to do because all is already in place with Polylang to filter by language, either you indicate to me which dispatch action I have to use. And mostly what is the better way to do between both of these two ways ?

I didn't see how can I do with the core/editor or core/edit-post stores without diving deeper in Gutenberg's code ?
Maybe I'm not at the right place but it is the diffculties I encounter.

Thanks for your help.

**Comment by tofumatt** [comment]
You probably want to use your own store, there is some documentation on our `data` module here: https://github.com/WordPress/gutenberg/tree/master/packages/data

To see how an `apiFetch` call is used in a store I searched the repo for `apiFetch` and found a Metabox-related effect using `apiFetch` to then dispatch actions. Hopefully it helps you understand how to create your own action related to API data updates: https://github.com/WordPress/gutenberg/blob/master/edit-post/store/effects.js#L68

That should allow you to update your components by making an API request and dispatching the new data to your store, which your panel should watch for updates.

Hope that helps! 👍

**Comment by danielbachhuber** [comment]
@tofumatt For this particular use-case, @manooweb needs to trigger a refresh of the data in the core store. How can this be achieved?

Specifically, they're trying to update the `Parent Page` dropdown when the value for `Language` is changed:

![image](https://user-images.githubusercontent.com/36432/46608983-46c7e280-cabb-11e8-8672-6cb73aaffc5a.png)

**Comment by tofumatt** [comment]
`dispatch( 'core' )` will allow dispatching based on the actions available to that store. There are examples in the file I linked to above.

**Comment by mtias** [comment]
You'll create a data-bound component:

```
function MyComponent( { title } ) {
  return <p>Here's the latest title: { title }</p>;
}

export default withSelect( ( select ) => {
  const { getEditedPostAttribute } = select( 'core/editor' );
  return {
    title: getEditedPostAttribute( 'title' ),
  };
} )( MyComponent );
```

**Comment by manooweb** [comment]
Hello :-)
@mtias I know that and I use it for getting the post ID and retrieve some of our REST API fields like the post's current language, translations and post synchronizations.
Here, this is not post content or fields I need to change but the content of the parent page dropdown list in the document sidebar when I change the language in our panel. It is a little bit different, isn't it ? Or I am missing something ??

@tofumatt I know how to use apiFtech.
I use it to retrieve our datas for our language panel like Languages, translated posts, user's metas and save translations and post synchronizations as well.

I use the middleware of apiFetch ("use" method) too for filtering all REST API requests by language by adding post's current language in the query.

At the moment, our metabox is no more a metabox as you can see in the screenshots I posted in june. As I said to @danielbachhuber before, I rewrote completly our metabox with React/Gutenberg technologies and put it in a panel in our own plugin sidebar. 
I will post another reply later with new screenshots for better showing you where we are today

The goal is not to have our own parent page attribute datas but to use the standard parent page attribute filtered by language in the "Page attributes" panel located in the document's sidebar of Gutenberg.

Maybe I'm wrong but I do not understand well why if I have my own store I will be able to refresh datas in the standard "Page attributes" panel if I can't dispatch these datas in this component.

To well understand what I saw in the standard panels and the difference between categories/tags and parent page attribute :

**For categories/tags**

- a REST API request is done each time the categories or tags is rendered
- so I can filtered the request by the current language by using apiFtech.use()
- then categories and tags are well filtered by the correct language I choose in the Language panel each time categories and tags panel is rendered.

**For parent page attribute**

- a REST API request is done just once : the first time the "Page attributes" panel is rendered
- So the datas of the parent page attribute can never be refreshed because no other REST API request is done after this first one as I can do for categories or tags.

Is it more clear ?

I will dive deeper in the Page attributes panel code to understand how its components work and will try to propose a PR if I can for solving my issue execpt if you already have a solution :-)

Regards

**Comment by manooweb** [comment]
Thanks @danielbachhuber for the feedback and having keep this issue opened
We are waiting for a solution as soon as possible :-)
Thank you so much
Regards

**Comment by manooweb** [comment]
We found a workaround thanks @youknowriad by invalidating resolution of this particular request ( parent page ) when we change the language in our metabox. 
As our metabox is in its own plugin sidebar when the document sidebar is rerendered the request for parent page is done again  and also correctly filtered by the language choosen.
As @youknowriad said it is a "hacky" solution :-)

**Comment by youknowriad** [comment]
I'm going to close this as there's a workaround. We'll plan to work more on Extensibility APIs for document panels (or document inspector controls) once we have a more precise idea of what full page editing means in the context of Gutenberg.

Thanks all.
