### ISSUE TITLE
Is it possible to access all shared blocks?

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#7569]
Hi! 

From what I can tell Shared Blocks are stored as a CPT. I tried accessing all posts from wp-admin/edit.php?post_type=wp_block but I get a "Sorry, you are not allowed to edit posts in this post type.". It there a specific permission I need to add to access this or is it completely locked down?

**Comment by mtias** [comment]
They are currently marked private, but that could change — see https://github.com/WordPress/gutenberg/issues/7387 . And feel free to share your thoughts there.
