### ISSUE TITLE
Templates documentation is missing a specific client-side example

### ISSUE THREAD

**Issue by nb** [WordPress/gutenberg#7572]
1. Go to https://github.com/WordPress/gutenberg/blob/e197ba045793158cec8ec47b88a438dfc417144a/docs/templates.md
2. Try to figure out how to add a default inner block to the block you're writing.
3. Try to find more details about`defaultBlock`.

I expected to have at least some sort of working client-side example, like the one I ended up with. Feel free to use it:

```jsx
<InnerBlocks
    key="children"
    allowedBlocks={ [ 'a8c/trials-list-item' ] }
    template={ [ [ 'a8c/trials-list-item', {} ] ] }
    templateLock={ false } />
```

**Comment by chrisvanpatten** [comment]
Closing to merge into #8251 :)
