### ISSUE TITLE
Request UI and to fix Link to for Image

### ISSUE THREAD

**Issue by Emilybkk** [WordPress/gutenberg#7574]
As now this "Link to" function is disappear (refer #5309  ) and we only have normal URL insert like a text link. I think for only Image Block we can bring back the Link to by add it as an option for to the current link button. 

Like this picture. Click add link for image  then open the option like the classic editor have. This will more user friendly, intuitive and natural than put it at the right panel. It reduce the clicks and moving left to right. 

![image-link](https://user-images.githubusercontent.com/13035541/41982227-13461e24-7a55-11e8-88d9-63e0da5690f0.png)

**Comment by danielbachhuber** [comment]
Hi @Emilybkk,

This issue is already tracked with #5309. Please search existing issues before opening new ones. Thanks.

**Comment by paaljoachim** [comment]
Thank you for your suggestion Emily!
