### ISSUE TITLE
Improve package installation documentation/README

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#7579]
The default installation instructions for `@wordpress/packages` READMEs tends to be:

```markdown
## Installation

Install the module
```

which I think is a bit blunt and unhelpful. We could expand it a little bit and make it friendlier.

Originally from https://github.com/WordPress/gutenberg/pull/7577#discussion_r198570237

**Comment by mkaz** [comment]
Closed with #12595
