### ISSUE TITLE
Make clarifications and tweaks to copy documentation

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#7598]
Documentation in #7588 is a start, but there are some inconsistencies and oddities in there I'd like to clear up.

Filing here so folks know I'm working on it, but the PR will have all the tweaks. Sorry 😓

**Comment by karmatosed** [comment]
Adding 'copy review' label so we can get some reviews on this, thanks :) cc @michelleweber.

**Comment by chrisvanpatten** [comment]
@tofumatt did anything come of this? Would be great to get actionable steps or we should close this up ^__^

**Comment by chrisvanpatten** [comment]
Would the improvements suggested in #8952 be related/helpful to closing this out?

**Comment by tofumatt** [comment]
I no longer remember what I was going to suggest, and now that I think of it this was basically a reminder to myself to audit the copy guidelines.

But I haven't in months and I think it's best to just close this out.
