### ISSUE TITLE
Consider making glyph symbol able to change type of block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#76]
From prototype testing:

> When a block is selected, clicking the “glyph” (H, paragraph symbol) does nothing. I wish it allowed me to change the type of block, like changing a paragraph to a blockquote, for example.

https://make.wordpress.org/design/2017/02/09/initial-gutenberg-prototype-editor-testing/#comment-25060

**Comment by jasmussen** [comment]
For the UI prototype at https://wordpress.github.io/gutenberg/, this works. The behavior is different in @iseulde's prototype at https://github.com/iseulde/editor-blocks. Labelling as question for now.

**Comment by mtias** [comment]
Since this works for the UI prototype, let's close and open issues targeting prototypes where this doesn't work.
