### ISSUE TITLE
Reintroduce browser build

### ISSUE THREAD

**Issue by ntwb** [WordPress/gutenberg#7600]
@aduth commented on [Wed Aug 02 2017](https://github.com/WordPress/packages/issues/24)

Related: #23
Slack discussion: https://wordpress.slack.com/archives/C5UNMSU4R/p1501594355646576

The browser build was removed in #23 because the generated file was problematic and could not be used in a browser. Specifically, it still included `require` CommonJS statements and implicit dependencies on the Babel runtime.

An independent browser bundle may still be useful to include in the packages distributable for developers who would like to use a module independent of WordPress, and without an npm build process. You can see other libraries which support this installation process via tools like [unpkg](https://unpkg.com/redux@3.7.2/dist/): https://github.com/reactjs/redux#installation

While it's questionable whether this should be a priority, or whether the browser build should occur in a consuming project with npm build process (like Wordpress), it may not be significant effort to reintroduce to [existing build variant configurations](https://github.com/WordPress/packages/blob/fd7fff1/scripts/build.js#L37-L49).

**Comment by youknowriad** [comment]
Was looking at the issue and I think this one should be closed. The packages are already used in several projects and there doesn't seem to be use-cases or demand for this.

**Comment by gziolo** [comment]
Based on the fact that there are no comments left on the issue, I also would vote to close this issue. We can always reopen if people think it's still would be useful.

There is also [Stop using Node.js built-ins in browser-packaged code](https://github.com/WordPress/gutenberg/issues/13386) which should be addressed instead to ensure that all packages can be executed in the browser and properly exposed through globals when using webpack to build code.
