### ISSUE TITLE
Release docs are slightly out of date and have dangerous instructions

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#7607]
The release docs in https://github.com/WordPress/gutenberg/blob/master/docs/reference/release.md could be updated a bit (the `package-lock.json` diff may not be relevant in the link example version bump commit). We could also link to the core-editor channel a bit more clearly and make a few other tweaks.

More importantly: the `npm run package-plugin` command removes files in the tree that `git` isn't tracking. This lead to me losing a file I had saved, but fortunately I had it open elsewhere. Apparently @mtias has been bit by this before too.

We should warn users that this command is 🚧 **DANGER ZONE** 🚧 and to be careful running it.

**Comment by aduth** [comment]
We can also test to see if there are changed files, and prompt the user to run `git clean -fdx` (with implications well-communicated) themselves rather than doing it on their behalf.

**Comment by tofumatt** [comment]
We should also mention the procedure here for patch releases; I'll add it to the PR I have open.
