### ISSUE TITLE
Organizing reusable blocks with categories or similar

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#7608]
Creating shared blocks is awesome, but what happens when you start getting a fair amount of them?

Things start to become hard to use, they take up screen space, finding that one block you wanted becomes a burden.

Adding some way to categorize shared blocks will likely be necessary moving forward, especially if we wish to do more in line with adding sidebar control etc to the editor experience.

#7606 looks like it might be a good stepping stone in that direction.

One might argue that naming your blocks to find them easier is the right choice, and using the block search after this to find them. Although that would be nice in a perfect world, with limited space for block names you just can't rely on naming alone.

![image](https://user-images.githubusercontent.com/468735/42040604-5006c44e-7af0-11e8-9967-a497ed54b263.png)
The example above is possibly a bit extreme, possibly not, we don't know how users will choose to name things.

**Comment by slimmilkduds** [comment]
If https://github.com/WordPress/gutenberg/issues/9964 ends up with opening the ”ordinary” editor for reusable blocks perhaps one solution could be to add a taxonomy to them which could be used for sorting them in the block list.

**Comment by paaljoachim** [comment]
Reusable blocks might as well be a tab next to the pattern tab in the Block Inserter.
Here is a wireframe idea of the block inserter that is being worked on these days: https://github.com/WordPress/gutenberg/issues/17335#issuecomment-587951100

**Comment by noisysocks** [comment]
I agree that we will eventually need to be able to organise Reusable Blocks somehow. It's not clear how this will work right now, though, while so much is up in the air regarding Block Patterns and the Inserter. (See https://github.com/WordPress/gutenberg/issues/21080.)

**Comment by paaljoachim** [comment]
I added an issue a while ago in relation to adding a drop down to the Blocks inserter panel (the same principle can be added to Reusable blocks as well). https://github.com/WordPress/gutenberg/issues/26028

**Comment by paaljoachim** [comment]
Here is an update. Showing what it looks like today. 
Reusable blocks have their own tab in the Block Inserter panel. Like so:
![Screen Shot 2021-02-16 at 00 20 19](https://user-images.githubusercontent.com/5323259/108001471-d3203380-6fec-11eb-8019-fd7d03b0d318.png)

In relation to adding categories etc.
Here is an issue experimenting with patterns: https://github.com/WordPress/gutenberg/issues/28312
I believe the result can also be brought over to the Reusable blocks tab.

**Comment by jordesign** [comment]
Just checking on this for opinions on whether the new Patterns interface in the Site Editor, and changes in the Block Inserter has resolved this issue - or if user-designated categorisation of patterns would be helpful?

**Comment by richtabor** [comment]
>  if user-designated categorisation of patterns would be helpful

Yes, it will be!

**Comment by annezazu** [comment]
Closing this out as we have converted reusable blocks to synced patterns and categories are now possible/slated for 6.4: https://github.com/WordPress/gutenberg/issues/53164
