### ISSUE TITLE
Drag Blocks Past the Fold

### ISSUE THREAD

**Issue by themightymo** [WordPress/gutenberg#7609]
Thanks for your continued work on Gutenberg!  I'm loving it!!!!

**Is your feature request related to a problem? Please describe.**
When I drag a block, I often want to drag it past the "fold"/the bottom of the screen.

For example, let's say on my monitor, I can see 5 of 10 blocks (5 are below the fold).

I want to drag the first block to position 8.

The furthest I can drag it is position 5.

**Describe the solution you'd like**
Personally, I like to drag and use the scroll on my trackpad to go beyond the fold.  But I could also see other scenarios where simply dragging a block causes the view to move down beyond the fold.

**Describe alternatives you've considered**
The hack I use is to simply drag the block to the lowest possible position.  Then scroll the screen down.  Then re-drag the block lower.  Then scroll the screen down.  Then...etc.

**Comment by youknowriad** [comment]
It looks to work properly for me. Drag and Scroll. It may have been fixed already. Closing, let me know if it works for you.
