### ISSUE TITLE
Hook up text editor quicktags

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#761]

**Comment by iseulde** [comment]
That code is probably a decade old. :)

**Comment by iseulde** [comment]
In Calypso: https://github.com/Automattic/wp-calypso/tree/master/client/post-editor/editor-html-toolbar

**Comment by afercia** [comment]
Since WordPress 4.8 is going to drop support for old IE, worth considering to update the QuickTags code which still supports old IEs selection methods. See relevant ticket on Trac, now outdated: https://core.trac.wordpress.org/ticket/31661

**Comment by jasmussen** [comment]
Given other tickets surrounding text mode, as well as separate discussions on the future of how that works, I'm going to close this one for now. We may reopen if this becomes relevant again.
