### ISSUE TITLE
Gutenberg block “This block appears to have been modified externally” on save. Fine on frontend

### ISSUE THREAD

**Issue by kyle-jennings** [WordPress/gutenberg#7614]
Just starting to play with Gutenberg block development, and I am building a very simple button (yes I know buttons are already included, but this block will have lots of settings and classes not included in the core block).

Seem's pretty straitforward, but when I save the block and reload, I get a validation error and the "This block appears to have been modified externally" message.

```

    registerBlockType('franklin/button', {
    	title: 'Button',
    	keywords: ['button' ],
    	icon: 'admin-links',
    	category: 'layout',
    	attributes: {
    		text: {
    			source: 'text',
    			selector: '.button-text'
    		},
    	},
    
    	edit({attributes, setAttributes }) {

    		return (
    			<div class="guttenberg-usa-button">
    				<button class="usa-button">
    					<PlainText
    					  onChange={ content => setAttributes({ text: content }) }
    					  value={ attributes.text }
    					  placeholder="Your button text"
    					  className="button-text"
    					/> 
    				</button>
    			</div>
    		);
    	},
    	
    	save({attributes}) {
    		return (
    			<button class="usa-button">
    				{ attributes.text }
    			</button>
    		);
    	} 
    
    });

```
So in the editor, I'll add my block, modify the (button) text, save, and reload where I get the This block appears to have been modified externally" message.

Console shows the following error

    ```
    Expected:
   
    <button class="usa-button" class="wp-block-franklin-button"></button>
    
    Actual:
    
    <button class="usa-button" class="wp-block-franklin-button">testest</button>

    ```

I must be missing some fundamental concept or something, but I thought the save() function determines what gets displayed on the frontend which btw, looks as expected.

**Comment by youknowriad** [comment]
change `selector: '.button-text'` with `selector: '.usa-button'` And I expect the issue will be fixed. I'm closing let me know how it goes

**Comment by kyle-jennings** [comment]
omg, ok I need to wear my glasses, that fixed everything.  Lets just delete this and pretend nothing happened.

**Comment by kyle-jennings** [comment]
Oh ok I see now.  Because the source on the text attribute is set to "text", then React/Gutenberg knows that the data is bound to the text block within the element specified in with the "selector" property?   

I had set the selector to "button-text" so Gutenberg was looking for a text block inside an element classed as "button-text" right?

**Comment by youknowriad** [comment]
exactly 👍 more details on the attributes matchers here https://wordpress.org/gutenberg/handbook/block-api/attributes/
