### ISSUE TITLE
Converting from an audio block with a formatted caption to a file block results in an incorrect file link

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#7626]
**Describe the bug**
When converting from an audio block that has a formatted caption (bold/underlined/strikethrough formating applied) to a file block, the caption is expected to be displayed as the link to the file. However, the conversion process is not correctly removing the applied formatting, causing `[object Object]` to be displayed.

File block is a new block being introduced in #7622

**To Reproduce**
1. Create an audio block
2. Add a caption to the audio block with formatted text (e.g. bold, underline, strikethrough, italic)
3. Convert the audio block to a file block
4. Note that the file link contains `[object Object]` where formatting was applied

**Expected behavior**
Any formatting should be removed and purely the text of the caption should be shown as the file link

**Screenshots**
![formatting-bug](https://user-images.githubusercontent.com/677833/42084382-10bd0534-7bc0-11e8-9412-05bd1cf75d08.gif)

**Comment by sarahmonster** [comment]
This issue also exists when converting an image to a file:

![2018-07-30 14 14 13](https://user-images.githubusercontent.com/376315/43399423-e1cce18a-9402-11e8-8ec1-444b6a621356.gif)

**Comment by jorgefilipecosta** [comment]
This bug was solved during the changes to the formatting API.
