### ISSUE TITLE
Only allow one settings panel to be open at a time to make it easier to navigate panels

### ISSUE THREAD

**Issue by 2one2** [WordPress/gutenberg#7628]
**Is your feature request related to a problem? Please describe.**
Opening and closing panel bodies in inspector control is not the best user experience.
Having multiple panel bodies opened takes a lot of space and makes it harder to find the option you need to edit. 
Closing panel bodies is extra step for user that is unnecessary.

**Describe the solution you'd like**
Opening panel body should auto collapse other opened panel bodies.

**Comment by designsimply** [comment]
Tested and confirmed by opening the Text Settings, Background Color, Text Color, and Advanced panels all at once within the paragraph block settings. 

<strong>Video:</strong> [25s](https://cloudup.com/cpg7Atja0fT)

![screen shot 2018-07-02 at mon jul 2 7 30 09 pm](https://user-images.githubusercontent.com/1119271/42193890-8121cb6e-7e2e-11e8-82f4-7d250d55f010.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13863&action=edit running WordPress 4.9.6 and Gutenberg 3.1.1 using Firefox 61.0 on macOS 10.13.5.</sup>

**Comment by karmatosed** [comment]
Right now being able to have multiple panels open makes sense for cases where you maybe are working on the design using colors. Where this becomes possible to limit back is if we get in one grouping of color settings as in #6255. I do think as you can close and open this is a user specific decision and not something to limit. It's noticeable that WordPress doesn't limit this in core. As someone can choose to close that's still an option.
