### ISSUE TITLE
onChange produce a lot of server side calls

### ISSUE THREAD

**Issue by miljushm** [WordPress/gutenberg#7629]
When I have a server side rendering with a Gutenberg block and, let's say, a text field (argument) - each change (each typed character in the field) will produce one server side call. What would be the best way to improve perfomance and lower the number of server side calls? I mean, that type of behavior is OK when you change select option, have a checkbox or radio buttons but I am not sure that's the best way for text fields.

**Comment by youknowriad** [comment]
Well, server-side rendering in the `edit` block is not the recommended way to build blocks. It's a fallback in case you want to upgrade your current shortcodes etc... quickly but we definitely should implement a specific rendering for blocks in the `edit` function.

**Comment by youknowriad** [comment]
You can try to call the server side rendering only when the inputs lose focus.

**Comment by youknowriad** [comment]
I'm going to close this, let me know if it does solve your issue.

**Comment by miljushm** [comment]
Obviously the only solution :) It would be great to have a solution in the core itself and make the same UX for everybody...

**Comment by youknowriad** [comment]
As I said, this is a fallback and not the recommended way, so I don't think having a solution to do something like that in Core is valuable. Having the `ServerSideRender` component is already a tradeoff as we don't want people to go this road.
