### ISSUE TITLE
No way to lock aspect ratio in Image block when using height/width inputs in inspector

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#7636]
## The issue
The block inspector for the Image block contains input fields for manually setting the width and height of the image. However, there is no way to lock those values together so that increasing one will increase the other and preserve the aspect ratio of the image. I think this feature is important to make sure that the Image block is accessible, since keyboard users cannot use the drag handles to increase the size of the image.

## Related issues and PRs
- #3977
- #7637
- #7638

**Comment by designsimply** [comment]
Tested and confirmed there is no option to preserve image ratio in the image block settings.

![screen shot 2018-07-02 at mon jul 2 7 06 20 pm](https://user-images.githubusercontent.com/1119271/42193360-52ec9d76-7e2b-11e8-976d-e780d7685cad.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13859&action=edit running WordPress 4.9.6 and Gutenberg 3.1.1 using Firefox 61.0 on macOS 10.13.5.</sup>

For comparison, if I change the width or height for an image in the Image Details in the Classic Editor the corresponding number is adjusted automatically to preserve the image ratio.

![screen shot 2018-07-02 at mon jul 2 7 10 22 pm](https://user-images.githubusercontent.com/1119271/42193496-f49ce748-7e2b-11e8-8f02-0e6fc5a82b2c.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13859&action=edit&classic-editor running WordPress 4.9.6 and Gutenberg 3.1.1 using Firefox 61.0 on macOS 10.13.5.</sup>

**Comment by designsimply** [comment]
Closing in favor of #8397 which has this suggestion for improvement plus a few others that make sense to consolidate together.
