### ISSUE TITLE
Image block: width and height input fields in inspector do not start at current values

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#7638]
## The issue
The `Width` and `Height` input fields in the block inspector settings for the Image block have placeholder text displaying the current height and width. However, I think this is a bit misleading as when you try to change the input values by pressing the up/down arrows added by browsers, the inputs start at `0`. The inputs should start at the current width/height values.

## Related issues and PRs
- #3977
- #7636
- #7637
- #8397

**Comment by designsimply** [comment]
Tested and confirmed with the following steps:

1. Click the 'Add Block' button and select 'Image'.
1. Select an image from the media library or upload one.
1. Go to Settings > Block.
1. Place cursor in the `Width` field and press the up arrow.

<strong>Result:</strong> my original image width was 3868 and I expected that pressing the up arrow would change the number to 3869 but it changed to 1 instead.

![screen shot 2018-07-02 at mon jul 2 6 55 47 pm](https://user-images.githubusercontent.com/1119271/42193043-ab12ed36-7e29-11e8-9145-a40fda174992.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13859&action=edit running WordPress 4.9.6 and Gutenberg 3.1.1 using Firefox 61.0 on macOS 10.13.5.</sup>
