### ISSUE TITLE
Gutenburg breaks my code

### ISSUE THREAD

**Issue by Robotxm** [WordPress/gutenberg#7639]
**Describe the bug**
When I add code, Gutenburg will convert some characters to somethings unexpected.

**To Reproduce**
For example, if I add:
```
<html>
</html>
```
and save, what I get finally is:
```
&lt;html>
&lt;/html>
```
However, there's nothing abnormal when using TinyMCE.
**I am using Gutenburg 3.1.1**

**Comment by chrisvanpatten** [comment]
@Robotxm Can you share how you're adding this code? Are you going into code editor mode, or are you entering it through the visual interface?

Have you tried using an HTML block? That should preserve your markup.

**Comment by Robotxm** [comment]
@chrisvanpatten 
1. I add the code by clicking "+" -> "Formating" -> "Code" and typing what I mentioned.
2. If I click "+" -> "Formatting" -> "Code", go into code editor mode and type the code manually, it will display normally.
3. If I click "+" -> "Formatting" -> "Code" and type the code, then change into code editor mode, it will be broken.

**Comment by aduth** [comment]
The Code block is intended for code snippets, and is escaped the same as any other content.

If you want unescaped HTML, you should use the Custom HTML block instead, which will not escape the characters.

**Comment by Robotxm** [comment]
@aduth 
However, if I add a Shell code like this:
`echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf`
it will become:
`echo "net.core.default_qdisc=fq" &gt;&gt; /etc/sysctl.conf`

**Comment by aduth** [comment]
@Robotxm I'm not sure I understand. Are you adding that to the Code block? It should not be converting to `&gt;` and does not in my testing.

The original behavior is to prevent issues where e.g. typing `</pre>` in a code snippet example accidentally closes out of the code snippet and breaks the site layout.

**Comment by Robotxm** [comment]
@aduth 
Oh I find the reason.
I deleted  tag by accident. Actually it is my fault.
Thanks you very much for testing. 😄
