### ISSUE TITLE
Animate blocks as they are created

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#764]
This should be a satisfying "pop out" animation that plays only when new blocks are created, either at the end of the list of blocks, or when spitting blocks.

**Comment by karmatosed** [comment]
@shaunandrews do you think you could come up with some suggestions of this as you have done some animation experiments?

**Comment by shaunandrews** [comment]
![guten-add](https://user-images.githubusercontent.com/191598/30763418-142a6c54-9fb4-11e7-90be-1b6114924075.gif)

Here's a quick try at bringing some personality into the process of adding a new block. This is only one of many variations for how you add blocks, but seemed to be the most straightforward to start.

**Comment by jasmussen** [comment]
That animation, Shaun, is very very close to what I pictured way back in the day when I imagined a new block "satisfyingly being created". Love the elasticity.

**Comment by jasmussen** [comment]
Given recent changes to the design of the block outlines, and the rearranging of toolbars, and even though I opened this ticket myself, I'm going to close this one as "maybe revisit one day". The benefit of this was meant to add a bit of delight, but given the text flow improvements, it seems like it could be more of a distraction than delight, and so we should probably explore this after other alternatives for delight.
