### ISSUE TITLE
Dark Themes?

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#7645]
I've seen a few references in the Gutenberg code about styling for a dark theme. I assume this must be for themes with a dark bg?

How does a theme tell Gutenberg it is a dark theme? It looks like this would be used to style the editor buttons and controls for a dark bg theme (assuming the theme has styled the editor to display that dark bg)?

I'm giving a presentation at the Denver WordCamp  called "Make Your Theme Compatible with Gutenberg" at the end of July, and this would be a good thing to know. Thanks.

**Comment by ntwb** [comment]
I believe the "Dark Mode" featured plugin has (or will) support for Gutenberg:
> https://wordpress.org/plugins/dark-mode/

I'm not sure of the implementation details and @danieltj27 might able to add some more info on this here.

**Comment by weavertheme** [comment]
Some clarification:

In many of the components .sccs files, the selector .is-dark-theme is provided. From the names of the parent selectors of components covered by the rules, it seems they might fix the display of components and other items. But I can't find any mechanism that would cause the .is-dark-theme selector to actually be applied to anything. Seems as if these alternative selectors are just there for some future implementation? 

This issue is related to #6451

**Comment by danieltj27** [comment]
@ntwb 

> I'm not sure of the implementation details and @danieltj27 might able to add some more info on this here.

Dark Mode only supports TinyMCE's toolbar right now. Dark Mode will support Gutenberg at some point, but it depends on which is added to core first. I'd take a shot at saying Gutenberg would be added first then it'd just be a case of supporting a core feature rather than having to support a plugin as it's changing very rapidly and would be hard to keep up with.

I'd need to speak to the core team first though and coordinate an approach once the merge proposal has been done. It's currently a work in progress!

**Comment by karmatosed** [comment]
There are 2 options, one the dark mode plugin, potentially something being considered for core at a later point - it's not been decided to merge yet so that's worth considering there. The second is to have a style with your theme. Because of these two options lets close this issue.

**Comment by weavertheme** [comment]
Thanks for the reply.

There is no real issue with having a dark theme provide extra styling to override the default editor controls - it is just good to know that this is a theme issue. For the future, it might be nice if there was an API interface option (add_theme_support('dark_theme'), for example) that could trigger a more integrated approach to dark themes. But just knowing about the issue is a good thing, and I will include a note about this in the presentation I'm developing.
