### ISSUE TITLE
Child block side UI doesn't reposition in align-wide/full

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#7646]
When a block is aligned wide or full, side UI controls are repositioned above the block to ensure the controls are accessible.

![_untitled____add_new_page_ _mindful_ _wordpress](https://user-images.githubusercontent.com/1231306/42126382-c5fe816c-7c55-11e8-8525-cd3631c90696.png)

However, this does not apply to child blocks where the parent is aligned wide or full, causing the child's side UI controls to become unavailable:

![_untitled____add_new_page_ _mindful_ _wordpress_and_typinator](https://user-images.githubusercontent.com/1231306/42126395-091ff372-7c56-11e8-9042-1c78b5bf1edf.png)

(This would be solved by #6224.)

**To Reproduce**
1. Create a block that can be aligned wide or full, with an InnerBlocks component
2. Set the block alignment to full
3. Insert a child block
4. Note that you can't access the side UI controls

**Expected behavior**
Side UI controls should be accessible regardless of the block's alignment settings.

**Comment by designsimply** [comment]
I would like to help test this. Could you let me know an example core block which can be aligned wide or full or perhaps provide an example to use for testing purposes?

**Comment by chrisvanpatten** [comment]
@designsimply Sorry I missed your reply! At the moment, I don't believe any core blocks exhibit this behaviour. However, I think this will also be solved by #6224. I'd like to leave this open for now, but if it looks like #6224 is on the right path to land in Gutenberg (it's still a bit too soon to say), it'd be a good candidate for closure.

**Comment by chrisvanpatten** [comment]
This is still an issue although now only on the left side. I'm not sure I have a good idea on fixing this short of repositioning the movers entirely, but that's a bigger chat.
