### ISSUE TITLE
Popovers misplaced with RTL languages

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#7660]
Tested in Firefox, seems the popovers (or components that use popovers) positioning doesn't work well with RTL languages:

Main inserter tooltip:

<img width="635" alt="screen shot 2018-07-02 at 11 56 47" src="https://user-images.githubusercontent.com/1682452/42158127-e285728c-7def-11e8-86f8-846d548c3ca8.png">

Undo tooltip:

<img width="619" alt="screen shot 2018-07-02 at 11 56 36" src="https://user-images.githubusercontent.com/1682452/42158139-eb78ac88-7def-11e8-942f-c866f8281177.png">

More menu:

<img width="1284" alt="screen shot 2018-07-02 at 11 58 12" src="https://user-images.githubusercontent.com/1682452/42158177-0850d1a0-7df0-11e8-8aad-8704f2c5d6c7.png">

Date picker:

<img width="1284" alt="screen shot 2018-07-02 at 11 57 04" src="https://user-images.githubusercontent.com/1682452/42158192-12c688a0-7df0-11e8-98a0-5b79be196e3b.png">

Note: main inserter and undo tooltips seem to work in Chrome.

**Comment by simison** [comment]
Also when adding blocks in the editor:

<img width="673" alt="screen shot 2018-09-14 at 15 43 09" src="https://user-images.githubusercontent.com/87168/45550931-0c10b880-b835-11e8-80e9-733d3904856f.png">

Tested using https://wordpress.org/plugins/rtl-tester/

- Gutenberg v3.8.0
- WP v4.9.8
- Chrome v68

**Comment by afercia** [comment]
Tested again on latest master (4.2.0) and still happens:

<img width="721" alt="screenshot 2018-11-08 at 14 12 05" src="https://user-images.githubusercontent.com/1682452/48200813-928ed580-e360-11e8-9dc7-462fa40f5064.png">

<img width="1440" alt="screenshot 2018-11-08 at 14 12 31" src="https://user-images.githubusercontent.com/1682452/48200814-928ed580-e360-11e8-812c-66dc92ccff02.png">

Worth noting on _some_ buttons the tooltip position is correct (top bar add block, undo, redo, etc.) while on other buttons the tooltip is completely mispositioned.

I'd suggest to create a new GitHub label `RTL` to track all the issues related to right-to-left languages, though at 4 days from the scheduled Release Candidate it's a bti late perhaps.
