### ISSUE TITLE
Categories and tags are hidden if role is author or lower

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#7662]
When writing a new post as an `author`, I do not have access to the Categories and Tags sections in the sidebar. Only `editor` and above can see those. This was not the case in the Classic Editor.

WP 4.9.6, GTB 3.1

**Comment by danielbachhuber** [comment]
Hi @hedgefield,

Is this against a stock WordPress installation with no other plugins active? Can you verify you haven't modified your user roles in any way?

**Comment by hedgefield** [comment]
Hi Daniel, I looked into it further:

The bug occurs on our intranet, but we don't have a test env for that so I couldn't check for a plugin conflict there. So what I did was set up a fresh local WP install with Gutenberg 3.1.1. and installed all the plugins that we have on the intranet also.

And succesfully! The problem could be reproduced, and turns out it is the fault of the `The Events Calendar` plugin by Modern Tribe. I logged a bug report with them (https://wordpress.org/support/topic/gutenberg-bug/), hope to hear back soon what they did that tripped this flag. I don't think they modify any user roles (as the Categories and Tags are still available when using the Classic Editor or the Quick Edit on the Posts screen) so maybe a REST API issue, or something else unintended that clashes with Gutenberg.

You could probably close this in the meantime? I'll report back when I hear what the problem was.

**Comment by danielbachhuber** [comment]
Thanks for spending more time on it, @hedgefield.

It's worth noting our REST API modifications are a series of massive hacks right now (#6761). The implementation will be much more robust once https://core.trac.wordpress.org/ticket/44096 lands in core.

I'll follow the WordPress.org support thread to see whether any useful information arises.
