### ISSUE TITLE
Windows (Edge/Chrome), Ctrl + A only selects all text in a block the first time

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#7678]
Here's how selecting text works on a Mac:

1. Set the caret in text and press ⌘A, you select all the text in that block
2. Press ⌘A again to expand the selection, and select all blocks
3. If your caret is not in text, ⌘A directly selects all the blocks.

2 and 3 work in Windows browsers, 1 only the first time.

**To Reproduce**

1. Use Edge or Chrome on Windows, probably Firefox too. 
2. Write a post in Gutenberg.
3. Load this post fresh (or reload the editor)
4. Set the caret in text, press Ctrl+A, notice how all the text in the paragraph block is selected (as expected)
5. Press Ctrl+A again to expand the selection, notice how all blocks are selected (as expected)
6. Try to reproduce steps 4 and 5, and notice that on subsequent Ctrl+A combos, you can no longer just select all the text, now you can only select all the blocks.

**Expected behavior**

When the caret is in text, Ctrl+A the first time should select all the text.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Latest Edge, latest Chrome

**Comment by mtias** [comment]
Closing in favor of #7445.
