### ISSUE TITLE
Typing becomes more laggy the more blocks you have in a post

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#7680]
**Describe the bug**

Typing can become more laggy, and possibly totally unresponsive, the more blocks you have in a post.

**To Reproduce**
1. Start a new post with a single paragraph block.
2. Hold down a key. The key should repeat in the paragraph block and the browser should stay responsive.
3. Create an extra 30 paragraph blocks.
4. Hold down a key in one of the paragraph blocks. The editor will lag, and it's possible for the browser to freeze.
5. Take your finger off the key, and notice how long it takes for the editor to update.

**Expected behavior**

Typing in a paragraph block should be responsive no matter how many blocks you have in a post.

**Screenshots**

![lag](https://user-images.githubusercontent.com/3314354/42212319-a83a5886-7ead-11e8-8213-52d2f518052d.gif)

**Desktop (please complete the following information):**
 - Browser: Chrome, Firefox, Safari
 - Version: all latest versions

**Smartphone (please complete the following information):**
 - Device: Hauwei mate 10 pro - noticeable lag even with just one block

**Comment by notnownikki** [comment]
I've tested with a single paragraph block and 50 embed blocks all in the initial state, and I see the same behaviour, so it's not linked to the paragraph block, although paragraph blocks do render more slowly than the embed block in its initial state so you need fewer paragraph blocks to reproduce the problem.

**Comment by notnownikki** [comment]
Problem isn't in v3.0.1, but is in v3.1.0

I'll `git bisect` to see if there's a single thing that introduced it.

**Comment by notnownikki** [comment]
The CPU usage jumped up after this commit: https://github.com/WordPress/gutenberg/commit/2c2189c0480604694874ceb8e25cb51a557f3294

Before that commit, the steps in this issue do not reproduce the problem, and performance on my mobile devices is fine. With that commit, my browser freezes and there's noticeable lag typing on mobile.

cc: @aduth

**Comment by aduth** [comment]
>Before that commit, the steps in this issue do not reproduce the problem

By "before", do you mean the immediate parent commit 07cb2ce ?

**Comment by notnownikki** [comment]
@aduth yes, the immediate previous commit is fine, and performs fine on my mobile devices too.
