### ISSUE TITLE
Pressing enter too quickly can create broken paragraph blocks

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#7681]
**Describe the bug**

Paragraph blocks should have a single paragraph. It's possible to create paragraphs with line breaks, and break them out into weird, non-blocks.

**To Reproduce**
1. Start a new post with a single paragraph block.
2. Hold down Enter.
3. When you get paragraph blocks that contain more than one line, place the cursor in the middle of one and press enter. You end up with a weird orphaned block with no type.

**Expected behavior**

All enters sent should split the paragraph block, and we shouldn't have blocks with no type.

**Screenshots**

![hold down enter](https://user-images.githubusercontent.com/3314354/42212656-a7fc146c-7eae-11e8-9727-8cf3f19a7194.gif)

**Comment by mtias** [comment]
Closing in favor of #6021.
