### ISSUE TITLE
Uncaught TypeError in 3.1.1 (latest WP) when editing a post or page

### ISSUE THREAD

**Issue by devignerforhire** [WordPress/gutenberg#7682]
**Describe the bug**
In the latest 3.1.1 build, when editing a page or post there is a js error in the (chrome) console:

> Uncaught TypeError: e.action.indexOf is not a function at HTMLDocument.e (onloadwff.js:58)

**To Reproduce**
1. Fresh install of the latest WP (4.9.6)
2. Go to Plugins > Add New
3. Search for Gutenberg, install and activate
4. Go to a page or post, then open the developer console to see the error.

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra 10.13.4
 - Browser Chrome
 - Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by rfearing** [comment]
@devignerforhire I had the same error show up. Turns out it was from the LastPass chrome extension for me. May be the same for you. When I turned of LP extension it stopped showing up.

**Comment by devignerforhire** [comment]
@rfearing Thanks Ricardo - that was it. The client I'm working with uses LastPass throughout their org, so disabling the extension isn't an option. I'll get in touch with LastPass to see if they can fix the issue on their side.

**Comment by webthread** [comment]
I get the same error on the front-end with LP. No Gutenberg, so it may be a more general WP issue.

**Comment by iamgabrielma** [comment]
I'm unable to reproduce this with:
- Gutenberg 4.0
- WordPress 4.9.8
- OSX El Capitan 10.11.6
- LastPass
- Firefox and Chrome

**Comment by ellatrix** [comment]
Sounds like this is an issue with LastPass, which should be reported there if it still exists.
