### ISSUE TITLE
Add an "Insert File" Block

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#7683]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to Insert a file in Gutenberg :)
(apart uploading it in the media library and then copy-paste the link, but… erf ^^)

**Describe the solution you'd like**
Can you please consider to add a new block type : "Insert File"?

Also, WP Core can manage thumbnails for PDF files so it can be great to get them too (but not mandatory 😄 ).

Thanks, 
Jb

**Comment by gziolo** [comment]
It has already been implemented in #7622 and is going to be included in the upcoming 3.2 release 😄 

You can read more about it #5462.
