### ISSUE TITLE
Audit of "More options" block menu

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#7684]
This task is used to track consistency of the "More options" block menu, discuss and address the outstanding issues, if any: 

![more-menu-gut-gallery](https://user-images.githubusercontent.com/583546/42217707-84b801f6-7ec6-11e8-9553-bb6cec602fa5.png)

Block / Menu option | [Show / Hide] Block Settings  | Edit [as HTML / visually] | Convert to blocks | Duplicate | Convert to [Shared / Regular] block | Delete Shared Block | Remove Block
--- | --- | --- | --- | --- | --- | --- | --- |
Inline Image | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Paragraph | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
List | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Gallery | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Quote | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Image | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Heading | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Audio | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Cover image | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Subheading | ✔️ | if no sharedblock |  | if sharedblock | ✔️ | if sharedblock | ✔️ |
Cover image | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Custom HTML | ✔️ |  | [#7466 enable it if no sharedblocks](https://github.com/WordPress/gutenberg/issues/7466) | ✔️ | ✔️ | if sharedblock | ✔️ |
Classic | ✔️ | if no sharedblock | if no sharedblock | ✔️ | ✔️ [#5941 disable it](https://github.com/WordPress/gutenberg/issues/5941) | if sharedblock | ✔️ |
Code | ✔️ | [#6672 asks to enable it](https://github.com/WordPress/gutenberg/issues/6672) |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Preformatted | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Pullquote | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Table | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Verse | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
More | ✔️ |  |  | if sharedblock | ✔️ | if sharedblock | ✔️ |
Page break | ✔️ |  |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Button | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Columns (beta) | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Separator | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Spacer | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Text Columns | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Shortcode | ✔️ |  |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Categories | ✔️ |  |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Latest Posts | ✔️ |  |  | ✔️ | ✔️ | if sharedblock | ✔️ |
Embeds | ✔️ | if no sharedblock |  | ✔️ | ✔️ | if sharedblock | ✔️ |

**Comment by nosolosw** [comment]
@jasmussen @karmatosed @mtias While working on https://github.com/WordPress/gutenberg/issues/7466 I've prepared this table to help us track issues if any.

The main actionable question I have is: should the `Duplicate` option be available at all times for the `Subheading` and `More` blocks?

**Comment by nosolosw** [comment]
cc @noisysocks as per https://github.com/WordPress/gutenberg/issues/5941 in case you are aware of any other issues/cases

**Comment by Soean** [comment]
> The main actionable question I have is: should the `Duplicate` option be available at all times for the `Subheading` and `More` blocks?

Both blocks have a `supports` attribute `multiple: false`, because they should only appear once per post. Also if they are shared bocks, they shouldn't be duplicatable.

**Comment by jasmussen** [comment]
@nosolosw Solid work here, and I agree with Soean, if the block is not supposed to be used more than once, it would be nice to make the Duplicate menu item `disabled` in those situations. I wouldn't _remove_ the item, I think it makes more sense that it's disabled, that helps the spatial memory by not shifting menus around.

**Comment by nosolosw** [comment]
Got it. So the more directly actionable item would be the contrary to what I've initially proposed: disable the Duplicate option for `More` and `Subheading` blocks when they are shared blocks, as to avoid having twice of them in a Gutenberg post. At the moment I can get two by:

* create a `More` or `Subheading` block
* click `Convert to shared block` and save
* at this point, the duplicate option is shown in the options menu; click it to effectively have two of them in a post/page

An alternative could be to prevent them from becoming shared blocks altogether, but I guess there may be use cases where it'd be useful for a `Subheading` to become a shared block.

**Comment by mtias** [comment]
See also the final design proposal here: https://github.com/WordPress/gutenberg/issues/7433

**Comment by youknowriad** [comment]
Seems like this issue served its purpose and now we should close it in favor of small actionable issues.
