### ISSUE TITLE
Add in separators to block sidebar like document sidebar

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#7686]
Currently, accordion panels in the block inspector are unique from the document inspector, because they don't have separators.

![accordion](https://user-images.githubusercontent.com/1231306/42219435-f00db50e-7e99-11e8-8dc8-dc3cfa0cafc7.png)

This gets especially confusing when you have blocks with many options, because the panels can blend together, for example in one of our custom blocks:

![_untitled____add_new_page_ _mindful_ _wordpress](https://user-images.githubusercontent.com/1231306/42219529-35ba1b6a-7e9a-11e8-9f62-dd4d9a9810bc.png)

While I suspect this was originally an intentional choice (and it works well enough with core blocks, which are relatively option-light), I think greater consistency between Document and Block Inspectors could be beneficial, and improve 'scanability'.

**Comment by karmatosed** [comment]
@chrisvanpatten I hope it was ok but I adjusted the title to make sure it was I think what you wanted? I agree that both should reflect the same style. I don't see it as a design decisions that means we shouldn't implement.

@ajitbohra just a little note on good first issue, totally this could be but let's make sure we get design decisions in first to ensure those coming into that first issue are able to just work on it. Also I think this maybe is Chrome but those labels are a little confusing in this case.

**Comment by chrisvanpatten** [comment]
@karmatosed thanks! 4th of July prep got me sidetracked but I’ll work up a PR ASAP.

**Comment by karmatosed** [comment]
@chrisvanpatten awesome thanks and happy 4th of July for yesterday!

**Comment by chrisvanpatten** [comment]
Finally pushed up a commit for this! 💃
