### ISSUE TITLE
Request: Documentation/Default blocks - Meta 

### ISSUE THREAD

**Issue by Sephsekla** [WordPress/gutenberg#7696]
## Issue Overview

I've started learning to create custom blocks, and I think the ability to create blocks that update a meta value/custom field (with or without front end display) is proving to be very powerful, but I think it's not at all obvious that it is a feature.

I think that drawing more attention to this will have a positive impact on developer perception of the project.

## Possible Solution

At the moment documentation on this is relatively tucked away at https://wordpress.org/gutenberg/handbook/block-api/attributes/#meta, but given the importance of custom fields in many installations I think it warrants a top level section with some more in depth code examples.

I would also make the case for a default *meta* block with the option to update a meta field, to showcase the feature, 

I can provide the code examples of my own experiments (although I'm far from being a modern JS developer).

## Todos
- [ ] Code examples
- [ ] Documentation
- [ ] Meta block

**Comment by mkaz** [comment]
Meta block tutorial deployed in #12834 

You can view the tutorial at: https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/metabox/
