### ISSUE TITLE
Replace modal's focusOnMount with a optional string providing more options.

### ISSUE THREAD

**Issue by abotteram** [WordPress/gutenberg#7698]
**Is your feature request related to a problem? Please describe.**
The Modal component (#6261) has a prop that can be passed to it (`focusOnMount`) just like the Popover. In the popover this can optionally be a string providing more option where to focus when the component mounts.

As discussed with @aduth this feature should be included in a future iteration.

**Describe the solution you'd like**
Allow the `focusOnMount` prop (https://github.com/WordPress/gutenberg/tree/master/packages/components/src/modal#focusonmount) to be either a boolean or a string, following the same pettern and options as the [Popover](https://github.com/WordPress/gutenberg/blob/master/components/popover/README.md#focusonmount).

**Describe alternatives you've considered**

**Comment by draganescu** [comment]
Howdy @Xyfi I wonder how much of this does #19997 solve? If not completely could we push that to cover this issue completely?

**Comment by aduth** [comment]
@draganescu If I recall, the primary goal here was to align `Popover` and `Modal` in how this prop works. On a brief glance of #19997, it seems to move in that direction.

**Comment by paaljoachim** [comment]
This PR might be associated.
https://github.com/WordPress/gutenberg/pull/28574

**Comment by jordesign** [comment]
Just checking in on this request to see if it is still relevant - or if other changes to the modal have resolved it?

**Comment by jordesign** [comment]
With no further comments in the last month I'm going to close this issue. We can always re-open if needed.
