### ISSUE TITLE
Inline style pops up on highlight

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#77]
From prototype testing:

> I’m sure it’s just a fluke, but the inline style editing pops up when I highlight a word in another popup.

![gutenberg-inline-editing-oddities](https://cloud.githubusercontent.com/assets/253067/22972685/a6833214-f372-11e6-8577-d3b3981f51ef.png)

https://make.wordpress.org/design/2017/02/09/initial-gutenberg-prototype-editor-testing/#comment-25095

**Comment by jasmussen** [comment]
This should be fixed per a recent report.
