### ISSUE TITLE
Paste: cannot paste multiple lists with single list items

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#7702]
Steps to reproduce:

1. Copy some HTML with several successive lists in a row each with a single list item (see below).
1. Paste the HTML into the content area of a Gutenberg post.

<strong>Result:</strong> if I try to paste multiple successive lists with one list item per list, only the first list gets converted into a list block and the other lists go missing.

<strong>Video:</strong> [1m19s](https://cloudup.com/c15IYdgkWgj)
<sup>Tested with WordPress 4.9.6 and Gutenberg 3.1.1 on Firefox 61.0 on macOS 10.13.5.</sup>

![screen shot 2018-07-03 at tue jul 3 5 48 17 pm](https://user-images.githubusercontent.com/1119271/42250816-db67efbe-7ef0-11e8-8863-2ebf228eb046.png)

<strong>Sample content and screenshots of results:</strong> 

```
<ul>
<li>list item 1</li>
</ul>
<ul>
<li>list item 2</li>
</ul>
<ul>
<li>list item 3</li>
</ul>
```

```
<ul>
<li>een</li>
</ul>
<ul>
<li>twee</li>
</ul>
<ul>
<li>drie</li>
</ul>

<ul>
<li>vier</li>
</ul>
<ul>
<li>vijf</li>
</ul>
<ul>
<li>zes</li>
</ul>

<ul>
<li>zeven</li>
</ul>
<ul>
<li>acht</li>
</ul>
<ul>
<li>negen</li>
</ul>
```

```
<ul>
<li>one</li>
<li>two</li>
<li>three</li>
</ul>

<ul>
<li>four</li>
<li>five</li>
<li>six</li>
</ul>

<ul>
<li>seven</li>
</ul>
<ul>
<li>eight</li>
</ul>
<ul>
<li>nine</li>
</ul>
```

**Comment by designsimply** [comment]
Re-tested with 4.0.0-rc.1 and confirmed this is still happening. 

Aside: I had to copy and paste the sample code into a plain text editor this time to see the same problem happen. If I copy and paste the sample HTML from the GitHub issue directly, it becomes a Code block, which kind of makes sense but was unexpected to me.

![screen shot 2018-10-16 at 12 13 15 pm](https://user-images.githubusercontent.com/1119271/47037765-0f050e80-d13d-11e8-9d30-1328fcc89726.png)

**Comment by nosolosw** [comment]
In https://github.com/WordPress/gutenberg/issues/12029#issuecomment-440403496 I've noticed the same with converting to blocks from the classic block.
