### ISSUE TITLE
[terminology] replace "Fix toolbar..." with "Dock toolbar..."

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#7709]
### Reconsider the phrase "Fix Toolbar to Top"

**Reason 1:** more accurate term

- The word "fix" basically means to "make it stationary."
- The word "dock" means to "make it stationary **in a designated area**."
- Plus, the word "fix" has the secondary meaning of "repair" which is distracting.

**Reason 2:** typical usage in other software
- "Dock" is a common term for this purpose in other software packages.
- A first-time user will immediately understand what the option is for, without needing to first try it.

**Reason 3:** can eliminate the phrase "to the top
- If using the word "dock", it's doubtful that "...to the top" contributes anything.

### Summary
I recommend to change from "**Fix toolbar to the top**" to "**Dock toolbar**".

**Comment by michelleweber** [comment]
Honestly, I'm not sold on dock either; I think there are a lot of first-time users who won't immediately know this, and "Dock toolbar" doesn't feel detailed enough. Dock it where? To the top, to the side, to my post?

I'd recommend a word we already use for this same kind of purpose in other parts of WP: Stick, as in "Stick toolbar to the top." It's a more widely-understood word, the sentence is clear re: what is going to happen, and it's a consistent use of the "stick" idea.

**Comment by GlennMartin1** [comment]
If there is a "where" question that's not immediately obvious, then we should keep the "...to the top."

Stick vs Dock - I don't have a strong preference. But I dislike the "fix" term for this.

**Comment by ajitbohra** [comment]
@GlennMartin1 reopening this as PR is not yet merged.

**Comment by karmatosed** [comment]
Closing as said in closed PR we've not experienced this as an issue in testing but totally can look at this if get feedback repeatedly that it is an issue.
