### ISSUE TITLE
HOC: toggleAttribute

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#7717]
In the Audio and Video block we use `toggleAttribute` to toggle the block attributes like Autoplay or Loop. It was proposed in https://github.com/WordPress/gutenberg/pull/7672#discussion_r200212119 to implement it as a HOC and use it also in other components.

**Comment by youknowriad** [comment]
I think a HoC for this is overkill as it just adds a new public API for small value. I'm going to close this one.
