### ISSUE TITLE
E2E tests: Add test case which will validate that blocks render properly when their definition changes

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#7719]
Related PR which triggered this: #7672. It would also help to discover bug in #7349. Those are only examples from this week.

We often change block definitions by adding/modifying/deleting attributes or output HTML. This causes issues when no proper backward compatibility handling is provided. We should add end-to-end test which loads all blocks (similar to Demo post) and ensures that all those blocks render properly even though blocks has changed in the meantime.

**Comment by tofumatt** [comment]
I've never written an e2e test yet and this seems like a great way to fix that. 👍

**Comment by gziolo** [comment]
@jorgefilipecosta added basic integration for test fixtures which covers a deprecated version of two blocks (paragraph and columns). See:
https://github.com/WordPress/gutenberg/tree/master/packages/e2e-tests/fixtures/blocks

I think this is enough to consider it done. We have now an easy way to cover deprecated blocks in e2e tests.
