### ISSUE TITLE
List text indentation

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#772]
I noticed that the second line of text within a list item isn't aligned with the start of the text, but rather is aligned with the bullet. 

Ideally, the second line of text should align with the start of the first line.

**Current**
<img width="679" alt="screen shot 2017-05-11 at 10 45 57 am" src="https://cloud.githubusercontent.com/assets/2846578/25955417/3505b64a-3637-11e7-9823-cb8da9a74e26.png">

**Proposed**
<img width="679" alt="screen shot 2017-05-11 at 10 45 57 am" src="https://cloud.githubusercontent.com/assets/2846578/25955564/a25a7a32-3637-11e7-8c2a-295502f0628f.png">

**Comment by jasmussen** [comment]
Wonderful ticket! Yes!

**Comment by aduth** [comment]
I believe this has been resolved by #765 (related to #725)
