### ISSUE TITLE
Regression: Weird behavior with default appender, appears to create two blocks

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#7722]
There are a couple of issues present in `master` that were not in 3.1. 

1. Click the default appender ("write your story") in Chrome, notice how there's a weird flickering
2. Try in Firefox, note how an empty block is created. 
3. Try clicking below the appender, which should rediret the click to the appender — it appears two .blocks are created _until you move the mouse_.

[See videos of issues 1 and 2 here](https://cloudup.com/i7eBVeZShD0).

GIF of issue 3:

![3 2beta](https://user-images.githubusercontent.com/1204802/42319924-d3221f6e-8053-11e8-9818-3e1325fe162e.gif)

Compare with the behavior in 3.1:

![3 1 1](https://user-images.githubusercontent.com/1204802/42319962-ef9c7108-8053-11e8-8b75-5e414b0415c7.gif)

**Comment by jasmussen** [comment]
CC @mcsf

**Comment by aduth** [comment]
Taking a look.

**Comment by aduth** [comment]
Initial explorations show that this may be a regression of #7365
