### ISSUE TITLE
Add ability to use gettext/code inside markup string (eg PreviewButton's "Please wait")

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#7725]
As mentioned in #3301, `PreviewButton` has untranslated strings (https://github.com/WordPress/gutenberg/blob/master/editor/components/post-preview-button/index.js#L75), but we can't just put `__()` in there because we don't have React escaping.

https://github.com/WordPress/gutenberg/pull/3301/files#r148514197

**Comment by noisysocks** [comment]
Using Lodash's [`escape`](https://lodash.com/docs/4.17.10#escape) utility should be fine for this.

```diff
- <p>Please wait&hellip;</p>
+ ${ escape( __( 'Please wait…' ) ) }
```

**Comment by swissspidy** [comment]
Note that there's an existing PR: #10880

**Comment by aduth** [comment]
Related: #9846
