### ISSUE TITLE
Implement styleselect equivalent for inline/CSS-class formatting

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#773]
Current TinyMCE (and therefore the WordPress post editor) supports the `styleselect`. This is an excellent way to allow editors to apply classes to HTML elements which is a great way to handle inline formatting like making a button or non-wrapper-block-element formatting like giving a paragraph a "Notice" or "Intro text" style.

I currently don't see how this type of formatting would work with this editor, but losing this ability would be a huge loss for applying this kind of inline/simple formatting.

Is re-implementing this type of feature on the roadmap at all? Is there another way this could be handled? Making an entire block type just for a "button" feels like overkill and doesn't address the ability to create inline span styles.

- [TinyMCE documentation](http://archive.tinymce.com/wiki.php/Configuration3x:style_formats) | [TinyMCE Demo](https://www.tinymce.com//docs/demo/format-custom/) ("Formats" menu in second row)
- [Codex documentation](https://codex.wordpress.org/TinyMCE_Custom_Styles#Using_style_formats)
- [Example of usage from WordPress StackExchange](https://wordpress.stackexchange.com/questions/167685/add-css-class-to-link-in-tinymce-editor/167764#167764)

Here's a screenshot on a site I've implemented it on:

![image](https://cloud.githubusercontent.com/assets/1238696/25976494/30b64180-366a-11e7-9537-55a64e3a68b8.png)

**Comment by jasmussen** [comment]
Seems like the freeform block should potentially be able to support this:

https://github.com/WordPress/gutenberg/issues/365

I think of it freeform block as essentially the old editor in block form.

**Comment by mrwweb** [comment]
That seems like a good path forward.

The more I think about it, the scope of such a feature should probably be limited to applying inline CSS classes and/or markup (like `<mark>`) so that the idea of "block variants" (is there a term of that concept yet) is handled in a different way that can apply to all block types.

**Comment by mtias** [comment]
We have support for additional classes to be added via the inspector, so closing as covering the original intention.

**Comment by mrwweb** [comment]
@mtias Thanks for paying some attention to this ticket.

While adding a class to a block is useful for developers and power users, it is not the original intention of the ticket nor is it remotely close to feature parity with the `styleselect`.

In brief:

1. The `styleselect` can insert _inline_ markup and classes. (My primary usecase.)
2. The `styleselect` can insert multiple inline elements based on what is appropriate for the markup (<mark>, <span>, <small>, etc.)
3. The `styleselect` was a drop-down menu with user-friendly labels. The reason it was useful is you could let a user choose "Border Button" and not have to remember or conceptually grasp a `.prefix-button--border` class.

If you refer back to the screenshot, I think you'll see all of these aspects and hopefully understand why a textbox for CSS classes is a totally different feature and usecase.

**Comment by mtias** [comment]
@mrwweb apologies, I've been going through piles of issues today and my brain is a bit exhausted.

The screenshot shows what should really become blocks under gutenberg, discoverable in the main inserter. (We have a pull quote block already, for instance, and the others could likely be custom blocks provided by you to your users.) That's the whole point of blocks, to avoid users remembering markup or classes.

It'd be good to have more examples of what sort of inline treatments would be useful to have to figure out how to handle them.

**Comment by mrwweb** [comment]
@mtias not a problem. I kinda of figured this was at the end of a bug scrub. Thanks for all your work.

You're right that the first drop-down shown is basically blocks and the second contains some styles of blocks, but here are some examples where I don't see a current way to handle with Gutenberg:

- An inline button class (or similar style variant) added to a link
- A highlighted inline portion of text with `<mark>`
- An "intro text" style that can be applied to the first sentence of a paragraph
- [Edge case] A way to apply the `.screen-reader-text` class to a portion of a link to make it more screen reader friendly
- Anything else you'd want to do with a `<span>`

More than anything, I'd like to highlight that in both this ticket and #783 (basically this request but for blocks), the ability for the theme to define user-facing Names for classes and styles is incredibly powerful and useful. A CSS class field is useful, but my experiencing training users to use similar features (such as in the Make theme), it doesn't really "stick" for users and they always have to refer back to documentation to remember class names.

It's also worth noting that both tickets almost certainly require some form of editor styles (#422) so that applying the class to the editing interface can result in the user seeing what the theme has applied.

**Comment by thedonquixotic** [comment]
I'd like to chime in here and say I agree with @mrwweb that the inline styleselect feature is useful and distinct from applying additional css classes to a block.

**Comment by thedonquixotic** [comment]
Hahaha lol. I was writing a blog post when I realized I wanted to implement a tooltip style hover link for footnotes, so I googled around to see if this was possible in Gutenberg and I found this thread. I totally forgot I'd commented on it a couple of months ago. It's still a useful feature!

**Comment by tekTutorialsHub** [comment]
`<p>Here is the guttenberg paragrpah where i want  <span class="code">This is important</span> to be shown in some fancy style</p>`

The above is still possible, but to do that i need to click on Edit HTML and add the span class manually.

In the old classic editor all i need to do is to 
1. Select the Text 
2. Click on the Menu and click on the custom style (refer to the screenshot provided by OP @mrwweb )
3. The span class was automatically inserted.

**Comment by mrwweb** [comment]
Following up on @tekTutorialsHub's comment, #783 addressed block style variants (quite successfully!), but not inline style variants within text. That was the other place that `styleselect` shined, for inserting `<span>`, `<mark>`, etc. with one or more classes (and with the potential to scope styles to specific elements or contexts). That does still feel like a need, and being able to add the styleselect to the end of the floating toolbar would beautifully address the need.

Maybe this issue can be reopened? It's certainly a clearly-defined regression from the Classic Editor extensibility.

**Comment by thedonquixotic** [comment]
Yes, please reopen this issue! Inline style variants ARE NOT THE SAME as the block style variants. They have similar an complimentary functions but they are not the same, and an inline style variant solution is greatly needed before Gutenberg gets pushed to WP 5 as the default. 

As mrwweb says, allowing to add mark or span is an important function that can allow for flexibility in the presentation of special kinds of text that can't be covered by a block level class styling selector. 

As I've mentioned in this thread, use cases for this are things like: having the ability to to create a special class of links that present and function differently (such as creating an anchor link which has a non default class, allowing for different behavior, such as foot notes which link/pop up a modal etc), or to have selective emphasis on a specific set of words (that is different or alternative to merely bolding of italicizing the words). 

While it is possible to do this stuff using the Classic Editor or to use an HTML block, it does not fit with the overall design of Gutenberg and prevents Gutenberg from acting as a true default editor. This isn't a particularly difficult design problem to address, and it should not be seen as adding unnecessary extras to the toolbar, it is only adding a single extra dropdown which has already been suggested by others as a solution to the issue of block level style variants, so I don't see why it shouldn't' be acceptable for inline stuff.

**Comment by chrisvanpatten** [comment]
I think this is covered in #4658 which is still open. Definitely recommend following along there.
