### ISSUE TITLE
Filter images by "Uploaded to this post type"

### ISSUE THREAD

**Issue by cr101** [WordPress/gutenberg#7736]
The current Classic Editor provides the ability to filter images by "Uploaded to this custom post type" (screenshot below), however, after I activate Gutenberg this functionality disappears. This feature is very useful and I use it daily.

![screenshot_1](https://user-images.githubusercontent.com/4064582/42355612-0ba09342-8122-11e8-9489-b14d34332627.jpg)

**Comment by danielbachhuber** [comment]
Hi @cr101,

Thanks for the report. Your screenshot indicates "Uploaded to this organization", which isn't a core WordPress feature. Do you know which plugin might be adding that?

Re: "Uploaded to this post", it looks like that was discussed before in #2218

**Comment by cr101** [comment]
Yes my issue is the same as [#2218](https://github.com/WordPress/gutenberg/issues/2218) and I use that feature every single day. Being able to filter the files by "Uploaded to this Post" and "Unattached" when you have thousands of images and PDF files is incredibly useful.

Please add the missing Select dropdown.

Classic Editor
<img width="234" alt="screenshot_17" src="https://user-images.githubusercontent.com/4064582/42411030-8baabd02-8248-11e8-8242-bd2c74e19748.png">

Gutenberg Editor (select box is missing)
<img width="214" alt="screenshot_18" src="https://user-images.githubusercontent.com/4064582/42411041-cbbff1fa-8248-11e8-8010-49fc5a565091.png">

**Comment by danielbachhuber** [comment]
Closing in favor of #8748 which is a bit more specific to existing WordPress behavior.
