### ISSUE TITLE
add_meta_box not working

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#7738]
Trying `add_meta_box` but it's not working. I've tried installing Yoast( @IreneStr  ) plugin to check the issue too and there metabox is also not showing on Gutenberg Editor. Works fine on classic editor though. Thanks!

**Comment by Soean** [comment]
I can see the Yoast metabox in Gutenberg. Do you have any other plugins installed?

**Comment by phpbits** [comment]
@Soean The issue is when `wp-edit-post` is added on the script dependencies. The metaboxes are not showing. You can give it a try and let me know how it goes on your end too. Thanks!

**Comment by phpbits** [comment]
@Soean Just following this up. Thanks!

**Comment by aduth** [comment]
I believe this is the same issue as described in #6963 . The current workaround is to specify the `$in_footer` argument when enqueueing your script. This should ideally not be necessary long-term, tracked as goal of #6963.
