### ISSUE TITLE
Content overlaps Yoast Notifications

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7744]
**Describe the bug**
I don't know if this is a Gutenberg issue or a Yoast SEO issue, but Gutenberg content is overlapping notices displayed by Yoast SEO.

If you look at the html in the developer tools at the bottom of the screen, you can see that there's actually supposed to be two Yoast notifications. You can only see one notification though as the other is hidden below the Gutenberg Post Header

![screenshot_722](https://user-images.githubusercontent.com/2078245/42371711-9b4deb30-8153-11e8-97a1-37acd68c6561.png)

It's also impossible to dismiss either notification.

**To Reproduce**
1. Update to latest version of Yoast and edit a page

macOS Sierra 10.12.1 
Firefox Quantum 61.0 (64-bit)
Yoast  7.7.3
Gutenberg 3.1.1

**Comment by tofumatt** [comment]
Gutenberg notifications, to my knowledge, don't have that problem so I'd think this is an issue with Yoast SEO's styles. If you could file an issue with Yoast to start with that'd be great as I think this is an issue with their plugin.

That way they can check it out and either fix it, or tell you/us that in fact it *is* a bug with Gutenberg and then we'll know and can work on fixing it 😉

I'll close this as won't fix for us for now as I don't think it's a Gutenberg issue, but if I'm wrong on that please say so here and we'll re-open 😄

**Comment by maddisondesigns** [comment]
Just as an FYI, after some further testing I have raised a support ticket with Advanced Custom Fields. It seems to only happen with the Release Candidate for their new version 5.7.0.
