### ISSUE TITLE
Changelog String Fixes

### ISSUE THREAD

**Issue by garrett-eclipse** [WordPress/gutenberg#7758]
**Describe the bug**
I came across two string issues in the changelog when translating.

1. update behaviours to behaviors
Permalink - https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev-readme/en-ca/default?filters%5Boriginal_id%5D=6334896

2. First colors should be singular so ‘color slugs’ rather than ‘colors slugs’
Permalink - https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev-readme/en-ca/default?filters%5Boriginal_id%5D=6334858

*I tried to find these in the project to push a PR but couldn't if someone could point out where they are I'd be happy to generate a PR.

Thanks

**Comment by Soean** [comment]
The readme.txt and changelog.txt are only on the plugin SVN repository, not on GitHub. So a PR is not possible. Only someone with plugin commit access can change these strings.

**Comment by garrett-eclipse** [comment]
Hey @Soean I came across some more listed below. As no action has been taken I assume I don't need a new ticket but let me know if you'd rather it separated into a new issue. Thanks

Additional Localization issues;

1. Update favour to favor
Permalink - https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev-readme/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6434009&filters%5Btranslation_id%5D=56444446

2. Update colour to color and off-centre to off-center
Permalink - https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev-readme/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6433996&filters%5Btranslation_id%5D=56444485

3. Update colour to color
Permalink - https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev-readme/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6433995&filters%5Btranslation_id%5D=56444487

4. Update Standardise to Standardize
Permalink - https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev-readme/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6434016&filters%5Btranslation_id%5D=56444425

All the best

**Comment by aduth** [comment]
Since there is no actionable item here for the repository, I'm going to close this issue.

I'm unsure what process would typically be recommended for future change requests. @Soean do you have any advice here?

**Comment by Soean** [comment]
Yes we can close this ticket.
I think there's no better way than to open an issue at GitHub. Should we discuss it on the weekly chat?
Maybe, in the future, we change the generation of the changelog to a more automated process, then we would have other options.

**Comment by aduth** [comment]
>I think there's no better way than to open an issue at GitHub. Should we discuss it on the weekly chat?

Could you describe the problem in an agenda item when the post is published?

>Maybe, in the future, we change the generation of the changelog to a more automated process, then we would have other options.

Yeah, I think the idea of automating these changelogs has been bounced around a few times before, and this could fit well into that conversation. Is the main idea to have a canonical resource for which strings are new or have been changed version-to-version?
