### ISSUE TITLE
[3.2 regression] Shortcodes no longer convert to Shortcode blocks...

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#7759]
**Describe the bug**
Type or paste a Shortcode. Since 3.2, it no longer converts to a Shortcode block.

**To Reproduce**
1. Open a new post/page
2. in a new paragraph, type/paste a Shortcode, i.e. [shortcode]
3. Press enter
4. The paragraph block is not converted to a Shortcode.

**Expected behavior**
Should convert to a Shortcode, as before 3.2.

**Comment by mtias** [comment]
This works for me if I paste `[gallery ids="378,5"]` or an unrecognized shortcode:

![image](https://user-images.githubusercontent.com/548849/42448910-20b44e90-837f-11e8-9640-912674fef157.png)

**Comment by GlennMartin1** [comment]
A few observations:

Important to observe the differences between **typing** and **pasting**

**TYPING SHORTCODES**
- Shortcodes **typed** into a paragraph block do not convert.
-- For example, in a paragraph block, type [shortcode_example] and press Enter. Does NOT convert.

-------------

**PASTING SHORTCODES**
- Shortcodes **pasted** into a paragraph block do not convert
-- For example, type [shortcode_example] in a text-editor (outside of Gutenberg). Cut and paste into Gutenberg. The paragraph block does NOT convert.

- EXCEPTION: if that shortcode text was first cut/copied from a Gutenberg paragraph block.
-- For example, type [shortcode_example] in a Gutenberg paragraph block. Cut and re-paste back into the paragraph block. Since 3.2, this is the only way a shortcode will convert.

**Comment by GlennMartin1** [comment]
Issues with pasting were fixed in 3.3.

I think it's reasonable that shortcodes typed into a paragraph block would convert, correct?

**Comment by danielbachhuber** [comment]
> I think it's reasonable that shortcodes typed into a paragraph block would convert, correct?

Hm, I'm not sure I agree with this. Having the user explicitly create a Shortcode Block seems like a more robust UX.

Also, this would mean the user wouldn't be able to type shortcode-like content into the Paragraph Block.
