### ISSUE TITLE
Can't insert Inline Image into Classic Block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7762]
**Describe the bug**
The new Inline Image functionality lacks support for inserting images into the Classic Block.

When 5.0 rolls out, everyone's existing content is going to be converted to Classic Blocks as soon as they try to edit it. If you currently have inline images in your content, it's going to be impossible to edit your content unless you convert everything to blocks. Some people might not want to convert the content to blocks, but instead, leave it all in the classic block. By not allowing support for Inline Images in the Classic Block your forcing them to convert content they may not want to convert. The Classic block needs support for Inline Images.

**To Reproduce**
1. Add Classic Block
2. Try to insert an Inline Image

**Expected behaviour**
I should be able to edit exiting content without being forced to convert it to blocks.

macOS 10.12.1
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.2.0

**Comment by mcsf** [comment]
Makes sense to have this. Looping in @iseulde, as we can just extend Inline Images functionality to the Classic block.

**Comment by kjellr** [comment]
Not sure if this is related, but when you drag an image over the classic editor block, some sort of white shape/overlay appears on top of the block. This looks like it might be a remnant of a drop zone:

![inline-images](https://user-images.githubusercontent.com/1202812/43536750-60db1daa-958b-11e8-89d2-e49535d95f10.gif)

(Of course, when you let go of the image, it doesn't get inserted into the classic block.)

**Comment by iseulde** [comment]
Well, the Classic block is not a `RichText` field, it's a custom TinyMCE field. Maybe in this case it's better to add a TinyMCE button to the toolbar instead.

**Comment by La-Geek** [comment]
Full agree with @maddisondesigns. Also the inline image should be editable. Atm you have only the option to insert the image, e.g. in paragraph block, but then you can do nothing with the image, the pop up panel with alignment and edit is missing.

Also the general option to insert media would be very appreciated (PDFs, Docs, gallery, etc.). The Gutenberg gallery block is missing features that you have in WordPress < 5.0 in TinyMCE. So it would be great to have the same options as before with classic editor.

**Comment by ahmadawais** [comment]
I have the same issue #8778

All of my older posts got converted to the classic editor block. But there's no way for me to add a new image inside the classic editor block.

![image](https://on.ahmda.ws/0k0g3N0T0X1a/c)
Peace! ✌️

**Comment by brandonpayton** [comment]
Adding priority to this as it was called out in core dev chat with a lot of interest.

**Comment by mrpritchett** [comment]
Echoing that this is a big issue. We have almost 2000 post authors. Many with no experience beyond Word. Converting to a classic block is our plan until we can provide Gutenberg training (as we live in a highly distributed content management, enterprise environment) on a case by case basis. Without the ability to edit/insert images in that block, there is no hope of updating to Gutenberg at all. We'll be forced to use the Classic Editor Plugin indefinitely.

**Comment by mrpritchett** [comment]
A current workaround for those that have content converted from the classic editor into a classic editor block, but no other blocks on the page/post is to switch to the TinyMCE editor. Content is still editable there (including images) and can be migrated back at any point.

**Comment by La-Geek** [comment]
Any progress/news here?

Another good argument for this is: Users could only use this block and would have the same as before with the TinyMCE editor. 

Prerequisite that!
1.) an "add media" button is added to the toolbar and 
2.) Third party plugins can add their buttons to this toolbar (think of an "add shortcode button" as an example).

This would eliminate a lot of criticism because these users could simply ignore the other blocks and have the same workflow as before.
