### ISSUE TITLE
Block style variant labels

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#7768]
Style variant for blocks is a great feature. For example Button block have 3 style variations with these labels:

- Rounded
- Outlined
- Squared

However how these labels can be changed? For example theme might not have `Rounded` button style at all.

**Comment by benoitchantre** [comment]
I would not use labels related to a specific style. I think is the responsability of the theme to define the appeareance of the buttons.

I would rename the labels to:

- Primary (default)
- Secondary

Secondary could be opt-in with `add_theme_support`.

**Comment by paaljoachim** [comment]
Hey @samikeijonen and @benoitchantre 
Has there been any update of these matters in Gutenberg?

I will ping Isabel. As she might have some view points on this issue.
@tellthemachines

**Comment by tellthemachines** [comment]
Default style variations (such as `fill` and `outline` for the Buttons block) come with basic styles attached, so they'll work even if themes don't add styling for them. If you'd like to remove a style variation altogether, you can use `wp.blocks.unregisterBlockStyle()`. Check out [these docs](https://developer.wordpress.org/block-editor/developers/filters/block-filters/) for more info.

Themes can also define additional style variations and name them as they see fit. As an example, check out the Image `frame` and Columns `overlap` styles in [Twenty Twenty One](https://wordpress.org/themes/twentytwentyone/). 

Hope this helps! I'll go ahead and close the issue as there's nothing actionable here.
