### ISSUE TITLE
Block style variant preview styles

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#7769]
For example Button block have 3 style variants. In the editor I can bring my own styles for these variants.

For example default button style:

<img width="254" alt="button default style" src="https://user-images.githubusercontent.com/1820415/42410266-c4b4d172-81ef-11e8-9ca5-7cadb050a01b.png">

However in the preview styles seems to come from default Core styles:

<img width="606" alt="button default style preview" src="https://user-images.githubusercontent.com/1820415/42410287-fe740fe0-81ef-11e8-8424-765b06df40fc.png">

I'd except my styles to work on preview automatically. This was kind of hard to debug since the preview was populated dynamically on hover.

For the button block itself I have `.edit-post-visual-editor .wp-block-button__link {}`.

**Comment by karmatosed** [comment]
I agree the preview should be 'what you'd expect in theme using'. I am not sure in saying that the technical implications, but let's find out!

**Comment by SuperGeniusZeb** [comment]
@samikeijonen Just to be clear, do the preview styles look like what the block looks like in the editor, and do the editor styles look like the theme styles?

I guess this kind of comes back to long-term wanting Gutenberg to directly use the main theme CSS to style blocks in the editor. What were the obstacles to having that right now? @karmatosed

**Comment by samikeijonen** [comment]
@SuperGeniusZeb I have screenshots in the first comment what the block looks like in the editor, and what does it look like in the preview.

Note that I dequeue `wp-core-blocks` and even deregister `wp-core-blocks-theme`. That's why it's even more weird that I get "Core styles" in the preview from somewhere.

**Comment by youknowriad** [comment]
@samikeijonen  I think the issue is that he’s using `.edit-post-visual-editor` as a namespace and since popovers are rendered outside of the editor’s namespace it doesn’t work.

Can I suggest to just use `.wp-block-button__link {}` to style your button and enqueue the style using the editor styles https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#editor-styles ?

**Comment by youknowriad** [comment]
Noting that I also opened this PR #10956 which make sure we explicitly apply the editor styles (provided following the approach from the link above) to the previews.

**Comment by samikeijonen** [comment]
Thanks @youknowriad. True, I was using `.edit-post-visual-editor` as a namespace. 

I tried the editor styles way but that didn't quite worked for me. At the moment I'm using PostCSS to roll namespace automatically. I'll let you know what I come up with.

**Comment by strarsis** [comment]
Would hovering a variant selection already show a preview in editor?

**Comment by youknowriad** [comment]
@strarsis It shows a preview on the right of the "popover", not directly in the editor.

**Comment by designsimply** [comment]
@samikeijonen I can help test this but would need really clear instructions. Any chance you can provide a code snippet for your button style variation and help me understand exactly where to add it for testing?

**Comment by samikeijonen** [comment]
@designsimply In my short test button variant styles now works. I'm going to close this for now, I'll re-open if I find something.
