### ISSUE TITLE
format="string" for RichText components not working

### ISSUE THREAD

**Issue by jmau111** [WordPress/gutenberg#7792]
it's possible to specify format="string" for RichText components but I get weird escaped strings on front (save) such as : 

```<p><em><strong>I walk the line</strong></em></p>```

Why is that so ? Is it a bug ? cannot find similar issues (sorry if it's a duplicate).

**Comment by ajitbohra** [comment]
@jmau111 kindly share the code snippet

**Comment by ajitbohra** [comment]
Was able to replicate this I guess its expected behavior as you have specified format as `string` removing the format props will render elements.

cc: @youknowriad @aduth

**Comment by aduth** [comment]
@ajitbohra @jmau111 Could one or the other of you share a complete code snippet example.

Trying to understand from the report: Is the HTML shown as plain-text ? i.e. not an actual bold, italicized paragraph, but the HTML markup for one?

**Comment by ajitbohra** [comment]
@aduth 

Save output 

![richtext error](https://user-images.githubusercontent.com/1039236/42457696-c41d5fdc-83b5-11e8-9a0c-86649bb527b6.png)

``` jsx
const { __ } = wp.i18n;
const { registerBlockType } = wp.blocks;
const { RichText } = wp.editor;

registerBlockType( 'cgb/block-block-test', {
	title: __( 'Block Test' ),
	icon: 'shield',
	category: 'common',
	keywords: [
		__( 'Testing' ),
	],

	edit( { className, attributes, setAttributes } ) {
		return (
			<RichText
				format="string"
				tagName="h2"
				className={ className }
				value={ attributes.content }
				onChange={ ( content ) => setAttributes( { content } ) }
			/>
		);
	},

	save( { attributes } ) {
		return <RichText.Content tagName="h2" value={ attributes.content } />;
	},
} );

```

**Comment by jmau111** [comment]
yes @aduth it's plain text, seems like <p> is written like that : &lt;p&gt; for example

**Comment by jmau111** [comment]
seems related to this  https://github.com/WordPress/gutenberg/blob/master/editor/components/rich-text/format.js#L84

**Comment by aduth** [comment]
In the snippet, `RichText.Content` requires a `format="string"` prop just like as in the `save`. Can you let me know if that makes a difference.

**Comment by ajitbohra** [comment]
Adding `format="string"` to `RichText.Content` solves the problem on the frontend but breaks the edit view and throws `This block appears to have been modified externally.`

**Comment by jmau111** [comment]
@aduth this solves everything, 
@ajitbohra the html markup has changed so, to me it's solved, I'm closing this issue.

thanks a lot !

**Comment by jmau111** [comment]
@ajitbohra yes everything is fine on my install. I've done the same setups.
