### ISSUE TITLE
Fitting image to whole view makes arrows disappear

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#78]
From prototype testing:

> This is a small problem, but I found that fitting the image to the whole view makes the up and down arrows disappear. It’s something that I haven’t seen mentioned in the comments so far.

https://make.wordpress.org/design/2017/02/09/initial-gutenberg-prototype-editor-testing/#comment-25109

**Comment by jasmussen** [comment]
Closing this in favor of #110 as that ticket sort of serves as an umbrella ticket for the side UI.
