### ISSUE TITLE
Add `CHANGELOG.md` files for each package

### ISSUE THREAD

**Issue by ntwb** [WordPress/gutenberg#7800]
@ntwb commented on [Tue May 01 2018](https://github.com/WordPress/packages/issues/118)

A [Slack discussion last week](https://wordpress.slack.com/archives/C5UNMSU4R/p1524576726000324) raised the issue of creating CHANGELOG.md for each package.

Lerna can help with that https://github.com/lerna/lerna#--conventional-commits

> `$ lerna publish --conventional-commits` (Can also be set in `lerna.json`)

When run with this flag, _publish_ will use the [Conventional Commits Specification](https://conventionalcommits.org/) to [determine the version bump](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump) and [generate CHANGELOG](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli) files for each package automatically.

Conventional Commits can be fully customized, a common implementation of this seen in widespread use thoughout GitHub is [Angular](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type) implementation, prefixing commits with `docs:`, `fix:`, `ci:`, `chore:` and so on, when working with _scoped_ packages the format takes on the _package name_ as the scope, e.g. `docs(i18n):`, `docs(a11y):`, `docs(is-shallow-equal):` etc

Even though the Angular format above is quite common _Conventional Commits_ is fully customizable and there are a numerous configurations available to be used from projects such as [ESLint, Atom, jQuery to name but a few](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages).

One of particular note is the [jQuery preset](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-jquery) where commits should look like:
```shell
Component: Short Description

Optional Long Description

Fixes #xxx
Closes gh-yyy
Ref #zzz
```

This matches quite closely the WordPress [commit message](https://make.wordpress.org/core/handbook/best-practices/commit-messages/) format documented in our handbook: 
```shell
Component: Brief summary.

Longer description with more details, such as a `new_hook` being introduced with the context of a `$post` and a `$screen`.

More paragraphs can be added as needed.

Props person, another.
Fixes #30000. See #20202, #105.
```

By mixing the _scope package names_ with our own WordPress _Conventional Commit Preset_ we could have our CHANGELOG.md files generated using a format common to existing WordPress processes which would be benfecial if the _packages_ repo is to get merged into SVN.

---

@atimmer commented on [Tue May 01 2018](https://github.com/WordPress/packages/issues/118#issuecomment-385675391)

Like I said int he #core-js meeting this week, I think this ties into @pento's proposal to only use squash commits when merging PRs on WordPress GitHub repositories. The squash pull request merge UI allows one to change the title and message of the squash commit:

<img width="706" alt="screen shot 2018-05-01 at 15 48 09" src="https://user-images.githubusercontent.com/584693/39475142-6ad54262-4d57-11e8-8e1a-321f2dbfb8f6.png">

That would remove the burden on new contributors completely. All maintainers would then make sure that this format is followed on the packages repository.

---

@ntwb commented on [Tue May 08 2018](https://github.com/WordPress/packages/issues/118#issuecomment-387393532)

Instead of hacking on _changelogs_ here in this repo, I've just created https://github.com/ntwb/lerna-playground to work on implementing a _"Conventional Commits Specification"_.

If you'd like access to push, pull, and hack on that repo please ping me here or in Slack and I'll add you.

---

@gziolo commented on [Thu May 10 2018](https://github.com/WordPress/packages/issues/118#issuecomment-388023510)

I would be happy to see something like this helping with changelog files. 👍 

---

@aduth commented on [Wed May 23 2018](https://github.com/WordPress/packages/issues/118#issuecomment-391341430)

This should also be codified in `CONTRIBUTING.md`. Also mention of when `CHANGELOG.md` edits should be made (as part of proposed changes, or prior to release).

Related discussion: https://github.com/WordPress/packages/pull/128/files#r190238611

**Comment by aduth** [comment]
I'm going to close this as largely satisfied by #8768
