### ISSUE TITLE
Suggestion for CSS in admin to avoid paragraph margin inheritance

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#7809]
Hi everybody

I'm using Gutenberg for some time and something bothers me a little : 

Some "global" styles as `.edit-post-visual-editor p {}` are a bit annoying. And not future proof (where CSS is meant to be applied at a component level only. 

I'm not sure if it's a good idea but, in order to limit admin style overrides in custom blocks, it could be cool to apply margin on <p> only for direct children : 

`.edit-post-visual-editor > p {}` 

So when someone is making a custom bloc `div.myblock p` : this p won't have default margins.

It could save hassle for custom blocks developers. Not sure tought if this approach may have side effects. 

What do you think ? Good or bad (or really bad) idea?

**Comment by mtias** [comment]
Seems sensible to me.

**Comment by karmatosed** [comment]
👍 from me.

**Comment by tellthemachines** [comment]
Apart from `box-sizing` and some form-related resets, there don't seem to be a lot of styles attached to descendants of `.edit-post-visual-editor` anymore. Is this issue still relevant?

**Comment by mtias** [comment]
I think we should close and revisit any specific issues that might be lingering when they surface.
