### ISSUE TITLE
'Insert from Media Gallery' button not working

### ISSUE THREAD

**Issue by maxduyck** [WordPress/gutenberg#781]
Unable to open the media gallery when adding a new image block.
![screen shot 2017-05-12 at 14 40 39](https://cloud.githubusercontent.com/assets/20770329/25998440/376c6506-3721-11e7-90c0-ec552198e43e.png)

**Comment by youknowriad** [comment]
This hasn't been done yet. I'd consider this issue a duplicate to #418

**Comment by nylen** [comment]
Yep, closing in favor of #418
