### ISSUE TITLE
Initial `@wordpress/licenses` package

### ISSUE THREAD

**Issue by ntwb** [WordPress/gutenberg#7813]
@ntwb commented on [Thu May 24 2018](https://github.com/WordPress/packages/pull/132)

Initial `@wordpress/licenses` package for use in #129 & #130

---

@codecov[bot] commented on [Thu May 24 2018](https://github.com/WordPress/packages/pull/132#issuecomment-391555653)

# [Codecov](https://codecov.io/gh/WordPress/packages/pull/132?src=pr&el=h1) Report
> Merging [#132](https://codecov.io/gh/WordPress/packages/pull/132?src=pr&el=desc) into [master](https://codecov.io/gh/WordPress/packages/commit/04093f52d024f5eca9b639ab593ffb6a830c512a?src=pr&el=desc) will **increase** coverage by `0.69%`.
> The diff coverage is `100%`.

[![Impacted file tree graph](https://codecov.io/gh/WordPress/packages/pull/132/graphs/tree.svg?height=150&width=650&token=9Zw9xmxPWW&src=pr)](https://codecov.io/gh/WordPress/packages/pull/132?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##           master    #132      +/-   ##
=========================================
+ Coverage      67%   67.7%   +0.69%     
=========================================
  Files          58      60       +2     
  Lines         697     709      +12     
  Branches      145     151       +6     
=========================================
+ Hits          467     480      +13     
+ Misses        187     186       -1     
  Partials       43      43
```

| [Impacted Files](https://codecov.io/gh/WordPress/packages/pull/132?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [packages/licenses/ossLicenses.js](https://codecov.io/gh/WordPress/packages/pull/132/diff?src=pr&el=tree#diff-cGFja2FnZXMvbGljZW5zZXMvb3NzTGljZW5zZXMuanM=) | `100% <100%> (ø)` | |
| [packages/licenses/gpl2Licenses.js](https://codecov.io/gh/WordPress/packages/pull/132/diff?src=pr&el=tree#diff-cGFja2FnZXMvbGljZW5zZXMvZ3BsMkxpY2Vuc2VzLmpz) | `100% <100%> (ø)` | |
| [packages/scripts/utils/index.js](https://codecov.io/gh/WordPress/packages/pull/132/diff?src=pr&el=tree#diff-cGFja2FnZXMvc2NyaXB0cy91dGlscy9pbmRleC5qcw==) | `100% <0%> (+2.7%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/WordPress/packages/pull/132?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/WordPress/packages/pull/132?src=pr&el=footer). Last update [04093f5...aef2631](https://codecov.io/gh/WordPress/packages/pull/132?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by youknowriad** [comment]
It looks like this can be closed as we have a check-licenses command in the scripts package.
