### ISSUE TITLE
Update `CONTRIBUTING.md` with pre-release `CHANGELOG.md` procedure

### ISSUE THREAD

**Issue by ntwb** [WordPress/gutenberg#7817]
@ntwb commented on [Tue Jun 05 2018](https://github.com/WordPress/packages/pull/135)

Updating the `CHANGELOG.md` file before a release ensures a few things:

• The `CHANGELOG.md` file is maintained and up to date as it is included in the package distribution

• Prevents Lerna from triggering a new release of the package because of `CHANGELOG.md` only changes

**Comment by youknowriad** [comment]
We do have changelogs for packages and they're updated on each released (and the process is documented). I think this is fine to close.
