### ISSUE TITLE
[3.2] columns have no side padding on front-end

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#7818]
**Describe the bug**
Columns have no side padding on the front-end

**To Reproduce**
1. Insert Columns block with 2+ columns
2. add content to columns
3. view on front end
4. observe no side padding

**Expected behavior**
There should be side padding on the front end

**Screenshots**
BACK-END (this is good):
![no side padding back end](https://user-images.githubusercontent.com/30901407/42452476-1f01fc2c-8358-11e8-930f-b267fb5feafb.jpg)

FRONT-END
![no side padding front end](https://user-images.githubusercontent.com/30901407/42452484-222aa958-8358-11e8-9b6f-574bc06e8816.jpg)

**Comment by karmatosed** [comment]
This is an interesting one as we scaled back these settings because themes wanted to control (rightly) more aspects. I see in this case it could be good to bring back. Let's see about getting a PR here and I think it is possibly right to iterate.

**Comment by GlennMartin1** [comment]
persists in 3.3

**Comment by tofumatt** [comment]
Note: there's some additional context about this in 
https://github.com/WordPress/gutenberg/pull/9936#issuecomment-426452682, the patch for this will need a bit more consideration. This might not be the best first issue after all.
