### ISSUE TITLE
fix: Update allowed licenses, i.e. GPL2 compatible licenses

### ISSUE THREAD

**Issue by ntwb** [WordPress/gutenberg#7821]
@ntwb commented on [Tue May 22 2018](https://github.com/WordPress/packages/pull/130)

This PR seeks to update the list of allowed GPL2 compatible licenses based on the list currently included in #129 

---

@aduth commented on [Wed May 23 2018](https://github.com/WordPress/packages/pull/130#issuecomment-391345004)

Why should we want WordPress packages to be published with anything other than a GPL license?

I understand from [related Slack discussion](https://wordpress.slack.com/archives/C5UNMSU4R/p1526987211000097) that there are some exceptions that exist currently, but should we want those exceptions? Or should those packages be relicensed?

Thinking we should want to promote a single license, rather than leaving it as an open question (consistency in expectations for consumers, no uncertainty for developers in choosing license).

---

@ntwb commented on [Thu May 24 2018](https://github.com/WordPress/packages/pull/130#issuecomment-391556047)

@pento via https://wordpress.slack.com/archives/C5UNMSU4R/p1526992426000277
> It’s not just GPL compatible licenses.
> w.org allows any OSS license.
> It’s only Core that has the strict GPL2 compat requirement.

So that was the basis of my decision to add more licenses to the allowed list.

A follow up discussion suggested we create a `@wordpress/licenses` package to use as the basic for the list used here and in #129 for the license check package.

An initial pass at the `@wordpress/licenses` package is in #132 

----

In relation to the _Packages_ and _Gutenberg_ repos we can restrict the allowed license to `GPL-2.0-or-later` as is currently done for the respective repos in the `npmPackageJsonLintConfig` config option in the repo [root here](https://github.com/WordPress/packages/blob/master/package.json#L31-L50)

---

@aduth commented on [Thu May 24 2018](https://github.com/WordPress/packages/pull/130#issuecomment-391556216)

Are not these packages considered "Core" ?

**Comment by pento** [comment]
We're only going to allow packages to be licenses as GPL2+.
