### ISSUE TITLE
Add a license check script

### ISSUE THREAD

**Issue by ntwb** [WordPress/gutenberg#7822]
@pento commented on [Tue May 22 2018](https://github.com/WordPress/packages/pull/129)

To ensure that any modules we use are GPL2 compatible, we need a script to scan across them and check their licenses.

---

@codecov[bot] commented on [Tue May 22 2018](https://github.com/WordPress/packages/pull/129#issuecomment-390983569)

# [Codecov](https://codecov.io/gh/WordPress/packages/pull/129?src=pr&el=h1) Report
> Merging [#129](https://codecov.io/gh/WordPress/packages/pull/129?src=pr&el=desc) into [master](https://codecov.io/gh/WordPress/packages/commit/4beeb1a7298b33f6144623a5efe50654d4903c7f?src=pr&el=desc) will **decrease** coverage by `5.06%`.
> The diff coverage is `0%`.

[![Impacted file tree graph](https://codecov.io/gh/WordPress/packages/pull/129/graphs/tree.svg?src=pr&token=9Zw9xmxPWW&width=650&height=150)](https://codecov.io/gh/WordPress/packages/pull/129?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #129      +/-   ##
==========================================
- Coverage   67.53%   62.46%   -5.07%     
==========================================
  Files          57       58       +1     
  Lines         690      746      +56     
  Branches      144      160      +16     
==========================================
  Hits          466      466              
- Misses        182      222      +40     
- Partials       42       58      +16
```

| [Impacted Files](https://codecov.io/gh/WordPress/packages/pull/129?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [packages/scripts/scripts/check-licenses.js](https://codecov.io/gh/WordPress/packages/pull/129/diff?src=pr&el=tree#diff-cGFja2FnZXMvc2NyaXB0cy9zY3JpcHRzL2NoZWNrLWxpY2Vuc2VzLmpz) | `0% <0%> (ø)` | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/WordPress/packages/pull/129?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/WordPress/packages/pull/129?src=pr&el=footer). Last update [4beeb1a...9249f89](https://codecov.io/gh/WordPress/packages/pull/129?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by talldan** [comment]
Closing this as I think it should have been closed by #8808
