### ISSUE TITLE
Floating images is broken in large screens

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#784]
Floating image blocks is broken because we the editor wrapper has no max-width to `700px` but all the non-floated blocks and non-wide blocks have a max-width of `700px` to center these blocks. This causes the floated block to show "outside" the limit of the `700px`.

**Note:** Fixing this can have an impact of full-width images too. Make sure to test this to avoid regressions.

<img width="1495" alt="screen shot 2017-05-12 at 17 23 00" src="https://cloud.githubusercontent.com/assets/272444/26007284/b1f44274-3737-11e7-86e8-84283ce5cd11.png">

cc @jasmussen

**Comment by aduth** [comment]
Dunno when it was changed, but I encountered this challenge as well with the original implementation of full-width images which tried to avoid putting max-width on the blocks themselves due to this behavior:

https://github.com/WordPress/gutenberg/pull/518#issuecomment-298018879

**Comment by jasmussen** [comment]
I have an idea for how to fix this (float the div inside `editor-visual-editor__block` rather than `editor-visual-editor__block` itself), which I'm going to try out.

Given the difficulty full width presents for us in the editor, it suggests we probably do want to gate it behind `add_theme_support`, doesn't it?

**Comment by aduth** [comment]
>Given the difficulty full width presents for us in the editor, it suggests we probably do want to gate it behind `add_theme_support`, doesn't it?

To me it seemed like we'd want this regardless, since otherwise how can we expect the image to be shown correctly on the front-end if the theme doesn't specifically target support for it?

**Comment by jasmussen** [comment]
This is fixed in master now! 🎉
