### ISSUE TITLE
Pre-publish panel panels lack spaces between titles and labels

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#7842]
## Issue Overview

There isn't any space between the titles and the labels of panels inside the pre-publish panel:
<img width="282" alt="screenshot 2018-07-09 20 06 39" src="https://user-images.githubusercontent.com/376315/42470848-aa7a8958-83b3-11e8-9720-37b554722088.png">

## Steps to Reproduce (for bugs)
1. Create a new post using Gutenberg.
2. Press the "Publish" button.
3. Notice lack of spaces!

Looks as though the translation strings here are written with the intention of there being a single space here (`<PanelBody title={ [__( 'Visibility: ' )] }>`), but that trailing space is removed when the text string is run through the translation function. Text strings aren't supposed to use trailing whitespace, so a little bit of CSS padding is probably a better solution here.

Sort of related (if pretty tangentially): #7426

**Comment by danielbachhuber** [comment]
👍 I've been noticing this too but never got around to create a ticket for it.

**Comment by chrisvanpatten** [comment]
Only concern I have about CSS padding is what happens if you select and copy/paste that text — presumably there's no space being copied? Also, what's the impact on screen readers if the space isn't in the markup?

**Comment by tofumatt** [comment]
Sounds like, from the issue description, we trim whitespace in the strings so it doesn't matter, but that isn't true. In master, I see:

<img width="225" alt="screenshot 2018-07-10 09 42 28" src="https://user-images.githubusercontent.com/90871/42498994-94720b96-8425-11e8-82f6-b73ad28f1549.png">

(Note the space after `"Visibility"`.)

In this case the whitespace is part of the translation and *should* stay, but we should also have some padding.
