### ISSUE TITLE
Button block: text should word-wrap if needed

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#7843]
**Describe the bug**
Depending on screen size, buttons must word-wrap.

**Screenshots**
This screenshot says it all:
![screenshot_2018-07-09-16-55-45](https://user-images.githubusercontent.com/30901407/42475816-d0ea394a-8399-11e8-8a8c-1fb1f038eec2.png)

**Comment by designsimply** [comment]
Tested and confirmed using the following sample button text:

> Check out our selection testing testing testing testing

![screen shot 2018-07-10 at tue jul 10 1 09 05 pm](https://user-images.githubusercontent.com/1119271/42531951-9c7040c0-8442-11e8-8fd5-c67cd3cc08e7.png)
<sup>Seen at http://alittletestblog.com/2018/07/10/button-block-word-wrap-test/ running WordPress 4.9.7 and Gutenberg 3.2.0 using Chrome 67.0.3396.99 with 'Toggle device toolbar' set to 'iPhone 5/SE' on macOS 10.13.5.</sup>

**Comment by GlennMartin1** [comment]
persists in 3.3

**Comment by GlennMartin1** [comment]
Persists in 4.0. 

Seems like this should be a simple fix.
