### ISSUE TITLE
Images: Bottom single image cut off

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#7848]
**Describe the bug**
First image selected: second Image cut and overlapping meta area.

![screen shot 2018-07-10 at 02 44 18](https://user-images.githubusercontent.com/5323259/42483000-3de5a25e-83eb-11e8-990d-f3d9df35e28e.png)

Second image selected: Caption shining through.

![screen shot 2018-07-10 at 02 44 45](https://user-images.githubusercontent.com/5323259/42483017-546513a2-83eb-11e8-94af-84296e837c00.png)

![image-overlap-gutenberg](https://user-images.githubusercontent.com/5323259/42483227-92ec71dc-83ec-11e8-8851-119f304487b6.gif)

**To Reproduce**
1. Create an image block.
2. Create another image block below it.
3. Align 1st image block left. Notice Bottom image cut off directly into the meta box area.

**Expected behavior**
Images show up nicely below each other. Or whatever happens when the image above is aligned left or right. What is the expected behavior when clicking an image to align left or right?

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Mac OSX - Desktop Server
 - Browser: Chrome
 - Version: Newest Gutenberg version 3.2

**Comment by designsimply** [comment]
Tested and confirmed that the block controls overlap if you left-align an image block and another image block is added below it.

![screen shot 2018-07-10 at tue jul 10 1 25 42 pm](https://user-images.githubusercontent.com/1119271/42532734-0c9c3a3c-8445-11e8-8b67-d53e19caeeac.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13904&action=edit running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

**Comment by designsimply** [comment]
Some work is being done on image floats that should address this issue and so I am closing this one in favor of https://github.com/WordPress/gutenberg/pull/7721. Thank you for the report!!
