### ISSUE TITLE
Image Block: Change the "Source Type" label to "Image Size"

### ISSUE THREAD

**Issue by BronsonQuick** [WordPress/gutenberg#7855]
## Issue Overview
While testing the image block I thought that "Source Type" isn't a very user friendly term and "Image Size" would be more user friendly. Even the `const` used refers to sizes. e.g. `const availableSizes = this.getAvailableSizes();` so it makes sense to change this label.

## Steps to Reproduce
1. Insert an Image block.
2. Upload or Select an Image to use.
3. Observe the "Source Type" label.

## Expected Behavior
The label should say "Image Size".

## Screenshots / Video
<img width="591" alt="source-type" src="https://user-images.githubusercontent.com/1377956/42490538-428ccf30-8454-11e8-8b44-8bfe8d25e0ec.png">

## Additional Info

Gutenberg @ https://github.com/WordPress/gutenberg/commit/c72f5b4f2a4a57fdd972513f0b623f83f533a8d7

**Comment by paaljoachim** [comment]
What about just removing the Source Type (image size) option? Since we can easily resize the image directly in the image block layout.

**Comment by michelleweber** [comment]
If you do keep this setting, +1 on changing it to "Image size." (But I'd also love to look at these settings and immediately understand the difference between "image size" and "image dimensions," which seem like they should be the same thing.)

**Comment by sarahmonster** [comment]
+1 for changing the setting name. +2 for getting rid of it altogether or combining it with Image Dimensions control.
