### ISSUE TITLE
Subheading Block: pressing 'Enter' inserts a line break instead of starting a new block

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#7871]
Steps to reproduce:

1. Start a new post with Gutenberg.
1. Insert a subheading block.
1. Press enter and start typing.

<strong>Result:</strong> if you press 'Enter' from a subheading block a line break is inserted. In comparison, when you press 'Enter' from a heading block a new paragraph block is started.

What is the intended behavior when you press the 'Enter' key from within a subheading block?

![screen shot 2018-07-10 at tue jul 10 12 27 38 pm](https://user-images.githubusercontent.com/1119271/42530075-74939840-843d-11e8-8a36-d02a97d6a2b2.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13902&action=edit running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

h/t Nick Miranda for the original question (internal reference: pb6Nl-cHt-p2#comment-88710)

**Comment by karmatosed** [comment]
It should like all blocks cause you to enter the 'add block' flow. This is a bug I think, thanks for catching.

**Comment by jorgefilipecosta** [comment]
Issue https://github.com/WordPress/gutenberg/issues/5475 refers to the same problem.

**Comment by youknowriad** [comment]
The subheading block is deprecated. Let's close this issue.
