### ISSUE TITLE
Embed Block: giphy embeds switch from animated gif to html page when clicked

### ISSUE THREAD

**Issue by mgalbritton** [WordPress/gutenberg#7872]
**Describe the bug**
Within Gutenberg, if you add a giphy embed via the generic embed block, the properly gif will show but if you then click on the gif to adjust the layout, the image showing changes to the giphy homepage. 

**To Reproduce**
1. Create a new post.
2. Using the embed block, add a giphy link.
3. See the gif embed
4. Click on the embed to adjust the layout of the embed. 
5. Watch the gif change instead.
6. Preview the post, and you will see the correct embed. 

**Expected behavior**
I expected the same preview image to show consistently. 

**Screenshots**
![screen shot on 2018-07-10 at 14_23_15](https://user-images.githubusercontent.com/19782997/42532547-d826344e-844c-11e8-80a5-4302f09d4264.png)
![screen shot on 2018-07-10 at 13_35_50](https://user-images.githubusercontent.com/19782997/42532577-ee117976-844c-11e8-9685-5cbeab95cd86.png)
![screen shot on 2018-07-10 at 13_36_09](https://user-images.githubusercontent.com/19782997/42532587-f78b0fbc-844c-11e8-8552-12fb14f1c787.png)

**Desktop (please complete the following information):**
 - OS: High Sierra
 - Browser Chrome
 - Version 67.0.3396.99

**Additional context**
Gutenberg version 3.2.0

**Comment by designsimply** [comment]
Tested and confirmed that I clicking on an embedded giphy causes the display to change from the animated gif to the whole html page for said giphy.

![screen shot 2018-07-12 at thu jul 12 4 15 06 pm](https://user-images.githubusercontent.com/1119271/42662500-119d568c-85ef-11e8-9248-d11d92eb248a.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13959&action=edit running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

Sample embed url I used for testing: https://giphy.com/gifs/peanuts-charlie-brown-a-christmas-Vz1cEfM0VFpII

**Comment by cmartini** [comment]
Anyone on this or is there a workaround?

**Comment by notnownikki** [comment]
Embedded content in the editor is rendered inside the `Sandbox` component, which i an `iframe` with security restrictions applied.

To fix this, there needs to be an option to allow or prevent clicks going to the rendered content. I've assigned myself to work on this.

**Comment by youknowriad** [comment]
This is fixed by #12981
