### ISSUE TITLE
Improve pre-publish prompt copy

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#7873]
When you first press the "publish" button, the pre-publish panel shows up, with the following text:

> Are you ready to publish?
>
> Here, you can do a last-minute check up of your settings below, before you publish.

Here it is in context:

<img width="724" alt="screenshot 2018-07-10 20 36 06" src="https://user-images.githubusercontent.com/376315/42533148-f32c2d82-8480-11e8-8e71-917544abee33.png">

I think we can improve this copy so it's a bit more clear and direct. The two references to a physical location ("here" and "below") are a bit confusing, and we probably don't need two commas in a single sentence.

Quick suggestion:

> Are you ready to publish?
>
> Double-check your settings, then use the button to publish your post.

See also: #7426

**Comment by michelleweber** [comment]
+1 for the suggested copy.

**Comment by karmatosed** [comment]
I think this is a great improvement, thanks for iterating here.
