### ISSUE TITLE
Blocks should be group and Reorder by Drag/Drop in the Content Structure

### ISSUE THREAD

**Issue by Emilybkk** [WordPress/gutenberg#7888]
**Is your feature request related to a problem? Please describe.**
I have problem when I have to move more than one block. Example I have heading like H2 as the main subject and then I have few paragraph for that subject. Like so If I want to move these heading and it content together I have to up and down for multiple time to move all of them. When I was using classic editor I just select all of those content no matter how many heading and paragraph and then I just cut/paste is wherever I want. Now it is more difficult and take time to move blocks with the up/down arrow.

**Describe the solution you'd like**

It would be good if we can group the blocks together and move them easily like Drag & Drop them in the Content Structure. When we drag them as group then they move together. 

![](https://i.imgur.com/mryjPBy.png)

**Comment by SuperGeniusZeb** [comment]
Duplicate of #5301.

Side note: it would be nice if there was a version of the Document Outline that included all blocks instead of just Heading blocks. That would be even more useful to have a drag-and-drop enhancement for. Maybe a toggle on the Document Outline pop-up to show all blocks?

**Comment by Emilybkk** [comment]
@samikeijonen Exactly. It should group any block that close to each other. Sorry for duplicate post. I already search but not good enough. Thank you.
