### ISSUE TITLE
Starting a sentence (or block) in bold, without the need to select text previously

### ISSUE THREAD

**Issue by JohnPixle** [WordPress/gutenberg#79]
I am wondering if it is worth pointing out that currently there is no way for a user to start typing in bold or italics right away without highlighting the text so for the toolbar to appear. 

He can do this via keyboard and works quite well as I see here https://wordpress.github.io/gutenberg/  but there are many people out there who are not familiar with keyboard shortcuts for bold, and rely on the **B** and _I_ icons.

Perhaps this is too much of a stretch at this point as there are more fundamental challenges to workaround, but it might be worth considering.

**Comment by mtias** [comment]
I agree with the concern. The latest round of mockups has a docked format bar instead of an inline floating one: https://github.com/WordPress/gutenberg/blob/master/mockups/Formatting,%20Click.png

**Comment by JohnPixle** [comment]
@mtias I also worked on a similar docked approach yesterday, and just added some further work on it, posted at #61

**Comment by jasmussen** [comment]
Closing for now, as the current UI prototype solves this.
