### ISSUE TITLE
Alignment: setting alignment attributes should be consistent across blocks

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#7909]
Split out from https://github.com/WordPress/gutenberg/issues/4010 where @bradyvercher says:

## Toolbar onChange Callback

Some blocks define a class method (requires binding in the constructor), others define a local function, and some use an inline arrow function. They all do the same thing. I'd like to see this be more consistent across blocks.

Considering how simple it is, I think using an inline arrow function would make things more concise and easier to read:

```js
<BlockAlignmentToolbar
    value={ align }
    onChange={ value => setAttributes({ align: value }) }
/>
```

**Comment by timhibberd** [comment]
@designsimply - I am championing [an issue that I believe is related to this](https://github.com/WordPress/gutenberg/issues/11234). If you could spare a moment and have a look and comment that would be fantastic. Regardless of how you feel about the issue I raised, I agree completely with this issue you raised...block styling consistency is a must if external themes are going to play well with GB. Thanks in advance...much appreciated :-)

**Comment by youknowriad** [comment]
Closing this as it's not really important and we'd like to bring consistency with #20650
