### ISSUE TITLE
Alignment: latest posts block reapplies `aligncenter` on save even if it was deselected

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#7911]
Moved from #4010 h/t @bradyvercher.

Steps to reproduce:

1. Insert a latest posts block.
1. Select the center alignment option in the block toolbar.
1. Deselect the center alignment option in the block toolbar.
1. Publish the post.

<strong>Result:</strong> the class is `aligncenter` even though alignment was deselected.

![screen shot 2018-07-11 at wed jul 11 6 07 28 pm](https://user-images.githubusercontent.com/1119271/42605478-5422f896-8535-11e8-81c2-2fd4ca212c04.png)<sup>Seen at http://alittletestblog.com/2018/07/11/latest-posts-block/ running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

**Comment by nfmohit-wpmudev** [comment]
Submitted #8847 addressing this bug. Thanks ❤️
