### ISSUE TITLE
Alignment: paragraph and text columns block alignment attribute name is `width`

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#7912]
Moved from #4010 h/t @bradyvercher.

### Paragraph Block

The attribute name for the block-level alignment is `width`, which doesn't seem to make much sense. Naming this something like `blockAlign` would be a little more clear, especially since the `width` attribute is a number in some other blocks.

Or the inline alignment attribute could be named `textAlign` since that's the property used when applying the inline style.

See https://github.com/WordPress/gutenberg/blob/6edaf6803e80fc5a0fa043a41e428fa0f113b9c3/core-blocks/paragraph/index.js#L477-L481

### Text Columns

Uses the `width` attribute for alignment.

See https://github.com/WordPress/gutenberg/blob/9d4fd108d37750eb4356cd22d64ebdc500ec4565/core-blocks/text-columns/index.js#L57-L61

**Comment by youknowriad** [comment]
Closing as the paragraph don't support this attribute anymore and the text block is deprecated.
