### ISSUE TITLE
Prefix everything

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#793]
There are a lot of things in the Gutenberg code that need a prefix like `wp-` to avoid conflicting with plugins.  For example, CSS classes and IDs:

![2017-05-15t16 09 47-0400](https://cloud.githubusercontent.com/assets/227022/26077155/1984bc54-3989-11e7-9705-4107a51e5484.png)

From that screenshot, some of the more problematic selectors look like `#editor`, `.button`, and `.clear`.

Also, the PHP function `register_block` should probably be `wp_register_block`.

Further reading: https://nacin.com/2010/05/11/in-wordpress-prefix-everything/

**Comment by aduth** [comment]
To the `.button` case, it's intentionally inheriting styles from WordPress's `.button` class.

More generally, #367 was an attempt at creating namespaces by enforcing a prefix on class names corresponding to the top level directory (`editor-`, `blocks-`, `components-`)

**Comment by nylen** [comment]
I wasn't aware that `button` was a WP class on its own.  WP not following its own guidelines? :see_no_evil: 

I think we might be better off changing the other classes you mentioned to `wp-editor-`, `wp-blocks-`, `wp-components-`, ...

**Comment by jasmussen** [comment]
Showerthought: CSS was meant to cascade from the very start. Now we're doing our very best to prevent the cascade. ;)

(Don't get me wrong — the endless CSS bleed was part of what drove me away, and componentized web development has reinvigorated it for me!)

**Comment by mtias** [comment]
Going to close this as it's not very actionable at the moment.
