### ISSUE TITLE
Line-height in Headings

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#7930]
This line-height is a bit awkward to me:

![image](https://user-images.githubusercontent.com/548849/42632461-88382ffe-85dd-11e8-9b76-d3fee83de9f6.png)

Specially compared to the main title:

![image](https://user-images.githubusercontent.com/548849/42632476-9898b774-85dd-11e8-8da7-c69905036a84.png)

**Comment by karmatosed** [comment]
I agree with reducing this.

**Comment by sarahmonster** [comment]
👍 

Using 1.4 instead of 1.8 here pulls things together much more nicely.

**Comment by kjellr** [comment]
For completeness, here's what all headings look like: 

![current](https://user-images.githubusercontent.com/1202812/42691908-d9c0eff6-8677-11e8-847b-d79c53630e72.jpg)

The post/page header is set to `1.4`, but all headers inside the post content inherit the default `1.8` line height. 

---

I agree with @sarahmonster that `h1`–`h3` should be `1.4`. 👍 

I suggest that `h4` be set to `1.5`. I'm being nitpicky, but I suggest that tiny smidge of extra space helps the line height scale down gradually with the text size. 

The smaller headlines, `h5` & `h6` can use the same `1.8` line height as the body text. 

![new](https://user-images.githubusercontent.com/1202812/42691951-fa7c399e-8677-11e8-9045-67bdc8265b9d.jpg)
