### ISSUE TITLE
Missing top margin for notices in edit post sidebar

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#7935]
The notice of the `ContrastChecker` component has no top margin due to [this rule](https://github.com/WordPress/gutenberg/blob/f920f2d36ed3f97e6a6ae85dcbd11e67462fd41b/edit-post/components/sidebar/style.scss#L59-L61). 

Some before/after screenshots…

In Gutenberg:
<img width="289" alt="before-gutenberg" src="https://user-images.githubusercontent.com/617637/42643788-50e4c7c0-85fa-11e8-9e75-01488e92ae77.png">
<img width="296" alt="after-gutenberg" src="https://user-images.githubusercontent.com/617637/42643791-52283374-85fa-11e8-8469-529b8168fe16.png">

With a custom implementation:
<img width="289" alt="before-custom" src="https://user-images.githubusercontent.com/617637/42643800-54425f68-85fa-11e8-8902-1366de870141.png">
<img width="281" alt="after-custom" src="https://user-images.githubusercontent.com/617637/42643803-55ddf29c-85fa-11e8-9cfd-8b5d220b363c.png">

**Comment by designsimply** [comment]
Thank you for the report @ocean90! I moved this from a bug to an enhancement and have asked for design feedback 2nd opinion because I think block settings notices are functional and still work as expected without the top margin on the paragraph tag.

**Comment by sarahmonster** [comment]
+1 for adding some top-padding here!

**Comment by ocean90** [comment]
This is no longer an issue due to some changes in the notices component.
