### ISSUE TITLE
package @wordpress/i18n is missing dependency 

### ISSUE THREAD

**Issue by marcusig** [WordPress/gutenberg#7936]
**Describe the bug**
I'm using @wordpress/i18n on an other project than Gutenberg and since v1.2.0 I get the error `Module not found: Error: Can't resolve '@babel/runtime/core-js/object/assign'`

I can obviously add @babel/runtime to my project package.json, but if @wordpress/i18n is meant to be used in other projects, @babel/runtime should be part of the dependencies. 

Unless I'm doing something wrong :)

**Comment by diegoreymendez** [comment]
Another ocurrence of this being an issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/71

**Comment by gziolo** [comment]
I missed this one. Yes, it all makes sense. We need to update the list of dependencies for all packages that are transpiled with Babel. I should publish new version of such packages on Monday the latest 👍

**Comment by gziolo** [comment]
Well, technically we need to publish those packages to npm. I hope to do it later today.

**Comment by gziolo** [comment]
`@wordpress/i18n@1.2.1` is now available on npm with the fix.
