### ISSUE TITLE
What's going to happen to media buttons and TinyMCE custom buttons?

### ISSUE THREAD

**Issue by UVLabs** [WordPress/gutenberg#794]
What's going to happen to these? 

![image](https://cloud.githubusercontent.com/assets/10324144/26077871/98b9759e-398b-11e7-8f04-2d237eee0e2f.png)

I'm assuming we might not be able to use the same code since the editor will most likely look different? Hoping some documentation could be created ahead of time before this is merged into core so plugin and theme developers could update.

This is a widely used feature and though one can argue that it may be bad UX I believe it still has a place since you don't expect users to remember your shortcode which may be long in most cases or let them have to copy and paste it. 

![image](https://cloud.githubusercontent.com/assets/10324144/26077820/65e2d44e-398b-11e7-9b88-4b4ccd388de7.png)

In my experience, I've seen both the custom tinyMCE buttons and the media buttons being used for this "shortcode injecting" feature.

Most plugins use this as some sort of  a shortcode builder even:

![image](https://cloud.githubusercontent.com/assets/10324144/26077886/a5b52ba8-398b-11e7-8c1f-9413663e43cb.png)

I personally use it for one of my plugins to let users build their custom tweet boxes:

![image](https://cloud.githubusercontent.com/assets/10324144/26078166/9ff303ec-398c-11e7-8cfb-0ba077d9706f.png)

With this behavior you let users decide on the fly what data they want and not necessarily having to create it prior to needing it. Curious about your approach to this.

**Comment by jasmussen** [comment]
The recommended course of action will be to convert those shortcodes to blocks. 

The block can be seen as an _evolution of the shortcode_. It embraces what made a shortcode great —  bundling a bunch of complicated markup together into a single tag —  but builds upon it. Blocks can be better designed, they can be manipulated directly inside the editor itself, and later in the year they will serve as a foundation for a customization focus that will likely involve a page building experience.

In this editor, shortcodes will still work, but can be seen as legacy feature. See also #334. That is, they will still technically work, but it would be recommended to migrate them to using the block API.

In that vein, block API documentation will be important, so I've added a milestone to #468. 

We have ideas for where plugins can add buttons to the editor, but these depend on how far we get with the other features, and so the buttons that insert these shortcodes should also be seen as a legacy pattern, and they might not work.

**Comment by mtias** [comment]
Thanks for chiming in. This describes precisely what "blocks" are meant to replace under a coherent UX: discovery (via the inserter), visual display, editable attributes (direct manipulation as much as possible, convenient settings in the toolbar, advanced ones in the sidebar inspector). When you register a new block it'll be added to the inserter as a new item:

![image](https://cloud.githubusercontent.com/assets/548849/26100373/fd9172c6-3a2d-11e7-8cc8-76d7ea287f12.png)
