### ISSUE TITLE
Change inserter inside InnerBlocks.

### ISSUE THREAD

**Issue by herregroen** [WordPress/gutenberg#7950]
Currently the inserter used inside `InnerBlocks` is the same as the general one used to edit posts.

When `core/paragraph` is allowed inside `InnerBlocks` this works for adding paragraphs but adding other types of blocks can be confusing as this depends on which block is currently active.

When `core/paragraph` is not allowed inside `InnerBlocks` adding blocks doesn't work at all as there's no way to make the `InnerBlocks` active.

To solve these I would suggest the default inserter for `InnerBlocks` is a simple plus that's always visible, clicking on it opens the popover which displays only a list of allowedBlocks. This is, by default, the only way to add blocks to InnerBlocks in order to remove all confusion.

Optionally a `prop` may be passed to revert back to the previous inserter if the user of `InnerBlocks` feels that makes sense.

**Comment by SuperGeniusZeb** [comment]
Dupicate of #6834. See also: #6569, #7006, and #7763.

**Comment by karmatosed** [comment]
Closing as we are collating into one issue.
