### ISSUE TITLE
Links in Gallery captions are low-contrast

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#7952]
**Describe the bug**
Our default blue link color for text inside of gallery captions make them barely readable against the dark gradient background. 

**To Reproduce**
1. Create a gallery.
2. Add a caption to an image in the gallery.
3. Add a link inside that caption. 

**Screenshots**

<img width="1122" alt="screen shot 2018-07-13 at 9 22 18 am" src="https://user-images.githubusercontent.com/1202812/42693862-8006482e-867e-11e8-862b-0f47dd257214.png">

**Suggestion**

Perhaps we continue using white text there, and only add the underline to links:

<img width="1123" alt="screen shot 2018-07-13 at 9 26 36 am" src="https://user-images.githubusercontent.com/1202812/42694056-0f4b5588-867f-11e8-9c16-a0382b73ea58.png">

**Comment by nfmohit-wpmudev** [comment]
#8004 applies the proposed changes.

**Comment by tofumatt** [comment]
Fixed in #8004.
