### ISSUE TITLE
Yoast + Gutenberg 3.2- Does Not Pull in Slug Info in Gutenberg

### ISSUE THREAD

**Issue by mgalbritton** [WordPress/gutenberg#7954]
**Describe the bug**
Slug information under `edit snippet` in Yoast does not populate.

**To Reproduce**
Create a post in Gutenberg. Publish it. Go back to the post and look at the Yoast information for the post by clicking on `edit snippet`. Notice that the slug information box is blank.

Create a post in the classic editor. Publish it. Go back to the post and look at the Yoast information for the post by clicking on `edit snippet`. Notice that the slug information is filled in based on the post slug. 

**Expected behavior**
The slug should populate the slug field in Yoast.

**Screenshots**
With Gutenberg and a published post:
![screen shot on 2018-07-13 at 09_11_40](https://user-images.githubusercontent.com/19782997/42696552-1b0f9a38-867e-11e8-98af-a7afc4ab1c49.png)

With Classic Editor and a published post:
![screen shot on 2018-07-13 at 09_20_33](https://user-images.githubusercontent.com/19782997/42696556-1eb026b2-867e-11e8-9947-6f6ab0e8313d.png)

**Desktop (please complete the following information):**
 - OS: High Sierra
 - Browser: Chrome 
 - Version: 67.0.3396.99

**Smartphone (please complete the following information):**

**Comment by youknowriad** [comment]
Yoast is now fully Gutenberg compatible, I think this issue is probably obsolete. If you're still having the issue, please let us know.
