### ISSUE TITLE
Page up and down keys don't scroll long blocks in Firefox

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#7955]
**Describe the bug**

If you create a block that has enough content that it doesn't all fit within the viewport, then click inside the block to focus it, the `Page Up` and `Page Down` keys will no longer work in Firefox. 

They still work if you're focused outside the block in Firefox. They work in both situations in Chrome.

**To Reproduce**

1. Open Gutenberg in the latest Firefox (v62 at the time of this writing)
1. Create a block with enough content that it is taller than the viewport
1. Click inside the block to focus it
1. Hit the `Page Up` or `Page Down` keys, nothing will happen

**Expected behavior**

`Page Up` and `Page Down` should scroll the viewport.

**Desktop (please complete the following information):**
OS X 10.13.5
Firefox Developer Edition 62.0b6
Gutenberg master @ 5fb24e44ceac6ac19b0d2bdffea87b467520f405

**Comment by designsimply** [comment]
I tested this with WordPress 4.9.8 and Gutenberg 3.4.0 and Firefox 61.0.1 on macOS 10.13.6 and was unable to reproduce. ([11s](https://cloudup.com/cjnVcx3JgnZ)) Is the problem still happening for you? What kind of keyboard are you using?

Note: I am using a Macbook Pro laptop and pressed `Function + Up Arrow` for `Page Up` and `Function + Down Arrow` for `Page Down`.

**Comment by iandunn** [comment]
I'm still seeing the problem with `master` @ 4fd5c20af4a8a46c92048574e363b07977aa0f3f. I have a Microsoft Sculpt connected to an iMac. It has the traditional `Page Up` and `Page Down` keys.

**Comment by manooweb** [comment]
I tested but I'm on Windows 10 - 1803.
WordPress 4.9.8 - Gutenberg 3.8.0 - Firefox 62 or Chrome 69
I tested with the keyboard of the laptop : Shift + Page Up or Shift + Page Down => no issue 
I tested with a classic 102 keys keyboard from logitech with Page Up and Page Down keys => no issue

**Comment by iandunn** [comment]
I'm not able to reproduce this anymore either, so I'm guessing it was fixed as as side-effect of some other issue.
