### ISSUE TITLE
Quote Block: the first letter from a citation remains even if the citation is deleted (tested with 3.2.0)

### ISSUE THREAD

**Issue by mgalbritton** [WordPress/gutenberg#7956]
**Describe the bug**
If you delete a citation, the first letter of the word in the citation remains in place. Also, the citation feature in the quote block will not allow you to add a new citation in visual mode once a citation has been deleted. 

**To Reproduce**
1. Start a new post.
2. Add a quote block.
3. Add your quotation.
4. See the citation line underneath the quote.
5. Add a citation.
6. Delete the citation. 
7. Preview the post and see the first letter of the citation you added is hanging on.
8. In the editor, switch to code editor. In the code editor, you will see the first letter remains.
9. Switch to visual editor and delete the hanging letter. 
10. Try to add a new citation and it see that it will not allow you to.

**Expected behavior**
For the delete citation not to hang and to be able to add a new citation to the quote.

**Screenshots**
![screen shot on 2018-07-13 at 09_47_01](https://user-images.githubusercontent.com/19782997/42698349-465b6a78-8683-11e8-928a-a2a487d126b3.png)
![screen shot on 2018-07-13 at 09_47_36](https://user-images.githubusercontent.com/19782997/42698362-4e6a7bd2-8683-11e8-8f3f-bbfb890250ae.png)
![screen shot on 2018-07-13 at 09_48_25](https://user-images.githubusercontent.com/19782997/42698391-5e031bb2-8683-11e8-9e2f-c92f8968691d.png)
![screen shot on 2018-07-13 at 09_57_26](https://user-images.githubusercontent.com/19782997/42698401-65756a26-8683-11e8-8c60-4ce5dbeaf3ca.png)

**Desktop (please complete the following information):**
 - OS: High Sierra
 - Browser Chrome
 - Version 67.0.3396.99

**Comment by mintplugins** [comment]
I am replicating this as well.

**Comment by earnjam** [comment]
I'm not able to replicate this. It's possible it's been resolved sometime since it was reported. 

@mgalbritton @mintplugins can either of you confirm whether this is still occurring for you?

**Comment by catehstn** [comment]
Closing this as there have been no reports since July. We can re-open if necessary.
