### ISSUE TITLE
Isolate end-to-end testing environment

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#7959]
In trying to write some e2e tests for the _Latest Comments_ block that involved a site with X number of comments on it, I realised that the e2e tests are *running against the development server*.

This is problematic because the tests rely on the site functioning a certain way and–at least soon–having certain content, but can't guarantee this as the developer may have changed content/settings/etc. The tests could pass locally thanks to changes in the development environment but fail on Travis CI without an obvious code difference.

I don't know a tonne about WordPress DB mocks or anything so my brute-forced solution thus far is to have a separate set of docker containers for running tests in that we either:

1. reset using WP-CLI on every test run (100% reliable/reproducible tests, but slower)
2. ensure we destroy test data after we create it in the test (fragile, but faster)

I lean toward option 1 for now, and we can see how it goes.

**Comment by tofumatt** [comment]
Ah, of course, I forgot that we can likely hook up an `npm posttest` script for the `e2e` tests to clean up posts (and eventually, if needed, other data).

**Comment by danielbachhuber** [comment]
> reset using WP-CLI on every test run (100% reliable/reproducible tests, but slower)

It may be even faster to have a base SQL file that's imported before every test run. This would effectively reset the environment, while avoiding a bunch of PHP execution.

**Comment by tofumatt** [comment]
I thought about that and indeed it's faster, but the issue there is we'd need to keep it updated–using `wp db reset` seems a bit easier to maintain.

I suppose we could create a custom image for each WP version with the SQL… or cache the SQL.

All that said, if we don't clean up test data in the test itself, `npm run test-e2e:watch` will fail on subsequent runs.

It seems, unfortunately, the best bet is likely to clean up test data in the tests themselves.

**Comment by tofumatt** [comment]
Of course, we can just delete all content at the end of each test using `afterEach` in `test/e2e/support/bootstrap.js`.

I have a branch where I just delete all posts using WP-admin for now and it works, plus allows me to have an empty database for each new test run, which makes tests I wanted to write for the `latest-comments` block work. PR incoming...
