### ISSUE TITLE
Block formatting toolbar goes off-screen when you scroll down past the first block in multiple block selection

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#7962]
## The issue
The block toolbar shown when multiple blocks are selected does not remain on-screen when you scroll down past the first block in the selection.

## Screenshots
![image](https://user-images.githubusercontent.com/19592990/45633563-b53df580-ba65-11e8-9af6-af9a5f784da2.png)
![image](https://user-images.githubusercontent.com/19592990/45633569-ba9b4000-ba65-11e8-8a73-504b50d6bc55.png)

## Related issues and PRs
- #6128
- #7635
- #7891

**Comment by SuperGeniusZeb** [comment]
@designsimply Please re-open. The toolbar has been moved in `master`.

**Comment by SuperGeniusZeb** [comment]
I have added screenshots to the original post.

**Comment by La-Geek** [comment]
Windows 10 64bit, Chrome browser, (all recent), WP (5.0-beta5-43907), Theme Twenty Nineteen

![multiple_block_toolbar_disappearing](https://user-images.githubusercontent.com/1585416/48675333-e4511000-eb57-11e8-9764-720db6914223.gif)
