### ISSUE TITLE
Attribute selectors for content nested inside <iframe> are not found

### ISSUE THREAD

**Issue by paulsowden** [WordPress/gutenberg#7968]
## Issue Overview

Block attribute selectors do not match elements inside of iframes. For example:

```js
registerBlockType( 'my-block', {
  attributes: {
    fallback_img: {
      source: 'attribute',
      selector: 'img',
      attribute: 'src',
    }
  },
  save: function( props ) {
    return el( 'iframe', null, el( 'img', { src: props.attributes.fallback_img } ) );
  }
} );
```

Which produces html:

```html
<iframe><img src="$url"></iframe>
```

The content in the iframe is provided as a fallback and is particularly important when the content is being transformed to amp.

## Expected Behavior

The above selector should match the <img>'s src attribute on load.

## Current Behavior

The selector does not match, presumably because the query is performed by the browser and the browsers we use to edit posts in wordpress support iframes so the html content inside the iframe is simply ignored by the browser. This was pretty counter-intuitive for me and took me a little while to figure out, all I saw was that each time I tried to reopen the post I would get a validation error in my block because the attribute was not correctly extracted.

**Comment by youknowriad** [comment]
Unless I'm missing something, this is invalid HTML anyway. iframes can't contain any content.

**Comment by paulsowden** [comment]
This valid html, iframes can absolutely contain content, see for example: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

"
Permitted content | Fallback content, i.e. content that is normally not rendered, but that browsers not supporting the <iframe> element will render. (RSS readers and email clients often show the fallback content instead.)
"

**Comment by youknowriad** [comment]
Interesting, I actually just checked the W3C validator and it's not valid for them.

```
<!DOCTYPE html>
<html lang="en">
<head>
<title>test</title>
</head>
<body>
<iframe><img src="http://google.com" /></iframe>
</body>
</html>
```

And the spec does say, that the content model of iframe is "nothing" which means texts and inner elements are not allowed https://html.spec.whatwg.org/multipage/dom.html#the-nothing-content-model
