### ISSUE TITLE
Copying text into first paragraph causes blank Paragraph Block to appear above text

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7973]
**Describe the bug**
I created a new page and pasted some (unformatted) text content into the first Paragraph block after the title. Instead of actually pasting the text into the Paragraph Block though, it created a whole new Paragraph Block and pasted the text into that instead, leaving me with a blank Paragraph Block.

![gutenberg_copytextcreatedemptyparagraph](https://user-images.githubusercontent.com/2078245/42741378-10755828-88f5-11e8-90f3-69f5febc206c.gif)

**To Reproduce**
1. Copy some unformatted text from somewhere
2. Create new Page
3. Type Page title in Title Block
4. Put cursor in first Paragraph Block
5. Hit Ctrl-V/Cmd+V to Paste text
6. A new Paragrph Block is created and the text appears in this block instead of the Block where you tried to paste it

**Expected behavior**
When I paste plain text into a Paragraph Block, it should paste into the Block where my cursor is, not create a brand new Block, leaving me with an empty Block.

_macOS Sierra 10.12.6 (16G1510)
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.2.0_

**Comment by SuperGeniusZeb** [comment]
Can confirm this is happening in `master` right now.

**Comment by designsimply** [comment]
Tested and confirmed that an empty paragraph block remains after I copy text from elsewhere that contains leading line breaks. I found that I was able to copy some text over without that happening if I only select a portion of text that does not include the beginning of a line.

**Video:** [1m21s](https://cloudup.com/crGxItB55dc)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13996&action=edit running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

![screen shot 2018-07-17 at tue jul 17 10 13 20 am](https://user-images.githubusercontent.com/1119271/42831638-148c88de-89ac-11e8-8a8a-f716e7d2d83c.png)

**Comment by matto15** [comment]
I copied text from pdf but when I switched to the classic editor, there were double spacing (&npsb;) after each paragraph. This is awful for a document of 1500 words.

**Comment by designsimply** [comment]
Closing this so we can consolidate in #7973 which addresses the underlying problem here which is that when you paste content with leading white space, such as a line break, it results in an empty block that shouldn't be there.
