### ISSUE TITLE
Selecting/finding elements in e2e tests is difficult and could result in maintainability problems

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#7974]
**Is your feature request related to a problem? Please describe.**
As our test coverage grows, using selectors based on class names or other attributes/content for our e2e tests will result in an update of the tests every time one of those strings changes. It could potentially become hard to maintain.

examples from our current tests:
```jsx
page.click( 'button[aria-label="Change block type"]' );
```

```jsx
page.click( '.editor-post-publish-panel__header button' )
```

**Describe the solution you'd like**
A common approach to solve this is to use data attributes for selectors in e2e tests. Some reading here:
- https://medium.com/@colecodes/test-your-dom-with-data-attributes-44fccc43ed4b
- https://kentcdodds.com/post/use-data-test/

What would it look like? When implementing something like a `IconButton`, it accepts a `test-name` prop which renders a `data-test-name` attribute on the resulting element.

``` jsx
<IconButton
    testName="convert-to-shared-block__button"
    // ... other props
> 
    { __( 'Convert to Shared Block' ) }
</IconButton>
```
becomes
```jsx
<button
    data-test-name="convert-to-shared-block__button"
    // ... other attributes
>
   Convert to Shared Block
</button>
```
and using the element in a test becomes `page.click( '[data-test-name="convert-to-shared-block__button"]' );`

As a second improvement, I think you could use a classnames style helper function to help concatenate test names for components:

```jsx
import makeTestNames from 'make-test-names';

// curried function with arity of 2, so returns a function
const testNames = makeTestNames( {
  button: '__button',
  icon: '__icon',
} );
export testNames;

// ...

render() {
  const {
    button: buttonTestName,
    icon: iconTestName,
  } = testNames( this.props.testName );

  return (
    <button
      data-test-name={ buttonTestName }
      // ... other props
    >
      // ... children
    </button>
  );
}
```

 and potentially we can use them in tests:

```jsx
import { testNames } from '@wordpress/components/icon-button';

const convertButtonTestNames = convertToSelectors( testNames( 'convert-to-shared-block' ) );

// ...

page.click( convertButtonTestNames.button );
```

**Describe alternatives you've considered**
Would love to hear arguments for or against, and other ideas on tooling. 

I think the idea of using data attributes for test names is pretty widely used and works well. 

One thing that could be beneficial is a way to prevent them being rendered in production.

**Comment by tofumatt** [comment]
On the [addons-frontend project at Mozilla](https://github.com/mozilla/addons-frontend) we ended up adding a `className` to nearly every element to do that–it doubled as useful for non-nested CSS selectors, but was obviously verbose and probably sending more text down-the-wire than strictly needed.

A data selector specifically for tests would be cool, though I'd say we should keep it simple… I don't think we need the helper. It might even be cool to have the production build remove those attributes but that's a future optimisation 😄

I like the idea of doing `data-testname="foo"`.

**Comment by noisysocks** [comment]
I'm into the idea, especially if we can remove the attributes or class names if `NODE_ENV === 'production'`.

**Comment by uuf6429** [comment]
I also need this in production (sort of). Long story short: I'm testing a WordPress plugin by interacting with the WordPress UI (via behat). With the current generated DOM it is as best a maintenance nightmare (`When I fill in "components-form-token-input-0" with "Test Tag"` instead of `When I fill in "tags" with "Test Tag"`) and at worst impossible to work with (some fields cannot be identified at all).

**Comment by markjaquith** [comment]
I feel pretty strongly about having a reliable way for E2E tests to work. Using `data-` attributes seems to be the proper way to do this.

https://docs.cypress.io/guides/references/best-practices.html

How can this get moved forward? It would be good to be agreed on an approach before someone spends hours coding it up.

**Comment by gziolo** [comment]
```js
page.click( 'button[aria-label="Change block type"]' );
```

As bad it seems, the fact that many selectors depend on the labels has its benefits. This helps to ensure that the user interface works as expected for those who depend on screen readers. I totally agree that we should never use those selectors in tests directly as they can change over time. However, we should consider using tiny abstractions which mirror the behavior on how the site is browsed by people with disabilities. In effect, we should be using more visual labels and aria attributes.

**Comment by noisysocks** [comment]
Came across this issue again and I think nowadays I agree wholeheartedly with @gziolo's comment above.

I even wonder if it's worth enforcing via a lint rule that our E2E tests use either `[aria-label="Button text"]` selectors for icon buttons or `//button[text()="Button text"]` XPath selectors for text buttons.

**Comment by talldan** [comment]
Closing this, as it's now a fairly old issue, and time has shown that there haven't been many of the predicted issues.
