### ISSUE TITLE
Ability to set a "default block"

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#798]
Right now the default block is text. We should look at ways to make this configurable, either by a setting the user can set, or a plugin filter. This would allow the use of blocks like "freeform" or "advanced tinymce" as well as setting "image" as the default block for an instagram like experience.

**Comment by youknowriad** [comment]
This could have an impact on #565. We may show the inserter next to the default block (instead of an empty text block). But the way it's implemented right now seems to be easily changeable.

**Comment by aduth** [comment]
Yeah a problem with #565 is that it needs to know the shape how to consider a text block as empty. That works fine enough for a statically defined default block, but not one which can be overridden.

Maybe it's enough to treat a block as "new" until an `UPDATE_BLOCK` action is called on it?

**Comment by mtias** [comment]
I'm still ok with reserving the + for empty text blocks only and the bottom of the page. I'm still not sure about the + button flow in any case, and it may be worth exploring in quick prototypes before diving too deeply in implementations.
