### ISSUE TITLE
Drop cap bouncing when you interact with paragraph block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#7989]
I feel this is a bug but it could be seen as an enhancement. If you set something as a drop cap and then edit you get this 'interesting' bouncing effect. Ideally it doesn't do this and just shows the drop cap.

![screenflick movie 91](https://user-images.githubusercontent.com/253067/42782652-745de246-8941-11e8-8dfb-03d2f598e031.gif)

**Comment by ocean90** [comment]
Related: #6359

**Comment by karmatosed** [comment]
Related and closing! Thanks for finding that @ocean90.
