### ISSUE TITLE
Fade out all outlines as you are typing

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#8]
Take the UI prototype for a spin: https://automattic.github.io/gutenberg/ — put the cursor in a paragraph, make some linebreaks, write some text, soak it up.

It's not intended to be super functional, but rather to give a feel for how the block and inline level controls can work, and how that feels while typing. Depending on how far we want to take it, here are some thoughts on how the feel of it all could be improved.

**Type selector + up/down rearrangement controls**

Should we be showing these controls when you hover over a block? Right now only the faint outlines show up. Might be nice for some quick rearranging to not have to click first. 

**Show outlines in block you are typing in**

Right now the faint outlines show only when you hover over a block with a mouse. Should we be showing these outlines as you are typing inside a block as well? (And only on that block?)

**... OR: fade out all outlines as you are typing?**

Related to hover outlines, instead of showing outlines on the block you are typing in, we could consider fading out *all* outlines as you are typing, even outlines on block that your mouse is currently over. The cursor itself fades out anyway, maybe the outlines should too?

**When rearranging blocks, the block moved should stay `is-selected`**.

Moving around blocks right now is neat, but a little disorienting. Perhaps we should even add a subtle animation showing the block moving to its new place, squishing out the old block.

**Comment by mtias** [comment]
> Show outlines in block you are typing in

I think so. Right now if you press enter from a block and start a new one, the previous block retains the light gray border and the new one has none. We should start with only highlighting in gray the block being edited.

**Comment by mtias** [comment]
I think we would end up with three states:

- Hover state.
- Selected state.
- Editing state.

**Comment by ianstewart** [comment]
> Should we be showing these controls when you hover over a block? Right now only the faint outlines show up. Might be nice for some quick rearranging to not have to click first.

When trying it out I felt like I expected to see the controls appear without having to click. It made me pause.

**Comment by jasmussen** [comment]
As an update, **When rearranging blocks, the block moved should stay is-selected** has been fixed. 

Showing controls on hover is in progress: https://github.com/WordPress/gutenberg/pull/59

The remaining task, **fade out all outlines as you are typing**, we should do that. We should also consider it in the context of https://github.com/WordPress/gutenberg/issues/61

**Comment by jasmussen** [comment]
This is done in both prototypes.
