### ISSUE TITLE
Polish the experience for IE11, Edge and other browsers

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#800]
Aside from #664 which blocks testing for IE11, there are a few rough edges here and there —  a couple of stray scrollbars, some floats that break, and other little things. Let's make the IE experience good.

**Comment by mtias** [comment]
@jasmussen do we have anything actionable here?

**Comment by jasmussen** [comment]
I'm sorry I've just had to prioritize other things. I've still meant to test properly against IE, and polish, but just haven't gotten to it. I can unassign myself so others can take it on if they like?

**Comment by mtias** [comment]
I was more thinking about closing, as this is something that just needs to happen at every stage, and will never be "closed" otherwise.
