### ISSUE TITLE
Button block - option to 'Open in new window'

### ISSUE THREAD

**Issue by danztoxsmith** [WordPress/gutenberg#8000]
Please can we have the option to 'open in a new window' on the button block? Either in the inspector controls or done in the same way as links (image below).

![image](https://user-images.githubusercontent.com/8281172/42823374-46fe8f3c-89d5-11e8-8bc8-ab52e698151f.png)

This was mentioned in #1404 with the button label but it seems the part about setting the target was missed.

**Comment by designsimply** [comment]
Adding a screenshot showing the current state of the button block floating toolbar:

![screen shot 2018-07-17 at tue jul 17 11 14 54 am](https://user-images.githubusercontent.com/1119271/42833970-e7309a68-89b2-11e8-8916-858f87e1d470.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14000&action=edit running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

**Comment by afercia** [comment]
Worth noting this has been mentioned also in https://github.com/WordPress/gutenberg/issues/3350#issuecomment-410531124 with some more details. The point is while other blocks (Paragraph, Image, etc.) use a standardised `URLInput` component, instead the `Button` component uses a custom implementation of the URL input field and it misses the option "open in a new window". Also, the design is different:

**Comment by mvpspl619** [comment]
@afercia Great point. It may be better to change the `Button` component to use the standardized `URLInput` component. However, I'm not sure if it was implemented this way on purpose.

**Comment by mvpspl619** [comment]
@chrisvanpatten @aduth @youknowriad (sorry, not sure who's more appropriate to be involved on this issue) Maybe we don't need to use `RichText` in the `Button` component at all? It's not a general use-case to have parts of a button **bold** or _italic_. Either the entire button is bold or italic or not.

**Comment by nfmohit-wpmudev** [comment]
Submitted #10128 which addresses this enhancement.

**Comment by shoxton** [comment]
Will this feature be implemented at the core? if so, when?

**Comment by designsimply** [comment]
@shoxton it looks like work on this has been picked up by @nfmohit-wpmudev at https://github.com/WordPress/gutenberg/pull/10128, however, there is no guarantee of a timeline for something like that to get added and generally it depends on how much time the core team and other committers and contributors have to work on pull requests as well as code reviews for each other. In this case, it looks like there's some recent movement which is great!

@mvpspl619 thank you so much for the note about 12738!

**Comment by BrunoBoehm** [comment]
Would be amazing, buttons are an important part of a UI, and not being able to direct to an external link in a new tab (as well as nofollow, noopener etc...) is quite a limiting parameter.

**Comment by eddieali** [comment]
It is essential to have (open in new tab) option just like other components for Buttons as well. +1 vote to have that option in next release. Thanks

**Comment by kristarella** [comment]
+1 from a WordPress.com customer

**Comment by morgangrip** [comment]
Being able to choose to open a button link in a new window? Yes + 1 on that.

**Comment by mattpan32** [comment]
+1 to this as well. The buttons are great, just that it'll be much better if we could have an option to open it in a new tab.

Btw, am quite inexperienced with this so hope you guys don't mind me asking again if it was already asked above or in other threads. May I know what is the quick fix/alternative to make the block open in a new tab? Editing the html? Many thanks!

**Comment by edwinhamers** [comment]
Another frustrated Gutenberg user that battles with buttons that do not offer a target setting....
Get it together

**Comment by shoxton** [comment]
> +1 to this as well. The buttons are great, just that it'll be much better if we could have an option to open it in a new tab.
> 
> Btw, am quite inexperienced with this so hope you guys don't mind me asking again if it was already asked above or in other threads. May I know what is the quick fix/alternative to make the block open in a new tab? Editing the html? Many thanks!

you can try adding the `target="_blank"` attribute to the button element, or just use the link block that has the "open in new tab" functionality.

**Comment by edwinhamers** [comment]
> > +1 to this as well. The buttons are great, just that it'll be much better if we could have an option to open it in a new tab.
> > Btw, am quite inexperienced with this so hope you guys don't mind me asking again if it was already asked above or in other threads. May I know what is the quick fix/alternative to make the block open in a new tab? Editing the html? Many thanks!
> 
> @mattpan32 you can try adding the `target="_blank"` attribute to the button element, or just use the link block that has the "open in new tab" functionality.

Isnt Gutenberg supposed to "streamline the editing".

**Comment by ohlauren** [comment]
> @mattpan32 you can try adding the `target="_blank"` attribute to the button element, or just use the link block that has the "open in new tab" functionality.
Adding it to the button block results in an "unexpected or invalid content" error and you have to convert to html. The only way that seems to work right now is just creating a link in a paragraph, editing the html for that block, and adding `class="wp-block-button__link"` to the link there.

**Comment by lakellie** [comment]
+1 from a WordPress.com user

**Comment by fosterTerence** [comment]
+1

**Comment by rendzina** [comment]
+1 also but, until this is added, here is how to achieve this:

Here is a button as normal, without the '_blank' new page option:

<img width="633" alt="Button_1" src="https://user-images.githubusercontent.com/6018947/57065399-2d89bc00-6cc1-11e9-85f0-2a05f5840567.png">

Under the button options, select 'Edit as HTML':

<img width="624" alt="Button_2" src="https://user-images.githubusercontent.com/6018947/57065400-2e225280-6cc1-11e9-8693-fd39bf4c4a0d.png">

Now edit the HTML to add the code **target="_blank"** as shown, and save:

<img width="636" alt="Button_3" src="https://user-images.githubusercontent.com/6018947/57065401-2e225280-6cc1-11e9-9d3c-4921baf38ee7.png">

Clicking the button will now open in new page.

**Comment by mcknightd** [comment]
Also requesting this feature. Thanks

**Comment by gpmw** [comment]
+1 from a WordPress.com customer

**Comment by phschmanau** [comment]
+1 This feature would be nice.

**Comment by gmmedia** [comment]
You add target="_blank" to a link but not to the button link? Why?

It's so frustrating.

This is what happens if you add the target via Edit as HTML
![button-block](https://user-images.githubusercontent.com/7474702/57605108-2aff5000-7566-11e9-8366-8881d06df555.png)

**Comment by taropaa** [comment]
This makes the block completely useless. Please add.

**Comment by dionysous** [comment]
In order to use this Block on landing pages, we need to have `rel` and `target` as option, otherwise we can't use this block.

**Comment by designsimply** [comment]
> +1 from a WordPress.com user in #12136336-hc (noting for myself as they asked me to notify them if this ever does end up being implemented)

@lakellie hey there! Thanks for adding this note. I would recommend in the case of someone wanting to follow progress to create a GitHub account and click the "Subscribe" option under Notifications in the column on the right side of this issue.

> +1 from a WordPress.com customer

> +1 from a WordPress.com customer

@kristarella @gpmw for cases where you are doing customer support for a company and someone requests a change, it would be really awesome to include a quote with any reasons why or what the customer's end goals are and how the enhancement would be helpful for them. For me, it makes the request much more compelling and it also helps a lot when working on prioritization.

> In order to use this button block on landing pages, we need to have rel and target as option, otherwise we can't use this block.

@dionysous can you please add a comment to https://github.com/WordPress/gutenberg/issues/13542 about the `rel` option too? It would be helpful to make a quick note about why it's needed if possible. :)

**Comment by mdrockwell** [comment]
+1 from a WordPress.com user.

**Comment by jennl524** [comment]
Hi, has this been resolved? Display of a button of page and upon click, it'll open a new tab or window?

**Comment by GlennMartin1** [comment]
+1
This is a much-needed feature in core.

**Comment by dougwollison** [comment]
I'd like to point out that this should also be accounted for on the Button component itself (the rel attribute I mean), and by extension components that use Buttons, such as Notices (from what I can tell if I want to do this currently, I have to write an onClick callback).

**Comment by wouthe** [comment]
+1
I don't understand why this is not here yet :/

**Comment by nfmohit-wpmudev** [comment]
> +1
> I don't understand why this is not here yet :/

Hey there, @wouthe ! Thank you for your query ❤️

This feature is now live in the Gutenberg plugin and will be included in the core soon. In order to be able to use this right now and to also see other cool stuff that we developers are working on, please [install the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/).

Thanks! ❤️

Regards,
Nahid

**Comment by wouthe** [comment]
> > +1
> > I don't understand why this is not here yet :/
> 
> Hey there, @wouthe ! Thank you for your query ❤️
> 
> This feature is now live in the Gutenberg plugin and will be included in the core soon. In order to be able to use this right now and to also see other cool stuff that we developers are working on, please [install the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/).
> 
> Thanks! ❤️
> 
> Regards,
> Nahid

Nahid, super, great to hear! If I install the plugin, will it not conflict with the core itself?
Thanks!
Wout

**Comment by nfmohit-wpmudev** [comment]
>Nahid, super, great to hear! If I install the plugin, will it not conflict with the core itself?
>Thanks!
>Wout

Hi there, @wouthe !
Thank you for your query.

First of all, sincere apologies about the delayed response here. The notification somehow missed my eyes.

If you install the plugin, it will not conflict with the core. It is more like an "_extension_", which lets you experience the upcoming features of the project.

Hope this helps. Thanks!

Regards,
Nahid

**Comment by cinghaman** [comment]
Hi @nfmohit-wpmudev do we know when this would become part of the core gutenberg?

**Comment by GlennMartin1** [comment]
> Hi @nfmohit-wpmudev do we know when this would become part of the core gutenberg?

This is already in WordPress 5.3 core, which was released on November 12.

**Comment by cinghaman** [comment]
@GlennMartin1 thanks, so i can disable the plugin and it won't affect/break the  button I have already setup

**Comment by GlennMartin1** [comment]
Yes you can, if you are running WordPress 5.3.

Keeping the Gutenberg plugin enabled gives you frequent small editor improvements (about every two weeks when a new Gutenberg version is released).

Having the Gutenberg plugin disabled, you'll eventually get the same updates (about every 3-4 months when a new WordPress version is released).

**Comment by cinghaman** [comment]
@GlennMartin1 thanks for the detail info :)

**Comment by gmmedia** [comment]
Now we have the link rel field in the button block, but still not for all other links.
