### ISSUE TITLE
IE11: top toolbar layout breaks when using navigateRegions

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#8008]
With IE11, when using the `Ctrl + backtick` keyboard shortcut to navigate through the navigable regions, the top toolbar layout breaks. See screenshot below: the elements that should stay on the right, are "shifted" to the center of the top bar:

![screenshot 34](https://user-images.githubusercontent.com/1682452/42831355-69efdd48-89ee-11e8-8b82-dbf6ec97aa90.png)

Haven't identified the actual issue, but seems to me it's related to the combination of flexbox used on the top bar and the `::after` pseudo element used for the focus style, which is a flex item (being a child of a flex container). Seems IE 11 doesn't take into account it's positioned absolutely.

Hint: I get the same "shifting" in Chrome if I add a third, empty, flex item e.g. `<span></span>`.

/Cc @jasmussen

**Comment by brandonpayton** [comment]
I confirmed this issue and added a PR to correct it. Thanks for the clue, @afercia!
