### ISSUE TITLE
eslint rule for object property shorthand/object-shorthand

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#8009]
Looks like we don't have an eslint rule around `object-shorthand`, as discovered in https://github.com/WordPress/gutenberg/pull/7941#discussion_r203121895. We do use it in the code in some places, I like it, so I'd advocate we use it anytime we can.

We should just make a rule around it. I'd prefer we enforce using it whenever possible (`"always"`), but I mainly don't like it being unclear.

**Comment by GeckoLisa** [comment]
Picking this up as my first ever open source issue. 🤞

**Comment by gziolo** [comment]
As commented in https://github.com/WordPress/gutenberg/pull/18123#issuecomment-546813694

> It looks like `object-shorthand` is already set up in the WordPress plugin for ESLint:
> https://github.com/WordPress/gutenberg/blob/af9ea75664c29befe35cd8526af0ea8b4f05b070/packages/eslint-plugin/configs/esnext.js#L26
> 
> I was surprised seeing no errors reported and that's why I double-checked. I don't think we should override it for the Gutenberg specific config. We can simply close the parent issue. Sorry about that. Thank you for helping with closing the open issue though 🙇

@GeckoLisa - thanks for your help!
