### ISSUE TITLE
Encoding issue with dash in quote source 

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#801]
Haven't been able to reliably reproduce, but I get in this state every once in a while:

![image](https://cloud.githubusercontent.com/assets/548849/26097784/f191a4a8-3a25-11e7-8e54-e2b97a737637.png)

**Comment by youknowriad** [comment]
Haven't seen this in a while, is this still an issue?

**Comment by mtias** [comment]
I have seen this again today. Often happens when saving demo content as a real post, and checking on the front-end.

**Comment by mtias** [comment]
I am considering dropping the forced dash and make it optional for the writer.

**Comment by dmsnell** [comment]
Looks like [a gremlin](https://webmasters.stackexchange.com/questions/15709/strange-characters-appearing-on-websites-ascii-unicode). Are we saving the Unicode character or the HTML-encoded sequence?

**Comment by mtias** [comment]
We have dropped the dash.
