### ISSUE TITLE
Testing: Consider resetting test site when running end-to-end tests

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8010]
If a previous end-to-end test run is abruptly terminated, it can leave the test site in a fragmented state where test plugins will be pre-activated on the next test run, causing unexpected test failures which are difficult to debug.

We should consider automatically disabling any activated plugins when the end-to-end test suite starts. In most cases, this will not need to do anything, but will account for the rare case where it does.

**Comment by tofumatt** [comment]
I agree, it'd be good not to have to re-run tests to clear themselves out.

This ties into #7959, and I think can be easily accomplished by resetting the (soon-to-be-sepaarte, hopefully, test) site with WP CLI using `npm`'s `pretest` script.
