### ISSUE TITLE
Blocks: Dropping an audio file should insert an Audio block

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8020]
Related: #8021

When drag-dropping an audio file from my computer, a File block is created. Since Audio block exists, it should include a transform to create itself from the file (via the `transforms` property `files` type).

See also:

- [Image block reference implementation](https://github.com/WordPress/gutenberg/blob/b06a33569a2b860110cb8d3f113ccf6c2b36e492/core-blocks/image/index.js#L128-L144)
- [Block API `transforms` property](https://wordpress.org/gutenberg/handbook/block-api/#transforms-optional)

**Comment by skorasaurus** [comment]
related https://github.com/WordPress/gutenberg/issues/9028
