### ISSUE TITLE
Blocks: Dropping an video file should insert a Video block

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8021]
Related: #8020

When drag-dropping a video file from my computer, a File block is created. Since Video block exists, it should include a transform to create itself from the file (via the `transforms` property `files` type).

See also:

- [Image block reference implementation](https://github.com/WordPress/gutenberg/blob/b06a33569a2b860110cb8d3f113ccf6c2b36e492/core-blocks/image/index.js#L128-L144)
- [Block API `transforms` property](https://wordpress.org/gutenberg/handbook/block-api/#transforms-optional)

**Comment by noisysocks** [comment]
#8122 has implemented this.
