### ISSUE TITLE
Block List: Removing a block triggers a tags REST API request

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8024]
**Describe the bug**

When removing a block, a network request is issued ot the `/wp/v2/tags` endpoint. This should not be necessary, unless I am not privy to specific details for its required existence.

**To Reproduce**

1. Navigate to Posts > Add New
2. Open your browser developer tools to its Network tab
   - [Chrome instructions](https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#requests)
3. Add a block
4. Remove the block added in Step 3
5. Observe network request for `/wp/v2/tags`

**Expected behavior**

There should be no request.

**Comment by jorgefilipecosta** [comment]
If we close and reopen the sidebar or go from the block sidebar to the document sidebar, the taxonomies are requested again.
What happens is that HierarchicalTermSelector and FlatTermSelector request the taxonomies on Mount.
I think what happens here is that when removing a block we go from block sidebar to document sidebar so the taxonomy component are mounted and the request happen.

**Comment by aduth** [comment]
Duplicate #7266
