### ISSUE TITLE
Add Block: Map

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#803]
Splitting this out from #283 .

## Attributes

- None, Left, Right, Center, Full Width.
- Caption

## States

Placeholder:

![map placeholder](https://cloud.githubusercontent.com/assets/1204802/26104870/056386c6-3a40-11e7-9d9e-d45195f0ebe0.png)

Neutral:

![map neutral](https://cloud.githubusercontent.com/assets/1204802/26104873/081b9e1c-3a40-11e7-8d30-247cbd535d8f.png)

Selected:

![map selected](https://cloud.githubusercontent.com/assets/1204802/26105197/56f49e20-3a41-11e7-8287-f1ab9921157a.png)

**Comment by mtias** [comment]
We also have #315 :D

**Comment by jasmussen** [comment]
Hah, closing this in favor of that, but updating the states.

**Comment by mtias** [comment]
Great, thanks.
