### ISSUE TITLE
Gutenberg menu item Feedback goes to PollDaddy and offers URL to Support non-clickable. 

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#8039]
**Describe the bug**
When a user would need to support, she has a menu item that might get her there called "Feedback" under the Gutenberg menu. 
When she clicks on it the first question to have a support or feedback. If she clicks support is states "Support is available via the support forum. Support can be reached here https://wordpress.org/support/plugin/gutenberg/"
The link is not clickable, not hot. 
The only place where the user can click is the "Continue" button and it gets her deeper into the PollDaddy survey. 

**To Reproduce**
1. Dashboard > Gutenberg > Feedback
2. Feedback
3. select "Support" 
4. click on "Continue" 

**Expected behavior**
I expected the be a way to get to the support forum so I could go and asked my questions there. 

I would find it a bit more intuitive if  the two were separated already on the menu level: 
1) Feedback goes to the PollDaddy Survey
2) Support goes to the Support Forum.

**Screenshots**
http://recordit.co/IxC0t1Z3aY

**Desktop (please complete the following information):**
 - OS: MacOS 10.11.6
 - Browser Firefox Development edition
 - Version 62.0b9

**Comment by designsimply** [comment]
Tested and confirmed.

![screen shot 2018-07-18 at wed jul 18 5 47 42 pm](https://user-images.githubusercontent.com/1119271/42913513-b1e80a20-8ab2-11e8-9fdf-fe07d2720c60.png)
<sup>Seen at https://wordpressdotorg.polldaddy.com/s/gutenberg-support?p=3&r=4E0A7074B017DCF7CB8DCC9503E80CAE running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

**Comment by bph** [comment]
Thanks @designsimply - seems there is already a solution in Gutenberg 3.3 (next version) with "Support" as separate menu item in WPAdmin with a direct link to the support forum.

**Comment by designsimply** [comment]
Ace! Let's close this then. 😊
