### ISSUE TITLE
Add Block: Audio

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#804]
Splitting this out from #283 .

## Attributes

- None, Left, Right, Center, Full Width.
- Caption

## States

Placeholder:

![audio placeholder](https://cloud.githubusercontent.com/assets/1204802/26105398/14889b8a-3a42-11e7-9799-eea2040f225e.png)

Neutral:

![audio neutral](https://cloud.githubusercontent.com/assets/1204802/26105401/181fb8be-3a42-11e7-9019-5c0f4fe1e1d5.png)

Selected:

![audio selected](https://cloud.githubusercontent.com/assets/1204802/26105404/1adca634-3a42-11e7-984e-d1620df21ab9.png)

**Comment by westonruter** [comment]
See also the new Audio widget which is now in `trunk`:

* https://github.com/WordPress/wordpress-develop/blob/master/tests/phpunit/tests/widgets/media-audio-widget.php
* https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/js/widgets/media-widgets.js
* https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/js/widgets/media-audio-widget.js

**Comment by timmyc** [comment]
@jasmussen should this block be similar to the audio widget where we allow users to select audio from the library, or are you thinking of just having the URL input?

**Comment by jasmussen** [comment]
It was designed as a replacement for the audio shortcode, which allows you to hotlink URLs. But maybe it should indeed be the new widget, I like the idea of not having two blocks that do the same. Can you insert a sound file from a URL in the widget?

**Comment by timmyc** [comment]
You can insert a url in the audio widget, it is kind of buried in the media modal though:

![customize__blog_ _xwp](https://user-images.githubusercontent.com/22080/28849339-74fc66a2-76cb-11e7-9e21-81f8be2ab828.png)

![customize__blog_ _xwp](https://user-images.githubusercontent.com/22080/28849351-814a70a2-76cb-11e7-96a4-3b6a30abc06c.png)

Seems like your original design is much quicker to insert the URL - I can pursue that in the first iteration of this block.

**Comment by westonruter** [comment]
It seems the main thing missing is selecting the file from the media library.

Beware, however, that there are many more inspector-style settings for audio, including the selection of alternate HTML5 audio sources, configuring preloading, looping, and autoplay:

![image](https://user-images.githubusercontent.com/134745/28858358-d766594a-7704-11e7-8904-f54a1b142938.png)

**Comment by jasmussen** [comment]
Hmm. Maybe it does make sense to have a separate "Embed Music" block, or someting in that vein. I can't quite wrap my head around it. 

The thing is, I think there's a legit use case for both the one from the media library, and the one where you just have a URL that is hotlinked. As @iseulde suggested yesterday, a hotlinked URL is an embed, in a way.

CC: @melchoyce for thoughts also.

**Comment by melchoyce** [comment]
Maybe we could consider something like this:

![image](https://user-images.githubusercontent.com/2846578/28886542-df49f58a-7787-11e7-9715-a047b5dfe962.png)

**Comment by timmyc** [comment]
Quick screen grab of progress thus far, will hopefully push up a branch/create a pr later today:

<img width="620" alt="screenshot_8_8_17__2_36_pm" src="https://user-images.githubusercontent.com/22080/29095786-0a568586-7c47-11e7-9054-e1451e99ad6d.png">

**Comment by getsource** [comment]
Having no text in between the button (as in @melchoyce's example) and the URL makes it look a bit like the insert button is referencing the URL entry box.

**Comment by mtias** [comment]
Done in #2299. Further improvements in new issues.
