### ISSUE TITLE
Inserter: Long block names - line break

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#8047]
**Describe the bug**
If the block name is very long it just breaks in a new line. 
Example:
![wpblocks de_wp-admin_post php_post 508 action edit 1](https://user-images.githubusercontent.com/695201/42941427-103f6f1e-8b5d-11e8-9584-6d6674664d23.png)

With `hyphens: auto`, we can set the break at a correct position.
![wpblocks de_wp-admin_post php_post 508 action edit 4](https://user-images.githubusercontent.com/695201/42941429-11109c88-8b5d-11e8-9516-0ecd3b8a7860.png)

This feature doesn't work on Chrome/Windows, see https://caniuse.com/#feat=css-hyphens But it's an enhancement for all other users.

**Comment by hedgefield** [comment]
Seems fine to me, it's a small non-essential visual tweak, and it forces the use of the `lang` attribute which I understand is good for accessibility.

**Comment by karmatosed** [comment]
As a check is hyphens used in core? If so then I don't mind.

**Comment by La-Geek** [comment]
Please look at the [browser stats](http://gs.statcounter.com/). Chrome is the most used browser worldwide.
Probably the hyphenator.js would solve this issue -> https://github.com/mnater/hyphenator

**Comment by tellthemachines** [comment]
Browser support for this feature is [actually not bad](https://caniuse.com/#feat=css-hyphens) though Chrome on Windows inexplicably fails. I'd agree with adding it as a progressive enhancement.

**Comment by laras126** [comment]
Tried this out just in the inspector and seems like a straightforward fix! Since browsers ignore CSS properties they don't support, I don't think there's anything we need for progressive enhancement here.

Also, the latest 5 versions of Chrome have full support for `auto`.

**Comment by t-hamano** [comment]
I have tested with a few words and it appears that hyphenation is not always done at the proper place. Also, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#browser_compatibility), non-English languages do not appear to be supported yet.

For now, I think it is better not to hyphenate.  What do you think?

### Pneumonoultramicroscopicsilicovolcanoconiosis

| Before | After |
|--------|--------|
| ![Pneumonoultramicroscopicsilicovolcanoconiosis_before](https://user-images.githubusercontent.com/54422211/230763714-01ea5571-5d4d-4bfd-b16f-1af68062b31f.png) | ![Pneumonoultramicroscopicsilicovolcanoconiosis_after](https://user-images.githubusercontent.com/54422211/230763717-1270c9c5-9d00-4589-acd4-e74c1e3d5ecc.png) | 

### Supercalifragilisticexpialidocious

| Before | After |
|--------|--------|
| ![Supercalifragilisticexpialidocious_before](https://user-images.githubusercontent.com/54422211/230763722-1a1188be-8fd1-419d-ba84-d0e83a88de61.png) | ![Supercalifragilisticexpialidocious_after](https://user-images.githubusercontent.com/54422211/230763724-eed65978-769b-4ac7-a248-634f8d312dcf.png) |

**Comment by t-hamano** [comment]
I've thought about this issue a bit more, and am beginning to think that if it's an improvement for a specific OS or language, it might be worth going ahead with.

Currently, `hyphens: auto` is used in the following two places in the Gutenberg project:

https://github.com/WordPress/gutenberg/blob/159d01a01b61ee76159ab67bc94d0d7cb3d90b35/packages/components/src/tabs/styles.ts#L78
https://github.com/WordPress/gutenberg/blob/159d01a01b61ee76159ab67bc94d0d7cb3d90b35/packages/editor/src/components/post-panel-row/style.scss#L16

It seems to be used widely in core:

https://github.com/search?q=repo%3AWordPress%2Fwordpress-develop%20hyphens%3A%20auto&type=code
