### ISSUE TITLE
Fix unexpected behaviour for `@wordpress/is-shallow-equal` package.

### ISSUE THREAD

**Issue by nerrad** [WordPress/gutenberg#8048]
**Describe the bug**
The [docs for this package](https://github.com/WordPress/gutenberg/tree/master/packages/is-shallow-equal) describe being able to import two specific exports for `is-shallow-equal`:

You can import a specific implementation if you already know the types of values you are working with:

```js
import isShallowEqualArrays from '@wordpress/is-shallow-equal/arrays';
import isShallowEqualObjects from '@wordpress/is-shallow-equal/objects';
```

However, with the latest release of the package this no longer works.  When building using webpack, the build fails with:

```
ERROR in ./src/index.js
Module not found: Error: Can't resolve '@wordpress/is-shallow-equal/arrays'
```

**To Reproduce**
I've [created a repository](https://github.com/nerrad/is-shallow-equal-e2e-package-test/tree/master) with some simple code to demonstrate what happens.

**Comment by aduth** [comment]
The root cause of this is that the require semantics were expecting `arrays.js` and `objects.js` files in the root module directory. These no longer exist (they live in `build`), as apparently the package is now subject to the transpile build step (it was not originally).

**Comment by aduth** [comment]
See #7556 , cc @gziolo @omarreiss
