### ISSUE TITLE
Indication of parent blocks in the block library is unclear.

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8053]
**Issue:**

Currently, if a block contains child blocks, we display an additional layer behind the block's button in the block library:

![artboard](https://user-images.githubusercontent.com/1202812/42949990-0abdf748-8b41-11e8-9dcf-bab248f0e8d9.png)

I think the intention was for this to read as a "stack," but in practice, it looks like a 3D button or a shadow. 

**Suggestion:**

It might be better to include an additional layer, so that this clearly reads as a stack of multiple things: 

![artboard copy 3](https://user-images.githubusercontent.com/1202812/42950375-daa5e916-8b41-11e8-876c-0a04b5a40c53.png)

**Comment by mtias** [comment]
How would it look with blocks using custom background colors?

**Comment by kjellr** [comment]
> How would it look with blocks using custom background colors?

I think something like this could work — the top level is 100% of the background color, then 70% for the middle layer, then 40% for the bottom layer. 

![artboard copy 6](https://user-images.githubusercontent.com/1202812/42966545-87b4009c-8b6b-11e8-8fc8-0f2d16c2a8e9.png)

At first I thought we'd have to do something tricky to get around the small bit of overlap that's visible due to the middle layer's opacity... but I actually kind of like that it's semi-transparent.

**Comment by ZebulanStanphill** [comment]
Blocks using `<InnerBlocks />` stopped being distinguished from other blocks in the inserter a while ago. (At least since WordPress 5.3.) I'm closing this issue since it is no longer relevant.
