### ISSUE TITLE
"Image Settings" for the Image block disappears on smaller screens. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8056]
**Describe the bug**

On small breakpoints, the "Image Settings" section of the image block's sidebar settings disappears: 

![image-settings](https://user-images.githubusercontent.com/1202812/42956359-c89dff0e-8b4d-11e8-92f0-6000d44bfb9b.gif)

**To Reproduce**

1. Insert an image block. 
2. Check the settings sidebar. 

On larger screens, you'll see an "Image Settings" section, but on smaller screens you won't. 

**Expected behavior**

I'd expect that the settings panel content would stay the same at all breakpoints. Currently, there's no way to enter alt text or a link to the image while on mobile. 

Tested on Safari on iOS 11.4.1, and Chrome (67.0.3396.99) on Mac OS 10.13.5.

**Comment by mtias** [comment]
Seem related to #7750.

**Comment by nfmohit-wpmudev** [comment]
@kjellr @mtias #7781 fixes this as well.

Screencast:
![pull-7781](https://user-images.githubusercontent.com/20284937/43210788-d5e62e1c-9051-11e8-8652-e75cc402cc55.gif)

**Comment by youknowriad** [comment]
This is fixed now
