### ISSUE TITLE
Clicking on editable placeholder should hide text

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#806]
When clicking on editable's placeholder we should probably remove the placeholder text:

![image](https://cloud.githubusercontent.com/assets/548849/26105807/deaddf96-3a43-11e7-9f9a-003c11b34eaa.png)

**Comment by iseulde** [comment]
At the moment it's the same behaviour as a normal input field, which also leaves the text there on focus: https://codepen.io/iseulde/pen/mmjRYV

**Comment by jasmussen** [comment]
I tend to agree with Ella on this one. It feels a little weird since the text is centered here, but it's actually sort of how it "should" work.

**Comment by mtias** [comment]
Maybe the cursor and text alignment given the centered position is throwing me off.
