### ISSUE TITLE
Tips: Asked to Open Settings When Sidebar Already Open

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#8060]
While clicking through the tips as a first time Gutenberg user, I began reading the second tutorial tip:

![tip](https://user-images.githubusercontent.com/617986/42967145-33a22720-8b54-11e8-83c7-0a50727a861c.png)

It says to click "Settings" to **open** it. But my settings were already open, so when I clicked it, the settings closed causing confusion.

Maybe it should says something like "This is where you can close or open the Settings panel."

**Comment by youknowriad** [comment]
closed by #12911
