### ISSUE TITLE
Tips: 3rd tip is a bit confusing

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#8061]
While clicking through the tutorial tips as a new Gutenberg user, I noticed the 3rd tip:

![tip-preview](https://user-images.githubusercontent.com/617986/42967283-9eee047c-8b54-11e8-8df6-aa14ff0d031b.png)

Because the tip begins with a call to action... "Click", I expected to be able to perform the action it was telling me to do. But the "Preview" button is disabled. So I can't click it as the tips tells me to.

Maybe we can say something like, "The 'Preview' button loads a preview of this page so you can make sure you're happy with your blocks."

or "Once you have some content saved for this page, click 'Preview' to load a preview of it, so you can make sure you're happy with your blocks."

**Comment by mapk** [comment]
Similar feelings about the 4th tip. These tips appeared at the beginning of my G experience, so every time I read them, I felt that they were prompting me too soon. I hadn't written anything yet.

![screen shot 2018-07-19 at 1 14 32 pm](https://user-images.githubusercontent.com/617986/42967661-d6982834-8b55-11e8-98b9-64105971d2a1.png)

**Comment by melchoyce** [comment]
For that third tip, what do y'all think about:

> Once you have some content drafted, click the “Preview” button to make sure your blocks look like what you expect.

**Comment by mapk** [comment]
> [...] to make sure your **blocks** look like what you expect.

I wonder if we should just say "to make sure your **page** looks like what you expect." ? I'm not sure they'll retain the concept of "blocks" 3 tips in. But maybe?

**Comment by melchoyce** [comment]
This is super pedantic, but you could be previewing a post, not a page, which is why I suggested something more generic. Maybe there's a better solution?

**Comment by mapk** [comment]
> This is super pedantic, but you could be previewing a post, not a page, which is why I suggested something more generic.

I was thinking the same thing, but thought in this instance it really didn't matter. "Posts" are technically "pages" too. 

How about... "to make sure your **content** looks like what you expect." ?

**Comment by sarahmonster** [comment]
> Once you have some content drafted, click the “Preview” button to make sure your content looks like what you expect.

Let's change "click" to something more device-agnostic, and see if we can nix that double "content", and maybe make it a bit shorter/snappier. What about:

> Ready to publish? Use the "Preview" button to see what your content will look like.

or 

> Finished writing? Use the "Preview" button to check your content before you publish.

**Comment by melchoyce** [comment]
Maybe:

> Once you're finished writing, use the "Preview" button to check your content before you publish.

**Comment by melchoyce** [comment]
@sarahmonster Do you have any ideas for the fourth tip?

**Comment by sarahmonster** [comment]
Do we need a fourth tip? Since the publish button is so close to the preview button and part of the same experience, we might be able to combine the messaging there with the third tip, and remove the extra tip. 

> Finished writing? Use the "Preview" button to check your content, and then use the "Publish" button to publish.

....ideally without the double-publish.

**Comment by melchoyce** [comment]
That's a good idea, we probably don't need that fourth tip. 

@michelleweber can you help us massage Sarah's latest message so it doesn't repeat "publish?"

**Comment by michelleweber** [comment]
Maybe something like:

Finished drafting? Use the "Preview" button to see how your content will look to readers, and then use the "Publish" button when you're ready to add it to your site.

(I try not to use "writing" all the time for stuff like this because not everyone's writing. Drafting isnt' perfect either, but it's *slightly* more open ended and sounds less stodgy than "Finished creating your content?", which makes my eye twitch.)

**Comment by sarahmonster** [comment]
Agreed on the "writing" point! Other words that might work here: "creating", "composing".

**Comment by mapk** [comment]
I'd avoid "Finished writing?" or "Ready to publish?" because at the time of viewing this tip, they've most likely not created any content yet. For this reason, I think Mel's solution of "Once you've drafted some content, ..." works better.

**Comment by melchoyce** [comment]
Yeah, at this point they have an empty page — so this message needs to refer to future actions, not actions they can take now.

**Comment by melchoyce** [comment]
> Once you’ve drafted some content, use the “Preview” button to see how it will look to readers. When you’re ready to add it to your site (exciting!), use the “Publish” button.

^ From @michelleweber

**Comment by melchoyce** [comment]
Let's make sure any additional feedback happens directly in https://github.com/WordPress/gutenberg/pull/16131.

**Comment by noisysocks** [comment]
#18041 has addressed this by removing dot tips in lieu of a welcome guide modal.
