### ISSUE TITLE
Replace "Textual Alternative" label with "Alternative Text"

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8063]
I noticed we're using a pretty non-standard phrasing for alt text:

<img width="929" alt="screenshot 2018-07-20 01 04 45" src="https://user-images.githubusercontent.com/376315/42976530-e56bc9f6-8bb9-11e8-99cc-bd5486deff42.png">

A quick Google search confirmed my suspicions that nobody uses this term—the top results are alternatives to a software called Textual, and issues in this repo. 😈 

I'd suggest replacing it with the more commonly-used (and Google-friendly for those users who'd like more context) "Alternative (ALT) Text".

Related: we may want to reconsider the "Source Type" label directly below, while we're at it—see #7855.

**Comment by michelleweber** [comment]
+1!
