### ISSUE TITLE
Visual issues when outermost scrollbar is scrolled downward

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#8068]
The outermost scrollbar causes some visual issues with the side controls and the formatting toolbars when it is scrolled down:

![image](https://user-images.githubusercontent.com/19592990/43021075-fcbb1882-8c27-11e8-95b5-efdc4fa1b9a7.png)

Video:
https://supergeniuszeb.com/wp-content/uploads/2018/07/gutenberg-outermost-scrollbar-visual-issues.webm

This causes formatting toolbars to go off-screen even though they are supposed to be sticky, and it causes the side controls to overlap the top bar of the editor when they are scrolled under it.

Tested in Firefox Beta on Antergos Linux, using WordPress 4.9.7 and Gutenberg 3.3.0.

**Comment by designsimply** [comment]
Would it be possible for you to document the OS, browser, WP, and Gutenberg plugin versions you are using when submitting issues such as this? It is also best practice to include a screenshot inline (uploaded to the repo) in addition to the video (which is awesome!) if possible. This will make it easier and faster to see and understand the problem.

**Comment by SuperGeniusZeb** [comment]
@designsimply Done! :smile:

**Comment by rogerlos** [comment]
See my note here, it's a bug in Gutenberg's editor stylesheet:

https://github.com/WordPress/gutenberg/issues/8790#issuecomment-413387324

**Comment by ZebulanStanphill** [comment]
Interestingly, this issue is no longer occurring for me unless the black nav menu on the far left is taller than the viewport height. Previously, the issue could still occur regardless of the height of the black nav menu, as my screenshot demonstrates.

I am closing this issue in favor of #8790, which covers the remaining issue.
