### ISSUE TITLE
Text Toolbar not working properly

### ISSUE THREAD

**Issue by Rcreators** [WordPress/gutenberg#807]
Text toolbar is not working properly. I am not sure are this bugs are its still not implemented in early testing. Still posting here.

1) Whatever the text alignment it will still show left align. Needs to change the active state when its right align or center
2) Missing Justify Text
3) Second Toolbar which contains Bold. Italic, underline and strickthrough, none of them working by clicking on them. So if i select text and click on Bold (B symbol), it is not making it bold. While it works with shortcuts. So doing ctrl + B making it bold.

**Comment by jasmussen** [comment]
Hi! Thanks for the ticket. Just to be sure, did you test the prototype when reporting these? I.e. https://wordpress.github.io/gutenberg/ ?

Because 1 and 3 are most definitely fixed in the editor plugin that we're building, but as I recall they are issues in the UI prototype.

Justify text was removed in WordPress 4.7: https://make.wordpress.org/core/2016/10/28/editor-changes-in-4-7/ — if you need that, it will have to be added through a plugin such as TinyMCE advanced.

**Comment by youknowriad** [comment]
@jasmussen Is it time to drop the prototypes?

**Comment by Rcreators** [comment]
@jasmussen Yes i am testing here: https://wordpress.github.io/gutenberg/

And it seems that the point i described are not working. I am using Chrome Version 58.0.3029.110 (64-bit) for testing, which is the latest.

**Comment by jasmussen** [comment]
@youknowriad 

> Should we think of dropping the prototypes?

Perhaps move them to a separate repo, or archive them somewhere. They have historical value for sure! And/or: can we redirect the prototype URLs to the main README without jumping through hoops?

**Comment by youknowriad** [comment]
> can we redirect the prototype URLs to the main README without jumping through hoops?

Seems like an easy change (need admin rights ;))

**Comment by jasmussen** [comment]
@Rcreators The prototypes are no longer being updated, alas. We are working on the feature plugin now. Here's a snapshot:

![screen shot 2017-05-16 at 16 28 31](https://cloud.githubusercontent.com/assets/1204802/26111196/c92909be-3a54-11e7-8609-817d28cdaa4f.png)

If you feel adventurous you can test a very very early prerelease of the plugin by uploading this zip to your plugins page and activating it: https://wordpress.slack.com/files/joen/F5B126517/gutenberg-2017-05-10.zip

**Comment by Rcreators** [comment]
@jasmussen Thanks. Will sure do that and let you know if come up with any bug or idea.

**Comment by Rcreators** [comment]
@jasmussen I am not able to download plugin as i am not a wordpress.slack member. Can you email me or add me on wordpress.slack channel. that will be great.

**Comment by jasmussen** [comment]
> I am not able to download plugin as i am not a wordpress.slack member. Can you email me or add me on wordpress.slack channel. that will be great.

In this very pre alpha period it's best that you sign up for slack and get it there, but it's free and easy: https://make.wordpress.org/chat/
