### ISSUE TITLE
Spacer - Insertion point overlap

### ISSUE THREAD

**Issue by marcusig** [WordPress/gutenberg#8070]
**Describe the bug**
When inserting a spacer block, the element 'insertion-point' overlaps the top part of the spacer, making the top handle unusable.

**To Reproduce**
1. Create a text block
2. insert a spacer block
3. insert an other text block
4. Try to resize the spacer using the top handle 

**Expected behavior**
If the handle is there, it should be usable. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11990914/42992371-9db43dec-8c08-11e8-80d9-5397bce4ae8d.png)

**Desktop**
 - OS: mac osx
 - Browser Chrome v67.0.3396.99

I'm not 100% sure that the top handle is necessary as naturally we would drag from the bottom, but if it's there it should work.

**Comment by Soean** [comment]
Thanks for your report, the top handle was removed in #7799 (Gutenberg 3.3)

**Comment by marcusig** [comment]
Ah sorry I missed that. Thanks 👍
