### ISSUE TITLE
Block "Columns (beta)" : Possibility to have only one column

### ISSUE THREAD

**Issue by funkycram** [WordPress/gutenberg#8073]
Sometimes we need to have several blocks inside a main block.
"Columns (beta)" make this possible, but we cannot choose **one** column only.

**Comment by alexsanford** [comment]
Related: https://github.com/WordPress/gutenberg/issues/4900

Currently you can work around this by using the text box to set the number of columns to `1`.

**Comment by rinkuyadav999** [comment]
Yes, we should also able to select 1 column.

**Comment by designsimply** [comment]
Closing because, as mentioned above, it is already possible to set the number of columns to one in Settings > Block (in the sidebar of the editor) and because the Section block has been proposed in #4500 for the purpose requested here which is to have several blocks inside a main block.

**Comment by Lissy01** [comment]
In Version WP 5.1. I could use Column-Block with one Column as a Container with fullsize like it is written in the post above.
In Version WP 5.2. I can NOT choose a Column Count smaller than two.
Is that realy true?

**Comment by designsimply** [comment]
@Lissy01 I just tested and it looks like that is true. I believe the group block is intended to be used instead of a single-column block. The group block should be released in WordPress 5.3 and you can install and activate the Gutenberg plugin to get access to it sooner.

**Comment by pattyok** [comment]
Why not just allow a single column? It allows for content to follow a simple design pattern. Requiring a different block for this makes no sense.

**Comment by Lissy01** [comment]
@pattyok, because It is simply not possible to select one column.
Gutenberg always switches to two columns.

**Comment by studiobovenkamer** [comment]
> Yes, we should also able to select 1 column.

This is not possible as per WP 5.2.  I don't understand why this is issues is closed. 
We really want to adopt the Gutenberg classes (wp-block-columns), but right now we have to hack our way around this issue because we cannot get a 1 column class or HTML layout that has the same wrapper class wp-block-columns like 2 columns and up do.

**Comment by Lissy01** [comment]
I get the tipp to use Group-Block which is a new feature of Gutenberg-Plugin but not in the Core.

**Comment by verdde** [comment]
@designsimply  please reopen.
