### ISSUE TITLE
Losing Blockquote Citation / Data recovery when changing block type

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#809]
I've noticed that when one changes a blockquote to another block type, the citation is lost. Here's a GIF:

![image](https://cldup.com/5qokKr-aey.gif)

This raises the general question of dataloss when changing between block types and whether the user can recover. This seems simple for something like the citation (why not just hang onto it?), but I realize that the same solution probably needs to exist for something like changing a photo gallery with 50 images to a heading.

Not fully understanding the technical issues here, I wonder whether it at least makes sense to maintain old block data until the user saves their changes. When considering what gets lost when changing, it's important to think of this as primarily an issue of **error recovery**, though the need to provide recovery would seem to fall off after the first minute, hour, and day.

**Comment by aduth** [comment]
Similar to #807, this appears to be specific to the now-unmaintained prototypes, not the plugin under active development. cc @jasmussen

**Comment by mrwweb** [comment]
Thanks for clarifying! Can instructions for finding and using the plugin get added to the README? I didn't realize there was a plugin as I had to step away from following this project for the last month. (sorry!)

**Comment by jasmussen** [comment]
> Edit: realizing that the repo is the plugin. I'm a genius. Readme clarification might still be nice.

No absolutely needs clarification. It's sort of a soft-launch because it's still very early. Some of the efforts ongoing now might be to replace the prototypes with the new editor, which can actually work outside of wp-admin. See also #655
