### ISSUE TITLE
Slider handle appears too big in Firefox

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#8090]
## The issue
The slider control handle appears to big in Firefox. This started happening at some point in `master` between Jul 15, 2018 and now.

## How to reproduce
- Use Firefox.
- Insert a Paragraph block
- Notice that the slider control handle appears much larger than it should.

## Screenshots
**Normal**
![gutenberg-slider-normal](https://user-images.githubusercontent.com/19592990/43014703-b2f31642-8c12-11e8-80b6-8e46f94d7aae.png)
**Bug**
![image](https://user-images.githubusercontent.com/19592990/43014746-d006b04a-8c12-11e8-8b7c-9c72ebac30ab.png)

**Comment by SuperGeniusZeb** [comment]
Still occurs in Gutenberg 3.4.0.

**Comment by chrisvanpatten** [comment]
@SuperGeniusZeb The PR (#8156) missed 3.4.

**Comment by ZebulanStanphill** [comment]
Fixed by #8156.
