### ISSUE TITLE
How to reuse a block in another block?

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#8092]
Let's say I have blocks "header", "button" and "image" and now I wish to create a block "call to action" that would need to contain all these elements.

I could use InnerBlocks with a locked template that has these blocks, but they would be in order, one after another. But the goal would be to have them in different places within some predefined markup.

For example the end result could be

```html
<div class="grid">
    <div class="row">
        <div class="column">
            <!-- header -->
        </div>
    </div>
    <div class="row">
        <div class="column">
            <InnerBlocks />
        </div>
        <div class="column">
            <!-- image -->
        </div>
    </div>
    <div class="row">
        <div class="column">
            <!-- button -->
        </div>
    </div>
</div>
```

How could I render a specific editable (but locked) blocks in the place of the comments?
Is it possible to use InnerBlocks more than once?
Looking at InnerBlocks source, it renders a BlockList, is it possible to use it directly to render a block?

**Comment by chrisvanpatten** [comment]
@ktmn As of now, you'd need to do a complex arrangement of InnerBlocks with allowedBlocks and such set. So ultimately you have a structure like:

```
gridBlock (innerBlocks)
  rowBlock (innerBlocks)
    columnBlock(innerBlocks)
      headerBlock

**Comment by SuperGeniusZeb** [comment]
In addition to what @chrisvanpatten, you could probably avoid using a lot of the containing blocks and have if you used CSS Grid and Flexbox to position and align the elements rather than creating rows/columns using a bunch of `<div>`s. What exactly do you want the CTA to look like?

**Comment by ktmn** [comment]
@chrisvanpatten this is what my original idea was but quickly ran into a wall due to all the extra markup that is generated in the editor when using InnerBlocks.

I guess the issue stems from the fact that I'm not trying to create an "original" Gutenberg solution, I'm trying to provide an alternative to already existing UI elements that were previously achieved with other means, so the markup should remain mostly the same.

```html
<div class="grid">
    <div class="row">
        <div class="column"></div>
        <div class="column"></div>
    </div>
</div>
```

If I created gridBlock, rowBlock and columnBlock, in the editor I would end up with 

```html
...
<div class="grid">
    <div class="editor-inner-blocks">
        <div class="editor-block-list__layout">
            <div data-type="my/row">
                <div class="editor-block-list__block-edit">
                    <div class="row">
                        <div class="editor-inner-blocks">
                            <div class="editor-block-list__layout">
                                <div data-type="my/column">
                                    <div class="editor-block-list__block-edit">
                                        <div class="column"></div>
                                    </div>
                                </div>
                                <div data-type="my/column">
                                    <div class="editor-block-list__block-edit">
                                        <div class="column"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
...
```

And it's just not feasible to convert the existing grid system CSS to handle all this extra markup and still function faithfully to front end. Not to mention all this block nesting makes it very slow, confusing and hard to click on things for the user.
For that reason I'm looking to "hard code" most of the markup and place editable blocks in key locations.

I guess the ideal solution would be if there was a way to render multiple single individual blocks similar to InnerBlocks:

```js
function edit() {
    return (
        <div className="grid">
            <div className="row">
                <div className="column">
                    <InnerBlock key="header1" block="core/heading" />
                </div>
            </div>
            <div className="row">
                <div className="column">
                    <InnerBlocks />
                </div>
                <div className="column">
                    <InnerBlock key="image1" block="core/image" />
                </div>
            </div>
            <div className="row">
                <div className="column">
                    <InnerBlock key="button1" block="core/button" />
                </div>
            </div>
        </div>
    );
}

function save() {
    return (
        <div className="grid">
            <div className="row">
                <div className="column">
                    <InnerBlock.Content key="header1" />
                </div>
            </div>
            <div className="row">
                <div className="column">
                    <InnerBlocks.Content template={contentTemplate} />
                </div>
                <div className="column">
                    <InnerBlock.Content key="image1" />
                </div>
            </div>
            <div className="row">
                <div className="column">
                    <InnerBlock.Content key="button1" />
                </div>
            </div>
        </div>
    );
}
```

Do you think that's something that's possible to do with the Gutenberg editor in the future?

**Comment by youknowriad** [comment]
This use-case is addressed using the `InnerBlocks` component and a template. See how the "Media & Text" block does it now https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/media-text/edit.js#L194-L198
