### ISSUE TITLE
Categories is only showing 2 category item and 1 item on sub category.

### ISSUE THREAD

**Issue by bantilan** [WordPress/gutenberg#8098]
## Issue Overview
When Creating or Editing a Post, under the Categories box on the right side - it only shows 2 items of Categories and 1 item of sub category. It doesn't show all of the category that I needed to check or uncheck. Currently, I have 70 categories on my site.

Guttenberg version: 3.3.0
Wordpress version: 4.9.7

## Expected Behavior
It should show all of the category in a manner that is not messy (expandable etc.)

## Current Behavior
only the first 2 categories are showing and 1 category in sub-categories.

## Screenshots / Video

Category showing in the gutenberg editor:  http://d.gaming.ph/iH7UJM
list of category currently in our site: http://d.gaming.ph/SrElnZ

## Related Issues and/or PRs
https://github.com/WordPress/gutenberg/issues/2154 - I think this open issues is related to this, showing all of the category.

**Comment by youknowriad** [comment]
Is this still the case with the last Gutenberg version?
Do you have any security plugins that can alter the REST API endpoints?

**Comment by aduth** [comment]
I am not able to reproduce this in my testing. All categories and subcategories are shown for me with a site of 120 categories.

Given the lack of response, I will assume this is now fixed. It can be reopened if additional information is provided.
