### ISSUE TITLE
Opening editor results in blank screen

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#8101]
**Describe the bug**
I Updated to v3.3.0 because I wanted to re-test a previous issue. When I tried to edit the page, the main content area was blank. The only items that showed on the page were the left-hand menu and top admin bar.

![gutenberg_editexistingcontent](https://user-images.githubusercontent.com/2078245/43034200-75a25758-8d1b-11e8-9c79-14ef3d25137b.png)

When viewing the console, the following errors were listed:

![screenshot_248](https://user-images.githubusercontent.com/2078245/43034307-8d73173a-8d1d-11e8-856d-4161d4f114d6.png)

I tried disabling ACF (and another ACF addon) but the editor still wouldn't display, so it's obviously not an error caused by ACF.

**To Reproduce**
1. I simply tried to edit a page that was created using the TinyMCE editor

_macOS Sierra 10.12.6 (16G1408)
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.3.0_

**Comment by thebugfixnet** [comment]
Yes, same here...

index.js:37 Uncaught TypeError: Cannot read property 'keycodes' of undefined
    at Object.<anonymous> (index.js:37)
    at n (index.js:1)
    at index.js:1
    at index.js:1
(anonymous) @ index.js:37
n @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
post-new.php:184 Uncaught TypeError: wp.blocks.unstable__bootstrapServerSideBlockDefinitions is not a function
    at post-new.php:184
(anonymous) @ post-new.php:184
index.js:1 Uncaught TypeError: Cannot read property 'withSafeTimeout' of undefined
    at Object.316 (index.js:1)
    at e (index.js:1)
    at wp.nux.0 (index.js:1)
    at index.js:1
316 @ index.js:1
e @ index.js:1
wp.nux.0 @ index.js:1
(anonymous) @ index.js:1
index.js:12 Uncaught TypeError: Cannot read property 'withFilters' of undefined
    at Object.<anonymous> (index.js:12)
    at n (index.js:1)
    at index.js:1
    at index.js:1
(anonymous) @ index.js:12
n @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
index.js:12 Uncaught TypeError: Cannot read property 'withFallbackStyles' of undefined
    at Object.<anonymous> (index.js:12)
    at n (index.js:1)
    at index.js:1
    at index.js:1
(anonymous) @ index.js:12
n @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
index.js:12 Uncaught TypeError: Cannot read property 'withState' of undefined
    at Object.<anonymous> (index.js:12)
    at n (index.js:1)
    at index.js:1
    at index.js:1
(anonymous) @ index.js:12
n @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
post-new.php:1880 Uncaught TypeError: Cannot read property 'initializeEditor' of undefined
    at HTMLDocument.<anonymous> (post-new.php:1880)
(anonymous) @ post-new.php:1880

**Comment by thebugfixnet** [comment]
@maddisondesigns seems that an simple delete of cache + reload with CTRL+F5 fixes this. At least for me it ist working now after this steps.

**Comment by maddisondesigns** [comment]
@thebugfixnet Yep, that worked for me as well. Thanks for that.

**Comment by designsimply** [comment]
@maddisondesigns are you using a multisite with subdomain install?

**Comment by maddisondesigns** [comment]
@designsimply Nope, mine was just a local site on my own development server. It's a copy of my main business site which is just a regular 'ol WordPress single site install.

Clearing the cache seemed to fix my issue but it looks like @celsobessa is still having the same issue on his multisite.

I hope we're not going to be seeing these issues once this is in core.

**Comment by designsimply** [comment]
@celsobessa could we move to the forums to do further troubleshooting? It would be helpful to work through the details for your specific case there to come up with some reliable steps to reproduce the bug before adding details back here on GitHub. https://wordpress.org/support/plugin/gutenberg/

Would it be possible to include the following details in the forums?

- Did you build Gutenberg from source or download and install through the Plugins page?
- Can you verify the error messages you are seeing? (I noticed the ones from the screenshot above are different than the ones pasted into the comment.)
- Have you tried disabling other plugins to rule out a plugin conflict?
- What theme are you using?
