### ISSUE TITLE
Editor styles loaded to end-user

### ISSUE THREAD

**Issue by nbrummerstedt** [WordPress/gutenberg#8102]
**Describe the bug**
The file `.../plugins/gutenberg/build/components/style.css` is loaded to the end user.
While the stylesheet might contain things that the end-user would need, it also contains very specific admin-area styles. For example, `.components-drop-zone` is targeted. 

The file is not excessively large, but it's still, in my humble opinion, a little backwards to send CSS to the user, that won't target anything in the HTML.

**Expected behavior**
Admin specific styles could be served in a stylesheet for admins.
Opinionated end-user styles could be merged into `../core-blocks/style.css`
This would also reduce the number of requests with one.

**Comment by samikeijonen** [comment]
@nbrummerstedt Do you mean you see it loaded in the front end? Because I only see it in the admin when using Twenty17 theme.

**Comment by youknowriad** [comment]
You probably have another plugin adding a dependency to `wp-components` to use on of these components in the frontend. That's not bad in itself, because these are meant to be generic components and the classnames follow a strict naming strategy which avoids most of the issues.
