### ISSUE TITLE
Button with setted background color does not render properly with outline type

### ISSUE THREAD

**Issue by Dartui** [WordPress/gutenberg#8106]
**Describe the bug**
After creating button and setting its background color, outline style does not render properly (only in Gutenberg editor). AFAIK, this is because inline styles, which are unnecessary.
https://github.com/WordPress/gutenberg/blob/201be4b98cc8ee5ebd249a5068added92385f08f/core-blocks/button/index.js#L120-L123
After deleting them in browser, each button style renders properly with correct colors.

**To Reproduce**
1. Insert new button
2. Set background color (to any color)
3. Try to change type of button

**Screenshots**
![obraz](https://user-images.githubusercontent.com/2657856/43037177-c1ad00e6-8d0a-11e8-8d01-ebed28187e08.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 61.0.1

**Additional context**
- Gutenberg version: 3.3.0
- WordPress version: 4.9.7

**Comment by sourourn** [comment]
Reproduced the same issue 

https://cld.wthms.co/3CdeUU

https://cld.wthms.co/yhpRg9

Desktop (please complete the following information):

    OS: MacOS 10.13.6 
    Browser: Firefox
    Browser Version: 61.0.2 

Additional context

    Gutenberg version: 4.0.0
    WordPress version: 4.9.8

**Comment by designsimply** [comment]
Thank you for teting @sourourn! 

I'm adding your screenshots inline for reference:

![screen shot on 2018-10-23 at 23-24-43](https://user-images.githubusercontent.com/1119271/48038193-d4cfd100-e12c-11e8-8ebe-e0c8d9b7a727.png)

![screen shot on 2018-10-23 at 23-25-44](https://user-images.githubusercontent.com/1119271/48038196-d7cac180-e12c-11e8-8e97-2e74fbee370f.png)

**Comment by jorgefilipecosta** [comment]
Hi all, thank you for reporting and testing this issue 👍 I tested the issue in the last version of Gutenberg, and it seems that the button previews match the expected block result, so I think this problem was fixed. If the problem is persisting in your tests, feel free to reopen the issue and we will look further.
