### ISSUE TITLE
Video, Audio, and embeds blocks: inconsistent input field width

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#8107]
While looking into #8104 I've noticed the input fields within the Audio, Video, and the various embed blocks have a different width. The one in Video / Audio is larger, not sure if there's a specific reason for this.

<img width="515" alt="screen shot 2018-07-21 at 16 50 49" src="https://user-images.githubusercontent.com/1682452/43037222-a4f63d9a-8d0b-11e8-8297-3121a8d85cce.png">

Considering an URL can be pretty long and translations of the buttons may increase the button width, I'd suggest to increase the space reserved for the input form so the input field can be larger.

I've also noticed the Audio and Video blocks use the `MediaPlaceholder` component, which in turn renders the mini-form for the URL. However, `MediaPlaceholder` inherits several styles from the `Placeholder` component, thus is not really "isolated" and actually depends on another component.

**Comment by hedgefield** [comment]
I would say yes to standardizing this into one default width. All the embed blocks are _basically_ interchangeable anyway.

**Comment by karmatosed** [comment]
Yes let's have them all the same width, the longer one probably is sensible.
