### ISSUE TITLE
Text mangling and inline boundary issues when adjusting formatting

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#8114]
**Describe the bug**
When your cursor is on a word within an inline boundary, you should be able to use formatting buttons and keyboard shortcuts to reformat that word. However, the behaviour in Gutenberg doesn't fully work; sometimes the text gets mangled (typically spaces get removed, see the end of the GIF below), the select area seems to break at the caret's insertion point, etc.

Some of this behaviour also exists in the Classic Editor (although the inline boundaries aren't visible in Classic, so it’s more noticeable in Gutenberg), namely the select boundaries being changed. I haven't been able to reproduce the issue with spaces being removed in Classic.

**To Reproduce**
1. Enter text in a Paragraph block
2. Format a sentence with bold, italics, etc.
3. Click within a word
4. Press a bold/italic/etc button (or fire the appropriate keyboard shortcut)
5. Do that a few times and see your text starts to mangle

**Expected behavior**
You should be able to format/unformat specific words through shortcuts or toolbar buttons without the text being altered.

**Screenshots**

Below, I'm just clicking into an inline boundary and pressing <kbd>Cmd+B</kbd> and <kbd>Cmd+I</kbd> at random.
![kapture 2018-07-22 at 9 02 55](https://user-images.githubusercontent.com/1231306/43045845-012d62c8-8d8e-11e8-9fac-dd4936f90ba2.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.5
 - Browser: Safari 11.1.1
 - Gutenberg: 3.3.0

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8 and Gutenberg 3.5.0 on Firefox 61.0.2 on macOS 10.13.6 and found that pressing `Cmd+B` multiple times for a bold word within a link boundary resulted in that word being selected as a boundary then unbolded then re-attaching to the link boundary and I didn't spot any text mangling other than the loss of a space character after selecting one of the words in the middle and unbolding it. ([1m8s](https://cloudup.com/cUKKgnFZTBx))

Note: it's possible there are differences between browsers and if anyone else happens upon this issue, reporting your experience with a different browser would be a nice-to-have here.

**Comment by chrisvanpatten** [comment]
I'm still able to reproduce this in Safari with 3.5; it seems like at a certain point an empty inline boundary is generated at the caret point, which traps the shortcuts.

**Comment by chrisvanpatten** [comment]
Yep, as expected there's an empty inline boundary being generated:

![web_inspector_ _dev_mindful_org_ _post_php](https://user-images.githubusercontent.com/1231306/44158869-e2247480-a083-11e8-900b-ddbe2a94b51e.png)

```html
<span id="_mce_caret" data-mce-bogus="1" data-mce-type="format-caret"><strong>﻿</strong></span>
```

I can't think of there ever being a case where you'd want an empty inline boundary; it should always attach to the nearest word. Seems potentially like a TinyMCE bug.

**Comment by chrisvanpatten** [comment]
@iseulde I can't reproduce this any more — rich text is feeling SUPER solid. Awesome, awesome work 🙌
