### ISSUE TITLE
Block drop zone has no background color

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#8115]
**Describe the bug**
When I drag an image inside an paragraph, I see a drop-zone text, but can't read the text, because the background color is missing. The background in `editor/components/block-drop-zone` now overrides `packages/components/drop-zone`, maybe introduced in #7640.

**Screenshots**
![drop-file](https://user-images.githubusercontent.com/695201/43045821-04230924-8dc0-11e8-82c4-cc5cb35a578d.gif)

**Comment by designsimply** [comment]
Tested and confirmed with the following steps:

1. Drag an image from another window over the top of a filled-in paragraph block.
1. Try to read the "Drop files to upload" message.
1. Update the paragraph block with a dark background color and a light text color.
1. Repeat steps 1 and 2.

<strong>Result:</strong> the dropzone notice that appears when an image is dragged over the top of a paragraph block is hard to read.

![screen shot 2018-07-25 at wed jul 25 8 40 11 am](https://user-images.githubusercontent.com/1119271/43208240-357f876c-8fe7-11e8-9fb0-b479417de26b.png)

![screen shot 2018-07-25 at wed jul 25 8 40 30 am](https://user-images.githubusercontent.com/1119271/43208242-37f00fb2-8fe7-11e8-8b89-dab0a2b63b32.png)

<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14036&action=edit running WordPress 4.9.7 and Gutenberg 3.3.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

**Comment by Taym95** [comment]
Hello, what should be the best fix, change the background of the DropZone component? example change it to black?

**Comment by Soean** [comment]
The DropZone has a blue background color, but it's overridden by an other component.

**Comment by karmatosed** [comment]
I am reopening this as it was added without a design review. We need to now focus on getting this fixed up, we can but in future let's make sure we do before commits.

@jasmussen is going to be amazing and work on a design solution - thanks for taking this on ❤️
