### ISSUE TITLE
Gutenberg Tip Text innacurate based on state

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#8116]
**Describe the bug**
The second tooltip: "You’ll find more settings for your page and blocks in the sidebar. Click ‘Settings’ to open it." always says open it, even if the settings is open.  If I follow the tip, the setting actually closes.

**To Reproduce**
Go through the tooltips and have the settings open. 

**Expected behavior**
Settings say open or close based on the state of the settings. 

**Screenshots**
<img width="531" alt="screen shot 2018-07-22 at 12 12 39 pm" src="https://user-images.githubusercontent.com/622599/43047746-2ae4491c-8daa-11e8-9a29-0a20caba6622.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version:  ¯\\_(ツ)_/¯

**Additional context**
Running master with the docker setup

**Comment by kristastevens** [comment]
Is it possible to have two tooltips -- one for the "open" state and one for the "closed" state? 

If Settings are open, the tip can read: 

> You’ll find more settings for your page and blocks in the sidebar.

If Settings are closed, the tip can read: 

> Click ‘Settings’ to see options for your page and blocks in the sidebar.

**Comment by afercia** [comment]
Seems to me #8060 already describes the same issue. /Cc @aaronjorbin

**Comment by youknowriad** [comment]
closed by #12911
