### ISSUE TITLE
@wordpress/element should export PureComponent

### ISSUE THREAD

**Issue by Shelob9** [WordPress/gutenberg#8118]
**Is your feature request related to a problem? Please describe.**
I prefer to use functional components, or if needed `React.PureComponent` when Redux/ WordPress/ etc. is managing state and lifecycle. `@wordpress/element` exports `Component` but not `PureComponent`. 

My favorite post on why PureComponent: https://codeburst.io/when-to-use-component-or-purecomponent-a60cfad01a81

**Describe the solution you'd like**
Export `PureComponent`

**Describe alternatives you've considered**
Importing from React, instead of WordPress is fine, but not forward-compatible.

**Comment by youknowriad** [comment]
We do have `wp.compose.pure` which solves the same problem and it works for any kind of React component (including functional ones). I'm closing this for now.
