### ISSUE TITLE
Inverse loading hooks add_meta_boxes and admin_enqueue_scripts

### ISSUE THREAD

**Issue by NenadObradovic** [WordPress/gutenberg#8127]
Hi guys,

Related to this ticket https://github.com/WordPress/gutenberg/issues/8074 , question 5. Example function where **admin_enqueue_scripts** hook doesn't work when Gutenberg plugin is active. 

if ( ! function_exists( 'create_meta_box' ) ) {
	function create_meta_box() {
		global $globalFramework;
		
		foreach ( $globalFramework->mainMetaBoxes->metaBoxes as $key => $box ) {
			if ( is_string( $box->scope ) ) {
				$box->scope = array( $box->scope );
			}
			
			if ( is_array( $box->scope ) && count( $box->scope ) ) {
				foreach ( $box->scope as $screen ) {
					add_meta_box(
						'meta-box-' . $key,
						$box->title,
						'render_meta_box',
						$screen,
						'advanced',
						'high',
						array( 'box' => $box )
					);
				}
			}
		}
		
		add_action( 'admin_enqueue_scripts', 'enqueue_meta_box_styles' );
		add_action( 'admin_enqueue_scripts', 'enqueue_meta_box_scripts' );
	}
	
	add_action( 'add_meta_boxes', 'create_meta_box' );
}

if ( ! function_exists( 'enqueue_meta_box_styles' ) ) {
	function enqueue_meta_box_styles() {
		wp_enqueue_style( 'wp-color-picker' );

		do_action( 'enqueue_meta_box_styles_action' );
	}
}

if ( ! function_exists( 'enqueue_meta_box_scripts' ) ) {
	function enqueue_meta_box_scripts() {
		wp_enqueue_script( 'jquery-ui-datepicker' );
		wp_enqueue_media();
        
		do_action( 'enqueue_meta_box_scripts_action' );
	}
}

In mine case I just modified this part of code

add_action( 'admin_enqueue_scripts', 'enqueue_meta_box_styles' );
add_action( 'admin_enqueue_scripts', 'enqueue_meta_box_scripts' );

with this code below to fix that problem

if ( is_gutenberg_installed() ) {
	enqueue_meta_box_styles();
	enqueue_meta_box_scripts();
} else {
	add_action( 'admin_enqueue_scripts', 'enqueue_meta_box_styles' );
	add_action( 'admin_enqueue_scripts', 'enqueue_meta_box_scripts' );
}

I hope this helps you to reproduce this issue. Sorry for code formatting but I can't force editor to display code in right order. :/

Best regards,
Nenad

**Comment by danielbachhuber** [comment]
Hi @NenadObradovic,

Is this the same as #4929?

**Comment by NenadObradovic** [comment]
Hi Daniel,

Sorry for too late response. Yes, it't the same problem

Best regards,
Nenad

**Comment by danielbachhuber** [comment]
Hey @NenadObradovic,

No worries. Closing in favor of #4929
