### ISSUE TITLE
Additional filter hook inside blocks.php for get_dynamic_block_names

### ISSUE THREAD

**Issue by NenadObradovic** [WordPress/gutenberg#8128]
Hi Guys,

What you think about adding a filter hook inside blocks.php file for this function **get_dynamic_block_names** where we can be able to disable some blocks if we don't need it inside our project. Related to this ticket https://github.com/WordPress/gutenberg/issues/8074 question 3.

Best regards,
Nenad

**Comment by youknowriad** [comment]
There are several existing methods to disable blocks See https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#removing-blocks
