### ISSUE TITLE
Single quote is displayed escaped in post title

### ISSUE THREAD

**Issue by gandalfar** [WordPress/gutenberg#8129]
**Describe the bug**

Post list shows correct: `Neisha in Hamo. Summer of 69' – Bryan Adams in Dan neskončnih sanj – Vlado Kreslin`, but Gutenberg displays: `Neisha in Hamo. Summer of 69&#x27; - Bryan Adams in Dan neskončnih sanj - Vlado Kreslin`

Images:

![screenshot 2018-07-23 10 58 13](https://user-images.githubusercontent.com/13806/43067396-8d69081c-8e67-11e8-9094-900516639804.png)

![screenshot 2018-07-23 10 58 20](https://user-images.githubusercontent.com/13806/43067400-90710762-8e67-11e8-8fc4-1ec146eff97c.png)

Content was originally authored with classic editor. Saving the post again doesn't fix the title. Authoring new one with above text copy-pasted it in Gutenberg `'` correctly escapes it.

 - Browser Chrome 68
 - Gutenberg 3.3
 - Wordpress 4.9.7

**Comment by brandonpayton** [comment]
I am not able to reproduce this with the latest and will close for now. Please let us know if you continue to see the issue, and we can reopen.

Here's what I'm seeing when I use the title mentioned above:
![single-quote-post-title-test](https://user-images.githubusercontent.com/530877/46061217-cb5d4d00-c11a-11e8-8d9f-08a555505018.gif)
