### ISSUE TITLE
How To Add your own editor buttons for the text widget in wp 4.8?

### ISSUE THREAD

**Issue by BackuPs** [WordPress/gutenberg#813]
Hi

Is there a doc or tut somewhere how to add your own button in to the editor for the new text widget?

Can someone point that out to me?

Thank you !
![new-textwidget](https://cloud.githubusercontent.com/assets/6078370/26141849/1a098208-3ade-11e7-88bb-d0d6ca3173ca.png)

**Comment by westonruter** [comment]
This is not relevant to Gutenberg but rather to the visual Text widget: https://core.trac.wordpress.org/ticket/35243

**Comment by jasmussen** [comment]
Thanks Weston. Yep, that's widget specific!

**Comment by BackuPs** [comment]
That thread is about the tinymce editor in the textwidget not about how to extend it with your own buttons

**Comment by coreyworrell** [comment]
@BackuPs 

I had the same question and could not find anything about it. After digging through the source a bit I have found a solution. It plays on the fact that JavaScript passes variables by reference, so I don't think it is the best solution, but it seems to be the only solution as of yet.

You can add a script using `admin_enqueue_scripts` action, and in that script use something like:

```js
;(function() {
    if (typeof jQuery !== 'undefined') {
        jQuery(document).on('wp-before-tinymce-init', function(e, init) {
            init.toolbar1 += ',styleselect'
        })
    }
})()
```

Using that I was able to get the style select button to show for the new text widget editor. It also doesn't seem to interfere with the regular post editor.
