### ISSUE TITLE
Category list doesn't support alphabetical sorting anymore

### ISSUE THREAD

**Issue by gandalfar** [WordPress/gutenberg#8130]
**Describe the bug**

In classical editor, categories were sorted alphabetically by default. This made it easy to find correct one in a list of 165 categories. We have about 50 editors, so most used category across global WP instance is not useful to individual editor.

**Expected behavior**
A way to list of categories in alphabetical order.

**Screenshots**

Before:
![screenshot 2018-07-23 11 12 09](https://user-images.githubusercontent.com/13806/43067983-5eb2bf02-8e69-11e8-90cc-779b0af902e9.png)

After:
![screenshot 2018-07-23 11 12 27](https://user-images.githubusercontent.com/13806/43067989-62298602-8e69-11e8-85da-1650a13cbb10.png)

**Desktop (please complete the following information):**
 - macOS 10.13
 - Chrome 68

**Additional context**
- Gutenberg 3.3 on Wordpress 4.9.7

**Comment by mrleemon** [comment]
#2607

**Comment by gandalfar** [comment]
Thanks @mrleemon closing this in favor of #2607
