### ISSUE TITLE
Multiple block can be in a "isHovered" state

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#8133]
Noticed while investigating on improvements for #8033.

There should be just one block in a "isHovered" state at a time. However, the implementation fails and multiple blocks can be in a "isHovered" state, with the related UI and styles displayed:

![screen shot 2018-07-23 at 13 03 13](https://user-images.githubusercontent.com/1682452/43073751-f7e891d6-8e7a-11e8-9f05-24c6a38193cf.png)

To reproduce:
- hover a block
- hover the "More Options" ellipsis button on the right
- **wait for the tooltip to appear**
- at this point, move the mouse up vertically, to hover the right area of the previous block
- both blocks are now in a "isHovered" state

Same happens with the "block mover" buttons on the left.

Repeating the same steps for all the blocks above, all the blocks become "isHovered".

**Comment by designsimply** [comment]
Tested and confirmed and found that this only happens when moving the mouse _very_ quickly from one control element _after_ the tooltip is triggered to another control element such as the more options, mover, or the block label that appears on hover. ([1m20s](https://cloudup.com/cckwM4S3z2q))

<sup>Tested using WordPress 4.9.7 and Gutenberg 3.3.0 both in Safari 11.1.2 and Firefox 61.0.1 on macOS 10.13.6.</sup>

Related: #2122

**Comment by afercia** [comment]
In my testing it happens also without being very fast when moving the mouse. It seems to always happen when moving the pointer vertically in the area highlighted in the screenshot below:

![hover](https://user-images.githubusercontent.com/1682452/43184344-935319e8-8fe8-11e8-85b8-32e593fb5913.png)

**Comment by designsimply** [comment]
For completeness, may I ask what OS and browser versions you are using for testing?

**Comment by afercia** [comment]
I've tested it on mac, latest Chrome and Firefox.

**Comment by jorgefilipecosta** [comment]
Hi @afercia thank you for reporting this issue. I tried to replicate this issue after all the design changes that happened and I was not able to do it, it was probably solved as a side effect of the design changes. If I missed something feel free to reopen the issue.

**Comment by afercia** [comment]
Hi @jorgefilipecosta yep, can't reproduce any onger. Thanks.
