### ISSUE TITLE
Subhead should support multiple use

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#8140]
Subheads currently have `supports.multiple = false` but I believe this should be `true`.

The main use-case would be an article or page with multiple sections, which need a subhead for each section of content.

**Comment by chrisvanpatten** [comment]
This has a PR now, #8143, for those with labeling powers :)

**Comment by Soean** [comment]
No it was added as a single use block under the title https://github.com/WordPress/gutenberg/pull/2091

Do we really need this Block? It is a paragraph with a class. I don't think many people, including me, really understand when to use this block.

**Comment by chrisvanpatten** [comment]
@Soean I know it was made single use when it was originally added, I'm just saying maybe it should be multi-use so it can be used in content with multiple sections.

But in that case I also think removing it and make it a block style on the paragraph block would be fine.

Is that a `Needs Design Feedback` question?

(Also fwiw I think the idea of the subhead is much more common/understood by folks in journalism/newsrooms.)

**Comment by designsimply** [comment]
Added the `Needs Design Feedback` label to see about getting an answer to @Soean's question about whether the subheading block is really needed. If it is kept, what is its intended use case and what makes a subheading different than using a smaller heading such as h3, h4, h5, or h6?

**Comment by chrisvanpatten** [comment]
> the subhead (also known as subheader, standfirst, rider, kicker, bankhead) in journalism is an introductory or summary line or brief paragraph, located immediately below the headline, and typographically distinct from the body of the article

[via](http://www.atlas101.ca/pm/concepts/lede-and-subhead/)

Whether it should be an h-tag or a paragraph is up to interpretation, although I'm of the opinion that a `<p>` is more correct, semantically. Headings/h-tags should be used to denote the title of a given section or sub-section, whereas the subhead _supports_ and _provides context_ for a heading. You'd really never have a subhead without a heading.

Another way to think about it: if you were generating a table of contents from H-tags (as we do in the Document Outline popover), you wouldn't want the subheads in there, therefore they are more appropriate as `<p>` tags.

**Comment by karmatosed** [comment]
Let's keep it for now as a single use. I have seen it used by people so for now keeping it makes sense. We can always revisit this decision.

**Comment by chrisvanpatten** [comment]
That’s really frustrating. Can you give a bit more context on why it isn’t a good candidate for multiple use @karmatosed?

**Comment by 0aveRyan** [comment]
It seems really confusing to explain to most users what the display/SEO ramifications are of using a Subheading, it's also very hard to see in the UI that it's only available once (and the plugin above presents a concern).

I like @chrisvanpatten of adding it as a block style, I'd also add two other ideas:
* Make the Subheading Block a plugin allowed to register it to the `core/` block namepsace.
* Make an Excerpt Block that allowed users to present `the_excerpt` in-body and bind input value to the sidebar excerpt box.

**Comment by mtias** [comment]
I have to say this block doesn't make a lot of sense to me in its current implementation. If it's mean to be a subtitle it should probably also enforce position — first block of the post. If it's more of a general purpose block, marking it as "use once" seems a bit arbitrary.

It seems like a valuable addition if / when the title can be a full block as well, and you use it in conjunction with a featured image block, an excerpt block, etc.

If that is the case, we might be ok just hiding it for now (not removing it, so it doesn't affect those that are already using it).

**Comment by karmatosed** [comment]
Looping back to this as we are considering removing it in #9308. Thanks everyone for working through this and highlighting the confusion.
