### ISSUE TITLE
Left alignment toggle isn't toggled initially

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#815]
Steps to reproduce:

- Click any text block with left aligned text
- Notice that the left align button isn't toggled
- Click the left align button, it's now toggled and stays toggled even if you click across many blocks

Expected result —  the active alignment of any element is always shown as toggled.

**Comment by aduth** [comment]
For what it's worth, even if the text _appears_ left, it's not _explicitly_ left. The difference between:

```html
<p>Hello world</p>
```

(Where we'd previously not shown any alignment as active)

And:

```html
<p style="text-align: left;">Hello world</p>
```

Unsure if there's really any implication here, except if a theme were to set its default paragraph alignment to something other than `left` (unlikely).

**Comment by jasmussen** [comment]
Oh interesting, so do we actually apply the inline text-align style when the left align button is pressed? Wow, just tried the current WordPress editor again and you're absolutely right — the behavior of the old editor is that it isn't toggled until it's toggled, and when it is the inline style is applied. Hmmmmm. 

Maybe I owe @youknowriad a sincere apology here, and we should revert this? —  it's always good to mimic established patterns. This just seems like a weird one. Wow, even Google Docs does this. This seems super obscure to me.

**Comment by youknowriad** [comment]
Don't worry I was aware of this small difference, and I'm finding that both approaches make sense. I'll revert if you prefer to keep the distinction between the default alignment and the left alignment.

**Comment by jasmussen** [comment]
I do think we should revert, and _I'm sorry_ :)

But this PR had value regardless. When the topic comes up, which it _will_, we can point back to this and say "yes, we explored it". We have cauterized this wound!
