### ISSUE TITLE
Columns Block causes horizontal scrolling in editor

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#8158]
**Describe the bug**
When you reduce the browser width, the columns block causes the whole editor to scroll horizontally.

![gutenberg_columnshorizontalscrolling](https://user-images.githubusercontent.com/2078245/43116168-b83a05ea-8f49-11e8-88d3-38a89048f7b8.gif)

This was tested with TwentySeventeen  with `add_theme_support( 'align-wide' );` added.

**To Reproduce**
1. Edit functions.php in TwentySeventeen
2. Add `add_theme_support( 'align-wide' );` into the `twentyseventeen_setup()` function to allow selection of Wide/Full block layouts
3. Add Columns Block to page
4. Set Columns Block to Wide and 6 columns
5. Add dummy content to each Paragraph Block in the Columns Block
6. Reduce browser width (to approx 1100px or less) and notice horizontal scrolling

**Expected behavior**
Blocks shouldn't cause horizontal scrolling

macOS Sierra 10.12.6
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.3.0

**Comment by designsimply** [comment]
Thank you for your feedback! I am closing this issue in favor including it in #6048 as part of the discussion there.
