### ISSUE TITLE
The problem: When we post in the blog, we get question marks out of the blue in some sentences, either in the beginning or in the final of the sentence.

### ISSUE THREAD

**Issue by SquemDev** [WordPress/gutenberg#8161]
The problem: When we post in the blog, we get question marks out of the blue in some sentences, either in the beginning or in the final of the sentence.

Also the subtitle block give us an error.

Here I attach some examples.

Images of the problem:

https://www.onlytherichters.com/wp-content/uploads/2018/07/captura-de-pantalla-2018-07-18-a-las-09-19-10-copia.jpg

https://www.onlytherichters.com/wp-content/uploads/2018/07/captura-de-pantalla-2018-07-18-a-las-09-18-01-copia.jpg

https://www.onlytherichters.com/wp-content/uploads/2018/07/captura-de-pantalla-2018-07-18-a-las-09-18-47-copia.jpg

https://www.onlytherichters.com/wp-content/uploads/2018/07/captura-de-pantalla-2018-07-18-a-las-09-17-44-copia.jpg

https://www.onlytherichters.com/wp-content/uploads/2018/07/captura-de-pantalla-2018-07-18-a-las-09-19-50-copia.jpg

https://www.onlytherichters.com/wp-content/uploads/2018/07/captura-de-pantalla-2018-07-18-a-las-09-20-08-copia.jpg

¡Many thanks Team!

**Comment by designsimply** [comment]
For the problem with the question marks in the content, it sounds like something that still needs a bit of troubleshooting. Would you mind posting more detail about your site such as versions installed and talk about how you are creating content (i.e. copy and paste, writing directly, editing previously written content, how was the content first added?) in the help forums at https://wordpress.org/support/plugin/gutenberg/ so we can go through it in more detail there first?

> Also the subtitle block give us an error.

I tested the subheading block just now with Gutenberg 3.3 and it worked in my test. May I ask what versions of WordPress and Gutenberg are you testing? Can you also write out your steps to reproduce the problem and copy and paste the exact error message you're seeing?

**Comment by youknowriad** [comment]
ARe you using any custom block that may have left a question mark in the code somewhere? Can you share the HTML (code editor) of your post. Thanks.

**Comment by designsimply** [comment]
I will close this issue but we can still continue the discussion if you are able to provide the additional details asked for such as the HTML from the code editor view for some of the problematic text. Thank you for testing Gutenberg and for asking questions here!
