### ISSUE TITLE
Custom HTML "An unknown error occurred" mixed content error

### ISSUE THREAD

**Issue by Forecaster** [WordPress/gutenberg#8164]
**Describe the bug**
When trying to use the custom HTML block the following is shown:

![image](https://user-images.githubusercontent.com/942137/43128793-2c84f5a2-8f33-11e8-991b-93c5d5bbf619.png)

It appears to be unable to load the code editor because it's trying to load it via http on my https site. So the script is blocked.

![image](https://user-images.githubusercontent.com/942137/43128860-4c82dd92-8f33-11e8-8f8b-d8eaa03f6142.png)

**To Reproduce**
1. Have SSL enabled site
2. Try to use Custom HTML block
3. Observe Mixed Content error hopefully?

**Additional context**
Using Gutenberg 3.3.0
Just updated in fact and unfortunately the issue remains.

Running WordPress 4.9.7 on an ancient Ubuntu Server 12.04.5 box, with a very old PHP version (unfortunately)

**Comment by designsimply** [comment]
Tested and confirmed and noting that I saw a different error in the console:

> Loading failed for the <script> with source “https://cute.wordpress.com/wp-admin/undefined/wp-admin/load-scripts.php?load=wp-codemirror,code-editor,htmlhint,csslint,jshint,htmlhint-kses”.

![screen shot 2018-07-24 at tue jul 24 11 05 16 am](https://user-images.githubusercontent.com/1119271/43154535-e7303b2a-8f31-11e8-9016-daabf3d4a64b.png)
<sup>Tested with WordPress.com and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.6. Note: I used 3.2 for a quick test but it would be nice to have an additional confirmation with a later version. 😊</sup>

**Comment by tofumatt** [comment]
It seems like there is an unrelated bug in latest master with `http` sites; I get `TypeError: potentialIframe is undefined` trying to replicate this on an HTTP site. 😢

**Comment by tofumatt** [comment]
#8211 will help in debugging this but I don't think I'll get to this today so moving the milestone. Sorry 😞

**Comment by Forecaster** [comment]
It's fine. There's a workaround in Chrome. It has the option to allow insecure scripts to load which allows the HTML editor to work until the next session.

![image](https://user-images.githubusercontent.com/942137/43882955-d5c0bae0-9bb1-11e8-8b31-552ec9cb08f5.png)

**Comment by OrdosX** [comment]
I tried what Forecaster said, but now I keep receiving error messages saying "updating failed" and 403 error like this:
![screenshot](https://user-images.githubusercontent.com/26003092/44309955-28216580-a401-11e8-8ae4-a463e95aae4e.jpg)

**Comment by arekkko** [comment]
I have had the same error, during developing webiste on address http://site.com HTML block work's fine. After change domain and activate https - HTML block display error. For me helped set addres in wp-config:

```
define('WP_HOME','https://site.com');
define('WP_SITEURL','https://site.com');
```

**Comment by Forecaster** [comment]
This solution worked for me as well. I didn't know about these statics before.

**Comment by designsimply** [comment]
I re-tested today on an SSL-enabled site, with the proper HTTPS values used for `WP_HOME` and `WP_SITEURL`,  and the Custom HTML block did not display any errors when I tested it. 

Closing as resolved.
