### ISSUE TITLE
Color picker has extra space on the right side. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8167]
**Describe the bug**

The rainbow color picker has a visual bug that shows extra empty space on its right side. 

**To Reproduce**
1. Select a block that has color options (Paragraph, Buttons, etc.)
2. In the Block Settings sidebar, open the rainbow color picker. 

**Screenshots**

<img width="279" alt="screen shot 2018-07-24 at 9 40 17 am" src="https://user-images.githubusercontent.com/1202812/43142141-b209894e-8f25-11e8-891d-d800b6c60c78.png">

<img width="341" alt="screen shot 2018-07-24 at 9 41 25 am" src="https://user-images.githubusercontent.com/1202812/43142168-c2df86d8-8f25-11e8-868f-d5bf4f2ac8b5.png">

---
**Tested using:**

Mac OS 10.13.6, Safari 11.1.2
Mac OS 10.13.6, Chrome 67.0.3396.99

Gutenberg 3.3.0

**Comment by chrisvanpatten** [comment]
Fixed by #8095, which will land with 3.4.

**Comment by kjellr** [comment]
Great. I'll close this then. Thanks!
