### ISSUE TITLE
Color options are missing top/bottom border in the settings sidebar.

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8172]
**Describe the bug**

Color options in the settings sidebar are missing the single-pixel divider lines that other collapsible settings panels have:

<img width="279" alt="screen shot 2018-07-24 at 10 55 26 am" src="https://user-images.githubusercontent.com/1202812/43147461-1517c856-8f31-11e8-95da-4aadd3aa5a1f.png">

<img width="278" alt="screen shot 2018-07-24 at 10 50 06 am" src="https://user-images.githubusercontent.com/1202812/43147466-192b486e-8f31-11e8-9ffe-59fcc2f25e33.png">
 
(I'm showing the Button block here, but this issue persists on other blocks that have color options as well). 

Compare this to the multiple options inside the Document settings panel: 

<img width="280" alt="screen shot 2018-07-24 at 11 10 17 am" src="https://user-images.githubusercontent.com/1202812/43147909-2981be72-8f32-11e8-98aa-3349d9c33f9b.png">

It's possible this is intentional, to denote some level of hierarchy in the button settings. But seeing as these sections behave and look identically to other settings that do have borders, I suggest we include them. 

**Tested in:**
Mac OS 10.13.6, Safari 11.1.2, using Gutenberg 3.3.0
Mac OS 10.13.6, Chrome 67.0.3396.99, using Gutenberg 3.3.0

**Comment by chrisvanpatten** [comment]
This actually applies to all custom panels in the Block Inspector; it's a duplicate of #7686.

**Comment by kjellr** [comment]
Thanks @chrisvanpatten — I'll close this in favor of that one. 👍
