### ISSUE TITLE
Color picker panels in the sidebar are missing bottom padding.

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8173]
**Describe the bug**
The "Clear" link bumps right up against the bottom of the next item in the sidebar:

<img width="280" alt="screen shot 2018-07-24 at 11 14 16 am" src="https://user-images.githubusercontent.com/1202812/43148219-da64803a-8f32-11e8-8aa5-d2f5cb90c248.png">

This section should have `16px` of padding on the bottom, to match the display of other similar expandable panels:

<img width="280" alt="screen shot 2018-07-24 at 11 18 04 am" src="https://user-images.githubusercontent.com/1202812/43148477-5da3d130-8f33-11e8-878d-2dc65534dd4b.png">

**To Reproduce**
1. Open a block with color controls (Buttons, Paragraphs)
2. Open the settings sidebar, and expand one of the color-related panels. 
3. Note the issue described above. 

**Tested in**
Mac OS 10.13.6, Safari 11.1.2
Mac OS 10.13.6, Chrome 67.0.3396.99
Gutenberg 3.3.0

**Comment by kjellr** [comment]
Potentially related: #8174

**Comment by Soean** [comment]
![bildschirmfoto 2018-08-21 um 18 10 14](https://user-images.githubusercontent.com/695201/44414264-a4d15280-a56d-11e8-9d2d-22a4f0452257.png)

Tested in Master, seems to be fixed. 
Please reopen if you can still reproduce it.
