### ISSUE TITLE
Bottom padding for accordion panels is inconsistent between the document and blocks tabs

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8174]
In the settings sidebar, the bottom padding on individual accordion panels is inconsistent. In the Document tab, there appears to be `16px` of padding below each element, whereas in the Blocks sidebar, there appears to be ~`30px` instead:

![artboard](https://user-images.githubusercontent.com/1202812/43149332-3361fa44-8f35-11e8-89cd-893ba26dd1b9.png)

I'd suggest we standardize this. `16px` seems fine and will be a more efficient use of space.

**Comment by Soean** [comment]
This should work: 
```
.edit-post-block-sidebar__panel .components-panel__body > div:last-child {
	margin-bottom: 0;
}
```
