### ISSUE TITLE
Deprecate old Speakerdeck block name

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#8177]
**Describe the bug**
The name of `core-embed/speaker` was changed to `core-embed/speakerdeck` in #7851. We should add a deprecation, see https://github.com/WordPress/gutenberg/pull/7851#issuecomment-406936267.

**Comment by ntwb** [comment]
I've reverted #7851 for now in #8277 to get 3.4 out without this holding the release up

Will reimplement with the correct deprecations in a follow up PR, as such closing this PR and removing it from the 3.4 milestone.
