### ISSUE TITLE
Inconsistent "Reset" controls in the block settings sidebar.  

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8179]
The text size and color controls in the block sidebar have buttons/links to "reset" to the default settings, but their treatment and labels are inconsistent. You can see this most evidently in the Paragraph block sidebar:

<img width="280" alt="screen shot 2018-07-24 at 2 34 24 pm" src="https://user-images.githubusercontent.com/1202812/43159083-54e653f8-8f4f-11e8-924a-99d83f5e8d3e.png">

I'd suggest we change all to use text links, and go with "Reset", since that seems like a clear label for both. I'd also suggest that these links don't need to appear if settings haven't been changed yet.

**Comment by SuperGeniusZeb** [comment]
>I'd also suggest that these links don't need to appear if settings haven't been changed yet.
The buttons could also be visible, but disabled when there is nothing to reset.

**Comment by mtias** [comment]
Tracking in #27331.
