### ISSUE TITLE
Preview button behavior

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#818]
Inspired by #659, let's discuss what the preview button should do.

Very very early and casual feedback suggested to me that a split screen preview feature was something people desired. So here's a mockup.

![preview](https://cloud.githubusercontent.com/assets/1204802/26147071/ae0b98c4-3af2-11e7-92bb-65819119ecf5.png)

![preview splitscreen](https://cloud.githubusercontent.com/assets/1204802/26147109/c9d5933e-3af2-11e7-8de6-76ce04006985.png)

In this draft flow, we treat the preview button as part of a "toggle group", which means toggling it untoggles Post Settings. The two buttons were designed like this from the start, which is why they have labels, and are separated from the others. 

There's a "Open in external window" button on the preview toolbar.

Resizing the preview window is essentially a way to test the responsive look of the post also. 

This is one flow we can explore. Another option is to simply open the preview in a new tab when you click the editor bar button, which is the current behavior. Though in that case we'd probably want to move the button out of of the "toggle group" separator.

**Comment by mtias** [comment]
Split screen is not great because we won't have the ability to sync them on edits—the "preview" will have a delay to reload. I think we should keep the current behaviour of wp-admin for v1.

**Comment by westonruter** [comment]
As noted on #659, anything related to preview I think is an area for collaboration with Customizer, namely in applying post data and post meta to the frontend for previewing.

**Comment by jasmussen** [comment]
As a quick minimal followup, in an interface where the Preview button isn't a toggle, but rather opens in a separate window, we could rearrange the top buttons ever so slightly:

![screen shot 2017-05-17 at 18 26 27](https://cloud.githubusercontent.com/assets/1204802/26164901/6ca7da00-3b2e-11e7-8377-7c0ca5c12af5.png)

Oh, and added a label there, which I think Mel will appreciate ;)

**Comment by karmatosed** [comment]
I really like the last mockup @jasmussen.
