### ISSUE TITLE
Tips: The tooltip didn't disappear when other parts of the editor are engaged

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#8181]
When going to edit a post in Gutenberg for the first time, the tooltip appears - great. However, the tooltip didn't disappear when I clicked on a different part of the editor (featured image). This caused the tooltip to be disconnected from it's purpose while it blocked other content visually.

![g-tooltips](https://user-images.githubusercontent.com/617986/43161991-8c27d51e-8f3e-11e8-826b-6263567b65d8.gif)

**Solution:** The tooltip should disappear if something else is clicked.

**Comment by arunsathiya** [comment]
I was about to report the same issue - the overlap when featured image is engaged - and caught this issue. 👍🏽 

Can confirm this is still an issue with Gutenberg 4.3.0.
