### ISSUE TITLE
Mark all (Ctrl/Cmd+A) is unpredictable across various browsers

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#8185]
I'll be using the `^` to symbolise the Ctrl/Cmd button

This applies to **Chrome**, **Internet Explorer 11** and **Edge:**

When clicking inside a block, ^A will first mark all the content inside that block, hitting the combination again will mark all content in the editor.

The "Mark only this block" only works the first time, every other attempt at using ^A will always mark all content in the editor.

I expect ^A to first check if the whole block is marked, if it is, mark all content in the editor.
If not all content in a block is marked, mark all content in a block.
I mention the second bit there, as you may have marked a part of a string manually, before deciding you want to mark everything in the block, so just testing for any marked content at all for the first scenario wouldn't help much.

Trickle down version information:
Gutenberg 3.3.0
Chrome 67.0.3396.99
Internet Explorer 11.112.17134.0
Edge 42.17134.1.0
Windows 10

**Firefox** behaves slightly different:

You need to double-tab ^AA to mark all content, you can't do ^A ^A (so even if all content in a block is selected, you need to double-tap to mark all content in the editor).

Once you've double-tapped, if you un-mark the content by selecting elsewhere within the same block, any use of ^A will mark all content in the editor.

If you click into another block, the status goes back, and you will again only mark the content in a singular block with ^A, and will need a double-tap of ^AA to mark all content.

Gutenberg 3.3.0
Firefox 61.0.1
Windows 10

**Comment by jorgefilipecosta** [comment]
Hi @Clorith thank you for testing and reporting this issue. We already have an issue referencing this problem https://github.com/WordPress/gutenberg/issues/7445, I will close this one in favor of that one given that it was created first.
This issue will hopefully get fixed when https://github.com/WordPress/gutenberg/pull/8180 is merged.
