### ISSUE TITLE
Typing a single quote marks opens browser search in Firefox responsive mode

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8191]
So here's a super fun potentially super edge-case issue I keeping running into:

![2018-07-20 01 24 03](https://user-images.githubusercontent.com/376315/42976891-27a9dc3e-8bbc-11e8-8e4f-a514859312b2.gif)

Basically, any time I type a single quotation mark (in dumb quotes, so '), it opens up my browser's search functionality. This makes it tricky to type a post, since I get stuck every time I try to use a contraction (let's it's I'm etc).

Weird, right? It seems to be happening only in Firefox, and only when I'm in responsive mode. I'm not exactly sure what's triggering it, but I can't seem to replicate it on my Android tablet (where I use Firefox), just in my browser... so it's possible it may be so edge case as to not be important. 😄 Figured I'd file it in case it affects other things as well.

**Comment by markjaquith** [comment]
This also happens here on GitHub. 😄

Here's the Firefox bug for the issue. Unfortunately, it seems to have no traction. https://bugzilla.mozilla.org/show_bug.cgi?id=1317323

Since it only happens in Firefox RDM and isn't unique to Gutenberg, I recommend we take no action on this.

**Comment by sarahmonster** [comment]
Ah lovely, that makes way more sense then.
