### ISSUE TITLE
Don't add any files to front end's <head>

### ISSUE THREAD

**Issue by radogado** [WordPress/gutenberg#8195]
**Is your feature request related to a problem? Please describe.**
Just noticed that Gutenberg adds a CSS file (gutenberg/build/core-blocks/style.css) to the front end, breaking my site's optimisation.

**Describe the solution you'd like**
Please provide an option to not add that file to "head". Thanks.

**Comment by designsimply** [comment]
Tested and confirmed that `gutenberg/build/core-blocks/style.css` is loaded on the front-end with Gutenberg:

![screen shot 2018-07-25 at wed jul 25 12 08 23 pm](https://user-images.githubusercontent.com/1119271/43219149-c18b8fe6-9003-11e8-9671-d757e7b5f725.png)
<sup>Seen at http://alittletestblog.com/2018/07/25/summer-night-riverside/ running WordPress 4.9.7 and Gutenberg 3.3.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

I think the solution for this will be to add theme support to replace such styles. I am not sure how to do that, and hopefully someone will chime in with a more technical answer!

**Comment by radogado** [comment]
@chrisvanpatten thanks for the quick response. I added only

`wp_dequeue_style( 'wp-core-blocks' );`

to my theme styles function and it works.

Cheers!
