### ISSUE TITLE
Colour picker: Toggle isn't properly aligned

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8197]
The colour picker component has a little toggle thing, to switch between different colour modes (HSL, RGB, hex). It's not aligned properly with the input:

Firefox:
<img width="233" alt="screenshot 2018-07-25 13 37 49" src="https://user-images.githubusercontent.com/376315/43201366-34a7aee0-9010-11e8-97b7-fad7c389a90a.png">

Chrome:
<img width="239" alt="screenshot 2018-07-25 13 41 15" src="https://user-images.githubusercontent.com/376315/43201510-9d8c5a28-9010-11e8-9540-8f138c1fa095.png">

This kinda works when it's spaced a little away from the input, but still feels a bit awkward:

![2018-07-25 13 48 16](https://user-images.githubusercontent.com/376315/43201815-79011346-9011-11e8-877b-4c73b489b44b.gif)

(From [React Color](https://casesandberg.github.io/react-color/), not sure if that's the source here!)

I'd suggest either moving it up:
<img width="291" alt="screenshot 2018-07-25 13 52 16" src="https://user-images.githubusercontent.com/376315/43202019-257e098a-9012-11e8-80e4-d90082f67888.png">

...or moving it over:
<img width="260" alt="screenshot 2018-07-25 13 52 50" src="https://user-images.githubusercontent.com/376315/43202021-25be1aa2-9012-11e8-849c-1197c39d78df.png">

**Comment by youknowriad** [comment]
We're using a different color picker now but I believe there are still some styling issues.

**Comment by skorasaurus** [comment]
This was resolved in https://github.com/WordPress/gutenberg/pull/19607 and can be closed; I checked in gutenberg 9.2, looks good.

**Comment by annezazu** [comment]
Wooohoo! Thank you for following up on this @skorasaurus. Closing this out.
