### ISSUE TITLE
Editing the table columns width

### ISSUE THREAD

**Issue by wvdz** [WordPress/gutenberg#8198]
Seems you can manually change the width of table columns in the editor. But this isn't reflected on the frond end. The width of the columns are stuck. The have a width you can not change in the editor. For example, one column has style="width:35px" in the td tag. Whatever I do, it doesn't change.

1. On a random post, add the Table block.
2. Throw in some rows and columns and add content to them.
3. Publish the post.
4. Edit the column width by hovering over with your mouse and dragging the column border.
5. Update the post. In my case, you will not see any changes to the width of the columns.

My expection is that when you can alter the width of the columns in the editor, this is reflected on the front end.

Screenshots

Table blocks in the editor: 
![gutenberg-table-column-width](https://user-images.githubusercontent.com/3425128/43203653-19ebfbe2-901f-11e8-80be-042085b90e31.png)

Table blocks on the website:
![gutenberg-table-column-width-front](https://user-images.githubusercontent.com/3425128/43203652-19d4698c-901f-11e8-9db0-dafaf03e8c35.jpg)

Table block HTML:
![gutenberg-table-width-html](https://user-images.githubusercontent.com/3425128/43203650-19bc3f88-901f-11e8-970f-b67d19c632af.png)

Specs
- MacOS 10.13.6 (latest release)
- Safari 11.1.2 (latest release) and Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Gutenberg version: 3.3.0

**Comment by danielbachhuber** [comment]
Thanks for the report, @wvdz.

The Tables Block implementation is getting a complete re-think in #6923. Closing in favor of that issue.

**Comment by wvdz** [comment]
Ok, succes with that!
