### ISSUE TITLE
Add Additional Sections & Scrolling to Insertion Block

### ISSUE THREAD

**Issue by timmyc** [WordPress/gutenberg#82]
The insertion block design shows the notion of having "Sections" within each tab of the dialog:

<img width="294" alt="insert_-_cloudup" src="https://cloud.githubusercontent.com/assets/22080/23046929/66bea8da-f461-11e6-9c3b-1f46dba0dc7b.png">

This task is to add support for sections within the tabs, and populate with some example block icons.  One section that could be added at this time would be for embeds and could display a list of popular services ( facebook, twitter, youtube, WordPress blog post etc ).

**Comment by jasmussen** [comment]
Here's the latest mockup:

https://github.com/WordPress/gutenberg/blob/5e50c86e0c5c53cd2245e92537e8931cdc0cb317/mockups/Insert.png

See also <a href="https://github.com/WordPress/gutenberg/issues/81#issuecomment-280595555">this comment</a>.

For some background on how this could work:

- As you are writing, typing typing typing, the plus button is below the last paragraph. As you make a linebreak, the plus moves to the side, see #72. 
- When on a new line, the inserter can be invoked by pressing the shortcut key `/`. See #24 and #71. 
- When the inserter is invoked, you can immediately use the arrow keys to select a block, and use Enter to insert that block. OR: you could start typing, at which point you'd start searching through the blocks. 

So these flows should work:

- Type text, press enter for new line, type /, use arrow keys to select image, press enter, image is inserted
- Click plus with mouse, start typing `ima` and `Image` would quickly be filtered as the top result, press Enter, image is inserted

**Comment by karmatosed** [comment]
This is making me very excited about how the interface will feel magic. Having it adapt and know what you want to use, to predict - that's going to be super powerful to users.

**Comment by jasmussen** [comment]
Closing this in favor of #34
