### ISSUE TITLE
Encoding issue: <br> becomes \\u003cbr/\\u003

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#8200]
**Describe the bug**
I have:
```
edit: function(){
...
	[...]
	el('div', {},
		el(wp.editor.RichText, {
			tagName: 'h2',
			format: 'string',
			value: props.attributes.content,
			onChange: function(content){
				props.setAttributes({ content: content });
			},
		}),
	),
	[...]
...
},
save: function(){
	return null;
},
```
And it's saving Shift + Enter as `\\u003cbr/\\u003` which I don't like because I can't do `get_posts()` and then `wp_insert_post()` because what used to be `<br>` is displayed as `u003cbr/u003`.

**To Reproduce**
1. In `wp.editor.RichText` enter `Shift + Enter` and it will be saved as `\\u003cbr/\\u003`.
2. Try to export this post.
3. Try to import this post.
4. See that `<br>` is no longer `<br>` but `u003cbr/u003`.

**Expected behavior**
Exporting `post_content` and importing via `wp_insert_post()` shouldn't require any processing.

**Additional context**
- Gutenberg v3.3.0

**Comment by iseulde** [comment]
Is this still an issue? The RichText value has changed since this has been reported.

**Comment by iseulde** [comment]
No feedback on this one and cannot reproduce.

**Comment by manake** [comment]
Yes, it's still an issue, I opened another ticket with a brand-new test on WordPress 5.1 this time: https://github.com/WordPress/gutenberg/issues/14068
