### ISSUE TITLE
Left/Right aligning a cover image block hides the block toolbar on mobile.

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8203]
**Describe the bug**

At smaller screen breakpoints, setting a Cover Image block to align to the left/right completely hides the Block toolbar. This makes it impossible to change the alignment back to any other setting, to change the text alignment, or to change the image. 

**To Reproduce**
1. Insert a cover image block.
2. Choose left or right alignment from the block toolbar.
3. The block toolbar will disappear. 

This happens whether or not you insert an image first. 

**Expected behavior**

I expected to still have access to the block toolbar.

**Screenshots**

![cover-image-mobile](https://user-images.githubusercontent.com/1202812/43212327-a956c0f0-9001-11e8-8fbc-11e727bb86dd.gif)

**Tested in**
iOS 11.4.1, Safari
Mac OS 10.13.6, Safari 11.1.2
Mac OS 10.13.6, Chrome 67.0.3396.99
Gutenberg 3.3.0

**Comment by jorgefilipecosta** [comment]
Hi @kjellr thank you for reporting this problem. With the recent changes to the cover block, I'm not being able to reproduce this issue anymore.
If I'm missing something feel free to reopen the issue.
