### ISSUE TITLE
Create warning user experience around editing Gutenberg post in Classic Editor

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#8213]
If a user opens a Gutenberg post in the Classic Editor, there are some ways TinyMCE can unexpectedly modify the contents of their post (e.g. #4672).

Because editing Gutenberg posts in the Classic Editor isn't formally supported, we should introduce some user experience around this scenario. Essentially, the user should be alerted to the fact that editing a Gutenberg post in the Classic Editor could cause problems, and that they might want to revert to an earlier revision.

While it's unlikely this will be ready by the time of `Try Callout`, it'd be great if this could be produced sooner rather than later. It may eventually make sense to commit this to a WordPress 4.9.9 too.

Previously https://github.com/WordPress/gutenberg/issues/4672#issuecomment-407058041

**Comment by pento** [comment]
I'm nudging this into the Try milestone, I think it'd be a good safety measure to have. I'll dig into it tomorrow, and see if we can get somewhere. (I'm not calling dibs, in case someone is inspired to tackle this before me.) 🙂

**Comment by chrisvanpatten** [comment]
Just wanted to paste @karmatosed's suggestion from the #core-editor meeting yesterday, which I thought sounded like a good starting point:

> Warning wise let’s just have one in classic editor, use post locking modal message and point to revisions. No need to disable visual.

If revisions are disabled it's slightly more complicated, but maybe that just means a stronger "hey seriously pal, think twice before doing this" message?

Just as a starting place on lingo:

> This post was previously edited in Gutenberg. While you can continue and edit in the Classic Editor, you may lose data or formatting from the Gutenberg version of this page.
> 
> To continue anyway, click the "Edit in Classic Editor" button. You can also find an earlier revision to edit by clicking the "Browse Revisions" button. Otherwise, press "Edit in Gutenberg" to keep this post in Gutenberg.

Alternate version of the last sentence if Revisions are disabled:

> Because your site does not have revisions enabled [maybe link to Revisions docs?], you may not be able to restore an earlier version of your content.
> 
> To continue anyway, click the "Edit in Classic Editor" button. Otherwise, press "Edit in Gutenberg" to continue to Gutenberg, preserving your content and formatting.

Just a starting point — don't think these would work as final text!

**Comment by Clorith** [comment]
I'd like to drop in my concerns here as well:

There's a presumption that users will access the classic editor while Gutenberg is active.
This is more likely than not, not going to be the case. If something broke in Gutenberg they are more likely to deactivate the plugin, meaning anything we put into Gutenberg to pop up in the classic editor is moot.

There is also the likelihood that users may activate/deactivate it to test it back and forth without ever realizing there's an option to "Classic Editor" option, many users are more likely to click the title to go into the editor, not hover to get the action row (will they even know what that option on the action row means?).

**Comment by danielbachhuber** [comment]
> This is more likely than not, not going to be the case. If something broke in Gutenberg they are more likely to deactivate the plugin, meaning anything we put into Gutenberg to pop up in the classic editor is moot.

Right, which is why we'd probably want to work this into a 4.9.9.

**Comment by Clorith** [comment]
This worries me a little then. Bringing around a new core release to sort this out is an added time delay in which we are not informing users that they run the risk of manipulating their content in a bad way, and we knew this before encouraging them to try things out.

**Comment by celloexpressions** [comment]
I am also concerned about the implications of this problem.

There is an assumption that many users will “try out the block editor, find that it doesn’t quite work for them yet, and switch back to the classic editor.” However, it is generally not possible to convert content from the Gutenberg block-based format back to the “classic editor” format. 

At a minimum, we need a reactive warning to users as to what has happened when their content is, essentially, lost following Gutenberg testing. This needs to be in core, and in the meantime core should not actively encourage testing a plugin that could cause functional problems with content on live sites without warning when the plugin is deactivated.

**Comment by Clorith** [comment]
Honestly, I am of the opinion this **needs** to be baked into core so that block content can receive proper warnings even without the plugin, and I would like to see this be a blocker that delays the release (someone has to say it).

There is no way we can know about these risks, a week in advance, and plan a reaction to it in a later core release. There is a _lot_ hinging on this encounter with Gutenberg being a good one for the users.
