### ISSUE TITLE
Image size control don't display proper labels for sizes.

### ISSUE THREAD

**Issue by bartekcholewa** [WordPress/gutenberg#8219]
**Describe the bug**
`Image size` control don't use `image_size_names_choose` filter for labels in block controls, just some made up names.

**To Reproduce**
1. Register a new image size.
2. Add proper labels to `image_size_names_choose`
3. Go to page edit with Gutenberg(definitely not core worthy "plugin"), add/edit image block and in `Image Size` control you will find some made up labels.

**Expected behavior**
See properly filtered image size labels.

**Comment by dillix** [comment]
I'm confirm this issue. Will it be fixed?
