### ISSUE TITLE
Can't click on text next to hovering toolbar

### ISSUE THREAD

**Issue by nb** [WordPress/gutenberg#822]
I was editing a block and wanted to focus on the block above. However, I couldn't click on the text right next to the my current block's toolbar, even though the text from was from the block above. Here’s what I tried:

![out](https://cloud.githubusercontent.com/assets/27954/26155127/cb68d134-3b1a-11e7-85f6-1246395982f0.gif)

I expected that clicking on “from the above” would focus on the block that contains it, but nothing happens.

**Comment by jasmussen** [comment]
Thanks for the report! But it's a duplicate of #763 ;) 

I'm copying the good image here though, and pasting on the other ticket.

**Comment by nb** [comment]
Argh, I thought I had looked through all issues. Sorry for the noise, I hope at least the gif is helpful :)

**Comment by jasmussen** [comment]
No worries! Gifs are great!
