### ISSUE TITLE
NUX tips: clicking on the area below the blocks makes the second tip appear

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#8220]
On current master:

- clear your browser's local storage  Gutenberg entry
- create a new post
- the first tooltip appears
- click on the area below the default block

![screen shot 2018-07-26 at 00 27 02](https://user-images.githubusercontent.com/1682452/43250330-66844498-90bd-11e8-8703-51eb81bf5526.png)

- the second tip appears:

![screen shot 2018-07-26 at 00 28 23](https://user-images.githubusercontent.com/1682452/43250355-7411da8a-90bd-11e8-82ad-59bcb8f4ba9c.png)

Seems to me this didn't happen in previous versions and I'd tend to think it's not the expected behavior as clicking outside the tip shouldn't do anything. Also, clicking on other blank areas doesn't do anything.

**Comment by aduth** [comment]
Related: #7447

This was meant to have been fixed in #7541

cc @noisysocks

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/pull/9223 makes this no longer a problem.
