### ISSUE TITLE
Make 'add a block' popup full width/wider

### ISSUE THREAD

**Issue by vincentariens** [WordPress/gutenberg#8221]
Hi,

From a UX perspective I think it is way better to make the add a block pop up full width. At the moment it is a very narrow and small popup with lots of options to choose from. I think it is better to us the available width since it is not used anyway;

**at the moment:**

![schermafdruk 2018-07-26 10 40 17](https://user-images.githubusercontent.com/41729631/43251671-d3147b3e-90c0-11e8-8448-67c9666659a4.png)

**Suggestion:**

![gutenberg](https://user-images.githubusercontent.com/41729631/43252134-12dd0af0-90c2-11e8-9252-3b27ad8afefc.png)

**Comment by chrisvanpatten** [comment]
Thanks for the suggestion @vincentariens! This is currently being discussed in #7141; you may want to comment over there as well.

**Comment by designsimply** [comment]
Thank you for the reference to #7141 @chrisvanpatten! And thank you for the feedback @vincentariens  🙂 I'm closing this issue in favor of #7141 and a link to this issue will already appear there since it was linked here.

**Comment by vincentariens** [comment]
Perfect! I discussed it further in #7141
