### ISSUE TITLE
Video or Audio Blocks - would be good to have no download as an option

### ISSUE THREAD

**Issue by aileenf** [WordPress/gutenberg#8222]
I've been trying out the Gutenberg Video and Audio blocks - I think they're working really nicely and the settings are good too.  But I see that the blocks appear automatically with the Download facility as standard.  

Since the HTML5 audio and video tags have a "nodownload" option, it would be good to see this included in the settings, along with autoplay, loop, etc. 

An addtional option in the settings box for Allow download  yes/no (or off/on) would be great.

A "no" to this would translate to adding controlsList="nodownload" to the audio or video tag.

Sorry if this has already been considered or raised - I did search but couldn't find it anywhere.

Thanks

**Comment by Soean** [comment]
Thanks for your feature request. 
This feature is experimental and only supported in Chrome and Opera, see: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList

So we should not implement it yet, maybe we can consider it again in 1-2 years.

**Comment by designsimply** [comment]
Thank you for your feedback! Because the answer is that the nodownload option isn't consistently available in all major browsers, I am closing this issue and we can re-visit in the future as @Soean suggested.

**Comment by EbonyyM** [comment]
I have a wordpress website and have uploaded my own videos and audio files. I have been able to disable the download on my video files, but I feel very strongly about being able to disable the download of audio files too. I am a musician and this website is part of a big project for my final year at uni, and I need to upload the audio files as evidence of my work, so if the files are downloadable by anyone (and they have been downloaded quite a few times in such a short time frame of them being on the website), there are concerns raised for me such as why would someone be downloading audio files of my rehearsals (it's not a final product of a song) and what is their intention with the download? I would prefer it to be accessible but not usable as a download for copyright reasons.

**Comment by designsimply** [comment]
@EbonyyM I think we can re-open to consider the `nodownload` option for HTML5 audio and video but with a caveat to say that there is no guarantee and there are _always_ ways around such methods and sometimes developers do not want to take extra time to try to block something which can be easily worked around (such as I know is the case with images but I am less familiar with audio and video). Even with an option such as `nodownload` there is a risk in posting content online where it can be retrieved by anyone if they work hard enough to do that.

**Comment by Soean** [comment]
It's an experimental feature, no standard and only supported in the chromium engine. I don't think we should support this feature at the moment.

**Comment by mtias** [comment]
Closing for now.

**Comment by jamiepalatnik** [comment]
Just wanted to add a +1 for this feature. It would be great to have the option to hide the download link, even if it were technically still possible to download the file.
