### ISSUE TITLE
2/1 gallery renderes completely wrong in Internet Explorer 11

### ISSUE THREAD

**Issue by oldrup** [WordPress/gutenberg#8238]
Using Gutenberg plugin 3.3.0  I've created some posts with galleries with three images, two columns.

In Chrome, Firefox and Edge they are rendered just fine.

In IE 11, latest Win10 release, all the thumbnails seems to be overlayed and in full size.

Link: https://dev.oldrup.dk/wifi-hotspot-via-mobiltelefonen/

Correct rendering in Edge
![image](https://user-images.githubusercontent.com/17141205/43284131-2993c19a-911b-11e8-8f0e-103e6fb6aade.png)

Horrible rendering in IE
![image](https://user-images.githubusercontent.com/17141205/43284158-41401b36-911b-11e8-9469-39c4c7807774.png)

Please let me know, if I can do anything else to troubleshoot this issue. I've still got 5-8% IE users.

**Comment by oldrup** [comment]
Sorry! The "Crop Images" toggle seems to fix the rendering in IE... 

![image](https://user-images.githubusercontent.com/17141205/43286151-6ad6bc42-9121-11e8-9fa2-3ae0d3451343.png)

My bad.

**Comment by jduartedj** [comment]
Just experienced the same problem as @oldrup.
Unfortunatly My gallery doesn't look good if I use cropped images. 

This is definitively an issue and should remain **open**.

![image](https://user-images.githubusercontent.com/350819/43931195-39c4f7a8-9c35-11e8-914d-75c062a586aa.png)

**VS**

![image](https://user-images.githubusercontent.com/350819/43931210-4a38a2ba-9c35-11e8-8288-a891adea100f.png)

**Comment by aduth** [comment]
Based on timing and described resolution, I'm expecting this to have been fixed by #9622 .

Let me know if it is still a problem, and the issue can be reopened.
