### ISSUE TITLE
Local .mp4 video, rendered full width, not limited to blog column, in popular themes.

### ISSUE THREAD

**Issue by oldrup** [WordPress/gutenberg#8239]
Well I don't know how to describe it better.. Here's a sceenshot

![image](https://user-images.githubusercontent.com/17141205/43284901-99257182-911d-11e8-9a75-dd9806f3af5a.png)

That's in all browsers I've tested.

Same thing in GeneratePress and Astra themes - both popular ones from WordPress.org.

In Twenty Seventeen however, it looks fine :)

![image](https://user-images.githubusercontent.com/17141205/43285031-06015d48-911e-11e8-8418-038a91db0a38.png)

Where to point my greasy finger?!

**Comment by oldrup** [comment]
Forgot the link: https://dev.oldrup.dk/clipchamp/

**Comment by jorgefilipecosta** [comment]
Hi @oldrup thank you for reporting this issue. I tried to replicate the issue in some of the default theme and It was not possible to do it. I guess probably the fix should be applied to the themes where the problem is happening.
