### ISSUE TITLE
"Updating Failed"

### ISSUE THREAD

**Issue by KensonPlays** [WordPress/gutenberg#8241]
**Describe the bug**
Similar to this issue: https://github.com/WordPress/gutenberg/issues/2565

I am getting 'Updating failed' and I cannot add/save any pages created with Gutenberg. I am not running on a VPS though, I am running on HawkHost, which have been very good to me so far. I do not have CloudFlare installed, nor any CDN. Just the host.

I do have a forum, Xenforo, installed with a bridge plugin to bridge WP and Xenforo together, and I've confirmed it isn't Xenforo or Xpress (the plugin)'s end.

**To Reproduce**
1. Go to edit/create a page.
2. Edit page.
3. Click 'Save' or 'Publish'
4. "Updating failed" 
5. Doesn't update.

**Expected behavior**
Expect it to save perfectly fine.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version: 68.0.3440.68 (Official Build) beta (64-bit)

**Smartphone (please complete the following information):**
N/A. Don't edit content on my phone.

**Additional context**
Gutenberg v 3.3.0

**Comment by mrleemon** [comment]
I'm on Hawkhost too and some weeks ago I had some similar problems. Can you try going to the ModSecurity section on your host's cPanel and disable it to determine if this is the culprit?

**Comment by KensonPlays** [comment]
ModSecurity has been disabled for a couple weeks now. So is Imunify360.

**Comment by pento** [comment]
@KensonPlays: Do you have any other plugins installed? In particular, any sort of security plugins?

Also, in Chrome, could you please open Gutenberg, then open browser the Developer Tools, visit the Network tab, then try to save the post? When the "Updating failed" message appears in your browser, you'll see an entry in the Network tab with a name something like `/wp/v2/posts/12345`, it should be in red, showing that there was an error. Click on that entry, then Headers, then please copy everything in the "Response Headers" section to this issue.

**Comment by designsimply** [comment]
I am closing this issue for now. If you are still having trouble with "updating failed" notices for all posts/pages and are able to find the information asked for about the API call in the Network tab, we can check to see if that helps us get closer to helping you with next steps once you post that information.

Thank you for testing Gutenberg and I hope to hear back from you as this case seems like a tricky issue that would be nice to learn more about.
